### ISSUE TITLE
alternate url (via CYPRESS_BINARY_VERSION) doesn't work with http links (only https)

### ISSUE THREAD

**Issue by BasieP** [cypress-io/cypress#1001]
- Operating System: all
- Cypress Version: all
- Browser Version: all

### Is this a Feature or Bug?
Bug

### Current behavior:
The download only works on https due to the regex check in 'cli/lib/tasks/download.js'
const isUrl = (s) =>
  isString(s) && /^https:/.test(s)

### Desired behavior:
should work with all links (http, https, or better, no check at all. cause it's a manual override)

### How to reproduce:
set the  CYPRESS_BINARY_VERSION variable to: 'http://somesite.internal/bla.zip'
do the 'npm i cypress' command.

**Comment by BasieP** [comment]
my PR: https://github.com/cypress-io/cypress/pull/1007
But perhaps the one bahmutov provided is better, since mine is very basic.
I would like to have all valid url's work when the env variable is provided (because the user did supply the alternative cypress should not have to check it)

I can't test his PR though, since i don't know how to get it as an npm package...

**Comment by brian-mann** [comment]
Released in [`1.1.4`](https://docs.cypress.io/guides/references/changelog.html#1-1-4).
