### ISSUE TITLE
proxy mishandles network errors

### ISSUE THREAD

**Issue by acthp** [cypress-io/cypress#1013]
- Operating System: ubuntu 14.04
- Cypress Version: 1.1.3
- Browser Version: chrome 60

### Is this a Feature or Bug?
bug

### Current behavior:
Connection refused errors, that should fail in a fraction of a second, are instead returned as timeouts, after 30s.

### Desired behavior:
Return error 'connection refused' on connection refused, at the time the connection is refused.

### How to reproduce:
In the test app, make an ajax request to port that isn't listening. Outside cypress, it should fail immediately with connection refused. In cypress, it will fail after half a minute with timeout.

#### Test code:

```js

```

**Comment by brian-mann** [comment]
Can you provide a reproducible example? The reason I ask is that given the description, I know that there must be more to this problem.

The Cypress proxy most definitely works as intended in these scenarios. A very simple and quick test results in the immediate returning of those network requests in the case of ECONNREFUSED.

Here's both an image and an XHR failing as intended.

![screen shot 2017-12-05 at 4 40 40 pm](https://user-images.githubusercontent.com/1268976/33632271-2ea814da-d9db-11e7-9509-79a8ef645a6f.png)

Timings: 

![screen shot 2017-12-05 at 4 40 37 pm](https://user-images.githubusercontent.com/1268976/33632272-2eba0686-d9db-11e7-8f1b-b68152996fb1.png)

-----

![screen shot 2017-12-05 at 4 40 14 pm](https://user-images.githubusercontent.com/1268976/33632274-2ede6cd8-d9db-11e7-8205-748075656ea3.png)

Timings:

![screen shot 2017-12-05 at 4 40 27 pm](https://user-images.githubusercontent.com/1268976/33632273-2ec98b24-d9db-11e7-8fd9-a18af6ca8ef8.png)

**Comment by acthp** [comment]
This can be tested by opening a second tab in the cypress-controlled browser, and loading this file (making sure nothing is listening on port 1234).

```
<html><body><script>
window.onload = function () {
	console.log('hello');
	var xhr = new XMLHttpRequest();
// This case should return connection refused, but instead returns server 500.
//	xhr.open('GET', 'http://localhost:1234/');
// This case should return connection refused, but hangs for 30s and returns timeout.
	xhr.open('GET', 'https://localhost:1234/');
	xhr.onreadystatechange = function() {
		console.log('got status', xhr.status);
	};
	xhr.send();
}

</script></body></html>
```

**Comment by acthp** [comment]
Also, verified same behavior on OSX 10.10 with chrome 62.
