### ISSUE TITLE
Update 'command:end' event to respect async values

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1014]
Users have sometimes asked for ways to run arbitrary code "in between" commands - which basically means to run something at the end of the command.

This is useful for debugging, but also for doing some cool things with your JS framework of choice.

For instance with Angular or Vue, you could return a promise that resolves once the framework specific internal event queue has finished flushing.

This would mean that after a Cypress command finishes it would not move on until the framework has rendered, updated the DOM, or done whatever else its enqueued to do.

We currently fire the `command:end` event, but we don't do anything with their return values.

The logic should be:

- If there are listeners
- And they returned something
- And one of those values is a promise
- Await the resolution of those promise(s)
- Else if nothing was a promise, do not introduce another async tick

```js
Cypress.on('command:'end, (command, subject) => {
  return Promise.delay(1000) // slow every command down by 1 second
})

Cypress.on('command:end', (command, subject) => {
  if (Cypress.dom.isElement(subject) {
     const win = cy.state('window')

     if (win && win.Vue) {
       return new Promise((resolve) => {
         win.Vue.nextTick(resolve)
       })
     }
   })
})
```

**Comment by chrisbreiding** [comment]
We decided in our discussions of 4.0 that we do not want `command:*` events to block tests from running or add any asynchrony, so we will not be implementing this.
