### ISSUE TITLE
Retrieve full URL from XHR entry in test runner

### ISSUE THREAD

**Issue by fineline** [cypress-io/cypress#1015]
### Is this a Feature or Bug?

FEATURE

### Current behavior:

In the test runner view, I see that a bunch of XHR requests have been made, but I can't see the full URL. Tried expanding the size of that pane, hovering over each item, clicking, right-clicking, but can't find a way to get the full URL.

### Desired behavior:

It would be great to be able to somehow get the full URL from these XHR lines, to visually confirm the order of events and to make it quick to set up cy.route(). Although I can open the Network tab of dev tools, there is a lot of activity going on there and no way to match it to the XHR entries in the test runner view. The test runner view is a better representation of the calls as they relate to the tests, and would be the ideal place to get these URLs from.

**Comment by brian-mann** [comment]
Clicking on an XHR provides you all of the glorious details in the console - as clicking any command does. It even uses a tooltip to remind you.

![screen shot 2017-12-05 at 6 30 46 pm](https://user-images.githubusercontent.com/1268976/33636505-7fa88090-d9ea-11e7-8ab8-eaebad4118a8.png)

**Comment by fineline** [comment]
Brilliant, thanks for the quick response Brian, exactly what I needed and lots more useful information in there too.

I can confirm there is a tooltip that pops up after I click, but it disappears so quickly I had only read the first part of the message, about the snapshot having been pinned. Doing it a few more times I can now see "... and printed output to your console".

**Comment by MikeDabrowski** [comment]
What if I want to see XHR urls in the video that cypress creates ?
