### ISSUE TITLE
There's no way to turn off 'fixtureFolders' and 'supportFolders' 

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#102]
There is a config option for `fixtureFolders` and `supportFolders` that accepts a string of the path to the folders that you want, but there's no way to turn this off. 

It would be ideal if `false` could be passed to these options to turn off the folders altogher.

**Comment by brian-mann** [comment]
Fixed in [`0.15.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0150-03282016).
