### ISSUE TITLE
Launch chrome with `--no-sandbox` when on linux

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1020]
Else it immediately crashes without this flag.

**Comment by bahmutov** [comment]
Use `is-root` module to determine

**Comment by brian-mann** [comment]
Released in [`1.1.4`](https://docs.cypress.io/guides/references/changelog.html#1-1-4).

**Comment by alexsch01** [comment]
Very old issue......is this still needed?

I think `--no-sandbox` and `--disable-gpu` are no longer needed
