### ISSUE TITLE
Capture browser launching crashes and display them to the user

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1022]
We can detect an immediate `fail` with non zero exit code when launching the browser and then create a nice experience for the user to understand why it failed.

Having this would have helped @bahmutov and myself track down chrome launching issues with linux.

When using `cypress open` the experience should be in the desktop app, and when launching from the CLI, the error should just be printed to stdout.

**Comment by jennifer-shehane** [comment]
related: https://github.com/cypress-io/cypress/issues/1660

**Comment by flotwig** [comment]
I think this is actually implemented already, need to verify.
