### ISSUE TITLE
Be less aggressive with error messages when plugins cause errors

### ISSUE THREAD

**Issue by Graham42** [cypress-io/cypress#1025]
In this bug: https://github.com/cypress-io/cypress-watch-preprocessor/issues/1

The wording of the error message that the user experiences has a fairly aggressive tone. Specifically this line:
> This error originated from \*your* test code, not from Cypress.

The error message could be better phrased to something like "This is an error from your test code."

When building developer tools it's very important to keep DX (developer experience) in mind.

**Comment by brian-mann** [comment]
We derive most of our errors messages out the the feedback we get and the questions we get from real users.

These error messages just went in `1.1.3` and they originated from many situations where users thought that Cypress was throwing the error (assuming there was a bug in it). Other users were also confused whether the error was coming from test code or application code.

We updated these errors to clearly call out the point of origin, and a suggestion that the user must take action to fix it. Here's the issue that documents these errors:

https://github.com/cypress-io/cypress/issues/825

If you search in our issues or search gitter you will find that users regularly were confused without this specific wording. They'd have to inspect a stack trace, and even before doing that, they might not recognize the error and have no idea where it's coming from or why. Many times they would ask: "Is there a bug in Cypress?" We wanted to make it super clear that this is something on their end, and this error is happening as part of the test framework as opposed to a software error in Cypress itself.

I'll keep this issue open if anyone else has an opinion. You can find the errors and rewrite them and submit a PR if you'd like.

**Comment by jennifer-shehane** [comment]
I think they are just suggesting changing a couple words in the error. :upside_down_face: 

I agree, the use of the phrase 'an error from' is much clearer than 'error originated from'. 

Code where this message can be found:
- https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/error_messages.coffee#L792
- https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/error_messages.coffee#L802

There are several tests and snapshots that will require updating when changing this message.

**Comment by brian-mann** [comment]
Released in [`1.2.0`](https://docs.cypress.io/guides/references/changelog.html#1-2-0).
