### ISSUE TITLE
Allow passing path to the browser in --browser <path> CLI option

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1026]
## feature

Last unfinished task from #511 

Allow the user to pass path to specific browser to use `--browser /my/bin/browser`

**Comment by brian-mann** [comment]
You need to also handle the error situation when the browser cannot be found.

The code paths likely already account for this, but at least write one test.

**Comment by brian-mann** [comment]
They are likely in `integration/cypress_spec.coffee` already

**Comment by bahmutov** [comment]
it is not as simple as I have hoped, and I was getting an error as I left for meetup :( basically I am passing the browser name all the way down to the launcher and want to either find it by name in the list of detected browsers or try running it as chrome

**Comment by bahmutov** [comment]
hmm, something is not shutting down browser after it is done testing

**Comment by rsudarson** [comment]
@bahmutov  : I've a path to linux chrome binary, how can i tell to cypress to pickup this chrome path for testing.

**Comment by Aurimas1** [comment]
Is this feature is still in development?

**Comment by ethernal** [comment]
I am also interested in this.. how can I for example use Chrom Beta that is installed side by side with stable version?
