### ISSUE TITLE
Trimmed "alert" output in the reporter

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1029]
## Current behavior:

When our app is using `alert()` they are intercepted and printed in the reporter. If we print `alert('abc')` it shows up. If we use a number like `alert(42)` the number is truncated :(

Load page that does `alert(42)`

### Additional Info (images, stack traces, etc)

<img width="1106" alt="screen shot 2017-12-06 at 7 25 34 pm" src="https://user-images.githubusercontent.com/2212006/33692523-ada051a4-dabb-11e7-97c5-9f7b17b2ccaa.png">

- Operating System: Darwin
- Cypress Version: 1.1.3
- Browser Version: Electron

**Comment by jennifer-shehane** [comment]
You are referring to this bit of the reporter where the numbers are slightly hidden? 
![screen shot 2017-12-07 at 10 51 57 am](https://user-images.githubusercontent.com/1271364/33724203-c545e360-db3c-11e7-9af1-c9ce12c17150.png)

**Comment by bahmutov** [comment]
Yes but it is only for numbers

**Comment by jennifer-shehane** [comment]
This no longer happens in Cypress version 3.4.0.

<img width="243" alt="Screen Shot 2019-07-12 at 10 31 36 AM" src="https://user-images.githubusercontent.com/1271364/61101577-4e744780-a490-11e9-8cb1-eae2abacd8a9.png">
