### ISSUE TITLE
Add chainable cy.getCookies() command that returns an object.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#103]
`cy.clearCookies` returns an object representation of the document's cookie. I'd like a `cy.getCookies()` that returns an object representation of the document's cookie that I can chain off of to make assertions about the cookie.

Currently I have to go into the `.document().its('cookies')` or go into the Cypress API Cookies, which is awkward.

**Example**
```javascript
cy.getCookies().should('have.property', 'token', '123ABC')
cy.clearCookies().should('not.have.property', 'token')
```

**Comment by brian-mann** [comment]
Fixed in [`0.14.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0143-03202016).
