### ISSUE TITLE
Cypress resolves import incorrectly?

### ISSUE THREAD

**Issue by tan-nhu** [cypress-io/cypress#1035]
- Operating System: Mac 10.12.6
- Cypress Version: 1.1.4
- Browser Version: Chrome 62

### Is this a Feature or Bug?

Bug

### Current behavior:

When two test files import a same module, cypress resolves each import from scratch instead using the same reference. This behavior is different from node/require imports.

### Desired behavior:

Cypress should import modules the same as node.

### How to reproduce:

cypress/utils.js:

```javascript
export const key = +new Date()
```

cypress/integration/test1.js

```javascript
import { key } from '../utils'

describe('Foo1', () => {
  it('Bar1', () => {
    cy.log(key)
  })
})
```

cypress/integration/test2.js

```javascript
import { key } from '../utils'

describe('Foo2', () => {
  it('Bar2', () => {
    cy.log(key)
  })
})
```

When running all, cypress logs two different keys. The same import in nodejs results the same key.

### Additional Info (images, stack traces, etc)

[cypress-test.zip](https://github.com/cypress-io/cypress/files/1540436/cypress-test.zip)

**Comment by brian-mann** [comment]
Cypress serves each spec in isolation - which is the correct and intended behavior.

We are actually moving **more** towards this way, which will become the default enforced behavior on all runs.  You can read more here: https://github.com/cypress-io/cypress/issues/681
