### ISSUE TITLE
Cookies are bound to outerframe instead of iframe when iframe app is navigated to a pathname

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#104]
When the iframe is navigated to a pathname that is not root, the cookies are bound to the outer frame, so that commands like `cy.clearCookies()` do not in fact clear the cookies in the test application.

**Comment by brian-mann** [comment]
Fixed in [`0.14.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0143-03202016).
