### ISSUE TITLE
Extend plugins to enable returning a promise and/or mutating config 

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1042]
Plugins are currently expected to return synchronously and bind to events.

Even though `config` is yielded, it is unmutable (we disregard the return value)

This feature will enable users to:

- Add async events to the plugins function
- Eventually resolve with a modified config object
- Programmatically alter config values or env vars

We'll need to also take this into account with the resolved values of config, and make sure we display them as the source in the Desktop GUI

**Comment by iGitScor** [comment]
The 3rd point is so freaking awesome 👏 👌

**Comment by brian-mann** [comment]
We now show config + env values overridden from plugins.

<img width="496" alt="screen shot 2017-12-10 at 11 01 30 pm" src="https://user-images.githubusercontent.com/1268976/33815283-23893008-ddfe-11e7-979a-17f865565f86.png">

**Comment by brian-mann** [comment]
Released in [`1.2.0`](https://docs.cypress.io/guides/references/changelog.html#1-2-0).
