### ISSUE TITLE
Lint js from root produces results different from lint in cli

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1047]
## internal bug

Running `npm run lint-js` from the root does not fix `cli/*.js` files, but running
```
cd cli
npm run lint
```
fixes JS files. In `cli` we use `bin-up` to find the eslint

**Comment by luanReis** [comment]
I don't see anything wrong with the command `npm run lint-js` for me it does fixes JS files at `cli/*.js`. Could you give more information about this issue? Perhaps a way to reproduce.

**Comment by jennifer-shehane** [comment]
Closing as this is nearly 2 years old now.
