### ISSUE TITLE
Update TS type definitions to match API more closely

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1050]
- Add mocha and chai (and sinon-chai and chai-jquery) types
- Add API methods that were missing (like `cy.clock')
- Fixed a few API methods that had pre 1.0 type definitions
- start type linting kitchenk sink spec file

**Comment by bahmutov** [comment]
Done by @NicholasBoll in the pull request #1048

**Comment by brian-mann** [comment]
Released in [`1.2.0`](https://docs.cypress.io/guides/references/changelog.html#1-2-0).
