### ISSUE TITLE
Wait for graphql query to complete

### ISSUE THREAD

**Issue by moimael** [cypress-io/cypress#1053]
- Operating System: Fedora 27
- Cypress Version: 1.1.4
- Browser Version: Chrome 63

### Is this a Feature or Bug?
Not sure

### Current behavior:
I wanna wait until after my graphql queries complete to start running my tests. Right now it displays a loading indicator after the page load and before the query complete, which makes my tests fails if the query do not complete quick enough. Using cy.wait doesn't work.

### Desired behavior:
I would like to use the wait feature on graphql query but it doesn't seems to work, cypress do not seems to pick graphql network requests.

### How to reproduce:
Try to use cy.wait on a graphql query made with react-apollo

**Comment by moimael** [comment]
Hi,

I think I found the cause of this, react-apollo is using fetch and cypress do not seems to support it. Disabling fetch and using xhr instead using the polyfill seems to do the trick :)

**Comment by bahmutov** [comment]
Perfect, glad it worked out. We have `fetch` support in the roadmap #687 but for now you can just disable `window.fetch` like shown in this recipe https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window-fetch
