### ISSUE TITLE
Uncaught SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by devnatash** [cypress-io/cypress#1066]
- Operating System:
- Cypress Version:
- Browser Version:

#### Test code:

```js

```

**Comment by Karuhanga** [comment]
If someone else runs into this in the future, mine was down to trying to load a non existent JS file(from my index page).

Adding this to the test file got me on the right track;

```
Cypress.on('uncaught:exception', (err, runnable) => {
  console.log(err);
  return false;
})
```
