### ISSUE TITLE
outgoing connections being made - possible privacy issue?

### ISSUE THREAD

**Issue by ndamjan** [cypress-io/cypress#1069]
Hello,

I have an outgoing connection firewall and I see some connection attempts being made:

<img width="634" alt="screen shot 2017-12-14 at 12 51 41" src="https://user-images.githubusercontent.com/5169234/33991165-d572940e-e0cd-11e7-8067-67e11c45ec63.png">

I am using only test runner, no dashboard and not defining a project. So I don't expect my tests to go anywhere but on my local computer.

**Can you please explain which kind of data gets sent and where?** 

I believe there could be serious privacy concerns with sending screenshots and test runs elsewhere without consent. 

Otherwise this looks like a great product!

Thanks,
Damjan

**Comment by brian-mann** [comment]
One of the best things about an open source project is... well - that it's open! You can freely read through every single line of code that the Test Runner does.

I can assure you there are zero situations where we send test recording data to any of our services unless you have:

- Setup a project to record (and received a projectId)
- Passed an explicit `--record` flag to your `cypress run`

Never is there ever a situation where we record anything while you are running in "GUI" mode locally when writing tests.

What is actually happening under the hood to trigger this is that Cypress itself has to spin up multiple http servers that run locally on your computer. These are necessary for Cypress to modify the traffic coming in and out of the browser - but they're not different than how any other webserver works.

I'm not sure what firewall you have or what the rules are. It may make a difference that (I'm guessing) you've "double-clicked" on Cypress as opposed to running it from the Command Line. 

Also the hostname you've provided is not one that we recognize. I'm guessing its actually yours. If that's the case, then what is triggering this is the underlying Cypress proxy spinning up a server so it can inspect the traffic when it comes back from your origin server (so it can modify it). This is what makes Cypress able to automate + control server responses. All of this stays within your local computer, it does not require a Cypress service or server outside of your computer. You can even turn off your internet and Cypress will continue to work as normal

I believe we make all of this very clear in our documentation, but if you read something somewhere which gave the wrong impression please point it out to us.
