### ISSUE TITLE
Allow {force: true} option to disable error checking on select & select options

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#107]
Allow `{force: true}` to be passed to `cy.select` (just as type & check commands), that disables error checking so that you can "select" a disabled select or option.

**Example Code**

`index.html`

```html
<html>
<body>
  <select id="disabled-select" disabled>
    <option value="456">apples</option>
    <option value="457">oranges</option>
    <option value="458">bananas</option>
  </select>

  <select id="disabled-option">
    <option value="456">apples</option>
    <option value="457" disabled>oranges</option>
    <option value="458">bananas</option>
  </select>
</body>
</html>
```

`spec.js`

``` javascript
it('test disabled select', () => {
  cy.visit('index.html')
  cy.get('#disabled-select').select('oranges')
})

it('test disabled option', () => {
  cy.visit('index.html')
  cy.get('#disabled-option').select('oranges')
})
```

<img width="733" alt="Screen Shot 2020-04-27 at 10 13 05 AM" src="https://user-images.githubusercontent.com/1271364/80332024-b6edb300-886f-11ea-9bfc-9c840cafa958.png">

**Comment by spaghetticode** [comment]
would love to see this happen ❤️

**Comment by carlos-granados** [comment]
Any news on this? The documentation says that this should be working but I just tested it and it is not.

**Comment by benowenssonos** [comment]
Any update on this?

**Comment by jennifer-shehane** [comment]
No, this does not currently work.

**Comment by jennifer-shehane** [comment]
I updated the docs to note that passing `force: true` to `.select()` does not disable the checks for selecting disabled options/optgroups. https://github.com/cypress-io/cypress-documentation/pull/2776

**Comment by davidmunechika** [comment]
We have decided not to implement this `{force: true}` option because there is no way to retrieve the value from selected disabled options (due to the nature of jQuery's `.val`). Therefore, this would prevent verifying the actual values of the selected options and cause common assertions such as `cy.select('foo', {force: true}).invoke('val').should('eq', 'foo')` to fail.
