### ISSUE TITLE
Not native behavior of XMLHttpRequest inside test enviroment

### ISSUE THREAD

**Issue by ossman11** [cypress-io/cypress#1080]
There is a incompatible difference between the ```XMLHttpRequestobject``` of cypress and the native javascript implementation. I found this difference when debugging the failing event handling of some application which had created a custom implementation of the ```XMLHttpRequest``` object.

- Operating System: Windows 10
- Cypress Version: 1.2.0
- Browser Version: Chrome 63

### Is this a Feature or Bug?
This seems to be a bug as it impacts the behavior of an application inside the cypress versus running natively.

### Current behavior:
Currently when an event is registered cypress returns a wrapper function for the event function or the overwritten (default) cypress function for that event. This wrapper function references an externally 
scoped object that contains the actual function to be called. This function is automatically overwritten once the event is set. Once the wrapper function is called it will fetch and call the related function to that event.

### Desired behavior:
What should be returned is the original function like it would do with the native implementation. This would of course cause trouble as it would no longer be called in the correct context of the ```XMLHttpRequest``` object, but this can easily be solved with calling ```bind(xhr)``` in the function to be returned.

### How to reproduce:
The issue is very easily reproduced by setting any event function twice and fetching it in between. This will cause the first fetched function to also call the second set function. If called after the second function is set.

#### Test code:

```js
var xhr = new XMLHttpRequest();

var fn0= xhr.onload;

xhr.onload = function(){
  console.log("Function 1");
};
var fn1 = xhr.onload; // gets wrapper function

xhr.onload = function(){
  console.log("Function 2");
};
var fn2 = xhr.onload; // gets wrapper function

console.log(!!fn0); // Will print out "false" natively and "true" when running inside cypress
fn1(); // Will print out "Function 1" natively and "Function 2" when running inside cypress
fn2(); // Will print out "Function 2" natively and "Function 2" when running inside cypress
```

### Additional Info (images, stack traces, etc)
The source code of this behavior can be found here.
https://github.com/cypress-io/cypress/blob/2b2b6d99a9f1bf232d9c7396b25390913d5f2b18/packages/driver/src/cypress/server.coffee#L442-L449

This issue might be addressed already by #687, But I couldn't find similar descriptions of this issue.

**Comment by brian-mann** [comment]
This is true - but I dont' think there's any working around it. Cypress instruments the XHR object so it can be notified in order to do its stubbing.

The fix for this is as you suggested: #687 which would move all of these API's out of the browser and into the network layer. We'll keep this open as a reference for that issue.
