### ISSUE TITLE
Select a place on a map (for example google maps)

### ISSUE THREAD

**Issue by tascioglu** [cypress-io/cypress#1081]
Hi all,

Need some help :(

How can I write a code to select a place on a map (for example google maps)? I tried different things but still hanging on this one :(

**Comment by brian-mann** [comment]
Use `x`, `y`, or `position` arguments in https://docs.cypress.io/api/commands/click.html#Syntax

Or use the lower level https://docs.cypress.io/api/commands/trigger.html to fire the exact event you want to fire.

You'll need to provide way more than this though if you want anyone to help you. Maybe set up a reproducible repo with the application under test and some test code.

**Comment by tascioglu** [comment]
Hi Brian...

Can not place a lot of code for this one.. Just see below. I selected this code with select element and copied..

<div _ngcontent-c1="" id="map" tabindex="0">
  <div class="ol-viewport" data-view="15" style="position: relative; overflow: hidden; width: 100%; height: 100%; touch-action: none;">
    <canvas class="ol-unselectable" style="width: 100%; height: 100%; display: block;" width="858" height="1714"></canvas>
    <div class="ol-overlaycontainer"></div>
    <div class="ol-overlaycontainer-stopevent">
      <div class="ol-overlay-container ol-selectable" style="position: absolute; display: none;">
        <div class="arrow_box" id="popup-container">
        </div>
      </div>
      <div class="ol-zoom ol-unselectable ol-control">
        <button class="ol-zoom-in" type="button" title="Zoom in">+</button>
        <button class="ol-zoom-out" type="button" title="Zoom out">−</button>
      </div>
      <div class="ol-zoomslider ol-unselectable ol-control">
        <button type="button" class="ol-zoomslider-thumb ol-unselectable" style="top: 188px;"></button>
      </div>
      <div class="map__mouse-position">
      </div>
    </div>
  </div>
</div>

**Comment by tascioglu** [comment]
Couldn't I copy and past some html code here?

**Comment by brian-mann** [comment]
Yeah pasting code like this especially HTML is not really feasible. You'd need to put together a reproducible repo, or find something already hosted online and provide your test code.

I imagine it has something to do with the `canvas` element but I'm sure you can fire events to it - you just might need to manually fire them with `cy.trigger`

**Comment by jennifer-shehane** [comment]
@tascioglu Could you include the tests you wrote that failed? And perhaps post a screenshot (or the actual text of the error) of the failure from the Cypress Test Runner.

**Comment by tascioglu** [comment]
will create a new issue with a better example and description of it. Closing this one.
