### ISSUE TITLE
Cypress type definitions don't unwrap subject in `cy.then`

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#1084]
The current cypress types don't properly handle returning a thenable from `cy.then`. It will return the wrapped subject instead.

- Operating System: N/A
- Cypress Version: 1.2
- Browser Version: N/A

### Is this a Feature or Bug?
Bug

### Current behavior:
```ts
cy.wrap('foo').then(subject => {
  subject // $ExpectType string
  return cy.wrap(subject)
}).then(subject => {
  subject // $ExpectType Chainable<string>
})
```

### Desired behavior:
```ts
cy.wrap('foo').then(subject => {
  subject // $ExpectType string
  return cy.wrap(subject)
}).then(subject => {
  subject // $ExpectType string
})
```

#### Test code:
In `cli/types/tests/cypress-tests.ts`
```ts
cy.wrap('foo').then(subject => {
  subject // $ExpectType string
  return cy.wrap(subject)
}).then(subject => {
  subject // $ExpectType string
})
```
In the `cli` folder run:
```
npm run dtslint
```

### Additional Info (images, stack traces, etc)

I have a fix pending, but I wanted to log it as an issue first.

**Comment by brian-mann** [comment]
Released in [`1.4.0`](https://docs.cypress.io/guides/references/changelog.html#1-4-0).
