### ISSUE TITLE
Selector Playground missing highlight/tooltip styles in Electron

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#1086]
The selector playground highlighting is broken in Electron because the styles are being added via a `<link>` tag, which isn't supported by the version of Chrome being run.

![screen shot 2017-12-18 at 2 38 33 pm](https://user-images.githubusercontent.com/1157043/34124531-3f7c32fc-e401-11e7-847f-714938078ed2.png)

**Comment by brian-mann** [comment]
Released in [`1.4.0`](https://docs.cypress.io/guides/references/changelog.html#1-4-0).
