### ISSUE TITLE
cy.click(), says it's detached from DOM when it isn't

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#109]
The DOM element that I am clicking on DOES get removed from the DOM after click, but the click() is timing out, there are 2 clicks in the log and the error message describes `cy.focus()`

**Example Code**
```javascript
cy.contains("Jane Lane").click()
cy.contains("a", "Logout").click()
```

**Command Log**
![screen shot 2016-02-22 at 5 24 08 pm](https://cloud.githubusercontent.com/assets/1271364/13234942/4d41cc1e-d989-11e5-80c0-df2a2bf21ee2.png)

**Comment by brian-mann** [comment]
Fixed in [`0.14.2`](https://github.com/cypress-io/cypress/wiki/changelog#0142-03142016).
