### ISSUE TITLE
cy.exec() example fails in windows (cannot use cat in windows) 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1097]
The example spec needs to be updated and re-deployed.

<img width="838" alt="screen shot 2017-11-30 at 10 32 19 am" src="https://user-images.githubusercontent.com/1271364/33438896-0bd6e992-d5ba-11e7-8465-e37d7f4e5c16.png">

See: 
- https://github.com/cypress-io/cypress-example-kitchensink/issues/27
- https://github.com/cypress-io/cypress-example-kitchensink/pull/33
- https://github.com/cypress-io/cypress/pull/1095

**Comment by brian-mann** [comment]
Released in [`1.4.0`](https://docs.cypress.io/guides/references/changelog.html#1-4-0).
