### ISSUE TITLE
Search specs by name of file in Desktop-GUI

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1098]
### Is this a Feature or Bug?
Feature

### Current behavior:
Cannot filter list of specs or search specs by name

### Desired behavior:
To filter list of specs by name through searchbar.

**Comment by brian-mann** [comment]
<img width="944" alt="screen shot 2017-12-19 at 12 05 48 pm" src="https://user-images.githubusercontent.com/1268976/34176505-199024cc-e4ce-11e7-9de4-f6b540222bdf.png">

**Comment by brian-mann** [comment]
Released in [`1.4.0`](https://docs.cypress.io/guides/references/changelog.html#1-4-0).

**Comment by jbpallingayan** [comment]
can we search multiple file and run it?
