### ISSUE TITLE
Improve error message on jquery traversal methods when elements aren't found

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#11]
jQuery child commands should output a similar error to `cy.contains` when their command fails finding their elements.

```html
<input type="text" name="search">
<i class="fa-spinner"></i>
```

```js
cy.get("input").find(".fa-spinner")
```

**Display Error:**
```
could not find `.fa-spinner` within the element: input
```

**Comment by brian-mann** [comment]
Fixed in `0.4.4`. [Changelog](https://github.com/cypress-io/cypress/wiki/Changelog#044-04092015)
