### ISSUE TITLE
cy.then needs to support {timeout: N} options

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#110]
Currently there is no way to extend a `cy.then` timeout on the fly like other commands. It needs to accept timeout options with the default being `commandTimeout`.

**Comment by jennifer-mann** [comment]
This is fixed in the upcoming `0.14.0` release.

**Comment by brian-mann** [comment]
Fixed in [`0.14.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0140-03082016).
