### ISSUE TITLE
Roadmap link is broken

### ISSUE THREAD

**Issue by nhducit** [cypress-io/cypress#1100]
Roadmap link is broken: https://github.com/cypress-io/cypress/projects

**Comment by brian-mann** [comment]
We disabled that in Github since we don't use it.

We added a `ROADMAP.md` file here https://github.com/cypress-io/cypress/blob/develop/ROADMAP.md

Which points you to here https://docs.cypress.io/guides/references/roadmap.html#

**Comment by jennifer-shehane** [comment]
@nhducit was referring to this link in the main README.md which was indeed broken but is now fixed. https://github.com/cypress-io/cypress/commit/24fd6a76eb84199ad691255a4bb67095ee7b74f2
