### ISSUE TITLE
Usage of environment

### ISSUE THREAD

**Issue by kemalbayar** [cypress-io/cypress#1101]
#### Test code:
I have some li or option values and i want to check if those exists so i use the following usage for this purpose. 

```js
cy.get(‘.myclassname li’).should(($lis) => {

        expect($lis).contain(‘Sugar’)
        expect($lis).contain(‘Juice’)
        expect($lis).contain(‘Bread’)
        expect($lis).contain(‘Ball’)

       })
```

as you see, i have to write every value i have one by one.  Is there a way to define all the values i have in a variable and use that variable instead of writing all the values one by one like above

**Comment by bahmutov** [comment]
You could find a `chai` assertion helper that does that (see how to bring additional chai assertions in this example https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/extending-cypress__chai-assertions) or just create little helper function that you can reuse. I see something like this

```js
const shouldContain = (...names) => ($lis) => {
  names.forEach(name =>
    expect($lis).contain(name)
  )
}
cy.get(‘.myclassname li’).then(shouldContain('Sugar', 'Juice', 'Bread', 'Ball'))
```

**Comment by jennifer-shehane** [comment]
Seems as if you could use Cypress `.each()` to iterate through each li (or also just assert against the $lis in my example below if you did want to check the entire list against each value). 

```js
let names = ['Sugar', 'Juice', 'Bread', 'Ball']

cy.get(‘.myclassname li’).each(($li, i, $lis) => {
    expect($li).to.contain(names[i])
})
```

**Comment by kemalbayar** [comment]
Thank you all of you for your answers. 

@jennifer-shehane  

im used to use the following code before your help  ...('.myclassname li')... im used li not div but when i used your code with li it failed but with div it run successfuly


the code i used before your help .... ('.myclassname li').....

cy.get('div[id="12345"]').click()
          cy.get('.myclassname li').should(($lis) => {

            expect($lis).contain('Sugar')
            expect($lis).contain('Juice')
            expect($lis).contain('Bread')
            expect($lis).contain('Ball')
          })
          


I couldnt run your code with li but it runs with div ....('.myclassname div')....

cy.get('div[id="12345"]').click()
          var names = ["Sugar", "Juice", "Bread", "Ball"]
          cy.get('.myclassname div').each(($div, i, $lis) => {
              expect($li).to.contain(names[i])
          })


in the web page Im trying to test,  all the li's which Im trying to check are in div tags seperatly
may it the reason? if so, i dont understand why the first code run successfuly and why your code doesnt run with li

**Comment by bahmutov** [comment]
Can you make a reproducible small example, maybe even in the fork of https://github.com/cypress-io/cypress-example-kitchensink with your code that shows the problem? It is hard to see what is going on and what you expect to happen via code snippets in this issue.
