### ISSUE TITLE
Update deps in CLI to avoid security warning

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1103]
https://npms.io/search?q=cypress puts "insecure" badge on our repo

<img width="728" alt="screen shot 2017-12-20 at 10 47 47 am" src="https://user-images.githubusercontent.com/2212006/34215458-600a819a-e573-11e7-9825-c1b8d2a7b45c.png">

Because https://nodesecurity.io/check/cypress shows debug -> extract-zip small issue

<img width="891" alt="screen shot 2017-12-20 at 10 48 45 am" src="https://user-images.githubusercontent.com/2212006/34215495-7b21db2c-e573-11e7-9398-3489d005446e.png">

Need to upgrade extract-zip to latest

**Comment by brian-mann** [comment]
Released in [`1.4.1`](https://docs.cypress.io/guides/references/changelog.html#1-4-1).
