### ISSUE TITLE
Add schema file for cypress.json to scaffolded files

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1105]
VSCode and (probably) other editors allow specifying a separate schema file for JSON files. If such file is found, the editor will show intellisense help, provide default values, etc - really nice experience.

For example, the scaffolded `cypress.json` could have the following

```json
{
  "$schema": "./cypress/cypress-schema.json"
}
```
And the new file `cypress/cypress-schema.json` could describe all configuration options we have https://docs.cypress.io/guides/references/configuration.html#Options

```json
{
  "title": "JSON schema for https://cypress.io test runner cypress.json file. Details at https://on.cypress.io/configuration",
  "type": "object",
  "properties": {
    "baseUrl" : {
      "type": "string",
      "description": "Url used as prefix for cy.visit() or cy.request() command’s url. Example http://localhost:3030 or https://test.my-domain.com"
    },
    "env": {
      "type": "object",
      "description": "Any values to be set as environment variables",
      "body": {}
    },
    "ignoreTestFiles": {
      "type": "string",
      "description": "A String or Array of glob patterns used to ignore test files that would otherwise be shown in your list of tests. Cypress uses minimatch with the options: {dot: true, matchBase: true}. We suggest using http://globtester.com to test what files would match."
    },
    "numTestsKeptInMemory": {
      "type": "number",
      "default": 50,
      "description": "The number of tests for which snapshots and command data are kept in memory. Reduce this number if you are experiencing high memory consumption in your browser during a test run."
    }
 }
}
```
and many more. Here is how helpful it is in VSCode

<img width="969" alt="intellisense-json" src="https://user-images.githubusercontent.com/2212006/34218868-6f3310ec-e57d-11e7-8e0d-de7fb7f7c9a8.png">

when adding new option

<img width="888" alt="screen shot 2017-12-20 at 12 01 03 pm" src="https://user-images.githubusercontent.com/2212006/34218927-9dfe661a-e57d-11e7-8d12-73112371af26.png">

**Comment by bahmutov** [comment]
Note, to allow a string or an array of strings, the item should be
```
"ignoreTestFiles": {
      "type": ["string", "array"],
      "items": {
        "type": "string"
      },
      "description": "A String or Array of glob patterns used ..."
    }
```

**Comment by bahmutov** [comment]
JSON schema for VSCode (and I assume other editors judging by the list) https://code.visualstudio.com/docs/languages/json

Public server with schemas for files like `package.json` and other common JSON files: http://schemastore.org/json/

**Comment by bahmutov** [comment]
For Atom, need this plugin https://atom.io/packages/autocomplete-json - reads from Schemastore. Seems making a pull request will make everyone happy.

**Comment by jennifer-shehane** [comment]
Was this closed in favor of this issue? Can't determine why this was closed. https://github.com/cypress-io/cypress/issues/1109

**Comment by bahmutov** [comment]
You see the @brian-mann comments? I strongly disagree with them of course - adding a `$schema` property to `cypress.json` has nothing but benefits, for now I have decided to pursue the round about solution of adding the schema file to json store and then you can set in your `.vscode` settings URL so ALL `cypress.json` files will be understood. It will be up to the user to set something like this

```
 "json.schemas": [
        {
            "fileMatch": [
                "/cypress.json"
            ],
            "url": "http://json.schemastore.org/cypress.json"
        }
    ]
```

**Comment by mikaelboff** [comment]
+1 would be nice

**Comment by mvasin** [comment]
If someone bumped into this issue to figure out how to enable suggestions for `cypress.json` (i.e. in VS Code), there you go:
```
{
  "$schema": "https://raw.githubusercontent.com/cypress-io/cypress/develop/cli/schema/cypress.schema.json",
  "baseUrl": "http://localhost:5000"
}
```
`baseUrl` of course is just an example, stuff it with your own stuff.

**Comment by jnnnnn** [comment]
I tried the other solutions in this thread and it turns out schemas are tricky because the Cypress config file is a Javascript file, not a JSON file. 

There is a code-completion solution at https://docs.cypress.io/guides/references/configuration#Intelligent-Code-Completion .
