### ISSUE TITLE
Using Contenteditable and type - caret does not move

### ISSUE THREAD

**Issue by mikeyarce** [cypress-io/cypress#1108]
- Operating System: Mac OS Sierra
- Cypress Version: 1.4.0
- Browser Version: Chrome 63.0.3239.108

### Is this a Feature or Bug?
Bug

### Current behavior:
Using the Cypress `type` function on a `contenteditable` input doesn't move the caret along with the text.  At first I thought this might be specific to React, but actually it does the same thing with a plain `contenteditable` input on any HTML page.

### Desired behavior:
To move the caret with the text so you can simulate typing and do things like `{enter}`

### How to reproduce:
1. Create a `contenteditable` html element
2. Use `type()` on that element

#### Test code:

```
<p contenteditable="true">
    Hello
</p>

cy.get('p').type('hello', {delay: 1000})
```

The delay is helpful so you can actually see the caret as it's being typed out.

### Additional Info (images, stack traces, etc)
![contenteditable](https://user-images.githubusercontent.com/3220162/34224025-404809c4-e576-11e7-846f-1f6a4058df3f.gif)

**Comment by Bkucera** [comment]
This issue should be fixed in an upcoming patch release, alongside other issues from the #1241 `cy.type()` epic
