### ISSUE TITLE
Add option to hide log to the "cy.its" command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1133]
Cypress v1.4.1 `cy.its` https://on.cypress.io/its command does not accept options argument, so there is no way to hide it from the command log for example.

**Comment by gabbersepp** [comment]
was implemented in this PR: https://github.com/cypress-io/cypress/pull/5519

**Comment by jennifer-shehane** [comment]
Released in [`3.8.0`](https://on.cypress.io/changelog#3-8-0).
