### ISSUE TITLE
Split TypeScript `Chainer` interface into different interfaces

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#1137]
## Problem:
`Chainer` is a very generic chainable interface, but there actually at least 3 distinct interfaces: Parent (or starters), Elements and generic. (Part of #1040)

For example:
```ts
// `.find` and `.click` only exist on the `Element` interface. Docs show `.get` as a Parent command.
cy.get('#result').find('button').click()

//
cy.get('.connectors-each-ul>input') // JQuery<HTMLElement>
  .filter('input') // JQuery<HTMLInputElement>
  .each(function($el, index, list) {
    $el // JQuery<HTMLElement> - cannot infer any better without splitting interface
    index // number - this is fine
    list // HTMLElement[] - cannot unwrap Subject type correctly, so fall back to `HTMLElement` rather than `HTMLInputElement`
    console.log($el, index, list)
  })
```

## Solution:
Break into at least 3 distinct interfaces.
- `ParentCommands` - anything valid after `cy.`
- `ElementCommands` - anything expecting a `JQuery`-wrapped element as a subject
- `Commands` - everything else. Many commands can handle any value

Actual names can change. Right now all commands are on a interface called `Chainer`. Probably because the chainable command class is called `$Chainer`. `Commands` might be a better name since each command is defined using the `addCommand` method (or `Cypress.Commands.add` externally). Maybe `Chainer` is a good name since `Cypress.Commands` is already used as a value (`Cypress.Commands.add` is a value. An interface and value can exist using the same symbol name since TypeScript knows the context, but maybe confusing to a developer).

### Pros:
- Auto-complete can now be more accurate and limited to what's actually available (biggest benefit).
- TypeScript can have type errors for invalid chains rather than relying solely on runtime errors
- `Subject` can be more accurate for many commands (context sensitive to Subject type)

### Cons:
- Any TypeScript implementation that extends the current `Chainer` will be broken after this change. No rumtime will be broken, but many people choose to not emit code on type errors. The fix involves updating the command chain overrides (simple enough when documented).
- Type definitions are more complicated - chainable interfaces need mechanism to move back and forth. For example: `cy.get('body').then(body => body.width())` returns a number, so we went from `ParentCommands` -> `ElementCommands` -> `Commands`

I have experimented with splitting the `Chainer` interface and it works pretty well. The current implementation isn't bad, but requires more generic overrides in a pinch rather than having chained commands return the correct subject. A command like `cy.get` may always require a generic override since it can return any value type from an alias which is untypeable in the current implementation.

**Comment by ryota-murakami** [comment]
Looks like this is really close my `cypress-react-unit-test` problem.
https://github.com/bahmutov/cypress-react-unit-test/issues/525
