### ISSUE TITLE
Server XHR is not detected / stubbed when using document.write

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1139]
Cypress 1.4.x

If we do NOT use `cy.visit` to open a page, and just do `document.write`, then the XHR requests are not detected and are not stubbed.

Example: https://github.com/bahmutov/cypress-hyperapp-unit-test/blob/master/cypress/integration/server-todos-spec.js#L8 where I stub the server XHR route before mounting a Hyperapp component. Same stubbing works if we do not mount Hyperapp but just load an HTML page. In this example, the command log does not even show XHR 

<img width="1120" alt="screen shot 2017-12-30 at 11 27 05 pm" src="https://user-images.githubusercontent.com/2212006/34459293-4be2352e-edba-11e7-8c49-ded26655d361.png">

**Comment by bahmutov** [comment]
The test stubs the route, mounts the component, then expects to find the synthetic data
```
  cy.server()
    cy.route('/todos?_limit=3', mockTodos)
  })

  context('Stubbed server', () => {
    beforeEach(() => {
      const state = {
        todos: []
      }
      const actions = {
        setTodos: todos => state => ({ todos }),
        toggle
      }
      const view = (state, actions) =>
        h(ServerTodos, {
          n: 3,
          todosLoaded: actions.setTodos,
          todos: state.todos,
          toggle: actions.toggle
        })
      mount(state, actions, view)
    })

    // skip until can figure out why the server is not stubbed
    // when writing into document directly.
    it.skip('shows todos', () => {
      cy.contains('Todo')
      cy.get('.todo').should('have.length', 3)
      cy.get('.todo').first().contains('Stub server')
    })
```

**Comment by brian-mann** [comment]
We don't bind to the remote app before the first `cy.visit` so we just need to add the bindings immediately when the remote window is first created.

**Comment by bahmutov** [comment]
Yeah I even tried to visit a dummy page just for this before writing to the document- did not help either

**Comment by brian-mann** [comment]
I see now. You are initiating the XHR from the test frame - not the app frame. The test frame is not bound to - although we could do that as well.

**Comment by bahmutov** [comment]
If we can do this behavior from test frame then the argument for unit testing components becomes irresistible- especially because react unit testing works beautifully :)

**Comment by jennifer-shehane** [comment]
This appears to be fixed. Ran https://github.com/bahmutov/cypress-hyperapp-unit-test/blob/master/cypress/integration/server-todos-spec.js#L8 in Cypress 3.4.0.

<img width="449" alt="Screen Shot 2019-07-12 at 2 13 33 PM" src="https://user-images.githubusercontent.com/1271364/61111333-58597300-a4af-11e9-9312-4a329a8ec8c1.png">
