### ISSUE TITLE
Headed/headless nomenclature 

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#1140]
TBD

**Comment by jennifer-shehane** [comment]
There are differences between **headless**, **headed**, and the **interactive mode** (which is what you do when you click to open a project). This is...confusing and we've even been discussing changing the names of some things to make it less confusing.

- **Headless Mode** - Run when you don't want a browser window popping up on the screen. Maybe you're on your computer and just want to run it in the terminal real quick. This is the *default* when typing `cypress run`. Electron is the only browser that can be run headlessly in Cypress. *Videos are only recorded when running headlessly.*
- **Headed Mode** - No different from headless, except that a browser window pops open on the screen. All browsers, other than Electron, are run headed by passing the `--browser` flag to `cypress run`. You can manually run Cypress in `headed` mode by passing the flag `--headed` to `cypress run`. *Videos are not currently recorded when running headed.*
- **Interactive Mode** - This occurs after opening Cypress using `cypress open` or after clicking on Cypress after a manual download. You can click into a project and test and see the tests run in real time, open your console, and work as you would with other dev tools. When running Cypress in CI, it will *never* run in interactive mode. You select any browsers available on your OS to run Cypress in interactive mode.

**Comment by brian-mann** [comment]
We are mixing up and conflating headless and headed nomenclature with the way a browser is spawned. These things have nothing to do with each other.

In Cypress there are only two modes of operation:

Interactive Mode - where you write your tests and run a single or handful of tests. You can use snapshots and the process never exits. This is what you get with cypress open and its what you'll do during day to day development.
Run Mode - where you run your tests to completion and receive an exit code with the number of failures. In this mode - the browser may be spawned headlessly or headed. This mode is used when you want to run all of your tests - typically in CI.
The terms headless and headed are specific to the way a browser is spawned - and don't have much meaningful value to Cypress. Cypress doesn't care which way it's spawned - the same things will happen headlessly or headed.

The only difference today is that we only record videos when running Electron in headless mode. Recording videos of headed browsers is of course possible - and we already bundle ffmpeg to do this - but we haven't yet implemented that behavior.
