### ISSUE TITLE
  Integration test folder not existing 

### ISSUE THREAD

**Issue by msman** [cypress-io/cypress#1144]
I am following the tutorial video here but after installing cypress I didn't have the folder called integration. Is it necessary to create the test file inside folder to continue with the tutorial?

**Comment by bahmutov** [comment]
That sounds like a bug during scaffolding the cypress folder. What OS are you using? Have you tried opening Cypress actually? It creates cypress folder on the first run.

**Comment by brian-mann** [comment]
You mention "after installing Cypress" - but Cypress does not scaffold the folders here you actually **open** Cypress. Can you be specific about the exact steps you took? Something like...

1. `npm install cypress --save-dev`
2. `./node_modules/.bin/cypress open`
3. I saw **X* but I expected **Y**

**Comment by msman** [comment]
Integration test folder is existing on my root, I thought it is on my node_modules/cypress/

thanks to all

**Comment by anil826** [comment]
https://ide.c9.io <<  any support for this IDE.
