### ISSUE TITLE
Testing Symfony apps requiring environmental variables issue

### ISSUE THREAD

**Issue by szymach** [cypress-io/cypress#1145]
My [repository's Travis configuration](https://github.com/szymach/talesweaver/blob/flex/.travis.yml) and the failing  build on [Travis](https://travis-ci.org/szymach/talesweaver/builds/324726251)

- Operating System: Ubuntu 14.04
- Cypress Version: 1.3.2

### Is this a Feature or Bug?
Either a bug or me misunderstanding how to use environmental variables.

### Setup:
1. In Travis, I set an environmental variable called `APP_ENV` to `test`.
2. I run the PHP's build-in server and have Cypress perform tests through it. The tested app should access the `APP_ENV` variable and run in test environment.

### Issue 
The previously set variable does not exist in the process spawned by the Cypress test, which causes the wrong environment to be loaded. I have tried using Cypress' environmental variables (through `cypress.json` and the `--env` parameter in CLI), but it does not change anything. Please tell me if there is something I am doing incorrectly or is this a bug?

Cheers.

**Comment by jennifer-shehane** [comment]
> The tested app should access the APP_ENV variable and run in test environment.

Could you provide the code where you are later accessing the `APP_ENV` in Cypress? I wasn't able to find this in your repository. Or how you are determining that it is not available in the spawned process?

**Comment by brian-mann** [comment]
`Cypress.env(...)` only has access to environment variables which are prefixed with `CYRPESS_` when set via the command line (or in your case via Travis env vars).

Setting it with `--env` would make it available. `cypress run --env APP_ENV=test` would make it available.

You can test this all locally without travis to make things easier on yourself. You can even use `cypress open` which will log out all the env vars it received.

To simulate what you're doing in Travis you'd do: `APP_ENV=test cypress open` -- and you will see that Cypress does not see that as an env var

`CYPRESS_APP_ENV=test cypress open` would be available.

**Comment by brian-mann** [comment]
You can see what Cypress has access to the in GUI per this screenshot. 

https://docs.cypress.io/guides/references/configuration.html#Resolved-Configuration

**Comment by szymach** [comment]
Hey,
Thanks for the quick response. 

@jennifer-shehane I am sorry that I did not make that clear enough, but the variable is not being accessed by Cypress explicitly, instead it is read in the [PHP script](https://github.com/szymach/talesweaver/blob/flex/public/index.php#L27) which acts as the front controller for the app. It works for the CLI commands that are ran before it, but when Cypress runs that file via browser, the variable is no longer set. This is also the reason to why I am questioning my understanding of the whole thing - I am not quite sure how to use the two together. If this is not related to Cypress directly, then I apologize.

@brian-mann I do not wish to access the variable in Cypress, but to have it be available in the PHP process that is spawned when the browser opens the built-in server. Somehow that variable is cleared between previous CLI commands that I run and the browser opening the app. Do you mean that it will not be set at all without the `CYPRESS_` prefix or that simply it will not be accessible?

Thanks again for the help.

**Comment by brian-mann** [comment]
This line here: https://github.com/szymach/talesweaver/blob/flex/.travis.yml#L43 

That makes this available to Cypress, but Cypress only. It's not a real environment variable so it will not affect your server at all.

You need to export a real environment variable in your travis scripts, or when you invoke your server you need to set it for that process.

`APP_ENV=test bin/console server:start`

But honestly the easiest thing is just setting it inside of Travis Env Vars using their UI. Then its available to all processes. And if you want it available to Cypress just prefix it with `CYPRESS_`

**Comment by szymach** [comment]
I have [set it](https://github.com/szymach/talesweaver/blob/flex/.travis.yml#L22), which is exactly the reason why I do not understand it being missing. The line you have pointed out is me just trying various things to fix it, but thank you for clarifying that.

To conclude - if I have previously set the variable via the configuration line I have just given, it *should* still exist when the browser accesses the application, yes?

**Comment by brian-mann** [comment]
I'm now super confused. What do you mean by `process spawned by the Cypress test`

I'm confused how your problem has anything to do with Cypress at all. Are you trying to boot your server from within Cypress? Like a `cy.exec` or something?

What boots your server?

**Comment by brian-mann** [comment]
> To conclude - if I have previously set the variable via the configuration line I have just given, it should still exist when the browser accesses the application, yes?

These things don't have anything to do with one another. A browser application is a completely independent process from your server and it's configuration and access to environment variables. Imagine the browser could be on another machine 1,000 miles away connecting to your server. The environment variables you have set won't affect the browser at all. 

You should just be able to remove Cypress altogether from this and recreate your problem. It sounds like what you're saying is that your server doesn't have access to environment variables you're setting.

**Comment by szymach** [comment]
Oh boy, sorry for the mess.

Flow:
1. Set `APP_ENV=test` in `.travis.yml`.
2. Run the server from the CLI via command `bin/console server:start` (this is a PHP process). 
3. Run Cypress tests through the server spawned in the previous step.

Now, everytime as Cypress accesses the application through the server from step 2, the environment variable `APP_ENV` is read in the `public/index.php` file and since it is not set I have a problem. I know that that variable previously had been correctly set, because the commands prior to Cypress tests all read it properly. I hope this clears it up a bit. If not, I will close this issue and figure it out on my own, since I am not sure if I should be bothering you at all with this.

**Comment by brian-mann** [comment]
Right I think you could eliminate Cypress and still have the same problem. Replace item 3 with just a few  `curl` requests to some endpoints that your server exposes and check that the server has access to those variables and responds with what you expect. It's the same as Cypress making those requests.

**Comment by szymach** [comment]
Alright then, thank you for your time :) Have a nice evening/day (depending on where you are at now).
