### ISSUE TITLE
"The requested URL /__/ was not found on this server" after running the testcase within Cypress

### ISSUE THREAD

**Issue by tascioglu** [cypress-io/cypress#1147]
I read some issues on the site.. but not clear yet.. Have some issues with running my testcases .. 
i have two laptops.. one my own and one at work.. installed cypress (1.4) on both.. when I run my testcases on my own laptop, everything works..

but..

when i do it on my computer at work.. I get a message "The requested URL /__/ was not found on this server" after running the test with **chrome**.. There's opening a blank screen with this text

strange thing is, **it is working with electron**..
some people said it could be security limitations for chrome at work.. could it be? Or is it something else?

Please help me with this one..

- Operating System: windows / macbook
- Cypress Version: 1.4
- Browser Version: chrome 60 (tried with all different ones)

### Is this a Feature or Bug?
I think it's a Feature (problem)

### Current behavior:
"The requested URL /__/ was not found on this server"

### Desired behavior:
Just running the created testcase with cypress + chrome

**Comment by brian-mann** [comment]
We would need some test code to reproduce this problem. Without it there's nothing we can do.

**Comment by tascioglu** [comment]
For example this one.. 

It doesn't matter what's in the script.. I can't get tot the page what I visit

ps: I changed the url of the real website to google in this example


describe('EXAMPLE', function () {
  //Openen website
  it("Example click on map", function () {
    cy.visit('http://google.nl').wait(700)
  })

//Object op kaart selecteren 
    it('Select place', function(){
      //cy.get('div.map__mouse-position').click().debug()
      cy.get('.ol-unselectable').eq(3).invoke('show').click({ position: 'center' }).debug()
      //cy.click(231, 277)
      //cy.get('div.map').click()
      //cy.get('.ol-unselectable').wait(700).eq(1).click({ position: 'center' })
      //cy.get('.ol-viewport').wait(700).click({ position: 'center' })
      //cy.get('#map').wait(700).click({ position: 'center' })
      //cy.get('#map').wait(700).click({ position: 'center' }, {force: true })
      
    }) 
})

**Comment by eroetman** [comment]
I have reproduced this problem, it seems to be something with different domains.
My testsystem is in domain "company.local"
Tests run fine with Electron and Chrome as long as I stay in this domain. Test a site "myapo.company.local" works fine.
But when I try to test "myotherapp.companyinternal.local" or an external site (e.g. cypress.io) I get a 404 when using Chrome. Electron keeps working fine.

Searching for a solution now... setting "chromeWebSecurity": false did not fix it.

**Comment by jennifer-shehane** [comment]
@tascioglu I'm not able to reproduce the problem you describe with the code pasted above. 

My Cypress Version: 1.4.1
My Chrome Version: 63

<img width="794" alt="screen shot 2018-01-16 at 9 48 32 am" src="https://user-images.githubusercontent.com/1271364/34994751-83640320-faa2-11e7-9cb4-0358fc449fdd.png">

**I suppose it is possible this only happens on Chrome 60? Can you try updating Chrome and see if it works or updating Cypress to 1.4.1?**

As a side note, you should never need to add arbitrary waits to your Cypress test code. Here's some explanation on why and better ways to guard that your test is in the correct state to proceed. https://on.cypress.io/best-practices#Unnecessary-Waiting

**Comment by tascioglu** [comment]
Problem was something with proxy @ business. not an issue anymore. Closing this one.

**Comment by errogaht** [comment]
@tascioglu , please help us. we have the same problem. what is 'proxy @ business' ?
cypress adding /__/ to the end

**Comment by jennifer-shehane** [comment]
@errogaht If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run.
