### ISSUE TITLE
Getting cypress to run on redhat 6.9

### ISSUE THREAD

**Issue by BasieP** [cypress-io/cypress#1148]
- Operating System: Redhat 6.9
- Cypress Version: 1.4.1

In our (goverment) organisation we have to work with 'standard' linux machines. These are (unfortunately) Redhat 6.9.

I read the documentation about dependencies (https://on.cypress.io/required-dependencies) but they are only written for apt, and on redhat we have to use yum rpm's.
Now thanks to an other issue: (https://github.com/cypress-io/cypress/issues/660) i have been able to install yum equivalents to the apt packages, but that issue was made for Redhat 7.
(which doesn't run on our network since we have a .local tld)

The installation of the additional packages did solve some of the errors i got. But not all.
Unfortunate i still get this error:
```
/test/node_modules/cypress/dist/Cypress/Cypress: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /test/node_modules/cypress/dist/Cypress/Cypress)
/test/node_modules/cypress/dist/Cypress/Cypress: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /test/node_modules/cypress/dist/Cypress/Cypress)
/test/node_modules/cypress/dist/Cypress/Cypress: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /test/node_modules/cypress/dist/Cypress/Cypress)
/test/node_modules/cypress/dist/Cypress/Cypress: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /test/node_modules/cypress/dist/Cypress/libnode.so)
```
Is this something i can install? if so, what rpm should i use?

### Desired behavior:
working Cypress on redhat 6.9

**Comment by bahmutov** [comment]
you can try to run Cypress (or just plain Electron) on your system and keep adding missing dependencies until it starts. Take a look at our Docker images https://github.com/cypress-io/cypress-docker-images (like centos, ubuntu) for inspiration. I don't know how rpm installs would be equivalent to apt.

**Comment by davified** [comment]
Thanks @bahmutov. The link to https://github.com/cypress-io/cypress-docker-images helped me fix the missing dependencies issues i discovered when I was trying to run cypress tests on RHEL 7.4

I think it would be helpful if we could add a line in the [CI::Dependencies section](https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies) to list the dependencies for centos/redhat boxes. (`yum install gtk2 libXtst libXScrnSaver GConf2 alsa-lib` and we found `yum update glib2` was also necessary (see [link](https://bugs.centos.org/view.php?id=15495)))

Or at the very least, a reference to the [cypress-docker-images repo](https://github.com/cypress-io/cypress-docker-images) would be helpful.

**Comment by asherccohen** [comment]
Same here, spent all afternoon finding the CentOs libraries equivalent to the deb packages suggested in docs.

**Comment by aonamrata** [comment]
also I had to install `yum install gtk3` for the latest version

**Comment by hanukatreddy** [comment]
> yum install - y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

I am not able to find equivalent dependencies for RHEL 6. please confirm, you got equivalent packages on rpm?
