### ISSUE TITLE
Creating tests by recording keyboard/mouse input?

### ISSUE THREAD

**Issue by ffxsam** [cypress-io/cypress#1149]
Does Cypress have the ability to create tests based on keyboard & mouse input? I looked through the docs but didn't see anything relevant.

**Comment by jennifer-shehane** [comment]
No, there was some effort made towards the code required for this with our CSS Selector Wizard here: https://github.com/cypress-io/cypress/issues/917

This issue (https://github.com/cypress-io/cypress/issues/73) is basically what you are asking about, will defer to it and close this issue as duplicate.

**Comment by ben-wyss-enview** [comment]
I have not yet checked out these Chrome browser extensions, but they might fit the bill:
https://chrome.google.com/webstore/detail/cypress-recorder/glcapdcacdfkokcmicllhcjigeodacab?hl=en-US
https://chrome.google.com/webstore/detail/cypress-scenario-recorder/fmpgoobcionmfneadjapdabmjfkmfekb?hl=en-US
