### ISSUE TITLE
'Add Project' button breaks after unfocusing desktop app while folder viewer is open.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#115]
**Description**
In the desktop app, the 'Add project' button breaks if you unfocus the desktop app while choosing a project.

**Steps To Reproduce**
- [ ] Open Desktop App and click "Add Project"
- [ ] Click on a window in the background (like Chrome)
- [ ] Re-focus Desktop App and click "Add Project"

**Comment by brian-mann** [comment]
This is a bug in `electron` but just going to work around it.

https://github.com/atom/electron/issues/4849

**Comment by brian-mann** [comment]
Fixed in [`0.14.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0143-03202016).
