### ISSUE TITLE
to.have.ordered.members

### ISSUE THREAD

**Issue by kemalbayar** [cypress-io/cypress#1151]
#### Test code:

```js
const listTypes = ['Static', 'Statistical', 'State Tracker', 'LDAP/AL']

//Type selection and check if default list types exists
        cy.get('#type_selection').click()
        cy.get('.select2-results div').should(function($divs) {
            var arrayOfDivs = $divs.map(function (i, el) {
               return Cypress.$(el).get(0).innerText //instead can be used Cypress.$(el).text()
            })
            var arrayOfDivs = arrayOfDivs.get() //convert jquery object to an array (by overwriting / redefining)
            expect(arrayOfDivs).to.have.ordered.members(listTypes, 'Check the List Types')
        })
```

When I run the test...
```
Console Output:
Error:     CypressError: Timed out retrying: Cannot read property 'members' of undefined
```

I also check if the Divs innerText order are the same as listTypes variable and saw no problem

**Comment by bahmutov** [comment]
Interesting, do other assertions on the arrayOfDivs like length work?

**Comment by brian-mann** [comment]
This is part of chai `4.0`, and we use `3.5.0`. There were a bunch of breaking changes bumping up to `4` and they changed the way they did plugins as well.

I would close this issue and open a new one that just asks to update chai. This isn't really a bug.

**Comment by jennifer-shehane** [comment]
Opened issue for Chai update to 4.0 here: https://github.com/cypress-io/cypress/issues/1153
