### ISSUE TITLE
Cannot pick up typings for Cypress with the Typescript recipe

### ISSUE THREAD

**Issue by NoNameProvided** [cypress-io/cypress#1152]
- Operating System: MacOS High Sierra 10.13.2 
- Cypress Version: 1.4.1 (both package and binary)
- Browser Version: 63.0.3239.132 (Official Build) (64-bit)

### Is this a Feature or Bug?

Bug.

### Current behavior:

Cypress ships with bundled typings but the compiler cannot pick up the typings for Cypress and fails on encountering  a`cy` call.

### Desired behavior:

Typescript compiler can pick up the typings and test files compile successfully.

### How to reproduce:

1. Setup a vanilla cypress setup
2. Use the provided [typescript recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/preprocessors__typescript-webpack) 
3. Write an example spec file like:
    ```ts
    describe('Example', function () {
      it('Example task', function () {
        cy.visit('http://example.com');
    });
    ```
4. Observe the compiler failing on `cy`

#### Test code:

See above

### Additional Info (images, stack traces, etc)

```
./cypress/integration/REDACTED.spec.ts
[tsl] ERROR in REDACTED(3, 5)
      TS2304: Cannot find name 'cy'.
```

**Comment by bahmutov** [comment]
Does the tsconfig include Cypress?

**Comment by NoNameProvided** [comment]
I have a `tsconfig.json` file in `projectRoot/cypress/tsconfig.json` as the example shows: 

```json
{
  "extends": "../tsconfig.json",
  "include": [
    "integration/*.ts",
    "support/*.ts",
    "../node_modules/cypress"
  ]
}
```

**Comment by bahmutov** [comment]
Is this typescript compiler or typescript linter?

**Comment by NoNameProvided** [comment]
Both, VS code doesn't see the typings neither the compiler.

**Comment by arochat** [comment]
Hello,

I have the same kind of issue with Cypress and typescript. I followed what is explained here : https://www.cypress.io/blog/2017/12/11/an-alternative-to-protractor-for-angular-projects/#Scaffolding-a-project in my own project.
When running the test it fails with errors like those : 

[...]/node_modules/cypress/types/index.d.ts
error TS2503: Cannot find namespace '_'.
[...]/node_modules/cypress/types/index.d.ts
error TS2304: Cannot find name 'JQuery'.

What am I missing ?
Thanks in advance

**Comment by bahmutov** [comment]
I wonder if TypeScript compiler does not find types for some reason. Like it does not see the included files referenced from non-root `tsconfig.json` for example? I don't know why that would be the case though.

```
  "include": [
    "../../node_modules/cypress",
    "cypress/*/*.ts"
  ]
```

**Comment by kandros** [comment]
same situation with vscode.

**Comment by mkatrenik** [comment]
@bahmutov aren't your files in nested directories? If that's the case, change this in `include` property `cypress/**/*.ts`.

**Comment by guetar** [comment]
Any resolution? Experiencing the same issue here (and it has nothing to do with nested paths, tried the solution above)

**Comment by brian-mann** [comment]
We have this other issue that explains this... https://github.com/cypress-io/cypress/issues/1236

**Comment by bahmutov** [comment]
One thing that helps a lot for JS and TS specs is adding a comment to manually tell where the `cypress` types are coming from 

```
/// <reference types="cypress" />
```
At least in VSCode the types start working, here is IntelliSense when hovering over `cy.visit`

![intellisense-vscode](https://user-images.githubusercontent.com/2212006/37663953-bf43620e-2c30-11e8-9e8e-28863f7682b3.jpeg)

**Comment by NicholasBoll** [comment]
Try adding `"types": ["cypress"]` to the tsconfig.json file under the Cypress directory. That worked for me. That should do the same thing as the reference directive @bahmutov suggested, but for all TS files.

**Comment by guetar** [comment]
Thanks so much! /// <reference types="cypress" /> worked for me, however, all tsconfig.json patches did not :(

**Comment by NicholasBoll** [comment]
@guetar A duplicate identifier like the is probably because you use Chai in your project. Cypress is currently using `@types/chai@4.0.8`. If your project also uses `@types/chai`, but your version is incompatible with 4.0.8, your package manager (yarn or npm) will nest `@types/chai` under `node_modules/cypress/node_modules` - meaning you'll have 2 versions of chai type definitions. Since it is a namespace (global), TypeScript will throw a duplicate identifier.

One of the solutions that worked well for me in this case (duplicate definitions) was to have a `tsconfig.json` inside the `cypress` folder that looked like this:

```json
{
  "extends": "../tsconfig",
  "compilerOptions": {
    "baseUrl": "../node_modules",
    "target": "es5",
    "types": ["cypress"],
  },
  "include": [
    "**/*.ts"
  ]
}
```

The `extends` is useful if you have a base `tsconfig.json`. Without it, you'll have to determine your own compiler options for the `cypress` directory.

A nuclear option would be to add `skipLibCheck` set to `true` which will disable TypeScript type checking inside lib files.

**Comment by NoNameProvided** [comment]
Adding `/// <reference types="cypress" />` in top of every file solves the issue, playing around with tsconfig does not. For me maybe an extension messes up something.

**Comment by jennifer-shehane** [comment]
I'm just dropping into this thread, but - would it not be helpful to keep [@types/cypress](https://www.npmjs.com/package/@types/cypress) npm package published as this is the preferred way to handle types in TypeScript? It could help people who are struggling with hooking up the types from within Cypress' install - I know it should be unnecessary for most though.

**Comment by bahmutov** [comment]
No, having to install separate `@types/cypress` would be a huge pain. Most packages that have types just include them (like we do).

**Comment by jennifer-shehane** [comment]
Well, it seems that Vue.js does the same, includes types in core, but their [configuration](https://vuejs.org/v2/guide/typescript.html) does not require defining `types`, `baseUrl`, `includes`. So, I'm just wondering what the discrepancy is? Why is ours so much more difficult to set up?

**Comment by bahmutov** [comment]
because for us the main things that cause problems
- global reference to `cy` which requires configuration (vs `import vue from 'vue'`)
- conflicts with other global test things like Jest that also use `expect` and stuff like that :(

**Comment by jennifer-shehane** [comment]
Yeah, I was just getting to this conclusion in my reading. :/ Thanks.

**Comment by rcwestlake** [comment]
Not sure this will solve it for other folks, but I was able to get around this error by updating my root `tsconfig.json` to exclude cypress (see very bottom of exclude):

```
"exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "cypress"
  ]
```

**Comment by jennifer-shehane** [comment]
There are new docs explaining how to configure TypeScript support. We would love any feedback on whether our recommended setup solves the issues laid out in this issue. https://on.cypress.io/typescript-support

There is also a new issue open proposing more "native" support of TypeScript (less config) if anyone has suggestions they'd like to add there: https://github.com/cypress-io/cypress/issues/1859

I am closing this issue, but please feel free to comment here again with any feedback/confusion!

**Comment by Knaledge** [comment]
@jennifer-shehane - I'm running into an issue with code completion / Intellisense (VS Code) that feels akin to what is being described here. Per your recommendation, I'm adding a comment in the hopes that you'll see it - especially since I am following right along with the docs (as you suggested :) 

**Environment**
- macOS High Sierra (10.13.6)
- VS Code (Insider, 1.27.0-insider, 2018-09-03T09:01:07.649Z) 

**Install**

1. Log in to macOS (user account)
2. Open "terminal.app"
3. brew install node
4. npm install -g cypress
5. npm install -g eslint
6. npm install -g eslint-plugin-chai-friendly
7. npm install -g eslint-plugin-cypress
8. npm install -g jshint

RESULT
`My-User:~ myuser$ ll -a /usr/local/lib/node_modules/
total 0
drwxr-xr-x   8 myuser  admin   256B Sep  5 11:04 .
drwxrwxr-x  18 myuser  admin   576B Sep  4 14:40 ..
drwxr-xr-x   9 myuser  admin   288B Sep  4 14:52 cypress
drwxr-xr-x  11 myuser  admin   352B Sep  5 10:54 eslint
drwxr-xr-x   7 myuser  admin   224B Sep  5 11:04 eslint-plugin-chai-friendly
drwxr-xr-x   7 myuser  admin   224B Sep  5 10:58 eslint-plugin-cypress
drwxr-xr-x  11 myuser  admin   352B Sep  4 14:41 jshint
drwxr-xr-x  24 myuser  admin   768B Sep  4 14:40 npm`

**Setup - Cypress**

1. Open "terminal.app"
2. mkdir /users/my-user/_CYPRESS
3. cd /users/my-user/_CYPRESS
4. npx cypress open

RESULT (~/_CYPRESS)
`My-User:~ myuser$ ll -a /users/myuser/_CYPRESS/
total 24
drwxr-xr-x   7 myuser  staff   224B Sep  5 11:00 .
drwxr-xr-x+ 67 myuser  staff   2.1K Sep  4 11:58 ..
drwxr-xr-x   8 myuser  staff   256B Sep  5 10:56 cypress
-rw-r--r--@  1 myuser  staff     3B Sep  4 14:53 cypress.json`

RESULT (~/_CYPRESS/cypress)
`My-User:~ myuser $ ll -a /users/myuser/_CYPRESS/cypress
total 16
drwxr-xr-x  8 myuser  staff   256B Sep  5 10:56 .
drwxr-xr-x  7 myuser  staff   224B Sep  5 11:00 ..
drwxr-xr-x  3 myuser  staff    96B Sep  4 14:53 fixtures
drwxr-xr-x  5 myuser  staff   160B Sep  4 14:56 integration
drwxr-xr-x  3 myuser  staff    96B Sep  4 14:53 plugins
drwxr-xr-x  5 myuser  staff   160B Sep  4 14:56 support`

**Setup - tsconfig.json**

1. Open "terminal.app"
2. nano /users/my-user/_CYPRESS/cypress/tsconfig.json
3. Add the following to the file, then save:
`{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": "../node_modules",
    "types": [
      "cypress"
    ]
  },
  "include": [
    "**/*.*"
  ]
}`

**Setup - .eslintrc.json**

1. Open "terminal.app"
2. nano /users/my-user/_CYPRESS/cypress/.eslintrc.json
3. Add the following to the file, then save:
`{
  "plugins": [
    "cypress",
    "chai-friendly"
  ],
  "env": {
    "cypress/globals": true
  },
  "rules": {
    "no-unused-expressions": 0,
    "chai-friendly/no-unused-expressions": 2
  }
}`

**VS Code**
1. Launch VS Code
2. Open /users/myuser/_CYPRESS/cypress/integration/examples/actions.spec.js

**ISSUES**
- Type "cy.get" - note that code completion / Intellisense is not triggered

- Display VS Code's "Output" pane (View -> Output | shift + command + U) 
- Note the following message is displayed: 
> Cannot find type definition file for 'cypress'.

**Comment by bahmutov** [comment]
@Knaledge is there a reason you install Cypress globally? Do the types work when installing locally?

**Comment by Knaledge** [comment]
@bahmutov As mentioned in Gittr, I sincerely appreciate the time you've spent having a look at this (especially with an artifact of a separate "story" / issue). 

For my particular circumstance, there's no "project" at the moment - I simply have Cypress installed on my Mac (via npm) and just write my tests in VS Code, then export to the development VM / commit to repo when they are more or less reviewed/tested/ready. The target application does not use node, so a lot of what I'm doing is: API testing, UI sanity, and general feature verification.

All that said, I could also just install Cypress "locally" (in a "project" folder - like _CYPRESS). I actually did have that set up - but I was still not getting Intellisense (code completion) working in VS Code. 

When I started over, I went back a global install as it felt cleaner and made more sense. 

All that said - what _do_ I put into tsconfig.json ? It seems there are a lot of assumptions in the docs that Cypress is installed locally (i.e. not globally installed) - but it's not clear when that matters. Just an observation, not a knock (as I absolutely love your docs).

**Comment by ashnur** [comment]
Happens with local install too.  Interesting how such a minor thing can go on for many many months without getting resolved.

**Comment by jennifer-shehane** [comment]
It shouldn't be necessary if you've set up everything the way the TypeScript Doc laid out.

**Comment by NicholasBoll** [comment]
@ashnur I've noticed sometimes the Typescript server needs to be restarted (cache invalidation issue). You can do this by either from the command palette `Cmd/Ctrl+Shift+P` and type `Restart Typescript server` or restart VS Code.

**Comment by abannsunny** [comment]
> @guetar A duplicate identifier like the is probably because you use Chai in your project. Cypress is currently using `@types/chai@4.0.8`. If your project also uses `@types/chai`, but your version is incompatible with 4.0.8, your package manager (yarn or npm) will nest `@types/chai` under `node_modules/cypress/node_modules` - meaning you'll have 2 versions of chai type definitions. Since it is a namespace (global), TypeScript will throw a duplicate identifier.
> 
> One of the solutions that worked well for me in this case (duplicate definitions) was to have a `tsconfig.json` inside the `cypress` folder that looked like this:
> 
> ```json
> {
>   "extends": "../tsconfig",
>   "compilerOptions": {
>     "baseUrl": "../node_modules",
>     "target": "es5",
>     "types": ["cypress"],
>   },
>   "include": [
>     "**/*.ts"
>   ]
> }
> ```
> 
> The `extends` is useful if you have a base `tsconfig.json`. Without it, you'll have to determine your own compiler options for the `cypress` directory.
> 
> A nuclear option would be to add `skipLibCheck` set to `true` which will disable TypeScript type checking inside lib files.

This worked for me! Thank you!

**Comment by arichter83** [comment]
Just a quick note for **Atom**: the second `cypress/tsconfig.json` with `"types": ["cypress"]` and `"extends": "../tsconfig",` was only recognized after restart.

**Comment by jakeleboeuf** [comment]
> Adding `/// <reference types="cypress" />` in top of every file solves the issue, playing around with tsconfig does not. For me maybe an extension messes up something.

This was my issue- prettier is formatting that to `// / <reference types="cypress" />` 😭

**Comment by GentryRiggen** [comment]
Here is what I use and I do not have to add `/// <reference types="cypress" />` at the top of every file.

I have my custom typings under `<projectroot>/cypress/support/index.d.ts`
```
/// <reference types="cypress" />

declare namespace Cypress {
  interface Chainable<Subject> {
    getByDataTest(tag: string): Chainable<any>
  }
}

```

And my `<projectroot>/cypress/tsconfig.json` looks like

```
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"],
    "typeRoots": ["./support"]
  },
  "include": ["**/*.ts"]
}
```

And TypeScript is finally happy
```
describe('when I want to select by data test tag', () => {
  it('should select by data test tag', () => {
    cy.getByDataTest('yolo').should('exist')
  });
});
```

**Comment by scipper** [comment]
@GentryRiggen added the reference works. sadly a bit of additional coding.

**Comment by sarink** [comment]
I finally figured out that, for some reason, awesome-typescript-loader is incompatible with the cypress-webpack-preprocessor-plugin, and throws these errors. Switching to ts-loader fixed things for me.

**Comment by Benny739** [comment]
I had the same error. Adding the following to my tsconfig.json solved the problem for me.
```
    "types": [
      "./support/index"
    ]
```

**Comment by MikeAski** [comment]
> Adding `/// <reference types="cypress" />` in top of every file solves the issue, playing around with tsconfig does not. For me maybe an extension messes up something.

Simply adding `/// <reference types="cypress" />` once in `cypress/support/index.js` made the tick for me.

**Comment by azollai** [comment]
After trying all the solutions above, I just had to mix the two most useful comments for me by @NicholasBoll :

https://github.com/cypress-io/cypress/issues/1152#issuecomment-374930065
https://github.com/cypress-io/cypress/issues/1152#issuecomment-435560901

...and it works as it should. : ) 👍

**Comment by leon0707** [comment]
> I had the same error. Adding the following to my tsconfig.json solved the problem for me.
> 
> ```
>     "types": [
>       "./support/index"
>     ]
> ```

What is in the support/index file?

**Comment by govindrai** [comment]
The `checkJs` option did it for me. We don't use TS at our shop, all our files are .js, but we like TS linting because it saves our butt all the time. 
```
{
    "compilerOptions": {
        "checkJs": true,
        "target": "es5",
        "lib": [
            "es5",
            "dom"
        ],
        "types": [
            "cypress"
        ]
    },
    "include": [
        "**/**.js"
    ]
}
```

**Comment by BrunoElo** [comment]
[Link to docs for typescript support](https://docs.cypress.io/guides/tooling/typescript-support)

**Comment by Arkady-Skvortsov** [comment]
> Adding `/// <reference types="cypress" />` in top of every file solves the issue, playing around with tsconfig does not. For me maybe an extension messes up something.

It's really helping :); Thank you very much!)

**Comment by mdarif** [comment]
Even in it does exist in June 2022 after setting it up correctly.

**Comment by mdarif** [comment]
One has to follow the below step after making the necessary config changes:

You may have to restart your IDE's TypeScript server if the setup above does not appear to work. For example:

VS Code (within a .ts or .js file):

- Open the command palette (Mac: cmd+shift+p, Windows: ctrl+shift+p)

- Type "restart ts" and select the "TypeScript: Restart TS server." option

If that does not work, try restarting the IDE.

**Comment by coler-j** [comment]
Is anyone able to import `json` files with this configuration? I get "cannot import .....json or its corresponding types", I have added `resolveJsonModule: true` to my tsconfig.

**Comment by tetranoir** [comment]
Just fyi, if youre using yarn, in a nested project, you may need to download the node_modules in that nest project (I used npm install) for typescript to find the types

**Comment by mauchacon99** [comment]
My solution was to install the package 

`yarn add eslint-plugin-cypress --dev` 


and in my configuration file .eslintrc.json

```js
{
    "env": {
      "cypress/globals": true
   },
   "plugins": [
      "cypress"
   ],
}
```

**Comment by tylim88** [comment]
`"types": ["cypress"]` pick up the typing

but how is this possible because there is no `@types/cypress`
