### ISSUE TITLE
Update Cypress to use Chai 4.0 instead of 3.5

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1153]
- Cypress Version: 1.4.1

### Is this a Feature or Bug?
Feature

### Current behavior:
There have been some new methods that were introduced to Chai between 3.5 & 4.0, but Cypress still uses 3.5. Current version of Chai 4.1.2 and have some more bug fixes and ES6 fixes.

### Desired behavior:
**Ability to use updates in Chai 4.0:**
- Add `ordered` assertion: `to.have.ordered.members`
- Throw when non-existent property is read. `expect(true).to.be.ture; // Oops, typo, now Chai will throw an Error`
- Have suggestions on typos. `expect(false).to.be.fals; // Error: Invalid Chai property: fals. Did you mean "false"?`
- Use `by` with `increase`, `change` `decrease`. `expect(increaseByTwo).to.increase(obj, 'val').by(2)`
- Use `does` and `but` as new no-op assertion.

### How to reproduce:
**Test Code**
```js
expect([1, 2]).to.have.ordered.members([1, 2])
```

**Resulting Error**
```
CypressError: Timed out retrying: Cannot read property 'members' of undefined
```

**Comment by lilaconlee** [comment]
Covered by #2529

**Comment by Swati-activeops** [comment]
Hi, I am using cypress@3.4.0 and still getting the same error
![image](https://user-images.githubusercontent.com/50127497/60988401-71d9ae00-a33b-11e9-8bdc-8904867f43e8.png)

**Comment by jennifer-shehane** [comment]
@Swati-activeops The code for this is done in https://github.com/cypress-io/cypress/pull/2862, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

Sorry for the confusion.
