### ISSUE TITLE
When test title contains text wrap in quotes, quoted text appears in test runner instead of "TEST"

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#1157]
- Operating System: Windows 10
- Cypress Version: 1.4.0
- Browser Version: 62

### Is this a Feature or Bug?
I cant tell if this is a Feature or a Bug, LOL

### Current behavior:
Test title contains a word in quotes. this then appears in the runner. 

### Desired behavior:
Well its not really undesirable perse, but confusing and it seems unintentional.

### How to reproduce:
Put a word in quotes in your test title

#### Test code:

```js
it.only('should not "lala" ...', () => {
```

### Additional Info (images, stack traces, etc)

![image](https://user-images.githubusercontent.com/2848185/34631077-c3e2c562-f23c-11e7-9588-29aa0bc45ed4.png)

**Comment by chrisbreiding** [comment]
Wow, that's certainly odd and not intended. 

@brian-mann I think this originates in the driver, since all the reporter does is display the `hookName` of the test log.
