### ISSUE TITLE
--spec option should be normalized against cwd and not projectRoot

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1159]
When invoking cypress from a PWD other than the current `projectRoot` and using a relative path - it will fail to find the spec file because we resolve the path using `projectRoot` instead of `process.cwd`

This behavior needs to move into the `cli` so it normalizes specs to absolute paths prior to handing them off.

**Comment by bahmutov** [comment]
Yeah good point

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
