### ISSUE TITLE
cy.dblclick() should accept same options as cy.click()

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#116]
`cy.dblclick()` currently will serially double click all of the current subjects. `cy.dblclick()` needs to accept options:
- `multiple`
- `force`
- `interval`

It also needs to accept `position` and `x`,`y` coordinate arguments.

**Comment by mounikauday** [comment]
> `cy.dblclick()` currently will serially double click all of the current subjects. `cy.dblclick()` needs to accept options:
> 
> * `multiple`
> * `force`
> * `interval`
> 
> It also needs to accept `position` and `x`,`y` coordinate arguments.

currently I am facing this problem to test my project

**Comment by Jero786** [comment]
+1 ... I need too :(
>  also needs to accept position and x,y coordinate arguments.
