### ISSUE TITLE
cy.visit fails on *.github.io websites due to CORS

### ISSUE THREAD

**Issue by bootstraponline** [cypress-io/cypress#1161]
- Operating System: Windows 10
- Cypress Version: 1.4.1
- Browser Version: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

### Is this a Feature or Bug?

Feature.

### Current behavior:

Cypress is not able to automate *.github.io websites for repos.

### Desired behavior:

`cy.visit` succeeds.

### How to reproduce:

Run the test.

#### Test code:

```js
describe('My First Test', function() {
  it('Does not do much!', function() {
    cy.visit('https://bootstraponline.github.io/hex/')
  })
})

```

### Additional Info (images, stack traces, etc)
![image](https://user-images.githubusercontent.com/1173057/34646908-1907f64c-f342-11e7-9f35-4f6a67c3a5b5.png)

**Comment by brian-mann** [comment]
The root cause of this is because `github.io` is on the public suffix which we have to utilize to make these work. There's a couple issues for this already open:

- https://github.com/cypress-io/cypress/issues/802
- https://github.com/cypress-io/cypress/issues/402

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).

**Comment by bootstraponline** [comment]
that link resolves to localhost

**Comment by brian-mann** [comment]
Fixed, thx
