### ISSUE TITLE
Cypress test login via GitHub impossible with U2F keys

### ISSUE THREAD

**Issue by bootstraponline** [cypress-io/cypress#1162]
### Current behavior:

Log in errors.

### Desired behavior:

Log in works.

### How to reproduce:

Log in with a GitHub account that has U2F enabled using a hardware key.

### Additional Info (images, stack traces, etc)

![image](https://user-images.githubusercontent.com/1173057/34646935-d64268b4-f342-11e7-9f00-ce38646f4924.png)

- Operating System: Windows 10
- Cypress Version: 1.4.1
- Browser Version: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by brian-mann** [comment]
Are you referring to logging into Github while inside of our Desktop Application?

**Comment by bootstraponline** [comment]
> Are you referring to logging into Github while inside of our Desktop Application?

Yes

**Comment by bahmutov** [comment]
Wait this is not regular 2FA - we use it ourselves. This looks like hardware second factor (press the button).

**Comment by bootstraponline** [comment]
Right, 2FA with hardware security keys doesn't work.

**Comment by jennifer-shehane** [comment]
This appears to be an issue with Electron apps in general and we would need this issue to be fixed for this to work: https://github.com/electron/electron/issues/3226
