### ISSUE TITLE
Aggregate stats ourselves, do not rely on mocha reporters

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1163]
Currently we rely on the mocha reporter's `stats` object to return us the stats related to a single run. We use this when displaying the final results of a run.

This is problematic because it may differ on custom reporters (which are not consistent with the base reporter) and we also disagree with the mocha semantics for things like counting the number of `tests`.

Tests to mocha are actual **test runnables** that must reach their `test end` event to being counted. This means that failures occurring in `hooks` they do not increment this number - which makes no sense.

In Cypress we consider the test body itself and **all associated hooks** to be one discrete "test". In our UI we show tests failing on their hooks (and provide you visual indicators). 

Since we've already gone through all the trouble of making the UI represent this - it's necessary for us to aggregate the stats ourselves during a `cypress run` so we can accurately provide you the same stats (including for our Dashboard).

**Comment by brian-mann** [comment]
We're now counting and aggregating the following ourselves:

- Suites
- Tests
- Failures
- Passes
- Pending
- Skipped

We now properly handle these counts even when hooks fail (mocha incorrectly reports these).

**Comment by JPHamlett1993** [comment]
Can't wait for this, had to stop using mochawesome because of fails passes
