### ISSUE TITLE
Email / submit GH issue straight from the test runner

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1173]
# new feature

When working in opened test runner and hitting a test failure, it would be so useful to send an error email or open a github issue with _all_ relevant details (test, steps, XHRs, exception, screenshot) with a single button push. Probably would require dashboard service though.

**Comment by jennifer-shehane** [comment]
I'm going to close this due to inactivity / seemingly lack of interest behind this feature. If we find there is more support for this feature in the future, we can reopen. (Add 👍 to main comment if you want this)
