### ISSUE TITLE
multiple domain exceptions with 2nd level sub domains

### ISSUE THREAD

**Issue by datpham23** [cypress-io/cypress#1175]
### Is this a Feature or Bug?
Bug

### Current behavior:
I want to test an app deployed at https://apphost.lab.domain.com.
1. When visiting my app https://apphost.lab.domain.com i'm redirected to an internal single sign on (SSO) at https://sso-host.dc1.domain.com 
2. I log in and then i'm redirected back to my app https://apphost.lab.domain.com.
3. When I issue the command cy.visit('/some-path') I run into the multiple domain exceptions.

"...The previous domain you visited was: 'https://sso-host.dc1.domain.com'
You're attempting to visit this new domain: 'https://apphost.lab.domain.com' ..."

### Desired behavior:
Should be able to issue cy.visit('/some-path') without exception.

#### Test code:

```js
cypress.json
{
  "baseUrl" : "https://apphost.lab.domain.com/"
}

describe('Test', ()=>{
  before(()=>{
    cy.visit('/');
   //Redirected to single sign on page
    cy.get('#username').clear().type(Cypress.env('userName'));
    cy.get('#password').clear().type(Cypress.env('userPassword'));
    cy.get('#submit').click();
   //after logging in i'm redirected to my app at https://apphost.lab.domain.com/
  });

  it('show /my-page', ()=>{
    cy.visit('/my-page');  //exception occurs
  });
```

### Additional Info (images, stack traces, etc)
Even though the sso host and app host is in the same sub domain i'm still seeing the multiple super domain exception. 
Ideally we should just allow multiple super domains. Due to how our SSO work we can only be authenticated going through the browser, we can't simply make cy.request() to grab the token/cookie and manually set it our session.

**Comment by brian-mann** [comment]
Also related to https://github.com/cypress-io/cypress/issues/600

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).

**Comment by datpham23** [comment]
Still facing this issue with version 2.1.0.
```
You may only visit a single unique domain per test.
Different subdomains are okay, but unique domains are not.

The previous domain you visited was: 'https://single-signon.corp.company.com'
You're attempting to visit this new domain: 'https://app-host.company.com'
```

**Comment by haiquan** [comment]
Still facing this issue with version 3.3.1.

```
CypressError: cy.visit() failed because you are attempting to visit a second unique domain.
You may only visit a single unique domain per test.
Different subdomains are okay, but unique domains are not.
The previous domain you visited was: 'https://frontend.company.net'
You're attempting to visit this new domain: 'https://backend.company.net'
You may need to restructure some of your code to prevent this from happening.
https://on.cypress.io/cannot-visit-second-unique-domain
```

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
