### ISSUE TITLE
Having to log in within every test - is this normal?

### ISSUE THREAD

**Issue by ffxsam** [cypress-io/cypress#1177]
I noticed that I need to log in within every single test. Is this expected, or am I doing something wrong?

So I've made my own Cypress command called `login` which fills out the login form with a test user account and signs in. And that command is executed in `beforeEach` before a series of tests.

**Comment by jennifer-shehane** [comment]
This is our recommended way to test. This ensures isolation of state between tests. https://on.cypress.io/best-practices#Having-tests-rely-on-the-state-of-previous-tests
