### ISSUE TITLE
Debugging cypress steps on terminal (headless mode)

### ISSUE THREAD

**Issue by chit786** [cypress-io/cypress#1180]
- Operating System: MAC OS HIGH SIERRA
- Cypress Version: 1.2.0
- Browser Version: 63

### Is this a Feature or Bug?
Question

### Current behavior:
No option to see what cypress is doing behind the scene or headlessly

### Desired behavior:
a way to pass --debug to the CLI to see the cypress processes and probably to debug which process is time consuming

**Comment by jennifer-shehane** [comment]
You can do `DEBUG=cypress:* cypress run` as outlined here: https://on.cypress.io/debugging#Debug-the-Command-Line

**Comment by castaway** [comment]
This "debug the command line", doesn't seem to exist on that doc page any more, did it move?

**Comment by castaway** [comment]
Aha nevermind, it moved to https://docs.cypress.io/guides/guides/command-line.html#Debugging-commands (mebbe a link between the two? or did I miss one)

**Comment by jennifer-shehane** [comment]
The info was moved to our Troubleshooting guide https://on.cypress.io/troubleshooting#Print-DEBUG-logs
