### ISSUE TITLE
Cypress silently hangs when no text provided in describe/context

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1181]
- Cypress Version: 1.4.1

### Current behavior:
Cypress runs first test,  then silently hangs and never moves onto second test within `describe`/`context` with no text provided.

### Desired behavior:
At least throw an error that the test was written incorrectly.

#### Test code:

```js
describe('', () => {
  it('First visit', () => {
    cy.visit('https://example.cypress.io')
  })
  it('Second visit', () => {
    cy.visit('https://example.cypress.io/commands/querying')
  })
})
```

### Additional Info (images, stack traces, etc)

**19 seconds into test, just runs forever**
<img width="772" alt="screen shot 2018-01-10 at 10 59 17 am" src="https://user-images.githubusercontent.com/1271364/34782131-bcc6a46c-f5f5-11e7-8e43-0d27db6e6c6b.png">

**Error in console**
<img width="474" alt="screen shot 2018-01-10 at 10 59 29 am" src="https://user-images.githubusercontent.com/1271364/34782150-c9b77a5c-f5f5-11e7-8c87-ec5b030fae35.png">

**Comment by bahmutov** [comment]
I believe https://github.com/cypress-io/cypress/pull/973 throws error for this case, but needs some development love to be merged in

**Comment by jennifer-shehane** [comment]
This is still happening in 3.4.0

**Comment by jennifer-shehane** [comment]
Closing as resolved. This no longer happens.

<img width="580" alt="Screen Shot 2021-02-05 at 2 14 50 PM" src="https://user-images.githubusercontent.com/1271364/107004354-8d799480-67bc-11eb-81ca-9a29ee263eff.png">


If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
