### ISSUE TITLE
TypeScript error using Cypress.on or cy.on

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#1186]
- Operating System: N/A
- Cypress Version: 1.4.1
- Browser Version: N/A

### Is this a Feature or Bug?
Bug? But also a Feature for better TypeScript support and type documentation for JavaScript

### Current behavior:
TS error using `Cypress.on()` or `cy.on()`

### Desired behavior:
Support for the different events including typed callbacks. This should help with the API in JavaScript as well

### How to reproduce:
See "Test code"

#### Test code:
```ts
Cypress.on('uncaught:exception', (err) => {
  return false
})
```
This will fail with an error like `Property 'on' does not exist on type 'Cypress'`

I have a PR coming to address this issue.

**Comment by bahmutov** [comment]
Thanks for noticing this!
