### ISSUE TITLE
Cypress.on('fail') does not fail tests

### ISSUE THREAD

**Issue by JPHamlett1993** [cypress-io/cypress#1200]
- Operating System: Mac OS
- Cypress Version: 1.4.2 technically
- Browser Version: Chrome

### Is this a Feature or Bug?
Not sure

### Current behavior:
When the test fails it enters Cypress.on('fail') does the commands in the function then the test passes

### Desired behavior:
For the test to fail

### How to reproduce:
Have a test fail with this override

#### Test code:

```js
const addContext = require('mochawesome/addContext')

Cypress.on('fail', function(err, runnable) {
	console.log(this)
	addContext(runnable.ctx, 'https://www.google.com')
})
```

**Comment by JPHamlett1993** [comment]
I can just throw err

**Comment by pkruhlei** [comment]
@JPHamlett1993 was you able to actually add some content to mochawesome report? maybe I'm doing something wrong, but for some reasons I cannot add anything

**Comment by Trykon** [comment]
I know that it is supposed to be closed, but is there any way to fail the test while using `Cypress.on('fail', ...` like `return false` or `throw err`. When in debugger, test is marked as not completed (neither red, nor green), so there should be, in theory, option to affect result.

**Comment by jiangjunfeng98** [comment]
@JPHamlett1993  @pkruhlei  Can you use `addContext`  success? I can't add new content to the report
