### ISSUE TITLE
xhr request is getting cached

### ISSUE THREAD

**Issue by Br3d89** [cypress-io/cypress#1202]
- Operating System:
macOS
- Cypress Version:
Beta Version 1.4.1
- Browser Version:
Chrome 63.0.3239.132

Hello, I have similar to #65 issue behaviour, when running same test few times (`cy.wait` fails).

Here is my test_spec.js:

```js
describe('test1', function () {
    before(function (){
        cy.server();
        cy.route('POST', 'getData', {testData: 1}).as('testData');
      })
    });

    it('Observe Creation Date', function () {
        cy.visit('/testUri/test');
        cy.wait('@testdata');
      });
 });
```

Here is my cypress.json:
```json
{
"baseUrl": "http://mytestSite.com",
"viewportHeight": 1080,
"viewportWidth": 1920,
"chromeWebSecurity": false,
}
```

I even don't see any xhr requests in Cypress commands window :
![image](https://user-images.githubusercontent.com/10284409/35095494-50f0885e-fc51-11e7-8f9a-72c0c297120d.png)

After clearing browser history test runs fine:
![image](https://user-images.githubusercontent.com/10284409/35095541-7a376200-fc51-11e7-9bf9-e0a0b53a51cd.png)

Also if I run Cypress on localhost environment (baseUrl: http://localhost:8080) which redirects all requests from http://localhost:8080 to http://mytestSite.com, there is no such problem.

**Comment by Br3d89** [comment]
@jennifer-shehane  how I can help you to speed up investigation ?

**Comment by jennifer-shehane** [comment]
We intend to rework a lot of how we clear things like browser history with this proposal: #686 

You can likely hook into Cypress events to handle clearing what you need as a workaround for now. https://on.cypress.io/catalog-of-events#Window-Before-Load

**Comment by brian-mann** [comment]
@Br3d89 for us to investigate this issue we must have a reproducible repo. As it stands from looking at your code there's no reason for this not to work. Cypress has likely hundreds of tests around the XHR stubbing behavior so we'd need a way to see it failing.

**Comment by jennifer-shehane** [comment]
Closing as stale. Please comment if you are still having this issue and we will consider reopening.
