### ISSUE TITLE
Prevent a form from submitting

### ISSUE THREAD

**Issue by weskor** [cypress-io/cypress#1203]
Probably a simple question. We have a form somewhere on a page and when the user submits the form the browser will go to a different URL of a website that is not maintained by us. Is there a way to stop this behaviour?

The desired behaviour would be: Cypress sees that the form is submitted. preventDefault and returns that there was a form submit.

**Comment by bahmutov** [comment]
You can attach event listener to the form and stop the event, no? For example in https://github.com/bahmutov/cypress-form-data-with-file-upload/blob/d1b741253a5df1dcf16636e88a045c98330126f7/index.js#L18

```js
cy.get('form').then(form$ => {
  form$.on('submit', e => {
    e.preventDefault()
 })
})
```

**Comment by weskor** [comment]
Thanks for the answer! that works :).

**Comment by melibe23** [comment]
Hey, Can I see the code? I need the same but for pressing {enter} and I am sure I am doing something wrong because it doesnt work.

**Comment by julienreszka** [comment]
Same problem here
