### ISSUE TITLE
failed to install on windows machine

### ISSUE THREAD

**Issue by tzookb** [cypress-io/cypress#1204]
- Operating System: Windows
- Cypress Version: 
- Browser Version: Chrome 63.0.3239.132

### Current behavior:
Just introduced Cypress to the QA team and it in some of the QA pc's it had an error when running 
`cypress open`

breaks with:
`extension "RANDR" missing on display ":99"`

### Desired behavior:
run properly

**Comment by bahmutov** [comment]
Any more details on this? It is hard to see why it might fail since we are testing cypress on windows too.

**Comment by tzookb** [comment]
My mistake :/

she just told me that she did it on our dev server that has no visible browser  :/
and not locally on her computer

so it must run headlessly 

:|
