### ISSUE TITLE
`cypress verify` fails on latest macOS with latest node: "TypeError: Cannot read property 'api_url' of undefined"

### ISSUE THREAD

**Issue by chapati23** [cypress-io/cypress#1205]
- Operating System: macOS 10.13.2
- Cypress Version: 1.4.1
- Node Version: 9.4.0

### Is this a Feature or Bug?
Bug

### Current behavior:
`yarn cypress verify` fails with the following error:

```
$ /my-project/node_modules/.bin/cypress verify
It looks like this is your first time using Cypress: 1.4.1

 ✖  Verifying Cypress can run /my-project/node_modules/cypress/dist/Cypress.app
   → Cypress Version: 1.4.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you using Docker, we provide containers with all required dependencies installed.
----------

/my-project/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/konfig.js:15
return config[getter];
^

TypeError: Cannot read property 'api_url' of undefined
at /my-project/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/konfig.js:15:20
at Object.<anonymous> (my-project/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/util/routes.js:11:13)
at Object.<anonymous>
…
…
…
----------

Platform: darwin (17.3.0)
Cypress Version: 1.4.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Desired behavior:
`yarn cypress verify` works as expected

**Comment by bahmutov** [comment]
That is very weird error, almost as if something did not install correctly. Can you remove `node_modules` folder and try installing again, please?

**Comment by chapati23** [comment]
Found the error. We're using [yarn autoclean](https://yarnpkg.com/lang/en/docs/cli/autoclean/) to downsize our `node_modules` folder. And it seems cypress depends on files that the standard config in `.yarnclean` deletes per default. The solution was to add the following to my `.yarnclean` file:

```
!cypress/**/*
```

This keeps `yarn autoclean` from deleting anything in the `node_modules/cypress` folder
