### ISSUE TITLE
Check for background traffic

### ISSUE THREAD

**Issue by BlaM** [cypress-io/cypress#121]
Is there a way to monitor and check background traffic?

For example if I enter a site and that site is supposed to issue a tracking call back to the server that does not change the UI - can I somehow check if that tracking call contained a specific string in its url?

**Comment by brian-mann** [comment]
If the `tracking call` is an XHR / AJAX request, then yes, you can easily do this. Cypress will not only display the traffic but you can easily route it and make assertions on any part of the request - the `url`, the `request body`, the `response body`, etc.

If the request is via `JSONP` or `new Image` (which is what many analytics providers actually do) then no, there's no way to access that request currently.

There are several browser API's which make regular HTTP requests available and it is possible the Cypress server can provide this data back to you but so far there's never been a use case from users wanting to access non XHR http requests.

Also for all further questions about Cypress' functionality and features [feel free to come into the gitter channel and chat with us.](https://gitter.im/cypress-io/cypress)

**Comment by pixeldynamics** [comment]
Very interested in the ability to view network payloads of any type, including JSONP or new Image. 
Would like to be able to validate Adobe Analytics and Tealium payloads and any other network request/response.

**Comment by brian-mann** [comment]
@pixeldynamics we are giving you that ability with the new network stubbing rewrite: https://github.com/cypress-io/cypress/issues/687
