### ISSUE TITLE
Server needs promise-based way to communicate with driver

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1211]
## Feature

When the client code (running in the spec iframe) stubs a network request it might have logic to execute. For example if the delay for the resource is not a constant but should be determined dynamically the test might do this

```js
it('delays', () => {
  cy.route({
   url: '/foo',
   delay: (req) => 500
  })
})
```

This "traffic rule" should be sent to the server's network proxy module that handles stubbing. We cannot send the callback function `delay: (req) => 500`, so it gets stripped when passing message from the client to the network proxy module. The module is running in the Node process. When it needs to handle the request it has a problem - how does it call `delay` callback?

We have three problems: 

- we cannot just strip `delay` callback and forget about it.
- network proxy module should send a message to the client saying "call delay callback"
- the client should be able to _respond_ back to the server after calling the delay callback

## Proposal

When stripping callback functions from traffic rules, we are going to collect all callbacks into an object by unique id.

```js
// before sending rule
const r = {
  url: '/foo',
  delay: (req) => 500
}
// after
const toSend = {
  url: '/foo',
  delay: '__message:a1234'
}
const callbacks = {
  __message:a1234: (req) => 500
}
```

On the server side, when reconstructing traffic rule object we put method proxies

```js
// on the server we receive
const received = {
  url: '/foo',
  delay: '__message:a1234'
}
// and make into
const rule = {
  url: '/foo',
  delay: (...args) => callClientCallback('__message:a1234', ...args)
}
```

The function `callClientCallback` uses socket message to communicate to the client, but it also registers 1 time unique _receiver_ message name to receive reply and resolve its promise.

```js
function callClientCallback(name, ...args) {
  return new Promise((resolve, reject) => {
    const replyId = '__reply:' + _.random(1, 1e+6)
    socket.emit('client:async', name, ...args)
    socket.on(replyId, (data) => {
     socket.remove(replyId) // used once
    })
  })
}
```

The network layer thus can transparently get specific delay or other values from the test's callbacks.

I have implemented rudimentary solution in https://github.com/cypress-io/cypress/commits/collect-traffic-rules but the communication needs to be tighten up and made general. 

## Related info

- https://github.com/bahmutov/iframe-api is example of making an API across iframe boundary using `postMessage` to communicate

**Comment by brian-mann** [comment]
This already exists in `server/lib/socket` - it's how Cypress already responds to socket message requests made by the driver.

I don't believe you don't need to add another layer here.

**Comment by bahmutov** [comment]
I could not find the same thing to communicate from server to the driver

**Comment by jennifer-shehane** [comment]
Hey @brian-mann, could you update on how to achieve this today please?

**Comment by jennifer-shehane** [comment]
Hey @brian-mann, any update on how to achieve this exactly?

**Comment by flotwig** [comment]
This is implemented in [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept), which has support for dynamic request/response callbacks in the driver, similarly to what @bahmutov described in the OP. Closing since this is now possible.
