### ISSUE TITLE
Need to update reported network stubs from the network layer

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1214]
## Network stubbing

When a traffic rule has been used, the server needs to send message to the driver with this information. The proxied call should be reflected in the reporter.

**Comment by bahmutov** [comment]
Some success recording intercepted requests / responses in https://github.com/cypress-io/cypress/tree/collect-traffic-rules

```js
it('returns mock data', () => {
    cy
      .route({
        url: '/users?_limit=3',
        response: [1, 2, 3],
        headers: {
          'access-control-allow-origin': '*'
        }
      })
      .as('users')
    cy.visit('has-fetch.html')
  })
```
Shows the count of stubbed requests and values
<img width="1282" alt="screen shot 2018-01-22 at 2 12 07 pm" src="https://user-images.githubusercontent.com/2212006/35239549-cb25567e-ff7e-11e7-9245-a41fbb2fb00b.png">

**Comment by bahmutov** [comment]
How to wait for aliased route?
```js
it('allows inspecting response', () => {
    cy
      .route({
        url: '/users?_limit=3',
        response: [1, 2, 3],
        headers: {
          'access-control-allow-origin': '*'
        }
      })
      .as('users')
    cy.visit('has-fetch.html')
    cy.get('@users').its('response.body').should('have.length', 3)
  })
```
Currently fails, because the `get('@users')` is just bare object - it does not understand the aliased request there

<img width="448" alt="screen shot 2018-01-22 at 4 46 01 pm" src="https://user-images.githubusercontent.com/2212006/35246174-c7b1cfbc-ff93-11e7-8034-a3042d5631c2.png">

**Comment by bahmutov** [comment]
oh, it was supposed to be `cy.wait('alias')`
<img width="988" alt="screen shot 2018-01-22 at 4 54 39 pm" src="https://user-images.githubusercontent.com/2212006/35246517-fd5ddbd2-ff94-11e7-8c29-ba7b0e0878ac.png">

**Comment by jennifer-shehane** [comment]
Yeah, this may not be the most clear thing in our docs...but using `cy.get('alias')` is used to get the route after it has been waited on and responded to. :thinking:

**Comment by flotwig** [comment]
Just realized this issue was assigned to me, not really sure what it is though. I think this will be covered by #687, please reopen if this is still something that is needed.
