### ISSUE TITLE
Upgade jQuery dependency to 3.x

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1215]
GitHub has security vulnerability against our 2.x version in packages/server/package.json. We should just upgrade to 3.x

<img width="1006" alt="screen shot 2018-01-22 at 12 38 13 pm" src="https://user-images.githubusercontent.com/2212006/35235173-5b2a5f48-ff71-11e7-9f2e-c669ffc92f7c.png">

<img width="758" alt="screen shot 2018-01-22 at 12 38 39 pm" src="https://user-images.githubusercontent.com/2212006/35235179-5edff1d4-ff71-11e7-9b6b-5655dd4e89fc.png">

**Comment by jennifer-shehane** [comment]
Updating jQuery is quite a big task, as many of our traversal api commands directly use jQuery. I updated jQuery from 2.1.4 to 2.2.4 and just remember it needing a lot of oversight to ensure things were working as intended.

**Comment by joyarzun** [comment]
There is no fix/patch for jQuery v2.x and it's only fixed on v3
https://github.com/jquery/jquery/issues/2432#issuecomment-290983196

**Comment by jennifer-shehane** [comment]
Yeah, I mean, anyone can open a pull request to update jQuery, the main thing to look for is failing tests after that - see what's changed and fix them up. https://github.com/cypress-io/cypress/blob/develop/packages/driver/package.json#L38

**Comment by bahmutov** [comment]
yeah, need to start this work by making a branch, pull request and then seeing which tests (if any) start breaking

**Comment by jennifer-shehane** [comment]
I've opened a PR and began outlining work that is necessary to upgrade. Any help would be appreciated! 😄 https://github.com/cypress-io/cypress/pull/1229
