### ISSUE TITLE
Calling cy.screenshot from custom failure handler

### ISSUE THREAD

**Issue by JPHamlett1993** [cypress-io/cypress#1217]
## Current behavior:
When a test fails and I call cy.screenshot() in my custom fail handler I get the following error

```
CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > cy.request()

The cy command you invoked inside the promise was: 

  > cy.screenshot()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises executeas soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

https://on.cypress.io/returning-promise-and-commands-in-another-command
```

### Desired behavior:

The screenshot is taken.

### How to reproduce:
Start a start project, override the fail method to call `cy.screenshot()` and make a failure test.

### Additional Info (images, stack traces, etc)

The reason I need to call `cy.screenshot` is because I need to name the file in a certain manner, for my reporter to work correctly. 

- Operating System: MacOS
- Cypress Version: 1.4.1
- Browser Version: Chrome

**Comment by JPHamlett1993** [comment]
Any help?

**Comment by bahmutov** [comment]
That's interesting - I think we are a little too aggressive catching Cy commands from inside other Cy commands @brian-mann - I see this error sometimes in other situations, although was not a blocker for me.

**Comment by jennifer-shehane** [comment]
Could you paste the code of your `cy.request`?

**Comment by JPHamlett1993** [comment]
@jennifer-shehane It is not related to the request.

It also happens with this code

Ignore the bad test 😃 

```
describe('Add Bank MOP', () => {

	before(() => {
		cy.visit('www.google.com')
		cy.get('#asdf')
	});
    
	it('should fail', () => {
		cy.visit('www.google.com')
		cy.get('#asdf')
	})
})
```

**Comment by jennifer-shehane** [comment]
could you share your custom fail handler where the `cy.screenshot()` command is written?

**Comment by JPHamlett1993** [comment]
Yup

```
Cypress.on('fail', function(err, runnable) {
	cy.screenshot()
        throw err
}
```

**Comment by nicholasmaddren** [comment]
I'm also having this problem.

**Comment by abhijithEvive** [comment]
Any updates on this issue?

**Comment by jennifer-shehane** [comment]
Verified - Promise error is thrown with code below:

```js
Cypress.on('fail', function (err) {
  cy.screenshot()
  throw err
})

it('should fail', () => {
  cy.visit('www.google.com')
  cy.get('#asdf')
})
```

![screen shot 2018-06-19 at 12 16 05 pm](https://user-images.githubusercontent.com/1271364/41610196-918f049a-73ba-11e8-826d-8461e9921fa7.png)

**Comment by chrisbreiding** [comment]
I'm not sure why this is happening, but it isn't specific to `cy.screenshot()`. You can call any command in the 'fail' handler and get the same error:

```javascript
Cypress.on('fail', (err) => {
  cy.wrap({})
  throw err
})

it('fail error', () => {
  cy.visit('www.google.com')
  cy.get('#asdf')
})
```

**Comment by brian-mann** [comment]
Plus this scenario doesn't really make sense and it would effectively create an endless loop. 

```js
Cypress.on('fail', (err) => {
  // this would continue to loop forever if we 
  // caught all errors and attempted to recover.
  // its a poor mans form of conditional testing
  // which is always an anti pattern in cypress
  // https://docs.cypress.io/guides/core-concepts/conditional-testing.html#
  return cy.get('somethingThatDoesNotExist')
})

cy.get('sopmethingThatDoesNotExist')
```


This really feels like an http://xyproblem.info/ where the true intention is obfuscated by asking how to issue a command in a `fail` handler. What is it that you're **trying to do**?

**Comment by chrisbreiding** [comment]
@brian-mann I think they already stated it:

> The reason I need to call cy.screenshot is because I need to name the file in a certain manner, for my reporter to work correctly.

**Comment by brian-mann** [comment]
This is better handled with background events such as `after:screenshot` that we need to add to the `pluginsFile` which enables you to get access to the results and use any node method to do stuff with `fs` if you wanted to.

Alternatively he could use an `afterEach` hook to check if the current test is failed, and if so to take another screenshot - or just use `cy.task` to rename the existing failed one.

**Comment by jennifer-shehane** [comment]
This after screenshot API was provided as of version [3.0.2](https://on.cypress.io/changelog#3-0-2) and is documented here: https://on.cypress.io/after-screenshot-api Closing as resolved.

**Comment by qxchen6** [comment]
so, any solutions ?

**Comment by jennifer-shehane** [comment]
@qxchen6 Use the after screenshot api: https://on.cypress.io/after-screenshot-api
