### ISSUE TITLE
TypeScript: Incorrect subject type from returning a wrapped `undefined` from `.then`

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#1219]
It is valid to return a wrapped `undefined`. Example: `cy.wrap(undefined)` or `Promise.resolve(undefined)` or even `cy.wrap(null)`.

In this case, the subject is a wrapped `undefined` instead of an unwrapped `undefined`.

- Operating System: N/A
- Cypress Version: 1.4.1
- Browser Version: N/A

### Is this a Feature or Bug?
Bug

### Current behavior:
```ts
cy.get('body')
  .then(() => cy.wrap(undefined))
  .then((subject) => {
    subject // Cypress.Chainable<undefined>
  })
```

### Desired behavior:
```ts
cy.get('body')
  .then(() => cy.wrap(undefined))
  .then((subject) => {
    subject // undefined
  })
```

### How to reproduce:
See "Current behavior"

#### Test code:
See "Current behavior"

### Additional Info (images, stack traces, etc)
PR is on the way

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).
