### ISSUE TITLE
If NODE_ENV is not set in parent shell, cypress sets it to `"undefined"`

### ISSUE THREAD

**Issue by jbr** [cypress-io/cypress#1223]
- Operating System: MacOS / bash 4.4.12
- Cypress Version: 1.4.1
- Browser Version: Chrome 64

### Is this a Feature or Bug?
Bug

### Current behavior:
If NODE_ENV is not in the environment, cypress sets it to `"undefined"`, which gets passed along to cy.exec() calls

### Desired behavior:
Cypress should not change the environment other than in documented ways. NODE_ENV never should be the string `"undefined"`

### How to reproduce:
`unset -v NODE_ENV` and run a cypress test that does `cy.exec("echo $NODE_ENV")` as in:
https://github.com/jbr/cypress-test-tiny/tree/jbr/undefined-node-env

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).
