### ISSUE TITLE
Cypress breaks webpack compiling when installed as an npm package

### ISSUE THREAD

**Issue by joshmccure** [cypress-io/cypress#1227]
### Current behavior:

Currently when I install the cypress npm package on my angular cli project it breaks webpack compiling. The error only happens when after cypress is installed via npm and then `ng serve` is run to trigger webpack compiling.

The repository itself has no trouble compiling pre-cypress or any other npm package

It seems related to lodash we define lodash as
```
import * as _ from 'lodash';
```

Please see the stack trace down the bottom

### Desired behavior:

cypress should not break webpack compiling

### How to reproduce:

Create and Angular 4 project and try to compile is after cypress is installed as an npm package

### Additional Info (images, stack traces, etc)

```
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (198,41): Property 'uNumber' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/_global/modal/party-select/party-select-modal.component.ts (126,21): Property 'partyRoleName' does not exist on type 'Party'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-form/contact-form.component.ts (422,41): Property 'TelephoneNumber' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (93,16): Property 'RoleName' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (93,37): Property 'RoleType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (127,64): Property 'TypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (128,16): Property 'Type' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (147,17): Property 'Number' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (147,41): Property 'Number' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (148,66): Property 'TTypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (149,17): Property 'NumberType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (168,65): Property 'EmailTypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-details/contact-details.component.ts (169,17): Property 'emailType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/account-form/account-form.component.ts (494,17): Property 'telephoneNumber' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/account-form/account-form.component.ts (494,41): Property 'TelephoneNumber' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (110,16): Property 'partyRoleName' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (110,37): Property 'PartyRoleType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (178,65): Property 'AddressTypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (179,16): Property 'addressType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (198,17): Property 'telephoneNumber' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/contacts/contact-form/contact-form.component.ts (422,17): Property 'telephoneNumber' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (199,17): Property 'telephoneNumberType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (199,75): Property 'TelephoneTypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (200,17): Property 'telephoneNumberType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (200,45): Property 'telephoneNumberType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (200,73): Property 'telephoneNumberType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (201,17): Property 'communicationType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (201,72): Property 'CommunicationTypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (202,17): Property 'communicationType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (202,43): Property 'communicationType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (202,69): Property 'communicationType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (221,17): Property 'emailType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (221,65): Property 'EmailTypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (222,17): Property 'communicationType' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/accounts/user-details/user-details.component.ts (222,72): Property 'CommunicationTypeID' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/templates/cat-form/cat-form.component.ts (111,63): Property 'value' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/templates/cat-form/cat-form.component.ts (111,75): Property 'value' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/templates/dog-form/dog-form.component.ts (135,63): Property 'value' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/templates/dog-form/dog-form.component.ts (135,75): Property 'value' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/templates/flyer-form/flyer-form.component.ts (128,63): Property 'value' does not exist on type '{}'.
ERROR in /Users/Josh/Desktop/ui/src/app/templates/flyer-form/flyer-form.component.ts (128,75): Property 'value' does not exist on type '{}'.

webpack: Failed to compile.
```

- Operating System: Mac Osx
- Cypress Version: latest
- Browser Version: 63 chrome

**Comment by bahmutov** [comment]
Hmm, I don't see `cypress` anywhere in your stack trace. Are you sure this is due to installing Cypress? I find this sentence weird in your bug report
```
The repository itself has no trouble compiling pre-cypress or any other npm package
```
We have been adding Cypress to Angular project without problems - see https://www.cypress.io/blog/2017/12/11/an-alternative-to-protractor-for-angular-projects/ for example

**Comment by joshmccure** [comment]
Adding more information because I think this is a genuine bug now. 

Just to clarify to problem. The compilation errors are coming from application code not cypress test code, but these errors only occur after installing Cypress as an NPM package.

I'm pretty sure this is because of some sub-dependencies that cypress installs for lodash typings which then force these on the application code. I'll list the errors below and walk through the application code.

Here is 1 of the many stack trace errors - (they're all the same and all in component.ts files)

ERROR in /Users/Josh/Documents/ui/src/app/accounts/account-details/account-details.component.ts (110,16): Property 'partyRoleName' does not exist on type '{}'.

webpack: Failed to compile.

here is the code causing the error - note partyRoleName

  private retrieveRoles() {
    this.accountService.getPartyRoles(this.account.PartyID).subscribe(
      partyRoles => {
        _.map(partyRoles, (role) => {
          role.partyRoleName = role.PartyRoleType.name;
        });
        this.Roles = partyRoles;
        if (this.Roles.length > 0) {
          this.retrievePrimaryContact();
          _.each(this.Roles, (role) => {
            role.owner = { party: new Party() };
            this.accountService.getPartyRoleParentsByRelationshipTypeId(role.iD, 13).subscribe(
              parents => {
                if (parents.length) {
                  role.owner = parents[0];
                  role.owner.party.PartyName = parents[0].partyName;
                }
              }
            );
            this.retrieveShares(role);
            this.retrieveRelations(role);
          });
        }
      }
    );
  }

We also define lodash at the top of the file 
import * as _ from 'lodash';

For now I need to have my cypress folder to have its own package.json as a workaround but this is less than ideal - otherwise it breaks our projects dependencies

**Comment by bahmutov** [comment]
Can you exclude the `Cypress` in the `tsconfig.json`?

**Comment by alexmgrant** [comment]
This is most definitely an issue. My build fails on first compile throwing type errors where lodash is used, only when cypress is installed via npm. `"cypress"` is ignored in `tsconfig.ts`.

**Comment by jedwantstocode** [comment]
I updated using the command from the cypress test runner now I can't build components with same error above. :(

**Comment by motabass** [comment]
For me, only deleting @types/lodash from node_modules directory by hand solves works around the issue.

**Comment by fr0** [comment]
This is probably due to two things that combine to create the problem:
1. `@types/lodash` is in cypress's `dependencies` list; typically, type def packages should be in `devDependencies`. They are needed for compilation of the code, but not needed at runtime. (Things like `@types/mocha` and `@types/chai` might be a weird exception to this rule specifically in Cypress's use case; although, you could argue that users should put those in their `package.json`'s `devDependencies` instead).
2. Cypress is referencing an old version of `@types/lodash` (`4.14.87`). I have problems when using that version. However, when upgrading to `4.14.120`, things work fine.

**Comment by bahmutov** [comment]
@fr0 and @motabass I am thinking of moving all `@types` out of prod dependencies, any comments on the proposal #3371?

**Comment by ro-savage** [comment]
@bahmutov - i've run into the same issue as here and #1319.

We have a working project with typescript using jest.

Only change i made was `yarn add cypress` and now typescript fails with a bunch of errors relating to jest types. One example is:

```
node_modules/@types/jest/index.d.ts:27:13 - error TS2300: Duplicate identifier 'beforeEach'.

27 declare var beforeEach: jest.Lifecycle;
               ~~~~~~~~~~
```

I believe this is because Cypress is overwriting our jest types with a different version. (Although I may be wrong)

**Comment by ro-savage** [comment]
Potential fix: https://github.com/cypress-io/cypress/pull/3425

**Comment by jennifer-shehane** [comment]
The code from https://github.com/cypress-io/cypress/pull/3425 is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by only4arunkumar** [comment]
Today happen to get the same error. But none of the above solution were relevant to me . 
But later found that  my  support/command.js  file had an import  statement for loaddash . not sure how it got added.
 removing it resolved my issue
