### ISSUE TITLE
unable to set up cypress on rhel

### ISSUE THREAD

**Issue by shrutisatish** [cypress-io/cypress#1228]
- Operating System: rhel 6.7
- Cypress Version:1.4.1
- Browser Version: Mozilla Friefox 52.2.0

```
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14  not found
 /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found 
 /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15'
```

the same setup works on a mac. However doesn't work on RHEL

**Comment by Bkucera** [comment]
Currently Cypress ships with a modern version of Electron and requires your system to have all the dependencies to run that version- even when run with a different browser option or in headless mode. Right now the dependencies align with Chromium 59, and will continue to update as logged in the [changelog](https://docs.cypress.io/guides/references/changelog.html#2-0-0).

Unfortunately Rhel 6, and by extension CentOS 6, are [officially unsupported by Chrome](https://access.redhat.com/solutions/523213), so I would recommend upgrading your distro to a supported one.
