### ISSUE TITLE
Popup escapes cypress

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress#123]
If the page loads a popup on click, here is the current behavior:
1. In browser test runs, chrome reports a [blocked popup](https://support.google.com/chrome/answer/95472?hl=en) 
2. The pop up shows when running via `cypress run` in headless mode. So, definitely an issue here.

**Comment by brian-mann** [comment]
Can you paste me your `window.open` code that opens the popup?

**Comment by brian-mann** [comment]
We will probably need an option on `cy.click` which enables you to issue a native click. Browsers (like Chrome) will block simulated event click handlers if they trigger `window.open`.

Showing the popup in headless mode is probably just a simple oversight, we'll take a look.

**Comment by brian-mann** [comment]
Windows opening headlessly will be fixed in `0.15.4`. The popup blocker problem will be fixed in `0.16.0`.

**Comment by brian-mann** [comment]
Fixed in [`0.15.4`](https://github.com/cypress-io/cypress/wiki/changelog#0154-04222016).

I'm going to open a second issue related to the pop-up blocker. That will be fixed in `0.16.0`.

**Comment by jennifer-mann** [comment]
See issue #125 for blocked pop-up
