### ISSUE TITLE
Add support for caching the Cypress downloaded package

### ISSUE THREAD

**Issue by ntwb** [cypress-io/cypress#1233]
- Operating System: all
- Cypress Version: all
- Browser Version: n/a

### Is this a Feature or Bug?

Feature

### Current behavior:

When using a CI (Travis/Circle etc) the Cypress zip is downloaded, currently, the zip file is ~105mb for the current release `https://cdn.cypress.io/desktop/1.4.1/osx64/cypress.zip` 

### Desired behavior:

To have Cypress check a local folder to see and compare if the file located in a specific directory exists and matches the current version, if not download the latest replacing the previous.

Cypress cache could use either of these common folders, `$HOME/.config` or `$HOME/.cache` and add a Cypress folder to either of those top level folders.

### How to reproduce:

n/a 

#### Test code:

n/a

### Additional Info (images, stack traces, etc)

n/a

**Comment by dschulten** [comment]
Also see https://github.com/cypress-io/cypress/issues/1300

**Comment by ntwb** [comment]
Closing this in favour of #1300 as it's been triaged and labeled up
