### ISSUE TITLE
Possible to silently fail upon timeout on visit()?

### ISSUE THREAD

**Issue by Paratron** [cypress-io/cypress#1237]
I am trying to test an app that is currently running inside the intranet of our company. The page makes an attempt to load google tag manager from within a script tag - thus I am unable to intercept that with cy.route() :(

The problem is that because IT dept. does not want to have requests on the test stage being logged in GTM, they just blocked access to that domain from within the intranet. While this is fine for manual browser testing, its poison for cypress, since cypress waits until the request to GTM is timed out until it reports the site as being loaded when calling visit().

I tried to set up a timeout of a few seconds, since the rest of the applocation loads quickly, but then cypress will fail the visit() action. 

There should really be an option to fail silently, when the visit() command times out.

**Comment by jennifer-shehane** [comment]
Have you looked into blacklisting the GTM requests? https://on.cypress.io/configuration#blacklistHosts

**Comment by brian-mann** [comment]
@Paratron the link @jennifer-shehane suggested is exactly what you are looking for. It will block all traffic to these hosts. I'm closing this issue.
