### ISSUE TITLE
Can't Open Cypress on Windows

### ISSUE THREAD

**Issue by rgavinc** [cypress-io/cypress#1238]
### Is this a Feature or Bug? 
Bug

### Current behavior:
After installing Cypress on windows I tried to run the command to open it and I got the following error:

node_modules\.bin\cypress open

Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you using Docker, we provide containers with all required dependencies installed.
----------

fs.js:982
return binding.lstat(pathModule._makeLong(path));
^

Platform: win32 (10.0.16299)
Cypress Version: 1.4.1

I'm not doing anything special, I just simply downloaded it and tried to open it.

**Comment by bahmutov** [comment]
is the path `node_modules.bin\cypress` correct? Seems like there is a missing slash.
Second question - did you download it as a zip or did `npm install`?

**Comment by rgavinc** [comment]
Oops I'm actually running the command: "node_modules\.bin\cypress open". There was a problem with starting the project in my OneDrive Folder. I started over in another location on the drive and it worked fine.

**Comment by Bonesarmy** [comment]
cd to bin folder then cypress open
