### ISSUE TITLE
.type() improvements

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1241]
There are multiple issues that have been raised in regards to `.type()` (with some tertiary issues concerning `.blur()` and `.clear()`). This issue is generally to be used to track the progress made for these improvements. 

## What we need to do

- #1234 
- #1209 
- #1176 
- #1171 
- #1108 
- #984 
- #940 
- #610 
- #596 
- #593 
- #586 
- #420 
- #365

**Comment by brian-mann** [comment]
Fixed in https://github.com/cypress-io/cypress/pull/2016
