### ISSUE TITLE
Cypress test runner redirects to __ suddenly

### ISSUE THREAD

**Issue by joelgrimberg** [cypress-io/cypress#1245]
I am building an E2E test in which I use a button / submit to go to a second page.
the submit triggers a redirect through jQuery. 

I tried using :
```javascript
Cypress.on('window:before:load', (win) => {
      Object.defineProperty(win, 'self', {
        get: () => {
          return window.top
        }
      })
    })
```

I also tried using
```javascript
cy.visit('url', {
			 onBeforeLoad: (win) => {
			 Object.defineProperty(win, 'self', {
			 get: () => {
			 return window.top
		 }
```

The code as shown above does not work (I still get the 'whoops') for redirects behind buttons;
it only works for redirects behind cy.visit as it looks.

#1064 
#392 
#969 
#992

**Comment by odranoelBR** [comment]
Tks a lot @brian-mann . You guys are creating a great tool, keep working and i help / hope it get bigger.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/1295

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).

**Comment by joelgrimberg** [comment]
Great! When will 2.0 be released?  
Cannot wait ;-)


Joël

Op 16 februari 2018 om 07:16:18, Brian Mann (notifications@github.com(mailto:notifications@github.com)) schreef:

**Comment by jennifer-shehane** [comment]
@joelgrimberg It is released now.
