### ISSUE TITLE
Validate readonly fields

### ISSUE THREAD

**Issue by pedromatos47** [cypress-io/cypress#1246]
Since Cypress doesn't support readonly attribute validation as of now, is there any way to work around it?

And would it be to much of a hassle to add this feature?

Cheers

**Comment by brian-mann** [comment]
PR's accepted! This would be rather simple to implement.

**Comment by jennifer-shehane** [comment]
`.type()` code is here, it should likely throw an err if the input is `readonly` unless opt `force` is `true`: https://github.com/cypress-io/cypress/blob/issue-895/packages/driver/src/cy/commands/actions/type.coffee#L23

**Comment by pedromatos47** [comment]
@jennifer-shehane  @brian-mann  Thank you for your feedback! 🙂

**Comment by brian-mann** [comment]
Reopening per my comments here: https://github.com/cypress-io/cypress/pull/4729#issuecomment-513625272
