### ISSUE TITLE
WARNING! Internal test version. Cookie Consent not logged.

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#1261]
- Operating System: Windows
- Cypress Version: 1.4.2
- Browser Version: Electron

### Current behavior:
In specific situations when i'm clicking on a button i'm getting response in console:
"WARNING! Internal test version. Cookie Consent not logged."
And button redirects me to wrong site.
I don't have this when i'm using Chrome and i don't have it when i'm clicking it manually in chrome.

### Desired behavior:
Button should redirect me to the site i need.

### How to reproduce:
I'm just using simple "cy.get('#MiniCart_BasketOrderNow').click();" - but this button propably sending some cookies ant this is not working in Electron...

**Comment by jennifer-shehane** [comment]
This looks to be an error from the web application you are testing. Perhaps having to do with Cookie Consent (such as for EU Cookie laws) not being accepted. 

Also, many websites have code written to specifically prevent them from being run by an automated system (to avoid bots doing bad things in their system). Unfortunately, this also inhibits automated testing by well intentioned developers. You may need to disable some of these checks programmatically in your application while testing.

Closing as this is not under Cypress direct control to fix.

**Comment by zbigniewkalinowski** [comment]
But i'm not experiencing this problem using Chrome... It must be some Electron issue.
Now i'm totally blocked, because i need to run my tests from external dashboard (i'm creating input json files for cypress test with simple html dashboard). And i can't run it in Chrome because of 1262 issue and i can't run it in Electron because od 1261 issue :(

This is what i'm getting from console:
![obraz](https://user-images.githubusercontent.com/34089686/35867553-4b2ef29e-0b5a-11e8-8365-e6d98fa1374b.png)
