### ISSUE TITLE
Whoops, we can't run your tests.

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#1262]
- Operating System: Windows
- Cypress Version: 1.4.2
- Browser Version: Chrome

### Is this a Feature or Bug?
Bug

### Current behavior:
When i'm running any test in Chrome for the first time i see "Whoops, we can't run your tests."
When i select Electron and Chrome again everything is working.
I'm experiencing this problem when i'm using Cypress app, but also when i'm trying tu run test from command line.
Running tests in Chrome from Command line is impossible now in fact...

### Desired behavior:
I need to run my tests from command line smoothly, because i need to run them from external dashbord.

### How to reproduce:
1. First situation
- cypress open
- select Chrome on right panel
- run any script

2. Second situation
- cypress run --spec cypress/integration/myFile.js --browser chrome

### Additional Info (images, stack traces, etc)
Result in both situations look like this:
![obraz](https://user-images.githubusercontent.com/34089686/35863444-f659b8cc-0b4e-11e8-873c-5cc1fb2b13f0.png)

**Comment by jennifer-shehane** [comment]
We have seen this problem, but have yet to determine why this is happening for some users. See duplicate issue here: #1239

**Comment by Turkirafaa** [comment]
Hello!
Can any one help me with this problem 

![skarmavbild 2018-03-26 kl 10 57 06](https://user-images.githubusercontent.com/32999333/37896674-9a5f92ce-30e4-11e8-9169-f859ab8a7457.png)

**Comment by jennifer-shehane** [comment]
@Turkirafaa Please refer to this issue https://github.com/cypress-io/cypress/issues/1239 It has some workarounds that may help you.

**Comment by zeinMch** [comment]
Hello 
I have the same problem :( 

<img width="824" alt="screen shot 2018-10-17 at 11 42 43 am" src="https://user-images.githubusercontent.com/39551878/47081188-d5e2a200-d201-11e8-88d4-3c9edbba7806.png">

**Comment by roshanpal** [comment]
I am having the same problem. Tests ran the first time when I installed cypress. After that it never worked.
Whoops, we can't run your tests.

This browser was not launched through Cypress. Tests cannot run.
