### ISSUE TITLE
Pass --ui options along to mocha

### ISSUE THREAD

**Issue by dkreft** [cypress-io/cypress#1263]
### Current behavior:

Cypress ignores all attempts to configure Mocha's UI

### Desired behavior:

Ideally, I would like to be able to simply drop a `mocha.opts` file into `cypress/` or perhaps `cypress/support` so that I can configure mocha in the usual manner.

The motivation for this request is that my team and several of my peer teams have grown quite fond of `bdd-lazy-var/rspec` which, as the name implies, makes mocha's BDD tests behave more like `rspec` and having the ability to use `bdd-lazy-var` would make our adoption of Cypress much easier.

**Comment by glysbaysb** [comment]
IMO this should be a more general option. For example I have that problem that I would like to use the [mocha-steps](https://www.npmjs.com/package/mocha-steps) package.

From mochas description it always loads (for example) ".mocharc.json".
> JSON: Create a .mocharc.json (or .mocharc.jsonc) in your project's root directory. Comments — while not valid JSON — are allowed in this file, and will be ignored by Mocha. -- [Source](https://mochajs.org/#configuring-mocha-nodejs)

However this neither works in my root directory nor in `./cypress` nor in `./cypress/integration`. Does cypress call mocha with any special options to disable the default behaviour?

**Comment by matt-d-rat** [comment]
I also support this feature request, our team would prefer to use a custom Mocha UI which better suits our use case.

**Comment by glysbaysb** [comment]
cypress does not run the mocha cli, but instead uses it [programmatically](https://github.com/mochajs/mocha/wiki/Using-Mocha-programmatically). See [packages/driver/src/cypress/mocha.coffee](https://github.com/cypress-io/cypress/blob/70c441c9f9793d599e97481fc98df51c9468261d/packages/driver/src/cypress/mocha.coffee#L60).

Luckily the CLI "--ui" option is supported by the API, so the original issue can be solved. Unluckily it seems my problem cannot be easily solved. I see three possible ways forward:
1. `specWindow.mocha` is defined. Your test code might be able to access it and then configure mocha to your liking
2. Making it an option (maybe in "cypress.json") and passing it to the Mocha contstructor
3. Changing mocha itself and adding another constructor which takes a path to a config file. And then using that somehow in cypress

Those three possible ways get progressively harder but allow for more control. I think the first option would be a quick way to solve the original issue. The third way would certainly be very cool but then two independet projects would need to be convinced of the need.

**Comment by guy333** [comment]
i tried the above suggestion: mocha.ui = {ui: 'bdd-lazy-var/global'} on support/index.js without success.

seems like there is an syntax check on the spec files before I could hack the mocha object.

**Comment by stalniy** [comment]
@jennifer-shehane what do we need to do to integrate this into cypress? 

I'm the author of bdd-lazy-var (custom ui for mocha) and I'm also want to use it in my e2e tests

**Comment by devhazem** [comment]
I would also like to use the following library https://github.com/devhazem/mocha-test-options in Cypress. Does anyone have a workaround?
