### ISSUE TITLE
Cookie problem with Cypress controlled browser

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#1268]
### Current behavior:

Yesterday i reported bug #1261. I want to come back to this situation:

1. Application that i'm testing is creating basket with bunch of products that customer orders.
2. This basket GUID is stored in cookie and when i'm clicking on "Order button" it's somehow sent to the next step of the order.

And now the problem:

1. I cleared the App Data (like it's described in #1239 ticket).
2. I'm running my test and when it's clicking on "Order button" in my app, it redirects me to start page...
3. I'm getting "WARNING! Internal test version. Cookie Consent not logged." message in my console log. (the same situation when i'm using Electron browser)
4. I'm going to Chrome settings and i'm disabling this:
	![obraz](https://user-images.githubusercontent.com/34089686/35910460-e8aed240-0bf6-11e8-879c-934224901e58.png)
5. Now my test is running smoothly - "Order button" is working fine.
6. But now i'm experiencing problems described in 1239 ticket again...

### Desired behavior:

For the automat that i'm writing now i need to run Cypress scripts from external dashboard that i created for my customer.

I can't run those scripts properly, because of those two problems.

Please tell me how to fix this problem, because my customer is waiting for ready product and i'm blocked because of this.

I'm trying to convince my customer for using Cypress automats in big TV and Internet provider.

Regards

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
