### ISSUE TITLE
The Test Runner view /(dashboard)

### ISSUE THREAD

**Issue by MaryBloom** [cypress-io/cypress#1270]
I have the following problem.

When I started recording my tests by  calling  commend: cypress run – record  (with scripts in package.json)
the tests are recorded but ” The Test Runner" view is not visible.

Why is it happen?
Should it be?

I change my script in package.json to commend: cypress run but when I call: npm command (what is: cypress only run ) the tests are still recorded and "The Test Runner" view is still not visible  (even after closing Visual Code)

How can I come back to “The Test Runner” view (how open this view again)?

**Comment by bahmutov** [comment]
- `cypress open` starts Cypress in the GUI interactive mode
- `cypress run` executes tests in non-interactive mode (this is what CI should do)
