### ISSUE TITLE
Getting Coordinates

### ISSUE THREAD

**Issue by DMarinsa** [cypress-io/cypress#1279]
- Operating System: Lubuntu
- Cypress Version: latest
- Browser Version: Chrome 64

### Is this a Feature or Bug?
Feature

### Current behavior:
Movements events are driven by coordinates input directly

### Desired behavior:
function that receives the coordinate from an element 
i.e.
x = cy.get('Element').getXcoordinate();
y = cy.get('Element').getYcoordinate();

**Comment by brian-mann** [comment]
Cypress is just Javascript - you can already do this with the DOM. Just call native methods like `getBoundingClientRect`

You could also wrap this up into a custom command easily.

**Comment by beirnem** [comment]
Hi, I am also trying to interrogate the position of an object, but I'm unable to combine use getBoundingClientRect() on an object I've gotten using cy.get(). I get an error stating
`Uncaught TypeError: cy.get(...).getBoundingRect is not a function`
Here is what I am trying: `cy.get('.claim > .btn-med-secondary').getBoundingRect();`
Could you provide an example of how to chain this function with cypress commands? I could not find any examples in the Cypress documentation. Thank you for your help.

**Comment by kyleoliveiro** [comment]
try `cy.get('.claim > .btn-med-secondary').then($el => $el[0].getBoundingRect())`

**Comment by jordivila** [comment]
> try `cy.get('.claim > .btn-med-secondary').then($el => $el[0].getBoundingRect())`

**getBoundingClientRect**

**Comment by BioJoseph** [comment]
If you need to get mouse position frequently (if there's a lot of mouse interactions in canvas) check out this plugin: https://github.com/BioRender-Team/cypress-mouse-position

**Comment by jennifer-shehane** [comment]
@BioJoseph 	Could you open a pull request to add this plugin to our [documentation](https://on.cypress.io/plugins)? Thanks! [Instructions here.](https://github.com/cypress-io/cypress-documentation/blob/develop/CONTRIBUTING.md#adding-plugins)

**Comment by bene-starzengruber** [comment]
There is one big drawback to this solution as it is not able to retry
My use-case is that I execute an action which will change the position a few ms later but cypress is too fast and directly asserts the position which is wrong at this time.
Sure, I can just put a wait into the code, but this is probably not what we want to do :)

The perfect way for me (who does not know cypress internals that well) is, to have something like cy.get(...).should('have.x', 100)
