### ISSUE TITLE
Cannot install Cypress, download server is down

### ISSUE THREAD

**Issue by NoNameProvided** [cypress-io/cypress#1280]
- Operating System: MacOS	
- Cypress Version: 1.4.1
- Browser Version: n/a

### Is this a Feature or Bug?

Bug.

### Current behavior:

Cannot download Cypress, because the post-install hook fails.

### Desired behavior:

I can download cypress.

### How to reproduce:

`npm install cypress@1.4.1`

#### Test code:

```js

```

### Additional Info (images, stack traces, etc)

```
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/1.4.1?platform=darwin&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 503
Response message: Service Unavailable
----------

Platform: darwin (17.3.0)
Cypress Version: 1.4.1
```

**Comment by brian-mann** [comment]
We did experience some timeouts this morning for a brief period of time - we'll look at the logs to investigate but it didn't last for very long.

**Comment by aahdahl** [comment]
@brian-mann - still experiencing the same issue as described above with Cypress version: 3.1.4

Log details:

The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/3.1.4?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 503
Response message: Service Unavailable
----------

Platform: linux (Debian - 9.6)
Cypress Version: 3.1.4

**Comment by wlsf82** [comment]
I am facing this issue right now. Could someone help, please?

**Comment by wlsf82** [comment]
It just worked after some tries. 🤔

**Comment by ZachGawlik** [comment]
The 503 issues seem to happen to all cypress download links. For a CircleCI run of our next prod candidate, where we're using a custom docker image that installs cypress through yarn we saw all 16 containers fail from a 503 of installing 3.1.1 via yarn which pointed to `https://download.cypress.io/desktop/3.1.1?platform=linux&arch=x64`

**Comment by jennifer-shehane** [comment]
We were experiencing a brief outage of our download service that has since been resolved. You can monitor our status and review any outages in the future here: https://status.cypress.io/

**Comment by sajjadh** [comment]
I am still experiencing the same issue!
Logs:-

5316 verbose stack Error: cypress@3.1.5 postinstall: `node index.js --exec install`
5316 verbose stack Exit status 1
5316 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
5316 verbose stack     at emitTwo (events.js:126:13)
5316 verbose stack     at EventEmitter.emit (events.js:214:7)
5316 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
5316 verbose stack     at emitTwo (events.js:126:13)
5316 verbose stack     at ChildProcess.emit (events.js:214:7)
5316 verbose stack     at maybeClose (internal/child_process.js:915:16)
5316 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
5317 verbose pkgid cypress@3.1.5
5318 verbose cwd C:\Users\Zone\cypressTest
5319 verbose Windows_NT 10.0.15063
5320 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cypress"
5321 verbose node v8.12.0
5322 verbose npm  v6.4.1
5323 error code ELIFECYCLE
5324 error errno 1
5325 error cypress@3.1.5 postinstall: `node index.js --exec install`
5325 error Exit status 1
5326 error Failed at the cypress@3.1.5 postinstall script.
5326 error This is probably not a problem with npm. There is likely additional logging output above.
5327 verbose exit [ 1, true ]

console error:- 


> cypress@3.1.5 postinstall C:\Users\Zone\cypressTest\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 3.1.5)

 √  Downloaded Cypress
 ×  Unzipping Cypress
   → Cypress Version: 3.1.5
    Finishing Installation
The Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at

https://github.com/cypress-io/cypress/issues
----------

Error: end of central directory record signature not found
----------

Platform: win32 (10.0.15063)
Cypress Version: 3.1.5
npm WARN cypresstest@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.1.5 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.1.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zone\AppData\Roaming\npm-cache\_logs\2019-03-15T09_26_07_581Z-debug.log

**Comment by jennifer-shehane** [comment]
@sajjadh Your issue seems to be related to this issue: https://github.com/cypress-io/cypress/issues/3515 Can you try updating to 3.2.0 to see if this issue is resolved please?

**Comment by sajjadh** [comment]
hi jennifer,
Still i could not get a proper solution. it says


"















* Installing Cypress (version: 3.2.0) ×  Downloading Cypress   → Cypress
Version: 3.2.0    Unzipping Cypress    Finishing InstallationThe Cypress
App could not be downloaded.Please check network connectivity and try
again:----------URL:
https://download.cypress.io/desktop/3.2.0?platform=win32&arch=x64
<https://download.cypress.io/desktop/3.2.0?platform=win32&arch=x64>Error:
read ECONNRESET----------Platform: win32 (10.0.15063)Cypress Version: 3.2.0
"*


Thank You & Best Regards,

* Sajjadh Ashroff*

Software Engineering Student | University of Westminster

E *sajjadhashroff@mail.com <+sajjadh.2017586@iit.ac.lk>*

* M* *+* *94 **77 3039097*

W www.zone24x7.com
