### ISSUE TITLE
Cypress should not require write access of root folder

### ISSUE THREAD

**Issue by itskingori** [cypress-io/cypress#1281]
Why do we check if the root of the project is writeable? 👇 i.e. the ` fs.accessAsync(projectRoot, fs.W_OK) `

https://github.com/cypress-io/cypress/blob/2b2b6d99a9f1bf232d9c7396b25390913d5f2b18/packages/server/lib/util/settings.coffee#L76-L93

cc:/ @zacblazic

**Comment by brian-mann** [comment]
Because we seed the project with `cypress.json` and the `cypress` folder and example spec code, and plugins, and fixtures, etc.

**Comment by itskingori** [comment]
@brian-mann Right. We're using this in Docker and common practice is to run the app as non-root. This means that we'd have to give the user access to write to the root of the app which is unnecessary since our app already has `cypress.json` and `cypress/`. Just giving you more context.

That said, seeding the project happens once and probably locally, right? Is this check really necessary?

**Comment by brian-mann** [comment]
I see - with that said, we should only do this check if we believe we need to seed something in the root folder.

**Comment by itskingori** [comment]
Yes. And this is why when the official Docker image set the user to a non-root user, many people were simply unable to work with it because of permission denied errors. See https://github.com/cypress-io/cypress-docker-images/issues/10. The solution then was just to use root and let user's do whatever they want on their own images.

Just wanted to check with you guys if you're aware of this use case and the implications of this part of the code to that use case.

That said, I think my work is done. I'm not sure if I should keep this open or not. 🤔

**Comment by brian-mann** [comment]
I agree with your suggestion and we'll get this out in a patch release.

**Comment by Bhavik-P** [comment]
I am currently experiencing the same issue while running it on Bitrise. Is there an expected timeline as to when this will get completed? If there is a working solution already I'd love to take a look at it.

**Comment by brian-mann** [comment]
@Bhavik-P @itskingori we talked about this at our team meeting today.

Even though we may not need to check for write access permissions to the project root - we still need write permissions to folders like `cypress/videos` or `cypress/screenshots` and the consensus was that these permissions would not be different than the `projectRoot`.

Can you two confirm or explain how this would NOT be the case? In other words, while we could remove this one specific check here, we'd have to add at least 2 more checks in other folders that are nested inside of the `projectRoot`. If the entire subtree has the same permissions it would simply error later in the process as opposed to here.

**Comment by Bhavik-P** [comment]
@brian-mann CI tools don't usually allow root access to apps. When I try to install Cypress locally (instead of globally) it doesn't pose any issues because the user has write-access to all subdirectories. The issue with this is that when I run the Cypress command, it says `command not found`. I have installed other libraries globally on Bitrise. Can you recommend something else that I can try? What if I don't want to use screenshots and videos?

**Comment by bahmutov** [comment]
Wait, you are installing Cypress globally as in “npm i -g cypress”?

**Comment by Bhavik-P** [comment]
Yes; installing it using `npm install --save-dev cypress` leads to bash a bash error `command not found`

**Comment by brian-mann** [comment]
@Bhavik-P to get on the same page I think we need to define terms a bit better.

You say: `root access to apps` but this makes no sense to me. Cypress does not require root access - it requires **write access** to the project's root directory. This is simply the folder that contains `cypress.json`.

We only write **inside** of that project. This is the same level of access that any `node_module` would need when running `npm install`.

In fact... how does your project ever run `npm install`? That needs the same level of write access as Cypress does to `node_modules`.

**Comment by Bhavik-P** [comment]
@brian-mann 
I was trying to install the package globally instead of with the project directory. When doing so, it required root access to write folders which for obvious reasons cannot be permitted. When I installed it in the project directory, I was able to install it, however, I couldn't just make a call to Cypress (`cypress run`) as I would when I globally installed it. This is where I went wrong. I knew something had to be wrong on my end so I looked at the docs and realized I missed a very important step. I needed to run cypress as such: `$(npm bin)/cypress`. I appreciate your time and thanks for the quick responses.

**Comment by brian-mann** [comment]
@itskingori do you mind weighing in on my comment here: https://github.com/cypress-io/cypress/issues/1281#issuecomment-400075705

We decided to fix this issue but once we investigated it, it made no sense how or why this would solve anything.

We'd really like to understand how Cypress doesn't have write access to the project root (where `cypress.json` is stored) and yet `node_modules` would have write access to the same exact folder?

**Comment by fgm** [comment]
Just have a similar problem, just worse: Cypress tries to create a directory below the system root, not just the project root, like `/.Trash-1002`, which I suspect might be related.

**Comment by DavideDaniel** [comment]
Here is Cypress attempting to gain access to root of a docker image where our install is happening. Please note that this isn't even us running cypress. The project is simply running it's normal build process but this time we have added cypress to the project and in the post install it attempts to access root to make a `/.cache/Cypress` directory.

**Comment by alexeagle** [comment]
Here's Angular's use case: for performance, we are rolling out a remote execution system where a farm of machines can run build/test actions.
When a test runs remotely, we copy over the declared inputs, run the test executor, then collect the outputs written to specified locations back to your machine. The remote execution uses a containerized FS where we prevent writes to the project directory, as these would be lost and not copied back to your machine.

I would like to run Cypress on such a remote build/test farm, which requires that we be able to configure the locations where it writes files, and it shouldn't check for write access in other locations.

**Comment by brian-mann** [comment]
@DavideDaniel per our installation docs we are pretty clear that Cypress will cache itself in the system `cache` folder appropriate for each operating system. In linux it would be `/.cache` - many other modules do this as well. This is very common, even moreso common for modules to store global configuration in places like `/.config`.

At any rate - per our installation docs you can with a simple environment variable change the location of this cache yourself here: https://docs.cypress.io/guides/getting-started/installing-cypress.html#Advanced

You can either skip the binary installation (if you have it cached elsewhere) or control where you want it to be installed.

What do you do about caching other things like your `node_modules`? Whatever mechanism you use for those you could use for Cypress which would prevent it from even needing to install when Jenkins loads.

**Comment by brian-mann** [comment]
@fgm see my comment here: likely this is the same issue with caching https://github.com/cypress-io/cypress/issues/1281#issuecomment-403233215

**Comment by brian-mann** [comment]
@alexeagle can you explain how if you want to disable write access to the project - Cypress would be able to generate any assets from the run? Things like logs, screenshots, videos, etc?

Can you suggest to us what you'd **like** Cypress to do instead?

Currently you can turn off taking screenshots and video in the configuration. Although we do have a hardcoded check to ensure the project root has write access. We can remove that check (or turn it into a warning) if need be. But I still don't understand how this really achieves anything considering you won't be able to capture anything from the test runs.

**Comment by alexeagle** [comment]
I assume that stdout is used for the primary pass/fail UI. I'd like to
configure a directory where those additional files are written.

**Comment by fgm** [comment]
@brian-mann thanks for the answer /.cache is rather uncommon AFAIK and not compliant with the linux Filesystem Hierarchy Standard. Per-user caches should go into ~/.cache, so typically in /root/.cache for caches for the root user ; while global runtime cache like these should probably go in /var/cache (/run/cache in the upcoming version of the FHS).

**Comment by brian-mann** [comment]
@fgm sorry I did not explain correctly - it DOES go into the user's `~/.cache` directory. We use this module here to create the paths: https://github.com/LinusU/node-cachedir

You can see that's where it puts it. I guess I'm now confused what the actual problem is now since this is the correct and intended behavior of how it installs.

@alexeagle You can already do exactly just that - Cypress provides options via its `cypress.json` to configure exactly where you want those folders to go. You can even override those values with environment variables specifically for CI.

**Comment by fgm** [comment]
@brian-mann : the problem I have is that it tries to write in /, to create directory` /.Trash-1002`, not in ~ like `/root/.Trash-1002`, which would be writable.

**Comment by Toxicable** [comment]
@brian-mann So if we disabled video / screenshot generation.
And you disable the hard coded write access check
Then there shouldn't be anything stopped us from using Cypress in a containerized write only FS, correct?

**Comment by publicvirtualvoid** [comment]
:( Could you please remove the FS write check, this is also blocking us.

**Comment by DavideDaniel** [comment]
@brian-mann ty for the tip about the advanced installation. Adding an env var pointed somewhere within the working directory path helped. 

For anyone else with a similar error to the one I mentioned, using `CYPRESS_CACHE_FOLDER` as referenced in https://docs.cypress.io/guides/getting-started/installing-cypress.html#Overriding-the-Binary-Cache-Folder might help.

**Comment by Toxicable** [comment]
Whats the resolution here? Are we getting the FS check removed?

**Comment by fgm** [comment]
@bahmutov this happens beffore the `(Run Starting)` message

npx cypress run -s .cypress/integration/meteor_spec.js 
Warning: We failed to trash the existing run results.

This error will not alter the exit code.

Error: EACCES: permission denied, mkdir '/.Trash-1002'



====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.0.3                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      1 found (meteor_spec.js)                                                           │
  │ Searched:   .cypress/integration/meteor_spec.js                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by Globegitter** [comment]
Any update on this? Would be great for the check to be removed for the read only FS use case. And Videos/Screenshots will be written into a custom writable location.

**Comment by Toxicable** [comment]
Could we get some movement here? It's a pretty easy code change from the looks of it.

**Comment by alexeagle** [comment]
FYI this may become a blocker for using Cypress under Angular CLI at some point, when we use a buildtool that creates a readonlyFS for hermeticity during testing

**Comment by Spartano** [comment]
Short answer: just delete the video folder and run cypress again.

Long answer: i have cypress dockerized within my project,
 so whenever i run cypress from docker it creates video and screenshot folders inside my project.

The problem for me was when i installed cypress globaly and wanted to run cypress locally, without docker, i was getting the required write access problem, but deleting the folders created by the dockerized version solved everything.

**Comment by Toxicable** [comment]
@jennifer-shehane Is there anything that can be done to pus forward this proposal?

**Comment by thomaswelton** [comment]
https://github.com/cypress-io/cypress/issues/2821#issuecomment-444109124

This fixed my issues running Cypress in Jenkins using the official docker image

**Comment by jennifer-shehane** [comment]
@Toxicable We are open to PR requests from anyone. Read our [contributing guides](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) to get started.

**Comment by RobDBob** [comment]
@jennifer-shehane link points to a dead location. Could you update please.

**Comment by lmiller1990** [comment]
I have been struggling with this for about a week now.

```
FROM node:10
RUN apt-get update && \
  apt-get install -y \
    libgtk2.0-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    xvfb \
    yarn
RUN mkdir /app
WORKDIR /app
COPY package.json /app/package.json
RUN CYPRESS_CACHE_FOLDER="/app" CYPRESS_RUN_BINARY="/app" yarn install
COPY . /app
RUN echo "Verifying Cypress..."
CMD ["yarn", "cypress:run"]
RUN echo "Done!"
RUN while true; do sleep 1000; done
```

Building: `docker build . -f Dockerfile.dev -t cypress-minimal`

Next, running this image  `docker run --rm --name cy cypress-minimal`

```
$ /app/node_modules/.bin/cypress verify
It looks like this is your first time using Cypress: 3.8.1

[04:19:24]  Verifying Cypress can run /root/.cache/Cypress/3.8.1/Cypress [started]
[04:19:25]  Verified Cypress!       /root/.cache/Cypress/3.8.1/Cypress [title changed]
[04:19:25]  Verified Cypress!       /root/.cache/Cypress/3.8.1/Cypress [completed]
Done in 2.72s.
```

Why is it still running a cypress installation in the `/root` directory, even though I see the cache and run binary directory to `/app`? When I run this on Jenkins (above example was run locally) where I do not have access to `/root`, it fails. Ideally I would install and execute from my `/app` directory.

**Comment by codler** [comment]
How can I add Cypress in Bitbucket pipeline?

**Comment by codler** [comment]
`npm install --unsafe-perm` solved it for me

**Comment by thecodejack** [comment]
I am also having permissions issue but creating a lock file inside `/tmp/cypress`. Since the machine can be used by multiple users in our case, if one user ran tests, other user can't coz of loosing control of `/tmp/cypress`. I am getting following error.


```
[OperationalError: EACCES: permission denied, open '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'

] {  cause: [Error: EACCES: permission denied, open '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'    ] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'
  },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'
}
Error: EACCES: permission denied, open '/tmp/cypress/4fa88ed0720f436f49e09ac33f63413a.lock'
```


Tried different ways mentioned above but didn't solve the issue.

**Comment by lmiller1990** [comment]
An option to turn off the write check would be useful... the problem most of have is likely a lack of dev-ops and linux permission experience, however if we are just running tests and writing to stdout, dropping the write access might make adopting Cypress easier for many people.
