### ISSUE TITLE
`.type` support for `force`

### ISSUE THREAD

**Issue by noah-potter** [cypress-io/cypress#1284]
### Current behavior:
`.type` doesn't support `force` option to allow typing on non-body/non-input elements

### Desired behavior:
Allow typing to be forced onto any element

Is there a reason only body was allowed to be typed on?

**Comment by brian-mann** [comment]
Is this a duplicate of https://github.com/cypress-io/cypress/issues/586?

What element do you want to type into that's a non-input?

**Comment by noah-potter** [comment]
Looks like a duplicate, I missed that earlier. I continued the discussion there.
