### ISSUE TITLE
Ability to change URL of all XHR requests

### ISSUE THREAD

**Issue by Raathigesh** [cypress-io/cypress#1285]
For example, if the app is making a call to `http://actual.api.com/`,  we want to proxy the request to `http://mock.api.com/`.  Is there a way to do this in a common place so all the requests would be proxied? 

I tried mutating the `url` property of the request as below but that doesn't seems to work.

```js
 cy.server({
        onRequest: request => {
           request.url = request.url.replace('actual.api.com', 'mock.api.com');
           request.xhr.url = request.url.replace('actual.api.com', 'mock.api.com');
        }
      });
```

Any pointer would be appreciated!

**Comment by brian-mann** [comment]
You would need to do this in your app code. You could go off of a query param like `?env=test` or just when bundling your app code swap out the baseUrl.

It may be possible for us to accommodate this feature later with #687 but it really feels like it belongs in your own code base.

**Comment by Raathigesh** [comment]
Thanks. It would be nice for us to do it entirely in cypress. Will wait for #687.
