### ISSUE TITLE
CLI doesn't finish

### ISSUE THREAD

**Issue by ibesora** [cypress-io/cypress#1286]
- Operating System: Windows 7
- Cypress Version: 1.4.2
- Browser Version: Electron

### Is this a Feature or Bug?
Bug

### Current behavior:
CLI never finishes running the test when visits point to our website

### Desired behavior:
CLI should stop

### How to reproduce:
I forked the cypress-test-tiny repo on my account and changed the test accordingly so you can reproduce it. https://github.com/ibesora/cypress-test-tiny

### Additional Info (images, stack traces, etc)
I've run cypress with the debug environment variable and, after printing the test report, prints a lot of cypress:server:timers sending timer id from 20 onward and it keeps printing them after some time and it enters some kind of infinite loop afterwards. 
You can see what it prints here:
```
engine:ws writing "3" 
cypress:server:timers child sending timer id 322
engine:ws received "2" 
engine:socket packet 
cypress:server:timers clearing timer id 325 from queue { '325': { args: [], ms: 85000, cb: [Function] } } 
cypress:server:timers queuing timer id 326 after 85000 ms 
engine:socket got ping 
engine:socket sending packet "pong" (undefined) 
engine:socket flushing buffer to transport 
cypress:server:timers child received timer id 326 
engine:ws writing "3" 
...
```

I've also tried two more things. Changing the visit URL and changing the wait value.
If I change the URL it works as expected so it seems to be a combination of cypress and our website. 
If I change the wait value to a lower value cypress doesn't always enter the infinite loop so some times it finishes and some others doesn't. Every time I change the value to a higher one it seems as if the probability of getting stuck in an infinite loop is bigger.

**Comment by brian-mann** [comment]
Hmm... not sure I can reproduce. Your site loads super slow, but it does eventually load and passes the test. The `cy.wait(...)` is not applicable or useful here. Cypress won't resolve the `cy.visit` until the page load finishes. During loading the page there is a redirect and therefore it awaits that as well before resolving. It takes approx 20ish seconds but does eventually finish.

The logs that you're posting are normal - those timers are from Socket.io. You can exclude them by writing `DEBUG=cypress:*,-cypress:server:timers cypress open`

**Comment by ibesora** [comment]
Hi again @brian-mann I've just found it was something on my side. We are using mocha 4 and I have came across this issue mochajs/mocha#2879
Seems mocha 4 has changed its default behaviour and now it doesn't close when tests finish.
Sorry about that!
