### ISSUE TITLE
Login through a gateway website is timing out

### ISSUE THREAD

**Issue by DMarinsa** [cypress-io/cypress#1287]
### Current behavior:
I'm login through a gateway website and it's timing out.

### Desired behavior:
-Access to localhost and redirect me to login page
-insert login credentials
-redirect me back to original website logged << this is the crashing point

#### Test code:

```beforeEach(()=>{
    cy.visit('http://localhost:3001/')
    cy.get('#username')
        .type('user');
    cy.get('#password')
        .type('pass');
    cy.get('#fm1 > div > section.row.btn-row > input.btn.btn-submit.btn-block')
        .click();
})
```

### Additional Info (images, stack traces, etc)

CypressError: Timed out after waiting '60000ms' for your remote page to load.
Your page did not fire its 'load' event within '60000ms'.
You can try increasing the 'pageLoadTimeout' value in 'cypress.json' to wait longer.
Browsers will not fire the 'load' event until all stylesheets and scripts are done downloading.
When this 'load' event occurs, Cypress will continue running commands.
Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'Test Drag and Drop, in cypr...'

- Operating System: Lubuntu
- Cypress Version: latest
- Browser Version: Chrome 64

**Comment by brian-mann** [comment]
Unfortunately there's not enough information here to debug anything. We'd need a reproducible repo or more information about how you're logging in. Is this redirecting across another different domain than `localhost:3001`?

**Comment by DMarinsa** [comment]
Yes, it's using a CAS protocol to login

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
