### ISSUE TITLE
Console log should display when subject is changed in an assertion (or print return)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#129]
When writing assertions that change the subject, ie:

``` javascript
cy.get("a").should("have.attr", "title", "Help")
```

In the command log on click of the command, the subject in the code above only displays the original subject `<a>`. It'd be nice if the command log indicated that the subject changed, or even just printed the return of the assertion (in this case `"Help"`).

**Comment by brian-mann** [comment]
Closing in favor of #555.
