### ISSUE TITLE
Sometimes .type() doesn't enter the space between words...

### ISSUE THREAD

**Issue by neiled** [cypress-io/cypress#1298]
- Operating System: MacOS
- Cypress Version: 1.4.1
- Browser Version: ChomeCanary

### Is this a Feature or Bug?
Bug

### Current behavior:
Sometimes, on two different machines, using Type('Example Name') actually enters ExampleName in the input box.

### Desired behavior:
Enters 'Example Name'

### How to reproduce:
I've really tried hard to reproduce this consistently and I cannot. It only seems to be the 'space bar' that sometimes is missed, I've never had any other characters missed.

#### Test code:

```js

```

**Comment by neiled** [comment]
So just to add some more information to this. Here is the command that sometimes fails at the last line. When I check the video you would see 'ExampleName' instead of 'Example Name'. This is also what's entered in the textbox, it's not a rendering issue.

```
Cypress.Commands.add('signup', email => {
  cy.visit('#/signup')
  cy.get('input[name=email]').type(email, { force: true })
  cy.get('input[name=username]').type('Example Name')
  cy.get('input[name=password]').type('password')
  cy.get('input[name=passwordConfirm]').type('password')
  cy
    .get('span')
    .contains('Sign Up')
    .click()
  cy.contains('Hi again Example Name')
})


```

**Comment by jennifer-shehane** [comment]
@neiled What is the input type of the username input? Is it of `type='email'`?

**Comment by neiled** [comment]
@jennifer-shehane no I just double checked, thanks. It is using vee-validate though, let me turn off validation for this field and see if the error keeps happening. It's pretty rare though, like I said it's hard to reproduce, but even happened in my circleci environment so not environment specific that I can tell.

**Comment by neiled** [comment]
I'm going to close this issue and reopen it again if I can definitely confirm this is a cypress issue and not some weird validation issue on my side, thanks for the help.
