### ISSUE TITLE
Allow running Cypress binary installed in arbitrary folder

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1299]
## Feature

Instead of always taking the binary from `node_modules/cypress/dist`, allow passing path to the binary folder dynamically.

- using environment variable `CYPRESS_BINARY_LOCATION`
- using CLI argument `--binary-location`

Part of caching binary epic

**Comment by bahmutov** [comment]
A sample implementation is here https://github.com/cypress-io/cypress/commit/0d28ff83af42468b22e1e3f2da9139301bfa48c3 but needs better API design. Currently requires passing folder function into each utility function.

**Comment by Bkucera** [comment]
fixed with https://github.com/cypress-io/cypress/issues/1300
