### ISSUE TITLE
"Sorry couldn't find any tests..." message displaying on .only after fixing error.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#13]
**To recreate:**
1. In test file, have syntax error where "Sorry couldn't find any tests" error displays.
2. Fix syntax error: all tests will auto-refresh and run in browser.
3. Set an `.only` on a test: The "Sorry..." message will display alongside the `.only` test.

![screen shot 2015-04-06 at 11 19 13 am](https://cloud.githubusercontent.com/assets/1271364/7006464/53e30d22-dc4f-11e4-8798-8aa34ac1cf24.png)

**Comment by brian-mann** [comment]
Fixed in [`0.6.8`](https://github.com/cypress-io/cypress/wiki/Changelog#068-0652015).
