### ISSUE TITLE
Support arbitrary list of methods, (Cf: Express)

### ISSUE THREAD

**Issue by NoMan2000** [cypress-io/cypress#1302]
### Is this a Feature or Bug?

Feature.

### Current behavior:

Currently, when using `cy.request`, you are limited to a handful of the most popular HTTP verbs.  However, there are far more verbs than the official ones, such as in [express API](http://expressjs.com/en/api.html#routing-methods).  Without supporting these, it makes it hard to test methods like `subscribe` and `unsubscribe`.

### Desired behavior:

Allow arbitrary HTTP methods to be used.  

### How to reproduce:

```js
cy.request({
        method: 'SUBSCRIBE',
        url: `users/1`,
        body: email
      }).then(() => {});
```

Result:  CypressError: cy.request() was called with an invalid method: 'SUBSCRIBE'.  Method can only be: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS

Possibilities:  Allow an extra flag to be checked that will turn off method checking.

**Comment by brian-mann** [comment]
Do you mind finding the code that express uses for this list... wanted to see if there was an npm package somewhere we could borrow from that lists them all out so we don't have to maintain them ourselves

**Comment by NoMan2000** [comment]
Sure.  They're using the methods package.

https://www.npmjs.com/package/methods

Then loading that into the prototype:

https://github.com/expressjs/express/blob/master/lib/router/route.js

That's overkill though, I think the basic list from methods has what you're looking for.

https://github.com/jshttp/methods/blob/master/index.js

**Comment by brian-mann** [comment]
Perfect this is what I was looking for. We can add these to the driver. We'll uppercase them though when running them through the validation.

**Comment by cdanielsen** [comment]
Any sense for a timeline of when this will be integrated? I'm testing an app that has a file system like component that makes PROPFIND, MOVE, COPY etc. calls where this would be very useful

**Comment by jennifer-shehane** [comment]
Need to make sure this works for cy.route() and cy.request()

**Comment by ivan-kleshnin** [comment]
My APIs use `SEARCH` method which is a part of the current HTTP standard. Not even a custom verb. And I'm getting the same error. Not good 😞
