### ISSUE TITLE
Desktop: Setup project modal doesn't display 'No orgs' message when only default org

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1306]
If there are no orgs available to choose in dropdown, should display message about how to add new org.

**Currently can only pick --Select Org-- in dropdown**
<img width="801" alt="screen shot 2018-02-13 at 4 31 04 pm" src="https://user-images.githubusercontent.com/1271364/36174792-66476706-10db-11e8-82d7-c69e60c949e1.png">

**Should display this instead**
<img width="800" alt="screen shot 2018-02-13 at 4 35 45 pm" src="https://user-images.githubusercontent.com/1271364/36174983-fe33c866-10db-11e8-8069-391c4aeaa48e.png">

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
