### ISSUE TITLE
[bug]system-proxy exclusion list not used

### ISSUE THREAD

**Issue by BasieP** [cypress-io/cypress#1312]
- Operating System: windows
- Cypress Version: 1.4.2
- Browser Version:chrome 63

### Current behavior:
when testing a self-hosted website (like localhost:8888 in my case) the requests run trough the cypress proxy. requests not for cypress go trough to the system proxy.
Only when we request localhost:8888 (with cy.visit) we see the 404 response from our corporate proxy server.
The point is that the request shouldn't go TO the proxy server cause the host (localhost) is on the system proxy exclusion list.

When opening a new tab in the chrome spawned with cypress, we still can't go to localhost:8888

When opening my own chrome (without the cypress proxy) i CAN navigate to localhost:8888.

My cypress chrome chrome://net-internals/#proxy page says:
Effective proxy settings
Proxy server: localhost:1317  //<-- the port cypress randomizes

My normal chrome chrome://net-internals/#proxy page says:
Proxy server: proxy.mydomain.local:8080
Bypass list: 
  *.local
   127.0.0.1
  localhost
  <local>
Source: SYSTEM

(where <local> and localhost/127.0.0.1/::1 etc. are the same)

### How to reproduce:
configure a system proxy server, and add localhost to the exclusion list.
Host your website (in iis, or via some npm package) on localhost, and use cy.visit to test it.

**Comment by brian-mann** [comment]
There are a number of proxy related bugs in Cypress - basically we aren't respecting or handling proxies and we should. There's nothing wrong with the Chrome network proxy settings - the browser needs to route all traffic through Cypress who **then** needs to reroute that through your proxy server settings.

There are a few workarounds if you search for `proxy` in our issues you'll find. Basically setting some env vars will force the underlying libs to utilize your system proxy. It may or may not work. This is something we should get fixed but it's a lower priority than some other things we're doing.

**Comment by flotwig** [comment]
As Brian said, all traffic (even to localhost) should flow through the Cypress proxy. This issue describes Cypress working as designed so I will close it for now.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/3531
