### ISSUE TITLE
Is `cypress run` using a different browser than `cypress open`?

### ISSUE THREAD

**Issue by gr2m** [cypress-io/cypress#1314]
- Operating System: Mac OS 10.11
- Cypress Version: 
  - Cypress package version: 1.4.2
  - Cypress binary version: 1.4.2
- Browser Version: Chrome 64.0.3282.140

### Is this a Feature or Bug?

Bug

### Current behavior:

A test works fine when run with `cypress open` but fails with `cypress run`

### Desired behavior:

Both should behave exactly the same

### How to reproduce:

https://github.com/gr2m/cypress-test-tiny/tree/cypress-1314

#### Test code:

See link to repository above

### Additional Info (images, stack traces, etc)

error for `cypress run`

![image](https://user-images.githubusercontent.com/39992/36236259-173900aa-11aa-11e8-85f8-bf2998d12aa7.png)

error for `cypress run --headed`

![image](https://user-images.githubusercontent.com/39992/36236289-34b5ae6c-11aa-11e8-8cbd-22373087ad5f.png)

**Comment by brian-mann** [comment]
Yes, it uses Electron by default.

This is documented here and here...

- https://docs.cypress.io/guides/guides/launching-browsers.html#Electron-Browser
- https://docs.cypress.io/guides/guides/command-line.html#cypress-run

**Comment by gr2m** [comment]
haw man I put lots of time into creating the reproducable test case, do you think there is a way to workaround it on cypress-level or is that an electron bug out of your control?

**Comment by gr2m** [comment]
Can I run cypress with a headless chrome?

**Comment by brian-mann** [comment]
The electron browser is based on Chromium 53 - which is much older than the newest version of Chrome 64 - and therefore does not have the equivalent browser API's. You'd need to use polyfills.

However - the good news is that we are bumping Electron in our next release `2.0.0` which will bump Chromium from 53 to 59 which will fill in the big gaps.

**Comment by brian-mann** [comment]
You can just run Cypress with Chrome itself by passing the `--browser` flag from the CLI so it's the same browser as you select with `cypress open`

**Comment by gr2m** [comment]
I run the tests on Travis CI, so I need it to run headlessly

**Comment by brian-mann** [comment]
We have docker containers that have all of Cypress dependencies including the latest browsers you could use.

TravisCI enables you to install Chrome, which Cypress will automatically orchestrate correctly and pick up.

https://docs.travis-ci.com/user/chrome

**Comment by brian-mann** [comment]
Cypress already does everything under the hood to run in CI - whether its with the built in Electron, or a headed browser like Chrome - it'll all just work

**Comment by brian-mann** [comment]
Or just sit tight for maybe 24-48 hours and Electron 59 will be the default and your `fetch` will work correctly.

**Comment by gr2m** [comment]
wow I didn't know that using Chrome on Travis just works out of the box, thanks Brian! Easy as pie https://github.com/gr2m/octokit-rest-browser-experimental/pull/26/files 🙌

**Comment by brian-mann** [comment]
As long as the system dependencies are installed (which they are in Travis) Cypress knows how to orchestrate itself to run in a headless CI environment without you doing anything. If Cypress detects a system dependency is missing it should print this out to you as well.

As a final footnote - in case you ever move off of Travis, we also have docker containers with everything prepackged that will also "just work".

I'll note this issue when we release `2.0.0` which has the Chromium 59 bump. You could then move back to that because we currently only record a video when running in Electron headlessly. This will eventually be fixed to record for headed browsers too, but that'll be the easiest thing today.
