### ISSUE TITLE
allow to disable cache when running tests in browser

### ISSUE THREAD

**Issue by gr2m** [cypress-io/cypress#1315]
### Current behavior:

When testing 301 redirect behavior that differs based on passed headers the tests will fail after first run because a browser caches 301 redirects

### Desired behavior:

It would be nice to test each run in isolation by disabling the browser cache

### How to reproduce:

https://github.com/gr2m/cypress-test-tiny/tree/cypress-1315

#### Test code:

See link to repository above

### Additional Info (images, stack traces, etc)

Browser redirects based on cached 301 redirect

![image](https://user-images.githubusercontent.com/39992/36236601-cca6188c-11ab-11e8-95e6-00670e5f5e02.png)

Which makes test fail

![image](https://user-images.githubusercontent.com/39992/36236609-d188b9fe-11ab-11e8-9723-71958c0fe47d.png)

Test pass when "disable cache" flag is checked (in the network tab of developer tools)

- Operating System: Mac OS 10.11
- Cypress Version: 
  - Cypress package version: 1.4.2
  - Cypress binary version: 1.4.2
- Browser Version: Chrome 64.0.3282.140

**Comment by brian-mann** [comment]
This is true. We intend to do this as part of the Lifecycle Events Epic. https://github.com/cypress-io/cypress/issues/686

We also just closed an issue today related to this - we are now clearing the cache once when the browser is launched - but not in between tests. We'll do that as per the Lifecycle events.

https://github.com/cypress-io/cypress/issues/1124

As for testing this today - there's not really any reason to do a browser test to do this as per your repo - you can just use `cy.request()` or just an API test for this.

**Comment by gr2m** [comment]
Thanks feel free to close if you like, I worked around the issue in my case.

**Comment by jennifer-shehane** [comment]
Was just reminded that `cy.reload(true)` should reload the page without using the cache. May be a solution for some. https://on.cypress.io/reload#Requirements
