### ISSUE TITLE
contains() breaks with a regex containing a `'`

### ISSUE THREAD

**Issue by jbr** [cypress-io/cypress#1322]
- Operating System: macos
- Cypress Version: 1.4.2
- Browser Version: chrome 65

### Is this a Feature or Bug?
bug

### Current behavior:
`cy.get('some selector').contains(/any regex containing a '/)` results in an error

### Desired behavior:
to select any dom nodes that match the provided regex, as is the behavior for any regex not containing a `'`

### How to reproduce / test code
https://github.com/cypress-io/cypress-test-tiny/pull/26

**Comment by brian-mann** [comment]
Released in [`2.0.1`](https://docs.cypress.io/guides/references/changelog.html#2-0-1).
