### ISSUE TITLE
Cypress manage organizations link does not work

### ISSUE THREAD

**Issue by dauledk** [cypress-io/cypress#1324]
- Operating System: Mac OS 
- Cypress Version: 1.4.2
- Browser Version: Version 63.0.3239.132 (Official Build) (64-bit)

### Is this a Feature or Bug?
Bug

### Current behavior:
In cypress --> Runs --> when you click on the link "(manage organizations)" an empty instance of chrome opens

### Desired behavior:
Should open something about managing organizations?

### How to reproduce:
Click on the link

### Additional Info (images, stack traces, etc)
![screen shot 2018-02-16 at 09 01 20](https://user-images.githubusercontent.com/9967422/36298417-59b6a334-12f8-11e8-8760-f7d64b5c07fa.png)

**Comment by jennifer-shehane** [comment]
I am completely unable to recreate this. We have tests around this link as well. It should open this link just FYI -> https://dashboard.cypress.io/#/organizations

It would require the internet, maybe there was an issue with your connection? Can you reliably reproduce this?

**Comment by dauledk** [comment]
Hi @jennifer-shehane - sorry for the long dealy. 

I think the issue is related to having multiple instances of chrome on Mac OS.

So to reproduce I need to have cypress running in chrome, or for example unit tests in angular. And btw - no links work then so I guess it has nothing to do with Cypress.
