### ISSUE TITLE
sinon matchers not working as expected in withArgs

### ISSUE THREAD

**Issue by brucewpaul** [cypress-io/cypress#1328]
- Operating System: mac osx
- Cypress Version: 1.4.2
- Browser Version: 64

### Is this a Feature or Bug?

bug

### Current behavior:

```js
// this returns true
const callback = sinon.stub(window, 'fetch');
callback.withArgs(sinon.match.any).returns(true);

console.log(window.fetch('/api'));

// this never matches and serverStub is never called
cy.stub(win, 'fetch').withArgs(sinon.matches.any).callsFake(serverStub)
```

### Desired behavior:

To be able to use withArgs the same way you would be able to as in sinon

### How to reproduce:

see above

#### Test code:

```js
import sinon from 'sinon';

const stub = {
  '/api/v2/stub': { data: 'test stub' },
};

function responseStub(result) {
  return {
    text() {
      return Promise.resolve(result);
    },
    ok: true,
  };
}

Cypress.Commands.add('visitStubbed', (location, options = {}) => {

  // this works as intended and console logs true
  let callback = sinon.stub(window, 'fetch');
  callback.withArgs(sinon.match.any).returns(true);

  console.log(window.fetch('/api')); // Returns true

  function serverStub(url, req) {
    // this never gets called
    const resultStub = stub[url];

    if (resultStub) {
      return Promise.resolve(responseStub(resultStub));
    }

    return fetch(url)
  }

  cy.visit(location, {
    onBeforeLoad: (win) => {
      cy.stub(win, 'fetch')
        .withArgs(sinon.match.any)
        .callsFake(serverStub);

      win.fetch.callThrough();
    },
  })
})
```

**Comment by chrisbreiding** [comment]
Cypress currently uses sinon `3.2.0` and the latest version is `4.3.0`, so that might be the issue. We'd need to make sure there won't be any breaking changes before upgrading.

In any case, in your example, is `withArgs(sinon.match.any)` necessary? Can't you just leave it out and it will match any args by default?

**Comment by brucewpaul** [comment]
this was just for a clear cut test case. I'm trying to do `withArgs(sinon.match(/api/))` so that it is only stubbing api calls. Additionally, sinon.match has been since before `3.2.0`

**Comment by brucewpaul** [comment]
and thanks for the quick response!

**Comment by Saulis** [comment]
@chrisbreiding any progress on this? Having pretty much exactly the same issue as @brucewpaul. Thanks!

**Comment by jennifer-shehane** [comment]
I've opened a pull request to bump sinon from 3.2.0 to 3.3.0 here: https://github.com/cypress-io/cypress/pull/2450

**Comment by akheron** [comment]
It seems that `sinon.match` works just fine even with sinon 3.2.0 and Cypress before 3.1.5. The thing is that you should access sinon from `Cypress.sinon` instead of importing it. The following modification to OP's test code makes it work:

```
 cy.stub(win, 'fetch')
        .withArgs(Cypress.sinon.match.any)
        .callsFake(serverStub);
```
