### ISSUE TITLE
Proposal: Implement intelligent caching layer

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1332]
Since Cypress is a fairly advanced proxy sitting between the browser and origin servers - it's in a perfect situation to implement its own special caching mechanisms.

This is important because since Cypress modifies response streams on the fly for things like `.html` and `.js` files - adding a middle tier cache layer can avoid needing to reparse these over and over again.

Normally, when the browser handles things like `E-Tag` coordination via `If-None-Match` headers then our proxy doesn't need to rewrite contents.

However, this option can be turned out by Developers using the Dev Tools `Disable Cache` option. Additionally, since we clear the browser's cache before opening it, it'll always be blank.

Unzipping, rewriting, and then zipping is a potentially expensive operation, that can take up to a couple hundred milliseconds.

**Proposal**

After rewriting a files contents - we should save it to disk by E-Tag ID. The next time the origin server replies with a non `304` status code - instead of rewriting the contents at that time - if we have a matching E-Tag file, just stream it from disk instead.

This disk cache should be ephemeral - and should be stored on a per project basis, and should be destroyed prior to starting a project. This prevents stale cache build-up, or if algorithms change we won't have to worry about purging it.

This will create speed ups when switching between spec files, or if the `Disable Cache` option is enabled in the Developer Tools.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close this issue.
