### ISSUE TITLE
Accessing Fixture Data: "this is undefined".

### ISSUE THREAD

**Issue by johnunclesam** [cypress-io/cypress#1340]
### Current behavior:

 I'm following https://docs.cypress.io/api/commands/fixture.html#Accessing-Fixture-Data

```
cy.fixture('users').as('usersJSON')
cy.route('GET', '/users/**', '@usersJSON')

  // ...later on...

cy.get('#email').then(() => {
  // we have access to this.usersJSON since it was aliased
  console.log(this.usersJSON); // => this is undefined
})
```

I cannot access `this.usersJSON` in my test. Why?

Cypress: 2.0.1
NodeJS: 8.9.4

**Comment by brian-mann** [comment]
My guess is that you're using fat arrows everywhere which always preserves the outer context. This is why Mocha does not recommend using them.

Switch your `it` block not to use fat arrow and it will work.

https://mochajs.org/#arrow-functions

**Comment by brian-mann** [comment]
I much more comprehensive doc about aliases and variables is here: https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html

That fully explains how to work through these scenarios.

**Comment by johnunclesam** [comment]
@brian-mann Thanks, but maybe this guide should be edited removing fat arrows: https://docs.cypress.io/api/commands/fixture.html#Accessing-Fixture-Data

**Comment by bahmutov** [comment]
@johnunclesam using fat arrow in testing is always a recipe for disaster :) https://glebbahmutov.com/blog/test-closures/

**Comment by brian-mann** [comment]
@johnunclesam to be clear - you are right that by changing the fat arrow in the docs code would fix the problem - but also by changing the fat arrows in the `it(...)` block would also fix the problem without having to modify the example code (not shown in the docs). 

Per the docs I sent above - the preferred way of accessing aliases is just to go back through `cy.get` which avoids the use of lexical `this` at all times.
