### ISSUE TITLE
cy.visit and redirects. cy.location("pathname") doesn't work.

### ISSUE THREAD

**Issue by johnunclesam** [cypress-io/cypress#1341]
- Cypress Version: 2.0.1
- Browser Version: Chrome 64

This is a **Bug** (at least I think).

### Current behavior:

I fail the login voluntarily because I need to try the redirect to `/login` path.

But instead I got this strange behaviour:

- `cy.visit("/dashboard")` takes me to `/dashboard`;
- my website **redirects** the browser to `/login` path;
- `cy.location("pathname").should("eq", "/dashboard")` is OK for Cypress;
- `cy.location("pathname").should("not.eq", "/login")` is OK for Cypress;
- after all this he says in test runner: "_(NEW URL) http://localhost:8080/login_"

### Desired behavior:

I expected a different flow. Because I thought Cypress waited for the redirect. But it doesn't. **Why?**

### How to reproduce:

_commands.js_:
```javascript
Cypress.Commands.add("login", (user, password) => {
  cy
    .request({
      url: "http://localhost:3000/api/login",
      method: "POST",
      body: { user, password: "badPassword" } // bad password because I want to fail this login
    })
    .then(resp => {
      expect(resp.status).to.eq(200);
      cy.visit("/dashboard");
      cy.location("pathname").should("eq", "/dashboard");
      cy.location("pathname").should("not.eq", "/login");
    });
});
```

_myTest.spec.js_:
```javascript
it.only("Login with API", function() {
  cy.login(user, password);
});
```

**Comment by brian-mann** [comment]
Depending on how your app is built - everything you posted is technically possible of happening and being correct. We'd need to see a screenshot of the Command Log (the left side) to understand better what is happening and in the order that it's happening.

This is all going to depend on whether or not the server is making the redirect as part of the `visit`, or Javascript is - and if Javascript is, is it happening through asynchronously loaded JS using `window.location.xxx`?

With that said, there are a **lot** of internal tests around this behavior - and I understand if you cannot post a reproducible repo, but it would be helpful for you to deconstruct your app into the smallest and simplest steps to reproduce this potential problem. Likely it's a small amount of code.

**Comment by brian-mann** [comment]
To clarify - redirects that happen as part of the `cy.visit` **are** awaited. It's not clear by what you say here: `my website redirects the browser to /login path;` - what exactly you mean. 

Your website as in your front end javascript code? If that's the case, and this JS is loaded asynchronously, then by all means what Cypress is seeing and those assertions would absolutely pass the way you've written them.

**Comment by johnunclesam** [comment]
Dear @brian-mann, thanks four your precious and speedy answers.

The problem I have is because when my website loads it check the localstorage key, if there is something (at least one character) it dispatch a redux "SUCCESSFUL_LOGIN_ACTION", so the route `/dashboard` is correctly accessed (so Cypress is OK) and after that an action "VERIFY_USER_LOGIN" is dispatched and now it redirects to `/login` because the token in localstorage is bad.

So I think Cypress is OK. What I need to understand is how to handle this scenario.

**Comment by brian-mann** [comment]
You would likely put all this logic in your `login` custom command. For instance, your server is returning a 200 on a bad password. Why? you could conditionally check the status code to know what happened and then to conditionally add assertions...
