### ISSUE TITLE
 Open Selector Playground - Select element (Tooltips)

### ISSUE THREAD

**Issue by pgroot91** [cypress-io/cypress#1351]
# Open Selector Playground - Select element (Tooltips)

Operating System: Windows 10
Cypress Version: 2.0.2
Browser Version: Chrome 64 (64 bits)

### Is this a Feature or Bug?

Bug (ish)

### Current behavior:

The tooltips are showing correctly above the fold of the viewport. Result that the tooltips are floating somewhere above the fold when you are selecting/inspecting something under the fold.

### Expected behavior:

The tooltips showing correctly also under the fold.

### See attachments:

![qa - cypress](https://user-images.githubusercontent.com/6934501/36427919-c2247c80-164e-11e8-88b1-b29050b9b68e.jpg)

**Comment by pgroot91** [comment]
After running the example_spec.js file i realised the issue with the tooltips are not in the kitchen Sink demo. So i have the feeling our application is breaking the the tooltips in Cypress.

**Comment by jennifer-shehane** [comment]
@chrisbreiding did look into this the other day. Were you able to recreate the issue Chris?

**Comment by chrisbreiding** [comment]
I was able to find an instance of this using the Cypress dashboard, but I haven't been able to boil it down to a simple reproduction or figure out what exactly is causing it.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?
