### ISSUE TITLE
regression: `onBeforeLoad` handler not called when overwriting `visit`

### ISSUE THREAD

**Issue by sokki** [cypress-io/cypress#1353]
# Current behavior:
`onBeforeLoad` hook is only getting called when defined inline with `cy.visit(url, { onBeforeLoad })`.

### Desired behavior:
`onBeforeLoad` hook should get called when defined with `Cypress.Commands.overwrite('visit', ...)`

### How to reproduce: 
```
git clone https://github.com/sokki/cypress-test-tiny
npm i
npm run cypress:run
```
or look at circleci build: https://circleci.com/gh/sokki/cypress-test-tiny/1

### Additional Info (images, stack traces, etc)
It seems, like the Issue was fixed in a previous version: https://github.com/cypress-io/cypress/issues/640

Test is visiting a static site (https://github.com/sokki/cypress-test-tiny/tree/master/static), deployed at https://static-fiwmrcysbv.now.sh
The site just writes `window.mocked || 'nope'` to the body 

- Operating System: macOS 10.13.3 and Linux @ circleci
- Cypress Version: 2.0.2
- Browser Version: Chrome and Electron

**Comment by brian-mann** [comment]
We added tests for this - so we'll look into how it would be possible for this to be a regression (if we can reproduce).

Regardless - you shouldn't be overriding `cy.visit` to accomplish this. There are Cypress events that you can utilize to automatically apply a callback function at the moment that `onBeforeLoad` would fire.

Just hook up to the `window:before:load` event here: https://docs.cypress.io/api/events/catalog-of-events.html#Window-Before-Load

**Comment by sokki** [comment]
I didn't know, that you can bind to those App Events 'globally' using `Cypress.on`. That does the trick for me - thank you very much!

The bug is still weird. Let me know, if I can help you to investigate.

**Comment by adamdicarlo** [comment]
onBeforeLoad works fine for me when overwriting `visit`. could you paste your code overwrite code here?

**Comment by sokki** [comment]
@adamdicarlo you can find the test-repo here: https://github.com/sokki/cypress-test-tiny

```
Cypress.Commands.overwrite('visit', (originalFn, url, options) => {
  return originalFn(url, {
    onBeforeLoad (win) {
      win.mocked = 'mocked'
    }
  })
})
```

**Comment by jennifer-shehane** [comment]
This appears to be fixed. Tested in Cypress 3.4.0 and it passes. Closing as resolved.

<img width="554" alt="Screen Shot 2019-07-23 at 5 33 11 PM" src="https://user-images.githubusercontent.com/1271364/61707221-f7b01d00-ad6f-11e9-9387-a97e87dda187.png">
