### ISSUE TITLE
Typescript example recipe workflow

### ISSUE THREAD

**Issue by SaltyDH** [cypress-io/cypress#1356]
## Current behavior: 
Using the Webpack with Typescript example recipe, Typescript compilation issues cause the plugin to crash. This brings you to the following screenshot.

![image](https://user-images.githubusercontent.com/2009544/36455721-20f68462-16ed-11e8-9aea-bdddf31dadc9.png)
(Image edited to remove sensitive information)

Additionally, the Try Again button on the Cypress app is at the bottom of the error message. When the error is quite lengthy, I spend a decent amount of time scrolling or using keyboard shortcuts to get to the bottom of the window so that I can click the Try Again button.

### Desired behavior:
The plugin doesn't crash due to compilation issues. It keeps monitoring for changes and the Typescript compilation issues are displayed in the running browser session.

The Try Again button remains above the error message to reduce the time needed to restart the plugin.

### How to reproduce:
Using the [Webpack with Typescript recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/preprocessors__typescript-webpack), add random text to the spec file such that the text cannot be resolved as a valid command or statement.

- Operating System: Windows 10
- Cypress Version: 2.0.2
- Browser Version: Chrome 64

**Comment by brian-mann** [comment]
I know we currently watch the file for changes - after you introduce an error and then revert the problem (and get back to working code) does it automatically update or do you have to click "Try Again" ?

**Comment by SaltyDH** [comment]
Yeah, had the same thought. For me, it's stopped watching. I always have to click try again even when the compilation error has been resolved.

**Comment by brian-mann** [comment]
@chrisbreiding ^^

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
