### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#1362]
- Operating System: Windows 7
- Cypress Version: 1.4.1
- Browser Version: Chrome 63

### Is this a Feature or Bug?
Bug

### Current behavior:
Receiving the following error in console dev tools:

```
Uncaught Error: only one instance of babel-polyfill is allowed

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```

### Desired behavior:
Not to receive this error

### How to reproduce:
Visit a page that requires babel-polyfill

There is a known issue to babel-polyfill [here](https://github.com/babel/babel-loader/issues/401).

**Comment by jennifer-shehane** [comment]
This error originated from your application code, not from Cypress. You can 

1. Fix this issue in your application code. 
2. Turn this off by listening to the 'uncaught:exception' event. https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by paulpruteanu** [comment]
If I open the same page in a browser, I don't receive this error message. It's only in cypress that I get it.

**Comment by Sartory** [comment]
Having the same problem if I open the website with Cypress. 
In the normal browser no error message regarding babel is shown.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to leave this issue closed if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by hiren0007** [comment]
I regularly getting Uncaught Error: Script error, while I tried to open URL https://harper-morpho-luna.myshopify.com by the command cy.visit('https://harper-morpho-luna.myshopify.com').
If anyone has any idea, then let me know ASAP.

**Comment by rsvenkata** [comment]
I changed the mode from electron to Chrome and it works fine.

**Comment by jennifer-shehane** [comment]
@hiren0007 I cannot recreate this issue on version 3.1.5. Please open a new issue if you're experiencing a bug with cypress.
