### ISSUE TITLE
cypress.exe crashing to desktop Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by cdoucet6302** [cypress-io/cypress#1365]
- Operating System: Ubuntu 16.04 LTS
- Cypress Version: Beta Version 2.0.3
- Browser Version: 64.0.3282.167 (Official Build) (64-bit)

### Is this a Feature or Bug?
Bug

### Current behavior:
cypress.exe is crashing when running a test.

### Desired behavior:
Not crash or at least open a crash log to debug the issue.

### How to reproduce:
1. Open the cypress program from desktop
2. Create a new empty project (this is just to replicate, it also fails using my work project)
3. Select that project manually. 
4. Run `example_spec.js`

Cypress opens Chrome like it is about to run the test, Chrome hangs, Chrome closes, cypress.exe closes.

**Comment by bahmutov** [comment]
What about other browsers like the built-in electron? Does it run the tests without crashing?

**Comment by cdoucet6302** [comment]
Looks like that's working, thank you!
