### ISSUE TITLE
Add `--config-file` CLI argument

### ISSUE THREAD

**Issue by kentcdodds** [cypress-io/cypress#1369]
### Current behavior:

I cannot specify a configuration file path

### Desired behavior:

I want to specify a configuration file path

#### Test code:

```
cypress run --config-file "/path/to/config"
```

### Additional Info (images, stack traces, etc)

I'm building a tool for PayPal called `paypal-scripts` (similar to `react-scripts`). One of the purposes is to cover 80% of the use cases by hiding all configuration from the user of the tool so they can focus on just writing the code. If they _do_ create a `cypress.json` file then we'll use that one, but for most people they should be able to just use the built-in configuration of `paypal-scripts` and they wont need to have and maintain a `cypress.json` file at all. There's honestly not a lot of configuration we'd need (mostly the `baseUrl` I think), but a lot of the value proposition of `paypal-scripts` is that people don't need to worry about configuring anything and it all just works out of the box.

I'm able to do this with `eslint`, `babel`, and many other tools, but I can't currently do it with `cypress` and I'd like to be able to do that if possible :) Thoughts?

**Comment by jennifer-shehane** [comment]
Would probably call the arg `--configFile` in keeping with the naming convention of our other file path args: https://on.cypress.io/configuration#Folders-Files

**Comment by kentcdodds** [comment]
That sounds great 👍

**Comment by brian-mann** [comment]
Yeah this has come up before in a longer thread here - https://github.com/cypress-io/cypress/issues/909#issuecomment-356967064

I agree with the need for this. At the moment cypress is hard coded to look for the `cypress.json` file. 

But, today -- for dynamic configuration - you could use `plugins/index.js` to modify all of the values before they're handed off to Cypress - https://docs.cypress.io/api/plugins/configuration-api.html

We have some examples that might satisfy your requirements today.

**Comment by reintroducing** [comment]
i am facing the exact same issue at SpotHero at the moment and would love to also have this option available.

**Comment by TroutZen** [comment]
Also have a use for this. I have a repo with tests for multiple services that each needs its own config file.

**Comment by haleagar** [comment]
+1

**Comment by brian-mann** [comment]
You can use the plugins API to programmatically alter the configuration **in whatever way you want today**.

You can simply have an empty `cypress.json` file and then merge in whatever you'd like based on whatever you'd like in whatever manner you want.

https://docs.cypress.io/api/plugins/configuration-api.html

I am confident this can handle whatever you want to throw at it.

**Comment by kentcdodds** [comment]
Probably so, but that would require that people have the plugin installed. For my use case I want people to be able to simply run: `paypal-scripts e2e` and it'll start things up for them without them having to have any configuration of plugins setup. The less in their filesystem the less they can mess up/have to maintain.

**Comment by vinnymac** [comment]
The docs [here](https://docs.cypress.io/api/plugins/configuration-api.html#Promises) kind of allow for this, although I had to fix it to get it working properly in a freshly setup project on version 3.1.0.

```js
const pathToConfigFile = path.resolve('..', 'config', `${file}.json`)
```

became
```js
const pathToConfigFile = path.resolve('cypress', 'config', `${file}.json`)
```

It is strange to me that something like this would not be built in. It is a necessity to be able to differentiate between environments and fixtures.

**Comment by Toxicable** [comment]
Would be great to see this feature in master.
It would help a lot with the Bazel intergration im working on here: https://github.com/bazelbuild/rules_nodejs/issues/607

**Comment by rodoabad** [comment]
Eagerly waiting! 👍

**Comment by SurajChande** [comment]
> Eagerly waiting! 👍

Same here!

**Comment by talentlessguy** [comment]
Very much needed!

**Comment by talentlessguy** [comment]
This is cool but it doesn't seem to be working :/

```
> yarn test:update
yarn run v1.17.3
$ cypress run --record --config-file update.cypress.json

  error: unknown option: --config-file
```

**Cypress version**: 3.4.1

**Comment by brian-mann** [comment]
@talentlessguy our `cypress-bot` comments on all closed issues indicating that they have yet to be released. This fix is slated for `3.5.0`, which is why it's not in `3.4.1`. Apparently the `cypress-bot` stopped working a couple days ago and we're fixing it.

**Comment by brian-mann** [comment]
@talentlessguy actually the `cypress-bot` is working, I'm not sure why it didn't comment on this issue, but here's an example of what it typically does: https://github.com/cypress-io/cypress/issues/4822#issuecomment-536296656

**Comment by talentlessguy** [comment]
@brian-mann okay, good luck with fixing `cypress-bot`. I hope `3.5.0` will be released soon.

**Comment by leonfs** [comment]
Same here - this would be a great option. We tried to modify the blacklistsHosts list in the plugins file, but for some an unknown reason, the config always ended with the same blacklistsHosts that in the .json file. It must be bug. All other properties modified by the plugin were actually showing the expected values.

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/3246, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
