### ISSUE TITLE
Prevent/Stub network request

### ISSUE THREAD

**Issue by tschaka1904** [cypress-io/cypress#1370]
### Current behavior:
I've in my application several `<script>...</script>` like pulling in jQuery and also a few internal things. Cypress gets errors that it is not authorised to get certain things. Now this question would be answered (if authorised or not) by an external js file. But this fails, as the "cypress user" is unknown. 

### Desired behavior:
A way of either overriding or mocking this `<script>...</script>`-tag to be able to influence the response. 

- Operating System: Mac OS High Sierra 
- Cypress Version: 2.0.3
- Browser Version: electron

**Comment by benpolinsky** [comment]
Similar situation, I think: 

I ended up blacklisting the host in my cypress.json, and then mocking it during the `window:before:load` event inside of a `beforeEach` method.

**Comment by brian-mann** [comment]
This feature is part of part of our large rewrite of the network layer that's actively being worked on - and you'll be able to fully stub all network requests including ones for script tags. Read this issue: https://github.com/cypress-io/cypress/issues/687

For today - you could either blacklist these requests, or you could use some combination of `document.currentScript` to get access to the `<script>` and then swap its `src` attribute to something you control.

You have native access to everything in Cypress - and you can use that to alter your scripts before they are fetched.

**Comment by tschaka1904** [comment]
Okay, I would blacklist my <script src="script/I/want/to/stub.js></script>, which basically returns an object which gets used in the global context. But for some reason, I can't create in my test something what is accessible from the application/window context. How would that work?

**Comment by bsmithEG** [comment]
@brian-mann 
>>> For today - you could either blacklist these requests, or you could use some combination of document.currentScript to get access to the <script> and then swap its src attribute to something you control.

Can you elaborate a little bit more on this approach?  I've tried listening to the "window:before:load" event, but when trying to get the document page scripts, it seems i'm getting the cypress window content and not the apps:

```
    cy.on("window:before:load", win => {
        console.log(win.document.documentElement.outerHTML)
    })
```

```
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head> <script type="text/javascript"> document.domain = 'scullyandscully.com'; var Cypress = window.Cypress = parent.Cypress; if (!Cypress){ throw new Error('Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'); }; Cypress.action('app:window:before:load', window); </script></head></html>
```

**Comment by jennifer-shehane** [comment]
The features requested in this issue are now possible as part of `cy.route2()`. 

`cy.route2()` is currently experimental and requires being enabled by passing `"experimentalNetworkStubbing": true` through your Cypress configuration. This will eventually be merged in as part of our standard API. 

**Please see the `cy.route2()` docs for full details: https://on.cypress.io/route2**

If you encounter any issues or unexpected behavior while using `cy.route2()` we encourage you to [open a new issue](https://github.com/cypress-io/cypress/issues/new?assignees=&labels=&template=bug-report.md&title=) so that we can work out all the issues before public release. Thanks!
