### ISSUE TITLE
Muted video plays with sound when running tests.

### ISSUE THREAD

**Issue by davidalekna** [cypress-io/cypress#1374]
- Operating System: Mac
- Cypress Version: 2.0.3
- Browser Version: Chrome 64.0.3282.186

### Is this a Feature or Bug?
Possibly a bug

### Current behavior:
Video sound is set on mute but still plays the sound when testing

### Desired behavior:
Should stay on mute

### How to reproduce:
`
                <video autoPlay muted loop>
                  <source
                    src={`${process.env.PUBLIC_URL}/video/host.mp4`}
                    type="video/mp4"
                  />
                  Your browser does not support the video tag.
                </video>
`

#### Test code:
I'm not testing the video itself, but when running tests on a page that includes video it plays the sound.

**Comment by Bkucera** [comment]
verified bug on Chrome 64, not present in Electron

**Comment by Bkucera** [comment]
This is actually a bug in Chrome 64. If the video is not loaded immediately in the DOM, Chrome doesn't recognize that it's muted, so anything nested in an iframe won't honor the `muted='true'` or `volume` attributes, see jsfiddle here: https://jsfiddle.net/rpmk93wm/11/
I would recommend using either Chrome Canary or Chromium or Electron, which don't have this problem.
