### ISSUE TITLE
How to catch data in not xml http request?

### ISSUE THREAD

**Issue by rrrainbows** [cypress-io/cypress#1377]
Hi! I've just started so probably have a foolish question)
How can I catch and verify data in not xml http request? For example if I have to check url, status and body in request/response after submitting a form?
I'm not stubbing anything now and want to check it with ui, not with cy.request.

I`ve seen issue cypress-io/cypress#687, but probably there is a workaround

Thank you!

- Operating System: ubuntu 16.04 LTS
- Cypress Version: 2.0.4
- Browser Version: Chrome 64

### Is this a Feature or Bug?
Question

**Comment by jennifer-shehane** [comment]
Why can check all of this with `cy.request()`, why is it that you want to use the UI instead? Just curious.

**Comment by brian-mann** [comment]
If you're talking about a traditional <html> form submission - that's not an XHR or a `fetch`, then no - there is no way to intercept that or assert about it until we finish network stubbing.

Currently the only way to test it is to test that the `window:unload` event fired, that the `window:load` event occurred, and then testing something on the subsequent page.

https://docs.cypress.io/api/events/catalog-of-events.html

**Comment by rrrainbows** [comment]
@jennifer-shehane I want to be sure that the form is sending expected data after submission and the server responce is correct.

**Comment by rrrainbows** [comment]
@brian-mann Yes, about a traditional form submission. Ok, thank you!
