### ISSUE TITLE
.type() does not type random characters (reproducibility is 10%)

### ISSUE THREAD

**Issue by Gennadiii** [cypress-io/cypress#1381]
- Operating System: Windows 10
- Cypress Version: 1.4.2
- Browser Version: Chrome 63

### Current behavior:
```js
cy.get('some css locator').first().clear().type('1000');
```
the field I'm typing to is input with `type='number'`
10% times I get input `100` (without the last character)

**Comment by pgroot91** [comment]
How did you came up with the 10 percent reproducibility? Running the same test multiple times in a row and see if or when it fails? so runs 10 times the same test and 1 fails? or... 

Is there a reason why you don't run the lastest version of Cypress?

**Comment by Gennadiii** [comment]
I trigger test run multiple times in a row. 10% is an approximate number. This old version was set up some time ago and I've just joined the project. I'll see if I can upgrade but if there's a solution or a reason why it's happening - would be good to know.
Thanks.

**Comment by rgkeith3** [comment]
I have a similar issue, all my tests pass when I run them separately, however when running them all at once, (doing some actions like typing in a field many many times over the course of a test run) I'll occasionally, and inconsistently end up with truncated strings in the inputs. usually missing the last couple letters.

**Comment by Bkucera** [comment]
I'm looking into this as part of the #1241 `cy.type()` epic.

**Comment by Floriferous** [comment]
I'm still seeing inconsistencies with `type()`, I can't reproduce them on my local machine, they only happen on circle CI. 

It doesn't make it to the end of the string, and then moves on to the next action.
