### ISSUE TITLE
Cypress should empty indexDB before onload

### ISSUE THREAD

**Issue by reaktivo** [cypress-io/cypress#1383]
- Operating System: Mac OS X
- Cypress Version: 2.0.4
- Browser Version: Chrome 64

### Is this a Feature or Bug?
Bug

### Current behavior:
IndexDB databases are not being cleared before runs

### Desired behavior:
IndexDB databases should be empty when doing the first `.visit`

### How to reproduce:
From an application that uses indexDB, reload the application and indexDb data will still be there 

#### Test code:

```js

```

**Comment by brian-mann** [comment]
It probably should - but you can clear this yourself. You don't need anything special.

```js
indexedDB.deleteDatabase(dbName)
```

**Comment by brian-mann** [comment]
Also, this is a feature, not a bug. 

Related to: https://github.com/cypress-io/cypress/issues/686

**Comment by brian-mann** [comment]
Closing as duplicate of https://github.com/cypress-io/cypress/issues/1208
