### ISSUE TITLE
Do not capture video during 'file:preprocessor', etc, before tests start

### ISSUE THREAD

**Issue by matt-psaltis** [cypress-io/cypress#1386]
- Operating System: Windows 10
- Cypress Version: 2.0.4
- Browser Version: Chrome 64

### Is this a Feature or Bug?
Feature

### Current behavior:
When using the typescript plugin, the uploaded video includes the typescript compilation time frame which is just a static image of the uninitialised test runner for the first 30 seconds of the video. I have to go hunting through the video for the point where the tests begin to execute.

### Desired behavior:
Do not capture the period of execution during the file:preprocessor (possibly others) into the resulting video.

Additionally, offer bookmarks on the dashboard search video viewer so that I can more quickly identify when individual tests execute. Bookmarks for point of failure would be awesome as well!

**Comment by brian-mann** [comment]
30 seconds is a crazy long time to transpile typescript! is that normal?

We'll look into stripping out that part of the video - or maybe adding something there like a spinner which indicates that the spec file is transpiling.

For bookmarks - these already exist. All failed tests have a reference to the Video section - and expanding that will play the video directly from the start of the test. No hunting required!

**Comment by SaltyDH** [comment]
Great line of thinking - I suspect I've become somewhat numb to the typescript compilation speeds, Angular 5 shop here so a couple of minutes for full compile isn't out of the question :) I'll take another look at what the compilation is pulling in, might have grabbed application code somehow. Thanks!

Dunno how I missed the videos section in the failed tests, thanks for that!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
