### ISSUE TITLE
Node-sass is not working due to node version difference

### ISSUE THREAD

**Issue by dz902** [cypress-io/cypress#1387]
- Operating System: OSX
- Cypress Version: 2.0.4
- Browser Version: doesn't matter

### Is this a Feature or Bug?
Bug / Question

### Current behavior:
- Using cypress against webpack. 
- At 1.4, node-sass throw: Node Sass could not find a binding for your current environment: OS X 64-bit with Electron.
- Then I updated to 2.0.4, node-sass throw again: Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.xX
- This also follows the error: Found bindings for the following environments: OS X 64-bit with Node.js 9.x
- The project itself can compile successfully, I'm using webpack-dev-server which is working okay

### Desired behavior:
- I understand that this is because cypress runs its own environment, at first Electron, then a different version of node
- I am not sure how to make those versions match, or whether it's possible to upgrade node version of cypress
- It should work and behave the same for the project and tests, I believe

Advices are welcome. Thanks!

**Comment by brian-mann** [comment]
Are you running Cypress from source? Or using the npm package?

Do you mind providing a reproducible repo? A good majority of our users use webpack without a problem.

**Comment by dz902** [comment]
I'm running from the npm package.

I think the problem is with node-sass and node version, webpack is fine. I'll see if I can make a minimal repo to reproduce it.

**Comment by bahmutov** [comment]
There is this issue reporter in cypress-vue-unit-test !

**Comment by dz902** [comment]
https://github.com/dz902/cypress-test-tiny

Here we go, a demo. Is it possible to use native node instead of bundled node? As I really only need webpack to compile, and cypress should only be responsible for running the compiled test (maybe this is only for my web-development scenario).

Any ideas on whether it's possible?

**Comment by dz902** [comment]
@bahmutov 

Oh man I did not know there is a package for vue. I'm using vue. Really love to test vue with cypress, both great.

Is this problem solvable?

**Comment by dz902** [comment]
Said issue https://github.com/bahmutov/cypress-vue-unit-test/issues/18

**Comment by brian-mann** [comment]
We likely need to rebuild the native node-sass prior to distributing Cypress - as it comes prepacked with native binaries.

**Comment by dz902** [comment]
Is there anything I can do at the time to alleviate the problem? Or maybe there is a hidden option to use native node instead of bundled node?

**Comment by bahmutov** [comment]
Someone suggested in https://github.com/bahmutov/cypress-vue-unit-test/issues/18#issuecomment-368962073 that using Node 8 to install and run Cypress solves the problem

**Comment by dz902** [comment]
Cool, [downgrading](https://www.abeautifulsite.net/how-to-upgrade-or-downgrade-nodejs-using-npm) to 8 and reinstalling node-sass solved the problem.

For any searchers landed here: I just found that there is a [list of pre-compiled binaries](https://github.com/sass/node-sass/releases/), which user could download (number 57_binding is for Node 8) and should be able to make cypress work. A map of number -> platform can be found in `extension.js` in node-sass directory for downloading the correct binary.

This breaks the integrity of the package though, as this has to be done manually by user.

Ultimately there will be a hero to create a real node/js based compiler for sass (or replace it altogether), distributing binaries is just ridiculous for a CSS-transpiler.

**Comment by brian-mann** [comment]
I think I know what the problem is - we build OSX + Windows version of Cypress in each applicable operating system.

In those builds - we forgot the bump the locally installed node version. So what's happening is that Cypress is using node `6.x.x` to install and build native node modules (node-sass) and then it's build the Cypress binary and then uploading it with those node modules.

Linux is correct - because we did bump the node version there.

As long as we bump Windows + OSX node version when distributing Cypress binaries everything "will just work".

We'll need to release `2.0.5` with this fix. As long as Cypress itself distributes the binaries natively compiled against its node version everything will always work. So it's actually a benefit to distributing node as opposed to using system node.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/issues/1390

**Comment by brian-mann** [comment]
Released in [`2.1.0`](https://docs.cypress.io/guides/references/changelog.html#2-1-0).

**Comment by pedroteixeira** [comment]
Hello, is there any way to run Cypress on node v9.x?
it seems there isn't, just want to confirm :)

**Comment by brian-mann** [comment]
Cypress comes bundled with its own node version and there is no way to change that.

**Comment by mAAdhaTTah** [comment]
Is there any way to run the install process with Cypress's built-in node version?
