### ISSUE TITLE
Improve command docs

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#139]
- [ ] Make more consistent
- [ ] Better focus on UX
  * [ ] Think how first-time user views it
  * [ ] Move usage to top?
- [ ] Improve explanations of timeouts

**Comment by jennifer-mann** [comment]
Issue moved to [cypress-io/cypress-documentation #2](https://github.com/cypress-io/cypress-documentation/issues/2) via [**ZenHub.io**](https://www.zenhub.io/)
