### ISSUE TITLE
Use Node 8 to build on Windows and Mac CIs

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1390]
We build the Linux binary using same major version of Node as the Electron itself is using (8), but Windows and Mac CIs are still using Node 6, which leads to wrong version of Node-sass included. This causes problems like #1387 and https://github.com/bahmutov/cypress-vue-unit-test/issues/18

- Use Node 8 on AppVeyor CI
- Use Node 8 on Buildkite CI

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/1391

**Comment by brian-mann** [comment]
Released in [`2.1.0`](https://docs.cypress.io/guides/references/changelog.html#2-1-0).
