### ISSUE TITLE
expect(element).to.have.style('height', '323px')

### ISSUE THREAD

**Issue by johnunclesam** [cypress-io/cypress#1393]
How can I get the element height or width?

Something like:

```javascript
cy.get(mainMenu).expect(element).to.have.style('height', '323px');
cy.get(mainMenu).expect(element).to.have.style('width', '20px');
```

Is it possible?

Maybe using this: https://github.com/darlanmendonca/chai-style ?

**Comment by ValerieThoma** [comment]
Can you try
```javascript
cy.get('mainMenu').should('have.attr', 'height', '323');
```
Or reference the Guides on Assertions **here** for what you're looking for? https://docs.cypress.io/guides/references/assertions.html#Chai

**Comment by johnunclesam** [comment]
Nothing.

I tried also:

`expect(mainMenu).to.have.attr("height", "323");`

In that page I don't see `height` or `width`.

I just need to get the height or wodth of an element.

**How to?**

**Comment by ValerieThoma** [comment]
Have you tried sharing this issue with the community in the Cypress Gitter channel? 
https://gitter.im/cypress-io/cypress

**Comment by johnunclesam** [comment]
Nope. I think this is at least a doc issue. Please don't close.

**Comment by brian-mann** [comment]
@johnunclesam the assertion you're looking for is documented here: https://docs.cypress.io/guides/references/assertions.html#Chai-jQuery

It's `to.have.css(....)`

The way you most commonly use assertions is with `.should()` as documented here.

https://docs.cypress.io/guides/references/assertions.html#Common-Assertions

```js
// assuming mainMenu is a string selector here
cy.get(mainMenu).should('have.css', 'height', ...)
```

When you have a direct element reference that's when you use `expect(subject)`

```js
cy.get(mainMenu).should(($el) => {
  expect($el).to.have.css('height', ...)
})
```

**Comment by cjohn17** [comment]
> // assuming mainMenu is a string selector here
cy.get(mainMenu).should('have.css', 'height', ...)

This mostly worked for me, except I get an error back that the expected value is 55, but the returned value is 55px. How to account for this?

**Comment by jennifer-shehane** [comment]
@cjohn17 

```js
cy.get(mainMenu).should('have.css', 'height', '55px')
```
