### ISSUE TITLE
How to select Multi-Value Select Boxes?

### ISSUE THREAD

**Issue by PlanPracy** [cypress-io/cypress#1395]
I could not select Multi-Value Select Boxes (http://select2.github.io/select2/)
I try:
```js
cy.get('s2id_e9').click()
 cy.get('ul li:first').contains('California').select()
```
, but it does not work. How can I select these options?

**Comment by jennifer-shehane** [comment]
Please carefully read the docs on [`cy.select()`](https://on.cypress.io/select), you need to pass the **value or text content of the option** to the [`cy.select()`](https://on.cypress.io/select) command: https://on.cypress.io/select
