### ISSUE TITLE
Weird encoding issue inside javascript assets when Cypress runs

### ISSUE THREAD

**Issue by SaltyDH** [cypress-io/cypress#1396]
- Operating System: Windows 10 & Server 2012
- Cypress Version: 2.0.4
- Browser Version: Chrome 64 and Electron with Chrome 59 both exhibit this behaviour

### Is this a Feature or Bug?
Bug

### Current behavior:
When running a cypress test of an Angular 5 application which has been webpacked, a chunk is asynchronously loaded from the web server. This chunk is malformed (somewhere in the pipeline) consistently on the same byte of the same file each time. The problem does not manifest when you browse the site directly through Chrome, only during the Cypress test run.

### Desired behavior:
The javascript files arrive at the browser intact and unmodified.

### How to reproduce:
I'm not really sure on a reproduction.

_Q: Is there a way I can bypass the cypress network stack for individual assets to try and identify if this is the cypress proxy or something else at play?_

Here's what I know so far... 

The test throws the following error consistently in the same place of the test.

If you open the chunk file from a Chrome browser having run the application normally you see:
`__WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵand"]`

However, when the error is thrown, the chunk contains the following:
`__WEBPACK_IMPORTED_MODULE_0__angular_core__["��and"]`

Full error and stack trace:

```
cypress_runner.js:138957 Console was cleared
cypress_runner.js:138954 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.��and is not a function

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
    at View_Dropdown_8 (https://<url-redacted>/0.d44dcaa6cf578dfd34f1.chunk.js:3913:490)
    at resolveDefinition (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:127750:17)
    at Object.anchorDef (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:128019:55)
    at View_Dropdown_0 (https://<url-redacted>/0.d44dcaa6cf578dfd34f1.chunk.js:3939:4669)
    at resolveDefinition (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:127750:17)
    at createViewNodes (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:131297:56)
    at callViewAction (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:131768:13)
    at execComponentViewsAction (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:131677:13)
    at createViewNodes (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:131361:5)
    at callViewAction (https://<url-redacted>/vendor.bundle.js?v=FtrhNBpDu18Mnhl7cHgNIXl06Fwzd5RdnAWtKahf5Qg:131768:13)
From previous event:
    at run (https://<url-redacted>/__cypress/runner/cypress_runner.js:62383:15)
    at Object.cy.(anonymous function) [as get] (https://<url-redacted>/__cypress/runner/cypress_runner.js:62603:11)
    at Context.runnable.fn (https://<url-redacted>/__cypress/runner/cypress_runner.js:62734:20)
    at callFn (https://<url-redacted>/__cypress/runner/cypress_runner.js:32354:21)
    at Test.Runnable.run (https://<url-redacted>/__cypress/runner/cypress_runner.js:32347:7)
    at https://<url-redacted>/__cypress/runner/cypress_runner.js:65627:28
    at <anonymous>
From previous event:
    at Object.onRunnableRun (https://<url-redacted>/__cypress/runner/cypress_runner.js:65626:20)
    at $Cypress.action (https://<url-redacted>/__cypress/runner/cypress_runner.js:61088:51)
    at Test.Runnable.run (https://<url-redacted>/__cypress/runner/cypress_runner.js:64766:20)
    at Runner.runTest (https://<url-redacted>/__cypress/runner/cypress_runner.js:32817:10)
    at https://<url-redacted>/__cypress/runner/cypress_runner.js:32923:12
    at next (https://<url-redacted>/__cypress/runner/cypress_runner.js:32737:14)
    at https://<url-redacted>/__cypress/runner/cypress_runner.js:32747:7
    at next (https://<url-redacted>/__cypress/runner/cypress_runner.js:32679:14)
    at https://<url-redacted>/__cypress/runner/cypress_runner.js:32715:5
    at timeslice (https://<url-redacted>/__cypress/runner/cypress_runner.js:27956:27)
```

**Comment by brian-mann** [comment]
This is almost certainly being caused by the `modifyObstructiveCode` option documented here: https://docs.cypress.io/guides/references/configuration.html#modifyObstructiveCode

You should be able to flip that off and it will work.

If you look through our changelog you'll see we've been iterating and fixing issues with this over the last few releases. 

Can you please host/post your source code somewhere for us to look at? We're running our tests through about 40 different libs to ensure it doesn't accidentally rewrite valid code. Your app code must be special in some way and it would be great to fix this bug.

**Comment by SaltyDH** [comment]
Thanks very much @brian-mann I was way off in my searching - trying to find things like "encoding" and "proxy issues". Happy to say the test is green! Changing the modifyObstructiveCode setting to false resolves this.

I won't be able to upload my application code as its part of a closed source product. I've put the specific webpack module (its part of a larger chunk) in a gist to help with identifying strategies for exclusion of this particular case. The offending code originates from PrimeNG, an Angular component library which is open source. I could try and work on a repro if the gist doesn't provide enough information to help.

https://gist.github.com/SaltyDH/421d76d1be43c1773d80f1431330ac0e#file-cypress-obstructive-code-sample1-js

The modified code appears on line 112 in the gist.

Thanks for the fast reply!

**Comment by brian-mann** [comment]
That should be enough to repro.

**Comment by brian-mann** [comment]
Unfortunately the gist you provided does not indicate a problem. I ran that code through the rewriter and it came out byte for byte the same...

Did you gist the ORIGINAL code? I need whatever is supposed to be sent to the browser - not what is being sent (the wrong bytes).

**Comment by SaltyDH** [comment]
Yeah, double checked its the original text. If you search for `and"` you should find all occurrences have the "Close-mid central rounded vowel" in front of them rather than the replacement character.

What would it take for me to run the rewriter as you've just done - If I can run it here, I can hopefully cut the chunk file down to something that reproduces this issue.

**Comment by brian-mann** [comment]
The easiest way is to run the unit tests.

1. clone the `cypress` repo
2. `cd packages/server`
3. `npm install`
4. open up `packages/server/test/unit/security_spec.coffee`
5. replace the contents of that file with this gist: https://gist.github.com/brian-mann/22871fd6b8b9b8096e012663b049c59a
6. inside of that gist, paste your app code exactly where i have the note to paste the code 
7. make sure you `pwd` is  `packages/server`
8. run the test: `npm run test-watch ./test/unit/security_spec.coffee` that will put it in watch mode and rerun on any changes.
9. if it fails, it will wrote out the diff to a file here: `packages/server/test/support/fixtures/server/libs/ng`

**Comment by brian-mann** [comment]
Shit I just realized you are on Windows... you may have some problems... and I wonder if that's not the actual root problem to begin with.

See how far you can get, but if not we'll have to spin up a windows box and try it out. We run all of our e2e tests on Windows but not the unit tests, so it's possible that's where the bug is.

**Comment by brian-mann** [comment]
Alternatively... this is much easier....

Go into this file: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/security.coffee

And just try those regexp's one by one against your code.

Just use a site like https://regex101.com/

If any of those regexp's match any of our content - that's where the problem. None of them should match and therefore the bytes should pass through unchanged.

**Comment by SaltyDH** [comment]
Just a quick update, none of the regex matched. Working theory is now gzip / chunked encoding issue corrupting the stream on windows. I'm currently on Node.js 7.7.4 so I'm going to try upgrading to a newer release and see if that helps.

**Comment by brian-mann** [comment]
Oh yes - that's actually possible. When `modifyObstructiveCode` is enabled we have to unzip and then strip and the gzip again. That's probably what's happening. The problem isn't the security - its gzip. That makes a lot more sense regarding encoding. I should be able to still use your gist as a fixture to reproduce.

As far as node is concerned - your local `node` does not matter. Cypress comes bundled with its own.

**Comment by zbjornson** [comment]
I think we hit the same issue, and have some debugging info to provide.

We have utf-8 characters in our application code. If the content is served gzip'ed, it goes through gunzip here:

https://github.com/cypress-io/cypress/blob/6dd7edea5c7920c35e984fa802401eee1c7c1c60/packages/server/lib/controllers/proxy.coffee#L162-L165

Any utf-8 character that falls on a stream chunk boundary is corrupted (the multi-byte code point is split apart). Here's a simple demo of that:

```js
const zlib = require("zlib");
const input = "0" + new Array(128).fill("λφ").join("");
const gzipped = zlib.gzipSync(input);
const gunzip = zlib.createGunzip({chunkSize: 64});
let out = "";
gunzip.on("data", d => out += d);
gunzip.on("end", () => console.log(out));
gunzip.end(gzipped);

// Output:
// 0λφλφλφλφλφλφλφλφλφλφλφλφλφλφλφλ��λφλφλφλφλφλφ...
//                                  ^^ phi split apart on chunk boundary
```

I think the only safe, simple thing to do is gunzip it all at once instead of streaming it.

---

This was super cryptic to debug. The message from Cypress was:
```
Invalid or unexpected token

This error originated from your application code...
```

Normally the message would include what the invalid or unexpected token is, but I guess an invalid character like this doesn't show up.

**Comment by jennifer-shehane** [comment]
Other recent gunzip error being encountered: https://github.com/cypress-io/cypress/issues/1756

**Comment by brian-mann** [comment]
Oh very nice... should be an easy win to get in then as a quick fix.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by zyv** [comment]
Hmmm, we are running Cypress 3.1.0 on Cypress browsers official Docker image and still having this issue on Mac and Linux. We have also managed to find a stable reproducer in form of a bundle, which we can share. Shall we open a new issue?

In any case, we will try `modifyObstructiveCode` to see if this makes the problem go away... it was really a hell to debug, and very difficult to find this ticket.

@pchorus @dniggemann @mm-matthias

**Comment by zyv** [comment]
Confirmed that setting `modifyObstructiveCode` to `false` solves the problem with botched ɵs. What is still not clear is how come this ticket is closed, but we can still reliably reproduce exactly this problem with the latest version of Cypress...

**Comment by dontgetfoundout** [comment]
I'm also seeing this in Cypress 3.1.2.  I have d3 included in a bundle of external libraries.  Without modifyObstructiveCode disabled, characters like lambda (λ) and phi (φ) are being replaced with REPLACEMENT CHARACTER (�� - U+FFFD).

setting modifyObstructiveCode to false resolves this issue.  A fix in cypress framework that doesn't require special configuration would be preferable.  I'm not sure what I would do if I needed the modifyObstructiveCode functionality and was impacted by this issue.

Hopefully this comment adds more keywords to make this thread easier to find.

**Comment by jennifer-shehane** [comment]
@dontgetfoundout Yes please open a new issue. It's another fix we will have to make with our modifications.

**Comment by alfaproject** [comment]
I can confirm that this issue happens with any recent version of Angular, so you will probably have a few complains soon: https://puu.sh/DOFhM/1dd12f8b4a.png

Took me a few hours to debug this because the error couldn't be any more cryptic. ):

**Comment by flotwig** [comment]
I believe that #4698 might fix this issue - browsers infer the character encoding of subresources (partially) based on the character encoding of the consuming HTML document, so fixing the character encoding of HTML in Cypress should cascade to this.

If anyone has a minimal reproducible example of this happening, I'll test it against #4698.
