### ISSUE TITLE
Open Modal or Page with Ionic 3

### ISSUE THREAD

**Issue by vpivet** [cypress-io/cypress#1397]
- Operating System: Mac OS 10.13.3
- Cypress Version: 2.0.0
- Browser Version: Chrome  64.0.3282.186

### Is this a Feature or Bug?

Bug

### Current behavior:

When I tap on a button to open an Ionic 3 page or Modal, nothing append and my test fail. Cypress success to click on the button but the page doesn't appear.

### Desired behavior:

Open Ionic Modale or Page on button click with Cypress

### How to reproduce:

Create an Ionic 3 empty project with a button who open a new page. 

#### Test code:

```js
it('should open page', () => {
        // Button to open my page : OK
        cy.get(my_button).click();

        // Check if a label exists in the opened page : FAIL
        cy.get(a_label_in_my_page).contains("All is ok !");
    });
```
Question : Is it possible to well test Ionic 3 with Cypress ?

**Comment by jennifer-shehane** [comment]
Is there any error that displays within your [Test Runner](https://on.cypress.io/test-runner) on click? Could you share the error that is displayed? 

Also, you may find success with [`.click({force: true})` option](https://on.cypress.io/interacting-with-elements#Forcing).

**Comment by vpivet** [comment]
No error in my test runner for the on click. I can see the on click animation when I execute my tests. But my page doesn't appear.

I tried `.click({ force: true })` option but nothing append

**Comment by brian-mann** [comment]
@vpivet can you make this easy on us and setup a reproducible repo with the bare minimum to demonstrate the problem. You did do a good job explaining the steps - but for our team - since we have to investigate these issues, we prioritize whatever is easiest to reproduce and diagnose.

**Comment by vpivet** [comment]
I created a new empty Ionic 3 project with Cypress with simple modal and page to share it with you. But I haven't the problem with this project, my page or modal open without problem.
I noticed that my function on click isn't call when button is clicked. (Can't see my console.log)
I will try to reproduce it in my empty project to share it with you. 

In the meantime I hope this new element can help you to understand my problem.

**Comment by vpivet** [comment]
It's ok ! I understand my mistake. 
I my code I used (tap) to do on click event. But it doesn't works with cypress. 
So I replace all my (tap) by (click) and it works better. 

`<button ion-button (tap)="doSomething()">My Button</button> ` => WRONG
`<button ion-button (click)="doSomething()">My Button</button> ` => GOOD

Thanks for your help. Cypress is really good ! ;)

**Comment by amiral-jion** [comment]
I have the same problem, I need to use `tap` instead of `click` but I can't find how to simulate this event with cypress. any one succeed on simulating the tap event guys?

**Comment by jennifer-shehane** [comment]
@vpivet @amiral-jion I would take a look at [`trigger()`](https://on.cypress.io/trigger)

I think this will be easier to achieve once we have native events support: https://github.com/cypress-io/cypress/issues/311
