### ISSUE TITLE
Parse Error on DELETE request

### ISSUE THREAD

**Issue by albertored** [cypress-io/cypress#1398]
### Current behavior:

My page send a `DELETE` request with a json body to the server that correctly respond with status 204 and empty body (I verified it both on server logs and using `wireshark`)

cypress instead show a 500 status in the command log and if I print the response body with
```js
cy.wait('@deleteApn').then(xhr => {
    cy.exec(`echo ${JSON.stringify(xhr.response.body)} > aaa.json`)
})
```
I get
```html
<!DOCTYPE html>
<html>
<body>
Cypress errored attempting to make an http request to this url:
http://172.17.102.170:3000/nc/api/apn/
The error was:
Parse Error
The stack trace was:
Error: Parse Error
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
</body>
</html>
```

- Operating System: Debian 9 virtual machine 
- Cypress Version: 2.0.4
- Browser Version: electron 59

**Comment by brian-mann** [comment]
This is likely a bug in Cypress but it's likely your server doing something funky to cause it.

My guess is that your server is sending back something like: `Content-Type: application/json` but then sending an empty response body (which is invalid). Cypress should probably handle this instead of dying - but we need to be able to reproduce this in order to fix it.

Can you send us the response exactly from your server - including headers and body. You could export as HAR. Even sending what it looks like when you work outside of Cypress would be enough for us to mimic and likely reproduce.

If what I suspect is the problem it will be easy to fix and we can get a patch out.

**Comment by albertored** [comment]
Thanks for your reply. Yes, it is indeed an error in my server, it was sending a non empty body with status 204 that is forbidden, 204 responses must have empty body.

It would be nice if cypress could handle it without dying or maybe just showing a better error message. If you only watch the command log you a see a 500 response that seems to be sent from the server. Only a check of the actual response body shows the real error.

If you still need the response tomorrow I will send it but you can easily reproduce it by having a 204 response with any non empty body.

**Comment by michalcafe** [comment]
Cypress should just accept browser's behaviour instead of altering status codes even when the response isn't technically correct.

**Comment by lgt1001** [comment]
is this defect fixed?

**Comment by brian-mann** [comment]
It is not fixed yet. If we have to put together a reproducible repo, and we analyze that only a few users are affected, then we don't really prioritize these fixes over other ones.

To be clear, we have our team working full time on Cypress (and we're adding more resources) but we cannot fix everything immediately in the order that everyone wants fixed.

If you want us to prioritize things, when having a cloneable repo that's immediately demonstrating the problem that we can instantly extract into a test and fix the issue, that would make a big difference in how quickly we get to the problem. As it stands, us having to recreate it and doing the legwork and research often accounts for hours of work. Sometimes we're never able to recreate and issues will sit until it does. I don't think this issue would be the case, but this is the truth of the matter.

Of course, PR's are always welcome, but even without one, we'll eventually fix this issue at some point.
