### ISSUE TITLE
Allow specifying cypress binary location from .npmrc

### ISSUE THREAD

**Issue by jedateach** [cypress-io/cypress#1399]
- Operating System: Linux
- Cypress Version: 1.4.2
- Browser Version: Chrome 60

### Is this a Feature or Bug?
Feature

### Current behavior:
https://docs.cypress.io/guides/getting-started/installing-cypress.html#Environment-Variables

### Desired behavior:
Rather than needing to introduce an environment variable outside of npm land, it would be nice to specify a `cypress_binary_version` npm config inside the .npmrc file.

This means our devs only need to type `npm install`, and don't need to think about specifying environment variables.

This is how PhantomJS does it.
https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs

### How to reproduce:
`npm install`

**Comment by bahmutov** [comment]
Hmm, that is not a bad idea!

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
