### ISSUE TITLE
Control for when and if cy.route() responds

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#14]
I want to be able to control when and if a route responds. My biggest use case is testing loading logic in my app. Currently, if I write the example below, Cypress will auto respond to the image route (with a 404) before my assertion.

```coffee 
it "displays loading gif on image load", ->
  cy.route
    url: /image/
    response: {http://cdn.morguefile.com/imageData/public/files/g/g3c59w/03/l/1427371209n1lyb.jpg}

  cy.get("a").click()
  cy.get("img").should("have.attr", "src").to("match", /ajax.gif/)
```

**Some suggestions:**
- Allow for option of `autoRespond: false` to be passed into `cy.route()`
- Have a way to tell the route to respond at a later point in the test.
- Allow for a specific delay time before auto responding (allow this is probably a separate issue)

**Comment by brian-mann** [comment]
Fixed in [`0.5.10`](https://github.com/cypress-io/cypress/wiki/Changelog#0510-04272015).
