### ISSUE TITLE
Run/record one part of the test from cypress/integration folder

### ISSUE THREAD

**Issue by MaryBloom** [cypress-io/cypress#1404]
I divided my test into 3 parts:
- checking the label,
- checking data
- checking the flow
What kind of purpose I must run one of these parts.
All tests are in the cypress/integration folder.
So when I use cypress run to record tests all tests run. 
How should be the structure of these tests to run (record) one part of the test?
How to run /record one part of the test?

**Comment by ValerieThoma** [comment]
It sounds like you just want to run 1 spec file? 
If so, you can do this with the `--spec` arg in the command line.

Else, if I misunderstood, are you referring to issue #681?
