### ISSUE TITLE
Very weird error related to modified page contents when using document.write

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1405]
I put the example test into branch https://github.com/cypress-io/cypress-test-tiny/tree/github-static-pages The test just loads a static github page of mine

```js
it('works for website that plays hydration tricks', () => {
  cy.visit('https://glebbahmutov.com')
})
```
Now that page is a little tricky - it loads Vue app, but it also writes part of the page using `document.write` to speed up the initial load. Then Vue hydrates the application and it becomes interactive.

First time loading this page in Cypress test runner shows the following error

![screen shot 2018-03-02 at 8 42 32 am](https://user-images.githubusercontent.com/2212006/36902505-ae06ac30-1df8-11e8-9f78-6e3e74dab8db.png)

Weird, isn't it? Then I set `"modifyObstructiveCode": false` in cypress.json and the website loaded fine. 

BUT: when I tried to recreate the issue again and set `"modifyObstructiveCode": true` the issue would not show up. I removed cached project bundles, still good. Then suddenly it appeared one more time. So there was no reliable way to recreate the problem.

- Mac OS
- Cypress 2.1.0

**Comment by bahmutov** [comment]
Haha, just went to look at staging api logs and see the same issue in a CI build
![screen shot 2018-03-02 at 9 17 02 am](https://user-images.githubusercontent.com/2212006/36903085-92572080-1dfa-11e8-9ccf-9d8933eb70e5.png)

**Comment by bahmutov** [comment]
I wonder if I should have removed certificates to recreate the error, maybe there was a race condition there

**Comment by jennifer-shehane** [comment]
Cannot recreate this in Cypress version 3.4.0. Closing. Related open issue, however: https://github.com/cypress-io/cypress/issues/1746
