### ISSUE TITLE
Loading React Dev Tools for specs

### ISSUE THREAD

**Issue by pedroteixeira** [cypress-io/cypress#1409]
Hello,
I suspect this is more of a https://github.com/facebook/react-devtools question.. but posting here in case someone already figured this out.

On plugin:
```
on('before:browser:launch', (browser = {}, args) => {
    console.log(browser, args) // see what all is in here!

    if (browser.name === 'chrome') {
      const homedir = require('os').homedir();
      args.push(`--load-extension=${homedir}/.config/google-chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/3.1.0_0/`);
      return args
    }
  })
```

Inside a test, following the hint from https://github.com/facebook/react-devtools/issues/76:
```
cy.window().then((win) => {
      if (win.parent !== win) {
        win['__REACT_DEVTOOLS_GLOBAL_HOOK__'] = win.parent['__REACT_DEVTOOLS_GLOBAL_HOOK__'];
      }
    });
```

React dev tools is loaded as extension fine but does not work inside the test iframe :/
Any hints appreciated :)

thanks.

**Comment by brian-mann** [comment]
We use react and I know for sure we use the react dev tools in Cypress. It's something close to what you're doing and some of our team members can hopefully shed some light.

This should probably be a recipe too.

@Bkucera @jennifer-shehane @chrisbreiding

**Comment by pedroteixeira** [comment]
Thanks - I can actually inspect the Cypress React elements but could not find a way to inspect inside de iframe of the target test. 

Just realized that I am using https://github.com/bahmutov/cypress-react-unit-test to mount the application, So guess not something related to Cypress core itself. 

I will close this one and will post news here in the future.

**Comment by pedroteixeira** [comment]
I managed to make it work, related solution in https://github.com/bahmutov/cypress-react-unit-test/issues/15

**Comment by bahmutov** [comment]
Thanks Pedro!
