### ISSUE TITLE
Rename some internal Cypress routes for nomenclature consistency

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1410]
Nomenclature:

- a "test" is a single `it` block that status pass, fail, skipped, or pending
- a "spec" is a file consisting of 1 or more "tests". it generally has "spec" in its name: `login_spec.js`

Currently we use the internal route: `__cypress/tests/path/to/file` to serve a "spec" file. This needs to be renamed.

WIP: auditing for other inconsistencies. There are likely event names used internally that also don't refer to these correctly.

**Comment by brian-mann** [comment]
Also worth renaming this button for consistency to: 'Run all specs'

![screen shot 2018-06-10 at 12 01 33 am](https://user-images.githubusercontent.com/1268976/41198232-8647d3de-6c42-11e8-87da-8d8b84418cd6.png)

**Comment by pjean** [comment]
@brian-mann Is it possible to have a route like `__cypress/assets/path/to/file` to deliver `assets` from the project ? It will be helpful for writing tests without running a server.

For more explanation: I'm writing React UT/IT and I'm using `task` to generate the content of the application iframe but now I'm looking for a way to deliver asset like javascript bundle or css from my project directory used by the generated content.

**Comment by brian-mann** [comment]
@pjean Cypress will serve content by default if you use an absolute relative `cy.visit('/')` and you don't have a `baseUrl` setup.

**Comment by pjean** [comment]
Great, it was missing part. Thank you so much.

**Comment by jennifer-shehane** [comment]
This is already resolved. paths have been renamed. Button has new 'specs' text. 

<img width="234" alt="Screen Shot 2019-07-15 at 2 00 04 PM" src="https://user-images.githubusercontent.com/1271364/61200880-dd8b9480-a708-11e9-8086-c7e93c926573.png">
