### ISSUE TITLE
Test Runner: Expand and highlight matched get elements

### ISSUE THREAD

**Issue by chrisenitan** [cypress-io/cypress#14172]
### What would you like?
When using the [test runner](https://docs.cypress.io/guides/core-concepts/test-runner.html#Spies), the get command returns all matches for an element which can be cycled through with the eq() method. This however can be improved if each match on the DOM snapshot could be labelled according to which index exactly it matches. 

### Why is this needed?
Usually the selection process for eq() method is to get all element matches then guess which element matches the eq() index from 0 to ... Lots of trial and error here that can be solved by labelling each element matched  y its index or by allowing the get log to expand into a more detailed list per item.

![Screen Shot 2020-12-14 at 12 28 58](https://user-images.githubusercontent.com/11727537/102076663-5617e880-3e08-11eb-9f12-3953a19ee201.png)

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
