### ISSUE TITLE
cy.intercept with dynamic stubbing always sends the request to the upstream server

### ISSUE THREAD

**Issue by bukharov** [cypress-io/cypress#14189]
### Current behavior

In the following scenario `cy.intercept` always sends the request to the upstream server:
```js
cy.intercept({ url: '/sponsor', method: 'GET' }, request => request.reply('{}'))
```

<img width="743" alt="Screen Shot 2020-12-15 at 11 18 49 AM" src="https://user-images.githubusercontent.com/49371/102241793-5cb96500-3ec7-11eb-8555-b8e8f15af0a1.png">

<img width="1792" alt="Screen Shot 2020-12-15 at 11 43 41 AM" src="https://user-images.githubusercontent.com/49371/102244843-d4d55a00-3eca-11eb-9ba9-15bbd666728a.png">

It works as expected if the destination server is running. However when there is no server (on CI) it fails.

### Desired behavior

As per documentation 👇 

<img width="822" alt="Screen Shot 2020-12-15 at 11 54 34 AM" src="https://user-images.githubusercontent.com/49371/102246105-609bb600-3ecc-11eb-8e97-3b8bb331f767.png">

### Versions

Cypress `6.1.0`

**Comment by jennifer-shehane** [comment]
This looks similar to https://github.com/cypress-io/cypress/issues/9599 Do you see any failed OPTIONS requests in your network tab in DevTools?

**Comment by bukharov** [comment]
no, just this:
<img width="1643" alt="Screen Shot 2020-12-15 at 11 20 45 AM" src="https://user-images.githubusercontent.com/49371/102401373-32dc6d00-3fb1-11eb-8e6b-b155c5d6fd65.png">

**Comment by bukharov** [comment]
same thing after upgrading to `6.2.1`

**Comment by bukharov** [comment]
and `6.4.0`

**Comment by bahmutov** [comment]
Can you give us a reproducible example please

**Comment by bukharov** [comment]
with `6.5.0` it stopped working even when the upstream server is running, for some reason when I create a simpler isolated example I cannot reproduce the issue

**Comment by bukharov** [comment]
somehow in my app `net:event` does not trigger, however it triggers fine in the simplified version

**Comment by bukharov** [comment]
any tips on debugging this further?

**Comment by bahmutov** [comment]
You could see the intercept's events by enabling debug logs, see https://on.cypress.io/troubleshooting#Log-sources

**Comment by bahmutov** [comment]
Looking at the list of intercepts, it does not seem like your intercept was ever matched. Notice there is no count for `GET /sponsor`.

<img width="827" alt="Screen Shot 2021-03-01 at 2 15 00 PM" src="https://user-images.githubusercontent.com/2212006/109546740-94808380-7a98-11eb-934f-370cf6d5b247.png">

Try writing the route matcher differently, https://on.cypress.io/intercept probably using 
`cy.intercept({ method: 'GET', pathname: '/sponsor', ...)`

**Comment by bukharov** [comment]
This turned out to be a #9599 duplicate. I didnt see a failed `OPTIONS` request because to work around that issue I had an `cy.intercept` for it. Once I removed that, it started working as expected. Thanks very much for your help!
