### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by harish2506** [cypress-io/cypress#14198]
CypressError: cy.visit() failed trying to load:

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not '2xx'.

This http request was redirected '1' time to:

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

Can someone help me with this as it is never allowing me to access. I am using in Mac and cypress version is 3.8.3

**Comment by cbruge** [comment]
Hey @harish2506 you need to put basic auth headers in your visit with valid username and password, e.g. cy.visit(url, {auth: {username: "putUsername", password: "putPassword"}});.
Hope that solves the issue!

**Comment by harish2506** [comment]
I have tried using this even then i am getting the same issue.
my url is : https://www.adac.de/fahrzeugwelt/
user name: test
Password: test
e.g. cy.visit(url, {auth: {username: "putUsername", password: "putPassword"}});.

    cy.visit('http://www.adac.de/fahrzeugwelt', {auth: {username: "test", password: "test"}});

even then i am getting error. Can you please help me with correct syntax replacing.

**Comment by harish2506** [comment]
cy.visit("https://test:test@www.adac.de/fahrzeugwelt)

**Comment by cbruge** [comment]
Hey @harish2506 test test does not seem to be the right credentials. The syntax is correct. Maybe ask internally in your company what are the right credentials? (and dont post them
here;)) You can simply reproduce it by trying to log in manually first. You need to put the same credentials as when you open the website manually.

**Comment by harish2506** [comment]
Ya i have changed credentials and even tried its not allowing to login. Always throwing the same error. When i did manually i was able to login. even when i just tried clicking in cy.visit("https://www.adac.de/fahrzeugwelt") it is not even opening the page.

**Comment by cbruge** [comment]
Mhhm...I am aware there are issues with special characters mentioned in https://github.com/cypress-io/cypress/issues/4091 . Also Mac and version 3.8.3 might be a special combination somehow. The latest version of Cypress is 6.1.0. Which browser are you using and maybe a screenshot+ console output will help.

**Comment by harish2506** [comment]
I am using google chrome version.

Please find the below screenshot for reference:

![image](https://user-images.githubusercontent.com/73274946/102354315-af1f8200-3faa-11eb-81dd-9a726029937f.png)

**Comment by harish2506** [comment]
Will upgrading to latest cypress version solve the issue ?

**Comment by cbruge** [comment]
I see you have visited http://the-internet.herokuapp.com before which is a different superdomain and might lead to CORS issues. Can you try visiting the adac site in a different spec file (no baseUrl set) directly without any other superdomain prior. Actually the response is 500 and not 401 now so there is some progress😛 Updating Cypress you will get some great new features too;)

**Comment by harish2506** [comment]
I updated to adac domain and still getting the same issue(500) so would updating the cypress version solve the problem?
Should i remove the existing cypress and install new or can it be upgraded. Please confirm this

**Comment by cbruge** [comment]
If this 500 error happens only during testing via cypress it might be specific to adac.de, maybe no iframe headers allowed? See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options  Its hard to debug without more information, e.g. console output or the detailed response from the network tab of your browser. 500 is a very generic internal server error response. So not caused by Cypress directly. Try updating Cypress but no guarantee it will help. Sorry ☹️

**Comment by harish2506** [comment]
I tried updating the cypress version but still same issue. Could you let me know how can i find out the iframe headers,because when i am trying to open url i was unable to check the inspect element as well. As it is not enabled.

**Comment by cbruge** [comment]
As i assume you tried logging in manually and it worked (no 500 error), I would suggest you open the dev console and reproduce the error via Cypress while having the network tab open. This allows you to see the response in more detail. The xframe option was just a shot in the dark...If its an option for you, also get in touch with whoever developed that website so they might be able to tell you if there are any restrictions put in place. Devops, backend people, etc.

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
