### ISSUE TITLE
Can we download cypress not on postinstall but on first real use?

### ISSUE THREAD

**Issue by johnunclesam** [cypress-io/cypress#1419]
Everytime I purge node_modules and use `npm i` or `yarn` it downloads Cypress.

Can we download cypress not on postinstall but on first real use?

Thanks a lot.

**Comment by vesper8** [comment]
yea I would like a solution to this as well.. I have to purge node_modules often as well and the cypress download makes the whole ordeal 10x slower

**Comment by Bkucera** [comment]
In Cypress version `3.0`, `npm install cypress` should now be almost instant to re-install after clearing node_modules, and wont have to download the cypress binary again for that version.
However, if you still wish to disable `post-install scripts`, you can accomplish this with   
`npm install --ignore-scripts`
