### ISSUE TITLE
Allow configuration of # of tests to hold snapshots in memory

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#142]
By default Cypress begins to cleanup snapshots for tests past 50.

Based on the type of project this can be too many - and can crash Chrome.

We need to allow users be able to configure this in `cypress.json`.

**Comment by brian-mann** [comment]
Fixed in [`0.16.0`](https://github.com/cypress-io/cypress/wiki/changelog#0160-05172016).

There is now a configurable option called: `numTestsKeptInMemory` which is 50 by default.
