### ISSUE TITLE
Invalid header content crashes Cypress

### ISSUE THREAD

**Issue by ScottMaclure** [cypress-io/cypress#1420]
I'll update the below with more information when I can.

- Operating System: Win10pro
- Cypress Version: 2.1.0
- Browser Version: Chrome 64

### Is this a Feature or Bug?

Bug

### Current behavior:

Testing a site, Cypress crashes with the following express error:

```
TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:507:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at ServerResponse.header (C:\myapp\node_modules\cypress\dist\Cypress\resources\app\packages\server\node_modules\express\lib\response.js:767:10)
    at ServerResponse.header (C:\myapp\node_modules\cypress\dist\Cypress\resources\app\packages\server\node_modules\express\lib\response.js:770:12)
    at Object.setResHeaders (C:\myapp\node_modules\cypress\dist\Cypress\resources\app\packages\server\lib\controllers\proxy.js:301:18)
    at C:\myapp\node_modules\cypress\dist\Cypress\resources\app\packages\server\lib\controllers\proxy.js:216:17
```

### Desired behavior:

Cypress deals with this gracefully and alerts the dev there was a problem with malformed header content (i.e. "go fix the app" moment).

Check version of express bundled with Cypress and upgrade?

### How to reproduce:

TODO - reproduce outside of client site and post here.

#### Test code:

```js
// was a form submit off a click()
```

**Comment by brian-mann** [comment]
Just `curl` the request outside of Cypress (or just use your site in Chrome) and capture a HAR of the response and send it to us. That would allow us to reproduce this issue.

I'm not sure what the correct behavior should be. Setting invalid header content is not something "you can just force" but it's possible the user agent handles this by stripping it, ignoring it, etc. I'd have to see what chrome does.

**Comment by ScottMaclure** [comment]
Issue is with a request to 3rd party scripts, so I'm isolating that first. Will post HAR when I can.

**Comment by jennifer-shehane** [comment]
Hi @ScottMaclure, do you have an update on this? Will have to close otherwise.

**Comment by ScottMaclure** [comment]
Apologies, no longer active, closing.
