### ISSUE TITLE
Cypress doesn't take changes to baseUrl into account when running Component tests

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress#14201]
### Current behavior

![2020-12-16-162027](https://user-images.githubusercontent.com/217543/102370509-6e7d3400-3fbd-11eb-999c-b60db509c186.png)

In this picture, the URL bar in Cypress test runner doesn't start with Cypress `baseUrl` (as visible in the console at the bottom).

We have a [Single Page Application](https://en.wikipedia.org/wiki/Single-page_application) with a C# server sending mostly empty HTML pages and answering to REST requests. We use Cypress for UI tests, Component tests and E2E tests. The first 2 kinds of tests require a mock-server that we quickly implemented in nodejs to return mostly empty HTML pages and server static files (e.g., CSS and pictures). E2E tests are executed against the real C# server.

To make launching our tests simple on developer's computers, I wrote a script that starts a mock-server and a proxy to the real server, save the 2 network ports in 2 environment variables and then starts Cypress. When launched, Cypress looks at the filename of the test file (e.g., "..._spec.ui.js" or "..._spec.e2e.js") to decide which environment variable to use as `baseUrl`. This way, we have 1 Cypress window open and we can launch either UI or E2E tests: we don't have to restart Cypress with a different `baseUrl`!

This works fine except for Component tests that refuse to take the new `baseUrl` into account. As you can see in the picture, the URL is `https://dev-master....` (which is the default `baseUrl` as stored in `cypress.json`) instead of being `http://localhost:36713/...` (which is the current value of `baseUrl`).

### Desired behavior

The URL bar in Cypress test runner should start with Cypress `baseUrl`.

### Test code to reproduce

`cypress/support/index.js`:

```js
/**
 * Use Cypress environment variables to set the `baseUrl` configuration
 * parameter (used for `cy.visit()` and `cy.request()`).
 *
 * The Cypress launchers we use from package.json may set OS environment
 * variables CYPRESS_MONITOR_MOCKSERVER_PORT and CYPRESS_MONITOR_PROXY_PORT.
 * These variables are accessible from Cypress without the CYPRESS_ prefix.
 *
 * One of these 2 variables is used, if defined, depending on the kind of
 * test being run (UI or E2E).
 */
export const setBaseUrl = () => {
	let isUITest = Cypress.spec.name.match(/_spec.ui.js/);
	let isComponentTest = Cypress.spec.relative.match(/cypress\/component/);

	if (isUITest || isComponentTest) {
		setBaseUrlFromPortEnvVariable("MONITOR_MOCKSERVER_PORT");
	} else {
		setBaseUrlFromPortEnvVariable("MONITOR_PROXY_PORT");
	}
};

/**
 * Use the Cypress environment variable named `name`, if defined, to
 * set the `baseUrl` configuration parameter (used for `cy.visit()` and
 * `cy.request()`).
 */
const setBaseUrlFromPortEnvVariable = (name) => {
	let port = Cypress.env(name);

	if (port) {
		Cypress.config("baseUrl", `http://localhost:${port}`);
	}
};

setBaseUrl();
```

### Versions

- Cypress 6.1.0
- Chromium 87
-  Fedora 32

**Comment by agg23** [comment]
See also #2918

**Comment by DamienCassou** [comment]
I'm closing this issue and will reopen with more information if needed. Thank you.
