### ISSUE TITLE
chromeWebSecurity setting has no effect in Chrome 87

### ISSUE THREAD

**Issue by alexknips** [cypress-io/cypress#14217]
`chromeWebSecurity=false` does not seem to have any effect in Chrome 87

### Current behavior
![image](https://user-images.githubusercontent.com/2787821/102471280-52c56c80-4055-11eb-845e-986adc78f10f.png)

### Desired behavior
`chromeWebSecurity=false` should actually disable Chrome's web security.
A work-around like restructuring the test code is not possibly in my actual test-case.

### Test code to reproduce
```
/// <reference types="cypress" />
context('Security', () => {
  it('security settings works', () => {
    cy.visit('https://docs.cypress.io/')
    cy.visit('https://www.google.com')
  })
})
```
and `cypress.json` contains
```
{
    "chromeWebSecurity": false
}
```
### Versions
Cypress 6.1.0

**Comment by jennifer-shehane** [comment]
Setting `chromeWebSecurity: false` does not bypass Cypress enforcing the single superdomain per test. This is noted in our docs: https://on.cypress.io/web-security#Set-chromeWebSecurity-to-false

Duplicate of https://github.com/cypress-io/cypress/issues/944
