### ISSUE TITLE
Windows installation cache is not cleared

### ISSUE THREAD

**Issue by creage** [cypress-io/cypress#14210]
### Current behavior

![image](https://user-images.githubusercontent.com/910967/102404704-5a026100-3fe8-11eb-8ee9-2cae311e9a9e.png)

### Download method
 

- [x] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux
- [ ] Mac
- [x] Windows

### Other

- [x] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by jennifer-shehane** [comment]
Clearing the cache is not done automatically by Cypress. 

- You can clear the cypress cache via [`cypress cache clear`](https://on.cypress.io/command-line#cypress-cache-clear)
- You can clear all cypress cache except for your current version via `cypress cache prune`.

**Comment by creage** [comment]
@jennifer-shehane but why not? what is the purpose of having it there when I have newer version installed? Is it used somehow?

**Comment by bahmutov** [comment]
Imagine you have several projects and each one uses its version of Cypress. Imagine if running `npm install` in `projects/A` removed _all_ other Cypress versions from your machine! That would defeat the purpose of caching and require you to always re-install.

**Comment by creage** [comment]
@bahmutov I got your point, but I'm not really buying it. I'd rather prefer having multiple versions of Cypress available by option, not by default. Personally I've never seen people using a mix of Cypress versions (but that might be just me).

Our project does not. We are trying to run the most recent version of Cypress. But due to that default behavior, all of our CI/CD build servers are literally bloated with old versions, and we have to clean them manually. This is odd.

**Comment by bahmutov** [comment]
So now this is a different problem, right. Your cache restore strategy is overly broad, see https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/

As far as what to restore on the CI - it is up to you, certainly :)
