### ISSUE TITLE
Allow force different superdomains with cy.visit() 

### ISSUE THREAD

**Issue by pablogfb** [cypress-io/cypress#1421]
Hi,
I own an application with several different tlds (.com, .es, .us...). I need to run a test to check that I am showing the same dynamic content in all of them so I need to visit the different tlds in the same test.

Could be posible something like 
    cy.visit('https://whatever.com', {force: true})

**Comment by jennifer-shehane** [comment]
We will not support visiting different tlds in the same test as outlined in our tradeoffs: https://docs.cypress.io/guides/references/trade-offs.html#Same-origin

You will need to split the visiting of these domains into separate tests. This should be achievable by creating dynamic tests. Something like:

```js
const websites = [{
  domain: 'https://www.cypress.io',
  header: 'The web has evolved',
}, {
  domain: 'https://example.cypress.io',
  header: 'Kitchen Sink',
}]

describe('my tests', () => {
  websites.forEach((website) => {
    it(`is running ${website.domain}`, () => {
      cy.visit(website.domain)
      cy.get('h1').should('contain', website.header)
    })
  })
})
```

**Comment by pablogfb** [comment]
Thanks for your advice. I've managed to solve it following your instructions.
