### ISSUE TITLE
Source maps are not used in error stack traces when using `cypress run`

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#14225]
### Current behavior

Given a test that throws an error for whatever reason, e.g.

`foo.test.js`:
```js
describe('foo', () => {
    it('works', () => {
        throw new Error('oh no!')
    })
})
```

When I run this test via `cypress run`, the error's stack trace is not resolved against the source maps. Observe the line and column numbers.

```
  1) foo
       works:
     Error: oh no!
      at Context.eval (http://localhost:51223/__cypress/tests?p=cypress/integration/foo.test.js:101:11)
```

### Desired behavior
I would expect a useful stack trace so I can easily find the error in my tests—just like how it works with `cypress open`.

![image](https://user-images.githubusercontent.com/921609/102549723-82f02800-40b4-11eb-91e5-322ab0941989.png)

This would be really useful for understanding errors in CI logs.

### Test code to reproduce

See above.

### Versions

Latest version of everything

**Comment by jennifer-shehane** [comment]
I think this may be a duplicate of this https://github.com/cypress-io/cypress/issues/7715

**Comment by OliverJAsh** [comment]
I think so, I will close this then
