### ISSUE TITLE
Cypress doesnt support having the same folder for fixtures and integration

### ISSUE THREAD

**Issue by habemuscode** [cypress-io/cypress#14226]
**Description**

I use always a folder structure by features, allowing to have the code and the test in same folder per each feature/component/endpoint/whatever. This makes me more fast to follow TDD, to find bugs related to some part, and more.

I try to put this in `Cypress.json`
```
"fixturesFolder": "src",
"integrationFolder": "src",
"testFiles": "**/*.test.js"
```

But when I run Cypress in any mode, with UI or not, don't found any test

Thanks,
Regards

**Comment by jennifer-shehane** [comment]
I can recreate this issue. The easiest way to reproduce this is to set the `fixturesFolder` to the default `integrationFolder`. 

```js
{
  "fixturesFolder": "cypress/integration"
}
```

<img width="925" alt="Screen Shot 2020-12-18 at 10 09 27 AM" src="https://user-images.githubusercontent.com/1271364/102571899-2410ca00-4119-11eb-89e8-ee0fa876a80a.png">

**Comment by bahmutov** [comment]
Reproducible example in https://github.com/cypress-io/cypress-test-tiny/tree/fixtures-same-folder

Opening Cypress with debug logs

```
$ DEBUG=cypress:server:specs npx cypress open
  cypress:server:specs experimentalComponentTesting false +0ms
  cypress:server:specs looking for test specs in the folder: /Users/gleb/git/cypress-test-tiny/cypress/integration +1ms
  cypress:server:specs there is no spec pattern +0ms
  cypress:server:specs globbing test files "**/*spec.js" +0ms
  cypress:server:specs glob options { sort: true, absolute: true, nodir: true, cwd: '/Users/gleb/git/cypress-test-tiny/cypress/integration', ignore: [ '/Users/gleb/git/cypress-test-tiny/cypress/integration/**/*' ] } +0ms
  cypress:server:specs [] +7ms
  cypress:server:specs found 0 spec files: [] +2ms
```
