### ISSUE TITLE
Click events throughout the site

### ISSUE THREAD

**Issue by MStahl15** [cypress-io/cypress#14224]
Chrome Version: 
Version 87.0.4280.88 (Official Build) (x86_64)

Issue:
Clicking on any hyper links throughout the site continues to ask to download the .html file to my local machine instead of navigating me to the page.

**Comment by bahmutov** [comment]
Please provide the reproducible example we can see. Also please follow our template when opening a new issue https://raw.githubusercontent.com/cypress-io/cypress/develop/.github/ISSUE_TEMPLATE/1-bug-report.md
