### ISSUE TITLE
win.location.reload is not a function

### ISSUE THREAD

**Issue by SenneVProceedix** [cypress-io/cypress#14229]
### Current behavior
The function cy.reload() throws "win.location.reload is not a function" once every 50 tests.

### Desired behavior
reload the page

### Test code to reproduce
This code snippet is called immediately after cy.visit()
 
```
cy.waitUntil(() => {
    retry++;
    //reload the page if angular is still undefined after 10 seconds/attempts
    if(retry % 10 == 0){
        cy.reload();
    }
    return cy.window().then($window => $window.angular != undefined);
});
```
### Versions

version 6.1.0

**Comment by bahmutov** [comment]
Please provide a reproducible example we can run to see this problem. 

From the other angle: what are you trying to achieve here? Is Angular not loaded properly sometimes and you want to reload the page? Why is Angular not loaded in the first place, isn't that an error?

I would suggest using [test retries](https://on.cypress.io/test-retries) to deal with occasional Angular load failing and waiting for angular to be initialized using

```js
cy.window().should('have.property', 'angular')
```

If loading angular can take longer than the standard command timeout, set a custom timeout 

```js
cy.window({ timeout: 10000 }).should('have.property', 'angular')
```
