### ISSUE TITLE
Better handling of unexpected HTTP call responses

### ISSUE THREAD

**Issue by craig-dae** [cypress-io/cypress#14236]
### What would you like?
Built-in, simplified checks for http responses. In particular, status codes. 

### Why is this needed?
It is not enough to intercept an http call and ensure that it returns. It should return with a specific code. If you expect a 200 and get a 500, you should know immediately, rather than failing later because some DOM element doesn't exist. 

Forcing customers to write their own commands for this will produce inconsistency for what should be a basic feature. 

Additionally, if a status code does not match, we would like to see the HTTP details. This would include the body of the call, and the response. 

Here is an example of a command that I've started writing. it is a work in progress.

```js
Cypress.Commands.add(
  'withStatusCode',
  {
    prevSubject: true,
  },
  (subject, status) => {
    // If you wait for an array of calls,
    if (Array.isArray(subject)) {
      cy.wrap(subject).then((subjects) =>
        subjects.forEach((_subject) => {
          // Log the body, because we probably got a 500 or 400 that we need to debug now
          if (_subject.response.statusCode !== status) {
            cy.log(_subject.response.body);
          }
          cy.wrap(_subject).its('response.statusCode').should('eq', status);
        }),
      );
      // else, if you wait for a single call
    } else {
      // Log the body, because we probably got a 500 or 400 that we need to debug now
      if (subject.response.statusCode !== status) {
        cy.log(subject.response.body);
      }
      return cy.wrap(subject).its('response.statusCode').should('eq', status);
    }
  },
);
```

Example of usage: 
```js
      // This is an array of waits, so the command above will check that all the results are 200 in the first part of the if statement
      cy.wait(['@load1', '@load2']).withStatus(200);

     // A single wait, which is the else part of the command above
      cy.wait('@load').withStatus(200);
```

If the status is not 200, it will produce a cypress log with the body of the response. I'd like it to include the response and the request body as well. Additionally, I'd like to see it in the Cypress Dashboard, without having to view the replay video. 

If you could take this, clean it up a bit, and format it really nicely in the dashboard, it would go a LONG way to solving several of the bugs that we have had much faster. We frequently get errors in CICD that do not appear locally, which this would be ideal for.

**Comment by jennifer-shehane** [comment]
Could you provide the test code on how you're using the `.withStatusCode()` command? What are you passing into it?

**Comment by craig-dae** [comment]
Sure thing. That function is a work in progress, and I had a shadowed-variable bug. I've updated it, and I've added a usage example below.

**Comment by jennifer-shehane** [comment]
@craig-dae Can you send a screenshot of what you're Command Log looks like when you run your custom command? We're interested to see the experience that is ideal for you from the code you have.

**Comment by craig-dae** [comment]
@jennifer-shehane: This ticket might be OBE. A developer on my team pointed out that the new `cy.intercept(...)` command includes the new option for a statusCode: `cy.intercept(..., {statusCode: 200})`. We have switched over to this instead of continuing to use our `withStatusCode` function. That makes it hard to get a screenshot. 

That said, if I'm running a test and it fails, I would get more value if the message was "Expected a 200 status code response, but got 500" or something of that nature, along with a copy of the http request/response. I would need to be able to see this request/response from the Cypress Dashboard, since a lot of the time, these bugs occur in CICD, and not in our local development. 

Again, a big part of my needs revolve around getting useful errors in the Dashboard, to help me debug problems that don't happen locally. Trying to replay a video to see the Cypress panel is less valuable than having text that I can scroll through. 

It's just very difficult to reduce the CICD/local environment parity to zero. And it's difficult to fix flaky tests.

**Comment by craig-dae** [comment]
@jennifer-shehane actually, now that I'm messing with it ... I think I'm misunderstanding the purpose of `cy.intercept(..., {statusCode: 200})`. It does not appear to enforce the statusCode of a call.

**Comment by craig-dae** [comment]
![image](https://user-images.githubusercontent.com/38156593/105393956-f96bd280-5bea-11eb-8f38-d4ac84984731.png)

Something like this. I expect a 200, I get a 500, show me the payload. In this case, it's a fake payload with a string error message. It might be something more complicated though.

**Comment by craig-dae** [comment]
@jennifer-shehane another example. 

We have a flaky test being caused by something on the backend. I can't see the error in the Cypress dashboard. If I use the `cypress-terminal-report` plugin, and I go directly to my github-action container, the best I can see is: 

```js
...
"httpErrors": [
                          {
                            "headers": null,
                            "status": 500,
                            "statusText": "Internal Server Error",
                            "url": "http://localhost:8080/api/reports/resource/generate/",
                            "ok": false,
                            "name": "HttpErrorResponse",
                            "message": "Http failure response for http://localhost:8080/api/reports/resource/generate/: 500 Internal Server Error",
                            "error": {
                              "detail": "ValueError at /api/reports/resource/generate/\ntime data '2021-01-22T16:11:34.780396Z' does not match format '%Y-%m-%dT%H:%M:%SZ'\n\nRequest Method: POST\nRequest URL: http://localhost/api/reports/resource/generate/\nDjango Version: 3.0.3\nPython Executable: /opt/hostedtoolcache/Python/3.6.12/x64/bin/python\nPython Version: 3.6.12\nPython Path: ['/h ...
        cons:log ⓘ  action,
...
```

It would be AMAZING if the dashboard could show me this error. I have no idea why, for example, my date format would invalid only sometimes, but not all the time. But without a stack trace, we have to guess at it.

**Comment by jennifer-shehane** [comment]
@craig-dae I would recommend trying Test Replay in the Cypress Cloud, you should be able to see that error message. 

Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
