### ISSUE TITLE
find API is not timing out up to defaultCommandTimeout

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#14244]
### Current behavior

It seems like `find` command isn't waiting until `defaultCommandTimeout` or `{timeout: ####}` to expire.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2043287/102655911-e9faf480-4127-11eb-82ec-b9f2ee6f8d86.png">

### Test code to reproduce

> export function clickIfExist(element) {
  const date = new Date()
  cy.get('body').then((body) => {
    cy.log(`Before find: ${date.getTime()}`)
    if (body.find(element, {timeout: 20000}).length > 0) {
      cy.log(`Found it: ${date.getTime()}`)
      cy.log('Clicking element', element);
      cy.get(element).then(($button) => {
        if (($button).is(':visible')) {
          cy.wrap($button).click();
        }
        else {
          cy.log(`'${element}' is not visible`)
        }
      })
    } else {
      cy.log(`Didn't find it: ${date.getTime()}`)
      cy.log('Element not found, not clicking', element);
    }
  });
}

### Versions

Cypress: 6.1.0
Chrome:  87.0.4280.88
Mac: 11.0.1

**Comment by bahmutov** [comment]
In your example, you are not using Cypress command `.find`. 

```js
cy.get('body').then((body) => {
  // body is a jQuery element yielded by cy.get
  body.find(...) // calls jQuery .find() method
}
```

I believe you want to write something like

```js
cy.get('body').find(element, {timeout: 20000})
```
