### ISSUE TITLE
cy.within followed by cy.screenshot capture runner does not capture runner

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14253]
Cypress v6.1.0

The following test
```js
describe('page', () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
    cy.get('.banner').within(() => {
      // should capture the entire test runner
      cy.screenshot('hello-world', {
        capture: 'runner'
      })
    })
  })
})
```

I expect the screenshot to be of the entire runner, like this

<img width="1277" alt="Screen Shot 2020-12-20 at 10 51 19 PM" src="https://user-images.githubusercontent.com/2212006/102737701-1e340800-4316-11eb-825d-aa3f55316c35.png">

But it takes only the `.banner`

![hello-world](https://user-images.githubusercontent.com/2212006/102737730-33109b80-4316-11eb-8555-09e68fa4b9f6.png)

The devtools console shows the subject of the `within` affects the screenshot command, ignoring `capture: runner` option

<img width="773" alt="Screen Shot 2020-12-20 at 10 52 51 PM" src="https://user-images.githubusercontent.com/2212006/102737768-49b6f280-4316-11eb-98d9-07104c37bb9d.png">

## Desired result

when using `capture: runner` we should ignore the subject instead

**Comment by bahmutov** [comment]
Workaround is to set the subject back to the entire document (then there is no subject)

```js
cy.get('.banner').within(() => {
  // should capture the entire test runner
  cy.document().within(() => {
    cy.screenshot('hello-world', {
      capture: 'runner'
    })
  })
})
```

**Comment by jennifer-shehane** [comment]
I thought this might have been caused by a recent regression with the within changes, but this has been an issue since 3.8.1 at least.
