### ISSUE TITLE
Cypress 6.2.0 intercept regular match is invalid

### ISSUE THREAD

**Issue by Linkontoask** [cypress-io/cypress#14269]
#### Screenshot on success
![image](https://user-images.githubusercontent.com/26475695/102842978-36557580-4443-11eb-8c60-a881be8e7227.png)
#### Screenshot at the time of failure
![image](https://user-images.githubusercontent.com/26475695/102843083-6a309b00-4443-11eb-9ccd-2854e9707d8b.png)

Note that this is the same code, but it leads to different results

### Desired behavior

Success every time is not a probabilistic success.

### Test code to reproduce

https://github.com/Linkontoask/radishes/tree/cypress_bug
### Steps to reproduce
- npx lerna bootstrap
- yarn test:open
- click `news.spec.js`
```js
// Key code
cy.intercept(/\/api\/song\/url/).as('getUrl')
cy.intercept(/\/api\/song\/detail/).as('getDetail')
cy.intercept(/\/api\/lyric/).as('getLyric')

cy.get(
  '.toplist-expansion-contanier:first-child .none-select:first-child'
).dblclick()

cy.wait(['@getUrl', '@getDetail', '@getLyric']).then(interceptions => {
  cy.get('source')
    .invoke('attr', 'src')
    .then(src => {
      expect(src).to.have.string('.mp3')
    })

  // pause music
  cy.get('.music-command-group button:nth-child(3)').click()
})
```

**Comment by Linkontoask** [comment]
I think I have found the root cause of the problem. It is because of the cache problem of get requests. I am not sure if this is the expected behavior. If it is, please close this issues.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Confirmed that the `cy.wait` throws an error after the second trial in 7.2.0.

But I have a question about the behavior of the app. When a request is sent to the same endpoint the second time, is it sent to the server or brings the data from cache? 

If the first, it's a bug. If the second, it's an intended behavior.

**Comment by Linkontoask** [comment]
Thank you for your reply. At present, it is the cache hit that causes the capture to fail.
