### ISSUE TITLE
Option To Configure/Bypass Final Courtesy Check For Running Server

### ISSUE THREAD

**Issue by tdreid** [cypress-io/cypress#14262]
### What would you like?

As discussed [here](https://github.com/cypress-io/cypress/discussions/14233) cypress checks for the sever running at `baseUrl`. If this check fails it exits. The number of retries is not configurable, nor can the check be bypassed.

- An option to suppress this check (nice to have -- ability to change it a "warning") 
- An option to configure the number of retries (nice to have -- retry-until-success).  

### Why is this needed?

- So that other mechanisms for ensuring that the server is already running during test are not superseded by this non-optional check.

- Avoid introducing dependencies on, e.g. `wait-on`, `start-server-and-test`

**Comment by estefafdez** [comment]
+1 on this one.

**Comment by ShubhamPalriwala** [comment]
Hey @jennifer-shehane, So basically we have to allow a user to configure the number of tries in the CLI as options and an option to bypass the baseUrl check. 
Is this what we are trying to fix?

**Comment by jennifer-shehane** [comment]
@ShubhamPalriwala I'm not sure exactly how the team would want to implement these changes, so I don't have a path forward at this time exactly for a change.

**Comment by jennifer-shehane** [comment]
Since this issue hasn’t gotten a lot of interest, we’ll close this issue. I think we may have increased the time to retry since this was opened though.
