### ISSUE TITLE
experimentalSourceRewriting - Dropdown unresponsive when setting this config as true.

### ISSUE THREAD

**Issue by TheFreeRangeTester** [cypress-io/cypress#14267]
<!-- 👋 Use the template below to report a bug. Fill in as much info as possible. 

### Current behavior
The dropdown selector ('.k.dropdown-wrap > .k-input') is not working when having the "experimentalSourceRewriting" config as true.

When disabling this config, clicking the above locator works correctly. 

### Desired behavior

The elements can be clicked when having experimentalSourceRewriting as true.

### Test code to reproduce
I've tried this with Electron and Chrome, same result. the code involves a click action for the element (you can find the locator above). Given this is on my work machine and because of confidentiality, can't share much more. 

### Versions

I'm using Cypress 6.1.0, on a Windows 10 enterprise machine with Intel Core i5-6200U CPU @ 2.30GHz 2.40 GHz and 16 GB of Ram,

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
