### ISSUE TITLE
"visit" overwrite is ignored when using @cypress/react

### ISSUE THREAD

**Issue by midanosi** [cypress-io/cypress#14260]
### Current behavior
`Custom.Commands.overwrite("visit", () => {...})` is ignored in repositories which use @cypress/react

### Desired behavior
To have my custom "visit" overwrite respected

### Suspected cause
https://github.com/cypress-io/cypress/blob/fb71b6548930ed671119c8a26457d921f07fbd1a/npm/react/src/hooks.ts
I think the "visit" override in the file above disallows a further overwrite to be made.
This is only called if `require("@cypress/react/support")` is included in `cypress/support/index.js`.

Sidenote: Thanks for making @cypress/react. I began using cypress-react-unit-test just a few days before it was moved, and I'm so excited for my future of writing unit/integration tests with visual feedback, whilst also being to run them in pipelines without depending on a pre-existing deployment. Match made in heaven!

**Comment by lmiller1990** [comment]
Hi @midanosi,

Thanks for your patience!

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (but still in alpha, with lots of updates and improvements coming in the next few weeks).

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

The main difference is we moved from a `file:preprocessor` architecture to a dev-server architecture. Component testing is no longer experimental, and has a dedicated runner (which is build on top of an extends the existing cypress runner).

The main benefits of the improved component testing runner and architecture are:

- no need to call `cy.visit()`. Using `mount` will directly render your component
- things are now (much) faster
- no need to launch into the electron shell. It opens straight to the browser (select your spec from the inline spec selector)

Do you have a specific reason or use case to want to override `cy.visit()` in your component tests?

**Comment by midanosi** [comment]
My main problem was that I was overwriting cy.visit() for my e2e test suite, and I was running cypress component tests in the same repo.
Now that there is the well-defined split between component test suite, and e2e test suite in the same repo (as far as I can briefly tell, haven't yet tried), I'm guessing this issue will be resolved? If you're confident that it is, happy for this to be closed!

Thanks for the reply, and congrats on the alpha release, and best of luck with further work, I'm really excited to see it develop

**Comment by lmiller1990** [comment]
I'll close it for now, lmk if you run into any problems in the future.

Thanks for the praise - this is just the beginning, lots more to come 🚀
