### ISSUE TITLE
no longer can attach file to the input after updated to version 6.2.0

### ISSUE THREAD

**Issue by inmotionnowalex** [cypress-io/cypress#14275]
### Current behavior
currently file dose not get attached to the input, im getting 520 error, if im going back on version "cypress": "5.3.0", everything is working as expected

### Desired behavior
file gets attached

### Test code to reproduce

![attachfile](https://user-images.githubusercontent.com/54545161/102910319-5f2c3980-4448-11eb-917f-8b07db724410.gif)

![image](https://user-images.githubusercontent.com/54545161/102909406-ed072500-4446-11eb-826a-edb9ef74cd8d.png)
cy.get('input[type="file"]').attachFile(path)
![image](https://user-images.githubusercontent.com/54545161/102909819-8afaef80-4447-11eb-9a8c-abba003509cd.png)

```
"Data":null,"Error":{"ErrorID":"637442507793810408","Kind":"Exception","Message":"Unexpected end of Stream, the content may have already been read by another component. ","StackTrace":"   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)\r\n   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)\r\n   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.TryCreateAsync(ActionContext actionContext, IList`1 factories)\r\n   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"
```

### Versions

 Last worked version 5.3.0     Updated version 6.2.0    OS Windows 10  Browser Chrome 87

**Comment by jennifer-shehane** [comment]
It looks like you're using cypress-file-upload plugin, have you tried filing an issue there? Because with the current example, we can't tell if this is an issue with Cypress or the plugin.

Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by MuckT** [comment]
Had a similar issue with cypress-file-upload. It was working with 6.2.0 in Chrome; however, when updating to 6.2.1 the plugin stopped working with pdf files specifically. Went so far to delete my node_modules  folder and do an ```npm install```, but the issue persisted. Looks similar to the issues in this thread: [cypress-file-upload#239](https://github.com/abramenal/cypress-file-upload/issues/239)

**Comment by jennifer-shehane** [comment]
@MuckT Can you provide a reproducible example? Seems strange to fail in 6.2.1 specifically.

**Comment by Sindr0me** [comment]
Hi, have the same problem with intercept, but my cypress version is 6.1.0. I jyst let you this small example:

my file input uploader: 
```
Cypress.Commands.add(
  "uploadFile",
  { prevSubject: true },
  (subject, fixturePath, mimeType) => {
    cy.fixture(fixturePath, "base64").then((content) => {
      const blob = Cypress.Blob.base64StringToBlob(content, mimeType);
      const file = new File([blob], fixturePath, { type: mimeType });
      const dataTransfer = new window.DataTransfer();
      const fileInput = subject[0];

      dataTransfer.items.add(file);
      fileInput.files = dataTransfer.files;

      cy.wrap(subject).trigger("change", { force: true });
    });
  }
);
```
define aliases:
```
  cy.intercept("POST", "/api/rc/update_rc").as("uploadFilePOST");
  cy.get('[accept=".xlsx"]').as("fileInput");
```

intercept request and uploading:
```
    cy.get("@fileInput").uploadFile(fixturePath, mimeType);
    cy.wait("@uploadFilePOST").then((xhr) => {
      expect(xhr.response.body.statusCode).to.equal(201);
    });
```

In this case i got an error from my server _Unexpected end of multipart data_
Therefore i decided move back to route. He's working correctly.

My file have sended via using intercept. With route it's empty instead of this strange symbols:

![image](https://user-images.githubusercontent.com/32894023/107033041-c5390a00-67c5-11eb-8e2a-4d579131bb17.png)
