### ISSUE TITLE
How lauch cypress on windows 10?

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1427]
Hi,

I would like ton open cypress on windows but I don't know exactly the path. I don't find informations in Cypress documentation. Could you help me?
Regards,
Elisa

**Comment by pgroot91** [comment]
You just download it and unpack it and launch the Cypress.exe?

or 

You install/run true the command line CMD or GITbash or something. (Node.js) 
node_modules\.bin\cypress open

**Comment by perceboisElisa** [comment]
Hi,

when I run: 
C:\..path project..>node_modules\.bin\cypress open
I get  the following error:
module.js:540
    throw err;
    ^

Error: Cannot find module '...path project...\node_modules\cypress\bin\cypress'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

I solved my issue by clicking on Cypress.exe

Regards,
Elisa

**Comment by jennifer-shehane** [comment]
@perceboisElisa Did you get Cypress up and running?

**Comment by perceboisElisa** [comment]
Hi,

Cypress.io on windows 10 - 64 bits doesn't actually work :-). 

When I click on Cypress.exe, a new "cypress" folder is always created...and I got "This browser was not launched through Cypress. Tests cannot run" and a Run Chrome 64 button appears.

Elisa

**Comment by jennifer-shehane** [comment]
@perceboisElisa It does sound like the install properly worked, but you are encountering another error. This issue details the error it seems to be you are seeing - https://github.com/cypress-io/cypress/issues/1239

**Comment by manideepmedisetty** [comment]
Hello Can someone help me with below issue when trying to open cypress
![image](https://user-images.githubusercontent.com/49680758/56211387-6bf26a80-6075-11e9-9b92-8cc0b84e4d7c.png)

**Comment by jennifer-shehane** [comment]
@manideepmedisetty You may want to try `npm prune` or deleting your node_modules folder and running `npm i` again.

**Comment by peterkemenyas** [comment]
Workaround:
1. Delete the file "E:\TestingCypress\node_modules.bin\cypress"
2. Open cypress again

**Comment by Pratyushwildnet** [comment]
Please help if anyone knows how to resolve this error.

When I tried to run the cypress Sample Test it crashed and showing the error below :

Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

I am using cypress the first time. so please If anyone knows please help.

When I run the same in Macbook then it's working fine but not for windows.

Nodejs: 12.14.0 windows: 10

**Comment by Pratyushwildnet** [comment]
@jennifer-shehane Please check my issue also if you can help me with this. As I am new and not able to start my work.

This is working fine on Macbook perfectly but not on Windows.
