### ISSUE TITLE
We should stringify an empty jQuery element better

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14279]
When throwing an error, I see the following

<img width="598" alt="Screen Shot 2020-12-22 at 2 29 22 PM" src="https://user-images.githubusercontent.com/2212006/102926286-b808cb80-4462-11eb-8063-cc4d6bdec749.png">

Which is due to code in `$utils.stringifyActual(subject)`

Debugging this I see an empty jQuery element. 

<img width="808" alt="Screen Shot 2020-12-22 at 2 29 14 PM" src="https://user-images.githubusercontent.com/2212006/102926276-b4754480-4462-11eb-8ae1-a44cf18b8c1e.png">

We can definitely report a better message instead of `{}`

I will create a better reproducible example, right now this happens inside a custom command

**Comment by sainthkh** [comment]
Below is the reproducible example:

```js
it('throws when not passed DOM element as subject', () => {
  cy.visit('fixtures/dom.html')
  cy.noop(cy.$$('#should-not-exist')).scrollTo('250px')
})
```

![Screenshot from 2021-01-27 17-36-01](https://user-images.githubusercontent.com/8130013/105964953-3857c780-60c6-11eb-92ef-b5a78f050140.png)
