### ISSUE TITLE
cypress can't process "SAMLRequest or SAMLResponse "

### ISSUE THREAD

**Issue by lijingshanxi** [cypress-io/cypress#14284]
### Current behavior

I use cypress to sign in, but after click sign in button, errors occurs:

![image](https://user-images.githubusercontent.com/13703027/102949543-7e3bd180-4503-11eb-812e-a57bd16873f5.png)

AADSTS750054: SAMLRequest or SAMLResponse must be present as query string parameters in HTTP request for SAML Redirect binding.

Request Id: 03a12765-7f34-469c-9a10-721d94082e00
Correlation Id: ee08e253-a216-4350-99c7-f9545526e8f2
Timestamp: 2020-12-22T11:05:16Z
Message: AADSTS750054: SAMLRequest or SAMLResponse must be present as query string parameters in HTTP request for SAML Redirect binding.

### Desired behavior

I can sign in;

### Versions

Cypress:    6.2.0
Browser:    Chrome Version 88.0.4324.11 (Official Build) dev (64-bit)

**Comment by jennifer-shehane** [comment]
Looks like this error: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-sign-in-problem-federated-sso-gallery#saml-request-not-present-in-the-request

Can you explain how you are signing in? What code are you using? cy.request()?

**Comment by lijingshanxi** [comment]
> Looks like this error: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-sign-in-problem-federated-sso-gallery#saml-request-not-present-in-the-request
> 
> Can you explain how you are signing in? What code are you using? cy.request()?

Hi, here is my code:
    describe('Sign In Button:', () => {
      it('find sign in button', () => {
        // Step 2: Take an action (Sign in)
        cy.wait(1000);
        cy.get(selectors.usernameInput).type("my_user_name");
        cy.wait(1000);
        cy.get(selectors.signInButton).contains('Log In').click();
        cy.get(selectors.inputPasswd).type("my_password");
        cy.get(selectors.inputSubmmit).contains('Sign in').click();
        // Step 3: Make an assertion (Check for sign-out text)
      });
    });
P.S. I use windows domain user and password to login, I think the problem is related to windows domain login functionality;

**Comment by jcopperman** [comment]
It appears this issue is with SSO in general, or at least I suspect so. I am having the same issue with [keycloak].   
 (https://stackoverflow.com/questions/65810102/cypress-ui-automated-login-with-keycloak-fails)

I am using `cy.visit`

**Comment by mwhitney86** [comment]
Any update on this?
