### ISSUE TITLE
Snowpack preprocessor

### ISSUE THREAD

**Issue by alejandroiglesias** [cypress-io/cypress#14285]
### What would you like?
In a similar way that there are preprocessors for Webpack, Browserify, Rollup, and Parcel, I would like to request a preprocessor for Snowpack. Snowpack is going to be included as a part of the next-gen [SvelteKit](https://svelte.dev/blog/whats-the-deal-with-sveltekit) web application framework, so it will most probably become a standard in the Svelte community. I took a look at the Webpack preprocessor but I'm not experienced with TypeScript, so it seems difficult to quickly adapt. Also, I'm still new to all Snowpack options. I opened a [ticket in the Snowpack repository](https://github.com/snowpackjs/snowpack/discussions/2095) as well in case a collaboration across projects is possible.

### Why is this needed?
This would allow us to implement cypress-svelte-unit-test within our build process using Snowpack.

**Comment by aislanmaia** [comment]
Any progress?

**Comment by jennifer-shehane** [comment]
Our team is not working on this feature. We would be open to PRs/plugins to support this.

**Comment by JessicaSachs** [comment]
Since Svelte and SvelteKit are Vite-based now, I suggest closing this issue.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
