### ISSUE TITLE
How lauch Cypress on app using certificate?

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1428]
Hi,

I would like to run my app with Cypress. However, we use certificates which need to be validate by the user before running your app. Which file must be configure in Cypress?

Regards,
Elisa

**Comment by lcastanedaCV** [comment]
I am having this similar issue. 
And can't find a solution to previous issues.
Can we open this again?

Here are my details
The page I am testing uses a certificate. If I open the page on the regular Chrome the page loads with no problem. But when I launch Cypress I get a "The connection is not secure" along with a 401 error (I am not sure if these are related). 
How do I use the certificate installed on my chrome into the chrome instance of Cypress' chrome?

**Comment by brian-mann** [comment]
@lcastanedaCV we tell the browser to ignore security errors so I'm not sure how you could be getting this unless you're modifying the arguments in which we launch chrome or you're doing something out of the ordinary.

Cypress must sit between your browser and the webserver and it will not work unless its making the connections, so the answer is you can't - but there's not any reason to need to do so.

The certificates don't affect the browser's actual behavior. 

Are you trying to load an ip address by chance? If so if you set an alias in your `/etc/hosts` file and visit that, you won't see that message. I think that's the only scenario in which we've seen that message happen.

What site are you trying to visit? Have you tried visiting it in Electron?

**Comment by lcastanedaCV** [comment]
Hi @brian-mann,
Thank you for your help.
/etc/hosts solved the problem
Cheers!

**Comment by Niemetz** [comment]
Hi @brian-mann  and @lcastanedaCV 
  I'm running into the same issue... what are the things I need to fix in my /etc/hosts?
  Thank you very much
