### ISSUE TITLE
After updating the Cypress Version from 6.0 to 6.1.0, all tests do not run

### ISSUE THREAD

**Issue by sofinapradhan** [cypress-io/cypress#14295]
After updating the Cypress Version from 6.0 to 6.1.0, I am getting this error when tests are run in headless mode for a long time (like 1 hour 13 minutes). 

I did not have this issue before when using Cypress version 6.0

****************************************************************************************************************
Starting type checking service...
Using 1 worker with 2048MB memory limit

<--- Last few GCs --->
```
[24432:000003EF00000000]  4200569 ms: Mark-sweep (reduce) 3625.0 (3728.9) -> 3584.7 (3727.8) MB, 1945.6 / 0.0 ms  (average mu = 0.940, current mu = 0.962) last resort GC in old space requested
[24432:000003EF00000000]  4202867 ms: Mark-sweep (reduce) 3584.7 (3727.8) -> 3584.1 (3707.3) MB, 2298.4 / 0.0 ms  (average mu = 0.878, current mu = 0.000) last resort GC in old space requested
```

<--- JS stacktrace --->
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00007FF6F7ADBBC6 node::Buffer::New+47574
 2: 00007FF6F7ADBDC5 node::Buffer::New+48085
 3: 00007FF6F58E0E33 v8::internal::Version::GetVersion+803
 4: 00007FF6F58E0DD1 v8::internal::Version::GetVersion+705
 5: 00007FF6F5A83D53 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+195443
 6: 00007FF6F5A8C499 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+230073
 7: 00007FF6F5A5C51A cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+33594
 8: 00007FF6F5A57639 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+13401
 9: 00007FF6F5CAF8D7 v8::internal::OSROptimizedCodeCache::GetBailoutIdFromEntry+96439
10: 00007FF6F58EE5DB v8::JSON::Parse+1083
11: 00007FF6F58FE83B v8::String::Utf8Length+43
12: 00007FF6F7AD195F node::Buffer::New+5999
13: 00007FF6F594C1BE v8::CFunction::CFunction+212110
14: 00007FF6F594B606 v8::CFunction::CFunction+209110
15: 00007FF6F594AC29 v8::CFunction::CFunction+206585
16: 00007FF6F594A8C7 v8::CFunction::CFunction+205719
17: 00007FF6F6349E3C v8_inspector::V8StackTraceId::ToString+3489308
18: 000003EF00E3CFA7


  1) An uncaught error was detected outside of a test

  0 passing (426ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     Error: The following error originated from your test code, not from Cypress.

  > Fetching resource at '/__cypress/tests?p=src\integration\libs\features\user-profile\user-profile-incomplete.spec.ts' failed

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at XMLHttpRequest.xhr.onerror (http://localhost:57185/__cypress/runner/cypress_runner.js:174416:14)
```
*******************************************************************************************************************************

Last known working Cypress Version 6.0
Browser: Chrome Version 87.0.4280.88 
Operating System: windows 10 (64-bit)

**Comment by chenfan-fchen** [comment]
Add this into your support/index.js try to see if this can resolve your problem.
`Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
})`

If still not, refer this https://docs.cypress.io/api/events/catalog-of-events.html#Examples to see which situation are you belong to

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by sofinapradhan** [comment]
@jennifer-shehane,
 
I have total 182 spec files. I am running all 182 specs files serially in a headless mode.

When running 10th specs files, I get the following error message regardless my 10th spec file contains the test-case or not. However, the testing is not aborted until it reaches to 164th (or 165th) spec files.

![1st](https://user-images.githubusercontent.com/12257060/103579327-5a7a7300-4e95-11eb-95c0-a71c5fec2234.png)

When running the 164th (or, 165th sometimes) spec file, it displays the above FATAL Error message regardless the spec file contains the test-case or not. Then, the remaining spec files do not run

![2nd](https://user-images.githubusercontent.com/12257060/103579362-6b2ae900-4e95-11eb-90dc-2d8908f3578a.png)

**Comment by bahmutov** [comment]
I see the message "starting type checking service". If this is typescript server running on every spec, it will be very memory consuming. Can you disable the typescript checks while running Cypress tests?

**Comment by sofinapradhan** [comment]
@bahmutov, how do I disable the typescript checks while running Cypress tests?
