### ISSUE TITLE
Unable to install cypress on an existing project

### ISSUE THREAD

**Issue by shreyaj-5** [cypress-io/cypress#14301]
Machine: Windows 10
Babel: 6.26.3
Webpack: 2.2.1
Node: 12.18.3
NPM: 6.14

Any help would be appreciated. I would prefer not to do updates at this point.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the template provided, we have one for [Install Issues](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/2-install-issue.md) - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
