### ISSUE TITLE
npx cypress open with Chrome always use headless mode

### ISSUE THREAD

**Issue by chenfan-fchen** [cypress-io/cypress#14307]
### Current behavior
When I use `npx cypress open` and select Chrome to run my test case, it worked always like headless mode, I only can see my test cases in left side, the realtime execution browser didn't appear
![image](https://user-images.githubusercontent.com/34032008/103068668-94778980-45f8-11eb-814f-a87a54317ed6.png)

So I have to use `npx cypress run --chrome --no-exit` to see how the action happen in browser
![image](https://user-images.githubusercontent.com/34032008/103068332-e4a21c00-45f7-11eb-8ab9-25858830bcb3.png)
### Desired behavior
`cypress open` with chrome, the default is use headed mode, so when I use debug my test case with cypress open, I wish I could see the browser on right side and to know how my test cases run

do you met the same issue ? and could you help me on this, thanks

### Versions
**Cypress:** 5.6.0
**Mac:** 10.14.6
**Chrome:** 87.0.4280.88

**Comment by jennifer-shehane** [comment]
Could you try following [these instructions](https://on.cypress.io/troubleshooting#Clear-App-Data) to Clear App Data?

I imagine that you dragged the left side bar so far to the right at some point that it is not taking up the entire width of the runner. You could play with moving the window around a bunch and it will come back, but clearing the app data will the left side bar to its original side.

Related issue: https://github.com/cypress-io/cypress/issues/2132

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
