### ISSUE TITLE
Execute Javascript statement

### ISSUE THREAD

**Issue by Kamuna** [cypress-io/cypress#14316]
Is there a way to execute a javascript statement in cypress. For example i am trying to run the following statement when i get to a certain page:

I want to run this and this works when i run it in chrome console: $.event.trigger({type: "Scan",message: "scanned",time: new Date()});

I have tried this:

Cypress.$.event.trigger({ type: "Scan", message: "scanned", time: new Date() });

But nothing seems to happen

Version 6.2.0

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
