### ISSUE TITLE
Persist Chrome settings

### ISSUE THREAD

**Issue by nachocab** [cypress-io/cypress#1431]
Is it possible to persist the Chrome Theme setting? 

I always have to go to `Settings | Appearance | Themes | Reset to default` because with the Cypress theme it is quite difficult to see the tab names if you don't hover over them.

Enabling this would make it easier for people to use the Cypress browser as their default while developing

**Comment by jennifer-shehane** [comment]
Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
