### ISSUE TITLE
Whoops we can't run your test. This browser was not launched through Cypress. Tests cannot run

### ISSUE THREAD

**Issue by Supanovas** [cypress-io/cypress#14322]
### Current behavior
Has anyone come across this? Running one of the examples tests in the integration folder and using Firefox Dev Edition 85 as the preferred browser and it throws this error when it launches the browser.

Ran it also on Firefox 84.0.1 and got the same issue. Runs fine on Edge and the prebaked Electron browser.

![image](https://user-images.githubusercontent.com/35727935/103142150-accdce00-46f6-11eb-8ce0-c0038ee8085a.png)

![image](https://user-images.githubusercontent.com/35727935/103142158-beaf7100-46f6-11eb-9626-8717f9ce1bb1.png)

When i click on the Cypress logo on the top right of the launched browser and select the "Docs" a new tab is opened and the connection is secure 

![image](https://user-images.githubusercontent.com/35727935/103142200-409f9a00-46f7-11eb-86cc-7eb2ec5246c6.png)

It would appear that it's just the browser launched by the test runners that's flagged and throws the connection not secure error.

### Versions

Cypress 6.2.0

**Comment by jennifer-shehane** [comment]
Certain group policies (GPOs) on Windows may prevent Cypress from working as intended, which can cause tests to break. 

Can you read here for more info and workarounds: https://on.cypress.io/error-messages#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues and see if any of those resolve your issues?

Likely a duplicate of https://github.com/cypress-io/cypress/issues/6889

**Comment by Supanovas** [comment]
@jennifer-shehane Ok, will do and update you shortly.

**Comment by adikeshri** [comment]
Any update on this yet?

I'm still facing this issue in Chrome & Edge but electron seems to be working.

**Comment by startfromzero0** [comment]
![image](https://user-images.githubusercontent.com/35767332/190535233-ea72ad67-00c6-435d-a73d-1923ae36df78.png)
I use the Kirin system with ARM architecture, and the browser is based on Chromium 360. After being configured in config.js, the browser can be displayed on the interface, but this error is also reported when I use it

**Comment by elibroftw** [comment]
Yeah @jennifer-shehane, how do you use custom browsers? I'm trying to use my Tauri app as a browser, but after hours I'm hit with 

"This browser was not launched through Cypress. Tests cannot run."

What specifically does Cypress check for in the browser to determine if tests may or may not run? Maybe then I can ask Tauri to support Cypress. Or maybe you guys can help me support Tauri.
