### ISSUE TITLE
The CDP port requested was 53160.

### ISSUE THREAD

**Issue by KamranShan-arbisoft** [cypress-io/cypress#14323]
Kindly can you please tell me what's wrong I can't understand the below issue.

Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 20 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 53160.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:53160 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/8986
