### ISSUE TITLE
Environment variables are combining as one string when there is comma separated values via --env

### ISSUE THREAD

**Issue by senthiltr** [cypress-io/cypress#14336]
HI,
I am start using cypress recently. I need to pass credentials(ip, username, password) via cli because need to run this tests on different VM. I used this command to pass credentials and get those values using `Cypress.env('HOST')`. But in cypress all the comma separated values combined and coming as one string. Can you please tell any wrong in my command and any other suggestion.
Currently using cypress release is below,
```
Cypress: 5.1.0 │
│ Browser: Firefox 84 │
│ Specs: 1 found (test.js) │
│ Searched: cypress\user_test_suites\test.js
```

command:
```
./node_modules/.bin/cypress run --env HOST="www.google.com",DATA="cypress tutorial" --headed --spec "cypress/user_test_suites/test.js" --browser firefox
```

tests:
```js
describe("TEST1", function(){
it.only("test2",()=>{
cy.log(Cypress.env())
cy.visit(Cypress.env("HOST"))
cy.get("q").type(Cypress.env('DATA'))
})
})
```
### Current behavior

```
CypressError: cy.visit() failed trying to load:

http://www.google.com/%20data=cypress%20tutorial/
```

`Cypress.env("HOST")` giving as whole www.google.com data=cypress tutorial.

### Desired behavior

The comma separated environment variables should not join with first environment variable.
### Test code to reproduce

The below are the same result getting from 6.2.0
```
(Run Starting)
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Cypress: 6.2.0 │
│ Browser: Firefox 84 │
│ Specs: 1 found (test.js) │
│ Searched: cypress\user_test_suites\test.js │
└──────────────────────────────────────────────────────────────────────────────────── Running: test.js (1 of 1)
TEST1
1) test2

0 passing (2s)
1 failing

TEST1
test2:
CypressError: cy.visit() failed trying to load:
http://www.google.com/%20data=cypress%20tutorial/

The response we received from your web server was:

404: Not Found
```

### Versions
5.1.0 , 6.2.0

**Comment by jennifer-shehane** [comment]
This example works from our docs, which is similar. Also the example below works for me on Mac:'

```
cypress open --env HOST="www.google.com",DATA="cypress tutorial"
```

```js
it('test', () => {
  cy.log(Cypress.env())
  expect(Cypress.env('HOST')).to.eq('www.google.com')
  expect(Cypress.env('DATA')).to.eq('cypress tutorial')
})
```

The example given also works for me, also with additional args. 

```
cypress open --env HOST="www.google.com",DATA="cypress tutorial"
```

```js
it('test', () => {
  cy.log(Cypress.env())
  cy.visit(Cypress.env("HOST"))
  cy.get("[name='q']").type(Cypress.env('DATA'))
})
```

<img width="525" alt="Screen Shot 2020-12-29 at 11 13 10 AM" src="https://user-images.githubusercontent.com/1271364/103259251-ef2d2e80-49c6-11eb-9e38-c612612f881a.png">

Are you on Windows? What terminal are you using? Because I've seen weird stuff in the past with quotations and some terminals not knowing how to read it the same.

**Comment by senthiltr** [comment]
> This example works from our docs, which is similar. Also the example below works for me on Mac:'
> 
> ```
> cypress open --env HOST="www.google.com",DATA="cypress tutorial"
> ```
> 
> ```js
> it('test', () => {
>   cy.log(Cypress.env())
>   expect(Cypress.env('HOST')).to.eq('www.google.com')
>   expect(Cypress.env('DATA')).to.eq('cypress tutorial')
> })
> ```
> 
> The example given also works for me, also with additional args.
> 
> ```
> cypress open --env HOST="www.google.com",DATA="cypress tutorial"
> ```
> 
> ```js
> it('test', () => {
>   cy.log(Cypress.env())
>   cy.visit(Cypress.env("HOST"))
>   cy.get("[name='q']").type(Cypress.env('DATA'))
> })
> ```
> 
> <img alt="Screen Shot 2020-12-29 at 11 13 10 AM" width="525" src="https://user-images.githubusercontent.com/1271364/103259251-ef2d2e80-49c6-11eb-9e38-c612612f881a.png">
> 
> Are you on Windows? What terminal are you using? Because I've seen weird stuff in the past with quotations and some terminals not knowing how to read it the same.

Yes. I am using Windows 10. Using Visual Studio Code Editor with default Powershell terminal. I am seeing this issue after remove quotes also.

**Comment by jennifer-shehane** [comment]
Can you try passing a JSON stringified object surrounded by single quotes to the env flag?

```js
cypress run --env '{"HOST":"www.google.com","DATA":"cypress tutorial"}'
```

**Comment by senthiltr** [comment]
I am getting the below result,
.\node_modules\.bin\cypress run --env '{"HOST":"www.google.com","DATA":"cypress tutorial"}' --headed --spec "cypress/user_test_suites/test.js"

Cypress encountered an error while parsing the argument env

You passed: {HOST:www.google.com,DATA:cypress tutorial}

The error was: Cannot read property 'split' of undefined
