### ISSUE TITLE
Uncaught SyntaxError: The following error originated from your application code, not from Cypress.

### ISSUE THREAD

**Issue by SuhasSunzant** [cypress-io/cypress#14340]
### Current behavior

Ucaught exception making tests to fail 
```
Uncaught SyntaxError: The following error originated from your application code, not from Cypress.
```

I added the code below 
```js
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  debugger
  return false
})
```

But still the exceptions not handled and cypress stops the flow 
![Uncaught exception](https://user-images.githubusercontent.com/26137334/103272350-a2575100-49e2-11eb-99b9-02a232d74923.PNG)

### Desired behavior

i am testing my commercial e-commerce application
### Test code to reproduce

cannot provide the code for the moment but i can share few details on exceptions 

### Versions
6.2.0

**Comment by CypressHarry** [comment]
This issue does not contain enough information for me to reproduce the issue.

**Note:**

I see you have sent a message to Cypress Support with screenshots of your test. Based on the screenshots provided, it looks like your tests are still running when the above error was thrown in the console. This means that your [Uncaught Exception handler](https://docs.cypress.io/api/events/catalog-of-events.html#Uncaught-Exceptions) is working as intended.

The below image shows the behavior that would happen if you removed the exception handler from your test. Your error would not appear in the Dev Tools console, but would be thrown in the Cypress Test Runner command log:

![Screen Shot 2020-12-29 at 11 38 16 AM](https://user-images.githubusercontent.com/64650781/103299487-a8d9ce80-49ca-11eb-9b63-c9a128bafcb1.png)
