### ISSUE TITLE
Unable to select a specific date in future when trying each method in if block

### ISSUE THREAD

**Issue by bhupy2312** [cypress-io/cypress#14346]
<!-- 👋 Use the template below to report a bug. Fill in as much info as possible. 
Hi,
Im trying to select the specific date in future in reservation site by clicking on next > in Date picker overlay. but im unable to select a date
can we use each in if block, i used but it works clicking 2 times but my selection date is based on 3rd click (April 31)
My code clicks on next twice only but i  need to see the April date by clicking on 3rd time.

### Current behavior
Im trying to select the specific date in future in reservation site by clicking on next > in Date picker overlay. but clicks on > twice and stops

### Desired behavior
From the Date calendar popup it should select April 31

### Test code to reproduce
import 'cypress-iframe'
import SearchPage from '../Aircanada/SearchPage'
describe('Aircanada TestSuite', function(){
 
it('Testcase02', function(){
    cy.visit('https://www.aircanada.com/ca/en/aco/home.html#/')
    cy.get('input#tripTypeField').click({force: true})
    cy.wait(3000)
    cy.get('ul.select-list').find('#tripTypeIdtripType_O').click()
    cy.get('span.flight-calendar-label').click()    
    cy.wait(2000)
    cy.get('.ui-datepicker-title').find('div').each(($monyear, index, $list) => 
    {
                if($monyear.text()==="April 2021")
                {
                    cy.get('table.ui-datepicker-calendar td').each(($date, index, $list)=>
                    {
                        const date = $date.find('span.ui-calendar-date').text()
                        if(date==='31')
                            {
                                cy.wrap($date).click({force: true})
                
                            }
                    })
                }
                    cy.wait(2000)
                    cy.get('a.ui-datepicker-next span:visible').find('span.sr-only').click({force: true})
                    cy.wait(2000) 
                    })
 
            })
})

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
