### ISSUE TITLE
Cannot read property 'uhcDB' of undefined when environment variables are referenced from within a cypress "task" in /plugins/index.js

### ISSUE THREAD

**Issue by parul-adhikari** [cypress-io/cypress#14347]
I am trying to get an object (in plugins/index.js) from one of my environment config files, but the test fails with the error:
```js
"cy.task('executeQuery') failed with the following error:
> Cannot read property 'uhcDB' of undefined"
```

This is what my plugin/index.js looks like:

```js
function getConfigurationByFile(file) {
  const pathToConfigFile = path.resolve("cypress/config", `${file}.json`);
  return fs.readJson(pathToConfigFile);
}

module.exports = (on, config) => {   
  on("task", {
    executeQuery({queryToBeExecuted, product}) {
      return new Promise((resolve, reject) => {
        const { Client } = require("pg");
        db1 = config.env.db[product];
        console.log("Product is " + product)
        console.log("queryToBeExecuted is " + queryToBeExecuted)
        const client = new Client({
          user: db1.user,
          host: db1.host,
          database: db1.database,
          password: db1.password,
          port: db1.port
        });
        client.connect();
        client.query(queryToBeExecuted, (err, res) => {
          console.log("Closing connection.....");
          console.log
          client.end();
          resolve(res);
        });
      });
    },
    parseXlsx({ filePath }) {
      return new Promise((resolve, reject) => {
        try {
          const jsonData = xlsx.parse(fs.readFileSync(filePath));
          resolve(jsonData);
        } catch (e) {
          reject(e);
        }
      });
    }
  });
  const file = config.env.configFile || "qa";
  return getConfigurationByFile(file);
};

```
This is how I am calling this task in one of my test files:
`cy.task('executeQuery', { queryToBeExecuted: "select * from XXXX where id = XXX", product: "uhcDB" }).then(function (queryResult) {console.log(queryResult)}`

Structure of cypress/config/qa.json:
```json
{
  "env": {
    "baseUrl": "https://example-site.com",
    "db": {
      "uhcDB" : {
        "user": "xxxx",
        "host": "xxxxxx",
        "database": "xxx",
        "password": "xxx",
        "port": xxxx,
      },
      "xyzDB" : {
       "user": "xxxx",
        "host": "xxxxxx",
        "database": "xxx",
        "password": "xxx",
        "port": xxxx,
      }
    }
  }
}
```

### Current behavior
I ran my script using "ENV=qa npm run test" and when the control reached cy.task('executeQuery') from within my test, I got this error "cy.task('executeQuery') failed with the following error: > Cannot read property 'uhcDB' of undefined"

![image](https://user-images.githubusercontent.com/39148324/103313480-2d1d6780-4a46-11eb-983a-38fc18c1faa9.png)

When I did a console.log(config) from within the task in /plugins.index.js, the env object was found to be empty {}
![image](https://user-images.githubusercontent.com/39148324/103312845-445b5580-4a44-11eb-96d3-7e911c0eed38.png)

After this, when I saved my plugins/index.js again without re-starting the Cypress runner, it seemed to work fine. This time the config object did return the necessary env object with appropriate keys. 

Seems like the first time I ran my tests either via Cypress run or open commands, it is unable to retrieve the environment variables in /config/qa.json. When I saved the index.js, it somehow loads those variables and everything starts working fine. 
Also, I tried copying the DB object and pasting it directly in cypress.json and it worked. But I need the DB creds to reside in my environment specific json file. 

### Desired behavior
I need my executeQuery task to get the database credentials that are stored in my cypress/config/qa.json config file, everytime I run my tests either using cypress open or cypress run (Without having to re-save the index.js).

### Versions
"cypress": {
"version": "5.6.0"}

Let me know in case you need any further information from me. Thanks in advance!

**Comment by bahmutov** [comment]
Can you determine if the config `env` block is really loaded or not? It should have those variables from the JSON file on the first open with `cypress open`.

Look at what `getConfigurationByFile` returns. Is it returning a promise? Can you print the resolved value? 

```js
function getConfigurationByFile(file) {
  const pathToConfigFile = path.resolve("cypress/config", `${file}.json`);
  return fs.readJson(pathToConfigFile);
}
```

Or even validate it better

```js
function getConfigurationByFile(file) {
  const pathToConfigFile = path.resolve("cypress/config", `${file}.json`);
  const config = require(pathToConfigFile);
  if (!config.env.db) {
     throw new Error(`Cannot find db in ${pathToConfigFile}`)
  }

  // just to debug this
  console.log('loaded config %o', config)

  return config;
}
```

**Comment by parul-adhikari** [comment]
> Can you determine if the config `env` block is really loaded or not? It should have those variables from the JSON file on the first open with `cypress open`.
> 
> Look at what `getConfigurationByFile` returns. Is it returning a promise? Can you print the resolved value?
> 
> ```js
> function getConfigurationByFile(file) {
>   const pathToConfigFile = path.resolve("cypress/config", `${file}.json`);
>   return fs.readJson(pathToConfigFile);
> }
> ```
> 
> Or even validate it better
> 
> ```js
> function getConfigurationByFile(file) {
>   const pathToConfigFile = path.resolve("cypress/config", `${file}.json`);
>   const config = require(pathToConfigFile);
>   if (!config.env.db) {
>      throw new Error(`Cannot find db in ${pathToConfigFile}`)
>   }
> 
>   // just to debug this
>   console.log('loaded config %o', config)
> 
>   return config;
> }
> ```

Hi @bahmutov, thanks for looking into it!

I added the code you shared in my plugings/index.js and it does log the entire qa.json config, including the env variables too. But somehow inside the executeQuery task, it is still unable to get config.env. It is '{}' still.
Note that: Neither of cypress.json or cypress.env.json have an env object in them. Its just my /config/xxx.json (qa.json in this case) file that does.

**Comment by katalie** [comment]
Hi @parul-adhikari ,

I got the same issue and wondering if it got resolved? Thanks

**Comment by quyenntn** [comment]
same issue here
