### ISSUE TITLE
Cypress 5.6.0 does not allow bearer authentication token to be loaded from url 

### ISSUE THREAD

**Issue by rocketsciencenerd** [cypress-io/cypress#14345]
### Current behavior

**Test Example**

```js
it('loads the webpage', function () {
    cy.visit('http://localhost:8000/?token=[MY_BEARER_TOKEN']')
    Cypress.on('fail', (err, runnable) => {return false});
    Cypress.config('defaultCommandTimeout', 6000);  
})
```

In Cypress 5.6.0 (bad)
Network Request:
  Request URL: MY_API_URL
  Status Code: 401 Unauthorized
  Authorization: _bearer null_

In Cypress 5.0.0 (good)
Network Request:
  Request URL: MY_API_URL
  Status Code: 200 Success
  Authorization: _bearer [MY_BEARER_TOKEN']_

### Desired behavior

**Steps to reproduce**
1. Run the above test to load the webpage with a valid [MY_BEARER_TOKEN] in the url
2. Any api calls that require [MY_BEARER_TOKEN] from within my app return an unauthorized error. This is  because the [MY_BEARER_TOKEN] from the url is null.
3. Webpage does not load because api calls are unauthorized (no token present)

**Expected**
Token should be passed from url and application should load.

**Notes**
This issue sounds like it could be an issue within my app; however, this same test is completely functional in cypress v5.0.0. Also, when loading the localhost url with the same token in a separate (non-cypress-controlled) chrome browser, the bearer token is passed to my api calls as expected and my webpage loads fine. 

### Test code to reproduce

(see above)

### Versions

Cypress version: 5.6.0.
Last working (and still functional) version: 5.0.0.

Browser chrome 87
OS MacOS Catalina 

Anyone else having this issue in cypress 5.6.0?

**Comment by rocketsciencenerd** [comment]
Also @eliarlington

**Comment by jennifer-shehane** [comment]
@rocketsciencenerd If you could pinpoint the version where this exactly broke, that would be helpful - as there are 5 releases between 5.0 and 5.6. So just install Cypress in earlier version and rerun the tests. 

How are you filling in the `MY_BEARER_TOKEN`, is it just a string written into the cy.visit()? You're not pulling in `Cypress.env` or anything to be read in there?

**Comment by eliarlington** [comment]
@jennifer-shehane I have tested versions 5.0 - 5.6. I did not hit the issue on versions 5.0 - 5.4. I did hit the issue on versions 5.5 and  5.6. Yes, it is just a string in cy.visit()! Cypress.env is not being used.

**Comment by rocketsciencenerd** [comment]
@jennifer-shehane thanks for the reply. @eliarlington and I have been working on this together. Right, our app gets that token only as a string in the url and then handles its own authentication and api requests on its own. So, it doesn't seem like we would need `Cypress.env` since we aren't relying on cypress to make the api calls by itself.
