### ISSUE TITLE
Test finished even though xhr request is in pending state

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#14349]
### Current behavior

Notice the `Status` column in web developer tool. It says the request we are looking for is `Pending` but Cypress test has already finished.

<img width="1680" alt="Untitled6" src="https://user-images.githubusercontent.com/2043287/103317816-36c0b400-49e1-11eb-911a-48e6783af5cc.png">

### Test code to reproduce

```js
let requests = []
cy.intercept({method: 'POST', url: "xyz.com/abc"}, (req) => {
        requests.push(JSON.parse(req.body));
        requests = requests.flat();
    }).as('alias1')
cy.visit(hostname);
    cy.log('print me 3')
    cy.wait('@alias1').then((interception) => {
        console.log(interception)
        console.log(requests);
    })
```

### Versions
Cypress: 6.2.0
Chrome: 87.0.4280.88 
Mac: 11.0.1

**Comment by jennifer-shehane** [comment]
Can you click on the `wait` command where it matched `alias1` and provide what that prints to the Developer Tools console? If there was ever any previous request matching, then it would resolve.

**Comment by quad5** [comment]
@jennifer-shehane  Here you go. Thanks. 

> it('reproducing', function() {
    cy.log('print me 1')
    cy.intercept({method: 'POST', url: '**/event'}, (req) => {
        console.log(req)
    }).as('alias1')
    cy.log('print me 2')
    cy.visit('https://www.yummly.com')
    cy.get('.qa-ready')
    cy.log('print me 3')
    cy.wait('@alias1').then((interception) => {
        console.log('in wait')
        console.log(interception)
    })
    cy.log('print me 4')
})

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/2043287/103327576-f4f83380-4a09-11eb-80ff-eb56e9ef124f.png">

**Comment by jennifer-shehane** [comment]
Hmm, I'm not seeing this exact behavior from the provided example. The matching requests show as Complete. Is there any other config/code I'm missing?

<img width="1415" alt="Screen Shot 2020-12-30 at 3 10 13 PM" src="https://user-images.githubusercontent.com/1271364/103339977-49a2b980-4ab1-11eb-92ae-6eee74d69ed1.png">

**Comment by quad5** [comment]
Sorry about that. It seems like i run into this state consistently when I use `class` implementation as given below. I was running into this state with the above  codes but it doesn't occur every time. 

I am attaching an image which seems like https://github.com/cypress-io/cypress/issues/9549. I was switching between production and staging url to reproduce this ticket issue. If you look at Cypress's error in developer tools section, url visited is different from the one I asked it too. Not sure what that means.

> const goToPageInstance = new homepage('https://www.yummly.com')
it('loads page', function() {
    goToPageInstance.load().then((result) => {
        console.log(result);
    })
})


> export class homepage {
    constructor(url) {
        this.url = url
    }    
    load() {
         let requests = [];
        console.log('in load')
        cy.intercept({method: 'POST', url: '**/event'}, (req) => {
            console.log(req)
        }).as('alias')
       cy.visit(this.url)
       cy.get('.qa-ready')
       return cy.wait('@alias').then((interception) => {
            requests.push(interception);
            return requests;
        })
   }
}

<img width="1680" alt="Untitled7" src="https://user-images.githubusercontent.com/2043287/103377375-1998ed80-4a94-11eb-95a5-fc2038cf5b4f.png">

**Comment by ModestasDaunys** [comment]
I have the same issue here. In my case, "/get-personal-info" is verified as received, but in devTools network tab it is still pending. Could network throttle have an influence here?

`cy.intercept('GET','**/get-personal-info').as('getPersonalInfo');

cy.visit(base_url + "accounts/sponsored-accounts");

 cy.wait('@getPersonalInfo').its('response.statusCode').should('eq', 200);`

![image](https://user-images.githubusercontent.com/45395460/103626655-30808980-4f45-11eb-9d2c-7aa9ef7e1321.png)

**Comment by quad5** [comment]
@jennifer-shehane Please try the following codes to reproduce original issue. Thanks.

> it.only('reproduce', function() {
    test().then((result) => {
        console.log(result)
    })
})
function test() {
    let alias = 'alias1'
    let obj = []
    intercept(obj, {method: 'POST', url: '**/event'}, alias)
    cy.visit('https://www.yummly.com')
    cy.get('.qa-ready')
    cy.log('print me 3')
    console.log(obj.length)
    return wait(obj, alias)
}
let intercept = (obj, routeMatcher, alias) => {
    cy.intercept(routeMatcher, (req) => {
        obj.push(JSON.parse(req.body));
    }).as(alias)
}
let wait = (obj, alias) => {
    return cy.wait(`@${alias}`).then((interception) => {
        return obj
    })
}

**Comment by jennifer-shehane** [comment]
@quad5 This example throws another error that looks unrelated to your original request.

<img width="620" alt="Screen Shot 2021-02-27 at 9 25 19 AM" src="https://user-images.githubusercontent.com/1271364/109390147-d4e7d200-78dd-11eb-8687-db77762642f3.png">

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
