### ISSUE TITLE
How to split the commands.js file when there are many custom commands?

### ISSUE THREAD

**Issue by tcw0nw** [cypress-io/cypress#14355]
How to split the commands.js file when there are many custom commands？？
I checked a lot of information, but I didn’t find a way to split the commands.js file。

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
