### ISSUE TITLE
Part of url path is missing while running test in cypress test runner 

### ISSUE THREAD

**Issue by scrumvisualize** [cypress-io/cypress#14365]
### Current behaviour
Url path missing while running the test in cypress test runner, as a result getting `404` error page.

Actual URL displaying in test runner while running the test:
`https://sometest.qa.somecloud.com/_/studentsOnline.php?mainTabsItem=connection`

### Desired behaviour
Expected URL where it displays the whole data :
`https://sometest.qa.somecloud.com/student/studentsOnline.php?mainTabsItem=connection`

### Test code to reproduce

On click on some button system will display a confirmation message. Once we have clicked on the confirmation button, below set of process will get initiated, as ie I could see from chrome network tab. After 15 seconds system should automatically navigated to  `Connection` tab where it displays the whole data under some tab.  But while running the test, after 15 seconds the test runner displays `404` error page with the url `https://sometest.qa.somecloud.com/_/studentsOnline.php?mainTabsItem=connection`
I assume some part of the url is getting missing while navigation occurs. The expected url as given below: 
`https://sometest.qa.somecloud.com/student/studentsOnline.php?mainTabsItem=connection`

```
startingProcess.php   POST
showProgress.php?processingName=studentsOnline&companyID=54   GET
studentsaccountLinkPost.php   POST
showProgress.php?processingName=studentsOnline&companyID=54   GET
showProgress.php?processingName=studentsOnline&companyID=54   GET
```

**Note:**
I am running my test from my `Git bash` as follows:

 `$ CYPRESS_baseUrl=https://sometest.qa.somecloud.com/student/ npx cypress open`

### Versions
Cypress version 6.2.0
Windows 10 64 bit

**Comment by jennifer-shehane** [comment]
Can you try setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by scrumvisualize** [comment]
Awesome! @jennifer-shehane that worked really well in my case ! Thank you very much ! Could you also please provide more details on how does the `experimentalSourceRewriting: true` helped in resolving the url problem !

**Comment by jennifer-shehane** [comment]
@scrumvisualize Sometimes code within an application expects the code to never run within an iframe, so it will call things like x.top, x.parent, x.frames which makes the code change the main Cypress window instead of the window within the application under test. So we change some of that code on the fly when that experimental flag is set to ensure the application under test renders as expected. It's a bit more complicated than that but all of the code can be found here: https://github.com/cypress-io/cypress/pull/5273
