### ISSUE TITLE
describe.only still runs ALL spec files

### ISSUE THREAD

**Issue by ZodsPlan** [cypress-io/cypress#14366]
### Current behavior

Adding "describe.only" or "it.only" still runs *ALL* tests when running by cli via `yarn run cypress run`.

### Desired behavior

When there are multiple spec files, and only one file has its suite specified with describe.only, all the tests are still run.

When changing "describe" to "describe.only," ONLY that test is supposed to run.

### Test code to reproduce

1. Add more than one spec file in your cypress/integration directory.
2. In one of the spec files, change the "describe" to "describe.only"

```js
describe.only('Cypress, function () {
    it('should only run this pending test');
});
```

### Versions
`npx cypress -v`

Cypress package version: 6.2.0
Cypress binary version: 6.2.0
Electron version: 11.0.3
Bundled Node version: 12.18.3

My laptop is running node v12.9.0
*Computer info:*
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H114

**Comment by bahmutov** [comment]
This is the expected behavior: every spec runs by itself as if you execute:

```
cypress run --spec cypress/integration/spec-a.js
cypress run --spec cypress/integration/spec-b.js
cypress run --spec cypress/integration/spec-c.js
```

Thus the `describe.only` or `it.only` in spec-a.js only affects that file.

**Comment by archangel-irk** [comment]
Maybe worth to add it to the documentation.
