### ISSUE TITLE
Cypress cannot fetch the supportFile with Cypress run (CLI) however it works with Cypress Open

### ISSUE THREAD

**Issue by panraj01** [cypress-io/cypress#14360]
Cypress run cannot fetch the support file however it works as expected with Cypress Open (when I run in Watch mode for development). I can see when the test executes with Cypress open, it get the supportfile with response 200 on the console but when i run an e2e test with CLI (headless/headed), it takes a long long time and then fails with "Fetching resource at '/__cypress/tests?p=src\support\index.ts' failed"

`tsconfig.e2e.json`
```json
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "sourceMap": false,
        "outDir": "../dist/out-tsc",
        "allowJs": true
    },
    "include": [
        " **/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx"
    ]
}
```
`tsconfig.json`
```json
{
    "extends": "../tsconfig.base.json",
    "ts-node": {
        "transpileOnly": true
    },
    "compilerOptions": {
        "types": [
            "cypress",
            "node",
            "cypress-wait-until"
        ],
        "outDir": "./dist/",
        "noImplicitAny": false,
        "module": "commonJs",
        "allowSyntheticDefaultImports": true,
        "target": "es6",
        "jsx": "react",
        "allowJs": true,
        "lib": [
            "es2017",
            "DOM"
        ]
    },
    "include": [
        "**/*.ts"
    ],
    "files": [],
    "references": [
        {
            "path": "./tsconfig.e2e.json"
        }
    ]
}
```

### Current behavior
Cypress OPEN can fetch the supportFile but Cypress RUN cannot.

### Desired behavior
Cypress RUN should be able to get to the supportFile. Why is there a difference in fetching the file in Cypress RUN Vs OPEN.

### Test code to reproduce
I use Cypress plugin for NX with Typescript and Cucumber. Its pretty complex to create a stand along test code to provide to you guys. But what's puzzling me is why Cypress OPEN gets to the support file but not Cypress RUN.

![image](https://user-images.githubusercontent.com/42047303/103369792-acd02400-4a90-11eb-8532-9cd15c64f262.png)

### Versions

I am yet to upgrade to Cypress 6.x which i will do shortly but as of now i am using 5.1.0.

**Comment by Elif5757** [comment]
i have the same issue @panraj01 @jennifer-shehane

**Comment by vtereshyn** [comment]
I have a similar issue - https://github.com/cypress-io/cypress/issues/14796

**Comment by Elif5757** [comment]
@vsavkin can you help us ?

**Comment by Elif5757** [comment]
@panraj01 
follow the instruction here and it will work. it worked for me! https://stackoverflow.com/questions/58374064/use-feature-files-in-cypress-with-nrwl-nx

**Comment by bahmutov** [comment]
closing as external issue

**Comment by olliiiver** [comment]
#509
