### ISSUE TITLE
Selecting the main window hides the developer tools menu item

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/cypress#14372]
### Current behavior
This bug : https://github.com/cypress-io/cypress/issues/3559

is happening in 6.2.0

I’m not sure if it has regressed or it was never fixed.

1. Open cypress
2. Open a spec
3. Click the main window
4. Developer tools menu disappears from the spec window

am Reproducing on windows.

### Versions

6.2.0
Windows 10

**Comment by lukeapage** [comment]
When I try this on master on the cypress repo - it doesn't happen.. not sure if it is because of https://github.com/cypress-io/cypress/pull/14352

**Comment by jennifer-shehane** [comment]
😞 I wonder if running it locally works because we have Developer Tools available within the Cypress window as well as Electron - which is not the case in a production release.
