### ISSUE TITLE
Issue after SSO Authentication

### ISSUE THREAD

**Issue by SangeetAgarwal** [cypress-io/cypress#14379]
I'm just starting to write a simple test case to visit an internal application. The URL redirects to SSO login properly and logs me into the application's home page.

```js
describe("my first test", function () {
  it("visit local host", function () {
    cy.visit("http://localhost:3000/login");
    // cy.visit('http://localhost:3000/listusers');
  });
});
```

But, if I now have it as 
```js
describe("my first test", function () {
  it("visit local host", function () {
    cy.visit("http://localhost:3000/login");
    cy.visit('http://localhost:3000/listusers');
  });
});
```
then I get 
![image](https://user-images.githubusercontent.com/2169707/103482581-a3f09280-4daf-11eb-9ebd-e3f8fcc8cc65.png)

So, I am able to successfully login but any route I then attempt to access causes the Sso login process to be cancelled. 

**Desired behavior:**
Proceed after SSO properly authenticates

Any help is highly appreciated.

Thank You

**Comment by jennifer-shehane** [comment]
The second visit will trigger immediately after the `load` event has fired when visiting the `login` page, so any requests that are in flight at that time will be cancelled and will immediately move on to the next visit command. 

If you want to visit a new page after the login has been successful, you'll need to assert that the proper state is present before going to the next page. 

```js
describe("my first test", function () {
  it("visit local host", function () {
    cy.visit("http://localhost:3000/login");
    
    // maybe the url has changed after login, so we can make sure of that first
    cy.url().should('include', 'dashboard')

    // maybe there's something on the page that displays after successful login
    cy.get('.profile').contains('Jennifer')

    // after we're sure the entire login process was successful, now visit another page
    cy.visit('http://localhost:3000/listusers');
  });
});
```

If there is some other issue present outside of this that indicates a bug, please provide more information that we can investigate. 

If you have questions on how to use Cypress try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.

**Comment by SangeetAgarwal** [comment]
@jennifer-shehane  Thank you, that approach worked perfectly.
