### ISSUE TITLE
Cypress errored trying to serve this file from your server?

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1438]
Hi,

I installed Cypress on windows 10 (64 bits) and a webapp locally. I started my web server and stopped the access to the web.

When I run `localhost:8000/index.html`, I get my webapp in chrome.

When I run the same path in Cypress browser, I get `Cypress errored trying to serve this file from your server`

Did you have any idea about this problem?
Thanks :-)

Operating System: Win10 64 bits
Cypress Version: 2.1.0
Browser Version: Electron 59

**Comment by jennifer-shehane** [comment]
Yes this is a bug dealing with the corporate proxy. You can track the issue here: https://github.com/cypress-io/cypress/issues/1469

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
