### ISSUE TITLE
cy.intercept() glob matching issue still appears

### ISSUE THREAD

**Issue by sakuranasty** [cypress-io/cypress#14380]
### Current behavior
I concatenate base URL with path and use it in URL param in routeMatcher
These are routes that are matched incorrectly (I skip  base URL in the examples)
For some reason it gets matched to caseListLoaded alias and the to caseCreated alias
![image](https://user-images.githubusercontent.com/34821835/103493653-a7cdf480-4e43-11eb-8a75-3ae8626c87a1.png)
This one has the same globe as previous, but should be actually /api/cases/someId, glob api/cases/* doesn't match the URL at all
![image](https://user-images.githubusercontent.com/34821835/103493717-f7acbb80-4e43-11eb-95b2-ac5de9e2cd81.png)
This one has globe `api/cases/**/dependent-cases`
![image](https://user-images.githubusercontent.com/34821835/103493742-1a3ed480-4e44-11eb-962d-389b66d76a16.png)

### Desired behavior
These routes worked as expected in cypress 4.12

### Test code to reproduce
this is wrapped to function that receives this props as params
```js
cy.intercept({
    url: `http://localhost:9001/api/cases/**/dependent-cases`,
    method: 'GET',
    matchUrlAgainstPath: false
  },
  (req) => {
    req.reply(res => {
      onRes(res);
    });
  }
  ).as('dependentCasesLoaded');
```

### Versions

 Cypress version 6.2.0

**Comment by jennifer-shehane** [comment]
If you have an intercept defined before the `dependent-cases` intercept that matches both urls, the it will always match the first define intercept. If you don't want the `api/cases` matcher to also match `api/cases/**/dependent-cases` then you'll need to make that matcher more specific, like `/https:\/\/example.com\/api\/cases$/`

We're working on fine tuning the 'overriding' of interceptors in this issue, so this may be relevant to how you'd like it to behave. https://github.com/cypress-io/cypress/issues/9302

In the meantime if you don't want to use this suggestion, I'd suggest continuing to use cy.route() for now.


```js
it('test cy.intercept()', () => {
  cy.intercept({
    url: `https://example.com/api/cases`,
    method: 'GET',
    matchUrlAgainstPath: false
  }).as('caseListLoaded')

  cy.intercept({
    url: `https://example.com/api/cases/**/dependent-cases`,
    method: 'GET',
    matchUrlAgainstPath: false
  },
    (req) => {
      req.reply(res => {
      });
    }).as('dependentCasesLoaded')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', 'api/cases/5ff26ad609d4e05600b167ec/dependent-cases')
    xhr.send()
  })
  cy.wait('@dependentCasesLoaded').then(({ request, response }) => {

  })
})
```

<img width="828" alt="Screen Shot 2021-01-04 at 8 21 07 AM" src="https://user-images.githubusercontent.com/1271364/103494557-d230a980-4e65-11eb-80e9-cb17c0775b1b.png">

**Comment by sakuranasty** [comment]
Thanks for your suggestion, I'll try with Regexp for URl, 
but can you please explain why ```api/cases``` matches ```api/cases/**/dependent-cases```?
