### ISSUE TITLE
Visit vue project bundle get 404 in Chrome opened by cypress, but 200 in Chrome opened by desktop shortcut

### ISSUE THREAD

**Issue by lucyluxiliu** [cypress-io/cypress#14389]
My project is written with vue&nuxt, and is runned by ```yarn dev```.

cypress.json
```
{
  "baseUrl": "http://10.25.80.86:3000"
}
```

![image](https://user-images.githubusercontent.com/48850688/103534051-215bf600-4ec9-11eb-8336-3d18466b14e9.png)
The directory cypress is produced by script. I only add the ```campaignSearch.spec.js``` file. 
![image](https://user-images.githubusercontent.com/48850688/103534092-30db3f00-4ec9-11eb-9db8-47e7da57cd8e.png)

When I run the test, sometimes I get 404, sometimes I can see the page but some files (for example, the bundles webpack produced) is 404. When I open the 404 file in Chrome which cypress opened, sometimes it still 404, sometimes it can be returned with 200. But I copy the url of 404 file and open it in Chrome which is opened from desktop shortcut, it always 200. I'm confused.
![image](https://user-images.githubusercontent.com/48850688/103534401-c24ab100-4ec9-11eb-9cc6-204b85717cc2.png)
![image](https://user-images.githubusercontent.com/48850688/103534449-d7274480-4ec9-11eb-833d-4163f1cbde5e.png)
![image](https://user-images.githubusercontent.com/48850688/103534484-e73f2400-4ec9-11eb-8173-3005f4510535.png)
![image](https://user-images.githubusercontent.com/48850688/103534514-f7570380-4ec9-11eb-9bdf-49f39d24b1fc.png)

cypress version is 6.2.0

Why are the files 404 and sometimes is the page 404 too? Are there some strategies that limit the visit?

**Comment by bahmutov** [comment]
Can you please create a small repo with a reproducible example? Otherwise, we have no idea what the problem might be.

**Comment by lucyluxiliu** [comment]
@bahmutov sorry for the slow apply.

There is the demo: https://github.com/lucyluxiliu/nuxt-vue-cypress-demo

After running ```yarn dev``` and opening the browser, I can get the page with a boy shown.
![image](https://user-images.githubusercontent.com/48850688/103861489-76318380-50f8-11eb-9b28-574962a11661.png)

But when I open cypress, the image request is responsed with 404.
![image](https://user-images.githubusercontent.com/48850688/103861535-919c8e80-50f8-11eb-940f-a5ec5c45f5d6.png)

The image url is http://img.yao51.com/jiankangtuku/phsnnwqpsy.jpeg

Chrome(version 87.0.4280.88, windows 64bits) and Firefox(version 83.0) have the same problem.

**Comment by lucyanonymous** [comment]
您的邮件我已经收到啦，我会尽快回复哒~lucy~

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
