### ISSUE TITLE
Cypress cy.visit() not passing auth headers with redirect

### ISSUE THREAD

**Issue by Jak-Tan** [cypress-io/cypress#14396]
### Current behavior

I noticed that my tests started breaking recently because of a 401 error with tests that are hitting a url that is being redirected. In my code I pass the basic auth headers as an object via a cy.visit() command. I feel like this used to pass the auth headers on when it redirected to url2 however now all my tests are breaking. 

![image](https://user-images.githubusercontent.com/63995898/103595316-fb356500-4f5f-11eb-8e2b-29ae555183ff.png)

 
### Desired behavior

Pass basic auth headers when url1 is redirected to url2, or have some method to set headers after being redirected.

### Test code to reproduce
`cy.visit('/url1', {
      auth: {
        username: 'username1',
        password: 'password1',
      }
    });`

where url1 get's redirected to url2

### Versions
Version 6.2

**Comment by smit9234** [comment]
I am running into the same issue.  I tried with version 5.5.0 and it is working fine.  Looks like something is broken between the different versions.

**Comment by smit9234** [comment]
@Jak-Tan try putting the entire url path in cy.visit().  It looks like the baseUrl env variable doesn't seem to be working with the visit call.  I put the entire url path in the visit and it authenticated.

**Comment by Jak-Tan** [comment]
@smit9234 it's not the baseUrl that is the issue for me, I'm intentionally hitting url1 which redirects to url2 as I don't know url2 at runtime. After getting redirected to url2 I'm losing the auth headers

**Comment by smit9234** [comment]
@Jak-Tan makes sense, I was going off the info in the screenshot.

**Comment by devhid** [comment]
I'm experiencing the same thing on v.9.5.0.

I click on a button on `example-url.com:<port1>` which redirects me to `example-url.com:<port2>`, but the authorization headers are not being passed (because of the different origin).
* I can't visit `example-url.com:<port2>` separately because it relies on data that's passed in from entering information `example-url.com:<port2>`.

I even tried intercepting the redirect request and insert the authorization headers manually, but the Basic Auth modal still popped up.

I saw this ticket, https://github.com/cypress-io/cypress/pull/20467, but it's unclear if this would also handle passing authorization headers on redirect to a different origin.

Any clarity here would be helpful. Thank you.

**Comment by aniskevichZhenia** [comment]
If someone is still struggling with this problem, I hope my solution will be useful to you.
This solution is based on [cy.intercept()](https://docs.cypress.io/api/commands/intercept)
```
cy.intercept(link, (req) => {
  req.continue((res) => {
    if (res.statusCode === 302) {
      let redirectionLink = res.headers.location;
      // Stub response to not follow redirect.
      res.send(200, 'fake response' , {'redirectionLink': redirectionLink});
    }
  })
}).as('redirectionLinkVisit');

// If the link has a redirect, the response will be stubbed.
cy.visit(link);

cy.wait('@redirectionLinkVisit').then((interception) => {
  if (interception.response.headers['redirectionLink']) {
    userData.redirectionLink = interception.response.headers['redirectionLink'];
    cy.task('saveData', userData);
  }
});

cy.task('loadData').then((userData) => {
  if (userData.redirectionLink) {
    // This will only happen if the link contains a redirect and the response was stubbed
    // otherwise, the original cy.visit(link) response is what we expect.
    cy.visit(userData.redirectionLink, {
      auth: {
        username: 'name',
        password: 'pass',
      },
    });
  }
});
```
