### ISSUE TITLE
cy.intercept doesn't catch request

### ISSUE THREAD

**Issue by Jacek-fstack** [cypress-io/cypress#14404]
Keep in mind the code is working just fine if I have route instead of intercept command. 
```js
 finishUserCreationAndSave() {
        cy.log('before intercept');
        cy.intercept('PUT', '/api/v1/organizations/current/members/**').as('membersPut');
        cy.log('after intercept');
        cy.contains('Save Changes').click();
        cy.wait('@membersPut');
    }
```
<img width="815" alt="Screen Shot 2021-01-05 at 12 41 03 PM" src="https://user-images.githubusercontent.com/29603168/103642388-557bf900-4f53-11eb-9181-c3f8a570d8b3.png">

Any idea why it would not catch the request? 
Seems like a bug.
Again, identical setup with cy.route() is working just fine.

### Versions
6.1.0

EDIT:
Okay, I found the solution, for some reason I need to remove the ** which was previously any string
```js
        cy.intercept('PUT', '/api/v1/organizations/current/members/').as('membersPut');
```
Does it mean it all now works like that? If I don't provide https:// it will always treat it as a substring?

**Comment by thaianalps** [comment]
same problem herer

**Comment by jennifer-shehane** [comment]
Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. We fixed an issue with glob paths in 6.2.0 with cy.intercept(). Your issue may have already been fixed. Thanks!

**Comment by Jacek-fstack** [comment]
yep, I THINK that fixes it

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by ArestrepoBlankfactor** [comment]
I have the same issue 
![image](https://user-images.githubusercontent.com/97688893/157953370-51c829bd-6f76-4028-bbc7-91b3cf899d47.png)

the post request finished but the intercept doesn't catch the request
