### ISSUE TITLE
Dashboard crashes when trying to invite user to organisation

### ISSUE THREAD

**Issue by dcastil** [cypress-io/cypress#1441]
- Operating System: Mac OS 10.13.3
- Cypress Version: 2.1.0
- Browser Version: Safari 11.0.3 and Chrome 65.0.3325.146

### Is this a Feature or Bug?
Bug

### Current behavior:
When I'm in the user section of the cypress dashboard of my organisation (https://dashboard.cypress.io/#/organizations/[…]/users) and click on "Invite User", the screen goes white and the website doesn't respond to anything until I reload.

### Desired behavior:
Being able to add users to my organisation

### How to reproduce:
Same behaviour in Safari and Chrome and on different computers. I didn't try it with another account though.

<!-- #### Test code:

```js

``` -->

### Additional Info (images, stack traces, etc)
before click
![screen shot 2018-03-12 at 10 34 08](https://user-images.githubusercontent.com/31006608/37276160-496be326-25e1-11e8-962a-4b837610119f.png)
after click
![screen shot 2018-03-12 at 10 34 21](https://user-images.githubusercontent.com/31006608/37276174-4fe4990a-25e1-11e8-9c38-60ce3adb1010.png)

**Comment by bahmutov** [comment]
Hmm, I do not see crash reports that look related to this - but what is very suspicious here from the screenshot you have provided (thank you for that), is that there is no email for your account! Can I ask how you got to this state?

**Comment by jennifer-shehane** [comment]
This is a bug in the Dashboard. Working on it now.

**Comment by dcastil** [comment]
@bahmutov I've just put a white bar over the e-mail-address to not make it public. Should have taken a black one to make the edit unequivocal.

**Comment by jennifer-shehane** [comment]
@dcastil Haha, I was so confused by the lack of email too. 

This should be fixed. I also wrote a test to ensure coverage of this situation. Sorry!

**Comment by dcastil** [comment]
That's what beta is for. 😊 Thank you for the quick fix!
