### ISSUE TITLE
Cant selects element with only specific class, avoid the rest of them 

### ISSUE THREAD

**Issue by LuyTester** [cypress-io/cypress#14410]
### Current behavior
Currently, I have a calendar, all days had class ".day" but only de old once, have class ".day.old.disabled" 
When I try to click on the cy.get(.day).contains("8").click() it clicks in the "28" that has class ".day.old.disabled" and that is not exclusive 8 it is a 28. I understand that when you what to add a class with more classes you can use * but not know if this is an issue or I'm missing something.- 
![Screenshot 2021-01-05 at 14 56 46](https://user-images.githubusercontent.com/52031937/103654629-6d10ad00-4f66-11eb-8110-38bd15d56d08.png)
BUG: if I'm not saying that element has more classes should look for the first element only class .day that contents 8. Not from all elements that contain class .day*? 

### Desired behavior
should look for the first element only class .day that contents 8. Not from all elements that contain class .day*+ other classes? 

### Test code to reproduce
Command: 
         Cypress.Commands.add(
            "selectMoveOut",(stayDays) => {
                var inDay = new Date();
                var outDay = new Date(inDay);
                    outDay.setDate(inDay.getDate() + stayDays);
                var outdd = String(outDay.getDate()).padStart(1,0);

        cy.get("td.day").contains(outdd).click()
  });

test: 
          Today is 5, I want to book for 3 days and select day 8 move out. 
                it(" completes booking successfully", () => {
                cy.visit("https://hotel-santorini.amenitiz-test.io/en");
                cy.get('#info_departure_date').click().then(() => {
                      cy.selectMoveOut(nights);
                    });
               cy.get("#site-date-selector__button").click(); 
              })

should select 
  

### Versions
Cypress package version: 6.1.0
Cypress binary version: 6.1.0
Electron version: 11.0.2
Bundled Node version: 12.18.3
![Screenshot 2021-01-05 at 14 56 46](https://user-images.githubusercontent.com/52031937/103656141-874b8a80-4f68-11eb-8613-5158fb14ce92.png)

**Comment by sergeyblohin** [comment]
@LuyTester, you can try change selector from `div.day` to `div[class="day"]`.

```html
<body style="background-color: white; font-size: 42px;">
    <div class="day old">28</div>
    <div class="day">8</div>
</body>
```

```javascript
// spec.js
/// <reference types="cypress" />

describe('Calendar', () => {
  it('day', () => {
    cy
      .visit('./calendar.html')

    cy
      .contains('div[class="day"]', '8')
      .should('have.text', '8')
  });
});
```

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/61824066/103660792-12d01600-4f7f-11eb-9ef6-fd9050274832.png">

**Comment by bahmutov** [comment]
@sergeyblohin is correct - you should look at `class` as just an attribute in this case and use the attribute selector `[class="day"]`. Using `contains` with text is also great. You can even use a regular expression to make sure you are selecting just `8` and not `28` with `cy.contains('[class=day]', /^8$/)`

See the full test example in https://glebbahmutov.com/cypress-examples/6.2.1/recipes/find-by-class.html

@sergeyblohin you might be interested in cypress-examples site where I code these little recipes and tests. They are markdown files that contains HTML and test JS and run straight using Cypress. Thus they are tested and deployed automatically (and are indexed for search there). To answer this question I have created https://github.com/bahmutov/cypress-examples/blob/master/docs/recipes/find-by-class.md and now never have to touch it again
