### ISSUE TITLE
Open-ssh-tunnel plugin fails to connect after upgrading to Cypress 6

### ISSUE THREAD

**Issue by bemanuel-trove** [cypress-io/cypress#14419]
I don't think I'll be able to provide a reproducible example as it deals with opening an ssh tunnel to a specific host, but I was able to set up the connection via a plugin task, where I am opening the tunnel via ['open-ssh-tunnel'](https://github.com/parro-it/open-ssh-tunnel) and then making a query to a Postgres database via Sequelize. 

Everything was running smooth on Cypress 5.6, but after I upgraded to 6.0 (have tried all of the latest versions after as well), the tunnel doesn't seem to want to connect and just hangs. Not sure what in the change log could possibly affect this.

Code:
```js
const tunnelConnection = {
    username: username,
    host: host,
    srcPort: 22,
    srcAddr: '127.0.0.1',
    privateKey: require('fs').readFileSync(privateKey),
    passphrase: 'passphrase',
    dstAddr: 'address',
    dstPort: 5432,
    localPort: 5444,
    localAddr: '127.0.0.1',
    forwardTimeout: 5000,
  };

dbQuery: async (query) => {
      if (cyConfig.environment !== 'local') {
        var tnl = await openSshTunnel(tunnelConnection);
      };
      const data = await dbConnection.query(query, { type: QueryTypes.SELECT });
      if (tnl) {
        await tnl.close();
      };
      return data;
    },
```
`var tnl = await openSshTunnel(tunnelConnection);` is where Cypress now hangs. Running the code locally where a tunnel isn't required also works fine.

**Comment by jennifer-shehane** [comment]
I'm not sure why this would hang specifically in 6.0. 

Are you running in Electron (the default browser)? Does this work in other browsers, like Chrome? or older versions of Chrome?

**Comment by bemanuel-trove** [comment]
@jennifer-shehane I get the same result whether running in Chrome (87) or Electron (browser or headless). Cypress says the plugin crashed and threw the following error: `Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed`, but I haven't been able to find anything helpful on that besides it being a node error. My locally installed node version is 12.6.

**Comment by bemanuel-trove** [comment]
Ok, ran with the debugger on to compare what each version of Cypress is doing.
5.6:
```
cypress:server:socket backend:request { eventName: 'task', args: [ { task: 'dbQuery', arg: "query", timeout: 60000 } ] } +14ms
  cypress:server:task run task dbQuery with arg query +3s
  cypress:server:plugins plugin event registered? { event: 'task', isRegistered: true } +1s
  cypress:server:plugins execute plugin event 'task' Node 'v12.16.3' with args: 'dbQuery' "query" undefined +0ms
  cypress:server:plugins call event task for invocation id inv11 +0ms
  cypress:server:plugins:child execute plugin event: task ({ eventId: 3, invocationId: 'inv11' }) +1s
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 60666 } +3s
Executing (default): query
  cypress:server:plugins promise resolved for id 'inv11' with value [ { id: id, uuid: 'uuid' } ] +3s
  cypress:server:task result is: [ { id: id, uuid: 'uuid' } ] +2s
```
6.2.1:
```
cypress:server:socket backend:request { eventName: 'task', args: [ { task: 'dbQuery', arg: "query", timeout: 60000 } ] } +28ms
  cypress:server:task run task dbQuery with arg query +0ms
  cypress:server:plugins plugin event registered? { event: 'task', isRegistered: true } +4s
  cypress:server:plugins execute plugin event 'task' Node 'v12.18.3' with args: 'dbQuery' "query" undefined +0ms
  cypress:server:plugins call event task for invocation id inv4 +0ms
  cypress:server:plugins:child execute plugin event: task ({ eventId: 3, invocationId: 'inv4' }) +4s
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 60713 } +6s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
```
So for some reason it looks like Cypress v6 or later doesn't 'execute' the task as it does in 5.6, and ends up jumping to the process_profiler and get:project:status event instead. 

Stack trace:
cypress:server:project got plugins error Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`../cypress/plugins/index.js`)
    at Object.get (../Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:961:15)
    at ChildProcess.handleError (../Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:159:20)
    at ChildProcess.emit (events.js:315:20)
    at internal/child_process.js:683:35
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by bemanuel-trove** [comment]
@jennifer-shehane It ended up being the node upgrade...set my config file to use system node and everything worked on 12.16.3.

**Comment by vasu4060** [comment]
> I don't think I'll be able to provide a reproducible example as it deals with opening an ssh tunnel to a specific host, but I was able to set up the connection via a plugin task, where I am opening the tunnel via ['open-ssh-tunnel'](https://github.com/parro-it/open-ssh-tunnel) and then making a query to a Postgres database via Sequelize.
> 
> Everything was running smooth on Cypress 5.6, but after I upgraded to 6.0 (have tried all of the latest versions after as well), the tunnel doesn't seem to want to connect and just hangs. Not sure what in the change log could possibly affect this.
> 
> Code:
> 
> ```js
> const tunnelConnection = {
>     username: username,
>     host: host,
>     srcPort: 22,
>     srcAddr: '127.0.0.1',
>     privateKey: require('fs').readFileSync(privateKey),
>     passphrase: 'passphrase',
>     dstAddr: 'address',
>     dstPort: 5432,
>     localPort: 5444,
>     localAddr: '127.0.0.1',
>     forwardTimeout: 5000,
>   };
> 
> dbQuery: async (query) => {
>       if (cyConfig.environment !== 'local') {
>         var tnl = await openSshTunnel(tunnelConnection);
>       };
>       const data = await dbConnection.query(query, { type: QueryTypes.SELECT });
>       if (tnl) {
>         await tnl.close();
>       };
>       return data;
>     },
> ```
> 
> `var tnl = await openSshTunnel(tunnelConnection);` is where Cypress now hangs. Running the code locally where a tunnel isn't required also works fine.

While working to implement Postgresql , i getting this error
process.binding is not supported

any ideas how to resolve this
