### ISSUE TITLE
'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Muhammadehsan2019** [cypress-io/cypress#14416]
I did lots of research and used different ways to delete the reports, but I couldn't get any results.  when I  try  to run the delete-mochawesome-report I get the below error, and I get the same error for all the delete (rm) commands.

C:\bit9prog\dev\cypress\ATMS> npm run delete-mochawesome-report
> atms_automated_tests@1.0.0 delete-mochawesome-report C:\bit9prog\dev\cypress\ATMS
> rm -rf mochawesome-report/* || true
'rm' is not recognized as an internal or external command,
operable program or batch file.

**'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! atms_automated_tests@1.0.0 delete-mochawesome-report: `rm -rf mochawesome-report/* || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atms_automated_tests@1.0.0 delete-mochawesome-report script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\muhammad.zuhoor1\AppData\Roaming\npm-cache\_logs\2020-12-23T22_38_16_051Z-debug.log
=====================================================

debug log:
 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'delete-mochawesome-report'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose run-script [
4 verbose run-script   'predelete-mochawesome-report',
4 verbose run-script   'delete-mochawesome-report',
4 verbose run-script   'postdelete-mochawesome-report'
4 verbose run-script ]
5 info lifecycle atms_automated_tests@1.0.0~predelete-mochawesome-report: atms_automated_tests@1.0.0
6 info lifecycle atms_automated_tests@1.0.0~delete-mochawesome-report: atms_automated_tests@1.0.0
7 verbose lifecycle atms_automated_tests@1.0.0~delete-mochawesome-report: unsafe-perm in lifecycle true
8 verbose lifecycle atms_automated_tests@1.0.0~delete-mochawesome-report: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\bit9prog\dev\cypress\ATMS\node_modules\.bin;C:\Program Files\Java\jdk-13.0.1\bin;C:\Program Files\Java\jdk-13.0.1\bin\server C:\Program Files (x86)\Common Files\Oracle\Java\javapath;;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\CCM;C:\Program Files (x86)\Common Files\Hitachi ID\;C:\Program Files\Common Files\Hitachi ID\;C:\Program Files (x86)\Hyland\Alt ActiveX\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\muhammad.zuhoor1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk-13.0.1\bin;C:\Program Files\Java\jdk-13.0.1\bin\server;C:\bit9prog\dev\gradle-6.0.1\bin;C:\Program Files\7-Zip;C:\Users\muhammad.zuhoor1\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\muhammad.zuhoor1\AppData\Roaming\npm
9 verbose lifecycle atms_automated_tests@1.0.0~delete-mochawesome-report: CWD: C:\bit9prog\dev\cypress\ATMS
10 silly lifecycle atms_automated_tests@1.0.0~delete-mochawesome-report: Args: [ '/d /s /c', 'rm -f mochawesome-report/* || true' ]
11 silly lifecycle atms_automated_tests@1.0.0~delete-mochawesome-report: Returned: code: 1  signal: null
12 info lifecycle atms_automated_tests@1.0.0~delete-mochawesome-report: Failed to exec delete-mochawesome-report script
13 verbose stack Error: atms_automated_tests@1.0.0 delete-mochawesome-report: `rm -f mochawesome-report/* || true`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid atms_automated_tests@1.0.0
15 verbose cwd C:\bit9prog\dev\cypress\ATMS
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "delete-mochawesome-report"
18 verbose node v14.15.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error atms_automated_tests@1.0.0 delete-mochawesome-report: `rm -f mochawesome-report/* || true`
22 error Exit status 1
23 error Failed at the atms_automated_tests@1.0.0 delete-mochawesome-report script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]**
============================================
package.json

{
  "name": "atms_automated_tests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node_modules\\.bin\\cypress run",
    "triggerAllTests-headless": "npx cypress run",
    "triggerAllTests-headed": "npx cypress run --headed",
    "triggerAllTests-chrome": "npx cypress run --browser chrome",
    "triggerAllTests-dashboard": "npx cypress run --record --key 430a1d71-2cbf-4fa5-a610-1cbb993f7b6b",
    "triggerAllTests-ATMSPageObjModel": "npx cypress run --spec cypress/integration/ATMSTests/**",
    "triggerAllTests-ATMSBDD": "npx cypress run --spec cypress/integration/ATMSBDD/**",
    "delete-mochawesome-report": "rm -f mochawesome-report/* || true"
  },
  "author": "Zuhoor",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^5.6.0",
    "cypress-cucumber-preprocessor": "^4.0.0",
    "cypress-iframe": "^1.0.1",
    "mochawesome": "^6.2.1",
    "multiple-cucumber-html-reporter": "^1.18.0"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  },
  "dependencies": {
    "mocha": "^8.2.1"
  }
}

**Comment by bahmutov** [comment]
Since you are on Windows, to delete the folder you probably need to use Windows command, maybe `DEL` like shown here https://www.thewindowsclub.com/delete-files-and-folders-command-prompt, since `rm` is a Unix shell utility.

**Comment by Muhammadehsan2019** [comment]
DEL command worked 
Thanks
