### ISSUE TITLE
Chrome no longer captures full test video

### ISSUE THREAD

**Issue by patcon** [cypress-io/cypress#14420]
Thanks to any readers! I'll update this is I figure it out, but wanted to log for now :)

Sometime between Wed Dec 2nd @ 7:30pm ET ([CI run with vid](https://github.com/pol-is/polis/runs/1489781853)) and Fri dec 4th @ 7:45pm ET ([CI run with vid](https://github.com/pol-is/polis/runs/1502020265)), cypress video artifacts stopped working.

- The build artifact went from ~1.5mb to 70kb, and hasn't changed back since.
- Most videos are just white screens, but some start to load the cypress app trimmings.
- Videos are all 1-2 sec
- running locally with electron produces not issue, but running locally with chrome shows same issue with capture
- note that there were no code changes in our repo to result in the failure, so likely related to GitHub updating the chrome version on GitHub Actions.

### Current behavior

Video exports from chrome are 1-2 sec white screen videos, which end mostly before the cypress window even loads (some load the app chrome around the edge). Electon video exports work fine. This affects both local runs and github action runs.

### Desired behavior

Would expect to Chrome to continue exporting video of specs.

### Test code to reproduce

See above links.

### Versions

- locally I am using:
  - Chrome `Version 87.0.4280.88 (Official Build) (x86_64)`
  - mac OSX catalina 10.15.7
  - Cypress 4.9.0 ([`package.json`](https://github.com/pol-is/polis/blob/fc0c11642e4d94e1f9fbcd37ca07a27e06f40f72/e2e/package.json))
  - GitHub Actions workflow: https://github.com/pol-is/polis/blob/fc0c11642e4d94e1f9fbcd37ca07a27e06f40f72/.github/workflows/cypress-tests.yml

### Mitigation

Switch to using another browser for testing for now.

**Comment by bahmutov** [comment]
Seems like the chrome version upgrade there. The chrome 87 requires a video frame ack which we have fixed in Cypress v6. Can you try the latest version?

**Comment by patcon** [comment]
Trying to see which updates the github actions environment might have gotten around this time...
https://github.com/actions/virtual-environments/commits/main?after=9b11155b751bf8f2d201180d28f93235faf65229+69&branch=main

Ubuntu 16.08 (my build image) got an update around this time, and in it Google Chrome was bumped to v87:
https://github.com/actions/virtual-environments/pull/2160

This is the same as my local system, where issue is reproducible. **Seems likely an issue with Chrome 87.**

**Comment by patcon** [comment]
Heh ok, seems I found my answer here: https://github.com/cypress-io/cypress/issues/9265 Closing as dup :) 🎉

**Comment by patcon** [comment]
You're a wonderful gem of a human, @bahmutov! Sorry to talk this out with myself in your inbox :)

**Comment by bahmutov** [comment]
Hehe thank you 🙏
