### ISSUE TITLE
Cypress doesn't take into account the config value 'chromeWebSecurity' when run in headless mode for Chrome

### ISSUE THREAD

**Issue by deepaksaggar** [cypress-io/cypress#14421]
When the tests are run in headless mode in Chrome(ver 87.0.4280.88 64 bit) with config value 'chromeWebSecurity=false' then Cypress(ver 6.2.0) FAILS to log into the app.
The same tests run fine when they are run in headless mode in Electron. Or when run in normal(headed) mode in Chrome.
This buggy behaviour with Chrome headless mode remains same when the config value is being provided through various ways i.e. :
1) directly through the command line (`--config chromeWebSecurity=false`)
2) through the default config file(cypress.json)
3) through a user config file(e.g. cypress-cypress.json) and then this files path is given in the command line`(--config-file cypress/fixtures/cypress-config.json`)

This buggy behaviour is observed on Window 10 machine when the tests were run locally.

Snippet from package.json file:
`"cypress:test": "cypress run --headless --spec cypress/integration/**/* --browser chrome --config chromeWebSecurity=false"`

Command used to trigger the run:
`npm run cypress:test`

**Comment by jennifer-shehane** [comment]
Can you add this test and run it within headed and headless, just to completely verify the config false is set properly or not, to narrow down the issue. Let us know the results. 

```js
it('test', () => {
  expect(Cypress.config('chromeWebSecurity')).to.be.false
})
```

Outside of this, the issue may be specific to your tests, so a reproducible example would be ideal.

**Comment by deepaksaggar** [comment]
@jennifer-shehane thanks for the prompt reply. The test suite have a 'before' hook where it logs into the application, so I placed the assertion(for chromeWebSecurity flag) that you suggested inside it, but just before where it tries to login to the app. And this assertion did pass both in headed and headless modes. So it establishes the fact that the flag value is correct however still the behaviour is as if the config value is not working for headless mode.
As for the example, because of the data confidentiality reasons I won't be able to share the code but I can that the app uses session authentication and it's a react app(ver 16.9).
