### ISSUE TITLE
Unhandled rejection Error: EACCES: permission denied, mkdir '~/.config/Cypress/cy/production'

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#14435]
### Versions
cypress: 6.0.0 6.2.1
system: linux
chrome : 80

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

In general EACCES errors involve permissions, so you may want to ensure you have the proper permissions within the directories you're working within.

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
