### ISSUE TITLE
Ability to whitelist as well as blacklist hosts

### ISSUE THREAD

**Issue by dracos** [cypress-io/cypress#1443]
### Is this a Feature or Bug?

Feature.

### Desired behaviour

Whilst you can blacklist hosts, I think it would be good if you could also provide a whitelist, as that way you could guarantee that your tests (which may be running quite frequently, after all) weren't making external requests you didn't know about (e.g. no need to worry about some third-party rate limiting for some item your page includes).

**Comment by brian-mann** [comment]
Yeah we were expecting this to be requested at some point. It's a good feature and can be implemented.

**Comment by jacobmelcher** [comment]
Can this get worked on this again? I don't believe this has been fixed. Thanks!

**Comment by jennifer-shehane** [comment]
Since this hasn’t had a lot of interest over the years, we’ll close this issue

**Comment by Pilatch** [comment]
I really need this to get merged.  It's causing me more pain than anything else at work, which is saying a lot.  We need to block basically everything except what we intercept, and what we want to whitelist.

If I don't block everything, the tests take forever.

If I try to only let some stuff through with a special minimatch expression in front of all parent domain, then weird things in our network layer will make our tests flake.

If I rig my own way of intercepting '*' and then doing my own logic on which requests get to continue, or get destroyed, or get fixtures, then the tests take forever, and it still sometimes flakes.

I NEED to blacklist basically everything of *.mydomain.com, except for one-subdomain.mydomain.com, which has web components we depend on at runtime.  Nothing else is working.  I've been bashing my head against this wall for two weeks now.

**Comment by jennifer-shehane** [comment]
@Pilatch If you can provide a way for us to see the performance issues, we’d prefer to address those outright. We’ve fixed several performance issue in 13 with the proxy, have you tried our latest version?
