### ISSUE TITLE
Delay for intercepted HTTP routes only works for the first call on that route

### ISSUE THREAD

**Issue by djungowski** [cypress-io/cypress#14446]
### Current behavior
When using `.intercept()` for a HTTP route and stubbing it with a static response with a defined delay, that delay is only used on the first ever occurrence of this call.

### Desired behavior
Every call of this route is delayed

### Test code to reproduce
Given the following HTML:
```html
<!DOCTYPE html>
<head>
    <title>msDelay Test</title>
</head>
<body>
<button id="click-me">Click me</button>
<p id="difference">0</p>
<script type="text/javascript">
    const difference = document.getElementById('difference');
    document.getElementById('click-me').addEventListener('click', () => {
        const before = new Date().getTime();
        fetch('/api/something').then(() => {
            const after = new Date().getTime();
            const diff = after - before;
            difference.innerHTML = `${diff / 1000}`;
        });
    });
</script>
</body>
```

the following Cypress test should work:
```js
describe('Delaying Responses', () => {
  it('should delay every response', () => {
    cy.intercept('GET', '/api/something', { body: {}, delayMs: 5000 }).as('apiRoute');
    cy.visit('msDelay.html');

    cy.get('#click-me').click();
    cy.wait('@apiRoute');
    cy.get('#difference').invoke('text').then(text => expect(parseFloat(text)).to.be.closeTo(5, 0.5));

    cy.get('#click-me').click();
    cy.wait('@apiRoute');
    cy.get('#difference').invoke('text').then(text => expect(parseFloat(text)).to.be.closeTo(5, 0.5));
  });
});
```

However the first assertion goes through just fine and the second one fails with `expected 0.009 to be close to 5 +/- 0.5`

### Versions

6.2.1

### Additional info
From what I can see, this is because in https://github.com/cypress-io/cypress/blob/f43f1c1f26290fc8387697c8122f0f50b6c7cb55/packages/driver/src/cy/net-stubbing/events/response-received.ts the delay is defined as follows and probably is only called on the first occurrence:
```
continueFrame.continueResponseAt = Date.now() + delayMs
```

**Comment by jennifer-shehane** [comment]
@djungowski I can recreate this issue as described. This is likely an oversight and not the intended behavior.
