### ISSUE TITLE
[Feature request] make cy.clearCookie() yield list of deleted cookies

### ISSUE THREAD

**Issue by shwarcu** [cypress-io/cypress#14449]
**Origin**
This is a followup to https://github.com/cypress-io/cypress-documentation/issues/2508

**Description**
Currently cy.clearCookie() yields null. It would be handy if it returned list of deleted cookies as confirmation of what has been done by the command.

**Docs:**
https://docs.cypress.io/api/commands/clearcookie.html

**Comment by jennifer-shehane** [comment]
Since this hasn’t had a lot of interest over the years, we’ll close this issue.
