### ISSUE TITLE
Cypress won't run tests on Windows in an enterprise as admin

### ISSUE THREAD

**Issue by asc-it-minds** [cypress-io/cypress#14447]
In our team we want to use Cypress for our End2End testing. We are able to run Cypress on macOS, but not on any Windows machines. We are running Cypress as admins on Windows. The error messages we get are not sufficient for us to solve the issue ourselves.

### Current behavior

To trigger the error, we have just sat up a standard Node Project with ```npm init``` and installed Cypress with ```npm install cypress```.

When verifying Cypress, we do not get any errors, and we are also able to open Cypress with ```npx cypress open```.

But when we are to run a test, either with the GUI from ```cypress open``` or with ```npx cypress run``` we are facing errors.

The error encountered in the GUI (cypress open):
![not_working_chrome](https://user-images.githubusercontent.com/71631165/103883714-db2bb000-50dd-11eb-8c31-ef7438a16dd5.PNG)
(clicking the balloon doesn't help)

with the output from the command prompt being:
```
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed
ERR_FAILED (-2) loading 'http://localhost:52682/__/#/tests/integration\examples\actions.spec.js'
Error: ERR_FAILED (-2) loading 'http://localhost:52682/__/#/tests/integration\examples\actions.spec.js'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:205:1868)
    at Object.emit (events.js:315:20)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     examples\actions.spec.js                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

We are running the example tests from Cypress, so it can't be because of any tests that we have written. We are also not running on Docker or any other VM. Furthermore we are not facing any issues with our GPUs, having tried different machines and GPUs.

When running ```npx cypress run``` we get the same error. I have attached the [debug.log](https://github.com/cypress-io/cypress/files/5781147/debug.log) after running with set DEBUG=cypress:*

### Desired behavior

Being able to run tests.

### Test code to reproduce

Since we are running on out enterprises' machines, it might not be possible for you to reproduce the problem we are facing.
But we did:
```
npm init
npm install cypress
npx cypress run
```

### Versions

Platform: win32 (10.0.19041)
Cypress Version: 6.2.1
Chrome 87

**Comment by jennifer-shehane** [comment]
Certain group policies (GPOs) on Windows may prevent Cypress from working as intended, which can cause tests to break. 

Can you read here for more info and workarounds: https://on.cypress.io/error-messages#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues and see if any of those resolve your issues?

I think a simple way to test this is to try to launch Cypress in the Electron browser.

**Comment by asc-it-minds** [comment]
Hi Jennifer. Thank you for your quick reply.

I tried solving the issue in the same order as the guide suggests:
1. I didn't find any Chrome GPO's that should block Cypress.
2. Running in Electron generates the same error message:
```ERR_FAILED (-2) loading 'http://localhost:53525/__/#/tests/integration\examples\actions.spec.js'
Error: ERR_FAILED (-2) loading 'http://localhost:53525/__/#/tests/integration\examples\actions.spec.js'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:205:1868)
    at Object.emit (events.js:315:20)
```
3. Running in Chromium generate the same error as above
4. Deleting all registries in both HKEY_CURRENT_USER and HKEY_LOCAL_MACHINE, regarding Chrome and Chromium unfortunately did not help either.

I have again attached a [debug.log](https://github.com/cypress-io/cypress/files/5787517/debug.log), if that could help.

**Comment by zaksta99** [comment]
Hi,
I had the same problem and for me works to run cmd(and after that cypress) NOT as admin.
So when I run cmd as administrator, I have the same problem as is described above and if I run cmd without administrator's rights, everything works.

**Comment by AskMarvinV** [comment]
> Hi,
> I had the same problem and for me works to run cmd(and after that cypress) NOT as admin.
> So when I run cmd as administrator, I have the same problem as is described above and if I run cmd without administrator's rights, everything works.

got same problem -  i was switching from my user as admin when i try to  unzip cypress to upgrade my local. But yes just run your VScode IDE as normal then it would run as perfect.

**Comment by asc-it-minds** [comment]
The company I work at does not allow to run non-whitelisted software as a non-admin account. Therefore the issue is solved by using an admin account to run the software. Unfortunately Cypress has been the only software that is not working this way.

**Comment by tomasscott** [comment]
I have exactly the same problem. Cannot run as non-admin, but fails when running as admin.

**Comment by dschmittwilken** [comment]
> I have exactly the same problem. Cannot run as non-admin, but fails when running as admin.

Me too. At least it works when using Firefox browser. For the longterm I need to have the interactive mode working with Chrome.

**Comment by Jsalvat** [comment]
after DAYS of having this problem. If u use ur cypress open on any console with admin rights it will crash or fail. Just use cypress open on any cmd without admin rights.

**Comment by mattiaskagstrom** [comment]
I can confirm this issue. Cypress 5.6.0 works as intended.

**Comment by BassT** [comment]
I experienced a similar problem and solution:
- Cypress fails to launch Chromium-based browsers (Chrome, Edge, Electron) on my enterprise machine, when I do `npm run cypress open` in the VS Code Powershell (Admin mode)
- But it works when running `npm run cypress open` in a non-admin Powershell

**Comment by mattiaskagstrom** [comment]
Seems to work again in version 7.5.0. anyone else?

**Comment by BassT** [comment]
Still experiencing the same issue.

**Comment by sharky910** [comment]
I am also experiencing this issue - it is all fine til I run a specific test that downloads a XLSX file, once it clicks to download that file then this issue occurs and cypress closes
