### ISSUE TITLE
Page load timeout will not fail the test if page is in redirection loop

### ISSUE THREAD

**Issue by henrikauppinen** [cypress-io/cypress#14445]
### Current behavior

Page load timeout will not stop the test if page is in redirection loop. The test may run forever. No log output is generated indicating what is happening.

Video: https://github.com/henrikauppinen/cypress-redirect-loop/blob/main/cypress/videos/redirect-loop.spec.js.mp4

The problem is obvious when looking at the UI but when this happens in headless mode in CI it may be extremely difficult to detect as the outcome may be just a long-running cypress process killed by CI.

We had a situation where tests completed successfully locally in headed mode and failed in CI. There was an oversight in test mocks and the application under test behaved differently in CI with drastically different performance constraints.

### Desired behavior
Page load timeout should trigger and stop the test even when page redirects continuously.

### Test code to reproduce

https://github.com/henrikauppinen/cypress-redirect-loop

### Versions

Confirmed with 5.4 until most recent 6.2.1 version.

**Comment by jennifer-shehane** [comment]
Yah that's a good one. I'm not sure that it's the pageLoadTimeout so much as the commands attempting to find the DOM elements that should timeout. The `cy.get('div')` should fail regardless of the redirects.

**Comment by prdarm** [comment]
reply+AQWYV3FK36DYW7Q44YOSVBF6HEZ6NEVBNHHBMWMYY4@reply.github.com

**Comment by bahmutov** [comment]
Released in v7.0.0
