### ISSUE TITLE
Opening child window to perform some operation is making main window to logout

### ISSUE THREAD

**Issue by hbuddaraju-CLGX** [cypress-io/cypress#14448]
### Current behavior

I am logging into an application and adding a member to it, after adding a member an email will be triggered with particular PIN and I have to enter the PIN to confirm. 

To get the PIN I have to login as ADMIN , and the main page should not be disturbed. So, I am using child window concept and trying to login as ADMIN and getting the PIN and closing the child window. But when I am trying to enter that PIN and click on verify , the main window page is logging out.

I tried using Incognito concept, even facing the same issue. If there is any possibility to use incognito mode only for child window, may be then I can get out of this issue.

### Desired behavior

There must be a way to use child window concept for getting the required information without main window getting logged out.

### Test code to reproduce

```js
describe('Add second market as OB', function () {
it('Add second market with valid data', function () {
        cy.visit(Cypress.env('stageupstreamlogin'))
        cy.url().should('contain', 'login')
        loginpage.getEmailBox().type(this.data.OfcBrokerEmail)
        loginpage.getPasswordBox().clear().type(this.data.Password)
        loginpage.getSignInButton().click({ force: true }).wait(2000)
        dashboardpage.getDashboardNavbar().should('be.visible').should('contain', 'Dashboard')
        cy.wait(2000)
        dashboardpage.getAddUserMarketButton().click()
        cy.wait(2000)
        addmarketpage.getMLO().select(this.data.MLO)
        addmarketpage.getMemberID().clear().type(this.data.ValidMemberId)
        addmarketpage.getVerifyAndResendButton().eq(0).click()
})
 it('open child window and login to Dashboard to get the PIN', function () {      
        cy.openWindow('')
        cy.get('input[id="txtLoginEmail"]').type('')
        cy.get('[id="Password"]').type('')
        cy.get('#btnSignIn').click().wait(2000)
        cy.openWindow('/ADM')
        cy.url().should('contain', 'ADM')
        cy.scrollTo(0, 1000)
        cy.get('a[href="/ADM/TrestleAlertLogs"]').click()
        cy.url().should('contain', 'ADM/TrestleAlertLogs')
        cy.openWindow('/ADM/TrestleAlertLogs')
        cy.get('button[data-id="AlertStatusValue"]').click()
        cy.get('div[class="btn-group bootstrap-select open"] div li:nth-child(1)').click()
        cy.get('input[class="form-control input-sm"]').clear().type(this.data.OBMemberId)
        cy.get('[value="Search"]').click({ force: true })
        cy.get('table[id="tblAlertList"]').then(($body) => {
            if ($body.text().includes('No alerts to display.')) {

                cy.get('button[data-id="AlertStatusValue"]').click()
                cy.get('div[class="btn-group bootstrap-select open"] div li:nth-child(4)').click()
                cy.get('input[class="form-control input-sm"]').clear().type(this.data.OBMemberId)
                cy.get('[value="Search"]').click()
                cy.get('table[id="tblAlertList"] tbody tr:nth-child(1) td:nth-child(7) a[class="btn-link btn-sm btn-info"]').invoke('attr', 'href').then(href => {
                    cy.openWindow(href)
                });
            } else {
                cy.get('table[id="tblAlertList"] tbody tr:nth-child(1) td:nth-child(7) a[class="btn-link btn-sm btn-info"]').invoke('attr', 'href').then(href => {
                    cy.openWindow(url + href)
                });
                //cy.get('table[id="tblAlertList"] tbody tr:nth-child(1) td:nth-child(7) a[class="btn-link btn-sm btn-info"]').should('be.visible').click()
            }
            trestledashboardpage.getMessageBody().invoke('text').then(($text) => {
                var fullText = $text
                var string1 = "12px;\">&nbsp;"
                var string2 = "&nbsp;</p>"
                PIN = fullText.match(new RegExp(string1 + "(.*)" + string2))
                cy.log(PIN[1])
            })
            cy.closeWindow();
            cy.wait(1000)
        })

    })
 it('Navigate to main window and Verify with Valid PIN', function () {

        addmarketpage.getPINField().clear().type(PIN[1]) // page is getting logged out
        addmarketpage.getVerifyAndResendButton().eq(2).click()
     
    })
})
```

### Versions

Cypress 6.2.1
Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Windows 10 64bit

**Comment by jennifer-shehane** [comment]
It's a little unclear, but I think you're using a single `cy.visit()` across your tests? The tests will automatically clear cookies/localStorage in between tests, so you'll need to ensure those are maintained across tests so that it doesn't logout. 

If you're using cookies, read this section of our docs: https://on.cypress.io/cookies#Preserve-cookies-through-multiple-tests

I think that you will likely find benefit from using our new Sessions API to write this test, which should be coming out as an experimental feature sometime next week. https://github.com/cypress-io/cypress/issues/8301

**Comment by hbuddaraju-CLGX** [comment]
Hey @jennifer-shehane , Thanks for your suggestion!!
I am using single test (i.e., single it block) for both main window and child window functionality, then its not getting logged out.

**Comment by bahmutov** [comment]
I don't understand the situation either. Is it a visit to the domain in the first test and when the second test runs it is logged out? Do you need to preserve the cookies to stay logged in then, see https://on.cypress.io/cookies?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
