### ISSUE TITLE
Lower minimum viewport dimension bound

### ISSUE THREAD

**Issue by dallaspersson** [cypress-io/cypress#1444]
- Operating System: macOS High Sierra (10.13.3)
- Cypress Version: 2.1.0
- Browser Version: Chrome 64.0.3282.186

### Current behavior:
Setting the viewport height or width bellow `200` pixels is currently not allowed. In the [docs](https://docs.cypress.io/api/commands/viewport.html#Arguments), it is stated that the height and width values must lie within the bounds of `200` to `3000` pixels. 

### Desired behavior:
To me, the desired behavior would be to allow setting values bellow `200` with my situation being that our web app is meant to be embedded within an iframe on other sites where it's layout relies on the viewport size, which height can be as small as `80` pixels. This makes us want to test down to this viewport size.

It would be very interesting to hear why this lower dimension bound exists and why it is currently `200` pixels. Any insight into this would be much appreciated. Could it be lowered or removed? I really like Cypress so far and hope to be able to use it. 

### How to reproduce:
Call `cy.viewport(199, 199)` and you'll get the warning I'm talking about.

**Comment by jennifer-shehane** [comment]
Honestly, I can't see any technical reason why the lower boundary is set to 200. Unless @brian-mann has some objection, you can create a pull request to change the lower value here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/window.coffee#L156-L157

The docs would also need to be updated to reflect the change when merged: https://github.com/cypress-io/cypress-documentation/edit/develop/source/api/commands/viewport.md

**Comment by dallaspersson** [comment]
Thanks you @jennifer-shehane for your swift and detailed reply. That is great news! I'll start working on a PR plus another for updating the docs in hope that @brian-mann doesn't have has any objection.

**Comment by karansapolia** [comment]
Hey! Seems a first-timers marked issue. @dallaspersson would you mind if I take this up? Also @brian-mann what should the lower value be according to you?

**Comment by dallaspersson** [comment]
@karansapolia: I have already started on this, so would really like to follow through with submitting the PR. Thanks.

**Comment by karansapolia** [comment]
@dallaspersson 👍
