### ISSUE TITLE
Cypress does support third party login like Salesforce or Google account

### ISSUE THREAD

**Issue by umarwmode** [cypress-io/cypress#14443]
We recently selected Cypress to be our test automation tool but noticed that Cypress does not recommend login via UI. The problem is that login into our app ( we want to test staging env) requires authentication via Salesforce or google.

Below are few issues:

- There is a unique client id in the url for each time we try to authenticate so cannot use `cy.request`
- Using UI does not work as Cypress gives redirect error

Please let us know how we can handle this. 

- Attached the video for your reference

For reference you can visit the page here: https://shift-training1.a.shiftdev.io/

https://user-images.githubusercontent.com/16259131/103868310-f79bfe00-5085-11eb-8943-8f1329f4db67.mov

**Comment by sainthkh** [comment]
Maybe [cypress-social-logins](https://github.com/lirantal/cypress-social-logins) plugin can give you some hints about the solution.

**Comment by AtofStryker** [comment]
Hey @umarwmode. This should now be feasible in Cypress 12 and possible in `12.4.0` with Salesforce UI login with https://github.com/cypress-io/cypress/issues/24290#issuecomment-1376214221.

Google login is also possible with Cypress `12.0.0` but we do not recommend it in CI as it will likely trigger MFA and other issues. If running locally this is not an issue

https://user-images.githubusercontent.com/3980464/211400949-9bf4c727-191b-4ff1-9e58-8c43b9b2daf9.mp4

 I am going to close this issue, but if this is still giving you problems in `12.4.0` please let us know! We will be having a Social Logins Guide published in the coming weeks
