### ISSUE TITLE
Missing Tests status menu - cypress runner

### ISSUE THREAD

**Issue by MusolQA** [cypress-io/cypress#14451]
Hi during today work, somehow the test details status bar disappeared in my browsers (Chrome, Electron,Firefox) - it doesn't matter which browser is used. I'm talking about this one:

![image](https://user-images.githubusercontent.com/40713510/103907033-05429980-5101-11eb-841b-02e52cd51baa.png)

The issue is only when I use cypress open command, my lists of test is displayed, and after selected one browser is open and tests are executed (Pages are loaded etc). But I cannot see this details on left. You can see below how my browser looks like in test mode. 

![image](https://user-images.githubusercontent.com/40713510/103907339-6ff3d500-5101-11eb-9f17-87e4f7d3a18f.png)

I tried to re-install cypress, use another version but same issue again and again...

Fun fact is that when I use cypress run --headed command everything is working fine

**Comment by jennifer-shehane** [comment]
There's an issue where you can drag the Command Log to be so small that it disappears https://github.com/cypress-io/cypress/issues/2132 that's likely what's happened here.

Could you try following [these instructions](https://on.cypress.io/troubleshooting#Clear-App-Data) to Clear App Data? This should reset the Command Log size back to default.

**Comment by MusolQA** [comment]
Working now!

Thanks!
