### ISSUE TITLE
McAfee halts installation on Letter_Number.js file

### ISSUE THREAD

**Issue by b-for** [cypress-io/cypress#14464]
When trying to install Cypress latest version with npm on Windows 10 from Powershell, the installation halts on extraction of file "Letter_Number.js".
I found that this file is rejected by the McAfee Agent on my company laptop:
 ```
'C:\Users\**********\AppData\Local\Cypress\Cache\6.2.1\Cypress\resources\app\packages\server\node_modules\regenerate-unicode-properties\General_Category\Letter_Number.js'
```

I was able to finish the install by creating the file myself from scratch with an editor and putting it in the correct folder in the cache.
See logs:

### Error from npm:

> PS C:\Sandbox> npm install cypress --save-dev
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> 
> > cypress@6.2.1 postinstall C:\Sandbox\node_modules\cypress
> > node index.js --exec install
> 
> Installing Cypress (version: 6.2.1)
> 
>   v  Downloaded Cypress
>   ×  Unzipping Cypress        87% 45s
>     ? Cypress Version: 6.2.1
>      Finishing Installation
> The Cypress App could not be unzipped.
> 
> Search for an existing issue or open a GitHub issue at
> 
> https://github.com/cypress-io/cypress/issues
> 
> ----------
> 
> Error: EPERM: operation not permitted, open 'C:\Users\**********\AppData\Local\Cypress\Cache\6.2.1\Cypress\resources\app\packages\server\node_modules\regenerate-unicode-properties\General_Category\Letter_Number.js'
> 
> ----------
> 
> Platform: win32 (10.0.19041)
> Cypress Version: 6.2.1
> npm WARN sandbox@1.0.0 No description
> npm WARN sandbox@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! cypress@6.2.1 postinstall: `node index.js --exec install`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the cypress@6.2.1 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\***********\AppData\Roaming\npm-cache\_logs\2021-01-08T08_03_22_484Z-debug.log
> 

### The log is in Dutch, in short: node.exe tried to access .... and the rule "letter_*.js" has been broken and the process has been blocked. 

> ************** heeft C:\Program Files\nodejs\node.exe uitgevoerd en dit proces probeerde toegang te krijgen tot C:\Users\**************\AppData\Local\Cypress\Cache\6.2.0\Cypress\resources\app\packages\server\node_modules\regenerate-unicode-properties\General_Category\Letter_Number.js, waarmee de regel 'letter_*.js voorkomen - Ivan' is overtreden en het proces is geblokkeerd. Zie KB85494 voor informatie over hoe u op deze gebeurtenis reageert.

> Analyzer / Detector
> --
> Aanmaakdatum van analyzerinhoud | 22-9-2015 1:11 PM
> Versie van analyzerinhoud | 10.7.0
> Productnaam | McAfee Endpoint Security
> Naam van analyzerregel | letter_*.js voorkomen - Ivan
> Productversie | 10.7.0
> Naam van functie | Toegangsbeveiliging
>  
> Bedreiging
> Ondernomen actie | Blokkeren
> Bedreigingscategorie | 'Bestand'-klasse of -toegang
> ID van bedreigingsgebeurtenis | 1092
> Bedreiging verwerkt | Ja
> Naam van bedreiging | letter_*.js voorkomen - Ivan
> Ernst van bedreiging | Kritiek
> Tijdstempel van bedreiging | 7-1-2021 7:16 PM
> Type bedreiging | Toegangsbeveiliging
>  
> Bron
> Brontoegangstijd | 7-1-2021 7:12 PM
> Bronaanmaaktijd | 16-11-2020 11:23 AM
> Bron bestandspad | C:\Program Files\nodejs
> Bron bestandsgrootte | 56441504
> Bron wijzigingstijd | 16-11-2020 11:23 AM
> Bronhash procesbestand | 23587436ad98fe47797a9ac33116b9a2
> Bron procesnaam | node.exe
> Bronproces ondertekend | Ja
> Bronproces ondertekenaar | C=US, S=CALIFORNIA, L=SAN FRANCISCO, O=OPENJS FOUNDATION, CN=OPENJS FOUNDATION
> Bron gebruikersnaam | ************
>  
> Doel
> Doelhostnaam | *********
> Doelnaam | Letter_Number.js
> Doelpad | C:\Users\*********\AppData\Local\Cypress\Cache\6.2.0\Cypress\resources\app\packages\server\node_modules\regenerate-unicode-properties\General_Category
> Doel ondertekend | Nee
> Doel gebruikersnaam | SYSTEM
>  
> Overige
> Toegang opgevraagd | Maken
> Vectortype | Lokaal systeem
> Duur vóór detectie (dagen) | 52

**Comment by jennifer-shehane** [comment]
We suggest excluding the Cypress cache folders from your virus software scanning.
