### ISSUE TITLE
cy.intercept() doesn't catch post request unless simple route matching is used

### ISSUE THREAD

**Issue by reuben-rodrigues** [cypress-io/cypress#14461]
### Current behavior

Unsure of the exact cause, but this works when using cy.route() but doesn't on intercept.

Using the following code, cy.intercept() does not seem to catch the post request:
```js
    cy.get('@id').then(id =>
      cy.get('@ChildId').then(ChildId =>
        cy.intercept({method: 'POST', url: `/Api/Apps/ChildApp/Data/PostWithId/${ChildId}?hierarchy=AllFields|${id}`}).as('childRecordPost')))
```

![image](https://user-images.githubusercontent.com/58171229/104010658-c2d29880-51a4-11eb-903e-ed75b775a590.png)
![image](https://user-images.githubusercontent.com/58171229/104010717-dc73e000-51a4-11eb-9177-d7a9395dc629.png)

Minimatch is successful when comparing the routes shown in cypress to the post request:
![image](https://user-images.githubusercontent.com/58171229/104010557-96b71780-51a4-11eb-8a37-864f569391eb.png)

However, using ** seems to work and catch the post.
```js
    cy.get('@id').then(id =>
      cy.get('@ChildId').then(ChildId =>
        cy.intercept({method: 'POST', url: `**/${ChildId}**${id}`}).as('childRecordPost')))
```
### Desired behavior

Same behaviour as using route instead of intercept. The post request should be caught.

### Versions
6.2.1

**Comment by jennifer-shehane** [comment]
Passing the `url` argument to `cy.intercept()` will attempt to match on the full url. Since you only want to match on the `path`, you'll want to pass the `path` argument. 

The glob works because it matches the full url when passed `**`.

```js
cy.get('@id').then(id =>
cy.get('@ChildId').then(ChildId =>
cy.intercept({method: 'POST', path: `/Api/Apps/ChildApp/Data/PostWithId/${ChildId}?hierarchy=AllFields|${id}`}).as('childRecordPost')))
```
