### ISSUE TITLE
use cy.visit('/')，However, the console displays "failed to load resource: Net:: err"_ EMPTY_ RESPONSE’

### ISSUE THREAD

**Issue by rzdong** [cypress-io/cypress#14481]
### Current behavior
The project I started locally is‘ https://127.0.0.1:80’ , However, Failed to load resource: net::ERR_EMPTY_RESPONSE
![image](https://user-images.githubusercontent.com/19262880/104167002-98980980-5436-11eb-87d7-b4ebb09e076a.png)

but, when i started project on 'http://127.0.0.1:80' (**use http**), it work;

### Desired behavior
I hope I can access it normally in the case of HTTPS

### Versions
mac 11.1
chrome 87

**Comment by jennifer-shehane** [comment]
Your webpage is serving mixed content. Your visiting an https page, yet your css stylesheet is being served over http. So Chrome attempts to visit the https location of the css and does not find it. See https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content This is not an issue with Cypress and needs to be fixed on your site.

**Comment by rzdong** [comment]
> Your webpage is serving mixed content. Your visiting an https page, yet your css stylesheet is being served over http. So Chrome attempts to visit the https location of the css and does not find it. See https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content This is not an issue with Cypress and needs to be fixed on your site.

I can visit this https://xxx.css in my own chrome.

But I cannot visit that in **cypress-chrome**

They are the same link

**Comment by rzdong** [comment]
@jennifer-shehane

**Comment by Remonell** [comment]
I had the very same issue with the same error message. My symfony php backend is running locally in docker. XDebug is also installed. Following 2 lines in the backend terminal resolved this issue and I was finally able to login.

    touch /var/www/html/xdebug.log
    chmod 777 /var/www/html/xdebug.log
