### ISSUE TITLE
Not able to select date from rc-calendar

### ISSUE THREAD

**Issue by francisngo** [cypress-io/cypress#14494]
I am trying to select a date from the rc-calendar library. When I attempt to select the date to get to the element, I get this issue:

<img width="730" alt="Screen Shot 2021-01-11 at 1 13 56 PM" src="https://user-images.githubusercontent.com/11182826/104251684-1e12be00-5425-11eb-8c27-289b29e478c2.png">

this is what the code looks like when it's rendered out:
![image](https://user-images.githubusercontent.com/11182826/104251841-75189300-5425-11eb-867f-4fa88aef9453.png)

and this is the cypress code:
(*** I can't add data-* because the element is created inside the rc-calendar so i am getting the element by class name)
```
cy.get('.rc-calendar-cell.rc-calendar-selected-day')
        .first()
        .children('.rc-calendar-date')
        .click();
```

**Comment by bahmutov** [comment]
Hi Francis, can you give us a reproducible example with the calendar that you are trying to test against?

**Comment by francisngo** [comment]
Code Sandbox: https://codesandbox.io/s/agitated-elion-bswpo

**Comment by bahmutov** [comment]
I took the code sandbox code and added my Cypress test in https://github.com/bahmutov/rc-calendar

I do not see a problem, here is a screenshot. Can you modify the test in my repo to show the problem?

<img width="1281" alt="Screen Shot 2021-01-12 at 10 22 30 AM" src="https://user-images.githubusercontent.com/2212006/104334537-7c40af00-54c0-11eb-8ef4-89da8edea77e.png">

**Comment by francisngo** [comment]
Our application is using cypress version ^4.12.1, if that makes a difference

**Comment by bahmutov** [comment]
Can you try Cypress v6.2.1 please

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
