### ISSUE TITLE
Copy/Paste doesn't work in the GitHub login Electron window

### ISSUE THREAD

**Issue by lorennorman** [cypress-io/cypress#145]
**Description**
I use 1Password and wish to paste my password into the GitHub login window (because it is a 20+ character monstrosity and the whole point is to not have to ever deal with it.) Keyboard shortcuts don't seem to work in the login window, however. This reduces confidence, increases frustration, and probably freaks people out a little bit because they're being asked for sensitive information about a _different_ site, but they aren't getting all of the warm fuzzies of a standard browser window that works as normal.

**Steps To Reproduce**
- [ ] Start Cypress
- [ ] Logout (optional, only if logged in)
- [ ] Click "Login with GitHub", an Electron web window appears
- [ ] Attempt to use standard keyboard shortcuts (copy, paste, select-all, etc)

**Additional Info**
This only happens on the packaged version of Cypress, it isn't a problem in dev. This link seems to nail the issue:
https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by brian-mann** [comment]
Fixed in [`0.16.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0161-05222016).
