### ISSUE TITLE
cy.wrap() makes methods loose reference

### ISSUE THREAD

**Issue by Luiz-Ossinho** [cypress-io/cypress#14508]
### Current behavior
When you set a method inside a object using another variable,
it seems that cy.wrap() will loose track of it.
But if you set a method inside the object itself,
cy.wrap will be able to call the method

### Desired behavior
I'm not extremely familiar with Cypress (or any Javascript), 
but i believe that i should be able call methods inside objects as in both examples

### Test code to reproduce

```js
const bar = () => {
    // this represents a method
};

// This object will throw undefined when trying to use its methods
let ObjectListError = {
    entry = { propertyStr: "foo", propertyInt: 1, propertyFunc: bar}
}

// This object will work properly
let ObjectList = {
    entry = { propertyStr: "foo", propertyInt: 1, propertyFunc: () => {
            // this represents a method
        }}
}

When('Wraping objects', () => {
    cy.wrap(ObjectList.entry).as('ObjectList')
    cy.wrap(ObjectListError.entry).as('ObjectListError')
})

Then('Using properties from objects', () => {
    cy.get('@ObjectList').then($object=>{
        cy.log($object);
        // This will show that propertyFunc is a function
        // { propertyStr: "foo", propertyInt: 1, propertyFunc: function(){ }}
        // $object.propertyFunc() will work as intended
    })
    
    cy.get('@ObjectListError').then($object=>{
        cy.log($object);
        // This will show that propertyFunc as undefined
        // { propertyStr: "foo", propertyInt: 1, propertyFunc: undefined}
        // $object.propertyFunc() will throw an error
    })
})
```

### Versions
Cypress Version 6.1.0
-From what i've read in the changelog, this "bug" is still present in 6.2.0 and 6.2.1

**Comment by jennifer-shehane** [comment]
You mention that the call will 'throw an error'. Can you include the error text or a screenshot of the error? Thanks.

**Comment by Luiz-Ossinho** [comment]
The error will be 
$object.propertyFunc() is not a function
(I will post a screenshot later today)

**Comment by bahmutov** [comment]
@Luiz-Ossinho I believe the problem is in your Cucumber / Gherkin transpiler. It seems it "loses" the external variable `bar`. I have added the equivalent JavaScript tests without transpiling in https://glebbahmutov.com/cypress-examples/6.2.1/commands/misc.html#cy-wrap and the methods / values / functions are never "lost". I suggest you check the Cucumber syntax to write it differently to avoid this error.
