### ISSUE TITLE
Sending {enter} in a field that is set to submit a form causes Cypress to hang indefinitely

### ISSUE THREAD

**Issue by alexp1980** [cypress-io/cypress#14500]
### Current behavior
We have a React app that has three fields that submit a form and navigate to the next page when hitting the "Enter" key within those fields. When trying to mimic this in Cypress with _element.type('sometext{enter}')_ Cypress just hangs on the type action and we have to kill cypress and start again. There doesn't appear to be any logs happening anywhere.

### Desired behavior
When typing some text in the field and then mimicking the enter key with _element.type('sometext{enter}')_, the next page should load

### Test code to reproduce
_element.type('sometext{enter}')_
or simply...
_element.type('{enter}')_

### Versions
5.6.0

**Comment by bahmutov** [comment]
Can you please provide a reproducible example? Some mini-repo that shows how and where the form is trying to submit?

Also, could you try using the latest Cypress v6.2.1

**Comment by alexp1980** [comment]
@bahmutov, it works in the 6.2.1 Cypress, thanks
