### ISSUE TITLE
The `its` command doesn't accept a log option (logging can't be disabled)

### ISSUE THREAD

**Issue by cwohlman** [cypress-io/cypress#1450]
### Current behavior:
`cy.window({ log: false }).its('something', { log: false })` throws an error because no options object is supported. (The docs bear this out as well).

### Desired behavior:
I should be able to suppress logging using `its('something', { log: false })` or the `its` command should inherit the log level from the previous call (if this is currently the expected behavior I'll investigate further and create a reproduction, I didn't see a mention of this in the docs).

Also, I would think that the `its` command should accept a timeout property.

- Cypress Version: 2.1.0

**Comment by brian-mann** [comment]
Agree. Oversight on our part.

**Comment by cwohlman** [comment]
How do we deal with the arguments spread operator for `invoke`?

**Comment by bahmutov** [comment]
Also needs timeout option, just like other commands

**Comment by wildaces215** [comment]
Is this open?

**Comment by wildaces215** [comment]
I would like handle it!

**Comment by simonhaenisch** [comment]
I also need this, but don't have any coffeescript experience :|

Is it that [`invokeFn = (subject, fn, args...) ->`](https://github.com/cypress-io/cypress/blob/issue-1350/packages/driver/src/cy/commands/connectors.coffee#L124) needs to be changed to

```coffee
invokeFn = (subject, fn, options = { log: true }, args...) ->
```

and then replace [`options._log = Cypress.log`](https://github.com/cypress-io/cypress/blob/issue-1350/packages/driver/src/cy/commands/connectors.coffee#L138) with

```coffee
if options.log
  options._log = Cypress.log
```

?

Or do you rather use

```coffee
_.defaults(options, {
  log: true
})
```

to set the defaults?

**Comment by gabbersepp** [comment]
At a first step I added the Loggable options to its(). I will try a variant for invoke() in the next days

**Comment by gabbersepp** [comment]
I will have a look at the `timeout` requirement now

**Comment by gabbersepp** [comment]
What would be the case for a timeout here? Is it a common use case that an existing object is extended with properties or functions after some time?
