### ISSUE TITLE
CypressError: Timed out retrying: Expected to find element: '#app-name', but never found it

### ISSUE THREAD

**Issue by devamani83** [cypress-io/cypress#14502]
### Current behavior
I get "Timeout retrying after 4000ms: Expected to find element:  h3#app-name, but never found it error after Azure AD login is successful and loaded the application landing page. 

![image](https://user-images.githubusercontent.com/13065329/104329076-8364be80-54ba-11eb-8914-e7efe10f6714.png)

![image](https://user-images.githubusercontent.com/13065329/104330464-fde20e00-54bb-11eb-946c-b03f058fbd37.png)

### Desired behavior
After the third-party login redirect is successful, the application landing page loads properly. cy.get() method should an specified element correctly and assert the test cases properly without any exception. 

### Test code to reproduce
Create a custom command to bypass/authenticate Azure ad login and call that custom command in the before() in the spec file. 
then write the test cases to test page elements. 

### Versions
Cypress version 6.2.1.16153

**Comment by bahmutov** [comment]
Look at the screenshot - it seems it is trying to get `h3#app-name` element _before_ the successful redirect has finished (that's why there is "page loaded" _after_ the command). I suggest you add a command with an assertion to make sure you are on the destination page after the login

```
cy.login()
cy.location('pathname').should('eq', '/home') // for example
cy.get('h3#app-name') ...
```

**Comment by devamani83** [comment]
Nope!  I still have the same error. 
![image](https://user-images.githubusercontent.com/13065329/104344976-cd09d500-54cb-11eb-8ab5-11fc22bb27e2.png)
![image](https://user-images.githubusercontent.com/13065329/104345016-d8f59700-54cb-11eb-9c69-4298df0763ab.png)

**Comment by devamani83** [comment]
![image](https://user-images.githubusercontent.com/13065329/104345145-004c6400-54cc-11eb-9b80-93e4b9c1fd0e.png)

**Comment by bahmutov** [comment]
Unfortunately, there is not enough information to reproduce or diagnose the problem. Please provide videos, screenshots, or a reproducible code example we can run to see the problem.

**Comment by devamani83** [comment]
I was using testing CI app in my local. Below are the code. 

Commands.js
--------------

/**
 * Allows you to first grab an access token before opening the application page
 */
Cypress.Commands.add("loginWithAdal", (pageUrl) => { 
    const config = {   
      tenant: '',
      clientId: '',
      clientSecret: '',     
    };
  
    // Fetch the access token for the Microsoft Graph
    cy.request({
      method: 'POST',
      url: `https://login.microsoft.com/${config.tenant}/oauth2/token`,
      headers: {
         'cache-control': 'no-cache',
         'Content-Type': 'application/x-www-form-urlencoded'
      },
      form: true,
      body: {
        grant_type: 'client_credentials',
        client_id: config.clientId,
        client_secret: config.clientSecret    
       
      }
    }).then(response => {
      if (response && response.status === 200 && response.body) {
        const accessToken = response.body["access_token"];
        const expires = response.body["expires_on"];
        // Store the retrieved access token in the session storage
        cy.window().then((crntWindow) => {
        //  crntWindow.sessionStorage.setItem(`adal.token.keys`, `${config.resource}|`);
          crntWindow.sessionStorage.setItem(`adal.expiration.key`, expires);
          crntWindow.sessionStorage.setItem(`adal.access.token.key`, accessToken);          
          cy.visit(pageUrl);
        });
      }
    });
  });

main.spec.js
-------------

describe('Azure AD login testing', function() {
    const PAGE_URL = "http://localhost:9000";
    
    /**
     * Before visiting application page, we first need to authenticate
     */
    before(() =>  {
      cy.loginWithAdal(PAGE_URL);      
    });
  
    /**
     * After all tests
     */
    after(() => {
      // Wait 1sec for the video
      //cy.wait(1000);
    });
  
   
    /**
     * Validate if a app return 200 ok
     */
    it('Validate app returns 200', () => {    
        cy.intercept('GET', '/').as('getPage')
        cy.wait('@getPage').its('response.statusCode').should('eq', 200)  
     
      
    });
      
    /**
     * Validate if a app name is shown
     */
    it('Validate app name', () => {    
        cy.location().should((loc) => {
            expect(loc.host).to.eq('localhost:9000')           
          })
      cy.get('h3#app-name').should('eq','Recon');
     
      
    });
    
    /**
     * Validate if app version is shown
     */
    it('Validate app version', () => {      
      cy.get('.ax-app-version').should('eq','v1.0.0.0');
     
    });
   
  })

**Comment by devamani83** [comment]
support\indes.d.ts
--------------------
declare namespace Cypress {
    interface Chainable {
      // Add custom commands if needed
      loginWithAdal: (pageUrl: string) => void     
    }
  }

**Comment by bahmutov** [comment]
Do you need to preserve cookie between the tests to continue being logged in?

**Comment by devamani83** [comment]
Hmm, I don't think I need cookie because I store the token in the session storage.

**Comment by devamani83** [comment]
@bahmutov - Please let me know if you could reproduce the issue and help me out to resolve this issue.

**Comment by bahmutov** [comment]
I cannot reproduce the error as no reproduction code that we can run was given to us

**Comment by devamani83** [comment]
@bahmutov  - Looks like the Cypress is not redirecting back to application page after the Azure ad login was successful.  After the Azure ad login authenticate step, token is being added to the appurl(http://localhost:9000) but it should redirect to http://localhost:9000 and load the page.  

![image](https://user-images.githubusercontent.com/13065329/104652273-df7c3e00-5686-11eb-9641-d5673db3827c.png)
