### ISSUE TITLE
cy.intercept() breaks multipart form submissions

### ISSUE THREAD

**Issue by javitonino** [cypress-io/cypress#14527]
### Current behavior

Since upgrading to Cypress 6.2.1, multipart form submissions no longer work when they are `intercept()`ed. This seems to be a regression introduced by https://github.com/cypress-io/cypress/issues/9359

### Desired behavior

I can intercept multipart uploads, as I was able to do in Cypress 6.0.0 - 6.2.0

### Test code to reproduce

As a minimal reproducing program, I used https://github.com/AlexCSR/cypress-intercept-buffer-bug (from the #9359 ticket). In my system, that tests works fine in 6.2.0, but breaks in 6.2.1. It seems to be the opposite of what people on that ticket where experiencing.

If I inspect network traffic using that test in 6.2.1:
- The body of the browser -> cypress proxy request is correct
- The body of the cypress proxy -> origin server is `{}` (no multipart boundaries included)

### Versions

Broken in Cypress 6.2.1, works in Cypress 6.0.0 - 6.2.0
Tested with Node 15.4.0, 10.20.1 and 12.18.2 running on Linux (Arch Linux & Ubuntu)
Chromium 87 (although that seems irrelevant, I can reproduce by sending HTTP requests to the Cypress proxy using curl)

Maybe @AlexCSR can comment on what versions they use? Since I'm using their code to reproduce and get the opposite results.

**Comment by bahmutov** [comment]
I am not sure I understand the steps to reproduce it. The references image problem should be broken in 6.2.0 and fixed in 6.2.1. You report the opposite. Can you add screenshots or better yet create a reproducible example?

We have a recipe that shows checking a multipart form here: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept see "form-spec.js" file. Maybe you can use it as the starting point?

**Comment by samtsai** [comment]
This might be related as well https://github.com/cypress-io/cypress/discussions/14535

**Comment by javitonino** [comment]
Yeah, I'm reporting the exact opposite than that other ticket. I even took the reproducing example from there to do the testing and I see the complete opposite: working in 6.2.0 and broken in 6.2.1.

I cloned the example from that ticker and added some Dockerfiles in order to try to isolate this as much as possible. https://github.com/javitonino/cypress-intercept-buffer-bug

This is what I see:

```sh
git clone https://github.com/javitonino/cypress-intercept-buffer-bug.git
cd cypress-intercept-buffer-bug
docker build . -f Dockerfile6.2.0 -t cypress-intercept-6.2.0
docker build . -f Dockerfile6.2.1 -t cypress-intercept-6.2.1
```

```sh
docker run cypress-intercept-6.2.0

[...]
    ✔  All specs passed!                        00:03        3        3        -        -        - 
```


```sh
docker run cypress-intercept-6.2.1

[...]
    ✖  1 of 1 failed (100%)                     00:10        3        1        2        -        - 
```

**Comment by jennifer-shehane** [comment]
Is this issue localized to Docker? I'm trying to recreate the issue from the repo you provided, but I see the provided tests always failing in Cypress 6.2.0, 6.2.1, and 6.3.0.

**Comment by javitonino** [comment]
> Is this issue localized to Docker?

No, it's not. I just used Docker to try to isolate as many factors as possible but I can reproduce without it. In my case, by running the repo outside docker I see the same behaviour (works in 6.2.0, breaks in 6.2.1). I just tested 6.3.0 and it breaks (same as 6.2.1) for me.

**Comment by javitonino** [comment]
So, I debugged a bit what is happening here, and the problem seems to be the following:

1. The cypress server receives a request. Since it's multipart, it sets the body to the buffer: https://github.com/cypress-io/cypress/blob/v6.2.1/packages/net-stubbing/lib/server/intercept-request.ts#L116
2. It's sent to the driver
3. The driver passes it to the user code. In my case, I do nothing.
4. The driver sends the modified request back to the cypress server. In doing that, it converts objects to JSON https://github.com/cypress-io/cypress/blob/v6.2.1/packages/driver/src/cy/net-stubbing/events/request-received.ts#L142-L144. Converting a buffer with `JSON.stringify` results in a string like `{}`
5. The server receives the new requests and sends it to the origin. The body is `{}` which is incorrect

This only happens when you `intercept()` a `multipart/form-data` request and do not modify the request and let it go to the origin. 

It did not happen in 6.2.0 because the body was always converted to string before sending it to the driver and, since strings are not objects, the driver did not run `JSON.stringify` before returning the modified request to the server.

**Comment by yoavniran** [comment]
Also had this problem upgrading from cypress 4.x. It certainly made upgrading to 6.5 a lot more difficult than expected.

I wrote a small command that makes it easy to work with multipart requests and make assertions on the body,

IMO it should have been handled by Cypress, but until then I'm using: https://www.npmjs.com/package/cypress-intercept-formdata

**Comment by ppiyush13** [comment]
We also impacted by this issue. Anyone find any workaround ?

**Comment by flotwig** [comment]
This appears to not be an issue in the newest release of Cypress. Please open a new issue if you are encountering issues with multipart and `cy.intercept()`.
