### ISSUE TITLE
If pausing on handled exceptions, isJQuery fires alot, making it more difficult to debug

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/cypress#14526]
### Current behavior
Open the devtools, switch on pause on handled exceptions. It breaks alot here:

![image](https://user-images.githubusercontent.com/309321/104442038-ce530480-5594-11eb-8bb7-19bf790e06ae.png)

### Desired behavior

No exceptions thrown.

It would be as simple as changing the code to:

```
hasJqueryProperty = obj && typeof obj === 'object' && ('jquery' in obj || obj.jquery);
```

I'm not really sure in what cases obj would be falsy but have a "jquery" property on it? Obviously don't know the code that well.

### Test code to reproduce
I think any test using `cy.get` that doesn't pass a jquery object.

### Versions

6.2.1

**Comment by sainthkh** [comment]
Sorry for the late reply.

Unfortunately, `try...catch` syntax is necessary because it causes failure in some cases like below: 

https://github.com/cypress-io/cypress/blob/26edc21ce7b9858f82144068b74f81e67983146f/packages/driver/cypress/integration/commands/actions/click_spec.js#L1815-L1839

**Comment by lukeapage** [comment]
But why would adding another condition break things - you need an exception?

**Comment by sainthkh** [comment]
The thrown exception is not about `obj` not being an object. `chai` object doesn't allow accessing invalid properties like `jquery`. The error message below:

```
Error: Invalid Chai property: jquery
    at Object.proxyGetter [as get] (proxify.js:78)
    at Object.isJquery (jquery.js:30)
    at Object.unwrapFirst (utils.js:60)
    at eval (cy.js:440)
    at tryCatcher (util.js:16)
    at Promise._settlePromiseFromHandler (promise.js:512)
    at Promise._settlePromise (promise.js:569)
    at Promise._settlePromise0 (promise.js:614)
    at Promise._settlePromises (promise.js:694)
    at eval (async.js:123)
```

Because of this, removing `try...catch` is impossible.
