### ISSUE TITLE
Install cypress on empty/clean visual studio project

### ISSUE THREAD

**Issue by ELFCHE** [cypress-io/cypress#14524]
Hello it is Evelina writing, 

As I cannot install cypress as part of a development project (we use old technology and we have may projects in the solution) I try to install in in an empty Java Script project. However, when I run npm install cypress --save-dev - cypress is installed but not included in the project and in packege.js file. What can I do?

Thank you in advance!

**Comment by jennifer-shehane** [comment]
You may need to initialize the project with npm first in order to add the package.json file within the project. Otherwise if may be installing cypress on some other directory where it is finding a package.json (like a parent directory). 

Try running the command below first.

```
npm init
```

**Comment by 89pabloalvarez** [comment]
i have the same issue... and doesnt work the "npm init" after all..

the steps i done was..

1_download Node.js from the main page and install the MSI package.
2_check Node installation typing "npm -version" and the answer was fine "8.11.0".
3_i create a "testing path" for this.
4_i run the cmd console into admin mode, navegate to that path and execute "npm init", it only created a "package.json" as Jennifer said.
5_then, i execute the main command "npm install cypress --save-dev". it finished successfully and create "node_modules" folder  and "package-lock.json" file..

When i open that folder with Visual Studio Code application i only see these files, the project was empty, i remember one or two years ago when i install that, the installation comes with a few files including test examples, now its empty and i dont know what i do wrong. On google searchs i see everyone typing "npm cypress install" and they all has that tests

NOTE: If i go to path folder /node_modules/.bin and execute in console "cypress open" it opens successfully
