### ISSUE TITLE
cy.intercept by request cause

### ISSUE THREAD

**Issue by notpushkin** [cypress-io/cypress#14525]
### What would you like?

Allow matching routes by its cause (e. g. `image` or `xmlhttprequest`):

```js
cy.intercept({
  url: "/orders",
  cause: "xmlhttprequest",
});
```

### Why is this needed?

My current application uses same URLs on API and UI side (e. g. `https://127.0.0.1:3000/orders` on the frontend queries `https://127.0.0.1:4000/orders` on the backend). I need to stub the API call, then open the page on the frontend as usual.

`cy.route` was handling only API requests, so simple `cy.route("/orders")` would work alright independent of the environment – if the backend was on a different hostname (e. g. CI could use a staging instance instead of localhost), `cy.route` would still match it. With `cy.intercept`, the only way to match API calls right now is to add a hostname, e. g.:

```js
const apiRoot = Cypress.env("api_root");
cy.intercept("${apiRoot}/orders");
```

This looks acceptable but it's another configuration variable to keep up to date, and can be avoided. :-)

### Implementation suggestion

If I get this correctly, this can't be implemented using just the current setup with running a proxy server. However, we could use the extension running in the browser to match the routes we need using the `webRequest.onBeforeRequest` ([Mozdev][mdn], [Chrome docs][chr]) API. If we can't move all intercepting business to the extension (why?), we could use it to add an HTTP header to all requests (`X-Cypress-Cause: xmlhttprequest`) and match that on the proxy side as usual.

P. S. Thank you all for your great work!

[mdn]: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest
[chr]: https://developer.chrome.com/docs/extensions/reference/webRequest/

**Comment by flotwig** [comment]
Related work: #14843

We will probably use CDP/foxdriver to do this, not WebExtensions, since WebExtensions do not work in headless Chrome. They also do not work completely in Electron.

**Comment by notpushkin** [comment]
@flotwig Will give 7.0 a go (perhaps next week?), thank you! Things do look a lot clearer (really love how you now can override a particular request by redefining a handler for it!) but I can't really see how this could help in this particular case. Could you elaborate, please? :-)

**Comment by flotwig** [comment]
Oh, never mind, I misunderstood why you needed to use `apiRoot`. :P

**Comment by flotwig** [comment]
This will be added in https://github.com/cypress-io/cypress/pull/25075, see PR for API details.
