### ISSUE TITLE
Cy.on + assertion destroys fetch stub set on window object

### ISSUE THREAD

**Issue by eric-burel** [cypress-io/cypress#14533]
### Current behavior
`cy.on` + an assertion seems to destroy currently activated mocks in `window` object.

This is a sample of the code that produces this:
```js
cy.on("window:before:load", win => {
  const originalFetch = win.fetch;
  cy.stub(win, "fetch").callsFake(mockedGraphqlFetch(originalFetch, stubs));
});
cy.on("url:changed", (url) => { 
    // this line is destroying the previous stub for unknown reason. It is not displayed anymore in the "spies/stub" section of the test UI either
   // when commented, everything works back again
    expect(url).to.match("whatever")
})
```
### Desired behavior
Do not destroy the mock on window.

### Test code to reproduce

This code should repro. You won't have this line when running the test:
![image](https://user-images.githubusercontent.com/7983005/104477018-1ab43980-55c1-11eb-80e2-47a85023053b.png)
But if you remove the expectation it appears again. (note: "google.com" do not use fetch so that's not the best example to test on, didn't found a website that actually used fetch).

Edit: it happens only if the assertion is failing. If the assertion is ok then the stub are kept as expected.
```js
describe("cy bug repro", () => {
  it("stubs", () => {
    cy.on("window:before:load", win => {
      const originalFetch = win.fetch;
      cy.stub(win, "fetch").callsFake((...args) =>
        console.log("fetch with args:", ...args)
      );
    });
    cy.visit("https://www.google.com/");
    cy.on("url:changed", url => {
      // this line is destroying the previous stub for unknown reason. It is not displayed anymore in the "spies/stub" section of the test UI either
      // when commented, everything works back again
      expect(url).to.match(/github/);
    });
  });
});

```

### Versions

`Found "cypress@4.8.0"`

**Comment by bahmutov** [comment]
Can you try the latest Cypress version 6.2.1 please?

**Comment by eric-burel** [comment]
Seems ok on 6.2.1... Thanks! Bonus PR so people like me update Cypress BEFORE opening the bug ticket: https://github.com/cypress-io/cypress/pull/14536

**Comment by eric-burel** [comment]
Hmm @bahmutov actually it seems to fix the issue on the small repro code, but not on my more complex private code. I keep the issue closed until I have more info but I may be back at it in the future.

**Comment by eric-burel** [comment]
@bahmutov Ok I figured it out: the stub is destroyed only if the `expect` assertion is failing. I've updated the repro with a failing assertion. Confirmed on 6.2.1 too. Sorry for the back and forth.

**Comment by bahmutov** [comment]
Haha of course, sounds good Eric

**Comment by jennifer-shehane** [comment]
@eric-burel I would suggest updating to our new `cy.intercept()` command for fetch requests as it can likely handle this a lot nicer.

**Comment by eric-burel** [comment]
Excellent! Thank you for taking care of such tickets even when they are quite old. It works perfectly:
```ts
function mockGraphQL(stubs: Array<GraphqlQueryStub>) {
  cy.intercept({ method: "POST", path: "/graphql" }, request => {
    const postBody: any = request.body; // it's already a parsed JSON when application/json is used
    if (postBody?.operationName) {
      const { operationName } = postBody;
      console.log(
        `Detected a call on a graphql URL ${request.url} and operation ${operationName}`
      );
      const matchingStub = stubs.find(stub => operationName === stub.operation);
      if (matchingStub) {
        console.log("Found a stub for operation", matchingStub.operation); // eslint-disable-line no-console
        return request.reply({
          body: matchingStub.response
        });
      }
      console.log(
        `Could not find a stub for the operation ${postBody?.operationName}. Using original fetch.`
      ); // eslint-disable-line no-console
    }
  });
}
Cypress.Commands.add("mockGraphQL", mockGraphQL);
```
