### ISSUE TITLE
Timeouts running cypress on Travis

### ISSUE THREAD

**Issue by dracos** [cypress-io/cypress#1453]
### Is this a Feature or Bug?

Bug.

### Current behavior:

We've started using Cypress (thanks!) and have got it running locally and on Travis, but more than half of our Travis-run recordings fail to upload the video timing out:
```
 (Uploading Assets)
Warning: We encountered an error talking to our servers.
This run will not be recorded.
This error will not alter the exit code.
RequestError: Error: ETIMEDOUT
```
Is there anything that we can do (at either end) to try and make sure the output is uploaded correctly?

### Desired behavior:

Videos/screenshots are uploaded from Travis to Cypress without issue.

**Comment by bahmutov** [comment]
Hmm, weird, maybe there is flaky communication problem with our API and the timeout is too short.

**Comment by dracos** [comment]
In case it's helpful, our runs can be seen at https://dashboard.cypress.io/#/projects/y8vvs1/runs – of the 19 so far, 10 have timed out at the video upload. I don't think at that point it's doing anything out of the ordinary :)

**Comment by cbovis** [comment]
@dracos did you find a solution for this? Looking at the dashboard link you posted things look pretty reliable now.

Asking because I have the same issue... My first spec always fails to upload.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
