### ISSUE TITLE
Cy.Intercept() not working correctly falsely intercepting 

### ISSUE THREAD

**Issue by Alex-passiv** [cypress-io/cypress#14539]
### Current behavior
Im trying to stub a password reset request, in order to have it available for continuous testing and not send out repeated emails.

I run the script in cypress tool and it comes up successfully stubbed but then the email is still getting through! I'm not sure what i did wrong. 
### Desired behavior
I want it to stop the request from going through, i just want to verify it is being sent. Will Cypress not stop automatically or do I have to pass a response to the request?

### Test code to reproduce

`
 it('Reset Pass works', () => {
        cy.intercept('GET', '/api/v1/*')
        cy.intercept('POST', '/api/v1/auth/resetPassword/', req => {
            console.log('POST email sent', req)
        }).as('Reset')
        cy.intercept('https://app.passiv.com/app/reset-password').as('redirect')
        cy.contains('Reset').click()
        cy.get('input').click().type('asutherland8219@gmail.com')
        cy.get('button').contains('Reset').click()
    

    })
`

### Versions

Using most up to date cypress,  linux manjaro and firefox 

![image](https://user-images.githubusercontent.com/60415557/104487859-feee6a80-55a3-11eb-95b7-898c8361f750.png)

**Comment by jimmy882** [comment]
according to https://docs.cypress.io/api/commands/intercept.html
if you stub the response, for example like this
```
cy.intercept('POST', '/api/v1/auth/resetPassword/', {
  statusCode: 200,
  body: 'it worked!'
}).as('Reset')
```
then the request is NOT sent to the server and you can check that it's called like this
```
cy.get('button').contains('Reset').click()
cy.wait('@Reset')
```

**Comment by Alex-passiv** [comment]
ah yup that worked! I think my issue was in the syntax for the request response. Thanks for your help!
