### ISSUE TITLE
Add options to prune command

### ISSUE THREAD

**Issue by GregLahaye** [cypress-io/cypress#14548]
### What would you like?
We'd like some options added to the `prune` command that would allow some flexibility in regards to which versions it deletes. We would like to add this to our CI pipeline but would run into the issue where if two branches had different versions of Cypress running (e.g. one on 6.2.0 and one just updated to 6.2.1) that they would each delete the other install. 

I was thinking something along the lines of one option that would allow you to disable deleting higher versions (e.g. an old branch with Cypress 3.6.0 runs and doesn't kill our current version of 6.2.1) and an option to keep the last version or two of Cypress installed (e.g. one branch updates from 6.2.0 to 6.2.1 and it doesn't delete 6.2.0 as it is just one version behind).

### Why is this needed?
Allow running command as part of CI pipeline, see above.

<hr/>

I'd be willing to have a go at the PR if this feature sounds reasonable.

**Comment by bahmutov** [comment]
Ughh, I can see it being confusing. How about "tolerance" within minor / patch versions.

For example if you are running 6.2.1 you could say "I want to keep any 6 version, no matter if their minor version is different". So you would say

```
cypress cache prune --keep minor
deletes 5.6.0
deletes 5.5.0
keeps 6.0.0
keeps 6.1.0
keeps 6.2.0
keeps 6.2.1
``` 

Or you can say keep just the versions with different patch

```
cypress cache prune --keep patch
deletes 5.6.0
deletes 5.5.0
deletes 6.0.0
deletes 6.1.0
keeps 6.2.0
keeps 6.2.1
``` 

How about this? You can see the argument parsing in the `cli` folder source and add the new arg and use `semver` NPM package to compare versions to decide if needs to be pruned or kept

**Comment by bahmutov** [comment]
But in general, I suggest just basing your CI caching on the exact versions declared in the yarn.lock or package-lock.json files to avoid this problem altogether https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/

**Comment by GregLahaye** [comment]
@bahmutov  I ended up solving this by adding a script to our CI that will delete Cypress binaries that haven't been accessed in more than 14 days. We are running local build servers so unfortunately your article does not help as everything installed is kept. 

It made me think that it would be possible to introduce something an argument that would allow users to only prune files that haven't been accessed in x days (using the [atime property from fs.stat](https://nodejs.org/api/fs.html#fs_stats_atime)). Maybe something like `cypress cache prune --unused=14` or similar. It that a PR you'd be interested in? Otherwise, no worries and I'll close this issue.

**Comment by jasikpark** [comment]
It would be nice to have this feature so that there isn't churn when moving between Cypress versions..

**Comment by mjhenkes** [comment]
We'll be working automatic cache pruning as part of cypress provided browser binaries see issue #19703

**Comment by jennifer-shehane** [comment]
Closing since this hasn’t gotten a lot of interest over the years and the cypress provided browsers is not currently planned work.
