### ISSUE TITLE
triggers --page loaded – event while interacting with an elements

### ISSUE THREAD

**Issue by arunharihar** [cypress-io/cypress#14549]
### Current behavior
Page is getting automatically reloads and opens home page of the application, resulting test cases failure (CypressError: Timed out retrying) 

This is the error:
Note:   This event initially fires when your application fires its 'beforeunload' event and completes when your application fires its 'load' event after the next page loads.

![image](https://user-images.githubusercontent.com/77329177/104548854-a8426880-5657-11eb-8cac-8c454dab5544.png)

![image](https://user-images.githubusercontent.com/77329177/104548889-bf815600-5657-11eb-840f-ab5af334f50c.png)

### Desired behavior
During test cases execution, current page should not be reloaded to the home page of the application.

### Test code to reproduce
Not able to reproduce with exact code snippet.
But I could give same behavior below

    it('reload', function () {
        cy.visit('http://webdriverjsdemo.github.io/leave/')
        cy.contains('Go Home').click()
    })

Followed the below workaround which is mentioned in the issue https://github.com/cypress-io/cypress/issues/2118
but still page is getting reloaded to the home page of the application.

### Versions

Windows server 2016, Chrome or Electron, any version.
"devDependencies": { 
    "@cypress/skip-test": "^2.5.0",
    "cucumber": "^6.0.5",
    "cypress": "^4.8.0",
    "cypress-cucumber-preprocessor": "^2.5.0",
    "sybase": "^1.2.1"
  }

**Comment by bahmutov** [comment]
I am not sure I understand the issue. Some code on the page triggers the navigation event and you want to disable it during the test?

**Comment by arunharihar** [comment]
@bahmutov  Yes. to explain more on this issue, While am in the current page, test is performing actions like dropdown selection, tooltip etc.. page gets reload to Home page.

Even I tried applying my below workaround but still fails at dropdown selection/tooltip etc.. 
below workaround reduced failure count but fails frequently in CI.
Example: current page >> Clicks on dropdown >> reload the page to Home page >> then look for the options element of dropdown clicked


```
const chartPage = () => {
    ui.waitReady() 
    cy.get(`input[value="Health Check"`).click() //Navigates to current page where I want test steps to complete
    ui.waitReady()
}
const loadPage = () => {
    let currentPage
    ui.pageTitle().then(url => {
        currentPage = url.text()
        cy.log('Current Page Title : ' + currentPage)
        if (currentPage === 'Home') {
            chartPage()
        } else {
            cy.log('Already on chart page' + ui.pageTitle())
        }
    })
}
```

let us know if any workaround which we can apply to disable the navigation event.

**Comment by bahmutov** [comment]
So your app navigates (as it should, right? on clicking the "Health Check" link) and you want to disable it?

Maybe take a look at https://glebbahmutov.com/blog/cypress-tips-and-tricks/#deal-with-target_blank and at https://glebbahmutov.com/blog/cypress-tips-and-tricks/#deal-with-windowopen ?

**Comment by kbaala88** [comment]
@bahmutov : For a stable application, it displays "Browsers will not fire the load event until all stylesheets and scripts are done downloading" though the page is loaded and able to perform the operations manually. Looks like it is waiting for some backend call or loading to be completed and it waits forever. Noting that one websocket related call is displaying as pending while analyzed through dev tools. Any help here plz....! posted the same on Nov'20 but no luck! Thanks!

**Comment by arunharihar** [comment]
Our Application was scheduled in backend to reload the latest data from the database. hence in cypress was logs was showing 'page loaded' and getting error ''detached from DOM". this issue was with respect to application not cypress issue.
