### ISSUE TITLE
cy.Server() and cy.route are striked out

### ISSUE THREAD

**Issue by naveenr34** [cypress-io/cypress#14556]
Hi,

 cy.server();
 cy.route("POST", "/Account/Registartion").as("accountRegistration");

for the above both cy.server() and cy.route() are striked out, not sure what the issue is, it suddenly happend from today morning, an image of how it looks:
![image](https://user-images.githubusercontent.com/48453738/104596744-ac30b380-5674-11eb-86d3-85f64267b478.png)

could somebody help me and tell me what the issue might be?

Chrome 87
Version : Cypress 6.0.

**Comment by bahmutov** [comment]
These Cypress commands have been marked as deprecated in Cypress v6 https://on.cypress.io/changelog#6-0-0 and this is how your code editor shows these commands that have JSDoc attribute `@deprecated`

**Comment by naveenr34** [comment]
Thank you, I learnt it after going through documentation with the open eyes...
