### ISSUE TITLE
cy.intercept does not recognize match as function on intercepted request body. 

### ISSUE THREAD

**Issue by Wurby** [cypress-io/cypress#14568]
### Current behavior
![image](https://user-images.githubusercontent.com/28383214/104624928-644c6500-5651-11eb-8dda-89c0094e7d21.png)

### Desired behavior
Prior to updating from cypress 6.0.1 -> 6.2.1, the cy.route2 method enabled me to utilize a custom command to alias each intercepted event. This allowed me to track all events to a specific destination, catch the specific event I was testing, and then make assertions against it. 

### Test code to reproduce
```js
Cypress.Commands.add("trackEvent", (eventName: string, eventType: string, eventPath: string) => {
    const regexTerm = new RegExp(`\{\"tealium_event\"\:\"${eventType}\"`)
    
    return cy.intercept('POST', eventPath, (req) => {
      if (req.body.match(regexTerm)) {
        expect(req.body).match(regexTerm)
        req.alias = eventName
      }
    })
```

### Versions

Current: 6.8.0
Last Working: 6.0.1

**Comment by Wurby** [comment]
Still an issue on 7.1

**Comment by jennifer-shehane** [comment]
@Wurby What is the error printing in 7.1? 

The API has changed over time for cy.intercept, so something that was working before in cy.route2 may no longer be supported.

**Comment by Wurby** [comment]
I was getting the same error, but today it appears to be working on 7.1.0, so I am going to assume there was something wrong with my environment and close this. Thanks for following up.
