### ISSUE TITLE
Cypress not able to locate element using cy.get

### ISSUE THREAD

**Issue by Ppkd2021** [cypress-io/cypress#14566]
### Current behavior
In the below DOM we are trying to locate the heading using data-test-id but for some reason, it is not able to locate in the runtime but when search with the same selector is suggested selector it is able to uniquely identify.
![image](https://user-images.githubusercontent.com/59794856/104608576-0dbe4580-56a8-11eb-9ca9-b116eb574951.png)
![image](https://user-images.githubusercontent.com/59794856/104608655-27f82380-56a8-11eb-8437-bd235b64118c.png)
I am using cypress for other  #tests where modal is used and I did not find this issue there but in this specific case it's failing.

### Test code to reproduce

```js
it.only(`Verify user is able to use welcome new member template`, () => {
		cy.getDataTestId(`template-link-post-composer`)
			.should(`be.visible`)
			.should(`contain.text`, `Use a template`)
			.click();
		cy.getDataTestId(`heading-template-pop-up`).should(`be.visible`).should(`contain.text`, `Use a template`);
		cy.getDataTestId(`button-close-template-pop-up`).should(`be.visible`).click();
		cy.getDataTestId(`template-link-post-composer`)
			.should(`be.visible`)
			.should(`contain.text`, `Use a template`)
			.click();
		cy.getDataTestId(`template-welcome-new-members`)
			.should(`be.visible`)
			.within(() => {
				cy.getDataTestId(`heading-template-type`)
					.should(`contain.text`, `Welcome New Members (weekly)`)
					.should(`be.visible`);
				cy.getDataTestId(`description-template`)
					.should(`contain.text`, `Copy this post and use this weekly to welcome the new members of your group`)
					.should(`be.visible`);
				cy.getDataTestId(`button-view-template`).should(`be.visible`).should(`contain.text`, `View`).click();
				cy.getDataTestId(`view-template-pop`).should(`be.visible`);
				cy.get('[data-test-id="view-template-heading"]').should(`be.visible`);
				cy.getDataTestId(`view-template-heading`).should(`be.visible`).should(`contain.text`, `View template`);
				cy.getDataTestId(`template-name-view-pop-up`)
					.should(`be.visible`)
					.should(`contain.text`, `Welcome New Members (weekly)`);
			});
	});
```

### Versions

Cypress version - 6.2.1

**Comment by bahmutov** [comment]
Can I ask you to post the structure of your document? I am wondering where the `<body>` element is with respect to the `view-template-pop`

**Comment by Ppkd2021** [comment]
![image](https://user-images.githubusercontent.com/59794856/104685553-5cf48c80-5721-11eb-8187-d996b3e0bb59.png)
I hope this helps.

**Comment by Ppkd2021** [comment]
Scenario 1 Reproducible Steps:
1. User navigates to the main screen where the link is available that opens a pop-up.
Expectation met: All the elements we are able to test and steer in the above screen using cypress.
2. User click on the link that opens pop up.
Expectation met: All the elements we are able to steer in the pop-up.
3. User selects a feature from the above pop-up and which lands them on the main screen in the first step.
The expectation did not meet, The features we are able to steer and test in the first step successfully but not able to do the same after the third step.
Scenario 2 Reproducible Step:
1. User navigates to the main screen where the link is available that opens a pop-up.
Expectation met: All the elements we are able to test and steer in the above screen using cypress.
2. User click on the link that opens pop up.
Expectation met: All the elements we are able to steer in the pop-up.
3. User clicks on the button in the popup that opens another pop-up.
The expectation did not meet, In the above pop up we are not able to steer and test anything which is the issue we found originally because of which scenario one is also failing.

**Comment by bahmutov** [comment]
Nothing seems to be extra-ordinary from your description or screenshot. 

If you do `document.querySelector('...')` and use the CSS selector to find that popup element from the DevTools console, does it find it?

**Comment by bahmutov** [comment]
Hi @Ppkd2021 can you try finding the elements yourself - I have recorded a short video showing how to correctly use `document.querySelector` or `$` methods from the DevTools console https://youtu.be/pXpVAQZ-Gi4

**Comment by Ppkd2021** [comment]
Hi, @bahmutov  Yes using document.querySelector it's able to locate the element which cypress is not able to during runtime.
![image](https://user-images.githubusercontent.com/59794856/104882959-f0c89180-5989-11eb-8178-463e5a6e734a.png)

**Comment by bahmutov** [comment]
Does it take longer than the default command timeout to appear? Try putting a longer default command timeout to `cy.get` or globally. Also maybe use cy.pause command to step through the commands before the failing command?

**Comment by Ppkd2021** [comment]
No, it appears on the screen while the timeout is happening but still it is not able to locate. I tried using pause and hardcoded wait but no luck.
![image](https://user-images.githubusercontent.com/59794856/105574211-0de5d180-5d89-11eb-89a6-14ccafe3d821.png)

**Comment by arthurlewisbrown** [comment]
I've seen a lot of things in my day that has caused my hair's to turn grey
but not was more shocking then to see such an information phishing device
known as chrome bring used for code testing... Try brave browser good sir
and maybe then you can keep praying eyes out of the sandbox... By the way
... if you actually go back to your sandbox you might find the source of
your problem there ...

If you need any directions get lost or get stuck in the sand give me a
holler

**Comment by jennifer-shehane** [comment]
@Ppkd2021 Is your app built using Shadow DOM? May need to use `.shadow()` to traverse it. https://on.cypress.io/shadow

**Comment by myselfsrjn4u** [comment]
Can you try with cy.get('[data-test-id="view-templete-heading"]',{withinSubject:null})... ..

**Comment by Ppkd2021** [comment]
@jennifer-shehane Its not.

**Comment by Ppkd2021** [comment]
@myselfsrjn4u  Let me try it.

**Comment by filipedanunes** [comment]
can you please explain this?

**Comment by filipedanunes** [comment]
> @Ppkd2021 Can you try with this ---> cy.get('[data-test-id="view-templete-heading"]',{withinSubject:null})

Can you please explain this? It seems to solve a similar problem

**Comment by Ppkd2021** [comment]
@myselfsrjn4u  Thanks for the above solution that you mentioned worked. :)

**Comment by neil-r-b** [comment]
For others who stumble across this issue, as I was suffering from the same exact problem. The suggestion to use `withinSubject:null` from @myselfsrjn4u does work although to add more color from the docs this does:
```
Element to search for children in. If null, search begins from root-level DOM element
```

Which clued us in to the mistake we were doing in code - it is due to checking for the existence of the modal in a `within()` block. This has cypress searching the DOM from that point but the modal is outside of it. So an alternative to using `withinSubject:null` is to check for existence outside of the `within()` block.

**Comment by simon-chen-1** [comment]
Thanks @myselfsrjn4u & @neil-r-b, I ran into this issue today and your solution worked!

**Comment by mcheung610** [comment]
This works for me as well. Thank you guys!

**Comment by sophiehongcai** [comment]
> For others who stumble across this issue, as I was suffering from the same exact problem. The suggestion to use `withinSubject:null` from [@myselfsrjn4u](https://github.com/myselfsrjn4u) does work although to add more color from the docs this does:
> 
> ```
> Element to search for children in. If null, search begins from root-level DOM element
> ```
> 
> Which clued us in to the mistake we were doing in code - it is due to checking for the existence of the modal in a `within()` block. This has cypress searching the DOM from that point but the modal is outside of it. So an alternative to using `withinSubject:null` is to check for existence outside of the `within()` block.

Many many thanks!!! This solved my problem!!!
