### ISSUE TITLE
https://cypress.io/ is down --> TIMEOUT error

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1457]
Hi,

I wanted to access to your website https://cypress.io/ but he is actually down. I get ERR_CONNECTION_TIMED_OUT (OS: Mac Sierra, site: FRANCE)

Regards,
Elisa

**Comment by leosuncin** [comment]
The site is up https://isdown.me/www.cypress.io

**Comment by perceboisElisa** [comment]
Hi, Yes I agree with you. Thanks
