### ISSUE TITLE
Adding Time Markers within a Test for Cypress Dashboard Reporting

### ISSUE THREAD

**Issue by mleonard0826** [cypress-io/cypress#14588]
### What would you like?

I have a test involve a sequence of three API calls and would like to be able to track the time required for each call via Cypress dashboard. For our purposes, we want to keep all three calls within a single 'it' test execution. I can see on the dashboard there is a section labeled performance that has a blue bar with the total execution time for each test - is there away to create markers in a test run, such that the bar can be broken down into segments representing the duration of time between each marker? In the case I described it would help me capture data about API performance. In other cases we have planned, it'd help me collect statistics on page load times from a large batch.

This could also be used in a UI test to evaluate how long it takes to navigate through each screen.

### Why is this needed?

This functionality would greatly expand the utility of Cypress for my organization and make it invaluable as a performance monitoring tool for our APIs and UI applications.

**Comment by jennifer-shehane** [comment]
This may be helpful, seeing the timings of each commands. https://glebbahmutov.com/blog/cypress-timings/

I'd need an example use case to really understand exactly what timing you want to see if it's outside of what the blog covers above.
