### ISSUE TITLE
Check for file and directory names

### ISSUE THREAD

**Issue by alewolf** [cypress-io/cypress#14589]
### What would you like?

Today I ran into an issue when I released a new version of my app to thousands of users. 

I added some new directories with php files into my app and all worked fine on my test machine. 

But, for some users the update broke their website. 

The reason was, that I named one folder with a capital letter like so `Example` instead of `example`.

My autoloader was working fine on my system because it is not capitalization sensitive. But other servers don't ignore capitalization and throw errors. 

Is there a way in Cypress to test all my file and folder structure for capitalization? 

If not, could you add this feature?

Thanks

**Comment by bahmutov** [comment]
I am not sure I understand what Cypress can do in this case? What is the observable effect of the folder name written as "Example" vs "example"? Is the URL uppercase? I suspect a better approach would be to have a linter or a commit script (or a CI task) that checks all files in the repo to have consistent casing)
