### ISSUE TITLE
download.cypress.io gives an .exe when you ask for Linux

### ISSUE THREAD

**Issue by JonathanDWood** [cypress-io/cypress#1458]
Operating System: Ubuntu 16
Browser Version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)

### Current behavior:
When navigating to: https://download.cypress.io/desktop?platform=linux64

the zip file downloaded contains an .exe

### Desired behavior:
Expected a Linux executable

### Additional Info (images, stack traces, etc)
![image](https://user-images.githubusercontent.com/20028526/37405996-7d43aa26-276c-11e8-8989-1acfe1f2a04c.png)

**Comment by Bkucera** [comment]
Not sure I understand, it looks like a linux executable to me. Have you tried running it?

**Comment by JonathanDWood** [comment]
Haha oh god. I have been using Wine for windows .exe files on Ubuntu and I haven't had any coffee yet :coffee: :sweat_smile: 

Thanks for your patience
