### ISSUE TITLE
cy.tick intermittently doesn't work

### ISSUE THREAD

**Issue by afosterget** [cypress-io/cypress#14594]
We use the following code to move the clock forward 10 minutes, and then test to make sure the UI is responding correctly. 

```js
  cy.clock();
  const now = new Date().getTime();
  const minutesToMoveForward = 10;
  const timeToMoveTo = now + minutesToMoveForward * 60 * 1000;
  cy.tick(timeToMoveTo);
```

The test log seems to show that the tick is working:
```
clock 12
tick 1610738408423ms
```

But, when the test runs, sometimes it passes and sometimes it doesn't. The UI sometimes looks like 10 minutes has passed and sometimes looks like only 2 seconds has passed. Is there a fix for this, or another method that would work?

**Comment by jennifer-shehane** [comment]
@afosterget Can you provide a full example? I'm not sure why this wouldn't work something. You'll want to make sure to call cy.clock() before you call any cy.visit() command.

**Comment by flotwig** [comment]
Closing since no example was provided.
