### ISSUE TITLE
Cypress doesnt work with maps based autocomplete

### ISSUE THREAD

**Issue by developdeez** [cypress-io/cypress#14598]
I am trying to use Cypress as a testing tool for an React website I am working on. One of the tests is for a location search, which uses the google places service to autocomplete locations. Functioning correctly, it looks like in the picture below:
![image](https://user-images.githubusercontent.com/13059525/104793488-b1b2fa00-5757-11eb-9dc8-2c6147e2d283.png)

### Current behavior
Cypress doesn't load suggestions from Google Places, MapBox, or any other autocomplete.

### Desired behavior
If should load the autocomplete suggestions

### Test code to reproduce
Made a test of the autocomplete. Not sure how to add cypress as it is my first time using codesandbox
https://codesandbox.io/s/delicate-microservice-k58c1?file=/src/index.js

Feel free to add if you have a harness.

### Versions

"cypress": "^6.2.1"

**Comment by bahmutov** [comment]
Please make a reproducible example for us to investigate. Without a reproducible example we cannot say anything. Even without a reproducible example when opening an issue you can paste screenshots and videos of the failing test showing the problem.

**Comment by developdeez** [comment]
@bahmutov 
I've updated my ticket. not sure how to run cypress in codesandbox but thats the tool used in react

**Comment by chghulamnabi** [comment]
I am also facing same issue with Cypress 6.2.1

**Comment by bahmutov** [comment]
@developdeez did you forget to add your code to the sandbox? 

<img width="1440" alt="Screen Shot 2021-01-16 at 12 36 32 PM" src="https://user-images.githubusercontent.com/2212006/104818751-8c75c880-57f7-11eb-8ef8-5ff0f1e2c674.png">

Maybe create a public repo instead and post a link?

**Comment by developdeez** [comment]
@bahmutov that's weird I thought I added it and saved. I updated and it shows a textbox on mine.

Just in case I put this in App.js

`import React, { useState } from "react";
import "./styles.css";
import PlacesAutocomplete from "mb-places";

export default function App() {
  const [address, setAddress] = useState();
  const handleAddress = (newAddress) => {
    setAddress(newAddress);
  };
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <PlacesAutocomplete
        value={address}
        onSelect={handleAddress}
        onChange={handleAddress}
      >
        {({ getInputProps, suggestions, getSuggestionItemProps, loading }) => {
          return (
            <div className="search" style={{ position: "relative" }}>
              <div style={{ display: "flex" }}>
                <input
                  id="search-location"
                  aria-label="search location"
                  autocomplete="off"
                  {...getInputProps({
                    className: "location-search-input"
                  })}
                />
              </div>
              <div className="autocomplete-dropdown-container">
                {loading && (
                  <div
                    className="suggestion-item"
                    style={{ backgroundColor: "#ffffff" }}
                    key="loading"
                  >
                    "Loading"
                  </div>
                )}

                {suggestions.map((suggestion, idx) => {
                  const style = suggestion.active
                    ? { backgroundColor: "#fafafa", cursor: "pointer" }
                    : { backgroundColor: "#ffffff", cursor: "pointer" };

                  if (idx !== suggestions.length - 1) {
                    return (
                      <div
                        {...getSuggestionItemProps(suggestion, {
                          className: `${
                            suggestion.active
                              ? "suggestion-item--active"
                              : "suggestion-item"
                          }`,
                          style
                        })}
                        key={suggestion.id}
                      >
                        <strong>{suggestion.main}</strong>{" "}
                        <span>{suggestion.rest}</span>
                      </div>
                    );
                  } else {
                    return (
                      <>
                        <div
                          key={suggestion.id}
                          {...getSuggestionItemProps(suggestion, {
                            className: `${
                              suggestion.active
                                ? "suggestion-item--active"
                                : "suggestion-item"
                            }`,
                            style
                          })}
                        >
                          <strong>{suggestion.main}</strong>{" "}
                          <span>{suggestion.rest}</span>
                        </div>
                      </>
                    );
                  }
                })}
              </div>
            </div>
          );
        }}
      </PlacesAutocomplete>
    </div>
  );
}
`

**Comment by developdeez** [comment]
Bump

**Comment by bahmutov** [comment]
<img width="1275" alt="Screen Shot 2021-01-23 at 2 06 38 PM" src="https://user-images.githubusercontent.com/2212006/105611607-43d48700-5d84-11eb-931f-f00aa8605890.png">

**Comment by bahmutov** [comment]
See the solution in https://github.com/bahmutov/cypress-geolocation-example 

I will keep this issue open until I show how I went about debugging this, and how to check the geolocation issue

**Comment by bahmutov** [comment]
Full explanation in addition to the updated repo in this blog post https://glebbahmutov.com/blog/cypress-geolocation/

**Comment by bhadmus** [comment]
I have a similar issue. The Cypress Runner makes the Ajax calls (when I proceeded to search manually ) but the test still does not show the auto complete

https://user-images.githubusercontent.com/29228964/123115691-2fcaa980-d438-11eb-87d5-6ed1bd15eee8.mp4

How do I address this?
