### ISSUE TITLE
"Login" is a noun, not a verb (grammar)

### ISSUE THREAD

**Issue by lorennorman** [cypress-io/cypress#146]
The Cypress login button should read "Log In with Github" instead of "Login with Github":
![image](https://cloud.githubusercontent.com/assets/17697/15399321/2dd3b87c-1db5-11e6-8a55-f67deffec94e.png)

When I get confused which is which, I think of how I would ask to be logged in. "Login me" or "Log me in"? Ah, right.

Reference:
http://grammarist.com/spelling/log-in-login/

**Comment by jennifer-mann** [comment]
Fixed in 0.16.1.

**Comment by brian-mann** [comment]
Fixed in [`0.16.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0161-05222016).
