### ISSUE TITLE
Update onboarding modal to reflect new scaffolding

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1460]
I was initially opening this issue for the updates being made to kitchen-sink in 3.0.0 here: https://github.com/cypress-io/cypress-example-kitchensink/pull/40 The onboarding modal should display a folder called `examples` instead of a file called `example_spec.js`

But, I realize that this was never updated after adding the plugins folder/file, so this modal also needs to be updated to reflect that. 

**Current onboarding dialog**
![screen shot 2018-03-14 at 1 14 22 pm](https://user-images.githubusercontent.com/1271364/37419060-066555f8-278a-11e8-910b-1ca320898b10.png)

**Comment by jennifer-shehane** [comment]
K, I'm wrong about the plugins folder - we actually display this from an array called `scaffoldedFiles` which looks to be updated. Our fixture was not updated however, which is why that screenshot from a test was incorrect. - Updating that fixture file now.

I am also noticing that the text above the folders is generated with keys sent in the project's `config` that is returns in `ipc.openProject` that will need to be updated / rethought. Specifically:

```
"integrationExampleFile": "/Users/jane/Dev/Projects/my-app/cypress/integration/example_spec.js",
"integrationExampleName": "example_spec.js",
```

This is now just a folder, so should return "integrationExampleFolder"? @brian-mann 

**Up to date onboarding dialog**
![screen shot 2018-03-14 at 1 38 52 pm](https://user-images.githubusercontent.com/1271364/37420416-1a3e8f06-278d-11e8-85c0-5759538dba76.png)

**Comment by chrisbreiding** [comment]
@jennifer-shehane Here's the latest modal. I didn't really like the closed examples folder, so I went with having it open but truncating the files. Let me know what you think. 

![screen shot 2018-05-10 at 9 48 38 am](https://user-images.githubusercontent.com/1157043/39872915-7b8304aa-5437-11e8-9a08-153233d2c854.png)

**Comment by jennifer-shehane** [comment]
Yeah, I mean this is more explicit about what's actually happening. 👍
