### ISSUE TITLE
Something went wrong while displaying the webpage

### ISSUE THREAD

**Issue by nehalbadelhafez** [cypress-io/cypress#14605]
Current behavior
After increasing the timeout of the fixture to upload a large video, suddenly the page turns white with this message. Also, this happens a lot not only with fixture command but with a number of test cases run after each other.
version
6.2.1

![Screenshot from 2021-01-14 16-08-45](https://user-images.githubusercontent.com/65114493/104845252-03d15800-58dd-11eb-8d91-023b38f80a75.png)

**Comment by nehalbadelhafez** [comment]
any help?

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nehalbadelhafez** [comment]
here is a reproducible example. Also, i change default command timeout to 600000 which is equivalent to 10 minutes
it("Add three plugins within one job", function () {
 // login 
  cy.login(url, email, password);
  
  // create 3 media
  for (var iterator= 0; iterator < pluginNames.length; iterator++) {
    var mediaName1 = "media " + iterator;
    cy.createMedia(mediaName1, inputMediaNames[iterator]);
    cy.reload();
  }
  //create job
  cy.createJob(jobName);
  //add plugins and media within the job
  for (var iterator= 0; iterator < pluginNames.length; iterator++) {
    cy.addPlugin(pluginNames[iterator]);
    cy.reload();
    cy.addMedia(mediaName + iterator, pluginNames[iterator]);
    
  }
  cy.startJob(jobName);
  cy.connectWithWebSocket(jobName, status);
  cy.log("Run three plugins within one job finishes successfully");
});
the function declaration is at the commands js file this example is for the websocket connection 
Cypress.Commands.add("connectWithWebSocket", function (jobName, status) {
  var options = {
    takeWhileFn: (payload) => {
      if (payload) {
        if (payload.type) return true;
        if (payload.message) {
          if (payload.message.data) {
            let data = JSON.parse(payload.message.data);
            if (data && data.name === jobName) {
              if (data.status) {
                if (data.status.type === status) {
                  return false;
                } else if (data.status.type == "stopped") {
                  return false;
                }
              }
              return true;
            }
          }
        }
      }
      return false;
    },
    startUpMessage: {
      command: "subscribe",
      identifier: '{"channel":"JobsChannel"}',
    },
  };
  cy.streamRequest(config, options).then((results) => {
    const result = results && results[results.length - 1];
    console.log(result);
    var data = JSON.parse(result.message.data);
    if (data.status.type == status) {
      cy.log(expect(data.status).to.have.property("type", status));
    } else if (data.status.type == "stopped") {
      cy.log(" job has stopped !");
    } else {
      cy.log("something went wrong");
    }
  });
});

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end - we cannot run the first step, which is the login. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
