### ISSUE TITLE
window:before:unload handler triggered before app's unload handler

### ISSUE THREAD

**Issue by jbojcic1** [cypress-io/cypress#14614]
### Current behavior
According to the docs:
`Fires when your application is about to navigate away. The real event object is provided to you. Your app may have set a returnValue on the event, which is useful to assert on`

but it seems that this event handler is called before the beforeunload handler in the app which sets the return value so I can't assert if value has been set correctly.

### Desired behavior
My understanding of the docs is that cypress handler should be called after and there I'd be able to see if return value has been set or not.

### Test code to reproduce
https://github.com/jbojcic1/cypress-test-tiny/tree/before-unload-example

Just run the only test. App code can be seen here:

https://codesandbox.io/s/modern-mountain-1vd73?file=/index.html

### Versions

6.2.1

**Comment by jennifer-shehane** [comment]
window before:unload event docs: https://on.cypress.io/catalog-of-events#App-Events

Yeah, this doc was written a long time ago, but I'm guessing it was written in the context of this test, which we had an example of checking that the `returnValue` was undefined. https://on.cypress.io/catalog-of-events#Test-that-your-application-was-redirected

But the wording of the doc sure makes it sound like the Cypress event should fire later in the unload event. I'll have to check on the intent of the code originally to know whether this is desired behavior.

**Comment by jbojcic1** [comment]
MDN  docs for onbeforeunload say: 
`When this event returns (or sets the returnValue property to) a value other than null or undefined, the user will be prompted to confirm the page unload.`

Since it cypress doesn't show unload window at all (which can be seen from the example I provided above), the only way I see to test if my page will show the unload window is to assert if  return value has been set. If cypress event is triggered only after the app's event which sets the value then I don't see how I can test this with cypress at all.

**Comment by jennifer-shehane** [comment]
The intent is for Cypress code within the `window:before:unload` to run before the applications code's unload code runs, so this appears to be a bug.

**Comment by lucas9122** [comment]
@jennifer-shehane Is it still unresolved? I am facing the same issue and I want to test the return value somehow
