### ISSUE TITLE
Certain Cookies Left Out When Setting Cypress.Cookies.defaults after using Puppeteer Cypress Plugin

### ISSUE THREAD

**Issue by InvisibleExo** [cypress-io/cypress#14617]
I'm testing with cookies to figure out ways to speed up the login process. I'm using a plugin: 'cypress-social-logins', which uses Puppeteer to perform sign in step to retrieve Cookies, ssd, and lsd which can be returned from a cy.task(). (Using http://store.steampowered.com/ as my site to explore automating with Cypress.) (Sign in with visit() or request() doesn't work  with this site.) The cypress-social-logins plugin is able to login and I see the cookies returned to me. [Here](https://gist.github.com/InvisibleExo/3554b373f163f61b5db478ea000ce98c)

However, when I perform Cypress.Cookies.defaults ({ preserve: <cookieName>}), then do a reload, notice that my test account isn't signed in. 

### Current behavior

While inspecting cookies under Application tab in Dev tools, I see a few cookies missing which include HttpOnly Attribute. See image. 
![image](https://user-images.githubusercontent.com/22781723/104968927-0fd01f00-599c-11eb-9a76-4131de3ca18b.png)

I get the strange feeling that the missing cookies with the HttpOnly attribute is the cause why I don't see my test account signed in. I tried looking up docs or posts if this is an expected behavior, but I'm couldn't a clear answer on the topic. I don't know if there is another factor I'm missing or if this is out of my reach for sign in process with this site.

### Test code to reproduce

Code to reproduce: [here](https://gist.github.com/InvisibleExo/d4aeef0ad7674fc99bd3256565ce1b3b)

**Comment by emilyrohrbough** [comment]
In the upcoming v12.0.0 release, the deprecated `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` will be removed. This has been related with [`cy.session()`](https://docs.cypress.io/api/commands/session). Closing as won't fix.
