### ISSUE TITLE
Writing E2E tests is almost impossible due to the restriction while navigating to an integrated system

### ISSUE THREAD

**Issue by rakeshnambiar** [cypress-io/cypress#14616]
### Current behavior

Writing E2E tests is almost impossible due to the restriction while navigating to an integrated system.
Test flow:
- Go to https://europepmc.org/accounts/login
- Click on `Sign in with ORCID` button

`Error message`

```
Cypress does not allow you to navigate to a different origin URL within a single test.
```

### Desired behavior
Other tools like Selenium or protractor support to interact with the elements on the newly navigated page.

### Test code to reproduce
```javascript
context('Login', () => {
    beforeEach( () => {
        cy.visit('https://europepmc.org/accounts/login')
        cy.get('#data-protection-agree').click()
    })

    it('Verify ORCID Login', () => {
        cy.get('#orcid--signin-button').click()
        cy.get('#username').type('xxxxx@gmail.com')
    })
})
```

### Versions
`"cypress": "^6.2.1"`

**Comment by Narretz** [comment]
Well, this is one of Cypress' main and well documented drawbacks. You can work around this by diasbling webSecurity in Chrome. https://docs.cypress.io/guides/guides/web-security.html#Set-chromeWebSecurity-to-false

And the usual suggestion is to not test the login via the ui.

**Comment by rakeshnambiar** [comment]
Thanks @Narretz  That helps .. I am from Protractor-selenium background and new to Cypress :)

**Comment by rakeshnambiar** [comment]
Hi @Narretz sorry for the delayed feedback. I tried this with the `"chromeWebSecurity": false,` and getting the below mentioned error. This is not just to test the login feature. Instead I need to claim an article after login to the ORCID as part of the E2E flow.

Here's the UI flow in case you wish to take a look:
- Go to http://europepmc.org/orcid/import
- Click `Start` button


![image](https://user-images.githubusercontent.com/20258636/144864212-d572dc7a-748b-42ad-82f8-86d32faff881.png)
