### ISSUE TITLE
material-multi-picker item requires 2 clicks for the item to be selected

### ISSUE THREAD

**Issue by GCHQDeveloper911** [cypress-io/cypress#14615]
### Current behavior
Currently when using the material-multi-picker component, you can type something into the input to filter the list of options. However, it then takes 2 cypress click() events to trigger the click on the list item correctly.

### Desired behavior
Just like when driving the UI manually, a single click on the list item should be sufficient to select it

### Test code to reproduce
Simple Cypress test:
```js
describe ('Scratch', function () {
  beforeEach(() => {
    cy.visit('https://atropos-tech.github.io/material-multi-picker/index.html')
  })

  it('Does stuff', function () {
      cy.get('#downshift-0-input').type('app')
      cy.get('li').contains('apple').click().click();  // shouldn't need the second click() here
  })
})
```
### Versions
Tried with Cypress 5.5 and 6.1, and Chrome 87 on CentOS

**Comment by jennifer-shehane** [comment]
I can recreate this issue. This doesn't look like a regression as I was able to reproduce this in 3.8.1 as well.

```js
it('Selects apple', () => {
  cy.visit('https://atropos-tech.github.io/material-multi-picker/index.html')
  cy.get('#downshift-0-input').type('app')
  // shouldn't need the second click() here
  cy.get('li').contains('apple')
  .click({ scrollBehavior: 'center'})
  .click({ scrollBehavior: 'center' })
  cy.get('#downshift-0-input').parent().contains('apple')
})

it('Does not select apple', () => {
  cy.visit('https://atropos-tech.github.io/material-multi-picker/index.html')
  cy.get('#downshift-0-input').type('app')
  cy.get('li').contains('apple')
  .click({ scrollBehavior: 'center' })  
  // fails, did not click to select with only one click
  cy.get('#downshift-0-input').parent().contains('apple')
})
```

### Click twice

<img width="837" alt="Screen Shot 2021-01-20 at 3 16 58 PM" src="https://user-images.githubusercontent.com/1271364/105150082-b1897480-5b32-11eb-85bd-4cf2afccd34d.png">

#### Mouse events

<img width="884" alt="Screen Shot 2021-01-20 at 3 20 27 PM" src="https://user-images.githubusercontent.com/1271364/105150359-11801b00-5b33-11eb-92fe-daa2b822c733.png">


### Click once

<img width="955" alt="Screen Shot 2021-01-20 at 3 17 14 PM" src="https://user-images.githubusercontent.com/1271364/105150098-b77f5580-5b32-11eb-8bb6-6f5ab03e330e.png">

#### Mouse events for single click

<img width="881" alt="Screen Shot 2021-01-20 at 3 18 39 PM" src="https://user-images.githubusercontent.com/1271364/105150192-d7167e00-5b32-11eb-8aa3-3cb5111307ac.png">
