### ISSUE TITLE
Cypress dashboard reset password doesn't send email

### ISSUE THREAD

**Issue by karthikamirapu** [cypress-io/cypress#14618]
I tried to reset the my cypress dashboard password multiple times but I am not getting the email .

**Comment by jennifer-shehane** [comment]
Hey @karthikamirapu, sorry to hear you're having difficulty resetting your password. Can you send us an email at support@cypress.io, letting us know what email address you're trying to reset the password for so that we can investigate.

**Comment by jennifer-shehane** [comment]
Closing since this requires followup through email.
