### ISSUE TITLE
Commands in promise chains' primitive arguments' values don't reflect updates made in previous promises

### ISSUE THREAD

**Issue by zachwildd** [cypress-io/cypress#14625]
### Current behavior

Commands in promise chains' primitive arguments' values don't reflect updates made in previous promises.

### Desired behavior

The desired behavior would be for the values passed to commands to reflect updates made to variables in previous promises.

### Test code to reproduce

```javascript
let someObject = 'some'
let otherObject = 'other'

cy
  .fixture('someObjects').then((someObjects) => {
    someObject = someObjects[0] 
  })
  .fixture('otherObjects').then((otherObjects) => {
    otherObject = otherObjects[0]
  })
  .customCommand(someObject, otherObject)
```

Value of someObject and otherObject in customCommand will be 'some' and 'other'.

### Versions

Cypress 6.2.0

**Comment by jennifer-shehane** [comment]
In the example given, the `someObject` and `otherObject` are evaluated immediately. This is from mixing async commands with synch values. 

I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).

```js
Cypress.Commands.add('customCommand', (someObject, otherObject) => {
  expect(someObject).to.eq('changed') // is 'some'
  expect(otherObject).to.eq('object') // is 'object'
})

it('test', () => {
  let someObject = 'some'
  let otherObject = 'other'

  cy.wrap('someObjects').then((someObjects) => {
      someObject = 'changed'
    })
  cy.wrap('otherObjects').then((otherObjects) => {
      otherObject = 'object'
    })
  // someObject and otherObject evaluate immediately
  // before the cy.wrap() commands have run above
  cy.customCommand(someObject, otherObject)
})
```

### To fix:

```js
Cypress.Commands.add('customCommand', (someObject, otherObject) => {
  expect(someObject).to.eq('changed') // passes
  expect(otherObject).to.eq('object') // passes
})

it('test', () => {
  let someObject = 'some'
  let otherObject = 'other'

  cy.wrap('someObjects').then((someObjects) => {
      someObject = 'changed'
    })
  cy.wrap('otherObjects').then((otherObjects) => {
      otherObject = 'object'
    }).then(() => {
      // this runs after values have been set
      cy.customCommand(someObject, otherObject)
    })
})
```

**Comment by zachwildd** [comment]
I should have tagged this as a feature request instead of a bug. 

Is this possible, it's not an issue for me, but I assumed the arguments were being evaluated when cypress builds some internal command queue, as opposed to them being evaluated when the command is executed.

**Comment by jennifer-shehane** [comment]
@zachwildd Yeah, there's some discussion in this thread because this is a pretty common confusion point for how our API is executed honestly. https://github.com/cypress-io/cypress/issues/1417
