### ISSUE TITLE
API - request oauth 1.0

### ISSUE THREAD

**Issue by bbonevPIT** [cypress-io/cypress#14638]
Hi everyone, 
I hope everyone is well and keeping safe. Its my second post still newbie so please bear with me. I will try to explain in depth as much I can. 

**Problem**
I tried many different ways but keep getting 401 cannot authorise to get the tokens successfully on cypress. I tried passing everything in the header same as in postman but still no luck. I am very stuck and would appreciate if anyone could help or suggest please.

**Details:**
API  method GET endpoint - /auth/oauth/request_token 
OAuth 1.0 version
Postman - 
1. set get and add endpoint
2. authorization change to oauth1.0 then add Consumer Key and Consumer Secret
3. then press sent status 200

postman screenshots and export of json format
![screenshot1](https://user-images.githubusercontent.com/61020069/105080489-c8738c80-5a88-11eb-8ea7-dda0ce084bfc.png)
![screenshot](https://user-images.githubusercontent.com/61020069/105080493-c9a4b980-5a88-11eb-9500-14ee183f0fe4.png)
![screenshot3](https://user-images.githubusercontent.com/61020069/105080494-c9a4b980-5a88-11eb-8e91-3d7171b9d839.png)

Example of the endpoint returning - oauth_callback_confirmed=1&oauth_token=xxxxxx1&oauth_token_secret=xxxx1&xoauth_token_ttl=3600

**cypress current code**
```js
describe('step 1 - request token', function () {

  it('step 1 - request token', function() {
    cy.request({
      method: 'GET',
      url: 'https://example.com/auth/oauth/request_token',
      
  headers: {
    'Authorization': 'OAuth 1.0',
    'Authorization:oauth_consumer_key': 'xxxx',
    'Authorization:oauth_consumer_secret': 'xxxx',
    'Authorization:oauth_signature_method': 'HMAC-SHA1',
   },
   
   failOnStatusCode: false
}).then((res) => {
    expect(res.status).to.equal(200)
})
})
})
```

**Comment by bbonevPIT** [comment]
I figured out the solution.

**Comment by itsmelibin** [comment]
Hi @bbonevPIT 

How did you solve this? I am getting error 
"> TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token ["Authorization:oauth_consumer_key"]"

**Comment by mischabraam** [comment]
What was the solution?
