### ISSUE TITLE
tailwindcss causing performance issues

### ISSUE THREAD

**Issue by m1yon** [cypress-io/cypress#14639]
### Current behavior
When tailwindcss is imported, the cypress runner runs at about 5 fps with 100% cpu usage. If I don't import the tailwindcss file, the test runner framerate and cpu usage is perfect.

### Desired behavior
No performance issues and normal cpu usage.

### Versions
Cypress: **6.2.1**
react: **17.0.1**
tailwindcss: **npm:@tailwindcss/postcss7-compat@^2.0.2**
@craco/craco: **6.0.0**

**Comment by jennifer-shehane** [comment]
@m1yon Where are you importing tailwindcss? Are you importing it into your specfiles or is it just a part of the application under test?

Can you provide a reproducible example?

**Comment by m1yon** [comment]
I actually fixed this issue by adding `"numTestsKeptInMemory": 0` to my `cypress.json` config. Thanks!
