### ISSUE TITLE
cypress.env.json is not being watched for changes

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1464]
- Cypress Version: 2.1.0

### Is this a Feature or Bug?

Bug

### Current behavior:

When creating the `cypress.env.json`, it isn't being read. Closing browser with test does not help. You have to exit whole Test runner and then it works again. Also changing values in the existing file won't be noticed. Original issue pointed out here: https://github.com/cypress-io/cypress-documentation/pull/444

### Desired behavior:

Watch changes in `cypress.env.json` file. It looks like Cypress only watching `cypress.json` here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/project.coffee#L219

**Comment by elamurugan-r** [comment]
In `Cypress10`, Is there a way to have the `cypress.env.json` file in some other name like `cypress.test.env.json`? If so how it should be configured ?
