### ISSUE TITLE
Studio unable to save to files with special characters in path

### ISSUE THREAD

**Issue by panzarino** [cypress-io/cypress#14659]
### Current behavior
Studio throws an error when trying to save to files that have a space somewhere in their path. If the space is removed, the saving works fine. I assume that a similar thing could be happening with `open in ide` since they share some of the same logic here but I'll have to test that.

### Desired behavior
Studio should be able to save to all file names.

### Test code to reproduce
See comment below

Originally reported by @ChaseBig https://github.com/cypress-io/cypress/discussions/14339#discussioncomment-297047

**Comment by jennifer-shehane** [comment]
Specs with special characters also encounter this error - I know you'll get some people with Chinese/foreign characters with this error. Not sure about emoji 😅 

And yes, the Open in IDE button in the reporter does not work for any of these files also

<img width="358" alt="Screen Shot 2021-01-21 at 11 56 52 AM" src="https://user-images.githubusercontent.com/1271364/105283960-ddaeff00-5bdf-11eb-9a58-9a6a543188e7.png">

Shows error:

>Cypress was unable to save these commands to your spec file. Cypress Studio is still in beta and the team is working hard to resolve issues like this. To help us fix this issue more quickly, you can provide us with more information by clicking 'Learn more' below

<img width="922" alt="Screen Shot 2021-01-21 at 11 55 03 AM" src="https://user-images.githubusercontent.com/1271364/105283794-93c61900-5bdf-11eb-837e-43e7039144c5.png">
