### ISSUE TITLE
Optional extra video record time on failure

### ISSUE THREAD

**Issue by JoseAlban** [cypress-io/cypress#14652]
### What would you like?
An optional config eg `videoRecordAfterFailureSeconds=30` that would allow videos to show DOM changes after a failure occurs

### Why is this needed?
If a failure has to do with non-sufficient timeouts, then that'd help a lot on answering the question: Would it succeed eventually if we increased the timeout?

**Comment by c32hedge** [comment]
Why not just increase the timeout in that failure case to see if it would eventually succeed? Seems like it would be a big slowdown for Cypress to have to wait to record an extra 30 seconds of video after every failure, regardless of the failure cause, before proceeding with the next test?

**Comment by bahmutov** [comment]
Imagine a test like this one - it fails

```js
describe('page', () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
    cy.wrap(false, {timeout: 100}).should('be.true')
  })
})
```

What you want to do is have an `afterEach` hook - in the same spec file, or better in the support file, so it applies to every test

```js
afterEach(function () {
  if (this.currentTest.state === 'failed') {
    cy.wait(5000)
  }
})
```

This is the video it captures, notice the five-second addition for the failing test.


https://user-images.githubusercontent.com/2212006/106038079-798baf80-60a5-11eb-9941-b017919f3365.mp4

I think this should be enough to support your case
