### ISSUE TITLE
window.open + redirect  error

### ISSUE THREAD

**Issue by jngchd** [cypress-io/cypress#14651]

**Comment by bahmutov** [comment]
Please fill our issue template when opening an issue

**Comment by jngchd** [comment]
logon.html
<input type="button" class="button_submit" id="btn_submit" value="logon" onclick="doSubmit()">

logon.jsp
request:
POST http://xxx.xxx.xxx.xxx:7002/Sit/Logon.jsp HTTP/1.1
Accept: application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, */*
Referer: http://xxx.xxx.xxx.xxx:7002/bankSit/logon.html
Accept-Language: zh-CN
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Host: xxx.xxx.xxx.xxx:7002
Content-Length: 46
Connection: Keep-Alive
Pragma: no-cache
Cookie: UserID=035001; JSESSIONID=BG1ynLgD3BCBtb2yNDQvDhBTnVScqvRFfSj0R22R92Th0PSbG1y2!-1503288452

ScreenWidth=1366&UserID=035001&Password=000000

response:
HTTP/1.1 200 OK
Date: Fri, 24 Nov 2028 01:28:11 GMT
Content-Length: 150
Content-Type: text/html; charset=GBK
Set-Cookie: JSESSIONID=YJnynLgLbMpH54Q6kT9QrlDFBvXNTkL0Yv6Vmncr2QK41n8mwhKK!-1503288452; path=/; HttpOnly
X-Powered-By: Servlet/2.5 JSP/2.1
<script type="text/javascript">

			window.open("/Sit/Redirector?ComponentURL=/Main.jsp&ComponentID=Main","_top");
</script>



302Redirect:
GET http://xxx.xxx.xxx.xxx:7002/Sit/Redirector?ComponentURL=/Main.jsp&ComponentID=Main HTTP/1.1
Accept: application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, */*
Accept-Language: zh-CN
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
Host: 14.1.78.206:7002
Cookie: UserID=035001; JSESSIONID=YJnynLgLbMpH54Q6kT9QrlDFBvXNTkL0Yv6Vmncr2QK41n8mwhKK!-1503288452


response:
HTTP/1.1 302 Moved Temporarily
Date: Fri, 24 Nov 2028 01:28:11 GMT
Transfer-Encoding: chunked
Location: http://14.1.78.206:7002/bankSit/ao?aoID=C2028112409281178728379052100878
Content-Type: text/html; charset=GBK
X-Powered-By: Servlet/2.5 JSP/2.1

<html><head><title>302 Moved Temporarily</title></head>
<body bgcolor="#FFFFFF">
<p>This document you requested has moved temporarily.</p>
<p>It's now at <a href="http://xxx.xxx.xxx.xxx:7002/Sit/ao?aoID=C2028112409281178728379052100878">http://xxx.xxx.xxx.xxx:7002/Sit/ao?aoID=C2028112409281178728379052100878</a>.</p>
</body></html>
0000

cypress location: /__/
puppeteer ok

**Comment by jngchd** [comment]
logon.html
<input type="button" class="button_submit" id="btn_submit" value="logon" onclick="doSubmit()">

**Comment by jngchd** [comment]
logon.html：“   <input type="button" class="button_submit" id="btn_submit" value="logon" onclick="doSubmit()">”

**Comment by jngchd** [comment]
logon.html：“   input type="button" class="button_submit" id="btn_submit" value="logon" onclick="doSubmit()"”

logon.jsp
request:
POST http://xxx.xxx.xxx.xxx:7002/Sit/Logon.jsp HTTP/1.1
Accept: application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, */*
Referer: http://xxx.xxx.xxx.xxx:7002/bankSit/logon.html
Accept-Language: zh-CN
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Host: xxx.xxx.xxx.xxx:7002
Content-Length: 46
Connection: Keep-Alive
Pragma: no-cache
Cookie: UserID=035001; JSESSIONID=BG1ynLgD3BCBtb2yNDQvDhBTnVScqvRFfSj0R22R92Th0PSbG1y2!-1503288452

ScreenWidth=1366&UserID=035001&Password=000000

response:
HTTP/1.1 200 OK
Date: Fri, 24 Nov 2028 01:28:11 GMT
Content-Length: 150
Content-Type: text/html; charset=GBK
Set-Cookie: JSESSIONID=YJnynLgLbMpH54Q6kT9QrlDFBvXNTkL0Yv6Vmncr2QK41n8mwhKK!-1503288452; path=/; HttpOnly
X-Powered-By: Servlet/2.5 JSP/2.1
<script type="text/javascript">
window.open("/Sit/Redirector?ComponentURL=/Main.jsp&ComponentID=Main","_top");
</script>



302Redirect:
GET http://xxx.xxx.xxx.xxx:7002/Sit/Redirector?ComponentURL=/Main.jsp&ComponentID=Main HTTP/1.1
Accept: application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, */*
Accept-Language: zh-CN
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
Host: 14.1.78.206:7002
Cookie: UserID=035001; JSESSIONID=YJnynLgLbMpH54Q6kT9QrlDFBvXNTkL0Yv6Vmncr2QK41n8mwhKK!-1503288452


response:
HTTP/1.1 302 Moved Temporarily
Date: Fri, 24 Nov 2028 01:28:11 GMT
Transfer-Encoding: chunked
Location: http://14.1.78.206:7002/bankSit/ao?aoID=C2028112409281178728379052100878
Content-Type: text/html; charset=GBK
X-Powered-By: Servlet/2.5 JSP/2.1

<html><head><title>302 Moved Temporarily</title></head>
<body bgcolor="#FFFFFF">
<p>This document you requested has moved temporarily.</p>
<p>It's now at <a href="http://xxx.xxx.xxx.xxx:7002/Sit/ao?aoID=C2028112409281178728379052100878">http://xxx.xxx.xxx.xxx:7002/Sit/ao?aoID=C2028112409281178728379052100878</a>.</p>
</body></html>
0000

cypress location: /__/
puppeteer ok

**Comment by jennifer-shehane** [comment]
@jngchd Can you try setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by jngchd** [comment]
response headers, location: /__/
