### ISSUE TITLE
cy.intercept is shown as processing

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14655]
Cypress v6.3.0

In this two test scenario

```js

beforeEach(() => {
  cy.visit('/')
})

it('confirms the number of times an intercept was called', () => {
  cy.intercept('/users?_limit=3').as('users3')
  cy.intercept('/users?_limit=5').as('users5')

  cy.get('#load-users').click().click()
  cy.wait('@users3')

  // to avoid clicking too quickly, add small pauses
  cy.get('#load-five-users').click()
    .wait(20).click()
    .wait(20).click()
    .wait(20).click()
})

it('spies using query parameter', () => {
  cy.intercept({
    pathname: '/users',
    query: {
      _limit: '3',
    },
  }).as('users3')

  cy.intercept({
    pathname: '/users',
    query: {
      _limit: '5',
    },
  }).as('users5')

  cy.get('#load-users').click()
  cy.wait('@users3')

  cy.get('#load-five-users').click()
  cy.wait('@users5')
})
```

I have noticed that the last XHR of the first test never completes

https://user-images.githubusercontent.com/2212006/105212173-19cc5c00-5b1b-11eb-97f8-bc5104c03746.mp4

## Reproduction

Repo and branch https://github.com/cypress-io/cypress-example-recipes/tree/runaway-test

- clone the repo
- install dependencies
- `cd examples/stubbing-spying__intercept`
- `npm run dev`
- click on the `spec.js`

Note that if there is no second test, or if the first test is `it.only` then everything is fine, the XHR completes right away. So something about the state is leaking from one test into another I guess

**Comment by flotwig** [comment]
Hmm yeah, all requests are cleared once the test ends, so there is no longer a reference to the log to end it...

Most likely the best fix is to update all unresolved request logs before each test to note that they were incomplete.

**Comment by bahmutov** [comment]
Yup
