### ISSUE TITLE
Stubing response headers with cy.intercept doesn't work

### ISSUE THREAD

**Issue by TomPradat** [cypress-io/cypress#14654]
### Current behavior

I recently upgraded to 6.3 and tried to use the `cy.intercept` API. So I followed [this article for stubbing a response](https://docs.cypress.io/api/commands/intercept.html#Stubbing-a-response)

According to the test runner and the network tab, the fetch request get caught and is stubbed but in my app code the header is not there in the code.

<img width="1436" alt="Capture d’écran 2021-01-20 à 17 38 39" src="https://user-images.githubusercontent.com/16164512/105206338-8d379300-5b46-11eb-93c0-112657937f9a.png">
<img width="1436" alt="Capture d’écran 2021-01-20 à 17 39 00" src="https://user-images.githubusercontent.com/16164512/105206346-8f015680-5b46-11eb-8631-2e827af6322c.png">

I've created a [repo](https://github.com/TomPradat/cypress-response-stub-headers-not-working) to reproduce the bug but here is a quick piece of code of how I'm intercepting the request :

```javascript
// index.spec.js
  it("", () => {
    cy.intercept("/toto", {
      statusCode: 200,
      body: "Toto",
      headers: {
        foo: "bar",
      },
    }).as("fetchToto");

    cy.visit("/");

    cy.wait("@fetchToto");

    cy.contains("The header was found");
  });
```

```javascript
// index.js
const testFetching = async () => {
  const response = await fetch("https://adomainthatdoesntexist.com/toto");
  const text = await response.text();

  const expectedHeader = response.headers.get("foo");

  console.log("expectedHeader", expectedHeader, text);

  if (expectedHeader === "bar") {
    const div = document.createElement("div");
    div.innerText = "The header was found";

    document.body.appendChild(div);
  }
};

testFetching();
```

### Desired behavior

I expect to be able to stub the response headers.

### Test code to reproduce

I created a repo to reproduce the bug : https://github.com/TomPradat/cypress-response-stub-headers-not-working

To run the test:
- `yarn install && yarn start`
- `yarn cypress:open`

### Versions

I'm using Chrome 88, cypress 6.3.0 (latest right now), OSX 10.15.7

**Comment by jennifer-shehane** [comment]
@TomPradat In your example, none of the headers are present, not just the one that is overwritten. Are you sure you're reading the headers correctly?

```js
console.log(response.headers.get('Connection'));
console.log(response.headers.get('Date'));
```

**Comment by TomPradat** [comment]
Yes I'm pretty sure because I made that example from code that runs. Also after trying a few things, I noticed that calling `fetch('/toto')` instead of `fetch('https://adomainthatdoesntexist.com/toto')` make the test work. I still don't know what's causing this problem though 🤔

**Comment by TomPradat** [comment]
Any chance anyone had time to look it up ?

**Comment by Xiphe** [comment]
I can confirm this issue.

**Comment by Xiphe** [comment]
I noticed that in your example, you're intercepting `"/toto"` while you fetch from "https://adomainthatdoesntexist.com/toto". 

Not entirely sure how the intercept API this is supposed to work but have you tried intercepting `https://adomainthatdoesntexist.com/toto`?

For my case, it makes no difference though.

**Comment by TomPradat** [comment]
Yes I tried that as well but got the same result

**Comment by Uysim** [comment]
Facing the same problem

**Comment by Uysim** [comment]
FYI, @dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
@Uysim can I help? I am not working on intercept part of cypress :)

**Comment by Uysim** [comment]
Oh sorry, @dmtrKovalenko. I thought you are the owner of this.

**Comment by Uysim** [comment]
@flotwig  I saw you working on intercept. Can you help with this?

**Comment by flotwig** [comment]
@TomPradat this looks like it will not work, since `foo` is not in `access-control-expose-headers`, it will not exist in `Response.headers`: https://stackoverflow.com/a/54928828/3474615

How's this work for you?

```js
// index.spec.js
  it("", () => {
    cy.intercept("/toto", {
      statusCode: 200,
      body: "Toto",
      headers: {
        foo: "bar",
        'access-control-expose-headers': 'foo'
      },
    }).as("fetchToto");

    cy.visit("/");

    cy.wait("@fetchToto");

    cy.contains("The header was found");
  });
```

**Comment by Uysim** [comment]
@flotwig Thank you. I can confirm that expose headers is working. 
@TomPradat How about your end?

**Comment by TomPradat** [comment]
Yeap I'm confirming it works with the `access-control-expose-headers`, I totally missed that :+1: 

I'm closing this issue as a consequence
