### ISSUE TITLE
Screenshot naming causes cross-platform compatibility issues

### ISSUE THREAD

**Issue by c32hedge** [cypress-io/cypress#14664]
### Current behavior

Since #2403 was fixed, I haven't seen any issues with Cypress saving screenshots while running. However, since the allowed size of a file path name is OS-specific, saving screenshot file names at the limit of what's allowed _for the platform a Cypress test is executed on_ causes issues if Cypress artifacts are copied to another platform.

In my use case, our tests run as part of a Jenkins build. The tests themselves run on an Ubuntu build agent. Once the tests have run, our Jenkins pipeline adds the test artifacts (JUnit reports, screenshots, videos, etc.) to a zip file that is saved as a build artifact. However, we often can't open the resulting zip file on Windows because the screenshot file names, while valid on Ubuntu where they were created and added to the zip file, are too long for Windows. Windows just gives a generic message like the screenshot below in this case:

![image](https://user-images.githubusercontent.com/8810829/105244349-5f4e5080-5b3e-11eb-8e6e-5c96b620263b.png)

### Desired behavior

Screenshots should be given short names (e.g. perhaps the test file name plus an incrementing integer) that are more likely to fall well within the size limits for common operating systems by default, instead of pushing the limit of the OS the tests were run on.

While I am aware of https://docs.cypress.io/api/plugins/after-screenshot-api.html, I'm not sure it helps me here, since I need to be able to ensure each screenshot name is unique and I don't think I have access to enough information to know, for example, that since this is the Nth failure I should add N to the screenshot file name. (I suppose I could use `takenAt`, sanitize the characters that can be problematic in filenames, like `:`, and hope that no two timestamps end up exactly the same, but that still feels kinda gross.)

### Test code to reproduce

``` javascript
describe('-3-5-7-9-12-15-18-21-24-27-30-33-36-39-42-45-48-51-54-57-60-63-66-69-72-75-78-81-84-87-90-93-96-100-104-108-112-116-120-124-128-132-136-140-144-148-152-156-160-164-168-172-176-180-184-188-192-196-200-', () => {
  it('-3-5-7-9-12-15-18-21-24-27-30-33-36-39-42-45-48-51-54-57-60-63-66-69-72-75-78-81-84-87-90-93-96-100-104-108-112-116-120-124-128-132-136-140-144-148-152-156-160-164-168-172-176-180-184-188-192-196-200-', () => {
    expect(true).to.be.false;
  });
});
```
1. run the test above in Ubuntu
2. zip the `screenshots` folder
3. copy the zip file to a Windows machine
4. try to open it

### Versions

Cypress 6.3.0

**Comment by jennifer-shehane** [comment]
Yeah, this is something we did not consider. I doubt that this work will be prioritized since it is a pretty rare use case, but we would be open to a PR to fix this.

The `after:screenshot` details provide the original name (path) of the screenshot, so you should have all the details of the original to edit. 

```js
module.exports = on => {
  on('after:screenshot', (details) => {
    console.log(details)
  })
};
```

An example of the details 

```
{
  testAttemptIndex: 0,
  size: 45799,
  takenAt: '2021-01-21T05:52:22.600Z',
  dimensions: { width: 1280, height: 720 },
  multipart: false,
  specName: 'spec.js',
  testFailure: true,
  path: '/Users/jennifer/Dev/cypress-transform-test/cypress/screenshots/spec.js/test (failed).png',
  scaled: true,
  blackout: [],
  duration: 333
}
```

**Comment by c32hedge** [comment]
@jennifer-shehane in terms of a community PR, would any of the following be preferred by the Cypress team for a new screenshot naming convention?

Given a spec name like `spec.js` and number of failures `NN` in the spec (I'm using `NN` instead of `N` to imply padding with leading zeroes). Listed in rough descending order of my personal preference:

1. `screenshots/spec.js/NN-spec.js.png`
2. `screenshots/spec.js/NN.png`
3. `screenshots/spec.js/spec.js-NN.png`
4. `screenshots/spec.js/NN-spec.js (failed).png`
5. `screenshots/spec.js/<other-unique-identifier-like-timestamp-or-mocha-test-id>.png`
6. `screenshots/spec.js/<other-unique-identifier-like-timestamp-or-mocha-test-id> spec.js.png`

**Comment by jennifer-shehane** [comment]
This would be a breaking change. I'm not sure we would want to make this change. It would affect our Dashboard service also. I'll have to check with the team.

**Comment by c32hedge** [comment]
As a nonbreaking alternative, what about adding the failure number (for the current spec) to the details object passed to `after:screenshot`?

**Comment by jennifer-shehane** [comment]
Our team has opted to not making a change currently to the screenshot naming convention. 

There isn't a way built into Cypress today to get the 'failure number'. There's a few considerations, especially concerning parallel runs with the numbering system. But it should be possible for you to create a system to rename using unique ids/counts to the screenshots yourself.
