### ISSUE TITLE
Remove/replace --disable-infobars flag for Chrome 65+

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1466]
- Cypress Version: 2.1.0
- Browser Version: Chrome 65+

Chrome has removed the flag `--disable-infobars` as of Chrome 65. Commit can be found here: https://chromium.googlesource.com/chromium/src/+/d869ab3350d8ebd95222b4a47adf87ce3d3214b1

Now this message appears in any Cypress tests run in Chrome 65+:
```
Chrome is being controlled by automated test software
```

This area takes up some real estate I'd like back on the screen, especially for screenshots. Maybe this can be removed during screenshot - @chrisbreiding ? Furthermore if you try to close the bar, it still takes up the space. There's probably an issue for Chrome open somewhere about this. 

Any feedback/research on how Cypress can remove this infobar is appreciated!

At the very least, we should remove this code: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.coffee#L42

![screen shot 2018-03-15 at 12 00 17 pm](https://user-images.githubusercontent.com/1271364/37476615-fa0ef918-284b-11e8-843f-a2529e8d732a.png)
![screen shot 2018-03-15 at 12 00 26 pm](https://user-images.githubusercontent.com/1271364/37476614-fa0191c4-284b-11e8-9add-86e6b54e715c.png)

**Comment by brian-mann** [comment]
I think we just need to remove `--enable-automation` although we originally enabled that flag due to Windows to actually **prevent** showing the infobars.

**Comment by jennifer-shehane** [comment]
It seems that the `--enable-automation` flag does some other useful things for us as mentioned here: https://github.com/GoogleChrome/chrome-launcher/pull/23#discussion_r138452200

- it disables the password saving UI
- it disables dev mode extension bubbles (?), and doesn't show some other info bars
- it means the default browser check prompt isn't shown
- it avoids showing these 3 infobars: ShowBadFlagsPrompt, GoogleApiKeysInfoBarDelegate, ObsoleteSystemInfoBarDelegate

**Comment by brian-mann** [comment]
We previously set flags to disable all those things but I guess some of them have been removed and rolled into this `--enable-automation` flag.

It's not only annoying but the fact that when you "x" it out it stays there is horrendous.

**Comment by brian-mann** [comment]
![why-chrome-why](https://user-images.githubusercontent.com/1268976/37480106-c76feffe-2854-11e8-8d17-74c9fc3c0ef7.gif)

**Comment by jennifer-shehane** [comment]
> --disable-infobars is back 

Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=820453#c6
Commit: https://chromium.googlesource.com/chromium/src/+/944fa28bae02e3381af9fed082c6e9870e4729a9

It seems as if they are discussing this as a temporary fix for now, but they do hope for this infobar to be present on all automated runs in the future. 

They didn't even discuss the fact of the closing of the infobar not working. Someone should likely [open an issue for chromium](https://chromiumbugs.appspot.com/?token=8AQ3yXrg7IjPwSPmrkSxJToxNTIyOTM0MTIx&role=&continue=https%3A//bugs.chromium.org/p/chromium/issues/entry.do%3Fcan%3D1%26q%3D%2522--disable-infobars%2522%26colspec%3DID%2520Pri%2520M%2520Stars%2520ReleaseBlock%2520Component%2520Status%2520Owner%2520Summary%2520OS%2520Modified) about this if it still exists:

**Comment by TLadd** [comment]
Looks like it was removed again: https://github.com/chromium/chromium/commit/1f2ed689344bffea49fd5e40bc734ec9e6c53691

Commit message mentions `An alternative middle-ground is to offer an enterprise policy which
allows disabling the security infobars related to automation.`. Based on the PR, I believe it's this one: https://cloud.google.com/docs/chrome-enterprise/policies/?policy=CommandLineFlagSecurityWarningsEnabled

**Comment by jennifer-shehane** [comment]
@TLadd We will not be supporting removing the info bar anymore as this is the intended behavior of Chrome. They want these warnings in place when running in an automated browser and it's not worth it to keep up hacking for every version around it.

**Comment by Jehoel** [comment]
It's a shame they went with the thick infobar approach rather than something else which *wouldn't impact the viewport size* - such as using a specific bright red browser tab-bar theme or an always-on statusbar message.

I had some of my ChromeDriver tests fail lately because they assumed the browser viewport size would be the same size as in a normal Chrome window with the same window dimensions.

Is it possible to run tests against Chrome's Device Emulation mode - or some other way to force a specific (or minimum) viewport size regardless of any infobars?

**Comment by jennifer-shehane** [comment]
@Jehoel The info bars should have zero effect on the viewport size of the tested application within Cypress. It's just an annoyance while working locally to have it pop up and take up the Test Runner. There's no way to use Chrome Device Emulation at this time.
