### ISSUE TITLE
toMatchImageSnapshot did not capture the exact component

### ISSUE THREAD

**Issue by IslamNosser** [cypress-io/cypress#14666]
### Current behavior
I'm developing a tool that has multiple graphs in one page. As below screen
![image](https://user-images.githubusercontent.com/15004805/105252822-e9220c00-5b86-11eb-9ccb-4de5a23167ee.png)
We've decided to use Cypress toMatchImageSnapshot in our frontend testing automation. I need to validate each graph separately. But When I tried to snapshot specific div the expected snapshot to capture is 

![image](https://user-images.githubusercontent.com/15004805/105253700-ab25e780-5b88-11eb-824a-fe3209d94a64.png)

Instead I received the below under __image__snapshot

![image](https://user-images.githubusercontent.com/15004805/105253778-d1e41e00-5b88-11eb-91eb-6c09f69b9c0e.png)
 
I'm getting the div and snapshot it as per documentation. Below is my used code
`cy.get('div[id=vis-190]').toMatchImageSnapshot({ clip: { x: 1000, y: 1000, width: 1000, height: 1000 } });`

And this my cypress.josn file

`{
    "defaultCommandTimeout": 10000,
    "ignoreTestFiles": [
        "**/__snapshots__/*",
        "**/__image_snapshots__/*"
    ],
    "env": {
        "cypress-plugin-snapshots": {
            "imageConfig": {
                "threshold": 0.01,
                "createDiffImage": true
            },
            "screenshotConfig": {
                "capture": "runner",
                "scale": true
            }
        }
    }
}`
 I'm using cypress version 3.5.0 and cypress-plugin-snapshots version 1.4.4 and running the test over chrome Version 87.0.4280.141

Thanks!

**Comment by jennifer-shehane** [comment]
I see that you are using a very old version of Cypress. I would suggest updating to our most current version to see if your issue is fixed.

Also this issue seems very coupled to the cypress-plugin-snapshots. If you can isolate the issue down to purely a `cy.screenshot()` command - and that causing the issue we'd be happy to look at it. Otherwise I would suggest opening an issue in https://github.com/meinaart/cypress-plugin-snapshots

**Comment by IslamNosser** [comment]
I think I made a mistake. I did not know that I need to scroll to the component I need to take screenshot for to be able to take proper screenshot. Adding `cy.get('div[id=vis-108]').scrollIntoView()` solved my issue.
I need to add that I got same behavior when using `cy.screenshot()`. scrollIntoView solved both toMatchImageSnapshot and screenshot.

Thanks!
