### ISSUE TITLE
In Cypress , List of cities in autocomplete search is not loading .

### ISSUE THREAD

**Issue by chghulamnabi** [cypress-io/cypress#14669]
### Current behavior
It is not loading Cities list in autocomplete search 

### Desired behavior
 It should load cities list.

### Test code to reproduce
```js
    describe('Events', function() {
    it.only("Events ", () => {
        cy.visit('https://foxtail-stage.netlify.app/')
            //cy.Login()
        cy.get(".actionLogin").click({ force: true });
        cy.get('input[placeholder="Phone Number"]').type("6783333333");
        cy.get(".color").click({ force: true });
        cy.get('.input > input').should('be.visible').type('123456');
        cy.get('.color').should('be.visible').click();
        cy.wait(2000)
        cy.get('.menu > :nth-child(3) > a > span').click()
        cy.get(':nth-child(2) > a > span').click();
        cy.get('.menu > :nth-child(2) > a').should('be.visible').click();
    });
    it.only('Create New Event', function() {
        cy.wait(2000)
        cy.get('.create-event-btn').click()
        cy.get('#eventname').type('Testing')
        cy.get('#tagline').type('Test')
        cy.get('textarea').type('My Text will be shown here ......')
        cy.get('.select_kinks').click()
        cy.get(':nth-child(1) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(2) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(3) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(4) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(5) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(6) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(7) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(8) > .kink-tooltip > label > span').click();
        cy.get('.close').last().click({
            force: true
        });
        var pic = "girl.jpg"
            // cy.get('.filepond--label-action') //.drag('.targetitem');
        cy.contains('Drag & Drop your image or ') //.attachFile(pic);
            .drag('.filepond--label-action', { force: true, timeout: 6000 })
        cy.wait(5000)
        cy.get(':nth-child(5) > .select-container').click();
        cy.contains('Public').click({ force: true })
        cy.get('#next-btn').click({ force: true });
        cy.wait(6000)
        cy.get('input[placeholder="Address"]').type("San Diego", { delay: 1000 }).invoke('show').type("i{enter}", { delay: 100 });
        cy.wait(3000)
       
    });
    }) ;
```

### Versions

 Cypress version:6.3.0

**Comment by chghulamnabi** [comment]
[Events.spec.zip](https://github.com/cypress-io/cypress/files/5847513/Events.spec.zip)
![Screenshot_9](https://user-images.githubusercontent.com/58205463/105316907-582d4e00-5be3-11eb-8033-4f976746f528.png)

**Comment by Narretz** [comment]
Please don't ignore the issue template. You won't get help if you just post a screenshot.

**Comment by chghulamnabi** [comment]
> Please don't ignore the issue template. You won't get help if you just post a screenshot.

I have also added my code

**Comment by chghulamnabi** [comment]
### Desired behavior


### Test code to reproduce



### Versions

**Comment by bahmutov** [comment]
![Screen Shot 2021-01-21 at 12 11 08 PM](https://user-images.githubusercontent.com/2212006/105385837-c5d87a80-5be1-11eb-8540-4c07c72fb99f.png)

The website is not responding

**Comment by jennifer-shehane** [comment]
@chghulamnabi Visiting the https://foxtail-stage.netlify.app/ does not load within Cypress with the provided code. Can you please provide all necessary steps to visit the webpage within Cypress. Maybe you have something in cypress.json or support files that is required?

**Comment by chghulamnabi** [comment]
> @chghulamnabi Visiting the https://foxtail-stage.netlify.app/ does not load within Cypress with the provided code. Can you please provide all necessary steps to visit the webpage within Cypress. Maybe you have something in cypress.json or support files that is required?

[Events.txt](https://github.com/cypress-io/cypress/files/5853922/Events.txt)

**Comment by chghulamnabi** [comment]
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // Uncaught: Exception failing the test
    return false
});
describe('Events', function() {

    it("Events ", () => {
        cy.visit('https://foxtail-stage.netlify.app')
            //cy.Login()
        cy.get(".actionLogin").click({ force: true });
        cy.get('input[placeholder="Phone Number"]').type("6783333333");
        cy.get(".color").click({ force: true });
        cy.get('.input > input').should('be.visible').type('123456');
        cy.get('.color').should('be.visible').click();
        cy.wait(2000)
        cy.get('.menu > :nth-child(3) > a > span').click()
        cy.get(':nth-child(2) > a > span').click();
        cy.get('.menu > :nth-child(2) > a').should('be.visible').click();

    });
    it.only('Create New Event', function() {
        cy.wait(2000)
        cy.get('.create-event-btn').click()
        cy.get('#eventname').type('Testing')
        cy.get('#tagline').type('Test')
        cy.get('textarea').type('My Text will be shown here ......')
        cy.get('.select_kinks').click()
        cy.get(':nth-child(1) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(2) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(3) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(4) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(5) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(6) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(7) > .kink-tooltip > label > span').click();
        cy.get(':nth-child(8) > .kink-tooltip > label > span').click();
        cy.get('.close').last().click({
            force: true
        });
        var pic = "google.png"
        cy.contains('Browse').click().attachFile('google', { subjectType: 'drag-n-drop' })
            // cy.get('.filepond--label-action') //.drag('.targetitem');
            // cy.contains('Drag & Drop your image or ') //.attachFile(pic);
            //     .drag('.filepond--label-action', { force: true, timeout: 6000 })
        cy.wait(5000)
        cy.get(':nth-child(5) > .select-container').click();
        cy.contains('Public').click({ force: true })
        cy.get('#next-btn').click({ force: true });
        //cy.wait(6000)
        cy.get('input[placeholder="Address"]').invoke('show').type("San Diego", { delay: 1000 });
        cy.get('.autocomplete-dropdown-container').should('be.hidden').invoke('show')
            //cy.get('.suggestion-item').invoke('show') // call jquery method 'show' on the '.container'
            .should('be.visible') //.children('.active')
            .first().invoke('show') //.contains('San Diego')
            .invoke('text') //.click({ force: true });
        cy.wait(3000);
});
});

**Comment by chghulamnabi** [comment]
> @chghulamnabi Visiting the https://foxtail-stage.netlify.app/ does not load within Cypress with the provided code. Can you please provide all necessary steps to visit the webpage within Cypress. Maybe you have something in cypress.json or support files that is required?

You are getting this just due to chrome's security issues . just add this line in cypress.json file .All other script is same
{"chromeWebSecurity": false,}

**Comment by bahmutov** [comment]
@chghulamnabi please create a public repo with the test code exactly as you want us to run to see the problem.

**Comment by chghulamnabi** [comment]
Ok
