### ISSUE TITLE
6.3: Error: Could not process 'take:screenshot'. No automation clients connected.

### ISSUE THREAD

**Issue by csvan** [cypress-io/cypress#14663]
### Current behavior

Under Cypress 6.3, tests randomly fail with `Error: Could not process 'take:screenshot'. No automation clients connected.`. This did not happen in 6.2.1 or earlier versions.

### Desired behavior

The above error should not occur

### Test code to reproduce

Sadly, our project is proprietary, but the setup is fairly vanilla and we do nothing out of the ordinary.

### Versions

OS: Centos7
Cypress: 6.3.0
Node: 14
Browser: Chrome 87

**Comment by jennifer-shehane** [comment]
@csvan It'd be helpful to get some more information on when this exactly throws.

- Is this happening during a `cy.screenshot()` command or is it throwing during a screenshot taken because a test fails? 
- If during a failure is it with an afterEach hook, etc?
- Are you using any plugins with screenshots, like cypress-image-snapshot?

**Comment by fgiroud** [comment]
Hi, we are experiencing the same issue since 6.3
You can check the log here: 
* [Github action](https://github.com/OpenRefine/OpenRefine/runs/1743471511?check_suite_focus=true)
* [Cypress dashboard](https://dashboard.cypress.io/projects/s5du3k/runs/172/overview)

We are currently investigating some other failures, not sure it's since 6.3, but we've also got this error message quite often since
``` 
Timed out waiting for the browser to connect. Retrying...
Warning: Cypress failed to connect to Chrome via stdio after 1 minute, 0 seconds. Falling back to TCP...
Connecting to Chrome via TCP was successful, continuing with tests.
```
Not sure if it's related

**Comment by nielsboecker** [comment]
I've had the same error messages and resolved the issue by going `headed` as per https://github.com/cypress-io/cypress/issues/8606#issuecomment-703544094.

**Comment by limonte** [comment]
Same issue here: https://github.com/sweetalert2/sweetalert2/runs/1756905102?check_suite_focus=true

This didn't happen with 6.2

**Comment by samueloakley** [comment]
Getting the same issue on VSTS with Chrome running headlessly.

@jennifer-shehane 
1. The screenshot is being taken on test failure.
2. Looks like it's happening in a beforeEach hook, but getting the same stack trace in the test result as above.
3. We use cypress-image-snapshot which was recently added.

Spotted this from the logs also, which seems to correspond to the failing tests:
```Timed out waiting for the browser to connect. Retrying...
Warning: Cypress failed to connect to Chrome via stdio after 1 minute, 0 seconds. Falling back to TCP...
Connecting to Chrome via TCP was successful, continuing with tests.
TypeError: testcase.testcase[0]._attr.time.toFixed is not a function
    at /home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:411:73
    at Array.forEach (<anonymous>:null:null)
    at /home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:405:12
    at Array.forEach (<anonymous>:null:null)
    at MochaJUnitReporter.getXml (/home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:392:14)
    at MochaJUnitReporter.flush (/home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:370:20)
    at MochaJUnitReporter.<anonymous> (/home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:247:10)
    at Runner.emit (events.js:315:20)
    at Reporter.emit (/home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/lib/reporter.js:333:46)
    at Object.onMocha (/home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/lib/project.js:360:18)
    at Socket.<anonymous> (/home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/lib/socket.js:321:32)
    at Socket.emit (events.js:315:20)
    at /home/vsts/.cache/Cypress/6.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)```

**Comment by JosephHalter** [comment]
If I upgrade cypress to 6.3, the builds are still green locally but fail constantly in CI (Github Actions). @samueloakley If this error really only happens when taking a screenshot after a test failure, then fixing this error will only reveal the real error underneath.

For now, I've no other choice but to stay with cypress 6.2.1 which work perfectly fine.

**Comment by JosephHalter** [comment]
I tried to go `headed` using `xvfb-run` like suggested in issue #8606, but it causes `ffmpeg` to crash with the following error:

```
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: Output #0, mp4, to '/project/test.spec.ts.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: Output #0, mp4, to '/project/test.spec.ts.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: Output #0, mp4, to '/project/test.spec.ts.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.1.0 ci:run-tests: `TZ=Etc/UTC xvfb-run cypress run --headed --browser chrome`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@0.1.0 ci:run-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I've tried looking at the various logs but there isn't much there. The `xvfb-run` trick is nice if it works for some people, but it doesn't appear like a solution that can replace Chrome headless for everybody.

**Comment by pavel-R5** [comment]
Same problem here. Got this error in CI: "Error: Could not process 'get:cookies'. No automation clients connected". 
Happened during the "before all" section. 
According to the logs before this tests, I also had this warning:
```
Timed out waiting for the browser to connect. Retrying again...
Warning: Cypress failed to connect to Chrome via stdio after 1 minute, 0 seconds. Falling back to TCP...
Connecting to Chrome via TCP was successful, continuing with tests.
```
For me, re-running the tests helped, but I don't want this to happen continuously.

**Comment by craig-dae** [comment]
Same behavior. A few of my tests, in github actions, now seem to hang for a few minutes. I can't see the screenshot, because of this error: 
```
Could not process 'take:screenshot'. No automation clients connected.

Because this error occurred during a before all hook we are skipping all of the remaining tests.

Although you have test retries enabled, we do not retry tests when before all or after all hooks fail
```

It looks like this message is separate from the actual error causing my tests to fail. It looks like, when they fail, it tries to take a screenshot for the cypres dashboard, which results in the above error.

**Comment by limonte** [comment]
For the record: this issue isn't happening for my project after upgrading to `7.0.1`.

**Comment by csvan** [comment]
I can't reproduce this on 6.8 or later either. Will close until someone can reproduce

**Comment by freshly-curtis** [comment]
Just wanted to update, we saw this issue this morning during one of our test runs in Firefox.

`Error: Could not process 'take:screenshot'. No automation clients connected.`
