### ISSUE TITLE
parallel tests

### ISSUE THREAD

**Issue by LuyTester** [cypress-io/cypress#14673]
I had set env in travis.yml and the the CLI with tags record and parallel. 2 days ago was working. now always is running in one machine! 

![Screenshot 2021-01-22 at 10 59 52](https://user-images.githubusercontent.com/52031937/105476916-7d809180-5ca1-11eb-80e4-61a0316c530a.png)
![Screenshot 2021-01-22 at 11 02 01](https://user-images.githubusercontent.com/52031937/105476923-7f4a5500-5ca1-11eb-8983-d5005a440fff.png)
After I updated plan, stoped working and it was working:

![Screenshot 2021-01-21 at 16 55 46](https://user-images.githubusercontent.com/52031937/105477256-e831cd00-5ca1-11eb-9121-e580f3859d1b.png)
![Screenshot 2021-01-21 at 16 59 15](https://user-images.githubusercontent.com/52031937/105477286-ee27ae00-5ca1-11eb-9aaf-2640ecf4b9d8.png)

**Comment by jennifer-shehane** [comment]
@LuyTester What do you mean by 'After I updated plan, stoped working and it was working:'?

**Comment by LuyTester** [comment]
Hello sorry after change my CI configuration many times i got the solution.

Thanks

**Comment by LuyTester** [comment]
Now it is working. So was travis no cypress 🙏

**Comment by jennifer-shehane** [comment]
@LuyTester Glad to hear the issue was fixed. Closing as resolved.
