### ISSUE TITLE
cy.intercept not breaking if request object is wrong

### ISSUE THREAD

**Issue by bvanderneut** [cypress-io/cypress#14671]
Hello,

I want to test that an outgoing request has the correct body. I saw in the documentation that you can do it like this.

```
describe('Check Marketing logging', () => {
	before(function () {
		cy.visit('https://www.independer.nl/zorgverzekering/intro.aspx');
	});

	it('Check button click - intercept req', function () {
		const requestBody = { "wrong": "request body" };

		cy.intercept('POST', '/api/ue/c', (req) => {
			expect(JSON.stringify(req.body)).to.include(JSON.stringify(requestBody));
		}).as('sLIdentifier');

		cy.getByUe('man', 'input').click({ force: true });

		cy.wait('@sLIdentifier');
	});
});
```

The only thing is if the condition is right or wrong the runner always shows succeded. See image below.

![image](https://user-images.githubusercontent.com/44266055/105353933-2a023b00-5bf0-11eb-8e2f-600de6479e83.png)

It feels like this is a bug. The workarround I have now it doing it on the wait like this.

```
it('Check button click - intercept wait', function () {
	const requestBody = { "wrong": "request body" };

	cy.intercept('POST', '/api/ue/c').as('sLIdentifier');
	cy.getByUe('vrouw', 'input').click({ force: true });
	cy.wait('@sLIdentifier').should(({ request }) => {
		expect(JSON.stringify(request.body)).to.include(JSON.stringify(requestBody));
	})
});
```

**Comment by bahmutov** [comment]
Can you put debugger keyword before json parsing in the intercept and inspect the request (or even console log) I think the request body is already an object

**Comment by bvanderneut** [comment]
If I do that then indeed both are objects

![image](https://user-images.githubusercontent.com/44266055/105355646-b4e43500-5bf2-11eb-8c13-69650864d588.png)

But If I change it to this

```
it('Check button click - intercept req', function () {
	const requestBody = { "wrong": "request body" };

	cy.intercept('POST', '/api/ue/c', (req) => {
		expect(req.body).to.include(requestBody);
	}).as('sLIdentifier');

	cy.getByUe('man', 'input').click({ force: true });
});
```

I still have the same issue that the result is green and the status of hij request in keeps staying on "pending".

![image](https://user-images.githubusercontent.com/44266055/105355829-f1179580-5bf2-11eb-8bb3-f83d1f7329a0.png)

**Comment by bvanderneut** [comment]
Btw in the old route version it was also not working as expected.

```
it('Check button click - route req', function () {
	const requestBody = { "wrong": "request body" };

	cy.server();
	cy.route({
		method: 'POST',
		url: '/api/ue/c',
		onRequest: (xhr) => {
			expect(xhr.requestBody).to.include(requestBody);
		}
	}).as('sLIdentifier');
	cy.getByUe('man', 'input').click({ force: true });
});
```

Same assert message but still green:
`expected { Object (u, d) } to have property wrong`

**Comment by bahmutov** [comment]
Could you create full standalone reproducible example it one does not exist already showing the problem.

**Comment by bvanderneut** [comment]
This is the example you can use. If I misunderstood please let me know.

```
describe('Check Marketing logging', () => {
	before(function () {
		cy.visit('https://www.independer.nl/zorgverzekering/intro.aspx');
	});

	it('Check button click - intercept req', function () {
		const requestBody = { "wrong": "request body" };

		cy.intercept('POST', '/api/ue/c', (req) => {
			expect(req.body).to.include(requestBody);
		}).as('sLIdentifier');

		cy.getByUe('man', 'input').click({ force: true });
	});
});
```

**Comment by bahmutov** [comment]
You are missing `cy.getByUe('man', 'input').click({ force: true });` code - what's `getByUe` does?

**Comment by bvanderneut** [comment]
Oeps my bad :)

```
describe('Check Marketing logging', () => {
	before(function () {
		cy.visit('https://www.independer.nl/zorgverzekering/intro.aspx');
	});

	it('Check button click - intercept req', function () {
		const requestBody = { "wrong": "request body" };

		cy.intercept('POST', '/api/ue/c', (req) => {
			expect(req.body).to.include(requestBody);
		}).as('sLIdentifier');

		cy.get('input[ue="man"]').click({ force: true });
	});	
});
```

**Comment by bahmutov** [comment]
I cannot recreate this problem with Cypress v6.3.0 using https://github.com/cypress-io/cypress-test-tiny/tree/intercept-issue-14671

<img width="1275" alt="Screen Shot 2021-01-21 at 10 41 22 AM" src="https://user-images.githubusercontent.com/2212006/105374058-4775db80-5bd5-11eb-90c2-66b6ae3787e8.png">

**Comment by bvanderneut** [comment]
Ah I found the issue. We are using a Cypress Helper package with custom function etc. But in there this code was placed

```
Cypress.on('uncaught:exception', (err, runnable) => {
	// returning false here prevents Cypress from
	// failing the test
	return false;
});
```

So when I removed this code it works fine.  Don't know why we put this code here the first place :(

Thanks for the help.
