### ISSUE TITLE
Windows 10 64 bits: How to launch directly Cypress io in command prompt

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1468]
- Operating System: Windows 10 64 bits
- Cypress Version: 2.1.0

Hi,

In order to solve the problem with your corporate proxy for Cypress, we have installed your frontent on local. Your cy command is cy.visit('http://localhost:XXXX/). When I load this localhost page in my browser, I can see your app.

Nevertheless, when I launch my test within Cypress.io, cypress.io can't to connect on localhost but I get the following error:
 407: Proxy Authentication Required

Cypress.io wants to access your corporate proxy and I don't know why?

I have 2 questions:
- when we use Windows 10, we have an .exe in one folder and your project in another project outside the setup folder (containing cypress.exe). Is it correct?
- where must I install node_modules folder? Is it in my project folder?
- how can I launch cypress.io on windows 10 by command prompt? `./node_modules/.bin/cypress open` doesn't work on windows 10.
- how can force Cypress.io to exclude the proxy connection and to connect directly to localhost?

Thanks for your helping :-)

**Comment by brian-mann** [comment]
This isn't **our** corporate proxy asking for this - this is **your** corporate proxy. There's numerous issues open about adding 3rd party proxy support for environments which require it.

The rest of your questions seem like they're about basic NPM and node usage and I believe they are answered in our getting started guides. You don't have to install Cypress with NPM but its highly recommended.

https://docs.cypress.io/guides/getting-started/installing-cypress.html

**Comment by perceboisElisa** [comment]
Sorry, it is a mistake...it is effectively our...
Regards

**Comment by perceboisElisa** [comment]
Thanks for the documentation!

**Comment by jennifer-shehane** [comment]
I addressed where the corporate proxy issues stand here: https://github.com/cypress-io/cypress/issues/1469

> how can I launch cypress.io on windows 10 by command prompt

The best workaround is to create an `npm script` to run `cypress open` as detailed here: https://on.cypress.io/installing-cypress#Adding-npm-scripts

Also - we have limited resources to answer all question in GitHub issues. Our chat is a great place for questions https://gitter.im/cypress-io/cypress
