### ISSUE TITLE
.should('not.have.css') assertion is passing even though the condition is false

### ISSUE THREAD

**Issue by mdodds93** [cypress-io/cypress#14699]
### Current behavior
I am trying to write a method which waits for the splash screen of my application to disappear before continuing. 

The HTML in my app has a `<div>` element representing the splash screen which gains the attribute `style='display:none;'` when the app has loaded.

The `<div>` element has `display: block;`as default - I'm getting cypress to assert that this css has been removed but it seems to pass the assertion anyway for `should('exist').and('not.have.css', 'display', 'block')`:

![image](https://user-images.githubusercontent.com/40863618/105490553-da357980-5cac-11eb-8b8b-94092a010425.png)

The negative assert that begins with 'expected undefined' is happening because cypress is trying to access the next part of the test, elements that don't exist, when I want it to wait until the splash screen is hidden

Furthermore there is a second `.and()` assertion which is never called here either.

### Desired behavior
I would expect `.and.('not.have.css', 'display', 'block')` to keep retrying until the element does not have `display: block;`

### Test code to reproduce
I can't provide the HTML template of any code due to my organisation, but basically it is as follows:
when the splash screen is displayed : `<div id='pre-load-section'></div>` // when app is loading (the 'display' style is set to 'block' as default)
when the splash screen is not displayed `<div id='pre-load-section' style='display:none;'>` // when the app loads

My method in cypress:
```
export const SPLASH_PAGE_SELECTOR: string = 'div#pre-load-section';

export const ensureSplashPageNotDisplayed: () => void = () => {
  cy.get(SPLASH_PAGE_SELECTOR)
    .should('exist')
    .and('not.have.css', 'display', 'block')
    .and('have.css', 'display', 'none');
};
```

### Versions
Cypress version: 6.3.0
Browser/version: Chrome 87
Operating System: macOS Big Sur 11.1

**Comment by matthew-dodds** [comment]
Additionally, removing the `'not.have.css'` assertion still results in a passed assert for a false value:

```
export const ensureSplashPageNotDisplayed: () => void = () => {
  cy.get(SPLASH_PAGE_SELECTOR)
    .should('exist')
    .and('have.css', 'display', 'none');
};
```

![image](https://user-images.githubusercontent.com/44771841/105491445-3351dd00-5cae-11eb-8040-782d0ae04e42.png)

**Comment by mdodds93** [comment]
Additionally, removing the `'not.have.css'` assertion still results in a passed assert for a false value:

```
export const ensureSplashPageNotDisplayed: () => void = () => {
  cy.get(SPLASH_PAGE_SELECTOR)
    .should('exist')
    .and('have.css', 'display', 'none');
};
```

![image](https://user-images.githubusercontent.com/44771841/105491445-3351dd00-5cae-11eb-8040-782d0ae04e42.png)

**Comment by bahmutov** [comment]
Can you capture the video of the app and the command log while this is happening? I have similar example in https://github.com/bahmutov/cypress-examples/commit/b089e7f1e6f52a2e14a9bfbc4212e4c4ff439a02 maybe you can modify it to show how the loading section changes its existence and CSS?

**Comment by mdodds93** [comment]
@bahmutov sorry but I wouldn't be able to publish a video of the app given restrictions within my organisation. However the splash screen is still displayed and the `style='display:none;'` attribute has not been applied to the `<div>`until well after these assertions have already passed

**Comment by mdodds93** [comment]
@bahmutov I've tried changing it via your example to the following:

`export const SPLASH_PAGE_SELECTOR: string = 'div#pre-load-section';

export const ensureSplashPageNotDisplayed: () => void = () => {
  cy.get(SPLASH_PAGE_SELECTOR).should('be.visible');
  cy.get(SPLASH_PAGE_SELECTOR).should('not.be.visible');
};`

It seems to run the first line `should('be.visible')` twice and fail on the second assert (while it is still displayed).

Error:       CypressError: You attempted to make a chai-jQuery assertion on an object that is neither a DOM object or a jQuery object.

The chai-jQuery assertion you used was:

  > visible

The invalid subject you asserted on was:

  > undefined

To use chai-jQuery assertions your subject must be valid.

```
This can sometimes happen if a previous assertion changed the subject.
    at Object.onInvalid (http://localhost:8080/__cypress/runner/cypress_runner.js:150946:17)
    at assertDom (http://localhost:8080/__cypress/runner/cypress_runner.js:168388:26)
    at assert (http://localhost:8080/__cypress/runner/cypress_runner.js:168394:5)
    at Assertion.<anonymous> (http://localhost:8080/__cypress/runner/cypress_runner.js:168496:14)
    at Assertion.propertyGetter (http://localhost:8080/__cypress/runner/cypress_runner.js:80925:29)
at Reflect.get (<anonymous>)
    at Object.proxyGetter [as get] (http://localhost:8080/__cypress/runner/cypress_runner.js:82363:22)
    at applyChainer (http://localhost:8080/__cypress/runner/cypress_runner.js:154723:30)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:154779:16
    at arrayReduce (http://localhost:8080/__cypress/runner/cypress_runner.js:25449:21)
    at Function.reduce (http://localhost:8080/__cypress/runner/cypress_runner.js:34473:14)
    at applyChainers (http://localhost:8080/__cypress/runner/cypress_runner.js:154756:24)
From previous event:
    at Context.shouldFn (http://localhost:8080/__cypress/runner/cypress_runner.js:154785:23)
    at Context.should (http://localhost:8080/__cypress/runner/cypress_runner.js:154803:23)
    at Context.<anonymous> (http://localhost:8080/__cypress/runner/cypress_runner.js:170229:21)
From Your Spec Code:
    at ensureSplashPageNotDisplayed (http://localhost:8080/my.spec.ts:791:34)
```

and it is pointing to the first line: 

`  cy.get(SPLASH_PAGE_SELECTOR).should('be.visible');`

**Comment by bahmutov** [comment]
Ughh, this is a hard to reproduce error we see sometimes: having `undefined` subject passed to Chai assertion. Without a reproducible example it would be difficult to debug it. In my test here https://glebbahmutov.com/cypress-examples/6.3.0/commands/assertions.html#should-with-callback-function it consistently passes, so I am not sure how I can recreate the problem

**Comment by mdodds93** [comment]
@bahmutov so I am actually implementing the splash screen method here because I was consistently getting the `undefined` subject Chai error elsewhere - I am able to consistently reproduce that error. The only thing is that unfortunately I wouldn't be able to share any of the source code for the web app with you but could show you what I have in cypress.

I have finished working now for the weekend but on Monday I could send you more information if you would like

**Comment by mdodds93** [comment]
If you look at my original screenshot in the first post, the failed assert is actually related to that `undefined` subject chai error. In my test I am waiting for other elements exist and then to be visible but it is trying (and failling) to run an assertion on them becaue they haven't yet been rendered on the DOM yet until the app is ready (and splash screen disappears)

**Comment by bahmutov** [comment]
Yeah, if you can come up with tiny self-reproducible example without any of your app's code, but showing the error, it would be the best way for us to proceed.

**Comment by mdodds93** [comment]
@bahmutov sorry for taking so long to get back to you.

I've been able to create an example that I'm able to reproduce every single time:

```
  it('Test Title', () => {
    // redirect to home page
    cy.visit('admin/home');
    // ensure that splash screen is rendered but hidden
    cy.get('div#pre-load-section').should('exist');
    cy.get('div#pre-load-section').should('not.be.visible'); // INCORRECTLY ASSERTS AS NOT VISIBLE BEFORE SPLASH SCREEN DISAPPEARS
    // assert that features of page are displayed - assert on correct page before continuing
    cy.get('li.make-link.home-icon.active').should('be.visible');
    cy.get('h1.page-heading.home-icon').should('be.visible'); // FAILS ON THIS CHECK
    // run test condition
    cy.get('li.metric-row').should('exist').and('be.visible');
  });
```

In the `cy:open` console:

![image](https://user-images.githubusercontent.com/40863618/105854420-c9ec0a00-5fde-11eb-9453-38355b4ecf04.png)

As far as I believe, it is firstly incorrectly asserting the splash page (`cy.get('div#pre-load-section')`) as not visible when it is still visible. The splash page is visible until my angular app is finished loading. It then positively asserts `cy.get('h1.page-heading.home-icon').should('be.visible')` as visible - it is rendered at this point but not yet visible behind the splash page but it gets `  cy.get('h1.page-heading.home-icon').should('be.visible');` as undefined.

I tried changing to this:

```
  it('Test Title', () => {
    // redirect to home page
    cy.visit('admin/home');
    // ensure that splash screen is rendered but hidden
    cy.get('div#pre-load-section').should('exist');
    cy.get('div#pre-load-section').should('not.be.visible'); // INCORRECTLY ASSERTS AS NOT VISIBLE BEFORE SPLASH SCREEN DISAPPEARS
    // assert that features of page are displayed - assert on correct page before continuing
    cy.get('li.make-link.home-icon.active').should('exist').and('be.visible');
    cy.get('h1.page-heading.home-icon').should('exist').and('be.visible'); // FAILS ON THIS CHECK
    // run test condition
    cy.get('li.metric-row').should('exist').and('be.visible');
  });
```

and I get similar behaviour:

![image](https://user-images.githubusercontent.com/40863618/105854842-4da5f680-5fdf-11eb-9cf6-d4da210d5d40.png)

**Comment by bahmutov** [comment]
Can you come up with a reproducible code repo we can execute to see it?

**Comment by mdodds93** [comment]
@bahmutov I have tried to create a new repo and set up a similar environment but cypress worked exactly as I would like it to (can't believe I'm complaining about that).

Unfortunately, I would not be authorised by my organisation to share any of the app code with you on github

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
