### ISSUE TITLE
When behind corporate proxy - cannot connect to API server in 'Runs' of test runner

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1470]
User got this error behind corporate proxy - confirmed error did not occur when they connected to their hotspot:
![00000003](https://user-images.githubusercontent.com/1271364/37528198-6410844e-290a-11e8-800c-fec53c52cf1c.png)

Original thread: https://gitter.im/cypress-io/cypress?at=5aa96043a60157d62fe8c9b6

**Comment by callmeaponte** [comment]
+1 for this. I'm stuck behind a corporate proxy at work and I'm seeing the exact same issue.

**Comment by lukeapage** [comment]
For us, I worked around it by editing server/lib/gui/events

```
      case "ping:api:server":
        apiUrl = konfig("api_url");
        return connect.ensureUrl(apiUrl).catch(function() { return ''; }).then(send)["catch"](function(err) {
          var subErr;
          if (err.length) {
            subErr = err[0];
            err.name = subErr.name || (subErr.code + " " + subErr.address + ":" + subErr.port);
            err.message = subErr.message || (subErr.code + " " + subErr.address + ":" + subErr.port);
          }
          err.apiUrl = apiUrl;
          return sendErr(err);
        });
```

==>

```
      case "ping:api:server":
        apiUrl = konfig("api_url");
        return connect.ensureUrl(apiUrl).then(send)["catch"](function(err) {
          var subErr;
          if (err.length) {
            subErr = err[0];
            err.name = subErr.name || (subErr.code + " " + subErr.address + ":" + subErr.port);
            err.message = subErr.message || (subErr.code + " " + subErr.address + ":" + subErr.port);
          }
          err.apiUrl = apiUrl;
          return sendErr(err);
        });
```

e.g. you are blocking people behind a corporate proxy in the code that detects whether you are blocked - but if you edit out the ping api server check like this, then I can login completely okay!!

**Comment by krishvv** [comment]
Where is server/lib/gui/events located . I am also facing the same issue . Not able to locate server/lib/gui/events
