### ISSUE TITLE
Type Error chalk.instance is not a constructor

### ISSUE THREAD

**Issue by cbruge** [cypress-io/cypress#14700]
### Current behavior
Updating to 6.3.0 running any .ts files I am getting an error 
```
Webpack failed to compile, TypeError: chalk.Instance is not a constructor
```
The dependency causing this is ts-loader 8.0.14 found in the Cypress Cache:
`Cypress/6.3.0/Cypress/resources/app/packages/server/node_modules/ts-loader`

### Desired behavior
Tests should run normally

### Test code to reproduce
In a testfile.ts:
```ts
it("Wants to Test", () => {
    cy.visit("https://google.com");
})
```

Try to run the file you get:

![image](https://user-images.githubusercontent.com/73653560/105500037-99e0f600-5cc2-11eb-9087-4ff1b853d3dc.png)

These are my current package.json dependencies:
```json
"dependencies": {
    "@types/node": "^14.14.22",
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "cypress": "^6.3.0",
    "eslint": "^7.18.0",
    "mocha": "^8.1.3",
    "mochawesome": "^6.1.1",
    "mochawesome-merge": "^4.2.0",
    "mochawesome-report-generator": "^5.1.0",
    "typescript": "^4.1.3"
  }
```

Npm Version 6.13.1
Node version 12.16.1

Also tried in a different VM (same dependencies though):
Npm Version 6.14.10
Node version 14.15.4

### Versions
6.3.0

### Workaround
Take the ts-loader from the cached Cypress 6.2.1 and copy paste it (cause this one is 8.0.13) works fine for me, but not sure what kind of side effects this might cause

**Comment by cbruge** [comment]
I updated the original post after significantly reducing my dependencies, now it only shows the ones i really need but im still facing the same issue. Not sure it has anything to do with my dependencies though as the issue lies within the dependencies inside the Cypress Cache...

**Comment by sucy6330133** [comment]
I have ran into the same issue after upgrade to cypress@6.3.0.

**Comment by jennifer-shehane** [comment]
Hmm, I can't reproduce this with the deps in Node 12.16.1. Can you provide:

- tsconfig
- any babel config (like babelrc)
- any plugins/support files

Thanks

**Comment by cbruge** [comment]
Hey @jennifer-shehane after more extensive research (including trying to recreate it with a fresh repo) I found the solution. I deleted the node_modules and package-lock.json. Installed everything fresh and it worked. I could have sworn I tried that before...oh well. 6.3.0 is running smooth now👌🏼

**Comment by sucy6330133** [comment]
Agreed with @cbruge , regenerate the package-lock.json file did fix the issue. However, regenerated package-lock.json is not an option for us since we maintained the package-lock.json file in our repository.
The tsconfig I have got is quite standard.
`{
  "extends": "../tsconfig.json",
  "include": [
    "./**/*.ts"
  ],
  "exclude": [],
  "compilerOptions": {
    "types": [
      "cypress"
    ],
    "lib": [
      "es5",
      "dom"
    ],
    "target": "es5"
  }
}`

.babelrc
`{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "env": {
    "test": {
      "plugins": [
        "istanbul"
      ]
    }
  },
  "plugins": [
    ["@babel/plugin-transform-typescript", { "allowNamespaces": true }],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ]
  ]
}` 

There are only standard plugins/support files.

**Comment by cbruge** [comment]
Hey @sucy6330133 I already closed this issue sorry... @jennifer-shehane is it possible to reopen? Is this something that you can fix?

**Comment by cbruge** [comment]
Adding to the above... @sucy6330133 you could see what changes are there in the package-lock in comparison to the one in your repository and this way you might get a bit closer to the truth. Also it might be possible to commit if the changes are minimal...

**Comment by sucy6330133** [comment]
@cbruge Yeah, my first thought is trying to compare the package-lock file. The changes are so many and very hard to locate the difference which might take effort on this.

**Comment by SleeplessByte** [comment]
FWIW: I ran into this too. Regenerating the lock does _not_ solve it. Downgrading to 7.7.0 didn't work. Downgrading to 6.9.1 didn't either but did yield a different source for the same error:

```
chalk.Instance is not a constructor
    at new TsconfigPathsPlugin (Cypress\Cache\6.9.1\Cypress\resources\app\packages\server\node_modules\tsconfig-paths-webpack-plugin\lib\plugin.js:17:47)
    at getDefaultWebpackOptions (Cypress\Cache\6.9.1\Cypress\resources\app\packages\server\node_modules\@cypress\webpack-batteries-included-preprocessor\index.js:96:31)
```

...so I switched back to JavaScript instead.

**Comment by eppsilon** [comment]
Modifying tsconfig.json fixed this issue for me: https://github.com/cypress-io/cypress/issues/17802#issuecomment-955071058
