### ISSUE TITLE
Expose test retries count in `after:spec` hook

### ISSUE THREAD

**Issue by khitrenovich** [cypress-io/cypress#14706]
### What would you like?
I want access to [retry stats](https://docs.cypress.io/guides/guides/test-retries.html#Can-I-access-the-current-attempt-counter-from-the-test) (specifically, whether any tests had to be retried for the spec to pass) in the `after:spec` hook.

### Why is this needed?
We are using [Test Retries](https://docs.cypress.io/guides/guides/test-retries.html) to make our CI more stable. We are using `after:spec` hook to [delete videos of passed runs](https://docs.cypress.io/api/plugins/after-spec-api.html#Delete-the-recorded-video-if-the-spec-passed). I want to be able to understand whether the test had passed on the first attempt or on a retry, and keep the video if latter - this will help us to investigate flakes.

**Comment by jennifer-shehane** [comment]
Yah, this is *possible* right now. There is an `attempts` array on each test that has all of the information for each retry. My below example is pretty naive (not taking into account multiple failing tests for example) so you could improve upon it based on your use case, but it's just to say that there is a `results.tests[0].attempts.length` available for each test in the results.

```js
const _ = require('lodash')

module.exports = (on, config) => {
  on('after:spec', (spec, results) => {
    const failingTests = _.filter(results.tests, { state: 'failed' })
    
    console.log('FAILING TESTS', failingTests)

    _.each(failingTests, (failingTest) => {
      console.log(failingTest)
      console.log(`${failingTest.title[0]}:`, failingTest.attempts.length + ' Attempts')

      if (failingTest.attempts.length > 1) {
        // The test retried, so let's keep the video
        return
      } else {
        // delete the video
      }
    })
  })
}
```

**Comment by khitrenovich** [comment]
@jennifer-shehane I suspect that by filtering for failed tests you are actually ignoring those that passed after retry...

This is the code I've ended up with - 
```
  // Delete videos of successful specs to reduce artifacts size
  on('after:spec', (spec, results) => {
    if (results.video) {
      // Do we have failures for any of the retry attempts?
      const failures = _.some(results.tests, (test) => {
        return _.some(test.attempts, { state: 'failed' });
      });
      if (!failures) {
        // `del()` returns a promise, so it's important to return it to ensure
        // deleting the video is finished before moving on
        return del(results.video);
      }
    }
    return true;
  });
```

Do you see any corner cases I could've missed here?

**Comment by jennifer-shehane** [comment]
@khitrenovich I believe this should work. You may want to add a check that `results` exist because I think if the run errors completely then results will be undefined.

**Comment by khitrenovich** [comment]
@jennifer-shehane Thank you for noticing, I've just added this check to our existing code. IMHO, we are good to close the issue.
