### ISSUE TITLE
use pfx file with cypress.io

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1472]
Hi, 
I would like to use a certificate (pfx file) with cypress.io. Is it already possible? if yes, how can I use it? a command in cypress.json?

Indeed, I have my app locally on localhost but each time I launch my test with cypress.io, I get error 407 (authentication required). Moreover, the proxy settings of chrome are disable. I don't use a proxy in this case.

Thanks

**Comment by themre** [comment]
were you able to solve this? i'm also facing the same issue.

**Comment by themre** [comment]
may I ask what was the alternative? thanks!
