### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by jngchd** [cypress-io/cypress#14724]
DevTools failed to load SourceMap: Could not load content for http://192.168.80.136:8080/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.

**Comment by Varsha-xiu** [comment]
> DevTools failed to load SourceMap: Could not load content for http://192.168.80.136:8080/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

how do solved it
