### ISSUE TITLE
Cypress getting wrong value for px size

### ISSUE THREAD

**Issue by rajinder-yadav** [cypress-io/cypress#14722]
### Current behavior

Not sure why cypress is not using the value specified in the css class "b1", like this:

```css
.b1 {
  border: 1px solid;
}
```

In the test html file

```
  <div id="b1" class="b1">Borders</div>
```

The following test fails

```js
    it("Border size 1px", () => {
      cy.get("#b1")
        .should("have.class", "b1")
        .should("have.css", "border-top-width", "1px")
    });
```

![snap-02](https://user-images.githubusercontent.com/439226/105621882-45c93500-5dda-11eb-851d-a6d3390bcb51.png)

Yet when I look at the class definition from the browser debug console, it clearly shows the class to have a px size of 1?

![snap-03](https://user-images.githubusercontent.com/439226/105621883-482b8f00-5dda-11eb-8e97-0ae6a7cb10c6.png)

### Versions

6.3.0

**Comment by jennifer-shehane** [comment]
I'm not seeing this with the given example. 

It may be that something within your app is making the computed value of the border width equal 0.999126px? I believe we just evaluate the computed value. Can you click on 'Computed' tab in css dev tools to see what it is there?

`spec.js`

```js
it("Border size 1px", () => {
  cy.visit('index.html')
  cy.get("#b1")
    .should("have.class", "b1")
    .should("have.css", "border-top-width", "1px")
});
```

`index.html`

```html
<html>
  <style>
    .b1 {
      border: 1px solid;
    }
  </style>
<body>
  <div id="b1" class="b1">Borders</div>
</body>
</html>
```

<img width="717" alt="Screen Shot 2021-01-25 at 2 20 46 PM" src="https://user-images.githubusercontent.com/1271364/105676380-d3ab3a00-5f18-11eb-85d7-6a155a67e114.png">

**Comment by rajinder-yadav** [comment]
I took your sample snippet and I'm still getting the same error.

I am using Linux openSUSE Tumbleweed. it looks like Chrome does not behave well.

![snap-01](https://user-images.githubusercontent.com/439226/105779353-26e2b400-5f3c-11eb-9985-a8e20cc9daa4.png)

I tried opening the static HTML file on Chromium, same calculation problem, however on firefox it shows as 1px. 

So I discovered I can use firefox as a browser from cypress, however when I run the test no browser opens? btw firefox is my default browser on my system.

![snap-02](https://user-images.githubusercontent.com/439226/105780067-b0df4c80-5f3d-11eb-84ef-ed6392558c86.png)

**Comment by rajinder-yadav** [comment]
I got firefox to open, however firefox launched by cypress is reporting a value of 0.75px vs firefox opening the file statically as 1px.

I checked that the version on both firefox opened is the same 84.0.2 (64-bit)

![snap-03](https://user-images.githubusercontent.com/439226/105787780-2999d500-5f4d-11eb-9032-6d1abb6aeeed.png)

![snap-04](https://user-images.githubusercontent.com/439226/105787994-9319e380-5f4d-11eb-918e-596bdcf793e7.png)

Just wondering, is there a way for me to check the pixel size with a delta? Say a value between (1px, 0.75px)

**Comment by jennifer-shehane** [comment]
@rajinder-yadav 

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('.b1').should('have.css', 'border-top-width').should((width) => {
    // ensure the unit is in pixels
    expect(width).to.include('px')
    // get Number value and assert
    expect(parseInt(width, 10)).to.be.within(0.75, 1)
  })
})
```

**Comment by Docc0** [comment]
Just adding further weight to this, we're seeing the same issue when checking certain css values.  The magnitude can be more extreme however (2/3/4 pixels) when comparing Chrome rendering to Cypress UI test rendering (same viewport size, etc).  

Could anyone allude to why would this be the case?

**Comment by kindoflew** [comment]
I'm seeing an issue that might be related where a pixel amount I am expecting is off by one with `cypress open` so the test fails, but passes with `cypress run`. 

With `cypress open` I can get the test to pass by altering the size of the viewport either with dev tools open or using the config to make sure the viewport isn't scaled down at all (it's normally scaled to 86% on my screen with the default dimensions). If I scale down the viewport far enough, the value is off by one in the opposite direction. 

I've confirmed with manual testing that the value I expect is correct so probably isn't an issue with my app or browser (firefox 89).

**Comment by luvicsoura** [comment]
I'm also facing this issue of Cypress being off by 1px when getting an element's width. The quick workaround I found was to use getBondingClientRect() instead of relying on JQuery's .width() to get the width of an element.

```javascript
cy.get([data-cy="my-element"]).should(
  ($el) => expect($el[0].getBoundingClientRect().width).to.be.equal(200)
);
```

**Comment by Luttenegger** [comment]
I had a similar issue and found a fix that worked for me. Turns out, I was zoomed out in my browser (at 75%) and that was messing with the styles when the tests were running for some reason in Chrome. When I zoomed back in and brought the browser view back to 100%, the test passed for me and I wasn't getting a sizing error.

**Comment by snout-o** [comment]
I feel my issue is similar to a few on this thread, however changing the zoom level (which I had already tried) simply moved the margin of difference of expected vs actual further out. 

For me, the test always fails in Terminal with the :run command and as if that wasn't bad enough, sometimes the test will pass when I observe in :open only to fail a few moments later (without changing anything). 

Now here's the _really_ good bit, when the test passes the assert message is **exactly the same** as the message when the test fails. In the screenshot below you can see the assert has passed despite the message saying it didn't...ok!

![Screen Shot 2022-07-21 at 2 53 57 pm](https://user-images.githubusercontent.com/505678/180143274-cdbb2e91-0d1c-4ce7-830b-1841a00fba12.png)

Needless to say, I'm confused and would appreciate any further insight. 

Oh and I tried different browsers (the above was Electron 100) but to no avail. Using Cypress GUI 9.7.0 on Mac Monterey 12.4

**Comment by dlatikaynen** [comment]
> cy.get('.b1').should('have.css', 'border-top-width').should((width) => {
>     // ensure the unit is in pixels
>     expect(width).to.include('px')
>     // get Number value and assert
>     expect(parseInt(width, 10)).to.be.within(0.75, 1)
>   })

this does not work for me. the lambda variable `width` ends up being of type `JQuery<>HTMLElement` and the parseInt function rejects that as a compilation error;
also if you expect width to include 'px', would that not fail anyway in parseInt(width)? how is that example supposed to work?
