### ISSUE TITLE
Cannot install cypress 6.3.0 on debian linux - 404 not found

### ISSUE THREAD

**Issue by robertfoobar** [cypress-io/cypress#14720]
### Current behavior
``npm install cypress`` currently fails because https://download.cypress.io/desktop/6.3.0?platform=linux&arch=ia32 returns HTTP 404 Not Found

### Debug logs
npm install output
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code 1
npm ERR! path /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_15/lib/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c node index.js --exec install
npm ERR! Installing Cypress (version: 6.3.0)
npm ERR! 
npm ERR! [00:18:44]  Downloading Cypress     [started]
npm ERR! [00:18:45]  Downloading Cypress     [failed]
npm ERR! [00:18:45] → The Cypress App could not be downloaded.
npm ERR! 
npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR! 
npm ERR! Otherwise, please check network connectivity and try again:
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! URL: https://download.cypress.io/desktop/6.3.0?platform=linux&arch=ia32
npm ERR! Error: Failed downloading the Cypress binary.
npm ERR! Response code: 404
npm ERR! Response message: Not Found
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Platform: linux (Debian - 10)
npm ERR! Cypress Version: 6.3.0
npm ERR! The Cypress App could not be downloaded.
npm ERR! 
npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR! 
npm ERR! Otherwise, please check network connectivity and try again:
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! URL: https://download.cypress.io/desktop/6.3.0?platform=linux&arch=ia32
npm ERR! Error: Failed downloading the Cypress binary.
npm ERR! Response code: 404
npm ERR! Response message: Not Found
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Platform: linux (Debian - 10)
npm ERR! Cypress Version: 6.3.0 
### Download method
- [x] npm (nodejs 15)

### Operating System
- [x] Linux / Debian 10

### Other
- not behind a proxy

**Comment by bahmutov** [comment]
We build a 64 bit version of the Linux test runner and do not built a 32 bit

**Comment by robertfoobar** [comment]
Okay. I was using armv71 which is 32bit.
