### ISSUE TITLE
Syntax Error "(" unexpected on Ubuntu 20.04 when running Cypress 6.3.0

### ISSUE THREAD

**Issue by robertfoobar** [cypress-io/cypress#14725]
### Current behavior

I've installed cypress v6.3.0 via npm v14.15.3 on Linux/Ubuntu 20.04 
When running cypress, I receive the following error: 

> my-project@1.0.0 test /home/robert/repos/my-project
>  cypress run
> 
>  It looks like this is your first time using Cypress: 6.3.0
> 
>  ✖  Verifying Cypress can run /home/robert/.cache/Cypress/6.3.0/Cypress
>    → Cypress Version: 6.3.0
> Cypress failed to start.
>
>This is usually caused by a missing library or dependency.
>
>The error below should indicate which dependency is missing.
>
>https://on.cypress.io/required-dependencies
>
> If you are using Docker, we provide containers with all required dependencies installed.
>
>----------
>
> /home/robert/.cache/Cypress/6.3.0/Cypress/Cypress: 1: Syntax error: "(" unexpected
>
> ----------
>
>Platform: linux (Ubuntu - 20.04)
>Cypress Version: 6.3.0
>npm ERR! Test failed.  See above for more details.

I installed all dependencies as listed here: https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup

### Desired behavior
cypress verification should succeed

### Test code to reproduce
cypress already fails in "verifying Cypress can run" - phase. So it's not connected to my tests I suppose.

### Versions

* cypress 6.3.0
* I already tried 6.2.1 which also fails verification but with another error message
* OS: Linux / Ubuntu Server 20.04.1 LTS 64bit for Raspberry Pi 4
* node v14.15.4 (node v12.20.1 fails with same error)

**Comment by ankushkatiyar** [comment]
Hi I'm still facing same problem while install cypress in ubuntu 
Jenkins server already installed in ubuntu OS, and i'm executing jenkins file in pipeline and this jenkins file installing npm dependencies ( cypress )

**Comment by Ari24-cb24** [comment]
Hello there, still facing the same issue (using chromeos).
Any known work-around?
