### ISSUE TITLE
SRI integrity attribute fails to get rewritten when launching a page

### ISSUE THREAD

**Issue by yabyab** [cypress-io/cypress#14726]
### Current behavior
As the code failed to re-written the integrity. All dependent resource from web site fails to download. Which lead the page loads fail or stuck in loading. Bug log as below:
![Screen Shot 2021-01-25 at 10 15 14 AM](https://user-images.githubusercontent.com/7196625/105653258-4bb43880-5ef6-11eb-9391-bd198a679c12.png)

### Desired behavior
Page is successfully launch. Which is same behavior as other web driver like selenium or puppeteer.

### Test code to reproduce
Test code to reproduce the issue
`it('fails to pass SRI', function () {
 cy.visit("https://www.casetify.com")
})`

### Versions
Cypress 6.3.0
Chrome 87.0.4280.141
macOS Catalina 10.15.6

**Comment by jennifer-shehane** [comment]
We have a potential fix available for this starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments).Can you try setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by yabyab** [comment]
After applied the configuration option, different failure is prompted.
![Screen Shot 2021-01-25 at 5 45 45 PM](https://user-images.githubusercontent.com/7196625/105689195-69ed5900-5f35-11eb-9bf2-dd1b2ea6626e.png)
<img width="637" alt="Screen Shot 2021-01-25 at 5 47 23 PM" src="https://user-images.githubusercontent.com/7196625/105689208-6d80e000-5f35-11eb-9ab3-647831f834b4.png">

Test code and versions are remain as the same

**Comment by linture** [comment]
any update? running into the same issue...

**Comment by linture** [comment]
solved by adding this config
`"modifyObstructiveCode": false`
