### ISSUE TITLE
Clear date field in calendar cypress test filed

### ISSUE THREAD

**Issue by Dovile22** [cypress-io/cypress#14730]
I would like to run a test in cypress (v6.0.0). I need to clear default values if calendar it match 4 values.  However, when I try to clear the field cypress throws an error.

```js
 cy.get('.ant-calendar-range-picker-input').clear({force: true}).should('have.value', '')
```

![image](https://user-images.githubusercontent.com/77967032/105698912-444d5900-5f0f-11eb-89a7-3165c83831e1.png)

![image](https://user-images.githubusercontent.com/77967032/105698962-53cca200-5f0f-11eb-9729-25fdcde2d139.png)

**Comment by jennifer-shehane** [comment]
@Dovile22 You're using an Ant components? Can you create a test against the exact component your using and provide that?

```js
cy.visit('https://ant.design/components/date-picker/')
// which component are you trying to clear?
```

**Comment by Dovile22** [comment]
I am not shore how is correctly to write in test ?
![image](https://user-images.githubusercontent.com/77967032/105821991-2aba1900-5fc4-11eb-9b6a-55aa6ae7c16c.png)
![image](https://user-images.githubusercontent.com/77967032/105822070-43c2ca00-5fc4-11eb-9af4-b0cd448f7f5c.png)

**Comment by Dovile22** [comment]
@jennifer-shehane  can you help me ?
![image](https://user-images.githubusercontent.com/77967032/107644561-40943300-6c80-11eb-9f49-fb4111872d14.png)

**Comment by Dovile22** [comment]
issue resolved
