### ISSUE TITLE
file download not working in electron

### ISSUE THREAD

**Issue by ruudgrosmann** [cypress-io/cypress#14747]
In spite of the anouncement that file download is now working with cypress 6.3.0, this is not yet the case for electron.
My test scenario that downloads a file works when using chrome, but the UI exits when electron browser is selected

### Current behavior

I have a step in which I click a download link. This appears on the console, while cypress exits by closing all windows and returning to the command prompt.

```
GET /TV052020_275039.pdf 200 44.374 ms - -
GET /_next/static/chunks/fonts/SourceSansPro-Italic~bjvXUARt.woff 200 24.019 ms - -
Error: ERR_FAILED (-2) loading 'https://mysite.com/TV052020_275039.pdf'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:205:1868)
    at Object.emit (events.js:315:20)
 {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'https://mysite.com/TV052020_275039.pdf'
}
Error: ERR_FAILED (-2) loading 'https://mysite.comTV052020_275039.pdf'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:205:1868)
    at Object.emit (events.js:315:20)
/home/rdgon/.cache/Cypress/6.3.0/Cypress/Cypress[632505]: ../../third_party/electron_node/src/api/callback.cc:245:MaybeLocal<v8::Value> node::MakeCallback(v8::Isolate *, Local<v8::Object>, Local<v8::Function>, int, Local<v8::Value> *, node::async_context): Assertion `(env) != nullptr' failed.
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.
```
### Desired behavior
At least a message in the UI while not exiting to the command prompt, but normal downloading preferred.

### Versions
Platform: linux (Ubuntu - 20.04)
Cypress Version: 6.3.0

**Comment by ruudgrosmann** [comment]
It looks it might be a content problem.

**Comment by ruudgrosmann** [comment]
In the downloads folder, I can actually find the downloaded file, which is a valid pdf in this case.. So somethings happens in cypress after the downloading itself

**Comment by jennifer-shehane** [comment]
I wasn't able to recreate this in Electron with a standard anchor link download pointing to a local PDF file. I'm seeing the file in the downloads folder and no crashing or errors. 

Looks like this issue https://github.com/cypress-io/cypress/issues/8865 - which some people had indicated pre-6.3.0 that their download prompt may be causing this crashing, but they said updating to 6.3.0 solved the issue. 

Make sure you'r using 6.3.0 - print `cypress version`.

Could you provide a reproducible example? Maybe some other code around your downloading of the file could be causing the issue. 

`index.html`

```html
<html>
<body>
  <a id="download-pdf" href="testing.pdf" download>test.pdf</a>
</body>
</html>
```

`spec.js`

```js
it('Test', () => {
  cy.visit('index.html')
  cy.get('#download-pdf').click()
  cy.readFile('cypress/downloads/testing.pdf').should('not.be.null')
})
```

<img width="681" alt="Screen Shot 2021-01-27 at 2 36 32 PM" src="https://user-images.githubusercontent.com/1271364/105961595-1736ad00-60ad-11eb-8262-28a8bae9500b.png">

**Comment by ruudgrosmann** [comment]
The difference between your code and mine is that I use cucumber for the steps. So I have a scenario like  
```
Scenario: doc12: article document download
    When I open document TV052020_275039
    And  I click on the article download link
    Then the download file should be PDF
```
and step definition
```
And('I click on the article download link', () => {
  cy.getByTestId('downloadLinks')
    .find('li:first a')
    .as('downloadLink');
    cy.get('@downloadLink').click();
});
```
Cypress crashes during the second step. Can the use of cucumber be of influence?

**Comment by jennifer-shehane** [comment]
Please update to the [current version of Cypress](https://on.cypress.io/changelog) - we've since implemented full support for downloading files, which includes Electron.
