### ISSUE TITLE
Remote address has different port than application port 

### ISSUE THREAD

**Issue by devamani83** [cypress-io/cypress#14740]
My application use port 9000 but the cypress use random port number and does not load the landing page.  

Cypress IDE: 
![image](https://user-images.githubusercontent.com/13065329/105759795-dc9f0a00-5f1e-11eb-8fd2-87dcb12d9f22.png)

Application url in Chrome browser
![image](https://user-images.githubusercontent.com/13065329/105759855-f6d8e800-5f1e-11eb-828d-6698e016636c.png)

Please see the difference in the remote address between these two pictures.  I am not sure how to let Cypress to use the application port instead of its own random port number.

**Comment by jennifer-shehane** [comment]
There's a `port` configuration available for the port used to host Cypress. https://on.cypress.io/configuration#Global

**Comment by devamani83** [comment]
@jennifer-shehane - I am able to set the port number in the Cypress.json file.  However,  the Cypress IDE is not loading the application and returns for application api endpoints.  Please see the below screenshare.  But the application works fine outside of Cypress IDE and in browsers.  

![image](https://user-images.githubusercontent.com/13065329/105856466-47038900-5fb7-11eb-8fa4-24114bd5a893.png)

**Comment by bagedevimo** [comment]
We've also started seeing this recently. Our use case is coming back from a Stripe checkout payment after 3DS, and the remote address is showing as a different port which means that Chrome treats it as a different-origin cookie, and blows up with the new sameSite origin cookies.

**Comment by ReactQQ** [comment]
Ok, I spoke with programers and the reason is that we're expecting Pascal case names of headers.
Is there configuration in cypress for this?

**Comment by githubaja** [comment]
@ReactQQ 
Any luck with this? I'm having the exact same problem. Remote address is 127.0.0.1 and it makes no sense to me....

**Comment by ReactQQ** [comment]
@githubaja 
It seems that remote address is not the problem, because Cypress IDE is working here like some kind of "router".
The root cause of mine problem was lying inside our application.

Somewhere in communication between backend and frontend(in my case it was request for translations), expected "PascalCase" headers name in request, but Cypress IDE is changing it to lower case and application couldn't consume it.
Developers have changed endPoint requirements and now it's working properly.

**Comment by flotwig** [comment]
Yes, this is not a bug. Cypress runs a proxy through which all requests are sent. The "Remote Address" in Chrome will thus display the proxy host and port instead of the destination server. If there is an issue with Cypress's proxying please open a new issue.

**Comment by faridescate** [comment]
For future reference, I had a similar issue and the root of cause was that cypress was removing the origin header to the request. After intercept the request and putting back the header origin the request was successful.

```js
  cy.intercept('GET', 'https://back.**something.com/**', (req) => {
    req.headers['origin'] = 'https://www.something.com';
  });
```
