### ISSUE TITLE
Setting watchForFileChanges to false keeps the Studio open

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#14744]
### Current behavior

Steps to replicate:
1. set `watchForFileChanges` to `false` in `cypress.json`
2. open a test and start a studio
3. interact with your app and click on "save commands"
4. nothing happens, studio remains open, however, scneario is added to my test file - multiple times if I click the button multiple times. which I do, because it feels unresponsive 🙈

### Desired behavior

When the `watchForFileChanges` is set to `true`, clicking on „save commands“ will close the studio. I believe this would be better UX for this case as well

### Test code to reproduce

I explored this in my stream, you can [see the behavior at 16:20](https://youtu.be/f_GAyKdD8OE?t=981)

### Versions
Cypress 6.3.1

**Comment by jennifer-shehane** [comment]
Love finding bugs in a live demo. 😅 Thanks for helping track down the cause. I can recreate this.

**Comment by filiphric** [comment]
yeah, that will keep you alert 😆
