### ISSUE TITLE
Failure in test causing actions (.type(), .click()) in afterEach to not work

### ISSUE THREAD

**Issue by Tarig0** [cypress-io/cypress#1477]
## Current behavior:

When a test fails in the "it" function the afterEach function is no longer able to type.

### Desired behavior:

type should always function regardless of failures in test

### How to reproduce:

https://github.com/Tarig0/cypress-test-tiny

- Operating System:Win 10
- Cypress Version: 2.1
- Browser Version: Chrome 64

**Comment by jennifer-shehane** [comment]
This is very weird. Can confirm. The `afterEach` test code does run, yet the `.type()` functionality specifically does not appear to be working. The `.type()` *only* does not work if the test fails. 

My example - to prove it was not some weird issue with google site - 
```js
context('Actions', () => {
  beforeEach(() => {
    cy.visit('http://example.cypress.io/commands/actions')
  })

  afterEach(() => {
    cy.get('.action-email').clear()
      .type('fake@email.com').should('have.value', 'fake@email.com')
  })

  it('type into a DOM element', () => {
    cy.get('.action-email').should('have.value', 'a')
  }
})
```

Also, this error appears as if some subject has changed incorrectly. 
<img width="1568" alt="screen shot 2018-03-19 at 2 36 34 pm" src="https://user-images.githubusercontent.com/1271364/37615162-f78355ce-2b82-11e8-978e-2aa40c307f55.png">

**Comment by Tarig0** [comment]
Added another case to show that the element is being found and can be set by 
```js
.then(($el) => $el.val('speed'))
```

**Comment by AaronRohrbacher** [comment]
Having this problem with `.click()` as well, also only in an afterEach function when the previous test has failed.

**Comment by rasmusvhansen** [comment]
I am also seeing this. `.click()` simply seems to stop working in afterEach if a test has failed.
This is kind of a showstopper, as it prevents cleanup after failing tests...

**Comment by toannguyen83** [comment]
I'm having the same issue. In the afterEach i need to perform cleanup after each test, undoing certain UI actions, but if the test failed, any action in afterEach doesn't work properly.

I have to do a weird workaround for now, having my clean up code in `beforeEach`, but, it won't perform clean up on the last test, so I need to also add a dummy test to the very end.

**Comment by stevenvachon** [comment]
`visit()` also does not work in `after()`/`afterEach()`.

**Comment by jennifer-shehane** [comment]
Going to close this in favor of #2831
