### ISSUE TITLE
cy.contains throws syntax error if searched text ends with backslash

### ISSUE THREAD

**Issue by JonahKK** [cypress-io/cypress#14772]
### Current behavior

If searched text has backslash (`\`) at the end, the `cy.contains` command ends with
```
Syntax error, unrecognized expression: :not(script,style):cy-contains('testValue'), [type='submit'][value~='testValue']
```
![image](https://user-images.githubusercontent.com/23238398/105972148-9b783880-608b-11eb-8647-e0370d689b5b.png)

### Desired behavior

`cy.contains` should search for a text with the backslash at the end.

### Test code to reproduce

```js
describe('page', () => {
  it('fails', () => {
    cy.contains('testValue\\').should('not.exist');
  })
})
```

### Versions
Tested on newest 6.3.0.

**Comment by jennifer-shehane** [comment]
Cypress uses a modified jQuery selector, so you'd have to do what you would do in jQuery to find backslashes in selectors, which apparently means that you need to write four backslashes for every backslash you want to find in the app. 

So:

1. original content: `testValue\`
2. escape backslash for jQuery selector `testValue\\`
3. escape each backslash for JS string `'testValue\\\\'`

`index.html`

```html
<html>
<body>
  <button>testValue\</button>
</body>
</html>
```

`spec.js`

```js
it('fails', () => {
  cy.visit('index.html')
  cy.contains('testValue\\\\')
})
```

<img width="648" alt="Screen Shot 2021-01-28 at 1 52 54 PM" src="https://user-images.githubusercontent.com/1271364/106103968-23d00980-6170-11eb-93f9-8ad99e048ab0.png">
