### ISSUE TITLE
Cypress timeout when I try to interact with browser

### ISSUE THREAD

**Issue by deebandrawis** [cypress-io/cypress#14770]
I have 175 cypress tests that run locally with no problems , but when I try to run on jenkins from specific test when the test try to interact with the browser I get a timeout , and then all the tests fail on the same timeout when they try to interact with the browser. the test that fails :

```
describe('Data Source bulk actions', () => {
  beforeEach(() => {
    cy.task('dropDB').then(() => {
      cy.viewport(1920, 1080);
      cy.login();
      cy.closeOnboardingModal();
    });
  });

  afterEach(function() {
    cy.logout();
  });

  it('bulk of enable/disabled', () => {
    createSeveralDs();
```

the error I get : 

```
Error Message Timed out after waiting 60000ms for your remote page to load. Your page did not fire its load event within 60000ms. You can try increasing the pageLoadTimeout value in /e2e-tests/cypress-ci.json to wait longer. Browsers will not fire the load event until all stylesheets and scripts are done downloading. When this load event occurs, Cypress will continue running commands. Because this error occurred during a before each hook we are skipping the remaining tests in the current suite: Entity Source Stacktrace CypressError: Timed out after waiting 60000ms for your remote page to load.

Your page did not fire its load event within 60000ms.

You can try increasing the pageLoadTimeout value in /e2e-tests/cypress-ci.json to wait longer.

Browsers will not fire the load event until all stylesheets and scripts are done downloading.

When this load event occurs, Cypress will continue running commands.

Because this error occurred during a before each hook we are skipping the remaining tests in the current suite: Entity Source at timedOutWaitingForPageLoad (https://bigid-ui/__cypress/runner/cypress_runner.js:156924:13) at https://bigid-ui/__cypress/runner/cypress_runner.js:157907:16 at tryCatcher (https://bigid-ui/__cypress/runner/cypress_runner.js:10609:23) at https://bigid-ui/__cypress/runner/cypress_runner.js:5731:41 at tryCatcher (https://bigid-ui/__cypress/runner/cypress_runner.js:10609:23) at Promise._settlePromiseFromHandler (https://bigid-ui/__cypress/runner/cypress_runner.js:8544:31) at Promise._settlePromise (https://bigid-ui/__cypress/runner/cypress_runner.js:8601:18) at Promise._settlePromise0 (https://bigid-ui/__cypress/runner/cypress_runner.js:8646:10) at Promise._settlePromises (https://bigid-ui/__cypress/runner/cypress_runner.js:8722:18) at _drainQueueStep (https://bigid-ui/__cypress/runner/cypress_runner.js:5316:12) at _drainQueue (https://bigid-ui/__cypress/runner/cypress_runner.js:5309:9) at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://bigid-ui/__cypress/runner/cypress_runner.js:5325:5) at Async.drainQueues (https://bigid-ui/__cypress/runner/cypress_runner.js:5195:14) From Your Spec Code: at Context.eval (https://bigid-ui/__cypress/tests?p=cypress/support/index.js:866:6)
```

any idea ? I tried to call visit from the test and not from the before I tried to delete onBeforeLoad from login function . also tried to change visit('/') to visit('') , also didn't work. I also tried to update cypress from 6.2.1 to 6.3.0 also didn't help .

**Comment by deebandrawis** [comment]
it was solved , it looks in some code I call an http request and that caused the failure

**Comment by assafey** [comment]
+1

**Comment by BlueWinds** [comment]
First, it can make your comments a lot easier to read when you use codeblocks (triple ticks surrounding code snippets). I edited some into your initial comment to make it easier to tell what's going on. :)

It's hard to tell what's going on just from what you provided, but notice this:

`Because this error occurred during a before each hook...`

It's definitely something in the beforeEach hook. At a guess, something in your `cy.login();` command - it's visiting a page and the page isn't loading for some reason.

One thing to consider would be moving this hook into the body of a test and enabling video recording - you might be able to learn more from watching a video of the test.

**Comment by deebandrawis** [comment]
Many thanks of your comment . 
there is no problem with url because the first 10-15 tests pass with the same url ,and then it hangs . 
we run our env with dockers so it looks like nginx stuck because of the access log that cypress send , it happens only when we run cypress .
