### ISSUE TITLE
PSoC 6 (CY8CKIT_062_WIFI_BT) AWS IOT With Enterprise Security Connection

### ISSUE THREAD

**Issue by Anudeep09** [cypress-io/cypress#14779]
Hi,

I wanted to connect and publish data to AWS IOT cloud from PSoC® 62S2 Wi-Fi BT Pioneer Kit (CY8CKIT-062S2-43012) using enterprise security WiFi connection.

I have added the **mbed-client-for-aws.lib** to the **mbed-os-example-enterprise-security** example project and while building the application getting some includes missing compilation errors and redefinition for multiple variables in mbed-os driver files.

Please help me resolve the issues and let me know the document source for the projects merging/porting guide. 

Please find attached error.
![Capture](https://user-images.githubusercontent.com/19724674/105993078-ec0f8600-60cb-11eb-8ec9-3908df9593d1.JPG)

**Comment by bahmutov** [comment]
I think you need to ask Cypress Semiconductors https://www.cypress.com/
