### ISSUE TITLE
_currentRetry value in beforeEach hook is always 0

### ISSUE THREAD

**Issue by adesko** [cypress-io/cypress#14783]
### The issue
We use a command to reset the database before each spec is run. Unfortunately, it is quite slow (takes about 7 seconds to reset DB fixtures), so we can't really execute it in a beforeEach hook as that would slow down the tests significantly. However, if a test fails mid-execution, it can make some changes in the database that will prevent the test from retrying.
I wanted to make a workaround where i would execute the DB reset command in a beforeEach hook if the current attempt counter is above 0, but that didn't work (see current behavior below).
If there is any other way to make this work, please let me know.

### Current behavior
When accessing attempt counter in the beforeEach hook (as described [here](https://docs.cypress.io/guides/guides/test-retries.html#Can-I-access-the-current-attempt-counter-from-the-test)), the attempts counter is 0 regardless of actual attempt count.

![изображение](https://user-images.githubusercontent.com/29997619/106013670-b9668d00-60cd-11eb-9ca3-2da9b48575bc.png)

### Desired behavior
Since the beforeEach hook is executed for each test attempt, i expected the attempt counter to contain current attempt counter.

### Test code to reproduce
```js
describe('Home page', () => {
    beforeEach(() => {
        console.log('---Start new attempt---');
        const attempt = cy.state('runnable')._currentRetry;
        console.log('Attempt count in "beforeEach": ' + attempt);
    });
    it.only('Opens homepage', {
        retries: {
            openMode: 1,
        },
    }, () => {
        cy.visit('https://github.com');
        cy.contains('not github');
        const attempt = cy.state('runnable')._currentRetry;
        console.log('Attempt count in test: ' + attempt);
    });
});
```

### Versions
6.3.0

**Comment by B4Art** [comment]
I am not an expert, but I am missing somethin like:
```
const retries = cy.state('runnable')._retries
```
or:
```
const retries = Cypress._.get(cy.state('runnable'), '_retries', 0)
```
Which is on the page you are referring to. Does that have anything todo with this?

**Comment by adesko** [comment]
> 
> 
> I am not an expert, but I am missing somethin like:
> 
> ```
> const retries = cy.state('runnable')._retries
> ```
> 
> or:
> 
> ```
> const retries = Cypress._.get(cy.state('runnable'), '_retries', 0)
> ```
> 
> Which is on the page you are referring to. Does that have anything todo with this?

I'm pretty sure this is just to access the total number of retries possible, and has nothing to do with what i'm describing

**Comment by MDjhowley** [comment]
@adesko I have testing using this solution and it seems to work: https://github.com/cypress-io/cypress/issues/8404#issuecomment-680122825

perhaps the documentation should be expanded to reference this? FYI `cy.state` has open ticket for documentation... (https://github.com/cypress-io/cypress-documentation/issues/108)

**Comment by adesko** [comment]
@MDjhowley Thanks for the reply! However, i already implemented another solution using the cypress module that re-runs failed specs.

**Comment by sainthkh** [comment]
Sorry for the late reply. Closing in favor of #8404.
