### ISSUE TITLE
Downloading dynamically generated file fails when Cypress does not detect page load

### ISSUE THREAD

**Issue by jimpriest** [cypress-io/cypress#14789]
### Current behavior
Was playing around with the new download feature in 6.3.0 but that functionality seems to be  targeted at simply downloading a file from a link.

I am dynamically generating a file on the server (via ColdFusion) and serving it through the browser.  These are mainly reports.  A user selects several 'filter' drop downs to select what data they want and then they click submit to generate a report.  ColdFusion processes this on the backend and then serves the file through the browser.

See: https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-c/cfcontent.html

So in 6.3.0 I submit my form, the file is downloaded to cypress/downloads (yay) but the actual Cypress test fails while waiting for a page load which never happens.

This is also similar to #8619, #7083

Searching it seems there have been quite a few issues opened for some way to stop or intercept a page load.

### Desired behavior
Once the file is downloaded have Cypress stop waiting for page load.

### Versions
Cypress 6.3.0

**Comment by jennifer-shehane** [comment]
Can you provide an example, html/js of a download where the page load is causing Cypress to fail? It'd be helpful for looking into the issue or creating a workaround. 

Our example recipes has an example with using a form `action` to download a file, and that test works in that situation. https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download

**Comment by jimpriest** [comment]
Looking at the testing-dom_download example it's just using a simple GET request.  

CFML Example
```
<cfheader name="Content-disposition" value="attachment;filename=#somefile#">
<cfcontent file="#somefile#" type="application/pdf">
```

PHP Example
```
$filePath="file path here";
$filename="file name here";
header('Content-type:application/pdf');
header('Content-disposition: inline; filename="'.$filename.'"');
header('content-Transfer-Encoding:binary');
header('Accept-Ranges:bytes');
@ readfile($filePath);
```

Node Example
```
app.post('/url/to/hit', function(req, res, next) {
  var stream = fs.readStream('/location/of/pdf');
  var filename = "WhateverFilenameYouWant.pdf";
  // Be careful of special characters
  filename = encodeURIComponent(filename);
  // Ideally this should strip them
  res.setHeader('Content-disposition', 'inline; filename="' + filename + '"');
  res.setHeader('Content-type', 'application/pdf');
  stream.pipe(res);
});
```

**Comment by maaaariana** [comment]
Hi @jennifer-shehane
I am also facing this issue
I can't stop cypress from waiting for a nonexistent page to load after downloading a file

**Comment by pitgrap** [comment]
I get the same issue with 6.5.0 and a file download via XHR (POST) and not a simple GET.
The file download works, but Cypress is waiting for a page load until timeout.

**Comment by jennifer-shehane** [comment]
Can anyone provide a reproducible example that we can run completely? An HTML/JS file or a repo would be ideal. That was we can investigate.

**Comment by SyafiqHadzir** [comment]
> I get the same issue with 6.5.0 and a file download via XHR (POST) and not a simple GET.
> The file download works, but Cypress is waiting for a page load until timeout.

I get the same issue with 6.6.0.

**Comment by bahmutov** [comment]
@SyafiqHadzir Can anyone provide a reproducible example that we can run completely? An HTML/JS file or a repo would be ideal. That was we can investigate.

**Comment by jimpriest** [comment]
I started on a CFML example - will try and complete that today.  It's a Docker repo so should work stand alone.

**Comment by jimpriest** [comment]
I cobbled this example together: https://github.com/jimpriest/cfml-cypress-download

See readme for info - simple link to a dynamically delivered file which fails in Cypress.

**Comment by ngandymov** [comment]
Hi @jimpriest , you can find a workaround here - https://github.com/cypress-io/cypress/issues/14857

**Comment by jimpriest** [comment]
Yay.  Been away from Cypress for a bit but this workaround in #14857 seems to work for me.  
Thanks @ngandymov.
