### ISSUE TITLE
add an option to create some kind of annotation

### ISSUE THREAD

**Issue by danielzzz** [cypress-io/cypress#14780]
### What would you like?
It would be great to have an option to add annotations on the screen while test are being executed

### Why is this needed?
Cypress could be a great too to create instructional video for websites.
I imagine, to be able to record the whole test and adding some kind of captions on the screen describing what is happening, for example:
"once you open the page, fill in the login form with your data and click login"
** user sees the login form being filled, clicked an goes to the next page
"this is you control panel, you can do ...."
** the app shows all the options according to the test script

kind regards
dan

**Comment by bahmutov** [comment]
Take a look at http://github.com/bahmutov/cypress-movie project

**Comment by danielzzz** [comment]
that's great, thanks!
