### ISSUE TITLE
Cypress removing certain headers in Chrome

### ISSUE THREAD

**Issue by amartinez1558** [cypress-io/cypress#14791]
We currently have a feature where the UI adds the request header under certain conditions

"Accept-version": "4.0" 

Unfortunately, when I test in a normal browser it appears. But in the test runner, it does not appear which makes it so we can't create a test. The odd thing is that we have another custom header that works just fine. My only suspicion is that the header is lower case for the second word, but I feel that shouldn't matter.

![image](https://user-images.githubusercontent.com/53919283/106078773-d056b080-60c8-11eb-8fcd-9214f86de7f4.png)
![image](https://user-images.githubusercontent.com/53919283/106078806-e3698080-60c8-11eb-8a9b-a6942aaaebec.png)

Is this header treated differently? I also noticed that there is no Origin header either.

**Comment by amartinez1558** [comment]
This bug is not present in 5.6.0. But when I change to 6.0, the header is removed.

**Comment by jennifer-shehane** [comment]
@amartinez1558 Can you provide a reproducible example of this situation? What tests does this happen within?
