### ISSUE TITLE
Support different response timeouts based on URL patterns

### ISSUE THREAD

**Issue by danmaftei** [cypress-io/cypress#14799]
### What would you like?
The `responseTimeout` configuration setting applies to all requests. It would be nice to be able to set different response timeouts depending on the requested URL.

### Why is this needed?
Our app supports routes with different timeouts (e.g. a regular `/api` route and an `/api-bg` for longer-running requests). If we set `responseTimeout` to match our `/api` route timeout, and a test makes an `/api-bg` request, `cy.wait()` might time out prematurely.

**Comment by jennifer-shehane** [comment]
You can pass a different `responseTimeout` to `cy.wait()` depending on what you're waiting on. The regex depends on what you need exactly, but the example below shows how this is possible. Does this meet your requirements?

```js
cy.intercept(/api[^-]/).as('api')
cy.intercept(/api-bg/).as('api-bg')

cy.wait('api', { responseTimeout: 20000 })
cy.wait('api-bg', { responseTimeout: 90000 })
```
