### ISSUE TITLE
Binding expression "true" cannot be assigned to.

### ISSUE THREAD

**Issue by sleknizi** [cypress-io/cypress#14802]
### Current behavior
I'm automating ui tests of an Aurelia application with cypress (wiche use binding events in web elements), but I'm getting this error 'Binding expression "true" cannot be assigned to.' when calling cypress  actions (check, select, click ...) on elements
<img width="960" alt="CypressCheckError" src="https://user-images.githubusercontent.com/48132821/106159830-7ec02b80-6185-11eb-946c-5b8502474ab3.png">

### Test code to reproduce
Here is the testes application HTML code : 
```html 
<input type="checkbox" checked.bind="todo.done" data-id="input.checkbox.done-${$index + 1}">
      <span css="text-decoration: ${todo.done ? 'line-through' : 'none'}">
        ${todo.description}
      </span>
```
<img width="875" alt="WebPage" src="https://user-images.githubusercontent.com/48132821/106159890-8da6de00-6185-11eb-9db8-663234d7bd98.png">

Here is cypress code
```js 
cy.get('input[data-id="input.checkbox.done-' + todoNumber + '"]').check()
```

### Versions
Cypress version: 6.3.1

**Comment by bahmutov** [comment]
Please create a small repo with full code (it can be as simple and small as you want) that we can clone, install and run tests in to see the problem.

**Comment by sleknizi** [comment]
Hello @bahmutov 
Thanks for your reply. I have created two repositories [https://github.com/sleknizi/todos-app](url) for the tested web application and [https://github.com/sleknizi/Cypress_issue_14802](url) for test project with Cypress
Please clone or download the projects then : 

1. Install and run The todos web application first (following the [readme](https://github.com/sleknizi/todos-app/blob/master/README.md) file instructions)
2. Run Cypress tests (following the [readme](https://github.com/sleknizi/Cypress_issue_14802/blob/master/README.md) file instructions)

**Comment by jennifer-shehane** [comment]
@sleknizi All of these links to repos 404. Can you provide the correct links to repos?

The error seems to be coming from your application code - did you check Devtools console?

**Comment by sleknizi** [comment]
Hello @jennifer-shehane 
Yes, I have checked the console, what makes me sure about the error source is Cypress is the fact that we have automated the same tests with other frameworks (Robot, selenium...) and we haven't got this error, even with manual tests the error is not thrown.
Here are the links to the public repositories, 

-  [Aurelia project](https://github.com/livre-blanc-adtf2020/todos-kdt-with-robot-framework) : to run app

1. Download or clone the app
2. Run `sudo npm install -g aurelia-cli`
3. Run [cd path/to/project](url)
4. Run `npm install`
5. Run `au run --open`
- [Cypress project](https://github.com/sleknizi/Cypress_issue_14802)

**Comment by jennifer-shehane** [comment]
This error is being thrown in your app outside of Cypress. Run the Aurelia project, type in the todo, and hit submit button, check devtools console. 

The reason this is not causing errors in Selenium, etc is because they do not fail tests on uncaught exceptions in your app. Cypress fails the test so that you can find uncaught errors. 

![](http://g.recordit.co/aaZGe53Pwh.gif)

I suggest fixing the error in your app. If you want to ignore the uncaught exception from your app and just let Cypress move on and not fail the test, you can ignore them using this code: https://on.cypress.io/catalog-of-events#To-turn-off-all-uncaught-exception-handling
