### ISSUE TITLE
Cypress does not load contents of a dropdown control & also does not load search contents

### ISSUE THREAD

**Issue by BiswajitNanda** [cypress-io/cypress#14803]
As an open source project with a small maintainer team, it may take some time for your issue to be addressed. Please be patient and we will respond as soon as we can. 🙏 -->

### Current behavior

I am working on a web application which opens a page while selecting an option from the menu. **When cypress loads the page, it does not load the values for a dropdown.** 

Secondly, there is a search page. When search criteria is provided and clicked on search button, it does not populate the contents but it shows a loading icon. 

Strangely, both are working fine in the browser without cypress. cypress does not even throw any error for both these cases,

### Desired behavior
cypress should populate values in the dropdown 
and 
for the search, it should populated the values.

### Versions

<img width="155" alt="Screenshot 2021-01-28 at 16 12 24" src="https://user-images.githubusercontent.com/7164478/106166428-13298e80-6184-11eb-9f88-614d27059b94.png">
<img width="777" alt="Screenshot 2021-01-28 at 16 12 44" src="https://user-images.githubusercontent.com/7164478/106166433-145abb80-6184-11eb-8977-fa923a332640.png">

Cypress package version: 6.2.1

**Comment by bahmutov** [comment]
Can you open the DevTools console and see if there are any errors? Can you create a tiny example with the test and the code you are using to create the dropdown?

**Comment by BiswajitNanda** [comment]
Thanks Gleb, I am seeing an error in the Dev tools. Attaching it
<img width="1262" alt="Screenshot 2021-01-29 at 09 47 29" src="https://user-images.githubusercontent.com/7164478/106259441-25084180-6217-11eb-9088-89a6a970a1d0.png">

**Comment by BiswajitNanda** [comment]
Any pointer please?

**Comment by jennifer-shehane** [comment]
@BiswajitNanda Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
