### ISSUE TITLE
cy.type() can only be called on textarea or text:

### ISSUE THREAD

**Issue by Evgen163Rabbit** [cypress-io/cypress#1481]
Hey all. At first, sorry for my english, its bad
need to type text in the form. How to do this not only with the cy.type command. Is it possible?

Ubuntu 16.04
cypress version 2.1.0
![selection_002](https://user-images.githubusercontent.com/37582973/37656838-9d1c2fd0-2c62-11e8-9390-a389d119600c.png)

/code
cy.get('.textField_question-0-155').type('sad')
/code
``
![selection_001](https://user-images.githubusercontent.com/37582973/37656319-24211362-2c61-11e8-837b-c388c220b13d.png)
What is problem? Thanks

**Comment by Tarig0** [comment]
The problem is that Cypress wants an input tag or textarea tag. Though doing a quick google you can get div's to respond to key events if you do some hacking. Is this site publicly available? Are there no Input html elements?

https://stackoverflow.com/questions/6633248/how-to-grab-keyboard-events-on-an-element-which-doesnt-accept-focus

**Comment by Evgen163Rabbit** [comment]
Thanks for answer. I dont have input elements, and this site is not publicly. i saw tabindex, but i dont it in my page code. All what i have its  "div" with .textField_question-0-155

**Comment by Tarig0** [comment]
Can you make a video of the interaction with the app?

**Comment by jennifer-shehane** [comment]
Related proposal to turn off validation checking with type: https://github.com/cypress-io/cypress/issues/586

**Comment by Evgen163Rabbit** [comment]
![selection_004](https://user-images.githubusercontent.com/37582973/37697263-3e14475a-2cf5-11e8-86fc-6efb753419cf.png)
![selection_005](https://user-images.githubusercontent.com/37582973/37697266-422a0aa0-2cf5-11e8-8885-aade0d1348a8.png)

![type](https://user-images.githubusercontent.com/37582973/37697587-0c3d425c-2cf7-11e8-92d7-1032434ce02e.png)



the field (Ваш вопрос) on english =  (your questions) in this field i need to type something, cy.type('blabla', {force: true} doesnt work. I can do this only with "type" command or i can do this with something else?

**Comment by Bkucera** [comment]
Is there a textarea nested inside that div? If so, select that to type in
