### ISSUE TITLE
Whoops, there is no test to run.

### ISSUE THREAD

**Issue by Muhammadehsan2019** [cypress-io/cypress#14811]
![image](https://user-images.githubusercontent.com/57292707/106201613-b2e81c00-6186-11eb-9e81-441a1f778f9f.png)

I get  the "Whoops, there is no test to run" as soon as I click on the submit button on the page. The page closes but doesn't navigate to the previous window. I tried to to put it in separate tests but nothing worked.

**Comment by jennifer-shehane** [comment]
This can happen when the application under test is redirecting to the main window, outside of Cypress, like setting `window.top.location` or when clicking a link with `target="_parent"`

Please see these [open issues](https://github.com/cypress-io/cypress/labels/topic%3A%20%20%F0%9F%98%B3%20whoops%20there%20is%20no%20test%20to%20run) for workarounds depending on your situation.
