### ISSUE TITLE
Studio fails to save command when test or suite definition has test configuration

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#14814]
### Current behavior

If my test definition or suite uses test configuration, the commands captured in Cypress Studio will error when trying to save. I tried several different properties of test config - so it doesn't seem to matter which one you use.

If you have a suite with test config and try to 'add commands' to the inner `it` test - it will be successful.

**Test definition with test config**

<img width="807" alt="Screen Shot 2021-01-29 at 11 17 34 AM" src="https://user-images.githubusercontent.com/1271364/106233036-f775c500-6223-11eb-9ff2-011da1fa8991.png">

**Suite definition with test config**

<img width="792" alt="Screen Shot 2021-01-29 at 11 21 39 AM" src="https://user-images.githubusercontent.com/1271364/106233276-81be2900-6224-11eb-87bb-a3e709050e65.png">

#### Failing to add commands for test definition

`index.html`

```js
<button>button</button>
```

`spec.js`

```js
it('test 1', { responseTimeout: 60000 }, () => {
  cy.visit('index.html')
})
```

1. `cypress open` with the files above
2. Click 'Add Commands to Test'
3. Click button on AUT
4. Click 'Save Commands'

#### Failing to add a new test for suite definition

```js
describe('tests', { responseTimeout: 60000 }, () => {
  it('test 1', () => {
    cy.visit('index.html')
  })
} )
```

1. `cypress open` with the files above
2. Click 'Add New Test'
3. Enter url
4. Click 'Save Commands'

### Versions

Cypress 6.3.0

**Comment by bahmutov** [comment]
Released in v6.7.0
