### ISSUE TITLE
Add documentation search to the test runner

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1482]
## new feature

It would be nice (and powerful) to search our documentation right from the test runner. For example we could add a search field right into the first modal that now has mostly blank space (in addition to project's spec filenames).

**Comment by jennifer-shehane** [comment]
The code for our search is open source in our docs: https://github.com/cypress-io/cypress-documentation

**Comment by kristinacarlsen** [comment]
Did you still need help with this?

**Comment by dario-piotrowicz** [comment]
A new menu has been added for the docs: https://github.com/cypress-io/cypress/pull/16433

Is this issue still valid/required? do we want to put a searchbar somewhere in the new docs menu?

**Comment by jennifer-shehane** [comment]
We'll close this issue for the respective docs teams to decide on implementation moving forward.
