### ISSUE TITLE
Unable to connect to the remote-debugging-port via Chome Dev Protocol (CDP)

### ISSUE THREAD

**Issue by tomardern** [cypress-io/cypress#14835]
### Current behavior
I am trying to use Chrome Dev Protocol (CDP) to connect to the spawned Chrome Instance via `$(npm bin)/cypress open`. The overall aim, is to run the built in chrome V8 profiler to get the code coverage for all the files.

To find the port, I've added the following to `plugins/index`:

```
on("before:browser:launch", (browser, launchOptions) => {
    console.log(launchOptions.args);
});
```
Which returns the following:
```
...
  '--disable-web-security',
  '--allow-running-insecure-content',
  '--proxy-bypass-list=<-loopback>',
  '--remote-debugging-port=64739', <-- This changes each time
  '--remote-debugging-address=127.0.0.1',
  '--remote-debugging-pipe',
...

```
However, when I try and connect to the spawned CDP (either by opening `http://127.0.0.1:64739`) or even just running the Port Scan utility on Mac OSX Catalina, I'm unable to see CDP running, and unable to connect.

Interestingly, adding the following to my test script shows the console message, so I presume that Chrome Devtools Protocol is available, just not accessible outside of Cypress.

```
Cypress.automation("remote:debugger:protocol", {
  command: "Runtime.evaluate",
  params: {
    expression: "console.log('hello world 2');",
  },
});
```

### Desired behavior
Able to connnect to Cypress's spawned Chrome instance via CDP.

### Test code to reproduce
(Any basic cypress install, with the above changes in `plugins/index`

### Versions
Cypress: 6.3.0
Node: (12.18.3)
Chrome: Version 88.0.4324.96 (Official Build) (x86_64)
Mac: MacOSX Catalina 10.15.1

**Comment by tomardern** [comment]
Interestingly, adding the following to my test script shows the console message, so I presume that Chrome Devtools Protocol is available...

```
Cypress.automation("remote:debugger:protocol", {
  command: "Runtime.evaluate",
  params: {
    expression: "console.log('hello world 2');",
  },
});
```

**Comment by watanas** [comment]
This workflow used to work in cypress@6.2.1. Perhaps the use of the `--remote-debugging-pipe` Chrome flag has changed, maybe related to https://github.com/cypress-io/cypress/pull/14348?

**Comment by leveneg** [comment]
I too am seeing this behavior on latest. Unable to connect with both chrome and firefox.

**Comment by flotwig** [comment]
This is strange, connecting to CDP like this should work.

@tomardern Are you waiting for the browser to launch in your and retrying the connection? `before:browser:launch` runs BEFORE the browser is opened, so the CDP port is not immediately usable at this point.

Is anyone having this issue not on Mac?

**Comment by fstylermiller** [comment]
I am also seeing this issue. Running `cypress@8.4.0`
MacOS Big Sur 11.5.2

My chrome configuration:
```
name:"chrome"
family:"chromium"
channel:"stable"
displayName:"Chrome"
version:"93.0.4577.82"
path:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
minSupportedVersion:64
majorVersion:93
```
Running
`$ DEBUG=cypress:* ./node_modules/.bin/cypress open`

I can see that Cypress attempts to start the chrome debugger with the following flags:
```
cypress:launcher spawning browser with args { args: [ ... '--remote-debugging-port=60030', '--remote-debugging-address=127.0.0.1', ... ] }
```
Immediately following is:
```
cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:60030     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 60030 } }
```

Cypress then times out.
