### ISSUE TITLE
Redundant CLI output while using JSON reporter

### ISSUE THREAD

**Issue by stormherz** [cypress-io/cypress#1483]
- Operating System: MacOS 10.13.3
- Cypress Version: 2.1.0
- Browser Version: -

### Is this a Feature or Bug?

Bug

### Current behavior:

Running tests via CLI with a specified reporter leaves a lot of redundant output, like `(Tests starting)`, info from headless browser invocation, etc, which prevents futher parsing of the reporter's output.

For example, on my system, execution of 
`./node_modules/.bin/cypress run --project=tests/Cypress/ --reporter=json`

responds with the following output
```
  (Tests Starting)
2018-03-21 03:13:21.639 Cypress[30346:7241623] *** WARNING: Textured window <AtomNSWindow: 0x7fbcce61d270> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
<JSON output>
  (Tests Finished)

  - Tests:           11
  - Passes:          11
  - Failures:        0
  - Pending:         0
  - Duration:        16 seconds
  - Screenshots:     0
  - Video Recorded:  false
  - Cypress Version: 2.1.0


  (All Done)
```

Since I only need the JSON output to parse it and use it later - there's no reliable way of retrieving JSON data from that output. Sure I could use some parsing and trimming - but that eliminates the whole idea of custom reporters.

### Desired behavior:

Cypress should have an output bufferization of some sort in order to prevent reporter's output pollution with info/debug output.

### How to reproduce:

Run tests via CLI with a specified reporter

**Comment by jennifer-shehane** [comment]
It looks like most of the code for this output can be found in this file: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/modes/headless.coffee#L482

Perhaps this can be skipped if reporter is not `spec`. It's open source and we welcome WIP pull requests!

**Comment by brian-mann** [comment]
There is likely an option to save the JSON to disk instead of having it print to `stdout`. You can use multiple reporters too to do this.

**Comment by stormherz** [comment]
@jennifer-shehane @brian-mann so it's actually not considered as a bug, when I can't change verbosity level to omit informational messages? 

More than that - the issue here lies a bit deeper, requiring cypress CLI commands to have output bufferization, at least to separate cypress output from any messages, related to underlying headless browser engine.

It's not that I can't achieve what I'm looking for (there's always file output, just like Brian said) - it's more about common practices with reporters/printers. People use reporters to get output in a predictable format, which they can parse, pass along the pipeline or work with it.

**Comment by brian-mann** [comment]
I think there is a case for potentially silencing Cypress' output - but if its **just** to enable you to pipe `stdout` then I would say there's a better way to do that.

For instance, we could accept a new CLI argument for reporters that does that. We already have `--reporter` and `--reporter-options` maybe there could be `--reporter-stdout=/path/to/file` and then we'd redirect it there.

But as I mentioned before... I think if you just want this "to work" today... just use a JSON reporter that saves to disk and you'd be done.

https://github.com/mackstar/mocha-spec-json-reporter

**Comment by stormherz** [comment]
@brian-mann I see your point, if it's OK with cypress it's fine by me - there's always a way of solving an issue =) Closing this one, since not really a bug
