### ISSUE TITLE
Empty space in GUI

### ISSUE THREAD

**Issue by Regnander** [cypress-io/cypress#14830]
### Current behavior

Since the button for running all specs was moved down, there is now empty space beside the search bar that is left unused.

![Empty space in GUI 2](https://user-images.githubusercontent.com/17113053/106355803-979e1d80-62fa-11eb-891c-a24701bb02b7.png)

### Desired behavior

I expected the search bar to stretch across the whole GUI.

### Test code to reproduce

No code is needed.
### Versions

Cypress 6.3.0
Windows 10

**Comment by jennifer-shehane** [comment]
Feel free to open a PR to fix this. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by fetchpatrick** [comment]
Hello! I'd like to take this issue!

**Comment by Regnander** [comment]
> Hello! I'd like to take this issue!

Sure, go ahead.

**Comment by ColomboRiccardo** [comment]
If you don't mind I'd like to have a stab at it too, first time!

**Comment by fetchpatrick** [comment]
Hello, I'm having trouble with the node version matching. I have installed avn, but when I try to start the project it says 'avn could not activate node 12.18.3'. What am I missing? This is my first ever open source contribution...so I'm open to feedback for future contributions. 

Thanks!

**Comment by jennifer-shehane** [comment]
@fetchpatrick Make sure you have Node 12.18.3 installed on your system

**Comment by shashwat-15** [comment]
Hi guys, this is my first time looking out for issues. Sorry, if I'm asking a dumb question, but where exactly can I find the file/code related to this issue?

**Comment by jennifer-shehane** [comment]
PR opened here: https://github.com/cypress-io/cypress/pull/14932
