### ISSUE TITLE
Cookie management issues when cy.request is used exclusively (without cy.visit)

### ISSUE THREAD

**Issue by Qarj** [cypress-io/cypress#14838]
### Current behavior
The documentation for `cy.request` leads my team to believe we can create tests that exclusively use `cy.request`. This
seems ideal for testing our backend APIs.

There is no mention on the page https://docs.cypress.io/api/commands/request.html that `cy.visit` must be
called at least once for cookie management and test state cleanup to occur.

We have created a page on our website with very minimal html that we call with `cy.visit` at the start of
each of our tests to enable correct cookie management for `cy.request` so that the remainder of the test
can be conducted purely with `cy.request`.

### Desired behavior
Cookie management and test state cleanup work without a dummy call to `cy.visit`.

Note that on some websites it might be hard to find a url that loads very quickly and returns
`text/html` as required by `cy.visit` - this would lead to a substantially increased test run time across
many tests.

### Test code to reproduce
Run the spec `requestCookies.js` in this repo:
* https://github.com/Qarj/cypress-request-cookie-bug

```
npm run cypress:open
```

Double click on `requestCookies.js`.

In my testing this doesn't fail in a consistent manner, the first run may be different
to subsequent runs. In fact, even if you close the Cypress runner entirely and reopen
it can seem to remember the previous state as if there has been no clean-up.

<ins>*Get the test to pass*</ins>

In `requestCookies.js`, uncomment these two lines:
```
    // let healthcheckUrl = 'https://www.stepstone.de/membersarea/health?format=html';
    // cy.visit(healthcheckUrl); // MUST BE .visit do not change for .request
```

Now the tests passes every time.

Comment out the two lines again. The test continues to pass every time.

Now run `spec.js` then run `requestCookies.js` again. Now it will fail, for me
it failed in a different way though.

### Versions

* Cypress 6.3.0
* Electron 87
* Windows 10
* also known to fail on Mac

**Comment by moderatemisbehaviour** [comment]
I have this problem too, my use case is a headless login which is no longer headless because I have to visit a page first.

**Comment by Qarj** [comment]
I've updated the repo for Cypress 12.12.0 and confirmed the issue is indeed fixed now.
