### ISSUE TITLE
Wrong typing for Response.headers that is returned by cy.request

### ISSUE THREAD

**Issue by harunurhan** [cypress-io/cypress#14842]
### Current behavior

`Response.headers` type is `{ [key: string]: string }`

### Desired behavior

Since an header value can be an array, at least that's what I realized when I put a breakpoint and inspected the response:

`headers: { set-cookie: [ "cookie1=...." ], ...} `

Type should be probably changed to `{ [key:string]: string | string[] }`

### Versions

`cypress@5.6.0`

**Comment by patrickshaughnessy** [comment]
This^^ would be really great to have ASAP. Stubbing network response with a set-cookie array is impossible in the current implementation.

**Comment by bahmutov** [comment]
Can’t you give a temporary typescript exception by using ts-ignore?
