### ISSUE TITLE
cy.contains('xxx').should('not.exist') try to expect <body> not to exist in the DOM

### ISSUE THREAD

**Issue by aNyMoRe0505** [cypress-io/cypress#14861]
### Current behavior
I try to test input validation by cypress
When user enter page first time, user should not see the error message
So I write test like this
`cy.contains('forgot_password_error_email_empty').should('not.exist');`
but it seems that command try to expect body not to exist in the DOM so it fails in the end

<img width="327" alt="2" src="https://user-images.githubusercontent.com/9814815/106564709-91ad7400-6568-11eb-84e8-3593970aa168.png">

When I reproduced my problem, I found this bug is related to `next-i18n` and only occur in `next production build`
If I have translation key `test` (public/static/locales/en) `cy.contains('test').should('not.exist')` will check body exist or not

If I write cy.contains with selector `cy.contains('span', 'test').should('not.exist')`, the test will pass.
But I think this is not the good solution.

### Desired behavior
cy.contains should not check the body 

### Test code to reproduce
clone this project (https://github.com/aNyMoRe0505/next-cypress)
npm install => npm run build =>  npm run start
then npm run cypress:open to execute test
### Versions
"cypress": "^6.3.0"

**Comment by jennifer-shehane** [comment]
I can recreate this issue with the repo provided. 

<img width="823" alt="Screen Shot 2021-02-03 at 2 32 11 PM" src="https://user-images.githubusercontent.com/1271364/106716289-a6ebd680-662c-11eb-9816-7d186bc73117.png">

**Comment by egucciar** [comment]
I ran into this on my Next app, found that `cy.contains` matches the `body` when used in combination with Next's `getStaticProps` which prints out static prop data in a `<script>` tag to the dom for Rehydration. 

To fix, as a work around, i can no longer rely on `cy.contains` to retrieve elements based on text.

suggestion solution would be to exclude `script` tags from which `cy.contains` matches/works against.

**Comment by sainthkh** [comment]
By default, `cy.contains` returns `<body>` when the text you're finding is in `<script>` or `<style>` tag. The workaround is to use `match` command like below:

```js
cy.contains('xxx').should('match', 'body');
```

----

You might ask, "can't we just ban the `body` tag?" Unfortunately, the problem isn't that simple because `<body>` is sometimes the answer.

**Comment by Nikoms** [comment]
We have exactly the same issue. We are moving from react to nextjs et our cypress tests are broken because of this. We are using the workaround, but is there something else planned for this? :)

Thank youuu

**Comment by Nikoms** [comment]
@sainthkh do you know what "icebox" mean? :D

**Comment by jennifer-shehane** [comment]
@Nikoms It means this work is not prioritized for the Cypress team to work on.
