### ISSUE TITLE
Looking for for fixture files within subdirectories inside cypress/fixtures

### ISSUE THREAD

**Issue by mohsenny** [cypress-io/cypress#14866]
### What would you like?
Currently fixture files (`yml`, `json`, etc) and fixture images (using `cypress-file-upload` module to test upload functionalities) should be directly inside the `/fixtures` directory, and creating directories inside `/fixtures` and placing the files there, would trigger an error that:

```
A fixture file could not be found at any of the following paths:
```

Having the fixture files directly under `/fixtures` causes no issues:

<img width="274" alt="Screenshot 2021-02-02 at 11 24 37" src="https://user-images.githubusercontent.com/1129811/106587080-75e6a580-6549-11eb-9263-bd8e21da8686.png">

<img width="474" alt="Screenshot 2021-02-02 at 11 24 12" src="https://user-images.githubusercontent.com/1129811/106587091-797a2c80-6549-11eb-9b2b-50d83c9cdb2c.png">

However having the under a subdirectory ( like: `/fixtures/translations`) causes the issue:

<img width="271" alt="Screenshot 2021-02-02 at 11 23 50" src="https://user-images.githubusercontent.com/1129811/106587109-7ed77700-6549-11eb-8bc0-4cb459c41a81.png">

<img width="1440" alt="Screenshot 2021-02-02 at 11 23 27" src="https://user-images.githubusercontent.com/1129811/106587123-81d26780-6549-11eb-92f2-79d2f2ebb10d.png">

### Why is this needed?
This is needed for better organizing fixtures files. Currently we have many fixtures files, from various translations, database seeding files to image files (for testing upload functionalities using `cypress-file-upload` module). At this moment all the files are mixed together inside `/fixtures` directory but ideally we would prefer to have separate sub directories like:
- `fixtures`
- `fixtures/seed_files`
- `fixtures/images`
- `fixtures/translations`
- ...

### Development Setup
- `cypress": "^5.6.0`
- `cypress-file-upload": "^5.0.2"`
- `node` version: `15.3.0`

**Comment by mcha-dev** [comment]
<img width="152" alt="cyfix copy" src="https://user-images.githubusercontent.com/13101565/106635150-158c4e00-65b3-11eb-9b98-891bafc69279.png">

I organize fixtures in folders and it works fine (cypress 5.6 & 6.4), maybe check your file path/name

**Comment by mohsenny** [comment]
@mcha-dev you're absolutely right. Sorry for the noise 😓
