### ISSUE TITLE
sync skip; aborting execution error thrown when this.skip() inside function

### ISSUE THREAD

**Issue by przemek-rzedkowski** [cypress-io/cypress#14867]
### Current behavior

Scenarios skipped with use of "@focus" annotation generates a bug as seen on screenshot:
![image](https://user-images.githubusercontent.com/51486694/106609905-64f85d00-6566-11eb-8d41-0b0cc6fa2a00.png)

Focused scenario(s) run(s) correctly. It happened shortly after upgrading cypress to v.6.4.0 (I was using 6.3.0 before). Also I am using cypress-cucumber-preprocessor v.4.0.0. Problem disappears while running tests without annotation. 
It's my first bug here so if you need any additional info please let me know, I will gladly provide :)  
 
### Desired behavior

It should simply run focused scenario(s) and skip the rest of them without failing .

### Versions
Cypress v.6.4.0
cypress-cucumber-preprocessor v.4.0.0
<!-- Cypress version, last known working Cypress version (if applicable), Browser and version, Operating System, CI

**Comment by dthisner** [comment]
I have the same issue, example project can be located here that reproduces the issue: https://github.com/dthisner/cypressIssue 
Issue logged at the cucumber-preprocess repo: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/503

**Comment by jennifer-shehane** [comment]
As mentioned previously in the cucumber project, this can be reproduced solely in Cypress using the following code:

```js
it("should work", function () {
  cy.then(() => this.skip()); // throws "sync skip; aborting execution"
});
```

This is `sync skip; aborting execution` error is being thrown from Mocha here: https://mochajs.org/api/runnable.js.html 

```js
/**
 * Halt and mark as pending.
 *
 * @memberof Mocha.Runnable
 * @public
 */
Runnable.prototype.skip = function() {
  this.pending = true;
  throw new Pending('sync skip; aborting execution');
};
```

I guess we're not handling this correctly in this case. This seems to have always errored in this case.

**Comment by vishnuprabhu-95** [comment]
I am facing same issue!

**Comment by bennymeade** [comment]
Same issue for me, to avoid this issue I had to roll back to:
"cypress": "^6.3.0",
"cypress-cucumber-preprocessor": "^4.0.0",

**Comment by damsorian** [comment]
same problem :(

**Comment by damsorian** [comment]
> Same issue for me, to avoid this issue I had to roll back to:
> "cypress": "^6.3.0",

The problem seems to be in the **6.4.0** version, the _6.3.0_. works as expected

**Comment by przemek-rzedkowski** [comment]
problem seems to be solved in v. 6.5.0

**Comment by narayananpalani** [comment]
Used 6.5.0 this morning and I got the same error when running tags in my repo.

**Comment by ataul821** [comment]
I see the same issue in 6.5.0 as well.

**Comment by IIsijola** [comment]
I am having the same issue with version 7.0.1

**Comment by martinsik** [comment]
Same thing in 7.2.0 :(.

**Comment by canansaricelik** [comment]
same issue on 7.4.0

**Comment by neilmatillano** [comment]
I also get it in latest 7.5.0 version 
![Screenshot 2021-06-14 at 14 46 14](https://user-images.githubusercontent.com/4159492/121894354-56456200-cd1f-11eb-9c2a-9f9b4f826558.png)

**Comment by sKavanaghV** [comment]
> I also get it in latest 7.5.0 version
> ![Screenshot 2021-06-14 at 14 46 14](https://user-images.githubusercontent.com/4159492/121894354-56456200-cd1f-11eb-9c2a-9f9b4f826558.png)

This error will trigger Cypress to take screenshots and for the skip'd test. In the Cucumber scenario where many tests can be skipped based upon the specified tags, the number of screenshots could be significant; increasing test execution time and generating unnecessary screenshots.

**Comment by bahmutov** [comment]
Try using this plugin https://github.com/cypress-io/cypress-grep - I think it would make more sense to grep by title or tag rather than skip tests once the test has started.

**Comment by guthizon** [comment]
I'm same error yet! Do you some news?

**Comment by Ex4l** [comment]
Same here with "cypress": "^7.5.0" and "cypress-cucumber-preprocessor": "^4.1.3"

![image](https://user-images.githubusercontent.com/5011287/124943988-4151ab00-e00d-11eb-9f19-88897975fe33.png)

**Comment by stevenlafl** [comment]
I'm not sure what's going on here, but I want to have multiple features and target a tag to run, like you're supposed to be able to do. Unfortunately, the second a file doesn't have the tag I specify, it stops ALL execution including any subsequent files that DO have the tag in them. This breaks my use-case and the intent of this feature.

**Comment by todd-m-kemp** [comment]
Though it doesn't seem like a big deal on its own, this error is appearing as one of the top `Most Common Errors` for my organization in the Cypress Dashboard which isn't particularly helpful because it is not actionable on our end.

**Comment by araujosnathan** [comment]
I was having this problem with Cypress 8.6.0, i did a downgrade to v8.3.1 and it worked. All version above of 8.3.1 to latest, the problem for me is happening.

**Comment by sweeyeancheong** [comment]
Using Cypress 8.7.0 and cypress-cucumber-preprocessor 4.3.0. 
Solved the error as I missed out '@' on the values entered for TAGS field in my environment json file.
