### ISSUE TITLE
Include ajax requests inline with test expectations (the green text in the left panel)

### ISSUE THREAD

**Issue by mP1** [cypress-io/cypress#14865]
This might help narrow down or associate roughly ajax requests with failed expectations. 

My tests include logic to type/click stuff and that means ajax. Sometimes my ajax of course fails and after I jump back its hard to match failed tests with failed ajax simply because ajax logs are one big log.

Screenshot showing the panel where i suggest to "inline" ajax requests.

![image](https://user-images.githubusercontent.com/726970/106582960-adc90980-6598-11eb-8e44-08f0ee3c866f.png)

Would be nice to see the ajax call that happened between lines #18 and #19.

**Comment by jennifer-shehane** [comment]
@mP1 Have you looked into using `cy.intercept()` to intercept requests and `cy.wait()` to ensure the result is as expected? This is our recommended way to see and assert on requests.

**Comment by mP1** [comment]
@jennifer-shehane 

Yes but im guessing my idea would be rather useful as a general purpose debugging aide. I like the panel as it shows the sequence of requests, and asserts but theres no way to connect ajax calls into that timeline. My idea is to add them to the timeline.
