### ISSUE TITLE
Documentation and types do not reflect behaviour of `then` when returning element

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#14875]
### Current behavior
Given

```ts
const event = new Event('click');

cy.get('div')
  .then((el$) => {
    const el: HTMLDivElement = el$[0];
    return el;
  })
  .then((el) => el.dispatchEvent(event));
```

This _doesn't_ produce a TypeScript type error.

At runtime it throws an exception:

```
TypeError: el.dispatchEvent is not a function
```

This appears to happen because `el` is not actually a `HTMLDivElement`, despite what TypeScript thinks. It's actually a `JQuery` wrapped element.

### Desired behavior
- This should produce a type error at compile time (i.e. the types need to reflect the runtime behaviour).
- This "wrapping" behaviour should be documented [on the page for `then`](https://docs.cypress.io/api/commands/then.html).

### Test code to reproduce
See above

### Versions

Latest TS and Cypress

**Comment by jennifer-shehane** [comment]
Feel free to open a PR here and in the docs. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).
