### ISSUE TITLE
RangeError: Maximum call stack size exceeded at Buffer.slice 

### ISSUE THREAD

**Issue by pkell** [cypress-io/cypress#14891]
### Current behavior
Cypress is crashing during test runs. I am unable to provide a reproducible project but does the log at least indicate what might be causing the problem?
This is one of two test projects from different applications that are set up similarly and use the same version of cypress but only this project is encountering the issue.
Have tried with both electron and chrome but both crash.

> 2021-02-03T14:37:21.878Z cypress:server:file get values from C:\Users\paulkelly\AppData\Roaming\Cypress\cy\production\cache
> 2021-02-03T14:37:21.879Z cypress:server:file attempt to get lock on C:\Users\paulkelly\AppData\Roaming\Cypress\cy\production\cache
> 2021-02-03T14:37:22.063Z cypress:server:file getting lock succeeded or failed for C:\Users\paulkelly\AppData\Roaming\Cypress\cy\production\cache
> 2021-02-03T14:37:22.063Z cypress:server:file read C:\Users\paulkelly\AppData\Roaming\Cypress\cy\production\cache
> 2021-02-03T14:37:22.067Z cypress:server:file read succeeded or failed for C:\Users\paulkelly\AppData\Roaming\Cypress\cy\production\cache
> 2021-02-03T14:37:22.067Z cypress:server:file attempt to unlock C:\Users\paulkelly\AppData\Roaming\Cypress\cy\production\cache
> 2021-02-03T14:37:22.067Z cypress:server:file unlock succeeded or failed for C:\Users\paulkelly\AppData\Roaming\Cypress\cy\production\cache
> 2021-02-03T14:37:22.070Z cypress:server:api request to url: POST https://api.cypress.io/exceptions with params: {"body":{"err":{"name":"RangeError","message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at Buffer.slice (buffer.js:1105:40)\n    at cloneBuffer (<stripped-path>lodash.js:4528:23)\n    at baseClone (<stripped-path>lodash.js:2646:18)\n    
> 2021-02-03T14:37:22.080Z cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/exceptions' }
> 2021-02-03T14:37:22.080Z cypress:network:connect beginning getAddress { hostname: 'api.cypress.io', port: 443 }
> RangeError: Maximum call stack size exceeded
>     at Buffer.slice (buffer.js:1105:40)
>     at cloneBuffer (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\node_modules\lodash\lodash.js:4528:23)
>     at baseClone (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\node_modules\lodash\lodash.js:2646:18)
>     at C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\node_modules\lodash\lodash.js:2691:34
>     at arrayEach (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\node_modules\lodash\lodash.js:516:11)
>     at baseClone (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\node_modules\lodash\lodash.js:2685
> Repeats for thousands more lines.
>     at Function.cloneDeep (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\node_modules\lodash\lodash.js:11114:14)
>     at HttpBuffers.set (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\lib\http\util\buffers.js:27:32)
>     at Http.setBuffer (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\lib\http\index.js:220:29)
>     at NetworkProxy.setHttpBuffer (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\proxy\lib\network-proxy.js:15:19)
>     at C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\lib\server.js:597:38
>     at C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\network\lib\concat-stream.js:23:16
>     at ConcatStream.<anonymous> (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\network\node_modules\concat-stream\index.js:37:43)
>     at ConcatStream.emit (events.js:327:22)
>     at finishMaybe (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\network\node_modules\readable-stream\lib\_stream_writable.js:630:14)
>     at afterWrite (C:\Users\paulkelly\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\network\node_modules\readable-stream\lib\_stream_writable.js:492:3)
>     at processTicksAndRejections (internal/process/task_queues.js:86:21)
> 2021-02-03T14:37:22.100Z cypress:server:browsers killing browser process
> 2021-02-03T14:37:22.101Z cypress:server:browsers:electron debugger detached due to { reason: 'target closed' }
> 2021-02-03T14:37:26.182Z cypress:cli child event fired { event: 'exit', code: 3221226525, signal: null }
> 2021-02-03T14:37:26.183Z cypress:cli child event fired { event: 'close', code: 3221226525, signal: null }

### Test code to reproduce
Cannot reproduce outside of the test project tied to a proprietary product so I am unable to provide this.

### Versions

6.3.0, 6.4.0

**Comment by jennifer-shehane** [comment]
No, there's not much we can track down from the stack trace without a reproducible example.  We'll have to close this issue until we can reproduce it.

Please comment in this issue with a reproducible example and we will consider reopening the issue.
