### ISSUE TITLE
Whenever an err is thrown inside a .then(), commands stop executing after

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#149]
If you run the example code below, after the failure within the `cy.then()`, the `cy.wait()` in the "next text", the `cy.wait()` command never executes.

**Example Code**
```javascript
context("example", function(){
    it('first test', function(){
      cy
        .wait(10).then(function(){
            expect(false).to.be.true
        })
    })

    it('next test', function(){
        cy.wait(10)
    })
})
```

**Example of Command Log**
![screen shot 2016-05-19 at 2 52 44 pm](https://cloud.githubusercontent.com/assets/1271364/15405778/63bc2c78-1dd1-11e6-92d0-19ce56ab4b61.png)

**Comment by brian-mann** [comment]
Fixed in [`0.16.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0161-05222016).
