### ISSUE TITLE
Cypress runs all the specs in bitbucket when tried to run only failed step.

### ISSUE THREAD

**Issue by Ppkd2021** [cypress-io/cypress#14917]
A general observation is that when the cypress test cases fail in the bitbucket pipeline then if we run failed step then ideally it should execute only failed spec but it is executing all the spec which got passed in the run earlier. It is annoying as it increases the build deployment time.

**Comment by bahmutov** [comment]
Unfortunately, running just the failed tests or the failed tests first is not currently possible.
