### ISSUE TITLE
cy.submit command does not check the form's validity

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14911]
Cypress v6.4.0
Reproduction in https://github.com/cypress-io/cypress-test-tiny/tree/invalid-form-submit

Imagine a form with input element validation

```html
<body>
  <form id="form-validation" action="/action_page.php">
    <div>
      <label for="item">Item:</label>
      <input id="item" type="text" name="item" required />
    </div>

    <div>
      <label for="quantity">Quantity (between 1 and 5):</label>
      <input
        type="number"
        id="quantity"
        name="quantity"
        min="1"
        max="5"
        required
      />
    </div>

    <input type="submit" />
  </form>
</body>
```

The user should not be able to submit this form. If we try to use `cy.click` then we see the browser validation message, and the form is not submitted

```js
/// <reference types="cypress" />
describe('form', () => {
  it('should not be submittable', () => {
    cy.visit('index.html')

    cy.get('#form-validation').within(() => {
      // note we cannot submit by clicking the button
      // since some of the input elements on the page
      // fail the HTML validation
      cy.get('input[type=submit]').click()
    })
  })
})
```
<img width="699" alt="Screen Shot 2021-02-03 at 9 56 29 PM" src="https://user-images.githubusercontent.com/2212006/106838724-d0c3ee00-666a-11eb-83ff-b948f63b473c.png">

But if we use `cy.submit` it happily submits the form bypassing the validation

```js
/// <reference types="cypress" />
describe('form', () => {
  it('should not be submittable', () => {
    cy.visit('index.html')

    cy.get('#form-validation').within(() => {
      // note we cannot submit by clicking the button
      // since some of the input elements on the page
      // fail the HTML validation
      cy.get('input[type=submit]').click()

      // but the .submit() happily ignores the checks
      cy.root().submit()
    })
  })
})
```

<img width="773" alt="Screen Shot 2021-02-03 at 9 56 43 PM" src="https://user-images.githubusercontent.com/2212006/106838784-ed602600-666a-11eb-9311-eb724b83431a.png">

## Expected

- `cy.submit` should check the form's validity by calling `element.checkValidity()` first, it should be a built-in assertion

**Comment by bahmutov** [comment]
It could be considered a breaking change, a good candidate for v7

**Comment by chrisbreiding** [comment]
We decided to hold off on this work until we can prioritize it and discuss a wholistic solution for it.

**Comment by GrayedFox** [comment]
I actually really like being able to submit forms that fail client-side validation via `cy.submit(). The docs [aren't correct](https://docs.cypress.io/api/commands/submit#Submit-will-fail-if-there-are-form-validation-errors) in this case but I would ask that when you do introduce this change, could you also make it backwards compatible by either:

1. introduce the change as non-breaking, instead extending the functionality of `cy.submit()` to be configurable, and then update the docs, allowing for `cy.submit({ respectFormValidation: true })` (defaults to false), OR
2. introduce the change as a breaking one but still extend the functionality of `cy.submit()` to be configurable, allowing for `cy.submit({ respectFormValidation: false })` (defaults to true)

Something like this would allow (ab)users of the current bug to benefit from it.
