### ISSUE TITLE
Wait for alias.all not working in Cypress 6.4.0.

### ISSUE THREAD

**Issue by ErikGrigoriev** [cypress-io/cypress#14916]
### Current behavior
Cypress throws an Error when trying to wait for alias.all:

cy.wait() could not find a registered alias for: @**getDailyChangesTable.all**.
Available aliases are: getAutocompleteOption, getArticle, getFullView2Table, getCountries, getFullViewTable, getArticleList, **getDailyChangesTable**

![image](https://user-images.githubusercontent.com/38311981/106872386-888ce600-66d3-11eb-8770-931c3d20d253.png)

### Desired behavior
Cypress should wait for all request when .all is used.

### Test code to reproduce
1) create alias eg. @getRequest
2) wait for it in test using .all suffix. eg. @getRequest.all

### Versions
Cypress 6.4.0

**Comment by ErikGrigoriev** [comment]
Seems like this [https://github.com/cypress-io/cypress/issues/14444](fix) is root cause.

**Comment by jennifer-shehane** [comment]
I can reproduce this. I'm not sure if this was intentional or not. The `.all` syntax was never officially supported. 

### Reproducible example

```js
it('test cy.intercept()', () => {
  cy.intercept('/users').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  cy.wait('@getUrl')
})
```

### 6.3.0

<img width="575" alt="Screen Shot 2021-02-05 at 12 25 56 PM" src="https://user-images.githubusercontent.com/1271364/106995451-53ed5d00-67ad-11eb-946e-d0640fc0b3a8.png">


### 6.4.0

<img width="567" alt="Screen Shot 2021-02-05 at 12 23 26 PM" src="https://user-images.githubusercontent.com/1271364/106995310-feb14b80-67ac-11eb-969e-6bac293de359.png">

**Comment by flotwig** [comment]
@ErikGrigoriev what are you expecting to occur? 

`cy.wait('@alias.all')` does not really make sense - how can Cypress wait for "all" requests to an endpoint?

If you are looking to assert on a list of all intercepted requests, try `cy.get('@alias.all')`, where `.all` is supported officially.

**Comment by ErikGrigoriev** [comment]
@flotwig the issue is that in our application there are several request which We're using as identificator of finished loading process. Table is loaded, Article is saved, Article is updated etc. Alias in cypress is saved for the whole duration of test. SO in case I'm:
1) opening table
2) waiting for it to load
3) Using filter for a column
4) waiting for it to load
5) assert something
2nd wait would work as expected, whereas 4th would just be skipped because for cypress request has already happened, so there's no need to wait for it again. That's where .all was really useful, so that cypress would wait for all request that are matching given alias.

**Comment by flotwig** [comment]
> That's where .all was really useful, so that cypress would wait for all request that are matching given alias.

Have you tried updating your `cy.wait('@alias.all')` to just `cy.wait('@alias')`? They were functionally identical prior to 6.4.0.

FYI, another way to wait for a table to load is simply to use `cy.get` to try to locate the desired element, it will retry automatically.

**Comment by jennifer-shehane** [comment]
Yah, it does appear that the `cy.get('alias.all')` syntax works in 6.4.0 which is the original usecase of the `all`. As stated above, `cy.wait('alias.all')` does not make sense, even though it was working to wait on the specific request previous to 6.4.0.

**Comment by rifeng-ding** [comment]
@jennifer-shehane @flotwig Sorry to bother you under this closed issue. But I am upgrading Cypress from 5.x to 6.8, and we are indeed using `cy.wait('alias.all')` at several places in our code base. 

Since it doesn't works anymore, what is the current behaviour of `cy.wait('alias')`? The comment from @flotwig on Feb 5 seems indicating now cy.wait('alias')` functions the same as the old `cy.wait('alias.all')`? If not, does it mean that now we need to figure out our own way to "wait for all request under the same alias"?

**Comment by dzuncoi** [comment]
@flotwig @jennifer-shehane I have 1 crucial use case to use `cy.wait('@alias.all')` is when using lazy loading React component. Full flow:
- User navigate to 1 specific path which is being lazily loaded
- The request pattern is `**/*.chunk.js` (intercept alias as `@chunks`)
- Cypress need to wait all requests under `@chunks` to finish to make sure the component is rendered in the page
- Then assert some expect statement

If `wait('@alias.all')` is not supported, the test is super flaky as Cypress can't find the element if it doesn't finish lazily loaded. Are there any official way to handle that?

**Comment by jennifer-shehane** [comment]
@dzuncoi You should replace any uses of `cy.wait('@alias.all')` with `cy.get('@alias.all')`. 

You cannot wait for "all" aliases, this functionality does not exist in Cypress and never has. We don't know what "all" means in the context of your app. It could do 3 requests or 300 requests, we don't know what all are. You can however get all of the aliases that have been awaited so far at the time the `cy.get('@alias.all')` is called.

**Comment by annezhang524** [comment]
Can someone help me with this problem? Thank you

cy.intercept(
            'https://ldls-qa-az-eastasia-hyena.seismic-dev.com/api/livedoc/lifecycle/v1/tenants/qafeature1autotestnew/instances/31a84571-c01e-46a6-a6cb-b621d8aa7c79/stages/7184edad-4c29-427f-a13c-91db5419f360/universalplayer/manifest',
        ).as('getmanifestresult');
cy.get('@getmanifestresult', { timeout: '10000' });
![image](https://user-images.githubusercontent.com/61179688/151538589-80e6a311-bd2c-4262-8c7a-40bbfd7c2b37.png)

**Comment by bahmutov** [comment]
You should use “cy.wait” to wait for network intercepts. You use “cy.get” to get element aliases or any other values previously saved like spies

**Comment by hijazi** [comment]
> @flotwig @jennifer-shehane I have 1 crucial use case to use `cy.wait('@alias.all')` is when using lazy loading React component. Full flow:
> 
> * User navigate to 1 specific path which is being lazily loaded
> * The request pattern is `**/*.chunk.js` (intercept alias as `@chunks`)
> * Cypress need to wait all requests under `@chunks` to finish to make sure the component is rendered in the page
> * Then assert some expect statement
> 
> If `wait('@alias.all')` is not supported, the test is super flaky as Cypress can't find the element if it doesn't finish lazily loaded. Are there any official way to handle that?

I'm facing this same issue since I'm trying to test a next.js app and the JS is loaded as chunks and cypress just interacts with the html and submits a login form before the JS chunks finish arriving which makes the test super flaky.
@dzuncoi did you find a solution please?
