### ISSUE TITLE
Editing openlayer polygon feature with cypress not working

### ISSUE THREAD

**Issue by mustafahamid** [cypress-io/cypress#14918]
I am trying to draw an openlayer polygon and edit it. With cypress version 6 I can add a polygon but I am not able to edit it or move it. The working code below shows the case.

### Current behavior
cypress can draw polygon
### Desired behavior
cypress not able to edit or move polygon

### Test code to reproduce
```js
describe('test', () => {
      beforeEach(() => {
        // visit page of creating and editing polygon
        cy.visit('http://dev.openlayers.org/examples/drag-feature.html')
      })
    
      // Create a new polygon
      it('Test drawing / moving / ', function () {
        cy.get('#polygonToggle').click()
        cy.get('body')
                    .click(150, 100)
                    .click(250, 100)
                    .click(250, 250)
                    .click(150, 250)
                    .dblclick(150, 100)
        cy.get('#dragToggle').click()
        cy.wait(1000)
        cy.get('body').trigger('mousedown',200,150).wait(1000)
        cy.get('body').trigger('mousemove',100,150).wait(1000)
    
      })
    
    })
```
### Versions

Cypress version 6
chrome version 87

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
