### ISSUE TITLE
Report the CPU type and number in "cypress info" command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14926]
Currently, in Cypress v6 we report just the amount of memory on the machine, 

```
Cypress Version: 6.4.0
System Platform: darwin (19.5.0)
System Memory: 17.2 GB free 260 MB
```

It would be so nice to report the number of CPU cores and their type:

```
$ node -p 'os.cpus()'
[
  {
    model: 'Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz',
    speed: 2500,
    times: { user: 72341610, nice: 0, sys: 40531250, idle: 435841580, irq: 0 }
  },
```

https://nodejs.org/api/os.html#os_os_cpus

**Comment by jennifer-shehane** [comment]
Since this feature hasn’t had a lot of interest over the years, we’ll close this issue.
