### ISSUE TITLE
req.reply function fixture support

### ISSUE THREAD

**Issue by clazette** [cypress-io/cypress#14927]
I am attempting to intercept and modify the response without hitting the destination server. I have a couple issues.

1. The routeMatcher object doesn't support interrogating the request body. In order to get around that limitation, I am using the `req.reply` method after performing some logic in the `routeHandler` to determine which response to send. This approach seems to work. 
2. However, the `req.reply` function takes a `string | object` and I can't seem to figure out how to use a fixture so that I can dynamically return a response for easily.

```js
cy.fixture('mocks/forms/post_search_open').as('searchOpen')

cy.intercept('POST', `**/${formsApi.searchRoute}*`, (req) => {
      if (req.body.find(b => b.Type === 'Status').Value.Items.includes('open')) {
        req.reply(200, '@searchOpen')
      } else if (req.body.find(b => b.Type === 'Status').Value.Items.includes('Pending')) {
        req.reply(200, [...
```

What am I doing wrong? Is there a better way?

Thanks!

**Comment by jennifer-shehane** [comment]
Yah, I think we could have better examples of this in the docs. You're using the `req.reply` which will intercept the response *after* it has hit the destination server. You mentioned not wanting to hit the destination server, so I'm not sure this is what you want. 

If this is what you want, there's an example below that you should be able to run and play around with.

I'm not sure about changing the `statusCode` in the `req.reply` function, so I'm checking with the team on that.

```js
it('test cy.intercept()', function () {
  cy.fixture('example.json').as('example')
  cy.fixture('movies.json').as('movies')
  cy.intercept('POST', '/users', (req) => {
    if (req.body === 'posting') {
      req.reply(this.example)
    } else {
      req.reply(this.movies)
    }
  }).as('postUrl')

  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/users')
    xhr.send('posting')
  })

  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('POST', '/users')
    xhr.send('foo')
  })

  cy.wait('@postUrl').then(({ request, response }) => {
    // this is data from our examples.json fixture
    expect(response.body.totalResults).to.eq(14)
  })

  cy.wait('@postUrl').then(({ request, response }) => {
    // this is data from our movies.json fixture
    expect(response.body[0].title).to.eq('Black Panther')
  })
})
```

**Comment by clazette** [comment]
Thank you! I will give this a try. I don't need to change the status code. I was just supplying the necessary parameters to the reply call.

Per the intercept documentation ([](https://docs.cypress.io/api/commands/intercept.html#Comparison-to-cy-route)): "If cy.intercept() provides a response object, or a fixture, or calls req.reply() then the request will NOT go to the server, and instead will be mocked from the test."

That's where I got the idea that my approach wouldn't hit the destination server.

**Comment by clazette** [comment]
Overall, your approach works well. A couple issues I am working through.
1. this is undefined
2. req.reply('@fixureAlias') results in the response.body being the literal text "@fixtureAlias". If I don't use fixtures and place the JSON as the body parameter to the reply function it works. That's just not practical though.

I was able to chain the cy.fixture promises but it's a bit more verbose than using the alias. Is there a way around this?

`cy.fixture(fixtures.statusSummaryQ42020).then((q4) => {
      cy.fixture(fixtures.statusSummaryQ12021).then((q1) => {
        cy.intercept('POST', `**/${formsApi.routes.statusSummary}`, (request) => {
          if (request.body.find((b) => b.Type === 'TaxYear').Value === 2020) {
            request.reply(q4)
          } else if (request.body.find((b) => b.Type === 'TaxYear').Value === 2021) {
            request.reply(q1)
          }
        }).as('statusSummary')
      })
    })`

**Comment by clazette** [comment]
Ahhh, I need to use standard function syntax in order to use this. I will try that.

**Comment by clazette** [comment]
The standard function syntax eliminated the undefined this. So, I can eliminate the fixture chaining with your fixture alias approach. Thank you very much. This really helped!

**Comment by jennifer-shehane** [comment]
That's great to hear! Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
