### ISSUE TITLE
The "origin" header does not appear in the "request" API in cypress execution

### ISSUE THREAD

**Issue by diegosierra12** [cypress-io/cypress#14924]
**Current behavior:**

1. Enter the url: https://reqbin.com/req/zvtstmpb/post-request-example.
2. Chrome browser developer tools are enabled. 
3. Select the network tab.
4. Finally click on the "Send" button.

![image](https://user-images.githubusercontent.com/41496286/106930409-82066a80-66e3-11eb-9802-f72092654797.png)

It's evident that in the API "request" contains the "origin" header.

**Desired behavior:**

Test run in Cypress simulating the same steps

![image](https://user-images.githubusercontent.com/41496286/106931249-5df75900-66e4-11eb-8cae-fe95456a4062.png)

It's evident that the "origin" header does not appear in the "request" API

**Test code to reproduce:**

cy.visit('https://reqbin.com/req/zvtstmpb/post-request-example');
cy.get('#submit').click();

**Versions:**

Cypress:  6.4.0.
Chrome: Version 88.0.4324.96

**Comment by diegosierra12** [comment]
Have you been able to verify this error?

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I checked that the `origin` header is sent when you check the network tab.

![Screenshot from 2021-05-04 11-28-47](https://user-images.githubusercontent.com/8130013/116954921-2771b000-accc-11eb-9f05-93d718c852a3.png)

But it doesn't show on the console window, because only header items changed by [`setRequestHeader`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader) are cached and shown. The options shown above are manually set up by the page. (Please click the tab, `Headers` and `Raw` on the [page](https://reqbin.com/req/zvtstmpb/post-request-example))

**Comment by diegosierra12** [comment]
@sainthkh I did the test as you indicate and indeed for that case it brings the header "origin".

For the following test on all services that are in red with 404 status, it is evident that it does not show the "origin" header when run with cypress.

![image](https://user-images.githubusercontent.com/41496286/116956947-25700880-ac5c-11eb-8062-943f52490029.png)

When done manually if it shows the "origin" header.

![image](https://user-images.githubusercontent.com/41496286/116956998-49cbe500-ac5c-11eb-8481-a3d06d7c03e3.png)

I did the test with the site that I indicated previously because I cannot provide the code to get to this point in the evidences of this comment.

In the same way you can see issue #15355 where the same is reported.

**Comment by sainthkh** [comment]
Now we need to narrow down and create a minimal example that reproduces the issue.

**Comment by Sjoerdsjoerd** [comment]
@diegosierra12 Is it possible that you disabled WebSecurity by using: `"chromeWebSecurity": false`?

Because I think that when you disable WebSecurity, the Origin header is not sent in the request to the backend.

**Comment by vandrieiev-godaddy** [comment]
> @diegosierra12 Is it possible that you disabled WebSecurity by using: `"chromeWebSecurity": false`?
> 
> Because I think that when you disable WebSecurity, the Origin header is not sent in the request to the backend.

have no clue why cypress remove all Origin headers when chromeWebSecurity is set to false. for me it cause many problems

**Comment by Hangochung81** [comment]
I have the same issue. Seem it happen when application uses SSE. Some more info to fix it? Thank a lot

**Comment by MehdiSv** [comment]
Same issue here. Any reason why Cypress removes the Origin header if chromeWebSecurity is set to false?
Is there a way to keep the Origin header without touching the chromeWebSecurity option?

**Comment by AshotAleqs** [comment]
Hello Everyone.

Yesterday I tried to use the `cy.intercept()` to handle all of the API calls that we are doing by `cy.request()` and set the authorization header in all of the requests if it is not the login API call. After spending some hours with no progress, I focused to find a workaround and I found one. I overwrote the `cy.request` command and it helps to resolve the issue connected with the authorization header. And after adding the proper headers, I faced the issue connected with the origin, but as I have rewritten the whole function I am now able to set any origin that I want. 

This is not the **solution** this is a workaround and I Hope this workaround can help you to solve your problem and save your time.

Setting only Origin 
```ts
Cypress.Commands.overwrite('request', (originalFn, ...rest: any) => {

  let request: Partial<Cypress.RequestOptions> = {
    method: RequestMethods.GET,
  };

  // the the cy.reqyest called by object argument {method: 'get',  url: 'https://any-url.com/route' }
  if (typeof rest[0] === 'object') {
    request = { ...rest[0] };
  } else {

    const first: string = rest[0];
    // when the first argoumet us the url
    if (first.startsWith('/') || first.startsWith('http')) {
      request.url = first;

      if (rest[1]) { request.body = rest[1]; }

    } else {
     // when the first argument is the method
      request.method = first;
      request.url = rest[1];
      if (rest[2]) { request.body = rest[2]; }
    }
  }

  let headers = {  ...(request.headers || {}) }

 // set the origin that you want 
  headers['origin']= 'origin';   // <---------- change 'origin' to the actual origin 

  request.headers = headers;
   
  return originalFn(request);
});
```


Complexe example with setting headers, base URL etc.
```ts
Cypress.Commands.overwrite('request', (originalFn, ...rest: any) => {

  let request: Partial<Cypress.RequestOptions> = {
    method: RequestMethods.GET,
  };

  // the the cy.reqyest called by object argument {method: 'get',  url: 'https://any-url.com/route' }
  if (typeof rest[0] === 'object') {
    request = { ...rest[0] };
  } else {


    const first: string = rest[0];
    // when the first argoumet us the url
    if (first.startsWith('/') || first.startsWith('http')) {
      request.url = first;

      if (rest[1]) { request.body = rest[1]; }

    } else {
     // when the first argument is the method
      request.method = first;
      request.url = rest[1];
      if (rest[2]) { request.body = rest[2]; }
    }
  }

  const authorization = Cypress.env('AUTHORIZATION');
  const session = Cypress.env('SESSION_AUTHORIZATION');

  let headers = {
    ...(request.headers || {}),
  }
 // <---------- this piece can. be removed
  if (!headers['content-type']) {                            
    headers['content-type'] = 'application/json';
  }

  if (!headers['authorization'] && authorization) {
    headers['authorization'] = authorization;
  }
 // <---------- this piece can. be removed until here

 // set the origin that you want 
  headers['origin']= 'origin';   // <---------- change 'origin' to the actual origin 

  request.headers = headers;

   // <---------- this piece is also optional and can be removed
  const baseURL = Cypress.env('BASE_URL');
  if (!request.url.startsWith('http')) {
    request.url = `${baseURL}${request.url}`;
  }
   // <---------- this piece is also optional and can be removed until here
   
  return originalFn(request);
});
```

**Comment by andreynav** [comment]
The bug is still reproduce

**Preconditions**:
1. To be at url: https://example.cypress.io/commands/network-requests 
2. To have a test
```
describe("Network Requests", () => {
    beforeEach(() => {
        cy.visit("https://example.cypress.io/commands/network-requests");
    })

    it("Post Request with intercept", () => {
        cy.intercept("POST", "/comments").as("postComment")
        cy.get('.network-post') .click()
        cy.wait("@postComment").should(({request}) => {
            console.log(request)
            expect(request.headers).to.have.property('origin', 'https://example.cypress.io')
        })
    })
})
```

**STR**:
1. Run the test

**AR**: assertion `expect(request.headers).to.have.property('origin', 'https://example.cypress.io')` fails - https://monosnap.com/file/nNZ2P5XpmGVIhrY2lnkMsW2eYV5RQa (cy test console.log(requests))
**ER**: assertion passed - https://monosnap.com/file/r4qyr0kB0k7xHcF7jiHsNYHiCpAzNV (site network tab)

**Comment by mike-plummer** [comment]
Hello everyone! This issue was actually re-reported under #23712 which includes some useful info.

>  --disable-web-security essentially disables the same-origin-policy, allowing sites to make cross origin requests without the security implications that CORS enforces. Since it is no longer enforced, the requests aren't considered cross-origin and won't include the Origin header.

From the investigation done under that ticket it appears the header simply isn't provided by the browser when running in that mode, so there's nothing for Cypress to copy over on the request. It's not clear whether this behavior was reported as a Chromium bug (I didn't see a link on that ticket) but there may be more context available from the Chromium team. In any event, it appears that this isn't a bug with Cypress itself but a browser behavior (maybe a bug, maybe intentional).

**Comment by adnanerlansyah403** [comment]
> Hello everyone! This issue was actually re-reported under #23712 which includes some useful info.
> 
> > --disable-web-security essentially disables the same-origin-policy, allowing sites to make cross origin requests without the security implications that CORS enforces. Since it is no longer enforced, the requests aren't considered cross-origin and won't include the Origin header.
> 
> From the investigation done under that ticket it appears the header simply isn't provided by the browser when running in that mode, so there's nothing for Cypress to copy over on the request. It's not clear whether this behavior was reported as a Chromium bug (I didn't see a link on that ticket) but there may be more context available from the Chromium team. In any event, it appears that this isn't a bug with Cypress itself but a browser behavior (maybe a bug, maybe intentional).

IF it's a bug from browser behaviour then why when I tried it with manually its running well on the browser ?

**Comment by faridescate** [comment]
I ended solving it this way.

```js
  cy.intercept('GET', 'https://back.**something.com/**', (req) => {
    req.headers['origin'] = 'https://www.something.com';
  });
```

**Comment by martincarstens** [comment]
> I ended solving it this way.
> 
> ```js
>   cy.intercept('GET', 'https://back.**something.com/**', (req) => {
>     req.headers['origin'] = 'https://www.something.com';
>   });
> ```

Thank you for this!
