### ISSUE TITLE
Timed out retrying: cy.type() failed because this element: *input* is being covered by another element: *label*

### ISSUE THREAD

**Issue by nemanjamilosavljevic-newtron** [cypress-io/cypress#14921]
### Current behavior
The test goal is navigating to a login page and entering a user name and password and submitting it.

This, however, has inconsistent behavior, when tested. 

When I try to fill in one text field (username) and run the test initially, it fails/passes randomly.
When I try to fill in both username and password and run the test initially, the username gets filled in but the password fails.

These both always fail when the test is being re-run, either due to the --watch mode or manually by clicking the "Run all tests" button.

When trying to populate an input 
```js
it('should successfully go to the login page', function () {
    cy.visit('/some/page');

    cy.findByRole('button', { name: 'Login' }).click();

    cy.get('input[name=j_username]').type('something');
    // Or
    cy.findByLabelText('User ID*').click().type('trg-s-ta-en');
    // Or
    cy.findByLabelText('User ID*').click({ force: true }).type('trg-s-ta-en');
    / OR
    cy.findByLabelText('User ID*').type('trg-s-ta-en');
    
```
this happens:

![image](https://user-images.githubusercontent.com/77624664/106901126-a4a27e80-66f7-11eb-8a99-b4d8510132b4.png)

### Desired behavior

The input should be filled with the provided text.

### Versions
Cypress: 5.5
OS: Windows 10
Chrome: Version 88.0.4324.146 (Official Build) (64-bit)
Framework: NX 11.0.4

**Comment by jennifer-shehane** [comment]
@nemanjamilosavljevic-newtron Did you inspect the DOM where this failure is happening? It looks like there is a label element covering the input with a `noselect` class. Perhaps the login has some implementation to cover up the input at some point during testing. 

We won't be able to help without a way to see the DOM / a reproducible example to tell whether this is a bug or just some behavior of the app you need to work around in your test cases.

Also, I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by nemanjamilosavljevic-newtron** [comment]
Hi @jennifer-shehane, 
thanks for the quick response. You are 100% right with your assumption.

![image](https://user-images.githubusercontent.com/77624664/107010131-382a8c80-6796-11eb-8ac3-9ea958df9cf6.png)

Is there anything that can be done in case I don't have access to the form with `noselect` class?

**Comment by jennifer-shehane** [comment]
Yeah, this is why testing an app you didn't write can be difficult. It's hard to tell what their logic is behind the scenes to write a test to get around. Have you tried passing `force: true` to the `.type()` command? It may be a good workaround in this situation.

**Comment by nemanjamilosavljevic-newtron** [comment]
I actually have not tried that with the `type` method, and it worked.
Thanks, @jennifer-shehane!

**Comment by jkajalin** [comment]
Having very similar problem with @mui/material: ^7.1.0 and cypress: ^14.4.0. 
Even forcing type won't work.
cy.get('#elementid').type( testDate, {force: true} )

Cypress test fails and says label element is covering input element. While in real app I could interact with element without any problem. Even copy pasting date  03/2025 to input, works.

Edit:
Found work around.
cy.get('#elementid').parent().parent().type( testDate )
