### ISSUE TITLE
"@types/cypress": "^1.1.3" have a dependencies "cypress": "*"

### ISSUE THREAD

**Issue by luckhpy** [cypress-io/cypress#14931]
"@types/cypress": "^1.1.3" dependent  "cypress": "*", which mean even though i install cypress global in docker, it will still install cypress in the `yarn` stag，it takes a long time， hope some help

package.json
```
{
    "name": "@types/cypress",
    "version": "1.1.3",
    "typings": null,
    "description": "Stub TypeScript definitions entry for cypress, which provides its own types definitions",
    "main": "",
    "scripts": {},
    "author": "",
    "repository": "https://cypress.io",
    "license": "MIT",
    "dependencies": {
        "cypress": "*"
    }
}
```

**Comment by jennifer-shehane** [comment]
Cypress provides its own type definitions, so you should need to use `@types/cypress` - https://www.npmjs.com/package/@types/cypress. Can you explain why you need this dependency?

**Comment by luckhpy** [comment]
@jennifer-shehane i installed cypress global in docker， typescript does not seem to find the global definition

**Comment by GeekaholicLin** [comment]
We encountered the same problem in our project. The node version limit of our project is <12, and only the global cypress can be installed. If `@type/cypress` cannot be used, is there a way to reference the global cypress type?
