### ISSUE TITLE
browser with test GUI should save size

### ISSUE THREAD

**Issue by balexandre** [cypress-io/cypress#1493]
### Current behavior:

using the tests GUI, every time I click `Run All Tests` button (or each file individually) the tests GUI window **always** open maximized.

my `state.json` on **Windows** (screen res: 3440x1440) is

```json
{
  "showedOnBoardingModal": true,
  "appWidth": 800,
  "appHeight": 545,
  "appX": 2602,
  "appY": 709
}
```

on **Ubuntu** is as 

```json
{
  "showedOnBoardingModal": true,
  "appWidth": 800,
  "appHeight": 1113,
  "appX": 565,
  "appY": 54,
  "reporterWidth": 259
}
```

### Desired behavior:

It should save the browser dimensions so it could use it to open the next time

### How to reproduce:

on **Windows**

I've simply added `cypress` to my project through npm and run it locally

```bash
npm i --save-dev cypress
./node_modules/.bin/cypress open
```

and then click "run all tests" button

#### Test code:

```js
const clientUrl = 'https://www.billigvvs.dk/';

describe('BilligVVS - Signup', () => {
    beforeEach(() => {
        cy.viewport('macbook-15');
        cy.visit(`${clientUrl}#sc-test`);
    });

    it('campaign loads after 60sec', () => {
        cy.getCookies();
        cy.wait(20 * 1000);
        cy.get('sign-up').should('have.value', 'abc'); // error-here
        expect(true).to.equal(true);
    });
});

```

### Additional Info (images, stack traces, etc)

[![](https://s6.postimg.org/5zxmkj5xd/screenshot_176.png)](https://s6.postimg.org/5zxmkj5xd/screenshot_176.png)

- Operating System: **Windows** 10 & **Ubuntu** 14.04
- Cypress Version: 2.1.0 beta
- Browser Version: Chrome 65

**Comment by daniel4andre** [comment]
On ubuntu my screen resolution is 1920x1200

**Comment by jennifer-shehane** [comment]
Could you explain why this is an issue for you? I'd like to understand better what you're trying to accomplish. 

The viewport of the application under test is [configurable in the configuration](https://docs.cypress.io/guides/references/configuration.html#Animations). It will render at that size always if set in your `cypress.json`

**Comment by balexandre** [comment]
@jennifer-shehane 

the issue is that every time I run tests from the "test tree-file small window" the test just opens as maximized, and having a 34'' screen makes no sense to occupy the hole screen...

from Gitter, I've found out that the `state.json` were missing `browserWidth` and `browserHeight` so it opens the window with those restrictions.

this is nothing to do with the test viewport.

**Comment by jennifer-shehane** [comment]
Yes, sorry I just saw the thread in gitter where @chrisbreiding was suspecting it may be a Windows issue: https://gitter.im/cypress-io/cypress?at=5ab5100635dd17022e9163ec

**Comment by Saibamen** [comment]
Still failing - Windows 10, Cypress 3.1.5

**Comment by jareks** [comment]
Is there any progress / quickfix for this issue? Having browser maximized on every test start messes with my others carefully positioned windows and I have to resize it every single time.

**Comment by WayneHiller** [comment]
Any news on this? Drives me crazy on my wide screen monitor.

**Comment by mtc3bmtc3b** [comment]
As a workaround, you can send a window size to Chrome via plugins/index.js:

`
module.exports = on => {
    on('before:browser:launch', (browser = {}, args) => {
        if (browser.name === 'chrome' || browser.name === 'chromium' || browser.name === 'canary') {
            args.push('--window-size=1000,1200');
            return args;
        }
    });
};
`

**Comment by Spiralis** [comment]
Thank you so much for your workaround, @mtc3bmtc3b. 
This was really driving me nuts... :)

**Comment by mattcarlotta** [comment]
The @mtc3bmtc3b solution works great, but unfortunately throws a [deprecation warning](https://docs.cypress.io/guides/references/migration-guide.html#Plugin-Event-before-browser-launch) because the API has changed. Here's an updated solution:

```js
module.exports = on => {
  on("before:browser:launch", (browser, launchOptions) => {
    if (browser.name === "chrome" || browser.name === "firefox") {
      launchOptions.args.push("--window-size=1800,1100");
      return launchOptions;
    }
  });
};
```

**Comment by kamranayub** [comment]
In my case I am trying to do screen recording (on an ultrawide) so I have all my windows just so and this definitely throws it all off (have to pause, resize, reposition). 👍

**Comment by hackel** [comment]
Is there any hope of progress on this?  It really makes using Cypress a pain.  (People who maximize their browsers are *evil!*)  The workaround given isn't appropriate in a shared codebase where users have different size displays and might not want their Cypress window the same dimensions as mine.

**Comment by GregLahaye** [comment]
If anyone wants to resize the window when using Electron, this worked for me (similar to Chrome workaround):

(in plugins/index.js)

```
module.exports = (on, config) => {
    on("before:browser:launch", (browser, launchOptions) => {
        if (browser.name === "electron") {
            launchOptions.preferences.width = 1920;
            launchOptions.preferences.height = 1080;

            return launchOptions;
        }
    });
}
```

**Comment by jarrodldavis** [comment]
The reason for this is Cypress injects the `--start-maximized` flag when opening Chrome:

https://github.com/cypress-io/cypress/blob/a4e96425d76acd76cf16ed2fdb0638f8d8611b3b/packages/server/lib/browsers/chrome.ts#L47-L52

The comment seems to imply that [this document](https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md) recommends use of the flag for browser automation, but I found no mention of the flag in it at all. Since there's no (good) reason for Cypress to do this (especially on ultra-wide screens!), this flag can be removed in the `before:browser:launch` event:

```js
on('before:browser:launch', (_browser, launchOptions) => {
    launchOptions.args = launchOptions.args.filter((arg) => arg !== '--start-maximized');
    return launchOptions;
});
```

This allows Chrome to use its normal window positioning behavior, which remembers the window size and position across launches (as expected).

**Comment by mjustin** [comment]
I also wouldn't mind if a consistent sensible default windowed size were chosen, as opposed to the last Chrome window size.  That actually feels a bit nicer to me.

In any event the full screen window is the main issue here for me, and either of these approaches solves it.
