### ISSUE TITLE
Chrome with Headless is not working in cypress while running with the --headless command

### ISSUE THREAD

**Issue by vinay150687** [cypress-io/cypress#14939]
I have requirement to run the scripts in headless browser either in Chrome or Electron

### Current behavior
When We run Scripts in headless browser with below mentioned command, it prompting which browser and version picking for execution but when feature file selects it got strucked over there without any progress on script execution.
```
 node_modules\\.bin\\cypress run --headless --spec "cypress/integration/regression/Cucumber/*.feature" --browser chrome
```
Note :Cross origin issue sorted out with chromeWebSecurity:False and working with headed chrome fine but in headless chrome not working
```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    6.4.0                                                                              │
  │ Browser:    Chrome 88 (headless)                                                               │
  │ Specs:      7 found (regression\Cucumber\adminfunctionalities.feature, regression\Cucumber\│
  │            ***.feature, regression\Cucumber\***.feature, re │
  │             gression\Cucumber\*****.feature, regression\Cucumber\****│
  │             **...)                                                                     │
  │ Searched:   cypress\integration\regression\Cucumber\*.feature                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
Running:  regression\Cucumber\adminfunctionalities.feature                                (1 of 7)


  ADMIN FUNCTIONALITY
```
### Desired behavior
It should execute ADMIN FUNCTIONALITY test and display the status whether failed or passed after execution

### Versions
Cypress:6.4.0,5.6.0(both tried)
Cucumber pre processor :1.8
Chrome:88 @cypressgreg

**Comment by vinay150687** [comment]
@cypress-io

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? We'll have to close the issue without a way to reproduce it.

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
