### ISSUE TITLE
Using Cypress with create-react-app (jest)

### ISSUE THREAD

**Issue by nWidart** [cypress-io/cypress#1494]
- Operating System: MacOS
- Cypress Version: `2.1.0`
- Browser Version: Chrome 65

I think this might be a bug.

### Current behavior:

On compilation, crashes with:

```
error TS2403: Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'Describe', but here has type 'IContextDefinition'
```

![image](https://user-images.githubusercontent.com/882397/37841412-ff6966da-2ebf-11e8-899b-55d0e9c7edcb.png)

### Desired behavior:

Ability to compile and run the application.

### How to reproduce:

Creating a new project with create-react-app typescript version, and installing cypress. 

*** 

I assume this is due to create-react-app using Jest, which comes with its own `describe`, `test`, `it` etc. and cypress shipping with Mocha.

Is there a way to make them work together?

Thank you!

**Comment by bahmutov** [comment]
hmm, I have to try it, but see if anything here https://github.com/cypress-io/cypress/issues/1319 or https://docs.cypress.io/guides/tooling/typescript-support.html# applies

**Comment by nWidart** [comment]
Hello and thank you for the reply.

The issue you linked provided some guidance.
I was able to make it work by specifying every `@types` package I use in the `tsconfig.json` file, except the `cypress` types.
Before I didn't provide any `types` option in `tsconfig.json`.

I'm not sure if this is the 'correct' way to do it, but it seemed to fix the compilation and cypress. 

Thanks! 👍

**Comment by avkonst** [comment]
I do not eject webpack config created by create-react-app. How could I use react-scripts from create react app to run cypress e2e and unit tests (https://github.com/bahmutov/cypress-react-unit-test) written in typescript?
