### ISSUE TITLE
Support disabling secure flag for SameSite=none cookies in Chrome

### ISSUE THREAD

**Issue by jippeholwerda** [cypress-io/cypress#14946]
When we use the latest cypress/browser Docker image (node14.15.0-chrome86-ff82) our Cypress tests are all failing. This is because as of Chrome 85, cookies set with `SameSite=None` should have the `secure` flag. This behavior causes our Cypress tests to fail since we're not using https for CI tests.

For more info, see: https://www.chromium.org/updates/same-site/test-debug

A possible workaround would be to start chrome with the following flag: `--disable-features=CookiesWithoutSameSiteMustBeSecure`

You can test whether the cookie is set using the following test site: https://samesite-sandbox.glitch.me/. Try it with and without the flag.

Is it possible to add this flag when using chrome to run Cypress tests?

If this is the way to go, I'm happy to come up with a merge request.

**Comment by jennifer-shehane** [comment]
You can modify browser flags by using our `before:browser:launch` event https://on.cypress.io/browser-launch-api#Modify-browser-launch-arguments. Try passing:

```js
// cypress/plugins/index.js
module.exports = (on, config) => {
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name === 'chrome' && browser.isHeadless) {
      launchOptions.args.push('--disable-features=CookiesWithoutSameSiteMustBeSecur')
    }

    return launchOptions
  })
}
```
