### ISSUE TITLE
On cy.visit() our website loads for a quick few milliseconds and then goes blank. 

### ISSUE THREAD

**Issue by dmvasquez** [cypress-io/cypress#14954]
Everything opens up great and after the tests begins to run and gets to the first visit() the page goes white: 

Here's the site: 
```
cy.visit("https://c2pms-stage.azurewebsites.net/Account/SignIn");
cy.login(Cypress.env("roleDevManName"), Cypress.env("roleDevManPass"));
```
Cypress used to work but for some reason now it does not.

**Comment by jennifer-shehane** [comment]
It looks like a bunch of requests for resources are cancelled when run within Cypress. 

### Reproducible Example

```js
it('test', () => {
  cy.visit("https://c2pms-stage.azurewebsites.net/Account/SignIn")
})
```

![](http://g.recordit.co/zk7bErGrRm.gif)

Seems like it may be happening after this cache.js script is appended. 

>Cypress used to work but for some reason now it does not.

I don't see any evidence of this working in a previous version of Cypress, so I suspect that the application under test has changed making it not render properly within the Cypress iframe anymore for some reason.

**Comment by sainthkh** [comment]
[Office.js](https://appsforoffice.microsoft.com/lib/1/hosted/Office.js) is the cause of the problem. 

When it loads, it checks how the script is loaded and it redirects the page to the "about:blank" with the code below: 

```js
if(typeof OsfOptOut===a&&f&&window.top!==window.self){window.console&&window.console.log&&window.console.log("The add-in is not hosted in plain browser top window.");window.location.href="about:blank"}
```

**Comment by dmvasquez** [comment]
Wow - thanks @sainthkh appreciate the help! Do you know how I can make this if statement not execute in cypress? Like is it possible to have cypress ignore this? (this is only happening under a cypress test)

**Comment by sainthkh** [comment]
As far as I know, there is no way to do this in Cypress. I have 2 suggestions: 

1. If office.js is not necessary, remove it. 
2. If it's loaded from node_modules, use [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by dario-piotrowicz** [comment]
Sorry I just wanted to suggest to close this issue as it seems pretty much resolved and inactive :slightly_smiling_face:
