### ISSUE TITLE
Reporter - the file (filename) property is undefined

### ISSUE THREAD

**Issue by leventecsordas** [cypress-io/cypress#1495]
### Current behavior:

When I use junit or any other reporter the `file` property of the `suite` object from the `runner.on('suite', function(suite) {})` listener is undefined.

### Desired behavior:

The `file` property of the suite should be the name of the file which contains the given test suite.

### How to reproduce:

In the example below I used `junit` reporter, but it can be reproduced with any reporter which contains filename in their report.

`cypress run --spec [spec_file].js --reporter junit` or `cypress run --reporter junit`

Bug:
The generated report doesn't contain the `file` property.

Expected: 
You should have a `file` on the generated report.
 

### Additional Info (images, stack traces, etc)

Suite object from the reporter:

![image](https://user-images.githubusercontent.com/2777071/37850529-1e836df8-2ee4-11e8-9ac4-a0b2aca0d404.png)

Generated report without filename:

![image](https://user-images.githubusercontent.com/2777071/37850232-176104a0-2ee3-11e8-98f4-6c2099bd9066.png)

**Comment by wrseward** [comment]
Having this same issue as well.

This would be great to have as part of [CircleCI test parallelization timings, as it requires the filenames to be present](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timings-data).

**Comment by paast** [comment]
Any news on this? Has anyone found a workaround for retrieving spec file names within a reporter?

**Comment by HugoGiraudel** [comment]
That would be good to have the path to the spec file indeed. :)

**Comment by Tarjei400** [comment]
Would be nice to have it, especially beacouse we are using cypress-run to re run failed tests, and we have failed reports collected by Jenkins due to that

**Comment by egucciar** [comment]
This bug prevents us from parallelizing Cypress in CircleCI by timings.

**Comment by ddesna** [comment]
I'm developing custom reporter and I would like to get screenshot of failed test. Without file name in mocha suite I could not access to cypress/screenshots failed test folder.

**Comment by BBE78** [comment]
Hi, I'm also interested by a correction on this issue, any news? This missing `file` information is needed for SonarQube reporters.
I did find a workaround (by adding the spec file path to the root suite) but it alters the root suite name with useless data...

**Comment by BBE78** [comment]
I've published a NPM package [cypress-sonarqube-reporter](https://www.npmjs.com/package/cypress-sonarqube-reporter) to workaround this issue...
