### ISSUE TITLE
Uncaught error while using type command on google autocomplete input.

### ISSUE THREAD

**Issue by piotr-bejamas** [cypress-io/cypress#14956]
I'm testing react gatsby based app with google autocomplete functionality.

### Current behavior
While using type() command, right after passing value to input app becomes blank and uncaught error shows up in console.
Very rarely it passes type commands, but few commands later Chrome crashes with "Aw, Snap!" error, code:11.
Error: Cannot destructure property 'targetLocation" of (intermediate value) as it is undefined.
<a href="https://ibb.co/FJWQr9f"><img src="https://i.ibb.co/S0xkj21/Zrzut-ekranu-2021-02-4-o-15-37-24.png" alt="Zrzut-ekranu-2021-02-4-o-15-37-24" border="0" /></a>

### Expected behavior
After typing query, user selects option from autocomplete dropdown. Then app genarates list of locations near selected place.

### Test code to reproduce
Test code, I tried:

```js
cy.getBySel('booking-location-title').should('contain', data.de.step1Title);
cy.getBySel('booking-location-search-input').type(data.de.step1searchQuery)
cy.get('.pac-container', {timeout: 10000}).should('exist').and('be.visible');
cy.get('.pac-item').first().should('be.visible').click()
cy.getBySel('booking-location-distance').should('exist').and('be.visible')
```
or

```js
cy.getBySel('booking-location-title').should('contain', data.de.step1Title);
cy.getBySel('booking-location-search-input').type(`${data.de.step1searchQuery}{downarrow}{enter}`)
cy.getBySel('booking-location-distance').should('exist').and('be.visible')
cy.getBySel('booking-location-name').first().should('contain', data.de.step1searchFirstResultTitle);
```
Tried to:
- ignore uncaught error by listening Cypress.on in support/index.js
```js
Cypress.on('uncaught:exception', (err, runnable) => {
return false
})
```
- disabling chrome web security
- using keys instead clicking
- adding delay to type command
- using cy.wait() just to check if cypress waits for something to load

Additional info:
I'm using gatsby-cypress plugin in this spec
Elements that I interact with are NOT inside iframe

### Versions
Cypress 6.3.0
Electron 87
Chrome 88
Brave 88
Firefox 85

**Comment by piotr-bejamas** [comment]
Update:
Though in concole it throws uncaught error, cypress runner shows assertion error. So maybe ignoring uncaught error is not respected here?
<a href="https://ibb.co/Y3z87KG"><img src="https://i.ibb.co/1LDKfpx/Zrzut-ekranu-2021-02-6-o-11-42-09.png" alt="Zrzut-ekranu-2021-02-6-o-11-42-09" border="0"></a>

**Comment by jennifer-shehane** [comment]
Ignoring the uncaught error is working as designed. It ignores uncaught errors and does not fail the test when they are thrown to the console.

Your test is now failing because the `[data-test=booking-location-distance]` element is not found in the DOM. 

Can you provide a reproducible example? We'll have to close the issue otherwise because there's no way for us to investigate. 

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by piotr-bejamas** [comment]
@jennifer-shehane You're right. Closing that issue. It was related to our app, not Cypress.
Basically we had some condition if google map was loaded && input value length >0 it should take value from sessionStorage, but it was not set there(we save value from previous user search and autofill input). So when user was typing and meanwhile map finished loading condition was met and app was crashing.
