### ISSUE TITLE
Add option for improved debugging of long, failing selectors

### ISSUE THREAD

**Issue by JackTheDane** [cypress-io/cypress#14976]
Hi team!

### What would you like?
Add an option to have long selectors passed to "cy.get" be split into sub-selectors, when the element cannot be found, for easier debugging, similar to when using chained methods.

### Why is this needed?
In our team, we have a series of controllers to help interact with the application UI. Lately, we have been trying to minimize flakiness in our tests, using the [guidelines for improved retry-ability in tests](https://docs.cypress.io/guides/core-concepts/retry-ability.html#Merging-queries), and have found that debugging long, very specific selectors becomes extremely difficult, due to not knowing which part of the selector that failed.

Example of a failing four-level deep selector:
![image](https://user-images.githubusercontent.com/35668734/107251978-35999280-6a35-11eb-9fad-bb048e9d9b2f.png)

When compared to our other implementations (Which use chained _findByTestId_ methods), this is far harder to debug, as there is only one DOM snapshot, and as opposed to the example below:

![image](https://user-images.githubusercontent.com/35668734/107251502-b1dfa600-6a34-11eb-8a9b-142455265ca3.png)

Would it be possible to have something similar to this debugging experience, when using longer query selectors for improved retry-ability?

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

We send along the single selector from the `cy.get()` and query it in the DOM, so splitting up a selector at arbitrary points and querying the DOM for every single possibility it could be split is not something we would work on implementing. 

This seems like something that could be implemented yourself in a custom command though if you work through some of the logic.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
