### ISSUE TITLE
Cypress Crashes w/ SIGSEGV Error in CircleCI w/ Parallelism

### ISSUE THREAD

**Issue by jonstone904** [cypress-io/cypress#14975]
### Current behavior
When running a workflow in CircleCI with a Cypress job, one or more of the containers will crash with a SIGSEGV error during the test run. This happens sometimes mid run and sometimes at the end of the run after all tests have passed. Attached are a screenshot fo the output in CircleCI as well as the DEBUG logs from the cypress run in CircleCI. This is happening a lot more frequently since we upped our parallelism in CircleCI to 3 from 2.
![Screenshot1](https://user-images.githubusercontent.com/46907262/107248807-ae322c00-6a00-11eb-93c8-33e71eeb9314.png)
![Screenshot2](https://user-images.githubusercontent.com/46907262/107248810-aecac280-6a00-11eb-958f-79541c6dc714.png)
[CircleCI Cypress Logs.txt.zip](https://github.com/cypress-io/cypress/files/5945112/CircleCI.Cypress.Logs.txt.zip)

### Desired behavior
Cypress should not crash and/or send SIGSEGV error during CircleCI run with parallelism

### Test code to reproduce
Happening for our entire project and not able to share repo/code

### Versions
Tests are running on the latest version of Cypress at this time (6.4.0) and on the latest version of Chrome. CircleCI is using a Docker Medium executor and the following images: `circleci/ruby:2.5.8-node-browsers`, `circleci/mysql:5.7.24`, `cypress/base:14.7.0`

**Comment by jonstone904** [comment]
@jennifer-shehane FWIW, I added `"video": false` to my `cypress.json` and that seems to have improved the stability and I haven't had any SIGSEGV errors since. I'll report back if anything happens.

**Comment by jennifer-shehane** [comment]
Yeah, not sure where to investigate without a way to reproduced. I haven't seen the `[1169:0208/152803.484173:VERBOSE1:CONSOLE(1)] "Main._createAppUI: 27.44287109375 ms", source: devtools://devtools/bundled/main/main.js (1)` error before either.

**Comment by jonstone904** [comment]
@jennifer-shehane I'm working on migrating our tests to Github Actions and got some logs that may help:

[CypressLogs.txt](https://github.com/cypress-io/cypress/files/5974166/CypressLogs.txt)

**Comment by pkyeck** [comment]
I'm getting the same error: `The Test Runner unexpectedly exited via a exit event with signal SIGSEGV`
But I'm not using parallelism on CircleCI.

@jennifer-shehane Which logs would you need to maybe see where this error comes from?

I'm still on 6.2.1 - I'll try and update and see if the errors goes away ...

**Comment by jonstone904** [comment]
@pkyeck Do you have the Cypress debug logs from your runs? Wonder if it's the same stack trace I'm seeing

**Comment by pkyeck** [comment]
@jonstone904 where did you find the stacktrace? I tried running with `DEBUG=cypress*` and there were lots of logs but no error was thrown ...

```
cypress:server:browsers:electron launching browser window to url: http://ui/__/#/tests/integration/user_detail_access.js +6ms
  cypress:server:browsers:electron debugger attached +23ms
  cypress:server:browsers:electron debugger: sending Browser.getVersion with params undefined +0ms
  cypress:server:browsers:electron clearing cache +2ms
  cypress:server:browsers:electron debugger: received response to Browser.getVersion: { jsVersion: '8.7.220.29', product: 'Chrome/87.0.4280.88', protocolVersion: '1.3', revision: '@74d8d14571473c7c1f4d9a98c77f08121040837b', userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/6.2.1 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36' } +3ms
  cypress:server:routes Serving Cypress front-end by requested URL: /__/ +11s
  cypress:server:server Getting remote state: { auth: undefined, props: { port: '80', tld: 'ui', domain: '' }, origin: 'http://ui', strategy: 'http', visiting: false, domainName: 'ui', fileServer: null } +104ms
  cypress:server:runner serving runner index.html with config { version: '6.2.1', platform: 'linux', arch: 'x64', projectName: 'app' } +13s
  cypress:server:runner env object has the following keys:  +0ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 40016 } +11s
  cypress:cli child event fired { event: 'exit', code: null, signal: 'SIGSEGV' } +5m
  cypress:cli Stopping Xvfb +5m
  cypress:cli child event fired { event: 'close', code: null, signal: 'SIGSEGV' } +40ms
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Debian - 10.6)
Cypress Version: 6.2.1
```

**Comment by jonstone904** [comment]
@pkyeck I stumbled upon the trace I found when I was testing out cypress in GitHub Actions. Not sure how to get it from CircleCI unfortunately. Setting `video: false` in my cypress.json seemed to help initially, but now the errors have been more frequent and I'm running Cypress 6.5.0

**Comment by pkyeck** [comment]
@jonstone904 I've always disabled video-creation on the CI server. So no luck there ...
Just tried re-running the test via SSH but they passed without error three times :( 
Now updated cypress from 6.2.1 -> 6.5.0 and will check again.

**Comment by jonstone904** [comment]
@pkyeck any luck with your errors? Still happening for us.

**Comment by pkyeck** [comment]
@jonstone904 Sadly no. Tried downgrading to 5.6.0 – the SIGSEGV error is gone but I get other random failures now :(

**Comment by jonstone904** [comment]
Just wanted to give an update: I reached out to CIrcleCI support and they think this could be a problem with memory allocation and the container basically crashing because we're not on the correct resource class to run all these parallel machines. Not sure about you @pkyeck, but that might be worth looking into.

**Comment by pkyeck** [comment]
@jonstone904 thanks for the update. 

As I mentioned above, after downgrading these errors went away. I sometimes get the "maxListener" errors and tests randomly fail – but this seems be a different problem.
I currently don't have the time to test the newest version with a higher resource class. 

But please update the issue if this turns out to be a solution to the problem. Thanks again
