### ISSUE TITLE
If the last record in the Command Log is a canceled or aborted XHR the test shows failure

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14978]
Cypress v6.4.0

Look at the image below: 6 passing tests, no failures, BUT the last test shows the failure icon. I think this happens when the last command in that test is an aborted XHR request

<img width="940" alt="Screen Shot 2021-02-08 at 2 39 59 PM" src="https://user-images.githubusercontent.com/2212006/107272554-dc713500-6a1b-11eb-8674-165cc5a87b0b.png">

## Reproduction

Clone https://github.com/bahmutov/ceceliacreates-nuxt/tree/problem branch `problem`

```
git checkout problem
npm install
npm run local
```

Click on the spec

Notice how this movie shows the status of the test keeps toggling depending on the XHR logs

https://user-images.githubusercontent.com/2212006/107421654-3808f480-6ae8-11eb-82c1-304f2d09aec3.mp4

At the end, the passing test becomes red again after a few more XHRs were cancelled

**Comment by jennifer-shehane** [comment]
Could you provide a reproducible example please? 😄

**Comment by bahmutov** [comment]
Yeah, I will add instructions for reproduction, but want to note that a user also reported same problem here

https://gitter.im/cypress-io/cypress?at=6021494e84e66b7f7edd7858

```
Hi all,
I have a test for a react app for a login page. On that page there is a request fired to get an access token which is supposed to fail with a 401 which it does. So I'm trying to visit a page (in a logged out state) which is supposed to give me a 401, but I'm ignoring it with {failOnStatusCode: false}, however it displays that the test fails (see screenshot above).
What am I doing wrong?
Interestingly enough, when I run the same test 'headless' it tells me it's passing. Is there a bug in the visualization?
```

![image](https://user-images.githubusercontent.com/2212006/107382969-7be70400-6abe-11eb-8c2b-99caec38e9b8.png)

**Comment by panzarino** [comment]
I think that this could be a regression introduced by some of the changes that I made for studio - I'll investigate

**Comment by panzarino** [comment]
I'm saying this before I'm fully certain, but I'm 99% sure that the issue is caused by [this](https://github.com/cypress-io/cypress/commit/4bff77ce2627e5243432adbe8a57de125c372824#diff-d7a49320461494662980a18d77893cc92c83a0fb4291cdfe5168f01b3e257b32R118-R120) and is a regression introduced with the Studio error state updates in `6.4.0`.
