### ISSUE TITLE
Framebusting on 3rd party (top.location != location)  breaks cypress test

### ISSUE THREAD

**Issue by huseyinalp-zz** [cypress-io/cypress#14986]
Cybpress 6.4.0 (6.4.0.597354)

When we're trying to test payment simulation using Cypress, we have trouble to complete writing test scenario for checkout flow. On our example, when we select payment methods, it redirects to an external page to confirm payment and somehow the test window closes immediately.

Sample URL : https://test.adyen.com/hpp/ideal/IssuerPage 

On my configiration, I didn't disabled modifyObstructiveCode option. 
modifyObstructiveCode : true (as default)

related issue : https://github.com/cypress-io/cypress/issues/886

**Comment by jennifer-shehane** [comment]
@huseyinalp Can you provide the Cypress test code to reproduce the issue? Thanks!

**Comment by huseyinalp** [comment]
Hello @jennifer-shehane ;
I don't understand which part of test code you need but if you create small script to visit to sample URL, you can see what is happening.

`describe('My First Test', () => {
  it('Visits Adyen page', () => {
    cy.visit('https://adoring-booth-f68425.netlify.app/');
    cy.get('#test').click();
  });
});
`

Thanks

**Comment by prdarm** [comment]
PayPal PPC002049:1.1:2d3ac8379c6b2

**Comment by prdarm** [comment]
https://test.adyen.com/hpp/ideal/IssuerPage

**Comment by huseyinalp** [comment]
> PayPal PPC002049:1.1:2d3ac8379c6b2

??

**Comment by huseyinalp** [comment]
Hello @jennifer-shehane ;
do you have any feedback for this?
Thanks

**Comment by jennifer-shehane** [comment]
I can recreate the issue as described:

```js
it('Visits Adyen page', () => {
  cy.visit('https://adoring-booth-f68425.netlify.app/');
  cy.get('#test').click();
});
```

<img width="582" alt="Screen Shot 2021-05-06 at 3 24 03 PM" src="https://user-images.githubusercontent.com/1271364/117361032-1d43e300-ae7f-11eb-9bba-265f98ca03a5.png">

If you pass `chromeWebSecurity: false`, then the webpage breaks out of the Cypress iframe and takes up the entire runner window. `experimentalSourceRewriting` doesn't change the behavior.

<img width="1172" alt="Screen Shot 2021-05-06 at 3 25 09 PM" src="https://user-images.githubusercontent.com/1271364/117361151-45cbdd00-ae7f-11eb-8407-f62199e9660a.png">

**Comment by AtofStryker** [comment]
@huseyinalp-zz have you tried the new `experimentalModifyObstructiveThirdPartyCode` option?

**Comment by vishwa999** [comment]
@huseyinalp-zz  Are you able to resolve the issue , even i am having the same issue, so if you solved this issue, can you ping me the code snippet which works fine to handle the 3rd party url.

**Comment by AtofStryker** [comment]
@vishwa999 I am going to close this issue as stale since I haven't heard back from @huseyinalp-zz . You can try the `experimentalModifyObstructiveThirdPartyCode` options or if on an older version of Cypress, possibly setting `chromeWebSecurity` to `false`. If this is still an issue for you, can you open a new issue?
