### ISSUE TITLE
Cypress.on('fail) runnable doesn't return err data instantly

### ISSUE THREAD

**Issue by nickclicksco** [cypress-io/cypress#1498]
Hi, when I run the following snippet:

```js
Cypress.on('fail', function(err, runnable) {
  console.log(runnable);
});
```

I can see this object is returned: ![Object Image](https://image.ibb.co/bZudFS/Screen_Shot_2018_03_26_at_09_36_44.png)

If I try and access `console.log(runnable.err);` it returns `undefined`.

When I use `setTimeout()` I can get it to return data:

```js
setTimeout(function () {
  console.log(runnable.err);
}, 1000);
```

So it seems `err` is returned with a delay, this took me quite some time to resolve.

Is this something you could fix for future users?

**Comment by jennifer-shehane** [comment]
I can't recreate this. 

Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
