### ISSUE TITLE
using cy.contains against a textarea with style="height: 0px" passes even though the user cannot see it

### ISSUE THREAD

**Issue by iainxt** [cypress-io/cypress#14981]
I suspect this is not how it is intended to work so I am raising this has a bug.

### Current behavior
cy.contains passes when there is a textarea with style="height: 0px;" that hence means the user cannot see it.

### Desired behavior
cy.contains fails when the element is not visible.

### Test code to reproduce
```js
describe('JsFiddle', () => {
    it('TextArea issue', ()=> {
        cy.visit('https://jsfiddle.net/ur5gmqvs/7/');
        cy.get('iframe[name="result"]').then($iframe => {
            const $body = $iframe.contents().find('body');
            cy.wrap($body)
                .find('#helloWorld')
                .should('have.length', 1);
            cy.wrap($body)
                .find('textarea')
                .contains('Comment 2');
            cy.wrap($body)
                .find('#theRedDiv')
                .contains('Comment 2');
        })
    });
});
```

### Versions
Chrome 88
Cypress 6.4.0

![image](https://user-images.githubusercontent.com/146976/107313439-a0ef6d00-6ae6-11eb-853c-dcf057379717.png)

**Comment by jennifer-shehane** [comment]
It seems they `cy.contains()` does not check for visibility by default when `height: 0`.

`index.html`

```html
<div style="border:1px solid red" id="theRedDiv">
  <textarea style="height: 0;">Comment 2</textarea>
  <span id="helloWorld" style="height: 0;">Hello World</span>
</div>
```

`spec.js`

```js
it('div no height', () => {
  cy.visit('index.html');
  cy.get('#helloWorld')
    .contains('Hello World').should('be.visible')
  })

it('textarea no height', () => {
  cy.visit('index.html');
  cy.get('textarea')
    .contains('Comment 2').should('be.visible')
})
```

**Comment by iainxt** [comment]
Thanks for the speedy reply.

The first test says div but its a span and apparently span have no height. That explains why I can see it on the right and the test passes. I tried as a div and the content is still visible to the user.

Perhaps because the textarea is slightly visible it passes?

This is a simplified html for a react material UI app I have built that is passing despite the fact the comment is hidden
![image](https://user-images.githubusercontent.com/146976/107315606-2a08a300-6aeb-11eb-8c9b-eb1865f45a9e.png)
I have resorted to using `let hidden = node.style.cssText.includes('height: 0px');`

**Comment by bahmutov** [comment]
1. by default `cy.contains` only checks the presence of the element in the DOM. If you want to make sure it is visible, use `cy.contains('some selector', 'some text').should('be.visible')`
2. if the element has height 0, but `.should('be.visible')` passes, that's probably because of some margin or border that make the element visible. Use https://on.cypress.io/dom#is-visible method to debug the visibility algorith, you can watch this little video showing how to do so https://www.youtube.com/watch?v=nSmHxxwceDU&list=PLP9o9QNnQuAYYRpJzDNWpeuOVTwxmIxcI&index=18

**Comment by sainthkh** [comment]
When Cypress checks visibility, it checks the offsetHeight, for those 2 elements, the height of `<textarea>` is 4 and `<span>` is 17. It's a reasonable result that they're both visible to the user.

**Comment by dario-piotrowicz** [comment]
Sorry I just wanted to suggest to close this issue as it seems pretty much resolved and inactive :slightly_smiling_face:
