### ISSUE TITLE
Integration Cypress with Optimizely

### ISSUE THREAD

**Issue by kalaivanee** [cypress-io/cypress#14980]
@bahmutov  : I tried to Integration Cypress with Optimizely with the help of audience condition.

Added a audience condition with string cypress = on and had that enabled.

When i run the tests and pass the query string =on, it enabled the feature and executed the tests and passed the query string =off, it disabled the feature and executed the tests.

All the above stuff works absolutely fine if the feature flag is turned off. But when its turned on, it always have that feature enabled even though when i pass the query string on/off.

EVERYONE Feature is turned ON 
![image](https://user-images.githubusercontent.com/77075297/107290308-4bf31e80-6a34-11eb-85eb-67122d48c9d7.png)

cypress=on
![tempsnip](https://user-images.githubusercontent.com/77075297/107290633-e3f10800-6a34-11eb-9f87-b53f19e29109.png)

cypress=off
![tempsnip](https://user-images.githubusercontent.com/77075297/107290744-13a01000-6a35-11eb-8e8b-72231d154875.png)

Can you please help me with this issue?

**Comment by bahmutov** [comment]
Can you please provide a reproducible example showing the problem? I have no idea what Optimizely does, what the test does, or what is going on there

**Comment by kalaivanee** [comment]
Hello Gleb : I implemented based on the following blog 
https://www.youtube.com/watch?v=payZtbdv8R8&ab_channel=Cypress.io
https://blog.optimizely.com/2020/03/26/automation-testing-feature-flags/

**Comment by bahmutov** [comment]
Maybe ping someone from Optimizely? We at Cypress have no idea what the spec code is doing or how the Optimizely app is supposed to behave

**Comment by kalaivanee** [comment]
Is there someone i can tag here? or open an issue in their blog?

**Comment by bahmutov** [comment]
I think you would need to ask them

**Comment by kalaivanee** [comment]
thanks
