### ISSUE TITLE
Add support to cy.type() for "typing into document"

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#150]
Allowing the document to be the subject when using `cy.type()` will allow typing that doesn't need a text field (namely, keyboard shortcut capturing) to be tested. So a user can write the following test, for example:

```javascript
// for this example, assume there's a listener on `document` that
// opens a modal when 'abcd' is typed
cy
  .document().type('abcd')
  .get('.modal').should('have.text', 'A modal!');
```

**Comment by brian-mann** [comment]
Fixed in [`0.17.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0171-08312016).

You can achieve this by typing into the body.

```javascript
cy.get("body").type("{ctrl}s")
```
