### ISSUE TITLE
Feature Request: Ability to "visit" with a post

### ISSUE THREAD

**Issue by Tarig0** [cypress-io/cypress#1500]
- Operating System: Win 10
- Cypress Version: 2.1
- Browser Version: ELectron

### Is this a Feature or Bug?
Feature

### Current behavior:

Request allows me to post information but not have the browser run Javascript
Visit allows me to issue, only, get requests and then runs the javascript

### Desired behavior:

Have the ability to have a visit esc command or an option to send post data that will resolve to a window that will then run JS to validate elements that are added by the JS

**Comment by jennifer-shehane** [comment]
Could you more fully explain the situation that you are trying to test that is not met by `cy.request()` and `cy.visit()` implementation as is? What is your application's behavior that you'd like to test?

**Comment by Tarig0** [comment]
Sorry for the late reply. My use case was posting a preformated request and expecting the browser to settle into a certain state.

Today you have to
1. Visit
2. Fill in form values
3. Trigger post

I was looking to skip these steps.

**Comment by brian-mann** [comment]
Yeah, I see how this could be useful. It could be like using `cy.request` like so...

```js
cy.visit({
  url: "https://foo.com/submit",
  method: "POST",
  body: {
    some: "values",
  },
})
```

This matches how `cy.request` works except that to pass urlencoded values you have to set `{ form: true }` else it sends the request body as JSON.

With `cy.visit()` it makes no sense to send anything other than urlencoded values so maybe that option doesn't need to exist.

**Comment by Paratron** [comment]
Any update on this?
