### ISSUE TITLE
cy.get cannot find data targets

### ISSUE THREAD

**Issue by westandy** [cypress-io/cypress#1501]
I am running a local storybook (localhost:9001) with one Node.js application.

I am running Cypress on another Node.js application.

I am trying to get my QA people up and running by using simple tests with the provided documentation.

Embedded deep in my storybook link, I have 

`<span class="some__class_name" data-qa-target="a_unique_name">Blah blah blah</span>`

According to the documentation, here: https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements,

I should be able to say:

```js
   it('cy.get() - query DOM elements', function() {
      cy.visit('mylink');
      cy.get('[data-qa-target=a_unique_name]').then($elem => {
        console.log($elem);
      });
  });
```

But Cypress is telling me 
`CypressError: Timed out retrying: Expected to find element: '[data-qa-target=oas-landing-provider-name]', but never found it.`

If I'm doing something wrong, it's not obvious to me.  Any suggestions?  There are no buttons or inputs above this span.  It's literally `body`, `section`, `div` upon `div`, and some `span`s within the `div`s

**Comment by jennifer-shehane** [comment]
Your test looks written correctly from what you have provided. Have you been able to [hover back over when the command runs](https://docs.cypress.io/guides/core-concepts/test-runner.html#Command-Log) to see if the element is actually on the page at that time? 

The element may not be there yet if it is waiting for an xhr request to finish, for example.

**Comment by westandy** [comment]
I think the problem is actually with storybook.  I'm using this blog as a reference: https://medium.com/@mtiller/testing-react-components-using-storybook-and-cypress-1689a27f55aa

And it looks like I need to grab the first storybook id, ` cy.get('#storybook-preview-iframe')` but then I'm sort of lost after that.  But I don't think that's an issue with `cypress`.  We can close this, I would say.
