### ISSUE TITLE
Feature: Ability to easily set workers to offline

### ISSUE THREAD

**Issue by jpodwys** [cypress-io/cypress#15011]
### What's the problem?
I'm attempting to write end-to-end tests for an application with an offline mode powered by a service worker. While `Cypress.automation` allows me to easily set the test's main thread to offline, I cannot easily do so for worker threads and cannot therefore test offline mode.

### Possible solution
Puppeteer's [`browser.targets`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#browsertargets) appears to expose a subset of [CRI](https://github.com/cyrus-and/chrome-remote-interface)'s output. Having the list of targets allows users to [set workers to offline](https://github.com/puppeteer/puppeteer/issues/2469#issuecomment-621860300).

It would be valuable to be able to access similar functionality from Cypress, perhaps with something like `cy.targets` or even `cy.CRI` so long as it comes from a context that's aware of all targets (so [not a browser context](https://github.com/cyrus-and/chrome-remote-interface#browser-usage)).

Even better, a Cypress abstraction might look something like
```js
cy.setOnline: (updateAllTargets: boolean = false)
cy.setOffline: (updateAllTargets: boolean = false)
```

Please let me know if providing code samples of my test setup in both Cypress and Puppeteer would be helpful. I'm happy to do so. Thank you!

**Comment by similicious** [comment]
I found a workaround for the problem: Using a `cy.task`, we can execute code in node from the test. I installed `puppeteer-core` and created a task to send arbitrary commands to all targets matching the type `page` or `service-worker`.

Note that Cypress needs to be executed with the `CYPRESS_REMOTE_DEBUGGING_PORT` env variable. 

cypress/plugins/send-devtools-command-to-page-and-service-worker.js
```javascript
const puppeteer = require('puppeteer-core')

module.exports = async ({ command, params }) => {

  console.log(`Plugin executed for command ${command}, params:`, params);

  const remoteDebuggingPort = Number(process.env.CYPRESS_REMOTE_DEBUGGING_PORT);
  const browser = await puppeteer.connect({ browserURL: `http://127.0.0.1:${remoteDebuggingPort}` });

  const targets = (await browser.targets()).filter(target => target.type() === 'page' || target.type() === 'service_worker');

  const sendPromises = targets.map(target => new Promise(async (resolve, reject) => {
    try {
      console.log(`Sending to ${target.type()} at`, target.url());
      const cdpSession = await target.createCDPSession();
      await cdpSession.send(command, params);
      resolve(null);
    } catch(error) {
      reject(error);
    }
  }));

  await Promise.all(sendPromises);

  return null;
}
```

cypress/plugins/index.js
```javascript
const sendDevtoolsCommandToPageAndServiceWorker = require('./send-devtools-command-to-page-and-service-worker');

module.exports = on => {
  on("task", { sendDevtoolsCommandToPageAndServiceWorker })
};

```
cypress/integration/demo.spec.ts
```javascript
describe('Service worker', () => {

  it('caches requests when offline to replay later.', () => {

    cy.task('sendDevtoolsCommandToPageAndServiceWorker', { command: 'Network.enable' });
    cy.task('sendDevtoolsCommandToPageAndServiceWorker', {
      command: 'Network.emulateNetworkConditions',
      params: {
        offline: true,
        latency: 0,
        downloadThroughput: 0,
        uploadThroughput: 0,
        connectionType: 'none'
      }
    });

    // Your test here

    cy.task('sendDevtoolsCommandToPageAndServiceWorker', {
      command: 'Network.emulateNetworkConditions',
      params: {
        offline: false,
        latency: 0,
        downloadThroughput: 0,
        uploadThroughput: 0
      }
    })
    cy.task('sendDevtoolsCommandToPageAndServiceWorker', { command: 'Network.disable' })
  })
});

```

Unfortunatley, this doesn't solve my problem completely: I use a service worker to cache failed requests wich are played back once the device is back online. When testing manually with devtools it works as expected and the requests are replayed right away. In the test however, the browser doesn't seem to recognize that it's online again and doesn't dispatch a SyncEvent.
