### ISSUE TITLE
Be able to run cypress/included on an Nx workspace

### ISSUE THREAD

**Issue by hadrien-toma** [cypress-io/cypress#15029]
### What would you like?

I would like to maintain the less possible code in order to execute my Cypress tests on an [Nx workspace](https://nx.dev/latest/angular/plugins/cypress/overview) :grin:.

As I explained [here](https://github.com/nrwl/nx/issues/4704), for the moment I maintain my own Docker image, with Cypress included for running the Cypress tests of my Nx workspace (this image is shared across developers and CI machines and the command used to run tests is the Nx one).

Few days ago, I discovered [this article](https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/), presenting `cypress/included` and I would be very happy to use it as a single Cypress source of truth. Unfortunately I am not able to run it on an Nx workspace (I tested it on a classical Angular app and liked it a lot :yum:).

### Why is this ~needed~ wanted?

Nx workspaces are very powerful and popular, providing a "ready-to-go" image to its users could improve their dev(ops) experience (in fact, I know several companies which would be very interested in this strategy for running their Cypress tests).

### Note

Following the discussion in [the abovementioned issue](https://github.com/nrwl/nx/issues/4704), I am considering the fact this feature could be transformed in a "documentation feature" because I suppose the issue can be solved by mounting the correct files in their correct places. Does anyone have an idea of something which could match in this case?

**Comment by weyert** [comment]
I am curious why you are mixing `yarn` and `npm`? 

> npm notice created a lockfile as package-lock.json. You should commit this file.

> yarn add v1.22.5
> info No lockfile found.

**Comment by hadrien-toma** [comment]
I am not mixing them (even if it is not forbiden): I only call yarn, NPM is here too as it is officially present in the node image...

**Comment by weyert** [comment]
Personally, I would advise to make a reproducible repository. I would happy to have a look but don't have the time to recreate your setup

**Comment by hadrien-toma** [comment]
Thank you very much @weyert, did you check the steps needed to reproduce the issue in https://github.com/nrwl/nx/issues/4704 ?
I made it reproductible, what is blocking you?

**Comment by hadrien-toma** [comment]
I am now able to use the `cypress/included` image only as I wanted. What I have done:

- Use `--entrypoint` docker run argument in order to set it to `/bin/bash` and bypass the default cypress command execution
- Mount the Nx workspace in the container
- Set the Docker container "working directory" to the Nx workspace
- Execute the standard `npm run nx e2e` command inside the container

Simple, efficient, with nearly 0 technical debt, thank you very much Cypress team to provide this `included` image! :heart_eyes:
