### ISSUE TITLE
Cypress hangs unexpectedly when using while or do-while loop 

### ISSUE THREAD

**Issue by RobertPecz** [cypress-io/cypress#1503]
- Operating System: Windows10 64 bit
- Cypress Version: 2.1.0
- Browser Version: Chrome65 and Electron 59

### Is this a Feature or Bug?
Bug

### Current behavior: 
In my test case I like to run the teststep (it) (or alternatively the testcase(context) in a loop. In this case it's only for figured it to how to use it, but in other test cases it might needed to for example loop a testcase for 15 minutes (like in Robot Framework 'Wait until keyword success' keyword). With a for loop it's works like a charm, but with a while or do-while loop I think it's hanging unexpectedly. Attached a print screen. It only occurring when I put an It or context snippet into to while loop, when I using the loop like 

```js
var x = 0
while(x < 5){
  cy.log(x);
  x++;
}
```
Is working as well.

### Desired behavior:
I think it should work with with a while loop as well.

### How to reproduce:
Simply when I click on the js file in the Cypress runner or trying run all tests it's hanging.
![capture](https://user-images.githubusercontent.com/20776035/37953974-a625f02e-31a4-11e8-896c-ba4f13fd036f.JPG)

#### Test code:

```js
describe('Smoke test of the Tricentis website Header Logo', function () {
    beforeEach(function () {
        cy.viewport(1920, 1080);
        cy.visit('http://demowebshop.tricentis.com/');
    });
    var numberOfCycles = 0;
    
    context('Smoketest Headerlogo', function () {
        do {
            it('Click on the Header logo', function () {
                cy.get('.header-logo > a > img')
                    .click()
                    .url()
                    .should('eq', 'http://demowebshop.tricentis.com/');
                numberOfCycles++;
            });
        } while (numberOfCycles < 5);
    });
});
```

**Comment by chrisbreiding** [comment]
When you're using `it()`, it doesn't run the test immediately, but registers the test to be run later. Mocha waits for all tests to be registered and then runs them in order. Because of this, `numberOfCycles` never increases and the `do while` keeps running indefinitely. Put the `numberOfCycles++` outside of the `it()` and it should work.

```js
        do {
            it('Click on the Header logo', function () {
                cy.get('.header-logo > a > img')
                    .click()
                    .url()
                    .should('eq', 'http://demowebshop.tricentis.com/');
            });
            numberOfCycles++;
        } while (numberOfCycles < 5);
```
