### ISSUE TITLE
Downloading a PDF with intercept corrupts the file

### ISSUE THREAD

**Issue by nickpalmer** [cypress-io/cypress#15038]
### Current behavior

Downloading with intercept on a URI corrupts the file contents.

This is #9359 on the download side. The fix made for #9359 isn't the "right" fix. Yes, it avoids corrupting multi-part file uploads, but it corrupts all binary downloads.

The problem is STILL here:
https://github.com/cypress-io/cypress/blob/develop/packages/net-stubbing/lib/server/intercept-request.ts#L116

You cannot convert a buffer to a string with toString() unless you know the data is a string, and not binary data.

This also probably messes with download of files which are not utf8 encoded, for example something encoded in utf16le, since you will be converting them into utf8 before you save them.

I didn't dig deep enough to understand why the toString() is required at all.  If other layers are expecting a string, then let THEM do the conversion when they are sure they know they have a string.

For the times you are doing toString() you may want to check the ContentType header for the encoding and put that in `toString()` if Node will support it, but LOADS of uncommon encodings are not supported in Node, though these are unlikely to be tested with Cypress.

### Desired behavior

Downloading with intercept should not corrupt the file.

### Test code to reproduce

https://github.com/nickpalmer/cypress-intercept-buffer-bug

### Versions

6.3.0

**Comment by johnnyperkins** [comment]
This is also an issue when trying to `upload` a file.
Uploading to `s3` with header `Content-MD5` fails since the request body is binary data and the `toString()` changes it's hash.

**Comment by MuckT** [comment]
Another test repo that works on windows machines: [cypress-file-upload-tests](https://github.com/MuckT/cypress-file-upload-tests);

A fix to this might also resolve: 
#8232 
#14275

**Comment by MuckT** [comment]
@jennifer-shehane this is likely PR that broke it in [6.2.1](https://github.com/cypress-io/cypress/issues/9359): #14235. Looks like it's slated to be fixed in the 7.0.0 release.

**Comment by bahmutov** [comment]
I tried the branch `7.0-release` and it is still broken when calling `res.setDelay`. Reproducible example in PR https://github.com/cypress-io/cypress-example-recipes/pull/688

**Comment by pedrovgs** [comment]
Hi! I'd need to intercept a request and return a pdf file I have saved as a fixture but looks like this issue is breaking the fixture integration and corrupting the data. Do you know if there is any workaround we can use or something we can do to fix this issue?
