### ISSUE TITLE
Cypress intercept isn't adding the alias to the cypress state requests

### ISSUE THREAD

**Issue by shannonhochkins** [cypress-io/cypress#15036]
### Adding `.as` to an intercept adds the alias for things like `get` and `wait`, however the requests array does not have the alias, every request mocked using intercept has an alias of 'undefined'

```
it('Should be able to find the request to check if its been called', () => {
    cy.intercept('GET', '/something', { body: [] }).as('alias-name');
    cy.request('/something');
    cy.wrap((cy.state('requests').filter(req => req.alias === 'alias-name')).its('length').should('eq', 1) // fails
});
```

### Desired behavior
The alias should be added to the requests array, this works for route but not for intercept...

### Test code to reproduce
see above

### Versions

`^6.3.0`

**Comment by eloisetaylor5693** [comment]
Also experiencing this issue in `^6.4.0`

**Comment by eloisetaylor5693** [comment]
Found another way around.  This method worked for me (approach stolen from tests in this repo):
```javascript
const timesCalled = 3;

cy.intercept(/\/users\?_limit=(3|5)$/).as('users');
cy.wait('@users').its('response.body').should('have.length', 3);

// Important difference:
cy.get('@users.all').then((interceptions) => {
    expect(interceptions).to.have.length(timesCalled);
    // other assertions.....
});
```

Seems like `cy.state('requests');` no longer has aliases available, but other functionality does

**Comment by flotwig** [comment]
@eloisetaylor5693 These are not documented APIs, but Cypress internals. In the future there may be a public API for this, but in the meantime, private APIs are not officially supported.
