### ISSUE TITLE
When run cypress record form git actions dispatch the run number does not change! "Run #167" 

### ISSUE THREAD

**Issue by LuyTester** [cypress-io/cypress#15041]
When run cypress record form git actions dispatch the run number does not change! "Run #167" 
That makes that git actions detect that this run is already passed and does not rerun the tests:
![Screenshot 2021-02-11 at 10 45 53](https://user-images.githubusercontent.com/52031937/107621509-a8ce1f00-6c56-11eb-9cc1-8ba39fa9bbb4.png)

As you see in the image, only the first time they run, after the next time. Consider that tests are finished.

**Comment by poncem91** [comment]
My team is also experiencing this issue.

Whenever our tests are run on a push action, the schedule action runs thereafter run the same run number as before and no tests are actually run.

**Comment by jennifer-shehane** [comment]
There's a note in running GitHub Actions that explains how to work around this limitation:

>Warning ⚠️: Cypress actions use GITHUB_TOKEN to get the correct branch and the number of jobs run, making it possible to re-run without the need of pushing an empty commit. If you don't want to use the GITHUB_TOKEN you can still run your tests without problem with the only note that Cypress Dashboard API connects parallel jobs into a single logical run using GitHub commit SHA plus workflow name. If you attempt to re-run GitHub checks, the Dashboard thinks the run has already ended. In order to truly rerun parallel jobs, push an empty commit with git commit --allow-empty -m "re-run checks" && git push. As another work around you can generate and cache a custom build id, read [Adding a unique build number to GitHub Actions](https://medium.com/attest-engineering/adding-a-unique-github-build-identifier-7aa2e83cadca)
