### ISSUE TITLE
should('not.be.empty') assertion successful on empty element

### ISSUE THREAD

**Issue by Sevpfl** [cypress-io/cypress#15052]
### Current behavior
Hi, currently (v6.4) the should('not.be.empty') assertion can be used after a get() or find() command that was not able to find an element and will still pass.

<img width="1168" alt="Screenshot 2021-02-11 at 15 12 28" src="https://user-images.githubusercontent.com/15630714/107650521-dcbd3a80-6c7e-11eb-8031-9ede5e32e506.png">

### Desired behavior
If an element could not be located, prior to a should('not.be.empty') assertion, I would expect the test to fail and display the following assertion error: 
> Timed out retrying after 4000ms: Expected to find element: DOESNOTEXIST, but never found it.

Identical to how other assertions like .should('not.have.text', "text") currently fail.
```
    cy.get('DOESNOTEXIST')
      .should('not.have.text', "text")
``` 
<img width="436" alt="Screenshot 2021-02-11 at 15 50 08" src="https://user-images.githubusercontent.com/15630714/107652431-dcbe3a00-6c80-11eb-8f34-a94aca0d6483.png">

### Test code to reproduce
The code can be added to any existing spec.
I created a fresh empty project, installed cypress and added the snippet to the first test of the actions.spec.js example
```
 cy.get('DOESNOTEXIST')
   .should('not.be.empty')
```

Here is the forked test-tiny example
https://github.com/Sevpfl/cypress-test-tiny

### Versions
Cypress v6.4.0
Chrome 88

**Comment by Xdudu** [comment]
> If the object asserted against is not a jQuery object, the original implementation will be called.

⬆️  According to the "empty" assertion in [chai-jquery](https://github.com/chaijs/chai-jquery#empty), this behavior is expected. But I think you can utilize `.should('not.to.match', ':empty')` for asserting the emptyness on a possibly non-existing element :)

**Comment by sainthkh** [comment]
As @Xdudu said, it's an expected behavior. Internally, should('not.be.empty') use jQuery's `is(':empty')`. And the result for `is(':empty')` against "length 0" jQuery object is `false`. Please check the code below:

```js
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
</head>
<body>
 
<script>
console.log($( "#doesnotexist" ).is(':empty')) // => false
</script>
 
</body>
</html>
```

### Workaround

Use `should('not.exist')` instead like `cy.get('DOESNOTEXIST').should('not.exist')`;
