### ISSUE TITLE
Page not fully loading

### ISSUE THREAD

**Issue by romulanul** [cypress-io/cypress#15065]
### Problem description
While visiting the https://semantic-ui.com/modules/checkbox.html the page is not completely loaded - only the top of the page is loaded. Due to this, further elements on the page cannot be found.

![2021-02-12 01_36_27-cypress-err](https://user-images.githubusercontent.com/36658502/107713078-2d5e8300-6cd3-11eb-9487-b67466bcd660.png)

### Test code to reproduce
```js
it('My FirstTest case',function() { 
cy.visit("https://semantic-ui.com/modules/checkbox.html")
cy.contains("Make my profile visible").click()
}) 
```

### Browsers
Chrome. Firefox, Electron

### Versions
Cypress package version: 6.4.0
Cypress binary version: 6.4.0
Electron version: 11.2.1
Bundled Node version:
12.18.3

**Comment by sainthkh** [comment]
Confirmed that the test code above reproduces the problem.

I found the message, `Tab: Activated tab cannot be found. Tabs are case-sensitive.`, on the console window, It doesn't show on the normal execution. It needs further research.

**Comment by jennifer-shehane** [comment]
This page loads and the test passes if you pass `experimentalSourceRewriting: true` to your Cypress configuration. I would suggest passing this configuration to test the website. 

`cypress.json`

```json
{
  "experimentalSourceRewriting": true
}
```

```js
it('My FirstTest case', function () {
  cy.visit("https://semantic-ui.com/modules/checkbox.html")
  cy.contains("Make my profile visible").click()
})
```

<img width="1427" alt="Screen Shot 2021-05-03 at 2 18 04 PM" src="https://user-images.githubusercontent.com/1271364/116922058-6e06d200-ac1a-11eb-9602-36bab518983e.png">
