### ISSUE TITLE
Update cypress.json schema URL at Schemastore

### ISSUE THREAD

**Issue by virgilwashere** [cypress-io/cypress#15067]
### What would you like?

Update the URL for `cypress.json` schema at https://schemastore.org (Original PR #1109)

In your [documentation](https://docs.cypress.io/guides/tooling/IDE-integration.html#Configuration
) you reference `https://on.cypress.io/cypress.schema.json` which redirects to https://raw.githubusercontent.com/cypress-io/cypress/develop/cli/schema/cypress.schema.json

### Why is this needed?

The [SchemaStore catalog](https://github.com/SchemaStore/schemastore/blob/fcbfd26200b9ecb3974d434358993fafd7c8cfa9/src/api/json/catalog.json#L566-L573) points to https://raw.githubusercontent.com/cypress-io/cypress/v5.3.0/cli/schema/cypress.schema.json

https://github.com/SchemaStore/schemastore/blob/fcbfd26200b9ecb3974d434358993fafd7c8cfa9/src/api/json/catalog.json#L566-L573

```json
    {
      "name": "cypress.json",
      "description": "Cypress.io test runner configuration file",
      "fileMatch": [
        "cypress.json"
      ],
      "url": "https://raw.githubusercontent.com/cypress-io/cypress/v5.3.0/cli/schema/cypress.schema.json"
    },
```

Thanks

Virgil

**Comment by bahmutov** [comment]
I would like someone from the community to do this since we recommend using our URL for this.

**Comment by virgilwashere** [comment]
@hasibhassan thanks!
