### ISSUE TITLE
Add keywords to npm package.json

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1508]
Should probably have keywords to enhance npm package search.

*Sad, no keywords*
<img width="1154" alt="screen shot 2018-03-27 at 2 26 00 pm" src="https://user-images.githubusercontent.com/1271364/37987011-14567f5c-31cb-11e8-9029-a2a26831e699.png">

*Suggested keywords*
```json
{
  "keywords": [
    "browser"
    "cypress",
    "automation",
    "mocks",
    "test",
    "testing",
    "runner",
    "spies",
    "stubs"
  ]
}
```

Need to add to root `package.json` and update `build` process to copy over `keywords` here: https://github.com/cypress-io/cypress/blob/develop/cli/scripts/build.js#L8

**Comment by bahmutov** [comment]
hahaha, really sad!

**Comment by bahmutov** [comment]
The keywords are copied from the root package.json file, so I will place them there.
