### ISSUE TITLE
Error upon requiring ibm_db module

### ISSUE THREAD

**Issue by lhimo** [cypress-io/cypress#15092]
### Current behavior
If I require the module "ibm_db" from either spec file or plugins/index.js I get the following error:

![Immagine 2021-02-15 141817](https://user-images.githubusercontent.com/36077138/107951888-4d26cd00-6f99-11eb-92b2-bf6251dca167.png)

The stacktrace is the following:
```
Error: The module '\\?\C:\[...]\node_modules\ibm_db\build\Release\odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (C:\[...]\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\[...]\node_modules\ibm_db\lib\odbc.js:57:31)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
```

### Desired behavior
I would like to import the module as a plugin/command in order to perform DB2 queries.

### Test code to reproduce
It is sufficient to install the "ibm_db2" module and then requiring it with:

`var ibmdb = require('ibm_db');`

### Versions
Cypress version 6.4.0 on Windows

**Comment by bahmutov** [comment]
Tell Cypress to use the system Node https://on.cypress.io/configuration#Node-version

Look at the slides https://slides.com/bahmutov/cypress-beyond-the-hello-world#/5/3/0 (press down key to go through this column of slides) or watch the entire presentation https://www.youtube.com/watch?v=Q5djbLL1Pjg

**Comment by lhimo** [comment]
Thanks @bahmutov now I can load the module but the task defined as in the example [page ](https://docs.cypress.io/api/commands/task.html#Syntax) is not logging to the console. What can I do?

**Comment by bahmutov** [comment]
Provide the code your run, have screenshots etc. otherwise I have no idea what your issue is.

**Comment by lhimo** [comment]
This is my spec file:
```
describe("Connetti al db", () => {

    it("crea una connessione", () => {
        cy.task('log', 'messaggio')
    });
})
```

And this is plugins/index.js:
```
module.exports = (on, config) => {
    on('task', {
        log (message) {
          console.log(message)    
          return null
        }
    })
}
```

but when I run the spec nothing gets printed on the console:

![image](https://user-images.githubusercontent.com/36077138/108066333-7d38a380-705f-11eb-881b-0584173fe8ca.png)

**Comment by bahmutov** [comment]
What does the test runner show? Does it show the task command? What does it print in the devtools console when you click on the task command?

**Comment by lhimo** [comment]
Sorry, here it is:

![image](https://user-images.githubusercontent.com/36077138/108066895-4a42df80-7060-11eb-8fcd-dbd571aec733.png)

**Comment by bahmutov** [comment]
Can you run Cypress not from the VSCode built in terminal but from a regular terminal?

**Comment by lhimo** [comment]
I tried both Powershell and cmd but it's not printing the message

**Comment by bahmutov** [comment]
Can you add throwing an error before returning from the task? Is the thrown error shown

**Comment by lhimo** [comment]
I tried with "throw 'Parameter is not a number!';", but no luck

**Comment by bahmutov** [comment]
I have put your code and ran it in https://github.com/cypress-io/cypress-test-tiny/tree/log-example

I am getting the console message

<img width="1280" alt="Screen Shot 2021-02-16 at 9 46 47 AM" src="https://user-images.githubusercontent.com/2212006/108078978-4b621580-703c-11eb-9163-ed684e0b7e86.png">

You can even enable `DEBUG=cypress:server:task` to see verbose logs https://on.cypress.io/troubleshooting#Log-sources

<img width="853" alt="Screen Shot 2021-02-16 at 9 48 24 AM" src="https://user-images.githubusercontent.com/2212006/108079108-6c2a6b00-703c-11eb-9e86-afa687691da6.png">

**Comment by lhimo** [comment]
If it helps, running a normal js file prints correctly to the console

**Comment by bahmutov** [comment]
Normal meaning not a cypress plugin?

**Comment by lhimo** [comment]
yes a js file outside cypress folder

Il mar 16 feb 2021, 17:42 Gleb Bahmutov <notifications@github.com> ha
scritto:
