### ISSUE TITLE
Getting and setting URL doesn't work in @cypress/react

### ISSUE THREAD

**Issue by midanosi** [cypress-io/cypress#15106]
## Current Behaviour
React hooks that set and get URL don't work in @cypress/react tests

## Desired Behaviour
Tests that rely on setting and getting the url to be possible to write for @cypress/react

## Other info
This is a roadblock I've been hitting multiple times recently, and I can't see any way around it. Could you please review my scenarios and suggest how I could test these scenarios using @cypress/react? I know I could just test these e2e, but I think there’s immense value in being able to test components in isolation. 

One quick point before listing 2 scenarios, I’ve personally learnt that the following pattern is good - if a component is getting/setting url state, then that url state should be the single source of truth, rather than say setting an equivalent state in react, and updating url as a side-effect. So this belief is my motivation for creating this ticket.

## Scenario 1 - initialising props
A common pattern I use is to have say React Router, with a `/items/:item` route.

Then an `Item` component;
```js
import * as React from 'react'
import { useParams } from 'react-router-dom'

const Item = () => {
  const { data } = useQuery()
}
```

So this `itemId` is the core prop for the component, and I seemingly have no way to set it. I could have defined my components like
```js
const ItemBase = ({itemId) => {
  …
}
const Item = () => {
  const { itemId } = useParams()
  return <Item itemId={itemId}
}
export { ItemBase, Item } // unit test ItemBase, use Item in rest of app
```
But having to change react code solely for the purpose of testing feels wrong. And this would be a necessity for every single component that uses data that lives in the URL.

Comparison with other testing libs - back in ol’ days with Enzyme, could have stubbed the react hook, but this smells bad and I would presume is not possible with Cypress? As for @testing-library/react, I think I saw that you could set a `route` attr in a config object on the mount function to achieve this desired effect.

## Scenario 2 - setting a query parameter, and asserting it’s been set

In this scenario, I have a Table which I am applying a search to. This search string is then persisted into the url via query parameter. Then the useQuery hook I’m using for fetching has it’s variables updated, therefore triggers a refetch. In my test I wish to assert 1. The url update, 2. The refetch.

```js
Import * as React from ‘react’
Import { useQueryParam, StringParam } from ‘use-query-params’

const SearchableTable = () => {
  const [foo, setFoo] = useQueryParam('foo', StringParam)
  const { data } = useQuery(“/api/tabledata”., {
    variables: {
      foo: foo,
    }
  }
  return (
    <>
      <label name="search">
        Search
        <input name"search" value={foo} onChange={(newVal) => setFoo(newVal)} />
      </label>
      <Table data={data} />
    </>
  )
}
```

and test code:
```js
specify("apply search, query param set in url, refetch triggered", () => {
  cy.intercept("/api/tabledata").as("tableQuery")
  const testSearchString = "this is my search string"
  mount(<SearchableTable />)
  cy.wait("@tableQuery") // wait for 1st request to complete
  cy.findByLabelText("Search").type(testSearchString)
  
  // url assertion
  cy.location().contains(`search=${testSearchString}`) <--- FAILURE HERE as url doesn't update
  
  // refetch assertion
  // 1. spy on the intercept somehow (can't remember how to do this off the top of my head), verify been called a 2nd time now
  // 2. wait on intercept and verify request succeeds
  cy.wait("@tableQuery").then((intercept) => {
    expect(intercept.response.status).equals(200)
  })
})
```

## Other wild speculation
Is the way that the Cypress runner loads a component by setting the url to sort of point at a file location? And this is why cy.visit() is overridden to block url being set?

**Comment by jennifer-shehane** [comment]
Please try updating to the latest versions of Cypress and @cypress/react. We made several changes in 7.0+ and this is likely resolved. Please comment if you're still experiencing this issue after updating.
