### ISSUE TITLE
Module not found: Error: Can't resolve 'cypress-react-selector'

### ISSUE THREAD

**Issue by softshipper** [cypress-io/cypress#15108]
Hi all 

I am trying to use [@cypress/react][1] and I followed the installation instructions. Besides, I have also installed [Cypress Testing Library][2] to use Testing Library extensions for Cypress. 

When the cypress is started, I have got the following error messages:
```
./node_modules/@cypress/react/support/index.js
Module not found: Error: Can't resolve 'cypress-react-selector' in '/home/developer/project/example/webapp/board-ui/node_modules/@cypress/react/support'
resolve 'cypress-react-selector' in '/home/developer/project/example/webapp/board-ui/node_modules/@cypress/react/support'
  Parsed request is a module
  using description file: /home/developer/project/example/webapp/board-ui/node_modules/@cypress/react/package.json (relative path: ./support)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
[/home/developer/project/example/webapp/board-ui/node_modules/@cypress/react/support/node_modules]
[/home/developer/project/example/webapp/board-ui/node_modules/@cypress/node_modules]  
```

Installed packages:
```
  "devDependencies": {
    "@cypress/react": "^5.0.0",
    "@testing-library/cypress": "^7.0.3",
    "cypress": "^6.5.0"
  }
 ```

Thanks

  [1]: https://www.npmjs.com/package/@cypress/react
  [2]: https://www.npmjs.com/package/@testing-library/cypress

**Comment by KoenCa** [comment]
I also got this when trying to run a test after updating Cypress dependencies from:

```json
{
  "@cypress/webpack-preprocessor": "^5.5.0",
  "cypress": "6.4.0",
  "@cypress/react": "^4.16.4"
}
```

to:

```json
{
    "@cypress/webpack-preprocessor": "^5.6.0",
    "cypress": "6.5.0",
    "@cypress/react": "^5.0.0",
}
```

I fixed it by adding `cypress-react-selector` so it becomes:

```json
{
    "@cypress/webpack-preprocessor": "^5.6.0",
    "cypress": "6.5.0",
    "@cypress/react": "^5.0.0",
    "cypress-react-selector": "^2.3.6"
}
```

Not sure why I need to add this dependency. I don't see this mentioned in any release notes.

**Comment by dmtrKovalenko** [comment]
Yeah, it's definitely a bug and this dependency should not be required by default. But I don't think we will be able to release this for the current @cypress/react version (we are near to release major stable version)

**Comment by anark** [comment]
@dmtrKovalenko Isn't the major version bump of cypress/react the one specified here?  Bumping to 5.0.0?

**Comment by dmtrKovalenko** [comment]
**please don't use @cypress/react v5** it is broken and should be reverted

**Comment by anark** [comment]
Thanks for the heads up.  Looking forward to seeing the changes for @cypress/react v5 when they are ready

**Comment by anark** [comment]
It looks like @cypress/react v5 has been released again.  Is this now ready to use?  When I try I am still seeing this issue.

**Comment by elevatebart** [comment]
Thanks @anark, it's great to see the excitement around this library. 

`@cypress/react` 5.0.1 works now but only if you install cypress 6.6.0. 
There was a little corruption in the 6.5.0 that we missed. 
Remember that 5.0.1 is an internal release. We changed the architecture entirely and I am writing the documentation as we speak. If you want to try things out and give us your feedback make sure you are connected to the cypress discord so that we can help you along the way. 

In terms of timeline, we aim to have a full release with cypress 7.0.0 at the beginning of March.
If you prefer a more stable build for your real tools, it probably would be wise to wait until then.

Can't wait to show you all we made!!

**Comment by reintroducing** [comment]
@elevatebart I don't see a v6.6.0 available on npm, v6.5.0 seems to be the latest.

**Comment by lee-beydoun-privitar** [comment]
I am also seeing this error: 
```
../../../node_modules/@cypress/react/dist/mount.d.ts:4:15 - error TS2306: File '/Users/leeprivitar/Workspace/dpp-exchange-ui/node_modules/cypress-react-selector/index.d.ts' is not a module.

export * from 'cypress-react-selector';
```
However, installing `cypress-react-selector` doesn't seem to help. I am using:
```
{
    "cypress": "^6.6.0",
    "@cypress/react": "^5.0.1",
    "@testing-library/cypress": "6.0.1",
}
```
Is there any update on this?

**Comment by lmiller1990** [comment]
As of the latest version, `5.3.2`, this module is no longer bundled or exported. This should no longer be problem.

Please upgrade to the latest version (and ideally Cypress 7.x, with the improved component testing runner + architecture). [Learn more here](https://www.cypress.io/blog/2021/04/06/introducing-the-cypress-component-test-runner/).

If there is still an outstanding problem after that, I will re-open and investigate. I was unable to reproduce with the latest version of everything.
