### ISSUE TITLE
Need to manually reset browser cache to run cypress

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#15102]
On shifting to cypress v6.5.0 and electron v11.2.3, on headed mode file changes aren't being watched even though the `"watchForFileChanges": true,` has been specified in cypress.json. The user has to manually clear the cache of the browser in the application menu for the new changes to reflect.

This behaviour isn't replicable in headless mode and is also not applicable since files aren't watched for change.

More info- 
Using zsh with oh_my_zsh plugin 
Node version 12.18.3 via nvm
Tried clearing cypress cache and app data didn't solve the issue.

**Comment by jennifer-shehane** [comment]
Does your site utilize service workers? There's an existing issue with file watching and service workers.

**Comment by n-Aden** [comment]
Yes, we do use service workers. Thank you for the clarification.
