### ISSUE TITLE
Cypress hangs randomly on test runs

### ISSUE THREAD

**Issue by vandammeb** [cypress-io/cypress#15124]
### Current behavior
Tests runs on CI (jenkins) and locally (using the same docker image) randomly get stuck in a never ending loop.
Some test runs (short application smoke tests, where the login is done through request to skip the ui part and a route in the application is visited) complete without a problem, and others get stuck and never complete or fail.
The application under test is using the angular service worker, which keeps triggering its cache busting mechanism when cypress never stops the tests (even if all tests have completed...)

![image](https://user-images.githubusercontent.com/1032765/108243717-af74fe80-714e-11eb-9779-4b114e5cdd90.png)

### Desired behavior
Test runs should preferably never hang or bail with a clear error after a configurable time frame.

### Test code to reproduce
I'm afraid I cannot share much code atm, but I've attached partial logs of the a successfull run and one that hangs:

hanging run logs:
[cypress_fail_2.txt](https://github.com/cypress-io/cypress/files/5995527/cypress_fail_2.txt)
[cypress_fail.txt](https://github.com/cypress-io/cypress/files/5995561/cypress_fail.txt)

successful run log:
[cypress_success.txt](https://github.com/cypress-io/cypress/files/5995571/cypress_success.txt)

One difference between success and failing logs is this warning:

`cypress:proxy:http warning: Request was not fulfilled with a response`

### Versions

- cypress 6.4.0 (CI tests runs have only recently been set up, so no prior versions tried)
- @cypress/webpack-preprocessor: "5.6.0"
- cypress-cucumber-preprocessor: "4.0.1"
- browser: chrome, chrome headless
- docker image: cypress/included:6.4.0
- angular 11 application

**Comment by jennifer-shehane** [comment]
We'll really need a way to reproduce this on our end in order to investigate. Otherwise we'll need to close. Can you provide any way to reproduce? Even with an example application?

**Comment by vandammeb** [comment]
@jennifer-shehane I'll try to set up an example repo in the coming days. I can open a new issue and refer to this one then if you want/need to close this one.

**Comment by norvinino** [comment]
@jennifer-shehane On the other hand, in my case the cypress closes completely and stops running. This it does in various tests. That's why I have to reopen the cypress

**Comment by emilyrohrbough** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
