### ISSUE TITLE
Cypress fixture returns an object that somehow is not an instanceof Object

### ISSUE THREAD

**Issue by jordyvandomselaar** [cypress-io/cypress#15135]
### Current behavior

```js
cy.fixture("example.json").then(fixture => console.log(fixture instanceof Object))
```

Logs `false`

```js
console.log(require("../../fixtures/example.json") instanceof Object);
```

Logs `true`

This is a problem because we use Immer to _mutate_ state but it doesn't work on the fixture data, breaking our app in Cypress tests.

### Desired behavior

```js
cy.fixture("example.json").then(fixture => console.log(fixture instanceof Object))
```

Logs `true`

### Test code to reproduce

https://github.com/jordyvandomselaar/Cypress-fixture-no-instanceof-object-bug

### Versions

1. "cypress": "^6.5.0",
2. MacOS Catalina 10.15.6

**Comment by jennifer-shehane** [comment]
```js
it('cy.fixture() - load a fixture', () => {
  cy.fixture("example.json").then((fixture) => {
    // logs false
    console.log("Cypress Fixture", fixture instanceof Object)
  })

  // logs true
  console.log("Require Fixture", require("../../fixtures/example.json") instanceof Object);
  
  // logs true
  console.log("Plain Object", {"key": "value"} instanceof Object);
})
```

The code for fixtures can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/fixture.js#L39:L39 

For now I would recommend requiring the fixtures as you showed where it will be `instanceof Object`.

**Comment by jordyvandomselaar** [comment]
@jennifer-shehane thanks for the reply! `require` does work and for now I'm using that, let me know if I can help get this resolved!

**Comment by sainthkh** [comment]
### Workaround

Use `global.parent.Object` instead of `Object`. 

```js
console.log('Cypress Fixture', fixture instanceof global.parent.Object) // => true
```

### Why it happened?

When `iframe` is in the HTML code, every `Object` is not same. We need to check where it came from. 

In Cypress runner, there are 3 types of windows:

1. Runner: This contains the reporter on the left (the list of test names we all know and love)
2. App: The app under test on the right
3. test file: It is not visible. But as it is written on the homepage, test files are run under the browser. It is possible because it is loaded from an iframe. 

When we simply write `Object`, it's from 3, test file. And the `__proto__` of the object generated by `cy.fixture()` is from 1, the runner. That's why simple `fixture instanceof Object` didn't work. 

### Problem & Possible Solution

It's super unintuitive. 

Maybe, we need to create APIs like `cy.runner()` that returns the runner window like `cy.window()`. Then, we can rewrite the code like below: 

```js
cy.runner().then(runner => {
  console.log('Cypress Fixture', fixture instanceof runner.Object) // => true
})
```

**Comment by jordyvandomselaar** [comment]
> ### Workaround
> Use `global.parent.Object` instead of `Object`.
> 
> ```js
> console.log('Cypress Fixture', fixture instanceof global.parent.Object) // => true
> ```
> 
> ### Why it happened?
> When `iframe`s are in the HTML code, there are multiple `Object`s which came from the `window`s. We need to check where it came from.
> 
> In Cypress, there are 3 types of windows:
> 
> 1. Runner: This contains everything. The reporter is on the left (the list of test names we all know and love). Cypress commands are run under this context.
> 2. App: The app under test on the right (where you can see how your app is working.)
> 3. Test file: It is not visible. Test files are run under the browser. It became possible because files is loaded into an iframe.
> 
> When we simply write `Object` on a test file, it's from 3, test file. And the parent `Object` of the object generated by `cy.fixture()` is from 1, the runner. That's why simple `fixture instanceof Object` didn't work.
> 
> ### Problem & Possible Solution
> It's super unintuitive.
> 
> Maybe, we need to create APIs like `cy.runner()` that returns the runner window like `cy.window()`. Then, we can rewrite the code like below:
> 
> ```js
> cy.runner().then(runner => {
>   console.log('Cypress Fixture', fixture instanceof runner.Object) // => true
> })
> ```

Unfortunately, that wouldn't work in this case. the Object check is in the app code, not spec code.

**Comment by bahmutov** [comment]
@jordyvandomselaar can I ask how you are using the object loaded from the fixture? Do you pass it to the application somehow? In the repo you provided you just have the spec code like

```js
context('Files', () => {
  it('cy.fixture() - load a fixture', () => {
      cy.fixture("example.json").then(fixture => console.log(fixture instanceof Object))

      console.log(require("../../fixtures/example.json") instanceof Object);
      console.log({"key": "value"} instanceof Object);
  })
})
```

Which to me is fine, the above workarounds are enough. I would love to fix the application example if you can provide one.
