### ISSUE TITLE
Can't set environment variables with `cypress.open()` configuration object

### ISSUE THREAD

**Issue by alopezsanchez** [cypress-io/cypress#1513]
- Operating System: macOS Sierra 10.12.6
- Cypress Version: 2.1.0
- Browser Version: Chrome 65

### Is this a Feature or Bug?
Bug.

### Current behavior:
Access to environment variables established with `cypress.open()` doesn't work.

### Desired behavior:
`cypress.open()` should let to set env vars in the configuration object in the same way as `cypress.run()`.

### How to reproduce:
https://github.com/alopezsanchez/cypress-test-tiny/tree/env-open-error
Branch `env-open-error`.

Just run `yarn jest`.

#### Test code:

```js
cypress.open({
  env: {
    username: "foo",
    password: "bar"
  }
});
```

```js
describe("page", () => {
  it("works", () => {
    expect(Cypress.env("username")).to.equal("foo");
    expect(Cypress.env("username")).to.equal("bar");
  });
});
```

### Additional Info (images, stack traces, etc)
![captura de pantalla 2018-03-28 a las 22 21 07](https://user-images.githubusercontent.com/15221596/38054142-5ec9dbcc-32d6-11e8-9959-5d7a26914f31.png)

If you think that this is a real bug, I can submit a PR if you give me a guidance 😃 

Thank you!

**Comment by brian-mann** [comment]
There is a PR open here https://github.com/cypress-io/cypress/pull/1447/files for this and it will be merged in the next release.

**Comment by alopezsanchez** [comment]
Ups, sorry for the duplicate.

Thank you!
