### ISSUE TITLE
Issue in Cypress Dashboard - tests run from CI are not completing

### ISSUE THREAD

**Issue by cwinters8** [cypress-io/cypress#15146]
### Current behavior
Any tests that were started from CI today seem to be endlessly hanging in Cypress Dashboard even though the process in CI completes successfully.
![image](https://user-images.githubusercontent.com/40615752/108423417-7182e380-71fd-11eb-860f-541b609beb73.png)
![image](https://user-images.githubusercontent.com/40615752/108423705-cc1c3f80-71fd-11eb-9f5e-48f71086b68a.png)

### Desired behavior
Tests should be showing completed after they finish in CI and the recordings are uplaoded.

### Versions
Cypress version: 6.3.0
CI Providers: Issue occurs with both Github Actions and Amplify

**Comment by matthemsteger** [comment]
We are having this problem too, seems to be a repeat of https://github.com/cypress-io/cypress/issues/14929

**Comment by VictorGosse** [comment]
Facing the exact same problem right now

**Comment by kylemh** [comment]
https://www.cypressstatus.com/incidents/frcpl9dryz8w

**Comment by jennifer-shehane** [comment]
There’s an incident we’re currently investigating regarding degraded performance for recorded tests. Please follow here for updates. https://www.cypressstatus.com/incidents/frcpl9dryz8w?utm_source=slack

**Comment by jennifer-shehane** [comment]
We have resolved the issue with recording service status updates. New test recordings should be complete properly, we will continue to monitor for additional issues.

**Comment by HartiganHM** [comment]
I've been seeing this behavior as well. I assumed it was because I'm on a free tier account, but am not positive. I have several test runs on the Cypress dashboard that hang and, eventually, time out. I'm running version `6.5.0`. What I'm seeing is exactly the same as the initial post, but I'm happy to provide any additional details.

**Comment by jennifer-shehane** [comment]
@HartiganHM Could you send an email to our team at support@cypress.io? This original issue should have been resolved, so we'd like to look more closely at what you're experiencing. Thanks.

**Comment by KrupalVaghasiya** [comment]
@jennifer-shehane I am facing same issue. in my case in the cypress dashboard test will not stop until i cancel it manually.
