### ISSUE TITLE
Add `before:action` event

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1515]
### Feature
Add a `before:action` event that fires immediately before an action is made.

### Purpose
Allow user to debug at the time immediately before Cypress takes an action.

**Comment by tahayk** [comment]
👍

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
