### ISSUE TITLE
Information from Cypress that it is unable to finish test due to loop

### ISSUE THREAD

**Issue by GabRog** [cypress-io/cypress#15150]
### What would you like?

I would like information form cypress that I cannot successfully run test with while loop, that it will hang and never end.
I would expect that such test will be unable to run and the reason would be provided. 
I want the developer to be aware (thanks to information from Cypress) that this is a problem with his test, not with environment or test/environment configuration.

### Why is this needed?

For testing my application I used Cypress 6.5.0 with Typescript and Chrome 88.
Testing the application, I need to wait until status of activation changes. In fact I am waiting for the color of element to change. Unfortunately I need to refresh page to see if color changed (element does not change color automatically). For activation I am waiting 5-15 minutes. 
To deal with it, I used while loop placed in external method. It looked like this:

```js
while(activation_peding) {
    cy.reload();
    activation_pending = isActivationPending(); // method returns bool, when status changes to finished returns false
    cy.wait(30 seconds);
}
```

I was expecting that loop will end after activation end. When I tried to execute the test suite (description), only clause "before" was executed, the only test (it) in suite looked as if it was started but nothing happened and it hanged with "pending arrows" next to test title.
![Screen Shot 2021-02-18 at 11 36 08 PM](https://user-images.githubusercontent.com/37714253/108433944-1a096580-7247-11eb-9bf6-8d1db9f5e5b7.jpg)
At the very end I finally got "Aw, snap!" error in chrome. 
![Screen Shot 2021-02-18 at 11 45 33 PM](https://user-images.githubusercontent.com/37714253/108433940-18d83880-7247-11eb-9eb5-f5ce6cdc438c.jpg)
I spent nearly two weeks trying to figure out what has happened. I was sure, that there can't be anything wrong with the test, because I would get an information from cypress. I was trying to reconfigure project, change versions of: cypress, browsers, node + npm, but nothing helped. I thought that maybe I have something wrong with my configuration on my computer. 
when I found out that previous version of test (without loop) was passing happily I started to run test lines one by one and in such way I get to know that the problem is in while loop.

**Comment by bahmutov** [comment]
Will address in the documentation https://github.com/cypress-io/cypress-documentation/pull/3599
