### ISSUE TITLE
Mocking in Cypress

### ISSUE THREAD

**Issue by asc-it-minds** [cypress-io/cypress#15157]
I encountered an issue where I had to mock an authentication service, in order to test my application in CI with Cypress.
Having done this before in Jest with [manual mocking](https://jestjs.io/docs/en/manual-mocks#mocking-user-modules), i couldn't find a similar approach to this in Cypress.

I have tried using ```cy.stub()```, but it only seems to mock my object in the Cypress test, and not used elsewhere in my application.

Is there a way to do this, or could this be a new feature?

### What would you like?

To mock a module applications wide, like Jest's [manual mocking](https://jestjs.io/docs/en/manual-mocks#mocking-user-modules) 

### Why is this needed?

When implementing Cypress in CI, mocking authentication is needed in order to make it possible for tests to pass.

**Comment by aesfer** [comment]
I would love to start using cypress for unit and component testing, we have been using it for ages to do e2e testing and love the concise and intuitive way in which cypress test are written.

Watching the docs, comments and issues it seems that it would cover almost all our needs except that there is no way to mock and replace node modules like `jest.mock` does. This is a blocker for us.

Would love to hear any workarounds for this or at least add my vote to the proposal. This is the only thing preventing us to try cypress for unit and component testing.
