### ISSUE TITLE
When Cookies with Same Name but Different Paths Exist, All Cookies are Deleted After A PreserveOnce Call

### ISSUE THREAD

**Issue by JarvisVon** [cypress-io/cypress#15166]
This issue is very similar to [8954](https://github.com/cypress-io/cypress/issues/8954). I used a similar format for this write up.

**Current behavior**
When multiple cookies with the same name but different paths are preserved via a call to PreserveOnce, no cookies are preserved.

**Desired behavior**
All cookies are preserved, even when there are multiple cookies with the same name and path.

**Test code to reproduce**
With the baseUrl set to "https://cypress.io", run the following test:

```js
context('Cookies', function () {
  it('Test 1 - Sets Cookies', function () {
    cy.setCookie('cookie', 'value 1', { path: '/first/path/' });
    cy.setCookie('cookie', 'value 2', { path: '/second/path/' });
    cy.getCookies()
      .should('have.length', 2);
  });

  it('Test 2 - Relies on Preserved Cookies', function () {
    cy.getCookies()
      .should('have.length', 2); // Fails; 0 cookies are present.
  });

  afterEach(function () {
    cy.getCookies()
      .then((cookies) => {
        cookies.forEach((element) => {
          Cypress.Cookies.preserveOnce(element.name);
        });
      });
  });
});
```
Versions
Cypress version 5.6.0, Chrome 88, macOS 10.15.6.

**Comment by jennifer-shehane** [comment]
I can recreate this behavior. The cookies are not preserved.

```js
context('Cookies', () => {
  beforeEach(() => {
    cy.visit('index.html')
  })

  it('Test 1 - Sets Cookies', () => {
    cy.setCookie('cookie', 'value 1', { path: '/first/path/' })
    cy.setCookie('cookie', 'value 2', { path: '/second/path/' })
    cy.getCookies().should('have.length', 2)
  })

  it('Test 2 - Relies on Preserved Cookies', () => {
    // Fails 0 cookies are present.
    cy.getCookies().should('have.length', 2) 
  })

  afterEach(() => {
    Cypress.Cookies.preserveOnce('cookie')
  })
})
```

<img width="512" alt="Screen Shot 2021-02-23 at 2 16 49 AM" src="https://user-images.githubusercontent.com/1271364/108812496-36760c80-757d-11eb-8870-0a210b4eed19.png">

This is the code for the `preserveOnce` method: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/cookies.js#L119:L119

**Comment by emilyrohrbough** [comment]
In the upcoming v12.0.0 release, the deprecated `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` will be removed. This has been related with [`cy.session()`](https://docs.cypress.io/api/commands/session). Closing as won't fix.
