### ISSUE TITLE
Cypress helper 100% CPU usage per process

### ISSUE THREAD

**Issue by or9** [cypress-io/cypress#15160]
### Current behavior
Closing the browser (cmd + q) during `npx cypress open` has different behaviors between Chrome and Electron. In Chrome, it will normally close the browser and return to the test dashboard screen. Exiting Electron will close the test runner and print….
```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (17.7.0)
Cypress Version: 6.5.0
```
Sometimes it will be
> The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Either way, after a couple crashes, Activity Monitor shows multiple Cypress Helper processes both using 100% CPU. 

### Desired behavior
* Do not use 100% CPU for each of multiple Cypress helper processes after Cypress has crashed.  
* Handle closing browsers consistently.  
* Exit cleanly  

### Test code to reproduce
```bash
npx cypress open
```
Open a test in Chrome or Canary browser. Close the browser.
Open a test in Electron. Close the browser <- (and crash)  
Observe two or more Cypress Helper processes using between 0 and 100% CPU. Processes do not exit when test runner exits.

**Comment by kweiberth** [comment]
This is happening to me. It seems to happen even without the "unexpected exited" error. My machine can accumulate multiple "Cypress Helper" processes in fact, each consuming significant CPU.

**Comment by l-monninger** [comment]
Any resolutions here? I'm running into something similar.
