### ISSUE TITLE
Test runner not listing XHR calls against a certain environment

### ISSUE THREAD

**Issue by mellis481** [cypress-io/cypress#15162]
Throughout my tests, I will define a route with an alias , visit a page, and wait for the aliased route to resolve.  Here is an example:

```
cy.route('systemSettings').as('systemSettingsGet');
cy.visit('/');
cy.wait('@systemSettingsGet');
```

This has worked fine when run locally and against deployed environments.  In the Cypress test running, I see the following:

![image](https://user-images.githubusercontent.com/39313898/108537596-cda44100-72ab-11eb-84c6-158feecf22b0.png)

As you can see, my aliased route (`systemSettings`) is successfully waited on and you can see a list of XHR calls made while waiting (including the one I'm waiting on).

I recently attempted to point my Cypress tests to a different `baseUrl`.  FWIW this one is an IP address + port.  When I run the same tests against this environment:

1. No XHR calls are listed in the test runner
2. My waited route (`systemSettings`) is never found (even though I can see it called in my browser's Network tab)

Here is a screenshot:
![image](https://user-images.githubusercontent.com/39313898/108538104-6fc42900-72ac-11eb-93a6-657050ffc2f7.png)

I'm using Cypress 6.2.0.  I tried switching my `cy.route()` to `cy.intercept()` and that, in fact, corrects this situation, but results in a number of other undesirable things happened so I do not want to switch conventions at this time.

**What could be causing this?**

**Comment by bahmutov** [comment]
@mellis481 

I see in the failing test you have "click" command, then the new page URL loading. But in the local first test, I do not see this. Can I ask you to add assertions to make sure the previous page is gone before adding the `cy.route`? 

Also, could you try `cy.intercept` in this case?

**Comment by mellis481** [comment]
@bahmutov That difference is due to the fact that, for the server in the first pic (the one where I can successfully wait), the login page is on a different domain so I'm programmatically retrieving an access token before visiting my app. For the server in the second pic (the one where I cannot successfully wait), the login page is on the same domain so I can login through a UI.  The click you see is the click of a submit button on the login page which redirects to my app

I did try replacing `cy.route()` with `cy.intercept()`, but as I noted at the bottom of my post, this results in other issues that I'd prefer to not tackle at this time.

**Comment by bahmutov** [comment]
It is hard to say then, maybe the route gets lost during the login transition

**Comment by mellis481** [comment]
@bahmutov In fact it did seem to be a timing issue as I was able to put in a `cy.wait()` after the login page and I'm now seeing the XHR requests.  I don't understand why Cypress would ever not display XHR requests that are occurring, but at least I've moved beyond this blocker.

**Comment by jennifer-shehane** [comment]
@mellis481 We're working on a way to allow more control over which requests display in the Test Runner and which don't. For many people seeing 100's of requests that aren't necessarily relevant to the test is not helpful - for some people seeing all is helpful.
