### ISSUE TITLE
File download issue, after that page visit times out

### ISSUE THREAD

**Issue by kbaala88** [cypress-io/cypress#15161]
Hi, 

Currently tried on Cypress 6.3.0, 6.4.0, 6.5.0 & older versions as well. In our application under test, we see that cypress gets stuck and couldn't proceed to next page stating that it is waiting for a load event that would never occur. Tried multiple workarounds , but couldnt resolve. Same behavior in chrome & electron browsers as well.

After debugging, found that cypress thrown below error that we could see from browser console. This issue is a blocker to us and any help on this issue would be of a great help.

_<head> <script type='text/javascript'> document.domain = '***.org'; var Cypress = window.Cypress = parent.Cypress; if (!Cypress) { throw new Error('Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'); }; Cypress.action('app:window:before:load', window); </script>_

**Comment by jennifer-shehane** [comment]
This script is added to every application run within Cypress. Is this error being thrown in the console? Can you give a screenshot of the console?

Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by kbaala88** [comment]
@jennifer-shehane : Thanks for the quick response. Due to restrictions, we couldn't share the code. However, below or the snapshots.

Browser network response snapshot showing the error while cypress is stuck:

https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-wus-d9-a3d32996dd17ebca331f8d7807fd0001/views/imgo

Cypress browser window in right corner displaying the loading icon (forever):
https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-wus-d1-305dada2e90d170ced7a136374502ab0/views/imgo

Left cypress window showing, page load (forever)[NOTE: Actually application is loaded fully, but cypress waits thinking for a page load that will never load]. Couldn't workaround this and stuck.

https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-wus-d6-7085bfdcbca1b747ed4359a945f977cb/views/imgo

**Comment by bahmutov** [comment]
I am not sure I understand - is the test failing? I think the previous page is triggering file download, which breaks the next page's visit. You can mock the redirect and other server responses (even the document), see examples in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept#stubbing-application-requests-using-cyintercept

But really I do not understand what the test is meant to do, how it is written, what the app is doing, and what is going wrong or right here

**Comment by kbaala88** [comment]
@bahmutov : Yes, the test stuck in the very 2nd page of the flow. & You are right, the previous page is triggering a file download, which is breaking the next page's visit.
Our application is single page architecture application i.e., all the pages in the application will be having the same url. Is it a known issue that, if the page triggers a file download will break next page's visit?

Also, couldnt find an example to mockthe server responses ( the document). Please help with one. Thanks!!!

**Comment by bahmutov** [comment]
If you can explain how you download the file there, we could advise how to avoid the stuck test. We have a bunch of file download examples in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download recipe that might help

**Comment by kbaala88** [comment]
@bahmutov : It is about a jnlp file download and step is like , click "OK" button , JNLP file download starts and application moves to next page. When cypress gets to next page, it is getting stuck and couldn't proceed though the controls are accessible.

**Comment by bahmutov** [comment]
Can you create small repo reproducing the file download? Or fork https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download and set up the file download the way it is done in your application so that we can investigate?

**Comment by kbaala88** [comment]
@bahmutov : Due to project limitations, couldn't share the code. Cypress step is to click OK and proceed to next page and perform further steps. In the 2nd page, application loaded successfully but cypress stuck and it thinks something yet to be loaded which will never load. Please let know if we can overwrite or skip the **_waiting for new page to load_** step and proceed? 
Please note that all the pages in our application has the same URL.

**Comment by bahmutov** [comment]
@kbaala88 all I am asking is to see how the download is triggered because obviously, it is not the same as in our recipe. When you trigger the download the browser tries to display that file probably (just like a like to PDF sometimes downloads the file, but sometimes is displayed in the browser). When the browser tries to display the file - guess what, it can no longer be controlled by Cypress, since it switched to the file view mode. 

This is NOT a problem with the next page loading or waiting. This is a problem with the file taking over the browser tab, blocking the rest of the test execution.

Thus if we understand how the file download event is coded in your application, we can suggest a workaround. Without it, there are only our examples we are showing in the recipe that we can suggest.

**Comment by kbaala88** [comment]
@bahmutov : Thanks for the quick responses. It is the file displayed in the browser and the file type is .jnlp

**Comment by bahmutov** [comment]
Can you make the same reproduction example in a fork of our repo, please

**Comment by kbaala88** [comment]
Unfortunately cudnt share the code! Below wud be the sample looks like:
document.location.href = 'jnlp:$(url)'

location:Location;
onfullscreenchange:((this: Document, ev:Event) => any) | null;

**Comment by bahmutov** [comment]
Take a look at https://github.com/cypress-io/cypress-example-recipes/pull/651 
I am using CSV file, but I think the principle is the same

**Comment by kbaala88** [comment]
Thanks much for the quick responses. Is it working for the CSV file?
Applied the same to .jnlp file and still the issue persists unfortunately .;(

**Comment by bahmutov** [comment]
I don’t have an example of a jnlp file, do you have an example?

**Comment by kbaala88** [comment]
@bahmutov : There is a call planned with cypress support team on this tomorrow. Please see if you can join or i shall keep posted on this.

**Comment by ajgray2017** [comment]
Updates on this? I have a similar issue, on the latest version of Cypress, after clicking and downloading a test txt file, (Mine from a presigned url) the page waits for a new load and fails after a timeout. I am following the code presented by the cypress recipe.

**Comment by bahmutov** [comment]
If you are following the cypress recipe and it does not behave as expected can you open a pull request with a failing tests showing the screenshots or videos of what is happening?
