### ISSUE TITLE
Support SSO authentication for the Dashboard

### ISSUE THREAD

**Issue by theabraham** [cypress-io/cypress#1516]
### Is this a Feature or Bug?

Feature

### Current behavior:

Authentication is currently handled through Github login only.

### Desired behavior:

Support authentication through SSO.

Right now, our team is required to authenticate through LastPass's SSO service when using third-party tools to meet set security requirements. For this reason, we're unable to use the Cypress dashboard. I'm sure other organizations have similar requirements, so this would be a handy feature to have. Of course, the alternative would be self-hosting the dashboard. Until that's possible, simply having SSO support would go a long way, and would be much simpler to put together.

I looked into Auth0's documentations, and it seems implementing SSO may be straight-forward using their [Universal Login](https://auth0.com/docs/hosted-pages/login#single-sign-on-sso-) tools.

**Comment by jennifer-shehane** [comment]
We currently have SSO login available as an experimental feature of the Dashboard. 

Please send us an email at support@cypress.io if you’re interested in getting set up with SSO login.

**Comment by jennifer-shehane** [comment]
This has been released
