### ISSUE TITLE
Can not run any test: Webpack Compilation Error

### ISSUE THREAD

**Issue by ingriddbritok3** [cypress-io/cypress#15178]
### Current behavior
My code was running before. Now it presents the following error when I try `Cypress run`

<img width="421" alt="error" src="https://user-images.githubusercontent.com/58943407/108720402-0e58c000-7521-11eb-86ea-e07189a85a9f.png">

### Desired behavior
Cypress should be able to execute the test with the command `cypress run`

### Versions

Cypress 6.4.0 
Browser Electron 87 headless 
Operating System Wind 10

**Comment by jennifer-shehane** [comment]
You mention that your code was running before - what changed from the time that the tests were running to now. Nothing will change within Cypress unless you explicitly update Cypress. Did you update? Did you change some code?

Please provide a fully reproducible example so we can investigate.

**Comment by ingriddbritok3** [comment]
> You mention that your code was running before - what changed from the time that the tests were running to now. Nothing will change within Cypress unless you explicitly update Cypress. Did you update? Did you change some code?
> 
> Please provide a fully reproducible example so we can investigate.

@jennifer-shehane This is the point, the only change to the code was to add the following line: `cy.get('.moduleSearchInput').type('pos{enter}')` I noticed after adding this line, `const { groupBy } = require("cypress/types/lodash")` was also added automatically. So, I removed the `const { groupBy } = require("cypress/types/lodash")`, now it seems to be working. Not sure what `lodash` does or why it was added.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
