### ISSUE TITLE
JUnit result should contain browser name

### ISSUE THREAD

**Issue by Camo30** [cypress-io/cypress#15177]
### What would you like?
In the file `cypress.json` I configured the reporter using these settings:
```
{
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "result/result-[hash].xml",
    "testsuitesTitle": "Cypress Tests"
  }
}
```

When executing the tests everything works as expected and the spec reporter shows some informations about the browser being used, something like this:

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    6.4.0                                                                              │
  │ Browser:    Chrome 88 (headless)                                                               │
  │ Specs:      1 found (sample.e2e.spec.ts)                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────
```

When using the junit reporter the result looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Cypress Tests" time="3.1030" tests="1" failures="0">
  <testsuite name="Root Suite" timestamp="2021-02-22T13:27:07" tests="0" file="src\integration\sample.e2e.spec.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test for login page" timestamp="2021-02-22T13:27:07" tests="1" time="3.1030" failures="0">
    <testcase name="Test for login page should check login url successfully" time="3.1030" classname="should check login url successfully">
    </testcase>
  </testsuite>
</testsuites>
```

When executing the tests against different browsers its impossible to say which result files are from which browser because there is no browser information available.

In the same project I'm also using [Karma-JUnit-Reporter](https://github.com/karma-runner/karma-junit-reporter) which is nearly the same reporter and by setting `useBrowserName` to true its possible to embed some browser information into the resulting file. This looks like this:

```
<?xml version="1.0"?>
<testsuite name="Chrome Headless 88.0.4324.182 (Windows 10)" package="" timestamp="2021-02-19T09:55:12" id="0" hostname="wchorsta4" tests="3871" errors="0" failures="0" time="206.499">
  <properties>
    <property name="browser.fullName" value="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/88.0.4324.182 Safari/537.36"/>
  </properties>
  <testcase name="Tests for login page" time="0.242" classname="Chrome_Headless_88_0_4324_182_(Windows_10).Tests for login page"/>
  ...
```

As you can see it adds the browser name and os to the testsuite attribute and adds a property to the property list. I think Cypress should handle this the same way.

### Why is this needed?
This is needed for CI purposes. I'm trying to setup a CI pipeline which runs the tests against multiple browsers like Firefox and Chrome. For this it is needed to identify the browsers within the resulting files.

**Comment by jennifer-shehane** [comment]
You are specifying to use the `junit` reporter - https://github.com/michaelleeallen/mocha-junit-reporter If you'd like a feature added to their reporter, I'd suggest opening an issue there. This is not under the control of Cypress.

**Comment by spiltcoffee** [comment]
@jennifer-shehane From what I can tell, `mocha-junit-reporter` - or in fact, any Mocha reporter - is unable to tell from Cypress what browser the tests were run in (in a sane fashion, at least).

It would be handy to have this information be able to appear in a test report. Currently when ingesting test reports with other tools, if multiple reports from different browsers exist, there's no way currently to tell which browser a test failed in.
