### ISSUE TITLE
Electron runner crash when current page redirect to a external website.

### ISSUE THREAD

**Issue by xpol** [cypress-io/cypress#15170]
### Current behavior

When the page been tested redirect user to a external website, the electron runner will crash with the follow message:

```
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

```
(PS. the message show trice).

The Chrome runner works well with `"chromeWebSecurity": false` in cypress.json.

### Desired behavior

The test itself has successful, should not crash the test.

### Test code to reproduce

https://github.com/xpol/electron-redirect-crash

Clone above reop and run `yarn`.
- run `yarn cy:chrome` will start server and run test in chrome, which will succeed.
- yun `yarn cy:electron` will start server and run test in electron, which will fail.

### Versions

Tested with cypress 6.3/6.4/6.5.

**Comment by jennifer-shehane** [comment]
I can recreate this from the https://github.com/xpol/electron-redirect-crash example. Like described, the example crashes when run in Electron with the Chrome renderer process crashed during `cypress run`

<img width="714" alt="Screen Shot 2021-02-23 at 2 01 00 AM" src="https://user-images.githubusercontent.com/1271364/108811305-02015100-757b-11eb-830d-871a35f7489b.png">

The application waits 5 seconds then redirects to cypress.io website (the website doesn't matter). The tests pass in the example, but the Electron tests still crash if they fail. 

<img width="823" alt="Screen Shot 2021-02-23 at 2 05 53 AM" src="https://user-images.githubusercontent.com/1271364/108811790-e8acd480-757b-11eb-99ad-c9d5906f6ceb.png">

**Comment by weyert** [comment]
I think I am experiencing a similar issue.
