### ISSUE TITLE
API to extend the client?

### ISSUE THREAD

**Issue by Elecash** [cypress-io/cypress#15175]
### What would you like?
I would like to extend the Cypress client to experiment and to add custom features to it (but mostly experiment).

<img width="1430" alt="cypress-client" src="https://user-images.githubusercontent.com/790704/108685246-354ccd00-74f4-11eb-87eb-221bf1cc1a69.png">

### Why is this needed?
It would open the opportunity to create plugins and some community around it.

For example: I was thinking in adding a control bar to the cypress tests like a video player so you can play/pause and scrub the timeline.

**Comment by dmtrKovalenko** [comment]
We are working on a plugins system for component testing. We are going to release UI plugins as a part of the stable component testing release – it will allow extend the UI and analyze the components. 

Any particular feature you are interested in?

**Comment by Elecash** [comment]
Not anything in particular, I just want to play a little bit with the plugin system :)

Feel free to close this issue if there's a plugin system feature ticket already open.

**Comment by dmtrKovalenko** [comment]
Yeah, I think this can be closed, cause we are working on it. I am just curious – are you testing the design system https://semantic-ui.com/? Why not using component testing?

**Comment by Elecash** [comment]
I'm not testing anything in particular, I just want to experiment and build a plugin to play a sequence of tests like a video by setting states in a timeline.

Think about it like a video player but you "play" in a timeline states of cypress tests.
