### ISSUE TITLE
Add log: boolean option to cy.tick

### ISSUE THREAD

**Issue by emilgoldsmith** [cypress-io/cypress#15180]
### What would you like?
```js
cy.tick(2000, { log: false });
```
Currently there is no log option on tick, as I had expected while working on customizing my log. Was wondering if it was an oversight or on purpose?

### Why is this needed?
To align with the feature set surrounding allowing you to customize your log, most commands support this option so I was expecting this one to have it too, and would be nice to silence this one in a specific custom command I'm building though I'll of course live without it

**Comment by jennifer-shehane** [comment]
I don't see any reason why `cy.tick()`` wouldn't allow an options argument. Probably just an oversight. 
We'd be open to a PR to implement this. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by emilgoldsmith** [comment]
Awesome! I’ll try getting on that in the near future :)

**Comment by saturninoabril** [comment]
@emilgoldsmith I hope you don't mind but I went ahead and created a PR to address your issue. Let me know if that works for you.

**Comment by emilgoldsmith** [comment]
That’s just perfect, thank you Saturnino :)

**Comment by nbgooch** [comment]
Woops, looks like I created a duplicate pr.. Can close..

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/15586, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
