### ISSUE TITLE
Getting error with cy.screenshot() while capturing a big image (page with lots of scrolling)

### ISSUE THREAD

**Issue by maulik190** [cypress-io/cypress#15199]
**Current behavior:**

cy.screenshot() is not working with a long web page

**Desired behavior:**

cy.screenshot()  should handle a long web page

**Test code to reproduce**

```
cy.visit("https://en.wikipedia.org/wiki/United_States");
cy.screenshot("big-image", { timeout: 100000 });
```
Error:

![image](https://user-images.githubusercontent.com/13773749/108907415-0d429400-75f0-11eb-9080-d0a81e4f53c7.png)

**Comment by jennifer-shehane** [comment]
Thanks for the reproducible example. I can reproduce this from the example provided. 

```js
it('test', () => {
  cy.visit("https://en.wikipedia.org/wiki/United_States");
  cy.screenshot("big-image", { timeout: 100000 });
})
```

It appears that it's just timing out. 

<img width="845" alt="Screen Shot 2021-02-24 at 11 01 24 AM" src="https://user-images.githubusercontent.com/1271364/109028326-ae345c00-768f-11eb-875f-a2de8d15108e.png">

**Comment by maulik190** [comment]
What's the solution? How do I fix it?

Regards,
Maulik

**Comment by danielosg** [comment]
Yes, I can confirm this bug, it is also affecting us. Tried few workarounds but nothing worked.
