### ISSUE TITLE
cy.reply routeHandler option is not working

### ISSUE THREAD

**Issue by fabien-somnier** [cypress-io/cypress#15190]
As I'm trying to implement mock for some graphQL responses, I would like to be able to dynamically modify the original response from the server.
So, I've followed the given [instruction](https://www.cypress.io/blog/2020/11/24/introducing-cy-intercept-next-generation-network-stubbing-in-cypress-6-0/) about `routeHandler` implementation.
But this is not working as expected, as `routeHandler` is never called. :(

### Current behavior
- `req.reply()` is working
- `req.reply(<JSON content>)` is working
- `req.reply({ fixture: <JSON filepath>)` is working
- `req.reply(res => { <anything> })` is not working

### Desired behavior
`req.reply(res => xxx)` to be working

### Test code to reproduce
```js
cy.intercept('/graphql', (req) => {
  console.log(req); // working
  req.reply((res) => {
    console.log(res); // not working
    return res;
  });
})
```

### Versions
`6.5.0` (also not working with `6.3.0`)

**Comment by fabien-somnier** [comment]
In fact, as I've continued to investigate, the problem in my code is that there's already a previous `intercept` for `/graphql`.

```
[...]
cy.intercept('/graphql').as('graphql');
[...]
cy.intercept('/graphql', (req) => {
  console.log(req); // working
  req.reply((res) => {
    console.log(res); // not working
    return res;
  });
})
[...]
```

I hope to be able to solve this, now I understand the origin of my problem.
If so, I'll close the issue.

**Comment by flotwig** [comment]
@fabien-somnier Sounds like you got it. I'm closing this issue, but FYI, the ordering of request handlers will be reversed in Cypress 7.0.0 to simplify this. See #14543 for more details.
