### ISSUE TITLE
When filling in a table cell step Cypress is switching to another tab without any click

### ISSUE THREAD

**Issue by ChristusArulanantham** [cypress-io/cypress#15206]
I am using Cypress 6.50

The following get works fine till chaining a type, that seems to be switching to the tab next

in Tab A 
```js
cy.get('[name="example\[0\]\.name"]').last().type('Mark')
```

As soon as I add the `.type('Mark')`

it is switching to Tab B without filling the table 

If I switch to Tab A while the test is running it does fill in the fields 

Is this a known issue?
Can you please help?

Thanks

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? We need that in order to investigate. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

I'm not aware of any issues with Cypress switching to different browser tabs mid test.

**Comment by ChristusArulanantham** [comment]
Hi Jennifer,

Thanks for the prompt response 
The code is //Pilots
    addRiskPage.getPilotsTab().click().should('have.text', 'Pilots ')
    cy.get('[name="pilots\[0\]\.name"]').last().type('Mark')

as you can see I use the page object model here  
getPilotsTab(){
        return cy.findByRole('tab', { name: /Pilots/i })
    }

This part works fine.

There are several tabs in the application one is Pitot is one.
In the form is with a table (3 cells )
1st cell is the Pilot name i.e. name="pilots\[0\]\.name"
the tab next to this is a tab called Aircraft 

The issue is when the follwing code is run it is switching to the Aircraft tab without filing in the name field in the Pilot tab
 cy.get('[name="pilots\[0\]\.name"]').last().type('Mark') --- this does not work

as soon as I add the .type('Mark') 

If I try  cy.get('[name="pilots\[0\]\.name"]') then it does NOT switch to the Airtcraft tab 

the tabs are like this 

![Screenshot 2021-02-25 091803](https://user-images.githubusercontent.com/10866619/109131282-8d7d0c80-774a-11eb-94ac-85e4703ae4c2.jpg)

**Comment by ChristusArulanantham** [comment]
I have resolved the issue with the following approach;

addRiskPage.getPilotsTab().click().should('have.text', 'Pilots ')
    cy.findByRole('tab', { name: /Pilots/i }).click({force:true})
    cy.get('[name="pilots\[0\]\.name"]').type('Mark Right')
