### ISSUE TITLE
clock.restore is not a function

### ISSUE THREAD

**Issue by isaaclyman** [cypress-io/cypress#1520]
- Operating System: Windows 10
- Cypress Version: 1.4.2
- Browser Version: Chrome 65

### Is this a Feature or Bug?
Bug.

### Current behavior:
If you attempt to use `clock.restore()` as described [here](https://docs.cypress.io/api/commands/clock.html#Yields), you see the error "clock.restore is not a function."

### Desired behavior:
If you use `clock.restore()`, the browser's default setTimeout and setInterval functionality should be restored, as happens automatically between tests.

### How to reproduce:
See https://github.com/isaaclyman/cypress-test-tiny/tree/clock-restore for an example repo. Run the test and you'll see the error.

#### Test code:

```js
describe('clock.restore', () => {
  it('works', () => {
    const clock = cy.clock()
    clock.tick(1000)
    clock.restore()
  })
})
```

**Comment by jennifer-shehane** [comment]
You cannot assign or work with the return values of any Cypress command. Commands are enqueued and run asynchronously. I suggest you look over this doc to familiarize yourself with this concept: https://on.cypress.io/variables-and-aliases.html

How you could write this:

```js
cy.clock().then((clock) => {
  clock.tick(1000)
  clock.restore()
})
```

**Comment by isaaclyman** [comment]
That's a little confusing, since `clock.tick(1000)` works in the original code--in fact, I use it that way throughout my tests.

Is there a way to enqueue the `clock.restore()` command?

**Comment by isaaclyman** [comment]
Okay, I think I answered my own questions. For anyone with the same confusion:

- `cy.clock()` returns a Cypress instance. `cy.tick()` can be used without a clock instance. This gave me the impression that `cy.clock()` returned a Cypress instance, yet it does not.
- `cy.tick().then(clock => clock.restore())` would be the correct way to restore the default timeout/interval commands at a given point in a test.
