### ISSUE TITLE
Cypress detected as a Trojan

### ISSUE THREAD

**Issue by kaceyarnold** [cypress-io/cypress#1521]
- Operating System:  Windows 10 Pro 64bit OS Build 19299.309
- Cypress Version:  2.1.0
- Browser Version: Chrome 65
- Kaspersky AV
- Visual Studios 2017
- Atom

### Current behavior:
Cypress was/is detected as a Trojan virus.  

### Desired behavior:
Not detected as Trojan virus.

### How to reproduce:
Simple log in test.
Test fails at current because the CSS selector gets the area above/around the input area.
Open Dev tools in the Cypress browser.
Click the input area
right click
select inspect element.
AV should detect a trojan virus
```
31.03.2018 11.09.03	
Detected object (process memory) deleted	
c:\users\kcarn\appdata\roaming\npm-cache\_npx\14776\node_modules\cypress\dist\cypress\cypress.exe	
Process memory: c:\users\kcarn\appdata\roaming\npm-cache\_npx\14776\node_modules\cypress\dist\cypress\cypress.exe	
Object name: PDM:Trojan.Win32.Generic	
Object type: Other malware	
Time: 3/31/2018 11:09 AM
```

8 other files were also detected as infected and deleted.  My guess is that something in the files trips the AV because of how they function then the checksum or heuristics match a trojan so away it goes.

#### Test code:

```js
describe('Login', function() {
  it('clicks the link "Log In"', function () {
    // https://localhost:44300/Account/Login/?ReturnUrl=%2F
    cy.visit('https://localhost:44300/Account/Login/?ReturnUrl=%2F')
    cy.get('.login-in.input')
    .type('user@user.com')
    .should('have.value', 'user@user.com')
    //cy.contains('Log In').click()
  })//closes it
})//closes describe

// selector from Chrome dev tools
//body > div.row > div > div > article > section.log-in-with-password > form > label:nth-child(3) > input[type="email"]

```

**Comment by jennifer-shehane** [comment]
I would suggest adding Cypress to your list of trusted applications in Kaspersky AV. The very definition of a trojan is it being 'non-legitimate / non-trusted software' that you didn't intend to download, which is not what Cypress is in your case. 

[Read how to set Cypress as trusted application](https://support.kaspersky.com/us/3025)

**Comment by hakankaraduman** [comment]
Hi, do you have an updated link for adding cypress to kaspersky?

**Comment by Byron2016** [comment]
Hi, the link to "how to set Cypress as trusted application in Kaspersky" does not have information. Maybe someone can help with this problem?
