### ISSUE TITLE
preserveOnce does not preserve cookies between tests visiting different domains

### ISSUE THREAD

**Issue by lprokein** [cypress-io/cypress#15223]
I set cookie to be preserved between tests by:
```js
beforeEach(() => {
  Cypress.Cookies.preserveOnce("example_cookie");
});
```

I run test on domain1 - website sets the `example_cookie`
```js
it("domain1 - test A", () => {
  cy.visit("https://www.domain1.com/");
});
```

I run another test on domain1 - cookie `example_cookie` from previous test is preserved correctly
```js
it("domain1 - test A", () => {
  cy.getCookies({log: true});
  cy.visit("https://www.domain1.com/");
});
```

Then I run test on different domain - domain2
```js
it("domain2 - test A", () => {
  cy.visit("https://www.domain2.com/");
});
```

Then I run test again on domain1 after a test on domain2 but all cookies including `example_cookie` are now gone.
```js
it("domain1 - test B", () => {
  cy.getCookies({log: true});
  cy.visit("https://www.domain1.com/");
});
```

I expected `example_cookie` to be preserved.

### Versions
6.5.0

**Comment by abdofficial18** [comment]
Kaug;;=÷ 777286```
2777twi@jennifer-shehane whuya$$$ - tyyy ::::{{{on full support))) ***
999??@agg23 @jennifer-shehane 
```

**Comment by MuckT** [comment]
@lprokein I found preserveOnce also a bit flaky.

I use the following to preserve cookies between tests:
```JavaScript
  Cypress.Cookies.defaults({
    preserve: /[\s\S]*/,
  });
```

**Comment by lprokein** [comment]
@MuckT thanks for tip but it did not help in my case.

It preserved cookies from between 2 test runs if the last test is domainA and also the first test is domainA. But once some other test used different domainB it wiped everything again.

**Comment by akis98** [comment]
Same here

**Comment by emilyrohrbough** [comment]
In the upcoming v12.0.0 release, the deprecated `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` will be removed. This has been related with [`cy.session()`](https://docs.cypress.io/api/commands/session). Closing as won't fix.
