### ISSUE TITLE
Add option to treat API communication errors as fatal errors

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1523]
## Proposal

Currently if there is a problem communicating with the Cypress dashboard API, we just continue (usually). We should add a CLI option to treat it as a fatal error to ensure the users know that recording is not happening

Example:
<img width="944" alt="screen shot 2018-04-02 at 2 08 56 pm" src="https://user-images.githubusercontent.com/2212006/38208646-bd6c7d5e-367f-11e8-9f3e-f80569daf7eb.png">

**Comment by jennifer-shehane** [comment]
I actually don't think we do want to do this anymore. After seeing how users have interacted with our current strategies of exiting tests when our server is down, they seem to prefer gracefully falling back than to exit their test run. 

Related conversation here where users want to disable parallelization as a fallback when API server errors occur as opposed to exiting: https://github.com/cypress-io/cypress/issues/2525
