### ISSUE TITLE
New file download feature: downloads should be organized into sub-directories just like videos

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#15231]
It seems that all downloads go into the same folder, which is inconsistent with other artifacts, like screenshots and videos, which are organized into folders based on the test file name. How do we get downloads to automatically go into those same per-test folders?

Dumping all downloads into a single folder doesn't seem like a good idea to me, for the same reason you wouldn't dump all screenshots or videos into a single folder: it makes organization and triage much more difficult than it needs to be. We regularly run 50-60 test suites, comprising ~600 tests, and we'd like to start testing downloads in several tests. I think it makes sense that downloaded files get organized correctly, so if something goes wrong, we can easily find the downloaded files with our other artifacts in the same directory. Without this, we'd have to match up timestamps, which seems unnecessarily annoying.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
