### ISSUE TITLE
cy.intercept example for stubbing fetch for the same url?

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#15237]
I have a list of items on the screen, for some reason after user performed some action it called the same url. I'm doing this, it is able to stubbed for the first time

```cy.intercept('graphql/items', {fixture: items.json});```

then I did

```cy.intercept('graphql/items', {fixture: anoterItems.json});```

it doesn't stub the 'later' fetch.

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/9302
