### ISSUE TITLE
assert intercept as alias to be called?

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#15239]
How to I assert an intercept is called once in cypress?
```js
cy.intercept("POST", "graphql/updateUser", {
        fixture: test.json
      }).as("updateUser");
      cy.get('@updateUser').calledOnce() //calledOnce is not a function
```
I tried ```cy.wait('@updateUser').calledOnce()```

but no luck.

**Comment by jennifer-shehane** [comment]
`.calledOnce()` is not a Cypress command, so cannot be used off of the `cy.wait()` or `cy.get()`. You could use `@alias.all` syntax, which is undocumented. 

```js
it('test cy.intercept()', () => {
  cy.intercept('/users').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  cy.wait('@getUrl')
  cy.get('@getUrl.all').should('have.length', 1)
})
```

**Comment by bahmutov** [comment]
Hey @thian4 I described a couple of ways of counting intercepts in this blog post parts:
- https://glebbahmutov.com/blog/cypress-intercept-problems/#get-number-of-times-an-intercept-was-matched
- https://glebbahmutov.com/blog/cypress-intercept-problems/#count-intercepts-again

You can find the counting spec example in our `cy.intercept` recipe at https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept
