### ISSUE TITLE
Cypess Closes

### ISSUE THREAD

**Issue by norvinino** [cypress-io/cypress#15248]
@jbr @lorennorman @jennifer-shehane @bahmutov 
The required behavior is for Cypress to automate testing.

What you're getting is that halfway through automation the cypress closes down and stops working.

For security reasons, the video showing the error cannot be sent this way. I can mail it in, as well as the test code.

The cypress version is 6.2.0

![image](https://user-images.githubusercontent.com/71896864/109308628-45c0b880-7810-11eb-9dd4-509af6cd1071.png)

**Comment by jennifer-shehane** [comment]
You can email us at support@cypress.io with a video/way to reproduce the error. 

Closing as this will be handled via support channel.
