### ISSUE TITLE
Adding typescript types in command.ts breaks Cypress tests

### ISSUE THREAD

**Issue by yann-combarnous** [cypress-io/cypress#15246]
### Current behavior
When calling a custom command written in Typescript, I am getting the error when running the test that `Record is not defined`, so the typescript types are not recognized by the compiler/WebPack, but working with Intellisense.

### Desired behavior
Typescript supported.

### Test code to reproduce

In plugins/index.ts (here the types are not causing any issue)
```js
module.exports = (on, config) => {
  on('task', {
    authTokens(refreshToken?: string) {
       return { hello: 'world' };
      }
  });
   return config;
}
```

In support/index.ts
```
import './commands';
```

In support/command.ts (here 'Record' type is causing an error, removing the type makes the test run)
```js
Cypress.Commands.add('login', () => {
   cy.task<Record<string, any>>('authTokens', '123').then((res) => {
      ...
   })
})
```

In tsconfig.json
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "target": "es5",
    "lib": ["es2015", "dom"],
    "types": ["cypress", "node"]
  },
  "include": [
    "../node_modules/cypress",
    "**/*.ts"
  ]
```

### Versions

- Cypress 6.5
- Typescript 4.1.5

**Comment by MuckT** [comment]
@yann-combarnous I get around this by doing the following in support/command.ts
```JavaScript
declare namespace Cypress {
  interface Chainable<Subject> {
    login(...args:any): any; // Just an example but you have to have the interface
  }
}

Cypress.Commands.add('login', () => {
   cy.task<Record<string, any>>('authTokens', '123').then((res) => {
      ...
   })
})
```

**Comment by yann-combarnous** [comment]
@MuckT , thx, but my issue is not with the type definition for login command, but with the generic definition for the task inside it.

For commands, I use an index.d.ts definition file, as per documentation.
