### ISSUE TITLE
Cypress w/ Shopify - Error: Content-Length can't be present with chunked encoding

### ISSUE THREAD

**Issue by paxsolutions** [cypress-io/cypress#15259]
### Current behavior
When locally testing Shopify themes whose storefronts are password-protected, Cypress tests fail almost immediately with the following error:

```
cy.visit() failed trying to load:

https://localhost:3000/?preview_theme_id=120240898208

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: Parse Error: Content-Length can't be present with chunked encoding

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
```

### Desired behavior
Cypress should load the storefront landing page normally when visiting: https://localhost:3000/?preview_theme_id=120240898208

### Test code to reproduce

I have created a repo with instructions on how to set everything up to recreate the issue.

https://github.com/paxsolutions/cypress-shopify-issue

### Versions

Cypress - v6.5.0
Chrome - v88.0.4324.192
Node - v14.4.0
macOS Big Sur

I understand there are several technologies in play here, still, any guidance is greatly appreciated.

**Comment by jennifer-shehane** [comment]
I get this error when trying to open the localhost normally, so I can't open it in the browser.

<img width="667" alt="Screen Shot 2021-03-01 at 12 54 55 PM" src="https://user-images.githubusercontent.com/1271364/109537858-63e71c80-7a8d-11eb-90be-b391c55533b6.png">

Is visiting the localhost site working for you normally?

**Comment by paxsolutions** [comment]
Hi Jennifer, thank you for getting back to me. That’s normal behavior for a local server. I go through the browser’s “Advanced” selection until it reads “proceed anyway” (or something like that). After that you should be able to see the site.

**Comment by paxsolutions** [comment]
@jennifer-shehane I tried to re-create the browser security issue but I cannot, even using incognito mode in Chrome or private browsing in Firefox. I was able to have Safari present a warning but simply accepted and then got through to the landing page.

![This_Connection_Is_Not_Private](https://user-images.githubusercontent.com/76080448/109665158-e29a9300-7b3b-11eb-91e7-6eb86f00eba5.png)

**Comment by paxsolutions** [comment]
@jennifer-shehane Here's how I got around this for local, manual testing. Thanks again.
![Privacy_error](https://user-images.githubusercontent.com/76080448/109706932-8e0d0d00-7b67-11eb-872a-d13c7244be9b.png)

**Comment by sirtawast** [comment]
https://github.com/cypress-io/cypress/issues/1185

This might be related.

I have similar issue with a certain webpack proxy / browser sync configuration, [wpack.io](https://github.com/swashata/wp-webpack-script) to be exact.

I can get the page to render by adding an additional header at NGINX, which servers the PHP upstream.

```
server {
  ...
  add_header transfer-encoding identity;
  ...
}
```

I might try using HTTPS and HTTP/2 so that `transfer-encoding: chunked` won't be there anymore, as per HTTP/2 spec.

**Comment by sirtawast** [comment]
This is a problem with the existing backend. For what it's worth, NGINX setting [chunked_transfer_encoding off;](http://nginx.org/en/docs/http/ngx_http_core_module.html#chunked_transfer_encoding) did the trick for me.

> #1185
> 
> This might be related.
> 
> I have similar issue with a certain webpack bundle / browser-sync configuration, [wpack.io](https://github.com/swashata/wp-webpack-script) to be exact.
> 
> I can get the page to render by adding an additional header at NGINX, which servers the PHP upstream.
> 
> ```
> server {
>   ...
>   add_header transfer-encoding identity;
>   ...
> }
> ```
> 
> I might try using HTTPS and HTTP/2 so that `transfer-encoding: chunked` won't be there anymore, as per HTTP/2 spec.
