### ISSUE TITLE
Cypress does not wait on all network requests to finish.

### ISSUE THREAD

**Issue by adamalston** [cypress-io/cypress#15262]
### Current behavior

Working on a React project. I started with the following snippet. I noticed that some of the requests were being cancelled early because `.click()` only waits for a specific element to reach an actionable state ([`.click()` docs](https://docs.cypress.io/api/commands/click.html#Assertions)) - instead of waiting for all of the page requests to finish.

```js
it('should show pages that have been favorited on the landing page', () => {
  cy.visit('/about');
  cy.get('.favorite').click();
  cy.visit('');
  cy.get('.favorites').children().its('length').should('eq', 1);
});
```

Whenever I run this test in the dev environment, I am getting the following errors which are due to the `xhr` requests being cancelled once the elements needed reach an actionable state.

```sh
[HPM] Error occurred while trying to proxy request /directory from localhost:3000 to <TARGET> (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /directory from localhost:3000 to <TARGET> (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /directory from localhost:3000 to <TARGET> (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /directory from localhost:3000 to <TARGET> (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /directory from localhost:3000 to <TARGET> (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

I know that these errors are from the cancelled requests because after adding a `cy.wait(2000)` command after every Cypress action, I get no errors.

```js
it('should show pages that have been favorited on the landing page', () => {
  cy.visit('/about');
  cy.wait(2000);
  cy.get('.favorite').click();
  cy.wait(2000);
  cy.visit('');
  cy.wait(2000);
  cy.get('.favorites').children().its('length').should('eq', 1);
  cy.wait(2000);
});
```

I do not think the snippet of code above is how Cypress is intended to work.

---

I wrote the following as a way to intercept all requests and make sure that they finish before moving to the next action. However, it does not seem to work as requests are still being cancelled.

```js
it('should show pages that have been favorited on the landing page', () => {
  cy.intercept({method: 'GET', url: '**'}).as('getAbout');
  cy.visit('/about');
  cy.wait('@getAbout');

  cy.intercept({method: 'GET', url: '**'}).as('favorite');
  cy.get('.favorite').click();
  cy.wait('@favorite');

  cy.intercept({method: 'GET', url: '**'}).as('getBaseUrl');
  cy.visit('');
  cy.wait('@getBaseUrl');

  cy.get('.favorites').children().its('length').should('eq', 1);
});
```

This snippet of code does not intercept all requests. Some are still cancelled once the button reaches an actionable state. In the meantime, I have gone back to the previous snippet where I have inserted a `cy.wait(2000)` command after every action.

### Desired behavior
I would like Cypress to wait on all network request to finish no matter what. I would also like to not have to specify a `.wait()` after every single page visit or button click.

### Test code to reproduce
I do not have any test code other than what I have posted above because the project I am working on is closed.

### Versions
Chrome: 88.0.x.x
macOS: 10.15.7

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. We won't be able to investigate if this is a bug without that.
