### ISSUE TITLE
Accessing iframe within iframe?

### ISSUE THREAD

**Issue by bahunov** [cypress-io/cypress#15268]
### Current behavior
How do I access iframe wihthin an iframe?

I have tried it all:
```js
const getIframeBody = () => {
    // get the iframe > document > body
    // and retry until the body element is not empty
    return cy
    .get('frame[name="login"]')
    .its('0.contentDocument.body').should('not.be.empty')
    // wraps "body" DOM element to allow
    // chaining more Cypress commands, like ".find(...)"
    // https://on.cypress.io/wrap
    .then(cy.wrap)
  }
  
 getIframeBody()
    .find('frame[name="leftbar"]')
```

Not working.. 

### Test code to reproduce
Following css:
![image](https://user-images.githubusercontent.com/22296212/109468511-1d41f400-7a86-11eb-9e07-e50596ad26a7.png)

Some elements are within the second iframe name="leftbar"

### Versions
6.5.0

**Comment by jennifer-shehane** [comment]
Your HTML is using `<frame>` elements, which are no longer supported by browsers, so I wouldn't expect Cypress to support this use case. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame

We're currently working on an API for iframe support: https://github.com/cypress-io/cypress/issues/136

With `<iframe>` you use the same commands you did for the first one, except start with a .find for the second iframe. 

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get("#iframe")
    .its('0.contentDocument.body').should('not.be.empty')
    .then(cy.wrap)
    .find('#iframe2')
    .its('0.contentDocument.body').should('not.be.empty')
    .then(cy.wrap)
    .contains('IFRAME 2')
})
```

`index.html`

```html
<html>
<body>
  <iframe id="iframe" src="iframe.html"></iframe>
</body>
</html>
```

`iframe.html`

```html
<html>
<body>
  IFRAME 1
  <iframe id="iframe2" src="iframe2.html"></iframe>
</body>
</html>
```

`iframe2.html`

```html
<html>
<body>
  IFRAME 2
</body>
</html>
```

<img width="968" alt="Screen Shot 2021-03-01 at 12 43 14 PM" src="https://user-images.githubusercontent.com/1271364/109536431-b6bfd480-7a8b-11eb-8368-a1d5e914f875.png">
