### ISSUE TITLE
Missing gconf2 dependency for Ubuntu 17.04: libgconf-2.so.4 error

### ISSUE THREAD

**Issue by kgish** [cypress-io/cypress#1526]
Error:
```
Cypress: error while loading shared libraries: libgconf-2.so.4: cannot open shared \
object file: No such file or directory
```

Ubuntu 17.04 doesn't ship anymore by default gconf2 (it uses dconf), so on a fresh Ubuntu 17.04 install you get this error after starting cypress

You'll need to install the missing library:
```
sudo apt install libgconf-2-4
```

**Comment by ondrek** [comment]
Getting the same :(

**Comment by Bkucera** [comment]
@ondrek do you have chrome installed when you got this error?

**Comment by dashaxiong** [comment]
After running the command above to install `libgconf-2-4`, Cypress runs but presents the warning: 
   
    GLib-GIO-CRITICAL **: timestamp : g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION    
    (connection)' failed

Then it proceeds to run the tests successfully. I have tried with and without Chrome installed, it doesn't seem to impact on it.

**OS**: Lubuntu 18.04
**Cypress version**: 3.1.0 (installed with NPM)

**Comment by oupala** [comment]
Same issue with debian stretch.

**Comment by flotwig** [comment]
@oupala You can install it by installing the `libgconf-2-4` package: https://packages.debian.org/search?mode=exactfilename&suite=stretch&section=all&arch=any&searchon=contents&keywords=libgconf-2.so.4

To fix this issue, perhaps we should detect if the user has missing dependencies in the CLI, and then warn them? Something like:

```
To run Cypress, please install missing dependencies on your system:

sudo apt install libgconf-2-4 libasound2...
```

...because right now, it's not very well-documented.

**Comment by oupala** [comment]
It is not documented and the [opposite is explicitly documented](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Direct-download):

> Just manually unzip and double click. Cypress will run without needing to install any dependencies.

And by the way, your workaround is working (installing the required library `libgconf-2-4`.

**Comment by flotwig** [comment]
Yeah, that is probably the case for Windows and Mac, but not so for Linux.

Linux dependencies are documented in Continuous Integration for some reason: https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies

**Comment by oupala** [comment]
So I believe linux as a desktop is not documented.

**Comment by jennifer-shehane** [comment]
Please check this workaround for Travis runs: https://github.com/cypress-io/cypress/issues/4069#issuecomment-488315675

**Comment by TDAK1509** [comment]
> @oupala You can install it by installing the `libgconf-2-4` package: https://packages.debian.org/search?mode=exactfilename&suite=stretch&section=all&arch=any&searchon=contents&keywords=libgconf-2.so.4
> 
> To fix this issue, perhaps we should detect if the user has missing dependencies in the CLI, and then warn them? Something like:
> 
> ```
> To run Cypress, please install missing dependencies on your system:
> 
> sudo apt install libgconf-2-4 libasound2...
> ```
> 
> ...because right now, it's not very well-documented.

You saved my ass!

**Comment by jennifer-shehane** [comment]
This is listed as a dependency in our docs, so this issue will be closed as resolved. https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup

**Comment by jennifer-shehane** [comment]
I've opened a PR in the docs to also add the dependency requirements to the install doc, since I think this is the core of the issue https://github.com/cypress-io/cypress-documentation/pull/2939
