### ISSUE TITLE
Warning: .then() only accepts functions but was passed: [object Undefined] when running Cypress in Docker

### ISSUE THREAD

**Issue by blomqma** [cypress-io/cypress#15281]
### Current behavior

So when running Cypress inside a Docker container with `node:15.10.0-buster-slim` image and all the required runtime dependencies from `cypress/base` Docker image, the terminal will be full of the following output on literally every test case.

![Screenshot 2021-03-02 at 10 28 29](https://user-images.githubusercontent.com/35772402/109620020-17a9e400-7b42-11eb-89c5-ca8ef6bb6dfb.png)

### Desired behavior

Obviously, no such output should exist.

### Test code to reproduce

I doubt this has nothing to do with the syntax of my test cases themselves, the error reproduces on every test with even empty contents so anything can be used - I think it's related to the node version somehow.

### Versions

Cypress: 6.5.0
Docker image: node:15.10.0-buster-slim

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? This is likely dependent on the project you are running - can you provide a repo? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
I couldn't recreate this running Node 15.10.0 with a sample project.

**Comment by pmerwin** [comment]
I see this output in our github actions running on Ubuntu: latest: with node 12


    (node:2795) Warning: .then() only accepts functions but was passed: [object Undefined]
(node:2795) Warning: .then() only accepts functions but was passed: [object Undefined]

(node:2262) Warning: a promise was created in a handler at internal/timers.js:456:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/home/runner/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:225:13)

**Comment by pmerwin** [comment]
@jennifer-shehane I believe to reproduce you can create a github workflow with cypress-io/github-action@v2

**Comment by kkaarreell** [comment]
I am seeing similar problem on RHEL container. The issue start appearing after a cypress update. The traceback looks as follows
```
(node:8997) Warning: .then() only accepts functions but was passed: [object Undefined]
    at Object.wrapChildPromise (/home/travis/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/util.js:42:8)
    at Object.wrap (/home/travis/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/child/task.js:53:8)
    at execute (/home/travis/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:127:19)
    at EventEmitter.<anonymous> (/home/travis/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:202:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/home/travis/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by kkaarreell** [comment]
Not an expert but to me it seems that `wrapChildPromise` is not getting the `cb` parameter.
```
  wrapChildPromise (ipc, invoke, ids, args = [], cb) {
    return Promise.try(() => {
      return invoke(ids.eventId, args)
    }).then(cb)
```
```
$ pwd
/home/testuser/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server
$ grep -R wrapChildPromise
lib/plugins/util.js:  wrapChildPromise (ipc, invoke, ids, args = [], cb) {
lib/plugins/child/browser_launch.js:    util.wrapChildPromise(ipc, invoke, ids, args)
lib/plugins/child/dev-server.js:  util.wrapChildPromise(ipc, invoke, ids, [options])
lib/plugins/child/preprocessor.js:  util.wrapChildPromise(ipc, invoke, ids, [childFile])
lib/plugins/child/run_plugins.js:  const wrapChildPromise = () => {
lib/plugins/child/run_plugins.js:    util.wrapChildPromise(ipc, invoke, ids, args)
lib/plugins/child/run_plugins.js:      return wrapChildPromise()
lib/plugins/child/task.js:  util.wrapChildPromise(ipc, invoke, ids)
lib/plugins/child/task.js:  util.wrapChildPromise(ipc, invoke, ids)
lib/plugins/child/task.js:  util.wrapChildPromise(ipc, invoke, ids, [arg])
```

**Comment by jweingarten** [comment]
Same problem here ... since 6.5.0 upgrade.

**Comment by kkaarreell** [comment]
Hi @jennifer-shehane , may I ask for a review? I believe the root cause is clear now and the fix should be also simple (e.g. define a default callback function for the `cb` parameter or just check it is not `undefined` before calling it).

**Comment by joelgrimberg** [comment]
same issue here, without running in Docker.. I will try to setup an example-repo

**Comment by jahusa02** [comment]
I have exactly the same problem with the cypress/base:10 image. Also my tests wont fail.
