### ISSUE TITLE
Need a way to pass flags settings to chrome launch args

### ISSUE THREAD

**Issue by pmerwin** [cypress-io/cypress#15291]
Hey my friends, I am trying to pass a flag setting to chrome on start like this:

in my plugins/index:

```js
module.exports = (on, config) => {
    on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chromium') {
            // Mac/Linux
            launchOptions.args.push('--disable-features=SameSiteByDefaultCookies');
            launchOptions.args.push('--reduce-security-for-testing');
        }
        console.log('launch options', launchOptions);
        return launchOptions;
    });
    require('cypress-log-to-output').install(on);
    require('cypress-fail-fast/plugin')(on, config);
    return config;
};
```

But those are not making it into the flag settings when I look at chrome://version command line args:

On a cypress started session, flag switches section has no options:

```
--flag-switches-begin --flag-switches-end about:blank
```

When I set it by hand in chrome:// flags:

```
--flag-switches-begin --disable-features=SameSiteByDefaultCookies --flag-switches-end
```

Looks we need a `launchOptions.args.flagSettings` or something? Any ideas on how to do this with cypress?

chrome://flags/#same-site-by-default-cookies
chrome://flags/#cookies-without-same-site-must-be-secure

We serve our site as http in github workflows to kick off browser tests, looks like chrome is now calling a http to https route a cross site violation, which breaks our automation.

https://support.siteimprove.com/hc/en-gb/articles/360007364778-Turning-off-Google-Chrome-SameSite-Cookie-Enforcement

**Comment by pmerwin** [comment]
Hmm, so as a test I tried passing --enable-experimental-cookie-features and that is not making it to the borwser via cypress either ? :

```
module.exports = (on, config) => {
    on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chromium') {
            launchOptions.args.push('--enable-experimental-cookie-features');
        }
        console.log('launch options', launchOptions);
        return launchOptions;
    });
    require('cypress-log-to-output').install(on);
    require('cypress-fail-fast/plugin')(on, config);
    return config;
};
```

```
chrome://version chrome are missing "--enable-experimental-cookie-features" ?

/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --test-type --ignore-certificate-errors --start-maximized --silent-debugger-extension-api --no-default-browser-check --no-first-run --noerrdialogs --enable-fixed-layout --disable-popup-blocking --disable-password-generation --disable-single-click-autofill --disable-prompt-on-repos --disable-background-timer-throttling --disable-renderer-backgrounding --disable-renderer-throttling --disable-backgrounding-occluded-windows --disable-restore-session-state --disable-new-profile-management --disable-new-avatar-menu --allow-insecure-localhost --reduce-security-for-testing --enable-automation --disable-print-preview --disable-device-discovery-notifications --autoplay-policy=no-user-gesture-required --disable-site-isolation-trials --metrics-recording-only --disable-prompt-on-repost --disable-hang-monitor --disable-sync --disable-web-resources --safebrowsing-disable-download-protection --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --disable-ipc-flooding-protection --disable-backgrounding-occluded-window --disable-breakpad --password-store=basic --use-mock-keychain --disable-dev-shm-usage --proxy-server=http://localhost:64328 --disable-web-security --allow-running-insecure-content --proxy-bypass-list=<-loopback> --remote-debugging-port=64332 --remote-debugging-address=127.0.0.1 --load-extension=/Users/pmerwin/Library/Application Support/Cypress/cy/production/browsers/chrome-stable/run-64448/CypressExtension,/Users/pmerwin/Library/Caches/Cypress/6.5.0/Cypress.app/Contents/Resources/app/packages/extension/theme --user-data-dir=/Users/pmerwin/Library/Application Support/Cypress/cy/production/browsers/chrome-stable/run-64448 --disk-cache-dir=/Users/pmerwin/Library/Application Support/Cypress/cy/production/browsers/chrome-stable/run-64448/CypressCache --flag-switches-begin --flag-switches-end about:blank
``

**Comment by jennifer-shehane** [comment]
When I visit chrome://version within Cypress, it does take the new flags passed with the code above, as well as having *several* other flags that Cypress adds by default. I did remove the plugins from the code sample, although I don't think that would be related.

<img width="643" alt="Screen Shot 2021-03-02 at 4 44 13 PM" src="https://user-images.githubusercontent.com/1271364/109719449-ac2e3980-7b76-11eb-85f3-a6c4807d0b58.png">

**Comment by pmerwin** [comment]
@jennifer-shehane I think this guy may be suspect, I am trying by removing it now:

require('cypress-log-to-output').install(on);

**Comment by pmerwin** [comment]
Yeah I am still not seeing the flag-switches:

```
Chrome/88.0.4324.192 Safari/537.36
--
<img width="464" alt="vsersion" src="https://user-images.githubusercontent.com/26633165/109724106-e215f280-7b63-11eb-9515-9b017e4311e4.png">


using:

```
/**
 * @type {Cypress.PluginConfig}
 */

module.exports = (on, config) => {
    on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chromium') {
            // Mac/Linux
            launchOptions.args.push('--disable-features=SameSiteByDefaultCookies');
            // launchOptions.args.push('--enable-experimental-cookie-features');
        }
        console.log('launch options', launchOptions);
        return launchOptions;
    });
    require('cypress-terminal-report/src/installLogsPrinter')(on);
    require('cypress-fail-fast/plugin')(on, config);
    return config;
};
```
@jennifer-shehane can you try with the plugins and see?  I appreciate it!

**Comment by pmerwin** [comment]
Yeah even with no plugins I do not see  flag-switches:  --flag-switches-begin --flag-switches-end about:blank

using: 

```
module.exports = (on, config) => {
    on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chromium') {
            // Mac/Linux
            launchOptions.args.push('--disable-features=SameSiteByDefaultCookies');
            // launchOptions.args.push('--enable-experimental-cookie-features');
        }
        console.log('launch options', launchOptions);
        return launchOptions;
    });
    // require('cypress-terminal-report/src/installLogsPrinter')(on);
    // require('cypress-fail-fast/plugin')(on, config);
    // return config;
};
```

**Comment by pmerwin** [comment]
@jennifer-shehane The only way I can get flag-switches to populate is to use the UI at chrome://flags, maybe that is what you did before running the test inadvertently??

**Comment by azmath606961** [comment]
@[jennifer-shehane](https://github.com/jennifer-shehane) has Chrome v88 where as @pmerwin has v89. Could that be a difference to note? I am on Chrome v99 and coming across "Blocked a frame with origin  from accessing a cross-origin frame." and could see my flags are not applied as well.
<img width="739" alt="Screenshot 2022-03-16 at 17 05 07" src="https://user-images.githubusercontent.com/18189600/158646973-6b56ec88-f4e0-4c72-ae2f-4b06397e1a62.png">
<img width="739" alt="Screenshot 2022-03-16 at 17 06 40" src="https://user-images.githubusercontent.com/18189600/158647322-b08a259c-ec14-4e4d-8490-08c671bee96a.png">

**Comment by yubischiess** [comment]
Did anyone ever figure this out? Having the same issue trying to disable experimental features.
