### ISSUE TITLE
have cypress host test files

### ISSUE THREAD

**Issue by BasieP** [cypress-io/cypress#1529]
Hello there,

I want to access some test files and they have to be hosted.
Now i know cypress uses fixtures, but they give me the file as base64 orso while i want to use them as a download.

My code so far:
```javascript
it('Link a file', function () {
	cy.get('input.link').then(function (inputs) {
		inputs[0].value = 'http://localhost:8888/test.xlsx';
		inputs.siblings('button').click()
		//check stuff here
	})
})
```
The problem is that now i host the file along with my application, but i don't want that. I want cypress to host the file as a 'test dependency'

I've been googling all day, but all i get is some stuff about fixtures...
i've tried figuring out cypress internals, and noticed links like this:
http://localhost:8888/__cypress/tests?p=cypress\fixtures\test.xlsx
(where i put my file)
But i got it back surrounded with some javascript errors..., not as a file download

What am i missing?

**Comment by Bkucera** [comment]
@BasieP  You can recreate this exact functionality by having cypress return a `fixture` using stubbed requests via `cy.route`
Docs here: https://docs.cypress.io/api/commands/route.html#Fixtures
If this isn't working for you feel free to open this issue back up with a minimal repro

**Comment by BasieP** [comment]
Well, i found that link, but it's not gonne help me.

These kind of issues need some working examples, cause so far i only see 3 line code snippets that don't work in a real situation.

As my problem continues:

```
cy.server()
cy.route('**/fixtures/test.xlsx', 'fixture:test.xlsx').as('excelfile')
cy.get('input.link').then(function (inputs) {
	inputs[0].value = 'http://localhost:8888/fixtures/test.xlsx';  //<-- crash
	cy.log('this is not logged')
	inputs.siblings('button').click()
})
```

The error message is: 
InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

Which is weird. all i want it to do is paste a link in the input field.
I'm guessing it then tries to retreive the fixture.. although i didn't do any actions yet. The line that pushes the button is where i expected it to do stuff. That executes code that downloads the file and processes it.

**Comment by Bkucera** [comment]
@BasieP I'll take a look at it, thanks for giving us more information!

**Comment by Bkucera** [comment]
In order to understand the problem I'll need to reproduce this on our end. Do you have a reproducible example or repo?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
