### ISSUE TITLE
Improve `cy.exec()` console output on errors

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#153]
When the `cy.exec()` process exits with a non-zero code, the stdout and stderr are truncated for the sake of the UI ouput, but that also results in them being truncated when the user clicks the error to view it in the console. The console output should include the full stdout and stderr.

**Comment by brian-mann** [comment]
Fixed in [`0.16.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0162-06112016).
