### ISSUE TITLE
Run tests in parallel across projects

### ISSUE THREAD

**Issue by alaboudi** [cypress-io/cypress#15308]
### What would you like?

I think it not currently possible to run Cypress in parallel across multiple projects. If there is a way to run multiple projects in one go in parallel, that would be great. Maybe something like this `cypress run -P ./path/to/my/first/project, ./path/to/my/second/project -p` (just a suggestion)

### Why is this needed?

Our application uses a monorepo. We trigger e2e cypress project based on whether or not a change affects the execution of a given project via a dependency graph. Currently, we can only run projects 1 at a time.

**Comment by bahmutov** [comment]
Think of this differently - no need to "join" all projects and all their specs to run in parallel. Just run each project in parallel by itself! Let's say you have 5 projects

```
repo/
  projects/
    p1/
      spec-a.js
    p2/
    p3/
    p4/
      spec-foo.js
      spec-bar.js
    p5/
```

And during the test execution, you have 2 machines and the files modified by the commit or pull request touch p1 and p4

Your commands are

```
cypress run --record --parallel --project projects/p1
cypress run --record --parallel --project projects/p4
```

So what happens?

The first machine starts running p1, grabs the `spec-a.js` and starts running the tests. Then the second machine starts running p1, but Cypress Dashboard says "there are no more specs for p1, you are done".

So while the first machine is running p1, the second machine ... goes onto the next command starts running p4. So it grabs `spec-foo.js`. Machine 1 finishes with `spec-a`, which finishes the p1 and moves on. It joins the p4 run, gets `spec-bar.js`

Eventually, both machines finish with p4 and the entire run is done.

This is pretty much the same as "merging" all files together and splitting spec-a, spec-foo, spec-bar across 2 machines. Would not make any difference!

PS: for more examples read https://glebbahmutov.com/blog/test-monorepo-apps/

**Comment by alaboudi** [comment]
That makes sense. Thank you very much @bahmutov 👍
