### ISSUE TITLE
Cypress is intercepting API calls inconsistently. Ideally a call should be intercepted 22 times but it is getting intercepted by cypress 42 times.

### ISSUE THREAD

**Issue by Ppkd2021** [cypress-io/cypress#15317]
### Current behavior
There is an API which is getting called in frontend multiple time(22  times) when we are trying to intercept each call for that respective api by cypress then it is intercepting inconsistently, sometimes 42 or 44 times.

### Desired behavior
It should intercept that API call 22 times.
### Test code to reproduce
```js
describe('cypress api intercept bug', () => {
  it('ListInsightViewMetricsByInsightViewId api', () => {

	let i =0
	cy.intercept(`POST`, `RouteURL`, req => {
		
        if (req.body.query.includes(`ListInsightViewMetricsByInsightViewId`)) {	
          console.log(req.body);
		  console.log(`request found`,i);
              i++ 
          //req.alias = `${query}-${i}`;
        }
      });
    cy.visit('Application URL');
	
    cy
		.get(`[type="submit"]`,{timeout:30000})
		.as(`BtnSubmit`)
		.should(`be.disabled`)
		.get(`[data-placeholder="Email"]`,{timeout:30000})
		.type(`Email`)
		.get(`[data-placeholder="Password"]`)
		.type(`Password`)
		.get(`@BtnSubmit`)
		.should(`be.enabled`)
		.click()
	
		//cy.wait(`@ListCampaignGroups`).then(req=>console.log(req))
    .get(`.brand-list-wrapper > :nth-child(1)`,{timeout:60000})
	
    .click()
	
    .get(`.link-btn`)
    .click()
	cy.wait(`@ListInsightViewMetricsByInsightViewId`,{timeout:80000}).then(req=>console.log(req))
  })
})  
```

**Comment by Ppkd2021** [comment]
Application intercepting 22 times
![image (7)](https://user-images.githubusercontent.com/59794856/109918062-6be8cb80-7cdc-11eb-9877-efabd98cac4f.png)

Cypress intercepting 43 times
![image (4)](https://user-images.githubusercontent.com/59794856/109918038-612e3680-7cdc-11eb-90e0-df4ad341ca02.png)

![image (5)](https://user-images.githubusercontent.com/59794856/109918010-4f4c9380-7cdc-11eb-9c51-b1e3183e301a.png)

**Comment by jennifer-shehane** [comment]
Looking further at this, it appears that the graphql calls are doubled regardless of the `cy.intercept()` definition, so it may not be related to intercept and be related to something else.

**Comment by bahmutov** [comment]
## Reproduction

The same problem in v6.5.0 v6.6.0 and branch `7.0-release`

https://github.com/cypress-io/cypress-example-recipes/tree/triple-intercept folder examples/server-communication__wait-for-api

- install root dependencies with `npm install`
- in the folder itself `npm run dev`

The following test there shows double or sometimes triple intercept execution for a single `fetch` from the application

```js
it('fails because the API is not ready', () => {
  cy.visit('/')
  cy.intercept({
    pathname: '/greeting',
  },
  {
    forceNetworkError: true,
  }).as('greeting')

  cy.get('#get-api-response').click()
})

it('fails because the API is not ready (with log)', () => {
  cy.visit('/')
  cy.intercept({
    pathname: '/greeting',
  },
  (req) => {
    console.log('in the greeting intercept')
    console.log(JSON.stringify(req))
    req.reply({ forceNetworkError: true })
  })

  cy.get('#get-api-response').click()
})
```

## Images

<img width="916" alt="Screen Shot 2021-03-05 at 1 08 52 PM" src="https://user-images.githubusercontent.com/2212006/110159031-26013580-7db8-11eb-96a3-c4745d2a51fa.png">

<img width="1274" alt="Screen Shot 2021-03-05 at 1 24 23 PM" src="https://user-images.githubusercontent.com/2212006/110159049-2ac5e980-7db8-11eb-9aab-1c3fdb99555e.png">

**Comment by flotwig** [comment]
@bahmutov I don't think this is related - those requests are probably actually being sent. I'm not sure if the Network tab will show it, but Chrome will re-send a request that fails due to network error a few times, so that is probably why you are seeing this behavior.

Check out the `0_network_error_handling_spec` e2e test if you're curious, Chrome's behavior w.r.t retrying on network errors is tested in great detail there.

**Comment by vrknetha** [comment]
@jennifer-shehane Thank you for having a look at it. Please let us know if you need anything else which helps fixing this issue.
