### ISSUE TITLE
issue with cy.wait()

### ISSUE THREAD

**Issue by muralimohan3628** [cypress-io/cypress#15319]
I just wanted to know that can cypress run a test case without using cy.wait() and can cypress wait till the web element is found/loaded while execution. If possible please share me with some knowledge of how its done.

Note: Help me out with this, I don’t to use this by increasing default command timeout or exec timeout.

**Comment by bahmutov** [comment]
Literally every example in our documentation shows how to do this. For example the https://on.cypress.io/get command retries until the element exists

```js
cy.get('input') // will retry up to four seconds to find the <input> element
```

Even better is to combine a command with an assertion. For example to retry until the element is visible you could do

```js
cy.get('#my-div').should('be.visible')
```

See more examples in the `cy.get` page https://on.cypress.io/get or reading http://on.cypress.io/retry-ability
