### ISSUE TITLE
Page `<title>` in `<head>` is overridden by Cypress

### ISSUE THREAD

**Issue by CoryDanielson** [cypress-io/cypress#15326]
### Current behavior
The `<title>` content is replaced by the directory that the tests live. This makes the [cy.title()](https://docs.cypress.io/api/commands/title.html) command useless.

### Desired behavior
The `<title>` should remain unchanged during a test run.

### Test code to reproduce
Run a test that visits a UI with a set `<title>Hello World</title>` and see that it will be replaced.

### Versions
5.6.0

**Comment by bahmutov** [comment]
Can you
1. try the latest Cypress version 6.6.0
2. create a reproducible example by clocking something like https://github.com/cypress-io/cypress-test-tiny or providing your own repo?

**Comment by CoryDanielson** [comment]
I'll try upgrading soon and see if I still see the issue afterwards. I had this test written when using v5.0, and the test started to fail after upgrading to 5.6

**Comment by CoryDanielson** [comment]
Closing - I was wrong. Got confused by the iframe and repetitive test code.
