### ISSUE TITLE
Desktop gui crashes when showing an environment object

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#15325]
Cypress v6.6.0

While investigating https://github.com/cypress-io/cypress/issues/15323 I stumbled upon a bug in desktop gui

In https://github.com/bahmutov/cypress-env-from-cli-example

```
$ CYPRESS_person='{ "name": { "first": "Joe", "last": "Smith" }, "age": 18 }' npx cypress open
```
plugins file has the config.env { person: { name: { first: 'Joe', last: 'Smith' }, age: 18 } }

So the environment will have parsed `person` value, but when I click on it from the configuration tab, the app goes blank

![person](https://user-images.githubusercontent.com/2212006/109999147-e9620b00-7cdf-11eb-8508-03b59851aba6.gif)

**Comment by jennifer-shehane** [comment]
Still an issue in 7.2.0.

```js
// plugins/index.js
module.exports = (on, config) => {
  config.env = { person: { name: { first: 'Joe', last: 'Smith' }, age: 16 } }
  return config
}
```

```
CYPRESS_person='{ "name": { "first": "Joe", "last": "Smith" }, "age": 18 }' npx cypress open
```
