### ISSUE TITLE
(node:30) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by Jenzz10** [cypress-io/cypress#1532]
Hi, 

We are working with cypress for about a week now, and we're very impressed with the initial results. 
Since today all our builds are failing and hanging on the following error. I don't find a lot of information about in on the web in the cypress context

(node:30) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit

We are running cypress in docker, with the provided docker image. When starting cypress in the local dashboard runner and running them 1 by 1 everything works fine. When running all the tests in docker we get the above error and everything hangs. 

Anyone come across this? 

Thx!

**Comment by Bkucera** [comment]
#1305

**Comment by Nawazsherif** [comment]
Could you explain this more. Where should we add this?
