### ISSUE TITLE
When 'modifyObstructiveCode' is utilized, display banner message

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1533]
Cypress modifies some applications code to prevent them from framebusting outside of Cypress. 

This is not very obvious that this is happening for users though.

We should display a banner message within the test runner informing the user that their application code has been modified. And a link to read more about it and how to turn off modifyObstructiveCode.

**Comment by brian-mann** [comment]
Also add response headers like `x-cypress-obstructive-code-removed: true` or something like that to indicate that this took place on the response.

Or potentially add an inline JS comment too at the point of the problem.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close this issue.
