### ISSUE TITLE
cy.writeFile type does not have 4 argument version

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#15353]
Cypress v6.6.0
`cy.writeFile` type signature does not allow 4 options, which works at runtime

<img width="840" alt="Screen Shot 2021-03-06 at 9 04 26 AM" src="https://user-images.githubusercontent.com/2212006/110209523-11c24480-7e5b-11eb-96ee-8b8556ad0d2e.png">

**Comment by jennifer-shehane** [comment]
Yes, this is misdocumented https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/files.js#L82:L82

**Comment by jennifer-shehane** [comment]
What happens if you pass different encoding in encoding arg than in options arg. I think this may be why this wasn't documented.

**Comment by sainthkh** [comment]
@jennifer-shehane  According to [the lodash doc](https://lodash.com/docs/4.17.15#defaults) and the `cy.writeFile` code below,

https://github.com/cypress-io/cypress/blob/35be2aea2ad1611d4b09fbf3a172a2473ca952a3/packages/driver/src/cy/commands/files.js#L90-L94

`encoding` in `options` takes precedence.
