### ISSUE TITLE
Cypress headers are different from real application, authorization is absent

### ISSUE THREAD

**Issue by Nervniyak** [cypress-io/cypress#15355]
In our Angular application we are using PouchDB synced with CouchDB to provide offline/online storage solution with replication. And it works awesome. The problem is that it doesn't work with Cypress, because request's headers are different when running tests.

(PouchDB is web indexedDB running on client and CouchDB is a similar document-based DB running on server)

In our code we provide basic Auth to the PouchDB setup that backend CouchDB expects, but as you can see on the screenshot below it's gone, the left request was done while using application normally running on localhost while the right one while running Cypress

![image](https://user-images.githubusercontent.com/34353798/110224052-6b715000-7ee9-11eb-98ef-12b0dff4501c.png)
A bunch of headers is different, but most importantly there's no `authorization` at all...

The HTTP request is produced by PouchDB sync using `fetch()`

![image](https://user-images.githubusercontent.com/34353798/110224269-0e769980-7eeb-11eb-9df8-ab8b80f6146d.png)

There result of the `fetch()` request is also different: on the left is normal app and on the right in Cypress:

![image](https://user-images.githubusercontent.com/34353798/110223983-d8381a80-7ee8-11eb-8a9b-f37c135ee57a.png)

**What happens to the authorization header in Cypress? Is it a bug?**

It is also worth mentioning that we have separate heartbeat check towards CouchDB using regular HttpClient provided by Angular and this one preserves Auth headers during Cypress testing.

cypress.json
```json
{
  "baseUrl": "http://localhost:4206",
  "video": false,
  "integrationFolder": "tests/e2e",
  "fixturesFolder": "tests/e2e/fixtures",
  "supportFile": "tests/utils/support.js",
  "pluginsFile": "tests/utils/plugins.js",
  "testFiles": "**/*.{feature,features}",
  "experimentalFetchPolyfill": true,
  "experimentalNetworkStubbing": true,
  "defaultCommandTimeout": 30000,
  "viewportWidth": 1248,
  "viewportHeight": 660,
  "env": {
    "TEST": "test"
  },
  "chromeWebSecurity": false
}
```

### Versions

```
    "@types/cypress-cucumber-preprocessor": "^4.0.0",
    "cypress": "^6.5.0",
    "cypress-cucumber-preprocessor": "^4.0.1",
    "pouchdb-browser": "^7.2.2",
```

**Comment by jennifer-shehane** [comment]
Do you have an example of the tests you're writing in Cypress?

**Comment by Never7Dice** [comment]
Test is basically empty, application visits UI gets redirected to login page of identity server, log ins, gets redirected back to UI and tests is ended, application is running and it should have DB sync working at this stage already, but sync requests fail because of headers. 

```
Feature: Create new App

  The whole workflow of creating new Application 

  Background:
    Given 'administrator' is logged to Server

  Scenario: Save App Detail page
```

```
Given('{string} is logged to Server', (user) => {
  cy.visit('/ui');
  LogInPage.login(user, PASSWORD);
})
```

```
  static loginField = `input[id='EmailOrUsername']`;
  static passwordField = `input[id='Password']`;
  static submitButton = `button[name='action']`;

  static fillLogin(value: string) {
    const field = cy.get(this.loginField);
    field.clear();
    field.type(value);

    return this;
  }

  static fillPassword(value: string) {
    const field = cy.get(this.passwordField);
    field.clear();
    field.type(value);

    return this;
  }

  static submit() {
    const button = cy.get(this.submitButton);
    button.click();
  }

  static login(login: string, password: string) {
    this.fillLogin(login);
    this.fillPassword(password)
    this.submit();
  }
```

**Comment by diegosierra12** [comment]
This error is similar to the one reported here #14924 
But in the example we only show that it does not bring the header "origin"

**Comment by diegosierra12** [comment]
Performing a review of the list of incidents, I found these that are also related to the same topic: #14791, #9221.
Right now I have version 6.7.1 and this behavior keeps happening.

**Comment by Jercik** [comment]
I can confirm the issue. I think that Cypresses `fetch()` polyfill is not working right when headers provided to the `fetch()` function are an instance of the `Headers` class. When I provide headers as a plain object, headers are set correctly.

This doesn't work:
```TypeScript
const headers = new Headers();
headers.set("Foo", "Bar");
const response = await fetch(endpoint, { ...init, headers });
```

This is working fine:
```TypeScript
const headers = {"Foo" : "Bar"};
const response = await fetch(endpoint, { ...init, headers });
```

**Comment by Jercik** [comment]
The underlying issue is that Cypress should not use `unfetch` polyfill because it is not fully compatible with Fetch API. It is clearly stated on the project page: https://github.com/developit/unfetch. Specifically `Headers` class is not supported and it looks like it will never be: developit/unfetch#124

**Comment by Never7Dice** [comment]
@jennifer-shehane any news on this? A lot of information was provided above.

**Comment by Never7Dice** [comment]
Still a thing in 8.4.0. Setting authorization header on existing headers of fetch doesn't work. Header is absent in Cypress.

**Comment by Never7Dice** [comment]
I had this properties in my cypress.json
```
  "experimentalFetchPolyfill": true,
  "experimentalNetworkStubbing": true,
```

Removing them seems to fix the issue.

(they were present in the configuration posted in original question, surprised nobody mentioned it)

**Comment by diegosierra12** [comment]
I don't have these properties in my cypress.json, but I still have the same problem

**Comment by Hangochung81** [comment]
I have the same issue. Seem it happen when application uses SSE. Some more info to fix it? Thank a lot
