### ISSUE TITLE
Reloading Cypress after unexpected error results in crash

### ISSUE THREAD

**Issue by JonahKK** [cypress-io/cypress#15360]
### Current behavior

When Cypress Runner (launched with `cypress open`) encounters an error it allows for reloading (`Try Again` option). 
![image](https://user-images.githubusercontent.com/23238398/110332562-c35ea280-8020-11eb-870d-eaff31762497.png)
When the `Try Again` button is clicked then the Cypress crashes and following errors are displayed:
![image](https://user-images.githubusercontent.com/23238398/110332817-1df7fe80-8021-11eb-8e70-b222b128f179.png)

### Desired behavior

Reload should not end with crash.

### Test code to reproduce

The easiest way to reproduce is:

1. Open Cypress with `cypress open`.
2. Change `cypress.json` that is no longer valid.
3. Unexpected error screen should be displayed.

### Versions
6.5.0

**Comment by jennifer-shehane** [comment]
Yeah, this is easily reproducible. This was introduced in 6.5.0.

<img width="1349" alt="Screen Shot 2021-03-16 at 6 54 24 PM" src="https://user-images.githubusercontent.com/1271364/111390415-1374df00-8689-11eb-8020-1380f630831d.png">


`cypress.json`

```json
{,}
```

1. Run `cypress open`
2. Tap 'Try again' in GUI.

Looks like this error is constructed and thrown by us ourselves. https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/class-helpers.ts#L14:L14

This error was introduced in https://github.com/cypress-io/cypress/pull/14479

**Comment by jennifer-shehane** [comment]
In 8.2.0, this no longer crashes but causes the UI to spin forever. 

<img width="910" alt="Screen Shot 2021-08-09 at 8 17 47 AM" src="https://user-images.githubusercontent.com/1271364/128712455-2dce4a90-03b1-4dab-9f79-797bd4902a34.png">

**Comment by jennifer-shehane** [comment]
This is no longer an issue. Tried in Cypress 8.6.0.
