### ISSUE TITLE
Route() command: the method parameter is case sensitive, lower case and not documented.

### ISSUE THREAD

**Issue by bbsimonbb** [cypress-io/cypress#1536]
## Current behavior:

When using route(), method is case sensitive and must be lower case. If, naively, you use the customary upper case for http methods, there is no error or warning, but your route will never match.

### Desired behavior:
Primal desire : method not case sensitive.
Secondal desire : method in upper case.
Tertial desire : a console warning if ever route() is called with an invalid method
Vague desire : more guidance in the documentation.

### How to reproduce:
[see this stack question](https://stackoverflow.com/q/49633554/1585345)
create a route to match a POST, as below.

#### Test code:

```js
route('POST','https://mysuperapp.com').as('willNeverMatch')
```

### Additional Info (images, stack traces, etc)
![cypress-wait](https://user-images.githubusercontent.com/11962703/38294376-ebdd2140-37ea-11e8-94c6-3a0f5365d05a.png) 

- Operating System: Windows 10
- Cypress Version: 2.1.0
- Browser Version: 67

**Comment by jennifer-shehane** [comment]
This issue has been resolved. The code below works. I believe this was fixed as part of this change https://github.com/cypress-io/cypress/pull/3555

```js
it('cy.route() - route responses to matching requests', () => {
    cy.visit('https://example.cypress.io/commands/network-requests')

    let message = 'whoa, this comment does not exist'

    cy.server()

    // Listen to GET to comments/1
    cy.route('get', 'comments/*').as('getComment')
    cy.get('.network-btn').click()
    cy.wait('@getComment').its('status').should('eq', 200)

    cy.route('pOsT', '/comments').as('postComment')
    cy.get('.network-post').click()
    cy.wait('@postComment')

    cy.route({
      method: 'puT',
      url: 'comments/*',
      status: 404,
      response: { error: message },
      delay: 500,
    }).as('putComment')
    cy.get('.network-put').click()
    cy.wait('@putComment')
    cy.get('.network-put-comment').should('contain', message)
  })
```

**Comment by lonewarrior556** [comment]
This is still an issue in 3.7.0
