### ISSUE TITLE
Cypress runner gives me a 404 when using Firefox browser

### ISSUE THREAD

**Issue by onimougwo** [cypress-io/cypress#15377]
### Current behavior
When I attempt to run a test with Cypress runner in Firefox I'm getting a 404 and can't run any test at all.
I can run my tests fine in Cypress runner with Chrome, Electron and Edge.

I contacted my company IT department but they don't think the issue is on our end, especially since it works in Chrome and Edge 

Same thing happens headless.

### Desired behavior
Tests should run in Firefox

### Test code to reproduce
Any test.

The application under test is our component library hosted in Storybook.

### Versions

Cypress v 6.5.0
Firefox 86

![FF](https://user-images.githubusercontent.com/40011061/110526904-5ca2bd00-80e4-11eb-9a7c-ca734b2b904e.png)

**Comment by onimougwo** [comment]
I worked with desktop support at my company and we figured that it's related to Zscaler who seems to be applying some settings to Firefox. Though they can't do anything on their end, any suggestion ?

**Comment by jennifer-shehane** [comment]
@onimougwo I'm not familiar with Zscaler. I think you'd need those settings removed.

**Comment by melibe23** [comment]
The same happens with webkit.
