### ISSUE TITLE
cy.intercept having issue with matching url 

### ISSUE THREAD

**Issue by AurelienKun** [cypress-io/cypress#15381]
The following piece of code is working :
```
 cy.intercept({
  hostname: "www.google-analytics.com",
  pathname: '/collect',
  query: {
    ec: 'button',
    ea: 'click',
    el: 'Register'
  }
}, {
  statusCode: 200
}).as('register')
```

whereas this one should work but it does not :
```
 cy.intercept({
  url: "https://www.google-analytics.com/j/collect",
  query: {
    ec: 'button',
    ea: 'click',
    el: 'Register'
  }
}, {
  statusCode: 200
}).as('register')
```
This has been tested on Cypress 6.6.0.

**Comment by flotwig** [comment]
What is the URL that you are expecting to match?

**Comment by AurelienKun** [comment]
@flotwig I need the exact url I have written in my comment. My compagny asked me to create a test that verify that a statistic is really send to google analytic (no stubbing asked). So I went naturally with the second case I described until I found out that specifiying the whole url did not work. Instead, separating the url with hostname/pathname did the trick.

**Comment by flotwig** [comment]
Is the request for `"https://www.google-analytics.com/j/collect"` as the second example has or `"https://www.google-analytics.com/collect"` as you have in the first example?

**Comment by AurelienKun** [comment]
Oh my bad I see what you mean. I thought I used the same path but not. Wrong copy & paste when I tried maybe ? I'm closing the issue.
