### ISSUE TITLE
Cypress should expose list of runnables!

### ISSUE THREAD

**Issue by trainbolt** [cypress-io/cypress#15380]
I've been trying to figure out how to get a list of 'runnables' from a given spec to no avail. However, internally the Cypress app gets this list and then just iterates over it. You can see that the Cypress app actually compiles a list when using cypress:open

![Screen Shot 2021-03-08 at 4 49 48 PM](https://user-images.githubusercontent.com/331553/110548426-64af2c80-80e5-11eb-992d-803e40d55316.png)

Before any tests actually start running the list is displayed. 

Even if you run cypress in debug mode you can't parse this information out on the fly before tests are run. Using the DEBUG=cypress:server:reporter option you'll see that this information is only exposed prior to 'each' test running. Using DEBUG:cypress:* does not give any further info into how to gain this list of tests.

Unless I'm missing something here the only way I can see of gaining access to the list is to possibly alter the Cypress app to log the list using the built-in debug() function.

**Comment by jennifer-shehane** [comment]
Since this feature request hasn’t had a lot of interest over the years, we’ll close this issue.
