### ISSUE TITLE
Issue with dropdown and scroll

### ISSUE THREAD

**Issue by SuperHuman12** [cypress-io/cypress#15384]
Guys , i have been facing issues with dropdown clicks
when test running its not click opening dropdown , scroll down and select the option.

it's not working when testing with cypress

I have been trying it on my website, datarecapp.herokuapp.com

**Comment by bahmutov** [comment]
Unfortunately, we can do nothing without any details, please provide a reproducible example that we can see and run to show the problem. You can also ask your question on our chat channel https://on.cypress.io/chat. Just by reading your question, I would suggest reading the blog post https://www.cypress.io/blog/2020/03/20/working-with-select-elements-and-select2-widgets-in-cypress/
