### ISSUE TITLE
The required API is not getting called after clicking a button on cypress execution window whereas same scenario executed manually on normal browser is working as expected.

### ISSUE THREAD

**Issue by Ppkd2021** [cypress-io/cypress#15400]
### Current behavior

After filling the form on the UI and clicking on submit button then it should trigger api call but that is not happening when we are executing it through cypress.
Please see the first two minutes of the video uploaded.

https://user-images.githubusercontent.com/59794856/110667038-dd9aab00-81ef-11eb-83dd-a7754c84efcd.mp4

cypress window.
### Desired behavior

The options that we have tried:
1. Before reaching the form we have put wait for each gql call using intercept. - Same behavior as reported
2. Tried with a different set of test data. - Same behavior 

NOTE - We tried automating the same scenario using playwright and it's working as expected there.
### Test code to reproduce

```js
cy.getDataTestId(`button-add-moderator`).should(`be.visible`).click();
		cy.getDataTestId(`field-name-add-moderator-pop-up`).type(`Jitendra Choudary`);
		cy.getDataTestId(`field-Email-add-moderator-pop-up`).type(`automation_haspile_moderator@tfbnw.net`);
		cy.getDataTestId(`field-mobileNumber-add-moderator-pop-up`).type(`8888888888`);
		cy.getDataTestId(`button-send-invite`).should(`be.visible`).should(`be.enabled`).click();
		// cy.wait(`@AddModeratorForGroup`, { timeout: 30000 }); -- This is the API which should be triggered.
		// cy.wait(`@GetGroupModeratorsByGroupId`, { timeout: 30000 });
		// cy.wait(`@GetInvitations`, { timeout: 30000 });
		cy.contains(`[data-test-id="moderator-name"]`, `Automation User`,{timeout:60000})
			.should(`be.visible`).should(`have.text`, `Automation User`);	
```

### Versions

6.6.0

**Comment by jennifer-shehane** [comment]
Are there any errors visible in the DevTools console? Can you recreate the issue locally and see?

**Comment by Ppkd2021** [comment]
Locally I am not able to recreate nor any error in dev console. The above scenario is working in production fine.
