### ISSUE TITLE
`have.css` assertion fails when passed number value

### ISSUE THREAD

**Issue by panzarino** [cypress-io/cypress#15417]
### Current behavior
Passing a string to `have.css` assertion will always fail. This might also be an issue with other assertions, I haven't checked yet.

```javascript
cy.get(...).should('have.css', 'opacity', 0.5)
```

Result:
<img width="426" alt="Screen Shot 2021-03-10 at 19 51 07" src="https://user-images.githubusercontent.com/7033952/110719284-99e97680-81da-11eb-9735-93de6d0035d7.png">

### Desired behavior
The assertion should implicitly cast the number to a string. This behavior would be consistent with the changes implemented in #7314

### Versions
Probably since 4.5.0 at least

**Comment by jennifer-shehane** [comment]
It does seem like it should accommodate numbers, which what we've already supported. I wonder if it's just a problem with the double assertions.
