### ISSUE TITLE
Cypres 6.6.0 - Gives TypeError "Cannot set property 'status' of undefined" while entering email id in user login screen

### ISSUE THREAD

**Issue by nyadav08** [cypress-io/cypress#15421]
### Current behavior

I am running below test script on chrome browser and it launch the browser but not able to enter the complete email id in user field and gives  TypeError "Cannot set property 'status' of undefined". If I launch this URL outside of cypress test then I can login to this account without an issue so its not an application issue.
```js
    it('navigates', () => {
        cy.visit('https://account.jetbrains.com/login');
        cy.get('#username').click().focused();
        cy.wait(5000)
        cy.get('#username').click().type('abc123@xyz12312.com', {force: true}).should('have.value', 'nyadav@splunk.com');
        cy.get('.js-auth-dialog-input-password > .form-control').click();
        cy.get('.js-auth-dialog-input-password > .form-control').type('ABCDE#2021);
        cy.get('.js-auth-dialog-btn-signin').click();
    })
```

### Desired behavior

It should allow to login and type the user id and password details completely and perform the login.
### Test code to reproduce

```js
    it('navigates', () => {
        cy.visit('https://account.jetbrains.com/login');
        cy.get('#username').click().focused();
        cy.wait(5000)
        cy.get('#username').click().type('abc123@xyz12312.com', {force: true}).should('have.value', 'nyadav@splunk.com');
        cy.get('.js-auth-dialog-input-password > .form-control').click();
        cy.get('.js-auth-dialog-input-password > .form-control').type('ABCDE#2021);
        cy.get('.js-auth-dialog-btn-signin').click();
    })
```

### Versions
6.6.0

**Comment by jennifer-shehane** [comment]
I'm not sure why this error would only show in Cypress. Maybe something to do with the page being rendered in an iframe.

```js
it('navigates', () => {
  cy.visit('https://account.jetbrains.com/login');
  cy.get('#username').click().focused();
  cy.wait(5000)
})
```

<img width="1632" alt="Screen Shot 2021-03-16 at 3 39 07 PM" src="https://user-images.githubusercontent.com/1271364/111369822-dcdd9b00-866d-11eb-80b0-823d1b0056e7.png">

<img width="605" alt="Screen Shot 2021-03-16 at 3 38 08 PM" src="https://user-images.githubusercontent.com/1271364/111369840-e23ae580-866d-11eb-9d43-d6dd6b58012f.png">

You can ignore the error by following these directions. https://on.cypress.io/catalog-of-events#To-turn-off-all-uncaught-exception-handling

**Comment by azimsky** [comment]
These errors overflow console (when writing tests) and logs (when running tests). Ignoring the error allows only to go on with the test. Is it possible to implement a fix? Something like:

```javascript
t.params = {...(t.params || {}), status: e.status };
```

**Comment by minaairsupport** [comment]
the same error happens to me 
I noticed something very import maybe make me change my mind about using cypress 
these errors are random sometimes I got that error on typing **email** or **password**
other times on click at login button `cy.get("#login").click`

I wonder why this happing 

```
describe('cats app', () => {
    beforeEach(() => {
      cy.visit(Cypress.env('host'))
    })
  
    it('login to cats', () => {
    // clear local storage 
    cy.clearLocalStorage()

    cy.get('#email').type(Cypress.env('email'))
    .should('have.value', Cypress.env('email'))
    cy.percySnapshot();
    cy.get('#password').type(Cypress.env('password'))
    .should('have.value', Cypress.env('password'))
    cy.percySnapshot();

    cy.get("#login").click({force: true})

     // to ensure login is working 
    cy.get("#TicketsNav").should('be.visible')
    cy.percySnapshot();

      
    })

})
```

**Comment by romreed** [comment]
i got same issue

**Comment by eiel** [comment]
the same error happens to me.
The reason was that newrelic was replacing XMLHttpRequest.
When running Cypress, it's easy to avoid loading newrelic, but I couldn't do it right away, so I forced myself to use the following code.
```
if (window.Cypress) {
  const XHR = window.newrelic?.o?.XHR;
  if (XHR) {
    window.XMLHttpRequest = XHR;
  }
}
```

**Comment by pichan-qantas** [comment]
Hello @jennifer-shehane, we also get the same issue in Cypress version 10.3

We got the error when Cypress try to start running a next test case. We already added uncaught exception handler which helps us handle the exception in our first test case, but it didn't catch the same exception in the subsequence test cases.

![Screen Shot 2565-08-16 at 11 14 58](https://user-images.githubusercontent.com/98799387/184796743-84568a2d-1689-40e1-80f4-61c66cb1aad8.png)
