### ISSUE TITLE
Standard output options

### ISSUE THREAD

**Issue by bjornandersson** [cypress-io/cypress#15423]
When i run `npx cypress run` in git bash or on Jenkins I'm getting ugly output as these terminals don't support colors. When i run the same command in VS Code terminal the output looks "pretty".

I can't find any `--no-color` flag or anything similar. Is there another way to solve this?

**Comment by jennifer-shehane** [comment]
You can turn off the ASCII characters to clean up the noise of the logs as explained [here](https://on.cypress.io/continuous-integration#Colors).
