### ISSUE TITLE
`Cypress.Cookies.defaults()` return type is `void` but the code does return a value

### ISSUE THREAD

**Issue by ben8p** [cypress-io/cypress#15426]
### What would you like?

`Cypress.Cookies.defaults()` allow to preserve some cookies during the test execution.  

However, there is no official way to extend the existing list of defaults.

`Cypress.Cookies.defaults()` return the default object but the type tells it returns `void`

Ideally the returnType of `Cypress.Cookies.defaults()` should be change, or a method to retrieve defaults could be added

### Why is this needed?

We have a cypress plugin doing some user authentication.  
This plugin uses `Cypress.Cookies.defaults()` to make sure the authentication is working.  

In our code, we also have a special cookie that we set and we could like it to be preserved.

With current types it seems impossible.  

However, we can "hack" something because `Cypress.Cookies.defaults()`  does return a value:

```js
// the Cypress type wrongly says the default method is returning void.
		// in fact it returns the destination object (because the implementation is based on _.extends)
		// see https://github.com/cypress-io/cypress/blob/c12347dc9c4f9dc0662ad9350536c6c6b99225c4/packages/driver/src/cypress/cookies.js#L144
		// thanks to this hack we can extend the existing defaults and add our cookie
		const currentDefault = Cypress.Cookies.defaults({}) as unknown as Partial<Cypress.CookieDefaults> | undefined;
		if (currentDefault && 'preserve' in currentDefault) {
			const { preserve } = currentDefault;
			const toPreserve = [];
			if (Array.isArray(preserve)) {
				toPreserve.push(...preserve, USERNAME_COOKIE);
			} else if (typeof preserve === 'string') {
				toPreserve.push(preserve, USERNAME_COOKIE);
			} else if (!preserve) {
				toPreserve.push(USERNAME_COOKIE);
			} else {
				throw new Error(`could not extend the existing Cypress.Cookies.defaults, received: ${JSON.stringify(currentDefault)}`);
			}
			Cypress.Cookies.defaults({ preserve: toPreserve });
			cy.log(`Preserved cookies: ${toPreserve.join()}`);
		} else {
			// because this whole solution is hack, let's be verbose in case of failure
			throw new Error(`could not fetch the existing Cypress.Cookies.defaults, received: ${JSON.stringify(currentDefault)}`);
		}
```

**Comment by jennifer-shehane** [comment]
Yes, feel free to open a PR to fix the types. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).
