### ISSUE TITLE
Expose setSystemTime from lolex

### ISSUE THREAD

**Issue by emilgoldsmith** [cypress-io/cypress#15424]
### What would you like?
I would like to be able to do:

```javascript
cy.clock().then(clock => clock.setSystemTime(12345));
```

### Why is this needed?
I am testing a timer, and I realized that when I wanted to test it also displays hours correctly, I did cy.tick(4*60*60*1000) and Cypress froze because it was running thousands of setInterval callbacks in a row. `setSystemTime` allows me to skip forward in time, and I can still use tick for small increment testing.

I'm happy to do the implementing

**Comment by emilgoldsmith** [comment]
P.S: I have a working test right now as I just used the workaround of installing the underlying package myself and manually faking timers, and then using setSystemTime, but would of course be neat to not have to do that

**Comment by emilgoldsmith** [comment]
Hi @jennifer-shehane so I see it was tagged as a proposal, what does this mean logistically, is it welcome for me to contribute this change or does it need to go through some kind of discussion first?

**Comment by jennifer-shehane** [comment]
@emilgoldsmith I think this would be an accepted change. There seems to be a use case for it. Maybe @chrisbreiding has some thoughts.

**Comment by chrisbreiding** [comment]
That sounds good to me 👍

**Comment by emilgoldsmith** [comment]
Great :), I’ll try to set aside time for it one weekend then, but anyone else following is definitely welcome to do it too :)
