### ISSUE TITLE
"no compatible source was found for this video" error on dashboard

### ISSUE THREAD

**Issue by jpita** [cypress-io/cypress#15437]
I'm getting this error
![image](https://user-images.githubusercontent.com/5482105/110832532-530b8780-8293-11eb-87c5-19ce6ee2d0e4.png)
![image](https://user-images.githubusercontent.com/5482105/110832824-a7af0280-8293-11eb-9a15-394a9550da2d.png)

when I try to watch the video from this flaky tests https://dashboard.cypress.io/projects/7izdto/runs/37/test-results/d1bdb002-c2b0-4b53-89de-46a866ffa37a
![image](https://user-images.githubusercontent.com/5482105/110832928-c0b7b380-8293-11eb-9e02-4239ef1013fc.png)

- this is how my `cypress.json` file looks like 

```
"videoUploadOnPasses": false,
"video": true,
"videoCompression": false,
```

**Comment by jpita** [comment]
update: that `cypress.json` content might not be correct for that error since the dev didn't have their code updated from main with my changes, I think the correct content is this:
``` 
"watchForFileChanges": false,
"viewportWidth": 240,
"viewportHeight": 290,
"videoUploadOnPasses": false,
"modifyObstructiveCode": false,
"baseUrl": "http://127.0.0.1:8080",
"defaultCommandTimeout": 6000,
"video": true,
"firefoxGcInterval": {
"runMode": null,
"openMode": null
}
``` 
https://github.com/wikimedia/wikipedia-kaios/blob/3088437dc11d89c6b2bd0fe18346fdd20402a230/cypress.json

**Comment by jennifer-shehane** [comment]
Have you tried recording video in Firefox locally? Is the video file viewable? I know we had an issue with video files being unplayable for Firefox 88+ at one point. What version of Firefox is it recording in?

**Comment by jpita** [comment]
this is the video I managed to take from circleCI

https://photos.app.goo.gl/bNbDZiJnyJeTYYsf6

note the length of the video is 00:00, maybe that's what's causing the issue?

I managed to build the code locally and ran the tests.

with electron it works fine ( videos play as expected and have "normal sizes/weight") but with firefox the video is "weird" (doesn't play all the tests, half the size of electron recordings)

https://drive.google.com/file/d/1kUdglkAHKZkGNOo79ixu1J2KggJV63Ui/view?usp=sharing

Firefox 86.0.1 on local, fully updated

the videos are all viewable with finder(select video and press the space bar) but can't play them on VLC (too short to play?).

**Comment by BradRyan** [comment]
I'm having the same issue from what I can tell, but with chrome... did you ever figure this out @jpita?

**Comment by BradRyan** [comment]
@jennifer-shehane nope, did not touch the the videoCompression.

Using the following docker image if it matters. `image: cypress/browsers:node12.18.3-chrome89-ff86`.  I noticed I had videos uploaded for every test in circle even with the `videoUploadOnPasses": false,` attribute, but I only had the failed test videos in cypress dashboard if I recall.  I'll try to revisit this next week as I had to switch off to some other work.

`cypress.json`
```
{
  "baseUrl": "http://localhost:3000",
  "chromeWebSecurity": false,
  "projectId": "XXXX",
  "video": true,
  "videoUploadOnPasses": false,
  "retries": {
    "runMode": 2,
    "openMode": 0
  }
}
```

**Comment by jennifer-shehane** [comment]
@BradRyan Yah, I've seen another report of this that I'm trying to track down which part of the product may be the cause. Can you run `DEBUG=cypress:server:project cypress run` and print the logs here?

**Comment by jennifer-shehane** [comment]
@BradRyan I think your issue may be https://github.com/cypress-io/cypress/issues/2939 and is different from thie 'no compatible source was found for video' error. Let me know if you see this exact error in the Dashboard though.

**Comment by benchaminaa** [comment]
I'm having same issue with Chrome. 

![image](https://user-images.githubusercontent.com/20333209/124542913-a53a6f00-de67-11eb-8998-107333af0abc.png)

Following is the configuration details
{
  "baseUrl": "http://localhost:3000",
  "video": true,
  "videoUploadOnPasses": false,
  "videoCompression": 32,
  "viewportWidth": 1280,
  "viewportHeight": 844,
  "retries": {
    "runMode": 2,
    "openMode": 1
  }
}

**Comment by vitaliy4us** [comment]
I have the same issue

**Comment by nagash77** [comment]
Hi @benchaminaa , this issue is quite old and stale at this point.  Would you please open a new issue with a reproducible example and our dev team will be be happy to investigate.  A couple of things that are important to note in the ticket, make sure you provide a test that we can run where you are seeing the problem.  The best way to provide us a reproducible example is to fork [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) and link to it in the ticket.  Also providing debug logs may be helpful in this scenario as well.

**Comment by nagash77** [comment]
This issue has become stale.  I am going to close this issue.  If folks encounter a similar issue in a current version of Cypress please open a new issue with a reproducible example and our team will be happy to investigate.
