### ISSUE TITLE
Character problems with character encoding of iso-8859-1 sites

### ISSUE THREAD

**Issue by darkcattz** [cypress-io/cypress#1543]
- Operating System: Mac OS
- Cypress Version: Last
- Browser Version: Chrome and Electron

Hello, 

My site is not yet in utf8 and i have Character problems for accented characters (`doctype iso-8859-1`) when I use cypress. It's not really blocking except when doing regular expression searches  : 

HTML HEADER CHARSET : 
```
meta http-equiv="content-type" content="text/html; charset=iso-8859-1"
```

Result : 
```
Les sites ont bien ï¿½tï¿½ supprimï¿½s
ï¿½ Tous droits rï¿½servï¿½s ï¿½ 
```

Thanks
Regards

**Comment by victorjspinto** [comment]
Same problem with me.

i'm trying to write some test to and old plataform with charset iso-8859-1

**Comment by Longtrainz** [comment]
Same problem with windows-1251

**Comment by cannibalcow** [comment]
Why is this labeled as a feature? Is this not a bug?

**Comment by dudevictor** [comment]
I'm also facing this issue. Trying to write tests in a old app that uses ISO-8859-1. Any workaround?

**Comment by dudevictor** [comment]
Hello @jennifer-shehane thanks for you time. I've uploaded the repository https://github.com/dudevictor/cypress-character-problem that shows this issue.

Besides the file must be encoded with `iso-8859-1`, also I've noticed that the server must returns the `content-type` header with `charset=iso-8859-1` so that the issue occurs.

**Comment by opensas** [comment]
I have a similar issue, I reported it [here](https://github.com/cypress-io/cypress/issues/3725), added a very simple html page to reproduce the bug:

```html
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html">
  <meta charset="windows-1252">
</head>
<body>
  <h1>Character encoding failing test: á é í ó ú ñ</h1>
</body>
```

also asked at [SO](https://stackoverflow.com/questions/55203672/cypress-runner-ignoring-charset-windows-1252-html-tag)

**Comment by opensas** [comment]
ON the other hand, I noticed this issue is labeled like `stage: needs information`, I would gladly help with this if anybody can tell me what information is missing

**Comment by jennifer-shehane** [comment]
Hey @opensas - I do believe this issue is likely the same. 

Honestly, this should be labeled as 'ready for work' on our side, since we do have a reproducible example. The cause it still unknown though, although we had a theory.

The fact that this doesn't run correctly in Electron only is a helpful new piece of information.

I will close https://github.com/cypress-io/cypress/issues/3725 as a duplicate.

**Comment by opensas** [comment]
> I will close #3725 as a duplicate.

Sure, go ahead, I do hope you can work it out. Please let me know if there's anything I can do to help.

BTW, can anybody give a clue on how to implement a custom extension to cy like this:

```js
cy.get('div.flash_error span')
      .containsWithEncoding('El código de la aplicacion no puede estar vacío.')
```

It would just build a regular expresion replacing every problematic char with '.'

thanks a lot

**Comment by jennifer-shehane** [comment]
@opensas Look into our [custom command documentation](https://on.cypress.io/custom-commands)

**Comment by opensas** [comment]
thanks, just for the record, this is the workaround I developed:

```js
Cypress.Commands.add('containsLike', {
  prevSubject: true
}, (subject, search, chars) => {

  chars = chars || 'áéíóúñÁÉÍÓÚÑ'
  if (!Array.isArray(chars)) chars = chars.toString().split('')

  chars.forEach( char => {
    const repAllChars = new RegExp(char, 'g') // see: https://stackoverflow.com/a/17606289/47633
    search = search.replace(repAllChars, '.')
  })

  const regExp = new RegExp('^' + search + '$')
  return cy.wrap(subject).contains(regExp)
})
```

and I use it like this:

```js
describe('my first test', () => {
  it.only('should pass', () => {
    cy.visit('http://localhost/xxxx/yyy.asp')
      .get('div.flash_error span')
      .containsLike('El código de la aplicacion no puede estar vacío.')
// it runs .contains(/^El c.digo de la aplicacion no puede estar vac.o\.$/)
  })
})
```

**Comment by HeatherFlux** [comment]
Hey this has to due with obstructive code. To fix the issue in your configuration file use, "modifyObstructiveCode": false . This should fix any issues with weird charsets.

**Comment by opensas** [comment]
I can confirm that setting modifyObstructiveCode to false does NOT fixes the issue, this is my cypress.json:

```js
{
  "modifyObstructiveCode": false,
  "browser": {
    "modifyObstructiveCode": false
  }
}
```

(didn't know if the settings goes on the root level or inside browser)

and I also tried starting cypress with:

```shell
cypress open --config modifyObstructiveCode=false
```

None of them seemed to work
```

**Comment by HeatherFlux** [comment]
Hmmm, sorry then. For me I was having issues with some chars not being translated properly when running my application. https://docs.cypress.io/guides/references/configuration.html#modifyObstructiveCode
This section was able to help me solve the issue I was having with ï¿½tï type of char in the translation of bsdatepicker. 

My config was laid out as such: 
`{
  "modifyObstructiveCode": false,
}`

**Comment by nagyzso94** [comment]
I have the same issue. Has anyone found a solution to this?
Tried to set the modifyObstructiveCode to false in cypress.json but that didnt help.

**Comment by simonmeggle** [comment]
Are there any new on this topic? I also have a web site which is comes in win1252; the charset gets utf8 in cypress. The german umlauts (ä,ö,ü) on this site are all displayed wrong (e.g. `ï¿½`). 
Setting `modifyObstructiveCode` to false also did **not** work for me.

**Comment by simonmeggle** [comment]
Great to hear that you are working on the charset issue. Ad far as I can see, #4698 does not cover the win-1252 charset. Is there any plan to do this also? Thanks...

**Comment by flotwig** [comment]
Hey @simonmeggle, it does also fix `win-1252` charset, along with any other charset you're likely to experience on the web. I'll update the issue comment to clarify :)
