### ISSUE TITLE
Can I run cypress as a service to get http request and run the command in request?

### ISSUE THREAD

**Issue by aaronchen2k** [cypress-io/cypress#15442]
I'd like to run cypress scripts line by line interactively. Can I run cypress as a service to get http request and run the command in request? Using node.js http service to interactive with cypress also is ok for me too.

For Example:
1. Postman send a request to service;
2. Service parse the request, get the cypress script in request;
3. Service exec cypress script interactively.

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
