### ISSUE TITLE
Module API : cypress.run() returns "result.failures = undefined"

### ISSUE THREAD

**Issue by abhidp** [cypress-io/cypress#15443]
### Current behavior

Please refer to my fork of `cypress-test-tiny` for source-code (link below with details on how to run the test)

When trying to handle test failures, using 
```javascript
cypress.run().then((result) => {
  console.log('Result Failures: ', result.failures) //undefined
})
```
`result.failures` is returned as `undefined`

### Desired behavior

According to the docs: https://docs.cypress.io/guides/guides/module-api.html#Handling-errors
```javascript
// e2e-run-tests.js
const cypress = require('cypress')

cypress.run({...})
.then(result => {
  if (result.failures) {
    console.error('Could not execute tests')
    console.error(result.message)
    process.exit(result.failures)
  }

  // print test results and exit
  // with the number of failed tests as exit code
  process.exit(result.totalFailed)
})
.catch(err => {
  console.error(err.message)
  process.exit(1)
})
```

`result.failures` should return the details of the failed results and allow the user to write their own custom error-handling logic

### Test code to reproduce

https://github.com/abhidp/cypress-test-tiny

Details: 
* there are 2 spec files which will fail `fail1.spec.js` and `fail2.spec.js`
* run the entire suite using `npm run cypress:module:run`
* after the run is complete, check for the debug message `===== Result Failures =====  undefined` on console 
* this `undefined` is the value of `result.failures` returned by `cypress.run()`

### Versions

```
"cypress": "^6.6.0"
"node": "v10.22.1"

Software:

    System Software Overview:

      System Version: macOS 10.15.7 (19H2)
      Kernel Version: Darwin 19.6.0
      Boot Volume: Macintosh HD
```

**Comment by jennifer-shehane** [comment]
result.failures will only be returned if the run is in an *errored* state - like there was a problem where the Cypress run couldn't complete. I think this is poor naming on our part. It will not return anything if the run completed - whether it completed with failing tests or passing tests.

**Comment by abhidp** [comment]
Thanks for the clarification @jennifer-shehane . 
Is there a way to find out which specs failed in the cypress.run()?
I want to get a list of all the failed specs and add more logic to handle them as mentioned in Cypress Module API docs

```

- Send a notification about failing tests with included screenshot images
- Rerun a single failing spec file
- Kick off other builds or scripts

```

I could not find any docs related to finding the names of the failed specs from `cypress.run()`

**Comment by jennifer-shehane** [comment]
The tests would be available in the `results.runs` array. You'd have to write some JavaScript to get it, but the first test title would be located at `results.runs[0].tests[0].title` - being an array itself, so you would concatenate the title array together to get the title. You would know if the test failed if any of the objects in the `results.runs[0].tests[0].attempts` array has a `state === 'failed'`. You can see an example of results here: https://on.cypress.io/module-api#Results

You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
