### ISSUE TITLE
Unable to continue test run and also left panel does not show when launch application

### ISSUE THREAD

**Issue by niloysur09** [cypress-io/cypress#15449]
Steps:

1. Launch Cypress
2. Run the test for the first time (runs well)
3. Then stop and run the test again

Result:
It is just launching my test application nothing else is happening, also the left panel where can see the step wise execution and command log also not showing.
If I Go to File -> View App Data and clear the data, re launch the Cypress. Then run the test in that case for the first time it runs fine and shows the left panel. From the next time again it is having the same issue

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? This is likely very dependent on the application under test + your test files. Can you recreate it with one of our example repo projects? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by niloysur09** [comment]
`describe('My First Test', () => {
  beforeEach(() => {
    cy.clearLocalStorage()
  })
    it('Visits the Hedwig Dashboard', () => {
      cy.visit('/')
      cy.contains('Login with Concedo').click()

      cy.get('#username').type('svc.qa.hedwig@grabtaxi.com')
      cy.get('#password').type('Hedwigtest2019$')

      cy.get('#login-button').click()

      cy.get('#identifierId').type('svc.qa.hedwig@grabtaxi.com')
      cy.contains('Next').click()

    })
  })`

**Comment by niloysur09** [comment]
cypress.json
`{
    "projectId": "w1srgz",
    "chromeWebSecurity": false,
    "baseUrl": "https://hedwig-dash.stg-myteksi.com"
}`

**Comment by niloysur09** [comment]
Hi @jennifer-shehane I have added the codes I have used and the cypress.json file as well. 
To confirm you, yes it it happening with My application only, If I launch the cypress test Kitchen application or google.com it works fine. Not sure why the issue is with my application only.
As the application is internal I can't provide the video recording, but as you can see in the screenshot - when I run 'hedwig.login.js' it opens the full screen application (second screenshot)

**Comment by 08screasey** [comment]
@niloysur09 Was it possible that you have a service worker installed on this app?
I am facing this issue today with a React/Workbox setup, The application is redirected to cover the full-screen for some reason and the test facilities are no longer available. After unregistering the service worker manually and setting "bypass for network" to checked in the devtools the issue is no longer there. @jennifer-shehane is this something that there is a current solution to?
