### ISSUE TITLE
Can't install cypress

### ISSUE THREAD

**Issue by steverb1** [cypress-io/cypress#15454]
I'm trying to install cypress, there is as proxy involved.  I've read everything on the Cypress web site about proxies and tried everything I know to try.  Still can't install it.
I'm doing this from a PowerShell window.

Here's the setup:
I have a .npmrc file with
`registry=https://{address of our internal npm repository}`

I have verified that Cypress is there.

In the PowerShell window, before installing I do:
```
$env:HTTP_PROXY = "{our internal proxy}"
npm config set registry https://{same address above, to internal npm repository}
```

After "npm install cypress" I get this error:
```
===================================================

> cypress@6.6.0 postinstall C:\Code\CypressTest\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 6.6.0)

  ×  Downloading Cypress
    → Cypress Version: 6.6.0
     Unzipping Cypress
     Finishing Installation
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

URL: https://download.cypress.io/desktop/6.6.0?platform=win32&arch=x64
Error: tunneling socket could not be established, cause=connect ECONNREFUSED xxx.xxx.xxx.xxx:80

Platform: win32 (10.0.18363)
Cypress Version: 6.6.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@6.6.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@6.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

======================================================
```
Any ideas on what I am missing?

**Comment by cbruge** [comment]
Try also adding https_proxy, HTTPS_PROXY and http_proxy, maybe even all_proxy. 
I dont know what it was but Cypress requires either upper or lowercase🤔
additionally npm config set proxy / npm config set https-proxy might help

**Comment by jennifer-shehane** [comment]
@cbruge The proxy configuration is not sensitive to capitalization: https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/download.js#L19:L19

**Comment by cbruge** [comment]
@jennifer-shehane thats great news! Maybe I mixed things up, have been using Cypress since v3.x🙈

**Comment by steverb1** [comment]
So, I ended up installing it from the binary.  Now, when trying to run my first sample test, I get:

     Cypress failed to make a connection to the Chrome DevTools Protocol

I'm sure this is something to do with the internal company network (it is locked down pretty good) but I don't know where to start.  What kinds of questions do I need to ask our security folks?

**Comment by steverb1** [comment]
Now, seeing other people have had this same issue in the past.  So maybe not related to our company network.  Is there a resolution for this?  Running Cypress 6.6.0

**Comment by steverb1** [comment]
Also, I can run a test in Cypress successfully in Edge, but not Chrome.

**Comment by steverb1** [comment]
Here's an update: I can run Cypress with Chrome, but only if Chrome is not already open.  If Chrome is already open I get the error "Cypress failed to make a connection to the Chrome DevTools Protocol".
Is that the expected behavior?
If so, can you warn users that Chrome should not be running prior to firing up Cypress?

**Comment by jennifer-shehane** [comment]
@steverb1 That is not expected behavior. This can happen if you have 2 Cypress applications running at the same time. https://github.com/cypress-io/cypress/issues/5613

I think it may also happen if you are connecting to the chrome debugging port in some other manner https://github.com/cypress-io/cypress/issues/14835

But I haven't seen that error in a while outside of those reasons.
