### ISSUE TITLE
Object has been destroyed

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1546]
Using an explicit `cy.screenshot()` and switching between the Electron browser + Chrome will result in this error:

![screen shot 2018-04-06 at 1 53 32 pm](https://user-images.githubusercontent.com/1268976/38436211-ee5a469c-39a1-11e8-9313-3c3d9d5ba1df.png)

This is a bug with not properly unregistering the Electron automation handlers when closing that browser and switching to a new one.

**Comment by jennifer-shehane** [comment]
Closing. This is no longer an issue in Cypress version 3.4.0
