### ISSUE TITLE
Can't import ES6 modules in plugins

### ISSUE THREAD

**Issue by krismosk** [cypress-io/cypress#15463]
### What would you like?

We discovered that we can't import ES6 modules in the Cypress plugin file without this error:
```
 /Volumes/workplace/package/src/test_package/node_modules/test_module/es6/test_directory/test.js:10
import * as t from 'io-ts/es6';
^^^^^^
 
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1051:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Volumes/workplace/package/src/test_package/cypress/plugins/index.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Module.m._compile (/Users/redacted/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/redacted/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```
### Why is this needed?

This is needed so that we can import ES6 modules that are necessary to be run as a node server process inside of the plugin `index.ts`. We would like the option to either modify the ts-node configuration, or be able to configure the babel transpilation before the plugin is loaded and accessed.

We have managed to find our own workaround for now. See my colleague's comment on this [issue](https://github.com/cypress-io/cypress/issues/7001#issuecomment-797838376).

**Comment by JohnnyFun** [comment]
I think you need to use `require` syntax in the plugins file. So something like `const t = require('io-ts/es6')` should work.

**Comment by adworacz** [comment]
@JohnnyFun https://github.com/cypress-io/cypress-realworld-app/blob/develop/cypress/plugins/index.ts#L1-L7

^^ Usage of `import` statements in an example project created and maintained by the Cypress team. It should be noted that this a Typescript file and not JS file, and Typescript discourages the use of `require`.

**Comment by JohnnyFun** [comment]
Ah, didn't see it was typescript. Cool. Did you guys check out similar closed issues? https://github.com/cypress-io/cypress/issues?q=SyntaxError%3A+Cannot+use+import+statement+outside+a+module

**Comment by krismosk** [comment]
@JohnnyFun Yep, we did look at other similar closed issues and contributed our workaround [here](https://github.com/cypress-io/cypress/issues/7001#issuecomment-797838376). While we have found our own workaround, it would be preferred if Cypress supported ES6 module imports out-of-the-box.

**Comment by TheDutchCoder** [comment]
I think this is actually a deeper problem. I don't know what Cypress does/uses under the hood, but I think pretty much every file is transpiled down to CommonJS.

The only file I can get to _actually_ use ES6 modules is the plugins file through TS, but spec files are transpiled down for sure, as they're not able to use ES6 modules at runtime.

Example:
`some-module.ts`
```ts
const a = []

export const setA = (val) => {
  a.push(val)
}

export const getA = () => {
  return a
}
```

`plugins/index.ts`
```ts
import { setA, getA } from '../some-module'

export default (on) => {
  on('before:browser:launch', (details) => {
    setA('hello!')
    console.log(getA()) // logs `['hello!']`
  })
}
```

`test.spec.ts`
```ts
import { setA, getA } from '../some-module'

describe('module', () => {
  beforeEach(() => {
     console.log(getA()) // logs `null`
  })
})
```

**Comment by DiegoMcDipster** [comment]
Any news on this?  I'm trying to read a config file (aws-exports) into my plugins.  The config file is exported like so:
```
export default awsmobile
```

When I import the file (ES6) I get the error: 

```
import awsmobile from "../../src/aws-exports";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

So, I try require (CommonJs) syntax:
```
const awsConfig = require("../../src/aws-exports");

export default awsmobile;
^^^^^^

SyntaxError: Unexpected token 'export'

```

I've been down a rabbit hole to use promises to get it imported.  None of it worked.

What I find strange though, is that the same config file can be required or imported into the support/command.js.  So, command.js is an ES6 module? and Index.js is cjs?

Note:
1. I'm using Javascript not typescript. 
2. I cannot change the export of the config file because it's dynamically generated according to my amplify environment. And therein lies the problem and the reason why i need to read from it.

Your advice and help in getting the config file into my plugins/index.js would really be appreciated!
