### ISSUE TITLE
Test consistently takes almost exactly 2 minutes to begin running from `cypress open` (can workaround by reloading browser. But I think I see the issue in DEBUG logs)

### ISSUE THREAD

**Issue by JohnnyFun** [cypress-io/cypress#15466]
### Current behavior
Click test, browser opens and shows loading indicator for almost exactly 2 minutes before running the test. In debugs, I'm seeing timeout errors like this that _maybe_ are the culprit?

```
2021-03-13T17:52:57.024Z cypress:server:request received an error making http request { 
  timeout: undefined, 
  retryIntervals: [ 0, 100, 200, 200 ], 
  url: 'http://gmupcrzgw/', 
  requestId: 'request10', 
  retryOnNetworkFailure: true, 
  retryOnStatusCodeFailure: false, 
  delaysRemaining: [], 
  err: Error: getaddrinfo ENOTFOUND gmupcrzgw 
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) { 
     errno: 'ENOTFOUND', 
     code: 'ENOTFOUND', 
     syscall: 'getaddrinfo', 
     hostname: 'gmupcrzgw' 
} }
```

Here's the [full debug log](https://github.com/cypress-io/cypress/files/6135319/cypress-open-debug.txt) too for more context if needed. Explanation of debug file:
- ran `set DEBUG=cypress:* && cypress open`
- search box already contains "validat", so I simply click "validator.spec.js"
- chrome opens at 11:52:22am shows loading indicator for almost exactly 2min at 11:54:18 (consistently ~2min give or take a few sec)
- test runs successfully
- stop cypress

If I simply reload the browser instead of waiting the 2 minutes, it starts pretty much right away, so don't beat yourself up if you're not seeing what's up since it seems like I can work around it.

Things I've tried so far:
- uninstalling cypress, clearing all cypress appdata local/roaming, re-installing cypress (also tried the formal `cypress cache clear` cmd too)
- downgrading cypress to `6.4.0` (we're running current latest `6.6.0`)
- using version of node that cypress comes with instead of what's on my system (which is 15.11.0 with npm 7.6.2)
- trying other browsers (edge, ff, electron)

Let me know if you want any other info about my setup--can provide `cypress.json`, `state.json` in appdata, etc.

If you all aren't quite sure, I might take some time to look around in cypress code. I didn't realize I have the whole thing, as this article mentions: https://docs.cypress.io/guides/references/troubleshooting.html#Edit-the-installed-Cypress-code. Very cool.

### Versions
Cypress: 6.6.0
Win10
Chrome89 (tried edge chromium, ff, electron too)
Node: 15.11.0 (cypress configured to use my `system` node)
Webpack: 5.25.0 (and a slightly modified version of `cypress-webpack-preprocessor-v5` to support webpack@5.x, but the bundles are definitely not the slowdown--that was what I originally thought was the culprit, but they get built super quick)

**Comment by jeroen-hoekstra** [comment]
Sound like the same issue as we're experiencing: [https://github.com/cypress-io/cypress/issues/15447](https://github.com/cypress-io/cypress/issues/15447).

If we downgrade to Webpack 4 everything works fine, but that's not desired.

**Comment by JohnnyFun** [comment]
Interesting, I didn't notice your issue when I made mine, but definitely sounds similar. Maybe changes in webpack 5 is causing a bad request uri to be made somehow in the cypress runner code. Looks like your log file, like mine, also has some wonky looking urls being attempted. Example:

`2021-03-12T08:26:06.100Z cypress:server:request received an error making http request { timeout: undefined, retryIntervals: [ 0, 100, 200, 200 ], url: 'http://iawabyex/', requestId: 'request7', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [ 0, 100, 200, 200 ], err: Error: getaddrinfo ENOTFOUND iawabyex at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) { errno: 'ENOTFOUND', code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'iawabyex' } }`

Betting my "workaround" of simply reloading the test browser window immediately instead of waiting works for you too?

**Comment by JohnnyFun** [comment]
If that's the underlying issue (building and attempting wonky urls), I think the issue might originate in `...\Cypress\Cache\6.6.0\Cypress\resources\app\packages\network\lib\agent.js` in `CombinedAgent.addRequest`. Thinking maybe the parameters passed to that function when it's called somewhere aren't in the correct order or something. But I'm not familiar with cypres's code much at all, so I might be way off...

**Comment by jeroen-hoekstra** [comment]
Yes, clicking the "Rerun" button during the almost 2 minute hang makes the test run instantly.

Requesting those strange looking urls appears to be normal behaviour: [https://github.com/cypress-io/cypress/issues/6695](https://github.com/cypress-io/cypress/issues/6695)

**Comment by lukeapage** [comment]
This may just be this:
https://github.com/cypress-io/cypress/issues/15447#issuecomment-804016838

You can look at my Pr to fix that issue and copy the cypress webpack pre processor from my branch locally (it’s 2 files) and use that from inside your plugins and see if it resolves the issue.
