### ISSUE TITLE
cy.intercept does not intercept URLs with single quotes

### ISSUE THREAD

**Issue by phelipetls** [cypress-io/cypress#15476]
### Current behavior
URLs with single quotes are not intercepted by `cy.intercept`.

This does not work:

```js
cy.intercept(
  "http://ipeadata2-homologa.ipea.gov.br/api/v1/Metadados('BM12_TJOVER12')",
  { }
)
```

Because the URL is `http://ipeadata2-homologa.ipea.gov.br/api/v1/Metadados(%27BM12_TJOVER12%27)`.

### Desired behavior
The request is intercepted normally.

I don't know what exact characters need to be escaped but it would be nice if this was automatically handled or documented. `encodeURIComponent` does not care about single quotes, so this is specially inconvenient.

### Test code to reproduce
I made a repo reproducing this opening my live application: https://github.com/phelipetls/cypress-test-tiny

**Comment by JohnnyFun** [comment]
What if you simply put in `%27` explicitly instead of `'` char?

**Comment by phelipetls** [comment]
It works but it's not great developer experience imo.

**Comment by JohnnyFun** [comment]
If you wanted to make the code more explicit about that and maybe more readable, you could replace single quotes with the url-encoded %27 like so: `"http://ipeadata2-homologa.ipea.gov.br/api/v1/Metadados('BM12_TJOVER12')".replace(/'/g, "%27")`.

Sounds like most times single quote chars don't need to be url encoded, but in certain URI schemes they do. More info here: https://stackoverflow.com/questions/18251399/why-doesnt-encodeuricomponent-encode-single-quotes-apostrophes/18251730

**Comment by jennifer-shehane** [comment]
Yeah, cy.route() used to encode everything, I'm not sure if intercept does that. https://on.cypress.io/route#url-as-a-string I mean, it at least doesn't with single quotes.

**Comment by phelipetls** [comment]
@jennifer-shehane I think this is a duplicate of #15956 and may be closed, as that issue has a better description of the problem.
