### ISSUE TITLE
Install fails if using vmware that contains Microsoft Edge browser

### ISSUE THREAD

**Issue by blainehilton** [cypress-io/cypress#15485]
### Current behavior

 I did the npm install cypress --save-deps and if I turn to use "run" instead of "open" at the command line it gives the error as well which is

```
We found an invalid configuration value:

Found an error while validating the `browsers` list. Expected `majorVersion` to be a string or a positive number. Instead the value was: `{"name":"edge","family":"chromium","channel":"stable","displayName":"Edge","version":"VMware Fusion 12.1.0","path":"/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge","majorVersion":null}
```

I have tried upgrading npm, restarting, reinstalling. I've tried googling the error message, I've tried searching for where this config file may be. I've tried searching the github issues. I'm not sure where to go from here. Any insights would be greatly appreciated.

The error is saying your Edge = "majorVersion":null
Test it running on Chrome npx cypress run --browser chrome --headless

Benny, thanks for your message. I tried that here, but the same thing happens:

```
npx cypress run --browser chrome --headless
We found an invalid configuration value:

Found an error while validating the `browsers` list. Expected `majorVersion` to be a string or a positive number. Instead the value was: `{"name":"edge","family":"chromium","channel":"stable","displayName":"Edge","version":"VMware Fusion 12.1.0","path":"/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge","majorVersion":null}`
```

npx cypress info shows:

```
npx cypress info
Displaying Cypress info...

Detected 3 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 89.0.4389.82
  - Executable: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

2. Edge
  - Name: edge
  - Channel: stable
  - Version: VMware Fusion 12.1.0
  - Executable: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

3. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 86.0
  - Executable: /Applications/Firefox.app/Contents/MacOS/firefox-bin

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox
- cypress run --browser edge

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected
```

I went into the Applications folder and deleted Microsoft Edge as that is what the error was mentioning, then I ran the info command and Edge was gone. So I tried open and now it loaded "properly" with the "To help you get started" screen

Gleb Bahmutov
@bahmutov

Yeah, why is Edge version VMware Fusion 12.1.0? This breaks the version parser we have for browser versions. If this is expected Edge version, could you open a new github issue for us

Gleb, this is because I'm running VM Ware Fusion on my mac so that I can run Windows 10 as well. That makes sense then as I couldn't get past that error even after trying a different version of node and reinstalling everything from scratch.

```
npx cypress -v
Cypress package version: 6.6.0
Cypress binary version: 6.6.0
Electron version: 11.2.3
Bundled Node version: 12.18.3
```

```
node -v
v14.16.0
```

```
npm -v
6.14.11
```

### Download method
 

- [X ] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux
- [X ] Mac Big Sur, Version 11.2.3
- [ ] Windows

with vmWare Fusion Professional version 12.1.0 running Windows 8.1

### Other

- [ x] I'm installing latest Cypress version 
- [no proxy ] I'm behind a proxy 
- [did not try in CI ] This only occurs in CI

**Comment by uebayasi** [comment]
A new comer & seeing the exact same problem.

Struggling to find the `plugins` directory to put browser filter configuration now.

https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers

**Comment by uebayasi** [comment]
I still have to hide `/Applications/Microsoft Edge.app` (I do `chmod 0000 ...` instead of `rm`) too.

The above `config.browsers.filter(...)` trick does not work, because it is applied _after_ all existing browsers are listed.

**Comment by jennifer-shehane** [comment]
We might want to fall back to 'version' instead of throwing if they're not even using this specific browser to run. Not sure if that's possible. 

But yes, we try to strip out the major version for display in our GUI and stdout, so `Running on Edge 56` for example. For this one....we're trying to strip out a major version from the `VMware Fusion 12.1.0` version which is not expected.

**Comment by jennifer-shehane** [comment]
In your `plugins/index.js` file, you can edit the browsers config, but...I'm not sure if this is early enough to fix the issue. You'd have to find the browser in the array that you want to edit, then change the `majorVersion`. 

```js
module.exports = (on, config) => {
  config.browsers[0].majorVersion = '12'

  console.log(config.browsers) // see what the browsers are now

  return config
}
```

I opened a PR here: https://github.com/cypress-io/cypress/pull/16990
