### ISSUE TITLE
Cypress not responding if we expect response body to have something that's not presented

### ISSUE THREAD

**Issue by emil14** [cypress-io/cypress#15489]
### Current behavior

Cypress not responding if we expect response body to have something that's not presented.

### Desired behavior

Cypress keeps respond and fails the test.

### Test code to reproduce

```js
cy.request(...) // in my case response is html page
    .then(
        resp =>
            expect(resp.body).to.include('not presented')
    )
```

### Versions

Cypress 6.5.0, Chrome 89.0.4389.82 64bit, Ubuntu 20.04.2

---

This is how it looks (cypress looks running but it not respond)

![Screenshot from 2021-03-15 18-06-09](https://user-images.githubusercontent.com/6453537/111175178-32a43b80-85b9-11eb-9c09-4dc54c6cdfe7.png)

**Comment by JohnnyFun** [comment]
What happens if you hit localhost 8080 in your normal browser? Do you need `https` instead of `http`? Does cypress eventually timeout trying?

**Comment by emil14** [comment]
> What happens if you hit localhost 8080 in your normal browser?

Everything is okay

> Do you need https instead of http?

No I don't :)

> Does cypress eventually timeout trying?

Nope

**Comment by JohnnyFun** [comment]
Hmm, any errors in the console?

**Comment by emil14** [comment]
I'm not able to see the console (or any other developer tools) in that situation :(

**Comment by JohnnyFun** [comment]
Oh, is the browser froze? If so, does this happen in other browsers too (ff, edge chromium, electron)? Could you put together a small project that recreates this situation? And/or provide the full test spec code? You might be able to open dev tools if you put a `cy.wait(1000)` so you can get it open before the browser freezes up (assuming that's what's going on).

**Comment by emil14** [comment]
Sorry no time for that right now. I'll try to provide working example later

**Comment by sainthkh** [comment]
Sorry for the late reply.

```js
it('t', () => {
  cy.request('https://google.com')
  .then((resp) => {
    expect(resp.body).to.include('not presented')
  })
})
```

I tested with the code above and it succeeded after 27~28 seconds. 

It seems that it's related with Cypress's rendering performance of the long content.

**Comment by jennifer-shehane** [comment]
This kind of reminds me of https://github.com/cypress-io/cypress/issues/6944 I think it's just an issue with trying to render the long content. You could turn off the Command Log to see if it's isolated to the rendering itself. Instructions: https://on.cypress.io/troubleshooting#Disable-the-Command-Log
