### ISSUE TITLE
Failed downloading the latest Cypress binary

### ISSUE THREAD

**Issue by bourdakos1** [cypress-io/cypress#15496]
### Current behavior

When trying to install 6.7.0 I get the following error (6.6.0 works fine):
```
URL: https://download.cypress.io/desktop/6.7.0?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
```

It looks like you just published 6.7.0 about 20 minutes ago, do I just need to wait a bit?

### Download method
 

- [ ] npm
- [X] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by fredrikgiang** [comment]
Windows: https://cdn.cypress.io/desktop/6.7.0/win32-x64/ - Works fine
Linux: https://download.cypress.io/desktop/6.7.0?platform=linux&arch=x64 - Not found

**Comment by bourdakos1** [comment]
looks like it's working now

**Comment by jennifer-shehane** [comment]
Yeah I think sometimes there is a weird lapse of a few minutes directly after release where this isn't available. Not sure why. Closing as resolved.
