### ISSUE TITLE
Weird characters when displaying compilation errors on Windowws

### ISSUE THREAD

**Issue by hannaofsweden** [cypress-io/cypress#1550]
- Operating System: Windows 10
- Cypress Version:  2.1.0
- Browser Version: Cypress 2.1.0 built-in Chrome

### Is this a Feature or Bug?

A bug.

### Current behavior:

Squares are displayed in compilation errors. Apparently the message contains characters that aren't represented in the font used, at least not in Windows 10.

### Desired behavior:

The characters replaced by squares should be displayed properly or the squares removed.

### How to reproduce:

Create a test file, have it import a Javascript file that contains errors.

### Additional Info (images, stack traces, etc)

![capture](https://user-images.githubusercontent.com/189345/38466586-c25c0414-3b2b-11e8-9e75-e48520e203b3.PNG)

**Comment by brian-mann** [comment]
Likely related to https://github.com/cypress-io/cypress/issues/1143.

It could be different though. If it's related it'll be fixed with #1143 gets fixed. If not, it can be fixed by setting `chcp 65001` in your windows console prior to running Cypress.
