### ISSUE TITLE
Docker image with cypress included missing for latest version

### ISSUE THREAD

**Issue by Shanson90** [cypress-io/cypress#15527]
Expected to find a docker image `/cypress/included:6.7.1` with the newest release but it doesn't seem to exist.  
We cannot update to latest without the image or a change to the way our CI pipeline is set up.

**Comment by jennifer-shehane** [comment]
Thanks - there was a PR for this to merge that was overlooked. https://github.com/cypress-io/cypress-docker-images/pull/463

**Comment by Shanson90** [comment]
No no, thank you!
