### ISSUE TITLE
Initial visit() is very slow on Vue apps 

### ISSUE THREAD

**Issue by murtazasultani** [cypress-io/cypress#15529]
### Current behavior

it is taking 95 sec to visit a page
<img width="322" alt="Screen Shot 2021-03-16 at 10 30 10 PM" src="https://user-images.githubusercontent.com/31856440/111357725-2e564c00-86a7-11eb-9041-fce97326171d.png">

### Desired behavior

it should load fast less than a sec

### Versions
Cypress 6.6.0
Chrome 89
Mac OS

**Comment by murtazasultani** [comment]
@jennifer-shehane do you have any idea?

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? This is likely specific to something on the project - like preprocessors, etc. This is not visible on most projects, so we'd need a way to reproduce to investigate.

**Comment by murtazasultani** [comment]
@jennifer-shehane Thank you, it was an issue with my project, the `cy.visit()` is waiting till all fonts and asset load completely I just solve that issue when running the test I remove my site fonts
