### ISSUE TITLE
Component testing fails to find #__cy_root in beforeEach - with no beforeEach in spec?

### ISSUE THREAD

**Issue by GCHQDeveloper911** [cypress-io/cypress#15524]
### Current behavior
I'm trying to get started with component testing a webpacked react project. When I launch my test (which currently does nothing more than trying to mount the component), Cypress fails with:
```
AssertionError: Timed out retrying after 4000ms: Expected to find element: `#__cy_root`, but never found it.

Because this error occurred during a `before each` hook we are skipping all of the remaining tests.

node_modules/@cypress/react/dist/cypress-react.esm-bundler.js:334:1
```
This is happening before any attempt to mount the component has happened, so it seems to be trying to unmount a 'default' root element - which fails (because it's not yet mounted the component being tested?)

### Desired behavior

If I'm understanding correctly, it shouldn't be building an unmount function based around a non-existent root element. If it mounted the component first, it would have the right root element to unmount?

### Test code to reproduce
I cannot provide full component code, however....

support/index.js:
```js
import './commands'
require('@cypress/react')
```
plugins/index.js:
```js
const webpackPreprocessor = require('@cypress/webpack-preprocessor')
const myWPWrapper = require('../../webpack.config');

module.exports = (on) => {
    const options = {
        // send in the options from your webpack.config.js, so it works the same
        // as your app's code
        webpackOptions: myWPWrapper(undefined, { mode: 'development' }),
        watchOptions: {},
    }
    on('file:preprocessor', webpackPreprocessor(options))
    // return codeCoverage(on, config);
}
```

cypress.json:
```json
{
    "experimentalComponentTesting": true,
    "componentFolder": "src",
    "testFiles": "**/*.cy.{js,ts,jsx,tsx}"
  }
```

simple spec:
```js
import React from 'react';
import { mount } from '@cypress/react';
import { myComponent } from './myComponent';

const mandatoryProps = {
  appName: 'Example App',
  environment: 'myenv',
};

describe('nothing', () => {
  it('does little', () => {
    mount(<myComponent  {...mandatoryProps} />);
  })
})
```

### Versions
Cypress various from 6.3 through to 6.7, CentOS8, Chrome 83

**Comment by anark** [comment]
I started seeing this when upgrading `@cypress/react` from `4.16.4` to `5.1.1`

**Comment by JessicaSachs** [comment]
Hi @anark, please use 4.x for now. The 5.x upgrade requires a different entry point and the documentation is not complete yet. We had accidentally released on the `latest` tag instead of `next` last night.
