### ISSUE TITLE
import causes a SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by musicformellons** [cypress-io/cypress#1553]
I am new to Cypress. As I use feathersjs (including its feathers client) with websockets I think it is recommended to stub my services (user creation etc.). I found [this example](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__functions/cypress/integration/unit-test-stubbing-dependencies-spec.js) which looks pretty close to what I think I need. However as soon as I add this line:
`import api from '../../../src/api' `
or:
`const api = require('../../../src/api.js'`

I get this errormessage:
![screenshot from 2018-04-09 19-51-44](https://user-images.githubusercontent.com/10334123/38514106-885c44e4-3c30-11e8-8140-3c5e92ac6d29.png)

I can import the api fine from my Vue components. The error refers to this code:
```
export default [
  {
    path: '/',
    component: () => import(`components/Index`),
    children: [
      {
        path: '',
        name: 'home',
        components: {
          default: () => import(`components/Home`)
        }
      },
      {
```
What's wrong here? As soon as I comment out the import/require, the tests do run again in Cypress.

**Comment by musicformellons** [comment]
Mmmh, so it seems that first the es6 arrow was a problem an now the es6 import is the problem as when I turn that into a `require` it moves the error to the next arrow etc. So why can't Cypress just read es6 anymore when I import my api module? Do I have to rewrite my route.js into es5? (gloops).

**Comment by musicformellons** [comment]
When I rewrite route.js into es5 the problem of not being able to handle es6 moves on to other app areas:
![screenshot from 2018-04-10 09-44-18](https://user-images.githubusercontent.com/10334123/38543100-ecd247e8-3ca3-11e8-9527-89b1c0c7276b.png)

**Comment by musicformellons** [comment]
I thought I maybe need to build the cypress spec files, but found Cypress to support es6 / es2015 by default, so looks to me this should just work then...

**Comment by bahmutov** [comment]
Did you install the modules? The error shows that it cannot find the module “quasar”?

**Comment by bahmutov** [comment]
It might be the dynamic import line there that the browserify bundler does not support - you would need to configure this separately

**Comment by musicformellons** [comment]
Uh, you mean setup a webpack/browserify preprocessor with non-default options?

It also is not really apparent that the example I used is using a non-default preprocessor. It use the same syntax:
```
import Auth from '../../auth'

// api.js is an adapter for the API the app uses
import api from '../../api'

// util.js is a module with utility functions
import util from '../../util'
```

**Comment by bahmutov** [comment]
don't you still have `component: () => import('components/Index')` line in the file? Can we have the complete reproducible example to see to debug this?

**Comment by musicformellons** [comment]
Ah, sorry, you meant thát dynamic import of course... Ok, then the dynamic and the alias of 'quasar' which is not in webpack makes the processor trip. A reproducible example would pretty much mean my entire app which is not possible. Maybe have a clear idea what's going on first before I cut stuff out and make a fiddle or something. 

I changed the dynamic import into es5 function code and that works. Instead of referencing 'quasar' in an import inside 'api' module I referenced the entire path:
`import {Notify} from '../node_modules/quasar-framework/dist/quasar.mat.esm.js'`

and get a new error:
![screenshot from 2018-04-10 16-48-21](https://user-images.githubusercontent.com/10334123/38564269-14d88960-3cdf-11e8-9db2-b1b971487c60.png)


which is something I can not really hack around I think...

**Comment by bahmutov** [comment]
well, the `quasar.mat.esm.js` seems to say "esm" which might be "ES module", so you are loading not ES5 common js module, but ES module (with `import` and `export` keywords). Maybe there is another file from that dependency you can load.

**Comment by musicformellons** [comment]
@bahmutov I am not sure I get your suggestion about the module:
1) apparently an esm module will not work (esm is > es2015 ?)?
2) if you mean a non esm version of quasar? No that is not available.
3) would using [esm](https://www.npmjs.com/package/esm) help me out somehow?

As you probably notice, I am kind of lost...

**Comment by musicformellons** [comment]
Regarding the websockets recipe: that would be great! This will involve stubbing I suppose?

**Comment by musicformellons** [comment]
These final two lines of ` ../node_modules/quasar-framework/dist/quasar.mat.esm.js` cause the error:
```
export default index_esm;
export { QActionSheet, QAjaxBar, QAlert, QAutocomplete, QBreadcrumbs, QBreadcrumbsEl, QBtn, QBtnGroup, QBtnDropdown, QBtnToggle, QCard, QCardTitle, QCardMain, QCardActions, QCardMedia, QCardSeparator, QCarousel, QCarouselSlide, QCarouselControl, QChatMessage, QCheckbox, QChip, QChipsInput, QCollapsible, QColor, QColorPicker, QContextMenu, QDatetime, QDatetimePicker, QDialog, QEditor, QFab, QFabAction, QField, QIcon, QInfiniteScroll, QInnerLoading, QInput, QInputFrame, QKnob, QLayout, QLayoutDrawer, QLayoutFooter, QLayoutHeader, QPage, QPageContainer, QPageSticky, QItem, QItemSeparator, QItemMain, QItemSide, QItemTile, QItemWrapper, QList, QListHeader, QModal, QModalLayout, QResizeObservable, QScrollObservable, QWindowResizeObservable, QOptionGroup, QPagination, QParallax, QPopover, QProgress, QPullToRefresh, QRadio, QRange, QRating, QScrollArea, QSearch, QSelect, QSlideTransition, QSlider, QSpinner, audio as QSpinnerAudio, ball as QSpinnerBall, bars as QSpinnerBars, circles as QSpinnerCircles, comment as QSpinnerComment, cube as QSpinnerCube, dots as QSpinnerDots, facebook as QSpinnerFacebook, gears as QSpinnerGears, grid as QSpinnerGrid, hearts as QSpinnerHearts, hourglass as QSpinnerHourglass, infinity as QSpinnerInfinity, QSpinner_ios as QSpinnerIos, DefaultSpinner as QSpinnerMat, oval as QSpinnerOval, pie as QSpinnerPie, puff as QSpinnerPuff, radio as QSpinnerRadio, rings as QSpinnerRings, tail as QSpinnerTail, QStep, QStepper, QStepperNavigation, QRouteTab, QTab, QTabPane, QTabs, QTable, QTh, QTr, QTd, QTableColumns, QTimeline, QTimelineEntry, QToggle, QToolbar, QToolbarTitle, QTooltip, QTree, QUploader, QVideo, backToTop as BackToTop, closeOverlay as CloseOverlay, goBack as GoBack, Ripple, scrollFire as ScrollFire, scroll$1 as Scroll, touchHold as TouchHold, TouchPan, TouchSwipe, actionSheet as ActionSheet, addressbarColor as AddressbarColor, appFullscreen as AppFullscreen, appVisibility as AppVisibility, cookies as Cookies, dialog as Dialog, Loading, notify as Notify, Platform, LocalStorage, SessionStorage, animate, clone, colors, date, debounce, frameDebounce, dom, easing, event, extend, filter, format, noop, openUrl as openURL, scroll, throttle, uid };

```
Anyway I found [this issue ](https://stackoverflow.com/questions/37902849/import-and-export-may-only-appear-at-the-top-level) which seems pretty much what I experience and it made clear to me that the quasar module is not transpiled by the default cypress settings, why not?

**Comment by musicformellons** [comment]
See referenced issue. I can transpile js files (and config my project aliases) using cypress webpack preprocessor, so closing.
