### ISSUE TITLE
Cypress visit and page load takes so much time when execute the testcases using docker in jenkins.

### ISSUE THREAD

**Issue by sardar-usman** [cypress-io/cypress#15536]
import HomePage from '../../support/page_objects/HomePage'
import DialPlanCallType from '../../support/page_objects/System/DialPlanCallTypePO'
import Common from '../../support/page_objects/CommonPO'

const homePage = new HomePage();
const DialPlanCallTypePage = new DialPlanCallType();
const CommonPage = new Common();

describe('Test Suite for Dial Plan Call Type', function () {

  before(function () {

    DialPlanCallTypePage.getAndDeleteAllDialPlanCallTypes()
  })

  beforeEach(function () {

    cy.fixture(Cypress.env('fixtureFile')).then((data) => {
      this.data = data
[HTML_20Report (4).zip](https://github.com/cypress-io/cypress/files/6156443/HTML_20Report.4.zip)

https://user-images.githubusercontent.com/45853972/111469642-be000700-8748-11eb-8d6f-58d6083990a0.mp4

    })

**Comment by sardar-usman** [comment]
@jennifer-shehane  - Can you please review this issue.

**Comment by sardar-usman** [comment]
@jennifer-shehane

**Comment by sardar-usman** [comment]
@brian-mann

**Comment by redReno** [comment]
I have a similar issue. After upgrading the Cypress docker/included image from 6.6.0 to 6.8.0 all tests are slower across the board. In particular we have tests using Chrome, where some commands take a long time. Especially visit and xhr requests, but all network communication seems slower than usual. Some test suites are 10% slower, others up to 40-50% slower.
