### ISSUE TITLE
cy.intercept on Request Interferes with Normal Operation of the Application Being Tested

### ISSUE THREAD

**Issue by todd-m-kemp** [cypress-io/cypress#15548]
### Current behavior

Use of `cy.intercept` is causing some unexpected behaviour in the application I am trying to test, but the application behaves just fine using `cy.server`/`cy.route` or when you don't use either one.

### Desired behavior

`cy.intercept` does not interfere with regular operation of the application under test.

### Steps to reproduce

_Note that manual steps are required to visualize this problem; please follow the steps as written. Simply running the test code below will *not* result in a failed test._

(1) Sign up for a Vidyard account (for free) [here](https://www.vidyard.com/), verify your email address, and then update the values of `email` and `password` in the test code below accordingly.

(2) Run the following test code. (Note that only the test using `cy.intercept` is being run; I've provided the version using `cy.route` for convenience.)

```
context('Cypress', function () {
  beforeEach(function () {
    // These are not real credentials.
    // Please sign up (for free) at www.vidyard.com, verify your email address, then update these accordingly.

    const email = 'yourAccount@fake.com';
    const password = 'yourPassword';

    cy.visit('https://secure.vidyard.com/user/sign_in');
    cy.get('#username').type(email);
    cy.get('#password').type(password);
    cy.get('#sign-in').click();
    cy.wait(5000); // Just to make sure the page is fully loaded.
  });

  it.only('Using intercept', function () {
    cy.intercept('PUT', 'https://vidyard.s3-accelerate.amazonaws.com/uploads/videos/**');
  });

  it('Using route', function () {
    cy.server();
    cy.route('PUT', 'https://vidyard.s3-accelerate.amazonaws.com/uploads/videos/**');
  });

  it('Using nothing at all', function () {

  });
});
```

(3) After the test has run, drag-and-drop a video file onto the application in the browser window. (I've attached a short video file for your convenience.)

https://user-images.githubusercontent.com/62152998/111535361-66a96900-873f-11eb-8c5a-3c99171249e1.mp4

(4) Wait for the video to upload and appear in your Video Library.

### Issue

The video is not properly added to your Video Library. You should see a thumbnail image representative of the video in the Library, but instead you see a black rectangle.

![image](https://user-images.githubusercontent.com/62152998/111536333-7f664e80-8740-11eb-8069-585740a0e7d7.png)

Looking at the most recent call to `/organizations/759619/graphql` sheds some light on why we see a broken thumbnail in the page. In the response to that request we see that `data.playableItems.folder.search.nodes.0.status` (which will be the video you just attempted to upload) is `failed` when it should be `ready`.

![image](https://user-images.githubusercontent.com/62152998/111537574-ff40e880-8741-11eb-9a79-9304dde5714c.png)

### Additional Notes

This is a strange problem and I certainly would not have expected it to be caused by `cy.intercept`, but if you repeat these steps instead running the equivalent test that uses `cy.route` or the test that calls neither `cy.route` nor `cy.intercept`, _then there is no problem at all_. Something about `cy.intercept` is interfering with the normal operation of the application. 😮 

We've begun migrating our Cypress code to use `cy.intercept` so that we will be be able to keep upgrading Cypress versions when `cy.route` is no longer available for use but obviously this problem will be a blocker to that.

Please let me know if there is more information I can provide or if you have any questions!

### Versions

Cypress 6.6.0 on macOS 10.15.7 with Chrome 89, Firefox 86, and Electron 87.

**Comment by todd-m-kemp** [comment]
@jennifer-shehane : Sorry to be a bother but it would be possible to get a comment on this? We've migrated the majority of our entire test suite to use `cy.intercept` but this issue blocks us from ceasing to use `cy.route` completely. I'd love to get confirmation that this is a Cypress issue that we can expect a fix for in a future release. Thanks!

**Comment by bahmutov** [comment]
`cy.intercept` now can spy on binary uploads / downloads, but it was broken, and will be fixed in Cypress v7 release, see https://github.com/cypress-io/cypress/issues/15038

**Comment by todd-m-kemp** [comment]
Thank you so much @bahmutov ! I had not seen that issue; that certainly seems to explain what we're seeing with our tests as well. Appreciate it.
