### ISSUE TITLE
Could @react/cypress please add support for webpack@5.x?

### ISSUE THREAD

**Issue by glomotion** [cypress-io/cypress#15569]
### What would you like?

Support for Webpack 5.x. It's been out for a while now, and shouldn't be too hard to support. 

The @cypress/react dev deps require "webpack": "4.44.1", but peer deps require "webpack": "^=3.x" - could this plz be upgraded? 🤔 

### Why is this needed?

We are working in a project already using webpack@5.x. Downgrading to webpack 3 is not an option. :(

**Comment by JessicaSachs** [comment]
We have support for webpack-v5 on a branch and have a PR open, but we're in the middle of releasing a rewrite of `@cypress/react` which has a better peerDependency design and will fix what you're talking about.

https://github.com/cypress-io/cypress/pull/8929

**Comment by glomotion** [comment]
@JessicaSachs thank you kindly for the update. 

A little background, ATM i'm trying to make a case for using @cypress/react inplace of jest/jsdom for my team, and these pesky dep errors are really hurting my case. 

I wonder, have you any timeline/roadmap for when these changes might be published?

**Comment by lmiller1990** [comment]
Hi @glomotion!

Cypress 7.x was just released, which includes our new component testing runner, marking the end of the experimental era for component testing.

- changelog: https://docs.cypress.io/guides/references/changelog#7-0-0
- intro to component testing runner: https://docs.cypress.io/guides/component-testing/introduction
- migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

Instead of using the `file:preprocessor` architecture, we moved to a dev server architecture, so now things are a (lot) faster. To actually verify webpack 5 is now working, I made a [super minimal setup](https://github.com/lmiller1990/cypress-react-webpack-5-example) with Babel + React + Webpack 5 + Cypress + `@cypress/react@5.x` and it seems to work just fine.

I am not sure of your exact set up, but if you are able to update to Cypress 7.x and the new dev server architecture + runner, you can use Webpack 5 (and all the other great things about the new component testing architecture).

**Comment by lmiller1990** [comment]
Hi @glomotion,

Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing


The main difference is we moved from a `file:preprocessor` architecture to a dev-server architecture. Component testing is no longer experimental, and has a dedicated runner (which is build on top of an extends the existing cypress runner).

The main benefits of the improved component testing runner and architecture are:

- things are now (much) faster
- no need to launch into the electron shell. It opens straight to the browser (select your spec from the inline spec selector)

Upgrading should not be too difficult, see the [migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing).

To make sure Webpack 5 is working, I made a minimal example with [Babel + Webpack 5 + React + Cypress 7.x + `@cypress/react@5.x`](https://github.com/lmiller1990/cypress-react-webpack-5-example) and it's working fine for me. Let us know if you are having problems upgrading.

**Comment by viraxslot** [comment]
@lmiller1990 I think problem is in node version. I've got the same error on v15 (event for your repository). LTS version of nodejs works just fine.

**Comment by lmiller1990** [comment]
I am node 14, I have not tried node 15 yet, but I will give this a try. Webpack 5 support is there, so I will close this. If we find an issue with node 15, let's triage and fix that in another issue.

**Comment by lmiller1990** [comment]
My repo worked fine for me with node 15 - what error are you getting @viraxslot?

**Comment by viraxslot** [comment]
@lmiller1990 here is the error
```
viraxslot@ip-192-168-2-92 cypress-react-webpack-5-example [master] $ git pull
Already up to date.
viraxslot@ip-192-168-2-92 cypress-react-webpack-5-example [master] $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
viraxslot@ip-192-168-2-92 cypress-react-webpack-5-example [master] $ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: webpack-dev-server@3.11.2
npm ERR! node_modules/webpack-dev-server
npm ERR!   dev webpack-dev-server@"^3.11.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack-dev-server@">=4" from @cypress/webpack-dev-server@1.1.1
npm ERR! node_modules/@cypress/webpack-dev-server
npm ERR!   dev @cypress/webpack-dev-server@"^1.1.1" from the root project
npm ERR!   peerOptional @cypress/webpack-dev-server@"*" from @cypress/react@5.3.2
npm ERR!   node_modules/@cypress/react
npm ERR!     dev @cypress/react@"^5.3.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/viraxslot/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/viraxslot/.npm/_logs/2021-04-09T10_32_46_572Z-debug.log
viraxslot@ip-192-168-2-92 cypress-react-webpack-5-example [master] $ node -v
v15.8.0
```

If change node version to LTS via nvm everything works fine as I mentioned.

**Comment by lmiller1990** [comment]
Thanks, can take a look into this one. It probably is not the highest priority, so I can't promise anything in the immediate future but definitely will keep this in mind. Looks like a dependency problem.
