### ISSUE TITLE
Progress logging firing too frequently

### ISSUE THREAD

**Issue by haroldtreen** [cypress-io/cypress#1557]
- Operating System: Mac OSX - 10.13.1
- Cypress Version: v2.1.0
- Browser Version: N/A

### Is this a Feature or Bug?

Bug

### Current behavior:

When I run:

```
npm install cypress
```

The progress is being printed out way more frequently than needed. 
It prints every time a progress event is dispatched from the download/unzip vs. every time there's meaningful progress.

### Desired behavior:

The code for printing progress updates should only fire if the progress/time changes, not on every progress event.

### How to reproduce:

This issue is most visible when using something like docker that doesn't let lines be overwritten in the output. 
I have a dockerfile with:

```
FROM cypress/base:8
RUN npm i cypress
```

Then when building:

```
docker build Dockerfile
```

The output is very spammy with the excessive updates. 

![image](https://user-images.githubusercontent.com/1745854/38525097-02a3c9d2-3c1f-11e8-95dd-c6066aab173c.png)

All those lines are the same, so printing them over and over is unnecessary. 

### Additional Info (images, stack traces, etc)

I believe the code responsible is here: 

https://github.com/cypress-io/cypress/blob/3a538601e117947c9632a5263633caf7a139ac98/cli/lib/tasks/install.js#L74-L88
https://github.com/cypress-io/cypress/blob/3a538601e117947c9632a5263633caf7a139ac98/cli/lib/tasks/install.js#L123

I think `progressify` could store a local copy of the last progress/remaining and only print when they change? Or maybe my debugging is off...

**Comment by jennifer-shehane** [comment]
Duplicate: https://github.com/cypress-io/cypress/issues/1243
See workaround: https://github.com/cypress-io/cypress/issues/1243#issuecomment-365560861

**Comment by jennifer-shehane** [comment]
If you want to open a PR that is WIP, we are welcome to that though - just reference it in the duplicate issue. Thanks!

**Comment by haroldtreen** [comment]
Whooops! My searching wasn't good enough obviously - sorry for the dup! 
Thanks for the link + quick reply!

**Comment by mbana** [comment]
Insane. Why not default to not producing sooooo much output unless a flag is passed.
Also, what happens someone has `cypress` already in their `package.json` file? Does `CI=true` still work?

Thanks,

@jennifer-shehane
