### ISSUE TITLE
Till when we are  expecting cypress release for mobile apps automation for React Native

### ISSUE THREAD

**Issue by abdullahsohailyaqoob** [cypress-io/cypress#15580]
Hi Cypress family, i developed frontend automation framework in my company in cypress for automation of web applications. Now we want automation for mobile apps as well. Our applications are developed in react native. How long will cypress family takes to  give its mobile release of cypress.

Looking Forward

**Comment by jennifer-shehane** [comment]
We are currently evaluating the requests and effort to support mobile application development. We don't currently have an estimate on when this feature would be delivered.
