### ISSUE TITLE
cy.request is not working in the pipeline even though the logs shows that the request is successful

### ISSUE THREAD

**Issue by SDAdham** [cypress-io/cypress#15590]
Hello, there is a bug where `cy.request` works in local but fails in the pipeline, have anyone came across similar issue? It fails when trying to collect `__coverage__` reports, so I made sure that the request is actually made rather than timing out as it's logged, by making the api to log that coverage request been made and it will respond and it is doing that just fine, so I know the request is successful but on `cy.request`, it's reporting failing.

Cypress version: `6.8.0` and previous version too.
Platform: Linux (pipeline), Windows (local dev environment)

**Comment by jennifer-shehane** [comment]
I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Perhaps look into opening an issue in the code-coverage repo if it is purely related to that plugin. 

Otherwise, we'll need a reproducible example to investigate. We'll have to close this issue until we can reproduce it.

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by valeria-chernikova** [comment]
@SDAdham, I have the same problem. Could you share your solution, please?

**Comment by SDAdham** [comment]
@valeria-chernikova , we stopped using Cypress because of the discrepancies between different OS and browser versions, sadly we experienced a major issues in matching the following:

- Pipelines run in Linux environment meanwhile we cannot force all of our developers to use pipeline's OS.
- We have to disable dev environment when running local to write test cases, meanwhile we need the prod environment enabled on pipelines before delivery.
  - The errors we see on production meanwhile not in dev, and vice versa that happens at randomness but reviewing recordings and screenshots, we could see no issues there, it's just random weird errors that sometimes it works and sometimes not, it just simply doesn't (really unexplained randomness) like:
    - request works but Cypress fails to get a response, or;
    - html elements get de-attached
   - And the interesting thing is we could see in the recordings it's there, it's working!
   - We would fix the errors we see in pipeline but then it happens on local! And if we fix local, it would happen on pipelines! It's like playing with Tom and Jerry here!
- Some of our devs are using Windows meanwhile the pipelines run in Linux (this causes issues even though it should be the same browser (but maybe different version?) - same problem as above)
  - Maintaining same browser used during development as the same browser version in pipelines is not easy.
- Maintaining test cases costs heavy investments of our time with Cypress, we end-up troubleshoot Cypress more than we troubleshoot our own code.
- And our test cases for Cypress can run for as long as 4 hours (without parallelisation) - so waiting to get a feedback on Cypress with the issues mentioned above is really a nightmare, make 1-2 changes per day to fix a discrepancy issue.

With above said, we didn't really give up on Cypress completely, it's amazing library and we really wish it would work for us. At some point in the future, here is our plans after heavy experience with Cypress, here are our to-do list:

- Configure and run Cypress in Docker (same image as Pipelines rather than allowing developers to run tests on their local machine's direct browsers and OS - but this will take away the visual aspect which is the core beauty of Cypress, however, they would still have the recordings as we believe), and;
- We will try to use **Parallelisation** but unfortunately, this requires a paid service https://www.cypress.io/pricing
