### ISSUE TITLE
Summary output should include number of skipped tests

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1559]
We show passed, failed, pending, and need to add skipped.

**Comment by jennifer-shehane** [comment]
I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document what defines a test as `pending` and `skipped` here: https://github.com/cypress-io/cypress-documentation/issues/593. Our documentation is open source and contributions are welcome. 😄

Relevant conversation: https://github.com/cypress-io/cypress/pull/1718#pullrequestreview-119975003
