### ISSUE TITLE
dispatching an event on a parent element will change the event target to child element

### ISSUE THREAD

**Issue by Damith88** [cypress-io/cypress#15607]
### Current behavior
dispatching an event on a parent element will change the event target to child element

### Desired behavior
dispatching an event on a parent element should NOT change the event target to child element. target should be the same element we trigger the event.

### Test code to reproduce
```html
<div id="parentDiv" draggable="true" style="width: fit-content;">
<span id="childSpan">My Div</span>
</div>
```

```js
cy.get('#parentDiv').trigger('dragstart', { eventConstructor: 'DragEvent' });
```

attach an event listener for drag event and observe the event target

### Versions

6.7.1

**Comment by jennifer-shehane** [comment]
@Damith88 Please provide the full JS code to run, including the event listener for the drag event. Thanks!

**Comment by Damith88** [comment]
below is the html page I want to test.

```
<div id="myDiv" draggable="true" style="width: fit-content;"><span id="mySpan">My Div</span></div>
 
<script>
$( document ).on('dragstart', function(ev) {
  console.log('actual event target:', ev.target); // this should be 'myDiv' instead of 'mySpan'
});

</script>
```

test code.
```
it('test drag', function () {
      cy.visit('./drag.html');
      cy.get('#myDiv')
      .then( $draggable => console.log('Event triggered on: ', $draggable.get(0)))
      .trigger('dragstart', { eventConstructor: 'DragEvent' });
    })
```

when interacting with the page manually event target is correctly set to parent element.

**Comment by Damith88** [comment]
instead of triggering the dragstart event from cypress I could get it working when I trigger the event with plain javascript.
```
cy.get('#myDiv')
      .then( $draggable => {
        $draggable.get(0).dispatchEvent(new DragEvent('dragstart', { dataTransfer: new DataTransfer(), bubbles: true}));
      })
```
