### ISSUE TITLE
Tailwind classes throw syntax errors

### ISSUE THREAD

**Issue by ianwijma** [cypress-io/cypress#15603]
### Current behavior
Using a tailwind class with a `/` causes syntax errors.

Example: `cy.get('.w-1/2')`

Ref: https://tailwindcss.com/docs/width#class-reference

### Desired behavior
No syntax error, because its a valid css class

### Test code to reproduce
```js
/// <reference types="cypress" />

describe('page', () => {
  it('works', () => {
    cy.visit('https://tailwindcss.com/docs/width#class-reference')
    cy.get('.top-0')
  })
  it('breaks', () => {
    cy.visit('https://tailwindcss.com/docs/width#class-reference')
    cy.get('.top-1/2')
  })
})
```

Repo: https://github.com/ianwijma/cypress-test-tiny/tree/tailwind-classes
Spec with breaking get: https://github.com/ianwijma/cypress-test-tiny/blob/tailwind-classes/cypress/integration/spec.js

### Versions

cypress@6.8.0

### Workaround

I've changed my clickable items to contain `[data-cy='<name>']` for my current project. But future projects might be too big to do this.

**Comment by sainthkh** [comment]
`cy.get()` internally uses jQuery selector engine. When CSS characters like `/` is used inside it, we need to escape it with `//`. [Please check this doc](https://docs.cypress.io/api/commands/get#Find-the-element-with-id-that-has-characters-used-in-CSS-like)
