### ISSUE TITLE
Cypress run shows all data of package.json

### ISSUE THREAD

**Issue by mmonteiroc** [cypress-io/cypress#15610]
### Current behavior
When running cypress run in headless mode, the terminal displays a lot of information including all package.json
![image](https://user-images.githubusercontent.com/28816737/111992390-a98b8800-8b15-11eb-9202-c80861aeb155.png)

### Desired behavior
This didn't use to happen before changing to version 6.7.1

### Test code to reproduce
Cannot give you the tests as its confidential, even I have done the getting started and with a simple tests trying to get a simple element of the page and clicking, still give the same error in console
### Versions

Happens on version 6.7.1

**Comment by jennifer-shehane** [comment]
Please update to the most recent version of Cypress. This was fixed in 6.8.0 https://docs.cypress.io/guides/references/changelog.html#6-8-0

**Comment by mmonteiroc** [comment]
I tried, works fine thanks ! I open the issue as in the changelog, doesnt appear a description of this bugfix :) Thanks againg

**Comment by jennifer-shehane** [comment]
Oh, right. This should have been fixed in 6.7.1 actually, that's where it's referenced in the changelog. 🤔

**Comment by mmonteiroc** [comment]
Strange.... As in the issue said, this was happening when upgrading to 6.7.1, and now works in 6.8.0

I cannot see that reference in the changelog for 6.7.1. Anyways, this is fixed from 6.7.1 to 6.8.0 so maybe you could update the changelog of 6.8.0 ? so future devs will see it easier and no need to create an issue like me ;)

Thanks again for your feedback
