### ISSUE TITLE
cy.get("@cred") times out with error: $result.find is not a function

### ISSUE THREAD

**Issue by petermartin2002** [cypress-io/cypress#15614]
**Current behavior:**

When I wrap and alias the result of a jQuery to use later I get "$result.find is not a function" 

When outputting the yielded contents to console.log it displays as:

`Yielded:  
{length: 1, jquery: "3.1.1", log: true}
jquery: "3.1.1"
length: 1
log: true
__proto__: Object`
![image](https://user-images.githubusercontent.com/13946993/112011064-cc229e80-8b1f-11eb-8918-af4f0206ccd2.png)
![image](https://user-images.githubusercontent.com/13946993/112011394-258acd80-8b20-11eb-8e7e-d2d5af810852.png)

NB it appears to wrap as opposed to get the alias?

**Code to reproduce**

```js
Then(
  "I can see the {string} Credential for an {string}",
  ($status, $credential) => {

    cy.get("@getPath").then(($result) => {
      cy.wrap(
        Cypress.$($result.allRequestResponses[0]["Response Body"])
          .find("table[id='tableID']:first")
          //filtering out td that do not meet criteria
          .find("tbody tr td")
          .filter(function () {
            return Cypress.$(this).text().includes($status);
          })
          .siblings()
          .filter(function () {
            return Cypress.$(this).text().includes($credential);
          })
          .parent()
      ).as("cred");
    });

    cy.get("@cred").then(($result) => {
      //Issue occurs here
      expect($result.find("td:eq(0)").text()).to.contain($credential);
    });
  }
);


```
![image](https://user-images.githubusercontent.com/13946993/112010851-95e51f00-8b1f-11eb-9518-db92472cc465.png)

However when we use it we get:
![image](https://user-images.githubusercontent.com/13946993/112011064-cc229e80-8b1f-11eb-8918-af4f0206ccd2.png)

**Versions**

Cypress  6.5.0 /6.6.0 /  6.8.0

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. 

I can't recreate this same situation in our latest version with the code below. We would need the full example - with HTML to recreate.

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('div').as('cred')
  cy.get("@cred").then(($result) => {
    expect($result.find("p").text()).to.contain('Hello')
  })
})
```

```html
<html>
<body>
  <div>
   <p>Hello</p>
  </div>
</body>
</html>
```

<img width="499" alt="Screen Shot 2021-03-22 at 12 59 59 PM" src="https://user-images.githubusercontent.com/1271364/112028442-8c9f8680-8b0e-11eb-9462-4b5cf78fdfa0.png">

**Comment by petermartin2002** [comment]
Hi @jennifer-shehane  I am using 6/8.0 my apologies I input the wrong version

Try with the following html: 

`
<html>
<body>
<table id="certificationTable">
<thead>
<tr>
<th>Level</th>
<th>Type</th>
<th>Initial Date</th>
<th>Expiration Date</th>
<th>Status</th>
</tr></thead>
<tbody>
<tr>
<td>
					Technician
    		</td>
<td>
				Initial
    		</td>
<td>
				03/22/2021
    		</td>
<td>
				03/12/2025
    		</td>
<td>
				Active
    		</td></tr></tbody></table> 
</body>
</html>
`
