### ISSUE TITLE
property 'findByRole' does not exist on type 'cy & EventEmitter' - switching to .ts from .js makes custom commands and testing-library commands unrecognisable

### ISSUE THREAD

**Issue by dominikabieder** [cypress-io/cypress#15615]
### Current behavior
Custom commands and commands from testing library are not recognisable after switching the test file extension from .js to .ts. Even plugins>index.ts is underlined, because it's not index.js. Cypress executes with both extensions ok. So it's just IDE problem? I'm using Webstorm. Everything works fine the moment I switch back to test.js.

<img width="673" alt="Screenshot 2021-03-22 at 16 18 45" src="https://user-images.githubusercontent.com/31188583/112020567-bec1e000-8b30-11eb-95df-571b11a43b89.png">

My folder structure:

```
test > 
  cypress >
    acceptance
    fixtures
    plugins > 
      index.ts
    support >
      commands.js
      index.ts > 
        index.d.ts
```

Here's my tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "baseUrl": "src",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "types": [
      "cypress",
      "cypress-file-upload",
      "@types/testing-library__cypress"
    ]
  },
  "include": [
    "src",
    "**/*.ts"
  ]
}
```

Here's the content of index.d.ts
```
/// <reference types="cypress" />

declare namespace Cypress {
  interface Chainable<Subject> {
    /**
     * Logs a BDD Given statement
     * @example
     * cy.given('I open the user list')
     */
    Given(title: string): Chainable<any>;

    /**
     * Logs a BDD When statement
     * @example
     * cy.when('I create a user')
     */
    When(title: string): Chainable<any>;

    /**
     * Logs a BDD Then statement
     * @example
     * cy.then('I see a user')
     */
    Then(title: string): Chainable<any>;

    /**
     * Logs a BDD And statement
     * @example
     * cy.and('I see an updated user count')
     */
    And(title: string): Chainable<any>;

    /**
     * Logs a BDD Finally statement
     * @example
     * cy.finally('I delete the user again')
     */
    Finally(title: string): Chainable<any>;
  }
}

```

**Comment by jennifer-shehane** [comment]
The `findByRole` command is not a Cypress command and does not come shipped with Cypress, so we are not going to include types for an outside plugin outside of our control. 

You can write your own typings for custom commands as explained here: https://on.cypress.io/typescript-support#Types-for-custom-commands or open an issue with the testing-library plugin for their types.

**Comment by dominikabieder** [comment]
but it's not just about that, every custom command is not recognised either by my IDE

**Comment by amraks** [comment]
having the same issue. using vscode. findBy* methods unrecognized.

**Comment by nbotond20** [comment]
Also use this `/// <reference types="@testing-library/cypress" />`. This should solve the issue

**Comment by paolooo** [comment]
You can try this one also. This solves my issue:

**tsconfig.ts**

```json
{
   ...
   "types": [
       "cypress",
       "@testing-library/cypress"
   ],
   ...
   "include": [
        ...
        "./cypress/**/*"
   ]
}
```

Reference:
https://testing-library.com/docs/cypress-testing-library/intro/#with-typescript
