### ISSUE TITLE
cy.intercept or cy.route does not intercept URLs with %

### ISSUE THREAD

**Issue by hpyou** [cypress-io/cypress#15627]
### Current behavior
cy.route('get', '/xxxx/yyyy?zzz=dfr%fff').as('request_1');

and then

cy.wait('@request_1',  {timeout: 10000})

throw error:
 CypressError: Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `request_1`. No request ever occurred.

### Desired behavior

want intercept url with %

### Versions

v6.3.0

**Comment by herecydev** [comment]
It might need to be url encoded, what happens if you do `cy.route('get', '/xxxx/yyyy?zzz=dfr%25fff').as('request_1');`?

**Comment by hpyou** [comment]
@herecydev ok, it works
