### ISSUE TITLE
Test hangs on retry

### ISSUE THREAD

**Issue by julianmendonca** [cypress-io/cypress#15622]
### Current behavior

Currently i have a cron job runing tests continusly, and sometimes (like onces per day) the tests hangs in a retry and never continues to the next test. (Seems to be hanging in a xhr request but i am not sure)

It seems to be hanging on xhr requests in the "after" event

### Desired behavior

Run all the tests without hanging, or find a way to set a timeout for this case.

### Test code to reproduce

https://github.com/julianmendonca/cypressError

I created this repo so you can test it, it is a cron job that runs 24/7. It doesen't hang on every run, so if you can clone de repo and do "node runCommand.js" it will run 24/7. In the runCommand.js file you can specify at what time it should run the test, so you can configure it in there.

These are some screenshots from the last hang event, the error on the iframe that should show the web page isn't allways like this, it shows the actual page usually

![image](https://user-images.githubusercontent.com/31936866/112047804-7b657280-8b2c-11eb-8a6a-3e48194b595d.png)

### Versions

I use "npx cypress run --browser chrome" so it should be using allways last, but it actually uses 6.8.0

Thank you in advance for the help :)

**Comment by jennifer-shehane** [comment]
You may have exposed some sensitive information in the first screenshot. You may want to delete that from the comments and delete from the comment history.

**Comment by julianmendonca** [comment]
> You may have exposed some sensitive information in the first screenshot. You may want to delete that from the comments and delete from the comment history.

I didn´t realize, thank you! i upload a screenshot without that information, the last requests keeps on repeating every few minutes (i dont know if that is relevant)

**Comment by julianmendonca** [comment]
@jennifer-shehane Did you have a chance to test the code? let me know if you have any trouble running it.
Thank you in advance :)

**Comment by julianmendonca** [comment]
I deleted the repo from the issue, it seems that i figured out the problem. I was working with Iframes DOMs and it seemed that it made the test hang for some reason.

The Method:

Cypress.Commands.add("checkGondolaIframe", (id) => {
  cy.get("#" + id).then(($iframe) => {
    cy.wait(3000);
    cy.get("#" + id).then(($iframe2) => {
      const $body2 = $iframe2.contents().find("body");
      cy.wrap($body2).find(".owl-item").should("exist");
    });
  });
});

I make a first cy.get to check if the iframe loaded, then wait 3 seconds to let it set the dom correctly (in my case all these iframes have a GET request and then render content) and then get the iframe again.

Hope this helps someone :)

**Comment by julianmendonca** [comment]
@jennifer-shehane I reopened the issue because the changed i commented above hasn't solve the problem.
Thank you in advance :)

**Comment by AndyReiblein** [comment]
Has this issue been resolved ? I have test that I wrote a week ago and they were working fine at the time. Ran them for the first time since then today and I am having the same issue. The test hangs as soon as I load the Iframe.
