### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by Mouvedia** [cypress-io/cypress#1564]
> [No IE support is planned. It is substantially more difficult.](https://github.com/cypress-io/cypress/issues/310#issuecomment-337349727)

### Is this a Feature or Bug?

It is a feature request from a maintainer perspective but a bug for the client.

### Current behavior:

It doesn't support IE.

### Desired behavior:

It should.

### Bountysource

https://www.bountysource.com/issues/56930685-ie11-support

**Comment by jrsinclair** [comment]
This would be incredibly helpful. But I understand that it's also incredibly difficult.

**Comment by kunwardeep** [comment]
Another ray of hope. Maybe no longer need to support Edge https://www.windowscentral.com/microsoft-building-chromium-powered-web-browser-windows-10

**Comment by jpike88** [comment]
"interest in IE11 support" is driven by users, not developers. We have to support IE11, or a great deal of our customers wouldn't even touch us. Time and time again cypress has failed to notice things that pop up in only IE11, and I can't do this anymore.

Can someone recommend an alternative to cypress which takes into account IE11?

**Comment by jennifer-shehane** [comment]
For more detailed issue tracking, check the progress on this issue: https://github.com/cypress-io/cypress/issues/3207

**Comment by anton-dealmeida** [comment]
Definitely need Cypress to support IE

**Comment by infomaven** [comment]
Any updates on this? It appears that many of our clients still use IE11.

**Comment by Mouvedia** [comment]
#5224 would close this

**Comment by amirrustam** [comment]
Closing in favor of #6423
