### ISSUE TITLE
Stubbing window.open doesn't work with redirects

### ISSUE THREAD

**Issue by Koenshi** [cypress-io/cypress#15654]
I am working with Cypress, and I have a test with the following flow:

1. Cypress gets a button and clicks it, which submits a form
2. Form redirects to a "loading" url, which then redirects to another url
3. On the last page, there is a single line of inline JavaScript:
```javascript
window.open("https://mockurl.com/", "_blank", "menubar=no,status=no");
```
4. This line opens a print dialog immediately on page load, so tests will hang until the dialog is manually closed.

I cannot seem to find a way to deal with this print dialog and prevent it from opening each time. I'm stubbing window.open like so:

```javascript
cy.visit('index.html', {
    onBeforeLoad: (win) => {
        cy.stub(win, 'open');
    }
})

cy.window().then(function (win) {
    cy.get('button').click()
    cy.contains('This is the last page').then(() => {
        expect(win.open).to.be.called
    })
})
```

### Current behavior

I get this error: `[Function: open] is not a spy or a call to a spy!`
The popup appears normally and the test process hangs until the dialog is manually closed.

<img width="400" alt="Screenshot 2021-03-25 at 13 16 10" src="https://user-images.githubusercontent.com/20304775/112465860-dcc85400-8d6d-11eb-9428-386fc6094be4.png">

### Desired behavior

Cypress should detect the popup, and it should not appear, allowing tests to continue running.

### Test code to reproduce

[Repo with sample code.](https://github.com/Koenshi/cypress-popup)
This includes an index.html with a button, which when clicked navigates to redirect.html, that after 2 seconds navigates to info.html. This last page, info.html, has the inline javascript that opens popup.html.

### Versions

Cypress 6.8.0
Chrome 89
MacOS Big Sur 11.2.3

**Comment by bahmutov** [comment]
Every page load creates a new `window` object. You only stub the first visit window, thus the second page visit creates a new `window` object, without your stub. See all answers to your question in https://glebbahmutov.com/blog/stub-window-open/ but in general

```js
// ✅ CORRECT SOLUTION
it('opens a new window', () => {
  // create a single stub we will use
  const stub = cy.stub().as('open')
  cy.on('window:before:load', (win) => {
    cy.stub(win, 'open').callsFake(stub)
  })

  cy.visit('/')
  // triggers the application to call window.open
  cy.click('Open new window')
  cy.get('@open').should('have.been.calledOnce')

  // cause the window to be recreated
  cy.reload()
  cy.click('Open new window')
  // all window.open calls are correctly forwarded to our stub
  cy.get('@open').should('have.been.calledTwice')
})
```

**Comment by seb-thomas** [comment]
Does anyone know how to assert the args `@open` is called with? I have tried loads of variations of `cy.get("@open").should("have.been.calledOnceWith", url);`  but keep getting 

```

Assertion error: 

The following calls were made:

    open("www.google.com", "_self")
```

thnx

**Comment by bahmutov** [comment]
@seb-thomas you are commenting on a closed issue which might not get any attention, but here is an example checking the call arguments, maybe it would be useful https://github.com/bahmutov/cypress-examples/pull/104/files
