### ISSUE TITLE
Tests fail because of exception in console

### ISSUE THREAD

**Issue by Gennadiii** [cypress-io/cypress#1565]
- Operating System: Win10
- Cypress Version: 1.4.2
- Browser Version: Chrome 65

### Is this a Feature or Bug?
This is a bug

### Current behavior:
I have exception on my app, I can see it in console: Uncaught TypeError: Cannot read property 'lastChild' of null
And I don't care about it actually. But Cypress fails tests because of it.

### Desired behavior:
I`d like to ignore such kind of errors since they don't influence the flow I need to test

**Comment by jennifer-shehane** [comment]
You can turn these off, as detailed here: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by Gennadiii** [comment]
@jennifer-shehane This would skip all the errors of some type. For example now I have error TypeError which is an error of the app and not tests. If I have this type of error in my tests I`d miss it, right?

**Comment by jennifer-shehane** [comment]
This should definitely work if the error is originating from your application. Could you provide more details about the `Uncaught TypeError`?
- Screenshots
- Your `support/index.js` code

**Comment by vjpr** [comment]
Same problem here...

**Comment by muslaydin** [comment]
Same problem

**Comment by gpcavalcante** [comment]
Same problem
