### ISSUE TITLE
Testing runs fine, but when the testing completes instead of exiting cleanly, it throws an npm ERR! Exit status 66

### ISSUE THREAD

**Issue by RahulAggarwal-V31848** [cypress-io/cypress#15657]
We are running Cypress testing as part of an Azure DevOps pipeline on a Linux VM.  Testing runs fine, but when the testing completes instead of exiting cleanly, it throws an npm ERR! Exit status 66.  This is causing the ADO to report the step as a failure even if all the tests pass, which would cause the stage to fail if we didn’t code it to ignore errors.  Setting it to ignore errors defeats the purpose of running the tests however, which is to be sure we haven’t introduced any real failures into the code base.

We are running a standard set of Cypress commands:

```
- script: npm run serve & ./node_modules/wait-on/bin/wait-on http://localhost:4200 & cypress run --headless --spec cypress/integration/apps/my-app/__my-app.features
 displayName: Running tests
        continueOnError: true
        timeoutInMinutes: 45
```

The output when the test completes is:
```
npm ERR! code ELIFECYCLE 
npm ERR! errno 66 
npm ERR! myApp@0.0.0 cy:deploy: `cypress run --headless --spec cypress/integration/apps/my-app/__my-app.features` 
npm ERR! Exit status 66 
npm ERR! 
npm ERR! Failed at the myApp@0.0.0 cy:deploy script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
npm ERR! A complete log of this run can be found in: 
npm ERR! /home/azbuild-user/.npm/_logs/2021-03-23T20_42_48_036Z-debug.log 
##[debug]Exit code 66 received from tool '/usr/bin/bash' 
The STDIO streams did not close within 10 seconds of the exit event from process '/usr/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited. 
##[debug]The STDIO streams did not close within 10 seconds of the exit event from process '/usr/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited. 
##[error]Bash exited with code '66'. 
##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '66'. 
##[debug]task result: Failed 
##[debug]Processed: ##vso[task.complete result=Failed;done=true;] 
##[debug]The task was marked as "done", but the process has not closed after 5 seconds. Treating the task as complete. 
```
Looking at a tail of the debug log gives us:
```
0 info it worked if it ends with ok 
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'cy:deploy' ] 
2 info using npm@6.14.11 
3 info using node@v14.16.0 
4 verbose run-script [ 'precy:deploy', 'cy:deploy', 'postcy:deploy' ] 
5 info lifecycle myApp@0.0.0~precy:deploy: myApp@0.0.0 
6 info lifecycle myApp@0.0.0~cy:deploy: myApp@0.0.0 
7 verbose lifecycle myApp@0.0.0~cy:deploy: unsafe-perm in lifecycle true 
8 verbose lifecycle myApp@0.0.0~cy:deploy: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/azbuild-user/Agent11U3A/_work/6/s/node_modules/.bin:/usr/local/git/bin:/usr/share/centrifydc/bin:/opt/rh/rh-dotnet31/root/usr/bin:/opt/rh/rh-dotnet31/root/usr/sbin:/usr/local/git/bin:/usr/share/centrifydc/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/root/.dotnet/tools 
9 verbose lifecycle myApp@0.0.0~cy:deploy: CWD: /home/azbuild-user/Agent11U3A/_work/6/s 
10 silly lifecycle myApp@0.0.0~cy:deploy: Args: [ 
10 silly lifecycle '-c', 
10 silly lifecycle 'cypress run --headless --spec cypress/integration/apps/my-myApp/__my-myApp.features' 
10 silly lifecycle ] 
11 silly lifecycle myApp@0.0.0~cy:deploy: Returned: code: 66 signal: null 
12 info lifecycle myApp@0.0.0~cy:deploy: Failed to exec cy:deploy script 
13 verbose stack Error: myApp@0.0.0 cy:deploy: `cypress run --headless --spec cypress/integration/apps/my-myApp/__my-myApp.features` 
13 verbose stack Exit status 66 
13 verbose stack at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16) 
13 verbose stack at EventEmitter.emit (events.js:315:20) 
13 verbose stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14) 
13 verbose stack at ChildProcess.emit (events.js:315:20) 
```
We have run various versions of Cypress but are currently using 6.5.0

**Comment by jennifer-shehane** [comment]
What was the results of the tests of this run? It should have passed with 0 failures?

**Comment by RahulAggarwal-V31848** [comment]
> What was the results of the tests of this run? It should have passed with 0 failures?

Hi Jennifer,

Thanks for the prompt response!  We are getting some failed tests, and yes I would expect that in this case the task would fail.  In reality that’s what I want.  However, I would think that it would fail with a standard error code like exit 1 and not throw a random NPM error as we are seeing.  

In examining some of our various runs I have discovered that the errno as seen here:

       Spec                                                                     Tests  Passing  Failing  Pending  Skipped  

   ✖  apps/myApp/__myApp.features          26:02      336      136       78      122                                                                           

    ✖  1 of 1 failed (100%)                            26:02      336      136       78      122        -  

npm ERR! code ELIFECYCLE
npm ERR! errno 78
npm ERR! aflac@0.0.0 cy:deploy: `cypress run --headless --spec cypress/integration/apps/myApp/__myApp features`
npm ERR! Exit status 78

Is actually the number of tests that failed during the run.  Because that number changes as tests are added, code is fixed, etc., when trying to automate it makes it difficult to determine if the task got the NPM error due to failed tests or if there was something actually wrong with process that caused it to die.
