### ISSUE TITLE
Hot reload does not work for app using ag-grid w/ stopEditingWhenGridLosesFocus on Chromium

### ISSUE THREAD

**Issue by LMFinney** [cypress-io/cypress#15675]
### Current behavior
I have an Angular app using @ag-grid-community v25.1.0 and Cypress v6.8.0. In the app is an ag-grid grid that uses the stopEditingWhenGridLosesFocus flag.

I have a Cypress test that asserts the initial values in the grid, changes two of the values using `type()` to new values with multiple characters, and then asserts that the values were correctly changed.

When the test runs initially, the test passes ("Prius" and "12345" are the new values).
![image](https://user-images.githubusercontent.com/6683747/112676209-267c7180-8e36-11eb-84fc-b3c2878f2adf.png)

However, after hot reload, by saving the test file while Cypress is already running, it types the full word 'in place', each character overwriting the former one, eventually only leaving the last character in the cell.
![image](https://user-images.githubusercontent.com/6683747/112676259-3431f700-8e36-11eb-9d1c-a9eb665e8a78.png)

I have confirmed this behavior on Electron 87, Chrome 89, and Edge 89.

This behavior does not happen on the initial run of the test, in real use, on Firefox 86, or with the stopEditingWhenGridLosesFocus flag turned off.

This seems to be the same general problem that was reported in https://github.com/cypress-io/cypress/issues/5394, but that was apparently fixed. I don't know if this demonstrates a regression, or if it was a previously-unknown corner case.

Note: in the proprietary repo in which this bug was first discovered, it also manifested by preventing a custom editor from being usable in the test. Presumably, edit mode is cancelled for the custom editor.

### Desired behavior
The test will pass after hot reload, just as it does on the initial run (see the first screenshot above).

### Test code to reproduce
I created a small repo that demonstrates the issue: https://github.com/LMFinney/cypress-ag-grid-bug-stopEditingWhenGridLosesFocus

Steps to reproduce:

1. Clone the repo.
2. Run `yarn` to install dependencies
3. Run `yarn e2e --watch` to run Cypress in watch mode.
4. See a successful running test (it loads a table of sample data, asserts the values, changes two of the values with text that has multiple characters, and asserts that the new values are accepted).
5. Make a trivial change to `app.spec.ts` (like adding a space at the end of a line).
6. See that the second run will fail (only the last characters of the new values will be visible).

### Versions

- Cypress 6.8.0 (unknown if it worked previously)
- Electron 87, Chrome 89, and Edge 89 (but not Firefox 86)
- Windows 10

**Comment by bn4z** [comment]
I had a similar case (using React) and the workaround with .focus suggested in #5394 did not work for me. In my case, I wanted to start the edition with a .click(). `.click().type('12345')` does what you describe but `.then(x => x.click()).type('12345')` works in all the cases: fresh start, hot reload in my IDE and Cypress run.
I would prefer to use a simple .click() but at least it's an acceptable workaround.
