### ISSUE TITLE
Not able to find elements within the body of iframe, getting Timed Out Error

### ISSUE THREAD

**Issue by sandyklh** [cypress-io/cypress#15676]
Hi , I am new to cypress , and i am stuck with using frames 

### Current behavior
i am trying to find an element within the iframe but could not find it. Giving error as Timed out after 8000s. Expected element not found. The concern is its not able to locate the item even after wrapping the body inside the frame. i am using the cypress-iframe plugin.
Trying to click on the button with frame id portalFrame

### Desired behavior
As per  expectations it should be able to click on button present within the  frame.

### Test code to reproduce

```js
  cy.frameLoaded('#portalFrame')
        cy.iframe().find('a[href*="cashlanding"]').eq(0).click({force: true})
        
        cy.iframe().find('a[href*="statementCredit.htm"]').click()
```

Error Msg:

Timed out retrying after 8000ms: Expected to find element: a[href*="statementCredit.htm"], but never found it. Queried from element: <body.pageBody.inside-iframe>
        
### Versions

Version: 6.8.0

HTML:

![image](https://user-images.githubusercontent.com/22787935/112686991-cb319a00-8e9c-11eb-89e0-f21a7047d353.png)

![image](https://user-images.githubusercontent.com/22787935/112686604-39299180-8e9c-11eb-9a86-a7177429b1ff.png)

**Comment by symon-skelly** [comment]
Hi @sandyklh, I've had problems with Iframes and cypress in the past. this is the solution I have been  using for months now and it works for any Iframe I've encountered so far:

```
const getIframeBody = (iframe) => {
    //gets the body of the iframe and wraps it in a cypress understandable object
    return cy
	.get(iframe, { log: false })
	    .its('0.contentDocument.body', { log: false }).should('not.be.empty')
	    .then((body) => cy.wrap(body, { log: false }))
}
```

**Usage:**

`getIframeBody('ifr_name')` //replace 'ifr_name' with your Iframe selector

**Comment by sandyklh** [comment]
@symon-skelly  i can get  to the  first frame  i.e. getIframeBody('#portalFrame').find('a[href*="cashlanding"]').eq(0).click()
 but on the next page i need to click on the highlighted element above i am  using getIframeBody('#portalFrame').find('a[href*="statementCredit.htm"]').eq(0).click() but again i am getting error 

as 

Timed out retrying after 8000ms: Expected to find element: a[href*="statementCredit.htm"], but never found it. Queried from element: <body.pageBody.inside-iframe>

![image](https://user-images.githubusercontent.com/22787935/113604855-77287180-9663-11eb-8d40-8e9f66e29f6f.png)

Please help!!!
Thanks in Advance!!
