### ISSUE TITLE
Screenshots sometimes don't render error text

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#1569]
### Current behavior: 

Screenshots sometimes don't render the error text. It shows the error box, but the text is invisible. This is because the font used for the error text (Open Sans) hasn't loaded yet

![screen shot 2018-04-11 at 3 21 53 pm](https://user-images.githubusercontent.com/1157043/38638435-3d5f1c38-3d9c-11e8-92af-58f9982a5ab3.png)

### Desired behavior:

The error text should be visible in the screenshot.

### Solution:

Pre-load the Open Sans font by using it elsewhere in the UI.

**Comment by bahmutov** [comment]
That’s such a good find!
