### ISSUE TITLE
Add {downarrow} and {upnarrow} to cy.type method

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#157]
Since you already have left and right arrow methods, it makes sense to add down and up so different UI widgets with a list of options can be tested quickly.

**Comment by brian-mann** [comment]
This is done and will be released with `0.16.2`.

We will not be able to move the cursor position - that requires a hefty amount of work and calculations and its unlikely anyone will be needing this anyway.

When we start firing native events we'll get this for free anyway so passing on that part now. We'll still fire all of the appropriate events so anything bound to these in javascript will work as you'd expect.

**Comment by brian-mann** [comment]
Fixed in [`0.16.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0162-06112016).

**Comment by Bkucera** [comment]
> We will not be able to move the cursor position - that requires a hefty amount of work and calculations and its unlikely anyone will be needing this anyway.

Moving the cursor up and down is enabled by PR #2016
