### ISSUE TITLE
Invalid snapshots css (decimal points replaced by comma)

### ISSUE THREAD

**Issue by aguingand** [cypress-io/cypress#1571]
The style in displayed snapshots seems to be "localized" which means all decimal points are replaced by comma (standard in France).
It only occurs with `link[href]` css, not with inline styles.

### Current behavior: 

_Rendered snapshot css_
```css
#test {
    ...
    opacity: 0,5;
    margin: 2,5rem;
}
```
<img width="1413" alt="capture d ecran 2018-04-12 a 17 51 20" src="https://user-images.githubusercontent.com/17453506/38688862-73cf97fa-3e7a-11e8-96e3-9eae018bd3a1.png">

### Desired behavior:

_Original css_
```css
#test {
    ...
    opacity: .5;
    margin: 2.5rem;
}
```
<img width="1413" alt="capture d ecran 2018-04-12 a 17 50 36" src="https://user-images.githubusercontent.com/17453506/38688847-677e1c92-3e7a-11e8-8096-2b114d3d9df1.png">

#### OS configuring (mac)
In _System preferences...._ > _Language & Region_
- Set _Français (France)_ as primary language ([explained here](https://support.apple.com/kb/PH25082?locale=en_GB&viewlocale=en_US))
- Select region : _France_
- Restart OS

#### Integration
Add  `<link rel="stylesheet" href="styles.css">` to a test page
Put some float numbers in the css (e.g `margin: 2.5rem`)
Run a test
Click on snapshot, and inspect the element

### Versions  

Cypress: 2.1
macOS 10.13.3
Chrome 65
**Locale: fr-FR**

_Edit : add configuring steps for mac_

**Comment by aguingand** [comment]
I've added configuring steps for mac (in _steps to reproduce_ section), **the issue is only happening when native locale is set to fr-FR**. I guess several other [countries are impacted](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_Arabic_numerals_with_decimal_comma).

**Comment by ValentinH** [comment]
I had a related issue when asserting on `transform` style. When run locally, the values are in the form of `50,30px` while in CI they are `50.30px`. Thus my tests fail in CI...

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
