### ISSUE TITLE
Consistant viewport scrolling during and after test runs

### ISSUE THREAD

**Issue by Regnander** [cypress-io/cypress#15715]
### Current behavior

When Cypress is (for example) typing in an input during a test run, it will respect any headers to make sure the viewport is scrolled enough for the input to be visible on screen.

![c](https://user-images.githubusercontent.com/17113053/113061417-47d0bb00-91b2-11eb-839b-beb886a90366.png)

However, when the test is done and you are browsing the Command Log, the viewport will be scrolled so the same input will end up *behind* the header.

![a](https://user-images.githubusercontent.com/17113053/113061413-47382480-91b2-11eb-9018-634a6c219c00.png)

### Desired behavior

I want the viewport to scroll the same way as it does during the test run, like this:

![b](https://user-images.githubusercontent.com/17113053/113061416-47d0bb00-91b2-11eb-809d-58983a83d739.png)

### Test code to reproduce

index.html:
```html
<!DOCTYPE html>
<html>
<head></head>
<body style="height: 200vh; padding-top: 30px;">
    <span style="background-color: brown; position: fixed; top: 0px; left: 0px; width: 100%; height: 30px; margin-left: 0px;"></span>
    <input id="a" type="text" style="display: block;" />
    <div style="padding: 30px 0px;"></div>
    <input id="b" type="text" style="display: block;" />
    <div style="padding: 30px 0px;"></div>
    <input id="c" type="text" style="display: block;" />
</body>
</html>
```

test.ts:
```js
context('...', () => {
    it('...', () => {
        cy.visit('index.html')
        cy.get('input').each(($i) => { cy.wrap($i).type('ABC123') })
    })
})
```

### Versions

Tested on Cypress 6.8.0

**Comment by todd-m-kemp** [comment]
This is likely the same issue I logged as #15618 . There hasn't been any comment from Cypress on that yet but I'm hopeful it will be addressed soon as its a big issue in my opinion and will block further Cypress upgrades at my organization!

**Comment by jennifer-shehane** [comment]
This is a different issue. There isn't an issue with the actionability, but with the preview scroll used when reviewing snapshots. These are different scrolling mechanisms.

**Comment by jennifer-shehane** [comment]
I can recreate this with the repro provided. The element scrolled in the snapshot preview does not match the action performed. This is unexpected behavior. 

`spec.js`

```js
context('...', () => {
  it('...', () => {
    cy.visit('index.html')
    cy.get('input').each(($i) => { cy.wrap($i).type('ABC123') })
  })
})
```

`index.html`

```html
<html>
<body style="height: 200vh; padding-top: 30px;">
  <span
    style="background-color: brown; position: fixed; top: 0px; left: 0px; width: 100%; height: 30px; margin-left: 0px;"></span>
  <input id="a" type="text" style="display: block;" />
  <div style="padding: 30px 0px;"></div>
  <input id="b" type="text" style="display: block;" />
  <div style="padding: 30px 0px;"></div>
  <input id="c" type="text" style="display: block;" />
</body>
</html>
```
