### ISSUE TITLE
Let overwrite intercept response

### ISSUE THREAD

**Issue by jdiegosierra** [cypress-io/cypress#15722]
I'm just copying this [StackOverflow question](https://stackoverflow.com/questions/65044704/change-fixture-response-in-cypress-for-the-same-url-with-intercept) because I have the same problem and I think that the answer they propossed is not very clean.

### What would you like?
I am trying to write a test with the interceptor method (Cypress API Intercept). For the test I am writing I need to change the reponse of one endpoint after some action was performed.
I am calling cy.intercept again with another fixture and expect it to change all upcomming calls to response with this new fixture.
Cypress still response with the first fixture set for the call.

### Why is this needed?
I think is needed if I want to simulate database changes in the same test.

**Comment by jennifer-shehane** [comment]
This will be the behavior in 7.0 which will be released any day now. https://github.com/cypress-io/cypress/pull/14543
