### ISSUE TITLE
Show warning when running binary directly and not from NPM module

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1573]
## New feature

Cypress binary should not be executed directly - instead the user should run NPM module which collects all arguments and then calls the binary.

We can pass an argument from NPM package to the binary, and if this argument is missing, the binary can show a warning, for example `--run-from-cli`.

From

https://github.com/cypress-io/cypress/issues/756#issuecomment-380922563

**Comment by jennifer-shehane** [comment]
There's actually a PR open for this. Going to see if I can move it along. https://github.com/cypress-io/cypress/pull/1574

**Comment by jennifer-shehane** [comment]
Closing the old PR in favor of https://github.com/cypress-io/cypress/pull/4701
