### ISSUE TITLE
cy.fixture using 'this' context not working as per the documentation

### ISSUE THREAD

**Issue by GCHQDeveloper911** [cypress-io/cypress#15736]
### Current behavior
Currently, according to the docs for cy.fixture (https://docs.cypress.io/api/commands/fixture#this-context) , I should be able to do something like:
```js
describe('nothing', function () {
  beforeEach(function () {
    cy.fixture('basic-test').then(function(testdata){
      this.data = testdata
    })
  })

  it('does little', function () {
    cy.log(this.data)
  })
})
```
However, 'this' in the 'beforeEach' and 'it' functions differ - no matter whether you do or do not use arrow functions.

### Desired behavior
Either the functionality should allow the above, or the docs need correcting / clarifying.

### Test code to reproduce
As above. Also you'll need some sort of arbitrary fixture json file.

### Versions

Cypress 6.x, CentOS8, Chrome 83

**Comment by jennifer-shehane** [comment]
This code provided does print the data from the example.json file for me. What does your fixture file look like exactly?

<img width="563" alt="Screen Shot 2021-04-01 at 11 20 44 AM" src="https://user-images.githubusercontent.com/1271364/113316449-587d5000-92dc-11eb-9424-d19977adefab.png">

**Comment by GCHQDeveloper911** [comment]
I've tried stripping things back to a basic sample json:
```
{
  "somefield": "VALUE1",
  "arrayvalue": ["VAL1", "VAL2"]
}
```
Same issue. Have attached a couple of screenshots to illustrate the problem as highlighted in dev tools... Hope this helps?

<img width="637" alt="Screenshot 2021-04-06 at 08 09 36" src="https://user-images.githubusercontent.com/45789551/113672765-0ce9ee00-96b0-11eb-91fa-06fce8a7e913.png">
<img width="637" alt="Screenshot 2021-04-06 at 08 10 10" src="https://user-images.githubusercontent.com/45789551/113672772-0eb3b180-96b0-11eb-8e25-96983265c645.png">

**Comment by bahmutov** [comment]
I have put your code in https://github.com/cypress-io/cypress-test-tiny/tree/fixture-example and it passes as expected

```js
/// <reference types="cypress" />

// load fixture separately
const basicTest = require('../fixtures/basic-test.json')

// https://github.com/cypress-io/cypress/issues/15736
describe('nothing', function () {
  beforeEach(function () {
    cy.fixture('basic-test').then(function(testdata){
      this.data = testdata
    })
  })

  it('does little', function () {
    cy.log(this.data)
    expect(this.data).to.deep.equal(basicTest)
  })
})
```

<img width="453" alt="Screen Shot 2021-04-06 at 10 25 25 AM" src="https://user-images.githubusercontent.com/2212006/113726820-8d194f00-96c2-11eb-96b4-ee6448585642.png">

Please provide a reproducible repo with failing test that you think does not work according to the docs
