### ISSUE TITLE
http2 requests to server fallbacking to http1

### ISSUE THREAD

**Issue by midan888** [cypress-io/cypress#15740]
I am using http2 requests in our project!

Trouble is that in cypress when starting chrome all requests two server become http1.
But if I start in regular chrome on host machine its http2.
Because of that we get a lot of stalled requests. Our project uses grpc over http2.
Need help!

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/3708

**Comment by loumacdev** [comment]
> Duplicate of #3708

why have both these issues been closed as duplicates when the issue has not been resolved - is anyone actively looking at this issue with server reverting to http1? many people are using grpc http2 - which would unfortunately make cypress an unacceptable choice

**Comment by gajus** [comment]
This could be solved with https://github.com/cypress-io/cypress/issues/22319

**Comment by MolochKel** [comment]
@jennifer-shehane Any update on either of the referenced issues?
