### ISSUE TITLE
Cypress intermittently skips commands after successful custom commands

### ISSUE THREAD

**Issue by ttomaszewski** [cypress-io/cypress#15757]
### Current behavior

I have a before() which uses a custom cy.login() command followed by a button click command. I've noticed running tests, that sometimes Cypress will not run the commands following the custom login command in the before(), even though the login appeared to be successful and no error thrown in the Runner. 
So in the snippet below, `cy.get('[data-test=button]').click();` never runs, which causes the following tests to fail since they are dependent on it.

### Desired behavior

Cypress runs all commands after custom commands in before(). 

### Test code to reproduce

```
  before('log in and click button', () => {
    cy.login('test@example.com');
    cy.get('[data-test=button]').click();
  });
```

### Versions
6.8.0

**Comment by shwarcu** [comment]
Hi, does your `login` command always return a subject?

**Comment by bahmutov** [comment]
The `before` hook is dangerous - it runs once before all the tests. Are you sure the `cy.get().click()` is skipped and not the entire `before` hook? Can you give us a tiny reproducible example showing the problem?
