### ISSUE TITLE
When ffmpeg fails, log more detailed information

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress#1578]
When ffmpeg fails, we don't get a very helpful error message, so we need to log out more information about the current user's configuration that could have cause ffmpeg's failure.
such as: 
user's screen resolution,
ffmpeg version from the binary,
possibly more

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
