### ISSUE TITLE
ReferenceError: cy is not defined

### ISSUE THREAD

**Issue by nnnoel** [cypress-io/cypress#15782]
### Current behavior
I am trying to stub `googleapis` via task inside `plugins/index.js`. Specifically in a NextJS app.

When I call the task, I get a cryptic error:
```
From Node.js Internals:
    ReferenceError: cy is not defined
      at stub:googleapis (~/project
/cypress/plugins/index.js:55:12)
```
This error does not occur when I remove the stub and I am able to use other `cy.task` calls just fine.

<img width="741" alt="Screen Shot 2021-04-03 at 4 50 29 PM" src="https://user-images.githubusercontent.com/14010887/113474868-b5276900-949c-11eb-8a35-b1164ed974cc.png">

### Desired behavior
A more useful error message.

### Test code to reproduce
1. Bootstrap a basic nextjs app (I think https://github.com/bahmutov/next-and-cypress-example works) and `yarn add googleapis`
2. Add a google drive handler to a serverless api route:

NOTE: In order to test with `googleapis`, you need a private key and a client email.

then call this somewhere in the api handler

```
    const jwt = new google.auth.JWT({
        email: clientEmail,
        key: privateKey,
        scopes: [
            'https://www.googleapis.com/auth/drive',
        ],
    })
    await jwt.authorize()
    await google.drive({
        auth: jwt,
        version: 'v3',
    })
```
3. Add the following to `plugins/index.js`:
```
const { google }= require('googleapis')

module.exports = (on) => {
    on('task', {
        'stub:googleapis'() {
          cy.stub(google, 'drive').returns({})
            return null
        },
    })
}
```
4. Write a cypress test for the api route calling this task (or call the command that calls the task as I did, both reproduce the issue)

### Versions
- "cypress": "^6.6.0" and 6.8.0
- macOS 10.15.7
- chrome latest

**Comment by bahmutov** [comment]
The plugin file runs in Node: it is used to configure your browser before launch, or execute Node code (via cy.task). It does not have `cy` or `Cypress` objects, those objects are only defined in the browser spec or support files. Read https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Plugin-files for details.

**Comment by nnnoel** [comment]
> Read https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Plugin-files for details.

This link doesn't mention anything about `It does not have cy or Cypress objects, those objects are only defined in the browser spec or support files`. Perhaps there should be a custom error message to note that Cypress objects are only defined within the browser spec or support files?

From what I could tell, I was getting an error message from Node.js Internals where I specified my stub, but then looked like it was instead the `cy.task` that was trying to call it in the commands file, which was confusing.
