### ISSUE TITLE
Installing cypress 6.9.0 fails when downloading binary

### ISSUE THREAD

**Issue by eppsilon** [cypress-io/cypress#15797]
### Current behavior

Trying to install cypress 6.x via Yarn fails because the binary can't be found. It also isn't downloadable via plain wget. I'm not behind a proxy. I don't see the 6.9.0 release posted on GitHub - was it published by mistake?

Installing 6.8.0 using `yarn add cypress@~6.8.0` does work.

```
> yarn add cypress@^6.0.0
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/6] ⢀ waiting...
[2/6] ⢀ fsevents
[3/6] ⠠ cypress
[-/6] ⠠ waiting...
error <...>/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: <...>/node_modules/cypress
Output:
Installing Cypress (version: 6.9.0)

[16:06:30]  Downloading Cypress     [started]
[16:06:31]  Downloading Cypress     [failed]
[16:06:31] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/6.9.0?platform=darwin&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: darwin (20.3.0)
Cypress Version: 6.9.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/6.9.0?platform=darwin&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------
```

### Download method

- [ ] npm
- [X] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux
- [X] Mac
- [ ] Windows

### Other

- [ ] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by bahmutov** [comment]
Yeah we published it by mistake, really the version is 7.0.0 and we will remove 6.9.0

**Comment by EMazzaglia** [comment]
Is there an issue with the     "@cypress/react": "^4.16.4", because of this update? Im getting this error when trying to install it on my amplify pipeline. 

![image](https://user-images.githubusercontent.com/31999516/113641189-84d5fb00-9653-11eb-8948-c6e93f58364e.png)

**Comment by jennifer-shehane** [comment]
There was an issue publishing our 7.0.0 release. We advise users to not install 6.9.0 at this time and to instead install:

6.8.0: Working version
7.0.0: Working version with breaking changes. See our [changelog](https://on.cypress.io/changelog) for full details.

**Comment by cupcakepanda89** [comment]
I am currently on 6.7.1 and it gets the same error when trying to install cypress on the codeship pipeline

**Comment by EMazzaglia** [comment]
> There was an issue publishing our 7.0.0 release. We advise users to not install 6.9.0 at this time and to instead install:
> 
> 6.8.0: Working version
> 7.0.0: Working version with breaking changes. See our [changelog](https://on.cypress.io/changelog) for full details.

@jennifer-shehane I removed my example component test since I can't get back the [cypress/react package](https://www.npmjs.com/package/@cypress/react) from npm it throws 404 when I want to install it via npm. Are you going to add it with a new version later?

**Comment by e-jigsaw** [comment]
same problem `@cypress/react` 404 😭

**Comment by develijahlee** [comment]
Glad to see this was not just happening to me. Vercel was working fine yesterday on 6.8.0 and today all my builds fail trying to get 6.9.0! Even made a stackoverflow question to see if anyone else was having this problem: https://stackoverflow.com/questions/66961328/error-failed-downloading-the-cypress-binary/66961811#66961811

**Comment by chrisbreiding** [comment]
We've published [Cypress 6.9.1](https://www.npmjs.com/package/cypress/v/6.9.1) with the same content as 6.8.0. It will be installed instead of 6.9.0 if your `cypress` dependency is set to `^6.x.x`.

**Comment by jayjnu** [comment]
I experienced the same problem. 

this is just a head-up for those who might get into the same trouble.

as @chrisbreiding 's instruction, I set cypress version to 6.9.1, which  didn't work in my ci server.

Instead, I downgraded cypress version to 6.8.0. then it worked.

```
"devDependencies": {
 "cypress": "6.8.0"
}
```

my ci env is listed below

- it's behind the proxy (enterprise proxy)
- it's a docker image (node:14.8-alpine) 

 maybe it's my company's proxy issue, and I'm currently okay with using 6.8.0.

**Comment by prashant-kajale** [comment]
Running into the same issue since last night for yan install step.

I have setup the cypress version as 6.4 but not sure why 6.9 is getting installed

**Comment by sjagoe** [comment]
We're seeing intermittent `HTTP 404` errors downloading cypress 6.9.1, causing CI installs to fail somewhat randomly

```
# First attempt
$ curl -Ssf -o/dev/null "https://download.cypress.io/desktop/6.9.1?platform=linux"
--> # success
# Second run:
$ curl -Ssf -o/dev/null "https://download.cypress.io/desktop/6.9.1?platform=linux"
curl: (22) The requested URL returned error: 404
```

**Comment by shuehner** [comment]
Same problem here essentially making cypress totally unusable in our CI (2nd time today)

Behavior is same as @sjagoe raised.

Checking headers of manual curl call to the download url seems that depending on cloudflare data-center (?)  behavior changes as if the 6.9.1 related cypress.zip file is not present in all download hosts?

If works i see consistently:
cf-ray header <some-id>-MAD

If it fails with 404
cf-ray header <-some-id>-LHR

Example concrete header when it fails with 404:
< server: cloudflare
< cf-ray: 63badf08db3d0706-LHR

It would be great if somebody from the project could follow up urgently on this.

From outside not clear if that is
- cloudflare infrastructure problem
- or npm 6.9.1 published in npm registry while the related cypress.zip is not guaranteed available yet for download everywhere (via cloudflare cdn which seems to be behind the download redirection)

**Comment by bahmutov** [comment]
We have purged the Cloudflare cache for v6.9.1 should be all set
