### ISSUE TITLE
Cypress shouldn't scroll when performing action (click) on a fully visible element

### ISSUE THREAD

**Issue by Andarist** [cypress-io/cypress#15806]
Cross-posting from https://github.com/cypress-io/cypress/issues/9739#issuecomment-811402773

### Current behavior

Scroll position is changed when clicking a fully visible element in a scrollable container 

### Desired behavior

No scroll position change should happen for fully visible elements.

### Test code to reproduce

~If you insist I can prepare a repro case later but I think that for this one a description with the attached recording is enough to understand the issue.~

The repro case can be found in [the comment bellow](https://github.com/cypress-io/cypress/issues/15806#issuecomment-815034995).

For already visible elements `scrollIntoView` may move the container - which feels like something that could/should be avoided as it's not required and might change something in the application's behavior by accident.

On the attached recording the "terefere" button is being clicked on - it is fully visible and thus I would expect the container to not be moved.

https://user-images.githubusercontent.com/9800850/113202458-0ea85180-926b-11eb-8335-7e2b6a13d6a3.mp4

### Versions

I had no chance yet to update to the latest 7.0 but there is no information in the changelog about this being fixed so I think it's safe to assume that the issue is still there since I've tested this on the latest 6.x.

**Comment by bahmutov** [comment]
@Andarist can you create a repo with a reproducible example?

**Comment by Andarist** [comment]
Sure thing. The test representing the situation can be found [here](https://github.com/Andarist/cypress-test-tiny/blob/cd2efd4804ef6f95c4ab6cb540ee93cb1d391231/cypress/integration/spec.js). I'm clicking the button with 5 on it. On the screenshots below we can notice that in the pre-click situation this button is **fully** visible and yet the container gets scrolled when clicking.

### pre click
<img width="244" alt="scroll position before click" src="https://user-images.githubusercontent.com/9800850/113896646-6ba38a80-97ca-11eb-8dfb-25d1192beda1.png">

### post click
<img width="247" alt="scroll position after click" src="https://user-images.githubusercontent.com/9800850/113896866-9ee61980-97ca-11eb-88e2-672415603c8f.png">

**Comment by Jacek-fstack** [comment]
I'm having a similar issue, but it doesn't occur in 6.x but ONLY in 7.x 
and it scrolls the item it found OUT of view and then fails. 
Can this be related or should I create a separate ticket?

**Comment by Andarist** [comment]
@Jacek-fstack I think your issue is different as mine can be reproduced on both Cypress 6 and Cypress 7 (and most likely on earlier versions as well) and it involves a visible element. So I think that you are experiencing something different.

**Comment by tylercaceres** [comment]
I'm seeing this issue as well.
I'm using version 7.4.0.

**Comment by jennifer-shehane** [comment]
I can recreate the issue as described. 

This is as designed so is not a bug (albeit maybe unexpected), from our docs:

>Before interacting with an element, we will always scroll it into view (including any of its parent containers). Even if the element was visible without scrolling, we perform the scrolling algorithm in order to reproduce the same behavior every time the command is run. https://on.cypress.io/interacting-with-elements#Scrolling


You can disable the scroll altogether by passing `scrollBehavior: false` to the `click` or any other action command, which is what I would suggest.

```js
.click({ scrollBehavior: false })
```

**Comment by Andarist** [comment]
Since it wasn't closed by @jennifer-shehane and behavior changes around this seem to be up for discussion... BUMP FOR THE STALE BOT 😉

**Comment by nagash77** [comment]
@Andarist thank you for replying and confirming this is still relevant.  I will update the ticket accordingly.

**Comment by marktnoonan** [comment]
I'm going to route this as a product request since

> This is as designed so is not a bug 

@Andarist could you confirm:

- whether you are experiencing problems related to this, or just found it to be unexpected?
- that `.click({ scrollBehavior: false })` combined with manually scrolling into view when needed wouldn't meet your needs?

I can imagine scenarios where heavily scroll-driven experiences might end up having unexpected side effects happen based on Cypress preforming scrolling that users would not perform when clicking a button or something. This might result in the content of the page changing and may even paper over bugs in the application under test, because you would get scrolling "for free". But I think it such cases where we expect an element to visible and don't want to scroll the page, we have the existing escape hatch.

But at this point I'm just speculating, I would like to understand the use case that prompted this issue itself.

**Comment by Andarist** [comment]
> whether you are experiencing problems related to this, or just found it to be unexpected?

At some point, I had to debug a failing test case to understand what was happening in it and this was directly contributing to it. So it's not something that I just found out accidentally.

> that .click({ scrollBehavior: false }) combined with manually scrolling into view when needed wouldn't meet your needs?

It would. IIRC, I was intentionally scrolling the container manually~ to some point - since the test was meant to check some logic related to the "above the fold threshold" (or similar). And then the container was moved again implicitly by `.click()`, despite the target being **completely** in the view and thus it defeated the purpose of this particular test. I knew about the "actionability rule" in Cypress but on this occasion, the element was already actionable so I found that extra scroll being redundant and confusing.

**Comment by marktnoonan** [comment]
Thanks @Andarist. From what you have described, using `.click({ scrollBehavior: false })` sounds like it would have worked for you.

> behavior changes around this seem to be up for discussion

I'm not sure what behavior change you would like. It seems like Cypress already can work in the way you describe, it is just not the _default_ behavior.

**Comment by Andarist** [comment]
It's a [documented behavior](https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Scrolling), at least today (I'm not sure f it was when I opened the issue). It took me off guard back then so I decided to open an issue about this. I'm fine with just closing this if you think it's OK how things are working right now.

**Comment by marktnoonan** [comment]
Got it - I will close for now. Thank you for providing the feedback!
