### ISSUE TITLE
Assert on HTML contents always fails if HTML includes a symbol

### ISSUE THREAD

**Issue by danatemple** [cypress-io/cypress#15800]
### Current behavior

There is an element 
```
<span>
&radic;y
</span>
```
 .. i.e. square root of y.

The assertion

    cy.get('span').should('have.html', "&radic;y");

fails.

![image](https://user-images.githubusercontent.com/11148387/113665287-83392100-96ad-11eb-8ef5-0ea09b03d426.png)

This is Cypress 6.6.0.

It is unclear how (or if) it is possible to make this assertion work. It seems to work fine with other HTML content.

**Comment by bahmutov** [comment]
```html
<span id="y-value">&radic;y</span>
```

```js
cy.get('#y-value')
  // use the text value of the HTML entity
  .should('have.html', '√y')
  // "have.html", "have.text", and "contain"
  // assertions work the same with text
  .and('have.text', '√y')
  .and('contain', '√y')
```

Unfortunately, there is no standard built-in JavaScript method for converting HTML entities like `&radic;` into the browser text. Thus the test can encode it itself to use in the assertion.

```js
// a utility for converting HTML entities into text
const encode = (s) => {
  const p = document.createElement('p')
  p.innerHTML = s // encodes
  return p.innerText
}
cy.get('#y-value').should('have.text', encode('&radic;y'))
```
