### ISSUE TITLE
Cypress version is fixed to 6.4 in dev dependency but still it tries to install 6.9.1

### ISSUE THREAD

**Issue by prashant-kajale** [cypress-io/cypress#15804]
### Current behavior
Dev dependency : 
    "@cypress/code-coverage": "3.8.5",
    "@cypress/instrument-cra": "1.3.2",
    "@cypress/skip-test": "2.5.0",
    "@shelex/cypress-allure-plugin": "1.10.1",
    "@testing-library/cypress": "7.0.2",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.1.0",
    "babel-plugin-istanbul": "^6.0.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "chai": "^4.3.3",
    "copy-webpack-plugin": "6.0.3",
    "css-loader": "^3.6.0",
    "cypress": "6.4.0",
    "cypress-multi-reporters": "1.4.0",
    "cypress-wait-until": "1.7.1",

### Debug logs

[4/4] Building fresh packages...
error /usr/src/app/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /usr/src/app/node_modules/cypress
Output:
Installing Cypress (version: 6.9.1)

[08:14:36]  Downloading Cypress     [started]
[08:14:36]  Downloading Cypress     [failed]
[08:14:36] → The Cypress App could not be downloaded.

### Download method
 

- [ ] npm
- [x] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux

### Other

- [ ] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [x] This only occurs in CI

**Comment by bahmutov** [comment]
I copied your dependencies into https://github.com/cypress-io/cypress-test-tiny/tree/install-version and ran the yarn install. I see cypress v6.4.0 

```
$ yarn why cypress
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "cypress"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "cypress@6.4.0"
info Has been hoisted to "cypress"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "9.24MB"
info Disk size with unique dependencies: "28.4MB"
info Disk size with transitive dependencies: "59.46MB"
info Number of shared dependencies: 91
✨  Done in 0.92s.
```

```
$ yarn cypress version
yarn run v1.22.10
$ /Users/gleb/git/cypress-test-tiny/node_modules/.bin/cypress version
Cypress package version: 6.4.0
Cypress binary version: 6.4.0
Electron version: 11.2.1
Bundled Node version: 12.18.3
✨  Done in 0.59s.
```

Please re-install again or provide a repo with a reproducible example

Also check your CI cache: https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/

**Comment by prashant-kajale** [comment]
I was doint 
RUN npm install cypress
RUN rm -rf package-lock.json
RUN yarn install

after this issue was reproducible.
I removed the step RUN rm -rf package-lock.json, then it started picking correct version
