### ISSUE TITLE
Test sections, checkpoint reporting, or subTests

### ISSUE THREAD

**Issue by Tarig0** [cypress-io/cypress#1581]
### Current behavior: 

To get a nice list of use cases to be listed, in test results, I currently have to run a test for each use case.

Example:
Order Bike
--> Pre Login
-> Initial Bike configuration is set
--> Navigate to Catalog
--> Find Bike
--> Click
--> Assert Page

-> Bike Type unicycle hides chain option
--> Navigate to Catalog
--> Find Bike
--> Click unicycle
--> Validate sections

-> Bike Type motorcycle shows engine section
--> Navigate to Catalog
--> Find Bike
--> Click motorcycle
--> Validate sections
etc.
etc.
### Desired behavior:

Be able to report on important checkpoints within the run that signify a validated use case. Where if the use case is not reached is reported as incomplete. I would also like to be able to see these checkpoints reported as tests with the time set to the current parent's time.

Order Bike
--> Pre Login
--> Navigate to Catalog
--> Find Bike
--> Click
--> Assert Page **Initial Bike configuration is set**
--> Click unicycle
--> Validate sections **Bike Type unicycle hides chain option**
--> Click motorcycle
--> Validate sections **Bike Type motorcycle shows engine section**

**Comment by Tarig0** [comment]
The main thing I want is to be able to say this test run satisfies the use cases A,B,C,D without having to do 4 full runs.

This avoids having to build up the state multiple times, when I'm trying to assert things, that if they don't exist isn't blocking me from continuing the run.

I like having the should ;)

Sorry I realize my desired behavior was incorrect, edited OP.

**Comment by fr0** [comment]
I agree this would be valuable. I expect my `it` cases to be self-contained and to not depend on the state left behind by previous tests. Your `checkpoint`s would be part of a single `it` and thus could depend on state from before, while still providing a meaningful way to group assertions or portions of a test.

**Comment by sania-dsouza** [comment]
Hi! Do we have an update on this feature? I have a use case in my project for a test section.

**Comment by BlueWinds** [comment]
`cy.session()` was released in Cypress 12 (https://docs.cypress.io/api/commands/session), and seems like it provides the functionality asked for here. I'm going to close this issue; feel free to leave a comment or open a new issue if you'd still like something else and don't believe .session() meets your use case!
