### ISSUE TITLE
WSL2: Extremely slow

### ISSUE THREAD

**Issue by BryantDavis1986** [cypress-io/cypress#15818]
With the release of WSL2 awhile back and the decent performance boost to operating purely on the linux side of the machine. I would prefer to stay on that side, react installs in about 5 seconds with wsl 2, a huge boost. 

Is there a work around or preferred method right now to using cypress inside of WSL2? For example I had to do a huge work around with XLaunch inorder for Cypress to even open a browser(live-server and react seem to not have this issue) but currently theirs very long delays. In my WSL2 setup it is taking 70 seconds to hit our main page which then redirects to Auth0. I understand this is bad practice and something I will ultimately have to address down the line. When i setup this same environment on windows side it takes about 4-5 seconds. I had setup my auto timeout to be 30 seconds so I thought the call was breaking entirely. 

Ultimately just looking for a way to keep using WSL2 with its superior performance than transitioning to windows side or being forced to get a MAC over this.

**Comment by jennifer-shehane** [comment]
@BryantDavis1986 I'm not aware of any issues in WSL2 currently with loading pages taking a long time. Are you running directly or in a docker container? 

What version of Cypress are you using?
