### ISSUE TITLE
Empty Cypress app in Dock

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#15822]
### Current behavior
When opening Component Testing using an external (non-Electron) browser, LSUIElement is set for the Cypress process. This means you can click on the Dock icon and make it the active app, even though it renders no windows.

### Desired behavior
We should not see a "ghost" Cypress app in the Dock since it has no actionable UI.

### Versions

7.0.0

**Comment by lmiller1990** [comment]
With the eventual re-introduction of the desktop gui for launching the CT runner, this issue probably is not worth solving right now, since we will always be launching the desktop gui in the future.

**Comment by JessicaSachs** [comment]
Closing this as wontfix. We have a **lot** of UX changes that will improve the ergonomics of this.
