### ISSUE TITLE
performance issue: cypress@7 next.js headless

### ISSUE THREAD

**Issue by frattaro** [cypress-io/cypress#15827]
### Current behavior

Running `start-server-and-test ... cypress:open` runs all my tests in a little less than 28 seconds. Running `start-server-and-test ... cypress:run` results in every test timing out. Happens locally (windows) as well as on travis (linux). This is new with cypress@7, did not happen on 6.8

The setup is pretty similar to a gatsby app I have (same cypress plugins, including code-coverage) that does not have failing tests, except this one is a next@latest app. Processor usage for `cypress run` is much higher than for `cypress open` (which is different in 7 vs 6.8), and I assume next can't get enough processor power to compile the pages on first load.

Running node 14 locally and in travis.

**Comment by frattaro** [comment]
Maybe this is helpful:

```
(node:25316) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
```

but I can't get it to trace the warnings.

**Comment by lmiller1990** [comment]
Thanks for the report, will look into this one for you. Just to check, as of Cypress 7.0, we have at component testing specific runner. Did you migrate to the latest [following this guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing)? Then you would do either `open-ct` and `run-ct` for the component testing runner + new dev-server architecture.

Aside from that, anything specific I should do or just use a standard next.js app like [this one](https://github.com/cypress-io/cypress/tree/develop/npm/react/examples/nextjs)?

Also what version of next.js are you on?

**Comment by frattaro** [comment]
next@10.1.3. Not very different from the example next app but the `getServerSideProps` function in mine is a bit more heavyweight, making a few parallel async api calls (contentful) and doing some object transformations afterwards.

I hadn't been using the component testing, but when I went to set it up I couldn't get it to find any spec files. `open-ct` had a blank left menu, and `run-ct --spec cypress/component-testing/home.spec.js` gave:

```
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

cypress\component-testing\home.spec.js

Relative to the project root folder:

C:\[my_app_dir]
```

**Comment by lmiller1990** [comment]
The missing spec list is windows specific, we have an issue and this will be fixed asap: https://github.com/cypress-io/cypress/issues/15842

As for your run mode problem, I will look into this. Once these problems are solved, things should be a lot faster. I'll keep you updated. 

Thanks for the patience and quick responses!

**Comment by pjg** [comment]
For us Cypress v7.0.0 is roughly 2-2.5x slower.

**Comment by lmiller1990** [comment]
Hi! The `cy.intercept` issue is been looked into as a priority [see here](https://github.com/cypress-io/cypress/issues/15841#issuecomment-816191140) for some more info, as is performance.

I will keep you updated!

**Comment by frattaro** [comment]
With 7.2.0, performance is good enough I merged in the dependabot PR. Difference is less than a minute to the slower side.

**Comment by lmiller1990** [comment]
Good to hear. We will continue to work on improving perf... for now, it seems this issue is mostly solved, so I will close this. This doesn't mean we won't keep working on perf - we are actively working on improving the dev server architecture.
