### ISSUE TITLE
Incorrectly set Webpack publicPath results in the client spinning

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#15824]
### Current behavior
Setting an incorrect `publicPath` in your Webpack config, such as:

```javascript
{
  output: {
    publicPath: 'someUnreachablePath',
  }
}
```

results in the list of specs loading, but clicking on one of them just results in spinning as it attempts to load the spec file.

### Desired behavior
An error should appear informing the user that the compiled spec cannot be reached.

### Versions

7.0.0

**Comment by lmiller1990** [comment]
Is there any scenario where we even care about `publicPath`? Should we just replace it with `/`?

**Comment by lmiller1990** [comment]
#15839 should solve this. There is the wider problem of "how to handle failed requests for resources", currently they just 404. We will probably need to go deeper and think about the different errors that can manifest and how best to handle those, but I think it's outside the scope of this ticket.
