### ISSUE TITLE
[7.0.0] cy.intercept(): stubbed responses still send request to server

### ISSUE THREAD

**Issue by risa-hdqc** [cypress-io/cypress#15841]
### Current behavior
After upgrading from 6.7.1 to 7.0.0, I noticed my tests are still working as expected, but my server logs show requests being made to my server for intercepted requests using fixtures, objects, or strings.
```
    cy.intercept('/api/getThings', { fixture: 'getThings' });
    cy.intercept('/api/getAnotherThing', 'AnotherThing');
    cy.intercept('/api/getYetAnotherThing', { text: 'YetAnotherThing' });
```
Each of these intercepts _will_ return the stubbed response, but the requests are still being made afterward.

Example server log:
```
GET /api/getThings 200 4.389 ms - -
error: GET - 500 - /api/getThings -- some error because I'm not using a live service
GET /api/getAnotherThing 200 2.312 ms - -
error: GET - 500 - /api/getThings -- some error because I'm not using a live service
GET /api/getYetAnotherThing 200 4.231 ms - -
error: GET - 500 - /api/getYetAnotherThing -- some error because I'm not using a live service
```

### Desired behavior
The requests should NOT go to the server after returning the stubbed response.
```
GET /api/getThings 200 4.389 ms - -
GET /api/getAnotherThing 200 2.312 ms --
GET /api/getYetAnotherThing 200 4.231 ms --
```

### Current workaround
`req.reply` works as expected, blocking the requests to the server.
```
    cy.intercept('/api/getThings', (req) => req.reply({ fixture: 'getThings' }));
    cy.intercept('/api/getAnotherThing', (req) => req.reply('AnotherThing'));
    cy.intercept('/api/getYetAnotherThing', (req) => req.reply({ text: 'YetAnotherThing' }));
```

### Versions
7.0.0

**Comment by bahmutov** [comment]
Hmm, I do see it in v7.0.0

Reproduction: https://github.com/cypress-io/testing-workshop-cypress/tree/intercept-calls-server-15841

- clone the repo
- checkout branch `intercept-calls-server-15841`
- `npm install`
- `npm run dev` starts the server and Cypress
- click the spec `05-xhr/answer.js` it has a single test `it.only`

The test stubs the `GET /todos` with a fixture

```js
it.only('starts with zero items (fixture)', () => {
  // stub route `GET /todos`, return data from fixture file
  // THEN visit the page
  cy.intercept('GET', '/todos', { fixture: 'empty-list.json' }).as('todos')
  cy.visit('/')
  cy.wait('@todos') // wait for `GET /todos` response
    // inspect the server's response
    .its('response.body')
    .should('have.length', 0)
  // then check the DOM
  cy.get('li.todo').should('have.length', 0)
})
```

I see the stub working - but I also see the server showing `GET /todos 200` message in the terminal

<img width="1044" alt="Screen Shot 2021-04-07 at 10 37 44 AM" src="https://user-images.githubusercontent.com/2212006/113885576-f2864200-978d-11eb-8201-cad281e83e7b.png">

**Comment by flotwig** [comment]
FYI, the `stdout` printed by Cypress will show all requests, regardless of they are intercepted or not, so you can't rely on that to tell if the request is going to the destination server or not

**Comment by bahmutov** [comment]
@flotwig 

I tried testing-workshop example in v6.8.0 and with separate terminals to avoid the confusion. Did NOT show the request reaching the server

When switching to Cypress v7.0.0 the server IS showing `GET /todos` request, even when stubbed

**Comment by Alex-passiv** [comment]
Hello, 

Just adding to the pot saying I have been  experiencing the same issue. All my stubs have now been reaching the server. Commenting so I can stay updated for a fix. Thanks!
