### ISSUE TITLE
Migration Guide link in release 7.0.0 is not working (404)

### ISSUE THREAD

**Issue by escapedcat** [cypress-io/cypress#15840]
https://github.com/cypress-io/cypress/releases/tag/v7.0.0  

Several times from here is being linked ot a migration-guide using this URL:  
https://github.com/cypress-io/cypress/blob/v7.0.0/guides/references/migration-guide  
This is only showing the Github 404 page though:  
![image](https://user-images.githubusercontent.com/1016218/113814283-f8871d80-97a3-11eb-8812-269feacccf64.png)

**Comment by trew** [comment]
Meanwhile, in case you're looking for the link to the guide: https://docs.cypress.io/guides/references/migration-guide

**Comment by bahmutov** [comment]
Fixed, thanks for reporting.
