### ISSUE TITLE
All tests are passed and running individually  but they get failed while using 'npx cypress run'

### ISSUE THREAD

**Issue by gazalshukla** [cypress-io/cypress#15857]
### Current behavior
All tests are passed and running individually  but they get failed while using 'npx cypress run'

### Desired behavior
All the tests should pass and running using npx cypress run command 

### Test code to reproduce
All tests are passed and running individually  but they get failed while using 'npx cypress run'
here is the screenshot when i run the tests individually: 
![image](https://user-images.githubusercontent.com/35330885/113912940-5a25a700-97f9-11eb-9b47-4aeb8b7e3d3e.png)

here is the screenshot when i run them all togather using npx cypress run command 👍 

![image](https://user-images.githubusercontent.com/35330885/113913100-8b9e7280-97f9-11eb-92ee-28b7adc81514.png)

### Versions

 "cypress": "^7.0.0"
using chrome browser 
System : MacBook Pro (16-inch, 2019) 
macOS Catalina

**Comment by Coding-Means-Always-Learning** [comment]
@gazalshukla - Did you happen to see in the recorded recorded video what's going wrong with your player profile test.

**Comment by gazalshukla** [comment]
> @gazalshukla - Did you happen to see in the recorded video what's going wrong with your player profile test.
> Location : \cypress\videos\Tests

Yes , video shows that it was unable to find the element but i run it individually from test runner ,it works perfectly fine. i have also attached screenshot of that as well.

**Comment by sainthkh** [comment]
Sorry for the late reply. Can you give us a reproducible example? As we all know, the first step to fix bug is to reproduce it.

**Comment by gazalshukla** [comment]
Thanks, Sainthkh for reaching out to me about this issue. fortunately, It worked for me and I am closing this issue.

**Comment by Khan-Mohtashim** [comment]
@gazalshukla Can you please let us know what you did to make it work?
