### ISSUE TITLE
cy.fixture fails if file extension does not match casing (only CI)1

### ISSUE THREAD

**Issue by IMightGitIt** [cypress-io/cypress#15868]
* Host a file like "FILE.txt" in the fixtures folder
* Write a test which includes the following. Notice how the extension for the file is written in uppercase:
`cy.fixture('FILE.TXT')`
* Run the test in both local UI and in CI (Issue seen in GitLab)

**Observed behaviour**
When running in local UI the file is found as expected
When running in CI, the test fails, stating "FILE.TXT" can not be found.

**Expected**
The behaviour for both local UI and CI should be the same.
Ideally, both runners should not be caps lock sensitive, at least on the extension of the file

**Workaround**
1. Change the extension to have the same casing as the file
2. Remove the extension altogether from the test code, assuming the extension is one of those Cypress automatically look for.

**Comment by flotwig** [comment]
Are you running locally in Windows and in CI in Linux?

**Comment by IMightGitIt** [comment]
Yes, that is right. Perhaps the issue is related to the OS and not CI vs locally. I didn't think of that :)
