### ISSUE TITLE
Jest + Typescript: type definitions for `describe` and `it` do not support `env` object as second parameter

### ISSUE THREAD

**Issue by lambda0xff** [cypress-io/cypress#15872]
### Current behavior
In a test file written in typescript, trying to pass env variables to `describe` or `it` fails:
![Screenshot 2021-04-08 at 10 35 54](https://user-images.githubusercontent.com/38687176/113995353-77d52980-9856-11eb-971d-e4d24d1a46b1.png)

### Desired behavior
should accept the `env` object

### Versions
Cypress 7.0.0

**Comment by bahmutov** [comment]
Seems like it is trying to use the Jest type definition for the "describe" block. Please read our https://on.cypress.io/typescript documentation.

If you are using both Jest and Cypress in the same project, the TypeScript types registered globally by the two test runners can clash. For example, both Jest and Cypress provide the clashing types for the `describe` and `it` functions. Both Jest and Expect (bundled inside Cypress) provide the clashing types for the `expect` assertion, etc. There are two solutions to disentangle the types:

1. Configure a separate `tsconfig.json` for E2E tests. See our example [cypress-io/cypress-and-jest-typescript-example](https://github.com/cypress-io/cypress-and-jest-typescript-example) repo.
2. Remove Cypress global variables by using NPM package [local-cypress](https://github.com/bahmutov/local-cypress). Read the blog post [How to Avoid Using Global Cypress Variables](https://glebbahmutov.com/blog/local-cypress/) for details.
