### ISSUE TITLE
Cypress Test runner-- CORS issue for payment scenario

### ISSUE THREAD

**Issue by sowmyasridharamurthy** [cypress-io/cypress#15886]
Hello, 

We are automating E2E test for retail website. when we reach the payment page, user will be redirected to a payment portal. 
Cypress test runner does not display the right URL. 

**Expected payment URL on button click** -- (example link) https://payments-test.check.com/checkout/payment-method/abc
[we see this URL when clicks are carried out manually]

**The URL shown in Testrunner** --- (example link) https://ulele.co.uk/checkout/multi/payment-method/abc

And i will be shown CORS error. 

when i check the HTML i see document.domain = https://ulele.co.uk

Is the CORS issue because of this? how to avoid this document.domain being assigned 

![image](https://user-images.githubusercontent.com/35350156/114083287-11c8c080-98af-11eb-9c2f-aed53d85fc7f.png)

**Comment by bahmutov** [comment]
Have you read our https://docs.cypress.io/guides/references/trade-offs#Same-origin ?

**Comment by sowmyasridharamurthy** [comment]
@bahmutov Yes i have read these ans also tried searching for references in stackoverflow. 
We are not calling different URL using cy.visit(). 
In our case we have a confirm payment button, onclick of which the payment URL will be called (which ofcourse is different domain).

**Why are we doing this?** 
To achieve End to end customer journey (launch website-> search product -> add to basket -> Confirm payment-> carry out  payment-> order confirmation). We are presenting this within our Org to build a case to use CypressIO as our automation framework. 

**What i am looking for?**
I am facing challenge in achieving the payment scenario. 
  cy.get('#cs_terms').click({force : true});     //agreeing to payment terms
  cy.get('#e_checkout_summary_confirm').click(); //clicking payment button - this triggers the Payment URL which is 3rd party


Can you please guide how to get through this?

Thank you

**Comment by bahmutov** [comment]
I’m afraid right now this is not impossible due to visiting 2nd domain during the test

**Comment by sowmyasridharamurthy** [comment]
@bahmutov 
I dont see the above issue anymore, 
We see the payment iframe loaded and i am able to interact with the elements. 

However, now i see DOM exception in console.
Can you please guide me here? Duew to this error the test flow is stopped
![image](https://user-images.githubusercontent.com/35350156/139557696-80f3acb8-0052-447c-a105-8161735e33e0.png)

**Comment by AtofStryker** [comment]
@sowmyasridharamurthy have you tried getting this to work with the new `experimentalSessionAndOrigin` flag? This will be generally available in cypress 12 and am fairly confident this will fix your issue. I am going to close, but if this is still an issue please let us know!
