### ISSUE TITLE
[@cypress/vite-dev-server] Ability to select different port when running dev server

### ISSUE THREAD

**Issue by michaelhays** [cypress-io/cypress#15892]
### What would you like?
The ability to define a specific port in [`@cypress/vite-dev-server`](https://github.com/cypress-io/cypress/tree/develop/npm/vite-dev-server)

### Why is this needed?
I'm attempting to run component tests with a Vite dev server. Here's my plugin file:

```js
const { startDevServer } = require('@cypress/vite-dev-server')

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on, config) => {
  on('dev-server:start', (options) =>
    startDevServer({ options, viteConfig: { server: { port: 3001 } } }),
  )

  return config
}
```

However, when running `npx cypress run-ct`, `server: { port: 3001 }` is ignored because of [this line](https://github.com/cypress-io/cypress/blob/e8dbffedd6f72752f0c7167fd8a6e95aad10f073/npm/vite-dev-server/src/startServer.ts#L46).

I'll open a PR to add this.

**Comment by jennifer-shehane** [comment]
This was released. Please update to the latest version of Cypress and @cypress/vite-dev-server.
