### ISSUE TITLE
[Component testing] Viewport size config ignored if 1000x660

### ISSUE THREAD

**Issue by Akryum** [cypress-io/cypress#15899]
### Current behavior

Default viewport size is always 500x500.

Note that `cy.viewport()` in tests works as expected.

![image](https://user-images.githubusercontent.com/2798204/114154160-60fb0980-9920-11eb-9b36-043055fce3a8.png)

![image](https://user-images.githubusercontent.com/2798204/114155071-5a20c680-9921-11eb-8dd8-65b05d3c67f8.png)

![image](https://user-images.githubusercontent.com/2798204/114154366-9dc70080-9920-11eb-9529-b9513ece91af.png)

![image](https://user-images.githubusercontent.com/2798204/114154381-a3bce180-9920-11eb-9e25-cd857139ca8a.png)

### Desired behavior

Default viewport size follows the `cypress.json` file.

### Test code to reproduce

`cypress.json`:

```json
{
  "viewportHeight": 660,
  "viewportWidth": 1000
}
```

```
cypress open-ct
cypress run-ct
```

### Versions

Cypress: 7.0.1

**Comment by Akryum** [comment]
This is caused because the code checks if values are `1000x660` to apply the component testing special default `500x500`. Workaround:

```js
{
  "viewportHeight": 661,
  "viewportWidth": 1001
}
```

https://github.com/cypress-io/cypress/blob/726120da183cb6d89c83181761d21f09844a9fc2/packages/server-ct/src/project-ct.ts#L26-L44

**Comment by Akryum** [comment]
I guess it could be fixed by adding a `rawJson` property to the project config here:

https://github.com/cypress-io/cypress/blob/726120da183cb6d89c83181761d21f09844a9fc2/packages/server/lib/config.js#L242

Then we can have a much simple code to check if the config was explicitly set by the user:

```js
return { 
 ...cfg, 
 viewportHeight: cfg.rawJson.viewportHeight ?? 500, 
 viewportWidth: cfg.rawJson.viewportWidth ?? 500, 
}
```

**Comment by jennifer-shehane** [comment]
This was released. Please update to the latest version of Cypress.
