### ISSUE TITLE
Cypress reports error when loading third-party library

### ISSUE THREAD

**Issue by ivan-xue-prospa** [cypress-io/cypress#15896]
I was trying to call function from one node module in plugin file and that node module has one dependent library called chakram. But when I open Cypress , I got the following error

![image](https://user-images.githubusercontent.com/54783155/114110760-97825580-991b-11eb-8f62-9efcb23073ab.png)

index.js under plugins

```js
const fs = require('fs');
const salesforce = require('@xxx/salesforce');

module.exports = (on, config) => {
  on('task', {
    deleteFile(fileName) {
      if (fs.existsSync(fileName)) {
        fs.unlink(fileName, err => {
          if (err) throw err;
          console.log('Successfully deleted the old failure log');
          return null;
        });
      }
      return null;
    },

    submitLOCAppToCreditTeam(applicationId) {
      const workitemId = salesforce.application.submitLOCAppToCreditTeam(
        applicationId,
        Cypress.env('SFCREDITTEAMPROCESSIDLOC'),
        Cypress.env('SFCLIENTID'),
        Cypress.env('SFCLIENTSECRET'),
        Cypress.env('SFUSER'),
        Cypress.env('SFPASSWORD')
      );
      return workitemId;
    }
  });
};

**Comment by lmiller1990** [comment]
This is the line throwing the error: https://github.com/dareid/chakram/blob/cdccb980b3cc4322cd6dcef5341b49a56a904753/lib/chakram.js#L161

I don't even see where this is included in your `plugins/index.js`, though. Is the salesforce import doing something? Where does `submitLOCAppToCreditTeam` come from?

**Comment by ivan-xue-prospa** [comment]
submitLOCAppToCreditTeam come from the following private node module

`const salesforce = require('@prospa/salesforce');`

And the chakram is imported in the above node module.

**Comment by ivan-xue-prospa** [comment]
@lmiller1990 Any update for this issue?

**Comment by lmiller1990** [comment]
The problem is `afterEach` is getting executed in a plugin which runs in a Node.js process - this is a separate process to where you want your tests to run (in the browser). Should this perhaps be loaded inside of `support/index.js`?

**Comment by jennifer-shehane** [comment]
@ivan-xue-prospa Please include a repo, or a full example we can run to see the issue.

**Comment by ivan-xue-prospa** [comment]
@jennifer-shehane We fould the cause: chakram only works in Node.js environment, we refactored our private node package to use axios, everything works now. Thanks!
