### ISSUE TITLE
UI shows *.hot-update.js files in list of tests

### ISSUE THREAD

**Issue by reintroducing** [cypress-io/cypress#159]
I have a relatively specific use case for my Cypress setup but I'll try to explain it as best I can. I'm using webpack to bundle individual tests and the bundles for these tests spit out into the /integration directory. My Cypress test renders a React component into the DOM of an index file and I run my tests on that component from there.  In webpack I have hot module reloading set up so I can effectively edit my component and it reloads in the Chrome window, edit the test to re-run it, and everything is gravy.  The only issue is that webpack outputs these *.hot-update.js files into the same directory as your bundle lives, so now my file structure looks like this: https://www.dropbox.com/s/cvkd8yhr659039r/Screenshot%202016-06-10%2011.54.33.png?dl=0

It would be nice to be able to ignore these as a glob in the config so that they don't show up there and pollute the UI with what aren't actually executable specs.

**Comment by brian-mann** [comment]
Okay we will likely ignore these by default since `webpack` is so common, but we'll additionally add an `ignore` field which will accept globs. 

This will be fixed in either `0.16.3` or `0.17.0` depending on how quickly `0.17.0` gets done.

**Comment by reintroducing** [comment]
Sounds great.

**Comment by brian-mann** [comment]
There is now an `ignoreTestFiles` option in `cypress.json` which accepts an array of `glob` patterns to ignore. By default it will now ignore `*.hot-update.js` files.

Fixed in [`0.16.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0163-06172016).
