### ISSUE TITLE
Retry API interactions with a backoff strategy

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1590]
Whenever we interact with the API in order to run specs we need to have a retry + backoff strategy in the case the API is temporarily available such as DNS/network partition problems.

Currently we wait 10 secs and then immediately give up. We should retry a few times and backoff incrementally if there are `5xx` errors or node connection related errors like ECONNREFUSED.

**Comment by chrisbreiding** [comment]
Retry 3 times after the first request fails due to timeout or a 5xx response. Use the following delays for the retries:

30 seconds
2 minutes
5 minutes
