### ISSUE TITLE
Vue 2.x + composition API bug

### ISSUE THREAD

**Issue by DorianMazur** [cypress-io/cypress#15904]
### Current behavior
Currently, I can't write any test, because I'm using Vue 2.x with composition API.
Every test fails with message that _vm.methodName is not a function. 
methodName is just method returned from setup() inside component.
![image](https://user-images.githubusercontent.com/46839236/114181661-125e6700-9942-11eb-8884-336378c42c17.png)

### Desired behavior
I can write tests

### Test code to reproduce
plugins/index.js
```
/// <reference types="cypress" />

const { startDevServer } = require("@cypress/webpack-dev-server");
const webpackConfig = require("@vue/cli-service/webpack.config.js");

module.exports = (on, config) => {
  on("dev-server:start", (options) => {
    return startDevServer({
      options,
      webpackConfig,
    });
  });

  return config;
};
```

### Versions
@vue/cypress 2.2.0
@cypress 7.0.1
vue 2.6.12

**Comment by lmiller1990** [comment]
Hey, can you please share your component and test? It's impossible to debug with just this. 

Thanks!

**Comment by DorianMazur** [comment]
@lmiller1990 Here is not working example - https://github.com/DorianMazur/Vue-component-tests

**Comment by JessicaSachs** [comment]
Got it, so, like Vue Test Utils, we require you to register your plugins with `createLocalVue`. I would suggest exporting a mount command from a helper that wraps your component. I'll submit a PR onto that repo.

**Comment by JessicaSachs** [comment]
Here's the PR with the fix. I'm going to close this issue. Let me know if you need any more help. https://github.com/DorianMazur/Vue-component-tests/pull/1
