### ISSUE TITLE
Focusing radio input and then using .type changes value

### ISSUE THREAD

**Issue by kylecombes** [cypress-io/cypress#15913]
### Current behavior

After focusing an `input[type="radio"]`, the `value` attribute of that element change be changed using `.type`.

### Desired behavior

Cypress should recognize that radio inputs cannot have their value changed by the user.

### Test code to reproduce

Given the following HTML (saved in `test.html`):

```html
<html lang="en">
  <body>
    <input id="my-radio" type="radio" value="foo" name="Foo"/>
    <label for="my-radio">Foo</label>
  </body>
</html>
```

the following test fails:

```js
describe('My radio', () => {
  it('value does not change when focusing and typing', () => {
    cy.visit('/test.html');
    cy.get('input').should('have.value', 'foo').type('bar').should('have.value', 'foo');
  });
});
```

<img width="699" alt="Screen Shot 2021-04-09 at 12 24 06 PM" src="https://user-images.githubusercontent.com/3915596/114211318-7d05a780-992e-11eb-8744-d34d145dfed3.png">

### Versions

* Cypress v7.0.1
* Chrome 89.0.4389.114
* macOS 10.15.7

**Comment by sainthkh** [comment]
Right, I ran your example and it was reproducible. 

I clicked the radio button manually and typed the text and saw that it doesn't change the value. `cy.type()` doesn't reflect the browser behavior.

**Comment by kylecombes** [comment]
Additionally, pressing the space bar when the radio input is focused in the browser selects the option (see [WAI-ARIA guidelines for RadioGroup](https://www.w3.org/TR/wai-aria-practices/#radiobutton)). I was trying to test that behavior and that's how I discovered this issue.
