### ISSUE TITLE
Cy.visit never end 

### ISSUE THREAD

**Issue by Tchougbe** [cypress-io/cypress#15914]
### Current behavior
Hi,

My test never end . It loads home page but never go to next step : cy.get() ...

### Desired behavior
I want to load homepage and go through the website by clicking element by class ".subscribe".

### Test code to reproduce
`
describe('My First Test', () => {  
      
    it('finds the content "je demarre"', () => {
      cy.on('uncaught:exception', (err, runnable) => {
              return false
      })
    
      cy.visit('https://preprod.rutabago.com/');
      cy.get('.subscribe').click({ force: true });

    })
})
  `

### Versions
Cypress v7

**Comment by lmiller1990** [comment]
Possibly related: https://github.com/cypress-io/cypress/issues/15906
