### ISSUE TITLE
Nunit3 reporter

### ISSUE THREAD

**Issue by Pieras2** [cypress-io/cypress#15917]
I would like Cypress had embedded Nunit3 reporter.
I use Azure Devops and it does not support upload of screenshots results unless the report file is in Nunit3 format.

**Comment by csvan** [comment]
Cypress can export to the junit report format, which you in turn can convert to nunit.

https://stackoverflow.com/questions/66356726/cypress-test-runner-reporter-nunit

**Comment by Pieras2** [comment]
Honestly speaking I saw this but didn't manage to do it. 
Anyway I will try again.

**Comment by Pieras2** [comment]
I'll look if I could use this https://github.com/FlorianRappl/nightwatch-nunit3-reporter

**Comment by bahmutov** [comment]
We suggest using an external reporter and telling Cypress to use it, see https://on.cypress.io/reporters documentation.
