### ISSUE TITLE
cy.request is not using cookie, but chrome does

### ISSUE THREAD

**Issue by kicktipp** [cypress-io/cypress#15926]
### Current behavior

To login we have a custom cypress method cy.login() which is sending the login data with cy.request to the server on  http://localhost:8080/login which is our cypress baseUrl. 

It sends back a cookie like this:
```
login=m6z3h37...; Path=/; Domain=localhost; Max-Age=...; Expires=...; Secure; HttpOnly; SameSite=None
```
See the "secure" property. It is activated. The browser saves this cookie and visiting the site with cy.visit("/"), I am logged in. The cookie is sent even so "http" is used and not "https"  

This is correct behaviour:
"Secure: Cookie is only sent to the server when a request is made with the https: scheme (except on **localhost**),"
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

But when I sent another request with  cy.request the cookie is not sent. 

I searched the cypress code and found:

https://github.com/cypress-io/cypress/blob/0ca53c783d442626fb9a005ea70c05b11c6f6b5e/packages/server/lib/browsers/cdp_automation.ts#L150

I don't know if this code is used by cy.request. But if so, it should add a check if the host is localhost and sent the cookie even if it is secure and the protocol is http

### Desired behavior
A secure cookie should be sent by cy.request to a http host according to browser rules.
 
### Workaround
I uses cy.setCookie as a workaround

### Versions
v 7.0.1 / chrome / Ubuntu

**Comment by bahmutov** [comment]
@Bkucera what would you say in this case? Should we warn / document this behavior?

**Comment by alvaromartmart** [comment]
Hi, any updates on this?
