### ISSUE TITLE
Shit sucks

### ISSUE THREAD

**Issue by azzholex** [cypress-io/cypress#15922]
### Download method
 

- [ ] npm
- [ ] yarn
- [x] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux
- [ ] Mac
- [ ] Windows

### Other

- [ ] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by jennifer-shehane** [comment]
Please be mindful of our Code of Conduct in our issues. https://github.com/cypress-io/cypress/blob/develop/CODE_OF_CONDUCT.md
