### ISSUE TITLE
Race condition when initializing component testing

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#15930]
### Current behavior

This error is shown in the console when running the very first component testing spec:

![](https://user-images.githubusercontent.com/19196536/114331993-986bef00-9b88-11eb-89e6-ae5954ded221.png)

### Desired behavior

No error.

### Test code to reproduce

- Get this repo: https://github.com/cypress-io/cypress/issues/15874#issuecomment-816101265
- `npm install`
- in `tsconfig.json`, remove `"noEmit": true`
- `npx cypress open-ct`
- observe error in console (test still executes)

The error is [here](https://github.com/cypress-io/cypress/blob/602c762cfd707ae497273ac38206d7f9d8545439/packages/driver/src/cypress/cy.js#L1002).

There is a comment:

```
// dont need to worry about a try/catch here
// because this is during initialize and its
// impossible something is wrong here
```

It claims it's impossible to error here - clearly not 😆  

### Versions

7.0.1

**Comment by JessicaSachs** [comment]
The linked repo doesn't compile at all. Going to close this as we've never seen this error.
