### ISSUE TITLE
create-cypress-tests bugs

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#15933]
### Current behavior

1. Wizard not adding `return config` to the bottom of plugins file.
2. Does not offer webpack dev server with new Vue CLI project

### Desired behavior

1. It should add `return config` when running `yarn create cypress-tests`:

![image](https://user-images.githubusercontent.com/19196536/114347994-412a4680-9ba9-11eb-959e-a3b9aa29516b.png)

2. Not offering webpack with new Vue CLI project:

![image](https://user-images.githubusercontent.com/19196536/114348143-7e8ed400-9ba9-11eb-80fd-9f6cca2b011c.png)

3. No example component test

We should have a nice example.

4. Simplify directories? (from https://github.com/cypress-io/cypress/issues/15450#issuecomment-800704849)

Might be worth condensing the cypress directory that's created. It feels odd having a cypress directory when the component tests live in /src. e.g renaming to plugins.js, support.js and just having fixtures and commands folders.

### Test code to reproduce

- create new cypress repo
- run `yarn create cypress-tests`
- observe incorrectly generated `plugins/index.js`

**Comment by elevatebart** [comment]
I would add:
- Support for Vue 2, according to the CLI, we only support vue > 3
- In the final message we should say "run-ct" to run tests for component tests
- The rollup server should be removed from the CLI
- In my opinion, if you only have vite installed, asking the user to choose between vite and webpack is pointless
