### ISSUE TITLE
cy.intercept() requires url argument to be in URL encoded format

### ISSUE THREAD

**Issue by thomn9** [cypress-io/cypress#15956]
### Current behavior
Command cy.intercept() requires url argument to be in URL encoded format to match XHR (opposed to cy.route()). It means it is necessary to take additional step beforehand and use encodeUri() method. The problem is, it may get complicated when regex is used as url pattern to be matched.

### Desired behavior
Command cy.intercept() will accept url argument in non-URL encoded format as cy.route() do.

### Test code to reproduce
To reproduce this behavior is necessary to simulate XHR request containing characters that must be URL encoded and try to intercept this XHR with cy.intercept() command passing url agrument as non-URL encoded string. 

E.g. intercepting https://somesite.com/search?q=číslo

Will not work (but it is desired):
`cy.intercet('GET', '/search?q=číslo')`

Will work:
`cy.intercet('GET', '/search?q=%C4%8D%C3%ADslo')`
or
`cy.intercet('GET', `/search?q=${encodeURI('číslo')}`)`

### Versions
Cypress 7.0.1

**Comment by Deop** [comment]
Would love to see this fixed as well, although realize it might not be the highest priority

**Comment by jennifer-shehane** [comment]
I can recreate this behavior. I can't see why this would have been intentional by design. 

```js
it('❗️ fails non encoded cy.intercept()', () => {
  cy.intercept('/search?q=číslo').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/search?q=číslo')
    xhr.send()
  })
  cy.wait('@getUrl')
})

it('✅ passes encoded cy.intercept()', () => {
  cy.intercept(`/search?q=${encodeURI('číslo')}`).as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/search?q=číslo')
    xhr.send()
  })
  cy.wait('@getUrl')
})

it('✅ passes non encoded cy.route()', () => {
  cy.server()
  cy.route('/search?q=číslo').as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/search?q=číslo')
    xhr.send()
  })
  cy.wait('@getUrl')
})
```

<img width="561" alt="Screen Shot 2021-04-26 at 3 18 12 PM" src="https://user-images.githubusercontent.com/1271364/116145204-a2badc80-a6a2-11eb-93e5-111fc0b0b6b8.png">

**Comment by jennifer-shehane** [comment]
We'd accept a PR to change this behavior.

**Comment by Deop** [comment]
Is there any update on this issue? With Cypress v12 cy.route is deprecated, so we are now forced to use cy.intercept. It's a bit painful to edit all URLs to encode some characters, like commas or spaces

**Comment by anbe6083** [comment]
Also wanted to ask for an update regarding this. It's especially painful for URLs which pass characters as a query parameter to sort API results in ascending and descending order

**Comment by Shivangi-23** [comment]
It still does not encode ";" or blank spaces in cypress 7.2.0

example- "param1=A;B;C&param2=D ASC"
It contains ; as well as a blank space for sorting

**Comment by karlhorky** [comment]
@jennifer-shehane should this one be reopened? I guess it hasn't been fixed in Cypress yet.

**Comment by nagash77** [comment]
@karlhorky are you still experiencing this issue in the latest version of Cypress?

**Comment by karlhorky** [comment]
Not really my issue here, so I'm not sure, but last thing that happened in the issue was an announcement that a PR would be accepted, so maybe good to leave it open? I think the bot closing it on a schedule is not a good signal that it's been fixed.

But yeah, if the Cypress team would rather have the issue closed and have a new one reported after frustrated users run into it, not much I can say here 🤷‍♂️
