### ISSUE TITLE
Elements on the page are not loading when Cypress test runner is visiting the page

### ISSUE THREAD

**Issue by VitalyAdweek** [cypress-io/cypress#15952]
A page which has an Ad element (iframe with `<a>` tag deep inside )
With the test I want to check if the element is available on the page and has a link

If the page is visited manually - the Ad is shown
If Cypress is running test - the Ad element is not loading

**### Current behavior**
The element that should contain the ad is not loading

<img width="1770" alt="Screen Shot 2021-04-12 at 6 17 30 PM" src="https://user-images.githubusercontent.com/82416786/114469579-6c1d9600-9bbb-11eb-90eb-dcb7ffd36cea.png">

<img width="999" alt="Screen Shot 2021-04-12 at 6 28 20 PM" src="https://user-images.githubusercontent.com/82416786/114470514-07fbd180-9bbd-11eb-93c0-2a4bb6ab2678.png">

**### Desired behavior**
The ad at the top is shown

<img width="1770" alt="Screen Shot 2021-04-12 at 6 14 28 PM" src="https://user-images.githubusercontent.com/82416786/114469758-ba329980-9bbb-11eb-8d47-d73ddd8312bb.png">

<img width="999" alt="Screen Shot 2021-04-12 at 6 30 14 PM" src="https://user-images.githubusercontent.com/82416786/114470641-3b3e6080-9bbd-11eb-9d53-17bed7ae0dca.png">

**### Test code to reproduce**

```js
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from failing the test
    return false
})

describe('Footer test', () => {

    it.only( 'sample check for ads', function() {
        cy.visit( 'https://stage.adweek.com/performance-marketing/not-all-data-types-are-equally-useful/' )
        cy.frameLoaded( 'iframe[id*="performance-marketing_5"]' )
        cy.iframe('iframe[id*="performance-marketing_5"]')
        .find( '#aw0' )
        .should( 'be.visible' );
    })

})
```

### Versions

macOS Catalina 10.15.7
Cypress 7.0.1
Chrome 89

**Comment by VitalyAdweek** [comment]
I tried the following, but it didn't help:

"chromeWebSecurity": false,
"modifyObstructiveCode": false

**Comment by jennifer-shehane** [comment]
I'm not seeing the issue with the ads not loading at this time. Have you tried accepting the cookies policy banner? Because my ad doesn't load until the banner is accepted. 

<img width="1386" alt="Screen Shot 2021-04-29 at 2 22 36 PM" src="https://user-images.githubusercontent.com/1271364/116606574-8ca55a00-a8f6-11eb-975a-0f69e132a432.png">

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
