### ISSUE TITLE
Unable to sign up at Cypress.io Dashboard using "Email" method due to CORS policy error

### ISSUE THREAD

**Issue by smedustin** [cypress-io/cypress#15965]
### Current behavior
Unable to create a new Cypress.io Dashboard account using the "Signup with email" method. "Something went wrong." error message. Using a Macbook Pro.

Chrome v90.0.4430.70:
`
Access to fetch at 'https://authenticate.cypress.io/login/local-register?source=dashboard' from origin 'https://dashboard.cypress.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

Firefox v87.0:

`
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://authenticate.cypress.io/login/local-register?source=dashboard. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://authenticate.cypress.io/login/local-register?source=dashboard. (Reason: CORS request did not succeed).
`

### Desired behavior
Signup process to proceed.

### Test code to reproduce
Attempt to sign up at https://dashboard.cypress.io/login/email

### Versions

Cypress.io website as of April 13, 2021, 1:45PM CST.

**Comment by tgriesser** [comment]
I was just able to successfully go through the account creation flow in Firefox, Chrome, and Chrome Canary, seeing the appropriate CORS headers for each. Can you provide more details about the requests you're seeing, a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) would to support@cypress.io and reference this ticket?
 
![image](https://user-images.githubusercontent.com/154748/114628593-157c8e80-9c85-11eb-9f4a-19123b3f737b.png)
