### ISSUE TITLE
Add `timings` to `cy.intercept()` objects

### ISSUE THREAD

**Issue by ngalluzzo** [cypress-io/cypress#15969]
`cy.intercept()` seems to be missing the `Duration` property in the response. We use this to ensure our network response times are acceptable - Are there any plans to bring it back? Or are there any workarounds available to do this?

**Comment by flotwig** [comment]
`cy.route()` had an undocumented (but typed) `duration` property, but it was never part of `cy.intercept()`. You can read more about the history of this on this SO answer: https://stackoverflow.com/a/66356009/3474615

---

You could use `cy.intercept()` to manually construct timing information for a request. For example, if you want the total duration of a request and response cycle, you could do something like the following:

```js
let duration

cy.intercept('/something', (req) => {
	const requestReceivedAt = Date.now()
	req.on('response', (res) => {
		duration = Date.now() - requestReceivedAt
	})
}).as('getSomething')

// later...

cy.wait('@getSomething')
.then(() => {
	expect(duration).to.be.whatever
})
```

---

It would be nice to add a timing API for `cy.intercept()` so you don't have to manually measure this. We could add more detail than the old `duration` property allowed. A good template for this is the HAR 1.2 spec, which provides several timing statistics that you are probably used to seeing in the DevTools Network pane. From http://www.softwareishard.com/blog/har-12-spec/#timings :

> blocked [number, optional] - Time spent in a queue waiting for a network connection. Use -1 if the timing does not apply to the current request.
> dns [number, optional] - DNS resolution time. The time required to resolve a host name. Use -1 if the timing does not apply to the current request.
> connect [number, optional] - Time required to create TCP connection. Use -1 if the timing does not apply to the current request.
> send [number] - Time required to send HTTP request to the server.
> wait [number] - Waiting for a response from the server.
> receive [number] - Time required to read entire response from the server (or cache).
> ssl [number, optional] (new in 1.2) - Time required for SSL/TLS negotiation. If this field is defined then the time is also included in the connect field (to ensure backward compatibility with HAR 1.1). Use -1 if the timing does not apply to the current request.
> comment [string, optional] (new in 1.2) - A comment provided by the user or the application.

Cypress could expose all or some of these on the object yielded by `cy.wait()`.

**Comment by ngalluzzo** [comment]
Thanks so much for the workaround @flotwig. I 100% support more timing information!

**Comment by AuToTe5ter** [comment]
@jennifer-shehane any more info on this? Thanks in advance

**Comment by KyorCode** [comment]
This would be really nice to have. As often the case is to have info on the timings.

**Comment by flotwig** [comment]
We would accept a PR that adds timings to `cy.intercept()`, using the same fields and semantics as the HAR 1.2 spec quoted earlier in this thread: https://github.com/cypress-io/cypress/issues/15969#issuecomment-819608114

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this over the years, we’ll close this as not planned.

**Comment by AuToTe5ter** [comment]
> Due to the lack of interest in this over the years, we’ll close this as not planned.

Boooo, never mind we will use Playwright if this is the stance the company takes on implementing something that previously worked

**Comment by thallbeck** [comment]
No action on your behalf doesn't mean lack of interest on ours. Are you saying unless there is a continuous stream of complaints aka squeaky wheels that requests get ignored? Lack of Api timing and performance tools are the top 2 reasons people have to use additional / alternative tools to cypress. Aftervwaiting 2+ years people give up and migrate. This should be reopened and highly prioritized.
