### ISSUE TITLE
Don't fire window.onload events, etc when restoring the DOM snapshot with iframe content

### ISSUE THREAD

**Issue by antonioaltamura** [cypress-io/cypress#15961]
I see the point of the "timeline" feature, but in my case, it is quite annoying: as soon as you hover on an entry in the Cypress log, all the actions are repeated.
This means every time I pass the mouse over an entry there (by mistake) I flood the server with dozens of unnecessary calls.
Is there a way to disable the hover action?

**Comment by jennifer-shehane** [comment]
@antonioaltamura Hovering over the Command Log to see snapshots should **not** repeat actions that were previously completed in the test. It should only preview the state of the DOM at the time the test ran. 

If you're having a situation where calls are being made upon hover of the Command Log, please provide a reproducible example so we can investigate. Thanks.

**Comment by avestura** [comment]
But Is there a way to disable the hover action anyway? I don't need those snapshot histories.

**Comment by avestura** [comment]
> If you're having a situation where calls are being made upon hover of the Command Log, please provide a reproducible example so we can investigate. Thanks.

Here it is: https://github.com/avestura/cypress-request-flood-reproduce
It basically happens when an `iframe` is present in the dom.
Replace [this line](https://github.com/avestura/cypress-request-flood-reproduce/blob/master/src/inner.html#L5) with an API call and you can flood the server with API calls.

**Comment by jennifer-shehane** [comment]
@avestura There's not a built in way to disable the hover but you may be able to hack it to disable it. I know this plugin change the DOM elements in the Test Runner, so it seems like it could be possible. https://github.com/bahmutov/cypress-dark, accompanying blog: https://www.cypress.io/blog/2018/10/11/halloween-theme/

Yah, this makes sense about the iframe. We replace the iframe during snapshots with a placeholder to indicate that the state of the snapshot is not correct in iframes. Seems like when it returns to it's previous iframe state - it will trigger the window.onload event in the iframe again. This is not intended behavior. 

Here is the code for restoring the DOM of the iframe: https://github.com/cypress-io/cypress/blob/develop/packages/runner/src/iframe/aut-iframe.js#L63:L63

`spec.js`

```js
it('snapshot of iframe causing side effect', () => {
  cy.visit('index.html')
})
```

`index.html`

```html
<html>
<body>
  <iframe src="iframe.html"></iframe>
</body>
</html>
```

`iframe.html`

```html
<html>
<head>
  <script>
    window.onload = () => {
      console.log('some side-effect')
    }
  </script>
</head>
<body>
  <h1>Hello</h1>
</body>
</html>
```

![](http://g.recordit.co/ay9KIq2grK.gif)

**Comment by avestura** [comment]
> There's not a built-in way to disable the hover but you may be able to hack it to disable it.

For those who might want to disable the hover actions of the command logs, here is a quick hack:
put this in your `index` file:

```javascript
Cypress.$(parent.window.document.head).append("<style>.reporter .command { pointer-events: none; }</style>")
```
