### ISSUE TITLE
Improve the Chai type definitions to enable autocompletion of assertion arguments

### ISSUE THREAD

**Issue by mardukbp** [cypress-io/cypress#15977]
### What would you like?

When writing a Chai assertion such as

```js
expect(obj.field).to.be.a('string')
```

I would like to have auto-completion for the arguments of `a` (and all other assertions whose arguments are already known).

### Why is this needed?

To save time. Having to look up in the documentation what are the valid values of the arguments costs time. Misspellings are caught at runtime, which also costs time.

### Suggestion for implementation

```typescript
const enum JStypes {
    array,
    error,
    float32array,
    object,
    promise,
    string,
    symbol,
    undefined
}

interface TypeComparison {
    (type: keyof typeof JStypes, message?: string): Assertion;
    instanceof: InstanceOf;
    instanceOf: InstanceOf;
}
```

**Comment by sainthkh** [comment]
Cypress simply imports the type from `@types/chai`. I think the issue should be more appropriate for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
