### ISSUE TITLE
Github action fails with `cypress run --record --key <record_key>` and requires manual re-run

### ISSUE THREAD

**Issue by NorfeldtAbtion** [cypress-io/cypress#15972]
### Current behavior

Not sure if this is related to https://github.com/cypress-io/cypress/issues/1193 but I have recently had the experience that I had to go in and trigger a re-run of my github action because of an error message

```sh
cypress run --record --key <record_key>
```

During the re-run it does not fail and everything passes

### Desired behavior

Not being so flaky about the `record_key` and differ between an auto and manual started CI test.

### Test code to reproduce

https://github.com/Norfeldt/react-kitchen-sink/pull/161/checks?check_run_id=2340237479

### Versions

usr/local/bin/npx cypress cache list
┌─────────┬───────────────────┐
│ version │ last used         │
├─────────┼───────────────────┤
│ 6.8.0   │ a few seconds ago │
└─────────┴───────────────────┘

**Comment by jennifer-shehane** [comment]
Please see the section under parallelization in our GitHub Action with the Warning. In order to rerun github actions, you'll need to pass a custom ci-build-id so that the rerun is recognized correctly. https://github.com/cypress-io/github-action#parallel

<img width="887" alt="Screen Shot 2021-04-30 at 2 00 06 PM" src="https://user-images.githubusercontent.com/1271364/116741997-6518c500-a9bc-11eb-848a-b06717175ec5.png">

**Comment by NorfeldtAbtion** [comment]
@jennifer-shehane thank you for this tip. However the issue is more about that the test keeps failing..

**Comment by jennifer-shehane** [comment]
If you're concerned about a test being flaky. We'd need to have a reproducible example to investigate. There are a 1,000 reasons why a test could be flaky and not necessarily attributable to a bug in Cypress.

**Comment by NorfeldtAbtion** [comment]
Sounds great @jennifer-shehane - I have a repoducible example at https://github.com/Norfeldt/react-kitchen-sink/pulls - you can fork it try it out if you are up for it 😀

**Comment by jennifer-shehane** [comment]
@NorfeldtAbtion Can you link to a specific action that had this rerun issue? I saw you initially linked to the 'Bump react-masonry-css' action, but don't see the initial Cypress tests having failed there: https://github.com/Norfeldt/react-kitchen-sink/actions?query=branch%3Adependabot%2Fnpm_and_yarn%2Freact-masonry-css-1.0.16

**Comment by NorfeldtAbtion** [comment]
Sorry, I gave up on using Cypress record and ripped it out of my CI

**Comment by NorfeldtAbtion** [comment]
Will have a another project with cypress in the near future and will give it another try.
