### ISSUE TITLE
[7.1.0][Component tests] Can't run test on Windows OS

### ISSUE THREAD

**Issue by taninnazar** [cypress-io/cypress#15976]
### Current behavior
With all the latests changes I can see spec files and can run them in Cypress Component Test Runner. But if you will try to run tests with `npx cypress run-ct` command you will see that tests are not running at all
![Screenshot_2](https://user-images.githubusercontent.com/11903748/114679930-50c69e00-9d15-11eb-837c-1391dcfed37d.png)

### Desired behavior
Tests should run with `npx cypress run-ct` on Windows os

### Test code to reproduce
https://github.com/lmiller1990/cypress-react-template

### Versions
OS: Windows10
@cypress/react: 5.3.3
@cypress/webpack-dev-server: 1.1.3
cypress: 7.1.0

**Comment by taninnazar** [comment]
File with debug of run - 
[Cypress_run_debug.txt](https://github.com/cypress-io/cypress/files/6316114/Cypress_run_debug.txt)

**Comment by elevatebart** [comment]
Hello @taninnazar,
Thank you for taking the time to file the windows issues. 
This helps a lot.

I am testing more thoroughly now on my windows machine.
I see what you are seeing and am investigating.

See you on the other side (AKA when I will know more)

**Comment by elevatebart** [comment]
Hello @taninnazar,
Thank you for taking the time to file the windows issues. 
This helps a lot.

I think I found the bug—another instance of the backlash battles. I will report back soon, hopefully with a fix.

**Comment by jennifer-shehane** [comment]
This was released in 7.2.0.
