### ISSUE TITLE
[7.1.0][Component tests] Fonts are not applying in tests on Windows OS

### ISSUE THREAD

**Issue by taninnazar** [cypress-io/cypress#15975]
### Current behavior
While running tests I see warning messages in browser console and also font are not applying to texts in test.
That's similar to this one issue - https://github.com/cypress-io/cypress-react-unit-test/issues/284
![Screenshot_3](https://user-images.githubusercontent.com/11903748/114679216-a3538a80-9d14-11eb-951d-3be7ab6adcda.png)

### Desired behavior
Should apply fonts in tests 

### Versions
OS: Windows10
@cypress/react: 5.3.3
@cypress/webpack-dev-server: 1.1.3
cypress: 7.1.0

**Comment by lmiller1990** [comment]
How are you including the fonts? `import`? Some other way? Can you please share your test so I can reproduce it (just copy paste the test/component here - I can set up a repo myself).

**Comment by taninnazar** [comment]
Try this example - https://github.com/taninnazar/cypress-cra-typescript/tree/error-on-loading-fonts
@lmiller1990 FYI:  @bahmutov has already fixed that issue earlier. When it was in `cypress-react-unit-test`

**Comment by lmiller1990** [comment]
This is getting looked into.

**Comment by elevatebart** [comment]
Hello @taninnazar,

I believe I fixed this issue in [this commit](https://github.com/cypress-io/cypress/commit/7340851097c792ca0d8d3157c3d803dccdd905d2) 
It will be delivered on Monday If all goes well, with version 7.1.1.

If you can't wait, there is a way to install the preview tar.gz of the binary.
To find it, scroll to the very bottom of the commit page ;)

Fingers crossed,
Thank you for your patience

**Comment by taninnazar** [comment]
Thanks
