### ISSUE TITLE
Missing elements on the page

### ISSUE THREAD

**Issue by VitalyAdweek** [cypress-io/cypress#15994]
Block loads fine when visiting the page manually
But not loading when using Cypress

**### Current behavior**
Block is missing

<img width="998" alt="Screen Shot 2021-04-14 at 6 38 38 PM" src="https://user-images.githubusercontent.com/82416786/114789762-986b1b00-9d51-11eb-99ff-1dbf85a5fdfc.png">

**### Desired behavior**
Block is loaded

<img width="1737" alt="Screen Shot 2021-04-14 at 6 34 57 PM" src="https://user-images.githubusercontent.com/82416786/114789648-6ce83080-9d51-11eb-92d1-1a1b10a53ed1.png">

### Test code to reproduce

```
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from failing the test
    return false
})
it( 'sample test', function() {
    cy.visit( 'https://stage.adweek.com/performance-marketing/not-all-data-types-are-equally-useful/' )
    cy.get('#text1').should( 'be.visible' );
})
```

**I tried the following, but it didn't help:**
```

"modifyObstructiveCode": true/ false,
"chromeWebSecurity": true/ false,
"experimentalSourceRewriting": true/ false

```
### Versions

macOS Catalina 10.15.7
Cypress 7.0.1
Chrome 89

**Comment by bahmutov** [comment]
From what I see the working iframe has the content inside the lightbox. The working page has the lightbox scripts loaded

<img width="1076" alt="Screen Shot 2021-04-15 at 8 56 19 AM" src="https://user-images.githubusercontent.com/2212006/114872703-91cbba80-9dc8-11eb-87a4-17ec11f846cd.png">

The page during Cypress test has NO lightbox scripts loaded, I am not sure what logic your server uses to include those script tags, but seems it is not handling loading the page during the test

<img width="764" alt="Screen Shot 2021-04-15 at 8 56 25 AM" src="https://user-images.githubusercontent.com/2212006/114872814-a9a33e80-9dc8-11eb-88ba-3acf38119419.png">

I think you should debug these script tags.
