### ISSUE TITLE
Configuration option to run specific specs/tests

### ISSUE THREAD

**Issue by ScottAgirs** [cypress-io/cypress#15996]
### What would you like?
I was digging through the docs to find a way to specify which specs to run.

Best I could find was via CLI 

```bash
cypress run --spec "cypress/integration/examples/actions.spec.js"
```

What I was hoping to find is a way to provide, for example, an array of paths to either specs of folders that could be added to some config file.

### Why is this needed?
This would help in development to test specific specs without the need to providing them via CLI each time. Especially useful if there are several specs to test, and especially useful if different ones need to be tested.

**Comment by abhidp** [comment]
@ScottAgirs `cypress run` is a very basic way of running tests. As your project grows bigger you will need a lot of different custom configuration to execute your tests with. 

Its better to use [Cypress Module API](https://docs.cypress.io/guides/guides/module-api) to programatically run your tests using node process. 

create a `cypress.run.js` file in your project and an npm script in your package.json like so: 
`{ "cy:run": "node cypress.run.js"}` and call it using npm or yarn : `npm run cy:run`

The magic happens in your `cypress.run.js` file where you can pass all sorts of custom config and arguments(refer docs for more)
In your case, if you want to run a specific set of tests, you can pass an array of all the files under the `config` object of the `option` that is needed by `cypress.run(options)` or can directly pass it to the `spec` property of the `options`. See example below.

see documentation for config: https://docs.cypress.io/guides/references/configuration#Folders-Files

```javascript
//cypress.run.js

// you can either use the `spec` property or `config.testFiles` property in runOptions. Your choice

; (async () => {
  const runOptions = {
    headless: true,
    parallel: true,
    record: true,
    browser: 'chrome',
    spec: './cypress/integration/examples/actions.spec.js' // refer module api docs
    config: {
      testFiles: '**/*.spec.js' // refer configuration docs
    }
  }
  await cypress
    .run(runOptions)
    .then((results) => {
      console.log(results)
    })
    .catch((err) => {
      console.error(err)
    })
})()
```
If you need more help, lemme know

**Comment by akselsoft** [comment]
It would still be very handy to be able to do this within the Test Runner. Let me know if I should add this as a separate issue.

**Comment by bahmutov** [comment]
You can use the option `testFiles` to list only specific files or wildcards https://on.cypress.io/configuration#Folders-Files

For example to run all smoke specs plus "a-spec.js" you can put the following array into cypress.json file

```json
{
  "testFiles": [
     "cypress/integration/smoke*.js",
     "cypress/integration/a-spec.js"
  ]
}
```

**Comment by abhidp** [comment]
> It would still be very handy to be able to do this within the Test Runner. Let me know if I should add this as a separate issue.

Its super easy to do with Test runner also, if you use Cypress module API as I explained above. Instead of `cypress.run(options)` , you have to use `cypress.open(options)` in a file called `cypress.open.js` and open it using node process - `node cypress.open.js`

**Comment by ScottAgirs** [comment]
Hello gents, thanks all for the suggestions, this is awesome! Will give this a go 🙌🏼

**Comment by akselsoft** [comment]
Thanks @abhidp  - that works great!

**Comment by tnrich** [comment]
Just curious @abhidp, will `cypress.open(options)` open the spec in the test runner *and* run it in the test run, or just open it?

Thanks!

**Comment by abhidp** [comment]
> Just curious @abhidp, will `cypress.open(options)` open the spec in the test runner _and_ run it in the test run, or just open it?
> 
> Thanks!

@tnrich The test runner will just open with specified tests in the `options` object. It won't run. Its the same behaviour as `npx cypress open`. To run the tests you will still need to click on the specs in the left panel.

**Comment by tnrich** [comment]
@abhidp hmm makes sense but that is unfortunate. There should be a flag IMO that would allow the first test in the suite to start running automatically. 

@bahmutov @jennifer-shehane  is there already an issue requesting that flag?

**Comment by bbsilverado** [comment]
I am having issues running specific scripts using the --spec option. it seems to be skipping the first and last scripts noted in the quotes
