### ISSUE TITLE
Element exists but erroring out because zero result is found from filter

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#15993]
### Current behavior

Please refer to image. At times, this filter will return 0 result. It works fine when there is result being returned from same filter/query.

<img width="593" alt="Untitled15" src="https://user-images.githubusercontent.com/2043287/114786716-75ca0980-9d33-11eb-8da2-a6c57bbec7d8.png">

### Desired behavior

I would expect it to return zero element rather erroring out. Please provide an alternative in the mean time. Thanks.

### Versions

Cypress: 7.1.0, Electron 89
Chrome: 89.0.4389.128
Mac: 11.0.1

**Comment by bahmutov** [comment]
Can you provide a small reproducible example showing the problem please?

**Comment by quad5** [comment]
Hi, please try the following:

`describe.only('issue', function() {
    it('should return 0 result', function() {
        cy.visit('./cypress/has0result.html')
        cy.get('.prefs-goals .bubble-group .account-bubble').not('.hide').not('.type-more')
    })
    it('should return 1 result', function() {
        cy.visit('./cypress/has1result.html')
        cy.get('.prefs-goals .bubble-group .account-bubble').not('.hide').not('.type-more')
    })    
})`

[has0result.html.txt](https://github.com/cypress-io/cypress/files/6322162/has0result.html.txt)
[has1result.html.txt](https://github.com/cypress-io/cypress/files/6322163/has1result.html.txt)

**Comment by quad5** [comment]
@bahmutov - please review my latest information. Thanks.

**Comment by jennifer-shehane** [comment]
The example provided appears to be working as expected for me. You are requesting all the DOM elements that are NOT with class `hide`, which returns 1 element, then further filtering to DOM element that do NOT have the class `type-more`, which the last element does have this class, so it returns 0. 

If you'd like to assert that this query does return 0 elements, then chain an assertion off of the query as such to prevent failing the test. 

```js
it('should return 0 result', function () {
  cy.visit('has0result.html')
  cy.get('.prefs-goals .bubble-group .account-bubble')
  .not('.hide')
  .not('.type-more')
  .should('have.length', 0)
})
```

<img width="625" alt="Screen Shot 2021-04-26 at 1 08 24 PM" src="https://user-images.githubusercontent.com/1271364/116130167-86ae3f80-a690-11eb-8e2d-8f7f6c8918a5.png">

**Comment by quad5** [comment]
The problem is that I don't know when our application shows 0 or > 0 result(s). So I don't know expected value ahead of time to assert. And Cypress errors out when application returns 0 result.

**Comment by jennifer-shehane** [comment]
Yeah, you won't be able to write it this way then. You may want to look through this thread, but you'll have to query the DOM outside of Cypress if you don't want Cypress assertions enforced around it. https://github.com/cypress-io/cypress/issues/3757

**Comment by quad5** [comment]
Thanks for confirming. I use jquery in `then` block instead and it seems to work.

**Comment by podfran** [comment]
The `should('have.length.gte', 0)` does not seem to work in 13.16. I get a `Timed out retrying after....`. Is there any other way to get the expected behaviour?
