### ISSUE TITLE
add command cy.not()

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#16]
Add command `cy.not()` to filter out elements from a set of matched elements. This will provide an opposite command to the already implemented `cy.filter()`.

**Example:**
```html
<ul>
  <li>list item 1</li>
  <li class="active">list item 2</li>
  <li>list item 3</li>
</ul>
```

```js
cy.get("li").not(".active")
```

**Comment by brian-mann** [comment]
Fixed in `0.4.4`. [Changelog](https://github.com/cypress-io/cypress/wiki/Changelog#044-04092015)
