### ISSUE TITLE
cy.contains() error when specifying selector should be more specific.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#160]
When `cy.get('ul').contains('foo')` errors, it prints:
```
Expected to find content: 'foo' within the element: 'ul' but never did.
```

When `cy.get('ul').contains('li', 'foo')` errors, it prints:
```
Expected to find content: 'foo' within the selector: 'li' but never did.
```

In the second scenario, when a selector is passed to contains, it would be helpful to also print the current subject with the selector (esp since we could be in an unexpected scope). This error message is preferable:
```
Expected to find content: 'foo' within the selector: 'li' within the element: 'ul' but never did.
```

**Comment by brian-mann** [comment]
Fixed in [`0.16.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0162-06112016).
