### ISSUE TITLE
Chrome window opened by Cypress keeps asking to add printer

### ISSUE THREAD

**Issue by dcastil** [cypress-io/cypress#1600]
### Current behavior 
I have a printer in my wifi network. Every time I run a Cypress test locally, the Chrome instance Cypress opens to run the tests in shows a notification whether I want to add the newly found printer in my network to Google Cloud Print. This gets quite annoying after some time.
<img width="394" alt="Google Chrome Cloud Print message" src="https://user-images.githubusercontent.com/31006608/38819438-a689cac0-419b-11e8-9caa-fea5b91bccbb.png">

### Desired behavior
Deactivate the Google features of Chrome and prevent the notification from showing up by default as it isn't necessary for test execution.

### Steps to reproduce

Add a printer to your network, `npm run cypress:open` and run any test locally.

### Versions  
Cypress v2.1.0
Chrome v65
Mac OS v10.13.4

**Comment by jennifer-shehane** [comment]
I believe that the [`--disable-device-discovery-notifications`](https://peter.sh/experiments/chromium-command-line-switches/) Chromium flag may silence these notifications. 

Could you try adding this to your `cypress/plugins/index.js` file and let me know if this works? 

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--disable-device-discovery-notifications')
      return args
    }
  })
}
```

If this works, we can very easily automatically do this in Cypress when launching Chrome.

**Comment by brian-mann** [comment]
@dcastil can you verify that this indeed silences that prompt? If so we can add this to the default chrome arguments.

**Comment by dcastil** [comment]
@jennifer-shehane @brian-mann I'm in the office in 14h again, I'll tell you then if it worked. But thank you for the quick fix!

**Comment by dcastil** [comment]
@jennifer-shehane @brian-mann Can confirm, it works. 🎉

**Comment by jennifer-shehane** [comment]
I'm actually going to keep this issue open until we add `--disable-device-discovery-notifications` to Cypress' default chromium flags as a fix for everyone.

**Comment by jennifer-shehane** [comment]
Default chromium flags passed in Cypress can be found here: https://github.com/cypress-io/cypress/blob/issue-1601/packages/server/lib/browsers/chrome.coffee#L16
