### ISSUE TITLE
if/else does not work properly

### ISSUE THREAD

**Issue by indirandira** [cypress-io/cypress#16008]
Hai, I have an issue in my code 

cy.get('.auth0-lock-form ').then((signin)=>{
            
         console.log(signin.find('div .auth0-lock-last-login-pane'))

            if(signin.find('div .auth0-lock-last-login-pane').length > 0){
                cy.contains('Not your account?').click()
                cy.login(email,pass)
            }else{
                cy.login(email,pass)
            }
        })

the element is true it run the else condition if condition unqualified but if condition is qualified it run the else statement to. is it something wrong in my code?

**Comment by bahmutov** [comment]
You can debug the code by placing the `debugger` keyword in the `.then` block, see the https://on.cypress.io/debugging

If you still think there is a problem, please comment on this issue with a reproducible example / screenshots / etc showing what you expect to see vs what happens during the test

Tip: there is also `cy.pause` command https://on.cypress.io/pause that is really handy
