### ISSUE TITLE
Update 'runs' tab in Desktop to handle API endpoint changes to 'builds'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1601]
The API endpoint has changed to `GET` `builds` with new object schema. The `runs` tab should:
- Use the new endpoint
- Test that fixtures match new object schema.

**Comment by brian-mann** [comment]
@jennifer-shehane I don't see this linked to a PR... is this an old issue?

**Comment by jennifer-shehane** [comment]
Close in favor of https://github.com/cypress-io/cypress/issues/1702
