### ISSUE TITLE
HTML elements and styles are removed when taking screenshots

### ISSUE THREAD

**Issue by tinganho** [cypress-io/cypress#16014]
### Current behavior

It seems Cypress removes some HTML elements from our app right before taking a screenshots, notice the canvas rectangle in the middle:
![image](https://user-images.githubusercontent.com/1324476/114895863-20aff580-9e10-11eb-9840-433e02de9c26.png)

During screenshot, the text is removed also the color is removed it seems.
![image](https://user-images.githubusercontent.com/1324476/114895970-38877980-9e10-11eb-9ea7-0bcb91456ea3.png)

And if I console.log the HTML I can see it missing som `<div class="text-line">...</div>` elements:

```html
<div id="p-a"><div id="a" class="text" style="background-color: transparent;"><svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%; overflow: visible; z-index: -1; pointer-events: none; backface-visibility: hidden; outline: transparent solid 1px; box-shadow: none;"><defs></defs><g id="a-65530-group" style="transform: translate(0px, 0px);"><rect id="a-65530-shape" fill="transparent" stroke="transparent" stroke-width="0" stroke-linejoin="square" stroke-linecap="butt" stroke-dasharray="" width="100" height="100" rx="0"></rect></g></svg><div class="center" style="width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;"><div class="text-content" spellcheck="false" style="outline: none; position: relative;"></div></div></div></div><svg xmlns="http://www.w3.org/2000/svg" width="250" height="250" style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%; overflow: visible; z-index: -1; pointer-events: none; backface-visibility: hidden; outline: transparent solid 1px; box-shadow: none;"><defs></defs><g id="creative-342240-group" style="transform: translate(0px, 0px);"><rect id="creative-342240-shape" fill="rgba(255,255,255,1)" stroke="transparent" stroke-width="0" stroke-linejoin="square" stroke-linecap="butt" stroke-dasharray="" width="250" height="250" rx="0"></rect></g></svg>
```

I think it also removes some styles on the canvas(big white rectangle). We build up style in the canvas using  [CSSStylesheet](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet)
### Desired behavior

It should not remove HTML and styles.

Would be good if we knew how we could get around this? It's a deal breaker right now for us in adopting Cypress.

### Test code to reproduce

```ts
it('canvas — Can present canvas', () => {
            cy.visit(baseUrl + '/brand/1/creativeset/1/editor/1/1/1?version=1');
            cy.get('#canvas').should('be.visible');
            cy.get('body').type('T');
            cy.get('#canvas').dblclick();
            cy.contains('Type');
            cy.get('#b0').screenshot({
                onBeforeScreenshot(el): void {
                    console.log(el[0].innerHTML)
                }
            });
        });
```

Sorry, don't know how to reproduce this :(
### Versions

  cypress@7.0.1
  cypress-plugin-snapshots@1.4.4

**Comment by lmiller1990** [comment]
Odd. Basically during a screenshot we hide all our the Cypress UI, so just the `<iframe>` where you app is rendered is showing. We take the screenshot, then revert everything - the `<iframe>` is an entirely separate document, so nothing should be affected. 

If you are able to provide a minimal reproduction, I could look into it. As it stands it's pretty difficult to investigate - I have a few apps using a `<canvas>`, but I did not expect this problem. Could you try ripping the core of your app into a small demo perhaps?

**Comment by tinganho** [comment]
@lmiller1990 I could create some sort of a minimum:

https://github.com/tinganho/cypress-bug

It's not as in my screenshot above. But, the text is removed at least.

**Comment by bahmutov** [comment]
From the example provided in https://github.com/cypress-io/cypress/issues/16014#issuecomment-821058159

- there is CSS transitions styling that fades the elements, you can see it when going through the commands on the left

![fade-in](https://user-images.githubusercontent.com/2212006/115068514-5ca29380-9ec0-11eb-86d6-e8f018ee682e.gif)

So I believe the same happens when taking the screenshot and our https://on.cypress.io/screenshot command does not disable this particular CSS animation for some reason.

- when deleting ALL CSS styles the element's screenshot is taken correctly

![Bug -- bug](https://user-images.githubusercontent.com/2212006/115068328-2107c980-9ec0-11eb-90dd-44498d9d78f9.png)

So the question is why and which CSS property does this. There is a LOT of CSS in that little page

**Comment by bahmutov** [comment]
Ok, found it

```css
.creative[_ngcontent-hcm-c190] {
  background: #fff;
  width: 100%;
  height: 100%;
  opacity: 1;
  -webkit-animation: canvas-creative-show 0.2s ease 0.2s;
          animation: canvas-creative-show 0.2s ease 0.2s;
  -webkit-animation-fill-mode: forwards;
          animation-fill-mode: forwards;
  box-shadow: 0 0 0 1px transparent;
}
@-webkit-keyframes canvas-creative-show {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@keyframes canvas-creative-show {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```

@chrisbreiding is the above animation with keyframes something our `cy.screenshot` should be capable of turning off via `disableTimersAndAnimations`?

**Comment by tinganho** [comment]
@bahmutov thanks for looking into this. I just tried to remove that animation. It seems to have resolved the issues I have. The remove HTML is also back, strange?

Anyway I will close this issue then.
