### ISSUE TITLE
cookie expected null to exist after POST login request

### ISSUE THREAD

**Issue by IgorStotskyy** [cypress-io/cypress#16018]
After POST request I should expect sessionid to exist, but instead of I got null to exist, after that I can't make any GET request, it gives me 403 error
https://user-images.githubusercontent.com/81786311/114917192-ab362c00-9df3-11eb-90da-15a00c9317a1.png

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
