### ISSUE TITLE
[Regression] onBeforeLoad option on cy.reload Not Working in Cypress 7.1.0

### ISSUE THREAD

**Issue by todd-m-kemp** [cypress-io/cypress#16028]
### Current behavior

The `onBeforeLoad` option no longer works when used with `cy.reload()` in Cypress 7.1.0.

### Desired behavior

The `onBeforeLoad` option used with `cyr.reload()` as it had done in prior Cypress versions. For example, there was no difficulty in using it with Cypress 6.6.0.

### Test code to reproduce

```js
context('onBeforeLoad Issue with Reload', function () {
  it('cy.visit', function () {
    cy.visit('https://wikipedia.org', {
      onBeforeLoad() {
        console.log('works for visit');
      },
    });
    cy.reload({
      onBeforeLoad() {
        console.log('works for reload');
      },
    });
  });
});
```

The test passes in both Cypress 6.6.0 and Cypress 7.1.0 but if you check the console you can see the that the `onBeforeLoad` option worked in Cypress 6.6.0 but not in Cypress 7.1.0.

In Cypress 6.6.0:

![image](https://user-images.githubusercontent.com/62152998/115023655-16800c80-9e8d-11eb-8a91-06af977782ef.png)

In Cypress 7.1.0:

![image](https://user-images.githubusercontent.com/62152998/115023974-77a7e000-9e8d-11eb-81e4-145c55baddc8.png)

### Versions

Cypress 7.1.0 in Chrome 89 on macOS 10.15.7.

### Additional notes

When searching to see if this issue was already logged, I came across #1895 which seems to suggest this option was never implemented for `cy.reload` which is strange but it clearly used to work in a past Cypress version. 🤔

**Comment by jennifer-shehane** [comment]
This changed in 7.0, but I don't actually see an `onBeforeLoad` option ever having been documented or implemented for `cy.reload()`. So I'm not sure why this was initially logging the console.log, but it's probably for another reason we aren't expecting. 

I would say this needs to be implemented and documented in order for us to support it. https://github.com/cypress-io/cypress/issues/1895
