### ISSUE TITLE
'test:after:run' for TypeError: spawn is not a function

### ISSUE THREAD

**Issue by ctan66** [cypress-io/cypress#16029]
### Current behavior

It threw the error "TypeError: spawn is not a function". When executing the spawn code in node environment, it can invoke the batch file successfully. However, if put inside 'test:after:run' event fires after a run is finished and it threw error "TypeError: spawn is not a function"

### Desired behavior

After the 'test:after:run', it needs to trigger the batch file to process and update the test results into the Jira system.

### Test code to reproduce

```js
Cypress.on('test:after:run', (attributes, runnable) => {

 const { spawn } = require('child_process');
    const bat = spawn('cmd.exe', ['/c', 'C:\\test.bat'], { shell: true });
  
    bat.stdout.on('data', (data) => {
      console.log(data.toString());
    });    
    bat.stderr.on('data', (data) => {
      console.error(data.toString());
    });    
    bat.on('exit', (code) => {
      console.log(`Child exited with code ${code}`);
    });   
})
```

### Versions
v7.1.0

**Comment by jennifer-shehane** [comment]
What file in your project do you have this code running within? 

You should make sure to put this within a `cypress/support` folder so that it executes within the context of Node and not the browser. The code runs fine for me. 

```
// cypress/support/index.js
Cypress.on('test:after:run', (attributes, runnable) => {

  const { spawn } = require('child_process');
  const bat = spawn('cmd.exe', ['/c', 'C:\\test.bat'], { shell: true });

  bat.stdout.on('data', (data) => {
    console.log(data.toString());
  });
  bat.stderr.on('data', (data) => {
    console.error(data.toString());
  });
  bat.on('exit', (code) => {
    console.log(`Child exited with code ${code}`);
  });
})
```

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
