### ISSUE TITLE
Mount snapshots give incomplete picture

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16031]
### Current behavior
There seems to be a fundamental flaw with the current state of `mount` snapshots. The tick after a `mount` is not necessarily the settled state of the component, and yet we offer no mechanism to wait for the settled state. Additionally, since the component may not be settled, the DOM snapshot we take may be confusing to the user.

Imagine a component like https://codesandbox.io/s/react-playground-forked-f54u6?file=/Hello.js. On first render, the component doesn't display anything, but the `useEffect` ticks after the first render is committed and causes a new render, this time displaying the `value` prop. Currently, our snapshots will show only the empty component, _even though_ the resting state of the AUT (what the user sees outside of the snapshot) will show `value`.

### Desired behavior
* At minimum, the user is notified that there was rendered data in between the snapshot and the next Cypress command, or the end of the test, whichever comes first.
* We expose [React's act() method](https://reactjs.org/docs/testing-recipes.html#act) to allow Cypress to wait on the stable state of the component.
* Possibly we expose some sort of settings to let snapshots wait on render stability with some timeout (this would also halt the Cypress command chain).

### Test code to reproduce
See https://codesandbox.io/s/react-playground-forked-f54u6?file=/Hello.js for an example component demonstrating this issue.

**Comment by JessicaSachs** [comment]
This issue requires a lot of discussion. Can the outcome can be coming up with a proposed solution?

**Comment by narinluangrath** [comment]
Shameless plug for my solution to this problem using Mutation Observer: https://github.com/narinluangrath/cypress-wait-for-stable-dom

**Comment by ZachJW34** [comment]
Related: https://github.com/cypress-io/cypress/issues/24138

**Comment by rockindahizzy** [comment]
This was solved in #24138. If this is still an issue feel free to reopen.
