### ISSUE TITLE
Typescript definition conflict, when including cypress types in create react app 

### ISSUE THREAD

**Issue by neiltownsley** [cypress-io/cypress#1603]
### Current behavior: 
When cypress types are included by tsconfig in cypress root folder and ```/// <reference types="Cypress" />``` exists inside cypress integration spec, any reference to jest in a react component test eg expect() is overwritten and now seems to reference chai expect()

Also it looks like cypress is not able to pick up the types that have been defined inside its own tsconfig, hence the need for ```/// <reference types="Cypress" />``` at the top of the test file see ```cypress/integration/app_spec.ts```.

### Desired behavior:
Any reference to jest in a react component test eg expect() is not overwritten.
Cypress is able to pick up the types defined in its own tsconfig file.

### Steps to reproduce:

```git clone  https://github.com/neiltownsley/react-typescript-cypress```

```yarn install```

```yarn start```

App.test.tsx:
(15,47): Property 'toEqual' does not exist on type 'Assertion'. Did you mean 'equal'?

```yarn cypress open```

cypress opens but can not resolve the domain because of compile errors.

When ```/// <reference types="Cypress" />``` is removed from app_spec.ts

```yarn start```

app_spec.ts:
(4,9): Cannot find name 'cy'.

```js

```

**Comment by neiltownsley** [comment]
Hi, will someone get to look at this today by any chance?

**Comment by bahmutov** [comment]
No, we are busy with 3.0.0 release, but you can look at the types and how they are configured in cypress (look at `types` property in the `node_modules/cypress/package.json`) to come up with a workaround.

**Comment by bahmutov** [comment]
I think https://github.com/neiltownsley/react-typescript-cypress/pull/1 solves your problem

**Comment by neiltownsley** [comment]
yep, it does :-) though I ended up separating cypress from the react app, could not see the benefit in coupling the two as cypress works so nicely independently 👍

**Comment by palashgdev** [comment]
Hi, @neiltownsley https://github.com/cypress-io/cypress/issues/1603#issuecomment-382863065 completely solves the issue but how to tackle with the root eslint any workaround?

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
```

**Comment by palashgdev** [comment]
It is resolved by adding the path of the cypress tsconfig to eslint project

**Comment by ppulwey** [comment]
Ich had the same issue with Next.js. This tsconfig.json works for me

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "types": ["cypress", "node", "jest"]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

**Comment by Lemesigor** [comment]
> Ich had the same issue with Next.js. This tsconfig.json works for me
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "es5",
>     "lib": ["dom", "dom.iterable", "esnext"],
>     "allowJs": true,
>     "skipLibCheck": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "noEmit": true,
>     "esModuleInterop": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "jsx": "preserve",
>     "incremental": true,
>     "types": ["cypress", "node", "jest"]
>   },
>   "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
>   "exclude": ["node_modules", "**/*.spec.ts"]
> }
> ```

It was the only solution for me in Next as well. The only cons is that by adding the `specs.tsx` in the `exclude` we neeed to manually import react in all the specs file (which is not needed using the default next ts config)
