### ISSUE TITLE
Error when running Component Testing with TS support file via react-scripts

### ISSUE THREAD

**Issue by oscar-b** [cypress-io/cypress#16035]
### Current behavior

Error when trying to run CT with a support file which is in Typescript:

```
./cypress/support/index.ts 14:39
Module parse failed: Unexpected token (14:39)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| });
| 
> Cypress.Commands.add('login', (userType: keyof UserType, options = {}) => {
| 	const types: UserType = {
| 		admin: {
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js (./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js) 2:30-105
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js
```

### Test code to reproduce

Project is a CRA application, initialised as per documentation like this in `plugins/index.ts`:

```js
const plugins: Cypress.PluginConfig = (on, config) => {
	if (config.testingType === 'component') {
		require('@cypress/react/plugins/react-scripts')(on, config);
	}
	return config;
}
export default plugins;
```

`support/index.ts` looks something like this:

```js
import { UserType } from './types';

Cypress.Commands.add('login', (userType: keyof UserType, options = {}) => {
	// ...
});
```

Been experimenting with the default `tsconfig.json` in the project root as well as `cypress/tsconfig.json` without much luck.

### Versions

```
"@cypress/react": "^5.3.3",
"@cypress/webpack-dev-server": "^1.1.3",
"cypress": "^7.1.0",
```

**Comment by lmiller1990** [comment]
I was not able to reproduce this in our internal test projects: https://github.com/cypress-io/cypress/pull/16132. 

I was able to reproduce in a project outside of our repo, though. I'm looking into what is causing this. I suspect it's some configuration somewhere.

**Comment by lmiller1990** [comment]
Ah, I found the problem. I reproduced in our repo too in the `react-scripts` example. The problem is the default webpack config in `react-scripts` does *not support transpiling files outside of src*. I tested this by moving my `support.ts` file into `src` and changing my `cypress.json` to say `"supportFile": "./src/support.ts"` and it worked.

I will see if we can modify the `react-scripts` plugin on the fly to support transpiling outside of `src` to make usage with Cypress easier. In the meantime, a good work around would be to could move your support file into `src`.

**Comment by lmiller1990** [comment]
I fixed this in https://github.com/cypress-io/cypress/pull/16197. It will go out in the near future (next release).

**Comment by oscar-b** [comment]
@lmiller1990 Very nice, thanks a lot for the fix! :)

**Comment by lmiller1990** [comment]
No problem. I'll make sure this goes out this week. I need it for my project, too!
