### ISSUE TITLE
select('value') cannot contain round bracket ( ) as value

### ISSUE THREAD

**Issue by jimmy-foong** [cypress-io/cypress#16045]
### Current behavior
select() are not able to find and select value with round bracket ( ). Example value: lorem (lorem)

### Desired behavior
select() should be able to find and select value with any special characters

### Test code to reproduce
cy.get('select#dropdownelement').select('Lorem (ipsum)');

### Versions
7.1.0

### Note
Had tested it with no round bracket ( ) and is able to select the desired value

![2021-04-17_16-05-33](https://user-images.githubusercontent.com/80996786/115106331-cb522080-9f96-11eb-998c-eb9838fd7e7b.png)

**Comment by sainthkh** [comment]
Can you give us a reproducible example? I tested with the code below, but it works without fail.

```html
<select>
  <option value="456">apples</option>
  <option value="457 (x)">oranges</option>
  <option value="458">bananas</option>
  <option value="Lorem (Ipsum)">Lorem</option>
</select>
```

```js
it('x', () => {
  cy.visit('index.html')
  cy.get('select').select('Lorem (Ipsum)')
})

```

**Comment by jimmy-foong** [comment]
Code snippet below
```
<select name="valueDropDown">
<option value="111&nbsp;Lorem (Ipsum)">111&nbsp;Lorem (Ipsum)</option>
</select>
```

_Coding using Page object pattern_
Page Code
```
getDropDown() { return cy.get('select#valueDropDown'); }

selectDropDownValue(value) {
	this.getDropDown().select(value);
}
```

Test Case Code
```
pageCode.selectDropDownValue('111&nbsp;Lorem (Ipsum)');
```

**Comment by sainthkh** [comment]
Confirmed that it doesn't work. 

```html
<select>
  <option value="456">apples</option>
  <option value="457 (x)">oranges</option>
  <option value="458">bananas</option>
  <option value="111&nbsp;Lorem (Ipsum)">111&nbsp;Lorem (Ipsum)</option>
</select>
```

```js
it('x', () => {
  cy.visit('index.html')
  cy.get('select').select('111&nbsp;Lorem (Ipsum)')
})
```

**Comment by sainthkh** [comment]
It can be solved by changing `&nbsp;` to `\u00a0` like below:

```js
cy.get('select').select('111\u00a0Lorem (Ipsum)')
```

[credits to this answer](https://stackoverflow.com/a/53306311/1038927)
