### ISSUE TITLE
Tests fail because of exception in console

### ISSUE THREAD

**Issue by Gennadiii** [cypress-io/cypress#1605]
Operating System: Win10
Cypress Version: 1.4.2
Browser Version: Chrome 65
Is this a Feature or Bug?
This is a bug

Current behavior:
I have exception on my app (third party), I can see it in console: TypeError: Cannot read property 'payload' of undefined
And I don't care about it actually. But Cypress fails tests because of it.
I have next in my support/index.js:
`
Cypress.on('fail', (err) => {
  if (err.message.includes('payload')) {
    return false;
  }
  throw err;
});
`
This code never runs.

Desired behavior:
I`d like to ignore such kind of errors since they don't influence the flow I need to test

**Comment by bahmutov** [comment]
This seems to be unlikely, since we test this feature. Could you create a minimal reproduction example by forking http://github.com/cypress-io/cypress-test-tiny (please install your version of cypress there with `npm i -D cypress`) and giving us a link, please?

**Comment by jennifer-shehane** [comment]
Duplicate issue: https://github.com/cypress-io/cypress/issues/1565

Please do not open duplicate issues, comment on the existing issue and we will respond as quickly as we can.
