### ISSUE TITLE
Cy.log only logs first 2 parameters when more then 2 are passed

### ISSUE THREAD

**Issue by okyrylenko** [cypress-io/cypress#16068]
### Current behavior
When passing 2+ parameters to cy.log function only the first 2 are displayed

### Desired behavior
All the passed parameters are logged
In the gist bellow, I am passing 4 strings to cy.log function but only the first 2 are being logged

### Test code to reproduce
link to gist - https://gist.github.com/okyrylenko/190d880dc5ca4b6808d57c5cc29240eb

### Versions

6.8

**Comment by sainthkh** [comment]
I confirmed that it's not working in 7.1.0.

```js
cy.log('s', 1, 2, 3, 4)
```

**Result**

![Screenshot from 2021-04-20 10-07-51](https://user-images.githubusercontent.com/8130013/115322149-54986b80-a1c0-11eb-809b-1a417c1fcfb2.png)
