### ISSUE TITLE
How I can test the drag and drop map marker and test the updated polyline path using Google Maps.

### ISSUE THREAD

**Issue by makasanas** [cypress-io/cypress#16060]
We are looking for option how we can test polyline drag test with cypress. 

any one know any method how to do test for drag polyline with google map

**Comment by connerleverett** [comment]
Have you tried something like this?
```
    getMapCanvas()
        // `pointerId` isn't sent by cypress see https://github.com/cypress-io/cypress/issues/5660
        .trigger("pointerdown", fromX, fromY, {
            pointerId: 1
        })
        .trigger("pointermove", toX, toY, {
            pointerId: 1
        })
        .trigger("pointerup", toX, toY, {
            pointerId: 1
        });
```

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
