### ISSUE TITLE
Cypress docker image - chrome browser setting shows syntax error

### ISSUE THREAD

**Issue by sowmyasridharamurthy** [cypress-io/cypress#16072]
### Current behavior
I Followed the setting mentioned in -- https://gitlab.com/cypress-io/cypress-example-docker-gitlab/-/blob/master/.gitlab-ci.yml

The CI execution shows error as below. There is nothing that i changed in this file not sure how the syntax error is coming up.
![image](https://user-images.githubusercontent.com/35350156/115277132-30974480-a144-11eb-82eb-f1ffd2af9396.png)

I dont face this issue when i run on default electron browser

### Desired behavior
On Build pipeline execution, the tests should run as usual on chrome browser

**Comment by jennifer-shehane** [comment]
Cypress no longer supports Node 10 as part of 7.0+. Assuming you are using Cypress 7+, could you try updating to `cypress/base:12`?
