### ISSUE TITLE
Changing viewport in beforeEach results in DOM flicker

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16071]
### Current behavior
Cypress has user-definable viewports at both compile and runtime. If the viewport is modified before a test run (say in a `beforeEach`), the viewport will flicker from the `cypress.json` configured value (or the default) and the modified viewport as the test begins. This results in unslightly flicker, particularly if this is done consistently in a test, where it shows one viewport, then flickers to a new viewport as the test runs, then flickers back to the first viewport as it begins the next test.

https://user-images.githubusercontent.com/238679/115273927-ffdbee80-a0f4-11eb-8feb-15a7cb93bcfb.mov

### Desired behavior
Somehow stability should be maintained in these scenarios. Whether that is addressed at an API level (a non-`beforeEach` way to set viewport per spec/test) or at a runtime level, I am not sure.

**Comment by jennifer-shehane** [comment]
I think this is expected behavior with the runner, that it resets to default in between tests. Maybe you'll want to switch to using suite level config instead of using the beforeEach?

```js
describe(
  'tests',
  {
    viewportWidth: 1024,
    viewportHeight: 700
  },
  () => {
    it('test 1', () => {
		// test
    })

    it('test 2', () => {
       // test
    )
  }
)
```

**Comment by jennifer-shehane** [comment]
Anyway, kind of related to some other user's complaints https://github.com/cypress-io/cypress/issues/1534
