### ISSUE TITLE
SearchInput hidden with many specs

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16089]
### Current behavior
When the spec list scrolls, the `SearchInput` is hidden off of the top of the screen.

<img width="364" alt="Screen Shot 2021-04-20 at 6 22 19 AM" src="https://user-images.githubusercontent.com/238679/115402938-c365cc80-a1a0-11eb-852f-1e5b325c2f8a.png">

### Desired behavior
The `SearchInput` should be visible

**Comment by jennifer-shehane** [comment]
This was released in Cypress 7.2.0.
