### ISSUE TITLE
webpack external ressources loading on windows fail with bad path

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#16097]
### Current behavior
When importing a custom font within a css file, the path to load the said font is malformed (see repro)

### Desired behavior
Be able to use custom fonts on tests windows

### Test code to reproduce
On windows
Checkout https://github.com/elevatebart/cy-load-fonts
yarn install
yarn cy

### Versions

```
"cypress": "^7.1.0",
"@cypress/vue": "^2.0.0",
"@cypress/webapck-dev-server": "^1.1.3",
```

**Comment by jennifer-shehane** [comment]
This was released. Please update to latest version of webpack-dev-server
