### ISSUE TITLE
Cypress ci command does not support `--spec` argument

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#161]
The docs claim that `cypress ci` supports same arguments as `cypress run`.
But while `cypress run --spec <path>` executes the desired spec file, `cypress ci --spec <path>` returns error: unknown option `--spec'

**Comment by brian-mann** [comment]
That's true. We didn't anticipate anyone wanting to run a single spec file in CI - but I get what you're doing by rolling your own docker container parallelization. 

We'll add this in the next release.

**Comment by bahmutov** [comment]
nice!

**Comment by brian-mann** [comment]
Update to `0.11.1` of the `cypress-cli` npm package and this will work now.

Fixed in [`0.16.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0163-06172016).
