### ISSUE TITLE
should('not.exist') misbehaves when using dirty-chai

### ISSUE THREAD

**Issue by mhelvens** [cypress-io/cypress#1610]
A simple test:

```js
it('check that something does not exist', () => {
  cy.visit('http://www.google.com')
  cy.get('.foobar').should('not.exist')
})
```

When run with `cypress run`, it will pass as expected. When run via `cypress open`, it will pass for the very first test run, but will fail in subsequent runs:

![image](https://user-images.githubusercontent.com/4012816/38923493-994a1272-42f2-11e8-91fb-0456eb635f94.png)

![image](https://user-images.githubusercontent.com/4012816/38923527-acaa86c6-42f2-11e8-86ea-4f489fa3db7e.png)

### Versions  

Cypress 2.1.0
Mac OS 10.13.4 (17E199)
Google Chrome 65.0.3325.181 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
`cypress run` runs your tests in Electron. Could you try using `cypress open` to run the tests and select Electron as the browser to run them in. See if there is anything strange in there with your console open. 

The 'second' run behavior is strange, but we would need a reproducible example to run on our end to look into it further.

**Comment by mhelvens** [comment]
I'm seeing the exact same behaviour with Electron.

If you think it will help I could create a repo with a minimal working example, but my bug report above fully describes the scenario. Nothing complicated going on.

**Comment by mhelvens** [comment]
OK, the problem is apparently [`dirty-chai`](https://www.npmjs.com/package/dirty-chai). Here is a [working example](https://github.com/QubitProducts/cypress-test-tiny/tree/expect-not-to-exist-bug).

We need to use `dirty-chai` where I work, because we enforce [standard](https://standardjs.com) company-wide.

**Comment by jennifer-shehane** [comment]
Yeah, this does seem to be `dirty-chai` conflicting with some Cypress logic. There's not that much code in dirty-chai, so shouldn't be too bad to track down. https://github.com/prodatakey/dirty-chai/blob/master/lib/dirty-chai.js

<img width="551" alt="screen shot 2018-04-18 at 12 24 35 pm" src="https://user-images.githubusercontent.com/1271364/38945078-7c15d23e-4303-11e8-9b36-ba8cb604726a.png">

**Comment by mhelvens** [comment]
Here is [a link to the working example](https://github.com/QubitProducts/cypress-test-tiny/tree/other-dirty-chai-bug) for the other bug just [discussed in Gitter](https://gitter.im/cypress-io/cypress?at=5ae0ccf227c509a7744eb0b3).

Another dirty-chai related bug.

**Comment by mhelvens** [comment]
This seems to still be an issue. A fix would be much appreciated!

**Comment by jennifer-shehane** [comment]
This issue still happens in Cypress 3.4.0

**Comment by jennifer-shehane** [comment]
This issue no longer occurs in 9.5.3. Closing as resolved.
