### ISSUE TITLE
Support better scaffolding experience on user first launch

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#16128]
### Current behavior
When I start to use cypress for component testing but I still don't have an e2e app to test, I still have to setup an empty "integration" folder. If I don't cypress keep creating a ton of probably e2e relevant examples that I do not care about at this point.

### Desired behavior
A way to state that I am ignoring integration for now. 
a `"integrationFolder": false` would do just fine.

### Versions
cypress 7.1.0

**Comment by akauppi** [comment]
Hmm.. I might be in the same boat with you.

What I did today was (Cypress config):

```
  "testFiles": "**/*.spec.js",
  "integrationFolder": "cypress",
```

Why I didn't like the `cypress/integration` naming:

1. I think all my tests are "integration" (SPA against Firebase Emulator) but I don't call them that. Just tests.
2. "cypress/integration/**" would have been an unnecessary directory level, and I like things rather flat.

I always thought "cypress/integration" is just a convention.

**Comment by rockindahizzy** [comment]
No longer applicable after Cypress 10
