### ISSUE TITLE
Issue with integrating cypress with jenkins

### ISSUE THREAD

**Issue by jedwantstocode** [cypress-io/cypress#1612]
### Current behavior: 
I am currently getting this error when trying to run my tests headlessly(jenkins)

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'cypress:run:test:e2e' ]
> 2 info using npm@5.6.0
> 3 info using node@v8.10.0
> 4 verbose run-script [ 'precypress:run:test:e2e',
> 4 verbose run-script   'cypress:run:test:e2e',
> 4 verbose run-script   'postcypress:run:test:e2e' ]
> 5 info lifecycle crumbs-web-ui@1.15.0~precypress:run:test:e2e: crumbs-web-ui@1.15.0
> 6 info lifecycle crumbs-web-ui@1.15.0~cypress:run:test:e2e: crumbs-web-ui@1.15.0
> 7 verbose lifecycle crumbs-web-ui@1.15.0~cypress:run:test:e2e: unsafe-perm in lifecycle true
> 8 verbose lifecycle crumbs-web-ui@1.15.0~cypress:run:test:e2e: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jgates\crumbs-web-ui\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\jgates\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Users\jgates\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin
> 9 verbose lifecycle crumbs-web-ui@1.15.0~cypress:run:test:e2e: CWD: C:\Users\jgates\crumbs-web-ui
> 10 silly lifecycle crumbs-web-ui@1.15.0~cypress:run:test:e2e: Args: [ '/d /s /c', 'node cypress/run-end-to-end-tests-jenkins.js' ]
> 11 silly lifecycle crumbs-web-ui@1.15.0~cypress:run:test:e2e: Returned: code: 1  signal: null
> 12 info lifecycle crumbs-web-ui@1.15.0~cypress:run:test:e2e: Failed to exec cypress:run:test:e2e script
> 13 verbose stack Error: crumbs-web-ui@1.15.0 cypress:run:test:e2e: `node cypress/run-end-to-end-tests-jenkins.js`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid crumbs-web-ui@1.15.0
> 15 verbose cwd C:\Users\jgates\crumbs-web-ui
> 16 verbose Windows_NT 10.0.14393
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cypress:run:test:e2e"
> 18 verbose node v8.10.0
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error crumbs-web-ui@1.15.0 cypress:run:test:e2e: `node cypress/run-end-to-end-tests-jenkins.js`
> 22 error Exit status 1
> 23 error Failed at the crumbs-web-ui@1.15.0 cypress:run:test:e2e script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

### Desired behavior:
I want to run my cypress tests headlessly and in jenkins. I'm a total noob in both.

### Steps to reproduce:

I did follow the npm installation in my project folder. In my package.json, "cypress:run:test:e2e": "node cypress/run-end-to-end-tests-jenkins.js", so when I npm run cypress:run:test:e2e I get the error above.

I have also tried going to where the file is in my commad prompt and run node run-end-to-end-tests-jenkins.js but it does not do anything.
```js

```

### Versions  
Cypress 2.1.0
Windows pro 10
Google Chrome 65.0.3325.181 (Official Build) (64-bit)

**Comment by bahmutov** [comment]
your command is wrong, in your package.json do
```json
{
  "scripts": {
     "open": "cypress open",
     "run": "cypress run"
  }
}
```
Open Cypress once using `npm run open` - it will scaffold the `cypress` folder. Run the tests to get a sense of what Cypress is like - you will be running `cypress/integration/example_spec.js`. Then watch https://docs.cypress.io/guides/getting-started/writing-your-first-test.html and start writing your own test.

**Comment by jedwantstocode** [comment]
This is my package.json:

**Comment by jedwantstocode** [comment]
![dot js file](https://user-images.githubusercontent.com/35259384/38968902-26635a88-43c0-11e8-9f1d-3ba9ddc27758.PNG)
![package dot json](https://user-images.githubusercontent.com/35259384/38968904-2698c6d2-43c0-11e8-974d-8ad8426e1e8e.PNG)

**Comment by jedwantstocode** [comment]
so by running npm run cypress:run:test:e2e, it should call the dot js file. but instead, im getting error posted above. If I do, npm run start, or any other command above, I am not getting the error

**Comment by bahmutov** [comment]
You are making this _way_ overcomplicated. You just want to start the server, wait until it builds the site, then run the tests. So ... to start the server and wait until it is ready and then start the test script use https://github.com/bahmutov/start-server-and-test 

and since this is Angular project, have you had a chance to read https://www.cypress.io/blog/2017/12/11/an-alternative-to-protractor-for-angular-projects/ ?

**Comment by jedwantstocode** [comment]
thank you. I am getting there
