### ISSUE TITLE
Intermittent dropped response bodies

### ISSUE THREAD

**Issue by alyssa-glean** [cypress-io/cypress#16137]
### Current behavior
Very occasionally, we are seeing random flakes in our tests caused by response bodies being unexpectedly absent. We can see from our backend logs that the request was received and handled ok, with a proper JSON body being returned. On the Cypress/browser end, we can see that the request was deemed successful too (via the status code), but then our test blows up because `response.body` is undefined.

### Desired behavior
If there's been some kind of network issue / dropped packets, this should manifest as such and auto-retry (per the `retryOnNetworkFailure` setting). If this *isn't* a network problem, then where has our request body gone? Given that the status code comes through ok, I'm not sure it can be a network thing - instead, it's like the body occasionally gets 'swallowed' somehow by Cypress. I'm guessing you have some code somewhere that intercepts requests in order for stubbing, mocking and so on to work - so perhaps there's a rare bug in there somewhere?

### Test code to reproduce

We've seen this for our in-app API calls as well, but the most recent one I saw was an explicit `cy.request`, the code for which is below:

```js
Cypress.Commands.add('setupUser', (request: Cypress.CreateUserRequest = {}) =>
  cy
    .request({
      method: 'POST',
      url: '/test-helper/create-user',
      body: request,
      ...commonHeadersWithAuth,
    })
    .then(({ body }) => {
      Cypress.log({
        name: 'User Creation',
        message: [`created user ${JSON.stringify(body)}`],
      })
      return body
    })
)
```

What we see logged out in the Cypress video is as follows:

![image](https://user-images.githubusercontent.com/57534485/115713685-33757d80-a36e-11eb-9a86-90eac87a6686.png)

As you can see, the `body` is undefined, when we would be expecting a JSON body containing details of the user we created. As I say, this works the vast majority of the time (our test suite is some 150 tests in size, and is run on a bunch of branches every day) - it's just every now and again that we see this problem (and it's been hard to correlate as a top flake to focus on fixing, because it'll break a different test each time / manifest slightly differently). 

### Versions

 - Cypress version: 6.8.0
 - Browser: Edge 90 (we also run tests on Chrome, but this most recent example happened to be on Edge)
 - OS: Linux (we're using a forked Docker image from https://hub.docker.com/r/cypress/browsers)
 - CI Provider: Jenkins

**Comment by alexburlton-sonocent** [comment]
We encountered this again today, this time on Chrome 88. So not an Edge-specific problem.

**Comment by ui-monorepo** [comment]
Myself and another team member are also seeing this problem. 

```
$ node -v
v16.13.0

"cypress": "^7.2.0",
```

Every intercept has either a defined response body or a forced error, yet empty response bodies are coming through at random.

**Comment by ui-monorepo** [comment]
This issue persists with Cypress version `^9.2.0`.

**Comment by sabarishnarain** [comment]
12.11.0 - issue still persists.

**Comment by AtofStryker** [comment]
Does anyone have a reproduction repository I could run to recreate the issue or is it more of an intermittent issue?

**Comment by AtofStryker** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
