### ISSUE TITLE
'New Spec File' filename adds extra dots

### ISSUE THREAD

**Issue by GregLahaye** [cypress-io/cypress#16131]
### Current behavior

As you can see in the video below, switching between JavaScript and TypeScript in the dialog will add a new dot to the end of the filename each time.

### Desired behavior

No extra dots! My guess would be the extensions here https://github.com/cypress-io/cypress/blob/3700fe7271b016f8a89c5a7a4c40d0af62155b45/packages/server/lib/gui/dialog.ts#L36-L45 shouldn't have dots (e.g. ['.js'] -> ['js']

### Test code to reproduce

https://user-images.githubusercontent.com/16643647/115658592-a4676600-a36b-11eb-9609-e2b8b845b2f0.mp4

### Versions

7.1.0

**Comment by jennifer-shehane** [comment]
This issue doesn't occur for me on Mac, so may be Windows. But also, yes, it should not require the dots for the specified extensions: https://www.electronjs.org/docs/api/dialog#dialogshowopendialogsyncbrowserwindow-options
