### ISSUE TITLE
with chrome browser version 90, cypress is  jump back and forth between main and the middle security url after logging in

### ISSUE THREAD

**Issue by venkata-018** [cypress-io/cypress#16149]
Cypree suite is worked well with chrome browser version till 89. with chrome 90 giving issue ,cypress is  jump back and forth between main and the middle security url after logging in.
Any solutions are helpful

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
