### ISSUE TITLE
Cypress Dasboard show run as Testing in progress when Jenkins job completed parallel execution of 2 instances via pipeline

### ISSUE THREAD

**Issue by inzerion** [cypress-io/cypress#16140]
Hi Cypress team, 
I've prepared jenkins pipeline to execute tests in parallel. Jenkins job completed work but Cypress Dashboard shows that testing is in progress. 
`pipeline {
  agent any
  tools {nodejs "NodeJS 14"}
  environment {
        HOME = pwd()
    	npm_config_cache = '$HOME/.npm'
    	CYPRESS_CACHE_FOLDER = "$HOME/.cache/Cypress"

  }

  stages {
    // first stage installs node dependencies and Cypress binary
    stage('Checkout project') {
      steps {
        //we download code here
      }
    }
    
    stage('Build') {
        steps {
                sh 'npm ci'
        }
    }

    // this stage runs end-to-end tests, and each agent uses the workspace
    // from the previous stage
    stage('cypress parallel tests config') {
      environment {
        // because parallel steps share the workspace they might race to delete
        // screenshots and videos folders. Tell Cypress not to delete these folders
        CYPRESS_RECORD_KEY = 'MY_KEY'
        CYPRESS_trashAssetsBeforeRuns = 'false'
      }

      // https://jenkins.io/doc/book/pipeline/syntax/#parallel
      parallel {
        // start several test jobs in parallel, and they all
        // will use Cypress Dashboard to load balance any found spec files
        stage('tester A') {
          steps {
            echo "Running build ${env.BUILD_ID}"
            sh "\$(npm bin)/cypress run --record --parallel --config-file cypress/configurations/cypress-paas-f2.json --spec **/objects/**/*.spec.js --browser chrome"
          }
        }

        // second tester runs the same command
        stage('tester B') {
          steps {
            echo "Running build ${env.BUILD_ID}"
            sh "\$(npm bin)/cypress run --record --parallel --config-file cypress/configurations/cypress-paas-f2-tenant2.json --spec **/objects/**/*.spec.js --browser chrome"
          }
        }
      }

    }
  }
} `

`
  (Uploading Results)

  - Nothing to Upload

tput: No value for $TERM and no -T specified
================================================================================

  (Run Finished)

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌──────────────────────────────────────────────────────

───────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                       
  Recorded Run: https://dashboard.cypress.io/projects/yky5ro/runs/24                                   

    3) create service via UI and check grid
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
Failed in branch tester B
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
Failed in branch tester A
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 2
Finished: FAILURE`

**Comment by inzerion** [comment]
Run is finished but next line is interesting ​3) create service via UI and check gri - from the left side I see [tester A]. Looks like run completed but not all testers finished their work.

**Comment by liamoar** [comment]
Hi I am facing the same issue my run gets passed successfully but Jenkins's job is not ending. Did you find any solutions?
