### ISSUE TITLE
Cypress formatter

### ISSUE THREAD

**Issue by rudyhadoux** [cypress-io/cypress#16164]
Hi,

Is there an easy way to format Cypress code like Beautify or Prettier ?

**Comment by bahmutov** [comment]
Cypress has nothing specific for code formatting built-in, but you can certainly use Prettier to format your spec source files. We have a pretty detailed blog post showing how to do this, including some ESLint + Cypress ESLint settings integration https://glebbahmutov.com/blog/configure-prettier-in-vscode/

**Comment by rudyhadoux** [comment]
Yes, but why it is not by default ?
Within the installation of Cypress.

**Comment by bahmutov** [comment]
Because Cypress runs your specs, it is not your code editor or code formatter.

**Comment by rudyhadoux** [comment]
With JS-CSS-HTML Formatter plugin, Cypress code is formatted by default.
