### ISSUE TITLE
when using the cypress github action, hyphens in folder names causes cypress to not see the spec file contained within

### ISSUE THREAD

**Issue by carlcartagena** [cypress-io/cypress#16184]
### Current behavior

error:
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

cypress/integration/tests/page-tests/login_test.spec.js

### Desired behavior

this should succeed and perform the test

### Test code to reproduce

cypress/integration/tests/page-tests/login_test.spec.js

all other tests without a hyphen in the folder name succeed

### Versions

6.9.1

**Comment by bahmutov** [comment]
Can you provide the GitHub action YML that you use to invoke Cypress?

**Comment by carlcartagena** [comment]
name: Run Cypress Test
on:
  push:
    - master
  workflow_dispatch:
jobs:    
  cypress-test-page:
    runs-on: ubuntu-latest
    steps:
    - name: ( ) cypress.io - Run Tests
      uses: cypress-io/github-action@v2
      with: 
        working-directory: test
        browser: chrome
        install: false
        spec: cypress/integration/tests/test-pages/test_page.spec.js

**Comment by carlcartagena** [comment]
`name: Run Cypress Test
on:
  push:
    - master
  workflow_dispatch:
jobs:    
  cypress-test-page:
    runs-on: ubuntu-latest
    steps:
    - name: ( ) cypress.io - Run Tests
      uses: cypress-io/github-action@v2
      with: 
        working-directory: test
        browser: chrome
        install: false
        spec: cypress/integration/tests/test-pages/test_page.spec.js`

**Comment by carlcartagena** [comment]
> Can you provide the GitHub action YML that you use to invoke Cypress?

name: Run Cypress Test
on:
  push:
    - master
  workflow_dispatch:
jobs:    
  cypress-test-page:
    runs-on: ubuntu-latest
    steps:
    - name: ( ) cypress.io - Run Tests
      uses: cypress-io/github-action@v2
      with: 
        working-directory: test
        browser: chrome
        install: false
        spec: cypress/integration/tests/test-pages/test_page.spec.js

**Comment by bahmutov** [comment]
Can you try surrounding the spec filename with single quotes? We suggest using single quotes around the URLs for example https://github.com/cypress-io/github-action#wait-on and the spec might need the same in this case.

**Comment by carlcartagena** [comment]
ok this may have been a fluke, it is working now thanks
