### ISSUE TITLE
Cypress 7.1 failing to run intermittently on CircleCI

### ISSUE THREAD

**Issue by tombeckenham** [cypress-io/cypress#16187]
### Current behavior
For some reason every second or third run on Circle is timing out or taking a really long time to run. This started occuring when I upgraded from Cypress 6.8 to 7.1. This is the sort of log we're getting.
[circleCiCypress.txt](https://github.com/cypress-io/cypress/files/6369994/circleCiCypress.txt)
[circleCiCypress2.txt](https://github.com/cypress-io/cypress/files/6370007/circleCiCypress2.txt)
There was also a case yesterday which gave a little more information before timing out:
[circleCiCypress3_reallylong.txt](https://github.com/cypress-io/cypress/files/6370008/circleCiCypress3_reallylong.txt)

### Desired behavior
Cypress to run normally in circle ci without timing out.

### Versions
Last known working 6.8
Version that is not working 7.1

**Comment by jennifer-shehane** [comment]
There are some performance issues introduced in recent versions of Cypress, please see those issues for relevant updates. We're working on them.

- https://github.com/cypress-io/cypress/issues/15853
- https://github.com/cypress-io/cypress/issues/15779
- https://github.com/cypress-io/cypress/issues/16152
- https://github.com/cypress-io/cypress/issues/15973
- https://github.com/cypress-io/cypress/issues/15990

If you are running Cypress in a headless browser, please try reducing the screen size to the default size prior to 7.0 (1280x720) to see if the new issues are related to the increase in screen size. [Instructions here.](https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless) 

If that doesn't resolve the issue, I suggest downgrading to the last known version of Cypress that worked well.

We'll be closing this issue as there are no reproducible actions. For now we need to focus on the performance issues where we're given clear reproducible examples.
