### ISSUE TITLE
Cypress 7 breaks Code Coverage with Create React App

### ISSUE THREAD

**Issue by PhillipRC** [cypress-io/cypress#16186]
### Current behavior

Cypress 7 has removed `Cypress.moment()` - [change log](https://docs.cypress.io/guides/references/changelog#7-0-0)

[@cypress/react package](https://github.com/cypress-io/cypress/blob/develop/npm/react/package.json#L36) references an old version of @cypress/code-coverage that uses `Cypress.moment()`

Running code-coverage fails and throws a moment undefined error

### Desired behavior

To be able to use Cypress 7 and Code Coverage with @cypress/react

Update the [@cypress/react package](https://github.com/cypress-io/cypress/blob/develop/npm/react/package.json#L36) to use the updated [@cypress/code-coverage 3.9.4](https://github.com/cypress-io/code-coverage/releases/tag/v3.9.4) which has removed the `Cypress.moment()` reference

**Comment by lmiller1990** [comment]
That dependency is a `devDependency` - this will not impact you are a user.

Are you having a problem with code coverage? It looks like it should be working fine. The docs are not very up-to-date for 7.0 for the new component testing runner with code coverage - I'll work on updating them now.

I was able to get code coverage to run in this [example repo](https://github.com/lmiller1990/cypress-react-template). It was pretty messy, we should provide a more simple way to set this up.

Here's how I did it:

- add instanbul plugin (`yarn add babel-plugin-instanbul`)
- add [`.babelrc`](https://github.com/lmiller1990/cypress-react-template/blob/master/.babelrc)
- add it to the webpack config on the fly, [see here](https://github.com/lmiller1990/cypress-react-template/blob/f6cd773772cdc544e9f3e1dc47ebd4f381b75438/cypress/plugins/index.js#L8). This was probably the messiest part. I grabbed that code from the [`instrument-cra`](https://github.com/cypress-io/instrument-cra/blob/master/index.js#L62) plugin, which I did not test with Cypress 7.x and component testing (yet).
- added [this import to support/index.js](https://github.com/lmiller1990/cypress-react-template/blob/master/cypress/support/index.js#L2)

I got most of this following instructions [here](https://github.com/cypress-io/code-coverage). I will look into updating docs and making sure this is a smoother experience.

I am not sure regarding the original question about the version of code-coverage - we can definitely update the version in `devDependencies`, but is this causing a problem in your code base?

**Comment by lmiller1990** [comment]
I made an issue to make sure code coverage is easy to set up and all docs are up to date. You can track the progress of this here: https://github.com/cypress-io/cypress/issues/16199

**Comment by lmiller1990** [comment]
https://github.com/cypress-io/cypress/pull/16239/files#diff-8ba8004aba5a8cdc445843c6c835b00f491bc9829664d8ad249f1bcbe7c54ce4 added more docs and examples on code coverage. That devDep should not cause problems - it's only used for our internal test suites and during development in this repo.

If you are still having a problem with code coverage, please open a new issue with a reproduction so we can look into it.
