### ISSUE TITLE
Updated test in Cypress Win EXE does not run automatically

### ISSUE THREAD

**Issue by jonnusmcjon** [cypress-io/cypress#1618]
When I save a test file using the Direct Download win exe, the documentation implies that the browser should re-run the updated file and present the results immediately. Yes, only Step 2 of the Tutorial. For me, the browser (chrome) does absolutely nothing.

The changes only seem to be reflected when I close and re-open the application, which isn't a practical solution every time I make an update to a file.

I note that there are suggestions elsewhere on the web to do something with IntelliJ/Webstorm Safe Save, but I'm editing the file in Notepad++, so have no idea where that configuration would need to happen, if it's even relevant. (plus i think that's a different issue). I also have the problem editing the test file in Visual Studio 2017, Windows Notepad, and Textpad

I'm on Windows 10, running the Direct Download version, via the application GUI (so not using the CLI at all).

What am I missing?

**Comment by jennifer-shehane** [comment]
Yes, Windows users have been reporting this issue of the spec files not causing the test runner to be refreshed. I'll be closing this as a duplicate. Make sure to keep track of this issue here: https://github.com/cypress-io/cypress/issues/712
