### ISSUE TITLE
Inconsistency Between Run and Open Mode with cy.intercept

### ISSUE THREAD

**Issue by MuckT** [cypress-io/cypress#16198]
### Current behavior
`cy.intercept` doesn't catch response in cli, but works fine in open mode.

#### Open Mode
![image](https://user-images.githubusercontent.com/26950305/116032806-2d54fa80-a615-11eb-88ce-5c6999865780.png)

#### Run Mode
![Auth-run](https://user-images.githubusercontent.com/26950305/116033078-a0f70780-a615-11eb-915c-b1cdf4443aa4.png)

### Desired behavior
`cy.intercept` should behave the same in run mode or open mode

### Test code to reproduce

  ```Bash
  # Cypress in Open Mode
  npm run test:e2e:open
  
  # Cypress as Run Mode
  npm run test:2e:run
  ```

### Versions
7.1.0 in Chrome

**Comment by jennifer-shehane** [comment]
@MuckT I don't see Cypress installed on this repo or any tests. Please provide a full repo with tests and instructions on how to run Cypress to see the failure. https://github.com/Mmarcos01/best-books-front-end

For the tiny-test example, `cy.wait()` is not designed to be used with `cy.request()`. This example will never work in `cypress run` or `cypress open`. Intercept will intercept requests initiated from the browser upon visiting a website, not using `cy.request()`. 

Can you provide a full example of `cy.wait()` intercept working in `cypress open` and not working during `cypress run`?

**Comment by MuckT** [comment]
@jennifer-shehane updated the link in the first repo to point to the right branch - cypress-testing. `cy.wait` is working with request on that branch, which sounds like unexpected behavior based on your comment.

**Comment by jennifer-shehane** [comment]
Getting an error trying to run the project. 

<img width="1132" alt="Screen Shot 2021-04-27 at 2 34 15 PM" src="https://user-images.githubusercontent.com/1271364/116301474-af543900-a765-11eb-803e-fdc572096a58.png">
