### ISSUE TITLE
Service Workers can break Cypress

### ISSUE THREAD

**Issue by csvan** [cypress-io/cypress#16192]
### Current behavior
Navigating to a page which uses a service worker can in some cases break Cypress completely, causing the Cypress panel to disappear and the page to stop responding to Cypress commands.

I have isolated this to the presence of the service worker - disabling it causes the page to behave normally under Cypress.

### Desired behavior

Cypress should be able to reliably test all pages using service workers.

### Test code to reproduce

To reproduce, I have set up an example URL which reliably reproduces this behavior when visited by Cypress. All that is needed to reproduce is a simple Cypress test which runs the following:

```js
cy.visit('https://qa.elegantconnect.com');
```

### Versions

Cypress 6.9.1, Nodejs 16.0.0, Chrome 90, OSX Big Sur.

### Other

The service worker in the provided example is created using Google Workbox (https://developers.google.com/web/tools/workbox). Below are the parts of it which most likely cause the behavior by defining a default URL, but I do not understand fully how this affects Cypress:

```js
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';

// eslint-disable-next-line no-underscore-dangle
precacheAndRoute(self.__WB_MANIFEST, {
  ignoreURLParametersMatching: [/.*/],
  directoryIndex: 'appshell/index.html',
});

const handler = createHandlerBoundToURL('/appshell/index.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);

```

**Comment by jennifer-shehane** [comment]
Can you include a full failing example? The example given with just the `cy.visit()` does load the page and looks fine within Cypress as far as I am aware. Thanks. 

<img width="1388" alt="Screen Shot 2021-04-26 at 12 08 28 PM" src="https://user-images.githubusercontent.com/1271364/116123393-932e9a00-a688-11eb-8172-4af6978631fd.png">

**Comment by csvan** [comment]
@jennifer-shehane I see, that's very strange. I can reliably reproduce it, but it might be a consequence of network infra on our side. I will close this until someone else can reproduce.

**Comment by fhp** [comment]
I can also reproduce this, and I have the same issue while testing my website (https://www.gynzykids.com).

It does not break immediately, only after the service worker has finished all the preloading. So rerunning the test after a minute or so would break the test.

As a workaround, I found that setting the Bypass for network option in the service worker webdev tab fixes the issue.
![image](https://user-images.githubusercontent.com/374671/123770331-83bb0f80-d8ca-11eb-9f85-4a9387b224e0.png)

**Comment by csvan** [comment]
We managed to get Cypress to work with Service Workers using Workbox. Key is simply to tell the SW not to cache (or precache) any Cypress resources:

```
const navigationRoute = new NavigationRoute(handler, {
  denylist: [
    new RegExp('/__'),
    new RegExp('cypress'),
  ],
});
```

Then add a rule which forces all Cypress requests to be network-only:

```
  registerRoute(
    (request) => request.url.includes('cypress'),
    new NetworkOnly(),
  );
```

**Comment by csvan** [comment]
@jennifer-shehane it hit me now that the reason you did not see it is probably because the Service Worker did not have time to install, I noticed it took quite a while to prefetch all resources.

However, as indicated above we have made it work now, but it feels hackish and is WorkBox specific.

**Comment by OtacilioN** [comment]
I tried the solutions presented here and got no progress.

Workbox seems to crash cypress. The project that I'm reproducing the error is https://github.com/Fundacao-1Bi/e2e-Aprendizap-web

I will try to find a solution and report it here.

**Comment by OtacilioN** [comment]
For me, the workaround that worked was:

```js
beforeEach(() => {
    cy.visit("https://appdev.aprendizap.com.br", {
      onBeforeLoad(win) {
        delete win.navigator.__proto__.ServiceWorker;
        delete win.navigator.serviceWorker;
      },
    });
    if (window.navigator && navigator.serviceWorker) {
      navigator.serviceWorker.getRegistrations().then((registrations) => {
        registrations.forEach((registration) => {
          registration.unregister();
        });
      });
    }
  });
```

I also added the registration.unregister to afterEach, and had to unregister all service works manually for the first time in application tab. 

the full project can be found at: https://github.com/Fundacao-1Bi/e2e-Aprendizap-web

**Comment by pauloh-sm** [comment]
> For me, the workaround that worked was:
> 
> ```
> beforeEach(() => {
>     cy.visit("https://appdev.aprendizap.com.br", {
>       onBeforeLoad(win) {
>         delete win.navigator.__proto__.ServiceWorker;
>         delete win.navigator.serviceWorker;
>       },
>     });
>     if (window.navigator && navigator.serviceWorker) {
>       navigator.serviceWorker.getRegistrations().then((registrations) => {
>         registrations.forEach((registration) => {
>           registration.unregister();
>         });
>       });
>     }
>   });
> ```
> 
> I also added the registration.unregister to afterEach, and had to unregister all service works manually for the first time in application tab.
> 
> the full project can be found at: https://github.com/Fundacao-1Bi/e2e-Aprendizap-web

Work for me. Thanks!!

**Comment by suterma** [comment]
I also have success using the unregistration, like described above. I have just put it in a global before each, and it's working great!

**Comment by distante** [comment]
@jennifer-shehane the given workaround is not working for already registered service workers. Which at least for us is breaking CI tests.
