### ISSUE TITLE
Not able to access new open window.

### ISSUE THREAD

**Issue by paritoshnice** [cypress-io/cypress#16193]
Hi,

Our application open after clicking one icon on the main window. But currently no way in Cypress to access the new window.
Is this issue going to be resolved in future? Is there any workaround to access the newly open window. I tried few but not working.

While we click on the icon on the main page new window is opened with a specific URL and after few seconds the URL is added with some more address for particular page location.

Example - When click the icon on main window the URL on new window is https://abcd.com/ then after few seconds it changes  to https://abcd.com/specificpage/landing

Please provide a solution.

Thanks

**Comment by csvan** [comment]
Cypress, by design, does not have multitab support: https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs

So no, this will most likely never be solved.

**Comment by jennifer-shehane** [comment]
@paritoshnice See the answer here: https://stackoverflow.com/questions/47749956/access-a-new-window-cypress-io
