### ISSUE TITLE
Ensure code coverage docs are up to date for CT

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#16199]
### Current behavior

No docs on how to configure code coverage with the component testing runner. All existing docs refer to the `file:preprocessor` architecture.

I hacked something together as detail in this issue: https://github.com/cypress-io/cypress/issues/16186. We should verify existing docs/READMEs are up to date, or make the required changes if they are not.

### Desired behavior

1. Better docs.
2. Make code coverage "just work" for the plugins/frameworks we support.

### Test code to reproduce

Following the [docs](https://github.com/cypress-io/code-coverage) does not work 100% as you might expect out of the box.

### Versions

7.x with CT runner.

**Comment by lmiller1990** [comment]
I will do this.

**Comment by lmiller1990** [comment]
Notes:

- [] Googling "cypress code coverage" takes you [here](https://docs.cypress.io/guides/tooling/code-coverage#Code-coverage-as-a-guide). That's fine - it's for e2e coverage, but it uses React - this might be confusing.
- [] This page is not just "how to set it up" but a deep dive into code coverage. We might want a more simple "here's how to make it work" type article, for people that just like to see coverage but don't care too much how it works. Most CT users from Jest are used to doing `--coverage` and getting a report.
- [] [Cypress/Code Coverage](https://github.com/cypress-io/code-coverage) talks about unit testing in [this section](https://github.com/cypress-io/code-coverage#instrument-unit-tests). Let's update this example to use the new architecture and CT runner. We should provide a working example.
- [] We have a [CRA code coverage library](https://github.com/cypress-io/instrument-cra). Let's update this to use CT and make sure it works as you would expect with all the projects (CRA, Next.js, Vue CLI...)
- [] [This demo](https://github.com/bahmutov/testing-react) use CRA and the e2e runner. Let's make a new version with the CT runner and use it in the docs.
- [] [This demo](https://github.com/bahmutov/next-and-cypress-example) use Next.js and the e2e runner. Let's make a new version with the CT runner and use it in the docs.
- [] [This demo](https://github.com/bahmutov/next-and-cypress-example) use Vue 2 and the e2e runner. Let's make a new version with the CT runner and use it in the docs.
- [] [This demo](https://github.com/bahmutov/code-coverage-webpack-dev-server) use Webpack dev server and `file:preprocessor` and the e2e runner. Let's make a new version with the CT runner and use it in the docs.

**Comment by yann-combarnous** [comment]
@lmiller1990, I just upgraded from Cypress 6.9.1 to 7.2.0, and @cypress/react 4.X to latest 5.X, and I am no longer getting code coverage for E2E tests.

We use CRA 4 with `react-scripts -r @cypress/instrument-cra` and added `@cypress/code-coverage` to support and plugin files, according to the doc, but nothing shows in Cypress UI / console or in coverage folders.

Any idea where to look at.

**Comment by yann-combarnous** [comment]
Sorry, found the issue, deleted by mistake `  return config;` from plugin file....

**Comment by lmiller1990** [comment]
Is it working for you now @yann-combarnous ?

**Comment by yann-combarnous** [comment]
Yes it is, ty.

**Comment by pashidlos** [comment]
@lmiller1990 do you have any working example for CT?
after update to version 7 I'm getting 
```
Cannot find coverage file /.nyc_output/out.json
Skipping coverage report
```
I have `@cypress/code-coverage/task` and `@cypress/code-coverage/support` added 
but I'm not getting how to instrument my code and then use it in CT
is there a way as before to add `babel-plugin-istanbul` inside `plugins/react-scripts` or how to force cypress to use manually instrumented src?

**Comment by pashidlos** [comment]
works with those lines added from your repo https://github.com/lmiller1990/cypress-react-template/blob/master/cypress/plugins/index.js#L11-L13

```
  const rules = webpackConfig.module.rules.find(rule => !!rule.oneOf).oneOf;
  const babelRule = rules.find(rule => /babel-loader/.test(rule.loader))
  babelRule.options.plugins.push(require.resolve('babel-plugin-istanbul'))
```
