### ISSUE TITLE
Cypress execution hangs in between when running through bitbucket.

### ISSUE THREAD

**Issue by Ppkd2021** [cypress-io/cypress#16202]
### Current behavior
We are executing UI test cases using the parallel flag in bitbucket, What we are observing is that builds get stuck during the execution the cypress does not send any failure which gets recorded in bitbucket. It kind of in execution state but it remains in execution state until build timeout happens that we have set to1hr.
### Desired behavior
Execution of test cases should not get stuck.
![image](https://user-images.githubusercontent.com/59794856/116082078-9e99b980-a6b8-11eb-8598-b64a193835f2.png)

### Versions
Cypress 6.8.0

**Comment by Ppkd2021** [comment]
@bahmutov Please can you suggest something how can we debug it further because it happens on a regular basis. 
Also, what we have observed is that the failure rate of cypress tests when running on a cli env(Bitbucket) is way more when compared to running a test locally. 
Which areas we should look into to resolve this problem as due to this it eats lots of our build time?

**Comment by jennifer-shehane** [comment]
@Ppkd2021 I would try capturing [debug logs](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) from Cypress. 

You might want to specifically log the memory and CPU usage of Cypress by following these instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage This will help determine if Cypress is running out of resources and whether the machine requires more.

Also, I would try isolating the differences between local runs and bitbucket runs. Running same browser, same browser version, headless/headed, same machine resources (CPU/memory), same OS. All of these differences could contribute to a run in CI failing and not failing locally for some reason.
