### ISSUE TITLE
DOM snapshots do not work with apps using Angular Elements (Web Components)

### ISSUE THREAD

**Issue by jdpearce** [cypress-io/cypress#16201]
### Current behavior

When looking at DOM snapshots with apps using Angular Elements they appear blank. It seems as though the addition of the elements to the DOM is forgotten/ignored.

e.g. Using the Angular Elements test app with a simple Cypress test that looks for the addition of the component, while the tests pass, the snapshots look like this:

Normal component added:
<img width="1814" alt="Screenshot 2021-04-26 at 11 55 38" src="https://user-images.githubusercontent.com/439121/116072482-0d5e1f00-a687-11eb-942e-287e47ca6ba8.png">

Angular Elements Web Component added:
<img width="1814" alt="Screenshot 2021-04-26 at 11 55 14" src="https://user-images.githubusercontent.com/439121/116072515-1949e100-a687-11eb-9364-c8c043885d61.png">

### Desired behavior

Both screenshots should be identical.

### Test code to reproduce

Repro repo here -> https://github.com/jdpearce/elements-and-cypress

To run the test runner use `npx nx e2e eletest-e2e --watch`

### Versions

Cypress 7.1.0
(see repro repo for full details)

**Comment by astilla** [comment]
We have the same issue.
