### ISSUE TITLE
Setting CYPRESS_ENV to an unexpected value leads to errors

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1621]
Per this issue: https://github.com/cypress-io/cypress/issues/1614

A user set `process.env.CYPRESS_ENV` to an unexpected value and caused Cypress to error / crash  when talking to the API.

We should check that its set to a valid value and provide a good error message when its set incorrectly.

**Comment by bahmutov** [comment]
I can catch in in the config in the server, but then it is too late, and it would be nice to catch in the CLI

<img width="1280" alt="screen shot 2018-04-20 at 9 36 20 am" src="https://user-images.githubusercontent.com/2212006/39053931-4d80468a-447e-11e8-9d40-563c4baa6027.png">

Just need to make sure we catch it in all scenarios
- running "normally" via NPM package
- running via Cypress NPM module
