### ISSUE TITLE
Desktop GUI redesign and integration

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16226]
For alignment across products and to improve the user experience, we are working on rebuilding the desktop GUI and expanding its capabilities.

- [ ] Welcome screen
  - [ ] MVP - No fancy inference on the CT side
  - [ ] Advanced onboarding flow
- [ ] Settings
  - [ ] UI driven by `cypress.json` schema
  - [ ] Override indications
- [ ] Dashboard integration
  - [ ] Login/logout
  - [ ] iframe

**Comment by rockindahizzy** [comment]
Hey @agg23, is there anything actionable here post Cypress v10?

**Comment by agg23** [comment]
lol I don't work at Cypress anymore, so I don't think I am the person to answer that question. I imagine you can safely close this.
