### ISSUE TITLE
Cypress fails and shows a blank page after uncaught: exception is thrown from the app even with the use of the listener uncaught: exception 

### ISSUE THREAD

**Issue by hdebas** [cypress-io/cypress#16222]
I'm testing https://store.google.com/ page. I visit this site, then get redirected to https://store.google.com/regionpicker, I choose "United States" and click continue, then I get a blank page in cypress. I can see on the console there is a type error: 
`Uncaught TypeError: Cannot read property 'name' of null`

Although I'm using 
```js    
Cypress.on('uncaught:exception', () => {
        return false
    })
```
but cypress loads a blank page and the test fails to continue. 

Here is a full code to reproduce the issue: 

```js
describe('Purchase a device from Google Store', () => {

const LOCATORS = {
    devicesMenu: '[id="desktop-products"]',
    headerContainer: '.header-container',
    regionTitle: '.region-title',
    dialog: '[role="dialog"]',
    button: '[role="button"]',
}

Cypress.on('uncaught:exception', () => {
    return false
})

before(() => {
    cy.visit('/')
})

it('Purchase device', () => {
    let region = 'United States'
    let urlToVerify = 'us/?hl=en-US&regionRedirect=true'

    cy.contains(LOCATORS.regionTitle, region)
    .click().then(() => {
        cy.get(LOCATORS.dialog).within(() => {
        cy.contains('Continue')
            .click({ force: true }).then(() => {
                cy.url()
                .should('include', urlToVerify)
            })
    })
    })
})
```

Also, I have the Cypress.on(..) in support/index.js, yet the exception is not caught. 

![image](https://user-images.githubusercontent.com/71205846/116208969-1b28a880-a74a-11eb-93ef-edec642f7886.png)

**Comment by jennifer-shehane** [comment]
This error is being thrown from within Cypress, so it's not an error being thrown from your application and won't be cause with the `uncaught:exception` handler.

Can you provide the full code to run to get to this page? I tried to replace your `cy.visit('https://store.google.com/')` but cannot reproduce the error completely.

**Comment by Justinohallo** [comment]
When I try to hit cy.visit('https://store.google.com/'), I am also brought to a blank page.

**Comment by itshaya** [comment]
@jennifer-shehane actually I think the blank page issue is not related to the exception in the console. as @Justinohallo said, cy.visit('https://store.google.com/') results in a blank page. maybe something from this app is preventing cypress automation?
