### ISSUE TITLE
Create a version of the Test Runner for Cross Domains

### ISSUE THREAD

**Issue by CypressJosh** [cypress-io/cypress#16231]
### What would you like?
Create the version of the runner that would be included in the sibling iframe
- Need another Test Runner bundle for the “other” domains AUT

Implementation of this will not include the reporter or any UI
- Doesn’t need one, because it’s nested

### Why is this needed?
This is the version of the driver that will run the tests cross domain. Associated with #944

**Comment by Amrita19900406** [comment]
Is this issue resolved?
