### ISSUE TITLE
cy.visit() fails indicating multiple origins per test - despite same origin and chromeWebSecurity override

### ISSUE THREAD

**Issue by duffar** [cypress-io/cypress#16235]
### Current behavior
I have a simple test that logs into our atlassian jira cloud server and upon successful login attempts to navigate to another page on the same server. The login process is successful but the second cy.visit() call fails with a CORS like error.

Here's the extent of the test:
```js
describe('Authentication', () => { 
    it('logs in and out', () => {
      cy.visit('/login.jsp');
      cy.get('#username').type(Cypress.env('UILOGIN_USER'));
      cy.get('#login-submit').click();
      cy.get('#password').type(Cypress.env('UILOGIN_TOKEN'));
      cy.get('#login-submit').click();
      cy.get('#createGlobalItemIconButton');  // visible on successful login

      cy.visit('/logout.jsp');
      cy.get('#logout-submit').click();
      cy.get('#form-login');  // should return to login page
    });  
  })
```
The test fails on the 2nd cy.visit (to /logout.jsp) with the following message:

```
cy.visit() failed because you are attempting to visit a URL that is of a different origin.

The new URL is considered a different origin because the following parts of the URL are different:

  > superdomain

You may only cy.visit() same-origin URLs within a single test.

The previous URL you visited was:

  > 'https://id.atlassian.com'

You're attempting to visit this URL:

  > 'https://jmwe-test-react.atlassian.net'

You may need to restructure some of your test code to avoid this problem.
```

Some things to note:

- I've configured the baseUrl to point to my site: 'https://jmwe-test-react.atlassian.net'
- The two cy.visit() calls I make are to paths under the same baseUrl
- The initial visit(/login.jsp) triggers a redirect to 'https://id.atlassian.com' where the script then finds the screen elements and submits the login request. Upon successful login, the browser is redirected back to a page on my baseUrl and the subsequent get successfully finds an element on that page.
- The ensuing cy.visit(/logout.jsp) fails as indicated above.

I've checked the cypress settings console and the baseUrl and environment variables are what I'd expect - and I can see from the snapshots that everything worked up to the second visit call.

I've searched the docs and issues on this error and realize it results from visiting different super-domains from a single test case. Although I didn't do that directly in my cy.visit() calls I suspect the SSO redirects have essentially done that under the covers.

I investigated the approach you recommend for Single Sign On and some of the examples that do it however I found the login path very complex on the Atlassian Jira/Confluence product set I am working on. That may indeed be the best approach for us but until I get it figured out I'd like to proceed with a scripted login.

The docs mention one workaround to the CORS issue is to disable it for Chrome and electron by setting the chromeWebSecurity config setting to false. Unfortunately this config setting seemed to have no effect when I disabled it.

### Desired behavior
Subsequent visits to subpaths under the same baseURL within the same test case should succeed.

### Test code to reproduce

see above

### Versions

I'm running the latest released version of cypress using npx

```
$ npx cypress --version
Cypress package version: 7.2.0
Cypress binary version: 7.2.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1
```

**Comment by jennifer-shehane** [comment]
It doesn't matter if you intertionally visit 2 superdomains or the app redirects and 2 superdomains are visiting in the same test. Neither will work in Cypress today. We've begun work on supporting this and understand it's one of our most requested features, so follow this issue: https://github.com/cypress-io/cypress/issues/944

For now you'll have to do the more complex login workarounds unfortunately.

**Comment by duffar** [comment]
Thanks for the quick reply @jennifer-shehane . Is there a back level version of cypress that this does work in? In the meantime I'll keep digging into the SSO request method.

**Comment by jennifer-shehane** [comment]
@duffar No, there's now. Most people end up programmatically testing their login APIS.
