### ISSUE TITLE
Cypress can not find selectors in Chrome correctly.

### ISSUE THREAD

**Issue by sigelok** [cypress-io/cypress#16248]
I have a problem in Chrome (Cypress) while I am trying to get the selector, suggested by the Cypress, the selector is shifted (down from the pointer) and after clicking on an element I expect to see the suggested selector in the selector field, but it didn't. Not reproduced in Firefox. And after the test was written using Firefox, it fails in Chrome - Cypress can not find selectors there.  Repro for Edge, Electron. Any suggestions?

"cypress": "^7.0.0"
Chrome: 90
Firefox: 87
Edge: 90
Electron: 89
UI of the tested page: Angular 1.5

**Comment by jennifer-shehane** [comment]
@sigelok This is a bug in Cypress. Please provide a full example of HTML required to reproduce the problem so that we can address it. Without this we'll have to close the issue since we can't see the HTML.
