### ISSUE TITLE
Flakey AJAX requests when using Cypress.on('fail') and the test runner

### ISSUE THREAD

**Issue by nickclicksco** [cypress-io/cypress#1625]
### Current behavior:

When using the `Cypress.on('fail', function(err, runnable) {});` method I am posting an AJAX request to our application like so:

```js
    Cypress.on('fail', function(err, runnable) {
      // we now have access to the err instance
      // and runnable this failed on
        setTimeout(function() {
          axios.post('https://site.com', {
            error_message: runnable.err.message,
          })
          .then(function (res) {
            console.log(res);
          })
          .catch(function (error) {
            console.log(error);
          });
        }, 0);
        throw err;
    });
```

Not sure why but runnable won't work unless I wrap it in a function or timeout, but that is another issue so don't get confused by it.

When using `npx cypress open` and then selecting my spec the AJAX request sends every time without any issues.

However if I run my tests using `npx cypress run` on my CircleCI job the AJAX request is very flakey. Sometimes it sends and sometimes it doesn't. I'm guessing this is because the test runner is killing the spec before the AJAX request can be sent.

### Desired behavior:

I'd like to know how we can stop the spec from being killed until the request has been successfully sent. I've already tried using `cy.wait` but this doesn't work.

Is there a way that I can manually fail a test in the promise on my AJAX request?

### Steps to reproduce:

Run an AJAX request inside of `Cypress.on('fail')` and then use the `npx cypress run` command. Alternatively any logic that can take a bit of time within here such as a `setTimeout` can't be ran.

**Comment by brian-mann** [comment]
To answer your question - it is because that request is async and if Cypress kills the process then that's why it's not being captured.

Alternatively we could enable you to write new Cypress commands so you could use `cy.request` or other commands in the `fail` handler.

We'd need to add a new section to the command log to capture the commands running under the `fail` event...

There's actually a surprising amount of complexity around this. It's because Cypress needs to associate everything correctly and handle all situations where things don't go as planned. The `fail` handler kind of bucks the way things are "supposed" to work. There's been other discussions on here about recovering from "errored" commands.

**Comment by nickclicksco** [comment]
Thanks for answering this @brian-mann, can you think of a work around for this for the time being?
 
Alternatively is there a way I can stop Cypress killing my tests when one fails and then just stick a `cy.wait()` on the end of the spec? This would allow time for any AJAX requests to complete, I know it would be pretty messy but might work.

**Comment by brian-mann** [comment]
You could likely do something like this...

```js
after(() => {
  const runnable = cy.state('runnable')

  if (runnable.currentTest && runnable.currentTest.state === 'failed') {
    cy.wait(5000)
  }
})
```

Did not try this... throw some `debugger` in there and muck around with `runnable`. I believe it hold a reference to the current test and you can check to see if its failed, and if so add a `cy.wait` to it...

**Comment by brian-mann** [comment]
If that works just drop the `after` hook into a support file so its included automatically on every suite

**Comment by nickclicksco** [comment]
By the way... are we free to use the API that is used by the Cypress dashboard? CORS is enabled so I'm guessing so. Are there any limitations on the amount of times I can ping the endpoint?

I find an API that returns test failures far more valuable than the actual dashboard in this case.

**Comment by jennifer-shehane** [comment]
I'd recommend using the [Cypress Module API](https://on.cypress.io/module-api) to achieve this today. You can access all failures after the test run and handle them however you want.
