### ISSUE TITLE
Cypress server does not respect `--quiet` config parameter

### ISSUE THREAD

**Issue by arusanov** [cypress-io/cypress#16268]
### Current behavior

When started with `--quiet` flag, cypress still prints warning and info to stdout from cypress server. 
Examples:
```
Warning from Cypress Dashboard: Organization with paid plan in grace period has exceeded monthly test results limit.

Details:
{
  "code": "PAID_PLAN_IN_GRACE_PERIOD_EXCEEDS_MONTHLY_TESTS",
  "name": "PaidPlanInGracePeriodExceedsMonthlyTests"
}
```
or
```

  (Uploading Results)

  - Nothing to Upload

```
https://github.com/cypress-io/cypress/blob/14f72a36246699f53ec62e72c5fe1315921f3106/packages/server/lib/modes/record.js#L673

### Desired behavior

When started with `--quiet` flag, Cypress output will not be printed to stdout. Only output from the configured Mocha reporter will print. (as in docs)

### Test code to reproduce

run any test with `--quiet` and `--record` with cypress dashboard enabled.

### Versions

any version. Tested on latest (7.2.0)

**Comment by jennifer-shehane** [comment]
Yes, I can confirm the `--quiet` flag does not quiet 'uploading results' and likely the other warnings you describe.
