### ISSUE TITLE
TS: `cy.window().then(win)` gives `TS2339: Property 'console' does not exist on type 'Window'.`

### ISSUE THREAD

**Issue by szymontodavizlib** [cypress-io/cypress#16267]
Hello, I report a bug that I do not know how to handle. I hope you can direct me to a solution.

using `cy.window().then(win)` gives `TS2339: Property 'console' does not exist on type 'Window'.`

```js
beforeEach(() => {
    cy.window().then((win) => {
        cy.spy(win.console, 'error'); // TS2339: Property 'console' does not exist on type 'Window'.
    });
});
```
It's using
`window(options?: Partial<Loggable & Timeoutable>): Chainable<Window>`

but it's never exported
```js
// Augments the DOM `Window` object when lib.dom.d.ts is loaded.
// tslint:disable-next-line no-empty-interface
interface Window extends Mocha.MochaGlobals { }
```

### Current behavior
Window type is detected as DOM member, not Cypress member.

### Desired behavior
Window type is matching Cypress.Window (currently not exported)

### Versions
7

**Comment by jennifer-shehane** [comment]
I would suggest disabling tslint for this line to ignore the error. We're open to a pull request to fix the Window type.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I failed to replicate this behavior with Cypress 7.4.0 and TypeScript 4.3.2. Can you provide me a reproducible example?

**Comment by szymontodavizlib** [comment]
@sainthkh you are right, I've upgraded to Cypress 7.4.0 and it works. My bad is I did not pay notice what version it was previously, it might be something 3.4 or 7.2 as those versions I was using in the past...

**Comment by sainthkh** [comment]
Thanks, then I believe it's safe to close this issue.
