### ISSUE TITLE
The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### ISSUE THREAD

**Issue by jazpearson** [cypress-io/cypress#16275]
### Current behavior

Just tried to create a test through cypress studio, but getting an error as shown in the screenshot.
![image](https://user-images.githubusercontent.com/7648154/116603754-30a5fa00-a925-11eb-94d8-c6b052d5446f.png)

Here's my project layout:
![image](https://user-images.githubusercontent.com/7648154/116603950-71057800-a925-11eb-8635-d91281fd3cc9.png)

and cypress.json
```
{
  "chromeWebSecurity": false,
  "defaultCommandTimeout": 60000,
  "pageLoadTimeout": 180000,
  "viewportHeight": 1050,
  "viewportWidth": 1680,
  "screenshotsFolder": "cypress/results/screenshots",
  "videosFolder": "cypress/results/videos",
  "video": true,
  "videoUploadOnPasses": false,
  "videoCompression": 32,
  "retries": 3,
  "experimentalStudio": true,
  "integrationFolder": "cypress/integration"
}

```

### Desired behavior

To be able to record the commands through cypress studio.

### Test code to reproduce

Going to be difficult getting some test code to reproduce. But i will try to create a sample project. 
I tried with the Real World Example app and was able to record the commands.... so i'm wondering if someone can spot something obvious here?

### Versions

7.2.0 - the latest.

**Comment by jennifer-shehane** [comment]
I think this may be related to https://github.com/cypress-io/cypress/issues/16223 Were you trying to create a test that was testing file upload?

**Comment by jazpearson** [comment]
No, just trying to create my first test with cypress studio - just tried clicking a link to navigate to another area of the app and trying to save. Will have a look at the related issue.

**Comment by jennifer-shehane** [comment]
@jazpearson Were you creating a New Test or adding commands to an existing test in the Studio? I tried to recreate your file as shown and I don't run into an issue creating or adding commands. 

```ts
import { Foo } from '../fixtures/amount.js';

describe('Testing', () => {
  const foo = Foo

  before(() => {
    cy.login()
    foo
  });

  it('testing', () => {

  });
});
```

**Comment by jazpearson** [comment]
It was trying to add a command that i got the error.

I've just tried creating a new test and that seems to have worked ok. Will dig around a bit more.....

Thanks for the very quick replies!!

**Comment by jazpearson** [comment]
Ok. It appears to be an issue with the `ts` file extension. If we use `js` things seem to be working as expected. My test files are all ts, but when i created a new test through the studio, it creted a js file. Adding and creating to this test worked and saved as expected.

When i renamed that test file so it had a ts extension, i got the same issue.

**Comment by orangejacky** [comment]
I have the same problem
