### ISSUE TITLE
Waiting for certain condition to be true (within the timeout): cy.wait(condition)

### ISSUE THREAD

**Issue by MacGyver27** [cypress-io/cypress#16270]
### What would you like?
Would it be possible to `cy.wait()` for certain condition to be true? Usage: `cy.wait(ready === true)`? The command would timeout as usual.

### Why is this needed?
This way it will be possible to keep things synchronous and avoiding those steps to be nested into `.then()`..

Overall look of the code can be more "flat".

I know there are other ways to achieve it but am curious about this "possible" feature.

Thank you.

**Comment by jennifer-shehane** [comment]
This is not currently possible using the `cy.wait()` syntax and is possible using Cypress in order structures. I would not expect us to build this feature in anytime soon over other features if that's your question. 

Probably this thread is most relevant to actually addressing what you want, where we'd have to consider a way to implement this in the future. https://github.com/cypress-io/cypress/issues/1417

**Comment by bahmutov** [comment]
@MacGyver27 you can probably use https://github.com/bahmutov/cypress-recurse to achieve this today

**Comment by MacGyver27** [comment]
@jennifer-shehane it would work as long as it would consider all the nested blocks to be finished. Thanks

@bahmutov will test it, thanks for the suggestion.

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
