### ISSUE TITLE
Cypress component testing could not detect tests when spec file contains spaces in path 

### ISSUE THREAD

**Issue by realmerx** [cypress-io/cypress#16278]
### Current behavior
Cypress component testing (cypress open-ct) could not detects tests when spec file contains spaces in path. When trying to load a spec in browser following message is displayed:

 No tests found.
Cypress could not detect tests in this file.

Example:
OS: Windows 10

path is: 

c:\projects\my project\cypress\component\test.spec.js

if I change the path to:

c:\projects\my_project\cypress\component\test.spec.js

then tests are successfully detected.

### Desired behavior
Tests would be detected

### Test code to reproduce
Just include space in path to spec file

### Versions

Cypress 7.2.0
OS: Windows 10

BTW: Cypress rules and keep up the good work :)

**Comment by realmerx** [comment]
If anyone needs quick workaround you can create symbolic link without spaces in path to the project directory.

**Comment by lmiller1990** [comment]
Thanks for reporting this. We should encode the URLs to support white-space.

**Comment by lmiller1990** [comment]
I think the problem is in the `packages/runner-ct` part of the code base. I am able to curl a spec with white space without any problems: `curl http://localhost:50117/cypress/component/Spec%20With%20Whitespace.spec.tsx`, where the spec is "Spec With Whitespace".

**Comment by lmiller1990** [comment]
Ok, I fixed it here. https://github.com/cypress-io/cypress/pull/16416
