### ISSUE TITLE
Allow passing undefined or null for no options per test

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#16281]
Cypress v7.2.0
Cypress allows passing per-test config options object like this

```js
it('works', { baseUrl: 'http://localhost:8000' }, () => {})
```

Turns out, if you pass `undefined` or `null` object as the second argument, the test is marked as pending, even if it has commands

```js
describe('page', () => {
  it('works', undefined, () => {
    cy.visit('https://example.cypress.io')
  })
})
```

<img width="487" alt="Screen Shot 2021-04-29 at 10 38 54 PM" src="https://user-images.githubusercontent.com/2212006/116642062-01e74e00-a93c-11eb-8b29-13c51718ef2f.png">

The only way to pass no options is to pass an empty object as the second argument

```js
describe('page', () => {
  it('works', {}, () => {
    cy.visit('https://example.cypress.io')
  })
})
```

<img width="544" alt="Screen Shot 2021-04-29 at 10 39 09 PM" src="https://user-images.githubusercontent.com/2212006/116642078-10ce0080-a93c-11eb-9dd4-0b5742bd135a.png">

## expected behavior

Allow passing undefined or null as the second argument to have no per-test options. This is also important when overwriting the `it` function, as I do in https://github.com/bahmutov/cypress-grep

## reproduction

https://github.com/cypress-io/cypress-test-tiny/tree/test-undefined-options

**Comment by jennifer-shehane** [comment]
Since this hasn’t had a lot of interest over the years, we’ll close this issue.
