### ISSUE TITLE
Cypress reports negative failures in mochawesome reports.

### ISSUE THREAD

**Issue by jaybeeuu** [cypress-io/cypress#16296]
### Current behavior

Cypress, using the [mochawesome](https://docs.cypress.io/guides/tooling/reporters#Installed-via-npm) reporter incorrectly reports negative failed tests when some tests are skipped with `describe.skip` or `xdescribe`.

The CLI output is correct as show below:

```sh
  ┌──────────────────────────┐
  │ Tests:        6               │
  │ Passing:      0               │
  │ Failing:      0               │
  │ Pending:      6               │
  │ Skipped:      0               │
  │ Screenshots:  0               │
  │ Video:        true            │
  │ Duration:     0 seconds       │
  │ Spec Ran:     skipped.spec.js │
  └──────────────────────────┘
```
However this disagrees with the report created by mochawesome.
The `stats` key of the `json` ouput file will contain the following values:

```json
{
  "stats": {
    "suites": 2,
    "tests": 2,
    "passes": 0,
    "pending": 6,
    "failures": -4,
    "testsRegistered": 6,
    "other": 4,
    "skipped": 4,
  }
}
```
Notice that `skipped` and `other` are `4` and `failures` is `-4`.

### Desired behavior

The reporter should produce the values it does when used in conjunction with the mocha:

```json
{
  "stats": {
    "suites": 2,
    "tests": 6,
    "passes": 0,
    "pending": 6,
    "failures": 0,
    "testsRegistered": 6,
    "other": 0,
    "skipped": 0
  }
}
```

### Test code to reproduce

https://github.com/jaybeeuu/cypress-mochawesome-reporter-repro

### Versions

Cypress: v7.2.0. I also looked back to cypress v  5.0.0 and it had the same behaviour.
Mochaswesome: v6.2.2

**Comment by droca** [comment]
I can still observe the issue while using the following versions:
 - Mochawesome: v7.0.1
 - Cypress: v8.6.0

**Comment by abhishek-lambda** [comment]
This issue is still occuring in the latest cypress version , please reopen this issue @cypress-app-bot @jennifer-shehane @jaybeeuu @JJ 

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/37b1b8a7-ebf4-4436-8878-77ea92c3a781" />
