### ISSUE TITLE
getCookies and getCookie are timing out in ci pipelines

### ISSUE THREAD

**Issue by SDAdham** [cypress-io/cypress#16297]
### Current behavior

Based on the docs https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Timeouts , getCookie should never timeout however I am experiencing this since the update to 7.1.0
![image](https://user-images.githubusercontent.com/11182824/116780599-0db04d00-aac1-11eb-8a66-a1e9385c86f5.png)
I tried both getCookie and getCookies, both result with the same error which is timing out.

this problem is happening in the build pipeline that uses the following image: cypress/browsers:node12.19.0-chrome86-ff82

### Desired behavior

As documentation mentioned, it shouldn't timeout.

### Test code to reproduce

In `index.ts`:

```js
before(() => {
  // one of the statements below:
  cy.getCookie('cookieName').then((cookie: Cypress.Cookie) => { ... });
  cy.getCookies().then((cookies: Cypress.Cookie[]) => { ... });
});
```
### Versions

Cypress: 7.1.0
Pipeline image: cypress/browsers:node12.19.0-chrome86-ff82

**Comment by jennifer-shehane** [comment]
@SDAdham Could you try updating to 7.2.0 to see if this helps with the issue? Thanks!

**Comment by SDAdham** [comment]
Hello @jennifer-shehane , I already did and it's the same problem, I did a workaround anyways which is using `document.cookie` directly rather than `cy.getCookie` and it works like a charm.

**Comment by jennifer-shehane** [comment]
Yah I'm not sure why this would occur. I haven't seen this before. If you can provide an application to test against to see this, that'd be helpful. Or try running the [kitchen-sink](https://github.com/cypress-io/cypress-example-kitchensink) tests to see if the getCookies() command passes there - that would narrow down whether it's specific to your app.
