### ISSUE TITLE
Adding a directory to the support directory causes cypress 500

### ISSUE THREAD

**Issue by paulfalgout** [cypress-io/cypress#163]
I wanted to break up my commands file and put them in a `/support/commands/` directory.  Worked great, but now I'm getting what looks to be an error when cypress attempts to load the actual directory
`500: http://localhost:2020/__cypress/tests?p=cypress/support/commands-247`

I verified this by adding an empty directory called `foo` with the same result:
`500: http://localhost:2020/__cypress/tests?p=cypress/support/foo-860 `

**Comment by brian-mann** [comment]
Yup it was not ignoring directories.

**Comment by brian-mann** [comment]
Fixed in [`0.16.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0163-06172016).
