### ISSUE TITLE
Cypress fails to detect DOM elements

### ISSUE THREAD

**Issue by Gennadiii** [cypress-io/cypress#1631]
- Operating System: Windows 10
- Cypress Version: 1.4.2
- Browser Version: Chrome 66

### Current behavior:
This is a flaky bug with reproducibility about 5%
CypressError: cy.click() failed because it requires a DOM element
It might be cased by slow server response which might take up to 2 seconds. I tried cy.wait, .should('be.visible'), increasing default timeouts,  setting timeout for the click, but nothing helps.
Passed test:
![2018-04-23 13_45_43-integration](https://user-images.githubusercontent.com/7658266/39122875-d84b1d76-46fe-11e8-87f2-bd315c88b375.png)
The same failed test:
![2018-04-23 13_45_35-integration](https://user-images.githubusercontent.com/7658266/39122886-dcff62fa-46fe-11e8-94ec-0acd419392e9.png)

The same sometimes happen to assertions:
Passed test:
![2018-04-23 13_45_07-integration](https://user-images.githubusercontent.com/7658266/39122922-f235f602-46fe-11e8-8d75-14cea7b4c121.png)
Failed test:
![2018-04-23 13_42_43-integration](https://user-images.githubusercontent.com/7658266/39122923-f7200766-46fe-11e8-940a-d2ef135d0114.png)

Notice second example with assertion - failed test didn't click between 2 asserts. Although it is the same piece of code.

**Comment by jennifer-shehane** [comment]
Hey @Gennadiii, could you provide the test code for these cases? I am particularly wondering if you are using aliases or `.as()` in your querying of the element.

**Comment by Gennadiii** [comment]
@jennifer-shehane Nope, just cy.get().should() - cy.get().click()

**Comment by jennifer-shehane** [comment]
@Gennadiii We will need to be able to reproduce this situation on our end in order to look into what is causing the DOM element to wrongfully be `undefined`. 

Can you provide an example of this that we can run on our end? Perhaps an example of the library you are using for the accordion (if applicable) or a repo with a smaller reproducible example?

**Comment by Gennadiii** [comment]
Unfortunately I can't provide an example. This issue reporduces with accordions, dropdowns and one link with svg inside.

**Comment by joelmeiller** [comment]
Hi I have the same problem. We are using React and Meteor. The random behaviour as described above appears in my test runs too.

I am still working on it, but maybe I can provide you a test example in the next days.

Furthermore, I have the problem, that if the _should_ assertion fails (because the element could not be found) the test runs forever.

**Comment by MarkNewcomb1** [comment]
Same problem here. Here's my code - note the two cy.pause commands, one active and one commented out.


`describe('testing for drill 2 hacker news', function(){
    it('1. Make sure the title has "Vue HN 2.0" in it 1. Make sure more than 1 news items show up on the page1. Go to the "New" area via the link1. Make sure you\'re on the correct page1. Make sure more than 1 items show up on the page1. Go to the next set of results with the "more" link1. Make sure you\'re on the correct page1. Make sure more than 1 news items show up on the page1. Go to the jobs page via the link1. Make sure you\'re on the correct page1. Make sure more than 1 news items show up on the page', function() {
        cy.visit('https://e2e-hackernews.herokuapp.com/')
        cy.get('title')
        .should('contain', 'Vue HN 2.0')
        cy.get('.news-item')
        .should('have.length.gt', 1)
        cy.get('a').contains('New')
        .click()
        cy.url()
        .should('contain', '/new')
        cy.get('body').find('.news-item')
        .should('have.length.gt', 1)
        //cy.wait(1000)
        //cy.pause()
        cy.get('a').contains('more >')
        cy.pause()
        .click()
        cy.url().should('include', '/new/2')
        cy.get('body').find('.news-item')
        .should('have.length.gt', 1)
        cy.get('a').contains('Jobs')
        .click()
        cy.url()
        .should('contain', '/job')
        cy.get('body').find('.news-item')
        .should('have.length.gt', 1)
    })
})`

 If you comment out the one that's active and un-comment the one that's currently commented, then step through the pauses, the tests will pass - but if you leave the code as I've pasted below, you'll get a 

> CypressError: cy.click() failed because it requires a DOM element.

> The subject received was:

  > undefined

> The previous command that ran was:

  > cy.pause()


Screenshot: 
<img width="696" alt="screen shot 2018-06-11 at 2 30 20 pm" src="https://user-images.githubusercontent.com/5383733/41255523-04a4f2f6-6d84-11e8-9a52-06bf31a88e00.png">

I'm doing this for an assignment that specifically does not want us to use cy.wait (which, if I give .wait 1000 or 2000 milliseconds, does pass).

**Comment by jennifer-shehane** [comment]
@MarkNewcomb1 This actually looks to be an issue with the use of `.pause()` and `.click()` chained together. So `.pause()` yields the [same subject that it was given](https://docs.cypress.io/api/commands/pause.html#Yields), and `.click()` expects a DOM element to be chained off of, so writing `cy.pause().click()` is not the correct use of either of the commands. 

Could you try writing:
```js
cy.get('a').contains('more >')
  .pause()
  .click()
```

The above has the element found from the `.contains('more >')` yielded to `.pause()`. The element is then passed through `.pause()` to `.click()` to be clicked on.

**Comment by MarkNewcomb1** [comment]
Ah, I see - that makes the pause work. Thank you.

**Comment by jennifer-shehane** [comment]
Hey @Gennadiii, just wanted to follow up. 
- Have you been able to reproduce this with out most recent Cypress version, `3.0.1`?
- Could you paste the test code? Even if not reproducible on my side, I'd like to just look at the structure of the test code you are running for the flaky test.

**Comment by Gennadiii** [comment]
Hi @jennifer-shehane,
There were no specific steps, the issue is flaky. Unfortunately I can't give you any code since I don't work for that project anymore.

**Comment by jennifer-shehane** [comment]
Hey @marcelo-rebello, your failed test does not look related to the issue detailed here of the subject logging as `undefined`. 

In terms of `.contains()` not finding the content, this can happen sometimes if there are new lines or space characters within the 'Clinical value'. 

Also, are you trying to look at the text that is the `value` of an input?

**Comment by marcelo-rebello** [comment]
Well, if I do something like `cy.contains('Clinical').should(...)` I will have an `undefined` result logged as Cypress fails to find the input field...
It happens with several input types using Vue.js/Quasar frameworks...

Look at the `value` field works, but it looks like a bug or limitation of Cypress that is not documented or made explicit anywhere. Cypress works on top of UI, but is not able to get a visible text element???

Maybe contains could have a configurable list of places to look for text/value... or just look in value fields also.
Maybe comment about this restriction on docs...

**Comment by jennifer-shehane** [comment]
@marcelo-rebello `.contains()` does not current look at input value fields. You can open a new issue for support for this.

**Comment by gtycherry** [comment]
Hi @jennifer-shehane 
I met below error when using contains.
![screen shot 2019-03-06 at 10 33 14 am](https://user-images.githubusercontent.com/8056464/53851970-4c3e4000-3ffb-11e9-8d8b-adfe361ac018.png)

could you please help to suggest what api i can use to assert there is one specific element visible on page? Thanks.

**Comment by bahmutov** [comment]
Split the long chain. After wait do a new “cy.contains ...”

**Comment by Tomas-Tr** [comment]
Hi the same issue here. If I add new row into table, fill data into first column and then blur or click out off the column, some part of the code is failing with error:
CypressError: cy.find() failed because it requires a DOM element.

The subject received was:

  > undefined

The previous command that ran was:

  > cy.get()


` cy.get('[data-cy=partner_groups_table]').then($table => {
        const rowCount = $table.find('tbody').find('tr').length;
        //add row and assert row count
        cy.get('[data-cy=add_partner_group_button]')
          .should('be.enabled')
          .click();

        cy.get('[data-cy=partner_groups_table]')
          .find('tbody')
          //.eq(0)
          .find('tr')
          .should('have.length', rowCount + 1);

        assertInvalidCategoriesPage();

        cy.log('Insert data to newly added row START');
        cy.get('[data-cy=partner_groups_table]')
          .find('tbody')
          //.eq(0)
          .find('tr')
          .last()
          .as('row');
        //test required validator
        cy.get('@row')
          .find('[data-cy=partner_group_name]')
          .click()
          .blur();
        cy.get('@row')
          .find('[data-cy=partner_group_name_form_field]')
          .find('mat-error')
          .should('be.visible');
        assertInvalidCategoriesPage();

        //insert correct data into row
        cy.get('@row')
          .find('[data-cy=partner_group_name]')
          .type('cat' + GuidUtils.newGuid().substring(0, 4));
        debugger;
        //after blur the @row alias not working anymore for some reason, therefore click to next input is used to blur from prev el
        cy.get('@row')
          .find('[data-cy=partner_group_working_hour_price]')
          .click();
        debugger;
        cy.log('@row');
        cy.get('@row')
          .find('[data-cy=partner_group_name_form_field]')
          .find('mat-error')
          .should('not.be.visible');

        cy.log('Insert data to newly added row END');
      });`
