### ISSUE TITLE
Cypress can't process Duplicated Headers from websitres: Error: Parse Error: Duplicate Content-Length

### ISSUE THREAD

**Issue by ferrarih** [cypress-io/cypress#16314]
Cypress script that is trying to access the following URL (https://sso.tce.sp.gov.br/cas-server/login ), but the website is returning a duplicated headers:

![QE8uz](https://user-images.githubusercontent.com/1271364/117030065-dad6a680-acc4-11eb-8c92-3d53594b75cb.png)

This websites loads perfectly when is manually accessed via Chrome, Edge or Firefox. But everytime it uses the browser operated by Cypress it nevers works.

**Cypress error:**
```
cy.visit() failed trying to load:

https://sso.tce.sp.gov.br/cas-server/login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

Error: Parse Error: Duplicate Content-Length

Common situations why this would fail:

you don't have internet access
you forgot to run / boot your web server
your web server isn't accessible
you have weird network configuration settings on your computer**
```

Expected result: Cypress can load the website as any browser does, without the error.

Script Code:

```js
describe("Test", () => { 
  it("Access AUDESP Website", function () {
    cy.visit("https://sso.tce.sp.gov.br/cas-server/login") 
  })
})
```

**Comment by jennifer-shehane** [comment]
Per the spec, duplicate content-length headers that contain the same value can be either rejected or send a single content-length header. So Cypress erroring here is not outside of the spec.

There are multiple security issues with sending duplicate content-length headers and you shouldn't be doing this if this is a website under your control. 

>If a message is received that has multiple Content-Length header
   fields with field-values consisting of the same decimal value, or a
   single Content-Length header field with a field value containing a
   list of identical decimal values (e.g., "Content-Length: 42, 42"),
   indicating that duplicate Content-Length header fields have been
   generated or combined by an upstream message processor, then the
   recipient MUST either reject the message as invalid or replace the
   duplicated field-values with a single valid Content-Length field
   containing that decimal value prior to determining the message body
   length or forwarding the message. https://tools.ietf.org/html/rfc7230#section-3.3.2

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
