### ISSUE TITLE
@cypress/webpack-dev-server is incompatible with webpack-dev-server ^4

### ISSUE THREAD

**Issue by mwren-mshanken** [cypress-io/cypress#16313]
### Current behavior

webpack-dev-server introduced breaking changes to their configuration object in their beta version. Cypress component tests fail when running with  "webpack-dev-server": "^4.0.0-beta.2",

I know that this is beta, but my team is using this to be able to serve our web app via `encore` for development. We need to have this installed at ^4 as a dev dependency

The following error is thrown:

```
 WARNING  The value passed to setManifestKeyPrefix "/dist" starts with "/". This is allowed, but since the key prefix does not normally start with a "/", you may have just changed the prefix accidentally.
Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'noInfo'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }
ValidationError: Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'noInfo'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }
    at validate (/Users/morgan/Documents/WineSpectator/git/ws/node_modules/webpack-dev-server/node_modules/schema-utils/dist/validate.js:104:11)
    at new Server (/Users/morgan/Documents/WineSpectator/git/ws/node_modules/webpack-dev-server/lib/Server.js:43:5)
    at Object.<anonymous> (/Users/morgan/Documents/WineSpectator/git/ws/node_modules/@cypress/webpack-dev-server/dist/startServer.js:57:16)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/morgan/Documents/WineSpectator/git/ws/node_modules/@cypress/webpack-dev-server/dist/startServer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Looks like this stems from line 55 in startserver.js

```js
const webpackDevServerConfig = Object.assign(Object.assign({}, userWebpackConfig.devServer), { hot: false, inline: false, publicPath: devServerPublicPathRoute, noInfo: false });
        // @ts-ignore types for webpack v5 are incorrect?
        return new webpack_dev_server_1.default(compiler, webpackDevServerConfig);
```

This is passing config options that are no longer supported/have moved

### Desired behavior

We'd love to be able to run cypress component tests alongside webpack-dev-server ^4 

I'm frustrated that the symfony team is requiring a beta version for their dev server to work with encore, and understand that it may be a stretch to support a beta version of webpack-dev-server, but this may be indicative of impending breaking changes at some point anyways.

### Test code to reproduce

`npm i -D webpack-dev-server@next`

`npx cypress run-ct`

### Versions

"@cypress/react": "^5.4.2"
"@cypress/webpack-dev-server": "^1.1.6"
"@symfony/webpack-encore": "^1.1.2"
"cypress": "7.2.0"
"webpack-dev-server": "^4.0.0-beta.2"

**Comment by lmiller1990** [comment]
At this point we only have support for WDS v3.

It looks like the API has some breaking changes. I'd be interested in how much work is actually involved to support WDS v4. We already have some conditional code for webpack 4/5, [see here](https://github.com/cypress-io/cypress/blob/3342ca3b7f6e0eb98b5d37f7e5b3efabffa788a5/npm/webpack-dev-server/src/plugin.ts#L86-L103). I wonder if we can do something similar for WDS v3 and v4.

I'm not sure this is a high priority considering WDS v4 is still in beta - is their any more info on the roadmap/ETA for a 4.0.0 release?

I think we'd just have a conditional branch, checking the WDS version, then supply the correct API. It looks like the `noInfo` key is the problem here. If you remove that line, does it work?

**Comment by mwren-mshanken** [comment]
Unfortunately, I don't see much directly referencing webpack-dev-server's roadmap in Webpack's documentation. Totally understand that this is low priority.

I will say that I tried removing `noInfo: false`, along with other options that are no longer supported.

It looks like `devServerPublicPathRoute` is no longer a part of the configuration object, but has moved to a separate dev object. I haven't had time to try to map this to the correct place and conditionalize, but that seems like a great approach!

**Comment by lmiller1990** [comment]
I think this should be fairly easy if someone wants to pick it up. The above approach is fine - just have a conditional checking for the different version of WDS, and make the relevant changes. Some `ts-ignore` may be needed.

If WDS v4 is getting close to release candidate or a full release we can bump this up in priority. Depending how things go, I might be able to spend some time on it. Alternatively, if anyone else is keen to pick this up, happy to work with you to get a PR up.

**Comment by derekdon** [comment]
Haven't tested, but _might_ be as easy as tweaking:

https://github.com/cypress-io/cypress/blob/e5ab805beb4d7c422e95c0ffc3ec03c3fdd1c04b/npm/webpack-dev-server/src/startServer.ts#L52

to

```
const webpackDevServerConfig: WebpackDevServer.Configuration = {
    ...userWebpackConfig.devServer,
    hot: false,
    dev: {
        publicPath: devServerPublicPathRoute,
    }
}
```

**Comment by lmiller1990** [comment]
That's basically what I was expected @derekdon. I'm not sure the best way to check for the version of WDS - maybe identifying a WDS v4 only property and seeing if it exists. This is how is works currently for webpack v4/v5 detection: https://github.com/cypress-io/cypress/blob/c340befb5a9134279d3febc3ef0bb0dea229b3be/npm/webpack-dev-server/src/plugin.ts#L88. I had a look in the [webpack dev server](https://github.com/webpack/webpack-dev-server/search?p=2&q=version) code base but it doesn't look like they have a `version` property we can use.

**Comment by derekdon** [comment]
On second thoughts I'm not sure version checking and code forking is the right way to go. Would it be better to just split the config generation from start and export both sides of it so the consumer can modify as they wish? That way the burden is on them if they use v3, v4, vX etc. This is a bit verbose, but might solve the problems. 

```
const { createWebpackConfig, createWebpackCompiler, createDevServerOptions, startDevServer } = require('@cypress/webpack-dev-server');
...
on('dev-server:start', options => {
        const cypressWebpackConfig = createWebpackConfig({...options, ...myOptionOverrides});
        const userWebpackConfig = merge(commonDev, cypressWebpackConfig, {...});
        const compiler = webpack(userWebpackConfig); // let them use webpack directly, or if you want some control, export a createWebpackCompiler
        const cypressDevServerOptions = createDevServerOptions(userWebpackConfig); // inspect user config and use it to create your options
        const userDevServerOptions = {
          ...cypressDevServerOptions,
          // do whatever I like
        };
        return new Server(compiler, userDevServerOptions); // let them use wds directly, or if you want some control export a new version of startDevServer
      }
    );
```

You could of course keep a simple single export version available to most users as you have today with startDevServer.

**Comment by lmiller1990** [comment]
Interesting proposal @derekdon. This solution would work great for a kind of expert user, who is very familiar with webpack and it's ecosystem. Supporting this would require exposing a lot of internals, which might make it difficult for us to implement changes in the future.

I still think it's worth considering, maybe @JessicaSachs or @agg23 or @elevatebart has an opinion. I think it's probably easier and an overall better DX to just support both WDS 3/4 alongside each other, like we do with webpack 4/5 at the moment.

**Comment by lmiller1990** [comment]
While we discuss the above, I was able to implement basic support for WDS v4 with minimal code changes here: https://github.com/cypress-io/cypress/pull/16414

**Comment by KaelWD** [comment]
Should this be closed now?

**Comment by lmiller1990** [comment]
I think so. We have basic support as of #16414. Let's keep an eye on WDS v4 as it moves to a stable release.
