### ISSUE TITLE
Display warning on `cypress run` if `timeout` is set > 10mins

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1632]
User's can set timeouts to be ridiculously high numbers. This is particularly a problem if the timeout is set over 10 minutes. 

```js
cy.get('.header', { timeout: 1000000 })
```

If, in the case above, for example, the `.header` turns out to not be found, then Cypress continues to try to find the element for over 10 minutes without any output. 

CircleCI, by default, will kill any run that does not have output for 10 minutes. Not all CI’s do this, but Circle does. 

So, the suggestion is to show a warning in stdout at the beginning of `cypress run` to warn the team that this could potentially cause timeouts and runs to not finish.

**Comment by bahmutov** [comment]
Why at the beginning of the run and not right before the command? We could show at the beginning for default global timeout

**Comment by jennifer-shehane** [comment]
I agree @bahmutov - Quotes from @brian-mann  on the subject when I spoke to him:

> its kind of a problem logging out in `stdout` while the tests are running
>
> mixing cypress messaging with the reporter stdout is a bad idea
>
> ive taken the stance of trying not to do that
>
> we’ve had people ask about silencing the other stuff before except for the reporter

He kind of ended up on the fence at the end of the discussion about it. It sounds like we kind of want to separate `stdout` from our own Cypress reporter - not sure why we couldn't do that as an overall strategy and then let user's decide if they want the "Cypress reporter"

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
