### ISSUE TITLE
Adding event handler for Cypress.on('fail') results in an unfailable test

### ISSUE THREAD

**Issue by nicojs** [cypress-io/cypress#16325]
### Current behavior

Add:

```js
// cypress/support/index.js
Cypress.on('fail', () => {});
```

results in a never failing test:

![image](https://user-images.githubusercontent.com/1828233/117030023-80a70700-acff-11eb-9554-645536fd8b60.png)

### Desired behavior

![image](https://user-images.githubusercontent.com/1828233/117030081-8ac90580-acff-11eb-8c6c-c5eec7668386.png)

### Test code to reproduce

```js
/// <reference types="cypress" />

context('Actions', () => {
  beforeEach(() => {
    cy.visit('https://example.cypress.io/commands/actions')
  })

  // https://on.cypress.io/interacting-with-elements

  it('.type() - type into a DOM element', () => {
    // https://on.cypress.io/type
    cy.get('.not exists')
      .type('fake@email.com').should('have.value', 'fake@email.com')
  })
})
```

### Versions

7.2

This definitely wasn't the case in 6.0.1

**Comment by jennifer-shehane** [comment]
This is expected behavior. If you are overwritting the 'fail' handler, then you are expected to handle it however you like and overwriting the default behavior. If you want to fail the test, you'll need to throw an Error in the fail handler. https://on.cypress.io/catalog-of-events#Catching-Test-Failures

```js
Cypress.on('fail', (error) => { 
  throw error
});

it('.type() - type into a DOM element', () => {
  cy.visit('https://example.cypress.io/commands/actions')
  cy.get('.not exists')
})
```

**Comment by nicojs** [comment]
Thanks for the quick response @jennifer-shehane . I've also found the workaround of rethrowing, that works great.

However, I would expect a message about this in the breaking changes list here: https://docs.cypress.io/guides/references/changelog#7-0-0. (or for another version, where this got introduced).

**Comment by jennifer-shehane** [comment]
I don't see any difference in the way the test above executes in Cypress 6.0.1 versus 7.2.0. The test passes in both versions when there is a 'fail' handler setup that does not rethrow the error.
