### ISSUE TITLE
cy.intercept should provide req.query since the url has the query object

### ISSUE THREAD

**Issue by eliw00d** [cypress-io/cypress#16327]
### Current behavior
`req.url` looks like `http://hostname:port/?someKey=someValue` but `req.query` is `undefined`.

### Desired behavior
`req.url` looks like `http://hostname:port/?someKey=someValue` and `req.query` is `{ someKey: 'someValue' }`.

### Test code to reproduce
```javascript
cy.intercept({ hostname }, (req) => {
  console.log(req.query) // undefined
  console.log(req.url) // http://hostname:port/?someKey=someValue
})
```

### Versions
Cypress: 7.2.0

**Comment by jennifer-shehane** [comment]
I can recreate this. Although I don't see `query` as a documented property that is meant to be available on the `req` object: https://on.cypress.io/intercept#Request-object-properties so I don't think this is a bug per se. 

But I can see the usefulness of wanting the req.query here.

### Example 

```js
it('test cy.intercept()', () => {
  cy.intercept({ url: '/users' }, (req) => {
    console.log(req)
    console.log(req.query) // undefined
    console.log(req.url)   // https://example.com/users?someKey=someValue
  }).as('getUrl')
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users?someKey=someValue')
    xhr.send()
  })
  cy.wait('@getUrl')
})
```

**Comment by eliw00d** [comment]
You are right, I think based on there being a query matcher I thought there would also be a query in the response, so this is more of a feature request. I was trying to do something like this for GraphQL:

```javascript
cy.intercept({ hostname }, (req) => {
  if (req.query?.operationName) {
    req.alias = req.query.operationName
  } else if (req.body?.query && req.body?.operationName) {
    req.alias = req.body.operationName
  }
```

but ended up doing this for now:

```javascript
cy.intercept({ hostname }, (req) => {
    if (req.url.includes('operationName')) {
      const { search } = url.parse(req.url)
      const searchParams = new URLSearchParams(search)
      req.alias = searchParams.get('operationName')
    } else if (req.body?.query && req.body?.operationName) {
      req.alias = req.body.operationName
    }
```

since we use persisted queries and this aliases the request based on GET vs POST and query vs mutation (which are not persisted).

**Comment by flotwig** [comment]
Yeah, I agree that it's weird to not have `query`. The only problem with this proposal is that `req.url` contains the querystring and can be modified, so it stands to reason that `req.query` can be modified as well. So, if a `query` property was added, any changes the user makes to it would have to be reconciled with changes to `req.url` somehow. 

IMO the best way to implement this would be to add `req.query`, but make it just a fancy getter/setter for `req.url`. What do you two think?

**Comment by eliw00d** [comment]
That sounds good to me!
