### ISSUE TITLE
Cypress window zooming off screen after restarting cyprress using 2 screens

### ISSUE THREAD

**Issue by TheNumbaCruncha** [cypress-io/cypress#16324]
### Current behavior
When i start cypress with npm run cypress:open from my current screen the cypress runner moves, and stays off screen

### Desired behavior
Cypress runner should appear on my scren

### Versions
7.2

Additional info: This has started happening since i used cypress on a laptop and monitor dual display when i extended desktops.
The runner was appearing on the second screen and i had no issues.
Npw I have went back to a single screen and I am having these issues. It looks like it is rememebering the position of the screen when i was using two monitors.

The ideal fix would be just to be able to reset the position the cypress window appears on

**Comment by TheNumbaCruncha** [comment]
so i fixed this by deleting all the cache files in appData and then i did a reinstall (not sure if the cache was re created correctly ) but probably there's an easier fix than a complete re-install .

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/4606
