### ISSUE TITLE
Can not click any button on menu bar of Cypress or the built-in Electron browser

### ISSUE THREAD

**Issue by EricKY26** [cypress-io/cypress#16323]
### Current behavior
Can not click any button on menu bar of Cypress or the built-in Electron browser, Even when I use ALT button on keyboard to select these ones, I cannot open any of these menus.
![image](https://user-images.githubusercontent.com/19644162/116975324-0f148c00-acf2-11eb-80a1-1745bb299696.png)

### Desired behavior
Can click buttons on menu bar of Cypress and the built-in Electron browser

### Test code to reproduce
Doesn't involve

### Versions
Cypress 7.2.0

**Comment by lukeapage** [comment]
just got the same issue, had to work-around getting devtools open using inspect element.

**Comment by jennifer-shehane** [comment]
Yah I saw someone else mention this but they didn't provide context. Are you both using Windows operating system?

**Comment by lukeapage** [comment]
I’m windows 10 yes

**Comment by EricKY26** [comment]
> Yah I saw someone else mention this but they didn't provide context. Are you both using Windows operating system?

@jennifer-shehane Yes, I'm using Windows 10

**Comment by jennifer-shehane** [comment]
I can recreate this in Windows 10. The menu bar is not selectable in 7.2.0.

**Comment by jennifer-shehane** [comment]
This issue does not exist in Cypress 7.1.0, so was introduced in 7.2.0. Pretty strange. All I can think that may be relevant is the Electron downgrade in 7.2.0? But I don't see this bug mentioned in Electron anywhere.

**Comment by csdivine** [comment]
I just noticed this as well. I'm running Cypress 7.2.0 on CentOS 7.

**Comment by EricKY26** [comment]
> This issue does not exist in Cypress 7.1.0, so was introduced in 7.2.0. Pretty strange. All I can think that may be relevant is the Electron downgrade in 7.2.0? 

That's exactly what I thought.

**Comment by CypressCecelia** [comment]
![windows menu](https://user-images.githubusercontent.com/60482585/121262274-d84a0c80-c881-11eb-89b5-34eeb517ef40.png)

Received additional reports of this, using latest version of Cypress.

**Comment by jennifer-shehane** [comment]
This bug was introduced in https://github.com/cypress-io/cypress/pull/16113

**Comment by jennifer-shehane** [comment]
Reopening as we are reverting the previous PR to avoid possible performance implications for many users on low resources machines recording video. We'll continue investigating and hopefully move towards updating Electron to fix this issue.

**Comment by strowk** [comment]
I have it on Ubuntu 20.04 (just fyi)

**Comment by srp-at-ah** [comment]
Same problem: Cypress 7.7.0 and Manjaro (XFCE)
