### ISSUE TITLE
cy.viewport() and TypeScript: Argument of type 'string' is not assignable to parameter of type 'ViewportPreset'.

### ISSUE THREAD

**Issue by 2ajh** [cypress-io/cypress#16339]
### Current behavior

Using TypeScript, and having this ViewportPreset array: 
```typescript 
const sizes = ['iphone-6', 'ipad-2'] 
```
When attempting to dynamically test multiple viewports:

```typescript
sizes.forEach(size => { 
    cy.viewport(size); 
})
```
 Then: `Argument of type 'string' is not assignable to parameter of type 'ViewportPreset'.`

![image](https://user-images.githubusercontent.com/26324473/117135677-940dad00-ada7-11eb-99f3-85ff1c9a0245.png)

### Desired behavior

Presets are supported when set from an array.

### Versions
Cypress 7.2.0

**Comment by 2ajh** [comment]
An ugly solution that is working for me is creating the following CustomCommand:
```typescript
Cypress.Commands.add("viewport2", size => {
  if (Cypress._.isArray(size)) {
    cy.viewport(size[0], size[1]);
  } else {
    cy.viewport(size);
  }
});
```

**Comment by bahmutov** [comment]
I think a better workaround would be ts-ignore comment above the line, no?

**Comment by 2ajh** [comment]
> I think a better workaround would be ts-ignore comment above the line, no?

Yes! I hadn't thought of that, thanks

**Comment by sainthkh** [comment]
Sorry for the late reply. The problem can be solved with the code below by specifying the type of items in the sizes array:

```ts
const sizes: Cypress.ViewportPreset[] = [ 'iphone-6', 'ipad-2' ] 

sizes.forEach(size => { 
  cy.viewport(size); 
})
```

I think leaing the current `cy.viewport` as-is better because it can help detect the typos.
