### ISSUE TITLE
Missing global Cypress in the parent window

### ISSUE THREAD

**Issue by jamaicabool** [cypress-io/cypress#16330]
### Current behavior
Cypress run gets stuck on loading assertion for 2 texts with error: 
"Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!"

script:
```js
//verify that total outstanding is same as booking amount
cy.get(':nth-child(2) > .payment-label-bottom').then(text => { //booking amount
     const bookingAmt = text;

     cy.get('.payments-panel > :nth-child(1) > .col-md-4 > :nth-child(1) > .booking-summary-panel > :nth-child(12) > :nth-child(2) > .pull-right').invoke('text').should('contain', bookingAmt) //total outstanding
      }); 
```

Cypress logs: (I cannot copy and paste the text because the Cypress got stuck)
https://ibb.co/z4n0Rmd

### Desired behavior
Should pass the assertion as both texts being compared are similar

### Versions

Version encountered: Cypress package version: 6.9.1
Mac OS Chrome Version 90.0.4430.93

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? We'll need that in order to investigate. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
