### ISSUE TITLE
The variables of level above are nullified  on the test case after using the cy.visit command

### ISSUE THREAD

**Issue by IvanHaid** [cypress-io/cypress#16340]
Reproducibility: Always
Env: Win10x64 v: 17134
**Steps**
1. Make a test case
2. Create variables of level above 
3. Collect data from first test case
4. Create second test case
5. Use the cy.visit command
6. Use the variable of level above
7. Observe
**Act**: The data of variable is nullified
**Exp**: The data of variable remained the same

**Example:**
let collect;
describe('RegistrationTestSuiteOnsite', () => {
    it('changes state', () => {
    cy.visit("http://www.google.com/")
    collect = "Name of Nubia"   
    cy.log(collect) 
    });
    it('changes state1', () => {
    cy.visit("http://mailinator.com")
    cy.log(collect)   
    });
    });

**Attachtments**
    
![JYVw48e3p8](https://user-images.githubusercontent.com/74537180/117137192-04b9c700-adb2-11eb-957e-02de1f6fccba.png)

**Comment by bahmutov** [comment]
In short: the spec is reloaded when the 2nd domain is visited, thus losing previously set variables. Luckily, it is not hard to store the values in more permanent place, like a file on disk, or inside the plugin file process. See the resolution in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/server-communication__visit-2nd-domain

**Comment by jennifer-shehane** [comment]
We have an example of how to save this in our docs also: https://on.cypress.io/task#Save-a-variable-across-non-same-origin-URL-visits
