### ISSUE TITLE
The more the test, the higher the memory occupation

### ISSUE THREAD

**Issue by lzxb** [cypress-io/cypress#1636]
### Current behavior: 
![image](https://user-images.githubusercontent.com/8424643/39223233-63926e14-4873-11e8-8447-21baa4bcd593.png)

### Versions  
Cypress 2.1.0
system: macOS
browser: chrome

**Comment by lzxb** [comment]
Maybe it's my program that has bug

**Comment by brian-mann** [comment]
Duplicate of

- https://github.com/cypress-io/cypress/issues/990#issuecomment-348517774
- https://github.com/cypress-io/cypress/issues/1586
- https://github.com/cypress-io/cypress/issues/681
