### ISSUE TITLE
Ability to mount a CSF story

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#16379]
### What would you like?
The same way I can mount a component using `@cypress/react`, I would like to mount a storybook story.

### Why is this needed?
Users of cypress component testing already have storybook stories installed in their codebase that they want to test.

**Comment by lmiller1990** [comment]
Relevant discussion about global styles: https://github.com/cypress-io/cypress/discussions/16294#discussioncomment-701552

We will need something like `preview-head.html`.

**Comment by elevatebart** [comment]
For react, I believe we already have a very relevant library called https://github.com/storybookjs/testing-react

We should think of doing the same for vue and angular.

Maybe within the storybook organization?

**Comment by lmiller1990** [comment]
Maybe we need to think about the goal a bit more. Just to confirm my understanding, if I have a super basic story like this:

```js
// MyComponent.stories.js

import React from 'react';

function MyButton({ innerText }) {
  const [show, setShow] = React.useState(false)
  return (
    <button onClick={() => setShow(!show)}>
      {innerText || 'Click me!'}
    </button>
    
    {show && <div>Hidden Message</div>}
}

export default {
  title: 'The story of the button',
  component: MyButton
};

export const Basic = () => <MyButton />;
export const WithProp = () => <MyButton innerText="Click me!" />;
```

It already work with `mount` - just import the story, `mount` it, and you are ready to go. 

My understanding is the main complexity is around two features:

## Args

Example from the storybook docs:

```js
import React from 'react';

import { ButtonGroup } from '../ButtonGroup';

//👇 Imports the Button stories
import * as ButtonStories from './Button.stories';

export default {
  title: 'ButtonGroup',
  component: ButtonGroup,
};
const Template = (args) => <ButtonGroup {...args} />;

export const Pair = Template.bind({});
Pair.args = {
  buttons: [{ ...ButtonStories.Primary.args }, { ...ButtonStories.Secondary.args }],
  orientation: 'horizontal',
};
```

In this scenario, the goal is to `mount(Pair)`?

## Decorators

Example from docs:

```js
// Button.stories.js

import React from 'react';

import Button from './Button';

export default {
  title: 'Button',
  component: Button,
  decorators: [
    (Story) => (
      <div style={{ margin: '3em' }}>
        <Story />
      </div>
    ),
  ],
};
```

We want to do:

```js
import DefaultButton from './Button.stories.js'

mount(DefaultButton)
```

This doesn't seems as complex as the `Args` API, and also seems lot more ergonomic. We should be aware there is also a [global decorator API](https://storybook.js.org/docs/react/writing-stories/decorators#global-decorators), that seems pretty important to consider.
