### ISSUE TITLE
(npm/vue) Vue 3 adapter should use @cypress/mount-utils

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#16387]
We have `@cypress/mount-utils` now, we should use it in the Vue 3 adapter for consistency.

**Comment by elevatebart** [comment]
I believe I did just that a few days ago. Did it not deliver?

**Comment by lmiller1990** [comment]
Right, great. We need to do a release for Cypress Vue.

Since the actual work has been done, I'll close this.
