### ISSUE TITLE
Cypress windows not rendering correctly in Xming

### ISSUE THREAD

**Issue by Oliver-Mitchell-CIC-UK** [cypress-io/cypress#16380]
### Current behavior

Initial test runner X window renders correctly but when clicking a test spec, a second X window opens but now both X windows render a flat grey. Tests can bee seen executing in the PuTTY window and although both windows are grey, the user can interact with elements, they just can't be seen.

### Desired behavior

All test runner windows should render elements consistently.

### Test code to reproduce

1. Run Cypress with PuTTY forwarding X11:

   ```sh
   ~ echo $DISPLAY
   127.0.0.1:10.0
   ~ cypress open
   ```

   Cypress Test Runner opens in X window.

1. Click to run an integration spec.

New X window opens but does not render anything, just shows grey, and the original window is now also grey.

Screen shots & logs: https://gist.github.com/Oliver-Mitchell-CIC-UK/b844b20e88ed072d2b736a581f0f392f

I have tried Git Bash and VS Code remote to do the X11 forwarding but all behave the same.

It could be an issue with Xming but I'm all out of ideas after a day of troubleshooting!

### Versions

Cypress: 7.2.0
Browser: Electron 89
Node.js: 14.15.1
Xming: 6.9.0.31
Remote OS: Amazon Linux 2 (4.14.231-173.361.amzn2.x86_64)
Local OS: Windows Server 2016 (10.0.14393)

**Comment by Ponthius** [comment]
U GitHub people stop sending me this s***t

**Comment by jennifer-shehane** [comment]
@Ponthius You may want to review your GitHub repo subscriptions and unwatch this repository if you are getting unwanted emails from this repo: https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions
