### ISSUE TITLE
Cypress Container iFrame is changing app window width

### ISSUE THREAD

**Issue by tayloraucoin** [cypress-io/cypress#16386]
### Current behavior
When testing component heights in our app, the **window width is being affected by the Cypress container iframe** element. In the browser we do not have a scrollbar and when inspecting in test-runner we can see its coming from the containing layer. 

Also, it is inconsistent on different machines. I wrote the tests and experience the scrollbar on my machine, but my coworkers do not get it when pulling the branch. 

https://user-images.githubusercontent.com/10913613/117381134-3d2fd280-ae90-11eb-8cca-4217e242437c.mp4

### Desired behavior
No added scrollbar by the Cypress containing iFrame. 

### Versions
cypress: 7.2.0
testing w/ chrome browser 90 in test-runner
macOS Mojave 10.14.6

**Comment by jennifer-shehane** [comment]
@tayloraucoin Can you provide some HTML/CSS/etc to reproduce this scrollbar that's present in Cypress and not outside? 

Do you happen to have 'Always' show scroll bars options set on your Mac and your coworkers don't?

>Click the Apple menu at the top-left of the screen, then select System Preferences.
>Next, select the General preferences pane; it's the very first one, up at the top.
>Under the “Show scroll bars” heading, you'll find three options: “Automatically based on input device,” “When scrolling,” and “Always.”

**Comment by tayloraucoin** [comment]
@jennifer-shehane 

Hi Jennifer,

No I already googled/checked to see if it was a mac setting, it is set to `Automatically based on mouse or trackpad`.

If its an issue requirement I can try and put something together.

**Comment by tayloraucoin** [comment]
@jennifer-shehane do you guys w/ Cypress have a code sandbox example that you like to use as a baseline? 

I started a Next.js codebase on codesandbox (including set to node 14) but cypress was rejecting it on load. Restarted server which is supposed to be all it needs. 

https://codesandbox.io/s/blissful-cray-ldyf0?file=/sandbox.config.json
