### ISSUE TITLE
cy.wait() doesn't work as expected

### ISSUE THREAD

**Issue by baeharam** [cypress-io/cypress#16389]
### Current behavior

I'm using Cypress with Apollo and I'm sending network error to slack via Sentry. But, when I run E2E test with Cypress, network error `Failed to fetch` occurs very often and flaky. I debugged why this error is occurred and found out cypress re-render before graphql request is completed. It means that **cypress cancels request when moving to other page.**

To solve this problem, I inserted `cy.wait()` before testing specific case like below.

```typescript
beforeEach(function() {
  cy.wait('@request1');
  cy.wait('@request2');
  cy.wait('@request3');
  ....// till every requests were completed
});

it('some specific test', function() {
  ...
});
```

However, it doesn't work in some cases so I changed alias waiting to time waiting.

```typescript
beforeEach(function() {
  cy.wait(2000);
  ....// till every requests were completed
});

it('some specific test', function() {
  ...
});
```

And it worked and doesn't occur any `failed to fetch` error! But, it is anti-pattern. In this situation, why `cy.wait()` doesn't work as expected?

### Desired behavior

When I specify every aliases per request, it should wait every Graphql requests before testing starts.

### Test code to reproduce

Above codes that wait all graphql requests.

(1) Alias every requests for loaded page
(2) Wait every aliased requests before starting test

-->`Failed to fetch` error is occurred intermittently. (flaky)

### Versions

Cypress: 7.1.0
OS: Mac OS Catalina 10.15.5

**Comment by jennifer-shehane** [comment]
We'll need a way to reproduce this on our end to see the error. Can you provide a failing example we can run? Thanks.

**Comment by baeharam** [comment]
If anyone need this problem to be solved, please re-open other issue. Thanks.
