### ISSUE TITLE
Cancel jobs on Github Actions does not stop cypress run

### ISSUE THREAD

**Issue by LuyTester** [cypress-io/cypress#16395]
I have Integration Cypress with Git actions for Continues integration, after git actions ends, Cypress neves stop running. 
Only when git actions cancel a job. 

How should i deal with it? 

thanks

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by gonjavi** [comment]
I have this issue, I am using act :https://github.com/nektos/act/issues, to test the pull request locally, I start running the cypress actions it completes all the created tests but continue testing them again as a circle and never stops, I think is the same case as the person above
