### ISSUE TITLE
Cannot use spaces for id in cy.get()

### ISSUE THREAD

**Issue by heagan01** [cypress-io/cypress#16410]
### Current behavior

When I tried `cy.get('#Cookies\ n\ Cream').type(1)`, it says `Timed out retrying after 4000ms: Expected to find element: #Cookies n Cream, but never found it.`, But I used the selector tool in cypress.

### Desired behavior
in it
Select the input and type 1 

### Test code to reproduce

```js 
cy.get('#Cookies\ n\ Cream').type(1)
```

### Versions

I can't find it I ran the app locally, I run it in firefox 84, and windows 10

**Comment by Zaista** [comment]
Make sure to double escape the space:
<code>cy.get('#Cookies\\\ n\\\ Cream').type(1)

Or even better, let developers know not to use spaces or dots in element ids.
Cheers

**Comment by heagan01** [comment]
> Make sure to double escape the space:
> <code>cy.get('#Cookies\\\ n\\\ Cream').type(1)
> 
> Or even better, let developers know not to use spaces or dots in element ids.
> Cheers

Thanks!

**Comment by jennifer-shehane** [comment]
ID's with spaces are not valid HTML, so you'll likely find that many libraries do not accommodate for this since this is invalid. 

>When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value must not contain any ASCII whitespace. https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute

Can you provide the exact HTML with the ID that you're testing against? I'm not sure what the exact ID is from what you've written.

**Comment by heagan01** [comment]
I'm sorry but this is my own project, and i don't have a domain for this

**Comment by heagan01** [comment]
> ID's with spaces are not valid HTML, so you'll likely find that many libraries do not accommodate for this since this is invalid. 
> 
> >When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value must not contain any ASCII whitespace. https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute
> 
> Can you provide the exact HTML with the ID that you're testing against? I'm not sure what the exact ID is from what you've written.

I'm sorry, but I dont have a domain for this
