### ISSUE TITLE
xhr.send(formData) doesn't work when upgraded  to cypress 7.2.0 ,

### ISSUE THREAD

**Issue by SanjayVeernala** [cypress-io/cypress#16422]
### Current behavior
Not able to send the formData with Post Request after upgrading to cypress 7.2.0 ,
but with 6.9.1 it was working absolutely fine.

The error given at xhr.send is "failed to load resource: the server responded with a status of 500 (Internal Server Error) "

### Desired behavior
Should able to send formData with Post request in cypress
### Test code to reproduce
my custom command:
```js
Cypress.Commands.add('formRequest', (url, filePath) => {
	const xhr = new XMLHttpRequest();
	const formData = new FormData();
	return cy
		.intercept('POST', url)
		.as('formRequest')
		.fixture(filePath, 'binary')
		.then(file => {
			const blob = Cypress.Blob.binaryStringToBlob(
				file,
				'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
			);
			formData.set('file', blob, `cypress/fixtures/${filePath}`);
			formData.set('input2', `input_content2`);
			xhr.open(`POST`, url);
			xhr.setRequestHeader('cf-admin-key', '*********');
			xhr.send(formData);
		})
		.wait('@formRequest', {timeout: 60000});
});
```

### Versions
current version : 7.2.0,

previous version: 6.9.1

**Comment by sainthkh** [comment]
Sorry for the late reply.

From 7.4.0, Cypress can send `FormData` with `cy.request()`. Maybe it can solve your problems.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
