### ISSUE TITLE
[7.2.0]The image does not load

### ISSUE THREAD

**Issue by softshipper** [cypress-io/cypress#16425]
Hi all 

Running the E2E test on Next.JS web app, I have got the following error message:
![Screenshot from 2021-05-10 17-28-35](https://user-images.githubusercontent.com/56756949/117684349-33221280-b1b5-11eb-945a-3025c824e211.png)

I recorded it as a video:

https://user-images.githubusercontent.com/56756949/117684453-4c2ac380-b1b5-11eb-9f95-bc7e5b177116.mp4

As you can see, the image does not get loaded. The fully loaded site should look as follows:
![Screenshot from 2021-05-10 17-30-25](https://user-images.githubusercontent.com/56756949/117684647-7aa89e80-b1b5-11eb-8a36-4ae76e54779b.png)

The browser is Chromium and I have downloaded it from https://chromium.cypress.io/linux/stable/90.0.4430.93. 
Running the test on firefox works fine:

https://user-images.githubusercontent.com/56756949/117686064-c9a30380-b1b6-11eb-85c9-fb35a2701b63.mp4

I think something is wrong with Chromium.

The web app is tested on MacOS and PopOS on Chromium. The result is the same. 
[cynext.zip](https://github.com/cypress-io/cypress/files/6453254/cynext.zip)

Best regards,
Softshipper

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I tested the app with Ubuntu 20.04 + Chrome 91. But it worked without fail. Is it still not working?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
