### ISSUE TITLE
Component testing does not honour configuration values provided by plugins. 

### ISSUE THREAD

**Issue by 3rd-Eden** [cypress-io/cypress#16424]
### Current behavior

In Cypress `^6.8.0` it was possible to configure component testing using a plugin file by modifying the received configuration. Since the release of 7 this is no longer possible and requires you to configure component testing
in the `cypress.json` file instead. 

### Desired behavior

It should honour the plugin overrides.

### Test code to reproduce

The Cypress.json that is now required, (this was empty on 6.8.0)

```json
{
  "component": {
    "componentFolder": ".",
    "fixturesFolder": false,
    "ignoreTestFiles": "**/node_modules/**",
    "testFiles": "**/*.cypress.js"
  }
}
```

The previous configuration merged in a plugin file:

```js
module.exports = function (on, base) {
    const config = require('deepmerge')(base, {
        testFiles: '**/*.cypress.js',
        integrationFolder: 'cypress',
        ignoreTestFiles: '**/node_modules/**',
        experimentalComponentTesting: true,
    });

    return config;
}
```

Packages:
-`cypress`: ^7.2.0
-`@cypress/react`: ^5.4.2
-`@cypress/webpack-dev-server`: ^1.1.6

Environment: 
-Node.js: v12.9.0
-NPM: 6.10.2

**Comment by lmiller1990** [comment]
Seems like a regression. Those defaults should be applied to both e2e and CT. Are you launching the component testing runner using `npx cypress open-ct`, or still using the original component testing plugin in the e2e? [Blog post discussion new Component Testing specific runner](https://www.cypress.io/blog/2021/04/06/introducing-the-cypress-component-test-runner/).

**Comment by lmiller1990** [comment]
I was not able to reproduce this. I'm using the Component Testing runner with the latest version of Cypress (7.3.0). My overrides in `cypress/plugins/index.js` worked, I was able to set the viewport height/width to 888, overriding `cypress.json`:

![image](https://user-images.githubusercontent.com/19196536/117757758-08db5e00-b264-11eb-9b0d-cf929c0c9e00.png)

**Comment by lmiller1990** [comment]
In your above screenshot, it looks like the sidebar is just really small.

![image](https://user-images.githubusercontent.com/19196536/117915773-4fdf5700-b329-11eb-94df-f30e439ec2bf.png)

See [this comment](https://github.com/cypress-io/cypress/issues/16356#issuecomment-833583632).

Back to your issue: I understand now and I reproduced the problem by creating an empty `cypress.json` and inlining the configuration in `plugins/index.js`. I will work on fixing this now.

**Comment by lmiller1990** [comment]
I am working on this [here](https://github.com/cypress-io/cypress/pull/16468). I added a minimal reproduction.

**Comment by lmiller1990** [comment]
Ok, I fixed it: https://github.com/cypress-io/cypress/pull/16468

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/16468, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
