### ISSUE TITLE
app.$store is not available

### ISSUE THREAD

**Issue by musicformellons** [cypress-io/cypress#1642]
I am following [this blog](https://www.cypress.io/blog/2017/11/28/testing-vue-web-application-with-vuex-data-store-and-rest-backend/#Store-to-UI-and-server-API). The window.app property does appear in the console after adding the code as described, however I can not reference `app.$store`. I can reference `app.store` which indeed contains properties from my vuex store, but it does not contain the `app.store.state`, just the getters (and dispatches etc.). 

E.g. using  `const getStore = () => cy.window().its('app.store')` it gives:

![screenshot from 2018-04-26 09-27-25](https://user-images.githubusercontent.com/10334123/39292130-87c91568-4935-11e8-9241-25de7e55a921.png)

I would prefer to be able to have state variables available directly and not only the once I made a getter for. What's wrong? Is this because I use namespacing in my vuex store?

**Comment by aidan99davis** [comment]
@musicformellons  Are you using firefox?

**Comment by musicformellons** [comment]
No, I use Chrome. It might relate to my way of assigning the store to the window. I use Quasar Framework, which in current version (>0.15) does a lot of configuration based on the settings in the `quasar.conf.js` file it uses. I assigned the store by adding this code as a [quasar plugin](http://quasar-framework.org/guide/app-plugins.html):
```
export default ({ app, store, Vue }) => {
  if (window.Cypress) { // should only be available during E2E tests
    window.app = app
  }
}
```
Doing so gives me indeed the `app.store` I mentioned, but not `app.$store` (including `state`). Quasar config is generated and shown in a file, which after adding this plugin contains:
```
/**
 * THIS FILE IS GENERATED AUTOMATICALLY.
 * DO NOT EDIT.
 *
 * You are probably looking on adding initialization code.
 * Use "quasar new plugin <name>" and add it there.
 * One plugin per concern. Then reference the file(s) in quasar.conf.js > plugins:
 * plugins: ['file', ...] // do not add ".js" extension to it.
 **/
import './quasar'
import Vue from 'vue'
Vue.config.productionTip = false
import 'quasar-app-styl'
import 'src/css/app.styl'
import App from 'src/App'
import router from 'src/router'
import store from 'src/store'

const app = {
  el: '#q-app',
  router,
store,
  ...App
}

const plugins = []

import pluginCypress_vuex_store from 'src/plugins/cypress_vuex_store'
plugins.push(pluginCypress_vuex_store)

import pluginVuelidate from 'src/plugins/vuelidate'
plugins.push(pluginVuelidate)

plugins.forEach(plugin => plugin({ app, router, store, Vue }))

new Vue(app)
```
As you can see the plugins are part of initialising the Vue app, whereas the way the blog and you suggest it, it is attached after the Vue initialisation. As Quasar autogenerates the config I do not know how to do 'window.app = app' after the initialisation to see if this causes my issue...

**Comment by musicformellons** [comment]
Ah, solved: see [here](https://stackoverflow.com/questions/50037628/can-not-get-vuex-state-using-cypress/50040210#50040210)!
