### ISSUE TITLE
Alias error message confusing

### ISSUE THREAD

**Issue by dericgw** [cypress-io/cypress#1643]
Whenever using an alias, if you happen to prefix the alias like so:
```js
cy.route('/some-route').as('@postMessage');
```
Cypress will give you an error message that is a bit hard to understand. It leads you to believe that you are doing the right thing, when in fact, you are not. Have a look:

<img width="585" alt="code" src="https://user-images.githubusercontent.com/34040106/39317422-2c084120-4941-11e8-820e-950c33e47f6a.png">

As you can see, it says that it cannot find `@postPassword` but the available aliases are `@postPassword`.

An error message that explains not to use the `@` in the `as` method, or possibly even has a link to the page on aliases would help avoid this.

**Comment by jennifer-shehane** [comment]
The alias gets sent to this `validateAlias` function and *does* have some checks for the type of argument it can have. Another `if` statement could easily be added here to throw an error if they alias begins with `@`

Code here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/aliases.coffee#L17

Please feel free to contribute/open a 'Work in Progress' PR. 😄
