### ISSUE TITLE
Hooks are being executed, but tests inside "it" not

### ISSUE THREAD

**Issue by clarissaar** [cypress-io/cypress#16432]
Hi all,

I´m executing following spec, and `before` and `after` hooks are properly running, but functions inside `it` test itself not - it ran correctly for a while, but right now it´s not running anymore, without any new update.
Going through documentation seems it´s correct. Does anyone have some idea about some workaround or the rootcause of this issue?

Cypress package version: 7.3.0
Cypress binary version: 7.3.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1
npm: 7.12.0
Node: 16.1.0

```js
import { createProject, deleteProject } from "../../pages/dashboardPage";
import { login } from "../../pages/loginPage";
import { importModel, editModel } from "../../pages/modellerPage";

describe('Workbench Functionality', () => {
    before(() => {
        login()
    });

    let projectTitle = 'ProjecTitle';
    let projectDescription = 'ProjectDescription';

    it('Create a project, Import and Edit a model, removing faces and Save it', () => {
        createProject(projectTitle, projectDescription);
        importModel('/Pipe Junction Model.x_t');
        editModel('#treeItem_B1_TE30', '#treeItem_B1_TE20');
    });

    after(() => {
        deleteProject(projectTitle);
    });
});

**Comment by lmiller1990** [comment]
Cool, thanks. Can you update the repro to be working out of the box? eg, moving the directories into the default location, `cypress`, install the necessary deps (when I ran it, it complains `faker` doesn't exist) and tell me exactly which spec to run?
