### ISSUE TITLE
npm download 404

### ISSUE THREAD

**Issue by alifa20** [cypress-io/cypress#16435]
### Current behavior
npm install fails to download binary.

### Debug logs
```
The Cypress App could not be downloaded.
--
  |  
  | Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
  |  
  | Otherwise, please check network connectivity and try again:
  |  
  | ----------
  |  
  | URL: https://download.cypress.io/desktop/7.3.0?platform=linux&arch=x64
  | Error: Failed downloading the Cypress binary.
  | Response code: 404
  | Response message: Not Found
  |  
  | ----------
  |  
  | Platform: linux (Debian - 10.5)
  | Cypress Version: 7.3.0
  |  
  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  | make: *** [/usr/local/cicd/make/web.mk:41: yarn] Error 1


```

### Desired behavior:
Cypress to download.

### Download method
yarn add cypress

- [ ] npm
- [x] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [X] Linux
- [ ] Mac
- [ ] Windows

### Other

- [x] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI 

### Versions
Debian 10.5 - 32 bit

### Note
Hitting https://download.cypress.io/desktop/7.3.0?platform=linux and removing the second query param seems to be working fine.

**Comment by emilgoldsmith** [comment]
I have this occuring on CI in my dependabot PR

**Comment by kpoelhekke** [comment]
Same problem here in our CI, I've downgraded cypress because of it

**Comment by EivydasKoc** [comment]
> I have this occuring on CI in my dependabot PR

same for me, seems to be intermittent as once in a blue moon it doesn't fail

**Comment by slauzinho** [comment]
I'm also having the same issue, can't get the CI to upgrade to the latest cypress version:

```
URL: https://download.cypress.io/desktop/7.3.0?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
```

**Comment by tgriesser** [comment]
Just cleared the cache here, the download should be resolving correctly now.

**Comment by alifa20** [comment]
Thanks a lot @tgreen7 , works like a charm now !

**Comment by phelipetls** [comment]
I'm seeing this error now as well.

```
----------
URL: https://download.cypress.io/desktop/1?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
----------
Platform: linux (Debian - 10.5)
Cypress Version: 8.6.0
```

**Comment by MFry** [comment]
Does the cache need to be cleared again? I am seeing the same problem when trying to download 
```
npm ERR! [FAILED] URL: https://download.cypress.io/desktop/1?platform=linux&arch=x64
npm ERR! [FAILED] Error: Failed downloading the Cypress binary.
npm ERR! [FAILED] Response code: 404
npm ERR! [FAILED] Response message: Not Found
```

**Comment by danielmhair** [comment]
Same here. I'm in a gitpod instance, but it hasn't been an issue before.

**Comment by BenShelton** [comment]
> Does the cache need to be cleared again? I am seeing the same problem when trying to download
> 
> ```
> npm ERR! [FAILED] URL: https://download.cypress.io/desktop/1?platform=linux&arch=x64
> npm ERR! [FAILED] Error: Failed downloading the Cypress binary.
> npm ERR! [FAILED] Response code: 404
> npm ERR! [FAILED] Response message: Not Found
> ```

I was getting the same error today, for future reference this is probably because you have `CYPRESS_INSTALL_BINARY` environment variable set as `1`, which I initially thought meant to enable binary installation, but actually means install version 1 of cypress which results in a 404.

**Comment by jennifer-shehane** [comment]
Please open a new issue if a similar error is encountered.
