### ISSUE TITLE
Mac usage should be able to accept a command line arg for project

### ISSUE THREAD

**Issue by paul-hammant** [cypress-io/cypress#1644]
Typing:

`open . -a Cypress` 

.. on the mac will invoke:

`/path/to/Cypress.app/Contents/MacOS/Cypress /path/to/currentDirectory`

.. but Cypress ignores that argument :-(

It would be great if it did not :)

**Comment by bahmutov** [comment]
so a couple of things
- Cypress binary is NOT meant to be invoked directly (because of CLI argument parsing that happens in the NPM package `cypress`)
- `cypress` package already allows you to pass the project path, just maybe install cypress globally and run
```
npm install -g cypress
cypress open --project /path/to/the/folder
```

**Comment by paul-hammant** [comment]
That's an arbitrary decision. The "load a project" capability exists within the UI itself, and could *easily* have equivalent functionality from the Mac-command-line launching of the UI.

**Comment by bahmutov** [comment]
Believe us - after 4 years, 11k commits and 1600 issues, no decision is arbitrary, but made after considering all pluses and minuses.
