### ISSUE TITLE
scrollBehavior: center ignored when in global config but respected when in click options object

### ISSUE THREAD

**Issue by gkatsanos** [cypress-io/cypress#16442]
I've added `  "scrollBehavior": "center"` to my cypress.json file:
```js
 {
  "baseUrl": "http://localhost:3000",
  "fixturesFolder": "test/e2e/fixtures",
  "integrationFolder": "test/e2e/integration",
  "pluginsFile": "test/e2e/plugins/index.js",
  "screenshotsFolder": "test/e2e/screenshots",
  "supportFile": "test/e2e/support/index.js",
  "videosFolder": "test/e2e/videos",
  "viewportWidth": 1366,
  "viewportHeight": 768,
  "scrollBehavior": "center"
}
```
but elements still scroll to the top most part of the page when clicked or `get`. 
I unfortunately can't provide a reproduction link as that'd mean essentially recreating the entire page, but what I can do is provide a live link of the HTML in question and the script I use. 

script: 

```js
describe('About us', () => {
  before(() => {
    cy.visit('/de/firma/boli-verpackungen-gmbh-548358')
  })

  it('when clicking right/left arrow, new items appear', () => {
    cy.get('#company-media-about-us').within(() => {
      cy.get('[data-test=about-us-next-arrow]').click()
      cy.get('[data-index=4]').should('be.visible')
      cy.get('[data-test=about-us-prev-arrow]').click()
      cy.get('[data-index=0]').should('be.visible')
    })
  })
})
```
This code does work though: 

```js
describe('About us', () => {
  before(() => {
    cy.visit('/de/firma/boli-verpackungen-gmbh-548358')
  })

  it('when clicking right/left arrow, new items appear', () => {
    cy.get('#company-media-about-us').within(() => {
      cy.get('[data-test=about-us-next-arrow]').click({ scrollBehavior: 'center' })
      cy.get('[data-index=4]').should('be.visible')
      cy.get('[data-test=about-us-prev-arrow]').click({ scrollBehavior: 'center' })
      cy.get('[data-index=0]').should('be.visible')
    })
  })
})
```

**Comment by gkatsanos** [comment]
Thank you for taking a look at this! disclaimer: I don't run my test against production but with the same HTML on my localhost dev server. Sometimes it passes, most often it doesnt. Here's where it fails : it tries to click on the link but the link isn't at the center of the page, but at the topmost part, and it's hidden by the div which is animated on top of it. I hope this screenshot can help. 

![image](https://user-images.githubusercontent.com/1768834/117924325-3aa10300-b2fe-11eb-87c0-241ad4cea19c.png)

**Comment by gkatsanos** [comment]
@jennifer-shehane can I help you with more information?

**Comment by jennifer-shehane** [comment]
The preview of the click might be scrolling differently than what actually happens during the click, so hoveringg over 'click' will always scroll the element to the top, even though the element may not have been there during the click. Can you add a `pause()` to see exactly where the scroll is when the click happens?

```js
    cy.get('[data-test=about-us-prev-arrow]').pause().click()
```

I'm just not able to reproduce it from the given example. It scrolls to center each time. I ran it 50 times. 

```js
describe("Testing", () => {
    Array(50).fill(0).forEach((val, i) => {
        it(`${i}: when clicking right/left arrow, new items appear`, () => {
            cy.visit('https://www.wlw.de/de/firma/boli-verpackungen-gmbh-548358')
            cy.get('#CybotCookiebotDialogFooterButtonAcceptAll').click()
            cy.get('#company-media-about-us').within(() => {
                cy.get('[data-test=about-us-next-arrow]').click()
                cy.get('[data-index=4]').should('be.visible')
                cy.get('[data-test=about-us-prev-arrow]').click()
                cy.get('[data-index=0]').should('be.visible')
            })
        })
    })
})
```

**Comment by gkatsanos** [comment]
I was able to get more passes by adding [scrollIntoView](https://docs.cypress.io/api/commands/scrollintoview) but it still fails. I saved the fail video here , in case it might help? 

https://user-images.githubusercontent.com/1768834/118649516-40aa4e80-b7ec-11eb-9dd2-d9fb148d4650.mp4

**Comment by gkatsanos** [comment]
@jennifer-shehane This is running on Gitlab CI so I don't have a lot of room to increase CPU :/  screen size is :
```
  "viewportWidth": 1280,
  "viewportHeight": 768,
```
The issue appears on both `open` and `run`

**Comment by gkatsanos** [comment]
https://user-images.githubusercontent.com/1768834/118667026-4e67d000-b7fc-11eb-8dc7-9323ef3e8b67.mp4

@jennifer-shehane I run it locally, it failed, and I'm uploading this video which is a lot smoother..

**Comment by gkatsanos** [comment]
@jennifer-shehane as the slide of the Carousel involves an animation , I am wondering if this is a racing issue dependent on system specs.. (cpu/memory). I dont know exactly how to tackle it but my instinct says I have to explicitly tell Cypress to wait for a specific time before evaluating ?

**Comment by gkatsanos** [comment]
@jennifer-shehane adding 2 artificial waits seems to have solved it:
```js
  it('when clicking right/left arrow, new items appear', () => {
    cy.get('#company-media-about-us').within(() => {
      cy.get('[data-test=about-us-next-arrow]').scrollIntoView().click()
      cy.get('[data-index=4]').should('be.visible')
      cy.wait(1500)
      cy.get('[data-test=about-us-prev-arrow]').scrollIntoView().click()
      cy.wait(1500)
      cy.get('[data-index=0]').should('be.visible')
    })
  })

```

**Comment by gplusdotgr** [comment]
Unfortunately reasons like this bug have pushed us to look into alternatives. Flimsiness is something that's a deal breaker as it causes lost time and effort from engineers to try to debug non-existent bugs.
