### ISSUE TITLE
Cypress errors on cy.type in an input type='phone'

### ISSUE THREAD

**Issue by lobor** [cypress-io/cypress#1645]
When writing the following code, an error displays saying cy.type can't be used on the specified input with `type="phone"`

###Example Code

```js
cy.type('[type="phone"]').type('1234567')
```

###Error
```js
CypressError: .type() can only be called on textarea or :text!
```

It needs to be whitelisted to allow typing into similar to types text, search, url, etc.

**Comment by jennifer-shehane** [comment]
`phone` is not a valid input type in html, `tel` is valid. If you are able, update your html: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

That being said, many users have asked us to loosen our validation logic, which is being tracked in this issue: https://github.com/cypress-io/cypress/issues/586
