### ISSUE TITLE
Investigate React DevTools improvements/alternative implementation

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16455]
The current implementation of React DevTools leaves much to be desired. It is not reliable when switching between specs or rerunning the existing spec, and the standard interaction model is damaged (inspect element will jump you to the DevTools around the runner, not the AUT, the React element selector doesn't work at all, etc...).

Explore areas of improvement, whether modifying the existing methods or developing a new one.

**Comment by piotrpalek** [comment]
Any tips on how to use react-devtools with component testing?

**Comment by rockindahizzy** [comment]
https://docs.cypress.io/guides/references/migration-guide#Component-Testing-Updates

**Comment by lmiller1990** [comment]
Going to track here: https://github.com/cypress-io/cypress/issues/15873
This would be nice, I think we should a public API so third parties can embed their devtools (like Vue, Redux, React..).
