### ISSUE TITLE
I'm facing an issue to navigate to URLs i provide while running my scripts it gave 404 error whenever i try to use cy.visit 

### ISSUE THREAD

**Issue by Mkawad** [cypress-io/cypress#16462]
Hi everyone, 
I'm facing an issue to navigate to the URLs i need, it's a 404 error
i'm only able to navigate to the base url to login into the site, after loging into the site i can not use cy.visit due to it gave 404 page not found error even tho i'm sure that the URL is correct 
i'm using 6.2.0 cypress version, and i tried the latest version of cypress it gave me the same result
could anyone please help me to figure out what the issue here and how to solve it 

thanks in advance

**Comment by bahmutov** [comment]
When the site runs, can you visit the site directly by entering the URL? I suspect you have client-side app without fallback https://glebbahmutov.com/blog/routing-with-fallback/

So it would not be a Cypress problem, but just the problem with the server setup itself
