### ISSUE TITLE
RangeError Invalid String length for file > 90MB and fixtures

### ISSUE THREAD

**Issue by mguthmuller** [cypress-io/cypress#16470]
### Current behavior

I'm working on a project in which we upload a file. A limit is set for the size of the file (200MB) that can be uploaded. So, in my tests, I'd like to test this limit by uploading a file with a size superior to the limit and check that an error is returned by the application.

For file uploading, I'm using fixtures. I generated a 200MB file and a second one 201MB file. However, I have an error about Invalid String length when I access to these files with fixtures.

After some tests, it seems that it works until 89MB and it starts to fail with files superior to 90MB. 

![fixture_error](https://user-images.githubusercontent.com/11680465/117956293-333b2300-b319-11eb-8eef-4d0a2aec6ba9.png)

### Desired behavior

I'd like to test with files superior to 200MB in my case.

### Test code to reproduce

Generate a file with a specific size with truncate : truncate -s 90MB file_90MB.txt

Load this file as fixture in a test => error!

### Versions

Cypress 7.3.0

**Comment by jennifer-shehane** [comment]
I've seen an error before with large fixture files timing out. https://github.com/cypress-io/cypress/issues/7365

@mguthmuller Can you try your test in Cypress 7.2.0? We made changes in socket.io recently and I wonder if it's related.

**Comment by mguthmuller** [comment]
Same error with Cypress 7.2.0... However, the issue that you mentioned indicates a timeout that I don't have in my case. The error relates to the size of the file, during the "stringifying" and parsing, so I'm not sure the issues are linked.

**Comment by sainthkh** [comment]
Internally, Cypress's `socket.io` uses `circular-json` to `stringify` objects and this `stringify` is the `JSON.stringify` with replacer function [(check this)](https://github.com/WebReflection/circular-json/blob/master/src/circular-json.js#L165-L183). 

And Nodejs's JSON.stringify has a size limit and it throws `Invalid string length` error when a too-long string is passed [(check this StackOverflow article)](https://stackoverflow.com/questions/29175877/json-stringify-throws-rangeerror-invalid-string-length-for-huge-objects)

From my research, I learned that the problem could be solved by breaking the file into smaller chunks and send them one by one. Maybe I should try that way.

**Comment by shixinla** [comment]
Same error with Cypress 8.4.0, is there any fix?

**Comment by BlueWinds** [comment]
In Cypress 9.0.0, we added the `null` encoding, which helps significantly when dealing with large fixtures and files. This transfers the data as an ArrayBuffer rather than a base64 encoded string.
https://docs.cypress.io/api/commands/fixture#Arguments

Cypress still tends to encounter issues with files in the gigabyte range, but 90mb should now work if you pass in `null` as an ecnoding. Going to close this issue as resolved, feel free to let us know if the above still isn't working for you.
