### ISSUE TITLE
cy.find is not reported properly in Cypress UI when used in a custom Cypress.Command

### ISSUE THREAD

**Issue by RodolpheNivelet** [cypress-io/cypress#16477]
Hello,

I had a small issue when using a `.find()` function in a custom Cypress.Command.

If I do a request like this :
```js
cy.get('[data-test=survey-question-next-button]')
  .eq(34)
  .find('[data-test=address-control-prediction]')
  .eq(0)
  .click();
```

I get this report in the UI :
<img width="331" alt="Screenshot 2021-05-12 at 16 04 38" src="https://user-images.githubusercontent.com/5870047/117989299-7c509e80-b33c-11eb-8fae-df74e32f3d54.png">

But if I had a custom command like so :
```js
Cypress.Commands.add(
  'findElem',
  {
    prevSubject: true,
  },
  (subject, selector: string) => {
    return subject.find(`[data-test="${selector}"]`);
  }
);
```

And then I change the request to :
```js
cy.get('[data-test=survey-question-next-button]')
  .eq(34)
  .findElem('address-control-prediction')
  .eq(0)
  .click();
```

The report I get is :
<img width="319" alt="Screenshot 2021-05-12 at 16 03 23" src="https://user-images.githubusercontent.com/5870047/117989569-b9b52c00-b33c-11eb-9b0f-1905649324be.png">

It's still working fine but the UI is not showing the right thing.

Version of Cypress : 7.3.0
Using Typescript version : 4.2.4
OS: macOS 10.15.7
Chrome version 90

Thank you,
Rodolphe Nivelet

**Comment by jennifer-shehane** [comment]
For custom commands, you need to call `Cypress.log()` to tell it what to log to the Command Log: https://on.cypress.io/cypress-log
