### ISSUE TITLE
runner-ct: Component test cy.screenshot has unneeded background 

### ISSUE THREAD

**Issue by pashidlos** [cypress-io/cypress#16478]
Before migrating to cypress `v7` when I used to make full page screenshot it was only mounted component full screen
After migrating I get some background over component 

is that expected and if possible to remove this background having only component?

<img width="1555" alt="1" src="https://user-images.githubusercontent.com/5182956/117993050-10743300-b348-11eb-988e-198deafcfa66.png">

**Comment by lmiller1990** [comment]
Definitely a regression. I tried a few images and it was working for me, though. I'll try some larger images.

If you have a reproduction by any chance, that'd be great.

**Comment by lmiller1990** [comment]
It's not happening anymore - I am not sure why. Please share your component and test.

**Comment by pashidlos** [comment]
@lmiller1990 thanks for clarification 
will be waiting for resolve of #15934
should I close this ticket then?

**Comment by lmiller1990** [comment]
Let's leave this open until it's solved. Should be soon :)

**Comment by lmiller1990** [comment]
Are you setting `cy.viewport` explicitly? What are you setting it to? Also does your component have somthing like `width: 1000px` or more like `width: 100%` or `width: 100vw`?

Unlike e2e tests, I think the use case can be slighly different here - often components are designed to fill a viewport, as opposed to e2e test on full websites, where scrolling and overflow are intentional.

**Comment by lmiller1990** [comment]
I created [this PR](https://github.com/cypress-io/cypress/pull/16543). There are still some edge cases where the screenshots seem weird, as described in the issue. Without your exact test case, I can't say if this will 100% fix your screenshot, but it should based on the testing I did.

If you can provide a repo that shows the problem, that would be really good.

**Comment by pashidlos** [comment]
@lmiller1990 wow, that was fast 

> Are you setting cy.viewport explicitly? What are you setting it to? Also does your component have somthing like width: 1000px or more like width: 100% or width: 100vw?

yes, some of them are using width: 100% or width: 100vw
I use `cypress.json` to set viewport and it's set to   
```
"viewportWidth": 1536, 
"viewportHeight": 960,
```

> I created this PR. There are still some edge cases where the screenshots seem weird, as described in the issue. Without your exact test case, I can't say if this will 100% fix your screenshot, but it should based on the testing I did.

could you advice how to test this locally so I could confirm it?

**Comment by pashidlos** [comment]
@lmiller1990 I get issue reproduce with this test
produced screenshot  get background 
https://github.com/Visual-Regression-Tracker/frontend/blob/cypress-7/src/pages/LoginPage.spec.tsx

now
![1](https://user-images.githubusercontent.com/5182956/118515851-7264dc00-b73e-11eb-8422-72e184984410.png)

before
![2](https://user-images.githubusercontent.com/5182956/118515868-77299000-b73e-11eb-9221-842aeac44b7c.png)

**Comment by lmiller1990** [comment]
Great, thanks! I will use this to test.

I'll post an explanation of the exact problem (hopefully today) and how I fixed it in the PR - it's still a work in progress.

**Comment by lmiller1990** [comment]
Seems to be working better.

![image](https://user-images.githubusercontent.com/19196536/118579577-b05f1000-b7d1-11eb-9846-ed91d614c311.png)
