### ISSUE TITLE
Intermittent: Cy.type() is not typing actual date and missing characters while typing

### ISSUE THREAD

**Issue by NeetuHundal** [cypress-io/cypress#16489]
Description: `cy.type()` is not typing actual date and missing characters while typing. Run below test multiple times if it's not reproducible once.
But when runner is launched, usually it's always reproducible.

### Current behavior
While using `.type('5/15/1950')` we are not able to see new typed value in the input field, sometimes few characters from the typed value is missing.

### Desired behavior
Should be able to see '5/15/1950' in the field.

### Test code to reproduce
```js
it('demo', () => {
  cy.visit('https://www.telerik.com/kendo-react-ui/components/dateinputs/examples/datepicker/default/value/func/?theme=material')
  cy.get(".k-input")
    .click()
    .type('{selectall}')
    .type("5/15/1950");
 });
```

### Versions : "7.3.0"

Impact: Currently all tests related to date picker are failing in pipeline.

Attachments:
![Cypress](https://user-images.githubusercontent.com/83235262/118040937-339ae480-b340-11eb-9481-668801609b74.png)

![CypressDatePicker](https://user-images.githubusercontent.com/83235262/118040983-43b2c400-b340-11eb-94f2-0dc69155ec94.gif)

**Comment by jennifer-shehane** [comment]
@NeetuHundal Is this a new issue or has the type always behaved this way?

I can recreate this, although it doesn't always behave this way. The below example will run the test 15 times, for me it failed once.

```js
describe('Testing', () => {
  Array(15).fill(0).forEach((val, i) => {
    it(`test ${i}`, () => {
      cy.visit('https://www.telerik.com/kendo-react-ui/components/dateinputs/examples/datepicker/default/value/func/?theme=material')
      cy.get('.k-input')
        .click()
        .type('{selectall}')
        .type('5/15/1950')
        .should('have.value', '5/15/1950')
    })
  })
})
```

<img width="903" alt="Screen Shot 2021-05-13 at 9 47 07 AM" src="https://user-images.githubusercontent.com/1271364/118142696-39400b00-b3d0-11eb-9de7-815c223fa10e.png">

I think if you put a `delay` in the typing that this will resolve your issue. I think Cypress is typing faster than a normal person would type, so the UI is reacting at a weird time. 

```js
.type('5/15/1950', { delay: 150 })
```

**Comment by NeetuHundal** [comment]
Thank you for your response.

It's a new issue.It is working fine in previous version 6.14.10 , after we upgraded cypress version tests starts failing. We tried multiple things like wait, delay. Tried to use invoke() as well but no help. Invoke is kind of not same as type so our assertions are failing because of it. one single test will work fine with wait() but after we will run multiple tests (around 24) in pipeline then mostly 3 or 4 fail always, sometimes more than that.

**Comment by bahmutov** [comment]
for me adding a type delay of 20ms seems to always fix the flake
```js
/// <reference types="cypress" />
describe('date picker', () => {
  Cypress._.times(150, (k) => {
    it('types in the date ' + (k+1), () => {
      cy.visit('/kendo-react-ui/components/dateinputs/examples/datepicker/default/value/func/?theme=material')
      cy.get(".k-input")
        .click()
        .type('{selectall}')
        .type("5/15/1950", {delay: 20});
      cy.get(".k-input").should('have.value', '5/15/1950')
    })
  })
})
```

Can you try using the delay + enable test retries on flake?

**Comment by NeetuHundal** [comment]
If you are talking about test retries in the pipeline then we already have that but still tests are failing.

**Comment by bahmutov** [comment]
@NeetuHundal what about adding `{ delay: 50 }` to the type? I think the typing is way too quick because Kendo UI does a lot of stuff on every interaction with that component, like really a lot. Unfortunately, the code is all private, so I don't even know what happens, but it does process pretty much lots of events on every key.

**Comment by NeetuHundal** [comment]
I tried again with { delay: 150 } but no success, still random failure. Build again failed :(

**Comment by NeetuHundal** [comment]
@jennifer-shehane i am entering different dates in each and every test what i have written and you tried with same date. Do you think this different will matter. You got failure only one time and my pipeline is always failing with different tests and always the reason is it's skipping typing characters. Even delay is not helping.

**Comment by bahmutov** [comment]
Can you show or provide a test code where you enter different dates that fail? Because we enter the same date with delay parameter and it seems to be working, no?

**Comment by NeetuHundal** [comment]
By different dates i mean, let's say i have around 24 test cases and in every test i am entering different date value with delay parameter and it's not working with me.

**Comment by bahmutov** [comment]
Can you give us the spec file (just like you showed the code above)? Because we cannot recreate a problem as given anymore , the `delay` parameter works for the case you have provided

**Comment by NeetuHundal** [comment]
Thank you so much everyone for the comments. Issue gets resolved with delay. Actually we are using electron in pipeline which seems to be the problem.
