### ISSUE TITLE
Component tests. plugins/react-scripts. Allow configure of webpack config path

### ISSUE THREAD

**Issue by pashidlos** [cypress-io/cypress#16480]
### What would you like?
make it configurable as in `plugins/load-webpack` via `webpackFilename` 

### Why is this needed?
In my case config file is stored in different place than `react-scripts/config/webpack.config` so plugin doesn't work
before version 7 it was implemented in `load-webpack` plugin by adding cypress folder to transpile via options #14601

<img width="1177" alt="1" src="https://user-images.githubusercontent.com/5182956/117998069-37346880-b34c-11eb-9edd-f54f50d3e654.png">

**Comment by lmiller1990** [comment]
This is actually already supported. The `react-scripts` plugin is designed especially for unejected CRA apps, which has the webpack config in the same place.

If you know where your webpack config is (which you do, you are using a custom one) you can load it manually with both the old `cypress/preprocessor` architecture and the new `webpack-dev-server` architecture. Here are examples:

## cypress/webpack-preprocessor

```js
// cypress/plugins/index.js
const webpackPreprocessor = require('@cypress/webpack-preprocessor')

module.exports = (on, config) => {
  const options = {
    webpackOptions: require('/path/to/your/webpack.config.js',
    watchOptions: {},
  }

on('file:preprocessor', webpackPreprocessor(options))
}
```

## cypress/web-dev-server

See how the react-scripts plugin works [here](https://github.com/cypress-io/cypress/blob/develop/npm/react/plugins/react-scripts/index.js).

```js
// cypress/plugins/index.js

const { startDevServer } = require('@cypress/webpack-dev-server')
const webpackConfig = require('./your/webpack.config.js')

module.exports = (on, config) => {
  on('dev-server:start', async (options) => {
    return startDevServer({ 
      options, 
      webpackConfig
     })
  })

  // IMPORTANT to return the config object
  // with the any changed environment variables
  return config
}
```

I think this should let you accomplish what you'd like to do.

**Comment by pashidlos** [comment]
@lmiller1990 thanks for quick reply 
the problem that I didn't ejected react-scripts but using our internal company fork of it (some small customisation)
so far the only difference that it's located not in the regular `react-scripts` package

I used to use utilise `plugins/load-webpack` and added cypress folders to be transpiled by default but seams it was lost in version 7 (#14602)

what I do right now is a custom script (just a copy of `findReactScriptsWebpackConfig.js` with parametrisation of path)
what about moving `allowModuleSourceInPlace` and `addCypressToWebpackEslintRulesInPlace` to utils so other people could reuse them in case like mine?
or add cypress folders to transpile  in `plugin/load-webpack` as it was before major release?

**Comment by lmiller1990** [comment]
The feature you added for transpiling modules in the `cypress` directory [still exists](https://github.com/cypress-io/cypress/blob/d4f81e8e7839741cc9a2df739f46b993b09b7ea2/npm/react/plugins/react-scripts/findReactScriptsWebpackConfig.js#L100-L103).

Regarding your initial proposal, something like this?

```js
const injectDevServer = require('@cypress/react/plugins/react-scripts')

module.exports = (on, config) => {
  injectDevServer(on, config, { webpackConfigPath: './your/custom/path/webpack.config.js' })

  return config
}
```

I don't like the idea of adding a feature for one specific use case, but this might be useful for post-ejected CRA too. Would this solve your problem?

**Comment by pashidlos** [comment]
@lmiller1990 yes, adding option like `webpackConfigPath` would make it work 
if we could pass it into `findReactScriptsWebpackConfig` that would be awesome

**Comment by lmiller1990** [comment]
I'll see what the team thinks, I'm not sure if this is a good change to make but it's relatively small and simple. @agg23 @elevatebart what do you think? Or do you see another way to accomplish what @pashidlos would like to do?

The other solution would simply be to use something like `patch-package` to modify the plugin for your project only. This might be the most sensible solution, since what you are looking for is a pretty specific modification for an usual use case (CRA fork).

The use case that this might be useful for is post-ejected CRA configs; they could still use the plugin to get around limitations like ModuleNameMapper (cannot transpile outside of `src`), etc.

**Comment by agg23** [comment]
It is possible that `react-scripts` is aliased or only available via a non-standard path. I'm not sure that warrants adding config for this, but I don't see an issue with doing so.

**Comment by lmiller1990** [comment]
@pashidlos would you be interested in making a PR adding this feature?

**Comment by pashidlos** [comment]
@lmiller1990 sure, I could do that

**Comment by lmiller1990** [comment]
Ok, go for it 👍 

You'll want to fork from master and make a PR with `feat` in the title and first commit. That way, it'll get released as soon as it's merged via the semantic release workflow we set up for anything in `npm`.

**Comment by lmiller1990** [comment]
It's out via semantic release.
