### ISSUE TITLE
AWS codepipeline test failing due to environment discrepencies

### ISSUE THREAD

**Issue by karimamarsi** [cypress-io/cypress#16484]
Hi Support Team,

We have a AWS Codepipeline test that has started to fail when attempting to determine the environment which the test is needs to run in. The test itself has been running successfully up until this point and none of the configuration has been changed prior to the failure so not sure if this may be an indication that there may be an issue with Cypress?

Please see the following script that's being executed as part of the tests :
<img width="1162" alt="Script" src="https://user-images.githubusercontent.com/83656751/118016214-0d2f7600-b34d-11eb-9503-c9a5eb1f95d7.png">

Also the output of the failure message:
![Error message](https://user-images.githubusercontent.com/83656751/118015925-b6c23780-b34c-11eb-8f0b-6c6cce99aa19.png)

If you require any further information then please do let me know.

Thanks,
Karim

**Comment by jennifer-shehane** [comment]
It looks like you're getting this error above the failure output. https://on.cypress.io/parallel-group-params-mismatch

>In order to run in parallel mode each machine must send identical environment parameters such as:
>
>Specs
>Operation system name
>Operating system version
>Browser name
>Major browser version

Can you review the info of the parallel run you made to see if there are some of these env params that don't match? 

In the past I've seen issues where the build is setup to run on latest Chrome, for example, and one parallel run ran on Chrome 89 and another ran on Chrome 90. 

Is this error consistent with every run?

**Comment by karimamarsi** [comment]
Hi @jennifer-shehane 

Thanks for all your help and the useful information you provided. We have now managed to resolve the issue.

Kind Regards,

Karim
