### ISSUE TITLE
Enviroment based conditional test cases (proposal)

### ISSUE THREAD

**Issue by mrchovo** [cypress-io/cypress#16496]
### What would you like?
Hello Cypress team! Me and my team have an proposal for environment based test cases. Our vision is to add additional parameter into test case definition/header, similar way how the **retries** are done at the moment. 
```js
it('Random test case', {
    retries: {
        runMode: 2,
        openMode: 0
    },
    condRun: { 
        hasComponentA: true
    }
}, () => { }
```
So basically this test will run only when variable `hasComponentA` is set up as true in my `cypress.env.json` file. It could be explained when test case or suite is wrapped in `if (hasComponentA == true) { it('Test', { }); }`. ( We are also aware of some edge case implementations such as defining enviroment variables in the test case definition next to the condition based on the same variable. )

### Why is this needed?

The example above is also the way we are currently "bending" the system, but we know this is not the clean way to do it. It's the main reason we would like to propose this idea. And the final execution or form of this feature can be totally different from what we are proposing (based on the problematic edge cases mentioned above). The main point is just the idea to **run test conditionally** . 

Also I didn't find any similar ticket as this one so if the majority is not interested in such a feature we totally understand that and we are okay with the way it's done now. Or maybe the solution is already out there and we just didn't find it.

**Comment by bahmutov** [comment]
So the closes we have is this plugin https://github.com/cypress-io/cypress-skip-test and your use case would be a slight addition to it, as you want to use the test config override object.

**Comment by mrchovo** [comment]
Thanks for the response. Yes that plugin can be used the way we need to.

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not currently planned.
