### ISSUE TITLE
EACCES: Permission Denied for /tmp/cypress directory

### ISSUE THREAD

**Issue by rsudarson** [cypress-io/cypress#16497]
```
[OperationalError: EACCES: permission denied, open '/tmp/cypress/98f02aa49d904646c81bf2095a0526cb.lock'

] {
  cause: [Error: EACCES: permission denied, open '/tmp/cypress/98f02aa49d904646c81bf2095a0526cb.lock'
  
  ] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/cypress/98f02aa49d904646c81bf2095a0526cb.lock'
  },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/cypress/98f02aa49d904646c81bf2095a0526cb.lock'
}
Error: EACCES: permission denied, open '/tmp/cypress/98f02aa49d904646c81bf2095a0526cb.lock'
```

This started happening with recent versions I think.  Can you please help to fix this issue.

**Comment by grantspeelman** [comment]
I have the same issue. It happens to me on linux when switching between to users I have on the machine.
I have one user for personal stuff and another user for work stuff.
When I use cypress on the one user, then log out and switch to the other user and try to open cypress, I see this error.

I usually remove the tmp folder using `sudo rm -rf /tmp/cypress` and then it works.
