### ISSUE TITLE
Open should not display dev server methods in success cases

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16499]
### What would you like?
When starting Cypress Component Testing, the dev server used (`webpack` or `vite`) will print the standard success messaging:

![Screen Shot 2021-05-13 at 7 09 01 AM](https://user-images.githubusercontent.com/238679/118137487-199de800-b3ba-11eb-8708-aa46f714a9df.png)

Ideally we would not show these messages, and would instead only show information from the underlying server if something went wrong.

**Comment by elevatebart** [comment]
This should be done using the flag [logLevel](https://vitejs.dev/config/#loglevel). I believe setting it to `warn` should make those messages disappear but leave the warning and compilation error in the log for users to use.

I should be a pretty simple fix.
