### ISSUE TITLE
.type() error is inaccurately stating what can be typed into

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1650]
### Current behavior: 

If you call `.type()` on an element that is not supported for typing, the error displays:

```
CypressError: .type() can only be called on textarea or :text. Your subject is a:
```

### Desired behavior:

This error message is inaccurate and has led to a lot of confusion for users on what `.type()` supports typing into. In actuality, we support typing into:

- HTML `body` and `textarea` elements
- Elements with a defined `tabindex` attribute
- Elements with a defined `contenteditable` attribute
- HTML `input` elements with a defined `type` attribute of one of the following:
  - text
  - password
  - email
  - number
  - date
  - week
  - month
  - time
  - datetime
  - datetime-local
  - search
  - url
  - tel

**The error message should be updated to just say that `.type() has been called on an unsupported element` and link to a doc that lists supported elements.**

- Code for error message: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/error_messages.coffee#L751

**Comment by jennifer-shehane** [comment]
Due to the fact that the supported type elements could *change* per version of Cypress - the error message should *not* link to an outside doc and instead include a list of supported type elements. 

Ideally, this list should be generated from the actual options checked, so they should be sent to the error message and generated from there.

**Comment by bishwenduk029** [comment]
@jennifer-shehane If this is open I can work on this one. I will update accordingly with changes.

**Comment by CarrieZ0320** [comment]
Hi, I am trying to write a test to confirm I can update the name, email those kind of information. Before I update cypress (was version 3.0.2) the feature worked fine. But now with 3.1.0, it shows me the error. 
![image](https://user-images.githubusercontent.com/31717156/44124454-630b268c-a081-11e8-8be2-3ee69283dc0d.png)
But I do want to clear the input to type something else, How should I do this?

Thanks
