### ISSUE TITLE
Cy.visit() gets stuck - .js scripts are not being loaded

### ISSUE THREAD

**Issue by Laurensvaldez** [cypress-io/cypress#16519]
Have a question? Start a new discussion 👉 https://github.com/cypress-io/cypress/discussions
Can anyone help me with this issue. I have been having this issue with testing 3 websites of my company since last Monday (10-May-2021)

### Current behavior
Two .js script get stuck and only work after quickly refreshing the test running. These scripts get bufferd and works perfect after manually retrying or when the retry (2) kicks in.
The given URL is our production website, and this issue only occurs in our testing environment, so reproducing the error will be difficult.
<img width="1104" alt="js scripts" src="https://user-images.githubusercontent.com/34915800/118282057-2a3f8280-b4ce-11eb-95b2-cb8b84e6fb95.png">
Scripts don't run and then a time-out occurs. Visiting the website outside of Cypress works perfect, in the Test and Production environment.

Sometimes I get to see another error: 
We received this error at the network level:

  > Error: ETIMEDOUT
![Error ETIMEDOUT](https://user-images.githubusercontent.com/34915800/118283650-e2215f80-b4cf-11eb-8e47-ca49796a6fb0.png)

Which is weird because if I go outside of Cypress, I can still visit the website.
I am currently using a Macbook Pro for testing.

### Desired behavior
Visit website in testing environment without having to do a retry (manually or with an automated retry)

### Test code to reproduce
Code that I run to check if it visits the website:
```js
/// <reference types="Cypress" />

    describe("Testing connection to website", function ()
    {

        it("Testing connection", () => {
            cy.visit("https://doorzenden.postnl.nl")
            // or cy.visit("https://nabestaanden.postnl.nl")
        })

    })
```

### Versions
Using every browser and Cypress version 7.3.0
Using the latest Cypress version but issue is still present.

**Comment by jennifer-shehane** [comment]
Visiting the urls provided loads for me within Cypress. I'm a little unclear on whether I should be able to reproduce it with just that, is there some other environment config I need to reproduce?

What operating system are you using?
<img width="1387" alt="Screen Shot 2021-05-14 at 10 44 42 AM" src="https://user-images.githubusercontent.com/1271364/118295601-acfe1880-b4a1-11eb-88a5-a3c0be538dbb.png">


<img width="1386" alt="Screen Shot 2021-05-14 at 10 44 01 AM" src="https://user-images.githubusercontent.com/1271364/118295496-8c35c300-b4a1-11eb-8133-ed088785665e.png">

**Comment by Laurensvaldez** [comment]
@jennifer-shehane 
The given URL is the Production environment, and the test are run on the Testing environment. 
This Test_environment site is only reachable for the dev team, but is equally or one version ahead the Production env.

**Comment by Laurensvaldez** [comment]
The first try always fails by the way, with the retry it does succeed in connecting to the website.

**Comment by Laurensvaldez** [comment]
@jennifer-shehane the ticket is still labelled as needs information. Is there anything else I can provide to maybe solve this issue?
I tried testing this on another laptop (Macbook Pro) and same issue occurred. If the first tests fails the second or third always passes. I can't find a solution to this issue.
A colleague of mine cloned the repo and tried it on Windows and the issue didn't seem to occur.

Many thanks in advance.

**Comment by jennifer-shehane** [comment]
@Laurensvaldez I'm not sure there's much more investigation we can do on our end without a way to reproduce it.

**Comment by awacode21** [comment]
Did you ever found out the issue and how to solve it?
