### ISSUE TITLE
Cypress doesn't detect  other supported browser which is installed on system

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress#16512]
### Current behavior

Cypress doesn't detect the installed Firefox browser (or microsoft-edge-dev). Please let me know what else I am missing.

OUTPUT OF FIREFOX INSTALLATION PATH
> 23:19:42  + ls -al /usr/bin/firefox
23:19:42  lrwxrwxrwx 1 root root 25 May  6 10:51 /usr/bin/firefox -> ../lib/firefox/firefox.sh
23:19:42  + /usr/bin/firefox --version
23:19:42  Mozilla Firefox 88.0.1
23:19:42  + firefox --version
23:19:42  Mozilla Firefox 88.0.1
23:19:42  + whereis firefox
23:19:42  firefox: /usr/bin/firefox /usr/lib/firefox /etc/firefox /usr/share/man/man1/firefox.1.gz
23:19:42  + export PATH=/usr/bin/firefox:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
23:19:42  + echo /usr/bin/firefox:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
23:19:42  /usr/bin/firefox:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

DEBUG LAUNCHER & CYPRESS INFO LOG:
> 23:20:42  /tmp/jenkins/workspace/ion-Cypress_runDifferentBrowsers/cypress
23:20:42  + npx cypress info
23:20:43  Displaying Cypress info...
23:20:43  
23:20:43  Detected no known browsers installed
23:20:43  
23:20:43  
23:20:43  Proxy Settings: none detected
23:20:43  Environment Variables:
23:20:43  CYPRESS_BROWSER: firefox
23:20:43  CYPRESS_SUBDOMAIN: development
23:20:43  CYPRESS_STACK_NAME: #####
23:20:43  
23:20:43  Application Data: /tmp/jenkins/workspace/ion-Cypress_runDifferentBrowsers/.config/cypress/cy/development
23:20:43  Browser Profiles: /tmp/jenkins/workspace/ion-Cypress_runDifferentBrowsers/.config/cypress/cy/development/browsers
23:20:43  Binary Caches: /tmp/jenkins/workspace/ion-Cypress_runDifferentBrowsers/.cache/Cypress
23:20:43  
23:20:43  Cypress Version: 7.3.0
23:20:43  System Platform: linux (Debian - 10.5)
23:20:43  System Memory: 16.4 GB free 10.4 GB
23:20:43  + DEBUG=cypress:launcher npx cypress run --browser /usr/bin/firefox
23:20:44  [?25l[06:20:44]  Verifying Cypress can run /tmp/jenkins/workspace/ion-Cypress_runDifferentBrowsers/.cache/Cypress/7.3.0/Cypress [started]
23:20:46  [06:20:45]  Verifying Cypress can run /tmp/jenkins/workspace/ion-Cypress_runDifferentBrowsers/.cache/Cypress/7.3.0/Cypress [completed]
23:20:49  [?25h2021-05-14T06:20:48.810Z cypress:launcher detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ] }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ] }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary' }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox' }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ] }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ] }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/m, binary: [ 'edge', 'microsoft-edge' ] }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge Canary (\S+)/m, binary: 'edge-canary' }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge Beta (\S+)/m, binary: 'edge-beta' }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge Dev (\S+)/m, binary: [ 'edge-dev', 'microsoft-edge-dev' ] } ]
23:20:49  2021-05-14T06:20:48.813Z cypress:launcher checking one browser chrome
23:20:49  2021-05-14T06:20:48.813Z cypress:launcher looking up chrome on linux platform
23:20:49  2021-05-14T06:20:48.813Z cypress:launcher finding version string using command "google-chrome --version"
23:20:49  2021-05-14T06:20:48.821Z cypress:launcher checking one browser chrome
23:20:49  2021-05-14T06:20:48.821Z cypress:launcher looking up chrome on linux platform
23:20:49  2021-05-14T06:20:48.821Z cypress:launcher finding version string using command "chrome --version"
23:20:49  2021-05-14T06:20:48.827Z cypress:launcher checking one browser chrome
23:20:49  2021-05-14T06:20:48.827Z cypress:launcher looking up chrome on linux platform
23:20:49  2021-05-14T06:20:48.827Z cypress:launcher finding version string using command "google-chrome-stable --version"
23:20:49  2021-05-14T06:20:48.836Z cypress:launcher Received error detecting browser binary: "google-chrome" with error: spawn google-chrome ENOENT
23:20:49  2021-05-14T06:20:48.836Z cypress:launcher Received error detecting browser binary: "chrome" with error: spawn chrome ENOENT
23:20:49  2021-05-14T06:20:48.837Z cypress:launcher Received error detecting browser binary: "google-chrome-stable" with error: spawn google-chrome-stable ENOENT
23:20:49  2021-05-14T06:20:48.837Z cypress:launcher browser chrome not installed
23:20:49  2021-05-14T06:20:48.837Z cypress:launcher browser chrome not installed
23:20:49  2021-05-14T06:20:48.837Z cypress:launcher browser chrome not installed
23:20:49  2021-05-14T06:20:48.837Z cypress:launcher checking one browser chromium
23:20:49  2021-05-14T06:20:48.837Z cypress:launcher looking up chromium on linux platform
23:20:49  2021-05-14T06:20:48.837Z cypress:launcher finding version string using command "chromium-browser --version"
23:20:49  2021-05-14T06:20:48.843Z cypress:launcher checking one browser chromium
23:20:49  2021-05-14T06:20:48.843Z cypress:launcher looking up chromium on linux platform
23:20:49  2021-05-14T06:20:48.843Z cypress:launcher finding version string using command "chromium --version"
23:20:49  2021-05-14T06:20:48.853Z cypress:launcher Received error detecting browser binary: "chromium-browser" with error: spawn chromium-browser ENOENT
23:20:49  2021-05-14T06:20:48.854Z cypress:launcher Received error detecting browser binary: "chromium" with error: spawn chromium ENOENT
23:20:49  2021-05-14T06:20:48.854Z cypress:launcher browser chromium not installed
23:20:49  2021-05-14T06:20:48.855Z cypress:launcher browser chromium not installed
23:20:49  2021-05-14T06:20:48.855Z cypress:launcher checking one browser chrome
23:20:49  2021-05-14T06:20:48.855Z cypress:launcher looking up chrome on linux platform
23:20:49  2021-05-14T06:20:48.855Z cypress:launcher finding version string using command "google-chrome-canary --version"
23:20:49  2021-05-14T06:20:48.862Z cypress:launcher Received error detecting browser binary: "google-chrome-canary" with error: spawn google-chrome-canary ENOENT
23:20:49  2021-05-14T06:20:48.863Z cypress:launcher browser chrome not installed
23:20:49  2021-05-14T06:20:48.863Z cypress:launcher checking one browser firefox
23:20:49  2021-05-14T06:20:48.863Z cypress:launcher looking up firefox on linux platform
23:20:49  2021-05-14T06:20:48.863Z cypress:launcher finding version string using command "firefox --version"
23:20:49  2021-05-14T06:20:48.870Z cypress:launcher Received error detecting browser binary: "firefox" with error: spawn firefox ENOENT
23:20:49  2021-05-14T06:20:48.871Z cypress:launcher browser firefox not installed
23:20:49  2021-05-14T06:20:48.871Z cypress:launcher checking one browser firefox
23:20:49  2021-05-14T06:20:48.871Z cypress:launcher looking up firefox on linux platform
23:20:49  2021-05-14T06:20:48.871Z cypress:launcher finding version string using command "firefox-developer-edition --version"
23:20:49  2021-05-14T06:20:48.878Z cypress:launcher checking one browser firefox
23:20:49  2021-05-14T06:20:48.878Z cypress:launcher looking up firefox on linux platform
23:20:49  2021-05-14T06:20:48.878Z cypress:launcher finding version string using command "firefox --version"
23:20:49  2021-05-14T06:20:48.886Z cypress:launcher Received error detecting browser binary: "firefox-developer-edition" with error: spawn firefox-developer-edition ENOENT
23:20:49  2021-05-14T06:20:48.887Z cypress:launcher Received error detecting browser binary: "firefox" with error: spawn firefox ENOENT
23:20:49  2021-05-14T06:20:48.887Z cypress:launcher browser firefox not installed
23:20:49  2021-05-14T06:20:48.887Z cypress:launcher browser firefox not installed
23:20:49  2021-05-14T06:20:48.887Z cypress:launcher checking one browser firefox
23:20:49  2021-05-14T06:20:48.887Z cypress:launcher looking up firefox on linux platform
23:20:49  2021-05-14T06:20:48.888Z cypress:launcher finding version string using command "firefox-nightly --version"
23:20:49  2021-05-14T06:20:48.894Z cypress:launcher checking one browser firefox
23:20:49  2021-05-14T06:20:48.894Z cypress:launcher looking up firefox on linux platform
23:20:49  2021-05-14T06:20:48.894Z cypress:launcher finding version string using command "firefox-trunk --version"
23:20:49  2021-05-14T06:20:48.901Z cypress:launcher Received error detecting browser binary: "firefox-nightly" with error: spawn firefox-nightly ENOENT
23:20:49  2021-05-14T06:20:48.901Z cypress:launcher Received error detecting browser binary: "firefox-trunk" with error: spawn firefox-trunk ENOENT
23:20:49  2021-05-14T06:20:48.901Z cypress:launcher browser firefox not installed
23:20:49  2021-05-14T06:20:48.902Z cypress:launcher browser firefox not installed
23:20:49  2021-05-14T06:20:48.902Z cypress:launcher checking one browser edge
23:20:49  2021-05-14T06:20:48.902Z cypress:launcher looking up edge on linux platform
23:20:49  2021-05-14T06:20:48.902Z cypress:launcher finding version string using command "edge --version"
23:20:49  2021-05-14T06:20:48.907Z cypress:launcher checking one browser edge
23:20:49  2021-05-14T06:20:48.907Z cypress:launcher looking up edge on linux platform
23:20:49  2021-05-14T06:20:48.907Z cypress:launcher finding version string using command "microsoft-edge --version"
23:20:49  2021-05-14T06:20:48.914Z cypress:launcher Received error detecting browser binary: "edge" with error: spawn edge ENOENT
23:20:49  2021-05-14T06:20:48.914Z cypress:launcher Received error detecting browser binary: "microsoft-edge" with error: spawn microsoft-edge ENOENT
23:20:49  2021-05-14T06:20:48.914Z cypress:launcher browser edge not installed
23:20:49  2021-05-14T06:20:48.914Z cypress:launcher browser edge not installed
23:20:49  2021-05-14T06:20:48.914Z cypress:launcher checking one browser edge
23:20:49  2021-05-14T06:20:48.914Z cypress:launcher looking up edge on linux platform
23:20:49  2021-05-14T06:20:48.914Z cypress:launcher finding version string using command "edge-canary --version"
23:20:49  2021-05-14T06:20:48.921Z cypress:launcher Received error detecting browser binary: "edge-canary" with error: spawn edge-canary ENOENT
23:20:49  2021-05-14T06:20:48.921Z cypress:launcher browser edge not installed
23:20:49  2021-05-14T06:20:48.921Z cypress:launcher checking one browser edge
23:20:49  2021-05-14T06:20:48.921Z cypress:launcher looking up edge on linux platform
23:20:49  2021-05-14T06:20:48.921Z cypress:launcher finding version string using command "edge-beta --version"
23:20:49  2021-05-14T06:20:48.927Z cypress:launcher Received error detecting browser binary: "edge-beta" with error: spawn edge-beta ENOENT
23:20:49  2021-05-14T06:20:48.927Z cypress:launcher browser edge not installed
23:20:49  2021-05-14T06:20:48.928Z cypress:launcher checking one browser edge
23:20:49  2021-05-14T06:20:48.928Z cypress:launcher looking up edge on linux platform
23:20:49  2021-05-14T06:20:48.928Z cypress:launcher finding version string using command "edge-dev --version"
23:20:49  2021-05-14T06:20:48.933Z cypress:launcher checking one browser edge
23:20:49  2021-05-14T06:20:48.933Z cypress:launcher looking up edge on linux platform
23:20:49  2021-05-14T06:20:48.933Z cypress:launcher finding version string using command "microsoft-edge-dev --version"
23:20:49  2021-05-14T06:20:48.939Z cypress:launcher Received error detecting browser binary: "edge-dev" with error: spawn edge-dev ENOENT
23:20:49  2021-05-14T06:20:48.940Z cypress:launcher Received error detecting browser binary: "microsoft-edge-dev" with error: spawn microsoft-edge-dev ENOENT
23:20:49  2021-05-14T06:20:48.940Z cypress:launcher browser edge not installed
23:20:49  2021-05-14T06:20:48.940Z cypress:launcher browser edge not installed
23:20:49  2021-05-14T06:20:49.816Z cypress:launcher finding version string using command "/usr/bin/firefox --version"
23:20:49  We could not identify a known browser at the path you provided: `/usr/bin/firefox`
23:20:49  
23:20:49  The output from the command we ran was:
23:20:49  
23:20:49   spawn /usr/bin/firefox ENOENT

### Versions

Cypress: 7.3.0
Unbuntu (sorry I don't know the version. It is on a Docker image)

**Comment by jennifer-shehane** [comment]
Have you tried our provided docker images with browsers already installed? https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

You should probably look at the Dockerfiles we have and how we install Firefox, etc if you want to set up your own docker image.

**Comment by quad5** [comment]
Thank you! Works great when using docker images with browser(s) installed.
