### ISSUE TITLE
 (uncaught exception) undefined: undefined

### ISSUE THREAD

**Issue by titivermeesch** [cypress-io/cypress#16516]
### Current behavior
Here is the test case that is failing:

```js
it('can create a new equipment model', () => {
    cy.clickOnElementByText('Equipment Models')
    cy.clickOnElementByText('Add model')
    cy.pickElementFromSelect('cy|type', equipmentType, '.ant-select-item')
    cy.get('cy|brand').type(modelBrand)
    cy.get('cy|name').type(modelName)
    cy.get('cy|description').type('description')
    cy.get('cy|cost').type(300)
    cy.contains('OK').click()
    // cy.searchTable(modelName)
    // cy.checkElementContainsValue('.ant-table-tbody', modelName)
  })
```

My test was not like this originally but I've tried to narrow it down as much as possible (by using normal cypress commands instead of custom ones for example).

I keep getting this error:
<img width="605" alt="Screenshot 2021-05-14 at 12 21 38" src="https://user-images.githubusercontent.com/12189066/118257455-f1dc7c00-b4ae-11eb-9067-7f6c3a423c20.png">
<img width="1680" alt="Screenshot 2021-05-14 at 12 22 28" src="https://user-images.githubusercontent.com/12189066/118257560-0e78b400-b4af-11eb-990c-5f95fe4333b9.png">
<img width="597" alt="Screenshot 2021-05-14 at 12 24 06" src="https://user-images.githubusercontent.com/12189066/118257746-48e25100-b4af-11eb-8b6d-e48955429e86.png">

Right now it's on the command `pickElementFromSelect` but it also happens on the `cy.get` ones, it seems like a very random behavior. 

I'm not sure where it comes from. There are no other errors in the console during execution and the app just workes fine when I test it manually.

Is there a way to know where this comes from?

### Desired behavior

The commands should just be executed.

### Versions

- Using Chrome 90, but also saw this with Edge 90
- Cypress 7.3.0 (also had it on 7.2.0)
- MacOS 11.2.3 (It also happens in CI on Ubuntu 18.04.5)

### Working versions

My tests seem to run fine on `6.5.0`, but not on the latest version

**Comment by jennifer-shehane** [comment]
Yah, that's not a great error message to help tracking down. Could you provide the custom command code for the `clickOnElementByText` and `pickElementFromSelect` commands?

**Comment by titivermeesch** [comment]
Sure:

clickOnElementBySelect: `text => cy.contains(text).click()`
pickElementFromSelect:
```
(selector, valueToPick, waitForLoading = true) => {
  if (waitForLoading) {
    cy.get('[data-cy=type] > .ant-select-arrow > .anticon > [data-icon=loading]svg').should(
      'not.be.visible'
    )
  }

  cy.get(selector).click().type(valueToPick)
  checkElementExists('.ant-select-item-option')
  clickOnElement('.ant-select-item-option').first()
}
```
checkElementExists: `selector => cy.get(selector).should('exist')`
clickOnElement: `selector => cy.get(selector).click()`

The last ones were little helper functions, but the result is the same by just doing `cy.get....`

**Comment by jennifer-shehane** [comment]
@titivermeesch Yeah, I don't see anything in the custom commands that seems strange. Can you provide a reproducible example? A full test file that we can run and see this throwing the error? Thanks.

**Comment by titivermeesch** [comment]
I recently updated to v8.3.0 and I'm not experiencing this issue anymore. I guess it solved itself.

I'll reopen this issue if I manage to recreate the issue again

**Comment by titivermeesch** [comment]
Having this as well with the latest version, had it as well with v8.3.0. I'm currently stuck at 6.9 because everything else seems to fail the tests instantly

**Comment by nullbytesoftware** [comment]
This works (depricated):

`cy.get('[data-testid="interruption-button-launch"]').then((el) => {
            el.click();
});`

This does not: 

`cy.get('[data-testid="interruption-button-launch"]').click()`

**Comment by ushashir** [comment]
I am having a similar issue with version 11.0.0

**Comment by geritol** [comment]
experiencing the same with version `11.2.0`
I am getting `(uncaught exception) undefined: undefined` errors, on the cypress log, but the error is correctly displayed on the developer console. I think it happens when a promise throws an uncaught exception in the app while executing the test code

**Comment by geritol** [comment]
isolated a potentatial root cause with reproduction in: https://github.com/cypress-io/cypress/issues/24915
