### ISSUE TITLE
Property 'env' does not exist on type 'CypressNpmApi'

### ISSUE THREAD

**Issue by inspiraller** [cypress-io/cypress#16513]
When using typescript implementation with cucumber I am having this error message:

Example test
```
import Cypress from 'cypress';
import { Before, Given, When, Then } from 'cypress-cucumber-preprocessor/steps';

Given(/I login to XYZ/, (url) => {
  const email = Cypress.env('email'); // <-Property 'env' does not exist on type 'CypressNpmApi'
});
```
I have updated my tsconfig and @types to ensure this should be picked up but at the very least the env property itself is undefined.

If I put type assertion as 'any' it resolves typescript error but then I get a different error when I run my tests
const email = (Cypress.env as any)('email'); 
```
npm run cypress
```
> error Cannot read property 'signals' of undefined

**cypress.env.json file**
```
{
  "email": "someemail@somehwere.com",
  "password": "somepassword"
}
```

**cypress/tsconfig,json**
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "noEmit": true,
    "typeRoots": ["cypress", "./@types"]
  },
  "include": [
    "../node_modules/cypress",
    "./**/*.ts"
  ]
}
```

**cypres/@types/index.d.ts**
```
/// <reference types="cypress" />
declare namespace Cypress {
  interface Cypress {
    env(key: 'email'): string;
    env(key: 'password'): string;
    env(key: 'api_key'): string;
  }
}
```
See repo - representing this problem
https://github.com/inspiraller/next-cypress-cucumber-boilerplate

**Comment by sainthkh** [comment]
How about changing `import Cypress from 'cypress';` to `/// <reference types="cypress" />`?

**Comment by inspiraller** [comment]
Its ok thanks. It was resolved by 
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/565#event-4746536875
