### ISSUE TITLE
Cypress does not see a certain part of a webapp deployed in Apache Tomcat

### ISSUE THREAD

**Issue by markuscab** [cypress-io/cypress#16515]
Hi!

**Current behavior:**

This is my first time using Cypress (and an automation tool for testing) and my team is currently looking at the possible cases we could use this for testing. Apparently, I had a bit of an issue on why it cannot redirect me to a certain URL. See code below and screenshot below.

Code:
```js
describe('Sample BPM Test', () => {
    it('Visits the LaunchPad', () => {
      cy.visit('http://bpm-botest1:8080/BOE/BI')
    })
  })
```

Result:
![image](https://user-images.githubusercontent.com/24310670/118255245-988c4100-b4de-11eb-9a4b-2acab5534567.png)

**Desired behavior:**

But if I change may code a bit to point it to another URL, it shows the expected one. See code below and screenshot below.

Code:
```js
describe('Sample BPM Test', () => {
    it('Visits the LaunchPad', () => {
      cy.visit('http://bpm-botest1:8080/BOE/CMC')
    })
  })
```

Result:
![image](https://user-images.githubusercontent.com/24310670/118255554-fb7dd800-b4de-11eb-8ba5-ae9c60dc3972.png)

**Test code to reproduce**

See sample code above.

Any insights on why is this happening? Point me to a closed issue if this has been raised already. Any help and feedback for a newbie like me is also appreciated. Thanks a lot!

**Versions**
Windows 10 Enterprise 1909
Node.js Version 14.15.1
Cypress Version 7.2.0

**Comment by jennifer-shehane** [comment]
This web address doesn't load for me outside of Cypress. Is this the correct url we can see the issue at?

Could you try updating to Cypress 7.3.0. We did some fixes in that version that may resolve your issue. Let us know. Thanks.
