### ISSUE TITLE
MaxListenersExceededWarning warning is still happening

### ISSUE THREAD

**Issue by crfrolik** [cypress-io/cypress#16529]
### Current behavior

According to https://github.com/cypress-io/cypress/issues/1305, this was supposed to be fixed in 7.0.0.

However, I just upgraded to 7.3.0, and saw this warning in my logs:

```
(node:117652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
```

### Desired behavior

No MaxListenersExceededWarning.

### Versions

7.3.0

**Comment by jennifer-shehane** [comment]
@crfrolik Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here? Thanks.

**Comment by aliakhlaghi93** [comment]
I have faced the same. This is the message I receive:

`(11 of 17) (node:26736) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 will-download listeners added to [Session]. Use emitter.setMaxListeners() to increase limit<?xml version="1.0" encoding="UTF-8"?>`

Sometimes it crashed: 

`(node:2960) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
error Command failed with exit code 3221226525.`
