### ISSUE TITLE
Can't get selector in the frist time run test

### ISSUE THREAD

**Issue by elvisvan91** [cypress-io/cypress#16535]
I am trying to input to chekout 3ds token but in the first time run test  it's always fail due to selector is undefined.
I have to put retry and it works fine
![image](https://user-images.githubusercontent.com/29598940/118347557-74784080-b56e-11eb-9740-28253ee821cf.png)

cypress 6.8.0/7.3.0. 
Thank you.

**Comment by WUBingfeng1984** [comment]
001

**Comment by lmiller1990** [comment]
Hi - can you please provide a repository replicating the example? Without more information, it's hard to say what could be wrong.

**Comment by WUBingfeng1984** [comment]
https://github.com/cypress-io/cypress/issues/16535

**Comment by WUBingfeng1984** [comment]
https://github.com/cypress-io/cypress/issues/16535
