### ISSUE TITLE
Plugins API - preprocessing with source file - electron/ chrome run

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#1654]
### Current behavior: 
Not being able to run "cypress run" (default to electron), when preprocessing the source file.
Ending up in "Uncaught ReferenceError: require is not defined"

### Desired behavior:
To be able to run it successfully.

### Steps to reproduce:
```js
# cypress/plugins/index.js
module.exports = (on) => {
  on('file:preprocessor', (file) => Promise.resolve(file.filePath))
  /* "cypress run" (default to electron) throws this error: Uncaught ReferenceError: require is not defined
  cypress run --browser chrome behaves the same
  it works resolving file.outputPath, but it's not good enough for staged containers that doesn't have the outputPath
  at the time */
}
```

<img width="800" alt="screen shot 2018-05-01 at 13 04 45" src="https://user-images.githubusercontent.com/8288389/39472298-4efccab8-4d40-11e8-9c0d-ac85991fdc7e.png">

same thing goes for
```js
const watch = require('@cypress/watch-preprocessor')

module.exports = (on) => {
  on('file:preprocessor', watch())
}
```

### Versions  
cypress@2.1.0, MacOs Sierra 10.12.6

**Comment by chrisbreiding** [comment]
By configuring the preprocessor in either of those ways, you're bypassing the default preprocessing and bundling that Cypress does. That means you can't use any features that aren't supported by the browser you're running the tests in. In this case, it looks like there's a commonjs `require()` in your code or code you import, which isn't supported by any browser. If you use the default preprocessor, it will handle converting any `require()`s into browser-compatible code.

Is there a reason you can't use the default preprocessor?

**Comment by paulpruteanu** [comment]
@chrisbreiding yes. My requirement is to selectively pre-process some of the tests (not all). So instead of browserifying everything just for make it compatible with the browser, isn't any other way?

**Comment by chrisbreiding** [comment]
You need to browserify anything that's not compatible with the browser. There's no getting around that. You can certainly do that selectively, but it will require a little bit of logic. Something like:

```js
const browserify = require('@cypress/browserify-preprocessor')
const watch = require('@cypress/watch-preprocessor')

module.exports = (on) => {
  on('file:preprocessor', (file) => {
    Promise.resolve(file.filePath)
  })
}
```

**Comment by chrisbreiding** [comment]
Sorry, that wasn't complete before I submitted it. 


```js
const browserify = require('@cypress/browserify-preprocessor')
const watch = require('@cypress/watch-preprocessor')

module.exports = (on) => {
  on('file:preprocessor', (file) => {
    if (/* file doesn't need preprocessing */) {
      return watch()(file)
    } else {
      return browserify()(file)
    }
  })
}
```

**Comment by paulpruteanu** [comment]
@chrisbreiding we're rounding in circles. Promise.resolve(file.filePath) won't work on the browser given the reasons you explained. Ideally there should be a way to exit the callback without resolving anything, which would let the normal preprocessor kick through.

**Comment by chrisbreiding** [comment]
Please see my above comment. The one above that had incomplete code.

**Comment by paulpruteanu** [comment]
@chrisbreiding [the watcher](https://github.com/cypress-io/cypress-watch-preprocessor/blob/master/index.js) returns filePath (source file), which gets us back to square one.
```js
    const filePath = file.filePath

    // if shouldWatch is false, this is a one-time run, probably in CI
    // so we don't need to watch
    // since this function can get called multiple times with the same
    // filePath, we return if we already have a cached watcher
    // since we don't want or need to re-initiate a watcher for it
    if (!file.shouldWatch || watchers[filePath]) {
      return filePath
    }
```

**Comment by chrisbreiding** [comment]
How are your files being processed in the case where you don't want them browserified?

**Comment by paulpruteanu** [comment]
Nope. For the ones that does not need processing, they should flow into the default native pre-processor.

**Comment by chrisbreiding** [comment]
> There's no output path given I start from an empty install. No output files have been processed regularly at that time.

What does it mean for those files to be 'processed regularly'?

**Comment by paulpruteanu** [comment]
They get transpiled by the default preprocessor, outside the Plugins API, right?

**Comment by chrisbreiding** [comment]
If that's the case, then why is there no output path? Also, can you explain why some files do not need to be or cannot to be processed?

**Comment by paulpruteanu** [comment]
On the first install, you won't an output directory eg `/Library/Application\ Support/Cypress/cy/production/projects/cypress-example-todomvc-a60a329e6511b7eefa5286529d267046/bundles/cypress/integration/app_spec.js`, therefore you can't do Promise.resolve(file.outputPath), because there's nothing there processed already.
Therefore, resolving it to file.filePath would get me in trouble with the browser as it won't understand it, going for file.outputPath means there's nothing there (it will be, if I don't use `on('file:preprocessor')` at all, as the native cypress bundling would kick in.

The business reason for selectively preprocessing files is the feature toggles concept I'm following. Given a project build with certain toggles in place, I need a way to decide which tests needs to be skipped (replace "it" with "xit"), provided the covered features aren't part of the build (toggled-off).

**Comment by chrisbreiding** [comment]
I see. In that case, is it alright if they don't run instead of being skipped with `xit`? If so, the following should work:

* Create an 'empty' test file with the contents `it('skipped feature')`
* Conditionally Promise.resolve the path to that file for any test file that needs to be skipped

That way you're resolving a file that exists while skipping tests you don't want run.

In `3.0`, which is being released relatively soon, there will be supported for [spec globbing](https://github.com/cypress-io/cypress/issues/681), which may also work for that purpose. Given you name or structure your files in a certain way, you could use a glob to only include the files you want run. You could do that instead of the above solution once `3.0` is out.

**Comment by brian-mann** [comment]
This sounds like an elongated `XY problem` that is finally realized at the end. If you're trying to skip tests conditionally there is a much better way to do that.

You could simply wrap `describe` blocks into a conditional, or handle this in a `beforeEach` by parsing the test title and running `this.skip()` inside of the test.

**Comment by paulpruteanu** [comment]
@chrisbreiding my requirement is to still be able to run other "its" within the file, so this won't work.
@brian-mann I get your point, but this would mix the toggling with testing concern, I'd rather keep it separated. With the current implementation, I only need to amend a mapping.json which links certain test.js files to certain `it`s within, and leave it to a pre-processor to transform the files accordingly.

My only blocker is that it does it for all 140 files, instead of just 2-3 files which are actually subject to being skipped.

**Comment by paulpruteanu** [comment]
`process.setMaxListeners(0);` fixed it for me. Ref on issue [here](https://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected).
