### ISSUE TITLE
chainers.split is not a function with an alias

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#16560]
Cypress v7.3.0 on Mac

Reproduction https://github.com/bahmutov/cypress-grep-example/tree/chainers-split

This is our React TodoMVC app with standard tests. The routing-spec.js has a single allowed test

```js
beforeEach(function () {
    cy.createDefaultTodos().as('todos')
 })

it.only('should allow me to display all items @smoke', function () {
  cy.get('@todos').eq(1).find('.toggle').check()

  cy.get('.filters').contains('Active').click()

  cy.get('.filters').contains('Completed').click()

  cy.get('.filters').contains('All').click()

  cy.get('@todos').should('have.length', 3)
})
```

When this test runs it gives an unusual error, I think it has to do with the alias recompute

<img width="1091" alt="Screen Shot 2021-05-17 at 10 47 34 PM" src="https://user-images.githubusercontent.com/2212006/118582749-e06eca80-b761-11eb-857d-7dcb956940a1.png">

<img width="721" alt="Screen Shot 2021-05-17 at 10 48 14 PM" src="https://user-images.githubusercontent.com/2212006/118582917-2f1c6480-b762-11eb-888a-d40df3c2f816.png">

<img width="572" alt="Screen Shot 2021-05-17 at 10 49 33 PM" src="https://user-images.githubusercontent.com/2212006/118582931-33488200-b762-11eb-8531-8b076bc39314.png">

The custom command creating the todos ends with

```js
cy.get('.todo-list li', { log: false })
  // .should('have.length', 3)
  .should(($listItems) => {
    // check the text in each list item
    expect($listItems[0], 'first item').to.have.text(TODO_ITEM_ONE)
    expect($listItems[1], 'second item').to.have.text(TODO_ITEM_TWO)
    expect($listItems[2], 'third item').to.have.text(TODO_ITEM_THREE)
  })
  .then(function ($listItems) {
    // once we're done inserting each of the todos
    // above we want to return the .todo-list li's
    // to allow for further chaining and then
    // we want to snapshot the state of the DOM
    // and end the command so it goes from that
    // 'spinning blue state' to the 'finished state'
    cmd.set({ $el: $listItems }).snapshot().end()
  })
```

Seems the alias with multiple assertions is running intro trouble

**Comment by bahmutov** [comment]
Workaround: select the elements again after passing the assertions to avoid having assertions in the chain
```js
cy.get('.todo-list li', { log: false })
    .should('have.length', 3)
    .and(($listItems) => {
      // check the text in each list item
      expect($listItems[0], 'first item').to.have.text(TODO_ITEM_ONE)
      expect($listItems[1], 'second item').to.have.text(TODO_ITEM_TWO)
      expect($listItems[2], 'third item').to.have.text(TODO_ITEM_THREE)
    })

  // select the elements again to avoid the alias including
  // the assertions, as they might not be passing
  // when the test code uses the alias
  cy.get('.todo-list li', { log: false })
```

**Comment by JessefSpecialisterren** [comment]
Ran into this one in the wild this week, and made minimum code to reproduce it before I found this issue. Posting the code in case it helps:

```js
it('', () => {
  cy.visit('https://example.cypress.io/')
  cy.get('body').should($el => expect($el).to.be.visible).as('b')
  cy.reload()
  cy.get('@b')
})
```

Replacing the should with `should('be.visible')` makes the error go away, it seems to only be triggered by aliasing a should with a callback. Removing `cy.reload()` also makes the error go away, it seems to require the alias being recomputed
