### ISSUE TITLE
Upgrade Electron to 2.0.0

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1658]
New release of Electron https://electronjs.org/releases#2.0.0

Summary

- Upgraded from Chrome 59.0.3071.115 to 61.0.3163.10.
- Upgraded from Node 8.2.1 to 8.9.3.
- Upgraded from v8 5.9.211.38 to 6.1.534.41.

### Breaking API changes

- Changed menu.popup signature.
- Removed deprecated crashReporter.setExtraParameter
- Removed deprecated webContents.setZoomLevelLimits and webFrame.setZoomLevelLimits.
- Removed deprecated clipboard methods.
- Removed support for boolean parameters for tray.setHighlightMode.

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/issues/2559
