### ISSUE TITLE
Snapshots for individual tests should be easily viewable

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16595]
### Current behavior
When running multiple tests in Component Testing, it is often desirable to view the final state of the DOM for each test that ran. Currently, this requires the user to expand the test in question, then scroll to the bottom in order to hover over the last entry in the CommandLog.

### Desired behavior
The snapshots are quickly viewable from a top level view of the reporter UI, preferably on hover/click of the individual tests.

**Comment by lmiller1990** [comment]
It's done now in Cypress 10.
