### ISSUE TITLE
Using `create react-app` + `create cypress-tests` in vscode results in eslint errors

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#16591]
### Current behavior
When I scaffold cypress component testing in Create react-app projects using `yarn create cypress-tests`, as soon as I try writing tests, VSCode starts complaining about jest related issue in my code

<img width="1792" alt="Screen Shot 2021-05-19 at 11 12 33 AM" src="https://user-images.githubusercontent.com/5592465/118851256-34c79680-b897-11eb-82b0-02f4ae23d00b.png">
<img width="1792" alt="Screen Shot 2021-05-19 at 11 12 40 AM" src="https://user-images.githubusercontent.com/5592465/118851324-3db86800-b897-11eb-81d3-bc3ed73292c3.png">

### Desired behavior
The scaffolding should probably update the eslint config and install the proper plugins.

### Test code to reproduce
```bash
yarn create react-app test
cd test
yarn create cypress-tests
```

then create a `src/App.spec.js` file with 

```js
import React from "react";
import { mount } from "@cypress/react";
import App from "./App";

it("should say Learn React", () => {
  mount(<App />);
  cy.contains("Learn React").then(($link) => {
    expect($link.prop("tagName")).to.equal("a");
  });
});
```

Finally, open the above file in VSCode and use an eslint plugin tod isplay the eslint failures.

### Versions

create-cypress-tests 1.1.1

**Comment by rockindahizzy** [comment]
In case it helps anyone looking at this issue, there is a documented workaround for the time being. https://docs.cypress.io/guides/component-testing/faq#How-do-I-get-TypeScript-to-recognize-Cypress-types-and-not-Jest-types
