### ISSUE TITLE
Faster feedback loop with UI control for test focusing (like `it.only`)

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#16599]
### What would you like?

I feel the need to use `it.only` a lot when I use tests to drive my development. Noticably more-so in component testing, when tests and smaller and re-run must more often.

An example scenario I often run into is I have a `describe` block with around 10 tests, each representing a state of my component. Often I just want to run one test while I develop the component, work on regression, etc.

Currently I need to add `.only` manually, then if I want to change to another test, delete the `only` and move it to another one. It's not that time consuming, but it interrupts the otherwise extremely fluid development experience I get when using the Cypress interactive runner.

Ideally, I'd like to click something in the interactive UI (like a "only" button) and it would just run that test (as if I added `it.only`). Refreshing the runner UI could reset the state - it wouldn't actually update the file on my file system to have `it.only`. It's just temporary, while I'm using the runner.

I made this mock up to show more clearly what I think would be useful. It's just a guide, things like icon/position/how it works are open for criticism. 

![image](https://user-images.githubusercontent.com/19196536/118920300-86e0e880-b979-11eb-8b83-da8c78535092.png)

### Why is this needed?

Faster feedback loop, better interactive workflow.

**Comment by JessicaSachs** [comment]
I’ve been juggling typing and moving around “only” a lot within demos, too. I agree that the UX flow isn’t good in your mocks, but the feature would significantly improve the usability of the product for CT.

**Comment by bahmutov** [comment]
would https://github.com/bahmutov/cypress-grep work

**Comment by lmiller1990** [comment]
Interesting @bahmutov, is there some way we can adapt this into the interactive runner? Or will this only work in run mode (just had a quick look at the README and your YT video on the library, didn't really dig in yet).

Ideally I want to click something (maybe the test name in the command log, for example) and only run that test until I decide otherwise (even clicking "re-run all" would just run that one test - basically like `it.only`, except we'd modify the spec virtually).

**Comment by bahmutov** [comment]
I have not checked with the component test runner, but you can control the grep right from the DevTools https://github.com/bahmutov/cypress-grep#devtools-console

**Comment by agg23** [comment]
From a UI perspective, this is directly related to #16595. We need some way to focus tests or suites to perform operations on them, such as viewing their last snapshot and running only that runnable group.

It may be decided that we don't need explicit focus (a la clicking and highlighting on the title of a test), but instead use implicit focus by buttons drawn next to the title, as @lmiller1990 demonstrated above. Explicit focus fits better with the changes that come along with node testing, and TR2 has concepts of selecting a particular test or a suite for the purposes of viewing their results or rerunning. Alternatively, E2E has little use of focusing particular tests, so this functionality makes more sense to be used in the implicit button form.

**Comment by lmiller1990** [comment]
I did up a more fleshed out proposal [here](https://www.notion.so/cypressdx/Test-Focus-Proposal-11ccc32a97d14026977d570c96a3da95).
