### ISSUE TITLE
@cypress/react/plugins/babel doesn't work in a monorepo

### ISSUE THREAD

**Issue by penx** [cypress-io/cypress#16596]
### Current behavior

If you import @cypress/react/plugins/babel in your cypress code in a package in a monorepo, and run`yarn cypress open-ct`, it doesn't resolve the babel config from the monorepo route and throws an error:

```
ERROR in ./src/index.test.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ./packages/example-application/src/index.test.js: Support for the experimental syntax 'jsx' isn't currently enabled (6:9):
```

This is due to babel not searching upwards for the babel config by default.

### Desired behavior

Babel should be configurable to search upwards in a monorepo to find the babel config.

As explained here:

https://babeljs.io/docs/en/config-files#monorepos

```
        loader: 'babel-loader',
        options: {
          rootMode: "upward",
        },
```

`rootMode: "upward"` needs to be optionally specified in getBabelWebpackConfig.

I will open a PR to allow this to be sent via a config option.

### Test code to reproduce

https://github.com/govuk-react/govuk-react/tree/c7aea92bec8d5d6b0c65a6cb821ddf60cfb11233

### Versions

    "@cypress/react": "^5.7.0",
    "@cypress/webpack-dev-server": "^1.3.0",
    "cypress": "^7.3.0",

**Comment by lmiller1990** [comment]
It's out in cypress/react 5.8.0.
