### ISSUE TITLE
Whoops, there is no test to run

### ISSUE THREAD

**Issue by Muhammadehsan2019** [cypress-io/cypress#16607]
![106201613-b2e81c00-6186-11eb-9e81-441a1f778f9f](https://user-images.githubusercontent.com/57292707/119006456-648da180-b95e-11eb-936c-528dd04d5d17.png)

@bahmutov 
@jennifer-shehane 
I am getting the "Whoops, there is no test to run" again, it happened previously but I was able to find a workaround for it by removing the "parent" target Attribute.
This time when I try to navigate back to the main page it throws this error. There is no target attribute that I can remove. I have tried all the suggested workaround but none worked.
I tried the following workaround as well but didn't work.
 
Cypress.on('window:before:load', (win) => {
  Object.defineProperty(win, 'self', {
    get: () => {
      return window.top
    }
  })
})

**Comment by jennifer-shehane** [comment]
There are a few cases this could happen, mostly if the app under test is navigating the main window - see all opened issues with this label: https://github.com/cypress-io/cypress/labels/topic%3A%20%20%F0%9F%98%B3%20whoops%20there%20is%20no%20test%20to%20run

There's not much we can investigate without seeing the application under test and the test where it is redirecting. If you can comment with a way to reproduce, we can reopen the issue and look at it.
