### ISSUE TITLE
Allow logging output of cy.exec commands which fail due to timeout

### ISSUE THREAD

**Issue by simon-mathewson** [cypress-io/cypress#16606]
### What would you like?
An option to log the `stdout`/`stderr` of a command run by `cy.exec` which failed because it exceeded the Cypress timeout.

### Why is this needed?
We have a seeding command in our project which times out occasionally in our CI runs, never locally. It is difficult to debug this because we have no access to the output of the command. It is not logged and can't be inspected via Cypress Dashboard, which only offers screenshots and videos.

### Previous attempts to make this work
I've tried this, without success:
```javascript
    cy.exec(command, { failOnNonZeroExit: false })
      .then((result) => {
        if (result.code !== 0) {
          cy.log(result.stderr);
          cy.log(result.stdout);
        }
      })
      .then((result) => {
        if (result.code !== 0) throw new Error('Seeding failed.');
      });
```

Cypress dashboard delivers the following screenshot, because `then` never gets called:
<img src="https://user-images.githubusercontent.com/17678744/118984709-0ffa1e80-b97e-11eb-9678-1ed52ba0696f.png" width="400"/>

There is already a `log` option, but this only logs the text of the command itself.

**Comment by jennifer-shehane** [comment]
The `cy.exec` is timing out, so the next command will never be run in Cypress. The `.then()` will never run. I wonder if you could move it into a [`cy.task()`](https://docs.cypress.io/api/commands/task#Argument-should-be-serializable) where you then run the scripts you want and console.log any information there for debugging.

I think you would want this functionality essentially, which doesn't exist: https://github.com/cypress-io/cypress/issues/5094

**Comment by simon-mathewson** [comment]
Thank you. Yes, this would be covered by #5094.
