### ISSUE TITLE
401 when executon the automation test 

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#16617]
cypress log shows 401 when executing the automation test however user is already logged in 
![image](https://user-images.githubusercontent.com/32042806/119120080-26f74a00-ba2c-11eb-8017-80881cccc9a7.png)

```
  "dependencies": {
    "connect-timeout": "*",
    "cypress": "*",
    "cypress-multi-reporters": "*",
    "mocha": "*",
    "mochawesome": "*"
  },
  "devDependencies": {
    "@shelex/cypress-allure-plugin": "*",
    "@testing-library/cypress": "latest",
    "chai": "*",
    "cypress-commands": "*",
    "cypress-localstorage-commands": "*",
    "cypress-ntlm-auth": "^3.2.2",
    "cypress-wait-until": "*",
    "cypress-xpath": "^1.6.2",
    "fs": "0.0.1-security",
    "mocha": "*"
  }
```

**Comment by jennifer-shehane** [comment]
We'll need some more information in order to investigate. Some way to reproduce it, or show some of the test code since we're not familiar with the web application. Is this the first test? Is this the second test after login? How are you logging in?

**Comment by Amrkamel1** [comment]
@jennifer-shehane 
the test is pretty straightforward, I have tried some other automation tests fw it was fine.
![image](https://user-images.githubusercontent.com/32042806/119161857-0ba33380-ba5a-11eb-8b8f-39a3baa609ce.png)
the test is failing in the 2nd it block, for some reason, I think cookies are cleared I don't know why. 

regarding the login, I'm passing regular user name and password then click login, I have added the login method as custom command for sake of resuability  as shown below

/**
 * Customized command for login
 */
Cypress.Commands.add('LoginWith',(userName,password)=>{
    p.login_with(userName,password)
});

**Comment by bahmutov** [comment]
You are using `before` to log in. Thus the cookies are set for the first test. Cypress clears all cookies _before each_ test. Thus at the start of the second test, the cookies are gone. The `before` hook does not run - it already ran once. Thus the second test is "logged out"

- https://docs.cypress.io/api/commands/clearcookies
- read our guide and see recipes for logging in here https://docs.cypress.io/guides/references/best-practices#Organizing-Tests-Logging-In-Controlling-State

**Comment by Amrkamel1** [comment]
@bahmutov 
Thanks for the info, but how then I can use a hook to run once per spec, without clearing cookies.

**Comment by bahmutov** [comment]
Look at the recipes linked from our advice
