### ISSUE TITLE
Tabs are hard to read when inactive

### ISSUE THREAD

**Issue by nothingismagick** [cypress-io/cypress#1661]
### Current behavior: 
![screen shot 2018-05-02 at 18 10 35](https://user-images.githubusercontent.com/35242872/39535481-50d879c8-4e34-11e8-8911-8f9abc2043b0.png)

### Desired behavior:
Perhaps a contrasting color / hue instead of Black text on Dark Gray tab.

### Steps to reproduce:
Open a second tab.

### Versions  
v2.1.0 MacOS Chrome

**Comment by xeger** [comment]
On a related note, the Cypress theme is amusingly almost identical to the default colors of the Mac OS X Dark theme.

These issues aren't enough of an annoyance that I feel like leaping into action to teach myself Chrome plugins - but if I get a bee in my bonnet at some point I'll try to puzzle through both of theme.

**Comment by jennifer-shehane** [comment]
Well, our theme came out before Mac OSX Dark theme, so sounds like Mac copied us. 😝

**Comment by gabbersepp** [comment]
Is this still relevant? If I install the theme of the current `develop` branch on WIn10 Chrome, i dont see black text but a light grey on dark grey:
![image](https://user-images.githubusercontent.com/3234900/67722215-cda67080-f9d8-11e9-828b-81e021e388d4.png)

If yes, I can set the color to white. Would look like this:
![image](https://user-images.githubusercontent.com/3234900/67722332-270e9f80-f9d9-11e9-932d-2a121b14e34e.png)
