### ISSUE TITLE
CORS when redirecting on localhost

### ISSUE THREAD

**Issue by dogrizz** [cypress-io/cypress#16622]
### Current behavior

```
"baseUrl": "http://localhost:4200/some_name" // an angular application
cy.visit('/')
cy.get('button).click() // a button which results in running window.location.href = **url**
```
when **url** is `http://localhost:4200/some_other_name`
  it results in CORS error
when **url** is `http://localhost:4200/#!/some_other_name`
  it redirects to that **url**  

Both urls are outside of scope of the application and call results with 404
This happens only when running with cypress run --spec.
When running from gui it works as intended.

### Desired behavior
It should redirect to provided url in both cases.

### Test code to reproduce
https://github.com/dogrizz/cypress-cors and run 'npm run run-cypress'

### Versions
 I am running this on 7.2.0. Reproduced on 7.3.0

**Comment by jennifer-shehane** [comment]
Please try running on Cypress 7.3.0. We fixed some redirect errors in this release, so it may already be fixed.

**Comment by dogrizz** [comment]
@jennifer-shehane Issue still exists in Cypress 7.3.0
