### ISSUE TITLE
Not able to enable location for chrome  browser in cypress

### ISSUE THREAD

**Issue by poonamgulwane** [cypress-io/cypress#16638]
### Current behavior

1. Added browser permissions plugin , still while running cypress my site shows , "Provide location permission"
https://github.com/kamranayub/cypress-browser-permissions
2. Whereas if I manually open duplicate chrome tab and click  I could see permissions are provided. 
3. Also in chrome setting , permissions are "allowed" for that site

### Desired behavior

1. After adding plugin , location permissions should be provided for the site.

### Test code to reproduce

I added this is cypress/plugins/index.js
```js
const { cypressBrowserPermissionsPlugin } = require('cypress-browser-permissions')
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  config = cypressBrowserPermissionsPlugin(on, config)
  return config
}
```

following lines in cypress.json

```json
  "env": {
    "browserPermissions": {
      "geolocation": "allow",
      "camera": "allow"
    }
  }
```

### Versions

chrome 90
MAC OS
Cypress package version: 4.4.1
Cypress binary version: 4.4.1

**Comment by jennifer-shehane** [comment]
This plugin is not maintained by the Cypress team. I'd suggest opening an issue in the plugin's repo: https://github.com/kamranayub/cypress-browser-permissions
