### ISSUE TITLE
Cannot test that a component throws an error

### ISSUE THREAD

**Issue by JessicaSachs** [cypress-io/cypress#16635]
### Current behavior
Cannot test that a component throws an error. Always fails the test because Cypress has no `.catch` method.

### Desired behavior
Can test a component throws an error

### Test code to reproduce

```js
import { mount } from '@cypress/react'

it('throws', (done) => {
  cy.on('uncaught:exception', (err, runnable) => {
    expect(err.message).to.include('Expected to throw')
    done()
    return false
  })

  const MyComponent = () => {
    const throwError = () => throw new Error('Expected to throw')
    return <div onClick={ throwError }>Click me to throw</div>
  }

  mount(<MyComponent></MyComponent>)
    .get('div')
    .click()
})
```

**Comment by ilovegithub2** [comment]
Any news on this??  Really effecting how we are working on an external component package.

**Comment by rockindahizzy** [comment]
@ilovegithub2 could you provide an example of a component that would require this functionality?

**Comment by lmiller1990** [comment]
This should be working correctly post  https://github.com/cypress-io/cypress/pull/23916 merging.

If not, please open a new issue with a minimal reproduction.
