### ISSUE TITLE
Not able to pass "--fake-flag" for electron browser in cypress 

### ISSUE THREAD

**Issue by poonamgulwane** [cypress-io/cypress#16637]
### Current behavior

1. Don't have any means to provide the "--fake-flag" for electron browser.
2. When cypress test is ran with electron browser , as soon as "Take photograph" tab is opened , blank white screen is shown
3. Whereas if I manually open duplicate electron tab and click on "Take photograph"  button , I could see the green dummy video

### Desired behavior

"--fake-flag" should supported for electron browser. 

### Test code to reproduce

I added this is cypress/plugins/index.js
```
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    launchOptions.args.push('--use-fake-ui-for-media-stream')
    launchOptions.args.push('--use-fake-device-for-media-stream')
    launchOptions.args.push('--use-file-for-fake-video-capture=cypress/fixtures/akiyo_qcif.y4m')
    launchOptions.args.push('--use-file-for-fake-video-capture=cypress/fixtures/sample_640x360.mjpeg')
    return launchOptions
  })
}
```

### Versions

Electron 80
MAC OS
Cypress package version: 4.4.1
Cypress binary version: 4.4.1

Note : 
I have followed following issue , but couldn't find a solution (everything seems to be given for chrome)
https://github.com/cypress-io/cypress/issues/2704
https://github.com/cypress-io/cypress/issues/1519
https://github.com/cypress-io/cypress/issues/9562

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

**Comment by jennifer-shehane** [comment]
Yah I don't think electron exposes a way to pass these flags specifically. You might want to test in a Chrome browser.
