### ISSUE TITLE
Cy.intercept() doesn't catch request to GET png

### ISSUE THREAD

**Issue by pisqa** [cypress-io/cypress#16645]
So I'm having problems calling cy.intercept() on a GET png file. 
I can't expose the real test environment but have reproduced with a call to trello home page.

Apologies in advance if this is due to some error on my part - I did put out a mayday call on the gitter forum but got no reply ;-)

### Current behavior
Call to cy.intercept() fails for a GET png file - get error 'No request ever occurred' on subsequent cy.wait()

### Desired behavior
cy.intercept()/cy.wait() should catch the call to GET .png file

### Test code to reproduce
```
describe('Reproduce GET png issue', () => {

    it('should open trello homepage - stub hero.png', () => {

        cy.intercept(
            'GET', '*/hero.png',
            {
                statusCode: 200,
                fixture: 'testStub.png'
            }).as('testStub');

        cy.visit('https://trello.com');
        cy.wait('@testStub');

        cy.get('h1').contains('Trello helps teams move work forward.').should('be.visible');
    });
});
```

![image](https://user-images.githubusercontent.com/57501449/119333419-1e9c4a80-bc8a-11eb-806d-9a57789a9aa9.png)

![image](https://user-images.githubusercontent.com/57501449/119333639-60c58c00-bc8a-11eb-994f-d341a8bc57ae.png)

### Versions
cypress 7.3.0
chrome 90.0
windows 10 pro

**Comment by bahmutov** [comment]
We have examples of stubbing image requests with a PNG file fixture in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept Can you see how your example is different from our working recipe?

**Comment by pisqa** [comment]
Hi @bahmutov, thanks for the quick reply!

I guess you're referring to image-spec.js / 'stubs a static image using fixture', right?
(fixture is jpeg not png but I guess thats not important)

I guess the big difference is that in the working recipe the stubbed url is in the same domain (http://localhost:7080/images/tiger.jpg), whereas in the trello example the image is fetched from a different domain (https://d2k1ftgv7pobq7.cloudfront.net/meta/p/res/images/spirit/hero/6a3ccd8e5c9a0e8ebea4235d12da6b24/hero.png)

Having said that.... if that is the problem, then its not going to help me much, because in my real test application , the image IS being fetched from the same domain (baseUrl is https://xxx.zzz.io and image is fetched from https://assets.zzz.io)

Apart from that I don't see any major differences:

**working recipe headers:**
GET /images/tiger.jpg HTTP/1.1
Host: localhost:7080
Proxy-Connection: keep-alive
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: image
Referer: http://localhost:7080/pics.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8

**trello example headers:**
GET /meta/p/res/images/spirit/hero/6a3ccd8e5c9a0e8ebea4235d12da6b24/hero.png HTTP/1.1
Host: d2k1ftgv7pobq7.cloudfront.net
Connection: keep-alive
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: image
Referer: https://trello.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8

**Comment by flotwig** [comment]
@pisqa From your screenshot, I can see that the `200` status code for your `.png` is greyed out, indicating that it is being served from cache. `cy.intercept()` cannot intercept a request unless it leaves the browser, which your `.png` request is not doing.

I've opened a PR to the docs repo to clarify how to work around cache issues: https://github.com/cypress-io/cypress-documentation/pull/4042

At this time, it is not planned to work around the cache in `cy.intercept()` itself, so I will close this issue.

**Comment by jalovatt** [comment]
I don't see an immediately obvious way to do this at present, but would it be feasible to offer a conditional variant/option for `cy.wait`? i.e. "`@myImage` may have been requested at this point. If it has, wait for it. If not, just keep going."
