### ISSUE TITLE
Count number of times intercepted route was called

### ISSUE THREAD

**Issue by pstephenwille** [cypress-io/cypress#16655]
### What would you like?

Intercepted routes should keep track of the number of times they were called.  

I'd like to `gy.get` the intercepted route and verify it was called N times.

I could put a custom property on the Req object and increment it in the RouteHandler but that is clunky, and not something the client should have to maintain.  This seems to be the responsibility of the testing framework.

### Why is this needed?

An essential part of testing is confirming your code is only making network requests the expected number of times.  This should be baked in to the testing framework.  If my code makes unnecessary requests, then my code is wrong, and I need to know about it.

SO post: https://stackoverflow.com/questions/67643208/verify-number-of-times-request-was-made

**Comment by jennifer-shehane** [comment]
@pstephenwille You can do this with the `cy.get('@alias.all')` which is undocumented but I believe we'll be documenting it soon. 

```js
cy.intercept('POST', 'my-url').as('postUrl')

// do stuff in your tests/app

// by this time this should have POSTed 4 times
cy.get('@postUrl.all').should('have.length', 4)
```

**Comment by sarahTheTester** [comment]
I had some trouble getting `cy.get('@alias.all')` to wait sufficient time, for example

```
it('counts intercepts', () => {

  cy.intercept({ url: 'page-data/**/*', middleware: true }, req => {
    req.on('response', (res) => {
      res.setDelay(2000)               // artificial delay to force failure
    })
  })

  cy.intercept('page-data/**/*')
    .as('pageData')

  cy.visit('https://www.cypress.io/')

  cy.get('@pageData.all')
    .should('have.length', 18);

})
```

Ideally you'd want a timeout, but `cy.get('@pageData.all', { timeout: 10000 })` does not seem to work.

**Comment by pstephenwille** [comment]
I was using `.all` before but since upgrading all my packages, it no longer seems to work.  Same for `@myreq.0`

**Comment by bahmutov** [comment]
See related advice for counting the number of intercepts https://glebbahmutov.com/blog/cypress-intercept-problems/#get-number-of-times-an-intercept-was-matched

**Comment by pstephenwille** [comment]
While there are clumsy work arounds, the ability to count the number of times a network request was made is fundamental to a testing library.  This should be baked in to Cypress.

**Comment by saranshvaid8** [comment]
We had an issue in our app, where the API returns a 403 and the UI goes into an infinite loop of retries. The ability to count the number of times a route was called would have definitely helped us add more coverage.

**Comment by pstephenwille** [comment]
I don't suppose there's been any movement on this?  What I'm looking for is a built in mechanism to count the number of times a request was made.

**Comment by BlueWinds** [comment]
Counting the calls is easy: ` cy.intercept('page-data/**/*').as('callCount')` but Cypress can't know when your page is settled, so raw assertions on "it should happen X times" are a recipe for flaky tests. https://docs.cypress.io/guides/core-concepts/conditional-testing discusses this in more detail.

There are solutions to this, but it depends on what you want your test to actually be asserting. You could say 'when the body has the 'content-ready' class, we have called the route seven times':
```
cy.get('body').expect('has.class', 'content-ready').then(() => {
  cy.get('@callCount.all').should('have.length', 7)
})
```

Or 'when some other route is called, we should have called the route seven times':
```
cy.intercept('/some/other/route', () => {
  cy.get('@callCount.all').should('have.length', 7)
})
```

Or you could wait for the route to resolve seven times before continuing with the rest of your test:
```
for (let i = 0; i < 7; i++) {
  cy.wait('@callCount')
}
```

But just saying "the route should be called 7 times" doesn't give an expiration date - we don't know when we should stop waiting.

**Comment by AndreVirtimo** [comment]
> @pstephenwille You can do this with the `cy.get('@alias.all')` which is undocumented but I believe we'll be documenting it soon.
> 
> ```js
> cy.intercept('POST', 'my-url').as('postUrl')
> 
> // do stuff in your tests/app
> 
> // by this time this should have POSTed 4 times
> cy.get('@postUrl.all').should('have.length', 4)
> ```

@jennifer-shehane this is working for me. But it is still undocumented. The alias it also marked as error in my IDE (WebStorm). I believe they will change this, when it is an officially documented feature.

**Comment by AaronProdyna** [comment]
".all" Works for me but it is still undocumented here: https://docs.cypress.io/api/commands/intercept
