### ISSUE TITLE
How to set environment JSON file in different folder

### ISSUE THREAD

**Issue by swatantra15081986** [cypress-io/cypress#16650]
We can easily set env variables if we create demo.json, production.json.
But I want to create one folder 'wms' under config and then want to create demo.json, production.json under wms folder .
What the approach without hardcopy folder name 'wms'.

Actually I have created one folder environment and two another folder DTDC and WMS under it.
image.png

I want to import environment variables in integration fileby below command :-

image.png

How can i set the environment.I have created app.js file and ewrite code:
const env1 = process.env.NODE_ENV || 'production' + '.js'

But it is not working.

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
