### ISSUE TITLE
CORS error when using cy.intercept instead of cy.server and cy.route

### ISSUE THREAD

**Issue by brandaogabriel7** [cypress-io/cypress#16657]
### Current behavior
I wrote a test using cypress where I tried stubbing a request to an external REST API. I used the `intercept` method instead of the deprecated `server` and `route` ones but I had a similar issue as described in #9264. Except that not even adding the headers manually resolved my problem.

Here's the error:

![image](https://user-images.githubusercontent.com/29805002/119392113-ad6a9080-bca5-11eb-910a-501b80d0050a.png)

![image](https://user-images.githubusercontent.com/29805002/119392500-34b80400-bca6-11eb-8850-ee20a4f36fe8.png)

Cypress works just fine if I use the deprecated `server` and `route` methods instead.

### Desired behavior
There shouldn't be any CORS error when I added the headers manually. Also, as said in #9264, those were fixed in v6.1.0 but I'm using v7.3.0.

### Test code to reproduce
Here's my code, with and without the headers:

```javascript
// without the headers
cy.intercept(
  '/restaurants',
  'GET',
  (_) => [
    { id: 1, name: pastaPlace },
    { id: 2, name: saladPlace }
  ]
);
    
// with the headers
cy.intercept(
  {
    url:
      '/restaurants',
    method: 'GET'
  },
  {
    headers: {
      'access-control-allow-origin': window.location.origin,
      'Access-Control-Allow-Credentials': 'true'
    },
    body: [
      { id: 1, name: pastaPlace },
      { id: 2, name: saladPlace }
    ]
  }
);
```

### Versions
Cypress: v7.3.0
Browser: I tested it both on Firefox 86.0 and Microsoft Edge 90.0.818.66.
OS: Windows 10 Pro version 20H2.

**Comment by sainthkh** [comment]
Sorry for the late reply. I tested with the code below, but it worked without fail.

```html
<!-- a.html -->
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="/node_modules/jquery/dist/jquery.js"></script>
  </head>
  <body>
    <button id="request">request</button>
    <div id="result"></div>
    <script type="text/javascript">
      $(function(){
        $("button#request").click(function(){
          $.ajax({
            method: "GET",
            url: "https://this-domain-should-not-exist-1234.com/restaurants",
          })
          .then((data) => {
            $('#result').text(data)
          })
        })
      })
    </script>
  </body>
</html>
```

```js
it('t', () => {
  cy.intercept(
    '/restaurants',
    [
      { id: 1, name: 'pasta hut' },
      { id: 2, name: 'pizza kingdom' },
    ],
  ).as('restaurants')

  cy.visit('fixtures/a.html')

  cy.get('#request').click()
  cy.wait('@restaurants')
})
```

Maybe, changing `window.location.origin` to your domain, `https://outside-in-dev-api...`, might work.

**Comment by sainthkh** [comment]
Closing because of the inactivity. If the problem continues to happen, please open a new issue with a reproducible example.
