### ISSUE TITLE
Cypress.Chainable incorectly wrapping any as JQuery<any> in typedef

### ISSUE THREAD

**Issue by MCFreddie777** [cypress-io/cypress#16669]
### Current behavior

When returning `any` from cypress chainable both following methods return types are `Cypress.Chainable<JQuery<any>>` which is incorrect.

```typescript
 foo() {
        return cy.get('body').then((_) => {
            return {} as any;
        });
    }

 foo() {
        return cy.request('/').then(response => {
            return response.body.bar;
        });
    }
```

![image](https://user-images.githubusercontent.com/27869979/119469423-a1cfa600-bd47-11eb-953d-a1759c02799a.png)

### Desired behavior

Tested on Cypress 6.9.1, it correctly return `Cypress.Chainable<any>`.

![image](https://user-images.githubusercontent.com/27869979/119469564-c3c92880-bd47-11eb-94c7-6ad9e2635404.png)

### Versions

Tested on 6.9.1 - working as expected, 7.3.0, 7.4.0 - incorrect types

**Comment by jennifer-shehane** [comment]
Maybe related to https://github.com/cypress-io/cypress/pull/15869 or https://github.com/cypress-io/cypress/pull/15624 We're open to a pull request to fix the types.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I checked the code and found out the it failed because the type of `response.body` is `any`. It's been raised at #9109 and solved at #16743. 

With it solved and you can write code like below:

```ts
interface ResBody {
  x: number
  y: string
}

cy.request<ResBody>({
  url: 'http://goooooogle.com',
  body: {}
}).then((resp) => {
  return resp.body.y
}).then(a => {
  a // => string
})
```

Meanwhile, you can manually cast the type like below:

```ts
cy.request({
  url: 'http://goooooogle.com',
  body: {}
}).then((resp) => {
  return resp.body.y as string
}).then(a => {
  a // => string
})
```

**Comment by MCFreddie777** [comment]
@sainthkh It's totally okay. Yes I know `cy.request` is proposed to be generic, but it is not at the moment.

If you look at the first example, it does not relate to the `cy.request` only, but to the `Chainable` (`.then()`) in general.
It casts implicit and explicit `any` as `jQuery<any>` which is unwanted behaviour. 

![image](https://user-images.githubusercontent.com/27869979/120184567-6a626d00-c211-11eb-8dfa-7f90363c3385.png)

If you explicitly specify return type of fn, it works okay.

![image](https://user-images.githubusercontent.com/27869979/120184567-6a626d00-c211-11eb-8dfa-7f90363c3385.png)

But, with other types - it does not.
Here's example with string without explicit function return typedef, it has correct type.

![image](https://user-images.githubusercontent.com/27869979/120184644-8239f100-c211-11eb-9aae-9a889c4bf677.png)

**Comment by sainthkh** [comment]
At first, I thought it was impossible because it's how `any` works. But I found a way.
