### ISSUE TITLE
Unable to Use Dynamically Generated Tests With Manually Defined Tests

### ISSUE THREAD

**Issue by csalazar1** [cypress-io/cypress#16661]
Overview:

When `it()`'s that were dynamically generated are mixed with manually defined `it()`, only the manually defined `it()` gets recognized. This wasn't an issue in the past

Steps to repro:
Just copy paste and run the following code

```js
const missingParams = ["foo", "bar"];

describe("Suite 1", () => {
  missingParams.forEach((param) => {
    it(`should display ${param}`, () => {
      cy.log(param);
    });
  });

  it("should cy.log", () => {
    cy.log("success");
  });
});
```

When you run the above code, you will see that only the last `it()` was picked up, but not the ones produced by the `array.forEach()` iterations. 

<img width="1373" alt="1" src="https://user-images.githubusercontent.com/32462093/119421866-4eb50f00-bcc5-11eb-9988-36bc9fdcd988.png">

However, when we comment out the manually defined test, the dynamically generated ones are recognized properly

<img width="1350" alt="2" src="https://user-images.githubusercontent.com/32462093/119421913-67252980-bcc5-11eb-97ee-2102ef8fdbfa.png">

Separating these tests into different contexts does not fix the issue

<img width="1380" alt="3" src="https://user-images.githubusercontent.com/32462093/119421944-7c9a5380-bcc5-11eb-8ad4-7b88111cd777.png">

Tested with Cypress
7.4.0 and 3 versions down

**Comment by jennifer-shehane** [comment]
Can you provide the Cypress version that this used to work on?

**Comment by csalazar1** [comment]
@jennifer-shehane The version that we know 100% sure used to work was 6.8.0. This is from the fact that we have a suite in our CI in this exact format, and that was the last time we can see that ran + passed. But weirdly enough when I tried to backtrack to 6.8.0 locally, i couldn't repro. Maybe something has changed with dependencies?

**Comment by jennifer-shehane** [comment]
@csalazar1 I can't recreate this in 7.3.0 or 7.4.0 with the example you provided. Can you provide the full repo to reproduce this? Maybe there's some other support, plugin code of config that's affecting it?

<img width="615" alt="Screen Shot 2021-05-25 at 3 19 21 PM" src="https://user-images.githubusercontent.com/1271364/119563003-9f337780-bd6c-11eb-945c-7ecb838fd9ae.png">

**Comment by csalazar1** [comment]
@jennifer-shehane you were right. This is being caused by a conflicting plugin code. More specifically, it's caused by this one https://www.npmjs.com/package/cypress-select-typescriptonly-tests which is to enable grep selection for typescript files

Feel free to close the issue

**Comment by csalazar1** [comment]
oh you added TS support! that's the only reason we forked the repo. It previously did not support typescript

**Comment by bahmutov** [comment]
It is a different runtime grepping so it should work with any language
