### ISSUE TITLE
Cypress runs the commands multiple times

### ISSUE THREAD

**Issue by andrasferenczi** [cypress-io/cypress#16665]
### Current behavior

Given this code:

```javascript

describe("Testing register", () => {
  it("Login page exists", async () => {
    cy.visit("/app/login");

    cy.contains("sign in to your account", { matchCase: false });
  });

  it("Cannot login with a random account 1", () => {
    cy.visit("/app/login");

    cy.get(`input[name="Email Address"]`).type("whatever@email.com");
    cy.get(`input[name="Password"]`).type("willnotletmein").type("{enter}");

    cy.contains("invalid credentials", { matchCase: false });
  });
});

```

This is what I see:

<img width="852" alt="Screenshot 2021-05-25 at 8 09 25" src="https://user-images.githubusercontent.com/17592224/119447660-873e0280-bd30-11eb-9128-c7fd8b47ff63.png">

The same code had this result in a subsequent run:

<img width="852" alt="Screenshot 2021-05-25 at 8 21 48" src="https://user-images.githubusercontent.com/17592224/119448944-42b36680-bd32-11eb-8ea0-6d8123f38eca.png">

I've found `Cypress` to be completely unreliable when it runs the test commands twice or just a single time.

### Desired behavior

Obviously, execute what the test says.

Run the requested commands in an atomic way: either run all, or don't run any of them. Currently, some `Cypress` commands are executed multiple times and then the entire test fails or timeouts randomly.

I was suspecting that `Webstorm` autosave is the issue here, but it also happened if I ran it in `--headed` mode and the issue came up as well. (These examples are ran with `npx cypress open --env secret=some_key`)

### Test code to reproduce

I'll get back to it later maybe, I have already wasted couple hours on this, it's enough time lost for now.

### Versions

- `"cypress": "^7.4.0",`
- Mac M1, latest
- run locally

**Comment by jennifer-shehane** [comment]
This is very unusual. I've never seen this. 

Can you provide a reproducible example? Is this reproducible if you fork and run our [kitchensink tests](https://github.com/cypress-io/cypress-example-kitchensink)? Or is it isolated to the application under test?

**Comment by andrasferenczi** [comment]
It was a rough ride, it needs to be taken into account that `npm ci` did not work on that project.

Based on this [stackoverflow response](https://stackoverflow.com/a/66044814/4420543) (and the comment it leads to on Github, which is [this one](https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-787912758) ) I managed to install dependencies.

But I've also used `npm i --legacy-peer-deps` so I could install the dependencies.

There are a lot of weird things around here:

1) I dont understand why the `Chromium` install was not needed earlier
2) It seems that `Cypress` does this only on my site.

I think I could use some hints on point 2:

### Code example 1

For the following code:

```Javascript
describe('Testing register', () => {
    it('Login page exists', async () => {
        cy.visit('http://localhost:3000/app/login');

        cy.wait(200)

        cy.contains('sign in to your account', {matchCase: false});
    });

    it('Cannot login with a random account 1', () => {
        cy.visit('http://localhost:3000/app/login');

        cy.wait(200)

        cy.get(`input[name='Email Address']`).type('whatever@email.com');
        cy.get(`input[name='Password']`).type('willnotletmein').type('{enter}');

        cy.contains('invalid credentials', {matchCase: false});
    });
});
```

I got this output:

<img width="691" alt="Screenshot 2021-05-25 at 21 18 32" src="https://user-images.githubusercontent.com/17592224/119555989-c3a84780-bd9e-11eb-8304-7f4cb99c4ff8.png">

Just wondering if it helps identifying the issue, what is happening under the hood.

### Idea

I could really use a couple hints or just random thoughts where I could start debugging this.

There is clearly a mismatch between `Cypress` and the site I am testing. 

...

I think I'll just leave this here since I've typed it out ...

**Comment by andrasferenczi** [comment]
# GODDAMN `async`

(logs inside the `chromium` showed a warning ...)
