### ISSUE TITLE
Chrome flag settings ignored when using Command-Line Test Runner

### ISSUE THREAD

**Issue by jerrykobes** [cypress-io/cypress#16677]
### Current behavior
When the "**SameSite by default cookies**" flag is set within a Chrome browser instance opened from the _interactive test runner_ it will continue to persist for the _interactive runner_. However, when using the _command-line runner_ this flag reverts back to the "**default**" setting. 

This behavior breaks any tests in the _command-line runner_ that rely upon "**SameSite by default cookies**" being "**Disabled**" since there is currently no way to disable it for such a run. Attempting to disable it within a browser instance of the _command-line runner_ does not persist. After Chrome 90 the "**Default**" for "**SameSite by default cookies**" is "**Enabled**".

### Desired behavior
Any Chrome flag (chrome://flags) set within a Chrome browser instance opened from the _interactive test runner_ should continue to persist when using the _command-line runner_.

##### cypress interactive runner
1. open the interactive test runner: `yarn run cypress open`
2. select `Chrome 90` as the browser
2. run a spec file
3. disable the chrome "SameSite by default cookies" flag by doing the following:
    1. open a new tab
    2. enter `chrome://flags/#same-site-by-default-cookies` into the url
    3. set `SameSite by default cookies` to `Disabled`
4. follow steps 1 through 4 and observe the flag persists
##### cypress command-line runner
1. run the spec through the command-line test runner with the `--no-exit` option: 
    1. `yarn run cypress run --spec "[spec file]" --browser chrome --no-exit`
2. check whether the chrome "SameSite by default cookies" flag setting persists by doing the following:
    1. open a new tab
    2. enter `chrome://flags/#same-site-by-default-cookies` into the url
    3. observe `SameSite by default cookies` is `Default` rather than `Enabled`
3. repeat steps 1 and 2, and then disable the flag
4. repeat steps 1 and 2 again, observe that the flag reverts back to `Default`

### Versions
* Cypress 7.4.0
* Chrome 90.0.4430.212
* MacOS Mojave 10.14.6

**Comment by jennifer-shehane** [comment]
Have you tried passing the command line flag through the plugins to enable the feature for each run? 

```js
module.exports = (on, config) => {
    on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chromium' && browser.name !== 'electron') {
            launchOptions.args.push('--enable-features=SameSiteByDefaultCookies');
        }

        return launchOptions;
    });
};
```

**Comment by jerrykobes** [comment]
@jennifer-shehane we added the extra launch option and it works now. Thanks
