### ISSUE TITLE
Periodically new localStorage value is not set between tests

### ISSUE THREAD

**Issue by coolswood** [cypress-io/cypress#16680]
### Current behavior

I have several tests that require different localStorage values. I make window.localStorage.setItem with a different value in each test in the file. But periodically, window.localStorage.setItem fails and the old values remain.

### Desired behavior

If I do window.localStorage.setItem inside the test, the changes should appear in the browser

### Test code to reproduce

`const challengeStore = {
      step: 15,
      lastDate: dayjs().dayOfYear(),
      startScoreBdi: null,
      startScoreHDU: null,
    };`

   ` window.localStorage.setItem(
      'user',
      JSON.stringify({ challenge: challengeStore })
    );`

### Versions

`"cypress": "^7.4.0"`
mac, docker linux

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I tested the case with the code below, but it passed without fail. 

```js
for (let i = 0; i < 100; i++) {
  it(`${i}`, () => {
    cy.window((win) => {
      win.localstorage.setItem('key', JSON.stringify({ val: i }))
      const obj = win.localstorage.getItem('key')

      expect(JSON.parse(obj)).to.deep.eq({ val: i })
    })
  })
}
```

Can you give me the more detailed example that fails? As we all know, the debugging starts with reproducing it on the developer's local machine.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
