### ISSUE TITLE
Intercept matching wrong url when array are used in query

### ISSUE THREAD

**Issue by cifren** [cypress-io/cypress#16686]
### Current behavior

When trying to intercept this URL `http://localhost/api/line?id=5&store[0]=5&store[1]=6` the command 

```js
cy.intercept(
        {
          url: '/api/line*',
          method: 'GET',
          query: {
            id: '5',
            'store[0]': '5',
            'store[1]': '9'
          },
        },
        {fixture: 'lines.json'}
      ).as('request')
```
is matching

### Desired behavior
That intercept should not match at all

### Test code to reproduce

See above

### Versions

Cypress:    7.4.0
Browser:    Chrome 90 (headless)

**Comment by jennifer-shehane** [comment]
@cifren It looks like you didn't indicate the 'wrong' url that it is matching on. Can you provide the wrong url that this is matching on that you don't think it should match? Thanks.

**Comment by cifren** [comment]
It is the wrong URL http://localhost/api/line?id=5&store[0]=5&store[1]=6

it should match http://localhost/api/line?id=5&store[0]=5&store[1]=9 but not http://localhost/api/line?id=5&store[0]=5&store[1]=6

It match both url

**Comment by IvanTC95** [comment]
Happening in version 8.0.0

**Comment by cifren** [comment]
And I noted as well an issue with that, I usually run it with GUI and if I don't close and open the test instance, the intercept method keeps old version of my code. I need to instanciate a new test window in order to make my code understood by the test.

For example, I will write :
```
beforeEach(() => {
    // this url doesn't exist on my running test app
    cy.intercept('GET', '/api/translations/wrong_url.json', { fixture: 'en.json' }).as('all');
  });
```
I run my test, It won't intercept anything, because it does not exist, it is normal, I wrote something wrong in purpose.

I will correct it after seeing my mistake : 
```
beforeEach(() => {
    // this url exist
    cy.intercept('GET', '/api/translations/corrected_url.json', { fixture: 'en.json' }).as('all');
  });
```
It won't work if I don't close and open the window, the hot-reload does not refresh intercept method or something like that.

So I suppose my bug might coming from that problem, because now It is working with all method.

**Comment by cifren** [comment]
And I noted as well an issue with that, I usually run it with GUI and if I don't close and open the test instance, the intercept method keeps old version of my code. I need to instanciate a new test window in order to make my code understood by the test.

For example, I will write :
```
beforeEach(() => {
    // this url doesn't exist on my running test app
    cy.intercept('GET', '/api/translations/wrong_url.json', { fixture: 'en.json' }).as('all');
  });
```
I run my test, It won't intercept anything, because it does not exist, it is normal, I wrote something wrong in purpose.

I will correct it after seeing my mistake : 
```
beforeEach(() => {
    // this url exist
    cy.intercept('GET', '/api/translations/corrected_url.json', { fixture: 'en.json' }).as('all');
  });
```
It won't work if I don't close and open the window, the hot-reload does not refresh intercept method or something like that.
