### ISSUE TITLE
Chrome update warning blocks hover tests

### ISSUE THREAD

**Issue by jamime** [cypress-io/cypress#16693]
### Current behavior

We use the official docker image https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node14.16.0-chrome89-ff86 and our builds that checked hover suddenly stopped working.

We build a lot of images and found that the issue lied in few specific chrome versions.

I connected using X11 and found that chrome sometimes displays an update message which means the `.trigger('mouseover')` does not work correctly.

![image](https://user-images.githubusercontent.com/2328042/119693774-826a7300-be44-11eb-92d5-3a3eee4a142d.png)

```
Can't update Chrome
Chrome couldn't update to the latest version, so you're missing out on new features and security fixes.
```

### Desired behavior
Chrome auto update should be disabled or dismissed.

### Test code to reproduce

~I'll create one and update the ticket.~

No longer required.

### Versions

| Image | Chrome | Base | Result |
|-------|--------|------|--------|
|cypress/browsers:node12.18.3-chrome87-ff82|87.0.4280.66|12.18.3 |:white_check_mark:|
|custom|87.0.4280.66|14.16.0|:white_check_mark:|
|custom|87.0.4280.88|14.16.0|:white_check_mark:|
|custom|88.0.4324.96|14.16.0|:x:|
|custom|88.0.4324.146|14.16.0|:x:|
|custom|88.0.4324.150|14.16.0|:x:|
|custom|88.0.4324.182|14.16.0|:x:|
|cypress/browsers:node14.16.0-chrome89-ff86|89.0.4389.72  |14.16.0|:x:|
|custom|89.0.4389.82|14.16.0|:white_check_mark:|
|custom|89.0.4389.90|14.16.0|:white_check_mark:|
|custom|89.0.4389.114|14.16.0|:white_check_mark:|
|custom|89.0.4389.128|14.16.0|:white_check_mark:|
|custom|90.0.4430.72|14.16.0|:white_check_mark:|
|custom|90.0.4430.85|14.16.0|:white_check_mark:|
|custom|90.0.4430.93|14.16.0|:white_check_mark:|
|cypress/browsers:node14.16.0-chrome90-ff88|90.0.4430.212|14.16.0|:white_check_mark:|

`cypress@7.4.0`

**Comment by jennifer-shehane** [comment]
We pass the `--disable-component-update` flag to Chrome by default, so this popup shouldn't display. Are you overwriting any of the flags passed on launch to Chrome?

Some threads online seem to indicate maybe the `--disable-component-update` flag doesn't always work and suggest passing the `--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'` flag to not update Chrome til 2099. 

If you haven't changed the default flags originally, can you try passing this flag like shown below to see if it gets rid of the popup?

```js
// cypress/plugins/index.js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      // auto open devtools
      launchOptions.args.push('--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'')
    }

    // whatever you return here becomes the launchOptions
    return launchOptions
  })
}
```

**Comment by jamime** [comment]
I'll give that a go now, I used this to simulate it in the newer versions of chrome it looks like they removed the popup in favour of the menu button. 

```js
// cypress/plugins/index.js
on("before:browser:launch", (browser = {}, launchOptions) => {
  launchOptions.args.push("--simulate-critical-update");
  return launchOptions;
});
```

`Chrome 90.0.4430.212`

![image](https://user-images.githubusercontent.com/2328042/119699475-1f7bda80-be4a-11eb-8b60-f605e8765ccd.png)

**Comment by jamime** [comment]
Great, that worked correctly with the `cypress/browsers:node14.16.0-chrome89-ff86` image.

![image](https://user-images.githubusercontent.com/2328042/119700731-7df58880-be4b-11eb-8a2c-7350a17eca2a.png)

Will this be added as a default option in a future version of cypress?

**Comment by jennifer-shehane** [comment]
Yah I can open a PR for this.
