### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined" at Object.appendErrMsg

### ISSUE THREAD

**Issue by James-E-Adams** [cypress-io/cypress#1669]
### Current behavior: 
This is a weird issue that is isolated to a single machine.

If I try run a test file with more than one or two tests, I get the following: 
<img width="645" alt="screen shot 2018-05-03 at 10 59 12 am" src="https://user-images.githubusercontent.com/9067274/39556082-11b6179a-4ec1-11e8-81d9-524004cdcd00.png">

The stack trace:

```
TypeError: Cannot read property 'replace' of undefined

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'bulk actions'
    at Object.appendErrMsg (http://localhost:3000/__cypress/runner/cypress_runner.js:66723:23)
    at Runner.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:65768:20)
    at Runner.EventEmitter.emit (http://localhost:3000/__cypress/runner/cypress_runner.js:28665:13)
    at Runner.fail (http://localhost:3000/__cypress/runner/cypress_runner.js:65066:17)
    at Runner.failHook (http://localhost:3000/__cypress/runner/cypress_runner.js:33083:8)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:33128:16
    at http://localhost:3000/__cypress/runner/cypress_runner.js:65918:11
From previous event:
    at onNext (http://localhost:3000/__cypress/runner/cypress_runner.js:65917:57)
    at done (http://localhost:3000/__cypress/runner/cypress_runner.js:32741:5)
    at Hook.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:32776:5)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:65936:28
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:65935:20)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:61399:51)
    at Hook.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:65075:20)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:33119:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:33141:5
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:28382:27)
```

The test spec file like:

``` js
describe('tests', () => {
  beforeEach(() => {
    cy.authenticatedVisit(
      'some_url'
    )
  })
  it('draws a box', () => {})
  it('potato', () => {})
  it('draws a circle', () => {})
  it('draws nothing', () => {})
})

```
and the `authenticatedVisit` command is:

```js
Cypress.Commands.add('authenticatedVisit', url => {
  cy.visit(url, {
    onBeforeLoad() {
      window.localStorage.setItem(
        'authRefreshToken',
        userJames.authRefreshToken
      )
      window.localStorage.setItem('authAccessToken', null) //it needs this field to have an entry
    },
  })
})
```

It works perfectly fine on other machines with the exact same set up.

It works fine running a single test at a time - but I'm wondering if anyone else has experienced this before?

Happy to provide any extra info if I can!

### Versions  

Both cypress 2.1.0 and the previous version. Mac OS 10.13.4, chrome 66.0.3359.139

**Comment by jennifer-shehane** [comment]
Can you try adding this to your suite and seeing what the `err` is here?

```js
Cypress.on('fail', (err, runnable) => {
  debugger
})
```

**Comment by Bkucera** [comment]
@James-E-Adams if you want to yield the window of the app, you should use `cy.window()` like this:
```js
cy.visit('http://localhost:8080/app')
cy.window().then((win) => {
  // win is the remote window
  // of the page at: http://localhost:8080/app
})
```

**Comment by James-E-Adams** [comment]
Hi @jennifer-shehane!
Sorry for the late response. I couldn't work out where that event listener should go?
I tried it in the spec file at the top, in the describe, in the beforeEach and inside a test.
I also tried it in the console, as well as using cy instead of Cypress.

**Comment by James-E-Adams** [comment]
@Bkucera I'm not sure if you noticed, but I'm using `onBeforeLoad` as an option for `cy.visit()`. If I try to use your suggestion of `cy.window()` to yield the window inside the `onBeforeLoad`, I get the attached error, which makes sense, I guess.

<img width="629" alt="screen shot 2018-05-15 at 3 58 32 pm" src="https://user-images.githubusercontent.com/9067274/40039225-d84b1fea-5858-11e8-80be-9fe68c6dee1b.png">

**Comment by xiankai** [comment]
@James-E-Adams I believe you are supposed to put the event listener outside of the describe.

```
Cypress.on('fail', (err, runnable) => {
  debugger
})
  
describe('tests', () => {
  beforeEach(() => {
    cy.authenticatedVisit(
  	'some_url'
    )
  })
  it('draws a box', () => {})
  it('potato', () => {})
  it('draws a circle', () => {})
  it('draws nothing', () => {})
})
```

Also Bkucera's suggestion's was to call `cy.window()` after `cy.visit()`, not inside `onBeforeLoad()`. Which means that your `authenticatedVisit` command would look like this:

```
Cypress.Commands.add('authenticatedVisit', url => {
  cy.visit(url);
  cy.window().then(window => {
  	window.localStorage.setItem(
  	  'authRefreshToken',
  	  userJames.authRefreshToken
  	);
  	window.localStorage.setItem('authAccessToken', null) //it needs this field to have an entry
  });
});
```

I'm not sure if that would solve your problem but I hope that gives you a working alternative.

**Comment by echurilov** [comment]
I'm getting a similar error in 3.1.5 when trying to `cy.setCookie` in a before: `TypeError: Cannot read property 'replace' of undefined"` at `Object.appendErrMsg`

Inserting that on-fail debugger as you showed yields `err = Error` and `runnable.trace.message = "Error: done() called multiple times"` at Hook.Runnable

**Comment by Bkucera** [comment]
@James-E-Adams in regards to the original issue, I believe it's possible for the global `window` reference to get lost. Instead, try this:
```js
cy.visit(url, {
    onBeforeLoad(win) {
      win.localStorage.setItem(
        'authRefreshToken',
        userJames.authRefreshToken
      )
      win.localStorage.setItem('authAccessToken', null)
    },
```

**Comment by jennifer-shehane** [comment]
This issue should be fixed as part of this refactor: https://github.com/cypress-io/cypress/issues/3762

**Comment by eddif** [comment]
Similar to @echurilov I'm unable to call cy.setCookie() within a beforeEach:

![image](https://user-images.githubusercontent.com/13355055/59241991-b6e4b600-8bbe-11e9-985a-e43f51e06953.png)

Within the Cypress window I see the error TypeError: Cannot read property 'replace' of undefined - 

![image](https://user-images.githubusercontent.com/13355055/59242497-9f0e3180-8bc0-11e9-9bfd-2df64c5cda37.png)

**Comment by eddif** [comment]
Resolved my issue by trimming the response. Whitespace was being included in the body.
