### ISSUE TITLE
with cypress execution , getting code 403 and after that page not loaded and error message "you are on an broken path" in display.

### ISSUE THREAD

**Issue by kaviti** [cypress-io/cypress#16701]
@bahmutov : Please look in to this as this is blocker to me.

### Current behavior
with cypress execution , getting code 403 and after that page not loaded and error message "you are on an broken path" in display.
This is working fine manually .Also getting 200  when I am doing things manually.

### Desired behavior
code 403 should not be in display and with out error page should get loaded as it is preforming in manual execution

### Test code to reproduce
Using cypress After step 2 in below code ,  that is clicking of "Continue in browser" btn : I am getting message on webpage "You are on a broken path."
also checked Terminal log and there I am seeing 403 GET /oauth2/login 403 262.180 ms

Below is the code -
```js
it('Launch application', function () {
   cy.visit("https://gm5qac.globalmeet.com/Web/AnilSingh")
   cy.get('#continueInBrowserBtn',{ timeout: 60000 }).should('be.visible').click()
    cy.get('#cpp-agree-btn > .pgi-btn-layout',{ timeout: 60000 }).should('be.visible').click()
  })
```

### Versions

6.5.0
![IssueSnipplet](https://user-images.githubusercontent.com/12135465/119823616-adbb9380-bf12-11eb-928d-6495aeb7de6c.PNG)
![TerminalLog](https://user-images.githubusercontent.com/12135465/119824005-10149400-bf13-11eb-8e40-4514407a6cf5.PNG)`

**Comment by bahmutov** [comment]
Seems it is trying to travel multiple domains to log in? See our notes about logging in: https://docs.cypress.io/examples/examples/recipes#Logging-In
