### ISSUE TITLE
Cypress can't open google sheet

### ISSUE THREAD

**Issue by hieuTranEnouvo** [cypress-io/cypress#16702]
1. Enter docs.google.com
2. Login google by oauth2.0 ==> DONE
3. Visit link (https://docs.google.com/.../1UUPYKA.../edit...)

==> The cypress can't open google sheet.

Cypres: 7.4.0
Browser: FF, Chrome, Electron
Image:
![187566787_4100231130035651_1110859421099449559_n](https://user-images.githubusercontent.com/48512781/119852746-c5f2d900-bf39-11eb-9e25-8c72b88cf777.jpeg)

**Comment by hieutrandn9889** [comment]
I still get this bug
