### ISSUE TITLE
cypress component testing[Urgent help]

### ISSUE THREAD

**Issue by Vishwaas** [cypress-io/cypress#16705]
### Current behavior
I am trying to setup my react project for component testing, everytime I do so I keep getting the below error:
![image](https://user-images.githubusercontent.com/6441192/119868820-c6a95200-bedc-11eb-97dc-225e0572618d.png)

Even if I install babel-plugin-transform-dynamic--import i get some other error, I seem to have followed all the instructions present in https://docs.cypress.io/guides/component-testing/introduction. I even tried a custom webpack but that again has other issues.
Can i also get a link to an example having component testing with cypress?The current blog link seems to be pointing to a older cypres component testing version

### Download method
 
npm  install --save-dev cypress 
npm install --save-dev @cypress/react @cypress/webpack-dev-server webpack-dev-server
npm version: 6.14.8
node version: 12.20.0

- [x] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux
- [ ] Mac
- [X] Windows

### Other

- [X] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI 
FYI: THe regular end to end testing with cypress is working fine.

**Comment by elevatebart** [comment]
Hello @Vishwaas 

This issue has completely escaped my attention.

Here is a few examples of installations with a recent-ish version of cypress

https://github.com/cypress-io/cypress-component-examples

I hope this helps.
If you still struggle, please create a repo where we can reproduce. 
This will make helping you so much easier.

Thank you in advance and sorry for the delay

**Comment by Vishwaas** [comment]
Thank you all, we can close this.
