### ISSUE TITLE
Dates in "route" fixture objects are transformed into strings

### ISSUE THREAD

**Issue by OlivierChirouze** [cypress-io/cypress#16704]
### Current behavior

Fixtures with Date properties return string representation of dates.
(I use a fixture to stub an API for which we have a generated TS client that returns objects with Dates)

### Desired behavior

Dates should be preserved (like numbers are preserved and not translated into strings)
Don't you think this is legit?
Thanks

### Test code to reproduce

```
cy.route('whatever', {
    updated: new Date(1538400822 * 1000)
})
```

Will return:

`{updated: "2018-10-01T13:33:42.000Z"}`

### Versions

7.2.0

**Comment by jennifer-shehane** [comment]
`cy.route()` is deprecated, so even if this is a bug we're not doing any new work on deprecated commands. Have you tried this using `cy.intercept()`? Is it the same issue?

**Comment by OlivierChirouze** [comment]
Thanks for your reply Jenniffer,

I just tried with `intercept`, with a `StaticResponse` or with a callback calling `req.reply()` in the body, they all behave the same (which, in a way, is reassuring).

I guess the issue is in this comment:
>   // this object will automatically be JSON.stringified and sent as the response
...that can be found in https://docs.cypress.io/api/commands/intercept#Providing-a-stub-response-with-req-reply

Do you think stringify is justified? A more elaborate serialization could maybe be used?

Thanks

**Comment by OlivierChirouze** [comment]
(For the record)
An ugly workaround I just used is to wrap the "date" property that I received in a `new Date()` object.
This way, when running Cypress the property is converted to a Date, and when running "on production", the property is simply "copied" to another Date object.
In the example above it would look like
```
useResponse(response: {updated: Date}) {
  // response.updated should be a date but is a string when running Cypress
  const updated = new Date(response.updated);
}
```
Not nice to change the production code for tests, but it works for the moment.

**Comment by OlivierChirouze** [comment]
Further investigation on my side: the endpoint I was trying to mock with Cypress is using a **generated** Typescript client that _pretends_ it is receiving `Date` properties while in fact it is, indeed, receiving stringified dates.

Of course, the JSON message has to be stringified for the communication to happen, I should have thought about it.

So there is nothing wrong on Cypress side, sorry for the noise.

Thanks for your support
