### ISSUE TITLE
Cypress 7.4.0 - Cannot find module 'term-size'

### ISSUE THREAD

**Issue by dombo82** [cypress-io/cypress#16707]
Hi Cypress!

When I upgrade to version 7.4.0 in my project on a Win10 machine, starting Cypress throws an uncaught exception in main process "Cannot find module 'term-size'".

I tried to resolve this by completely deleting Cypress (inclusive roaming cache) and node.js without success.

Only possible healing: revert to 7.3.0!

![cypress-740-term-size-error](https://user-images.githubusercontent.com/67309974/119874129-95a13f80-bf25-11eb-981c-273411bfcf3a.png)
![cypress-730-NO-term-size-error](https://user-images.githubusercontent.com/67309974/119874131-9639d600-bf25-11eb-8293-9fd2afb3cee4.png)

**Comment by jennifer-shehane** [comment]
@dombo82 Can you try clearing your node modules and installing fresh? We haven't seen this issue reported by anyone else.

**Comment by dombo82** [comment]
I did so by clearing all local and global node_modules and re-installed the latest LTS node version, as I use node.js for Cypress exclusively.

**Comment by dombo82** [comment]
I did so by clearing all local and global node_modules and re-installed the latest LTS node version, as I use node.js for Cypress exclusively

**Comment by jennifer-shehane** [comment]
@dombo82 When does the crashing happen exactly? You run `cypress open`, when does it crash? Are you clicking and running a specific file? 

Can you provide a small reproducible example that reproduces the issue in Windows? Then we can run and see the crash. Thanks.

**Comment by dombo82** [comment]
@jennifer-shehane issue still appears when opening Test Runner (cypress open) on Cypress 7.4.0

- dev repository removed completely
- Node deinstalled
- Cypress and Node caches cleared up ("AppData")
- Node re-installed (node-v14.17.0-x64.msi)
- npm install --save-dev cypress@7.4.0
- npm cypress open
>>> CRASH with exception

Issue seems to be resolved with Cypress 7.5.0!
