### ISSUE TITLE
CT-UNI - Routing/Screen Workflow

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#16713]
- set up routing
- should have an appropriate interface to work with carousel
- "steps" abstractions
- some pages may not have the dots

Perhaps something like:

```jsx
<Carousel>
    <Page> 
      {/* This is a react router route?? */}
    </Page>
  <Steps number={1} />
</Carousel>
```

**Comment by rockindahizzy** [comment]
Nothing Actionable
