### ISSUE TITLE
Cypress There is no Internet connection

### ISSUE THREAD

**Issue by nWidart** [cypress-io/cypress#1671]
### Current behavior: 

When running `cypress open` and clicking `Run All Tests`, the chrome browser opens but with the following message:

```
There is no Internet connection
```

![image](https://user-images.githubusercontent.com/882397/39572875-40066fc2-4ed1-11e8-86d2-088aae0e9198.png)

### Desired behavior:

The browser opens correctly.

### Versions  

- `2.1.0`
- Chrome 66

Thanks!

**Comment by jennifer-shehane** [comment]
Hi @nWidart, this error usually displays when:
1. You don't have internet (I'm sure you've already determined this is not the issue 😉)
2. You are behind a corporate proxy - I suggest following the env vars workaround outlined [here](https://github.com/cypress-io/cypress/issues/1469).

Let me know if the proxy workaround solves your issue!

**Comment by nWidart** [comment]
Hello,

Indeed I was the issue about the corporate proxy, but even when not on the vpn it wouldn't work.
It worked before also on this same vpn.

Strangely what did work, however, was rebooting the computer 😄

Not sure what went on, but I guess it can be considered as resolved then :)

Thank you for your reply.

**Comment by jeremyjh** [comment]
I had this same error when a Cypress process was left open after I'd closed the client. I did a `ps -ef | grep cypress`, found the culprit, and killed it. That fixed it, which is probably what the reboot accomplished as well.

**Comment by nWidart** [comment]
That's good to know, thanks @jeremyjh !

**Comment by seanpoulter** [comment]
Force quitting a test running in Chrome can also cause these symptoms. Thanks @jeremyjh. 👌

**Comment by NoahPlanGrid** [comment]
Just saw this error.  Solved by rebooting.

**Comment by mukul7** [comment]
Rebooting Solves this

**Comment by jeremyjh** [comment]
@muku7 it really is not necessary to notify everyone subscribed to this issue with information that is already in the thread. Just upvote someone else's comment instead of adding a new one.

**Comment by mukul7** [comment]
> @muku7 it really is not necessary to notify everyone subscribed to this issue with information that is already in the thread. Just upvote someone else's comment instead of adding a new one.

its @mukul7  **

**Comment by prashanth-sams** [comment]
Still an issue on the end of 2021. Rebooting helps.
