### ISSUE TITLE
Development Guide does not cover common CLI use-case

### ISSUE THREAD

**Issue by upsampled** [cypress-io/cypress#16729]
### Current behavior
Developer/Contribute guide explains how to compile from source (IE: `yarn`); however, the compiled CLI command is unusable.

The specific use-case I have is:
* cypress is missing a feature I need for an integration test in my project repo
* I perform the typical git workflow (fork, modify, etc)
* Compile my fork and test it in my primary project
* Submit result as PR

### Debug logs
```
CY=/home/user/Projects/cypress/cli/bin/cypress
$CY run ./cypress/integration/crud/sanity.spec.js
No version of Cypress is installed in: /home/user/.cache/Cypress/0.0.0-development/Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: /home/user/.cache/Cypress/0.0.0-development/Cypress/Cypress

----------

Platform: linux (Ubuntu - 18.04)
Cypress Version: 0.0.0-development
```
Trying to work around this triggers another error:

```
 mkdir -p /home/user/.cache/Cypress/0.0.0-development/Cypress/
$CY run ./cypress/integration/crud/sanity.spec.js
No version of Cypress is installed in: /home/liam/.cache/Cypress/0.0.0-development/Cypress

Please reinstall Cypress by running: cypress install

----------


Cannot read binary version from: /home/liam/.cache/Cypress/0.0.0-development/Cypress/resources/app/package.json

----------

Platform: linux (Ubuntu - 18.04)
Cypress Version: 0.0.0-development
```

Playing around with `CYPRESS_CACHE_FOLDER` and `CYPRESS_RUN_BINARY` have just resulted in one or both of these two errors. 

### Download method
 

- [ ] npm
- [ ] yarn
- [ ] Direct download
- [x] other 
`git`
### Operating System
 

- [x] Linux - Ubuntu
- [ ] Mac
- [ ] Windows

### Other

- [x] development repository 
- [ ] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by jennifer-shehane** [comment]
You should be able to test your repo by running `yarn start` and pulling in your repo or running `yarn cypress:run --project=/dir/to/project`

If you need to manually test changes made to the `cli` directory, there are instructions on how here: https://github.com/cypress-io/cypress/blob/develop/cli/README.md#L44
