### ISSUE TITLE
Ability to display passed steps in headless mode in terminal

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#16749]
### What would you like?
It would be useful to have opt-in option to display passed headless mode in terminal (to be equivalent of displayed steps in headed mode).

### Why is this needed?
It will make logs more readable for business persons, who don't access source code of tests.

**Comment by jennifer-shehane** [comment]
@tomaszwojciechowski Could you provide a visual example of what you mean by the 'displayed steps in headed mode'? I'm not sure I exactly understand the feature request as is. 

What do you want to see during `headless` mode? Does 'headless' mean running `cypress run` or do you mean when passing the literal `--headless` flag?

**Comment by tomaszwojciechowski** [comment]
@jennifer-shehane By "headed mode" I mean GUI of Cypress Runner, and by "headless mode" I mean execution by `cypress run`.

Currently using `cypress run` I don't see steps which have passed, and I think that it would be useful to opt-in to display passed steps too, as in GUI of Cypress Runner.

**Comment by jennifer-shehane** [comment]
`cypress run` shows passing test titles to stdout as part of the default reporter. If you've changed your Cypress reporter, this may not display. Is this what you mean by showing 'steps which have passed'?

<img width="841" alt="Screen Shot 2021-06-02 at 11 06 15 AM" src="https://user-images.githubusercontent.com/1271364/120514234-abce5600-c392-11eb-8874-a222b4a7b732.png">

If you mean seeing each Cypress command that is run, you can review the video of the run to see this. 

There are a few plugins that log the commands, but I think they only do this when a test fails. I'm sure they could be edited to print it all for both. https://github.com/bahmutov/cypress-failed-log https://github.com/archfz/cypress-terminal-report
