### ISSUE TITLE
have to reinstall cypress everytime i restart my machine on ubuntu 20.04

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#16748]
### Current behavior
Have to install cypres after each time I shut down my machine 
![image](https://user-images.githubusercontent.com/32042806/120156867-b5b95300-c1f2-11eb-9c8b-17e78d54e71a.png)

### Desired behavior
should use cypress without reinstalling the node_modules every time I restart my machine

### Test code to reproduce
no code is needed, just try on ubuntu 

### Versions
7.4.0

**Comment by jennifer-shehane** [comment]
We have other users using ubuntu that don't encounter this error. Is there anything about or on your system that would be clearing this specific cache directory upon restart?

**Comment by Amrkamel1** [comment]
> We have other users using ubuntu that don't encounter this error. Is there anything about or on your system that would be clearing this specific cache directory upon restart?

yes you are right, seems I have one app that clearing cache was causing this
