### ISSUE TITLE
Allow copy/paste via keybindings like CTRL+C, CTRL+V via using .type

### ISSUE THREAD

**Issue by nisarhassan12** [cypress-io/cypress#16740]
### What would you like?

It would be great if `.type` allows copying and pasting via some sort of key combinations like `.type({ctrl}c)` just like `.type({selectall})` does what `CTRL + A` does. Thanks. 

### Why is this needed?

It is needed for testing that keybindings on a Textarea work as expected.

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/2386
