### ISSUE TITLE
Intercept url regex match only on get

### ISSUE THREAD

**Issue by cifren** [cypress-io/cypress#16753]
### Current behavior
```js
cy.intercept({url: '/api/*'},
        {
          "id": 3
        }).as('All')
```
match any 'GET' url and not 'PUT' url

### Desired behavior
```js
cy.intercept({url: '/api/*'},
        {
          "id": 3
        }).as('All')
```
match any 'GET' url and 'PUT' url and any other method.

### Test code to reproduce
See above

### Versions

Cypress: 7.4.0
Browser: Chrome 90 (headless)

**Comment by jennifer-shehane** [comment]
`cy.intercept()` automatically matches any method. 

>If you don't pass in a method argument, then all HTTP methods (GET, POST, PUT, PATCH, DELETE, etc.) will match. https://on.cypress.io/intercept#Matching-url

This should already work this way. Can you provide an example where this is not working?

**Comment by cifren** [comment]
Yes it is what I am telling on that post, it is not working the way it should, I suppose you want me to create a repo with a clear example. I'll see if I have the time to do it.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
