### ISSUE TITLE
cy.intercept does not return boolean stub correctly

### ISSUE THREAD

**Issue by martin-luo** [cypress-io/cypress#16752]
### Current behavior
When intercepting a request that returns boolean data the response is corrupted by cy.intercept:
```
response:{ json: null, responseStatusCode: 200, requestBody: null, url: 'PLACEHOLDER_FOR_LOCAL_HOST' }
```

### Desired behavior
Intercept should return correct stub response, e.g.
```
response:{ json: true, responseStatusCode: 200, requestBody: null, url: 'PLACEHOLDER_FOR_LOCAL_HOST' }
```

### Test code to reproduce
Create a simple application and intercept an API returning boolean value

### Versions
Cypress: "^7.2.0"

**Comment by jennifer-shehane** [comment]
@martin-luo Can you provide the test code to run to reproduce this issue?

**Comment by martin-luo** [comment]
Sorry for the late reply, it looks like it's working for me now. It's more like a application-side error. I'll close the card for now.
