### ISSUE TITLE
@cypress/react regression in 5.9.0 from 5.8.0: findReactScriptsWebpackConfig returns undefined

### ISSUE THREAD

**Issue by yann-combarnous** [cypress-io/cypress#16751]
### Current behavior
findReactScriptsWebpackConfig is returning "undefined" for react-script webpack configuration in version 5.9.0.

### Desired behavior
findReactScriptsWebpackConfig was returning react-scripts webpack configuration in version 5.8.0, both with `cypress-run` and `cypress run-ct`.

### Test code to reproduce
In plugin/index.js, we setup the following for unit/component testing code coverage:

```js
import injectDevServer from '@cypress/react/plugins/react-scripts';
import findReactScriptsWebpackConfig from '@cypress/react/plugins/react-scripts/findReactScriptsWebpackConfig';
import { startDevServer } from '@cypress/webpack-dev-server';
// Code coverage
import codeCoverageTask from '@cypress/code-coverage/task';

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)
/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  codeCoverageTask(on, config);

  // Component testing web dev server setup for code coverage
  injectDevServer(on, config);
  const webpackConfig = findReactScriptsWebpackConfig(config);
  const rules = webpackConfig.module.rules.find((rule) => !!rule.oneOf).oneOf;
  const babelRule = rules.find((rule) => /babel-loader/.test(rule.loader));
  babelRule.options.plugins.push(require.resolve('babel-plugin-istanbul'));
```

### Versions

Create-React-App 4.0.3
@cypress/react: 5.9.0

**Comment by yann-combarnous** [comment]
@jennifer-shehane , found the issue: findReactScriptsWebpackConfig now requires webpack config path to be set explicitely.

This is a breaking change, would have been nice to have default set to former 5.8.0 value if not provided.

**Comment by jennifer-shehane** [comment]
Perhaps introduced in https://github.com/cypress-io/cypress/pull/16644

**Comment by yann-combarnous** [comment]
@jennifer-shehane , correct, the default CRA path was replaced by a variable, would have been nice to substitute CRA value for backward-compatibility.

**Comment by lmiller1990** [comment]
#16813 should fix it.

**Comment by elevatebart** [comment]
Delivered in 5.9.1
