### ISSUE TITLE
Cypress redirects to not-found when running chrome

### ISSUE THREAD

**Issue by BertaVR** [cypress-io/cypress#16758]
Apparently it fails to load static content when using chrome or electron (the website works correctly when testing in manually on chrome) and redirects to not-found. On firefox it works well.

**Comment by BertaVR** [comment]
Version

Cypress: 7.2.0
Google Chrome: 90.0.4430.212
Electron: 89

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.

**Comment by BertaVR** [comment]
I'm sorry!

### Current behavior

![image](https://user-images.githubusercontent.com/72273706/120432794-b1b83d00-c37a-11eb-9bcc-2fd4c8076ecc.png)
![image](https://user-images.githubusercontent.com/72273706/120432869-d0b6cf00-c37a-11eb-9c16-696215b516ff.png)

Apparently it fails to load static content when using chrome or electron (the website works correctly when testing in manually on chrome) and redirects to not-found. On firefox it works well.  
It redirects to not found when it loads svg contents.



### Desired behavior

Finding the content
### Test code to reproduce


### Versions


Cypress: 7.2.0
Google Chrome: 90.0.4430.212
Electron: 89
Ubuntu 20.04.2

**Comment by jennifer-shehane** [comment]
The screenshot you posted shows an .svg as complete - is this from Firefox?

This will not be possible to track down without a way to see the issue ourselves. Is there a way to reduce the example to something reproducible that can be shared?
