### ISSUE TITLE
Proposal: Regular Release Cycle

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1677]
# Proposal

Release a new version of Cypress every 2 weeks.

There are many pull requests that are merged in and working in the `develop` branch that do not get released regularly and makes users 😢 

# To Achieve

The main challenge in achieving a regular release cycle is our internal process. We will need to be stricter about our branching strategy and release process.

- `develop` branch should always have all tests passing and **never** have 'partial' features.
- Any new feature should always be in a ['feature branch'](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). When a feature is **complete**, it gets merged back into develop.
- Release every 2 weeks! It does not matter if another feature is *close*. 
- Automate, document and/or disperse more responsibility of [deploy process](https://github.com/cypress-io/cypress/blob/develop/DEPLOY.md). 
- This can only be done after 3.0 as there are a myriad of half-done features in the `develop` branch at the moment.

**Comment by bahmutov** [comment]
I just want to add one more to this list
- merge pull requests (after approval) as early as possible. No waiting until "starting the release" process; instead landing features in `develop` early gets us a chance to actually interact with the new code a little bit to flush out any hidden side effects.

**Comment by jennifer-shehane** [comment]
We have made some progress on this! Particularly where it comes to "Automate, document and/or disperse more responsibility of deploy process." Our [DEPLOY.md](https://github.com/cypress-io/cypress/blob/develop/DEPLOY.md) doc has recently been updated with more documentation on the process. We also have more hands on the deploy process.

I'd still like to aim to have a set release cycle of 2 weeks. cc @flotwig

**Comment by flotwig** [comment]
An update on this: we've decided to aim for a maximum of two weeks between releases, with less time if a patch release needs to come out or something. This should provide a nice balance between time spent on release and time before new features are released to users.
