### ISSUE TITLE
Multi-domain: Create postMessage bus for cross-domain communication

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#16777]
There's currently rudimentary postMessage communication implemented, but it needs to be made more robust with a proper API and serialization handling.

- Move internal multidomain-related events off the public Cypress/cy event bus onto a dedicated internal bus
- Create a naming scheme for events sent over the bus
- ~Create a promise-based API for request-response~
- ~Ensure serialization of more complex of data works, or else implemented JSON stringify and parsing~

**Comment by AtofStryker** [comment]
We currently do not see an applicable use case for the promised based implementation of cross domain events, but will likely revisit this in the future if the need arises. 

It's also worth noting that right now we don't have any serialization baked into cross domain communication. Currently, I believe we only need to serialize function commands going to the spec bridge. As the multi domain implementation is fleshed out, we will likely see the need to bake in standard serialization for more complex data types being messaged, but as of right now it isn't needed.
