### ISSUE TITLE
Cypress : Using "modifyObstructiveCode": false solved Blankscreen issue but TestRunner crashes with ERR_TLS_REQUIRED_SERVER_NAME

### ISSUE THREAD

**Issue by Aishwarya-UR** [cypress-io/cypress#16782]
I'm hitting an issue where Cypress is loading my desired webpage, but quickly crashes with the following error in the logs: 

```
Error [ERR_TLS_REQUIRED_SERVER_NAME] [ERR_TLS_REQUIRED_SERVER_NAME]: "servername" is required parameter for Server.addContext
``` 

anyone help for this please?
Spent a lot of time with no valid answer to this :(

Have tried setting "chromeWebSecurity": false to cypress.jon while running against Chrome browser, still no luck

### Versions
Cypress version: 7.4.0
Browser: Chrome 9.0
Operating System: Windows 2016

**Comment by jennifer-shehane** [comment]
Can you try setting this config option in your `cypress.json` or elsewhere? 

```json
{
	"experimentalSourceRewriting": true
}
```

If you can provide a reproducible example of the issue to begin with, with the application under test or a smaller subset that shows the problem - that will help others in providing workarounds.

**Comment by Aishwarya-UR** [comment]
@jennifer-shehane - Hi, its an company internal application, hence I will not be able to provide AUT or its code.
But adding the above said tag in cypress.json - doesnt help - same error & test runner crashes:

![TLS_ServerError](https://user-images.githubusercontent.com/55271275/120595867-ab9c8c00-c460-11eb-88f4-5ae113ffd95f.PNG)


But the application is HTTPS enabled & while I invoke the application in any browser after the cache is cleared - it usually gives the below :
![image](https://user-images.githubusercontent.com/55271275/120596296-354c5980-c461-11eb-826f-12cab1a9c14c.png)

& the same in handled in Protractor - via setting - --ignore-certificate -errors in config.ts file.

**Comment by Aishwarya-UR** [comment]
Ok, so fix mentioned in thread [https://github.com/cypress-io/cypress/issues/9220](url) worked for my issue. Application runs fine now. Thanks alot for the quick attention.

**Comment by rohitkadam19** [comment]
I still see the problem with Cypress version 7.6.0 and Electron, Chrome 91.
With the workaround mentioned here - https://www.gitmemory.com/issue/cypress-io/cypress/9220/757066680 it works.
But on CI, it will be hard do this change.
