### ISSUE TITLE
files.spec.js uses an API that is not defined in cypress typescript types

### ISSUE THREAD

**Issue by lifeiscontent** [cypress-io/cypress#16785]
this test is using an undefined API in Cypress Typescript Types.

`cy.wrap<F extends Promise<S>, S>(promise: F, options: Partial<Loggable & Timeoutable>)`

where its clear the test here is using a string instead of some object of options, can you guys please update your types to either reflect this API or fix the test that is used when installing cypress for the first time?

```js
  it("cy.fixture() or require - load a fixture", function () {
    // we are inside the "function () { ... }"
    // callback and can use test context object "this"
    // "this.example" was loaded in "beforeEach" function callback
    expect(this.example, "fixture in the test context").to.deep.equal(
      requiredExample
    );

    cy.wrap(this.example, "fixture vs require").should(
      "deep.equal",
      requiredExample
    );
  });
```

**Comment by jennifer-shehane** [comment]
This is not an accepted signature for `cy.wrap()`. I'm not sure why it was written this way. 

Opened a PR to address. Closing this issue. Feel free to followup in the PR https://github.com/cypress-io/cypress-example-kitchensink/pull/496
