### ISSUE TITLE
No clear pattern for waiting global events

### ISSUE THREAD

**Issue by eric-burel** [cypress-io/cypress#16793]
### What would you like?
A more robust way to listen for global events that can be triggered at page load.

### Why is this needed?

Imagine this test:

```js
it("trigger 'loaded' event on page load", () => {
    cy.visit("/home") // imagine some component of home is triggering a "loaded" event
    // TODO: how to check that the 'loaded' event is triggered?
})
```

Alternative I've tested:
- Using `cy.document().then()` to add the event listener after the `cy.visit()` => doesn't work, because the event is often already triggered by the time `cy.document()` resolves, too late.
- Using `cy.window()` and `cy.document()` before the `cy.visit()` => doesn't work, because the Window/document do not exist before you call `cy.visit()`
- Using `cy.window` after the `cy.visit()` => it does work, but I am not sure about it. The race condition might still exist if the event is triggered very early on, so I think this works only if your app is doing some computation (like rendering a React page).
- Using `onBeforeLoad`: doesn't work, because you can use `cy` to write the assertion in the event listener callback, but you cannot wait.
This is what I tried:
```js
    cy.visit(`/home', {
      onBeforeLoad: $window => {
        return new Cypress.Promise(resolve => {
          $window.addEventListener('loaded', () => {
              cy.expect(true).toBe(true) // may work, but the test won't wait for assertions to be true
              $window.removeEventListener('loaded') // cleanup step
              cy.resolve()
          });
        });
      }
    });
```
The problem is that returning a Promise in `onBeforeLoad` doesn't work.

Possible solution:
The most reliable solution would be to allow returning a promise in `onBeforeLoad` and wait for it in the test.

**Comment by StefanVesper** [comment]
Hey everybody,

I just ran into the same issue trying to test if a global event has been called by my component. 
Has there been a solution to this lately? 

Cheers,
Steve
