### ISSUE TITLE
Cypress : How to get style attribute value & use it for verification further?

### ISSUE THREAD

**Issue by Aishwarya-UR** [cypress-io/cypress#16794]
Hi, I have a requirement to select on a radio button from a table. 3columns of the table are Radio button, Column1, Column2.
Here Column1 can have same values, but based on Column2 passed, I should select on radio button row of Column1.
Like this:
![image](https://user-images.githubusercontent.com/55271275/120637388-77d75b80-c48c-11eb-955f-18f98adb83d5.png)

### Current behavior
The only way to differentiate the Column1 value for corresponding Column2 is their style="top:10px" attribute which is also seen in DOM. Hence I'm trying to read the style attribute for Column2 and match it with style attribute of Column1 - with no luck :(

From F12:
![image](https://user-images.githubusercontent.com/55271275/120638618-fa144f80-c48d-11eb-9a54-f79925d50cfc.png)

### Test code to reproduce
Have tried below:
```
cy.get().invoke('prop', 'style.cssText'').then(style =>{}) // here style returns undefined
```
and
```
cy.get().invoke('prop', 'style'').then(style =>{}) // here style returns undefined
```
and
```
cy.get().invoke('attr','style').then(style =>{}) // here style returns undefined
```
and inside then - need to check the Column1 style also matches & check that respective radio button.

Can someone please help?

### Versions
Cypress version: 7.4.0
Browser: Chrome 9.0
Operating System: Windows 2016

**Comment by Aishwarya-UR** [comment]
OK, tried something like below as mentioned in [https://github.com/cypress-io/cypress/issues/3837](url)

```
cy.get().its('style').should('exist').then((style) => {
...
this says below & further steps to check radio button does not happen
![image](https://user-images.githubusercontent.com/55271275/120643594-fe436b80-c493-11eb-90c8-acaa98a23934.png)

..
});
```

**Comment by jennifer-shehane** [comment]
I'm not sure exactly what you're trying to test, but here's an example of comparing styles. 

You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.

```js
it('style attr', () => {
  cy.visit('index.html');
  cy.get('h1')
    .should('have.attr', 'style').as('h1Style')
  cy.get('h2')
    .should('have.attr', 'style').as('h2Style')

  cy.get('@h1Style').should(function (style) {
    expect(style).to.eq(this.h2Style)
  })
})
```

```html
<html>
<body>
  <div>
    <h1 style='top: 35px'>Testing with Cypress.</h1>
    <h2 style='top: 35px'>Testing with Cypress.</h1>
  </div>
</body>
</html>
```
