### ISSUE TITLE
Wait for additional services to be available for E2E Testing

### ISSUE THREAD

**Issue by joshmccure** [cypress-io/cypress#16805]
### What would you like?
When Cypress currently starts up it checks for availability of the baseUrl. This is great because it allows teams to get fast feedback the application isn't available and should be investigated. In a microservices environment an application contains many services that make up the full E2E stack, it would be great to have a way to configure additional services that Cypress will wait to be available before running tests.

### Why is this needed?
Faster feedback loop when a critical service is down. Rather than investigating failing tests, the team should know that the service is simply down.

### Additional Notes
To go with this feature the Dashboard product should be extended to allow Slack posts for this. This would further improve the feedback loop, as teams would know instantaneously what the problem on the current test run is. 

The Current behavior on the Cypress Dashboard when the baseUrl isn't available is that the Test run will stop and there is no way to reliably know about this without checking CI. Slack updates fit this purpose perfectly. 

Maybe a Slack update like the following

`Cypress failed to run your tests because the following services were down: baseUrl, serviceA, serviceB`

Note: If you'd like me raise a separate feature request for the Dashboard Slack message, let me know.

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work given the lack of interest from others on this feature.
