### ISSUE TITLE
Webpack Comilation Error

### ISSUE THREAD

**Issue by Rao-J** [cypress-io/cypress#16804]
@jennifer-shehane , this issue still persists

Cypress package version: 7.4.0
Cypress binary version: 7.4.0
Electron version: 12.0.0-beta.14
Bundled Node version:
14.15.1

```js
describe('Login Test', () => {
it('Visit app server', () => {
// visit app server
cy.visit('https://SomeLink.html')

})

it('Enter credential', () => {
  // type user name
  cy.get('#username')
    .type('Value1')
    .should('have.value','Value1')

  // type user name
  cy.get('#password')
    .type('Value1')
    .should('have.value','Value1')
})

it('Click login botton', () => {
  // click login button
  cy.get('.btn-submit').click()
  // check if login
  cy.get('#userdisplay-btnInnerEl').should('contain','Value')
})
})
```

![image](https://user-images.githubusercontent.com/85312536/120701416-309b9b80-c489-11eb-9a8b-d68e281bba8b.png)

**Comment by jennifer-shehane** [comment]
@Rao-J Could you provide the webpack configuration you have setup? Ideally a smaller repo that can reproduce the issue. 

The error seems to indicate that it cannot find anything within the `C:\Cypress_Workspace` path. Is this path correct?

**Comment by Rao-J** [comment]
@jennifer-shehane ,

I am assuming this is the the right path, if not please correct me, I brought this config from below mentioned path .
C:\Cypress_Workspace\node_modules\webpack
[webpack.zip](https://github.com/cypress-io/cypress/files/6600806/webpack.zip)
I think this path is correct that is where I setup my workspace and installed everything. 
What I meant "this issue persists means" that this ticket was closed as not reproducible in 7.3.0 found some bug and read it in it's comments, but it still persist as I am using 7.4.0

**Comment by jennifer-shehane** [comment]
@Rao-J Could you include the code from the entire plugins file where you have configured the @cypress/webpack-preprocessor?

**Comment by Rao-J** [comment]
@jennifer-shehane ,
[Cypress_Workspace.zip](https://github.com/cypress-io/cypress/files/6765523/Cypress_Workspace.zip)

Here is the whole setup that I am attaching and the code is in this path : Cypress_Workspace\cypress\integration\app_server
