### ISSUE TITLE
Add option to scaffold component level tests and remove Karma when using Cypress Angular schematic

### ISSUE THREAD

**Issue by Yethal** [cypress-io/cypress#16817]
### What would you like?
Add option to scaffold component-level tests using @cypress/angular and remove karma when adding Cypress using angular schematic
### Why is this needed?

Make it easier and more convenient to move all test levels to Cypress for Angular applications

**Comment by lmiller1990** [comment]
We've got first class Angular support now - if there's more to be desired, please open a new issue.
