### ISSUE TITLE
Failing at Redirect

### ISSUE THREAD

**Issue by jasonellington** [cypress-io/cypress#1681]
### Current behavior:
I am accessing my local project at http://drupal.docker.localhost.website.com:8000/ and then I am doing a form submission. Upon form submission it goes to another url (same domain) http://drupal.docker.localhost.website.com:8000/after/form/submit and instead of staying on the page, it suddenly goes to the page with "Sorry, there are no test to run" 

## a few notes
* I am on a corporate proxy
* I was having this issue accessing an external url (uat.oursite.com) however now I am getting this odd functionality for my localhost as well

**Comment by jennifer-shehane** [comment]
Could you try running the current workarounds, specifically about "environment variables" with corporate proxy as outlined in https://github.com/cypress-io/cypress/issues/1469 and let me know if this resolved your issue?

**Comment by jasonellington** [comment]
@jennifer-shehane 

* I attempted to NO_PROXY to prevent hitting corporate proxy - same behavior
* I downloaded via the direct download and that doesnt even run my test, says: "Whoops, we can't run your test"

**Comment by Bkucera** [comment]
@jasonellington are you specifically having problems on localhost subdomains?

**Comment by jasonellington** [comment]
@Bkucera although i havent tried it on a regular domain, i was not having this problem until recently. No significant changes to my cypress code were made, however there were a few commits to our develop branch that i merged in to my testing branch...

I am testing a e-commerce process where someone is adding a product to their cart. In my local environment i cannot get passed the homepage and filling out a form and browsing products... however if i used our uat.website.com (external site) i can get further along the shopping process but the same behavior still occurs... I am unsure if this information helps but I am very stuck on this problem

**Comment by jasonellington** [comment]
here is the code I am executing:
```
it('test 1', function() {
    cy.visit('http://docker.localhost.website.com:8000/')
    cy.get('#button').click()
    cy.get('product').select('product_1')
    cy.get('#zipcode').type('10003').
    //failing after this call
    cy.get('#form').submit().debug()

    cy.get('#age').select('60')
  })
```

here is a statement in the log of the debug on the command line that looks suspicious
```
cypress:server:files specPattern for test files is undefined +0ms
```

**Comment by jennifer-shehane** [comment]
> cypress:server:files specPattern for test files is undefined

This message just means that you did not pass anything to the `--spec` flag when running your tests.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
