### ISSUE TITLE
Plugin cannot retrieve updated env variables from a running test

### ISSUE THREAD

**Issue by symon-skelly** [cypress-io/cypress#16822]
### Current behavior

Cypress Environment Variables that are set / updated during the running state of a test are not accessible to plugins within the plugins\index.js file. 

### Desired behavior
Any plugins that are set up to use config.env variables should be able to use the most recent state of the variable, not just the value the variable contains when starting a test run.

### Test code to reproduce

cypress.json:
```
"env": {
  "IP": "",
  "db": {
    "host": "",
    "port": "12345",
    "user": "user-omitted",
    "password": "ps-omitted",
    "database": "db-omitted"
  }
}
```
plugins\index.js:
```js
const mysql = require('mysql')

function queryTestDb (query, config) {
  config.env.db.host = config.env.IP //config.env.IP is an empty string, even though we're setting Cypress.env("IP") before running the task.
  const connection = mysql.createConnection(config.env.db)
  connection.connect()
  return new Promise((resolve, reject) => {
    connection.query(query, (error, results) => {
      if (error) reject(error)
      else {
        connection.end()
        return resolve(results)
      }
    })
  })
}

module.exports = (on, config) => {
  on('task', {
    queryDb: query => {
      return queryTestDb(query, config)
    }
  })
}
```

in get_host_spec.js:

```js
Cypress.env("IP", "123.123.123.123")
cy.task('queryDb', "Update users SET address = 'an_acceptable_address_here'")
```

### Versions
Cypress 7.4.0
Google Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by priscillakitice** [comment]
I want to know what the solution was, because I'm having the same problem.

**Comment by austinbradshaw** [comment]
Having the same issue here
