### ISSUE TITLE
Video Autoplay not working when invoked from Cypress Testrunner

### ISSUE THREAD

**Issue by only4arunkumar** [cypress-io/cypress#16824]
### Current behavior
Video with autoplay enabled are no more playing automatically when they are loaded from Cypress test runner
Here video is embedded in an iframe . And the player is based on videojs.
When the user manually load the video url from browser it works fine  
### Desired behavior
Video with autoplay enabled at iframe and query-string should play automatically 

### Test code to reproduce
https://github.com/only4arunkumar/CypressAutoPlay

### Versions
Cypress :7.4.0
testing-library/cypress :7.0.6
cypress-iframe: 1.0.1

**Comment by jennifer-shehane** [comment]
Hey @only4arunkumar, you mentioned this previously working in 6.8.0, but when I downgrade Cypress in the given repo - the test still doesn't pass. 

I do see that the website does not autoplay the video as it would outside of Cypress. 

### Outside Cypress

![](http://g.recordit.co/ytunFJWSc1.gif)

### Inside Cypress

![](http://g.recordit.co/LEb6hx47M9.gif)

It looks like there's an error in the console that doesn't show up when running outside of Cypress. Not sure if that is relevant. 

<img width="687" alt="Screen Shot 2021-06-10 at 12 53 29 PM" src="https://user-images.githubusercontent.com/1271364/121573498-f4b58880-c9ea-11eb-9db6-6615ef55e2ee.png">

Sometimes the autoplay seems to work when I run the tests in Electron 87 with `modifyObstructiveCode: false`, which seems like a strange combination. But I was thinking there may have been changes in recent Chrome browsers that are causing this. I'm not sure.

**Comment by only4arunkumar** [comment]
The issue which was highlighted by @jennifer-shehane  was fixed by our dev and my test started to work fine.  Thanks a lot for your time Jennifer. I shall update with the details of the fix by our developers
