### ISSUE TITLE
Require is not defined on electron

### ISSUE THREAD

**Issue by reetou** [cypress-io/cypress#1683]
### Current behavior: 

`require is not defined` inside index.html

![image](https://user-images.githubusercontent.com/18047528/39666767-ca877498-50b1-11e8-809b-c8895848e666.png)

### Desired behavior:

Renders successfully

### Steps to reproduce:

My index.html contains this inside `<script>` tag. Webpack preprocessing didn't make sense.

```js
window.addEventListener("keydown", e => {
            if (e.ctrlKey && e.shiftKey && e.key === "I") { // для возможности открытия в релизных версиях
                let remote = require("electron").remote;
                remote.getCurrentWindow().toggleDevTools();
            }
        });

        // You can also require other files to run in this process
        let render = require('./out/App').render;
        render('id1');
```

### Versions  

macOS High Sierra `10.13.3`
Cypress `2.1.0`
Electron `1.8.2`
Webpack preprocessing plugin `1.1.3`
Webpack `3.6.0`
I am also using typescript and es6.
Webpack preprocessor config
```js
const wp = require('@cypress/webpack-preprocessor')

module.exports = (on) => {
	const options = {
		webpackOptions: {
			resolve: {
				extensions: ['.ts', '.js'],
			},
			module: {
				rules: [
					{
						test: /\.ts$/,
						exclude: [/node_modules/],
						use: [{
							loader: 'ts-loader',
						}],
					},
				],
			},
		},
	}
	on('file:preprocessor', wp(options))
}
```

**Comment by brian-mann** [comment]
You're trying to use a `require` tag inside of the chrome browser that's requiring a node module that's only available inside of `electron`. 

Cypress can run tests in electron but only with `nodeIntegration` disabled. Even with it enabled it would also run in `electron` and would never work in `chrome`.

Cypress is about testing things that a browser renders - whereas with electron it can do a whole lot more and is much more than just a browser. These things aren't compatible.

**Comment by gtamas** [comment]
So this means that it's actually impossible to really test Electron apps with Cypress, right?

I mean, you can make it run the tests, but only if you stub everything electron / node specific. Basically, Cypress can only execute code which natively runs in the browser.

**Comment by gtamas** [comment]
And for example, if my app uses an RPC lib which runs only in node, all one must stub all RPC calls to make this work with Cypress?

Is this correct?

**Comment by gtamas** [comment]
@brian-mann

**Comment by jennifer-shehane** [comment]
@gtamas Yes, this is correct. You can currently only test Electron apps by stubbing the ipc events. https://on.cypress.io/using-cypress-faq#Can-I-test-my-Electron-app

There's an issue open to support this here https://github.com/cypress-io/cypress/issues/2072

**Comment by gtamas** [comment]
@jennifer-shehane 
OK, I see thanks for the info. The issue you linked seems to be kinda dead. Is the Cypress team actively working on this? 

Problem is, stubbing some IPC events is fine, but if you have to stub every single Node API too, that's way too much hassle.

In your opinion, will electron support be available relatively soon, or it's better to use Spectron for now?

**Comment by jennifer-shehane** [comment]
@gtamas We haven't done any development on the feature to support Electron testing yet, so I wouldn't say it will come relatively soon.

**Comment by gtamas** [comment]
ok thx
