### ISSUE TITLE
Remove usage of `--remote-debugging-port`, rely on Chrome-chosen port instead

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#16833]
### Current behavior

Cypress launches Chrome with `--remote-debugging-port=SOME OPEN PORT`. Unfortunately, this creates a race condition, since the port that was open at the time of port detection may not be open once Chrome has finished launching and listening. Especially in CI where the TCP port namespace is shared between containers.

### Desired behavior

Do not specify a port, instead, let Chrome choose an open port so this race condition cannot occur.

This will break a common pattern that users use in their plugins - snarfing the RDP port from `--remote-debugging-port` arg and then connecting to it via their plugin code to send commands. This is used in many community plugins, including https://github.com/flotwig/cypress-log-to-output , so we should consider it a breaking change.

As a result, this should not be added until we have another way to expose CDP to users. 

Edit: Most likely this could also be applied to Firefox's CDP port.

**Comment by jennifer-shehane** [comment]
Do you think this will solve the leftover "Cypress failed to make a connection to the Chrome DevTools Protocol" errors?

- https://github.com/cypress-io/cypress/issues/16571
- https://github.com/cypress-io/cypress/issues/16620
- https://github.com/cypress-io/cypress/issues/16620
- https://github.com/cypress-io/cypress/issues/15650
- https://github.com/cypress-io/cypress/issues/5613

**Comment by bahmutov** [comment]
“ This is used in many community plugins, including https://github.com/flotwig/cypress-log-to-output”

I see what you did there

**Comment by flotwig** [comment]
> Do you think this will solve the leftover "Cypress failed to make a connection to the Chrome DevTools Protocol" errors?

This only fixes the race condition possibility.

#16620 kinda sounds like a duplicate of #16571, since from what I can gather it's happening every time. #15650 might be a duplicate as well, since it implies that it's happening every time. But since it's happening every time, none of these 3 are covered by this issue.

#5613 happens for a different reason too: https://github.com/cypress-io/cypress/issues/5613#issuecomment-553491728

**Comment by jennifer-shehane** [comment]
Yah I was going to try to clean up the duplicates today. Would be nice to fix those. 😢
