### ISSUE TITLE
type() won't tipe in autoformating field

### ISSUE THREAD

**Issue by souljacker** [cypress-io/cypress#1684]
I'm testing a client's react app and it has a credit card page. type() is not filling the fields, which are designed to autoformat the input to match a credit card or date format. (4242424242424242 -> 4242 4242 4242 4242).

Is there a way to deal with this behavior or to simply change the field values directly?

**Comment by Bkucera** [comment]
@souljacker could you share the Cypress code you're using with `.type` ? This should be supported already

**Comment by souljacker** [comment]
@Bkucera 

```
 cy.contains('Add card').click();
    cy.contains('Card').click();

    cy.get('input[name=card_number]').its('name');
    cy.get('input[name=card_number]').type('4242424242424242');
    cy.get('input[name=card_number]').its('name');

    cy.get('input[name="card_exp"]').type('0120');
    cy.get('input[name="card_cvc"]').type(123);
    cy.contains('Save card').click();
    cy.contains('xxxx xxxx xxxx 4242');
```

I know the component is using react-input-mask, but I'm not really sure about how it works

**Comment by jennifer-shehane** [comment]
This issue is likely related to input masking - this issue also outlines some issues encountered with input masking https://github.com/cypress-io/cypress/issues/940

**Comment by iam4x** [comment]
Hi :wave:

I ran into the same issue, with `react-input-mask` and `React16` but I have found a workaround.

```
  it.only('should format birthdate', () => {
    cy.get('input[id*=birthdate]')
      .as('birthdateInput')
      .then($input => {
        // get native DOM element
        $input = $input.get(0);

        // track last value since we need it for React16 track value
        const lastValue = $input.value;

        $input.value = '29041992';

        // dispatch change into React as well
        $input._valueTracker.setValue(lastValue);
        $input.dispatchEvent(new Event('change', { bubbles: true }));
      });

    cy.get('@birthdateInput').should('have.value', '29/04/1992');
  });
```

Hope it helps @souljacker 👍

**Comment by Bkucera** [comment]
I'm looking into this, as well as the other issues in the `cy.type() epic` #1241

**Comment by adil-boukdair** [comment]
Clearing the input before typing seems to solve the issue

`cy .get('input[name*=birthdate]').clear().typeMask('29041992')`

**Comment by arimourao** [comment]
Can confirm this bug is still alive and well. It fails to fill an masked input text about 50% of the time. This need to be priority.

**Comment by Bkucera** [comment]
@arimourao we have tests around this and they pass. Please present a reproducible example if you want an issue looked into. Thanks
