### ISSUE TITLE
High CPU Usage starting cypress from Visual Studio Code terminal and not running any tests

### ISSUE THREAD

**Issue by morissonmaciel** [cypress-io/cypress#1685]
Hi,
I've just find myself impossible to continue to write my test cases using **cypress** due a unexpected issue running the command `./bin/cypress open` in my web site project.

I'm using Visual Studio Code setup with a simple web site folder (using only **HTML/Javascript/DOM** stuff) and, when I run cypress with given command, **my CPU usage just blow up with highs in 30% up to 38%.**

Simple starting cypress and doing nothing more. In **current behavior** section you can find a screen shot with related issue (my current language is Brazilian-Portuguese, but I think this won't meter at all).

### Current behavior: 

High CPU usage only running initial command `./bin/cypress open` in Visual Studio Code terminal.

![screenshot_1](https://user-images.githubusercontent.com/11509104/39716883-f9a4085c-5207-11e8-9ab3-a9c7c9d41242.png)

### Desired behavior:

Extremely low CPU usage once I'm not running any tests with cypress.

### Steps to reproduce:

1. Open Visual Studio Code bound to a specific folder
2. Create a empty `node_modules` folder
3. Open Visual Studio Code terminal with `CTRL+'` keyboard keys
5. Enter `node_modules` folder (i.e: `cd node_modules` in Windows)
4. Type **npm install** command `npm install cypress`
5. Wait for package both download and unzip stages
6. Enter `cypress open` command (i.e: `.\.bin\cypress open` in Windows)
7.  Wait for **cypress window** come up
8. Check CPU usage (i.e: **Show Task Manager in Windows** and go to  `Process` ordered by `CPU usage %`)

I have a custom test file in my `cypress/integration` folder with following code: 
```js
describe('Simple Test Collection', function() {
    it('Simple test usage', function() {
        cy.visit('http://127.0.0.1:5500/')
    })
})
```
`NOTE: Once again, even with above .js, I'm not running any tests at the moment of this screenshot.`

### Versions 
* Architecture x64
* cypress: '2.1.0'
* node: '7.9.0'
* npm: '5.6.0'
* Visual Studio Code: '1.23.0'
* Windows: '10 Build 1804'

**Comment by benpolinsky** [comment]
Not sure how many Windows users Cypress has, but I am not seeing this behavior. CPU is humming along at 0-0.4% while running but 'idle'. Also running from within VSCode, though not a blank project.

## Versions

- Architecture x64
- Cypress '2.1.0'
- node: '9.7.1'
- npm: '5.6.0'
- VSCode: '1.23.0'
- Windows '10 Build 1703'

**Comment by morissonmaciel** [comment]
I suppose this is something related to Windows 10 2018 April Update (Build 1803/1804).
Maybe affecting VS Code environment and cypress process.

I can try to run cypress tests directly in command prompt.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by morissonmaciel** [comment]
Hello again,
Now I can confirm the problem was related to last major `Windows 10 Update`. After install this weekend patch and recreating my cypress test project, I can run cypress with extremely low CPU usage.

Windows 10 April Update affected `webkit` somehow and, maybe, this is the cause of anomalous issue.

![screenshot_1](https://user-images.githubusercontent.com/11509104/39975170-5fc38798-5703-11e8-872d-541066d93475.png)

**Comment by jennifer-shehane** [comment]
Great. If others can confirm - we can close this issue. @benpolinsky Can you confirm you had the April update?

**Comment by benpolinsky** [comment]
@jennifer-shehane I am on build 1703 which was LAST (2017) April's update and have no problems.

**Comment by brian-mann** [comment]
Atom, VSCode, and Cypress all share the same dependencies - so if a Windows update caused it for us, it would cause it for the others too.

**Comment by Saibamen** [comment]
Cypress 3.1.5, latest VS Code. Windows 10.0.17763.316:
![obraz](https://user-images.githubusercontent.com/905878/53272492-63228f80-36e9-11e9-9409-80f6d53786e5.png)

**Comment by jennifer-shehane** [comment]
Closing. Please comment here if you are still experiencing this or open a new issue.
