### ISSUE TITLE
Cypress-social-login works fine, but after the login, we redirect to a different URL using cy.visit() that fails to load using Etimedout #101

### ISSUE THREAD

**Issue by sarathk-blink** [cypress-io/cypress#16859]
I'm using cypress-social-login plugin to login into our application that uses google account as Oauth. I can see that the login happens successfully, cookies are being set and I can verify cookies on the cypress console. When I do cy.visit() after the social login to access my app with the URL, (that uses google account as sign-on) I see below error message.
```
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:

Error: ETIMEDOUT
Common situations why this would fail:

you don't have internet access
you forgot to run / boot your web server
your web server isn't accessible
you have weird network configuration settings on your computer
Below are some troubleshooting steps:
```

This issue is intermittent, happens about 7/10 times. The other 3 times I Can do social login fine and cy.visit() to our app loads the page. I even tried cy.visit() with https://www.google.com after the social login for the times when it failed, even the google page would timeout.

I have verified my VPN settings, removed http, https proxy and made sure that the network connection is looking good.

Removed and Reinstalled NPM, Node and cypress several times. (With different versions) - No luck.

When I see that error, I then open a new tab manually on the same automation browser instance and I can load my app url just fine. But it wouldn't load in the same window of cypress after the social login.

Works perfectly fine if I first visit my app url and then do a call social-login plugin (Just did the otherway to see where the problem is).

When I try the same flow (Doing social-login first) then hitting my app URL manually, everything works just perfect. Doesn't work when I run via cypress automation.

I tried all other steps to debug from the internet and I'm not able to figure this out. Appreciate anyone that can help.

MacOs : Catalina 10.15.7
Node : v14.17.0
Npm : 6.14.13
Cypress: 6.8.0

**Comment by xiaoyueguang** [comment]
I also have this problem.
if the response code === 302, so cy.visit() maybe failed
