### ISSUE TITLE
browser notification permission state

### ISSUE THREAD

**Issue by NazrulChowdhury** [cypress-io/cypress#16852]
### Current behavior
Chrome browser instance loads with 'browser notification allowed' state. Browser settings shows 'Notifications Allowed by your administrator' that is greyed out and can't be edited.
![Screenshot from 2021-06-08 15-35-06](https://user-images.githubusercontent.com/82603517/121206919-c2801b80-c870-11eb-8b3b-b2f394c7dd06.png)

### Versions
Cypress 7.3.0
Chrome 91

the test bellow fails and the browser notification pops up regardless....
```js
it('should trigger and block a notification', () => {
    cy.visit('/', {
      onBeforeLoad (win) {
        cy.stub(win.Notification, 'requestPermission').resolves('denied')
        cy.stub(win, 'Notification').as('Notification')
      }
    })   
  cy.get('#notification-button').click()  // some mechanism to trigger a notification
  cy.get('@Notification').should('not.have.been.called')  })
}
```

**Comment by bahmutov** [comment]
Take a look at our browser notification recipe https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/blogs__notification and the blog post explaining it https://www.cypress.io/blog/2020/01/24/testing-the-browser-notification-api/

**Comment by Techno-Disaster** [comment]
For some reason I am unable to allow notifications, the permission is always Ask (default) any idea why? @bahmutov 

![image](https://user-images.githubusercontent.com/52817235/128042143-71547a81-bc00-48a1-bc58-0c213f8892a2.png)
