### ISSUE TITLE
macOS trackpad back gesture doesn't work in cypress dashboard

### ISSUE THREAD

**Issue by matewka** [cypress-io/cypress#16850]
**Steps to reproduce:**

- Use a Mac device with a trackpad (I use MacBook Pro with macOS 10.15.7 Catalina)
- Use Chrome browser (my version is 90.0 but the problem is present for many versions)
- Go to any view in dashboard.cypress.io (e.g. /runs)
- Swipe 2 fingers left or right on the trackpad to perform a "history back" gesture (in trackpad settings it's called "Swipe between pages")

**Expected behavior:**
Browser history goes back or forth

**Actual behavior:**
Nothing happens

I didn't test this in different trackpad settings.
Other websites respect the gesture with no issues.

**Comment by CypressFinn** [comment]
Tracking in dashboard. OK to close this ticket @jennifer-shehane

**Comment by jennifer-shehane** [comment]
Hey @matewka, our Dashboard team is tracking this internally and have taken your comments into account. 

I will be closing this issue since this is related to our Dashboard and not the Test Runner and we want to make sure any feedback gets seen and addressed by the right team. Thanks!
