### ISSUE TITLE
High CPU usage in Cypress

### ISSUE THREAD

**Issue by dbonilla3197** [cypress-io/cypress#16864]
**Current behavior**
When I run tests in cypress the CPU usage is is at the top of 100%.

For example, running 3 test cases at the same time

Video:
https://user-images.githubusercontent.com/59613252/121283246-09cdd280-c898-11eb-8f88-d21edafb1a5a.mp4

Screenshot CPU result:
![image](https://user-images.githubusercontent.com/59613252/121283293-16eac180-c898-11eb-9063-54284625c28b.png)

Also, you can see how the behavior of the CPU changes while the cypress processes are running

https://user-images.githubusercontent.com/59613252/121283464-66c98880-c898-11eb-8a19-9c564d14aa5f.mp4

**Desired behavior**
The CPU usage of Cypress Helper should be under 100%

 **Test code to reproduce**
I am using threads with node.js to run different test cases at the same time

`cypress
  .run({
    browser: 'chrome',
    headless: true,
    spec: './cypress/integration/examples/login.spec.js',
  })
  .then((results) => {
    serverResponse(results);
  })
  .catch((err) => { console.log(err) })`

**Versions**
Cypress: 7.4.0
Windows 10
Node version: 14.17.0

**Comment by jennifer-shehane** [comment]
We don't recommend running multiple instances of Cypress on a single machine for this exact reason. This is essentially opening 3 instances of Cypress, 3 instances of the browser running tests through your application, and any other server resources required to run also. Most machines would not have the resources to run all of these things simultaneously and still be performant. 

See our [parallelization](https://on.cypress.io/parallelization) and [continuous integration](https://docs.cypress.io/guides/continuous-integration/introduction) guides on some recommendations on splitting up your run across several virtual machines.
