### ISSUE TITLE
Problems with cypress 7.5.0 & @cyprss/react and 'uncaught:exception' handling

### ISSUE THREAD

**Issue by glomotion** [cypress-io/cypress#16868]
### Current behavior

REPRO: https://github.com/glomotion/cypress-bug-repro

When running headless tests WITH coverage enabled, cypress errors out (`npm run test`)

![Screen Shot 2021-06-09 at 6 13 39 pm](https://user-images.githubusercontent.com/1452237/121318262-6e4b6900-c94e-11eb-803a-32fd8e515f16.png)

However when running headed or with coverage DISABLED, cypress tests pass as they should (`npm run test:fast` or `npm run test:watch`)

![Screen Shot 2021-06-09 at 6 17 08 pm](https://user-images.githubusercontent.com/1452237/121318817-f2055580-c94e-11eb-8109-ba8cad2b1f7a.png)

### Desired behavior

Tests should pass in all modes or fail in all modes 🤪  🤷 

### Test code to reproduce

REPRO: https://github.com/glomotion/cypress-bug-repro

NOTE: these tests are using 'uncaught:exception' to catch runtime errors, and assert that they are happening correctly. EG:
```typescript
before(() => {
    Cypress.on('uncaught:exception', () => {
      // returning false here prevents Cypress from
      // failing the test
      return false;
    });
  });

it('should throw error, when a fragment is supplied as children', done => {
    cy.on('uncaught:exception', err => {
      expect(err.message).to.include(ERROR_TEXT);
      done();
      return false;
    });
    mount(
      <AppHeaderBarNavItem testId="nav1">
        <>moo</>
      </AppHeaderBarNavItem>,
    );
  });
```

### Versions
MacOS: 11.4 (20F71)
MacBook Pro (15-inch, 2019)
```json
  "@cypress/code-coverage": "^3.9.6",
  "@cypress/react": "^5.9.1",
  "@cypress/webpack-dev-server": "^1.3.1",
  "cypress": "^7.5.0",
  "cypress-real-events": "^1.5.0",
```

**Comment by bahmutov** [comment]
I looked at the situation, something is wrong because when the error is thrown Cypress CT tries to mount the component _again_ causing the problem. You can find my simplified test in https://github.com/bahmutov/double-error-bug

- npm install
- npm run test:watch

I am printing the log message before throwing the error

```js
if (
    typeof children === 'string' ||
    isReactFragment(children) ||
    !isChildReactComponent(children)
  ) {
    console.error('App throwing an error')
    throw Error(ERROR_TEXT);
  }
```

I see the double log message in the console, which is incorrect

<img width="1281" alt="Screen Shot 2021-06-09 at 9 44 50 AM" src="https://user-images.githubusercontent.com/2212006/121366552-92378c00-c907-11eb-8e33-de8177813bd0.png">

**Comment by bahmutov** [comment]
By the way, we have error message tests for E2E here https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__errors

**Comment by lmiller1990** [comment]
I think we fixed error propagation as part of CT Stack Traces: https://github.com/cypress-io/cypress/pull/23916

Should be 💯 now.
