### ISSUE TITLE
Download folder is not showing while Running in Linux 

### ISSUE THREAD

**Issue by Animeshkr29** [cypress-io/cypress#16875]
Issue : Download Folder not created in when running Cypress with Linux with Docker 

i am trying to run Cypress code in Pipeline Job in Jinkins with Docker Image 
with the recent 7.5.0 Cypress , 

i notice when ever i am downloading any file and later i am trying to read its Showing 

> ENOENT: no such file or directory, open '/cypress/download/XYZ_1234.xlsx'

But while Running locally in Windows 10 its working as expected for any Browser . 

i am running Jenkins with 

npx cypress run --reporter mochawesome --env grepTags=${params.Tags} --spec cypress/integration/${params.Spec_Files} --browser ${params.Browser} --headed

**Comment by jennifer-shehane** [comment]
@Animeshkr29 Can you pull down and run our 'download' examples in your image? See if those tests pass. That would narrow down some variables. https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download

**Comment by Animeshkr29** [comment]
Thanks for reply , this Looks like Product issue in my Project .
Download is working expected in Linux box
