### ISSUE TITLE
Last assertion in a series of assertions is always failing in some cases

### ISSUE THREAD

**Issue by anshap1719** [cypress-io/cypress#16872]
### Current behavior
We have a series of assertions that call `should('not.exist')` on certain elements. When we do this, the last one always fails. I have tested this in multiple scenarios, which you can find in the below sections.

### Desired behavior
It should not fail. I searched for the string based on which we are getting the element in the dom tree when tests are running and can confirm that it doesn't exist anywhere.

### Test code to reproduce
We have the following command that we use in almost all places.
```js
Cypress.Commands.add('testClass', className => {
    return cy.get(`[data-test-class="${className}"]`);
});
```

In all the following cases of assertions in series, the test fails at the last one:
```js
cy.testClass('class1').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class3').should('not.exist');
```
```js
cy.testClass('class1').should('not.exist');
cy.testClass('class2').should('not.exist');
```
```js
cy.testClass('class1').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class2').should('not.exist');
cy.testClass('class3').should('not.exist');
```

### Versions

Cypress: v7.4.0 & v7.5.0
Test Browser: Chrome 91

Also, the same issue happens when using both `cypress open` or `cypress run`.

**Comment by jennifer-shehane** [comment]
@anshap1719 Can you provide the generated HTML to run these tests against? Or provide a repo to run the tests against? I can't recreate this issue as is. 

Is the element present on the page and then is removed from the page? Will need more info to track down why this is happening.

**Comment by mauricioszabo** [comment]
I'm having the same problem. The element is present, then removed from the page asynchronously. Seems that `cy.get(<something>).should('not.exist')` is not retrying when it finds the element on the page...
