### ISSUE TITLE
Correct type definition for `ThenReturn`

### ISSUE THREAD

**Issue by whatasoda** [cypress-io/cypress#16871]
### Current behavior

If I have a util to get page content data like:
```ts
const getListItems = <T>(transform: (items: string[]) => T) => {
  const items: string[] = [];
  return cy
    .get('li')
    .each((elem) => {
      items.push(elem.text());
    })
    .then(() => {
      return transform(items);
    });
};
```
and if I use the util like:
```ts
const items = getListItems<string[][]>((items) => {
  return items.map((item) => item.split(''));
});
```
then the returned chainable has type `T | JQuery<HTMLElement>` (= `string[][] | JQuery<HTMLElement>` in this example).
```ts
items.should((items) => {
  items; // Its type is `string[][] | JQuery<HTMLElement>`
});
```

### Desired behavior

The retuned chainable should have type just `T` (= `string[][]` in this example).

It's because [`ThenReturn`](https://github.com/cypress-io/cypress/blob/8c9c02e1d3263088929eb1a37d609e74fceeba9a/cli/types/cypress.d.ts#L547-L550) has a problem.
```ts
type ThenReturn<S, R> =
    R extends void ? Chainable<S> :
    R extends R | undefined ? Chainable<S | Exclude<R, undefined>> :
    Chainable<S>
```

The point is the third line. `R extends R | undefined` should be `undefined extends R`. `R` can be assigned to `R | undefined` regardless `R` includes `undefined` or not, whereas `undefined` cannot be assigned to `R` unless `R` includes `undefined`.

So `cli/types/cypress.d.ts#L547-L550` should be like:
```ts
type ThenReturn<S, R> =
    R extends void ? Chainable<S> :
    undefined extends R ? Chainable<S | Exclude<R, undefined>> :
    Chainable<S>
```

Could you update it?

### Test code to reproduce

Plz see above

### Versions

I met this issue with `v6.0.0`, but the latest version also has the issue.
TypeScript version is `v3.9.6`

**Comment by sainthkh** [comment]
Sorry for the late reply.

I agree that the result is not satisfactory but it seems that it's the best at the moment. 

With the change, it breaks the code like below that uses jQuery functions:

```ts
const result = cy.get('foo').then(el => el.attr('foo'))
result // $ExpectType Chainable<JQuery<HTMLElement>> | Chainable<string | JQuery<HTMLElement>>
```

And it also doesn't solve your problem, too. 

```ts
const getListItems = <T>(transform: (items: string[]) => T) => {
  const items: string[] = [];
  return cy
    .get('li')
    .each((elem) => {
      items.push(elem.text());
    })
    .then(() => {
      return transform(items);
    });
};

const items = getListItems<string[][]>((items) => {
  return items.map((item) => item.split(''));
});

items.should((items) => {
  items; // $ExpectType Chainable<JQuery<HTMLElement>>
  // It's not string[][]
});
```

I checked the code and it's `Chainable<JQuery<HTMLElement>>`, not `string[][]`.

**Comment by whatasoda** [comment]
Sorry for late response.

Thank you for explaining. If it may break something, it's fine keeping it as it is to me. I'm still able to solve issue of my use case by casting its type.
