### ISSUE TITLE
Spec files ran in single shot should be using the same mocha runner and reporter

### ISSUE THREAD

**Issue by meetmangukiya** [cypress-io/cypress#16874]
### Current behavior

If you run the whole cypress test suite with `cypress run` it will creates a new `Mocha.Runner` and / or new `Reporter` instance for each spec file.

### Desired behavior

All the spec files should be ran with same runner and reporter instance so reporters can summarize / report on all spec results at the same time.

### Versions

```
meet@Meets-Mac-mini ~/d/f/t/web-app (cypress/ci) [SIGINT]> npx cypress version
Cypress package version: 7.5.0
Cypress binary version: 7.5.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1
```

### My digging so far

I believe this is the reason why `mocha-junit-reporter` also requires to use a file name including `[hash]` because a new reporter is being constructed for each spec leading to next spec run overwriting the previous run's results but the reporter works fine for mocha tests when multiple test files / suites / specs are ran.

This behavior is effectively probably breaking functionality of any reporter using `EVENT_RUN_BEGIN` and `EVENT_RUN_END` events. So if you want to be doing something only once at start or end(like writing the report out as junit style xml, or reporting the results to an external source like testrail) can no longer be done, or can be done but not _correctly_ since you will be acting as "before each spec" instead of "before all".

---

This also sounds related -- https://github.com/cypress-io/cypress/discussions/16870
`cypress run` should run all the specs in same runner. 

If browser is launched and stopped for each spec, i believe it will fire 
https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/packages/runner/src/lib/event-manager.js#L346
for each run, leading to https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/packages/server/lib/project-base.ts#L356-L372 being called for each spec, leading to creating a new mocha runner for each spec
https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/packages/server/lib/reporter.js#L275-L277

---

https://github.com/cypress-io/cypress/blob/c340befb5a9134279d3febc3ef0bb0dea229b3be/packages/server/lib/modes/run.js#L1484
this condition seems like it will always be true leading to relaunching of browser for each spec? Since it is explicitly set for e2e aka integration tests, is there any reason for it? Or can we flip the condition?

Also possible that my drill down might be incorrect and i followed the wrong flow.

**Comment by jennifer-shehane** [comment]
For context: https://github.com/cypress-io/cypress/issues/1824 and https://github.com/cypress-io/cypress/issues/1946

I think running specs in parallel across several machines would be the challenge here.

**Comment by meetmangukiya** [comment]
Not sure how parallel across machines is working. But shouldn't the central / master still be able to emit out the events to the reporter on the master node that is if the reporting in parallel mode happens or gets aggregated in the master node. Only reporters that don't work well with parallel mode in mocha are the ones like `progress` because of the nature and it simply not being possible, but other reporters which are just interested in the end results should still be able to process and work in parallel mode, the tricky thing here is possibly the several machines thing but I am guessing there already has to be stuff for aggregating results?

**Comment by jennifer-shehane** [comment]
@meetmangukiya For several machines, we have a way to communicate and aggregate results to the Cypress dashboard specifically. There's nothing communicating for all of the specific reporters. For people using custom reporters, they usually generate several reports for each spec file and combine them on their own.

**Comment by meetmangukiya** [comment]
I see, cool. I think then maybe when the results reach the cypress dashboard, if the dashboard can instantiate the reporters and emit relevant events, it can work? instead of passing the reporters to the mocha runner and mocha emitting the events to the reporters, we could be mocking that behavior at the dashboard to get same results?
