### ISSUE TITLE
Allow global `@alias` values + Allow `cy.intercept()` to accept `@alias` as a first parameter

### ISSUE THREAD

**Issue by SergeyVolynkin** [cypress-io/cypress#16882]
### What would you like?
Allow `cy.intercept()` to accept `@alias` as a first parameter

For example:
```js
    cy.intercept('graphql?opname=createUser').as('createUser');
    cy.intercept('@createUser', mockResponse);
```

### Why is this needed?
This will create a unified interface to handle requests

Imagine the following scenario:
```js
    // file apiInterceptors.js

    /* Initialize interceptors once */
    cy.intercept('graphql?opname=createUser').as('createUser');
    cy.intercept('graphql?opname=deleteUser').as('deleteUser');
    cy.intercept('graphql?opname=updateUser').as('updateUser');
```
```js
    // somewhere in createUserView.spec.js

    /* Use Across the test suite */
    cy.intercept('@createUser', mockResponse);
```

```js
    // somewhere in updateUserView.spec.js

    /* Use Across the test suite */
    cy.wait('updateUser')
```

**Comment by SergeyVolynkin** [comment]
@bahmutov, if you have a few min., what do you think?

**Comment by jennifer-shehane** [comment]
@SergeyVolynkin Can you explain the scenario you're trying to test with `cy.intercept()` and the code you have to currently write to achieve this? I'd like to better understand the original case you're suggesting to optimize. Thanks!

**Comment by sainthkh** [comment]
Closing because of the inactivity.
