### ISSUE TITLE
Chaining Elements into an arary

### ISSUE THREAD

**Issue by praveenngp15** [cypress-io/cypress#16887]
How to find chaining elements in cypress

There is a table,
```js
cy.get('tbody tr').each(($el, index, $list) => { //It is returning 5 elements
// In every row we have 5 columns. Need to get the text of five column and store it in map
    /*In protractor i used below code*/
    Subelement of ele
    ele.element(by.tagName('tag-within-css')).getText();
})
```

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
