### ISSUE TITLE
How to push all elements texts into an array or map

### ISSUE THREAD

**Issue by praveenngp15** [cypress-io/cypress#16886]
How to push all the elements texts into an array
/My code for printing data code/
```js
cy.get('tbody tr:nth-child(2) td').each(($el, index, $list) => {
cy.log($el.text())
})
```
I tried with the below code but it is throwing an error
```js
cy.get('tbody tr:nth-child(2) td').each(($el, index, $list) => {
letTextForArray.push($el.text())
})
```

**Comment by thomassjogren** [comment]
Please provide the error. Might be good to state why you want to do it and what you trying to accomplish as it helps trying to solve the problem.

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
