### ISSUE TITLE
Support scrollBehavior option in scrollIntoView() to control position of scroll

### ISSUE THREAD

**Issue by JessefSpecialisterren** [cypress-io/cypress#16895]
### Current behavior

Let me start by saying that the new `scrollBehavior` option is awesome and a very welcome addition to Cypress 😄! It really helps to avoid elements getting scrolled under sticky menu bars and the like

However, Cypress' `scrollIntoView()` command does not seem to obey or support the `scrollBehavior` option. In fact, it does not appear to offer any option to reliably scroll an element to the center or bottom of the viewport

### Desired behavior

Cypress' `scrollIntoView()` should support the `scrollBehavior` option, whether passed in the `options` argument or part of the current configuration

### Test code to reproduce

scrollBehavior.html:
```html
<body style="height: 200vh; padding-top: 120vh;">
    <div style="background-color: brown; position: fixed; top: 0px; left: 0px; width: 100%; height: 30px; margin-left: 0px;"></div>
    <span style="font-size: 50px;">Hello</span>
</body>
```
scrollBehavior.spec.js:
```js
it('scrollBehavior center', { scrollBehavior: 'center' }, () => {
  cy.visit('scrollBehavior.html')
  cy.get('span')
    .pause()
    // This ignores the scrollBehavior specified for this test
    .scrollIntoView()
    // This, on the other hand, obeys it
    .click()
})
```

### Versions

Cypress 7.5.0
Google Chrome 91
Windows 10

**Comment by jennifer-shehane** [comment]
Since this feature request hasn’t gotten a lot of interest over the years, we’ll close this issue.
