### ISSUE TITLE
Does not wait on XHR request

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#169]
Seems we cannot intercept server request with search parameters like
```
GET <server>/api/v1/foo/bar?a=42
```
Tried different regular expressions when setting the `server().route('GET', ...)` without success, using Cypress 0.16.2

**Comment by brian-mann** [comment]
this works for me...

```javascript
cy
      .server()
      .route(/api/, []).as("getApi")
      .visit("/index.html")
      .window().then(function(win){
        var xhr = new win.XMLHttpRequest
        xhr.open("GET", "/api/v1/foo/bar?a=42")
        xhr.send()
      })
      .wait("@getApi")
        .its("url").should("include", "api/v1/foo/bar")
```

**Comment by brian-mann** [comment]
In `0.16.3` we have added support for glob patterns via `minimatch`. So you can more easily use strings to match dynamic route segments.

**Comment by brian-mann** [comment]
Closing this as I'm pretty sure this wasn't ever a bug.
