### ISSUE TITLE
Had to manually force install on Windows

### ISSUE THREAD

**Issue by pdevito3** [cypress-io/cypress#16901]
### Current behavior
When doing an install for the first time, I followed the instructions [here](https://docs.cypress.io/guides/getting-started/installing-cypress#npm-install) (1. run `npm i cypress --save-dev` in a react project with `node_modules` and `package.json`, 2. run `./node_modules/.bin/cypress open`)

I had cypress at that node modules path, but it didn't run the installer when i did the `npm install`, so i get the below error when trying to open it. 

Once I ran `npx cypress install --force` (didn't work without force), it ran the install and I was able to open it

### Debug logs
```shell

It looks like this is your first time using Cypress: 7.5.0


Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------



#
# Fatal error in , line 0
#
#
#
#FailureMessage Object: 0000001CA732ED70
1: 00007FF74BD1BCCF node::OnFatalError+69935
2: 00007FF746B8E6CA Ordinal0+59082
3: 00007FF74713CEC8 v8::Isolate::Initialize+744
4: 00007FF747BFD48F v8::Isolate::AddMessageListenerWithErrorLevel+1039
5: 00007FF74A767583 std::__1::vector<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProfileDeoptInfo> >::max_size+856: 00007FF74A75F89B std::__1::vector<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProfileDeoptInfo> >::max_size+825835
7: 00007FF74B16A382 v8_inspector::protocol::Binary::operator=+2434098
8: 00007FF74B16DC29 v8_inspector::protocol::Binary::operator=+2448601
9: 00007FF74B169E12 v8_inspector::protocol::Binary::operator=+2432706
10: 00007FF74AE8B2D0 v8::ExtensionConfiguration::ExtensionConfiguration+2964624
11: 00007FF74AE8AEEA v8::ExtensionConfiguration::ExtensionConfiguration+2963626
12: 00007FF74AE89E57 v8::ExtensionConfiguration::ExtensionConfiguration+2959383
13: 00007FF74AE8A17D v8::ExtensionConfiguration::ExtensionConfiguration+2960189
14: 00007FF74A693167 uv_sleep+2434663
15: 00007FF74D0CFF02 uv_random+10012786
16: 00007FFBF51A6FD4 BaseThreadInitThunk+20
17: 00007FFBF5BBCEC1 RtlUserThreadStart+33

----------

Platform: win32 (10.0.19041)
```

### Download method
node 14.17, npm 7.13.0

- [x] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
Win10 10.0.19041

- [ ] Linux
- [ ] Mac
- [x] Windows

### Other

- [x - 7.5.0 atm] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by pdevito3** [comment]
that could be it for me. this is my corporate comp that i do have pretty good flexibility on privilege wise, but could have some underlying stuff like that in play regardless. let me know if there's something you'd like me to check for this.

regardless, might be worth a note in the docs that calls out if you don't see the install happening after the normal npm install that you might need to manually run the above

**Comment by jennifer-shehane** [comment]
Actually, I don't think `npm install --force` seems relevant in terms of Windows perms. This would just have all the packages re-downloaded and re-installed. 

From my understanding, it's forcing redownload of cypress and all child dependencies. So I think there must have been some conflict with the original deps - where it wasn't downloading a child dep originally without this flag.

I'd like to more clearly understand why this is necessary before recommending it as a broad solution in the docs. 

I also feel like this error is too generic. I see it often for different reasons that don't ever seem clearly described in this error.

**Comment by Yohandah** [comment]
I have currently the same issue.
