### ISSUE TITLE
Cypress never exits on infinite loops in the browser

### ISSUE THREAD

**Issue by sharmilajesupaul** [cypress-io/cypress#16903]
### Current behavior
On an infinite loop in the browser (from the app or in test code), the Cypress test runner, in both "open" & "run" mode, will hang indefinitely. We lose any kind of test state reporting, there are no errors logged or videos or screenshots for an extended period of time (over an hour).

Some context: Cypress caught a bug at Airbnb where a change introduced an infinite loop in the browser (yay!). However, the user experience around triaging this issue not clear or helpful and required us to extensively debug. 

The behavior prompted us to add a timeout to kill off Cypress processes to prevent jobs hanging on similar issues. 

### Desired behavior
Cypress should detect infinite loops and fail the test / exit the process with information about why the process was exited.

In Jest, as a comparison, it can't continue garbage collection anymore & jest will crash in ~2mins. Which is still better because the process will end & outputs useful information about what happened.
```
❯ yarn jest tests/infinite.test.ts

 RUNS  tests/infinite.test.ts

<--- Last few GCs --->

[58983:0x110008000]   112018 ms: Mark-sweep 4094.8 (4100.6) -> 4094.8 (4101.1) MB, 4442.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 4443 ms) (average mu = 0.075, current mu = 0.000) allocat[58983:0x110008000]   116395 ms: Mark-sweep 4095.7 (4101.1) -> 4095.3 (4101.3) MB, 4334.2 / 0.0 ms  (+ 39.5 ms in 13 steps since start of marking, biggest step 9.1 ms, walltime since start of marking 4377 ms) (average mu = 0.039, current mu = 0.001) alloc

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x10097d5b9]
    1: StubFrame [pc: 0x10090465b]
Security context: 0x2a89e7bc08d1 <JSObject>
    2: /* anonymous */ [0x2a89c8180169] [/node_modules/jest-mock/build/index.js:~382] [pc=0x565ac922b88](this=0x2a89b583fe89 <Console map = 0x2a89afd5b6e9>)
    3: arguments adaptor frame: 1->0
    4: mockConstructor [0x2a89c81801e1] [...
```

Obviously, Jest & Cypress are wildly different frameworks, but ideally, the Cypress NodeJS process would be able to detect and kill of tests if they either exceed a given timeout / chrome becomes unresponsive.

### Test code to reproduce
I would recommend running this wrapped in a timeout command of some sort i.e. `timeout 100 npx cypress run ...` 
```js
// cypress/integration/some-spec-file_spec.ts
describe('oh no' , () => {
   it('runs infinitely', () => {
    while(true) {}
  })
});
```

what I see:
```

==============================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    7.5.0                                                                              │
  │ Browser:    Chrome 91 (headless)                                                               │
  │ Specs:      1 found (playgroundApp.spec.ts)                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
Running:  playgroundApp.spec.ts                                                           (1 of 1) 
  oh no

```

& then, nothing else, for an extended period of time until you forcibly exit. In open mode the browser will become unresponsive.

To recreate the same thing with a browser page that has infinite loop, set your base url to `https://jsfiddle.net` and then run this test: 
```js
describe('Infinite loop', () => {
  it('runs the fiddle', () => {
    cy.visit('/xspqo2kv');
    cy.contains('Run').click();
  });
});
```

Cypress will visit https://jsfiddle.net/xspqo2kv and hang indefinitely.

### Versions
Cypress Version: 6.6.0 & 7.5.0
Browser: Chrome 91
OS: Ubuntu 1804 (in docker) & MacOS Big Sur v11.4 (local)

**Comment by jennifer-shehane** [comment]
@sharmilajesupaul Thanks for the very clear reproducible examples. I can recreate this behavior of the cypress process running forever.

```js
it('runs infinite loop in fiddle', () => {
  cy.visit('https://jsfiddle.net/xspqo2kv')
  cy.contains('Run').click()
})
```

I would expect many CI processes to automatically exit upon receiving no signal after a period of time. CircleCI exits after 10 mins with no signal at least. 

I'm not sure how the team would want to handle this situation exactly, except that 'hanging' is not the desired behavior for the Test Runner.

**Comment by sharmilajesupaul** [comment]
Thanks @jennifer-shehane, you're right, the CI process reaching the timeout is what we experienced. The workaround on our end was making the timeout configurable & updating our default timeout which was 70mins -> 20mins for Cypress.

The confusion from the teams trying to debug this was the fact that there were no logs from Cypress indicating that anything went wrong. All we saw was tests stop running. The way they figured out It was an infinite loop was manually stepping through the code following the steps of the test.

I'm also curious to see what kind of solution you all propose.

**Comment by sharmilajesupaul** [comment]
@jennifer-shehane One interesting  point is that I tried to make this reproduction case with Codepen originally, see: https://codepen.io/airbnb/pen/GRWXapj. Unlike [JSFiddle](https://jsfiddle.net/xspqo2kv), Codepen was able to catch my infinite loop and stop the editor from running.

![Screen Shot 2021-06-11 at 11 04 41 AM](https://user-images.githubusercontent.com/7876997/121730644-d3b16e00-caa4-11eb-9e00-3cc150cb4060.png)

When we dug into why, it seems like this is because the iframe for the editor, is on a different domain (https://cdpn.io/airbnb/fullpage/GRWXapj vs https://codepen.io/airbnb/pen/GRWXapj). So this might be something you could take advantage of. This stackoverflow has more info on this too https://stackoverflow.com/a/51693715/5443327

cc. @ms

**Comment by sharmilajesupaul** [comment]
@jennifer-shehane Another idea that might be more cross browser compatible, is to use a plugin like this: https://github.com/jsbin/loop-protect
