### ISSUE TITLE
Automation command Page.printPDF simply says error

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#16900]
Cypress v7.5.0

I was trying to answer https://gitter.im/cypress-io/cypress?at=60c256b956df183c23097dd0

The test is trying to call `Page.printPDF` method using CDP automation https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF (note that `Page.captureScreenshot` is working fine)

```js
/// <reference types="../support" />

// check this file using TypeScript if available
// @ts-check

it('prints the page to PDF', { browser: '!firefox' }, () => {
  cy.visit('/')
  cy.get('.new-todo')
    .type('write Cypress tests{enter}')
    .type('use Cypress.automation{enter}')
    .type('???{enter}')
    .type('Profit!{enter}')

  cy.get('.todo-list li')
    .should('have.length', 4)
    .then(() => {
      // print the application to PDF
      // https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
      return Cypress.automation('remote:debugger:protocol', {
        command: 'Page.printToPDF',
        params: {
          transferMode: 'ReturnAsBase64',
        },
      })
    })
})
```

<img width="1298" alt="Screen Shot 2021-06-10 at 3 32 50 PM" src="https://user-images.githubusercontent.com/2212006/121586560-cdb68100-ca01-11eb-9120-85d190556c44.png">

Reproduction in https://github.com/bahmutov/cypress-grep-example/tree/add-print-spec

- git clone the repo
- `git checkout add-print-spec`
- `npm install`
- `npm run dev`
- pick the `print-spec.js`

**Comment by philippefutureboy** [comment]
@bahmutov Any update on this one? :)
Cheers!
