### ISSUE TITLE
Respond to 'cancel run' from Dashboard and cancel remaining specs

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1691]
New button to 'Cancel' run will be added to Dashboard, want to cancel the run and any remaining specs left to run. 

Cancel button (only displayed when running): 
![screen shot 2018-04-17 at 4 19 04 pm](https://user-images.githubusercontent.com/1271364/38894396-1cd69400-425b-11e8-8cb4-97ab169033fa.png)

API Issue: https://github.com/cypress-io/cypress-api/issues/455
Dashboard Issue: https://github.com/cypress-io/cypress-dashboard/issues/502

**Comment by Dygerati** [comment]
+1
I actually have a run now that's been "running" for 19 hours waiting for results. Not sure how I can remove it?

**Comment by jennifer-shehane** [comment]
Yes, this unfortunately didn't make it in 3.0, will be aiming for 3.1 release of this now. 

Deleting a run is also a feature. Opened an issue here for that: https://github.com/cypress-io/cypress/issues/1839

**Comment by jennifer-shehane** [comment]
@brian-mann TODO for run cancellation on test runner

- [ ] Test runner should expect 422 `RUN_CANCELLED` and 422 `INSTANCE_CANCELLED` (or whatever the API ends up sending and write specific error message: 
  >This run was cancelled by ...... at ...... To see the results of the run visit ....url
- [ ] When user cancels run in CI or when kills process locally -via `SIGKILL`, `SIGINT`, `SIGTERM` (or something) - could we send a request from the Test Runner to the API to do a `POST runs/id/cancel` to cancel the run - (may not have `cancelledBy` in this situation - so may be `null`)?

**Comment by jennifer-shehane** [comment]
@puneetiet Yes, this run cancellation not been released yet. If the run runs **longer** than 90 minutes, you should open a new issue because this should not happen.

**Comment by dafiber** [comment]
my tests are running in dashboard more than 22 hours now.. (version 3.2) how I can stop them?

**Comment by jennifer-shehane** [comment]
@dafiber This should never happen. If you can, please email extra details to support@cypress.io about your run.

**Comment by jorgeautomation** [comment]
Any news regarding the Cancel button? Thanks!

**Comment by DennisLoska** [comment]
My question is not 100% related, but is there a way to cancel a run/spec when using the Cypress module API? I have not found anything in the docs which would suggest that. I would like to be able to cancel a run with e.g. cy.cancel(), or do I need to run cypress in a Node child process and end the child process in order to end a running test?

**Comment by SUSANO-O** [comment]
holle How to remove test from the dashboard vesion 3.3.1?thanks

**Comment by jennifer-shehane** [comment]
@DennisLoska You may want to look at some of the workarounds in this issue: https://github.com/cypress-io/cypress/issues/518

@SUSANO-O This is not currently supported. See this issue: https://github.com/cypress-io/cypress/issues/1839

**Comment by jhays-nhaschools** [comment]
I don't know whether this is technically feasible, but if possible, it would be nice if cancelled runs still had video output.

**Comment by SUSANO-O** [comment]
hello good day there are examples of how to use window other than cypress documents, muchas gracias.

**Comment by rikumo** [comment]
Hi. Just I'm having same issue as @dafiber. How do I stop my spec file that has been running for a while now. The job has already failed in circleci. Or even a workaround for this would be appreciated. Thanks.

**Comment by ChaseBig** [comment]
Hello, any updates on this? @jennifer-shehane 

Or any feasible workarounds? 90% of my builds sit there still thinking tests are running even though they're not.

**Comment by jennifer-shehane** [comment]
JSON schemas changes to be tested against: https://github.com/cypress-io/json-schemas/pull/507

**Comment by namhuynhkien** [comment]
Hello,
We are facing problem that the tests keep running more than 90 minutes and still goes on. I already emailed for support but haven't received any response. 
In addition, we cannot run the tests as well.
Hope to hear from you soon.
