### ISSUE TITLE
Screenshot command creates new copies instead of replacing original image

### ISSUE THREAD

**Issue by Enzo-Parodi** [cypress-io/cypress#16921]
### Current behavior
Wheen using `cy.screenshot('screenshot-name')` I get new copies of the original image every time I run the tests:

![image](https://user-images.githubusercontent.com/37559641/121869322-3784a280-cd02-11eb-8133-4dc20209ff0e.png)

### Desired behavior
No new copies should be created, there should only one image per screenshot.

I suppose there may be some configuration that could change this that I couldn't find, but I actually don't think this is this expected default behaviour anyway.

Thanks in advance.

**Comment by jennifer-shehane** [comment]
@Enzo-Parodi How are you running the tests? via `cypress open` or `cypress run`? 

Below are the rules for clearing existing screenshots from https://on.cypress.io/screenshots-and-videos#Screenshots

>Cypress clears any existing screenshots before `cypress run`. If you do not want to clear your screenshots folder before a run, you can set `trashAssetsBeforeRuns` to `false`.

**Comment by Enzo-Parodi** [comment]
@jennifer-shehane thanks for the quick reply.

It seems that I was confused about the usage of snapshots, since they are not meant for diffing visual regressions. Instead, I am now using `cypress-plugin-snapshots`, and it work as expected.

It's clear from the docs that previous snapshots are only automatically erased with `cypress run`. I was using `cypress open`. 

Nothing to report then :)
