### ISSUE TITLE
cy.get('#seo\[\'description\'\]')

### ISSUE THREAD

**Issue by rasool-swipe** [cypress-io/cypress#16924]
### Current behavior
using this cy.get('#seo\[\'description\'\]')
and I get this error
Syntax error, unrecognized expression: #seo['description']

### Desired behavior
Just want to be able to select it. Tried using the selector playground, the actual ID, and ranorex and all of them produce the same error

### Test code to reproduce
        cy.get('#seo\[\'description\'\]')

**Comment by jennifer-shehane** [comment]
@rasool-swipe Could you provide the HTML of the DOM element you want to select? That would help in making a suggestion for how to query for it. Thanks!
