### ISSUE TITLE
Uncaught exception should not fail test inside beforeEach hooks 

### ISSUE THREAD

**Issue by AlexandreBonaventure** [cypress-io/cypress#16930]
### Current behavior

Since v7.0 uncaught exception in Promise are now failing tests per default.
When using cy.intercept(), it seems like the fetch requests connections are closed and can fire an uncaught:exception in the following test `beforeEach` hook

<img width="506" alt="Screen Shot 2021-06-14 at 2 24 53 PM" src="https://user-images.githubusercontent.com/4596409/121941281-0fef0380-cd1d-11eb-9097-bc0d855bad29.png">
<img width="1020" alt="Screen Shot 2021-06-14 at 2 27 21 PM" src="https://user-images.githubusercontent.com/4596409/121941742-a3c0cf80-cd1d-11eb-852e-2fcdadbfcfb6.png">

### Desired behavior
uncaught exceptions should not fail/listened to in the beforeEach hooks.

### Test code to reproduce
Our project is pretty big, so I'm still in the process of creating a minimal repro

### Versions
Since 7.0 and still present in following versions.

**Comment by jennifer-shehane** [comment]
A repro would be good. But yes, uncaught exceptions in promises now fail in 7.0. You can read more here, including workarounds: https://on.cypress.io/migration-guide#Uncaught-exception-and-unhandled-rejections

**Comment by AlexandreBonaventure** [comment]
Yes thanks and that's a good behaviour! 
For now I have this workaround: 
```js
let shouldIgnoreError = false;
Cypress.on('uncaught:exception', () => {
  if (shouldIgnoreError) return false;
});
Cypress.on('window:before:load', () => {
  shouldIgnoreError = false;
});
Cypress.on('test:before:run', () => {
  shouldIgnoreError = true;
});

```
