### ISSUE TITLE
Application throwing error in cypress but not on browser

### ISSUE THREAD

**Issue by fabpotato** [cypress-io/cypress#16938]
Hi Team, 

I am running a node js based application. And i am using cypress to perform automation on the same.
The application connects to two websockets. This behaviour works fine on browser. But when i attempt to run the same application in cypress I am getting error connecting to the second websocket:

Websocket connection to 'ws://<hostname>:<port>/' failed, connection closed before receiving a handshake response

Cypress version 4.1.0
Node version 12.16.1

**Comment by sainthkh** [comment]
Sorry for the late reply. 

As we all know, the first step to debug is to reproduce the error in the developer's local machine. Can you give us a reproducible example?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
