### ISSUE TITLE
Visited page leaks between tests

### ISSUE THREAD

**Issue by adarnon** [cypress-io/cypress#16935]
### Current behavior

Between tests, if `before/beforeEach` execute for a long time, the last visited page is still active, and behavior on that page might cause the next test to fail.

#### Explanation - real world context

We are developing a web app (Next.js) that requires users to log in. We use Auth0 for authentication, and then keep the user's token in a cookie that is transmitted to the server.
In order to make sure the current user's session is not expired, our app periodically calls an API route that verifies the client's access token is unexpired. If it is expired, the app redirects the user to the Auth0 login flow to re-login.

Because of Cypress cross-origin limitation, at the beginning of the tests we perform a login through `cy.request` and keep a signed cookie for the duration of the tests. The cookies get cleared between tests, and we load them into the browser before visiting a page that requires authentication.

Now for the flow:

* We have a test that finished running. The browser is still open on the last visited page
* Cypress starts running `before` for the next test. It clears the browser's cookies
* The open web app decides to check if the user's session is still valid. It sends a request, which fails (because cookies have been cleared). So the web app decides to redirect to Auth0 login form
* Cypress errors with a cross-origin problem

Here is a sequence of screenshots:

New test suite if running `before`, but the previous browser state is still visible.

![image](https://user-images.githubusercontent.com/5649771/121981217-1c398780-cd42-11eb-8308-255ccd841c26.png)

We got redirected to Auth0.

![image](https://user-images.githubusercontent.com/5649771/121981145-01ffa980-cd42-11eb-8252-301f938cbf68.png)

### Desired behavior

I think that when a new test suite starts, the previous state of the browser shouldn't still be active. And certainly browser actions shouldn't impact the result of the new test suite.

### Test code to reproduce

I created a reproduction in Cypress RWA that shows how the previous page stays loaded if the `before` block takes a long time to execute.

You can run the test `tests/ui/notifications.spec.ts` and see what happens when cypress moves from the first `describe()` block to the second.

https://github.com/adarnon/cypress-before-wait

### Versions

Cypress version: 6.9.1, 7.5.0.
This error occurred on Ubuntu 20.04, Electron 87. But it also statistically reproduces locally on MacOS Big Sur & Chrome 91.

**Comment by jennifer-shehane** [comment]
@adarnon I have seen people report similar sounding issues in terms of their app 'logging out' unexpectedly after a test and this explanation makes sense. 

Is the provided test case meant to fail? When I run the test case it passes. Is the issue intermittent? Can you provide a failing test case?

**Comment by adarnon** [comment]
I actually want the app to log out after the test. The problem is that the app page stays loaded and active even after the `before/beforeEach` clauses for the next test start running, instead of clearing the page.

I have updated the test to be more clear. As you can see, the second `describe()` clause has a 20 second wait on `before()`. While this is happening, the app page from previous test issues a redirect that makes the test fail.

**Comment by jennifer-shehane** [comment]
K, I've simplified the example where the application can still trigger side effects in the 'before' of the next spec.

### Reproducible Example

`spec.js`

```js
describe('tests', () => {
  it('test', () => {
    cy.visit('index.html')
    cy.get('button').click()
  })
})

describe('more tests', () => {
  before(() => {
    cy.wait(10000)
  })

  it('test', () => {
    // we expect to still be on the page 
    // (in real world, maybe still logged into the app)
    cy.url().should('eq', 'index.html')
  })
})
```

`index.html`

```htmtl
<html>
<body>
  <button id='button'>Create Side Effect</button>
  <script>
    document.getElementById('button').onclick = () => {
      setTimeout(() => {
        window.location.assign("https://www.google.com")
      }, 5000);
    }
  </script>
</body>
</html>
```

<img width="1252" alt="Screen Shot 2021-06-15 at 2 13 44 PM" src="https://user-images.githubusercontent.com/1271364/122110235-ed73ed80-cde3-11eb-985e-12f42f60c510.png">

**Comment by adarnon** [comment]
Thanks for making the simplified version :) in your version, I'd expect the test to fail during `before()` on cross-origin frame - that's what happens in the repro I created.

I think the solution should be to clear the page from the previous test before running `before()`, instead of preventing redirects or anything of that sort.

Even if the second test starts with `cy.visit('/')`, currently Cypress would issue a cross-origin frame error before that happens.

**Comment by jamos99** [comment]
I think we are noticing this as well. Intermittent failures in specs that immediately follow a spec with some kind of redirect in it. We reset our stub server before each test via a global beforeEach, and the preceding redirect test ends up trying to fire off a request with a now invalid csrf token, resulting in our error page showing. Waiting for an arbitrary amount of time at the end of the redirect test, or clearing the page with a visit to an empty page in between seems to alleviate it, but is clearly undesirable.

**Comment by jennifer-shehane** [comment]
I feel like reports of this have been coming up more recently, so I wonder if there's something that recently changed in the Test Runner that is making these cases more frequent.

**Comment by jamos99** [comment]
@jennifer-shehane have you got links to the other issues that might be related handy? Keen to look into it further. We've resorted to adding waits to our redirect tests increasing total build time significantly - wondering if this might be tagged as a regression of it was a specific version that introduced it?

**Comment by PunkeroAlpha** [comment]
@adarnon @jennifer-shehane did you find any workaround for this?

**Comment by adarnon** [comment]
@PunkeroAlpha We just adapted our test config so the redirect doesn't happen for now

**Comment by jennifer-shehane** [comment]
A workaround for this that I think would work today is a bit sideways, but with our new `experimentalSessionSupport` feature, Cypress will visit `about:blank` in between every single test case. I believe that turning this feature on globally (or for the affected spec) may solve this issue. Can anyone try this out and report if this is the case?

Please make sure to read about [`cy.session`](https://on.cypress.io/session) and what it does before making those updates.

**Comment by bahmutov** [comment]
You can visit a blank page even without the session experiment https://glebbahmutov.com/blog/visit-blank-page-between-tests/

**Comment by PunkeroAlpha** [comment]
It seems to work fine, much obliged @jennifer-shehane  @badeball

**Comment by emilyrohrbough** [comment]
In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation) to prevent cases like this.
There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is on, before each test, Cypress will:

- clear the page by visiting about blank
- clear cookies
- clear local storage
- clear browser storage

This will prevent DOM and browser state bleed over between tests. The [`cy.session()`](https://docs.cypress.io/api/commands/session) command can be leveraged to save and cache shared browser contexts.

If it is desired to persist DOM and browser state between a set of tests, you will be able to turn test isolation off for the run or at the suite level.

Above you described needing to login at the beginning to work around the cross-domain constraints in Cypress. In v12.0.0 we will also be release [`cy.origin()`](https://docs.cypress.io/api/commands/origin) which enables testing multiple origins within a single test.

Closing this issue as done and tagging for the v12.0.0 release.
