### ISSUE TITLE
(uncaught exception)TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by SriQA1** [cypress-io/cypress#16932]
Hi All,

I am new to Cypress and this forum.
can somebody take a look at this error below, I get this when I am trying to do drag and drop via cypress
In other words trying to drop a file from the fixture folder into the drop zone in my application.

```
(uncaught exception)TypeError: Cannot read property 'name' of null
```

this is my code snippet

```js
cy.xpath('//div[contains(text(),&quot;Drag files here to upload&quot;)]')
.attachFile(filename,  {subjectType: &quot;drag-n-drop&quot;});
```

Note:
It recognizes the drop zone even initiates the upload but then the exception occurs and no upload happens.

I did try by giving the File Content directly

```js
Cypress.Commands.add('upload_file', (selector, fileUrl, type = '') => {
    return cy.fixture(fileUrl, 'base64')
      .then(Cypress.Blob.base64StringToBlob)
      .then(blob => {
        const nameSegments = fileUrl.split('/')
        const name = nameSegments[nameSegments.length - 1]
        cy.log(name)
        const testFile = new File([blob], name, { type })
        cy.log(testFile)
        const event = { dataTransfer: { files: [name] } }
        return cy.xpath(selector).trigger('drop', event)
      })
  });
```

But then I see this error `(uncaught exception)Invariant Violation: Cannot call hover while not dragging`

**Comment by jennifer-shehane** [comment]
It sounds like this error is being thrown from you application code. This doesn't seem like a bug from the information given exactly. We'd need a reproducible example to show it is a bug - if you can provide one we can run.

You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
