### ISSUE TITLE
Launch in clean chrome window with no sidebar or background

### ISSUE THREAD

**Issue by oneillsp96** [cypress-io/cypress#1694]
Cypress is a beautiful tool for being able to access and test the various error states in my UI using JSON fixtures, but it's hard to use it for subsequent CSS changes because I can't view the page/window at a normal size, and I can't resize it to see how my changes look at various screen sizes.  This is the only thing preventing me from using Cypress all the time while I'm developing.  Could we implement a config option to launch the app as a user would actually see it?  Maybe use a favicon/title/ some kind of small watermark to distinguish it from our actual app?

**Comment by jennifer-shehane** [comment]
Yeah, we have played with having a fullscreen view - where the command log can be separated into another window from the application under test. Our initial use case for this was for on mobile, but this is a good use case too. I am also sometimes frustrated with not being able to change the screen size quickly. I wonder if we could make that at least a dropdown to configure from the test runner.

**Comment by oneillsp96** [comment]
Any tips/ starting place if I were to try tackling this in a PR?

**Comment by jennifer-shehane** [comment]
Oh boy, I'd have to go on a scavenger hunt to find where this used to be/should be. Maybe @chrisbreiding has some idea?

**Comment by jennifer-shehane** [comment]
You can hide the Command Log sidebar with the following OS env var `CYPRESS_NO_COMMAND_LOG=1`

```
CYPRESS_NO_COMMAND_LOG=1 cypress run
```
