### ISSUE TITLE
cypress load tests twice at startup

### ISSUE THREAD

**Issue by alexneo2003** [cypress-io/cypress#16958]
### Current behavior

When cypress start spec tests it reload spec and run tests second time
**Steps:**
1. start launcher 
2. launcher load spec tests and execute 'beforeEach' hook
3. launcher load spec tests at SECOND time and execute 'beforeEach' hook at SECOND time
4. launcher run tests

This moment can be seen in video at third second
https://user-images.githubusercontent.com/11705902/122227682-c854ad00-cebf-11eb-88b8-5ce4c4cf63a5.mp4

In my case i'm using precondition task which execute from 'before' hook 
Because of hook executes twice one by one - API requests call twice and it brock precondition task

### Desired behavior
At startup cypress load tests only ONE times and all before hooks run only ONE time

### Test code to reproduce
init new project and run
```
npx @bahmutov/cly init
cypress run or cypress open
```

### Versions
cypress info

Displaying Cypress info...

Detected 3 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 91.0.4472.106
  - Executable: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  - Profile: C:\Users\Alex\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable

2. Edge
  - Name: edge
  - Channel: stable
  - Version: 91.0.864.48
  - Executable: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
  - Profile: C:\Users\Alex\AppData\Roaming\Cypress\cy\production\browsers\edge-stable

3. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 89.0.0.7817
  - Executable: C:\Program Files (x86)\Mozilla Firefox\firefox.exe
  - Profile: C:\Users\Alex\AppData\Roaming\Cypress\cy\production\browsers\firefox-stable
 
Cypress Version: 7.3.0
System Platform: win32 (10.0.19043)
System Memory: 8.45 GB free 1.27 GB

**Comment by alexneo2003** [comment]
ok
i'm defined 'baseUrl' at cypress.json and have same issue
![image](https://user-images.githubusercontent.com/11705902/122238772-115d2f00-cec9-11eb-96cf-d5b0bbcf4c1f.png)

at video

https://user-images.githubusercontent.com/11705902/122238865-29cd4980-cec9-11eb-9670-15b2c3524ca0.mp4

**Comment by jennifer-shehane** [comment]
This is reloading due to the 301 redirect that occurs during the visit. You're visiting `http://todomvc.com/examples/vue`, which then redirects to the `https` url -> `https://todomvc.com/examples/vue`.

Any time the application under test is navigating to a new domain, the main url of the Cypress browser needs to update to reflect this. The reasons why are explained in https://on.cypress.io/web-security

Try updating your baseUrl to `https://todomvc.com/examples/vue` to avoid the reload on the 301 navigation.
