### ISSUE TITLE
type() doesn't work with Cyrillic 

### ISSUE THREAD

**Issue by Viktor-Rus** [cypress-io/cypress#16953]
I try to print text in input
Cypress works with Latin 
![Снимок экрана 2021-06-16 в 10 18 59](https://user-images.githubusercontent.com/41300396/122175972-c1f90d80-ce8c-11eb-8406-039f63afc933.png)

But doesn't work with  Cyrillic
![Снимок экрана 2021-06-16 в 10 20 14](https://user-images.githubusercontent.com/41300396/122176173-fe2c6e00-ce8c-11eb-995f-1070090b24f6.png)

**Comment by bahmutov** [comment]
I have added Cyrillic example here which works fine
https://github.com/bahmutov/cypress-examples/commit/09aec67de260858c63f746de1d051e3f8b5d1f0e 

I think we would need a reproducible example to debug this

**Comment by Viktor-Rus** [comment]
> I have added Cyrillic example here which works fine
> [bahmutov/cypress-examples@09aec67](https://github.com/bahmutov/cypress-examples/commit/09aec67de260858c63f746de1d051e3f8b5d1f0e)
> 
> I think we would need a reproducible example to debug this

 application is running local

log

<img width="1550" alt="Снимок экрана 2021-06-16 в 15 47 58" src="https://user-images.githubusercontent.com/41300396/122222140-a6a4f700-ceba-11eb-8455-176aa6075ce9.png">

![Снимок экрана 2021-06-16 в 15 48 15](https://user-images.githubusercontent.com/41300396/122222203-b7ee0380-ceba-11eb-8466-1f9d82469d10.png)
