### ISSUE TITLE
Test duration keeps running even once test is completed

### ISSUE THREAD

**Issue by mmitchell3590** [cypress-io/cypress#16959]
### Current behavior
Test duration keeps running even once test is completed

### Desired behavior
Once test is completed, timer stops.

### Test code to reproduce
I am not sure this is test code specific. I've seen it occur in several test files.

### Versions
7.5.0

https://user-images.githubusercontent.com/25928813/122248610-2ec4d580-ce96-11eb-99e5-b9855718b164.mp4

**Comment by jennifer-shehane** [comment]
@mmitchell3590 Likely there's something dependent in the test code that you're running that is making Cypress 'hang'. We'll need a reproducible example or some clue on the test code to see why this is happening.

**Comment by krishhna123** [comment]
This issue still exists in Cypress@9.3.1 I am not very sure how to reproduce it but there should not be any reason to continue counter once the execution is done irrespective of any dependent code.
