### ISSUE TITLE
cy.task('combineCoverage') timed out after waiting 60000ms getting this error during bitbucket CI build.

### ISSUE THREAD

**Issue by Ppkd2021** [cypress-io/cypress#16955]
### Current behavior
cy.task('combineCoverage') timed out after waiting 60000ms. getting this error a lot during the execution of test cases on bitbucket but locally when the same test cases are executed then it is working fine.
The above error is randomly thrown for various test cases.

### Desired behavior
A test case should not fail due to this at least.

### Test code to reproduce

![image](https://user-images.githubusercontent.com/59794856/122215616-0aceb780-cec9-11eb-9bfd-8e37b90b559c.png)

### Versions
Cypress code coverage Version - 3.9.2
Cypress version - 7.3.0

**Comment by peteygao** [comment]
This hasn't seen any additional updates since 2021, but I want to update that this is STILL happening with latest `Cypress version 10.10.0`.

Is this issue visible to the Cypress team to address? 🙏🏼

**Comment by bbansalWolfPack** [comment]
seeing same issues. Any solutions yet?

**Comment by calcazar** [comment]
Still seeing this issue on version 11.0.1

**Comment by peteygao** [comment]
Has anyone tried with Cypress 12.x+? We've temporarily turned off code coverage to work around this issue, but obviously that is _not_ ideal.
