### ISSUE TITLE
cypress aborts application requests with `X-Requested-With` header

### ISSUE THREAD

**Issue by alexanderzulechner** [cypress-io/cypress#16957]
### Current behavior

We have a web application, running in docker containers: 
* one docker container serving the frontend application via nginx 
* one docker container with the backend system

We have to add the `X-Requested-With = XMLHttpRequest` header to each request, as soon as we do it, all requests are aborted by cypress. it doesn't matter if the request is intercepted or not via cypress.
The message as seen in the screenshot does not really provide a good information:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/66992731/122229433-05697100-ceb9-11eb-9861-47324cfc9f3f.png">

The output from the console:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/66992731/122228541-3dbc7f80-ceb8-11eb-9ee5-1dfe76a542b8.png">

Investigation points out that it could have something todo with CORS, maybe?
The tests work as soon as we export the docker-ports to the host system und have all paths frontend <-> backend as localhost with different ports.

Executing the failing request from the cypress-console ( copied from the network tab as cUrl ), and execute it in the frontend docker-container succeeded, so problem has to be somehow related to cypress.

### Desired behavior
No XHR request abortion.

### Versions

Tested with cypress 6.8. and also 7.5.

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? We haven’t had any reports of this issue with the headers causing aborted requests before. Thanks!

**Comment by alexanderzulechner** [comment]
after investigation and creating an example for you , we found out that our e2e test setup was restricted by CORS, which wasn't really clear by the message in the browser console cypress did print.

thanks for your response!

 I will close this issue and will add that we solved that problem by adding the additional header in the CORS filter on the backend side of our application in case somebody gets a similar error and does not how to tackle that :)
