### ISSUE TITLE
schematic : should be installed as a devDependency

### ISSUE THREAD

**Issue by Badisi** [cypress-io/cypress#16954]
### Current behavior

When using the command `ng add @cypress/schematic` the library is installed as a `dependency`.

### Desired behavior

The schematic library should be installed as a `devDependency`.

### Fix
https://angular.io/guide/schematics-for-libraries#define-dependency-type

Add the following to the schematic `package.json`:
```json
"ng-add": {
  "save": "devDependencies"
}
```

### Versions
1.3.0

**Comment by jennifer-shehane** [comment]
@Badisi I opened a PR here to address this: https://github.com/cypress-io/cypress/pull/16956

**Comment by Badisi** [comment]
I can confirm that this has been fixed in `@cypress/schematic@1.3.1`.
Thank you guys
