### ISSUE TITLE
Unable to run the specs from the command line

### ISSUE THREAD

**Issue by T-e-j-k-u-m-a-r** [cypress-io/cypress#16968]
### Current behavior

I'm using below code to run my scripts which are present inside the folder -> Integration/examples/exploration by
cypress run --spec "cypress\integration\examples\Exploration\*.js" from the cypress -> bin directory. 

### Desired behavior

All the specs inside the folder Integration/examples/exploration should be executed. 

### Versions
7.5.0

**Comment by T-e-j-k-u-m-a-r** [comment]
Encountered error: 
![error while running spec's from command line_Cypress](https://user-images.githubusercontent.com/54025065/122328349-1e236680-cf4d-11eb-8243-b597fd1c5316.png)

**Comment by jennifer-shehane** [comment]
Can you try running `./node_modules/.bin/cypress run --spec "cypress\integration\examples\Exploration*.js"` from the root of the project (where the node_modules folder is)? https://on.cypress.io/installing-cypress#Opening-Cypress

**Comment by T-e-j-k-u-m-a-r** [comment]
Thanks @jennifer-shehane : It works!

**Comment by abdullahsohailyaqoob** [comment]
Yes I also faced that issue when i wrote my code in MAC machine and zip it and unzip to windows machine and tried to run and got that issue
