### ISSUE TITLE
ignoreTestFiles is ignored when passed from cli

### ISSUE THREAD

**Issue by Sergeon** [cypress-io/cypress#1696]
### Current behavior:
When invoking cypress with `config ignoreTestFiles=*blob` from the command line, specs that match the blob aren't ignored. For instance, this `npm` command:
```
"cypress:run": "cypress run --config ignoreTestFiles=*.demo.js"
```
Will make a `spec.demo.js` to run, when it should be ignored.

### Desired behavior:
Files that match the `ignoreTestFiles` parameter should be ignored.

### Steps to reproduce:

I set up a test-tiny-repo clone with a demo of the issue. The branch is called `ignore-test-files-cli-issue`. [You can find the repo here](https://github.com/Sergeon/cypress-test-tiny/tree/ignore-test-files-cli-issue).

The readme has all the instructions.

### Versions:
Mac Os: 10.13.4
Cypress: 2.1

**Comment by ValerieThoma** [comment]
Thank you for taking the time to provide this excellent example.
I was able to reproduce what you described. 
Passing `ignoreTestFiles` as a CLI argument does not work as the documentation suggests: cypress-io/cypress-documentation#535
We believe this is a bug.

**Comment by Sergeon** [comment]
Hi @brian-mann, thank you for your suggestion.

However, both 
```

"cypress:run": "cypress run --config ignoreTestFiles='*.demo.js'"
```
And:

```
"cypress:run": "cypress run --config ignoreTestFiles='**/*.demo.js'"
```

Still run the `demo` spec. I updated the demonstration repo with the new npm commands.

**Comment by felixkempf** [comment]
This issue unfortunately still exists in cypress 3.2.0

Also I found it rather confusing that even when successfully configuring `ignoreTestFiles` via config file and running `cypress:open`, the configured `ignoreTestFiles` are not shown under "Settings > Configuration".

**Comment by jennifer-shehane** [comment]
I think this PR may fix this issue https://github.com/cypress-io/cypress/pull/3880 Can anyone verify?

**Comment by brianmcgue** [comment]
#3880 does seem to fix this issue for me.
