### ISSUE TITLE
Disable Video Recording through a CLI parameter

### ISSUE THREAD

**Issue by adarnon** [cypress-io/cypress#16963]
### What would you like?

I want to be able to disable video recording in the CLI. Something like:

```
cypress run --video=false
```

### Why is this needed?

Currently, the only way to disable video recording is to set `video: false` in `cypress.json`. This setting controls video recording in both `run` and `run --record`, which is undesirable for us.

In our CI/CD pipeline we run a normal `cypress run` in both branches, and we run `cypress run --record` in some important branches (e.g., `develop`). There is no way to selectively enable/disable video recording (unless I replace the `cypress.json` file in each environment when I need recording to be enabled).

**Comment by jennifer-shehane** [comment]
You can pass any configuration values in the CLI via the `--config` flag. So you can pass `cypress run --config video=false` https://on.cypress.io/configuration#Command-Line Hope this helps!
