### ISSUE TITLE
Placeholder support for CYPRESS_INSTALL_BINARY 

### ISSUE THREAD

**Issue by FDIM** [cypress-io/cypress#16976]
### What would you like?

An easy way to configure and install cypress in corporate environment. It's nice that CYPRESS_INSTALL_BINARY options exists but it could be better. 

To cover all scenarios we need to support windows, mac, and linux (for CI) and there is no nice way do this if you are sitting behind corporate firewall. Here is what I ended up doing and I believe it would work for quite a few others without having to mirror download site (we use artifactory and sadly cypress download site does not come out of the box, I also have limited rights to play with it so I'm also not aware of complete functionality).

So.... drums rolls....

in .npmrc I have this:
```
CYPRESS_INSTALL_BINARY_TEMPLATE=https://artifactory.some.internal.domain/npm-packages/cypress/__VERSION__/cypress___PLATFORM__-__ARCH__.zip
CYPRESS_INSTALL_BINARY=0
```
and in our postinstall hook I do this:
```
console.info('Running cypress install task manually');
process.env.CYPRESS_INSTALL_BINARY = process.env.npm_config_CYPRESS_INSTALL_BINARY_TEMPLATE
    .replace('__VERSION__', process.env.npm_package_devDependencies_cypress)
    .replace('__PLATFORM__', process.platform)
    .replace('__ARCH__', process.arch);

require('cypress/lib/tasks/install').start({
    force: false
}).catch(console.error);
```
This is obviously workaround and I'll have to maintain it in the future, but it is definitely better than proposed alternatives I could find.

So for the solution, how about adding placeholders for cypress version, platform and architecture in CYPRESS_INSTALL_BINARY variable?

```
CYPRESS_INSTALL_BINARY=https://artifactory.some.internal.domain.com/npm-packages/cypress/__CYPRESS_VERSION__/cypress___PLATFORM__-__ARCH__.zip
``` 

Thanks for an awesome tool!

### Why is this needed?

To make it less painful to configure and use cypress across workstations and CI.

**Comment by jemerald** [comment]
`CYPRESS_DOWNLOAD_PATH_TEMPLATE` was added since 9.3.0

**Comment by tbiethman** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/23194, but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
