### ISSUE TITLE
Cypress removes custom status text/reason phrase from http response

### ISSUE THREAD

**Issue by mattiaskagstrom** [cypress-io/cypress#16973]
### Current behavior
Server responds with a http 400 with the text "Åtgärden kan inte vara utförd innan bristen upptäcktes."
generated by the code
`var resp = new HttpResponseMessage(HttpStatusCode.BadRequest)
                    {
                        Content = new StringContent(""),
                        ReasonPhrase = "Åtgärden kan inte vara utförd innan bristen upptäcktes."
                    };`
in C# for .NET 4.8
Cypress then strips that text and returns http.STATUS_CODES[400]

shows up in Chromiums network tab as: 
![image](https://user-images.githubusercontent.com/3661126/122365615-1b2f7280-cf5b-11eb-9b3a-eab9bf2d1a49.png)

The only other resource I found about this issue was this:
https://stackoverflow.com/questions/63050722/cypress-not-receiving-custom-status-text
### Desired behavior
The status text /reason phrase should be forwarded as is to the client.

running outside of Cypress, Chromium shows this
![image](https://user-images.githubusercontent.com/3661126/122365856-55990f80-cf5b-11eb-9984-f924d572f1f9.png)

### Versions
Running Cypress 5.6.0. Unable to upgrade to 6+ due to #14447 
Chromium Version 90.0.4427.0
Windows 10 Enterprise 2004
Cypress-ntlm-auth 3.2.2-beta.1 (https://github.com/bjowes/cypress-ntlm-auth/issues/175)

**Comment by mattiaskagstrom** [comment]
Same issue with Cypress 7.4.0

**Comment by sainthkh** [comment]
It's happening because Cypress normalizes the `statusMessage` in the code below:

https://github.com/cypress-io/cypress/blob/8550842e3696095c9391e89f30c87af6369ecfb9/packages/server/lib/request.js#L499-L505

It's been added at 4/21/2017 by @chrisbreiding (23209b2d34cc31ddc4731e15bdbe858ff9c0190e). 

It's not hard to fix this but I'm not sure it's OK to do so.

**Comment by flotwig** [comment]
I think this would be fine to open a PR for if someone wants to fix this. I don't think we should be messing with the `statusText` here.

**Comment by HughParsons** [comment]
I found a work around for this issue which allows defining a custom statusText and statusCode simultaneously by first stubbing the response with a staticResponse and then modifying that response with a routeHandler:

```javascript
cy.intercept("PUT", "/url", { statusCode:422 });
cy.intercept("PUT", "/url", (req) => {
  req.on("before:response", (res) => {
    res.statusMessage = "ConcurrentLiveEvent";
    res.send();
  });
});
```

This also works using `req.reply()` within a routeHandler in the first intercept.

**Comment by v1b3m** [comment]
Heya,
I want to work on this but I am new to OSS. I've read through the contribution guidelines and everything is set up. Anything I should look out for? Any help will be appreciated 😄

**Comment by kshastri** [comment]
I would like to take this up and drill down more into it. Kindly let me know whether the approach proposed by @Jeje2201 can be taken forward?

**Comment by flotwig** [comment]
@kshastri Yes, please feel welcome to open a PR and tag me if you need help or a review.

The solution that I would like to see implemented would involve our proxy *not* manipulating the "reason phrase" at all. The proxy should *transparently* proxy the reason phrase - if the server sends an empty phrase, we should proxy an empty phrase, if the server sends "200 foo", we should proxy  "200 foo".

I think you'll most likely be able to make this happen inside of `response-middleware.ts` in `packages/proxy`.

**Comment by flotwig** [comment]
The code for this is done in [cypress-io/cypress#22061](https://github.com/cypress-io/cypress/pull/22061), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
