### ISSUE TITLE
Is it possible to mock a HTTP request response?

### ISSUE THREAD

**Issue by souljacker** [cypress-io/cypress#1698]
I'm testing some integration with external APIs like Twitter and Facebook.

Since I don't want to test their app, I wanted to mock the response I get when hitting their API. The thing is, when I'm not authenticated the app redirects me to their Oauth page, where I have to authenticate and then continue with my apps workflow.

It would be something like this

my app --->   request to Twitter api ---\\/------------------- handle response
twitter ----------------------------  oauth  -----> response /\

I'd like to intercept the redirection to Twitter's authorization and reply to my app with a fixture.

Is that a way I can do this with Cypress or only with XHR requests?

**Comment by Bkucera** [comment]
@souljacker Hi, I believe `cy.route` is what you're looking for https://docs.cypress.io/api/commands/route.html#Fixtures
If you have any further questions, please direct them to the [gitter](https://gitter.im/cypress-io/cypress), as you can get better support from other Cypress users. If you have specific feature request or bug, feel free to open another issue. Thanks!
