### ISSUE TITLE
Ability to customize the indentation level of commands in Cypress log

### ISSUE THREAD

**Issue by DanaGoyette** [cypress-io/cypress#16993]
### What would you like?
An ability to customize the indent level of logged commands, allowing more than just `parent` and `child` levels.

### Why is this needed?
This would be a simple alternative to having a [group](https://github.com/cypress-io/cypress/issues/1260) concept, and would be useful for things like the `within` block.

Here's an example of an item I'd like to indent (right side truncated for privacy).
The first `get` is an alias, and the second `get` is a part of the page that uses a value from that alias.
I'd want to be able to indent the second `get` to the level of the `assert` (possibly without showing a dash), and the `assert` to a level further than that.
![image](https://user-images.githubusercontent.com/1697486/122449288-8e84b480-cf5a-11eb-9a78-500e6f56e981.png)

**Comment by jennifer-shehane** [comment]
Since this has not gotten a lot of interest over the years, we’ll close this as not planned.
