### ISSUE TITLE
Ability to test bad internet connection by allowing cy.route never to return a response

### ISSUE THREAD

**Issue by ErikBehar** [cypress-io/cypress#1700]
### Current behavior: 
A request always returns a response 

### Desired behavior:
ability to mock a request timeout 

### Steps to reproduce:

```js

```

### Versions  
latest

**Comment by Bkucera** [comment]
I believe you are looking for the delay option in cy.route, if you have any further questions, please direct them to the gitter for better support from other Cypress users, thanks! https://docs.cypress.io/api/commands/route.html#Options

**Comment by jennifer-shehane** [comment]
What is your application logic when a request 'fails to receive a response' - your application can't be waiting forever. I'm not sure how you want a response to mimic a timeout.

Did you try setting a very high delay?

**Comment by virtualstyle** [comment]
Not trying to revive the thread, but adding my workaround for others who find this from Google: using the blacklistHosts config, you can blacklist your API server to simulate an unresponsive server.

**Comment by flotwig** [comment]
Adding support for simulating unstable network connections is something we're looking at adding as part of #687.
