### ISSUE TITLE
v7.4.0 No longer allows localhost as a RouteMatcher hostname

### ISSUE THREAD

**Issue by lucitez** [cypress-io/cypress#17015]
### Current behavior

`cy.intercept({ hostname: 'localhost' }, (req) => {
...
})`

Results in

```
An invalid RouteMatcher was supplied to cy.intercept(). hostname must be a valid host name or domain name.

You passed: {
  "hostname": "localhost"
}
```

<img width="897" alt="Screen Shot 2021-06-18 at 1 55 53 PM" src="https://user-images.githubusercontent.com/5984157/122615159-e72c7e00-d03c-11eb-8456-6e893d30a03e.png">

### Desired behavior

As the docs suggest (https://docs.cypress.io/api/commands/intercept#Usage), I should be able to use 'localhost' as the `hostname`.

>
```
// spying, dynamic stubbing, request modification, etc.
cy.intercept('/users*', { hostname: 'localhost' }, (req) => {
  /* do something with request and/or response */
})
```

### Test code to reproduce

`cy.intercept({ hostname: 'localhost' }, (req) => {
...
})`

### Versions

Introduced in 7.4.0 in this PR https://github.com/cypress-io/cypress/pull/16577

Worked in 7.3.0

**Comment by sainthkh** [comment]
@flotwig @jennifer-shehane 

The code or doc should be fixed.

**Comment by flotwig** [comment]
@sainthkh the validation is incorrect, `localhost` should be permitted here.
