### ISSUE TITLE
--config-file flag on cypress open is not passing parameters

### ISSUE THREAD

**Issue by joske-em** [cypress-io/cypress#17034]
### Current behavior
When one starts cypress with `--config-file` flag. 
Parameters from the file are not passed to cypress.
e.g. `baseUrl`

### Desired behavior
Parameters from file are passed to cypress.

### Test code to reproduce
1. Install cypress
2. Create `local.json` file
3. Content of file `{
    "baseUrl": "http://localhost:8080",
    "env": {
        "api_server": "http://localhost:5000"
    }
}`
4. Start cypress `npx cypress open --config-file local.json`
5. [Link](https://imgur.com/a/gsCi1JF) to image with cypress settings 

### Versions
Cypress: 7.5.0
Chrome: 91
macOS: 11.4

**Comment by jennifer-shehane** [comment]
I'm not seeing this behavior when following the instructions above. There may be something else influencing the `baseUrl` being set that isn't immediately obvious. Could you provide a repo we could run / with instructions on what to run so we can see the issue? Thanks.

<img width="395" alt="Screen Shot 2021-06-22 at 1 17 26 PM" src="https://user-images.githubusercontent.com/1271364/122978620-54515380-d35c-11eb-9a87-997fba961495.png">

**Comment by joske-em** [comment]
Reinstalled cypress fixed the problem.
