### ISSUE TITLE
Immediate Crash on snapshot hover in all browsers

### ISSUE THREAD

**Issue by 08screasey** [cypress-io/cypress#17035]
I'm quite new to cypress so I'm not sure what could have caused this, but after upgrading from v6 to v7 Cypress does not run well at all. Using "cypress open" the sample test successfully completes, but as soon as I hover over any of the DOM snapshots the test runner immediately freezes. Interestingly if the devtools are open they are still usable, but I cannot open them after it has frozen.
Test:
```js
describe("messages", ()=>{
    beforeEach(()=>{
        cy.loginWithoutUI();
        cy.intercept("GET", `${Cypress.env("API")}/messages/*`, {fixture:"messages/GET_client-messages.json"});
        cy.intercept("GET",`${Cypress.env("API")}/messages/conversations*`, {fixture:"messages/GET_conversations--page0-5.json"})
        cy.intercept("GET",`${Cypress.env("API")}/labels`, {fixture:"labels/GET--default.json"})
        cy.intercept("GET",`${Cypress.env("API")}/users/networks`, {fixture:"user/GET_networks--default-5.json"})
        cy.intercept("GET",`${Cypress.env("API")}/templates`, {fixture:"templates/GET--default-3"});
        cy.intercept("GET", `${Cypress.env("API")}/clients/*`, {fixture:"client/GET--default.json"});
        cy.intercept("POST", `${Cypress.env("API")}/messages`, (req) => {
        req.reply({ ...req.body});
        });
        cy.visitNoSW("/chat");
    })

    it("Should show client messages, updating dialogue and chat list on new message", ()=>{
        cy.getByData('dialogue').should("exist");
        cy.getByData('message').should("have.length", 8)
    })
})

```

Commands:
```js
Cypress.Commands.add("loginWithoutUI", () => {
    localStorage.setItem("userToken","token");
    localStorage.setItem("expDate", Date.now() + 3600000);
    cy.intercept("GET", `${Cypress.env("API")}/users/me`, {fixture:"user/GET_me--complete.json"})
});

Cypress.Commands.add("visitNoSW", (path)=>{
    cy.visit(path, {
        onBeforeLoad (win) {
          delete win.navigator.__proto__.serviceWorker
        }
      })
});

Cypress.Commands.add("getByData", (string)=>{
     cy.get(`[data-cy=${string}]`)
});

```

Is there something wrong with my code here that's causing it to break with no indication as to why?
![Screenshot (279)](https://user-images.githubusercontent.com/59900275/122788040-36c9ae80-d2b6-11eb-93d1-31f00e638717.png)

Here is the printout of my command log, hovering over any over the XHR values causes the entire app to crash.
I'd love to get this resolved if anyone has any idea what could be wrong. I'd also like to not have to add 
  "numTestsKeptInMemory": 0 to the config and lose the debugging perks, and since this is such a small test it end up masking a larger problem.

**Comment by jennifer-shehane** [comment]
@08screasey Which Cypress version are you using? 

Likely it is specific to the application under test because others aren't reporting this, something using up an excessive amount of memory. Is there any way to provide a way for us to reproduce this on our side? Reduce it down to a repo we can run?

**Comment by 08screasey** [comment]
I will try, it is a private repo so it might not be easy to reproduce an example. It can crash even with around 400mb memory usage, but slowly climbs despite being frozen.
Weirdly enough it stops being an issue if I trigger any other api endpoint manually once the tests have been completed (ie Submitting a form). Then I am free to traverse the snapshots with no issues. I have replicated this on v6.8.0, v7.5.0 and currently I am using v7.1.0 since I was having issues with the menu buttons from the electron downgrade on windows. Also my global node version is v14.16.1.
Are there any functions that are fired when the UI switched to an uncontrolled version that would clean-up this hanging memory leak?
