### ISSUE TITLE
Whoops, we can't run your tests.

### ISSUE THREAD

**Issue by RKodandam** [cypress-io/cypress#17049]
### Discussed in https://github.com/cypress-io/cypress/discussions/16989

<div type='discussions-op-text'>

<sup>Originally posted by **kod-raj** June 17, 2021</sup>
I have windows 10 and cypress: 7.4.0 and Firefox78.11.0

When I run tests in Chrome 91, Edge 91 and Electron 89 works as expected. But same test run in Firefox 78, received an error message "Whoops, we can't run your tests. This browser was not launched through Cypress. Tests cannot run."

Also I see that in Firefox browser says that  Cypress is currently running and automating your browser.

Any help much appreciated. Thank you</div>

**Comment by mikestopcontinues** [comment]
I just updated to cypress 7.6.0 with chrome, and I'm getting this error now too. Not sure when it started, as I put aside this project for a few months, but I've tried all the obvious solutions with no success.

**Comment by RKodandam** [comment]
@jennifer-shehane - any help
