### ISSUE TITLE
Cannot visit my enterprise website

### ISSUE THREAD

**Issue by lucas-neves** [cypress-io/cypress#17042]
### Current behavior

When I try to visit the website below, I get the following error on cypress, but the same website do not show console error visiting manually.

https://brc6imobpro.viverebrasil.com.br/imobiliariopfpp/#/painelparceiros/login

![image](https://user-images.githubusercontent.com/17414564/122829341-44366700-d2bd-11eb-8706-10a8b6049df6.png)

I googled it and found it might be an error related to Angular, but since it doesn't prevent the site from being accessed outside of automation, I think it's a Cypress problem.

### Desired behavior

In my opinion it should access the same way the browser itself can do it.
I wouldn't want to stop using Cypress in my company because of this problem.

### Test code to reproduce

Accessing this website from your browser:
https://brc6imobpro.viverebrasil.com.br/imobiliariopfpp/#/painelparceiros/login

Then, try to visit on Cypress.

### Versions

7.5.0

**Comment by jennifer-shehane** [comment]
@lucas-neves By default Cypress modifies code it detects as frame busting so the application under test runs properly in the Cypress Test Runner (which runs your app inside an iframe itself). If you disable our modification by setting `modifyObstructiveCode=false` in your configuration - it seems to load. Further explanation can be found here: https://on.cypress.io/configuration#modifyObstructiveCode
