### ISSUE TITLE
cy.wait(@alias) find all aliases but it doesn'tt continue the execution

### ISSUE THREAD

**Issue by sergio-everis** [cypress-io/cypress#17052]
Hello everyone :),

### Current behavior
![image](https://user-images.githubusercontent.com/86286053/122879241-f9f2cb80-d338-11eb-93b8-983df5f687bb.png)

All those tags are marked as found if you hoover your mouse.

### Desired behavior
To continue after finding those aliases

### Versions

Cypress app 7.5.0 with Electron 89

Thanks.

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by sergio-everis** [comment]
Hi Jennifer,

Thanks for answering. 
Sorry for my short issue explanation, I am reading your tips for improving them.

At the end **the problem was** cy.wait(@alias) was being executed too soon before the page was loaded so I added a **cy.wait() before** and it is now working properly.

Thanks again for your time, I close the issue.
