### ISSUE TITLE
intercept() sometimes parses request or response body as ArrayBuffer

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#17055]
### Current behavior

Some intercepts don’t parse request or response body well, instead of JSON, it is parsed as ArrayBuffer.
![Screenshot 2021-06-22 at 10 47 49](https://user-images.githubusercontent.com/23213553/122894310-5f4db900-d347-11eb-8c7f-3f3722b54b79.png)

### Test code to reproduce
You can find the whole [code example here](https://github.com/filiphric/intercept-error). I was unable to pin down what kind of response or request body caused this. I tried to create a minimalistic example but I ended up just copying the whole payload from the app I’m testing.

### Versions
Problem appears from v7 and higher. `.intercept()` actually behaves well on 6.x versions.

**Comment by jennifer-shehane** [comment]
I think this may be addressed in this issue, which will be fixed in our next release. https://github.com/cypress-io/cypress/issues/16292

**Comment by filiphric** [comment]
Awesome, thanks. I’ll make sure to close the issue once the release is out 👍

**Comment by alexneo2003** [comment]
after upgrade cypress to latest 7.6.0 i'm having same issue like #16292 with test example at [this message](https://github.com/cypress-io/cypress/issues/16292#issuecomment-831282908)

![image](https://user-images.githubusercontent.com/11705902/123221056-34926a80-d4d7-11eb-9083-7d12bad0ef55.png)

**Comment by filiphric** [comment]
Same goes for me. I updated the example with latest version, you can observe the issue still happening.

**Comment by frankind** [comment]
I also found this issue in my project too.

**Comment by tiagodread** [comment]
Running into the same issue with Cypress 7.7.0:

![image](https://user-images.githubusercontent.com/12464858/125514742-aa026608-9fe7-44f6-bd42-4389a6652139.png)

**Comment by nemkin** [comment]
I'm experiencing the same issue with Hungarian strings, using Cypress 7.7.0.

Not just the special characters, but the structure of the JSON object and the distance between the special characters seems to be important.

Test code to reproduce:

```javascript
const data9as = {
  a: [
    {
      a: "üaaaaaaaaaé", // 9 a-s between
      b: 1,
    },
  ],
};

const data8as = {
  a: [
    {
      a: "üaaaaaaaaé", // 8 a-s between
      b: 1,
    },
  ],
};

it("cy.intercept hungarian issue test", () => {
  cy.intercept("https://example.com/test", {
    body: { result: "ok" },
  }).as("testRequest");

  cy.window().then(() => {
    const xhr = new XMLHttpRequest();
    xhr.open("PUT", "https://example.com/test");
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.send(JSON.stringify(data9as));
  });
  cy.wait("@testRequest")
    .its("request")
    .then((req) => {
      expect(req.body).to.not.be.an("ArrayBuffer"); // ❗️ fails
      expect(req.body).to.be.an("object"); // ❗️ fails
    });

  cy.window().then(() => {
    const xhr = new XMLHttpRequest();
    xhr.open("PUT", "https://example.com/test");
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.send(JSON.stringify(data8as));
  });
  cy.wait("@testRequest")
    .its("request")
    .then((req) => {
      expect(req.body).to.not.be.an("ArrayBuffer"); // ✅ passes
      expect(req.body).to.be.an("object"); // ✅ passes
    });
});
```

**Comment by GlebkaF** [comment]
same issue with Russian letters

**Comment by lorenzogrv** [comment]
Similar issue with latin letters with tilde: `áéíóú`

Cypress version `7.6.0`. Upgrading to `8.1.0` did not help

**Comment by SimeonC** [comment]
I've found that this also happens with Japanese characters in `v8.1.0` of cypress.

**Comment by lorenzogrv** [comment]
@jennifer-shehane I wanted to help a bit and created reproducible failed tests → https://github.com/lorenzogrv/cy-intercept-latin-error

An excerpt

```js
const URL = 'https://example.com/test'

function request (body) {
  // performs an XMLHttpRequest to URL
}

function dryAssert (interception) {
  const { request: req } = interception
  expect(req.body).to.not.be.an('ArrayBuffer')
  expect(req.body).to.be.an('object')
}

describe('cy.intercept latin tilde ArrayBuffer issue', () => {
  beforeEach(() => {
    cy.intercept(URL, { body: { result: 'ok' } }).as('interception')
  })

  describe('Cases working as of 8.x', () => {
    it('should work single "letter with tilde"', () => {
      request({ key: 'á' })
      cy.wait('@interception').then(dryAssert)
    })
    it('should work with five "letters with tilde"', () => {
      request({ key: 'áéíóú' })
      cy.wait('@interception').then(dryAssert)
    })
    it('should work with six "letters with tilde"', () => {
      request({ key: 'áéíóúá' })
      cy.wait('@interception').then(dryAssert)
    })
    it('should work with fiveteen "letters with tilde"', () => {
      request({ key: 'áéíóúáéíóúáéíóú' })
      cy.wait('@interception').then(dryAssert)
    })

    it('should work with letters with tilde" within key', () => {
      request({ 'tíldéd Kéy': null })
      cy.wait('@interception').then(dryAssert)
    })
  })

  describe('Cases not working as of 8.x', () => {
    it('should work with mixed tilded and non-tilted letters', () => {
      request({ key: 'válúéwíthsómánytíldés' })
      cy.wait('@interception').then(dryAssert)
    })

    it('should work with letters with tilde" within key and value', () => {
      request({ 'tíldéd Kéy': 'áéíóúáéíóúáéíóú' })
      cy.wait('@interception').then(dryAssert)
    })
  })
})
```

After research I can conclude the JSON structure does not need to be complicated to reproduce the bug

**Comment by lorenzogrv** [comment]
I have tested [the reploducible I shared above](https://github.com/lorenzogrv/cy-intercept-latin-error) with cypress `8.2.0`. Issue seems gone.

**Comment by nemkin** [comment]
[Mine](https://github.com/cypress-io/cypress/issues/17055#issuecomment-879729463) also passes in 8.2.0. Thank you!

**Comment by Deop** [comment]
Issue we had with an ArrayBuffer response seems to have gone in 8.2 as well.
