### ISSUE TITLE
Unable to download Cypress during npm install or yarn install

### ISSUE THREAD

**Issue by pr447e** [cypress-io/cypress#17059]
### Current behavior
```
> cypress@7.5.0 postinstall /Users/pr447e/attt/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 7.5.0)

[STARTED] Task without title.
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/7.5.0?platform=darwin&arch=x64
Error: read ETIMEDOUT

----------

Platform: darwin (19.6.0)
Cypress Version: 7.5.0
```

### Download method
 

- [.] npm
- [.] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [ ] Linux
- [.] Mac
- [ ] Windows

### Other

- [ ] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by jennifer-shehane** [comment]
@pr447e I've typically seen this when losing internet / after switching internet sources. Some other people have seen this when they're behind a proxy - which requires configuration to run Cypress. The https://download.cypress.io/desktop/7.5.0?platform=darwin&arch=x64 url can't be reached for some reason essentially.

Is this consistently happening on every attempt to install?

**Comment by pr447e** [comment]
Yes, I couldn't proceed further and I am using VPN.
