### ISSUE TITLE
Cypress is not running.

### ISSUE THREAD

**Issue by pallavichaudhary** [cypress-io/cypress#17050]
- [ ] [#[](url)](

> url
<img width="1440" alt="Screenshot 2021-06-22 at 11 49 30 AM" src="https://user-images.githubusercontent.com/50236717/122875256-a476e880-d351-11eb-9c42-aecfb7152043.png">

)

**Comment by pallavichaudhary** [comment]
This is the issue

**Comment by jennifer-shehane** [comment]
Hey @pallavichaudhary, it looks like the error is indicating an unexpected end of JSON input for your `package.json` file which is maybe referenced in your plugins file? 

Try expanding the 'Stack Trace' in the error message.

Please provide the full plugins file + package.json referenced for further assistance.
