### ISSUE TITLE
[Request] Cypress run not finding property that cypress open finds

### ISSUE THREAD

**Issue by lucasdonato** [cypress-io/cypress#17065]
### Discussed in https://github.com/cypress-io/cypress/discussions/17064

<div type='discussions-op-text'>

<sup>Originally posted by **lucasdonato** June 22, 2021</sup>
Good afternoon everyone, I'm behaving strangely when running cypress through npx cypress run!
When I run npx cypress open I can access the property **this.currentTest.commands[0]**  on my afterEach function in my file support/index.js, however, when I run the same test via cypress open, I have access to the property.

Look this:

**support/index.js**
![image](https://user-images.githubusercontent.com/12953400/122995614-31d13180-d380-11eb-873e-0695ad54d42d.png)

**my test file**
![image](https://user-images.githubusercontent.com/12953400/122995409-f46ca400-d37f-11eb-9198-4475d5bef7c8.png)

**When I run npx cypress open this is the result**
![image](https://user-images.githubusercontent.com/12953400/122995637-3bf33000-d380-11eb-8534-4f4cb881bdbb.png)

**When I run npx cypress run this is the result**
![image](https://user-images.githubusercontent.com/12953400/122995726-5927fe80-d380-11eb-82eb-836cbc557348.png)

Why doesn't this property exist in cypress run?
Should have the same behavior.. </div>

**Comment by jennifer-shehane** [comment]
We're trying to get consensus on an API for `Cypress.currentTest` (or similarly named), so I'd love to just make this available for us, where it would work consistently. https://github.com/cypress-io/cypress/pull/16652

I'm not sure why this would behave differently without diving into code.
