### ISSUE TITLE
Typings for cy.contains do not support includeShadowDom

### ISSUE THREAD

**Issue by ashblox** [cypress-io/cypress#17066]
### Current behavior
I'm using Cypress with Typescript and while I can pass options to `cy.get()` with `includeShadowDom: true`, I cannot do so with `cy.contains()`. It appears the typings differ, where `cy.get()` allows a `Partial<Cypress.Shadow>` and `cy.contains()` does not. I have tried this using both Cypress v 6.8.0 and v 7.3.0.

Screenshot 1 (Works with `cy.get()`):

![cy-get works](https://user-images.githubusercontent.com/47283036/123000659-d9993000-d37d-11eb-9101-0791f3c6e085.png)

Screenshot 2 (Doesn't work with `cy.contains()`):

![cy-contain doesnt work](https://user-images.githubusercontent.com/47283036/123000658-d9993000-d37d-11eb-8187-5b22ad7ca2cf.png)

### Desired behavior
I should be able to pass the includeShadowDom argument to `cy.contains()`. My current workaround is to enable includeShadowDom in the `cypress.json` but of course that enables it globally.

### Test code to reproduce
Example repo: https://github.com/ashblox/cypress-issue

[This](https://github.com/ashblox/cypress-issue/blob/main/cypress/integration/cypress-issue/cypress-issue.steps.ts) is the file with the issue.

### Versions
Confirmed this does not work with 7.5.0 either.

**Comment by jennifer-shehane** [comment]
Yes, this option is not included on the types but should be. 

<img width="816" alt="Screen Shot 2021-06-23 at 10 06 14 AM" src="https://user-images.githubusercontent.com/1271364/123121352-b8325580-d40a-11eb-858a-681dee534284.png">
<img width="809" alt="Screen Shot 2021-06-23 at 10 06 21 AM" src="https://user-images.githubusercontent.com/1271364/123121367-b9638280-d40a-11eb-9bc9-4d07d1dee82f.png">

**Comment by ashblox** [comment]
Much appreciated. Thank you!
