### ISSUE TITLE
"have.text" or "contain.text" assertions do not work with HTML whitespace entities

### ISSUE THREAD

**Issue by thecp** [cypress-io/cypress#17079]
### Current behavior
Assertion fails when HTML entities like `&nbsp;` are involved:

![grafik](https://user-images.githubusercontent.com/6319976/123116369-24c84700-d441-11eb-8a67-b70e78c8de75.png)

### Desired behavior
Assertion shouldn't fail with HTML entities involved.

### Test code to reproduce
`<div>100&nbsp;%</div>`

`cy.get('some-selector').should('contain.text', '100 %')`

### Versions
Happens with v6 and latest v7 but haven't tried others

**Comment by jennifer-shehane** [comment]
@thecp Could you include the HTML content that you are testing against or edit the example I've given below so that it fails?

`spec.js`

```js
it('visit', () => {
  cy.visit('index.html')
  cy.contains('100 %')
})
```

`index.html`

```html
<html>
<body>
  <div>100 %</div>
</body>
</html>
```

<img width="560" alt="Screen Shot 2021-06-23 at 4 25 30 PM" src="https://user-images.githubusercontent.com/1271364/123170023-a4edad00-d43f-11eb-9019-acef3abe2c7c.png">

**Comment by thecp** [comment]
@jennifer-shehane When trying to reproduce this I recognized that this is not related to the percentage sign but the way how whitespaces are handled in Cypress (and Angular localization).

The code underneath would look like this: `<div>100&nbsp;%`</div>

However the error message in this case is not at all helpful and should either show the real difference by showing HTML entities or the assertion should pass by setting `nbsp;` equal to space.

I updated the description accordingly.

**Comment by diggabyte** [comment]
@jennifer-shehane I can confirm that specifically `&nbsp;` is not interpreted correctly. Example below.

test.html
```
<div class="html-entities">
  <span>hello<span>&nbsp;world
</div>
```
test.js
```
cy.get('.html-entities')
  .should('contain.text', 'hello world');

> Timed out retrying after 10000ms: 
  expected '<div.html-entities>' to have text 'hello world', but the text was 'hello world'

cy.get('.html-entities')
  .should('have.text', 'hello world');

> Timed out retrying after 10000ms: 
  expected '<div.html-entities>' to have text 'hello world', but the text was 'hello world'
```
