### ISSUE TITLE
Feature working on my app but is not working when running it on cypress browser

### ISSUE THREAD

**Issue by talaamin** [cypress-io/cypress#17071]
Hi,
I have a feature where if I click on a link, a popup shows. This is working perfectly fine on my app. However, when I automated this using cypress, it clicks on the link, but it does not open any popup. 

I used the same browser in both cases. 

Are such cases possible?

**Comment by jennifer-shehane** [comment]
Yes, Cypress is running your application within an iframe in a browser, so you may encounter differences. 

When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
