### ISSUE TITLE
cy.wait doesn't seem to be seeing server calls when using requestjs

### ISSUE THREAD

**Issue by StupidIncarnate** [cypress-io/cypress#1708]
I set up a `cy.route` and am waiting for it to fire, but the wait times out, even if I extend the timeout. I'm seeing the request in the console so I'm sure it's happening. 

### Current behavior: 
Test:
![image](https://user-images.githubusercontent.com/276331/39900757-a4beff0c-5489-11e8-94e0-dfd2b1143896.png)

GUI
![image](https://user-images.githubusercontent.com/276331/39900865-631a39b2-548a-11e8-8e07-42dae5c8bbeb.png)

![image](https://user-images.githubusercontent.com/276331/39900791-ec20779a-5489-11e8-916a-ecda735d4fd5.png)
![image](https://user-images.githubusercontent.com/276331/39901083-e2a0c66e-548b-11e8-80f4-cb90e065fd51.png)

I can see the request finish before the wait times out, so I'm at a loss. 

### Desired behavior:
For cy.wait to succeed after a PUT call is made. 

### Steps to reproduce:

```js
let regexPath = new RegExp("save");
		cy.server();
		cy.route("PUT", regexPath).as("saveModel");

		cy.get(`.new-model-property [data-cy="property-name"] input`).type("mainProp");
		cy.get(`.new-model-property [data-cy="property-data-type"] input`).type("Text").blur();

		cy.get(".new-model-property").should("have.length", 1);
		cy.get(".property").should("have.length", 2);
		cy.get(`.property:not(.new-model-property) [data-cy="property-name"] input`).should("have.value", "mainProp");
		cy.get(`.property:not(.new-model-property) [data-cy="property-data-type"]`).should("contain", "text");

		/**
		 *  Did it save?
		 */

		cy.wait("@saveModel");
```

### Versions 
Cypress: 2.1.0
Chrome: v66

**Comment by jennifer-shehane** [comment]
Yeah, this is *really* strange. I don't see anything wrong with your test code by just looking at it. 

I have an exact test with route written this way for a PUT request where the `cy.wait()` does work. 

Is there anything special about your XHR requests? I've seen things like this for `fetch` requests in the past.

**Comment by StupidIncarnate** [comment]
It looks like something to do with [requestjs](https://www.npmjs.com/package/request). All my server calls go through that package. I switched to doing a GET call in jquery and cypress was able to pick it up. Requestjs GET exhibited the same timeout error.  

JQUERY GET REQUEST 
![image](https://user-images.githubusercontent.com/276331/39948798-3bc13916-553d-11e8-9640-731ff4e7e976.png)
![image](https://user-images.githubusercontent.com/276331/39948742-fa9e1120-553c-11e8-9d2f-deee751669b1.png)

REQUESTJS GET REQUEST
![image](https://user-images.githubusercontent.com/276331/39948815-4ca94bd8-553d-11e8-86e9-10599f58ba8f.png)
![image](https://user-images.githubusercontent.com/276331/39948882-973e317c-553d-11e8-8768-16f393a76037.png)

The only differences I see there is jquery doesn't have the X-requested-with header, and has accept: */* instead of accept: application/json. Do you know what that means or do those look like they can cause issues with cypress picking up on things?

**Comment by gs8961** [comment]
Was there ever a resolution to this issue?

**Comment by jennifer-shehane** [comment]
@gs8961 No, we haven't had a chance to look at this as it would require us setting requestjs up on a project to test. Is it possible you could provide a reproducible repo of this issue?

**Comment by rachelfreeman** [comment]
I'm having a similar issue but not using requestjs. Some of my cy.wait's work and some don't. I don't see any rhyme or reason to it. The ones that don't work randomly time out and randomly work.

**Comment by jennifer-shehane** [comment]
Hi @rachelfreeman, if you provide a reproducible example of this behavior, we can look into it.

**Comment by DDC222** [comment]
Hi @jennifer-shehane,

I am having a similar problem when running the code below. The wait step always fails with the following error "CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st request to the route: 'enablePackage'. No request ever occurred." I have two other use-cases that work successfully with a similar code structure.

`cy.server()
cy.route({
	method: 'GET',
	url: 'http://localhost/GhostDraftConfigurationManager/Admin/GDServer/1/*/*/false/EnablePackage',
}).as('enablePackage')
//Click Enable
var arr = Array(10)
cy.get('#enable_package_btn > a').click({ force: true })
cy.contains('Enabling Packages')
	.should('contain.text', 'Enabling Packages')
	.wrap(arr).each(() => {
		cy.get('.modal-content > .modal-footer > .btn-primary').contains('Continue')
			.click().wait('@enablePackage').its('status').should('eq', 200)
	})`

10 /EnablePackage requests are returned:
![image](https://user-images.githubusercontent.com/24717655/49798148-444b6880-fd4a-11e8-822d-b4eed7c25de5.png)

All requests returned are as follows (this is an image of the first request that occurs before the wait(@enablePackage)):
![image](https://user-images.githubusercontent.com/24717655/49798224-6e048f80-fd4a-11e8-9516-c7ff995ff822.png)

I initially wrote this to test if a single request route resolves successfully and it does, it is only when using an array that this occurs.

**Comment by jennifer-shehane** [comment]
cy.route() has been deprecated. Please update to using cy.intercept(), this issue may already be solved.
