### ISSUE TITLE
Cypress doesn't recognize PUT method to be done, fires page load event instead

### ISSUE THREAD

**Issue by yasinitskyi** [cypress-io/cypress#17099]
My application is PSD file editor, when user done with all modification he/she can get JPEG file after all (similar to photoshop online). 

When the user clicks the download button, FRONTEND sends a request with PUT method with updated metadata  (user changed elements alignment etc it is for future re-use, if user wants to re-use parsed PSD file in the future for future campaign whatever), then FRONTEND sends PATCH request, response for PATCH is zip file. 

Sometimes it takes time for BE to create zip. so I need to wait for the response, I am using intercept for both PUT and PATCH, however, whenever I am waiting for the PUT response, despite it is done in 2sec with 200 response, Cypress won't confirm it, moreover, Cypress starting to redirect application to pseudo-external website by firing `new page loading` event. 

If I delete `cy.wait() ` for PUT response, Cypress won't fire such event, it just waits for PATCH methods, downloading zip to `cypress/downloads`. My code:
![image](https://user-images.githubusercontent.com/67145411/123246307-3cbeca00-d518-11eb-905e-7bb693e58493.png)
![image](https://user-images.githubusercontent.com/67145411/123246381-4ea06d00-d518-11eb-8c29-0865e23b73a2.png)
Error with waiting for PUT method to be done:
![image](https://user-images.githubusercontent.com/67145411/123247367-6a584300-d519-11eb-9abd-b149875d0f64.png)
![image](https://user-images.githubusercontent.com/67145411/123247416-780dc880-d519-11eb-9eb5-96d2e701ba3b.png)

No error with no waiting for PUT method to be done:
![image](https://user-images.githubusercontent.com/67145411/123247027-033a8e80-d519-11eb-9630-0a53e7532038.png)

**Comment by jennifer-shehane** [comment]
Probably similar to https://github.com/cypress-io/cypress/issues/15161 

Can you create small repo reproducing the file download? Or fork https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download and set up the file download the way it is done in your application so that we can investigate?

There probably is a situation where if the download takes extra time it may be stuck in this situation.

**Comment by yasinitskyi** [comment]
> Probably similar to #15161
> 
> Can you create small repo reproducing the file download? Or fork https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download and set up the file download the way it is done in your application so that we can investigate?
> 
> There probably is a situation where if the download takes extra time it may be stuck in this situation.

As I mentioned, the structure of the application download is complicated because Backend sends a link in the response, then Frontend retrieves it and download will begin. It is just impossible to mimic. Even if I won't wait for the PUT request as I mentioned, and for example try to assert `cy.url()` after download, it won't run that assert but will fire load page instead.

**Comment by yasinitskyi** [comment]
@jennifer-shehane `download` attribute set on an a element, and `href` points to a resource behind a `302`.
Download function:
```
const downloadByPureUrl = (url, downloadName = 'download') => {
  const eleLink = document.createElement('a');
  eleLink.style.display = 'none';
  eleLink.href = url;
  eleLink.setAttribute('download', downloadName);
  document.body.appendChild(eleLink);
  eleLink.click();
  document.body.removeChild(eleLink);
};
```
How we use it:
`downloadByPureUrl(zipResponse.resource)`
Link for zip download:
![image](https://user-images.githubusercontent.com/67145411/123371793-f9666900-d5b4-11eb-81d9-c2511cef1a77.png)

**Comment by yasinitskyi** [comment]
@jennifer-shehane Any news about my issue? I already sent the code how our download code works? I guess it is because of 302 status code, how to resolve it and do not let cypress react to the 302 redirection status

**Comment by yasinitskyi** [comment]
@jennifer-shehane ???

**Comment by yasinitskyi** [comment]
Amazing support thx @jennifer-shehane
