### ISSUE TITLE
Network requests are not intercepted for a short time between tests

### ISSUE THREAD

**Issue by kevinkir** [cypress-io/cypress#17107]
### Current behavior

There is a short amount of time between tests, where the page is still active but they `cy.intercept`s have been removed. As a result, stubbed network calls can make it through to the server. This can lead to test flakiness.

### Desired behavior

Network stubs should remain in place for as long as the page is active.

### Test code to reproduce

https://github.com/kevinkir/cypress-min-repro-17107

### Versions

Cypress version: 7.6.0 (failures are reprodicible as well all the way back on 6.0.0, although the error is slightly different)
Browser: Chrome 91, Firefox 78, Electron 89
OS: Mac, Linux

**Comment by jennifer-shehane** [comment]
@kevinkir Thanks for providing a reproducible example. I can recreate this flake with intercept from the given example.

**Comment by naganathH** [comment]
@jennifer-shehane -- Looks like I am having  the same issue
