### ISSUE TITLE
CypressError: cy.visit() failed because you are attempting to visit a second domain

### ISSUE THREAD

**Issue by bala465** [cypress-io/cypress#17103]
Current behavior:
cypress.json has "chromeWebSecurity": false. My test visits two sites, with URLs that look like https://example.com/ex01 and http://example.com throws a "When Cypress detects uncaught errors originating from your application it will automatically fail the current test".

Desired behavior:
Ideally this test url should launch with out any errors.

As a work around we tried to give "chromeWebSecurity": false, in cypress.json but it did not resolve the issue.
![error](https://user-images.githubusercontent.com/86420482/123282209-eb1e3b80-d527-11eb-82d3-5fa7fb05ec6c.png)

**Comment by jennifer-shehane** [comment]
Did you try ignoring the `uncaught:exception` with the instructions in the error message? https://on.cypress.io/catalog-of-events#To-conditionally-turn-off-uncaught-exception-handling-for-a-certain-error

We're working on support for visiting multiple domains https://github.com/cypress-io/cypress/issues/944

**Comment by bala465** [comment]
Yes, I have tried to ignore the  exception, but since the application was not loaded properly due to the above error my test case got failed.

**Comment by SelvamNivetha** [comment]
Hi , We tried setting chromeWebSecurity to false and tried ignoring the uncaught:exception as suggested . Now we are facing the error "Page blocked by the extension" 
![image](https://user-images.githubusercontent.com/86411911/123387456-6d087600-d5b5-11eb-8b7a-8847f3fa78dc.png)

**Comment by jennifer-shehane** [comment]
I haven't seen this error before within Cypress. Cypress does use an extension as part of the browser, but I can't see why that would cause this error. 

The logs seem to indicate that a form submit is triggering in the app upon just visiting the application?
