### ISSUE TITLE
cypress browser has an XHR get 200 error in red

### ISSUE THREAD

**Issue by spencer1573** [cypress-io/cypress#1710]
nobody answered my question in chat so i thought i'd ask it here

### Current behavior: 

-> in normal chrome the website loads the asset after login
-> in cypress tab browser (not a test) the website loads the asset after login
-> in the cypress browser when running my test it gives me this error:

<img width="384" alt="screen shot 2018-05-10 at 4 20 10 pm" src="https://user-images.githubusercontent.com/4762850/39950886-258d8cf8-5542-11e8-98d5-a02224b5321d.png">

### Desired behavior:

i just want it to load the asset/ successfully make the XHR request like it normally does in the chrome browser and when it loads in a tab of the cypress browser.

### Steps to reproduce:

```js
beforeEach(function () {
  cy.visit(Cypress.env('STAGE_SITE'))
    .get('.field.top-margin-small > .control > .input')
    .type(Cypress.env('USERNAME_ONE'))

  cy.get(':nth-child(4) > .control > .input')
    .type(Cypress.env('PASSWORD'))

  cy.get(".login-build")
    .click()
    .click()
    .click()

  cy.get(".button")
    .click()
})

context('Left Column Sorted', function () {
  it('Participant reponses selection column sorted alphabetically', function () {
    cy.wait(2000)
    // the error occurs after this.
  })
})
```

### Versions  

running sierra
Cypress package version: 2.1.0
Cypress binary version: 2.1.0
chrome 66.0.3359.139 (Official Build) (64-bit)

so i totally realize you can't replicate this because i can't put the companies login online, but if there was a way i could arrange to pay someone at cypress.io to walk me through the problem while controlling my screen that would be awesome. 

it seems to be an issue where the cypress.io's proxy system is blocking all authenticated requests after a successful login. i can't figure it out. 

thanks so much in advance!

**Comment by jennifer-shehane** [comment]
Hi, did you look into the current workarounds for proxy issues? https://github.com/cypress-io/cypress/issues/1469

**Comment by jennifer-shehane** [comment]
You can prevent Cypress from failing if it is an uncaught exception that is occurring during the test run: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by spencer1573** [comment]
that was an awesome link in the documentation! the only issue is i'm running into the same issue as this issue: [#987](https://github.com/cypress-io/cypress/issues/987)

it doesn't seem to work past the error and continue with the test. 

thanks so much for your help with this!

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if there is still an problem with the issue specified here.
