### ISSUE TITLE
Facing Webpack Compilation Error 

### ISSUE THREAD

**Issue by swasthik08** [cypress-io/cypress#17105]
Getting Web Compilation error, can someone help me to resolve this 

Cypress version -7.6.0

```
Error: Webpack Compilation Error
./cypress/integration/examples/Practice/practice1.js
Module not found: Error: Can't resolve 'cypress/types/lodash' in '/Users/swasthik/CypressAutomation/cypress/integration/examples/Practice'
resolve 'cypress/types/lodash' in '/Users/swasthik/CypressAutomation/cypress/integration/examples/Practice'
  Parsed request is a module
  using description file: /Users/swasthik/CypressAutomation/package.json (relative path: ./cypress/integration/examples/Practice)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
[/Users/swasthik/CypressAutomation/cypress/integration/examples/Practice/node_modules]
[/Users/swasthik/CypressAutomation/cypress/integration/examples/node_modules]
[/Users/swasthik/CypressAutomation/cypress/integration/node_modules]
[/Users/swasthik/CypressAutomation/cypress/node_modules]
[/Users/swasthik/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash.js]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash.json]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash.jsx]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash.mjs]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash.coffee]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash/index]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash/index.js]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash/index.json]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash/index.jsx]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash/index.mjs]
[/Users/swasthik/CypressAutomation/node_modules/cypress/types/lodash/index.coffee]
```

![Screenshot 2021-06-24 at 9 17 36 PM](https://user-images.githubusercontent.com/86422303/123294160-38070f80-d532-11eb-8fe5-1899ab1f5c3a.png)

**Comment by jennifer-shehane** [comment]
@swasthik08 Is this an error that began happening when you updating to 7.6.0 from some previous version? What version? Or was this a new project?

Can you provide the contents of the `cypress/integration/examples/Practice/practice1.js` file and your `package.json` file? Or any way to reproduce this on our end so we can investigate. Thanks.

**Comment by swasthik08** [comment]
This error happened on 7.5.0 as well, so updated it to 7.6.0..still facing the same issue.
sharing the file content here.
practice1.js -
`///<reference types = "Cypress"/>

const { includes } = require("cypress/types/lodash")

describe('My first test suite',function()
{

it('My first test case', function()

{

    cy.visit('url')
    cy.get('.search-keyword').type("ca")
    cy.get('.product').should('have.length',5) //invisible elements
    cy.get('.product:visible').should('have.length',4)  // filtering invisible elements

    //parent child chaining
    //find>> used to get child elements, contains>>to check text , eq>>index
    cy.get('div.products').find('.product').eq(2).contains('ADD TO CART').click()

//dynamically driven 
 

cy.get('div.products').find('.product').each(($el, index, $list) => {
const vegtext = $e1.get('product-name').text()

     if (vegtext.includes("cashews") ) 
     {
        cy.wrap($el.find('button')).click()
      } 
  })
}
)
}
)`

Package.json- 
`{
  "name": "cypressautomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^7.6.0"
  }
}
`

**Comment by swasthik08** [comment]
package.json 

`{
  "name": "cypressautomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^7.6.0"
  }
}
`


practice.js--

///<reference types = "Cypress"/>
const { includes } = require("cypress/types/lodash")
describe('My first test suite',function()
{
it('My first test case', function()
{
    cy.visit('xyz')
    cy.get('.search-keyword').type("ca")
    cy.get('.product').should('have.length',5) 
    cy.get('.product:visible').should('have.length',4)  
    cy.get('div.products').find('.product').eq(2).contains('ADD TO CART').click()
cy.get('div.products').find('.product').each(($el, index, $list) => {
const vegtext = $e1.get('product-name').text()

     if (vegtext.includes("cashews") ) 
     {
        cy.wrap($el.find('button')).click()
      } 
  })})})

**Comment by swasthik08** [comment]
@jennifer-shehane This got fixed by changing   `experimentalSourceRewriting":true`

**Comment by jennifer-shehane** [comment]
Closing as resolved.
