### ISSUE TITLE
Cypress doesn't start with runner, after refreshing works fine

### ISSUE THREAD

**Issue by tomekbuszewski** [cypress-io/cypress#17108]
### Current behavior
Using `cypress open`, after selecting a test, a loading screen is hanging permanently. After refreshing (CMD+R), tests are running. 
![image](https://user-images.githubusercontent.com/13830635/123308031-7812c600-d523-11eb-828c-f28d94b2b707.png)

It started after I've added a preprocessor (using `@cypress/webpack-batteries-included-preprocessor`). My `plugins/index.ts` file looks as following:

```js
const preprocessor = require("@cypress/webpack-batteries-included-preprocessor");
const webpack = require("webpack");

module.exports = (on: typeof Function) => {
  const cfg = {
    typescript: require.resolve("typescript"),
    ...preprocessor.defaultOptions,
  };

  cfg.webpackOptions.plugins = [
    new webpack.ProvidePlugin({
      process: "process/browser",
    }),
  ];

  cfg.webpackOptions.module.rules = [
    ...cfg.webpackOptions.module.rules.filter(
      (item: Record<string, string>) =>
        !item.loader?.includes("coffee-loader") &&
        !item.loader?.includes("ts-loader") &&
        item.type !== "javascript/auto",
    ),
    {
      test: /\.svg$/,
      loader: "@svgr/webpack",
      exclude: [/node_modules/],
    },
    {
      exclude: /node_modules/,
      test: /\.[tj]sx?$/,
      loader: "ts-loader",
      options: {
        transpileOnly: true,
      },
    },
  ];

  on("file:preprocessor", preprocessor(cfg));
};

export {};
```

and my cypress.json:

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "noEmit": false,
    "strict": true,
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"],
    "target": "ES5"
  },
  "include": ["../node_modules/cypress", "**/*.ts", "**/*.tsx"]
}
```

I've also tried using `@cypress/webpack-preprocessor` and importing some of my original Webpack config, but the result is the same.

It is like this on Chrome, Firefox and Electron. Headless mode works without issues.

### Desired behavior
Tests are running automatically even with preprocessors active.

### Test code to reproduce
Just simplest, easiest tests currently, so basically only `cy.visit()` and one or two DOM assertions. 

### Versions

Cypress 7.6.0.
Webpack 5.20.1

**Comment by melibe23** [comment]
I have the same issue.

Cypress 7.19.1
cypress/webpack-preprocessor: "version": "5.7.0"

**Comment by jwalton** [comment]
This is just started happening for me in Cypress 6.1.0 and in 8.3.0.
