### ISSUE TITLE
Cypress fails to run on CI with Cypress Dashboard after upgrading from 6.1.0 -> 7.5.0

### ISSUE THREAD

**Issue by BryantUng-at** [cypress-io/cypress#17113]
### Current behavior
Currently, we're on version 6.1.0 and after upgrading to 7.5.0, test run fine locally.  When kicking off test on CI, we're using the cypress dashboard and get the following response back:  (scrubbed some maybe sensitive data):
```
2021-06-24T04:20:53.553Z cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/runs/<GUID>/instances' }
2021-06-24T04:20:53.553Z cypress:network:agent got family { family: 4, href: 'https://api.cypress.io/runs/<GUID>/instances' }
2021-06-24T04:20:54.003Z cypress:server:api response { spec: null, instanceId: null, totalInstances: 1, claimedInstances: 0, estimatedWallClockDuration: null }
```

### Desired behavior

When I run the same command that is ran on CI locally, I get the following:
```  
cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/runs/<GUID>/instances' } +627ms
cypress:network:agent got family { family: 4, href: 'https://api.cypress.io/runs/<GUID>/instances' } +1ms
cypress:server:api response { spec: 'integration_tests/cypress/test/smoke.spec.tsx', instanceId: '<GUID>', totalInstances: 1, claimedInstances: 1, estimatedWallClockDuration: 17434 } +403ms
```

The same command seems to work locally on my mac but not in a docker container in CI.  The only difference on CI is upgrading from 6.1.0 -> 7.5.0. If I remove dependency to cypress dashboard on 7.5.0 on CI it works as well.

### Test code to reproduce
This isn't related to the test code as it works locally fine but more of running test on ci with cypress dashboard.  

### Versions
Cypress 6.1.0 works on CI
Cypress 7.5.0 doesn't work on CI

**Comment by jennifer-shehane** [comment]
@BryantUng-at The logs you printed don't look right to me either. What is the actual result of the run? Is an error ever thrown in 7.5.0? 

There shouldn't be anything that should have caused an issue from 7.0+ that I can think of. Maybe if you're not using Node 12+ something weird could happen?

If possible, could you email support@cypress.io with the details, including the organization / run url so we can look on our side to see what happened in the API? Thanks.

**Comment by BryantUng-at** [comment]
Thanks Jennifer, will email you after I can grab more data and logs.  can look at what node version I'm using as well.  

No error is thrown it just goes from 
(Run Starting)
to 
(Run Finished)

and no test is ran.

**Comment by jennifer-shehane** [comment]
Yah, I haven't seen this issue before. That information should be helpful. Thanks!
