### ISSUE TITLE
Check Cypress cookie is null without using assertion 

### ISSUE THREAD

**Issue by Arunk28** [cypress-io/cypress#17123]
Hi,
I want to check the Cy.getcookie value is null or not in if statement without using assertion.

If(Cy.getcookie('name')==null){..do some operation}
This is not working

**Comment by 109149** [comment]
You have typo in your code. It's: `cy.getCookie('name')`.

[getCookie syntax](https://docs.cypress.io/api/commands/getcookie#Syntax).

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
