### ISSUE TITLE
Cypress collect javascript console warnings

### ISSUE THREAD

**Issue by rsudarson** [cypress-io/cypress#1712]
How to collect all the javascript warnings in cypress test spec.

**Comment by brian-mann** [comment]
If they are coming from your javascript code, just use `cy.spy` on `console.*` functions.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
