### ISSUE TITLE
Cypress 7.6.0 broken when used with Flow

### ISSUE THREAD

**Issue by fila90** [cypress-io/cypress#17130]
### Current behavior

Cypress won't run tests complaining about `flow` syntax.
![Screen Shot on 2021-06-28 at 14-26-22](https://user-images.githubusercontent.com/16494464/123636303-fcfc2900-d81c-11eb-8369-dbc843dfb85a.png)
If i remove that `flow` syntax it will just point to different file again complaining about `flow`

### Desired behavior

Cypress 7.5.0 runs tests with no issues, so something in last version caused this issue 

### Versions

Flow version 0.154.0
Broken on version - 7.6.0
Last working version - 7.5.0
OS Version - macOS Big Sur 11.4

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by fila90** [comment]
@jennifer-shehane 
here you go https://github.com/alacrity-law/cypress-test2

if you try an downgrade to `7.5.0` it works like a charm

**Comment by thomaswelton** [comment]
@fila90 I encountered an issue with flow types when I upgraded from 7.2.0 to version 8

I followed the notes here https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor#use-babelrc
so that I can use my own babel config (that contains the flow preset) with cypress

After installing `@cypress/webpack-preprocessor` and adding this to my plugins.js file
```
const webpackPreprocessor = require('@cypress/webpack-preprocessor')
const defaults = webpackPreprocessor.defaultOptions
module.exports = (on) => {
  delete defaults.webpackOptions.module.rules[0].use[0].options.presets
  on('file:preprocessor', webpackPreprocessor(defaults))
}
```

My issue was resolved

**Comment by thomaswelton** [comment]
I've opened a PR against your repo and verified that the update fixes your test

![flow-fix](https://user-images.githubusercontent.com/678372/128702906-69bad4cd-eaee-46c4-9065-19d33f625d11.png)

**Comment by fila90** [comment]
> I've opened a PR against your repo and verified that the update fixes your test
> 
> ![flow-fix](https://user-images.githubusercontent.com/678372/128702906-69bad4cd-eaee-46c4-9065-19d33f625d11.png)

thank you so much for your effort 🎉 

in the meantime we already fixed this, i just forgot to close this issue 😅
