### ISSUE TITLE
Tests set as it.only do not all run with nested describes

### ISSUE THREAD

**Issue by svaccaro** [cypress-io/cypress#17145]
### Current behavior
When tests are set to run with it.only, they do not always reliably run. This happens specifically when the tests are at different nesting levels.

### Desired behavior
Every it.only in a spec will run.

### Test code to reproduce
For a simple example, the below will reproduce the behavior I've seen. I would expect Test 1.2 and Test 1a.2 both to run, but only Test 1.2 runs. 

```js
describe('Test type 1', () => {
    it('Test 1.1', () => {
      cy.log('Ran test 1.1');
    });
    it.only('Test 1.2', () => {
      cy.log('Ran test 1.2');
    });
    describe('Test type 1a', () => {
      it('Test 1a.1', () => {
        cy.log('Ran test 1a.1');
      });
      it.only('Test 1a.2', () => {
        cy.log('Ran test 1a.2');
      });
    });
});
```

### Versions
7.5.0

**Comment by jennifer-shehane** [comment]
Yeah, this shouldn't be happening in this way. It's not just a visual issue with the reporter - the console.logs do not log also. 

Doesn't seem like a regression either - went back to Cypress 4.7.0 and it's the same issue.

```js
describe('Test type 1', () => {
  it('Test 1.1', () => {
    console.log('Ran test 1.1')
    cy.log('Ran test 1.1')
  })
  it.only('Test 1.2', () => {
    console.log('Ran test 1.2')
    cy.log('Ran test 1.2')
  })
  describe('Test type 1a', () => {
    it('Test 1a.1', () => {
      console.log('Ran test 1a.1')
      cy.log('Ran test 1a.1')
    })
    it.only('Test 1a.2', () => {
      console.log('Ran test 1a.2')
      cy.log('Ran test 1a.2')
    })
  })
})
```

<img width="437" alt="Screen Shot 2021-06-29 at 10 30 59 AM" src="https://user-images.githubusercontent.com/1271364/123826156-207aae80-d8c5-11eb-827c-8406bb99560e.png">
