### ISSUE TITLE
Intercept type definition should include methods 'continue' and 'on'

### ISSUE THREAD

**Issue by Camo30** [cypress-io/cypress#17140]
### Current behavior
When looking at the [documentation](https://docs.cypress.io/api/commands/intercept#Controlling-the-response) following methods should be available on RouteHandler when using `cy.intercept`:

- req.reply()
- req.continue()
- req.destroy()
- req.redirect()
- req.on()

When trying to use this in a project which uses TypeScript it seems that `continue` and `on` is missing.

### Desired behavior
All methods should be available like in the documentation mentioned above.

### Test code to reproduce
```TS
cy.intercept("POST", "**/getuser", req => {
        req.reply();
        req.continue(); // <-- Fails
        req.destroy();
        req.redirect("");
        req.on(); // <-- Fails
});
```

### Versions

> Cypress package version: 7.6.0
Cypress binary version: 7.6.0   
Electron version: 12.0.0-beta.14
Bundled Node version:
14.15.1

**Comment by jennifer-shehane** [comment]
There are types defined here: https://github.com/cypress-io/cypress/blob/develop/packages/net-stubbing/lib/external-types.ts#L169:L169 

So, perhaps there's something missing in this situation for the definition.

**Comment by Camo30** [comment]
Hm you are right, it seems to be an issue on my side. I'm going to close this one. Thanks!
