### ISSUE TITLE
Test runs not showing in 'runs'

### ISSUE THREAD

**Issue by mspanish** [cypress-io/cypress#1715]
I can run my test - which I see in the test runner and fake browser window - but even though I can see all of that and it passes, only the kitchen sink run shows up in the "runs" tab, there and in the dashboard service. How can I get my new tests to show up there? I have recording enabled in my cypress.json if that's necessary.

**Comment by mspanish** [comment]
Sorry bit of a dumb error - I wasn't using --record in my cli command

**Comment by jennifer-shehane** [comment]
No problem!
