### ISSUE TITLE
Test is passing in localhost but failing in the live site

### ISSUE THREAD

**Issue by jsanes** [cypress-io/cypress#17159]
### Current behavior
I have a test that:

1. Clicks on an element that makes the page scroll to the Contact section.
2. Clicks on the Contact Us button
3. This shows an overlay panel with `position: fixed` with the contact form inside
4. Fills out a form and clicks on the submit button.

When I run the test in my local machine, it passes and I can see the overlay panel appearing and the text being typed. But when I run the same test on the published site it fails because the overlay panel is covered by another div.

This happens in headless and headed modes. When it's in headed mode I can see that the overlay panel doesn't show correctly (unlike in localhost, where it shows correctly).

I'm using a Gatsby project and I made a production build and ran it with Gatsby's `serve` command and the test passes. The only problem is when the test runs against the live, production environment website.

I've tested this with Chrome and Firefox.

### Desired behavior
This test should pass in all environments since it's the same code. The browser that Cypress runs should work the same between localhost and the live site since with the production build running in my machine, the test passes.

### Versions
Cypress: 7.6.0
Chrome: 91
Firefox: 88
OS: macOS 11.4

**Comment by Narretz** [comment]
Is it possible that there's a timing difference between localhost and production? Something that loads fast on localhost (or not at all) and slow on prod which blocks the element?

**Comment by jsanes** [comment]
@Narretz That's it! I added a `cy.wait()` after visiting the page and it worked. It seems the required JS was not completely loaded when I clicked the contact button. Thank you very much!

**Comment by RealCyGuy** [comment]
Should be closed?

**Comment by jsanes** [comment]
Yes, I just added a custom property to `document` when the JS code in question loaded. Then I tested that the property was true and, as you know, Cypress retries the `should` statement for a predefined timeout. This way I could know when the element was ready to be clicked without having to `wait()` for a specific amount of time.
