### ISSUE TITLE
Check Cypress Cookie is null or not 

### ISSUE THREAD

**Issue by Arunk28** [cypress-io/cypress#17156]
I want to store the token and expire time in the cookie and need to check that in every 
request before made to the server 

So for the first time am checking the cookie is null if there am getting the token from 
server 

so in this case it is not working 
the 'if' condition is fails 
because it wont return null or empty or undefined 

```js
export const getToken = ()=>
{        
    if(cy.getCookie("tokenDetails") == null){
         getTokenData();     
     }
    else
     {
        cy.getCookie("tokenDetails").then((c)=>{            
            const data = JSON.parse(c.value);
            const expire = data.expiresAt;
            let  token =  data.token;
            const timeStamp =  Math.round((new Date()).getTime() / 1000);
            cy.log(timeStamp >= expire);
            if(timeStamp >= expire)
            {
                getTokenData();        
            }
            else
            {
                cy.wrap(token).as('token')
            }
        });
    
}
```

**Comment by jennifer-shehane** [comment]
@Arunk28 You can work with 'return' values of Cypress commands since they aree asynchronous. I suggeest reading the entirety of this document: https://on.cypress.io/variables-and-aliases#Return-Values

cy.getCookie() will yield null if it isn't found. 

You want to instead do something like

```js
cy.getCookie("tokenDetails").then((cookie) => {
  if (cookie == null) {
    getTokenData();
  } else {
	...
  }
})
```
