### ISSUE TITLE
running component tests without component directory fails with infinite recursion

### ISSUE THREAD

**Issue by lievenvaneeckhaute** [cypress-io/cypress#17151]
### Current behavior
When running the cypress component tests without a cypress/component directory it appears to try and recurse in cypress/component directories. The dev server then finally gives up with:

```
errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'stat',
  path: 'cypress/component/cypress/component/cypress/component/cypress/component/cypress/component/cypress/component/cypress/component/cypress/component/cypress/component/.../cypress/component'
```

This is easily resolved by adding a component directory.

### Desired behavior
Some indication/warning that the component directory doesn't exist.

### Test code to reproduce
This happens with the simplest example I could find.

### Versions
```
    "@babel/core": "^7.10.4",
    "webpack-dev-server": "^3.11.2",
    "@svgr/webpack": "^5.5.0",
    "@cypress/webpack-dev-server": "^1.3.1",
    "html-webpack-plugin": "4.0.0",
    "css-loader": "^5.2.6",
    "file-loader": "^4.2.0"
```

 ../../node_modules/.bin/cypress --version
Cypress package version: 7.5.0
Cypress binary version: 7.5.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1

**Comment by jennifer-shehane** [comment]
@lievenvaneeckhaute What operating system are you using when you run your tests? Can you include your `cypress.json` file?

**Comment by fiveable-jferg** [comment]
I'm also seeing this behavior on non-WSL Ubuntu with the following cypress.json: 

```
{
  "video": false,
  "testFiles": "**/*.spec.{js,jsx}",
  "viewportWidth": 500,
  "viewportHeight": 800,
  "componentFolder": "cypress/components/",
  "pluginsFile": "cypress/plugins/plugins.js"
}
```

**Comment by smfelsher** [comment]
I was also experiencing the same issue (test continuously running) until I disabled the @cypress/code-coverage/support. I have not yet set up my project to instrument my components prior to running a component test. I will report back my findings once I have this setup.

**Comment by smfelsher** [comment]
Well, I added

```js
on(
    'file:preprocessor',
    require('@cypress/code-coverage/use-browserify-istanbul')
  )
```
to my `plugins/index.ts` file, but Cypress did not detect that my file was instrumented and the test still continuously ran.

Looks like I'll just disable code coverage until this is resolved.

**Comment by elevatebart** [comment]
I am working on a solution.

**Comment by elevatebart** [comment]
The problem is that tests are re-run even when unrelated files are modified.

@cowboy I will take care of this one tomorrow

**Comment by lmiller1990** [comment]
I can't seem to find the issue, but I remember we fixed this (or something similar) in another issue.

If anyone still has this issue, please make a new issue with a minimal reproduction. Thanks!
