### ISSUE TITLE
Attempting to record a run, but my record keys are being invalidated against a projectID from a deleted project

### ISSUE THREAD

**Issue by yaredw** [cypress-io/cypress#17167]
### Current behavior

1. Decided today to start recording test sessions. When I run `cypress run --record --key $keyfromproject1` (or with _any_ other project's record key), I receive an error saying that the record key is not valid with a projectID from an old project that I had deleted months ago:

```
Your Record Key $key...project1 is not valid with this project: $deletedprojectID

It may have been recently revoked by you or another user.

Please log into the Dashboard to see the valid record keys.

https://on.cypress.io/dashboard/projects/$deletedprojectID
```

2. When I go to that dashboard URL, I am directed to my projects (where the $deletedproject does not exist)
3. The error occurs when I attempt to run with _any_ project's record key, the error returned always mentions the same $deletedprojectID
4. I also tried removing the projects from cypress runner and re-adding them (I verified the "projectID" key present in each project's `cypress.json` matched the projectID in the cypress GUI's settings tab), but it is still the same $deletedprojectID that is returned in the "is not valid" error
5. If I manually change the projectID in cypress.json to $deletedprojectID, I see this error in the Cypress GUI's "Runs" tab:

<img width="1433" alt="Screen Shot 2021-06-30 at 12 54 31 PM" src="https://user-images.githubusercontent.com/5853806/124023101-71140980-d9a2-11eb-985d-53cfb4cdb9f4.png">

### Desired behavior
- I expected to see the record keys validated against their respective projectIDs
- I expected to not see the $deletedprojectID at all
- I expected that removing and re-adding the projects in the Cypress GUI would fix the issue

### Versions

- Cypress 7.6.0
- macOS Big Sur 11.4

**Comment by jennifer-shehane** [comment]
It sounds like the best thing to do is to create a new 'project' for recording to the Dashboard since the old one was deleted.  

- Can you try removing the `projectId` entirely from the `cypress.json`, close Cypress and reopen via `cypress open`. 
- Then within the 'Runs' tab, click to "set up a new project to record". 

Let me know the results of this. Also feel free to email our support@cypress.io if these steps don't produce thee desired result and we can look behind the scenes at the projectIds.

**Comment by yaredw** [comment]
@jennifer-shehane thank you for the response! I followed the steps and sent the record command (copied from the Runs tab), but unfortunately I am receiving the same error validating against that same $deletedprojectID

**Comment by yaredw** [comment]
I also tried removing all projects both in dashboard.cypress.io and my local Cypress GUI, but still seeing the same old $deletedprojectID in the error

**Comment by jennifer-shehane** [comment]
@yaredw Sorry for the delay in responding. Our team has been on holiday. Can you email our team at support@cypress.io with the details of the organization and projectId? I looked in the code and this error is throwing from our API so there may be a situation when a project is deleted that we're not accounting for. This way we can look up the details of the error directly. Thank you!

**Comment by jennifer-shehane** [comment]
Closing as resolved. Uninstalling Cypress and reinstalling, the issue was able to be resolved.

**Comment by yaredw** [comment]
Note for any future readers, uninstalling/reinstalling specifically with these flags worked:
1. `npm uninstall cypress -g --save`
2. `npm install cypress -g`
