### ISSUE TITLE
Global keyboard shortcut doesn't work in Firefox

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#17163]
### Current behavior
We have a test that holds the Ctrl button while clicking on an element. We've basically copied the code directly from the Cypress docs: https://docs.cypress.io/api/commands/type#Global-Shortcuts

This test works fine in Chrome, but fails reliably in Firefox with this error:

![image](https://user-images.githubusercontent.com/10719780/124004808-3eabe180-d98d-11eb-8ec9-cc8f3bd43aa9.png)

The Cypress sidebar seems to contradict itself: it shows that we're getting `body` and typing into it, but then a few lines down, it says we're typing into a button. Where did the button come from?

### Desired behavior
Global shortcuts should work in Firefox.

### Test code to reproduce
More or less copied wholesale from the Cypress docs:

```
cy.get('body').type('{ctrl}', { release: false }).findByTestId(`stage.header.${testId}`).click();
```

### Versions
Cypress 7.5.0
Firefox 88 or 89
Linux (Debian 9), Windows 10

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Using the example above plainly doesn't reproduce the issue in Firefox 89.

My guess would be that this ant button at some point after calling type calls focus programmatically as part of the app code. So then it tries to type into the currently focused element. But I couldn't say without having a way to reproduce.

`index.html`

```html
<html>
<body>
  <div>0</div>
</body>
</html>
```

`spec.js`

```js 
it('test', () => {
  cy.visit('index.html')
  cy.get('body').type('{ctrl}', { release: false }).find('div').click()
})
```

<img width="967" alt="Screen Shot 2021-06-30 at 12 45 42 PM" src="https://user-images.githubusercontent.com/1271364/124007591-1d54f080-d9a1-11eb-8a84-7df0a187a7a3.png">

**Comment by kaiyoma** [comment]
Okay, let me investigate this and get back to you. That said, if this was related to button auto-focus, I would expect to see this problem in Chrome too, but our test passes reliably in Chrome.

**Comment by kaiyoma** [comment]
No, we don't have any auto-focusing elements in this UI. Coming up with a simple example may prove to be really difficult, as this is happening in a large proprietary application. Any suggestions for debugging?

**Comment by kaiyoma** [comment]
Turns out `force: true` works here, so even though I don't like using it, I think this will be our workaround for now.
