### ISSUE TITLE
Intercept is not working properly on version 7.4

### ISSUE THREAD

**Issue by fernandomartinez82** [cypress-io/cypress#17168]
In this piece of code, the request is not intercepted. And Uncaught exceptions are shown. 
**With cypress version 6.8 it works properly.**

```js
cy.intercept('GET', 'api.bounceexchange.com/capture/convert2.gif').as('eventWunder')

  cy.visit("https://shapees.com/a/checkout/4591b47f-bd10-4590-9202-694f00443c03/ODJlYjRkN2/u/2/?shop=shapees&has_plan=False&plan_cart=False&cart-items=2514_1")
  
  //rest of code 
  //cy.wait("@eventWunder").......
```

Note: 
I have added 'ignore exception' on the index.js

```js
Cypress.on('uncaught:exception', (err) => {
    return false
  });
```

Cypress: 7.4.0
Chrome: 91.0.4472.124

**Comment by naganathH** [comment]
@fernandomartinez82 -- have you found any work around for this, I am facing same issue.
