### ISSUE TITLE
Subsequent cy.readFile calls fail

### ISSUE THREAD

**Issue by adi518** [cypress-io/cypress#17165]
### Current behavior
Subsequent `readFile` calls fail.

### Desired behavior
Resolve files.

### Test code to reproduce
```js
describe('foo', async () => {
	const foo = await cy.readFile('foo.json')
	const foo2 = await cy.readFile('foo.json') // fails
})
```

### Versions
Cypress 7.0.6, macOS 11.4, Chrome 91

**Comment by jennifer-shehane** [comment]
You need to call Cypress commands within an `it` test, not outside in the `describe`. 

I also suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Cypress commands are async and this is not going to work the way you're suspecting. 

```js
it('foo', () => {
  cy.readFile('cypress/fixtures/amount.json').then((data) => {
    // work with the resolved data here
  })
  cy.readFile('cypress/fixtures/amount.json').then((data) => {
    // work with the resolved data here
  })
})
```

**Comment by adi518** [comment]
For brevity, I used the `describe` block, but pretty sure I used a `it` block in the actual test. Not sure why it's an issue. I'm guessing the describe block is unawaited for `it` blocks, but again, I'm near certain I tried to resolve these files under a `it` block. We know commands are async, or mostly async due to the nature of client-side testing. Is there anything wrong with using `async/await` instead of chaining?

**Comment by bahmutov** [comment]
Please read cypress documentation. You cannot use async await as cypress commands are reactive chain and not promises

**Comment by adi518** [comment]
The docs changed a little since last I last looked at it. I found the relevant section though and will give it a try soon. Well anyway, this started off as a hack to match my intercepts to my fixtures, but I later found the correct way to make a fixture path dynamic through `cy.intercept`. Thanks guys. 👍
