### ISSUE TITLE
attempt to log into gmail account, got "Cookies are disabled" warning

### ISSUE THREAD

**Issue by ponienchen** [cypress-io/cypress#17166]
### Current behavior
Log into a google account (no FSA enabled, not explicitly stubbing to disable cookies)
![Screen Shot 2021-06-30 at 12 27 21 PM](https://user-images.githubusercontent.com/4860256/124020242-dfef6380-d99e-11eb-8ea4-6c19bec98a8b.png)

### Desired behavior
Google account related cookies are created and users are redirected to google page as a signed-in user or gmail account directly

### Test code to reproduce
cy.visit('https://accounts.google.com');
cy.get('#identifierId').type("gmail test account email address");
cy.get('#identifierNext').click();        
cy.get('#password').type("gmail test account password");
cy.get('#passwordNext button').click();

**Comment by AtofStryker** [comment]
Hi @ponienchen. This will be supported with the `cy.origin` experimental command with the completion of #23885 with being supported by #23872, but may not work if leveraging accounts.google.com as your testing domain (which is an unlikely use case). If that is the case, that should likely be completed with #24094

**Comment by ImBIOS** [comment]
I still get this problem and opening new issue #26929
