### ISSUE TITLE
Offer option to disable clearing of cookies by default before each test

### ISSUE THREAD

**Issue by symon-skelly** [cypress-io/cypress#17174]
### What would you like?

I would like an option in Cypress to disable the clearing of cookies / localStorage before each test is performed.

### Why is this needed?

When running tests in the firefox Browser with cookies that are set using cy.setCookie, the following issue occurs:

https://github.com/cypress-io/cypress/issues/6375

Please give the option to disable this automatic clearing of cookies / localStorage so that the issue above has a consistent workaround for all users.

**Comment by emilyrohrbough** [comment]
In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation). There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

This will prevent DOM and browser state bleed over between tests.

If it is desired to persist DOM and browser state between a set of tests, you will be able to turn test isolation off for the run or at the suite level.

Closing this issue as done and tagging for the v12.0.0 release.
