### ISSUE TITLE
cypress web-app in vagrant, web-browser in host

### ISSUE THREAD

**Issue by hlb-schmidt** [cypress-io/cypress#1717]
how can we use the cypress web-app `./node_modules/.bin/cypress open --port 4567` in a web-browser on vm host?

we develop our web-shop in a headless linux virtual machine (vagrant) on a ms-windows host, and when i try to open the cypress web-app in google-chrome on host i get an error: "This browser was not launched through Cypress. Tests cannot run."

if not possible, what is the technical limitation?

**Comment by brian-mann** [comment]
Run the browser locally in your host OS, expose a port into vagrant so it can connect to your webserver and use Cypress in the host OS. I know this is not ideal given that the source code is in vagrant, but this will at least work.

**Comment by jennifer-shehane** [comment]
Hey @hlb-schmidt, did this solution work for you?

**Comment by hlb-schmidt** [comment]
nope.

**Comment by Anyoks** [comment]
I am also working on Vagrant Vm and I'd like to test with cypress. @hlb-schmidt  how did you go around this?

**Comment by hlb-schmidt** [comment]
@Anyoks i didn't have to look for a workaround, and could just stop caring. (it turned out that marketing department - _who now have the absolute say in the shop i code for_ - wants to test everything manually, so who am i to take/question their work.)

but fwiw, my old tests (when my previous boss still wanted automation) are made with python + selenium. and if i need/want automated website testing again, i would try https://playwright.dev/ next.

**Comment by Anyoks** [comment]
hmm, Thanks for the feedback @hlb-schmidt . I do appreciate, Checking out PlayWright now. The marketing team, I believe, will eventually catch up with the right technology once they see the need to be more productive!

**Comment by Anyoks** [comment]
I figured out what to do, just in case you are still interested @hlb-schmidt or anyone else in the future:
Assuming you have corrently installed cypress and can run it headless:` yarn run cypress run` (or whichever way you run it, `npm` etc)

**1. You need an X-Server on the host.**

- On Linux, you already have and X Server running
- On Mac, On Mac OSX you can install XQuartz

**2. Enable X-forwarding on your Vagrant VM**

Just add this to your `Vagrantfile`
`config.ssh.forward_x11 = true`

**3. Ssh into the box without vagrant ssh**
We need to access the guest with `ssh` as opposed to the normal  `vagrant ssh`. Do do this:
run `$ vagrant ssh-config` on the host in your directory with the vagrant file

```
$ vagrant ssh-config
Host default
  HostName 127.0.0.1
  User ubuntu
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/xxxx/work/.vagrant/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardX11 yes
```
From this we have the details we need to ssh. The  `user`, the `HostName` the `Port` and the `IdentityFile`.

Now we can, from the host `ssh` into the guest and run the cypress test runner. 

We also need to add `-X` flag that tells `ssh` to use the X-forwarding.

Assuming my project runs in a directory called `project` in the home directory of my guest machine... Run this command from the host machine while your box in running.

`ssh vagrant@127.0.0.1 -X  -p 2222 -i  /Users/xxxx/work/.vagrant/private_key -t "cd /home/vagrant/project;  yarn run cypress open"`

Voila! the Test runner will run in your box and the GUI will display on your host machine.

Credits to [Gabor](https://code-maven.com/xforwarding-from-vagrant-box) and [Martin](https://coderwall.com/p/ozhfva/run-graphical-programs-within-vagrantboxes)
