### ISSUE TITLE
responseTimeout is ignored in wait function with alias

### ISSUE THREAD

**Issue by Juliia13** [cypress-io/cypress#17182]
Here is an example of code
The first thing I do is intercept the request, then I want to wait until response will contain expected status in body. But the test is failing after default timeout - 30000ms with the error like this:

Timed out retrying after 30000ms: expected 'Running' to equal 'Completed'

So the test is failing because status is Running, and the expected is Completed. how to increase timeout in this case? 

```js
 cy.intercept('GET', Cypress.config().baseUrl + 'api/scans/' + scanID).as('getStatus');
 cy.visit('/')
 cy.wait('@getStatus', {responseTimeout: 80000}).its('response.body.status').should('eq', 'Completed')
```

**Comment by dlabrecque-uzinakod** [comment]
Same issue with version 9.3.1. 
Regardless of the value I provide to `cy.wait()` to overwrite `responseTimeout `for that one request, it waits for the default `responseTimeout `or the one specified in `cypress.json`.
