### ISSUE TITLE
Mkdirp incompatible with Cypress

### ISSUE THREAD

**Issue by cbruge** [cypress-io/cypress#17185]
I originally created a discussion thread but it might also be a bug on Cypress side.

Closed bug on mkdirp side:

https://github.com/isaacs/node-mkdirp/issues/3

I have json-schema-to-typescript installed as dependency in my project, however since 7.6.0 (7.1.0 still worked somehow) Cypress crashes with Type Error invalid options argument.

This is related to a peer dependency mkdirp, in its opts-arg.js it does not consider typeof function for options (which is somehow being passed in by cypress?)

Is there any way to work around that?

Currently I have put it in devDependencies and ignore it for now and only install that dependency when i need it.

**Comment by jennifer-shehane** [comment]
Can you include the full error and an example of where it is being thrown? Can you provide a repo that we can run to reproduce the error? Thanks.

**Comment by cbruge** [comment]
Hey @jennifer-shehane, I changed the project dependency to quicktype in the end. 

But if you want to reproduce the error, just add json-schema-to-typescript as dependency to your project and start any *.ts spec file inside Cypress. This way it through the error for me reliably.
