### ISSUE TITLE
Cookies not being cleared

### ISSUE THREAD

**Issue by spearmootz** [cypress-io/cypress#17183]
I am on Cypress 7.6.0

On most tests i want to persist session cookies except on the login tests where i try to log in and then later need to do stuff that requires me to not be logged in.

I have in support/index.js

```js
Cypress.Cookies.defaults({
  preserve: ['id_token', 'phr_id', 'access_token', 'refresh_token'],
});
```

In my tests, one of the tests logs in and then subsequently the next tests needs to be logged out.

on the subsequent call i get the cookies from login.  Now i tried to do cy.clearCookies(), i tried to visit /logout and have them cleared in a before each within a context, i tried to do it inline with the tests but every single time the persisted cookies gets added and so the first test after login always fails and then somehow they stop

**Comment by archiekd** [comment]
@spearmootz I am also having this issue! 

Have you found a workaround at all?

**Comment by emilyrohrbough** [comment]
In the upcoming v12.0.0 release, the deprecated `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` will be removed. This has been related with [`cy.session()`](https://docs.cypress.io/api/commands/session). Closing as won't fix.
