### ISSUE TITLE
I am getting The automation client disconnected. Cannot continue running tests. with Cypress 7.6.0

### ISSUE THREAD

**Issue by ChristusArulanantham** [cypress-io/cypress#17181]
This is happening every few minutes and it is really annoying 

Node.js Version (14.15.1)

can you please look into this?

FYI I am not running Cypress in a Docker container but on my Windows machine.
It worked fine in the previous versions.

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Can you specify which previous version you were using where you did not encounter the issue?
