### ISSUE TITLE
Plugin file error in index.js

### ISSUE THREAD

**Issue by kaleos** [cypress-io/cypress#17191]
I am getting an error that states something is wrong with my plugin, I re-installed cucumber using npm install --save-dev cypress-cucumber-preprocessor and got a newer version, but I am still getting this error.
Please refer to the attached images.

![Test Case](https://user-images.githubusercontent.com/13407889/124392375-c14cdd80-dcba-11eb-82f9-84db7dbdbb3a.png)
![index js](https://user-images.githubusercontent.com/13407889/124392380-cdd13600-dcba-11eb-9ca4-2bcc68820902.png)
![cypress json](https://user-images.githubusercontent.com/13407889/124392384-d1fd5380-dcba-11eb-9132-b34d1b0567bf.png)
![package json](https://user-images.githubusercontent.com/13407889/124392387-dcb7e880-dcba-11eb-94d7-ac7db1043846.png)

**Comment by jennifer-shehane** [comment]
I would look in your code where 'Application Regression' is written. Perhaps something is malformed in the cucumber written. Otherwise I would suggest opening an issue with the cypress-cucumber-preprocessor plugin as this plugin is not maintained by Cypress.
