### ISSUE TITLE
Test runner shows passed test despite failed assertion in intercept

### ISSUE THREAD

**Issue by pauwilk** [cypress-io/cypress#17198]
### Current behavior
I have a test where I use intercept and some assertion for the request. If the assertion fails, the test is still marked as "passed" in test runner:
![image](https://user-images.githubusercontent.com/72187888/124483760-fd5f6b80-ddaa-11eb-8b6b-37978b40ff33.png)

### Desired behavior
Failed assertion in intercept should fail the test in test runner

### Test code to reproduce
example test:

```js
describe("Sample test", () => {
  it("should fail when assertion in intercept fails", () => {
    cy.intercept("/login/local?source=dashboard", req => {
      expect(req.body).to.be.eq("fail");
    });
    cy.visit("https://dashboard.cypress.io/login/email");

    // some sample data:
    cy.get("#email").type("test@test.com");
    cy.get("#password").type("abc");
    cy.get("button[type='submit']").click();
  });
});
```

### Versions
cypress 7.6.0
testing on Chrome, Windows 10
running tests locally in cypress test runner

**Comment by bahmutov** [comment]
The test finishes before the intercept throws an error. Read https://www.cypress.io/blog/2020/01/16/when-can-the-test-stop/

**Comment by pauwilk** [comment]
Thanks :)
I've rewritten my test to something like this:
```
describe("Sample test", () => {
  it("should fail when assertion in intercept fails", () => {
    cy.visit("https://dashboard.cypress.io/login/email");

    // some sample data:
    cy.get("#email").type("test@test.com");
    cy.get("#password").type("abc");
    cy.get("button[type='submit']")
      .click()
      .then(() => {
        cy.intercept("/login/local?source=dashboard", req => {
          expect(req.body).to.be.eq("fail");
        }).as("x");
        cy.wait("@x");
      });
  });
});
```

and it fails in test runner for real 👍

**Comment by sainthkh** [comment]
It seems that the problem has been solved and it's safe to close this issue, right?

**Comment by pauwilk** [comment]
Yes, you're right, it's solved
