### ISSUE TITLE
Downloaded files don't go to downloadFolder config, also the filename changes

### ISSUE THREAD

**Issue by lerouxb** [cypress-io/cypress#17195]
### Current behavior

My test clicks a link to download a file. Chrome downloads it and it gets put into ~/Downloads. The filename also gained the prefix `~$`.

### Desired behavior

My understanding of what it should be doing according to the documentation and download recipes is that it should go where  `Cypress.config('downloadsFolder')` points which is `cypress/downloads`. Since I need to use cy.readFile() to read it I have to know what the filename will be, so it should probably match what was specified.

### Test code to reproduce

```javascript
cy.get('.path .to .download .link').click();

const downloadsFolder = Cypress.config('downloadsFolder');
const filename = Path.join(downloadsFolder, expectedFilename);

cy.readFile(filename, 'binary').should((buffer) => { // this never succeeds because the file is not in cypress/downloads and it has a different name
    expect(buffer.length).to.be.gt(100);

    return buffer;
})
.then((buffer) => {
    // do something
});

```

### Versions

Cypress 7.6.0
Chrome 92
macOS Catalina

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? You can modify one of our existing tests to recreate. https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download
