### ISSUE TITLE
Cannot type on arbitrary elements

### ISSUE THREAD

**Issue by MarkAZhang** [cypress-io/cypress#172]
Any element can receive keydown events if it has a tabindex. However, the cypress type command only works on input text elements and textareas. In order to fire keydown events on arbitrary elements, for example if we want to test keyboard shortcuts in an app, we have to manually create a KeyboardEvent and call dispatchEvent on the element. While this is a viable workaround, a solution in cypress would be preferred.

**Comment by bahmutov** [comment]
can it be done using`{force: true}`? Or is Cypress not allowing to type at all in these elements? https://docs.cypress.io/v1.0/docs/type#options-usage

**Comment by brian-mann** [comment]
Nope, the error checking involving the element type happens prior to that. 

This is a pretty easy addition so I'll likely shoot to have this in `0.16.3`.

**Comment by brian-mann** [comment]
Fixed in [`0.16.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0163-06172016).
