### ISSUE TITLE
Cypress saving folders - screenshots/videos/results as root user

### ISSUE THREAD

**Issue by vinamrajais** [cypress-io/cypress#17206]
Cypress is creating folders with "**root**" permission instead of current user "**_csp-builder**"

Running cypress test cases inside docker, followed https://github.com/cypress-io/cypress-example-docker-compose

cypress.json
```
{
  "reporter": "cypress-multi-reporters",
  "defaultCommandTimeout": 20000,
  "chromeWebSecurity": false,
  "reporterOptions": {
    "reporterEnabled": "mochawesome",
    "mochawesomeReporterOptions": {
      "reportDir": "cypress/results/json",
      "overwrite": false,
      "html": false,
      "json": true
    }
  },
  "testFiles": [
    "device/prerequisite.spec.js",
    "device/device-action.spec.js",
    "device/device-inventory.spec.js"
  ]
}
```

### Current behavior

```
 + whoami
 _csp-builder

 + ls -l e2e/cypress
 total 48
 drwxrwxr-x 2 _csp-builder _csp-builder 4096 Jun 29 22:03 api
 drwxrwxr-x 2 _csp-builder _csp-builder 4096 Jun 29 22:03 conf
 drwxrwxr-x 3 _csp-builder _csp-builder 4096 Jun 29 22:03 dom
 drwxrwxr-x 2 _csp-builder _csp-builder 4096 Jun 29 22:03 fixtures
 drwxrwxr-x 4 _csp-builder _csp-builder 4096 Jun 21 10:40 integration
 drwxrwxr-x 2 _csp-builder _csp-builder 4096 Jul  5 20:06 plugins
 -rw-rw-r-- 1 _csp-builder _csp-builder  343 Jun 29 22:03 README.md
 drwxr-xr-x 3 root         root         4096 Jun 30 12:51 results
 drwxr-xr-x 3 root         root         4096 Jul  5 20:07 screenshots
 drwxrwxr-x 2 _csp-builder _csp-builder 4096 Jul  5 20:06 scripts
 drwxrwxr-x 2 _csp-builder _csp-builder 4096 Jun 29 22:03 support
 drwxr-xr-x 3 root         root         4096 Jul  5 20:06 videos
```

### Desired behavior
Generated folders (screenshots/videos/results) should have same user permission "**_csp-builder**"

### Test code to reproduce
Run below project as different user
https://github.com/cypress-io/cypress-example-docker-compose

### Versions
cypress --version
Cypress package version: 7.4.0
Cypress binary version: 7.4.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1

**Comment by vinamrajais** [comment]
@jennifer-shehane Could you or any of cypress team members help with this?

**Comment by flotwig** [comment]
This is not a bug, Docker will run using whatever user ID is specified. By default Docker runs as root. If you want Cypress to run as a different user, configure Docker to use a different user ID.
