### ISSUE TITLE
Fixtures loading slower than equivalent request

### ISSUE THREAD

**Issue by tehandyb** [cypress-io/cypress#1720]
### Current behavior: 

Large fixtures taking longer to load than the same data in an actual request

### Desired behavior: 

Large fixture should take much less time to load than the request.

### Steps to reproduce:
I don't have a repo to do this with as mine is private. The fixture I am using is 1.7mb of json data, the same as generated from my rails backend. It takes 500ms for the real request/response, and takes around 4 seconds when I am using the fixture.

**Comment by jennifer-shehane** [comment]
A reproducible repo would be very helpful to get this narrowed down - may be somewhat related to this issue https://github.com/cypress-io/cypress/issues/76

**Comment by tehandyb** [comment]
@jennifer-shehane Thanks so much. It does seem related to that issue. I tried out @ankri solution and it was an improvement that took about half the time as the original real request. I'll try to come up with a reproducible repo.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
