### ISSUE TITLE
CI: Cypress should log in real time the commands that are executed

### ISSUE THREAD

**Issue by jjkavalam** [cypress-io/cypress#17201]
### Discussed in https://github.com/cypress-io/cypress/discussions/17170

<div type='discussions-op-text'>

<sup>Originally posted by **jjkavalam** July  1, 2021</sup>
In my org, we are trying to troubleshoot an issue with Cypress tests that happen in CI (Github Actions).

Issue is that, randomly (but multiple times a day), test runs timeout and get killed by Github Actions.

After combing through cypress debug logs [1], it appears as though the test is not making progress beyond a certain point. So, it will be greatly helpful to have the commands being executed be logged to the CI logs so that we can know at what point the test is stuck.

Unfortunately, the existing solutions ([2][3]) for logging cypress commands are not useful in this case. This is because, it assumes that the test actually completes (either pass / fail). But in this case, it is simply killed.

So, the ask is to have the command log be send to the CI logs as well.

[1] https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs
[2] https://github.com/bahmutov/cypress-failed-log
[3] https://github.com/archfz/cypress-terminal-report</div>

**Comment by jennifer-shehane** [comment]
Does the cypress-terminal-report not log all commands if `printLogsToConsole` is set to `always`? https://github.com/archfz/cypress-terminal-report#optionsprintlogstoconsole

**Comment by jjkavalam** [comment]
@jennifer-shehane Yes it does; only if the test actually completes (either pass or fail).

It is not useful for cases where the test time out or is killed for some reason. In this case, there is no way to know which command was last executed.

**Comment by rsouthgate** [comment]
Just to add a +1 to this. We experience this behaviour in Azure Devops. Every other pipeline command can be essentially tailed and watched while in progress. But our cypress command (just a cypress run cli command) will not output anything until the task completes. I don't know the inner workings of cypress but it seems like it should be streaming output to stdout at this point but in fact must be buffering internally. The same command run on my local dev mac does not behave the same - there I seem to get a stream of output. No idea what the difference is in CI env.

**Comment by jjkavalam** [comment]
@rsouthgate It's interesting if you are able to get a stream of output at least on your dev Mac ... could you give details of how that streaming output looks like and if you did any configuration for the same ?

(Hope you are not referring to the command log rendered in the browser window)

**Comment by rsouthgate** [comment]
@jjkavalam Running --headless on my mac I get a console output which is updated as each spec file is run:

<img width="1052" alt="Screen Shot 2021-07-20 at 8 25 56 AM" src="https://user-images.githubusercontent.com/362909/126222875-bb260e7e-a7c9-4494-abad-7afb20fcd901.png">

This is what I'm missing in the pipeline. This entire console output is only updated when the task completes.

**Comment by jjkavalam** [comment]
@rsouthgate Thank you. 

@jennifer-shehane Waiting for a response ...

**Comment by rsouthgate** [comment]
@jennifer-shehane Just wondering if there is any movement on this. We've updated to cypress 8.7.0. Still see the same behaviour of logs not output in our CI environment until the whole suite completes. Could this at least have the 'awaiting response' label removed?

**Comment by adriannieto-attechnest** [comment]
This is also affecting us but we are not sure if this is a gitlab or cypress issue or a combination of both, at left you can see the result of kubernetes console log for the pod running the build on gitlab, and right shows current gitlab log. 

When build finishes all output is displayed, but no progress is shown during the CI process:

![image](https://user-images.githubusercontent.com/88320765/148924755-26ab8ab0-2ae1-4792-857c-e1fb388678f8.png)

**Comment by iljapavlovs** [comment]
Any news when this will be fixed?

**Comment by rsouthgate** [comment]
@jennifer-shehane Could the awaiting response flag be removed from this? I'm desperate for it to be looked into but it seems to be stuck without anyone looking at it.

**Comment by mthornton-globality** [comment]
Hi, @jennifer-shehane I am also curious if there are any updates here? Thanks!

**Comment by Napster134** [comment]
@jennifer-shehane  

We're running into this issue as well. We're trying to debug a hanging test but no way for us to know where/when it stopped executing. 
 
please help 😢

**Comment by aspacek-se** [comment]
Azure DevOps user here- fixed this by switching from the 'npm' task to a generic shell command. Apparently this is inherent to the 'npm' task and there are no plans to fix it: https://github.com/microsoft/azure-pipelines-tasks/issues/8171

I think the 'npm authenticate' task followed a dedicated test runner is the preferred solution, but I'm not sure
