### ISSUE TITLE
Webpack Preprocessor not installing on OSX (darwin)

### ISSUE THREAD

**Issue by DanielLuu** [cypress-io/cypress#17213]
### Current behavior
Getting `The platform "darwin" is incompatible with this module.` when trying to install the webpack preprocessor

### Operating System
- [x] Mac

**Comment by emilyrohrbough** [comment]
@DanielLuu can you please provide more information? I was able to successfully install on a Mac with both npm and yarn.
```
npm install @cypress/webpack-preprocessor
yarn add @cypress/webpack-preprocessor
``
