### ISSUE TITLE
Plugin support for custom keyboard shortcuts

### ISSUE THREAD

**Issue by alycda** [cypress-io/cypress#17219]
### What would you like?
I would like for a Custom Plugin to be able to add additional keyboard shortcuts (like these: https://docs.cypress.io/guides/core-concepts/test-runner#Keyboard-Shortcuts)

### Why is this needed?
I am aware that I can invoke keyboard commands for the AUT, but I would like to add some commands that can be invoked while the runner is paused. Basic example: UP/DOWN/LEFT/RIGHT arrow keys can be mapped to a custom Cy Command on the AUT (not in the Node env).

**Comment by sainthkh** [comment]
Sorry for the late reply.

It's a bit hard for me to understand how the keyboard shortcuts can improve your testing process.

Can you give us a more specific example?

**Comment by alycda** [comment]
Hi,

We have a need to test an application that doesn't have any UI for the cypress runner to "interact" with. A workaround is for us to create a testing iframe, that loads our application. The test iframe can contain dom elements for cypress to interact with, which ultimately just fires a command via the window to our actual application. But since cypress already loads our app inside an iframe, I'd prefer to not have to make the intermediary iframe just to send commands to our application. 

This is for a video player that doesn't have any controls, it is controlled via window messaging. Not your typical website, but it is utilized in a modern browser.

**Comment by sainthkh** [comment]
I don't know the internals of your video player. But I guess this can be tested with `cy.window()` like below:

```js
cy.window().then(win => {
  const player = win.document.getElementById('#video-player')
  sendPlayerMessage()
})

// assert
```

Maybe `cy.wait()` might be needed.

**Comment by alycda** [comment]
@sainthkh we are already doing that, to test some parts of the application, but we still have a need to interact with the AUT while paused, and we would need to type directly into the console to run our commands. 

We have workarounds, but I would still like the ability to add additional keyboard shortcuts so that while the application is paused, I can press keyboard keys and trigger events that have been configured via a cypress plugin (again, to avoid the need for an interim iframe to add a fake UI).

**Comment by johnzhang-redspace** [comment]
Hi @sainthkh, I would like to request this suggestion as well. By being able to map custom keyboard keys to commands, it will greatly improve the `accessibility` of the tool for our testers on the team. As well, we will be able to utilize Cypress to interact with the application during tests (as it does not have an UI) to change configuration on the fly.

Thank you.
