### ISSUE TITLE
Content-Length is missing from chunked blob response

### ISSUE THREAD

**Issue by adi518** [cypress-io/cypress#17210]
### Current behavior
None of the chunked blob responses include a content-length header.

### Desired behavior
Every response should include a content-length header.

### Versions
Cypress 7.0.6, macOS 11.4, Chrome 91.0.4472.114.

**Comment by sainthkh** [comment]
Sorry for the late reply.

Can you give us a reproducible example? As we know, debugging starts with reproducing the bug on the developer's machine.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
