### ISSUE TITLE
screenshot Duplicated  issue

### ISSUE THREAD

**Issue by shiralwz** [cypress-io/cypress#17225]
I was using cy. screenshot() to take a screenshot for full-page, the page is quite a large one, but the top 2 snapshot seems duplicated.

```
    cy.visit('https://www.xxx.com');
    cy.wait(10000);
    cy.screenshot('guide');
```

![image](https://user-images.githubusercontent.com/6162142/124699899-d38b7d80-df3f-11eb-9b7e-791c75d2cdab.png)

**Comment by jennifer-shehane** [comment]
This is likely a duplicate of https://github.com/cypress-io/cypress/issues/7966

**Comment by shiralwz** [comment]
Hi @jennifer-shehane  it seems the website I'm taking screenshots of is a little bit different than the example you provided.

https://www.harmoney.co.nz/personal-loans/debt-consolidation/guide-to-debt-consolidation-ebook

there is no main tag in the HTML body.
Could you explain more about this issue?
thank you very much.

**Comment by panzarino** [comment]
@shiralwz Looking at the state of the linked issue and from my own knowledge of the issue, I don't think that we've found a fix (or at least a workaround) yet but @jennifer-shehane would probably know better than I would
