### ISSUE TITLE
Cypress is not failing tests due to uncaught promise error

### ISSUE THREAD

**Issue by mgmpskywalker07** [cypress-io/cypress#17222]
Might be related to these issues:
- https://github.com/cypress-io/cypress/issues/243
- https://github.com/cypress-io/cypress/issues/2487

### Current behavior
Uncaught exceptions from a promise are logged but does not fail the test
![image](https://user-images.githubusercontent.com/54514617/124682129-ea1dd000-de7e-11eb-93ef-384a37334add.png)

Same for rejected promises
![image](https://user-images.githubusercontent.com/54514617/124682432-93fd5c80-de7f-11eb-86b8-2e3065b4d2e7.png)

### Desired behavior
A test should fail for any uncaught exception / promise generated from the test. 

### Test code to reproduce
To test rejected promise use this
```
function test() {
    return new Promise<any>((resolve: (value?: any) => void, reject: (reason?: any) => void):any  => {
        reject("abcd");
    });
}
context("Test", () => {
    // tslint:disable-next-line:no-empty
    beforeEach(() => {
    });
    it('Do something',() => {
        test()
            .then((value:any)=>{
                // throw new Error();
                console.log("here")
        });
    })
});
```
To test uncaught error from promise use this
```
function test() {
    return new Promise<any>((resolve: (value?: any) => void, reject: (reason?: any) => void):any  => {
        resolve("abcd");
    });
}
context("Test", () => {
    // tslint:disable-next-line:no-empty
    beforeEach(() => {
    });
    it('Do something',() => {
        test()
            .then((value:any)=>{
                throw new Error();
                // console.log("here")
        });
    })
});
```

### Versions
7.5.0, Electron 89, Mac

**Comment by bahmutov** [comment]
In your code, you never tell Cypress test to wait for the promise - thus the test completes before the rejection happens. You should use `cy.wrap` as shown https://docs.cypress.io/api/commands/wrap#Promises to tell Cypress - hey, here is a promise, wait for it, and if it is rejected, fail the test

```js
it('Do something',() => {
    cy.wrap(test())
})
```

**Comment by mgmpskywalker07** [comment]
That does work thank you
