### ISSUE TITLE
`auth` option on cy.visit doesn't seem to work with "https" domain

### ISSUE THREAD

**Issue by pablote** [cypress-io/cypress#1723]
### Current behavior: 

I get an "Unauthorized" error when trying to access an https site using the `auth` option in `cy.visit()`.

![1](https://user-images.githubusercontent.com/2463995/40081389-36919524-5864-11e8-9c2c-86b92996eb1b.png)

Authentication is set like this:

```js
Cypress.Commands.overwrite('visit', (orig, url, options) => {
    options = options || {};
    options.auth = {
      username: Cypress.env('AUTH_USER'),
      password: Cypress.env('AUTH_PASS')
    };
    return orig(url, options)
});
```

If I set the same username/password in the url instead before the host name, then it works fine:
![2](https://user-images.githubusercontent.com/2463995/40081502-949faa02-5864-11e8-8b33-1dbe97274717.png)

Bad thing about this is, username/password on the url works fine on chrome but not on electron: https://github.com/cypress-io/cypress/issues/1639. 

So right now I'm unable to test an https site headless from CI.

### Desired behavior:

I can access https site, using `auth` option.

### Steps to reproduce:

Try to access an https site, with basic security, and use the `auth` option in `cy.visit()` to authenticate.

### Versions  
Cypress 2.1.0
macOS 10.13.4
Chrome 66, Electron 59

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
