### ISSUE TITLE
Cannot login to my app with discord OAuth2 using cypress

### ISSUE THREAD

**Issue by BugrahanDurukan** [cypress-io/cypress#17235]
### Discussed in https://github.com/cypress-io/cypress/discussions/17234

<div type='discussions-op-text'>

<sup>Originally posted by **BugrahanDurukan** July  7, 2021</sup>
Hello, I recently came across cypress. I really liked it at the first sight. Cypress has helped me a lot in terms of speed. However, there are a couple of issues that came with it. My app uses discord OAuth2 to log in. When I use cypress with chrome to log in to my app, my app throws me to the login back again. My app doesn't do that when I use it manually or simply use mocha. I really like cypress and I wanna recommend everyone in my organization to use it but I really need to fix this issue first. 

"Login" button clicked on the main page >> app sends me to discord OAuth2 authentication page >> "authenticate" button clicked >> redirect back to main page??????
Do I need to do something similar to the documentation provided for the Google OAuth2

Also, When I use cypress with electron it logs in correctly but the requests I send to my backend would return 401

![image](https://user-images.githubusercontent.com/34229203/124763693-ed779100-df3c-11eb-9cae-d33ac1c5059b.png)
</div>

**Comment by AtofStryker** [comment]
@BugrahanDurukan would you be able to try this with the `experimentalSessionAndOrigin` feature in Cypress `10.11.0`? I am going to close due to inactivity, but if this is still an issue for you please let us know and we can reopen!
