### ISSUE TITLE
command timeout in the test body causes afterEach hook to fail unexpectedly

### ISSUE THREAD

**Issue by jjkavalam** [cypress-io/cypress#17232]
### Current behavior

When a custom command that returns a promise is timed out, commands in the afterEach hook fails unexpectedly

### Desired behavior

After hooks should not be affected by failure of commands in the test body

### Test code to reproduce

https://github.com/jjkavalam/cypress-test-promise

### Versions

Cypress: 7.6.0

**Comment by jjkavalam** [comment]
## https://github.com/jjkavalam/cypress-test-promise

```js
// cypress/integration/start.spec.js

describe('issue', function () {
    it('fails', function () {
        // use a delay greater than the command timeout
        cy.returnPromiseThatResolvesAfter(5000);
    })
    afterEach(() => {
        cy.wait(1); // fails !! In my understanding, it could be any command here
    })
})


// cypress/support/commands.js

Cypress.Commands.add('returnPromiseThatResolvesAfter', function (n) {
    return Cypress.Promise.delay(n);
})

```

**Comment by bahmutov** [comment]
Do not return a promise from Cypress command. If you really need to wait on a promise, use `cy.wrap`

```js
Cypress.Commands.add('returnPromiseThatResolvesAfter', function (n) {
    cy.wrap(Cypress.Promise.delay(n))
})
```
