### ISSUE TITLE
npm install failing on 2.1.0

### ISSUE THREAD

**Issue by pixeleet** [cypress-io/cypress#1724]
### Current behavior: 
npm install broken

```
pixeleet in ~/Workspace/cypress on develop*
⚡ cat  /Users/pixeleet/.npm/_logs/2018-05-16T09_11_25_208Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/pixeleet/.nvm/versions/node/v8.2.1/bin/node',
1 verbose cli   '/Users/pixeleet/.nvm/versions/node/v8.2.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'all',
1 verbose cli   'install' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'preall', 'all', 'postall' ]
5 info lifecycle cypress@2.1.0~preall: cypress@2.1.0
6 info lifecycle cypress@2.1.0~all: cypress@2.1.0
7 verbose lifecycle cypress@2.1.0~all: unsafe-perm in lifecycle true
8 verbose lifecycle cypress@2.1.0~all: PATH: /Users/pixeleet/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/pixeleet/Workspace/cypress/node_modules/.bin:/Users/pixeleet/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/pixeleet/Workspace/cypress/node_modules/.bin:/Users/pixeleet/.nvm/versions/node/v8.2.1/bin:/Users/pixeleet/.rvm/gems/ruby-2.3.4/bin:/Users/pixeleet/.rvm/gems/ruby-2.3.4@global/bin:/Users/pixeleet/.rvm/rubies/ruby-2.3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pixeleet/.rvm/bin:/usr/local/opt/go/libexec/bin:/bin:/Users/pixeleet/.local/bin:/Users/pixeleet/.rvm/bin
9 verbose lifecycle cypress@2.1.0~all: CWD: /Users/pixeleet/Workspace/cypress
10 silly lifecycle cypress@2.1.0~all: Args: [ '-c', 'node ./scripts/run.js "install"' ]
11 silly lifecycle cypress@2.1.0~all: Returned: code: 1  signal: null
12 info lifecycle cypress@2.1.0~all: Failed to exec all script
13 verbose stack Error: cypress@2.1.0 all: `node ./scripts/run.js "install"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/pixeleet/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/pixeleet/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid cypress@2.1.0
15 verbose cwd /Users/pixeleet/Workspace/cypress
16 verbose Darwin 16.7.0
17 verbose argv "/Users/pixeleet/.nvm/versions/node/v8.2.1/bin/node" "/Users/pixeleet/.nvm/versions/node/v8.2.1/bin/npm" "run" "all" "install"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error cypress@2.1.0 all: `node ./scripts/run.js "install"`
22 error Exit status 1
23 error Failed at the cypress@2.1.0 all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Desired behavior:
npm install works

### Steps to reproduce:
- clone cypress repo
- npm install

### Versions  
Cypress 2.1.0
macOS Sierra 10.12.6
Node versions tried: 8.2.1 (.node-version), 10

**Comment by pixeleet** [comment]
Yep I just cloned it and went for an npm install, branch is indeed `develop` of `cypress`

**Comment by jennifer-shehane** [comment]
Yeah - we've been merging PRs in left and right into develop for our upcoming release, although it should we haven't encountered an issue `npm install`. Check that you have the latest commits by pulling if you want to run our newest `develop` branch - or change to `master` branch if you just want 2.1.0 standard release.

**Comment by egucciar** [comment]
@jennifer-shehane i can confirm that running `npm install` on develop branch is currently not working, whereas running the same on master branch worked.

**Comment by jennifer-shehane** [comment]
We suspect this may be due to a bug in a previous version of `npm`. 
- What version are you using? 
- Could you try updating `npm`? 
- I am using `npm` version `5.2.0`

**Comment by naseem-qadium** [comment]
I seem to be having the same problem. https://github.com/cypress-io/cypress/pull/1778

**Comment by egucciar** [comment]
@jennifer-shehane my npm version is 5.6.0 and the issue is still occurring.

**Comment by egucciar** [comment]
@jennifer-shehane upgraded to 6.1.0 and same problem.

I think removing node_modules solves it, but since the node_modules folder exists within all the packages folders its not easy to get rid of all of them in one fell swoop.

Can you guys advise?

**Comment by Bkucera** [comment]
@egucciar since we are structured as a monorepo, the way to clear them would be to `cd` into each folder and `rm -rf node_modules` 
I don't suggest you do this, but it might work: **in the cypress repo** `rm -rf  */*/node_modules`

**Comment by jennifer-shehane** [comment]
@Bkucera You can do the equivalent of this from the main dir with `npm run clean-deps` instead of targeting each package dir.

**Comment by jennifer-shehane** [comment]
Perhaps try it on `npm 5.2.0`? :( I had an issue recently in a repo that was solved by this.

**Comment by Bkucera** [comment]
For anyone else having trouble building the repo, ensure your node version matches the `node-version` file

**Comment by kshitijmjoshi** [comment]
I am facing the same problem.
I tried npm i with node -v 8.11, 8.4, 8.2.1 (.node-version file) & 6.5.0
Used npm -v 5.2 & 5.6.
npm i works with node -v 6.5.0 and npm -v 5.2 if I install babelify & babel-core manually.
Still it gives me error when I try to do a npm run binary-build to package the app.
