### ISSUE TITLE
Cypress version 7.7.0 issue on CircleCI - name too long

### ISSUE THREAD

**Issue by ztulic** [cypress-io/cypress#17246]
### Current behavior
When running cypress on CircleCI there is an error
{
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'stat',
  path: 'cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration/cypress/integration'
} 

### Test code to reproduce
It doesn't happen in local.

Have at least 40 test specs in Cypress.
And have them in cypress.json as they need to run in particular order.
Start tests on CircleCI.

The issue is not reproducible if they are missing in cypress.json file

### Versions that this worked previously

7.6.0

**Comment by jennifer-shehane** [comment]
>Have at least 40 test specs in Cypress.
And have them in cypress.json as they need to run in particular order.

Can you provide your `cypress.json` file? 

We haven't seen this issue before, so would like to track down what configuration would cause this. If you could provide a repo that would  reproduce the is that would be ideal.

**Comment by ztulic** [comment]
Hi @jennifer-shehane

Thanks for a quick replay.
I've figure it out.
In cypress.json I have one test file that is running only in local and it's not committed.
Removing it from testFiles seems to fix the issue.

Issue is reproducible in local too if there is a test in testFiles that doesn't exist.

I would still like you to try reproducing it, just put one test that doesn't exist in the list like this:
```
"testFiles": [
    "user/test1.js",
    "user/test2.js"
  ]
```
test2.js - exist
test1.js - doesn't exist

**Comment by mfaidagit** [comment]
Hi @ztulic,
I want to thank you for your message.
I searched all over the web about this problem, and there were many answers about node js and stuff.
my problem was the same, some files were missing but it was working with cypress version 6.2.1. When i upgrade to the latest version it gives me the same error as yours
once again, thank you
