### ISSUE TITLE
websocket fails before cypress version 6.0 and later

### ISSUE THREAD

**Issue by jgarcia1095** [cypress-io/cypress#17244]
The problem is that my application uses a web socket safely, and I was using cypress without problems but when updating to any version older than 6.0, cypress produces a failure in the web socket, it is very important to understand that I am not mocking on it web socket.

it happens that instead of delivering the websocket messages, it generates an error stating the following-> HTTP authentication error; no valid credentials available

I can't share the project because it works with an application of my current job, but if I run the test with version 5.0.0 I have no problems but with 7.7.0 if the error occurs

I clarify that we use a security header which is Sec-WebSocket-Protocol and it does not change by using some version of cypress

example with 5.0.0
![image](https://user-images.githubusercontent.com/42305193/124860106-b920c680-df76-11eb-96aa-53fdad306374.png)

example with 7.7.0
![image](https://user-images.githubusercontent.com/42305193/124860347-1caaf400-df77-11eb-8631-53e011bd4657.png)
![image](https://user-images.githubusercontent.com/42305193/124860372-27658900-df77-11eb-9eae-a335bb2baf02.png)

It is also important to mention that it does not generate any problem if the web socket is not secure.
![image](https://user-images.githubusercontent.com/42305193/124860717-c68a8080-df77-11eb-8c05-3f4df65ccd7b.png)

**Comment by adilconstantine** [comment]
Im running into same issue. Any update on this?

**Comment by souravsaraf123** [comment]
I am also facing this issue , any fix to this ?

**Comment by jgarcia1095** [comment]
I have had no response so far, I had to work with version 5.
