### ISSUE TITLE
Cypress erasing cookies during test when running on Chrome

### ISSUE THREAD

**Issue by Zach-Costa** [cypress-io/cypress#17254]
Recently, my org has made an overhaul to our SAML Identity Provider for internal users. Before now, we were using a hybrid of Auth0 and OneLogin to access our internal app, but we've now moved to a hybrid of Auth0 and Okta. Our specs have always logged in via the UI with no issues, and we were able to log in through our new system via UI without any problems. After a couple of weeks, however, our specs began to encounter an issue where the session token would be removed after logging in, redirecting the test to our "Not Logged in" landing page.

### Expected behavior
Here's how our current system works:

User tries to access app without an active session
Auth0 makes a request to Okta for authentication
Okta redirects the user to the Okta login page
User submits a valid username, password, and passcode
Okta sets a session token for the user and forwards a SAML response to Auth0
Auth0 sends a JWT to a callback URL in our Rails application, which validates the token, records some data from the token into the user's session, and redirects the user
The app reads the token data out of the session and signs the user into our system

### Current behavior
When running Cypress on Electron, Firefox, or in Headless mode, this works exactly as described above. However, when running in Chrome, the session cookie gets dropped between steps 6 and 7, resulting in the spec failing. This ONLY occurs when running tests against the Chrome browser, and it also ONLY occurs with Cypress.

When logging the Cookie changes with Cypress.Cookies.debug(), nothing is reported when the session token gets dropped. In addition, no warnings or errors are reported in the Chrome DevTools console while running the tests. However, we've been able to confirm that this issue is Cypress-specific, and occurs consistently 100% of the time. As Chrome is the browser we've always recommended users use with our app, it's been a huge blocker and time sink not being able to run tests on the main browser we support.

I'm aware that Cypress clears out the cookies between tests, but this issue is happening in the middle of the beforeEach() step, which shouldn't happen.

### Fixes already attempted

- Adding in Cypress.Cookies.preserveOnce("session_token") does not work, the session token still gets dropped
- We're still investigating logging in via the API, but since we actually do need to test the login flow that our end-users will go through, this would only be a solution for some of our tests. We need to be able to login via the UI to make sure we're testing our login flow as well. In addition, the Okta API token gives more permissions than our security team is comfortable with giving to a large group of people
- We've run our tests in secure Docker Image to remove any discrepancies caused by our local environments. We've also attempted setting up a brand new Cypress repo to test against. In both instances, the bug occurred.
- Tried programmatically pulling the session ID after it's set, and then resetting it after the cookie is dropped. This resulted in an unusual state where the user became logged into Okta, but Auth0 would no longer recognize the token.
- We've tried reverting to older versions of Chrome. This is not a Chrome issue, but an issue with how Cypress is interacting with Okta

### Versions
This has been tested on several builds, including 7.2.0, 6.3.0, and 5.2.0. The bug seems to be version-agnostic.

**Comment by Zach-Costa** [comment]
This is a repost of issue #17045, as that one was being ignored due to the "Awaiting response" label.

**Comment by jennifer-shehane** [comment]
Please do not open duplicate issues. We'll address issues when we have the time to address them. Opening separate threads just creates more misdirection on previous conversations and context.
