### ISSUE TITLE
cy.route doesn't match http calls to .js resources

### ISSUE THREAD

**Issue by pixeleet** [cypress-io/cypress#1725]
### Current behavior: 
![image](https://user-images.githubusercontent.com/5776997/40112071-20dee5aa-5905-11e8-9e38-9163b841b5d1.png)
(Notice how # is - because cypress doesn't think the route is matched)

Interestingly the response handler is still called and the log appears in the console.

### Desired behavior:
I'd like the route to match and be able to replace the contents of the resource I'm trying to hijack.

### Steps to reproduce:

```js
describe('Route matching fails', function () {
    it('fail matching routes', function () {
        cy.server()
        cy.route({
            method: 'GET',
            url: 'https://consent.snmmd.nl/js/cookiebar-latest.js',
            response: (req) => {
                console.log('[REQUEST] JavaScript');
            }
        })
        cy.visit('http://www.nu.nl')
    })
})
```

### Versions  
Cypress 2.1.0
macOS 10.12.6
Node 10.0.0

**Comment by pixeleet** [comment]
```js
/* global cy, Cypress, assert */
describe('Route matching fails', function () {
    it('fail matching routes', function () {
        cy.server({
            whitelist: (xhr) => {
                // specify your own function that should return
                // truthy if you want this xhr to be ignored,
                // not logged, and not stubbed.
                console.log('[wHITELIST]', xhr.url)
                return false
            }
        })
        cy.route({
            method: 'GET',
            url: 'https://consent.snmmd.nl/js/cookiebar-latest.js',
            response: (req) => {
                console.log('[REQUEST] JavaScript', req.url, Cypress.minimatch('https://consent.snmmd.nl/js/cookiebar-latest.js', 'https://consent.snmmd.nl/js/cookiebar-latest.js'));
            }
        })
        cy.visit('http://www.nu.nl')
    })
})
```

**Comment by mledom** [comment]
@pixeleet were you able to get the whitelist function to work? I'm trying to do something similar but always only see the XHR request that are by default.

**Comment by jeremyrader** [comment]
I'm reporting the same as @mledom. I only see the XHR requests that are on by default.
v 3.1.0

**Comment by jennifer-shehane** [comment]
I looked into this issue a bit because I was unsure if this was a bug or intended behavior as well. 

The requests you are wanting to track in the Command Log are JavaScript resources loading, not XHR requests. **Cypress currently only logs XHR requests within the Command Log**, although we have intentions to [track more in the future](https://github.com/cypress-io/cypress/issues/687). 

They will **not** be logged no matter what you define in the `whitelist` function for `cy.server()`, because this has not been coded in Cypress.

We realized this is not made clear enough in the documentation, and apologize for the confusion. We have [plans to update the docs ](https://github.com/cypress-io/cypress-documentation/issues/1297) to make it clearer that Cypress only tracks XHR requests.

I will leave this issue opened as a requested feature.

**Comment by jennifer-shehane** [comment]
Have been thinking about this some. I thought maybe some people would find it useful to hook into the `onLoad` event and edit the `<head>` directly, maybe edit the JS resources here.

```js
cy.visit('https://example.cypress.io', {
  onBeforeLoad: (contentWindow) => {
    // contentWindow is the remote page's window object
    contentWindow.document.head
    // I can change the <head> however I want here
    // including <script> src or content
  },
})
```

**Comment by corey-aloia** [comment]
@jennifer-shehane thanks for sharing! In the case of dynamically loaded scripts (like tracking solutions) this is a bit more difficult. This is what I came up with. Although Im not proud of it, it works:
`cy.visit('https://example.cypress.io', {
onBeforeLoad: contentWindow => {
          const oldAppendChild = contentWindow.document.head.appendChild;
          contentWindow.document.head.appendChild = <T extends Node>(
            newChild
          ): T => {
            if (
              newChild &&
              (<HTMLScriptElement>(<any>newChild)).src &&
              (<HTMLScriptElement>(<any>newChild)).src.indexOf(
                'my-script'
              ) !== -1
            ) {
              doStuffBesidesLoading();
              return newChild;
            }
            return oldAppendChild(newChild);
          };
        },
})`

Maybe someone else has a better solution?

**Comment by jennifer-shehane** [comment]
cy.route() and cy.server() are now deprecated. We suggest migrating to cy.intercept(). Open a new issue if you encounter one with intercepting calls to .js resources using [cy.intercept()](https://docs.cypress.io/api/commands/intercept).
