### ISSUE TITLE
Ability to copy request as curl

### ISSUE THREAD

**Issue by raphaelmatori** [cypress-io/cypress#17264]
### What would you like?

During http calls, cypress could have a button to allow us to copy the request as curl, or either, another formats.

### Why is this needed?
When testing applications as QAs Analysts, we constantly need to inspect requests and also to replicate some of them using another applications such as Postman. 

We are able to see the request opening the browser debugger. However, when doing this all day long for months, we see that we could save lots of clicks and, of course, our time.

**Comment by Bruna-Siqueira** [comment]
It would be great having this curl feature at cypress, I believe it would save a lot of time for us QAs that use Cypress to test APIs. I use automated tests in cypress also to generate data mass for other tests that I need to run manually and I have to copy every information one by one to my postman request.

**Comment by jennifer-shehane** [comment]
Since this request has not gotten a lot of interest over the years, we’ll close this issue.
