### ISSUE TITLE
DOM snapshots that use @import directive are not restored correctly.

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#17263]
Cypress v7.7.0 (but all versions of Cypress are affected I believe)

I have noticed a pretty terrible jumping when using time-traveling debugger in Cypress. All DOM snapshots are jumping, the element overlays are incorrect, making the debugging impossible. I have finally traced it to the CSS style attribute used by the application. As many modern apps, the site imports a reset.css stylesheet (similar to https://necolas.github.io/normalize.css/) using the `@import url()` keyword. In that case the time-traveling DOM snapshots are really bad.

I created a reproduction in https://github.com/cypress-io/cypress-test-tiny/tree/import-css-demo showing what is working and what is not woring

### Using style tag without any imports

If the reset style is directly included in the HTML, there is no problem

```html
<html>
  <head>
    <!-- reset CSS style -->
    <style>
      body {
        margin: 0;
      }
      button,
      input,
      optgroup,
      select,
      textarea {
        font-family: inherit;
        font-size: 100%;
        line-height: 1.15;
        margin: 0;
      }
    </style>
    <style>
      .signup {
        border: 1px;
        cursor: pointer;
        color: red;
        background: yellow;
        padding: 2em;
        margin-left: 10em;
        margin-top: 2em;
        width: 8em;
      }
    </style>
  </head>
  <body>
    <button class="signup">Sign up</button>
  </body>
</html>
```

https://user-images.githubusercontent.com/2212006/125084591-b5389580-e097-11eb-92c9-ce8ab126503d.mp4

### Using linked stylesheet

We can move the reset style into its own CSS resource and link it from the doc

```html
<html>
  <head>
    <!-- reset CSS style via link -->
    <link rel="stylesheet" href="cypress/fixtures/reset.css" />
    <style>
      .signup {
        border: 1px;
        cursor: pointer;
        color: red;
        background: yellow;
        padding: 2em;
        margin-left: 10em;
        margin-top: 2em;
        width: 8em;
      }
    </style>
  </head>
  <body>
    <button class="signup">Sign up</button>
  </body>
</html>
```

DOM snapshots work great.

https://user-images.githubusercontent.com/2212006/125085060-2d9f5680-e098-11eb-8994-c672fb5612f3.mp4

## Not working

Now imagine the style is imported using `@import url` directive

```html
<html>
  <head>
    <!-- reset CSS style via import -->
    <style>
      @import url('cypress/fixtures/reset.css');
    </style>
    <style>
      .signup {
        border: 1px;
        cursor: pointer;
        color: red;
        background: yellow;
        padding: 2em;
        margin-left: 10em;
        margin-top: 2em;
        width: 8em;
      }
    </style>
  </head>
  <body>
    <button class="signup">Sign up</button>
  </body>
</html>
```

The DOM snapshot shows "jump" while the CSS is loaded

https://user-images.githubusercontent.com/2212006/125085305-6f300180-e098-11eb-859f-8ec9c88881a8.mp4

The the imported CSS resource is remote, the jumps are even more pronounced. I have simulated the CSS delay using an intercept

```js
it('DOM snapshots jump with CSS resource delay', () => {
  cy.intercept('reset.css', {
    fixture: 'reset.css',
    delay: 500,
  })
  cy.visit('index-with-css-import.html')
  cy.get('button').click()
})
```
Notice how the test runner is making the CSS request again and again.

https://user-images.githubusercontent.com/2212006/125085720-e36aa500-e098-11eb-99e5-c8cb57c4b4d9.mp4

## Expected result

No DOM jumps in time-traveling debugger. In a larger site it becomes impossible to use the debugger.

**Comment by jennifer-shehane** [comment]
Yah it doesn't look like a regression, went back to 6.0.0.
