### ISSUE TITLE
Timed out retrying after 4000ms: Expected to find element xxxxxxxxxxxxxx but never found it.

### ISSUE THREAD

**Issue by SebasProgrammer2020** [cypress-io/cypress#17265]
### Versions
    "cypress": "^7.6.0",

, Browser and version: available on cypress:open interface
, Operating System: linux
, CI Provider: gitlab

related to,
CypressError: Timed out retrying: Expected to find element: '#name', but never found it. #6811
in which never got a solution
I have read all that one

### Current behavior
I am having this issue, bug, problem when try to run cypress integrated with gitlab

cypress dashboard
![](https://cdn.discordapp.com/attachments/689206146376007741/863130397285941248/unknown.png)

gitlab pipeline
![](https://cdn.discordapp.com/attachments/689206146376007741/863130279752105984/unknown.png)

i have tried first with normal 
cy.contains by did not work

and also try with 
cy.get(selector)

but neither 

in locally it runs perfectly but when I run in gitlab it fails

### Desired behavior
that it works and pass all the test

### Test code to reproduce

`	<h3 className="text-yellow-600 text-2xl" name="warehouseWelcomeTitle">Welcome</h3>`

` it("Accessing to welcome page", () => {
    cy.visit(`/auth/${token}`);
    cy.get('[name="warehouseWelcomeTitle"]');
  });`

PLEASE HELP

**Comment by jennifer-shehane** [comment]
@SebasProgrammer2020 Have you tried recording the video or looking at the screenshot taken on failure? What is tthe state of the app when shown in the video/screenshot - why is this element not present? 

Sometimes there's variation in the way things fun in CI. I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

**Comment by SebasProgrammer2020** [comment]
https://user-images.githubusercontent.com/60513462/125149852-22344580-e101-11eb-9421-635908375649.mp4

well the video is loading nothing, 

is there any way to take a screenshot per every time or step?

![image](https://user-images.githubusercontent.com/60513462/125149972-ed74be00-e101-11eb-89bc-5393dea510b4.png)

screenshot in first step also, because it only took it when fails.

why is this element not present?
is not that is no present, it that never gets there.

**Comment by SebasProgrammer2020** [comment]
taken from https://docs.cypress.io/faq/questions/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI
There is a problem isolated to the Electron browser (cypress run by default runs in the Electron browser)

![image](https://user-images.githubusercontent.com/60513462/125302735-d7c5eb00-e2f1-11eb-81ba-4cf18dab4fe8.png)
-now running on chrome


taken from https://docs.cypress.io/faq/questions/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI
A test failure in CI could be highlighting a bug in your CI build process
-there is not problem in my CI build process

**Comment by jennifer-shehane** [comment]
@SebasProgrammer2020 Since the video is freezing, this usually indicates that the machine you're' running the tests on does not have enough resources (CPU/memory). Do you know the CPU/memory of the machine it's running on?

You can log the memory and CPU usage of Cypress by following these instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage This will help determine if Cypress is running out of resources and whether the machine requires more.

This might explain why the application would lock up and potentially not be loading in the 4 seconds needed to get the element.

**Comment by SebasProgrammer2020** [comment]
in which file or where should i set this ?

DEBUG=cypress:server:util:process_profiler cypress run

**Comment by SebasProgrammer2020** [comment]
![image](https://user-images.githubusercontent.com/60513462/126016095-16643fec-3d77-4e85-a3e7-fd464108dbf5.png)


i wanna tell u that finally solution the problem, it was some env variable that were missing in the stage.

**Comment by SebasProgrammer2020** [comment]
thanks for everything, by the way.

**Comment by ChenYanting** [comment]
I got the same issue, but it happens in github workflow. Everything works fine and perfect locally, however when it runs in github, only see the blank page.

**Comment by SebasProgrammer2020** [comment]
check if your it is running or mounting the server in github. if you are accessing to the site, if the is not missing variables like me.

**Comment by madhuriaarth** [comment]
how to click material icons in cypress

**Comment by Sampath-vi** [comment]
@madhuriaarth You can add a custom data attribute`data-cy`.
https://docs.cypress.io/guides/references/best-practices#How-It-Works

**Comment by kailash360** [comment]
> I got the same issue, but it happens in github workflow. Everything works fine and perfect locally, however when it runs in github, only see the blank page.

I am having the same issue. I have made sure that all the variables are present. It passes perfectly in the local device, but fails in GitHub Actions. Any solutions or references?

**Comment by nurRiyad** [comment]
I am having the same issue. It passes perfectly on my local device but fails in GitHub Actions. 

> > I got the same issue, but it happens in github workflow. Everything works fine and perfect locally, however when it runs in github, only see the blank page.
> 
> I am having the same issue. I have made sure that all the variables are present. It passes perfectly in the local device, but fails in GitHub Actions. Any solutions or references?

**Comment by timdavhen** [comment]
Same here. Everything is working locally but it fails in github action. Sometimes it passes sometimes not.

**Comment by bhati416416** [comment]
do we have resolution for this issue?

**Comment by rolandm2017** [comment]
Having the issue myself

**Comment by javeria-qa** [comment]
![assertion error in cypress](https://user-images.githubusercontent.com/124682680/229048051-9bbf3e84-5660-4d53-abbf-2bde312589f7.png)

I am facing this issue kindly help me

**Comment by madhuriaarth** [comment]
cy.get('a[acsb-trigger-icon]').click() you can try like this it will work.

**Comment by dsgriffin** [comment]
Any solution for this? It works perfectly locally, and the second test runs fine on Github Actions, so it's clearly not done loading in time for the first test.

**Comment by sasielsa** [comment]
> Any solution for this? It works perfectly locally, and the second test runs fine on Github Actions, so it's clearly not done loading in time for the first test.

I got it working by adding alias to the intercept and wait to the response before the test continues to get the element:

` cy.intercept("GET", "https://#", { fixture: "" }).as("mockData");`

Then add do the action that triggers the request and add wait() for the response:

`cy.wait()`

**Comment by Dasith1** [comment]
![error](https://github.com/user-attachments/assets/5217ce44-df15-4f84-be85-4300a200c796)

I am facing issue. can anyone help me please?
