### ISSUE TITLE
Pass previous subject through `.screenshot()` in new screenshot usage

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1726]
The new implementation of `.screenshot()` from https://github.com/cypress-io/cypress/pull/1504 documents `.screenshot()` always yielding `null`. 

In the new use case of `cy.get('table').screenshot()`, I would like the `.screenshot()` to yield the previous DOM subject, the `table`.

This would *technically* be a breaking change - if someone were not following the recommendations within the docs about chaining, but honestly, I couldn't even come up with an example that would work -> then break after these updates.

**Comment by brian-mann** [comment]
`screenshotConfig` should just be `options` since they are the resolved/merged in values including what's been overridden or passed as options to `cy.screenshot`

**Comment by chrisbreiding** [comment]
The idea was to have it be a flat object with each options key, hence the `...`. I just didn't want to list every key in the screenshot config.
