### ISSUE TITLE
Cypress says Content-type is null but it is not

### ISSUE THREAD

**Issue by joshmccure** [cypress-io/cypress#1727]
### Current behavior: 

When trying to access my application I am getting the error:

Error:     CypressError: cy.visit() failed trying to load:

http://site.com.au/applications/

The content-type of the response we received from your web server was:

  > null

This was considered a failure because responses must have content-type: 'text/html'

However, you can likely use cy.request() instead of cy.visit().

cy.request() will automatically get and set cookies and enable you to parse responses.

<img width="1410" alt="screen shot 2018-05-17 at 3 38 58 pm" src="https://user-images.githubusercontent.com/19568272/40158672-18f7e3b6-59e9-11e8-920a-41db71cef973.png">

After making a cy.request after you can see that the page does not send null content-type. I've also checked the response and it's valid html that is being sent.

### Desired behavior:

Cypress renders the application and is able to test it. I have included a screenshot of the debugging console messages. Any help would be much appreciated.

Happy to make changes to the application under test, however I can't find anywhere where the content-type is null.

curling the headers of the URL gets this:
HTTP/1.1 200 OK
Date: Thu, 17 May 2018 06:21:57 GMT
Connection: keep-alive

### Steps to reproduce:

```js

```

### Versions  
 Latest

**Comment by githubuser19** [comment]
I'm having the same issue, I'm getting the message "The content-type of the response we received from your web server was: null" even though the page has the content-type properly setup on the head. This is happening with only one URL, the other ones I'm using are working fine. Any thoughts?

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

**Comment by jennifer-shehane** [comment]
Hey @githubuser19, do you happen to have `Content-Type=` defined anywhere else in the header because as per [this doc](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types#How_to_determine_the_MIME_type_sent_by_a_server):

> A meta tag that gives the MIME type such as `<meta http-equiv="Content-Type" content="text/html">` should be ignored if there's a `Content-Type` line in the header.

**Comment by githubuser19** [comment]
Hi Jennifer, thanks for your response.

I just checked and this is the only line that Content-Type is defined.

**Comment by flotwig** [comment]
The fix for #3101 does not change this behavior substantially. It will now say that the Content-Type is "undefined" instead of "null".

Do we want to change this behvaior? MDN says that using `http-equiv="Content-Type"` to define Content-Type is [obsolete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv):

![image](https://user-images.githubusercontent.com/1151760/51408515-f7b73200-1b2c-11e9-828d-9834dbe08801.png)

**Comment by achimkoellner** [comment]
In my case the charset-part in the header string was invalid saying:

```
Content-Type: text/html;charset=utf-8;charset=UTF-8;
```
Maybe this is helpful for somebody.

**Comment by flotwig** [comment]
Closing this issue for now as wontfix since Cypress is (correctly) expecting a Content-Type header to be sent along with the request, instead of attempting to parse the response body for a Content-Type which we don't currently support. 

@achimkoellner the confusing error message there has been fixed and will be released in 3.1.5 (today!)

**Comment by mohammedroni4** [comment]
I'm not sure why you closed it, even though many of us facing this issue right now, I think you guys should bring alternate solution of how to make it work. Having an undefined of the content type is pretty dumb to have I think you guys should work on that. It is working fine in the regular browser, I'm wondering why it wouldn't work inside of cypress chrome browse.

**Comment by brian-mann** [comment]
We recently made a change to `cy.visit()` that would allow us to fix this issue and more durably verify the content-type by parsing the actual response body.

@flotwig 	do you wanna take a crack at a PR for this? Since we buffer the response body regardless we can likely wait until the end of the request stream to verify the body is HTML-like. There also may be some libs out there to help do that.

**Comment by mohammedroni4** [comment]
Thanks for taking care of this and also let us know when the new build is released so we can download it, And Briann i’m also facing with other issue , regarding auth in my localhost im not sure if you will be able to help on this, this seems to be critical as well, but let see first if this fix the problem then i guess we are good but if itsn’t then ill tell you about authentication failure

**Comment by mohammedroni4** [comment]
Hey one of the job is failing on the PR. It seems like it's some how not merging. If you guys can fix the PR and get it released I think I think it would be very helpful...

<img width="808" alt="Screen Shot 2019-05-28 at 10 21 43 AM" src="https://user-images.githubusercontent.com/13221629/58498215-70a94480-8132-11e9-8370-9248d6e85824.png">

**Comment by mohammedroni4** [comment]
It seems like all the checks are passing but now its waiting for the Review...
<img width="912" alt="Screen Shot 2019-05-28 at 12 59 09 PM" src="https://user-images.githubusercontent.com/13221629/58508244-7a3da700-8148-11e9-98a4-8ba053a8a467.png">

**Comment by flotwig** [comment]
@mohammedroni4 We're working on getting it released, don't worry; it should come out with the next bugfix release.

**Comment by mohammedroni4** [comment]
Sounds good thank you so much for all the hard work :--)

**Comment by fferrari19** [comment]
Hi everyone!

I´m still struggling with this issue. Cypress is taking `content-type` as `undefined` but with a url from the same enterprise `cy.visit()` works perfectly. In addition, opening the url directly from browser shows that the `content-type` is text/html; charset=utf-8. My cypress version is 8.5.0 and running on chrome.

**Comment by herbertpimentel** [comment]
+1 now days. 

It does not make any sense, it says my content type is undefined but doing a curl -v on it it returns 


```sh
curl -v http://localhost:4200/
*   Trying 127.0.0.1:4200...
* Connected to localhost (127.0.0.1) port 4200 (#0)
> GET / HTTP/1.1
> Host: localhost:4200
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Accept-Ranges: bytes
< Content-Type: text/html; charset=UTF-8
< Content-Length: 2383
< ETag: W/"94f-VE3WkPzhSIGGlQMp+EQsCxbJR5g"
< Date: Tue, 12 Apr 2022 02:21:42 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```
