### ISSUE TITLE
c.wrap(interception) is throwing an error

### ISSUE THREAD

**Issue by AbrahamBrookes** [cypress-io/cypress#17279]
### Current behavior
I have an XHR call that goes out to a crud route and I am expecting it to return with a validation error. There's a good chance I'm not doinitrite here, as the error I am getting is a funny one. Also worth noting is that I am running cypress from within a docker containers mounted shell which means I don't have access to the test runner UI, only the command line runner.

I have a feeling that my patter for testing this validation error is erroneous so any advice there is appreciated as well!

Here is my test:
```js
	specify('filling out the form without filling in the name field will throw a validation error', () => {

		cy.intercept({
			method: 'PUT',
			url: '**/api/personalactivitytemplate/*' // I don't know how this pattern is supposed to work but this doesn't seem correct
		}).as('template.update') // the 'as' is arbitrary, I'm going with model.method

		cy.get('[data-testid="save-activity-template-btn"]').click()

		cy.wait('@template.update').then(interception => {
			cy.log(interception.response.body)
			cy.wrap(interception.response.body).should('include', 'errors')
		})

	})
```

The ajax call goes out of my application and returns as expected - the call to `cy.log(interception.response.body)` logs as expected:

```
{
  message: 'The given data was invalid.',
  errors: {
    id: [ 'The id field is required.' ],
    name: [ 'The name field is required.' ]
  }
}
```

But cypress waits for a while and then throws a silly sounding error:
![image](https://user-images.githubusercontent.com/8340776/125214520-f67caf80-e2fa-11eb-8344-d695872eb488.png)

### Desired behavior
The call to `cy.wrap()` should wrap my object without throwing an error

### Versions
```
# yarn cypress --version
yarn run v1.22.5
$ /var/www/node_modules/.bin/cypress --version
Cypress package version: 6.6.0
Cypress binary version: 6.6.0
Electron version: 11.2.3
Bundled Node version: 12.18.3
Done in 0.26s.
```

**Comment by jennifer-shehane** [comment]
😅 Yah, this is an error thrown by our assertion engine,  Mocha, so this is not Cypress exactly. 

I believe this horribly written error message is meant to tell you that this assertion statement is not the right one for this object. 

So you should write `.should('have.property', 'errors')` instead which will pass. 

```js
it('test', () => {
  expect({
    message: 'The given data was invalid.',
    errors: {
      id: ['The id field is required.'],
      name: ['The name field is required.']
    }
  }).to.include('errors') // really weird error
})

it('test', () => {
  expect({
    message: 'The given data was invalid.',
    errors: {
      id: ['The id field is required.'],
      name: ['The name field is required.']
    }
  }).to.have.property('errors') // passes 👍 
})
```
