### ISSUE TITLE
Component testing "Open in IDE" link broken

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#17272]
### Current behavior

When trying to open my test on the right line, using the "Open in IDE" link, nothing happens.

This is what I see:

https://user-images.githubusercontent.com/5592465/125167656-488ccc00-e167-11eb-917f-eca13426d666.mov

NOTE: It does not depend on Webpack or Vite, both link fail the same way.

### Desired behavior

I would like to be taken to my test on the first line

### Test code to reproduce
- checkout https://github.com/elevatebart/calc-vite
- open the spec named `Container.tsx`
- hover on the test
- Click on the `Open in IDE` link
- nothing happens

### Versions

Cypress 7.7.0

**Comment by elevatebart** [comment]
I managed to track this issue down to this method. The `new Error().stack` is returning a lot more intermediary information in CT than in E2E.

https://github.com/cypress-io/cypress/blob/cf689dd6093b92cd950e9ec77edd84977f90260f/packages/driver/src/cypress/mocha.js#L104-L125

Even if we did get the same kind of information, the url of the final file ishighly depedent on the dev-server. It suggests we configure this details resolving in the devServer homepage itself as an event. 

It could be done in the Cypress object before we run `onSpecWindow()`

here for webpack https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/aut-runner.ts#L9

and here for vite https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/client/initCypressTests.js#L22

**Comment by JessicaSachs** [comment]
Stale, fixed in Cypress 10
