### ISSUE TITLE
Cypress hooks doesn't work when running dynamic tests

### ISSUE THREAD

**Issue by rupakgithub** [cypress-io/cypress#17271]
### Current behavior
No cypress hooks are executing if only dynamic tests are present in spec file. I am fetching data from json file and dynamically creating tests. Tests are running as expected. But, if cypress hooks are present then the hook is not executing. In the below code sample, Before & BeforeEach blocks are not executing at all if only dynamic tests are present

### Desired behavior
Cypress hooks should execute irrespective of tests being static or dynamic.

### Test code to reproduce
```js
const connectedDevices = require("../fixtures/connectedDeviceList.json");
let finalToken;

describe('Download Monitor', function () {

    before(function(){
        cy.fixture('saveSessionData.json').then((sessionData) => {
            cy.log(sessionData);
        });
    });

    beforeEach(function(){
       cy.log("Test before Each")
    });

    connectedDevices.forEach((device) => {
        const { Id, name, version  } = device;
        it('My dynamic tests', function () {
            cy.getActionUpdate(Id, this.finalToken, name, version);
        });
    });
});
```

### Versions

7.7.0

**Comment by jennifer-shehane** [comment]
I am seeing all of the hooks code execute when  running a simplified version of the test you provided. Please provide a reproducible example to see tthat the code is not executing withint the hooks. 

```js
describe('Tests', function () {
  before(function () {
    console.log('Test before')
    cy.log('Test before')
  });
  beforeEach(function () {
    console.log('Test before Each')
    cy.log('Test before Each')
  });

  [1, 2, 3].forEach((num) => {
    it(`test ${num}`, function () {

      cy.log(`Test ${num}`);
    });
  });
});
```

<img width="472" alt="Screen Shot 2021-07-12 at 9 09 05 AM" src="https://user-images.githubusercontent.com/1271364/125301876-07c0be80-e2f1-11eb-813f-35849db7456c.png">

**Comment by rupakgithub** [comment]
Thanks for replying. I am not able to reproduce this issue again. All hooks are working as expected.
