### ISSUE TITLE
Not possible to set specific timeout on custom commands

### ISSUE THREAD

**Issue by amitzur** [cypress-io/cypress#1728]
This issue is related to Cypress API for custom commands. Hopefully it's just undocumented or I didn't find it in the docs.

I define a custom command, which might be a long operation. I wish to control the default timeout for my custom command. My command looks like this:
```js
Cypress.Commands.add('myCommand', () => {
  return cy.document().then(doc => {
   <long operation>
  });
});
```
I'd like the `<long operation>` to have its own timeout. Is that possible? Or achievable in some way?

**Comment by brian-mann** [comment]
You put the `timeout` on the `.then()` because that's what's timing out. I'm assuming `<this operation>` is a promise too.

**Comment by amitzur** [comment]
This solves my issue, I now do this:
```
return cy.document().then({ timeout: 10000 }, doc => { ... });
```
Thanks!

**Comment by dfang** [comment]
what if custom command is not cy apis ?

i tried this , but i still got `Cypress command timeout of 4000ms exceeded.` on command log in test runner.

```
Cypress.Commands.add('login', { timeout: 10000 }, (overrides = {}) => {
  Cypress.log({
    name: 'loginViaAmplifyAuth',
  });

  return Auth.signIn(dummy.email, dummy.password)
});
```

**Comment by vince1995** [comment]
@dfang use the same logic @amitzur replied, even if you don't need the document.

**Comment by dfang** [comment]
@vince1995 could you be more specific ？

**Comment by vince1995** [comment]
```
Cypress.Commands.add("login", () => {
    return cy.document().then({ timeout: 10000 }, doc => {
        
        // And here your code.

    });
});
```

**Comment by dfang** [comment]
@vince1995 Auth.signIn is from amplify,  it's an api,  why should i wrap it in` cy.document` promise ?

**Comment by dfang** [comment]
@vince1995 

i'm using this 

```
cy.login().then({ timeout: 10000 }, ()=> {
        cy.visit('/profile').then(() => {
          cy
            .get('amplify-authenticator')
            .should('have.length', 0)
        })
})
```

**Comment by vince1995** [comment]
> @vince1995 Auth.signIn is from amplify, it's an api, why should i wrap it in` cy.document` promise ?

It's just a workaround so you can sepcify the default timeout time in the command and not in the test.

**Comment by maxkoretskyi** [comment]
This works

```
Cypress.Commands.add('custom', () => {
  const promise = new Promise((resolve) => {
    setTimeout(resolve, 5000);
  });

  return cy.wrap(promise, {timeout: 10000});
});
```
