### ISSUE TITLE
cy.clock() setting date to 19th Jan 1970 instead of date provided in epoch format.

### ISSUE THREAD

**Issue by Ppkd2021** [cypress-io/cypress#17281]
### Current behavior
If we are setting cy.clock(1622633011707,[`Date`]), THen we are overriding date function which we need to do in order to freeze application date to past date.  Instead of the date provided (3rd June 2021) the application date is getting set to 19th Jan 1970. Due to which graph data and other time range scenarios we are not able to develop.
If override using other functions such as setTimeout,ClearInterval then it does not set the system date which does not fulfill our purpose.
### Desired behavior
The date provided in cy.clock with date as an overriding function then it should set application date to that respective date.

### Versions

Cypress 7.6.0

FYI, We are using dayJs library throughout the application for handling date and time.

**Comment by papermana** [comment]
@Ppkd2021 Sometimes the Unix time is measured in seconds, sometimes in milliseconds. I think `cy.clock` is supposed to be using milliseconds, and 1622633011707 is a value in milliseconds as well. But note that dividing it by 1000 gives you a Unix time (in milliseconds) for Jan 19. Just an observation. I don't have a solution to this issue.
