### ISSUE TITLE
Add cy.intercept option to disable auto-parsing of JSON bodies

### ISSUE THREAD

**Issue by simfeld** [cypress-io/cypress#17280]
### What would you like?
The `cy.intercept` command automatically parses bodies of `application/json` content type before passing them to the intercept handler, as a convenience for the user: https://docs.cypress.io/api/commands/intercept#Response-object-properties. I'd like to propose an option to disable this behaviour for a particular intercept, i.e. the handler would just be passed the original JSON string.

### Why is this needed?
`JSON.stringify(JSON.parse(x)) !== x` in all cases. It certainly is equivalent from the JSON spec viewpoint, but there could be for example newlines in the original string that are not present anymore after parsing and stringifying, even if the intercept handler doesn't manipulate the response body at all. In one of our projects we have optimized code which relies on some custom assumptions on the JSON bodies (which might not be a good idea to begin with, but I don't want to get into the details here) passed to the browser which fails when an intercept handler touches the response, even if no modifications are made. This option allows the user to control even more what happens (or doesn't happen in this particular case) to the request or response that's being intercepted, which is a good thing from my viewpoint.

### Note
I'd be willing to contribute this myself if the proposal is accepted.

**Comment by jennifer-shehane** [comment]
Yah, we originally shipped cy.intercept() without automatically parsing the JSON and that broke a lot of people's expectations on how this should work, so we began automatic parsing. So I would call this the exception to the rule - wanting to not JSON parse by default.  But sounds fair.

Could you provide an example (repo)  of a test case that fails unexpectedly with the way intercept is currently handled? That would  be really helpful in demonstrating the issue and use case. Thanks!
