### ISSUE TITLE
Add Paths and .zip to Download URLs

### ISSUE THREAD

**Issue by CypressJosh** [cypress-io/cypress#17291]
### What would you like?

1. Add a path option to our downloads URL that would essentially work the same as the query params, but as paths, ex:
  a. https://download.cypress.io/desktop?platform=OS&arch=ARCH (current)
  b. https://download.cypress.io/desktop/linux-86/binary/ (net new)
2. Adding .zip to https://download.cypress.io/desktop and supporting both, ex:
  a.  https://download.cypress.io/desktop (current)
  b. https://download.cypress.io/desktop.zip (net new)

### Why is this needed?

JFrog's Artifactory appears to have a couple limitations preventing users from being able to download Cypress while using Artifactory.

**Comment by jennifer-shehane** [comment]
Are these related? https://github.com/cypress-io/cypress/issues/15697, https://github.com/cypress-io/cypress/issues/17238

Whats the error they see when downloading?

**Comment by flotwig** [comment]
Someone posted some instructions for Artifactory users: https://github.com/cypress-io/cypress/issues/15697#issuecomment-839852863

**Comment by amirrustam** [comment]
@flotwig https://github.com/cypress-io/cypress/issues/15697#issuecomment-839852863 won't be a sufficient enough solution since many Artificatory users have to store artifacts locally after they are scanned by Artifactory's XRay (vulnerability scanner) system.

**Comment by jennifer-shehane** [comment]
Someone mentioned wanting to be able to also include the version in the download url. `cypress_8.0.0.zip`, etc. Mentioning it here since it seems partially related. https://github.com/cypress-io/cypress/issues/17417

**Comment by flotwig** [comment]
The following routes have been deployed to download.cypress.io:

* /desktop.zip
* /desktop/:platform-:arch/cypress.zip
* /desktop/:version/:platform-:arch/cypress.zip

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. It should be released soon by our API team.
