### ISSUE TITLE
Cypress can get into a weird state where it doesn't reset correctly in between test runs.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#173]
If theres a failure after it listens to `before:log`, Cypress can get into a weird state. The tests will continue to work if we reset the state (with a refresh).

**Console Log Error**
![screen shot 2016-06-16 at 11 38 56 am](https://cloud.githubusercontent.com/assets/1271364/16122981/48483b3e-33b7-11e6-9081-9ed636a6503d.png)

**Stack Trace**
![screen shot 2016-06-16 at 11 39 12 am](https://cloud.githubusercontent.com/assets/1271364/16122986/50f9450c-33b7-11e6-909c-6dc935f5a502.png)

**Code with broken logic in `ensure.coffee`**
<img width="635" alt="screen shot 2016-06-16 at 11 39 26 am" src="https://cloud.githubusercontent.com/assets/1271364/16123005/5c46bd36-33b7-11e6-8655-0a577ac4da07.png">

**Comment by brian-mann** [comment]
Fixed in [`0.16.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0163-06172016).
