### ISSUE TITLE
Private projects on the Dashboard should support README badges

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#17301]
### What would you like?

To add a Dashboard README badge to a private projects

<img width="361" alt="Screen Shot 2021-07-13 at 08 48 21" src="https://user-images.githubusercontent.com/2212006/125454206-7ec7d25b-54d4-461c-8414-6d0da63fe1ca.png">

### Why is this needed?

Because in a large organization users should know where to find the test results

**Comment by ndua-globality** [comment]
Hi there! Was wondering if this was actively being looked at? Thx!
