### ISSUE TITLE
cy.click() is not clicking the element in the dropdown, also i am not getting any errors

### ISSUE THREAD

**Issue by Jenicia** [cypress-io/cypress#17307]
### Current behavior

cy.click() is not clicking an element in the dropdown, and also not throwing any error

```js
  cy.get('#coinType')
      .click({ force: true })
      .then(() => {
        cy.contains('N/A').click({ force: true });
      });
```

### Desired behavior

Need to select any element from the dropdown

### Test code to reproduce

![image](https://user-images.githubusercontent.com/87384663/125490799-3e4a5888-8d43-4479-8ed6-e9cbcade70ba.png)
![image](https://user-images.githubusercontent.com/87384663/125492204-749d6bad-ffc3-426d-ba49-79e1d4fbcda0.png)

### Cypress Version

Cypress package version: 6.3.0

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. 

Using `force: true` will turn off our default checking for reasons why the element may be unselectable.  What error is thrown when you remove `force: true`? That likely indicates why it  may be unclickable.

**Comment by Jenicia** [comment]
> Thanks much for the reply, I have updated my cypress version to 7.7.0
> 
> I executed the same piece of code below by removing the force: true as you have suggested:
> 
> ```
> cy.get('#coinType')
>   .should('be.visible')
>   .click()
>   .then(() => {
>     cy.contains('N/A').click();
>   });
> ```
> 
> but getting **the _This element <input#coinType.ant-select-selection-search-input> is not visible because it has CSS property: opacity: 0_**
> ![image](https://user-images.githubusercontent.com/87384663/125783545-570d3e29-aaf3-4efb-a272-b706ba6f82a2.png)
> 
> kindly help!

**Comment by JohnnyFun** [comment]
Can you remove the opacity style or select a more specific element to click?

**Comment by taliaholtz** [comment]
We might have the same issue. After I click to open the dropdown, it doesn't stay open but sort of flickers open & closed which is causing instability when clicking on an element in the dropdown
