### ISSUE TITLE
Using a config-file that does not exist does NOT fail. Instead creates empty config file.

### ISSUE THREAD

**Issue by dotwork** [cypress-io/cypress#17313]
### Current behavior

If you specify a config file that does not exist, ie:

`yarn cypress open --config-file=cypress/configs/non-existent-config-file.json`

it will load the UI like normal, with all tests, and create a config file with an empty json object. I keep having to delete these.

### Desired behavior

The command should fail and raise an error stating that the specified config file does not exist.

### Test code to reproduce

`yarn cypress open --config-file=cypress/configs/non-existent-config-file.json`

### Cypress Version

6.5.0

### Other

I am running on Linux Mint 20.1

**Comment by jennifer-shehane** [comment]
This is the intended behavior when a non-existent `--config-file` is passed. 

I encountered this recently though and also thought this was an unusual way to handle this. I can't completely remember the reasoning behind why we implemented it this way.

**Comment by dotwork** [comment]
I see. I hope that behavior is changed. It's quite unexpected/unintuitive. Sometimes I misremember a config file name, ie `workflows.json` instead of `workflow-tests.json`...easy mistake to make, and then I have to realize I used a bad config, cancel the command and delete the new file. It would be nice if it just failed and didn't require an additional step to clean up the mistake.
