### ISSUE TITLE
cy.clock() even block setTimeout(()=>..., 0) running

### ISSUE THREAD

**Issue by cpdyj** [cypress-io/cypress#17320]
### Current behavior

If I use cy.clock() stub the clock, `setTimeout(()=>console.log(), 0)` doesn't running.

### Desired behavior

`setTimeout(()=>console.log(), 0)` shouldn't be blocked because the timeout is **zero**

### Test code to reproduce

I don't think it's needed.

### Cypress Version

7.6.0

### Other

Cypress package version: 7.6.0
Cypress binary version: 7.6.0   
Electron version: 12.0.0-beta.14
Bundled Node version: 
14.15.1

**Comment by jennifer-shehane** [comment]
Check the `clock` docs, `cy.clock()` overrides native functions like `setTimeout`. https://on.cypress.io/clock

You can specify the exact functions you want `cy.clock()` to override and ignore `setTimeout` if wanted like described here: https://on.cypress.io/clock#Function-names

<img width="690" alt="Screen Shot 2021-07-14 at 9 01 00 AM" src="https://user-images.githubusercontent.com/1271364/125635352-a5b5ddb5-02a9-4b36-a1fb-a55c5b129a13.png">
