### ISSUE TITLE
cannot cy.type("{enter}") (or any other key combinations) into inputs with validations (like time, date, etc)

### ISSUE THREAD

**Issue by ahfarmer** [cypress-io/cypress#17337]
### Current behavior

<img width="301" alt="Screen Shot 2021-07-14 at 11 44 05 AM" src="https://user-images.githubusercontent.com/597825/125675811-d1dc191c-bc3f-4775-a85b-5702d5f972f0.png">

```
Typing into a time input with cy.type() requires a valid time with the format HH:mm, HH:mm:ss or HH:mm:ss.SSS, where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999. You passed: EnterLearn more
```

For code `cy.type("{enter}")`

### Desired behavior

Ability to press enter in a time input field

### Test code to reproduce

`cy.type("{enter}")` on an `<input type="time" />`

### Cypress Version

7.6.0

**Comment by jennifer-shehane** [comment]
We do a naive RegExp against the string passed into `.type()` here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/keyboard.ts#L401:L401 Likely this is an issue with other input types as well. 

I'm not sure what we would do to get around this exactly though.

The workaround for this would be to manually trigger the events on the input using [`.trigger()`](https://on.cypress.io/trigger) using the corresponding event and charCodes, etc.

**Comment by ahfarmer** [comment]
Is it necessary to have time-specific logic here? I initially tried "010203" instead of "01:02:03" since a real user doesn't actually type the colons.

**Comment by indignant** [comment]
I agree with @ahfarmer on this. I'm working on a regression test where typing "09092014" in a date input breaks Chrome while working in Firefox, but I'm running into that validation error.
