### ISSUE TITLE
Allow customization of slack message that notifies about test failure.

### ISSUE THREAD

**Issue by pawarvaibhav** [cypress-io/cypress#17339]
### What would you like?

Slack notifications sent to a given slack channel (post integration with Cypress Dashboard) include a few things 
- how many tests failed 
- merge commit details 
- a short transcript of each failure. 

It would be great if I could add 
- environment: qa
- Test tags: regression or e2e

this helps add more context to the current execution.

### Why is this needed?

This allows anyone who looks at the slack message to have a better idea of which configuration the tests ran against. That way, for example, if a given notification includes
- environment: qa
- tags: regression
just the QA folks might be interested in looking at overall failures and determine which issues are app code issues and which are test code ones.

But if the given notification includes
- environment: dev
- tags: e2e
This may need immediate attention since the new changes broke end to end workflow.

**Comment by cy-veronica** [comment]
We are reviewing your request for the slack integration, thank you!
