### ISSUE TITLE
The specs view on the dashboard is missing empty specs

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#17349]
### Current behavior

When recording specs to the Dashboard some specs might be empty. In that case the numbers reported in the Machines view do not add up. For example, the top and the bottom machines report 6 specs, but counting the green bars - there are only 5 specs. This is because these two machines also executed the empty specs which are not shown

<img width="1192" alt="Screen Shot 2021-07-15 at 09 32 51" src="https://user-images.githubusercontent.com/2212006/125797080-fee0de19-f59a-4c2d-b222-cf42dd7c8975.png">

Second part: the empty specs are counted as "errored". But they are NOT errors. They are just empty, so the label is wrong.

### Desired behavior

- Show in yellow bars / squares for empty specs so the chart makes sense
- Call empty specs "empty" rather than "errored"

### Test code to reproduce

set up a project with recording with an empty spec

### Cypress Version

7.7.0

**Comment by finnstech** [comment]
Thanks for this. This is a UX issue and I have filed it for the product team to consider.
