### ISSUE TITLE
How to mock $route when mounting a component

### ISSUE THREAD

**Issue by toaditoad** [cypress-io/cypress#17345]
### Current behavior

When executing a component test with Cypress 6.9.1, the `$route` object cannot be mocked:

```javascript
it('Counter should show initial value passed as route parameter', () => {
    const initialCounterValue = 17;

    mount(Counter, {
        mocks: {
            $route: {
                params: {
                    initialCounter: initialCounterValue,
                },
            },
        },
    });

    cy.contains(initialCounterValue).should('be.visible');
});
```

![image](https://user-images.githubusercontent.com/15110724/125767049-4cb3ae86-0495-4e92-8651-1e2f9ddcc210.png)

### Desired behavior

Since the documentation states that options of `mount` from `@vue/test-utils` are available, I would expect to mock the `$route` accordingly.

### Test code to reproduce

See https://github.com/toaditoad/cypress-component-mount-mwe for a minimal working example to reproduce the error messages in the console.

### Cypress Version

6.9.1

### Other

Vue issues an error that `#app` cannot be found.

```shell
$ npx cypress version
Cypress package version: 6.9.1
Cypress binary version: 6.9.1
Electron version: 11.3.0
Bundled Node version: 12.18.3
```

Cypress cannot be updated to 7.x due to some other project restrictions.

**Comment by MRZ07** [comment]
Hi @toaditoad,

I have forked your project and in a separate branch I have made a fix using shallowMount: https://github.com/MRZ07/cypress-component-mount-mwe/tree/fix-route-mocking

**Comment by MRZ07** [comment]
Hi @toaditoad,

I forked your project and created a fix in a separate branch using shallowMount: [MRZ07/cypress-component-mount-mwe@fix-route-mocking](https://github.com/MRZ07/cypress-component-mount-mwe/tree/fix-route-mocking?rgh-link-date=2022-02-10T08%3A34%3A05Z)

**Comment by MRZ07** [comment]
In this case it would be possible to run a local vue router in a local vue instance and push a location on the local vue router.

The following helper class can be used for this purpose to create a local vue router:

```
import VueRouter from 'vue-router';
import routes from '../../../src/Routes';

export default function createLocalRouter(): VueRouter {
    return new VueRouter({
        mode: 'history',
        base: process.env.BASE_URL,
        routes,
    });
}

```


The test can look like this:
```
 		const localVue = createLocalVue();
        localVue.use(VueRouter);
        const router = createLocalRouter();

        const param = '123'

        const $route: Location = {
            path: '/main-ui/page/'+param,
            params: {
                param,
            },
        };

        router.push($route);

        mount(DemoComponent, {
            localVue,
            router,
        });
```
