### ISSUE TITLE
test recording

### ISSUE THREAD

**Issue by nameetjambla** [cypress-io/cypress#17342]
### Current behavior

while recording the cypress test cases the video does not work properly. I have tried all the time speed but doesn't work well.
![image](https://user-images.githubusercontent.com/79189939/125736698-0b188e82-317e-4008-a19d-b93b28c5b10b.png)

### Desired behavior

In just the normal app which gets the user Input

### Test code to reproduce

 All the test case is passing, able to record the video as well but not able to watch the recorded test video properly due to speed issues.

### Cypress Version

7.0.0

**Comment by jennifer-shehane** [comment]
Hey @nameetjambla If you are running Cypress in a headless browser, the default screen size was increased to 1920x1080 in 7.0 which could affect the video recording. Try reducing the screen size to the default size prior to 7.0 (1280x720) to see if the performance is related to the increase in screen size. [Instructions here.](https://on.cypress.io/browser-launch-api#Set-screen-size-when-running-headless)

We generally see this issue with videos when the machine the tests are run on have lower CPU/memory than is required to run Cypress while recording video. We suggest increasing the CPU/memory to see if there's improvement int he video.  We have some things we're working on  currently to address this  more fully.

**Comment by paschalidi** [comment]
We use GH actions. Gh doesnt give you the option to define your VM specs https://github.com/actions/virtual-environments/issues/1043
