### ISSUE TITLE
cy.wait causes cypress browser network requests malfunctioning

### ISSUE THREAD

**Issue by Terence625** [cypress-io/cypress#17340]
### Current behavior

In this project, when I click a button, it'll refresh the page and "GET" three APIs in random order, I use cy.intercept and cy.wait for all these 3 APIs so that I can continue the following actions. It looks like cy.wait(['@request1', '@request2', '@request3']), and I'll repeat this behaviours multiple times as a workflow test. The first few times still ok, but after 2 or 3 times, the browser will lose one request and cause cy.wait to timeout. I fix this issue for my project by adding another cy.wait(1000) after the cy.wait(['@request1', '@request2', '@request3']). Just wanna point out if this is a bug for cypress.

### Test code to reproduce

This is a confidential project so cannot post any codes here

### Cypress Version

7.3.0

**Comment by nboisteault** [comment]
I had some kind of similar weird behavior. https://docs.cypress.io/api/commands/intercept#Comparison-to-cy-route resolved my problem.
