### ISSUE TITLE
Cypress detects overwrite command as promise and throws error when using cy commands inside overwrite command

### ISSUE THREAD

**Issue by darkpunito** [cypress-io/cypress#17350]
### Current behavior

Cypress throws an error and fails executing test if inside overwrited commands there is called other cypress command

![image](https://user-images.githubusercontent.com/25249637/125804225-11965057-3627-433c-945b-d391d0d36ef6.png)

### Desired behavior

Cypress allows to execute cy commands inside overwrited commands and return additional object in then callback

it("Visit example page", function() {    
    cy.visit("https://example.cypress.io/commands/actions").then(overWritedVisitObj => {
    console.log(overWritedVisitObj.window) //outputs original window from cy.visit()
     console.log(overWritedVisitObj.waitedRequest) //outputs added response from waited xhr request in overwritten cy.visit()
    });    
  });

### Test code to reproduce

Reproduce:
Overwrite some command e.g. 'visit' with any cypress commands inside

Cypress.Commands.overwrite('visit', (originalFn, url, options) => {
  cy.log('Something')  
  return originalFn(url, options)  
})

Run test with calling overwriting method:
it("Visit example page", function() {    
    cy.visit("https://example.cypress.io/commands/actions");    
  });

Noticed this during trying to output additional information to returned object
Cypress.Commands.overwrite('visit', (originalFn, url, options) => {
  cy.intercept('GET', 'matching url after visiting 'url').as('myWaitedRequest')
  return originalFn(url, options).then(window => {
  return cy.wait('@myWaitedRequest').then(xhr => {
  return cy.wrap({window: window, waitedRequest: xhr})
  })
  })  
})
Will above scenario be viable in Cypress ? To add additional object in overwrite to yield of original command 

### Cypress Version

7.7.0

**Comment by amiroous** [comment]
Same issue for me when overwriting visit command and wanted to add a callback to its onLoad
