### ISSUE TITLE
click() on <label> element triggers handler on chromium for Mac but not Linux

### ISSUE THREAD

**Issue by mxs** [cypress-io/cypress#1735]
### Current behavior: 
![cypress](https://user-images.githubusercontent.com/360265/40213656-eb9c2b50-5a99-11e8-8eec-036398f04ecd.png)

click() the <label> does not check the containing <input> of the label.

### Desired behavior:
![screenshot](https://user-images.githubusercontent.com/360265/40213749-71e0fa7e-5a9a-11e8-8b91-4da242952107.png)
click() the <label> should check the checkbox input 

### Steps to reproduce:

```js

```

### Versions  
Cypress 2.1.0, Ubuntu 16.04 LTS, Electron Chromium

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
