### ISSUE TITLE
Test Runner not showing in Chrome

### ISSUE THREAD

**Issue by Badisi** [cypress-io/cypress#17367]
**Operating system**: macOS 10.15.6
**Chrome**: 91.0.4472.114 (Official Build) (x86_64)
**Node**: 14.17.0
**Cypress**: 8.0.0
**Angular**: 12.1.2

I'm trying to use Cypress with a simple Angular project.

Everything works fine when opening the tests in Electron:
<img width="1518" alt="Screenshot 2021-07-16 at 17 17 49" src="https://user-images.githubusercontent.com/674862/125970541-e250ac07-d6e1-4249-8f47-e3e87a6a2763.png">
But with Chrome the Test Runner is not showing at all :
<img width="1450" alt="Screenshot 2021-07-16 at 17 03 13" src="https://user-images.githubusercontent.com/674862/125969781-4418473f-4488-45fa-8b1a-502a80535d9f.png">
I tried anything I could think of:
- verbose logs with `DEBUG=cypress:*` but nothing much relevant in there (at least to me)
- verbose logs in the browser with `localStorage.debug = 'cypress*'` but not working as the test runner is not even loaded
- chrome extension, but it's perfectly loaded and has full access (as shown in the screenshot)

Any help would be very appreciated as I have now no more idea where to look at.
Especially how the Test Runner is supposed to be loaded ?..

Thanks

**Comment by Badisi** [comment]
@jennifer-shehane Any advices please ?

I'm willing to investigate it myself but I have no clue on how it is supposed to work.

**Comment by dwhieb** [comment]
I'm having this same issue and not sure how to proceed.

**Comment by Badisi** [comment]
@dwhieb, unfortunately I never found a solution to this issue..

Not to criticize but I personally gave up on `cypress` due to the lack of support and the growing number of issues.
I went with [WebdriverIO](https://webdriver.io/) which meets my requirements even better and which do have a really active and responsive community.

**Comment by dwhieb** [comment]
Thanks for the update @Badisi. I also find the large number of open issues concerning, although the project is continuing to close them at a steady pace. I've been eyeing [Playwright](https://playwright.dev/) myself.

**Comment by tchu10** [comment]
I'm seeing this issue in Cypress 10.3.1 in both Chrome and Edge browsers in Windows 10.  I don't see this issue in Safari.

**Comment by marktnoonan** [comment]
> I don't see this issue in Safari.

@tchu10, I am a bit puzzled by this since Safari is not supported.

This issue itself looks like it was referring to 8.0.0. In 10.0 there were significant changes in the code around the runner that should have prevented the ability to get the reporter hidden as shown in these screenshots.

Could you describe what exactly you are seeing and share some screenshots?

**Comment by tchu10** [comment]
Sorry, not Safari.  I meant to say MacOS Chrome.  I'm seeing the same thing the OP described last year.  I can add that this only happens for me in windows.  Selecting a browser for E2E testing (Chrome or Edge)  will show the aut without the test runner panel.  Running in electron works in both windows and MacOS.  I will try to get a screenshot, but this may have an NDA repercussion.

**Comment by marktnoonan** [comment]
Thanks @tchu10. If you can't get a screenshot that's fine, though I'd appreciate knowing a few things:

- when you open the browser console, are there errors logged there?
- could you grab [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) and share those? I'd be interested to see what is logged around the time you open a spec. It will be a lot of output and you might want to redact some stuff with find/replace

We do test in windows regularly and haven't seen this ourselves, so any detailed information about the OS version etc would be useful too.

**Comment by tchu10** [comment]
Hi @marktnoonan ,

- There are no errors logged into the browser console
- Tests do not execute.  It does seem to open baseUrl
- I've attached an output from **set DEBUG=cypress:***

**Comment by tchu10** [comment]
[Cypress debug log.txt](https://github.com/cypress-io/cypress/files/9213900/Cypress.debug.log.txt)

**Comment by tchu10** [comment]
It's been about a week, is there an update?

**Comment by tchu10** [comment]
This is still not working in 10.4.0

**Comment by marktnoonan** [comment]
Hi @tchu10 I haven't had a chance to come back to this in detail yet. I did look at the logs and something that sticks out is `experimentalSessionAndOrigin` is set to `true`, which means though this presents similarly to the above issue, it might not be the same underlying cause. The example in the OP here doesn't seem to involve auth and predates the current experimental session API.

What I was expecting to find was something about the UI not rendering correctly, but it's clear that what's going on has a little bit more to do with the application breaking out of the Cypress iframe and doing something like setting the location of `window.top`. This wouldn't explain why this issue is only on Windows.

Within the log I do see this error `Could not open pak file for writing: The process cannot access the file because it is being used by another process.` This error has been mentioned before: https://github.com/cypress-io/cypress/issues/14175 and looks like it might be related to Sophos, which might explain the difference between Windows and Mac for you, in some way that causes the login page to bust out of the iframe, possibly by interfering with things Cypress needs to do when `chromeWebSecurity` is set to `false`.

```
  cypress:server:browsers:cri-client connecting { target: 'ws://localhost:59603/devtools/browser/8757f40c-f5ee-427a-aa99-5938ba2ef2b0' } +0ms
  cypress:server:browsers:browser-cri-client Attaching to target url about:blank +0ms
  cypress:server:browsers:cri-client connecting { target: 'E1292F518C19AD1956ECAB48B3B6F1B2' } +190ms
  cypress:launcher:browsers chrome stderr: [11384:3328:0728/155447.717:ERROR:scoped_file_writer.cc(16)] Could not open pak file for writing: The process cannot access the file because it is being used by another process. (0x20) +946ms
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Network.requestWillBeSent' } +37ms
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Network.responseReceived' } +16ms
  cypress:server:browsers:chrome options.onScreencastFrame is false +3s
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Page.downloadWillBegin' } +788ms
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Page.downloadProgress' } +2ms
  cypress:server:browsers:chrome received CRI client +72ms
  cypress:server:browsers:chrome navigating to page https://fit.totalsolutions.oneadp.com/__/ +0ms
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Fetch.requestPaused' } +767ms
  cypress:server:browsers:chrome listen for frame tree changes +830ms
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Page.frameAttached' } +71ms
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Page.frameDetached' } +2ms
  cypress:server:browsers browser opened +4s
```

**Comment by tchu10** [comment]
Thank you for taking a look @marktnoonan .  I tried running with `chromeWebSecurity` set to `true` and I get the same results.  I'm checking, but I'm pretty sure we don't use Sophos here.  I think it may be possible that there could be a security setting causing this.  I just don't know which setting it may be.

**Comment by marktnoonan** [comment]
> I tried running with chromeWebSecurity set to true and I get the same results.

That tracks, I feel like what you are seeing is what we might expect if setting `chromeWebSecurity` to `false` was not working correctly.

It might be worth experimenting by setting up a page that renders your application in an iFrame and seeing what it does on Windows vs Mac, without Cypress at all.

**Comment by marktnoonan** [comment]
@tchu10 please let me know if you got anywhere with reviewing your security settings, or the general tolerance this page has for being rendered in an iframe on your Windows machine in general.

If this issue remains inactive we'll likely have to close it for the time being until there's a reproducible example that can be shared.

Oh and actually, re-reading your comments:

>  I tried running with chromeWebSecurity set to true and I get the same results.

Did you try setting it to false? That was my suggestion. The logs you sent already showed it being set to true, so if you haven't tried `false` yet, please give it a shot and let me know.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
