### ISSUE TITLE
Multiple cy.intercepts need to be declared in reverse order

### ISSUE THREAD

**Issue by TheDutchCoder** [cypress-io/cypress#17379]
### Current behavior

```ts
it.only('Should login successfully', () => {
    cy.intercept({ method: 'POST', url: 'https://cognito-idp.us-east-1.amazonaws.com', times: 1 }, { fixture: 'cognito/email-valid.json' }).as('call1')
    cy.intercept({ method: 'POST', url: 'https://cognito-idp.us-east-1.amazonaws.com', times: 1 }, { fixture: 'cognito/challenge-valid.json' }).as('call2')

    cy.get('input#email').type(LOGIN_EMAIL_VALID)
    cy.get('[data-login-email-submit]').click()
    
    cy.wait('@call1')
    
    cy.get('input#verification').type(LOGIN_CHALLENGE_VALID)
    cy.get('[data-login-code-submit]').click()

    cy.wait('@call2')

    cy.location('pathname', { timeout: 10000 }).should('include', 'profile')
})
```

This test fails because Cypress (for some reason) actually intercepts the calls in the reverse order (it will intercept the last declared one first and then move "back").

This seems like a strange way of doing it, especially since I'm using aliases.

### Desired behavior

Multiple cy.intercepts to be handled in order of declaration.

### Test code to reproduce

See Current behavior

### Cypress Version

7.7.0

**Comment by fernyb** [comment]
You can also do something like this:

```

const fixtures = ["cognito/email-valid.json", "cognito/challenge-valid.json"];
cy.intercept({ method: "POST", url: "https://cognito-idp.us-east-1.amazonaws.com" }, (req) => {
  const file = fixtures.shift();
  if (file.indexof("email-valid") > 0) req.alias = "call1";
  if (file.indexof("challenge-valid") > 0) req.alias = "call2";
  req.reply({ 
    fixtures: file
  })
});

```

**Comment by Narretz** [comment]
Pretty sure this works as intended because "last first" is necessary to support overrides of intercepts. For example, you have a global intercept that mocks a url, and in a single test you want to make it pass through. See this change log: https://docs.cypress.io/guides/references/changelog#7-0-1

**Comment by jennifer-shehane** [comment]
Please read about the lifecycle of intercept calls: https://on.cypress.io/intercept#Interception-lifecycle This is as intended.

**Comment by TheDutchCoder** [comment]
In retrospect that seems to make sense.
I somehow assumed that the aliasing would make that a non-issue, but I understand why a reverse order is needed to overwrite other intercepts. Thanks!

**Comment by DiegoMcDipster** [comment]
@TheDutchCoder , how did you get this to work in the end?  I've been trying to stub a login to aws since last friday and i'm hitting problem after problem. The current problem being the multiple calls the api makes to aws and how to handle that via cy.intercept.

Your guidance could really help me out, not only saving time but also grey hair!

**Comment by TheDutchCoder** [comment]
> @TheDutchCoder , how did you get this to work in the end? I've been trying to stub a login to aws since last friday and i'm hitting problem after problem. The current problem being the multiple calls the api makes to aws and how to handle that via cy.intercept.
> 
> Your guidance could really help me out, not only saving time but also grey hair!

I honestly can't quite remember, I think I used the API to log in in the end, instead of the UI (except for the actual login page test). I'll be digging into Cypress tomorrow and Friday again, so I can let you know after!

**Comment by DiegoMcDipster** [comment]
@TheDutchCoder that would be fantastic.  I really appreciate it!

**Comment by TheDutchCoder** [comment]
> @TheDutchCoder that would be fantastic. I really appreciate it!

So I previously ended up writing a custom command that I call before each test run, a sample of which would be this:
```
Cypress.Commands.add('addCognitoInterceptors', () => {
  cy.intercept('OPTIONS', 'https://cognito-idp.us-east-1.amazonaws.com', {
    'statusCode': 200,
    'headers': {
      'access-control-allow-headers': 'content-type,x-amz-target,x-amz-user-agent',
      'access-control-allow-methods': 'POST',
      'access-control-allow-origin': '*',
    },
  })

  // Intercept all preflight requests and return a 200.
  cy.intercept('OPTIONS', 'https://cognito-identity.us-east-1.amazonaws.com', {
    'statusCode': 200,
    'headers': {
      'access-control-allow-headers': 'amz-sdk-invocation-id,amz-sdk-request,content-type,x-amz-target,x-amz-user-agent',
      'access-control-allow-methods': 'POST',
      'access-control-allow-origin': '*',
    },
  })

  // Intercept all cognito identity calls and return fixtures based on the data
  // posted.
  cy.intercept({ method: 'POST', url: 'https://cognito-idp.us-east-1.amazonaws.com' }, (req) => {
    console.log('Cognito intercept', req)
    const { body } = req
    const user = Cypress.env('cognitoUser')

    // Handle username posts.
    if (body.AuthFlow && body.AuthFlow === 'CUSTOM_AUTH') {
      if (body.AuthParameters.USERNAME === utils.LOGIN_EMAIL_BOUNCE) {
        req.alias = 'customAuthInvalid'
        return req.reply(getUserEmailInvalid())
      } else {
        req.alias = 'customAuthValid'
        return req.reply(getUserEmailValid(user))
      }
    }

    // etc
})
```

Where we return different responses based on things like email address used in a test.
It's a bit "manual" and I pretty much just went through different real responses in our app, just so I could see what shape they were.

There's a bit more to it as well, I have to generate things like JWT tokens in our tests as well, to make sure you can login through a Cypress command.

The docs are a bit basic that way, it all sounds great in theory, but you really need to figure out the internals of these auth systems in order to be actually able to mock these things out. Not an easy task.

Hope this helps a bit!

**Comment by DiegoMcDipster** [comment]
Great!  Thanks so much for that.  Je hebt mij op een zaterdag nacht geholpen! Waarschijnlijk ben je de enige echt DutchCoder ;)

Yes, it does sound like a very painful process when the theory on the docs are as you said 'basic'. I've already raised a couple of discussions here and on discord.  But unfortunately no one has picked them up yet.

For now, because of time contstraints, I'll move these tests into E2E (and hope that someone at Cypress picks them up). And when I do get the time, I'll use your tips as a scaffold.

Again, I really appreciate your help!
