### ISSUE TITLE
Not able to access variable data captured from UI Element  outside the Then() for future use

### ISSUE THREAD

**Issue by vinaykona** [cypress-io/cypress#17386]
### Current behavior

Hi Everyone,
we are reading data from UI element and storing them in a Variable. In order to do that we have used: below code:
```js
Var myText; //declared globally
cy.get("textElement").then(($text)=>{
  myText=$text.text()
  cy.log(myText)   //it displayed the proper UI Element value inside this then
}}
```
Now we want to use myText variable data outside then() method some where in our class for future use. but, it is returning undefined or empty data
Note: Variable also we declared Globally.

### Desired behavior

Variable data what we captured inside the Then() method should be accessible out side of the then aswell to use for future use or some other purpose.but which is not happening.

### Test code to reproduce
```js
Var myText; //declared globally
cy.get("textElement").then(($text)=>{
  myText=$text.text()
  cy.log(myText)   //it displayed the proper UI Element value inside this then
}}
```

### Cypress Version

5.6.0

**Comment by jennifer-shehane** [comment]
I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).

You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
