### ISSUE TITLE
@cypress/vue: Allow to wrap components/specify globals when mounting

### ISSUE THREAD

**Issue by LeBenLeBen** [cypress-io/cypress#17387]
### What would you like?

I’d like to be able to configure how Cypress mount Vue components in component testing mode so that I can provide globals, install plugins, … and be able to wrap them in a custom root component.

### Why is this needed?

Some frameworks such as Vuetify require a global `vuetify` object on the `Vue` instance as well as all components to be wrapped in the `VApp` component, otherwise it trigger warnings in the simplest cases and doesn’t work at all in more complex situations.

### Other

Here’s an example how Storybook allows this:

```js
import { addDecorator } from '@storybook/vue';
import { VApp } from 'vuetify/lib';

import vuetify from '@/plugins/vuetify';
import i18n from '@/plugins/i18n';

addDecorator(() => ({
  vuetify,
  i18n,
  components: {
    VApp,
  },
  render() {
    return (
      <VApp>
        <div>
          <story />
        </div>
      </VApp>
    );
  },
}));
```

**Comment by JessicaSachs** [comment]
Hey @LeBenLeBen, we have a recipe that we use internally for this. We're working on documentation and an improved API design shortly, but essentially you want to create a custom Cypress command that wraps the raw `mount` function.

Registering the custom mount command:
```jsx
// Support File: support.jsx
import { mount as cypressMount } from '@cypress/vue'
import { addDecorator } from '@storybook/vue';
import { VApp } from 'vuetify/lib';
import vuetify from '@/plugins/vuetify';
import i18n from '@/plugins/i18n';

Cypress.Commands.add('mount', (component, overrides = {}) => {
  const mountOptions = {
    /* Anything you'd normally do in Vue Test Utils to setup your component */
    plugins: [ vuetify, i18n ]

    ...overrides // you'll wanna break this out to make it easier to override certain plugin settings (like Vuex)
  }

  return cypressMount(() => (<VApp>
    <div>
        <component is={component}/>
    </div>
  </VApp>), mountOptions)
})

```

And the usage:
```jsx
// Spec File: Modal.spec.jsx
it('renders', () => {
  cy.mount(() => <Modal show={true}/>)
})
```

**Comment by mariocardinal** [comment]
I've also run into this issue and would like to see it resolved, as I think this is a valid use case with regards to component testing.  I have tried JesssicaSachs workaround without success.  Unfortunately, until I see a proven approach to inject Vuetify ands i18n with '@cypress/vue', I am going to stay away from Cypress component testing and keep using StoryBook to obtain a playground for visual testing component. Sorry!

**Comment by lmiller1990** [comment]
Hi all, I am documenting various recipes relating to Vue and Cypress (Vuetify, Router, etc) here https://cypress-testing-handbook.netlify.app/vuetify.html. Github: https://github.com/lmiller1990/cypress-testing-handbook

If you have an issue, let me know and I will show you how I'd recommend solving it.
