### ISSUE TITLE
Cy.Url Doesnt support UTF-8 charset

### ISSUE THREAD

**Issue by arifozkan** [cypress-io/cypress#17399]
### Current behavior

I want to test Url to check the page right or not. But whenever url contains unique chars such as (ä, ö," " ) it errors. Is there any solution?

The first one is cy.url().The second one is original url. Url changes inside cypress test.
![image](https://user-images.githubusercontent.com/79975632/126234045-af4be391-49f0-4bf3-bd1a-47bb93bf8350.png)

My solution is 

```js
if(arrLost[2].raceLocation.includes("ä")){
  trackName.replaceAll("ä", "%C3%A4")
}
else if(arrLost[2].raceLocation.includes(" ")){
  trackName.replaceAll(" ", "%20")
}
else if(arrLost[2].raceLocation.includes(" ")){
  trackName.replaceAll("´", "%C2%B4")
}
cy.url().should("contain",trackName).wait(2000)
```

But this is waste of time. Thanks...

### Test code to reproduce

```js
if (arrLost[2].raceLocation.includes("ä")) {
  trackName.replaceAll("ä", "%C3%A4")
}
else if (arrLost[2].raceLocation.includes(" ")) {
  trackName.replaceAll(" ", "%20")
}
else if (arrLost[2].raceLocation.includes(" ")) {
  trackName.replaceAll("´", "%C2%B4")
}
cy.url().should("contain", trackName).wait(2000)
```

### Cypress Version

6.9.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

How about using `decodeURI` function like below?

```js
it('t', () => {
  cy.visit('https://mozilla.org/?x=шеллы')

  cy.url().then((url) => {
    expect(decodeURI(url)).to.contain('шеллы')
  })
})
```

**Comment by sainthkh** [comment]
@jennifer-shehane 

I believe there are 2 solutions for this issue:

* Add a note about `decodeURI` to [`cy.url` documentation](https://docs.cypress.io/api/commands/url#Syntax).
* Add `decode` option to the `cy.url` option.
