### ISSUE TITLE
Cypress Test runner crashes unexpectedly 

### ISSUE THREAD

**Issue by marijana-rukavina** [cypress-io/cypress#17409]
### Current behavior

I am testing an e-commerce site. I want to test the checkout flow with choosing the payment method Mastercard.
These are the steps performed in the test:

1. navigate to product detail page
2. add product to the cart
3. go to the checkout page
4. fill the form and choose Mastercard as the payment method
5. click the button to confirm the order
6. pop up opens (with the URL from our Payment Service Provider)
7. input the data required for the card (like card number, CVV, expiration date)
8. click the confirm button

After clicking the confirm button Test Runner crashes meaning that it just closes unexpectedly.

### Desired behavior

I would expect that Test Runner is kept opened and that I can see what is the error.

### Test code to reproduce

I cannot share the test repository since this is confidential data from the client. 
I am running the test on the privately secured environment not accessible publicly. 
Besides that, I don't know how to expose the payment service provider example since it is a third party system we are integrating with. 

### Cypress Version

8.0.0

### Other

I know this might lack in information but some ideas about in what direction to go would help. 
Also please let me know if I could somehow provide some logs. I am not that familiar with running cypress in debug mode so some more detailed information would be appreciated how to achieve that.   
Thanks!

**Comment by jennifer-shehane** [comment]
Could you try on a previous version of Cypress to run the tests? 7.7.0? 

We're not aware of any situations of the Cypress Test Runner crashing currently, so would like to know if this was recently introduced. 

Also, generally when there  is a crash there is an error that is printed to the  stdout in the terminal where you originally called `cypress open`. Can you provide that  error message?

Also could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by marijana-rukavina** [comment]
I run it first with 7.5.0 version and it happen there. Then I upgraded the version 8.0.0 and it happens there as well.
When I run `cypress open` and the test runner crashes I couldn't see any errors in the logs. 

I am on Windows 10 machine and I run these commands in order to start cypress in debug mode:  
`set DEBUG=cypress:*`  
`cypress open --env configFile=dev 2>logs.txt`
And I run my test. 
 
This is the [logs.txt](https://gist.github.com/marijana-rukavina/e4b728ad7904c892ed8b1282da742b6a) that I got.
I don't see any errors there, but it is a lot of data being logged so I might be missing something.  

Please let me know if I can provide with something else. I hope this information could tell us more about why the runner crashes and I am not able to see what is causing this.

**Comment by marijana-rukavina** [comment]
@jennifer-shehane 
Did you have the chance to look at the logs? Is there something else I can provide that could help in resolving it? :D

**Comment by Anonymvs17** [comment]
@jennifer-shehane is the log provided by @marijana-rukavina useful or do you need more info?

**Comment by mjhenkes** [comment]
Hi @marijana-rukavina, what we can tell from the logs is that cypress crashes somewhere between the `cypress:server:request successful response received` event and the `cypress:proxy:http:response-middleware received response` event.

Below are the relevant events. We're getting a json request sent down and something is happening to exit the app.
```
2021-07-21T10:06:24.793Z cypress:server:request received status code & headers on request { requestId: 'request88', statusCode: 200, headers: { 'content-type': 'application/json;charset=UTF-8' } }
2021-07-21T10:06:24.793Z cypress:server:request successful response received { requestId: 'request88' }
```

There's a couple of things we can try as next steps.
1. Try updating to our latest version, 9.2.0. It may not fix your issue but it will get us on the same baseline for debugging.
2. Is there an error printed to you console when cypress fails? Is anything else printed out when cypress quits?
3. Can we narrow the test case to produce a minimally reproducible (and ideally non confidential) test case? Does cypress crash if simply replay the last request? If so could you provide an example request for us to try to reproduce the crash?

**Comment by marijana-rukavina** [comment]
@mjhenkes Thanks a lot for your reply.
I tried upgrading to 9.2.0, but the issue remains :( 
I don't see any errors in the console except the bunch of logging stuff which I don't understand.
I will try to check with my team to see how would it be possible to provide the minimally reproducible test case.
In case it is not going to be possible, is there a possibility to have somebody take a look the issue with us in like one time debug session call?
Thanks! Please let me know what are the possibilities.
Regards,
Marijana Rukavina
