### ISSUE TITLE
cy.wrap() example is failing

### ISSUE THREAD

**Issue by drewbrend** [cypress-io/cypress#1740]
Hi, I have been trying to get cy.wrap() to work to share some context in my tests.  Figuring I've been doing something wrong I copy/pasted the example from https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context to build off of a working example.  To my surprise this also failed when ran.  My exact test is below, I've modified styling to please eslint in my project, otherwise it's copied straight from that page.

### Current behavior: 
Test fails with:  Cannot read property 'a' of undefined

### Desired behavior:
Test passes

### Steps to reproduce:
Copy and run this test, or the one from the link above.

```js
describe("parent", () => {
  beforeEach(() => {
    cy.wrap("one").as("a");
  });

  context("child", () => {
    beforeEach(() => {
      cy.wrap("two").as("b");
    });

    describe("grandchild", () => {
      beforeEach(() => {
        cy.wrap("three").as("c");
      });

      it("can access all aliases as properties", () => {
        expect(this.a).to.eq("one"); // true
        expect(this.b).to.eq("two"); // true
        expect(this.c).to.eq("three"); // true
      });
    });
  });
});
```

### Versions  
Cypress 2.1.0

**Comment by drewbrend** [comment]
I have modified the test to get it working for me, so I'm thinking the test in the docs is outdated perhaps?  Here's the passing version using `cy.get()` first:

`
describe("parent", () => {
  beforeEach(() => {
    cy.wrap("one").as("a");
  });

  context("child", () => {
    beforeEach(() => {
      cy.wrap("two").as("b");
    });

    describe("grandchild", () => {
      beforeEach(() => {
        cy.wrap("three").as("c");
      });

      it("can access all aliases as properties", () => {
        cy.get("@a").then(ay => expect(ay).to.eq("one")); // true
        cy.get("@b").then(bee => expect(bee).to.eq("two")); // true
        cy.get("@c").then(see => expect(see).to.eq("three")); // true
      });
    });
  });
});
`

**Comment by jennifer-shehane** [comment]
Also could do:

```js
cy.get('@a').should('eq', 'one')
cy.get('@b').should('eq', 'two')
cy.get('@c').should('eq', 'three')
```

**Comment by brian-mann** [comment]
You are using fat arrows as opposed to `function(){}` which will always preserve the outer context which will be `window`.

Using the `cy.get('@alias')` method avoids that so it's good.
