### ISSUE TITLE
ELECTRON_RUN_AS_NODE fails with --browser chrome

### ISSUE THREAD

**Issue by arschmitz** [cypress-io/cypress#17412]
### Current behavior

currently when combining `ELECTRON_RUN_AS_NODE` with `--browser chrome` in ubuntu with chrome 91 via github actions fails. with the error

```
We found an invalid configuration value:

Found an error while validating the `browsers` list. Expected `version` to be a non-empty string. Instead the value was: 

`{"name":"electron","channel":"stable","family":"chromium","displayName":"Electron","version":"","path":"","info":"Electron is the default browser that comes with Cypress. This is the default browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses."}`
```

Running `--browser chrome` works fine and runs headless in chrome 91

### Desired behavior

the should work as described in the docs and version 8 release notes 

### Test code to reproduce

`ELECTRON_RUN_AS_NODE=1 ENVIRONMENT=test cypress run --config-file cypress-listings.json --spec cypress/integration/listings.spec.ts --browser chrome`

cypress-listings.json
```
{
    "baseUrl": "http://localhost:3000",
    "componentFolder": "src/",
    "nodeVersion": "system",
    "reporter": "cypress/reporters/github-actions.js",
    "testFiles": ["**/listing*.spec.ts"],
    "video": false,
    "watchForFileChanges": true
}
```

### Cypress Version

8.0.0

### Other

Trying this locally on macos any use of `ELECTRON_RUN_AS_NODE` produces this seemingly unrelated error 

```
internal/modules/cjs/loader.js:890
  throw err;
  ^

Error: Cannot find module '/Users/username/Library/Caches/Cypress/8.0.0/Cypress.app/Contents/MacOS/Contents/Resources/app/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by jennifer-shehane** [comment]
This flag has not been fully tested and we should probably be clearer about this in the docs - that it's essentially experimental. 

What is the result of running `cypress info`? 

It seems like it's trying to run Electron, not Chrome like you specified. Not sure why the version would be empty.

**Comment by arschmitz** [comment]
```
Displaying Cypress info...

Detected 3 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 91.0.4472.114
  - Executable: google-chrome

2. Chromium
  - Name: chromium
  - Channel: stable
  - Version: 91.0.4472.0
  - Executable: chromium-browser

3. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 89.0.2
  - Executable: firefox

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox
- cypress run --browser chromium

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /home/runner/.config/cypress/cy/development
Browser Profiles: /home/runner/.config/cypress/cy/development/browsers
Binary Caches: /home/runner/.cache/Cypress

Cypress Version: 8.0.0
System Platform: linux (Ubuntu - 20.04)
System Memory: 7.29 GB free 205 MB
```

I also updated the original comment to show the output browser object with the empty version from the error

**Comment by jennifer-shehane** [comment]
I realize now this error is coming from our check of all of the browsers located on the machine.  So it seems the Electron version and path bundled with Cypress is not showing any version for the browser which is  weird. cc @mrmeku 

For  now, I would suggest not using the env var. This is not a high priority for our team to fix as this is experimental but if someone tracks down the  issue we would  open a PR to fix  it.

**Comment by rsudarson** [comment]
This is a useful feature, Can we please prioritize @jennifer-shehane

**Comment by jennifer-shehane** [comment]
This feature is not currently a priority for our team over other initiatives as explained in https://github.com/cypress-io/cypress/pull/16537#pullrequestreview-701384541. There will be effort in the future put in to remove Electron as a dependency, but there's no timeline for that currently.

**Comment by mrmeku** [comment]
I'll fix this when I have time. In my repo I'm currently patching cypress to remove the browser validation step. But a PR is definitely in order

**Comment by searls** [comment]
If it impacts priority at all, just an FYI that this is the only blocker preventing Cypress tests from being run on Heroku CI

**Comment by rsudarson** [comment]
@mrmeku - Thanks! This feature will improve the CI integration.

**Comment by nikoladjordjevicsymphony** [comment]
So sorry to bother you, but do we have any idea when will fix be available, or any workaround how to disable browser check or manually input Electron version into browsers config, so this implementation can work? Having major problems on starting Xvfb in our CI workflow. 😞

**Comment by ext** [comment]
I've ran into this myself, is there anything I can do to help troubleshooting or point me to the source code for detecting electron version? Shouldn't electron be pruned from the browser list if `ELECTRON_RUN_AS_NODE ` is used?

**Comment by ilovejs** [comment]
same in v9.1.0. Team not helping in gitter and discord.
previously, ppl also said https://gitter.im/cypress-io/cypress?at=5b753b04a2101b348b36a5c0
basically, it's a not tested feature that released.

**Comment by sproogen** [comment]
I ran into this issue recently and thought I would share my findings if anyone else is having a similar issue.

So when running with ELECTRON_RUN_AS_NODE=1 (we don't have Xvfb on our CI agents) and using --browser chromium, it looks like the chrome version cannot be found in the browser utils here https://github.com/cypress-io/cypress/blob/v9.5.2/packages/server/lib/browsers/utils.ts#L255 
It sets the version to an empty string if not found, but that causes an error for not being a valid browser config. It could be solved by updating this to be something like
```
if (!process.versions.chrome) {
  debug('underlying chrome version for electron not found, skipping adding electron browser')
  return browsers
}
const version = process.versions.chrome
```
I hadn't found the reason the chrome version doesn't get set when using ELECTRON_RUN_AS_NODE, but as mentioned in the documentation the electron browser can't run without an X11 server so not adding electron in this scenario doesn't seem like an issue.

I'm happy to raise a PR if this seems like a sensible solution.

In the mean time for anyone with this issue a workaround would be to edit the browsers list in your plugins/index.js similar to as mentioned in the docs here https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers
Filtering out browsers with an empty version like this
```
// cypress/plugins/index.js
module.exports = (on, config) => {
  // inside config.browsers array each object has information like
  // {
  //   name: 'chrome',
  //   channel: 'canary',
  //   family: 'chromium',
  //   displayName: 'Canary',
  //   version: '80.0.3966.0',
  //   path:
  //    '/Applications/Canary.app/Contents/MacOS/Canary',
  //   majorVersion: 80
  // }
  return {
    browsers:  config.browsers.filter((browser) => browser.version !== ''), // Filter out browsers without a valid version
  }
}
```

**Comment by thyarles** [comment]
I found that this problem happen when you have you browser installed for the first time and try to run it with the `ELECTRON_RUN_AS_NODE` enabled.

### To reproduce (on Cypress 9.6.0)
1. Clean your cache
```
$ yarn cypress cache clear
```
2. Reinstall the executables
```
$ yarn cypress install
Installing Cypress (version: 9.6.0)

✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation /home/thyarles/.cache/Cypress/9.6.0

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

Done in 57.61s.
```
3. Set the `ELECTRON_RUN_AS_NODE` as `1`
```
$ export ELECTRON_RUN_AS_NODE=1
```
4. Try to run Cypress
```
$ yarn cypress open
It looks like this is your first time using Cypress: 9.6.0

Cypress failed to start.
This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
Please refer to the error below for more details.

----------
/[...]/.cache/Cypress/9.6.0/Cypress/Cypress: bad option: --no-sandbox
/[...]/.cache/Cypress/9.6.0/Cypress/Cypress: bad option: --smoke-test
/[...]/.cache/Cypress/9.6.0/Cypress/Cypress: bad option: --ping=945
----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 9.6.0
error Command failed with exit code 1.

```
5. As you can see, if you try to run it the first time with the flag `ELECTRON_RUN_AS_NODE` enabled, the binary don't understand the flags `--no-sandbox`, `--smoke-test`, and `--ping=XXX`

7. If you unset the `ELECTRON_RUN_AS_NODE` flag and try again, it'll work
```
$ unset ELECTRON_RUN_AS_NODE
$ yarn cypress open
It looks like this is your first time using Cypress: 9.6.0

✔  Verified Cypress! /[...]/.cache/Cypress/9.6.0/Cypress

Opening Cypress...
Done in 6.88s.
```
8. From now on, you can set the `ELECTRON_RUN_AS_NODE` again and it'll work fine for run tests in Chrome (if you try to open, you'll get a lot of errors with Electron stuff).
```
$ export ELECTRON_RUN_AS_NODE=1
$ yarn cypress run --browser chrome | grep Running
  Running:  1-getting-started/todo.spec.js                                                 (1 of 20)
  Running:  2-advanced-examples/actions.spec.js                                            (2 of 20)
  Running:  2-advanced-examples/aliasing.spec.js                                           (3 of 20)
  Running:  2-advanced-examples/assertions.spec.js                                         (4 of 20)
  Running:  2-advanced-examples/connectors.spec.js                                         (5 of 20)
  Running:  2-advanced-examples/cookies.spec.js                                            (6 of 20)
  Running:  2-advanced-examples/cypress_api.spec.js                                        (7 of 20)
  Running:  2-advanced-examples/files.spec.js                                              (8 of 20)
  Running:  2-advanced-examples/local_storage.spec.js                                      (9 of 20)
  Running:  2-advanced-examples/location.spec.js                                          (10 of 20)
  Running:  2-advanced-examples/misc.spec.js                                              (11 of 20)
  Running:  2-advanced-examples/navigation.spec.js                                        (12 of 20)
  Running:  2-advanced-examples/network_requests.spec.js                                  (13 of 20)
  Running:  2-advanced-examples/querying.spec.js                                          (14 of 20)
  Running:  2-advanced-examples/spies_stubs_clocks.spec.js                                (15 of 20)
  Running:  2-advanced-examples/traversal.spec.js                                         (16 of 20)
  Running:  2-advanced-examples/utilities.spec.js                                         (17 of 20)
  Running:  2-advanced-examples/viewport.spec.js                                          (18 of 20)
  Running:  2-advanced-examples/waiting.spec.js                                           (19 of 20)
  Running:  2-advanced-examples/window.spec.js                                            (20 of 20)
```
That's the bug. My workaround on my CI is install Cypress, call it one time to warm up and then set the flag `ELECTRON_RUN_AS_NODE` to run my tests on Chrome without the race condition on virtual displays.
