### ISSUE TITLE
Cypress version in download name

### ISSUE THREAD

**Issue by PetMou** [cypress-io/cypress#17417]
### What would you like?

It would make cypress version management more easy if the downloaded cypress zip would have the version number in the name. Instead of the fixed 'cypress.zip' something like 'cypress_8_0_0.zip' 

### Why is this needed?

As we are behind a firewall we need to download the cypress zip to install. Further more we have several projects, where not all projects use the same version. Especially when coping with breaking changes it can make a difference.
You are a very active organisation (kudo's!), and releases happen all the time. So wen we download a version, it is not always instantly clear that again, where was a new release. This caused some issues in our organization.

**Comment by jennifer-shehane** [comment]
Since this request has not gotten a lot of interest over the years, we’ll close this issue.
