### ISSUE TITLE
Basic Authentication using cypress not working

### ISSUE THREAD

**Issue by STamilarasan** [cypress-io/cypress#17420]
### Current behavior

My application has basic auth where user needs to enter username/password in the alert and I tried to login my application by passing username and password in the URL and it didn't work in cypress.

Example:
```js
cy.visit('https://myUserName:myActualPassword@domain');
cy.visit('https://john:password123@v10n5056:558/dashboard'); // This works well directly in browser, logging in.
```
Error Message:
```
cy.visit() failed trying to load:

https://v10n5056:558/dashboard

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: socket hang up

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
```
### Desired behavior

Cypress should login into application when username and password are passed in the url in case of basic auth.

### Test code to reproduce
```js
describe("Login",()=>{
    it.only("TestcaseOne",()=>{
            //  Cypress.config('chromeWebSecurity',false);
           cy.visit('https://john:password123@v10n5056:558/dashboard'); 
          //this works fine when username and password is sent in url directly in browser
    })
})
```

### Cypress Version

8.0.0

### Other

Is there any alternate way or work around to proceed further by logging in.
Below ways are also not working.

2) `cy.visit('https://v10n5056:558/dashboard', {
           auth: {
              username: 'john',
              password: 'password123',
           },
           })`

3) `cy.ntlm('https://v10n5056:558/', 'john', 'password123');`

Error:
```
cy.visit() failed trying to load:

https://v10n5056:558/dashboard

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: socket hang up

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
````

**Comment by jennifer-shehane** [comment]
Both the 1st and 2nd way shown are ways that should  work within Cypress. I'm not familiar with ntlm's plugin to say how it would work. Maybe there's some edge case around how this  url is, with  the port number that is causing it to not work? It'd be hard to verify without a way  to reproduce it on our end.

**Comment by STamilarasan** [comment]
Thanks for quick response, I went through many blogs and tried different solutions but nothing worked for me. As you mentioned, it could be because of port number in url, I m new to cypress, not sure about it. Without able to logging in, I m completely struck with this for long long time. Is there any work around to achieve this that would be much helpful.

P.S. As my application's url is not for public access, it will not be working for others.

**Comment by STamilarasan** [comment]
> Both the 1st and 2nd way shown are ways that should work within Cypress. I'm not familiar with ntlm's plugin to say how it would work. Maybe there's some edge case around how this url is, with the port number that is causing it to not work? It'd be hard to verify without a way to reproduce it on our end.

Thanks for quick response, I went through many blogs and tried different solutions but nothing worked for me. As you mentioned, it could be because of port number in url, I m new to cypress, not sure about it. Without able to logging in, I m completely struck with this for long long time. Is there any work around to achieve this that would be much helpful.

P.S. As my application's url is not for public access, it will not be working for others.
