### ISSUE TITLE
cypress.open() promise doesn't fire until Cypress is closed

### ISSUE THREAD

**Issue by KevinGhadyani-minted** [cypress-io/cypress#17429]
### What would you like?

I'd like a way to either pass a callback or boolean to Cypress so when the `.open` command runs, it notifies me that it's done opening, not only when the window is closed.

### Why is this needed?

I need this functionality because I've built a react-scripts style library for work which includes Cypress and needs to begin the next tasks when `cypress.open` is done doing its thing.

I also need to unit test that this functionality is working, but since `cypress.open` only notifies me when closed, that'll never happen during a unit test.

In another library, Storybook fires its promise when Webpack is done compiling, not when you're killed the process. That's exactly what I need to know, so I can begin the next piece of the chain.

**Comment by jennifer-shehane** [comment]
@KevinGhadyani-minted Yeah, I see what you  mean. There is a `before:run` event that you  could listen to and possibly do what you need in there: https://on.cypress.io/before-run-api or maybe the `before:spec` depending on the specifics of what you need to do. https://on.cypress.io/before-spec-api Do you think either of those could satisfy what you need?
