### ISSUE TITLE
Add an error message for incorrect syntax when using wait()

### ISSUE THREAD

**Issue by AbrahamBrookes** [cypress-io/cypress#17436]
### What would you like?

I made a silly mistake today that stumped me for too long. When writing my intercept tests I passed the callback as a second parameter to `wait`, instead of using a `then`:

```js
// WRONG:
cy.wait('@request', (interception) => {
    // do stuff
})

// RIGHT:
cy.wait('@request').then((interception) => {
    // do stuff
})
```

Obviously this was totally my mistake, but it seems like something that could have an error message for morons like me?

**Comment by jennifer-shehane** [comment]
This wouldn't be too hard to implement. Detect that the second argument passed to `cy.wait()` is a function and throw an error explaining that the 2nd argument is meant to be an options object. We do this in our other commands. We'd be open to a PR. 

Code is here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/waiting.js#L269:L269

**Comment by corentinclichy** [comment]
Hi Jennifer,
Hope you are doing well. 
Is it still needed a fixed? 

I can try to solve this!
