### ISSUE TITLE
Using routeHandler > request.continue() callback is not stubbing response.statusCode

### ISSUE THREAD

**Issue by paxcodes** [cypress-io/cypress#17447]
### Current behavior

Status code of the network call still shows 200 in dev tools.

### Desired behavior

Network calls as seen in dev-tools will result in 500 because I stubbed it to be 500.

### Test code to reproduce

1) Given this command,

```js
describe('page', () => {
  it('blocks network calls', () => {
    cy.intercept(
      "*", (request) => {
        request.continue(response => {
          response.statusCode = 500;
        });
      }).as('interceptedRequest');
    cy.visit('https://example.cypress.io');
  })
});
```

2) Everything in dev-tools still show up as 200 when everything should be 500

![Screen Shot 2021-07-22 at 6 52 07 AM](https://user-images.githubusercontent.com/13646646/126650556-4be4a859-741f-4c93-b691-c68a6d97f08b.png)

### Cypress Version

7.7.0 / 8.0.0

### Other

Using staticResponse works as expected:

```js
cy.intercept(
  "*", { statusCode: 500 }
).as('interceptedRequest');
```

I need to use the routeHandler callback instead of a staticResponse because I have other logic that goes in the callback.

**Comment by sainthkh** [comment]
```html
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="/node_modules/jquery/dist/jquery.js"></script>
  </head>
  <body>
    <button id="request">request</button>
    <div id="result"></div>
    <script type="text/javascript">
      $(function(){
        $("button#request").click(function(){
          $.ajax({
            method: "POST",
            url: "/post-only",
            data: JSON.stringify({client: 'data'}),
            success: function(data, textStatus, xhr) {
              $("#result").text(xhr.status)
            },
            complete: function(xhr, textStatus) {
              $("#result").text(xhr.status)
            },
          })
        })
      })
    </script>
  </body>
</html>
```

```js
it('works', () => {
  cy.intercept(
    '/post-only', { statusCode: 500 },
  )

  cy.visit('fixtures/a.html')

  cy.get('#request').click()

  cy.get('#result').contains('500') // works
})

it('fails', () => {
  cy.intercept(
    '/post-only', (request) => {
      request.continue((response) => {
        response.statusCode = 500
      })
    },
  )

  cy.visit('fixtures/a.html')

  cy.get('#request').click()

  cy.get('#result').contains('500') // fail
})
```

@flotwig I reproduced the case above. And it seems that it's a bug. 

[According to the documentation](https://docs.cypress.io/api/commands/intercept#Response-object-properties), `statusCode` of the `res` can be modified, but in the reproduction above, it does not return the modified `statusCode`. 

Am I missing something?

**Comment by sainthkh** [comment]
I researched more on the problem and learned that your problem can be solved by sending the status code with `res.send()` like below:

```js
  cy.intercept(
    '/post-only', (request) => {
      request.continue((response) => {
        response.send({ statusCode: 500 })
      })
    },
  )
```

When you want to modify the response and send it to the client with the `continue` function, `res.send()` should be called.
