### ISSUE TITLE
Scope `before` hooks in tests

### ISSUE THREAD

**Issue by TheDutchCoder** [cypress-io/cypress#17451]
### What would you like?

It would solve a lot of issues if `before` hooks were scoped to `describe` blocks, instead of being hoisted out of files and into the global scope.

Especially since all those hooks fire before the global `beforeEach` hooks.

### Why is this needed?

Example: I have to define interceptors in `before` **and** `beforeEach` globally, because some tests set a variable in their `before` hook that influence the intercepts (their responses actually).

I assumed `beforeEach` would be enough for obvious reasons, but the test's `before` hook gets hoisted up and run before the global `beforeEach` is executed.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
