### ISSUE TITLE
Add slice function

### ISSUE THREAD

**Issue by jkevingutierrez** [cypress-io/cypress#17450]
### What would you like?

Similar to how we have the `eq` function in Cypress (https://docs.cypress.io/api/commands/eq) that match the behavior of jQuery `eq`, it would be useful to have an implementation of the `slice` function https://api.jquery.com/slice/

### Why is this needed?

There are cases where we don't need to use all the elements, but only a few of them, and sometimes, having a selector with `:nth-child` or `:nth-of-type` is not enough to select the subset. There is the `:lt` selector, but it is deprecated https://api.jquery.com/lt-selector/ and more than that, it can be confused as it is not an oficial CSS selector.

**Comment by jennifer-shehane** [comment]
Since this request has not gotten a lot of interest over the years, we’ll close this issue.
