### ISSUE TITLE
Cypress tests fail randomly when first running test via cypress open

### ISSUE THREAD

**Issue by lancepollard** [cypress-io/cypress#17454]
### Current behavior

Current behavior is that when I run `npx cypress open` or `yarn run cypress open` and then click on a test suite to run, the test suite almost always takes a while at the first `cy.visit` step, and then fails at the first check/query/etc.. For example, we have this:

```js
Cypress.Commands.add('setupTests', (actions) => {
  return cy.request('POST', `${Cypress.env('API_URL')}/test-setup`, {
    actions,
  });
});

Cypress.Commands.add('getTableRow', (id: string) => {
  return cy.get(`[data-row-key="${id}"]`);
});
```

```js
describe('Something', () => {
  let userId;

  before(() => {
    cy.setupTests({ action: 'createUser' }).then(({ body }: any) => {
      userId = body.userId;
    });
  });

  it('can do something', () => {
    cy.visit('/some/page');
    cy.getTableRow(userId);
  });
});
```

The `setupTests` makes a graphql call to the BE to create some data for the test. The `[data-row-key=${userId}]` _always_ exists on the second+ run of cypress (presumably after everything is loaded into memory). But it _almost_ always faiils on the first run right at the first step. Doesn't really matter what the first step is, as long as it's accessing the DOM.

Why is this? What are some things that could be going wrong?

Also note, the `cy,visit` step almost always takes over 10-20 seconds to load. By the first step, sometimes the screen is still blank. However, when I hover over the `cy.visit` step when looking back over the history, it appears that the data was loaded, so the history isn't accurately reflecting what's going on.

### Desired behavior

Desired behavior is for tests to always run successfully on the first try.

### Test code to reproduce

I can't provide an extract of our code, it is too large.

### Cypress Version

7.6.0

### Other

I am on a MacBook Pro M1, and my server is running through docker, but I run the `cypress open` command outside of docker.

**Comment by jamos99** [comment]
Wonder if part of your issue might be the use of 
let to store the user id as the return of a custom command. https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Aliases
