### ISSUE TITLE
`cy.get('@thing')` returns the wrong type

### ISSUE THREAD

**Issue by TheDutchCoder** [cypress-io/cypress#17456]
### Current behavior

In TypeScript, when you have something aliased like an array, the returned type of `cy.get('@thing')` is `jQuery<HTMLElement>`.

### Desired behavior

The return type to be the type passed in to the alias.

### Test code to reproduce

```ts
type User = {
  id: string;
}

const thing: User[] = []
cy.wrap(thing).as('thing')
cy.get('@thing').then(thing => {}) // thing is of type jQuery<HTMLElement>, but should be of type User[]
```

### Cypress Version

8.0.0

**Comment by jennifer-shehane** [comment]
We'll review any PRs submitted to improve the types, so PRs are welcome.

**Comment by sainthkh** [comment]
TypeScript cannot statically detect the type of user-defined aliased name. Use the generics below:

```ts
cy.get<User[]>('@thing').then((thing) => {})
```

![Screenshot from 2021-07-26 14-53-39](https://user-images.githubusercontent.com/8130013/126939680-e9081d92-6659-4010-8810-90b9b212ff5b.png)
