### ISSUE TITLE
Alias created in global `beforeEach` hook is not available in a test's second `before` hook

### ISSUE THREAD

**Issue by TheDutchCoder** [cypress-io/cypress#17467]
### Current behavior

The condensed code below shows that an alias created in the global beforeEach hook is _not_ available in a test's **second** before hook.

```ts
// setup file
before(() => {
  console.log('global before')
  cy.getUsers() // exposes `@users`
})

beforeEach(() => {
  console.log('global beforeEach')
  cy.getUsers() // exposes `@users`
})
```

```ts
// test file
describe('Profile', () => {
  describe('New user', () => {
    before(() => {
      console.log('local before 1')
      cy.get('@users').then(users => {}) // works
    })
  })

  describe('Owner', () => {
    before(() => {
      console.log('local before 2')
      cy.get('@users').then(users => {}) // fails
    })
  })
})
```

Console output:
```
global before
global beforeEach
local before 1
global beforeEach
local before 2
```

`cy.getUsers()` assigns an alias `cy.wrap(users).as('users')` and runs every time correctly.

Also note that this all works fine if the test's `before` hooks are changed to `beforeEach` hooks for some reason, but I don't want to needlessly log in every time before a single test, I do that in the nested describe block.

### Desired behavior

Aliases to be available to both types of hooks in a test.

### Test code to reproduce

See Above

### Cypress Version

8.0.0

**Comment by TheDutchCoder** [comment]
To add: the only alternative I've found is to split the test in multiple files.
That's "fine" for now, but I'd rather have the option to bundle related tests.

**Comment by sainthkh** [comment]
Sorry for the late reply.

[The example here](https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Sharing-Context) might help you solve the problem.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
