### ISSUE TITLE
E2E test for react app - React portal isn't shown

### ISSUE THREAD

**Issue by NumanIjaz** [cypress-io/cypress#17466]
### Current behavior

While testing a react app, I have dropdown buttons which are implemented using React Portals. By clicking on the button, the portal should be shown. However when I click on the button (through cy.contains('button', 'My Tasks').click() or manual click in the cypress-controlled chrome window), the portal isn't shown.

The DOM is not updated.

### Test code to reproduce

Here is my test

```js
describe("My Tasks", () => {
    it("renders the dropdown", () => {
        cy.visit("http://localhost:8888/tasks");
        cy.contains('button', 'My Tasks').click();
    });
});
```

The DOM highlights the portal div when clicking on the button however the inner html of the div is not filled (Like in normak case when I have it running outside of cypress).

### Cypress Version

8.0.0

**Comment by jennifer-shehane** [comment]
Have you checked DevTools to see if there are any errors being shown there? Could you print if there are any errors shown?

**Comment by NumanIjaz** [comment]
The following is printed on the console:

![image](https://user-images.githubusercontent.com/12031506/126802842-0ba5559e-b384-4a9e-909d-18468b0b6a91.png)
