### ISSUE TITLE
Visits with a hash (#) where you are visiting the same base url will not re-visit the page.

### ISSUE THREAD

**Issue by nishio** [cypress-io/cypress#17479]
### Current behavior

When I use `cy.visit('/')`, the page is re-visited and states are reset. (see code A, C)
However, when I use `cy.visit('/#blank')` (URL with hash), the page is not re-visited and states are retained. (see code B)

It cause unexpected influence between tastcases.

### Desired behavior

`cy.visit` should always visit the specified page.

### Test code to reproduce

```js
  it("main", () => {
    cy.visit("/");
    cy.window().its("x").should("eql", undefined);
    cy.window().then(window => {window.x = 1})
    cy.window().its("x").should("eql", 1);

    cy.visit("/");
    cy.window().its("x").should("eql", undefined); // (A)
    cy.window().then(window => {window.x = 2})
    cy.window().its("x").should("eql", 2);

    cy.visit("/#blank");
    cy.window().its("x").should("eql", 2);  // (B)

    cy.visit("/");
    cy.window().its("x").should("eql", undefined);  // (C)
  });
```

### Cypress Version

8.0.0

### Other

It may related to #225

**Comment by nishio** [comment]
It is expected behavior of browsers, not test runners. We need to isolate each tests.

**Comment by nishio** [comment]
Are there any way to force browser reload? I am developing single page application whose all URLs have a hash. I need methods to isolate each test cases.

**Comment by JessicaSachs** [comment]
If you need to force route reloading, you can make a new test (this will destroy the entire iframe) or you can use `document.location.reload` after setting the hash with `cy.visit(...)`. 

If you'd like to isolate your when navigating between hashes, you can do something like the below... which acts like `Cmd + R` instead of the browser's normal hash navigation.

```
it("main", () => {
  cy.visit("/#blank")
  cy.window().then(window => {window.x = 2})
  cy.window().its("x").should("eql", 2);

  cy.visit("/").document().its('location').invoke('reload');
  cy.window().its("x").should("eql", undefined);  // (C)
});```

**Comment by nishio** [comment]
Thank you!
