### ISSUE TITLE
The screenshot filename generated when running a case error has Spaces, which can cause some bugs in reading the file (在 运行 case错误情况下生成的截图文件名有空格，会导致某些读取文件的bug)

### ISSUE THREAD

**Issue by Yangfan2016** [cypress-io/cypress#17474]
### Current behavior

The screenshot file name generated when running a case error has Spaces, which can cause some bugs in reading the file (在 运行 case错误情况下生成的截图文件名有空格，会导致某些读取文件的bug)

![image](https://user-images.githubusercontent.com/17830872/126873247-352a3977-8059-4735-93df-27aa6ad99c19.png)

https://github.com/cypress-io/cypress/blob/b457010bd742a64da64daf7816ce8832f63990f7/packages/server/lib/screenshots.js#L365

### Desired behavior

Remove whitespace, or you can let the user define the file name in case of failure
去掉空格，或者可以让用户自定义失败时的文件名

### Test code to reproduce

![image](https://user-images.githubusercontent.com/17830872/126873238-01f5171a-b1d9-4432-ac2d-0611caa24bdb.png)

### Cypress Version

6.9.1

**Comment by jennifer-shehane** [comment]
@Yangfan2016 Can you explain the error that you see when attempting to read filenames with spaces? Spaces are allowed in filenames and something that should be able to be read in all cases because you can name a file with spaces.
