### ISSUE TITLE
Unable to visit a site using Cypress. Getting access denied.

### ISSUE THREAD

**Issue by rupakgithub** [cypress-io/cypress#17473]
### Current behavior

I am trying to visit a website using cypress to test file upload. When I use Cypress it shows access denied. But when I tried using Selenium it worked fine.

### Code to reproduce

``` javascript
describe('Test upload file with cypress',function(){
    beforeEach(function(){
        cy.visit('https://easyupload.io',{failOnStatusCode: false});
    })
    it('upload pdf file',() =>{
        cy.get('form#dropzone').attachFile(
            {
                filePath: 'example.json',
                mimeType: 'document/json',
                encoding: 'binary'
            },
            {
                subjectType: 'drag-n-drop',
                force: true,
            })
        cy.wait(2000);
    });
})
```

### Cypress Version

7.7.0

### Screenshot
![image](https://user-images.githubusercontent.com/13873164/126867650-1aa8e11c-e799-439d-a0f8-99f89febf173.png)

**Comment by jennifer-shehane** [comment]
When I try to load this page outside the US, I get directed to a Cloudflare page first. 

<img width="1558" alt="Screen Shot 2021-07-26 at 10 41 48 AM" src="https://user-images.githubusercontent.com/1271364/127020556-73b7bb9a-7b01-41eb-970a-5061c58152cb.png">


When trying to load inside the US it just hits this 403 page as you've shown above. I'm not sure why it says the content-type is `text/plain` I can see the content-type outside of Cypress as `text/html; charset=UTF-8`.

**Comment by Sumedh-k** [comment]
Cloudflare is blocking the request. You should look at the network traffic and see what headers Selenium sends and then compare that with Cypress.

**Comment by rupakgithub** [comment]
@HartiganHM sorry for the late reply. I haven't able to achieve it. If that worked for you please let us know.

**Comment by bruno88cabral** [comment]
any news on this case?

**Comment by alexlazarciuc** [comment]
Looking for a possible solution as well.

**Comment by gustawdaniel** [comment]
I had exactly the same problem

![cloudflare-access](https://user-images.githubusercontent.com/16663028/192750751-b93d9004-4587-477f-814d-0a5c9897f3ea.png)

Fixed by opening cypress in electron instead of chrome.
