### ISSUE TITLE
Cypress cy.request does not change the whole url when ws:// is present

### ISSUE THREAD

**Issue by Lumca** [cypress-io/cypress#17472]
### Current behavior

When I am trying to send POST request with cy.request to ws://127.0.0.1:8580/, but before I have visited a website with different URL, it simply joins them together.

![image](https://user-images.githubusercontent.com/4989415/126866178-00a36778-e50e-4eee-8707-f7731f3910ac.png)

### Desired behavior

When I present ws:// it should be taken as whole new URL.

### Test code to reproduce
```
describe('reporduce the bug', () => {
it('Visits google, send POST to different URL', () => {
        cy.visit('https://www.google.com')
        cy.request({
            method: 'POST',
            url: 'ws://127.0.0.1:8580/rdc-api/ws/'
        });
    });
});
```

### Cypress Version

7.5.0

**Comment by flotwig** [comment]
@Lumca `ws` is not a valid protocol to use with `cy.request` (or `POST`), use `http` instead:

```ts
describe('reporduce the bug', () => {
it('Visits google, send POST to different URL', () => {
        cy.visit('https://www.google.com')
        cy.request({
            method: 'POST',
            url: 'http://127.0.0.1:8580/rdc-api/ws/'
        });
    });
});
```
