### ISSUE TITLE
Wait for clickable button

### ISSUE THREAD

**Issue by pcmanprogrammeur** [cypress-io/cypress#17475]
### What would you like?

Hi,
I would like to click on a button where the click is loaded after JS execution.
I would like to avoid cy.wait(XXX)
How can i do that please ?

**Comment by jennifer-shehane** [comment]
You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions) or asking in our [chat](https://on.cypress.io/discord). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.

**Comment by bahmutov** [comment]
See answer in this blog post https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/
