### ISSUE TITLE
Component testing broken on next@11.0.2-canary.20

### ISSUE THREAD

**Issue by WillSquire** [cypress-io/cypress#17476]
### Current behavior

Using an early release of `next` (`11.0.2-canary.20`) breaks `cypress` component testing. This release is critical to many users as it fixes a performance issue with their `Image` component, blocking usage for many. See https://github.com/vercel/next.js/issues/23637

Running tests with this version throws `Error: Cannot find module 'next/dist/next-server/server/config'`.

### Desired behavior

Not throw an error.

### Test code to reproduce

Running component tests.

### Cypress Version

8.0.0

### Other

```
"@cypress/react": "^5.9.2",
"@cypress/webpack-dev-server": "^1.4.0",
"@testing-library/cypress": "^8.0.0",
"cypress": "^8.0.0",
"html-webpack-plugin": "5",
"webpack": "5",
"webpack-dev-server": "3"
```

**Comment by WillSquire** [comment]
Is there any releases of that fix the moved config yet? It's a bit of a show stopper for me, as the Next.js update has a critical bug fix and the project uses Cypress 'whole hog' - i.e. everything is tested with Cypress.

**Comment by WillSquire** [comment]
Is there any release date or a pre-release version available for this?

**Comment by elevatebart** [comment]
It has been release in version `@cypress/react@5.9.3`

**Comment by WillSquire** [comment]
This is still erroring with `Cannot find module 'next/dist/next-server/server/config'`? 

Is this update meant to read `next/dist/server/config.js` instead? Can we override this path? It's a major blocker, the project can't run without tests.

**Comment by elevatebart** [comment]
I do, you are right. It should be in a `else` statement. How did we miss that.
Let me fix that. 

In the meantime, I invite you to use `patch-package`.
