### ISSUE TITLE
Support a NO_COLOR argument to force disabling all colors

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1748]
Because we are now aggressively forcing color output in CI, we need to support a `NO_COLOR=1` argument when spawning Cypress.

**Comment by jennifer-shehane** [comment]
Is this accessible to users of Cypress? Or only internal?

**Comment by brian-mann** [comment]
It's an environment variable the user would add to their system or use when spawning Cypress

```
NO_COLOR=1 cypress run
```
