### ISSUE TITLE
Add is inViewport assertion

### ISSUE THREAD

**Issue by jkevingutierrez** [cypress-io/cypress#17483]
### What would you like?

It would be great to have the ability to check if some element is not only visible, but also in the viewport.

Something like:

```
cy.get('nav')
  .should('be.inViewport')
```
There are some solutions, like https://github.com/cypress-io/cypress/issues/877#issuecomment-538708750  and https://github.com/cypress-io/cypress/issues/877#issuecomment-490504922

But it looks like a common assertion that would be great to have built in Cypress.

### Why is this needed?

Checking if some element is in the viewport is a common case that we want to check in Cypress. It would be good to have it in the Cypress core.

**Comment by jennifer-shehane** [comment]
Due to the low amount of interest in this feature request, we’ll close this as not planned work.
