### ISSUE TITLE
cy.select() Should Look For Trimmed Value Inside of <option></option>

### ISSUE THREAD

**Issue by pihish** [cypress-io/cypress#175]
When an option element is formatted with line breaks:

``` html
<option value="someNumber">
    Gold package
</option>
```

`cy.select()` is unable to find the option by element text because of the line breaks.  `cy.select()` should trim the `text()` value of `<option>` before trying to match it with the parameter passed in.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
