### ISSUE TITLE
Cannot set property 'err' of undefined

### ISSUE THREAD

**Issue by memee** [cypress-io/cypress#17501]
### Current behavior

From time to time after `cy.exec` is run, I get following error:

```
The following error originated from your application code, not from Cypress.

  > Cannot set property 'err' of undefined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.

Because this error occurred during a after each hook we are skipping the remaining tests in the current suite
```

It doesn't come from my application though, but from cypress_runner.js from `hookFailed` function. Line `var test = getTest() || getTestFromHookOrFindTest(hook)`. First returns `null` and second returns `undefined`, so `test.err = err;` fails.

### Desired behavior

I should see the real error which caused the problem

### Test code to reproduce

Let me know if failing test repo is needed it uses npm script to clear database.

### Cypress Version

4.12.1

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

After that, can you provide a failing test case that we can run to see this error  throw ourselves? That will help us track down the issue.

**Comment by memee** [comment]
@jennifer-shehane thank you. Upgrading Cypress helped. With 8.0.0 everything is ok.
