### ISSUE TITLE
Cypress tests fail

### ISSUE THREAD

**Issue by nickland03** [cypress-io/cypress#17519]
### Current behavior

I'm using Renovate for updating Node dependencies. It suggested using the latest version (11.0.2-canary.23) this morning, but the tests on the pull request fail with the following message:

```
The function exported by the plugins file threw an error.
We invoked the function exported by `[my_dir_path]/cypress/plugins/index.js`, but it threw an error.
Error: Cannot find module 'next/dist/next-server/server/config'
```

cypress/plugins/index.js:
```javascript
/// <reference types="cypress" />
/**
 * @type Cypress.PluginConfig
 */
module.exports = (on, config) => {
    const injectDevServer = require('@cypress/react/plugins/next')
    injectDevServer(on, config)

    return config
}
```

### Desired behavior

Tests should still be passing and not throwing an error.

### Test code to reproduce

Try using Cypress and Next.js with their latest version

### Cypress Version

8.0.0

**Comment by lmiller1990** [comment]
Possible dup: https://github.com/cypress-io/cypress/issues/17476
