### ISSUE TITLE
Uncaught exception from testing web application not fail cypress test

### ISSUE THREAD

**Issue by alexneo2003** [cypress-io/cypress#17518]
### Current behavior

My testing web application based on angular in some case it would trigger uncaught exception in console byt cypress not detect this
I'm can't to reproduce this in isolated test because it is standalone angular app, i'm can't coding on angular)
i can share code from app that would be trigger exception
``` javascript
  onChangePhone(event) {
    event.preventDefault();
    const srcElement = event.srcElement || event.target;
    const phone = srcElement ? srcElement.value : '';
    if (phone.length === 19) {
      this.lastNameInput.nativeElement.focus(); // <--- this line trigger exception
    }
  }
```
![image](https://user-images.githubusercontent.com/11705902/127478011-12d6ede9-9548-4d65-936e-7248848feea1.png)

screencast
https://screenrec.com/share/PlLfgMvDBw

### Desired behavior

cypress would be detect Uncaught exception and fail tests

### Test code to reproduce

I'm can't to reproduce this in isolated test

### Cypress Version

8.0.0

### Other

I'm not using any overrides for 'uncaught:exception' described [docs](https://docs.cypress.io/api/events/catalog-of-events#Uncaught-Exceptions)

**Comment by JessicaSachs** [comment]
The exception throws **after** the test is completed. Cypress can't fail the test if the application throws an exception after the test is completed.

**Comment by alexneo2003** [comment]
> The exception throws **after** the test is completed. Cypress can't fail the test if the application throws an exception after the test is completed.

oke, i'm make full screencast with full test - https://screenrec.com/share/PxZK9AJWO0
test not failed
