### ISSUE TITLE
Rerun selected test

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#17516]
### What would you like?

During debugging, when I ran group of tests in Cypress window and some of tests fail, I would like to rerun only failed ones, while keeping results of  ones ended with success. Currently I can only rerun whole group by clicking Run All Tests button.

### Why is this needed?

To safe time of tests execution.

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/4886
