### ISSUE TITLE
MacOS: Cypress cannot find chrome:beta

### ISSUE THREAD

**Issue by FRSgit** [cypress-io/cypress#17513]
### Current behavior

After upgrade to Cypress@7.6.0 (and further to 8.0.0) it has stopped finding chrome:beta browser. Everytime I try to run the test suite with `yarn cypress run --browser chrome:beta` (even though Google Chrome Beta is installed in the default location) I get:
```
yarn run v1.22.5
$ /Users/jakubfreisler/Projects/Phrase/vue-components/packages/vue3/node_modules/.bin/cypress run --browser chrome:beta
Can't run because you've entered an invalid browser name.

Browser: 'chrome:beta' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- chrome
- firefox
- electron
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Desired behavior

To run chrome beta

### Test code to reproduce

macOS Big Sur 11.2.3 (20D91)
`yarn cypress --browser chrome:beta`

### Cypress Version

8.0.0

**Comment by FRSgit** [comment]
[Detailed cypress log](https://github.com/cypress-io/cypress/files/6897044/debug_cypress.log)

**Comment by jennifer-shehane** [comment]
I can recreate this. I have Chrome beta installed and Cypress cannot find it. Will have to investigate further on why this would be happening. Likely the location of the install.

**Comment by jennifer-shehane** [comment]
Can I ask which version you upgraded from before you were on 7.6.0?

**Comment by jennifer-shehane** [comment]
I'm not finding a version where this was working, went back to 6.1.0. Did you recently update to Big Sur? Perhaps we're not finding the correct install location on Big Sur. 

The location on my Mac Big Sur is at `/Applications/Google\ Chrome\ Beta.app/Contents/MacOS/Google\ Chrome\ Beta` which looks correct to me from our code: https://github.com/cypress-io/cypress/blob/develop/packages/launcher/lib/darwin/index.ts#L22:L22

**Comment by FRSgit** [comment]
@jennifer-shehane Sorry, forgot to check my notifications before. Now I also tried to downgrade cypress, but no luck so far. On thing - I'm 100% sure that it have worked with Big Sur (I've set up my chrome:beta pipeline when I was already on Big Sur). So I don't know what might be the reason, but IMO it's not the Mac update.
For me the location of Google Chrome Beta is the same

**Comment by FRSgit** [comment]
Just FYI - the issue is still in the newest Cypress version.

**Comment by mschile** [comment]
Closing as I am able to successfully run `chrome:beta` on MacOS Sonoma.


```

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.16.1                                                                        │
  │ Browser:        Chrome Beta 132 (headless)                                                     │
  │ Node Version:   v22.11.0 (/Users/mschile/.nvm/versions/node/v22.11.0/bin/node)                 │
  │ Specs:          1 found (todo.cy.js)                                                           │
  │ Searched:       cypress/e2e/1-getting-started/todo.cy.js                                       │
  │ Experiments:    experimentalWebKitSupport=true                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```
