### ISSUE TITLE
Cypress 7 & 8 changed Element.getAttribute

### ISSUE THREAD

**Issue by endercrest** [cypress-io/cypress#17512]
### Current behavior

It seems that both Cypress 7 & 8 changed the return value for [Element.getAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute) from null to empty string when the attribute doesn't exist in Chrome. This occurred when executing on a returned element from a document body event listener. 

This is different from the return value chrome gives when running without cypress

### Desired behavior

Expected cypress to continue to follow the respective browser's implementation. In the case of chrome, currently they return null when the attribute doesn't exist. This is observed in Cypress 6 (tested on both 6.4.0 & 6.9.1)

This is only a problem when Cypress is controlling chrome. Haven't tested other browsers / electron. 

### Test code to reproduce

https://github.com/endercrest/cypress-getattribute

Steps:
1. Install dependencies (`yarn`)
2. Start the server (`yarn start`)
3. Start cypress

Defaults to Cypress 8.0.0, which is broken. If ran on cypress 6.9.1 it works as expected.

https://user-images.githubusercontent.com/2616075/127408970-a883d194-3d37-45a6-83e2-53157356bdd1.mp4

https://user-images.githubusercontent.com/2616075/127409066-a4585cd4-0368-41ae-8388-07ef212777d4.mp4

### Cypress Version

8.0.0

### Other

Chrome: Version 92.0.4515.107 (Official Build) (x86_64)

**Comment by sainthkh** [comment]
It happens when the argument for `getAttribute` is `target`. This behavior is introduced with #16394 to fix #1244.
