### ISSUE TITLE
Timed out after waiting 60000ms for your remote page to load.

### ISSUE THREAD

**Issue by 18804601171** [cypress-io/cypress#17522]
### Current behavior

using visit function show error Timed out after waiting 60000ms for your remote page to load.
![image](https://user-images.githubusercontent.com/34762346/127493901-c683d81d-cce7-41e5-8d0e-68b1642869d6.png)

### Test code to reproduce

using visit function show error Timed out after waiting 60000ms for your remote page to load.

### Cypress Version

8.0.0

**Comment by vyvanand** [comment]
I too facing same issue. Any work around helped you or can someone suggest the fix?
