### ISSUE TITLE
Test runner should run first test matching filter when press {enter}

### ISSUE THREAD

**Issue by JohnnyFun** [cypress-io/cypress#17530]
### What would you like?

When I search in the test runner for a spec, I either have to move my arm waaaay over to my mouse, move it, then click it's button. Would be cool to just press enter, particularly when only one spec matches my filter.

![image](https://user-images.githubusercontent.com/8106379/127562902-fcb2500c-f683-464f-a0b4-b14eba8652da.png)

**Comment by jennifer-shehane** [comment]
We do have keyboard support so you could hit `tab` to select the spec and hit `enter` to run it, but you would have to cycle through a few other links first.

**Comment by JohnnyFun** [comment]
Yeah, it's like 3 or 4 tabs. Not a huge deal, I often just search for 1 spec that failed in ci and run it, so if it'd be quick cool, otherwise, not the end of the world.

**Comment by jennifer-shehane** [comment]
Since this hasn’t had a lot of interest, and we’ve rebuilt our Test Runner since this was opened, we’ll close this issue.
