### ISSUE TITLE
Client Certificate feature is not working

### ISSUE THREAD

**Issue by srinireddygithub** [cypress-io/cypress#17543]
### Current behavior

We added the client certificate in cypress.json as mentioned in the documentation (https://docs.cypress.io/guides/references/client-certificates#Syntax). Cypress doesn't seem to  be picking up certificates. We get exact same behavior without client certificates added inside cypress.json

### Desired behavior

It should at least try to use certificates specified in the cypress.json. 

### Test code to reproduce

Unable to share code due to company's policy

### Cypress Version

8.0.0

**Comment by jennifer-shehane** [comment]
Could you share your cypress.json file (removing sensitive information)?

**Comment by srinireddygithub** [comment]
**@jennifer-shehane  please see the content of the **cypress**.json file**

{
    "baseUrl": "https://####/###/pkmslogin.form",
    "env": {
        "overrideVariable": "cypress.json",
        "TAGS":"@wip"
    },
    "defaultCommandTimeout": 10000,
    "video": true,
    "screenshotOnRunFailure": true,
    "screenshotsFolder": "cypress/screenshots",
    "videosFolder": "cypress/videos",
    "trashAssetsBeforeRuns": true,
    "downloadsFolder": "cypress/downloads",
    "ignoreTestFiles": "*.md",
    "chromeWebSecurity": false,
    "testFiles": [ "**/*.feature", "**/*.spec.ts" ],
    "supportFile": "cypress/support/commands.js",
    "clientCertificates": [
        {
            "url": "https://####/###/pkmslogin.form",
            "ca": [],
            "certs": [
                {
                    "pfx": "softcerts/flcDIU12.pfx",
                    "passphrase": "softcerts/pfx-passphrase.txt"
                }
            ]
        }
    ]
}

**Comment by srinireddygithub** [comment]
> Could you share your cypress.json file (removing sensitive information)?

@jennifer-shehane please see the content of the cypress.json file

{
"baseUrl": "https://####/###/pkmslogin.form",
"env": {
"overrideVariable": "cypress.json",
"TAGS":"@wip"
},
"defaultCommandTimeout": 10000,
"video": true,
"screenshotOnRunFailure": true,
"screenshotsFolder": "cypress/screenshots",
"videosFolder": "cypress/videos",
"trashAssetsBeforeRuns": true,
"downloadsFolder": "cypress/downloads",
"ignoreTestFiles": ".md",
"chromeWebSecurity": false,
"testFiles": [ "**/.feature", "**/*.spec.ts" ],
"supportFile": "cypress/support/commands.js",
"clientCertificates": [
{
"url": "https://####/###/pkmslogin.form",
"ca": [],
"certs": [
{
"pfx": "softcerts/flcDIU12.pfx",
"passphrase": "softcerts/pfx-passphrase.txt"
}
]
}
]
}

**Comment by rkrisztian** [comment]
This may not help, but have you tried:

* Setting `DEBUG=cypress:*` or `DEBUG=cypress:server:record:ci-info` for finding out the cause?
* Setting `"url": "https://####/###/**",` just in case you get a redirection or the server needs it for every request.

**Comment by LucaPaganin** [comment]
Any news on this issue? I am facing the same problem at the moment, and having an answer would be very Bice.

**Comment by ghost** [comment]
I previously couldn't get it to work with ```https://localhost:3000/**``` and kept getting a 403, but setting the url to ```https://**urlneedingcert**``` worked for me.

**Comment by srinireddygithub** [comment]
@walleyyang- glad it worked for you! 
Wondering, if you could share content of cypress.config.ts which is working for you?

**Comment by ghost** [comment]
> @walleyyang- glad it worked for you! Wondering, if you could share content of cypress.config.ts which is working for you?

I didn't realize that you were on Cypress 8. I'm not sure about Cypress 8, but I was on 10. The below is what I had. The passphrase.txt is simply the password for the certs. My baseUrl is localhost.

```
clientCertificates: [
  {
    url: 'https://**urlneedingcert**',
    ca: [],
    certs: [
      {
        pfx: 'cypress/certs/cert.p12',
        passphrase: 'cypress/certs/passphrase.txt'
      }
    ]
  }
]
```

**Comment by srinireddygithub** [comment]
Thank you. We are using Cypress 12.5.1.

**Comment by srinireddygithub** [comment]
@walleyyang- it worked me! thank you so much :-) 👍 

A quick question- 
Solution works with single certificate, but my requirements is to use multiple certificates. Wondering, if you tried with more than one Certs?

**Comment by ghost** [comment]
> @walleyyang- it worked me! thank you so much :-) 👍
> 
> A quick question- Solution works with single certificate, but my requirements is to use multiple certificates. Wondering, if you tried with more than one Certs?

I think I tried at one point, but couldn't get different certs to work so I gave up on it since I didn't really need it. I'm not 100% sure, but I think you might only be able to have one cert to one URL. The certs I tried gave users access to different areas of the website and it needed the same URL.

**Comment by srinireddygithub** [comment]
sounds good

**Comment by srinireddygithub** [comment]
This issue can be closed as the solution works as expected!
