### ISSUE TITLE
Add a configuration option to allow watching for fixture changes

### ISSUE THREAD

**Issue by knorrium** [cypress-io/cypress#17552]
### What would you like?

The [docs](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#What-isn-t-watched) state that `cypress/fixtures` is not watched for file changes, so I would like to have a way to configure the test runner to disable this behavior and watch for file changes.

### Why is this needed?

When iterating on tests that use fixtures, it would be very useful to watch for file changes not only to the test files, but to the fixtures as well.

With the current behavior, one has to manually rerun the test on the test runner after updating a fixture - using `it.only()` to only run one test helps speed up the process, but still requires a manual step.

**Comment by jennifer-shehane** [comment]
Since this request has not gotten a lot of interest over the years, we’ll close this issue.
