### ISSUE TITLE
Allow Cypress test scheduling by previous test execution times

### ISSUE THREAD

**Issue by SVaeth** [cypress-io/cypress#17566]
### What would you like?

In optimizing Jest tests, the Jest team added features lists here:

https://jestjs.io/blog/2016/03/11/javascript-unit-testing-performance

The first feature, optimal scheduling of test run, leverages the jest cache to see the execution times of the previous test run of a given suite/file and use those times to predict which tests will take the longest to execute and schedule them to be run first. 

I would like to do the same with our cypress tests in our CI/CD pipeline.

### Why is this needed?

Currently our scheduling algorithm is naive and hashes the cypress tests to a CI node in the order is received. I would like to write an algorithm that sorts these tests by their previous execution order to leverage the same optimizations we got from jest testing, but no sources I have found show a way to do this. I would have to have access to the previous running test data, which I am note sure if cypress stores this in its cache. 

It is also safe to assume Cypress Dashboard is not going to be accepted by our platform and security team.

Two solutions I could think of: 

1. Some means to extract this data from the cache, like maybe a json file with the data readily available to be read.
```
{
     test1.spec.js: 5678ms,
     test2.spec.js: 1234ms
} 
```

2. Automatically sort it. Jest automatically sorts tests by its jest cache. The only caveat is there would then need to be a way to section the tests among CI nodes without running the tests. This could be something like a dry run command for Cypres
```
cypress dry-run OR cypress run --dry-run
test2.spec.js
test1.spec.js
```

**Comment by jennifer-shehane** [comment]
As you stated, this is offered through our Cypress Dashboard currently. You would have to somehow store the previous runtimes and write an algorithm to sort it by previous runtimes. You might be able to use our Module API to get the run data of each run and use that. https://on.cypress.io/module-api

Closing since this is a feature that already exists in Cypress.

**Comment by SVaeth** [comment]
Also as I stated, Cypress Dashboard should be assumed to not be an option. Scheduling should be available in base Cypress. Not every organization is going to have permissions to use paas not previously approved for use, nor the willingness to pay for it.

**Comment by jennifer-shehane** [comment]
Automatic parallelization is a service that we offer that helps fund all of the features we offer on our open source product. 

On prem solutions are something we're exploring for the Dashboard. We'd also be open to talk to your security team on any blockers for using the current Dashboard if you'd like to email us at support@cypress.io we can work directly with you.

**Comment by SVaeth** [comment]
Jest, JUnit, TestNG, and more tools do not rely on blackboxing this feature without a paid service, but I don't even need automatic parallelization. I'm fine writing my own runner. 

Cypress should at least have a way to get runtime data to write your own scheduling algorithm.
