### ISSUE TITLE
Firefox `beforeinput` event support

### ISSUE THREAD

**Issue by btjones** [cypress-io/cypress#17583]
### What would you like?

I would love to get `beforeinput` support in Firefox now that Firefox supports it.

### Why is this needed?

This would be beneficial to anyone relying on the Firefox `beforeinput` event - otherwise that functionality cannot be tested with Cypress. In my case I am building a text editor which relies heavily on this event.

### Other

`beforeinput` support was added to Cypress last year for Chromium browsers. [Firefox has also added support for the `beforeinput` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event) which was added in version 87.

In [this PR](https://github.com/cypress-io/cypress/pull/8411/files#diff-712f21b6f16b578d5d31b64e7ae7adfa1074e97cfe015559f348b105802eb684R614) where `beforeinput` support was added there is a check specifically for the Chromium family of browsers. It would be great if Cypress triggered this event for Firefox (87+) just as it does for Chromium browsers.

**Comment by btjones** [comment]
Looks like this is starting to get buried a few pages deep - wondering if anyone from the cypress team could comment on if this either already is or could be added to the roadmap? Thanks!

**Comment by JessicaSachs** [comment]
It's not on the roadmap right now and may take us a little bit to get to. Our Firefox userbase is actually quite small, so in order to get the fix in soon, you should consider submitting a PR.

**Comment by btjones** [comment]
@JessicaSachs here's a PR (plus documentation PR):

- https://github.com/cypress-io/cypress/pull/17820
- https://github.com/cypress-io/cypress-documentation/pull/4070

**Comment by btjones** [comment]
@JessicaSachs Thanks for getting the proper people assigned to review my PR (which has been merged) 🎉  I've converted the documentation PR from a draft to `ready for review` but noticed there are no automatic assignees. Is there anything else I need to do to get a review on that? Thanks!
