### ISSUE TITLE
Race condition with cy.request() / localstorage?

### ISSUE THREAD

**Issue by rrauenza** [cypress-io/cypress#17585]
### Current behavior

I'm using 8.1.0, with typescript.

I have an issue where I'm trying to use cy.request() to login before running tests.  Whether the cy.request() is in beforeEach() or the it() body, I seem to get a race condition occasionally that it continues before the localstorage has the jwt.  I'm only seeing this so far with the second it().  The end result is my angular app thinks I'm not logged in when it does the first visit() ... but only sometimes.

```
Cypress.Commands.add(
  "login",
  (username: string = 'e2e', password: string = 'e2e') => {
    cy.request('POST', 'api/rest/accounts/login/', {'username': username, 'password': password}).then((response) => {
      expect(response.status).to.eq(200)
      const jwt = JSON.stringify(response.body.jwt)
      window.localStorage.setItem('jwt', jwt)
      expect(window.localStorage.getItem('jwt')).to.eq(jwt)
    })
  }
)
```

![image](https://user-images.githubusercontent.com/1376251/128100650-6e246568-184e-4993-bfa3-e7e0ce3ce4a0.png)

That GET that is red/canceled probably shouldn't even be there.  I wonder if it's leftover from the previous it() test as an outstanding GET?   We haven't even visit()ed the angular app yet in this it().    I see in the snapshots, the app already rendered in the second it() ... from the previous it().  And its the page the previous it() finished on.

### Desired behavior

Have a fresh state between it()'s

### Test code to reproduce

see above

### Cypress Version

8.1.0

**Comment by rrauenza** [comment]
Added a visit to chrome://about to see if I could clear the app... but... it seems clear that somehow the angular app is still running and has pending GET's:

![image](https://user-images.githubusercontent.com/1376251/128101440-f3238b1d-34b4-4c3d-953a-2117fcc162b7.png)

**Comment by rrauenza** [comment]
Looking through other bugs about pending http requests... I wonder if the angular xhr callback is still in place between it()'s , which then causes the code to run that redirects me to SSO when the jwt isn't set yet.  

If I could find a way to wait until all pending xhr requests resolve before moving to the next test that may solve it.  It seems like intercept() and wait() only wait for a single request.

**Comment by bahmutov** [comment]
Can you try visiting about blank pages at the start of each test? This should cancel all pending network requests https://glebbahmutov.com/blog/visit-blank-page-between-tests/

**Comment by rrauenza** [comment]
Ah!  I did try chrome://about.  I can try the other as well.

I am trying window.stop() in before and after currently.

Also, thinking more about it... it wouldn't be the cancelled XHR's... it may be ones that aren't cancelled yet in between it()'s and trigger a redirect to the SSO page.

So far I haven't reproduced it when doing:

 ```
beforeEach(() => {
    window.stop()
    cy.log('beforeEach')
    cy.login()
    //cy.intercept('/**').as('pending_requests')
  })
  
  afterEach(() => {
    //cy.wait('@pending_requests')
    window.stop()
  })



```

**Comment by rrauenza** [comment]
@bahmutov Added this to support/index.ts, as you suggested in your blog...

```
beforeEach(() => {
    cy.log("Going to about:blank")
    cy.window().then((win) => {
      win.location.href = 'about:blank'
    })
  })

afterEach(() => {
    cy.log("Going to about:blank")
    cy.window().then((win) => {
      win.location.href = 'about:blank'
    })
  })
```

Haven't reproduced it yet.  

Should this be a standard thing that happens in cypress between tests?  (window.stop() might also be equivalent.  )

**Comment by bahmutov** [comment]
I think beforeEach is enough and doing it by default kind of breaks all tests that only visit the page once so they don’t need the hard reset. I’m not sure about window.stop remember looking at it a long time ago and it seemed insufficient but don’t have any writing on it

**Comment by rrauenza** [comment]
FYI, I found doing it in afterEach() to be really annoying ... because it makes iterative development harder.  It seems to be enough to only do it in beforeEach(), though!

**Comment by jennifer-shehane** [comment]
You can turn on `experimentalSessionSupport` and it will visit `about:blank` in between each test as part of that feature. May resolve some of this.

**Comment by emilyrohrbough** [comment]
In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation) to prevent cases like this. There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

This will prevent DOM and browser state bleed over between tests.

Closing this issue as done and tagging for the v12.0.0 release.
