### ISSUE TITLE
Support Node 14

### ISSUE THREAD

**Issue by david-shortman** [cypress-io/cypress#17599]
> We use the same Node version as Electron. So once Electron upgrades, we will upgrade too.

_Originally posted by @bahmutov in https://github.com/cypress-io/cypress/discussions/14919#discussioncomment-338192_

As of [Electron 12](https://github.com/electron/electron/releases/tag/v12.0.0), Node 14 is included.

Cypress should migrate to supporting Node 14.

**Comment by jennifer-shehane** [comment]
We support Node 14. The current Node version 14.15.1. You can see the current node version in the Test Runner's Settings tab with instructions on how to overwrite it with your system Node version.

Please make sure you update to the latest version of Cypress. 

<img width="923" alt="Screen Shot 2021-08-05 at 9 01 29 AM" src="https://user-images.githubusercontent.com/1271364/128363224-420f3f2f-039d-4548-a664-5281369fac89.png">
