### ISSUE TITLE
Blank Video Recording on Cypress: 4.12.1 and Browser: Chrome 92

### ISSUE THREAD

**Issue by CypressDashboard** [cypress-io/cypress#17590]
### Current behavior

Recorded video is returned blank on Cypress: 4.12.1 and Browser: Chrome 92 ( headless or headed).
But I could able to see the complete video, when I run the same scripts over default Cypress: 4.12.1  and Browser: Electron 80 (headless or headed)

### Desired behavior

Video should record normally.

![Recorded video is returned blank in Chrome 92](https://user-images.githubusercontent.com/68445518/128137744-ff6327df-98f4-4146-b911-a4bb2cdfc527.png)

### Test code to reproduce

Blank Video Recording on Cypress: 4.12.1 and Browser: Chrome 92.
Attached the screenshot for reference.

### Cypress Version

4.12.1

**Comment by jennifer-shehane** [comment]
The 4.12.1 version of Cypress is a year old. We suggest that you update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!
