### ISSUE TITLE
Can't log in to app under test 

### ISSUE THREAD

**Issue by boriskogan81** [cypress-io/cypress#1759]
### Current behavior: 

My app's login component will not let me log in when opened with the Cypress browser. I can log in via the normal Chrome browser. Copypasting the username and password which work in the normal browser to the Cypress browser ralso esults in a login error. 

### Desired behavior:

Valid credentials should let me log in.

### Steps to reproduce:

Cypress test:
```js
describe('Logging in', () => {
	it('Logs in as admin', () => {
		cy.visit('/')
            .get('input[type="text"]')
            .type('Admin')
		    .get('input[type="password"]')
            .type('Pass1234')
            .get('button').click()
		    .location().should((loc) => {
			expect(loc.pathname).to.eq('/dashboard-main/dashboard');
		})
	})
})
```
Login component (Vue):
```html
<template>
    <div class="d-flex justify-content-center">
        <div v-if="isAuthenticated" class="text-center">
            <div>Hello, authenticated user!</div>
            <button v-on:click="logout()" class="button is-primary">Logout</button>
        </div>
        <div v-else>
            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">Username</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control">
                            <input v-model="username" class="input" type="text"
                                   placeholder="Your username">
                        </div>
                    </div>
                </div>
            </div>
            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">Password</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control">
                            <input v-model="password" class="input" type="password"
                                   placeholder="Your password">
                        </div>
                    </div>
                </div>
            </div>
            <div class="field is-horizontal">
                <div class="field-label">
                    <!-- Left empty for spacing -->
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control text-center">
                            <button v-on:click="login()" class="button is-primary">
                                Login
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

```
### Versions  
Cypress: ^2.1.0
OS: Windows 10
Browser: Chrome  66.0.3359.139

**Comment by jameskaupert** [comment]
We started having a similar problem last week with Chrome 66 (believe it was working with earlier versions).  Cannot log in using the UI, or navigate to other pages if we log in programatically as suggested in the docs then try to take actions.  Have not had a chance to write up our problem in its own issue yet.

For us, it appears to be happening because of the following console error:
`Blocked current origin from receiving cross-site document at https://my-api-site.ourdomain.com/api/v1/our/route with MIME type application/json.` in `cypress_runner.js:66589`.

Not sure why Cypress is blocking this call, given that the UI is trying to hit this route (we are not directly navigating to that route).  We have `"chromeWebSecurity": false` set in the `cypress.json` file as recommended in the docs as well.

Swapping to Electron 59 has allowed us to continue working with the UI for now.

Not sure if you're seeing the same type of error (we're using Angular, not Vue), but hopefully this gives you another route to continue for now.

**Comment by boriskogan81** [comment]
Thanks. For us, it doesn't work with Electron 59 either.

I will set up the cypress.json as recommended tomorrow.

It does feel like a CORS problem.

Sincerely,

Baruch

**Comment by boriskogan81** [comment]
Unfortunately, in projects created using Vue CLI 3, there is no cypress.json file. Just another one of those configurations which have been helpfully abstracted away...Anyone know how to configure in this environment?

**Comment by boriskogan81** [comment]
OK, got it, there's actually a cypress.json in root, added "chromeWebSecurity": false, same problem remains.

**Comment by ValerieThoma** [comment]
@boriskogan81 can you please add more information about how you believe this is a bug? 
Are you receiving an error from Cypress?

**Comment by ValerieThoma** [comment]
@boriskogan81 You have not provided any information that suggests this is a bug. There are countless reasons why your login is failing. Is your server running? 
What do you see in the test runner? In the console? 
Do you have a screen shot?

**Comment by boriskogan81** [comment]
My server is running. 

Here's what I see:

![image](https://user-images.githubusercontent.com/10279403/40489414-b79719dc-5f71-11e8-89ff-b0c0cc429353.png)

**Comment by ValerieThoma** [comment]
Check your assertion: https://docs.cypress.io/api/commands/location.html#Requirements

**Comment by boriskogan81** [comment]
A successful login should be redirected to /dashboard-main/dashboard.

This is my code:

```
describe('Logging in', () => {
	it('Logs in as admin', () => {
		cy.visit('/')
            .get('input[type="text"]')
            .type('Admin')
		    .get('input[type="password"]')
            .type('Pass1234')
            .get('button').click()
		    .location().should((loc) => {
			expect(loc.pathname).to.eq('/dashboard-main/dashboard');
		})
	})
});

```

**Comment by ValerieThoma** [comment]
@boriskogan81 
>cy.location() requires being chained off of cy.

**Comment by boriskogan81** [comment]
Isn't it currently?

Sincerely,

Baruch

**Comment by ValerieThoma** [comment]
**It is not.** 
You have `location` chained off of `visit`. 

Please try `cy.location()`

**Comment by boriskogan81** [comment]
OK, tried cy.location().

Same problem-I'm still getting a 404 error.

This looks like a CORS issue.

**Comment by Bkucera** [comment]
@boriskogan81 you should open up the devtools and see if there is an error in the console. If it's a CORS issue it'll say there.

**Comment by boriskogan81** [comment]
This is what I see there. 

```
:8080/auth/login Failed to load resource: the server responded with a status of 404 (Not Found)
app.service.js:24 Error: Request failed with status code 404
    at LYNF.t.exports (http://localhost:8082/js/vendors~app.975e96e7.js:21:12180)
    at Rn+g.t.exports (http://localhost:8082/js/vendors~app.975e96e7.js:21:15880)
    at XMLHttpRequest.h.(anonymous function) (http://localhost:8082/js/vendors~app.975e96e7.js:31:30144)
```

**Comment by Bkucera** [comment]
@boriskogan81 If you think it will work on an earlier version of chrome, can you try that? It would help to narrow down the problem...however if it is breaking in electron, its most likely not due to upgrading to chrome 66...

**Comment by boriskogan81** [comment]
Sure. How do I configure the chrome version?

On May 24, 2018 17:41, "Ben Kucera" <notifications@github.com> wrote:

@boriskogan81 <https://github.com/boriskogan81> If you think it will work
on an earlier version of chrome, can you try that? It would help to narrow
down the problem...however if it is breaking in electron, its most likely
not due to upgrading to chrome 66...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cypress-io/cypress/issues/1759#issuecomment-391740037>,
or mute the thread

**Comment by Bkucera** [comment]
@boriskogan81 you can download it here, then if you use Cypress open, it should be in the browser picker https://www.chromium.org/Home

**Comment by boriskogan81** [comment]
I'm not seeing options to download older versions at chromium.org.

**Comment by jennifer-shehane** [comment]
@boriskogan81 Yeah, it's not the easiest process to be honest. You can find instructions [here](https://www.chromium.org/getting-involved/download-chromium) under *Downloading old builds of Chrome / Chromium**

**Comment by modulitos** [comment]
I am encountering a similar error, where I am able to login in Chromium, but I am unable to login through the Cypress browser. I am filling out my login form using the same Cypress API that @boriskogan81 described above.

I can confirm that my server endpoint is returning a 200 and response with the login information, but my app is getting the following error:

>Error: Request has been terminated
>Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
>    at Request.crossDomainError (VM781 client.js:621)
>    at XMLHttpRequest.xhr.onreadystatechange (VM781 client.js:703)

It seems like the Cypress browser is cancelling the request for some reason. Any suggestions?

Also, I am noticing the the Cypress browser is not sending an OPTIONS preflight request, while my Chromium browser *is* sending the OPTIONS preflight. Perhaps this is related?

I have also added `"chromeWebSecurity": false` to my `cypress.json`, but no luck.

**Comment by boriskogan81** [comment]
I have figured this out. Debug mode was causing timeouts, which killed the login process. Works fine in normal mode. Want me to close the issue?

**Comment by modulitos** [comment]
@boriskogan81 Wow, thank you so much! I prefixed a `DEBUG=cypress:* ` to my `cypress open` command, and the login process works! If you think this is the proper solution, feel free to close the issue.

**Comment by Bkucera** [comment]
@boriskogan81  @modulitos let me get this straight, what caused the issue from one person, solved it from another?

**Comment by modulitos** [comment]
@Bkucera I'm not sure what @boriskogan81 did to fix his issue, but I can attest that prefixing `DEBUG=cypress:*` to my `cypress open` command avoids the CORS error I posted above.

**Comment by jennifer-shehane** [comment]
If you are experiencing the 'cross origin' error, could you try to update to version [3.1.2](https://on.cypress.io/changelog#3-1-2) as we just fixed some cross origin error issues. 

Otherwise we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this - app code + test code?

**Comment by lawphotog** [comment]
Hi, I am new to cypress and just started trying it today. I am having similar problem with logging in with cypress to one of the sites. The site is written in Asp.net Mvc. The error I am getting with cypress is 

`The required anti-forgery cookie "__RequestVerificationToken" is not present.`

I know this is server side error but the site can be logged in using manually clicking the login button even within cypress iframe. But cy.get('.loginbutton').click() is always throwing this problem. So Cypress is definitely doing something differently.

Seems any form submits in MVC will fail using cypress as there will be anti-forgery cookie check. Please let me know if there's a way around this problem.

**Comment by ushakp** [comment]
is this Issue resolved , I am facing same issue

**Comment by jennifer-shehane** [comment]
No one has provided a reproducible example that can be run locally, so no, this issue is not resolved. Can anyone provide a way to reproduce this?

**Comment by jameskaupert** [comment]
Sorry I never followed up on this.  I do not recall how we got around this, but we are not seeing it on our end anymore.  We are on 3.1.2 and using Chrome 67 in our CI builds (using the docker image from the cypress docker repo) and Chrome 71/72 for local `cypress open` work.

**Comment by jennifer-shehane** [comment]
@ushakp What version of Cypress are you using? Can you update to the latest Cypress version and see if this is resolved please?

**Comment by syagawa** [comment]
I also faced the same problem, 
My problem was solved by adding `"chromeWebSecurity": false` to cypress.json.

**Comment by mohammedroni4** [comment]
Hi, @jennifer-shehane 
So I'm new to cypress where I'm facing issue and not able to move on, the problem that I'm currently facing is, I started my localhost, and it is not somehow showing in the cypress site, I'm using localhost:3000, but it seems to be saying to use cy.request(). which I did and it still not showing the UI or the content of them html for some reason and it is not giving me any error either.


<img width="1766" alt="Cypress" src="https://user-images.githubusercontent.com/13221629/57879401-3f935080-77d1-11e9-8dee-b2dea71885eb.png">

**Comment by ewelinasobora** [comment]
I faced the same issue as boriskogan81.
I prefixed DEBUG=cypress:* to my cypress open, I also added "chromeWebSecurity": false to cypress.json - nothing fixed this issue. Is it going to be fixed?

**Comment by mohammedroni4** [comment]
Not sure, I do not know whats going on, it seems to be priority for most of us I think now.

**Comment by jennifer-shehane** [comment]
@mohammedroni4 	In order to preview the website in the righthand side, you need to use `cy.visit()`. Please print the error that is displayed here if you have one.

**Comment by jennifer-shehane** [comment]
Closing the original opener's issue as resolved. Please open a new issue if you are experiencing something similar to this issue.
