### ISSUE TITLE
[sessions] When using an active session with cy.session waiting for an array of aliased XHR's do not resolve

### ISSUE THREAD

**Issue by joshpzero** [cypress-io/cypress#17607]
### Current behavior

When using cy.session to create a session and login using this session, it appears that XHR requests defined and waited on seem to hang, with no error in the Cypress test runner. This seems to happen in an array of aliases to wait

`cy.wait('['@alias1',  '@alias2', '@alias3']`

### Desired behavior

Cypress should wait for all aliases defined in the array.

### Test code to reproduce

```js
const login = (name, password) => {
  cy.session(
    [name, password],
    () => {
      cy.visit('/')
      cy.get('#signin-username').type(name)
      cy.get('#signin-password').type(password)
      cy.get('#signin-submit').click()
    })
}
```

```js   
login(Cypress.env('testUserEmail'), Cypress.env('testUserPassword'))
    cy.visit('/')
    cy.wait(['@alias1', '@alias2', '@alias3']);
```

### Cypress Version

8.2.0

**Comment by jennifer-shehane** [comment]
- Where are these aliases defined?
- You tried this without sessions and the issue is not reproducible? Because we also made changes to XHRs in the 8.2 release.

**Comment by amirrustam** [comment]
@joshpzero where in your test are you defining your aliases? Can you share more code for the sake of more context?

**Comment by nahuelnct** [comment]
This happened to me when running headless

```javascript
Cypress.Commands.add('loginAs', (mail, password) => {
  cy.session('defaultUser', () => {
    cy.visit(Cypress.env('base_url'));
    cy.get('[name="email"]')
      .type(mail)
      .get('[name="password"]')
      .type(password)
      .get('[data-cy=login-button]')
      .click()
      .url().should('contain', '/oauth/consent');   
  });
});
```
After logging it should wait for the URL assertion but it gets stuck in the login form. This problem does not happen in headed Cypress.

Error:
```
  1) login:
     AssertionError: Timed out retrying after 4000ms: expected 'http://localhost:8001/login' to include '/oauth/consent'
      at Object.eval [as setup] (http://abowire.localhost:8001/__cypress/tests?p=cypress/support/index.js:131:14)

**Comment by joshpzero** [comment]
> * Where are these aliases defined?
> * You tried this without sessions and the issue is not reproducible? Because we also made changes to XHRs in the 8.2 release.

They're defined in the `beforeEach` block. However I did try to define these in any way possible (inside the test) in an attempt to get it to work. The only thing that made the test pass was calling the cy.wait('@alias') sequentially, not in an array. Yes the test passed previously without `cy.session()`

**Comment by wlsf82** [comment]
I think I'm facing a similar (or even the same issue).

For more details, see the comments from [this thread](https://github.com/brmodeloweb/brmodelo-app/pull/254#issuecomment-970737614) on.

**Comment by wlsf82** [comment]
> > * Where are these aliases defined?
> > * You tried this without sessions and the issue is not reproducible? Because we also made changes to XHRs in the 8.2 release.
> 
> They're defined in the `beforeEach` block. However I did try to define these in any way possible (inside the test) in an attempt to get it to work. The only thing that made the test pass using `cy.session()` was calling the`cy.wait('@alias'`) sequentially, not in an array. Yes the test passed previously without `cy.session()`

I think I'm facing a similar (or even the same issue).

For more details, see the comments from [this thread](https://github.com/brmodeloweb/brmodelo-app/pull/254#issuecomment-970737614) on.

**Comment by chrisbreiding** [comment]
Unfortunately there doesn't seem to be enough information to reproduce this issue. This does not mean that the issue is not happening - it just means that we do not have a path to move forward.

If you or anyone is still experiencing this issue, please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [short, self-contained, correct Example](http://sscce.org/).
