### ISSUE TITLE
Can't type the literal `}` using `.type`

### ISSUE THREAD

**Issue by wawhal** [cypress-io/cypress#1760]
I am trying to type a JSON string.

### Current behavior: 

![image](https://github.com/wawhal/test-repo/raw/master/cypress-error-closing-curly.png)

### Desired behavior:

There should be some way to print the `{` literal.
I am using a workaround: `.type('{{} \"key\": \"value\"{{}}{leftarrow}{backspace}`

### Versions  

Cypress: 2.1.0
OS: Linux x86_64 (Ubuntu 16.04)
Browser: Google Chrome 62.0.3202.89

**Comment by ValerieThoma** [comment]
Can you try this? 
```js
.type('{{}key:value}')
```

**Comment by Kryshtopenko** [comment]
{} works find. Prosti gospodi...
