### ISSUE TITLE
npm ERR! punycode not accessible from cypress:url

### ISSUE THREAD

**Issue by aomaryus** [cypress-io/cypress#17604]
### Current behavior

Using cypress with cucumber. This error is showing in Jenkins and bloks build.
+ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! punycode not accessible from cypress:url

### Desired behavior

This was working before cucumber. 

### Test code to reproduce

This is only happening in CICD. Works fine on local both open and run modes.

### Cypress Version

8.1.0

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example?

What plugin are you using? I'd suggest opening an issue with the plugin as it may be an issue with the plugin as we haven't had this issue reported before. 

Can you provide the npm debug log?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
