### ISSUE TITLE
Cypress warns that chromeWebSecurity is set to "false" but it isn't

### ISSUE THREAD

**Issue by cars10** [cypress-io/cypress#17614]
### Current behavior

When selecting firefox to run the test there is a warning that says i have disabled `chromeWebSecurity`. This is not true, the settings clearly show that it is enabled. It is not even included in the actual config file or my run command.

![image](https://user-images.githubusercontent.com/4118628/128316238-ae4f1050-420c-4fb7-ae1c-d2a2bc7d732b.png)

### Desired behavior

Cypress should not warn me because the setting is not disabled.

### Test code to reproduce

This is reproduceable in the example `cypress-test-tiny` example repo. Simply add cypress and run `yarn cypress:open`.

### Cypress Version

8.2.0

**Comment by jennifer-shehane** [comment]
I am able to reproduce this. Looks like this is showing the tooltip regardless of the value set. This was introduced in 8.0.0. I'm guessing maybe it was introduced in https://github.com/cypress-io/cypress/pull/17355/files
