### ISSUE TITLE
Cypress tests are not executing on chrome 92

### ISSUE THREAD

**Issue by vishnuprabhu-95** [cypress-io/cypress#17625]
### Current behavior

Tests are running fine in Chrome 91 and below version. After chrome upgrade, Its not running. Below screenshot error is getting displayed.

![chrome_cxvifSSV4v](https://user-images.githubusercontent.com/63766633/128412576-b323763b-cab2-4dab-9fb1-f9b7100d762f.png)

### Desired behavior

Tests should be running in Chrome 92 too. Running Fine in all Electron version.

### Test code to reproduce

Chrome Version 91 and I have used latest cypress version too.

### Cypress Version

7.2.0 >

**Comment by dapinto8** [comment]
I had same issue. It was because I was importing a file that imports mongodb in my spec, mongodb@4.1 use SAB. Check if any package is using SAB and try to avoid importing it on client side.

**Comment by vishnuprabhu-95** [comment]
May I know the easy way to find SAB in packages please, @dapinto8 .

![image](https://user-images.githubusercontent.com/63766633/128459309-be771d68-31ef-4dfc-9c6c-432682a865d1.png)

Packages used :
Part 1:
![image](https://user-images.githubusercontent.com/63766633/128459419-f22db305-405e-4287-af9a-8dc73c0b6987.png)

Part 2:
![image](https://user-images.githubusercontent.com/63766633/128459435-0a37fbfb-83b5-4ba7-9e81-2dc32d5b1697.png)

**Comment by csvan** [comment]
You should not be importing jsdom in your client code, it's not meant to run there. Check your imports.

**Comment by dapinto8** [comment]
Check if any or your specs are importing jsdom or your client code like @csvan says

**Comment by vishnuprabhu-95** [comment]
You guys are awesome!
I am using JsDom package for automating email scenarios for the application. 
Using gmail-tester package mentioned below, I read the email scenarios and fetch html email body details.

Package : https://github.com/levz0r/gmail-tester

In-order to fetch OTP and body of the html mail, I am using JsDOM. If I remove JsDOM, we can't run email scenario's guys.

Reference:
1. 
![image](https://user-images.githubusercontent.com/63766633/128526853-955a5872-923c-4c1d-8ce4-914f604ff19f.png)

2.
![image](https://user-images.githubusercontent.com/63766633/128526893-8a3948a6-7aaa-4230-a0ac-d17e7189a5f6.png)

3.
![image](https://user-images.githubusercontent.com/63766633/128527248-bdffd4a1-8dcf-4f77-921a-c409da2f9e7c.png)

 Please help with the same.
@csvan  @dapinto8

**Comment by csvan** [comment]
@vishnuprabhu-95 jsdom is meant to provide a DOM environment where none is available (e.g. when running tests outside the browser). In the browser, you have an actual DOM so jsdom is not even needed. You should be able to do whatever you are currently doing with the regular DOM.

**Comment by vishnuprabhu-95** [comment]
Thanks @csvan 
You did a wonder. Issue resolved. 
Replaced jsDOM package with domParser

Piece of code below:
![image](https://user-images.githubusercontent.com/63766633/128546382-3776baba-7ecb-4953-b76d-f097491b974f.png)

**Comment by csvan** [comment]
Great 😁
