### ISSUE TITLE
Real device in browser stack with Cypress Automation

### ISSUE THREAD

**Issue by sureshpralayakaveri** [cypress-io/cypress#17632]
### Current behavior

Currently we are working on Cypress Automation tool to automate the functional test cases in my project, we have a requirement to automate functional test cases using real device in browser stack. Kindly suggest can it be done using Cypress tool

### Desired behavior

not familiar with real device automation using cypress

### Test code to reproduce

not familiar with real device automation using cypress

### Cypress Version

8.2.0

**Comment by jennifer-shehane** [comment]
This cannot be done with Cypress currently.

**Comment by jennifer-shehane** [comment]
Since this request has not gotten a lot of interest over the years, we’ll close this issue.
