### ISSUE TITLE
Cannot specify port on intercept

### ISSUE THREAD

**Issue by jonoreilly** [cypress-io/cypress#17653]
### Current behavior

Hi there, I'm having an issue where if I specify the port on `cy.intercept` it won’t match the request.
This is what my code looks like:

```javascript
cy.intercept(
  { 
    method: 'POST', 
    pathname: '/api/my-work-list', 
    hostname: 'localhost', 
    port: 8100,
  }, { 
    body: 'Created successfully',
  }
).as('POST-createWorklist')
```
<img width="712" alt="Screenshot 2021-08-09 at 12 46 39" src="https://user-images.githubusercontent.com/29210740/128695376-4da35837-e2a1-45b4-a43e-617dc80b224a.png">

<img width="456" alt="Screenshot 2021-08-09 at 12 29 28" src="https://user-images.githubusercontent.com/29210740/128693209-74520b5b-7ba4-4895-8dfe-aae60f9f116e.png">

When I don’t specify the port it works correctly:
```javascript
cy.intercept(
  { 
    method: 'POST', 
    pathname: '/api/my-work-list', 
    hostname: 'localhost',
  }, { 
    body: 'Created successfully',
  }
).as('POST-createWorklist')
```

<img width="702" alt="Screenshot 2021-08-09 at 12 45 49" src="https://user-images.githubusercontent.com/29210740/128695318-39ce5863-7ec6-4a50-88d8-a3a1d3234dc6.png">

<img width="744" alt="Screenshot 2021-08-09 at 12 32 56" src="https://user-images.githubusercontent.com/29210740/128693768-33ff2f75-75c3-4dff-80c1-48aeef571926.png">

The expected behaviour is that it will only match the calls to the port if it is specified, as described in the [documentation](https://docs.cypress.io/api/commands/intercept#routeMatcher-RouteMatcher).
 
I'm using Cypress version `8.2.0`.

Thanks in advance.

### Desired behavior

The expected behaviour is that it will only match the calls to the port if it is specified, as described in the [documentation](https://docs.cypress.io/api/commands/intercept#routeMatcher-RouteMatcher).

### Test code to reproduce

```javascript
cy.intercept(
  { 
    method: 'POST', 
    pathname: '/api/my-work-list', 
    hostname: 'localhost', 
    port: 8100,
  }, { 
    body: 'Created successfully',
  }
).as('POST-createWorklist')
```

### Cypress Version

8.2.0

**Comment by bspot** [comment]
I'm also experiencing this. Matching on port appears to simply not work.

**Comment by mgaonach** [comment]
Having the same issue with cypress 13.8.0
