### ISSUE TITLE
Downloading cypress (both with npm/yarn install and direct CDN download) is very slow

### ISSUE THREAD

**Issue by RomanDavlyatshin** [cypress-io/cypress#17652]
### Current behavior

Download speed (both with npm install and direct CDN download) is around **50-60kbps**. The installation took hours to complete.
I am experiencing no issues with other packages/resources, my bandwidth is **80Mbps**.

I've posted in a [similar issue thread](https://github.com/cypress-io/cypress/issues/7251), but it's closed, so I'm re-creating the issue once again.
I am certainly not the only one affected by the issue, as there are 5 people reported since it was closed, 2 of them in the last two weeks.

### Cypress Version

7.2.0

### Package Manager

npm

### Operating system

Windows

**Comment by RomanDavlyatshin** [comment]
Quoting @jennifer-shehane [response](https://github.com/cypress-io/cypress/issues/7251#issuecomment-886752311)
> We believe this issue to be a problem localized to the network where Cypress is installed under and not an issue directly with Cypress.

Could you please elaborate on that point? Currently, I just feel stuck dead in the water, as "network where Cypress is installed" does not sound like a thing I can fix in any way 😢

**Comment by RomanDavlyatshin** [comment]
@bahmutov Sorry to bother you, but can you comment on that one please? 
It's a second thread on that kind of issue (just like the [this one](https://github.com/cypress-io/cypress/issues/7251)), and there is no real feedback as well 😞 

There were [some responses](https://github.com/cypress-io/cypress/issues/7251#issuecomment-886752311) from the Cypress team,  but it's kinda vague, and no real solution is proposed.

The problem is here, and it certainly affects a number of users that **do not experience issues with any packages**, other than Cypress.

**Comment by bahmutov** [comment]
I’m sorry I cannot help anyone debug this, for me the downloads are always fast and since I no longer work at Cypress.io I cannot debug other user’s problems without a consulting contract

**Comment by RomanDavlyatshin** [comment]
@jennifer-shehane 
Can you, please, give a comment on that problem, or recommend somebody that has more info?
P.S. Sorry to ping you like that, but I don't really see/know anybody else from the Cypress.io team responding to the issues.

**Comment by RomanDavlyatshin** [comment]
As mentioned earlier, the speed test shows decent download speed (33-34mbps)
But cypress download is abysmally slow (~10% per 5 minutes)
So it's almost a one-hour installation, sometimes it gets worse, closer to 1h 30m
**Screenshot1** - Timer against `npm install cypress` log
![image](https://user-images.githubusercontent.com/34244611/133646102-a9c07a85-f3b6-4003-8b3a-2637ddc2fe53.png)
**Screenshot2** - Speed test results
![image](https://user-images.githubusercontent.com/34244611/133644327-4cabe96b-39a3-4257-ad30-f95954e7bd6a.png)

@jennifer-shehane  can we count on any follow-up on the situation? 😭

**Comment by TheDiveO** [comment]
It's a mess in other places in Europe too. Cloudflare doesn't deliver, "everything else" being performing well.
