### ISSUE TITLE
Cypress Dashboard sets failing specs and "error/warnings"

### ISSUE THREAD

**Issue by lifeiscontent** [cypress-io/cypress#17665]
### Current behavior

When some tests fail, cypress dashboard marks them as error'd specs with no tests.

### Desired behavior

Cypress dashboard actually shows the errored specs as failures

### Test code to reproduce

write a test using https://github.com/jaredpalmer/cypress-image-snapshot

see the tests red locally, push changes and watch the tests turn yellow in cypress dashboard

### Cypress Version

5.6.0

### Other

![image](https://user-images.githubusercontent.com/180963/128791274-78b1cef4-ac7b-4f22-a3ef-4c756a361855.png)

the .then is coming from https://github.com/jaredpalmer/cypress-image-snapshot/blob/master/src/command.js#L34-L63

![image](https://user-images.githubusercontent.com/180963/128791303-abca2f39-035e-42a4-8405-27b61cd94a8c.png)

**Comment by lifeiscontent** [comment]
@jennifer-shehane let me know if I can provide anything else for this issue to be actionable.

**Comment by jennifer-shehane** [comment]
@lifeiscontent Can you send the url of the run in the Dashboard that this occurred on?

**Comment by shawnhelps** [comment]
@jennifer-shehane I have debugging logs and a Dashboard link to provide internally

**Comment by lifeiscontent** [comment]
Turns out it was an issue in our setup, we were having cypress exit on any assertion error
