### ISSUE TITLE
If more than 1 screenshot is taken per test, screenshot names stay same and overwrite previous

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1766]
### Current behavior: 
With code below, I am expecting 2 screenshots to be taken. 
1. The screenshot from `.screenshot()` command
2. The screenshot on failure from my `.contains()` failing to find the content.

```js
it('cy.screenshot() - take a screenshot', () => {
  cy.get('.misc-table')
    .screenshot()
  cy.contains('Cheryl') // failure here
})
```

In the process output, you can see the 2 screenshots have the same name:

```bash
  (Screenshots)

  - /.../cypress/screenshots/Misc -- cyscreenshot - take a screenshot.png (672x300)
  - /.../cypress/screenshots/Misc -- cyscreenshot - take a screenshot.png (2560x1440)
```

This behavior strangely works in regards to displaying in the Dashboard - both screenshots still appear. But, in my local `cypress/screenshots` folder, it causes the first screenshot to be overridden by the second, leaving me with 1 final screenshot. 

<img width="437" alt="screen shot 2018-05-24 at 1 53 20 pm" src="https://user-images.githubusercontent.com/1271364/40502753-efcbc806-5f59-11e8-8e4d-7bb6646f046d.png">

### Desired behavior

I should have uniquely named screenshots regardless of whether they were captured in the same test. 

### Versions  

Ran in Cypress `develop` - future 3.0.0 release

**Comment by stevepkuo** [comment]
Does anyone know of any workaround? Such as anticipating what name the screen shot would be saved under, checking if it already exists in the folder, and giving the new screenshot a slightly different name? I'm currently on Cypress v2.1.0. It looks like I might need the newer cy.task() from v3.0.0 to do the above.

**Comment by chrisbreiding** [comment]
As long as you pass in a name for the screenshot and ensure that's unique, this shouldn't be a problem.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by jaydeep987** [comment]
There should be option for that instead of directly duplicating. Not in all case duplicate behavior is needed. In some cases replacing is better.

**Comment by jennifer-shehane** [comment]
@jaydeep987 Please open a new issue specifying the exact details of the feature you are requesting.
