### ISSUE TITLE
Screenshot (failed) captured during skipped tests

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#17660]
### Current behavior

In some circumstances invovling skipped tests and the Cypress 'fail' event listener a failure screenshot will be taken when it shouldn't be. 

### Desired behavior

1. A failure screenshot should never be taken when the test is skipped. 
2. The `fail` event handler shouldn't be triggered during skipped tests. 

### Test code to reproduce

`spec.js`

```js
Cypress.on('fail', () => {
  throw new Error('error')
})

describe('tests', () => {
  before(function () {
    this.skip()
  })
  it('failing test', () => {
    expect(true).to.be.false
  })
})
```

<img width="829" alt="Screen Shot 2021-08-09 at 2 14 45 PM" src="https://user-images.githubusercontent.com/1271364/128761523-22bfa84e-edf0-4cda-ac1d-38ebe5f5ecec.png">

### Cypress Version

8.2.0

**Comment by jmoses** [comment]
I'm seeing this with 8.4.1 using the https://github.com/cypress-io/cypress-skip-test plugin, as well.

**Comment by rkrisztian** [comment]
Same bug when using [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor), which I use to filter tests by tags, thus I'm having plenty of failed screenshots when none of my tests fail.

**Comment by petetnt** [comment]
I think I am running into this, but even in a weirder from on 8.7.0.

In my case, is have two test cases, called Foo and Bar

In Foo.spec.ts, I have a failing case:

```ts
describe('Foo', () => {
  it('foo fails', () => {
    throw new Error('Fail');
  });
});
```

I have `bar.spec.ts`

```ts
describe('Bar', () => {
  it.skip('skip', () => {
    // noop 
  });
});
```

When running the tests, I had the following screenshot saved:

```
screenshots/bar.spec.ts/Foo -- foo fails (failed).png
```

The test output shows that `Bar skip` failed and the failed succeeded.

I have no idea what's going on with that.

**Comment by ryanthemanuel** [comment]
@petetnt I have a fix for the issue in the main description coming in on #19331. I could not reproduce your use case exactly. When this lands, if you still are having the same problem, feel free to open a separate issue.
