### ISSUE TITLE
UserAgent is not being set

### ISSUE THREAD

**Issue by melibe23** [cypress-io/cypress#17672]
### Current behavior

I created a [repo](https://github.com/melibe23/doubts-with-cypress/tree/master/cypress/integration) where you can see the reproducible bug or where you can point me out the mistake. 

The thing is that I always get the same userAgent, it doesn't change. I have even split the tests (originally on file) into 3 different ones (desktop, tablet, mobile) with no luck.

We just bought an Enterprise plan for my company, and our app really depends on userAgent (google bot as well). So it is a must that the userAgent is set. 

Is this a bug or I am doing something wrong?

### Desired behavior

userAgent should be set.

### Test code to reproduce

```js
import { viewportsObj, userAgents, viewportsNames, browser } from '../support/default'

const path = `https://example.cypress.io/`

describe(`${browser}-hero-image`, () => {
  viewportsObj.slice(0,1).forEach((viewport, i) => {
    context(`${viewportsNames[0]}`, viewport, () => {
      before(() => {
        cy.visit(path, {
          headers: {
            'user-agent': `${userAgents[0]}`,
          },
        })

      })

      it('Log-user-agent', () => {
        console.log(`Expected UserAgent: ${userAgents[0]}`)
        console.log(`navigator.userAgent: ${navigator.userAgent}`)
        // logs: UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
      })

    })
  })
})
```

default.js

```js
export const browser = Cypress.browser.name
export const domain = Cypress.config().baseUrl

const obj = {
  iphonexr: {
    viewportHeight: 896,
    viewportWidth: 414,
  },
  iPad2: {
    viewportHeight: 1024,
    viewportWidth: 768,
  },
}

export const viewportsObj = Object.values(obj)
export const viewportsNames = Object.keys(obj)

export const userAgents = [
  'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1',
  'Mozilla/5.0 (iPad; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1',
]
```

### Cypress Version

^8.2.0v

### Other

![image](https://user-images.githubusercontent.com/32499737/128857332-c1918cec-68e9-4e3e-8a9f-1e272b06087c.png)

**Comment by jennifer-shehane** [comment]
You need to set the `user-agent` via the Cypress config, since the browser needs to be launched/relaunched with this browser agent. https://on.cypress.io/configuration#Browser If you want to change the user-agent between tests, you'll need to write it in such a way so thaty you relaunch the browser via `cypress run` each time.

**Comment by melibe23** [comment]
@jennifer-shehane So I have to use 3 different config files to have 3 different userAgents? then I have to create 3 different sscripts, desktop, mobile, tablet and use each config accordingly?

**Comment by austinberner360** [comment]
I am also encountering the same problem with my Cypress project as well. I'm running on my local machine and userAgent reveals a Catalina OS, instead of Big Sur (which is my current one). 

It does reveal the correct browser version though...
