### ISSUE TITLE
Cannot run component testing in pre-commit hook

### ISSUE THREAD

**Issue by Zombobot1** [cypress-io/cypress#17699]
### Current behavior

If I add "npx cypress run-ct" in .git/pre-commit and use default vs code git GUI to make a commit I get an error:
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

> template@1.0.0 pre-commit
> npm run test-ci


> template@1.0.0 test-ci
> cross-env NODE_ENV=development cypress run-ct

We found an invalid configuration value:

Found an error while validating the `browsers` list. Expected `version` to be a non-empty string. Instead the value was: `{"name":"electron","channel":"stable","family":"chromium","displayName":"Electron","version":"","path":"","info":"Electron is the default browser that comes with Cypress. This is the default browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses."}`
husky - pre-commit hook exited with code 1 (error)
```

### Desired behavior

The hook runs with no errors

### Test code to reproduce

I added husky to make it easier to run hooks (the problem can be reproduced without it)

How to reproduce:
1. Clone [Repo](https://github.com/Zombobot1/cypress)
2. npm i
3. npm set-script new "cypress run-ct" # make changes to repo
4. use vs code (version 1.59, all extensions disabled) to commit changes and click "Show command output"
![image](https://user-images.githubusercontent.com/48030070/129012964-e9920850-8960-42aa-9656-8dcd9d2a93c3.png)

### Cypress Version

8.2.0

### Other

If I change cypress version to 7.7.0 the error changes to something like this: "Cannot import module "--run-project""
If I run another command e.g. open-ct it succeeds
If I commit without using VS Code git GUI then the hook with run-ct succeeds

**Comment by jennifer-shehane** [comment]
Do you have the `ELECTRON_RUN_AS_NODE` env var set by chance? I've seen this similar error in this issue. https://github.com/cypress-io/cypress/issues/17412

**Comment by Zombobot1** [comment]
I didn't set any environment variables but NODE_ENV. However, I don't know how to check it. If I write console.log with it in webpack.config.js it doesn't print anything. I suppose the error happens before processing my webpack.config.js

**Comment by JessicaSachs** [comment]
This example works fine on the Command Line. It's only an issue with VSCode. I'm using the same version of Cypress and VSCode. Our stack traces are different though -- I don't get an error about the `--browsers`.

I'll upload some of my logs from the failed VSCode command.

[2021-08-18T04_02_27_369Z-debug.log](https://github.com/cypress-io/cypress/files/7004436/2021-08-18T04_02_27_369Z-debug.log)
[git-error-1629259350871.log](https://github.com/cypress-io/cypress/files/7004437/git-error-1629259350871.log)

It can't find Cypress at the location it thinks it should be. I'm not really sure why.

**Comment by Omarov3000** [comment]
I experience the same problem on MacOS. I have the similar log as @JessicaSachs has.

**Comment by a-zich** [comment]
I run into the same problem in VSCode.
As @jennifer-shehane  asked about the environment variables, I added an 'export' command before the test run. And yes, besided a lot of other stuff, it shows

export ELECTRON_RUN_AS_NODE="1"

So VSCode sets this automatically.

I change my pre_commit file and it commited fine.

```
echo "***Running unit tests***"
unset ELECTRON_RUN_AS_NODE
npm test -- --config video=false screenshotOnRunFailure=false
```

**Comment by krchmkn** [comment]
Thanks @a-zich this line helped me `unset ELECTRON_RUN_AS_NODE`
