### ISSUE TITLE
Cypress Trigger eventConstructor  does not support DropEvent

### ISSUE THREAD

**Issue by bhavikpatel7023** [cypress-io/cypress#17703]
### Current behavior

I would like to see support for Browser native event in a trigger.

### Desired behavior

Should support browser native events.

### Test code to reproduce

const testFile = new File([blob], filePath)
const dropEvent = { eventConstructor: 'DragEvent', dataTransfer: { files: [testFile] } }

### Cypress Version

7.7.0

**Comment by bhavikpatel7023** [comment]
@jennifer-shehane

**Comment by JessicaSachs** [comment]
Can you add a standalone reproduction? In the meantime, consider giving [this plugin](https://github.com/4teamwork/cypress-drag-drop) a try.
