### ISSUE TITLE
hooks can rerun on unrelated tests after top navigation

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#17705]
### Current behavior

example: session_spec running hooks multiple times after navigation: https://app.circleci.com/pipelines/github/cypress-io/cypress/22975/workflows/4a639267-6eda-4e78-84b6-5c1f3426f04e/jobs/845803/parallel-runs/7

This occurs when a global before/after hook is present
### Desired behavior

before/after hooks should only be run once and on correct suite

### Test code to reproduce

n/a

### Cypress Version

8.2.0

**Comment by c32hedge** [comment]
Please be sure to also check the case of visiting multiple superdomains, as described in #17940
