### ISSUE TITLE
Cypress browser & accepting cookies with SSO

### ISSUE THREAD

**Issue by jdoetricksy** [cypress-io/cypress#17701]
### Current behavior

- The following happens:

1. `beforeEach(() => {
        Cypress.Cookies.defaults({
           preserve: /[\s\S]*/
        });
    })`
2. Visit baseUrl page
2. Click on Claims and the page goes to page with SSO login 
3. Login with SSO username and password
4. Login fails with the error message "Please ensure that your browser accepts cookies when logging in."

- The test runs in Electron and successfully works, but when we re-run the test, the authenticated state remains logged in and breaks the test. This is performing unintentionally
- The test does not work in Chrome browser. When trying to log the cookies using cy.getCookies, the only cookies logged were from the baseURL domain. Preserving the cookies in beforeEach doesn't have an effect
- When removing "chromeWebSecurity":true from the cypress.json, the test errors in all browsers
- I tried to restructure the test by extracting the dynamicURL from the href and visiting it in separate test but it still shows the same error.

### Desired behavior

- The test steps should be the following:

1. Visit baseUrl page
2. Click on Claims and the page goes to page with SSO login 
3. Login with SSO user and password
4. Page redirects back to baseUrl and the authorization cookie is loaded
5. Check that the COOKIE is ok

### Test code to reproduce

```js
describe('Authentication with SSO', function(){

    beforeEach(() => {
        Cypress.Cookies.defaults({
           preserve: /[\s\S]*/
        });
    })

    it('Should get SSO authentication cookie',() => {

      // The flow will be:
      // 1. Visit baseUrl page
      // 2. Click on Claims and the page goes to SSO sign in page
      // 3. Login with SSO user and password
      // 4. Page redirects back to baseUrl and the authorization cookie is loaded
      // 5. Check that the COOKIE is ok

      cy.visit('/')
      cy.contains('Claims').click()

      //Click to redirect to WebSSO page
      cy.contains('Button').click()

      // redirects to WebSSO sign in page
      cy.url()
        .should('include','https://example.com/signin')
                        
      cy.get('#InputUsername')
        .type('ExampleUsername')
      
      cy.get('#InputPassword')
        .type('examplePassword')
      
      cy.get('#LoginButton').click()

      // after successful login redirects back to base url
      cy.url()
        .should('include','https://example.com/Redirect/SSO)

      // validates that the authentication cookie is there
      cy.contains('COOKIE_OK').should('be.visible')
    })
})
```

### Cypress Version

7.7.0

### Other

In case you need access to reproducible repository feel free to contact me.

**Comment by jennifer-shehane** [comment]
I would suggest taking a look at our new `cy.session()` command, it's meant to help with logging in flows and handle things like cookies for you. It's available in 8.2.0+. https://on.cypress.io/session

**Comment by jdoetricksy** [comment]
Hi Jennifer, 

thank you for the prompt response. 
Applying cy.session() to the code in the following way 

`describe('Authentication with SSO', function(){

    beforeEach(() => {
        Cypress.Cookies.defaults({
           preserve: /[\s\S]*/
        });
    })

    it('Should get SSO authentication cookie',() => {

      // The flow will be:
      // 1. Visit baseUrl page
      // 2. Click on Claims and the page goes to SSO sign in page
      // 3. Login with SSO user and password
      // 4. Page redirects back to baseUrl and the authorization cookie is loaded
      // 5. Check that the COOKIE is ok
      cy.sesssion('sesssionName', ()=> {
        cy.visit('/')
        cy.contains('Claims').click()
  
        //Click to redirect to WebSSO page
        cy.contains('Button').click()
  
        // redirects to WebSSO sign in page
        cy.url()
          .should('include','https://example.com/signin')
                          
        cy.get('#InputUsername')
          .type('ExampleUsername')
        
        cy.get('#InputPassword')
          .type('examplePassword')
        
        cy.get('#LoginButton').click()
  
        // after successful login redirects back to base url
        cy.url()
          .should('include','https://example.com/Redirect/SSO)
  
        // validates that the authentication cookie is there
        cy.contains('COOKIE_OK').should('be.visible')
      })
    })
})` 
returned the same error as a result. 
Am I missing something here?

**Comment by alvaromartmart** [comment]
According to the documentation, [Cypress.Cookies.defaults() does not work while the experimental cy.session command](https://docs.cypress.io/api/commands/session).

...but that's probably not the problem, unless you're getting the error in other tests that might need the cookie but are not using cy.session to perform the login.

Is it possible that some of the cookies are being set asynchronously *after* the last assertion in the cy.session setup function passes? In that case, I think those cookies might not be cached.

**Comment by fahmij8** [comment]
@jdoetricksy I am also facing the same problem, and it's been almost a year (roughly) since you opened the issue. Have you found another workaround, especially dealing with SSO?

**Comment by Thebarda** [comment]
I'm facing the same issue with `cy.session`
