### ISSUE TITLE
events like "window:before:load" dont fire when running component tests

### ISSUE THREAD

**Issue by glomotion** [cypress-io/cypress#17707]
### Current behavior

putting code like: 
```javascript
it('should do something, () => {
   cy.on('window:before:load', (win) => {
       console.log('#######################', win);
   });

   // assertions ...
});

```
inside of a `@cypress/react` test suite - does absolutely nothing. 😭 

### Desired behavior

the console log should fire before the test begins (just as the window begins loading, per the [docs](https://docs.cypress.io/api/events/catalog-of-events#App-Events))

### Test code to reproduce

https://github.com/cypress-io/cypress-test-tiny/pull/69 includes an exmaple failing spec

### Cypress Version

8.2.0

### Other

"@cypress/react": "^5.9.4",

**Comment by JessicaSachs** [comment]
Not surprised. We haven't added a lot of the E2E-heavy hooks yet.

Just curious... What are you trying to do?

**Comment by lmiller1990** [comment]
Hi! Docs have been updated - some events are marked "End to End only". https://docs.cypress.io/api/events/catalog-of-events.

The `window` ones are not implemented in CT. Maybe they should be? What are you going to do with `window`?

An alternative might be

```
  Cypress.on('test:before:run', () => {
      window. // do things here
  });
```

If you have a specific use case where you absolutely need `window` and `test:before:run` won't cut it, can you make a new issue explaining the use case? We can implement it if it makes sense 👍 thanks!
