### ISSUE TITLE
Update cy.screenshot() to accept directory location + filename

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1771]
### Current behavior: 

The code below saves the screenshot as the name `foobarbazquux.png` within the `screenshotsFolder`

```js
cy.screenshot('foo/bar/baz/quux')
```

### Desired behavior:

The above code should create the necessary directories in order for the screenshot to be saved at `foo/bar/baz/quux.png` within the `screenshotsFolder`.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by egucciar** [comment]
@jennifer-shehane @brian-mann how can I disable the automatic folder placement for screenshots? since I have custom commands which store images and move them into a specific folder, please let me know the option i need to pass to disable this feature temporarily while I evaluate the new screenshot capabilities and work on solving the matching. Thanks!

**Comment by brian-mann** [comment]
@egucciar I wouldn't hard code its path there - thats the problem. I would use the new `after:screenshot` event in your `pluginsFile` so you can do whatever it is you want to do in node. That would avoid the need to ever need `cy.exec` here.

Alternatively you could use the `onAfterScreenshot` callback that `cy.screenshot()` takes, which will always include the path to the screenshot.

- https://docs.cypress.io/api/plugins/after-screenshot-api.html#
- https://docs.cypress.io/api/commands/screenshot.html#Get-screenshot-info-from-the-onAfterScreenshot-callback

**Comment by egucciar** [comment]
@brian-mann the issue is that this is not a plugin but rather a `Cypress.command`. the way I understood is commands go into `support` and plugins go into `plugins`. Would i be able to write a command such that I can actually invoke a `cy.matchScreenshot` ?

**Comment by egucciar** [comment]
@brian-mann the question is can we make an assert & fail a test from a `plugin` ? Because the idea is to run `assert` on the results of the diffing algorithm.

**Comment by brian-mann** [comment]
Yes every plugin event is promise aware so if you reject a promise or throw then the `cy.screenshot` will fail and the error will propagate as the source of the failure.
