### ISSUE TITLE
Selector prefers DOM hierarchy instead of cypress class(Data-*)

### ISSUE THREAD

**Issue by shahul01** [cypress-io/cypress#17727]
### Current behavior

When I use Cypress selector in test to get identify element, it outputs DOM hierarchy(via class and pseudoclass) instead of cypress attribute(data-*).

### Desired behavior

![image](https://user-images.githubusercontent.com/53307156/129288330-3fe6b58b-97b3-4059-a893-17c82a69c4b3.png)

If there is data-* attribute in element it should output that first then it can go through preferred selectors according to best practises (descending order).

### Test code to reproduce

(general cypress behaviour)

### Cypress Version

8.0.0

**Comment by MDjhowley** [comment]
You can configure this behaviour, see https://docs.cypress.io/api/cypress-api/selector-playground-api#Syntax

**Comment by JessicaSachs** [comment]
Thanks @MDjhowley. We have a solution for this already and we're actively developing in this area so there will likely be improvements. (With tools like Cypress Studio, selector playground, etc).
