### ISSUE TITLE
Reversed argument order in .then

### ISSUE THREAD

**Issue by superMDguy** [cypress-io/cypress#1772]
### Current behavior: 

According to [this line](https://github.com/cypress-io/cypress/blob/2e68ab8d7e234f96910c36b8609b33a3fa049004/packages/driver/src/cy/commands/connectors.coffee#L26), the `.then` function has a signature of `(subject, options, fn)`. The [docs](https://docs.cypress.io/api/commands/then.html#Arguments) say that, like most other cypress functions, the options is the last argument, so `(subject, fn, options)`.

### Desired behavior:

The signature should be `(subject, fn, options)`, to be consistent with the docs and other cypress functions. However, that could break others' existing tests. So, maybe a better solution would be to just update the docs with the correct argument order.

### Steps to reproduce:

n/a

### Versions  

n/a

**Comment by jennifer-shehane** [comment]
> The docs say that, like most other cypress functions, the options is the last argument, so (subject, fn, options)

The syntax indicates the `options` is the first argument (if needed) here:

<img width="338" alt="screen shot 2018-05-25 at 10 32 30 am" src="https://user-images.githubusercontent.com/1271364/40550059-1597d374-6007-11e8-9f83-009282771310.png">

I suppose you are referring to the order of the [Arguments](https://docs.cypress.io/api/commands/then.html#Arguments) as listed, with the `fn` first and `options` last - indicating that this reflects the order or arguments. 

This *does* seem to coincidentally be the case on most of the API docs. I seriously doubt we will change to order of the `option` in the API itself.

So, I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to update this here: https://github.com/cypress-io/cypress-documentation/issues/618. Our documentation is open source and contributions are welcome. 😄

**Comment by superMDguy** [comment]
Somehow I missed the syntax section, since I was looking at the arguments section. It's kind of strange that the options are the first argument in this command, but I agree that changing the docs is the best option.
