### ISSUE TITLE
Ability to loop through asserts(it)

### ISSUE THREAD

**Issue by shahul01** [cypress-io/cypress#17726]
### What would you like?

I use custom commands to create loop to go through multiple input and type or read values. And I use those loop to make a CRUD test for each page.

However I want to make that entire CRUD test itself a module. So I can just call it on many pages.

Here's an example: this is the Read part of test for a page:

  ` it('can read correct values', function() {
      cat = this.data.update;
      cy.page1ReadLoop(cat)
  }); `

I want to make this:
  `cy.crudLoop(this.data.page1)`

The latter may or may not require `it`(assertions) but CAN create `it`(assertions).

### Why is this needed?

Why: DRY principle.

Cypress is known for making good features, this feature is based on DRY principle and it should be implemented as much. This would remove unnecessary code therefore less bugs to hunt and make entire test a module which can help testing code update easily.

So kindly make this feature, regards.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

It's a bit hard to guess what you want without working examples. 

Testing scenario for CRUD can be really different from page to page. 

If it really hurts DRY In the code, maybe [custom commands](https://docs.cypress.io/api/cypress-api/custom-commands#Syntax) can be a solution. Or simply adding a few test utility functions might do the job.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
