### ISSUE TITLE
Type to input field within iFrame not working

### ISSUE THREAD

**Issue by MichaelBaySAP** [cypress-io/cypress#17731]
### Current behavior

I have a input field within an iFrame 
![image](https://user-images.githubusercontent.com/40032066/129357927-abc4e276-30a4-4404-ab8c-f26813141286.png)

I can locate the input through locating the iFrame object, getting its contents and searching for inputs.

`cy.get('div.[..]-dialog__body.[..] > div > iframe ').then((iframe) => {
   const doc = iframe.contents();
      const inputs= doc.find('input');
        inputs[1].click();
          inputs[1].type('test', {force: true});
          });` 
          
However, when I execute ` inputs[1].type('test', {force: true});`, it returns me, that it cannot type to this element.
![image](https://user-images.githubusercontent.com/40032066/129355176-6bb1a012-5cd3-4778-b329-638e057a12b0.png)

When I execute `inputs[1]`, it returns the input , so the input can be located but it cannot be typed to.
![image](https://user-images.githubusercontent.com/40032066/129355854-4741fcfd-8c66-45f6-8889-317f2f14ca9c.png)

Do you know how to get it to work?

### Desired behavior

Type into input field within iFrame

### Test code to reproduce

`cy.get('div.[..]-dialog__body.[..] > div > iframe ').then((iframe) => {
   const doc = iframe.contents();
      const inputs= doc.find('input');
        inputs[1].click();
          inputs[1].type('test', {force: true});
          });` 

### Cypress Version

8.2.0

**Comment by JessicaSachs** [comment]
This isn't a bug. I just tested it locally The reason your test is failing is because you're operating on a DOM Element. `type` isn't a function on DOM Elements. Here's a working example, using `cy.wrap`, which takes DOM Elements and wraps them into Chainables where you can call all the normal Cypress methods.

```js
const selector = 'div.[..]-dialog__body.[..] > div > iframe '

cy.get(selector)
  // iframe.contents()
  .invoke('contents') 

   // Once input exists, we can try to type in it.
  // You can't call cy.wrap(input) from within should, so you need to go into another `then`
  .should((doc) => {
    const input = doc.find('input')
    expect(input.length).to.equal(1)
  })
  .then((doc) => {
    cy.wrap(doc.find('input')).type('input value')
  })
```

**Comment by MichaelBaySAP** [comment]
Hi Jessica,

I have tried your code. I have omitted the should block and I tested with input.length === 2. 

I still only receive a Chainer Object and no text is typed.
![image](https://user-images.githubusercontent.com/40032066/129874090-81e1452a-55b9-41a3-aa54-d4ee9baaee93.png)

**Comment by JessicaSachs** [comment]
You need to use `should` to retry the DOM to wait until the input is found inside. Just asserting the length won't force Cypress to wait until it exists. Apologies, but I can't help you debug further. This is what our support forums are for. :bow:
