### ISSUE TITLE
Browser extensions or add ons button are not showing in browser(chrome) opened by cypress during execution of tests

### ISSUE THREAD

**Issue by waqaskamran** [cypress-io/cypress#17733]
### Current behavior

Browser extensions are not showing in browser(chrome) opened by cypress during execution of tests.

Browser :Chrome 92

I have one extension/add on button in my browser ,but when i execute automation test and cypress opens browser that extension  does not appear and i get an error button does not found . 

Cypress package version: 8.2.0
Cypress binary version: 8.2.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1

### Desired behavior

there should be extension button to click on it .

### Test code to reproduce

    cy.get('#scxt-stock-btn').click();

### Cypress Version

8.2.0

**Comment by Narretz** [comment]
Cypress is using a fresh instance of Chrome without extesions. You can add them manually: https://docs.cypress.io/api/plugins/browser-launch-api#Modify-browser-launch-arguments-preferences-and-extensions

**Comment by sayjavajava** [comment]
thanks for reply . I need to add this addon https://chrome.google.com/webstore/detail/online-seller-addon/cmjihoeplpkmlmbbiiognkceoechmand

I tried with crx downloaded from here https://www.crx4chrome.com/crx/241166/  but i am not sure its same or not . 

how can i convert or find exact extension or addon that i am using in my browser https://chrome.google.com/webstore/detail/online-seller-addon/cmjihoeplpkmlmbbiiognkceoechmand ?
```
module.exports = (on, config) => {
  on('before:browser:launch', (browser, launchOptions) => {
    // supply the absolute path to an unpacked extension's folder
    // NOTE: extensions cannot be loaded in headless Chrome
    launchOptions.extensions.push('/Users/AWS/extension_1_3_5_0.crx')

    return launchOptions})
}
```

but it didn't work.
