### ISSUE TITLE
Invalid URL for CI guide

### ISSUE THREAD

**Issue by decio** [cypress-io/cypress#17735]
### What would you like?

Hello,

After running my first test on cypress, I got an email about integrating with CI and there is a link for a guide but the link gives a 404 error:
https://docs.cypress.io/guides/guides/continuous-integration.

![image](https://user-images.githubusercontent.com/31675741/129364909-25dc0a96-48db-4cf1-8a24-ddd34a066cdc.png)

![image](https://user-images.githubusercontent.com/31675741/129364934-a95bb0ed-3620-4d62-9493-b162f70b8908.png)

I believe the correct link should probably be: https://docs.cypress.io/guides/continuous-integration/introduction

**Comment by jennifer-shehane** [comment]
Thanks for pointing this out. Checking to get our success team to look at the email links and see if docs can reroute this route by default instead of 404'ing.

**Comment by jennifer-shehane** [comment]
Closing as the respective teams have addressed
