### ISSUE TITLE
Hello, I am getting proxy error while installing Cypress. I have added proxy of my organization. Still it shows same error. I tried all options like connecting/disconnection from vpn and installing. With proxy without proxy. Restarting. but nothing could help. CAn anyone please assist me.

### ISSUE THREAD

**Issue by 503090795** [cypress-io/cypress#17743]
### Current behavior

 Screenshots of errors getting- 
```
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! Installing Cypress (version: 8.2.0)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be downloaded.
npm ERR!
npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR!
npm ERR! Otherwise, please check network connectivity and try again:
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! URL: https://download.cypress.io/desktop/8.2.0?platform=win32&arch=x64
npm ERR! Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Platform: win32 (10.0.18363)
npm ERR! Cypress Version: 8.2.0
npm ERR! [FAILED] The Cypress App could not be downloaded.
```

I also tried options mentioned in https://on.cypress.io/proxy-configuration, Set env var too.

![image](https://user-images.githubusercontent.com/45641563/129501047-e731b971-6669-42f0-a367-4e3d639d087b.png)

### Cypress Version

8.2

### Package Manager

npm

### Operating system

Windows

**Comment by aychernov** [comment]
I am getting a similar error, what should I do?
![image](https://github.com/cypress-io/cypress/assets/67840786/ded9a31e-5b1d-49fa-80a7-936a6eeb786e)

**Comment by aychernov** [comment]
> E.g.: `HTTP_PROXY`

Where can I set it up?

**Comment by MikeMcC399** [comment]
@tallkey 

You should probably read https://docs.cypress.io/guides/references/proxy-configuration

**Comment by nagash77** [comment]
I am going to close this issue as it is a question.  Questions should be directed to [Cypress Discord](https://discord.gg/cypress).

**Comment by RadoslavSt** [comment]
I solved this when I put -y on npm init.    npm init -y     
Then install cypress.

**Comment by MrSwitch** [comment]
In my case this resolved itself after the issue reported in https://www.cypressstatus.com was unblocked
