### ISSUE TITLE
Cypress causing battery drain and heat on M1

### ISSUE THREAD

**Issue by saurabhnemade** [cypress-io/cypress#17754]
### Current behavior

I am not sure what is exact reason for this but I am using M1 with cypress for over a month now and every time I open cypress it drains battery of M1 faster than any other application. It also heats up while running cypress.

### Desired behavior

It should not consume so much battery and produce so much heat.

### Test code to reproduce

Nothing specific even the default test cases results in same behaviour.

My cypress configuration:
```
{
  "component": {
    "componentFolder": "src/tests/cypress/components",
    "testFiles": "**/*spec.{js,jsx,ts,tsx}"
  },
  "viewportHeight": 660,
  "viewportWidth": 1600
}
```

### Cypress Version

7.2.0

### Other

Cypress package version: 7.2.0
Cypress binary version: 7.2.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1

**Comment by francisu** [comment]
If you are using Typescript and CRA, forcing you to use v4.x of fork-ts-checker-webpack-plugin, this might be your problem: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/655

**Comment by binarykitchen** [comment]
(how did you manage to install Cypress on M1??)

**Comment by saurabhnemade** [comment]
> If you are using Typescript and CRA, forcing you to use v4.x of fork-ts-checker-webpack-plugin, this might be your problem: [TypeStrong/fork-ts-checker-webpack-plugin#655](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/655)

Nope. I am using plain create-react-app boilerplate without TS.

**Comment by saurabhnemade** [comment]
> (how did you manage to install Cypress on M1??)

Scripts: 
```
"cypress:open": "node_modules/.bin/cypress open-ct open",
"cypress:ci": "node_modules/.bin/cypress run-ct",
```

Dev-Deps
```
"@cypress/react": "^5.4.1",
"@cypress/webpack-dev-server": "^1.1.5",
"@testing-library/cypress": "^7.0.6",
"cypress": "^7.2.0",
```

Using with Rosetta 2 :
```
npm : 7.20.3
node: v16.6.2
``

**Comment by saurabhnemade** [comment]
> We've made some improvements in terms of performance, which could save some CPU in our more recent versions. You may want to update and see if it still has this effect.

Thanks @jennifer-shehane 
Will check it with latest version for next couple of weeks.

**Comment by binarykitchen** [comment]
Well good for you but for me, it gets stuck at 100% Download.

**Comment by emilyrohrbough** [comment]
As of Cypress 10.2.0, Cypress is available natively on Apple silicon, including the M1 and M2 processor families. For more details, read [our blog post](https://www.cypress.io/blog/2022/06/21/cypress-10-2-0-run-tests-up-to-2x-faster-on-apple-silicon-m1/). Addresses [#19908](https://github.com/cypress-io/cypress/issues/19908).

Closing as fix. Please open a new issue if you experience any other problems.
