### ISSUE TITLE
cy.visit() performance degradation after upgrade from 7.1 (persists in 8.3)

### ISSUE THREAD

**Issue by amacgregorhumi** [cypress-io/cypress#17759]
### Current behavior

We're using Cypress extensively to test our application, and we noticed some performance issues and odd `pageLoadTimeout` error that randomly started happening, after several days of back and forth; support pointed towards https://github.com/cypress-io/cypress/issues/16671 

While upgrading to 8.3.0 seems to have marginally help with this issue becoming less frequent; there is still a pretty high chance of occurrence; as far as we have been able to tell the page in question is loaded but the `load` event was not captured by cypress. 

Our test suite is currently using chromium 91. 

### Desired behavior

`cy.visit()` should work as expected and load the page without timing out.

### Test code to reproduce

-

### Cypress Version

8.3.0

**Comment by jennifer-shehane** [comment]
What’s the last known version that worked without the perf/timeouts?

can you provide a reproducible example? Even one emailed to support@cypress.io?

Is this happening locally or only in a specific CI environment?

**Comment by amacgregorhumi** [comment]
Hi Jennifer, 

> What’s the last known version that worked without the perf/timeouts?

The last version known to work for us was 7.1 


> can you provide a reproducible example? Even one emailed to [support@cypress.io](mailto:support@cypress.io)?

We have provided support with additional information including debug logs #2517

> Is this happening locally or only in a specific CI environment?

Right now it seems to be specific to Github Actions or at least where is happening more frequently.

**Comment by jennifer-shehane** [comment]
@amacgregorhumi I looked over the debug logs and don't see anything obvious that would be causing this to time out regularly. Have you tried increasing the timeout? Does it ever resolve if given more time? 

I think we'll need a way to run and see the situation though to track down why the load is hanging. 

Just to confirm, 7.1.0 is working but 7.2.0 has the issue? Tracking down the exact version where the issue begins would also be helpful in tracking down the cause. Thanks.
