### ISSUE TITLE
Cypress 8.3.0 is crashing while closing test runner window on MacOS

### ISSUE THREAD

**Issue by viktorgogulenko** [cypress-io/cypress#17766]
### Current behavior

When I'm trying to close a window of UI test runner on my Mac, it crashes with an error:
```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (19.6.0)
Cypress Version: 8.3.0
```

### Desired behavior

Cypress should exit without crashing

### Test code to reproduce

Just open Cypress 8.3.0 test runner with 'cypress open' and try to close a test runner window from UI

### Cypress Version

8.3.0

**Comment by bahmutov** [comment]
Yup, see it often myself, even when shooting a video about upgrading to v8.3.0 :) https://www.youtube.com/watch?v=UMtvmVgpZdU&ab_channel=glebbahmutov

**Comment by jennifer-shehane** [comment]
Thanks for reporting. Thanks for the video gleb. Timestamp of crash: https://youtu.be/UMtvmVgpZdU?t=137 We're investigating.

**Comment by flotwig** [comment]
Very similar to #9164. I wonder if that bugfix was actually correct.

**Comment by viktorgogulenko** [comment]
I reverted back my version to 8.2.0 and unfortunately have no time now to play with it. For me it was consistently reproducible with every closing of window.

**Comment by flotwig** [comment]
I can reproduce this on MacOS Catalina 10.15.7 by launching tests in `cypress open`, opening Electron 91, closing Electron 91, and then closing Cypress. Then the SIGSEGV occurs.

**Comment by bahmutov** [comment]
Yes!
