### ISSUE TITLE
Syntax error reported in version 8.3.0 but not in 8.2.0

### ISSUE THREAD

**Issue by RaduQA** [cypress-io/cypress#17769]
### Current behavior

Error: Webpack Compilation Error
![22](https://user-images.githubusercontent.com/88479939/129739842-08510d06-669e-43e9-a1e1-6791940eae49.png)

### Desired behavior

it should work like version 8.2.0

### Test code to reproduce

nothing to add

### Cypress Version

8.3.0

**Comment by jennifer-shehane** [comment]
This looks like this is a legitimate error in the writing of the expect. The line `expect(password LabelFirst)` requires a `,` as it is 2 arguments if it is not concatenated together as string.

**Comment by jennifer-shehane** [comment]
I am able to reproduce this issue in both 8.2.0 and 8.3.0 when not suplying a comma when passing 2 arguments to expect. Can you also confirm? I'm using the example below.

```js

describe('tests', () => {
  it('failing test', () => {
    expect('foo' 'bar').to.equal('baz');
  })
})
```

**Comment by emilyrohrbough** [comment]
@RaduQA I am going to go ahead and close this issue since this issue is fairly old without any more information. Feel free to re-open this issue if needed.
