### ISSUE TITLE
Updating to 8.3.0 Causes Cypress Executable to Be Missing

### ISSUE THREAD

**Issue by AdamEntaQA** [cypress-io/cypress#17767]
### Current behavior

When upgrading the version from 8.2.0 to 8.3.0 while installing using NPM within a docker environment, the install completes and shows as successful. However when running `./node_modules/.bin/cypress open` the container no longer picks up the executable file and I get the following in the output: 

`Cypress executable not found at: /Users/:user:/Library/Caches/Cypress/8.3.0/Cypress.app/Contents/MacOS/Cypress
`

I have tried setting the `CYPRESS_CACHE_FOLDER` env variable to override this but it has no effect. 

### Desired behavior

When the `./node_modules/.bin/cypress open` is run, the cypress window should open. 

### Test code to reproduce

`npm install --save-dev cypress@8.3.0`

### Cypress Version

8.3.0

### Other

Reverting back to 8.2.0 seems to resolve this issue.

**Comment by flotwig** [comment]
@AdamEntaQA You mention Docker - can you clarify if this error happens inside of Docker, or outside of Docker inside your regular MacOS terminal?

What happens if you do `cypress install`? 

The reason I ask is that it seems like it is trying to launch the MacOS version of Cypress at `/Users/:user:/Library/Caches/Cypress/8.3.0/Cypress.app/Contents/MacOS/Cypress` which is not going to work inside of Linux Docker. Something went wrong during OS detection or installation in this case.

**Comment by AdamEntaQA** [comment]
Hi @flotwig, 

Yep so when running outside the docker container, it is throwing the error listed in the above report. When attempting to run inside the docker container, I get an error stating that the cypress is not installed even though I can find it in the node_modules directory. 

What I found strange was that the error that was occurring was specific to version 8.3.0, and had none of these issues with 8.2.0 when running inside or outside of the container. 

Admittedly I am fairly new to Cypress so apologies if this is user error. 

Thanks, 
Adam

**Comment by flotwig** [comment]
@AdamEntaQA Cypress installs to a global cache location, so if you install it inside of a Docker container and the cache is not persisted, it will not be installed next time you go to launch it: https://docs.cypress.io/guides/getting-started/installing-cypress#Binary-cache

Run `cypress install` inside your terminal to install the correct binary for Cypress to the global cache. This should work inside Docker or inside your MacOS terminal, just keep in mind you can't use the Linux install outside of Docker or the MacOS install inside of Docker.

**Comment by AdamEntaQA** [comment]
@flotwig 

Thanks for the assistance, much appreciated.
