### ISSUE TITLE
Failure during cypress open after cypress  v8.3.0 upgrade--exit code 2147483651 in Windows

### ISSUE THREAD

**Issue by dhamo-pk** [cypress-io/cypress#17765]
### Current behavior

After upgrading with cypress using ´npm install --save-dev cypress@8.3.0´ and opening cypress with cli, gives this error. 

```
It looks like this is your first time using Cypress: 8.3.0
Cypress failed to start.
This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
Please refer to the error below for more details.
----------
Command failed with exit code 2147483651: C:\Users\USERID\AppData\Local\Cypress\Cache\8.3.0\Cypress\Cypress.exe --smoke-test --ping=729
----------
Platform: win32 (10.0.19043)
Cypress Version: 8.3.0
```

### Desired behavior

Cypress should open the Test Runner with all available test files. 

### Test code to reproduce

```
npm install --save-dev cypress@8.3.0
npm run cypress:open
```

### Cypress Version

8.3.0

**Comment by igoroctaviano** [comment]
Same here..

**Comment by jennifer-shehane** [comment]
@dhamo-pk We're working on reproducing. The crash happens when you run `cypress open` and do not click into the specfile or run the specs at all correct?

**Comment by jennifer-shehane** [comment]
@dhamo-pk @igoroctaviano It is high priority for us to track down the cause of crashes. Could either of you provide a repo that when opened in Cypress 8.3.0 causes this crash? It may be something isolated to the test suite or it's configuration. Two of our team members have not been able to reproduce it from the information given. 

- We're running on Windows 10. 
- Installing 8.3.0
- Opening Cypress

Also could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by flotwig** [comment]
Can't reproduce on Win10 x64 using Cypress 8.3.0. Cypress can launch and run tests successfully.

This user had the same issue and seems to have fixed it by updating security policies on their Windows machine: https://github.com/Microsoft/vscode/issues/15567#issuecomment-291843933

Can you check your "Event Log" when you open Cypress and see what it says? There should be an error message when Cypress crashes with this exit code that will provide more exact information.

**Comment by dhamo-pk** [comment]
Ran again with debug and here is the log.

```
C:\Repositories\fi-testautomation>set DEBUG=cypress:*

C:\Repositories\fi-testautomation>npx cypress open
  cypress:cli:cli cli starts with arguments ["C:\\Program Files\\nodejs\\node.exe","C:\\Repositories\\fi-testautomation\\node_modules\\cypress\\bin\\cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +2ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +131ms
  cypress:cli opening from options {"project":"C:\\Repositories\\fi-testautomation"} +0ms
  cypress:cli command line arguments ["--project","C:\\Repositories\\fi-testautomation"] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress\Cypress.exe +3ms
  cypress:cli Binary is executable? : true +3ms
  cypress:cli binaryDir is  C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress +1ms
  cypress:cli Reading binary package.json from: C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress\resources\app\package.json +0ms
  cypress:cli Found binary version 8.3.0 installed in: C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress +5ms
  cypress:cli could not read binary_state.json file at "C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\binary_state.json" +6ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +2ms
  cypress:cli running binary verification check 8.3.0 +1ms
It looks like this is your first time using Cypress: 8.3.0


  cypress:cli clearing out the verified version +6ms
  cypress:cli needs Xvfb? false +2ms
  cypress:cli spawning, should retry on display problem? false +0ms
  cypress:cli running smoke test +1ms
  cypress:cli using Cypress executable C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress\Cypress.exe +1ms
  cypress:cli smoke test command: C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress\Cypress.exe --smoke-test --ping=604 +1ms
  cypress:cli smoke test timeout 30000 ms +1ms
  cypress:cli Smoke test failed: Error: Command failed with exit code 2147483651: C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress\Cypress.exe --smoke-test --ping=604
    at makeError (C:\Repositories\fi-testautomation\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Repositories\fi-testautomation\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: 'Command failed with exit code 2147483651: C:\\Users\\username\\AppData\\Local\\Cypress\\Cache\\8.3.0\\Cypress\\Cypress.exe --smoke-test --ping=604',
  command: 'C:\\Users\\username\\AppData\\Local\\Cypress\\Cache\\8.3.0\\Cypress\\Cypress.exe --smoke-test --ping=604',
  exitCode: 2147483651,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +2s
  cypress:cli error message: Command failed with exit code 2147483651: C:\Users\username\AppData\Local\Cypress\Cache\8.3.0
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with exit code 2147483651: C:\Users\username\AppData\Local\Cypress\Cache\8.3.0\Cypress\Cypress.exe --smoke-test --ping=604

----------

```

**Comment by dhamo-pk** [comment]
> @dhamo-pk We're working on reproducing. The crash happens when you run `cypress open` and do not click into the specfile or run the specs at all correct?

That's correct., I was waiting for the Test Runner to open to start the tests.

**Comment by dhamo-pk** [comment]
> This user had the same issue with a different Electron app and seems to have fixed it by updating security policies on their Windows machine: [microsoft/vscode#15567 (comment)](https://github.com/microsoft/vscode/issues/15567#issuecomment-291843933)

I could not find any SRP errors/warnings in the MS - Event viewer. I have tried opening cypress again after updating the security policies in windows but no luck yet.

**Comment by flotwig** [comment]
`2147483651` is the same as hex `0x80000003` which is easier to Google about. It seems that some people have resolved this issue by removing information about the `.exe` in the Registry: https://social.msdn.microsoft.com/Forums/WINDOWS/en-US/654e30f8-e2ed-41a0-8a67-85d819f97526/a-crash-with-exception-code-0x80000003-occurred-in-module-quotvrfcoredllquot?forum=whck

**Comment by dhamo-pk** [comment]
Thank you @flotwig. I got it worked by deleting the complete folder and the reinstalled cypress from scratch. 

I have tried the above link and could not find the last part after `Image File Execution Options`. 
Goto Registry editor-> win+R->regedit->HKEY_LOCAL_MACHINE->SOFTWARE->Microsoft->Windows NT->CurrentVersion-> Image File Execution Options ->(Your application name.exe) / Delete te.processhost.exe or delete te.ext or both. 

So, I **deleted this folder** `C:\Users\username\AppData\Local\Cypress` completely 

then installed cypress using **npm install --save-dev cypress@8.3.0**   which gave the following error.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: cypress-real-events@1.5.0
npm ERR! Found: cypress@8.3.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"8.3.0" from the root project
```

then tried with **npm install --save-dev cypress@8.3.0 -force**, 

then **npm run cy:o** 

which throws 

```
> cypress open

No version of Cypress is installed in: C:\Users\DDH053\AppData\Local\Cypress\Cache\8.3.0\Cypress

Please reinstall Cypress by running: cypress install
```
Then from here, it's easy. Run the following code

**`./node_modules/.bin/cypress install`**

That's it, it will download, unzip and finish the installation. 

Finally, 

**`npm run cy:o`** or
 **`npx cypress open`** 

will launch the test runner.

**Comment by RonaldVanMaanen** [comment]
Still occuring at 8.4.1

**Comment by lukeapage** [comment]
How to get cypress to install and verify:

https://github.com/cypress-io/cypress/issues/6082#issuecomment-927020752
