### ISSUE TITLE
Cypress Component Tests do not detect tests in spec file when path contains brackets `[]`

### ISSUE THREAD

**Issue by foxfriends** [cypress-io/cypress#17785]
### Current behavior

When I have a spec file and the path (parent directory in my case) contains square brackets, the tests in that file are not run. Both of these files contain one empty test, but see that for the file with brackets, the test is not found:

![Screen Shot 2021-08-18 at 9 42 18 AM](https://user-images.githubusercontent.com/6126521/129909184-3cd9cb90-5018-4e9a-9d97-5711d6c7b925.png)

This occurs both when running with `run-ct` and `open-ct`.

### Desired behavior

The tests in all files found should be run! 

### Test code to reproduce

See this repo where the above example was produced: https://github.com/foxfriends/cypress-bug. Should be able to just `npm install` and `npx cypress run-ct` and see it does not detect the tests in that one file.

### Cypress Version

8.3.0

### Other

This reminds me of the other issue before with spaces in the file name: https://github.com/cypress-io/cypress/issues/16278

This is particularly relevant when trying to use cypress with Svelte + Sapper (and SvelteKit too when that comes out) as the square brackets are used in route paths to denote path variables. When attempting to write tests for components defined alongside routes, I am unable to run them.

**Comment by JessicaSachs** [comment]
Thanks for this issue report. We'll investigate shortly.

**Comment by rwitchell** [comment]
this is also problematic when using a framework where we have: `src/pages/user/[id].js` and `src/pages/user/[id].test.js`. 

getting error: 

> Error: ENOENT: no such file or directory, stat '~/Library/Application Support/Cypress/cy/production/projects/frontend-bce6a735a06cc119252b612f24b6/bundles/src/pages/user/[id].test.js'

**Comment by JessicaSachs** [comment]
@foxfriends can you test with the latest version of `@cypress/webpack-dev-server`?

**Comment by foxfriends** [comment]
Worked for me! Thanks
