### ISSUE TITLE
8.2.0 - 9.5.3 Example files always created

### ISSUE THREAD

**Issue by saschwarz** [cypress-io/cypress#17789]
### Current behavior

Since I've upgraded to Cypress 8.2.0 every time I launch cypress via:
`npx cypress open --project path-to-existing-project` 

I get the banner `We've created some sample test files that demonstrate key Cypress concepts to help you get started.` 

I click: `No thanks, delete example files` and then the next time I launch cypress the same banner appears. How can I permanently disable this?

### Desired behavior

Example files should not get created for existing projects

### Test code to reproduce

Unfortunately, I can't share our repo. I'm assuming this happens whenever cypress is run from a directory above the `--project` directory

### Cypress Version

8.2.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

Is this still happening with the latest version?

**Comment by saschwarz** [comment]
@sainthkh Yes. I just confirm it is still happening with Cypress 9.5.3:

![Screen Shot 2022-04-04 at 8 17 31 AM](https://user-images.githubusercontent.com/184171/161552251-6c42e715-0198-46c1-82ee-d3a588dcfdee.png)
