### ISSUE TITLE
Type to input field within iFrame not working (cont.)

### ISSUE THREAD

**Issue by MichaelBaySAP** [cypress-io/cypress#17782]
### Current behavior

Hi Jessica,

This is related to https://github.com/cypress-io/cypress/issues/17731#event-5172165800.

I have tried your code. I have omitted the should block and I tested with input.length === 2.

I still only receive a Chainer Object and no text is typed.
![image](https://user-images.githubusercontent.com/40032066/129894427-eb66a3f3-c4a9-4bdc-9c92-e3a52cecc896.png)

cy.get('div.[..]-dialog__body.svelte-1r5o48z > div > iframe ').invoke('contents').then((doc) => { const inputs= doc.find('input'); cy.wrap(inputs[1]).type('test', {force: true});

Best, Michael

### Test code to reproduce

cy.get('div.[..]-dialog__body.svelte-1r5o48z > div > iframe ').invoke('contents').then((doc) => { const inputs= doc.find('input'); cy.wrap(inputs[1]).type('test', {force: true});

### Cypress Version

8.2.0

**Comment by sainthkh** [comment]
Closing because of the inactivity.
