### ISSUE TITLE
Cypress does not type in all the letters before moving on

### ISSUE THREAD

**Issue by techkymoni2021** [cypress-io/cypress#17783]
### Current behavior

Cypress does not type in all the letters before moving on. It is not entering full text in fields & hence the expected result is different from actual. This is frequent & inconsistent (getting frequently but different tests where this code is invoked ) error i am getting while trying to enter text in fields. I even tried to use some wait time (which isn't recommended), still the errors are seen.
Here is the error message -

![cypress_error](https://user-images.githubusercontent.com/89133935/129880211-e9914e4b-6084-46a4-a4ad-d7e58a8ef432.JPG)

### Desired behavior

Whatever input text the test is proving that should be entered in fields on the form. This is happening most of the times but one test in every execution fails with above mentioned error ( there are 10 such tests which enters text in empty fields on form). so the failures are once in every 10 test in every execution.

### Test code to reproduce
```js
When(`I enter text in the fields on form`, function (table) {
for(var row of table.raw()) {
    var field = row[0];
    var value = row[1];
    cy.findByLabelText(field)
        .focus().type('x').clear() 
        .type(value).should('have.value', value)
    cy.wait(1000)
}
});
```
### Cypress Version

7.6.0

### Other

I even tried to use a workaround for cypress as it does not type in all the letters before moving on.

**Comment by jennifer-shehane** [comment]
Can you click on the `type` command in the Command Log? It will print to the console in your DevTools. It prints a table of each character typed and where it was typed. Can you respond with a screenshot of that console.table? Usually this occurs because the input has lost focus mid-type, where something in the application calls focus aware.

**Comment by techkymoni2021** [comment]
Hi Jennifer,
Attaching few screenshots. Please note the error seen this time was on different field , as stated in my original post these errors are frequent & inconsistent -

![cypress_reply4](https://user-images.githubusercontent.com/89133935/130234430-7caa399e-d9a4-4a38-b184-f3b58d906488.JPG)
![cypress_reply3](https://user-images.githubusercontent.com/89133935/130234434-0df5b8e6-b0f2-4daa-a23e-c2b83413fef8.JPG)
![cypress_reply2](https://user-images.githubusercontent.com/89133935/130234437-62c37b71-ae09-45cc-9828-bd2bc5a1a1cf.JPG)
![cypress_reply1](https://user-images.githubusercontent.com/89133935/130234439-d47b529b-c108-4428-829c-b724b25bd369.JPG)

**Comment by techkymoni2021** [comment]
Attaching one more after -->
Click on **type** cmd -> click on _Print to console_  ->this is the output

![cypress_reply5](https://user-images.githubusercontent.com/89133935/130235056-682ec4cf-ce66-400d-8c8c-097d56adc7eb.JPG)

**Comment by techkymoni2021** [comment]
Please can someone guide me on this issue
