### ISSUE TITLE
Missing types for clientCertificate

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#17799]
### Current behavior

There is a `clientCertificates` option. https://docs.cypress.io/guides/references/client-certificates#Syntax

It should include in the type definitions: https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L2491

### Desired behavior

Included in types.

### Test code to reproduce

```ts
const C: Cypress.ResolvedConfigOptions = {
  clientCertificates: // <- no completion or hint
}
```

### Cypress Version

8.0.0

### Other

This is a good first issue for a new contributor or a new employee. Although adding the type is simple enough, it's a good way to learn how to set up Cypress locally, make a PR, get a review, etc. Let's encourage a new contributor to take this one.

**Comment by Jayita10** [comment]
I want to work on this issue

**Comment by JessicaSachs** [comment]
> I want to work on this issue

Go for it @Jayita10. Do you need anything?

**Comment by Jayita10** [comment]
Hi, I'm not able to understand the type definitions part, How should I proceed with this

**Comment by JessicaSachs** [comment]
You'd need to open the file Lachlan linked and add the types for the clientCertificate field. There are examples in that file.

**Comment by Et-008** [comment]
Hi, is this issue still open?
if yes, I'd like to work on it, thanks.

**Comment by aashish0909** [comment]
Hey, is this issue still open?

**Comment by lmiller1990** [comment]
@aashish0909 the work has been completed in #18028 so it will be closed soon and marked as done.

If you are looking for some good first issues, I can probably tag you in a few, if you like.

**Comment by aashish0909** [comment]
@lmiller1990 Yeah, please do. It will be really helpful.
