### ISSUE TITLE
Add JUnit XML Reporter to Cypress

### ISSUE THREAD

**Issue by pihish** [cypress-io/cypress#178]
When you're running Cypress through the command line, we can only generate outputs in JSON format right now.  We need to be able to generate the same outputs in JUnit XML format.  This is the standard output format for Jenkins.

There's a Mocha JUnit reporter available [here](https://github.com/michaelleeallen/mocha-junit-reporter)

**Comment by brian-mann** [comment]
@chrisbreiding and I have been working on it and you'll see this release pretty soon.

**Comment by chrisbreiding** [comment]
This will be supported soon along with [any custom reporter](https://github.com/cypress-io/cypress/issues/231).

**Comment by brian-mann** [comment]
Fixed in [`0.17.5`](https://github.com/cypress-io/cypress/wiki/Changelog#0175-10022016).
