### ISSUE TITLE
existingSession.setup is not a function

### ISSUE THREAD

**Issue by testingJava2** [cypress-io/cypress#17806]
### Current behavior

For a login logic where cy.session() is used, along with the validate option, the below error is thrown by Cypress when the validation of the session fails.
Following this, the session is not recreated, and the old, invalid session is used, failing the test.
![image](https://user-images.githubusercontent.com/64204907/130081894-2bdc0f79-fa7e-4494-a142-437cf4bb37c8.png)

### Desired behavior

The cy.session() validate option should work as expected, recreating the session in case the validation fails.

### Test code to reproduce

Create a session for which the validation will fail; the above error should be ecountered; session will not be recreated.

### Cypress Version

8.3.0

### Other

N/A

**Comment by Lasidar** [comment]
Looks like you and I are having the same issue: https://github.com/cypress-io/cypress/issues/17805! Hopefully we get a response soon :)

**Comment by testingJava2** [comment]
Issue is duplicate of #17805. Closing this BUG as we're tracking progress on #17805
