### ISSUE TITLE
Cypress session validation failure results in a 'existingSession.setup is not a function' error

### ISSUE THREAD

**Issue by Lasidar** [cypress-io/cypress#17805]
### Current behavior

While using the new experimental feature _sessions_ in cypress 8.2.0, adding a session validation routine does not seem to work correctly. Specifically, when a session exists, but the validation routine returns false, an error is thrown saying that the setup function does not exist.

Here is a sample block of code that can reproduce this issue:
![Screenshot from 2021-08-19 09-53-14](https://user-images.githubusercontent.com/32787297/130082019-f1a174fa-e5aa-4175-8575-d64dbc09efea.png)

When running this for the first time:
![Screenshot from 2021-08-19 09-52-29](https://user-images.githubusercontent.com/32787297/130082229-8bd6b4e2-3516-4419-9618-a45f9338d78d.png)

When re-running this test:
![Screenshot from 2021-08-19 09-52-45](https://user-images.githubusercontent.com/32787297/130082274-fa010203-65eb-4d89-8227-a05d7efce3e2.png)

### Desired behavior

Cypress should fail the validation, and re-run the setup function as specified in the docs. For some reason, the current code somehow loses the setup function when validation fails.

### Test code to reproduce

```js
  it('fails the session setup on the second run', () => {
    var validateFlag = false
    cy.session('test', () => {
      validateFlag = true
      cy.log('setup')
    },
    {
      validate() {
        cy.log('validate')
        if (validateFlag) {
          return true
        }
        else {
          return false
        }
      },
    })
  });
```

### Cypress Version

8.2.0

**Comment by Bkucera** [comment]
Thanks, the `existingSession.setup` error is definitely a bug. This might be an issue related to retries, if you turn off retries do you get the same error?

However the test should still fail, that is expected. In order to prevent an endless loop if your `validate` function always returns false, we fail the test if we have just initialized the session via the `setup` function.
https://docs.cypress.io/api/commands/session#The-command-log
> Note that in cases where the validate function fails immediately after setup creates the session, the test will fail with an error.

We should improve the error message to explain this to the user

**Comment by Lasidar** [comment]
@Bkucera disabling retries does not seem to make a difference

**Comment by testingJava2** [comment]
Hello @Bkucera - same as @Lasidar, disabling retries did not change anything for me either.

Same concern here, not a problem that this is failing, it's normal in the end - but the recreation process for a new session is never initiated because of the `existingSession.setup is not a function` error.

**Comment by alvaromartmart** [comment]
I can confirm this is an issue. It basically renders the validate function useless 😅 until this is fixed.

**Comment by bahmutov** [comment]
Also hit this problem

**Comment by bahmutov** [comment]
Few stack screenshots, seems the `setup` suddenly becomes a `fn.toString()` output. Is this serialized somewhere?

<img width="467" alt="Screen Shot 2021-09-28 at 15 58 31" src="https://user-images.githubusercontent.com/2212006/135157739-4e8ea261-934b-4c78-b2dc-54b581647e38.png">

<img width="1026" alt="Screen Shot 2021-09-28 at 15 58 52" src="https://user-images.githubusercontent.com/2212006/135157815-d557a25c-3c0b-4dbc-ad2b-66e778fef61b.png">

**Comment by bahmutov** [comment]
Maybe in https://github.com/cypress-io/cypress/blob/2caa5de2c58dd3d16ba03729a6004d2e6335ccb5/packages/driver/src/cy/commands/sessions.ts#L609-L615 

We might need to omit `setup` from serialized properties, otherwise when restored the string overwrites the original callback

**Comment by bahmutov** [comment]
Ohh, it was a little bit lower in

https://github.com/cypress-io/cypress/blob/2caa5de2c58dd3d16ba03729a6004d2e6335ccb5/packages/driver/src/cy/commands/sessions.ts#L807-L810

Patching it to be 
```js
if (serverStoredSession && serverStoredSession.setup === existingSession.setup.toString()) {

            lodash__WEBPACK_IMPORTED_MODULE_0___default.a.extend(existingSession,
              lodash__WEBPACK_IMPORTED_MODULE_0___default.a.omit(serverStoredSession, 'setup'));
```
fixed my problem

**Comment by ComicScrip** [comment]
Had the same issue, any news on this ?

**Comment by eLarocque** [comment]
Same issue here. Providing the `validate` function is useless until this is fixed. 
I know this is an experimental feature (and a great one at that!) but would love this issue prioritized :)
Thanks!

**Comment by DanaGoyette** [comment]
In my case, since I haven't generally had sessions become invalid in the middle of the run, I can work around it by clearing all sessions at the start of the run.  In `support/index.ts` or `support/index.js`:

```
before(() => {
  /**
   * Workaround for https://github.com/cypress-io/cypress/issues/17805
   * @see https://docs.cypress.io/api/commands/session#Explicitly-clearing-sessions
   */
  Cypress.session.clearAllSavedSessions()
})
```
