### ISSUE TITLE
should('have.value', expected) succeeds when value is undefined

### ISSUE THREAD

**Issue by JamShady** [cypress-io/cypress#17809]
### Current behavior

I'm building an app where the components on the page are loaded on demand, i.e. it can be a little slow to load.

At the start of my test, I have the following
```cy.get('form#personal input#name').should('have.value', name)```

However, when running this test, there was a failure experienced at this point. However, the test runner indicated it as a pass. The remaining assertions were not executed (so it did bail out of the test) but it was otherwise indicated as a pass in that (a) it was coloured green, and (b) it was marked as completing successfully

The error was exactly like this, but the assertion had turned green, the completed test indicated incremented and it had moved on to the next test (all the remaining tests completed successfully)
![image](https://user-images.githubusercontent.com/167395/130103244-58ba6c80-e404-4efa-bd1a-06ec33b2e3a1.png)

The test likely failed because the elements didn't load/render in time to meet the timeout Cypress was configured for (15s)

I'm sorry I didn't get a screenshot of when it happened, it disappeared/fixed after a refresh.

### Desired behavior

Cypress should have recorded it as a failure

### Test code to reproduce

It was intermittent (it happened twice), but the code hadn't changed so not sure what to advise here to help diagnose the problem.

### Cypress Version

8.3

**Comment by JessicaSachs** [comment]
Thanks for opening an issue. Can you add a reproduction repository that shows the bug?

**Comment by JamShady** [comment]
@JessicaSachs how do I do that when it's an intermittent issue that seems to be related to how quickly Cypress can load the page (which itself depends on other factors)?

**Comment by sainthkh** [comment]
One solution is to use `cy.wait()` to wait for loading and test things after that. 

And we can use `cy.get('#el').should('not.have.value', undefined)` to make it fail.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
