### ISSUE TITLE
Browser detection takes twice as long during `cypress open-ct` than `cypress open`

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#17808]
### Current behavior

When running `cypress open-ct`, the browsers are being detected twice making it take twice as long. 

Related but will not fix the double browser detection issue: https://github.com/cypress-io/cypress/pull/17807

### Test code to reproduce

`cypress open-ct` - track the time is takes during DEBUG logs of the browser detection.

### Cypress Version

8.3.0

**Comment by JessicaSachs** [comment]
I'm marking this as wontfix because we're rewriting this logic, and #17807 makes the perf difference negligible.
