### ISSUE TITLE
Pass 'Details" via CLI to run instead of getting from commit

### ISSUE THREAD

**Issue by mspanish** [cypress-io/cypress#1781]
This would be a great feature, as we use Cypress in a team, and it would enable others to see what the latest test I added was. I try to do this by committing using a name that will point them to what the most recent test was, but sometimes I commit other stuff and then that string shows up under DETAILS for that  run.

**Comment by jennifer-shehane** [comment]
I'm unclear about what feature you are specifically asking for in this issue. What exact details do you want to pass to the CLI?

**Comment by mspanish** [comment]
Hi sorry I posted this a long time ago - but I think I wanted to post the details that show up in the dashboard with each run - so you could personalize the message attached to that run, rather than just pulliing it from the commit.  For example, you may have fixed a typo - so that would be your commit message, but your run message could read "new run for testing modal windows" or something like that.

**Comment by jennifer-shehane** [comment]
Since this request has not gotten a lot of interest over the years, we’ll close this issue.
