### ISSUE TITLE
Show dynamic request aliases in the command log

### ISSUE THREAD

**Issue by xeger** [cypress-io/cypress#17819]
### What would you like?

When I assign an alias from my `cy.intercept()` route handler, I want it to show up in the command log just as if I had aliased the route using `cy.intercept().as()`.

### Why is this needed?

The command log is extremely useful to understanding test execution and control flow, and without a clear link between the route table and an XHR made by my app, it can be difficult for developers  to understand what happened.

### Other

To reproduce the issue, you can run this standalone test:
```js
describe("Dynamic aliasing", function () {
  it("test", () => {
    cy.visit("https://jsonplaceholder.cypress.io/");
    cy.intercept('/todos/1', req => {
      req.alias = 'dynamic';
      req.continue();
    });
    cy.contains('button', 'Try it').click();
    cy.contains('#result', 'delectus aut autem');
  });
});
```

Which results in the XHR having "no alias" in the command log, even though I clearly gave it an alias:
![image](https://user-images.githubusercontent.com/73368/130158784-becc918e-f5cb-4c71-8c19-dac2caab8248.png)

**Comment by andreifg1** [comment]
Its not just the the command log but when assigning dynamic alias, its not working.

Im my case I am trying to alias all the requests to our GraphQL server with the operation name, but it doesn't work.

**Comment by Notorious112** [comment]
Confirmed, the following won't work:

```
  cy.intercept('/modelYear/*', (req) => {
    req.alias = 'myRequest';
  });
```

**Comment by Notorious112** [comment]
@andreifg1 
Instead of 
`  cy.intercept('/users/*****', (req) => {
    req.alias = 'users';
  });
`
try
`  cy.intercept('/users/******', (req) => {
    req.alias = 'users';
  });
`

**Comment by andreifg1** [comment]
@Notorious112 In my case its like this:
```
cy.intercept("POST", "/graphql", (request) => {
    request.alias = request.body.operationName;
});
```

But even the most basic use case doesn't work:
```
  cy.intercept("POST", "/**", (request) => {
    request.alias = "test";
  });
```

**Comment by bahmutov** [comment]
Confirmed, the alias is there, just not shown in the command log

**Comment by DamienCassou** [comment]
Same here

**Comment by ekeijl** [comment]
It seems I can neither use `cy.wait('@test')` on the dynamic alias.

**Comment by andreifg1** [comment]
@bahmutov This cause our company major issues while working with graphql, is there an estimate it its goling to be fixes anytime soon?

**Comment by andreifg1** [comment]
> Well, you might submit a pull request and that way it will be fixed soon
> […](#)
> Sent from my iPhone
> On Oct 13, 2021, at 06:57, andreifg1 ***@***.***> wrote: ﻿ @bahmutov This cause our company major issues while working with graphql, is there an estimate it its goling to be fixes anytime soon? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I could but this is such a huge issue for everyone who is using Cypress with GraphQL so I (maybe wrongly) expect it to be high priority issue.

**Comment by ShaunWangGo** [comment]
Here's a workaround:
Use `Cypress.log` in the `cy.intercept`.
`Cypress.log` runs syncrounously, so the log appears directly below the request, which is good enough for identifying which graphql request is which.
https://docs.cypress.io/api/cypress-api/cypress-log#Syntax

```
cy.intercept("POST", {graphql url}, (req) => {
    const { body } = req;
    if (body.hasOwnProperty("operationName")) {
      Cypress.log({
        name: "Log GraphQL Request",
        message: body.operationName,
      });
    }
  });
```
