### ISSUE TITLE
cy.request doesn't support dynamic body value

### ISSUE THREAD

**Issue by listana** [cypress-io/cypress#17825]
### Current behavior

Try to run cy.request several times with different bodies:
{
    "setAsRejected": {}
}

{
    "setAsDone": {}
}

{
    "setAsReview": {}
}
and so on...
Request failes with 514 error

### Desired behavior

if i use the constant body value, request is OK:
body: {"setAsDone": {}},

### Test code to reproduce

   let toStatus = ['Done'/*, 'Rejected'*/]

    ;toStatus.forEach((new_status) => {        
        it('Перейти в статус: ' + new_status, () => {
            var command = '"setAsDone": {}'
            cy.log(command)
            cy.request({
                method: 'PATCH',
                url: `${cameras}/v2/entities/${last_created_usertask_id}/attrs?options=keyValues&type=UserTask`,
                body: `{${command}}`,
                // body: {"setAsDone": {}},
                contentType:'application/json'          
            }).its('status').should('equal', 204) 
        })
    })

-----------------------------------------------------------
Body: {'setAsDone': {}}

-----------------------------------------------------------

The response we got was:

Status: 415 - Unsupported Media Type

### Cypress Version

Cypress package version: 7.6.0 Cypress binary version: 7.6.0 Electron version: 12.0.0-beta.14 Bundled Node version: 14.15.1

**Comment by sainthkh** [comment]
Confirmed that it doesn't work with the tests below:

```js
it(`string`, () => {
  let command = '"setAsDone": {}'

  cy.request({
    url: `/status-code?code=204`,
    body: `{${command}}`,
    contentType: 'application/json',
  }).its('status').should('equal', 204) // fail
})

it(`obj`, () => {
  cy.request({
    url: `/status-code?code=204`,
    body: { 'setAsDone': {} },
    contentType: 'application/json',
  }).its('status').should('equal', 204) // pass.
})
```

**Comment by sainthkh** [comment]
Workaround: Use `JSON.parse` like below:

```js
body: JSON.parse(`{${command}}`)
```

**Comment by sainthkh** [comment]
I was wrong. According to [the cy.request doc](https://docs.cypress.io/api/commands/request#Syntax), there is no `contentType` option. To use `content-type`, use `headers` option instead like below:

```js
it(`string`, () => {
  let command = '"setAsDone": {}'

  cy.request({
    method: 'PATCH',
    url: `/status-code?code=204`,
    body: `{${command}}`,
    headers: {
      'content-type': 'application/json',
    },
  }).its('status').should('equal', 204)
})
```
