### ISSUE TITLE
Not able to monitor real-time execution through the Cypress UI mode

### ISSUE THREAD

**Issue by dhuriaditi1** [cypress-io/cypress#17826]
### Current behavior

Not able to monitor real-time execution through the Cypress UI mode. This was working till last week. However, now I don't see the UI for the AUT on the right-hand side.
I have tried changing the viewport values, but it did not work.

### Desired behavior

The AUT UI should open on the right-hand side

### Test code to reproduce

Generic Cypress error on Mac Big Sur. 

### Cypress Version

6.8.0 , 8.3.0

**Comment by sainthkh** [comment]
Maybe related with #9195
