### ISSUE TITLE
Validate configuration values coming from the CLI or env vars

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1783]
We currently validate `config.json` settings to ensure they of the correct types.

However if you override these configuration values through env vars like `CYPRESS_BASE_URL` or `cypress run --config baseUrl=foo` we don't validate those.

We should additionally validate these after merging in overrides.

**Comment by bahmutov** [comment]
Hmm sounds like a job for a json schema!

**Comment by brian-mann** [comment]
We already do the validation, but we do it before merging in values coming from the CLI or Env Vars - so those are potentially missed.
