### ISSUE TITLE
bug in proccessing symbol " in request body

### ISSUE THREAD

**Issue by listana** [cypress-io/cypress#17830]
### Current behavior

Cannot place into varibale body with symbol "
In console request is logged like:
```
Request Body: "{\"setAsDone\":{}}",
```

I tryed to escape symbol ", but that did not help:
```
var command = "{\"setAsDone\":{}}"
```
...
 body: command,

### Desired behavior

use variable in body value, even if body contains symbol "

### Test code to reproduce
```js
var command = "{\"setAsDone\":{}}"                         
            cy.log(command)
            cy.request({
                method: 'PATCH',
                url: `${cameras}/v2/entities/${last_created_usertask_id}/attrs?options=keyValues&type=UserTask`,
                // body: `{\'${command}\':{}}`,
                // body: {command: {}},
                body: command,
                // body: {"setAsDone": {}},
                contentType:'application/json',
                         
            }).its('status').should('equal', 204)
```
### Cypress Version

Cypress binary version: 7.6.0

**Comment by sainthkh** [comment]
This should be revisited after solving #17825. `"` might not be a problem, but the #17825 is.

**Comment by sainthkh** [comment]
I guess `"` is not the problem. It's because `contentType` option doesn't exist in `cy.request`.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
