### ISSUE TITLE
Cypress Docker Images: Chrome sometimes fails to launch with error: Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by matthemsteger** [cypress-io/cypress#17835]
### Current behavior

The symptom is that on our dashboard, the run will time out after 1.5 hours with the status never being reported. When looking at the docker container, it just says that 

```
Failed to connect to Chrome, retrying in 1 second (attempt 61/62)
Failed to connect to Chrome, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.
This usually indicates there was a problem opening the Chrome browser.
The CDP port requested was 39369.
Error details:
Error: connect ECONNREFUSED 127.0.0.1:39369
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

I enabled some additional debug information with `DEBUG=cypress:server:util:process_profiler,cypress:server:browsers,cypress:launcher` to get a better idea of what was happening when the docker container did `cypress run`.

Now it appears the root cause of the issue is:

```
2021-08-20T12:19:19.870Z cypress:launcher chrome stderr: Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
2021-08-20T12:19:19.876Z cypress:launcher chrome exited: { code: 127, signal: null }
```

I found an issue in `playwright` where they had to enable retries https://github.com/microsoft/playwright/issues/5214 because this is an upstream issue. Its mentioned that puppeteer stumbled on this .. https://github.com/puppeteer/puppeteer/issues/2207. When I look at that research, it is an upstream issue in a linux package. When looking at the upstream issue (https://sourceware.org/bugzilla/show_bug.cgi?id=19329) and the root cause (a race condition in a library) .. it looks like it was fixed in may. Maybe cypress needs to update containers OS packages?

### Desired behavior

If cypress cannot update the package that seems to root cause this, I would like cypress to do the same workaround as playwright and retry.

### Test code to reproduce

There is not a reliable way to reproduce this. It is intermittent based on what appears to be a race condition in a library used by chrome.

### Cypress Version

8.3.0

### Other

We are using `cypress/browsers:node14.17.0-chrome91-ff89` as our container base. Here is the command .. `ONBUILD CMD ./wait-for-it.sh $BASE_URL/health && DEBUG=cypress:server:util:process_profiler,cypress:server:browsers,cypress:launcher $(yarn bin)/cypress run --headless --browser chrome --record --parallel --ci-build-id=$CI_BUILD_ID --config baseUrl=$BASE_URL`

**Comment by jennifer-shehane** [comment]
Yeah, we likely will want to retry launching the browser in this case. Thanks for the investigative work. We’d be open to reviewing a PR implementing a retry.

**Comment by jennifer-shehane** [comment]
Yeah, we likely will want to retry launching the browser in this case. Thanks for the investigative work. We’d be open to reviewing a PR implementing a retry.
