### ISSUE TITLE
add `ToDo` helper function

### ISSUE THREAD

**Issue by distante** [cypress-io/cypress#17840]
### What would you like?

I am asking for a concise and clear way to mark a test as pending using something like `it.todo('I have to be implemented')`

### Why is this needed?

When I write unit tests (using jest), I first lay out what my function should behave like:

```
describe('#sumTwoNumber', () => {
   test.todo('throws if the first param is not a number');
   test.todo('throws if the second param is not a number');
   test.todo('sums the first param plus the second params');
});
```

Then I start to implement one of the tests, then the function, and repeat.

I would like to do something similar with the e2e tests, I want to define a list of test descriptions so I can have a mental map of what I have to do, then start implementing tests + views.

**Comment by bahmutov** [comment]
No need for todo. Use tests without callback functions or it.skip to get what you want https://glebbahmutov.com/blog/cypress-test-statuses/

**Comment by distante** [comment]
Oh, I miss it. Thank you.
