### ISSUE TITLE
Component Tests hang indefinitely when using webpack-dev-server@4.0.0

### ISSUE THREAD

**Issue by anark** [cypress-io/cypress#17846]
### Current behavior

After upgrading my project to use webpack-dev-server@4.0.0(previously 3.11.2) and running `yarn cypress open-ct` the component test are not started and the runner waits indefinitely.

I am using `loadWebpack` via cypress/plugins/index.js as follows

```
  if (config.testingType === 'component') {
    require('@cypress/react/plugins/load-webpack')(on, config, { webpackFilename: 'config/webpack/base.js' })
  }
```

### Desired behavior

The component tests run the same way they did when using webpack-dev-server@v3

### Test code to reproduce

Use https://github.com/anark/cypress-react-component-example and run the following
```
yarn
yarn cypress open-ct
```

This is a fork of https://github.com/bahmutov/cypress-react-component-example with the only change being the upgrade to webpack-dev-server 4.  They ran when using webpack-dev-server 3 but hang when trying with webpack-dev-server 4

### Cypress Version

8.3.0

### Other

I believe it is waiting on the dev server on the wrong port.  When I run `yarn cypress open-ct` I see a message that states

```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/project/public' directory
```

When using v4 the port is always 8080.  This port was random when using webpack-dev-server v3

When using webpack-dev-server@3 the port changed every run and the message was
```
ℹ ｢wds｣: Project is running at http://localhost:62147/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /__cypress/src
ℹ ｢wds｣: Content not from webpack is served from /project
```

**Comment by BBB** [comment]
Looks like the assumption here is incorrect: https://github.com/cypress-io/cypress/blob/0cea625f359ef554e87600ef7e7c3afa4e36da4d/npm/webpack-dev-server/src/index.ts#L23 listen does return a promise, but it doesn't resolve to a value. https://github.com/webpack/webpack-dev-server/blob/804b86836a691290dd71ef75dc3d6893b3ed3209/lib/Server.js#L1894

**Comment by lmiller1990** [comment]
I had this working with WDS v4 as of https://github.com/cypress-io/cypress/pull/16414. At that time it was still alpha and the API was not stable.

It looks like there's a stable 4.0.0 now, so we should revisit this and make sure it's working correctly. I can look into this sometime during the week, but if someone else wants to give it a try, happy to help out!

We need a good strategy to run our test suite against both v3 and v4. I'm not sure how to handle this, yet.

**Comment by snoozbuster** [comment]
Having the same issue with webpack-dev-server@4. Was able to resolve the cypress hang by locking to `webpack-dev-server@4.0.0-beta.3`. Downgrading to 3.x isn't an option as the version of http-proxy-middleware it includes is much too old for what I'm doing. Hope this gets fixed soon!

**Comment by BBB** [comment]
I have a WIP of support here: https://github.com/BBB/cypress/tree/webpack-dev-server-v4
