### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGABRT on Chrome 92 headless and Cypress Version 8.3.0

### ISSUE THREAD

**Issue by veronicamirada** [cypress-io/cypress#17849]
### Current behavior

I am having troubles to run Cypress tests not only on my Jenkins machine but also on my laptop running them locally. 
It happened only sometimes but after upgrading to 8.3.0 I think it happens more often. 

The execution gets stuck at some point as Cypress gives the SIGABRT signal. 

I have seen https://github.com/cypress-io/cypress/issues/8865 issue, but it referrs to Electron, and it happens to me also in Chrome. 

```
12:37:57   Running:  parental-control/contents-rating.spec.js                                      (35 of 65)
12:38:19 
12:38:19 
12:38:20   Parental Control - Contents - Full HD
12:48:20 Build timed out (after 10 minutes). Marking the build as aborted.
12:48:20 Xvfb stopping
12:48:20 Build was aborted
12:48:21 Archiving artifacts
12:48:22 Cypress error Error: The Test Runner unexpectedly exited via a exit event with signal SIGABRT
12:48:22 
12:48:22 Please search Cypress documentation for possible solutions:
12:48:22 
12:48:22 https://on.cypress.io
12:48:22 
12:48:22 Check if there is a GitHub issue describing this crash:
12:48:22 
12:48:22 https://github.com/cypress-io/cypress/issues
12:48:22 
12:48:22 Consider opening a new issue.
12:48:22 
12:48:22 ----------
12:48:22 
12:48:22 Platform: linux (Ubuntu - 18.04)
12:48:22 Cypress Version: 8.3.0
```

### Desired behavior

Test runs properly until the end

### Test code to reproduce

It happens on several tests

### Cypress Version

8.3.0

**Comment by alexandrabusu** [comment]
I have the same problem...

**Comment by bukharov** [comment]
I get this when I close Cypress normally (via Cmd+Q or by clicking on the X).

<img width="251" alt="Screen Shot 2021-08-24 at 6 14 23 PM" src="https://user-images.githubusercontent.com/49371/130697163-8e5eaf3e-963c-44a6-8961-eb402204eead.png">

And then there's this in the console:

```
Error: The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (20.5.0)
Cypress Version: 8.3.0
    at /Users/deniz/Work/cwealth-frontend-mono/node_modules/cypress/lib/errors.js:257:17
    at tryCatcher (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/deniz/Work/cwealth-frontend-mono/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  known: true
}
```

**Comment by bblwbtd** [comment]
I also have this problem. Are there any temporary solutions?

**Comment by peeyushohri04** [comment]
I am also facing the same issue , since upgrading to cypress  8.3.0

**Comment by romankhomitskyi** [comment]
Same issue on 8.3.1
![Screenshot 2021-08-30 at 10 49 14](https://user-images.githubusercontent.com/57874507/131304870-e3ac2630-90e1-4ec9-b97f-397b4c9648e8.png)

**Comment by skambo** [comment]
Getting a similar error on `8.3.0` when running tests locally

```
Opening Cypress...
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (19.6.0)
Cypress Version: 8.3.0
```

**Comment by romankhomitskyi** [comment]
I solved this issue by stop throwing DISPLAY and x11 socket. So that xvfb inside the docker understands that there is no need to send anything anywhere, and dealing with display virtualization on its own.

**Comment by romankhomitskyi** [comment]
You could try searching for XQuarts

**Comment by tommy0831** [comment]
> 

@romankhomitskyi Can you give more details?  What do you mean by stop DISPLAY and x11 socket?  What commands did you run?

**Comment by romankhomitskyi** [comment]
> > 
> 
> @romankhomitskyi Can you give more details? What do you mean by stop DISPLAY and x11 socket? What commands did you run?

I was getting this error when trying to run cypress in docker container with UI test runner, so I needed to pass x11 as a volume and display as variable to get it worked
So I just removed them because I run cypress heedless now

**Comment by tommy0831** [comment]
> > > 
> > 
> > 
> > @romankhomitskyi Can you give more details? What do you mean by stop DISPLAY and x11 socket? What commands did you run?
> 
> I was getting this error when trying to run cypress in docker container with UI test runner, so I needed to pass x11 as a volume and display as variable to get it worked So I just removed them because I run cypress heedless now

Yes.  I can confirm that running headless works.  The problem is running with --headed option.
