### ISSUE TITLE
Cypress 8.2.0 running error with using cy.session(): Cannot call cy.session() outside a running test.

### ISSUE THREAD

**Issue by thoinguyen249** [cypress-io/cypress#17841]
### Current behavior

![image](https://user-images.githubusercontent.com/68260035/130353379-a5854a23-4192-4c42-a195-b15890768ef8.png)

### Desired behavior

When I running test, the error displays that it only use cy.session within it(...), but in the docs I see no where said about this.
If I remove cy.session, test can run normally.

### Test code to reproduce

```js
Cypress.Commands.add(
  "registerUserCaseSensitive",
  cy.session(({ emailAddress, password, firstName, lastName }) => {
    cy.getDataCy("ModalSignUp-emailBtn").click();
    cy.getDataCy("modalSignUpForm-firstName")
      .should("be.visible")
      .type(firstName);
    cy.getDataCy("modalSignUpForm-lastName")
      .should("be.visible")
      .type(lastName);
    cy.getDataCy("modalSignUpForm-email")
      .should("be.visible")
      .type(emailAddress.toUpperCase());
    cy.getDataCy("modalSignUpForm-password")
      .should("be.visible")
      .type(password);
    cy.getDataCy("modalSignUpForm-confirmBox").should("be.visible").click();

    cy.getDataCy("ModalSignUpForm-submitBtn").click();

    cy.waitStatusIs200("@register");
  })
);
```

### Cypress Version

8.2.0

**Comment by jennifer-shehane** [comment]
You have to call your custom command within an `it()`. You cannot call `cy.session` or ANY command within Cypress outside of an `it()` block as the error states.
