### ISSUE TITLE
cy.log ignores casing on variable names

### ISSUE THREAD

**Issue by monkpit** [cypress-io/cypress#17862]
### Current behavior

When logging an object, Cypress converts all property names (not values) to lowercase in the Cypress log window.

![image](https://user-images.githubusercontent.com/5297293/130523434-a9c436dd-0f01-45a9-96cd-575e89a78024.png)

### Desired behavior

Honor the casing of the variable names as they are in the object itself.

### Test code to reproduce

```javascript
describe("Cypress", () => {
    it("can log an object", () => {
        const confirmationNumber = "ABC123";
        const ConfirmationNumber = "abc123";
        
        cy.log({
            confirmationNumber,
            ConfirmationNumber
        });
    });
});
```

### Cypress Version

Tested with: 6.9.1, 8.3.0

**Comment by jennifer-shehane** [comment]
We'd be willing to accept a PR to change this behavior.
