### ISSUE TITLE
Ability to add assertions to an xhr

### ISSUE THREAD

**Issue by paulfalgout** [cypress-io/cypress#17861]
### What would you like?

Similar to #16295 it would be nice to be able to click something in the sidebar that would allow for setting an assertion based on a POST/PATCH etc.

### Why is this needed?

It would cut down on non-javascript people needing to know much javascript to add meaningful tests.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
