### ISSUE TITLE
Should use DRONE_SOURCE_BRANCH

### ISSUE THREAD

**Issue by lifeiscontent** [cypress-io/cypress#17860]
### Current behavior

https://github.com/cypress-io/cypress/blob/29b803f54b9a8b5c3b336d3e696d4795276a763e/packages/server/lib/util/ci_provider.js#L503

### Desired behavior

Cypress uses the right branch

### Test code to reproduce

N/A

### Cypress Version

5.6.0

**Comment by lifeiscontent** [comment]
@jennifer-shehane

**Comment by jennifer-shehane** [comment]
We're open to a PR to address this if you can reference the env var for this from Drone's docs or however you found this.

**Comment by lifeiscontent** [comment]
@jennifer-shehane I'm okay with that, is there a possibility of releasing this as a patch version to multiple major versions across cypress? We're specifically needing this for <6 as we haven't ported over our specs yet to intercept API

**Comment by lifeiscontent** [comment]
@jennifer-shehane bump

**Comment by lifeiscontent** [comment]
@jennifer-shehane bump

**Comment by lifeiscontent** [comment]
@jennifer-shehane bump

**Comment by bendapkiewicz** [comment]
+1 very much want to see this change.

**Comment by LeoKotschenreuther** [comment]
+1 would really like to see this.

**Comment by lifeiscontent** [comment]
@jennifer-shehane can we please get a release for versions < 8?
