### ISSUE TITLE
Incorrect document.domain

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#17879]
### Current behavior

In my case – my app is using document.domain to switch enviroment. 
So, when my app is running on internal domain https://my.domain1.domain2.com but cypress changes each document.domain to domain2.com, it use domain1 to change service environment, so document.domain error for service .
As a possible solution - it would be sufficient for me to be able to hard-code desired domain inside tests.

### Test code to reproduce

internal website

### Cypress Version

6.7.0

**Comment by merrywhether** [comment]
I'm having this problem as well. This is the error I get:
```
cypress_runner.js:113978 Blocked a frame with origin "https://app.team.org.com" from accessing a frame with origin "https://app.team.org.com". The frame requesting access set "document.domain" to "org.com", the frame being accessed set it to "team.org.com". Both must set "document.domain" to the same value to allow access.
```

We're working under a shared domain for our organization, which is then split into subdomains by teams which have distinct apps. As a result, we intentionally set `document.domain = team.org.com` to scope cross-app interactions at the team level (we also similarly tighten the cookie domain, etc). This prevents Cypress from interacting with the framed-application.

It would be great if we could specify `documentDomain` in `cypress.json` or something to override the current logic in Cypress.

**Comment by AtofStryker** [comment]
we can likely set the true document domain once we address #24094 and no longer have to set it during injection

**Comment by AtofStryker** [comment]
@mingyixu would you be able to try the [experimentalSkipDomainInjection](https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection)? You should be able to provide a wildcard to the config.
