### ISSUE TITLE
Getting errors using cy.get(...).contains(...).click()

### ISSUE THREAD

**Issue by yonatanaftali** [cypress-io/cypress#17888]
### Current behavior

Currently, when running a test in headless mode, doing `cy.get('element').contains('something').click()` will be completed successfully, however will show up as an error:

![Add Edit Contact - From Other Sections -- Can't edit unsaved OFF-NET number (failed)](https://user-images.githubusercontent.com/57040227/130831595-636f1bce-ba85-47f4-b552-4e0b7137a8d1.png)

 and throw the following error along the way:
`2021-08-25 19:27:57.384 Cypress Helper[66690:816470] In -[NSApplication(NSQuietSafeQuit) _updateCanQuitQuietlyAndSafely], _LSSetApplicationInformationItem(NSCanQuitQuietlyAndSafely) returned error -50`

The issue here for us is it might seem like a flaky test, but it is actually not.

### Desired behavior

In this situation, Cypress shouldn't throw an error.

### Test code to reproduce

`cy.get('element').contains('something').click()`

### Cypress Version

8.3.1

**Comment by yravid** [comment]
I experienced similar behavior, cy.contains failing to find an element which exist and visible, started after I upgraded from 7.6 to 8.3

**Comment by yonatanaftali** [comment]
@jennifer-shehane Can you please go over the information I shared? I'd appreciate  your help with this matter.

**Comment by bahmutov** [comment]
@yonatanaftali try reading the retry-ability guide linked above and use a single `cy.contains` command instead of cy.get+ cy.contains combination

```
cy.contains('[data-cy=call-row]', '(111) 111-1111').click();
```
As another precaution I would add
```
cy.contains('[data-cy=call-row]', '(111) 111-1111').should('be.visible').click();
```
For any more help, please provide the app we can run to see the problem.

**Comment by yonatanaftali** [comment]
@bahmutov I followed your suggestion and it solved our issue. Thanks! Much appreciated!
