### ISSUE TITLE
Cypress is not detecting chrome processes being killed with SIGKILL

### ISSUE THREAD

**Issue by muhammad-st** [cypress-io/cypress#17893]
### Current behavior

Cypress keeps waiting forever when a descendent chrome process is killed with `SIGKILL`.

### Desired behavior

Cypress should detect the killed chrome process (or at least timeout) and closes accordingly.

### Test code to reproduce

1. `cypress run --browser chrome`
2. `htop`
3. find the cypress process in `htop` and look at the process tree.
4. kill the parent chrome process with `SIGKILL`.
5. return to the cypress output.
6. cypress will be still waiting forever.

### Cypress Version

8.3.0

### Other

Sometimes, we find Cypress process trees with Cypress and cypress sub-processes without any `chrome` process and stuck for more than 20 hours.

the latest lines on the log in that case are:
```
    ✓ Should display the correct info on initial page load (11691ms)
    ✓ Should display correctly collapsed and expanded states (12884ms)
    ✓ Should show the correct information with filters engaged (32327ms)
Gdk-Message: 19:51:52.245: Cypress: Fatal IO error 11 (Resource temporarily unavailable) on X server :99.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by emilyrohrbough** [comment]
related to: https://github.com/cypress-io/cypress/issues/18002

**Comment by emilyrohrbough** [comment]
related to: https://github.com/cypress-io/cypress/issues/18885 - there is quite a bit of investigation on this issue.
