### ISSUE TITLE
Add a feature from within cypress that helps with writing to a file

### ISSUE THREAD

**Issue by adokania** [cypress-io/cypress#179]
Currently I am trying to setup my test suite and want to write the response object received into a file in the fixture directory for future comparisons. This helps me bypass the manual process of having to copy the object to a file, which is tedious in any case from the console.

The VCR mode might be an option, but what if I am not using the cy.server directly and have my own tool that is making the request from within cypress. Having an independent writeToFile option would be a good addition imo

**Comment by brian-mann** [comment]
We'll be adding `writeFile` and `readFile` API's sometime in `0.17.x`

**Comment by brian-mann** [comment]
Fixed in [`0.17.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0171-08312016).
