### ISSUE TITLE
Read the PR_NUMBER from an environment variable

### ISSUE THREAD

**Issue by dvlato** [cypress-io/cypress#17913]
### What would you like?

I'd like to be able to pass an environment variable with the PR_NUMBER related to a run, so it is recorded by Cypress. As far as I can tell, we can pass variables such as COMMIT_INFO_BRANCH to pass git related information, but for the PR ID/Number it can only be extracted from the CI engine default env vars.

That seems unfortunate as not all the CI engines record the PR Number (or do it consistently) or are included in Cypress. In our use case, we use a "workflow_dispatch" GH workflow that receives the PR number as an input variable... so we definitely have the value and could set any env var with it, but I don't know how to pass it to Cypress.

If this is doable and I might have misunderstood something, we might want to document it close to where we document git related info?

### Why is this needed?

This would give us greater flexibility in passing in the PR Number without being restricted to default values for each engine.

**Comment by emilyrohrbough** [comment]
@dvlato You can pass an environment variable via the cli with `--env`. See https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_.

**Comment by jennifer-shehane** [comment]
This feature is available and documented here: https://docs.cypress.io/guides/continuous-integration/introduction#CI-Build-Information
