### ISSUE TITLE
[Component Testing] I have an error after running a command cypress run-ct inside docker container: EINVAL: invalid argument, scandir '/proc/41/net'

### ISSUE THREAD

**Issue by Cigan12** [cypress-io/cypress#17926]
### Current behavior

I have an error after running a command cypress run-ct inside docker container: EINVAL: invalid argument, scandir '/proc/41/net', but without docker everything is working fine, 
![image](https://user-images.githubusercontent.com/42859813/131210742-d3b17c1c-371e-4f8c-aa36-1a3df4012941.png)

And after the errors it just stuck.

### Desired behavior

Cypress should run my component tests inside docker))

### Test code to reproduce

https://github.com/Cigan12/vite-cypress-template

### Cypress Version

8.3.1

### Other

This is my Dockerfile - 
![image](https://user-images.githubusercontent.com/42859813/131210944-3f9db288-11c4-495c-9cc4-b6b594160c52.png)

To build image i'm using command - docker build -t vite-tests --target test .  And to run -  docker run --name tests -it --rm vite-tests

**Comment by lmiller1990** [comment]
We reworked CT internally significantly at Cypress v10 - if you upgrade and still have issues, please re-open with a new reproduction and I'll take a look.
