### ISSUE TITLE
BUG: use the readFile api get the json object value,then pass it to cy.get() always timeout

### ISSUE THREAD

**Issue by qileilove** [cypress-io/cypress#1794]
### Is this a Feature or Bug?
BUG 

### Current behavior:
```
 cy.readFile(filePath).its(key)
```
now i use this api to get the value from the json file, the value is the css path
then i pass it to 
```    
cy.get( cy.readFile(filePath).its(key))
```
the result always get timeout

### Steps to reproduce:

```js

```

**Comment by brian-mann** [comment]
This is not a bug, commands are async, you must yield their values.

- https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous
- https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#

**Comment by qileilove** [comment]
@brian-mann thanks for your reply. so the soluation is that use then to handle this issue?can you give me a simple example to me?

**Comment by jennifer-shehane** [comment]
```js
cy.readFile(filePath).its(key).as('fileKey')
cy.get('@fileKey')
```

```js
cy.readFile(filePath).its(key).then((fileKey) => {
  cy.get(fileKey)
})
