### ISSUE TITLE
Component tests fail after component code calls document.location

### ISSUE THREAD

**Issue by twhoff** [cypress-io/cypress#17943]
### Current behavior

If a mounted component redirects to a different path, the Cypress window shows "Cannot GET <path>" and subsequent tests fail.

For example, I am testing that the app redirects to an error page at `/error/401` when the user is not authorised.

The test passes when I use `cy.url().should('contain', '/error/401')`, but the next test does not run because it seems to want to start from `http://localhost:58532/error/401`

If I remove the test which has the component which redirects when the user is not authorised, the path in the Cypress iFrame stays as:
![image](https://user-images.githubusercontent.com/4405822/131509666-a2ad1449-2ce5-4c07-9c47-87422f0b03c1.png)

with the test that redirects, the iFrame path changes permanently to:
![image](https://user-images.githubusercontent.com/4405822/131509774-962adbcf-1460-4421-922f-32ac4f4c1038.png)

### Desired behavior

The URL is reset between tests.

### Test code to reproduce

Use a component which redirects the browser, for example using `document.location = '/error/401`

### Cypress Version

8

**Comment by lmiller1990** [comment]
Are you mounting your entire app (include the full backend as well)?

I have not considered the implications of `document.location` in component testing, but if you are using `@cypress/webpack-dev-server`, the architecture is dependent on the URL, so navigating away might have some unexpected consequences. It's for this exact reason `cy.visit()` is not supported, and throws an error, in component testing.

**Comment by JessicaSachs** [comment]
Navigating or otherwise modifying `document.location` in component tests will not work and is unsupported right now.

This is because the test's context exists within the iframe window being navigated.

If you were to call `document.location = 'something'` you'd blow away the entire test. The same problem occurs with links and form submission.

Anything that does a full-page navigation should be avoiding.
