### ISSUE TITLE
Cypress only works in Electron browser

### ISSUE THREAD

**Issue by deysejesuino** [cypress-io/cypress#17949]
### Current behavior

Cypress only works in Electron browser, not Chrome, Firefox and Edge

When I'm at the company connected to the network cable, cypress works normally. When I get home with my internet, the Cypress examples themselves don't work in browsers. Tests performed: I checked the proxy (my internet does not have a proxy, in any of the browsers), I tested the local network cable on the machine (it didn't work), I tested another type of internet without being corporate, without success.

The timeout print follows, what can I do? I even formatted my corporate computer, but without success.

NOTE: My personal computer is on the same internet network, and it works correctly.

![erro 1](https://user-images.githubusercontent.com/89205486/131568227-55a0e5c3-8d62-485d-833f-90b9d304104f.png)
![erro 2](https://user-images.githubusercontent.com/89205486/131568230-fab5e9f5-a4fc-499f-b8ca-d4c29328ebcd.png)

### Desired behavior

That it works in browsers, at least on Chrome and Edge

### Test code to reproduce

cypress examples themselves do not open

### Cypress Version

Cypress package version: 8.3.1 Cypress binary version: 8.3.1 Electron version: 13.2.0 Bundled Node version: 14.16.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

Is it still not working with 8.5.0? 

You can directly visit the todo example page, https://example.cypress.io/todo, with your local network cable, right?

Does Cypress fail to visit other pages?

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by vishal14121996** [comment]
@sainthkh  we are facing this issue

**Comment by jennifer-shehane** [comment]
@vishal14121996 Please open a new issue, providing a reproducible example and error.
