### ISSUE TITLE
Possible regression of @cypress/vue: mounting a new component does not remove the old one

### ISSUE THREAD

**Issue by rathax** [cypress-io/cypress#17941]
### Current behavior

cypress/vue 3.0.0-beta.4 and newer do not seem to clean up old components on my end when running cypress component tests:

component
```vue
<template>
<div>text</div>
</template>


<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  name: "MainMenu",
  setup() {
  },
});
</script>
```

test.spec.ts
```javaScript
describe("test", () => {
  it("test1", () => {
    mount(component);
    expect(true).to.be.true;
  });

  it("test2", () => {
    mount(component);
    expect(true).to.be.true;
  });
  it("test3", () => {
    mount(component);
    expect(true).to.be.true;
  });
});
```
![image](https://user-images.githubusercontent.com/16104507/131486060-8cfba92a-b883-49d4-863e-101f695013b5.png)

cypress/vue 3.0.0-beta.3 works as expected:

![image](https://user-images.githubusercontent.com/16104507/131486435-aad16641-3844-46f2-a019-eb3cca2053f3.png)

### Desired behavior

Component gets properly replaced by the new one when calling mount()

### Test code to reproduce

see above, i could get up a repo if that is not enough

"dependencies": {

    "@quasar/extras": "^1.10.9",
    "@vuelidate/core": "^2.0.0-alpha.22",
    "@vuelidate/validators": "^2.0.0-alpha.19",
    "axios": "^0.21.1",
    "core-js": "^3.16.0",
    "cypress": "8.3.1",
    "lodash": "^4.17.21",
    "mixin-deep": "^2.0.1",
    "msw": "^0.33.2",
    "pinia": "^2.0.0-rc.6",
    "quasar": "^2.0.3",
    "register-service-worker": "^1.7.1",
    "vue": "3.2.6",
    "vue-i18n": "^9.1.7",
    "vue-router": "^4.0.9"
  },
  "devDependencies": {
    "@cypress/vue": "3.0.3",
    "@cypress/webpack-dev-server": "^1.4.0",
    "webpack-dev-server": "^3.11.2",
    "@intlify/vue-i18n-loader": "^2.1.2",
    "@types/lodash": "^4.14.172",
    "@typescript-eslint/eslint-plugin": "^4.29.0",
    "@vue/cli-plugin-babel": "^4.5.13",
    "@vue/cli-plugin-eslint": "^4.5.13",
    "@vue/cli-plugin-pwa": "^4.5.13",
    "@vue/cli-plugin-router": "^4.5.13",
    "@vue/cli-plugin-typescript": "^4.5.13",
    "@vue/cli-service": "^4.5.13",
    "@vue/compiler-sfc": "^3.1.5",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-rc.12",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.15.1",
    "html-webpack-plugin": "4.5.2",
    "prettier": "^2.3.1",
    "sass": "^1.37.5",
    "sass-loader": "^10.2.0",
    "typescript": "~4.3.5",
    "vue-cli-plugin-i18n": "^2.1.2",
    "vue-cli-plugin-quasar": "^4.0.1"
  },

### Cypress Version

8.3.1

**Comment by lmiller1990** [comment]
What do you mean by `@cypress/vue 3.0.0-beta.4`? The latest version is `3.0.3`. Are you saying `3.0.2` -> `3.0.3` broke for you?

**Comment by anark** [comment]
I'm seeing something very similar using the most recent @cypress/react.  If a test fails and is retried then the previous component is not removed before the new one is added.

**Comment by rathax** [comment]
> What do you mean by `@cypress/vue 3.0.0-beta.4`? The latest version is `3.0.3`. Are you saying `3.0.2` -> `3.0.3` broke for you?

@cypress/vue 3.0.0-beta.3 works without any issues.

when upgrading to 3.0.0-beta.4 or 3.0.3 it shows the described behavior.

**Comment by lmiller1990** [comment]
A reproduction repo would be really good. I'm not seeing this in any of our internal test suites or example projects, but it could be a bug. If someone can share a repo, that'd be great.

**Comment by rathax** [comment]
@lmiller1990 

here is a repo
https://github.com/rathax/cypress-17941-reproduction

testen on:
windows 10
node v16.5.0

windows 10
node v16.7.0

**Comment by lmiller1990** [comment]
Thanks. I was able to verify the problem is happening with your reproduction (macos).

Oddly enough, I could not reproduce it myself in a fresh repo.

- created Vue CLI project (using Vue 3, TypeScript)
- followed this: https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/
- [here's the repo](https://github.com/lmiller1990/cypress-vue-3-failed-repro), works as expected

I wonder what the difference is here... some kind of dependency mismatch?

@anark are you able to provide a repo with the bug you are experiencing?

**Comment by rathax** [comment]
@lmiller1990

upgrading from cypress 8.3.1 to 8.4.1 seems to have solved the issue. You can reproduce this in my repo by updating the cypress dependency.

I guess this issue can be closed then.

**Comment by anark** [comment]
@lmiller1990,
Sorry for the delay, I've had a hard time making a reliable reproduction of the issue I am having.

Basically I use the following function to wrap the mount function
```
export const mountComponent = (element: ReactElement) => {
  mount(
    <Router>
      <GlobalStyles />
      <DndProvider backend={HTML5Backend}>
        <IntlProvider locale="en" defaultLocale="en">
          {element}
        </IntlProvider>
      </DndProvider>
    </Router>
  )
}
```

On a specific test when it fails(for an actual valid failure), on the retry I get the following error
```
Cannot have two HTML5 backends at the same time.
```

However I am only getting this when running on Github Actions worker and cannot get the issue to reproduce locally.
This may be something with my setup so I assume this can be closed.  If I can narrow it down to a specific issue I will create a new issue.

**Comment by lmiller1990** [comment]
I have seen several bugs that are GH actions *only*. You could try running on Circle and see if it still happens there.

Happy to reopen and investigate once we have a reproduction.
