### ISSUE TITLE
Expected to find the global cypress parent window but it is missing! (window.Cypress is undefined)

### ISSUE THREAD

**Issue by ds-clearago** [cypress-io/cypress#17952]
### Current behavior

When visiting the main page, cypress fails immediately with `TypeError Cannot set property name of  which has only a getter`
This happens regardless of using localhost or https://staging.clearago.de/.
Looking at the page, cypress visibly manipulates the site and outputs the following in the HTML:
![page-weird-cypress-bug](https://user-images.githubusercontent.com/26897541/131637277-472d63ba-2185-41d8-aa36-295556b405e7.png)
![html-weird-cypress-bug](https://user-images.githubusercontent.com/26897541/131637294-1dd954a0-791c-466e-838f-840041dd11e5.png)
```
<script type='text/javascript'> document.domain = 'localhost'; !function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){" undefined"!="typeof" symbol&&symbol.tostringtag&&object.defineproperty(e,symbol.tostringtag,{value:"module"}),object.defineproperty(e,"__esmodule",{value:!0})},n.t="function(e,t){if(1&amp;t&amp;&amp;(e=n(e)),8&amp;t)return" e;if(4&t&&"object"="=typeof" e&&e&&e.__esmodule)return="" e;var="" r="Object.create(null);if(n.r(r),Object.defineProperty(r,&quot;default&quot;,{enumerable:!0,value:e}),2&amp;t&amp;&amp;&quot;string&quot;!=typeof" e)for(var="" o="" in="" e)n.d(r,o,function(t){return="" e[t]}.bind(null,o));return="" r},n.n="function(e){var" t="e&amp;&amp;e.__esModule?function(){return" e.default}:function(){return="" e};return="" n.d(t,"a",t),t},n.o="function(e,t){return" object.prototype.hasownproperty.call(e,t)},n.p="" ,n(n.s="0)}({&quot;./injection/index.js&quot;:function(e,t,n){&quot;use" strict";n.r(t);const="" new=""error("something="" went="" terribly="" wrong="" and="" we="" cannot="" proceed.="" expected="" to="" find="" the="" global="" cypress="" parent="" window="" but="" it="" is="" missing!.="" this="" should="" never="" happen="" likely="" a="" bug.="" please="" open="" an="" issue!");const="" class=" no-touchevents es5date no-touchevents es5date" style="--carousel-scroll-speed:320ms;">
```
```
{setTimeout:window.setTimeout,setInterval:window.setInterval,requestAnimationFrame:window.requestAnimationFrame,clearTimeout:window.clearTimeout,
                clearInterval:window.clearInterval},a=(e,t)=>o[e].apply(window,t),s=e=>n=>(t&&(r[n]=!0),a(e,[n])),u=t=>(...r)=>{let o,[s,u,...l]=r;return o=a(t,[(...r)=>
                    {if(!e)return i(s,r);n.push({timerId:o,fnOrCode:s,params:r,type:t})},u,...l]),o};window.setTimeout=u("setTimeout"),window.setInterval=u("setInterval"),
                    window.requestAnimationFrame=u("requestAnimationFrame"),window.clearTimeout=s("clearTimeout"),window.clearInterval=s("clearInterval")},reset:o,pause:a=>
                    {e=Boolean(a),e||(t=!0,n.forEach(e=>{const{timerId:t,type:n,fnOrCode:o,params:a}=e;"setInterval"===n&&r[t]||i(o,a)}),o())}}})();r.removeAllListeners
                    ("app:timers:reset"),r.removeAllListeners("app:timers:pause"),r.on("app:timers:reset",o.reset),r.on("app:timers:pause",o.pause),o.wrap(),r.action
                    ("app:window:before:load",window)},0:function(e,t,n){e.exports=n("./injection/index.js")}});
```

The JS console doesn't show anything of interest at all at that time.

Interestingly enough, when I click around within the tested page, that weird thing disappears: https://share.vidyard.com/watch/cNt4pwn4EYff6sA4UHBcJ2?

### Desired behavior

In this situation, Cypress should visit the site normally without problems and then proceed with next test steps.

### Test code to reproduce
```
/// <reference types="Cypress" />
describe('pages_seo', () => {
    /* beforeEach(() => {
    }) */

    it('Test Case 35: Go through all SEO LPs and land on CSP', function () {
        cy.viewport('macbook-13')
        cy.visit('https://staging.clearago.de/?test=1&utm_source=test&utm_medium=cypress').debug()
        // cy.get("#footer_waste li").should('be.visible')
    })
  })
```

### Cypress Version

8.3.1

### Other

I'm running 
* Cypress v8.3.1 on 
* Mac OS 10.15.7 in
* Chrome v92

I thought it might be related to other 3rd-party-JS and therefore added this in the config, but that hasn't helped neither. Removing Google Optimize Anti-Flicker Code also didn't help.
```
"blockHosts": [
    "*google-analytics.com",
    "*googletagmanager.com",
    "*tagmanager.google.com",
    "*googleoptimize.com",
    "*googleadservices.com",
    "*doubleclick.net",
    "*doubleclick.com",
    "*facebook.net",
    "*facebook.com",
    "*hotjar.com",
    "*clarity.ms",
    "*ads.linkedin.com",
    "*bat.bing.com"
  ]
```

**Comment by ds-clearago** [comment]
This might be related to https://github.com/cypress-io/cypress/issues/972

**Comment by rsokolov06** [comment]
Hello,

Could this be also related to the issue #17986 ?

**Comment by ds-clearago** [comment]
Another test case for seemingly same issue to be seen in #17986

**Comment by rsokolov06** [comment]
Hello @ds-clearago , thanks for stating my record. Nevertheless I was told that cy.visit('https://www.saucedemo.com/'); does not pass only in my environnment (or possibly Cypress version which is latest :).

By the way, could you try it on your side using the example I have provided in my ticket.

**Comment by ds-clearago** [comment]
@jennifer-shehane I've tried your solution suggested in https://github.com/cypress-io/cypress/issues/17986 here and indeed the runner actually starts then. Even though I actually don't understand how chromeWebSecurity is a topic here because I'm facing all the issues explained below regardless whether I cy.visit `staging.clearago.de` or `localhost:9999`.

I've now tried with the following `cypress.json` config:
```
{
  "chromeWebSecurity": false,
  "blockHosts": [
    "*google-analytics.com",
    "*googletagmanager.com",
    "*tagmanager.google.com",
    "*googleoptimize.com",
    "*googleadservices.com",
    "*doubleclick.net",
    "*doubleclick.com",
    "*facebook.net",
    "*facebook.com",
    "*hotjar.com",
    "*clarity.ms",
    "*ads.linkedin.com",
    "*bat.bing.com"
  ]
}
```

And the following `testfile.js`:
```
/// <reference types="Cypress" />

describe('selenium-35-waste_pages_seo', () => {
    it('Test Case 35: Go through all SEO LPs and land on CSP', function () {
        cy.viewport('macbook-13')
        
        cy.visit('https://staging.clearago.de/?test=1') //.debug()
    
        cy.get('#footer_waste li:nth-child(1) > a').click()             // clicks the SEO page
        cy.get('#postcode3').type('12345')                              // enters plz
        cy.get('.mt-10 .button_primary').click()                        // proceeds to CSP
        cy.url().should('include', 'no-results')                        // asserts redirect to no results page
        cy.go('back')
        cy.go('back')
    })
})
```

But it's somehow very buggy as the features of the runner where you can go through all the steps don't work at all:
https://www.loom.com/share/028c33ea54264839b0125e046feba1c2

----
Here a screenshot with same problems on local while using `cy.visit('http://localhost:9999/')`
![2021-09-08 at 17 58](https://user-images.githubusercontent.com/26897541/132543968-01531241-c893-4279-9178-86a606ead885.png)

**Comment by ds-clearago** [comment]
Behaviour has slightly changed with cypress v8.4.1:
## ChromeWebSecurity turned on
### localhost
![localhost + chromewebsecurity true](https://user-images.githubusercontent.com/26897541/134135187-d2d6ae93-fe8f-42cc-bcfb-ae9e0fa0874b.png)
### remote host
![remote + chromewebsecurity true](https://user-images.githubusercontent.com/26897541/134135316-e6494cdf-e31f-438e-a735-83081c005855.png)


## ⚠️ ChromeWebSecurity turned off
### remote or localhost look exactly the same
![localhost + chromewebsecurity false](https://user-images.githubusercontent.com/26897541/134135356-116fd2ba-5474-4111-9662-335c3a05da3a.png)

@jennifer-shehane Since you commented the working workaround in the related issues but I can't seem to figure it out here, tagging you again hoping you have an idea and so that you can prioritize the issues with the correct cypress internal labels. Cheers!

**Comment by ds-clearago** [comment]
Just found issue #3459 that I thought might be related. But adding https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe and adding the `"modifyObstructiveCode": false,` option both didn't help...
