### ISSUE TITLE
Cy.visit generates an error

### ISSUE THREAD

**Issue by rsokolov06** [cypress-io/cypress#17986]
### Current behavior

Hello,

When performing cy.visit() on the "sauce demo" website, it generates an error: _**Cannot set property name of  which has only a getter**_.

![sauce_error](https://user-images.githubusercontent.com/78181445/132129928-187a0872-b9a5-4cec-9a77-3c0944d911f0.JPG)

Could you please have a look,

Thanks in advance!
R  

### Test code to reproduce

describe('example', () => {
    
    it('open sauce', () => {   
     
     cy.visit('https://www.saucedemo.com/');

    })
  })

### Cypress Version

8.3.1

**Comment by jennifer-shehane** [comment]
This error only occurs when the visit is moved within a `beforeEach` hook. Cypress is displaying a non-helpful error in this situation introduced in 8.2.0, it should be showing a different error about cross origin frames. 

```js

describe('tests', () => {
  beforeEach(() => {
    cy.visit('https://www.saucedemo.com/');
  })
  it('test', () => {
  });
});
```

### 8.1.0

<img width="1320" alt="Screen Shot 2021-09-07 at 12 48 52 PM" src="https://user-images.githubusercontent.com/1271364/132389033-247cb999-e280-405e-868b-0ca28f0a9456.png">


### 8.2.0



<img width="1322" alt="Screen Shot 2021-09-07 at 12 28 46 PM" src="https://user-images.githubusercontent.com/1271364/132386569-a14831cc-9463-4d59-a503-4aee15658a4d.png">

**Comment by rami-almofleh** [comment]
I have the same Problem, any solution?

**Comment by leonardoluizantunes** [comment]
rsokolov06 I was facing the same problem and solved it by removing the www from inside the base url.

![Screenshot_1](https://user-images.githubusercontent.com/51132607/210092977-90d53331-5c94-4fec-b938-58b05b8123b8.png)

**Comment by danielthon** [comment]
**@leonardoluizantunes** The same was happening here, and removing "www" worked! Thanks so much! 💚🇧🇷
