### ISSUE TITLE
Can't resolve '~/

### ISSUE THREAD

**Issue by amaralc** [cypress-io/cypress#17981]
### Current behavior

While testing components, it is not possible to resolve imports with a pattern starting with '~/'.

### Desired behavior

It should be possible to resolve modules starting with any pattern configured in jsconfig.js

### Test code to reproduce

```js
import React from 'react';
import { mount } from '@cypress/react';
import MyButton from '~/components/MyButton';

it('renders my button', () => {
  mount(<MyButton />);
  cy.get('button').contains('Label');
});

```

### Cypress Version

^7.4.0

### Other

If I use any other pattern rather than "~/*", the imports are recognized, and everything works fine. The problem is that we have already used that in the entire code and it would be unfeasible to change it everywhere.

**Comment by lmiller1990** [comment]
Can you share a minimal reproduction? Are you using the webpack dev server? We just read your `webpack.config.js`, so if you have configured a `~` alias there, it should work just fine inside of Cypress, too.

**Comment by lmiller1990** [comment]
Happy to take a look w/ a minimal reproduction.
