### ISSUE TITLE
Cypress intercept with NOT and OR condition

### ISSUE THREAD

**Issue by dhamo-pk** [cypress-io/cypress#17990]
### What would you like?

Would like to have the option of capturing the service with the below condition 
 
**With NOT Condition:**
 ` cy.intercept("GET", "**/NOT(f0000000000)/path1*").as('abc');`
 ` cy.intercept("GET", "**/!(f0000000000)/path1*").as('abc');`

**With OR Condition:**
 ` cy.intercept("GET", "**/(f0000000000 OR t0000000000 )/path1*").as('abc');`
 ` cy.intercept("GET", "**/(f0000000000 || t0000000000 )/path1*").as('abc');`

### Why is this needed?

Out of the following services, the last one we need to intercept where the valueA (f2021090606) is dynamic and we have only option to go with ensuring the endpoint does not have a valueB(f0000000000). 

```
https://example.com/f0000000000/path1 - GET
https://example.com/f0000000000/path1 - GET
https://example.com/f0000000000/path1 - GET
https://example.com/f2021090606/path1 - GET
```

**Comment by sainthkh** [comment]
`cy.intercept` supports glob and regex. 

So it can be written like below:

```js
it('negate', function () {
  cy.intercept('GET', '**/!(f0000000000)/path1*', ['foo', 'bar'])
  .then(() => {
    return Cypress.$.getJSON('/f0000000000/path1')
  })
  .should('deep.eq', ['foo', 'bar']) // fail
})

it('negate', function () {
  cy.intercept('GET', '**/!(f0000000000)/path1*', ['foo', 'bar'])
  .then(() => {
    return Cypress.$.getJSON('/f0000123000/path1')
  })
  .should('deep.eq', ['foo', 'bar'])
})

it('or', function () {
  cy.intercept('GET', '**/{f0000000000,t0000000000}/path1*', ['foo', 'bar'])
  .then(() => {
    return Cypress.$.getJSON('/f0000000123/path1')
  })
  .should('deep.eq', ['foo', 'bar']) // fail
})

it('or', function () {
  cy.intercept('GET', '**/{f0000000000,t0000000000}/path1*', ['foo', 'bar'])
  .then(() => {
    return Cypress.$.getJSON('/f0000000000/path1')
  })
  .should('deep.eq', ['foo', 'bar'])
})
```

As for glob patterns, check [this article](https://linuxhint.com/bash_globbing_tutorial/) and [this checker program](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%21%28f0000000000%29%2Fpath1%2A&matches=false&tests=example.com%2Ff0000000000%2Fpath1&tests=example.com%2Ff0000001200%2Fpath1).

**Comment by dhamo-pk** [comment]
thank you @sainthkh
