### ISSUE TITLE
Since version 8 up the suite of tests gets broken randomly with Error: ERR_TIMED_OUT (-7) loading   

### ISSUE THREAD

**Issue by petrican** [cypress-io/cypress#17998]
### Current behavior

Since version 8 up the suite of tests gets broken randomly with Error: ERR_TIMED_OUT (-7) loading   

I had to downgrade to 7.7.0 version for the tests to pass (all are passing using this version)

### Desired behavior

There should be no random failure like that causing false positive results.

### Test code to reproduce

Clone https://github.com/metasfresh/metasfresh

Go to e2e folder and upgrade to a version of cypress above 8. Run the suite several times against a dev instance. The error will randomly stop the build. Sample in CI env:

<img width="1619" alt="Screenshot 2021-09-07 at 11 01 28" src="https://user-images.githubusercontent.com/1708561/132307635-95bda5fd-77ac-46f1-a409-0791e47ffa00.png">

### Cypress Version

anything above 8.0.0

### Other

Someone also experienced this it seems https://www.gitmemory.com/issue/cypress-io/cypress/17627/897135367

**Comment by joelgrimberg** [comment]
I was on version 8.4.0 when this started to happen.
seems like downgrading to 8.3.1 works for me

**Comment by rebel-l** [comment]
I can confirm version **8.2.0** and above are causing this error every time. We are using Jenkins with Docker image **cypress/base:14.17.0**.

We tried to get more information by using the parameter `-e DEBUG="cypress:*"` but then this error didn't appear.

**Comment by baviereteam** [comment]
This seems to be a duplicate of #17627

**Comment by rebel-l** [comment]
@baviereteam you are right

**Comment by bahmutov** [comment]
observed in Cypress v9.7.0 too
