### ISSUE TITLE
Next.js ^11.1.1 : webpack error + bundling step timeout

### ISSUE THREAD

**Issue by g10** [cypress-io/cypress#17992]
### Current behavior

Using the [create next app webpack 5 example](https://github.com/cypress-io/cypress-component-testing-examples/tree/main/create-next-app-webpack-5) setup, with `"next": "latest"` that resolves to `^11.1.1`. 

Result in a TypeError and a timeout on the bundling step
```
✖ ｢wdm｣: TypeError: Cannot read property 'traceChild' of undefined
...
ℹ ｢wdm｣: wait until bundle finished: /__cypress/src/index.html
```

### Test code to reproduce

[create next app webpack 5 example](https://github.com/cypress-io/cypress-component-testing-examples/tree/main/create-next-app-webpack-5) setup with `"next": "latest"` (`11.1.1` or `11.1.2`)

### Cypress Version

^8.3.0

## workaround / temporary solution :

use exact version at `11.1.0`

```
"next": "11.1.0"
```

tnx https://github.com/cypress-io/cypress/discussions/17883#discussioncomment-1233406

**Comment by danielweil** [comment]
Same error in Next version 11.1.2
