### ISSUE TITLE
Cypress runs slow on Mac OS Big Sur

### ISSUE THREAD

**Issue by omartaghlabi** [cypress-io/cypress#18006]
### Current behavior

All versions of Cypress run extremely slow on Mac OS Big Sur 11.4. This is the case for both `cypress open` and `cypress run`. A significant amount of time is spent waiting for pages to load.

I installed version 8.3.1 which includes a fix to speed up browser detection #17773, but Cypress is still running slow.

A simple test to perform a google search takes about 30 seconds in Big Sur, whereas it only takes 3 seconds in Mojave.

### Desired behavior

Running Cypress on macOS Big Sur should run as fast as it runs on previous OS versions.

### Test code to reproduce

Run this test on macOS Big Sur. I'm running Version 11.4.

```
context('Playground', () => {
  beforeEach(() => {
    cy.visit('https://www.google.com/')
  })
  
  it('Google search Cypress', () => {
    cy.get("input[name=q]")
      .type("cypress");
  
    cy.get("input[name=q]")
      .type('{enter}');
  })
})
```

### Cypress Version

8.3.1

### Other

Browser: Chrome V93

Results from running the test in Big Sur, notice it took 30.35 seconds to run:
![bigSur](https://user-images.githubusercontent.com/5993638/132362547-9df213ef-a223-4714-b658-e5cbd39f4ce7.png)

Results from running the same test in Mojave, notice it took 2.69 seconds to run:
<img width="1320" alt="mujave" src="https://user-images.githubusercontent.com/5993638/132364273-8d61e988-a8f9-4b2c-ba3b-ded2d8dd2e58.png">

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this slowness on Big Sur, tried version 11.3.1 and 11.5.2. 

Are there any other differences to the running tests? Is it the same Google Chrome version running on both? Is one behind a VPN or other corporate network restrictions?

**Comment by omartaghlabi** [comment]
They are both running the same version of Chrome (Version 93) and neither is behind VPN.
I'm still seeing the slow behavior after upgrading to Big Sur's latest Version(11.5.2).

**Comment by omartaghlabi** [comment]
Hi @george-cz,
Yes, I'm seeing improved performance on rerun without closing the window and just hitting rerun.

**Comment by andreasstrey** [comment]
Hi,

is there any progress on this issue? 

We see the same behavior, that the first run is much slower than the re-runs. Before the upgrade of MacOS to Monterey our testsuite took ~22 minutes and now it is ~45 minutes.

**Comment by danfooks** [comment]
> 

I experience the same behavior as well on Mac. When using Electron, my tests run as quickly as I would expect. When using Chrome, not only does Chrome take a while to open, but the tests run _very_ slowly. If the tests are re-ran, they run much faster, closer to normal. This issue seems to be very apparent on the first test run upon opening a new browser instance.

**Comment by Muhammadhassanyamin** [comment]
Its the same for me, cypress runs very very slow. The app under consideration works very well when it is being run manually but as soon as run it on cypress it takes so much time even on re-runs.

It is slow on all the versions currently I am on macOS M1 Ventura 13.4 and electron/chrome browser is also updated. I have seen the same behaviour on macBook Air M1 too. 

Do you recommend any sort of settings for it ?

**Comment by nagash77** [comment]
@Muhammadhassanyamin Issues in the github repo are reserved for bugs and feature requests.  I suggest you Check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
