### ISSUE TITLE
Failed to connect to Chrome ,  Cypress failed to make a connection to the Chrome DevTools

### ISSUE THREAD

**Issue by shanshanrjz** [cypress-io/cypress#18004]
### Current behavior

cypress version 8.3.1 ; chrome :  9.3 ; MAC os
run ./node_modules/.bin/cypress open
![image](https://user-images.githubusercontent.com/90261016/132349597-ff74ccd8-1fbb-46e1-8340-33aeee7bbe65.png)
and the cypress:
![image](https://user-images.githubusercontent.com/90261016/132349683-e662e082-5efc-47cf-b2e1-1796abad334d.png)

### Test code to reproduce

run ./node_modules/.bin/cypress open

### Cypress Version

8.3.1

**Comment by mshre001** [comment]
I had the same problem and tried clearing app data, that fixed it for me -
https://docs.cypress.io/guides/references/troubleshooting#Allow-Cypress-URLs-on-VPNs

hope this works for you!

**Comment by lkreynolds** [comment]
this worked for me, thanks!
