### ISSUE TITLE
Unable to launch tests in chrome,firefox, edge

### ISSUE THREAD

**Issue by Amrita19900406** [cypress-io/cypress#18018]
### Current behavior

Unable to launch tests in chrome,firefox, edge. Not able to see the cypress icon on the browser[](url)
![image](https://user-images.githubusercontent.com/45754319/132500774-e83b4cc6-bde2-4661-b37a-ebf7af21f396.png)

### Desired behavior

![image](https://user-images.githubusercontent.com/45754319/132500972-520a38cf-b144-4fee-89f9-0c3727b2c10a.png)

should be able to run tests as working in electron browser

### Test code to reproduce

Launching any url

### Cypress Version

8.3.1

### Other

chrome - Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by Amrita19900406** [comment]
@ jennifer-shehane: could you please help here? We are completely blocked

**Comment by Amrita19900406** [comment]
@jennifer-shehane please help here

**Comment by Amrita19900406** [comment]
@sainthkh Please have a look and help us. Completely blocked

**Comment by Amrita19900406** [comment]
Test code to reproduce: 
describe('LocatorsSpecs', () => {

    it('Verify Title Of Webpage- positive', () => {

      cy.visit('https://demo.nopcommerce.com') // visits the page

      cy.title().should('eq','nopCommerce demo store')

      cy.get("#small-searchterms").type("Apple MacBook Pro 13-inch")

      cy.get(".search-box-button").click({ force: true })

      cy.get(".product-box-add-to-cart-button").click({ force: true })

      cy.get("#product_enteredQuantity_4").clear().type("2") // quantity

      cy.get("#add-to-cart-button-4").click()

      cy.wait(5000)

      cy.get("#topcartlink > a > span.cart-label").click()

      cy.get(".product-unit-price").contains("$1,800.00") // validating price


    })

  })

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this error on my side when running the tests given. 

Could you try following [these instructions](https://on.cypress.io/troubleshooting#Clear-App-Data) to Clear App Data?

Outside of that, perhaps something related to your network or restrictions? Have you tried to run the tests on a completely different network.

**Comment by sainthkh** [comment]
Sorry for the late reply.

Is this still happening with 8.5.0?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
