### ISSUE TITLE
Mocha reports "expect" reporterOption passed into it

### ISSUE THREAD

**Issue by KamalAman** [cypress-io/cypress#18014]
### Current behavior

Currently, the Cypress integration with mocha assumes that reporters take in an option called `reporterOptions` however `reporterOptions` is actually an alias for `reporterOption` 

The current implementation
https://github.com/cypress-io/cypress/blob/a6a2c49c353d692e0009018a3fa186f164bc4730/packages/server/lib/reporter.js#L293

The change to the API is stated here https://github.com/mochajs/mocha/issues/4741#issuecomment-914511516
and documented here: https://mochajs.org/#-reporter-option-option-o-option-reporter-options-option

That being said, you cannot just pass in `reporterOption` instead of `reporterOptions` since some reporters still reference the legacy variable.

### Desired behavior

Should be able to use any mocha reporter, and it should respect `reporterOptions` Cypress CLI parameter.

For example the JSON reporter here uses the new variable `reporterOption` https://github.com/mochajs/mocha/blob/master/lib/reporters/json.js

### Test code to reproduce

In the latest version of the JSON version in v9.11 of mocha it has an `output` option. Currently the render options do not get properly passed in.
```
nx affected --target=e2e  --reporter json --reporterOptions "output=results.json"
```

### Cypress Version

8.3.1

### Other

The proposed change would be to make the following change

```js
this.reporter = new this.mocha._reporter(this.runner, {
      reporterOptions: this.reporterOptions,
      reporterOption: this.reporterOptions,
})
```

**Comment by patcon** [comment]
I believe I'm hitting this, where mocha reporters can't be output to file:

```json5
// cypress.json
{
  "reporter": "json",
  "reporterOption": {
    "mochaFile": "output.txt"
  }
}
```

Cypress package version: 9.6.0

Wondering if there's a way to force an old version of mocha in the meantime...

**Comment by patcon** [comment]
Thanks @KamalAman! Pushed this just a little bit further in https://github.com/cypress-io/cypress/pull/21224 😆

**Comment by patcon** [comment]
The breaking commit in mocha:
https://github.com/mochajs/mocha/commit/eed38d798270e230363abefd6934df8302c5f036

The attempted backward compat that should ideally work for us: https://github.com/mochajs/mocha/commit/9c10adab3340abd8baff147cb595256234d88de6

**Comment by jholmes-seek** [comment]
Is there anything we can do to help get this through?
