### ISSUE TITLE
cy.wait() doesn't wait for request to be done and executes code below it.

### ISSUE THREAD

**Issue by kevinmamaqi** [cypress-io/cypress#18010]
### Current behavior

I have a graphql api that I am trying to stub with the following code:

```js
describe('Painblock', () => {
    beforeEach(() => {
      cy.intercept('POST', URLS.GRAPHQL_URL, (req) => {
        aliasQuery(req, 'getInitialData')
        aliasQuery(req, 'queryPollData')
      })
    })
    it('renders no pain recorded yet', () => {
      cy.intercept('POST', URLS.GRAPHQL_URL, (req) => {
        if (hasOperationName(req, 'getInitialData')) {
          req.alias = 'getInitialData'
          req.reply({ status: 200, data: RESPONSE })
        }
      })
  
      store.dispatch(getInitialData())
  
      cy.wait('@getInitialData').its('response.statusCode').should('eq', 200)
  
      console.log('hola', store.getState()) // This is empty
    })
  })
```

The alias, response and everything else works well.

The cy.wait command although it identificais the alias, doesn't wait for the request to be finished. Therefore the console log that is below executes before I get my data in the store.

Is there something that I am missing?

### Desired behavior

cy.wait(), waits until the request is finished.

### Test code to reproduce

Above.

### Cypress Version

7.6.0

**Comment by jennifer-shehane** [comment]
I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code). The sync console.log will always run before the async cy.wait() resolves.
