### ISSUE TITLE
Command log will incorrectly show "req modified"

### ISSUE THREAD

**Issue by exalted** [cypress-io/cypress#18024]
### Current behavior

For some reason, the command log incorrectly reports that the intercepted request as modified (ie `req modified`) even though it clearly wasn't as in this code snippet:

```js
it('Command log incorrectly shows ', () => {
  // Instead of `res => res` below you could also pass `() => {}` but that
  // wouldn't alter the outcome
  cy.intercept('http://localhost:3000/sendPayload', { times: 1 }, res => res)
    .as('sendPayload');

  cy.visit('http://localhost:3000/');

  cy.wait('@sendPayload');
});
```

### Desired behavior

If the request wasn't modified then the command log shouldn't say so.

### Test code to reproduce

I've set up a very basic repository here: https://github.com/exalted/cypress-intercept-bug

### Cypress Version

8.3.1

### Other

I was able to trace down the issue to https://github.com/cypress-io/cypress/blob/e216ae2422706d4f46e6dfa68abe2d589c72cf96/packages/driver/src/cy/net-stubbing/events/before-request.ts#L289-L291.

For this specific case, `req` and `reqClone` will be different, because `req.body` is a string whilst `reqClone.body` will be a parsed JSON body.

**Comment by jennifer-shehane** [comment]
I can recreate this from the provided repo. 

<img width="1148" alt="Screen Shot 2021-09-08 at 3 25 43 PM" src="https://user-images.githubusercontent.com/1271364/132580436-56cef083-d5f9-4cdc-8e6e-385c525e8fd4.png">

Seems like a legitimate use case to me, maybe you want to inspect the request or do something with it but aren't modifying it. It shouldn't show as modified in the UI.

```js
it('Command log incorrectly shows ', () => {
  cy.intercept('http://localhost:3000/sendPayload', (req) => {
    return req
  }).as('sendPayload');

  cy.visit('http://localhost:3000/');
  cy.wait('@sendPayload')
})
```

**Comment by exalted** [comment]
Further insight:

In my case all I wanted was to pass it the `{ times: 1 }` which in return "forced" me to pass the `routeHandler` parameter as well. Since I didn't care about that, I had to pass `() => {}` as the 3rd argument to `intercept` to silent the usage error. 

The fact that a route handler function was given, for some reason, in this specific case, shows as "req modified". However, clearly, the request wasn't modified.
