### ISSUE TITLE
"expected undefined to exist" when running inside a hook

### ISSUE THREAD

**Issue by erwindetesters** [cypress-io/cypress#18041]
### Current behavior

When running commands like `should('exist')` or `should('be.visible')` in hooks, I get an error stating `expected undefined to exist` or `expected undefined to be visible`.

### Desired behavior

When running commands like `should('exist')` or `should('be.visible')` in hooks, I expect the code to work the same as when running it inside the test function.

### Test code to reproduce

I had this happen by placing a `before` and `after` hook in the `/support/index.js` (take note that I didn't use the index.js directly for this as I use TypeScript but I don't think this matters)

I placed two commands in there, a `login` custom command in the `before` hook and a `logout` custom command in the `after` hook.

During the page load during the logout it returns undefined most of the time.

I ran a clean project for this with the latest version and no additional reporters or plugins.

### Cypress Version

8.3.1

**Comment by erwindetesters** [comment]
Turns out this isn't related to the hooks but something else. I have a feeling it might be due to React's virtual DOM while rendering / reloading / loading a page, therefor I will close the issue and recreate it with the proper information.

**Comment by moritz-baecker-integra** [comment]
Im probably running into the same problem, just with VueJS. How did you solve that?
