### ISSUE TITLE
getting TypeError: this[name] is not a function while running demo test cases after installation

### ISSUE THREAD

**Issue by anilrulezz** [cypress-io/cypress#18050]
### Current behavior

![image](https://user-images.githubusercontent.com/90420006/132754249-43ebf8b4-9f23-4667-a7b5-d45f98ffdf56.png)

### Cypress Version

    "cypress": "^8.3.1",

### Package Manager

npm

### Operating system

Windows

**Comment by jennifer-shehane** [comment]
@anilrulezz Thanks for reporting. Could you provide a reproducible example of the code run to reproduce this issue? We haven't seen this issue before, so it is likely something specific to the test code or the preprocessor or plugins code, etc.
