### ISSUE TITLE
`cypress runner window` overlaps with results panel

### ISSUE THREAD

**Issue by thedoublejay** [cypress-io/cypress#18058]
### Current behavior

When running via Cypress Dashboard, cypress runner window overlaps with the sidebar making it difficult to check screenshots or videos. It occurred on 8.3.1 version, previous Cypress versions don't have this issue. 

<div>
<img  src="https://user-images.githubusercontent.com/25013382/132826913-ddb7ff7e-7c76-4c91-a775-e178181103c9.png" />
</div>

### Test code to reproduce

Here is our cypress dashboard with videos - https://dashboard.cypress.io/projects/oqk3fk/runs/2116/test-results/d887a64a-73c4-478c-8bac-cf083570a5b2

### Cypress Version

8.3.1

**Comment by jennifer-shehane** [comment]
This should not be happening. This doesn't happen in every case so there must be something about the app rendering in your case. 

- Are you able to reproduce this running locally on the same browser as is run in CI?
- When running locally, if you downgrade to 8.3.0 - does the app render correctly again?
- If possible, can you provide a reproducible example?

**Comment by thedoublejay** [comment]
@jennifer-shehane I have reproduced it also for 8.3.0. I'm not sure what changed but before, it was rendered on the right side. Now, when the app auto-scales, it aligns it to the left, pushing it under the sidebar. 

It's the same locally, but it can be fixed with browser zoom but I think there's no zoom option for cypress config.
