### ISSUE TITLE
EPERM: operation not permitted, unlink XX

### ISSUE THREAD

**Issue by devmeqa** [cypress-io/cypress#18060]
### Current behavior

Hi everyone,

I'm running my Cypress tests in my ADO CI pipeline in Chrome and Firefox. As of Tuesday when Chrome was upgraded to version 93 I cannot run my tests anymore in Chrome headed (it seems to be fine headless though)

I'm getting the following error :
```
Timed out waiting for the browser to connect. Retrying...
EPERM: operation not permitted, unlink 'C:\Users\tfsbuild\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable\run-13636\CypressCache\Default\Cache\data_1'
Error: EPERM: operation not permitted, unlink 'C:\Users\tfsbuild\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable\run-13636\CypressCache\Default\Cache\data_1'
```

Working pipeline chrome 92 on Tuesday :

![image](https://user-images.githubusercontent.com/90473783/132897242-ed6d6ac2-e6b9-42f3-932d-f4c897f5da87.png)

Failing pipeline chrome 93 :

![image](https://user-images.githubusercontent.com/90473783/132897383-e879be2e-155f-46c7-8946-3db3d3d3ceea.png)

### Test code to reproduce

Attempt to run tests in ADO with chrome 93 ? 

### Cypress Version

6.5.0 and 8.3.1

### Other

I tried to upgrade to Cypress 8.3.1 and the same thing happened 

Note : 
Before I upgrade cypress,  I didn't have to specify --headed when running the tests and it looks like they were running headed based on the screenshot, it shows "Chrome 93" (it would show headless if they run headless)
When I upgraded to the latest version of Cypress I had to specify --headed, any idea why ?

**Comment by jennifer-shehane** [comment]
Could you try following [these instructions](https://on.cypress.io/troubleshooting#Clear-App-Data) to Clear App Data?

**Comment by devmeqa** [comment]
@jennifer-shehane I already did that :( The pipeline was working fine and with no code changes but just the chrome upgrade it started failing all of a sudden.

- I deleted the entire content of the folder "C:\Users\tfsbuild\AppData\Roaming\Cypress" which contains "cy\production"
- I restarted the server in case something was locked 
- I ran npx cypress cache clear
- I updated Cypress to the latest
- I ran cypress info and everything looks fine 
```
- Detected 1 browser installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 93.0.4577.63
  - Executable: C:\Program Files\Google\Chrome\Application\chrome.exe

```

**Comment by MKA01** [comment]
@devmeqa I have the same problem with Cypress running in Jenkins enviroment. None of found fixes worked for me. As a workaround I downloaded older version of Chrome from this site [.](https://chromium.cypress.io/win64/stable/92.0.4515.159) Then I forced cypress to run with custom Chrome version with this command "npx cypress run --browser "path\to\chrome\folder\chrome.exe". That allows for tests to run. For me problem started at 03.09 and I hope it will be somehow fixed.

**Comment by devmeqa** [comment]
Thanks @MKA01 unfortunately that workaround can only be temporary. Waiting for @jennifer-shehane  to provide an update on this.

**Comment by lalwk** [comment]
It looks like Chrome version 94 is running fine again.

**Comment by agelico** [comment]
Have same issue with headed Chrome, Cypress 8.4.1 and TeamCity CI: get this error after (any) single successfully run spec. Locally all works fine.

What I've gathered from debug is that it tries to close/open browser and fails. Or something. Tried to move to Firefox for now, but it totally fails to connect in CI. Have no idea what's going wrong there and how to fix it.
