### ISSUE TITLE
when using cy.type('{enter}'); on a button it does not send a click event.

### ISSUE THREAD

**Issue by lifeiscontent** [cypress-io/cypress#18068]
### Current behavior

cy.get('button').type('{enter}'); does not send a click event.

the behavior of userEvent from @testing-library/user-event works as expected, but cypress does not.

### Desired behavior

I'd expect type() to behave correctly for buttons as they are also a form of inputs.

### Test code to reproduce

I used https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html as a test case.

this works:

```js
    it('expands its region when {enter} is pressed', () => {
      cy.get('@buttons').then($buttons => userEvent.type($buttons[0], '{enter}'));
      cy.get('@buttons').eq(0).should('have.attr', 'aria-expanded', 'true');
      cy.get('@buttons').eq(0).should('have.attr', 'aria-disabled', 'true');
      cy.get('@regions').eq(0).should('not.have.attr', 'hidden');
    });
```

this does not:

```js
    it('expands its region when {enter} is pressed', () => {
      cy.get('@buttons').eq(0).type('{enter}');
      cy.get('@buttons').eq(0).should('have.attr', 'aria-expanded', 'true');
      cy.get('@buttons').eq(0).should('have.attr', 'aria-disabled', 'true');
      cy.get('@regions').eq(0).should('not.have.attr', 'hidden');
    });
```

### Cypress Version

8.3.1

**Comment by marktnoonan** [comment]
Hi @lifeiscontent, this caught my eye as I tested something similar last week. I could not reproduce the issue. With the URL you provided I wrote the following test, which passes just fine on the same Cypress version:

```js
describe("Button {enter} test", () => {
  it("Enter toggles accordion panels", () => {
    cy.visit("https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html");

    cy.get("button").eq(1).type("{enter}"); // expand the second panel
    cy.get("button").eq(1).should("have.attr", "aria-expanded", "true"); // it has the attribute
    cy.get("[role=region]").eq(0).should("have.attr", "hidden"); // first panel is now hidden
    cy.get("button").eq(0).type("{enter}"); // expand the first panel
    cy.get("button").eq(0).should("have.attr", "aria-disabled", "true"); // first button is now disabled
    cy.get("button").eq(1).should("have.attr", "aria-expanded", "false"); // the second panel now has false
    cy.get("[role=region]").eq(0).should("not.have.attr", "hidden"); // first panel is visible
  });
});
```

This suggests to me that in the `type` command is working as expected on buttons, and your issue might be something else.

**Comment by lifeiscontent** [comment]
@marktnoonan I see the issue now, its because I registered my event listener onto the parent, not the button itself, but regardless that event bubbles to the parent, which I believe should also happen in cypress.

**Comment by lifeiscontent** [comment]
@marktnoonan yeah, I get that, but the event should still bubble as it does in any browser https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event

**Comment by marktnoonan** [comment]
@lifeiscontent Oh I misread your previous comment, my bad. I thought you meant your Cypress selector was on the parent, which was confusing.

So anyway, to look at your accordion example more closely... when my test types `{enter}` with the 2nd button as the subject, the 2nd panel opens. The code that handles switching active panels, updating aria attrs, and all that stuff, is all in a `click` event listener on the wrapper `div` of the accordion. So as far as I can tell the keyboard event for that `{enter}` on the button is working correctly. It causes a `click` event to be fired, which bubbles normally up to the handler that switches tabs. If it didn't the test would fail as the `type()` would do nothing.

Can you share a reproduction with the bug happening, or correct me on something above?
