### ISSUE TITLE
The component rendering is taking more time in cypress tests then the normal browser

### ISSUE THREAD

**Issue by Optimus2297** [cypress-io/cypress#18074]
### Current behavior

The components are taking more time to render in cypress tests then the  normal browser. I have stubbed all the api's, except the login api, its a single page application, the components are developed using polymer.  I am visiting an application in cypress test, and doing different actions like clicking menus and its taking more time then what it takes in a normal browser to render the components in the application. Specifically the loader is getting rendered for an extended period of time even if the component is loaded. The behavior is random i.e. sometimes it works fine and sometimes it takes time. So what this is causing is I am using cypress-image-snapshot for image comparison and the testcases are failing because of this, the screenshots are captured of different rendered screens.

### Desired behavior

The websites visited in cypress testcases should render the components in the same time as normal browser.

### Test code to reproduce

Due to security reasons cant share any reproducible code

### Cypress Version

8.2.0

**Comment by jennifer-shehane** [comment]
There's not much we'll be able to look at without a reproducible example we can run to see the timing differences. Can you reduce tht example to a small subset of the app that we could run? Otherwise we'll have to close the issue.
