### ISSUE TITLE
Error launching Browser 

### ISSUE THREAD

**Issue by jesmarcor** [cypress-io/cypress#18079]
### Current behavior

I try to launch a test this error appear when I use Chrome or Firefox but I don't have any problem when I use Electron, I clear app data but not resolve the problem
![Error](https://user-images.githubusercontent.com/10673095/133122082-40c90f41-895f-4c53-9b04-25c185a2c418.PNG)

### Desired behavior

This should run a test in the Chrome browser 

### Test code to reproduce

Launching any example

### Cypress Version

8.3.0

**Comment by jesmarcor** [comment]
Can you help me @jennifer-shehane please??

**Comment by jesmarcor** [comment]
can you help me @thinway me?

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Is this still happening with 8.5.0?
