### ISSUE TITLE
Cypress.version is undefined when running component tests

### ISSUE THREAD

**Issue by rlucha** [cypress-io/cypress#18082]
### Current behavior

Tested on v8.0.0 and v8.3.1.

When configuring `cypress-terminal-report` as in [the instructions](https://github.com/archfz/cypress-terminal-report/blob/master/README.md) and running `npx cypress open-ct` an error is displayed in the tests related to an invalid version of Cypress.

`cypress-terminal-report` is trying to access Cypress.version to check for compatibility but it is undefined *only* when running component tests, not normal Cypress tests.

### Desired behavior

Cypress.version should be properly set when running component tests.

### Test code to reproduce

Add a `console.log(Cypress.version)` in any Cypress Component test to verify.

### Cypress Version

8.3.1

**Comment by jennifer-shehane** [comment]
I'm not seeing this behavior when running in Cypress 8.3.1 during `cypress open-ct` just doing a simple console.log of it in a test. 

```js
it('renders learn react link', () => {
  cy.get('a').contains('Learn React');
  console.log(Cypress.version)
});
```

<img width="738" alt="Screen Shot 2021-09-15 at 2 10 13 PM" src="https://user-images.githubusercontent.com/1271364/133494926-d58185f8-5956-49f9-90c4-0a872688ba81.png">

**Comment by rlucha** [comment]
I'll prepare a repo to reproduce, thank you.
