### ISSUE TITLE
NPM warnings when executing 'npm install --save-dev cypress'

### ISSUE THREAD

**Issue by stevenmchaves** [cypress-io/cypress#18092]
### Current behavior

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[                  ] - reify:rxjs: timing reifyNode:node_modules/lodash Completed in 4369ms
```

Hangs. I need to do `Ctrl+Z` to get out.

Running the command again completes the installation successfully.

### Cypress Version

8.3.1

### Package Manager

npm

### Operating system

Windows

**Comment by jennifer-shehane** [comment]
The npm warnings will not hang the terminal process. They are just warnings and do not affect the exit code or run of install. 

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here? There's likely something else stalling the install.

**Comment by stevenmchaves** [comment]
I can no longer duplicate the issue. Going to close this item.
