### ISSUE TITLE
--env doesn't work when using globbing/filename expansion in --spec

### ISSUE THREAD

**Issue by simonhaenisch** [cypress-io/cypress#1810]
### Is this a Feature or Bug?

Bug

### Current behavior:

```
cypress run --env foo=bar --spec=cypress/integration/**/*.js
```

does not add `foo` to the environment variables (`cy.env('foo')` returns `undefined`). It works though if I don't use globs in the spec path.

### Desired behavior:

I want to be able to use globbing/filename expansion in the `--spec` argument and also pass in an environment variable using `--env`.

**Use case:** I'm running the same tests on two different projects (using `data-cy` props) that implement basically the same thing, but one has additional routes. (Yes, I know this is painful to maintain, but it's a three year old codebase and tests are the first step to start refactoring).

### Workaround:

This works:

```
CYPRESS_foo=bar cypress run --spec=cypress/integration/**/*.js
```

I'm ok with that workaround but thought I'd leave this here FYI.

### Versions

`cypress@2.1.0`, latest Chrome, macOS 10.13.4

**Comment by jennifer-shehane** [comment]
The `--spec` flag accepting globbing is new to 3.0, could try updating Cypress to 3.0 and ensure it is working in that version please?

**Comment by simonhaenisch** [comment]
Globbing is working in `2.1.0` for me (using `zsh`)... just installed `3.0.0` (nice work 👏 ), but it behaves the same (`--env` gets ignored).

Instead of globbing it would also be nice to be able to set multiple `integrationFolders` (as an array).

**Comment by jennifer-shehane** [comment]
You can set multiple spec files like:

```bash
cypress run --spec cypress/integration/filter.spec.js, tests/users.spec.js
```

**Comment by jennifer-shehane** [comment]
I am not seeing the issue you are describing. 

I just noticed you said that `cy.env('foo')` is `undefined`. To access environment variables, you should use `Cypress.env('foo')` as detailed [here](https://on.cypress.io/env), can you see if this is `undefined` for you?

**Comment by simonhaenisch** [comment]
Sorry that was a typo, I am using `Cypress.env()`.

I'm invoking cypress like this:

```
cypress run --env foo=bar --spec cypress/integration/{user,admin}/**/*.js
```

Then in `support/index.js` I do:

```js
if (Cypress.env('foo') !== 'bar') {
  throw new Error(`Expected foo to be bar but got ${Cypress.env('foo')}`);
}
```

And I get:

```
1)  An uncaught error was detected outside of a test:
     Uncaught Error: Expected foo to be bar but got undefined
```

When I don't use any wildcards in the `--spec` arg, it works. I don't want to pass in a comma-separated list of specs, that is neither scalable nor maintainable.

**Comment by brian-mann** [comment]
Quote your --spec argument or use equals.

`--spec=foo` or `--spec 'foo'`

**Comment by simonhaenisch** [comment]
On `cypress@3.0.1` now, tried both `bash` and `zsh`... using quotes I get this error:

> Can't run because no spec files were found.
>
> We searched for any files matching this glob pattern:
>
> `cypress/integration/{user,admin}/**/*.js`

I figured out that the `{dir1,dir2}` syntax doesn't actually work.

This works in both `bash` and `zsh`:

```
ls cypress/integration/{dir1,dir2}/*.js
```

This works in `zsh` only:

```
ls cypress/integration/{dir1,dir2}/**/*.js
```

Neither of the expressions works properly in Cypress.

When using the braces (`{}`) with the equals (`--spec=...`) syntax, it runs but it only takes specs from the last folder included in the braces. Using a comma-separated specs list instead of the braces works:

```
--env foo=bar --spec=cypress/integration/dir1/**/*.js,cypress/integration/dir2/**/*.js
```

Would be interested to know how exactly you expand/glob the given expression? Do you run it as a system command with `ls` and parse the result? If so, would it be using `bash` or my current shell?

**Comment by brian-mann** [comment]
We don’t run it in the system at all. The problem is that your shell is modifying what it sends into Cypress as an argument. 

The spec argument needs to go in as a literal because we pass it off to the glob npm module. You can pass whatever it supports.

You can use DEBUG=cypress:* cypress run to see what we receive.

**Comment by simonhaenisch** [comment]
Thanks for that info, that's what I needed to know...

According to [isaacs/node-glob#glob-primer](https://github.com/isaacs/node-glob#glob-primer) this syntax works:

```
--env foo=bar --spec='cypress/integration/@(dir1|dir2)/**/*.js'
```
