### ISSUE TITLE
Progress callback from ng-file-upload library is never called in FF starting from Cypress v7.6.0 

### ISSUE THREAD

**Issue by anastasiaZen** [cypress-io/cypress#18106]
### Current behavior

My company is using Cypress version 5.6.0 and running Chrome/FF/Edge. We wanted to upgrade to 8.3.1 but then discovered the blocking for us issue: file upload is 'stuck' in FF and never completes. Here are some investigation details:

- progress callback from [ng-file-upload AngularJS library](https://github.com/danialfarid/ng-file-upload) is never called in Firefox (it works in Chrome though) using Cypress 8.3.1. Tried to upgrade that library from 12.0.4 to latest 12.2.4 but that doesn't help. Looks like problem lays somewhere in Cypress, not in the ng-file-upload library (also because it works without issues out of the Cypress environment).
- seems that it's broken in Cypress v7.6.0+, in v7.5.0 and lower it works.
- updated to latest axios and cypress-file-upload, but it didn't help.

### Desired behavior

file upload succeeds 

### Test code to reproduce

Additional remark:
There are some tricks in ng-file-upload library itself, but that perfectly works. 
```
if (!config.disableProgress) {
      config.headers.__setXHR_ = function () {
        return function (xhr) {
          if (!xhr || !xhr.upload || !xhr.upload.addEventListener) return;
          config.__XHR = xhr;
          if (config.xhrFn) config.xhrFn(xhr);
          xhr.upload.addEventListener('progress', function (e) {
            e.config = config;
            notifyProgress(getNotifyEvent(e));
          }, false);
          //fix for firefox not firing upload progress end, also IE8-9
          xhr.upload.addEventListener('load', function (e) {
            if (e.lengthComputable) {
              e.config = config;
              notifyProgress(getNotifyEvent(e));
            }
          }, false);
        };
      };
    }
```

So there is some Cypress commit between versions 7.5.0 and 7.6.0 that caused the problem.

### Cypress Version

7.6.0+

**Comment by shambig** [comment]
Addition:
I looked into commits between 7.5.0 and 7.6.0 and the found [the one](https://github.com/cypress-io/cypress/commit/66303f63313f227d79d9d12efde1df18a6d69ed7) which possible caused the problem. Just trying to be helpful.

We use ng-file-upload without  any modifications, just like their readme suggests:

```
Upload.upload({
    url: 'upload url',
    data: {file: file}
}).then(function (resp) {
    // success callback
}, function (resp) {
    // error callback
}, function (evt) {
    // progress callback
});
```

We use progress callback to update progressbar.
None of callbacks are fired since 7.6.0+. Call just hangs in pending state when I look in devTools. All works for years outside Cypress env, and also with Cypress <= 7.5.0.

**Comment by anastasiaZen** [comment]
@jennifer-shehane Hi! I'd really appreciate if you could take a look at this issue. We reported it some time ago but didn't any reaction on it.

**Comment by LaurensLeeuwis** [comment]
I found this code in v7.6.0:

```
shouldCorrelatePreRequests = () => {
    if (!this.browser) {
      return false
    }

    const { family, majorVersion } = this.browser

    return family === 'chromium' || (family === 'firefox' && majorVersion >= 86)
  }
```

I did a small test, and indeed: Firefox 84 works as expected with Cypress 7.6.0, while Firefox 97 doesn't work.

Is there a way for me to configure so shouldCorrelatePreRequests is false?
