### ISSUE TITLE
cy.wait timeout on cy.intercept - cypress v8.3.1

### ISSUE THREAD

**Issue by sumithjain85** [cypress-io/cypress#18109]
### Current behavior

cy.wait is failing to get response for cy.intercept -- Due to site is internal can't provide full code.

![image](https://user-images.githubusercontent.com/90774611/133443598-06ad82fa-5d1d-447c-92ea-6215ec2650e1.png)

### Test code to reproduce

```js
cy.intercept('POST','/api').as('queryList'); (also tired -- cy.intercept('/api').as('queryList');
cy.get('element').should('contain','text');
cy.wait('@queryList').its('response.statusCode').should('equal',200); 
```

### Cypress Version

8.3.1

**Comment by jennifer-shehane** [comment]
What is the url you're trying to match, perhaps the url doesn't match exactly. Is this a new issue that occured after updating Cypress or this has never worked?

**Comment by sumithjain85** [comment]
Thanks for quick response - this document from cypress helped to resolve the issue - https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-7-0

**Comment by TubaCytomate** [comment]
I'm still facing the same problem.
![image](https://user-images.githubusercontent.com/83274203/134139788-4dd8d1da-99ef-4f9b-9fb7-e70c536cde7a.png)

**Comment by TubaCytomate** [comment]
I'm still facing the same problem. Version is 8.4.1
