### ISSUE TITLE
Cypress does does not open website and does not download assets

### ISSUE THREAD

**Issue by ismailsobhy** [cypress-io/cypress#18108]
### Current behavior

 When trying using cy.visit on a remote web site, files such as index.js and vendor.js are not downloaded

![image](https://user-images.githubusercontent.com/32613878/133424522-cadd488d-7eb9-49e9-aebb-04d4d876bd87.png)

According to the documentation https://docs.cypress.io/guides/guides/web-security#Limitations.

> When Cypress first loads, the internal Cypress web application is hosted on a random port: something like http://localhost:65874/__/.

> After the first cy.visit() command is issued in a test, Cypress changes its URL to match the origin of your remote application, thereby solving the first major hurdle of same-origin policy. Your application's code executes the same as it does outside of Cypress, and everything works as expected.

What happens, the remote application remains localhost with the generated port , does not change the URL.

![image](https://user-images.githubusercontent.com/32613878/133424333-990ec158-200c-4000-907c-2a0f79d62087.png)

I am assuming it is the problem that cypress does not change the url, please assist. Please clarify if it is the reason and if not please advise.

I tried changing the port, chromeWebSecurity to false ,and editing host file, but no hope.

This what appears, not able to find the locators.
![image](https://user-images.githubusercontent.com/32613878/133445050-4d8a6e36-e07f-41ed-a7cf-9a317fdb502c.png)

### Desired behavior

The website should appear normally and switch to right url, index and vendor should appear and all the assets should be downloaded.

### Test code to reproduce

Cypress.json
`{
    "reporter": "mochawesome",
    "chromeWebSecurity":false
}`

webConfig.json (the url is removed from the example)

`{
    "pageLoadTimeout": 60000,
    "defaultCommandTimeout": 4000,
    "extends": "./cypress.json",
    "baseUrl": "http://xxx.xxxx.net:443"
}`

Normal visit

`cy.visit("/login");`

### Cypress Version

8.4.0

### Other

Chrome 93
Node 14.6.0

**Comment by jennifer-shehane** [comment]
>When Cypress first loads, the internal Cypress web application is hosted on a random port: something like http://localhost:65874/__/.

This should only happen if you haven't set the `baseUrl`. If you've set the `baseUrl`, as it seems you have, then Cypress navigates directly to that baseUrl.

**Comment by ismailsobhy** [comment]
Yes, it get the baseUrl and the  it tries to get the assets it supposed to get and the result is 404 and pending in network tab. If I try to open the same website from normal Chrome or edge (not from cypress). It works normally.

**Comment by ismailsobhy** [comment]
Yes, it get the baseUrl and the  it tries to get the assets it supposed to get and the result is 404 and pending in network tab. If I try to open the same website from normal Chrome or edge (not from cypress). It works  
 normally.

**Comment by ismailsobhy** [comment]
Yes, it get the baseUrl and the  it tries to get the assets it supposed to get and the result is 404 and pending in network tab. If I try to open the same website from normal Chrome or edge (not from cypress). It works  
 normally.

**Comment by ismailsobhy** [comment]
Yes, it get the baseUrl and the  it tries to get the assets it supposed to get and the result is 404 and pending in network tab. If I try to open the same website from normal Chrome or edge (not from cypress). It works  
 normally.

**Comment by ismailsobhy** [comment]
@jennifer-shehane I tried all other browsers, the problem still happens.

**Comment by ismailsobhy** [comment]
@jennifer-shehane we found the problem, the website is defined with http on port 443. Cypress used the visit the website with port 443 (this works) and then tries to load the assets on port 80 and then it fails with 404. This means and correct me if I am wrong, Cypress depends on the standard that http should be always on port 80 and https on port 443, correct?. Is there a way to use a non standard port when connecting to the server?
