### ISSUE TITLE
Wait for page finish reloading after click

### ISSUE THREAD

**Issue by jkohlin** [cypress-io/cypress#18104]
### What would you like?

Cypress could be perfect.
In wordpress, Woocommerce reloads the checkout page (not a get request, a javascript reload) when you click a link to change billing type of user. That reload takes a while and then then DOM is rewritten. 
This means, If I do `cy.get('billingtypeofuser').click()`, then `cy.get('stripe')` is detached from the DOM and can't be found. Adding a `cy.wait(3000)` sometimes help, but just as often breaks. 

We need a reliable way to wait for a `location.reload`, kind of like the asynchronous jQuery function `$('document').on('ready', () => {})`

### Why is this needed?

Many tests fail because elements expected to be there are detached from the DOM when a page is reloading after a click. wait(time) is not reliable because in best case scenario, you waisted 4 seconds because the pageload was faster, worst case scenario, the 4s wasn't enough and the test fails.

**Comment by jennifer-shehane** [comment]
We’ve made several improvements to our command chaining to prevent much of the detached dom issues there used to be. Please try updating to latest. Closing as addressed.
