### ISSUE TITLE
Skip Cypress on npm instal

### ISSUE THREAD

**Issue by Mugane** [cypress-io/cypress#18110]
So what was the solution? It's noted that it was released but no mention of what it actually is/how to use it.

Released in [`1.1.4`](https://docs.cypress.io/guides/references/changelog.html#1-1-4).

_Originally posted by @brian-mann in https://github.com/cypress-io/cypress/issues/1005#issuecomment-349850006_

**Comment by TomCaserta** [comment]
> There is now a new CYPRESS_SKIP_BINARY_INSTALL flag you can pass during npm install which skips the binary installation after the cypress npm module completes its installation. Fixes #1005.

This means when installing you can do:

`CYPRESS_SKIP_BINARY_INSTALL=true npm install`

Or any other way you would set an environment variable & installing your dependency. It just needs to be set when installing your project.

**Comment by jennifer-shehane** [comment]
Closing as resolved.

**Comment by Mugane** [comment]
Could we reopen? I wonder if there's a way to skip the npm install of cypress? That's the one that is big and takes forever. I realize that it's a bit out of scope but hoping someone has had to manage a dev/deploy situation and found a good way to handle the skip in spite of an entry in package.lock/package.json being committed to git.
