### ISSUE TITLE
Dayjs/Typescript - cannot extend Cypress interface

### ISSUE THREAD

**Issue by martin-pikalek** [cypress-io/cypress#18115]
### Current behavior

![Screenshot 2021-09-16 at 3 58 07](https://user-images.githubusercontent.com/57229273/133536937-433c906a-f347-4370-b0f6-c988c2b99d19.png)
![Screenshot 2021-09-16 at 4 01 18](https://user-images.githubusercontent.com/57229273/133537154-1400f7df-541d-402e-beef-9f0bb174dc5f.png)

### Desired behavior

As dayjs is recommended as replacement for momentjs I would like to extend Cypress interface for custom function in same way as it is possible to extend Chainable interface for custom commands. 

### Test code to reproduce

// support/index.ts
import * as dayjs from 'dayjs'
import * as utc from 'dayjs/plugin/utc'

dayjs.extend(utc)

declare namespace Cypress {
    interface Cypress {
        dayjs: dayjs.Dayjs;
    }
}

// testfile.ts
const time = Cypress.dayjs().add('1', 'h').format('H:00')

### Cypress Version

8.3.0

**Comment by martin-pikalek** [comment]
I found a solution:
It is possible to extend Cypress interface under global declaration as in example below - 

declare global {
    namespace Cypress {
        interface Cypress {
            dayjs(): dayjs.Dayjs
        }
    }
}

**Comment by martindzejky** [comment]
Thanks @martin-pikalek, I was also missing the `declare global` part. This is how to extend the `Chainable` interface to add custom commands:

```
declare global {
    namespace Cypress {
        interface Chainable {
            customCommand: () => void;
        }
    }
}
```

This should be fixed [in the docs over here](https://docs.cypress.io/guides/tooling/typescript-support#Types-for-custom-commands). Do you mind re-opening this issue?
