### ISSUE TITLE
Promises call inside cy.wait don't fail tests

### ISSUE THREAD

**Issue by Octirke** [cypress-io/cypress#1811]
### Current behavior:

I have something that annoys me a lot. I'm testing an AWS S3 upload with cypress. The last step of my test is to query the AWS S3 bucket with the js AWS SDK. The end of my test looks like this :
```js
    // We wait on our previously tagged request and then verify that the file exists on S3 !
    cy.wait('@uploadPut').then(resp => {
      const etag = resp.response.headers.etag
      const params = {
        Bucket: Cypress.env('videoBucket'),
        Key: fileName + 'jfj' // introduce error here
      }
      // This crashes (uncaught promise) but everything still green with Cypress 
      s3.headObject(params).promise()
        .then(data => {
          expect(data.ContentType).to.equal(type)
          expect(data.ETag).to.equal(etag)
        })

      // Cypress is not too kind with Promises throwing error in cy.wait, e.g

      // This expect crashes but main test is still green
      // Promise.resolve('wow').then(resp => {
      //   expect(null).not.to.be.null
      // })

      // This expect crashes too but main test is still green
      // return s3.headObject(params).promise().then(res => {
      //   expect(null).not.to.be.null
      // })
    })
```

Promises are behaving very strangely inside cy.wait() and I didn't find any problem similar to mine. I'm just trying to make the test fail gracefully with a good error message. The only workaround I found was to return the call to s3.headObject(params).promise(). That will make the test fail but the error message is really bad.
![error message](https://i.imgur.com/wfDZuqS.png)
### Versions

Cypress 2.1.0, Latest for the everything else

**Comment by escape-llc** [comment]
If you use `cy.wrap` to manage the promise, it works as expected.  The "getPdfVersion" function resolves a promise (for an ArrayBuffer) with the extracted text, then provides an "outer" promise to examine it.

	cy.wrap(helpers.getPdfVersion(pdf)).then(prefix => {
		expect(prefix).to.eq(helpers.PKZIP);
	});
