### ISSUE TITLE
before hook still reruns on Cypress 8.4.0

### ISSUE THREAD

**Issue by JohnnyTheBoy** [cypress-io/cypress#18128]
### Current behavior

before hook triggers multiple times inside one describe() block.

### Desired behavior

Before hook inside one describe() block should be triggered only once.

### Test code to reproduce

describe("Testing", () => {

before(() => {
    cy.log("Before hook is called!");
});

beforeEach(() => {
    cy.log("Before each hook is called");
});

it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });

it("says hi", () => {
    cy.visit("www.google.com");
    cy.log("Hi!");
});

it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
it("do something", () => { expect(true).to.be.eq(true); });
});

### Cypress Version

8.4.0

### Other

![cypress_before_hook_issue](https://user-images.githubusercontent.com/8955489/133646667-b21b949a-7c59-45af-8fa3-f6ad8b6c83f4.png)
I'm very surprised that after 8.4 update this thing still doesn't work. This is so simple test and yet nobody tried it before merge/push... sad

**Comment by sainthkh** [comment]
@flotwig When domain changes, Cypress reloads and it reruns the `before()`. I don't think it's a right behavior, right?

**Comment by jennifer-shehane** [comment]
See https://github.com/cypress-io/cypress/issues/17940
