### ISSUE TITLE
Add the feature to remove the focus on inputs

### ISSUE THREAD

**Issue by udhayaas97** [cypress-io/cypress#18125]
### What would you like?

Add a feature to removing the focus on input element

### Why is this needed?

I am focusing the input by the following  code
```
cy.get('input[type=email]').focus();
````
Now I need to remove the focus on email input

**Comment by bahmutov** [comment]
cy.blur does not work?

**Comment by udhayaas97** [comment]
@bahmutov  , It's working. Thanks for your reply
