### ISSUE TITLE
Is there a way when using selector to copy to clipboard directly after selecting an element?

### ISSUE THREAD

**Issue by frederikhors** [cypress-io/cypress#18126]
### What would you like?

Is there a way when using selector to copy to clipboard directly after selecting an element without clicking on the small (almost unusable on big screens) copy button?

An option in cypress.json at least?

### Why is this needed?

Using it on big screens it's awful. And it can speed up the work of test writers a lot!

**Comment by jennifer-shehane** [comment]
@frederikhors Do you mean this button in the selector playground?

<img width="747" alt="Screen Shot 2021-09-16 at 8 45 47 AM" src="https://user-images.githubusercontent.com/1271364/133623578-7dd62ec4-394f-4015-b92c-e1a00d95582e.png">

**Comment by frederikhors** [comment]
Yep. I would like to avoid this click each time. It is unnecessary IMO. I just click the element et voilà!

**Comment by frederikhors** [comment]
Yep. I would like to avoid this click each time. It is unnecessary IMO. I just click the element et voilà!
