### ISSUE TITLE
Erro Whoops, the Cypress extension has disconnected.

### ISSUE THREAD

**Issue by CaetanoLucas** [cypress-io/cypress#18131]
### Current behavior

Atualmente só consigo executar testes (testes leves como um teste de login por exemplo) pelo navegador Electron, nos demais, como: Chrome(Versão 93.0.4577.82 (Versão oficial) 64 bits), Firefox(92.0 (64-bits)) e Edge(Versão 93.0.961.47 (Compilação oficial) (64 bits)) está dando o erro (Whoops, the Cypress extension has disconnected.) conforme o print abaixo:
![image](https://user-images.githubusercontent.com/56043570/133670588-551f23dd-4020-438e-b8fe-c5576c31a30c.png)

### Desired behavior

Conseguir executar testes em utilizando todos os navegadores instalados no sistema operacional. 

### Test code to reproduce

https://github.com/CaetanoLucas/Desafio

### Cypress Version

8.4.0

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by drilon241** [comment]
Hi 👋 

I'm getting similar error when trying to run the [cypress lighthouse example](https://glebbahmutov.com/blog/cypress-lighthouse/) by @bahmutov 

Running with Chrome Version 110.0.5481.177 (Official Build) (x86_64)
![Screenshot 2023-03-16 at 15 56 35](https://user-images.githubusercontent.com/9594368/225678320-455050d0-63b0-4b27-8e36-0a3b9ab04263.png)

Any help is appreciated, as we are looking to add lighthouse tests to our setup. We already use cypress for our integration & e2e tests.

**Comment by bhavanareddymahakala** [comment]
Hi,

I’m getting same error while running lighthouse example. I could test a Lighthouse sample before migrating to cypress 12 but after upgrade I’m not able to test a lighthouse sample and getting same error as above. Any help is appreciated. Running with chrome 110

**Comment by bhavm24** [comment]
Hi Team,

I’m getting same error while running lighthouse example. I could test a Lighthouse sample before migrating to cypress 12 but after upgrade I’m not able to test a lighthouse sample and getting same error as above. Running with chrome 110. Any help is appreciated.

**Comment by spurthiprasad** [comment]
Hi all,
I am also getting the above exception on calling cy.lighthouse. 
Running on chrome version 111.0.5563.64  and Cypress version: 9.7.0
This was running perfectly fine a week ago. 
Any help is appreciated.

**Comment by ghost** [comment]
Hi all,
I am also getting the above exception on calling cy.lighthouse.
Running on chrome version 111.0.5563.64 and Cypress version: 12

**Comment by bhavm24** [comment]
Refer to https://github.com/mfrachet/cypress-audit/issues/207. Looks like the issue has been resolved.
