### ISSUE TITLE
The studio does not work with the shadow dom

### ISSUE THREAD

**Issue by eggp** [cypress-io/cypress#18158]
### Current behavior

Studio edit cannot handle the shadow dom, even though "includeShadowDom" is set to true.
In the attached gif I show that in the studio edit mod it was not able to detect the shadow dom and recorded an incorrect click and it could not detect typing either.
![Peek 2021-09-20 12-21](https://user-images.githubusercontent.com/1015211/133997214-f39e3603-c982-49fb-a32f-ee60e4a69b51.gif)

### Test code to reproduce

GitHub repo: https://github.com/eggp/cypress-studio-shadow-dom-error
start:
1. npm install
2. ng serve
3. npx cypress open
4. run shadow-dom.spec.js
5. edit "Test selector with studio" in studio
6. click or type in the input

### Cypress Version

8.4.1

**Comment by AdrianRRo** [comment]
Same problem here, did you found any solution?

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/26146
