### ISSUE TITLE
Is it possible to add the author name next to the test?

### ISSUE THREAD

**Issue by shash-hegde** [cypress-io/cypress#18155]
### What would you like?

Is it possible to add the test author name next to the actual test.
Some times it becomes difficult to see who has actually authored the test 

```js
it('Test case 1', { author: 'User 1' }, () => {

})

it('Test case 2', { author: 'User 2' }, () => {

})
```

### Why is this needed?

This will help to assign the test cases to correct QA Engineer during failures especially during Releases

**Comment by jennifer-shehane** [comment]
The test does accept a second argument, which is an object for test configuration. You could pass in an author key into that object, for your own use, although it won't functionally do anything within Cypress itself. 

```js
it('visits the site', { author: 'Jennifer Shehane' }, () => {
  cy.visit('https://example.cypress.io/todo')
})
```
