### ISSUE TITLE
Getting error "Cannot read properties of null (reading 'uuid')"

### ISSUE THREAD

**Issue by patelsmit2890** [cypress-io/cypress#18152]
### Current behavior

I've written 3 cypress test cases but 2nd test case is showing passed but it's not getting executed and showing error as :
**Uncaught TypeError: Cannot read properties of null (reading 'uuid')**

![image](https://user-images.githubusercontent.com/8512175/133929817-dfcc1fd5-f5aa-49c3-8c6f-ef90c5850a1a.png)

### Test code to reproduce

Code:

```js
describe('Login', () => {
  const baseUrl = Cypress.env('CYPRESS_BASE_URL')
  const oktaBaseUrl = Cypress.env('CYPRESS_OKTA_BASE_URL')
  Cypress.config({ force: true, baseUrl })

  after(() => {
    cy.contains('a', 'Sign Out')
      .click()
  })

  it('it redirects to OKTA, logs in, and redirect to vstaas', () => {
    cy.visit(`${ baseUrl }/hvstaas/home`)
    cy.url()
      .should('include', `${ baseUrl }/hvstaas/home`)
    cy.url()
      .should('include', `${ oktaBaseUrl }`)
    cy.get('input[id="okta-signin-username"]')
      .type('username')
    cy.get('input[id="okta-signin-password"]')
      .type('pwd')
    cy.get('input[id="okta-signin-submit"]')
      .click()
  })

  it('the authToken cookie exists', () => {
    cy.getCookie('authToken').should('exist').then(cookie => {
      expect(cookie).to.have.property('value')
    })
  })

  it('Sign Out', () => {
    cy.contains('a', 'Sign Out')
      .click()
  })
})
```

### Cypress Version

8.4.0

**Comment by patelsmit2890** [comment]
Console error:
Uncaught TypeError: Cannot read properties of null (reading 'uuid')

**Comment by jennifer-shehane** [comment]
This error is being thrown from within your application. Have you tried looking at the stacktrace of the error where it is being thrown from?

**Comment by sainthkh** [comment]
I'm sorry for the late reply.

It's hard to guess because I don't have the project code. 

Maybe `clearTimeout` would do the job.

**Comment by patelsmit2890** [comment]
I've found work around for this issue. you can close this case.

`Cypress.on('uncaught:exception', () => false)`

**Comment by ashokkumarg** [comment]
> I've found work around for this issue. you can close this case.
> 
> `Cypress.on('uncaught:exception', () => false)`

You have added this on any index.js file?

**Comment by LeohsPaixao** [comment]
> > I've found work around for this issue. you can close this case.
> > `Cypress.on('uncaught:exception', () => false)`
> 
> You have added this on any index.js file?

No. In the Spec itself, however, this is considered an error, as it is disappearing with some errors, leaving the tests not covering the entire system within this Spec.
