### ISSUE TITLE
cy task succeeds but throws "Converting circular structure to JSON" error

### ISSUE THREAD

**Issue by sharmarahul** [cypress-io/cypress#18166]
### Current behavior

There seems to be an issue already open about it: https://github.com/cypress-io/cypress/issues/5539
BUT it appears that in some cases the task succeeds but the error is still shown

```
on('task', {
    async 'cosmosDBReplaceDoc' ({container, id, newDoc}) {
      await cosmosDB.container(container).item(id).replace(doc)
    }
})
```
This throws a "Converting circular structure to JSON" error but the document gets replaced in the database. There doesn't seem to be a way to rescue **CypressError**. If the task succeeds then the error shouldn't be thrown?

### Desired behavior

Either the error shouldn't be thrown or a way to rescue the error.

### Test code to reproduce

on('task', {
    async 'cosmosDBReplaceDoc' ({container, id, newDoc}) {
      await cosmosDB.container(container).item(id).replace(doc)
    }
})

### Cypress Version

3.14.1

**Comment by sainthkh** [comment]
Sorry for the late reply.

I tried to reproduce the case where the task code is executed but the circular json error is thrown. 

Can you give me a reproducible example about the case?

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by bvandrc** [comment]
+1

**Comment by juampicres** [comment]
+1
