### ISSUE TITLE
Cancel a run on the Cypress Dashboard from the CI

### ISSUE THREAD

**Issue by ManuCastrillonM** [cypress-io/cypress#18168]
### What would you like?

A webhook that allow us to send a signal to cancel the run on the Cypress dashboard from the CI.

### Why is this needed?

When running the test suite from our CI, if the run gets canceled, the Cypress dashboard doesn't stop the run and it stays active until it times out (90 minutes later) which is messing up the overall test metrics that we get from the Cypress Dashboard. 

![image](https://user-images.githubusercontent.com/10585946/134087173-e8d19bbb-8938-4f5d-8c56-d10071e3f6d6.png)

Having the possibility of sending a signal from the CI to the Dashboard via webhook (`/projects/projectId/runId/cancel`) to cancel the run would allow us to have more accurate metrics.

**Comment by ManuCastrillonM** [comment]
Thank you for taking this feature into consideration 🙌.

The metric affected by this issue is the 'run duration'. Since the timeout adds 90 extra minutes to the run, the overall runtime increases without reflecting the actual amount of time the tests took to run.
I just shared with you via email some screenshots from our dashboard and the metrics we are getting vs. the expected ones.

**Comment by jennifer-shehane** [comment]
I know this is not the best solution, but if you were to archive the runs where this is occuring, it would be removed from the analytics.
