### ISSUE TITLE
Cypress can't get coverage report from window.__coverage__

### ISSUE THREAD

**Issue by sp41mer** [cypress-io/cypress#18164]
### Current behavior

I've tried to use cypress/code-coverage, but seems like I've missed something in configuration.

I have an empty coverage report with this issue message :
```Could not find any coverage information in your application by looking at the window coverage object.```

I've checked and I do have `window.__coverage__` object, that is not empty. 

I've also tried to run the following inside my testcase:

```
cy.window().then(win => {
	console.log(win.__coverage__) // The window of your app, not `window` which is the Cypress window object
})
```

And I was able to see this object inside console and that object is not empty. 

### Desired behavior

I expect clearer error output, because I don't know what to check and how to search for the reason of the issue

### Test code to reproduce

support/index.js:

```
import './commands'
import '@cypress/code-coverage/support'
require('cypress-xpath');
```

supprot/commands.js:
```
Cypress.on('uncaught:exception', (err, runnable) => {
	return false
});

```
 
plugins/index.js:

```
module.exports = (on, config) => {
	require('@cypress/code-coverage/task')(on, config)
	config.env.codeCoverageTasksRegistered = true
	return config
}
```

Here are versions of libraries:
```
"babel-plugin-istanbul": "6.0.0",
"babel-plugin-transform-runtime": "6.23.0",
"cypress/code-coverage": "3.9.11"
"cypress": "8.4.1",
"cypress-xpath": "1.6.2",
"istanbul-lib-coverage": "3.0.0",
"nyc": "15.1.0",
```

### Cypress Version

8.4.1

**Comment by sainthkh** [comment]
Sorry for the late reply.

It's a bit hard to guess the problem without a reproducible example. 

How about comparing your project with [the working examples](https://github.com/cypress-io/code-coverage#examples)?

And I guess `instanbul` is added `.babelrc`'s `plugins`, right?

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by frayhan94** [comment]
i meet same case need help

**Comment by suchali93** [comment]
I was getting the same error. Adding this to my `babel.config.js` file fixed my issue.
```
...
env: {
  development: {
     plugins: ['istanbul'],
  },
},
```

As of cypress 10.0.0, you also need to add your plugin to the `setupNodeEvents` function in `cypress.config.js`.
```
...
e2e: {
  setupNodeEvents(on, config) {
     require('@cypress/code-coverage/task')(on, config);
     return config;
  },
}
```

**Comment by mjriyanto** [comment]
> I was getting the same error. Adding this to my `babel.config.js` file fixed my issue.
> 
> ```
> ...
> env: {
>   development: {
>      plugins: ['istanbul'],
>   },
> },
> ```
> 

I got the same problem about this `__coverage__` thing in other e2e test tools and fixed with this one too

**Comment by filipe-jsales** [comment]
Is this possible to be solved using nextjs, also need to create a babel file?
