### ISSUE TITLE
cy.wait fails on request body array assertion when it shouldn't

### ISSUE THREAD

**Issue by rudolfs-blaumanis** [cypress-io/cypress#18162]
### Current behavior

I'm calling a simple API and it's request body contains:
```currencies: [203]```

When I try to assert the request body with `cy.wait`, test fails although it shouldn't:
```expected { Object (pledgeTypes, countries, ...) } to have property currencies of [ 203 ], but got [ 203 ]```
![Screenshot 2021-09-20 at 17 00 49](https://user-images.githubusercontent.com/85102182/134017674-ff625ce6-5bee-498c-a302-7cf6af6877bc.png)

### Desired behavior

Test should pass since request body contains `currencies: [203]`

### Test code to reproduce

```
      cy.intercept({
        method: 'POST',
        url: '/filter',
      }).as('filterNotes');

      cy.wait('@filterNotes')
        .its('request.body')
        .should('contain', {
          currencies: [203],
        });
```

### Cypress Version

8.3.0

### Other
As you can see in console screenshot Actual matches with Expected:
![Screenshot 2021-09-20 at 17 06 42](https://user-images.githubusercontent.com/85102182/134017753-084f49a6-de41-414b-bced-e2876200a59d.png)

Similar assertion works fine with other types of values like String or Boolean, but not with Array as you can see in this example.

**Comment by F3n67u** [comment]
Use `deep.contain` instead of `contain` when you want to compare array. `deep` causes `contain` assertions that follow in the chain to use deep equality instead of strict (===) equality. see chai doc: https://www.chaijs.com/api/bdd/#method_deep

``` js
cy.wait('@filterNotes')
    .its('request.body')
//  .should('contain', {
    .should('deep.contain', {
       currencies: [203],
    });
```

**Comment by sainthkh** [comment]
Confirmed that @F3n67u's solution works. 

```js
it(`automatically parses  request bodies`, function () {
  const p = Cypress.Promise.defer()

  cy.intercept('/post-only', (req) => {
    p.resolve()
  }).as('post')
  .then(() => {
    return Cypress.$.ajax({
      url: '/post-only',
      method: 'POST',
      contentType: 'application/json',
      data: JSON.stringify({ foo: 'bar', love: [123] }),
    })
  })
  .wait('@post').its('request.body').should('deep.contain', { love: [123] })
})
```
