### ISSUE TITLE
Assertion passes even though condition not fulfilled, test stops there and is marked passed

### ISSUE THREAD

**Issue by mduft** [cypress-io/cypress#18176]
### Current behavior

*Sometimes*, assertions and their enclosing tests seem to pass even though the condition is not met, and the test aborts in that place instead of continuing. *Both* the assertion *and* the test are marked passed in this case

### Desired behavior

Assertions should - obviously - fail in case of a problem.

### Test code to reproduce

It is extremly hard to reproduce. However I have pushed a state of our application to a [dedicated branch](https://github.com/bdeployteam/bdeploy/tree/cypress-pass-issue).

use `./gradlew runCypress` to run cypress - you need a Java 17 JDK set as `JAVA_HOME`. The spec `ui/webapp/cypress/integration/instances-settings.spec.js` run repeatedly at some point fails on windows as well as linux. It is marked as *passed* despite the failure - where the failure is that the tests are not fully executed.

There are screenshots as proof attached:
* Shows the test `Prepares the test (group, products, instance)` which should assert an element does *not* exist. The assertion passes, the asserted element is even highlighted in the DOM.
![Screenshot from 2021-09-21 13-54-52](https://user-images.githubusercontent.com/533793/134167515-7263786e-1e8e-4071-a94f-66909b64c8d3.png)
* Following this failure to setup the test environment, the next test fails similarly. Shows the test `Tests Base Configuration` which asserts that the prepared element exists in the DOM, which it clearly does *not*, yet the assertion passes. 
![Screenshot from 2021-09-21 13-52-38](https://user-images.githubusercontent.com/533793/134167776-39029d28-e7b2-409c-b192-a7d38ee8955b.png)

In *both* cases, the assertion which seems to cause the trouble is *not* the end of the test case. There would be numerous more steps in the test to follow, as you can re-read in the actual spec I pushed [here](https://github.com/bdeployteam/bdeploy/blob/cypress-pass-issue/ui/webapp/cypress/integration/instances-settings.spec.js).
 

### Cypress Version

8.4.1

### Other

This was already observed with 8.4.0, potentially even older versions.

**Comment by mduft** [comment]
This seems to happen quite frequently while developing tests. I started today in the morning with a new test case, and had the issue around 6-7 times already in only a few hours. Re-running the same test almos always fixed it, however since tests are fully green all the time I'm quite unsure whether I can trust tests at all these days...

**Comment by mduft** [comment]
Maybe also useful additional information. I just watched it do it again. I was waiting on a `.click()` which was doomed to fail due to a mistake I made while developing the test (detached DOM element). The `click()`'s timeout started ticking, I could watch the progress bar in the cypress UI, when all of a sudden after only 1/4th of the timeout went by, the test completed...

**Comment by greghqa** [comment]
We have been seeing this issue too, as mduft describes although often after just one or two steps. In a suite of several tests, just a few will do this up to once every three runs. It isn't always on the same step. Currently we're using cypress 8.5.0, with cucumber.

**Comment by mduft** [comment]
Glad to see that it is not only us (meaning: something in our test code :)).

**Comment by mike-mccormick** [comment]
I've been seeing this a bunch recently. Same overall circumstances; usually while writing new tests, and it usually rectifies itself on re-runs.
