### ISSUE TITLE
After update cypress have problem with open

### ISSUE THREAD

**Issue by Peggy1012** [cypress-io/cypress#1817]
### Is this a Feature or Bug?

Bug

### Current behavior:

It looks like this is your first time using Cypress: 3.0.0

 √  Verified Cypress! C:\Users\....\AppData\Local\Cypress\Cache\3.0.0\Cypress

Opening Cypress...

TypeError: tty.getWindowSize is not a function

### Versions

Cypress : 2.1.0 -> 3.0.0

**Comment by jennifer-shehane** [comment]
Duplicate https://github.com/cypress-io/cypress/issues/1815

**Comment by jennifer-shehane** [comment]
Fixed in [`3.0.1`](https://docs.cypress.io/guides/references/changelog.html#3-0-1).
