### ISSUE TITLE
Add the option to permanently delete assets before run

### ISSUE THREAD

**Issue by electrofLy** [cypress-io/cypress#18214]
### What would you like?

I would like to be able to permanently delete assets instead of cypress moving them to the trash folder. 

### Why is this needed?

I have a windows continuous integration server on which I run cypress. To make it less time consuming I do not clear the workspace before running it. That means that the assets of the previous run will still be in the workspace. This makes cypress move them to the recycle bin and thus filling up the server's disk space.

**Comment by jennifer-shehane** [comment]
Since this has not gotten a lot of interest over the years, we’ll close this as not planned.
