### ISSUE TITLE
Cypress errors should not be thrown for files that are purposefully deleted using the After Spec API  

### ISSUE THREAD

**Issue by adamalston** [cypress-io/cypress#18220]
### What would you like?

_Not sure if this should be a bug report or a feature request._

I am using the After Spec API to delete videos from spec files' whose tests all pass with 0 retries:

```tsx
module.exports = (on, config) => {
  ...
  on('after:spec', (spec, results) => {
    if (results && results.video) {
      const failures = lodash.some(results.tests, (test) => {
        return lodash.some(test.attempts, { state: 'failed' });
      });
      if (!failures) {
        const filePath = results.video;
        const filename = filePath.split('/').slice(-1)[0];

        // Delete the video
        fs.unlinkSync(filePath);
        console.log(`Tests passed with 0 retries, ${filename} deleted.\n`);
      }
    }
  });
  ...
};
```

When running the tests in the command line I get the following error:

```text
Tests passed with 0 retries, {filename} deleted.

Warning: We could not find the video at the following path, so we were unable to process it.

Video path: path/to/file/{filename}

This error will not alter the exit code.
```

### Why is this needed?

Yes, the error message(s) don't really affect anything but I don't think they should be throw given that I have purposefully deleted the file.

### Other

Version 6.9.1.

**Comment by jennifer-shehane** [comment]
I believe this warning message was removed in more recent versions. Can you try on the most recent version? 8.4.1?

**Comment by IlCallo** [comment]
Can confirm the warning isn't present anymore on Cypress 9.2
