### ISSUE TITLE
Bug during excel project

### ISSUE THREAD

**Issue by Arjun-Mohandas** [cypress-io/cypress#18227]
### Current behavior

I am new to cypres. While trying to read an excel data it is showing like "fs.readFileSync is not a function".
![Capture](https://user-images.githubusercontent.com/91188175/134626111-c2c3ac43-470b-474d-8e22-60b825d42773.PNG)

### Desired behavior

I am using windows 7, cypress version 8.4.1, chrome 93, node.js version 13.14.0, npm version 6.14.4,

package.json
--------------
```json
{
  "name": "CypressAutomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^8.4.1",
    "cypress-xpath": "^1.6.2"
  },
  "dependencies": {
    "xlsx": "^0.17.2"
  }
}
```

### Test code to reproduce

the code I have written to read data from excel file
----------------------------------------------
```js
const xlsx = require('xlsx');

const filePath = process.argv.slice(2)[0];
const workbook = xlsx.readFile(filePath);
const worksheet = workbook.Sheets[workbook.SheetNames[0]];

const Book = [];
let Book1 = {};

for (let cell in worksheet) {
   const cellAsString = cell.toString();

   if(cellAsString[1] !== 'r' 
      &&  cellAsString !== 'm' && cellAsString[1] > 1) {
         if(cellAsString[0] ==='A') {
            Book1.FirstName = worksheet[cell].v;
         }
         if(cellAsString[0] ==='B') {
            Book1.LastName = worksheet[cell].v;
         }
         if(cellAsString[0] ==='C') {
            Book1.DoB = worksheet[cell].v;
         }
         if(cellAsString[0] ==='C') {
            Book1.DoB = worksheet[cell].v;
            Book1.push(Book1);
            Book1 = {};
         }
         
      }
}

console.log();
```

### Cypress Version

cypress version 8.4.1, chrome 93, node.js version 13.14.0, npm version 6.14.4,

**Comment by Narretz** [comment]
fs isn't available in a cypress test, because cypress runs in the browser, not in node. You can use https://docs.cypress.io/api/commands/readfile

**Comment by jennifer-shehane** [comment]
We have an example of reading in a csv file here that may be helpful. But as mentioned above, you can only call fs in the Node.js context, so you could use it in your Cypress support file if necessary. https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__csv-table
