### ISSUE TITLE
Cross Domain logins

### ISSUE THREAD

**Issue by purejgleason** [cypress-io/cypress#18225]
### What would you like?

I use Auth0 OpenIdConnect for Authentication I would like to be able to use it with cypress.

### Why is this needed?

So I can log in with Auth0

### Other

https://stackoverflow.com/questions/69291691/authenticate-auth0-using-cypress-with-in-browser-cross-domain-login

**Comment by purejgleason** [comment]
My current fallback is using straight selenium which does seem to work no problem.

**Comment by jennifer-shehane** [comment]
I answered the other issue you opened earlier. 

You can't currently visit another url that is of a different origin within a single test. We're currently working on supporting this. Duplicate of #17336 

You can try to stub the calls behind the scenes for the Auth0 login flow, that's the only way to test it now.

**Comment by purejgleason** [comment]
@jennifer-shehane That is why I made a feature request. So there is no interest in this feature?

**Comment by jennifer-shehane** [comment]
We are working on supporting this as a feature. Once https://github.com/cypress-io/cypress/issues/17336 is delivered, this will be fully supported. Please follow that issue.
