### ISSUE TITLE
Allow baseUrl to be a path

### ISSUE THREAD

**Issue by simonhaenisch** [cypress-io/cypress#1823]
### Is this a Feature or Bug?

Feature

### Current behavior:

Throws error:

> Expected 'baseUrl' to be a fully qualified URL (starting with `http://` or `https://`). Instead the value was: `"app/#!"`

### Desired behavior:

When `baseUrl` is a path, I want Cypress to run the built-in server and prefix `cy.visit()` with `baseUrl`. I'm using environment variables and `Cypress.Commands.overwrite('visit', ...)` now as a work around.

I know you don't recommend using the built-in server, but I'm testing an old AngularJS app that can easily be served that way (no build process involved, all files are being served from `index.html`).

### Steps to reproduce:

**`cypress.json`:**

```json
{
  "baseUrl": "app/#!"
}
```

### Versions

`cypress@3.0.0`, macOS 10.13.4, latest Chrome

**Comment by jennifer-shehane** [comment]
Adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by jauntyjocularjay** [comment]
+1 vote
