### ISSUE TITLE
Option to purge old versions.

### ISSUE THREAD

**Issue by sidharthv96** [cypress-io/cypress#18231]
### What would you like?

An option in CLI to purge unused/old versions of Cypress.
Something similar to docker purge.

### Why is this needed?

When upgrading versions frequently, Old ones pile up and takes up a lot of storage.
With many machines having limited storage, 128GB and all, the size is significant.

![image](https://user-images.githubusercontent.com/10703445/134644169-459d4cd7-88a7-4e89-bc99-795da9fd334e.png)

### Other

I could try to raise a PR if the feature request is accepted.

**Comment by Narretz** [comment]
isn't that kind of what https://docs.cypress.io/guides/guides/command-line#cypress-cache-prune does? It doesn't delete all but the latest version, but if you are in a project that currently uses the latest version, it does behave as you want.

**Comment by sidharthv96** [comment]
My bad, missed that in docs.
