### ISSUE TITLE
Custom Command Not Working In Typescript

### ISSUE THREAD

**Issue by akashshyamdev** [cypress-io/cypress#18239]
### Current behavior

I'm using a custom command in my code. Here's an error which is being thrown by typescript.
![Screenshot 2021-09-24 at 22 53 18](https://user-images.githubusercontent.com/56759828/134715917-0b2e08dc-2f40-4d20-ba7e-f4092be97a47.png)
 

### Desired behavior

The typescript should know about the custom command and there should be no error.

### Test code to reproduce

Commands.ts:
```javascript
import { builderUser } from './generate';

declare namespace Cypress {
  interface Chainable {
    /**
     * Custom command to create a user on the backend using fake data
     * @example cy.createUser()
     * @returns a promise containing the firstName, lastName, email, password, _id etc
     */
    createUser(overrides?: object): Promise<{
      firstName: string;
      lastName: string;
      email: string;
      password: string;
    }>;
  }
}

Cypress.Commands.add('createUser', (overrides) => {
  const user = builderUser(overrides);

  cy.request('POST', `${Cypress.env('server_url')}/developers/signup`, {
    firstName: user.firstName,
    lastName: user.lastName,
    email: user.email,
    password: user.password,
  }).then((response) => ({ ...response.body.data, ...user }));
});
```

Index.ts
```javascript
import '@testing-library/cypress/add-commands';
import './commands';
```

login.test.ts
```javascript
/// <reference types="cypress" />
import {} from 'cypress';

describe('login', function () {
  beforeEach(() => {
    cy.createUser().then((user) => {
      cy.wrap(user).as('currentUser');
    });
  });

  it('should login the user', function () {
    cy.visit('/auth/login');

    cy.get(':nth-child(2) > [data-testid=input]').type(this.currentUser.email);
    cy.get(':nth-child(3) > [data-testid=input]').type(this.currentUser.password);
    cy.get('.btn').click();

    cy.url().should('include', '/');

    // our auth cookie should be present
    cy.getCookie('jwt').should('exist');
  });
});
```

### Cypress Version

8.4.1

**Comment by F3n67u** [comment]
Looks like the types aren't being added to the global scope. The types need to be updated to:

```
declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Custom command to create a user on the backend using fake data
       * @example cy.createUser()
       * @returns a promise containing the firstName, lastName, email, password, _id etc
       */
      createUser(overrides?: object): Promise<{
        firstName: string;
        lastName: string;
        email: string;
        password: string;
      }>;
    }
  }
}
```

**Comment by F3n67u** [comment]
Another solution is move type argument into a `.d.ts` file, then you don't need add `declare global`:

```js
// support/commands.d.ts
declare namespace Cypress {
  interface Chainable {
    /**
     * Custom command to create a user on the backend using fake data
     * @example cy.createUser()
     * @returns a promise containing the firstName, lastName, email, password, _id etc
     */
    createUser(overrides?: object): Promise<{
      firstName: string;
      lastName: string;
      email: string;
      password: string;
    }>;
  }
}
```

**Comment by akashshyamdev** [comment]
Thanks @F3n67u. Now, I've added a `signup.test.ts` and the command is not found there, but it's found in `login.test.ts`. Here's my `signup.test.ts`:

```javascript
/// <reference types="cypress" />
import {} from 'cypress';

describe('login', function () {
  beforeEach(() => {
    cy.createUser().then((user) => {
      cy.wrap(user).as('currentUser');
    });
  });

  it('should login the user', function () {
    cy.visit('/auth/login');

    cy.get(':nth-child(2) > [data-testid=input]').type(this.currentUser.email);
    cy.get(':nth-child(3) > [data-testid=input]').type(this.currentUser.password);
    cy.get('.btn').click();

    cy.url().should('include', '/');

    // our auth cookie should be present
    cy.getCookie('jwt').should('exist');
  });
});
```

Also, the docs say this:

```typescript
declare namespace Cypress {
  interface Chainable {
    /**
     * Custom command to select DOM element by data-cy attribute.
     * @example cy.dataCy('greeting')
     */
    dataCy(value: string): Chainable<Element>
  }
}
```

Should this be corrected?

**Comment by F3n67u** [comment]
> Thanks @F3n67u. Now, I've added a `signup.test.ts` and the command is not found there, but it's found in `login.test.ts`. Here's my `signup.test.ts`:
> 
> ```js
> /// <reference types="cypress" />
> import {} from 'cypress';
> 
> describe('login', function () {
>   beforeEach(() => {
>     cy.createUser().then((user) => {
>       cy.wrap(user).as('currentUser');
>     });
>   });
> 
>   it('should login the user', function () {
>     cy.visit('/auth/login');
> 
>     cy.get(':nth-child(2) > [data-testid=input]').type(this.currentUser.email);
>     cy.get(':nth-child(3) > [data-testid=input]').type(this.currentUser.password);
>     cy.get('.btn').click();
> 
>     cy.url().should('include', '/');
> 
>     // our auth cookie should be present
>     cy.getCookie('jwt').should('exist');
>   });
> });
> ```
> 
> Also, the docs say this:
> 
> ```ts
> declare namespace Cypress {
>   interface Chainable {
>     /**
>      * Custom command to select DOM element by data-cy attribute.
>      * @example cy.dataCy('greeting')
>      */
>     dataCy(value: string): Chainable<Element>
>   }
> }
> ```
> 
> Should this be corrected?

I don't think the code snippet in the doc works. Type argument inside a module without using `declare global` won't work. The following is the code snippet in the doc.

```js
// in cypress/support/index.ts
// load type definitions that come with Cypress module
/// <reference types="cypress" />

declare namespace Cypress {
  interface Chainable {
    /**
     * Custom command to select DOM element by data-cy attribute.
     * @example cy.dataCy('greeting')
     */
    dataCy(value: string): Chainable<Element>
  }
}
```

**Comment by akashshyamdev** [comment]
Thanks @F3n67u, are there any pending beginner friendly issues/tasks which I could work on?

**Comment by F3n67u** [comment]
> Thanks @F3n67u, are there any pending beginner friendly issues/tasks which I could work on?

Start with cypress doc will be easier. I am new here too. https://github.com/cypress-io/cypress-documentation/issues

**Comment by akashshyamdev** [comment]
@F3n67u thanks a lot 👍

**Comment by akashshyamdev** [comment]
@F3n67u thanks a lot 👍
