### ISSUE TITLE
Ability to add dashboard Tags per test

### ISSUE THREAD

**Issue by lukebjerring** [cypress-io/cypress#18244]
### What would you like?

At Faire, we have a ubiquitous concept of "Product Area". Every Database query, API endpoint, frontend route, setting, etc are attributed to a Product Area, and Product Areas are assigned ownership (a Pod / team that is repsonsible for that product area). E2E tests have owners, and when the tests are flaky, those owners need to make them stable.

When looking at the health of features (or Product Areas) owned by a team, it would be really helpful to view cypress's dashboard from a Product Area perspective (i.e. look at flakiness of all of the specs that belong to a product area).

To achieve this, we need to be able to logically group different results (or specs) in an arbitrary manner, with labels.
Specifically, we tag our Cucumber specs with something like `@ProductArea.SIGNUP`. Ideally, we'd just have a `beforeEach` hook that reads the tag for the spec and calls some API like `cy.labelRun("SIGNUP")`, which tells Cypress to attach the tag to the currently-running test result.

Then, in the dash, there would be a filter for those labels.
Note that this might already be covered by tags, and perhaps I'm asking to be able to apply tags at the result-level rather than the run-level.

### Why is this needed?

Faire's growing rapidly and the combinatorics of small flake rates mean that it's becoming less and less likely for any given run to be completely green. We need to have a self-serve mechanism for teams to understand the health of the E2E specs that they're responsible for, and set OKRs to get flakiness under an acceptable level (e.g. 1%)

**Comment by biltongza** [comment]
Chiming in here to say having tags as a first class feature would be wonderful. We are in a similar situation where we run a suite of tests across different products/teams, and it would be really nifty to be able to have a broad way to categorise/group test results in dashboard. Especially if we could say, for example, 9/10 tests passed for tag x, 8/10 tests passed for tag y etc.
