### ISSUE TITLE
Unable to Type in "number" input field in Chrome 93

### ISSUE THREAD

**Issue by ritbr** [cypress-io/cypress#18257]
### Current behavior

I am using chrome version 96 and cypress version 8.4.1. Whenever I try to type in an input field with type="number" cypress immediately fails with the error: InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.

### Desired behavior

.type() should be able to type number in input field.

### Test code to reproduce

Trying to automate this simple order page. URL : https://www.5staressays.com/order

-Input Phone number:
cy.get('#phone_lead').click({force:true}).type('16777')

### Cypress Version

8.4.1

**Comment by kurek-private** [comment]
I don't think it is a cypress issue - this website is poorly coded. `Your phone` input on cypress focus seems to be scrolling down. 

Try to set the input value using promise-like syntax, like: 
```js
cy.get('#phone_lead').then((el) => {
      el[0].value = '777-777-777';
    });
```
![image](https://user-images.githubusercontent.com/91222506/135082358-121a759c-04cb-4792-b59f-7ce8f2a17fbb.png)
