### ISSUE TITLE
Proposal: Nest screenshot path based on spec path by default

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#1826]
Instead of saving screenshots all directly in the screenshots directory, nest them based on where the spec file is relative to the integration directory. So if running 

`cypress/integration/app/login/user_spec.js`

a screenshot will be saved as 

`cypress/screenshots/app/login/user_spec.js -- login -- users -- can log in.png`.

**Comment by chrisbreiding** [comment]
@brian-mann What about when/if we eventually support having different folders for unit and e2e tests? Should we include the test type too to avoid collisions? 

So the pattern is:

`{screenshotsFolder}/{type}/{specPath}{testName}.png`

with

`cypress/integration/app/login/user_spec.js`

saved as

`cypress/screenshots/integration/app/login/user_spec.js -- login -- users -- can log in.png`

**Comment by brian-mann** [comment]
Definitely don't take into account the `unit` vs `integration` stuff.

It is a good point, but I don't think we can factor that in right now.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by jennifer-shehane** [comment]
@phryneas Sorry for the inconvenience. There has been a new section added to the screenshots docs on ["Naming conventions"](https://on.cypress.io/screenshot#Naming-conventions), hopefully this helps.
