### ISSUE TITLE
Not able to generate dynamic tests using a fixture

### ISSUE THREAD

**Issue by dhuriaditi1** [cypress-io/cypress#18269]
### Current behavior

I tried to run the following example in my local. However, I am getting No tests found error. (Version 8.4.0 (8.4.0.873087))

https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__dynamic-tests/cypress/integration/fixture-spec.js

![](https://user-images.githubusercontent.com/83175299/135037609-4fbd644f-bddb-40c9-b9c4-398b878e9992.png)

### Desired behavior

Tests should be generated dynamically based on the data stored in the fixture

### Test code to reproduce

Same as the example files from https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__dynamic-tests/cypress/integration/fixture-spec.js

### Cypress Version

Version 8.4.0 (8.4.0.873087)

**Comment by kurek-private** [comment]
- Make sure you have this file under exact same path as it is showing in cypress.
- Make sure your tests are wrapped with describe or context. 

Attached example is running without any problems on my pc. 

![image](https://user-images.githubusercontent.com/91222506/135079146-9eb389ce-84cd-405a-be17-8c37910e66ac.png)
