### ISSUE TITLE
TypeScript - importing package failed on "Module parse failed: Unexpected token"

### ISSUE THREAD

**Issue by keeema** [cypress-io/cypress#18262]
### Current behavior

I import npm package with additional functions and I get error:

```js
Error: Webpack Compilation Error
../node_modules/cypress-somecompany-utils/src/env.ts 1:22
Module parse failed: Unexpected token (1:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export function getEnv<TEnv, K extends keyof TEnv>(key: K): TEnv[K] {
.
.
.
```

I do not face this issue when I use @cypress/webpack-preprocessor. My target is to get rid of this preprocessor to increase build performance.

### Desired behavior

I can import typescript packages.

### Test code to reproduce

import * as utils  from "cypress-somecompany-utils";

### Cypress Version

8.4.1

**Comment by keeema** [comment]
It doesn't occur on my other, much smaller project.
I can't find any significant difference.

**Comment by sainthkh** [comment]
Sorry for the late reply.

It seems that there is no compiled version of the `ts` files in `cypress-somecompany-utils`. 

To get rid of `@cypress/webpack-preprocessor`, your webpack configuration should be updated to handle typescript files.

**Comment by keeema** [comment]
Thank for the reply.

Yes, it is exactly that case - there are no compiled javascript files in the imported package. Our infrastructure is completely typescript.

I know how to manage configuration with `@cypress/webpack-preprocessor` (simply change webpack.config.ts).

How can I do it without `@cypress/webpack-preprocessor`? There is no webpack.config.ts.

**Comment by sainthkh** [comment]
Please check [this file](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-preprocessor/index.ts) and [this file](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-preprocessor/lib/typescript-overrides.ts).

Maybe, you might need to use typescript loader for your webpack.config file. 

Or simply using the @cypress/webpack-preprocessor might be the best solution.

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by adi518** [comment]
Just chiming in on this. I got this error after the target on my main `tsconfig.json` was changed to a later target than `es5`. My Cypress `tsconfig.jsoon` inherits from that file and so I got the error. I simply overrode the target for Cypress and set it back to `es5`.

**Comment by burnettk** [comment]
we got this error because we were unintentionally loading up more of our react application code than we had intended from cypress test files.
