### ISSUE TITLE
400 Bad Request - no cookies set while login with keycloak in cypress test

### ISSUE THREAD

**Issue by Kat259** [cypress-io/cypress#18268]
### Current behavior

cypress v 8.2.0
keycloak v. 9.0.3
chrome v. 93

Executing test in Chrome browser.
Simple login test fails with 400 Bad Request Error - I see no response cookies for keycloak are set.

```js
cy.get("input#username").type('user')
cy.get("input#password").type('password')
cy.get("input[value='Log In']").click()
```

Below cookies are set while performing log-in manually:
![image](https://user-images.githubusercontent.com/91521988/135036291-17cb12d7-b87e-43f1-b097-66c6f1527038.png)

Requests are identical for manual log in and log in via cypress test so I assume the lack of cookies is an issue.

I disabled below flag in chrome://flags/:

Enable removing SameSite=None cookies

It didn't help. 

test is passing on Electron.

### Test code to reproduce

cy.get("input#username").type('user')
cy.get("input#password").type('password')
cy.get("input[value='Log In']").click()

### Cypress Version

8.2.0

### Other

keycloak v. 9.0.3
chrome v. 93

**Comment by jennifer-shehane** [comment]
You might consider using [`cy.session()`](https://on.cypress.io/session), an experimental command (set `experimentalSessionSupport` to `true` in config) to test your login. This command can be used to cache and restore cookies, `localStorage`, and `sessionStorage`. It should better handle cookies.

**Comment by Kat259** [comment]
I tried using cy.session () :
cy.session(user,()=>{
    cy.visit('/');
   
    cy.get("input#username").type(user)
    cy.get("input#password").type(user)
    cy.get("input[value='Log In']").click()
     
    cy.getByTestId('menu-icon').should('be.visible')
    })
Unfortunatelly it is still failing on chrome - same error

**Comment by BlueWinds** [comment]
Are the cookies extremely long? Chrome recently changed how they handle cookies over 4096 characters for name and value combined - https://www.chromestatus.com/feature/4946713618939904.

This might not be your issue, but seemed worth bringing up since you mentioned the tests pass in electron and fail in chrome and we've had other users running into the same issue.

**Comment by AtofStryker** [comment]
Hi @Kat259. This issue should be solved with `cy.origin` and looks like a very similar issue to #22282. I am going to close this issue because I am fairly confident it is fixed, but can you follow that issue thread and let us know whether or not it solves your issue?
