### ISSUE TITLE
 Cypress waiting for a new page to load even if page is loaded and throwing timed out error 

### ISSUE THREAD

**Issue by manishGitHub555** [cypress-io/cypress#18266]
### Current behavior

 While running cypress test case, sometimes cypress waiting for a new page to load even if page is loaded and there is no load event happening and throwing timed out error and issue is happening randomly at any steps[]
 (url
![Cypress Load error](https://user-images.githubusercontent.com/91519004/135029586-73892c56-76e2-4138-9e50-83e8c67deb8f.png)
)

### Desired behavior

Cypress should continue running script and not to wait for page load if page is already loaded or there should be a command to disable wait for page load for this exception handling

### Test code to reproduce

Test Cases Code
```js
it("To verify PayIn from Vault to Till",function()
 {
  const TillsActions = new Retail_Manage_Tills_Actions()
 
  TillsActions.Retail_manage_tills_event()
  TillsActions.GetVaues_PayInVaultCard_Before()
  TillsActions.VaultPayInLink()
  TillsActions.Vault_FillCashAmount()
  TillsActions.VaultModal_PayIn_ClickDdl_From()
  TillsActions.VaultModal_PayIn_EnterDdl_From()

  TillsActions.VaultModal_PayIn_ClickDdl_To()
  TillsActions.VaultModal_PayIn_EnterDdl_To()

  TillsActions.VaultModal_PayIn_ReasonDdl()
  TillsActions.VaultModal_PayIn_ReasonInput()
  //TillsActions.VaultModal_PayIn_Notes()

  TillsActions.VaultModal_PayIn_AddPayIn()
  TillsActions.VaultModal_Dismiss()
  cy.reload()
  TillsActions.GetVaues_PayInVaultCard_After()
  TillsActions.Validate_Updated_CardandModalValues()
 })
```
 -------------------------------------------------------------------------------------------------------------------
 Methods code
 Retail_manage_tills_event()
```js
{   
    cy.xpath('//div[@class="k-loading-mask"]').should('not.exist')
    element.Retail().click({force: true})
    cy.xpath('//div[@class="k-loading-mask"]').should('not.exist')
    element.Tillmodule1().trigger('mouseover').click({force: true})
    cy.xpath('//div[@class="k-loading-mask"]').should('not.exist')
    cy.wait(1000)
    element.ManageTills1().trigger('mouseover').click({force: true})
}

Validatecashvault_functionality()
{
    element.Countvalut().click()
    element.Cashbag_Subvault_Count().type('1000')
    element.Coinbag_Subvault_Count().type('1000')
    element.Automation_Deposit_SubVault_Count().type('1000')
    element.Automation_Zero_Amount_Count().type('1000')
    element.Automation_Sub_Tillu_Count().type('1000.50')
    //element.Scriollintoview()
    element.Report_Cash_Button().scrollIntoView().should('be.visible').then(($Element)=>
    {

        $Element.click()


    })
}

VaultPayInLink()
{   
    element.VaultPayInLink().should('be.visible').click({force: true})
}

GetVaues_PayInVaultCard_Before()
{
    cy.wait(2000)     
    element.VaultCard_CashInVault().should('be.visible').then(($el) => 
    {
        const vaultCard_CashInVaultBefore =$el.text().replace('$','').replace(',','');
        cy.wrap(vaultCard_CashInVaultBefore).as('GetVaultCard_CashInVaultBefore')
        cy.log('GetVaultCard_CashInVaultBefore',vaultCard_CashInVaultBefore)         
    })
    element.VaultCard_CashBag().should('be.visible').then(($el) => 
    {
        const vaultCard_CashBagBefore =$el.text().replace('$','').replace(',','');
        cy.wrap(vaultCard_CashBagBefore).as('GetVaultCard_CashBagBefore')
        cy.log('GetVaultCard_CashBagBefore',vaultCard_CashBagBefore) 
    })
    element.VaultCard_CoinBag().should('be.visible').then(($el) => 
    {
        const vaultCard_CoinBagBefore =$el.text().replace('$','').replace(',','');
        cy.wrap(vaultCard_CoinBagBefore).as('GetVaultCard_CoinBagBefore')
        cy.log('GetVaultCard_CoinBagBefore',vaultCard_CoinBagBefore) 
    })
    element.VaultCard_AutomationDepositSubVault().should('be.visible').then(($el) => 
    {
        const vaultCard_AutomationDepositSubVaultBefore =$el.text().replace('$','').replace(',','');
        cy.wrap(vaultCard_AutomationDepositSubVaultBefore).as('GetVaultCard_AutomationDepositSubVaultBefore')
        cy.log('GetVaultCard_AutomationDepositSubVaultBefore',vaultCard_AutomationDepositSubVaultBefore) 
    })
    element.VaultCard_AutomationZeroAmount().should('be.visible').then(($el) => 
    {
        const vaultCard_AutomationZeroAmountBefore =$el.text().replace('$','').replace(',','');
        cy.wrap(vaultCard_AutomationZeroAmountBefore).as('GetVaultCard_AutomationZeroAmountBefore')
        cy.log('GetVaultCard_AutomationZeroAmountBefore',vaultCard_AutomationZeroAmountBefore) 
    })
    element.VaultCard_SubTillu().should('be.visible').then(($el) => 
    {
        const vaultCard_SubTilluBefore =$el.text().replace('$','').replace(',','');
        cy.wrap(vaultCard_SubTilluBefore).as('GetVaultCard_SubTilluBefore')
        cy.log('GetVaultCard_SubTilluBefore',vaultCard_SubTilluBefore) 
    })
}
```

### Cypress Version

8..5.0

### Other

Recorded video for reference
https://drive.google.com/file/d/1y65QWWnjOngH4M_cfSwmIiWzGy0riwkB/view?usp=sharing

**Comment by jennifer-shehane** [comment]
Cypress is detecting a window onBeforeLoad event, so is then waiting for the following `load` event to fire. Can you put this in your test code and look at debugger where this event is happening? It will show where this is being fired. 

```js
Cypress.on('window:before:load', (err, runnable) => {
  debugger
})
```

**Comment by nicojones** [comment]
Nice, closed because @cypress didn't respond. Beautiful support

**Comment by jennifer-shehane** [comment]
@shwarcu You're asking for this feature: https://github.com/cypress-io/cypress/issues/788

@nicojones The issue here did not provide a reproducible example to work from, not did they respond to our asking for more detail. We close issues in this case when we don't receive responses so that we can focus on issues we can reproduce and fix. If you have a similar issue, please open an issue with a reproducible example so we can investigate.

**Comment by rafaelcavalcante** [comment]
Cypress just started to fail in some tests written for more than 2 years ago with this same issue. In my case the page is fetching an image that does not exist anymore and the browser tries to load the image and fails, thats why it does not dispatch the onload event 👍

**Comment by samuel25n** [comment]
I have the same issue in my tests, but only when running suites on CI. Somehow i managed to find a workaround for this, by adding a check in the error and if the error contains 'load' event or something like that, it should be seen as not an error
This is causing many tests to fail when the page is actually fully loaded and could continue running

**Comment by Liam-McKenna** [comment]
Same issue. page is full loaded, but Cypress is still "fetching page" and then errors that 
"Your page did not fire its load event within 60000ms."

**Comment by ChristofFritz** [comment]
Same here. Page is clearly loaded, yet cypress throws the error 
```
Timed out after waiting 60000ms for your remote page to load.

Your page did not fire its load event within 60000ms.
```

And it only happens in CI, so it's extremely hard to reproduce locally.
