### ISSUE TITLE
[cy.type for filter]: cy.type is not working well in filter box.

### ISSUE THREAD

**Issue by yandong01** [cypress-io/cypress#18264]
### Current behavior

Steps:

1. I have a datagrid with a Name coloumn which can be filtered. 
2. There are some items in my datagrid, like "demoname1, demoname2, name1, name2, name3 ....."
3. Run: cy.type("demoname1") in the filter box for Name coloumn

Expect:

The complete string "demoname1" should be typed in the filter box and only the item "demoname1" should be filtered.

Actual:

The typing is stopped when just type "d",  the whole string "demoname1" doesn't have a chance to type in the filter box, and all Name with "d" displayed.
 

### Test code to reproduce

cy.type("demoname1")

### Cypress Version

8.3.1

**Comment by sainthkh** [comment]
Sorry for the late reply. 

As we all know, reproducing the bug on the developer's machine is the initial stage to solve bugs. Can you provide me a reproducible example?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
