### ISSUE TITLE
Failed to connect to Chrome, Cypress 7.0.0, Chrome 94.0.4606.61

### ISSUE THREAD

**Issue by devictoribero** [cypress-io/cypress#18281]
### Current behavior

After running `cypress open` the UI is displayed with a list of all the existing tests. If I try to execute one, the connection to chrome cannot be established.

**Error**
```
Failed to connect to Chrome, retrying in 1 second (attempt 55/62)
```

<img width="757" alt="Screenshot 2021-09-28 at 11 00 41" src="https://user-images.githubusercontent.com/16169890/135132557-f929eaae-3697-41a6-9708-d67ac6eae5a1.png">

![Screenshot 2021-09-28 at 11 01 36](https://user-images.githubusercontent.com/16169890/135132565-5d6137a9-844d-49cf-9a92-765005387748.png)

### Desired behavior

I would expect tests to work just fine.

### Test code to reproduce

After UI displays all the tests, execute any test by clicking on it

### Cypress Version

7.0.0

### Other

Chrome version: 94.0.4606.61
Node version: v14.15.4

I'm currently migrating from 6.x.x to 7.0.0 so later I can upgrade to 8.0.0

**Comment by devictoribero** [comment]
Samee issue as https://github.com/cypress-io/cypress/issues/5912.

I checked the chrome policies and they look fine.

**Comment by jennifer-shehane** [comment]
Make sure to kill all instances of Chrome that are open and try again.

**Comment by molteninjabob** [comment]
I am also seeing this issue with Chrome 94.0.4606.61. It worked fine on 8.4.1, but started seeing the problem after upgrading to 8.5.0. Even after downgrading back to 8.4.1, I still see the error. I tried clearing the cypress binary cache as well as rebooting the computer.

**Comment by agelico** [comment]
I have same problems with Firefox 89 on 8.4.1, Chrome works fine. Happens when there are no other instances of Firefox, I can't see the pattern: it just fails to connect sometimes. Trying to figure this out for a week(

**Comment by MarikoKujo** [comment]
I am having the same issue with cypress 7.1.0 and Chrome 94.0.4606.61.

**Comment by Mateus863** [comment]
Seeing the same issue with Chrome 94.0.4606.71. Cypress version 8.5.0 , Mac OS Big Sur 11.6 . Can't run any of my tests

**Comment by nonnonno** [comment]
I restarted Google Chrome and this problem has solved!
(FYI: Chrome v.104.0.5112.101, Cypress v.7.7.0 on M1 Mac)
