### ISSUE TITLE
Custom commands are not working inside Cypress.Promise

### ISSUE THREAD

**Issue by 4en1x** [cypress-io/cypress#18282]
### Current behavior

Cypress does not call custom commands inside Cypress.Promise.

It also can be related to the usage of .each command - 
Docs says that Promises are awaited inside each:
https://docs.cypress.io/api/commands/each#Promises

### Test code to reproduce

```
cy.wrap(elements).each((element) => {
        return new Cypress.Promise((resolve) => {
            cy.someCustomCommand(element).then(() => {
                resolve()
            });
        })
    })
```

### Cypress Version

7.2.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

It's a bit hard to guess what the intended behavior is without a reproducible example. 

Internally, Cypress creates a stack of commands when the test commands are run. And execute them later in batch. 

To solve this problem,

1. Remove `Promise`.
2. Change the custom command to a plain JavaScript function.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
