### ISSUE TITLE
Assertions on GQL responses are failing inconsistently

### ISSUE THREAD

**Issue by pmerwin** [cypress-io/cypress#18285]
### Current behavior

I am able to use the cy.intercept method to intercept our GQL endpoints, but the assertions are failing to find properties that actually exist in the response object?

https://share.getcloudapp.com/5zuNzgoY

### Desired behavior

Assertions should work the same every time and succeed when properties are correctly found.

### Test code to reproduce

// Utility to match GraphQL mutation based on the operation name
export const hasOperationName = (req, operationName) => {
  const { body } = req
  return (
    body.hasOwnProperty('operationName') && body.operationName === operationName
  )
}

// Alias query if operationName matches
export const aliasQuery = (req, operationName) => {
  if (hasOperationName(req, operationName)) {
    req.alias = `gql${operationName}Query`
    
  }
}

cy.intercept('POST', commAPI, (req) => {
            aliasQuery(req, 'getChannelsForUser')
        });

cy.wait('@gqlgetChannelsForUserQuery', {timeout: 30000})
            .its('response.body.data.getChannelsForUser[1]')
            .should('have.property', 'owner')

### Cypress Version

Cypress package version: 8.5.0 Cypress binary version: 8.5.0 Electron version: 13.2.0 Bundled Node version: 14.16.0

### Other

![Uploading Screen Shot 2021-09-28 at 2.23.44 PM.png…]()

**Comment by pmerwin** [comment]
hmm this may be a nesting issue into the array as this works everytime:

cy.wait('@gqlgetChannelsForUserQuery', {timeout: 30000})
            .its('response.body.data')
            .should('have.property', 'getChannelsForUser')

**Comment by bahmutov** [comment]
@pmerwin the correct syntax for accessing an element in the array is `.<number>.` not `[number]`

```diff
- .its('response.body.data.getChannelsForUser[1]')
- .its('response.body.data.getChannelsForUser.1')
```

**Comment by pmerwin** [comment]
its('prop.some.list.1'), not its('prop.some.list[1]')

yep that works thank you!!!
