### ISSUE TITLE
Configurable or increased VERIFY_TEST_RUNNER_TIMEOUT_MS 

### ISSUE THREAD

**Issue by TimothyGillespie** [cypress-io/cypress#18290]
### What would you like?

The VERIFY_TEST_RUNNER_TIMEOUT_MS constant is increased to, for example, 100000, or the option smokeTestTimeout can be used via a static file (i.e. `cypress.json`). Being able to run it in via command line parameter would work also but is a less convenient solution for internal distribution.

### Why is this needed?

The static timeout causes issues at my workplace and seems to be a shared issue where ever slow systems are verifying the cypress or certain background software is slowing down the execution.

The currently worked out fix involves editing the source code in node_modules which is not very neat nor does it seems reliable for automated solutions.

see fix suggestions here: https://swingli.com/how-to-fix-cypress-verification-timed-out-exception/
and here: https://stackoverflow.com/questions/63667880/cypress-verification-timed-out-after-30000-milliseconds

### Other

The constant `VERIFY_TEST_RUNNER_TIMEOUT_MS` in `node_modules\cypress\lib\tasks\verify.js` will be used in the options as `smokeTestTimeout`. But only the dev option seems to be usuable.

**Comment by Narretz** [comment]
There's a PR for that https://github.com/cypress-io/cypress/pull/18243

You can voice your support there

**Comment by legap** [comment]
Because [PR #18243](https://github.com/cypress-io/cypress/pull/18243) seems to be stale I opened a new one including a test. Hope this one will be available in the next version.

**Comment by johndpotts** [comment]
great to see there's a PR open for this! Getting cypress to work at my workplace involves manually updating this value in node_modules right now.
