### ISSUE TITLE
don't cache to a global cache directory in CI

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1829]
don't cache to a global cache folder in CI, use `{workspace}/node_modules/cypress/dist`

Pros:
- caching node_modules in CI will continue to work as expected and recommended
- upgrading cypress is absolutely painless in CI - newer versions of binary are downloaded and older versions are deleted when upgrading- as long as system dependencies (on linux) stay the same (very likely)

Cons:
- makes caching `node_modules` (or at least `node_modules/cypress`) a necessity in CI (or else 150Mbs+ download will drastically slow down build)
- can't pre-cache any binary related code with docker images
- differing behavior between local / CI should probably be kept to a minimum

**Comment by bahmutov** [comment]
Ok, so seems `npm` itself is moving _away_ from preserving `node_modules`. The command `npm ci` that was introduces in v5.7.1 actually _removes node_modules_ folder before running https://docs.npmjs.com/cli/ci instead using `~/.npm` to cache all downloaded NPM modules. 

Similarly we should not store any state in `node_modules`, but instead prefer to use `~/.cache/Cypress` folder. In our documentation on CI we should advise the user to cache the two folders

```
# .travis.yml
install:
- npm ci
# keep the npm cache around to speed up installs
# and keep Cypress binary cached in ~/.cache
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
```

**Comment by Bkucera** [comment]
@bahmutov I agree with everything you mentioned! Closing this
