### ISSUE TITLE
URL proxy issue

### ISSUE THREAD

**Issue by sarahgracesmith** [cypress-io/cypress#183]
I’ve got the same URL loaded in the browser and in cypress. I’m inspecting the footer link “Integrations”. In the browser its `<a href="http://help.fullstory.com/11270-Integrations">Integrations</a>` and when I inspect the cypress browser I see `<a href="/11270-Integrations">Integrations</a>`. The latter, when clicked in cypress, ends up at www.fullstory.com instead of help.fullstory.com.

The actual element in code is `<a href="http://help.fullstory.com/11270-Integrate">Integrations</a>`

![cypressfs](https://cloud.githubusercontent.com/assets/16545003/16777484/be047c72-4837-11e6-9522-ecc019ee459d.png)

![realfs](https://cloud.githubusercontent.com/assets/16545003/16777488/c2c06f64-4837-11e6-9fbd-5fdac03ad74c.png)

**Comment by brian-mann** [comment]
Fixed in [`0.17.0`](https://github.com/cypress-io/cypress/wiki/changelog#0170-08302016).
