### ISSUE TITLE
project name in Windows should not be displayed as entire path.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1830]
### Current behavior:

In Windows Desktop-Gui, where in nav bar where project name should be, is displayed as entire path

<img width="785" alt="screen shot 2018-05-30 at 1 14 10 pm" src="https://user-images.githubusercontent.com/1271364/40736238-7b45aef0-640b-11e8-84c1-1feb1faf3c5f.png">

### Desired behavior:

Only show current dir as project name in nav bar.

<img width="802" alt="screen shot 2018-05-30 at 1 15 58 pm" src="https://user-images.githubusercontent.com/1271364/40736310-af670dd2-640b-11e8-950f-f1eed77d2f05.png">

### Versions

Cypress <=3.0.0

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
