### ISSUE TITLE
Typings for cy.route inconsistent with documentation

### ISSUE THREAD

**Issue by bsmithEG** [cypress-io/cypress#1831]
### Is this a Feature or Bug?

(documentation) bug

### Current behavior:

Docs (or typings) are wrong

### Desired behavior:

Both should be consistent

### Steps to reproduce:

The docs for ```cy.route``` with stubbing are inconsistent with the typings published with cypress.  Examples:

Docs:
```js
cy.route('**/users', [
  {id: 19, name: 'Laura'},
  {id: 20, name: 'Jamie'}
])

const commentsResponse = (routeData) => {
  //routeData is a reference to the current route's information
  return {
    data: someOtherFunction(routeData)
  }
}

cy.route('POST', '**/comments', commentsResponse)
```

And the typings for cy.route:

```
route(url: string | RegExp, response?: string | Response): Chainable<null>
route(method: string, url: string | RegExp, response?: string | Response): Chainable<null>
route(fn: () => RouteOptions): Chainable<null>
route(options: Partial<RouteOptions>): Chainable<null>
```

Also, it seems that Cypress.Response isn't really want is specified in the docs.  At least, if this is what's required, a bunch of props that probably shouldn't be necessary for this are required.

```js
  interface Response {
    allRequestResponses: any[]
    body: any
    duration: number
    headers: { [key: string]: string }
    isOkStatusCode: boolean
    redirectedToUrl: string
    requestHeaders: { [key: string]: string }
    status: number
    statusText: string
  }
```

### Versions

Cypress 3.0.0

**Comment by jennifer-shehane** [comment]
Sorry, could you be more specific about where exactly the docs/typings differ? Is there an error when you run the code above?

**Comment by bsmithEG** [comment]
The typescript compiler has an error, and thus there's an error reflected in the IDE.  I can get around this by ignoring it or typecasting around, but the point is that it's wrong unless the function isn't meant to be used in the way the docs specify.

There error I get in Cypress (but this just comes from the typescript preprocessor)

```shell
[tsl] ERROR in /Users/rsmith/project/specs/test.spec.ts(61,40)
TS2345: Argument of type '{ campaignResponses: { campaignName: string; messages: { promotedItems: { type: string; name: str...' is not assignable to parameter of type 'string | Response'.
Type '{ campaignResponses: { campaignName: string; messages: { promotedItems: { type: string; name: str...' is not assignable to type 'Response'.
Property 'allRequestResponses' is missing in type '{ campaignResponses: { campaignName: string; messages: { promotedItems: { type: string; name: str...'.
```

**Comment by bahmutov** [comment]
Hmm, I have to look at this, probably missing "partial"

**Comment by no23reason** [comment]
@bahmutov IMO it is not missing `Partial`. According to [the docs](https://docs.cypress.io/api/commands/route.html#With-Stubbing) you can pass arbitrary object as the response (see the first example of the code):

```js
cy.server()
cy.route('https://localhost:7777/users', [{id: 1, name: 'Pat'}])
```

Therefore I believe the typings should look something like this:

```ts
route(url: string | RegExp, response?: string | Response | object /* or any or unknown in TS 3.0 */): Chainable<null>
route(method: string, url: string | RegExp, response?: string | Response | object /* or any or unknown in TS 3.0 */): Chainable<null>
route(fn: () => RouteOptions): Chainable<null>
route(options: Partial<RouteOptions>): Chainable<null>
```
