### ISSUE TITLE
Pending tests are reported as Passed by teamcity reporter

### ISSUE THREAD

**Issue by papatelst** [cypress-io/cypress#18319]
### Current behavior

We use `--env grepTags=@SMOKE` along with following parameters with docker run command
`cypress run --reporter teamcity`. Per [documentation](https://docs.cypress.io/guides/tooling/reporters), teamcity reporter is built into cypress.
Teamcity(TC) buildlog shows tests under `Pending `and `Passing `status correctly as shown below
![image](https://user-images.githubusercontent.com/45948323/135536138-83c0b2a3-6afb-4bde-869e-2db978916f04.png)
However, the TC `overview `tab shows all Pending tests as passed as seen below
![image](https://user-images.githubusercontent.com/45948323/135536328-9d1161d8-b55f-4663-9375-717ef694af94.png)
The TC `Tests ` tab shows all tests as successful. When I filter by 'ignored' status, it does not return any tests as shown below. 
![image](https://user-images.githubusercontent.com/45948323/135536514-b95119fa-c600-417b-8c20-c9231200d50c.png)
Note: TC does not have test filter statuses like `Pending`, which are mocha specific as mentioned [here](https://github.com/cypress-io/cypress/issues/3092#issuecomment-511611728). The only default filters TC has is `'successful', ''failed' and 'ignored'.`

This issue is also reported in Mocha teamcity reporter project [here](https://github.com/travisjeffery/mocha-teamcity-reporter/issues/65) and there seems to be an fix for it [here](https://github.com/travisjeffery/mocha-teamcity-reporter/pull/66). 
Differences b/w mocha teamcity reported and cypress using mocha teamcity reporter can be found [here](https://gist.github.com/fernyb/813ff8764b6dc969f1574df349ae59f9).

### Desired behavior

`Pending `tests from cypress teamcity reporter should display as `Ignored `tests in Teamcity UI. It should not display under '**Successful'/Passed** status on TC UI.

### Test code to reproduce

Dont have

### Cypress Version

8.3.0

### Other

Relevant plugins included in our project
"mocha-teamcity-reporter": "^4.1.0"
"cypress-grep": "^2.5.3"

**Comment by Narretz** [comment]
If it only happens with cypress-grep, you should open an issue in the repository for it: https://github.com/cypress-io/cypress-grep

**Comment by papatelst** [comment]
@Narretz cypress-grep is only a means to filter and run tagged tests. It is doing its job to run only tagged tests and marking other tests as 'Pending' as seen in Build log snapshot. 
There is discrepancy in how TC is reporting it on TC UI (passed instead of ignored)
I also logged is as Teamcity [Issue](https://youtrack.jetbrains.com/issue/TW-73346) to see if this is something they can fix.

**Comment by papatelst** [comment]
Its fixed in mocha-teamcity-reporter using this [PR](https://github.com/travisjeffery/mocha-teamcity-reporter/pull/66). A similar fix should be applied to cypress project as well.

**Comment by BlueWinds** [comment]
Thank you for the detailed report, and all the helpful context around it.

Given that the problem and solution are already known, a pull request would be welcome. I'll add this issue for discussion with the team, but can't promise when we'll get to it.
