### ISSUE TITLE
cy.visit(url) redirects me to another end point on my app in CI 

### ISSUE THREAD

**Issue by fiosman** [cypress-io/cypress#18321]
### Current behavior

After attempting to visit a page on my application after successful authentication, I am re-directed to another page that wasn't specified in the argument passed to`cy.visit`. Note, this issue only occurs on CI (github actions). It does not occur locally via cypress open/run mode (had multiple developers run the test files on their machines and all was ok). 

In the example below, I visit /sites/2/users. However, I get redirected to /sites/2/global on my app. 

```
describe("Tests for Site Users Page", () => {
  beforeEach(() => {
    cy.login(); //note I am integrating cy.session() in this custom login command
  });

  it("should handle user page properly", () => {
    cy.visit("/sites/2/users");
    cy.contains("Site Name").should("exist"); //wait for page to load
  });
```
 

### Desired behavior

The URL /sites/2/users should load successfully and I should not be redirected to another URL that I did not specify. 

### Test code to reproduce

```
describe("Tests for Site Users Page", () => {
  beforeEach(() => {
    cy.login(); //note I am integrating cy.session() in this custom login command
  });

  it("should handle user page properly", () => {
    cy.visit("/sites/2/users");
    cy.contains("Site Name").should("exist"); //wait for page to load
  });
```

### Cypress Version

8.3.1

**Comment by fiosman92** [comment]
I have a screenshot from the Cypress dashboard if that might help?

**Comment by fiosman** [comment]
I found a similar issue, but even after waiting for XHR to finish, still didn't work. It just fires off the new url event right away. Pretty sure this is a bug in Cypress

https://github.com/cypress-io/cypress/issues/1713

**Comment by Kseniia-Lushnei** [comment]
I have the similar issue - when I want to visit url like `/sites/2/user` our app somehow receives `/sites/2/undefined`. The last portion of URL becomes 'undefined' whatever URL I want to visit. May be the same thing - your app just falls back to Home page while receiving unknown URL

**Comment by fiosman92** [comment]
> I have the similar issue - when I want to visit url like `/sites/2/user` our app somehow receives `/sites/2/undefined`. The last portion of URL becomes 'undefined' whatever URL I want to visit. May be the same thing - your app just falls back to Home page while receiving unknown URL

Were you able to get this resolved?

**Comment by fiosman** [comment]
> I have the similar issue - when I want to visit url like `/sites/2/user` our app somehow receives `/sites/2/undefined`. The last portion of URL becomes 'undefined' whatever URL I want to visit. May be the same thing - your app just falls back to Home page while receiving unknown URL

Hi, were you able to resolve this?

**Comment by Kseniia-Lushnei** [comment]
@fiosman Not yet, but Electron works fine for me and Chrome doesn't. Actually stuck with it as well. On the other hand our CI uses dockerized version and everything fine there so far, it's only on my (as well as most of my teammates) local.

**Comment by swoods07** [comment]
I have the same issue the using cy.visit(/myURL) during the test it gets redirected to main URL (the home page) whilst XHR requests are being sent. I can't intercept or wait for these requests as its caused by a websocket.
