### ISSUE TITLE
Wrap command message

### ISSUE THREAD

**Issue by daleqq** [cypress-io/cypress#18340]
### What would you like?

Wrap the command message in **Command Log** window like `cy.log` command.

### Why is this needed?

The command message in **Command Log** window is not wrapped. It is hard to see the detail command message.
In contrast with command message, the message of `cy.log` command is wrapped as below:
![image](https://user-images.githubusercontent.com/1555563/135700197-d543efe3-1ed0-4c42-ab10-f4f8efbe85b1.png)

**Comment by emilyrohrbough** [comment]
This work was completed in #20465 and released in 10.0
