### ISSUE TITLE
cy.viewport(x,y) does not reflect on Cypress.config('viewportWidth'/'viewportHeight') 

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#18342]
### Current behavior

Given code
```javascript
describe('test', () => {
  beforeEach(() => {
    cy.viewport(50, 50);
  });

  it('test', () => {
    cy.log(Cypress.config('viewportWidth'));
    cy.log(Cypress.config('viewportHeight'));
  });
});
```

I would expect cypress to log `50` and `50` during the test run.
However, 
![image](https://user-images.githubusercontent.com/36670132/135740456-9804f17b-a115-4543-b893-7365ac357916.png)
Cypress default values are reported back 

### Desired behavior

Cypress logs `50` and `50` during the test run

### Test code to reproduce

See above

### Cypress Version

8.3.1

**Comment by jennifer-shehane** [comment]
`Cypress.config` logs the configuration values that are set - which the viewport command doesn't change. You could set the config via the config and then read it:

```
Cypress.config('viewportWidth', 800)
Cypress.config('viewportWidth') // => 800
```

**Comment by sainthkh** [comment]
I'm currently thinking about adding APIs like `cy.viewport('width')`. But the problem is that I cannot guess the valid use case. Can you tell us what you're trying to do with viewport width and height with some example code?
