### ISSUE TITLE
Cypress clock does not work with Intercept

### ISSUE THREAD

**Issue by kunjee17** [cypress-io/cypress#18343]
### Current behavior

if I put cypress clock with the cypress intercept. Intercept stops working. While without intercept it do work without any issues.

Below code does not work
```
describe('Intercept with clock', () => {
  it('should work with clock', () => {
    const now = new Date();
    cy.clock(now);
    cy.intercept('**/Org/InitialAppInfo', {fixture : 'initialAppInfo.json'}).as('initialAppInfo');
    cy.intercept('**/Tickets', { fixture : 'myTickets.json' }).as('myTickets');
    cy.visit('http://localhost:4002');
    cy.wait('@initialAppInfo');
    cy.wait('@myTickets'); 
    cy.tick(1000);
  });
});
```

But below code works without any issue.

```
describe('Intercept with clock', () => {
  it('should work with clock', () => {
    cy.intercept('**/Org/InitialAppInfo', {fixture : 'initialAppInfo.json'}).as('initialAppInfo');
    cy.intercept('**/Tickets', { fixture : 'myTickets.json' }).as('myTickets');
    cy.visit('http://localhost:4002');
    cy.wait('@initialAppInfo');
    cy.wait('@myTickets'); 
  });
});

```

Scenario is to make notification go away fast (code is not added for clarity), but when I add that in combination with intercept it just don't work.  

### Desired behavior

```
describe('Intercept with clock', () => {
  it('should work with clock', () => {
    const now = new Date();
    cy.clock(now);
    cy.intercept('**/Org/InitialAppInfo', {fixture : 'initialAppInfo.json'}).as('initialAppInfo');
    cy.intercept('**/Tickets', { fixture : 'myTickets.json' }).as('myTickets');
    cy.visit('http://localhost:4002');
    cy.wait('@initialAppInfo');
    cy.wait('@myTickets'); 
    cy.tick(1000);
  });
});

```

Clock should work with intercept without any issue. 

### Test code to reproduce

```
describe('Intercept with clock', () => {
  it('should work with clock', () => {
    const now = new Date();
    cy.clock(now);
    cy.intercept('**/Org/InitialAppInfo', {fixture : 'initialAppInfo.json'}).as('initialAppInfo');
    cy.intercept('**/Tickets', { fixture : 'myTickets.json' }).as('myTickets');
    cy.visit('http://localhost:4002');
    cy.wait('@initialAppInfo');
    cy.wait('@myTickets'); 
    cy.tick(1000);
  });
});

```

Does not work.

### Cypress Version

8.5.0

### Other

I thought I was doing some mistake as I m running cypress with nwrl workspace. But even in isolated setup with pure javascript code it is not working. I have also asked a question regarding this in question section but I guess it is a bug. One can find question here. https://github.com/cypress-io/cypress/discussions/18310

I am new to Cypress and if Clock should not be used with intercept, or some sort of setting is required. Please feel free to close the issue and answer the question.

**Comment by anicioalexandre** [comment]
any news about that issue? still getting it

**Comment by anicioalexandre** [comment]
Not sure if that's your case, but I had a similar issue and made it work by adding the type `["Date"]` as the second parameter
```
  const middleOfJanuary = new Date(2023, 0, 15, 12)
  cy.clock(middleOfJanuary, ["Date"])
  
  cy.intercept(...)
```

**Comment by MattTreichelYeah** [comment]
@anicioalexandre Do you have any idea why this helps? I had added this ages ago and can't remember why, seems very unintuitive

**Comment by dwjohnston** [comment]
I'm not sure if it's the same thing, but I'm having an issue where `cy.clock(new Date(2023, 0, 1))` works fine on my local machine, but when it runs in a build pipeline the mocking behaviour appears to have not taken effect.
