### ISSUE TITLE
Internal: Automated e2e system tests with Cypress

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#18347]
### What would you like?

We'd like to test more of the Cypress system e2e with Cypress itself. Details TBD

### Why is this needed?

To ensure we deliver a stable product, especially with the concern of CT stable launch.

**Comment by ChrisZie** [comment]
Hi @jennifer-shehane ,
what do you mean by "Cypress system e2e"? Do you mean the cypress.io website?
