### ISSUE TITLE
Webpack 'tree-shaking' doesn't work at sharing code files with both browser and NodeJs logic

### ISSUE THREAD

**Issue by kosiakMD** [cypress-io/cypress#18353]
### Current behavior

I know this kind of issue was fixed in the version `5.1.0` but ...

I'm trying to seed DB in the Node JS part logic at the `before` hook
We have the `cls-hooked` and 1 more internal npm module for sharing both use `async_hooks`
When I'm trying to import and use any of that modules I receive crashes at the test script launch:
```
Error: Webpack Compilation Error
./node_modules/...[our private module name].../lib/...[file name]....js
Module not found: Error: Can't resolve 'async_hooks' in '/Users/.../node_modules/...[private module or cls-hooked].../lib'
resolve 'async_hooks' in '/Users/.../node_modules/...[private module or cls-hooked].../lib'
  Parsed request is a module
  using description file: /Users/.../node_modules/...[private module or cls-hooked].../package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
```

### Desired behavior

Test script launch should go smoothly with `before` hook executing

### Test code to reproduce

require some module in `./cypress/plugins/index.ts` with next similar logic

shared/index.ts
```TypeScript
const async_hooks = require("async_hooks");
export const asyncLocalStorage = new async_hooks.AsyncLocalStorage();

export enum TaskEnum {
    task1: 'task1',
}
```

integration/someTest.ts
```TypeScript
before(() => {
  cy.task(TaskEnum.task1, `let's rock!`);
});
```

cypress/plugin/index.ts
```TypeScript
import { TaskEnum, asyncLocalStorage } from
...
on('task', {
    [TaskEnum.task1](message: string): void {
      console.log('message', message);
      asyncLocalStorage.getStore();
});
```

### Cypress Version

`^8.1.0` - `8.5.0`
```Cypress package version: 8.5.0
Cypress binary version: 8.5.0
Electron version: 13.2.0
Bundled Node version: 14.16.0
```

the same for:
```Cypress package version: 7.7.0
Cypress binary version: 7.7.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1
```
### Other

Using TS
```"typescript": "^4.1.5"```
OS
`macOS Big Sur 11.16`

**Comment by mmayors** [comment]
I'm hitting this too, Cypress version 9.6.0. I'm trying to export common utils (run in the browser) and custom tasks (Node) from a shared package.

**Comment by cjshelton** [comment]
@kosiakMD Did you find a solution to this?

**Comment by kosiakMD** [comment]
> @kosiakMD Did you find a solution to this?

unfortunately no
