### ISSUE TITLE
Opened page dissapears

### ISSUE THREAD

**Issue by VitalyAdweek** [cypress-io/cypress#18359]
### Current behavior

When the link is clicked the new page appears for a moment and then disappears 
AND
The following error is shown:
Timed out retrying after 6000ms: expected '<a.nav-link.text-uppercase.active.>' to be 'visible'
This element <a.nav-link.text-uppercase.active.> is not visible because it has an effective width and height of: 0 x 0 pixels.

### Desired behavior

When the link is clicked the new page is kept opened AND Brand Marketing text is visible

### Test code to reproduce
```js
it( 'Test', function() {
                cy.visit( 'https://www.adweek.com/' );
                cy.get('nav').contains('Brand Marketing').click();
                cy.wait(1000);
                cy.contains('Brand Marketing').should('be.visible');
            })   
```

### Cypress Version

8.5.0

### Other

Sometimes only an ad unit is shown, maybe the framework is going inside an ad iframe?
![Screen Shot 2021-10-05 at 10 35 32 AM](https://user-images.githubusercontent.com/82416786/136044650-12c50a99-479b-4d3e-93e2-e9951c1316e0.png)

**Comment by Fadelallah** [comment]
🤨🤨
