### ISSUE TITLE
Weird reports for smart orchestration

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#18352]
### Current behavior

Schrödinger's "Run failed tests first" feature. Unavailable but somehow running at the same time

<img width="599" alt="Screen Shot 2021-10-04 at 21 42 51" src="https://user-images.githubusercontent.com/2212006/135947326-26c0f996-d008-4038-a3cc-185b3c9fc4a4.png">

Saw this in this project https://dashboard.cypress.io/projects/f1j79r/runs/124/overview

### Desired behavior

I want some whitespace between the spinner and the text, and this whole widget is weird. Enabling these settings to me is a not a "100% is the goal", so why does it always tell me 1/3 ...

### Test code to reproduce

It was during the public run https://dashboard.cypress.io/projects/f1j79r/runs/124/overview

### Cypress Version

8.5.0

**Comment by finnstech** [comment]
This has been fixed. Closing.
