### ISSUE TITLE
How to use cypress to test on CNAME forwarded production sites which run on https?

### ISSUE THREAD

**Issue by keerthanaca** [cypress-io/cypress#18366]
### Current behavior

We automated our local docker application using cypress.However in production, the frontend is hosted in cloudfront andbacked is hosted on AWS ELB enabled with a certificate created onour domain, so that the requests only from our domain are honored inthe ELB. Now the cloudfront and domain redirected (through CNAME) ELBbackend are functional in manual testing. However in cypress automationthe login button in the login page served through cloudfront (in https mode)is not returning any response to the cypress click when the login page is loadedin cypress. We think that this has something to do with the cypress' way of injectingits code into application which makes event processing better and smoother asper cypress architecture guidelines. Any workaround for this?The certificates are AWS generated and they never leave AWS except for the publickey and the certificate chain.

### Test code to reproduce

static visit() {
    cy.visit(URL)
  }

### Cypress Version

8.3.0

**Comment by ditionl** [comment]
@keerthanaca  was there a solution to this issue?
