### ISSUE TITLE
Redirect from authentication provider to application not working since chrome 94 removed CookiesWithoutSameSiteMustBeSecure

### ISSUE THREAD

**Issue by simon-ittmann** [cypress-io/cypress#18377]
### Current behavior

After login in on a external login mask of the authentication provider the redirect back to the application is not working. Just a white page occurs and the command line shows this error:

_Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being set in a cross-site context. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests._

Before chome 94 it worked with this workaround:

    _on('before:browser:launch', (browser, launchOptions) => {
        if (browser.name === 'chrome') {
            launchOptions.args.push('--disable-features=SameSiteByDefaultCookies');
        }
        return launchOptions;
    });_

This workaround is not supported anymore. Is there any other possibility to get tests running again?

### Desired behavior

Redirect back to the application should work (no white page)

### Test code to reproduce

-

### Cypress Version

8.5.0

**Comment by mbenzenhoefer** [comment]
any updates on this issue? Having the same issue...

**Comment by Zach-Costa** [comment]
My team is also having this issue, and it's preventing us from running our tests on Chrome entirely. Are there any updates on this?

**Comment by 7118path** [comment]
We are having this issue also starting from Cypress 8.0. We are testing an app for nextcloud, which enables a user to connect an eID provided by an Identity Provider with it`s account and use it for login based on SAML.

The Problem occurs in electron 93 and chrome 96. 

This is how chrome 96 started with the flag "--enable-features=SameSiteDefaultChecksMethodRigorously" behaves outside cypress:
* it sends the cookie "oc_sessionPassphrase" with "samesite=None"
* it accepts the other nextcloud cookies which have "samesite=Lax" set

![cypress_cookie_sent_none](https://user-images.githubusercontent.com/59734644/145374930-245924b3-b49b-42a6-9b75-578bcef038b3.png)

![chrome_cookie_accepted](https://user-images.githubusercontent.com/59734644/145373651-4bde724c-6262-4c9a-a505-a11cf2c99099.png)
Therefore the user is still logged in after returning from the Identity Provider.

This is how chrome 96 behaves in cypress
* it sends the cookie "oc_sessionPassphrase" with "samesite=Lax" or does not sent it at all
* it rejects all cookies which have "samesite=Lax" set

![cypress_cookie_sent_lax](https://user-images.githubusercontent.com/59734644/145375089-7eb9a4ec-5dc4-41f8-b31e-61fbe6f36927.png)
![cypress_cookie_not_accepted](https://user-images.githubusercontent.com/59734644/145375121-8f9281f1-cda6-48e2-bb9b-1937e506cdba.png)
Therefore the user is NOT logged in after returning from the Identity Provider.

This difference in behaviour seems strange to me and is maybe a bug? Should I open another issue for this?

@ecmrauh FYI

**Comment by tanmdoan** [comment]
We are also relying on this work around, just adding our name to the hat, thanks! 🙏

**Comment by plebcity** [comment]
We're having the exact same issue

**Comment by ttomaszewski** [comment]
Same issue. Please fix.

**Comment by meruu** [comment]
We are facing same issue, please let us know if there are any workarounds

**Comment by andyg101** [comment]
Update: I tried upgrading to the latest version of Cypress 9.5.3 and this is also now happeingin with Chrome 100 and electron 94

**Comment by tdsproulehpd** [comment]
+1 for this issue - it is affecting our tests with KeyCloak with Chrome

**Comment by ttomaszewski** [comment]
+1

**Comment by AtofStryker** [comment]
Hi @simon-ittmann . Would you be able to try this login with `cy.origin`  with the `experimentalSessionAndOrigin` flag set to true to use Lax cookies by default and not pass in the `--disable-features=SameSiteByDefaultCookies` flag? This does work with keycloak and chrome in #22282. I am going to close as I think the cookie management issues are solved with cross-origin testing support and handled correctly in the proxy, but if not let us know and we can reopen
