### ISSUE TITLE
Typing issue in date field

### ISSUE THREAD

**Issue by ehtsham-rns** [cypress-io/cypress#18387]
### Current behavior

Typing was successful from Cypress, but the dates are not visible on UI.
[Visual proof](https://drive.google.com/file/d/1zeb2356G1c16RQFWrd_71dUZlYtat6kj/view?usp=sharing)

### Desired behavior

After successful typing from Cypress, dates should be visible on UI.

### Test code to reproduce

cy.get("#startdate").type("2050-05-05");
cy.get("#enddate").type("2050-05-05");

![image](https://user-images.githubusercontent.com/78526974/136325315-df4b9460-2c49-4e17-95b1-99639b770aaf.png)

### Cypress Version

8.5.0

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by paul-hammant** [comment]
I'm getting this too with v10.10.0.  I can find the date picker, and seeming type into it, but nothing it in changes.  The cypress script continues just fine to the next step.

If we deliver a smallest-possible-reproduction to GitHub, would the maintainers be pleased?

**Comment by mark-r-maciver-db** [comment]
I also observe this in v10,6.0
