### ISSUE TITLE
Ability to delete run from Dashboard

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1839]
### Current behavior:

Users may want to delete runs due to sensitive data or just to clean up their Dashboard.

### Desired behavior:

Button at top of run that say "Delete run data" with confirmation dialog. 

![36328792-832f04c0-1331-11e8-9bc0-1b9d04693770](https://user-images.githubusercontent.com/1271364/40792571-46cc004e-64c8-11e8-8f3e-2a42523481d2.png)

- API Issue: https://github.com/cypress-io/cypress-api/issues/376
- Dashboard Issue: https://github.com/cypress-io/cypress-dashboard/issues/501

**Comment by phoebe-lew** [comment]
If a user deletes a private test run, will it no longer count towards their limit for private recordings?

**Comment by jennifer-shehane** [comment]
@phoebe-lew The usage reflects the total number of tests recordings that actually ran this month. Deleting runs will have no effect on the usage.

**Comment by hvuong-sigma** [comment]
@jennifer-shehane 

Bump - this is a useful feature. I'm having trouble with ghost runs via ci that can't be killed.

**Comment by jennifer-shehane** [comment]
You can express interest in this feature and see it's progress on our Roadmap from our Dashboard's new product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard/c/36-delete-runs

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
