### ISSUE TITLE
@cypress/webpack-dev-server + run-ct command hangs if multiple repos run at same time 

### ISSUE THREAD

**Issue by sdaconceicao** [cypress-io/cypress#18402]
### Current behavior

We currently have multiple jenkins pipelines running cypress components tests via cypress run-ct commands with @cypress/webpack-dev-server. If 2 jobs run the run-ct task at the same time on the jenkins instance, the run-ct command hangs indefinitely on the 2nd pipeline.
With verbose debugging on, there is an error about the port already being in use

### Desired behavior

Ideally the 2nd pipeline's run-ct command should retry itself with a different port. Having an option to set the webpack dev server port would also be an option.

### Test code to reproduce

Setup 2 repos running @cypress/webpack-dev-server, then try and run their tests at the same time with debugging enabled. 

plugins/index.js
```js
const injectCraDevServer = require('@cypress/react/plugins/react-scripts');

module.exports = (on, config) => {
  injectCraDevServer(on, { ...config, addTranspiledFolders: ['.storybook'] });
  return config;
};
```

DEBUG=cypress:* cypress run-ct

The first run-ct should work normally, the second returns an error:
```
 cypress:server:plugins:child uncaught exception: {
  name: 'Error',
  message: 'listen EADDRINUSE: address already in use 127.0.0.1:2121',
  stack: 'Error: listen EADDRINUSE: address already in use 127.0.0.1:2121\n' +
    '    at Server.setupListenHandle [as _listen2] (net.js:1318:16)\n' +
    '    at listenInCluster (net.js:1366:12)\n' +
    '    at GetAddrInfoReqWrap.doListen (net.js:1503:7)\n' +
    '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)',
  code: 'EADDRINUSE'
```

### Cypress Version

7.0.0

**Comment by JessicaSachs** [comment]
Related to running Cypress in parallel here https://github.com/cypress-io/cypress/issues/18446

We need to fail over two different ports with `get-port` like we do for the latest releases of `vite-dev-server`

**Comment by larsk2009** [comment]
Any updates on this?

**Comment by lmiller1990** [comment]
I tried this just now, it's working fine for me - two terminals, two `npx cypress run --component`, tests executed.

The second one correctly opened a new port on 8081.

Happy to re-open if this is still an issue, but seems fine now when testing on Cypress 12.
