### ISSUE TITLE
`desktop-gui` can display wrong `<record-key>` instructions on slow Internet

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#18403]
### Current behavior

1. Slow down your internet, or use staging environment to slow it down.
2. Connect to a project on the dashboard.
3. Observe that an incorrect CLI command is readable and copyable for some time, potentially enough to read it: 
![image](https://user-images.githubusercontent.com/1151760/136466447-00a915db-8282-421c-b2fd-1f16ec1d3e16.png)

### Desired behavior

Display a loading indicator in place of the command.		

### Test code to reproduce

--

### Cypress Version

all

**Comment by bahmutov** [comment]
Haha I just saw that and was hmm, what is happening

**Comment by jennifer-shehane** [comment]
I feel like this was introduced recently with this PR https://github.com/cypress-io/cypress/pull/17317 because I did have this problem when I was testing that branch.

**Comment by jennifer-shehane** [comment]
Closing as this entire UI was rewritten in 10.0.
