### ISSUE TITLE
trashAssetsBeforeRuns does not clear screenshots folder

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/cypress#18410]
### Current behavior

`trashAssetsBeforeRuns` does not clear screenshots folder as it is supposed to documentation https://docs.cypress.io/guides/references/configuration#Screenshots

### Desired behavior

clear screenshots folder

### Test code to reproduce

Add `"trashAssetsBeforeRuns": true,` to cypress.json

### Cypress Version

8.5.0

**Comment by kpurikhova** [comment]
Same for downloads folder!
Cypress Version 9.5.1

**Comment by emilyrohrbough** [comment]
duplicate of https://github.com/cypress-io/cypress/issues/8280. Closing in favor of https://github.com/cypress-io/cypress/issues/8280.
