### ISSUE TITLE
Dashboard - can't add more than 1 user

### ISSUE THREAD

**Issue by bkoper** [cypress-io/cypress#1842]
### Is this a Feature or Bug?
It's a bug

### Current behavior + Steps to reproduce

1. go to Dashboard -> organizations -> users
2. try to invite more than one user
3. nothing happens (no error is displayed)
4. request gets 402, with a message that in order to add more users I have to upgrade billing plan
<img width="1786" alt="screen shot 2018-05-31 at 20 26 14" src="https://user-images.githubusercontent.com/519968/40800575-10909532-6511-11e8-9dc1-b6808ebe2eb2.png">

### Desired behavior:
- there is no possibility for now to upgrade billing plan
- in beta, all features should be available
<img width="802" alt="screen shot 2018-05-31 at 20 29 19" src="https://user-images.githubusercontent.com/519968/40800712-6bd6f40e-6511-11e8-9e6a-4cea5de97f25.png">

**Comment by brian-mann** [comment]
We're aware of the issue and have created a patch that is deploying now - you'll see this fixed in the next 15 minutes or so.

**Comment by brian-mann** [comment]
We had a feature flag not working correctly so the billing validations leaked out.

**Comment by bkoper** [comment]
you're really quick :) thanks

Are you aware of another bug, that invitation does not work. Or maybe I'm doing something wrong, but accepting invitation link just shows user's personal dashboard and invited users remain with status pending. I can file another bug if it helps.

**Comment by bkoper** [comment]
I can confirm, it works fine now.

Thanks again

**Comment by brian-mann** [comment]
@bkoper open another issue if you're experiencing something else that's different
