### ISSUE TITLE
cy.intercept does not "see" header added from the middleware intercept

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#18436]
### Current behavior

The test below

```js
describe('Adding header', () => {
  beforeEach(() => {
    cy.intercept(
      {
        method: 'POST',
        url: '/',
        middleware: true,
      },
      (req) => {
        console.log('operationName: %s', req.body.operationName)
        req.headers['x-intercept-operation'] = req.body.operationName
      },
    ).as('posted')
  })

  it('intercepts operations using header added above', () => {
    cy.intercept({
      method: 'POST',
      url: '/',
      headers: {
        // "x-gql-operation-name" is added by the Apollo Client
        // and matching by it works
        // 'x-gql-operation-name': 'allTodos',

        // "x-intercept-operation" is added by the intercept middleware above
        // and this matcher does not work
        'x-intercept-operation': 'allTodos',
      },
    }).as('allTodos')

    cy.visit('/')
    cy.wait('@allTodos')
  })
})
```

Using a custom header set by the application works. Trying to use a header set in the middleware intercept does not work, even though I can see it has worked.

<img width="1273" alt="Screen Shot 2021-10-11 at 08 39 37" src="https://user-images.githubusercontent.com/2212006/136791693-eaab19af-2924-4c8a-b6ea-f123a4e71ad0.png">

### Desired behavior

For GraphQL matching, being able to set the header in the middleware intercept is super convenient - since then all other matchers can be static, and set the aliases correctly.

### Test code to reproduce

- clone https://github.com/bahmutov/todo-graphql-example
- check out branch `add-header-in-middleware`
- run `npm install`
- run `npm run dev`
- click on the `add-header-spec.js` to run the failing test

### Cypress Version

8.5.0

**Comment by awilson9** [comment]
+1 on this, currently I am dynamically intercepting the graphql requests and adding a value to req.alias, however requests intercepted this way do not show up properly in the routes table that's generated for a request. The suggestion here would allow us to intercept separate routes based on header and properly reflect that in the table

<img width="643" alt="Screen Shot 2022-02-07 at 5 23 50 PM" src="https://user-images.githubusercontent.com/15809032/152900215-ae9e1667-aa7e-4e67-9f87-df8f5554213d.png">

**Comment by npostma** [comment]
+1 I have encountered this issue a few times now. The system i am testing does have a one entry point (one url) and a header to route the request. This is done with the header x-route in the request header. But on pages with 2 or more requests i cant differentiate between those requests.

Example:

`
cy.intercept({
        method: 'POST',
        url: '/API/V1/PageRequestHandler.php',
        headers: {
            'x-route': 'AddPage'
        }
    }).as('POST::page-add')
    
    cy.intercept({
        method: 'POST',
        url: '/API/V1/PageRequestHandler.php',
        headers: {
            'x-route': 'SortPages'
        }
    }).as('POST::page-sort')
`

I cant wait for both calls.  Those will always be caught by the first intercept. Cypress will see `POST::page-add` twice.
