### ISSUE TITLE
Does cypress support FIPS?

### ISSUE THREAD

**Issue by gouyang** [cypress-io/cypress#18434]
### Current behavior

While running tests in headless mode against a FIPS enabled server, it meet below error:

CypressError: `cy.visit()` failed trying to load:
16:09:47  
16:09:47  https://www.example-server.com/
16:09:47  
16:09:47  We attempted to make an http request to this URL but the request failed without a response.
16:09:47  
16:09:47  We received this error at the network level:
16:09:47  
16:09:47    > Error: Client network socket disconnected before secure TLS connection was established
16:09:47  
16:09:47  Common situations why this would fail:
16:09:47    - you don't have internet access
16:09:47    - you forgot to run / boot your web server
16:09:47    - your web server isn't accessible
16:09:47    - you have weird network configuration settings on your computer

Note: the server is accessible by curl and cypress GUI, just not able to access it in headless mode.

### Test code to reproduce

This is about server connection, not test code related.

### Cypress Version

8.5.0

**Comment by LiZhang19817** [comment]
The same question as above, Does Cypress support FIPS?

**Comment by sathismr** [comment]
I also face the same issue. Is there any solution? Thanks!

**Comment by hchenxa** [comment]
same for me

**Comment by dtthuynh** [comment]
Looks like this happens in specific browser types. Try running with `electron` (bundled with cypress)
