### ISSUE TITLE
.type() doesn't work properly in for loop.

### ISSUE THREAD

**Issue by spbond** [cypress-io/cypress#1843]
### Is this a Feature or Bug?
Bug

### Current behavior:
Second iteration clears input instead of concatenating, third iteration concatenates.

![image](https://user-images.githubusercontent.com/3751622/40803860-2907f6fa-64c6-11e8-8033-6d5f8c498030.png)
```ts
cy.get( "#maxSessions input[type=text]" ).first().focus().clear();

let input: string = "";
for ( let digit: number = 0; digit < 10; ++digit ) {
    input += digit.toString();

    cy.focused()
    .type( digit.toString() )
    .should( "have.value", digit.toString() );
}
```

### Desired behavior:
Every iteration through the loop should concatenate to existing value.

### Steps to reproduce:
I have provided the code above which produces this behavior and a screenshot showing the results.

### Versions
OS: Kubuntu Linux 16.04 (64-bit)
Cypress: 2.1.0
Chrome: 66.0.3359.181 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
I think this may be due to [how Cypress runs commands](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Noisy-Promise-demonstration-Not-valid-code). Can you try this:
```
cy.get( "#maxSessions input[type=text]" ).first().focus().clear().then(() => {
  let input: string = "";
  for ( let digit: number = 0; digit < 10; ++digit ) {
      input += digit.toString();

      cy.focused()
      .type( digit.toString() )
      .should( "have.value", digit.toString() );
  }
};
```

**Comment by spbond** [comment]
I tried your suggestion, but the behavior is unchanged.

**Comment by spbond** [comment]
My apologies I was casting the input to a number using parseInt(), which was removing the leading zero.  The for loop works as it should.
