### ISSUE TITLE
[Chromium] The automation client disconnected. Cannot continue running tests.

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress#18433]
### Current behavior

Since today, Cypress will immediately crash each time I start a test with Chromium. How to reproduce:

1. clone the real world app at `git@github.com:cypress-io/cypress-realworld-app.git`
2. run `yarn install`
3. run `yarn dev`
4. in another terminal run `yarn cypress:open`
5. select "Chromium" browser in Cypress
6. select `bankaccounts.spec.ts` in Cypress

Chromium opens and closes itself after less than five seconds. The terminal shows:

> The automation client disconnected. Cannot continue running tests.`

### Desired behavior

Chromium opens and the test starts and finishes successfully

### Test code to reproduce

n/a

### Cypress Version

8.5.0

### Other

Chromium: Version 94.0.4606.61 (Developer Build) Fedora Project (64-bit)

**Comment by rkrisztian** [comment]
I get the same issue with the same version of Chromium and Cypress, on RHEL 8.

**Comment by mjhenkes** [comment]
I am unable to recreate this issue with either chromium 97 or 94 on mac OS. What system are you running on? What happens if you upgrade chromium?

Cypress version: 8.5.0
Chromium version: 94.0.4606.0
System: mac os 11.6

**Comment by DamienCassou** [comment]
I can't reproduce either. You may close the issue unless @rkrisztian has anything to add.

**Comment by rkrisztian** [comment]
@DamienCassou , @mjhenkes , yes I can still reproduce this issue. Recently upgraded Cypress to 9.2.1, Chromium version is still at 94, OS is RHEL 8.4.
