### ISSUE TITLE
Cypress Test runner showing status code 200 intead of 302

### ISSUE THREAD

**Issue by sowmyasridharamurthy** [cypress-io/cypress#18459]
### Current behavior

Cypress test runner, a post API is called and status captured as 200 instead of 302.

because of this the location is also not getting filled in the repsonse header.  

However when we execute the same manually, we see in network call the status code returned will be 302 with location in response header

### Test code to reproduce

sorry this is internal to organization, cannot expose the test code

### Cypress Version

latest

### Other

Cypress Test runner
![image](https://user-images.githubusercontent.com/35350156/136993257-791e1be8-afe9-4dc3-b248-5a0640dc8247.png)

location not captured in runner 
![image](https://user-images.githubusercontent.com/35350156/136993865-1fbcad3e-4fb6-4da0-a438-0b323640e84c.png)

Network call in normal browser
![image](https://user-images.githubusercontent.com/35350156/136993736-46b6b09a-564d-4f70-9dca-4d5f00b35e51.png)
 
location is shown in respose header
![image](https://user-images.githubusercontent.com/35350156/136993946-d0d848c8-815f-40e5-9f7d-a65ccea487a3.png)

**Comment by mistvan** [comment]
experiencing same issue when trying to log into my wordpress website, please help

**Comment by mistvan** [comment]
I found workaround. Just trying login twice I am logged in successfully.

**Comment by tumbatata** [comment]
the same with me. I'd have a status of 200 (no code error and confirmed by Postman), however cypress is considering status 202 and breaking the rest of my tests.

**Comment by anandhij** [comment]
I have similar issue. But I am expecting a 200 and it returns 302 and loads the error page. When I run the test manually in the browser, it works fine and returns 200 and lands on the correct page. Any advice please?

**Comment by aymanapatel** [comment]
We are also facing issue when we are running behind a login. It calls API the first time (200) but calls 302 when we call new API within the same page.

**Comment by Skibsons** [comment]
Same for me, it is forcing me to create test objects without using API.
