### ISSUE TITLE
cypress run --spec cypress/integration/APP/**/* runs all tests instead of just subfolder APP tests

### ISSUE THREAD

**Issue by maximilianschmid** [cypress-io/cypress#1845]
### Is this a Feature or Bug?
Bug

### Current behavior:
I have two subfolders in my integration folder:
cypress/integration/APP/
cypress/integration/API/

When I run 
> cypress run --spec cypress/integration/APP/**/*

ALL tests run, but I expected that only tests in the APP subfolder would run. 
Is this a bug or intended behaviour? Doesn't the --spec flag support globs?

### Desired behavior:
Just run tests in cypress/integration/APP/ subfolder
The --spec feature would be really useful if I could run all tests in different subfolders so I could manually distribute tests across machines. 

### Steps to reproduce:
```bash
cypress run --spec cypress/integration/SUBFOLDER/**/*
```

### Versions
cypress 3.0.1 on Mac OS 10.13.4

**Comment by jennifer-shehane** [comment]
You should see new output we added in 3.0 that specifies **Specs** and **Searched**

**Specs** being the specs that will be run
**Searched** being what Cypress used to search for the specs (should show `cypress/integration/customer_spec.js,cypress/integration/faxes_spec.js` if it runs accurately)

<img width="825" alt="screen shot 2018-05-31 at 12 37 13 pm" src="https://user-images.githubusercontent.com/1271364/40795260-7b5f1f1a-64cf-11e8-8715-f1bf97b05f3a.png">

What is printed in these fields in the console ouput?

You can run different subfolders by passing multiple globs to the spec argument like:
```
cypress run --spec cypress/integration/APP/**/*,cypress/integration/API/**/*
```

**Comment by jennifer-shehane** [comment]
I just ran mine for a subfolder and it did work for me. Double check your glob with a glob tester. 

If it's still not working, let me know what terminal you are using. 

```
$ ./node_modules/.bin/cypress run --spec cypress/integration/examples/**/*


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.0.0                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      19 found (examples/actions.spec.js, examples/aliasing.spec.js, examples/assertion… │
  │ Searched:   cypress/integration/examples/**/*                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by maximilianschmid** [comment]
Thanks for your helpful response.
I further investigated this issue. I'm using the original Mac OS Terminal.

> cypress run --spec cypress/integration/API/**/*

Output:
  │ Cypress:    3.0.1                                                                           
  │ Browser:    Electron 59 (headless)                                                           
  │ Specs:      199 found (_reset-to-fixtures.spec.js, API/crm/task-crm-test-end.spec.js, API/doc… 
(1 of 199) 


BUT when **adding a trailing comma** to the glob only tests in API folder run, so it works as expected:

> cypress run --spec cypress/integration/API/**/*,

Output:
 │ Cypress:    3.0.1                                                                       
 │ Browser:    Electron 59 (headless)                                                           
 │ Specs:      125 found (API/crm/task-crm-test-end.spec.js, API/documents/acl_GET_all.spec.js, …    
 │ Searched:   cypress/integration/API/**/*,                                                   
   (1 of 125) 

Tested with locally installed cypress (npm i cypress) and globally installed cypress (npm i cypress -g) - both show the same behaviour.


So adding a trailing comma to the glob works for me and is ok for me as workaround.

**Comment by silversteez** [comment]
Just want to chime in to say I had the same issue and adding the trailing comma got it working for me. (Thanks @maximilianschmid) 

```
  "scripts": {
    "cypress:open": "cypress open",
    "cypress:run": "cypress run --spec cypress/integration/test/**/*,"
  },
```

**Comment by brian-mann** [comment]
@silversteez @maximilianschmid try adding single quotes around the spec glob or use an equals sign...

```
cypress run --spec 'cypress/integration/test/**/*'
cypress run --spec=cypress/integration/test/**/*
```

**Comment by silversteez** [comment]
@brian-mann Yup, both of those work for me, as well. Thanks.

**Comment by maximilianschmid** [comment]
@brian-mann both solutions work form me as well. thx. 

Checkout your documentation to reflect this solutions:
https://docs.cypress.io/guides/guides/command-line.html#Run-tests-specifying-a-project

**Comment by brian-mann** [comment]
We updated the documentation last week and I'm going to close this issue.
