### ISSUE TITLE
cy.request unauthorized error

### ISSUE THREAD

**Issue by kamilpioro** [cypress-io/cypress#18469]
### Current behavior

Yesterday I've updated Cypress version 6.8.0->8.6.0.

Since then I've spotted an issue that poped up for cy.request.

I'm constantly receiving unauthorized error for the same request that was working in 6.8.0.

  > 401: Unauthorized

The solution here is to pass _contador_session cookie every time we send a request.
This wasn't a problem earlier since we were passing cookie every time.

Also spotted that its working as before when I pass it on our testing env, but fails on local env.

### Desired behavior

Cookie should be added in every cy.request call by default.

### Test code to reproduce

```
Cypress.Commands.add('sendRequest', (test, leg, route = '/{request}') => {
  cy.getCookie('_contador_session').then((cookie) => {
    cy.request({
      method: 'PUT',
      url: route,
      body: {
        leg,
        name: test,
      },
      headers: {
        cookie: `_contador_session=${cookie.value}`,
      },
    }, { timeout: 20000 }).then((response) => {
      expect(response.body).to.have.property('status', 'ok');
    });
  });
```
  
  It's working again for such code, but stops when we remove cookie from headers.

### Cypress Version

6.8.0

### Other

PS. I'm logging in to app in before (() => and using Cypress.Cookies.preserveOnce('_contador_session'); in beforeEach.
PS2. I've checked other versions and it happens also after updating to 7.0.0

**Comment by getpoucher** [comment]
I'm having the same issue on v10.1.0, it's quite verbose to get cookies values on each request

**Comment by kamilpioro** [comment]
Here is a workaround for this.
`Cypress.Commands.add('authRequest', (...args) => cy.getCookie('_contador_session').then((cookie) => {
  if (cookie) {
    const firstArg = args[0];
    let headers;
    let url;
    let method;
    let body = null;

    if (typeof firstArg === 'object') {
      headers = {
        ...firstArg.headers,
        cookie: `_contador_session=${cookie.value}; ${firstArg?.headers?.cookie || ''}`,
      };
      method = firstArg.method;
      url = firstArg.url;
      body = firstArg.body;
    } else { // two params case method + url
      const [arg1, arg2] = args || [];
      method = arg1;
      url = arg2;
      headers = {
        cookie: `_contador_session=${cookie.value}`,
      };
    }

    return cy.request({
      method,
      url,
      headers,
      body,
    });
  }
  return cy.request(...args);
}));`

**Comment by kamilpioro** [comment]
> I'm having the same issue on v10.1.0, it's quite verbose to get cookies values on each request

Here is workaround for that.

`Cypress.Commands.add('authRequest', (...args) => cy.getCookie('_contador_session').then((cookie) => {
  if (cookie) {
    const firstArg = args[0];
    let headers;
    let url;
    let method;
    let body = null;
    if (typeof firstArg === 'object') {
      headers = {
        ...firstArg.headers,
        cookie: `_contador_session=${cookie.value}; ${firstArg?.headers?.cookie || ''}`,
      };
      method = firstArg.method;
      url = firstArg.url;
      body = firstArg.body;
    } else { // two params case method + url
      const [arg1, arg2] = args || [];
      method = arg1;
      url = arg2;
      headers = {
        cookie: `_contador_session=${cookie.value}`,
      };
    }
    return cy.request({
      method,
      url,
      headers,
      body,
    });
  }
  return cy.request(...args);
}));
`
