### ISSUE TITLE
cy.exec timeout issues

### ISSUE THREAD

**Issue by paulsheldrake** [cypress-io/cypress#18493]
### Current behavior

`cy.exec` seems to timeout when there is a double hypen in the command.

For example between "environment" and "uli":
```
CypressError: `cy.exec('terminus -n -vvv drush mysite.environment --  uli --uid=1191')` timed out after waiting `60000ms`.
```

### Desired behavior

When the command is run without the "--" the `exec` completes.   

The double hyphen is part of the formatting of the `terminus` client https://github.com/pantheon-systems/terminus so just removing it causes the command to not complete as expected.

### Test code to reproduce

Unfortunately, the `terminus` client is integrated into the Pantheon hosting system so there isn't an example to share without also having a site hosted on Pantheon.

### Cypress Version

8.5.0

**Comment by joelsteidl** [comment]
@paulsheldrake I'm seeing the same behavior. Many `terminus` commands (example `terminus site:list`) will execute with `cy.exec`, but `terminus drush` commands specifically fail every time for me. I think you are on the right track with the `--` causing the problem.

Example:
`terminus drush site.env st` will output `Command: site.env -- drush st [Exit: 0]` in my normal CLI and `cy.exec`  will timeout. Unfortunately there is no helpful debug info I can get...just a timeout.

Were you able to find a workaround?

**Comment by paulsheldrake** [comment]
Hello

My colleague @sean-e-dietrich figured out that you can basically `ssh` into a pantheon environment and pass in the drush commands.

i.e.
```
let cmd = 'ssh -T live.bc58863457-666-4adf-9c95-0007542abfcd@appserver.live.bc58863457-666-4adf-9c95-0007542abfcd.drush.in -p 2222 -o "StrictHostKeyChecking=no" -o "AddressFamily inet" "drush uli"'
```

We then wrapped that in a command that would figure out if you were running the test locally or on a pantheon environment so `drush` just kind of works wherever

**Comment by joelsteidl** [comment]
Thanks for the help! I made it a bit more flexible if ever useful...pardon my JS skills. :-)

`Cypress.Commands.add("terminusDrush", (cmd) => {
  // Terminus Drush Fails...this is a workaround.
  const site = Cypress.env("PANTHEON_SITE");
  const env = Cypress.env("PANTHEON_ENV");
  const terminus = Cypress.env("TERMINUS");
  cy.exec(`${terminus} connection:info ${site}.${env} --format=json`)
    .its("stdout")
    .should("contain", "sftp_command")
    .then(function (stdout) {
      const connections = JSON.parse(stdout);
      const sftp_connection = connections.sftp_command;
      const env_connection = sftp_connection.replace("sftp -o Port=2222 ", "");
      const execCmd = `ssh -T ${env_connection} -p 2222 -o "StrictHostKeyChecking=no" -o "AddressFamily inet" "drush ${cmd}"`;
      cy.exec(execCmd)
        .its("stdout")
        .then(function (stdout) {
          return stdout;
        });
    });
});`

It can be called like:

`cy.terminusDrush("uli --uid=1").then(function (url) {
      cy.visit(url);
 });`

**Comment by aangelinsf** [comment]
Glad to have found this...experienced the same issue and came here to see if others had.
