### ISSUE TITLE
Electron video not playable in Firefox browser since Cypress 8.6.0

### ISSUE THREAD

**Issue by imichellewang** [cypress-io/cypress#18503]
### Current behavior

Got this error when trying to play the recorded test video

<img width="1210" alt="Screen Shot 2021-10-15 at 11 36 07 am" src="https://user-images.githubusercontent.com/91445150/137414062-e55af339-d9a3-4433-a1f3-dff4ac5f4e4f.png">

### Desired behavior

I can replay the video.

### Test code to reproduce

Test run and recorded successfully, but the video link is broken.

https://dashboard.cypress.io/projects/se51fq/runs/8/test-results/b17742d3-5178-4fb2-9c37-730927f45e26/video?utm_source=Dashboard&utm_medium=Share+URL&utm_campaign=Video

### Cypress Version

8.6.0

### Other

This might related to upgrading cypress to latest version, it was working before.

**Comment by jennifer-shehane** [comment]
Hmm, this video link does load for me fine. Can you try again and see if it loads?

What browser / OS are you using to view the video in the Dashboard? Do you see any errors in the console when viewing this video?
