### ISSUE TITLE
Problem with running test from script

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#1850]
### Current behavior:
When i'm trying to run test from script, i'm getting errormessage:
![obraz](https://user-images.githubusercontent.com/34089686/40839852-7ce4efec-65a4-11e8-98b7-700575b78b46.png)

### Desired behavior:
Script should run

### Steps to reproduce:
This is my script. I'm sure that the path is correct.

```js
function runScript() {
    const cypress = require('cypress')
  
    cypress.run({
      browser: 'canary',  
      spec: '../../integration/1ARegisterDashboardCustomer.js'
    })
    .then((results) => {
      console.log(results)
    })
    .catch((err) => {
      console.error(err)
    })
  };
```

The same situation is for chrome and electron.

When i'm running it from Command Line using this:
```bash
cypress run --spec cypress/integration/filter.spec.js,cypress/integration/1ARegisterDashboardCustomer.js
```

it's working fine, but i need to run it from a script.

**Comment by jennifer-shehane** [comment]
Did you try running the same argument within the module as you did in the command line? So instead of `../../integration/1ARegisterDashboardCustomer.js` passing in `cypress/integration/1ARegisterDashboardCustomer.js`?

**Comment by zbigniewkalinowski** [comment]
![obraz](https://user-images.githubusercontent.com/34089686/40900563-6feb26ba-67cc-11e8-9d50-492d4521315d.png)

Crazy :)

**Comment by bahmutov** [comment]
@zbigniewkalinowski can you describe you project's folder structure? Where is the `cypress.json`, where is the integration folder, specs, etc? And from where do you run Cypress as a module? We have a project that tests module api with a few cases https://github.com/cypress-io/cypress-test-module-api - if you can recreate the structure, even without adding a test, here https://github.com/cypress-io/cypress-test-module-api/tree/master/test that would be great for us to recreate it.

**Comment by zbigniewkalinowski** [comment]
cypress.json folder:
C:\Users\Zbyszek\Automats\online

integration folder:
C:\Users\Zbyszek\Automats\online\cypress\integration

fileserv.js folder: (i'm trying to run this script from browser dashboard i made in html):
C:\Users\Zbyszek\Automats\online\cypress\support\dashboard

I added some additional logs.
This is my script now:

function runScript() {
    const cypress = require('cypress')
    console.log(path.join(__dirname, '../../integration/1ARegisterDashboardCustomer.js'))
  
    cypress.run({
      browser: 'canary',  
      spec: path.join(__dirname, '../../integration/1ARegisterDashboardCustomer.js')
    })
    .then((results) => {
      console.log(results)
    })
    .catch((err) => {
      console.error(err)
    })
  };

And this is what i'm getting now:
![obraz](https://user-images.githubusercontent.com/34089686/40960633-a21e7c48-68a0-11e8-8427-5c59b975df78.png)

As you can see the path in log is correct, so why it can't see spec file?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
