### ISSUE TITLE
Chrome, Edge, Chromium and Electron only: Timed out retrying after 4050ms: cy.click() failed because the center of this element is hidden from view:

### ISSUE THREAD

**Issue by eujeniozayats** [cypress-io/cypress#18527]
### Current behavior

Hello! I'm fully stuck. My tests have been working for the past 6 months correctly. Now it can't see our app's elements. 
BUT! It works fine on the current FF. I've also tried different versions of chrome and it did not help
![Screenshot_1](https://user-images.githubusercontent.com/61874901/137746903-f076d4d3-3ffb-43d1-921a-d9258ef49679.png)
.

### Desired behavior

Force true is not a solution. It should work fine on all browsers. Another tools like Selenium can also easily interact with these elements.

### Test code to reproduce

This is ordinary click() method

### Cypress Version

7.6.0

### Other

Downgrading Cypress version did not help

**Comment by Kolombiken** [comment]
I have a smilar issue. Using Cypress 10.0.2.
For some reason the page scrolls down when I want to perform a click. This hides the element is (which was visible before the scrolling took place). When interacting manually this never happens. If I only check for the existence of the element no scrolling is performed either. 
I'm guessing the scrolling happens so the element should be in focus but there is a bug in these browsers with scrolling to an element so instead the element is hidden outside the view. 

To resolve the issue for now I had to pass `scrollBehavior: false` to the click command.
