### ISSUE TITLE
Load fixed json file

### ISSUE THREAD

**Issue by theTestingApproach** [cypress-io/cypress#18526]
### Current behavior

Hello There,
I have a json file which i want to load everytime that the site runs my test as we reset db and do stuff like that and due to this all my test fail as the test data changes. Therefore i want to load my page with a fix data.

I have added this on my beforeEach so that the file loads this everytime:
cy.intercept('GET', '/amount/**', {fixture: 'ops.json'})
the api request i want to fix that too as the request changes everyday when the db resets.
but whenever i update my db it takes the recent db changes and not what is in the json file.
i know this is a platform for reporting actual bugs/feature request but i cannot figure out whats wrong with what i am doing.
Hoping to get some help on how this can be achieved.
thank you

### Desired behavior

It should load the page with my json file content

### Test code to reproduce

Create a json file with the different test data 

### Cypress Version

7.7.0

**Comment by Narretz** [comment]
For questions, you should really ask on Q&A sites like Stackoverflow.

That said, if the fixture isn't loaded, your url probably isn't matched by cy.intercept. In cy.open mode, the sidebar tracks xhr / fetch requests and shows if they are intercepted.
