### ISSUE TITLE
installing 8.6.0 webpack compilation error

### ISSUE THREAD

**Issue by jet7janice** [cypress-io/cypress#18556]
### Current behavior

Error: Webpack Compilation Error
./cypress/support/index.js
Module not found: Error: Can't resolve 'cypress-plugin-tab'

### Cypress Version

8.6.0

### Package Manager

npm

### Operating system

Mac

**Comment by emilyrohrbough** [comment]
@jet7janice Please provide additional information. Did you install the `cypress-plugin-tab` module before running cypress?
