### ISSUE TITLE
Session Cookies not Being set

### ISSUE THREAD

**Issue by Gouravroy7** [cypress-io/cypress#18558]
### Current behavior

Our Api call is returning set-cookie header , but its not setting any cookie , and I am unable to see the cookie in the Application panel. Please find the image in the below link.

![Cypress Api Response Header](https://user-images.githubusercontent.com/43235534/138034552-083fb201-6ab8-4f6d-914a-e285321ea230.png)

### Desired behavior

It should set the Session Cookie and the session should be appended to subsequent api calls request headers , thereby not creating new session for each call.

### Test code to reproduce

  cy.intercept({url: '**/path/*', middleware: true}, (req) => {
      if (req.url === 'https://firstApiCall') {
        req.continue( res => {
          sessionVal = res.headers['set-cookie'][0].split(';')[0];
        });
      } else {
        req.headers['cookie'] += ';' + sessionVal;
      }
    });

The above code should intercept all apis with some path 'path' , and take the session cookie in sessionVal variable from first api call 'https://firstApiCall' and append it to subsequent api calls request headers, but the cookie is not being set.

### Cypress Version

8.4.0

**Comment by AtofStryker** [comment]
Hi @Gouravroy7. would you be able to provide a reproduction repository? If this is a cross-origin navigation + subsequent requests, session cookies should be correctly set now with `cy.origin` and the `experimentalSessionAndOrigin` flag enabled. I am going to close as this should be fixed, but if not let us know and we can reopen!
