### ISSUE TITLE
Overwriting cy.get breaks cy.contains

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#18567]
### Current behavior

`cy.contains` always yields a single element, but this changes when overwriting the `cy.get` command. Below is how I've done that, inspired by https://glebbahmutov.com/blog/writing-custom-cypress-command/ and https://github.com/Lakitna/cypress-commands/blob/develop/src/then.js. The code doesn't attempt to augment the behavior of `cy.get`, it simply overwrites it and calls the original function.

```js
Cypress.Commands.overwrite("get", (originalFn, ...options) => {
  const getValue = () => {
    return originalFn(...options);
  };

  const resolveValue = () => {
    return getValue().then((value) => {
      return cy.verifyUpcomingAssertions(value, options, {
        onRetry: resolveValue
      });
    });
  };

  return resolveValue();
});
```

### Desired behavior

I don't know if this is unintended behavior, because `verifyUpcomingAssertions` is somewhat undocumented. Furthermore, I've [found that](https://github.com/cypress-io/cypress/issues/7267#issuecomment-627124815)

> Overwrite should always return the originalFn

.. which neither I nor Lakitna/cypress-commands does. However it would obviously be nice if the above overwrite example worked.

### Test code to reproduce

A repository reproducing the issue can be found [here](https://github.com/badeball/reproducible-issues/tree/master/cypress/overwrite-cy-get). The test fail, but will pass upon commenting out the overwrite.

### Cypress Version

8.6.0

**Comment by mccataldo** [comment]
@badeball In my case I just created an escape hatch in the case where `cy.get` was called in a contains using `cy.state().current.attributes.name === 'contains'`. Not sure what you're trying to do so YMMV.

**Comment by Lagluck07** [comment]
Hi,

I need to overwrite the cy.get() to add the default log = false, something like this:

Cypress.Commands.overwrite('get', (originalFn, subject, ...args) => {
    args[0] == undefined? args[0] = {log:false} : args[0].log = false
    cy.wrap(subject).highlight().then(() => originalFn(subject, ...args))
})

Is it possible?

**Comment by Lagluck07** [comment]
> Hi,
> 
> I need to overwrite the cy.get() to add the default log = false, something like this:
> 
> Cypress.Commands.overwrite('get', (originalFn, subject, ...args) => { args[0] == undefined? args[0] = {log:false} : args[0].log = false cy.wrap(subject).highlight().then(() => originalFn(subject, ...args)) })
> 
> Is it possible?


Hi all, 


Replying my question above : 

I guess isn´t  the best way to do, but for me it´s working:

Cypress.Commands.overwrite('get', (originalFn, ...args) => {
    args[1] == undefined? args[1] = {log:false} : args[1].log = false
    return originalFn(...args)
})
