### ISSUE TITLE
Add cli commands for managing binary cache

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1856]
- `cypress cache clear`: clears ~/.cache/Cypress/*
- ~`cypress cache trim`~
- `cypress cache folder`: logs `~/.cache/Cypress`

**Comment by brian-mann** [comment]
`cypress cache open`: opens finder/explorer to the folder

**Comment by jennifer-shehane** [comment]
Hey @Bkucera, can you add docs for these new commands?

**Comment by Bkucera** [comment]
:+1:

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
