### ISSUE TITLE
Cypress support for mitt

### ISSUE THREAD

**Issue by gitSwaroop** [cypress-io/cypress#18580]
### Current behavior

Hi Team,

I have used mitt for my project and I have used micro frontend
I am emitting event from one micro frontend app to other which is working fine.
I am writing test cases by using cypress library I am not able to mock event in cypress integration test.
https://github.com/developit/mitt

### Test code to reproduce

Not facing any error hut I am not getting data in console not able to write test cases based on data

### Cypress Version

8.5.0

**Comment by marcodu** [comment]
I'm interested spy on events emitted with mitt
Does anybody knows how to do this ?
I've seen how to mock an event, but not how to spy on an emitted event.
