### ISSUE TITLE
Ability to add a message to stdout during cypress run

### ISSUE THREAD

**Issue by jasonLaster** [cypress-io/cypress#186]
It would be great to have a cypress function that helps me debug failing ci tests by adding logs that print to the stdout

**Comment by jennifer-mann** [comment]
A way to see console.log is currently being worked on. Please leave any feedback on this issue: #448

**Comment by david-golightly-leapyear** [comment]
Any updates on this? in particular, for headless mode...

**Comment by jennifer-shehane** [comment]
There are a couple of plugins that allow you to log console logs to stdout output:

- https://github.com/flotwig/cypress-log-to-output
- https://github.com/archfz/cypress-terminal-report

More generally, you can now log messages to stdout through Cypress by using [`cy.task()`](https://on.cypress.io/task) like shown below:

`spec.js`

```js
it('logging', () => {
  cy.task('log', 'This message shows in stdout')
})
```

`plugins/index.js`

```js
module.exports = (on, config) => {
  on('task', {
    log(message) {
      console.log(message)

      return null
    }
  })
}
```

<img width="815" alt="Screen Shot 2020-06-10 at 2 53 41 PM" src="https://user-images.githubusercontent.com/1271364/84244963-659d3880-ab2a-11ea-9f98-7661342d967b.png">

**Comment by OmarSlame** [comment]
after following steps for cypress-log-to-output, the logs doesnt appear in stdout 
the difference i got it when type in command line npx cypress run the browser pop up and run same as when write npx cypress open.
and this is not what you are promis @jennifer-shehane

**Comment by jennifer-shehane** [comment]
@OmarSlame Please open a new issue with a completely reproducible example where it is not logging to stdout.

**Comment by patcon** [comment]
I tried https://github.com/archfz/cypress-terminal-report (and am super-grateful for the hot tip, @jennifer-shehane!), but logs didn't show up for passing tests until I modified: https://github.com/archfz/cypress-terminal-report#optionsprintlogs

(The default is to only log to terminal on failure.)

Thanks so much for the advice! This is very helpful to debugging issues in continuous integration environments like GitHub Actions <3

**Comment by Dicee** [comment]
Is there any known solution for logging within asynchronous functions? I happen to have a lot of AWS SDK calls in my tests, and I came up with the following pattern:

```typescript
export function cyasync<T>(alias: string, promise: () => Promise<T>, timeout?: Duration): Chainable<T> {
    const options = timeout ? { timeout: timeout.toMillis() } : {}
    return cy
        .wrap(null)
        .as(alias)
        .then(options, async () => await runAsync(alias, promise))
        .then((result) =>
            Async.flushLogs().then(() => {
                if (isError(result)) throw result
                return cy.wrap(result)
            }),
        )
}

// we get out of asynchronous execution without throwing so that we can flush logs to stdout via a Cypress command
// (incompatible with async execution). We can then rethrow at this point.
async function runAsync<T>(alias: string, promise: () => Promise<T>): Promise<Result<T>> {
    try {
        Async.log(`Running async task "${alias}"`)

        const start = Instant.now()
        const result = await promise()
        const duration = Duration.between(start, Instant.now())

        Async.log(`Successfully executed task "${alias}" in ${duration}`)
        return result
    } catch (e) {
        const message = `Failed "${alias}" due to ${Logger.formatError(e)}`
        Async.log(message, Level.ERROR)
        return new Error(message)
    }
}

type Result<T> = T | Error
function isError<T>(result: Result<T>): result is Error {
    return result instanceof Error
}
```

This allows me to treat async portions of the code in a safe manner regarding Cypress queuing mechanism. However, I can't call `cy.task` from within an async/await method, or hell will ensue like every time (mix of Cypress commands and Promise). Thus, I had to use `Async.log`, which accumulates logs in memory, and is then flushed using `Async.flush` after each test suite, using `cy.task` to go to stdout. It works, but a bit crafty... `cypress-terminal-report` did not help with that, it logs what my website logs in the browser, but somehow omits the logs I add as part of the tests. Finally, `cypress-log-to-output` doesn't support Electron.

Thus, the above really is the best option I found so far, and it takes quite a bit of custom code and thought process to get there.

Appreciate any suggestion :)

**Comment by rakeshnambiar** [comment]
@jennifer-shehane appreciate it if you could update your solution for the latest Cypres file structure. Thanks in advance.

**Comment by anilpujaraofficial** [comment]
![Screenshot from 2023-10-02 15-30-38](https://github.com/cypress-io/cypress/assets/65593381/dc3b83f3-1140-41fa-b2bc-210f70b2ebe0)
how can solve this issue

@jasonLaster

**Comment by MikeMcC399** [comment]
@anilpujaraofficial 

The same comment applies here.

Your report is:

1. unrelated to the issue you have attached it to
2. related to the npm module https://www.npmjs.com/package/cypress-cloud which is not supported here
