### ISSUE TITLE
cy.intercept is not recognized as a function

### ISSUE THREAD

**Issue by Danoolo** [cypress-io/cypress#18608]
### Current behavior

Hey guys, i was working with Cypress for a while and got good result testing my angular app. As i was working with the last version of Cypress i could use cy.intercept for mocking responses. The next step was installed @cypress/code-coverage for analysing code coverage, so after installed all dependencies i got this error on browser console
![Screenshot from 2021-10-22 10-39-30](https://user-images.githubusercontent.com/30710193/138483045-62a561c3-1f19-4f59-941f-6e439d975ddf.png)
Not using cy.intercept everything was fine but a good feature of cypress is mocking responses, and go back to cy.route is not an option. The question (and sorry if this is not the place for asking this question) is, how could i overcome this issue ? do i have to use another version of code-coverage?. 
For using code coverage and instrument my project i used this tutorial https://lukas-klement.medium.com/implementing-code-coverage-with-angular-and-cypress-6ed08ed7e617
Thanks all guys for this incredible tool!

### Desired behavior

-

### Test code to reproduce

-

### Cypress Version

8.2.0

### Other

-

**Comment by sainthkh** [comment]
Sorry for the late reply.

Can you please check the version of your Cypress? It might be not over 6.0.0.

I'm not sure when the interface changed. But the error message interface shows that it's not the recent version.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
