### ISSUE TITLE
Document the available plugin events in the scaffold file

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1861]
Currently the scaffolded file looks like this...

```js
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}
```

I think this puts too much emphasis on "turning off this file" - there's not really even a use case of that, and instead we should maybe list out the available plugin events.

The only problem I see with this is that when this file is scaffolded - it's scaffolded based on the current version of Cypress. As users upgrade Cypress we may release new plugin events but they won't be listed into the commented out code.

**Comment by jennifer-shehane** [comment]
File can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/scaffold/plugins/index.js

**Comment by wildaces215** [comment]
Is this open?

**Comment by jennifer-shehane** [comment]
@wildaces215 Yes, no work has been done on this.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
