### ISSUE TITLE
Cypress tests fail to run after upgrading to Chrome 95

### ISSUE THREAD

**Issue by JourneymanTester** [cypress-io/cypress#18627]
### Current behavior

After Chrome 95 was released, our Cypress tests fail to run, apparently because Cypress is unable to communicate with Chrome.

`cypress run --browser chrome --headless`

produces the following log entries:

`Failed to connect to Chrome, retrying in 1 second (attempt 18/62)`
...
`2021-10-25T17:19:47.931Z cypress:launcher launching browser { browser: { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', version: '95.0.4638.54', path: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', minSupportedVersion: 64, majorVersion: 95, isHeadless: true, isHeaded: false }, url: 'about:blank' }`

`2021-10-25T17:19:47.932Z cypress:launcher spawning browser with args { args: [ 'about:blank', '--test-type', '--ignore-certificate-errors', '--start-maximized', '--silent-debugger-extension-api', '--no-default-browser-check', '--no-first-run', '--noerrdialogs', '--enable-fixed-layout', '--disable-popup-blocking', '--disable-password-generation', '--disable-single-click-autofill', '--disable-prompt-on-repos', '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-renderer-throttling', '--disable-backgrounding-occluded-windows', '--disable-restore-session-state', '--disable-new-profile-management', '--disable-new-avatar-menu', '--allow-insecure-localhost', '--reduce-security-for-testing', '--enable-automation', '--disable-print-preview', '--disable-device-discovery-notifications', '--autoplay-policy=no-user-gesture-required', '--disable-site-isolation-trials', '--metrics-recording-only', '--disable-prompt-on-repost', '--disable-hang-monitor', '--disable-sync', '--disable-web-resources', '--safebrowsing-disable-download-protection', '--disable-client-side-phishing-detection', '--disable-component-update', "--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'", '--disable-default-apps', '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--disable-ipc-flooding-protection', '--disable-backgrounding-occluded-window', '--disable-breakpad', '--password-store=basic', '--use-mock-keychain', '--disable-dev-shm-usage', '--proxy-server=http://localhost:49907', '--proxy-bypass-list=<-loopback>', '--headless', '--window-size=1280,720', '--force-device-scale-factor=1', '--remote-debugging-port=49912', '--remote-debugging-address=127.0.0.1', '--user-data-dir=C:\\Users\\BUILDLABTESTNKLBBFZC\\AppData\\Roaming\\Cypress\\cy\\production\\browsers\\chrome-stable\\run-4712', '--disk-cache-dir=C:\\Users\\BUILDLABTESTNKLBBFZC\\AppData\\Roaming\\Cypress\\cy\\production\\browsers\\chrome-stable\\run-4712\\CypressCache' ] }`

`2021-10-25T17:19:48.041Z cypress:server:browsers:chrome connecting to Chrome remote interface at random port 49912`

`2021-10-25T17:19:48.042Z cypress:server:browsers:protocol Getting WS connection to CRI on port 49912`

`2021-10-25T17:19:49.072Z cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:49912 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 49912 } }`

`2021-10-25T17:19:49.165Z cypress:launcher chrome stderr: [1025/121949.167:ERROR:network_service_instance_impl.cc(474)] Failed to grant sandbox access to cache directory C:\Users\BUILDLABTESTNKLBBFZC\AppData\Roaming\Cypress\cy\production\browsers\chrome-stable\run-4712\CypressCache: The specified procedure could not be found. (0x7F)`

`2021-10-25T17:19:49.572Z cypress:launcher chrome exited: { code: 3221225477, signal: null }`

`2021-10-25T17:19:50.197Z cypress:network:connect received error on connect, retrying { iteration: 1, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:49912 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 49912 } }`

`2021-10-25T17:19:51.337Z cypress:network:connect received error on connect, retrying { iteration: 2, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:49912 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 49912 } }`

`2021-10-25T17:19:52.459Z cypress:network:connect received error on connect, retrying { iteration: 3, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:49912 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 49912 } }`

### Test code to reproduce

No code to reproduce.

### Cypress Version

8.6.0

**Comment by xecrets** [comment]
The issue was caused by something in Chrome 95, and was subsequently fixed in Chrome 96 and later versions. The issue can be closed.
