### ISSUE TITLE
Improve image duplicate checking performance

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1863]
When checking whether or not the browser has painted new pixels during `cy.screenshot` we are comparing hashes of the images. This is super slow. Instead we can simply compare the raw data buffers to see if they are equal. This reduces almost `500ms` of CPU calculations.

**Comment by bahmutov** [comment]
Is this to detect just control pixels? Then we can compare just a subset of pixels directly and that will be very fast if we avoid Re computing the index

**Comment by brian-mann** [comment]
I'm just opening an issue to track the changes. I've already done this. Comparing the raw data buffers is a less than 1ms operation. It ensures it's 100% identical, which is what we need when knowing whether or not the browser has rendered yet.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
