### ISSUE TITLE
Audio commands during web automaton are not working in latest cypress version 8.4

### ISSUE THREAD

**Issue by ganeshac123** [cypress-io/cypress#18633]
### Current behavior

Audio commands during web automaton are not working in latest cypress version 8.4. However audio commands are working in older cypress version 4.1.

### Desired behavior

Audio commands during web automaton should be working in latest cypress version 8.4.

### Test code to reproduce

import { USER, USER_PERSONA } from '../../support/constants'
const HIST_SECT = 'History'.replace(/\W/g, '-').toLowerCase()
const PE_SECT = 'Physical Exam'.replace(/\W/g, '-').toLowerCase()

describe('Schudule Patients Voice tests', function () {
  
  it('cy.get() - Login to Suki as a Physician', function () {
    // Login as physician
    cy.login(USER_PERSONA.USER)
        .playAudioURL('https://storage.googleapis.com/audiofiles-e2e/SHOW_SCHEDULE.mp3', 20000)
        
  })
})

### Cypress Version

8.4

**Comment by sainthkh** [comment]
Sorry for the late reply.

`playAudioURL` is a custom API and we cannot research what went wrong without a working example. 

Maybe some code in the command might contain some functions under [the breaking changes list](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-8-0).

**Comment by ganeshac123** [comment]
describe('Schudule Patients Voice tests', function () {
  
  it('cy.get() - Login as user', function () {
   
    cy.login(USER_PERSONA.USER)
        .playAudioURL('https://storage.googleapis.com/audiofiles-e2e/SHOW_SCHEDULE.mp3', 20000)
        
  })
})

**Comment by ganeshac123** [comment]
@sainthkh Above is working example

**Comment by BlueWinds** [comment]
> @sainthkh Above is working example

As sainthkh said, `playAudioURL` is not part of the core Cypress code. It might be a custom command you have added in your project, or it might be provided by a community plugin you've installed - either way, your example does not work **standalone** - it has dependencies you don't mention and we can't reproduce the issue without knowing what those are..

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by ganeshac123** [comment]
@sainthkh playAudioURL is working as expected it doesn't have any issue, problem is with Cypress it is not working consistently for voice commands.

**Comment by sainthkh** [comment]
@ganeshac123 If you want to reopen this issue, can you do the following for us?

1. Open the problematic project that has the test code above.
2. Search `playAudioURL`. 
3. Find the definition of `playAudioURL` in the project. 
4. Copy that code into a minimal Cypress project. ([this](https://github.com/cypress-io/cypress-test-tiny) might be a good starting point.)
5. Reproduce the problem with `playAudioURL` in that project. 
6. Share the project in the comment below.

As we all know, every debugging starts with reproducing it on the developer's machine. `playAudioURL` is NOT Cypress's bundled API. Someone in your team or some plugins you're using has added that to the project. 

Without knowing what's going on inside that command, no Cypress developer can help you solve the problem.

**Comment by ganeshac123** [comment]
Cypress.Commands.add('playAudioURL', (url, delay) => {

  const evt = new CustomEvent('new-audio', { detail: url })
  cy.get('[data-cy=audio-player]').then(($apNode) => {
    $apNode[0].dispatchEvent(evt)
  })
    .wait(delay)
})

**Comment by ganeshac123** [comment]
@sainthkh Above is code in which playAudioURL is defined..

As I told you before looks like it is cypress issue, as playAudioURL is working for andriod devices when we use Appium.

**Comment by ganeshac123** [comment]
@sainthkh Can we get on call if possible that would be easy to discuss the problem.

**Comment by sainthkh** [comment]
I failed to reproduce the problem with the code below:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Document</title>
</head>
<body>
  <div id="audio-player"></div>
  <div id="result"></div>
</body>
<script>
  const player = document.getElementById('audio-player');
  const result = document.getElementById('result');

  player.addEventListener('new-audio', () => {
    result.innerHTML = 'new-audio sent';
  })
</script>
</html>
```

```js
it('t', () => {
  cy.visit('fixtures/a.html')

  cy.get('#audio-player').then(($audio) => {
    $audio[0].dispatchEvent(new CustomEvent('new-audio', { detial: 'asdf' }))
  }).wait(100)

  cy.get('#result').should('have.text', 'new-audio sent')
})
```

We need more information about `audio-player` code.

**Comment by ganeshac123** [comment]
@sainthkh I am going send to full repository to you, please take a took at the issue.

**Comment by ganeshac123** [comment]
@sainthkh https://drive.google.com/drive/folders/1x9DUNVop3hq3n2klWKD8cFswY8oICO3H?usp=sharing
above link, repository is kept please download and run any file in integration folder you will see issue.

**Comment by sainthkh** [comment]
Unfortunately, I'm unable to visit the admin page. There's an error message like this below:

![image](https://user-images.githubusercontent.com/8130013/155633874-28c401ea-dc90-4b36-86a6-c0292926d1df.png)

I used Cypress 4.4.1.

Note: Your Cypress Key is revealed in the shared project.

**Comment by ganeshac123** [comment]
@sainthkh Please run any other test in physician folder, especially Copyforword, undodelete files.

For your information voice commands working fine in the 4.4.4 but not working in recent versions.

**Comment by sainthkh** [comment]
I've run undo-delete.spec.js with 9.5.0. But it was working without fail like below:

![Peek 2022-02-25 16-04](https://user-images.githubusercontent.com/8130013/155670210-f8a0e9bf-3662-4128-9c79-bbd7b613c9d4.gif)

**Comment by ganeshac123** [comment]
@sainthkh Issue is Cypress it is not playing audio,  you can see the audio is being played their but it is not entering into to the note.

**Comment by sainthkh** [comment]
I've run copyforword with 4.4.1 and 9.5.0. They both failed at the same point. 

### 4.4.1

![Peek 2022-02-25 16-12](https://user-images.githubusercontent.com/8130013/155671612-3a15fb7a-078b-4b0e-acdf-efc27d03d0e6.gif)


### 9.5.0

![Peek 2022-02-25 16-15](https://user-images.githubusercontent.com/8130013/155671704-8bf10183-269c-436f-b7f4-8efcb528f822.gif)

**Comment by ganeshac123** [comment]
How did you opened 9.5.0 through Cypress dashboard or through npm(command line)?

**Comment by sainthkh** [comment]
`npm run cypress:open`

**Comment by ganeshac123** [comment]
Actually it is working in 4.4.1, don't know why it is not working for you.
