### ISSUE TITLE
keep failure case request in memory for fault check

### ISSUE THREAD

**Issue by xchnshi** [cypress-io/cypress#18632]
### What would you like?

if 'numTestsKeptInMemory'  not set in cypress.json, the cases could be interrupted by 'Out of Memory', but if set to 0 or a number, the OOM still could happen.
Is it possible to settle an option like 'numTestsKeptInMemory' wow to only keep failure requests in memory, then it will be easy to find why it failed with the request data recorded.

### Why is this needed?

An option configure in cypress.json to tell cypress only keep failure case requests saved in memory.

**Comment by hawkpatrick** [comment]
We'd love to see this feature, too.
