### ISSUE TITLE
Allow for caps lock to be activated

### ISSUE THREAD

**Issue by AlexanderAntov** [cypress-io/cypress#18659]
### What would you like?

I would like to be able to activate caps lock via Cypress. This could possibly be implemented in a similar way as the [other type modifiers](https://docs.cypress.io/api/commands/type#Arguments).

### Why is this needed?

There are use cases in which this would be useful, for example caps lock detection warnings. In javascript code, activating the caps lock should be treated as a modifier state on the key events. For example:

```js
input.addEventListener("keyup", function(event) {
  if (event.getModifierState("CapsLock")) {
    //show warning
  } else {
    //make sure warning is hidden
  }
});
```

**Comment by windmaomao** [comment]
Currently the following code wouldn't work, because it says `capslock` isn't supported.

```
    cy.get('input')
      .type('{capslock}')
      .then(() => {
        // cy.get('input').contains('ON');
      });
```

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
