### ISSUE TITLE
Electron video not playable in Firefox browser since Cypress 8.6.0/8.7.0

### ISSUE THREAD

**Issue by jweingarten** [cypress-io/cypress#18667]
### Current behavior

https://github.com/cypress-io/cypress/issues/18503 is supposed to be fixed with 8.7..0. We are still seeing this issue. 

* We are running  `Cypress 8.7.0 is installed in /root/.cache/Cypress/8.7.0`
* Tests run against Electron on Rhel 7.7

This works on 8.5.0 ... or use Chrome to play the video...

https://user-images.githubusercontent.com/2966099/139135395-c01b2d32-ea60-4236-9c6a-9cad53b64779.mp4

The attached video, recorded from one of our tests, plays fine if I open it from a Chrome browser (File | Open), but Quicktime or Firefox does not play the video. 

### Desired behavior

Video should play in a Firefox browser and Mac QuickTime

### Test code to reproduce

* Run tests on Cypress 8.7.0, Electron, Rhel 7.7. 

### Cypress Version

8.7.0

**Comment by lioncedric** [comment]
Same issue for me with cypress 9.3.1 
tried on both windows and Linux (docker image)
The electron recording is not playable on Firefox
(everything worked ok with 8.5.0)
