### ISSUE TITLE
Stubbing methods doesn't work

### ISSUE THREAD

**Issue by p-christ** [cypress-io/cypress#18662]
### Current behavior

My component is as follows

```js
import {myMethod} from "./myFile"

function MyComponent(){
   const output = myMethod();

   return <div>{output}</div>    
}
```

And i am stubbing myMethod because I want it to return a specific value like so

```js
import * as Parent from "./myFile"
cy.stub(Parent, "myMethod", () => "i was stubbed")

cy.visit("/my_component")  # Does not use the stubbed function 
```

but then i am finding that the component still uses the original function and not the stubbed function, does anyone know what i am doing wrong?

### Test code to reproduce

```js
# Component file
import {myMethod} from "./myFile"

function MyComponent(){
   const output = myMethod();

   return <div>{output}</div>    
}
```

```js
# Test file
import * as Parent from "./myFile"
cy.stub(Parent, "myMethod", () => "i was stubbed")

cy.visit("/my_component")  # Does not use the stubbed function 
```

### Cypress Version

8.7.0

**Comment by FelipeLahti** [comment]
This is great @web-bert
It worked for me. Thanks!

**Comment by rbecheras** [comment]
Thanks, it worked for me too ! 

However, IMHO it requires a fix for `open-ct` don't you think ?

**Comment by muratkeremozcan** [comment]
Stubbing modules isn't working in the component runner. The same thing is ok in the e2e runner. Wait for Cy 10 or work around it like the above...

![image](https://user-images.githubusercontent.com/34237651/159122184-9077e98c-52dd-4c8b-b8c8-a0108ecb3462.png)

**Comment by radikris** [comment]
My question is connected to this issue: If anyone can checkout my issue, would appreciate it:

https://stackoverflow.com/questions/72161856/vue-js-how-to-stub-mock-http-request-in-cypress-component-test

**Comment by muratkeremozcan** [comment]
> My question is connected to this issue: If anyone can checkout my issue, would appreciate it:
> 
> https://stackoverflow.com/questions/72161856/vue-js-how-to-stub-mock-http-request-in-cypress-component-test

https://github.com/muratkeremozcan/multi-stage-caching/tree/master/cypress/component/network

**Comment by muratkeremozcan** [comment]
There is a solution to this. In short, we need to add `@babel/plugin-transform-modules-commonjs` and and customize webpack config, so that we can makes all imports accessible from any file including specs.

https://glebbahmutov.com/blog/stub-react-import/index.html#stub-the-import

Here's how I applied it to enable LaunchDarkly feature flag  mocked Cypress component tests.
https://github.com/muratkeremozcan/react-hooks-in-action-with-cypress/pull/175/files

**Comment by danielbucher** [comment]
I'm having the same issue on a gatsby application when trying to use stubs on e2e tests. I even tested with the same methods as the example from [Gleb Bahmutov](https://glebbahmutov.com/blog/stub-react-import/index.html#stub-the-import). I created a `getLocation` function:

```
// utils/location.ts
export const getLocation = () => {
  const { hostname, pathname } = window.location
  return { hostname, pathname }
}
```

And used it on a component (just console.logging the values returned by it to be honest). On the test, I'm doing:
```
cy.stub(Location, 'getLocation').returns({
      hostname: 'cy-test',
      pathname: '/App',
    })
```

but I don't get these values back on the console. `tsconfig` is as follows:

```
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": "./",
    "module": "commonjs",
    "target": "esnext",
    "jsx": "preserve",
    "lib": ["dom", "esnext"],
    "strict": true,
    "noEmit": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "noUnusedLocals": false,
    "resolveJsonModule": true,
    "allowJs": true
  },
  "exclude": [
    "node_modules",
    "public",
    ".cache",
    "./cypress",
    "./cypress.config.ts"
  ]
}
```

with a different `tsconfig` for cypress:

```
//cypres/tsconfig.json
{
  "include": [
    "e2e/**/*",
    "support/**/*",
    "utils/**/*",
    "fixtures/**/*",
    "../node_modules/cypress",
    "../node_modules/@testing-library/cypress"
  ],
  "compilerOptions": {
    "baseUrl": ".",
    "noEmit": true,
    "types": ["node", "cypress", "@testing-library/cypress"],
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "target": "es2019",
    "strict": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "typeRoots": ["../types", "../node_modules/@types"]
  }
}
```

`webpack-config` is just:

```
const path = require('path')

module.exports = {
  resolve: {
    modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    alias: {
      data: path.resolve(__dirname, 'data'),
      static: path.resolve(__dirname, 'static'),
    },
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    fallback: {
      util: require.resolve('util'), // Required fallback fills for twilio
      events: require.resolve('events'), // Required fallback fills for twilio
    },
  },
  module: {
    rules: [
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader',
      },
    ],
  },
}
```

What am I missing? Why can't I use `cy.stub` properly?
