### ISSUE TITLE
Make Slider Interaction More Intuitive

### ISSUE THREAD

**Issue by nalandial** [cypress-io/cypress#18664]
### What would you like?

Easily interact with slider components and set their values directly.

### Why is this needed?

Right now interacting with sliders is not intuitive. Triggering a mousedown and mousemove event is possible but does not allow selection of precise values especially with a responsive UI.

The other option that worked for me was to set the value directly and manually trigger an `input` event, but it feels like a hack and took quite a bit of time to figure out.

### Other

This is what I had to do to get it to work for me in React:

```html
<input type="slider" data-testid="foo" min="0" max="100" value={sliderValue} onInput={...} />
<span data-testid="bar">{sliderValue}</span>
```
```js

cy.get('[data-testid=foo]')
  .invoke('val', '123')
  .trigger('input')

cy.get('[data-testid=bar]').should('have.text', '123')
```

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
