### ISSUE TITLE
Cypress 'Refused to frame' issue 

### ISSUE THREAD

**Issue by pelinoloji** [cypress-io/cypress#18669]
### Current behavior

I'm using Cypress to run end-to-end tests on an our application. All test were good but we have a feature and with this feature user integrate their bank account via then they're landing our page and we're showing some extra stuff and it continues. Until bank integration, everything is fine. When it comes to integration I'm sending user via link to external provider, then I've got an error.  

`Redirected to chrome-error://chromewebdata/`
`Refused to frame 'https://login.truelayer.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://somelink.github.io".`

on config file `"chromeWebSecurity": false`

**What I tried?**
- `csp.js` I updated  `'frame-ancestors'` it didn't work. 
- Downloaded [this](https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe)  didn't work. 

Is there any way that I can tackle this? 

### Desired behavior

Ideally it should open the page.

### Test code to reproduce

cy.visit('https://www.somelink.com')
cy.request('https://www.somelink.com')

### Cypress Version

5.6.0

**Comment by BlueWinds** [comment]
I'm sorry we never got back to you. Cypress 5.6.0 is quite old at this point, and we don't generally support anything beyond the most recent version; if you're still having problems, please open a new issue on the latest version and we'll try not to let it languish this time.
