### ISSUE TITLE
Send key F3 without input

### ISSUE THREAD

**Issue by rccclr** [cypress-io/cypress#1867]
I am newbie on cypress.

I need write a  test with F3 send key to page.

I wrote this (114 = charcode key for F3):

```js
cy.get('body').type('{114}')  // (not ok) 
cy.get('body').type('{{114}') // (not ok)
```

Pease help

**Comment by jennifer-shehane** [comment]
The only special characters built in to Cypress are listed in the docs [here](https://on.cypress.io/type#Arguments). There is not a special character for `{114}`.

You should be able to trigger the `keydown` event with the character code needed for F3 using [`.trigger()`](https://on.cypress.io/trigger) like this:

```js
cy.get('body').trigger('keydown', { keyCode: 114, which: 114 })
``` 

Let me know if this works.

**Comment by rccclr** [comment]
Perfect !!!

Many many thanks.

**Comment by peetjvv** [comment]
I recently ran into a similar issue and came across this thread. In my case I had to trigger a Backspace. Unfortunately @jennifer-shehane 's suggestion didn't work. I later learned that keyCode is deprecated in KeyboardEvent, but using key worked for me.

Here is my code:

```cy.get('body').trigger("keydown", { key: "Backspace" });```

**Comment by muscapades** [comment]
With the current version 3.4.1, to simulate a function key press I had to do 
 
`cy.get('body').trigger('keydown', { key: "F8", code: "F8", which: 119 })`

(using https://keycode.info/ as a handy way to find the relevant values for any given key).

**Comment by dte** [comment]
For anyone else finding this thread, I had to add the full `keydown`, `keypress` and `keyup` events as specified here: https://stackoverflow.com/a/56854185

**Comment by skivol** [comment]
For typing special characters built into Cypress without focus into some specific input one can do, for example, like this `cy.get('body').type('{esc}', { force: true })`.

**Comment by Todsphol** [comment]
> For typing special characters built into Cypress without focus into some specific input one can do, for example, like this `cy.get('body').type('{esc}', { force: true })`.

It work for me. I use cypress version 3.8.2 but have to loop to click 2 times
```
for (let i = 0; i < 2; i++) {
     cy.get('modal-container').type('{esc}', { force: true});
}
```

**Comment by TimmyDDthe1st** [comment]
So this way worked with a React app, but a PixiJS app doesn't receive the event at all, it just times out...
<img width="473" alt="Screenshot 2020-12-01 at 14 51 47" src="https://user-images.githubusercontent.com/58341411/100756168-ddb32f80-33e4-11eb-9c51-1de221907d19.png">
Force true, sends the event, but then my PixiJS App doesn't seem to get the event 🤔

**Comment by pakhilov** [comment]
https://github.com/dmtrKovalenko/cypress-real-events#cyrealpress
Try to use this library

**Comment by guoyupeng01** [comment]
> https://github.com/dmtrKovalenko/cypress-real-events#cyrealpress
> Try to use this library

hi，Is this method supported cy.realPress ('Esc')

![image](https://user-images.githubusercontent.com/32129782/110891376-d5945580-832c-11eb-8920-4206d7354b7c.png)

**Comment by pakhilov** [comment]
'Escape'

**Comment by guoyupeng01** [comment]
> Escape

Thanks for your reply, I tried to close the pop-up box through the Escape method, but after the pop-up window came out, Cypress kept waiting for the pop-up box to close before continuing. How can I close the print window? 

![image](https://user-images.githubusercontent.com/32129782/110900181-4fccd600-833d-11eb-9b61-5c0ad761565c.png)

**Comment by mikhail-g** [comment]
In my test i needed to type F2 and those commands worked
```
cy.get('body).trigger('keydown', {eventConstructor: 'KeyboardEvent', code: 'F2'})
cy.get('body).trigger('keyup', {eventConstructor: 'KeyboardEvent', code: 'F2'})
```
