### ISSUE TITLE
Cypress bar disappeared during a test

### ISSUE THREAD

**Issue by refael-nagosa** [cypress-io/cypress#18680]
### Current behavior

Hi,
I ran a test that goes between domains. When the test reached the second domain the cypress window disappeared (pic 3) and although the test supposedly continues to run behind the screen (pic 4), nothing seems to be happening.
This is not the first test I wrote that goes between domains, and for that I disabled the web security, so I guess that's not the issue. 
pic 1- cypress ran properly in the default domain
pic 2 - the moment that passes between the domains
pic 3 - cypress bar disappear in the second domain
pic 4 - once the window is gone, the test still appears to be runnin

<img width="1187" alt="1" src="https://user-images.githubusercontent.com/68903860/139247473-e48e2c4d-7f7c-484b-b7ef-743189433048.png">
<img width="1186" alt="2" src="https://user-images.githubusercontent.com/68903860/139247491-2fd3b3e1-c536-4de7-86c3-ddc865e1b1eb.png">
<img width="1187" alt="3" src="https://user-images.githubusercontent.com/68903860/139247494-580523b1-98c4-461c-bd3c-98251522a228.png">
<img width="1322" alt="4" src="https://user-images.githubusercontent.com/68903860/139247968-a5a0091e-9be7-4582-8583-d57d44e5c38c.png">

### Desired behavior

Keep running after moving to the second domain.

### Test code to reproduce

describe('Login with Azure', () => {

	beforeEach ( () => {
		cy.visit('/');        
	});
	it.only('Login positive azure', function () {
		cy.wait(500);
		cy.get('button.sso-log-in-button').click();   // login with sso
		cy.wait(500);
		cy.get('input[id="userid"]').type(azureuser);    //enter user name
		cy.wait(500);
		cy.get('button[type="submit"]:not([disabled])').click();    //click next - should be transferred to Azure domain
		cy.wait(2000);

		//cy.url().should('include', 'https://login.microsoftonline.com/');
		cy.get('[name="loginfmt]').type(azureuser);              // enter user name on azure
		cy.get('[id="SIButton9"]').click();                      // click next
		cy.get('[type="password"]').type(password);              // enter password on azure
		cy.wait(500);
		cy.get('[id="SIButton9"]').click();                      // click login

		cy.url().should('include', 'https://app.vonage.com/');
	});	
});

### Cypress Version

7.6.0

**Comment by mikhailhathey** [comment]
I'm also experiencing this with Azure B2C Login, I've tried with Origin and Session but still get the same issue constantly.

**Comment by shinu-ajayakumar** [comment]
I also faced same issue for B2C login, couldn't find a solution for the same

**Comment by hello202222** [comment]
it is a shame that this issue is reported many times but cypress did not admit this is issue. for certain applications cypress preview window disappear. I need to switch to otjer test automation tool just like other reporters did as cypress is unable to provide a solution for this
