### ISSUE TITLE
cy.type() failed because the center ot this element is hidden from view. Tried scrollTo() and scrollIntoView(). 

### ISSUE THREAD

**Issue by snake-py** [cypress-io/cypress#18697]
### Current behavior

Interesting to note is that if I go through the history, cypress does indeed scroll to the element. But it does not recognize it.  

The input for the password fails.

### Desired behavior

Cypress interactive view should scroll to the element. 

### Test code to reproduce

```JavaScript

function login(username, password) {
    cy.visit('/');
    // cy.window().scrollTo(0, 200); \\ try to manual scroll did not help 
    cy.get('[data-test=username]', { timeout: 10000 }).type(Cypress.env('CY_LOGIN_USERNAME'));
    cy.get('[data-test=password]', { timeout: 10000 }).type(Cypress.env('CY_LOGIN_PASSWORD'));
    // did also not help: 
    // cy.get('[data-test=password]', { timeout: 10000 }).scrollIntoView().type(Cypress.env('CY_LOGIN_PASSWORD'));
    cy.get('[data-test=btn-login]').click({ force: true });
}
```

### Cypress Version

unsure

### Other

cypress version did not work for me, probably because I added it with vue?  

"@vue/cli-plugin-e2e-cypress": "^4.5.13",

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by DBLaci** [comment]
Sorry I can't provide detailed reproduction. But tests working in 8.7.0 fails in 9.0.0 because scrollIntoView() simply doens't work as expected. Downgrading to 8.7.0 fixed it for me. Otherwise I should add force: true to everywhere, where scrollIntoView() was enough before.

**Comment by BlueWinds** [comment]
The scrolling behavior has changed a bit in 9.0.0. We're always looking to improve our test coverage so that our updates don't break how Cypress is used in the wild. but without an example we can run to see how it's failing we'll be hard-pressed to fix the bug you're running into.

**Comment by AnisAbidRafique** [comment]
Still getting the same issue in 2023
I think bug didn't got fixed by the support team....

**Comment by Amritanshu-Amoga** [comment]
Hi team, I am still facing this issue, can you please tell me when I can expect the resolution on this
