### ISSUE TITLE
Huge amount of uncaught exceptions: Cannot set properties of undefined (setting 'status')

### ISSUE THREAD

**Issue by juanpallares** [cypress-io/cypress#18700]
### Current behavior

When doing cy.visit() I get a huge amount of uncaught exceptions

![image](https://user-images.githubusercontent.com/35956788/139421871-b43bec8b-7e47-432c-92c1-212844c8235b.png)

I'm catching the exceptions so the cypress tests are not affected but I don't want this exceptions to happen

```
Cypress.on('uncaught:exception', (err) => {
  // returning false here prevents Cypress from
  // failing the test
  if (err.message && err.message.includes('Cannot set propert')) {
    return false;
  }
  return true;
});
```

### Desired behavior

No exceptions since it's a just a simple visit to a public webpage

### Test code to reproduce

cy.visit('https://www.vistaprint.ca/clothing-bags/t-shirts/fruit-of-the-loom-r-ink-printed-5-ounce-heavy-cotton-hd-tm-t-shirt', { timeout: 15000 })

### Cypress Version

8.7.0

**Comment by Narretz** [comment]
The exceptions are coming from the code of the site you are visiting. Cypress can't do anything about this. Or does it only happen when the site is run in Cypress?

**Comment by juanpallares** [comment]
We fixed the issue with this workaround, adding this in each test suite:

```
beforeEach(() => {
          cy.log('Blocking NewRelic scripts');
          //Will block
          //  https://js-agent.newrelic.com/nr-spa-1208.js
          cy.intercept(/\.*newrelic.*$/, (req) => {
            console.log('NEW RELIC INTERCEPTED');
            req.reply("console.log('Fake New Relic script loaded');");
          });
          cy.visitPageWithSize(url, size);
        });
```

**Comment by tsirilson** [comment]
My god @juanpallares, this happened to be my issue exactly. I have a project that loads new relic as well. Good catch!

**Comment by timdoherty** [comment]
I have the same issue, however the exception is thrown from the inline NewRelic script that in turn loads a script matching the regex in @juanpallares answer.

What's disconcerting is that running through the identical test flow manually, in the exact browser/version Cypress is using, results in zero exceptions. The exceptions are only thrown when exercising the application via Cypress
