### ISSUE TITLE
Build passes when tests have failed (Cypress screenshots are taken too)

### ISSUE THREAD

**Issue by tpbowden** [cypress-io/cypress#1870]
### Is this a Feature or Bug?

Bug

### Current behavior:

Build passes but tests fail. See screenshot:

![image](https://user-images.githubusercontent.com/1159553/40929219-04f8b5ca-681c-11e8-9d51-f02f7ab57483.png)

### Desired behavior:

Build fails when tests fail. This would be fixed by checking the number of tests run adds up to failures + success + pending. 

### Steps to reproduce:

Don't know.

### Versions

Cypress 2.1.0 in chrome on linux

**Comment by brian-mann** [comment]
Nobody has ever opened an issue regarding failures not being aggregated correctly - although in `2.1.0` we relied primarily on Mocha for determining these statuses, in `3.0.0` we now aggregate them ourselves independently of Mocha.

I'm going to close this issue as there are no steps to reproduce and likely this will show up correctly in `3.x.x`.
