### ISSUE TITLE
`cypress run` command is displayed in the documentation for `cypress open`

### ISSUE THREAD

**Issue by AndreyYevtukhov** [cypress-io/cypress#18712]
### Current behavior

`cypress run --config pageLoadTimeout=100000,watchForFileChanges=false`

---

![image](https://user-images.githubusercontent.com/14858875/139522187-4f8fae4f-64f4-4fe1-a7b4-874c465883b7.png)

### Desired behavior

`cypress open --config pageLoadTimeout=100000,watchForFileChanges=false`

### Test code to reproduce

1. Open https://docs.cypress.io/guides/guides/command-line#cypress-open-config-lt-config-gt
2. Check the link in the code block

### Cypress Version

any

**Comment by jennifer-shehane** [comment]
Closed in https://github.com/cypress-io/cypress-documentation/pull/4191
