### ISSUE TITLE
Support `cypress run --no-exit`

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1871]
Option to keep browser open after test run, useful for
- quickly finding errors that happened in CI, without having to use debugger

**Comment by jennifer-shehane** [comment]
Hey @Bkucera, can you add this new flag to our docs?

**Comment by Bkucera** [comment]
@jennifer-shehane sure

**Comment by jennifer-shehane** [comment]
I was just looking over the new docs on this and thinking. Is this flag also going to be supported when passed as an option through the [Module API](https://on.cypress.io/command-line#Cypress-Module-API)?

**Comment by Bkucera** [comment]
should be, any option passed via the Module API is passed right through the same code as the CLI

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by nwshane** [comment]
@Bkucera Can you describe how you would use the `--no-exit` flag to find/debug errors that happen in CI?

**Comment by Bkucera** [comment]
@nwshane it's nothing magical, it just allows you to keep the browser open and use see the failed commands after a failed test using `cypress run`. Otherwise the browser would just close and you wouldn't be able to inspect anything

**Comment by nwshane** [comment]
@Bkucera but how would you be able to see what's happening in the browser if it's running in CI?

**Comment by Bkucera** [comment]
@nwshane test fails in CI, you then run `cypress run --spec failed.spec.js --headed --no-exit` 
This assumes the test fails the same way in ci as it does locally

**Comment by bahmutov** [comment]
What Ben means you run the command locally hoping it fails the same way as it does on CI

**Comment by nwshane** [comment]
@bahmutov @Bkucera Okay thanks, I understand. Did you see my question about `--no-exit-on-failure` (or maybe `--pause-on-failure`)? This could allow me to run the test locally 100 times and automatically pause when the test fails - I think it'd actually be quite useful. Ideally there'd also be some sort of API for specifying what kind of failure it should pause on, in case there are multiple intermittent test failures happening (which I've experienced in my test suite).

**Comment by bahmutov** [comment]
Yes we are thinking of adding flags or even single test option to catch these intermittent failures that are so hard to debug normally one run at a time

**Comment by jennifer-shehane** [comment]
@nwshane Could you open a new issue for these flags you would like to see per failure? Thanks!

**Comment by nwshane** [comment]
@jennifer-shehane I can open a new issue for the `--pause-on-failure` flag, but thinking again, I'm not sure that it would address the problem I'm trying to fix. I'd like it to be easier to diagnose and fix intermittent cypress test failures that happen in CI. The `--pause-on-failure` flag would allow me to run tests locally many times and to see browser logs when a failure occurs, but as the local and CI testing environments are different, the CI failures might not occur locally. 

What I'd really love would be to have access to browser logs in the dashboard, i.e. https://github.com/cypress-io/cypress/issues/448

**Comment by andezzat** [comment]
I have to second this.

I have issues with flaky tests in Cypress that are very difficult to debug as they ONLY show up when running via `cypress run` and not `cypress open`. So my only solution right now is to keep doing `cypress run --headed --no-exit`, and then I have SOME chance to debug...

Even then, it's cumbersome as I would love a no exit flag ONLY on failure, this way I can repeat the commands as many times as needed knowing it'll pause when failed.
