### ISSUE TITLE
Request to add a github action 

### ISSUE THREAD

**Issue by Jassi10000-zz** [cypress-io/cypress#18722]
### What would you like?

I  would love to see  a github action in the repo to welcome the first time contributors to make the repo more interactive !!

### Why is this needed?

Since the repo is quite awesome and engaging with so many new people becoming interested in this , so to make repo more interactive I have suggested this feature

Secondly , adding a github action gives value to the repo and keeps the repo in pace with the modern style of handling repos

### Other

I want to take this opportunity 
So , can you please assign me the responsibility to add the following feature

**Comment by jennifer-shehane** [comment]
@Jassi10000 We'd love to have our repo more friendly to contributors. Can you explain exactly the behavior that our contributors would see from these changes?

**Comment by Jassi10000** [comment]
Yeah ,
something like this would be seen after one opens an issue or makes a PR
![action](https://user-images.githubusercontent.com/64856348/139689991-ce6bd0ec-fdb8-4d32-bb0c-a0ced0530e5b.png)
