### ISSUE TITLE
__/#/tests/... page errors 404 - page not found on Chrome 72+

### ISSUE THREAD

**Issue by pklejnowski** [cypress-io/cypress#1872]
### Is this a Feature or Bug?

BUG

### Current behavior:

Sometimes when I run **all tests** I have such error:
![image](https://user-images.githubusercontent.com/28590512/40938953-9f4f7e02-6843-11e8-8ce6-f580f88e0eef.png)

Important thing that I noticed If i remove tests "group_page.js" (check gif) it seems that the problem disappeared. "group_page.js" using different page: `cy.visit(https://localhost:5002)` for testing when the other tests that crashing using `cy.visit(https://localhost:5000)`
![error2](https://user-images.githubusercontent.com/28590512/40939071-e58c058e-6843-11e8-8022-42a2992918b1.gif)

Check this gif, I had to run 3 times **RUN ALL TESTS** to make it work. Before always failed at login_page.js 

I was trying hardcode url in `cy.visit()` (before I had url from cypress.json). The same result.

### Steps to reproduce:

Run a few tests that include cy.visit(https://localhost:5002) for 1st test and cy.visit(https://localhost:5000) for 2nd test.

### Versions
Cypress: 3.0.1
Windows 10
Chrome

**Comment by bgp1** [comment]
Wanted to add to my previous comment with additional information. I have been testing this and I can't seem to get this to work when it's on the same domain, either. The second feature I wanted to test is a self-hosted feature, meaning it's a JS file that other sites would add to their site. I was testing it on a different domain that we own. However, I have since created a page to host this for testing on the same domain as the other tests and it still does this same behavior as before. So I don't believe this to just be an issue because of two different domains. 

I believe this is an issue with the tests being broken out into multiple spec files. Even though neither test file inherits from the other I am able to replicate that the first file completes, runs a second time (for some unknown reason) and then the second test file stalls. 

I have been trying to see if I can get all tests to run in a single spec file, but so far that has proved unsuccessful for some unknown reason I am still trying to determine. 

I tested this on both 2.x and 3.x versions and the problem persists when tests are split between files.

**Comment by pklejnowski** [comment]
@bgp1 Did you find any workaround so far?

**Comment by pklejnowski** [comment]
@bgp1 Did you find any workaround so far?

**Comment by bgp1** [comment]
My workaround is to host the second application on the same domain as the first (I just created a page on there to trigger it) and then included all of the tests for both applications in a single spec file. Working for me, although not ideal.

**Comment by pklejnowski** [comment]
:/ I can't do the same thing. So I have to wait for fix...

**Comment by pklejnowski** [comment]
How long it can be in stage: "needs investigation"?

**Comment by pklejnowski** [comment]
@jennifer-shehane is it possible that you are going to fix it soon?

**Comment by jennifer-shehane** [comment]
I was not able to reproduce this issue. 

I visited 2 websites on `localhost` with different ports - visiting the first url in `spec1.js` and the second url in `spec2.js` then running "All Tests" and ran this several times. 

**spec1.js**
```js
context('Site 1', () => {
  beforeEach(() => {
    cy.visit('http://localhost:8080/commands/actions')
  })

  it('get an el', () => {
    cy.get('.action-email')
  })
})
```

**spec2.js**
```js
context('Site 2', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3030/')
  })

  it('gets el', () => {
    cy.contains('Features')
  })
})
```

![screen shot 2018-07-12 at 3 32 32 pm](https://user-images.githubusercontent.com/1271364/42655091-f79e624a-85e8-11e8-908f-bbc79143521b.png)

@pklejnowski **There is some other factor that is influencing the crash and will have to have a reproducible issue in order to begin investigating what the issue is.**

**Comment by jennifer-shehane** [comment]
@bgp1 In reference to your comment:

> When it tries to go to the second spec file it refreshes, runs the first spec file again

The first test file is not running again, but since we did go to a different url in the main window browser, the first test in the Command Line does have to re - render, so it * looks * like it is running again, when the Command is just rendering to the fresh page.

**Comment by Gachapen** [comment]
I'm having the same issue, and am struggling to debug it. It works fine when running against localhost, but when I try running it against a deployed version of the application from my computer, I get 404 instead of the cypress runner application. The 404 page shown is the 404 page generated by our application (using Vue). This makes sense, because the URL path is /__/ which should result into a 404 in our application. Something seems to prevent the cypress runner from starting up, instead it loads the application directly.

**Comment by SimoneDahmen** [comment]
I have the same Issue as @Gachapen. A "/_" is added to the app's URL and it's loaded in the chrome adress bar not in the cypress-created view within.
happens with cy.visit():
`describe('create content', function () {
        it('opening app', function () {
            cy.wait(1000),
                cy.visit('https://dev.site.com');
        });
});`
and the result is our App's 404 page on baseurl + "/_"

For me it might be an issue that I'm using an external URL.

**Comment by acailly** [comment]
If it helps, I ran into this problem by following the tutorial.

Steps I followed:

```
mkdir cypress-test
cd cypress-test
yarn init -y
yarn add cypress --dev
yarn cypress open
```

Then create a `sample_specs.js` file with: 

```
describe('My First Test', function() {
  it('Visits the Kitchen Sink', function() {
    cy.visit('https://example.cypress.io')
  })
})
```

Then click on this file in cypress GUI: 

- the browser open at `http://localhost:65327/__/#/tests/integration\sample_specs.js`
- the browser navigate to `https://example.cypress.io/__/#/tests/integration\sample_specs.js` which gives a 404 error

**Comment by vadymkukhtinOD** [comment]
@jennifer-shehane @acailly @SimoneDahmen 
Same issue here. 
The reason for me is that I have service-worker which is precaching assets.
If I unregister service-worker everything works fine.
If I remove manually "/__/" on debug mode and after reload tests are working as well fine.
The problem is that first test runs well, then cypress goes to 2nd one and 2nd test case starts on 404 "..../__/#/tests/integration" already even not reaching beforeEach func.

**Comment by acailly** [comment]
@vadymkukhtinOD  I don't see any registered service-worker in the application tab of dev tools

**Comment by pklejnowski** [comment]
I don't have any service-worker and this problem still occurs in my application.
What is interesting. I have 3 test files. When I run each test separatly, there this problem is not occuring, but when I run all of them at once, then this problem occurs.

**Comment by blakelee-pendo** [comment]
+1 
We're having the same issue

**Comment by vadymkukhtinOD** [comment]
@acailly Probably service-worker just covering the real issue. Still investigating

**Comment by matt212** [comment]
+1
We're having the same issue

**Comment by matt212** [comment]
@jennifer-shehane  any updates or workaround since it's bit of a hinderance  when writing test cases.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll cannot investigate an issue if no reproducible example is provided. Can anyone provide a way to reproduce this exactly?

**Comment by SimoneDahmen** [comment]
@jennifer-shehane I am working on a Mac, have a parent folder with one cypress child and one yarn child. In the yarn child I have the app files, in the cypress/integration I have my tests files. Both child folders have their own git repository.
I installed cypress via console, using npm.

That very integration folder I open in cypress (cypress I have in my applications so I'm not starting it via terminal).
Then I click the file in the cypress window.
Then the chrome window opens and starts running the test but is redirected to the url mentioned above after a second.
This is the code I try to visit the page with:
`it('opening /moments', function () {
            cy.visit('localhost:3000/moments');
        });`

When reproducing this again, I noticed that the first script I run after opening cypress works, but the ones afterwards don't. So when I close/stop the remote chrome window and try to run another test file, I will have this issue.

![bildschirmfoto 2018-11-30 um 16 17 07](https://user-images.githubusercontent.com/42211937/49299269-a04afd00-f4bf-11e8-954e-6d6acf74920f.png)
![bildschirmfoto 2018-11-30 um 16 54 15](https://user-images.githubusercontent.com/42211937/49299754-cfae3980-f4c0-11e8-9608-461ffeabbbf3.png)
![bildschirmfoto 2018-11-30 um 16 54 52](https://user-images.githubusercontent.com/42211937/49299755-d046d000-f4c0-11e8-8b39-86cb064dae49.png)
('this site does not exist – back to index')

**Comment by jennifer-shehane** [comment]
@SimoneDahmen Ok, you are running cypress in what we call 'global mode'. 

I'm still a bit confused as to what your project directory looks like and which part you are opening in global mode from the screenshots and information given. 

- Could you share your `cypress.json` configuration? As I'm sure you have edited some of the folder's locations like these: https://on.cypress.io/configuration#Folders-Files
- Could you draw an example of your folder config like below?

```
📁my-web-app -- // this folder I drag into cypress
  📁app
  📁cypress
    📁fixtures
    📁integration
    📁plugins
    📁support
  📁node_modules
  📄cypress.json
  📄package.json
```

**Comment by jarrodldavis** [comment]
I'm running into this same issue and it appears to be caused by Chrome/Chromium not respecting the `--proxy-server` command line flag (provided by Cypress when launching the browser) for `localhost` and `127.0.0.1` URLs. I confirmed this behavior using debugging output both by Cypress (using `DEBUG=cypress:* ./node_modules/.bin/cypress open --config baseUrl=http://127.0.0.1:8080/`) and Chromium's own network logging (`chrome://net-export/`).

Here's a snippet of those `net-export` logs:

```json
{"params":{"priority":"HIGHEST","url":"http://127.0.0.1:8080/__/#/tests/integration/test.js"},"phase":1,"source":{"id":180,"type":1},"time":"8498558","type":2},
{"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":100},
{"phase":2,"source":{"id":180,"type":1},"time":"8498559","type":100},
{"params":{"load_flags":9217,"method":"GET","privacy_mode":0,"url":"http://127.0.0.1:8080/__/#/tests/integration/test.js"},"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":96},
{"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":99},
{"phase":2,"source":{"id":180,"type":1},"time":"8498559","type":99},
{"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":113},
{"phase":2,"source":{"id":180,"type":1},"time":"8498559","type":113},
{"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":114},
{"params":{"entry_hash":"0x52f2db36893f29dc"},"phase":1,"source":{"id":181,"type":13},"time":"8498559","type":355},
{"params":{"key":"http://127.0.0.1:8080/__/"},"phase":0,"source":{"id":181,"type":13},"time":"8498559","type":356},
{"phase":0,"source":{"id":181,"type":13},"time":"8498559","type":379},
{"phase":0,"source":{"id":181,"type":13},"time":"8498559","type":380},
{"params":{"net_error":-411},"phase":2,"source":{"id":180,"type":1},"time":"8498559","type":114},
{"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":115},
{"params":{"entry_hash":"0x52f2db36893f29dc"},"phase":1,"source":{"id":182,"type":13},"time":"8498559","type":355},
{"params":{"key":"http://127.0.0.1:8080/__/"},"phase":0,"source":{"id":182,"type":13},"time":"8498559","type":356},
{"phase":0,"source":{"id":182,"type":13},"time":"8498559","type":360},
{"phase":0,"source":{"id":182,"type":13},"time":"8498559","type":361},
{"phase":2,"source":{"id":180,"type":1},"time":"8498559","type":115},
{"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":116},
{"params":{"address_family":0,"allow_cached_response":true,"host":"127.0.0.1:8080","is_speculative":false},"phase":1,"source":{"id":183,"type":0},"time":"8498559","type":3},
{"phase":2,"source":{"id":183,"type":0},"time":"8498559","type":3},
{"phase":2,"source":{"id":180,"type":1},"time":"8498559","type":116},
{"params":{"is_preconnect":false,"url":"http://127.0.0.1:8080/__/#/tests/integration/test.js"},"phase":1,"source":{"id":184,"type":23},"time":"8498559","type":151},
{"phase":1,"source":{"id":180,"type":1},"time":"8498559","type":137},
{"params":{"source_dependency":{"id":184,"type":23}},"phase":0,"source":{"id":180,"type":1},"time":"8498559","type":152},
{"params":{"source_dependency":{"id":180,"type":1}},"phase":0,"source":{"id":184,"type":23},"time":"8498559","type":152},
{"phase":1,"source":{"id":184,"type":23},"time":"8498559","type":23},
{"params":{"pac_string":"DIRECT"},"phase":0,"source":{"id":184,"type":23},"time":"8498560","type":25},
{"phase":2,"source":{"id":184,"type":23},"time":"8498560","type":23},
{"params":{"proxy_server":"DIRECT"},"phase":0,"source":{"id":184,"type":23},"time":"8498560","type":153},
```

Notice the last line: `{"proxy_server":"DIRECT"},`.

Here's another snippet of those same logs, this time connecting to the same local server using my computer's network IP instead of `127.0.0.1`: 

```json
{"params":{"priority":"HIGHEST","url":"http://10.0.0.249:8080/__/#/tests/integration/test.js"},"phase":1,"source":{"id":195,"type":1},"time":"8515014","type":2},
{"phase":1,"source":{"id":195,"type":1},"time":"8515015","type":100},
{"phase":2,"source":{"id":195,"type":1},"time":"8515015","type":100},
{"params":{"load_flags":9216,"method":"GET","privacy_mode":0,"url":"http://10.0.0.249:8080/__/#/tests/integration/test.js"},"phase":1,"source":{"id":195,"type":1},"time":"8515015","type":96},
{"phase":1,"source":{"id":195,"type":1},"time":"8515015","type":99},
{"phase":2,"source":{"id":195,"type":1},"time":"8515015","type":99},
{"phase":1,"source":{"id":195,"type":1},"time":"8515015","type":113},
{"phase":2,"source":{"id":195,"type":1},"time":"8515015","type":113},
{"phase":1,"source":{"id":195,"type":1},"time":"8515015","type":114},
{"params":{"entry_hash":"0xfcb31c53c472bc92"},"phase":1,"source":{"id":196,"type":13},"time":"8515015","type":355},
{"params":{"key":"http://10.0.0.249:8080/__/"},"phase":0,"source":{"id":196,"type":13},"time":"8515015","type":356},
{"phase":0,"source":{"id":196,"type":13},"time":"8515015","type":357},
{"params":{"net_error":-2},"phase":0,"source":{"id":196,"type":13},"time":"8515015","type":359},
{"phase":2,"source":{"id":196,"type":13},"time":"8515015","type":355},
{"params":{"net_error":-2},"phase":2,"source":{"id":195,"type":1},"time":"8515015","type":114},
{"phase":1,"source":{"id":195,"type":1},"time":"8515015","type":115},
{"params":{"entry_hash":"0xfcb31c53c472bc92"},"phase":1,"source":{"id":197,"type":13},"time":"8515015","type":355},
{"params":{"key":"http://10.0.0.249:8080/__/"},"phase":0,"source":{"id":197,"type":13},"time":"8515015","type":356},
{"phase":0,"source":{"id":197,"type":13},"time":"8515015","type":360},
{"phase":0,"source":{"id":197,"type":13},"time":"8515015","type":361},
{"phase":0,"source":{"id":197,"type":13},"time":"8515015","type":362},
{"phase":2,"source":{"id":195,"type":1},"time":"8515016","type":115},
{"phase":1,"source":{"id":195,"type":1},"time":"8515016","type":116},
{"phase":2,"source":{"id":195,"type":1},"time":"8515016","type":116},
{"params":{"is_preconnect":false,"url":"http://10.0.0.249:8080/__/#/tests/integration/test.js"},"phase":1,"source":{"id":198,"type":23},"time":"8515016","type":151},
{"phase":1,"source":{"id":195,"type":1},"time":"8515016","type":137},
{"params":{"source_dependency":{"id":198,"type":23}},"phase":0,"source":{"id":195,"type":1},"time":"8515016","type":152},
{"params":{"source_dependency":{"id":195,"type":1}},"phase":0,"source":{"id":198,"type":23},"time":"8515016","type":152},
{"phase":1,"source":{"id":198,"type":23},"time":"8515016","type":23},
{"params":{"pac_string":"PROXY localhost:58283"},"phase":0,"source":{"id":198,"type":23},"time":"8515016","type":25},
{"phase":2,"source":{"id":198,"type":23},"time":"8515016","type":23},
{"params":{"proxy_server":"PROXY localhost:58283"},"phase":0,"source":{"id":198,"type":23},"time":"8515016","type":153},
```

This time, Cypress' proxy server is being used: `{"proxy_server":"PROXY localhost:58283"}`

**Comment by jennifer-shehane** [comment]
Can confirm - this is happening on Chrome Version 73.0.3658.0 (Official Build) canary (64-bit) for me also.

**Comment by jennifer-shehane** [comment]
Checking through [changelogs between Beta build (71.0.3578.80) and the current Dev build (72.0.3626.7)](https://chromium.googlesource.com/chromium/src/+log/71.0.3578.0..72.0.3626.0?pretty=fuller&n=10000)

I'm initially suspecting that this implementation change is the culprit - introduced in Version 72.0.3605.0 - which I can confirm is broken (showing 404 page). Commit: https://chromium.googlesource.com/chromium/src/+/da790f920bbc169a6805a4fb83b4c2ab09532d91 

**Commit Text**
>Implicitly bypass localhost when proxying requests.
>
>This aligns Chrome's behavior with the Windows and macOS proxy resolvers (but not Firefox).
>
>Concretely:
> * localhost names (as determined by net::IsLocalhost) now implicitly bypass the proxy
> * link-local IP addresses implicitly bypass the proxy
>
>The implicit rules are handled by ProxyBypassRules, and it is possible to override them when manually configuring proxy settings (but not when using PAC or auto-detect).
>
>This change also adds support for the "<-loopback>" proxy bypass rule, with similar semantics as it has on Windows (removes the implicit bypass rules for localhost and link-local).
>
>The compatibility risk of this change should be low as proxying through localhost was not universally supported. It is however an idiom used in testing (a number of our own tests had such a dependency). Impacted users can use the "<-loopback>" bypass rule as a workaround.

[*Download Chromium Version 72.0.3598.0 (WORKING)*](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/604471/)
[*Download Chromium Version 72.0.3605.0 (BROKEN)*](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/606281/)

Further narrowing down of [Changelog between broken versions](https://chromium.googlesource.com/chromium/src/+log/72.0.3598.0..72.0.3605.0?pretty=fuller&n=10000)

**Other potentially relevant commits:**
- https://chromium.googlesource.com/chromium/src/+/d31efeca7c0554367d4ba3a293a0a81b6fe872e0

**Commits made after culprit commit that may help with solution**  (oldest -> newest commits)
- https://chromium.googlesource.com/chromium/src/+/5b1b6fbfb1953a06eb78ec1ea1bf70e124417edb
- https://chromium.googlesource.com/chromium/src/+/1deb8f2c7684650358ca739e7c34f2e17aaa6a0d
- https://chromium.googlesource.com/chromium/src/+/2e38d313a49bc8c28b8ce38f004776dbf4357b99
- https://chromium.googlesource.com/chromium/src/+/efdf315bc867468592bfe7a58da2225935281e7d
- https://chromium.googlesource.com/chromium/src/+/15242c0c52f055089ca410881dc049f43a2c4e62
- https://chromium.googlesource.com/chromium/src/+/7aeea3a2da27e2bf566cf11e75f960124061c79c

**Comment by smoothdvd** [comment]
It's not working in headless mode

**Comment by jennifer-shehane** [comment]
Hey @smoothdvd, could you open a new issue with a reproducible example of your problem? This issue has been fixed and likely you are experiencing a similar issue due to another cause. Thanks!

**Comment by yeya** [comment]
Same issue with cypress 3.1.5 and chrome 72.
I'm running `npx cypress open` on new project with no files at all. Just the auto generated specs.

Same issue with localhost site.

![image](https://user-images.githubusercontent.com/6382246/53304344-c09b1580-387c-11e9-8e3f-67cfbc3c8667.png)

I tried to add the temp code to plugins but I see that the argument already there:
`  '--disable-default-apps',
  '--use-fake-ui-for-media-stream',
  '--use-fake-device-for-media-stream',
  '--proxy-server=http://localhost:30943',
  '--proxy-bypass-list=<-loopback>',
  '--proxy-bypass-list=<-loopback>' ]`

**Comment by RicardoVaranda** [comment]
This is still happening to me in 3.2.0

**Comment by jennifer-shehane** [comment]
Hey if you're experiencing a similar issue, could you open a new issue with a complete reproducible example of your problem? Thanks!
