### ISSUE TITLE
Very flaky tests depending on CPU: `cy.type()` failed because it targeted a disabled element

### ISSUE THREAD

**Issue by jannnik** [cypress-io/cypress#18738]
### Current behavior

In most of our tests we experience the following error type. After migrating from Jenkins to GitHub Actions, the error occurs more often. Around 20 percent of our tests fail. After our investigation (see below), we think that the tests are flakier on slow machines. 

The error only occurs on the `cy.type()` command after a new page in our SPA is rendered. 

```
CypressError: `cy.type()` failed because it targeted a disabled element.
The element typed into was:

> <input aria-invalid="false" autocomplete="random-ortqaaq3k7f" id="toolbar-search-input" placeholder="Search..." type="text" data-tid="toolbar-search-input" class="resourceroadrunner-MuiInputBase-input resourceroadrunner-MuiInput-input resourceroadrunner-MuiInputBase-inputAdornedStart" value="">

Ensure the element does not have an attribute named `disabled` before typing into it.
```

### Desired behavior

This error should never occur without a valid reason. We have analyzed the tests and made sure that the element is ready for text input. It is **not** disabled and has no other properties that should prevent typing. 
We think that the tests should be able to run on GHA runners without problems and that Cypress should handle machines reaching their CPU limit.

### Test code to reproduce

Since the error is in our test suite with about 100 tests, we have tried to find a minimal example in which the error becomes reproducible. Unfortunately, we didn't manage to create an example without leaking our secrets for API calls and test system creation. 

Here is a repository where one of the failing tests is schematically recreated and executed on an existing test system. 
https://github.com/meisterplan/cypress-disabled-element-repo/blob/master/cypress/integration/min.spec.js

As soon as we create the test system inside the test, add some more steps to 'setup' the test and make some API calls, the test fails in 10-20 percent. 

### Cypress Version

6.9.1, 8.5 - 8.7

### Other

We investigated **a lot of time** to find the cause of the error and to find workarounds, none of them stabilized the tests completely. Key findings were that increasing the platform performance decreased the error rate and decreasing the performance (or enabling debugging) increased the error rate. 

#### Tried Workarounds
* We added `wait(500)` in the chain before executing `type()`  
* We added `wait(30000)` in the chain before executing `type()`  
* We added `wait(30000)` in multiple parts of the test to give the CPU time to calm down 
* We added the `force: true` option to the `type()` command
* We asserted `should('not.to.be.disabled')`  before executing `type()`
* We added `focus()`on the input before executing `type()`
* We added `click()`on the input before executing `type()`
* We tried to type on different elements (on the MUI TextField `div` directly on the `input`)
* We checked our application against weird render behaviors
* We checked `isTextLike` und `isFocusable` before executing `type()`, both were always true

#### Tried different test platform and configuration
* We disabled auto scrolling 
* We removed 3rd party dependencies
* We tried multiple cypress versions (6.9.1, 8.5 - 8.7)
* We set `numTestsKeptInMemory` to `0` and `1`
* We enabled debugging --> this increased the error rate 
* We analyzed CPU an Memory via debugging --> **the busier the CPU, the higher is the error rate**
* We executed the tests in the official cypress docker container (cypress/browsers:node16.5.0-chrome94-ff93)
* We executed the tests directly on the GHA machine
* We executed the tests on different Chrome versions
* We executed the tests on electron
* We disabled video recording 
* We disabled screenshot recording 
* We executed the tests with `nodeVersion: local` and tried different node versions
* We executed the tests on self-hosted runners with different machine performance --> **higher performance leads to lower error rate, but the error occurs on machines with very high performance**

**Comment by cheapsteak** [comment]
We ran into what looks like the same problem

Have also asserted `should('not.to.be.disabled')` before running `.clear()` and `.type()`

Setting `{ force:true }` seems to have successfully worked around the problem for us (in calls to both `clear()` and `type()`)

Looking at the code https://github.com/cypress-io/cypress/blob/3817e507169b01eb0a29966a77be765fba605cdf/packages/driver/src/cy/keyboard.ts#L446-L452 

It seems like it should be impossible to get the `not_actionable_textlike` message (`${cmd('type')} failed because it targeted a disabled element.`) to throw if `force` was set to true, 
 and that instance is the only place that throws `not_actionable_textlike` that I could find

(side note -- wish cypress could more clearly state which part of the conditional was not behaving as needed; i.e. was it not focuseable or was it not textlike?)
