### ISSUE TITLE
Angular schematic ignores baseUrl if a devServerTarget is defined

### ISSUE THREAD

**Issue by ashblox** [cypress-io/cypress#18745]
### Current behavior

We recently made a switch to use the Cypress' official Angular schematic, @cypress/schematic. After doing so, some of our commands stopped working - particularly when a `devServerTarget` is specified.

For background, our app uses different routing when it's run locally. So instead of https://localhost:4200, our landing page lives at https://localhost:4200/foo. Well the `baseUrl` defined in our e2e configurations is meant to account for this. Oddly enough, though, when we run an e2e command that specifies the `devServerTarget` && the `baseUrl` the `baseUrl` gets completely ignored!

I've put together an example app. There is a workaround, which is to define the `deployUrl` for your app in that particular configuration in the `angular.json`. I'll add that this is probably best practice. But if I specify an option in my build config... I'd think it would get used. Right?

### Desired behavior

If I specify a `baseUrl` in my e2e configurations using the @cypress/schematic builder, then that `baseUrl` should be what Cypress uses when I do a `cy.visit()` or a `cy.log(${Cypress.config().baseUrl})`.

### Test code to reproduce

https://github.com/ashblox/base-url-problem

### Cypress Version

8.7.0

### Other

@cypress/schematic version 1.5.1

**Comment by admah** [comment]
Custom URLs can be passed through configurations via Angular.json in `1.7.0`. More info can be found [here](https://www.npmjs.com/package/@cypress/schematic).

For example: 

```
"cypress-open": {
  "builder": "@cypress/schematic:cypress",
  "options": {
    "devServerTarget": "{project-name}:serve",
    "watch": true,
    "headless": false
  },
  "configurations": {
    "production": {
      "devServerTarget": "{project-name}:serve:production"
    },
    "local-dev": {
      "devServerTarget": "{project-name}:serve:development",
      "baseUrl": "http://localhost:4002"
    },
    "another-env": {
      "devServerTarget": "{project-name}:serve:development",
      "baseUrl": "http://localhost:4004"
    }
  }
}```
