### ISSUE TITLE
moving from iframe to another page Cypress open it inside the first iframe 

### ISSUE THREAD

**Issue by muhammmedkhattab** [cypress-io/cypress#18744]
### Current behavior

if you opened iframe A then click on any button that takes you to another page with the same domain cypress open it in iframe A so you can't access the elements or make any action on them  and toolbar and everything is duplicated it opens the whole website in another iframe 
images is added in the code 
[couldn't add a code because our environment can't be access globally ]

### Desired behavior

cypress should normally move to the other page and forget in the memory that he already out of the iframe 

### Test code to reproduce

**Iframe page:** 
![Screenshot 2021-11-02 at 15 28 25](https://user-images.githubusercontent.com/36113228/139867435-647895fa-d6a4-4cd5-a9aa-08f8921e276b.png)
**Next page after iframe:** 
![Screenshot 2021-11-02 at 15 32 36](https://user-images.githubusercontent.com/36113228/139868408-0670ed8f-6d19-445c-8efd-fbd9705ca062.png)

### Cypress Version

8.7.0

### Other

[can't use cypress without access iframe selectors as it is mandatory for our business ]

**Comment by emilyrohrbough** [comment]
> [couldn't add a code because our environment can't be access globally ]

Can you create a small code-example and a sample test case we can use as a reference point? They can be a simplified/high-level examples based on  the workflow of the code you are testing against. Adding this would give us a better understanding of the flow you are trying to accomplish.

**Comment by muhammmedkhattab** [comment]
Hi @emilyrohrbough ,
I hope this can help out 
this is the iframe HTML code 👍 


`<div class="BaseLayout-children css-1lp67ca-BaseLayout"><div class="DesktopDetailPage-servicePanel"><div class="css-1fzsd0p-mainContainer"><div class="css-mrmi9c" style="left: 179.05px;"><div class="css-198rwon-icon"><svg xmlns="http://www.w3.org/2000/svg" width="20.673" height="27.634" viewBox="0 0 20.673 27.634"><path fill="#005EA8" d="M4.6,27.675A3.617,3.617,0,0,1,2.2,27.149C.373,25.961-.1,24.5.041,24.109a18.547,18.547,0,0,1,1.631-2.986,20.138,20.138,0,0,1,1.963-2.516c.553-.636,2.9,1.355,3.981.525a34.833,34.833,0,0,0,3.566-4.672,36.911,36.911,0,0,0,2.847-5.2c.332-1.327-2.433-2.709-2.073-3.456a20.9,20.9,0,0,1,1.493-2.82A22.515,22.515,0,0,1,15.522.279c.3-.276,1.825-.442,3.649.746a3.134,3.134,0,0,1,1.493,2.682c-.691,3.124-2.9,7.989-6.082,12.993a56.072,56.072,0,0,1-8.4,10.063Z" transform="translate(-0.018 -0.079)"></path></svg></div><div><div><div class="css-12be2u1-phoneNumber">089 - 21 12 98 598</div><div class="css-1vln73g-openingTimes">Mo. - So. von 08 - 20 Uhr</div></div></div></div><div class="css-mrmi9c" style="left: 179.05px;"><div class="css-198rwon-icon"><svg xmlns="http://www.w3.org/2000/svg" width="25.932" height="20.375" viewBox="0 0 25.932 20.375"><g transform="translate(0 0)"><path fill="#005EA8" d="M39.764,331.447a2.216,2.216,0,0,0,1.517-.573l-7.347-7.347-.509.366q-.825.608-1.339.948a8.252,8.252,0,0,1-1.367.695,4.168,4.168,0,0,1-1.592.354H29.1a4.167,4.167,0,0,1-1.592-.354,8.225,8.225,0,0,1-1.367-.695q-.514-.34-1.339-.948c-.153-.112-.323-.236-.507-.368l-7.348,7.349a2.217,2.217,0,0,0,1.518.573Z" transform="translate(-16.148 -311.072)"></path><path fill="#005EA8" d="M1.462,199.814A7.672,7.672,0,0,1,0,198.555v11.178l6.475-6.475Q4.532,201.9,1.462,199.814Z" transform="translate(0 -191.985)"></path><path fill="#005EA8" d="M418.335,199.814q-2.957,2-5.026,3.446l6.473,6.473V198.555A7.988,7.988,0,0,1,418.335,199.814Z" transform="translate(-393.85 -191.985)"></path><path fill="#005EA8" d="M23.622,59.013H2.321a2.066,2.066,0,0,0-1.715.752,2.92,2.92,0,0,0-.6,1.881,3.381,3.381,0,0,0,.8,1.975,7.179,7.179,0,0,0,1.693,1.671q.492.348,2.967,2.062c.891.617,1.665,1.155,2.331,1.619.567.4,1.057.738,1.461,1.022l.216.154.4.288q.47.34.781.55t.753.47a4.39,4.39,0,0,0,.832.391,2.3,2.3,0,0,0,.723.13h.029a2.3,2.3,0,0,0,.724-.13,4.38,4.38,0,0,0,.832-.391q.441-.261.753-.47t.781-.55l.4-.287L16.691,70l1.464-1.018,5.308-3.685a6.883,6.883,0,0,0,1.765-1.78,3.828,3.828,0,0,0,.709-2.185,2.334,2.334,0,0,0-2.316-2.315Z" transform="translate(-0.006 -59.013)"></path></g></svg></div><div><div><div class="css-8g0xoz-emailAddress"></div><div class="css-18o7ig3-email"><a>E-Mail schreiben</a></div></div></div></div></div></div><div class="DesktopDetailPage-container"><div class="MobileDetailHeader"><div class="HeaderBackNavigation"><a class="HeaderBackNavigation-backLink"><svg class="Icon HeaderBackNavigation-backLinkIcon"><use xlink:href="#icon-slider-dda3c0"></use></svg><span class="HeaderBackNavigation-backLinkText">zurück</span></a></div></div><div class="DesktopDetailHeader"><div class="HeaderBackNavigation DesktopDetailHeader-backNavigation"><a class="HeaderBackNavigation-backLink"><svg class="Icon HeaderBackNavigation-backLinkIcon"><use xlink:href="#icon-back_arrow-25806b"></use></svg><span class="HeaderBackNavigation-backLinkText">zurück</span></a></div><p class="DesktopDetailHeader-description">Meine <span class="DesktopDetailHeader-productName">Privathaftpflichtversicherung</span> im Detail</p></div><div class="DesktopDetailPage-thirdView"><div class="DetailFrame-outerContainer"><div class="DetailFrame"><div class="DetailFrame-border"><div class="DetailFrame-container"><iframe id="DetailiFrame" title="DetailFrame" class="DetailFrame-frame" scrolling="no" src="https://www.check24-test.de/versicherungsordner/vertraege/detail/contract/61824126ad41dd00062c198c?deviceoutput=desktop&amp;sameOrigin=true&amp;vc-data=null&amp;from=2ndView" style="height: 1817px;" frameborder="0"></iframe></div></div></div></div></div></div></div>`

**Comment by jennifer-shehane** [comment]
@muhammmedkhattab Thanks for sending the iframe code. Could you also include the test code ran to get into this situation? A repo example of the example app code + test code would be ideal.

**Comment by muhammmedkhattab** [comment]
Hi @jennifer-shehane 

I hope this can help you out 

My code:

`    cy.getIframe("#DetailiFrame")
     .find("[data-id='button-edit-vertragsdaten']")
      .click();
`
iframe command:
`Cypress.Commands.add("getIframe", ($getIframeSelector) => {
  return (
    cy
      .get($getIframeSelector)
      .its("0.contentDocument")
      .should("exist")
      // automatically retries until body is loaded
      .its("body")
      .should("not.be.undefined")
      // wraps "body" DOM element to allow
      // chaining more Cypress commands, like ".find(...)"
      .then(cy.wrap)
  );
});
`

Video:

https://user-images.githubusercontent.com/36113228/140485967-bc667f64-727f-4ffe-a543-1df2cbfe4fd1.mp4

**Comment by BlueWinds** [comment]
I'm having trouble following how this is a cypress bug - without your application, I can't debug the internals of your iframe.

Consider the following test:

```
  it.only('iframe', () => {
    cy.document().then(doc => {
      doc.body.innerHTML = `
        <iframe id="foo" />
      `
    })

    cy.get('iframe').then(iframe => {
      iframe[0].contentDocument.body.innerHTML = `
        <a href="https://google.com" target="_parent">Link</a>
      `
    })

    cy.getIframe("#foo")
      .find("a")
      .click({ force: true }); // force is only necessary because of how I'm hacking this example together
  })
```

This test causes the application under test - the whole page - to load google.com. If we remove the _target attribute:
```
<a href="https://google.com">Link</a>
```
google instead opens inside the iframe. Can you edit this example test to show the behavior in your application you're not expecting to see?
