### ISSUE TITLE
Cypress crash when we try to click on button in iframe  or when we use {multiple:true} or visible

### ISSUE THREAD

**Issue by muhammmedkhattab** [cypress-io/cypress#18742]
### Current behavior

when i access the iframe no issues appears 
but after trying to click on certain buttons with (id selectors) in the iframe , **Cypress UI crash**
Tried with {multiple:true} and : visible but also failed 

### Desired behavior

cypress should not crash and continue usual  

### Test code to reproduce

`    cy
      .get($getIframeSelector)
      .its("0.contentDocument")
      .should("exist")
      // automatically retries until body is loaded
      .its("body")
      .should("not.be.undefined")
      // wraps "body" DOM element to allow
      // chaining more Cypress commands, like ".find(...)"
      .then(cy.wrap)
      .find("[data-id=test]")
      .click();
`

### Cypress Version

8.7.0

### Other

[This issue block us from using cypress as we have iframes to deal with in the project]

**Comment by jennifer-shehane** [comment]
Hey @muhammmedkhattab Iframe testing is not natively available within Cypress, so some of the testing is using the approach you have above. We can’t guarantee everything is testable in this situation.

However the Cypress UI crashing is definitely not the intended behavior, even when hacking around iframes. 

Can you provide a video/screenshot of what is shown during the ‘crash’? What error is printing in the terminal at that time?

Also a way to reproduce the issue on our end would be ideal if you can narrow down the issue to a repo we could run and see. Thanks!

**Comment by muhammmedkhattab** [comment]
Hello @jennifer-shehane  
I added a video to help and the last logs that cypress throws and the code used 

Code used : 

` cy.getIframe("#DetailiFrame")
      .find("[data-id='button-cancel-contract-desktop']")
      .click();`

`Cypress.Commands.add("getIframe", ($getIframeSelector) => {
  return (
    cy
      .get($getIframeSelector)
      .its("0.contentDocument")
      .should("exist")
      // automatically retries until body is loaded
      .its("body")
      .should("not.be.undefined")
      // wraps "body" DOM element to allow
      // chaining more Cypress commands, like ".find(...)"
      .then(cy.wrap)
  );
});`

Cypress last logs in the vs console : 
`GET /__cypress/runner/cypress_runner.js 304 0.911 ms - -
GET /__cypress/runner/cypress_runner.css 200 2.472 ms - -
GET /__cypress/runner/fonts/mulish-latin-400-normal.woff2 304 1.437 ms - -
GET /__cypress/runner/img/no-spec-instructions.png 200 3.585 ms - 46495
GET /__cypress/runner/fonts/fa-solid-900.woff2 304 2.508 ms - -
`


https://user-images.githubusercontent.com/36113228/140483804-5fabec9a-d6dc-462e-a23b-b81915768859.mp4

**Comment by BlueWinds** [comment]
@muhammmedkhattab - If you use triple ticks, it can make multi-line code blocks much easier to read. I hope you don't mind I edited your last comment to include them.

I've attempted to reproduce your issue, but haven't had and luck so far. It may be specific to something about your iframe; the simplest case seems to work fine.

I based this on your provided code, but since I don't have your application, mocked up the inner iframe.
```
  it('crashes', () => {
    Cypress.Commands.add("getIframe", ($getIframeSelector) => {
      return (
        cy
          .get($getIframeSelector)
          .its("0.contentDocument")
          .should("exist")
          // automatically retries until body is loaded
          .its("body")
          .should("not.be.undefined")
          // wraps "body" DOM element to allow
          // chaining more Cypress commands, like ".find(...)"
          .then(cy.wrap)
      );
    });

    cy.document().then(doc => {
      doc.body.innerHTML = `
        <iframe />
      `
    })

    cy.get('iframe').then(iframe => {
      iframe[0].contentDocument.body.innerHTML = `<button>Hi</button>`
    })

    cy.getIframe("iframe")
      .find("button")
      .click();
  })
```

This works as expected, no crash.

If you can help narrow down the issue a bit more - such as with a standalone test case that causes the crash for you - that would be very helpful. You may also be able to get more information by enabling by [enabling debug logs](https://docs.cypress.io/guides/guides/command-line#Enable-Debug-Logs).

**Comment by SimonGiraudMVMS** [comment]
i still have the same issue with the followed code : 

```
`    cy.get('.__PrivateStripeElement > iframe').click() // in cy.get() insert stripe iframe id
    cy.wait(6000)
    cy.get('iframe').then($iframe => {
      const doc = $iframe.contents()
      let input = doc.find('input')[0]
      cy
        .wrap(input)
        .type('4242424242424242')
      input = doc.find('input')[1]
      cy
        .wrap(input)
        .clear()
        .type('12')
        .type('29')
      input = doc.find('input')[2]
      cy
        .wrap(input)
        .type('123')
      // .type('{enter}')
    })`
```
    
    Anyone can help ?

**Comment by nagash77** [comment]
@SimonGiraaudMVMS please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate. We will need a full test in order to replicate this issue including navigation to a site that demonstrates the problem.
