### ISSUE TITLE
.intercept() does not provide statusCode and response body in GUI

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#18757]
### Current behavior

I’m having trouble with intercepting a request in my application. I should be able to look into the response body, but it is not visible. Status code is 0. I can see the proper response and status code about once in 100 times, not sure what exactly causes it to appear. But I can see that the dot is grey instead of being blue in the GUI.
![Screenshot 2021-11-02 at 22 35 08](https://user-images.githubusercontent.com/23213553/139955514-4a4e64f1-fd01-4be2-beef-3db03e2cbfd8.png)

### Test code to reproduce

https://github.com/filiphric/trelloapp-vue-vite-ts/blob/failing-to-load-response-body/cypress/integration/example.spec.ts

### Cypress Version

8.7.0

**Comment by jennifer-shehane** [comment]
The status code within the XHR in our own console log expansion shows as 200. I bet there's some falsey check or something somewhere that's making this convert to 0 in our logs. 

<img width="525" alt="Screen Shot 2021-11-02 at 4 11 04 PM" src="https://user-images.githubusercontent.com/1271364/139958925-91242c1d-5998-4f6f-a192-eb72496106cf.png">

**Comment by Igarfinkle** [comment]
I'm also having this issue. Is there a workaround? A way to look at the XMLHttpRequest object for a request that Cypress thinks never completes?
