### ISSUE TITLE
cy.attachFile for aliases, fixtures and file paths

### ISSUE THREAD

**Issue by BlueWinds** [cypress-io/cypress#18753]
### What would you like?

As a follow-up to https://github.com/cypress-io/cypress/issues/18752, we'll expand the features `cy.attachFile()` supports for increased usability, allowing developers to load their data in a wider variety of ways.

This ticket will add support for:
```js
cy.attachFile('path/to/myFile.json')
cy.attachFile('@myAlias')
```

The details of this feature are described more thoroughly in our internal documents, and will be described here (and in the documentation) when we start work on them.

**Comment by Shahrukhk999** [comment]
i want to use this please let me know when the feature is ready
