### ISSUE TITLE
yarn install is slow when using cypress orb

### ISSUE THREAD

**Issue by timharsch** [cypress-io/cypress#18750]
### Current behavior

I'm using cypress orb and have noticed that my yarn install step is slow. It seems the issue is that the workspace does not persist the node_modules path (from my reading of the source, and discussion on gitter). I do get the yarn cache between jobs, but it seems the step is slow from all the I/O around recreating the node_modules path.  see this discussion topic for some additional insight into the node_modules problem: https://discuss.circleci.com/t/yarn-cached-install-slow/34823

This is due to the simplified api of the attach-workspace command of the orb.  Currently it takes only a boolean value, which then translates the desired attach-workspace command of the circieci configuration.

I'm still new to circleci and fumbling my way through.  Not sure if the solution is to just add the paths to the save cache of the orb, or if there should be a new parameter introduced to the orb for saving the node_modules.
see: https://github.com/cypress-io/circleci-orb/blob/a56e6062e7fe547cccc9f77a0649f2ec1dcc4114/src/orb.yml#L258

### Desired behavior

Have node_modules included in the cache, or have a new parameter that would allow it.

### Test code to reproduce

 jobs:
      - cypress/install:

run time for my project is around 2 minutes for yarn install step, when it should be <10 seconds or so.

### Cypress Version

8.6.0

**Comment by timharsch** [comment]
my workaround to this problem was to eject from the cypress orb

**Comment by sandwichsudo** [comment]
We've found this as well, it looks like the orb caches the yarn cache, and while that prevents us having to download the dependencies again, we still end up having to build all the packages. Ideally we'd want to also cache the node_modules directory. It doesn't look there is a way to do that from the orb?

**Comment by timharsch** [comment]
That's the conclusion I came to.  I worked around the problem by ejecting from the orb and just writing the build code from scratch, borrowing pieces of the orb code when I needed to.  That got us a lot farther..  however, in the end, we decided CircleCI was not the platform we wanted to use so we switched to GitHub actions.  We're much happier with actions.
