### ISSUE TITLE
cy.attachFile for Buffers with `input` action

### ISSUE THREAD

**Issue by BlueWinds** [cypress-io/cypress#18752]
### What would you like?

As discussed internally at Cypress, we would like to support a new command, `cy.attachFile()`. For the very first implementation, we will support only directly passing in Buffers and Buffer-like objects (or an array of them) - basically, those that can be passed directly into the [`File` constructor](https://developer.mozilla.org/en-US/docs/Web/API/File/File).

Reading data from fixtures, aliases and file paths will be done in a follow-up pull request, as well as drag-n-drop mode. See #18753 and #18754.

### Why is this needed?

This is the minimal unit of work to have something that can actually be played with in the browser, and tested against a variety of file uploading frameworks. If we've missed anything that requires rethinking the spec, we'll find it at this stage, stripped of as many features as possible.

**Comment by x-yuri** [comment]
The technical brief is not available (404). The same in the other 2 issues.

**Comment by BlueWinds** [comment]
Apologies, removed the broken link from all three. I'll add more exact details of our implementation here when we start work on it.

**Comment by BlueWinds** [comment]
For anyone following along at home - this did not go out in 9.1, we had some confusion with github tags.
