### ISSUE TITLE
Add interaction steps to upgrade and remove protractor

### ISSUE THREAD

**Issue by hantsy** [cypress-io/cypress#18769]
### What would you like?

The `ng update @cypress/schematic` add Cypress to replace the original Angular protractor,  if there is some steps or standalone commands to convert the protractor config/tests to cypress, and remove the Protractor from projects, it is more friendly for Angular developers. 

### Why is this needed?

More friendly for Angular develoeprs to migrate to Cypress.

**Comment by jordanpowell88** [comment]
Hey @hantsy, thanks for your feedback. Have you read through our Protractor Migration Guide found [here](https://docs.cypress.io/guides/migrating-to-cypress/protractor#Introduction)

**Comment by hantsy** [comment]
Thanks @jordanpowell88 , it is very helpful. But I have tried `ng add` command, it did not remove the existing Protractor from *package.json*.

**Comment by jordanpowell88** [comment]
@hantsy I am glad that the Protractor Migration Guide was helpful. We will also be releasing a Protractor migrator very soon as well that should help folks migrating. Please be on the lookout for that news.

In regards to the schematic, we decided that we did not want to remove the current Protractor dependency as a part of the schematic.  Many users who are migrating will need both Cypress and Protractor to coexist at the same time.
