### ISSUE TITLE
percySnapshot - TypeError: Cannot read properties of undefined (reading 'isTTY')

### ISSUE THREAD

**Issue by ayaanqui** [cypress-io/cypress#18760]
### Current behavior

Running `percy exec -- cypress run` gives me the following errors:
```
TypeError: Cannot read properties of undefined (reading 'isTTY')
      at PercyLogger.write (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:5511:27)
      at PercyLogger.log (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:5498:12)
      at Object.isPercyEnabled (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:5839:11)
      at async Context.eval (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:5148:10)
```
I was able to narrow down where the error/failed tests were stemming from, and it looks like all my tests pass if I comment out lines where I'm using `percyScreenshot`. The odd thing is that running `cypress open` works fine and passes all tests as expected.

### Test code to reproduce

The error occurs exactly at line `7`, so removing/deleting that line (`cy.percySnapshot(...`) results in a passing test.
```ts
const screenWidths = [375, 768, 1280]

describe("ordering stocks", () => {
  it("should visit homepage", () => {
    cy.visit("/")
    cy.findByText(/My text/)
    cy.percySnapshot("DSC homepage", { widths: screenWidths })
  })
})
```

### Cypress Version

8.7.0

**Comment by alexbjorlig** [comment]
I have this exact same issue - looking very much forward to possilbe solutions/workaorounds

**Comment by jennifer-shehane** [comment]
It seems this error is throwing from the percy plugin, and not Cypress itself. Have you tried opening an issue with Percy? https://github.com/percy/percy-cypress

**Comment by ayaanqui** [comment]
@jennifer-shehane Thanks for responding. @alexbjorlig I did post a similar issue on [percy/precy-cypress](https://github.com/percy/percy-cypress). Here's the link to the issue if you are interested [https://github.com/percy/percy-cypress/issues/430](https://github.com/percy/percy-cypress/issues/430)

**Comment by Robdel12** [comment]
This _might_ be a Percy issue but it's more likely to be an issue with a pre-processor not respecting the `browser` field in `@percy/logger`'s `package.json`. 

What pre-processor is being used for your cypress projects?

**Comment by emilyrohrbough** [comment]
Per responses https://github.com/percy/percy-cypress/issues/430#issuecomment-1211147131, this issue was a dependency resolution error.
