### ISSUE TITLE
DevTools failed to load source map: Could not load content HTTP error: status code 404

### ISSUE THREAD

**Issue by valeria-chernikova** [cypress-io/cypress#18773]
### Current behavior

When trying to navigate to the page receive an error in Console:
"DevTools failed to load source map: Could not load content for .../angular.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"

There is no issue in Chrome. 

### Test code to reproduce

I just visit the page and login. 

### Cypress Version

8.6.0

**Comment by flotwig** [comment]
Sounds like the source map does not exist in prod. Since this is not a problem with Cypress, closing.
