### ISSUE TITLE
[tests] Investigate Percy Build Timeouts

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#18774]
### Current behavior

The following CI error can arise and the cause is unknown. This cause jobs to be flaky.

![Screen Shot 2021-11-03 at 8 54 56 AM](https://user-images.githubusercontent.com/14099737/140077843-2e63c4e6-248c-4f84-8675-f3de8544fee3.png)

### Desired behavior

Percy snapshots are successfully uploaded when parallel builds complete.

### Test code to reproduce

Example failure: https://app.circleci.com/pipelines/github/cypress-io/cypress/26009/workflows/09201cea-c797-4827-954a-8d96abac4af7/jobs/978435

### Dependency Versions

cypress@8.7.0
@percy/cli@1.0.0-beta.48 <-- latest version is 1.0.0-beta.70. 
@percy/cypress@3.1.0

**Comment by mjhenkes** [comment]
We believe that this issue was fixed by this commit: https://github.com/cypress-io/cypress/commit/99c8d466c8dc675b381a98d5a16c50f05232dc78

The previous circle job was missing a comma and since the 9.0.0 release this hasn't be seen.
