### ISSUE TITLE
On dashboard Cypress, I am not redirected to the right Test Results section when clicking on one Spec file if a failed test exist

### ISSUE THREAD

**Issue by rwralitera** [cypress-io/cypress#18775]
### Current behavior

Given I am on dashboard cypress
And I am on "Specs" tab
When I click on one spec file WITH Test Failed inside
Then I am redirected to "Test Results" tab
And I do NOT see ONLY the Scenarios related to the Spec file

### Desired behavior

Given I am on dashboard cypress
And I am on "Specs" tab
When I click on one spec file WITH Test Failed inside
Then I am redirected to "Test Results" tab
And I see ONLY the Scenarios related to the Spec file

### Test code to reproduce

Given I am on dashboard cypress
And I am on "Specs" tab
When I click on one spec file WITH Test Failed inside
Then I am redirected to "Test Results" tab
And I see ONLY the Scenarios related to the Spec file

### Cypress Version

8.4.1

**Comment by jennifer-shehane** [comment]
@rwralitera I'm not seeing this behavior. You can click on the link below to follow my recreation.

1. I navigate to Specs tab: https://dashboard.cypress.io/projects/4b7344/runs/21488/specs
2. I click on the row saying `2-advanced-examples/actions.spec.js` (the one with failures)
3. I am redirected to [this url](https://dashboard.cypress.io/projects/4b7344/runs/21488/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%222-advanced-examples%2Factions.spec.js%22%2C%22value%22%3A%22%5B%5C%22887903e5-1531-4575-9f10-f48a1a8f6302%5C%22%5D%22%7D%5D&statuses=%5B%5D), which only shows the test results of the specfile I clicked on.

Do you not have this same behavior? What browser are you using?

**Comment by rwralitera** [comment]
I found the problem last week and I think that I used a firefox which is not updated :-).
<img width="790" alt="image" src="https://user-images.githubusercontent.com/35451879/140084847-72909138-61f7-4eb9-b081-6fbe6f620f82.png">

**Comment by rwralitera** [comment]
It works better now, you can close the issue. Sorry for the misdiagnosis.
