### ISSUE TITLE
Test does not set cookies when visiting SSO

### ISSUE THREAD

**Issue by JDansercoer** [cypress-io/cypress#18779]
### Current behavior

Currently we have this test

```
describe('Log in', () => {
  it('Is able to correctly log in', () => {
    cy.visit('/');

    cy.get('#login__email').type('email');
    cy.get('#login__password').type('
');

    cy.get('#login__submit').click();
  });
});
```

- When the tests visits `/` (with `"baseUrl": "http://localhost:3000"`), the application get redirected to the SSO link. 
- This link is something akin `https://sso.test.ourcompany.com/oauth2/auth?response_type=code&client_id=...`. 
- This link returns a `302` and this is one of the headers `Set-Cookie: oauth2_authentication_csrf_insecure=MTYzNTk1ODYyNHxEdi1CQkFdwez0SUFBUkFCRUFBQVB2LUNBQUVHYzNSeWFXNW5EQVlBhsdweNtWUdjM1J5YVc1bkRDSUFJRFpoTqgwdNR1kwWlRSaVpUaGhZdweT1RJMFpEZ3daamhqTWpaaXwLf_M7lconouX1tJr2qNWPSZam4-FgV04siS9NIp4esA==; Path=/; HttpOnly; SameSite=Lax`
- The final redirected link is `https://auth.test.ourcompany.com/login?login_challenge=900667`.
- Here we fill out email and password, and click login.
- We get the error `No CSRF value available in the session cookie.`

When looking further into it, when checking the cookies, we see that the `oauth2_authentication_csrf_insecure` cookie is **not set**, resulting in the error.

### Desired behavior

Have the cookie returned by the `302` available to the application

### Test code to reproduce

Not sure how to provide test code that integrates with our SSO setup.

### Cypress Version

8.7.0

### Other

I have a hunch that this has something to do with the properties of the cookie, but I can't directly figure it out.

Especially since, whatever the cause is, is not happening when using whatever browser (Chrome, Edge, ...), even when disabling third-party cookies.
We also tried Playwright and have no issues there as well.

Is there some kind of hidden Cypress setting that we are missing?

**Comment by FDIM** [comment]
I have the same or very similar issue. The flow us is:
- open main app on domain X
- click a link that leads to another app on domain Y
- do few actions there to login and then click a button to SSO back to main app
- user is redirected to one of the APIs under domain X
- this API sets few cookies and adds Location header that points to main app root (with access token in fragment)
- app loads and no cookies are set

**Comment by kemmis** [comment]
It seems like chromeWebSecurity=false no longer works with recent versions of chrome. It was working for me about a month ago with with Cypress 8.6. But now it's not working with Chrome 95, or 96.

**Comment by AtofStryker** [comment]
Hi @JDansercoer. have you tried you OAuth2 flow with `cy.origin()` enabling the `experimentalSessionAndOrigin`? This should correctly set your sessionId Token. I might be absent in the browser, but it should persist in the proxy layer of cypress. Would you be willing to give it a try in a version at or above `10.11.0`?

**Comment by RareSecond** [comment]
Sorry @AtofStryker, I switched to Playwright for all my projects and clients

**Comment by AtofStryker** [comment]
@JDansercoer that is disappointing to hear, but very understandable considering this issue has been open for a little over a year with little to no feedback. If you are ever interested in trying Cypress again with the new features we have added, please let us know. We'd love to have you back in the community!
