### ISSUE TITLE
cypress browser electron crashed when click element skipping to new page

### ISSUE THREAD

**Issue by syy1023** [cypress-io/cypress#18799]
### Current behavior

Cypress version: 8.7.0
Browser: Electron

Description: 
when locate an element and skip to a new page, the driver crashed.
It seems to open a new window  out of cypress electron

Logs:
Error: ERR_ABORTED (-3) loading 'https://xxxxx&redirect_uri=http://xxxxx'
    at rejectAndCleanup (electron/js2c/browser_init.js:161:7486)
    at Object.navigationListener (electron/js2c/browser_init.js:161:7792)
    at Object.emit (events.js:376:20)

### Test code to reproduce

describe('test',()=>{
...
cy.contains("monitor").click()
   
.....
})

### Cypress Version

8.7.0

**Comment by BlueWinds** [comment]
Can you provide a more thorough code sample, or a github repo we can clone that shows the issue? With the information provided - and no other details - I can't reproduce what you ran into.

For example,
```js
cy.document().then(doc => {
      doc.body.innerHTML = `
        <a somePropertiesCausingAnIssue>Foo</a>
      `
    })
    cy.get('a').click()
```

**Comment by Bassadin** [comment]
This issue seems pretty old but I'm running into a similar one. I'm trying to click on a link with `target="_blank"` and it opens in a seperate Electron window whereafter cypress just crashes. the log says:

```
Error: ERR_ABORTED (-3) loading 'http://localhost/anleitung/startseite.htm'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.navigationListener (node:electron/js2c/browser_init:165:7792)
    at Object.emit (node:events:394:28)
 {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'http://localhost/anleitung/startseite.htm'
}
Error: ERR_ABORTED (-3) loading 'http://localhost/anleitung/startseite.htm'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.navigationListener (node:electron/js2c/browser_init:165:7792)
    at Object.emit (node:events:394:28)

The terminal process "C:\Windows\System32\cmd.exe /d /c npm run cypress" terminated with exit code: 1.
```

**Comment by BlueWinds** [comment]
@Bassadin - Is this sample test causing the crash for you?

```js
it('passes', () => {
  cy.document().then(doc => {
    doc.body.innerHTML = `
      <a href="/foobar" target="_blank">Foo</a>
    `
  })
  cy.get('a').click()
})
```

On my linux machine it results in a new browser window opening and the test passing. If this does crash, that'll be super useful to know (and we can guess it's probably a windows specific issue) - if not, can you update it somehow to show the behavior?

**Comment by Bassadin** [comment]
@BlueWinds will try tomorrow and update you :)

**Comment by Bassadin** [comment]
Hm, no, your example works for me. The test in my project that causes the crash seems to work too, but after Cypress tries to close the window, the crash occurs, I believe. The error message is the same as I posted above:

```
Error: ERR_ABORTED (-3) loading 'http://localhost/anleitung/startseite.htm'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.navigationListener (node:electron/js2c/browser_init:165:7792)
    at Object.emit (node:events:394:28)
 {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'http://localhost/anleitung/startseite.htm'
}
Error: ERR_ABORTED (-3) loading 'http://localhost/anleitung/startseite.htm'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.navigationListener (node:electron/js2c/browser_init:165:7792)
    at Object.emit (node:events:394:28)
```

Unfortunately, I cannot easily share the code I'm working in because it's for the company I work at. If I can help you with any data about my environment, I'd be happy to help, though. :)

**Comment by nikhilesh009** [comment]
That's interesting, i believe your app doesn't have an anchor tag and it generates a dynamic URL, in that case, it will crash. try to use something 
```js
it('opens the about page', () => {
  cy.visit('index.html')
  cy.window().then(win => {
    cy.stub(win, 'open').callsFake((url, target) => {
      expect(target).to.be.undefined
      // call the original `win.open` method
      // but pass the `_self` argument
      return win.open.wrappedMethod.call(win, url, '_self')
    }).as('open')
  })
  cy.get('a').click()
  cy.get('@open').should('have.been.calledOnceWithExactly', '/about.html')
})
```
https://glebbahmutov.com/blog/cypress-tips-and-tricks/  it might help

**Comment by Elli143** [comment]
I'm running into this problem after upgrading from Cypress 9.6 to Cypress 10.8. Cypress completely crashes when a test clicks on a link that opens a new tab in Electron. Runs fine in Chrome. Prior to the upgrade there was no crash for the same test in Electron.

**Comment by kate-mashkina** [comment]
Same - currently on 10.1.0 and headless electron mode runs just fine, however starting from 10.2.0 it will crush. Now I really like to upgrade to version past 10.2.0 as it includes the fix for https://github.com/cypress-io/cypress/discussions/22128 - so having a crushing test is blocker for us, unfortunately

**Comment by Yangfan2016** [comment]
+1

**Comment by stepanroznik** [comment]
Same - this used only used to cause crashes in headed Electron in Cypress 9.7 but since upgrading to 10.11 it also crashes in headless.

**Comment by camiloesub** [comment]
+1
