### ISSUE TITLE
Add CLI option to system-tests

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#18795]
### What would you like?

I'd like to be able to have the option to run my system tests through the CLI. 

Basically we should add a `useCli` option, so that it spawns the `cli` instead of `server`.

### Why is this needed?

There are some options that are injected via the CLI that have to be manually injected with our current setup. This change would allow us to give situations like these a full end to end test.

**Comment by BlueWinds** [comment]
@tgriesser - I remember back in https://github.com/cypress-io/cypress/pull/18719 you had discussed planning some work about using the CLI more directly in system tests. Just want to make sure we don't have duplicate tickets, or you haven't already started this in another branch. :)
