### ISSUE TITLE
Configuration to force test to fail if an url is not mocked

### ISSUE THREAD

**Issue by bluepioupiou** [cypress-io/cypress#18794]
### What would you like?

Be able to set a variable to tell that I want that a test fail if there is a call to an external resource that is not mocked

### Why is this needed?

I want this because some times, when my devs code some tests, they still have the back running and the test will pass locally but not on the CI after. And, when a dev add a new API on the back called by the front, I want to force them to at least mock it empty in cypress to prevent longer test because they try to reach unexisting routes

### Other

I'm trying to perfect tests where everything is mocked to control what we do and how the application will react

**Comment by bluepioupiou** [comment]
Any comment on this idea ? good ? bad ? won't do ? ^^ Anyone else interested ?

**Comment by TomasChmelik** [comment]
Good idea IMO. We added some additional requests after writing tests. The test are still succeeding, but application console is screaming bloody murder from all the errors.

It might be possible to intercept URL `*` and cause test to fail if it is called. Depends on if intercept itself can cause test to fail and if cypress tries to find intercept with longest match in the URL (instead of just first match for example).

**Comment by TomasChmelik** [comment]
Possible solution is to use stubs with beforeEach and afterEach in cypress/support/index.js

```
beforeEach(() => {
  const notMockedRequests = cy.stub().as('notMockedRequests')
  cy.intercept('https://url.of.your.backend/**', notMockedRequests)
})

afterEach(() => {
  cy.get('@notMockedRequests')
    .then(stub => cy.wrap(stub.getCalls().map(call => call.args[0].url).join(', ')))
    .should('be.empty')
})
```

**Comment by bluepioupiou** [comment]
Hmmm good idea, i'll try that soon and will get back to you

**Comment by FabianUntermoser** [comment]
Hi @bluepioupiou! Im trying to triage issues here. 
Is this still an issue for you or has the workaround suggested by @TomasChmelik worked for you? If it still persists, I suggest consider adding the label `topic: network` to it. Otherwise maybe we can close the issue. Thanks.

**Comment by TomasChmelik** [comment]
The only problem I had with my workaround is that once one afterEach fails the entire test battery is cancelled. Is there a way to say Cypress to continue testing even if "this" `afterEach` fails?

**Comment by bluepioupiou** [comment]
The workaround is enough for me, I like the fact that, when you forgot to mock a route, everything will fail.

**Comment by jsphstls** [comment]
This ended up being my solution in a support file. The `headers` usage is the cleanest way of differentiating between static file requests and authenticated data requests for my specific application.

```
beforeEach(() => {
  cy.intercept(
    {
      url: '/**',
      headers: {
        Authorization: 'Bearer' 
      }
    },
    req => { throw new Error('Request not mocked: ' + req.url) }
  ).as('Needs intercept')
)}
```

I prefer to fail the test right away vs evaluating in an `afterEach`.

**Comment by dpage-mdsol** [comment]
> Possible solution is to use stubs with beforeEach and afterEach in cypress/support/index.js
> 
> ```
> beforeEach(() => {
>   const notMockedRequests = cy.stub().as('notMockedRequests')
>   cy.intercept('https://url.of.your.backend/**', notMockedRequests)
> })
> 
> afterEach(() => {
>   cy.get('@notMockedRequests')
>     .then(stub => cy.wrap(stub.getCalls().map(call => call.args[0].url).join(', ')))
>     .should('be.empty')
> })
> ```

This is a great workaround. Only issue I found with it is if I have "before()" hooks in my Cypress tests these "beforeEach()" hooks in the support/index.js file occasionally run after the cy.intercepts in the tests. I think it's an async issue.

**Comment by LiviuTrifoi** [comment]
The local cypress runner detects if a call was mocked or not and places either a hollow or full circle.
The way it does it is via Cypress.ProxyLogging.proxyRequests.
You can add the code below to either an individual file or to your support.ts if you want it for all tests.

```
afterEach(() => {
    console.log((Cypress as any).ProxyLogging.proxyRequests);
    const callsNotMocked = (Cypress as any).ProxyLogging.proxyRequests
        .filter((req: any) => !req.flags?.stubbed)
        .map((req: any) => req.preRequest?.method + ' ' + req.preRequest?.url);
    // you can add aditional filters and exclude  /assets or static routes if you want

    const callsNotMockedStr = callsNotMocked.join(' \n');
    throw Error(`The following requests are not mocked: ${callsNotMockedStr }`);
});
```
