### ISSUE TITLE
Auto reload when other files than spec has been saved

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#188]
Currently the test runner reruns when you modify and save a spec file.

I like keep my code clean, so I move a lot of stuff to support files (by creating Commands). However, when I modify and save a support file, the tests are not re-running.

To extend this a bit, I also would like to auto reload when the src is changing (watching the `baseUrl` config parameter?).
Even better, a configuration parameter to set up a 'watch list' using globs would be awesome.

**Comment by jennifer-shehane** [comment]
Closing in favor of #456 which defines more specific implementation details.
