### ISSUE TITLE
 CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete. at

### ISSUE THREAD

**Issue by Arunk28** [cypress-io/cypress#18801]
### Current behavior

Offen getting this issue.
CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete. at 

### Desired behavior
the error should not come because of this test is failing 
_No response_

### Test code to reproduce

am always getting this issue now continuously. in 8.6.0 version

### Cypress Version

8.6.0

**Comment by szamanr** [comment]
duplicate of: #18778

**Comment by BlueWinds** [comment]
Closing in favor of #18778, which has more information about the same issue.
