### ISSUE TITLE
URLs are parsed with formatting rules before display

### ISSUE THREAD

**Issue by JamShady** [cypress-io/cypress#18800]
### Current behavior

I have an API endpoint for my app to load Cypress fixtures located at `/__cypress__/fixtures`

When an error occurs, instead of displaying `http://localhost/__cypress__/fixtures` as the request, Cypress perform text formatting on the URL and uses the double-underscores to convert 'cypress' into bold, now presenting `http://localhost/cypress/fixtures` with 'cypress' in bold

![image](https://user-images.githubusercontent.com/167395/140506297-80f888ee-abb0-40c0-bb05-2339d01f44a2.png)

### Desired behavior

Cypress should not be parsing the URL and should display it literally/correctly as `http://localhost/__cypress__/fixtures`

### Test code to reproduce

`cy.request({ url: '/__cypress__/fixtures' })`

### Cypress Version

8.7

**Comment by jennifer-shehane** [comment]
This is due to our display of errors utilizing markdown, so it's formatting it via markdown. This just affects the display of the url and would not affect the actual url it is attempting a request on.
