### ISSUE TITLE
yarn 3: Install not working

### ISSUE THREAD

**Issue by amuttsch** [cypress-io/cypress#18819]
### Current behavior

I'm using cypress with yarn 3 and in my CI pipeline I added the `CYPRESS_CACHE_FOLDER` environment variable to install the binaries to a folder that is cacheable.

However, after the `yarn install`, the binary is not installed in the path set but in the global folder. This leads to cypress not opening.

Installing it with `yarn dlx cypress install` downloads cypress in the folder set by the `CYPRESS_CACHE_FOLDER` enviromnent variable, however if fails to start with the following error:

```
Error: Your application tried to access graceful-fs, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

Removing the cache folder environment variable and doing a fresh install fixes the problems and cypress runs fine.

### Desired behavior

`yarn install` should honour the `CYPRESS_CACHE_FOLDER` environment variable and, if installed there, be able to run.

### Test code to reproduce

Checkout the repo: https://github.com/amuttsch/cypress-test-tiny

```
git clone https://github.com/amuttsch/cypress-test-tiny.git
```

Run the following commands:

```
CYPRESS_CACHE_FOLDER=.cy-cache yarn install
yarn cypress:open
```

To trigger the 2nd error execute the following commands:

```
CYPRESS_CACHE_FOLDER=.cy-cache yarn dlx cypress install
yarn cypress:open
```

### Cypress Version

8.7.0

**Comment by flotwig** [comment]
Some users are also seeing this without CYPRESS_CACHE_FOLDER, just with Yarn v3.

**Comment by danielsilva** [comment]
FYI

I am on Cypress 12.1.0 with Yarn 3.2.3 and am encountering the same issue on my CI build where the install and specs steps run separately. 

The workaround is to run `yarn dlx cypress@12.1.0 install --force` right before running the specs.
