### ISSUE TITLE
Not able to use Chrome in Cypress

### ISSUE THREAD

**Issue by theonemartian** [cypress-io/cypress#18816]
### Current behavior

I am not able to use chrome browser in cypress, Any help will be appreciated thanks
I tried commands like
npx cypress open --browser chrome and other commands too.
here is a screenshot of the problem, as you can see there is only electron browser.
![image](https://user-images.githubusercontent.com/48899770/140739789-2ab78f09-6c0f-4bf2-a009-fbc10f246b3c.png)

### Desired behavior

I should get options for chrome and other browsers which I am not getting

### Test code to reproduce

![image](https://user-images.githubusercontent.com/48899770/140739999-dc46e02a-27e6-4868-a978-575b4c0930a8.png)

### Cypress Version

8.7.0

**Comment by jennifer-shehane** [comment]
- Can you run `cypress info` and print the results here? 
- Likely we can't find the installed Chrome browser on your system. Did you rename it or move it somewhere on your system?

Try reading through our [troublshooting on launching browsers](https://docs.cypress.io/guides/references/troubleshooting#Launching-browsers).

**Comment by fdc80** [comment]
![image](https://user-images.githubusercontent.com/7305475/141425912-1dc1472d-c898-4a73-b082-5bf8c4e1e4dd.png)

This is my cypress info
Not working with Chrome

**Comment by theonemartian** [comment]
> * em. Did you rename it or move it somewhere on your syste

**Comment by fdc80** [comment]
UPDATE
After a computer restart it works for several times. Then something goes wrong, and "There was an error reconnecting to the Chrome DevTools protocol. Please restart the browser." red advice appears.
Obviuosly I tried to restart both Chrome and Cypress, close every app/process from task manager, but only a machine restart makes Chrome work with Cypress, until something breaks it out again. 
Firefox, Electron and Edge work.
