### ISSUE TITLE
Intercepted response is not yielded properly in recursive funcion

### ISSUE THREAD

**Issue by PALLY27** [cypress-io/cypress#18828]
### Current behavior

![image](https://user-images.githubusercontent.com/16815519/140834628-63dd06ac-6650-4f49-8059-f8eddb39895f.png)

in first calling of my interceptor, there is not my deisred object in yielded data (200 items) - that's ok, because new object appear after the while

In second calling, object is present on site, so in yielded data too (201 items)
![image](https://user-images.githubusercontent.com/16815519/140834995-8113e3b0-ad14-4df7-ba24-293cc1a097b0.png)

So I finding index of my new object placed in the yielded data, by recursive function.
As you see, I'm waiting on my list, then I  yield respose body data to property, then I finding the index :
![image](https://user-images.githubusercontent.com/16815519/140835304-acfeb81b-90be-4c37-8613-fe3e9801bfcd.png)

Unfortunaltely, my index has still value from first call of cy.wait('@alias') "-1", when my object was notpresent.  

### Desired behavior

So I finding index of my new object placed in the yielded data, by recursive function.

As you see, I'm waiting on my list, then I  yield respose body data to property, 
then I finding the index :

Unfortunaltely, my index has still value from first call of cy.wait('@alias') "-1", when my object was not present.  

My Desired behavior is that batchListData yielded array , should be rewrited after new call from recursive.
Seems like not

### Test code to reproduce

```
cy.intercept('POST', '/ibs/batch-payments/search').as('batchList');

const checkState = () => {
        cy.wait('@batchList').its('response.body.data').then((batchListData) => {
            newPaymentObj.batchIndex = batchListData.findIndex(x => x.packageId === (newPaymentObj.draftPackageId + 1));

            console.log("kukaj hen tu >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
            console.log(newPaymentObj.batchIndex);

            if (newPaymentObj.batchIndex === -1) {
                batchListPage.buttonRefresh.click();
                delete newPaymentObj.batchIndex;
               
                checkState();

            } else {
                newPaymentObj.packageId = newPaymentObj.draftPackageId + 1;
            }

        });
    };

checkState();
```

### Cypress Version

8.7.0

**Comment by bahmutov** [comment]
I think you can implement it using cypress-recurse
