### ISSUE TITLE
Internal: Fix flaky tests in circle CI

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#18822]
### Current behavior

We currently have several flaky tests that need to be retried several times to pass.

### Desired behavior

Cypress tests should not be flakey and offer 

### Test code to reproduce

Submit a PR to cypress and watch the circle ci build.

We can identify the flaky tests to focus on by using the cypress flak report: https://dashboard.cypress.io/projects/ypt4pf/analytics/flaky-tests

and circle CI's report: https://app.circleci.com/insights/github/cypress-io/cypress/workflows/linux/tests?branch=develop&reporting-window=last-30-days

### Cypress Version

n/a

**Comment by mjhenkes** [comment]
settings spec flaky test fix: #18979

**Comment by davidmunechika** [comment]
PR to fix flaky net stubbing, websocket, proxy logging, and Firefox system tests: https://github.com/cypress-io/cypress/pull/19159

**Comment by ryanthemanuel** [comment]
PR for system-tests-firefox screenshot fix: #20260 
PR for server-performance-tests screenshot fix: #20271

**Comment by rachelruderman** [comment]
Closing since we're taking care of flaky tests as part of Firewatch duties 🔥
