### ISSUE TITLE
Quitting Cypress does not also quit the running browser

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#18827]
### Current behavior

Starting in Cypress 8.3.0, when quitting Cypress (using cmd + q or clicking the x button to close) will not close the browser that is running with Cypress. 

### Desired behavior

Previously closing Cypress would also quit the browser process - this is the desired behavior.

### Test code to reproduce

- `cypress open`
- Click a spec to open in Chrome
- Focus the Desktop-gui
- Type cmd+q

### Cypress Version

8.3.0

**Comment by emilyrohrbough** [comment]
Look like this should have been fixed in https://github.com/cypress-io/cypress/pull/19322
