### ISSUE TITLE
Cypress fails smoke test upon initial startup (WSL2/Windows 10)

### ISSUE THREAD

**Issue by raphaelspies** [cypress-io/cypress#18839]
### Current behavior

When opening Cypress, I get the following error message:
```
Command timed out after 30000 milliseconds: /home/raphaelspies/.cache/Cypress/8.7.0/Cypress/Cypress --no-sandbox --smoke-test --ping=557
Timed out
```

### Desired behavior

Open and run

### Test code to reproduce

[My fork of cypress-test-tiny](https://github.com/raphaelspies/cypress-test-tiny)

### Cypress Version

8.7.0

### Other

My current setup: Windows 10 machine running WSL2 with Ubuntu 20.04.
Prior to installing Cypress on a local project, I followed the instructions [from this medium article](https://shouv.medium.com/how-to-run-cypress-on-wsl2-989b83795fb6)

Next, I installed Cypress on a local project using `npm install --save-dev cypress`. However, when opening it, I get the following error message:
```
Command timed out after 30000 milliseconds: /home/raphaelspies/.cache/Cypress/8.7.0/Cypress/Cypress --no-sandbox --smoke-test --ping=557
Timed out
```

I followed instructions from [issue #4624](https://github.com/cypress-io/cypress/issues/4624) by running `DEBUG=cypress:* npx cypress verify` and noticed the following error message right before the timeout: 

```
cypress:cli error message: 2021-11-09T07:37:00.390Z cypress:ts Running without ts-node hook in environment "production"
```

**Comment by SindreSvendby** [comment]
Are you sure VcXsrv is running? I had the same problem after restarting, before I realized that I had not started the service! I would recommend you to verify that each step is working correctly and see if it works :)
