### ISSUE TITLE
Invalid arch info in `require('os').arch()`

### ISSUE THREAD

**Issue by 0x009922** [cypress-io/cypress#18837]
### Current behavior

On **macOS 11.4 20F71 arm64** I am getting `x64` arch inside of Cypress' plugin environment (i.e. in `cypress/plugins/index.js`), but in any other script I am getting the correct `arm64`.

```js
// cypress/plugins/index.js

const os = require('os')

module.exports = (on, config) => {
  throw new Error(os.arch()) // throws `x64` instead of `arm64`
}
```

### Desired behavior

Cypress should provide correct system information.

### Test code to reproduce

Here is a reproduction: https://github.com/0x009922/cypress-issue-invalid-os

### Cypress Version

8.7.0

### Other

It breaks usage of `esbuild@^0.13.0` with "optionalDependencies" installation strategy (see https://github.com/evanw/esbuild/issues/789). `pnpm` installs correct `esbuild-darwin-arm64` and it works outside of Cypress, but when `esbuild` tries to build something in plugin (e.g. in `cypress-esbuild-preprocessor`) it tries to resolve `esbuild-darwin-x64` package according to `os.arch()`, and it fails. Apparently, this is not a bug of esbuild, but of Cypress.

**Comment by jennifer-shehane** [comment]
Are you using the default `nodeVersion` in Cypress? It defaults to the bundled Node version, does this behavior change if you set it to use `system`?

**Comment by 0x009922** [comment]
@jennifer-shehane, yes, setting `nodeVersion` to `system` changed behaviod to the desired.
I consider this issue is closed. Thank you!
