### ISSUE TITLE
baseUrl can't be set from env variables in Configuration API

### ISSUE THREAD

**Issue by lexith** [cypress-io/cypress#18847]
### Current behavior

I want to set the baseUrl from my environmental variables by running cypress via an npm script like `cypress open --env PROXY_HOST=https://localhost`. i can access this variable successfully with configuration API and update the cypress config, but it doesn't work if i want to use it to set a new baseUrl (see "Test code to reproduce").

![weird](https://user-images.githubusercontent.com/1146312/140934781-5b9519ec-7c47-475d-b94f-aec98842b9e0.PNG)

### Test code to reproduce

    cypress open --env PROXY_HOST=https://localhost
    
    module.exports = (on, config) => {
         const { PROXY_HOST } = process.env; // e.g. https://localhost

         config.env.PROXY_HOST = PROXY_HOST; // <------- this is set correctly
         config.baseUrl = 'https://localhost/some/target'; // <------- this works
         config.baseUrl = `${PROXY_HOST}/some/target`; // <------- this doesn't work

         return config;
    };

### Cypress Version

8.7.0

**Comment by bahmutov** [comment]
You are confusing `--env` parameter - it does NOT set the values into the `process.env` object, instead it sets the values into the Cypress' own `env` object. In your case, you would see the proxy by accessing it from the `config.env`. So it should be:

```
cypress open --env PROXY_HOST=https://localhost

module.exports = (on, config) => {
     const { PROXY_HOST } = config.env; // e.g. https://localhost

     config.baseUrl = `${PROXY_HOST}/some/target`;

     return config;
};
```
And no need to set it back into `config.env` as it was set

**Comment by lexith** [comment]
Oh my god. Thank you. Which means in my example i actually set `config.env.PROXY_HOST` to undefined because it doesn't exist. But i didn't get an error for that, only for the baseUrl (which makes sense) and i did not understand.
Testing with two different shells, one where `PROXY_HOST` is set in env and one where it is not...That added to my confusion. 

Thanks again.

**Comment by osifo** [comment]
> You are confusing `--env` parameter - it does NOT set the values into the `process.env` object, instead it sets the values into the Cypress' own `env` object. In your case, you would see the proxy by accessing it from the `config.env`. So it should be:
> 
> ```
> cypress open --env PROXY_HOST=https://localhost
> 
> module.exports = (on, config) => {
>      const { PROXY_HOST } = config.env; // e.g. https://localhost
> 
>      config.baseUrl = `${PROXY_HOST}/some/target`;
> 
>      return config;
> };
> ```
> 
> And no need to set it back into `config.env` as it was set

This was very helpful. thank you!
