### ISSUE TITLE
Selector playground omits quotes for preferred data- attribute selectors

### ISSUE THREAD

**Issue by silversteez** [cypress-io/cypress#1884]
### Current behavior:

When using selector playground to select elements with preferred data attributes (data-cy, data-test, data-testid), the provided selector is missing quotes around the value. The selector then fails to .get() the desired element during test. 

Any other data- attribute works correctly.

### Desired behavior:

Preferred data- attribute selectors should have quotes around the value

### Steps to reproduce:

Use selector playground to select any element with a data-test="whatever" attribute

### Versions
Cypress 3.0.1, Mac Os 10.12.5, Electron 59

**Comment by brian-mann** [comment]
I believe there is a check that tests whether or not the quotes are necessary - and only conditionally adds them.

Can you provide an example / code / screenshot / whatever to show the behavior you're describing?

**Comment by silversteez** [comment]
#### Here are a few screenshots of the DOM and results offered by selector playground:

<img width="649" alt="screen shot 2018-06-05 at 3 14 20 pm" src="https://user-images.githubusercontent.com/3078902/41005658-484d92ac-68d3-11e8-8c3e-2d95572e9740.png">
<img width="532" alt="screen shot 2018-06-05 at 3 14 10 pm" src="https://user-images.githubusercontent.com/3078902/41005657-47e564a2-68d3-11e8-879b-39bd380ea470.png">
<img width="235" alt="screen shot 2018-06-05 at 3 14 28 pm" src="https://user-images.githubusercontent.com/3078902/41005659-486c424c-68d3-11e8-9c9e-d3f92f8d5063.png">

#### Any non-preferred data- attribute includes the quotes:

<img width="456" alt="screen shot 2018-06-05 at 3 17 08 pm" src="https://user-images.githubusercontent.com/3078902/41005739-900a6228-68d3-11e8-8724-15eeee9110bc.png">

**Comment by chrisbreiding** [comment]
Looks like this is only an issue in electron. Chrome has no problem with `cy.get('data-test=add-attribute-button]')`. @brian-mann Do you recall the reason for [this change](https://github.com/cypress-io/unique-selector/commit/ea73a06c9a6436d0ff4da0f62b485fabb4bf1ff3#diff-e4b981f973273012bb8f82e76d8d7246R11)? Any reason not to quote all attribute values?
