### ISSUE TITLE
Typescript: 3.0.1 lib type compile fail.

### ISSUE THREAD

**Issue by kingfolk** [cypress-io/cypress#1885]
### Current behavior:
```
...
ERROR in ... node_modules/@types/sinon-c  hai/node_modules/@types/sinon/index.d.ts(489,36)
TS1005: ';' expected.
```

where i found

```
type SinonStubbedMember<T> = T extends Function ? SinonStub : T;
```

seem to relate to typescript version. Current version 2.4.2. If upgrade to ~2.8.0, the error is gone.

try to use `skipLibCheck` to avoid lib check but seems not work.

tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "../node_modules",
    "module": "commonjs",
    "target": "es5",
    "skipLibCheck": true,
    "lib": ["es5", "dom"]
  },
  "include": [
    "**/*.ts",
    "../node_modules/cypress"
  ]
}
```

### Steps to reproduce:

following recipe here https://github.com/cypress-io/add-cypress-custom-command-in-typescript

### Versions

os: macOS 10.12.6 
cypress: 3.0.1
node: v8.2.0
typescript: 2.4.2

**Comment by bahmutov** [comment]
We are including sinon types from the registry, not writing them ourselves. Maybe open an issue in that repo to remove semi colons, or upgrade TypeScript version?

**Comment by Toxicable** [comment]
In my situation I couldn't upgrade TypeScript due to Angular's requirement on the Typescript version.
To solve it I used `transpileOnly: true` in the `ts-loader` config.
