### ISSUE TITLE
cy.visit with array does not work 

### ISSUE THREAD

**Issue by Peggy1012** [cypress-io/cypress#1886]
### Current behavior:

I have this code, but cy.visit with array does not work.
Tests runs without end. 
    let newList = myList.map(item => cy.get(item).click().should('have.attr', 'value'))
      cy.log(newList)
      cy.visit(newList[0])
### Versions

Cypress: 3.0.1, Win 10

**Comment by MaxVolobuev** [comment]
hey, how did you fix it?
