### ISSUE TITLE
Uploading a file

### ISSUE THREAD

**Issue by mall3r** [cypress-io/cypress#18868]
### Current behavior

When i upload a Example.csv file it show that the file have been uploaded but the Upload button is still cant be clicked
when i upload the file manually after cypress stop it works fine 
![image](https://user-images.githubusercontent.com/79092326/141072781-bd0154ff-4430-4946-8e6f-921b6cad23f9.png)

### Desired behavior

the file is supposed to be uploaded then the file entry can be selected in another feature

### Test code to reproduce

```
        cy.get('#version-no').type('4')
        cy.get('#version-notes').type('added new Example')
        const test_upload = "../fixtures/example.csv";
        cy.get('#file')
            .attachFile(test_upload)


        cy.get('#file')
            .its('0.files')
            .its('0')
            .its('name')
            .should('eq', 'example.csv')

        cy.get('#file')
            .trigger('change', { force: true })

        cy.get('#file')
            .trigger('fileuploadsubmit', { force: true })

        cy.get('[data-cy=Submit_Example]').click({ force: true })
    })
})
```

HTML
```
<input _ngcontent-hsp-c143="" type="file" accept=".csv" id="file" formcontrolname="file" class="form-control ng-untouched ng-pristine ng-invalid">
```

### Cypress Version

8.7.0

**Comment by BlueWinds** [comment]
`cy.attachFile()` is provided by a community plugin,  [cypress-file-upload plugin?](https://github.com/abramenal/cypress-file-upload), and they'd be better equipped to provide support. I'm going to close this issue, and suggest you open one in that repository instead.

**Comment by juanan22** [comment]
@mall3r try with adding trigger after attachfile function: 

cy.get('input[type="file"]').attachFile(fileName).trigger('input');

That worked for me
