### ISSUE TITLE
Even chromWebSecurity = false, I still got error

### ISSUE THREAD

**Issue by refael-nagosa** [cypress-io/cypress#18873]
### Current behavior

I'm tried to login with single sign-on, and for that I read that needs to be changed the chromeWebSecurity to false, after I changed it worked for me successfully. 
Then, I wanted to add another test of login with single sign-on, ( with different IDP), but this time I got an error that I need to change chromeWebSecurity to false, although it's already on false.  

<img width="1185" alt="Screen Shot 2021-11-10 at 16 36 42" src="https://user-images.githubusercontent.com/68903860/141132823-b3d77faf-6b95-4c6f-a492-6a85d532214e.png">

### Test code to reproduce

escribe('Login with SSO', () => {
	beforeEach ( () => {
		cy.visit('/');
	});
//the tests with okta works well
	it('Login with Okta', function () {
		cy.wait(500);
		cy.get('[data-aid="login-with-sso-button"]').click();
		cy.wait(500);
		cy.get('[data-aid="username-input"]').type(oktauser);
		cy.wait(500);
		cy.get('[data-aid="next-sso-button"]').click();

		cy.get('[id="okta-signin-username"]').type(oktauser);
		cy.get('[id="okta-signin-password"]').type(password);
		cy.wait(500);
		cy.get('[type="submit"]').click();

		cy.url().should('include', 'https://app.');
	});	
//the test with g-suite doesn't work 
	it.only('Login with G-suite', function () {
		cy.wait(500);
		cy.get('[data-aid="login-with-sso-button"]').click();
		cy.wait(500);
		cy.get('[data-aid="username-input"]').type(gsuiteuser);
		cy.wait(500);
		cy.get('[data-aid="next-sso-button"]').click();

		cy.get('[id="identifierId"]').type(gsuiteuser);
		cy.wait(500);
		cy.get('[jsname="V67aGc"]').click();
		cy.wait(500);
		cy.get('[name="password"]').type(password);
		cy.wait(500);
		cy.get('[jsname="V67aGc"]').click();

		cy.url().should('include', 'https://app.');
	});	
});

### Cypress Version

7.6.0

**Comment by kemmis** [comment]
You might try the Okta auth guide here: https://docs.cypress.io/guides/testing-strategies/okta-authentication
