### ISSUE TITLE
Still logged in at the start of the next test

### ISSUE THREAD

**Issue by rdadoune** [cypress-io/cypress#18874]
### Current behavior

I'm experiencing an issue where tests run from our Jenkins server exhibit flakiness. Between tests, the session is not reliably cleared out. The test passes most of the time, but occasionally this happens:
<img width="507" alt="Flakey Test" src="https://user-images.githubusercontent.com/26726578/141177725-7f1fc927-a987-4d5a-b60a-638d9d4e9847.png">
The first line of the test is to visit the `/login` page, and the redirect should only occur if the user is already logged in. So how is it possible for this redirect to occur at the start of the test? It seems as though the session must still be hanging around from the previous test. The one possible theory I have is that there's a race condition between the time cookies are cleared and pending XHR requests (that contain old cookies) complete. As shown in the screenshot, some of the XHR requests appear to bleed into the next test.

The good news is, I was able to fix this flakiness by enabling `experimentalSessionSupport` in `cypress.json`, which navigates the browser to `about:blank` before the start of each test. 

> Cypress navigates to the default blank page before each test to ensure test reliability.

Maybe this is the reason for this experimental feature. I'm not sure. I haven't seen this discussed anywhere else, so I figured I'd call it out here to see if anyone else has had this same problem. 

### Desired behavior

Cypress should reliably wipe the session between tests.

### Test code to reproduce

Unfortunately, I've been unable to reproduce this outside of our Jenkins environment. 

### Cypress Version

8.6.0

**Comment by jennifer-shehane** [comment]
Yes, I would suggest using the `experimentalSessionSupport` to address this behavior. We intend to make this the default behavior in the future. To visit `about:blank` in between tests and this is exactly why. There can be some requests that leak through without doing that, causing flake.

**Comment by franco-martin** [comment]
Im having the same issue on 9.4.1, is there any workaround atm?

**Comment by emilyrohrbough** [comment]
In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation) to prevent cases like this, which you have experienced by opting into `experimentalSessionSupport`. There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

This will prevent DOM and browser state bleed over between tests.

Closing this issue as done and tagging for the v12.0.0 release.
