### ISSUE TITLE
Cypress.Commands.add with object argument

### ISSUE THREAD

**Issue by benwiley4000** [cypress-io/cypress#18886]
### What would you like?

I want to be able to do this:

```js
Cypress.Commands.add({
  myCommand(arg) {
    // ...
  },
  myOtherCommand(arg) {
    // ...
  }
});
```

### Why is this needed?

This way we can maintain a commands.js file that looks like this:

```js
export function myCommand(arg) {
  // ...
}

export function myOtherCommand(arg) {
  // ...
}
```

And we can add them all like this:

```js
import * as commands from './commands';
Cypress.Commands.add(commands);
```

### Other

This will be especially useful for typescript where declaring the function separately from the `Cypress.Commands.add(...)` call is helpful for maintaining correct typing in `Cypress.Chainable`.

**Comment by BlueWinds** [comment]
We already have `addAll` available and use it inside Cypress. For example: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/files.ts. Does `Cypress.Commands.addAll()` work for what you're trying to do?

This isn't documented anywhere at the moment - but if someone wanted to open a PR to [add it to the docs](https://github.com/cypress-io/cypress-documentation/), that would be very welcome.
