### ISSUE TITLE
Please consider not removing the `nodeVersion` configuration option

### ISSUE THREAD

**Issue by JessefSpecialisterren** [cypress-io/cypress#18882]
### What would you like?

With the release of Cypress 9.0.0, the `nodeVersion` configuration option has been marked as deprecated. We'd like it to continue to be available in future releases of Cypress.

### Why is this needed?

Cypress having a fixed bundled nodeVersion has been a real help to us as it ensures consistent functionality of the test code across multiple, diverse systems. Due to the nature of working remotely in several separate teams spread across multiple organizations, maintaining consistency in software versions and configuration is continually proving to be a challenge. Additionally, some team members are also involved in other projects with other constraints on Node.js versioning, and Cypress's bundled nodeVersion has made this a lot easier to deal with.

### Other

Thanks for making the awesome testing tool that Cypress is and for your continued efforts in developing and maintaining it!

**Comment by jennifer-shehane** [comment]
Thanks for the feedback. It’s definitely something that we’ll consider. We’d love to hear more feedback from anyone else that wants us to not remove the `nodeVersion` option and why they’d like to be able to set it to ‘bundled’ specifically.

**Comment by JessefSpecialisterren** [comment]
Linking to a few issue comments where being able to fall back on the bundled `nodeVersion` was helpful:

- https://github.com/cypress-io/cypress/issues/18914#issuecomment-976951533
- https://github.com/cypress-io/cypress/issues/18973#issue-1057052012
- https://github.com/cypress-io/cypress/issues/19320#issuecomment-994056272

All these examples show that varying system Node versions can cause problems and that being able to use the bundled version can solve those problems

**Comment by alexsch01** [comment]
Upvote

**Comment by alexsch01** [comment]
Upvoted

**Comment by alexsch01** [comment]
@jennifer-shehane what does the team think about this issue now? Sorry to ping you directly

**Comment by JessefSpecialisterren** [comment]
The `nodeVersion` configuration option hasn't been removed yet and its benefits are still relevant to us, so this issue is still relevant. However, the `bundled` setting seems to be broken now 🙁 , see #27016

**Comment by JessefSpecialisterren** [comment]
The `nodeVersion` configuration option has been removed in Cypress 13.0.0, closing this issue.
