### ISSUE TITLE
Cypress still has issues with copying fails from a read-only location

### ISSUE THREAD

**Issue by cideM** [cypress-io/cypress#18893]
### Current behavior

I use NixOS and as such Cypress is originally installed into a read-only location. It seems to me that https://github.com/cypress-io/cypress/pull/17800/files for some reason only fixed this for `background.js`. But, please see the output below, from my NixOS machine, with Cypress 9.0.0:

```shell
~/private/nixpkgs on update-cypress •
$ ls -lah ~/.config/Cypress/cy/production/browsers/chrome-stable/interactive/CypressExtension/
total 1.5M
dr-xr-xr-x 4 tifa users 4.0K Nov 12 09:59 .
drwxr-xr-x 8 tifa users 4.0K Nov 12 10:01 ..
-rw-r--r-- 1 tifa users 1.5M Nov 12 09:59 background.js
dr-xr-xr-x 2 tifa users 4.0K Nov 12 09:59 icons
dr-xr-xr-x 2 tifa users 4.0K Nov 12 09:59 logos
-r--r--r-- 1 tifa users 1.2K Nov 12 09:59 manifest.json
-r--r--r-- 1 tifa users  333 Nov 12 09:59 newtab.css
-r--r--r-- 1 tifa users  771 Nov 12 09:59 newtab.html
-r--r--r-- 1 tifa users  571 Nov 12 09:59 popup.css
-r--r--r-- 1 tifa users  527 Nov 12 09:59 popup.html
```

As you can guess, this results in the following error:

```
**Title:** Error launching browser

**Message:** EACCES: permission denied, unlink '/home/tifa/.config/Cypress/cy/production/browsers/chrome-stable/interactive/CypressExtension/popup.html'

**Stack trace:**
Error: EACCES: permission denied, unlink '/home/tifa/.config/Cypress/cy/production/browsers/chrome-stable/interactive/CypressExtension/popup.html'
```

### Test code to reproduce

I can't currently provide test code since the official Nixpkgs repository has Cypress 8.3.1 and I am reporting this specifically for 9.0.0, which already includes the PR I mentioned above. The issue would pop up in older versions as well though. If it's required to verify this issue with an actual Nix Cypress I can provide an overlay that would you have to use to get version 9.0.0.

### Cypress Version

9.0.0

**Comment by BlueWinds** [comment]
@chrisbreiding - Can you take a look at this? Looks like you were the author of the PR mentioned and might have more context here.

**Comment by chrisbreiding** [comment]
Afraid I can't take credit for authoring that PR. I only merged it. @flotwig reviewed it, so maybe has some insight?

**Comment by flotwig** [comment]
> ### Current behavior
> 
> I use NixOS and as such Cypress is originally installed into a read-only location. It seems to me that [#17800 (files)](https://github.com/cypress-io/cypress/pull/17800/files) for some reason only fixed this for `background.js`.

Yeah, I agree, it looks like #17800 only fixed permissions for `background.js`. Cypress should fix permissions for all the copied extension files, not just `background.js`.

**Comment by Abdillah** [comment]
I actually the author of the PR. I can see the problem persist cause I encountered similar error.

```
EACCES: permission denied, unlink '/home/user/.config/Cypress/cy/production/browsers/chromium-stable/interactive/CypressExtension/popup.html'
```

I will try to investigate again.

**Comment by Abdillah** [comment]
> Cypress should fix permissions for all the copied extension files, not just background.js.

Okay, I think it is best to make everything under `CypressExtension` dir writable.
