### ISSUE TITLE
viewport error should match viewport limits

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#189]
Viewport limit should match the error message

<img width="559" alt="viewport" src="https://cloud.githubusercontent.com/assets/1271364/16882053/116e930c-4a8b-11e6-92f7-bada0f79985c.png">

**Comment by brian-mann** [comment]
Fixed in [`0.17.0`](https://github.com/cypress-io/cypress/wiki/changelog#0170-08302016).
