### ISSUE TITLE
Place describe/it function in their own namespace to avoid conflict with jest/mocha when using Typescript

### ISSUE THREAD

**Issue by burtonator** [cypress-io/cypress#18905]
### What would you like?

The typescript configuration now is really ugly from my perspective as a Typescript advocate.

We try to keep every thing clean/simple so that we can have a fast cadence of execution internally and having to setup a custom types entry, custom typescript config, then re-haul our CI system and build system is really ugly and is going to cause a lot of maintenance issues for us 

Could there a simpler way to do this so that instead of ```describe``` for example you used ```cytest.describe``` or something along those lines?

It wouldn't conflict with the existing 'cy' namespace and it's different conceptually anyway.

Granted, it's a bit more verbose but it's worth it.  

### Why is this needed?

Having to configure this is a pain when using Typescript and is going to grow into a long term maintenance issue.

I'm now aware of your internal architecture but it seems you could make this an optional way to setup typescript support. 

Existing describe/it would work just fine but people can opt-in to using the new and slightly more verbose syntax.  

The downside is that tools like IntelliJ wouldn't be aware of cytest.describe or cytest.it immediately but I don't really think this is a huge problem.

If you import 'cytest' then cytest.describe will be auto-completed thanks to types and IDE support.

**Comment by bahmutov** [comment]
Have you tried module local-cypress?

**Comment by FDIM** [comment]
I think this (exposing it/describe) should be an opt-in behavior and not necessary the default. 

In the project I'm working we are using angular and default jasmine for unit tests. To fix conflicts, since there is no sensible way to exclude types in typescript, I have made a post install script that renames all these functions in `cypress/types/mocha` file and in `cypress/types/cypress-expect`
