### ISSUE TITLE
Unable to select options in a dropdown list created using InLineSelect html code.

### ISSUE THREAD

**Issue by kodriscollics** [cypress-io/cypress#18928]
### Current behavior

Current html code located in a file called SearchData.js:

    <div>
      <MoreFormal>Search Data</MoreFormal>
      <SearchBox
        prefix={
          <InlineSelect
            id={"search-data"}
            name={"searchData"}
            defaultValue={defaultDataStatus.name}
          >
            <option value={searchDataStatusEnum.CURRENT.name}>
              {searchDataStatusEnum.CURRENT.text}
            </option>
            <option value={searchDataStatusEnum.ARCHIVED.name}>
              {searchDataStatusEnum.ARCHIVED.text}
            </option>
            <option value={searchDataStatusEnum.CURRENT_AND_ARCHIVED.name}>
              {searchPositionStatusEnum.CURRENT_AND_ARCHIVED.text}
            </option>
          </InlineSelect>
        }
        defaultValue={defaultSearchText}
        onSubmit={handleSubmit}
        placeholder="Enter Data to Search For"
        clearButtonLabel="Clear"
        submitButtonLabel="Search"
        name="searchBox"
      />
    </div>

When the webpage first renders, the visible/default selection of "Current" is shown. I see the following in developer mode in the browser on the Elements tab:

   `  <div` class="sc-1injwnz-1 IHADu" xpath="1"> == $0	
	 `  <select` name="searchData" style="width:auto;" id="search-data" class="sc-11vo36o-0 ipeoKO sc-97e1f1-0 j6ZRIO" data-form-type xpath="1"> == $0
	   `  <option` `value="CURRENT">Current</option>`
	 `  </select>`
   `  </div>`

If I click on  the visible/default selection of "Current", I see all of the available options in the dropdown list and the following in developer mode in the browser on the Elements tab:

   `  <div` class="sc-1injwnz-1 IHADu" xpath="1"> == $0	
	 `  <select` name="searchData" style="width:auto;" id="search-data" class="sc-11vo36o-0 ipeoKO sc-97e1f1-0 j6ZRIO" data-form-type xpath="1"> == $0
	   `  <option` `value="CURRENT">Current</option>`
	   `  <option` `value="ARCHIVED">Archived</option>`
	   `  <option` `value="CURRENT_AND_ARCHIVED">Current and Archived</option>`
	 `  </select>`
   `  </div>`

This is how it looks in the browser:

<img width="456" alt="CypressInLineSelectIssue2" src="https://user-images.githubusercontent.com/75755773/141870881-0fd51102-0df9-44eb-9425-5f07441481be.PNG">

<img width="480" alt="CypressInLineSelectIssue" src="https://user-images.githubusercontent.com/75755773/141870505-65751d02-5a2b-4d1d-b2f0-8cd2147592f4.PNG">

I get the following errors when trying to use anything other than an index of 0 in the test code (See "Test code to reproduce" below):

    CypressError: Timed out retrying after 4000ms: `cy.select()` failed because it could not find a single `<option>` with value, index, or text matching: `1`

    CypressError: Timed out retrying after 4000ms: `cy.select()` failed because it could not find a single `<option>` with value, index, or text matching: `Current`

    CypressError: Timed out retrying after 4000ms: `cy.select()` failed because it could not find a single `<option>` with value, index, or text matching: `CURRENT`

Etc..

It may seem logical/intuitive to just do a:

    cy.get('select').click()  

on the default value of "Current" to expose the remaining options and then have cypress select a different one (which I am able to do on the actual webpage) but Cypress doesn't allow you to do this.  You will get this error if you try to click on the default value of "Current":

  CypressError: `cy.click()` cannot be called on a `<select>` element. Use `cy.select()` command instead to change the value.

### Desired behavior

Be able to select any dropdown option by index, text or value after first performing a .click() on  the 'select' element to expose the remaining options.

### Test code to reproduce

Tests using the following cypress code will pass. 0 is the default selection of "Current" which is visible on the webpage:

      cy.get('select').select(0);

Tests using any of the following cypress code will fail:

     cy.get('select').select(1);
     cy.get('select').select(2);
     cy.get('select').select('CURRENT');
     cy.get('select').select('ARCHIVED');
     cy.get('select').select('CURRENT_and_ARCHIVED');
     cy.get('select').select('Current');
     cy.get('select').select('Archived');
     cy.get('select').select('Current and `Archived');

Cypress is able to only select the first/default option ("Current") and then only by its index number of 0. 

### Cypress Version

9.0.0

### Other

Also happens with Cypress version 8.5.0 and 8.6.0
Testing with Electron (as none of my tests run on the latest version of Chrome.)

**Comment by kodriscollics** [comment]
After doing some more research, the html code is an Eden component which, by design, shows only the selected option unless the select element is brought into focus in some way. After troubleshooting from that perspective, the following two options work:

        cy.get('body').tab().tab().tab();

which tabs to the 'select' element, bringing it into focus. Or...
         
        cy.get('select').focus();

which also brings the 'select' element into focus. Then this works:

        cy.get('select').select('Archived');

Having a Cypress override of the requirement to allow a .click() to follow cy.get('select') (instead of a strict .select() rule) would better mimic what the users will have to do when interacting with the page, as the only way a user will be able to see the dropdown is to click on it first.

**Comment by BlueWinds** [comment]
It seems like `cy.focus()` might work for your use, rather than `cy.click()`? Since tabbing to the element in question also activates it, it seems like it's listening for `focus` events regardless.

https://stackoverflow.com/questions/58122127/how-to-trigger-a-click-on-a-select-with-cypress/58123411#58123411 contains some more details and suggestions on the topic.

**Comment by kodriscollics** [comment]
Retested with Cypress 12.12.0 and this is working properly now.
