### ISSUE TITLE
Cypress picks non-spec files as test files

### ISSUE THREAD

**Issue by schuetza** [cypress-io/cypress#18920]
### Current behavior

We have categorized our tests by folders. To document which content the folders should have, I added `readme.asciidoc` files in this folders. However, when I execute headless tests, Cypress picks my readme file and tries to execute it as a spec file. The file is then flagged as failed test.

```

Running:  end2end/readme.asciidoc                                                        (4 of 10)

Oops...we found an error preparing this test file:

  tests\end2end\readme.asciidoc

The error was:

Error: Webpack Compilation Error
./tests/end2end/readme.asciidoc 2:0
Module parse failed: Unexpected token (2:0)


...

  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  end2end/readme.asciidoc                    0ms        -        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤


```

### Desired behavior

Accoding to https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-files only `.js|jsx|.coffee|.cjsx` files are valid for test files. 
Cypress should ignore other files. 

### Test code to reproduce

1. create a subfolder  and put a spec file there. 
2. add a readme.asciidoc into the folder
3. run `cypress run --headless`

### Cypress Version

8.6.0

**Comment by BlueWinds** [comment]
By default, cypress will attempt to run *any* file located in your integration test folder - the documentation is saying those are the supported languages, but we don't filter files based on extension out of the box.

You should be able to fix this for your use with the [`testFiles`](https://docs.cypress.io/guides/references/configuration#Folders-Files) configuration option. Add
```js
"testFiles": "**/*.js"
```
(or a similar pattern customized to your needs) to your cypress configuration. `"ignoreTestFiles": "*.asciidoc"` would work as well.

**Comment by schuetza** [comment]
Thanks for the hints. Not quite obvious, but both ways work.
