### ISSUE TITLE
Verification timming out since 8.4.0+

### ISSUE THREAD

**Issue by KuroiRaven** [cypress-io/cypress#18933]
### Current behavior

Hello guys,

At my workplace, we're facing a weird issue where the Cypress version has no problem verifying that it can run properly until the 8.4.0+ version. (So the last version we're able to launch without having the bug is the 8.3.1).
Weirdly, the message shows up only once and then, if we relaunch the command, the verification passes in a split second.

The error message that is thrown the first time is the following :
```
$ cypress open
It looks like this is your first time using Cypress: 9.0.0


Cypress verification timed out.

This command failed with the following output:

C:\Users\user\AppData\Local\Cypress\Cache\9.0.0\Cypress\Cypress.exe --smoke-test --ping=453

----------

Command timed out after 30000 milliseconds: C:\Users\user\AppData\Local\Cypress\Cache\9.0.0\Cypress\Cypress.exe --smoke-test --ping=453
Timed out

----------

Platform: win32-x64 (10.0.18363)
Cypress Version: 9.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The second time : 
```
It looks like this is your first time using Cypress: 9.0.0

✔  Verified Cypress!
```

### Desired behavior

The verification should either pass straight away or retry before throwing an error ?

### Test code to reproduce

Upgrade version of cypress to 8.4.0+
yarn cypress open

### Cypress Version

8.4.0+

**Comment by CloudToGoTest** [comment]
+1

**Comment by KuroiRaven** [comment]
Bump ?

**Comment by donegjookim** [comment]
Yep, can verify that this is happening for me as well using version 8.7.0

**Comment by donegjookim** [comment]
[Solution](https://stackoverflow.com/a/70867864)
