### ISSUE TITLE
Teamcity integration .exe timing out

### ISSUE THREAD

**Issue by vijaymann0102** [cypress-io/cypress#1893]
### Is this a Feature or Bug?

issue

### Current behavior:

running in teamcity pipeling its getting timeout without any out or error

### Desired behavior:
should give result of cypress commands

### Steps to reproduce:

Deploy cypress.zip extracted in some folder of your project.
Go in teamcity build steps and try to execute `cypress.exe` with any commands like `cypress -h`

**Comment by Bkucera** [comment]
@vijaymann0102 Hi, I'll need some more info.
- what version of windows
- how did you install cypress, what version did you download
- can you check if you have executable permissions on the `.exe` 
- was this setup working previously, if so with what version of cypress ? and can you try downloading the older version and seeing if it works
- can you reproduce this in a local windows environment

**Comment by zerdos** [comment]
we are using cypress with teamcity 
(package.json dependency), and work as expected

**Comment by vijaymann0102** [comment]
Ok are ur packages installed from internet, wat abt directly executing Exe from teamcity without packages?

Wic version of cypress?

Can u share ur package. JSON?

**Comment by vijaymann0102** [comment]
Due to corporate firewall we cannot install all packages , so trying to run cypress. Exe with node-module zip extracted

**Comment by Bkucera** [comment]
@vijaymann0102 can you please answer the questions I asked above? This is the only way we can work towards solving your issue.

**Comment by vijaymann0102** [comment]
Answers below

**Comment by Bkucera** [comment]
@vijaymann0102 
was this setup working previously, if so with what version of cypress ? and can you try downloading the older version and seeing if it works
> -local n teamcity servers r different
Not sure what this means, I'm asking how this was working previously, what changed to cause the failure.

**Comment by vijaymann0102** [comment]
It never worked on teamcity

Is . Exe having some dependencies on packages?

**Comment by vijaymann0102** [comment]
Can we run tests on command line without opening electron through Exe from extract?

In teamcity it runs n not able to open electron due to firewall can we run in command prompt any command like
Cypress --version it still trying to open 
Electron?

**Comment by Bkucera** [comment]
> Can we run tests on command line without opening electron through Exe from extract?

Yes, please read our docs on [Installing Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-Requirements)

**Comment by vijaymann0102** [comment]
Even when r executing from command line it's trying to open electron even in headless is it expected behaviour, how to run n view tests results in command line itself
