### ISSUE TITLE
`Cypress.Commands.add` type doesn't take into account `prevSubject` to define the type of the custom command

### ISSUE THREAD

**Issue by IlCallo** [cypress-io/cypress#18940]
### Current behavior

```ts
declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Custom command to select DOM element by data-cy attribute.
       * @example cy.dataCy('greeting')
       */
      dataCy<E extends Node = HTMLElement>(value: string): Chainable<JQuery<E>>;
    }
  }
}

Cypress.Commands.add(
    'dataCy',
    { prevSubject: 'optional' },
    (subject, value) => {
      return cy.get(`[data-cy=${value}]`, {
        withinSubject: subject,
      });
    },
  );
```

`subject` and `value` are inferred as `any` as `prevSubject` isn't taken into account and TS expect a single param
If `value` is removed, the first param becomes `string` which is wrong
The same problem applies to child commands

### Desired behavior

Types should take into consideration `prevSubject` and use it into a conditional to provide correct typings
There may be other edge cases with `element` | `document` | `window`

### Test code to reproduce

https://github.com/cypress-io/cypress/pull/17496/files#diff-facdf706a5238380b5e97c040bc1a5f5cb89e3116f878754dd7fb4e693787715R77

This test is wrong, it should be

```ts
Cypress.Commands.add('newCommand', { prevSubject: true }, (subject, arg) => {
    // $ExpectType string
    arg
    return
  })
```

### Cypress Version

9.0.0

**Comment by villanuevaSEAT** [comment]
We have the same issue 😢

**Comment by Nodonisko** [comment]
same issue here, problem is both for dual and child custom commands

**Comment by radan-iml** [comment]
Same here, introduced with [this PR](https://github.com/cypress-io/cypress/pull/17496), like OP said wrong tests.

**Comment by Nodonisko** [comment]
Also this test should be added:

```ts
Cypress.Commands.add('newCommand', { prevSubject: 'optional' }, (subject, arg) => {
    // $ExpectType string
    arg
    return
  })

```

**Comment by keeema** [comment]
Same issue:


This was working in Cypress < 9.0.0
```
declare namespace Cypress {
    interface Chainable<Subject> {
        myCommand(options?: Partial<Cypress.Loggable>): Cypress.Chainable<Window>;
    }
}
```

```
Cypress.Commands.add(
    "myCommand",
    {
        prevSubject: ["optional", "window"],
    },
    (prevSubject?: Window, options?: Partial<Cypress.Loggable>): Cypress.Chainable<Window> => {
       ....some code....
    }
);
```

It is not working in Cypress 9.0.0.
I have looked to given example mentioned in [PR](https://github.com/cypress-io/cypress/pull/17496#issuecomment-888110985).
But [cypress-image-snapshot](https://github.com/jaredpalmer/cypress-image-snapshot) is JS plugin with external d.ts. Not a TS plugin.
