### ISSUE TITLE
Unbreak `Cypress.Commands.add({ hover })`

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#18941]
### Current behavior

Cypress.Commands.add({ hover }) errors since we have it stubbed out to throw an error: https://github.com/cypress-io/cypress-documentation/pull/4208

The intent seems to be to add discoverability to the fact that Cy does not support hover OOTB. #10 But it confuses users to have to use `.overwrite` for this, and it's weird.

We have docs for it too: https://docs.cypress.io/api/commands/hover

### Desired behavior

Until Cypress officially adds #10, either:

1. Remove `cy.hover()` completely, and move the docs for it to a guide, like how we document other tasks you can do in Cypress. Trust that users will Google for it.
2. Keep `cy.hover()` for IntelliSense and docs, and still throw, but have a special case to allow `Cypress.Commands.add()` to add it so you don't need to `overwrite` a no-op command?
3. Some other choice that resolves this incongruity		

### Test code to reproduce

---	

### Cypress Version

9.0.0

**Comment by jennifer-shehane** [comment]
Yes, I think it's weird that we have a weird command and docs that doesn't work. But the core of this was to encourage discoverability I suppose - that there are workarounds to hover available that they could look into. Just want to consider that in the solution.

**Comment by emilyrohrbough** [comment]
This was handled in https://github.com/cypress-io/cypress/pull/19633

**Comment by emilyrohrbough** [comment]
This was released in 10.0.0. Verified in Cypress 11.1.0 that this does not error.
