### ISSUE TITLE
In cypress GUI are not visible skipped and pending tests, in dashboard yes

### ISSUE THREAD

**Issue by Peggy1012** [cypress-io/cypress#1894]
### Current behavior:

In cypress GUI are not visible skipped and pending tests, in dashboard yes

![ashampoo_snap_ctvrtek 7 cervna 2018_14h18m55s_001_](https://user-images.githubusercontent.com/22873782/41099247-31c70cfc-6a5e-11e8-87df-d799f9ba428b.png)
![ashampoo_snap_ctvrtek 7 cervna 2018_14h19m29s_002_](https://user-images.githubusercontent.com/22873782/41099248-31e7db4e-6a5e-11e8-9596-d47e84cf0e63.png)

### Versions

Cypress: 3.0.1., Win 10

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
