### ISSUE TITLE
Set cookie domain prefixed with a dot

### ISSUE THREAD

**Issue by LeungMichael** [cypress-io/cypress#1896]
### Current behavior:
The problem I am having is that the website I am testing is hosted on www.something.com. The website is using cookies to avoid showing a popup multiple times. The cookie the website adds has a domain "www.something.com". I want to set this cookie when I start my test run so I don't get the popup.

When I use setCookie and pass it a domain "www.something.com", it actually adds a dot in the domain (.www.something.com). This causes the website to ignore this cookie and adds a duplicate cookie, without the dot before the domain.

Can I somehow force the setCookie to not alter my domain value?

### Desired behavior:

The cookie domain to not be prefixed with a dot.

### Steps to reproduce:

```js
cy.setCookie('myCookie', 'true', { domain : 'www.something.com' })
cy.getCookie('myCookie').should('have.property', 'domain', 'www.something.com')
```

the assertion fails with ".www.something.com"

### Versions
3.0.1
Windows 10
Chrome

**Comment by jennifer-shehane** [comment]
This is still an issue in Cypress 3.4.0. 

Reproducible test

```js
it('test 1', () => {
  cy.visit('https://example.cypress.io')
  cy.setCookie('myCookie', 'true', { domain: 'example.cypress.io' })
  cy.getCookie('myCookie').should('have.property', 'domain', 'example.cypress.io')
})
```

<img width="558" alt="Screen Shot 2019-07-23 at 9 55 53 PM" src="https://user-images.githubusercontent.com/1271364/61724849-be3dd880-ad94-11e9-9f97-631b24c46cb7.png">

**Comment by jennifer-shehane** [comment]
After further investigation - this is exactly how cookies work and are implemented within user agents. If you run this within the console - a `.` is prefixed to the domain that is set.

```js
document.cookie = "test=Hello;domain=example.cypress.io"
```

Then go to the `Application` tab of your devtools, you will see the following cookie set, with the domain being `.example.cypress.io`

![Screen Shot 2019-07-26 at 3 56 55 PM](https://user-images.githubusercontent.com/1271364/61941752-186db200-afbe-11e9-9cb7-86973e3f69a1.png)

Cypress is simply passing along the domain information to the `document.cookie` as intended. This is not a bug, but exactly what happens within the browser itself.

Notably, as part of the cookies spec, leading `.` are ignored. https://tools.ietf.org/html/rfc6265#section-4.1.2.3

**Comment by chenfan-fchen** [comment]
same here, how do you resolved this?

**Comment by vdechef** [comment]
I had the same problem: cookies are not cleared by `cy.clearCookies()`

So what I did was simply overwrite the `clearCookies` command, in *support/commands.js*
```javascript
Cypress.Commands.overwrite("clearCookies", () => {
    cy.getCookies().then(cookies => {
        for (const cookie of cookies) {
            cy.clearCookie(cookie.name)
        }
    })
})
```

**Comment by emil14** [comment]
> Then go to the Application tab of your devtools, you will see the following cookie set, with the domain being .example.cypress.io

I don't see anything

**Comment by xumepadismal** [comment]
Hi @jennifer-shehane! Although this is indeed native browsers behavior there IS a possibility to set dot-less cookie by not specifying domain at all:

```js
document.cookie = "test=Hello"
```

And this is what we can meet in real applications. By using `cy.setCookie()` we can't mimic this behavior and this can lead to this:

<img width="462" alt="cookie-domain" src="https://user-images.githubusercontent.com/7963211/120474284-b0096c00-c3b0-11eb-9269-9a8f789542b2.png">

First cookie was set by PHP itself while second one by Cypress. One of those cookies is definitely outdated and wrong and you never know which one will be used by application.
Furthermore, real applications can have some technical subdomains which can also have their cookies set without leading dot.

Would it be possible to add some extra option to `SetCookieOptions`? Something like this:

```js
cy.setCookie('test', 'value', {domain: 'example.com', domainExact: true})
cy.setCookie('test', 'value', {domain: 'api.example.com', domainExact: true})
cy.setCookie('test', 'value', {domain: 'static.example.com', domainExact: true})
```

And last but not least. I noticed that if my baseUrl is e.g. "docs.cypress.io" and I'm trying to `cy.setCookie('test', 'value');` (without specifying domain) then cookie will be set to ".cypress.io" which is weird and not match browser behavior

![image](https://user-images.githubusercontent.com/7963211/120476274-10011200-c3b3-11eb-88a9-389e727b2800.png)

**Comment by titchimoto** [comment]
Any updates on this issue? Having my tests fail in CI due to this prefixed `.` and it not setting the _exact_ hostname.

**Comment by melibe23** [comment]
I am having the same issue

**Comment by itsik-avidan** [comment]
Encountered this behavior as well. 
We have cookies been set with the expectation to be available on sub-domains and defined using the 'leading-dot' while relying on [RFC-6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.1.3)
It seems that electron is failing to support this while major browsers does

**Comment by xumepadismal** [comment]
@Songyu-Wang There is already an open issue #16856 to track this

**Comment by Songyu-Wang** [comment]
Ah thank you @xumepadismal
