### ISSUE TITLE
Cypress debug script is broken "Unknown command --inspect-brk=5566"

### ISSUE THREAD

**Issue by BboyKeen** [cypress-io/cypress#18963]
### Current behavior

When trying to run Cypress in debug mode to investigate some issues using the command `yarn cypress:open:debug`, I ran into an error message `Unknown command --inspect-brk=5566`.

```
➜  cypress git:(develop) yarn cypress:open:debug                                          
yarn run v1.22.5
$ yarn ensure-deps
$ ./scripts/ensure-dependencies.sh
success Folder in sync.
$ node ./scripts/debug.js cypress:open
Node: v16.13.0
Script: cypress:open
Spawning: cypress open --dev --global
Unknown command "--inspect-brk=5566"
Usage: cypress <command> [options]

Options:
  -v, --version      prints Cypress version
  -h, --help         display help for command

Commands:
  help               Shows CLI help and exits
  version            prints Cypress version
  open [options]     Opens Cypress in the interactive GUI.
  run [options]      Runs Cypress tests from the CLI without the GUI
  open-ct [options]  Opens Cypress component testing interactive mode.
  run-ct [options]   Runs all Cypress Component Testing suites
  install [options]  Installs the Cypress executable matching this package's version
  verify [options]   Verifies that Cypress is installed correctly and executable
  cache [options]    Manages the Cypress binary cache
  info [options]     Prints Cypress and system information
Done in 1.86s.
```

### Desired behavior

Cypress shoud start in debug mode as it does using the command `yarn dev-debug` 

### Test code to reproduce

Run `yarn cypress:open:debug`

### Cypress Version

9.0.0

### Other

It looks like the command taken into account by the debug script is "cypress" and not "node".

`cypress:open:debug` : `node ./scripts/debug.js cypress:open`
`cypress:open` : `cypress open --dev --global`

Thus when the debug script grabs the command at https://github.com/cypress-io/cypress/blob/develop/scripts/debug.js#L19, it will grab `cypress` and will try to apply `--inspect-brk` to this command.

I'm able to run it successfully by modifying the `cypress:open` script to `node node_modules/.bin/cypress open --dev --global`
I don't know what could be a less verbose way to make it work

**Comment by BlueWinds** [comment]
Thank you for the detailed report - it's definitely doing the wrong thing here, exactly as described.

I'll add it to the teams backlog, but if anyone's interested in opening a PR to fix the issue, contributions are always welcome.

**Comment by BboyKeen** [comment]
If you tell me which approach I should take, I can push a PR ;)

**Comment by flotwig** [comment]
Perhaps we should get rid of the extra commands and continue documenting `dev-debug`.
