### ISSUE TITLE
Cypress 9.0 + `@cypress/vite-dev-server` throws in Node.js v12

### ISSUE THREAD

**Issue by sodatea** [cypress-io/cypress#18973]
### Current behavior

See the log here: https://github.com/vuejs/create-vue/runs/4247905252?check_suite_focus=true#step:6:30

It is because the optional chaining syntax used in `@cypress/vite-dev-server`	is only supported in Node.js v14+.
Now that Cypress 9.0 defaults the `nodeVersion` option to `system`, it uses Node.js v12 rather than the bundled version (v14 in Cypress 8, v16 in Cypress 9), which cannot recognize this syntax, thus the error.

A workaround is to explicitly set `nodeVersion` to `bundled`, but this option is deprecated in Cypress 9 so I don't think it's a good idea.

### Desired behavior

Cypress 9 supports Node.js v12+ as stated in the [package.json](https://unpkg.com/browse/cypress@9.0.0/package.json); `@cypress/vite-dev-server` doesn't have a clear supported Node.js version range.

I expect both to work on Node.js v12 as I didn't see further documentation on this breaking change.
Though, I understand that maybe it's not worth the extra effort to support a soon-to-reach-end-of-life version.

So,
- if Node.js v12 should be supported in this current major version, please transpile away the optional chaining syntax in `@cypress/vite-dev-server`;
- if the Cypress team has decided to drop Node.js v12 for this particular package, it would be much appreciated if this change can be included in the v9 release notes.

### Test code to reproduce

https://github.com/vuejs/create-vue/tree/ee1cc5bc69d4838ed83bdc4bd9da703f2e1dc5bd/playground/with-tests

Run `pnpm test:unit:ci` and you'll see the error. 

The CI log is available at https://github.com/vuejs/create-vue/runs/4247905252?check_suite_focus=true#step:6:30

### Cypress Version

9.0.0

**Comment by jennifer-shehane** [comment]
Thanks for opening this issue. We should likely update vite-dev-server to work properly in Node.js 12.

**Comment by JessicaSachs** [comment]
Released in @cypress/vite-dev-server Version 2.2.1
