### ISSUE TITLE
CypressError: `cy.visit()` failed trying to load: undefined: undefined

### ISSUE THREAD

**Issue by sachila** [cypress-io/cypress#18997]
### Current behavior

```
CypressError: `cy.visit()` failed trying to load:

undefined

The response we received from your web server was:

  > undefined: undefined

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false` 

```

### Desired behavior

Should visit to desired web page

### Test code to reproduce

```
describe('login component', () => {
  it('Does not do much!', () => {
    cy.visit('https://docs.cypress.io/');
  });
});

```

### Cypress Version

9.0.0

### Other

Cypress json

```
{
  "baseUrl": "http://localhost:3001/",

  "testFiles": "**/*.test.{js,ts,jsx,tsx}",
  "componentFolder": "e2e",

  "failOnStatusCode": false
}
```
plugins/index.js

```
const injectDevServer = require("@cypress/react/plugins/react-scripts")

module.exports = (on, config) => {
  injectDevServer(on, config)
  return config
}
```

**Comment by chrisbreiding** [comment]
Component tests are tailored for directly importing and mounting components, not visiting a site/app. If you'd like your test to visit your site/app like a user would, it's better to use `cypress open` with e2e/integration tests.

That said, the error in this scenario is terrible and needs to be improved. If `cy.visit()` is not supported for component tests, we should tailor a better error message that makes that clear.

**Comment by lmiller1990** [comment]
We've now got better error handling across all CT mount adapters: https://github.com/cypress-io/cypress/blob/develop/npm/mount-utils/src/index.ts#L41-L63
