### ISSUE TITLE
typescript definition (and docs) for clearLocalStorage are incorrect

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1899]
## bug

Documentation and typescript definition for `cy.clearLocalStorage()` say it yields `null` (https://docs.cypress.io/api/commands/clearlocalstorage.html#Yields), but example shows that it yields local storage object

```js
cy.clearLocalStorage(/prop1|2/).then((ls) => {
  expect(ls.getItem('prop1')).to.be.null
  expect(ls.getItem('prop2')).to.be.null
  expect(ls.getItem('prop3')).to.eq('magenta')
})
```

- need to update TS definition
- need to update documentation

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
