### ISSUE TITLE
Typescript for runtime properties still missing?

### ISSUE THREAD

**Issue by GCHQDeveloper911** [cypress-io/cypress#19001]
### Current behavior

When using typescript with Cypress, if I do something like:
```
if (Cypress.config('isInteractive')){
    cy.log('yes it is')
}
```
Then vsCode is complaining that "No overload matches this call" because "Type '"isInteractive"' has no properties in common with type 'ConfigOptions'"

Supposedly this was addressed in issue #14392 (pull req #14584) - but this seems to still be an issue.

### Desired behavior

Cypress should provide support for runtime properties in the developer's IDE of choice.

### Test code to reproduce

See above.

### Cypress Version

9.0.0

**Comment by chrisbreiding** [comment]
This definitely looks like an oversight in regards to our types. #14584 updated the type for `Cypress.config()` (no arguments), but [when you pass in a key](https://github.com/cypress-io/cypress/blob/5e2de0c9ce3bfd4b3561fcb91883f52886c8dc4f/cli/types/cypress.d.ts#L331), it's accepting a returning a different type than `Cypress.config()`. 

I'm hoping it can be fixed as part of #18896.
