### ISSUE TITLE
Record throws 500 error when launched via module api

### ISSUE THREAD

**Issue by jtwite** [cypress-io/cypress#1901]
I'm launching our cypress instance via the module api and would like to record them so we can view the results in the dashboard.  Currently it is throwing the below error at the start of the test.  It doesn't keep the tests from completing, we just don't get any information in the dashboard.  This exact code works in v2.1.0.

### Current behavior:

Here is the module api call:
`cypress.run({
		project: 'project dir',
		browser: 'electron',
		record: true,
		key: 'key here',
		reporter: 'mocha-bamboo-reporter',
		reporterOptions: {
                         output: 'results.json'
                },
		config: {
			trashAssetsBeforeRuns: false
		}
	});`

> Warning: We encountered an error talking to our servers.
> This run will not be recorded.
> This error will not alter the exit code.
> StatusCodeError: 500
> {}

### Desired behavior:
The module api allows the run to be recorded for a project's dashboard

### Steps to reproduce:
Attempt to record a run launched via the module api

### Versions
Cypress: 3.0.0, 3.0.1
OS: Linux Mint, Redhat
Browser: electron

**Comment by brian-mann** [comment]
Our team has been notified and we'll issue a patch. I'll update the issue when it's done.

**Comment by brian-mann** [comment]
Should be fixed now... closing this unless you continue to have the problem

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
