### ISSUE TITLE
Cypress pre-installs not working as expected with NPM 7+ / Node 15+

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#19013]
### Current behavior

We use `npm_config_argv` to generate the pre-release binary URL when the binary is installed via CLI arg, like with "npm install .....cypress.tgz" or "npx ......cypress.tgz open": https://github.com/cypress-io/cypress/blob/64b1aef36d3c801c76efc906b98a100a1079c0d7/cli/lib/tasks/install.js#L86-L106

However, `npm_config_argv` was removed in NPM 7: https://stackoverflow.com/a/68111110/3474615 https://github.com/npm/cli/issues/1995

So this is broken for those users.	

Pre-releases still work with NPM 7 if you put the `cypress.tgz` URL in `package.json`, and then run `npm install`.

### Desired behavior

We have to hard-code the binary URL in the CLI NPM package, since `npm_command` does not provide the required metadata to cover this use case. 

The only other way I can think would be some kind of climb up the process tree to try and read argv from parent processes, but that sounds hard to maintain.		

### Test code to reproduce

---

### Cypress Version

9.0.0

**Comment by tgriesser** [comment]
https://github.com/npm/rfcs/blob/main/implemented/0021-reduce-lifecycle-script-environment.md

Looks like the correct env var to use is `npm_package_resolved`:

![image](https://user-images.githubusercontent.com/154748/142727300-7d3e9fed-4c96-4a95-8538-9ffc7db868eb.png)

**Comment by tgriesser** [comment]
Fixed in #19013 (d1b7ce5afed5da18a1bb1e7d64f72a69d599f30b)
