### ISSUE TITLE
Do not stringify return of a cypress task

### ISSUE THREAD

**Issue by tomfriedhof** [cypress-io/cypress#19030]
### What would you like?

I'm trying to setup a socket client when testing an API that events are being emitted over the socket. Here is the code I'm using to setup the socket in a task:

```
  on("task", {
    setupSocket(accessToken: string) {
      const socket = io("http://localhost:8302/my/namespace", {
        auth: {
          accessToken,
        },
      });
      socket.on("connect", () => {
        console.log(`Connected to Socket: ${socket.id}`);
      });
      socket.on("message", (msg) => {
        console.log(`Message from Socket: ${msg}`);
      });
      return socket;
    },
  });
```

Cypress throws an error when returning this socket because the socket cannot be `stringify`'ed

```
From Node.js Internals:
  TypeError: Converting circular structure to JSON
      --> starting at object with constructor 'Socket'
      |     property 'io' -> object with constructor 'Manager'
      |     property 'nsps' -> object with constructor 'Object'
      --- property '/mtrvss/uptape' closes the circle
      at stringify (<anonymous>)
```

### Why is this needed?

I want this so that I can ensure that a socket is registered. I want to `wrap` the socket and then execute my tests with my wrapped socket.

**Comment by chrisbreiding** [comment]
Values return from tasks have to be stringified/serialized because the task is run in a Node.js process, while your test code is run in the browser. It's not possible to send the value without serializing it.

For your use-case, I would recommend keeping a reference to the socket in the plugins file and using other tasks to interface with it for the sake of your tests.

**Comment by tomfriedhof** [comment]
Thanks Chris, that's how I ended up getting things working. I kept the socket code in the task and created tasks for operating on the socket inside the plugin file. Thanks!
