### ISSUE TITLE
Failed xhr calls can be matched up with later calls

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19039]
### Current behavior

This issue was discovered by investigating flake in the [redirect driver tests](https://github.com/cypress-io/cypress/blob/mismatched-xhr-calls/packages/driver/cypress/integration/e2e/redirects_spec.js#L15-L30). An xhr call would randomly show up in the log where none should be.

Note the blue 'xhr' request in the third test case.
![Screen Shot 2021-11-22 at 10 34 01 AM](https://user-images.githubusercontent.com/1588747/142899707-234e6937-c18e-41e0-aaa2-4c56787c6991.png)
*screenshot from the reproduced test case but you can see the problem regardless.

### Desired behavior

Improve xhr matching and clean up failed xhr calls that have failed each retry.

### Test code to reproduce

Using branch [mimatched-xhr-calls](https://github.com/cypress-io/cypress/tree/mismatched-xhr-calls)
I've created a test case called '[retry_spec](https://github.com/cypress-io/cypress/blob/mismatched-xhr-calls/packages/driver/cypress/integration/e2e/retry_spec.js)` in the driver to showcase the problem

The test fails an xhr call 25 times to queue up the failed pre-request then uses a meta redirect to make the same call which will match to a failed xhr call.

### Cypress Version

9.0.0 and earlier

**Comment by flotwig** [comment]
#19161 improves this by matching pending pre-requests in reverse order, so it's more likely that an incoming request will be matched with its recent prerequest.

To fix this completely, we'd need a better way to correlate the pre-requests to the automatic retries that browsers do on errored requests.

Either we'd need:

1. browsers to report when they retry so we can get an actual pre-request, or
2. browsers to not retry at all

**Comment by emilyrohrbough** [comment]
This might still be an issue we need to verify.
