### ISSUE TITLE
cy.visit(url) does not send Accept-Language header.

### ISSUE THREAD

**Issue by piyalcodes** [cypress-io/cypress#1904]
### Current behavior:

`Accept-Language` is not sent to server when using `visit()`;. Websites which are expecting to execute based on the `Accept-Language`, can not integrate cypress. It is a default header any web browser.

### Desired behavior:

`Accept-Language` header should be available when using `cy.visit(url)`

### Steps to reproduce:

1) Create a server `instance/page` with a back-end code to listen to `HTTP_ACCEPT_LANGUAGE`,
E:g `$_SERVER['HTTP_ACCEPT_LANGUAGE']`

2) Try to access that page using `cy.visit(url)`

3) You will see the error since the Cypress does not send Accept-Language to server.

### Versions
Cypress = 1.1.2
operating system = Windows 10
browser = Google Chrome

**Comment by andrew-codes** [comment]
Hi, I am also experiencing this issue. Although I am able to provide the `Accept-Language` header in a `cy.request()`, I am unable to do so with `cy.visit()`. I'd love to submit a PR. I will review the contributing guidelines, etc. tonight, though if there are any things and/or direction on preference for a solution, that would be helpful (so I don't implement a solution that does fit the vision of the API, etc.). Thanks.

**Comment by andrew-codes** [comment]
Does it make sense to enable `cy.visit` to accept an options object with headers? Although this would fix it similar to how request does, it seems kind of strange to me; something I'd expect the browser to send along. I'll investigate a little further.

**Comment by jennifer-shehane** [comment]
@andrew-codes I believe @brian-mann has some opinions on the implementation of this. 

I also think this thread may be relevant. https://github.com/cypress-io/cypress/issues/908

**Comment by RockChild** [comment]
@andrew-codes pls do that :) a lot of people has their own edge/odd cases where headers needed!

**Comment by chupa-cabras** [comment]
I have the same problem :-(
