### ISSUE TITLE
process.env variables not read in support/index.ts files 

### ISSUE THREAD

**Issue by ShourryaGuha** [cypress-io/cypress#19047]
### Current behavior

```
import E2ePlatformService from "src/app/services/e2e/e2e-platform.service";
import * as dotenv from "dotenv";
import { TestPlatform } from "src/app/enums/TestPlatform";

// When a command from ./commands is ready to use, import with `import './commands'` syntax
// import './commands';

// tslint:disable-next-line: no-namespace
dotenv.config({ path: '.env.local' });
dotenv.config();

console.log('TEST PLATFORM = ', process.env.TEST_PLATFORM);
```

This is what I have written in my support/index.ts file. It still does not output the correct environment value in the console.

`TEST_PLATFORM=cypress` is my .env file.

As you can see down below, it is outputting undefined
<img width="1209" alt="Screen Shot 2021-11-22 at 1 49 27 PM" src="https://user-images.githubusercontent.com/71526713/142918321-6ad473e3-1fe2-4f44-bbc4-0a480aa57b6c.png">

### Desired behavior

I would want it to output cypress as the value for TEST_PLATFORM logging

### Test code to reproduce

https://github.com/ShourryaGuha/cypress-test.git

clone this repo and run ```npm run cypress:open```, inspect in chrome, the console does not output the correct env value.

### Cypress Version

8.7.0

**Comment by chrisbreiding** [comment]
Since specs run in the browser and not Node.js, environment variables are not carried over from the command line to `process.env`. Please read our guide on [Environment Variables](https://docs.cypress.io/guides/guides/environment-variables).
