### ISSUE TITLE
Support application/Javascript content-type in cy.visit() command 

### ISSUE THREAD

**Issue by shivamshah23** [cypress-io/cypress#19056]
### Current behavior

Cypress won't load web page and throwing content type: application/javascript error. I am using cy.visit(' ') command to load the web page. It worked on regular browser but when trying to load with Cypress, getting error.

cy.visit() failed trying to load:
The content-type of the response we received from your web server was:
>application/javascript

This was considered a failure because response must have content-type : 'text/html'

How can I load webpage and perform other actions? This is blocking my test and I can't do anythng.

### Test code to reproduce

cy.visit('https://battimswebapps.abcd.gov/apex/defg/f?p=1100:1')

### Cypress Version

9.0.0

**Comment by Narretz** [comment]
`application/javascript` is simply the wrong content-type for a webpage. Browsers may be more allowing with this, but I don't see a reason why cypress should be.

**Comment by chrisbreiding** [comment]
As @Narretz said, an html page should not have the content-type `application/javascript` and I think Cypress should stay opinionated about that and not allow it.
