### ISSUE TITLE
Unable to clear span text

### ISSUE THREAD

**Issue by Aishwarya-U-R** [cypress-io/cypress#19064]
### Current behavior

Tried various methods like:

cy.xpath().clear() - since the xpath yields a span element - Cypress invalid clearable element error was thrown

Hence tried:

cy.xpath().type('{selectall}{backspace}') - does not work consistently
cy.xpath().type('{selectall}{del}') - does not work consistently
cy.xpath().type('{cmd+a}{del}') - does not work consistently
cy.xpath().invoke('text', "") - does not work at all

### Desired behavior

All below should work:

cy.xpath().type('{selectall}{backspace}')
cy.xpath().type('{selectall}{del}')
cy.xpath().type('{cmd+a}{del}')

### Test code to reproduce

cy.xpath().type('{selectall}{backspace}')
cy.xpath().type('{selectall}{del}')
cy.xpath().type('{cmd+a}{del}')

### Cypress Version

7.6.0

### Other

Please help here, this is really very displeasing when unable to clear a non-input fields's text value.

**Comment by Narretz** [comment]
Isn't this expected (and has nothing to do with xpath)? clear type etc are only for input and textarea. Or is your span contenteditable? But even then, it's not clear if the cypress commands explicitly support thos.

**Comment by Aishwarya-U-R** [comment]
Ofcourse yes, any medium to complex application will have span's, div's, p's tags contenteditable - I hope !

**Comment by chrisbreiding** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example and we will consider reopening the issue.
