### ISSUE TITLE
Cypress 9.1 appears to mishandle POST content with special characters

### ISSUE THREAD

**Issue by davymitchell** [cypress-io/cypress#19084]
### Current behavior

Upgraded from 9.0 to 9.1

Multiple Tests that send a POST including random generated password content with blackslashes:

e.g.  "oldPassword":"S.]\\x7e}gZ3=kFJ"  (Note the double backslash - GH editor might hide this!).

Fails at when received at the server as oldPassword is wrong. 

### Desired behavior

Tests execute POST commands as before.

### Test code to reproduce
-UPDATED-
Analysis as in comment below from slavab89 appears to be what I am observing.

### Cypress Version

9.1.0

### Other

Thank you. 😄

**Comment by slavab89** [comment]
Can confirm this.
In the logs and when inspecting a command, it shows the correct char. For example `~`, but when receiving this on the server side it shows as `\x7e` which is the hex value

**Comment by pazernh** [comment]
What is strange in my request when I have ~two times in a string, only first one is changed to %5Cx7e second one stays as ~

**Comment by chrisbreiding** [comment]
Do you have a reproducible example of this? What app code or test code is running to evidence this?

**Comment by pazernh** [comment]
I am sending request to authenticate with cy.request and I have ~ in my client secret randomly generated in azure portal and Cypress is trying to encode while creating url for POST

**Comment by duck1123** [comment]
In my case, I'm seeing it when I try to intercept a request and respond with json data (using req.reply) that contains a `~` character.

I haven't been able to get a reproducible example together yet.

**Comment by LoaderB0T** [comment]
Hi @chrisbreiding , hi @duck1123 
I have basically the same issue and created a very simple repro repo. Different use case but the same origin of error, I'm sure. Linked in this issue: #19178
