### ISSUE TITLE
Cypress 9.1 seems to not be reporting to dashboard

### ISSUE THREAD

**Issue by Jacek-fstack** [cypress-io/cypress#19087]
### Current behavior

I'm not sure if I'm the only one with the issue, but 9.0 works fine, but 9.1 does not report to dashboard (batch build@codebuild if that matters) and throws

```
The run started, but never completed. This can happen when the run is canceled from CI or when Cypress crashes during running tests.

Check your Awscodebuild logs for more information. Archive this run to remove it from the runs list and analytics.
```

### Test code to reproduce

Run batch build  @ 9.1 on Codebuild

### Cypress Version

9.1

**Comment by allie-VT** [comment]
I am experiencing this issue with Cypress 9.1 as well. My tests complete in Buildkite and I can see the results in the console there, but the Cypress dashboard continues to say 'In Progress' until it eventually just times out.

**Comment by Adhersan11** [comment]
Experiencing exact same behavior in Jenkins starting from Cypress 9.1.0. The tests are completed in the Job Console but never moved from 'In Progress' in the Dashboard.

**Comment by zaq42** [comment]
Confirming the same behaviour.  Running cypress locally with `--record`.  After upgrading to 9.1.0, runs completed locally, but dashboard timed out (eventually) with the message quoted in the OP.

Rolled back to Cypress 9.0.0 and it worked as expected.

(FYI, Bitbucket integration is enabled)

**Comment by SanderMeesterIndepender** [comment]
Same issue here. Using AzureDevops with a windows agent. 9.0.0 works fine, 9.1.0 does no longer report to the dashboard (no errors whatsoever in the console log)

**Comment by sharpar** [comment]
Experiencing the same issue. Test results are not reported when running locally or with GitHub integration. The runs exist but all of them timeout. Dropping to v9.0.0 fixed the issue.

**Comment by viktorgogulenko** [comment]
Great that I've found this ticket as I was trying to understand why our builds on dashboard started to timeout with still running tests, but logs clearly showing that tests were actually executed. And also with version 9.1.0.

**Comment by Jacek-fstack** [comment]
Any response from devs?

**Comment by mncharlton** [comment]
Same issue here with 9.1.0 not reporting into the dashboard, downgrading to 9.0.0 seems to have fixed it.

**Comment by dmitry** [comment]
@jennifer-shehane can you please check this issue, as a paid customer I cannot use dashboard at the moment because of the 9.1.0 has a problem, and it's a bit challenging to make a revert to the previous version, plus everytime I push the changes it adds `test results` to the billing without actually showing the results.

**Comment by lounsbrough** [comment]
Same issue for us, downgrading to `9.0.0` resolves the issue.

**Comment by chrisbreiding** [comment]
The Cypress team is currently investigating this issue.

**Comment by jennifer-shehane** [comment]
There is a fix that was deployed to the Dashboard that should fix runs being recorded going forward, even when using Cypress 9.1.0. 

We're investigating the 9.1.0 release to further isolate how this was introduced. 

Please notify us of any further issues with test recordings and 9.1.0 in this thread.

**Comment by zaq42** [comment]
Thanks for the update. 

I've tried again on 9.1.0 and it behaves properly.

**Comment by tkharuk** [comment]
Problem remains for me on Dashboard.

<img width="54" alt="Screenshot 2021-12-01 at 10 38 17 AM" src="https://user-images.githubusercontent.com/1205052/144200506-8f1f21dd-3303-42ee-b4b8-99cb737c7c45.png">


```
npx cypress version
Cypress package version: 9.1.0
Cypress binary version: 9.1.0
Electron version: 15.2.0
Bundled Node version: 16.5.0
```

Node on CI
```
cypress/base:12
```



Not sure whether relevant or not:
```
[244:1201/081204.273686:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

**Comment by jennifer-shehane** [comment]
@tkharuk This does not look related to the original issue logged.

**Comment by tkharuk** [comment]
@jennifer-shehane you are right. In a rush I've read title only 😞

**Comment by viktorgogulenko** [comment]
Seems now we have the same issue also with v9.0 as well (we downgraded from 9.1 to resolve a problem). Was something changed from dashboard side?

**Comment by chrisbreiding** [comment]
> builds on dashboard started to timeout with still running tests

@viktorgogulenko Sounds like a different issue. This issue involves the test runs finishing in CI but reporting as having hung in the Dashboard.

**Comment by viktorgogulenko** [comment]
@chrisbreiding so what I've seen is that our bamboo jobs (CI) were successfully finishing, but dashboard was showing that few tests are still running. After some time dashboard was going to the timeout state. As FYI - our CI is checking dashboard using dashboard REST API and from that side it's giving 'success' response, but dashboard is still showing that something is happening on it. That was happening with 9.1 and we downgraded it to 9.0 - issue was gone, but today one of our builds again became green while dashboard was still showing that some test is running and seems after one our dashboard shown this test run as timeout happened.
