### ISSUE TITLE
Cypress 9.1 open wrong URL when there is a ~ (tilde) in the link

### ISSUE THREAD

**Issue by lephuongbg** [cypress-io/cypress#19083]
### Current behavior

In Cypress 9.1, some of our tests failed due to Cypress process the URL in `visit()` calls incorrectly.

This code:

```
cy.visit('/?q=~%28match_status~%28~%27invoiced%29%29')
```

causes Cypress to visit this link:

```
/?q=%5Cx7e%28match_status~%28~%27invoiced%29%29
```

Note the strange `%5Cx7e` right after the `q=`.

### Desired behavior

Cypress should not alter the visit URL in anyway.

### Test code to reproduce

https://github.com/lephuongbg/cypress-test-tiny/tree/cypress-9.1-url-bug

Quick link to diff:

https://github.com/cypress-io/cypress-test-tiny/compare/master...lephuongbg:cypress-9.1-url-bug

### Cypress Version

9.1.0

**Comment by lephuongbg** [comment]
These also look like the same issue:

https://github.com/cypress-io/cypress/issues/19084
https://github.com/cypress-io/cypress/issues/19115

**Comment by chrisbreiding** [comment]
Thanks for the report and the reproduction. This appears to be a regression, so we'll look into addressing it.

**Comment by Narretz** [comment]
Hi @chrisbreiding while you're investigating: it appears that this issue also affects requests via cy.request(): https://github.com/cypress-io/cypress/issues/19084

(Fixing one will probably fix the other because both use the cypress-request lib?)

**Comment by chrisbreiding** [comment]
> (Fixing one will probably fix the other because both use the cypress-request lib?)

I think you're right. Here's all the other issues so far reporting this for various commands:

- #19084
- #19115
- #19096
- #19178

**Comment by barboramartinkova** [comment]
We have the same problem with writing a response body into a fixture file, it converts `~` into `\7x` and then when cypress tries to read from that fixture, it's throwing an error that it's an invalid JSON because of the `\` char 😢
