### ISSUE TITLE
setCookies is broken since 9.0.0. `~` is converted to `\x7e` 

### ISSUE THREAD

**Issue by jweingarten** [cypress-io/cypress#19096]
### Current behavior

After calling setCookie with a valid cookie and then loading the desired page the cookies are somehow not accepted or read. The page we load should show the user is logged in, but he appears as if the cookies are not there. The Network Application Cookies show that they are set, but the page that is loaded doesn't seem to either see them or read them. Note in this example baseUrl is not set, but I tried it with it being set and not. Same behavior.

I ran 8.7.0 and 9.0.0 and 9.0.1. Its broken since 9.0.0. Tested on Chrome, Firefox and Electron. Broken in all 3. 
In 8.7.0 the user appears to be logged in, in 9.* the user is not.

### Desired behavior

User should be logged in after calling setCookies and then visiting the destination url. In this example when I run the provided code and www.yahoo.com is loaded and I move the mouse over the top right `mail` icon I see the user as logged in.  

See screen shot for Cypress 8.7.0
<img width="437" alt="Screen Shot 2021-11-24 at 11 34 07 AM" src="https://user-images.githubusercontent.com/2966099/143302553-c57082d3-adca-4f03-b0bf-39f9b9eeb1c0.png">

Now when running with 9.0.0 you will see this. As if the user is not signed in.
<img width="401" alt="Screen Shot 2021-11-24 at 11 31 42 AM" src="https://user-images.githubusercontent.com/2966099/143302646-73f46718-ea5c-4e61-8686-e70c48b85f38.png">

### Test code to reproduce

I can't give you fully reproducible code, because I can't provide you with the way we get our cookies. Here is the basic script with a hardcoded sample cookie value. 

```
describe('Main Dashoard login load test', function() {
  context('Login', function() {
    it('When moving the mouse over the mail icon at the top right corner the user should show logged in', function() {
      cy.clearCookie('Y');
      cy.clearCookie('T');
      cy.getCookie('Y').should('not.exist');
      cy.getCookie('T').should('not.exist');

      cy.setCookie('Y', "v=1&np=1&n=23eno0bmig3ub&l=8a2dn1nck044hib2atdgsc5adwppb5ii12lf2i04/o&p=n33vvvv00000000&r=11p&intl=us");
      cy.setCookie('T', "af=JnRzPTE2Mzc3Nzg4NTYmcHM9SDR2cHdfbnZXdd=bnMBeWFob28BZwFDTU5NWlhOUURBNkI3SFoyTFlTTUpLQUY3RQFhYwFBSTJLRmlHNQFhbAFkc3BfYXV0bwFzYwF5cWEBZnMBa1VGSTV3Qmhub1dvAXp6AW9Xb25oQjhBQQFhAVFBRQFsYXQBb1dvbmhCAW51ATA-&kt=asdffadfaf--~I&ku=FAATcU6Cc1YDmlpoXPv7S4BTWHg5Uz58mDuWHcxOtOQKf6gvdQ10fhJAnSJ9k_HlToJ4.YDa4kNdee2LAEpqg.KtqhyHvvi2o5MRjmhOesmE7p4fxxHAwiK1gYjNXygVm_AHV95GryLqDPnfuEFaHFQy_vfOKU1YtxEi3W2AdQM3j8-~E");
      cy.visit('https://www.yahoo.com');
    });
  });
});
```

### Cypress Version

9.*

**Comment by jweingarten** [comment]
Network Tools | Application | Cookies screen shot for 9.0.0
<img width="1677" alt="Screen Shot 2021-11-24 at 11 57 26 AM" src="https://user-images.githubusercontent.com/2966099/143305416-6658251e-81e7-4e30-bd8f-325b8b536cf4.png">

Network Tools | Application | Cookies screen shot for 8.7.0
<img width="1677" alt="Screen Shot 2021-11-24 at 11 57 26 AM" src="https://user-images.githubusercontent.com/2966099/143305604-00804919-702d-44e8-a67e-b07b96c0b8fb.png">

I don't see a difference, which is why I don't understand why this is not working in 9.0.0

**Comment by jweingarten** [comment]
When I run the test under `DEBUG=cypress:*` and compare the logs between 8.7 and 9.0 I see in the 9.0 version 

`2021-11-24T20:17:59.259Z cypress:server:browsers:electron debugger: sending Network.deleteCookies with params { name: 'Y', domain: '.yahoo.com' }`
`2021-11-24T20:17:59.259Z cypress:server:browsers:electron debugger: sending Network.deleteCookies with params { name: 'Y\T', domain: '.yahoo.com' }`

Those deleteCookies calls do not show up in 8.7. Not sure if that info is useful :-)

**Comment by jweingarten** [comment]
Attaching output from `DEBUG=cypress:*` for 9.0 and 8.7. Test was run from the test runner.

[debugLog8.log](https://github.com/cypress-io/cypress/files/7599007/debugLog8.log)

[debugLog9.log](https://github.com/cypress-io/cypress/files/7599009/debugLog9.log)

**Comment by jweingarten** [comment]
I figured out what the issue is. With 9.x the a `~` is converted to `\x7e` during the `setCookie` call. 
When I look at my `T` cookie in the Dev Tools Application Cookie entry and change the `\x7e` back to a `~` and reload the page it loads logged in. 

Here are simple steps to reproduce the problem.

```
describe('Main Dashoard login load test', function() {
  context('Login', function() {
    it('The Main Dashboard should be able to load now', function() {
      cy.setCookie('FOO', '~', { domain: 'www.google.com', expiry: 1701057873, path: '/', secure: false });
      cy.visit('https://www.google.com');
      cy.setCookie('FOO', '~', { domain: 'www.google.com', expiry: 1701057873, path: '/', secure: false });
      cy.getCookies().then((cookies) => {
        for (let i = 0; i < cookies.length; i++) {
          if (cookies[i].name === 'FOO') {
            cy.log(cookies[i]);
          }
        }
      });
    });
  });
});
```

Note how the Dev Tools shows `\x7e` and it should be a `~`. 

<img width="1647" alt="Screen Shot 2021-11-26 at 12 14 06 PM" src="https://user-images.githubusercontent.com/2966099/143626450-b8ded833-0e8e-4a3e-b9bf-55e8dd298024.png">

When you look at the `cy.log` output in the Dev Console it shows `~` again. 

<img width="773" alt="Screen Shot 2021-11-26 at 12 15 50 PM" src="https://user-images.githubusercontent.com/2966099/143626547-971cdf3d-322f-4e73-9ef7-10b7e6ce8b1a.png">

**Comment by jweingarten** [comment]
Video showing that the cookie isn't set correctly, but when manually changing `\x7e` back to `~` that the cookie is valid again. 

https://user-images.githubusercontent.com/2966099/143631814-f6390251-1a98-438a-92d7-ce6ff8f6ee97.mov

**Comment by chrisbreiding** [comment]
This seems to be a regression in 9.1.0.

Similar issues using different commands:

- #19083
- #19084
- #19115
- #19178

**Comment by jweingarten** [comment]
@chrisbreiding This is broken since 9.0.0. At least what I am reporting in this ticket is.
