### ISSUE TITLE
Can not start cypress after installing

### ISSUE THREAD

**Issue by lim1017** [cypress-io/cypress#19100]
### Current behavior

Note I had to upgrade node version from 10.23 => 12.0

I installed cypress with npm, which went fine, but after running npx run cypress, it just hangs and i get the image below.

![image](https://user-images.githubusercontent.com/56137210/143318255-d05a7634-0eae-49be-9c89-87674aa48bdf.png)

I also downloaded the standalone app, and it will launch fine, but it crashes every time I load a project (any project)

### Debug logs

The logs just kept on looping as far as I could tell...

So copied the logs from 1 chart until it repeated.

[cypressLog.txt](https://github.com/cypress-io/cypress/files/7598944/cypressLog.txt)

### Cypress Version

9.1

### Package Manager

npm

### Operating system

other

### Other

Windows 10, running a Ubuntu virtual machine

**Comment by mjhenkes** [comment]
Related to https://github.com/cypress-io/cypress-docker-images/issues/555#issuecomment-978164558
