### ISSUE TITLE
Unable to add extra information to mocha test object

### ISSUE THREAD

**Issue by StormPooper** [cypress-io/cypress#1910]
### Current behavior:

I'm attempting to use [mochawesome](https://github.com/adamgruber/mochawesome)'s `addContext` method to add additional information to my tests. Debugging within the test, `addContext` is adding additional properties to the test object (`this` or `runnable.ctx`, but that information appears to be stripped out by the time it reaches the reporter. I raised this at mochawesome - adamgruber/mochawesome#242 - but it appears to be Cypress-specific.

### Desired behavior:

When additional properties are added to the mocha test object, they should be passed to the reporter too.

### Steps to reproduce:

Create a passing test and call `addContext`:

```js
const addContext = require('mochawesome/addContext');

describe('example context missing', () => {
    it('should have context', function () {
        expect(1+1).to.eq(2);
        addContext(this, 'some context');
    });
});
```

Alternatively, call `addContext` on a failed test run by adding this to `support/index.js`, (based on #1200, which reported this was working but then follow-up comments say it stopped) and write a failing test elsewhere:

```js
const addContext = require('mochawesome/addContext')

Cypress.on('fail', function(err, runnable) {
	addContext(runnable.ctx, 'failed context');
	throw err;
});
```

### Versions

Cypress 2.10 running in Electron
mochawesome 3.02
Windows 10 1803

**Comment by LinusCenterstrom** [comment]
Having the same problem in Cypress 3.0.2

**Comment by StormPooper** [comment]
I can also confirm that we're still experiencing this after updating to Cypress 3.0.2.

**Comment by brian-mann** [comment]
Looks like we just need to forward the `context` property.

We pluck off certain properties off of the runnables from the driver to send them to the background node process, so this just needs to be one of the additional properties we send.

**Comment by elicordero-dv** [comment]
Do you have any news about this issue?
We are facing the same issue and we are wondering if there is a solution implemented already.

**Comment by dpasos** [comment]
@StormPooper Hey man, did you find any workaround for this issue?

**Comment by StormPooper** [comment]
@dpasos nope, think it needs what @brian-mann described above to be implemented.

**Comment by LVCarnevalli** [comment]
Actually, onfail does not return the context of the current test.
Alternative, use:

```
Cypress.on('test:after:run', (test, runnable) => {
    if(test.state == 'failed') {
        addContext({ test }, `./screenshots/${runnable.parent.title} -- ${test.title} (failed).png`)
    }
});
```

Also remember to configure the screenshot (https://docs.cypress.io/guides/references/configuration.html#Screenshots) in cypress and run a rename linux command in the file (`mv screenshots/*.feature/* screenshots/`).

Observation:
This code did not work for me, because it always came undefined.

```
Cypress.on('fail', function(err, runnable) {
    addContext(runnable.ctx, 'https://www.google.com')
    throw err
})
```

**Comment by StormPooper** [comment]
@LVCarnevalli nice one, able to do what I needed from your snippet. Oddly, I wasn't getting an undefined back when I logged this, not sure if something has changed. Either way, job done, thanks.

**Comment by vvanmol** [comment]
Hello, 

Thanks to @LVCarnevalli 's post I'm now able to add extra information to the Mocha Context through Cypress Events as in his example, but I'm still not able to update the Mocha Context directly from a Test.

```javascript
const addContext = require('mochawesome/addContext');

describe('example context missing', () => {
    it('should have context', function () {
        expect(1+1).to.eq(2);
        addContext(this, 'some context'); // <== This is still not working
    });
});
```

Did anyone manage to make it work ?

**Comment by fr0** [comment]
Why is this issue closed? It seems like it hasn't been fixed.

**Comment by vvanmol** [comment]
Hi @fr0 

As the issue was already closed when I left my comment I created a new one as follow-up: #3654

**Comment by jamesg1** [comment]
@LVCarnevalli Thanks for the temporary solution here. Surely this is a common use case to show context/screenshots in reports?

**Comment by lots0logs** [comment]
Here's another workaround for screenshots that doesn't require you to manually construct the screenshot file names:

#### `cypress/support/index.js`
```javascript
import addContext from 'mochawesome/addContext';

Cypress.on('test:after:run', (test, runnable) => {
  if ('failed' === test.state) {
    addContext({ test }, window.screenshots.pop())
  }
});
```

#### `cypress/support/hooks.js`
```javascript
afterEach('Maybe get screenshot path', function() {
  cy.task('screenshots', {log: false}).then(screenshots => {
    window.screenshots = screenshots;
  });
});
```

#### `cypress/plugins/index.js`
```javascript
const screenshots = [];

module.exports = (on, config) => {
  on('after:screenshot', details => screenshots.push(details.path));

  on('task', {
    screenshots() {
     return screenshots;
    }
  });
};
```

**Comment by pgroot91** [comment]
@lots0logs thanks for your solution. At the moment struggling to make things to work.

```
// Add context to mochawesome (screenshots on failure)
const screenshots = [];

module.exports = (on, config) => {
  on('after:screenshot', details => screenshots.push(details.path));

  on('task', {
    screenshots() {
		return screenshots;
    }
  });
};

// Add visual testing to cypress with percy
let percyHealthCheck = require('@percy/cypress/task');

module.exports = (on, config) => {
  on('task', percyHealthCheck);
}
```

At the moment having the following error when running the scripts.

> CypressError: cy.task('screenshots') failed with the following error:
> 
> The task 'screenshots' was not handled in the plugins file. The following tasks are registered: percyHealthCheck
> 
> Fix this in your plugins file here:
> C:\Users\Patrick\cypress\plugins\index.js
> 
> https://on.cypress.io/api/task
> 
> Because this error occurred during a 'after each' hook we are skipping all of the remaining tests.

**Comment by lots0logs** [comment]
@pgroot91 Try this:
```
let percyHealthCheck = require('@percy/cypress/task');

// Add context to mochawesome (screenshots on failure)
const screenshots = [];

module.exports = (on, config) => {
  on('after:screenshot', details => screenshots.push(details.path));

  on('task', {
    screenshots() {
		return screenshots;
    },
    percyHealthCheck,
  });
};
```

**Comment by pgroot91** [comment]
@lots0logs thanks for the response and the screenshots are working :D 

Only somehow **percy** is not working anymore.

> CypressError: cy.task('percyHealthCheck') failed with the following error:
> 
> The task 'percyHealthCheck' was not handled in the plugins file. The following tasks are registered: percyHealthCheck, screenshots
> 
> Fix this in your plugins file here:
> C:\Users\Patrick.DESKTOP-Q3EBHKB\cypress\plugins\index.js
> 
> https://on.cypress.io/api/task

**Comment by pgroot91** [comment]
@lots0logs i think i have it working now and did the following:

```
// Add visual testing to cypress with percy
const percyHealthCheck = require('@percy/cypress/task');

// Add context to mochawesome (screenshots on failure)
const screenshots = [];

module.exports = (on, config) => {
	on('after:screenshot', details => screenshots.push(details.path));
	
	on('task', {
		'screenshots' () {
			return screenshots;
		}
	});
	
	on('task', percyHealthCheck);
};
```

Thanks for all the help 👍

**Comment by albertmir** [comment]
> Hello,
> 
> Thanks to @LVCarnevalli 's post I'm now able to add extra information to the Mocha Context through Cypress Events as in his example, but I'm still not able to update the Mocha Context directly from a Test.
> 
> ```js
> const addContext = require('mochawesome/addContext');
> 
> describe('example context missing', () => {
>     it('should have context', function () {
>         expect(1+1).to.eq(2);
>         addContext(this, 'some context'); // <== This is still not working
>     });
> });
> ```
> 
> Did anyone manage to make it work ?

Yes. You can use it by creating a custom command this way:

```js
const addContext = require('mochawesome/addContext');

cy.addToReport = function addToReport(element) {
  addContext({ test: this }, element);
};
```

And then, inside a test you can call it this way:

```js
describe('example context missing', () => {
    it('should have context', function () {
        expect(1+1).to.eq(2);
        cy.addToReport('some element...');
    });
});
```

In your example it does not work because of the wrong context passed to addContext. You can check by viewing your tests console logs. It expects the param named as 'test'. So `addContext({ test: this }, element);` should be enough.

Notice that if you use arrow functions they don't bind the `this` context, so you'll need to move to an ES5 function.

**Comment by jbarriojim** [comment]
> > Hello,
> > Thanks to @LVCarnevalli 's post I'm now able to add extra information to the Mocha Context through Cypress Events as in his example, but I'm still not able to update the Mocha Context directly from a Test.
> > ```js
> > const addContext = require('mochawesome/addContext');
> > 
> > describe('example context missing', () => {
> >     it('should have context', function () {
> >         expect(1+1).to.eq(2);
> >         addContext(this, 'some context'); // <== This is still not working
> >     });
> > });
> > ```
> > 
> > 
> > Did anyone manage to make it work ?
> 
> Yes. You can use it by creating a custom command this way:
> 
> ```js
> const addContext = require('mochawesome/addContext');
> 
> Cypress.Commands.add("addContext", (context) => {
>   cy.once("test:after:run", (test) => addContext({ test }, context))
> })
> ```
> 
> And then, inside a test you can call it this way:
> 
> ```js
> describe('example context missing', () => {
>     it('should have context', function () {
>         expect(1+1).to.eq(2);
>         cy.addToReport('some element...');
>     });
> });
> ```
> 
> In your example it does not work because of the wrong context passed to addContext. You can check by viewing your tests console logs. It expects the param named as 'test'. So `addContext({ test: this }, element);` should be enough.
> 
> Notice that if you use arrow functions they don't bind the `this` context, so you'll need to move to an ES5 function.

Hi,

I'm trying to use the addContext function into the afterEach in cypress but I wasn't able to do it. Did you solve it?

Thank you in advance.

**Comment by eduhunter** [comment]
> > Hello,
> > Thanks to @LVCarnevalli 's post I'm now able to add extra information to the Mocha Context through Cypress Events as in his example, but I'm still not able to update the Mocha Context directly from a Test.
> > ```js
> > const addContext = require('mochawesome/addContext');
> > 
> > describe('example context missing', () => {
> >     it('should have context', function () {
> >         expect(1+1).to.eq(2);
> >         addContext(this, 'some context'); // <== This is still not working
> >     });
> > });
> > ```
> > 
> > 
> > Did anyone manage to make it work ?
> 
> Yes. You can use it by creating a custom command this way:
> 
> ```js
> const addContext = require('mochawesome/addContext');
> 
> Cypress.Commands.add("addContext", (context) => {
>   cy.once("test:after:run", (test) => addContext({ test }, context))
> })
> ```
> 
> And then, inside a test you can call it this way:
> 
> ```js
> describe('example context missing', () => {
>     it('should have context', function () {
>         expect(1+1).to.eq(2);
>         cy.addToReport('some element...');
>     });
> });
> ```
> 
> In your example it does not work because of the wrong context passed to addContext. You can check by viewing your tests console logs. It expects the param named as 'test'. So `addContext({ test: this }, element);` should be enough.
> 
> Notice that if you use arrow functions they don't bind the `this` context, so you'll need to move to an ES5 function.

Great solution, fits perfectly! TY so much!
