### ISSUE TITLE
cypress 9.1.0 depends on deprecated 'har-validator', this is reported on Node 17

### ISSUE THREAD

**Issue by nagkumar** [cypress-io/cypress#19102]
### Current behavior

> cypress@9.1.0 postinstall G:\DWork\angular\angular-coffee-shop\node_modules\cypress
> node index.js --exec install

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'har-validator'
Require stack:
- G:\DWork\angular\angular-coffee-shop\node_modules\@cypress\request\lib\har.js
- G:\DWork\angular\angular-coffee-shop\node_modules\@cypress\request\request.js
- G:\DWork\angular\angular-coffee-shop\node_modules\@cypress\request\index.js
- G:\DWork\angular\angular-coffee-shop\node_modules\cypress\lib\tasks\download.js
- G:\DWork\angular\angular-coffee-shop\node_modules\cypress\lib\tasks\install.js
- G:\DWork\angular\angular-coffee-shop\node_modules\cypress\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (G:\DWork\angular\angular-coffee-shop\node_modules\@cypress\request\lib\har.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (G:\DWork\angular\angular-coffee-shop\node_modules\@cypress\request\request.js:23:11)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'G:\\DWork\\angular\\angular-coffee-shop\\node_modules\\@cypress\\request\\lib\\har.js',
    'G:\\DWork\\angular\\angular-coffee-shop\\node_modules\\@cypress\\request\\request.js',
    'G:\\DWork\\angular\\angular-coffee-shop\\node_modules\\@cypress\\request\\index.js',
    'G:\\DWork\\angular\\angular-coffee-shop\\node_modules\\cypress\\lib\\tasks\\download.js',
    'G:\\DWork\\angular\\angular-coffee-shop\\node_modules\\cypress\\lib\\tasks\\install.js',
    'G:\\DWork\\angular\\angular-coffee-shop\\node_modules\\cypress\\index.js'
  ]
}

Node.js v17.0.1

### Cypress Version

9.1.0

### Package Manager

npm

### Operating system

Windows

**Comment by Haynesy** [comment]
We are seeing the same issue, tried lower versions of Cypress down to 7.1 and the are all having the same issue.

**Comment by rsov** [comment]
Dependency was dropped in `@cypress/request` 2.88.7 and 2.88.8

https://www.npmjs.com/package/@cypress/request/v/2.88.8
https://www.npmjs.com/package/@cypress/request/v/2.88.7

This is what's causing this issue

**Comment by Arunk28** [comment]
facing the same issue 
cypress version 8.7

**Comment by asso1985** [comment]
Same issue here with Cypress `"cypress": "^7.1.0",`

**Comment by Arunk28** [comment]
@jennifer-shehane  without this we cant open cypress fyi .. please help

**Comment by yujeongJeon** [comment]
Same issue with version `8.7.0`, NodeJS `14.16.1`

**Comment by davidsneighbour** [comment]
@Arunk28 run `npm install har-validator` on your project and keep an eye on this issue to remove it again when this is solved.

**Comment by imabp** [comment]
Hello folks, I am also facing this issue.
The stuff that I could do to solve this, was the same.. installing `hat-validator` manually.

**Comment by abrahamseni** [comment]
I also have the same issue today :)
Yesterday it was working fine.
OS: Ubuntu 20
node: 16.13.0
npm: 8.1.0

workaround is like @davidsneighbour said.

**Comment by anneleenscholts** [comment]
Same issue. Proposed workaround seems to solve it for now.

**Comment by rajendran-k** [comment]
Same issue. thanks @davidsneighbour for workaround

**Comment by ikosumi** [comment]
Same here, on macOS Monterey 12.0.1 as well as Ubuntu 18 on github actions.
Thanks for reporting and the workaround

**Comment by asankasira** [comment]
Just include har-validator as a dependency in package.json until a proper solution is suggested

"dependencies": {
    "dayjs": "1.10.4",
    "mocha-allure-reporter": "1.4.0",
    "mochawesome": "6.2.2",
    "mochawesome-merge": "4.2.0",
    "typescript": "4.2.4",
    **"har-validator": "5.1.5"**
  }

**Comment by mryraghi** [comment]
Funny this is a testing library...

**Comment by tatjana-quaschnik** [comment]
> Funny this is a testing library...

and deprecated ...

**Comment by mryraghi** [comment]
> > Funny this is a testing library...
> 
> and deprecated ...
![Screenshot 2021-11-25 at 12 39 30](https://user-images.githubusercontent.com/5071701/143435110-779200d4-ba16-440b-b77a-95bc591751a7.png)
Doens't seem like so :)

**Comment by tatjana-quaschnik** [comment]
I meant har-validator ;p - npm says so https://www.npmjs.com/package/har-validator

**Comment by niltonxp2** [comment]
> @Arunk28 run `npm install har-validator` on your project and keep an eye on this issue to remove it again when this is solved.

This worked for me. Let's follow this issue -_-

**Comment by marekdano** [comment]
Still getting `Cannot find module 'har-validator'` after running `npm install har-validator`.
We used the docker image of `cypress/base:16.13.0`. We've already tested on the previous versions of base:16, but still the same error.
Any idea how this can be fixed?

**Comment by web-dragon-smsp** [comment]
Is there an unofficial version of har-validator?

**Comment by JJ** [comment]
> I meant har-validator ;p - npm says so https://www.npmjs.com/package/har-validator

This is why it was eliminated. A fix for this issue is on the way, please check the latest issue mention just above this.

**Comment by Aterfax** [comment]
This is also appears to be indirectly erroring out in the https://github.com/upptime/upptime project during the Static Site CI build.

**Comment by nujumo** [comment]
Same issue with Cypress 6.0.1

**Comment by joaomelo** [comment]
Same here: package.json => "cypress": "^8.6.0",

**Comment by ArturKaluza** [comment]
Same here with Cypress 8.7.0

**Comment by Darep** [comment]
Can confirm this happens all the way down to even on `npm install cypress@4.12.1` on Node.js 12 😀

**Comment by Arunk28** [comment]
> Can confirm this happens all the way down to even on `npm install cypress@4.12.1` on Node.js 12 😀

if you can check -- > npm i

**Comment by nagkumar** [comment]
Very Active Cypress team, thank you for the speedy workaround suggested.

**Comment by JJ** [comment]
> Same here: package.json => "cypress": "^8.6.0",
> 
> har-validator is reported as deprecated in npm site => https://www.npmjs.com/package/har-validator i don't know if this is expected, but the version tab in the package page doesn't list any version

Expected, and the reason why it was eliminated in the first place.

**Comment by anamicaarya** [comment]
Our integration test suite broke this morning for the same reason.
this work around works as I am using Cypress 7.5.0

  "devDependencies": {
    "cypress": "7.5.0",
    "cypress-file-upload": "4.1.1",
    "cypress-localstorage-commands": "1.4.0",
    "cypress-otp": "^1.0.3",
    "mocha": "^7.1.1",
    "mochawesome": "^5.0.0",
    "mochawesome-merge": "^4.2.0",
    **"har-validator": "2.0.0"**
  }

**Comment by segl84** [comment]
Workaround does help!

**Comment by Zahen** [comment]
Same with Cypress 7.7.0.

Add "har-validator": "^5.1.5" to devDependencies solve it for know...

Question: When Cypress solve this problem, we must upgrade our Cypress package to the latest release, like 9.2.0 ?? for example ???

Thanks

**Comment by JJ** [comment]
> Same with Cypress 7.7.0.
> 
> Add "har-validator": "^5.1.5" to devDependencies solve it for know...
> 
> Question: When Cypress solve this problem, we must upgrade our Cypress package to the latest release, like 9.2.0 ?? for example ???
> 
> Thanks

Not really. It's an upstream dependency, `@cypress/request`. As soon as it's upgraded, this problem will be fixed.

**Comment by chrisbreiding** [comment]
The code for this is done in [cypress-io/cypress#19099](https://github.com/cypress-io/cypress/pull/19099), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
