### ISSUE TITLE
Bad body encoding in `cy.request`

### ISSUE THREAD

**Issue by jean9696** [cypress-io/cypress#19115]
### Current behavior

Body is encoding chars like  '~' into hex chars (` \x7e`)

### Desired behavior

Body sent should be ` { key: '~'}` without encoding

### Test code to reproduce

```js
    cy.request({ method: 'POST', body: { key: '~'}, 'url': 'https://www.google.com'})

```

### Cypress Version

9.1.0

### Other

I thank you for what you do at Cypress ! I'm facing the issue described here since the v9.1, is it a bug or is it what you wanted? 😬 

Thanks for your time !

**Comment by Narretz** [comment]
Looks like a duplicate of https://github.com/cypress-io/cypress/issues/19084

**Comment by chrisbreiding** [comment]
This seems to be a regression in 9.1.0.

Similar issues using different commands:

- #19083
- #19096
- #19178
