### ISSUE TITLE
Cypress stuck after modifying test

### ISSUE THREAD

**Issue by wtchnm** [cypress-io/cypress#19111]
### Current behavior

After modifying a test, Cypress shows a loading screen indefinitely:
![image](https://user-images.githubusercontent.com/37726261/143439795-f0438fdd-2a26-4435-bfd9-df64b2ff672d.png)
An error is logged to the dev tools:
[localhost-1637842376608.log](https://github.com/cypress-io/cypress/files/7602835/localhost-1637842376608.log)

If I restart Cypress, it will redirect from http://localhost:5000/__/#/tests/__all to the http://localhost:5000:
![image](https://user-images.githubusercontent.com/37726261/143440082-30fd0b54-2119-4cc6-9f41-43cc000a08d4.png)

If I delete /home/wtchnm/.config/Cypress, it will work fine again.

### Desired behavior

Cypress should work as expected.

### Test code to reproduce

https://github.com/wtchnm/Vitamin

### Cypress Version

9.1.0

### Other

Node.js: 16.13.0
Operating System: EndeavourOS
Kernel: Linux 5.15.4-arch1-1
Architecture: x86-64

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Is it still happening with the latest Cypress?

**Comment by sainthkh** [comment]
Closing because of the inacitivy.
