### ISSUE TITLE
Cypress scripts are not working in chrome browser due to forcepoint app

### ISSUE THREAD

**Issue by sankarijayapal** [cypress-io/cypress#19119]
### Current behavior

Cypress automation scripts are executing well in chrome browser , if forcepoint app is uninstalled . Due to the company policy we reinstalled the forcepoint app in my machine and scripts are not executing in chrome browser..So now in Forcepoint they been configured to bypass endpoint policy enforcement for Cypress.exe and Node.exe file extensions but still we get same error as 'Failed to connect to chrome' could anyone guide us please.

### Test code to reproduce

No.

### Cypress Version

9.0.0

**Comment by Narretz** [comment]
Wouldn't it make more sense to ask your Forcepoint admin to check the logs on what Forcepoint blocks when you execute Cypress?

**Comment by sankarijayapal** [comment]
We can't see any entry in log file..

**Comment by sankarijayapal** [comment]
how we can configure cypress to bypass proxy setting??
