### ISSUE TITLE
Cypress failed to make a connection to the Chrome DevTools Protocol

### ISSUE THREAD

**Issue by Svetlana0107** [cypress-io/cypress#19122]
### Current behavior

Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 56204.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:56204 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)

Stack trace

### Desired behavior

connect without any issues

### Test code to reproduce

demo codes from examples

### Cypress Version

9.1.0

**Comment by rcauquil** [comment]
I have the same issue for both firefox and chromium.

### Cypress Version

9.1.1

**Comment by PolinaLyzenkova** [comment]
same for me

**Comment by rcauquil** [comment]
@PolinaLyzenkova I solved it this morning, for me it was a typo inside my /etc/hosts
and for another guy I found on a blog post he was missing `127.0.0.1 localhost`
let me know how it goes for you

**Comment by matiaso** [comment]
I had the same issue and I solved it by changing the `/etc/nsswitch.conf` file on linux to make sure that the files were prioritized over DNS:

`hosts:      files dns`

To check, you can ping localhost and make sure it resolve to `127.0.0.1`

In my case, the router's DNS was resolving localhost to `127.0.0.2` which is also a local address, but doesn't work.

**Comment by Svetlana0107** [comment]
> @Svetlana0107 did this happen for you locally or in ci? i've been having this issue a lot in ci. i'm on version 9.5.3 now.

@onthespotqa it’s reproduced locally in my case

**Comment by sarthak-verma-bcg** [comment]
@Svetlana0107 Any update on this issue? Facing the same issue

**Comment by mauro-mendaro-lmnd** [comment]
Having the same on my side, any updates on the issue?

**Comment by MikeMcC399** [comment]
@Svetlana0107 

The original issue here referred to

Test code to reproduce
demo codes from examples

Are you still seeing this issue? Which examples are you referring to? Could you provide a URL?

**Comment by MikeMcC399** [comment]
@mauro-mendaro-lmnd 

> Having the same on my side, any updates on the issue?

Which version of Cypress are you using? This issue refers to an old version `9.1.0`.

Are you also using examples provided by Cypress? If not do you have a public repo where you can show the problem?

**Comment by nagash77** [comment]
Looking over this thread I don't see any details about which examples folks are referring to.  This ticket is also for a quite old version of Cypress.  As such I am going to close this issue.  If anyone in this thread is still experiencing this issue on the latest versions of Cypress please open a new ticket and we will be happy to investigate.

**Comment by lucasbatier** [comment]
Hi there, the same issues happened today for me on my GitHub action CI. Can you help me on that ?

Cypress version 12.7.0

Here is the workflow file :

```yarn
name: On Approved PR Cypress Tests

on:
    pull_request_review:
        types: [submitted]

jobs:
    cypress-run:
        if: github.event.review.state == 'approved'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cypress run
              uses: cypress-io/github-action@v4
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              with:
                  config: "viewportWidth=${{ matrix.viewport[0] }},viewportHeight=${{ matrix.viewport[1] }}"
                  browser: ${{ matrix.browser }}
                  group: ${{ matrix.browser }}-${{ matrix.viewport[0] }}x${{ matrix.viewport[1] }}
                  build: yarn run build
                  start: yarn start_dev
                  wait-on: "http://localhost:3000"
                  wait-on-timeout: 300
                  record: true
                  parallel: true
        strategy:
            matrix:
                browser: [chrome]
                viewport: [[1920, 1080], [375, 667]]
                include:
                    - browser: chrome
                    - viewport: [1920, 1080]
```

**Comment by MikeMcC399** [comment]
@lucasbatier 

Which version of Chrome are you using?

- This may be related to issue https://github.com/cypress-io/cypress/issues/27804

**Comment by MikeMcC399** [comment]
@lucasbatier

If you see  runner-image `Version: 20230917.1.0` in your log file, then this image includes Chrome `117` which has a bug that causes Cypress < `12.15.0` to fail.

If possible, update to `cypress@^12.15.0` or later.

![image](https://github.com/cypress-io/cypress/assets/66998419/26627f8c-ddfa-428c-8809-c4aec99cdbf8)

**Comment by ssteezens** [comment]
Just commenting in case it helps anyone else.  This issue would randomly happen to us (using cypress v13.3.3) in our azure devops pipeline jobs but only when using the windows-2019 image.  We have our tests split up to run in 20 different parallel jobs and inevitably at least one of the agents would get this issue.  Switching to ubuntu-20.04 fixed the issue for us.

**Comment by ritikb01** [comment]
> Just commenting in case it helps anyone else. This issue would randomly happen to us (using cypress v13.3.3) in our azure devops pipeline jobs but only when using the windows-2019 image. We have our tests split up to run in 20 different parallel jobs and inevitably at least one of the agents would get this issue. Switching to ubuntu-20.04 fixed the issue for us.

Thanks, It helped.
