### ISSUE TITLE
Github action build timed out because Cypress hanged until time out reached

### ISSUE THREAD

**Issue by sangmai350** [cypress-io/cypress#19137]
### Current behavior

I have set up a build for cypress to run on Github Action pipeline but then I saw Cypress doesn't end until timed out has reached. 

I ran on Chrome and this is my executed command: "cypress:run": "TZ=UTC yarn cypress run --headless --browser chrome"

Please see the image here
![image](https://user-images.githubusercontent.com/37669424/143867824-83f45544-86f1-48b9-a716-52f2ed788cfa.png)
![image](https://user-images.githubusercontent.com/37669424/143867942-f0530233-eba2-4dc4-88ee-8f35ee404c94.png)

### Desired behavior

Cypress shouldn't be hanged at the end of the build

### Test code to reproduce

This is my github action code
name: cypress

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: cypress/included:7.6.0
    env:
      GITHUB_NPM_REGISTRY_TOKEN: ${{ secrets.GITHUB_NPM_REGISTRY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEBUG: '@cypress/github-action'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn cypress:run
          browser: chrome
          headless: true
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Cypress Integration Test # default: 8398a7@action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()

### Cypress Version

9.1.0

### Other

I tried to downgrade to a few other version like 8. and 7. but none of them work

**Comment by aizotov** [comment]
I am running into the same issue. What was your fix?
