### ISSUE TITLE
Failed downloading the Cypress binary.

### ISSUE THREAD

**Issue by SwethaGotety** [cypress-io/cypress#19133]
### Current behavior

The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/C:/..................AppData/Local/Cypress/Cache/8.7.0?platform=win32&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

### Cypress Version

8.7.0

### Package Manager

npm

### Operating system

Windows

**Comment by winkbrace** [comment]
Same issue in our github actions:

```
[FAILED] The Cypress App could not be unzipped.
[FAILED] 
[FAILED] Search for an existing issue or open a GitHub issue at
[FAILED] 
[FAILED] https://github.com/cypress-io/cypress/issues
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Error: EACCES: permission denied, mkdir '/cypress/9.1.0'
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Debian - 10.9)
[FAILED] Cypress Version: 9.1.0
```

**Comment by DavidIAm** [comment]
In troubleshooting this matter: cypress needs to stop using deprecated module 'request' to do this processing as that is incapable of cleanly handling redirects done through a proxy, apparently.  The http module handles it just fine.

**Comment by SwethaGotety** [comment]
I resolved this issue by placing the cypress executable in Cache folder and it worked yesterday.I was able to open cypress and run my script. But, today when I restarted my system, again it showed the same error message.
No version of Cypress is installed in: C:\Users\Arvind\AppData\Local\Cypress\.cypress-cache\8.7.0\Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: C:\Users\.....AppData\Local\Cypress\.cypress-cache\8.7.0\Cypress\Cypress.exe


Platform: win32 (10.0.19042)
Cypress Version: 8.7.0

**Comment by gkatsanos** [comment]
We just changed the node version / cypress container we used to run our cypress tests:

```
 -   container: cypress/browsers:node12.14.1-chrome85-ff81
 +   container: cypress/browsers:node16.5.0-chrome94-ff93
```

And updated the core cypress npm dependency:

```
-    "cypress": "^9.1.0",
+    "cypress": "^9.1.1",
```

And our pipeline fails:

```sh
/usr/local/bin/npx cypress cache list
┌─────────┬─────────────┐
│ version │ last used   │
├─────────┼─────────────┤
│ 9.1.1   │ 14 days ago │
└─────────┴─────────────┘
/usr/local/bin/npx cypress verify
[STARTED] Task without title.
[FAILED] EACCES: permission denied, open '/github/home/.cache/Cypress/9.1.1/binary_state.json'
An unexpected error occurred while verifying the Cypress executable.

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Error: EACCES: permission denied, open '/github/home/.cache/Cypress/9.1.1/binary_state.json'

----------
```

Is this related to the same issue or should I file a new one?

**Comment by mmahalwy** [comment]
Running into same problem as @gkatsanos. 16.5, and 9.1.1 not working.

**Comment by davidiamaf** [comment]
I encourage all concerned on this issue to promote the pull request I created to fix it.
