### ISSUE TITLE
Option { failOnNetwork: false } for cy.visit() and cy.request()

### ISSUE THREAD

**Issue by san-ouadghiri** [cypress-io/cypress#19136]
### What would you like?

We have the following options
- `failOnStatusCode `and `retryOnStatusCodeFailure`
- `retryOnNetworkFailure`

I'd like us to have `failOnNetwork`.
So we could do `cy.request(`${Cypress.env('serviceUrl')}`, { failOnNetworkFailure: false }).should(something)`

It means request should still yield something to assert on.
There is probably not much you can assert on. Maybe if you have error codes (ETIMEDOUT, ...) you can yield that. It would go like: `cy.request(`${Cypress.env('serviceUrl')}`, { failOnNetworkFailure: false }).should('eq','ETIMEDOUT').`

### Why is this needed?

We want to test that, at deployment, the env. we provide don't come with some tools exposed (tech urls, non-exposed api, broker urls, ...). In those case, it is not a error 500 that you get but a network error, as the service (if all goes fine) is really not available at all.

I'd like to test that I am in this situation. That we attempted to make an http request to this URL but the request failed without a response. So that Cypress got what it gets when it logs

```
We received this error at the network level:

  > Error: connect ETIMEDOUT <myDNS>

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: <myUrl>

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
```

### Other
[This feature requests is on the existing options I mention ](https://github.com/cypress-io/cypress/issues/4605)

**Comment by dan-kirberger** [comment]
Is cypress the best option here? Do you have any more api-focused tests that can make the rest calls and assert that the appropriate error happened? This isn't really a scenario where you need/want a browser driving the experience, you're just validating http connectivity period.

If cypress is more convenient in your pipeline, you could just make a test that makes a direct request, skipping the cypress plumbing.
```
  it('makes an arbitrary rest call', async () => {
    try {
      await fetch('https://www.fake.comz')
      throw new Error("Uh oh the call didnt fail, whats up with that")
    } catch (e) {
      expect(e).to.equal('compare the error details here')
    }
  })
```
(or preferably use a more elegant pattern for testing promises :) )
