### ISSUE TITLE
Update actionability checks to require an accessible name and role for actionable elements

### ISSUE THREAD

**Issue by junyper** [cypress-io/cypress#19139]
### What would you like?

Along the same lines of [this feature request recently opened for Playwright](https://github.com/microsoft/playwright/issues/10562), I'd like to propose extending the actionability checks for Cypress to include (optionally) checking for an [accessible name](https://www.w3.org/TR/accname-1.1/) and role.

Relevant details from the Playwright issue:

> Accessible name and role are synthesized by the browser into an accessibility tree, and normally (with the exception of experimental AOM in Chrome) aren't available to JS. However, there's work to recreate the browser accessible name and role computation in JS, e.g. https://github.com/eps1lon/dom-accessibility-api, that could be used here.

### Why is this needed?

By adding this capability to the [built-in actionability checks](https://docs.cypress.io/guides/references/configuration#Actionability) in Cypress, users could enable this for their test suite and find accessibility issues without needing to rewrite their existing tests to use better element selectors (via [testing-library](https://testing-library.com/) or similar) or run [axe-core](https://github.com/dequelabs/axe-core) validations.

With this feature enabled, my existing test suite will automatically time out if the application is not accessible to screen readers or other assistive tech due to missing accessible names and role for actionable elements.

### Other

Ideally this would be configurable [via the global actionability config](https://docs.cypress.io/guides/references/configuration#Actionability), via actionability options passed to `cy.visit`, and also at the individual selector level, but [the existing](https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Forcing) `force: true` might be an acceptable solution.

**Comment by chbdetta** [comment]
could we have custom actionability check too?

**Comment by 787681277** [comment]
Is there any way to get element's accessible name and role?
