### ISSUE TITLE
Cypress breaks on visit some pages

### ISSUE THREAD

**Issue by BorjaRobles** [cypress-io/cypress#1914]
###  Bug
On visit some pages like instagram the server breaks because can not set csrftoken.

### Current behavior:

```bash
➜ ./node_modules/cypress/bin/cypress open

GET /__/ 200 36.036 ms - -
GET /__cypress/runner/cypress_runner.css 200 50.975 ms - -
GET /__cypress/runner/cypress_runner.js 200 418.919 ms - -
GET /__cypress/static/favicon.ico 200 8.891 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 2.489 ms - 77160
GET /__cypress/iframes/integration/test.js 200 13.156 ms - 711
GET /__cypress/tests?p=cypress/integration/test.js-110 200 695.765 ms - 665
GET /__cypress/tests?p=cypress/support/index.js-696 200 771.774 ms - -
{ [Error: Failed to parse or set cookie named "csrftoken".] name: undefined }
undefined
```

### Desired behavior:

The page is loaded correctly

### Steps to reproduce:

Launch this test

```js
describe('My First Test', function() {
  it('Visits the main page', function() {
    cy.visit('https://instagram.com')
  })
})

```

**Comment by EirikBirkeland** [comment]
I suggest running Cypress on websites you own, where you've disabled CSRF protection beforehand. Cypress is not intended to handle websites you don't own.

**Comment by EirikBirkeland** [comment]
But check this out (example of how to circumvent CSRF protection):
https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/logging-in__csrf-tokens
