### ISSUE TITLE
Problem cancelling XHRs from previous test (bis)

### ISSUE THREAD

**Issue by devfservant** [cypress-io/cypress#19141]
### Current behavior

I have a file containing two tests:

```ts
describe('My page', () => {
  beforeEach(() => {
    cy.login();
    cy.visit('/#/new-receipt');
  });
  it('should display elements', () => {
    // some stuff
  });
  it('should complete some form', () => {
    // some other stuff
  });
});
```

But when my second test starts, some requests from the first test are not cancelled and are still running:

![image](https://user-images.githubusercontent.com/43757707/143934313-1d59ea49-1288-4eb0-90d6-eaa74485d0a1.png)

In my case, those are cross-origin requests and so it failed my test suite.

My workaround is:

* either to add a `cy.wait(1000)` in a `afterEach`
* or to use `{ chromeWebSecurity: false }` in my _cypress.json_ config

The fact that my tests pass with the `cy.wait(1000)` at the end of the first test highlights the problem.

### Desired behavior

In this situation, I expect Cypress to start each test from a clean state.  
Therefore, there should be no on-going request when launching a new test.

### Test code to reproduce

see above

### Cypress Version

9.3.1

### Other

* My application uses `@angular/core@^13.0.0` and `@azure/msal-angular@2.0.5`
* My `cy.login` has nothing very special; it follows [this recipe](https://github.com/juunas11/AzureAdUiTestAutomation) taken from https://stackoverflow.com/a/68298957/12292636
* Relates to https://github.com/cypress-io/cypress/issues/761

**Comment by JohnnyTheBoy** [comment]
just to confirm, it's the same on  9.1.1 version

**Comment by devfservant** [comment]
> just to confirm, it's the same on 9.1.1 version

Yes, I tested it too with the 9.1.1 version and the behaviour is the same. I'll update the description accordingly

**Comment by RiZKiT** [comment]
Might me related to https://github.com/cypress-io/cypress/issues/19039

**Comment by mjhenkes** [comment]
@devfservant / @JohnnyTheBoy , could you try on version 9.2.0, we introduced some changes to our proxy server that may affect this issue. #19043

**Comment by devfservant** [comment]
I'll the test with the latest version of Cypress ASAP and will keep you up-to-date

**Comment by devfservant** [comment]
I can confirm that the issue is still here. I did the test with the latest version of Cypress (9.3.1)

**Comment by jpaas** [comment]
Having the same issue on 9.6.0

**Comment by bluepioupiou** [comment]
Exact same behavior here with version 9.7 and still in 12.6.0. Only the systematic cy.Wait() is working here and I think it's not a good practice. Does someone ca look at that or offer us some perspectives ?

**Comment by devfservant** [comment]
I am going to test with the latest Cypress version this week and will keep you inform quickly

**Comment by jennifer-shehane** [comment]
@devfservant Was this issue resolved? I would it would be in v12 since we clear the state between tests.

**Comment by devfservant** [comment]
After testing, I no longer observe the issue. It seems to have been fixed, thank you :)
