### ISSUE TITLE
Target element is null on chrome

### ISSUE THREAD

**Issue by hadrien4789** [cypress-io/cypress#19153]
### Current behavior

On chrome when I type into an input,  the target element is null so no event are triggered where as on firefox I have a not null target element and  event are triggered.

### Desired behavior

The target element is the same whatever the navigator is.

### Test code to reproduce

```
 cy.visit('https://dev.fournisseur-energie.com/comparator-form/')

cy.get('div#slide-0 > ppn-autocomplete')
 .shadow()
 .find('.input-text-container')
 .shadow()
 .find('#housing\\.address')
 .click()
 .type('2 rue lecourbe 75015 Paris',{ force : true})
```

### Cypress Version

9.0.0

**Comment by sainthkh** [comment]
It's related with #19260. Change `click()` with `click({position: 'top'})`.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
