### ISSUE TITLE
Issue when using `testFiles` option

### ISSUE THREAD

**Issue by tiec7** [cypress-io/cypress#19154]
### Current behavior

I have this folder structure

cypress
├── fixtures
 │   └── template.test.js
├── integration
 │   ├── login.spec.js
 │   └── mytest.spec.js

NOTE that `template.test.js` contain a test structure, very similar to `mytest.spec.js`

When i specify in `cypress.json`

`"testFiles": ["login.spec.js", "*.spec.js"]`

Cypress launches 3 tests:
`login.spec.js, mytest.spec.js, template.test.js`

If I use

`"testFiles": ["integration/login.spec.js", "integration/*.spec.js"]`

Cypress dashboard says "no test files found" on the entire project.

### Desired behavior

Cypress should launch 2 tests:
`login.spec.js, mytest.spec.js`

Or at least should recognize

`"testFiles": ["integration/login.spec.js", "integration/*.spec.js"]`

using `integration` as the only folder where to search for tests.

### Test code to reproduce

Just add
`"testFiles": ["*.spec.js"]`
to `cypress.json` file, having a test in another folder

### Cypress Version

9.0.0

### Other

Complete `cypress.json` file is
```
{
  "projectId": "geu3qf",
  "chromeWebSecurity": false,
  "defaultCommandTimeout": 10000,
  "experimentalInteractiveRunEvents": true,
  "video": false,
  "screenshotOnRunFailure": false,
  "testFiles": ["login.spec.js", "*.spec.js"]
}
```

**Comment by emilyrohrbough** [comment]
The spec configuration and resolution has changed in Cypress 10.0.0. The current Cypress version is 11.1.0. Please try upgrading and open a new issue if this persists.
