### ISSUE TITLE
Upgrading to Cypress 9.1.0 breaks code coverage

### ISSUE THREAD

**Issue by esdc-esac-esa-int** [cypress-io/cypress#19166]
### Current behavior

Upgrading from Cypress 9.0.0 to 9.1.0 breaks the code coverage of our Angular e2e tests. Our setup is based on this:
https://github.com/skylock/cypress-angular-coverage-example

When using 9.1.0 a message is displayed saying:
nyc out.json is empty 

This basically means the instrumentation failed or did not happen. However, downgrading to 9.0.0 and everything continues to work.

I don't know if it can somehow be related to the plugin for code coverage e.g https://github.com/cypress-io/code-coverage/issues/78

### Desired behavior

Code coverage should continue to be generated.

### Test code to reproduce

N/A

### Cypress Version

9.1.0

**Comment by JonCook** [comment]
Hi, my bad. Looks to be a duplicate.

**Comment by emilyrohrbough** [comment]
Closing in favor fo #19070
