### ISSUE TITLE
Performance: preemptively transpile 'the next spec file'

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1917]
Today each spec file is not transpiled until the browser specifically requests it (when Cypress is open and about to start running tests).

Because we know the spec file ahead of time (prior to opening the browser) during a `cypress run`, we should preemptively transpile it ahead of time so by the time the browser requires it, it'll be ready to be served (or have failed and we can immediately display the error message).

**Comment by bahmutov** [comment]
👍👍👍

**Comment by brian-mann** [comment]
Can also do this for `cypress open` by kicking off the spec transpilation process in `open_project.coffee` the `launch` function

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close this issue.
