### ISSUE TITLE
After updating Cypress package 9.1.0, build failed on Jenkins while Docker build. 

### ISSUE THREAD

**Issue by isatmun** [cypress-io/cypress#19176]
### Current behavior

![Screenshot 2021-12-01 at 17 12 11](https://user-images.githubusercontent.com/95216632/144281534-28c5de43-2104-4078-bc39-e721ac24d9b0.png)

[FAILED] Error: ENOSPC: no space left on device, write

[FAILED] 

[FAILED] ----------

[FAILED] 

[FAILED] Platform: linux-x64 (Alpine Linux - 3.13.5)

[FAILED] Cypress Version: 9.1.0

The Cypress App could not be unzipped.

### Cypress Version

9.1.0

### Package Manager

npm

### Operating system

Linux

**Comment by legap** [comment]
Hi @isatmun

It looks like you're running out of disk space on the host system.

Try to do a `df -h` to see the available space left on your system.

These command could further help you to analyse the problem (run it in the directory where your package.json is):
```
# show the path to the cypress cache
npx cypress cache path

# show a list of already cached binaries including its size
npx cypress cache list --size
```

Hope that helps.

**Comment by flotwig** [comment]
Closing since this is not actionable and stale.
