### ISSUE TITLE
Cypress.config("defaultCommandTimeout", 15000) does not work in it() function

### ISSUE THREAD

**Issue by myildizCH** [cypress-io/cypress#19171]
### Current behavior

When  Cypress.config("defaultCommandTimeout", Number) is used inside an it() function, it does not override global default defaultCommandTimeout value.

Ex: 

```
it("Login should be successful with valid credentials C115", () => {
    Cypress.config("defaultCommandTimeout", 15000);
    SignInPage.emailInput().type(email);
    SignInPage.passwordInput().type(password);
    SignInPage.continueButton().click();
    SignInPage.logo().should("be.visible");
  });
```

### Desired behavior

For the example above, the it function should have 15000 ms of timeout but it is instead default timeout of 6000ms.

### Test code to reproduce

```
it("Login should be successful with valid credentials C115", () => {
    Cypress.config("defaultCommandTimeout", 15000);
    SignInPage.emailInput().type(email);
    SignInPage.passwordInput().type(password);
    SignInPage.continueButton().click();
    SignInPage.logo().should("be.visible");
  });
```

### Cypress Version

9.1.0

**Comment by jennifer-shehane** [comment]
The default command timeout applies to each individual Cypress command that is run within the test, not the entirety of the `it` function itself.
