### ISSUE TITLE
cy.intercept fails to respond with JSON containing tilde (~) in string property

### ISSUE THREAD

**Issue by LoaderB0T** [cypress-io/cypress#19178]
### Current behavior

When intercepting a request and responding with a JSON that contains a tilde an error is thrown.
```
cy.intercept("GET", "localhost/123", (res) => {
      res.reply({
        bla: "~",
      });
    });
```

`VM263:1 Uncaught (in promise) SyntaxError: Unexpected token x in JSON at position 9`

This seems to be a regression in 9.1.0, in 9.0.0 this executes just fine.

### Desired behavior

No error, the response contains the correct object with a tilde.

### Test code to reproduce

Repro repo: https://github.com/LoaderB0T/cypress-tilde-regression

### Cypress Version

9.1.0

**Comment by LoaderB0T** [comment]
Probably related to #19170

**Comment by chrisbreiding** [comment]
This seems to be a regression in 9.1.0.

Similar issues using different commands:

- #19083
- #19084
- #19115
- #19096
