### ISSUE TITLE
Does cypress support authorized websocket?

### ISSUE THREAD

**Issue by Piyush12011990** [cypress-io/cypress#19188]
### Current behavior

I want to established authorized  websocket in cypress
url: ws://localhost:8080/ws
Headers:
Authorization : Bearer token
Message:
{"type": "command","data": {"services": [{"name": "point" }]}}

If this is possible, please share link for the same

### Test code to reproduce

https://github.com/cypress-io/cypress/issues/2492

### Cypress Version

8.6.0

**Comment by sainthkh** [comment]
Sorry for the late reply. 

But it's a bit hard for me to understand what is being tested with the description above. 

If you're trying to mock your websockets with auth toke like `new WebSocket("ws://www.example.com/socketserver", ["access_token", "3gn11Ft0Me8lkqqW2/5uFQ="]);`, then it could be solved with `mock-socket` library [like this in the comment here](https://github.com/cypress-io/cypress/issues/2492#issuecomment-888089499).

**Comment by sainthkh** [comment]
Closing because of the inactivity.
