### ISSUE TITLE
Cypress 9 electron not sending full headers when on http site

### ISSUE THREAD

**Issue by pmerwin** [cypress-io/cypress#19197]
### Current behavior

We run our site as http in our github actions and all works great with chrome, and was fine with electron until vs 9.

With vs 9 on electron we get CORS issues and our endpoint returns an unauthorized to electron, but all is well with chrome 96 and FF.
Explained here:

https://share.getcloudapp.com/YEuP0GPz

...also, going back to cy 8.6 works.

 cy:xhr (K): POST https://api.adept.at/web/login
                        Status: 200 - OK
        cy:command (K): wait	@token
          cy:fetch (!): (token) GET https://api.adept.at/web/token
                        Status: 401
                        Response body: {
                          "message": "Unauthorized"
                        }
        cons:error (X): Error: Unable to retrieve token for session

Electron (fails): Missing header info (cookie)
Accept: /
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Connection: keep-alive
Host: api.adept.at
Referer: http://learn.adept.at:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Adept
x-datadog-origin: rum
x-datadog-parent-id: 2670188163476211859
x-datadog-sampled: 1
x-datadog-sampling-priority: 1
x-datadog-trace-id: 6190204999158093994

Chrome ( succeeds )
Accept: application/json, text/plain, /
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 71
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Cookie: removed by me for security
Host: api.adept.at
Referer: http://learn.adept.at:3000/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Adept
x-datadog-origin: rum
x-datadog-parent-id: 9059599271481811950
x-datadog-sampled: 1
x-datadog-sampling-priority: 1
x-datadog-trace-id: 2025085556435353620

### Desired behavior

Cy 9 electron should send same headers as chrome 96, specifically cookie data

### Test code to reproduce

Run our site as http hitting our https backend see above ^

### Cypress Version

9

**Comment by pmerwin** [comment]
Anyone have a chance to take a look at this?

**Comment by pmerwin** [comment]
@froggman2k Our site works over electron with cypress when it is using https, our issue is, we run our site http in github actions, and we can no longer use electron as the browser there due to this issue. Curious, if you use https for your site does that work and th headers are correct for you as well?

**Comment by RalphBragg** [comment]
Hi - i now have same issue which is blocking automation testing (unfortunately) is there any known workaround for this?

**Comment by ldeveber** [comment]
We are still seeing this in both electron and chrome as of 9.7. Downgrading to 8.7 and using electron works for us currently, but we're stuck on that version until this is fixed :(
