### ISSUE TITLE
Option to see git status changes by color

### ISSUE THREAD

**Issue by conversayShawn** [cypress-io/cypress#19194]
### What would you like?

User requests to have the option to see the changes in GitHub by color in the App
![image](https://user-images.githubusercontent.com/48733734/144440997-84f49dc3-7914-4a77-a836-b2761899b124.png)
similar to what is seen in the Cloud
![image](https://user-images.githubusercontent.com/48733734/144441177-19d42246-cad3-44d0-9556-6607a60ae3d9.png)

### Why is this needed?

Use case:
User would like to have a toggle button or something similar in the interface to show the changed files for locally run tests to increase productivity

### Other

Additional information is available internally via Support ticket

**Comment by jennifer-shehane** [comment]
We have actually built this into the App since then. You can see when last changes were made to files.
