### ISSUE TITLE
Enable stubbing all kinds of HTTP requests (not just XHR)

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress#192]
Currently, cypress can only stub out XHRs but it would be great if it also did the same for static resources like js files.

In our case, we would like to stub a static js file URL that returns test content to check if our server-side code behaves well or fails in a reliable fashion if the js is an older/non-standard version.

**Comment by brian-mann** [comment]
This is now possible to do now that [`0.17.0`](https://github.com/cypress-io/cypress/wiki/changelog#0170-08302016) is out. It's on our radar.

**Comment by paulpruteanu** [comment]
Any update on this one?

**Comment by brian-mann** [comment]
Closing this in favor of this proposal which goes into a lot more detail: https://github.com/cypress-io/cypress/issues/687
