### ISSUE TITLE
Popover created with Popper is considered hidden when it rendered over the boundary of an overflow container

### ISSUE THREAD

**Issue by arrocke** [cypress-io/cypress#19204]
### Current behavior

You can see the dropdown menu renders under the button that opens it. The table has overflow scroll on bigger tables, but Popper is able to render this popover without it clipping so the element is visible. However, here Cypress considers this a hidden element.

![popper-cypress](https://user-images.githubusercontent.com/11968925/144490162-43323c6d-abeb-475c-8a8b-3f3ffe284771.png)

### Desired behavior

This is probably a real edge case, but it would be nice in this situation that the element would be considered visible. The alternative is to add `{ force: true }` to click this element

### Test code to reproduce

Here is a [reproduction](https://github.com/pivot-interactives/cypress-test-tiny)

Run `npm run dev` before running cypress

### Cypress Version

9.1.0

**Comment by CesarLanderos** [comment]
having this issue too, on v9.5.3
