### ISSUE TITLE
Why I am not able to interact with cypress/base container?

### ISSUE THREAD

**Issue by malmuzaini** [cypress-io/cypress#1920]
I am working on executing e2e testing on our Jenkins pipline. However, I want to run the cypress/base container locally on my machine and interact with it by running this command
“docker container run —rm -it cypress/base:10”
I should be able to interact with the container through the shell, but I am not!!

**Comment by brian-mann** [comment]
I am pretty sure our docker containers are like any other docker container. They are downloaded and used thousands of times in CI per day.

Maybe you could go into more detail about: 

> I should be able to interact with the container through the shell, but I am not!!

What does this mean?

**Comment by Bkucera** [comment]
@malmuzaini i believe you are looking for:
```
docker run -it cypress/base:8 bash
```
Here is the [Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/base/8/Dockerfile) used to build that image
