### ISSUE TITLE
Unification App: Write E2E tests around "Runs"

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#19216]
### What would you like?

Write end-to-end tests to cover the new Unification work in 10.0-release branch for "[Runs](https://docs.google.com/spreadsheets/d/1iPwi89aW6aYeA0VT1XOhYdAWLuScW0okrlfcL9fzh3s/edit#gid=0)" in the App.

**Comment by ryanthemanuel** [comment]
The remaining work is going to be done by @elevatebart and tracked elsewhere
