### ISSUE TITLE
Unification App, Test Runner: Write E2E tests around "Reporter Header"

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#19218]
### What would you like?

Write end-to-end tests to cover the new Unification work in 10.0-release branch for "[Reporter Header](https://docs.google.com/spreadsheets/d/1iPwi89aW6aYeA0VT1XOhYdAWLuScW0okrlfcL9fzh3s/edit#gid=0)" in the App's Test Runner.

**Comment by ryanthemanuel** [comment]
The current PR contains component tests for the spec list. It does not contain any end to end tests
