### ISSUE TITLE
Cypress Component Testing seems to ignore `watchForFileChanges: false`

### ISSUE THREAD

**Issue by obeobe** [cypress-io/cypress#19220]
### Current behavior

Setting `watchForFileChanges` to `false` seems to have no effect in component testing (i.e. when starting Cypress with `npx cypress open-ct`).

It *does* work with regular Cypress (i.e. `npx cypress open`).

I tried with and without adding it under the `component` key in addition to root - and in both cases it didn't work.

### Desired behavior

Cypress should not refresh and restart the test when the spec file changes when the `watchForFileChanges` flag is set to false.

### Test code to reproduce

My `cypress.json`:
```
{
	"watchForFileChanges": false,
	"experimentalStudio": true,
	"integrationFolder": "cypress/integration",
	"video": false,
	"defaultCommandTimeout": 8000,
	"component": {
		"watchForFileChanges": false,
		"defaultCommandTimeout": 10,
		"viewportHeight": 500,
		"viewportWidth": 700
	}
}
```

Code:
```
describe("test", () => {
    it("test", () => {
        expect(42).to.equal(42);
    });
});
```

And then make a change in the file, and save.

### Cypress Version

8.7.0 (currently the latest 8.* version)

### Other

It's a big issue because IntelliJ saves files automatically and it causes many undesired refreshes.

**Comment by lmiller1990** [comment]
For now you can do it on a dev server basis:

- [webpack docs](https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr) `hot: false`
- [vite](https://vitejs.dev/config/server-options.html#server-hmr) `server: { hmr: false }`

We should fix this.
