### ISSUE TITLE
How to test custom events?

### ISSUE THREAD

**Issue by 4z5lz** [cypress-io/cypress#1922]
Hi!

I want to test application that fire custom events.
How can I catch them (".on" ?) in Cypress?

Thanks

**Comment by brian-mann** [comment]
Cypress has native access to your application, the same way your application has access to the window.

If you rephrase the question: "How can I test that custom events are firing on my DOM elements in javascript" the answer would be the same.

```js
cy.window().then((win) => {
  // listen for events bubbling up to the window
  win.addEventListener(...) 
  Cypress.$(win).on(...)
})
```

or directly on your DOM elements...

```js
cy.get('button').then(($button) => {
  $button.get(0).addEventListener(...) 
  $button.on(...)
})
```

**Comment by 4z5lz** [comment]
thank you very much!

**Comment by codeofsumit** [comment]
hey @brian-mann, where is `Cypress.$(foo).on(...)` documented?
I'm searching for the guide/docs section to find out how I can "export" variables from it for the rest of my test (like a JS object from a library I accessed via the window)

**Comment by jennifer-shehane** [comment]
@codeofsumit You can proxy jQuery methods using `Cypress.$` as documented here: https://on.cypress.io/$

**Comment by jnnnnn** [comment]
@brian-mann This approach creates an event handler that will validate that the event is correct. 

I can't figure out how to check if the custom event completely fails to be triggered at all.

**Comment by jnnnnn** [comment]
I finally got it working properly. It wasn't fun, I'm all ears if there's a better way to validate a custom event.

```js
// set up (and clean up) a mock event listener
const container = {};
cy.window().then(win => {
  const listener = e => {
    win.removeEventListener("MyNotification", listener);
    container.e = e;
  };
  win.addEventListener("MyNotification", listener);
});

// application (asynchronously) fires the event on click (or whatever)
cy.get("#notificationButton").click();

// this should retries until container has an event in it.
// there's quite a lot going on here -- the JavaScript event loop is firing the event
// and the Cypress event loop is polling the container until it has a value
cy.wrap(container).should(container => expect(container.e).not.to.be.undefined);

// Add one more statement to the Cypress event loop to validate the event from the JavaScript event loop
cy.wrap(container).then(container => validateEvent(container.e));
```

**Comment by adambondarzewski** [comment]
Is it possible to use event value as described [here](https://shiny.rstudio.com/articles/js-events.html) for `shiny:value` event?

```
// use event.target to obtain the output element
$(document).on('shiny:value', function(event) {
  // cancel the output of the element with id 'foo'
  if (event.target.id === 'foo') {
    event.preventDefault();
  }
});
```

**Comment by bjankord** [comment]
To expand on @brian-mann's comment, I was apply to successfuly spy on on custom event with the following code:
```js
cy.window().then((win) => {
      const gClickEventHandlerMock = cy.spy()
      Cypress.$(win).on('gClick', gClickEventHandlerMock)

      cy.get('g-button')
        .click()
        .then(() => {
          expect(gClickEventHandlerMock).to.be.calledOnce
        })
    })
```

**Comment by Xusr404** [comment]
@brian-mann it works fine for me when i replace 'calledOnce' with 'calledAfter'
Now i want to replace the get command with a var/const that i can put that into a "function"/cypress custom Command:

`const executeCommand = cy.get('.screen__tab-bar').contains(Cypress.env('test')).parent();

cy.window().then((win) => {
            const gClickEventHandlerMock = cy.spy();
            Cypress.$(win).on('screenDidAppear', gClickEventHandlerMock);
      
            executeCommand
              .click()
              .then(() => {
                expect(gClickEventHandlerMock).to.be.calledAfter
            });
        });`

I always get the error message "cy.click() failed because it requires a DOM element. The subject received was:  > <window>"
I also tried it with:
`cy.window().then((win) => {
            const gClickEventHandlerMock = cy.spy();
            Cypress.$(win).on('screenDidAppear', gClickEventHandlerMock);
      
            executeCommand
              .click.call()
              .then(() => {
                expect(gClickEventHandlerMock).to.be.calledAfter
            });
        });`
but its the same problem.
What do i have to change?

**Comment by yasinitskyi** [comment]
> @brian-mann it works fine for me when i replace 'calledOnce' with 'calledAfter'
> Now i want to replace the get command with a var/const that i can put that into a "function"/cypress custom Command:
> 
> ```js
> const executeCommand = cy.get('.screen__tab-bar').contains(Cypress.env('test')).parent();
> 
> cy.window().then((win) => {
>             const gClickEventHandlerMock = cy.spy();
>             Cypress.$(win).on('screenDidAppear', gClickEventHandlerMock);
>       
>             executeCommand
>               .click()
>               .then(() => {
>                 expect(gClickEventHandlerMock).to.be.calledAfter
>             });
>         });
> ```
> 
> I always get the error message "cy.click() failed because it requires a DOM element. The subject received was: > "
> I also tried it with:
> 
> ```js
> cy.window().then((win) => {
>             const gClickEventHandlerMock = cy.spy();
>             Cypress.$(win).on('screenDidAppear', gClickEventHandlerMock);
>       
>             executeCommand
>               .click.call()
>               .then(() => {
>                 expect(gClickEventHandlerMock).to.be.calledAfter
>             });
>         });
> ```
> 
> but its the same problem.
> What do i have to change?

Where are you creating screenDidAppear event? Is it working?

**Comment by gromann** [comment]
Hi, I was able to solve this for my vue app using kuker emitters. Also described in one of the cypress articles. 
You can use this emitters like this: 
````

et kukerEvents
           let vueEvents
           beforeEach(() => {
               kukerEvents = []
               vueEvents = []
               cy.visit('https://the-koi.com/playground', {
                   onBeforeLoad (win) {
                       const postMessage = win.postMessage.bind(win)
                       win.postMessage = (what, target) => {
                       // check if the event is a kuker event
                           if (isKuker(what)) {
                               let raw = Cypress._.pick(what,  'state');
                               let obj = null
                               try{
                               	// save events with a payload here
                                   obj = JSON.parse(raw.state);
                                   vueEvents.push(obj)
                               }catch(e){
                                   console.log(e);
                               }
                               // save all the events here
                               // you would not need them, 
                               // this is just interesting to get a deeper insight
                               // into vue
                               kukerEvents.push(Cypress._.pick(what, 'label', 'state'))
                           }
                           return postMessage(what, target)
                       }
                       // save for sync
                       cy.spy(win, 'postMessage').as('postMessage')
                   }
                   })
           });

````
Since I had serious issues with that and it took me days of trial and error I also wrote an article about it here: https://www.the-koi.com/projects/cypress-listen-to-events-from-dom-elements/
I hope cypress will have an better support for this important feature soon.
