### ISSUE TITLE
Allow Users to set browserDependencies in configuration file.

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19242]
# What would you like?

Users should be able to set the `browserDependencies` config in the cypress.js/ts config file.

The `browserDependencies` config should be made available in the application. 

# Why is it needed?

The `browsersDependencies` config is required to know what version of a browser a user wishes to test against.

**Comment by jennifer-shehane** [comment]
Closing as this is no longer planned work.
