### ISSUE TITLE
Do not throw error when using `scrollTo` on non-scrollable elements

### ISSUE THREAD

**Issue by Clem-D** [cypress-io/cypress#1924]
### Current behavior:
When someone using "scrollTo" on a non-scrollable element we get the following error : 

```
Error: CypressError: Timed out retrying: cy.scrollTo() failed because this element is not scrollable: <window>
```

### Desired behavior:
No error. It just does nothing.
I use `scrollTo` on an element which can contain sometimes 0 and sometimes +100 elements. So I don't know by advance if the window will be scrollable or not... 
It could be nice to not have any error or having an option to bypass this error.

### Versions
* Cypress :  2.1.0
* OS : CentOS Linux release 7.5.1804 (Core)
* Browser : Google Chrome version 67

┆Issue is synchronized with this [Jira Story](https://cypress-io.atlassian.net/browse/TR-130) by [Unito](https://www.unito.io/learn-more)

**Comment by hieuTranEnouvo** [comment]
Hello,

I still got this issue on 
Versions
Cypress : 4.0.1
OS : MAC
Browser : Google Chrome version 80

pls help me the issue

**Comment by jennifer-shehane** [comment]
Repro:

```html
<html>
<body>
</body>
</html>
```

```js
it('does not error on scroll', () => {
  cy.visit('index.html')
  cy.scrollTo(0, 500)  
})
```

**Comment by jennifer-shehane** [comment]
The code for this is done in [cypress-io/cypress#8003](https://github.com/cypress-io/cypress/pull/8006), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
