### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by SwethaGotety** [cypress-io/cypress#19250]
### Current behavior

This is the error in my command prompt when tried to install cypress through npm.

C:\Users\MMMM\Desktop\Myrepo_IQHive\IQHiveNewRepo>npm install cypress --save-dev
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! code 1
npm ERR! path C:\Users\MMMM\Desktop\Myrepo_IQHive\IQHiveNewRepo\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! Note: Overriding Cypress cache directory to: C:\Users\MMMM\AppData\Local\Cypress\.cypress-cache
npm ERR!
npm ERR!       Previous installs of Cypress may not be found.
npm ERR!
npm ERR! ‼ Warning: Forcing a binary version different than the default.
npm ERR!
npm ERR!   The CLI expected to install version: 9.1.1
npm ERR!
npm ERR!   Instead we will install version: C:\Users\Arvind\AppData\Local\Cypress\Cache\8.7.0\Cypress.exe
npm ERR!
npm ERR!   These versions may not work properly together.
npm ERR!
npm ERR! Installing Cypress (version: C:\Users\MMMM\AppData\Local\Cypress\Cache\8.7.0\Cypress.exe)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be downloaded.
npm ERR!
npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR!
npm ERR! Otherwise, please check network connectivity and try again:
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! URL: https://download.cypress.io/desktop/C:/Users/MMMM/AppData/Local/Cypress/Cache/8.7.0/Cypress.exe?platform=win32&arch=x64
npm ERR! Error: Failed downloading the Cypress binary.
npm ERR! Response code: 404
npm ERR! Response message: Not Found
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Platform: win32-x64 (10.0.19042)
npm ERR! Cypress Version: 9.1.1
npm ERR! [FAILED] The Cypress App could not be downloaded.
npm ERR! [FAILED]
npm ERR! [FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR! [FAILED]
npm ERR! [FAILED] Otherwise, please check network connectivity and try again:
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] URL: https://download.cypress.io/desktop/C:/Users/MMMM/AppData/Local/Cypress/Cache/8.7.0/Cypress.exe?platform=win32&arch=x64
npm ERR! [FAILED] Error: Failed downloading the Cypress binary.
npm ERR! [FAILED] Response code: 404
npm ERR! [FAILED] Response message: Not Found
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] Platform: win32-x64 (10.0.19042)
npm ERR! [FAILED] Cypress Version: 9.1.1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MMMM\AppData\Local\npm-cache\_logs\2021-12-04T06_14_43_584Z-debug-0.log

C:\Users\MMMM\Desktop\Myrepo_IQHive\IQHiveNewRepo>

### Cypress Version

9.1.0

### Package Manager

npm

### Operating system

Windows

**Comment by legap** [comment]
Hi @SwethaGotety

It looks like you have set an environment variable to a cypress binary that has a different version number to the one in the package.json.

See the section about [Enviroment variables](https://docs.cypress.io/guides/getting-started/installing-cypress#Environment-variables) for details.

I would recommend that you either unset the variable `CYPRESS_INSTALL_BINARY` or point it to a valid binary for version 9.1.1:
```
# unset the variable
CYPRESS_INSTALL_BINARY=

# set it to a valid cypress binary for version 9.1.1
CYPRESS_INSTALL_BINARY=<path_to_your_binary>
```

Hope that helps.

**Comment by ejjaganisairam** [comment]
I am unable to install cypress with error 

npm ERR! code 1
npm ERR! path D:\cypress\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! Installing Cypress (version: 12.17.3)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be downloaded.

**Comment by nagash77** [comment]
HI @ejjaganisairam can you provide any other information?  There is not enough here for us to reproduce this issue.  Have you tried again after waiting awhile for any potential connection problems on either end to possibly resolve?  The information provided isn't enough for us to go off of unfortunately.
