### ISSUE TITLE
Scroll into view doesn't work on my website when using cypress

### ISSUE THREAD

**Issue by yarusl** [cypress-io/cypress#19255]
### Current behavior

Not scrolling when I click a button on the website I'm trying to test. 
Tried using: 
* cy.window().then((win) => {
* .trigger("click")
* click 
* click force
* click with position

Before and after the click I wait for two second. When debugging  it's clear that the click itself works and I see that it runs scrollIntoView, but nothing happens. When I click the button manually the scroll works

### Desired behavior

There is a scrollIntoView on the website I'm testing and when clicking a specific element it should scroll. 

### Test code to reproduce

cy.get('[data-cy="some-element"]').trigger("click");

### Cypress Version

9.0.0

**Comment by sainthkh** [comment]
Can you provide a reproducible example? 

As we all know, debugging starts with reproducing the problem on the developer's environment.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
