### ISSUE TITLE
I have problem when I am using Cypress Testing Library

### ISSUE THREAD

**Issue by ahmedelamine** [cypress-io/cypress#19257]
### Current behavior

TypeError:
cy.findByRole is not a function

### Desired behavior

I am getting this error even I am using the cypress testing library as in the [docs](https://testing-library.com/docs/cypress-testing-library/intro/)
I have added this line to project cypress/support/commands.js:
`import` '@testing-library/cypress/add-commands';

And in my test, I use it like this

```
describe("App", () => {
  it("user can fetch stories", () => {
    cy.visit("http://localhost:3000/");
    
    cy.findByRole("button", { name: /fetch stories/i }).click();
  });
});
```

then when I run the test I get this error
`TypeError: cy.findByRole is not a function

### Test code to reproduce

```
describe("App", () => {
  it("user can fetch stories", () => {
    cy.visit("http://localhost:3000/");
    
    cy.findByRole("button", { name: /fetch stories/i }).click();
  });
});
```

### Cypress Version

9.1.1

**Comment by ahmedelamine** [comment]
I fix it, by adding an index.js file in cypress/support/

```
// cypress/support/index.js

import "./commands";
```

**Comment by np185092** [comment]
Hi,

even after adding the above file. still getting the same issue

**Comment by zeyasar** [comment]
@np185092 I fixed the problem by adding the "import '@testing-library/cypress/add-commands' line to the cypress/support/command.ts " file

**Comment by MuhtasimMusfiqZarab** [comment]
[ahmedelamine](https://github.com/ahmedelamine)
This is the way to resolve this issue:
-` yarn add --dev cypress @testing-library/cypress` or `npm install --save-dev cypress @testing-library/cypress`
-Add this line to your project's cypress/support/commands.js:    `import '@testing-library/cypress/add-commands'`
-Typings should be added as follows in tsconfig.json:
```
{
  "compilerOptions": {
    "types": ["cypress", "@testing-library/cypress"]
  }
}
```

**Comment by ericcmmi** [comment]
With Cypress 10.8.0 I added "import "@testing-library/cypress/add-commands";" to cypress/support/e2e.ts which worked for me.

**Comment by bsnahrwold79** [comment]
I am having the same problem but I am using javascript, not typescript. Here is my set up:
I installed:
`npm install --save-dev @testing-library/cypress`

I have updated my project files as follows:  
**/cypress/support/commands.js:**
`import '@testing-library/cypress/add-commands'`

**/package.json:** (updated after install)
```
"devDependencies": {
  "@testing-library/cypress": "^9.0.0"
}
```
**My test contains:**
```
describe('example use of cypress testing library', () => {
  it('gets cypress.io text', () => {
    cy.visit('/') // baseUrl in cypress.config.js set to 'https://example.cypress.io'
    cy.findByText('cypress.io')
  })
})
```
I have restarted my terminal window and relaunched vs code. I still get the error:
`TypeError: cy.findByText is not a function.`
  
Does this work with JavaScript or only TypeScript?

**Comment by Tbaut** [comment]
This was solved for me adding `/// <reference types="@testing-library/cypress" />` to `the command.ts`.

So the command.ts now looks like:
```ts
/// <reference types="@testing-library/cypress" />
/// <reference types="cypress" />

import '@testing-library/cypress/add-commands'
```


Thanks to https://github.com/testing-library/cypress-testing-library/issues/227#issuecomment-1260723693

**Comment by falcondpr** [comment]
Thanks, this worked for me
