### ISSUE TITLE
After click Page URL,tab and Iframe is not getting changed

### ISSUE THREAD

**Issue by atulpatil33347** [cypress-io/cypress#19251]
### Current behavior

On click action
All the content of the page B is displayed correctly, but URL,tab and iframe are not changed. Cypress is 
not able to detect the elements on page B. Page B is still showing the 'pageA_iframe' in the cypress 
runner dom.

### Desired behavior

On page A, we perform the click action on the element which is in iframe 'pageA_iframe'. On this click
the user should get navigated to page B and the page url should change from '/pages/A' to 'pages/B' and 
the navigation tab should change from 'tabA' to 'tabB' and the content should be displayed which is in 
pageB_iframe' iframe.

URL :- '/pages/A' --> 'pages/B'
tab :- 'tabA' --> 'tabB'
iframe :- 'pageA_iframe' -->  'pageB_iframe'

### Test code to reproduce

Cannot give test code

### Cypress Version

cypress@8.7.0

### Other

C. What we tried -
1. Intercepting API's
2. Adding cy.wait()
3. We cannot consider directing visiting pageB url with cy.visit() after click.
4. We do preserve cookies during test run of all test cases. Here we tried adding some adding cookies to preserve list but 
this did not help.
5. We revisited the cypress documentation for iframe interaction.So we do follow all the instruction 
given in the documentation for iframe iteraction.

D. What is the page navigation process
These two pages are angular pages with iframes on it. API's are loaded after token verifications. 

The application works on iframe communication basically a parent-child relationship. The parent site communicates with the website through an iframe and two-way communication is established between them once the authentication is done successfully.
Once the user clicks on the menu tab, a request message is sent by the parent site to the child site (via post message commands), the child after validating the received message, redirects to the URL and changes the tab as requested by the parent.
Similarly, if a change is requested by the child to the parent, a similar process is followed.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I guess [cypress-iframe](https://www.npmjs.com/package/cypress-iframe) might help solve your problem.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
