### ISSUE TITLE
The function cy.should('have.css', 'width',...) does not return the value viewed on Chrome dev tool

### ISSUE THREAD

**Issue by thienthu1410** [cypress-io/cypress#19256]
### Current behavior

Given an element has info css.width viewed on Chrome dev tool is `112.797px`
Then I write this step verification: `cy.get(...).should.('have.css', 'width', '112.797px)'`

When I run the test on cypress, the cypress failed the above step as cypress detect the width is `112.796875px`

### Desired behavior

Cypress should returned the value width that is shown on Chrome dev tool

### Test code to reproduce

![image](https://user-images.githubusercontent.com/15967414/145380879-4b9dfabf-447a-4ff8-9d08-0daf5ffd8d78.png)

![image](https://user-images.githubusercontent.com/15967414/144741566-7e9e5f13-0bd8-4514-b5cd-c8f492782f2f.png)

### Cypress Version

9.1.1

**Comment by sainthkh** [comment]
I tested with the code below and found out that it's something that cannot be handled with Cypress because Chrome and Firefox handle them differently.

```html
<style>
  #t {
    width: 3.14159265353979px;
    height: 10px;
    background: read
  }
  #t2 {
    width: 1.234567891px;
  }
</style>
<div id="t"></div>
<div id="t2"></div>
```

**Result:**

| | t | t2 |
| ---- | ---- | ---- |
| Chrome | 3.14062 | 1.23438 |
| Firefox | 3.13333 | 1.23333 |

I suggest to round the result like below:

```js
cy.get('#t').then(($el) => {
  expect($el.get(0).offsetWidth).to.eq(3)
})
```

**Comment by thienthu1410** [comment]
ok let me check

**Comment by sainthkh** [comment]
Do `querySelector()` and `$el.get(0)` return the same element?

**Comment by thienthu1410** [comment]
Hi @sainthkh ,
 I think they are the same element, as I have checked carefully on cypress and chrome dev tool. I use the same selector string, and I see that only one element is returned. Ah may be my test application has the issue on loading, which lead to the width changing. I just notice that. Thanks for your supporting. I will close this ticket
