### ISSUE TITLE
cypress while taking screenshot content not appear

### ISSUE THREAD

**Issue by Eshicagupta3** [cypress-io/cypress#19252]
### Current behavior

content is missing between

 cy.get('.returnReasons-reasonContainer')
        .screenshot('return_reasons')

### Desired behavior

should take screenshot whole div

### Test code to reproduce
![image](https://user-images.githubusercontent.com/15893080/144713368-1f58ba35-34e0-4447-bdd2-4361e68f80ae.png)

![image](https://user-images.githubusercontent.com/15893080/144713375-a092e9a4-fee7-4827-9615-ca1d1f95be88.png)

 cy.get('.returnReasons-reasonContainer')
        .screenshot('return_reasons')

### Cypress Version

 "cypress": "^9.0.0",

### Other

 "@babel/preset-env": "^7.16.0",
    "@cypress/code-coverage": "^3.9.11",
    "@myntra/eslint-config-standard": "^1.13.78",
    "@types/cypress-image-snapshot": "^3.1.6",
    "@types/node": "^16.11.7",
    "@typescript-eslint/eslint-plugin": "^5.3.1",
    "@typescript-eslint/parser": "^5.3.1",
    "cypress": "^9.0.0",
    "cypress-image-snapshot": "^4.0.1",
    "dotenv": "^10.0.0",
    "dotenv-json": "^1.0.0",
    "eslint": "8.2.0",
    "husky": "^7.0.4",
    "inquirer": "^8.2.0",
    "lint-staged": "^12.0.2",
    "typescript": "4.4.4"

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Can you provide a reproducible example? With only those screenshots, it's hard to check what caused the problem. As we all know, debugging starts with reproducing the problem on the developer's environment.

**Comment by Eshicagupta3** [comment]
"viewportHeight": 1000,
  "viewportWidth": 1280,
for this viewport if am taking screenshot . it is not taking whole element.. some bottom part become white

but if am changing my  viewport size "viewportHeight": 1000,
  "viewportWidth": 660, then it works perfectly fine

**Comment by Eshicagupta3** [comment]
Viewport -[1200,900]
<img width="836" alt="Screenshot 2021-12-07 at 11 49 02 AM" src="https://user-images.githubusercontent.com/15893080/144977055-5e18bf26-9d48-4af4-9fb2-9cd161160ba3.png"> 


viewport [1280, 1000]
<img width="836" alt="Screenshot 2021-12-07 at 11 49 10 AM" src="https://user-images.githubusercontent.com/15893080/144977142-5ca3b4d7-0d73-4030-85bf-f71dce2b43e1.png">

for this viewport if am taking screenshot . it is not taking whole element.. some bottom part become white

but if am changing my  viewport size "viewportHeight": [1000, 660] or [1200, 900]
then it works perfectly fine

**Comment by sainthkh** [comment]
Confirmed with the code below:

```js
it('t', () => {
  cy.visit('https://cypress.io')
  cy.get('.DifferencesList-pwmmfx-0 .container').screenshot()
})
```

It should take the screenshot like below:

![image](https://user-images.githubusercontent.com/8130013/145495173-29b16f1f-19a2-4a2d-8b42-eacbbd322148.png)

But it was a simple line:

![image](https://user-images.githubusercontent.com/8130013/145495307-c626f198-f00c-4ac3-b113-f1e1f71e3a08.png)

**Comment by Lyokolux** [comment]
I am also facing this issue: if I set the viewport size with

```ts
export default defineConfig({
  viewportWidth: 1920,
  viewportHeight: 1080,
})
```

and use `cy.screenshot({ capture: 'viewport'})`

then the screenshot size is `1280x720` instead of the viewport size.
