### ISSUE TITLE
Cypress creates a new line (<br> tag) after entering the first letter of a word in text area.

### ISSUE THREAD

**Issue by Pankajshuklaqa** [cypress-io/cypress#1926]
### Current behavior:
Cypress creates a new line after entering the first letter of a word.
![screen shot 2018-06-11 at 4 53 27 pm](https://user-images.githubusercontent.com/30429058/41229403-7e487492-6d99-11e8-9aa5-a0ec6ad18417.png)

### Desired behavior:
The code should not create new line and enter letter like "Who" 
not like "W
ho"

### Steps to reproduce:

Code:-
```js
cy.get("<text area locator>").should('be.visible')
        .type("Who", { force: true })
```

The above code is creating a new line after entering 'W' letter.
```
W
ho
```

### Versions
Cypress: 3.1.0
Operating System: MacOS Sierra v10.12.6 (16G1212)
Browser: Chrome v66.0.3359.181 (Official Build) (64-bit)

**Comment by davidzambrana** [comment]
This is also happening to me. The field I type into is

`<div aria-describedby="placeholder-rq89" class="notranslate public-DraftEditor-content" contenteditable="true" role="textbox" spellcheck="true" style="outline: none; user-select: text; white-space: pre-wrap; word-wrap: break-word;"><div data-contents="true"><div class="classname" data-block="true" data-editor="rq89" data-offset-key="67lbi-0-0"><div data-offset-key="67lbi-0-0" class="public-classname"><span data-offset-key="67lbi-0-0"><span data-text="true">Text here</span></span></div></div></div></div>`

**Versions**

Cypress: 3.0.1
Operating System: Ubuntu Linux 16.04 LTS
Browser: Electron

**Comment by Bkucera** [comment]
may be related to issue in progress #1932

**Comment by Bkucera** [comment]
@Pankajshuklaqa why are you using `{force: true}` ? Cypress should not have to force a type into an element with `contenteditable`

**Comment by Pankajshuklaqa** [comment]
@Bkucera will try to remove `{force: true}`
Yes, `<br>` show up when manually type enter in the field.

here are the event listeners on the element:-

![screen shot 2018-06-18 at 11 57 27 pm](https://user-images.githubusercontent.com/30429058/41554862-a50368ca-7353-11e8-8f7e-9668ca8b36af.png)

**Comment by Bkucera** [comment]
I've got the fix for this coming up in a patch release. Still working on related issues before submitting a PR
