### ISSUE TITLE
Port Cypress studio to unified GUI

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#19263]
Currently, the new `app` does not have support for `experimentalStudio`.

Tasks for porting:

- [ ] Convert React component to Vue
- [ ] Convert server communications to GraphQL (mostly required so we can use the `app` `e2e` tests)
- [ ] Add to `app`

Further tasks:

- [ ] Update Studio to add a Component Testing flow
- [ ] Update broken system-tests and convert to app-e2e tests ( see #18498  )
- [ ] Update UI to more closely match unified UI
- [ ] Clean up implementation

**Comment by AtofStryker** [comment]
currently removing the `runIsolatedCypress` tests in the runner as they are unused. The tests though might provide useful for writing `cy-in-cy` tests for studio. PR is #21638

**Comment by lmiller1990** [comment]
We did this, it's done now, closing.
