### ISSUE TITLE
Example links broken on @cypress/webpack-preprocessor NPM README

### ISSUE THREAD

**Issue by zeptonaut** [cypress-io/cypress#19289]
### Current behavior

1. Go to https://www.npmjs.com/package/@cypress/webpack-preprocessor?activeTab=readme
2. Click on any of the examples (React app, `use-babelrc`, `use-ts-loader`)
3. You're taken to https://github.com/cypress-io/cypress/blob/HEAD/examples/use-babelrc show a Github "can't find this page" screen 

### Desired behavior

For example, for `use-babelrc`, instead of seeing the Github can't find this page screen you should instead see https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor/examples/use-babelrc. Note the `npm/webpack-preprocessor/` part of the path that's missing in the "Current behavior".

### Test code to reproduce

N/A

### Cypress Version

5.10.0

### Other

Strangely, the links _do_ seem to be correct on https://github.com/cypress-io/cypress/blob/master/npm/webpack-preprocessor/README.md. I'm not sure how it's possible that the links work in Github but are incorrect in NPM.

Sorry if this doesn't belong here - I know this tracker isn't for documentation issues, but I thought that because this was a documentation issue pertaining to checked in code, it may make more sense here than in the `cypress-documentation` repo.

**Comment by emilyrohrbough** [comment]
@zeptonaut Thank you for logging this issue. It does appear that the links within the repo are correctly opening where as the paths are incorrect when clicked from the npm page. Its likely caused by the links being relative to the repo's document

```md
- [React app](examples/react-app) shows how to point Cypress at Webpack configuration from `react-scripts` dependency
- [use-babelrc](examples/use-babelrc) shows how to use your project's `.babelrc` with Webpack
- [use-ts-loader](examples/use-ts-loader) shows how to transpile TypeScript specs following [Webpack TypeScript guide](https://webpack.js.org/guides/typescript/)
```
Do you have any interest in contributing the fix to update these links?
