### ISSUE TITLE
Getting Cross Origin policy blocker in chrome browser

### ISSUE THREAD

**Issue by Imamitashish** [cypress-io/cypress#19288]
### Current behavior

we are trying to automate our application unfortunately i am getting cross origin policy blocker with chrome browser.

i have made changes in cypress.json file and add "chromeWebSecurity": false but it is not working.

Application is working fine in other browser.

please find the blow error message for your reference.
Cypress detected a cross origin error happened on page load:

  > Blocked a frame with origin "https://....com" from accessing a cross-origin frame.

Before the page load, you were bound to the origin policy:

  > https://....com

A cross origin error happens when your application navigates to a new URL which does not match the origin policy above.

A new URL does not match the origin policy if the 'protocol', 'port' (if specified), and/or 'host' (unless of the same superdomain) are different.

Cypress does not allow you to navigate to a different origin URL within a single test.

You may need to restructure some of your test code to avoid this problem.

Alternatively you can also disable Chrome Web Security in Chromium-based browsers which will turn off this restriction by setting { chromeWebSecurity: false } in cypress.json.Learn more

### Test code to reproduce

/// <reference types="cypress" />

describe('example to-do app', () => {
    beforeEach(() => {
        Cypress.config('chromeWebSecurity', false);
    })
    it('displays Application is loaded in 20 sec', () => {
        
        
        //cy.visit('https://www.testing.com/tests')
        cy.wait(10000)
        cy.log('page loaded')
    })

    it('displays Application is loaded in 21 sec', () => {
        //cy.visit('https://www.testing.com/tests/')
        cy.wait(10000)
        cy.log('page loaded')
    })
})

### Cypress Version

6.14.13

**Comment by azmath606961** [comment]
@Imamitashish : Were you able to get a workaround for this issue? In my case this was working until chrome v93, but with chrome v94 as the flags SameSiteByDefaultCookies, CookiesWithoutSameSiteMustBeSecure were removed, it is no longer working. Mine has an SSO login which navigates to two super domains. Even though we are getting the token with cy.request and then visit to application page with cy.visit, it is still failing.

Cypress version: 7.1.0 to 7.7.0
Chrome v94 to 99

**Comment by AtofStryker** [comment]
@Imamitashish would you be able to try this with the `experimentalSessionAndOrigin` flag using `cy.origin()`? This should fix your issue and will be generally available in cypress 12. Since there isn't a full reproduction, I am taking a guess that this solves your issue. But if not, please let us know!
