### ISSUE TITLE
Cy.visit () removes query perms  in URL  

### ISSUE THREAD

**Issue by Shahrukhk999** [cypress-io/cypress#19287]
### Current behavior

i was working on a test that that open a new chrome session for a URL for that I created a constant URL like this http://test.com/aaa/bbb and saved values like login password in a variable from Ui and created a URL like this 
http://test.com/aaa/bbb/?proto=rdp&login=${login_}&password=${pass_}
so when I try to visit this by cy.visit()
cypress return this URL `?proto=rdp&login=$[object%20Object]&password=undefined`
cypress removed login_ pass_values from URL and I am not able to access this 

### Desired behavior

Cypress should save query paras value so that we can visit the. desired URL

### Test code to reproduce
```js
it ('GET ssh keys for server',function()
{   cy.viewport(1280, 720)
    const login_= this.login_rdp
//comming from globle variables 
    const pass_ = this.pass_rdp
    cy.log(login_,"login")
    cy.log(pass_)
    cy.log(`http://test.com/aaa/bbb?id=${idp}`)
   
    cy.visit(`/pamwebclient?proto=rdp&login=${login_}&password=${pass_}`)
   
    cy.get('#btn-connect').click()
    
})
```

### Cypress Version

Cypress package version: 8.7.0 Cypress binary version: 8.7.0 Electron version: 14.1.0 Bundled Node version: 14.17.0

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I tried to reproduce the problem with the code below:

```js
it('t', () => {
  cy.visit('https://www.google.com/search?q=cypress')
})

it('t', () => {
  cy.visit('/fixtures/a.html?a=b&c=d')
})

```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div id="result"></div>
</body>
<script>
const urlSearchParams = new URLSearchParams(window.location.search);
const params = Object.fromEntries(urlSearchParams.entries());

const result = document.getElementById('result');
result.innerHTML = JSON.stringify(params);
</script>
</html>
```

But both worked correctly. Can you provide a working code example? 

Maybe it's not working on the server-side because it's ID & password for security reasons.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
