### ISSUE TITLE
Unnecessary data property which breaks the merge.

### ISSUE THREAD

**Issue by sushilkumaraitian** [cypress-io/cypress#19281]
### Current behavior

```
{"C:\\Code\\app\\src\\App.js": {"data":{"path":"C:\\Code\\app\\src\\App.js","statementMap": {}},
,"C:\\Code\\app\\src\\index.js": {"data":{"path":"C:\\Code\\app\\src\\index.js","statementMap"{},
,"C:\\Code\\app\\src\\components\\logo\\Logo.tsx": {"path":"C:\\Code\\app\\src\\components\\logo\\Logo.tsx","statementMap":{}},
```
For some of the files, coverage-final.json has nested the object inside data property. Due to this when I run the merge command, it gives me following error:

Invalid file coverage object, missing keys, found:datathe 

### Desired behavior

It happens when I run end to end test and generate a report.

### Test code to reproduce

cy:open

### Cypress Version

9.1.1

### Other

_No response_[](url)

![image](https://user-images.githubusercontent.com/5736999/144915274-40b12a5e-400e-482b-a0e2-0b670c105add.png)

**Comment by Narretz** [comment]
Should probably be reported here https://github.com/cypress-io/code-coverage

**Comment by sainthkh** [comment]
Closing because of the inactivity.
