### ISSUE TITLE
Access cypress config from within the CLI

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19284]
# What would you like?

Various CLI commands will have to access the cypress config. We need to figure out what the implications are of evaluating the config multiple times as generally (AFAIK) the config is 

* Install: to determine what to install for `cypress install` and `cypress install <browser>`
* Info: to determine what versions we currently have installed.

We may be able to defer run and open to the service and not have to check them in the CLI. 

# Why is it needed?

Some CLI commands need access to the browser config.

**Comment by jennifer-shehane** [comment]
Closing as this is no longer planned work.
