### ISSUE TITLE
 Unable to resize an element by clicking on the bottom right corner arrow and dragging it down few pixels

### ISSUE THREAD

**Issue by mekalag** [cypress-io/cypress#19296]
### Current behavior

Hello Team,

I have seen lot of examples for drag and drop of an element. ie to move from source to target. But in my case, I want to resize an element by clicking on the bottom right corner arrow and dragging it down a few pixels. I tried lot of options ex:
```
cy.get('.applications > .cdk-drag')
  .trigger("mousedown", {which: 1})
  .trigger("mousemove", 100,50, {force: true})
  .trigger('mouseup', { force: true })
```
Basically it does nothing. Though in screenshots I see the element is clicked but not dragged.
I have tried few other options and even installed _@4tw/cypress-drag-drop_ module, but unable to just drag an element to few pixel down.

here is the html and the element I am trying to drag. 

<img width="1025" alt="Screenshot 2021-12-07 at 15" src="https://user-images.githubusercontent.com/11612209/145073408-2071cd36-8688-4ca5-9b43-bcb7d55ad0b6.png">

I don't know why it's so tough to drag an element, nothing seem to work after trying lot of options suggested around.
Can someone please help here?

### Test code to reproduce

Options I tried to drag an element:         

```
cy.get('.applications > .cdk-drag')
          .trigger("mousedown", {which: 1})
          .trigger("mousemove", 100,50, {force: true})
          .trigger('mouseup', { force: true })
```

I tried suggestion mentioned here  https://stackoverflow.com/questions/70198631/cypress-resizing-dragging-elements/70202151  which is not working.

Also functions from _@4tw/cypress-drag-drop_ module not working in my case.

### Cypress Version

9.1.0

**Comment by Hareramrai** [comment]
I have also faced some problems with resizing a standard textarea and a div with the style resize.
