### ISSUE TITLE
Support ultrawide aspect ratio 21:9 in cypress dashboard

### ISSUE THREAD

**Issue by alex-savvyy** [cypress-io/cypress#19294]
### What would you like?

Support ultrawide aspect ratio 21:9 in cypress dashboard so that test run videos scale properly. As of right now, the video playback's font size increases in 21:9 aspect ratio making the video hardly visible using an ultrawide monitor.

### Why is this needed?

quality of life change for ultrawide users

### Screenshots

Note that while the these images are taken from browser windows "with the same height" and the ultrawide picture only has a wider width. Cypress dashboard is "zooming in" when the browser width is increased

![cypress-normal-video](https://user-images.githubusercontent.com/87037291/145244897-2114cd26-4977-4ea4-a1d2-01c6cb0b5561.jpg)
![cypress-wide-video](https://user-images.githubusercontent.com/87037291/145244898-f7294db5-a5cd-43b2-831e-be554fe5f21e.jpg)

**Comment by jennifer-shehane** [comment]
Can you provide a screenshot of what you mean (blocking out any sensitive data)?

**Comment by alex-savvyy** [comment]
@jennifer-shehane 

Thanks for your prompt response. I have attached some screenshots and more details (apologies for the aggressive redaction). 

I also posted a similar issue with the dashboard (not related to ultrawide monitors) in https://github.com/cypress-io/cypress/issues/18368/

The other issue is a higher priority for me. Would you be able to take a look at that one as well?
