### ISSUE TITLE
[9.1.x Regression] Element actionability often fails because it is "is being covered by another element"

### ISSUE THREAD

**Issue by glomotion** [cypress-io/cypress#19302]
### Current behavior

When using `@cypress/react` and any cypress version after `9.0.0` - I have noticed that tests which have previously passed for thousands (maybe millions) of test runs are now sometimes failing in CI due to the same kind of error:

```
 CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element:

`<button data-testid="fakeSearchBar__searchBox__clearButton" class="css-buxwsf-IconStyles-className-className-className-Icon-Button-ClearIcon">action_x</button>`

is being covered by another element:

`<button data-testid="fakeSearchBar__searchBox__searchButton" class="css-1j8wy6i-IconStyles-className-className-className-Icon-Button">action_...</button>`

Fix this problem, or use {force: true} to disable error checking.
```

In the particular case above the 2 elements in question are next to each other in the UI - but should never overlap. 

### Desired behavior

Tests on code which hasn't changed at all, should continue passing 100%

### Test code to reproduce

-

### Cypress Version

9.1.x

### Other

Incase someone from Cypress wants to take a look, you can dig into our the test run logs here: https://dashboard.cypress.io/projects/vyof1e/runs/416/test-results

This regression is preventing us from upgrading beyond cypress 9.0.0. I have tested with all versions released after 9.0.0 (including 9.1.1) - and this regression is present in all versions.

**Comment by glomotion** [comment]
possibly related: https://github.com/cypress-io/cypress/issues/15618

**Comment by glomotion** [comment]
FWIW - i can never seem to get these tests to fail when running them locally

**Comment by TheDutchCoder** [comment]
I can confirm the same problem (locally) with a Component Test.
Cypress thinks an element is in front of the background (it is, but only in the center) and clicking anywhere on the background throws the error:
![image](https://user-images.githubusercontent.com/1668207/146033816-c4a24626-13f5-4dfb-936e-f0cfe3a61c8e.png)
