### ISSUE TITLE
cy.wait using array with one alias returns a single interception, not an array of iterceptions

### ISSUE THREAD

**Issue by veloware** [cypress-io/cypress#19317]
### Current behavior

According to the docs, https://docs.cypress.io/api/commands/wait#Aliases

and also the type definition for `wait()` - 

```
wait(alias: string[], options?: Partial<WaitOptions>): Chainable<Interception[]>
```

a `wait` that accepts an array of aliases, should return an array of `Interception`

This doesnt seem to be the case when the array has one interception.  The `then` callback receives a response with a single interception, so either this is incorrect, or the type definition is incorrect

e.g. having `cy.wait([@myIterception]).then((res) => ...)` currently yields `res` as a single interception object

### Desired behavior

`cy.wait([@myIterception]).then((res) => ...)` should yield `res` as a an array of `Interception` objects, granted it would be an array of one `Interception`

### Test code to reproduce

.

### Cypress Version

8.4.1

**Comment by flotwig** [comment]
This is indeed a bug, the issue seems to be here: https://github.com/cypress-io/cypress/blob/e2f0a66a1f4cb5168c37805617627de04ad39e7f/packages/driver/src/cy/commands/waiting.ts#L254-L256

A PR with a fix and a test would be welcome.
