### ISSUE TITLE
Tests ran and passed but cypress didn't exit step in Github Actions, intermittently. 

### ISSUE THREAD

**Issue by uccmen** [cypress-io/cypress#19315]
### Current behavior

After upgrading cypress to v9.1.0 from v8.3.1, we noticed that one of our workflow steps which involves cypress didn't complete and just kept running, greedily eating away our Action minutes.

Unfortunately for us, we only just recently learned about setting [timeout-minutes](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes) in our workflows to prevent certain steps like our e2e step with cypress from going rogue.

The weird thing is, this only happens intermittently but a lot more recently after the upgrade.

I've attached the logs from our Github Action workflow (with cypress running in DEBUG mode) which describes the above scenario.

**_When tests passed but step didn't complete_**
<img width="1090" alt="Screenshot 2021-12-09 at 2 35 29 PM" src="https://user-images.githubusercontent.com/1238697/145351087-ed9c8fc6-b07e-4bc4-b8c6-55e1d6c6adb3.png">

**_When tests passed and step completed_**
<img width="1096" alt="Screenshot 2021-12-09 at 2 37 52 PM" src="https://user-images.githubusercontent.com/1238697/145351250-d6bb5495-616e-47c8-8fa6-69e3f5fc6dda.png">

[logs_2604.zip](https://github.com/cypress-io/cypress/files/7682765/logs_2604.zip)

### Desired behavior

In this situation, once Cypress has successfully ran and completed all tests, it should exit the step - consistently.

### Test code to reproduce

Our workflow simply calls one of our npm script which basically runs `yarn cypress run`

### Cypress Version

v9.1.0

**Comment by JeremyKirkham** [comment]
I'm seeing this also, some times it exits, more often than not it doesn't.

**Comment by grace-purcell** [comment]
I'm also facing this issue when running the tests with a webkit browser

**Comment by MikeMcC399** [comment]
@grace-purcell 
> I'm also facing this issue when running the tests with a webkit browser

There is no mention in the original issue of a webkit browser, which according to https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental is an experimental feature.

If you are asking for the Cypress team to investigate, then it would make sense for you to open a new issue and for you to provide the information which new issues require.

**Comment by grace-purcell** [comment]
> @grace-purcell
> 
> > I'm also facing this issue when running the tests with a webkit browser
> 
> There is no mention in the original issue of a webkit browser, which according to https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental is an experimental feature.
> 
> If you are asking for the Cypress team to investigate, then it would make sense for you to open a new issue and for you to provide the information which new issues require.

It's the same error and same instance though. tests run headless, in the workflow with github actions. With the browser property set to "browser: chrome" it runs fine sometimes and others has the same result, but with browser set to webkit it has the same result consistently of all specs passed and nothing else produced until it eventually produces "Error: the action has timed out"
