### ISSUE TITLE
Error to the second cy.visit after automatic authentification redirection 

### ISSUE THREAD

**Issue by keaoner** [cypress-io/cypress#19318]
### Current behavior

In my cypress 9.1.1 test with chrome 96 the first step is OKTA authentication with this url ` cy.visit` : https://login.innovation-lefebvre-sarrut.eu then I am I am automatically redirected to the site https://innovation-lefebvre-sarrut.eu then the second test which is opened  in this url `cy.visit `on a different domain: https://okdoc.okdoc-dev.app.eks-dev.sandbox.els-lab.eu/
The problem is that the second url called is in error in cypress runner but I have no error message in the console what I see is that the second cy.visit is in red and therefore is not not executed.

Could you help me please?

### Desired behavior

I would just like the second `cy.visit` to work, as it worked when we didn't have the OKTA redirect on this url :  https://innovation-lefebvre-sarrut.eu .
We cannot remove this redirect because it is production

### Test code to reproduce

````javascript

Cypress.Commands.add('oktaLogindev', () => {
    cy.visit("https://login.innovation-lefebvre-sarrut.eu");
    cy.wait(2000);
    cy.get("#okta-signin-username").type(Cypress.env('username'));
    cy.get("#okta-signin-password").type(Cypress.env('password'));
    cy.get("#okta-signin-submit").click();
    cy.wait(3000);
    // as each test in cypress will create a seperate session of browser
    // we need to preserve the cookies after logging in to okta
    // these cookies will be used in next test by cypress
    Cypress.Cookies.defaults({
      preserve: /.*/,
    });
   cy.visit("https://okdoc.okdoc-dev.app.eks-dev.sandbox.els-lab.eu/");
})
```

### Cypress Version

9.1.1

### Other

Chrome 96
Firefox 89
Edge 96
Electron

**Comment by AtofStryker** [comment]
HI @keaoner. This should be fixed with `experimentalSessionAndOrigin` and will be generally available in cypress 12. Please take a look at https://github.com/chrislacey89/cypressOktaBug/pull/1 and #23733. I am going to close this issue, but please let us know if this doesn't fix your issue.
