### ISSUE TITLE
Automatic test creation via GUI

### ISSUE THREAD

**Issue by noalbalint** [cypress-io/cypress#19329]
### What would you like?

In Cypress, you can watch your test files be run through your app, but you can't run through your app and generate a test file.

It would be ideal if Cypress could just record me clicking through my app and then auto-generate a test file based on the click events and DOM snapshots, and then presto that's my test!

I recognize this would be a big leap to make from the current implementation, but it would be such an incredible boon for development. Imagine never having to manually write a test file ever again!

I'm imagining something similar to the Heap Event Visualizer (if anyone is familiar with that) in the sense that you can just click an element on your app and define an event for it directly, rather than being required to go into the code, find the exact element, and give it an ID (though you can also do that if you want)

### Why is this needed?

writing tests is a pain. clicking through an app is painless.

**Comment by tmieulet** [comment]
Have you looked https://docs.cypress.io/guides/core-concepts/cypress-studio#Overview ?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
