### ISSUE TITLE
cy.document().invoke("write", "<h1>test</h1>") throws unreadable error

### ISSUE THREAD

**Issue by johannespein** [cypress-io/cypress#19328]
### Current behavior

I'm using https://github.com/bahmutov/cypress-ethereal-email-example/blob/main/cypress/integration/check-email.js#L45 but have the following issue:

```
cy.document().invoke("write", "<h1>test</h1>")
``` 
results in
```
Cannot set property message of [object DOMException] which has only a getter
```

`"chromeWebSecurity": false` is set.

### Desired behavior

I would like to have a proper error message, why my code is failing.

### Test code to reproduce

Unfortunately, I don't have a sample project to reproduce this issue right now.

### Cypress Version

9.1.1

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Can you provide a reproducible code example? I tried to reproduce it with the code below, but failed. 

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
</body>
</html>
```

```js
it('t', () => {
  cy.visit('fixtures/a.html')
  cy.document().invoke('write', '<div>foo</div>')
})
```

**Comment by johannespein** [comment]
I could not reproduce a sample, but I found out that it has something to do with the html code I was trying to `invoke` on. Thanks to your comment I developed a workaround for this error by doing the following:

```javascript
cy.visit("<html></html>")
cy.document().invoke("write", "<h1>test</h1>")
```
