### ISSUE TITLE
Cypress Crash: Uncaught TypeError: Cannot read properties of undefined (reading 'emit')

### ISSUE THREAD

**Issue by DobQA** [cypress-io/cypress#19337]
### Current behavior

Upon finishing running my Cypress script, Cypress would crash (On Chrome Latest)

In dev tools we can see the following error:
```
cypress_runner.js:191727 Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at Socket.<anonymous> (cypress_runner.js:191727)
    at Socket.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:18455)
    at Socket.emit (cypress_runner.js:199652)
    at Socket.emitEvent (cypress_runner.js:199401)
    at Socket.onevent (cypress_runner.js:199388)
    at Socket.onpacket (cypress_runner.js:199352)
    at Manager.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:18455)
    at Manager.emitReserved (cypress_runner.js:199665)
    at Manager.ondecoded (cypress_runner.js:198944)
    at Decoder.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:18455)
    at Decoder.add (cypress_runner.js:199978)
    at Manager.ondata (cypress_runner.js:198936)
    at Socket.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:18455)
    at Socket.onPacket (cypress_runner.js:196867)
    at WS.<anonymous> (cypress_runner.js:196676)
    at WS.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:18455)

Clicking on the .js line:
 lodash__WEBPACK_IMPORTED_MODULE_0___default.a.each(socketToDriverEvents, event => {
      ws.on(event, (...args) => {
        Cypress.emit(event, ...args);
      });
    });
```

### Test code to reproduce

Issue seems to happen on screen redirection, not sure if its due to when a session becomes invalid.
If anyone can explain what the above is related to I can investigate more before providing sample code.

### Cypress Version

9.1.1

**Comment by ilovegithub2** [comment]
Does anyone know if this is going to be prioritised soon?  It is really blocking us with some critical testing.

**Comment by ilovegithub2** [comment]
@bahmutov - please send help!! 👍

**Comment by bahmutov** [comment]
Can you provide the cypress team with a reproducible example of the crash?

**Comment by ilovegithub2** [comment]
I have reached out to Cypress support as our use case is behind auth.

**Comment by ThiloHettmer** [comment]
I got the same issue with vue 3. Tried it with the hello-world example project and followed your tutorial: https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/

package.json:
`
...
  "dependencies": {
    "core-js": "^3.20.2",
    "vue": "^3.2.26",
    "webpack": "^5.65.0"
  },
  "devDependencies": {
    "@cypress/vue": "^3.1.0",
    "@cypress/webpack-dev-server": "^1.8.0",
    "@vue/cli-plugin-babel": "^5.0.0-rc.1",
    "@vue/cli-plugin-eslint": "^5.0.0-rc.1",
    "@vue/cli-service": "^5.0.0-rc.1",
    "@vue/compiler-sfc": "^3.2.26",
    "autoprefixer": "^10.4.1",
    "babel-eslint": "^11.0.0-beta.2",
    "cypress": "^9.2.1",
    "eslint": "^8.6.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-vue": "^8.2.0"
  },
"eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended",
      "plugin:cypress/recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
...
`

cypress/plugins/index.js:
`
const { startDevServer } = require('@cypress/webpack-dev-server')
const webpackConfig = require('@vue/cli-service/webpack.config')

module.exports = (on, config) => {
  on('dev-server:start', (options) => {

    return startDevServer({
      options,
      webpackConfig,
    })
  })

  return config
}
`

cypress.json:
`
{
  "component": {
    "componentFolder": "src",
    "testFiles": "**/*.spec.js"
  }
}
`

1) run npx cypress open-ct
2) selectHelloWorld.spec.js

=> UI stuck on "Your tests are loading..."

Console output:
`
cypress_runner.js:209081 Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at Socket.<anonymous> (cypress_runner.js:209081:17)
    at Socket.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:31735:20)
    at Socket.emit (cypress_runner.js:217050:15)
    at Socket.emitEvent (cypress_runner.js:216799:20)
    at Socket.onevent (cypress_runner.js:216786:18)
    at Socket.onpacket (cypress_runner.js:216750:22)
    at Manager.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:31735:20)
    at Manager.emitReserved (cypress_runner.js:217063:15)
    at Manager.ondecoded (cypress_runner.js:216342:14)
    at Decoder.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:31735:20)
    at Decoder.add (cypress_runner.js:217376:23)
    at Manager.ondata (cypress_runner.js:216334:22)
    at Socket.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:31735:20)
    at Socket.onPacket (cypress_runner.js:214265:16)
    at WS.<anonymous> (cypress_runner.js:214074:14)
    at WS.../../node_modules/component-emitter/index.js.Emitter.emit (cypress_runner.js:31735:20)
`

I'm pretty new to cypress, so perhaps I am missing something?

**Comment by philippjenni** [comment]
I had the same issue, but only when i open cypress for component testing with command `npx cypress open-ct --project projects/[myAngularComponentProject]`

I have tested also with older cypress version and the error exists since 8.7.0. Also tested with older nodejs versions [12.x, 16.x] and this makes no difference.

**Comment by luxalpa** [comment]
yes same error here with Vue 3. Also in Firefox the error message is slightly different, reading `Uncaught TypeError: Cypress is undefined` (tested with Edge and Firefox).

It seems that I can still use it although I am not sure if I can use all functions (I tried to add some handlers into support/index.js but they don't seem to work; but the error message still exists without those modifications).

**Comment by priyankatakale** [comment]
I am facing the same issue, is there any resolution for it?

**Comment by garubin** [comment]
Same here, someone resolved the issue?

**Comment by adam-thomas-privitar** [comment]
This isnt really a cypress bug. For me what it was is my test code was importing an index file and somewhere along the way that index file had side effects which impacted the DOM. In my case, I was accidentally importing a file that called React DOM render on a `root` dom node. This nukes cypress component testing, which needs to mount into the DOM itself.

**Comment by sarahsamaya** [comment]
I am having the same issue. Test execution just stops with message _"whoops, there is not test to run"_. 

Checking the console source, the error occurs in the cypress_runner.js. Also, it does not happen all the time. It is hard to describe the issue, since it is so aleatory, but I am trying to delete a data from a grid, then it opens a modal to click on a [DELETE] button to confirm it.

    lodash__WEBPACK_IMPORTED_MODULE_0___default.a.each(socketToDriverEvents, event => {
      ws.on(event, (...args) => {
        Cypress.emit(event, ...args); => error here
      });
    });

**Comment by hereiscasio** [comment]
I can confirm this issue existed.
On my side, this is all about _**Cypress**_ Component Testing.

And I think I found some clues of the bug.
This bug will only happen if you install any _**Cypress**_ version large than v.8.1.0
(i.e. v.8.1.0 is safe)

The issue is reproducible, and it's easy to do:

1. Clone: https://github.com/cypress-io/cypress-component-testing-examples/tree/main/create-nuxt-app
2. update _**Cypress**_ package to 8.2.0
3. run `npx cypress open-ct`
4. you can see the browser console show the error(see attachment)
5. but if you update _**Cypress**_ to 8.1.0, no error anymore!!!

![image](https://user-images.githubusercontent.com/44331046/160258118-ff16086b-939c-4724-a68c-48edc5f449e7.png)

cc @bahmutov

Thx for reading.
And hope this bug can be fixed.

**Comment by patrickcate** [comment]
Getting this same error with Vue 3 and component testing. I haven't started on E2E tests so I'm not sure they are affected as well.

vue@3.2.31
vite@2.8.6
cypress@9.5.2
@cypress/vue@3.1.1
@cypress/vite-dev-server@2.2.2

**Comment by zeeshankhan0330** [comment]
Has anyone managed to find a workaround?

**Comment by mohamedjkr** [comment]
I am having the same issue as well, but looks like it only occurs in the component test runner.

**Comment by badeball** [comment]
Followed [this](https://www.cypress.io/blog/2021/04/06/cypress-component-testing-react/) blog posts and got the same error. An example illustrating the error can be found [here](https://github.com/badeball/cypress-reproducible-issues/tree/master/component-testing-react).

**Comment by cailloumajor** [comment]
I also encountered this issue in my project ([Quasar](https://quasar.dev/) / Vue 3 / Vite) using Cypress to do component tests.
The issue appeared when I added a test for `process.env.NODE_ENV` in the code of a stored used by the component under test.
The stranger thing is that I had the issue even when the code was commented out, and only running Cypress (no error at all in the browser when running the dev server).
Replacing `process.env.NODE_ENV` with `import.meta.env.DEV` ([Vite specific](https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes)) solved the problem.

**Comment by mayank99** [comment]
I'm getting the same error with `cypress open-ct`. Initially I was getting "Cannot find module" on a line that was requiring `webpack-dev-server`, so I installed it and then I started seeing "Cannot read properties of undefined (reading 'emit')".


```
"@cypress/react": "^5.12.4",
"@cypress/webpack-dev-server": "^1.8.4",
"@storybook/react": "^6.4.22",
"@storybook/testing-library": "^0.0.11",
"cypress": "^9.6.0",
"react": "^17.0.0",
"react-dom": "^17.0.0",
"react-scripts": "5.0.1",
"webpack": "^5.72.0",
"webpack-dev-server": "^4.8.1"
```

**Comment by DobQA** [comment]
Issues still exists in Cypress 9.6, Im hoping fix comes in Cypress 10, how can we get a Cypress dev on this?

**Comment by IvaanTorres** [comment]
I had the same issue using cypress 9.5.3 (Chrome 101) with Node 16.14.0.
What I did was to use a setTimeout() for the first action of the test. For example:
setTimeout(() => {
  cy.url()
    .should('eq', 'http://localhost/auth/login')
}, 3000)
This fixed the problem. I know it is not a great solution but there it is :)
Hope that it helps you

**Comment by am1fat32** [comment]
Having the same issue:
- @cypress/react@5.12.4
- cypress@9.6.0

**Comment by bel0v** [comment]
I've got the same with Vite dev server. 

* @cypress/react": "5.12.4"
*  cypress": "9.5.2"
* @cypress/vite-dev-server": "2.2.3"

<details>
  <summary>Contents of cypress/plugins/index.ts</summary>
  
  ```javascript
/// <reference types="cypress" />

import { startDevServer } from '@cypress/vite-dev-server'

const pluginsConfig: Cypress.PluginConfig = (on, config) => {
  on('dev-server:start', (options) => startDevServer({ options }))

  return config
}

module.exports = pluginsConfig

  ```
  
</details>

I tried with the simplest test file that doesn't include any imports:
```javascript
import { mount } from '@cypress/react'

it('runs test', () => {
  mount(<div />)
})

```
and the error occurs on the All tests page, before I even select a spec to run:
<img width="600" alt="Screenshot 2022-05-16 at 14 19 30" src="https://user-images.githubusercontent.com/2889382/168582519-4c1d81d9-0c38-4a0d-b83c-d1880c521380.png">

Looks like as if Cypress is not being initialized properly somewhere down the road.

**Comment by CarolineSenes** [comment]
**The probleme :** 
I have the same with React/Vite/Cypress.

![template_cypress_KO](https://user-images.githubusercontent.com/78350952/170714239-60eea4ee-37c0-4590-a655-59c0132aae4d.PNG)

Notice that if the dev server is not start before cypress, a new error is generated instead of the loading spinner ("Your tests are loading..." : 
```
The following error originated from your test code, not from Cypress.

  > Failed to fetch dynamically imported module: http://localhost:3000/__cypress/src/src/shared/components/TestComponent/TestComponent.test.tsx
```

**Some of my code :** 
plugins/index.ts : 
```
import { startDevServer } from '@cypress/vite-dev-server';
import path from 'path';

export default (on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions): Cypress.PluginConfigOptions => {
  on('dev-server:start', (options) => {
    return startDevServer({
      options,
      viteConfig: {
        configFile: path.resolve(__dirname, '..', '..', 'vite.config.ts'),
      },
    });
  });
  return config;
};
```

**What i tried :** 
- With cypress 8.1.0 the only difference is that there is no error in the cypress console.
- Same issue with cypress 9.6.1
- [Reproduce un minimal repo](https://github.com/CarolineSenes/Vitejs_Cypress) : error in the cypress console is steal here, but test works fine.


**Version :** 
Cypress : 9.7.0
@cypress/react : 5.12.5
@cypress/vite-dev-server : 2.2.3
Vite : 2.9.9
React : 16.13.1
Node : 14.0.0

**Comment by DobQA** [comment]
Just upgraded to Cypress 10.0 hoping the issue maybe resolved, sadly not 👎  Not its worse as Cypress just closes the test and nothing happens. Any ideas how we can get Cypress devs to have a look at this?

**Comment by chris-aeviator** [comment]
for me this appears when my cypress compilation (due to a wrong import in a file that I'm not currently opening) contains an error. It disappears if I fix the error (cypress 9.6)

**Comment by wpplumber** [comment]
@cailloumajor did you meet the following error with Quasar Vite project?

![image](https://user-images.githubusercontent.com/52907282/176147606-163484ad-633a-4c12-87b0-da620327d2cb.png)

**Comment by cailloumajor** [comment]
> @cailloumajor did you meet the following error with Quasar Vite project?
> 
> ![image](https://user-images.githubusercontent.com/52907282/176147606-163484ad-633a-4c12-87b0-da620327d2cb.png)

No

**Comment by wpplumber** [comment]
Did you manage the **cypress.config.ts** `viteConfig` section below?
```
import { defineConfig } from 'cypress'

export default defineConfig({
  fixturesFolder: 'test/cypress/fixtures',
  screenshotsFolder: 'test/cypress/screenshots',
  videosFolder: 'test/cypress/videos',
  video: true,
  viewportWidth: 1000,
  viewportHeight: 960,
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require('./test/cypress/plugins/index.js')(on, config)
    },
    baseUrl: 'http://localhost:8081/app/',
    specPattern: 'test/cypress/integration/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: 'test/cypress/support/index.js',
  },
  component: {
    setupNodeEvents(on, config) {},
    supportFile: 'test/cypress/support/component.js',
    specPattern: 'src/**/*.spec.js',
    devServer: {
      framework: 'vue',
      bundler: 'vite',
      // viteConfig: 'quasar.config.js',
    },
  },
})
```

**Comment by Hugo01** [comment]
Facing the exact same issue with Quasar/Vite/Vue3
What is weird is that it was working fine a few weeks ago

**Comment by wpplumber** [comment]
Did you try this?

```
import { defineConfig } from 'cypress'
const vue = require('@vitejs/plugin-vue');

export default defineConfig({
  fixturesFolder: 'test/cypress/fixtures',
  screenshotsFolder: 'test/cypress/screenshots',
  videosFolder: 'test/cypress/videos',
  video: true,
  viewportWidth: 1000,
  viewportHeight: 960,
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require('./test/cypress/plugins/index.js')(on, config)
    },
    baseUrl: 'http://localhost:8081/app/',
    specPattern: 'test/cypress/integration/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: 'test/cypress/support/index.js',
  },
  component: {
    setupNodeEvents(on, config) {},
    supportFile: 'test/cypress/support/component.js',
    specPattern: 'src/**/*.spec.js',
    devServer: {
      framework: 'vue',
      bundler: 'vite',
      viteConfig: {
        plugins: [vue()],
    },
    },
  },
})

```

**Comment by DobQA** [comment]
Issue still exists in Cypress 10.4.0 - not sure if there is more then one problem being discussed here but its still a showstopper for myself. This only issue with Cypress I see when Cypress crash and no proper way to debug. Surely this bug should have more priority then backlogged.

**Comment by DobQA** [comment]
Issue still existis in Cypress 12.3.0, I think its todo with perhaps switching from iframe to non iframe solution. Waiting for iFrame support from Cypress for very long time.

**Comment by leochen0818** [comment]
> Issue still existis in Cypress 12.3.0, I think its todo with perhaps switching from iframe to non iframe solution. Waiting for iFrame support from Cypress for very long time.

I have the same problem. I guess the last available version is 8.7.0.

**Comment by DobQA** [comment]
I will close issue for now and carry on discussion on the official iFrame support thread: https://github.com/cypress-io/cypress/issues/136

I'm now convinced that the issues is related to iFrame switching. I just hope cypress team look into this as if we do not get a solution soon my team will be forced to switch to alternatives.

**Comment by georgyevv** [comment]
I'm having this issue *Cannot read properties of undefined (reading 'MyDetailsFacadeService')* and stack trace doesn't make sense. This is in component testing cypress v12.17.2. I can't analyze this tried so many things. Would anyone happen to have an idea of how to figure it out? I don't have an iframe at all.

![image](https://github.com/cypress-io/cypress/assets/13435068/f6c0ad3e-0951-4c15-9af3-4e5b3f3f79bd)

**Comment by nagash77** [comment]
@georgyevv please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
