### ISSUE TITLE
Intercept not stubbing data

### ISSUE THREAD

**Issue by ymoon715** [cypress-io/cypress#19339]
### Current behavior

https://user-images.githubusercontent.com/39988020/145751534-cc4a144a-c6e0-4aa8-b0fd-d8f0caee18a0.mov

### Desired behavior

Stubbing data consistently as array of empty buildings

### Test code to reproduce

![Screen Shot 2021-12-12 at 8 17 35 PM](https://user-images.githubusercontent.com/39988020/145751691-ac5dd32f-dcb5-4cc1-b099-92fc468d3de3.png)

### Cypress Version

9.0

**Comment by sainthkh** [comment]
Closing because of the inactivity.
