### ISSUE TITLE
Issue with MP4 fixtures when intercepting with Cypress 9.1.1

### ISSUE THREAD

**Issue by ldabiralai** [cypress-io/cypress#19330]
### Current behavior

Cypress 9 does not intercept with mp4 fixtures correctly. The MP4 does not load when loaded via either the `<video>` tag or directly in the browser.

### Desired behavior

The MP4 should be mocked correctly by cypress and the video should autoplay. The test should pass.

### Test code to reproduce

This repo demonstrates the issue, it's setup with cypress 9.1.1 by default in which the test will fail.

https://github.com/ldabiralai/cypress-mp4-bug

### Cypress Version

9.1.1

**Comment by emilyrohrbough** [comment]
Hi @ldabiralai. Thank you for creating this issue and providing a reproducible example of the behavior you are seeing. Using your example project, I was able to re-create the issue.

It appears this was introduced in Cypress 9.0.0. by [#18534](https://github.com/cypress-io/cypress/pull/18534) which made changes such that 
- when null is passed as the encoding to cy.readFile() or cy.fixture(), the file is treated as binary and read as a Buffer.
- When null passed as the encoding to cy.writeFile() allows direct writing of buffers.
- If the encoding is unspecified, the default remains ‘utf8’, matching the current behavior.

Before this changes, when a fixture path was specified in `cy.intercept()` without an encoding value, the encoding would assume to be null and the file extension would be used to determine the encoding type and eventually fallback be read a a Buffer. When adding `null` as an explicit option, the default encoding changed from `null`  to `undefined` when a fixture path without an encoding value is passed, which caused the file to be read with the default encoding of `utf8`.

Given the change in behavior, you should be able to read the MP4 with a Buffer with:
```md
describe("mp4", () => {
  it("should be able to mock an mp4", () => {
-    cy.intercept("video.mp4", { fixture: "video.mp4"});
+   cy.intercept("video.mp4", { fixture: "video.mp4,null"});
```
However, while verifying it does appear we missed supporting `null` encoding for `cy.intercept()`. A small change is needed to fix this.

**Comment by ldabiralai** [comment]
Awesome, thanks for explaining the issue and the workaround to me so quickly @emilyrohrbough!
