### ISSUE TITLE
Tests do not happen, namely keystrokes, when testing window is not in focus

### ISSUE THREAD

**Issue by mscale-wmp** [cypress-io/cypress#19333]
### Current behavior

I am running cypress 5.6.0 with Angular for my employer. We use Material and ngx components in our UI. I have noticed that when I am running frontend tests, the tests don't complete correctly if the cypress chrome window is not in focus on my screen, aka not visible.

The two main tests that are problematic are type.('{enter}') and cy.get('.mat-snackbar').should('not.exist')

The type test says it happens in the cypress logs, but the UI shows that enter was never hit since the material/ngx-mat-select-search are still visible. This causes the rest of the tests to fail since the UI cannot move on.

The snackbar should failures can happen too, these tests make sure that the snackbar disappears before moving on. The angular material snackbar has a timeout that causes it to remove itself from the UI after three seconds. However, cypress shows the snackbar frozen on the screen.

Again, these tests only fail if I am running the tests in the cypress chrome browser and am focused on another window. I cannot share my repo since it is classified code, but will create a similar example.

![screenshot_cypress_type_fail](https://user-images.githubusercontent.com/73251945/145638483-bbe9119c-6a8e-4896-b8e3-a339aeea2a0c.png)
In the screenshot, you can see the command type({enter}) but the dropdown is still visible.

### Desired behavior

Interact with the UI correctly instead of getting confused when the window is not focused/visible on my computer.

### Test code to reproduce

.type(`${select_name}{enter}`)

### Cypress Version

5.6.0 

### Other

I cannot share my repo or major parts of my code. Company policy.

**Comment by sainthkh** [comment]
Sorry for the late reply.

Is it still happening with the latest version?

In most cases, the tests work correctly without getting any focus. Can you provide a reproducible code example? As we all know, the debugging starts with reproducing the problem on the developer's environment.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
