### ISSUE TITLE
Cypress and Travis CI build fail sometimes... "No output has been received in the last 10m0s"

### ISSUE THREAD

**Issue by glabrat** [cypress-io/cypress#1934]
### Current behavior:

https://travis-ci.org/gpincheiraa/bln-frontend-project1/builds/391102661

![Error](https://user-images.githubusercontent.com/19995834/41309909-f64c77e0-6e4d-11e8-9604-31f408cbb42d.png)

### Desired behavior:

https://travis-ci.org/gpincheiraa/bln-frontend-project1/builds/391093551

![Desired behavior](https://user-images.githubusercontent.com/19995834/41309962-1d10efc8-6e4e-11e8-8b58-f1ead4441902.png)

### Steps to reproduce:

https://github.com/gpincheiraa/bln-frontend-project1
https://travis-ci.org/gpincheiraa/bln-frontend-project1/builds

It's hard to tell what's happening here and how reproduce the error, sometimes it happens, sometimes doesn't happen. The project has two scripts in folder "ci", deploy and functional-test, which is odd why deploy works and functional-test works sometimes, this is the code of functional-test:

```
echo '{ "address": "1FwJk" }' > btc-config.json
npm start & (wait-on http://localhost:3000 && cypress run)

kill $(jobs -p) || true
```
Folder  #"ci": 
https://github.com/gpincheiraa/bln-frontend-project1/tree/master/ci

### Versions

Travis CI 
Cypress 3.0.1
Browser Electron 59

**Comment by glabrat** [comment]
@brian-mann Hi, this is the output with the enviroment variable, please check out!

https://travis-ci.org/gpincheiraa/bln-frontend-project1/jobs/393222511#L349

**Comment by brian-mann** [comment]
It appears it is dying on video compression, which is unusual - not sure if we've seen that before. Plenty of tests run in Travis CI without this problem.

It appears this is sometimes happening on your builds and sometimes not.

For the moment I would just turn off video compression by passing `videoCompression: false`.

As to why this is happening, the logs are unclear - we likely need to add more DEBUG logs to ffmpeg to understand why.

Also - your Travis CI script is caching `node_modules` but you're using `npm ci`, which will automatically blow away your `node_modules`, thus rendering your cache useless.

Here is an example `.travis.yml` file that shows you how to properly cache both `node_modules` and also the Cypress binary: 

https://docs.cypress.io/guides/guides/continuous-integration.html#We-recommend-users

**Comment by brian-mann** [comment]
Also likely related to: https://github.com/cypress-io/cypress/issues/1333

**Comment by paulfalgout** [comment]
FWIW I'm seeing the same issue on travis but am not using the video at all: https://github.com/cypress-io/cypress/issues/1905

**Comment by glabrat** [comment]
@brian-mann Hello, sir. I have to announce that the build keep failing.

Tried the videoCompression: false, I don't know if this can help.
https://travis-ci.org/gpincheiraa/bln-frontend-project1/jobs/395550617

**Comment by brian-mann** [comment]
Can you update to 3.0.2 and see if this issue is resolved?

We updated ffmpeg to 4.x.x there and added many more debugging logs.

Also please be sure that you use DEBUG=cypress:* cypress run when running so that we can get the debug logs to understand what is happening.

**Comment by glabrat** [comment]
Hi, this is my log:

https://travis-ci.org/gpincheiraa/bln-frontend-project1/builds/399205721

You can check there's still an issue, I don't know why.

**Comment by brian-mann** [comment]
Okay it appears as if ending the video recording is not working. The logs are pretty clear that that is the last spot.

I checked the logs and there's no indication of an error with the video recording, so I'm not sure why it can't be ended.

Regardless though, we can add a timeout here of a few seconds, and if that triggers just continue on without fussing with the video. That's really just a workaround, it'll take more work to dig into the underlying issue.

Appreciate you posting these though - it helps. I'm sure we'll get it resolved.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
