### ISSUE TITLE
Endless loading in Cypress Test Runer when you click on a button that leads to the internal structure of the site.

### ISSUE THREAD

**Issue by sergerudenko** [cypress-io/cypress#19343]
### Current behavior

the page https://www.chartjs.org/docs/latest/ loads endlessly and won't open

the page loads endlessly and then nothing happens

### Desired behavior

page opened

### Test code to reproduce

Steps to reproduce:
1. cy.visit('https://www.chartjs.org/')
2. cy.get('.button__red').click()
note that the href of this button is "/.docs"

### Cypress Version

9.1.1

**Comment by sainthkh** [comment]
Confirmed with the code below:

```js
it('t', () => {
  cy.visit('https://www.chartjs.org/')
  cy.get('.button__red').click()
})
```
![image](https://user-images.githubusercontent.com/8130013/147168833-29384c33-928e-4af2-bbcc-e83dd5b3f8c9.png)
