### ISSUE TITLE
Cypress broken by URL with special characters

### ISSUE THREAD

**Issue by marcandre** [cypress-io/cypress#19355]
### Current behavior

Our Phoenix app will redirect `/vida` to `/vida/información-basica/empleo` (notice the special character "ó"). That page then opens a websocket (same URL).

A test with `cy.visit("/vida")` in Cypress breaks. Same test after the route is changed to remove the accent on the "o" works.

With the accent "ó", our server logs:
```
23:50:27.501 request_id=FsCF2BaXBlhl5zcAAAgJ [info] POST /end-to-end/login
%{account_id: 121}
23:50:27.513 request_id=FsCF2BaXBlhl5zcAAAgJ [info] Sent 200 in 11ms
23:50:27.765 request_id=FsCF2CZaEwCBqVMAAAhJ [info] GET /vida
23:50:27.776 request_id=FsCF2CZaEwCBqVMAAAhJ [info] Sent 302 in 10ms
23:50:27.994 request_id=FsCF2DQBvaBrqm8AABTF [info] GET /vida/información-basica/empleo
23:50:28.017 request_id=FsCF2DQBvaBrqm8AABTF [info] Sent 200 in 22ms
23:50:28.254 request_id=FsCF2EN3Zch76RgAABIH [info] GET /vida/informaci%C3%83%C2%B3n-basica/empleo
```

Without the accent, our server logs:
```
23:54:47.872 request_id=FsCGFLXrmkhSgwkAAH8C [info] POST /end-to-end/login
%{account_id: 123}
23:54:47.888 request_id=FsCGFLXrmkhSgwkAAH8C [info] Sent 200 in 16ms
23:54:48.434 request_id=FsCGFNdtukhKR34AAH9C [info] GET /vida
23:54:48.459 request_id=FsCGFNdtukhKR34AAH9C [info] Sent 302 in 24ms
23:54:49.175 request_id=FsCGFQOaTmBzlmsAAJzB [info] GET /vida/informacion-basica/empleo
23:54:49.228 request_id=FsCGFQOaTmBzlmsAAJzB [info] Sent 200 in 52ms
23:54:51.093 [info] CONNECTED TO Phoenix.LiveView.Socket in 59µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "..., "_mounts" => "0", "vsn" => "2.0.0"}
```

On the Cypress side, only a single line appears:

```
# With the accent:
GET /vida/informaci%C3%83%C2%B3n-basica/empleo 404 300.388 ms - -
# Without the accent:
GET /vida/informacion-basica/empleo 200 5.114 ms - -
```

Screenshots of the requests from Chrome:
![Screen Shot 2021-12-13 at 11 51 52 PM](https://user-images.githubusercontent.com/33770/145937170-db71ee49-c591-4f1e-bf37-1eacea445fa2.png)
![Screen Shot 2021-12-13 at 11 57 11 PM](https://user-images.githubusercontent.com/33770/145937191-90311c57-8383-49e6-8bb5-dd9077661cc4.png)

### Desired behavior

Cypress should respect the encodings. Note that our app currently runs in production, with users having the usual browsers on desktop and mobile.

### Test code to reproduce

```
cy.visit("/url-that-redirects-to-url-with-non-latin-characters"
```

### Cypress Version

2.88.10

**Comment by emilyrohrbough** [comment]
@marcandre Please try upgrading to the latest version of Cypress v9.1.1 and confirm is this is still an issue.

**Comment by marcandre** [comment]
@emilyrohrbough I wasn't on the latest because it crashed, but I found a workaround in #19320 and can confirm it is still an issue.

**Comment by sainthkh** [comment]
Confirmed that the code below:

```js
it('t', () => {
  cy.visit('https://seototo.net/한글-도메인-사용해도-될까-한글-도메인의-장단점-소/amp/')
})
```
![image](https://user-images.githubusercontent.com/8130013/147169965-477200e2-ea2f-48c9-b92a-c086e4e67afd.png)

**Comment by sainthkh** [comment]
You can bypass the problem by using `encodeURI` like below:

```js
it('t', () => {
  cy.visit(encodeURI('https://seototo.net/한글-도메인-사용해도-될까-한글-도메인의-장단점-소/amp/'))
})
```

**Comment by einarpersson** [comment]
I just spent 3 hours today, and finally found this issue which explains my problem. I'll use `encodeURI` now.

Please fix this, and consider adding a yellow warning box in the docs to `cy.visit` about this in the meantime.

Regards from Sweden (åäö)

**Comment by marcandre** [comment]
>  Cypress evolves quickly and the reported behavior should be tested on the latest version of Cypress

If there was timely support, I'd be more than willing to do that.

**Comment by nagash77** [comment]
Hi @marcandre , I apologize that this issue has not been worked on.  Our developers wish they could address every single issue that comes in but that is not realistic at this time.  We are making changes to our support process and continue to strive to give the best support possible.  I am going to close this issue until you have time to verify it is still happening in current versions of Cypress.  Please comment back here with details and we will be happy to reopen and investigate.

**Comment by marcandre** [comment]
@nagash77 here's the thing... I have opened a half dozen bug reports, most or all with reproducible code, I've been asked before to confirm it didn't work on different versions, and _none_ have been resolved.

Please understand you can not ask your users to keep on confirming that bugs are still valid versions after versions if nobody is doing anything about it, especially when the code to reproduce it is included.

The message you are sending me is loud and clear: open issues if you want, spend time writing reproducible code, but we'll ignore it anyways and close it after 6 months.

**Comment by nagash77** [comment]
@marcandre I totally understand your feelings.  We do our best to offer support to all our end users using this free tool but we cannot address every issue we wish we could.  I definitely understand if you cannot take the time to verify if you are still having the issue, but I just want to be transparent that given the amount of requests we get, we cannot guarantee an issue will be worked on in any given time frame.  And with all the pieces of Cypress that change over time, often these issues change or resolve themselves.   As we do not back patch as a rule of thumb and can only work on so many issues at any given point, we want to prioritize issues that are affecting current versions of Cypress.

**Comment by donaldpipowitch** [comment]
If it is not planned to fix it internally, maybe it could be at least added to the ["Common situations why this would fail:"](https://github.com/cypress-io/cypress/blob/a0a4eb1b2c1baac9f4d6ad4b02a3db44b4abd70b/packages/driver/src/cypress/error_messages.ts#L1413) message with the suggested workaround?
