### ISSUE TITLE
Beeing able to use .click() on a select component

### ISSUE THREAD

**Issue by bluepioupiou** [cypress-io/cypress#19359]
### What would you like?

I would like to be able to do a click action on a select component. Right now I get a Cypress error telling me to use select() function but for me it's quite different.

The click() action will juste show/display the options of the select input

### Why is this needed?

In my tests I take screnshots to generate Xray results with proofs and I would like to display the "open" select to be checked by whoever check the xray report.

**Comment by flotwig** [comment]
This would require native events, which Cypress currently does not support. You can use `cypress-real-events` to trigger real click events on a `<select>`: https://github.com/dmtrKovalenko/cypress-real-events

**Comment by bluepioupiou** [comment]
Thanks a lot it does the trick !!
