### ISSUE TITLE
chore: move forked deps into monorepo/replace with patch packaged dep

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#19367]
### What would you like?

Repos that are dependencies of `cypress` that could be refactored by just making it patch-package or moving it into the monorepo (or maybe leaving it as is!):

- https://github.com/cypress-io/sinon-chai
- https://github.com/cypress-io/request
- https://github.com/cypress-io/foxdriver
- https://github.com/cypress-io/node-xvfb
- https://github.com/cypress-io/mocha-teamcity-reporter
- https://github.com/cypress-io/opn (Required by cypress/server, awaiting a fix from sindesaurus or a change in our behavior to replace #183) 
- https://github.com/cypress-io/fira (this may be removed in 10.0-release?)
- https://github.com/cypress-io/bower-kendo-ui (we might could remove this entirely, not sure this offers value to our tests anymore)
- https://github.com/cypress-io/listr-verbose-renderer
- https://github.com/cypress-io/jscodemods (this was used for decaffeinate - maybe it's already removed?)
- https://github.com/cypress-io/socket.io-circular-parser
- https://github.com/cypress-io/what-is-circular
- https://github.com/cypress-io/parse-domain
- https://github.com/cypress-io/request-promise

### Why is this needed?

These repos are not closely watched, so we're missing any patches given to the original package (like critical security dependencies).

**Comment by flotwig** [comment]
One thing blocking cypress-io/request from being moved to `patch-package` is that it is used in the CLI, where we can't distribute patched packages. However, we could probably swap out that usage for a more maintained library.

**Comment by tgriesser** [comment]
> One thing blocking cypress-io/request from being moved to patch-package is that it is used in the CLI, where we can't distribute patched packages. However, we could probably swap out that usage for a more maintained library.

I'm good with swapping out, but kind of along the the same lines - have we ever looked into considered using something like https://github.com/vercel/ncc to build the CLI into a single package, so we don't have any dependencies we need to worry about for the install?
