### ISSUE TITLE
[typescript] Cypress.session type does not exist

### ISSUE THREAD

**Issue by IanVS** [cypress-io/cypress#19363]
### Current behavior

I tried to use `Cypress.session.clearAllSavedSessions();`, but got a typescript error.

![image](https://user-images.githubusercontent.com/4616705/146071324-e0e84c9c-faed-427f-acaa-79279c92611f.png)

### Desired behavior

`Cypress.session` should be typed correctly.

### Test code to reproduce

https://github.com/IanVS/cypress-test-tiny

`npm i`
`npm run typecheck`

### Cypress Version

9.1.1

**Comment by emilyrohrbough** [comment]
@IanVS Would you be interested in contributing the types for this syntax?

**Comment by IanVS** [comment]
Honestly I'm not sure why they're not already there, since the file is written in typescript...  https://github.com/cypress-io/cypress/blob/e216ae2422706d4f46e6dfa68abe2d589c72cf96/packages/driver/src/cy/commands/sessions.ts#L303

To me, that points to a larger problem in the way that typescript is being run and published within the repo.  Maybe it's better for someone with more familiarity to take a quick look at it?

**Comment by emilyrohrbough** [comment]
@IanVS I think the issue is session is missing from the [Cypress interface here](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L208).

**Comment by IanVS** [comment]
:+1: thanks, then yeah I can take a crack at adding it.
