### ISSUE TITLE
`cy.contains` removes `<script>` and `<style>` nodes from the app under test

### ISSUE THREAD

**Issue by simfeld** [cypress-io/cypress#19377]
### Current behavior

Since version `9.0.0`, calling `cy.contains` removes `<script>` and `<style>` nodes from the DOM of the app under test. This is most likely caused by the change in #17477. From the description in the changelog

> `cy.contains()` no longer yields the `<body>` element when it matches the content of `<script>` or `<style>` tags.

I would expect that this only affects the result of the `contains` command, but leaves the actual DOM unchanged.

### Desired behavior

The `cy.contains` command should not alter the DOM of the application under test as a side effect.

### Test code to reproduce

The problem can be reproduced with https://github.com/simfeld/cypress-contains-script. Note that downgrading to `8.7.0` makes these tests pass.

### Cypress Version

9.0.0 and later

**Comment by tobiasweibel** [comment]
As another drawback of the #17477 change the stack traces of code that is loaded within `<body>` doesn't make sense anymore. I think I remember that even the browser dev tools aren't working properly after upgrading to Cypress v9 if code was loaded within `<body>`.

**Comment by jennifer-shehane** [comment]
cc @sainthkh

**Comment by jennifer-shehane** [comment]
I can confirm the behavior described. The `<script>` and `<style>` tags are being removed from the DOM simply by calling `cy.contains()` on something that is matched within them. This is not intended behavior.
