### ISSUE TITLE
Okta authentication failed

### ISSUE THREAD

**Issue by fseee** [cypress-io/cypress#19373]
### Current behavior

We are currently running tests on cypress on a single page application.
The authentication is based on okta as identity provider and is hosted on our custom login page, so no redirect is requested to the okta login page.
The library used for authentication is [the okta-auth-js](https://github.com/okta/okta-auth-js), and the login method is as follows:

```
login(username: string, password: string) {
    return this.oktaAuthClient.signInWithCredentials({
        username: username,
        password: password
    }).then((response) => {
        if (response.status === 'SUCCESS') {
            return this.oktaAuthClient.token.getWithoutPrompt({
                issuer: environment.okta_issuer,
                responseType: ['token'],
                sessionToken: response.sessionToken,
            }).then((tokenObj) => {
                const idToken = tokenObj.tokens.idToken;
                const accessToken = tokenObj.tokens.accessToken;
                this.oktaAuthClient.tokenManager.setTokens({
                    accessToken,
                    idToken
                });
                return true;
            }).catch((err) => {
                console.error("Get Without Prompt Error :", err);
                return false;
            })
        } else {
            console.error("Response Status Error", response.status);
	    return false;
        }
    }).catch((err) => {
        console.error("err", err);
	return false;
    })
}
```
the issue is that by prompting username and password and executing login, the above signInWithCredentials method will result in below error, catched in the last code block:

```
err: AuthApiError at http://localhost:4200/
	errorCauses: undefined
	errorCode: undefined
	errorId: undefined
	errorLink: undefined
	errorSummary: undefined
	name: "AuthApiError"
	xhr: TypeError: Failed to fetch at http://localhost:4200/
	stack: "AuthApiError\n    at http://localhost:4200/"
	[[Prototype]]: CustomError
```

Cypress code is below:

```
Cypress.Commands.add('login', (username, password) => {
    cy.get('#username-input').clear().type(username).then(() => {
        cy.get('#password-input').clear().type(password).then(() => {
            cy.get('.login-panel').click().then(() => {
                cy.get('.sign-in-button').click();
            })
        })
    })
})
```

Please be aware that cypress is able to navigate external url (I've successfully tested cy.visit on multiple external sites), the problem is just when trying to call okta directly, since it seems that cypress browser is not able to open any xyz.okta.com urls.
Let's be clear, I'm not sure if I had to post this issue here or in the okta github issues repository, most probably I will ask there as well. 
I'm aware that a compromise solution could be to "simulate" a login as described [here](https://docs.cypress.io/guides/testing-strategies/okta-authentication#Custom-Command-for-Okta-Authentication) as suggested as best practice, maybe using [this](https://gist.github.com/ndavis/2c84ab40aaa3c98c3a8062bdb3938232) implementation, but that would completely invalidate the whole test workflow:

1. landing on login page
2. prompting username and password
3. clicking on login
4. redirecting to the main page using application internal auth-guard service 

Any help would be much appreciated, thanks.

### Desired behavior

Cypress should properly contact okta url and allow requests through okta-auth-js api

### Test code to reproduce

```
Cypress.Commands.add('login', (username, password) => {
    cy.get('#username-input').clear().type(username).then(() => {
        cy.get('#password-input').clear().type(password).then(() => {
            cy.get('.login-panel').click().then(() => {
                cy.get('.sign-in-button').click();
            })
        })
    })
})
```

### Cypress Version

9.1.1

**Comment by emilyrohrbough** [comment]
@fseee Assuming you test is something like:

```js
it('does something', () => {
    cy.visit('/login')
    cy.login() // fails
})
```
Your conclusion of 
> it seems that cypress browser is not able to open any xyz.okta.com urls.

is likely accurate. You can only visit urls with the same super domain in a single test. You can learn more about the limitations [here](https://docs.cypress.io/guides/guides/web-security#Limitations).

**Comment by fseee** [comment]
It was a proxy issue, solved by introducing HTTP_PROXY and HTTPS_PROXY env variables
