### ISSUE TITLE
Cypress and Facebook Login

### ISSUE THREAD

**Issue by exotlv** [cypress-io/cypress#19394]
### Current behavior

Right now when trying to Login with Cypress on Facebook, I'm getting an error:
Your Request Couldn't be Processed
There was a problem with this request. We're working on getting it fixed as soon as we can.
Return home

![image](https://user-images.githubusercontent.com/8436809/146381460-f2da6c48-b15d-42e9-937e-565a7a0e6810.png)

### Test code to reproduce

       cy.visit('https://www.facebook.com/')
       cy.get('button[data-testid="cookie-policy-dialog-accept-button"]').click();
       cy.get('input[id="email"]').click().type(Cypress.env('userName'));
       cy.get('input[id="pass"]').click().type(Cypress.env('userPassword'));
       cy.get('button[name="login"]').click();

### Cypress Version

7.7.0

**Comment by emilyrohrbough** [comment]
@exotlv This screenshot you provided does not appear to indicate an issue with Cypress. Please check with Facebook/Meta for Developers to learn the best approach for testing Facebook. This ["Testing a Login Flow" document ](https://developers.facebook.com/docs/facebook-login/testing-your-login-flow) appears to provide some guidance for creating test users for testing applications.
