### ISSUE TITLE
Config variable not updated

### ISSUE THREAD

**Issue by pcmanprogrammeur** [cypress-io/cypress#19392]
### Current behavior

Hi,

I have a problem with the config variable which is not updated in the plugins/index.js file.

The result of logs is :
```
log : {database_uri: [DATABASE_URI], database_name: de_dev}
task : findUser
log : {database_uri: [DATABASE_URI]}
```

### Test code to reproduce

Here are all my files content :

**cypress.json :**
```
{
  "video": false,
  "env": {
    "database_uri": "[DATABASE_URI]"
  },
  "sites": [
    {
      "code": "de",
      "database_name": "de_dev"
    },
    {
      "code": "fr",
      "database_name": "fr_dev"
    },
    {
      "code": "uk",
      "database_name": "uk_dev"
    }
  ]
}
```

**integration/test.js :**
```
/// <reference types="cypress" />

Cypress.config().sites.forEach((site) => {
    describe(
        'Test ' + site.code,
        {
            env: {
                database_name: site.database_name
            },
        },
        () => {
            it('Test ' + site.code, () => {
                cy.log(Cypress.env())
                cy.task('findUser').then((user) => {
                    cy.log(user)
                })
            })
        }
    )
})
```

**plugins/index.js :**
```
module.exports = async (on, config) => {
    on('task', {
        'findUser': async () => {
            return config.env;
        }
    })
}
```

As you can see, we lose the env variable "database_name" when we are in the file plugins/index.js.

### Cypress Version

8.3.0

**Comment by emilyrohrbough** [comment]
@pcmanprogrammeur Thanks for providing a clear example of the issue you are facing.

The behavior you are experiencing is expected given how the Plugins are leverages and resolved in Cypress. The Plugins allow you to hook into and extend Cypress behavior by enabling you to tap into the Node process running outside of the browser. 

When you start Cypress, your Plugin file will allow you to dynamically modify configuration values and environment variables and will determine the configuration used during your Cypress run. At this point, the configuration provided to plugins file will be static and it will not update if Test Overrides are passed or if configuration has been updated through `Cypress.config()`.

I recommend restructuring this a bit to meet your needs:
```diff
// spec
-                cy.task('findUser').then((user) => {
+                cy.task('findUser').then((site.database_name) => {


// plugins/index.js
module.exports = async (on, config) => {
    on('task', {
-        'findUser': async () => {
+        'findUser': async (database) => {
            // look up user
        }
    })
}
```

**Comment by pcmanprogrammeur** [comment]
Thank you @emilyrohrbough !

This is the first idea I had but it involves sending the information from the database in each call (over 30).

That's why I wanted to manage connections by environment variable.

**Comment by emilyrohrbough** [comment]
Any time. I'm going to go ahead and close this issue.
