### ISSUE TITLE
Screenshot on failure should scroll the command list

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#194]
When capturing the screenshot on failure, it would be nice if the left column with
the command list scrolled to the bottom to show the latest failure

**Comment by brian-mann** [comment]
Yup I agree - @chrisbreiding has been working on this feature which may make it into `0.17.0`. 

It will auto scroll with you as the tests run so when a `cy.screenshot` happens the current test will be in view.

**Comment by brian-mann** [comment]
Fixed in [`0.17.0`](https://github.com/cypress-io/cypress/wiki/changelog#0170-08302016).
