### ISSUE TITLE
`cy.root().should` in a `within` should retry failed assertions

### ISSUE THREAD

**Issue by marcandre** [cypress-io/cypress#19404]
### Current behavior

My [test example](https://github.com/cypress-io/cypress-test-tiny/pull/71/commits/fddb7a3e35e40ba24a466610327b294d3490e056) shows how `cy.root()` does not retry failed tests when called inside a `within`. It also shows quite similar tests that work as they are intended.

### Test code to reproduce

[PR showing issue](https://github.com/cypress-io/cypress-test-tiny/pull/71)

### Cypress Version

9.1.1

**Comment by sainthkh** [comment]
Confirmed with the code below:

```js
describe('page', () => {
  beforeEach(() => {
    cy.visit('https://example.cypress.io')
    writeHelloAfter1s()
  })

  it('`root` inside a `within` should retry but doesn\'t (bug)', () => {
    cy.get('body').within(() => {
      cy.root().should('contain', 'Hello')
    })
  })
})

function writeHelloAfter1s () {
  cy.window().then((w) => {
    w.eval(`setTimeout(() => {
        document.querySelector('.banner .container').innerHTML = '<p> Hello, world!</p>'
      }, 1000)
      console.log("ok")
      `)
  })
}
```

Thank you for the reproducible code.

**Comment by marcandre** [comment]
If there was timely support, I'd be more than willing to do that.

**Comment by nagash77** [comment]
Hi @marcandre  , I apologize that this issue has not been worked on. Our developers wish they could address every single issue that comes in but that is not realistic at this time. We are making changes to our support process and continue to strive to give the best support possible. I am going to close this issue until you have time to verify it is still happening in current versions of Cypress. Please comment back here with details and we will be happy to reopen and investigate.
