### ISSUE TITLE
`cy.request()`, `cy.visit()` and `cy.intercept()` query strings are inconsistent

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#19407]
### Current behavior

The query string generated from the query search options of `cy.request()` and `cy.visit()` are inconsistent.

`cy.request()` accepts `qs` option to generate query parameters to append to the url of the http request. Under the hood, the http request is passed to `@cypress/request` which uses the `qs` library by default to stringify & parse the qs object. `@cypress/request` does accept additional qs parameters to toggle the use of the [`qs`](https://www.npmjs.com/package/qs) library and [`query-string`](https://www.npmjs.com/package/query-string) library (provided by Node.JS) as well as takes options for the stringification/parsing configuration.

`cy.visit()` also accepts a `qs` option to generate query parameters to append to the new browser url request. This command is using the `url-parse` module, which uses `[querystringify](https://www.npmjs.com/package/querystringify)` stringify & parse the qs object.

With different libraries are being used, the query parameters are inconsistent, causing unexpected behavior for consumers. Additional because of the different library that are in use, we cannot provide additional qs configuraiton options at this time without the options diverging for `cy.request()` & `cy.visit()`. 

### Desired behavior

The query string generated from the query search options of `cy.request()` and `cy.visit()` are the same. 

_Nice to have:_ be able to provide qs configuration options once these align.

### Test code to reproduce

```js
  it.only('queries should match', () => {
    let visitURL
    let requestURL

    cy.intercept('https://jsonplaceholder.cypress.io/comments*', {
      statusCode: 200,
      headers: {
        'content-type': 'text/html',
      },
    }).as('request')

    cy.visit({
      url: 'https://jsonplaceholder.cypress.io/comments',
      qs: {
        postId: [1, 2],
        id: 3,
      },
    })

    cy.wait('@request').then(({ request }) => {
      visitURL = request.url
    }).then(() => {
      cy.request({
        url: 'https://jsonplaceholder.cypress.io/comments',
        qs: {
          postId: ['1', '2'],
          id: 3,
        },
      }).then((resp) => {
        requestURL = resp.allRequestResponses[0]['Request URL']
      })
    }).then(() => {
      expect(visitURL).to.eq(requestURL)
    })
  })
```
<img width="818" alt="Screen Shot 2021-12-16 at 5 22 31 PM" src="https://user-images.githubusercontent.com/14099737/146465233-6fedd21b-fa12-4986-a06a-b2056a1d6dcf.png">

### Cypress Version

9.1.1+

### Other

While investigating https://github.com/cypress-io/cypress/issues/17921, this is was discovered.

**Comment by emilyrohrbough** [comment]
It appears `cy.intercept()` is using the [`url`](https://www.npmjs.com/package/url) module which uses [`querystring`](https://www.npmjs.com/package/querystring?activeTab=readme) to parse the query string to match intercepted routes.

**Comment by jennifer-shehane** [comment]
@emilyrohrbough This would be something good to bring up with @flotwig when he gets back to understand why this is.
