### ISSUE TITLE
REPL-like environment for running command chains after a test

### ISSUE THREAD

**Issue by itsalaidbacklife** [cypress-io/cypress#19427]
### What would you like?

It would be incredibly powerful to be able to run cypress command chains via the console after a test has finished like [cy.now()](https://docs.cypress.io/guides/guides/debugging#Run-Cypress-command-outside-the-test) except able to execute commands that are compositional chains of other cypress commands (`cy.now()` can only run a single command that does not itself chain other commands).

After a test completes the [dangling state is your friend](https://docs.cypress.io/guides/guides/debugging#Run-Cypress-command-outside-the-test) -- it is an amazing feature of cypress that you can look at your application state under the hood and **play around with the application interactively**, as this lets you dig deeper into your application's behavior in a free-form way that is flexible to your needs. 

Where this falls short is if you want to take actions behind-the-scenes on behalf of other users after a test completes (e.g. in a websocket driven application where my experience as a user depends on actions taken by other users). A full REPL environment would not be necessary, but a more robust, externally facing analog to `cy.now()` that allows the execution of command chains would allow cypress to revolutionize the active development of complex features by bootstrapping access to edge case in an interactive environment.

### Why is this needed?

To use cypress for active development and debugging of features details which are too subtle and nuanced to capture in assertions but which are cumbersome to reach 'organically' using the browser.

For example, suppose I am working on an animation for a particular edge case in my websocket-driven card game. It requires a specific configuration of cards on the field and then a sequence of plays made by myself and my opponent to be triggered. I can use cypress' testing capabilities to confirm that the appropriate classes and styles are applied at the correct time, but if I want to nail the UX of how the interaction **feels** I will need to iteratively replicate it myself and look at the result as I make changes. The automated test runner goes too quickly to get a good feel for what the actual experience will be like for my users, so I want to click around in the application to trigger the effect (particularly while I am in the process of iteratively working out how it should look and feel).

But setting up the particular edge case is incredibly cumbersome outside of cypress. It entails using multiple browser windows to sign in with multiple accounts before arduously setting up the specific edge case I'm developing by hand. Currently, I can get halfway towards an ideal solution by writing a 'dummy' cypress test that sets up the edge case and then ends the test, allowing me to tinker with the dangling state of the application by hand in order to trigger the exact interaction I'm working on. This works reasonably well, but where it falls short is when I want to organically simulate various sequences of interactions between my user in the UI (by clicking around) and the unseen opponent whose moves are made during my tests using cypress commands that make requests directly to my backend api. 

The ideal solution, which I think could revolutionize test-driven development of complex multi-user applications, is a REPL-like ability to interleave within-UI interactions in the dangling state (already possible) with arbitrary chains of cypress commands (which for my use case, are most useful for their ability to take actions on behalf of other users).

### Other

This request follows up on an exciting [blog post](https://glebbahmutov.com/blog/cy-now-and-state/) by Gleb Bahmutov on the subjects of `cy.now()` and `cy.state()` which are **tantalizingly close** to bridging the current gap between what is concretely, programmatically testable, and the greyer, UX-oriented details that need to be evaluated by the human eye. With official support for a more robust REPL-like environment, cypress could save engineers even more time building even better interactions.

EDIT: typo

**Comment by bahmutov** [comment]
“exciting” not “exiting” I guess. And I would love REPL too

**Comment by itsalaidbacklife** [comment]
**WORKAROUND**: in my use case, the main reason that I want to execute composite commands that chain other commands is because my API endpoints are parameterized with ID's (e.g. which game you're in and which card you're playing) that are tracked in my vuex store, which I've exposed to cypress by adding my Vue app instance to the window object.

So the structure of many of my request-making cypress commands is to use 

```
cy.window().its('app.$store')
.then(()=> // do stuff);
```
to grab the relevant ID's from the store before making a request to the backend. That's the part that doesn't work with `cy.now()`

So my awkward kludge of a workaround is to write alternative versions of whatever commands I want to run in REPL which explicitly input the necessary ID's as parameters of the command instead of grabbing them programmatically from the store. The jankity part of this is that in order to provide those ids, I need to make the test itself read these ids from the store and `console.log()` them, so that I can manually type them into the params of the REPL version of the command inside the `cy.now()` call.

This is clearly inelegant, but it circumvents the need for a composite cypress command chain, which enables me to use `cy.now()` for more robust use cases.
