### ISSUE TITLE
chromeWebSecurity:false is not working 

### ISSUE THREAD

**Issue by varshanharshank** [cypress-io/cypress#19435]
### Current behavior

I had set the attribute chromeWebSecurity:false in cypress.json. But when i execute my test, it is throwing the below error.

Note: In my script, two different urls.

 CypressError: `cy.visit()` failed because you are attempting to visit a URL that is of a different origin.

The new URL is considered a different origin because the following parts of the URL are different:

  > superdomain

You may only `cy.visit()` same-origin URLs within a single test.

### Desired behavior

It should consider the chromeWebSecurity:false and able to navigate different domains

### Test code to reproduce

I am running scripts in BDD style .

### Cypress Version

9.1.1

**Comment by mjhenkes** [comment]
I believe you're running into our current multi-domain limitation. We're currently working on supporting multi-domain.

Follow #17336 for progress updates.

For more info see our current [multi-domain limitation](https://docs.cypress.io/guides/guides/web-security#Same-superdomain-per-test) documentation

**Comment by NorseGaud** [comment]
@mjhenkes, Cypress 11.x is out and this is still an issue.

**Comment by NorseGaud** [comment]
bump

**Comment by AtofStryker** [comment]
@NorseGaud @varshanharshank would either of you be able to provide a reproduction of the issue with the latest version of Cypress?

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
