### ISSUE TITLE
Cypress controll panel disapears

### ISSUE THREAD

**Issue by toahawk-hu** [cypress-io/cypress#19439]
### Current behavior

![image](https://user-images.githubusercontent.com/68554958/146933007-4080582c-35f0-4108-8dc1-6c9c11497798.png)

Here everything is OK. I writes my e-mail account to login. And click the next button.
Then, in the cypress test there is a cy.pause(), because a 6 digit code arrives to that mail address (user have to write it into the proper field). I writes it, and I want to click the play button to resume the test running, but it disapears.

![image](https://user-images.githubusercontent.com/68554958/146933141-b0bd3acc-15d4-4f6d-9efc-5a84d95ef224.png)

### Desired behavior

Should show the button

### Test code to reproduce

describe('Zoho people filler', function () {
    beforeEach('Before', function () {
        Cypress.Cookies.preserveOnce('session_id', 'remember_token');
        Cypress.Cookies.debug(true);
    });

    it('Login to ZOHO application', function () {
        const username = 'toth.attila@idbc.hu';

        cy.clearCookies();
        cy.visit('https://accounts.zoho.eu/signin?servicename=ZohoHome&signupurl=https://www.zoho.com/signup.html');
        cy.get('#login_id').type(username);

        cy.get('#nextbtn').click();
        // here arrives the login code to e-mail address
        cy.pause();
        // here resume button disapears

### Cypress Version

latest

**Comment by mjhenkes** [comment]
@toahawk-hu looks like your running into our [superdomain limitation](https://docs.cypress.io/guides/guides/web-security#Same-superdomain-per-test) when you switch from `https://accounts.zoho.eu` to `https://www.zoho.com`

We're working implementing this feature on issue #17336, but for now check out the doc I linked above for work arounds.
