### ISSUE TITLE
[9.0.0 Regression] Change #17496 breaks linter on return types

### ISSUE THREAD

**Issue by faiteanu** [cypress-io/cypress#19443]
### Current behavior

Change #17496 in `9.0.0` modified the signatures of `Cypress.Commands.add()` methods. Now our linter (@typescript-eslint) marks our common Cypress commands as erroneous. 

Minimal code example:
```TS
export {};

declare global {
    namespace Cypress {
        interface Chainable<Subject = any> {
            doFoo(arg: string): Chainable<string>
        }
    }
}

Cypress.Commands.add('doFoo', (arg) => {
    cy.wrap(arg);
});
```
Error message from the linter on the line with `(arg) => {` is:
`TS2345: Argument of type '(arg: string) => void' is not assignable to parameter of type '(arg: string) => Chainable<string>'. Type 'void' is not assignable to type 'Chainable<string>'.`

The message is understandable, because doFoo is supposed by definition to return a `Chainable<string>`, but it does not have a return statement, thus is considered to return void.

For us this was a breaking change, as it renders every custom command invalid and breaks the CI/CD pipeline with TS errors. As a return statement is a syntactical element of the TypeScript language, it cannot be disabled by a rule for a linter.

### Desired behavior

Cypress should provide code that results in syntactically correct TypeScript for custom commands.

`Cypress.Commands.add()` should have a function type parameter similar to `CanReturnChainable<T>`, so that the return type is allowed to be `void` for methods that do not have an explicit return statement and rely on _yielding_.

As a workaround, we tried to insert return statements before the last Cypress command of each method, but that does not really  look Cypress-style-like (https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Return-Values):
```TS
Cypress.Commands.add('doFoo', (arg) => {
    cy.visit('...');
    cy.get('..').click();
    return cy.wrap(arg); // 'return' should not be present here
});
```

### Test code to reproduce

see above

### Cypress Version

9.1.1

### Other

Note that in `cli/types/tests/cypress-tests.ts` there is not a single example of a custom method with Chainable return type, thus the issue was probably overlooked.

**Comment by Narretz** [comment]
9.2.0 (just released) fixes some type issues with Cy.add, maybe your issue is fixed with that? https://docs.cypress.io/guides/references/changelog#9-2-0

**Comment by nitzanashi** [comment]
@ faiteanu your function does not return anything and therefore it has a false return value 
change it to `doFoo(arg: string): void` and it will work

**Comment by faiteanu** [comment]
Thanks  @Narretz, #19003 fixed the problem.

@nitzanashi: I suggest you read the concept of [yielding in Cypress ](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Some-commands-yield). My example above worked correctly with `8.7.0` and now again with `9.2.0`.

**Comment by nitzanashi** [comment]
> Thanks @Narretz, #19003 fixed the problem.
> 
> @nitzanashi: I suggest you read the concept of [yielding in Cypress ](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Some-commands-yield). My example above worked correctly with `8.7.0` and now again with `9.2.0`.

@faiteanu You are correct sorry for misleading you thanks for pointing me to docs!
