### ISSUE TITLE
Cypress test doesn't display any text

### ISSUE THREAD

**Issue by simsim2006** [cypress-io/cypress#1944]
I'm using Cypress 3.0.1 and Chrome 67.0.3396.87. I didn't install any extension since last time cypress was working. I tried to reinstall Chrome but it doesn't help.

![cypress_issue](https://user-images.githubusercontent.com/9596971/41407717-955bb9a8-6fd0-11e8-867a-78ee71b68503.png)

**Comment by jennifer-shehane** [comment]
Duplicate issue: https://github.com/cypress-io/cypress/issues/1944

Our team has never seen this error. We would *love* to investigate this issue, but we *have* to be able to reproduce it ourselves. Can you provide the tests you ran? Any more details in the other issue?

**Comment by simsim2006** [comment]
mmhhhh #1944 is a duplicate of #1944 ... i will try that when my backlog will be a bit too overloaded and i want to close a few of them 😄 

i found a workaround, but running my test with Electron 59 instead of Chrome. The issue is not related to a test in particular. It occurs for all my tests, while they were working previously.

**Comment by simsim2006** [comment]
i also uninstalled cypress, removed it from my cache (`rm -rf /Users/xxxxxxxxxxxx/Library/Caches/Cypress`), reinstalled it, but nothing help. 

What kind of information could be helpful for you ?
