### ISSUE TITLE
Typescript for runtime properties still missing?

### ISSUE THREAD

**Issue by yongish** [cypress-io/cypress#19448]
### Current behavior

`Cypress.config('UserID')` gives the following error in VSCode.
```
No overload matches this call.
  Overload 1 of 4, '(key: keyof ResolvedConfigOptions | keyof RuntimeConfigOptions): string | number | boolean | string[] | { [key: string]: any; } | ... 8 more ... | Spec[]', gave the following error.
    Argument of type '"UserID"' is not assignable to parameter of type 'keyof ResolvedConfigOptions | keyof RuntimeConfigOptions'.
  Overload 2 of 4, '(Object: ConfigOptions): void', gave the following error.
    Type '"UserID"' has no properties in common with type 'ConfigOptions'.ts(2769)
```

<img width="1363" alt="Screen Shot 2021-12-21 at 3 56 06 PM" src="https://user-images.githubusercontent.com/3132550/147013520-c20d9547-5eac-43c8-8ded-092c2e855f1c.png">

My `cypress.json`:
```
{
  "baseUrl": "http://localhost:8001/personalization/interactions?roles=PP_SSO_CEP_SuperAdmin",
  "integrationFolder": "cypress/integration",
  "defaultCommandTimeout": 50000,
  "UserID": "sujanarthanan",
  "viewportWidth": 1500,
  "viewportHeight": 900,
  "maxWait": "9000",
  "ignoreTestFiles": "**/examples/*.js"
}
```

Same issue as https://github.com/cypress-io/cypress/issues/19001, which was closed after Cypress 9.2.0 was released.

### Desired behavior

Cypress should provide support for runtime properties in the developer's IDE of choice.

### Test code to reproduce

See above.

### Cypress Version

9.2.0

**Comment by emilyrohrbough** [comment]
@yongish `UserID` is not a valid cypress configuration options. Try including this option as an env option:
```js
{
   "env": {
      "UserID": "sujanarthanan",
  }
}
```
and accessing it like:
```js
Cypress.env("UserID")
```

**Comment by yongish** [comment]
Thank you Emily.
