### ISSUE TITLE
cypress.env.json file nulling out defaults found in cypress.json

### ISSUE THREAD

**Issue by spencer-vizio** [cypress-io/cypress#19444]
### Current behavior
When I create a `cypress.env.json` file that only overrides `baseUrl` and `apiUrl` the other values like `integrationFolder` and `projectId` are being nulled out. 

My `cypress.json` looks like this: (where `****` are omitted values)
```{
    "projectId": "****",
    "baseUrl": "****/",
    "testFiles": "**/*.e2e.ts",
    "fixturesFolder": "fixtures",
    "integrationFolder": "tests",
    "pluginsFile": "plugins/index.ts",
    "screenshotsFolder": "screenshots",
    "screenshotOnRunfailure": true,
    "supportFile": "support/index.ts",
    "viewportWidth": 1280,
    "viewportHeight": 720,
    "videosFolder": "videos",
    "env": {
        "baseUrl": "****",
        "apiUrl": "****"
    }
}
```
`cypress.env-staging.json`
```
{
    "baseUrl": "****",
    "apiUrl": "****"
}
```

### Desired behavior

Only the values that collide in both `cypress*.json` files should be overridden / overwritten by the `cypress.env.json` file. **THIS IS HOW THE BEHAVIOR IS DESCRIBED IN THE CYPRESS DOCS** https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypress-env-json

### Test code to reproduce

My `cypress.json` looks like this: (where `****` are omitted values)

```{
    "projectId": "****",
    "baseUrl": "****/",
    "testFiles": "**/*.e2e.ts",
    "fixturesFolder": "fixtures",
    "integrationFolder": "tests",
    "pluginsFile": "plugins/index.ts",
    "screenshotsFolder": "screenshots",
    "screenshotOnRunfailure": true,
    "supportFile": "support/index.ts",
    "viewportWidth": 1280,
    "viewportHeight": 720,
    "videosFolder": "videos",
    "env": {
        "baseUrl": "****",
        "apiUrl": "****"
    }
}
```

`cypress.env-staging.json`
```
{
    "baseUrl": "****",
    "apiUrl": "****"
}
```

### Cypress Version

9.1.1

### Other

This was first discovered as an issue when I noticed that my GH Action workflow wasn't able to find my `projectId` even though it was set in my `cypress.json` , but **wasn't** set in my override file `cypress.env-staging.json`

**Comment by jennifer-shehane** [comment]
@spencer-vizio How is the `cypress.env-staging.json` file being read into Cypress, because Cypress only reads in a file named `cypress.env.json`. Do you have code setup somewhere that reads in the values of `cypress.env-stagins.json` somewhere?

**Comment by elamurugan-r** [comment]
Is there anyway to define multiple env files like (cypress.test.env.json, cypress.prod.env.json) and if so how to configure and how to run based on env file from run command in Cypress10?
