### ISSUE TITLE
Issue While Uploading Json and Avro Files

### ISSUE THREAD

**Issue by bharat-dussa** [cypress-io/cypress#19452]
### Current behavior

Hi, i want to test out the upload functionality in my project, but somehow it fails.
By manually uploading through UI it is perfectly working, there is no issue
but when i use cypress to test out uploading feature, 
testing out kafka files and avro files.
it giving an error: 

### Desired behavior

Cypress should upload as it is without doing any changes with data.
as we are converting them to base64.

### Test code to reproduce

for json:     
  
            cy.fixture("common-dataset.json").as("kafkaJson");
            cy.get("input[type=file]").then(function (el) {
                const blob = Cypress.Blob.base64StringToBlob(
                    window?.btoa(JSON.stringify(this.kafkaJson)),
                    "application/json"
                );
            const file = new File([blob], "common-dataset.json", {
                type: "application/json",
            });
            const list = new DataTransfer();

            list.items.add(file);
            const myFileList = list.files;

            el[0].files = myFileList;
            el[0].dispatchEvent(new Event("change", { bubbles: true }));
        });

for avro:

        cy.fixture("avro_file.avro").as("avro");
        // eslint-disable-next-line jest/valid-expect-in-promise
        cy.get("input[type=file]").then(function (el) {
            const fileEncode = window?.btoa(
                unescape(encodeURIComponent(this.kafkaJson))
            );
            const blob = Cypress.Blob.base64StringToBlob(
                fileEncode,
                "application/avro+json"
            );

            const file = new File([this.kafkaJson], "avro_file.avro", {
                type: "application/json",
            });
            const list = new DataTransfer();

            list.items.add(file);
            const myFileList = list.files;

            el[0].files = myFileList;
            el[0].dispatchEvent(new Event("change", { bubbles: true }));
        });

### Cypress Version

7.7.0 & 9.2.0

**Comment by Narretz** [comment]
Have you tried with the latest Cypress version?

Another option is to use the dedicated plugin for Cypress: https://www.npmjs.com/package/cypress-file-upload

**Comment by bharat-dussa** [comment]
> Have you tried with the latest Cypress version?
> 
> Another option is to use the dedicated plugin for Cypress: https://www.npmjs.com/package/cypress-file-upload

Tried using this plugin.

Try to give another shot by latest cypress version.

**Comment by bharat-dussa** [comment]
@Narretz 
tried with latest version its still giving same issue
