### ISSUE TITLE
Cypress runner does not load

### ISSUE THREAD

**Issue by oxkr21** [cypress-io/cypress#19478]
### Current behavior

When I run cypress it does not fully load the runner and in my project it does not generate all the folders, only the plugins

/usr/local/Cellar/node/17.0.1/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

I work on a mac computer and Visual Studio Code

### Desired behavior

That cypress runs correctly

### Test code to reproduce

/usr/local/Cellar/node/17.0.1/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

### Cypress Version

9.2.0

### Other

This problem was once I update the cypress version.

**Comment by lanwen** [comment]
seems duplicates https://github.com/cypress-io/cypress/issues/19320

**Comment by mjhenkes** [comment]
Closing as duplicate.

Thanks @lanwen
