### ISSUE TITLE
Version 9.2.0 can't loading menu correct in macos

### ISSUE THREAD

**Issue by cuobiezi** [cypress-io/cypress#19474]
### Current behavior

cypress can't load menu successful, just display loading icon

### Desired behavior

cypress can load menu successful 

### Test code to reproduce

I want just write my first cypress test according Docs. But cypress can't load menu successful, just display loading icon.

I try to install version 8.7.0 instead 9.2.0 it is working now.

### Cypress Version

9.2.0

**Comment by oxkr21** [comment]
Hello, 

I have a similar problem. When you run cypress does it send you this in the terminal?

/usr/local/Cellar/node/17.0.1/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

**Comment by mjhenkes** [comment]
@cuobiezi Could you provide more information? Is the app crashing? Are there any logs?

@oxkr21 Your issue is most likely related to issue #19320 and its related issues.
