### ISSUE TITLE
Cypress XHR requests get aborted when running headless, in cypress based image container

### ISSUE THREAD

**Issue by iuyt9003** [cypress-io/cypress#19481]
### Current behavior

Cypress XHR requests get aborted when running headless, in a cypress-based image container. Browser: Electron

```js
describe('Test Sign-In and search', () => {
  before(() => {
    cy.clearLocalStorageSnapshot();
  });
  beforeEach(() => {
    cy.restoreLocalStorage();
  });
  afterEach(() => {
    cy.saveLocalStorage();
  });
  it('Test Sign In Process', () => {
    cy.visit(Cypress.config().baseUrl);
    cy.get('[data-test="signInHeader"]', { timeout: 10000 }).should(
      'be.visible'
    );
    cy.get('[data-test="emailInput"]').type(Cypress.env('USER_EMAIL'));
    cy.get('[data-test="passwordInput"]').type(Cypress.env('USER_PASSWORD'));
    cy.get('[data-test="signInBtn"]').click(); // Preform Sign-in
    cy.get('[data-test="newAnalysisHeader"]', { timeout: 25000 }).should(
      'be.visible'
    );
  });
```

![Uploading image.png…]()

### Desired behavior

To not abort the XHR request :(

### Test code to reproduce

Use angular, with angular client add some HTTP requests (angular client based XHR requests). 

### Cypress Version

9.1.1

**Comment by mjhenkes** [comment]
Hey @iuyt9003, thanks for logging this issue. Could you help us get a reproduce-able test case put together? Do all xhr requests get aborted? Which docker container are you using? Do requests not get aborted in open mode?

**Comment by sheinze** [comment]
I can reproduce the error using the `cypress/base:10` as well as the `cypress/browsers:node14.15.0-chrome96-ff94` image. For me, all intercepted XHR requests in the test suite get aborted when using the run mode of cypress. The open mode does not start when missing an x server (at least that's what the error messages tell me). Running everything in gitlab ci.

**Comment by BlueWinds** [comment]
It would still be helpful if you could put together a reproducible example; perhaps a public github repo demonstrating your problem. 

One easy way to do that is with a fork of https://github.com/cypress-io/cypress-test-tiny, and then include the docker command you're using either in a script or in a comment here.

**Comment by gab1018** [comment]
Hi Just checking if you got this resolved. Im encountering this for my test. Locally test runs fine. I have an application build in react and created cypress script (currently) login using web form which eventually fire up Post api request(XHR). THis gets aborted in Azure pipeline running in docker image. I tried to do a cy.request post method for same api end point and it works fine so api works fine. Im not jsut sure on the difference between actual browser call and the cy.request as cy.request post method works which isolate the issue on connection inside docker and getting response.

**Comment by sheinze** [comment]
Please help by supplying a reproducible example, unfortunatly my focus had to be shifted. It is still not solved for me.

**Comment by fusionshoes** [comment]
related
https://github.com/cypress-io/cypress/discussions/22254

**Comment by pureLifeWater101** [comment]
@sheinze you get it to work? I'm having the same issue

**Comment by sheinze** [comment]
No change for me since then. As I said, my project focus changed, so i don't have much time investigating further.
