### ISSUE TITLE
404 error code is received when run cypress tests in GitHub workflow

### ISSUE THREAD

**Issue by mbugaiov** [cypress-io/cypress#19487]
### Current behavior

I am seeing 404 error code for all cypress tests:
<img width="1580" alt="Screenshot 2021-12-28 at 18 38 49" src="https://user-images.githubusercontent.com/4127912/147587677-91eaa43d-ba01-4f8e-9113-f905aac78f9a.png">

### Test code to reproduce

Tested 2 cases in Github workflow:
      **- name: Cypress run
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: front
          record: true
          config: baseUrl=http://localhost:3000
          wait-on-timeout: 120**

      **- name: Test Cypress
        run: |
          npm install cypress --save-dev
          ./node_modules/.bin/cypress run --config baseUrl=http://localhost:3000/
        working-directory: front**

In both cases, received error code 404
When I try to test same flow in Jenkins ( run under ubuntu in AWS ) or locally ( Mac ) - Cypress works fine with local build of the application. Checked default port '3000' and custom '55555'. In all cases all is fine.

### Cypress Version

Cypress package version: 9.1.0 Cypress binary version: 9.1.0 Electron version: 15.2.0 Bundled Node version: 16.5.0

**Comment by MuckT** [comment]
@mbugaiov are you able to share your `.yaml` / `.yml` file for Github Actions?

Your server might not be fully started prior to launching Cypress. I've followed [this example](https://github.com/cypress-io/github-action#wait-on) in the past without issues using GitHub Actions.

**Comment by mbugaiov** [comment]
`jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'
      - name: Install dependencies
        run: |
          npm install
          npm install jest-junit
      - name: Run Application
        run: |
          echo APP_VERSION=dev.777 >> .env.dev
          cp .env.dev .env
          nohup npm run dev > application.txt 2>&1 &
      - name: Check all is good
        run: |
              ls -la
              pwd
              sleep 10
              ls -la
              curl http://localhost:3000/
              echo "Request to the local server DONE"
              cat application.txt
              ps axf
              netstat -tulpn
              npm run test:unit -- --coverage --collectCoverageFrom=src/** --reporters="jest-junit"
#      - name: Test Cypress without GitHub actions
#        run: |
#          npm install cypress --save-dev
#          netstat -tulpn
#          ls -la
#          pwd
#          ./node_modules/.bin/cypress run --config baseUrl=http://localhost:3000/ --record --key $C_KEY
#        working-directory: front

      - name: Setup npm package
        run: npm init -y && npm install
        working-directory: front
      - name: Check all is good
        run: |
              ls -la
              pwd
              ls -la front
      - name: Cypress run
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: front
          record: true
          config: baseUrl=http://localhost:3000
          wait-on-timeout: 120
        env:
          # pass the Dashboard record key as an environment variable
          # Request to set using secrets.
          CYPRESS_RECORD_KEY: $C_KEY`

**Comment by mbugaiov** [comment]
@MuckT posted .yaml file above. Thanks for help in advance!

**Comment by MuckT** [comment]
@mbugaiov it looks like you're not staring your server in the Cypress action try the following:

```
      - name: Cypress run
        uses: cypress-io/github-action@v2.11.7
        with:
          start: <insert local start command>
          wait-on: http://localhost:3000
          working-directory: front
          record: true
          config: baseUrl=http://localhost:3000
          wait-on-timeout: 120
```

**Comment by belwalshubham** [comment]
hey @mbugaiov @MuckT   I also get the same error when I run Cypress in github.

in package. json I have this code.
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt build && nuxt preview"
  },
  ```
and In YML file 
``` steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: install npm
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true
 ```
If instead of using npm run dev, I run npm run preview, it works fine and Cypress runs successfully, but it does not generate a code coverage report. A code coverage report can only be generated when I use npm run dev, but it gives a 404 error.

![cypress error](https://user-images.githubusercontent.com/61574835/211468616-1756fb32-5c4f-4bc7-ae84-6fbda9afa95e.PNG)
