### ISSUE TITLE
cy.request failed with  timed out waiting 30000ms for a response from your server

### ISSUE THREAD

**Issue by quyenntn** [cypress-io/cypress#19484]
### Current behavior

I implemented cy.request for a REST api call and got this error even though this is a free REST API which is successful all the time and I can call  it successfully with Postman from my local machine

I used to get this error with older version of NodeJs and cypress then I attempted to upgrade both to the latest version. At the first time, it works properly and then when I restarted my laptop, the same error returned til now.

I am using NodeJs 16.13.1 and below is my package.json

>  "devDependencies": {
    "cypress": "^8.7.0",
    "cypress-mochawesome-reporter": "^2.3.0",
    "mysql2": "^2.3.0"
  },
  "dependencies": {
    "faker": "^5.5.3",
    "mocha": "^9.1.3",
    "randexp": "^0.4.0"
  }

> cy.request() timed out waiting 30000ms for a response from your server.
> 
> The request we sent was:
> 
> Method: POST
> URL: https://reqres.in/api/users
> 
> No response was received within the timeout.Learn more
> cypress/integration/test/test.js:4:12
>   2 |     it('REST api', () => {
>   3 |         let rdNum = faker.random.number({ min: 1000000, max: 9999999});
> > 4 |         cy.request({
>     |            ^
>   5 |                 method: 'POST',
>   6 |                 url: `https://reqres.in/api/users`,
>   7 |                 failOnStatusCode: false, 
> View stack trace
>  Print to console
>     at <unknown> (http://localhost:49533/__cypress/runner/cypress_runner.js:157357:79)
> From previous event:
>     at Context.request (http://localhost:49533/__cypress/runner/cypress_runner.js:157356:16)
> From Your Spec Code:
>     at Context.eval (webpack:///./cypress/integration/test/test.js:4:12)

![image](https://user-images.githubusercontent.com/89009560/147449956-88dfdc69-46be-402f-ad39-f3e1f9412d29.png)

### Desired behavior

Fix to make cy.request sucessful and stable

### Test code to reproduce

const faker = require('faker');
    it('REST api', () => {
        let rdNum = faker.random.number({ min: 1000000, max: 9999999});
        cy.request({
                method: 'POST',
                url: `https://reqres.in/api/users`,
                failOnStatusCode: false,
                body: {
                    "header": {
                        "Content-Type": "application/json"
                      },
                    "payload": {
                        "name": "prinf thompson " + rdNum,
                        "job": "doctor"
                    }

                }
        }).then((response) => {
            expect(response.status).to.be.equal(201);

        })
    })

### Cypress Version

8.7.0

**Comment by sainthkh** [comment]
I tested with the code below, but failed to reproduce it with 9.2.0. 

```js
// const faker = require('faker')

it('REST api', () => {
  let rdNum = 1000012 // faker.random.number({ min: 1000000, max: 9999999 })

  cy.request({
    method: 'POST',
    url: 'https://reqres.in/api/users',
    failOnStatusCode: false,
    body: {
      'header': {
        'Content-Type': 'application/json',
      },
      'payload': {
        'name': `prinf thompson ${ rdNum}`,
        'job': 'doctor',
      },
    },
  }).then((response) => {
    expect(response.status).to.be.equal(201)
  })
})
```

Maybe updating Cypress can solve the problem.

**Comment by quyenntn** [comment]
Retested after version upgrade
Current behavior: same issue on the first run with test runner. After first failed run, I checked Rerun button, request is sent successfully after about 31~38s (pretty slow I think but at least it works)
However, this only works when I call the open API as in the code above. I tried with API requests of our own project, always failed with the same error message while I set up proxy properly ( assuming that due to the fact that I am able to download libs as normally)
Could you pls add some information of this error? In which case does it happen?

**Comment by sainthkh** [comment]
It might be the problem of proxy. [Please check this doc.](https://docs.cypress.io/guides/references/proxy-configuration)

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by OukhellouFst** [comment]
> It might be the problem of proxy. [Please check this doc.](https://docs.cypress.io/guides/references/proxy-configuration)

I have this issue due to a proxy, thank you for this info
