### ISSUE TITLE
aws-sdk issue when using cypress

### ISSUE THREAD

**Issue by estebanaragonc** [cypress-io/cypress#19489]
### Current behavior

I tried to use the cypress envs to capture AWS_SDK_LOAD_CONFIG and AWS_PROFILE.

I print them out:

![image](https://user-images.githubusercontent.com/55291655/147589795-72c155b8-6c04-4505-8410-d02b0fb5e7fd.png)

from inspector:

![image](https://user-images.githubusercontent.com/55291655/147589610-c3c24676-0b93-4233-b64e-a6dbe1f5c16e.png)

from config

![image](https://user-images.githubusercontent.com/55291655/147591703-fe0d2afd-39d9-42c6-813e-dc0ebba82663.png)

But I'm still having the error: **CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1**

How to set that system env so cypress will take it?

thank you in advance

**Note**: I have tested the same JS function in another nightwatchJS script and it is working, the token is already generated in ./aws

### Desired behavior

AWS Working

### Test code to reproduce

-

### Cypress Version

9.2.0

**Comment by emilyrohrbough** [comment]
@estebanaragonc It's a bit unclear from you code snipped how you are attempting to access the AWS env from the cypress configurations to pull your Secret.

The `aws-sdk` will be looking for these in the OS-level environment variables. My best guess is that you are assume the `aws-sdk` will be able to pull the env values from the cypress configuration, however, the cypress envs are stored in Cypress to access within you tests, and are not storing as OS-level environment variables (see these [docs](https://docs.cypress.io/guides/guides/environment-variables)).

I recommend setting these before starting Cypress:
```
AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=saml yarn cypress
```

**Comment by emilyrohrbough** [comment]
@estebanaragonc Did you get a chance to try out my suggestion?

**Comment by estebanaragonc** [comment]
Hello @emilyrohrbough - no, I have tried everything without any success. The OS variables are not accessible through the runner (yarn cypress open) but when I hardcode the secret key like

```
var client = new aws.SecretsManager({
      region: region,
      accessKeyId: 'aaasd12123',
      secretAccessKey: 'adsasd1231'
      sessionToken: 'asdasd123123'
  });
```

I'm able to get the secrets but we do not want to hardcode that to the aws library we created. I'm still thinking of a solution to this.
