### ISSUE TITLE
Allow for "global logging" to be possible from Cypress events

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#1949]
### Current behavior:

Cyrrently, attempting to make a `cy.log` call either onBeforeLoad or on fail is not working. I need to output some metadata to test runner on each run so i can reconcile the test run with our Sentry integration in case there is a backend or JS error which is not being captured in the test runner.

These codes do not work 

```js
Cypress.on('window:before:load', win => {
  win.SentryReleaseVersion = (new Date()).toISOString() + randomString(5);
  console.log('Release Version', win.SentryReleaseVersion)
  cy.log('Release Version', win.SentryReleaseVersion);
});

Cypress.on('fail', () => {
  cy.window().then(win => {
    console.log('Release Version', win.SentryReleaseVersion)
    cy.log('Release Version', win.SentryReleaseVersion);
    Cypress.log({
      name: 'Test',
      message: win.SentryReleaseVersion
    })
  })
})
```

### Desired behavior:

I would like a clear path to accomplish the above use case without writing a `beforeEach` for every suite in the app.

### Versions

3.0.1

**Comment by brian-mann** [comment]
Neither of those functions support writing async code, which `cy.*` commands are. However you can use the synchronous versions of both to do what you want to do.

Can you go into more detail about: 
  > I would like a clear path to accomplish the above use case without writing a beforeEach for every suite in the app.

You can write a simple root level `beforeHook` in your `supportFile` which will automatically run for all specs. You don't need to touch anything in your spec files for that to work. The support file is automatically imported before each spec.

Per your other questions: you can use `Cypress.log(...)` and you can use `cy.state('window')` to get synchronous access to the AUT's window.

- https://docs.cypress.io/api/cypress-api/cypress-log.html

**Comment by egucciar** [comment]
@brian-mann where can i find the docs for the root level before? I have not seen the capability yet.

Let me try `cy.state` and `Cypress.log` in the `fail` event and see if it works.

**Comment by egucciar** [comment]
@brian-mann trying this code passes the test & then has an indefinite loading graphic on what im trying to do :(

![image](https://user-images.githubusercontent.com/2848185/41421176-27ed743a-6fc4-11e8-8909-515e7b93152a.png)

```
Cypress.on('fail', () => {
  const window = cy.state('window');
  Cypress.log({
    name: 'Version:',
    message: window.moveiqSentryReleaseVersion
  })
})
```

**Comment by egucciar** [comment]
@brian-mann ok i understand - you can use `beforeEach` and `afterEach` outside of a describe block. TIL.


This is working for me:

```
afterEach(() => {
  const window = cy.state('window');
  cy.log('Version:', window.moveiqSentryReleaseVersion)
})
```

**Comment by jennifer-shehane** [comment]
Doc on global hooks in support file: https://on.cypress.io/writing-and-organizing-tests#Support-file

**Comment by brian-mann** [comment]
@egucciar this is a feature as part of `mocha` so we don't really go into a lot of detail since it's not us adding anything here.

I think this is an FAQ question too: @jennifer-shehane / @ValerieThoma if it's not, it should be, possibly a recipe as well.

https://mochajs.org/#root-level-hooks

**Comment by egucciar** [comment]
@ValerieThoma @jennifer-shehane @brian-mann 

wil the `afterEach` run before the error screenshot occurs? the reasoning behind all of this is i want to output a uniquely identifying string to the Cypress console when a test fails. That way, if the test fails due to an exception or error thrown, i can cross-match it to Sentry.

**Comment by jennifer-shehane** [comment]
I've added Sentry to the list of integrations we're considering in our integrations issue: https://github.com/cypress-io/cypress/issues/981

**Comment by egucciar** [comment]
Neat! For now I'm beforeEaching the version instead and can reference the video for more details. Sentry and other integrations out of the box would be awesome. We personally use Segment to streamline our use of Integration platforms , and are happy with the result

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
