### ISSUE TITLE
`npx cypress cache list` command is downloading latest Cypress version

### ISSUE THREAD

**Issue by bennymeade** [cypress-io/cypress#19507]
### Current behavior

Visiting Cypress path (Mac: **/Users/me/Library/Caches/Cypress**) for list of local installed versions I see version `v8.5.0`:

![image](https://user-images.githubusercontent.com/1033474/147851641-490a4429-9d9c-4dc2-8d95-1a4dfd8f1667.png)

Then run `npx cypress cache list`.

This results in downloading the latest Cypress version:

![image](https://user-images.githubusercontent.com/1033474/147851688-69c2d3be-45aa-4803-8b53-a85065ebb3e2.png)

![image](https://user-images.githubusercontent.com/1033474/147851696-b794a196-b86a-4de9-b99f-57da861ffac2.png)

### Desired behavior

I expect to only receive info on the versions I have already installed.

### Test code to reproduce

* Do not have latest Cypress version installed.
* `npx cypress cache list` or `npx cypress cache list --size`

### Cypress Version

Not latest

**Comment by mjhenkes** [comment]
@bennymeade, I'm unable to reproduce this issue. I removed cypress 9.2.0, installed cypress 8.5.0 and listed the cache, but cypress 9.2.0 wasn't installed.

![Screen Shot 2022-01-04 at 3 13 38 PM](https://user-images.githubusercontent.com/1588747/148124904-31b9b7d9-3502-4418-aaab-8a12d3671226.png)
![Screen Shot 2022-01-04 at 3 14 10 PM](https://user-images.githubusercontent.com/1588747/148124886-79e88a61-c20d-46de-be41-b9a49f4f86c0.png)
![Screen Shot 2022-01-04 at 3 15 23 PM](https://user-images.githubusercontent.com/1588747/148124877-c9f28e52-3aa6-4b0f-b0d2-3f61347fe7e3.png)

**Comment by bennymeade** [comment]
Thanks for checking @mjhenkes I retested my tests on a new clean repo and the error doesn't occur. Might have been something related to the large mono repo we work in. I'm closing this as 'not a bug'.
