### ISSUE TITLE
TypeScript: syntax error on type annotation

### ISSUE THREAD

**Issue by SeriousM** [cypress-io/cypress#1950]
### Current behavior:

```
C:\dev\CypressDockerTester\src\cypress\integration\portal-spec.ts:14
    cy.fixture('usersData.json').then((usersData:any) => {
                                                ^
ParseError: Unexpected token
```

### Desired behavior:

Type annotation works as expected

### Steps to reproduce:

* Use typescript [as described](https://docs.cypress.io/guides/tooling/typescript-support.html)
* write spec in typescript and use type annotation

### Versions

Cypress: 3.0.1

**Comment by jennifer-shehane** [comment]
Yeah, you will need to transpile Typescript tests using a preprocessor like one of the examples. https://on.cypress.io/typescript-support#Examples

This is also not very well documented, since it's specific to the preprocessor you would like to set up for you project. We'd love to make this more intuitive.

**Comment by jennifer-shehane** [comment]
I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document TypeScript transpiling here: https://github.com/cypress-io/cypress-documentation/issues/704.

**Comment by SeriousM** [comment]
Thank you Jennifer. Why do I need to transpile my ts files at all? The specs are executed without any issues till now and the files are named *.ts

**Comment by jennifer-shehane** [comment]
By default Cypress handles normal JS, CoffeeScript and ES6 using babel and then uses browserify to package it for the browser, so we just don't automatically handle TypeScript by default. https://on.cypress.io/plugins-guide#Preprocessors

I'm honestly not sure why we don't automatically handle .ts files. @bahmutov @brian-mann ?

**Comment by brian-mann** [comment]
I opened a proposal for this and we talked about it at our team meeting last week: https://github.com/cypress-io/cypress/issues/1859

Nobody provided any actionable feedback or opinions and it requires consideration and configuration that is different from the other tools.

**Comment by jennifer-shehane** [comment]
There is is! I thought this was an issue, but searching skills failed on this one.

**Comment by jennifer-shehane** [comment]
Closing. Please see #1859 for comments and updates on better handling TS files.
