### ISSUE TITLE
cy.screenshot limits the screenshot to 1280x720

### ISSUE THREAD

**Issue by ickata** [cypress-io/cypress#19505]
### Current behavior

If I resize the viewport to something larger than 1280w or 720h, e.g. 1440x1400, I see that in the GUI it is properly resized; then, if I take a screenshot, the screenshot is limited to the maximum width of 1280px and maximum height of 720px.

### Desired behavior

The taken screenshot must be as big as the current viewport is.

### Test code to reproduce

cy.viewport(1440, 1400);
cy.screenshot();

### Cypress Version

9.2.0

**Comment by gurudattgd04** [comment]
@ickata  Did you get a change to go through this  https://www.cypress.io/blog/2021/03/01/generate-high-resolution-videos-and-screenshots/

**Comment by ickata** [comment]
Hey @gurudattgd04 ,

Many thanks for posting this. I didn't find it when searching, it worked like a charm.
