### ISSUE TITLE
Support  self hosted Gitlab instance

### ISSUE THREAD

**Issue by tibz7** [cypress-io/cypress#19519]
### What would you like?

Currently it seems only possible to create a dashboard for Gitlab PAaS, not the self hosted version. 

### Why is this needed?

It would be better it was accessible to everyone, my organization cannot use the dashboard.

**Comment by nalandial** [comment]
If you're referring to Cypress Cloud being able to integrate with a self hosted version of GitHub/GitLab: that feature is currently in development.

**Comment by tibz7** [comment]
I'm refering to this dashboard,  https://www.cypress.io/dashboard  where it is not possible to add a selfhosted Gitlab instance, only gitlab.com

**Comment by nalandial** [comment]
Yes -- integration with self hosted instances of GitHub/GitLab is currently under development for the dashboard.

**Comment by nalandial** [comment]
@tibz7 This is now officially supported. Closing this ticket.
