### ISSUE TITLE
Cypress Dashboard run records are not ending when canceled in command line

### ISSUE THREAD

**Issue by Nate-Watts** [cypress-io/cypress#1952]
### Current behavior:
When terminating a run that is being recorded from the command line the test runner and the dashboard display it as still running.
![image](https://user-images.githubusercontent.com/38437438/41432095-35ad4c22-6fd2-11e8-8cb2-004019040ce4.png)

### Desired behavior:
To have the runs display as canceled, stopped, or terminated when they are terminated from the command line.

### Steps to reproduce:
Begin a test record of a test suite and terminate it before it has completed.

### Versions
Versions show in screenshot
Cypress 3.0.1

**Comment by Nate-Watts** [comment]
Related to this issue that was closed. https://github.com/cypress-io/cypress/issues/1891

**Comment by EirikBirkeland** [comment]
I was just getting questions about this one  ... "4 days ago" :)
![image](https://user-images.githubusercontent.com/12223584/41438040-645e2b8c-7026-11e8-95ed-8f7f78b2e771.png)

I suggest indicating in the Dashboard that incomplete data were received by add a "Connection timeout" or "Disconnected" icon.

**Comment by EirikBirkeland** [comment]
@Nate-Watts I think maybe we just have to wait for 3.0.2:
![image](https://user-images.githubusercontent.com/12223584/41438568-f55a7bbc-7027-11e8-8ecc-15f23f8f8a7b.png)

**Comment by brian-mann** [comment]
I fixed an issue related to this last week but it appears that I did not account for all of the scenarios. This is a problem specifically with our Dashboard service running a Cron job that cleans up timed out runs - and it's not doing it correctly.

I will close this issue when it it is indeed fixed.

**Comment by brian-mann** [comment]
This is fixed again.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by Muslyadin** [comment]
I am using version 3.1.3 and the problem repeats
![image](https://user-images.githubusercontent.com/42549826/49499718-e4ebe500-f87f-11e8-927d-71b33d1c8f79.png)

**Comment by jennifer-shehane** [comment]
@Muslyadin This can happen if the run in your CI had an error or timed out without throwing an exit code. Cypress cleans up these runs every 90 minutes - so the actual status will be reflected after that time. 

I understand this is not made very clear though, our team is working on a solution for cleaning runs quicker. https://github.com/cypress-io/cypress/issues/1691

**Comment by Muslyadin** [comment]
Yes, that is what happened. Thanks for explaining
