### ISSUE TITLE
Cannot instrument TypeScript test code

### ISSUE THREAD

**Issue by t1v1** [cypress-io/cypress#19530]
### Current behavior

I'm aiming to achieve 100% code coverage for [`thavma`](https://github.com/t1v1/thavma) but I'm unable to because of a few statements in my `lib/api/handle.ts` file that can't be covered through end-to-end integration tests:

![image](https://user-images.githubusercontent.com/93789775/147990925-72cc6bf0-bfc8-4948-b4da-e9110ed47e09.png)

So, to test those lines of code, I'm importing that file into a Cypress test and performing some unit tests (as recommended in [Cypress's documentation](https://docs.cypress.io/guides/tooling/code-coverage#E2E-and-unit-code-coverage)):

```typescript
// cypress/tests/api/handle.spec.ts
import { ServerResponse } from 'http';

import handle from 'lib/api/handle';

describe('Handle FX', () => {
  beforeEach(() => {
    const res = {
      setHeader: cy.stub().as('header'),
      statusCode: 500,
      end: cy.stub().as('end'),
    };
    Object.defineProperty(res, 'statusCode', {
      set: cy.stub().as('status'),
    });
    cy.wrap(res).as('res');
  });

  it('handles error objects', () => {
    cy.get('@res').then((res) => {
      handle(new Error('This is an error!'), res as unknown as ServerResponse);
      cy.get('@header').should('be.calledTwice');
      cy.get('@status').should('be.calledWithExactly', 500);
      cy.get('@end').should('be.calledOnce');
    });
  });

  it('handles error strings', () => {
    cy.get('@res').then((res) => {
      handle('This is an error string!', res as unknown as ServerResponse);
      cy.get('@header').should('be.calledTwice');
      cy.get('@status').should('be.calledWithExactly', 500);
      cy.get('@end').should('be.calledOnce');
    });
  });

  it('handles unknown errors', () => {
    cy.get('@res').then((res) => {
      handle(0, res as unknown as ServerResponse);
      cy.get('@header').should('be.calledTwice');
      cy.get('@status').should('be.calledWithExactly', 500);
      cy.get('@end').should('be.calledOnce');
    });
  });
});
```

Then, to include those unit tests in my end-to-end code coverage reports, I need to instrument my test code. So, I added this line to my plugins file:

```typescript
// cypress/plugins/index.ts
  on('file:preprocessor', require('@cypress/code-coverage/use-babelrc'));
```

This, however, caused the following error (because I'm guessing it wasn't made to support TypeScript... yet):

![image](https://user-images.githubusercontent.com/93789775/147991135-e072dd3e-bfbe-42d2-8c37-6a5cfafe8598.png)

Here's the error text itself (just in case it's hard to read in the screenshot above):

```
Error: Error running @cypress/browserify-preprocessor:

You are attempting to preprocess a TypeScript file, but do not have TypeScript configured. Pass the 'typescript' option to enable TypeScript support.

The file: /home/nchiang/repos/thavma/cypress/tests/join.spec.ts
    at throwError (/home/nchiang/repos/thavma/node_modules/@cypress/browserify-preprocessor/index.js:74:15)
    at Object.handler (/home/nchiang/repos/thavma/node_modules/@cypress/browserify-preprocessor/index.js:198:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Desired behavior

Cypress's custom `.babelrc` support should be able to compile and instrument TypeScript test files.

### Test code to reproduce

1. Clone https://github.com/t1v1/thavma.git
2. Either checkout to the `test` branch or add the following to `cypress/plugins/index.ts`:
```typescript
  on('file:preprocessor', require('@cypress/code-coverage/use-babelrc'));
```
3. Start the development server: `NODE_ENV=test yarn dev`
4. Start Cypress: `yarn cypress open` or just `yarn dev:cy`
5. Click on the "Run all tests with Firefox/Chrome/Electron"
6. See this error message:
```
You are attempting to preprocess a TypeScript file, but do not have TypeScript configured. Pass the 'typescript' option to enable TypeScript support.
```

### Cypress Version

```
Cypress package version: 9.2.0
Cypress binary version: 9.2.0
Electron version: 15.2.0
Bundled Node version: 16.5.0
```

**Comment by t1v1** [comment]
Related to cypress-io/code-coverage#518

**Comment by mjhenkes** [comment]
I see that you're using the browserify pre processor. Have you enabled typescript support for it? https://github.com/cypress-io/cypress-browserify-preprocessor#typescript
