### ISSUE TITLE
contains() not working with filter and RegExp

### ISSUE THREAD

**Issue by Maw-Jung** [cypress-io/cypress#19540]
### Current behavior

The **.contains()** command currently only works when split into **.get() and .contains()** with Regular Expression.

### Desired behavior

I'd like to use a single command to search for an element with a regular expression. The RegExp is needed to distinguish "edit & save" and "edit" f.e. without using an index. The single `.contains()` also works, when including the final html tag the text is within like so: `main .container p`

### Test code to reproduce

```js
it('on cypress website', () => {
    cy.visit('https://www.cypress.io/');
    cy.get('main .container').contains(new RegExp('^Cypress is the new standard in front-end testing that every developer and QA engineer needs.$', 'm'));
  });
```
works but this doesn't:
```js
it.only('on cypress', () => {
    cy.visit('https://www.cypress.io/');
    cy.contains('main .container', new RegExp('^Cypress is the new standard in front-end testing that every developer and QA engineer needs.$', 'm'));
  })
```

### Cypress Version

8.7.0

**Comment by mjhenkes** [comment]
@Maw-Jung, thanks for your reproducible code. I've been able to to recreate this.

additionally this test case works as expected

```js
  it('it succeeds with a string', () => {
    cy.visit('https://www.cypress.io/');
    cy.contains('main .container', 'Cypress is the new standard in front-end testing that every developer and QA engineer needs.');
  });
```

**Comment by sainthkh** [comment]
These 2 commands are not same. 

`cy.get('.selector').contains(/text/)` means to find elements that meets `/text/` that are under `.selector` elements. Because of that, it returns `<p>Cypress is...</p>` correctly. 

`cy.contains('.selector', /text/)` means to find elements that meets `/text/` that has `.selector` tag. There is no `main .container` that starts with `Cypress is` on the page. So, it throws an error. 

It's the intended behavior.

**Comment by Maw-Jung** [comment]
Thanks for your response @sainthkh !
From the .contains documentation i read that in order to achieve not getting the deepest element we have to pass the selector. In my example i passed the selector for the element i wanted to get, which is a .container. This container in my example is only specified by some text it contains deeper down the tree. This simplified, public example may have been missing my intention, sorry for that. Knowing now, that this is intended behavior, how do i accomplish what i've understood from the documentation to be possible this way?
Thanks,
Marcel

**Comment by sainthkh** [comment]
@Maw-Jung Sorry for the late reply. Can you give us a more specific example? Without the specific DOM tree you're using, it's hard for me to solve your problem. If it doesn't matter, adding an `id` or `data-cy` attribute to that element might solve the problem.

**Comment by Maw-Jung** [comment]
@sainthkh no worries, i wasn't in time, either. The problem occurs with the generated tree, which i have no control over. Thus i can only identify reoccuring elements by content further down the node. I'll try to add an simplified example:
`<ul>
    <li>
        <span>banana</span>
    </li>
    <li>
        <span>pineapple</span>
    <li>
</ul>
`
I hope this makes it a bit more clear, i need to grab the li-elements by identifying the correct one by it's content. This example clearly lacks all the boilerplate dom around the described nodes, but i think it works as an example. 
`cy.contains('ul li', new RegExp('^pineapple$', 'm'));`
What i want this to find is the element containing 'pineapple' within the subtree of 'ul li' to achieve a better performance with big trees. Thanks for your response, hope this makes it any clearer.
