### ISSUE TITLE
type('{enter}') does not fire click event

### ISSUE THREAD

**Issue by jamime** [cypress-io/cypress#19541]
### Current behavior

When the target element is a button `type('{enter}')` fires the events

- keydown
- keypress
- keyup

![image](https://user-images.githubusercontent.com/2328042/148062294-69cd75f1-df54-4cc6-bbba-ebe290560bad.png)
Note the first "click" is from activating the button.

### Desired behavior

When the target element is a button `type('{enter}')` should fire the events

- keydown
- keypress
- **click**
- keyup

![image](https://user-images.githubusercontent.com/2328042/148062390-ac8782fc-91c4-4a62-a4f0-1cd0c534944c.png)

Note the first "click" is from activating the button.

### Test code to reproduce

https://github.com/jamime/cypress-test-tiny

### Cypress Version

9.2.0

### Other

> If the key is the Enter or   key and the current focus is on a state-changing element, the default action MUST be to dispatch a click event, and a DOMActivate event if that event type is supported by the user agent (refer to § 3.5 Activation triggers and behavior for more details)

https://w3c.github.io/uievents/#event-type-keydown

Once the cypress test has failed, if you click "reset", then click the second button and press "Enter" you will see the correct output.

**Comment by mjhenkes** [comment]
@jamime, Thanks for the reproducible repo. I've confirmed this is an issue in 9.2.0
