### ISSUE TITLE
Unification: Support testing Cypress within Cypress

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#19547]
### What would you like?

We need the ability to write E2E tests that test running Cypress within Cypress. The strategy we are using for this is to namespace the child routes in such a way that they can be distinguished from the parent. At a minimum this can be set up in the cypress config, but a nice to have would be to automatically create appropriate namespaces for the child when we know we are testing Cypress in Cypress. Currently, there are a few road blocks within the Unification project that are hindering progress on this:

**Namespacing**
* General routes need to be namespaced
  * We will ensure that we are both utilizing the namespace on the client and factoring in the namespace in our route handling on the server
  * Currently the config is being retrieved via a call to the server. This will prevent the child Cypress instance config from being able to be loaded properly on the client since it doesn't know to namespace the API call yet. We will fix this by rendering the cypress config to the initial page server side in a global variable that can then be utilized client side to access the config.
* Websockets need to be namespaced
  * We will ensure that we are using the config.socketIoRoute as the path wherever we are creating a websocket
  * The proxied websockets from parent cypress to child cypress do not create an initial http connect event and thus the socket is not added to the allowed list for the child app server. Solution for this is TBD
* Graphql requests need to be namespaced

**Other Problems**
* Connecting to an already existing browser 
  * Since we already have a browser running when the child cypress server starts, we will need to set up a remote connection. We will do this by using CDPAutomation to attach to the existing browser instead of opening a new browser instance when we are in cypress in cypress. In order to facilitate this we are going to launch cypress in cypress tests with the environment variable set that specifies the remote debugging port. Also we are focused only on chrome

**Comment by baus** [comment]
@ryanthemanuel Do we need to break this down into subtasks?

**Comment by ryanthemanuel** [comment]
With https://github.com/cypress-io/cypress/pull/19602, the remaining work left to be done is:

* The proxied websockets from parent cypress to child cypress do not create an initial http connect event and thus the socket is not added to the allowed list for the child app server. Solution for this is TBD
* Graphql requests need to be namespaced

The first issue was determined to be a problem in Cypress itself and will be worked on separately. The second issue will be fixed with https://github.com/cypress-io/cypress/pull/19619

Closing this issue as all of the remaining work will be done separately.
