### ISSUE TITLE
Tests fail on [Cannot create property 'Symbol(ERR_PREPARED_FOR_SERIALIZATION)' on boolean 'true']

### ISSUE THREAD

**Issue by Arcturus5404** [cypress-io/cypress#19561]
### Current behavior

Currently some of our tests sometimes fail on 
`Cannot create property 'Symbol(ERR_PREPARED_FOR_SERIALIZATION)' on boolean 'true'`

It seems like the error itself is swallowed somehow? or there is no error to begin with and there is something wrong with the error parsing?

### Desired behavior

No to fail the tests, and log a helpful error message

### Test code to reproduce

No idea how to reproduce this. We have cypress dashboard; those are the tests that are flaky right now.

### Cypress Version

9.2.0

**Comment by mjhenkes** [comment]
It's likely that through some method the boolean `true` is being being thrown which causes our error serialization to fail itself [here](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/error_utils.ts#L53)

We could handle boolean errors similar to how we handle strings here, but it's still unclear where and how 'true' is being thrown

**Comment by rafinskipg** [comment]
i'm getting this error too, and i don't understand why

**Comment by Arcturus5404** [comment]
I think it is because some Promise is rejecting with value `true` which is uncaught
