### ISSUE TITLE
Single-machine parallel execution occasionally results in "not a function" errors

### ISSUE THREAD

**Issue by j1000** [cypress-io/cypress#19565]
### Current behavior

I have a weird intermittent failure that only happens when I run the tests in parallel on my local machine (using a Powershell script). Out of ~200 tests about 5 will fail, and it's never the same tests. The error is always "__ is not a function" where __ is one of my Cypress custom commands. It seems as if there's a race condition happening in Cypress's code, and the spec file is loading before /support/index.js has been loaded. (Maybe there's a file permission issue due to all the threads accessing the same stuff?)

![image](https://user-images.githubusercontent.com/10520969/148243859-c4c73ff2-1c99-4875-9bdd-2590bab8e47c.png)

### Desired behavior

Ideally the bundling would work consistently and /support/index.js will always be properly loaded for each spec file. **But** alternatively it would be nice if test reruns reloaded (and rebundled) the spec file entirely so that the test doesn't fail upon rerun.

### Test code to reproduce

I wish it were simple to reproduce. You need any large set of tests running in parallel locally. I am on a Windows 10 workstation. I'll give you my Powershell script in case that helps.

```
$processes = 5

# Provide an argument when invoking this script to target a specific environment
$bUrl = $args[0]
if ($bUrl) { $hostUrl = "baseUrl=$bUrl" } else { $hostUrl = "baseUrl=https://www.somewebsite.com" }

Write-Host "Running tests on $hostUrl"

$epoch = Get-Date -UFormat %s

$script = { param($pEpoch, $pHostUrl) cmd /c "npx cypress run --spec './cypress/integration/!(debug)/**' --record --key insertkeyhere123456789 --parallel --ci-build-id $pEpoch --browser chrome --config video=false,$pHostUrl" }

$loc = Get-Location

for ($i = 1; $i -le $processes; $i++) {
  Start-Job -ScriptBlock $script -WorkingDirectory $loc -ArgumentList $epoch, $hostUrl -Name "cypress"
}

Get-Job | Wait-Job

Remove-Job *
```

### Cypress Version

9.2.0

**Comment by mjhenkes** [comment]
Hi @j1000, we currently don't support running multiple instances of cypress in the same project on the same machine at the same time. It can cause weird interactions (as you've run into). You could take a look at splitting this up to run in several docker containers in parallel, but i can't promise it's a faster solution. Sorry.

**Comment by j1000** [comment]
Gotcha, thanks. This is a shame, because it used to work without issue. I'm not sure if Cypress changed or if my tests changed.

**Comment by j1000** [comment]
@mjhenkes I think I have a viable workaround for this. If you launch the tests with the configuration value `numTestsKeptInMemory=0` the errors no longer happen. I'll continue monitoring this to make sure it's not a false correlation.

**Comment by j1000** [comment]
> @mjhenkes I think I have a viable workaround for this. If you launch the tests with the configuration value `numTestsKeptInMemory=0` the errors no longer happen. I'll continue monitoring this to make sure it's not a false correlation.

After some time using this workaround, it's not a cure but it seems to make a huge difference. I was getting 3-6 "is not a function" failures with every run before; now I'm getting 0-1. Usually 0. I'll learn Docker eventually but this works for now ;)

**Comment by actuallymentor** [comment]
> @mjhenkes I think I have a viable workaround for this. If you launch the tests with the configuration value `numTestsKeptInMemory=0` the errors no longer happen. I'll continue monitoring this to make sure it's not a false correlation.

Thank you very much for this. Makes my tests far less flaky too.
