### ISSUE TITLE
A modal which is supposed to be visible after clicking an element is not opening up after the click

### ISSUE THREAD

**Issue by DomyNithanth** [cypress-io/cypress#19563]
### Current behavior

I am trying to validate a popup modal that will appear after clicking on an element. During the test run, the click command is successfully completed but the modal **is not visible.**

**I stopped running the test and then tried to click the element manually(Inside Test Runner) - To my surprise, even now the modal is not opened up!!**. 

Tried click({ force: true }) and also all the element locators are correct.

### Desired behavior

In this situation, cypress should be able to open up the modal inside the test runner if the user does the click action via Automation script or manually.

### Test code to reproduce

//code

  cy.get(locator for opening up the modal).click() // click is done 
  cy.get(**div locator** for modal).should('be.visible') // modal is not visible 

### Cypress Version

9.2.0

### Other

For now, I have found two places where the modal open issue is observed and the tag for both modals(which is not visible inside cypress test runner) is the same and **it's a div tag.**

![image](https://user-images.githubusercontent.com/95854242/148224190-38a2be50-2e35-4bd1-84d3-ad35480ecac6.png)

**Comment by mjhenkes** [comment]
Hey @DomyNithanth, Could you create a small reproducible example. It's going to be hard for us to debug this without having any context to the implementation of your modal.

**Comment by DomyNithanth** [comment]
Hi @mjhenkes,

I think this issue is because of Cypress limitation as to its running all its Testcases within an Iframe. 
I added the below code on visit to URL and its working fine now:

`cy.visit(config.pageUrl, {
  onBeforeLoad: (win) => {
    // Let the child think it runs in the parent
    win["parent"] = win;
  }
});`

I referred it here:
[https://www.eliostruyf.com/tests-running-iframe-cypress-e2e-tests/](url)

And do you have nay other solution(s) for this issue?
