### ISSUE TITLE
API requests are not always ordered in the order they were made

### ISSUE THREAD

**Issue by ldabiralai** [cypress-io/cypress#19570]
### Current behavior

When expecting multiple API calls to the same intercepted route, they are sometimes not ordered in the order they were made by the application.

In the image below we make 3 api requests, all to `/api`. The first has a payload of `{ body: "first" }`, the second `{ body: "second" }` and third is `{ body: "third" }`.

![image](https://user-images.githubusercontent.com/1711610/148261903-8aa89f95-2e31-4e8c-9a5c-15164b82dafd.png)

In the reproducable example I `console.log` out the result of the calls in the order that `spread` gives to the callback: 

![image](https://user-images.githubusercontent.com/1711610/148262508-22788269-d5d9-4b9d-8f5a-2d2bb14ee0ab.png)

As you can see they come through in the incorrect order, with the second & third api call being the wrong way around.

Here's a video that demonstrates this behaviour (this time the first and second calls are the wrong way around).

https://user-images.githubusercontent.com/1711610/148263731-9bcff15b-0376-48f8-903f-bf37ae23e720.mp4

### Desired behavior

I believe that `wait` should preserve the order in which the API calls were made by the application.

### Test code to reproduce

https://github.com/ldabiralai/cypress-wait-spread-bug

### Cypress Version

9.2.0

**Comment by mjhenkes** [comment]
@ldabiralai, Thanks for the reproducible project. I've been able to reproduce this myself.
