### ISSUE TITLE
cypress.run() should return test failure reason when marking tests as failed

### ISSUE THREAD

**Issue by MichaelHindley** [cypress-io/cypress#1957]
### Current behavior:
Currently, when using `cypress.run()` the returned object does not contain any information about why a test failed when a failure has occurred. 

### Desired behavior:
Consider this screenshot:
![image](https://user-images.githubusercontent.com/1016639/41455239-b6fb5170-707c-11e8-9b22-efd1027b3d05.png)

There is no way to know what exactly has failed without watching the entire produced video, where we can see that an ASSERT is not passing.

![image](https://user-images.githubusercontent.com/1016639/41455690-47cd607a-707e-11e8-87a2-e6073f18947f.png)

I think it would greatly ease to build status reports if we knew what has failed in the data returned from `cypress.run()`. Currently, it returns `runs.tests[*].state` as `failed`.
I suggest there should be a key like `run.tests.[*].failure` that holds the actual reason why it failed.

### Versions
3.0.1

**Comment by brian-mann** [comment]
It does. It includes the `error` property amongst other things.

**Comment by MichaelHindley** [comment]
@brian-mann the `error` property shows `"error": "Maximum call stack size exceeded",` and I've never seen it *not* do that so I thought it's what happens by default internally on failure, is that a bug perhaps?

`stack` below
```
"RangeError: Maximum call stack size exceeded\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144562:22)\n    at _hasBinary  
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary  
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary  
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary  
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary  
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary  
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary   
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)\n    at _hasBinary 
 (https://url/__cypress/runner/cypress_runner.js:144586:63)",

```

The assertion that triggers the failure is quite simple:
`expect($input).not.be.disabled`

Should I file a new bug report?

**Comment by MichaelHindley** [comment]
I've created a repro case for the above mentioned bug in #1958
