### ISSUE TITLE
In consistent behavior of before hook in support file, when ran in head and headless mode.

### ISSUE THREAD

**Issue by appanasantosh** [cypress-io/cypress#19587]
### Current behavior

I am doing login in before hook of support file. So that login is done only once through out multiple spec files. When i run the tests in test runner by clicking run all specs, it is working fine and login is executed once. But when i run the tests in headless, then the hook is executed in each spec file.

### Desired behavior

It should behave same in both the cases.

### Test code to reproduce

login command call in before hook of support file.

### Cypress Version

8.7.0

### Other

I cannot use before:run event plugin for calling my custom cypress login command as we cannot use cy commands in plugin. Is there any way to handle the single time login across multiple spec files?

**Comment by mjhenkes** [comment]
@appanasantosh, could you provide an example of how you're setting up your hook in your support file?
