### ISSUE TITLE
Expecting element to be disabled results in maximum call stack size error

### ISSUE THREAD

**Issue by MichaelHindley** [cypress-io/cypress#1958]
### Current behavior:
When expecting something to not be disabled(or quite possibly when expecting on jqueryfied objects, or other assertions), the `error` field is set to `Maximum call stack size exceeded`

[Test repo](https://github.com/MichaelHindley/cypress-stack-test)

### Desired behavior:
It should show the failed assertion with a nice human readable error.

### Steps to reproduce:
git clone git@github.com:MichaelHindley/cypress-stack-test.git
cd cypress-stack-test
yarn && yarn dev
visit localhost:3001

![image](https://user-images.githubusercontent.com/1016639/41460289-80348b24-708c-11e8-84d0-45e0389602ec.png)

### Versions

3.0.1

**Comment by jennifer-shehane** [comment]
I'm not experiencing this with the tests you have posted in your repo. 

<img width="1167" alt="screen shot 2018-06-15 at 12 23 33 pm" src="https://user-images.githubusercontent.com/1271364/41478943-8e5ff87c-7097-11e8-8d5d-08ed051c37aa.png">

We also generally do not recommend testing sites outside of your control [for a variety of reasons](https://on.cypress.io/best-practices#Visiting-external-sites)

**Comment by MichaelHindley** [comment]
are you looking at the JSON returned by cypress.run()?

I've added a Docker runnable example that runs on node 8 jessie, the same error is present there.

![image](https://user-images.githubusercontent.com/1016639/41524778-df34e11a-72de-11e8-84c9-1fd0706e5d86.png)

**Comment by MichaelHindley** [comment]
So I've added a Docker runnable example in the test repo to ensure that same environment can be used to debug, and a case where it runs against a local index.html that has just an button.

I haven't been able to figure out a common denominator though, in a bare-bones index.html, everything works as expected, but it seems that both we internally in our apps and google.com do something in the DOM that makes Cypress error out with call stack limit when a expectation fails it's check.


![image](https://user-images.githubusercontent.com/1016639/41527263-dc379c5c-72e6-11e8-91dd-d999a0e4c5ce.png)

**Comment by flotwig** [comment]
I was able to reproduce the call stack error, adding #4407 seems to fix it and allow the test to run as expected:

![image](https://user-images.githubusercontent.com/1151760/59113072-5d585f00-8912-11e9-8794-a595773a9f77.png)
