### ISSUE TITLE
Last element is only taken from Cypress._.each() during assertion

### ISSUE THREAD

**Issue by ssv-w32** [cypress-io/cypress#19588]
### Current behavior

Last element is only taken from Cypress._.each() during assertion.

When running tests I only get the last element checked for 7 times (count of objects in array). Console output is the following:

```
get .element-1
get .element-2
get .element-3
get .element-4
get .element-5
get .element-6
get .element-7

assert expected [ <div.element-7>, 1 more... ] to be visible
assert expected [ <div.element-7>, 1 more... ] to be visible
assert expected [ <div.element-7>, 1 more... ] to be visible
assert expected [ <div.element-7>, 1 more... ] to be visible
assert expected [ <div.element-7>, 1 more... ] to be visible
assert expected [ <div.element-7>, 1 more... ] to be visible
assert expected [ <div.element-7>, 1 more... ] to be visible
```

### Desired behavior

Loop through all elements in list, not only the last one.

### Test code to reproduce

```
export class TestClass {
  get testElementFirst() {
    return cy.get(".element-1")
  }

  get testElementSecond() {
    return cy.get(".element-2")
  }

  get testElementThird() {
    return cy.get(".element-3")
  }

  get testElementFourth() {
    return cy.get(".element-4")
  }

  get testElementFifth() {
    return cy.get(".element-5")
  }

  get testElementSixth() {
    return cy.get(".element-6")
  }

  get testElementSeventh() {
    return cy.get(".element-7")
  }

  verifyVisibility() {
    const visibilityElements = [
      this.testElementFirst,
      this.testElementSecond,
      this.testElementThird,
      this.testElementFourth,
      this.testElementFifth,
      this.testElementSixth,
      this.testElementSeventh
    ]

    Cypress._.each(visibilityElements, element => {
      element.should('be.visible')
    })
  }

}

```

### Cypress Version

9.0.0

**Comment by sainthkh** [comment]
I checked the code and it's the intended behavior. 

### Problem.

`cy.get()` command doesn't return the element. All it does is registering what to do to Cypress. And those commands are run in batch later. 

In the array above:

```js
const visibilityElements = [
      this.testElementFirst,
      this.testElementSecond,
      this.testElementThird,
      this.testElementFourth,
      this.testElementFifth,
      this.testElementSixth,
      this.testElementSeventh
    ]
```

`cy.get()` commands are registered at once. 

And in the `Cypress._.each` below, assertions are called. 

That's why the code is only checking the last element. 


### Solution

I don't know why we need getters in this code. I guess this might be the simplification of the long and complicated code. But if it's possible, remove `Cypress._.each()` like below:

```js
it('pass', () => {
  cy.visit('fixtures/a.html')

  cy.get('.element-1').should('have.text', '1')
  cy.get('.element-2').should('have.text', '2')
  cy.get('.element-3').should('have.text', '3')
})
```

Or if you really need to use a function-like way to solve your problem. Remove getter and call the function directly like below:

```js
class TestClass {
  testElementFirst () {
    return cy.get('.element-1')
  }

  testElementSecond () {
    return cy.get('.element-2')
  }

  testElementThird () {
    return cy.get('.element-3')
  }

  verifyVisibility () {
    const visibilityElements = [
      this.testElementFirst,
      this.testElementSecond,
      this.testElementThird,
    ]

    Cypress._.each(visibilityElements, (element, i) => {
      element().should('have.text', `${i + 1}`)
    })
  }
}
```

**Comment by ssv-w32** [comment]
@sainthkh, thank you for response!

Solution you've provided works good in my case, however for consistency I've made decision to leave getters in my code for all the locators I have and use:
`
it('pass', () => {
  cy.visit('fixtures/a.html')

  cy.get('.element-1').should('have.text', '1')
  cy.get('.element-2').should('have.text', '2')
  cy.get('.element-3').should('have.text', '3')
})
`

This is quite an overhead but still refactoring of all locators will cost more in this case, since they all wrapped in getters.
