### ISSUE TITLE
Test Runner exits or stops running when executing the testcases in cypress version 8.7 or higher

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#19594]
### Current behavior

Everything was fine till Cypress 8.3.1 
But when we upgraded cypress 8.3.1 to 8.7.0 or higher it has tremendously slowed down the execution as well as it behaves flaky when running all testcases together .

Test runner either breaks/exits without any warning or error message when running headlessly

and when running with debug mode (with header in chrome/electron) it goes in Not Responding state and never stables.

If we execute the same all testcases in 8.3.1 it works like a charm. No Problem or breakage or crash
Even if we execute the testcase individually in 8.7.0 or higher it will work but if we execute in bunch (all together ) its not working perfectly. 

### Desired behavior

All the testcases should work and give us the desired results (either fail or pass) instead of Exiting without any warning or error

### Test code to reproduce

Try to execute more than 20 testcases in latest version of the Cypress which has DB connection and atleast 4-5 server API calls 

### Cypress Version

8.7.0 or higher

**Comment by testingJava2** [comment]
+1 for this issue.

When a lot of tests are passed to the `Cypress Test Runner`, when hitting around 1000 seconds of run, the browser windows (Electron in my case) will freeze and nothing will work anymore (not even the stop button).

The Runner Browser need to be closed and everything needs to be started again.
