### ISSUE TITLE
Test runner stopped loading all of the sudden - forever stuck in spinner screen

### ISSUE THREAD

**Issue by feliperaul** [cypress-io/cypress#19599]
### Current behavior

Without any updates to the project code, the test runner is getting stuck in the spinner screen loading forever:

![image](https://user-images.githubusercontent.com/743879/148436985-e9579654-4515-482b-b7f8-6e948f72147a.png)

### Desired behavior

It should load

### Test code to reproduce

Can't reproduce

### Cypress Version

9.2.0

### Other

Already tried:

- Upgrading node from 17.0.1  to 17.3.0
- `rm -rf node_modules`
- `yarn cypress cache clear` && `yarn cypress install`

I noticed terminal outputing `/usr/local/Cellar/node/17.3.0/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS`, which I didn't know if it did before; starting cypress with DEBUG mode doesn't produce any error message whatsoever.

MacOS Catalina 10.15.7

**Comment by feliperaul** [comment]
Just found this recent comment suggesting it's a problem with node 17:

https://github.com/cypress-io/cypress/issues/7027#issuecomment-997388311

**Comment by feliperaul** [comment]
Confirmed that downgrading to node 16 fixed it for me.

Steps for a quick fix if you're on Mac and used brew to install node.

`brew uninstall node`
`brew install node@16`

Brew will then alert you to run `echo 'export PATH="/usr/local/opt/node@16/bin:$PATH"' >> ~/.zshrc`, because you just installed a non-default version of `node`, and you should do that, *reopen your terminal window*, otherwise you'll start facing `node command not found` error messages.

`rm -rf node_modules`
`yarn`

**Comment by mschile** [comment]
Thanks @feliperaul. The issue you are seeing is related to #19320 and is being addressed in #19522.
