### ISSUE TITLE
key combinations

### ISSUE THREAD

**Issue by sarahgracesmith** [cypress-io/cypress#196]
**Description** 
Would be useful to allow typing key combinations for testing keyboard shortcuts (we have a shortcut ctrl-/ for example)

**Comment by brian-mann** [comment]
@chrisbreiding is working on this right now. You'll see this come out pretty soon (as in days).

**Comment by brian-mann** [comment]
Fixed in [`0.17.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0171-08312016).
