### ISSUE TITLE
npm cypress run task hangs when there are test retry attempts

### ISSUE THREAD

**Issue by clazette** [cypress-io/cypress#19603]
### Current behavior

npm cypress run tasks do not complete whenever there is a test retry attempt even when the retry attempt succeeds. This is causing issues with test automation, during the CI/CD pipeline's execution, in that the task never completes and, ultimately, the deployment process fails. Built-in retries are part of the benefit we get from using Cypress as you know. It seems odd that a successful retry attempt would cause the task to hang.

### Desired behavior

The npm cypress run task completes with exit code 0 even when there are test retries assuming the retries succeed.

### Test code to reproduce

Any test retry attempt will cause the issue to occur.

### Cypress Version

9.2.0

**Comment by clazette** [comment]
I really need some assistance here. Why would a successful retry prevent the task from completing with exit code 0?

![image](https://user-images.githubusercontent.com/1321806/148591257-0321a878-4a93-4420-a158-cf3a205d1c95.png)

**Comment by mjhenkes** [comment]
@clazette, I setup a simple test and was unable to recreate this issue locally.

With the following test and config the cypress run command exited with a zero

```js
describe('issue-19603', () => {

    let isTrue = false
    it('fails the first time', () => {
        setTimeout(() => {
            isTrue = true
        }, 10)
        expect(isTrue).to.be.true
    });
})
```

cypress.json config
```json
{
    "retries": {
        "runMode": 2,
        "openMode": 0
      }
}
```

Could you provide a reduced test case that recreates this issue?

**Comment by clazette** [comment]
@mjhenkes, I can try but it's every time there is a retry attempt, even when the subsequent attempt is successful, the process just doesn't exit. All the tests will pass but, without that exit code 0, TeamCity just hangs and ultimately times out. Locally, in the VS terminal, same deal...all specs passed and the wait indicator just keeps spinning...no completed check mark.

![image](https://user-images.githubusercontent.com/1321806/149003895-80ae3050-ca04-4596-a1bb-586fb435610f.png)

**Comment by clazette** [comment]
This issue can be closed. It's not the retries from what I can tell now. Thank you for looking into it. I'm glad you didn't waste too much time...my apologies.

**Comment by mjhenkes** [comment]
@clazette, no problem. If you are able to narrow the issue down further, don't hesitate to log another issue.
