### ISSUE TITLE
My Jenkins console output looks like this for cypress tests:

### ISSUE THREAD

**Issue by hassankaz** [cypress-io/cypress#19607]
I am still having this issue in cypress 9.2.0 when running tests on jenkins (ubuntu).
I've tried all workaround on the previous posting, as well as the one mentioned here
https://docs.cypress.io/guides/continuous-integration/introduction#Common-problems-and-solutions
but it didn't work.

If anyone could share a workaround, I really appreciate it. thank you so much in advance! 

-----------------------------------------------------------------
My Jenkins console output looks like this for cypress tests:
```
[90m  ┌[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m┐[39m
[90m  │[39m [90mCypress:[39m    3.4.0                                                                              [90m│[39m
[90m  │[39m [90mBrowser:[39m    Electron 61 [90m(headless)[39m                                                             [90m│[39m
[90m  │[39m [90mSpecs:[39m      26 found [90m([39m[90mdetails/appearance.spec.ts, companies/view[39m… [90m│[39m
[90m  └[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m─[39m[90m┘[39m
```

I don't understand why there is no option to disable color in output. This seems like a basic requirement for any type of testing -- the results should be easy to view and quickly assess. This jumble of formatting is anything but.  Also the `cypress run` output TRUNCATES the test file names, which makes it very difficult to locate the spec files that resulted in errors.

_Originally posted by @richworx in https://github.com/cypress-io/cypress/issues/3079#issuecomment-521320328_

**Comment by emilyrohrbough** [comment]
Have you considered installing the [AnsiColor](https://plugins.jenkins.io/ansicolor/) plugin to your Jenkins instances to view your logs with colors? It'd be helpful for quickly differentiating logs from errors.

**Comment by hassankaz** [comment]
Thank you @emilyrohrbough for your comment. For me color isn't much an issue but i will try adding the plugin to see if it makes difference.  If you know any solutions for removing the garbled characters in the log, please let me know. thanks!

**Comment by nalandial** [comment]
@hassankaz This may be related to #19624, in which case a fix (#19622) is currently slated to be released in 9.2.1.

**Comment by hassankaz** [comment]
> @hassankaz This may be related to #19624, in which case a fix (#19622) is currently slated to be released in 9.2.1.

thank you! I'm checking it now.

**Comment by tbiethman** [comment]
@hassankaz Just following up, has your issue been resolved?

**Comment by geyuqiu** [comment]
expected: ✓ download recollection result (16478ms)

current output:
[90m [39m [0mhould – download recollection photo report (failed).png[0m

**Comment by hasithawaruna** [comment]
This issue still exists. Did anyone find a solution?

**Comment by mike-plummer** [comment]
@hasithawaruna If you are seeing this issue against the latest version of Cypress on a fully-updated Jenkins instance after applying the [suggested workaround](https://docs.cypress.io/guides/continuous-integration/introduction#Colors) then you should open a new issue, ideally with a reproducible example and/or exact instructions on how we can reproduce the issue so we are able to troubleshoot. Since there are so many possible combinations and configurations of CI systems it is impossible for us to attempt to diagnose issues without at least a basic method of reproducing the problem.

**Comment by keevferreira** [comment]
the colors are not the problem, the problem is these characters here

                       
  ────────┘│
  
they make this square or table that shows the tests passed, i didn't find a solution
