### ISSUE TITLE
experimentalStudio doesn't record steps in 9.2.0

### ISSUE THREAD

**Issue by unickq** [cypress-io/cypress#19613]
### Current behavior

Generates empty steps
```
/* ==== Generated with Cypress Studio ==== */
/* ==== End Cypress Studio ==== */
```

### Test code to reproduce

```js
describe("My First Test", () => {
  it("Does not do much!", () => {
    cy.visit("/");
    /* ==== Generated with Cypress Studio ==== */
    /* ==== End Cypress Studio ==== */
  });
});
```

### Cypress Version

9.2.0

### Other

8.7.0 works as expected

**Comment by jennifer-shehane** [comment]
Can you explain the steps you took within Cypress Studio or provide a video of stepping through it? Are there any errors in the devtools console?
