### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by MuhammadUmairMoosani** [cypress-io/cypress#19615]
### Current behavior

`import { Link } from 'react-router-dom'`
When Link in ReactJs component so it show this error

exports is not defined

 cypress component testing 

### Test code to reproduce

                  <Link id="example" to={`/example}`}>
                    <Button className="mr-1 mb-2" size="small" type="primary">
                      View
                    </Button>
                  </Link>

### Cypress Version

^9.2.0

**Comment by smkamranqadri** [comment]
That's an external dependency you need to remove the link component, pass a function for navigation from parent component.
