### ISSUE TITLE
Configure time between retry attempts

### ISSUE THREAD

**Issue by intellix** [cypress-io/cypress#19616]
### What would you like?

I'd like to configure the time between spec retry attempts, either globally or on a describe/it basis

### Why is this needed?

We're calling a CMS and running many tests concurrently. We often run into 429 Rate Limited errors and currently Cypress just retries the test immediately. We know that we can run X API calls within Y timeframe so would like to increase the time between retries so that we don't hit the same rate limit and fail again straight afterwards

### Other

Example:
 - Go to homepage
 - Check that a button appears
 - 429 RATE LIMITED
 - ............... wait 5 seconds
 - Retry

**Comment by sainthkh** [comment]
`retry` feature is created for flaky tests. In e2e test world, tests sometimes fail for outside reasons (database lag, network problem,  etc.).

In your case, it might be a better idea to test it with `cy.wait` like below:

```js
cy.visit('your-site.com')
cy.get('#the-button').click()
cy.checkButtonWorks()
cy.get('#the-button').click()
cy.check429() // It might be your custom check. 
cy.wait(5000)
cy.get('#the-button').click()
cy.checkButtonWorks()
```

**Comment by bahmutov** [comment]
Or use the cypress-recurse plug-in

**Comment by intellix** [comment]
In this case, the 429 happens on the server side, so I suppose I'd need to do something like this?
```ts
cy.visit('your-site.com')
cy.check429()
cy.wait(5000)
cy.visit('your-site.com')
cy.get('#the-button').click()
cy.checkButtonWorks()
cy.get('#the-button').click()
cy.get('#the-button').click()
cy.checkButtonWorks()
```

**Comment by stefilomonaco** [comment]
@intellix have you solved this issue? or have you upgraded to 12?

**Comment by intellix** [comment]
erm, we've already updated to 12 but I wasn't aware that it was fixed there. Will give it another go
