### ISSUE TITLE
The project relies on colors.js with malicious code

### ISSUE THREAD

**Issue by shijiatongxue** [cypress-io/cypress#19624]
### Current behavior

- Bugs when run cypress cli

It's a known bug of [`colors`](https://github.com/Marak/colors.js/issues/290)

![image](https://user-images.githubusercontent.com/26477537/148726391-52edaf86-dfe4-4a3f-9e2e-7676b44d10a3.png)

![image](https://user-images.githubusercontent.com/26477537/148726241-82b5a0d7-9e80-4640-ae9a-81278c11b974.png)

[bugs here](https://github.com/DouyinFE/semi-design/runs/4756809788?check_suite_focus=true)

- cypress dependency

![image](https://user-images.githubusercontent.com/26477537/148727738-92f9fd14-4a0a-4434-8e15-c259050cc064.png)

### Desired behavior

everything is ok when run cypress

### Test code to reproduce

run it **_MAY BE DANGER_** on local machine: `npx cypress run`

### Cypress Version

9.2.0

**Comment by felladrin** [comment]
There's a PR for replacing `colors` by `chalk` in `cli-table`: https://github.com/Automattic/cli-table/pull/166

**Comment by tzimmermann** [comment]
You can already upgrade `cli-table3` to `0.6.1` in your lockfile to fix this.
They've released a fix with a pinned dep to `colors@1.4.0`.
https://github.com/cli-table/cli-table3/pull/251
