### ISSUE TITLE
Cypress cannot execute binary file when running on Linux on System z

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [cypress-io/cypress#19636]
### Current behavior

Not able to run Cypress at all on linux on Z system.

Cypress package version: 9.2.0
Cypress binary version: 9.2.0
Electron version: 15.2.0
Bundled Node version: 16.5.0

node: v16.13.1
npm: 8.1.2
Red Hat Linux - 8.4 (s390x)

DEBUG=cypress:* ./node_modules/.bin/cypress verify
  cypress:cli:cli cli starts with arguments ["/opt/nodejs/node-v16.13.1-linux-s390x/bin/node","/root/cypress-test-tiny/node_modules/.bin/cypress","verify"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +8ms
  cypress:cli parsed cli options {} +2ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /root/.cache/Cypress/9.2.0/Cypress/Cypress +2ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /root/.cache/Cypress/9.2.0/Cypress +0ms
  cypress:cli Reading binary package.json from: /root/.cache/Cypress/9.2.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 9.2.0 installed in: /root/.cache/Cypress/9.2.0/Cypress +2ms
  cypress:cli could not read binary_state.json file at "/root/.cache/Cypress/9.2.0/binary_state.json" +2ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli force verify +0ms
  cypress:cli running binary verification check 9.2.0 +0ms

  cypress:cli clearing out the verified version +4ms
  cypress:cli undefined DISPLAY environment variable +0ms
  cypress:cli Cypress will spawn its own Xvfb +0ms
  cypress:cli needs Xvfb? true +1ms
  cypress:cli Starting Xvfb +0ms
  cypress:cli disabling Electron sandbox +32ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /root/.cache/Cypress/9.2.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /root/.cache/Cypress/9.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=253 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command failed with exit code 126: /root/.cache/Cypress/9.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=253
/root/.cache/Cypress/9.2.0/Cypress/Cypress: /root/.cache/Cypress/9.2.0/Cypress/Cypress: cannot execute binary file
    at makeError (/root/cypress-test-tiny/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/root/cypress-test-tiny/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 126: /root/.cache/Cypress/9.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=253',
  command: '/root/.cache/Cypress/9.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=253',
  exitCode: 126,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/root/.cache/Cypress/9.2.0/Cypress/Cypress: /root/.cache/Cypress/9.2.0/Cypress/Cypress: cannot execute binary file',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +20ms
  cypress:cli error message: /root/.cache/Cypress/9.2.0/Cypress/Cypress: /root/.cache/Cypress/9.2.0/Cypress/Cypress: cannot execute binary file +1ms

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

/root/.cache/Cypress/9.2.0/Cypress/Cypress: /root/.cache/Cypress/9.2.0/Cypress/Cypress: cannot execute binary file

----------

Platform: linux-x64 (Red Hat Linux - 8.4)
Cypress Version: 9.2.0

### Desired behavior

Cannot execute simple Cypress command like: cypress verify or cypress run

### Test code to reproduce

https://github.com/alfonso-rios-ibm/cypress-test-tiny

### Cypress Version

9.2.0

### Other

Cypress package version: 9.2.0
Cypress binary version: 9.2.0
Electron version: 15.2.0
Bundled Node version: 16.5.0

node: v16.13.1
npm: 8.1.2
Red Hat Linux - 8.4 (s390x)

**Comment by ghost** [comment]
This is still an issue, not able to run Cypress in a zLinux machine
