### ISSUE TITLE
Multi-domain script is injected into cross origin html regardless of switchToDomain context

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#19632]
### Current behavior

With the introduction of #19465, a [bugfix](https://github.com/cypress-io/cypress/pull/19465/commits/393f1c9226d02f87712258b98145b8d896e71bdd) to attempt fixing cache issues with multidomain html state introduced a regression where the multidomain script is being injected on cross origin html requests (ex: `cy.visit`) when `switchToDomain` is not used. This causes the browser to error, as it is expecting to have the content renders in a subframe that does not exist. 

![Screen Shot 2022-01-10 at 12 41 02 PM](https://user-images.githubusercontent.com/3980464/148813612-07227733-1451-403a-a82b-d36590f08ac0.png)

### Desired behavior

Ideally, if `switchToDomain` is used, the content of the visited site that is also configured in `switchToDomain` should be rendered in a subframe with the injection script. Otherwise, the content should should bypass the multidomain flow. 

### Test code to reproduce

Example to produce desired result:

```js
    it('visits without switchToDomain', () => {
      // renders in the main frame without the injection script
      cy.visit('foobar.com')
    })

    it('visits with switchToDomain', () => {
      cy.visit('foobar.com')
      // navigates to barbaz.com
      cy.click('a')

      cy.switchToDomain('barbaz.com', () => {
        // barbaz.com renders in a sub frame with the injection script
      })
    })

    it('visits without switchToDomain', () => {
      // renders in the main frame without the injection script, regardless of cached results
      cy.visit('foobar.com')
    })
```

### Cypress Version

feature-multidomain

**Comment by AtofStryker** [comment]
related to #20428

**Comment by chrisbreiding** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/20752
