### ISSUE TITLE
.task

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#1964]
### Current behavior:
After adding new libraries it says:
Uncaught TypeError: Cannot read property 'prototype' of undefined

### Desired behavior:
Use external library functions properly
### Steps to reproduce:

npm install Cypress --save-dev
npm install excel --save-dev
npm install babel-cli --save-dev
npm install babel-preset-env --save-dev
npm install mocha --save-dev;

in test file in integration insert code below:
var parseExcel = require('excel/commonjs/excelParser').default;

### Versions

Mac
electron 59

**Comment by brian-mann** [comment]
I'm sorry, I'm not quite sure why you've opened another issue - the exact same one as the previous, which we answered and closed here: https://github.com/cypress-io/cypress/issues/1963
