### ISSUE TITLE
The scrollbar goes up and down and never shows the menu buttons

### ISSUE THREAD

**Issue by frankaste** [cypress-io/cypress#19650]
### Current behavior

When I run my test, cypress is waiting for a button that doesnt appears because the scrollbar goes up and down. I use clickById to try click the element. I tried with these differents methods but not worked 

 protected clickById(elementId: string): void {
        elementId = BrowserActionsHelper.addCharAtFirst(elementId, "#");
        cy.get(elementId).first().click();
    }

 protected clickById(elementId: string): void {
        elementId = BrowserActionsHelper.addCharAtFirst(elementId, "#");
        cy.get(elementId).first().scrollTo('top').click();
    }

 protected clickById(elementId: string): void {
        elementId = BrowserActionsHelper.addCharAtFirst(elementId, "#");
        cy.get(elementId).scrollIntoView().click();
    }

https://user-images.githubusercontent.com/37113052/148943495-5c226656-53e9-4db6-95f9-b08e186aa31b.mp4

![image](https://user-images.githubusercontent.com/37113052/148945856-ff6ce504-cef0-44f4-b74d-f6c689e33312.png)

### Test code to reproduce

test

### Cypress Version

8.7.0

**Comment by mjhenkes** [comment]
@frankaste, could your provide a project recreating the issue?
