### ISSUE TITLE
The Cypress App could not be unzipped

### ISSUE THREAD

**Issue by AliAhmar** [cypress-io/cypress#19655]
### Current behavior

When i try to download cypress i get following error..

![issue](https://user-images.githubusercontent.com/69307398/148961107-2f3f5908-8e20-4100-b037-9214dc97f5ae.png)

I am not behind any proxy or firewall on Windows 10
Cypress version is 9.2.1

### Cypress Version

9.2.1

### Package Manager

npm

### Operating system

Windows

**Comment by mjhenkes** [comment]
@AliAhmar, i was unable to recreate this issue. But i did notice your error:
 `Error: EEXIST: file already exists, mkdir 'C:\users\Owner\AppData\Local\Cache\9.0.0`
 
 Have you tried removing that file and re-installing?

**Comment by AliAhmar** [comment]
@mjhenkes Yes I have removed this file and tried re-installing multiple times without any luck

**Comment by davidmunechika** [comment]
@AliAhmar Did you ever find a fix for this issue?

**Comment by Ahmar8228** [comment]
@davidmunechika  Yes the issue was with node version. if you check [here](https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirement) cypress only supports node 12, 14 or above and I was using node 10. Upgrading my node fixed this issue

**Comment by davidmunechika** [comment]
Thanks for your response! Glad to hear you found a fix
