### ISSUE TITLE
cy.visit loads page very slow for first time in open mode

### ISSUE THREAD

**Issue by tpitko-parsable** [cypress-io/cypress#19656]
### Current behavior

When I open cypress GUI, and start test for first time cy.visit works very slow (seems that it load chunks very slow) 
After starting test again cy.visit works fine 

Note: this reproduces not depending on latest cypress versions (first I faced this behaviour when started using cypress with v 7.5.0)

### Desired behavior

cy.visit page for first, second and further times should take approximately the same time and it should be approximately the same as visiting page without cypress

### Test code to reproduce

the following repo contains all code to reproduce https://github.com/tpitko-parsable/cypress-repro

Steps to reproduce:

1. start dev server in terminal by npm start
2. in different terminal window start cypress GUI by npm run cy:open
3. select app.spec.js test in GUI and click on it -> browser opened and test started
4. remember time of test execution - time1
5. start test again by R on by clicking on Run button
6. remember tests execution time again - time2

__Actual__: time2 is significantly lower than time1 

__Expected__: time2 is approximately the same as time1 

 ![./docs/first_run.png](https://raw.githubusercontent.com/tpitko-parsable/cypress-repro/main/docs/first_run.png)
 ![./docs/second_run.png](https://raw.githubusercontent.com/tpitko-parsable/cypress-repro/main/docs/second_run.png)

### Cypress Version

9.2.1

### Other
node v14.18.1
npm 7.0.14
MacOS Big Sur 11.6.2

**Comment by lorenzofidalgo** [comment]
Could this issue be realted with this other one? https://github.com/cypress-io/cypress/issues/19999
