### ISSUE TITLE
Conditionally retry a test or suite

### ISSUE THREAD

**Issue by azoff** [cypress-io/cypress#19677]
### What would you like?

I would like the ability to natively retry a test from within the logic of a test itself. I currently accomplish this with a complete hack:

```js
if (stateIsCorrupt()) {
  cy.state('runnable')._retries = 1 // force a retry
  repairCorruptState() // fix the underlying state before retrying
  assert(false) // fail the test to start the retry
}
```

### Why is this needed?

My use case is that many of my integration tests share a server state. This is unavoidable in my particular case. 

If that shared state gets corrupted, the test will fail. Ideally, a test could detect the corrupt state, repair it manually, and retry the test.

### Other

In theory, the existing retry functionality could support this idea, but the problem is that it is all-or-nothing. Basically, it will retry for *any* failure, and not just for the failure modes that I'd like to retry on. This makes tests unnecessarily inefficient.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest, we’ll close this issue.
