### ISSUE TITLE
hyphens: auto does not work during cypress tests in chrome/electron

### ISSUE THREAD

**Issue by awaigand** [cypress-io/cypress#19670]
### Current behavior

When testing a page, that has the language declared as "de" (`html lang="de"`) and elements have hyphens:auto, long strings should break according to specific language rules using hyphens. This does not happen in Chrome and Chromium in Cypress However, opening the same page in chrome or chromium outside of cypress, it works. It also works using Firefox inside of Cypress.

This is an example with the German word "Auftragsbekanntmachung" (declaration of orders).
Chrome 
![image](https://user-images.githubusercontent.com/5626967/149096348-cc39fb48-a592-4a33-a315-6214ba1033d3.png)

Same site, same Chrome, just outside of Cypress
![image](https://user-images.githubusercontent.com/5626967/149096466-d0aea812-b069-47da-983a-866b75af894f.png)

Firefox inside of Cypress. this works
![image](https://user-images.githubusercontent.com/5626967/149096684-62d8cbf4-29f1-43b1-b539-7cbcdc9bac73.png)

This happens on Linux (Kubuntu 20.04) and Windows 10. It also happens with electron.

### Desired behavior

The string should break according to language rules, even inside of Cypress.

### Test code to reproduce

- Download this Repo : https://github.com/awaigand/cypress-hyphens-demo
- Run `npm install`
- Run `npm run test`
- Select Chrome, Chromium or Electron (or Edge, for that matter)
- Notice that the string "Auftragsbekanntmachung" is not breaking
- Open "localhost:8080" in regular Chrome and notice that "Auftragsbekanntmachung" is breaking

### Cypress Version

9.2.1

### Other

Thank you for your great work and support!

Some more Details: 
Chrome Version: 97 (most recent)
Firefox: Most Recent
Tested On: Windows 10, Kubuntu 20.04

I also added an "iframe-test.html", since I thought it might be something generic with iframes, but it also worked there outside of Cypress.

**Comment by RazielleS** [comment]
I still experience this issue. Can we open this again?

**Comment by jennifer-shehane** [comment]
I ran the example in Cypress 13.7.0 and no longer see this issue in Chrome or Electron. 

@RazielleS Could you provide an example that doesn't work with our latest version?

![Screenshot 2024-03-14 at 11 58 52 AM](https://github.com/cypress-io/cypress/assets/1271364/c0f6c746-d0d1-4a95-9db8-3e6e64ff636b)
