### ISSUE TITLE
"npm install" fails in this repository

### ISSUE THREAD

**Issue by JJ** [cypress-io/cypress#19694]
### Current behavior

`npm i` simply fails with a package not found.

### Debug logs

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: cypress@9.2.1
npm ERR! Found: dev @percy/cypress@"^3.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @percy/cypress@"^3.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/jmerelo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jmerelo/.npm/_logs/2022-01-13T17_30_19_326Z-debug-0.log
```

### Cypress Version

9.2.1

### Package Manager

npm

### Operating system

Linux

### Other

This is mainly a less than awesome error. Not a big deal.

**Comment by JJ** [comment]
I might suggest something along the lines of [this]("node -e \"if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('You must use Yarn to install, not NPM')\"), although I've tested it and it does not seem to work, at least locally.

**Comment by mjhenkes** [comment]
Hi @JJ , thanks for logging this issue (and i must say, nice get on the two letter username!). Yarn 1 is required for developing in the which we have documented in [contributor guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) which is enough for us now. That said, we are always happy to accept Pull requests!
