### ISSUE TITLE
Recent Cypress versions don't work when a `Content-Security-Policy` meta tag specifies a `script-src` directive without `unsafe-eval`

### ISSUE THREAD

**Issue by pmattj** [cypress-io/cypress#19697]
### Current behavior

Our app presents its Content Security Policy via a meta tag. The `script-src` directive specifies `self`, a few domains, and a few sha256 hashes for script files. Notably, it does not specify `unsafe-eval`.

We're currently using Cypress 7.0.0. When we try to upgrade to any recent version (including 9.2.1), we see the following error when Cypress attempts to load the app:
```
Cypress detected a cross origin error happened on page load:

  > Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://a.fakedomain.com https://.anotherfakedomain.com 'sha256-ZULbkGmGe5zed/vot6JJ5Qydvd1j/b3G8R/WaST6XIY=' 'sha256-NIPa1sf5+FN4jNBz487q56NyL61V8p5VCL4gQ6xXxQs='".

Before the page load, you were bound to the origin policy:

  > https://slack.com

A cross origin error happens when your application navigates to a new URL which does not match the origin policy above.

A new URL does not match the origin policy if the 'protocol', 'port' (if specified), and/or 'host' (unless of the same superdomain) are different.

Cypress does not allow you to navigate to a different origin URL within a single test.

You may need to restructure some of your test code to avoid this problem.

Alternatively you can also disable Chrome Web Security in Chromium-based browsers which will turn off this restriction by setting { chromeWebSecurity: false } in cypress.json.
```

We believe the text about a cross-origin error is misleading and the actual problem is with this new function introduced in Cypress 7.4.0: https://github.com/cypress-io/cypress/pull/15995/files#diff-de6e9902e3eb298fa80eaee4cdffd16b6f3db0a8576254715771e43b8441ccadR130-R134

Because `new contentWindow.Function(...)` is an unsafe eval and `unsafe-eval` isn't specified in the policy, Chrome refuses to evaluate this code.

(We're already using `chromeWebSecurity: false`.)

### Desired behavior

Cypress should work even if there's a `Content-Security-Policy` meta tag without `script-src: unsafe-eval`.

Ideally, Cypress wouldn't need `script-src: unsafe-eval`. Perhaps there's a way to achieve the goal of https://github.com/cypress-io/cypress/pull/15995 without it.

Second best would be for Cypress to intercept the meta tag and rewrite it to include `unsafe-eval` if that directive isn't already present.

If that's not feasible, I believe Cypress already ignores the `Content-Security-Policy` _header_, so perhaps the simplest approach would be to ignore the CSP meta tag as well. (Moving the CSP into a header isn't an option for us.)

### Test code to reproduce

https://github.com/pmattj/cypress-test-tiny/tree/issue_19697

### Cypress Version

9.2.1

**Comment by pmattj** [comment]
I added a minimal repro in the description.

**Comment by bahmutov** [comment]
You can intercept and rewrite the html of the document itself using cy.intercept

**Comment by BlueWinds** [comment]
> I added a minimal repro in the description.

I'm unable to reproduce this using the given example; It appears to run fine on all my installed browsers.

Tested under Cypress 9.0.0, 9.2.1 and 9.3.0, with Electron 94, Firefox 96, and Chrome 98 - both tests pass in all cases.

Which browser+versions are you seeing issues with, and on which OS? It's possible that it's more a specific bug, help tracking it down would be appreciated. 

![image](https://user-images.githubusercontent.com/3003404/150013336-0f5636c2-b9c8-4b81-b19e-17adbfaff426.png)
