### ISSUE TITLE
Component testing doesn't work after CRA ejecting (webpack 5)

### ISSUE THREAD

**Issue by weblaetitia** [cypress-io/cypress#19690]
### Current behavior

After ejecting a CRA application, the component test are not working. 
The `npx cypress run-ct` command will display the error below: 
```
Dev-server compilation failed. We can not run tests if dev-server can not compile and emit assets, please make sure that all syntax errors resolved before running cypress. 

 Module parse failed: Unexpected token (6:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| it("renders learn react link", () => {
>   mount(<App />);
|   cy.get("a").contains("Learn React");
| });
Error: Dev-server compilation failed. We can not run tests if dev-server can not compile and emit assets, please make sure that all syntax errors resolved before running cypress. 
```
I follow this cypress guide https://docs.cypress.io/guides/component-testing/introduction with same settings.

### Test code to reproduce

You can check this minimal app I've created on this repo: https://github.com/weblaetitia/cra-eject-cypress/tree/eject
- On "master" branch: app with CRA: component testing are working fine
- On "eject" branch: app with webpack config: component testing fails

Config is
- CRA 5
- webpack 5
- cypress 8.5.0
- @cypress/react 5

### Cypress Version

8.5.0

**Comment by JessicaSachs** [comment]
Thanks for the great issue report. I was able to repro this and we'll add this to the backlog.

**Comment by Phonesis** [comment]
Hello, I am seeing a similar issue with the Cypress Component testing feature (which I know is still in alpha) and wondered if related or same. When I run Cypress ct-open the component mounts fine and the test passes. However, using the same webpack config and test etc when I run ct-run it fails with: 

```
Dev-server compilation failed. We can not run tests if dev-server can not compile and emit assets, please make sure that all syntax errors resolved before running cypress. 

 [tsl] ERROR in /src/SaaSScheduler/SaaSScheduler.tsx(13,21)
      TS2307: Cannot find module './SaaSScheduler.module.scss' or its corresponding type declarations.
Error: Dev-server compilation failed. We can not run tests if dev-server can not compile and emit assets, please make sure that all syntax errors resolved before running cypress. 
```

It seems odd it works when in open mode but not run using same webpack config?

**Comment by ZachJW34** [comment]
@Phonesis are you working with an ejected create-react-app? If not, can you open a new issue and provide a reproduction?

**Comment by Fewwy** [comment]
Having a similar issue, I'm not sure that I can share the code. Installing @sentry didn't help

```
Module not found: Error: Can't resolve 'process/browser.js' in '/node_modules/@sentry/utils/esm'
Error: Dev-server compilation failed. We can not run tests if dev-server can not compile and emit assets, please make sure that all syntax errors resolved before running cypress.
```

**Comment by lmiller1990** [comment]
Just tested with Cypress 12

1. `yarn create react-app my-app`
2. `cd my-app && yarn`
3. `yarn add cypress`
4. `yarn cypress open` -> configure component testing
5. it works
6. git add . && git commit -m 'add cypress'
7. kill cypress
8. `yarn eject` -> yes
9. `yarn cypress open`
10. still works

If this is still an issue, please tell me how to reproduce. Thanks!

**Comment by alessandro308** [comment]
@lmiller1990 What if I ejected the project BEFORE to install Cypress? 🤔 
As you did, I expect to see framework set in cypress.config file as create-react-app that throw error if, after the ejecting, we remove react-script package

I made it working manually adding the config:
```
component: {
    devServer: {
      framework: "react",
      bundler: "webpack",
      webpackConfig: {
        ...require('./config/webpack.config'),
      }
    },
  },
  ```
