### ISSUE TITLE
Testing the tests.

### ISSUE THREAD

**Issue by nothingismagick** [cypress-io/cypress#1970]
This is neither an issue nor a feature request, as I am quite satisfied with the atomic patterns with which I can control the way that Cypress runs and how I can step through the tests when they fail, but I am working on the generational production of a large battery of tests based on generic types hydrated from a resource that also scaffolds the vuex store, localstorage and vue (using Quasar). 

My components and logic are all unit tested, I am using the electron version of vue-devtools to watch state and events, I personally test critical external modules and cypress guarantees that vuex and vue collaborate properly during runtime - but... 

My tests are generational and only exist in memory during the run - so how can I test my tests to make sure that they (or more rather the code itself) has 100% coverage? 

Does anyone have any experience in this admittedly silly exercise or recommendations about similar work? I have thought about wrapping the cypress tests in [tap](https://github.com/tapjs/node-tap), but I am pretty sure that cypress won't really like that double-bootstrapping. I also thought about using cy.exec() in each step, but cy.task() almost seems more appropriate. Anyway, I would totally appreciate any ideas or pointers here...

**Comment by brian-mann** [comment]
Write the state of the tests using `cy.writeFile` and possibly verify that object after the run is complete.

Alternatively use an `after` hook and use `cy.task` to do it as well.

**Comment by nothingismagick** [comment]
Wow - that was really fast. Thanks for the advice. 👍
