### ISSUE TITLE
Multi-domain: Handle 'error' and 'unhandledrejection' events

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#19709]
### What would you like?

Handle 'error' and 'unhandledrejection' events occurring in the secondary domain AUT. This primarily means wiring up [this callback](https://github.com/cypress-io/cypress/blob/d8fa85d3dc9888c3fe65af9b4fb8291939f5675d/packages/driver/src/multi-domain/index.ts#L200-L202) so that it forwards any errors to the primary domain and displays them properly.

See what the [primary domain driver does for this](https://github.com/cypress-io/cypress/blob/d8fa85d3dc9888c3fe65af9b4fb8291939f5675d/packages/driver/src/cypress/cy.ts#L1077-L1093). The code there can probably be abstracted and re-used so that the secondary domain error goes through it in the primary domain before being displayed to the user.

[errors.html](https://github.com/cypress-io/cypress/blob/d8fa85d3dc9888c3fe65af9b4fb8291939f5675d/packages/driver/cypress/fixtures/errors.html) is a good fixture to use for testing this.

**Comment by AtofStryker** [comment]
resolved by #19922
