### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'uid'). Cypress 9.2.1 along with cucumber bdd.

### ISSUE THREAD

**Issue by Vik4290** [cypress-io/cypress#19707]
### Current behavior

<img width="1440" alt="Screenshot 2022-01-14 at 1 22 07 PM" src="https://user-images.githubusercontent.com/62888395/149507428-a51a7c69-df0a-43e6-a24f-b4c17699acdc.png">

==============================================================

**Package.json file:**

{
  "name": "package.json",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "lint": "eslint 'cypress/**/*.{js,ts,tsx}'",
    "pretty": "prettier --write \"cypress/**/*.{ts,js,jsx,json}\""
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.9.1",
    "@typescript-eslint/parser": "^5.9.1",
    "eslint": "^8.6.0",
    "eslint-config-airbnb-typescript": "^16.1.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "prettier": "^2.5.1"
  },
  "cypress:open": "cypress open",
  "dependencies": {
    "@cypress/browserify-preprocessor": "^3.0.2",
    "@types/chai-string": "^1.4.2",
    "@types/chai-subset": "^1.3.3",
    "@types/cypress-cucumber-preprocessor": "^4.0.1",
    "chai": "^4.3.4",
    "chai-string": "^1.5.0",
    "chai-subset": "^1.6.0",
    "cypress": "^9.2",
    "cypress-cucumber-preprocessor": "^4.3.1",
    "cypress-file-upload": "^5.0.8",
    "cypress-promise": "^1.1.0",
    "husky": "^7.0.4",
    "lint-staged": "^12.1.7",
    "tsify": "^5.0.4",
    "typescript": "^4.5.4",
    "uuidv4": "^6.2.12",
    "@testing-library/cypress": "^8.0.2",
    "@types/uuid": "^8.3.4",
    "cypress-tags": "^0.3.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "./cypress/**/*.{js,ts}": [
      "eslint --fix --max-warnings 0"
    ],
    "./**/*.{json,md,yml}": [
      "prettier --write"
    ]
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  },
  "resolutions": {
    "graceful-fs": "4.2.9"
}

  
}

### Desired behavior

There should not be any error. Code must run.

### Test code to reproduce

will provide privately

### Cypress Version

cypress 9.2.1

**Comment by mjhenkes** [comment]
Maybe fixed by #19676

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Is it still not working with the latest Cypress?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
