### ISSUE TITLE
Cypress could not verify that this server is running

### ISSUE THREAD

**Issue by indignant** [cypress-io/cypress#19711]
### Current behavior

When I run Cypress open:
- Cypress opens
- It hangs for several minutes
- Error: "Cypress could not verify that this server is running"
- Cypress provides a link and that link takes me to my application as expected

Tried:
- Rebooting
- Updating Cypress
- Removing and reinstalling node_modules

<img width="593" alt="Screen Shot 2022-01-14 at 1 17 47 PM" src="https://user-images.githubusercontent.com/69015187/149573034-0ef346f8-8d3b-49e3-b92f-19108f5cd8d4.png">

### Desired behavior

I would like Cypress to open so I can run tests.

### Test code to reproduce

Not sure how to recreate

### Cypress Version

9.2.1

**Comment by indignant** [comment]
Tried switching to `http://127.0.0.1:3000`, but got this issue instead: https://github.com/cypress-io/cypress/issues/19669

**Comment by tbiethman** [comment]
@indignant can you provide details about your dev environment:

* OS version
* Node version
* Any other versions of Cypress you tried that exhibit this issue
* Any DEBUG logs output during cypress execution (`DEBUG=cypress:* yarn cypress open`)

**Comment by indignant** [comment]
@tbiethman I think I figured out the problem. Something wiped my `/etc/hosts` file and cleared my `127.0.0.1 localhost` mapping. This, combined with a VPN, subtly wrecked havoc on my whole dev environment. Thank you for reminding me to close this.

**Comment by 0303vikas** [comment]
I had the same issue, fixed it by Running the front-end before running cypress. if you are using gitlab ci, check if your front end server is running and if its running on correct port.

**Comment by MetRonnie** [comment]
For me this was apparently caused by changing OpenSSL version
