### ISSUE TITLE
cypress dashboard password reset email not received

### ISSUE THREAD

**Issue by dlabrecque-uzinakod** [cypress-io/cypress#19718]
### Current behavior

Hi,
I tried to reset my password through the password reset form, but I never received the email.
I tried to hit resend, no email.
I checked my spam forder, no email.
I used another email address, no email.

### Desired behavior

I should receive an email with a link to get me to a reset password form.

### Test code to reproduce

https://dashboard.cypress.io/reset-password

### Cypress Version

cypress.io

### Other

Apologies if it's not the right place to report this.

**Comment by jennifer-shehane** [comment]
Please email support@cypress.io if this is still not resolved for you.

**Comment by conversaShawn** [comment]
I also recommend first checking to see if you are using social auth to sign in (Google or GitHub). 

To sign in with Social Authentication, you will need to click "Login with << Google OR GitHub >>" when you reach the Dashboard login page. If you cannot remember that password, you will need to go through that separate "Forgot Password" process.

**Comment by sinhaam** [comment]
I just tried recovering my password through e-mail, did'nt recieve any email.

**Comment by nagash77** [comment]
@sinhaam please see jennifer's comment above.
