### ISSUE TITLE
Passthrough is not supported, GL is disabled, ANGLE is 

### ISSUE THREAD

**Issue by usama-khalied** [cypress-io/cypress#19723]
### Current behavior

I am getting this error and have enabled Webgal 2.2 but it is not resolving it.

### Debug logs

What i do ?

### Cypress Version

Electron

### Package Manager

npm

### Operating system

Windows

**Comment by usama-khalied** [comment]
Electron

**Comment by tbiethman** [comment]
When opening an issue, please fill out the issue template provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our contributing guidelines. Please comment in this issue with the required information from our issue template and we will consider reopening the issue.
