### ISSUE TITLE
Websocket SSL cert issue when running a site in Cypress

### ISSUE THREAD

**Issue by mikejurka** [cypress-io/cypress#19722]
### Current behavior

I'm running a simple test just loading a page (see below). When you run the test with Cypress, you'll see the websocket error in the console, and the web app shows a join error and ends on a screen "Create an account and sign in" which it normally does not when not run in Cypress.

Error:
```
WebSocket connection to 'wss://pi_spatial-us-ns.exitgames.com:19093/?libversion=4.1.6.6&sid=30&app=NameServer' failed: Error in connection establishment: net::ERR_SSL_SERVER_CERT_BAD_FORMAT
```

The test is
```
describe('Home Tests', () => {
    it('basic test', () => {
        cy.visit('https://app.spatial.io/rooms/61b816d729f14600012b1573?share=4484498830363372785');
        cy.wait(10000);
    });
});
```

and I've also disabled chrome web security.

### Desired behavior

If you load the url `https://app.spatial.io/rooms/61b816d729f14600012b1573?share=4484498830363372785` you will see that it does not have the websocket error, and does not end up on a screen saying "Create an account and sign in" 

In this situation, Cypress should not cause the websocket connection to fail due to `ERR_SSL_SERVER_CERT_BAD_FORMAT` and the web app should load as normally. The documentation says:
"Under the hood we act as our own CA authority and issue certificates dynamically in order to intercept requests otherwise impossible to access. We only do this for the superdomain currently under test, and bypass other traffic. That's why if you open a tab in Cypress to another host, the certificates match as expected."
This websocket connection is being made to a host that's not the superdomain, so I wouldn't expect it to be changing anything about the SSL cert.

### Test code to reproduce

```
describe('Home Tests', () => {
    it('basic test', () => {
        cy.visit('https://app.spatial.io/rooms/61b816d729f14600012b1573?share=4484498830363372785');
        cy.wait(10000);
    });
});
```

### Cypress Version

9.2.1

### Other

My cypress.json looks like this
```
{
    "chromeWebSecurity": false
}
```

**Comment by matiasgarcia** [comment]
I have a similar issue, any workaround for this?
