### ISSUE TITLE
Cypress - 403 - Forbidden: Not able to launch websites like lowes.com

### ISSUE THREAD

**Issue by kaukul** [cypress-io/cypress#19725]
### Current behavior

When I do
cy.visit('https://www.lowes.com/')

I get:

Sorry, we could not load:
https://www.lowes.com/
403 - Forbidden (text/html)

However, If I write a script to search lowes.com on google and click on lowes.com from search result. In this case the Lowes website works fine

### Desired behavior

User should be able to navigate to the website

### Test code to reproduce

Does not work:

       cy.visit('https://www.lowes.com/')

Works:
        cy.visit('https://www.google.com/')
        cy.get('[name="q"]').type("lowes.com")
        cy.wait(400)
        cy.contains('lowes.com').click()
        cy.contains('Official Site').click()

### Cypress Version

9.2.1

**Comment by kaukul** [comment]
Note: Setting _chromeWebSecurity_ to **false** did not work

**Comment by Krisell** [comment]
The website seems to modify the response depending on the sent User-Agent header. If you do a curl request without a UA header, you get that 403, and also if you specify only "Chrome". However if you use a "real-looking" UA, the page HTML is returned instead.

So, you can probably "solve" this by modifying the Cypress User-Agent, however realise that they probably added this behaviour to try to block tools like Cypress.

**Comment by kaukul** [comment]
> The website seems to modify the response depending on the sent User-Agent header. If you do a curl request without a UA header, you get that 403, and also if you specify only "Chrome". However if you use a "real-looking" UA, the page HTML is returned instead.
> 
> So, you can probably "solve" this by modifying the Cypress User-Agent, however realise that they probably added this behaviour to try to block tools like Cypress.

Thank you @Krisell for your reply. I tried to set user in cy.visit(), this also did not work for me: Can you please copy the snippet that worked for you here?

        let url = 'https://www.lowes.com'
        cy.visit(url, {
          headers: {
              'user-agent': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
          },
          timeout: 60000
      });

Sorry, I am new to Automation, so not able to resolve it with your suggestion.

**Comment by Krisell** [comment]
That UA doesn't work in Curl either, but this does: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36`

However it is of course possible the website has other ways to try to detect, and block, Cypress.

**Comment by kaukul** [comment]
> 

I wonder how come it works when cypress clicks on lowes.com from google but not directly. Anyway, Thank you. I'll keep learning.

**Comment by cvenkatreddy** [comment]
I am facing a similar issue(403 forbidden) on website `ninjacasino.com`, but for me `cy.visit(url)` is working fine on chrome browser if we run it via cypress runner. I am seeing issue only via CLI(cypress run -b chrome), same tests on passing on Firefox and Electron, I am seeing issue only chrome that to via CLI

**Comment by BinaryJava** [comment]
I also have the same issue on Cypress 12.3.0. If I do `cy.visit('https:www.google.co.uk')` it works fine, but when I switch to another website I get the 403 error

**Comment by irealsourav** [comment]
I am also facing the same issue..any workarounds ?

**Comment by astone123** [comment]
@irealsourav what is most likely happening is that the site that you are trying to visit is returning 403 based on some info that is sent in the request that Cypress makes to the site. This is most often the `User-Agent` header as pointed out by @Krisell above.

The only way that I know to work around this is to try to figure out which headers the server is rejecting, and then either remove or modify that header using `cy.intercept` to a value that is acceptable for the site that you are trying to visit.

However, understand that this was probably an intentional move by the site in order to block automated tools like Cypress from visiting their site, and it could potentially violate their terms of service.

**Comment by kaukul** [comment]
> @irealsourav what is most likely happening is that the site that you are trying to visit is returning 403 based on some info that is sent in the request that Cypress makes to the site. This is most often the `User-Agent` header as pointed out by @Krisell above.
> 
> The only way that I know to work around this is to try to figure out which headers the server is rejecting, and then either remove or modify that header using `cy.intercept` to a value that is acceptable for the site that you are trying to visit.
> 
> However, understand that this was probably an intentional move by the site in order to block automated tools like Cypress from visiting their site, and it could potentially violate their terms of service.

Makes sense. Thanks so much for looking into it!
