### ISSUE TITLE
'test:after:run' swallows errors

### ISSUE THREAD

**Issue by LirSegev** [cypress-io/cypress#19728]
### Current behavior

`test:after:run` swallows errors. Test passes and error is not logged anywhere
unlike #2271 it doesn't hang

### Desired behavior

test should fail and propagate error message, like `window:before:load` for example
```typescript
Cypress.on('window:before:load', () => {
    undefined.test
});
```
```
TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read properties of undefined (reading 'test')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

```

### Test code to reproduce

```typescript
Cypress.on('test:after:run', () => {
    undefined.test;
});
```

### Cypress Version

9.2.1

### Other

There is a workaround for this by using `try...catch`, however for people who don't know about this bug it can be a pain to debug a failure in `test:after:run`.

```typescript
Cypress.on('test:after:run', (test) => {
    try {
         undefined.test;
    } catch (e) {
        test.state = 'failed';
        test.err = e;
    }
});
```

**Comment by tbiethman** [comment]
@LirSegev thanks for reaching out. Unlike the `window:before:load` event, the test is no longer in a reportable state during the `test:after:run` event. When I try your workaround, I don't see it having any impact on the reported test status within Cypress, which is what [we would expect](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/runner.ts#L75-L78). I do see the error caught and logged to the console.

Can you give us more information regarding how this is impacting your development? We might be able provide suggestions or alternatives.
