### ISSUE TITLE
Run into an error of "‘node\r’: No such file or directory" with Cypress 9.3.0

### ISSUE THREAD

**Issue by weareoutman** [cypress-io/cypress#19747]
### Current behavior

With the latest version of Cypress 9.3.0, an error of `‘node\r’: No such file or directory` will occur when running cypress, while no errors for previous versions.

### Test code to reproduce

See the failed GitHub Action: https://github.com/easyops-cn/next-core/runs/4861762531?check_suite_focus=true

### Cypress Version

9.3.0

**Comment by robbtraister** [comment]
I just ran into the same issue. It seems as though the bin file is now using windows line-endings.

**Comment by n3ps** [comment]
We just ran into this too. v9.3.0 definitely broke our CI pipeline. 

Pinned to v9.2.1 for now and its working again.

**Comment by ryota-murakami** [comment]
same here
OSX 11.6 Node v16.13.0

**Comment by mjhenkes** [comment]
I can confirm that some how the package got released with a CRLF line endings in the bin file instead of LF line endings.

This is exactly the problem we're seeing.

https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

**Comment by tbiethman** [comment]
cypress@9.3.1 has been released correcting this issue. Thank you for your patience everyone.
