### ISSUE TITLE
`undefined (reading 'undefined')` on cypress_runner.js

### ISSUE THREAD

**Issue by thedoublejay** [cypress-io/cypress#19749]
### Current behavior

When running on `cypress@9.3.1`, there is an issue on `cypress_runner.js` - `Cannot read properties of undefined (reading 'undefined')`. It happens on https://github.com/cypress-io/cypress/blob/8355e5d8ec35411a6935687c9c91540dd32cf7f4/packages/driver/src/cy/navigation.ts#L29

![image](https://user-images.githubusercontent.com/25013382/150078043-d8a8a72c-72d6-4a4a-b6ca-42aef2b4f5cb.png)

This error usually happens on `cy.go('back')`. Failing tests on Cypress dashboard - https://dashboard.cypress.io/projects/oqk3fk/runs/4680/overview

### Desired behavior

No undefined error messages

### Test code to reproduce

 it('should return to previous page', function () {
    cy.go('back')
 })

### Cypress Version

9.3.1

**Comment by jennifer-shehane** [comment]
@thedoublejay 

- What version of Chrome are you using?
- Does this work in Cypress 9.1.1?

I do see some changes around this code that was released in 9.2.0: https://github.com/cypress-io/cypress/commit/ec84f660be3ceccaba0cab355e9e2624e0ad6902

**Comment by tbiethman** [comment]
@jennifer-shehane I am able to reproduce this back to 9.2.0 in both Electron and Chrome. 9.1.1 does not show this specific issue.

Still investigating, but we either need more checks around [this logic](https://github.com/cypress-io/cypress/commit/ec84f660be3ceccaba0cab355e9e2624e0ad6902#diff-7cbe95bf81f4c0f5ad2dd065d8771cd8415f97556335efd1d34a039f499d4b72R21-R27) or need to be more selective on when we execute it.

**Comment by thedoublejay** [comment]
@jennifer-shehane Yes it was working with `9.1.1`. It was also working for `9.2.0` for us (Chrome 96). Our current Chrome version is Chrome 97.

**Comment by Hypercubed** [comment]
@thedoublejay Thank you for posting this... helped me narrow down an issue that was really bothering us.  For Cypress team I'd like to point out that this error includes the message "The following error originated from your application code, not from Cypress." which really lead us astray!!

**Comment by raulfdm** [comment]
For the record, I'm having the exact same issue with `cy.go('back')` after upgrading from `9.1.1` to `9.3.1`.

We have a test that navigate between 2 pages and we assert about keeping some query params in the URL after `cy.go('back')`.

After upgrade cypress this test stoped working. `go back` seems not working well, sometimes it throws this error, sometimes it **does not** go back, and rarely it works as it should.

My workaround would be navigating back twice (`cy.go('back'); cy.go('back');`) to ensure that at least we can navigate back and suppress this exact error message.

**Comment by crappylime** [comment]
We also have the same issue with `cy.go('back')` in versions 9.2.0 - 9.4.1.
It works in 9.1.1 (Chrome 98) and older versions.

**Comment by sKavanaghV** [comment]
Seeing the same at Cypress 9.2.0 w/ Chrome 98

**Comment by sainthkh** [comment]
I tried to reproduce the problem with the code below, but failed:

```js
it('should return to previous page', function () {
  cy.visit('https://example.cypress.io')
  cy.contains('Querying').click({ force: true })
  cy.go('back')
})
```

**Comment by emilyrohrbough** [comment]
> We have a test that navigate between 2 pages and we assert about keeping some query params in the URL after cy.go('back').

After upgrade cypress this test stoped working. go back seems not working well, sometimes it throws this error, sometimes it does not go back, and rarely it works as it should.

It sounds like the behavior you are describing is a bit unrelated to the original issue. There is a PR out to fix the error reported. If this change doesn't resolve your issues, can you open a new issue with a reproducible example we can use to narrow down the issue you are seeing?
