### ISSUE TITLE
Documentation typo on the cy.get() page

### ISSUE THREAD

**Issue by nothingismagick** [cypress-io/cypress#1974]
I don't know how things use to be with v2, but on v3.0.1 `cy.fixtures` is not available.

https://docs.cypress.io/api/commands/get.html#Alias

![screen shot 2018-06-18 at 02 42 22](https://user-images.githubusercontent.com/35242872/41513759-448048a4-72a1-11e8-8907-a81f354b4bfd.png)

**Comment by Bkucera** [comment]
This should be `cy.fixture`, seems like a typo, I'll move this issue to the docs repo.

**Comment by jennifer-shehane** [comment]
Link to docs issue: https://github.com/cypress-io/cypress-documentation/issues/718
