### ISSUE TITLE
Cypress intercept method fails when modifying the response for a Stoplight Prism mock server

### ISSUE THREAD

**Issue by endigo9740** [cypress-io/cypress#19741]
### Current behavior

We currently use Stoplight's Prism tool, which generates a mock server against an OpenAPI spec:
https://stoplight.io/open-source/prism/

We have a particular endpoint that we would like to test, by intercepting and modifying only one value within the response. In order to to this, we've been attempting to follow the instructions here:
https://docs.cypress.io/api/commands/intercept#Response-object-properties

When we try to modify the full response, this works. For example:
```
cy.intercept('/example', {foo: 'bar'}).as('@httpGetExample`);
```

However, when we try to do this using the arrow function to inspect and modify the response values, this fails
```
cy.intercept('/example', (req) => {
    req.on('response', (res) => {
        res.send(res.body);
    })
}).as('@httpGetExample`);
```
Even with no modification to the body, just a simple passthrough like this, we see the following in browser:
* Status: 400 bad request
* Error Body: `error: {code: "invalid_json", message: "Invalid JSON"}`

I believe this error message to be coming from the mocked Prism server. Which immediately strikes me as strange since I'd think the handoff from the Prism mock server -> Cypress would have already occurred, correct? Prism should be out of the equation by this point if I'm using `req.on('response', ...)`. Am I correct in thinking that?

### Desired behavior

We would just love to be able to modify the response on the fly. Our current solution requires providing a fixture of the ENTIRE response (which is quite large and complex), modifying one key, then providing that as the full replacement body for the response. This is far from ideal.

### Test code to reproduce

Unfortunately I'm not sure if this would be easily reproduced. This would require the following:

* A generated OpenAPI spec
* Prism mock server running against the API spec
* A minimal application making an HTTP call to the mock server
* Cypress installed and a test spec written to intercept the call

If anyone can suggest a realistic means to do so, I'd appreciate it. But I understand our stack is outside of the norm here.

### Cypress Version

9.2.1

### Other

Another thought may be that our OpenAPI endpoint spec is malformed in some way that works well enough for the browser as is, but when intercepted by Cypress, is modified to the point it stops working.

However, realistically I think the problem is due to WHEN the modification occurs (what part of the lifecycle events). It seems that Prism is part of the exchange, where as we would like to modify the data in a later state. Ideally something like this:

* Mock server receives a request
* Mock server responds with appropriate response
* Cypress intercepts the data from the mock server, modifies the request <--- this!
* Cypress provides the modified request/response to the browser
* The web app utilized the modified call

Here's what we've settled on as our temporary work around:
```
cy.fixture('example.json').then((fixture) => {
    fixture.foo = 'bar';
    cy.intercept('/example', fixture).as('httpGetExample');
})
```

This works, but requires us to replicate our ENTIRE response as a fixture. Which will be harder to maintain over time. Especially when we just one a quick one-off change to a value.

Thanks for any help you can provide!

**Comment by endigo9740** [comment]
Quick follow up - I've confirmed I can modify the response using the documented methods for http calls outside of our mock server. I did the following:

* Implemented a call in my app to the JSON Placeholder API: https://jsonplaceholder.typicode.com/
* Intercepted the call, used the "pass through" method -> worked
* Intercepted the call, modified the response -> worked

Unfortunately that means our issue is specific to Cypress + Prism. If this it outside the scope of support I'd understand, but any suggestions are welcome!

**Comment by tbiethman** [comment]
@endigo9740 Can you validate the shape of the `res.body` in your passthrough example? Or is this error occurring prior to your response handler even executing? If the response handler is executing, Prism should be out of the equation.

When given a [single argument](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/net-stubbing/events/response.ts#L58), the `send()` API validates whether or not the given object represents a [StaticResponse](https://docs.cypress.io/api/commands/intercept#StaticResponse-objects) object or solely a request body. There might be a collision with the keys in the Prism response? Not sure why that would result in invalid rather than unexpected JSON, but it might be worth checking.

**Comment by endigo9740** [comment]
Per my understanding and testing (with another API source), the `res.body` just matches the original body data.

If the original request was `{foo: 'bar'}` then the pass through would return `{foo: 'bar'}` verbatim.

If you're asking per what our specific body response looks like, it's unfortunately fairly large. But he's the an example. I've only modified a couple private or identifying values within the strings. Structurally this should be 1:1...
```
{
    "id": 24,
    "name": "Another Quiz",
    "description": "This is a test quiz.",
    "branding": {
      "id": 13,
      "name": "Company Name",
      "logo_url": "https://example.com/organization/default/logo.png",
      "backsplash_url": "https://example.com/organization/default/backsplash.jpg"
    },
    "logo_url": "https://example.com/quiz/company/logo.png",
    "backsplash_url": "https://example.com/quiz/company/backsplash.jpg",
    "interstitial_urls": [
      "https://example.com/quiz/company/interstitial.jpg",
      "https://example.com/quiz/company/interstitial-1.jpg",
      "https://example.com/quiz/company/interstitial-2.jpg",
      "https://example.com/quiz/company/interstitial-3.jpg"
    ],
    "rewarded_video": "https://example.com/quiz/video.mp4",
    "rewarded_video_poster": "https://example.com/quiz/company/poster.jpg",
    "sponsor_url": "https://example.com/quiz/company/sponsor.jpg",
    "sponsor_link": "https://www.example.com",
    "sponsor_iframe": true,
    "conversion_iframe": true,
    "conversion_url": "https://example.com/quiz/company/conversion.jpg",
    "conversion_link": "https://www.example.com",
    "question_amount": 5,
    "organization": 13,
    "rewarded_video_interval": 10,
    "allow_attempts": true,
    "max_attempts": 10,
    "categories": [
      1,
      4
    ],
    "start_date": "2020-11-20T16:00:10.054000Z",
    "end_date": "2020-11-27T16:00:10.054000Z",
    "lifecycle_status": "active",
    "canceled_at": null
}
```

From what I can tell everything looks like standard/valid values. When not intercepted the calls complete in the browser as expected and the page populates as expected. FYI we're using Angular for this project; the templates render as expected when not intercepted.

Any pass through or modification of the response, specifically when using the arrow function in place of a static object for the replacement body, triggers the error though.

**Comment by endigo9740** [comment]
Another follow up - we've identified the issue to be a bug on Prism's end. I'm going to close this ticket and report the issue to them asap. Look for this on their Github issue tracker soon if you're encountering a similar issue.
