### ISSUE TITLE
Cypress.Cookies.debug() not logging anything

### ISSUE THREAD

**Issue by aryzing** [cypress-io/cypress#19745]
### Current behavior

Using `Cypress.Cookies.debug(true)` does not produce any logs when the electron browser is selected.

### Desired behavior

Logs should appear

### Test code to reproduce

Repo: https://github.com/aryzing/practice-cypress-cookies

Note, there are no failing tests b/c I can't make a test fail (or don't know how to) when logs aren't logged.

### Cypress Version

9.2.1

### Other

* Ubuntu 21.04
* Brave Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
* Firefox 96.0
* Node v17.1.0

https://user-images.githubusercontent.com/4924405/150016912-2fa6543d-c525-4c51-a4e0-b597546f3ca7.mp4

**Comment by tbiethman** [comment]
@aryzing Thank you for the reproduction. I see the same on Chrome/Firefox/Electron on macOS/node v16.

**Comment by lgschell** [comment]
I'm having the same issue, the Cypress.Cookies.debug(true) command is not printing any message on console's log. I'm currently using Cypress v12.1.0. Thank you

Expected behavior described here: https://docs.cypress.io/api/cypress-api/cookies#Syntax
