### ISSUE TITLE
Cypress 9.3.1 can't be installed via npm

### ISSUE THREAD

**Issue by Maw-Jung** [cypress-io/cypress#19755]
### Current behavior

Cypress tells me there is a new version available, which i can't find via npm
![image (2)](https://user-images.githubusercontent.com/27959981/150108881-df642d0f-67ce-4154-9ac5-b36d5cb32835.png)
```
npm install --save-dev cypress@9.3.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cypress@9.3.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/[userName]/.npm/_logs/2022-01-19T10_06_13_292Z-debug.log
```
![image (4)](https://user-images.githubusercontent.com/27959981/150108886-c8d2ad64-634f-4f18-9098-f76fa33f5977.png)

### Desired behavior

The new version shall be installable and mentioned on the "What's new" page

### Test code to reproduce

npm install --save-dev cypress@9.3.1

### Cypress Version

9.2.1

**Comment by Maw-Jung** [comment]
I just included the page due to the version being possibly false. I just tried again doing the install command (as in the update dialog in the runner) and the results are still the same. I use npm `6.14.15` on an opensuse tumbleweed. Please let me know, if more informations are needed and what i shall share.
Thanks,
Marcel

**Comment by tbiethman** [comment]
@Maw-Jung I am able to install and run cypress@9.3.1 from npm.

* Do you see 9.3.1 listed as the latest version when you run `npm view cypress` in your console? 
* Have you tried removing any present lock files and/or clearing your npm cache?

**Comment by Maw-Jung** [comment]
Thanks @tbiethman,
the version was indeed listed and i was now able to install it.
