### ISSUE TITLE
Repetitive actions execution question

### ISSUE THREAD

**Issue by uoziod** [cypress-io/cypress#1976]
I have some repetitive actions in my tests, so I moved them to a separate functions out of actual tests and calling them from tests assuming that they'd be executed just as bunch of commands:

```ts
describe( "Page one", () => {
    function one() {
      cy.get("...")
      ...
    }

    function two() {
      cy.get("...")
      ...
    }

    it( "Test 1", async () => {
      cy.get("...")

      one();
      two();
    }

    it( "Test 2", async () => {
      cy.get("...")

      one();
      two();
    }

    ...
```

Although in this particular case I see that functions `one` and `two` will be called only in `Test 2`, whereas `Test 1` will run only `cy.get("...`, then `Test 2` will start straight away.

Might be that I'm just approaching the problem from an incorrect way.
In any case, suggestions are much appreciated)

**Comment by uoziod** [comment]
Guys, is this expected behavior? Should I elaborate on details?
Seems like a bug to me, unless I doing it wrong.

**Comment by Bkucera** [comment]
@uoziod is there a reason for `async` ? You shouldn't need that

**Comment by uoziod** [comment]
Indeed. I've been using them for other purposes, but refactored code and now it works fine. Thanks for pointing out!

**Comment by brian-mann** [comment]
@uoziod yes, @Bkucera is right, you were mixing up async / Promise code with Cypress, which is never necessary. You also weren't returning like this `return one()` which would have meant the promisifed `async` test callback would not have awaited.

This is one of the reasons I don't like the idea of conforming to `async/await`. It's not necessary in Cypress, there's no reason to enforce it, and it creates a confusing mismatch between the two styles.
