### ISSUE TITLE
The cypress release process has the possibility to generate a package with a bin file with windows line endings.

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19771]
### Current behavior

The windows build of the cypress package will produce a binary with windows line endings. If this package is released it will cause issues like #19747.

### Desired behavior

Produce a binary without windows line endings.

### Test code to reproduce

In CI cause the windows build to run last and check out the generated package.

### Cypress Version

n/a

### Other

We have been lucky previously to not have seen this with either the darwin or linux build finishing last.

I believe issue was introduced with #8483, so it has been a possibility for some time.

Options for correction include:
Prevent windows from setting windows line endings when building.
Prevent windows from pushing the generated package to s3
Use linux to build the package and push it to s3 prior to generating the binary build jobs for each os.

**Comment by tgriesser** [comment]
> We have been lucky previously to not have seen this with either the darwin or linux build finishing last.

We didn't build Windows with Circle [until recently](https://github.com/cypress-io/cypress/issues/17962), so that might be why we haven't seen it?

**Comment by jennifer-shehane** [comment]
I don't think that would have affected the timing to make Windows be a slower build. The instance we saw, it seems the Darwin build finished earlier than usual. I think it has literally been luck for 16 months since https://github.com/cypress-io/cypress/pull/8483 was merged.
