### ISSUE TITLE
Spec glob seems to have broken in 9.3.1

### ISSUE THREAD

**Issue by nickbrook72** [cypress-io/cypress#19783]
### Current behavior

We use Bitbucket Pipelines for tests, and in order to run in parallel we split up the specs using simple globs. 
e.g:

`cypress run -s 'cypress/integration/[a-c]*/**`

This worked fine up till 9.3.0, but broke in 9.3.1 with the following error:

`Cypress encountered an error while parsing the argument spec

You passed: cypress/integration/[a-c]*/**

The error was: spec must be a string or comma-separated list`

### Desired behavior

It should pull in all the specs referenced by the glob i.e all specs beginning with a, b or c

### Test code to reproduce

cypress run -s 'cypress/integration/[a-c]*/**

### Cypress Version

9.3.1

### Other

You fixed a glob-related bug in 9.3.1: regression due to that?

**Comment by tbiethman** [comment]
@nickbrook72 Thank you for reporting. I am able to reproduce with the provided command and will look into the 9.3 changes around this: 273b7035b09bc763b6d398a848c67a474ba37545
