### ISSUE TITLE
Setting CYPRESS_ENV to something other than production returns a cryptic error

### ISSUE THREAD

**Issue by MichaelHindley** [cypress-io/cypress#1978]
### Current behaviour:
If you invoke `cypress.run()` with `record: true` with the `CYPRESS_ENV` env variable set to something different than `production`, Cypress will fail with a cryptic message:

```
Warning: We encountered an error talking to our servers.

This run will not be recorded.

This error will not alter the exit code.

RequestError: Error: Invalid URI "/runs"
```

### Desired behavior:
```
Warning: You are trying to record a test run in a non-production environment.  
This is not supported and this run will not be recorded.

Check the CYPRESS_ENV variable if behaviour is undesirable in the context of this run.

This warning will not alter the exit code.
```

### Steps to reproduce:
Run Cypress with `CYPRESS_ENV` set to something like `dev`, with `record: true` and `key: 'key'`

### Versions
3.0.1 on
* macOS 10.13.5
* Debian 8

**Comment by jennifer-shehane** [comment]
What are you trying to achieve by setting the `CYPRESS_ENV` key to `dev`? 

`CYPRESS_ENV` is an internal key used by Cypress and I thought we had updated the error messages to better handle this @bahmutov - but this is a very cryptic error message.

**Comment by brian-mann** [comment]
This is actually already in a PR and is a duplicate issue. https://github.com/cypress-io/cypress/pull/1626

https://github.com/cypress-io/cypress/issues/1621

**Comment by MichaelHindley** [comment]
Ah great :)

@jennifer-shehane was thinking about using it to match our general environments such as dev, test, stage, prod and ran into this issue- didn't realise it's not ment to be used when consuming, thanks for the heads up! 👍
