### ISSUE TITLE
Cypress 9.3.1 Fails/Errors When Attempting Any Test

### ISSUE THREAD

**Issue by fugazi** [cypress-io/cypress#19787]
### Current behavior

Today I've updated to Cypress 9.3.1 but once I am running 'npx cypress open' and the dashboard is displayed, I am getting an error when attempting any test.
![cypress-error](https://user-images.githubusercontent.com/403366/150378122-bea8ba8a-82aa-423f-ab35-8cfb16b211ca.jpg)

Note: I've downgraded to version 9.2 and all tests are running pretty well.

The log error is:
`The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (C:\.\.\.\cypress\plugins\index.js)`

 **Error: error:0308010C:digital envelope routines::unsupported**

Stack trace:
`Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file`

### Desired behavior

All tests **.spec.js** should run properly.

### Test code to reproduce

npx cypress open
Click on any test from the dashboard

### Cypress Version

9.3.1

### Other

Note: I've downgraded to version 9.2 and all tests are running pretty well.

Windows version: 11
Node version: 17.0.1
Npm version: 8.3.0

**Comment by tbiethman** [comment]
@fugazi Thank you for the report. #19712 is tracking the same issue. Please see that issue for more info and updates.
