### ISSUE TITLE
The `.selectFile` command does not work from an aliased fixture

### ISSUE THREAD

**Issue by wlsf82** [cypress-io/cypress#19803]
### Current behavior

The file is not selected when using an aliased fixture, as follows on the docs of the new `.selectFile` command (on the [**From a fixture**](https://docs.cypress.io/api/commands/selectfile#From-a-fixture) section.)

### Desired behavior

The file should correctly be selected from an aliased fixture.

### Test code to reproduce

https://github.com/wlsf82/cy-hands-on-select-file/blob/main/cypress/integration/selectFile.spec.js#L21

**Note:** To test it out, change the test from `.skip()` to `.only()`.

### Cypress Version

9.3.1

### Other

Here is a screenshot of the failure.

![cy handsOn( selectFile) -- selects a file for upload using an aliased fixture (failed)](https://user-images.githubusercontent.com/2768415/150441710-fc9948f6-abff-48d8-99b0-9b046828b4d8.png)

**Comment by BlueWinds** [comment]
The current implementation stores the fixture file _contents_, but does not persist the file _name_ when you alias it - which your test is asserting on.

This isn't a great experience, and we'll be resolving it in 9.4.0 - the fixture filename will be preserved through an alias. I'll have a PR up in a few minutes here.
