### ISSUE TITLE
cy.request() with followRedirects sometimes is ignored.

### ISSUE THREAD

**Issue by rrauenza** [cypress-io/cypress#19804]
### Current behavior

I have a login command that I used beforeEach test.  It almost always works, except sometimes it doesn't.  When it doesn't, I seem to see the additional GET's caused by the redirect.

 ```
cy.request({method: 'POST', url: 'api/rest/accounts/login/', followRedirect: false, body: {username: username, password: password}}).then(
    (response) => {
      expect(response.status).to.eq(200);
      const jwt = JSON.stringify(response.body.jwt);
      window.localStorage.setItem('jwt', jwt);
      expect(window.localStorage.getItem('jwt')).to.eq(jwt);
    }
  );
```

Good case:

![image](https://user-images.githubusercontent.com/1376251/150450040-8e0612e9-4fbc-4a5c-99fd-82583b671034.png)

Bad case:

![image](https://user-images.githubusercontent.com/1376251/150450132-10799e0f-1733-4640-ab91-941f069f1a9a.png)

### Desired behavior

followRedirect should always do the same thing as directed.

### Test code to reproduce

```
cy.request({method: 'POST', url: 'api/rest/accounts/login/', followRedirect: false, body: {username: username, password: password}}).then(
    (response) => {
      expect(response.status).to.eq(200);
      const jwt = JSON.stringify(response.body.jwt);
      window.localStorage.setItem('jwt', jwt);
      expect(window.localStorage.getItem('jwt')).to.eq(jwt);
    }
  );
```

This is going to be hard to reproduce.  Even in my environment it seems to happen fairly rarely per it(), but at least once per cicd run.

### Cypress Version

9.3.0

**Comment by pi3natt** [comment]
Also found at version 11.1.0
