### ISSUE TITLE
Incorrect test output. 2 tests failed but all listed as passing

### ISSUE THREAD

**Issue by Elzebub** [cypress-io/cypress#19810]
### Current behavior

![Incorrect output](https://user-images.githubusercontent.com/2094394/150508293-b4842d72-2627-4b74-ac06-feb69e1e0f0b.jpg)

### Desired behavior

The test summary should list 2 tests as having failed. 

### Test code to reproduce

 Not sure

### Cypress Version

9.2.0

**Comment by Narretz** [comment]
Are you sure? The screenshot says "Attempt 1 of 4" for two tests. This means the two tests failed once, but passed in the first retry. Cypress still saves screenshots of failed attempts.

**Comment by Elzebub** [comment]
Ok that makes sense. What is confusing is that when running against Electron in a Github action within a Linux environment and reporting up to Cypress.io these 2 tests DO actually fail whereas in Windows Powershell they do not as you pointed out. Is there anything I can do to ensure the results in Linux are closer aligned to the results in Windows? Sorry I'm not that familiar with Linux.

**Comment by Elzebub** [comment]
Thanks for pointing that out. Closing.
