### ISSUE TITLE
TypeError: net.isIP is not a function

### ISSUE THREAD

**Issue by Andy-2018** [cypress-io/cypress#1981]
### Current behavior:

When trying to connect to SQL Server database using module mssql, this error "net.isIP is not a function" happens.

See this link https://github.com/tediousjs/node-mssql/issues/516 for details.  I linked it here as I think this is an issue in Cypress.

### Versions

Windows 10, Cypress 3.0.1 + mssql 4.1.0.

**Comment by brian-mann** [comment]
You didn't post any code in here, which is something we ask for when opening a new issue, so we can help you and don't have to guess at what you're trying to do.

With that said, I am virtually 100% sure you are trying to require the `mssql` node library into your spec files. Your spec files run in the browser, not in node. It's not possible to make a connection to an SQL database out of the browser. You must do this in node.

You can use the new `cy.task` API to pass messages to the background node process if you want to do things like seed your DB or create records, query for stuff, etc.

**Comment by brian-mann** [comment]
See these other issues:

- https://github.com/cypress-io/cypress/issues/1963
- https://github.com/cypress-io/cypress/issues/1358
- https://github.com/cypress-io/cypress/issues/482
