### ISSUE TITLE
Error in cypress"Constructor is not a constructor" during a .click()

### ISSUE THREAD

**Issue by uncontrol21** [cypress-io/cypress#19814]
### Current behavior

I am experiencing the "Constructor is not a constructor" error on Cypress version 9.3.1. It appears when I identify a button and try to click on it. Error "TypeError Timed out retrying after 4050ms: Constructor is not a constructor"

![HXWiI](https://user-images.githubusercontent.com/20306535/150531699-a88b16b0-7a27-4bdd-acdb-5c99f8431f09.png)

### Desired behavior

I am expecting the button to be clicked without errors.

### Test code to reproduce

        describe('authorization ', () => {
        it('login_page', () => {
        cy.fixture('VirtualMachines').then(data => {

            cy.visit(data.vmware_url)

            cy.get('.btn').click();

            cy.get('#username').clear();
            cy.get('#username').type(data.loginVM);

            cy.get('#password').clear();
            cy.get('#password').type(data.passwordVM);

            cy.get('#submit').click();
            
            cy.xpath('//*[@id="clr-tab-link-8"]').should('be.visible').click();
            cy.get('button[class="tid-app-folder-vms btn btn-link nav-link"]').should('be.visible').click();
            cy.get('#clr-tab-link-8').should('be.visible').click();
        })
    })
    })

### Cypress Version

9.3.1 

### Other

error appears when determining through cy.get and cy.xpath
Operating system: win10 
Browser: Chrome 97.0.4692.71 / fiirefox 96.0.1
html code:
<img width="558" alt="html" src="https://user-images.githubusercontent.com/20306535/150533462-82f842f8-e3c4-4ac4-8528-68051ea804ff.PNG">

**Comment by tbiethman** [comment]
@uncontrol21 Can you provide a minimal reproducible example? An easy way to start with that is by forking the [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny).
