### ISSUE TITLE
[Multi-domain]: Handle uncaught errors in the spec bridge

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19858]
### What would you like?

Throwing errors in timeout functions should be appropriately handled

```js
it('handles errors in timeout callbacks' , () => {
  cy.switchToDomain('foobar.com', () => {
    setTimeout(() => {
        throw 'error'
    })
  })
})
```

### Why is this needed?

Uncaught errors and promise rejections in the spec itself should be caught and fail the test with the right error message.

### Other

The discussion around command naming and possible command combination has not been resolved. Keep this in mind when implementing.

**Comment by mschile** [comment]
Closing with 4070270
