### ISSUE TITLE
DrawLine or shapes feature

### ISSUE THREAD

**Issue by scsannalli** [cypress-io/cypress#19863]
### What would you like?

To accomplish signature simulation using automation. 
 I'm looking for an api which can used to draw lines or shapes. 
Right now I'm just able to put a dot in signature window. 

something cy.get().draw(options)  will help a lot

### Why is this needed?

To accomplish signature simulation using automation.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest, we’ll close this issue.

**Comment by emebet12** [comment]
I'd like to simulate a signature, to draw a line on cypress UI automation. Is there any feature to draw a signature?
