### ISSUE TITLE
 Cypress selectFile() command doesn't support .pdf files

### ISSUE THREAD

**Issue by khashaba** [cypress-io/cypress#19864]
### Current behavior

After doing the upgrade to [v9.3.1](https://github.com/cypress-io/cypress/releases/tag/v9.3.1) I migrated to ```selectFile()```
using the[ migration guid](https://docs.cypress.io/guides/references/migration-guide#Migrating-from-cypress-file-upload-to-selectFile).

After finishing the migration I found that ```selectFile()``` command is working with ```.png``` and ```.jpg``` but it's not working with ```.pdf``` files. "knowing that the path is correct as I prefixed the path with cypress/fixtures/"

It doesn't throw any errors, but the uploaded file is corrupted. it keeps loading forever when I click to preview it

FYI: I tried uploading the ``.pdf`` manually and it works but not with cypress automation 

### Desired behavior

Should be able to upload ``.pdf`` files

### Test code to reproduce

`    cy.get("#myInput").selectFile(pdfPath);`

### Cypress Version

9.3.1

**Comment by khashaba** [comment]
I have a normal input - but invisible so I have to use ``force`` -
I think it's the same issue as #19751

**Comment by tbiethman** [comment]
@khashaba Can you verify whether the mimeType changes that released with [9.4.0](https://docs.cypress.io/guides/references/changelog#9-4-0) correct the issue you were seeing?

@cheukribbon ^ Same question :) If not, please log a new issue following the issue template so we can track it properly.

**Comment by cheukribbon** [comment]
@tbiethman that did not work for me.

**Comment by anatolie-darii** [comment]
@cheukribbon @khashaba 
in case you guys still have issues I managed to make it work by doing this:
`
cy.fixture('myFile.pdf', null)
    .then(Cypress.Buffer.from)
    .then(contents =>
        cy.get('.file-input')
            .should('be.enabled')
            .selectFile({
                contents,
                fileName: fileName,
                lastModified: Date.now(),
                mimeType: 'application/pdf',
            }),
    )
`

**Comment by wlsf82** [comment]
To me it works perfectly.

![Uploading 5491B6D5-D87A-47B6-81EA-A732AA834A59.jpeg…]()

**Comment by wlsf82** [comment]
For me, it works perfectly.

I used Cypress v12.0.2

![0803B11A-8143-4CDF-8CC7-CB382B89D602](https://user-images.githubusercontent.com/2768415/215124773-c6a3f5ff-37ec-499b-b44d-fc78fd96397c.jpeg)

**Comment by ORicardoSouza** [comment]
With the support and guidance of @wlsf82, I managed it that way and he teaches in this video
"cypress": "^12.4.0",

```
 cy.get('#file')
        .selectFile('cypress/fixtures/nomeArquivo.pdf', { action: 'drag-drop', force: true })
        .then(input => {
            expect(input[0].files[0].name).to.equal('nomeArquivo.pdf')
})
```
        
       [Aula](https://youtu.be/xwltoOnmfVE) 
       by TAT

**Comment by alexsch01** [comment]
Not an issue for me

cy.get(selector).selectFile('filename.pdf')  just works

I checked the file on the other side and the PDF is fine

**Comment by nagash77** [comment]
I am going to close this issue as it is quite old at this point.  If folks are seeing this behavior in current versions of Cypress please open a new ticket with a reproducible example and we will be happy to investigate.

**Comment by Xsasan** [comment]
I had the same issue with corrupted PDF file when I try to work with the uploaded file in the backend. I had to add `encoding: null` to the command to get the unbuffered original file:

```
  cy.fixture(fileName, { encoding: null }).as('myFixture');
  return cy.get('input[type=file]').selectFile('@myFixture');
```

As stated on the documentation (https://docs.cypress.io/api/commands/fixture), `.pdf` is not a supported extension:

> For other types of files, they will be read as utf8 by default, unless specified in the second argument of cy.fixture(). You can specify null as the encoding in order to read the file as a [Cypress.Buffer](https://docs.cypress.io/api/utilities/buffer) instance instead.
