### ISSUE TITLE
[Multi-origin]: Analyze the cross-origin driver bundle

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19888]
### What would you like?

Analyze the size of the cross-origin driver bundle - to allow us to schedule refactor driver as necessary so no un-needed code is included in bundle.

### Why is this needed?

Increased efficiency for testing is important.

**Comment by mschile** [comment]
Ran the [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) for both the `cypress_runner.js` and `cypress_cross_origin_runner.js` with the following optoins:

`new BundleAnalyzerPlugin({ analyzerMode: 'json', reportFilename: 'cypress_runner-stats.json' }),`
`new BundleAnalyzerPlugin({ analyzerMode: 'json', reportFilename: 'cypress_cross_origin_runner-stats.json' }),`

[runner-stats.zip](https://github.com/cypress-io/cypress/files/8575571/runner-stats.zip)

# cypress_cross_origin_runner.js
<img width="3275" alt="Screen Shot 2022-04-27 at 12 46 19 PM" src="https://user-images.githubusercontent.com/2002044/165597777-0d882427-925d-4311-a008-0273538569b3.png">

# cypress_runner.js
<img width="3272" alt="Screen Shot 2022-04-27 at 12 46 57 PM" src="https://user-images.githubusercontent.com/2002044/165597866-82a251a7-9937-4932-ad3e-5d2b460ab173.png">
