### ISSUE TITLE
Google Autocomplete Infinity Loading and not showing results

### ISSUE THREAD

**Issue by jasminhusadzic** [cypress-io/cypress#19895]
### Current behavior

Autocomplete does not show any results.

### Desired behavior

Autocomplete should show results.

### Test code to reproduce

describe('test', () => {
    
    it('test apfm', () => {

        cy.visit('https://www.aplaceformom.com/')
        cy.get('[data-au-id="leadform-location-search-input"]')
            .should('exist')
            .click()
            .clear()
            .type(90210)
    })
})

### Cypress Version

9.3.1.

**Comment by jasminhusadzic** [comment]
![image](https://user-images.githubusercontent.com/30021518/151059229-96d4d0ef-6162-4e47-ba52-2fa336725374.png)

**Comment by tbiethman** [comment]
@jasminhusadzic The error I get from your provided test case (that seems to align with the one in your screenshot) is:

> Event:      uncaught exception
index.01ca4225.js:32777 Caught by:  "error" handler
index.01ca4225.js:32777 Error:      TypeError: Cannot read properties of undefined (reading 'getPlacePredictions')
    at t.n.fetchPredictions (_app-a3ac8436e0110bb0580c.js:formatted:22473:43)
    at g (_app-a3ac8436e0110bb0580c.js:formatted:12405:23)
    at x (_app-a3ac8436e0110bb0580c.js:formatted:12427:26)
    at S (_app-a3ac8436e0110bb0580c.js:formatted:12419:28)
    at i ((index):1:1459)
    at (index):1:1832

This exception is not being thrown by Cypress but site under test. Can you confirm this is what you're seeing locally?

**Comment by jasminhusadzic** [comment]
@tbiethman Yes, those errors. But what is interesting, that error i do not have with other tools or even manually, only when i try with Cypress.

**Comment by tbiethman** [comment]
@jasminhusadzic That is interesting. I recommend using some breakpoints in the site under test to see why that is turning up undefined during your test run and narrow down the potential issues.

**Comment by jasmin-husadzic-apfm** [comment]
@tbiethman Thanks for support. We can close this issue now. Thank you again.

**Comment by jasminhusadzic** [comment]
@tbiethman Thanks for support. We can close this issue now. Thank you again.
