### ISSUE TITLE
[Multi-domain]: Mark chromeWebSecurity as deprecated

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19892]
### What would you like?

When the experimental flag is enabled, mark chromeWebSecurity as deprecated in config.

### Why is this needed?

ideally chromeWebSecurity would not be set to false when testing.

**Comment by mschile** [comment]
According to our [docs](https://docs.cypress.io/guides/guides/web-security#Set-chromeWebSecurity-to-false), disabling `chromeWebSecurity` is used in the following scenarios:

```
Setting chromeWebSecurity to false in Chrome-based browsers allows you to do the following:

- Display insecure content
- Navigate to any superdomain without cross-origin errors
- Access cross-origin iframes that are embedded in your application

```

> - Display insecure content

Can be handled by setting `--allow-running-insecure-content` in the launch options

> - Navigate to any superdomain without cross-origin errors

Can be handled using `cy.origin`

> - Access cross-origin iframes that are embedded in your application

No support yet but on the plan.


We shouldn't deprecate `chromeWebSecurity` until we support cross-origin iframes.
