### ISSUE TITLE
More reliably determine CI Provider

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1990]
### Current behavior:

Some CI Providers show up as "unknown" with a suspected large amount of Jenkins CI runs going reported as "unknown"

### Desired behavior:

@RandallKent mentioned this package may be helpful in determining the CI provider. 
- https://www.npmjs.com/package/ci-info

Update the current code to use package instead of env keys. 

Link to current code: https://github.com/cypress-io/cypress/blob/issue-1942/packages/server/lib/util/ci_provider.coffee#L12

### Versions

Cypress 3.0.1

**Comment by brian-mann** [comment]
That package won't help with jenkins. It's more restrictive than our current check.

**Comment by brian-mann** [comment]
The only way to figure this out is spin up a jenkins instance and go look at it. It's obviously not setting what it's documented to say it sets...

https://wiki.jenkins.io/display/JENKINS/Building+a+software+project

**Comment by chrisbreiding** [comment]
I set up a Jenkins Docker instance, ran `env` and this is the output:

```
JENKINS_HOME=/var/jenkins_home
JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
RUN_CHANGES_DISPLAY_URL=http://localhost:8080/job/test/1/display/redirect?page=changes
HOSTNAME=417aade22af6
NODE_LABELS=master
HUDSON_URL=http://localhost:8080/
SHLVL=0
HOME=/var/jenkins_home
BUILD_URL=http://localhost:8080/job/test/1/
HUDSON_COOKIE=26651f26-d73d-4da8-ae6d-e4893ce3a8be
JENKINS_SERVER_COOKIE=5c0de994b3c8ec8b
JENKINS_UC=https://updates.jenkins.io
WORKSPACE=/var/jenkins_home/workspace/test
JAVA_VERSION=8u171
NODE_NAME=master
CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1
EXECUTOR_NUMBER=1
JENKINS_VERSION=2.121.1
BUILD_DISPLAY_NAME=#1
HUDSON_HOME=/var/jenkins_home
JOB_BASE_NAME=test
JAVA_DEBIAN_VERSION=8u171-b11-1~deb9u1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BUILD_ID=1
BUILD_TAG=jenkins-test-1
LANG=C.UTF-8
JENKINS_URL=http://localhost:8080/
JOB_URL=http://localhost:8080/job/test/
BUILD_NUMBER=1
RUN_DISPLAY_URL=http://localhost:8080/job/test/1/display/redirect
JENKINS_SLAVE_AGENT_PORT=50000
HUDSON_SERVER_COOKIE=5c0de994b3c8ec8b
JOB_DISPLAY_URL=http://localhost:8080/job/test/display/redirect
JOB_NAME=test
COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
JAVA_HOME=/docker-java-home
PWD=/var/jenkins_home/workspace/test
```

`JENKINS_URL` is there, so I assume this run would be detected as Jenkins. We could try also looking for some of the other `JENKINS_*` variables to be safe:

* JENKINS_HOME
* JENKINS_SERVER_COOKIE
* JENKINS_UC
* JENKINS_VERSION
* JENKINS_SLAVE_AGENT_PORT

**Comment by brian-mann** [comment]
This is good. Can you please add `JENKINS_HOME` and `JENKINS_VERSION` to the checks?

Also can you setup a recorded run on the dashboard and make sure it works?
