### ISSUE TITLE
Inconsistencies in CYPRESS_DOWNLOAD_PATH_TEMPLATE handling

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#19914]
### Current behavior

There seem to be some inconsistencies in how CYPRESS_DOWNLOAD_PATH_TEMPLATE is handled from the .npmrc file depending on package manager and version.

Given
`CYPRESS_DOWNLOAD_PATH_TEMPLATE=${endpoint}/${platform}-${arch}/cypress.zip`

npm 7 works, though locally i've seen the env fail to get picked up because of casing.
npm 6 attempts to replay endpoint etc with other ENVs (this is unfortunate, but you can escape them but that doesn't work either)
Yarn 1 doesn't remove double quotes.

I haven't tested yarn 3 or npm 8 but they should be looked at, as well as windows useage.

### Desired behavior

Ideally you could set the CYPRESS_DOWNLOAD_PATH_TEMPLATE variable with any package manager

### Test code to reproduce

Try out setting variations of

```sh
CYPRESS_DOWNLOAD_PATH_TEMPLATE=${endpoint}/${platform}-${arch}/cypress.zip
CYPRESS_DOWNLOAD_PATH_TEMPLATE=\${endpoint}/\${platform}-\${arch}/cypress.zip
CYPRESS_DOWNLOAD_PATH_TEMPLATE="${endpoint}/${platform}-${arch}/cypress.zip"
CYPRESS_DOWNLOAD_PATH_TEMPLATE="\${endpoint}/\${platform}-\${arch}/cypress.zip"
```

### Cypress Version

9.3.1

### Other

Where CYPRESS_DOWNLOAD_PATH_TEMPLATE is used
https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/download.js#L67

getEnv implementation
https://github.com/cypress-io/cypress/blob/develop/cli/lib/util.js#L459

We should probably be setting trim on getENV, that should resolve any double quotes problems.

**Comment by amoshydra** [comment]
backslash is very uncommon in URL. Would it be reasonable to escape backslash specifically for `CYPRESS_DOWNLOAD_PATH_TEMPLATE` in current version?

https://github.com/cypress-io/cypress/blob/v9.3.1/cli/lib/tasks/download.js#L69-L72

### Proposal:
```diff
  const prepend = (urlPath) => {
    const endpoint = Url.resolve(getBaseUrl(), urlPath)
    const platform = os.platform()
    const pathTemplate = util.getEnv('CYPRESS_DOWNLOAD_PATH_TEMPLATE')
  
    return pathTemplate
-     ? pathTemplate.replace('${endpoint}', endpoint).replace('${platform}', platform).replace('${arch}', arch())
+     ? pathTemplate.replace(/\\?\$\{endpoint\}/, endpoint).replace(/\\?\$\{platform\}/, platform).replace(/\\?\$\{arch\}/, arch())
      : `${endpoint}?platform=${platform}&arch=${arch()}`
}
```

### Test snippet

```js
output = (pathTemplate) => {
    const endpoint = 'endpoint';
    const platform = 'platform';
    const arch = () => 'arch';

    const codeFn = () => {
        return pathTemplate
            ? pathTemplate.replace(/\\?\$\{endpoint\}/, endpoint).replace(/\\?\$\{platform\}/, platform).replace(/\\?\$\{arch\}/, arch())
            : `${endpoint}?platform=${platform}&arch=${arch()}`;
    };

    console.log(`input : ${pathTemplate}`);
    console.log(`output: ${codeFn()}`);
};

output("\\${endpoint}/\\${platform}-\\${arch}/cypress.zip");
// input : \${endpoint}/\${platform}-\${arch}/cypress.zip
// output: endpoint/platform-arch/cypress.zip

output("${endpoint}/${platform}-${arch}/cypress.zip");
// input : ${endpoint}/${platform}-${arch}/cypress.zip
// output: endpoint/platform-arch/cypress.zip
```

**Comment by amoshydra** [comment]
I have done additional research in Windows 10 comparing the behaviour for 
- npm@6
- npm@7
- npm@8
- yarn@1


| cli          | npmrc                                              | cypress input
| --           | --                                                 | --
| npm@6.14.16  | `${endpoint}/${platform}-${arch}/cypress.zip`      | Error: Failed to replace env in config: ${endpoint}
| npm@6.14.16  | `\${endpoint}/\${platform}-\${arch}/cypress.zip`   | `\${endpoint}/\${platform}-\${arch}/cypress.zip`
| npm@6.14.16  | `"${endpoint}/${platform}-${arch}/cypress.zip"`    | Error: Failed to replace env in config: ${endpoint}
| npm@6.14.16  | `"\${endpoint}/\${platform}-\${arch}/cypress.zip"` | Error: Failed parsing JSON config key
| --           | --                                                 | --
| npm@7.24.2   | `${endpoint}/${platform}-${arch}/cypress.zip`      | `${endpoint}/${platform}-${arch}/cypress.zip`
| npm@7.24.2   | `\${endpoint}/\${platform}-\${arch}/cypress.zip`   | `${endpoint}/${platform}-${arch}/cypress.zip`
| npm@7.24.2   | `"${endpoint}/${platform}-${arch}/cypress.zip"`    | `${endpoint}/${platform}-${arch}/cypress.zip`
| npm@7.24.2   | `"\${endpoint}/\${platform}-\${arch}/cypress.zip"` | `"${endpoint}/${platform}-${arch}/cypress.zip"`
| --           | --                                                 | --
| npm@8.5.5    | `${endpoint}/${platform}-${arch}/cypress.zip`      | `${endpoint}/${platform}-${arch}/cypress.zip`
| npm@8.5.5    | `\${endpoint}/\${platform}-\${arch}/cypress.zip`   | `${endpoint}/${platform}-${arch}/cypress.zip`
| npm@8.5.5    | `"${endpoint}/${platform}-${arch}/cypress.zip"`    | `${endpoint}/${platform}-${arch}/cypress.zip`
| npm@8.5.5    | `"\${endpoint}/\${platform}-\${arch}/cypress.zip"` | `"${endpoint}/${platform}-${arch}/cypress.zip"`
| --           | --                                                 | --
| yarn@1.22.18 | `${endpoint}/${platform}-${arch}/cypress.zip`      | Failed to replace env in config: ${endpoint}
| yarn@1.22.18 | `\${endpoint}/\${platform}-\${arch}/cypress.zip`   | `\${endpoint}/\${platform}-\${arch}/cypress.zip`
| yarn@1.22.18 | `"${endpoint}/${platform}-${arch}/cypress.zip"`    | Failed to replace env in config: ${endpoint}
| yarn@1.22.18 | `"\${endpoint}/\${platform}-\${arch}/cypress.zip"` | `"\${endpoint}/\${platform}-\${arch}/cypress.zip"`

* Not familiar with yarn2 or yarn 3 yet. Not sure how this can be tested.

From the findings above, cypress will need to be able to handle 3 cases:
1. `${endpoint}/${platform}-${arch}/cypress.zip`
1. `\${endpoint}/\${platform}-\${arch}/cypress.zip`
1. `"\${endpoint}/\${platform}-\${arch}/cypress.zip"`

---

All three cases will be address in #20698 @ 6c74734
