### ISSUE TITLE
Dashboard: Add an AND relation for tags filter

### ISSUE THREAD

**Issue by xvyslo05** [cypress-io/cypress#19930]
### What would you like?

When I have multiple tags for single run and I want to filter them (for example i want to filter only `stage` AND `nightly` tag), the relation between tags is OR. This makes impossible to filter more specific runs.

![image](https://user-images.githubusercontent.com/22894514/151335457-d8fa66c1-34b4-4de0-9236-43c2196a69dd.png)
⬆️ this is the state after I set the filter to `nightly`, `stage`, `smoke`.

Desired behavior would be to choose between AND and OR relation, when filtering tags, or just change it to AND.

### Why is this needed?

For better user experience, when filtering in Dashboard.

**Comment by tbiethman** [comment]
@xvyslo05 Thanks for reaching out. I've raised this feature request internally with our Dashboard team. We do not track Dashboard features here, so I'm going to close this issue.
