### ISSUE TITLE
Don't truncate urls of network requests

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1995]
Notice `cy.visit` url is not shortened like the XHRs. 

The logs shouldn't truncate XHR urls as much becuase this is useful information for the user for ensuring the correct route was aliased, and the logs give the assumption that the url is not very important

![image](https://user-images.githubusercontent.com/14625260/41687210-d383aaae-74b4-11e8-9e46-27787e4a1498.png)

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
