### ISSUE TITLE
Consider chrome.tabCapture for video recording in Chromium

### ISSUE THREAD

**Issue by BlueWinds** [cypress-io/cypress#19958]
### What would you like?

Our video capture code currently relies on CDP's [screencasting](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast), which captures the tab as a png or jpeg and base64 encodes it. We pas this on to the server, which then [pipes it into ffmpeg](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/video_capture.ts) in slideshow mode.

This is not terribly efficient - a series of still images is extremely large compared to a properly encoded video, and the current process taxes the CPU on low-resourced VMs. Much preferable, if possible, would be to have the browser do the encoding directly. While this normally requires the user to select which portion of their screen to share, our extension in Chromium-based browsers is capable of accessing the [tabCapture API](https://developer.chrome.com/docs/extensions/reference/tabCapture/), which can get a MediaStream of the current tab without any still-frame intermediaries.

It's possible there is a similar win to be had on Firefox, but I have not investigated that browser closely enough to say.

### Why is this needed?

There is the potential to cut CPU usage (particularly on machines with one 2 cores), speed up tests, and improve video quality - by making this change.

### Other

In order to use the tabCapture API, we need to turn off the `--use-fake-ui-for-media-stream` command line arg for chromium. use-fake-ui is currently required in order to allow applications to write tests around webRTC functionality, but this can be worked around by overriding the browser's implementation of `navigator.mediaDevices.getDisplayMedia` and related methods without our own code, returning a sample MediaStream (as --use-fake-ui currently does).

**Comment by khitrenovich** [comment]
Does it apply to videos stored locally or only to Cypress Dashboard integration? If former, it would be great to have this implemented - the videos that we get on the GitHub runners with 2-core CPU are so laggy that it borders with useless.

**Comment by BlueWinds** [comment]
Going to close this, as the high-fidelity debugging effort has made video recording less of a priority to think about and work on.
