### ISSUE TITLE
Not Able to cancel big file downloads

### ISSUE THREAD

**Issue by mudit94** [cypress-io/cypress#19969]
### What would you like?

My usecase is I am downloading a very big file for which I dont want my other tests to wait. I infact want to cancel the download in between. How can I achieve it using Cypress 

### Why is this needed?

For avoiding other tests getting blocked waiting for the download to complete

**Comment by flotwig** [comment]
@mudit94 Try stubbing it with `cy.intercept()` like I mentioned.

**Comment by mudit94** [comment]
@flotwig can you please explain the arguments which i need to pass in above command?

**Comment by romankhomitskyi** [comment]
> @flotwig can you please explain the arguments which i need to pass in above command?

path to your file or fixture name

**Comment by mudit94** [comment]
Path to the file shall be server path right? @flotwig

**Comment by flotwig** [comment]
@mudit94 please refer to the `cy.intercept()` URL matching docs: https://docs.cypress.io/api/commands/intercept#Matching-url

It needs to be the path or full URL for the request.

**Comment by sainthkh** [comment]
Closing because of the inacitivity.
