### ISSUE TITLE
Couldn't set selectedTextBackgroundColor from default ()

### ISSUE THREAD

**Issue by simonhaenisch** [cypress-io/cypress#1996]
I keep getting this warning on my console before each spec that is run (in both headless and headed mode):

```
Cypress Helper[73789:3860241] Couldn't set selectedTextBackgroundColor from default ()
```

### Versions

`cypress@3.0.1`, macOS 10.13.5 (Macbook Pro 2011), Electron 59

**Comment by brian-mann** [comment]
This is a bug in Electron with many issues open about it. You can try reading in there for a workaround.

Alternatively we could just filter out this the way we filter out XVFB and OSX High Sierra warnings...

https://github.com/electron/electron/issues/4420

**Comment by fr0** [comment]
This was fixed in Electron in December, but I'm still getting warnings about it. Can you guys fast-track the Electron upgrade?

**Comment by jennifer-shehane** [comment]
The Electron upgrade is in progress as part of our v4.0 release. Please watch [this issue](https://github.com/cypress-io/cypress/issues/2840) for any comments from the Cypress team for updates.

**Comment by jennifer-shehane** [comment]
Electron has been upgraded quite a bit since this issue, so is likely resolved.
