### ISSUE TITLE
dependency-check is in prebuild, should be in release

### ISSUE THREAD

**Issue by duncan-bayne** [cypress-io/cypress#1997]
Currently, we run `dependency-check` as part of our `prebuild` step:

```
"scripts": {
    "test": "npm run test-unit",
    "test-unit": "npm run dtslint && npm run unit",
    "test-watch": "npm run unit -- --watch",
    "test-dependencies": "bin-up deps-ok && dependency-check . --no-dev",
    "test-debug": "node --inspect --debug-brk $(bin-up _mocha)",
    "test-cov": "nyc npm run unit",
    "unit": "BLUEBIRD_DEBUG=1 NODE_ENV=test bin-up mocha --reporter mocha-multi-reporters --reporter-options configFile=../mocha-reporter-config.json",
    "lint": "bin-up eslint --fix *.js bin/* lib/*.js lib/**/*.js test/*.js test/**/*.js",
    "dtslint": "dtslint types",
    "prebuild": "npm run test-dependencies && node ./scripts/start-build.js",
    "build": "node ./scripts/build.js",
    "prerelease": "npm run build",
    "release": "cd build && releaser --no-node --no-changelog",
    "size": "t=\"$(npm pack .)\"; wc -c \"${t}\"; tar tvf \"${t}\"; rm \"${t}\";"
  },
```

While reporting [an issue](https://github.com/maxogden/dependency-check/issues/89) with `dependency-check` on FreeBSD, several of their developers [suggested](https://github.com/maxogden/dependency-check/issues/89#issuecomment-398940325)  we should be running it as a release step instead:

> > > hmm that also seems like incorrect behavior. the idea of this module is to catch things before you publish, not when you install. i would just remove it in your port
> >
> > Oh, okay. I might raise an upstream PR to move this, then, as it sounds like the problem lies with Cypress.
> >
> > If I understand you correctly, the fix would be to move test-dependencies into the release script above? (Which is also not called by the port :) ).
>
> Correct

Unless otherwise directed by more knowledgable folks here, I will submit a PR to do fix this, thereby closing this issue.  (That will also have the entirely selfish benefit of unblocking my work on a FreeBSD port by moving this step outside the port compilation phase :wink: ).

**Comment by jennifer-shehane** [comment]
Closing. We decided not to go this route.
