### ISSUE TITLE
Could not find the '@cypress/schematic:cypress' builder's node package.

### ISSUE THREAD

**Issue by distante** [cypress-io/cypress#19970]
### Current behavior

After adding the Cypress Angular schematic running `ng e2e` returns 
```
Could not find the '@cypress/schematic:cypress' builder's node package.
```

### Desired behavior

`ng e2e` should open cypress

### Test code to reproduce

Created angular code
```
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "app:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "app:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "app:serve:production"
            }
          }
```

### Cypress Version

9.2.0

### Other

`npx cypress open`. works as expected.

**Comment by tommskar** [comment]
I'm seeing the same behavior in Cypress 10.1.0.

**Comment by Linutux** [comment]
I have the same problem. Is there and solution to this?

**Comment by grgkro** [comment]
Run this command in your project folder terminal:
`npm add @cypress/schematic --save-dev`
And then `ng e2e` should work.
Tbh, I don't really know what the schematic package does, but it seems to be needed.

**Comment by dnordahl1** [comment]
Has anyone figured out how to get cypress-ntlm to be invoked as part of the ng e2e call?

**Comment by tolerious** [comment]
I have just tested the latest version of Cypress in an Angular project, still has the problem.

**Comment by AtofStryker** [comment]
@tolerious or anyone subbed to the issue be able to provide a reproduction repository that we can reproduce locally on our end?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
