### ISSUE TITLE
mocha Done() not find when using Typescript

### ISSUE THREAD

**Issue by TimoPot** [cypress-io/cypress#1998]
https://docs.cypress.io/api/events/catalog-of-events.html#App-Events has multiple examples using **done()** 

I'm using typescript and in the following piece of code:

```
cy.on('window:load', (win) => {
     ....
     done();
});
```
i get the following error: [ts] cannot find name 'done'

my tsconfig.json has the following includes:
```
  "include": [
    "node_modules/cypress",
    "cypress/**/*.ts"
  ],
```

### Desired behavior:
I expected the done to be recognised as valid.

### Versions
Cypress: 3.0.1. Beta
OS: Win 7
Browser: Chrome 64

**Comment by chrisbreiding** [comment]
`done` is not a global and has to be used in the scope of an `it`, `before`, or `beforeEach` block, like so:

```javascript
it('is a test', (done) => {
  cy.on('window:load', (win) => {
     ....
     done()
  })
})
```

I'd need to know more about what you're doing to be sure, but it looks like what you're trying to do is unnecessary. If you use `cy.visit()`, Cypress already waits until the `load` event fires on the page to run subsequent commands, so there's no need to manually wait for `window:load`.

**Comment by brian-mann** [comment]
My guess is that he's navigating around within a single test and is wanting to wait for the page to load like after a `.click()`.

This event would be useful in that context - however, since Cypress automatically detects the page unloading, it will pause command execution and pick it back up whenever the page finishes loading, it's mostly unnecessary. But it could be useful in a specific scenario.

**Comment by TimoPot** [comment]
@chrisbreiding @brian-mann 

I'm navigating to a page which has an iFrame. This iFrame loads some content by means of an XHR.
I need to test if the the iFrame content is correct.

I managed to get the content of the iFrame by using some Promises. 

The test in which I want to to check the content has already finished because it does not wait for the Promises I made. I somehow need to wait for my Promises to finish before I can test the content.

I probably misunderstood the need for done()

I also see that the expects that I write withing the then() of a Promise has no influence on the test result of the it() I write. Thus when the expect fails the result of the it() is still green because the it() was already finished.

**Comment by chrisbreiding** [comment]
You were correct about the need for `done`. Since you're waiting for the iframe to load, you'll need to use `done` and call it after your assertions on the iframe contents. I'd need to see more of your test code to determine what is going wrong.

**Comment by TimoPot** [comment]
I'm new on using Promises so I might have made some thinking errors but it does what I expect.

**iframe.ts in the support map:**
`import { Promise } from 'bluebird';

export const waitForIFRameReady = (frm: any): Promise<any> => {
    console.log('1');
    return new Promise((resolve, reject) => {
        let y = (frm[0].contentWindow || frm[0].contentDocument);
        if (y.document) {
            y = y.document;
            y.addEventListener('readystatechange', () => { // start listening to readyStateChange
                if (y.readyState === 'complete') {
                    resolve(event);
                } else {
                    reject(new Error(`iframe state '${event}' is not yet ready`));
                }
            });
        } else {
            reject(new Error('iframe not found'));
        }
    });
};

const state = (event: string): Promise<any> => {
    return new Promise((resolve, reject) => {
        if (event === 'complete') { // if the state is complete then the iFrame is ready
            resolve(event);
        } else {
            reject(new Error(`iframe state '${event}' is not yet ready`));
        }
    });
};

export const waitForIFrameBody = (ifr: any): Promise<any> => {
    return new Promise((resolve, reject) => {
        getIFrameBody(ifr)
            .then((res) => {
                console.log(`res: ${JSON.stringify(res.innerText, null, '\t')}`);
                resolve(res.innerText);
            })
            .catch((err) => {
                console.log(`err: ${err}`);
                reject(err);
            });
    });
};

const getIFrameBody = (ifr: any): Promise<any> => {
    return new Promise((resolve, reject) => {
        const y = (ifr[0].contentWindow || ifr[0].contentDocument);
        // debugger;
        if (y.document) {
            resolve(y.document.body);
        } else {
            reject(new Error('iframe not found'));
        }
    });
};

// export default iframe;
`

**The test using the above:**
`        it(`should - find the iframe`, () => {

            const checkIframe = (ifr: any, iteration = 0) => {
                nr = ++iteration;
                console.log(`new: ${nr}`);

                frame.waitForIFrameBody(ifr)
                    .then((str: string) => {
                        expect(str).to.contain(TOELICHTING_TEKST);
                    })
                    .catch((err2) => {
                        console.log(`err2: ${err2}`);
                        // nr++;
                        if (nr < 5) {
                            setTimeout(() => {
                                checkIframe(ifr, nr);
                            }, 2);
                        }
                    });
            };

            cy.on('window:load', (win) => {
                cy.get('#inhoudPanelGroup').find('iframe').as('iframe');

                cy.get('@iframe').then((ifr) => {
                    return frame.waitForIFRameReady(ifr)
                        .then(() => {
                            console.log('first wait for iframe body');
                            frame.waitForIFrameBody(ifr)
                                .then((str: string) => {
                                    **expect(str).to.contain(TOELICHTING_TEKST); // the Cypress expect**
                                }).catch((err) => {
                                    console.log(`err1: ${err}`);
                                });
                        }).catch((err) => {
                            console.log(`${err}. Trying 5 x more`);
                            checkIframe(ifr); // call to try the waitForIFrameBody again
                        });

**this is the place where I want to add the done() statement**
                });
            });
        });`

**Comment by chrisbreiding** [comment]
In this case, you don't need `cy.on('window:load')`. That event signals that the window for the page you're `cy.visit`ing has loaded. For the iframe, you can wait for its 'load' event and then make assertions. Something like:

```
it('should - find the iframe', (done) => {

**Comment by TimoPot** [comment]
cy.on('window:load') is fired when the main paged is loaded. But the main page contains an iframe which also loads content.

The waitForIFRameReady() waits for the iframe to be ready and after that the waitForIFrameBody() checks for the content of the iframe to be present. If that's the case then I do the it.

I will try your suggestion.

thx
