### ISSUE TITLE
`cy.root` ignores `timeout` option

### ISSUE THREAD

**Issue by marcandre** [cypress-io/cypress#19985]
### Current behavior

Passing a `timeout` option to `cy.root` has no effect.

### Desired behavior

Like `get` and al., it should retry for the given timeout duration.

Note: there's a separate bug with `root` [not retrying *at all* when called from `within`](https://github.com/cypress-io/cypress/issues/19404). This seems different but may be related.

### Test code to reproduce

From [this demo](https://github.com/cypress-io/cypress-test-tiny/pull/72):

```js
describe("page", () => {
  beforeEach(() => {
    cy.visit("https://example.cypress.io");
    delayedHelloAfter(7);
  });

  it("`root` retries using the default so this test fails (good)", () => {
    cy.root().should("contain", "Hello");
  });

  it("`root` does not respect the `timeout` options so this test fails too (bad)", () => {
    cy.root({ timeout: 10000 }).should("contain", "Hello");
  });
  it("get('html') does respect the `timeout` options so this test passes (good)", () => {
    cy.get("html", { timeout: 10000 }).should("contain", "Hello");
  });
});

function delayedHelloAfter(seconds) {
  cy.window().then((w) => {
    w.eval(`setTimeout(() => {
        document.querySelector('.banner .container').innerHTML = '<p> Hello, world!</p>'
      }, ${seconds} * 1000)
      console.log("ok")
      `);
  });
}
```

### Cypress Version

9.3.1 & 9.4.0

**Comment by sainthkh** [comment]
Confirmed that this fails. 

Thank you for the reproducible example.
