### ISSUE TITLE
`cy.config(defaultCommandTimeout, ...)` has no effect

### ISSUE THREAD

**Issue by marcandre** [cypress-io/cypress#19988]
### Current behavior

`cy.config(defaultTimeout, ...)` has no effect, at least on the subsequent `cy.get` command.

### Desired behavior

Calling `cy.get(sel)` or `cy.get(sel, {timeout: Cypress.config().defaultCommandTimeout})` should always behave identically.

### Test code to reproduce

As shown in [this PR](https://github.com/cypress-io/cypress-test-tiny/pull/73):

```js
describe("page", () => {
  beforeEach(() => {
    cy.visit("https://example.cypress.io");
    delayedHelloAfter(7);
  });

  it("`get` retries using the defaultTimeout so this test fails (good)", () => {
    cy.get("body").should("contain", "Hello");
  });

  it("`get` respects the `timeout` option so this test passes (good)", () => {
    cy.get("body", { timeout: 10000 }).should("contain", "Hello");
  });

  it("`get` does not respect the `defaultCommandTimeout` changed via `config` so this fails (bad)", () => {
    Cypress.config("defaultCommandTimeout", 10000);
    cy.get("html").should("contain", "Hello");
  });

  it("This form should be equivalent to the previous one, but passes (good)", () => {
    Cypress.config("defaultCommandTimeout", 10000);
    cy.get("html", {
      timeout: Cypress.config().defaultCommandTimeout,
    }).should("contain", "Hello");
  });
});

function delayedHelloAfter(seconds) {
  cy.window().then((w) => {
    w.eval(`setTimeout(() => {
        document.querySelector('.banner .container').innerHTML = '<p> Hello, world!</p>'
      }, ${seconds} * 1000)
      console.log("ok")
      `);
  });
}
```

### Cypress Version

9.4.0

**Comment by marcandre** [comment]
If there was timely support, I'd be more than willing to do that.

**Comment by nagash77** [comment]
Hi @marcandre  , I apologize that this issue has not been worked on. Our developers wish they could address every single issue that comes in but that is not realistic at this time. We are making changes to our support process and continue to strive to give the best support possible. I am going to close this issue until you have time to verify it is still happening in current versions of Cypress. Please comment back here with details and we will be happy to reopen and investigate.
