### ISSUE TITLE
have.class is not working properly

### ISSUE THREAD

**Issue by anas-qa** [cypress-io/cypress#1999]
Hi,

Apologies if duplicated, but didn't manage to find a properly relative open issue

### Current behavior:

Following code snippent

```js
it('should assert sign in tab UI and text', function () {

        // assert sign in Btn active by default
        cy.get("ul.nav.nav-tabs > li:nth-child(1)").should('have.class','.active');
    });
```

Execution marked as failed as `CypressError: Timed out retrying`

<img width="496" alt="screen shot 2018-06-21 at 12 34 13 pm" src="https://user-images.githubusercontent.com/16471809/41708941-0b16de3e-7553-11e8-9f7a-386fc988b5d9.png">

### Desired behavior:

Should assert tue as per log screenshot on Cypress GUI

### Versions
Cypress package version: 3.0.1
Cypress binary version: 3.0.1

OS: Mac
Browser: Chrome

**Comment by anas-qa** [comment]
As per docs, above code should work

However, 

I fixed it by 
```js
// assert sign in Btn active by default
cy.get($SELECTOR).should("have.attr","class","active")
```

I will leave it open for you to take action of closing

**Comment by chrisbreiding** [comment]
`have.class` should always be the bare class name ("active") and never the CSS selector form (".active"). Could you link to where in the docs it indicates the selector form can be used?

**Comment by chrisbreiding** [comment]
It doesn't look like there's an issue here. `should('have.class', 'active')` works and `should('have.class', '.active')` does not work. I don't see anything in our docs that contradicts that, so I'm going to close this.

**Comment by cyclic-1** [comment]
`should('have.class', 'active')` does not work if the element has multiple classes though, it finds all matching elements regardless of whether the class is present or not.
