### ISSUE TITLE
Attempting to call cy.task inside a .then is failing 

### ISSUE THREAD

**Issue by eoin-roll-out** [cypress-io/cypress#19998]
### Current behavior

The code included attempts to use a cypress task to house the query inside index.ts and then I am trying to use that within the .then so I have access to the variable I need. I am receiving the following error when it is ran:

![Screenshot 2022-02-01 at 16 12 22](https://user-images.githubusercontent.com/60970259/152005968-11e1a41a-23f2-4701-88ac-dcab3faf5336.png)

I do not know why it is not recognising cy and this seems like an issue with cypress as opposed to anything I've done although happy to be corrected.

The code isn't copying properly so here is some screenshots:

![Screenshot 2022-02-01 at 16 19 11](https://user-images.githubusercontent.com/60970259/152007324-1327e834-3800-467c-88b7-115f26973512.png)
![Screenshot 2022-02-01 at 16 19 24](https://user-images.githubusercontent.com/60970259/152007328-026c91a0-4004-466b-a1f9-955a3765b8a5.png)

### Desired behavior

I want to get a value from the page html and then use it within the query to the database inside query1 however, this is proving far more difficult than I had anticipated. If anyone has any easier methods then PLEASE let me know.

### Test code to reproduce

plugins/index.ts

`module.exports = (on, config) => {
  on('task', {
    ssQuery: query1,
  });
};

const query1 = async (taskOrgId) => {
  return new Promise((resolve) => {
    resolve(GraphqlService.runQuery('siblingSequence.graphql', {
      parentTaskOrgID: taskOrgId,
    }));
  })
};`

pageObjects/page.ts

`  async checkForAndSelectNextDropdown(indexArray: Array<number>) {
    for (const index of indexArray) {
      this.loadingUnitIcon.should('not.exist');
      // probably race condition here
      cy.get('.symbolic-button').eq(index).click();
      cy.get('.taskorg.open')
        .eq(index)
        .then((el) => {
          const taskOrgId = el.attr('data-testid').split('-')[1];
          cy.task('ssQuery', parseInt(taskOrgId)).then((val) => {
            const { workforce, vehicles } = val.getPositionSummaryById;
            cy.contains('Vehicles (${vehicles}) Workforces (${workforce})');
          });
        });
    }
  }`

### Cypress Version

9.2.1

**Comment by flotwig** [comment]
@eoin-roll-out please share your stack trace. It looks like you are running a callback with `cy` in it inside of your plugin, where `cy` is undefined.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
