### ISSUE TITLE
Integration with Travis CI

### ISSUE THREAD

**Issue by lorennorman** [cypress-io/cypress#2]
Would love support and documentation for automatically running the Cypress tests with Travis.

**Comment by brian-mann** [comment]
This is being worked on currently and is on track for end of July.

**Comment by brian-mann** [comment]
This is done as of last week but the docs need to be written, so leaving this open until that's done.

**Comment by brian-mann** [comment]
Forgot to close this out. This has been done for awhile now, the docs are here: https://github.com/cypress-io/examples-react-travis-ci
