### ISSUE TITLE
Better error message for shortform cy.routes()

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#20]
My actual mistake was that I did not define a response to the route, but the error message is telling me to define a url although I have defined a url.

**My route:**
```js
cy.route(/answers/)
```

**The error:**
![screen shot 2015-04-09 at 4 02 38 pm](https://cloud.githubusercontent.com/assets/1271364/7075686/f0a97842-ded1-11e4-9a97-d8a562378145.png)

**Comment by brian-mann** [comment]
Fixed in `0.4.4`. [Changelog](https://github.com/cypress-io/cypress/wiki/Changelog#044-04092015)
