### ISSUE TITLE
Use `.csv` as fixture

### ISSUE THREAD

**Issue by jheijkoop** [cypress-io/cypress#200]
Currently `.csv` files (`text/csv`) aren't accepted as such ("invalid fixture extension"). As a workaround I renamed mine to `.txt` for now. I suspect they can be handled/accepted like normal text files

**Comment by brian-mann** [comment]
So you would just like `csv` parsed into regular text as an unformatted string?

**Comment by jheijkoop** [comment]
yeah, it's just text to a web app right? It's not a "first class citizen" like json/images. I tried to use it as a fixture for an upload

**Comment by brian-mann** [comment]
Fixed in [`0.17.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0171-08312016).
