### ISSUE TITLE
Typescript: ts(2345) - Command.js file

### ISSUE THREAD

**Issue by Vik4290** [cypress-io/cypress#20001]
### Current behavior

Getting error:

Argument of type '(subject: any, testId: any, options: any) => void' is not assignable to parameter of type '<E extends Node = HTMLElement>(testId: string, options?: Partial<Loggable & Timeoutable & Withinable>) => Chainable<JQuery<E>>'.ts(2345)
![Uploading Screenshot 2022-02-01 at 10.04.55 PM.png…]()

### Test code to reproduce

Upgraded cypress to 9.0

### Cypress Version

9.0

**Comment by gauravgandhi1315** [comment]
Can't open this screenshot. Can you provide more details?

**Comment by Vik4290** [comment]
<img width="1440" alt="Screenshot 2022-02-01 at 10 04 55 PM" src="https://user-images.githubusercontent.com/62888395/152020196-8dffc51b-caa3-4a40-8dfb-6274818c5e27.png">

**Comment by Vik4290** [comment]
**command.ts** 
Cypress.Commands.add(
  'getByTestId',
  {
    prevSubject: ['optional', 'window', 'document', 'element'],
  },
(subject, testId, options) => {
    const selector = `[data-cy=${testId}]`;

    if (subject) {
      cy.wrap(subject).find(selector, options);
    } else {
      cy.get(selector, options);
    }
  },
);

**index.d.ts**

declare namespace Cypress {
  interface Chainable<Subject> {
    getByTestId<E extends Node = HTMLElement>(
      testId: string,
      options?: Partial<Loggable & Timeoutable & Withinable>,
    ): Chainable<JQuery<E>>;
  }
}

**Comment by flotwig** [comment]
@Vik4290 Cypress 9.0.0 updated the types for Custom Commands. Check out the changelog and update your types accordingly: https://docs.cypress.io/guides/references/changelog#9-0-0

> Custom command implementations are now typed based on the declared custom chainables. Addresses [#17496](https://github.com/cypress-io/cypress/pull/17496).
