### ISSUE TITLE
Videos of failing tests only show 1 or 2 frames

### ISSUE THREAD

**Issue by manwithtwowatches** [cypress-io/cypress#20012]
### Current behavior

The videos of failing tests which are available in the dashboard only show 1 or 2 frames for, say, a 30 second video. This makes them useless. This used to work when we were using CircleCI but since moving to Github Actions this behaviour started happening. I could assume that this perhaps has something to do with a lack of resources available on the Actions machines, but this is something which I do no have any control over. Do you have any suggestions as to what I could do about this? Moving back to Circle is not an option.

### Desired behavior

I would like the videos to be videos again instead of single frame images.

### Test code to reproduce

Have a look at any of the videos which have been recorded in our runs.

### Cypress Version

9.3.1

**Comment by flotwig** [comment]
> I could assume that this perhaps has something to do with a lack of resources available on the Actions machines, but this is something which I do no have any control over.

@manwithtwowatches This is the case, browsers throttle the screencasts when the system is low on CPU, which explains why moving from Circle to Actions could have impacted your videos.

We have some improvements to the video recording performance coming soon, including #19983.

Chromium-family browsers only: You could try setting the `CYPRESS_EVERY_NTH_FRAME` environment variable to increase the number of frames sent. By default it is `CYPRESS_EVERY_NTH_FRAME=5`, but you could set it to `CYPRESS_EVERY_NTH_FRAME=1` to lower the throttling. Let me know if this helps.

**Comment by manwithtwowatches** [comment]
Thanks for the response @flotwig. I tried the suggestion you made and also updated to the latest version but it did not seem to make any difference.

**Comment by camiloesub** [comment]
Any news on this? I can not switch to chrome it my github actions pipeline. I need electron but the video just shows the firs 3 or 4 seconds...
