### ISSUE TITLE
invoke('val') fails if called a second time

### ISSUE THREAD

**Issue by plynchnlm** [cypress-io/cypress#20018]
### Current behavior

If I do cy.get() on an input field, and call invoke('val'), the first call works, and the second times out with the complaint that the 'val' property does not exist.
```
let s = cy.get('#\\/intField\\/1');
s.type('2');
s.invoke('val').then((v)=>console.log('v7 is '+v)); 
s.invoke('val').then((v)=>console.log('v7b is '+v)); 
```
![image](https://user-images.githubusercontent.com/6410979/152192560-77e31283-4fc0-4141-83b3-62fcb9316928.png)

### Desired behavior

It should work both times.  If you issue a second cy.get() for the element between the two invokes, both succeed.

### Test code to reproduce

Sample code is as above.
```
let s = cy.get('#\\/intField\\/1');
s.type('2');
s.invoke('val').then((v)=>console.log('v7 is '+v)); 
s.invoke('val').then((v)=>console.log('v7b is '+v)); 
```

### Cypress Version

9.3.1

**Comment by mohanhbk** [comment]
Hi @plynchnlm ,
I suspect the approach to be wrong as per the documentation.
The variable and aliasing page in cypress recommends to not use like the below code snippet
```
// this won't work the way you think it does
const button = cy.get('button')
const form = cy.get('form')

button.click()
```

Instead you can modify your code to
`y.get('#\\/intField\\/1').then((s)=>{
                          cy.wrap(s).type("2");
                          
                          cy.wrap(s).invoke('val').then((v)=>console.log('v7 is '+v))
                          
                          cy.wrap(s).invoke('val').then((v)=>console.log('v7b is '+v))
                        })`

**Comment by flotwig** [comment]
This is an error because of the way the Cypress chainer works. You'll need to do either:

```js
cy.get('#\\/intField\\/1').as('field')
cy.get('@field').invoke('val').then((v)=>console.log('v7 is '+v)); 
cy.get('@field').invoke('val').then((v)=>console.log('v7b is '+v)); 
```

or something like what @mohanhbk suggested.

Closing since this is working as expected.
