### ISSUE TITLE
Allow spaces instead of periods in .should()

### ISSUE THREAD

**Issue by Herteby** [cypress-io/cypress#2002]
Personally I think it looks a little ugly to use dot notation inside a string.
A simple `str.replace(/ /g, '.')` would allow chainers to look more like English.

I don't think it's currently possible for a "chainer string" to contain spaces and be valid, which means that this addition shouldn't break any existing uses.

### Current behavior:
```js
get('#myButton').should('not.be.disabled')
```
### Desired behavior:
```js
get('#myButton').should('not be disabled')
```
### Example implementation:
```js
Cypress.Commands.overwrite('should', (originalFn, subject, ...args) => {
  if(typeof args[0] === 'string'){
    args[0] = args[0].replace(/ /g, '.')
  }
  return originalFn(subject, ...args)
})
```

**Comment by chrisbreiding** [comment]
Currently, the dot notation mirrors chai syntax. Any chai matcher (`expect(_el_).to.not.be.disabled`) translates into the Cypress version (`cy.get(_selector).should('not.be.disabled')`), so it's more or less self-documented. 

I don't think this is something we should add to Cypress itself, especially since it can be pretty concisely achieved in the userland with the code you posted. 

Thoughts, @brian-mann?

**Comment by jennifer-shehane** [comment]
@Herteby Does your overwrite of the command above work? If so...does seem a bit unnecessary to extend Cypress to include this.

**Comment by Herteby** [comment]
@chrisbreiding Yes. I could see the argument that having spaces instead of dots might make it less obvious how it works.
@jennifer-shehane Yes it works. This was more of a "proposal" than a "demand". It was just in case other people might prefer spaces too, it should be a simple thing to add.

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
