### ISSUE TITLE
Invoke command displays data in Command log with disabled log

### ISSUE THREAD

**Issue by leonid-sviderskii-mtl** [cypress-io/cypress#20043]
### Current behavior

Hello guys!

I'd like to hide the values I'm invoking into a field so I use `{ log: false }` argument as the command docs say it's possible: https://docs.cypress.io/api/commands/invoke#Arguments

Here is the test code, I used kitchen sink as an example and added an invoke command there.
```
it.only('displays two todo items by default', () => {
  cy.get('[data-test="new-todo"]', { log: false })
    .invoke('val', 'Gleb is awesome', { log: false })
)}
```

As you can see on the screenshot, the `cy.get` command is hidden from the Command log but invoke is not:
![image](https://user-images.githubusercontent.com/71408484/152419775-686c9bd0-7056-4a3a-bd40-346a0454bc16.png)

### Desired behavior

The invoke logs are hidden from the Command log when` { log: false }` is used

### Test code to reproduce

```
it.only('displays two todo items by default', () => {
  cy.get('[data-test="new-todo"]', { log: false })
    .invoke('val', 'Gleb is awesome', { log: false })
)}
```

### Cypress Version

9.4.1

**Comment by bahmutov** [comment]
hahaha, i like the sentiment. `cy.invoke` is a little different from other commands because it accepts unknown number of method's arguments. Thus the Cypress options should be in the first argument position, see https://on.cypress.io/invoke
