### ISSUE TITLE
Decorators not supported

### ISSUE THREAD

**Issue by AStoker** [cypress-io/cypress#20055]
### Current behavior

When I run unit tests that include decorators, I get a web pack compilation error (note, I'm not using webpack in my application).

```powershell

 Oops...we found an error preparing this test file:   

src\test-attribute.spec.js

  The error was:

  Error: Webpack Compilation Error 

./src/test-attribute.js

 Module build failed (from C:/Users/softdocs/AppData/Local/Cypress/Cache/9.4.1/Cypress/resources/app/node_modules/babel-l oader/lib/index.js): 
SyntaxError: 

C:\Users\softdocs\Downloads\cypress-decorator-bug\src\test-attribute.js: Support for the experimental synta x 'decorators-legacy' isn't currently enabled (3:1):   

1 | import { bindable, customAttribute } from 'aurelia';  
2 | 
3 | @customAttribute({     
  | ^   
4 |     name: 'test-attribute'   
5 | })   
6 | export class TestAttribute {  
@ ./src/test-attribute.spec.js 3:21-48

```
 

There is a babel config in my application that includes the plugin for proposal decorators, but it looks like Cypress isn't using it. It "appears" that Cypress is doing it's own runtime compilation and is having a hard time with compiling the code. I tried including the babel config in the cypress folder (copy and paste) but still didn't have any luck.

### Desired behavior

I should be able to use decorators in my files for unit tests.

### Test code to reproduce

Repro: https://github.com/AStoker/cypress-decorator-bug
Run `yarn run test:e2e`

### Cypress Version

9.4.1

**Comment by emilyrohrbough** [comment]
@AStoker The` webpack-batteries-included-preprocessor` module is used to process files in Cypress by default. This uses this [webpack configuration](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-batteries-included-preprocessor/index.js#L84) which will not reference your babel-configuration.

If you needed webpack configuration beyond these defaults, you can add use the webpack preprocess module to add your own configuration to Cypress. The documentation can be found here: https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor.

The full collection of official and community provided preprocessor can be found here: https://docs.cypress.io/plugins/directory#Preprocessors

**Comment by AStoker** [comment]
Aha, interesting! So having webpack preprocess at that root level will then transpile and feed it to cypress in a way that it can understand over there? If, for example, I didn't want to use webpack as a preprocessor, could I use something else, as long as cypress receives some kind of code that it can understand?

**Comment by emilyrohrbough** [comment]
Yup! You can use an existing non-webpack preprocessor or even write your own. Here are the docs on the preprocessor API [around the API and the ](https://docs.cypress.io/api/plugins/preprocessors-api)

**Comment by AStoker** [comment]
Perfect, that works! Thanks for the help.
