### ISSUE TITLE
Cypress failed to start.

### ISSUE THREAD

**Issue by atQaCraftnote** [cypress-io/cypress#20052]
### Current behavior

When i try to run Cypress I get an error: It looks like this is your first time using Cypress: 9.4.1

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with Unknown system error -86: /Users/Myname/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=481
spawn Unknown system error -86

----------

Platform: darwin-x64 (21.3.0)
Cypress Version: 9.4.1

### Cypress Version

9.4.1, 9.3.1

### Package Manager

npm

### Operating system

Mac

**Comment by gauravgandhi1315** [comment]
If you had installed it previously, try to delete all versions of cypress in the cache & then re-installing Cypress.

**Comment by atQaCraftnote** [comment]
I did that but still no luck. Getting the same error after reinstall.

**Comment by atQaCraftnote** [comment]
Issue was that my Mac's M1 chip wasnt compatible with Cypress so going to "get info" on the terminal and checking "open using roseta" checkbox resolved it.

**Comment by Obadha2** [comment]
Hi @atQaCraftnote  
I'm having this same issue on my M1 MBP, could you explain how you fixed this? 
Thanks.

**Comment by Obadha2** [comment]
Nvm, I found it. :)

**Comment by mmtmohit** [comment]
Cypress versions 10.1.x and below are not supporting the new Mac M1 chip on the MBPs , hence the -86 error is coming,
Solution is here on the Cypress blog - https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2
