### ISSUE TITLE
Constant changes its value within the script visiting cross-domain URLs

### ISSUE THREAD

**Issue by vovcharenko1** [cypress-io/cypress#20050]
### Current behavior

1. Create a spec file having 3 tests:
2. Declare a constant which gets its value from a calculation (e.g. as a timestamp or Math.random) as a global
3. Create 3 tests. Each of the test logs out the constant first and then visit cross-domain URL
4. Run the test

**Expected result:** The test log contains 3 same values of the constant.
**Actual result:** The test log contains 3 different values of the constant.

3. Remove cy.visit() commands or replace them with the same domain URL
4. After this the constant values are the same

### Desired behavior

A constant should not change its value in any case

### Test code to reproduce

```import {now} from "moment";
const timeStamp = now().toString();
const businessEmail = `user${timeStamp}`;

describe('Smoke tests', ()=> {
    it('Create temporary email', () => {
        cy.log(businessEmail);
        cy.visit('https://ahem-email-api.datapwn.com/');
    })

    it('Create a trial account', ()=> {
        cy.log(businessEmail);
        cy.visit('https://google.com');
    })

    it('Register with temporary email', () => {
        cy.log(businessEmail);
        cy.visit('https://ahem-email-api.datapwn.com/')
    })
})```

### Cypress Version

8.7.0

### Other

![screen-1](https://user-images.githubusercontent.com/90378456/152497423-0f4dc77c-1c47-499a-97a3-86bef8a6130b.png)

**Comment by vovcharenko1** [comment]
![screen-1](https://user-images.githubusercontent.com/90378456/152497849-67c2f84e-80b9-4c94-8e40-94b6e60b2197.png)

**Comment by flotwig** [comment]
@vovcharenko1 this is a natural consequence of the way Cypress currently works - it only supports visiting 1 superdomain per test: #944 Navigating between superdomains is not explicitly supported. You'll lose your local variables because Cypress has to reload `window.top` on `cy.visit` to a new superdomain.

Once multi-domain #17336 is added, you will be able to execute code in a second domain and pass in data from the primary domain.

**Comment by Srikanth07482** [comment]
Is there any alternative to use variables across domains without values getting changed? @flotwig

**Comment by mazhuga** [comment]
> Is there any alternative to use variables across domains without values getting changed? @flotwig

any updates here?
