### ISSUE TITLE
TypeError Cannot convert object to primitive value

### ISSUE THREAD

**Issue by romankhomitskyi** [cypress-io/cypress#20058]
### Current behavior

We are getting the following error trace. This is occurring randomly on random spec files in our CI environment. We are not able to reproduce it. All the retries also fail with the same error.
```

1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Cannot convert object to primitive value

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

      at Array.join ()
      at Object.decodeBase64Unicode (https://example.com/__cypress/runner/cypress_runner.js:178904:8)
      at base64toJs (https://example.com/__cypress/runner/cypress_runner.js:178118:76)
      at Object.extractSourceMap (https://example.com/__cypress/runner/cypress_runner.js:178076:21)
      at extractSourceMap (https://example.com/__cypress/runner/cypress_runner.js:177156:87)
      at tryCatcher (https://example.com/__cypress/runner/cypress_runner.js:13212:23)
      at MappingPromiseArray._promiseFulfilled (https://example.com/__cypress/runner/cypress_runner.js:10332:38)
      at MappingPromiseArray.PromiseArray._iterate (https://example.com/__cypress/runner/cypress_runner.js:11534:31)
      at MappingPromiseArray.init (https://example.com/__cypress/runner/cypress_runner.js:11498:10)
      at Promise._settlePromise (https://example.com/__cypress/runner/cypress_runner.js:11201:21)
      at Promise._settlePromise0 (https://example.com/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (https://example.com/__cypress/runner/cypress_runner.js:11329:18)
      at Promise._fulfill (https://example.com/__cypress/runner/cypress_runner.js:11273:18)
      at MappingPromiseArray.PromiseArray._resolve (https://example.com/__cypress/runner/cypress_runner.js:11546:19)
      at MappingPromiseArray._promiseFulfilled (https://example.com/__cypress/runner/cypress_runner.js:10372:18)
      at Promise._settlePromise (https://example.com/__cypress/runner/cypress_runner.js:11209:26)
```

### Desired behavior

The tests should not fail with this error

### Test code to reproduce

Unable to reproduce the error consistently.

### Cypress Version

Cypress version: 8.6.0
Docker image: FROM cypress/browsers:node14.17.0-chrome91-ff89
Chrome headless

**Comment by flotwig** [comment]
> Unable to reproduce the error consistently.

@romankhomitskyi can you share test code/conditions that cause this to fail sometimes? Hard to know where this is coming from with nothing, and it hasn't been reported yet. You could also try updating to the latest Cypress.

**Comment by romankhomitskyi** [comment]
> > Unable to reproduce the error consistently.
> 
> @romankhomitskyi can you share test code/conditions that cause this to fail sometimes? Hard to know where this is coming from with nothing, and it hasn't been reported yet. You could also try updating to the latest Cypress.

The only array join I have in my code is 

```
function verification(verified = false, withSimpliVerified = false): void {


const state: string[] = [];
if (verified) {
state.push('verified');
}

if(withSimpliVerified) {
state.push('with_active_simpli_verified');
}

cy.request('POST', 'url', {body: {state: state.join()}})
}
verification();
```
Also worth mentioning that I'm running 11 instances of Cypress in one docker container
I thought it had smth do to with [invalid token and window atob issue](https://davidwcai.medium.com/fix-cypress-invalid-or-unexpected-token-errors-in-parallel-runs-e887d7efa945)

Could you  please 100% admit that is the issue on my side not on cypress?

**Comment by romankhomitskyi** [comment]
I have updated Cypress to 9.5.0 same error keeps occurring

**Comment by sainthkh** [comment]
Sorry for the late reply.

`decodeBase64Unicode` and `base64toJs` are definitely Cypress code. 

But I tried to reproduce the problem with the code below, but I failed.

```js
it('t', () => {
  cy.request('POST', 'http://localhost:3501/post-only', { body: { state: ['foo', 'bar'].join() } })
})
```

```js
  app.post('/post-only', (req, res) => {
    return res.send(`<html><body>it worked!<br>request body:<br>${JSON.stringify(req.body)}</body></html>`)
  })
```

We need more specific code sample.

**Comment by romankhomitskyi** [comment]
> Sorry for the late reply.
> 
> `decodeBase64Unicode` and `base64toJs` are definitely Cypress code.
> 
> But I tried to reproduce the problem with the code below, but I failed.
> 
> ```js
> it('t', () => {
>   cy.request('POST', 'http://localhost:3501/post-only', { body: { state: ['foo', 'bar'].join() } })
> })
> ```
> 
> ```js
>   app.post('/post-only', (req, res) => {
>     return res.send(`<html><body>it worked!<br>request body:<br>${JSON.stringify(req.body)}</body></html>`)
>   })
> ```
> 
> We need more specific code sample.

I expirienced this issue randomly on CI, 
However I haven't seen this issue for a while

**Comment by romankhomitskyi** [comment]
```
public create(user: UserDbFixture, withIdVerified = false, withSimpliVerified = false): Chainable<number> {

		const state: string[] = [];
		
		
		if (withIdVerified) {
			state.push('verified');
		}
		
		
		if (withSimpliVerified) {
			state.push('with_active_simpli_verified');
		}
		

		return databaseSeeder
			.create({ model: this.userModel, state: state.join(), overrides: { ...user } })
		
	}
	
class DataBaseSeeder {
    public create(options: Partial<SeederOptions>): Cypress.Chainable<Cypress.Response<any>> {
		return cy.request('POST', url, { action: 'create', ...options });
	}

}


export interface SeederOptions {
	model: string;
	action: string;
	state: string;
	overrides: unknown;
}

```
I have encountered this issue recently 
here is my full example

It's the only array.join() in my code, I researched well my project

![image](https://user-images.githubusercontent.com/57874507/161748936-e759d575-6289-495f-900d-3adaad8eb144.png)

**Comment by romankhomitskyi** [comment]
@sainthkh Hi I was wondering if the following code from plugins could somehow cause these issue? When running 10 cypress instances on the same machine

import webpackPreprocessor from '@cypress/webpack-batteries-included-preprocessor';
const filePreprocessor = webpackPreprocessor({ typescript: 'typescript' });

const id = uuid();
	on('file:preprocessor', file => {
		file.outputPath = file.outputPath.replace(/^(.*\/)(.*?)(\..*)$/, `$1$2.${id}$3`);
		return filePreprocessor(file);
	});

**Comment by romankhomitskyi** [comment]
![image](https://user-images.githubusercontent.com/57874507/168156741-b6eae3de-0cdb-4422-896d-40a9226c5571.png)
