### ISSUE TITLE
Proposal: use release tagging

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2006]
We recently discussed as a team to add "Releases" in github.

I'm against adding the binary as releases but for using tags so that it's easy for users to see the source code that makes up a specific version of Cypress.

I think this would require a minor change to our build process (that could be further optimized). My only request is that we go back through and tag previous releases. There should always be a "Released X.X.x" commit for every version so we'd only have to add a git tag for those.

**Comment by bahmutov** [comment]
- go back and tag all previous releases, like `release 1.0.0 [skip ci]`

**Comment by bahmutov** [comment]
We can ask NPM for each version and it has `_from` property that shows the published commit SHA
```
$ npm info cypress@3.0.2 --json
"_from": "https://s3.amazonaws.com/cdn.cypress.io/beta/npm/3.0.2/circle-develop-58f3453b357f2e11bd4fce83ad746cafaf714d31-27598/cypress.tgz",
```
which points at the actual built commit

<img width="980" alt="screen shot 2018-07-11 at 9 56 02 pm" src="https://user-images.githubusercontent.com/2212006/42596243-4516a404-8555-11e8-92c0-a38639c7700e.png">

**Comment by bahmutov** [comment]
yeah, I get the old ones, will traverse through the commit messages to find them instead of going through the NPM @brian-mann

**Comment by brian-mann** [comment]
Done! https://github.com/cypress-io/cypress/releases

Thank you @bahmutov

**Comment by bahmutov** [comment]
Use https://github.com/cypress-io/set-releases as a CLI tool to publish new GitHub release for a version
