### ISSUE TITLE
I can't delete the recorded video if the spec is passed

### ISSUE THREAD

**Issue by hager-yousri** [cypress-io/cypress#20065]
### Current behavior

I followed this steps to remove recorded video for the spec file but it doesn't be removed 
https://docs.cypress.io/api/plugins/after-spec-api#Delete-the-recorded-video-if-the-spec-passed

all tests are passed but the recorded video in cypress/videos not removed

### Desired behavior

I want to delete the recorded video if the spec file is passed

### Test code to reproduce

1- I run "npm i del --save-dev" in terminal
2-I added this to plugin/index
```js
const del = require('del')
module.exports = (on, config) => {
  on('after:spec', (spec, results) => {
    if (results && results.stats.failures === 0 && results.video) {
      return del(results.video)
    }
  })
}
```
3-I run the tests in headles mode via this script
"run-tests-headless": "cypress run --spec cypress/integration/login.spec.js"

### Cypress Version

9.0.0

**Comment by jennifer-shehane** [comment]
Are you able to console.log any of these values locally, to show up in the terminal to see the state of your tests? `results`, `results.stats`, `results.stats.failures`, `results.video`? See what the values are, maybe there's something that is not meeting the requirements of the if statement in your case.

**Comment by hager-yousri** [comment]
yes I tried and nothing is printed

const del = require('del')
module.exports = (on, config) => {
  on('after:spec', (spec, results) => {
    console.log('Finished running', spec.relative)
    console.log(results)
    if (results && results.stats.failures === 0 && results.video) {
      console.log(results.stats.failures)
      console.log(results.stats)
      console.log(results)
      return del(results.video)
    }
  })
}

**Comment by romankhomitskyi** [comment]
> yes I tried and nothing is printed
> 
> const del = require('del') module.exports = (on, config) => { on('after:spec', (spec, results) => { console.log('Finished running', spec.relative) console.log(results) if (results && results.stats.failures === 0 && results.video) { console.log(results.stats.failures) console.log(results.stats) console.log(results) return del(results.video) } }) }

You might use plugins which have already subscribed to after spec event that is why your code does not work

**Comment by hager-yousri** [comment]
it is solved. thanks

**Comment by hager-yousri** [comment]
it is solved thanks

**Comment by romankhomitskyi** [comment]
> it is solved thanks

Could you share the solution?

**Comment by mihhail-m** [comment]
Anyone else have a solution for this? I am having the same issue in `12.5.0`.
