### ISSUE TITLE
Building Cypress (9.4.1) project with typescript 4.5 - Error with Sinon

### ISSUE THREAD

**Issue by jacky-lam** [cypress-io/cypress#20078]
### Current behavior

When I try to build my Cypress project with the latest cypress version 9.4.1, it has a problem with compiling with using the typescript version 4.5.

It seems only typescript 4.1 supports using `FakeTimers.TimerId;`, and 4.2 onwards this was removed.

Can you confirm you are able to build a cypress project using typescript compiler version 4.5?

<img width="1287" alt="Screenshot 2022-02-07 at 19 22 55" src="https://user-images.githubusercontent.com/17092881/152857632-f5178928-dac9-4ad1-a95d-a1e053719e56.png">

- I see you introduced using sinon fake-timer on 7.2.0 logs: https://docs.cypress.io/guides/references/changelog#7-2-0

### Desired behavior

To be able to compile the typescript cypress project using Typescript 4.5

### Test code to reproduce

my tsconfig.json:
```
{
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es5",
    "isolatedModules": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "sourceRoot": "/",
    "outDir": "output/dist",
    "strict": true,
    "types": ["cypress", "cypress-localstorage-commands", "./cypress/support"],
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": true,
    "resolveJsonModule": true
  },
  "include": ["cypress/**/*.ts"],
  "lib": ["es5", "dom"]
}
```

Steps to reproduce:
1. Create a blank cypress project using version 4.2.1
2. Using Typescript version 4.5, run `tsc -b tsconfig.json`

Should see the error with Sinon Fake Timer

### Cypress Version

9.4.1

**Comment by flotwig** [comment]
Hi @jacky-lam thanks for opening an issue, I can't actually reproduce this using the `tsconfig.json` and steps you've given on 9.4.1 and TS 4.5.

Can you fork [`cypress-test-tiny`](https://github.com/cypress-io/cypress-test-tiny) and modify it so that it reproduces this issue? That will help debug.

Also - you shouldn't need to `tsc -b tsconfig.json` to compile your TS tests. Cypress will run `typescript` for you.

**Comment by sainthkh** [comment]
Sorry for the late reply.

[This comment](https://github.com/cypress-io/cypress/issues/19759#issuecomment-1017030737) might solve your problem.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
