### ISSUE TITLE
cy.intercept with wildcard sometime fails with 404 on multiple requests

### ISSUE THREAD

**Issue by tommyblue** [cypress-io/cypress#20070]
### Current behavior

The component test intercepts the calls to `/groups/*` into the `beforeEach`, then mounts a react component which, internally, calls `/groups/1`, `/groups/2`, `/groups/3`.
Sometimes the second call (and always the second, never the first) fails, mainly with a 404 error (or a generic "failed" request in the browser console). As it happens in a `beforeEach` hook, cypress stops the test.
The behaviour is not stable and it causes flaky tests.
When tested locally in the browser, if the test fails, all following retries fail. But before the first failure, it could require several retries to make it happen.

The code of the interception causing the failure is:
`cy.intercept("GET", "/groups/*", { fixture: "groups/one.json" }).as("getGroup");`

The issue can be fixed adding a delay:
`cy.intercept("GET", "/groups/*", { fixture: "groups/one.json", delay: 300 }).as("getGroup");`

### Desired behavior

The wildcard interception should correctly reply to all requests (also when repeated very quickly), without giving a 404 error

### Test code to reproduce

```js
describe("MyTest", () => {
	beforeEach(() => {
		cy.intercept("GET", "/groups/*", { fixture: "groups/one.json" }).as("getGroup");
	});

	it("test component", () => {
		mount(<MyComponent />);
		cy.wait("@getGroup").then(interception => {
			// test something
		});
	});
});
```

### Cypress Version

9.3.1

### Other

Tests are executed with `cypress open-ct --browser chromium` or `cypress run-ct --headless --browser chromium --quiet`

**Comment by flotwig** [comment]
@tommyblue I can't reproduce this using the test code given. What does the DevTools show in the Network tab?

**Comment by tommyblue** [comment]
@flotwig see screenshot
![image](https://user-images.githubusercontent.com/122749/153146682-4050a836-e477-4f83-986f-65dd6e89e996.png)

**Comment by tommyblue** [comment]
Sometimes we also get `net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)` error:
![image](https://user-images.githubusercontent.com/122749/153149288-df6e3676-5bbd-4d7f-b618-8cfc0865c0cf.png)

**Comment by tommyblue** [comment]
@flotwig additional information that could be useful here:

I have this test structure, with interceptions in the `beforeEach` and 3 tests. The last one fails intercepting `GET /users/3` with 404 (I'm also attaching the screenshot of the calls made by the 3 tests). Note that in this case the `delay` option doesn't solve the issue.

```js
describe("User Management | Users", () => {
	beforeEach(() => {
		cy.intercept("GET", "/users", { fixture: "users/all.json" }).as("getUsers");
		cy.intercept("GET", "/groups/*", { fixture: "groups/one.json", delay: 300 }).as("getGroup");
		cy.intercept("GET", "/groups", { fixture: "groups/all.json" }).as("getGroups");
	});

	it("test 1", () => {
		mount(<MainComponent />);

		cy.wait(["@getUsers", "@getGroup", "@getGroups"]).then(_ => {
			// OK
		});
	});

	it("test 2", () => {
		mount(<MainComponent />);

		cy.wait(["@getUsers", "@getGroup", "@getGroups"]).then(_ => {
			// OK
		});
	});

	it("test 3", () => {
		mount(<MainComponent />);

		cy.wait(["@getUsers", "@getGroup", "@getGroups"]).then(_ => {
			// FAIL with 404 on GET /groups/3
		});
	});
```

![image](https://user-images.githubusercontent.com/122749/153563315-ae5d96dc-d523-4fb3-865b-115926a4441c.png)

If I remove the first 2 tests (with `xit`), the one remaining works correctly. Moreover, and this is the solution I'm now following, splitting the tests in multiple files solves the problem

**Comment by BlueWinds** [comment]
I'm having trouble reproducing this as well. Here's the sample I set up, based on what you pasted above:

https://github.com/cypress-io/cypress-component-examples/blob/issue-20070/vite-react/src/App.jsx
https://github.com/cypress-io/cypress-component-examples/blob/issue-20070/vite-react/src/App.spec.jsx

I'm getting 200 response codes across the board, in Firefox, Electron and Chromium.

If you run my branch of the sample project, are you seeing the same? If so, it might help you narrow it down / provide a reproducible example. If not, then that's helpful too - it would point heavily towards environmental differences.
