### ISSUE TITLE
on(...) types do not match cy.stub() format

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2007]
The TypeScript definition of `Cypress.on` and `cy.on` are not working correctly if you use `cy.stub` callback function. Example from Cypress `window:alert` documentation https://docs.cypress.io/api/events/catalog-of-events.html#Window-Alert

<img width="391" alt="screen shot 2018-06-21 at 1 08 49 pm" src="https://user-images.githubusercontent.com/2212006/41734209-44b42632-7554-11e8-880e-7be9b77fcf31.png">

Notice red line when I am using `cy.stub()` callback, this is because I am using `//@ts-check` in my specs. The types correctly work if I use "regular" callback function

Both `Cypress.on` and `cy.on` show red lines and show an error

![cy on](https://user-images.githubusercontent.com/2212006/41734278-6fe79ab4-7554-11e8-953c-f89252a2e268.jpeg)

Same for `cy.on('window:confirm', cy.stub())`

Cypress v3.0.1

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
