### ISSUE TITLE
Windows 10-Cypress Error-"Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds." while trying to run in the chrome/electron browser in headed or headless mode.

### ISSUE THREAD

**Issue by Praveentrp** [cypress-io/cypress#20074]
### Current behavior

We are getting the below error, while trying to run the cypress scripts through chrome/Electron browser, 
`Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 60***.

Error details:

Error: could not find CRI target at lazyAssLogic (C:\Cypress\9.4.1\Cypress\resources\app\node_modules\lazy-ass\index.js:110:14) at lazyAss (C:\Cypress\9.4.1\Cypress\resources\app\node_modules\lazy-ass\index.js:115:28) at findStartPage (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\lib\browsers\protocol.js:56:28) at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Stack trace
`Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m60489[**m.

Error details:

Error: could not find CRI target
    at lazyAssLogic (C:\Cypress\9.4.1\Cypress\resources\app\node_modules\lazy-ass\index.js:110:14)
    at lazyAss (C:\Cypress\9.4.1\Cypress\resources\app\node_modules\lazy-ass\index.js:115:28)
    at findStartPage (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\lib\browsers\protocol.js:56:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at get (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\lib\errors.js:1043:15)
    at Object.throwErr [as throw] (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\lib\errors.js:1061:9)
    at C:\Cypress\9.4.1\Cypress\resources\app\packages\server\lib\browsers\protocol.js:113:21
    at tryCatcher (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Cypress\9.4.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:464:21)`

Chrome crashed Screenshot:
![image](https://user-images.githubusercontent.com/96192630/152822179-e0923439-f184-44c2-8d79-15c01821a1d3.png)

### Desired behavior

Chrome browser should open successfully inside the cypress test runner.

### Test code to reproduce

1. Run the below command: 
"ELECTRON_EXTRA_LAUNCH_ARGS=--disable-gpu-sandbox ./node_modules/.bin/cypress open --env environment=SIT" or "ELECTRON_EXTRA_LAUNCH_ARGS=--disable-gpu-sandbox npx cypress open --env environment=SIT"
**Note:** We are adding the environment variable "ELECTRON_EXTRA_LAUNCH_ARGS=--disable-gpu-sandbox" as mentioned in the below ticket https://github.com/cypress-io/cypress/issues/19924 by @flotwig.

2. Select any feature file which you want to be executed in the SIT environment.

### Cypress Version

9.4.1

### Other

This is the continuation of the issue number https://github.com/cypress-io/cypress/issues/19924

**Comment by flotwig** [comment]
@Praveentrp did this start with a recent release of Cypress? 

Is it possible you have group policy set? https://docs.cypress.io/guides/references/error-messages#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues

Does `--browser electron` work?

Possibly a duplicate of https://github.com/cypress-io/cypress/issues/15650

**Comment by Praveentrp** [comment]
Hi @flotwig 

When I try to run with --browser electron, then I am getting the below error. Also, I am trying with the recent cypress release v9.4.1.

**Command used:** "ELECTRON_EXTRA_LAUNCH_ARGS=--disable-gpu-sandbox npx cypress run --env environment=SIT --spec cypress/integration/RetailIB/example.feature --browse electron"

**Console error log:**

`We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed
ERR_FAILED (-2) loading 'http://localhost:8081/__/#/tests/integration/RetailIB/example.feature'
Error: ERR_FAILED (-2) loading 'http://localhost:8081/__/#/tests/integration/RetailIB/example.feature'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.stopLoadingListener (node:electron/js2c/browser_init:165:7861)
    at Object.emit (node:events:394:28)`

**Comment by onthespotqa** [comment]
i've also run into these issues in ci. it's been happening since 9.2. Our configuration is circleci ubuntu-2004:202201-02 and the cypress docker image cypress/browsers:node16.14.2-slim-chrome100-ff99-edge.
