### ISSUE TITLE
Allow JS configuration files (instead of JSON)

### ISSUE THREAD

**Issue by stdedos** [cypress-io/cypress#20086]
### What would you like?

I would prefer the configuration files to be of JS format.

### Why is this needed?

(Strict) JSON file type is too strict for my liking (e.g. no comments, no trailing commas, etc etc)

**Comment by emilyrohrbough** [comment]
Hi @stdedos in the upcoming 10.0 release of Cypress, JS configuration files will be supported.

**Comment by stdedos** [comment]
When would that be? I see no references of v10 e.g. here https://docs.cypress.io/guides/references/roadmap

**Comment by flotwig** [comment]
@stdedos we are aiming to get 10.0 out in the next 2 months. For a preview of the changes, you can see the [WIP migration guide for 10.0](https://deploy-preview-4186--cypress-docs.netlify.app/guides/references/migration-guide#Migrating-to-Cypress-version-10-0-0)
