### ISSUE TITLE
Non third-party multi window testing in an SPA use case

### ISSUE THREAD

**Issue by codingnuclei** [cypress-io/cypress#20085]
### What would you like?

Hi - I know that this feature has been raised many times and I have read and understand cypress' viewpoint on the matter.
 #19739 #19896 #15812 #7215 #5952 #590

I do believe I have a use case where it is valid reason to be able to test over multiple windows.  I want to raise this issue just to document it and highlight it to the team.

### Why is this needed?

We have an internal enterprise Angular 2+ application that is often run in a small window (say 2000px by 500px).

Due to the small window size - a window popup is used to gather form data before submitting and exiting the flow.

The SPA is time critical - so rather than bootstrapping the whole application again in the window popup we inject and render a single component instead and control this component's lifecycle from the application running in the opener window.

Here is a basic stackblitz showing this technique in action: https://stackblitz.com/edit/portal-simple-kx9qgf?file=src/app/services/popout.service.ts

This means that:

-  There is no route to navigate to that will load the required view.
-  The window popup is created dynamically by interaction with the main window/application
- The main application behaves differently based on the actions in the window popup

### Other

I understand that many use cases presented previously can be avoid using techniques highlighted in the docs - but I hope the above highlights a non third-party use case for multi window support.

**Comment by YglesEyes** [comment]
The multiple window should be very interesting in embedded Man Machine Interface.

For our products we have 3 types of authentication process:
- Multiple user: All user can be connected at the same time
- Single user and block: If an user is already connected the current user which try to connect must be blocked
- Single user and eviction: If an user is connected and an other want to connect, the first one must be disconnected (like windows remote desktop)

Another use case:
- There is 2 interfaces into a same product, 1 for control/command and another for read only display (navigation for example)
- If an user change some parameters into one of the 2 interfaces the second interface must be updated without needed a page refresh
- The 2 windows must be fully independent (cookie, local storage etc...) and/or not necessary the same browser
