### ISSUE TITLE
cy.contains fails to find an element

### ISSUE THREAD

**Issue by jasonLaster** [cypress-io/cypress#201]
**test case:** list of items and the first one is inside an element with `visible: false` even though the rest are visible.

We ran into this with Codemirror, when it was instantiated without a default value. In this case, the first element was hidden, but the rest were visible, and cypress could not find a child element down the list.

**Comment by brian-mann** [comment]
Can you create a small reproducible repo showcasing this problem? I cannot reproduce locally.

**Comment by jasonLaster** [comment]
A simple way to reproduce what we saw would be to create a codemirror instance without default text, then add text and try to select the second line number.
