### ISSUE TITLE
cy.get("h2").contains("My page") doesn't work. Other methods yes!

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#2010]
### Current behavior:

The first method doesn't work at all! Never. And I don't understand why from the docs.

### Desired behavior:

I think the 4 methods below are the same, right? I also read this: https://github.com/cypress-io/cypress/issues/1805

### Steps to reproduce:

```js
- cy.get("h2").contains("My page"); // Doesn't work! Never! Why?
- cy.get("#root > div > div > div.col-md-10 > div > div.d-flex > h2").contains("My page"); // Works!
- cy.contains("h2", "My page"); // Works!
- cy.get("h2").should("contain", "My page"); // Works!
```

### Versions

- Cypress 3.0.1
- Chrome 67

**Comment by bahmutov** [comment]
Can we have the page where this happens?

**Comment by johnunclesam** [comment]
Unfortunately is not on the public internet!

And it is a mess to reproduce exactly it.

But the question is why every time (100 times!) the methods are working and the first one no!?

**Comment by brian-mann** [comment]
@johnunclesam all you need to do is visit your application, get it to the page where this happens and then export everything as `.html` so its completely static.

From there boot up a static webserver to host the assets, and then visit it in Cypress.

Then start yanking out all the HTML elements until you can boil it down to the very simplest reproducible scenario.

**Comment by johnunclesam** [comment]
@brian-mann I have just one "h2" in the page.

If I use `cy.get("h2").first().contains("My page");` it doesn't work either.

If I use `cy.wait(50)` it works with `cy.get("h2").contains("My page");`.

Something strange is happening...

**Comment by jennifer-shehane** [comment]
Is the `h2` visible on the page when the error occurs? 
Can you paste the screenshot of the application at this step? So, using the Command Log, [click on the command](https://docs.cypress.io/guides/core-concepts/test-runner.html#Command-Log) and see if the h2 is rendered on the page when the command runs.

**Comment by johnunclesam** [comment]
> Is the h2 visible on the page when the error occurs?

Yes, and the other three methods are working good in fact.

`h2` is present.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
