### ISSUE TITLE
Improvements/fixes for reading state.json

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2013]
In an attempt to mitigate [Cypress randomly hanging in CI](https://github.com/cypress-io/cypress/issues/1912), implement the following:

1. Add debug logs around reading/writing/locking/unlocking files, so if the issue occurs again, they'll hopefully provide more information
2. Stop the `state.json` file from being read during `run` mode. The last log before Cypress hanging is the `state.json` being read, so it's possible it is the cause. Since we solely persist state related to the GUI/browser in interactive mode, it's not necessary to read it at all during a run. This may solve the issue.
3. Add a timeout for unlocking a file. If the hanging is indeed caused by the `state.json`, it's likely it's actually unlocking the file that never resolves. It would be better to time out in this scenario, catch the timeout, and carry on without the file unlocked. There's already a timeout on getting a lock on the file, so subsequent read and writes will handle that accordingly.
4. Add a whitelist for keys that can be saved in `state.json`. Currently, it allows any arbitrary keys to be written to it, making it difficult to tell what state it actually can possibly contain. This will document the keys in the code.

**Comment by bahmutov** [comment]
Excellent ideas and we can document the keys using json schemas to enforce them

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
