### ISSUE TITLE
Configuring cypress through cypress.js, not only cypress.json

### ISSUE THREAD

**Issue by stopsopa** [cypress-io/cypress#20148]
### What would you like?

Configure cypress not only with cypress.json but also through common js style cypress.js.

### Why is this needed?

- It would provide more flexibility to parametrise programatically cypress (json is just data notation, but js is a programming language - we could inject something programatically. Like read .env directly in cypress.js - just example). Without that developer is limited to what cypress provides only.
- It would be possible to comment config. there is not comments in json

**Comment by flotwig** [comment]
This is planned, please see #20086 for some more details. Closing as duplicate.
