### ISSUE TITLE
cypress seems to pick up cached webpage

### ISSUE THREAD

**Issue by fangquan** [cypress-io/cypress#20159]
### Current behavior

I changed my webpage to cause a test fail, after that I changed it back to expect the test pass, but cypress seems to visit the old version webpage and still fails. 

It appears cypress will visit some cached version of webpages??

### Test code to reproduce

N/A

### Cypress Version

Cypress package version: 9.4.1

**Comment by BlueWinds** [comment]
You haven't provided a lot of details to go on, so here's some relatively generic information that might help.

> cy.intercept() intercepts requests at the network layer. This can cause confusion when trying to intercept a request that has already been cached by the browser. If a request is served from the browser cache, it will never hit the network layer, and cy.intercept() will never fire.

https://docs.cypress.io/api/commands/intercept#cy-intercept-and-request-caching

Also worth noting that Cypress does not override the browser's default caching behavior - if your requests have headers indicating the browser should cache responses, it may be the browser deciding not to call the server at all.
