### ISSUE TITLE
Cypress failed to start

### ISSUE THREAD

**Issue by gopi-git-hub** [cypress-io/cypress#20167]
### Current behavior

After installation when we try to open error is appearing.>>>It looks like this is your first time using Cypress: 5.6.0

  ✖  Verifying Cypress can run /home/gopinath/.cache/Cypress/5.6.0/Cypress
    → Cypress Version: 5.6.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

/home/gopinath/.cache/Cypress/5.6.0/Cypress/Cypress: 1: Syntax error: word unexpected (expecting ")")

----------

Platform: linux (Ubuntu - 20.04)
Cypress Version: 5.6.0

### Cypress Version

5.6.0

### Package Manager

npm

### Operating system

Linux

**Comment by BlueWinds** [comment]
Cypress 5.6 is fairly old at this point, having been released in November 2020.  The current release is 9.5.0 - is there a reason you're trying to use such an old version?

You can also make it easier to read code you've copy-pasted from the terminal by enclosing it in triple ticks.
```
`` `
Like this (but without the spaces)
`` `
```
