### ISSUE TITLE
cypress/mount utils needs `type: module`

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#20166]
### Current behavior

1. Install `@cypress/mount-utils`
2. Start Vite project that imports this in some capacity (like via `@cypress/react`)
3. Obseve

```
@cypress/mount-utils doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't 
have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

### Desired behavior

Not show that warning.

### Test code to reproduce

1. Create a Vite project
2. Install `@cypress/mount-utils`
3. Config component testing and import this module
4. See that warning

### Cypress Version

9.x

### Other

I can make a PR for this, just need to change `type: module` in `package.json` (I think).

**Comment by BlueWinds** [comment]
If you want to make a PR for this, I'd be happy to test + review.

**Comment by lmiller1990** [comment]
We fixed this at some point or another, works great now.

**Comment by lmiller1990** [comment]
Here's the ESM entry: https://github.com/cypress-io/cypress/blob/develop/cli/package.json#L129
