### ISSUE TITLE
Voice commands not working in Cypress

### ISSUE THREAD

**Issue by ganeshac123** [cypress-io/cypress#20174]
### Current behavior

Voice commands not working in Cypress.

### Desired behavior

Voice commands should work in Cypress.

### Test code to reproduce

.get('[data-cy=section-content-history]').click({ force: true })
        .playAudioURL('https://storage.googleapis.com/audiofiles-e2e/fever.mp3', 15000)

### Cypress Version

8.3.1

**Comment by ganeshac123** [comment]
@cy-veronica @cypress-app-bot @CypressAdam

**Comment by flotwig** [comment]
Hi, this issue will have to be closed as there is not enough detail. If you are still encountering this issue on the latest version of Cypress, please open a new issue with a reproducible example and a description of the current vs. expected behavior.
