### ISSUE TITLE
Cypress form element: Getting elements from an Iframe within an Iframe

### ISSUE THREAD

**Issue by Corbz69** [cypress-io/cypress#20173]
I had an issue the other day (Took me a while to figure it out) but wanted to share with the community that always shares with me!

My issue I had was: I needed to get to an element which was housed in an Iframe (My companies) and a second Iframe (3rd Parties) to enter a passCode and then click a "Continue" button.

First thing I needed was the 3rd parties iframe (iframeTwoBody) element so I could type a passCode into it once I did this I needed to access a Form element in my companies iframe one level up (iframeOneBody) element was "input.button"

See my code below:

```
cy.get('iframe')
      .then(($iframe) => {
      const $iframeOneBody = $iframe.contents()
      const $iframeTwoBody= $iframe.contents().find('#putTheNameOfTheSecondIframeHERE').contents()

      cy.wrap($iframeTwoBody)
      .find('input#elementName')
      .click({force: true})
      .type('things here', { force: true })

      cy.wrap($iframeOneBody)
      .find('input.button')
      .click({force: true})
      })
```
I hope this helps..

_Originally posted by @Corbz69 in https://github.com/cypress-io/cypress/issues/136#issuecomment-1039053095_

**Comment by BlueWinds** [comment]
I'm going to close this issue, since there's nothing actionable for us in here, but thanks for sharing! Hopefully this points someone else looking to do something similar in the right direction, and glad you're finding the community helpful. :)

**Comment by rupesh1395kumar** [comment]
Thank you this one helped me
