### ISSUE TITLE
Unable to Test Link That Scrolls to Element

### ISSUE THREAD

**Issue by aetherealtech** [cypress-io/cypress#20187]
### Current behavior

Cypress currently will scroll to an element when clicking it, which interferes with any scrolling that is induced by the app under test when clicking that element.  Adding the option `scrollBehavior: false` disables not just the Cypress scrolling but also the scrolling the app is supposed to do.  The only two available options are to enable scrolling, which causes Cypress's scrolling behavior to interfere with the scrolling behavior we're trying to test, or disabling scrolling behavior, which breaks what we are trying to test.

We found that our test passes if we run in interactive mode and press "Disable Auto-Scrolling".  However, we cannot find any equivalent option when running in headless mode.  All the suggestions we found for an equivalent option are to pass `scrollBehavior: false` to a test, but as mentioned, this causes different behavior where in scrolling even by the app is disabled.

### Desired behavior

There should be an option to disable scrolling by Cypress when interacting with an element that does not disable any scrolling that the app itself would trigger by interacting with those elements.

### Test code to reproduce
```
const ComponentWithScrollingLink = () => {
  return <div>
      <a href="#target" aria-label={"Scrolling Link"}>
        Click Me!
      </a>
      <div style={{height: '100vh'}}/>
    <div id="target" aria-label={"Scrolling Target"}>
      Hello!
    </div>
  </div>;
}
```

```
it('Tries to click scrolling link', () => {
    cy.visit('/');
    const findLink = () => cy.get(`[aria-label="Scrolling Link"]`);
    findLink().click();
    cy.get(`[aria-label="Scrolling Target"]`).should(($el) => {
      const windowInnerWidth = Cypress.config(`viewportWidth`);
      const windowInnerHeight = Cypress.config(`viewportHeight`);

      const bounding = $el[0].getBoundingClientRect();

      const rightBoundOfWindow = windowInnerWidth;
      const bottomBoundOfWindow = windowInnerHeight;

      expect(bounding.top).to.be.at.least(0);
      expect(bounding.left).to.be.at.least(0);
      expect(bounding.right).to.be.lessThan(rightBoundOfWindow);
      expect(bounding.bottom).to.be.lessThan(bottomBoundOfWindow);
    });
  });
```

### Cypress Version

9.4.1

**Comment by BlueWinds** [comment]
I've not been able to reproduce the issue based on the description. Consider the following test:
```
it('scrolls', () => {
  cy.visit('https://en.wikipedia.org/wiki/France')

  cy.get(`[href="#Culture"]`).click({ scroll: false});

  cy.get(`#Culture`).should(($el) => {
    const windowInnerWidth = Cypress.config(`viewportWidth`);
    const windowInnerHeight = Cypress.config(`viewportHeight`);

    const bounding = $el[0].getBoundingClientRect();

    const rightBoundOfWindow = windowInnerWidth;
    const bottomBoundOfWindow = windowInnerHeight;

    expect(bounding.top).to.be.at.least(0);
    expect(bounding.left).to.be.at.least(0);
    expect(bounding.right).to.be.lessThan(rightBoundOfWindow);
    expect(bounding.bottom).to.be.lessThan(bottomBoundOfWindow);
  });
})
```
This test passes in Firefox:

![image](https://user-images.githubusercontent.com/3003404/154572671-61693ad8-fec5-443a-afcb-350d9e4e114d.png)

And fails in Chrome:

![image](https://user-images.githubusercontent.com/3003404/154572778-69a7f1b5-325b-4c37-b3e3-258b47b682f1.png)

But I'm not sure I'd say that Cypress's scrolling behavior is the cause in either case.

Running the test, cypress briefly scrolls to the "Culture" link before clicking on it, and it's the browser's slightly different behavior (by a couple of pixels) that results in the exact value of `bounding.top` differing. It looks like this is related to the navigation bar's `box-shadow` css, exactly how far the browser scrolls the AUT's iframe - but this is the browser's behavior differing around a static header after cypress' scrolling is already complete.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
