### ISSUE TITLE
`cy.request` hangs in headless mode on big rejected response

### ISSUE THREAD

**Issue by marcandre** [cypress-io/cypress#20183]
### Current behavior

If server responds with >=400 status code and big body, the following line will systematically hang in headless mode:

```js
cy.request(some_url) # => hangs for hours
```

In interactive mode, this test fails as it should.

Note: our big body was ~1.2MB, I didn't check further what's the size threshold. This might be an Electron bug

### Desired behavior

Cypress should not hang.

### Test code to reproduce

I couldn't find a way to start a server from https://github.com/cypress-io/cypress-test-tiny
I can't use `cy.intercept` either.
If `cypress-test-tiny` is modified to include a basic npm server, I will provide a complete exmaple.

### Cypress Version

  │ Cypress:        9.4.1                                                                          │   │ Browser:        Electron 94 (headless)                                                         │   │ Node Version:   v17.2.0 (/usr/local/Cellar/node/17.2.0/bin/node)                               │

**Comment by emilyrohrbough** [comment]
@marcandre Are you still experiencing this issue? If so, can you try running with our verbose debug logs enabled to determine if this a browser crash? `DEBUG=cypress* cypress run`
