### ISSUE TITLE
Please use the releases feature of github so that people can see what you have released and be able to browse the code related to the release

### ISSUE THREAD

**Issue by KellyR-STCU** [cypress-io/cypress#2019]
It seems like it would make a lot of sense to use the releases feature on github so that people can understand what your progression is and when things have happened.  I think it is basically as simple as using tags.

An example of this is:

https://github.com/angular/angular/releases

Also an example of a specific release:

https://github.com/angular/angular/compare/6.1.0-beta.2...master

You can see when the release occurred as well as the commits that went into the release.

**Comment by brian-mann** [comment]
We've talked internally recently about adding releases - but using only the tag feature. It will not include the full binary or the changelog - just the actual source pointing to that commit, which I think is all that's needed.

Currently we use `milestones` so if you'd like to see what's going to be included in `3.0.2` just look here: https://github.com/cypress-io/cypress/milestones?direction=asc&sort=due_date

**Comment by jennifer-shehane** [comment]
I agree, I would like to see this! Closing this as duplicate: https://github.com/cypress-io/cypress/issues/2006
