### ISSUE TITLE
[Multi-domain]: Fix error with re running the test after an error.

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#20197]
### What would you like?

When a test containing a switchToDomain block fails the subsequent tests also fail.

This can also be caused by hot reloading within a test. 

If the switch to domain command has exited without achieving stability this seems to occur.

### Why is this needed?

Tests should not fail in this manner

**Comment by mschile** [comment]
Closing as I am no longer able to reproduce this issue. It appears to have been resolved with this change: https://github.com/cypress-io/cypress/blob/c8c20467157ffa9a6f15d8e32efece26611c67e1/packages/runner-shared/src/event-manager.js#L594
