### ISSUE TITLE
Cypress Dashboard - all videos frozen after a couple of seconds

### ISSUE THREAD

**Issue by tmarcinkowski-logitech** [cypress-io/cypress#20195]
### Current behavior

Every video I tried viewing - either directly in Cypress Dashboard, or locally after downloading it - freezes after a couple of seconds. The playback "continues" but the frame is stuck.

This only happens for tests run in the AWS CodeBuild and sent to Cypress Dashboard.  
Videos recorded on local test runs are fine.

### Desired behavior

The video should show all test runs till their end.

### Test code to reproduce

An example run. Try viewing any of the videos.
https://dashboard.cypress.io/projects/25pyh1/runs/4/specs

### Cypress Version

9.4.1

### Other

The AWS CodeBuild action uses this particular (official) Docker image:  
```
public.ecr.aws/cypress-io/cypress/browsers:node14.17.0-chrome88-ff89
```

Electron 94
Linux Debian - 10.9

**Comment by tmarcinkowski-logitech** [comment]
It's reproducible with Cypress 9.5.0. But I found out that this happens only with Electron and not Chrome.

**Comment by SimonasB88** [comment]
Same for me using 
```
cypress_1  |   │ Cypress:        9.5.0                                                                          │
cypress_1  |   │ Browser:        Electron 94 (headless)                                                         │
cypress_1  |   │ Node Version:   v16.5.0 (/usr/local/bin/node)                                                  │
```
Somehow I can not see the ending of the clip also.

**Comment by andrei10k** [comment]
Same thing happens for me. Cypress v9.5.3

**Comment by jennifer-shehane** [comment]
Usually this is indicative of their not being enough CPU to run cypress, any other services you have running, and to record video. 

You can log the memory and CPU usage of Cypress by following these instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage This will help determine if Cypress is running out of resources and whether the machine requires more.

**Comment by cnotv** [comment]
My issue got solved by changing the browser from Electron to Chrome.
