### ISSUE TITLE
enter title in cypress.json

### ISSUE THREAD

**Issue by jheijkoop** [cypress-io/cypress#202]
I have several small projects all called `cypress`, because the folder is named that way. I would like to name test project by entering a `title` somewhere, for instance in the `cypress.json`. This would help me distinguish between the projects in a more friendly manor than moving project to a differently named folder. :D

**Comment by brian-mann** [comment]
Where would you like title to be displayed exactly?

**Comment by jheijkoop** [comment]
In the menu in the cypress gui, before opening any test, just after running `cypress open`. This where you select which project/suite to run. Currently is just shows you the folder of the project as distinguishing feature

**Comment by jennifer-mann** [comment]
@jheijkoop You can now rename projects from the [Cypress Dashboard](https://on.cypress.io/dashboard) or from the Desktop when [Setting up the Project to Record](https://on.cypress.io/guides/projects#section-setting-up-a-project-to-record).

**Comment by jheijkoop** [comment]
hmm, that is not commitable to revision control and requires online interaction. This not exactly what I had in mind
