### ISSUE TITLE
Cypress may leak secrets into output

### ISSUE THREAD

**Issue by alxy** [cypress-io/cypress#20214]
### What would you like?

I'm running Cypress in a CI environment (Azure pipeline) and have configured it as recommended to use `cy.request()` in a `beforeEach` hook to programmatically login to my application. The application uses AAD authentication (OAuth), thus this request contains a `clientId` and `clientSecret` to actually get an access token. These secrets are supplied via environment variables in my pipeline so that they are not checked in to source control.
I have also set up a [reporter](https://docs.cypress.io/guides/tooling/reporters) to have some nice dashboards for my test results directly within the CI environment. Now I have the problem that developers potentially do something to the tests which make the initial token requests fail (maybe because they have modified the pipeline itself, or just because some of the credentials changed). In that case, the full request (including the body, which includes client ids and secrets) and response is logged in my test results view:
```
cy.request() failed on:  https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/token  The response we received from your web server was:    > 400: Bad Request  This was considered a failure because the status code was not 2xx or 3xx.  If you do not want status codes to cause failures pass the option: failOnStatusCode: false
<!-- HERE IS THE FULL STACKTRACE INCLUDING THE REQUEST BODY (CLIENT SECRETS, IDS, ) -->
```

### Why is this needed?

I do not want these secrets to be available in plain text in my CI environment. A lot of people have access to these logs, whereas only a small amount of people has access to the actual secrets usually.
It's not that critical on the development environment, however, we do plan to run these tests also on a production-like environment where we can not accept leaking these secrets.
Is there a way to suppress the secrets in the output?

### Other

Cypress version: `9.4.1`

**Comment by BlueWinds** [comment]
I may be misunderstanding the situation here, but it sounds like your reporter is the one outputting the strings which are then visible. If that's the case, would it be possible to filter the text output? Something like

`text.replace(\"clientId":".*?"\g, '"clientId":"****"')`

is an approach I've seen taken before.

**Comment by alxy** [comment]
We have used the following alternative now:

```typescript
cy.request({
      url: authority + '/oauth2/v2.0/token',
      method: 'POST',
      body: {
           // ...
      },
      form: true,
      failOnStatusCode: false, // Do not immediately fail here to avoid leaking client credentials
    }).then((response) => {
        if(!response.isOkStatusCode) {
          throw new Error(response.body.error_description);
        }

        return response;
    });
```

**Comment by mercer** [comment]
We run into this issue as well. I believe this is what's happening

1. [Reporters](https://docs.cypress.io/guides/tooling/reporters#Custom-reporter), more precisely, [Junit reporter](https://github.com/michaelleeallen/mocha-junit-reporter) decides to create that output body including the headers --> this is where the leak happens 
2. [toConsole](https://docs.cypress.io/guides/tooling/reporters#Config-file-1) prints this in the task console output
3. And we rely on junit format to publish test result in the pipeline, resulting that the value is leaked there as well

Not clear to me where does the junit reporter harvest the request headers readable output.

We'll try the same approach as handling the failOnStatusCode ourselves, but this is a broader issue of leaking secrets when executing tests over a production environment.
