### ISSUE TITLE
Performance Issue Between Cypress 8.3.1 and Latest 

### ISSUE THREAD

**Issue by matthewhartman** [cypress-io/cypress#20213]
### Current behavior

Hi There,

I currently have a Single Page Application which I am running a Cypress test suite against in headless mode.

After setting up all the tests with the latest Cypress 9.5.0 (as of today) - each test varied from 47000ms - 173000ms (each test seemed to get slower towards the end).

I stumbled across this issue:
https://github.com/cypress-io/cypress/issues/18740

and tried downgrading to a locked down version of Cypress 8.3.1.

After doing so I noticed a big performance increase - each test varied from 21000ms -  34000ms.

I am not sure if this is an issue with Electron or Cypress.

I noticed that Cypress 9.5.0 is using Electron 94 and 8.3.1 is using Electron 91.

Just wondering if this is something related to Cypress or Electron?

Cheers.

### Test code to reproduce

N/A

### Cypress Version

9.5.0

**Comment by jameskraus** [comment]
Just chiming in: I'm doing a similar upgrade from 7.7.0 and I'm also finding the more recent versions of Cypress require more than 2x the CPU we used to require. We're running against beefy GCP nodes, but it seems there's been a significant performance regression.

**Comment by jfheins** [comment]
I, too, was looking to upgrade our cypress version. I have ran a subset of our tests across different cypress versions and newer ones are way too slow:
![image](https://user-images.githubusercontent.com/5293502/164684006-052ff6da-8a1d-4ce1-b3ca-81d04c007e37.png)

So far we are using 8.2.0 and the speed is bearable but 8.6.0 and later is too slow.
