### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'measure')

### ISSUE THREAD

**Issue by danielkv** [cypress-io/cypress#20215]
### Current behavior

The cypress says that the error occured on my code, but I didn't find anything wrong

This is the error:
![image](https://user-images.githubusercontent.com/5912401/154263893-1252703c-3890-48aa-a4bd-5e447118fd26.png)

![image](https://user-images.githubusercontent.com/5912401/154264674-bded965e-a35a-45b1-a994-f6bda3379595.png)

The error is **random**. When use `it.only` DOES NOT return any error, the test run successfully. But if I run 2 or more errors at the same time, it returns this error.

I'm running it also on GitHub Actions and it doesn't seem to be happening it, last time the tests ran successfully.

### Desired behavior

Run tests smotth.

### Test code to reproduce

```js
it.only('should return to home when user click "close" during review page', () => {
        const SELECTED_RATING = 4;

        const mockReviews = [professionalReviews.data[0]];
        cy.intercept(
            { method: 'GET', pathname: /\/review\/.*/ },
            {
                body: professionalReviews.data[0],
            }
        ).as('getReview');

        cy.intercept(
            { method: 'POST', pathname: /\/review\/listpending/ },
            {
                body: { items: mockReviews },
            }
        ).as('listPendindReviews');

        cy.setCachedUser(completeClient as IUser, authResponse as unknown as TAuthResponse);

        cy.visitWithGeolocation('/');

        cy.wait('@listPendindReviews')
            .getTestID('VotingStar')
            .eq(SELECTED_RATING - 1)
            .click();

        cy.url().should('include', '/profissional/avaliar');

        cy.getTestID('CloseButton').click();

        cy.url().should('include', '/home/');
});
```

### Cypress Version

9.5.0

### Other

I'm running on WSL2 on Windows 11 with **XLaunch**

**Comment by sainthkh** [comment]
Sorry for the late reply.

Without the website code under test, it's impossible for us to fix the problem. 

Can you provide us a reproducible code example? As we all know, debugging starts with reproducing the problem on the developer's machine.

**Comment by danielkv** [comment]
Hi @sainthkh I got to fix it yesterday, it actually happened because of a package `react-native-ratings` that was upgraded and something went wrong.

I'm not sure what exactly what happened in the package, but it seems to be it was upgraded, because it was working before.

Anyway, my solution was remove the package and use the one I developed.
