### ISSUE TITLE
Unable to override javascripts config in plugins

### ISSUE THREAD

**Issue by pjean** [cypress-io/cypress#2022]
### Current behavior:

When [javascripts](https://github.com/cypress-io/cypress/blob/df0ec8ea8cd49befec6f1244c5a189857b9d7fe6/packages/server/lib/config.coffee#L110) config property is overridden in the plugin the error below occurs. This issue is similar to #1736 despite that `javascripts` is a property of the default configuration (but a deprecated one regarding this [comment](https://github.com/cypress-io/cypress/blob/df0ec8ea8cd49befec6f1244c5a189857b9d7fe6/packages/server/lib/config.coffee#L109))

You might wonder why I want to use `javascripts` property which seems to be deprecated. Because, it's the only way I found to add javascript script code dynamically in the iframe spec before running test. My aim is linked to this issue cypress-io/cypress-webpack-preprocessor#19, I want add the vendor lib script of my applicaion to the iframe spec in order to avoid webpack long time processing and initialize the window correctly.

The stack trace below is visible with `DEBUG=cypress:*`:

```
cypress:server:events send error: TypeError: Cannot set property '0' of undefined
at /Users/i314982/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:302:37
at arrayEach (/Users/i314982/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:537:11)
at Function.forEach (/Users/i314982/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9359:14)
at setResolvedOn (/Users/i314982/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:298:18)
at /Users/i314982/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:300:20
at /Users/i314982/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4944:15
at baseForOwn (/Users/i314982/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:3001:24) 
```

### Desired behavior:

When `javascripts` property is overridden in plugin, the config should be merged into the main config, and no error is shown.

### Steps to reproduce:

Simply place the following code in `plugins/index.js` file.
```js
module.exports = (on, config) => {
  config.javascripts = [
    'dist/vendor.bundle.js'
  ];
  return config;
};
```

### Versions

Cypress package version: 3.0.1
Cypress binary version: 3.0.1

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

My plugins/index.js file

```js
module.exports = (on, config) => {
  config.javascripts = [
    'bundle.js'
  ];
  return config;
};
```

My test code

```js
it('fail error', () => {
  cy.visit('index.html')
})
```

My index.html

```html
<!DOCTYPE html>
<html>
<head>
  <script>
  </script>
</head>
<body>
  <div id="main"></div>
</body>
</html>
```

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
