### ISSUE TITLE
Search is disabled in browser runner window

### ISSUE THREAD

**Issue by saschwarz** [cypress-io/cypress#20222]
### Current behavior

Prior to 9.5.0(?) setting focus in the browser runner window and typing Cmd-F to search for text would search the text within the browser window. Now Cmd-F is captured and focus is shifted to the search bar in the Cypress app and the names of tests are searched.

I use search within the browser window as a normal part of my testing debugging workflow: to find specific steps, to find accessible roles that aren't matching exactly, to find logging, etc.

### Desired behavior

Please restore the default browser search functionality

### Test code to reproduce

No specific test code is required.

### Cypress Version

9.5.0

**Comment by BlueWinds** [comment]
I agree this is not great usability.

It looks like this happened in https://github.com/cypress-io/cypress/issues/248, when we added test runner keyboard shortcuts ([docs](https://docs.cypress.io/guides/core-concepts/test-runner#Keyboard-Shortcuts)). In https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/lib/shortcuts.ts we're not checking for modifier keys (like `ctrl`) when deciding how to react to keypresses.

This is something we'd like to address, and I'll see when we can get to it; a pull request would be very welcome if anyone wants to create one, should be fairly straightforward.

**Comment by majidzeno** [comment]
@saschwarz It's merged now 🎉

**Comment by BlueWinds** [comment]
Forgot to tag this with a release before merging, so the bot didn't comment properly. This is merged into the develop branch, and will go out with the next Cypress release.
