### ISSUE TITLE
Cypress automatically redirecting to different url 

### ISSUE THREAD

**Issue by Saravanakumarsivan** [cypress-io/cypress#20230]
### Current behavior

I have some plenty of it blocks, after executing the some it blocks the page redirected to different url

### Desired behavior

In UI I have 5 tabs ,code started running on the first tab with lot of assertion inside the it block and successfully passed for the first tab,when code clikcs the 2nd tab page is automatically redirected to the different URL.

### Test code to reproduce

It{}
It{}
It{}
It{}
After the above blocks
It{}
Its redirected to another page

### Cypress Version

7

**Comment by BlueWinds** [comment]
You can make code you're pasting into a comment a lot more readable by enclosing it in triple ticks:
```
code()
```

With that said, I'm not really sure exactly what you're describing here - the presented code is definitely not valid Javascript. Perhaps some of these docs pages will be helpful:

https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-test-anchor-links-that-open-in-a-new-tab
https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__tab-handling-links

**Comment by sainthkh** [comment]
Closing because of the inactivity.
