### ISSUE TITLE
Drag and drop is not working

### ISSUE THREAD

**Issue by sashan4u007** [cypress-io/cypress#20232]
### Current behavior

I tried to drag below element 
`        var modelSchemaString = "//div[@id='toolbox-stub-[MODEL_NAME]']";
        const draggable = cy.xpath(modelSchemaString.replace('[MODEL_NAME]', 'Calendar'))  // Pick up this
`
and drag to following element 
`        const droppable = cy.xpath("//div[@id='mfgx-data-flow-diagram']")  // Drop over this
`

using three approaches but could not get success

1st - 
```
    dragAndDrop() {
        var modelSchemaString = "//div[@id='toolbox-stub-[MODEL_NAME]']";
        const draggable = cy.xpath(modelSchemaString.replace('[MODEL_NAME]', 'Calendar'))  // Pick up this
        const droppable = cy.xpath("//div[@id='mfgx-data-flow-diagram']")  // Drop over this

        const coords = droppable.getBoundingClientRect()
        draggable.dispatchEvent(new MouseEvent('mousedown'));
        draggable.dispatchEvent(new MouseEvent('mousemove', {clientX: 10, clientY: 0}));
        draggable.dispatchEvent(new MouseEvent('mousemove', {
            clientX: coords.x+10,   
            clientY: coords.y+10  // A few extra pixels to get the ordering right
        }));
        draggable.dispatchEvent(new MouseEvent('mouseup'));
    }

```
2nd
```
   dragAndDrop() {
        var modelSchemaString = "//div[@id='toolbox-stub-[MODEL_NAME]']";
        const draggable = cy.xpath(modelSchemaString.replace('[MODEL_NAME]', 'Calendar'))  // Pick up this
        const droppable = cy.xpath("//div[@id='mfgx-data-flow-diagram']")  // Drop over this
        const dataTransfer = new DataTransfer;
        draggable
            .trigger('dragstart', { dataTransfer });
        droppable
            .trigger('drop', { dataTransfer });
        draggable
            .trigger('dragend');
    }
```
3rd - By adding `import '@4tw/cypress-drag-drop'` in `support/commands.js` file
```
    dragAndDrop() {
        var modelSchemaString = "//div[@id='toolbox-stub-[MODEL_NAME]']";
        const draggable = cy.xpath(modelSchemaString.replace('[MODEL_NAME]', 'Calendar'))  // Pick up this
        const droppable = cy.xpath("//div[@id='mfgx-data-flow-diagram']")  // Drop over this
        draggable.drag(droppable)
    }

```
Could not get success.

Details of draggable element :
![image](https://user-images.githubusercontent.com/44443976/154429310-70ec9f49-4ca5-43df-8257-c8ec8ac49e7a.png)
Details of droppable element :
![image](https://user-images.githubusercontent.com/44443976/154429372-222dd384-8b59-4c32-9079-dce65716154d.png)

### Test code to reproduce

Added in **Current Behavior** section

### Cypress Version

9.4.1

**Comment by BlueWinds** [comment]
Sorry you're having trouble getting your tests working. Your test code to reproduce contains your Cypress test, but without access to your application's code and knowledge of it, there's no way I can tell exactly what's not working here. Your application's drag/drop functionality is listening for some events - you'll need to look into that code to figure out what it's listening for and what the test isn't providing.

If you can provide a reproducible example in a public repo - perhaps by forking https://github.com/cypress-io/cypress-test-tiny - I'll be happy to take a look, but the place to start is by examining your application's code (what events it's listening to and where).

**Comment by sainthkh** [comment]
Closing because of the inactivity.
