### ISSUE TITLE
Proposal: Add methods for determining current browser

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2023]
With Firefox support around the corner, the following methods will be useful to conditionally test things based on browser:

* `Cypress.isBrowser(_browserName_)`: 
	- Returns true if the exact browser is being run
	- `browserName` is case-insensitive
* `Cypress.isBrowserType(_browserType_)`: Returns true if the browser is in the family of `browserType`: 
	- `Cypress.isBrowserType('chrome')` will return true for Chrome, Canary, Chromium, and Electron
	- `Cypress.isBrowserType('firefox')` will return true for Firefox, Firefox Developer Edition, and Firefox Nightly
	- `browserType` is case-insensitive

**Comment by jennifer-shehane** [comment]
We now have [Cypress.browser](https://on.cypress.io/browser) which can be used to achieve the same thing. Closing as resolved.
