### ISSUE TITLE
Yahoo login page in cypress is loaded once and then disappears.

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#20237]
### Current behavior

I have to login to Yahoo through Cypress Automation but currently the Yahoo login page in Cypress loads once and then disappears. Which causes my next command to fail. 

![cypress_error](https://user-images.githubusercontent.com/71917476/154485161-30a6dd59-00c6-4202-882d-93420f516936.png)

### Desired behavior

As per my code, The Yahoo login page should load and stay there.

![yahoo_login_page](https://user-images.githubusercontent.com/71917476/154485106-daa0c562-ac7f-4d87-b0bb-5a0fa067b7a4.png)

### Test code to reproduce

```
/// <reference types="cypress" />

describe('login to yahoo', function(){
    it('login to yahoo to verify an email', function(){

        cy.viewport(1366, 768)
     
        //login to yahoo account
        cy.window().then(win => win.location.href = 'https://login.yahoo.com/');
        cy.wait(5000)
        cy.get('#login-username').should('be.visible')
        cy.get('#login-username').type('dhara@yahoo.com')
        cy.get('#login-signin').click()

    })
})
```

### Cypress Version

9.5.0

**Comment by BlueWinds** [comment]
Rather than setting `windom.location.href`, you probably want [`cy.visit()`](https://example.cypress.io/commands/navigation#visit). This does more than just visit the given url - it also sets up Cypress' network proxying, which does a great deal of work to improve testing.

**Comment by dharaaum** [comment]
Hi @BlueWinds,

I have to register in one website and then check the verification email in yahoo so if I use `cy.visit `I get cross origin error so I have used `windom.location.href`. i.e  cy.visit() failed because you are attempting to visit a different origin domain

**Comment by BlueWinds** [comment]
Yeah, that won't work - in cypress tests, the browser is limited to a single domain. https://docs.cypress.io/guides/guides/web-security#Same-superdomain-per-test contains more information about this limitation and some possible workarounds.
