### ISSUE TITLE
cy.visit not working for "https://hinduism.stackexchange.com"

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#20233]
### Current behavior

When I'm writing some sample tests to visit "https://hinduism.stackexchange.com", Cypress attempt to run tests but reports no test to run eventually

![hinduism](https://user-images.githubusercontent.com/7692328/154429591-27d584eb-38a9-4fc7-975b-cf275e8a0359.gif)
.

### Desired behavior

`cy.visit()` should be able to visit any URL.

### Test code to reproduce

```js
describe('Simulate error in visiting site', () => {
    it('check Hinduism Stackexchange', () => {
        cy.visit(`https://hinduism.stackexchange.com`); 
        cy.get(".s-post-summary").invoke("length").should("be.greaterThan", 10); //not reaching here
    });
});
```

### Cypress Version

9.5.0

### Other

I've already tested with v8 and v9 but it is not working.

**Comment by BlueWinds** [comment]
It looks like they have some framebusting code, which is breaking the application under test (https://hinduism.stackexchange.com/) out of Cypress' iframe.

You have a couple of options:
- If this is a site you control (I'm guessing it's not), disable the framebusting code.
- Figure out what technique stackexchange is using to break the iframe, and help us improve cypress. We already attempt to mitigate framebusting at the network level, but as you've discovered, it's not perfect. https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/util/rewriter.ts
- You could try Cypress' `experimentalSourceRewriting` config option. https://docs.cypress.io/guides/references/experiments#Configuration.

Hopefully that provides some helpful pointers.

**Comment by amitguptagwl** [comment]
Yes, this is not the site I control. I just took this is an example during live demonstrate of how to use cypress. But it failed.

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by baruchiro** [comment]
Hi, I found this answer:
https://stackapps.com/a/4963/102029

They said that embedding StackExchange website inside `iframe` is not allowed.
