### ISSUE TITLE
Unable to start cypress after fresh installation

### ISSUE THREAD

**Issue by UmangLavaniya** [cypress-io/cypress#20272]
### Current behavior

Getting below error.

npx cypress open              
It looks like this is your first time using Cypress: 9.5.0

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with Unknown system error -86: /Users/umang/Library/Caches/Cypress/9.5.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=528
spawn Unknown system error -86

----------

Platform: darwin-x64 (21.0.1)
Cypress Version: 9.5.0

### Desired behavior

Should be able to start.

### Test code to reproduce

Followed https://docs.cypress.io/guides/getting-started/installing-cypress#npm-install link

### Cypress Version

9.5.0

### Other

Node version : v17.5.0
Platform: darwin-x64 (21.0.1)
Cypress Version: 9.5.0

**Comment by UmangLavaniya** [comment]
Post java installation the issue got resolved.

**Comment by Sueun-Lee** [comment]
@UmangLavaniya 
Hello, I am also having a problem with the same issue.
I don't quite understand that installing Java solved the issue.
Could you please explain in more detail?

Below is a screenshot of my error.

![스크린샷 2022-03-02 오전 11 37 12](https://user-images.githubusercontent.com/98135175/156284118-d03359c3-a1d3-468e-b3c5-4f6a7ca68f12.png)

**Comment by oomkoos** [comment]
Installing Xcode solved this issue for me
