### ISSUE TITLE
As of Chrome v98 there's an issue with pdf embed viewer crashing

### ISSUE THREAD

**Issue by Deop** [cypress-io/cypress#20291]
### Current behavior

After updating Chrome v98 there's an issue with pdf embed viewer crashing while running tests in Cypress.
Tried with multiple Cypress versions, same result.

### Desired behavior

Embed pdf viewer in Chrome should load with content.

### Test code to reproduce

```
describe('test', () => {
  it('testing pdf viewer', () => {
    cy.visit('https://pdfjs.express/blog/how-embed-pdf-in-html-website');
    cy.get('object[type="application/pdf"]').scrollIntoView();
  })
})
```

![chrome_2022-02-21_18-30-54](https://user-images.githubusercontent.com/7953144/154994818-612ccea9-6cae-4da7-a40d-c445e7e6b2ee.png)

### Cypress Version

9.4.1

**Comment by bpartridge** [comment]
Can confirm this also occurs when calling `cy.visit()` on a URL that redirects to a PDF, on Chrome 100.0.4896.60 (macOS arm64)
