### ISSUE TITLE
cy.fixture() throws parse error when an empty JSON file is used as fixure.

### ISSUE THREAD

**Issue by AbdulKadirKhann** [cypress-io/cypress#20292]
### Current behavior

The cy.fixture() throws parse error when we try to use an empty JSON file.

### Desired behavior

It should have a provision/flag to even use empty JSON files. As there can be a use case where I want to send an empty file and see if the app throws an error.

### Test code to reproduce

cy.fixture('emptyJSONFile.json').then(()=>{
//logic
//but it throws error and never reaches this line
})

### Cypress Version

7.7.0

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I tested with the code below and learned that it's the default behavior of Node.js.

```js
const fs = require('fs')

fs.readFile('empty.json', 'utf8', (err, s) => {
  JSON.parse(s)
})
```

```
# Error Message
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/sainthkh/src/cypress/a.js:4:8
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

And eslint disallows empty json file like below:

![Screenshot from 2022-02-28 10-17-51](https://user-images.githubusercontent.com/8130013/155909330-e2901e30-02c4-48de-a917-8ba25201f93b.png)

It seems that it's not a bad default behavior.

It's hard to know what to be expected without more precise test sample. 

If it's a file upload testing, [`cypress-file-upload`](https://www.npmjs.com/package/cypress-file-upload) might solve your problem.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
