### ISSUE TITLE
Problem with downloading cypress 9.4.1

### ISSUE THREAD

**Issue by MikeP707** [cypress-io/cypress#20308]
### Current behavior

I upgraded cypress from version 9.3.1 to 9.4.1 and even 9.5.0. after such actualisation appeared problem with "unable to get local issuer certificate".
I downgraded to version 9.3.1 and problem disappeared.

I used cypress with earlier versions and no similar problem did exist.
Was implemented some breaking changes in version 9.4.1 and later that there appears such problem?

### Cypress Version

9.4.1

### Package Manager

yarn

### Operating system

Windows

### Other

Corporate proxy from script

**Comment by melibe23** [comment]
I am having the same issue with version 9.5.1
![image](https://user-images.githubusercontent.com/32499737/156161160-9b0c9c6f-268c-46a2-b560-c1c26262127f.png)
