### ISSUE TITLE
Cypress test automatically stop when i run cypress run command in the terminal

### ISSUE THREAD

**Issue by KrupalVaghasiya** [cypress-io/cypress#20304]
### Current behavior

I have 5 spec files that I want to run in headless mode and when I run this command in the terminal `npm run cy:run` cypress test automatically stops during running the test.

and also not creating the test report.

### Desired behavior

It should finish all spec files and also create a report for that test.

### Test code to reproduce

I have many lines of code so I can not show you here.

### Cypress Version

9.5.0

**Comment by KrupalVaghasiya** [comment]
![image](https://user-images.githubusercontent.com/86508745/155102325-73f1b708-21d2-48c2-83cf-01c4cf55d19d.png)
See the image. when the fourth file is running it will stop automaticaly.

**Comment by sainthkh** [comment]
Sorry for the late reply.

As we all know, debugging starts with reproducing the problem on the developer's machine. With only the screenshot, it's impossible to start solving the problem. Can you provide a working code example?

**Comment by KrupalVaghasiya** [comment]
@sainthkh Thank you for responding, Please clone `https://github.com/KrupalVaghasiya/orderFlow.git` and after install all dependencies and run in headless mode. when the test failed it will automatically stop the test exeution.

**Comment by sainthkh** [comment]
I tested it with Unbuntu 20.04 and it failed with SIGSEGV. It might not be what you expected, right.

**Comment by KrupalVaghasiya** [comment]
@sainthkh It should complete all test execution. but it will stop execution when any tests are failed.

**Comment by KrupalVaghasiya** [comment]
@sainthkh Any updated on this? I am still receiving `failed with SIGSEGV`
