### ISSUE TITLE
[BUG] - "The Cypress App could not be unzipped"

### ISSUE THREAD

**Issue by Arkady-Skvortsov** [cypress-io/cypress#20309]
### Current behavior

When am I want to update a deps from my (Nx) repo, I see that trouble

### Desired behavior

Just update npm dependencies in my repo

### Test code to reproduce

```sh 
npm update
```

### Cypress Version

ex. 9.1.0

### Other

Nrwl Cypress version is 13.7.2

**Comment by sainthkh** [comment]
Sorry for the late reply.

Is it still happening with the latest version?

**Comment by Develliot** [comment]
It is for me
