### ISSUE TITLE
Cypress does not fail on uncaught exception 

### ISSUE THREAD

**Issue by vaclavGabriel** [cypress-io/cypress#20313]
### Current behavior

Cypress does not fail a test when an uncaught exception happens. Instead, the test passes. 

I conditionally turned off uncaught exception handling in the `cypress/support/index.js` file, however in this case, a different uncaught exception occurred and therefore the test should fail as it did in the 9.4.1 version and below. 

![image](https://user-images.githubusercontent.com/48252269/155145096-2321a762-699e-4e90-b193-a9186758100a.png)

### Desired behavior

An uncaught exception should fail a test.

### Test code to reproduce

Run a test and trigger an uncaught exception.

### Cypress Version

9.5.0

**Comment by sainthkh** [comment]
Sorry for the late reply. 

As we all know, debugging starts with reproducing the problem on developer's machine. Can you provide a reproducible code example?
