### ISSUE TITLE
JQuery is not defined

### ISSUE THREAD

**Issue by giacomomaccanti** [cypress-io/cypress#20310]
### Current behavior

When i start test to this web page https://www.brt.it/it/form-danni with chrome (not cypress) i don't see any error in console. 
When lanch some web page with cypress it return this error:

```
The following error originated from your application code, not from Cypress.

  > jQuery is not defined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.[Learn more](https://on.cypress.io/uncaught-exception-from-application)
```

View stack trace:

`at <unknown> (https://www.brt.it/flex/cm/js.7.8.05/jq/FlexJS.js:60:5)`

### Desired behavior

Cypress shouldn't show any error for Jquery, any not?

### Test code to reproduce

```
describe('My First Test', () => {
    it('BRT PROD - FORM DANNI', () => {
      cy.visit('https://www.brt.it/it/form-danni')
    })
  })
```

### Cypress Version

9.5.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

I tried to reproduce the problem, but I failed. 

![Peek 2022-02-28 11-36](https://user-images.githubusercontent.com/8130013/155914767-12171a7a-fcdc-4a54-b263-7aada3d093f5.gif)

**Comment by sainthkh** [comment]
Closing because of the inactivity.
