### ISSUE TITLE
scrollIntoView() in grid is not working

### ISSUE THREAD

**Issue by gayathri-rl** [cypress-io/cypress#20328]
### Current behavior

Scrolling horizontally to find an element is failing

### Test code to reproduce

  it('should scroll right & click on march column', () => {
      cy.visit('https://www.ag-grid.com/example.php');
      cy.get('div.ag-center-cols-viewport div[row-id="0"] div[col-id="mar"]')
        .scrollIntoView()
        .click();
   });

### Cypress Version

8.4.1

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by gayathri-rl** [comment]
@sainthkh so if we need to column nov, how to do it? In my case, the order of column is not consistent. How to check its existence, and scroll if not found? any better way of handling it?

**Comment by sainthkh** [comment]
Maybe, [`nth-child`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) would help.
