### ISSUE TITLE
Respect scrollBehavior in GUI mode when clicking in the command log

### ISSUE THREAD

**Issue by KrekkieD** [cypress-io/cypress#20326]
### What would you like?

All this applies to the GUI mode.

I have set my `scrollBehavior` to `center` which works fine during the run. After the run when I click on a command to see which element was found it does not follow the same scrolling behavior. As a result this leads to a command log snapshot showing elements that are hidden behind other elements (sticky header) where this wasn't the case during the actual running of the test. I am able to scroll it into view manually, though.

### Why is this needed?

Having this scrolling alignment will make the view of the snapshot (that was taken for the command during the test) match what the browser was actually displaying when the test was running the command, or at least it should match it more accurately.

Currently there is some confusion because cypress usually can't act on a hidden element, and after jumping to the snapshot it shows the element is hidden behind the sticky bar where in reality it wasn't.

### Other

Another way of implementing this could potentially be storing the current scrolling position of the browser when a snapshot is taken, and restoring this when viewing the snapshot (might be more accurate, technically). Although this could maybe pose a problem when user resizes the cypress window after the test (then again I'd say supporting those cases can be omitted).

**Comment by zorankova** [comment]
Could be related to https://github.com/cypress-io/cypress/issues/3200
