### ISSUE TITLE
Using as() - Cannot set properties of undefined

### ISSUE THREAD

**Issue by stevenlafl** [cypress-io/cypress#20324]
### Current behavior

This simple code:
```
cy.get('form').as('form')
```
results in:
Cannot set properties of undefined (setting 'form')

Contrary to the documentation.

### Desired behavior

It shouldn't error. It should alias to be used as cy.get('@form')

### Test code to reproduce

Run the above code. I could get it to run on Cypress 9.0.0.

### Cypress Version

\>= 9.1.0

**Comment by stevenlafl** [comment]
Testing determines that this has been a problem starting in 9.1.0, exists in every subsequent version.
It works perfectly in 9.0.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

I tried to reproduce the bug, but failed with the code below:

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <form>
    <input />
  </form>
</body>
</html>
```

```js
it('t', () => {
  cy.visit('fixtures/a.html')

  cy.get('form').as('hello')
})
```

Can you provide us a reproducible code example? As we all know, the debugging starts with reproducing the problem on the developer's machine.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
