### ISSUE TITLE
Argument of type '{ tags: string; }' is not assignable to parameter of type 'TestConfigOverrides'

### ISSUE THREAD

**Issue by HibaBarakat** [cypress-io/cypress#20327]
### Current behavior

When trying to add tag for describe or it, it shows that there is error although they are added to index.js

![image](https://user-images.githubusercontent.com/50820483/155285117-33f37daa-c428-4052-a157-faef3527c210.png)

![image](https://user-images.githubusercontent.com/50820483/155284869-1060e842-ada5-4fca-a674-a50a62c49931.png)

### Desired behavior

Need to add tags from grep to my tests 

### Test code to reproduce

describe('NAND Plan Sourcing e2e tests',{ tags: '@two' }, () => {

### Cypress Version

9.5.0

**Comment by Narretz** [comment]
Tags are a feature of https://github.com/cypress-io/cypress-grep, please open an issue there with a reproducible example.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
