### ISSUE TITLE
[Dashboard] Github Action runs: Add PR links/name on the run

### ISSUE THREAD

**Issue by stdedos** [cypress-io/cypress#20348]
### What would you like?

I am expecting that, instead of this:
![image](https://user-images.githubusercontent.com/133706/155487767-7f5cf897-8588-44b7-8124-4ec2dda52933.png)

I will be seeing this instead:

![image](https://user-images.githubusercontent.com/133706/155488055-0ac4c4b7-80c5-4a1f-a18f-3821b1aaee9a.png)

i.e. add:
* A link to the PR, and
* The PR title

Instead of no-link, and the illegible `Merge sha1-x onto sha1-y`

### Why is this needed?

I can "come" to Cypress Dashboard, but I cannot "go back" to Github

**Comment by stdedos** [comment]
Seems that Github is able to provide this already? https://github.com/actions/checkout/issues/58#issuecomment-663103947

**Comment by modern-sapien** [comment]
Hi @stdedos 

Here are some quick resources on how to clean up those commit messages or provide alternate information.

- [Docs: Overwrite Commit Message Cypress Provides](https://docs.cypress.io/guides/continuous-integration/introduction#Git-information)
- [Docs: CI Environment Variable Handling](https://docs.cypress.io/guides/continuous-integration/introduction#Git-information)

**Comment by stdedos** [comment]
True - I should've also added:
> I am using https://docs.cypress.io/guides/continuous-integration/introduction#Git-information `DEBUG=commit-info,cypress:server:record,cypress:*` to try and decipher how cypress "identifies" my repository (and why is the PR link missing), but nothing shows up during `npx cypress info`. What gives? 😕

Also, please note that the https://docs.cypress.io/guides/continuous-integration/introduction#Git-information makes no mention of "Pull Request" anywhere (or "pull" for that matter)

**Comment by conversaShawn** [comment]
@stdedos Thanks for bringing this to our attention.
The docs have been updated to reflect [common GitHub Actions problems & solutions](https://docs.cypress.io/guides/continuous-integration/github-actions#Common-Problems-and-Solutions)

Also, see [this comment](https://github.com/cypress-io/github-action/issues/124#issuecomment-1076826988) in our GH Actions examples repo
