### ISSUE TITLE
Whoops there is no Test to run

### ISSUE THREAD

**Issue by Akhil-Vadlamudi** [cypress-io/cypress#20342]
### Current behavior

Currently, I created a test on cypress and it works fine on my laptop but then when my fellow coworker tried to run the test on his laptop it says whoops there is no test run. the image below is what my coworker gets. Do you have any clue as why the test works on my laptop but not on my coworkers?
![image](https://user-images.githubusercontent.com/92115333/155400193-a17a7e83-bb43-41e4-a7cc-cbee2b0656de.png)
 

### Desired behavior

I want the test to work both on my laptop and my coworker's laptop.

### Test code to reproduce

I cannot provide my code.

### Cypress Version

9.4.1

**Comment by Narretz** [comment]
Maybe you didn't commit your spec file?

**Comment by Akhil-Vadlamudi** [comment]
It was committed and uploaded into our repo but the code works for me and not my fellow coworker.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Is it still not working with the latest Cypress?
