### ISSUE TITLE
Error during screenshot capture: RangeError: Index out of range | The value of "offset" is out of range.

### ISSUE THREAD

**Issue by rbayliss** [cypress-io/cypress#2034]
### Current behavior:
Executing `cy.screenshot()` on large pages causes error.  Stack trace:

```bash
     RangeError: Index out of range
      at checkInt (buffer.js:1180:11)
      at Buffer.writeUInt32BE (buffer.js:1271:5)
      at new Jimp (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/jimp/index.js:137:30)
      at stitchScreenshots (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:199:17)
      at /Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:295:21
      at tryCatcher (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
      at Async._drainQueue (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)
```

### Desired behavior:
Screenshots are captured.

### Steps to reproduce:
Call `cy.screenshot()` on a page that exceeds 16,000,000 square pixels (in my case, the element is 1195px by 13518px).  Reproduction test case: https://github.com/rbayliss/cypress-test-tiny/tree/index_error

### Versions

```
Cypress package version: 3.0.1
Cypress binary version: 3.0.1
Chrome 67.0.3396.87 on OSX 10.13
```

**Comment by rhoog** [comment]
I'm getting the same error when trying to create a screenshot of an area 1170px by 1317px.

My workaround is to increase the viewport from 
cy.viewport(1200, 800);
to
cy.viewport(1200, 1500);

**Comment by wBingwei** [comment]
I've met the same issue.  Running Cypress v3.1.0

The same version works on my workstation, but not works on my laptop.

**Comment by wBingwei** [comment]
This seems to be an issue of dependency "jimp" package.
My laptop is Windows 10, 14' size, and the screen resolution is 1080P. At first, I use 125% text size, then the range error happened. But when I changed the text size to 100%, the error disappear.

**Comment by guigonc** [comment]
I am have the same problem running cypress open

Cypress: 3.1.0
SO: OS X 10.13.6
Node: 8.11.3

The strange is that I have a lot of other tests that runs ok. The test that fails looks no different from the others

```
it('renders passenger card with open special service options', () => {
   cy.get('.checkbox label').click()
   cy.get('.form-section').screenshot('form-section-opened')
})

```

If I remove the command that does the click the screenshot works.

**Comment by mattbgold** [comment]
I have the same issue on 3.1.0, both when running locally on Windows and in a docker container.

Every call to cy.screenshot() in my spec file would produce the same error, and this was across three different viewport sizes. (1700x900, 375x812, and 768x1024).

The issue disappeared after I changed the viewports to slightly different sizes (1700x800, and 375x667), and now I seem to be able to use the original viewport sizes again without any issue.

**Comment by leeuwd** [comment]
Same here. Latest Cypress, Vue CLI 3 project, macOS Mojave.

**Comment by rsumith89** [comment]
In subscribe

On 27-Jan-2019 8:29 PM, "Loïc Salou" <notifications@github.com> wrote:

just found a workaround which seems to work in any case (at least for all
of my cases).
never call cy.screenshot('file') directly, always use some dom element and
chain with .root().screenshot('file')

   - simple ex. *cy.get('[data-cy=myTag]').root().screenshot('file')*
   - different use case, to see the result of an action like opening a
   popup,
   *cy.get('[data-cy=myPopupButton]').click().root().screenshot('result-screen-file')*
   works fine.

Hope this helps.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cypress-io/cypress/issues/2034#issuecomment-457924841>,
or mute the thread

**Comment by loicsalou** [comment]
unfortunately my workaround does not seem to always work. Some of my screenshots which were working 2 days ago are crashing today, no change on my side.
This feature is really important for my users, we intend to deliver them a "book" for each release so they can check small issues with desing like CSS bugs etc.

Thanks for not letting this down !

**Comment by lukeapage** [comment]
We are suddenly getting this issue now - though it wasn’t happening last week??!

**Comment by lukeapage** [comment]
This could well be fixed when master is released since jimp is upgraded and last time I looked at the code, a lot of differences exist in the upgrade. 
https://github.com/cypress-io/cypress/pull/3415

**Comment by bluehenry** [comment]
setResolution() works for me. Windows 10 + Chrome.
        cy.setResolution([2560, 1440]);

**Comment by lukeapage** [comment]
@bluehenry is that a custom command?

**Comment by bluehenry** [comment]
> @bluehenry is that a custom command?

the code looks like: 
context('demo', () => {    
    beforeEach(() => {
        cy.setResolution([2560, 1440]);
        cy.visit('https://google.com');
        cy.wait(8000);
    })    

    it('demo', function() {
     cy.matchImageSnapshot('dashboard');
    })
});

**Comment by chisma** [comment]
@bluehenry , this works for me too. On a headless Chrome browser, though I don't understand how.

**Comment by nitzanashi** [comment]
This did not happen to me on Cypress 3.8.0 trying to upgrade to Cypress 4+for a while now and this Error keep poping out...

**Comment by QA-Open** [comment]
I battled this error all morning and then realized the test-runner's Chrome window had the zoom set to 75%. As soon as I set it to 100% the error went away.

**Comment by maamounapprise** [comment]
The issue is still happening, @jennifer-shehane what is the priority for fixing this or if there is a work around?

**Comment by gael-ian** [comment]
> setResolution() works for me. Windows 10 + Chrome.
> cy.setResolution([2560, 1440]);

`cy.setResolution` does not exist (and seems to never exist before as the Cypress changelog doesn't mention it at all) so it can't be a valid workaround.

I have the same problem and it seems to come from the [`packages/server/lib/screenshots#crop`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.coffee#L129) method. Sometime dimensions ends with a negative value as y and jimp does'nt like it at all.

```
cypress:server:screenshot (s345) dimensions for cropping are { x: 200, y: -0.859375, width: 1065, height: 666 } +0ms
cypress:server:screenshot (s345) crop: from 200, -0.859375 +0ms
cypress:server:screenshot (s345)         to 1065 x 666 +0ms
[…]
cypress:server:reporter got mocha event 'fail' with args: [ {
  […]
  err: {
    message: 'The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received -4320',
    name:
      'RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received -4320\n' +
      'at boundsError (internal/buffer.js:72:9)\n' +
      'at Buffer.readUInt32BE (internal/buffer.js:295:5)\n' +
      'at Jimp.<anonymous> (/[…]/4.5.0/[…]/server/node_modules/@jimp/plugin-crop/dist/index.js:45:37)\n' +
      'at scan (/[…]/4.5.0/[…]/server/node_modules/@jimp/utils/dist/index.js:55:9)\n' +
      'at Jimp.scanQuiet (/[…]/4.5.0/[…]/server/node_modules/@jimp/core/dist/index.js:1352:32)\n' +
      'at Jimp.cropQuiet (/[…]/4.5.0/[…]/server/node_modules/@jimp/plugin-crop/dist/index.js:44:12)\n' +
      'at Jimp.<computed> [as crop] (/[…]/4.5.0/[…]/server/node_modules/@jimp/core/dist/index.js:1266:23)\n' +
      'at crop (/[…]/4.5.0/[…]/server/lib/screenshots.js:145:26)\n' +
      'at /[…]/4.5.0/[…]/server/lib/screenshots.js:209:22\n' +
      'at arrayEach (/[…]/4.5.0/[…]/server/node_modules/lodash/lodash.js:516:11)\n' +
      'at Function.forEach (/[…]/4.5.0/[…]/server/node_modules/lodash/lodash.js:9342:14)\n' +
      'at stitchScreenshots (/[…]/4.5.0/[…]/server/lib/screenshots.js:206:7)\n' +
      'at /[…]/4.5.0/[…]/server/lib/screenshots.js:350:21\n'
    },
    […]
  }
] +6s
```

You already check if calculated dimensions do not exceed image dimensions ([Line 139-140](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.coffee#L139)). A solution may be to add a second check on dimensions not being negative.

**Comment by iGoog** [comment]
I was running into the same error when [trying to do matchImageSnapshot of an element.](https://github.com/iGoog/appliHack/blob/main/TraditionalTestsV1/cypress/pages/productCatalog.js) I was able to work around the issue by chaining a "then" statement with this function like this passed to it. 

```
const clipWorkaround = ($el) => {
	const rect =  $el[0].getBoundingClientRect();
	const opts = {clip: {x : rect.x, y: rect.y, width: rect.width, height: rect.height } };
	cy.screenshot(opts);
};
```
The opts probably should also be using the capture: 'fullPage' to work correctly. It might be viable to select the body of the page as your element. I was originally using 'viewport' if you're digging into my code.

**Comment by bahmutov** [comment]
Another reproducible example: https://github.com/masakudamatsu/line-height-picker/blob/visual-testing/cypress/e2e/visual-tests.js

Cypress v4.8.0

<img width="1277" alt="Screen Shot 2020-06-18 at 9 23 42 AM" src="https://user-images.githubusercontent.com/2212006/85025445-67c45000-b145-11ea-9e54-cfe4d000d41a.png">

**Comment by MatissAndersons** [comment]
Quite new to the cypress and automated testing, and for me the same issue occurred. However, at least for me the issue is that if the element before has height that is of float value, the cypress tries to crop with a negative y value (-0.78125 in my case). If I force the y value to have a minimum value zero, everything proceeds smoothly.
I did in Cypress/resources/app/packages/server/lib/automation/screenshot.js that by adding 
`data.clip.y = Math.max(data.clip.y, 0);`
But couldn't find the cause for it calculating the y value to be negative.

**Comment by askirmas** [comment]
Issue appears if body is scrollable means bigger than viewport. Don't know exactly how screenshots are made but *somethings* is opened with the same body state except scroll position.
Despite discussed issue, scrollable body sounds rather wrong, especially in 2020 with `display: grid` and responsive layout

**Comment by jennifer-shehane** [comment]
Narrowed this issue down to a smaller repro so we don't have to rely on outside repos/URLs. This is reproducible outside of any snapshot plugins. 

`index.html`

```html
<html>
<body>
  <svg width="778pt" height="308pt" style="background-color: green;"></svg>
  <svg id="blue" width="778pt" height="308pt" style="background-color: blue;"></svg>
  <div style="height: 300px; background-color: red;"></div>
</body>
</html>
```

`spec.js`

```js
it('works', () => {
  cy.visit('index.html')
  cy.get('#blue').screenshot()
})
```

```
RangeError: The value of "offset" is out of range. It must be >= 0 and <= 20553340. Received -11304
    at boundsError (internal/buffer.js:72:9)
    at Buffer.readUInt32BE (internal/buffer.js:295:5)
    at Jimp.<anonymous> (/Users/jennifer/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/plugin-crop/dist/index.js:43:37)
    at scan (/Users/jennifer/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/utils/dist/index.js:53:9)
    at Jimp.scanQuiet (/Users/jennifer/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/core/dist/index.js:1262:32)
    at Jimp.cropQuiet (/Users/jennifer/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/plugin-crop/dist/index.js:42:12)
    at Jimp.<computed> [as crop] (/Users/jennifer/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/core/dist/index.js:1176:23)
    at crop (/Users/jennifer/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:161:24)
    at /Users/jennifer/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:435:17
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at $Cypress.automation (http://localhost:51135/__cypress/runner/cypress_runner.js:164254:14)
    at automate (http://localhost:51135/__cypress/runner/cypress_runner.js:157822:20)
    at automateScreenshot (http://localhost:51135/__cypress/runner/cypress_runner.js:157832:10)
    at scrollAndTake (http://localhost:51135/__cypress/runner/cypress_runner.js:157901:12)
From previous event:
    at takeScrollingScreenshots (http://localhost:51135/__cypress/runner/cypress_runner.js:157904:18)
    at takeElementScreenshot (http://localhost:51135/__cypress/runner/cypress_runner.js:158019:10)
    at http://localhost:51135/__cypress/runner/cypress_runner.js:158123:14
From previous event:
    at takeScreenshot (http://localhost:51135/__cypress/runner/cypress_runner.js:158115:19)
    at Context.screenshot (http://localhost:51135/__cypress/runner/cypress_runner.js:158229:14)
    at Context.<anonymous> (http://localhost:51135/__cypress/runner/cypress_runner.js:167810:21)
    at http://localhost:51135/__cypress/runner/cypress_runner.js:167243:15
From previous event:
    at runCommand (http://localhost:51135/__cypress/runner/cypress_runner.js:167222:8)
    at next (http://localhost:51135/__cypress/runner/cypress_runner.js:167368:14)
From previous event:
    at next (http://localhost:51135/__cypress/runner/cypress_runner.js:167368:34)
From previous event:
    at http://localhost:51135/__cypress/runner/cypress_runner.js:167409:37
From previous event:
    at run (http://localhost:51135/__cypress/runner/cypress_runner.js:167402:19)
    at $Cy.cy.<computed> [as visit] (http://localhost:51135/__cypress/runner/cypress_runner.js:167854:11)
    at Context.runnable.fn (http://localhost:51135/__cypress/runner/cypress_runner.js:168079:21)
    at callFn (http://localhost:51135/__cypress/runner/cypress_runner.js:103224:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:51135/__cypress/runner/cypress_runner.js:103211:7)
    at http://localhost:51135/__cypress/runner/cypress_runner.js:173313:28
From previous event:
    at Object.onRunnableRun (http://localhost:51135/__cypress/runner/cypress_runner.js:173301:20)
    at $Cypress.action (http://localhost:51135/__cypress/runner/cypress_runner.js:164070:61)
    at Test.Runnable.run (http://localhost:51135/__cypress/runner/cypress_runner.js:171914:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:51135/__cypress/runner/cypress_runner.js:103883:10)
    at http://localhost:51135/__cypress/runner/cypress_runner.js:104009:12
    at next (http://localhost:51135/__cypress/runner/cypress_runner.js:103792:14)
    at http://localhost:51135/__cypress/runner/cypress_runner.js:103802:7
    at next (http://localhost:51135/__cypress/runner/cypress_runner.js:103704:14)
    at http://localhost:51135/__cypress/runner/cypress_runner.js:103770:5
    at timeslice (http://localhost:51135/__cypress/runner/cypress_runner.js:97696:27)
```

<img width="1038" alt="Screen Shot 2020-07-28 at 3 15 20 PM" src="https://user-images.githubusercontent.com/1271364/88641437-36945380-d0e5-11ea-82d0-98f466e217e1.png">

**Comment by melibe23** [comment]
I am experiencing the same issue only in Chrome, Firefox is fine. Thank you for all your hard work!

**Comment by melibe23** [comment]
I am experiencing the same issue, waiting for this fix to finish my mobile e2e testing. It only happens to me when I set a viewport. Thank you in advance.

**Comment by santam85** [comment]
Also running into this. Seems to happen only with <canvas> or <svg> elements, in Blink/Webkit browsers.

**Comment by j1000** [comment]
I'm able to work around this issue by using Electron instead of Chrome. (So far.)

Part of what seems to trigger this issue is setting the viewport before taking a screenshot. It can be very inconsistent. I have a custom command to take a series of screenshots at various browser widths, and the same dimensions will work with one page but fail with another. Fiddling with the viewport X and Y can get it working in one place but will likely break another.

**Comment by chisma** [comment]
This bug is really coming in the way of my success with visual testing with Cypress(cypress-image-snapshot/plugin). I get the out of range error only when I run with headless chrome, inside a container! I setup the viewport to (1600,900) in cypress.json. Dont use cy.viewport() anywhere in the test. I get the snapshots with cy.matchImageSnapshot() for the test- locally, in both headed and headless chrome. Also headless, locally. But not on headless-inside container!
![image](https://user-images.githubusercontent.com/16785245/95961615-8f7ea880-0e05-11eb-8003-6e8d7d5c8af2.png)

**Comment by vivekbwaj** [comment]
is there any update on this issue?

**Comment by alexbjorlig** [comment]
I hoped that I could workaround this issue by using `scrollIntoView()` on the element, before calling `.screenshot()`. But that does not help - still get the index out of range. Any ideas how to avoid this issue, until an official fix arrives?

**Comment by wesselvanderlinden** [comment]
I'm also getting this error frequently. I've tried several workarounds suggested in the comments above, but none of them worked. It's a real pain since our build pipeline depends on the screenshot functionality, and they are failing randomly now.

Are there any plans to fix this issue? We now either have to disable all our tests, or retry until they succeed.

**Comment by aleksandryackovlev** [comment]
In my case this error was caused by the behavior of the `dom.getElementPositioning` (https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/coordinates.js#L27).
In some cases it returns negative values between -1 and 0 in `fromElViewport.top` for elements that are being captured. 

I suppose changing https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/screenshot.js#L235 to `y: Math.max(0, elPosition.fromElViewport.top),` will fix the problem with negative offsets.

Unfortunatelly, I'm not deeply familiar with the code of cypress, so I can't predict whether any other behavior of the system will be affected or not by this change.

Can anyone tell me where else this code is used? And is this the right place in code to fix the problem?

For now I just overwrote the `screenshot` command as a workaround and it works for me: 
```
Cypress.Commands.overwrite(
  'screenshot',
  (originalFn, subject, name, options) => {
    if (subject) {
      let scrollY = null;
      const win = Cypress.dom.getWindowByElement(subject[0]);

      return originalFn(subject, name, {
        ...options,
        onBeforeScreenshot(...args) {
          if (options.onBeforeScreenshot) {
            options.onBeforeScreenshot(...args);
          }

          scrollY = Object.getOwnPropertyDescriptor(win, 'scrollY');

          Cypress.log({
            name: 'stub scrollY',
            displayName: 'stub sY',
            message: `${win.scrollY} => ${
              win.scrollY ? win.scrollY - 1 : win.scrollY
            }`,
          });

          Object.defineProperty(win, 'scrollY', {
            value: win.scrollY ? win.scrollY - 1 : win.scrollY,
          });
        },
        onAfterScreenshot(...args) {
          Object.defineProperty(win, 'scrollY', scrollY);

          if (options.onAfterScreenshot) {
            options.onAfterScreenshot(...args);
          }

          Cypress.log({
            name: 'restore scrollY',
            displayName: 'restore sY',
            message: `${win.scrollY}`,
          });
        },
      });
    }

    return originalFn(subject, name, options);
  }
);
```

**Comment by jfhector** [comment]
I'm getting this error too. It's preventing me from being able to use Cypress to accomplish our goals.

**Comment by jarrietas** [comment]
> In my case this error was caused by the behavior of the `dom.getElementPositioning` (https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/coordinates.js#L27).
> In some cases it returns negative values between -1 and 0 in `fromElViewport.top` for elements that are being captured.
> 
> I suppose changing https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/screenshot.js#L235 to `y: Math.max(0, elPosition.fromElViewport.top),` will fix the problem with negative offsets.
> 
> Unfortunatelly, I'm not deeply familiar with the code of cypress, so I can't predict whether any other behavior of the system will be affected or not by this change.
> 
> Can anyone tell me where else this code is used? And is this the right place in code to fix the problem?
> 
> For now I just overwrote the `screenshot` command as a workaround and it works for me:
> 
> ```
> Cypress.Commands.overwrite(
>   'screenshot',
>   (originalFn, subject, name, options) => {
>     if (subject) {
>       let scrollY = null;
>       const win = Cypress.dom.getWindowByElement(subject[0]);
> 
>       return originalFn(subject, name, {
>         ...options,
>         onBeforeScreenshot(...args) {
>           if (options.onBeforeScreenshot) {
>             options.onBeforeScreenshot(...args);
>           }
> 
>           scrollY = Object.getOwnPropertyDescriptor(win, 'scrollY');
> 
>           Cypress.log({
>             name: 'stub scrollY',
>             displayName: 'stub sY',
>             message: `${win.scrollY} => ${
>               win.scrollY ? win.scrollY - 1 : win.scrollY
>             }`,
>           });
> 
>           Object.defineProperty(win, 'scrollY', {
>             value: win.scrollY ? win.scrollY - 1 : win.scrollY,
>           });
>         },
>         onAfterScreenshot(...args) {
>           Object.defineProperty(win, 'scrollY', scrollY);
> 
>           if (options.onAfterScreenshot) {
>             options.onAfterScreenshot(...args);
>           }
> 
>           Cypress.log({
>             name: 'restore scrollY',
>             displayName: 'restore sY',
>             message: `${win.scrollY}`,
>           });
>         },
>       });
>     }
> 
>     return originalFn(subject, name, options);
>   }
> );
> ```

Just tested this and seems to be working OK! Fixed the issue I was having.

**Comment by aleksandryackovlev** [comment]
> I'm getting this error too. It's preventing me from being able to use Cypress to accomplish our goals.

@jfhector try to put into `cypress/support/commands.js` that `Cypress.Commands.overwrite(...` code I wrote above. Maybe it would fix the issue.

**Comment by jfhector** [comment]
@aleksandryackovlev I've tried [the workaround you've suggested](https://github.com/cypress-io/cypress/issues/2034#issuecomment-729515705), and I'm still getting the same issue.

Thanks for trying to help though!

**Comment by jennifer-shehane** [comment]
There's a PR open to fix this here: https://github.com/cypress-io/cypress/pull/9281
