### ISSUE TITLE
download.cypress.io is down

### ISSUE THREAD

**Issue by fzaninotto** [cypress-io/cypress#20355]
### Current behavior

https://download.cypress.io/ doesn't respond. 

this breaks every install of my app, which depends on cypress downloading https://download.cypress.io/desktop/5.1.0?platform=linux&arch=x64

### Desired behavior

well, the url used to return the right version of Cypress

### Test code to reproduce

try to download the version https://download.cypress.io/desktop/5.1.0?platform=linux&arch=x64

### Cypress Version

5.1.0 and others

**Comment by HeathNaylor** [comment]
Downloads site looks to be back up.

**Comment by jennifer-shehane** [comment]
We did have an outage today. Please check our status page for all updates on our services. Right now we are continuing to monitor but the outage should be resolved. [https://www.cypressstatus.com/](https://www.cypressstatus.com/)

**Comment by fzaninotto** [comment]
Thanks!
