### ISSUE TITLE
Can't build binary on OSX Monterey

### ISSUE THREAD

**Issue by JessicaSachs** [cypress-io/cypress#20358]
### Current behavior

When you run `yarn binary-build` on OSX Monterey, it fails because the version of `macos-release` we depend on doesn't include it in its array.

There's a long dependency tree, but it can be traced back to the fact that the [Cypress Release Automations repository](https://github.com/cypress-io/release-automations) depends on versions of `@octokit/rest` that are two major versions behind.

### Desired behavior

`yarn binary-build` shouldn't crash.

### Test code to reproduce

..

### Cypress Version

develop

**Comment by flotwig** [comment]
This is resolved.
