### ISSUE TITLE
Cannot find module SupportFile

### ISSUE THREAD

**Issue by antifragger** [cypress-io/cypress#2036]
Hi,

I'm getting a 
`Error: Cannot find module '/Users/davidcarlier/www/***/cypress/support/index.js' from '/Users/davidcarlier/www/***'`
 error when trying to launch my tests.

I've tried adding/emptying the support file in `cypress/support/index.js`. Also tried defining the support path in my cypress config json.

**Comment by ChrystelleGIT** [comment]
@antifragger Did you find a solution for this? I've got the same thing going on.

**Comment by jennifer-shehane** [comment]
Likely they replaced the `index.js` with the standard seeded content:

```js
module.exports = (on, config) => {}
```
