### ISSUE TITLE
[Chrome] Clicking on web app option to Copy a URL into clipboard does not work

### ISSUE THREAD

**Issue by rodrigo-vazquez** [cypress-io/cypress#20365]
### Current behavior

At the moment we are kind of stuck with Electron since when Using Chrome we have an elipsis menu that allows users to copy invitation URLs, when running the test in Chrome it actually clicks on it but somehow the invitation is not copied into the clipboard.

We also show a snackbar that states "Copied!" and in Electron is shown as expected but when executed in Chrome is not being shown.

The weirdest thing is that if I pause the test before getting into the copy part and resume it works fine in Chrome.

### Desired behavior

Cypress users should be able to write the clipboard without any issues when Using Chrome.

### Test code to reproduce

```
function copyInvitationLink() {
  groceriesList.elements.firstTableElipsis.should('be.visible');
  groceriesList.elements.firstTableElipsis.click();
  cy.get('.mat-menu-item').contains('Copy Invitation Link').click();
}
```

### Cypress Version

8.3.0 - 9.5.0

**Comment by sainthkh** [comment]
Maybe solutions at #2752 might help solve your problem.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
