### ISSUE TITLE
Typo in env var error message

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2038]
![image](https://user-images.githubusercontent.com/14625260/41931812-28e8d1d0-794d-11e8-8620-41d69eca7ffe.png)

**Comment by saurabhgoyaliitr** [comment]
Hi, I am interested to solve this. Can you help?

**Comment by jennifer-shehane** [comment]
Hey @saurabhgoyaliitr, thanks for the interest. This has already been fixed. Keep an eye out for any other first-timers-only issues!

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
