### ISSUE TITLE
Proposal: add 'after:screenshot' plugin event

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2039]
Add an event for the `pluginsFile` that is called after a screenshot is taken and written to disk. It will be called with an object with the following properties:

```
{
  size 
  takenAt
  dimensions
  multipart
  pixelRatio
  name
  specName
  testFailure
  path
  scaled
  blackout
  duration
}
```

An object can be synchronously returned or resolved in a promise with the following properties:

```
{
  size 
  dimensions
  path
}
```

Those properties will be merged into the original object and will be passed to the `onAfterScreenshot` browser callback. Any extra properties returned/resolved will be ignored.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
