### ISSUE TITLE
Clear session between same-level describes in a single spec when using cy.session()

### ISSUE THREAD

**Issue by wojciech-sygier** [cypress-io/cypress#20393]
### What would you like?

A nice addition to `cy.session()` would be an option to clear sessions at command between same-level describes. This is especially useful in cases where there are multiple describes for various viewports. An option like `clearAtBeginning` or something would do.

### Why is this needed?

I have a couple of specs that run the same describe over three different viewports. At least one test changes the state to the point it has to be reset at the beginning of the next describe. Without the ability to clear the state between describes my tests are coupled.

It looks roughly like this:
```
const viewports = ['iphone-x', 'macbook-15'];

viewports.forEach(viewport => {
  describe('My tests', () => {
    beforeEach(() => {
      cy.login(); // my custom login command utilising cy.session();
      // all the other required stuff
    });
    
    it('does something that changes the state', () => {
      // this test will work for the first time, but fail the second time due to saved state
    });
});
```

### Other

Currently I'm using a workaround with `cypress-localstorage-commands` which I want to deprecate in favour of `cy.session()` to clean up my code. At the beginning of each describe new session is created and preserved throughout the whole iteration of the single forEach element run.

Like that:
```
const viewports = ['iphone-x', 'macbook-15'];

viewports.forEach(viewport => {
  describe('My tests', () => {
    before(() => {
      // set up the whole state and save at the end
      cy.saveLocalStorage();
    });

    beforeEach(() => {
      cy.restoreLocalStorage();
      // more code required at this point
    });
    
    it('does something that changes the state', () => {
      // this test will work all the time with that solution
    });
});
```

However this is messy now, as I have two different things to maintain instead of one and more redundant code.

**Comment by wojciech-sygier** [comment]
A nice additional feature would also be to clear session before retrying the whole spec in `cypress open`. I'm not sure if you want to do it in the same PR or would you prefer me to open another.

**Comment by emilyrohrbough** [comment]
@wojciech-sygier There are a couple of options you might try to achieve what you are describing if I understand your request correctly:
1. You could leverage a beforeEach hook at the root level to clear all active sessions -- this is likely the better option
2. You could use a unique session ID per viewport

```diff
const viewports = ['iphone-x', 'macbook-15'];

+ // option 1
+ beforeEach(() => {
+   Cypress.session.clearAllSavedSessions()
+ })

viewports.forEach(viewport => {
  describe('My tests', () => {
    beforeEach(() => {
      cy.login(); // my custom login command utilising cy.session();

      // all the other required stuff
    });
    
    it('does something that changes the state', () => {
      // this test will work for the first time, but fail the second time due to saved state
    });
});
```

> A nice additional feature would also be to clear session before retrying the whole spec in cypress open

You can achieve this today with a before hook at the root-level like:
```js
before(() => {
  // sessions has logic built in to persists sessions on UI refresh
  Cypress.session.clearAllSavedSessions()
})
```

**Comment by wojciech-sygier** [comment]
I'll give it a shot, I seldom go that deep into Cypress API. I'll update the comment with the results. Thanks anyway :)

**Comment by gajus** [comment]
I believe you need to wrap it, i.e.

```ts
beforeEach(() => {
  cy.wrap(
    Cypress.session.clearAllSavedSessions()
  );
});
```

**Comment by emilyrohrbough** [comment]
@wojciech-sygier Did you get this working?

**Comment by wojciech-sygier** [comment]
To be honest, I don't remember. I think my last comment remains valid, as I didn't really do anything regarding the second problem I had and the solution for the first one worked (again, look at my comment). Since then I also changed my job to game dev, so I'm no longer using Cypress, at least for now. Thus, I can't really verify whether it's still a thing.

**Comment by emilyrohrbough** [comment]
@wojciech-sygier No problem! I am going to close this out for now since you don't be able to verify.

BTW, congratulations on the new job! 🎉
