### ISSUE TITLE
Intercepted requests can bleed over into the next test when the test ends quickly after interception

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#20397]
### Current behavior

When you intercept a request and then immediately move on to the next test, the response will occasionally not make it back to the client which will cause the browser to trigger an automatic retry. This can cause a subsequent test to pick up the call if it is also intercepting the same route. This can cause duplicate interception or an interception when one is explicitly being tested not to occur. An example of the second scenario can be seen below from [this code](https://github.com/cypress-io/cypress/blob/05f9ad163ec4ab13dc296b6ec184d28b5cea6670/packages/driver/cypress/integration/commands/net_stubbing_spec.ts#L3237-L3255):

<img width="562" alt="image" src="https://user-images.githubusercontent.com/4873279/156017570-72474526-71f2-4072-acdf-b1385f2ef939.png">

Note that the request is flagged as "other" since the prerequest didn't happen in the current test. The code that does that is [here](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/proxy-logging.ts#L305-L315)

### Desired behavior

A request in one test should not be intercepted by a subsequent test.

### Test code to reproduce

This code is an example of what causes the problem:

https://github.com/cypress-io/cypress/blob/05f9ad163ec4ab13dc296b6ec184d28b5cea6670/packages/driver/cypress/integration/commands/net_stubbing_spec.ts#L3237-L3255

It is a race condition however so it will not occur consistently.

### Cypress Version

9

**Comment by flotwig** [comment]
I think that this is partly caused because Cypress `req.destroy`s unresolved intercepted requests before each test, which increases the number of retries automatically sent by the browser: https://github.com/cypress-io/cypress/blob/c3eb6350fb0c5cee15da18ae766390c6796794dc/packages/net-stubbing/lib/server/state.ts#L9-L23

This behavior makes sense when the proxy can't know how to fulfill the request, which is if there is a callback supplied to `req.reply` or `res.continue`. We don't want these callbacks to leak between tests, so we don't want to run them if the test that defined them has already concluded. 

But if a StaticResponse is being used, or we're in the response phase and the request callback has already completed, or the user is only using `.spy`, there's no harm in allowing the request to complete, since we know it was initiated by the same test that defined the applicable `cy.intercept`. So we should update `netStubbingState#reset` to not `.destroy` in the case that the `.intercept` is resolvable without a callback to the browser. This will reduce the possibility for users to encounter this issue by limiting it to cases where `cy.intercept` is used with a callback and the request leaks across tests.

**Comment by TLadd** [comment]
Ran into this. It was happening pretty reliably for us on tests that are very quick  Specifically, we were just testing that under specific conditions, we redirect to the correct place. So the tests were basically just intercepting network requests, `cy.visit`, and asserting that the pathname becomes what we expect. Fairly often, the test following that sort of test would fail, looking like the `intercept` call in that following test never took effect.

We've worked around it by adding an additional assertion to the very fast tests that just gets an expected element  on the page that is redirected to, and thus guaranteeing that the calls that go out to load that page have resolved by the time the test ends and therefore can't bleed over into the next test.

**Comment by fochlac** [comment]
For component testing I added a global wrapper around the fetch function that can be used to reset all stale fetch-requests. For a full workaround more wrappers around the other async methods, especially setTimeout/setInterval would be needed, but for us it seems to mostly fix the issue. I'm dropping it here in case it helps someone:
```
/**
 * Workaround for https://github.com/cypress-io/cypress/issues/20397
 * sometimes requests bleed over into the next texts, as the container is not 
 * reset between it-blocks. This leads to intercepts not being able to catch them.
 */

let index = 0
let cutoff = Number.MAX_SAFE_INTEGER
before(() => {
    cy.window().then((win) => {
        const fetch = win.fetch
        const mockPromise = {
            then() {
                return mockPromise
            },
            catch() {
                return mockPromise
            },
            finally() {
                return mockPromise
            }
        }
        win.fetch = (url, ...params) => {
            if (cutoff > index) {
                return mockPromise
            }
            const id = index++
            const method = params?.[0]?.method || 'get'
            return fetch(url, ...params)
                .then(
                    (result) => {
                        if (id < cutoff) {
                            console.error(`Discarded ${method.toLocaleUpperCase()}-request to "${url}" - you should propably await it in your test.`)
                            return mockPromise
                        }
                        return result
                    },
                    (error) => {
                        if (id < cutoff) {
                            console.error(`Discarded ${method.toLocaleUpperCase()}-request to "${url}" - you should propably await it in your test.`)
                            return mockPromise
                        }
                        return Promise.reject(error)
                    }
                )
        }
    })
})

// new fetch request can have been created by async methods i.e. setTimeout, so disable fetch until the component is mounted again.
afterEach(() => {
    cutoff = Number.MAX_SAFE_INTEGER
})

// this will usually run earlier than your intercept setups, but its better than nothing. if possible integrate the cy.activateFetch command below in your testcode after the intercepts are set up.
beforeEach(() => {
    cutoff = index
})

// command used to reenable fetch. if you use this, delete the beforeEach above.
Cypress.Commands.add('activateFetch', () => {
    cutoff = index
})
```

**Comment by antischematic** [comment]
Please reopen this issue.

**Comment by uladzimirdev** [comment]
It happened in my test where I simulated long response from the server. I didn't find a way to somehow cancel the request, so it affects number of intercepted calls in another test

**Comment by Hypenate** [comment]
Having the same issue in our project.
Not sure why this was closed.

Well, it _seems_ we solved it.
We are using Angular, and we were not `await`ing our navigate.
