### ISSUE TITLE
Add ability to see full test name in Test Result UI

### ISSUE THREAD

**Issue by StephenOTT** [cypress-io/cypress#204]
Currently if you have a long test name you get ellipsis:

![screen shot 2016-08-24 at 5 19 06 pm](https://cloud.githubusercontent.com/assets/1994838/17948582/60f1cc24-6a1f-11e6-8ab7-1188aa7a0229.png)

would be great if we could see the full text.  This is mainly a problem when you are on smaller screens such as a Macbook Air 13" 😉 

@chrisbreiding

**Comment by brian-mann** [comment]
Let's implementing dragging the divider between the runner + reporter and then persisting the state to the local `app data` on the file system.

**Comment by brian-mann** [comment]
Fixed in [`0.17.5`](https://github.com/cypress-io/cypress/wiki/Changelog#0175-10022016).
