### ISSUE TITLE
Missing url to navigate to {spec file path}

### ISSUE THREAD

**Issue by rishoo2019** [cypress-io/cypress#20407]
### Current behavior

Reading through the [**extending-the-cypress-config-file**](https://www.cypress.io/blog/2020/06/18/extending-the-cypress-config-file/) on cypress blog, i have implemented it.

On my cypress dashboard, i can see the configuration files getting merged and producing a desired configuration.

**Note:** The spec file path it shows in exception is incorrect. An extra folder `/#/tests/integration/` path is getting appended to my file path. Whereas the correct path to my intragrations is: 
`cypressE2ETesting/apiIntegrationTests/testFile.spec.ts`

While running the test i am getting following exception:

**Missing url to navigate to {spec file path}**

`**Title:** Error launching browser

**Message:** missing url to navigate to /#/tests/integration/apiIntegrationTests/testFile.spec.ts

**Stack trace:**
```
Error: missing url to navigate to /#/tests/integration/apiIntegrationTests/testFile.spec.ts
    at lazyAssLogic (C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\node_modules\lazy-ass\index.js:110:14)
    at lazyAss (C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\node_modules\lazy-ass\index.js:115:28)
    at Object.<anonymous> (C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\packages\server\lib\browsers\chrome.js:230:32)
    at Generator.next (<anonymous>:null:null)
    at C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at __awaiter (C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\node_modules\tslib\tslib.js:113:16)
    at Object._navigateUsingCRI (C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\packages\server\lib\browsers\chrome.js:228:34)
    at Object.<anonymous> (C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\packages\server\lib\browsers\chrome.js:417:24)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (C:\Users\rishoo.mittal\AppData\Local\Cypress\Cache\9.5.0\Cypress\resources\app\node_modules\tslib\tslib.js:114:62)

````

My generated configuration file is as follows:
`{
animationDistanceThreshold:5
baseUrl:"http://localhost:4200"
blockHosts:null
chromeWebSecurity:false
clientCertificates:
component:{}
componentFolder:"cypress/component"
defaultCommandTimeout:10000
downloadsFolder:"cypressE2ETesting/cypressArtifactsAndDownloads/downloads"
e2e:{}
env:
api_server:"http://nodejs-fb-app.herokuapp.com/"
login:"/login"
registration:"/registration"
execTimeout:20000
exit:true
experimentalFetchPolyfill:false
experimentalInteractiveRunEvents:false
experimentalSessionSupport:false
experimentalSourceRewriting:false
experimentalStudio:false
fileServerFolder:""
fixturesFolder:"cypressE2ETesting/fixtures"
ignoreTestFiles:"*.hot-update.js"
includeShadowDom:true
integrationFolder:"cypressE2ETesting/"
keystrokeDelay:0
modifyObstructiveCode:true
numTestsKeptInMemory:50
pageLoadTimeout:60000
pluginsFile:"cypressE2ETesting/plugins/index.ts"
port:3430
projectId:null
redirectionLimit:20
reporter:"junit"
reporterOptions:null
requestTimeout:5000
resolvedNodePath:null
resolvedNodeVersion:null
responseTimeout:30000
retries:
runMode:0
openMode:0
screenshotOnRunFailure:true
screenshotsFolder:"cypressE2ETesting/cypressArtifactsAndDownloads/artifacts/screenshots"
slowTestThreshold:10000
scrollBehavior:"top"
supportFile:"cypressE2ETesting/support/index.ts"
supportFolder:false
taskTimeout:60000
testFiles:"**/*.spec.ts*"
trashAssetsBeforeRuns:true
userAgent:null
video:true
videoCompression:32
videosFolder:"cypressE2ETesting/cypressArtifactsAndDownloads/artifacts/videos"
videoUploadOnPasses:true
viewportHeight:660
viewportWidth:1000
waitForAnimations:true
watchForFileChanges:true
browsers: Array (4)
0:Chrome
1:Firefox
2:Edge
3:Electron
hosts:null
isInteractive:true
$schema:"https://on.cypress.io/cypress.schema.json"
configFile:{}
testingType:{}
}`

### Desired behavior

The integration folder as mentioned in cypress.json, should be found.

### Test code to reproduce

1. Implement the blog post [extending-the-cypress-config-file](https://www.cypress.io/blog/2020/06/18/extending-the-cypress-config-file/)
2. Rename cypress folder and integrations folder.
3. Add the path to integrations folder in base.json or cypress.json or staging.json
4. Load the cypress dashboard or run tests in headless
5. You will receive an exception just before the spec file starts to get executed.
6. The browser is opened with a blank scree,

### Cypress Version

9.5.0

### Other

As mentioned i face this problem after implementing the following blog post: [Extending the Cypress Config File](https://www.cypress.io/blog/2020/06/18/extending-the-cypress-config-file/)

**Comment by clarknoah** [comment]
Also having the same issue on 8.3.0
