### ISSUE TITLE
Screenshot callbacks not called for all failure screenshots

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2040]
Currently, when a [failure screenshot is taken](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/screenshot.coffee#L284-L308), we bypass a number of steps that are unnecessary for failure screenshots as long as there hasn't been a screenshot taken in the failing test. This means that the `onBeforeScreenshot` and `onAfterScreenshot` callbacks are not called.

However, in the case that there is a screenshot taken (via `cy.screenshot()`) in the failing test, we *do* call the callbacks. 

We should fix this inconsistency and have the callbacks called for all failure screenshots.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).
