### ISSUE TITLE
can't use cypress with a proxy that requires auth

### ISSUE THREAD

**Issue by nikinchitrakar** [cypress-io/cypress#20443]
### Current behavior

I want to use cypress with a proxy that requires auth

```
HTTP_PROXY=http://username:password@host:port cypress open
```

I can see the proxy settings in the Cypress Test Runner.
![Screenshot 2022-03-02 at 9 55 45 AM](https://user-images.githubusercontent.com/19317364/156293677-6544175b-9b93-4458-a2c7-3c93ec17b258.png)

But when running the tests I am getting this error: `Wrong proxy credentials`

![Screenshot 2022-03-02 at 8 37 36 AM](https://user-images.githubusercontent.com/19317364/156285788-8f947d1e-5ec0-436e-a1a4-d38ded3711fb.png)

The same proxy is working properly using the curl command. 

### Test code to reproduce

HTTP_PROXY=http://username:password@host:port cypress open

### Cypress Version

9.5.0

**Comment by t0mm4rx** [comment]
Up! I also need this feature to work, I can't figure out how to set up a proxy that requires auth.

**Comment by mm-matthias** [comment]
FWIW Cypress seems to work just fine with an authenticated proxy now.
