### ISSUE TITLE
Running Cypress Cucumber in Jenkins pipeline

### ISSUE THREAD

**Issue by ashuans** [cypress-io/cypress#20459]
### Current behavior

I am currently running Cypress / cucumber tests as a part of our Jenkins build pipeline. This only happens on Jenkins, I am able to run the tests locally.

I am getting below error in Jenkins :-

11:03:18  Your pluginsFile is invalid: /home/jenkins/workspace/project-path/cypress/plugins/index.js
11:03:18  It threw an error when required, check the stack trace below:
11:03:18  Error: Cannot find module 'cypress-cucumber-preprocessor'
11:03:18  Require stack:
11:03:18  - /home/jenkins/workspace/project-path/cypress/plugins/index.js
11:03:18  - /home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
11:03:18  - /home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js
11:03:18      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
11:03:18      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
11:03:18      at Module.require (internal/modules/cjs/loader.js:974:19)
11:03:18      at require (internal/modules/cjs/helpers.js:101:18)
11:03:18      at Object.<anonymous> (/home/jenkins/workspace/project-path/cypress/plugins/index.js:5:18)
11:03:18      at Module._compile (internal/modules/cjs/loader.js:1085:14)
11:03:18      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
11:03:18      at Module.load (internal/modules/cjs/loader.js:950:32)
11:03:18      at Function.Module._load (internal/modules/cjs/loader.js:790:12)
11:03:18      at Module.require (internal/modules/cjs/loader.js:974:19)
11:03:18      at require (internal/modules/cjs/helpers.js:101:18)
11:03:18      at runPlugins (/home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:186:15)
11:03:18      at Object.<anonymous> (/home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
11:03:18      at Module._compile (internal/modules/cjs/loader.js:1085:14)
11:03:18      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
11:03:18      at Module.load (internal/modules/cjs/loader.js:950:32)
11:03:18  error Command failed with exit code 1.

plugins/index.js

const cucumber = require("cypress-cucumber-preprocessor").default;
module.exports = function(on){
on("file:preprocessor", cucumber());
};
My only concern is, why it's a problem in Jenkins and not in local. I went through couple of solutions but none of them worked - 

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/437

### Desired behavior

The Jenkins pipeline should work.

### Test code to reproduce

Not Required

### Cypress Version

9.2.1

### Other

I have tried all the solutions so far. Even I tried installing the cypress-cucumber-preprocessor into the Jenkins separately. None of them worked. I have stuck badly at this place. Any help would be appreciated.

**Comment by davidmunechika** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by Sindhu144** [comment]
Hi I also faced similar issue , but mine is a freestyle project .
I did npm install first and then executed the required --spec file. This fixed the issue in jenkins.
