### ISSUE TITLE
Conversion to onPointerDown

### ISSUE THREAD

**Issue by ZakTax** [cypress-io/cypress#2045]
### Current behavior:
We are converting our app to React 16.4 which introduced Pointer Events API. However, items that we convert from onClick/onMouseDown-> onPointerDown break our Cypress tests. Everything works normally on our dev environment, and we have a PointerEvents polyfill as well (cypress' Chrome version supports the API natively).

Duplicating our `onPointerDown={someAction}` to `onPointerDown={someAction} onMouseDown={someAction}` fixes the tests but adds duplication. 

### Desired behavior:
Cypress should be able to handle onPointerDown events without code duplication

### Versions
Cypress 3.0.1

**Comment by jennifer-shehane** [comment]
Pointer events documentation: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

Should be triggered on commands like:
- .click()
- .dblclick()
- .check()
- .uncheck()
- .select()

You may be able to use `.trigger()` to trigger the `pointerdown` events in the meantime.

**Comment by Bkucera** [comment]
@ZakTax Hi, we're planning on firing pointer events with cy.click as a part of Native Events #2956
