### ISSUE TITLE
NTLM login

### ISSUE THREAD

**Issue by Rashminair88** [cypress-io/cypress#20451]
### Current behavior

I am trying to log in to a site that's windows authenticated. 
[cypress-ntlm-auth](https://github.com/bjowes/cypress-ntlm-auth)[](https://user-images.githubusercontent.com/96204241/156216571-033c57a9-78db-477a-bbdb-aeb59a93ac69.png).
image

I tried with both cypress 9.4.0 and 9.5.1. Getting same error
Do I need to set proxy? set HTTP_PROXY=http://my-company-proxy.com
I have another issue opened:  #20422, But no reply on that. SO creating new issue
### Desired behavior

Should be able to login

### Test code to reproduce

 cy.ntlm(['rhbeta.rockfin.com', 'rhbeta.rktfoc.com'], Cypress.env('uname'), Cypress.env('password'));
  cy.visit("https://rhbeta.rktfoc.com/crib/dashboard/tester");

### Cypress Version

9.4.0, 9.5.1

**Comment by sainthkh** [comment]
Sorry for the late reply.

It seems that the problem is on `cypress-ntlm-auth`'s side. Maybe, opening an issue on the plugin's repo might solve the problem.

**Comment by Rashminair88** [comment]
Thank you. Will do.
