### ISSUE TITLE
Intercept and stub third party `<script>` tags

### ISSUE THREAD

**Issue by Mohamed3on** [cypress-io/cypress#20469]
### What would you like?

Our use case: Testing a third party widget on a website. 

For that, we load the widget on the third party as a `<script src='https://cdn.com/widget.js'/>` tag. What we'd like to do is intercept that JS request and replace `https://cdn.com/widget.js` with `https://localhost:3000/dist/widget.js`.

### Why is this needed?

So that we can run the cypress tests with the local version of the widget (run in CI on a PR), and make sure that the PR doesn't break the e2e tests, before merging it.

**Comment by jennifer-shehane** [comment]
Since this feature request hasn’t had a lot of interest, we’ll close this issue.
