### ISSUE TITLE
Cypress - Unable to login static CDN URL - working with selenium though

### ISSUE THREAD

**Issue by UdaiSingh163** [cypress-io/cypress#20462]
### Current behavior

Unable to navigate to home screen posting login.
Page keeps loading once user enter username and password.

### Test code to reproduce

describe("Loing test",()=>{
it('does not match',()=>{

    cy.visit('https://ofsaa.us-phoenix-1.ocs.oc-test.com/todrfu-prd/afc')

    cy.get('input[id="idcs-signin-basic-signin-form-username"]').type('AFCSQA')
    cy.get('input[id="idcs-signin-basic-signin-form-password|input"]').type('Password1234')
    cy.contains('Sign In').click()

 
})
})

### Cypress Version

command not found error - used "cypress version"

**Comment by davidmunechika** [comment]
I see that you haven't listed the Cypress version you are using. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!
