### ISSUE TITLE
Redirects do not honor `set-cookie` header

### ISSUE THREAD

**Issue by kentcdodds** [cypress-io/cypress#20476]
### Current behavior

I have a `cy.request` that ends up doing several redirects (as intended). In one of them a cookie is set along with the redirect location. The next request to follow the redirect does not include the cookie header:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/1500684/156665684-8776e852-8cdb-4bb0-9e31-f9a2a4295022.png">

Here's my `cy.request` call that starts this chain of redirects:

```ts
cy.request('POST', '/__tests/login', {email, firstName, team, role})
```

### Desired behavior

Cypress should behave as a browser does when following redirects for a `cy.request` call.

### Test code to reproduce

My repository is open source, you can follow the instructions here to get it set up: https://github.com/kentcdodds/kentcdodds.com/blob/main/CONTRIBUTING.md#project-setup

This is the test I ran to get the screenshot above: https://github.com/kentcdodds/kentcdodds.com/blob/main/cypress/e2e/contact.cy.ts

### Cypress Version

9.5.1 (latest at the time of this report)

### Other

I've experienced this in another (non-public) project and had to workaround it using `cy.setCookie` manually. I'd love to not have to do that here.

**Comment by AtofStryker** [comment]
Almost wondering if there is a slight delay in the automation API setting cookies on `http:request` in the server socket? The cookie looks to be eventually set and sent with subsequent requests except for the one immediately proceeding it

**Comment by jonasraoni** [comment]
Hey @kentcdodds, this looks similar to: https://github.com/cypress-io/cypress/issues/19800, which has a temporary workaround available (changing the `SameSite` setting).

**Comment by wilsonpage** [comment]
I had a similar issue with `cy.visit()`, here's my workaround 👇 

```ts
// HACK: cypress seems to drop cookies that have 'Secure;' and 'SameSite=None';
// when used w/ localhost and redirects. As a workaround we intercept the redirect
// response and remove the `Secure` and `SameSite` flags from the cookie values.
// https://github.com/cypress-io/cypress/issues/20476
cy.intercept('/your-endpoint-that-redirects', (req) => {
  req.continue((res) => {
      const value = res.headers['set-cookie'];
      const setCookie = Array.isArray(value) ? value : [value];

      res.headers['set-cookie'] = setCookie.map((value) =>
        value.replace(/ ?Secure;?/, '').replace(/ ?SameSite=None;?/, '')
      );
   });
});

cy.visit('/your-endpoint-that-redirects');
```

**Comment by Deop** [comment]
Haven't tried a workaround yet, but would be nice to have this fixed/implemented in Cypress.
