### ISSUE TITLE
'Failed to fetch' error when calling fetch in `cypress run`

### ISSUE THREAD

**Issue by amitzur** [cypress-io/cypress#2047]
### Current behavior:

Getting `Failed to fetch` error when running `cypress run` and visiting a website in `https`.
I'm not getting this error when running in `cypress open` and also not when running in `http` websites.

### Desired behavior:

Not to get this error.

### Steps to reproduce:

I made one commit to demonstrate the problem in the following fork and branch:
https://github.com/amitzur/cypress-test-tiny/tree/fetch_issue

I'm calling `fetch` inside a custom command to a local webserver launched in a cypress plugin.

### Versions

This happens on both Cypress version `2.1.0` and `3.0.1`

**Comment by jennifer-shehane** [comment]
When running `cypress run`, the tests are run within the packaged Electron browser - which as of 3.0.1 uses Chromium version 59. 

You can recreate the issue in `cypress open` by selecting Electron from the dropdown of browsers. This will at least show the error in a more interactive manner - but the issue may be just an issue in Chromium 59. I didn't look into the actual cause of the error. 

<img width="912" alt="screen shot 2018-06-27 at 10 48 09 am" src="https://user-images.githubusercontent.com/1271364/41981723-9c42dd42-79f7-11e8-801e-6f6c60c21864.png">

**Comment by amitzur** [comment]
Thanks! This indeed makes it easier to understand and reproduce.
I did suspect this to be a mixed-content issue. But is it related to Chrome's earlier version or to Electron?

![screen shot 2018-06-27 at 6 03 11 pm](https://user-images.githubusercontent.com/394320/41982600-88c2f10c-7a34-11e8-877f-1958498bf9a3.png)

**Comment by jennifer-shehane** [comment]
Honestly, I'm not sure about where the difference originates. I believe you should be able to set `chromeWebSecurity` to `false` in your `cypress.json` if you want to ignore this error in your tests though.

```json
{
  "chromeWebSecurity": false
}
```

**Comment by austinfox** [comment]
Why was this closed? It doesn't seem like the original bug was fixed. I'm experiencing this issue as well and would like to avoid disabling chromeWebSecurity if possible.

**Comment by jennifer-shehane** [comment]
@austinfox You'll have to set `chromeWebSecurity` false because the action that is being performed is against chromes web security protocols. This error will always show without it.

**Comment by VigneshTrantor** [comment]
> Why was this closed? It doesn't seem like the original bug was fixed. I'm experiencing this issue as well and would like to avoid disabling chromeWebSecurity if possible.

Have you managed to solve it ? I am facing the same problem too

**Comment by anilpujaraofficial** [comment]
![Screenshot from 2023-09-27 16-36-04](https://github.com/cypress-io/cypress/assets/65593381/f345f7b8-012c-4351-95c1-784c75b7bcda)

how can handle this issue

**Comment by MikeMcC399** [comment]
@anilpujaraofficial 

Your screenshot appears to be from https://sorry-cypress.dev/ not from Cypress so this would be the wrong place to report your issue.
