### ISSUE TITLE
Restore Pages prompt

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2048]
After manually crashing chrome, I was prompted with this "Restore Pages?" dialog / prompt. 
I would prefer if that didn't happen
![image](https://user-images.githubusercontent.com/14625260/41982956-b8730980-79fa-11e8-833d-a086c058e864.png)
I'm not entirely sure if this causes any issues besides cosmetics, but I could see it being an issue.

**Comment by ap1969** [comment]
Hi,
I get this as well. I thought when chrome was launched via Cypress this was supposed to be suppressed. Did you find a workaround?
Regards,
Andy

**Comment by Bkucera** [comment]
@larscom @ap1969  no, but please place a :+1: on the top level to help us gauge the importance of this

**Comment by flotwig** [comment]
There used to be a command-line flag for this (`--disable-session-crashed-bubble`) but it got removed in Chrome 58. We can load the Preferences and use this method to fix it before we launch: https://superuser.com/a/886258/458816
