### ISSUE TITLE
cypress support for latest, latest-1 browser versions

### ISSUE THREAD

**Issue by lsamruth** [cypress-io/cypress#20502]
### Current behavior

With current docker images `cypress/browsers:node14.17.0-chrome91-ff89` we will be running scripts in one chrome version.
i.e chrome-91.

### Desired behavior

I would like to run scripts in latest browser and minus one versions
ex: 
1.chrome91
2.chrome90

### Test code to reproduce

NA

### Cypress Version

9.1.1

**Comment by jennifer-shehane** [comment]
There is a chrome90 docker-image, see https://github.com/cypress-io/cypress-docker-images/tree/master/browsers.

You can run two separate runs with either docker images. Is there something prohibiting this?

**Comment by lsamruth** [comment]
thanks for quick reply @jennifer-shehane , my intention was to run tests in latest and latest-1 version of any browser.
i have just given example of chrome91 and chrome90.
