### ISSUE TITLE
UI bug in cypress dashboard: running test icon doesn't fit neatly on the test panel

### ISSUE THREAD

**Issue by fawadshahzada** [cypress-io/cypress#20506]
### Current behavior

Unexpected behavior LInk to bug :https://drive.google.com/file/d/16eP47pX7B6c88sVKoSUAmDl99CktCEt0/view?usp=sharing

### Test code to reproduce

No, its UI bug

### Cypress Version

8.7.0

### Other

Bug Video https://drive.google.com/file/d/16eP47pX7B6c88sVKoSUAmDl99CktCEt0/view?usp=sharing

**Comment by jennifer-shehane** [comment]
We've notified the Dashboard team of the UI bug.

**Comment by finnstech** [comment]
This is being tracked internally and should be fixed shortly!

**Comment by benpatterson** [comment]
This has been pulled into active work.

**Comment by benpatterson** [comment]
This has been fixed. 🎉
