### ISSUE TITLE
wait for intercept never gets triggered

### ISSUE THREAD

**Issue by goldylucks** [cypress-io/cypress#20503]
### Current behavior

I register an interceptor:
```
cy.intercept("/api/v1/payments/customers/payment_methods.json*").as('payment_methods')
```
and then make an action that triggers this request:
```
GET 200 /api/v1/payments/customers/payment_methods.json?some-query-params-here
```
then wait for it
```
cy.wait("@payment_methods");
```

and even tho I can see the get request after the wait has been registered, the wait times out:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/6963212/156980631-ad883357-2c6e-45e4-9a8f-efbd90b74227.png">

### Desired behavior

the wait should catch the request

### Test code to reproduce

I can't consistently reproduce this, it happens on some of our interecptors but not for others.

### Cypress Version

7.4.0

**Comment by davidmunechika** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog)[](https://gist.github.com/jennifer-shehane/8a819d831efd7d82b4714d286ef2bde5#triage---cypress-version-cached) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by mattvb91** [comment]
There is something extremely weird happening here. I have been running v9.4.1 for the past few weeks and today all of a sudden ALL of my interceptors stopped working / listening. So my assumption is that some chrome update happened and broken something??

Upgrading to 9.5.1 seems to resolve it... But again, this was working for weeks and stopped as of today

**Comment by Emzawadzki** [comment]
I have similar issue, which is not however 100% repeatable. Sometimes request is intercepted correctly and sometimes it isn't. Latest Cypress version (9.5.2)
<img width="516" alt="obraz" src="https://user-images.githubusercontent.com/37591659/159497875-ab1e0432-8db9-4e54-82e6-5e95fdfa8671.png">
The code responsible:
```typescript
  cy.visit('/');
  cy.intercept({
    method: 'POST',
    url: '/api/users/login',
  }).as('postLogin');
  cy.get('#email').type(E2E_USER_EMAIL);
  cy.get('#password').type(E2E_USER_PASSWORD);
  cy.get('button').contains('LOGIN').click();
  return cy.wait('@postLogin').then(/* do sth with data */)
```
The API response time in this particular case was ~800ms, so much less than timeout given.

In case it succeeded it looks like: (everything was the same - both tests were ran in a single `cypress open` session.
<img width="518" alt="obraz" src="https://user-images.githubusercontent.com/37591659/159499032-60c7fa26-22a8-497e-9d06-7dcdcf27c4c3.png">

What's also interesting is it doesn't seem to happen in CI environment via `cypress run` command.
It's not the only place I have such troubles (also with other requests), though it subjectively seems to work a bit more smoothly in Cypress 9.5.2 compared to previously used 9.0.0
