### ISSUE TITLE
Promises timing out in proton, but not chrome

### ISSUE THREAD

**Issue by jfisher-staywell** [cypress-io/cypress#20514]
### Current behavior

Hello,
I have a block of code below that runs differently depending on how the spec file is started.
I do recognize I'm using promises in a bit of an odd way, however, the way the code runs should be similar no matter how it's started.  It shouldn't run differently in proton, or whether or not I'm starting it from the UI or from the command line.

if I start the spec file from `cypress open` using chrome - everything passes and all logs work correctly.
![image](https://user-images.githubusercontent.com/38301059/157095560-b967c51c-62d4-4992-9d28-bec39957b545.png)
if I start the spec file from `cypress open` using Electron - the second test block fails when trying to run the second promise
![image](https://user-images.githubusercontent.com/38301059/157095478-fb85722e-bc02-4e93-866e-75d1a3aefec3.png)
if I start the spec file from `cypress run` using either electron (default) or specify chrome - the second test block fails when trying to run the second promise.
```
npx cypress run -s 'cypress/integration/0WebMd/UiTests/sandbox.spec.js' --browser chrome 96 --headed
...
  sandbox
    ✓ single promise works
    1) should not timeout


  1 passing (4s)
  1 failing

  1) sandbox
       should not timeout:
     CypressError: Cypress command timeout of `4000ms` exceeded.
      at cypressErr (https://www.blue.dev.webmdhealth.com/__cypress/runner/cypress_runner.js:176336:18)
      at Object.errByPath (https://www.blue.dev.webmdhealth.com/__cypress/runner/cypress_runner.js:176405:10)
      at https://www.blue.dev.webmdhealth.com/__cypress/runner/cypress_runner.js:178159:80
```

### Desired behavior

Code should run the same on chrome/proton and whether it's started through the UI or the command line.

Preferably the test cases I included in the test code will pass and things get logged properly.

### Test code to reproduce

```js
describe('sandbox', function () {
	it('single promise works', async function () {
		var p = new Cypress.Promise((resolve, reject) => {
			Cypress.on('fail', rejectPromise);

			function resolvePromise(value) {
				resolve(value);
				Cypress.off('fail', rejectPromise);
			}
			function rejectPromise(error) {
				reject(error);
				Cypress.off('fail', rejectPromise);
			}

			cy.wrap('foo').then(resolvePromise);
		});

		var t = await p;
		cy.log(t);
	});
	it('should not timeout', async function () {
		var p = new Cypress.Promise((resolve, reject) => {
			Cypress.on('fail', rejectPromise);

			function resolvePromise(value) {
				resolve(value);
				Cypress.off('fail', rejectPromise);
			}
			function rejectPromise(error) {
				reject(error);
				Cypress.off('fail', rejectPromise);
			}

			cy.wrap('foo').then(resolvePromise);
		});

		var t = await p;
		cy.log(t);

		var p2 = new Cypress.Promise((resolve, reject) => {
			Cypress.on('fail', rejectPromise);

			function resolvePromise(value) {
				resolve(value);
				Cypress.off('fail', rejectPromise);
			}
			function rejectPromise(error) {
				reject(error);
				Cypress.off('fail', rejectPromise);
			}

			cy.wrap('foo').then(resolvePromise);
		});

		var t2 = await p2;
		cy.log(t2);
	});
});
```

### Cypress Version

9.5.1

**Comment by miracllife** [comment]
having same problem

**Comment by miracllife** [comment]
like this one :https://github.com/cypress-io/cypress/issues/6202
