### ISSUE TITLE
[Error TS18002] Cypress Typescript Not Working

### ISSUE THREAD

**Issue by Wilson13** [cypress-io/cypress#20524]
### Current behavior

Followed the steps documented on this page: https://docs.cypress.io/guides/tooling/typescript-support.

But can't run any Typescript test file due to the following error:

> Error: Webpack Compilation Error
> [tsl] ERROR
>       TS18002: The 'files' list in config file 'tsconfig.json' is empty.

<img width="1202" alt="Screenshot 2022-03-08 at 9 45 52 AM" src="https://user-images.githubusercontent.com/5605451/157149470-d8b352dd-a785-47ac-8315-e4c3e891fb85.png">

### Desired behavior

Able to run Typescript test files.

### Test code to reproduce

Change any example JS file to TS file and attempt to run it.

### Cypress Version

9.5.1

### Other

Cypress package version: 9.5.1
Cypress binary version: 9.5.1
Electron version: 15.3.4
Bundled Node version: 16.5.0

**Comment by flotwig** [comment]
Hi @Wilson13, I believe this is a duplicate of #18938 (misleading error with no tsconfig.json), can you confirm if your project has a `tsconfig.json` in root?

**Comment by IPWright83** [comment]
I've got the same problem, I have no `tsconfig.json` as I'm not using TypeScript.

**Comment by dinaRodeny** [comment]
I've got the same problem

**Comment by GeorgeousPRO** [comment]
this might happen if you have the `configFile `property incorrectly set in _webpack.config.j_s file. 
 use: [
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
              configFile: 'cypress/tsconfig.json',
            },
          },

**Comment by stefanusdeo07** [comment]
I've got the same problem :'(
