### ISSUE TITLE
'cy.click' or 'click({ force: true })' or 'trigger('mouseover').click({ force: true })' nothing works in github pipeline sometime and test fails

### ISSUE THREAD

**Issue by nishant994** [cypress-io/cypress#20527]
### Current behavior

'cy.click' or 'click({ force: true })' or 'trigger('mouseover').click({ force: true })' nothing works in github pipeline sometime and test fails
A very wired situation. 'cy.click' or 'click({ force: true })' or 'trigger('mouseover').click({ force: true })' nothing works in github pipeline sometime and test fails. It works perfectly fine by running from cypress runner but issue is only in github pipeline. Its really annoying and stopping our deployment pipeline. Can somebody please please help!!!!!

### Desired behavior

Cypress should aways click on the element but it doesn't. Only in the github runner from github workflow

### Test code to reproduce

cy.get('[data-testid="searchButton"]').should('be.visible').click({ force: true })

### Cypress Version

9.5.1

### Other

It stopping my deployment pipeline. Need urgent help to resolve

**Comment by davidmunechika** [comment]
Could you include a code example to reproduce this issue (possibly an example repo)? Unfortunately, if we don't have enough information to recreate the issue we will have to close this issue. Thanks!

**Comment by nishant994** [comment]
it('displays results when given a query', () => {
    const searchField = new SearchField()
    cy.visit(url)
    cy.acceptCookie()
    cy.wait(8000)
    searchField.getSearchButton().should('be.visible').trigger('mouseover').click({force:true})
    searchField.getSearchTextField().should('be.visible').type('TEST')
    searchField.getSearchResultDropdown().should('be.visible')
    searchField.getFirstElementFromDropdown().trigger('mouseover').click({force:true})
    searchField.getSearchResult().should('be.visible')
  })
})

**Comment by nishant994** [comment]
Giving static wait as 8000 ms works but removing it, fails most of the time in CI/CD pipeline

**Comment by nicktelindert** [comment]
Same issue here, only difference is i use bitbucket pipelines.  Click works locally but not when running in pipeline.

**Comment by anzhelikakovalchuk** [comment]
have the same issue, neither `click` or `trigger('click')` works in pipeline

**Comment by jhmartins0x1** [comment]
Hello @nishant994 
did you find a solution?
