### ISSUE TITLE
Error: use mount or unmount functions please place the spec in component folder

### ISSUE THREAD

**Issue by DamomHd** [cypress-io/cypress#20528]
### Current behavior

When I run my component test, I get the following error:
Error: In order to use mount or unmount functions please place the spec in component folder

### Test code to reproduce

When I run my component test, I get the following error:
Error: In order to use mount or unmount functions please place the spec in component folder
<img width="656" alt="image" src="https://user-images.githubusercontent.com/33109486/157229013-c3b560da-2427-4281-8e3f-67571b472017.png">

<img width="457" alt="image" src="https://user-images.githubusercontent.com/33109486/157229124-9ca3e1d7-dee1-4c43-9a35-ae971a6d9e30.png">

~cypress/conponent/hello.spec.js :
```
/// <reference types="cypress" />
import { mount } from 'cypress-vue-unit-test'
import Hello from '../../src/components/Helloword.vue'
describe('Hello.vue', () => {
  it('shows hello', () => {
    mount(Hello)
    cy.contains('Hello World!')
  })
})
```

~src/components/Helloword.vue :

```vue
<template>
  <h1>hello</h1>
</template>

<script>
export default {

}
</script>

<style>

</style>
```

~cypress/plugins/index.js:
```
const { startDevServer } = require('@cypress/webpack-dev-server')
const webpackConfig = require('@vue/cli-service/webpack.config.js')

module.exports = (on, config) => {
  on('dev-server:start', options =>
    startDevServer({
      options,
      webpackConfig
    })
  )

  return config
}
```

Versions :

- @cypress/vue@3.1.1 
- cypress@9.5.1 
- node@v14.17.3

### Cypress Version

9.5.1

**Comment by JessicaSachs** [comment]
👋🏻 Hey, you're a few major versions behind. Please follow the instructions at https://on.cypress.io/component to get setup again. You should be running `@cypress/vue` since Cypress 7.0.0

**Comment by ZachJW34** [comment]
This should no longer be an issue for Cypress CT testing > v10. If it is, feel free to reopen this issue.
