### ISSUE TITLE
Cypress Test failed with the Error: Webpack Compilation Error

### ISSUE THREAD

**Issue by ndhakal26** [cypress-io/cypress#20533]
### Current behavior

Cypress test should pass.

### Desired behavior

Error: Webpack Compilation Error
20:20:34   Module build failed (from C:/Users/TCAgentUser$/AppData/Local/Cypress/Cache/9.4.1/Cypress/resources/app/node_modules/babel-loader/lib/index.js):
20:20:34   BrowserslistError: Unknown version 15 of Safari

### Test code to reproduce

# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries

# You can see what browsers were selected by your queries by running:
#   npx browserslist

# These are what we support (Edge is covered, but not listed due to a bug in CLI):

last 2 Chrome versions
last 2 ChromeAndroid versions

# Bug in can-i-use-lite and Angular CLI compatibility on how Safari is reported!
# When we upgrade to Angular 13 we can restore this rule and delete the more specific Safari ones.
# last 2 Safari versions
Safari 15
Safari 14

last 2 iOS versions

last 2 Firefox versions
last 2 FirefoxAndroid versions

not IE 9-11

### Cypress Version

9.4.1

**Comment by sainthkh** [comment]
Sorry for the late reply.

Is it still happening with the latest version?
