### ISSUE TITLE
Unable to intercept request using cy.intercept

### ISSUE THREAD

**Issue by justinpincar** [cypress-io/cypress#20536]
### Current behavior

I am trying to mock Algolia's search API using the following code.

```
cy.intercept({
  hostname: 'algolia_app_id-dsn.algolia.net',
}, (req) => {
  req.reply({
    cat: 'dog',
   });
   return;
});
```

The interception route is registered, as shown in the screenshot, but it is not intercepted. The `cy.intercept` call is part of the same test and happens well before the actual network request is made.

<img width="1624" alt="Screen Shot 2022-03-08 at 15 37 45" src="https://user-images.githubusercontent.com/810323/157344153-4520e304-bb58-43c4-a301-24e34d42f384.png">

I've read the docs repeatedly and tried different versions of the interceptor syntax, but it never intercepts. Is this a bug?

### Desired behavior

It should intercept the API request and reply with `{ cat: 'dog' }`

### Test code to reproduce

```
cy.intercept({
  hostname: 'algolia_app_id-dsn.algolia.net',
}, (req) => {
  req.reply({
    cat: 'dog',
   });
   return;
});
```

### Cypress Version

9.5.1

### Other

Intercepting local requests seems to work. Is there a restriction on 3rd-party interceptions?

**Comment by 0xApotheosis** [comment]
I'm getting the same issue when attempting to update our axios package from `0.24.x` to `0.26.x`.

It's registered the interception route, as in the screenshot above, but seems to ignore the intercept when the tests run.

This only occurs on axois `0.26.x` - we can mitigate the issue for now by not upgrading.

**Comment by dominics** [comment]
Algolia uses a `Transfer-Encoding: chunked` response, so this is likely https://github.com/cypress-io/cypress/issues/1185 (and https://github.com/cypress-io/cypress/issues/24278)
