### ISSUE TITLE
Chrome 67 is not displaying text elements

### ISSUE THREAD

**Issue by mrreynolds** [cypress-io/cypress#2053]
### Current behavior:

Chrome 67 (booted by cypress 3.0.1 is not showing any text elements, regardless of the page I'm visiting. Even the cypress UI elements have no text.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/3011/42020994-c8b93afc-7ab9-11e8-81dd-f1f416ccfb4b.png">

### Desired behavior:

Text elements should be present and readable.

### Steps to reproduce:

    git clone https://github.com/mrreynolds/cypress-test-tiny.git
    npm i
    npx cypress open
    Run spec.js

### Versions

cypress 3.0.1
Chrome 67

**Comment by brian-mann** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/1617#issuecomment-397373555
