### ISSUE TITLE
chromeWebSecurity flag behaves differently in open and headless mode with chrome browser

### ISSUE THREAD

**Issue by bahunov** [cypress-io/cypress#20541]
### Current behavior

When visiting insecure content (https://docs.cypress.io/guides/guides/web-security#Insecure-Content) with chromeWebSecurity: false and chrome browser in open mode - it works.

When doing the same in headless mode (with chrome browser) - it gives an error:  This request has been blocked; the content must be served over HTTPS."

Note. as workaround, I'm using electron in headless mode.

### Desired behavior

Should be same behaviour in both open and headless mode

### Test code to reproduce

https://docs.cypress.io/guides/guides/web-security#Insecure-Content

### Cypress Version

9.1.1

**Comment by opanitch** [comment]
I am experiencing the same issue with Chrome headless when trying to run a test that clicks a link that directs to a different subdomain ("application") which currently requires `http` due to TLS/Auth updates that are still in development.

**Comment by julien-robert50** [comment]
Hi, same issue on my side but with an older version of Cypress `7.0.1`. Suggested workaround with Electron works.

**Comment by KyorCode** [comment]
Same here `v10.3.0`. Running Electron in headless does work locally, but hangs on the CI. Can't connect to electron.. times out.. :/

**Comment by Pardonjo** [comment]
I have the same issue in `v10.9.0` & `v10.10.0`. I have some tests where I have to visit a third party site ([here](https://www.theoplayer.com/test-your-stream-hls-dash-hesp)). This is with chromeWebSecurity set to false and in headless, the test fail : 

> error (security): Mixed Content: The page at 'https://www.theoplayer.com/__/#/specs/runner?file=cypress/integration/test.js' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://time.akamai.com/?iso&ms'. This content should also be served over HTTPS.

When running in headed the test still fail but it's now a warning : 

> warning (security): Mixed Content: The page at 'https://www.theoplayer.com/__/#/specs/runner?file=cypress/integration/test.js' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://time.akamai.com/?iso&ms'. This content should also be served over HTTPS.

None of the workarounds in this ticket have worked for me. To find more about this I have created a separate project with one test where all I am doing is just visiting the page. Cypress is executed inside this docker image : node14.15.0-chrome96-ff94 found in the cypress/browser docker hub. I also tried with a few other images without success.
