### ISSUE TITLE
Cypress.Buffer has the wrong TypeScript type

### ISSUE THREAD

**Issue by dantman** [cypress-io/cypress#20542]
### Current behavior

The TypeScript type for `Cypress.Buffer` is currently mapped to the type of a Buffer instance, not the static/constructor.

As a result trying to use `Cypress.Buffer.from` gives the TypeScript error:
```Property 'from' does not exist on type 'Buffer'. Did you mean to access the static member 'Buffer.from' instead?```

### Desired behavior

Using `Cypress.Buffer.from` should not result in a TypeScript error.

### Test code to reproduce

```ts
Cypress.Buffer.from('Test');
```

### Cypress Version

9.5.1

**Comment by jennifer-shehane** [comment]
We'd welcome a PR to fix this.
