### ISSUE TITLE
CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

### ISSUE THREAD

**Issue by SiwarBelhadi** [cypress-io/cypress#20555]
### Current behavior

i don't receive the bug when i run the test but when i throw a repport

### Desired behavior

cy

### Test code to reproduce

cy.get('#validate-export').click()

### Cypress Version

8.7.0

**Comment by davidmunechika** [comment]
Could you include a reproducible example (possibly an example repo) so that we will be able to reproduce and investigate this issue? Unfortunately, if we don't have enough information to reproduce the issue we will have to close this issue.
