### ISSUE TITLE
`{enter}` not working in Firefox 98

### ISSUE THREAD

**Issue by LaurensLeeuwis** [cypress-io/cypress#20562]
### Current behavior

When sending `{enter}`, it doesn't work in Firefox 98, while it did work in Firefox 97.

### Desired behavior

Sending `{enter}` has the same behavior in Firefox 98 as in older Firefoxes and other browsers.

### Test code to reproduce

```javascript
describe('Hitting enter', () => {
  it('works', () => {
    cy.visit('https://www.duckduckgo.com/');
    cy.get('input#search_form_input_homepage').type('hello{enter}');
    cy.get('div#links_wrapper').should('exist');
  });
});
```

### Cypress Version

9.5.1 (reproduced in 7.5.0)

**Comment by melibe23** [comment]
I am experiencing the same issue over here.

**Comment by sainthkh** [comment]
Confirmed that it doesn't work on Firefox 98. 

Actually, the tests in `type_event_spec.js` also fails on Firefox 98. I'm trying to figure out why.
