### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by nitish-Datman** [cypress-io/cypress#20579]
### Current behavior

Test script getting failed on CircleCi with the error `The Test Runner unexpectedly exited via a exit event with signal SIGSEGV`

  │ Cypress:        9.5.1                                                 │
  │ Browser:        Electron 94 (headless)                  |
  │ Node Version:   v10.22.0 (/usr/local/bin/node)   |
  | Platform:           linux-x64 (Debian - 10.5)          |

### Test code to reproduce

describe("Test", function () {
  it("Log ", function () {
//Test

  });

})

### Cypress Version

 9.5.1

**Comment by michaelstock88** [comment]
So we found a work around

We believe that this is a problem with electron

Switching to chrome as the default runner allowed us to progress

We are using cypress 8.7.0

Hope this can help someone

**Comment by karol-gro** [comment]
Isn't it a duplicate of #18464 ?
