### ISSUE TITLE
No tests found when directory name has `[` or `]` (Component Testing with Next.js)

### ISSUE THREAD

**Issue by e-jigsaw** [cypress-io/cypress#20573]
### Current behavior

Hello, I was set up Cypress Component Testing with Next.js plugin. I encountered `No tests found.` error. 

<img width="848" alt="Screen Shot 2022-03-11 at 12 53 36" src="https://user-images.githubusercontent.com/557961/157798909-bb6dce42-0d51-44dd-b189-31b7dc700263.png">

<img width="886" alt="Screen Shot 2022-03-11 at 12 55 21" src="https://user-images.githubusercontent.com/557961/157799115-a0eb010a-9c66-4cf5-9801-bbd4d9dc4518.png">

I'm writing exactly the same code for these two files. But different behavior. I investigated below

- `some/foo.spec.js` => works
- `some/[thing]/foo.spec.js` => No tests found
- `some/[thing/foo.spec.js` => No tests found
- `some/thing]/foo.spec.js` => No tests found

`[thing]` style is used in Next.js pages directory. Is it possible to fix this issue?
Thanks

### Desired behavior

- `some/foo.spec.js` => works
- `some/[thing]/foo.spec.js` => works
- `some/[thing/foo.spec.js` => works
- `some/thing]/foo.spec.js` => works

### Test code to reproduce

It can reproduce minimum Component Testing with Next.js. Just put `[` or `]` in directory name.

### Cypress Version

9.5.1

**Comment by lmiller1990** [comment]
Hi, thanks for the bug report. This is definitely possible to fix.

**Comment by e-jigsaw** [comment]
I'm glad to hear that!

**Comment by lmiller1990** [comment]
I looked into it. It's only happening with webpack-dev-server, not vite-dev-server. So, this isn't a Next.js specific thing, but just a webpack-dev-server thing. I will continue looking into this.

**Comment by lmiller1990** [comment]
Fixed here https://github.com/cypress-io/cypress/pull/20575. Let's see if this change breaks anything.

**Comment by e-jigsaw** [comment]
yay! blazing fast! thanks a lot

**Comment by e-jigsaw** [comment]
Hi @lmiller1990 ! I confirmed to fix this issue with @cypress/webpack-dev-server@1.8.3. I'm very grateful. Thanks again

**Comment by lmiller1990** [comment]
Nice, thanks for the confirmation!
