### ISSUE TITLE
Cypress unable to detect redirection

### ISSUE THREAD

**Issue by pjuneja760** [cypress-io/cypress#20596]
### Current behavior

Cypress UI remains the same when it should have been redirected to a different page. Redirection works well in the browser both Firefox and Chrome.

### Desired behavior

When clicking a button, the react DOM for a component renders multiple times because setting state multiples time in the click handler function. During last render, component redirects and Cypress should detect redirection and update the page.

### Test code to reproduce
```
cy.visit('myAppUrl');
cy.contains('button', 'someText').click();
cy.url().should('include', 'relativePathToTheRedirectedUrl');
```

## How redirect happens
```
import 'React' from 'react'; // Version 16.14.0
import 'Redirect' from 'react-router'; // Version 5.2.0

class MyComponent {
    render() {
        if (state.redirectionNeedsToHappen) {
            <Redirect push to="myRelativeUrl" />
        }
    }
}
```

### Cypress Version

5.6.0

## Button Click handler
Click a button makes a post request to the backend which takes a while to responds and wait for the job to succeed or fail for quite some while

## Miscellaneous
Behind a corporate proxy

**Comment by joelbentham** [comment]
Hi, is there any updates on this?
