### ISSUE TITLE
clarification with custom npm modules

### ISSUE THREAD

**Issue by country-bumpkin-software** [cypress-io/cypress#20600]
### Current behavior

I have a repo with he following structure:
![image](https://user-images.githubusercontent.com/85832271/158084583-a2909335-ca5f-467c-b404-b81228f74c0e.png)

Im trying to create an npm module of custom commands for various teams to use and download. We are using typescript. The custom commands are in the index.ts file and have this format:

```
const enterUsername = (value: string) => {
    return cy.get('input[name="username"]').type(value)
}

export default  {
    getDataTestId,
    enterUsername
}
```

Questions.

1. do I need to use index.ts and compile to js or do I use index.js directly (my colleague recommended using all typescript since it is a typescript project)
2. When I build the index.ts I get the following issue: 
![image](https://user-images.githubusercontent.com/85832271/158084407-671be907-eca1-43f4-bc9a-156bc1d7c188.png)
How do I workaround that? I mean Cypress appears to be installed and everything.

Ive tried various things:
I renamed the index.ts to custom_commands.ts and changed the functions to look like this:
![image](https://user-images.githubusercontent.com/85832271/158084800-5d607b91-8ac2-405b-b361-7aa8f0da7e46.png)

But I get somewhat similar issues:
![image](https://user-images.githubusercontent.com/85832271/158084814-7897812a-85eb-4a55-8b64-d8889dc3be20.png)

I have also tried declaring the the types as follows:
![image](https://user-images.githubusercontent.com/85832271/158085680-a7d344c1-91f1-4209-9d57-1b3cdbbf3641.png)
But then compiling the code I get the error 
![image](https://user-images.githubusercontent.com/85832271/158085696-7839a66d-b4fb-41aa-bb3c-e4d4fcb46e21.png)

So im kind of getting nowhere with this it seems.

The idea is to build the the index.ts(or custom_commands.ts) file to a distribution folder and then package that up for teams to use.

Your assistance on this issue would be greatly appreciated as it is holding us rolling this out to teams.

### Desired behavior

Be able to package up easily custom commands in typescript as an npm module

### Test code to reproduce

I provided the example above

### Cypress Version

8.1.4

**Comment by country-bumpkin-software** [comment]
Ok I got this all resolved.

In case others are confused by this to publish a typescript npm cypress custom command npm package do the following:
1. create a repo for the custom commands
2. set up the repo with a package.json file and give it a name
3. I set "peerDependencies": "cypress version" and devDependencies to the same cypress version. I also had a key pair in the package.json file for "types":"my src folder"
4. I put all my custom commands in an index.js file and the types in an index.d.ts file and this seemed to work

**Comment by dbarrientostk** [comment]
> Ok I got this all resolved.
> 
> In case others are confused by this to publish a typescript npm cypress custom command npm package I did the following:
> 
> 1. create a repo for the custom commands
> 2. set up the repo with a package.json file and give it a name
> 3. I set "peerDependencies": "cypress version" and devDependencies to the same cypress version. I also had a key pair in the package.json file for "types":"my src folder"
> 4. I put all my custom commands in an index.js file and the types in an index.d.ts file and this seemed to work
> 5. I then created a pipeline that uploaded this to npm
> 
> What was confusing me was if I needed to compile the project with typescript but that seems unnecessary for this. So I avoided using typescript files except for defining types in the index.d.ts

Hey Do you have an example?
I'm trying to achieve something similar.
