### ISSUE TITLE
Cypress giving error in Chrome  and in firefox when i try UI Automation and same scenario working with Selenium Serenity

### ISSUE THREAD

**Issue by shraddhaJaiswal11** [cypress-io/cypress#20609]
### Current behavior

Cypress giving error in Chrome - Uncaught RangeError: Maximum call stack size exceeded and in firefox - Uncaught InternalError: too much recursion. 
Please find attached details of Screenshots

<img width="1437" alt="BugCypressFirefox" src="https://user-images.githubusercontent.com/101589745/158230762-25ed04c6-ca48-4f47-90cd-ec4ca1c6604f.png">
<img width="1305" alt="BugChrome" src="https://user-images.githubusercontent.com/101589745/158230771-8e2b0890-110a-46c9-bfed-7a0e9e316952.png">

### Desired behavior

It should normally allow to login after adding credentials on login page and  click on Submit.

### Test code to reproduce
```js
/// <reference types = "Cypress" />

describe('TestSuite', () =>{
    it("webpage redirect", () => {
        //cy.clearCookies()
        cy.visit("https://xyz.com/documents/home")
        cy.log('Prod URL Launched...')
     });
     it('LoginPageEnterUserPass', function() {
        cy.pause()
         cy.get('#sso_username').should('exist');
         cy.log('SSO Login Page loaded...')
         cy.get('#sso_username').type('xyzl@abc.com')
         cy.get('#ssopassword').type('abc$$$196')
         
     });
     it('LoginPageSubmit', function() {
         // cy.pause()
         cy.get('#signin_button').click();
     });
})
```

### Cypress Version

9.5.1

### Other

Just replaced original product URL with xyz for security issues. Hope for a quick help. Thanks

**Comment by CaiqueCoelho** [comment]
I think you can try using the code below at the top of your describe block:

```
Cypress.on('uncaught:exception', (err, runnable) => {
    return false;
});
```
