### ISSUE TITLE
Current 'it()' block that executing from console differs from what Cypress UI shows

### ISSUE THREAD

**Issue by mgmpskywalker07** [cypress-io/cypress#20613]
### Current behavior

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/54514617/158268800-230348eb-b606-48fe-b614-dc2dd8dc82d5.png">

Hello. I hope this is just some fluk on my part but this is a pretty serious issue. As you can see in the screenshot, when I run a cypress test from the command line, from some reason the console logs stop at 'Step 5' even though the Cypress UI clearly shows the test proceeding to 'Step 6' (you can think of steps as new 'it()' blocks). When I run my test in a CI/CD tool, the console logs also reflect the test stopping at 'Step 5' even though the test has proceeded much further. I have never seen this behavior before and it does not seem to happen with each test. Does anyone know why the logs might all of a sudden stop in the console?

### Desired behavior

The console logs should match the current point of execution in the Cypress UI.

### Test code to reproduce

No code I am hoping to get general advice

### Cypress Version

9.5.2

**Comment by emilyrohrbough** [comment]
@mgmpskywalker07 Can you please provide additional information? I agree this behavior appears odd, but we cannot provide guidance or advise without understanding more about the structure of your project setup/test structure. Can you provide a minimal, reproducible example?

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
