### ISSUE TITLE
SSL Handshack error with `--record` on CircleCI

### ISSUE THREAD

**Issue by iam4x** [cypress-io/cypress#2062]
Hi 👋 

First, thank you for this wonderful tooling <3
I'm having one last issue for setting it up correctly, I'm not sure what is wrong there.

```
$ /home/circleci/repo/packages/e2e/node_modules/.bin/cypress run --record --key XXXX

It looks like this is your first time using Cypress: 3.0.1

[22:20:06]  Verifying Cypress can run /home/circleci/.cache/Cypress/3.0.1/Cypress [started]
[22:20:08]  Verifying Cypress can run /home/circleci/.cache/Cypress/3.0.1/Cypress [completed]

Opening Cypress...
Warning: We encountered an error talking to our servers.

This run will not be recorded.

This error will not alter the exit code.

RequestError: Error: write EPROTO 140555546335744:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:772:
```

I'm running cypress.io on Nodejs v9.11.2

**Comment by brian-mann** [comment]
Appears to be a bug in node. Strange that you're getting this in Circle and we've not had any reports from anyone else. 

https://github.com/nodejs/node/issues/16196

Perhaps you're using a docker image that has problems... can you give any more information? Is this happening every time?

The node version you're running does not affect Cypress - it runs with its own built in node version. The node version you're on only affects downloading and installing the CLI + Binary.

**Comment by iam4x** [comment]
Thanks for the informations, it has happened a few times, the image I use is a custom one:

Dockerfile
```
FROM circleci/node:9.11.2

# cypress.io dependencies
RUN sudo apt-get update
RUN sudo apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

# imagemin-mozjpeg fix (dependency of next-optimized-images)
# https://github.com/imagemin/imagemin-mozjpeg/issues/26#issuecomment-369269277
RUN sudo apt-get update
RUN sudo apt-get install -y nasm

RUN yarn global add @adonisjs/cli

# we need pg_restore
RUN sudo apt-get install -y postgresql-client-9.4
```

I will post more informations if I have anything 👍
