### ISSUE TITLE
Please join to us #standwithukraine

### ISSUE THREAD

**Issue by id-dan** [cypress-io/cypress#20641]
### What would you like?

Please support Ukraine, more infos here: https://github.com/vshymanskyy/StandWithUkraine

**Comment by id-dan** [comment]
@jennifer-shehane pay attention, please and support us.

**Comment by id-dan** [comment]
@bahmutov pls, have a look. Maybe you can inform them about it

**Comment by jennifer-shehane** [comment]
Hey @id-dan, as a person who had myself and my family personally displaced by conflict and that has family living in a country in conflict, I feel deeply for those affected around the word. It is constantly on my mind and is something that I invest my personal time in helping to bring awareness to. Cypress has empathy for so many of the tragedies occurring in the world, but we will not take part in posting the Readme Banner suggested within our product.

**Comment by id-dan** [comment]
@jennifer-shehane pls have a look how others projects support us
https://github.com/cucumber/cucumber-js/issues/1961#issuecomment-1084666364

**Comment by id-dan** [comment]
> Cypress has empathy for so many of the tragedies occurring in the world, but we will not take part in posting the Readme Banner suggested within our product.

Could you please explain why you do not want to add banner?
