### ISSUE TITLE
Unable to pass basic authentication credentials with cy.visit as of 9.5.1

### ISSUE THREAD

**Issue by dpiersonR0ckporT** [cypress-io/cypress#20649]
### Current behavior

As of 9.5.1 my configuration to access a website generates a  401: Unauthorized.

I have an environment config file located in cypress/config directory with this value 
```json
{
	"env": {
		"mainUrl": "https://user:password@staging.testsite.com/",	
	}
}
```
the site has basic authentication and I pass the credentials in the url. This stopped working as of 9.5.1.
Adding the credentials in the script as part of cy.visit fails as well. 

### Desired behavior

restore the ability to pass basic auth creds 

### Test code to reproduce
```json
 {
	"env": {
		"mainUrl": "https://user:password@staging.testsite.com/",
	}
}
```
```js
before(function () {
		cy.visit(Cypress.env('mainUrl'))
}
```
### Cypress Version

9.5.1 & 9.5.2

**Comment by sainthkh** [comment]
Sorry for the late reply. 

This feature has been added at #573 with [this test](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/integration/issues/573_spec.js).

And this test passes in `9.5.1` and `9.5.2`. 

We need a reproducible code example for this failure.

**Comment by dpiersonR0ckporT** [comment]
we work on macos so this makes sense, its blocking our ability to keep up
with new releases and fixes.

**Comment by netroy** [comment]
@dpiersonR0ckporT I deleted the comment because in our case it was something else. The credentials were not getting picked up correctly. 
I don't know if that's the same issue on your end or not, but this works for me on both linux and macos now.

**Comment by dpiersonR0ckporT** [comment]
Perhaps its our configuration design?
 
The suite has unique environment config files located in /cypress/config/env.json 
in each environment config file we have various urls and db connection details 
"env": {
		"mainUrl": "https://user:password@staging.testsite.com/",
		"registerUrl": "https://user:password@staging.testsite.com//register",
		"portal": "https://user:password@staging.testsite.com//minor-consent/portal/",
		"envTag": "staging",

		"db": {
			"user": "user",
			"host": "host",
			"database": "db",
			"password": "encrypted password",
			"port": 22222,
			"ssl": "true"
		}
	}

in package.json we have various prebuilt command lines where the required config file is passed
cypress open --env configFile=staging

**Comment by dpiersonR0ckporT** [comment]
I was able to alter my suites by creating a custom command and pass basic auth credentials with this pattern
cy.visit(url, {
				auth: {
					username: 'authusername',
					password: 'pwdstring',
				},
			})

upgraded and confirmed I am unblocked. 
still unable to use this pattern 
 "https://user:password@staging.testsite.com/",
