### ISSUE TITLE
Paid Version - Cypress Dashboard Runs times when run from Jenkins for big spec files

### ISSUE THREAD

**Issue by zlareb1-yb** [cypress-io/cypress#20660]
### Current behavior

Hi, 
I am running Cypress Tests from Jenkins. We have integrated Cypress Dashboard and results gets pushed to Cypress Dashboard. It used to work correctly.

Now as our spec file became bigger we are observing Jenkins Job is successful and triggered all the tests but Cypress gives error like:
```
Incomplete
The run started, but never completed. This can happen when the run is canceled from CI or when Cypress crashes during running tests.

Check your CI logs for more information. Archive this run to remove it from the runs list and analytics.

2 of 4 specs skipped
```

I can see all the tests got executed on Jenkins console logs but that has not been updated on Cypress Dashboard

### Desired behavior

Cypress Dashboard should reflect all the specs and not time out

### Test code to reproduce

Big test spec file where test time is more than 2 hours. 

Note - we are not in position to reduce our spec file size

### Cypress Version

9.5.1

**Comment by jennifer-shehane** [comment]
Cypress automatically times out the run if we don't hear a signal back after 90 minutes. A specfile running longer than 2 hours is not recommended in Cypress and will always cause this timeout behavior with how it works today. I'd suggest splitting up your specs into smaller files.
