### ISSUE TITLE
cy.type with {delay:0} is not working as expected when using the library react-select-async-paginate

### ISSUE THREAD

**Issue by IvoLeist** [cypress-io/cypress#20668]
### Current behavior

I experienced an odd behavior when using cy.type with search boxes (connected directly to an API)
in normal text fields Cypress is basically copy pasting when using {delay: 0} however when wanting to type in
the item_id "1234" in a filterable selection box (provided by: react-select-async-paginate*) below is happening
*https://github.com/vtaits/react-select-async-paginate

data_query :>> {item_id: ''}
data_query :>> {Item_id: '1'}
data_query :>> {item_id: '12'}
data_query :>> {item_id: '123'}
data_query :>> {item_id: '1234'}

each line is a console.log of the fetch function to our API

### Desired behavior

expected would be to have only one query to our API 
when using cy.type("1234",{delay:0})
> data_query :>> {item_id: '1234'}

### Test code to reproduce

I have not yet figured out how to set up a reproducible example
Are there some python flask/react/cypress boiler plates which I could use?

Or maybe it is already enough to run cypress against a code sandbox
https://codesandbox.io/s/o75rno2w65
https://codesandbox.io/s/5y2xq39v5k?file=/src/App.jsx
If this is possible, do you have an example for it?

### Cypress Version

9.5.2

### Other

This is an extension of the following issue:https://github.com/cypress-io/cypress/issues/20570

**Comment by emilyrohrbough** [comment]
@IvoLeist In the example you provided, when I manually enter text slowly, you can see the loading state & results display. I think this is the behavior of the component you are leveraging.

**Comment by emilyrohrbough** [comment]
@IvoLeist adding `{ delay: 0 }` does not change the `.type()` behavior to act as a `paste` behavior. It will add each char in the string one by one as if your were typing it but without a delay between entering characters. I'd recommend using `invoke()` to mimic `paste` behavior. Here is an example: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__clipboard/cypress/integration/spec.js#L43

**Comment by IvoLeist** [comment]
ah ok in that case I understood it wrong, I thought 0ms delay is equivalent to pasting it....
*maybe a note in your documentation would be helpful (?)

Thanks for providing me the example, I will try it out tomorrow :)

**Comment by IvoLeist** [comment]
in case someone stumbles about a similar issue invoke was not working but in the end
I resolved it using the following custom command.
```
Cypress.Commands.add("inputChange", (input, value) => {
  // taken from https://stackoverflow.com/a/69552958/11217233
  const nativeInputValueSetter = Object.getOwnPropertyDescriptor(
    window.HTMLInputElement.prototype,
    "value"
  ).set;

  const changeInputValue = (inputToChange) => (newValue) => {
    nativeInputValueSetter.call(inputToChange[0], newValue);
    inputToChange[0].dispatchEvent(
      new Event("input", {
        newValue,
        bubbles: true,
        composed: true,
      })
    );
  };
  return cy.get(input).then((input) => {
    changeInputValue(input)(value);
  });
});
```
and in Cypress it works as follows:

```
cy.intercept("POST", `${Cypress.env("apiUrl")}/items/list`).as("itemsList");
cy.get("#react-select-2-input")
      .then((input) => {
        cy.inputChange(input,datasetId)
        cy.wait("@itemsList").then((res) => {
          expect(res.response.body.length).to.eq(1);
          expect(res.response.body[0]).to.eq(String(datasetId));
        })
    })
```
@emilyrohrbough feel free to close the issue

**Comment by emilyrohrbough** [comment]
@IvoLeist Glad you were able to get this to work.
