### ISSUE TITLE
 Security Vulnerabilities

### ISSUE THREAD

**Issue by vw98075** [cypress-io/cypress#20669]
### Current behavior

We use JHipster for our application project. And JHipster uses Cypress. A security code scan of Fortify reports some command injection and cross-site scripting in Cypress.

### Desired behavior

The followings are issues in the critical category.

Command injection:

Executing commands that include unvalidated user input can cause an application to execute malicious commands on behalf of an attacker.

Line start 171 in xvfb/index.js 
Line start 102 in lib/tasks/unzip.js (not sure whether this one is from an outside library or not)
Line start 139 in lib/tasks/unzip.js   
Line start 146 in lib/tasks/verify.js  

Insecure transport:

The call uses an unencrypted protocol instead of an encrypted protocol to communicate with the server. 

225 lib/tasks/download.js
61 request/index.js

### Test code to reproduce

An attacker may indirectly control commands executed by a program by modifying the environment in which they are executed. he environment should not be trusted and precautions should be taken to prevent an attacker from using some manipulation of  the environment to perform an attack. Whenever possible, commands should be controlled by the application and executed using an absolute path. In cases where the path is not known at compile time, such as for cross-platform applications, an absolute path should be constructed from trusted values during execution. Command values and paths read from configuration files or the environment should be sanitychecked against a set of invariants that define valid values. Other checks can sometimes be performed to detect if these sources may have been tampered with. For example, if a configuration file is worldwritable, the Program might refuse to run. In cases where information about the binary to be executed is known in advance, the program may
perform checks to verify the identity of the binary. If a binary should always be owned by a particular user or have a particular set of access permissions assigned to it, these properties can be verified programmatically before the binary is executed. In the end it may be impossible for a program to fully protect itself from an imaginative attacker bent on controlling the commands the program executes. You should strive to identify and protect against every conceivable manipulation of input values and the
environment. The goal should be to shut down as many attack vectors as possible.

Use secure protocols such as HTTPS to exchange data with the server whenever possible. 

### Cypress Version

9.3.1

**Comment by vw98075** [comment]
@emilyrohrbough Thanks very much for your quick response. I agree with you on the security assessment. I will pass your response over.

**Comment by AkechiShiro** [comment]
Any news on this ? Are these minor "vulnerabilities" still reproducible ?

**Comment by vw98075** [comment]
You can close this ticket. We agree with Emily's comment and won't view that as are vulnerabilities.

**Comment by AkechiShiro** [comment]
Alright, then you, @vw98075 should close the ticket. 
Only the one who opened this issue or a maintainer of the project can close this issue.
I can't as I'm neither of these at the moment.
