### ISSUE TITLE
Disconnection when attempting ajax request.

### ISSUE THREAD

**Issue by FilipDziarmaga** [cypress-io/cypress#20673]
### Current behavior

I am quite new to automated testing (up until recently I'v been a manual tester) and I've recently taken up Cypress.

I've been trying to select an item from a drop down list. After selecting one item the next drop-down list should occur under. A 'POST' request should be made.

When a test case is runned in Cypress after selecting an item from the first drop-down list I am getting an alert in my native language about a temporary lack of internet connection  ("Brak połączenia z siecią. Prosimy spróbować za chwilę. Przepraszamy za chwilę") and no 'POST' request is being made and no HTML body as the response is being received.

![chrome_GNKJOpoiZC](https://user-images.githubusercontent.com/91876275/158894662-36661c9b-e0a2-453c-958e-b7fade311c12.gif)

### Desired behavior

This is how a browser behaves when the test case is executed manually:

![chrome_e1kUE5mX3G](https://user-images.githubusercontent.com/91876275/158896235-f23169fc-6b06-4ce8-b4ec-5a613b400a32.gif)

There is a 'POST' request and a HTML body as a response. Notice the second drop-down list occuring.

### Test code to reproduce

Below I provide a code snippet:

```js
describe("Selecting an item from a drop-down list", () => {

  it("Selecting", () => {
    cy.visit("www.sprzedajemy.pl");
    var id = String(2);
const routeMatcher ={

  method: 'POST',
  url: '**/tmp_id/*?category_id=id_2',
  path: '**/tmp_id/*?category_id=id_2',
  pathname: '**/tmp_id/*',
  query: {
       category_id: 'id_2'
     },
  times:1
};
    cy.get(".theButton.theButtonRed.theButtonAdd").click({ force: true });
   cy.intercept(routeMatcher).as('authenticate')
    cy.pause();
    cy.get("#category_selector_5>:nth-child(" + id + ")").then(function ( $elem) {
      cy.log($elem.text());
      cy.wait(5000)
      cy.get("#category_selector_5").select($elem.text(),{ force: true });
       cy.wait('@authenticate').its('response.statusCode').should('eq', 200)
    }); });
});
```

### Cypress Version

8.7.0

**Comment by emilyrohrbough** [comment]
@FilipDziarmaga I was able to successfully run the example you provided. Watching the video attached in the issue, it seems like additional steps to log in are performed before the code-snippet you shared with me. Could the issue be that the authentication request is not going through because the login has already occurred?
