### ISSUE TITLE
When a test get failed in the "after each" Cypress is aborting the execution for all subsequent it's. - How to avoid that?

### ISSUE THREAD

**Issue by zwingliernst** [cypress-io/cypress#20682]
How to ensure, that when a test fails in the afterEach-hook, that subsequent tests get executed?

We have a series of regular generic checks, such as console, screen-size, visibility of header-bar, etc, that we basically put in the afterEach-hook, as they literally shall be checked after every test.

However, as soon as it fails in one test, all subsequent tests are aborted.
This is really annoying as it basically impedes generic checks.

**How to stop Cypress from aborting the test run, when an afterEach fails?**
*(the assumption, that any subsequent it would fail, because it's in the afterEach-hook is simply wrong).*

*Taken from Issue 518, but facing the same problem*:
Hi there guys, I'm facing the opposite here. I don't have a afterEach function but after update from 6.8.0 to 8.1.0 when a test get failed the "after each" and "after all" hooks are aborting the execution on first failure.

I don't wanna to abort on first failure I'd rather execute all tests then in the end of execution see the reports. I'm don't finding the configuration or code for that default after each and after all hooks.

How can I handle it? In 6.8.0 version I was able to do it by default...

_Originally posted by @szanelato in https://github.com/cypress-io/cypress/issues/518#issuecomment-892723241_

**Comment by zwingliernst** [comment]
This is some example code for reproducing it:
```
describe("afterEach shall fail only current it and continue", function(){
  afterEach(() => {
    if (this.failIt) throw new Error("this it fails")
  })

  it("shall not fail", ()=> {
    cy.log("everything fine. I'll pass!")
    this.failIt = false
  });
  it("shall fail this it only", ()=> {
    cy.log("there is an console-error in my test")
    this.failIt = true
  });
  it("shall be tested and not fail", ()=> {
    cy.log("there is everything alright, but do I even get tested?")
    this.failIt = false
  });
});
```

**Comment by sainthkh** [comment]
Sorry for the late reply. 

First of all, Cypress uses Mocha and the current behavior came from it (ignoring tests after it). [Please check this pen](https://codepen.io/sainthkh/pen/RwxVgXK).

And it's not a wrong behavior because the purpose of `after` and `afterEach` is [cleaning up for the next test](https://mochajs.org/#hooks). 

```
These should be used to set up preconditions and clean up after your tests.
```

Failures in those functions mean "cleaning up aren't done correctly. So, we cannot start the new test in the clean state." That's why it doesn't run the tests. 
hould be used to set up preconditions and clean up after your tests.
```

Failures in those functions mean "cleaning up aren't done correctly. So, we cannot start the new test in the clean state." That's why it doesn't run the tests. 

One way to solve the problem is to define a function that contains assertions and put it inside `it` functions.

**Comment by zwingliernst** [comment]
So in this case I'm likely looking for a new functionality such as `withinEach()`.
I understand the line of reasoning, though I disagree with it. However, Mocha seems to blame here.
The issue is, we want those checks to apply for hundreds of it's (basically all of them) and applied it therefore via `support/index.js`.
Now I was additionally looking into Cypress Events, but couldn't find any event, that runs after each it, but before the afterEach() hook.
In general it seems a bit verbose, to have a `withinEach()`, that literally just runs before the `beforeEach()`, but given the reasoning, this seems to be the only way forward.

What event could I bind on, to achieve this `withinEach()`-effect?
Or would I need to stub the beforeEach()-hook to achieve that? And how would I do that?

Thank you in advance

**Comment by sainthkh** [comment]
I can give you only general answers because I don't know how your tests are going on. 

I guess there are various ways of setting up tests while assertions are same for them. 

In that case, tests can be written like below:

```js
const setups = [
  () => { /* setup for test 0 */ },
  () => { /* setup for test 1 */ },
]

function assertions() {
  // assertions
}

function cleanup() {
  // clean up code
}

setups.forEach((setup, i) => {
  it(`test ${i}`, () => {
    setup()
    assertions()
    cleanup()
  })
})
```

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by T-e-j-k-u-m-a-r** [comment]
Hi @sainthkh : Exactly the way you explained, I'm executing the cypres tests from jenkins and observed that when this a folder called login which will have 3 files inside it: Something like: (spec1.ts, spec2.ts & spec3.ts) inside a folder lets say: Login,
If the spec1.ts failed then it will not pick the very next test case. Instead it will go for next folder which is in my case HomePage.

Why is that?
