### ISSUE TITLE
Adding null as an encoding argument to cy.readFile command results in TypeError

### ISSUE THREAD

**Issue by Zaista** [cypress-io/cypress#20683]
### Current behavior

Adding null as an encoding argument to `cy.readFile` command results in `TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object`.

It seems that `null` option somehow bypasses the timeout and waiting for file to be downloaded, because as soon as I add 1 sec wait, the command works as expected, and file is read.

### Desired behavior

`cy.readFile` command (with null as encoding argument) should fall back to default timeout of 4 seconds and retry until file is found.

### Test code to reproduce

... trigger a download of a file
```js
cy.readFile(pathToFile, null);
```

### Cypress Version

9.5.1

**Comment by emilyrohrbough** [comment]
@Zaista Thank you for reporting this issues. I was able to reproduce this with this simple example:

```js
it('test', () => {
  cy.readFile('./cypress/fixtures/non-existent-file.json', null)
})
```

Looking in the code, this appears to be a relatively straight forward fix.
