### ISSUE TITLE
Intercept i is not showing the latest respnose if Intercept same call multiple times

### ISSUE THREAD

**Issue by varshanharshank** [cypress-io/cypress#20697]
### Current behavior

During end to end testing, I am intercepting the same api call many places (each place, it will provide different response). When i use cy.wait() command to retrieve the response, it is always showing the old response (it means, it is showing response which intercepted first time)

```js
    cy.intercept('**customerInfo/inventory/review/*').as('reviewInvetory')
    cy.wait('@reviewInvetory').then((res) => {
      cy.log(JSON.stringify(res.response?.body))
    }) //printing reviewInvetory1 response
    //doing some action in the application, then again intercepting the same call
    cy.intercept('**customerInfo/inventory/review/*').as('reviewInvetory')
    cy.wait('@reviewInvetory').then((res) => {
      cy.log(JSON.stringify(res.response?.body))
    }) //printing the first call data instead of printing the latest intercept call
```
### Desired behavior

Expecting to show latest call instead of showing the old call

### Test code to reproduce

I can't share my repo to public

### Cypress Version

9.4

**Comment by emilyrohrbough** [comment]
@varshanharshank Can you provide a reproducible example using https://github.com/cypress-io/cypress-test-tiny since you are unable to share you're repo? I tired to reproduce the issue and was unable to. Here is the test I used:

```js
it('test intercept response that is used when called multiple times', () => {
  cy.intercept('https://jsonplaceholder.cypress.io/*', {
    statusCode: 200,
    headers: {
      'content-type': 'text/html',
    },
    body: 'response1'
  }).as('request')

  cy.visit('https://jsonplaceholder.cypress.io/comments')

  cy.wait('@request').then(({ response }) => {
    expect('response1').to.eq(response.body)
  })

  cy.intercept('https://jsonplaceholder.cypress.io/*', {
    statusCode: 200,
    headers: {
      'content-type': 'text/html',
    },
    body: 'response2'
  }).as('request')

  cy.visit('https://jsonplaceholder.cypress.io/comments')

  cy.wait('@request').then(({ response }) => {
    expect('response2').to.eq(response.body)
  })
})
```

**Comment by restrin-extensis** [comment]
I ran into the same issue (I'm on 9.7.) I discovered using server().route() rather than intercept() worked around the problem.

**Comment by Deop** [comment]
I've been having this issue ever since switching to using cy.intercept instead of cy.route. It's a bit hard to find reproducible example without giving access my project. But issue is usually happen when you stay on the same page and do the same request (for example do search with the same text twice). It usually just match wait for to the first route it already matched and give you response of that first route.
