### ISSUE TITLE
Proposal: Add package-lock.json

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2070]
It's probably time to do this and add it to every package.	

/cc @cypress-io/developers

**Comment by jennifer-shehane** [comment]
via @brian-mann 

>We are going to move to yarn to facilitate this. It's not worth the effort IMO to introduce package-lock and stay on npm. I would rather us spend the effort to convert to yarn since there are far more upsides and benefits beyond just this.

https://github.com/cypress-io/cypress/pull/4711#issuecomment-512889613
