### ISSUE TITLE
Testing web extension fails on headless mode (for CI)

### ISSUE THREAD

**Issue by goldylucks** [cypress-io/cypress#20705]
### Current behavior

I have a simple test the passes on `cypress open`, but fails with `cypress run`

what I'm trying to achieve is running the tests in a CI.

is that even possible on cypress?

### Desired behavior

should work like on `cypress open`

### Test code to reproduce

https://github.com/goldylucks/cypress-test-tiny

### Cypress Version

9.5.2

**Comment by emilyrohrbough** [comment]
@goldylucks Could you provide additional details on what you are trying to achieve and the behavior you are experiencing?

**Comment by goldylucks** [comment]
I'm trying to test a web extension E2E.
the simplest of tests, inject an element to the dom and assert it's there

**Comment by equinix-sulai** [comment]
@emilyrohrbough  Can cypress chrome load / inject an extension in headless mode? I know in the headed mode it can.

**Comment by goldylucks** [comment]
@emilyrohrbough , this works, thanks!!
```
$ npx cypress run --browser chrome --headed
```

FYI, this doesn't work
<img width="659" alt="image" src="https://user-images.githubusercontent.com/6963212/160593955-f06f4d76-e1c4-4a46-a5ec-1cd04d9f2f56.png">

**Comment by dvirtz** [comment]
cypress doesn't pass the `--load-extension` flag to chrome when it runs in headless mode
https://github.com/cypress-io/cypress/blob/ffcc6387ef44aeb5f84556574680a86bbca73df4/packages/server/lib/browsers/chrome.ts#L138-L141

This can be worked around by passing the `--load-extension` flag directly
```
on('before:browser:launch', (browser, launchOptions) => {
  if (browser.family === 'chromium') {
    launchOptions.args.push(
      `--load-extension=${extensionPath)}`
    );
  }
});
```

I believe this is left over from before the `--headless=new` switch was added which enabled extensions in headless mode.
