### ISSUE TITLE
The Cypress App could not be installed after setting up HTTP_PROXY

### ISSUE THREAD

**Issue by shagupta92042** [cypress-io/cypress#20714]
I was getting below error while installing cypress

**Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration**

So I did setup http proxy using set HTTP_PROXY=http://my-company-proxy.com/ and ran below steps

**1.
C:\Users\shashank.gupta>npm install cypress --save-dev**

added 165 packages, and audited 166 packages in 27s

27 packages are looking for funding
run npm fund for details

found 0 vulnerabilities

**2.
C:\Users\shashank.gupta>npx cypress -v**
Cypress package version: 9.5.2
Cypress binary version: not installed
Electron version: not found
Bundled Node version: not found

**3.
C:\Users\shashank.gupta>npx cypress run**
No version of Cypress is installed in: C:\Users\shashank.gupta\AppData\Local\Cypress\Cache\9.5.2\Cypress

Please reinstall Cypress by running: cypress install

Cypress executable not found at: C:\Users\shashank.gupta\AppData\Local\Cypress\Cache\9.5.2\Cypress\Cypress.exe

Platform: win32-x64 (10.0.19042)
Cypress Version: 9.5.2

Now the below step stuck for hours and it is not able to install the cypress on my system.

**4.
C:\Users\shashank.gupta>npx cypress install**
Installing Cypress (version: 9.5.2)

**5.
C:\Users\shashank.gupta>npm list cypress**
shashank.gupta@ C:\Users\shashank.gupta
`-- cypress@9.5.2

**Comment by vaffen** [comment]
I have the same exact issue. Have you resolved it yet?
