### ISSUE TITLE
element covered by an other

### ISSUE THREAD

**Issue by zohrasaida** [cypress-io/cypress#20731]
### Current behavior

i am writing a script to execute the mapping of the react flowchart, the problem is that the elements are dragged into the grid on each other so some elements are covered by some others.
how can i solve this issue?
ps : i used the position using X,Y in the dropping but nothing changed

### Test code to reproduce

   it('mapping nodes', () => {
        const dataTransfer = new DataTransfer();

        cy.get(".react-flow__handle.react-flow__handle-bottom.nodrag.source.connectable[data-nodeid='test1_1']")
        .trigger('mousedown', {which: 1})
        .trigger('dragstart', { dataTransfer });
        

        cy.get(".react-flow__handle.react-flow__handle-top.nodrag.target.connectable[data-handleid='right']")
        .trigger('drop', { dataTransfer })
        .trigger('mouseup', {});
    });
![verify drag and drop react flow -- mapping nodes (failed)](https://user-images.githubusercontent.com/60110185/159506817-7a445fe0-fc0d-4a85-a334-1cfc6e37a7bb.png)

### Cypress Version

9.5.2

**Comment by emilyrohrbough** [comment]
@zohrasaida Thanks for opening an issue. I don't quite understand the issue you are experience. Are you able to provide a reproducible example and the error you are encountering?

**Comment by zohrasaida** [comment]
> @zohrasaida Thanks for opening an issue. I don't quite understand the issue you are experiencing. Are you able to provide a reproducible example and the error you are encountering?

so I am automating the react flow action, I started by automating the drag and drop and it works correctly, the problem is when I tried to map the nodes, it can't work because the first element is covered by the second as it is in the screenshot above .
i tried to solve this issue using specific coordinations where to drop each element but still the same problem and it does not work.

**Comment by zohrasaida** [comment]
Hello we can fix a meeting to show you how to deal with it or can you send
me your code so i can check

**Comment by madhuriaarth** [comment]
it("search source input and drag and drop the souce input",() => {
        const dataTransfer = new DataTransfer()
        cy.get('[data-test-id="ruleEditor-sidebar-draggable-operator-sourcePathInput"]').trigger("dragstart", { dataTransfer} );
        cy.get('#ruleEditor-react-flow-canvas').trigger("drop", { dataTransfer })
        cy.get('#ruleEditor-react-flow-canvas').trigger("dragend", { dataTransfer}).click(100,100,{ force: true });
    }) ***This is for drag and drop but i don't how to give the position in canvas***

***This is for how link between the nodes in canvas and using same drag and drop to linking the nodes***
it("connect the links",() => {
        const dataTransfer = new DataTransfer()
        cy.get('[data-nodeid="sourcePathInput"]').click({force:true})
        .trigger("dragstart", { dataTransfer, force: true} )
        cy.get('[data-handleid="0"]').trigger("drop", { dataTransfer,force: true} )
      cy.get('[data-handleid="0"]').trigger("dragend", { dataTransfer, force: true });
     });

**Comment by puranjayjain** [comment]
I'm facing a similar issue on click but with angular material and modals

**Comment by madhuriaarth** [comment]
I think facing with material icons need to add like this button.mat-icon.
