### ISSUE TITLE
Add environment variable CYPRESS_FORCE_INSTALL to do the same thing as cypress install --force

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2074]
Useful in CI so that you can force installs of cypress when you have a `CYPRESS_BINARY_VERSION` set but that specific version number is already cached.

In those cases I want to force it to be installed no matter what. Currently I have to change the CI scripts and add `cypress install --force`.

Having `CYPRESS_FORCE_INSTALL=1` would act as if the `--force` flag is always set during `npm install` and `cypress install`.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
