### ISSUE TITLE
Amazon RDS DB connectivity

### ISSUE THREAD

**Issue by Ranjith241096** [cypress-io/cypress#20749]
### What would you like?

couldn't find the configuration details for connecting Amazon RDS DB Connectivity.

### Why is this needed?

Needed this configuration to connect DB.

**Comment by emilyrohrbough** [comment]
@Ranjith241096 Please reference the AWS documentation. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_CommonTasks.Connect.html
