### ISSUE TITLE
Cypress is trying to load ALL js outside of `cypress` folder

### ISSUE THREAD

**Issue by mikeerickson** [cypress-io/cypress#20740]
### Current behavior

The project we use to perform all of our cypress tests also contains code to run our custom CLI code.

When running `npx cypress open -C config/cypress.dev.json` after selecting the desired spec to run, we receive the following error, which occurs because it is somehow process all js/ts outside of thte `cypress` directory

In this case, we have a file located at `./src/cli.js` which has a something like that ultimately causes the error

```
const { CLI } = require('@codedungeon/gunner');
```

```
Webpack Compilation Error
./node_modules/@codedungeon/gunner/src/gunner.js 41:15
Module parse failed: Unexpected token (41:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

Here is what appears in the Cypress Test Runner

![CleanShot 2022-03-22 at 13 20 07](https://user-images.githubusercontent.com/183153/159568834-f6dd6b41-6186-4efd-865e-2a57ec30f22c.png)

And this appears on left side

![CleanShot 2022-03-22 at 13 22 43](https://user-images.githubusercontent.com/183153/159569281-aaa703ac-72d7-40b1-8ae0-05987da22c7a.png)

### Desired behavior

I would expect the spec to not attempt to access code outside the `cypress` folder (see screenshot with directory structure)

![CleanShot 2022-03-22 at 13 16 56](https://user-images.githubusercontent.com/183153/159568342-b95fe133-82c5-433e-a932-c587d61751b8.png)

### Test code to reproduce

issue occurs with any spec we attempt to execute

### Cypress Version

9.5

**Comment by urmzd** [comment]
Having a similar problem, was this happening with earlier versions of the library?
