### ISSUE TITLE
Using cypress json schema for tooltips on configuration settings in Desktop Gui

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2075]
Would be nice as I hover over each property that we show a tooltip with the `description` and even the `default` value.

The schema file is here: https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json

![screen shot 2018-06-30 at 8 58 21 pm](https://user-images.githubusercontent.com/1268976/42130128-570bdaf4-7ca8-11e8-816b-7b883756b8e2.png)

**Comment by bahmutov** [comment]
Ohhh that’s such a nice idea.

**Comment by nhc** [comment]
I will have a go at this one.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
