### ISSUE TITLE
Modify the contents of a fixture inside cy.intercept

### ISSUE THREAD

**Issue by TenPotatoes** [cypress-io/cypress#20761]
### What would you like?

I'd like to be able to modify a fixture's contents inside cy.intercept. Or, modify the response of all cy.intercept calls.

```
cy.intercept(
    {
        method: 'POST',
        url: '/graphV2',
    },
    (req) => {
        const operationName = req.body.operationName;
        const fixtureName = operationNameToFixtureMap[operationName];
        if (fixtureName) {
            // I would like to load the fixture here and change the logged in username: replace "user1" with "user2"
            req.reply({ fixture: fixtureName });
        }
    }
);
```

Similar question:

https://stackoverflow.com/questions/66705779/how-to-can-i-load-cypress-fixture-inside-intercept-based-on-request-data

### Why is this needed?

I'm writing UI only tests that fully mock APIs. Different users have different permissions. I'd like to be able to reuse my fixtures for different users, so I need to modify the usernames inside the fixture contents for different tests.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest, we’ll close this as not planned.
