### ISSUE TITLE
Application does not behave as expected in cypress runner. Same works on browser when manually done (outside of cypress). 

### ISSUE THREAD

**Issue by mkathu** [cypress-io/cypress#20766]
### Current behavior

I am trying to work with cypress on url : https://www.clearhaircare.com/arabia/en/products/type/Shampoo.html

once the page is loaded i am trying to interact with drop down. Based on the values selected in the dropdown the results are displayed.

This works as expected when tried manually on chrome browser. But in cypress it does not show any result on selecting the values in the dropdown.

**_manually:_**
![image](https://user-images.githubusercontent.com/7846128/159864342-0dbe930e-1e56-4ad2-b4be-2ea98f63c5f5.png)
![image](https://user-images.githubusercontent.com/7846128/159864613-c934baaa-258b-48e8-8793-37eb2dd72e0e.png)

**_Cypress runner:_**
![image](https://user-images.githubusercontent.com/7846128/159864395-ac8e2a63-21cd-45c2-a0d2-443810d87c20.png)
![image](https://user-images.githubusercontent.com/7846128/159864439-6804cd90-3d87-4145-bca0-e559ef5a03e3.png)
![image](https://user-images.githubusercontent.com/7846128/159864547-5c3cb350-082a-424f-aa8a-14dc77492259.png)

### Desired behavior

Ideally the script should perform the following:

1. Open page
2. Interact with filters defined in fixtures
3. Once the results are filtered, capture the screenshot and push percy

Note: There is no failure in the script. Its just that the results are not updated on the page on applying filters in cypress runner. The same works fine when done manually outside cypress runner.

### Test code to reproduce

Fixture:
```json
{
    "site": "clearhaircare_ar_en",
    "requestintercept": "**/sprites/cross-search-overlay.svg",
    "url": "https://www.clearhaircare.com/arabia/en/products/type/Shampoo.html",
    "cookielocator": "onetrust-accept-btn-handler",
    "filters":[
        {
            "locator":"*[name='listing-filter-0']",
            "value":"clear^product^type^shampoo",
            "url": "shampoo"
        },
        {
            "locator":"*[name='listing-filter-1']",
            "value":"clear^product^needs^damaged",
            "url": "damaged"
        },
        {
            "locator":"*[name='listing-filter-2']",
            "value":"clear^product^collection^men",
            "url": "men"
        }
    ]
}
```

Code snippet.
```js
describe("Filter prodcuts suite for clearhaircare ar en",function(){
    before(() => {
        // Block newrelic js outright due to issues with Cypress networking code.
        cy.log("Blocking NewRelic scripts");
        //Will block 
        //  https://js-agent.newrelic.com/nr-spa-1208.js
        cy.intercept(/\.*newrelic.*$/, (req) => {
            console.log("NEW RELIC INTERCEPTED");
            req.reply("console.log('Fake New Relic script loaded');");
        });
    });

    beforeEach(function () {
        cy.fixture("/clearhaircare_ar_en/prod-site/filter").then((data) => {
            this.testdata = data
        })
    })

    it("Filter prodcuts test for clearhaircare_ar_en", function () {
        cy.intercept('GET',this.testdata.requestintercept).as('call')
        cy.visit(this.testdata.url).wait('@call')
        for (var i = 0; i < this.testdata.filters.length; i++) {
            cy.get(this.testdata.filters[i].locator).select(this.testdata.filters[i].value).should('have.value',this.testdata.filters[i].value)
            cy.url().should('contain',this.testdata.filters[i].url)
        }
        cy.log("snapshot: " + this.testdata.site+"_filter_"+ i)
    })
})
```

package.json:
```json
  "dependencies": {
    "cypress": "^9.5.2",
    "cypress-real-events": "^1.6.0",
    "scroll-to-bottomjs": "^1.1.0"
  },
  "devDependencies": {
    "@percy/cli": "^1.0.0-beta.68",
    "@percy/cypress": "^3.1.1",
    "cypress-iframe": "^1.0.1",
    "cypress-pipe": "^2.0.0",
    "cypress-wait-until": "^1.7.2",
    "mochawesome": "^7.1.0",
    "mochawesome-merge": "^4.2.1",
    "mochawesome-report-generator": "^6.1.0"
  }
```

### Cypress Version

9.5.2

**Comment by emilyrohrbough** [comment]
@mkathu This doesn't appear to be an issue when I run your example. There are quite a few errors going on & I had to bypass an error within your site, but running this correctly selects the options.
```js
describe('Filter prodcuts suite for clearhaircare ar en', function () {
  before(() => {
    // Block newrelic js outright due to issues with Cypress networking code.
    cy.log('Blocking NewRelic scripts')
    //Will block
    //  https://js-agent.newrelic.com/nr-spa-1208.js
    cy.intercept(/\.*newrelic.*$/, (req) => {
      console.log('NEW RELIC INTERCEPTED')
      req.reply('console.log(\'Fake New Relic script loaded\');')
    })
  })

  beforeEach(function () {
    cy.fixture('/issue').then((data) => {
      this.testdata = data
    })
  })

  it('Filter prodcuts test for clearhaircare_ar_en', function () {
    cy.on('uncaught:exception', () => {
     // seeing
     // (uncaught exception)
     // Error: Script error. Cypress detected that an uncaught error was thrown from a cross origin script. We cannot provide      
     //  you the stack trace, line number, or file where this error occurred. Check your Developer Tools Console for the actual      
     // error - it should be printed there. It's possible to enable debugging these scripts by adding the crossorigin attribute and 
     // setting a CORS header.
      return false
    })

    // cy.intercept('GET', this.testdata.requestintercept).as('call')
    cy.visit(this.testdata.url)
    // .wait('@call')
    for (var i = 0; i < this.testdata.filters.length; i++) {
      cy.get(this.testdata.filters[i].locator).select(this.testdata.filters[i].value).should('have.value', this.testdata.filters[i].value)
    //   cy.url().should('contain', this.testdata.filters[i].url)
    }
    cy.log(`snapshot: ${ this.testdata.site }_filter_${ i}`)
  })
})
```
<img width="1589" alt="Screen Shot 2022-03-24 at 11 35 57 AM" src="https://user-images.githubusercontent.com/14099737/159966007-a19ed70d-1ad4-4668-b101-cd3b57262567.png">

**Comment by mkathu** [comment]
No its not that the drop downs or filters are not selectable in cypress. It is the result which needs to be displayed once filters are applied. This works manually on browsers but no results are displayed in cypress.

**Comment by mkathu** [comment]
> @mkathu This doesn't appear to be an issue when I run your example. There are quite a few errors going on & I had to bypass an error within your site, but running this correctly selects the options.
> 
> ```js
> describe('Filter prodcuts suite for clearhaircare ar en', function () {
>   before(() => {
>     // Block newrelic js outright due to issues with Cypress networking code.
>     cy.log('Blocking NewRelic scripts')
>     //Will block
>     //  https://js-agent.newrelic.com/nr-spa-1208.js
>     cy.intercept(/\.*newrelic.*$/, (req) => {
>       console.log('NEW RELIC INTERCEPTED')
>       req.reply('console.log(\'Fake New Relic script loaded\');')
>     })
>   })
> 
>   beforeEach(function () {
>     cy.fixture('/issue').then((data) => {
>       this.testdata = data
>     })
>   })
> 
>   it('Filter prodcuts test for clearhaircare_ar_en', function () {
>     cy.on('uncaught:exception', () => {
>      // seeing
>      // (uncaught exception)
>      // Error: Script error. Cypress detected that an uncaught error was thrown from a cross origin script. We cannot provide      
>      //  you the stack trace, line number, or file where this error occurred. Check your Developer Tools Console for the actual      
>      // error - it should be printed there. It's possible to enable debugging these scripts by adding the crossorigin attribute and 
>      // setting a CORS header.
>       return false
>     })
> 
>     // cy.intercept('GET', this.testdata.requestintercept).as('call')
>     cy.visit(this.testdata.url)
>     // .wait('@call')
>     for (var i = 0; i < this.testdata.filters.length; i++) {
>       cy.get(this.testdata.filters[i].locator).select(this.testdata.filters[i].value).should('have.value', this.testdata.filters[i].value)
>     //   cy.url().should('contain', this.testdata.filters[i].url)
>     }
>     cy.log(`snapshot: ${ this.testdata.site }_filter_${ i}`)
>   })
> })
> ```
> 
> <img alt="Screen Shot 2022-03-24 at 11 35 57 AM" width="1589" src="https://user-images.githubusercontent.com/14099737/159966007-a19ed70d-1ad4-4668-b101-cd3b57262567.png">

@emilyrohrbough not sure what is the difference but the same script does not work on my system. I used windows machine. Can you please share the script so that i give it a try.

**Comment by emilyrohrbough** [comment]
@mkathu Can you share a generalized snipped of the callback that should be triggered when the `option` is selected?

**Comment by mkathu** [comment]
@emilyrohrbough ,
I tried to observe the network logs and found that on selecting a value from a drop down, request is made.

Example:
On selecting Type drop down as "shampoo" and selecting need dropdown as "damaged" below api call is made which fetches the response in json format.

https://www.clearhaircare.com/arabia/en/products/type/Shampoo/_jcr_content/flexi_hero_par/productlistingv2.data.json?fl=clear^product^type^shampoo&fl=clear^product^needs^damaged&pn=1

On chrome manually:
![image](https://user-images.githubusercontent.com/7846128/160235049-54e89700-42c9-4f81-8eed-7f231f6d8801.png)

Same thing when done in Cypress runner:
![image](https://user-images.githubusercontent.com/7846128/160235068-2ee5d8c8-4347-42e7-bc22-8487dd81eb55.png)

Looks like this request is not going through in cypress.
![image](https://user-images.githubusercontent.com/7846128/160235137-58c678b9-9950-49b2-87fb-b8431704dcc4.png)

Hence, zero results is seen on screen.
![image](https://user-images.githubusercontent.com/7846128/160235209-535d94b7-a62e-4c53-a617-938e5003e1dc.png)

Not sure if this is the cause.

**Comment by mkathu** [comment]
Any update on this?

**Comment by emilyrohrbough** [comment]
@mkathu I am not actively looking into this issue. Sorry 😞

**Comment by umashankar-pm** [comment]
> Any update on this?

did you find a solution or fix for this?
