### ISSUE TITLE
Swap out config validation with standardized json schema validator

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2076]
We already created a JSON schema spec for the configuration here: https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json

We can use this to also do the `lib/config` validation, setting defaults, etc. We're using this on all of our other projects so it just makes sense to keep it all in one area and one file.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
