### ISSUE TITLE
I can't join my company team

### ISSUE THREAD

**Issue by Porkstone** [cypress-io/cypress#20779]
### Current behavior

When I login in with my company email @tulipshare.com the admin panel forces me to create a new organisation. A colleague already created our organisation and I would like to join. Any ideas?

### Desired behavior

I would like to join our existing team.

### Test code to reproduce

IF this is not the correct place to report this issue please let me know.

### Cypress Version

1.0

**Comment by jennifer-shehane** [comment]
@Porkstone Ask your team member to invite you to the organization. https://docs.cypress.io/guides/dashboard/users#Invite-a-user-to-an-organization

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
