### ISSUE TITLE
How can I solve this error: css property: hidden

### ISSUE THREAD

**Issue by Plhamo65** [cypress-io/cypress#20795]
### Current behavior

Timed out retrying after 4050ms: cy.click() failed because this element is not visible: 
[This](<img width="282" alt="error" src="https://user-images.githubusercontent.com/93437040/160369552-e5cdb08a-b9fc-4472-9aa0-e47ee875934d.PNG">) element <button#btnAddNew.btn.btn-primary> is not visible because its parent <div#_PatientSavedModal.modal> has CSS property: display: none

### Desired behavior

it should able to add new patient and close the dialog box.

### Test code to reproduce

cy.get('#\_PatientSavedModal').click({ force: true });
cy.get('#btnAddNew').should('be.visible').click();
cy.get('#btnReset').contains('Close').click();

### Cypress Version

9.5.2

**Comment by davidmunechika** [comment]
Could you provide an example repo so we could reproduce this issue? Unfortunately, we will have to close this issue if we cannot reproduce it.
