### ISSUE TITLE
cross browser bug with the installed browser 

### ISSUE THREAD

**Issue by ahmedmostaffa** [cypress-io/cypress#20791]
### Current behavior

it show this error  when I run cypress via this command >>npx cypress run --browser firefox
whereas I have installed firefox and chrome browser in my windows 10
"Can't run because you've entered an invalid browser name.
Browser: firefox was not found on your system or is not supported by Cypress."

### Desired behavior

run the test cases on firfox

### Test code to reproduce

run this command >>npx cypress run --browser firefox

### Cypress Version

9.5.2

**Comment by davidmunechika** [comment]
Cypress has very strict browser detection rules. On Windows 10 it looks for browser binary in Program Files and Program Files (x86): https://github.com/cypress-io/cypress/blob/develop/packages/launcher/lib/windows/index.ts#L45-L49

If for some reason you installed Firefox in some other folder, it is possible that Cypress fails to automatically detect that browser.

Get the path for your firefox.exe (go to properties on your firefox shortcut and copy the value in the target field) and pass it as an arg to your cypress open/run command like this

```shell
cypress open --browser "C:\\Path\Foo\\Bar\\firefox.exe"
```
Cypress will list the browser from the given path as Custom Firefox Browser.

For more information: https://docs.cypress.io/guides/guides/launching-browsers.html#Launching-by-a-path

Let me know if this works for you!

**Comment by ahmedmostaffa** [comment]
I am very sorry for late response ,but my browsers chrome and firefox has already installed at program files folder. 
Is there any solution for this situation?!

**Comment by mjhenkes** [comment]
@ahmedmostaffa, try out our 'launching-by-a-path` docs to launch browsers installed in an unexpected (to cypress) path.

https://docs.cypress.io/guides/guides/launching-browsers#Launching-by-a-path

**Comment by mjhenkes** [comment]
@ahmedmostaffa, Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
