### ISSUE TITLE
Ability to override config files from CLI parameter --env

### ISSUE THREAD

**Issue by richardszanyi-kasa** [cypress-io/cypress#20793]
### What would you like?

Hi all, 

I would like to propose a feature that would highly benefit in the terms of customizing how cypress gets its environment variables. 

I would like to have access to CLI parameters in the plugin files, however, there is no way in my knowledge to do that. 

I have the following scenario done with the use of @bahmutov 's dependency to merge cypress.json configs. 

mobile-dev.json extends > dev.json extends > cypress.json
mobile-dev.json contains mobile-specific env vars such as userAgent, viewportHeight
dev.json contains development environment-specific vars, such as authUrl, abc, and def variables.
cypress.json contains global configuration, which should be default to any runs on any environment.

Furthermore, we are overriding variables from CLI as well in some cases such as and to have the highest precedence:
`npx cypress:open --config-file mobile-dev.json --env abc=123,def=456`

In the example above I would expect the following behavior: 
mobile-dev.json read >> it contains extends so with the `cypress-extends` dependency it reads the next >> dev.json read >> cypress.json read. >> config returned in plugin >> **CLI --env parameters gets read and cypress overrides the parameters in the returned config.**

This is however not the case. Config is correctly merged, but there is no way for me to access CLI parameters in plugins, and CLI parameters get overridden by the config or do not overwrite existing environment variables. 

The easiest solution would be to let us change this order of the sources to be read up however we like:
![image](https://user-images.githubusercontent.com/101114202/160354317-751348a6-69b6-4f58-b17b-279ae86ec608.png)

Anyone has a solution for the above-mentioned problem, or have you considered the possibility to let us configure the precedence in which order these values come from?

Cypress version:  8.6.0

### Why is this needed?

I would like to have the ability to customize our configuration however we see fit in Cypress.

**Comment by bahmutov** [comment]
Are you sure? Whatever your get in your plugins file is the merged result with the CLI values being applied last, thus overwriting the previous values, or at least they should. Are you using cypress-extend? Can you create a small repo with a reproducible example showing the expected vs actual result?

**Comment by richardszanyi-kasa** [comment]
Yes, I'm pretty sure, unfortunately. 
I have a workaround for that by putting my --env variables into process.env and manipulating the config object in the plugin. 

Unfortunately, I've taken some time with that and can confirm that CLI vars gets overwritten by the config changes in the plugin. I'm unsure if its due to the dependency, or cypress itself.

**Comment by bahmutov** [comment]
And this is stock cypress or cypress-extend?

**Comment by richardszanyi-kasa** [comment]
cypress-extends.

> And this is stock cypress or cypress-extend?
> […](#)
> Sent from my iPhone
> On Mar 28, 2022, at 07:48, richardszanyi-kasa ***@***.***> wrote: ﻿ Yes, I'm pretty sure, unfortunately. I have a workaround for that by putting my --env variables into process.env and manipulating the config object in the plugin. Unfortunately, I've taken some time with that and can confirm that CLI vars gets overwritten by the config changes in the plugin. I'm unsure if its due to the dependency, or cypress itself. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

**Comment by bahmutov** [comment]
So this issue should probably be reported in that repo, no?

**Comment by richardszanyi-kasa** [comment]
I'm not sure, it would need more investigation on a clean repo. 
Unfortunately, I do not have the necessary capacity to handle this, sorry.

**Comment by richardszanyi-kasa** [comment]
It is no longer an issue in cypress 10+
