### ISSUE TITLE
Property `isInteractive` is missing on the `Cypress.PluginConfigOptions` type

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#20790]
### Current behavior

SSIA.

### Test code to reproduce

```ts
export default (
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Cypress.PluginConfigOptions
  config.isInteractive // Property 'isInteractive' does not exist on type 'PluginConfigOptions'.
}
```

### Cypress Version

9.5.2

**Comment by emilyrohrbough** [comment]
@badeball This is set by Cypress when `open` mode is leveraged and It's not intended to be a configurable property.

**Comment by emilyrohrbough** [comment]
Re-opening after reading #20789 ..Are you utilizing this value to determine how your plugin should behave? It would seem this value should be accessibly to check this.
