### ISSUE TITLE
Test Runner does not show text

### ISSUE THREAD

**Issue by explofish** [cypress-io/cypress#2080]
### Current behavior:
When running examples/action.spec.js i cant see any test results as well as no text on the site to test.

<img width="1192" alt="bildschirmfoto 2018-07-01 um 14 05 23" src="https://user-images.githubusercontent.com/3141112/42134240-de8e9cb6-7d37-11e8-9943-2c8e319a054d.png">

### Desired behavior:
Correct Rendering of Test Runner and Site to test

### Steps to reproduce:
I installed Cypress in my project via npm and started it via package.json cypress open.
The Tests overview window renders correctly. After selecting any test the new Test Runner window does not show any fonts

### Versions
Cypress: 3.0.2
Browser: In the electron app chrome 67 is selected
System: OSX 10.13.5

**Works as expected in Electron 59!**

**Comment by brian-mann** [comment]
Please see my comment here for a fix: https://github.com/cypress-io/cypress/issues/1617#issuecomment-397373555
