### ISSUE TITLE
Bug: TypeError fn.apply is not a function

### ISSUE THREAD

**Issue by RamoniDias** [cypress-io/cypress#20803]
### Current behavior

Boa tarde,

Ao executar um arquivo no cypress, esse bug é apresentado na Tela do Cypress, não sei se o bug é do cypress ou do Java script do desenvolvedor.

Bug:
![image](https://user-images.githubusercontent.com/86800157/160447412-2bcaae45-0726-45eb-acb5-83583e7165b3.png)

### Desired behavior

Que ele execute os testes normalmente.

### Test code to reproduce

Nos testes apenas testo alguns radio button.

/// <reference types = "cypress" />

describe('TESTAR: Termo de Adesão e Contratação de Serviços', () => {
  // Repete essa linha em todos os "it" em todos os grupos
  before(() => {
    cy.visit('http://localhost:8080/');
  });

  /*beforeEach(() => {
    cy.reload(); 
  });*/

  it.only(
    'CENÁRIO DE TESTE 01: Tipo de Venda.',
    'Caso de Teste 01: Validar se os Radios existe.',
    'Caso de Teste 02: Validar se o Rádio esta selecionado.',
    'Caso de Teste 03: Validar quantos Rádios tem na Tela ',
    function() {
      Cypress.on('uncaught:exception', (err, runnable) => {
        // Ignorar erro 500  da API
        // Ignora Erros e continua os testes
        // returning false here prevents Cypress from
        return false;
      });

      //Tela Login
      cy.get('#ndamatrcula-1').type('9999999', { delay: 35 });
      cy.get('#senha-1').type('Trade@2020');
      cy.get('#button-35').click({ delay: 35 });

      //Tela Módulo
      cy.get('#TermoContingencial').should('exist');
      cy.get('#TermoContingencial').click();
      cy.get('[label="label"] > .smart-card__wrapper').click();

      //Tipo de Venda
      cy.get('[name="v-radio-99"][value="venda"]').should('exist');
      cy.get('[name="v-radio-99"][value="venda"]').should('be.checked');

      cy.get('[name="v-radio-99"][value="posVenda"]').should('exist');
      cy.get('[name="v-radio-99"][value="posVenda"]').should('not.be.checked');

      //Contar Qauntos Radio Buton existe
      cy.get('#tipoVendaRadio [name="v-radio-99"]').should('have.length', 2);

      //Mensagem
      cy.log('Mensagem: Existem 2 radios Button / Tipo de venda');
    }
  );

  it(
    'CENÁRIO DE TESTE 02: Pessoa.',
    'Caso de Teste 01: Validar se os Radios existe.',
    'Caso de Teste 02: Validar se o Rádio esta selecionado.',
    'Caso de Teste 03: Validar quantos Rádios tem na Tela ',
    function() {
      //Física
      cy.get('[name="v-radio-115"][value="fisica"]').should('exist');
      cy.get('[name="v-radio-115"][value="fisica"]').should('be.checked');

      //Jurídico
      cy.get('[name="v-radio-115"][value="juridica"]').should('exist');
      cy.get('[name="v-radio-115"][value="juridica"]').should('not.be.checked');

      //Contar Qauntos Radio Buton existe
      cy.get('#pessoaRadio [name=v-radio-115]').should('have.length', 2);

      //Mensagem
      cy.log('Mensagem: Existem 2 radios Button / Pessoa');
    }
  );

  it(
    'CENÁRIO DE TESTE 03: Tipo de Serviço.',
    'Caso de Teste 01: Validar se o Radio existe.',
    'Caso de Teste 02: Validar se o Rádio esta selecionado.',
    'Caso de Teste 03: Validar quantos Rádios tem na Tela ',
    function() {
      //SMP
      cy.get('[name="v-radio-123"][value="smp"]').should('exist');
      cy.get('[name="v-radio-123"][value="smp"]').should('be.checked');

      //STFC
      cy.get('[name="v-radio-123"][value="stfc"]').should('exist');
      cy.get('[name="v-radio-123"][value="stfc"]').should('not.be.checked');

      //SMC
      cy.get('[name="v-radio-123"][value="scm"]').should('exist');
      cy.get('[name="v-radio-123"][value="scm"]').should('not.be.checked');

      //Convergência
      cy.get('[name="v-radio-123"][value="convergencia"]').should('not.exist');

      //Contar Qauntos Radio Buton existe
      cy.get('#tipoServicoRadio [name="v-radio-123"]').should('have.length', 3);

      //Mensagem
      cy.log('Mensagem: Existem 3 radios Button / Tipo de Serviço');

      //Botão Avançar para proxima tela
      cy.get('#btnNext')
        .click()
        .should('be.true');
    }
  );

  it(
    'CENÁRIO DE TESTE 04: Planos.',
    'Caso de Teste 01: Validar se o Radio existe.',
    'Caso de Teste 02: Validar se o Rádio esta selecionado.',
    'Caso de Teste 03: Validar quantos Rádios tem na Tela ',
    function() {
      //Pós Pago Fatura
      cy.get('[name="v-radio-140"][value="fatura"]').should('exist');
      cy.get('[name="v-radio-140"][value="fatura"]').should('be.checked');

      //Controle Fatura
      cy.get('[name="v-radio-140"][value="controleFatura"]').should('exist');
      cy.get('[name="v-radio-140"][value="controleFatura"]').should('not.be.checked');

      //Pós Pago Express
      cy.get('[name="v-radio-140"][value="express"]').should('exist');
      cy.get('[name="v-radio-140"][value="express"]').should('not.be.checked');

      //WTTX
      cy.get('[name="v-radio-140"][value="wttx"]').should('exist');
      cy.get('[name="v-radio-140"][value="wttx"]').should('not.be.checked');

      //Pós Pago Familía
      cy.get('[name="v-radio-140"][value="family"]').should('exist');
      cy.get('[name="v-radio-140"][value="family"]').should('not.be.checked');

      //Controle Express
      cy.get('[name="v-radio-140"][value="controleExpress"]').should('not.exist');

      //Corporativo
      cy.get('[name="v-radio-140"][value="corporativo"]').should('not.exist');

      //Contar Qauntos Radio Buton existe
      cy.get('#tipoPlanoRadio [name="v-radio-140"]').should('have.lenght', 5);

      //Mensagem
      cy.log('Mensagem: Existem 5 radios Button / Planos');

      //Botão Avançar para proxima tela
      cy.get('#btnNext')
        .click()
        .should('be.true');
    }
  );
});

### Cypress Version

8.7.0

**Comment by davidmunechika** [comment]
Closing because duplicate of https://github.com/cypress-io/cypress/issues/20804
