### ISSUE TITLE
Publish latest `cypress/browsers` Docker images to AWS ECR

### ISSUE THREAD

**Issue by ddzz** [cypress-io/cypress#20812]
### What would you like?

The latest browser image on AWS ECR is `browsers:node14.17.0-chrome88-ff89`, which is several months behind what's on Docker Hub. Can you please push the latest images to ECR? Thank you.

### Why is this needed?

ECR browser Docker images are out of date.

**Comment by davidmunechika** [comment]
Closing this issue since it is a duplicate of https://github.com/cypress-io/cypress-docker-images/issues/518 in the cypress-docker-images repo. Thanks for opening an issue, we will look into this!
