### ISSUE TITLE
Add example in documentation for Rubaxa

### ISSUE THREAD

**Issue by sebastien-A256** [cypress-io/cypress#2082]
Hi, I'm using Rubaxa into an Angular6 project and I'm trying to interact with the Ui to drag and drop elements. I've been trying a lot of things and I never succeed.
Could it be possible to add an example in the documentation for testing drag and drop with Rubaxa.

### Current behavior:

No example for Rubaxa, example for query-ui sortable is not working.

### Desired behavior:

Add an example in the documentation for testing drag and drop with Rubaxa.

### Versions

Cypress 3.0.2, OSX 10.13.5, Chrome 67.0.3396.99

**Comment by jak-kal** [comment]
Hi - could be a completely unrelated issue, however, I am also experiencing issues with the drag-and-drop API in Chrome 67.0.3396.99. Your post is the only reference to there being an issue in this particular version of Chrome and I'm trying to narrow it down.

Using Browserstack, I was able to test the issue in versions 67.0.3396.62 and 68.0.3440.7 dev and I am not able to reproduce the same issue as experienced in version 67.0.3396.99.

Could you possibly test your code in another browser or, preferably, an older/ newer version of Chrome (if you don't have a paid Browserstack subscription, I think you can sign up for a free 30-minute trial).

Sorry I cannot be of any help with your particular situation, though I feel if it is a browser-related issue (really, really strange!) then it might resolve your problem anyhow.

**Comment by jennifer-shehane** [comment]
I created a new issue in our [example recipes repo](https://github.com/cypress-io/cypress-example-recipes) to document drag and drop in Rubaxa here: https://github.com/cypress-io/cypress-example-recipes/issues/166. Our recipes is open source and contributions are welcome. 😄

**Comment by jennifer-shehane** [comment]
@jak-kal Hey, if you are still experiencing this issue, I would suggest opening a new issue, since the core of this issue was surrounding documentation. Thanks!
