### ISSUE TITLE
[Multi-domain]: Reset to `baseurl` between tests

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#20826]
### What would you like?

Reset to `baseurl` between tests

### Why is this needed?
When a test is run, top is set to whatever the previous test set top to, regardless of base url. How this relates to multi-domain is that without an initial visit, tests do not explicitly set top. switchToDomain does not require an initial visit but expects to return to top for any subsequent commands.

This allows the top set in a test to bleed into subsequent tests. Ideally tests would be isolated from each other.

```javascript
    it('reset top to localhost', () => {
      cy.visit('/fixtures/auth/index.html')
    })
    
    it('reset top to foobar', () => {
      cy.visit('http://www.foobar.com:3500/fixtures/auth/index.html')
    })
    
    // Top for this test will be set to foobar, unless the test is skiped, then it will be localhost.
    it('D logs in with primary set via switch to domain config', () => {
      cy.switchToDomain('http://idp.com:3500', () => { // PrimaryDomain set to localhost
        cy.visit('http://www.idp.com/fixtures/auth/idp.html')
        cy.get('[data-cy="username"]').type('FJohnson')
        cy.get('[data-cy="login"]').click() // Where does this click take us?
      })
    
      cy.get('[data-cy="welcome"]') // What domain does the user expect this command to be run against?
      .invoke('text')
      .should('equal', 'Welcome FJohnson')
    })
```
    
The rules for setting top are as follows:
* Base url. If base url is set, top is initially set to baseUrl for test run.
* The first visit within a test sets top.
  * If visiting a domain other than base url, the before steps will be repeated.
 * The second visit within a test will not set top.

Proposal:

* Require `baseurl` with cypress 11 (The GA release of multi-domain)
* Reset top to `baseurl` before each test.
* `baseurl` can be dynamically set for each test, though it cannot be set to null or undefined
* The first visit still can reset top, if visiting a cross origin url.  If the first visit resets top the before steps will be repeated.
* This may result in some inefficiencies depending on how tests are written.

```javascript
// Assume baseurl is localhost
// Inefficient
context('tests', () => {
  it('visits a cross origin url', () => { // Top set to localhost
    cy.visit('https://www.foobar.com/page1') // Top reset to foobar.com
  })

  it('visits a cross origin url again', () => { // Top set to localhost
    cy.visit('https://www.foobar.com/page2') // Top reset to foobar.com
  })
})

// Better
context('tests', { baseUrl: 'https://www.foobar.com' }, () => {
  it('visits a cross origin url', () => { // Top set to foobar.com
    cy.visit('/page1')
  })

  it('visits a cross origin url again', () => { // Top set to foobar.com
    cy.visit('/page2')
  })
})
```

**Comment by nagash77** [comment]
Cancelled.  We will revisit the issue with product to get input on approach which could have a large impact on users.
