### ISSUE TITLE
[Multi-domain]: Support cy.visit('/redirect?<back to previous>')

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#20824]
### What would you like?

Support cy.visit('/redirect?<back to previous>')

### Why is this needed?

We want to support redirects via cy visit.

**Comment by mschile** [comment]
After further discussion, this change is not needed. Visiting another origin within `switchToDomain` is not supported even if it's back to a previous origin.  In this case, the user would just move the visit out of the `switchToDomain` into a location where the final redirect would resolve correctly (either a different `switchToDomain` or at the top-level).
