### ISSUE TITLE
Jenkins runs in CI are often missing branch name

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#20833]
### Current behavior

For many of our users running in Jenkins, the branch name is often missing when recording to the Dashboard. We do capture the information from a `GIT_BRANCH` environment var here: https://github.com/cypress-io/cypress/blob/10.0-release/packages/server/lib/util/ci_provider.js#L537:L537 but perhaps this is not the correct env var, perhaps it's not being captured correctly, or perhaps users git info is not available in some cases. 

### Desired behavior

Investigate why the branch name is missing from many Jenkins users and collect the correct environment variable or update our docs to guide users on how they can get this collected. 

### Test code to reproduce

You'd have to run within Jenkins to see how this is working and collected. 

### Cypress Version

9.5.3

**Comment by emilyrohrbough** [comment]
We may need to check both `GIT_BRANCH` and `BRANCH_NAME`. `BRANCH_NAME` is an env exposed by the [multibranch plugin](https://www.jenkins.io/doc/book/pipeline/multibranch/).

**Comment by rockhold** [comment]
This issue is also currently in the [backlog for the Dashboard team](https://cypress-io.atlassian.net/browse/CLOUD-430). Peter is open to either team picking it up when we're ready from a priority standpoint.
