### ISSUE TITLE
Not possible to remove yourself from an organization via the dashboard

### ISSUE THREAD

**Issue by volkanogretmen** [cypress-io/cypress#2083]
### Current behavior:
Currently, it's not possible for me to remove myself from an organization that is owned by someone else. The page keeps loading and nothing happens. I get a status code 403 in the console.

### Desired behavior:
I can remove myself from an organization via the dashboard.h

### Steps to reproduce:
To reproduce:

- Go to https://dashboard.cypress.io
- Go to Organizations tab
- Click on the organization you want yourself removed from
- Go to Users
- Click on Leave behind your username
- Results in a 403 in the console

**Comment by jennifer-shehane** [comment]
This should be fixed now!
