### ISSUE TITLE
AWS Codebuild CI runs do not show branch name in the Dashboard. 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#20832]
### Current behavior

Runs in the Dashboard that were run through AWS Codebuild do not show the branch name. It seems as if we're not collecting this information currently: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.js#L151:L151

It doesn't seem completely straightforward on which env var we would need to read to get this information from the AWS Codebuild docs. Some env vars show commit or branch for instance. https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

### Desired behavior

Collect an environment variable from AWS Codebuild runs that would reliably provide branch name for the majority of cases. 

This is important because the Dashboard wants to rework some of their designs to be more branch focused, but for many of our users this branch name is missing. 

### Test code to reproduce

You'd have to set up an AWS Codebuild run unfortunately. 

### Cypress Version

9.5.3

**Comment by emilyrohrbough** [comment]
This one would be tricky to get right. It'd depend on how the user has configured AWS Codebuild and how their source code was triggering it. `CODEBUILD_SOURCE_VERSION` is the that might provide use the information we need, but it won't be a guarantee that it'll referencing GIT source code or a git branch name.

**Comment by rockhold** [comment]
This issue is also currently in the [backlog for the Dashboard team](https://cypress-io.atlassian.net/browse/CLOUD-567). Peter is open to either team picking it up when we're ready from a priority standpoint.

**Comment by DaweiTao** [comment]
Do you have any updates on this? Tests were run through Codebuild and the branch name in the dashboard was "unknown". If there is a way to set a branch name for the run, that would be great.

**Comment by nagash77** [comment]
Hi @DaweiTao , I have passed this ticket along to our Cloud team.  However if you are a cloud customer I would recommend you reach out to your support rep at Cypress and mention this ticket.  It will help them understand if this ticket is a priority to end users.

**Comment by benpatterson** [comment]
Reviewing some stale tickets... This CI provider has been added; thanks for raising it and advocating for it. The issue should be all set now. 

Referenced in docs now as well: https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#AWS-CodeBuild
