### ISSUE TITLE
LocalStorage and cookies is not cleared even if use clearLocal Storage function

### ISSUE THREAD

**Issue by MaksymKot88** [cypress-io/cypress#20845]
### Current behavior

Steps to reproduce
1. Login in web site using cypress. 
2. run test as logined user.
3. run next test.

Actual result
User stay logined in site when run 2nd test

Expected results
User is not logined in 2nd test

### Desired behavior

i need clear Site data before each tests . But Site data aren't  deleted.  I use this function before each tests:         cy.clearLocalStorage()
cy.clearCookies()

and even this:  cy.window().then(window => window.localStorage.clear());

but user still logined in each tests. Even if i restart Cypress app user still logined

### Test code to reproduce

```js
 before(() => {
        cy.resetInstance;
        cy.window().then(win => win.sessionStorage.clear());
        cy.clearLocalStorage()
        cy.clearCookies()
        cy.login()
    })
describe('test', () => {
  it('test1', () => {
   
  });
  it('test2', () => {
  
  });
  
});
```

### Cypress Version

9.5.3

**Comment by davidmunechika** [comment]
I notice you are using the Cypress `before()` hook. This will execute once prior all tests in a `describe` block. Therefore, it is not running after test1 completes and prior to the execution of test2. I would suggest trying a `beforeEach()` hook instead, which will run prior to each test within its block. Alternatively, bear in mind that [Cypress clears out the state of browser](https://docs.cypress.io/api/commands/clearcookies.html#Syntax) in between tests. So if you included the `cy.login()` command inside test1 you will be logged out at the start of test2. 

Let me know if this was able to fix your issue! I am happy to reopen it if you run into any other problems.

**Comment by MaksymKot88** [comment]
@davidmunechika i mean that user always logined.Even if i don't use before or beforeEach hook. I even can use this code:   before(() => {
        cy.resetInstance;
        cy.window().then(win => win.sessionStorage.clear());
        cy.clearLocalStorage()
        cy.clearCookies()
        cy.login()
    })
describe('test', () => {
  it('test1', () => {
   
  });
  it('test2', () => {
 cy.window().then(win => win.sessionStorage.clear());
        cy.clearLocalStorage()
        cy.clearCookies()
  
  });
  
});

and user in test 2 still stay  logined.

**Comment by davidmunechika** [comment]
Would you be able to provide a demo repository so that I can try and reproduce this issue and look into it further?
