### ISSUE TITLE
Documentation outdated for screenshots

### ISSUE THREAD

**Issue by phryneas** [cypress-io/cypress#2084]
Since 3.0.2, the screenshot behaviour seems to have changed in many aspects and the documentation ( https://docs.cypress.io/api/commands/screenshot.html ) does not reflect that yet.

This is mainly caused by #1826, but I guess other changes in #1858 could have some impact, too?

I do not feel comfortable fixing the documentation myself as I am still just evaluating if I want to use cypress at all and have no idea what is really going on there.

**Comment by chrisbreiding** [comment]
Thanks for pointing this out. I think we overlooked a few things when updating the docs. I'm going to update the screenshot doc and add a section about naming conventions.

**Comment by chrisbreiding** [comment]
No worries. I completely understand how frustrating incorrect documentation can be.

**Comment by brian-mann** [comment]
We noticed a bug in the implementation when capturing screenshots in `cypress run` and `cypress open` that is also making this more confusing.
