### ISSUE TITLE
Deprecate `firefoxGcInterval` configuration value

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#20874]
### What would you like?

We should deprecate and subsequently remove the [`firefoxGcInterval`](https://docs.cypress.io/guides/references/configuration#firefoxGcInterval) flag.

### Why is this needed?

The `firefoxGcInterval` was only intended for use with Firefox versions 80 and below. In our [official guide on Firefox versions we support](https://docs.cypress.io/guides/guides/launching-browsers#Browser-versions-supported), we do not support below Firefox 86.

**Comment by emilyrohrbough** [comment]
This configuration option was removed in Cypress 8.0.0 per the warning message: https://github.com/cypress-io/cypress/blob/1c5a67fa927e16620966e977f12cd8a7c3ff69fc/packages/errors/src/errors.ts#L1231.
