### ISSUE TITLE
assertion error in within block passes limited scope to after/afterEach block

### ISSUE THREAD

**Issue by AlyonaQA** [cypress-io/cypress#20887]
### Current behavior

assertion error in .within block passes limited visibility scope to after/afterEach block

### Desired behavior

after/afterEach block regain scope of the whole page and is not limited to within scope 

### Test code to reproduce

```
<table>
  <tr>
    <td>My first client</td>
  </tr>
</table>
```

```
describe('sample 1', () => {
  beforeEach(() => {
    cy.visit(/)
  })

  afterEach(() => {
        cy.get('table').click() // will never happen - is undefined because of wintin scope focused on tr element
  })

  it(`sample test`, () => {
    cy.get('tr')
        .within(() => {
          cy.get('td')
            .should('have.length4', 123) // should fail here
        })
    })
  })
```

### Cypress Version

9.1.1

### Other

very annoying produces a lot of skipped tests without proper reason

having a simple page structure

```
header 
page content
```

having any assertion fail within page content will make your header unreachable in after block

you can call `cy.root()` in after block and see it's still limited to within scope where assertion failure happened

**Comment by davidmunechika** [comment]
I see that you are using an older version of Cypress. Does this issue also occur on the [current version of Cypress](https://on.cypress.io/changelog)? Thanks!

**Comment by AlyonaQA** [comment]
same result with 9.5.3. @davidmunechika 

after has limited visibility which is passed from the element where within chain have started

```
cy.root() // <html>...</html>
cy.get('content')
  .within(() => {
    cy.get('innerContent')
    .should("have.l", "123") // intentional failure
  })
})

after() {
  cy.root() // get.('content') - actual result
}
```

Expected: `<html>...<html/>`
