### ISSUE TITLE
Recover from being unable to end the video recording stream

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2088]
It appears that there are conditions to which a video recording stream cannot be finished as per these Travis CI logs: https://travis-ci.org/gpincheiraa/bln-frontend-project1/builds/399205721

I'm unsure what the underlying issue is, but regardless we need to simply add a timeout around this promise not resolving and continue on. It'll take a bit more digging to understand the underlying issue and whether or not the video is useful or corrupted at that point.

Related to: https://github.com/cypress-io/cypress/issues/1934#issuecomment-401862385

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
