### ISSUE TITLE
"A merge conflicted on path "/cypress.json".

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#20896]
### Current behavior

When I execute
`npm run ng add @cypress/schematic`
while having cypress.json file with one line:
`{}`
then I answer Yes to "Would you like the default 'ng e2e' command to use Cypress?"
then I see: "A merge conflicted on path "/cypress.json".

### Desired behavior

Display message: "/cypress.json already exists. Merge is not possible", instead of "A merge conflicted on path "/cypress.json".

### Test code to reproduce

-

### Cypress Version

9.5.3

**Comment by muuvmuuv** [comment]
Yep, same here. No Protactor installed, maybe thats the issue.

**Comment by muuvmuuv** [comment]
Oh, okay my issue was that I had two projects where one had a different root than the default.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. If you’re encountering something similar, plz open a new issue.
