### ISSUE TITLE
Type() behavior change between 8.x and 9.x (may related to event/focus/etc logic)

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#20904]
### Current behavior

Hello,
Currently I am trying to upgrade our Cypress 8.7.0 to newest version. 
However, after making the changes, some of our tests failed because `type()` command will only input the last char of the string into our table. The rest of the string were overwritten. Our tests are passing with 8.7.0. After some trying, I identified the root cause is introduced between 8.7.0 and 9.0.0. 

Current behavior:

9.0.0
https://user-images.githubusercontent.com/36670132/161647979-cde59e5c-fe21-4233-a8a4-4baa61e1c315.mp4

9.5.3 (newest)
https://user-images.githubusercontent.com/36670132/161648064-f4172f78-e946-43a0-af1e-2b45e0a5ebaa.mp4

### Desired behavior

The code works find in 8.7.0
https://user-images.githubusercontent.com/36670132/161648162-020dc926-1adc-4092-b2d8-7c90c5709c6f.mp4

### Test code to reproduce

```javascript
describe("s", ()=>{
    it("s", ()=>{
        cy.visit("https://benchling.com/signin/welcome#")
        // Manually login
        // and remove existing document if you ran this test before
        cy.pause()
        cy.get('[data-test-component="LegacyDropdownMenu"][data-test-element="item"] [data-test-key="entry"]').first().click({force:true})
        cy.get('[data-test-element="createButton"]').click()
        cy.get('[data-allow-at-search="true"]').first().click()
        cy.wait(2000)
        cy.get('[data-test-key="note-table"]').click({force:true})
        cy.get('[data-test-component="TableCell"][data-test-element="root"]').first().click()
        if(Cypress.version==="8.7.0"){
            cy.focused().type("abcde")
            cy.get('[data-test-component="TableCell"][data-test-element="root"]').first().find("span").should("have.text","abcde")
        }else{//    cypress 9.0.0 +

            //    have to use force
            cy.focused().type("abcde", {force:true})
            //only last char inputted is saved
            cy.get('[data-test-component="TableCell"][data-test-element="root"]').first().find("span").should("have.text","e")

        }




    })
})
```

### Cypress Version

9.5.3 (any 9.x version )

### Other

Please see the if condition in the test code to see the difference

Also, unfortunately, our app does not have a visiter demo that can be used to reproduce this issue. You have to register a free account and manually login during the `pause()`

**Comment by Songyu-Wang** [comment]
Hello @davidmunechika Thank you so much for tagging this issue. Do you have an estimated timeline on when should I expert your colleagues to take a first look? I just wanna have a general idea to how long we may be blocked for the cypress upgrade while the investigation is ongoing so we can internally plan this interruption accordingly.
Thanks again!

**Comment by davidmunechika** [comment]
@Songyu-Wang I am able to reproduce the issue with your site, but I am unable to reproduce it in an example `index.html` site with code. It is necessary for us to have a reproducible example that isn't dependent on your internal site (in order to write a test for the work). 

Would you be able to provide a simple example `index.html` file that reproduces this issue that we could use to fix this moving forward? Thanks!

**Comment by Songyu-Wang** [comment]
@davidmunechika 
The site is close sources so I cannot just copy and paste a piece of production code for that whole component and post here unfortunately.
It is probably easier if you can determine the root cause of the issue so we can find a way to generate an independent example in a targeted way.
