### ISSUE TITLE
No error on file upload but does not attach the file

### ISSUE THREAD

**Issue by darkhillreturns** [cypress-io/cypress#20913]
### Current behavior

Hi, 

I am trying to automate a file upload and I got no error on Cypress. It shows that it gets the file passed but does not attach it to the site.

Here is my code:
**The file is located under Fixture

```js
const filePath = 'bulkClientsUpload.xlsx';
 cy.get('.input-file-value').attachFile(filePath)
 ```

### Desired behavior

Should attach the file

### Test code to reproduce

```js
const filePath = 'bulkClientsUpload.xlsx';
 cy.get('.input-file-value').attachFile(filePath)
```

### Cypress Version

9.5.2

**Comment by davidmunechika** [comment]
Hi, thanks for opening an issue! I would recommend migrating from `cypress-file-upload` to the new `.selectFile()` API. Here are some links you might find helpful:

https://docs.cypress.io/guides/references/migration-guide#Migrating-from-cypress-file-upload-to-selectFile
https://docs.cypress.io/api/commands/selectfile#Syntax

Let me know if you are still experiencing an issue with file uploads, and I will be happy to reopen this issue!

**Comment by saeedkhan-github** [comment]
thanks , migration-guide help me to fix my code.
