### ISSUE TITLE
Tests fail if application port is 443 

### ISSUE THREAD

**Issue by superaleks** [cypress-io/cypress#20915]
### Current behaviour

When I test an application on port 443 and protocol HTTP, the tests fail. When I try to do the same behaviour manually using Chrome, the tests behave properly.
If I deploy the application on a **different** port (ex. 9000) the tests will pass in Cypress. 

### Tests
![Issue](https://user-images.githubusercontent.com/47592680/161743102-b93a1227-8870-456b-b1c7-cafc4620bbe8.png)

I took the failing API call and tried to see how it behaves in Cypress and it Chrome.

### Cypress
![Cypress](https://user-images.githubusercontent.com/47592680/161743738-bd702380-580c-43de-a75a-ef2f7c47028b.png)

### Chrome
![Chrome](https://user-images.githubusercontent.com/47592680/161743750-990c41da-6975-4210-94cf-cd8b4251a0db.png)

`cypress.json`

### Desired behaviour

Same behaviour in Cypress as in Chrome browser. 
Tests don't fail just because I am using port 443. 

### Test code to reproduce

[This is the code](https://github.com/superaleks/charts/blob/master/.vib/thanos/queryfrontend/cypress/cypress/integration/thanos_queryfrontend_spec.js)
I don't think the code is the problem. It seems to be something related to port 443, Web Security and same origin policy. 

### Cypress Version

9.3.1

**Comment by superaleks** [comment]
Please note that a similar issue has been created before. [Link to issue](https://github.com/cypress-io/cypress/issues/6572)

**Comment by CaiqueCoelho** [comment]
Hey, @superaleks have you set chromeWebSecurity to false in your cypress.json?

**Comment by superaleks** [comment]
Yes, I've tried this as well, but the behaviour was the same.
