### ISSUE TITLE
Option to save screenshots in cypress/screenshots (As prior to 3.0.2)

### ISSUE THREAD

**Issue by AlbertQM** [cypress-io/cypress#2092]
After the last update (3.0.2), screenshots are nested within a folder with the name of the spec file that is currently running.
An option to revert/choose default behaviour (to pre-3.0.2, i.e. having all the screenshots saved in a single folder) would be great.

I'm running my tests inside a container, and copying its `/cypress/screenshots`  folder to the local machine. This way I can easily check the contents of that folder, which contains all the files I need, and then share them.

The new behaviour makes it trickier to access all the files in their relative paths, hence why I'm opening the issue.

**Comment by brian-mann** [comment]
We recognized that some users would want this feature so in `3.0.2` we also released the `after:screenshot` plugin event which enables you to programmatically control where the screenshot ends up without needing to touch anything in your test code.

I'm closing this issue as we believe this is more than adequate without needing anything hacky.

https://docs.cypress.io/api/plugins/after-screenshot-api.html

Also - just curious if you were aware of this event? We're always interested in better communicating with our users about what it is they can do when new stuff comes out.

**Comment by AlbertQM** [comment]
Thanks for the reply.
I was not aware of that event, nor I was aware of why my script stopped working (until I properly read the whole changelog, since the documentation didn't mention anything as per [#2084](https://github.com/cypress-io/cypress/issues/2084)).

Cypress documentation is always very helpful, and I clearly should've spent more time looking around since the solution was already there; however, as you said, perhaps a better way of communicating what's new/updating the docs as soon as the new features are up and running would be even more amazing.

**Comment by AlbertQM** [comment]
I implemented the after:screenshot plugin, but I still have an issue.

By default, screenshots had a very detailed name e.g.

```describe('my tests', function () {
  it('takes a screenshot', function () {
    // screenshot will be saved as
    // cypress/screenshots/users.spec.js -- my tests -- takes a screenshot.png
    cy.screenshot()
  })
})
```
Now, if I want to change the path with the plugin, e.g.
 
```const newPath = '/Users/user/cypress/screenshots'```

I get EISDIR, this means that I have to specify a file, not a directory in the path property.

Is there a way to retrieve the default name I would get if I wasn't modifying the path?

The close I could get to is using the specName.

```
    const name = (details.specName).replace(/integration\//, ' ').replace(/\.js/, ' ');
    const newPath = `/Users/user/cypress/screenshots/${name}.png`
```

I tried using name property but I get `undefined`.

Thanks in advance.

**Comment by brian-mann** [comment]
@AlbertQM sorry per what you provided there is not enough information to understand what the source of the failure is or what exactly you're trying to do. There should be enough information provided in the object to do whatever it is you want to do with it. You likely just need to use some of node's `path` utils to extract the raw file name of the screenshot and then do whatever it is you'd like to do with it.
