### ISSUE TITLE
Rotating recycle icon is anchored incorrectly in dashboard UI

### ISSUE THREAD

**Issue by micgurro** [cypress-io/cypress#20923]
### Current behavior

Loading spinner is anchored incorrectly in Cypress dashboard and rotates in an orbit.

![864F6775-151E-4E11-BE63-8227F889189B](https://user-images.githubusercontent.com/31846901/161846087-153cfd9f-b8a3-4cc6-b6fb-3cdba5a77dda.jpeg)

### Desired behavior

Anchored so it spins correctly.

### Test code to reproduce

N/A

### Cypress Version

@1

**Comment by benpatterson** [comment]
This issue is resolved; let us know if it's still an issue (or distinctly different than the other referenced ticket below).

Also see #20506
