### ISSUE TITLE
Error - Cannot read property 'aIOf' of undefined

### ISSUE THREAD

**Issue by stanislavche** [cypress-io/cypress#20937]
### Current behavior

Hello Cypress devs.
We have strange behaviour on Jenkins side when we start e2e cypress tests some of test cases randomly fail. 
Example of broken test:
```
TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read property 'aIOf' of undefined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
    at M.get [as readyState] (http://localhost:4200/ruxitagentjs_ICA27Vfgjqrux_10235220309135426.js:456:459)
```
What could be the issue and what is "aIOf"

### Test code to reproduce

On local machine ( MAC, Windows ) it's not reproduce-able.

### Cypress Version

7.1.0

**Comment by Zaista** [comment]
It says that this error originated from your application code, rather than cypress. Have you tried to manually perform those test cases in your app, open browser dev tools console and see if any errors like that appear? Looks like you should be talking to your devs rather than cypress devs :)
