### ISSUE TITLE
Froala (WYSIWYG HTML Editor) does not read correctly the virtual keyboard input of Cypress

### ISSUE THREAD

**Issue by e7d** [cypress-io/cypress#2096]
### Current behavior:
The virtual keyboard inputs does not work as expected, especially regarding the meta keys. In the specific case of the ENTER key, the expected line feed doesn't seem to be outputted at all on the Froala editor.
Considering the example stringto be outputted by Cypress in the Froala Editor:
```
Hello{enter}{enter}{enter}world!
``` 
Then the result is actually looking like this:
![image](https://user-images.githubusercontent.com/1412033/42279283-96b78534-7f9d-11e8-9313-adec92686cac.png)

### Desired behavior:
When running my end-to-end tests with Cypress on a webpage including a Froala editor, the virtual keyboard inputs should behave as a real.
If the test run by Cypress inputs the following string (same as above) in the Froala editor:
```
Hello{enter}{enter}{enter}world!
``` 
I intend to get 3 line feeds between `Hello` and `world!`, producing an inner HTML looking like this:
```
<p>Hello</p><p><br></p><p><br></p><p>world!</p>
```
The result should look like following in an actual webpage:
![image](https://user-images.githubusercontent.com/1412033/42279488-33c8c1f8-7f9e-11e8-86ad-fa3bb0e447d4.png)

### Steps to reproduce:

I made a simple GitHub repository that repoduces the problem live.
1) Clone `https://github.com/jack-in-the-box/froala-vs-cypress.git` with git
2) At the root of the produced folder, run `npm run gui` (this installs the dependencies of Cypress and then, runs its GUI)
3) Click on the `froala.spec.js` link:
![image](https://user-images.githubusercontent.com/1412033/42279968-acb4ba58-7f9f-11e8-8281-07d0296dd8bd.png)
4) Cypress runs the test on Chrome 67 for you
5) The actual routine of the test can be seen on the file `cypress/integration/froala.spec.js`

### Versions

Latest version of Cypress, on Ubuntu, running Google Chrome 67

**Comment by e7d** [comment]
As i don't know which of Froala and Cypress leads to this results, i opened a corresponding ticket here:
https://github.com/froala/wysiwyg-editor/issues/2939

**Comment by Bkucera** [comment]
Hi @e7d This issue will be fixed in an upcoming patch release, along with many other issues in the #1241 epic for `cy.type()` improvements!
