### ISSUE TITLE
Using log in filter returns null

### ISSUE THREAD

**Issue by Luxusio** [cypress-io/cypress#20985]
### Current behavior

Using `cy.log()` in filter returns null.
If I remove `cy.log()` in current code, then test runs normally.

![스크린샷 2022-04-08 오전 10 10 00](https://user-images.githubusercontent.com/44326048/162343640-02d47644-ea48-4bb7-8f47-397673a796f3.png)

### Desired behavior

I want filter would not return null.

### Test code to reproduce

`
cy.get('.todo-list li')
    .filter((idx, e) => {
        cy.log(e);
        return true;
    }).should('have.length', 2);
`

### Cypress Version

9.5.3

### Other

CPU : M1
OS : macOS Monterey (12.3.1)

node -v : v16.13.1

**Comment by geromegrignon** [comment]
In my opinion, the issue relies on API usage: as there is no real filtering, [each](https://docs.cypress.io/api/commands/each) should be used in such a situation.
