### ISSUE TITLE
Cypress: Unable to login into Facebook inside CircleCi

### ISSUE THREAD

**Issue by aasimali** [cypress-io/cypress#20983]
### Current behavior

I have a test scripts which log into the Facebook via UI, and that script works well when I execute it in my local machine, but when I run the same inside CircleCi, its not working, any suggestions?

### Desired behavior

Script should work in local as well as remote environment (CircleCi)

### Test code to reproduce

My repo is private, so can't share it

### Cypress Version

6.8.0

**Comment by emilyrohrbough** [comment]
This appears to be related to the run-mode issue you opened since you should be running in run-mode in CI. Closing as a duplicate of https://github.com/cypress-io/cypress/issues/20988.
