### ISSUE TITLE
Cypress: Facebook:: Unable to login into Facebook using cypress run command

### ISSUE THREAD

**Issue by aasimali** [cypress-io/cypress#20988]
### Current behavior

 I noticed a strange case with cypress, im connecting to Facebook in cypress, and it works well, if I execute "cypress open" but the same case doesn't work if I execute with "cypress run" command, any reason?

### Desired behavior

Ideally it should work with both, cypress open and cypress run 

### Test code to reproduce

It's a private repo

### Cypress Version

6.8.0

**Comment by emilyrohrbough** [comment]
@aasimali Can you provide more information including an example code snippet and the errors you are experiencing?
