### ISSUE TITLE
Dashboard not timeout

### ISSUE THREAD

**Issue by lobor** [cypress-io/cypress#2099]
### Current behavior:
I kill process record on jenkins machine because take screenshot failed and process stuck
You can see on dashboard process run but process killed

![capture d ecran 2018-07-05 a 11 07 54](https://user-images.githubusercontent.com/3316940/42313786-d7d35538-8043-11e8-9e85-af37667fb455.png)

![capture d ecran 2018-07-05 a 11 05 06](https://user-images.githubusercontent.com/3316940/42313631-8041bf3a-8043-11e8-9755-9783af3927fe.png)

### Steps to reproduce:
I don't know how reproduce

### Versions
Cypress 3.0.2

**Comment by brian-mann** [comment]
It will eventually automatically time out.

**Comment by frazboyz** [comment]
@brian-mann How long does it take to timeout? For me they have been stalled for 2 hours now.
