### ISSUE TITLE
OSX Menubar icon doesn't Cmd+drag

### ISSUE THREAD

**Issue by lorennorman** [cypress-io/cypress#21]
I would like to be able to drag the cypress icon to a different position on the menu bar (because I have too many already and my screen is too small sometimes.)

Many applications (especially built-in ones from Apple) allow you to Cmd+Click+Drag to re-organize. I noticed that Cypress does not support this, but thought it might be a trivial bit of polish to drop in.

**Comment by brian-mann** [comment]
Doesn't seem possible at the moment.

https://github.com/nwjs/nw.js/issues/3347

**Comment by brian-mann** [comment]
Closing. Only apps created by apple can do this in OSX.
