### ISSUE TITLE
Intercepting with audio fixture not working after upgrading to v9

### ISSUE THREAD

**Issue by mikaelrss** [cypress-io/cypress#21018]
### Current behavior

I have an application with an `<audio>` element with a `src` attribute, pointing to a remote audio file on `some-audio-url.com`. 

In my tests I have implemented an intercept, which returns a fixture `audio.mp3` whenever requesting a file from the host `some-audio-url.com`. I have done this to always return the same audio file in my tests, and this worked perfectly in v8. After upgrading to v9, this piece of code no longer works, and I get this error message in the console when trying to play the audio. `Uncaught (in promise) DOMException: The element has no supported sources.`
```
cy.intercept(
  "*",
  { hostname: "some-audio-url.com" },
  { fixture: "audio.mp3" }
);
``` 

I see the request to the audio element returning status 200 in the network tab, but my DOM is unable to play the fixture. 

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/26043795/162725910-3053fc3f-5363-4d40-a908-3ff7216b80ad.png">

I am also doing the exact same thing for images, and this works perfectly as expected.

### Desired behavior

I would expect the audio file `audio.mp3` from my fixtures folder, to be loaded into the application, and have playable audio. 

### Test code to reproduce

```
// DOM
<audio data-testid="audio" src="https://some-audio-url.com/myfile.MP3"></audio>

// TEST
cy.intercept(
  "*",
  { hostname: "some-audio-url.com" },
  { fixture: "audio.mp3" }
);


cy.visit("http://localhost:3000");

cy.findByTestId("play-pause").click({ force: true });

cy.contains("00:00:01");
cy.contains("00:00:02");

```

### Cypress Version

9.5.3

**Comment by mikaelrss** [comment]
For some reason, adding `,null` after the fixture name in the intercept it works. From what I can tell, adding `null` will return the fixture as a Buffer. 

```
cy.intercept(
  "*",
  { hostname: "some-audio-url.com" },
  { fixture: "audio.mp3,null" }
);

**Comment by davidmunechika** [comment]
There was a bug in Cypress previously (addressed by https://github.com/cypress-io/cypress/pull/19379 in v9) where the encoding was accidentally non-passive to default to `utf8` where previously it used to be `null` to read it as a buffer. Therefore, I will close this issue since your fix to add `null` is correct and is the expected usage in this situation. Thanks!
