### ISSUE TITLE
"/" is added at end of loaded URLs breaks GET parameters

### ISSUE THREAD

**Issue by samdelong** [cypress-io/cypress#2101]
### Issue
Currently when calling .visit('url'), cypress loads it as url/, which makes the final GET parameter invalid

My cypress.json:
![screenshot from 2018-07-05 11-16-37](https://user-images.githubusercontent.com/20839292/42331984-e6900fd4-8044-11e8-8b41-0c8e89c5c04a.png)

My test.js:
![screenshot from 2018-07-05 11-10-38](https://user-images.githubusercontent.com/20839292/42331745-363e9088-8044-11e8-9e81-71ff75ad65f8.png)

The loaded URL in Cypress

![screenshot from 2018-07-05 11-11-23](https://user-images.githubusercontent.com/20839292/42331746-364c7c48-8044-11e8-8d53-80688aa6b38c.png)

### Desired behavior:

Either don't add the extra character, or possibly add an option for removing it.

### Steps to reproduce:

Screenshots above 

### Versions
Ran on Ubuntu 18.04, using Cypress v3.0.2

**Comment by samdelong** [comment]
In the electron developer console, the request is being sent with the "/", thus making it invalid as the server is expecting it without.

**Comment by brian-mann** [comment]
If you were to visit say `http://example.com` and pop open your dev tools then you'd see the browser making a request to `/` with a host of `example.com`.

Check it out in Chrome + Firefox.

Whenever you make a request that only includes the domain, the browser will automatically add `/` as the pathname. So I'm unsure how this could ever be invalid with your server.

Can you explain what you mean by: "invalid"?

![screen shot 2018-07-05 at 11 35 53 am](https://user-images.githubusercontent.com/1268976/42333071-becf5434-8047-11e8-99b7-daadc52b901a.png)
![screen shot 2018-07-05 at 11 30 40 am](https://user-images.githubusercontent.com/1268976/42333072-bedeccca-8047-11e8-9148-3f4049ffd09c.png)

**Comment by samdelong** [comment]
If you see my first screenshot, I have a GET parameter after example.com/ (https://example.com/?exam=param). The issue is the final GET parameter is send with a "/" at the end, which is invalid because it's a different value than the server is expecting.

**Comment by brian-mann** [comment]
Okay I understand now. It's because you added a param in the `baseUrl`. We aren't expected or parsing that. This is a bug for sure, likely easy fix.

**Comment by samdelong** [comment]
Excellent!

**Comment by bahmutov** [comment]
Real world use cases always are more exciting than our own imagination, great find

**Comment by gautamkrishnar** [comment]
@jennifer-shehane @bahmutov @brian-mann This issue still exists in latest version. I am interested in fixing it. Do we really need to fix this since the **baseUrl** key in cypress.json should only contain top level domain without the param. It doesn't makes sense to me, how can a base url has params in it?

**Comment by jennifer-shehane** [comment]
I'm pretty sure a good deal of the baseUrl logic is contained in this file: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/location.coffee

**Comment by valivvvv** [comment]
@gautamkrishnar many baseUrls can contain url params. Take for instance one page apps, which might pass a sessionId as url param, for example. I can think of hundreds of examples.
