### ISSUE TITLE
`{enter}` not working in Firefox 99 and 100

### ISSUE THREAD

**Issue by Cito** [cypress-io/cypress#21033]
### Current behavior

When sending `{enter}`, this has no effect in Cypress 9.5.4 in Firefox 100, while it did work in Firefox 97.

This had been already reported in #20562 and has been claimed to be fixed in v9.5.4, but it seems that is not the case.

Tested with Firefox Dev 99.0b8 and 100.0b4 (probably same problem with Firefox 98 as well).

### Desired behavior

Sending `{enter}` should work as it did in Firefox 97 and older.

### Test code to reproduce

```js
describe('Hitting enter', () => {
  it('works', () => {
    cy.visit('https://www.duckduckgo.com/');
    cy.get('input#search_form_input_homepage').type('hello{enter}');
    cy.get('div#links_wrapper').should('exist');
  });
});
```

### Cypress Version

9.5.4

**Comment by sainthkh** [comment]
Confirmed that it doesn't work. 

I'm sorry. I first thought that fixing the broken tests would solve the problem. But it seems that it wasn't enough.
