### ISSUE TITLE
Unable to run more than one test in one spec file as page doesn't load properly

### ISSUE THREAD

**Issue by kabhishek0892** [cypress-io/cypress#21039]
### Current behavior

I am hitting login API and then visiting home page every time for my tests. On first attempt, its able to load home page perfectly but from the second test onwards the page doesn't load anymore provided the script is same.

### Desired behavior

It should run all the test and load home page everytime. It was working fine earlier
Tried: 
increasing timeout
clear cache in before each

### Test code to reproduce
```
 beforeEach(() => {
        //cy.exec('npm cache clear --force')
        loginWithEmail(Cypress.env('email'), Cypress.env('password'))
        
    })

  **this works  -->**  it('incomplete request with text message  ', () => {
        cy.intercept("GET", "/home/inCompleteRequest", { fixture: "incomplete-req-text-only.json" }).as('incompleteReq')
        cy.visit('/home/')
        cy.wait('@incompleteReq')
        cy.fixture('incomplete-req-text-only.json').then(req => {
            cy.get('p.tripIdText').should('contain.text', req.data.incompleteRequest.inCompleteReqText)
        })
    })
   **this doesn't work --> **it('incomplete request with empty response  ', () => {
        cy.intercept("GET", "/home/inCompleteRequest", { fixture: "noresultfound.json" })
        cy.visit('/home/')
        cy.get('a[class="cpltItnryWrap"]').should('not.exist')
    })
```
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/36696583/162880268-cd61d389-0cc0-4859-899a-4fe876435988.png">

### Cypress Version

9.5.4

**Comment by davidmunechika** [comment]
> "It should run all the test and load home page everytime. It was working fine earlier"

When you say "it was working fine earlier", do you mean this was working in a previous version of Cypress?

**Comment by kabhishek0892** [comment]
It used to work 4 months back but I tried downgrading to 7.7 and 8.0 but the issues remains the same. Please can you suggest changes as I am completely blocked 
cypress.json file has:
  "baseUrl" :"http://abc:port",
    "pageLoadTimeout": 10000,
    "clientRoute": "/",

**Comment by davidmunechika** [comment]
Is the issue what is provided in the error message in the screenshot? That you are expecting a request to occur but it never is, therefore `cy.wait()` is failing? I'm not sure how to interpret the screenshot here...
