### ISSUE TITLE
`within` does not yield the subject from previous command

### ISSUE THREAD

**Issue by wadjoh** [cypress-io/cypress#2106]
### Current behavior:

I am having trouble with `.within()` and `.should()`. `.within()` seems to yield the last subject that was yielded inside its scope rather than the subject from the previous command.

```javascript
    cy.get('.query-list')
    .within(() => {
      cy.get('li.first');
    })
    // `should` should run assertion against '.query-list'.
    // Instead runs against 'li.first'
    .should('be.visible')
    // `get` should get '#query-btn'
    // Instead tries to get 'li.first #query-btn'
    .get('#query-btn');
```
![screen shot 2018-07-06 at 9 04 37 am](https://user-images.githubusercontent.com/7109607/42388873-be50f620-80fb-11e8-8f6b-a25e6663a155.png)

The `.within()` command yields the `li.first` subject instead of `.query-list`.
And I'm not sure if this is a separate issue, but I found it at the same time: when I run the `.get()` command on `#query-btn` after the `.should()` command, it tries to find `li.first #query-btn`

```javascript
    cy.get('.query-list')
    .within(() => {
      cy.log('inside the `within`');
    })
    // Assertion should run against '.query-list' subject
    .should('be.visible')
    .get('#query-btn');
```
![screen shot 2018-07-06 at 9 07 09 am](https://user-images.githubusercontent.com/7109607/42389136-98b27122-80fc-11e8-9d9b-78e33032e105.png)

In this example, I expected `.should()` to assert that `.query-list` was visible, but it instead receives `null`.

### Desired behavior:
The [docs](https://docs.cypress.io/api/commands/within.html#Yields) state:
> `.within()` yields the same subject it was given from the previous command.

But in my examples it seems to yield the last subject that was yielded from within its own scope.

### Steps to reproduce:

Reproduction repo: [https://github.com/hooskers/cypress-test-tiny](https://github.com/hooskers/cypress-test-tiny)
```bash
npm i
npm run cypress:open
```
Test cases are in `cypress/integration/spec.js`

### Versions

Cypress: 3.0.2
Browser: Chrome 67.0.3396.99
OS: MacOS 10.13.5

**Comment by jennifer-shehane** [comment]
The `within` is behaving the way you described - not according to what the docs say. 

**Reproducible example**
```js
it('get an el', () => {
  cy.visit('http://example.cypress.io')
  cy.get('.banner').within(($banner) => {
    console.log($banner)   // logs .banner el
    cy.get('a').first()
  }).then(($banner) => {
    console.log($banner)    // logs anchor el and not banner
  })
})
```

Now the question is, are the docs inaccurate? Or is the implementation inaccurate? So, we need to make a decision on what would likely be expected to be yielded from a `within` command.

**Comment by BrettHoutz** [comment]
Any update on this? Since `within` is still behaves in this way, perhaps the docs should simply be updated to describe the behavior.
