### ISSUE TITLE
Cypress scrolls to element when page hides overflow and user would not be able to scroll

### ISSUE THREAD

**Issue by sintti** [cypress-io/cypress#21067]
### Current behavior

Currently Cypress scrolls to element when it is out of viewport and page hides overflow. In the below screenshots we have three elements. User can see and reach the yellow button when the screen is big enough. But when it is smaller they can't reach it. In the second case Cypress scrolls to the yellow button and finds it and interacts with it even though the user would not be able to do that.

Yellow button can be seen and interacted with here:
![yellow_button_shown](https://user-images.githubusercontent.com/27669053/163226335-7056cb7e-7e43-433d-a2f1-6d31df8299df.png)

User can't see or interact with the yellow button:
![yellow_button_unreachable_by_user](https://user-images.githubusercontent.com/27669053/163226330-9d140118-e8c6-4cc2-96cd-cc5e2b5e1c5c.png)
 

### Desired behavior

In this situation Cypress should not be able to find and interact with the yellow button when the screen is small because a real user wouldn't be able to do that either. They have no means to scroll to it. This is a problem, because there could be a bug in the page that could put elements outside of reach of user, but Cypress would still find them and be able to interact with them thus we would not be able to find the bug with Cypress.

### Test code to reproduce

HTML:

```
<!DOCTYPE html>
<html>
<style>
.elementBase {
    position: absolute;
    top: 70px;
    width: 60px;
    height: 30px;
}
.button1 {
    background: red;
    left: 20px;
}
.button2 {
    background: green;
    left: 100px;
}
.overlay2 {
    background: blue;
    left: 100px;
}
.button3 {
    background: purple;
    left: 200px;
    visibility: hidden;
}
.button4 {
    background: yellow;
    left: 1000px;
}
.eventDiv {
    top: 110px;
    left: 20px;
    width: 200px;
    
}
body {
    overflow: hidden;
}
</style>
<script>
function changeTextToElement(mytext) {
    document.getElementById('eventDiv').innerHTML = mytext.innerHTML;
}
</script>
<body>
<h1>Validation of test automation</h1>
<div class="elementBase button1" onclick="changeTextToElement(this)">Button1</div>
<div class="elementBase button2" onclick="changeTextToElement(this)">Button2</div>
<div class="elementBase overlay2" onclick="changeTextToElement(this)">Overlay2</div>
<div class="elementBase button3" onclick="changeTextToElement(this)">Button3</div>
<div class="elementBase button4" onclick="changeTextToElement(this)">Button4</div>
<div id="eventDiv" class="elementBase eventDiv">None clicked</div>
</body>
</html>
```

Test cases:
```

describe('Button test', () => {
    it('button1', () => {
      cy.visit('http://localhost:80')
      cy.get('div.elementBase.button1').click();
    });
    it('button2', () => {
      cy.visit('http://localhost:80')
      cy.get('div.elementBase.button2').click();
    });
    it('overlay2', () => {
      cy.visit('http://localhost:80')
      cy.get('div.elementBase.overlay2').click();
    });
    it('button3', () => {
      cy.visit('http://localhost:80')
      cy.get('div.elementBase.button3').debug().click();
    });
    it('button4', () => {
      cy.visit('http://localhost:80')
      //cy.viewport(600, 100)
      cy.get('div.elementBase.button4').click();
      cy.end()
    })
  })
```

### Cypress Version

9.5.4

### Other

This is discussed in documentation: https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Visibility

"Any of its ancestors hides overflow*

    AND that ancestor has a width or height of 0 <-- Why should it have this? If we didn't have this, then it would work properly in this case.
    AND an element between that ancestor and the element is position: absolute
"

**Comment by sintti** [comment]
Happens also with version 9.5.1

**Comment by davidmunechika** [comment]
Thanks for opening an issue! I was able to reproduce using your test code and this appears to be a bug. Feel free to open a contributing PR if you believe you have a potential fix, otherwise we will investigate this and determine the priority of this against other issues.

**Comment by sintti** [comment]
Hi, sorry to bother but I wanted to ask. What is the current state of this issue in the backlog? We tried to mess around with the visibility and scrolling but could not manage to find a fix for this. We would like to move forward with our validation process for test automation and validate Cypress as our tool of choice for test automation but this bug is preventing us from doing that.

**Comment by rihaskh** [comment]
Scrolling is not even working if we change viewport to  cy.viewport(1440,850),
