### ISSUE TITLE
Error only when spec file is exactly named [id].js

### ISSUE THREAD

**Issue by ypresto** [cypress-io/cypress#21065]
### Current behavior

```
touch 'cypress/integration/[id].js'
npx cypress run --spec 'cypress/integration/\[id\].js'
```

```
Oops...we found an error preparing this test file:

  > cypress/integration/[id].js

The error was:

Error: ENOENT: no such file or directory, stat '/Users/.../Library/Application Support/Cypress/cy/production/projects/.../bundles/cypress/integration/[id].js'



This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies
```

### Test code to reproduce

(Wrote in current behavior)

### Cypress Version

9.5.4

### Other

It is very corner case, but if someone names spec files to match Next.js dynamic route files, it can cause this error.
(I'm using macOS 12.3.1 .)

**Comment by curtaincall888** [comment]
> It is very corner case, but if someone names spec files to match Next.js dynamic route files, it can cause this error.

I’m encountering the exact same case.
In my case, the file name is `[name].spec.js`.
`version "9.6.0"`
