### ISSUE TITLE
Unable to download cypress

### ISSUE THREAD

**Issue by ToddRB** [cypress-io/cypress#21073]
### Current behavior

When I attempt to download cypress, it stops at 37%. 

I have several test agents that are running tests via pipelines and the install cypress task times out on these machines. 
Using this link here I am able to reproduce 'manually' so to speak. 
https://cdn.cypress.io/desktop/9.5.1/win32-x64/cypress.zip

I am able to download via this link on other machines, but not my test agents. 
It simply stops - no error. If I try to close the browser it thinks I still have pending downloads. 

![image](https://user-images.githubusercontent.com/5262597/163262786-2ec85210-be0b-427c-86c6-1d6b70265ae7.png)

I've done some troubleshooting with IT on my side and there does not appear to be any mechanism causing the failure. 
Is it possible that my machines are being stopped

### Cypress Version

9.5.1

### Package Manager

npm

### Operating system

Windows

### Other

I've got 18 test agents as VMs. I'm wondering if perhaps there are so many downloads of cypress, that some mechanism on the cypress side is throttling my connection.

**Comment by ToddRB** [comment]
> I have the same issues (some agents can't download Cypress while others can):
> 
> ```
> [FAILED] The Cypress App could not be downloaded.
> [FAILED] 
> [FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
> [FAILED] 
> [FAILED] Otherwise, please check network connectivity and try again:
> [FAILED] 
> [FAILED] ----------
> [FAILED] 
> [FAILED] URL: https://download.cypress.io/desktop/9.6.1?platform=linux&arch=x64
> [FAILED] Error: Failed downloading the Cypress binary.
> [FAILED] Response code: 524
> [FAILED] Response message:
> [FAILED] 
> [FAILED] ----------
> [FAILED] 
> [FAILED] Platform: linux-x64 (Ubuntu - 20.04)
> [FAILED] Cypress Version: 9.6.1
> The Cypress App could not be downloaded.
> 
> Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
> 
> Otherwise, please check network connectivity and try again:
> 
> ----------
> 
> URL: https://download.cypress.io/desktop/9.6.1?platform=linux&arch=x64
> Error: Failed downloading the Cypress binary.
> Response code: 524
> Response message:
> ```

FYI, our solution was just to target a different version. In this case, 9.5.4. If this issue occurs again, where the 9.5.4 download fails, my hope is that there will be a newer version link we can use haha.

**Comment by DamienCassou** [comment]
> Does your workplace require a proxy to be used to access the Internet?

No proxy is required and, as I said, it works for most agents.

**Comment by SantiagoCL** [comment]
Same issue here, trying to install Cypress 10.7
