### ISSUE TITLE
Number input doesn't increment on .type({uparrow})

### ISSUE THREAD

**Issue by hally9k** [cypress-io/cypress#2110]
### Current behavior:

`.type({uparrow})` doesn't increment the number input.
Additionally I cannot `invoke('stepUp')` either.

### Desired behavior:

Increments the number input's value on `.type({uparrow})` and `invoke('stepUp')`.

### Steps to reproduce:

https://github.com/hally9k/cypress-test-tiny
Clone this fork, `npm install` and `npm start`

### Versions

macOS 10.13.5
Cypress 3.0.2

**Comment by Bkucera** [comment]
@hally9k hi, `invoke()` calls jQuery functions, so that may be why `stepUp` is failing. Try this:
`cy.get('.numInput').then(($el)=>$el.get(0).stepUp())`

**Comment by hally9k** [comment]
@Bkucera Thanks for that, clearly skimmed that part of the docs a little too hastily. Any insight on why the `.type({uparrow})` case isn't working?

**Comment by jennifer-shehane** [comment]
@hally9k Are you writing the command using quotes? The `{uparrow}` should be in quotes like this:

```js
.type('{uparrow}')
```

**Comment by hally9k** [comment]
@jennifer-shehane Sorry this is a typo in the comments here, see the repro:
https://github.com/hally9k/cypress-test-tiny/blob/bbe451faf33e49536576749a88526566a403fecd/cypress/integration/spec.js#L14

**Comment by Bkucera** [comment]
This should be fixed in an upcoming patch release, {uparrow} will be fixed to increment number/date inputs , and move cursor on contenteditables and textareas

**Comment by eireland** [comment]
Has this been released? Using 3.4.1 and still can't get .type('{uparrow}') to increment number input.

**Comment by Bkucera** [comment]
@eireland yes, see the test here that verifies that https://github.com/cypress-io/cypress/blob/simulated-type-fixes/packages/driver/test/cypress/integration/commands/actions/type_spec.js#L2184

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved in Cypress 3.0.3 and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
