### ISSUE TITLE
Type command brackets logic adds weird limitations

### ISSUE THREAD

**Issue by douweknook** [cypress-io/cypress#2111]
### Is this a Feature or Bug?
Feature suggestion 

### Current behavior:
In the app I'm adding cypress tests for we have inputs that accept "variables". Users can add a variable by type encapsulating a variable in bracket like `{{variable}}`. However, when I try to type this using Cypress' `type()` method it throws an error because the special character sequence is not recognized.

![schermafbeelding 2018-07-09 om 12 48 34](https://user-images.githubusercontent.com/3264754/42446419-71b1f8fa-8376-11e8-9990-ebc7ae5f14e0.png)

### Desired behavior:
Preferably it should be possible to disable listening for the command and just input whatever I tell `type to input. An alternative option would be to white-list the commands Cypress does support but still accept inputs that do not match any of those commands.

### Steps to reproduce:
To reproduce I suppose get an input element, grab it and try to input anything wrapped in `{{}}`.

For now my approach is to add a custom type command that just sets the input' value and emits an input event but this adds some overhead which ideally would not be needed

**Comment by chrisbreiding** [comment]
You can [type a literal `{` with `{{}`](https://docs.cypress.io/api/commands/type.html#Arguments). To type `{{variable}}`, you would do: `cy.type('{{}{{}variable}}`.

**Comment by douweknook** [comment]
Aah I see. Makes sense now. Thanks for the quick response! My bad!

**Comment by benwiley4000** [comment]
Could we get a new `option` to pass in that disables the control sequences? It makes it kind of confusing to read tests when we have `{{}` all over the place.

**Comment by Pachat** [comment]
As of 9.6.0, 
>cy.type('{{}{{}variable}}')

doesn't work, whatever parseSpecialCharSequences is set to `true` or `false`.
Curly braces are skipped.
