### ISSUE TITLE
offline installation does not succeed with cypress.zip on windows

### ISSUE THREAD

**Issue by geyuqiu** [cypress-io/cypress#21126]
### Current behavior

https://download.cypress.io/desktop/3.0.0/win32-x64/cypress.zip

offline installation stops at 80% percent when doing 

`CYPRESS_INSTALL_BINARY=/local/path/to/cypress.zip npm install cypress -g --loglevel verbose`

### Debug logs

npm ERR! [TITLE]  Unzipping Cypress        80% 40s
npm ERR! The Cypress App could not be unzipped.
npm ERR!
npm ERR! Search for an existing issue or open a GitHub issue at
npm ERR!
npm ERR! https://github.com/cypress-io/cypress/issues
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Error: ENOENT: no such file or directory, realpath 'C:\Users\****\AppData\Local\Cypress\Cache\9.5.4\Cypress\resources\app\packages\server\node_modules\npm\node_modules\update-notifier\node_modules\bo
xen\node_modules\ansi-align\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan'
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Platform: win32-x64 (10.0.17763)
npm ERR! Cypress Version: 9.5.4
npm ERR! [FAILED] The Cypress App could not be unzipped.
npm ERR! [FAILED]
npm ERR! [FAILED] Search for an existing issue or open a GitHub issue at
npm ERR! [FAILED]
npm ERR! [FAILED] https://github.com/cypress-io/cypress/issues
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] Error: ENOENT: no such file or directory, realpath 'C:\Users\910739\AppData\Local\Cypress\Cache\9.5.4\Cypress\resources\app\packages\server\node_modules\npm\node_modules\update-notifier\node_m
odules\boxen\node_modules\ansi-align\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan'
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] Platform: win32-x64 (10.0.17763)
npm ERR! [FAILED] Cypress Version: 9.5.4

### Cypress Version

9.5.4

### Package Manager

npm

### Operating system

Windows

### Other

- checked .npmrc is valid
- checked local path of cypress zip is valid
- the offline installation already worked on my machine 2 months ago, but did not work on this one from my colleague

**Comment by davidmunechika** [comment]
Possibly related to https://github.com/cypress-io/cypress/issues/19655

**Comment by davidmunechika** [comment]
Could you try upgrading your node version and see if you are still experiencing this problem?

**Comment by geyuqiu** [comment]
it is working without -g, so I tip that update notifier utilizes some updates that requires some permissions
