### ISSUE TITLE
Create a test for each item of a loop

### ISSUE THREAD

**Issue by antonioaltamura** [cypress-io/cypress#21129]
### What would you like?

I would like to create a test for each element of a list on a page. That would be the only way to actually track what item fails.

```
describe("loop test", () => {
        cy.get("li").each(el => {
            const id = el.attr("id");
            it(`loop test for ${id}`, () => {
                cy.get("#" + id).should("exist").click();
                // other async (remote) operations
                cy.wait(2000);
            });
        });
    });
```
This block won't work as you will get the error:
`You will get an error "Cannot call cy.get() outside a running test."`

You can't nest `it` blocks and you can't use `cy.get` or `cy.wrap` in `describe()` blocks.
Is there a plan to support any of this, or, even better, is there a known workaround?

### Why is this needed?

Better control on lists. There is no other way to have a test for each item of a list, therefore there is no way to tell what item the test failed on.

**Comment by geromegrignon** [comment]
> It is common for tests in Cypress to issue 30+ commands.

I challenge you to test all items in a single test: https://docs.cypress.io/guides/references/best-practices#Creating-tiny-tests-with-a-single-assertion
