### ISSUE TITLE
Changing the visited page's location before onload event will make Cypress timeout

### ISSUE THREAD

**Issue by warpdesign** [cypress-io/cypress#21130]
### Current behavior

It seems that when the page being visited by Cypress attempts to change the location before the load event is triggered, Cypress will then wait forever for the load event, even after the new page has been fully loaded (maybe it waits for the first page to fire the load event ?).

### Desired behavior

Cypress shouldn't timeout when being redirected to a new page.

### Test code to reproduce

Page that's being visited:

```html
<!DOCTYPE html>
<html>
    <script type="text/javascript">
        // changing the page's location before the page has been loaded will make Cypress timeout
        // visiting the next page
        window.location.replace('https://warpdesign.fr/tests/another/')
    </script>
    <body>
        Redirect Test
    </body>
</html>
```

This simple test will trigger a timeout error when visiting the above page:

```js
/// <reference types="cypress" />
describe('page', () => {
  it('triggers a timeout error', () => {
    cy.visit('/index2.html')
  })
})
```

I made a repo to reproduce the problem: https://github.com/warpdesign/cypress-test-redirect-before-onload

- `timesout.spec.js`: the visited page updates `document.location` before the page has been loaded -> cypress times out
- `works.spec.js`: the visited page updates `document.location` after the page has been loaded -> no timeout

### Cypress Version

9.5.4

### Other

Also happens in 9.5.1

**Comment by romankhomitskyi** [comment]
Also experiencing  this issue

**Comment by sainthkh** [comment]
With 9.6.0, the error message has been changed to:

> Blocked a frame with origin "https://warpdesign.github.io" from accessing a cross-origin frame.
