### ISSUE TITLE
cypress.get(element) fails without waiting or retrying

### ISSUE THREAD

**Issue by dan19** [cypress-io/cypress#2113]
### Current behavior:

The `cypress.get(element)` function fails without waiting or retrying if the element is not visible on the page.

### Desired behavior:

The `cypress.get(element)` function should wait and find the dom element in the page or timeout after the default timeout if the element is not visible in the page.

### Steps to reproduce:

Non-working code:
```js
describe('Starts a chat conversation', () => {
  describe('When visiting /chat ', () => {
    it('creates a new chat and the the chat bot starts sending messages', () => {
      cy.loginAs(clientWithMembership); // custom command that execute an http call

      const url = getChatUrl();
      cy.visit(url);
      cy.get('div[data-cy=chat-message-container]').should('have.length', 1); // Fails without waiting
    });
  });
});
``` 

Working code: (adding a wait before checking if the element exists)
```js
describe('Starts a chat conversation', () => {
  describe('When visiting /chat ', () => {
    it('creates a new chat and the the chat bot starts sending messages', () => {
      cy.loginAs(clientWithMembership); // custom command that execute an http call

      const url = getChatUrl();
      cy.visit(url);
      cy.wait(3000);
      cy.get('div[data-cy=chat-message-container]').should('have.length', 1);
    });
  });
});
```

### Versions

Cypress: 3.0.1
Mocha: 4.0.1
Browser: Chrome

**Comment by justinwhall** [comment]
Curious, does your test fail and return:

```
...failed because it requires a DOM element.

The subject received was:

  > undefined
```

**Comment by dan19** [comment]
The assert fails with the message: 
`expected '' to have a length of 1 but got 0`

**Comment by jennifer-shehane** [comment]
@dan19 It does appear from the information provided that Cypress attempted to retry for the duration of the timeout (4000ms), and did not find the DOM selector to have a length of 1. Could you try increasing the timeout of the actual `get` to see if this helps?

```
cy.get('div[data-cy=chat-message-container]', {timeout: 7000}).should('have.length', 1);
```

Also, make sure you are following some of our recommendations on waiting for you app to load before getting an element in your tests. https://on.cypress.io/using-cypress-faq#How-do-I-wait-for-my-application-to-load

**Comment by dan19** [comment]
@jennifer-shehane thanks for your answer. I've tried that already and it doesn't even wait a second when I passing in the timeout option.

**Comment by brian-mann** [comment]
Can you provide a screenshot and/or video

**Comment by dan19** [comment]
@brian-mann @jennifer-shehane I believe my issue has to do with the fact that when I go to `/chat` then it redirects to `/chat/create` and then `/chat/<id>`. This is after this last redirection that the element would be available.
Do you think that is this issue and if so how to fix that?
I read the documentation but can not figure it out.

**Comment by jennifer-shehane** [comment]
@dan19 Could you try a `cy.visit()` directly to the `/chat/<id>` url and see if it happens?

**Comment by MCTaylor17** [comment]
It seems like the challenge is waiting for `/chat/<id>` despite an intermediate call to `/chat/create`. 
I'm curious if this would this work:

```js
cy.server();
cy.route("/chat/!(create)").as("anythingButCreate");
cy.visit(url);
cy.wait("@anythingButChat")
cy.get('div[data-cy=chat-message-container]').should('have.length', 1);
```
I'm new to Cypress and don't use negated globbing patterns very often, so I could be missing something. 

If the above does work, you could make it more robust by aliasing a route using the specific `<id>` or a regex pattern to avoid the negation.  That way, if `create` ever changes or other intermediary calls are introduced, it won't fire off prematurely.

**Comment by jennifer-shehane** [comment]
Hey @dan19, did you find a solution to your issue?

**Comment by mikhaildzarasovvineti** [comment]
I do have the the problem, its not waiting even a second and failing. Waiting for api response wont help if you have a long list of data to render. Api got 200 response but react takes time to render huge amount of data from response. Any suggestions how to wait until element is presented?

**Comment by jennifer-shehane** [comment]
@mikhaildzarasovvineti If you want to purely wait for an element to be present on the page, you can increase the timeout that Cypress waits for an element to be present. `cy.get('button', {timeout: 60000}`.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by ryan-m-williams** [comment]
I've run into something similar.. I simply prepend be.visible assertion and the timeout is applied.

i.e. cy.get('element').should('be.visible').and('some.assertion')

**Comment by D0rmouse** [comment]
For me, upgrading to Cypress 4.4.0 caused this issue. I've found an answer on Stackoverflow to waitForAngular similar to Selenium: https://stackoverflow.com/a/58706928/883603
It fixed the element nog being present in the DOM when Cypress starts to assert for me.

**Comment by laDanz** [comment]
I don't know if its the same issue, but i am confused about this behaviour:
A get with an empty result set:
`cy.get('div.recipe[recipeid]:visible').should("have.length", 1)`
results in:
![image](https://user-images.githubusercontent.com/166216/96176703-fba7fc00-0f2c-11eb-9c87-e2e0818ae1f4.png)
and i would expect that this would fail.

**Comment by jennifer-shehane** [comment]
@laDanz Please open a new issue with a fully reproducible example. This should have.

**Comment by lucidity-joe** [comment]
I've been using cypress for half a year now and I can honestly say I have not once seen cy.get() wait for the default timeout I have set it - not even once. It frequently comes back saying the element doesn't exist, when a get is run immediately after a page load. It does not wait at all. If you like I can try to come up with a generic example?

**Comment by bahmutov** [comment]
@lucidity-joe please give us an example showing `cy.get` immediately failing without retrying for the default command timout.

**Comment by lucidity-joe** [comment]
@bahmutov Unfortunately all my code is full on manual waits now because it hasn't been working. Next time it happens I'll be sure to put the details here.

**Comment by QuentinDouarre** [comment]
I have the same problem, I fixed it by putting code in support/commands.js

```
Cypress.Commands.overwrite('get', async (originalFn, selector, options) => {
  if(Cypress.browser.family !== 'firefox') {
    await ((ms = 1500) => (new Promise((resolve) => (setTimeout(resolve, ms)))))()
  }
  return originalFn(selector, options)
})
```
