### ISSUE TITLE
Crash if a "describe" block does not have a callback function

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2115]
reproduction in https://github.com/cypress-io/cypress-test-tiny branch `empty-describe`
- https://github.com/cypress-io/cypress-test-tiny/commit/63a6828b1e37a8895272fc36beaeaf7f986b49a9

Whenever `describe` has just a function, or just a name (without a callback function) Cypress (probably Mocha engine inside) dies a violent death. Both these crash with `Uncaught TypeError: Cannot read property 'call' of undefined`

```js
describe(function page() {})

describe('nope')
```

<img width="1279" alt="screen shot 2018-07-10 at 2 43 07 pm" src="https://user-images.githubusercontent.com/2212006/42510656-e82b90a2-844f-11e8-9817-c803b8d557da.png">

Code at crash site

```js
context.describe = context.context = function(title, fn) {
  var suite = Suite.create(suites[0], title);
  suite.file = file;
  suites.unshift(suite);
  fn.call(suite);
  suites.shift();
  return suite;
};
```

Note that tests without a callback function are fine, they are just pending, so `it('works')` has no problems.

- Cypress 3.0.1
- Mac

**Comment by lilaconlee** [comment]
Took a stab at a more specific error message instead of fixing to keep the same behavior as mocha:
<img width="506" alt="screen shot 2019-03-05 at 3 39 46 pm" src="https://user-images.githubusercontent.com/7514489/53839545-6f1a1700-3f5d-11e9-989d-7f84874517de.png">

Down to set the suite to pending if that's preferred.

**Comment by jennifer-shehane** [comment]
I confirmed this bug is still happening in Cypress 3.8.0

**Comment by jennifer-shehane** [comment]
This fails with a much better error - testing in Cypress 6.2.1. Closing as resolved. 

<img width="648" alt="Screen Shot 2021-01-05 at 5 54 24 PM" src="https://user-images.githubusercontent.com/1271364/103640852-27141300-4f7f-11eb-8cd2-bc420a64be08.png">
