### ISSUE TITLE
Error: The 'task' event has not been registered in the plugins file. You must register it before using cy.task()

### ISSUE THREAD

**Issue by VaghasiyaKrupal** [cypress-io/cypress#21153]
### Current behavior

I have this code in my `plugins/index.js` file.
```
module.exports = (on, config) => {
on("task", { "setUserId": (val) => { return (userId = val); }});
};
```
And in my test, I have used this way.
`cy.task('setUserId', randomEmail);`

I got this error. 
![image](https://user-images.githubusercontent.com/45596703/164310585-baf9215e-6804-4286-aafd-04547ce17723.png)

Before my test worked fine with this implementation, but now I am receiving this error. I have searched a lot but have not to find a solution.

### Test code to reproduce

Put this in `plugins/index.js`
```
module.exports = (on, config) => {
on("task", { "setUserId": (val) => { return (userId = val); }});
};
```
Use this in the test `cy.task('setUserId', randomEmail);`

### Cypress Version

9.5.4

**Comment by davidmunechika** [comment]
> Before my test worked fine with this implementation, but now I am receiving this error. I have searched a lot but have not to find a solution.

Do you know what version of Cypress were you using before when this implementation worked?

**Comment by VaghasiyaKrupal** [comment]
@davidmunechika Unfortunately I don't know that.

**Comment by davidmunechika** [comment]
Can you double check your code in the plugins file and make sure it matches the task signature here: [on.cypress.io/task#Usage](https://on.cypress.io/task#Usage)

Also could be worth double checking that your plugins file is building and compiling correctly

**Comment by davidmunechika** [comment]
This past issue has some proposed solutions for this problem: do any of these work for you?

https://github.com/cypress-io/cypress/issues/3198

**Comment by VaghasiyaKrupal** [comment]
@davidmunechika I have these 3 tasks registered in my plugin file.
```
on("task", {
    "gmail:get-messages": async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json"),
        args.options
      );
      console.log(messages);
      return messages;
    }
  });

  on("task", { "setUserId": (val) => { return (userId = val); }});

  on("task", {"getUserId": () => { return userId; }});
};
```

**Comment by KrupalVaghasiya** [comment]
@davidmunechika Any solution on this?

**Comment by davidmunechika** [comment]
Unfortunately, I'm not able to reproduce your issue with the test code you provided. This might be an issue outside of your plugins file. Would you be able to provide a demo repo by any chance that we could use to reproduce this issue?

<img width="1780" alt="Screenshot 2022-04-25 at 10 14 45 AM" src="https://user-images.githubusercontent.com/27690333/165107283-fc381d4b-faae-448a-88bc-0e4bc77f8971.png">

**Comment by VaghasiyaKrupal** [comment]
@davidmunechika please clone `https://github.com/VaghasiyaKrupal/cucumber-issue.git` this repo and install all the dependencies and after run the `signup.feature` and `login.feature` files for different registered task.

**Comment by KrupalVaghasiya** [comment]
@davidmunechika Any update on this issue?

**Comment by VaghasiyaKrupal** [comment]
@davidmunechika Any update on this issue?

**Comment by davidmunechika** [comment]
Apologies for the delayed response @VaghasiyaKrupal. I tried to clone your example repo but it appears to be a private repository. Could you make this repo public so I can try and reproduce your issue? Thanks!

**Comment by KrupalVaghasiya** [comment]
@davidmunechika Please try not I have made it public.

**Comment by VaghasiyaKrupal** [comment]
@davidmunechika Please try now, i have made it to public.

**Comment by davidmunechika** [comment]
You have two `module.exports` declarations in your `index.js` plugins file which is why your task events aren't being recognized as registered:

```js
module.exports = (on, config) => {
  on("task", {
    "gmail:get-messages": async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json"),
        args.options
      );
      console.log(messages);
      return messages;
    }
  });

  on("task", { "setUserId": (val) => { return (userId = val); }});

  on("task", {"getUserId": () => { return userId; }});
};


const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}
```

You should condense your `module.exports` into a single declaration:
```js
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())

  on("task", {
    "gmail:get-messages": async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json"),
        args.options
      );
      console.log(messages);
      return messages;
    }
  });

  on("task", { "setUserId": (val) => { return (userId = val); }});

  on("task", {"getUserId": () => { return userId; }});
};
```

**Comment by KrupalVaghasiya** [comment]
@davidmunechika yeah, it will work now, amazing. Thank you.

**Comment by VaghasiyaKrupal** [comment]
@davidmunechika its work fine but test is ganging in between run.

**Comment by mjhenkes** [comment]
I see you've opened up a new issue #21353, we'll continue the discussion there
