### ISSUE TITLE
Unable to connect to chrome when providing --remote-debugging-port

### ISSUE THREAD

**Issue by MGana** [cypress-io/cypress#21167]
### Current behavior

When providing `--remote-debugging-port` in `launchOptions ` arguments , Cypress is no more able to connect to chrome
and the message `Still waiting to connect to Chrome, retrying in 1 second (attempt 19/62)` is displayed
```
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.name === 'chrome') {
      launchOptions.args.push(
        '--remote-debugging-port=9222',
        '--disable-background-timer-throttling',
      );
    }
    return launchOptions
  })
```
<img width="367" alt="image" src="https://user-images.githubusercontent.com/21100403/164492796-a33fc44d-335a-4772-8d85-f909392ebba9.png">

When removing the line` '--remote-debugging-port=9222',`  , it works !

### Desired behavior

Cypress able to connect to chrome when providing `'--remote-debugging-port=9222',`

### Test code to reproduce

Any basic cypress install, with the above changes in `plugins/index.js`

### Cypress Version

9.5.4

### Other

Node: v16.13.2

**Comment by yogeshgadge** [comment]
Its happening to me too v9.6.0

I need to debug 'cypress run' because it fails what succeeds in 'cypress open'.
Not being able to debug is a big issue in trying to use cypress.

**Comment by MichaelRobsonSliide** [comment]
I'm getting the same in Cypress 10.3.0

**Comment by Songyu-Wang** [comment]
can confirm this issue on 10.7.0

**Comment by daminebenq** [comment]
This is a persistant issue...
The port number keeps on changing at every new execution.
even using the following, didn't change it: 
```
    launchOptions.args.push('--remote-debugging-port=9222');
    launchOptions.args.push('--remote-debugging-address=127.0.0.1');
```

any help?

current versions: `10.3.0` and even `10.8.0`

**Comment by bartonhammond** [comment]
Since setting the debug port doesn't stick, I just used the one that was set:
```
         let index = launchOptions.args.findIndex((s) =>
            s.includes("--remote-debugging-port")
          );
          debugPort = launchOptions.args[index].split('=')[1];
```
Then later in a "task" I could do 
```
        let result = require("child_process") .execSync(`curl http://127.0.0.1:${debugPort}/json/list`)
```
which prints:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   486  100   486    0     0   307k      0 --:--:-- --:--:-- --:--:--  474k
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=127.0.0.1:53214/devtools/page/98FEAF9C93C3C2A9048E8DE9B8632D09",
   "id": "98FEAF9C93C3C2A9048E8DE9B8632D09",
   "title": "smc-cypress",
   "type": "page",
   "url": "http://localhost:53210/__/#/specs/runner?file=cypress\\integration\\caseProcessing\\financial\\agedTrialBalanceReport.feature",
   "webSocketDebuggerUrl": "ws://127.0.0.1:53214/devtools/page/98FEAF9C93C3C2A9048E8DE9B8632D09"
} ]
```
and now able to run
