### ISSUE TITLE
Firefox specific TypeError `el is null`

### ISSUE THREAD

**Issue by alexniculae** [cypress-io/cypress#21162]
### Current behavior

- when running the Cypress tests stack in Firefox (cannot replicate on Chrome)
- TypeError `el is null` occurs when trying to interact with an element (e.g. on commands `click`, `type`)
- happens on both Windows and Linux machines

A stack trace of the error:
```
TypeError:
el is null
     getTagName cypress_runner.js:183770:19
     isInput cypress_runner.js:183785:10
     onEvent cypress_runner.js:154920:128
     fireSimulatedEvent cypress_runner.js:165288:13
     simulatedKeydown cypress_runner.js:165434:66
     typeSimulatedKey cypress_runner.js:165458:10
     ../driver/src/cy/keyboard.ts/type/typeKeyFns</< cypress_runner.js:165128:14
     ../driver/src/cy/keyboard.ts/type/< cypress_runner.js:165138:64
```

Attached a sample of the cypress_runner file, for lines 183742 until 183835, to help with debugging where the error is coming from.

[cypress_runner.txt](https://github.com/cypress-io/cypress/files/8528954/cypress_runner.txt)

Firefox versions tested on: 99

### Cypress Version

9.5.4

**Comment by davidmunechika** [comment]
Do you have a reproducible code example that causes this error on Firefox?

**Comment by alexniculae** [comment]
@davidmunechika ,

For the most basic Cypress project, with:
- Cy versions 9.5.4 || 9.6.0
  - issue was not reproducible on 8.5.0 (can be validated with below code)
  - not sure at what version it started to occur
- issue will occur only on Firefox (no problems on Chrome or Electron)
  - reproduced on versions 99 and 100
  - not sure if reproducible on previous versions
 
```
// cypress.json

{
    "includeShadowDom": true
}
```
```
// firefox-issue.spec.js

describe('Firefox el is null issue', () => {
  beforeEach(() => {
    cy.visit('https://mwc-demos.glitch.me/');
  });

  it('type into web component textarea', () => {
    cy.get('.mdc-text-field__input').eq(0).type('text');
  });

  it('type into web component textfield', () => {
    cy.get('.mdc-text-field__input').eq(2).type('text');
  });
});
```

------
![image](https://user-images.githubusercontent.com/64204907/166718344-46b76d1a-f4cf-4c3d-aa60-a0b7d0fdfec0.png)

To let you know, these sort of `TypeError: **some-element** is null` is occurring in quite a lot of situations when using Cypress(latest versions) with Firefox(latest versions) to test an apps that contains web-components.

**Comment by alexniculae** [comment]
@davidmunechika, any update on this, please?

**Comment by rodriguesgio** [comment]
@alexniculae @davidmunechika I'm having this issue on Firefox 100, any update/workaround?
