### ISSUE TITLE
Qestion: Instant XHR response using .route()

### ISSUE THREAD

**Issue by Ancinek** [cypress-io/cypress#2117]
### Current behavior:

I have a fixture that I want to pass as `response` attribute in `route` options. It works great, but the original request to my server takes 3 seconds. Then I get the fixture back (when this request is finished).

### Question

Is it possible to make this thing go instantaneous?  So I make the request and the cypress server responds with a fixture instead of my server doing this thing?

**Comment by Ancinek** [comment]
Sure!

I have a login command that looks like this:

```javascript
const defaultCredentials = { email: 'admin@example.com', password: 'test1234' };
Cypress.Commands.add('login', (credentials = defaultCredentials) => {
  cy.request({
    method: 'POST',
    url: '/authentication/login/',
    form: true,
    body: credentials,
  }).then(({ body }) => {
    cy.setCookie('jwt', body.token);
  });
  provideFixture('autocompletes', '/autocompletes/');
});
```

My `provideFixture` method looks like this:

```javascript
const provideFixture = (name, url) => {
  cy.server();
  const filePath = `cypress/fixtures/${name}.json`;
  const alias = `fixture_${name}`;
  cy.task('checkFixtureExistance', name).then((exists) => {
    if (exists) return;
    cy.request(url).then(({ body }) => {
      cy.writeFile(filePath, body);
    });
  });
  cy.route(path, `fixture:${name}.json`).as(name);
};
```

The `checkFixtureExistance` task was written in `cypress/plugins/index.js`:

```javascript
const fs = require('fs');
const appRootDir = require('app-root-dir');

module.exports = (on, config) => {
  on('task', {
    checkFixtureExistance: (name) => {
      const rootPath = appRootDir.get();
      const filePath = `${rootPath}/cypress/fixtures/${name}.json`;
      return fs.existsSync(filePath);
    },
  });
};
```

The request to `/autocompletes/` takes now 3 seconds. (note: tt is being worked on to improve this time and have the autocompletes split up into few ones, but this will be ready and tested probably in 5-7 days).

For now I have to wait for this request to finish and then I get my fixture. The desired behavior (for me at least) would be to get this response instantaneous so:
1. My app makes the request to a desired endpoint
2. Cypress sees that this route is supposed to have mocked response
3. It responds instantly with the fixture data.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
