### ISSUE TITLE
cy.contains finds text in invisible tags

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2119]
`cy.contains` finds text in `<head>` and  `<style>` tags, which do in fact have `.textContent` properties, but aren't visible.

For example:
![image](https://user-images.githubusercontent.com/14625260/42525927-72db2892-8442-11e8-9402-7ad4a9623b30.png)
![image](https://user-images.githubusercontent.com/14625260/42525989-95f85e58-8442-11e8-8f85-bfc37d69c429.png)

**Comment by sainthkh** [comment]
@Bkucera Is this issue fixed in #5079?

**Comment by Bkucera** [comment]
@sainthkh nice catch, yes :+1:
