### ISSUE TITLE
Visiting an https ip address can cause Chrome to refuse to display contents

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#212]
In this example we are visiting:

``` javascript
cy.visit("https://52.11.216.129")
```

Once Cypress swaps the domain Chrome will refuse to display the contents:

![screen shot 2016-09-06 at 12 24 23 am](https://cloud.githubusercontent.com/assets/1268976/18261635/6e56317c-73c8-11e6-993a-3fd54b02ad7c.png)

Using node's `request` module or `curl` works just fine, so we'll have to look into why exactly Chrome isn't happy about the cert Cypress provided.

What's strange is that we can modify `/etc/hosts` and insert this line:

``` bash
52.11.216.129 dev.foobar.com
```

And now our `cy.visit` will work. This leads me to believe its a problem specifically with certificates generated for ip addresses and not fully qualified hosts.

``` javascript
cy.visit("https://dev.foobar.com") // yay this works now
```

**Comment by jennifer-shehane** [comment]
This was fixed a long time ago - we have tests for this. If you're experiencing a similar issue, please open a new issue.
