### ISSUE TITLE
Incorrect DOM snapshot

### ISSUE THREAD

**Issue by Glacian22** [cypress-io/cypress#21209]
### Current behavior

Having Cypress click on a select dropdown element shows the wrong selection when reviewing the DOM snapshots by hovering over the command log.

### Desired behavior

The DOM snapshot should be correct.

### Test code to reproduce

https://github.com/Glacian22/Cy-dropdown-error

Run the only spec file, "kronk.spec.js", which contains a single test. It has Cypress get the "select" element, select "Kronk", and then continue the test. This works, but when hovering over the command log to look at the DOM snapshots, it shows the other option in the select dropdown, "Llama", as having been selected.

### Cypress Version

9.0, and 9.60

**Comment by AtofStryker** [comment]
Likely a duplicate of #4443

**Comment by AtofStryker** [comment]
> #21214
@emilyrohrbough I think it's a different issue. #21214 almost looks like its applying the `data-cypress-el`  attribute in places it might not supposed to be?
