### ISSUE TITLE
Support having tests in separate folders

### ISSUE THREAD

**Issue by jamie-kupka-acl** [cypress-io/cypress#2120]
### Current behavior:

Tests must all exist in the same folder.

### Desired behavior:

I like to store tests in the folder of the component they are testing.

When running this command
`cypress run --browser chrome --spec app/components/**/*.cyp.js`

I get the error:
```
Can't run because no spec files were found.
We searched for any files matching this glob pattern:
app/components/**/*.cyp.js
```

### Versions

Cypress v3.0.1

**Comment by Bkucera** [comment]
@jamie-kupka-acl I believe you just need quotes around your glob pattern, shown here https://docs.cypress.io/guides/guides/command-line.html#Run-tests-specifying-a-glob-of-where-to-look-for-test-files

**Comment by jamie-kupka-acl** [comment]
Thanks @Bkucera but still get the same error when add quotes.

If I put the tests in `cypress/integration` folder and run `cypress run --browser chrome --spec cypress/**/*.cyp.js`, it works.  But putting it in another folder it does not.  Note in my cypress.json all I have set is the `baseUrl`

**Comment by Bkucera** [comment]
@jamie-kupka-acl can you try adding `integrationFolder: './'` to your `cypress.json` ?

**Comment by jamie-kupka-acl** [comment]
Ok that does work, thanks.

**Comment by sebastianjung** [comment]
> @jamie-kupka-acl can you try adding `integrationFolder: './'` to your `cypress.json` ?

This seems to make my cypress GUI load forever and longer. 

Is there any way to add multiple folders to the 'integrationFolder' option?

**Comment by jennifer-shehane** [comment]
@sebastianjung The glob can match whatever folder structure you want. Try playing around on https://globster.xyz/ and find what works for the folders you want.

**Comment by aarondotsteele** [comment]
Jennifer,
What I add `"integrationFolder": "{other-folder/cypress,cypress}/integration",` in my config file, when the ide loads, all I get is an error stating "No Files Found In" "root\{other-folder\cypress,cypress}\integration"

Am I doing something wrong. It doesn't seem to parse the glob in that field?

**Comment by bahmutov** [comment]
You can use combination of integration folder and test files config options to get this. Integration folder is a strict string but test files allows you to use mini match

**Comment by Garrett-R** [comment]
In case it helps anyone stumbling across this thread, here's an example:

If you want to grab all tests from the `src/pages` and `src/components` directories that have `.spec.` in them, you could update your `cypress.json` to be:

```json
{
  "integrationFolder": "./",
  "testFiles": "{./src/pages/**/*.spec.*,./src/components/**/*.spec.*}"
}
```

This seems to work well and the Cypress GUI is not slow to open.
