### ISSUE TITLE
Cy.intercept query does not work with arrays

### ISSUE THREAD

**Issue by MehmetCanBOZ** [cypress-io/cypress#21200]
### Current behavior

1
I mocking endpoint with query parameters in Cypress. But when give query field with array of field items.

`cy.intercept(
    {
      method: 'POST',
      pathname: '/api/initiate/manual',
      hostname: Cypress.env('CY_API_URL'),
      https: true,
      query: {
        orderId: '13535353453',
        items: [
          {
            id: '3853438474',
            name: 'Standard Wholesale HB Yellow Pencils',
          },
          {
            id: '2424534353453',
            name: 'natural wood dipped end 72 color',
          },
        ],
      },
    },
    {
      statusCode: 200,
    },
  ).as('mockManuelOrder');`

it gives error :

CypressError

An invalid RouteMatcher was supplied to cy.intercept(). query.items must be a string or a regular expression.

### Desired behavior

It should not give error

### Test code to reproduce

cy.intercept(
    {
      method: 'POST',
      pathname: '/api/initiate/manual',
      hostname: Cypress.env('CY_API_URL'),
      https: true,
      query: {
        orderId: '13535353453',
        items: [
          {
            id: '3853438474',
            name: 'Standard Wholesale HB Yellow Pencils',
          },
          {
            id: '2424534353453',
            name: 'natural wood dipped end 72 color',
          },
        ],
      },
    },
    {
      statusCode: 200,
    },
  ).as('mockManuelOrder');

### Cypress Version

9.4.1

**Comment by davidmunechika** [comment]
`cy.intercept` accepts url, method, or routeMatcher arguments. The routeMatcher is an object used to match the incoming HTTP requests with this intercepted route, but it appears your usage does not conform to the format described in the docs here: https://docs.cypress.io/api/commands/intercept#Arguments

I will be closing this issue as it appears not to be an issue with Cypress itself, but if you have more information to provide I will be happy to reopen it. Thanks!

**Comment by jpblair** [comment]
I opened an issue for this as #28633, as the answer here doesn't really solve the underlying problem.
