### ISSUE TITLE
Really bad error if trying to call "cy.stub(fn)"

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2121]
In Cypress 3.x if we call the following code

```js
const add = (a, b) => a + b
cy.stub(add)
```

we get really terrible error message

```
TypeError: Attempted to wrap undefined property undefined as function
```

and if we click on the error Devtools print the stack

<img width="1283" alt="screen shot 2018-07-10 at 9 28 37 pm" src="https://user-images.githubusercontent.com/2212006/42532808-44b24130-8488-11e8-8c8b-1c2d480577f3.png">

To me this error made zero sense.

**Comment by jennifer-shehane** [comment]
This is still an error in Cypress 3.4.0

**Comment by jennifer-shehane** [comment]
This error no longer occurs - tested in Cypress 6.2.1 

```js
it('test', () => {
  const add = (a, b) => a + b
  cy.stub(add)
})
```

<img width="644" alt="Screen Shot 2021-01-05 at 5 56 10 PM" src="https://user-images.githubusercontent.com/1271364/103640977-5f1b5600-4f7f-11eb-8848-89278d5dbd3c.png">
