### ISSUE TITLE
cypress setup works on mac, but cannot find cypress.json and test files on windows

### ISSUE THREAD

**Issue by geyuqiu** [cypress-io/cypress#21239]
### Current behavior

.
├── package.json // typescript installed here
└── ui-test

ui-test
├── cypress
├── cypress.json
├── node_modules
├── package-lock.json
└── package.json

runs perfectly fine on mac

but on windows: 
* cypress run works (finds test files)
* cypress open does not find test files and cypress.json, then try to recreate empty cypress.json inside cypress/integration folder

### Desired behavior

* same behaviour on mac and on windows
* cypress open also works on windows 

### Test code to reproduce

`cat ui-test/package.json`
```
...
  "scripts": {
    "e2e:open": "cypress open",
    "e2e": "cypress run",
    "e2e:firefox": "cypress run --browser firefox",
    "e2e:edge": "cypress run --browser edge"
  },
  "keywords": [
    "cpyress"
  ],
  "devDependencies": {
    "@bahmutov/add-typescript-to-cypress": "^2.1.2",
    "cypress": "^9.5.4",
    "cypress-file-upload": "^4.1.1",
    "pdf-parse": "^1.1.1",
    "ts-loader": "^8.0.0",
    "webpack": "^4.43.0"
  }
```

`cat ui-test/cypress.json`

```
{
  "defaultCommandTimeout": 5000,
  "env": {
    "stage": "local",
    "local": {
      "baseUrl": "http://localhost:4200"
    },
    "dev": {
      "baseUrl": "***"
    },
    "test": {
      "baseUrl": "***"
    }
  },
  "testFiles": "**/*.e2e.spec.ts",
  "chromeWebSecurity": false,
  "viewportHeight": 1024,
  "viewportWidth": 1280,
  "numTestsKeptInMemory": 10,
  "integrationFolder": "cypress/integration"
}
```

### Cypress Version

9.5.4

**Comment by lmiller1990** [comment]
The logic should be the same for both: are you definitely running `yarn e2e` from inside of `ui-test` on windows? (Sanity check).

It's possible to do something like `yarn cypress run --configFile path-to-config.json`, but as long a you are running `cypress` in a directory with `cypress.json`, it should find in correctly.

I wasn't able to reproduce this - "then try to recreate empty cypress.json inside cypress/integration folder" seems super strange to me, I can't imagine why it would do that.

**Comment by geyuqiu** [comment]
turns out it was a windows specific error with --prefix

npm run --prefix ui-test e2e:open
