### ISSUE TITLE
How to set certain ram to be used by cypress application

### ISSUE THREAD

**Issue by nani554** [cypress-io/cypress#21259]
### What would you like?

Hello i've a requirement, it goes like this
i want my cypress application to use certain amount of ram size for which i need to set **max-old-space-size** but how to set to below command?
`cmd /c npx cypress run *`?

### Why is this needed?

If cypress application uses more ram space then cypress application takes in less time to complete execution, so we can test more test cases in less time.

### Other

cypress: 9.1.0
windows: 7
ram size: 16gb && 8gb machines

**Comment by jennifer-shehane** [comment]
Since this issue hasn’t had a lot of interest, we’ll close this as not planned.
