### ISSUE TITLE
Module API docs are out of date

### ISSUE THREAD

**Issue by James-E-Adams** [cypress-io/cypress#2125]
I'm not sure when this happened, but the module api described here:

https://docs.cypress.io/guides/guides/command-line.html#cypress-run-1

used to be accurate, but now if I log the return of the promise coming from `cypress.run()`, the object looks a little bit more like:

```js
{"startedTestsAt":"2018-07-11T07:34:55.996Z","endedTestsAt":"2018-07-11T07:43:54.136Z","totalDuration":444802,"totalSuites":13,"totalTests":46,"totalFailed":8,"totalPassed":38,"totalPending":0,"totalSkipped":0,"runs":....}
```
Am I missing something or has the api changed and the docs are no longer up to date?

I was previously using `res.failures > 0` to fail in CI, but it seems it should be `res.totalFailed` now..

**Comment by jennifer-shehane** [comment]
Yes, the api did change in v3.0.0. I apologize for the oversight in missing this in our documentation. 

I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document the newly returned Promise here: https://github.com/cypress-io/cypress-documentation/issues/769. Our documentation is open source and contributions are welcome. 😄

**Comment by James-E-Adams** [comment]
Ah I see! Thanks for clearing that up. I understand 3.0.0 included a number of breaking changes, but I wonder how many CI flows this change broke. I'm also slightly alarmed how long it took me to notice this as I upgraded to 3.0.0 a while ago. Thanks for making a great product!
