### ISSUE TITLE
Cypress no longer auto reloading when updating cypress.json

### ISSUE THREAD

**Issue by fairbuj** [cypress-io/cypress#21266]
### Current behavior

Previously when the Cypress.json file was updated Cypress would refresh and update the new settings.  This is no longer happening since approximately Cypress 9.3/9.4 (possibly earlier) and I can't see anything in the release notes to indicate that it is an intentional change.

The work around is to manually close and reopen cypress every time you update environment variables.  Which is much more time consuming

### Desired behavior

Previous functionality returned so when updating Cypress.json cypress refreshes and utilises the updated environment variables / settings

### Test code to reproduce

update the base url or a setting such as the experimentalSessionAndOrigin flag and save cypress.json

### Cypress Version

9.6.0

**Comment by davidmunechika** [comment]
I am able to reproduce this issue _sometimes_. At first, I was testing on 9.6.0 and changing the `retries` configuration option. Cypress was correctly refreshing and re-run the spec with the updated config. However, when I tried changing the `baseUrl` config option, this did not work and Cypress did not refresh. When I removed the `baseUrl` config option and tried changing the `retries` config option again, this continued to not work and nothing would refresh (even though this worked earlier). Closing the browser and re-running the spec did not have the correct configuration option. It did appear that I needed to entirely close Cypress and re-open for these config values to update.

**Comment by rockhold** [comment]
@fairbuj, with the release of v10.0.0, this file is now considered [legacy configuration](https://docs.cypress.io/guides/references/legacy-configuration) and we are unlikely to prioritize fixing this issue. If you're still seeing an issue with auto reloading on v10 or greater, however, please let us know by logging a new issue. Thanks!
