### ISSUE TITLE
Prevent experimentalSessionAndOrigin navigating to default blank page before each test

### ISSUE THREAD

**Issue by PentoreXannaci** [cypress-io/cypress#21260]
### What would you like?

I would like a way to prevent cypress navigating to a blank page between each test if experimentalSessionAndOrigin is enabled,
or maybe allow/support Cypress.config() to enable/disable experimentalSessionAndOrigin in tests.

### Why is this needed?

my tests relies on cross domain so i use the experimental feature cy.origin(), before that i used ugly workarounds which where not reliable at all. some tests are bulid that they continue on the state of the test before and navigating to blank page is completly ruining over 50 tests i have.

**Comment by estefafdez** [comment]
We are also facing this problem in our project with the `experimentalSessionAndOrigin` enabled.

**Comment by mjhenkes** [comment]
@PentoreXannaci && @estefafdez Thank you for your feedback, we will take this back to our product team.

`cy.session` and `cy.origin` are planned to both become Generally available in the 11.0 release. Included with the cy.session command is better test isolation, where 'about:blank' is visited between tests. 

 To better model our users experience, we've combined the feature flag to enable both features at the same time, such we can gather feedback on the entire process. 
 
 For authentication workflows cy.session and cy.origin have been designed to work together and some assumptions were made in the cy.origin code that relies on session data being cleared between each test.

**Comment by pstakoun** [comment]
Hey @PentoreXannaci and @estefafdez, I'm a Product Manager at Cypress and would like to hear more about your use cases. Can you elaborate on what portion of your test suites rely on shared/leaked state, as well as why that is? Specifically, what state is shared/leaked between tests and what is the time and level of effort that it would take to refactor your tests to conform to our new model of test isolation?

**Comment by PentoreXannaci** [comment]
our page takes way too long to load (bout 5-10seconds), so i navigate from page to page via navigation instead of url.

so my tests are like: 
going to the frontpage -> compare snapshot -> test some UI elements -> click on the next tab -> repeat.
and each page/ui element test should be a own test because it would be a massive test block.

refactoring those tests is no option because it would stretch the ci build to beyond bearable time. (page loading time).
i hope you can follow me.

**Comment by david-garcia-garcia** [comment]
Same here, our case is a huge corporate SPA, where initial loading takes several seconds. Going to blank after each spec makes tests execution time unbearable.

**Comment by rasha-cse** [comment]
Setting `testIsolation: "off"` in **cypress.config.js** will prevent navigating to a default blank page between each test!

**Comment by thomasgubler** [comment]
I ran into this when upgrading to Cypress 12.x.

Starting with 12.0.0  Session and Origin Experiment (experimentalSessionAndOrigin) is now generally enabled (see https://docs.cypress.io/guides/references/changelog#12-0-0)

The config parameter changed as well. The following line in cypress.config.js resolved the issue for me:

`testIsolation: false`

**Comment by yogawa** [comment]
@thomasgubler you saved my day!
