### ISSUE TITLE
TouchEvent Test

### ISSUE THREAD

**Issue by yosr-maker** [cypress-io/cypress#21265]
### What would you like?

Does Cypress support TouchEvent ?
I'm testing touch event on button , but it doesn't work ! 
This is the code of the triggers Touch : 
```js
.trigger(`touchstart`, {
        changedTouches: [
          {
            clientX: 200,
            clientY: 50,
          },
        ],
      })
      .trigger(`touchmove`, {
        changedTouches: [
          {
            clientX: 440,
            clientY: 50,
          },
        ],
      })
      .trigger(`touchend`, {
        changedTouches: [
          {
            clientX: 440,
            clientY: 50,
          },
        ],
```

**Comment by davidmunechika** [comment]
Thanks for opening an issue! Are you receiving an error message or is simply nothing happening? More information on the behavior you are experiencing would help us understand this issue better.

**Comment by yosr-maker** [comment]
it focues on the button but nothing happening that means there's no touch (click) on the button.
