### ISSUE TITLE
CYPRESS_NO_COMMAND_LOG=1 leaves faulty empty space

### ISSUE THREAD

**Issue by Agalias** [cypress-io/cypress#21271]
### Current behavior

Hello, currently when running `CYPRESS_NO_COMMAND_LOG=1 npm run cy:open` and opening any test - there is some space left where Test Runner Command Log should be. Probably because of reporter

![Screenshot 2022-04-28 at 17 33 43](https://user-images.githubusercontent.com/77224571/165777677-0ea3577c-a132-4f65-82c1-480339efb369.png)

Probably empty space is left there because `<div class="reporter-wrap" style="left: 0px;"></div>` is not deleted. If to delete it and resize the Test Runner window - empty space will disappear.

https://user-images.githubusercontent.com/77224571/165968558-71fa981b-70ca-44a5-aec1-bf55b118b6fe.mov

### Desired behavior

There is no space left where Test Runner Command Log should be when using `CYPRESS_NO_COMMAND_LOG=1` environment variable:
![Screenshot 2022-04-28 at 17 40 19](https://user-images.githubusercontent.com/77224571/165778113-d7e6b449-10cc-48b3-9c4c-e98289f38837.png)
 

### Test code to reproduce

Should be reproducible anywhere, I tested it on the fresh 9.6.0 Cypress project with getting started examples.

### Cypress Version

8.7.0, 9.6.0

**Comment by davidmunechika** [comment]
Thanks for opening an issue. I was able to reproduce on 9.6.0 and it looks like a regression occurred sometime after 5.4.0 (when it was implemented).

**Comment by rockhold** [comment]
I tested this out in v10.0.2 and realized we don't yet have support for this environment variable in v10+. Here is a related issue for implementing that support: #21721

We should ensure that the spacing issue called out here is taken care of as part of that work.
