### ISSUE TITLE
PDF inside iframe not showing in chrome

### ISSUE THREAD

**Issue by lgenzelis** [cypress-io/cypress#21274]
### Current behavior

According to the comments made by @jennifer-shehane in #2835 , PDFs loaded within iframes used to work in chrome in the past, but they don't now.

<img width="1144" alt="Screen Shot 2022-04-29 at 12 50 40 PM" src="https://user-images.githubusercontent.com/4582440/165979684-06aa8072-7ae7-4501-8f97-d309578107d4.png">

I'm using cypress 9.6 with chrome 100. This works fine if I instead choose edge (101) or firefox (98).

### Test code to reproduce

Clone [this example repo](https://github.com/jennifer-shehane/cypress-pdf-problem) by @jennifer-shehane and do:

```bash
$ npm install
$ npm install cypress@9.6
$ npm run cypress:open
```

Select Chrome (I'm using v100) and run the test. You'll see something like my screenshot above instead of seeing the PDF inside the `iframe`.

### Cypress Version

9.6

**Comment by mjhenkes** [comment]
Using chrome v100 and this simple test, pdfs are not preview-able.

Requires testing.pdf file in project root.

index.html

```html
<html>
<body>
  <iframe src="testing.pdf"></iframe>
</body>
</html>
```

spec.js

```javascript
it('Visiting iframe with pdf src', function () {
  cy.visit('index.html')
})
```

This appears at first glance to be an issue with cypress interfacing with chrome. This issue was not seen with:
* Firefox 99
* Chromium 94
* Edge 101

**Comment by lgenzelis** [comment]
Maybe also worth mentioning, @mjhenkes , if I run cypress in headless mode, the PDF goes to `cypress/downloads/`

**Comment by sean-mystyle** [comment]
I have the same issue with Chrome Version 102.0.5005.115 (Official Build) (64-bit)

A few months ago using a Base64 PDF generated inline in an iframe as src via javascript on page, the Chrome PDF Viewer used to load.  Now, it does not, just blank, with no errors in console or network tabs in developer tools.

Still works OK as expected in FireFox.  I'm guessing this is a Chrome issue...

**Comment by arnocloete-za** [comment]
> I have the same issue with Chrome Version 102.0.5005.115 (Official Build) (64-bit)
> 
> A few months ago using a Base64 PDF generated inline in an iframe as src via javascript on page, the Chrome PDF Viewer used to load. Now, it does not, just blank, with no errors in console or network tabs in developer tools.
> 
> Still works OK as expected in FireFox. I'm guessing this is a Chrome issue...

We have the exact same issue as described here in this comment. Has anyone resolved this? Or found a way around it?

**Comment by sszemer** [comment]
i'm using cypress 9.7 and chrome 103
the pdf loads fine inside an iframe when running locally, but fails running in docker.
ff and electron don't seem to have this issue

**Comment by lgenzelis** [comment]
This is no longer happening. Tested with Cypress 12.12 and chrome 113. I'm closing the issue.
