### ISSUE TITLE
STOP button in Test runner doesn't stop multiple test retries

### ISSUE THREAD

**Issue by Darksymphony75** [cypress-io/cypress#21275]
### Current behavior

I have set up **retries :1**, so when any test fails, it will retry the same test again. This is normally working fine, but: In Cypress test runner when some step fails and I immediately press STOP, then the second attempt is still starting, even I have stopped the test execution. This is quite annoying, because after failure I press stop and I am analyzing the cause of failure, but as the second attempt is starting and ignoring that I pressed stop, it will close the Attempt1 section and shows the same failure in second Attempt section.

### Desired behavior

In Test runner, after I click the STOP button, the test execution should immediately STOP, and no other retries should start.

### Test code to reproduce

This is a general issue with the Test runner, not related to any specific code.

### Cypress Version

9.6.0

**Comment by davidmunechika** [comment]
Hi thanks for opening an issue. I was able to reproduce a similar issue- I pressed stop after the first attempt failed and then some time later the second attempt failed due to a command timeout. The first attempt collapsed to show the second attempt which was unexpected.

<img width="1484" alt="Screenshot 2022-05-03 at 10 54 44 AM" src="https://user-images.githubusercontent.com/27690333/166478325-7a7e855e-71b1-4679-9095-c222d406b6e3.png">

**Comment by Darksymphony75** [comment]
exactly, thank you very much for reproducing this. It'll be good, if the stop really stops the execution even the 2nd attempt

**Comment by rockhold** [comment]
@Darksymphony75, with our recent release of v10.0.0 (and subsequent patches), we have several issues in our backlog which may no longer be relevant. To assist with the volume of issues we're combing through (new, as well as historic), could you try to reproduce this on v10+ to see if it's still an issue? Thanks!

**Comment by Darksymphony75** [comment]
So, **Cypress 10** has now similar behavior. The difference is that it doesn't timeout, just say Test was stopped, but the issue persist.

**Reproducing issue in Cy10:** 

1/ Set retries to 1
2/ Make an error in 1 your test
3/ Run this faulty test in test runner
4/ After the error appears, immediately click on STOP button
5/ The Attempt 2 has already started, but after a few seconds the Attempt 1 section is closed and Attempt 2 section stays open with the message, that the test was stopped.

So the issue is still there, just the message changed. I don't want to Attempt 1 section to be closed while I am analysing the error.

![obrázok](https://user-images.githubusercontent.com/73718902/178805042-ab0083d8-9364-467b-bc60-98ed3ea4bf3b.png)
