### ISSUE TITLE
Page not loading completely , showing access forbidden with strict-origin when cross-origin

### ISSUE THREAD

**Issue by Sriram-S** [cypress-io/cypress#21270]
### Current behavior

Trying to automate web app where each page access different domains . Unfortunately will not be able to call out the app under test here. With cy.visit("https://ur....l"), for example , we have calls across different domains within the same page (homepage loads data from diff external sites like abc.com,xyz.com).
 Cypress waiting for all those to be loaded only to get 403 error with strict-origin when cross-origin in network tab.  However no issue is seen when loading it in normal chrome browser.
I have tried using "chromeWebSecurity": false in cypress.json and also tried to update chrome preference during launch inside plugins/index.js with --disable-site-isolation-trials but none of them works.

Any possible workaround or anything else to be tried here?

### Desired behavior

Should allow to load pages across domains with security disabled?

### Test code to reproduce

in cypress.json

`{
"chromeWebSecurity": false
}
`

in pulgins/index.js

`module.exports=(on,config)=>{
on('before:browser:launch',(browser={},args)=>{
if(browser.name === 'chrome'){
launchOptions.args.push('--disable-site-isolation-trials');
return args
}
}
}`

### Cypress Version

9.6.0

### Other

Chrome v100

**Comment by mjhenkes** [comment]
@Sriram-S, checkout the newly released experimental cy.origin command. 

[blog](https://www.cypress.io/blog/2022/04/25/cypress-9-6-0-easily-test-multi-domain-workflows-with-cy-origin/)

[API](https://docs.cypress.io/api/commands/origin)

[Feedback discussion](https://github.com/cypress-io/cypress/discussions/21186)
