### ISSUE TITLE
Cypress fails to find element only in headless mode

### ISSUE THREAD

**Issue by eladmoshe** [cypress-io/cypress#2127]
### Current behavior:
When trying to query for a marker in Google map, although the test consistently passes in headed browser, it always fails in headless browser.  Adding an arbitrary `wait` is not helpful.<br/> I am not sure why Google map cause the test to fail -  I tried to create a simpler DOM structure but in that case everything worked as expected. 

### Recording:
Video recording of the failing test in headless mode (source code below). The same test passes in both Electron and Chrome.
[spec.js.mp4.zip](https://github.com/cypress-io/cypress/files/2184693/spec.js.mp4.zip)

### Desired behavior:
Cypress should be able to query in headless mode as it does in headed mode.

### Steps to reproduce:
Clone the [repo](https://github.com/eladmoshe/cypress-issue-repro) and follow the instruction in the README file

### Versions
OSX 10.13.5, node.js 10.2.1, Cypress 3.0.2

**Comment by jennifer-shehane** [comment]
Thanks so much for the reproducible example and video!

This is...really weird. I definitely see this behavior when running headless, but I also see this behavior if I pop open and drag the test runner to my non-retina display to run there (on Chrome and Electron). I'm having a hard time believing that is related to the issue exactly, but something funny is going on 🤔

**Comment by jennifer-shehane** [comment]
Oh my gosh, this is related! So, when the map is rendered on my retina screen, the map url contains `spotlight-poi2_hdpi.png`, but when the map is rendered on my non-retina screen, the map url is now `spotlight-poi2.png` - notice there is no `_hdpi` suffix. 

I would suggest updating your test to instead use `cy.get("img[src*='spotlight-poi2']")` to not be as restrictive on the dpi of the rendered map you are looking for.

**Comment by eladmoshe** [comment]
Wow, thanks @jennifer-shehane!

**Comment by thakkarsaurabh** [comment]
> Oh my gosh, this is related! So, when the map is rendered on my retina screen, the map url contains `spotlight-poi2_hdpi.png`, but when the map is rendered on my non-retina screen, the map url is now `spotlight-poi2.png` - notice there is no `_hdpi` suffix.
> 
> I would suggest updating your test to instead use `cy.get("img[src*='spotlight-poi2']")` to not be as restrictive on the dpi of the rendered map you are looking for.

This works for me. Thanks.
