### ISSUE TITLE
No information regarding git branch in cypress dashboard - Jenkins CI

### ISSUE THREAD

**Issue by ArieLevs** [cypress-io/cypress#2129]
### Current behavior:

`Branch` on test run not showing current branch name

![image](https://user-images.githubusercontent.com/34907201/42585328-f96faab2-853d-11e8-86b3-7ac8ea43bcb4.png)

### Desired behavior:

Show info regarding branch test when running from Jenkins
### Steps to reproduce:

Run Cypress e2e test from Jenkins
(Running same test from Mac OS for example is showing current branch)

### Versions
Cypress: 3.0.1
Browser: Electron 59.0.3071.115
Operating System: CentOS 7.3.1611
CI Service: Jenkins

**Comment by jennifer-shehane** [comment]
[Jenkins env vars](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-belowJenkinsSetEnvironmentVariables) seems to have:
- `GIT_BRANCH`
- `GIT_URL`

**Comment by jennifer-shehane** [comment]
Actually, the work for this is already done, but has not been released here: https://github.com/cypress-io/cypress/pull/2089
