### ISSUE TITLE
Cypress version command hangs (0.17.2)

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#213]
Using latest cypress 0.17.2 and cypress-cli 0.11.1 
when running `cypress version` or `cypress --version` just hangs

**Comment by brian-mann** [comment]
This is happening for the same reason as your other issue. There's a missing dependency and Cypress is failing to ever invoke the desktop application which causes it to hang.

**Comment by bahmutov** [comment]
Hmm, got the same timing out behavior locally on Mac OSX with cypress-cli 0.12.2
