### ISSUE TITLE
Branch links are broken in the browser UI

### ISSUE THREAD

**Issue by opike** [cypress-io/cypress#21308]
### Current behavior

Whenever I click on one of the branch links under a project in the cypress UI, the page crashes with a browser console log error:
"TypeError: t.map is not a function"

Here you can see a screencast of the issue:
https://d.pr/i/XGMbfJ

This happens with both of my projects.

### Desired behavior

The cypress test run details for that branch should be shown.

### Test code to reproduce

I don't have access to the cypress cloud-based UI code.

### Cypress Version

9.6.0

**Comment by mjhenkes** [comment]
Hi @opike, Since this is an issue with the cypress cloud, feel free to reach out to [support@cypress.io](mailto:support@cypress.io)

**Comment by pstakoun** [comment]
Hi @opike thank you for raising this, the Dashboard team is currently investigating.

**Comment by pstakoun** [comment]
@opike we have resolved the error you are seeing. It looks like your organization has some branches coming in with newlines, so depending on which branch you are filtering on (with or without newline in the name), you may see different results. We will continue to investigate the result of this, but would you be able to give some context on why some branches are coming in with newlines? Would be curious as to what CI setup you have and if this is simply a misconfiguration or intentional.

**Comment by opike** [comment]
@pstakoun Thanks for looking into this issue. The console error message has been resolved but for one of the branches, I don't see any runs when I drill down into the details:
https://d.pr/i/h7I7yj

The tests are being run and uploaded on a Debian instance using Jenkins. What configuration should I be looking at that might be causing newlines?

**Comment by pstakoun** [comment]
@opike we've logged an issue on our end to consolidate the branches with newlines and those without. From some very surface-level digging around, I've come across a couple config problems that may be adding newlines to environment variables with Jenkins (potentially via certain containerization configs). Unfortunately we likely cannot investigate much further on our end in terms of why the newlines are coming in, but we are looking into updating how we ingest those values to potentially strip off the newlines in the future.

**Comment by benpatterson** [comment]
Calling out that I'm going to close this ticket as resolved. We have made some additional accommodations on the dashboard side of the equation to handle branch names ending with newline characters. We likewise have cleaned up historical data at this point. Let us know if there are additional issues in this sector for you and thanks for letting us know about it.
