### ISSUE TITLE
CI: Builds from external contributors duplicate tests run across mutliple machines

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#21318]
### Current behavior

When a build is created by an external contributor, the tests are not split up across the machines due to them not having access to the record keys. We still parallelize the job (up to 7 machines) which means we are using up CI time and increasing the likelihood that the job fails due to flake.

### Desired behavior

We should not be parallelizing jobs if the tests cannot be split up, or we should use our own logic for splitting the tests across machines

### Test code to reproduce

Check out a build from an external contributor e.g. https://app.circleci.com/pipelines/github/cypress-io/cypress/37271/workflows/1ad10bf4-86c3-4bff-bad8-044b3952ad4b/jobs/1499238/parallel-runs/5?filterBy=ALL

### Cypress Version

9.6.0

**Comment by flotwig** [comment]
I think anywhere we use Cy parallelization we should fall back to using CircleCI test splitting, same way we do for `driver-integration-tests`: https://github.com/cypress-io/cypress/blob/7a76de10f88d3737fb0f46cfabe3b398af0a833f/circle.yml#L438

This could be factored out into a unique CircleCI step to reduce duplication.
