### ISSUE TITLE
Escape input event is ignored when using `cy.type('{esc}')`

### ISSUE THREAD

**Issue by davidmunechika** [cypress-io/cypress#21313]
### Current behavior

If the escape key has been implemented with functionality that changes the text of an input field (i.e. hitting escape when focused on an input field clears the text in the input), this behavior is not replicated correctly when using cy.type('{esc}').

The Escape input event is being ignored at this line: https://github.com/cypress-io/cypress/blob/6e03e020682e73e0e5480fe010fe818fce488205/packages/driver/src/cy/keyboard.ts#L1315-L1316

because input is getting set to `false` here: https://github.com/cypress-io/cypress/blob/6e03e020682e73e0e5480fe010fe818fce488205/packages/driver/src/cy/keyboard.ts#L1264-L1269

because the Escape event doesn't have a `text` field associaed with it so `shouldUpdateValue` is returning false (even though in this specific case, we want Escape to be able to update the value).

### Desired behavior

`cy.type('{esc}')` should simulate the same behavior experienced by the user when hitting Escape manually.

### Test code to reproduce

Replace `realType()` with `type()` and the test will fail.

https://github.com/cypress-io/cypress/blob/6750d33b46dbb2ca40c6af6bcf67ca6d09c6b868/packages/app/cypress/e2e/specs_list_e2e.cy.ts#L168-L178

### Cypress Version

10.0.0

**Comment by niketpathak** [comment]
It's been over a year, and this still doesn't seem to work. Tested on the latest version as of today (**v12.12.0**)

**Comment by niketpathak** [comment]
Been 2 years now ? Can the Cypress team look into this ?
