### ISSUE TITLE
'Property 'login' does not exist on type 'cy & EventEmitter'.' error is showing with custom command

### ISSUE THREAD

**Issue by shitalmeghanathi** [cypress-io/cypress#21312]
### Current behavior

![image](https://user-images.githubusercontent.com/3427772/166456188-469b714e-31b7-492e-88fd-3c3ac400490b.png)

![image](https://user-images.githubusercontent.com/3427772/166456276-d0e28f5d-34d0-493a-b143-c81ceba1ed04.png)

### Test code to reproduce

![image](https://user-images.githubusercontent.com/3427772/166456299-147168ce-a316-4e8a-9582-13458d28aa7f.png)

### Cypress Version

9.6.0

**Comment by shitalmeghanathi** [comment]
@jennifer-shehane Please help

**Comment by mjhenkes** [comment]
@shitalmeghanathi, check out our docs for adding types for custom commands.
https://docs.cypress.io/guides/tooling/typescript-support#Types-for-custom-commands

**Comment by ness-EE** [comment]
what is written in the docs doesn't work

**Comment by KomaGR** [comment]
> @shitalmeghanathi, check out our docs for adding types for custom commands. https://docs.cypress.io/guides/tooling/typescript-support#Types-for-custom-commands

Following the instructions results to
```
> namespace global
Augmentations for the global scope can only be directly nested in external modules or ambient module declarations. ts(2669)
```


Related to https://github.com/cypress-io/cypress-documentation/issues/2565

**Comment by BrendonHenrique** [comment]
although this issue was closed, the problem still persists and the docs doesn't completely explains how to set up typescript on the project...

**Comment by Drew-Daniels** [comment]
Yeah, having the same exact issue here. Even when following the docs like @mjhenkes recommended, I'm not getting types on custom commands.

I have:
- A similar command to what they show in the [docs]():
```ts
// cypress/support/commands.ts

Cypress.Commands.add(
  'login',
  ({ username = Cypress.env('username'), password = Cypress.env('password') } = {}) => {
    cy.session([username, password], () => {
      cy.visit('/login');
      cy.get('[data-cy=legacy-auth-login-button]').click();
      if (Cypress.env('mode') === 'local' || Cypress.env('mode') === 'docker') {
        cy.origin(
          Cypress.env('auth_url'),
          {
            args: {
              usr: username,
              pwd: password,
            },
          },
          ({ usr, pwd }) => {
            cy.get('#username').type(usr);
            cy.get('#password').type(pwd);
            cy.get('button').click();
          },
        );
      } else {
        cy.get('#username').type(Cypress.env('username'));
        cy.get('#password').type(Cypress.env('password'));
        cy.get('button').click();
      }
      cy.location('pathname').should('eq', '/my_tasks');
    });
  },
);
```

- Added the exact `tsconfig.json` they [recommend](https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfigjson) using in my `cypress` folder:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"]
  },
  "include": ["**/*.ts"]
}
```
- Added an [index.ts](https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands) file to `cypress/support`:
```ts
export {}

declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Logs in E2E user
       * @returns void
       */
      login: () => void;
    }
  }
}
```
- Run `restart ts` from the command pallete
- Restarted VSCode

Pretty frustrating when the maintainers just assume we haven't read the docs and close the issue?

**Comment by nagash77** [comment]
Hi @Drew-Daniels thank you for providing that example.  I am going to reopen this issue and have an engineer take a look and see what they find.

**Comment by cacieprins** [comment]
Hi @Drew-Daniels , thank you so much for your example code!

Does adding argument definitions to the type declaration (in the `index.ts` file) resolve your issue? As declared when extending the `Chainable` interface, your login command takes no arguments - and this does not match the signature of your implementation.

**Comment by Drew-Daniels** [comment]
Thanks @nagash77 and @cacieprins ! Yes, this appeared to be the issue in my case. Once I made sure the login function signature (defined in `index.ts`) matched my implementation I was able to get typing for my custom commands:

![image](https://github.com/cypress-io/cypress/assets/62859552/6660a568-f84a-410a-b7f6-2c7c820adb57)

```ts
// index.ts
type LoginCommandArgs = {
  username?: string;
  password?: string;
};

Cypress.Commands.add(
  'login',
  ({ username = Cypress.env('username'), password = Cypress.env('password') } = {}) => {
    cy.session([username, password], () => {
      cy.visit('/login');
      cy.get('[data-cy=legacy-auth-login-button]').click();
      if (!(Cypress.env('mode') === 'dev')) {
        cy.origin(
          Cypress.env('auth_url'),
          {
            args: {
              usr: username,
              pwd: password,
            },
          },
          ({ usr, pwd }) => {
            cy.get('#username').type(usr);
            cy.get('#password').type(pwd);
            cy.get('button').click();
          },
        );
      } else {
        cy.get('#username').type(Cypress.env('username'));
        cy.get('#password').type(Cypress.env('password'));
        cy.get('button').click();
      }
      cy.location('pathname').should('eq', '/my_tasks');
    });
  },
);

export {}

declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * 
       * @param args 
       * @returns 
       */
      login: (args?: LoginCommandArgs) => Chainable<JQuery<HTMLElement>>
      clickOutside: () => void
    }
  }
}
```

Thanks a lot for the help 👍🏻

**Comment by cacieprins** [comment]
@Drew-Daniels glad to help! I'll mark this issue as resolved.

**Comment by ThePiyushAggarwal** [comment]
Hi @Drew-Daniels @cacieprins !

I am having a similar issue. Can you please help out!
I have created a sample repository for the issue https://github.com/ThePiyushAggarwal/cypress-testing-typescript-setup

![image](https://github.com/cypress-io/cypress/assets/27003616/5e7d01ef-ca04-4d7c-9ded-8820c30080a3)

**Comment by ThePiyushAggarwal** [comment]
No further help required. I could solve my issue using `cypress.d.ts` file. (Updated the repo. Keeping it for my reference later on as well)

I don't know why this happened to me. I created a simple vite app and integrated cypress with normal process. Even the `cypress-realworld-app` seem to throw these errors for me. 🥲

![image](https://github.com/cypress-io/cypress/assets/27003616/d1ef038e-224a-4a8a-9458-c9baa30611d9)

**Comment by mwimbledon** [comment]
For others who may be having this issue, I had to explicitly include the file in which I added my custom cypress command to the global cypress namespace (in my case `cypress/support/commands.ts`) in my `tsconfig.json` to get the type to pull through without erroring:

```javascript
{
  "include": [ 
    "cypress/support/commands.ts"
  ],
}
```

**Comment by robsonos** [comment]
For me `export {}` did the trick.
