### ISSUE TITLE
If you shrink the reporter sidebar (Command Log) by dragging the width to be too small you cannot get it back

### ISSUE THREAD

**Issue by cmswalker** [cypress-io/cypress#2132]
### Current behavior:
![screen shot 2018-07-11 at 8 57 25 pm](https://user-images.githubusercontent.com/8467234/42611839-0eda0bfe-854d-11e8-8de6-80317aab00d1.png)

### Desired behavior:
If you manually drag and shrink the sidebar there should be a way to get it back.

### Steps to reproduce:
Shrink the sidebar on the ui with the arrow drag (just like you shrink any GUI). You'll see that there is no obvious way to get this back to normal. Even when I uninstall and reinstall the package its persisting and relying on some cached data somewhere.

### Versions

cypress: ^3.0.2
Chrome: 67
Mac OS

**Comment by jennifer-shehane** [comment]
Yes, it is replying on some global app data. You *can* grab the left side and drag it, it's just very very tricky. 😝 

But, to clear our the app data that has this saved state:

- Goto `File` -> `View App Data`
- Delete everything in here
- Close cypress and open it up again

Let me know if this works!

**Comment by cmswalker** [comment]
*You can grab the left side and drag it, it's just very very tricky. 😝*

Omg you're right, so tiny!

It would be great if there was a toggle button that persisted next to the DOM Selector button. That way the panel could be collapsed or expanded on demand. I'd be interested in creating a PR for this but I know adding more stuff to the sidebar and control panel is a difficult subject

**Comment by jennifer-shehane** [comment]
Yeah, this does seem like a good feature. You aren't the first one to lose the command log. 

The code for this lives in the `reporter` package here: https://github.com/cypress-io/cypress/tree/develop/packages/reporter

**Comment by jennifer-shehane** [comment]
When dragged too small - you could transform the left side into a button of sorts - that allows you to click and expand. 

Or you could simply add a minimum width to the command log so that it's not dragged too small.

**Comment by Manuel-Suarez-Abascal** [comment]
> it is relying on some global app data...
> But, to clear our the app data that has this saved state:

@jennifer-shehane I would like to work on this feature. It shouldn't be too hard & it's a good feature to add.

 I think it would be cool to have a button that shows up once we shrink the `test runner's sidebar` to a certain point(a width value to be determined?). 
 
 This button will reset the `sidebar's width` to its original value(to be determined?) & disappears again afterward.
 
 I would like to take inspiration from Jira's `sidebar` toggle `button`. What do you think?
 

https://user-images.githubusercontent.com/32891808/123010561-d78a9d80-d38c-11eb-96df-a545cd7a10e3.mov

**Comment by strowk** [comment]
This workaround does not work for me. Clicking on File does nothing (neither any other menu items next to it - Edit, View, Window). Running 7.5.0 on Ubuntu 20.04. Should I create issue for not working "File" menu?

**Comment by jennifer-shehane** [comment]
@strowk There's an existing issue for this: https://github.com/cypress-io/cypress/issues/16323

@Manuel-Suarez-Abascal This design is good. We are reworking/redesigning a lot of the runner currently, planning to merge the component testing + e2e testing screens, so I'm not sure this is the best time to introduce that work since it may be addressed with that work.

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane thanks for the update! Sounds good! Otherwise, I'm available to work on it if needed!

**Comment by emilyrohrbough** [comment]
This issue is no longer relevant with the recent 10.x release which places a min-width on the reporter.
