### ISSUE TITLE
Launching Cypress with the --dev flag throws an error

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#21320]
### Current behavior

`--dev` is shown as a flag that can be used in the `--help` menu, but it errors when you try to use it on a released version.

<img width="1047" alt="Screen Shot 2022-05-03 at 11 59 39 AM" src="https://user-images.githubusercontent.com/1271364/166802240-b3cdc235-d120-4696-9028-2cfab5de4242.png">

### Test code to reproduce

Run `cypress open --dev`

### Cypress Version

9.6.0

**Comment by mjhenkes** [comment]
@jennifer-shehane, could you post that screen shot again? I think you might have posted the issue before it was done uploading.
