### ISSUE TITLE
Cypress env is undefined after visiting page

### ISSUE THREAD

**Issue by JonasGoetz01** [cypress-io/cypress#21331]
### Current behavior

I am creating some ENVs in my test. These are also known and set correctly. However, when I visit a page or something similar, the ENVs are suddenly "undefined".

![image](https://user-images.githubusercontent.com/65551807/166639461-fc23ab6c-ca0f-48eb-a195-b1fb8b5b655f.png)

As you can see first the ENV is set and in the next step it's value is recognized correctly.
After the second test file visits a page, the ENVs are all undefined.

Also, I found out that the ENVs are known when I don't visit a page in the second file and they are also known when I restart the test via the restart button after I started the test. If I close the browser and then run the test again, Cypress does not know the ENVs again on the first run.

### Desired behavior

I want Cypress to know the values of the ENVs throughout the test.

### Test code to reproduce

Test file 2:
```js
describe('00_einrichten',() => {

    it('Create ENVs', () => {
        const date1 = new Date()    
        const registerDate = date1.getTime()  
        Cypress.env('registerUsername', String(registerDate) + "@example.com")
        cy.log(Cypress.env('registerUsername'))
    })

    it('Registrieren', () => {
		expect(Cypress.env('registerUsername')).to.be.a('string').not.empty;
    })

})
```
Test file 2:
```js
describe('00_einrichten',() => {

    it('Google', () => {
		cy.visit('https://google.com')
	})

    it('Registrieren', () => {
		expect(Cypress.env('registerUsername')).to.be.a('string').not.empty;
    })

})
```

All other files were not changed by me.

### Cypress Version

9.6.0

**Comment by davidmunechika** [comment]
Thanks for logging an issue! I was able to recreate this as you described. If the second test does not visit a new page, the env persists between tests, but as soon as a new page is visited, the env becomes undefined.

**Comment by sainthkh** [comment]
There's some German and unnecessary lines in the test code. I simplified it like below:

```js
describe('a', () => {
  it('Create ENVs', () => {
    Cypress.env('registerUsername', `asdf@example.com`)
  })

  it('Check env -> Pass', () => {
    expect(Cypress.env('registerUsername')).to.be.a('string').not.empty
  })
})

describe('b', () => {
  it('Google', () => {
    cy.visit('https://google.com')
  })

  it('Check env -> Fail', () => {
    expect(Cypress.env('registerUsername')).to.be.a('string').not.empty
  })
})

```
