### ISSUE TITLE
Reasonable Metrics for Test Latency 

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#2133]
Please see if you can add the following to docs

I was looking into what would be a reasonable metric for cypress test latency so we could sanity check ourselves. We have 43 tests that take 12 minutes. I know this is slow, however I do not have a point of reference. What kind of speed should I be aiming for with a tests? What's good? What's average?

Thanks!

**Comment by jennifer-shehane** [comment]
Hey @egucciar, have you had an opportunity to use our Dashboard Service? There are metrics in there regarding your test timings and we are working on improving the insight into the timing of tests in there. 

Dashboard docs: https://on.cypress.io/dashboard-service#Spec-amp-Test-Durations

**Tests for our docs and their timings**
![screen shot 2018-07-12 at 11 36 19 am](https://user-images.githubusercontent.com/1271364/42643710-d4876a2a-85c7-11e8-9ff9-bcc6072d4cba.png)

I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document writing some more recommendations here: https://github.com/cypress-io/cypress-documentation/issues/773.

Writing this doc was already on our roadmap and will be even more important when we release [parallelization](https://github.com/cypress-io/cypress/issues/681), which is landing soon.

**Comment by egucciar** [comment]
@jennifer-shehane

This is not really about my tests. I'd like to see in the docs a simple page about best practices about test speed. For example, what a reasonable test time would be, what's good, what's average. I was reading an open ticket where a user reports that their tests were far slower than protractor . The response was that theoretically, cypress tests should be fast. How fast? What's a reasonable speed for tests considering how fast cypress is, the overhead of `visit`? How fast is a fast test? How fast is an average test? How slow is a bad/slow test? What kind of variables impact test speed? What can one do to optimize their tests for speed? 

We have an issue with our tests taking too long. However it's hard to know whether to question if that's just the nature of our test suite, or if that's the nature of Cypress. So it would be super awesome if Cypress team can publish a performance and optimization document. For teams who have adopted TDD and develop tests for each feature, you can end up with lots of tests, extending build times by A LOT. It's great to have a sanity check to understand that Cypress team stands by certain practices for optimizing, or plans to introduce certain features to make things faster, or features which can be leveraged to speed things up, or things which make tests slower than they need to be.

I'm not sure if there's a separate repository for documentation requests. But I'd ask if this can be reopened or if I can open it there unless you disagree that this shouldn't be a document or guide worth writing.
