### ISSUE TITLE
{downArrow} on input type "number" inconsistent across browsers

### ISSUE THREAD

**Issue by speexy** [cypress-io/cypress#21339]
### Current behavior

I have a form field of `type=number` that should only allow positive numbers. I set the `min-tag` to `1` so that when you click the little down-arrow in the field, or fill in the field with the down-arrow-key, it won't change the field value to less than `1`.

The test I wrote passes on firefox, but not on electron. On electron nothing gets typed in the field

![Screenshot from 2022-05-04 19-18-01](https://user-images.githubusercontent.com/14757801/166744324-5f4165ef-c843-4e18-8e09-a096efa24b32.png)
![Screenshot from 2022-05-04 19-21-20](https://user-images.githubusercontent.com/14757801/166744232-7c104b59-3a82-4690-9cdb-afbf9c35f394.png)

### Desired behavior

The test should either pass in electron, or, if I am misusing the `{downArrow}` syntax, it should fail in firefox. 

### Test code to reproduce

To test the behavior I wrote:

```
 cy.get(sel("input-working_hours"))
   .type("{downArrow}{downArrow}")
   .should("have.value", 1);
```
where the first `{downArrow}` changes the empty value to `1` and the second `{downArrow}` does nothing, as intended. (in firefox)

The input field is a  simple `<input name="working_hours" type="number" min="1" data-testid="input-working_hours">`

### Cypress Version

^8.7.0

### Other

electron 93
firefox 98

**Comment by davidmunechika** [comment]
I can verify that this bug occurs and nothing gets typed on both Electron and Chrome browsers.
