### ISSUE TITLE
@cypress/schematic: can't `run` in headed mode

### ISSUE THREAD

**Issue by GerkinDev** [cypress-io/cypress#21332]
### Current behavior

Even when passing `headless: false` in `angular.json`, I can't find a way to set the `headed` flag on the actual runner.

### Desired behavior

Not setting `headless` or setting it explicitly to `false` through the builder should open cypress in headed mode

### Test code to reproduce

```sh
ng e2e --headless=false # Note that this is the default
```

### Cypress Version

9.6.0, but also affects ~9.5.x

### Other

https://github.com/cypress-io/cypress/blob/cb14ae62e7c4362d759ceb450f4af518ee486f90/npm/cypress-schematic/src/builders/cypress/index.ts#L70-L75

It seems that there is no way to actually set the `headed` flag explicitly. I kind-of fixed it by patching the schematic with this: 

```patch

--- a/node_modules/@cypress/schematic/src/builders/cypress/index.js
+++ b/node_modules/@cypress/schematic/src/builders/cypress/index.js
@@ -36,7 +36,8 @@ function initCypress(userOptions) {
     };
     const options = Object.assign(Object.assign(Object.assign({}, defaultOptions), userOptions), { 
         //@ts-ignore
-        dev: process.env.CYPRESS_ENV === 'test' });
+        dev: process.env.CYPRESS_ENV === 'test', headed: !userOptions.headless });
+        console.log(options)
     if (userOptions.configFile === undefined) {
         options.config = {};
     }
```

**Comment by davidmunechika** [comment]
I was able to reproduce this issue with a new Angular project. It appears there is no way to currently run Cypress headed in run mode with @cypress/schematic.

**Comment by admah** [comment]
`headed` has been added as a valid builder option for `run()` in [cypress/schematic](https://www.npmjs.com/package/@cypress/schematic) `1.7.0`.
