### ISSUE TITLE
@cypress/schematics: cypress binary is no longer installed with CLI v14

### ISSUE THREAD

**Issue by cexbrayat** [cypress-io/cypress#21346]
### Current behavior

Currently, when running `ng add @cypress/schematic` the Cypress binary is automatically installed

This is no longer the case when using Angular CLI v14 (currently v14.0.0-next.13), as the CLI introduced a breaking change that no longer runs postinstall scripts

See https://github.com/angular/angular-cli/releases/tag/14.0.0-next.13 for the breaking change and a potential solution

### Desired behavior

The schematics should still install the cypress binary out of the box with CLI v14+

### Test code to reproduce

```
npm i -g @angular/cli@14.0.0-next.13
ng new binary --defaults
cd binary
ng add @cypress/schematic --defaults --skip-confirmation
ng e2e
```

throws:
```
No version of Cypress is installed in: /Users/cedric/Library/Caches/Cypress/9.6.0/Cypress.app

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: /Users/cedric/Library/Caches/Cypress/9.6.0/Cypress.app/Contents/MacOS/Cypress

----------

Platform: darwin-x64 (21.4.0)
Cypress Version: 9.6.0
```

### Cypress Version

9.6.0

### Other

This can be workaround by installing the Cypress binary manually installed

**Comment by emilyrohrbough** [comment]
This was released as `@cypress/schematic v2.0.2` on Aug 9th.
