### ISSUE TITLE
Run Timed Out on DashBoard

### ISSUE THREAD

**Issue by Victor-Telemaque** [cypress-io/cypress#21348]
### Current behavior

![image](https://user-images.githubusercontent.com/73354664/166906488-c5f2b50d-0230-4651-a87a-af71e1cfaa5f.png)
Some test are timed out but (passed or failed) on github action side.

Moreover, i cant use github integration on cypress dashboard, dunno why.

Thanks for helping me.

Best Regards.

### Test code to reproduce

Cant copy, cause my repository is private

### Cypress Version

9.5.0

**Comment by conversaShawn** [comment]
@Victor-Telemaque 
Unfortunately, I can't say for sure. It does however seem to possibly coincide with an incident we were having. I recommend keeping an eye on both the [Cypress status page](https://www.cypressstatus.com/) and [GitHub Actions status page](https://www.githubstatus.com/).
