### ISSUE TITLE
if string 'AUTH' is used in env variable it became not accessible

### ISSUE THREAD

**Issue by RadwaSaleh** [cypress-io/cypress#21366]
### Current behavior

It's retrieved as undefined.

### Desired behavior

I should be able to give my env variables descriptive names

### Test code to reproduce

example:

```
  "APP_AUTH_TOKEN_URL": "url value",
  "AUTH_EXAMPLE": "token value"
```
  
  then get the values as `Cypress.env('APP_AUTH_TOKEN_URL')`

### Cypress Version

9.6.0

**Comment by jennifer-shehane** [comment]
Please provide the full test code where you are trying to use the env variable and where it is undefined. It may be relevant where you are calling this in the code.

**Comment by RadwaSaleh** [comment]
i tried AUTH and TOKEN and both didn't work when I upgraded to latest cypress version same code worked as expected

**Comment by mjhenkes** [comment]
@RadwaSaleh, I'm happy to hear this worked on the latest cypress version, sorry for the trouble.

**Comment by yorch** [comment]
@mjhenkes @jennifer-shehane actually, I could be wrong, but I don't think @RadwaSaleh said it worked, on the contrary, she said it didn't work after upgrading to latest version.

I'm actually experiencing something similar, we've been using version `8.2.0` for a long time and when I've tried to upgrade to both versions `9.6.*` and `10.0.*`, I no longer can read certain env variables that are defined outside of the cypress config file (it's defined in `environment` in the docker compose file that runs the Cypress image). Without any changes other than changing the cypress version used, the env variable `CYPRESS_ENV` is no longer available. There are other env variables defined in the same docker compose file (like `CYPRESS_USER`) that are still available when calling `Cypress.env()`, but no `SCALYR_ENV`.

I'm digging through the Cypress code base to figure where `config.env` is getting hydrated from `process.env` and the config file to see if there is any filtering going on, but still finding my way around the code base.

For reference, when I run `printenv` within the container, right before the cypress command is executed, I get:

```
BACKEND=backend
CI=1
CYPRESS_CACHE_FOLDER=/root/.cache/Cypress
CYPRESS_EMAIL=user@domain.com
CYPRESS_ENV=DEV
CYPRESS_PASSWORD=****
CYPRESS_RECORD_KEY=****
CYPRESS_REMOTE_DEBUGGING_PORT=31111
CYPRESS_trashAssetsBeforeRuns=true
DBUS_SESSION_BUS_ADDRESS=/dev/null
DEBUG=cypress:*
E2E_LOG_FILE=e2e.log
HOME=/root
HOSTNAME=123456
KEEP_PREVIOUS=true
NO_WAIT=false
NODE_PATH=/usr/local/lib/node_modules
NODE_VERSION=16.14.2
npm_config_loglevel=warn
npm_config_unsafe_perm=true
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/e2e
SHLVL=1
TERM=xterm
WEBAPP=webapp
YARN_VERSION=1.22.18
```

But when I print the cypress config object from within `e2e.setupNodeEvents`, I get:

```json
...
env: {
   EMAIL: 'test@test.com',
   REMOTE_DEBUGGING_PORT: 31111,
   RECORD_KEY: '********',
   CACHE_FOLDER: '/root/.cache/Cypress',
   PASSWORD: '******'
},
...
```

Thanks
