### ISSUE TITLE
Running "Cypress run" with multiple options from the Command Line does not work

### ISSUE THREAD

**Issue by achelonmm** [cypress-io/cypress#2136]
### Current behavior:

When running the command below, it's not working:
```
./node_modules/.bin/cypress run --browser chrome --config baseUrl=http://localhost:45/
```

### Desired behavior:
Cypress should start with the baseUrl configuration variable overriden and the browser being Chrome.

As a personal note, this may be because of inexperience or incorrect formating (I'm fairly new to Cypress, been using it for two weeks) as in the official Cypress doc it only gives one example using two different options (`--headed --no-exit`) and I'm using `--browser` and `--config`.

We need this to work as it's the command that will be executed in an automated task every night for E2E testing.

**Comment by Bkucera** [comment]
Try quotes around the url

**Comment by achelonmm** [comment]
I cannot as I have it using a VSTS variable. 
For me it looks like this:
./node_modules/.bin/cypress run --browser chrome --config baseUrl=$(myUrlVariable)

I don't know if I can put that variable with quotes tho.

**Comment by gaoxk** [comment]
I'm having a similar issue.
`npx cypress run --config baseUrl=http://localhost:3001 --browser chrome ` and
`npx cypress run --config baseUrl="http://localhost:3001" --browser chrome ` and
`npx cypress run -c baseUrl=http://localhost:3001 -b chrome `  and 
`npx cypress run -c baseUrl="http://localhost:3001" -b chrome `
all yeild 
```
npx: installed 1 in 1.496s
Path must be a string. Received undefined
C:\my\path\node_modules\cypress\bin\cypress

```

**Comment by dorothythurston** [comment]
I have found that in my case adding single quotes around the thing i am passing in to the -s flag fixed my problem. So it could be that @Bkucera had the right idea. The underlying library that cypress is using (commander) does allow for multiple flags so it is probably a parsing error in that library... it seems to choke on extra spaces or missing ' ' around the value

**Comment by jennifer-shehane** [comment]
There have been some improvements to the handling of these config options since this issue was opened. I suggest updating to the [current version of Cypress](https://on.cypress.io/changelog) and also using single quotes when passing values in the cli.

**Comment by jorshjorge** [comment]
Try using `-- --config baseUrl=http://localhost:45/` instead, thank you.
