### ISSUE TITLE
gettext value should be store for global function use, like as protractor and selenium

### ISSUE THREAD

**Issue by jenishgandhi7** [cypress-io/cypress#21372]
### What would you like?

get text value should be store into var and use that for other global function or file test validation use, like as protractor and selenium.

as currently unable to assign value to let for global use. 
![image](https://user-images.githubusercontent.com/8191015/167181757-f2713af2-d4cf-4a17-b736-834db36047a9.png)

As for automation test required gettext value use to other function validation with other page element.

**Comment by mjhenkes** [comment]
Could you provide the test code that you're currently writing to get this result?

**Comment by jenishgandhi7** [comment]
**spec.js**

```

describe("Create & cancel check; pay recurring bill", () => {

it("TC-1 - Create Check and cancel check from list page", () => {

       const checkCatg =  payBillsPage.action();  /
       CheckBillsPage.Validation(checkCatg)
}}

```

**function file**
payBillsPage.ts
```


export class PayBillsPage (){
    let checkCategory:string;
     payBillsLocator.categoryInfo().invoke("attr", "value").then(function ($elem) {
      checkCategory=$elem
      cy.log(checkCategory)  // Value print under log
    })

    cy.log("Outside"+checkCategory) //value undefine

return {checkCategory}

}

```

I tried different solution which but unable to solve this i getting undefined. this is just example.

**Comment by mjhenkes** [comment]
I've written up a simpler example:

```javascript
  it('displays two todo items by default', () => {

    cy.visit('https://example.cypress.io/todo')

    let textValue
    cy.get('.todo-list li').first().invoke('text').then(text => {
      cy.log(text) // This will log the invoked text.
      textValue = text
    })

    cy.log(textValue) // This will log as undefined
  })
```

The second `cy.log` command will not log 'text' as an artifact of how the cypress command queue is evaluated. We evaluate cypress commands up front before they are executed so that in this case at evaluation time we don't know that textValue will later be set to text.

To use the values returned in the .then block you will have to put the code that consumes them inside the block.
