### ISSUE TITLE
[sessions] Evaluate & Update Clear Page System Event Logs

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#21397]
### What would you like?

Sync notes:
- Clear Page
- Redesign or remove this? TBD
    - *Brian: i think we should keep this*
- Why is there an extra Clear Page at the very end of the session?

### Why is this needed?

Clearly indicate to users when and why we are clearing the page and removing session data. Current messaging and number of clear pages are confusing.

**Comment by emilyrohrbough** [comment]
1. Remove clearing the page before the validate (on create)
    1. Users don’t understand that validate purges the cache
    2. Users will DRY up code
5. Always clear the page at the end of the command - Revert the most recent change that removed that final “clear page”
    1. This restores the original specification

**Comment by duplessc** [comment]
So I have set experimentalSessionAndOrigin:true and testIsolation: "off" but when creating the session it still ends up clearing the page.

Cypress: 11.0.1
Node: 14.17.4
Chrome: 103

![image](https://user-images.githubusercontent.com/117908633/201090467-d879d6fe-d639-4411-a6ce-95c750b7b11c.png)

Code:
![image](https://user-images.githubusercontent.com/117908633/201090738-06a8be16-469c-40ed-a09e-2dc4cbcdd01c.png)

**Comment by emilyrohrbough** [comment]
@duplessc I was unable to repo the Clear Page with the code sample provided. Can you share a small repo?

**Comment by duplessc** [comment]
> @duplessc I was unable to repo the Clear Page with the code sample provided. Can you share a small repo?

@emilyrohrbough unfortunately no. I have to recreate a repo with just this command in it. I'd be happy sharing other details I can if needed
