### ISSUE TITLE
Multiple elements detected, but only one present

### ISSUE THREAD

**Issue by nemonemi** [cypress-io/cypress#21392]
### Current behavior

After updating to the latest version of both cypress and material-ui I have noticed that the existing tests asking for the single element are now reporting that there are 2 elements instead of one.
For assertions, we use cypress-testing-library and the `findByLabelText` method.

I am unsure who should be responsible for this behavior, so I've reported it on the cypress-testing-library page, but would also like to bring it to attention here since it's a big issue.
https://github.com/testing-library/cypress-testing-library/issues/214

### Desired behavior

Find element assertion should detect the correct number of elements.

### Test code to reproduce

`cy.findByLabelText(/^valid from/i).should('have.length', 1)`

This fails because it finds 2 elements.

### Cypress Version

9.6.0

**Comment by mjhenkes** [comment]
@nemonemi I am not able to recreate this issue. I created a test with the following:

index.html at root

```html
<input
    aria-describedby="name-helper-text"
    aria-invalid="false"
    class="MuiInputBase-input-hieRCO MuiFilledInput-input-gnEWXF gVXmpM gqxwhg MuiFilledInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd"
    disabled=""
    id="name"
    name="name"
    type="text"
    value="Certificate name 6"
/>
<span
    aria-label="Certificate name"
    class=""
    data-mui-internal-clone-element="true"
>
    Certificate name
</span>

```

cypress test
```javascript
describe('issue', () => {
    it('tests', () => {
        cy.visit('index.html')
        cy.findByLabelText(/^certificate name$/i).should('have.length', 1)
    })
})
```

Could you provide provide a repo with this issue recreated?

I'm using `@testing-library/cypress version: 8.0.2`

**Comment by nemonemi** [comment]
Quick update, this is actually the HTML that MUI's TextField produces:
```ts
<div class="...">
  <label class="..." data-shrink="true" for="name" id="name-label">
    <span aria-label="Certificate name *" class="" data-mui-internal-clone-element="true">Certificate name *</span>
  </label>

  <div class="...">
    <input aria-invalid="false" aria-describedby="name-helper-text" id="name" name="name" type="text" class="..." value="Certificate name 0">

    <div class="..."></div>
  </div>

  <p class="..." id="name-helper-text">
    <span class="...">18 / 100</span>
  </p>
</div>
```

**Comment by nemonemi** [comment]
I have this issue no longer after I've replaced my old and custom TextField component completely with the MUI v5 component.
