### ISSUE TITLE
How to use `--use-file-for-fake-video-capture` with `cypress run`

### ISSUE THREAD

**Issue by theolavaux** [cypress-io/cypress#21407]
### What would you like?

https://docs.cypress.io/api/plugins/browser-launch-api#Use-fake-video-for-webcam-testing
I followed the docs to override default video input to test my app, it works well with Chrome but not with Electron.

To be exact, I test with a `.mjpeg` file like so

`cypress/plugins/index.ts`
```js
/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on(
    'before:browser:launch',
    (
       browser = {
        name: '',
        family: 'chromium',
        channel: '',
        displayName: '',
        version: '',
        majorVersion: '',
        path: '',
        isHeaded: false,
        isHeadless: false,
      },
      launchOptions
    ) => {
      if (browser.family === 'chromium') {
        launchOptions.args.push(
          '--use-file-for-fake-video-capture=cypress/fixtures/assets/fake-video.mjpeg'
        );
      }

      return launchOptions;
    }
  );

  return config;
};

```

![image](https://user-images.githubusercontent.com/25274586/167471011-f384b002-d92b-4d4c-ac55-9014615bfdee.png)

The supplied video is still this green pie chart, does Electron need extra config steps ?

It seems that Electron supports this feature so I'm curious about why it's not working out of the box
https://github.com/electron/electron/issues/4505

### Why is this needed?

I need to test video upload both locally and in CI and it currently only works with `cypress open` not `cypress run`

**Comment by theolavaux** [comment]
I added a snippet a code snippet to my original post to explain my use case better

**Comment by mjhenkes** [comment]
@theolavaux, I put together a sample project that recreates the issue the fake video file not working with electron in either open or run mode

https://github.com/mjhenkes/webstream-fake-test

When using chrome i am able to see the file in both open and run mode.

When you run cypress, have you tried running it against chrome? 

`cypress run --browser=chrome` I would expect that to work.

**Comment by theolavaux** [comment]
I thought Electron was the only alternative to have a Chromium browser run headlessly! And I also thought that since that `-use-file-for-fake-video-capture` parameter was working in Chrome, it would work on Electron too because both are chromium-based. It definitely works with Chrome, still wondering why not Electron though but the issue is on their side right?

**Comment by mjhenkes** [comment]
I'm going to close this issue for now, We appear to be passing the flag correctly to electron, but electron doesn't appear to honor it.
