### ISSUE TITLE
Cypress not quitting due to chrome download popup

### ISSUE THREAD

**Issue by tommy0831** [cypress-io/cypress#21417]
### Current behavior

Running cypress tests through cypress.run in headless mode.  After run completes, it is does not exit after sending exit and close events.
`cypress:cli child event fired { event: 'exit', code: 0, signal: null } +2m
cypress:cli child event fired { event: 'close', code: 0, signal: null } +6ms`

I turned on headed mode to watch what's going on and it turns out that it was stuck because Chrome shows a "Download is in progress.  Quit chrome anyway?" popup.  The test is not downloading anything, and it was completed successfully.  I know this may not be a Cypress issue.  But, why does Cypress Chrome instance think it's downloading something when nothing is being dowloaded?  How can one force a quit?

<img width="1199" alt="Screen Shot 2022-05-09 at 5 29 35 PM" src="https://user-images.githubusercontent.com/98181057/167523203-346dfea6-a20e-47b9-8422-2775263df996.png">

### Desired behavior

* Cypress should exit after test completes.
* Ability to force a quit on chrome programmatically.

### Test code to reproduce

Use cypress.run to run test.

### Cypress Version

8.7

### Other

Cypress:    8.7.0                                                                              │
Browser:    Chrome 101

**Comment by tommy0831** [comment]
OK.  I think I found the root cause.  Behind the scene, Chrome is downloading something.  The test finishes before the background download finishes, so Chrome is giving that popup.  I don't know why Chrome is doing that.  The workaround I implemented was to intercept the calls.

`  // google downloads https://optimizationguide-pa.googleapis.com/downloads
  cy.intercept(/\.*googleapis\.com\/downloads/, (req) => {
    console.log('googleapis download INTERCEPTED');
    req.reply("console.log('Fake google download script loaded');");
  });`


<img width="1792" alt="Screen Shot 2022-05-09 at 7 18 29 PM" src="https://user-images.githubusercontent.com/98181057/167530307-16d4de0e-f639-48d5-a66c-c08f50df5cac.png">

**Comment by BlueWinds** [comment]
Hm. Looking into this, it looks like it's unfortunately a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1311753.

Looks like it will be fixed in Chrome 102. Not something we can really fix from the Cypress end. For now, if this is a serious/recurring problem for you, I'd recommend either downgrading to Chrome 99 or using another browser.

> Providing a quick update/summary for folks following along (including the experts in our Chrome help community forum who are seeing questions about this):

> This behavior appears when Chrome updates items in the background, such as machine learning models for certain features. This has likely always been the case, but more frequent background updates may have resulted in the behavior being easier to observe.

> [Comment 9](https://bugs.chromium.org/p/chromium/issues/detail?id=1311753#c9) introduces a change that will exclude these transient background downloads from appearing in the UI. This change has landed in M102, and should be available now to users on Chrome Canary. When M102 reaches stable, users that update should stop observing this behavior.

**Comment by BlueWinds** [comment]
(As a side note, this sort of background downloading of machine learning modules, which always happens but is only visible when they accidentally reveal it, is why I don't trust Chrome and don't use it - much prefer Firefox or Chromium).

**Comment by mjhenkes** [comment]
Closing this as a chrome issue that we cannot correct.
