### ISSUE TITLE
Add support for node 16.10+

### ISSUE THREAD

**Issue by admah** [cypress-io/cypress#21425]
### What would you like?

Currently, `.node-version` is set to `16.5.0`. I would like to see that updated to at least `16.10.0`.

### Why is this needed?

As we look to support Angular more (ie. cypress/schematic and angular-ct) it is a necessity to support >= 16.10.0 since that is a requirement for Angular 13+. 

cc: @jordanpowell88

**Comment by tbiethman** [comment]
We'll be on v16.13.2 with our bump to Electron v18: https://github.com/cypress-io/cypress/pull/21418

**Comment by admah** [comment]
@tbiethman that's perfect. Thanks!

**Comment by mjhenkes** [comment]
Closing as this will be addressed with #21418
