### ISSUE TITLE
[dashboard] doesn't get all data from CI run after update to the latest docker image cypress/browsers

### ISSUE THREAD

**Issue by DlgSHi** [cypress-io/cypress#21423]
### Current behavior

Currently we are using `cypress/browsers:node14.17.0-chrome91-ff89` image for our CI runs. But as far as we were using `chrome v.91` we decided to update the `chrome` version to `100` by updating the docker [image](https://hub.docker.com/layers/browsers/cypress/browsers/node14.17.6-chrome100-ff98/images/sha256-3f1ceb98712c697071ac194a0cae263a8b082af8ed418b7792dd9b0888a0338f?context=explore) `cypress/browsers:node14.17.6-chrome100-ff98` in this [PR](https://github.com/Sage/carbon/pull/5126)

But after the update we noticed that the `Dashboard` has no data about commit message and the committer as well.

![Screenshot 2022-05-10 at 14 21 21](https://user-images.githubusercontent.com/34001198/167627117-e35be4cc-cce3-48c4-adae-d1a001fd213c.png)

We also noticed that the older one image `node14.17.0-chrome91-ff89` is running on `Debian 10.9` os but the newly added `node14.17.6-chrome100-ff98` is running on `Debian 10.10`.

### Desired behavior

We would like to update version of `chrome` to have possibility to run on the latest version of browser. 

### Test code to reproduce

[GitHub action](https://github.com/Sage/carbon/actions/runs/2300086114)
[Dashboard](https://dashboard.cypress.io/projects/8458bb/runs/11554/overview)
[PR with revert](https://github.com/Sage/carbon/pull/5134)

### Cypress Version

9.6.0

**Comment by admah** [comment]
@DlgSHi that specific image is missing `git`. If you can update the node version, here is an updated [image](https://hub.docker.com/layers/browsers/cypress/browsers/node16.14.2-slim-chrome100-ff99-edge/images/sha256-44f4157bfb319fccf537b590841315c9f777937f02f930e9d295e5cbdeb02381?context=explore). If you need `14.17.0` I can create an updated image and publish it.

**Comment by DlgSHi** [comment]
@admah Hi, thanks for a quick reply, I would be wonderful. Unfortunately we have a restrictions for the `node` version and it could not be above `14.latest`. So that image we've used was the only one we can use with `chrome 100`

**Comment by admah** [comment]
@DlgSHi the new image can be found [here](https://hub.docker.com/layers/browsers/cypress/browsers/node14.17.6-slim-chrome100-ff99-edge/images/sha256-f1f20c067dbb4a54ccbc060f8d46b41b5d08fd74a863467ca35cdc00c238dbcd?context=explore). It has a base of `14.17.6` with latest Chrome, FF, and Edge browsers.
