### ISSUE TITLE
Cypress component tests fail to run when using @cypress/vite-dev-server@2.2.3

### ISSUE THREAD

**Issue by rstoneIDBS** [cypress-io/cypress#21434]
### Current behavior

Running Cypress component tests (Cypress 9.6.1) results in the following error message for all the tests:
"Cannot read properties of undefined (reading 'REACT_APP_SC_ATTR')"

### Desired behavior

The cypress component tests should run correctly as they do with @cypress/vite-dev-server@2.2.2

### Test code to reproduce

N/A
Standard component tests as per Cypress instructions, tests started with "cypress open-ct"
Uses cypress-image-snapshot-plugin and vite-dev-server, configured in plugins/index.js with:
```
module.exports = (on, config) => {
  if (config.testingType === 'component') {
    const { startDevServer } = require('@cypress/vite-dev-server');
    const { addMatchImageSnapshotPlugin } = require('cypress-image-snapshot/plugin');

    on('dev-server:start', (options) => startDevServer({ options }));
    addMatchImageSnapshotPlugin(on, config);
  }
};
```

cypress.json content:
```
{
  "component": {
    "componentFolder": "src",
    "testFiles": "**/*spec.{js,jsx,ts,tsx}",
    "viewportHeight": 600,
    "viewportWidth": 800
  },
  "video": false,
  "screenshotOnRunFailure": false
}
```

### Cypress Version

9.6.1

### Other

@cypress/vite-dev-server@2.2.3
vite 2.9.8
react 17.0.2

**Comment by rstoneIDBS** [comment]
"fix" is to revert to @cypress/vite-dev-server@2.2.2 for now

**Comment by mjhenkes** [comment]
@rstoneIDBS  Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

**Comment by yann-combarnous** [comment]
Same issue here...

**Comment by yann-combarnous** [comment]
Couldn't Cypress revert changes from 2.2.3?

**Comment by amoshydra** [comment]
Testing Cypress@10.0.2.

Facing the same issue: "Cannot read properties of undefined (reading 'REACT_APP_SC_ATTR')"

the variable process is defined. however it is assigned to an empty object `{}`. This behaviour breaks styled-component's logic below, as it tries to access property inside process.env

```ts
export const SC_ATTR: string =
  (typeof process !== 'undefined' && (process.env.REACT_APP_SC_ATTR || process.env.SC_ATTR)) ||
  'data-styled';
```
https://github.com/styled-components/styled-components/blob/7aa709ffbb826d0b1daa1b7e54b188c818298e22/packages/styled-components/src/constants.ts#L4-L6

---

For my local testing, I am going with a temporary workaround to populate the process env field before important styled-components like this:

```ts
// workaround-cypress-10-0-2-process-issue.js
global.process = global.process || {};
global.process.env = global.process.env || {};
```

```ts
// your-component.cy.tsx
import './workaround-cypress-10-0-2-process-issue'
import YourComponentThatUsesStyledComponent from './your-component';
```

**Comment by tomekbuszewski** [comment]
Hi, I am having the same issue when using Styled Components with Cypress 10.7.0 and cypress-vite 1.1.1. Unfortunately @amoshydra's fix doesn't help. Any ETA on fixing this?

**Comment by rstoneIDBS** [comment]
> Hi, I am having the same issue when using Styled Components with Cypress 10.7.0 and cypress-vite 1.1.1. Unfortunately @amoshydra's fix doesn't help. Any ETA on fixing this?

@amoshydra's fix worked for me, I'm using 10.4.0 but have used every release since 10.0.0 with the fix. In my case I added it to 'component.js' as pretty much all my components use Styled Components.
I've noticed you mention 'cypress-vite', which suggests you aren't component testing which is what this issue is related to so you might need to find a different solution for e2e tests :(

**Comment by tomekbuszewski** [comment]
E2Es work flawlessly, it's component testing (which requires actually rendering) broken for me. I've mentioned cypress-vite, as it is a dependency and I use Vite as a bundler, so, you know, provided this information as it might be helpful ;)

**Comment by rstoneIDBS** [comment]
> E2Es work flawlessly, it's component testing (which requires actually rendering) broken for me. I've mentioned cypress-vite, as it is a dependency and I use Vite as a bundler, so, you know, provided this information as it might be helpful ;)

Which version of @cypress/vite-dev-server are you using for the component tests then? I'm on 3.1.0. With this and the changes mentioned above the component tests run as expected. Here's the cypress.config.js I use:
`
const { defineConfig } = require('cypress');

module.exports = defineConfig({
  video: false,
  screenshotOnRunFailure: false,
  component: {
    viewportHeight: 600,
    viewportWidth: 800,
    specPattern: 'src/**/*.spec.{js,jsx,ts,tsx}',
    devServer: {
      framework: 'react',
      bundler: 'vite',
    },
  },
});
`
I'm using Vite 3.07

**Comment by rstoneIDBS** [comment]
> E2Es work flawlessly, it's component testing (which requires actually rendering) broken for me. I've mentioned cypress-vite, as it is a dependency and I use Vite as a bundler, so, you know, provided this information as it might be helpful ;)
> 
> **edit**
> 
> Adding mentioned lines to `component.ts` does help! I was adding it to the test file, which wasn't working. Thanks for hinting this, @rstoneIDBS!

Ah, your edit arrived just as I replied. Glad you got it working :)

**Comment by lmiller1990** [comment]
`REACT_APP_SC_ATTR ` error is related to styled components, I debugged this and found it's an upstream bug - workaround here: https://github.com/cypress-io/cypress/issues/22678#issuecomment-1204899534, although it's been a while - if you update all libraries to the latest one, it's likely fixed by now, most likely in Vite 4 (grab Vite 4 and the latest Cypress).

LMK if you still have this issue.

**Comment by rstoneIDBS** [comment]
@lmiller1990 - the problem still persists for me if I remove the fix mentioned earlier, I'm on:

"@cypress/vite-dev-server": "^5.0.3"
"cypress": "^12.6.0",
"vite": "^4.1.4",
"styled-components": "^5.3.6"

So latest versions of everything.

I tried switching to the fix you mention here: https://github.com/cypress-io/cypress/issues/22678#issuecomment-1204899534
But this fails with a different error:
```
  > Cannot read properties of undefined (reading 'NODE_DEBUG')
```

For now I'm going to stick with the existing "fix"

**Comment by lmiller1990** [comment]
I'm not familiar with `styled-components` - why does it use a Node.js API, `process`, at all? If it's a front-end library, it shouldn't really do that. Is 5.0.6 the latest version of Style Components? I wonder if there's a bug in their  code - I don't see why it would want to access `process` in the browser, unless it's relating their [babel and SSR](https://github.com/styled-components/styled-components#babel-macro) feature?

It's certainly possible it something on our end. Stubbing out `process` as suggested seems like the most reasonable solution at this point. If it turns out we are doing something incorrectly in our `vite-dev-server`, we can re-open and investigate.

**Comment by lmiller1990** [comment]
Hm, we do have https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/client/initCypressTests.js#L81-L82, I wonder if this is a non-ideal.

**Comment by rstoneIDBS** [comment]
> I'm not familiar with `styled-components` - why does it use a Node.js API, `process`, at all? If it's a front-end library, it shouldn't really do that. Is 5.0.6 the latest version of Style Components? I wonder if there's a bug in their code - I don't see why it would want to access `process` in the browser, unless it's relating their [babel and SSR](https://github.com/styled-components/styled-components#babel-macro) feature?
> 
> It's certainly possible it something on our end. Stubbing out `process` as suggested seems like the most reasonable solution at this point. If it turns out we are doing something incorrectly in our `vite-dev-server`, we can re-open and investigate.

At a guess, styled-components will be running translation code as part of the build process (which is running in 'dev' server mode I assume?) so its not unreasonable for it to be using Node features.

**Comment by lmiller1990** [comment]
Sure, but it should be stripping out any Node.js code before outputting a browser bundle. I wonder if we've got something misconfigured in our Vite Dev Server...

**Comment by gooddays-cdf** [comment]
Facing the same error even after the workaround, this is my cypress/support/component.tsx
```
import { mount } from 'cypress/react18';
import React from 'react';
import { ThemeProvider } from 'styled-components';

import './commands';

global.process = global.process || {};
global.process.env = global.process.env || {};

declare global {
  namespace Cypress {
    interface Chainable {
      mount: typeof mount;
    }
  }
}

Cypress.Commands.add('mount', (component, options) => {
  mount(<ThemeProvider theme={{}}>{component}</ThemeProvider>, options);
});
```

**Comment by MSandeep96** [comment]
Facing the same error even with the workaround, this is my cypress/support/component.tsx

```
import { mount } from 'cypress/react18';
import React from 'react';
import { ThemeProvider } from 'styled-components';

import './commands';

global.process = global.process || {};
global.process.env = global.process.env || {};

declare global {
  namespace Cypress {
    interface Chainable {
      mount: typeof mount;
    }
  }
}

Cypress.Commands.add('mount', (component, options) => {
  mount(<ThemeProvider theme={{}}>{component}</ThemeProvider>, options);
});
```

**Comment by lmiller1990** [comment]
Did you add that workaround to `vite.config`?

```
import { mount } from 'cypress/react18';
import React from 'react';
import { ThemeProvider } from 'styled-components';

import './commands';

global.process = global.process || {};
global.process.env = global.process.env || {};
```

This will not work, the import is above where you defined `global.process`.

**Comment by MSandeep96** [comment]
I figured as much and tried moving the import below the global workaround. I was getting a tsc error saying imports must be at the top of the file.

**Comment by lmiller1990** [comment]
Did that fix the error for you?

**Comment by rstoneIDBS** [comment]
> I figured as much and tried moving the import below the global workaround. I was getting a tsc error saying imports must be at the top of the file.

Just move your
```
global.process = global.process || {};
global.process.env = global.process.env || {};
```

code into a separate file and import that before `import './commands';` then, this is pretty much exactly what I do (I import the 'fix' inside of `commands`)

**Comment by lmiller1990** [comment]
Okay, sounds like this is solved for now. I am unsure about the original error, but this seems like a reasonable work around for now.
