### ISSUE TITLE
Nuxt Example

### ISSUE THREAD

**Issue by lanbau** [cypress-io/cypress#2143]
### Current behavior:
There isn't any.

### Desired behavior:
A simple example on how to use cypress with nuxt.js

**Comment by jennifer-shehane** [comment]
I created a new issue in our [example recipes repo](https://github.com/cypress-io/cypress-example-recipes) to add a new recipe for nuxt.js here: https://github.com/cypress-io/cypress-example-recipes/issues/167. Our example recipes are open source and contributions are welcome. 😄

**Comment by melrefaie** [comment]
@lanbau  here is an example for using [Nuxt.js](https://github.com/nuxt/nuxt.js) + [Cypress](https://github.com/cypress-io/cypress)

https://github.com/melrefaie/nuxt-cypress

**Comment by blowsie** [comment]
@jennifer-shehane has the example mentioned been removed? I cant find it on here
https://github.com/cypress-io/cypress-example-recipes

**Comment by jennifer-shehane** [comment]
There is currently an issue open to add a Nuxt.js example to the recipe repo. No one has added the actual example to the repo yet. https://github.com/cypress-io/cypress-example-recipes/issues/167

**Comment by warheartvik** [comment]
https://github.com/bahmutov/cypress-vue-unit-test/tree/master/cypress/integration here's an example
