### ISSUE TITLE
Cypress not loading page headless after click login button

### ISSUE THREAD

**Issue by TestSV2019** [cypress-io/cypress#21446]
### Current behavior

Hi there, When i run my script **_headless_** seems not load the next page, the video recorded after execute it, shows the following:
https://i.stack.imgur.com/wVF0g.jpg
and fails after that with a timeout error: https://i.stack.imgur.com/hB1Mb.png

Also, tried headless in 3 browsers (electron, chrome, firefox)but no success. Important point: this works perfect in protractor : headed and headless, but need it to work in cypress and headless. I'm using version 9.6.1 and tried as well with 8.5.0 but no success , Please help.

### Desired behavior

This needs to work in cypress and headless. 

### Test code to reproduce

here the test: 
context('TS001-login', () => {

beforeEach(() => {
  cy.visit('/');
})
const userName = "sdfgsdfg";
const passwrd = "gsdfgsdgg";
it.only('login with valid user and password', () => {  
  cy.get('#j_username', {timeout : 31500}).type(userName);
  cy.get('#j_password', {timeout : 31500}).type(passwrd);
  //cy.contains('Login').click({force: true});
  cy.contains('Login').type('{enter}');      
  cy.get('#logout', {timeout : 71500}).should('be.visible');
  cy.wait(2500);
});

it.only('login with invalid user and valid password', () => {
  cy.get('#j_username', {timeout : 31500}).type('userName');
  cy.get('#j_password', {timeout : 31500}).type(passwrd);
  cy.contains('Login').click({force: true});
  cy.get('#error').should('contain', errorLP1);
  cy.wait(2500);
});

here the cypress.json: 
{
"baseUrl": "http://salesportal-uat.xxxxx/",
"ignoreTestFiles": "**/ignore/*.spec.js",
"chromeWebSecurity": false,
"viewportWidth": 1280,
"viewportHeight": 720,
"defaultCommandTimeout": 30000,
"pageLoadTimeout": 60000,
"requestTimeout": 20000,
"retries": {
    "runMode": 1,
    "openMode": 1
},
"experimentalSessionAndOrigin": true
}

Here my support/index.js : 
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  });

### Cypress Version

9.6.1

**Comment by TestSV2019** [comment]
Ok guys, i did some more test tried **headless** edge browser and it passed, but not working in electron or chrome (tried diff versions 98, 92 and 84). Why is that ? Looks like after click Login button (headless mode) can not get the next page.  Can you please tell me if this is a cypress bug or not?. My problem is that the scripts need to run in chrome or firefox as a company request.
here the screenshots headless edge browser (extracted from video): https://ibb.co/0QFJ852 ; https://ibb.co/THjyFrT

Pls help

**Comment by TestSV2019** [comment]
I cant give company information here or the web portal code. 
The only thing I know is that the web portal the script i posted before, a similar one works as a charm in protractor but not in cypress. I posted screenshots, what else do you need. 
The portal that i intend to automate has the following :
![image](https://user-images.githubusercontent.com/53199847/169937923-fb030858-22a2-4900-928d-785eeb97759f.png)

**Comment by gcsHeyLaika** [comment]
@TestSV2019 Did you find any solution apart from running it in edge? I am facing the same issue...
