### ISSUE TITLE
Multiple zombie processes when running Cypress inside the Docker with Node

### ISSUE THREAD

**Issue by daria-graf** [cypress-io/cypress#21443]
### Current behavior

When running Cypress tests in an infinite loop inside a docker container and starting the test script with `node cypress.js`, we can see a huge amount of zombie (`<defunct>`) processes. 
When starting the same cypress-test.js file inside the docker container by using a shell script - all child processes are killed correctly, so no zombies are left.
Due to this bug, it is impossible to run cypress tests using 'pm2' or 'node' inside a docker container. At one point all processes just stop, because no free PID is left, so no new process can be started.

Tested with Cypress Version: 7.7.0, 9.6.1

### Desired behavior

No <defunct> zombie processes should appear, when running cypress tests synchronously inside a docker container by using `ENTRYPOINT [ "node", "./cypress-test.js" ]`

### Test code to reproduce

**Dockerfile:**

```
FROM cypress/browsers:node14.16.0-chrome90-ff88

RUN mkdir /opt/prj/
WORKDIR /opt/prj/
COPY package.json package-lock.json *node_modules /opt/prj/

RUN npm install
RUN $(npm bin)/cypress verify

COPY . /opt/prj/
ENTRYPOINT [ "node", "./cypress-test.js" ]
```

**cypress-test.js:**
```
const cypress = require('cypress');
const TEST_FOLDER_PATH = process.cwd() + '/cypress/integration/test/';

(async () => {
    while (true) {
        const result = await cypress.run({
            spec: TEST_FOLDER_PATH + 'test.spec.js',
            video: false
        });
    }
})();
```

**/cypress/integration/test/test.spec.js**
```
describe('Test', () => {
    it('should be true', () => {
        expect(1).to.equal(1);
    });
});

```
**cypress.json**
```
{
  "pluginsFile": "cypress/plugins/index.js",
  "retries": {
    "runMode": 1,
    "openMode": 0
  },
  "defaultCommandTimeout": 15000,
  "video": false,
  "videoCompression": false,
  "videoUploadOnPasses": false,
  "viewportWidth": 1280,
  "viewportHeight": 720
}

```
Start docker:
```
> docker build . -t cypress
> docker run cypress
```
Look up the name of the running docker container and execute:
```
> docker exec -it <container_name> bash
> ps aux
```

<img width="948" alt="Bildschirmfoto 2022-05-11 um 23 18 57" src="https://user-images.githubusercontent.com/11724048/167949489-817dd765-2236-4343-9d2a-6abc6d001349.png">

_______________________________________________________________________________________________
___________________ EXAMPLE WITH NO ZOMBIES____________________________________________
When replacing the ENTRYPOINT in the Dockerfile with:
```
RUN ["chmod", "+x", "/opt/prj/commands.sh"]
ENTRYPOINT [ "./commands.sh" ]
```

**commands.sh**
```
#!/bin/bash
node cypress-tests.js
```

NO Zombies

<img width="1747" alt="Bildschirmfoto 2022-05-11 um 23 26 43" src="https://user-images.githubusercontent.com/11724048/167950541-417002d3-55b9-42d2-a054-1478b95a49f7.png">

### Cypress Version

7.7.0, 9.6.1

**Comment by dgrafova** [comment]
The article could be helpful to understand, why the example above works fine with the 'bash' and why zombies can appear inside a docker container https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/. Just in case someone else has the same problem.

**Comment by mjhenkes** [comment]
@dgrafova, Thank you for the detailed issue. I've been able to reproduce the issue and have a sample issue here: https://github.com/mjhenkes/docker-zombie-processes

**Comment by mjhenkes** [comment]
Based on the article you included, it seems we may have two solutions:

1. Check to make sure processes are being properly terminated in cypress.
2. Add the mentioned script in the article to clean up zombie processes, This would probably be the quicker fix.

**Comment by BlueWinds** [comment]
@daria-graf - Try adding `--init` to the docker run command. https://docs.docker.com/engine/reference/run/#specify-an-init-process

`docker run --init cypress`

This is actually a docker issue, not a Cypress one - your entrypoint, `commands.sh`, is PID 1 inside the docker container. As explained in the article @mjhenkes linked, in linux PID 1 has the special responsibility of adopting orphaned processes (like the `Cypress` processes spawned, and the browser processes that Cypress in turn creates) and waiting for them to exit.

Since commands.sh doesn't do this, orphan processes pile up - the loop spawns new processes, but nothing ever reaps the zombies after they exit.

Fortunately, docker has implemented a solution for this in the years since that article was written. Using `--init`, docker will insert [tini][https://github.com/krallin/tini] as PID 1, whose sole purpose is to clean up zombie processes and otherwise execute your command as normal. Quick fix!

**Comment by daria-graf** [comment]
@BlueWinds thank you for your comment, but i disagree that it is "a docker issue". It is just the way docker works. The documentation of the library you posted ([tini](https://github.com/krallin/tini) says it very good: "It **protects** you from **software that accidentally creates zombie processes**". So i believe cypress is not waiting and killing its child processes (browser, video recording etc.) properly. The "docker --init" command or starting a script by using a shell script just help to clean up the cypress' childs, but the cypress should actually be responsible for that.

**Comment by BlueWinds** [comment]
@daria-graf - I stand corrected, you are absolutely right. I wasn't reading your sample script correctly, and thought it was leaving the zombies `Cypress` processes itself, which is not the case.

With that said, I'm not sure this is going to be easy to prioritize for the team. I'm reopening, but doubt we'll have time to take a look - if you or another contributor wants to take a crack at auditing how we open processes and properly waiting for them, feel free to ping me on a PR and I'll take a look.

--init / tini remains at least a valid workaround though.
