### ISSUE TITLE
SelectFile is not working for the csv file format.

### ISSUE THREAD

**Issue by dhakalsamundra** [cypress-io/cypress#21447]
### Current behavior

When running the file upload with the cypress, the csv file is not getting recognise while uploading the file. If I upload the same file manually, it will upload as csv. But when I tried to upload the csv file via automation, there is validation error saying Please select the csv file for same file which was working via manual upload. Am I missing something here?
please check the attached video below.

https://user-images.githubusercontent.com/40796489/167999754-df46f28f-ac59-47e7-9008-a0423918bafb.mov

### Desired behavior

File should be in csv format while uploading.

### Test code to reproduce

`cy.get("input[type='file']").selectFile("cypress/fixtures/contributors.csv");`

### Cypress Version

9.5.0

**Comment by BlueWinds** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. This does not mean that your issue is not happening - it just means that we do not have a path to move forward, since there's nothing here for me to run and debug.

Basically - the video shows that there's an issue. Your one-line code snippet doesn't give me any clues as to what's causing it. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) which can help us help you.

**Comment by dhakalsamundra** [comment]
The issue here is just to check the selectFile is not uploading the csv file. If you add the csv file in fixture folder and using the selectFile, if you upload the same csv file via cypress, it seems like there is no csv format while if I add the same csv file manually, it get uploaded as csv which is the problem that I am facing.

To reproduce this issue in your side for investigating, you should have one csv file and try to upload it using the selectFile.
Just ignore all the javascript that I used. I used those to delete some column and paste the update one in fixture csv file.


Here is the csv file attached and the cypress code to upload the csv file.
[contributors.csv](https://github.com/cypress-io/cypress/files/8684271/contributors.csv)
![Screenshot 2022-05-13 at 8 20 25](https://user-images.githubusercontent.com/40796489/168216580-c50f0981-587a-44c7-bb54-9fd0299ef16f.png)

**Comment by BlueWinds** [comment]
You haven't provided the most important aspect though - your application. I can't debug why your test isn't working with your application via a screenshot of a test.

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide - ideally, a repository that I can clone and execute myself. https://github.com/cypress-io/cypress-test-tiny is a good basis.

**Comment by dhakalsamundra** [comment]
I can not share you the whole code. Do you have any example repos where you have upload the csv file using selectFile?

**Comment by jitenderchand1** [comment]
@dhakalsamundra could you please post your solution here, I am facing the same problem.

**Comment by dhakalsamundra** [comment]
I have not get any solution. I can add the csv file but if there is any validation of file format, then it will show the validation error while manually adding won't show it. Are you also facing exactly the same, @jitenderchand1 ?

**Comment by divyagupta301** [comment]
@dhakalsamundra - Hi, do you have any update on this issue? Is this issue fixed in the latest version of cypress. I am using following versions:

 "cypress-file-upload": "^5.0.8",
 "cypress": "9.4.1",

**Comment by vincezipparro** [comment]
This is happening for me as well except with `pdf`'s, has there been any workaround discovered?

**Comment by jingMYOB** [comment]
This way works for me, so put it here for reference if anyone needed.

"cypress": '^12.17.0'

`
cy.fixture('fileName').as('alias');  //Detail can be found in fixture doc. 
cy.get('label[for=""]').selectFile({
  contents: '@alias',
  fileName: 'fileName.csv',
  mimeType: 'text/csv',
  lastModified: Date.now(),
})
`

**Comment by jyangTWer** [comment]
This way works for me, put it here for reference if anyone needed.

"cypress": "^12.17.0"

cy.fixture('fileName').as('alias');
cy.get('label[for=""]').selectFile({
contents: '@alias',
fileName: 'fileName.csv',
mimeType: 'text/csv',
lastModified: Date.now(),
});
