### ISSUE TITLE
InvocationDetails is empty during component testing

### ISSUE THREAD

**Issue by larsk2009** [cypress-io/cypress#21448]
### Current behavior

During component testing, the `InvocationDetails` are not filled in, so the `fileUrl` can't be retrieved. Even the `Cypress.spec.relative` is empty. See [this issue](https://github.com/archfz/cypress-terminal-report/issues/143) for the original source of this issue.

### Desired behavior

`InvocationDetails` should be filled so the `fileUrl` can be retrieved.

### Test code to reproduce

Just run any test in component testing and try to retrieve these details. I only see this issue in Firefox myself.

### Cypress Version

9.5.2

**Comment by mjhenkes** [comment]
Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

**Comment by larsk2009** [comment]
Nice, I am really excited for more/better component testing!

**Comment by villelahdenvuo** [comment]
@mjhenkes I'm getting the same error with regular E2E tests, you can see my comment on the linked issue.

**Comment by ZachJW34** [comment]
Is this still an issue with Cypress > 10.0.0 @larsk2009?
