### ISSUE TITLE
cy.origin test hangs when visiting inside a cy.origin block

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21453]
### Current behavior

A simple test to visit cypress.io in a cypress.io `cy.origin` block hangs.

### Desired behavior

The test should not hang.

### Test code to reproduce

```javascript
it('navigates', () => {
  cy.origin('https://www.cypress.io/', () => {
    cy.visit('https://www.cypress.io/')
    cy.url().should('eq', 'https://www.cypress.io/')
  })
})
```

### Cypress Version

9.6.1

**Comment by AtofStryker** [comment]
It looks like tests inside of `https://www.google.com` also hang, but looks related to accessing a cross origin parent frame referencing `window.top`. Setting `chromeWebSecurity` to `false` seems to fix the issue.
![](https://user-images.githubusercontent.com/3980464/168890951-c287a2b5-8007-47f8-8806-030535c54864.png)

![](https://user-images.githubusercontent.com/3980464/168890869-9516b7a7-12cf-426d-9da9-adfd70ac426f.png)


sample test looks something like this:
```js
  it('go to google', () => {
    cy.visit('/fixtures/primary-origin.html')
    cy.get('a[data-cy="request-link-to-google"]').click()
    cy.origin('https://www.google.com', () => {
      cy.url().should('eq', 'https://www.google.com/')
    })
  })
```

**Comment by etavenerInmarsat** [comment]
I've got a similar case of using 'origin' and it hangs. No errors, just doesn't proceed. I use this for a login page, which sometimes works and sometimes hangs.

Any update?

**Comment by AtofStryker** [comment]
@etavenerInmarsat are you using `Google Chrome` to visit `google.com` inside `cy.origin`? That currently doesn't work for a different reason related to #22987

**Comment by mjhenkes** [comment]
This test works except for the uncaught exception thrown by the cypress.io webpage. Handling that exception allows the test to pass without hanging:

```javascript
it('navigates', () => {
  cy.origin('https://www.cypress.io/', () => {
    Cypress.on('uncaught:exception', () => {
      return false
    })

    cy.visit('https://www.cypress.io/')
    cy.url().should('eq', 'https://www.cypress.io/')
  })
})
```
