### ISSUE TITLE
.select unable to find option when value given is a number

### ISSUE THREAD

**Issue by edudelta** [cypress-io/cypress#21463]
### Current behavior

When trying to select and value given is a number, Cypress fails to find the option value and fails. However, when it's changed to string, it finds and passes.

### Desired behavior

According [docs](https://docs.cypress.io/api/commands/select#Arguments) it receives strings and numbers.

### Test code to reproduce

Index.html as documentation
```
<html lang="en">
  <body>
    <form>
      <select>
        <option value="456">apples</option>
        <option value="457">oranges</option>
        <option value="458">bananas</option>
      </select>
    </form>
  </body>
</html>
```

example.js
```/// <reference types="cypress" />
it('it will fail', () => {
  const selection = 457;
  cy.visit('index.html')
  cy.get('select').select(selection);
})
it('it will pass', () => {
  const selection = 457;
  cy.visit('index.html')
  cy.get('select').select(selection.toString());
})
```

### Cypress Version

9.6.1

### Other
Current result:
Timed out retrying after 4000ms: cy.select() failed because it could not find a single <option> with value, index, or text matching: 457

**Comment by BlueWinds** [comment]
@edudelta - HTML values are always strings. In most cases Cypress uses strict equality, and `457 !== "457"`, so what you are experiencing is the intended behavior.

**Comment by edudelta** [comment]
Hi @BlueWinds !
Yes, html values are always strings and I was expecting a cast to string instead using as index.
Thank you.
