### ISSUE TITLE
Cypress test running very slow and sometime crash the test runner.

### ISSUE THREAD

**Issue by VaghasiyaKrupal** [cypress-io/cypress#21469]
### Current behavior

I have implemented the cucumber framework to my cypress test. But some script is hanging in between run and running very slow. Also, the test runner crashed sometime.

Below is the image that I am facing the issue with. It will fail to visit the URL because of a hanging issue. Error is below
![image](https://user-images.githubusercontent.com/45596703/168321110-d4081382-44c0-43cf-85c6-15fadc67169c.png)
I have given maximum timeout and the page is also loaded but still, it will show test fails due to the page is not loaded by the given timeout.

Sometimes test runner is crashes and below is the snapshot for avoidance.
![image](https://user-images.githubusercontent.com/45596703/168316493-bf5a94d8-fd84-499e-a1b5-eda8923a8e2a.png)

### Test code to reproduce

To reproduce the issue please follow the below steps.
1. clone `https://github.com/VaghasiyaKrupal/cucumber-issue.git`
2. Install all dependencies using `npm install`
3. run `npx cypress open`
4. Run `ProjectProfile.feature` OR `Event.feature` OR `HubActivity.feature` file

Must run `ProjectProfile.feature` and `HubActivity.feature` file.

### Cypress Version

9.5.4

### Other

The test is hanging in between runs and sometimes the test runner is crashed. Please you are not able to reproduce the issue please try to run `3 - 4` times you will definitely face the issue.

**Comment by mjhenkes** [comment]
@VaghasiyaKrupal, I'm sorry that you're seeing this issue. We've investigated it previously in issue https://github.com/cypress-io/cypress/issues/21353, specifically comment https://github.com/cypress-io/cypress/issues/21353#issuecomment-1120432116. It seems that you're having some bad interactions between plugins outside of cypress' control. The reason cypress appears to hang is due to your long timeouts.

**Comment by VaghasiyaKrupal** [comment]
@mjhenkes I am not using any plugins in this script. But it's okay if you don't want to take it seriously and also no hope in `Cypress`.
