### ISSUE TITLE
Write `cy.origin` integration tests for Azure Active Directory

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21476]
### What would you like?

Each of these `modifyObstructiveCode` tasks should include two tasks

1. Implement this authentication provider in the real world app.
2. Test logging in via the authentication provider in the real world app.
  * This may involve modifying modifyObstructiveCode or other tasks.

### Why is this needed? 

Workflows using Azure Active Directory for authentication currently cannot succeed due to frame busting.

#### Related issues:
* #21307

**Comment by mschile** [comment]
Hi @pedrocarloto, we have https://github.com/cypress-io/cypress/issues/21474 logged to solve Google Auth.

**Comment by akamud** [comment]
Hi, do we have any guide on how to write the `cy.origin` for a new SSO?
