### ISSUE TITLE
Remove `Cookies.preserveOnce` and `Cookies.defaults`

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21472]
`Cookies.preserveOnce` and `Cookies.defaults` were deprecated in 9.7.0 and have been replaced with `cy.session`. They can now be removed.

**Comment by emilyrohrbough** [comment]
Quick audit, when these are removed, the following `Cookies.preserveOnce ` issues will no longer be valid:
- https://github.com/cypress-io/cypress/issues/5409
- https://github.com/cypress-io/cypress/issues/8954
- https://github.com/cypress-io/cypress/issues/8955
- https://github.com/cypress-io/cypress/issues/15166
- https://github.com/cypress-io/cypress/issues/15223
- https://github.com/cypress-io/cypress/issues/17183

When these are removed, the following `Cookies.defaults` issues will no longer be valid:
- https://github.com/cypress-io/cypress/issues/9121
- https://github.com/cypress-io/cypress/issues/14617
