### ISSUE TITLE
Write `cy.origin` integration tests for Google Authentication

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21474]

**Comment by Anshita-Bhasin** [comment]
Hi @mjhenkes, Is there any update on Google Oath2 Login (SSO Login)?

**Comment by nagash77** [comment]
We also want verification on how other testing frameworks respond to Google Auth.  Including Puppeteer and Playwright.  Make sure we are on track with their limitations

**Comment by JaviRpo** [comment]
Hi @AtofStryker, Is there any update on Google Oath2 Login (SSO Login)?

**Comment by AtofStryker** [comment]
For support within Google Chrome, please follow #22987.
For support within Firefox (which there is a current work around with `mkcert` and securing localhost), please see #22988
