### ISSUE TITLE
Remove visiting about:blank in navigation.ts

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21487]

**Comment by emilyrohrbough** [comment]
👀  Curious about this one.

**Comment by kshastri** [comment]
@mjhenkes - could you share more details here. Being new to Cypress, I may need more details and would like to work on this one (or any other issue of my interest).
Does it mean removing the usage of `currentlyVisitingAboutBlank` or something else?

**Comment by mschile** [comment]
@kshastri, thank you for your interest in helping out with this issue but this one is more for internal development. I would encourage you to look at any of the issues with the [good-first-issue](https://github.com/cypress-io/cypress/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label to see if any of those interest you.

**Comment by mschile** [comment]
Closing since test isolation can be turned off so this functionality is still needed.
