### ISSUE TITLE
I need to insert a different fake video in each test.

### ISSUE THREAD

**Issue by LucyQA94** [cypress-io/cypress#21499]
### What would you like?

Hello, 
I work for a video identification company and I am automating video identifications with Cypress and Javascript. 
This means that for each test I need to insert a different video. 
Currently I have found a way to insert a single video from the index (within cypress plugins) but I can't find a way to insert several videos, within the tests. Is it possible that there is a feature for this? 
You would make me very happy. 
Thank you very much.

### Why is this needed?

Need insert different fake videos in differents tests.

**Comment by mjhenkes** [comment]
I believe that Chrome allows you to insert one fake video file per launched instance.

This may not be what you're looking for but you could write a custom plugin to vary the video file based on the spec name.

Here's a simple example that will change the fake video used for the spec if the spec contains the term 'videoA'.

enable the `experimentalInteractiveRunEvents` feature flag in cypress.json

cypress/plugins/index.js
```javascript
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  let currentSpec

  on('before:spec', (spec) => {
    currentSpec = spec.name
  })

  on('before:browser:launch', (browser = {}, launchOptions) => {
    const videoName = currentSpec.includes('videoA') ? 'akiyo_qcif.y4m' : 'deadline_qcif.y4m'

    if (browser.family === 'chromium') {
      // Mac/Linux
      launchOptions.args.push(
        `--use-file-for-fake-video-capture=cypress/fixtures/${videoName}`,
      )

      // Windows
      // launchOptions.args.push('--use-file-for-fake-video-capture=c:\\path\\to\\video\\my-video.y4m')
    }

    return launchOptions
  })
}
```

**Comment by LucyQA94** [comment]
Hello @mjhenkes, thank you so much for the possible solution.
Today i will try insert this code with this configuration in the cypress plugin.
I will keep you informed if I implement this solution and I don't get it or have any problems.

Kind regards and have a nice day.

**Comment by LucyQA94** [comment]
Hello again, I has been implemented this configuration in my cypress framework and it works.

After all, as I was commenting, it would be nice if the video we want could be inserted directly into the test, since if we have many tests it could cause problems to have so much code in the cypress plugin.

I put in this issue the solution implemented in my framework:
1. First put "experimentalInteractiveRunEvents": "true" -> feature flag in cypress.json
2. Put inside on "cypress/plugins/index.js":

/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */
const fs = require("fs-extra");
const path = require("path");

const fetchConfigurationByFile = file => {
  const pathOfConfigurationFile = `config/cypress.${file}.json`;

  return (
    file && fs.readJson(path.join(__dirname, "../", pathOfConfigurationFile))
  );
};

const mapTestNameToVideoFilePath = (env, testName) => {
  console.log('TEST_NAME: ', testName)
  if (testName.includes('test-dni-positive-case.spec')) {
    return env.DNI
  } else if(testName.includes('test-nie-positive-case.spec')) {
    return env.RESIDENT_PERMIT
  }
};

module.exports = async (on, config) => {
  const environment = config.env.configFile || "local";
  const configForEnv = await fetchConfigurationByFile(environment) || config;
  
  let currentTestName
  on('before:spec', (spec) => {
    console.log('before:spec ', spec.name)
    currentTestName = spec.name
  })

  on('before:browser:launch', (browser = {}, launchOptions) => {
    console.log('before:browser:launch')
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      launchOptions.args.push("--disable-gpu")
      launchOptions.args.push("--use-fake-ui-for-media-stream")
      launchOptions.args.push("--use-fake-device-for-media-stream")
      launchOptions.args.push(`--use-file-for-fake-video-capture=` + mapTestNameToVideoFilePath(configForEnv.env, currentTestName))
    }
    return launchOptions;
  })

  return configForEnv;
};

Keep in mind i put the index.js with environments configuration and fake video cam parametrized.

Thank you in advance for the help.
Nice day!!

**Comment by mjhenkes** [comment]
@LucyQA94, I did want to bring up one more thing. This workaround will not work in the next version of cypress. This currently works because between each spec we close and re-launch the browser instance. In 10.0 we won't close the browser instance between specs so you won't have the opportunity to set different files between specs. I'm not very familiar with 10.0 yet so I don't have further suggestions for you at this time, but I did want to warn you.

**Comment by LucyQA94** [comment]
Hello @mjhenkes thank u so much for the warn.
Well, this problem is important to my company and me.
We need insert differents videos with cypress.
Please, could you implement a solution for the next cypress releases?
Thank u again and nice day.
Regards.
