### ISSUE TITLE
Remove obsolete comment about cookie secure context

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21492]
See https://github.com/cypress-io/cypress/blob/885541ea5e736dfd4dac1d3254025b55b367fa3e/packages/server/lib/browsers/cdp_automation.ts#L266-L273

Is this a breaking change?

**Comment by AtofStryker** [comment]
we might also need to add this in the simulated cookie handling in the server side jar [here](https://github.com/cypress-io/cypress/pull/23872/files#diff-8bcc53731d8dc8219a282445e0ae5ae47e2884d0fb28ead3eef2b488819d1bf0R215) to be consistent

**Comment by mjhenkes** [comment]
We don't think this is breaking so remove the condition and the comment.

**Comment by chrisbreiding** [comment]
This was completed in https://github.com/cypress-io/cypress/pull/24340
