### ISSUE TITLE
cy.pause in cy.origin

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21495]
Add support for `cy.pause` within `cy.origin`.

**Comment by nedredmond** [comment]
Using `cy.pause` within `cy.origin`, no pause UI to step through commands. Is that what this bug is about?
![image](https://user-images.githubusercontent.com/23404711/180798188-86a10e07-3800-4592-a1d0-67527fd0e1d1.png)

**Comment by mschile** [comment]
@nedredmond, yes, this bug is in regards to `cy.pause` not working within `cy.origin` (looks like the issue description never got filled out). No need to report a new bug. Thanks!

**Comment by SivAlka** [comment]
Just checking to see if this is fixed anyhow. Still seeing the issue with cypress 10.8.0
