### ISSUE TITLE
Update all tests outside of the driver to support session

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21491]
When we enable test isolation by default, we need to verify that our tests pass with testIsolation on by default.  This ticket is to FIX all broken things.

**Comment by AtofStryker** [comment]
I set the default testIsolation to `strict` in https://github.com/cypress-io/cypress/compare/spike/test-isolation-strict?expand=1 and we have a [green build](https://app.circleci.com/pipelines/github/cypress-io/cypress?branch=spike%2Ftest-isolation-strict). Doesn't look like cutting over will be entirely difficult. @emilyrohrbough did I miss anything or is it really just this straight forward?

**Comment by nagash77** [comment]
Spike completed.  Now we need to do the work to fix what tests are still broken.

**Comment by nagash77** [comment]
work needs to go into the 11.0 branch

**Comment by nagash77** [comment]
marking as done and moving on to #21471 to complete the work.  Needs to go into the v11 branch

**Comment by emilyrohrbough** [comment]
this has been done.
