### ISSUE TITLE
cy visit fails to load

### ISSUE THREAD

**Issue by ccinfotech** [cypress-io/cypress#21504]
### Current behavior

cy visit fails to load . the same is working some times without changing anything.

```
We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: socket hang up

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `General Insurance Flow`
    at http://localhost:4000/__cypress/runner/cypress_runner.js:163598:82
    at visitFailedByErr (http://localhost:4000/__cypress/runner/cypress_runner.js:162902:12)
    at http://localhost:4000/__cypress/runner/cypress_runner.js:163597:11
From previous event:
    at go (http://localhost:4000/__cypress/runner/cypress_runner.js:163559:17)
    at http://localhost:4000/__cypress/runner/cypress_runner.js:163629:20
From previous event:
    at visit (http://localhost:4000/__cypress/runner/cypress_runner.js:163627:38)
    at Context.visit (http://localhost:4000/__cypress/runner/cypress_runner.js:163636:14)
From Your Spec Code:
    at Context.eval (http://localhost:4000/__cypress/tests?p=cypress\support\index.js:171:6)

From Node.js Internals:
  Error: socket hang up
      at connResetException (node:internal/errors:690:14)
      at TLSSocket.socketOnEnd (node:_http_client:471:23)
      at TLSSocket.emit (node:events:406:35)
      at endReadableNT (node:internal/streams/readable:1331:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
**the url is loading in normal browser with out any issues. with in cypress only the error comes.**

**There is no proxy configured . its direct network.**

### Test code to reproduce

cy.visit()

### Cypress Version

9.6.1

**Comment by mjhenkes** [comment]
@ccinfotech, I'm sorry that you're seeing this issue. Unfortunately there isn't enough information on this issue for us to be able to reproduce it. Could you provide us a minimally reproduce able example? Generally i find it nice to start from this [template](https://github.com/cypress-io/cypress-test-tiny), but I'll take what i can get :).

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
