### ISSUE TITLE
cy.url() and/or cy.location('href') does not return a string as documentation claims

### ISSUE THREAD

**Issue by TheRobBrennan** [cypress-io/cypress#2150]
### Current behavior:
According to the documentation, Cy.url() should produce a string. I wanted to capture the current URL into a variable and then reference it after I run a custom Cypress command.

My question is, if cy.url() and cy.location('href') no longer return strings in `3.0.1` - how do we get that value?

### Desired behavior:
Expecting a string of the current URL; instead an object is received that looks like:
```
// JSON.stringify(cy.url())
{ "chainerId": "chainer2504", "firstCall": false }

// JSON.stringify(cy.location('href'))
{ "chainerId": "chainer2558", "firstCall": false }

```

### Steps to reproduce:
Attempting to log either `cy.url()` or `cy.location('href')` does not result in a string as indicated by the documentation.

### Versions
Cypress 3.0.1

**Comment by brian-mann** [comment]
Cypress commands are async they do not produce a useful return value.

They've always been this way for all versions.

Read these docs and they will answer your exact question for working with them.

- https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#
- https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous

**Comment by dugajean** [comment]
@brian-mann  Then you should update your documentation and stop claiming that `url()` returns a string?

![image](https://user-images.githubusercontent.com/2448254/67635846-17089a00-f8cb-11e9-9dbf-9c3f5682fe35.png)

**Comment by RobDBob** [comment]
What's the correct approach to read current url?

**Comment by kristinamongo** [comment]
// if you need the current url in order to store it and use it later, you may do that:
```
let currentURL
  cy.url().then(url => {
    currentURL = url
  });
```

// and then use it later like that
` cy.then(() => cy.visit(currentURL))`

**Comment by jennifer-shehane** [comment]
@dugajean You can create a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document the cy.url() returns here: https://github.com/cypress-io/cypress-documentation/issues/new. Our documentation is open source and contributions are welcome.

**Comment by devonjs** [comment]
Just curious, under the recommendation of using `aliases`, what would be the proper way to chain `.as()` so that we could assign `cy.url()` to an alias?

**Comment by jennifer-shehane** [comment]
@devonjs You can alias a url. The below test passes:

```js
it('works', () => {
  cy.visit('https://example.cypress.io')
  cy.url().as('url')
  cy.get('@url').should('eq', 'https://example.cypress.io/')
})
```

**Comment by Vadorequest** [comment]
Using `async/await`:

```js
  it('should be running on the right domain', async () => {
    const url = await cy.url();
    cy.log(`Expected to be running on:`);
    cy.log(baseUrl);
    cy.log(`Actually running at:`);
    cy.log(url);
    cy.url().should('contains', baseUrl);
  });
```

![image](https://user-images.githubusercontent.com/3807458/84815085-c6d57800-b012-11ea-89c7-0ab66c1f9b0d.png)


Beware it doesn't work with `cypress run` though. See https://github.com/cypress-io/github-action/issues/160

**Comment by SimonasB88** [comment]
> // if you need the current url in order to store it and use it later, you may do that:
> 
> ```js
> let currentURL
>   cy.url().then(url => {
>     currentURL = url
>   });
> ```
> 
> // and then use it later like that
> 
> ```js
> cy.then(() => cy.visit(currentURL))
> ```

Nice thing, how could this look across different domains or tests?
