### ISSUE TITLE
Cypress component tests go into a hanging state in CI environment

### ISSUE THREAD

**Issue by tt5015** [cypress-io/cypress#21505]
### Current behavior

The component tests go into a hanging state in about half of the runs in CI environment whereas it always run perfectly locally each time. There is no test failure that causes this. The CPU and memory usage look ok to me from the logs. Sometimes the hanging happens at the time of running 2nd test spec file, sometimes at the time of running the 1st test spec file. I have only 3 component/unit spec files (written in typescript) and they are all extremely lightweight with no screenshots/video recording and bare minimum `it` blocks (1-8), so I don't believe this has anything to do with how tests are structured.

**Logs**
[test.txt](https://github.com/cypress-io/cypress/files/8693826/test.txt)

I have tried the following things which have not worked out:-
1. Downgrading to Cypress `8.7.0` and `7.6.0`
2. Removing `ForkTsCheckerWebpackPlugin` from webpack before instantiating `@cypress/webpack-dev-server` (https://github.com/cypress-io/cypress/issues/16169#issuecomment-837971016)
3. Setting `launchOptions.args['disable-dev-shm-usage'] = true;` in `on("before:browser:launch")` 
4. ` numTestsKeptInMemory` set to both 1 and 0 over multiple different runs.
5.  Forced garbage collection after each run (https://github.com/cypress-io/cypress/issues/8525#issue-696149834)

Here is my `cypress.json`

```
{
  "defaultCommandTimeout": 8000,
  "component": {
    "testFiles": "**/*.test.{js,ts,jsx,tsx}",
    "componentFolder": "src",
    "port": 8089
  },
  "blockHosts": [
    "redirector.gvt1.com"
  ],
  "numTestsKeptInMemory": 1,
  "screenshotOnRunFailure:": false,
  "chromeWebSecurity": false,
  "video": false,
  "supportFile": "cypress/support/index.ts",
}

```

**Versions**
Cypress - `9.3.1`
Electron - `94.0.4606.81`

Please let me know what could be tried to fix this? 

### Desired behavior

Component tests should not hang in CI.

### Test code to reproduce

No reproducer. The hanging behavior happens in about half the runs in CI; runs perfect each time locally.

### Cypress Version

9.3.1

**Comment by mjhenkes** [comment]
Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

**Comment by tt5015** [comment]
Thank you. Can you please share some timelines on when you expect the release to happen?

**Comment by galczo5** [comment]
We resolved this problem locally. From our investigation, it looks like GC is not working correctly when you stay in the same domain in every test. Our solutions is quite simple, between tests we call `cy.visit` with address of local html file when it's loaded we force the GC. 

It works for us, but It might be problematic when you have a lot of very small and fast tests.

**Comment by tclancy** [comment]
You may be able to achieve the same without touching the test code [via this suggestion](https://github.com/cypress-io/cypress/issues/8525#issuecomment-739731658).

**Comment by lmiller1990** [comment]
Can you update to the latest Cypress (v12). A lot of improvements were made to component testing. Also, some chrome specific GC related improvements landed in https://github.com/cypress-io/cypress/pull/25462.

Please let us know if you still have this issue.
