### ISSUE TITLE
Cypress.io dashboard constantly shows "oops. there was a problem talking to our servers"

### ISSUE THREAD

**Issue by paustint** [cypress-io/cypress#21512]
### Current behavior

For users with an adblocker - sentry, pendo, and trackcmp are blocked which results in a really annoying "oops. there was a problem talking to our servers" toast message constantly while using the application.

![image](https://user-images.githubusercontent.com/5461649/168626955-672704ec-eb3e-482a-b102-302151a7aecf.png)

### Desired behavior

don't show me a useless toast message when your tracking tools are unable to track a user.

### Test code to reproduce

Any project that is connected to cypress.io dashboard in a browser with adblock+ installed

### Cypress Version

NA

**Comment by mjhenkes** [comment]
@paustint We've opened a ticket with the dashboard team to look into this issue. Thanks!
