### ISSUE TITLE
client side generated CSV can't be downloaded and read

### ISSUE THREAD

**Issue by sanstream** [cypress-io/cypress#21510]
### Current behavior

We've implemented a test that verifies that a CSV file is generated for download in the front-end based on some tabular data. 

This works fine on a Ubuntu PC (21.04) and also works during CI/CD, but does not work on Windows in Edge and Chrome. We're also experiencing problems with Firefox, but those seem to the same as in https://github.com/cypress-io/cypress/issues/17896.

Here is a screenshot of the test output on Windows:
![1093989238-image](https://user-images.githubusercontent.com/4071142/167848561-e8ea0cdf-bd66-4e1d-b325-3430930a446e.png)

### Desired behavior

Cypress should be able read the file

### Test code to reproduce

```javascript
/// <reference types="cypress" />
import { join } from 'path'

// Added a \r to the end of the line, because it will be part of the final output too.
const csv = `distributor,sku,pkg,moq,stock,1,10,100,1000,10000\r
"Arrow Magnetics","29189501","","3000","0","","","","",""\r
"Bird America","ERFDKAS66,115","Tape & Reel","6000","0","","","","",""\r
"Digital Magic","1727-1240-2-ND","Tape & Reel","","3000","","","","",""\r
"Digital Magic","1727-1240-1-ND","Cut Tape","","3929","$0.542","$0.434","$0.296","$0.167",""\r
"Digital Magic","1727-1240-6-ND","Custom Reel","","3929","$0.542","$0.434","$0.296","$0.167",""\r
"Future Magnetics EMEA","ERFDKAS66,115","Reel","3000","0","","","","",""\r
"Mouser Magnetics UK","771-ERFDKAS66115","","1","4192","$0.538","$0.433","$0.295","$0.167",""\r
"Newark Magnetics","29AK3948","Tape & Reel","3000","0","","","","",""\r
"E3 Portugal","ERFDKAS66,115","Reel","","0","","","","",""`

describe('Stock levels tab', () => {
  const downloadsFolder = Cypress.config('downloadsFolder')
  it('the export function works as expected', () => {
    cy.intercept('/api/products', {
      fixture: 'products.json',
    }).as('productApi')
    cy.intercept('/api/stock?searchTerm=ERFDKAS66,22', {
      fixture: 'tabs/stock-levels-ERFDKAS66.json',
    }).as('stockLevelsApi')
    cy.visit('/search/nexperia/part*=ERFDKAS66/details/934066872115/stock-levels')

    cy.wait([ '@productApi', '@stockLevelsApi' ])
    cy.get('[data-e2e-test="stock-levels-table"] [data-test="ExportData"]').should('exist')
    cy.get('[data-e2e-test="stock-levels-table"] [data-test="ExportData"]').click()

    cy.log('**read downloaded file**')
    // file path is relative to the working folder
    const filename = join(downloadsFolder, 'download.csv')

    // browser might take a while to download the file,
    // so use "cy.readFile" to retry until the file exists
    // and has length - and we assume that it has finished downloading then
    cy.readFile(filename, { timeout: 15000 }) // < -- seems to fail here!
      .should('have.length.gt', 50)
      .and('equal', csv)
  })
})
```

### Cypress Version

8.1.0

**Comment by mjhenkes** [comment]
@sanstream, it looks like the test is failing to read the .csv file because the download failed. Do you have any more information why the download is failing on windows?

Could you create a minimally reproducible test case to show this issue? I find that https://github.com/cypress-io/cypress-test-tiny is a good template to start from.

**Comment by mjhenkes** [comment]
Hey @sanstream, Just a heads up We are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
