### ISSUE TITLE
[ component testing ] flakey tests in `CI` mode

### ISSUE THREAD

**Issue by DlgSHi** [cypress-io/cypress#21511]
### Current behavior

We have an issue with few flakey tests failing only in `CI` mode.

Steps to reproduce:
1. clone the [repo](git@github.com:Sage/carbon.git) 
2. run `npm install`
3. replace `.skip` in `mutli-action-button.test.js` and `split-button.test.js` with `.only`

Description:
- When trying to run `npx cypress run-ct --browser chrome` or `npx cypress run-ct` and **NOT** specify any spec few tests will fail from `mutli-action-button.test.js` and `split-button.test.js`. Tried to add `.wait's` - doesn't help. BUT when running the same command but with `--headed` and trying to debug spec - all tests are passing - MAGIC :)

- When running `npx cypress open-ct` and select those files the tests will pass.

results from [dashboard](https://dashboard.cypress.io/projects/8458bb/runs/11770/overview)
[spec1](https://github.com/Sage/carbon/blob/master/src/components/multi-action-button/multi-action-button.test.js)
[spec2](https://github.com/Sage/carbon/blob/master/src/components/split-button/split-button.test.js)

`describe` - `should check colors for MultiActionButton component`
`describe` - `should check colors for Split Button component` 

### Desired behavior

tests should pass using either `open-ct` and `run-ct`

### Test code to reproduce

`mutli-action-button.test.js` and `split-button.test.js` in repo from above

### Cypress Version

9.6.0

**Comment by mjhenkes** [comment]
Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

**Comment by DlgSHi** [comment]
Hi @mjhenkes, thank you for your update :)

**Comment by lugosium** [comment]
Hi,

We have the same issue i think.
We have flaky tests with `run`, but these tests are always working with `open`.
I worked this evening on this, and discover that if i remove the `--browser chrome` from the `run` command, it's always passing.

Not sure if it's help you!

**Comment by lugosium** [comment]
> Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

It's fixed for me with the v10 as my flaky tests now also fail with open like run ✅ 
I was able to fix them, thank you.

**Comment by DlgSHi** [comment]
same here :) closing issue
