### ISSUE TITLE
[spike] Define strategy for testing authentication providers in CI

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21525]
### What would you like?

Set up cypress tests in CI to use `cy.origin` to test the authentication providers specified in #21342. Likely we will need to update the RWA to allow logging in with the specified auth providers.

Part of this spike will be determining, how often we run theses tests, where and If they should break the build.

### Why is this needed? 

Auth providers are outside of our control so we should build a set of canary tests (within reason) to alert us if changes in an auth provider will break our users.

**Comment by mschile** [comment]
## Proposals:

### Create new RWA:
Pros:
* Separates concerns from existing repos that have other purposes
* Can create CI that won't impact Cypress's build/release
* Can be maintained by engineering (E2E-Auth)

Cons:
* New repository to maintain

### Use existing RWA:
Pros:
* Repository already exists
* Already connected to Auth providers through API calls (not all providers are supported)
* Can create CI that won't impact Cypress's build/release

Cons:
* Not owned by the engineering team
* Testing other scenarios not relevant to 3rd party providers

### Cypress System Tests:
Pros:
* Tests are located within existing repository
* CI already setup

Cons:
* System tests are more meant for testing Cypress functionality not verifying 3rd party providers
* These tests are tied into existing CI which would cause builds to fail if the provider changed

**Comment by mschile** [comment]
After discussion, we've decided to proceed with the first proposal (Create new project).

Plan:
* Create a new project (cypress-origin-providers???)
* Incorporate Auth0???
* Create a new test for each provider that verifies the user can perform the desired task (e.g. login for auth providers)
  * Create testing user for the provider
    * Does this need to be maintained by Cypress somehow?
  * If provided by the 3rd party provider, use a sandbox environment for testing
* Setup the project to run in CircleCI
  * Setup the project to run daily

**Comment by mschile** [comment]
Logged: https://cypress-io.atlassian.net/browse/ENTENG-140
