### ISSUE TITLE
cy.task does not wait for finish async functions to return

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#2152]
### Current behavior:
Return command don't wait async function finish
### Desired behavior:
All task modules force to use a return value but do not wait finish of function
what is the best way to keep waiting a "task" to return until a function inside in it?

```js

on('task', {
'somethingWithAsyncFunction': (response) => {
var value;
function doAsyncSomething()
{
//do something
}
return value;
}
});
```

### Versions
mac, electron 57

**Comment by brian-mann** [comment]
You return a promise and it will be awaited.
