### ISSUE TITLE
The Cypress App could not be unzipped.

### ISSUE THREAD

**Issue by zaunaro** [cypress-io/cypress#21531]
### Current behavior

Hi, 

i try to install cypress on my bitbucket ci/cd pipeline and i have an issue at unzipping the cypress app, ecause he can not find the file **/root/.cache/Cypress/9.6.0/Cypress/locales/am.pak**.

Can anyone help me ?

Thanks, 

Daniel

### Debug logs

> cypress@9.6.0 postinstall /opt/atlassian/pipelines/agent/build/apps/myapp/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 9.6.0)
[STARTED] Task without title.
[SUCCESS] Task without title.
[STARTED] Task without title.
The Cypress App could not be unzipped.
Search for an existing issue or open a GitHub issue at
https://github.com/cypress-io/cypress/issues
----------
Error: ENOENT: no such file or directory, open '/root/.cache/Cypress/9.6.0/Cypress/locales/am.pak'
----------
Platform: linux-x64 (Debian - 9.13)
Cypress Version: 9.6.0
lerna ERR! npm ci stderr:
npm WARN prepare removing existing node_modules/ before installation
[FAILED] The Cypress App could not be unzipped.
[FAILED] 
[FAILED] Search for an existing issue or open a GitHub issue at
[FAILED] 
[FAILED] https://github.com/cypress-io/cypress/issues
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Error: ENOENT: no such file or directory, open '/root/.cache/Cypress/9.6.0/Cypress/locales/am.pak'
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Debian - 9.13)
[FAILED] Cypress Version: 9.6.0

### Cypress Version

8.6.0 - 9.6.0 

### Package Manager

npm

### Operating system

Linux

**Comment by benbabaev** [comment]
Why the issue was closed? What was the solution?
