### ISSUE TITLE
Component testing / vue / app.config.globalProperties is undefined

### ISSUE THREAD

**Issue by marcodu** [cypress-io/cypress#21534]
### Current behavior

this.$bus is considered undefined in component testing, I get the following error :
  > Cannot read properties of undefined (reading '$emit')

### Desired behavior

app.config declarations should be accessible from component tests

### Test code to reproduce

main.js
```
import { createApp } from 'vue'
import bus from './services/event-bus'

const app = createApp(App).use(store).use(router)

app.config.globalProperties.$bus = bus
```

BaseSidebar.vue
```
<script>
export default {
  methods: {
    closeAllSidebars: function () {
      this.$bus.$emit('closeAllSidebars')
    }
  }
}
</script>
<template>
         <button @click.once="closeAllSidebars" [data-cy=BaseSidebarClose]>Close</button>
</template>

```

BaseSidebar.test.js

```
import { mount } from '@cypress/vue'
import BaseSidebar from './BaseSidebar'

describe('BaseSidebar', () => {
  it('test', () => {
    mount(BaseSidebar)

 
    cy.get('[data-cy=BaseSidebarClose]').click()
  })
})
```

### Cypress Version

8.3.0

**Comment by mjhenkes** [comment]
Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

**Comment by lmiller1990** [comment]
I think you need to pass this in on a test-by-test basis, we do not read `main.js` - just your component. Eg:


```js
mount(Comp, {
  global: {
    config: {
      $bus: /* thing here */
    }
  }
})
```

[Docs](https://test-utils.vuejs.org/api/#config-global).

You could customize your mount function in `cypress/support/component.ts`.

Some tips here on a custom mount function: https://cypress-testing-handbook.netlify.app/vuetify.html#custom-mount-function

Let me know if you still cannot get it working, I'll try and make a minimal example.
