### ISSUE TITLE
Mounting vue component causing ant components not wok properly.

### ISSUE THREAD

**Issue by alien1976** [cypress-io/cypress#21546]
### Current behavior

When you try to mount Vue component with the `mount` method from `@cypress/vue` and that component has antdv components inside then they are not working properly. This is produced by the [ant date range picker](https://www.antdv.com/components/date-picker/) and [ant select components](https://www.antdv.com/components/select/#Select).

The problem is that when they are mounted they could receive a click event but their popovers are not opening or not interactable.

* Ant select - The popover and select options are not visible when the select is clicked.
![image](https://user-images.githubusercontent.com/29014573/169034656-d3dca70e-1509-4a7f-9db9-81e9a595f1a1.png)
* Ant range picker - The range picker is not interactable and the dates are not clickable.
![image](https://user-images.githubusercontent.com/29014573/169035002-d53ee168-60b2-45f2-a894-a266440b69f0.png)

### Desired behavior

* Ant select - To display the dropdown with all the available options when it is clicked.
![image](https://user-images.githubusercontent.com/29014573/169034226-075aea39-fffc-4285-a5ee-8dfa3652890c.png)
* Ant range picker - To be able to select any date from the picker when it is opened.
![image](https://user-images.githubusercontent.com/29014573/169034494-807ad473-b2fb-4664-857e-1f89f75ee74a.png)

### Test code to reproduce

You can produce the issue by the following code and interact with the ant components after the test finish to check the problems. Make sure that the cypress, vue and ant versions are the same as described in the **Other** section. Also make sure to add
```js
resolve: {
    alias: {
        vue: 'vue/dist/vue.esm-bundler.js',
    },
},
```
to your webpack configuration in order the `mount({ template:...` works.

```js
import { mount } from '@cypress/vue';
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';

describe('Test', () => {
    it('test', () => {
        mount({
            template: `
                <div>
                    <a-range-picker/>
                    <a-select 
                        show-search
                        placeholder="Select an item"
                        :options="[
                            { value: '1', label: 'A' },
                            { value: '2', label: 'B' }
                        ]"
                    />
                </div>`,
        }, {
            global: {
                plugins: [Antd],
            },
        });
    });
});
```

### Cypress Version

9.5.4

### Other

The `@cypress/vue` has version `^3.1.2`
The `and-design-vue` has version `^3.1.1`

Maybe the problem is coming from the `@vue/test-utils` module that you are using in `@cypress/vue` because when I mount the component with `"vue": "^3.2.31"` like this
```js
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';
import * as Vue from 'vue';

describe('Test', () => {
    it('test', () => {
        const app = Vue.createApp({
            template: `
                <div>
                    <a-range-picker/>
                    <a-select 
                        show-search
                        placeholder="Select an item"
                        :options="[
                            { value: '1', label: 'A' },
                            { value: '2', label: 'B' }
                        ]"
                    />
                </div>`,
        });
        app.use(Antd);
        app.mount('#__cy_root');
    });
});
```
there are no problems. However, mounting component like this is very inconvenient because additional logic should be added to cypress that is related to unmounting components and other operations that are implemented inside the `mount` method.

Thanks!

**Comment by mjhenkes** [comment]
Thanks for logging this. We are tantalizingly close to releasing the new component testing workflow with Cypress 10.0. After the 10.0 has been released we will revisit your issue and determine if it is still relevant post release.

**Comment by alien1976** [comment]
Hello there! I figured out what was the problem. It seems that the vue ant components are using `transition` and `transition-group` for displaying popovers such as the dropdown or date picker. By default `mount` method stubs both of them so that is why the ant components are not working.

To fix the problem I tried to remove the stub from `transition` and `transition-group` and everything works like a charm.

```js
import { mount } from '@cypress/vue';
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';

describe('Test', () => {
    it('test', () => {
        mount({
            template: `
                <div>
                    <a-range-picker/>
                    <a-select 
                        show-search
                        placeholder="Select an item"
                        :options="[
                            { value: '1', label: 'A' },
                            { value: '2', label: 'B' }
                        ]"
                    />
                </div>`,
        }, {
            global: {
                plugins: [Antd],
                stubs: { transition: false, 'transition-group': false },
            },
        });
    });
});
```

**Comment by lmiller1990** [comment]
Seems OP found a fix, nice!
