### ISSUE TITLE
TypeScript: make use of source maps when displaying failure stack traces in reports

### ISSUE THREAD

**Issue by csabakoncz** [cypress-io/cypress#21562]
### Current behavior

When using TypeScript with Webpack the UI nicely shows the original test code and navigates to the failure location in the TypeScript source.

However, the reports still indicate the failure location in the transpiled code. E.g. for my test file that has 67 lines I get the following report:
```
     AssertionError: Timed out retrying after 4000ms: expected '<button#query-btn.query-btn.btn.btn-primary>' to contain 'ButtonAAAA'
      at Context.eval (https://example.cypress.io/__cypress/tests?p=cypress/integration/spec.ts:87:30)
```
This holds for spec, junit and mochawesome reports.

### Desired behavior

Cypress reports should indicate the failure locations in the original sources, not the transpiled code used during execution.

### Test code to reproduce

Here is the tiny test repo fork with spec reporter alone: 
https://github.com/csabakoncz/cypress-test-tiny-typescript

Test: `NO_COLOR=1 npm run cypress:run`
Output:
```
$ NO_COLOR=1 npm run cypress:run

> cypress-test-tiny@1.0.0 cypress:run
> cypress run


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.6.1                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v16.13.2 (/Users/ckoncz/work/apps/node-v16.13.2-darwin-x64/bin/node)           │
  │ Specs:          1 found (spec.ts)                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  spec.ts                                                                         (1 of 1)


  TypeScript
    ✓ works (44ms)
    ✓ checks shape of an object (29ms)
    ✓ uses cy commands (37ms)
    1) tests our example site
    ✓ has Cypress object type definition (45ms)
    2) can visit website
    3) adds numbers
    4) uses custom command cy.foo()
    ✓ yields the subject to .then callback (28ms)


  5 passing (11s)
  4 failing

  1) TypeScript
       tests our example site:
     AssertionError: Timed out retrying after 4000ms: expected '<button#query-btn.query-btn.btn.btn-primary>' to contain 'ButtonAAAA'
      at Context.eval (https://example.cypress.io/__cypress/tests?p=cypress/integration/spec.ts:87:30)
      ...
```

Repo with extra reporters (junit, mochawesome):
https://github.com/csabakoncz/cypress-typescript-sample

### Cypress Version

9.6.1

**Comment by BlueWinds** [comment]
Yeah, it's an unfortunate that we don't generate the correct source maps. Thank you for the reproducible example - I've closed another similar ticket as duplicate (https://github.com/cypress-io/cypress/issues/9332), since you have something that shows the issue in the most recent version.

**Comment by ckoncz-hwx** [comment]
Would like to stress that #9332 is about displaying the test source in the test runner and that feature is working for me, too.
(in the screenshot above both the action log and the stack trace printed to the browser console display the correct source location which is spec.ts:35 in that case).

The problem I am reporting is with the reporters. When running tests in the CI I do not have access to the Cypress test runner UI. What I tried to show is that the failure location as displayed by the "spec" reporter is wrong.

In this respect there is no difference between the reporters, the junit and mochawesome reporters also display wrong line numbers.

**Comment by ckoncz-hwx** [comment]
Is it possible to have the failure rendered in the command log when running tests with `cypress run` similarly to the case when the test is launched from the runner?

Then at least the screenshots would contain the correct line numbers.

**Comment by csabakoncz** [comment]
Managed to upgrade to Cypress 10.11 a few months ago. Typescript sources + stack traces work perfectly now.
Updated the tiny test repo: https://github.com/csabakoncz/cypress-test-tiny-typescript/tree/cypress-10.11
