### ISSUE TITLE
Wrong HTTPS request on cy.visit()

### ISSUE THREAD

**Issue by mespeche** [cypress-io/cypress#2157]
Hello,

I have a web application to test. 

When I do tests in local environment, it's work. But when I start the tests in remote environment, Cypress App or command crash.

It crash when I call a remote url after displaying the page.

I call a remote url like this : `cy.visit('http://my-webapp-url.test.fr')`

I do not know if it comes from there, but when i see the logs, an HTTPS request is visible : 

```
cypress:server:server Got CONNECT request from my-webapp-url.test.fr:80 +401ms
cypress:https-proxy Writing socket connection headers for URL: my-webapp-url.test.fr:80 +2s
cypress:server:cors Parsed URL { port: '80', tld: 'pro', domain: 'test' } +0ms
cypress:server:server HTTPS request does match URL: https://my-webapp-url.test.fr:80 with props: { port: '80', tld: 'pro', domain: 'test' } +0ms
```

I don't understand why HTTPS is called while I call an HTTP url...

_Note that this does not happen when I call an other url like http://www.google.fr_

Thanks for help 😉 

### Versions

Version 3.0.2
Browser Electron or Chrome

**Comment by jennifer-shehane** [comment]
- When you visit `http://my-webapp-url.test.fr` normally in your browser, does it redirect to the `https` url?
- Are you using WebSockets?

**Comment by mespeche** [comment]
Hi,

No HTTPS redirection and no websocket usage.

Thanks

**Comment by burgalon** [comment]
also having this issue specifically with a site certificate that doesn't match, althought i'm using `chromeWebSecurity: false`

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
