### ISSUE TITLE
the experimentalSessionAndOrigin feature should not be available in component testing

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21573]
### What would you like?

`experimentalSessionAndOrigin` should be an e2e-only configuration option. Later we must evaluate if using session in CT would be valuable as well was what test isolation in CT looks like, if it is available at all.

There also needs to be an update to the migration algorithm to prevent adding this config to CT?

The change may be similar to this:
https://github.com/cypress-io/cypress/blob/10.0-release/packages/data-context/src/sources/migration/codegen.ts#L436-L440

### Why is this needed? 

`cy.session` and `cy.origin` are both experimental and need further evaluation on their relevance to Component testing.

### Other

* Only allow `experimentalSessionAndOrigin` within the E2E object of the configuration file.
* Migrate anyone using `experimentalSessionAndOrigin` at the global config to move it into the E2E object during 10.0 migration.
* Throw error if `experimentalSessionAndOrigin` exists within the global config object for the CT config object.
* Document `experimentalSessionAndOrigin` as an E2E config only property in the unification docs.
* Add this change to the 10.0 Release changelog.

**Comment by AtofStryker** [comment]
> ### Other
> * Only allow `experimentalSessionAndOrigin` within the E2E object of the configuration file.
> * Migrate anyone using `experimentalSessionAndOrigin` at the global config to move it into the E2E object during 10.0 migration.
> * Throw error if `experimentalSessionAndOrigin` exists within the global config object for the CT config object..

These bulletpoints should be addressed in #21588
