### ISSUE TITLE
Chrome v67 : web SecurityError: Blocked a frame with origin from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by lesabag** [cypress-io/cypress#2158]
BUG

Current behavior:
I Updated **chrome** to LTS  version @2018-07-11 from V64... to V**67**.0.3396.99
Update caused to:
```json
{
  "chromeWebSecurity": false
}
```
NOT TO WORK AS EXPECTED!

### Desired behavior:
Be able to run Cypress tests like before 'chrome upgraded'.

### Steps to reproduce:
Upgrade chrome to the LTS version.
Launch Cypress runner and run tests.
Actual result: 
-> Test failed at `cy.visit(url)` step due to cross origin issue (see issue title)
Expected result:
-> Tests are running

Versions:
Cypress: ^3.2.0
-------
OS: Ubuntu 16.04
Browser: Chrome V67

Workaround:
I downgraded chrome back to version 'chrome64_**64**.0.3282.140'

**Comment by brian-mann** [comment]
This has been fixed already per and will be in the next release. https://github.com/cypress-io/cypress/issues/1951#issuecomment-401579981

**Comment by lesabag** [comment]
Great news, thanks :+1:
