### ISSUE TITLE
Not able to open corporate site via cypress in Windows 11

### ISSUE THREAD

**Issue by Astha626** [cypress-io/cypress#21595]
### Current behavior

Not able to open corporate site via cypress in Windows 11. Tried all the proxy settings available on Google and even configured all the proxy settings given on cypress official site but no luck. With same setup I'm able to access localhost url as well as other sites which are in public domain. But there is some issue in accessing intranet or private sites.

**Cypress could not verify that this server is running:

https://corportesite/

This server has been configured as your baseUrl, and tests will likely fail if it is not running.**

This warning appears as soon as I run cypress runner like below. And if I still try to run the script then it says:
cy.visit() failed trying to load:
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:

Error: A connection to the upstream proxy could not be established: connect ETIMEDOUT 145.7.175.233:80
Common situations why this would fail:

you don't have internet access
you forgot to run / boot your web server
your web server isn't accessible
you have weird network configuration settings on your computer

![image](https://user-images.githubusercontent.com/105936573/169697630-a3c4ef75-a16f-4ea6-ae9a-07c5c5ad9ecf.png)

![image](https://user-images.githubusercontent.com/105936573/169697640-a921e395-e049-476e-85f5-e8f72ff8520c.png)

### Desired behavior

Sites running on Intranet should also be accessible in Cypress

### Test code to reproduce

1. Provide the baseurl which runs only on Intranet
2. Launch the cypress runner
3. On Cypress runner, user can see a warning message (as shown in attached Screenshot)
4. Still try to run the test case
5. On cypress Browser, user can again see an error where cy.visit() unable to access given url. (as shown in attached Screenshot)

### Cypress Version

9.5.1

**Comment by mschile** [comment]
Can you access the domain normally, via curl within your environment? What is the result of running `curl yourdomain.com`? Can you access the domain via a normal [Node http.request](https://nodejs.dev/making-http-requests-with-nodejs) within the environment? Knowing the results of these will help narrow down if this is a network issue inside or outside of Cypress.

**Comment by Astha626** [comment]
@mschile I checked running curl command and got below response. What can be the next steps to resolve it? Pls guide here.

_curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above._

**Comment by mschile** [comment]
@Astha626, I probably should've included this in my first response, but when you ran the curl command, did you include the proxy environment variables as well?

`HTTP_PROXY=http://your-proxy.com/ HTTPS_PROXY=http://your-proxy.com/ curl https://your-website.net/`

It may also be helpful to see Cypress's debug logs, 
`DEBUG=cypress-verbose:proxy:http,cypress:* npx cypress open`

**Comment by Astha626** [comment]
@mschile I tried the above command and got below response:

curl: (28) Failed to connect to xxxxxxx (my proxy name) port 443 after 288666 ms: Timed out

**Comment by mjhenkes** [comment]
@Astha626, this appears to be an issue with your proxy connection since you are not able to curl outside of cypress. Try contacting your IT department and work on getting the curl command to work. Once you have the curl command working with a proxy, if cypress with a proxy is still experiencing errors, please open a new issue.

**Comment by navdeepdevrepublic** [comment]
> @Astha626, this appears to be an issue with your proxy connection since you are not able to curl outside of cypress. Try contacting your IT department and work on getting the curl command to work. Once you have the curl command working with a proxy, if cypress with a proxy is still experiencing errors, please open a new issue.

@mjhenkes I am also facing the same issue however I am able to get the response when I curl (mentioned in the last comment by you) but not able to access the same in cypress. Please help.
