### ISSUE TITLE
Write cy.origin integration tests for Paypal

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21602]

**Comment by AlexTheMagnus** [comment]
Hi @mjhenkes! I'm facing this right now, but I'm finding it hard. Is there any way to test PayPal integrations currently? Maybe any workaround? Thanks!

**Comment by freemaxt** [comment]
Hi! I need it as well and know one more person who also is trying to find workaround. It seems there is no way to use cypress for it.

**Comment by estefafdez** [comment]
Yes please, we will love to have a solution or at least a workaround with this one. Maybe a plugin? 

Thanks for your hard work on cypress and congrats on the new version!

**Comment by DavidFontalba** [comment]
Hi! We need to make tests for those cases and could be so nice to have them, I'd be so happy to know more about how this solution is going. Can you give some announcements about the developing please?

Thanks for your great work!

**Comment by mjhenkes** [comment]
Hi all, this is currently requires iframe support (#136). We're planning to start on iframe support after we bring `cy.origin` out of experimental.

**Comment by AtofStryker** [comment]
cy.origin tests are written for paypal for authentication, but NOT for payment field integration. This is just a small piece of this issue and as @mjhenkes pointed out that this requires iframe support to be complete
