### ISSUE TITLE
Write cy.origin integration tests for Stripe

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#21603]

**Comment by tlolkema** [comment]
I was keen to try out Cypress 10.4.0 with the `experimentalModifyObstructiveThirdPartyCode` in combination with `cy.origin` to check if Stripe integration works.

Our setup is the following:
- Checkout page in our application with Stripe input fields (those inputs are seperate iframes on stripe.com)
- Button to go to external Stripe page
- External stripe page with button to finish payment and redirect back to application

Without the `experimentalModifyObstructiveThirdPartyCode` > Stripe will frame bust when it goes to external Stripe page
With the `experimentalModifyObstructiveThirdPartyCode` > Test will fail at first step to interact with iframes, as Stripe will not render content succesfully:

<img width="687" alt="Screenshot 2022-08-04 at 13 05 36" src="https://user-images.githubusercontent.com/30321659/182834311-2d1bbec0-7d20-45ed-81cd-65a84545b9aa.png">

I tried if i could set the  `experimentalModifyObstructiveThirdPartyCode` within a test before clicking the button to go to Stripe but that didn't work.

**Comment by AtofStryker** [comment]
> 

@tlolkema this seems expected as we still need to implement cross-origin iframe support. 

`experimentalModifyObstructiveThirdPartyCode` cannot be set at runtime and should be set in the config.

I know we haven'y fully integrated with Stripe yet, but this seems like progress that you are able to get through the external page, at least solving that piece of the puzzle 😃 !

**Comment by mbbillz** [comment]
@tlolkema I'm having this same issue and it's preventing fully testing my whole checkout flow 🙈. Hoping for a fix soon! 🤞

**Comment by kishorequalitlabs** [comment]
We are also facing the same issue even with Cypres 12. x; Is it possible to fix the cypress issue, or should we live with it?

**Comment by AtofStryker** [comment]
@kishorequalitlabs it is possible to fix the issue but the timeline for Stripe checkout support isn't in the near future (next 4 weeks). What you could do is turn off [`chromeWebSecurity`](https://docs.cypress.io/guides/guides/web-security#Set-chromeWebSecurity-to-false) to interact with the iframe, similar to what this [medium article](https://medium.com/swinginc/testing-stripe-integration-with-cypress-3f0d665cfef7) is suggesting in the meantime.

**Comment by tlolkema** [comment]
> @kishorequalitlabs it is possible to fix the issue but the timeline for Stripe checkout support isn't in the near future (next 4 weeks). What you could do is turn off [`chromeWebSecurity`](https://docs.cypress.io/guides/guides/web-security#Set-chromeWebSecurity-to-false) to interact with the iframe, similar to what this [medium article](https://medium.com/swinginc/testing-stripe-integration-with-cypress-3f0d665cfef7) is suggesting in the meantime. 

This will not work since the navigation to stripe will frame bust.

**Comment by AtofStryker** [comment]
@tlolkema ah I see now. Since we are having the conversation on the issue that is for adding integration tests for Stripe, would you be able to possibly open a new issue that expresses your [comment](https://github.com/cypress-io/cypress/issues/21603#issuecomment-1205123127) that we can investigate for support with `experimentalModifyObstructiveThirdPartyCode`?

**Comment by tlolkema** [comment]
@AtofStryker 
https://github.com/cypress-io/cypress/issues/25934

Let me know if you need more info :)

**Comment by hyungjunk** [comment]
Any update on this issue? `experimentalModifyObstructiveThirdPartyCode` would be great to overridden.

**Comment by AtofStryker** [comment]
@hyungjunk no updates on writing the integration tests yet, but when this work item gets picked up we should update the issue!

**Comment by SahanRama** [comment]
im also facing the issue. with the "cypress": "^12.6.0"

in my cypress.config.js file im having the     `experimentalModifyObstructiveThirdPartyCode: true,`

you can easily reproduce this using the following steps
```javascript
describe("My First Test", function () {
  it("test", function () {
    cy.visit("https://stripe.dev/elements-examples/");
    cy.get(".__PrivateStripeElement > iframe")
      .eq(0)
      .then(($iframe) => {
        const body = $iframe.contents().find(".InputContainer");
        cy.wrap(body).find(`input[name="cardnumber"]`).type("4242424242424242");
        cy.wrap(body).find(`input[name="exp-date"]`).type("12/20");
        cy.wrap(body).find(`input[name="cvc"]`).type("424");
      });
  });
});
``` 

![image](https://github.com/cypress-io/cypress/assets/68191711/38e6cdc3-ef8b-4e05-aef4-c7e92bbf7958)

also this issue was happend before 
https://github.com/cypress-io/cypress/issues/8983


I would really love to getback on this issue. its blocking the test automation for me.

**Comment by JvazquezQAexoticca** [comment]
Yes, this is blocking me to enable experimentalModifyObstructiveThirdPartyCode and make test for Paypal, for instance. I have to choose

**Comment by hyungjunk** [comment]
As a workaround, I just had to separate test suite to run with different configs.

**Comment by BioCarmen** [comment]
Any updates on this. I can visit Stripe Checkout page with `experimentalModifyObstructiveThirdPartyCode` but I can't interact with the checkout page element without `chromeWebSecurity` set to true

**Comment by AtofStryker** [comment]
@BioCarmen sorry for the delay on a response here. Currently we don't have any updates on the issue.
