### ISSUE TITLE
cy.visit() fails for any page

### ISSUE THREAD

**Issue by the-einstein** [cypress-io/cypress#21641]
### Current behavior

I have an application on nuxt running in localhost and trying to write tests in cypress. But cy.visit() fails for all pages, I also tried for example.com, but it is not working. There is no problem with nuxt application. It is running and working well

### Test code to reproduce

here is my cypress.json

`{
    "baseUrl": "http://localhost:39775/",
    "testFiles": "**/*.spec.js",
    "componentFolder": "components",
    "retries": {
        "runMode": 2,
        "openMode": 0
      }
}`

here is a test I am running 

 `describe('The Home Page', () => {
    beforeEach( () => {
        cy.visit('/', { failOnStatusCode: false})
    })
    it('renders the correct markup', () => {
        cy.get('#__nuxt').should('be.visible')
    })
  })`

plugins.js file is the same as shown in cypress docs

 `import { startDevServer } from '@cypress/webpack-dev-server'
import { getWebpackConfig } from 'nuxt'

export default (on, config) => {
  on('dev-server:start', async (options) => {
    const webpackConfig = await getWebpackConfig()
    return startDevServer({
      options,
      webpackConfig,
    })
  })
}`

here is an error that I am having

 `cy.visit() failed trying to load:

undefined

The response we received from your web server was:

  > undefined: undefined

This was considered a failure because the status code was not 2xx.

If you do not want status codes to cause failures pass the option: failOnStatusCode: false

Because this error occurred during a before each hook we are skipping the remaining tests in the current suite: The Home Page`

this error shows even when url is https://example.com 

### Cypress Version

^9.7.0

**Comment by flotwig** [comment]
@the-einstein we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
