### ISSUE TITLE
Add the ability to ignore chosen assertion failures

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#21669]
### What would you like?

I would like the ability to ignore cypress assertion failures if I choose to. For example
```javascript
cy.get('.save-icon').click()
// Wait for the "waiting" icon to disappear.
cy.get('.wait-icon').should('be.visible',{continueOnFail:true})
cy.get('.wait-icon').should('not.be.visible',{continueOnFail:true})
cy.get("exit-icon").click()
cy.request("api/get/xxx").then((res)=>{expect(res.body).have.length(3)})
```

### Why is this needed?

Let's assume we are testing some kinda article writing site
Once a user finished writing, they click the "save" button to save their work and then exit the app.

To ensure the save action is succeeded, we want to query the API to see if the data is readable. 

This creates a racing condition that if the user exit the app too early before the "behind the scenes sync" is triggered, the request assertion gonna fail. That is why we want to wait for the "wait" icon to show and disappear so we know the "behind the scenes sync" is triggered. 

Well, this is still not perfect, sometimes, the "be.visible" check is triggered too late (after the icon showed up and disappeared) and the test fails on that assertion even tho this is a false negative. 

With selenium, I probably can write something like this 
```python
  wait_element = null
   while(timeout after 10 seconds):
       try:
          wait_element = driver.get('.wait-icon')
       catch(NoSuchElementException):
          pass
    if wait_element:
       wait_until_wait_element_disappear()
    else:
      // We probably missed it, but it is ok. we will let the API query to decide the fate of this test case
       pass
        
```

### Other

Of course, if we get creative, most of the time we can somehow hack the issue away. For example, in this case, we probably can monitor the "sync" request instead of the UI icon. 
 
That being said, a common/generic solution for this type of issue would be great due to the best practice of cypress includes:
1. no negative assertion
2. use assertion to wait for intermediate steps to complete

But we have to accept that sometimes, the UI state is not deterministic no matter how hard you pretend.

**Comment by mschile** [comment]
While this doesn't directly address your feature request, I would still encourage you to make your tests as deterministic as possible instead of relying on an assertion that may or may not pass. For this use-case, I would use `cy.intercept` to hold up the response from the sync request so you can verify the wait icon is displayed before proceeding. For example:

```
  it('works', () => {
    let continueResponse
    cy.intercept(/example.json/, (req) => {
      req.continue(() => {
        return new Promise((resolve) => {
          continueResponse = resolve
        })
      })
    })

    cy.visit('cypress/fixtures/index.html')
    cy.get('#button').click()
    cy.get('#loading').should('be.visible').then(() => {
      continueResponse()
    })
    cy.get('#loading').should('not.be.visible')
  })
```

You can see the complete example here: https://github.com/mschile/cypress-test-tiny-issue-21669

**Comment by Songyu-Wang** [comment]
@mschile yea, like I mentioned in the original post, this indeed can be solved with network request monitoring. That being said, comparing to the proposed code, which one do you think have better readability and maintainability?

**Comment by mschile** [comment]
@Songyu-Wang, I would always suggest using a 'signal' that is deterministic over one that is not. We do have a [Conditional Testing](https://docs.cypress.io/guides/core-concepts/conditional-testing#What-you-ll-learn) guide that touches on some of these topics.

After discussion with the team, adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. Thank you for taking the time to open the feature request.
