### ISSUE TITLE
Test Partytown in Cypress

### ISSUE THREAD

**Issue by tyhopp** [cypress-io/cypress#21671]
### Current behavior

We are unable to test [Partytown](https://github.com/BuilderIO/partytown), a library that loads scripts in a web worker, in Cypress. Scripts loaded with Partytown load fine outside of Cypress but do not load when Cypress runs.

We suspect this might be due to the fact that Cypress loads sites in an iframe, but Partytown is aware of the context it runs in and works as expected in a regular iframe. I've tried setting `modifyObstructiveCode` and `chromeWebSecurity` to `false` to see if that makes a difference but it doesn't seem to.

There's a [related issue in the Partytown repo](https://github.com/BuilderIO/partytown/issues/179).

### Desired behavior

As per [the minimal reproduction](https://github.com/tyhopp/partytown-cypress-reproduction), we expect that Partytown will load the script when running in Cypress.

### Test code to reproduce

Minimal reproduction - https://github.com/tyhopp/partytown-cypress-reproduction

### Cypress Version

9.6.1

**Comment by ZachJW34** [comment]
@tyhopp in the Partytown issue you mentioned you had a reproduction of Partytown working fine in an iframe. Could you provide that reproduction? Not too familiar with web-workers so I'd like to see how Partytown works in an iframe so I can see what the missing link is on our end.

**Comment by tyhopp** [comment]
Hi @ZachJW34, I looked into this again and I was wrong, Partytown does not work in a regular iframe.

Here's the repro for that: https://github.com/tyhopp/partytown-iframe-reproduction

I'll update the original issue in the Partytown repo.

**Comment by flotwig** [comment]
@tyhopp have you tried `experimentalSourceRewriting`?

**Comment by tyhopp** [comment]
Hi, I don't intend to spend more time on this so I will close it.

**Comment by yarniko** [comment]
Hi. Can you reopen this issue?
I'm facing a similar problem. In my project, we used Partytown and my tests failed.
