### ISSUE TITLE
cy.get(el).getBoundingClientRect() returns wrong coordinates

### ISSUE THREAD

**Issue by kyleoliveiro** [cypress-io/cypress#2170]
### Current behavior:

```js
cy.get($el).then($el => {
  $el[0].getBoundingClientRect();
});
```

The above will return `x` and `y` coordinates of the element relative to the outer viewport, instead of the page it is being tested on.

### Desired behavior:

Coordinates returned should be relative to the inner page that is being tested. (e.g. if `$el` is at the top of the page, then `getBoundingClientRect().y` should equal `0`.)

### Versions

Cypress 3.0.2

**Comment by devsh4** [comment]
Same thing happens for me. getBoundingClientRect.x and .y give coordinates specific to the viewport and not the page.

**Comment by jennifer-shehane** [comment]
Can anyone provide a way to reproduce this - html code + test code with failure?

**Comment by mohamedyoussefmaaref** [comment]
can anyone give us the code?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by canbax** [comment]
I see the same issue. It simply returns an empty object. Can we call all javascript functions with the above approach? Reproducing this issue is fairly simple. For any DOM Element just call this

```
cy.get("div").then($el => {
  $el[0].getBoundingClientRect();
});
```

Also @kyleoliveiro why do you use the same name `$el` for 2 different variables. This is confusing

**Comment by vimalsharma081990** [comment]
to get correct coordinates set ViewPort sizes to your Browser's viewPort sizes.

    cy.viewport(width, height), you can do the same in cypress config file
