### ISSUE TITLE
Publish GitHub release when building a release commit on CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2172]
related to #2006 

- every time we release a new version we push a commit like `release 3.0.2 ...` which changed `package.json` file in `master` branch
- it would be nice to create a new GitHub release note with the changelog (grabbed from cypress-documentation source) automatically, and not using a separate script
- this action could / should be done from CI

**Comment by bahmutov** [comment]
Currently using https://github.com/cypress-io/set-releases as a CLI tool to publish new GitHub release for a version

**Comment by jennifer-shehane** [comment]
Closing as resolved. Our GitHub release is published automatically now.
