### ISSUE TITLE
this.test.file is null when test is executing in UI Runner

### ISSUE THREAD

**Issue by scspieker** [cypress-io/cypress#2174]
While running Cypress SPEC files, I would like to perform some actions in order to help with custom reporting (like: Updating the mochaFile name based on the current test file being run) - the reference to the `this.test.file` is always `null` when the file is executing and inaccessible when running the `before/beforeEach` hooks.

The `before/beforeEach` hook would be the ideal location to access and set the behavior of the mochaFile configuration.

### Current behavior:
`console.log(this.test.file)` -> output is `null`.
`console.log(this.test)` -> `file: null`

### Desired behavior:
`console.log(this.test.file)` -> output something like: `Cypress.config('integrationsFolder') + "example_spec.js"` OR the fully qualified path of the test file being executed.  Ideally this value would be available when the centralized `before/beforeEach/after/afterEach` hooks are executed (i.e. these hooks are normally placed within `$CYPRESS_HOME/support/index.js`.

before hook desired implementation:
```js
var testFile = path.basename(this.test.file, '.js');
var reporterOpts = Cypress.config('reporterOptions');
var mochaFile = reporterOptions.mochaFile;
var resultsDir = path.dirname(mochaFile);
reporterOpts.mochaFile = resultsDir + '/' + testFile + '_test_results.xml';
```

### Steps to reproduce:

```js
describe('Get Test File name', function() {
    it('Display file name', function() {
        console.log('Test file name: ' + this.test.file);
        console.log('Test Object:')
        console.log(this.test)
    })
})
```

### Versions

Windows 10,
Chrome 67, 
Cypress 3.0.1
Node.js: 8.11.1
npm: 5.6.0

**Comment by bahmutov** [comment]
can you see if  `this.currentTest` is set correctly inside the test?

**Comment by scspieker** [comment]
Thank you for responding to this issue so quickly.

When attempting:
console.log(this.test.file) = null
console.log(this.currentTest) = undefined

**Comment by scspieker** [comment]
Are there any additional operations that could be attempted in order to ascertain the currently running test?  Perhaps injecting an operation into the runner or overriding the function that defines the suite definition?

**Comment by scspieker** [comment]
Is there possibly any other actions that I might try in order to assess the name of the currently running test?  Perhaps a hook or another location where the file, path or other appropriate value might be pulled from perhaps?

**Comment by scspieker** [comment]
There seems to be an element that would contain the value that I am looking for as outlined in:
https://github.com/cypress-io/cypress/issues/2141

The element that I am referring to is:
runs[].spec.name would be ideal.

Now the question becomes, how could I access this information within the Before hook?

**Comment by BalajiGiffGaff** [comment]
@scspieker I am also facing this issue right now... Did you got any work around ?

**Comment by jennifer-shehane** [comment]
Hey @scspieker, sorry for the delay in the response. You should be able to use [`Cypress.spec`](https://on.cypress.io/spec) to access the current spec, including its name.
