### ISSUE TITLE
Glob route doesn't seem to work, but passes the Globtester

### ISSUE THREAD

**Issue by sitefinitysteve** [cypress-io/cypress#2178]
Need to wait on a route, but I can't seem to get wait to detect it, with glob or regex (glob obviously easier).  However if I make the route less specific it works, problem is thats the ROOT route for the site, so I need to make sure the waits contain both that and the next segment (so /RestApi/layout, /RestApi/favorites, etc etc)

### Current behavior:

![image](https://user-images.githubusercontent.com/1542376/42959585-56b990f6-8b57-11e8-8388-674335723e81.png)

### Desired behavior:

Route to be hit with the second segment
![image](https://user-images.githubusercontent.com/1542376/42959641-876bab30-8b57-11e8-811a-e0e4cb328e46.png)

### Steps to reproduce:
Route in question:
```
/RestApi/favorites?PageName=Medical+Foundation+1&Url=%2Fug%2Fmf%2F1&_=1532020653920
```

#### fail
```js
        cy.server();
        cy.route("**/RestApi/favorites**").as("getFavs");
        cy.route("**/favorites**").as("getFavs");
```
#### works
```js
        cy.server();
        cy.route("**/RestApi/**").as("getFavs");
```

Both pass the globtester http://globtester.com, but cypress doesn't pick up on the complex one

### Versions

3.0.2, Windows 10

**Comment by brian-mann** [comment]
I believe its passing globtester because in what you pasted above, the forward slash is URL encoded, but in reality Cypress is seeing it as `/` when its comparing the globs. To grab all of the subpaths you need this...

```
**/RestApi/**/*
``

Also you likely don't need the `**/Rest...` in front, probably just `/Rest...`

So try...

```
**/RestApi/**/*
RestApi/**/*
``

One or both should work.

**Comment by sitefinitysteve** [comment]
Yeah I don't need that, sorry I'm just trying everything at this point.  Sorry if I didn't make it clear :/

It's not that I need subpathing I specifically need to watch for this route
/RestApi/favorites**

Any varient of RestApi works great\fine, but I can't get a single variant containing "favorites" to pass cypress.

Like lets say even just this
```

**Comment by brian-mann** [comment]
Did you try `**/*` ?

**Comment by sitefinitysteve** [comment]
Same deal with 
```
cy.route("**/favorites**/*").as("getFavs");
```
(If thats the syntax you meant)

**Comment by brian-mann** [comment]
The code responsible for matching the routes is this exact line... https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/server.coffee#L241

Open up devtools... goto Sources and do a search for that code and put a debugger there. You'll then see how Cypress compares the glob you passed and the URL.

**Comment by sitefinitysteve** [comment]
This is WAY more convenent to test with thx!  ...but I mean I can't get it to pass still, am I missing something obvious?

![image](https://user-images.githubusercontent.com/1542376/42961408-b25ee12c-8b5c-11e8-9583-8bad15b0999d.png)

**Comment by jennifer-shehane** [comment]
@sitefinitysteve There is a `?` directly after `favorites`, not a `/`

**Comment by sitefinitysteve** [comment]
Sorry yeah I forgot to remove there, I have tried many varients over the last couple days, slash or no slash, makes no diff

![image](https://user-images.githubusercontent.com/1542376/42963250-a9aeee0a-8b61-11e8-9f8a-6f773675ab2c.png)

**Comment by sitefinitysteve** [comment]
![image](https://user-images.githubusercontent.com/1542376/42963319-e88e7b4a-8b61-11e8-9eb9-9bb3a9c4bd1a.png)

**Comment by jennifer-shehane** [comment]
Since you have more `/` later in the url params, I believe this glob should work. `**/favorites?**/**`

The globtester on globtester.com is a bit buggy, so it's generally best to try matching using the minimatch util.

Has your issue been fully resolved?

**Comment by sitefinitysteve** [comment]
@jennifer-shehane That was exactly it, I'll use minimatch from now on!  I read the docs over and over, it wouldn't be a terrible idea to point people over to the minimatch page and explicitly say to not trust online glob generators. https://docs.cypress.io/api/utilities/minimatch.html#Examples

Thanks so much, keep up the great work!

**Comment by sitefinitysteve** [comment]
@jennifer-shehane I have a situation right now where the Cypress.minimatch returns true, but the Wait for the route never gets triggered.  I've burned like 4 hours trying various combinations.  Is it something with the querystring throwing it?

```
describe("Admin Capacity Planner Tests", function(){
    beforeEach(function(){
        
    }),

    it("Loads the properly", function(){ 
        cy.visit("/sso/cilogin?role=ugadmin&returnurl=/admin/cps/capacity-planner"); 
        cy.server();

        var route = "**/capacityplanner/blocks?**";
        ///RestApi/cps/ug/admin/capacityplanner/blocks?phase=all&skip=0&take=20&fromDate=Sep-19-18&filter=gt&format=json&testmode=false
        cy.route(route).as("getCpsBlocks");
        
        var isMatch = Cypress.minimatch("/RestApi/cps/ug/admin/capacityplanner/blocks?phase=all&skip=0&take=20&fromDate=Sep-19-18&filter=gt&format=json&testmode=false", route)
        console.log(isMatch);

        cy.wait("@getCpsBlocks", {timeout: 1000}).then((xhr) => {
            var response = xhr.response.body;
            console.log(response);
        });
    })
});
```
![image](https://user-images.githubusercontent.com/1542376/45823966-e49a6f80-bcbc-11e8-80c6-05878b20e7af.png)

**Comment by jennifer-shehane** [comment]
Closing as resolved.
