### ISSUE TITLE
LocalStorage clearing in between tests

### ISSUE THREAD

**Issue by jhuys** [cypress-io/cypress#2180]
We were setting up an end-to-end test for our website with the latest version of Cypress. It took us quite a while to figure out why it wasn't behaving exactly the same as if we would carry out the actions ourselves on the website. The following test shows the essence of what was going wrong in our end-to-end test:

``` javascript
describe('Academic pre-fill test', function() {

	before(function(){

		cy.visit('https://admissionchance.tst.prtl.co/');
	});

	context('Academic questionnaire', function(){

		it('should answer the first question', function(){

			cy.get(".js-radioButton[value='bachelor'] + .Button.Ghost.Blue").click();
		});

		it('should pre-fill the first question when going back', function(){

			cy.get('#BestFitAcademic .ButtonJump[title="Back"]').click();
			cy.get(".js-radioLabel.Active .js-radioButton[value='bachelor'] + .Button.Ghost.Blue").should('exist');
		});
	})
});
```

The first test (`should answer the first question`) sets a property in localStorage. The second test (`should pre-fill the first question when going back`) reads the data from localStorage as part of pre-filling the question answer. After a couple of days we found out that localStorage data is cleared between tests. At that point we also thought that clearing between tests meant between each end-to-end test, but it happens more often (between every `it`).

By adding the line `Cypress.LocalStorage.clear = function(keys, ls, rs){};` at the top of the test it's solved, since localStorage clearing doesn't happen anymore, but the default behaviour of clearing it between test cases caused quite some time and frustration for us in trying to figure out what was going wrong, and raises the question whether this should be the default behaviour.

**Comment by jennifer-shehane** [comment]
This is related to our proposal on implementing clearer "lifecycle" events outlined here: https://github.com/cypress-io/cypress/issues/686

Feel free to post any feedback there after reading some of our proposal.
