### ISSUE TITLE
--no-exit flag causes Cypress to hang after first file in multiple file run

### ISSUE THREAD

**Issue by cdanielsen** [cypress-io/cypress#2182]
### Current behavior:

If `cypress run` is invoked with the `--no-exit` flag and the pattern to find specs matches multiple files, cypress will only run the first file and then hang with the message
`not exiting due to options.exit being false`

### Desired behavior:

Cypress should run **all** the matched files before ending the run and not exiting

### Steps to reproduce:

Clone https://github.com/cdanielsen/cypress-test-tiny
git checkout bug/no-exit-flag-prevents-multiple-file-run
npm run test:noexit

### Versions
Cypress: 3.0.2
OS: Ubuntu 18
Browser: Chromium

**Comment by Bkucera** [comment]
@cdanielsen Hi,
Can you explain your use case for this? I'm just curious, because the `--no-exit` was added to allow users to debug a `--headed` run by allowing you to keep the browser open.

**Comment by cdanielsen** [comment]
Is the `--no-exit` flag only intended to be used for a headed run then? This still seems like it would be problematic in that it doesn't process all the files it matches from the `testFiles` config option pattern. (If you pass the --headed flag to the script in the test repo I provided, you see the same behavior).

My use case is a custom reporter that does async work (reporting results to Test Rail via http). Because mocha doesn't seem to support waiting for async calls on its `end` event, I want the cypress process to not exit and have my reporter exit the process when its done with its work.

**Comment by Bkucera** [comment]
@cdanielsen I think you should use the Module API. I'd create a script that `require`s Cypress and then you can do whatever you want after Cypress exits.

https://docs.cypress.io/guides/guides/command-line.html#Cypress-Module-API

**Comment by Bkucera** [comment]
@cdanielsen the `--no-exit` is for the browser exiting, not the Cypress node process

**Comment by cdanielsen** [comment]
> @cdanielsen the --no-exit is for the browser exiting, not the Cypress node process

That doesn't seem to be the case. If you run my original script (cypress run --no-exit), the node process spun up to run the tests headlessly will hang indefinitely without exiting.

> @cdanielsen I think you should use the Module API. I'd create a script that requires Cypress and then you can do whatever you want after Cypress exits.

I suppose that's a possibility, but seems a little heavy for my use case. Wondering if tapping into one of [these events](https://docs.cypress.io/api/events/catalog-of-events.html#Cypress-Events) might be a better route.

**Comment by brian-mann** [comment]
@cdanielsen you can use a custom reporter today and it will "just work". We explicitly supporting calling the `done()` function asynchronously in mocha reporters. Other reporters already do it and it works.

**Comment by brian-mann** [comment]
That's how you can tap into the underlying test results and perform work prior to Cypress quitting.

**Comment by cdanielsen** [comment]
@brian-mann I've been googling but haven't been able to find a mocha reporter that supports calling something async and waiting for it in response to the `end` event. [This issue](https://github.com/mochajs/mocha/issues/2541) seems to indicate that's the intended interface on mocha's part? Thanks for any clarification you can offer.

**Comment by cdanielsen** [comment]
@brian-mann Can you also clarify whether I should expect this behavior with the `--no-exit` flag?
> Cypress should run *all* the matched files before ending the run and not exiting

**Comment by Bkucera** [comment]
@cdanielsen `--no-exit` will prevent the browser from closing, that includes the first spec run

**Comment by cdanielsen** [comment]
Bump. @brian-mann any chance you can clarify https://github.com/cypress-io/cypress/issues/2182#issuecomment-406691742 or the questions above?

**Comment by brian-mann** [comment]
@cdanielsen 

> My use case is a custom reporter that does async work (reporting results to Test Rail via http). Because mocha doesn't seem to support waiting for async calls on its end event, I want the cypress process to not exit and have my reporter exit the process when it's done with its work.

Just use the module API of Cypress and we will yield you all of the results of all the tests. You can then do whatever it is you want to do because at that point Cypress is done and your own node script does whatever it does with the results. Also I believe someone already wrote a Test Rails cypress integration.

**Comment by cdanielsen** [comment]
@brian-mann Thanks for the response... there is a cypress-test-rails reporter, but it has the [same issue](https://github.com/awaragi/mocha-testrail-reporter/issues/2) because of the underlying `[mocha architecture](https://github.com/awaragi/mocha-testrail-reporter/issues/2#issuecomment-404639410)`  Was just curious based on your comment above if the wrapping you'd done on mocha would provide some way around this.

I'll look into using the module API; will go ahead and close this issue.

**Comment by vtertre** [comment]
@cdanielsen Hi,
This is a bit old but it appears the async work issue with custom reporters remains.
Did you find any workaround solution for your use case?

**Comment by cdanielsen** [comment]
Hello @vtertre,

I ended up using the module api, as suggested!

**Comment by DeveloperTheExplorer** [comment]
How can I continue to the next test file when using the `--no-exist` and `--headed` parameters?

I would like to debug multiple test files, and after each continue to the next.

**Comment by jennifer-shehane** [comment]
@DeveloperTheExplorer This functionality doesn't work with the experimental run all specs today. Can you log this as a separate issue with this request?
