### ISSUE TITLE
@faker-js/faker Webpack Compilation Error (in typescript environment) 

### ISSUE THREAD

**Issue by dante01yoon** [cypress-io/cypress#21874]
### Current behavior

Hi, I'm trying using @faker-js/faker in my cypress test.
During running test, Webpack Compilation Error occured where I try
`import { faker } from "@faker-js/faker"` 

error looks like below.
I tried create .babelrc  fiiled with `{}` below  `cypress/`, but didn't work.  
<img width="915" alt="스크린샷 2022-05-30 오후 6 58 56" src="https://user-images.githubusercontent.com/6510430/170968403-c3dbe3bd-2f3d-4e32-a2b9-d0f79d9caa32.png">

dependencies version:  
```
"@faker-js/faker": "^7.1.0",
 "typescript": "^4.7.2"
```

my tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2020",
    "lib": ["es2020", "dom"],
    "types": ["cypress"],
    "esModuleInterop": true,
    "moduleResolution": "Node"
  },
  "include": ["**/*.ts"]
}
```

### Desired behavior

test should work properly

### Test code to reproduce

-

### Cypress Version

9.5.0

**Comment by ZachJW34** [comment]
This is an issue with @faker-js/faker and [webpack@4 compatibility](https://github.com/webpack/webpack/issues/10227). This will work with webpack 5, but we won't be migrating to v5 just yet #8900. You can open an issue with [@faker-js/faker](https://github.com/faker-js/faker) if you want this to be officially fixed.

There are a few workarounds in the meantime, if you are using yarn you can use the `resolutions` to enable the newer ES features (see [webpack issue](https://github.com/webpack/webpack/issues/10227))

You can also modify the webpack options via the [Webpack Preprocessor API](https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor). I got faker loading with this plugins file:

```js
const webpackPreprocessor = require("@cypress/webpack-preprocessor");

module.exports = (on) => {
  const options = webpackPreprocessor.defaultOptions;
  options.webpackOptions.module.rules[0].exclude = {
    and: [/node_modules/],
    not: [/@faker-js/],
  };
  options.webpackOptions.resolve = {
    alias: {
      "@faker-js/faker": require.resolve("@faker-js/faker"),
    },
  };

  on("file:preprocessor", webpackPreprocessor(options));
};
```

**Comment by dante01yoon** [comment]
@ZachJW34 I see.. it would be better be fixed sooner or later.  fakerjs is the most well used for testing.
Thank you for your answer!

**Comment by dante01yoon** [comment]
@dante01yoon

**Comment by JessicaSachs** [comment]
This is fixed and merged. Will be deployed on Monday.

**Comment by Shinigami92** [comment]
@dante01yoon @ZachJW34 

Please checkout the newest version of Faker https://github.com/faker-js/faker/releases/tag/v7.3.0
