### ISSUE TITLE
filter spec files in open mode

### ISSUE THREAD

**Issue by MohamadKh75** [cypress-io/cypress#21876]
### What would you like?

Hey

It would be great to filter spec files in open mode, such as:

```bash
cypress open --spec "cypress/integration/login/**/*"
```

### Why is this needed?

In some cases, there are +20 folders so it would be great to have a filter option.
Also, sometimes there are multiple configs (mobile, desktop, etc.) and it would be great to open like these:

```bash
cypress open --config-file cypress/config/desktop.json --spec "cypress/integration/**/*.desktop.*"
```

```bash
cypress open --config-file cypress/config/mobile.json --spec "cypress/integration/**/*.mobile.*"
```

### Other

I can create a PR if it's approved!

**Comment by mjhenkes** [comment]
Closing as duplicate (https://github.com/cypress-io/cypress/issues/1925)
