### ISSUE TITLE
Migration guide using wrong support file on v10.x

### ISSUE THREAD

**Issue by tiagodread** [cypress-io/cypress#21934]
### Current behavior

Installed pre-release to poke around and went through the migration process, my config file was renamed from `cypress/support/index.js` to `cypress/support/e2e.js` as follow:

![Screen Shot 2022-05-30 at 16 56 56](https://user-images.githubusercontent.com/12464858/171053671-052120f7-5dcf-404a-b6e0-9dd1489a417d.png)

The next step is to convert my `cypress.json` into a `cypress.config.js` but note that `supportFile`  is pointing to the old file format.

![Screen Shot 2022-05-30 at 16 57 40](https://user-images.githubusercontent.com/12464858/171054782-7a0750c2-a337-46a2-9052-54b0b8c520dd.png)

The result is:
![Screen Shot 2022-05-30 at 16 59 28](https://user-images.githubusercontent.com/12464858/171054020-72ce8491-91e4-4995-9cf4-e6280a0e8430.png)

### Desired behavior

As a migration guide helper, if the file format/structure is changing, I'd expect the migration step in which generates the `cypress.config.js` script to use the new `supportFile` file format/structure or allow me to change anything needed.

### Test code to reproduce

Migrating to v10.x using latest devel version https://github.com/cypress-io/cypress/commit/2af1ad03bb3b23402650dd7f68a9e68ba2008431

### Cypress Version

10.0.0

**Comment by mjhenkes** [comment]
This was fixed in v10.0.1
