### ISSUE TITLE
Investigate adding support for ts-node/esm

### ISSUE THREAD

**Issue by tgriesser** [cypress-io/cypress#21939]
### Current behavior

In 10.0 using `package.json` with `"type": "module"` with `.ts` will not work out of the box without `esbuild` installed.

### Desired behavior

Cypress should use the `ts-node/esm` builder to support loading `.ts` from esmodules. https://github.com/TypeStrong/ts-node#commonjs-vs-native-ecmascript-modules

### Test code to reproduce

```
cd system-tests
yarn test config_modules_spec
```

`config-cjs-and-esm/config-with-ts-module` fails but it should pass

### Cypress Version

10.0

### Other

Related to #21574

**Comment by lmiller1990** [comment]
This will come for the ride with https://github.com/cypress-io/cypress/issues/22074 most likely! The core problem is the same: need better es module support.

**Comment by lmiller1990** [comment]
WIP PR: https://github.com/cypress-io/cypress/pull/22118.
