### ISSUE TITLE
`file:preprocessor` event not being fired during component testing

### ISSUE THREAD

**Issue by ItsaMeTuni** [cypress-io/cypress#21992]
### Current behavior

The `file:preprocessor` plugin event is not being fired during component testing.

### Desired behavior

The `file:preprocessor` event should be fired during component testing, just like it is fired during integration and unit testing.

### Test code to reproduce

https://github.com/ItsaMeTuni/cypress-preprocess-event-test

Take a look at `cypress/plugins/index.js`, there is a `console.log` in the
`file:preprocessor` event handler.

Run with `npm run cypress:run-ct`, if you look at the console the message "file:preprocess called!"
is not printed. If you run `npm run cypress:run`, the message is printed to the console (and
a few errors are thrown, but that doesn't really matter).

### Cypress Version

9.7.0

### Other

I've been digging through Cypress' source code but couldn't really find where the `file:preprocessor` is being fired. I believe it's in `packages/server/lib/plugins/child/run_plugins.js`, but I'm not sure. I'm not familiar with Cypress' architecture and organization, so I'm a bit lost in the source code. If anyone can point me in the right direction, I can try to solve this and submit a PR.

Thanks in advance for your time :)

**Comment by ZachJW34** [comment]
The preprocessor API is only available for e2e tests. Specs related to component testing are processed and served by the configured devServer (webpack or vite). If you need to change the compilation of component specs, you can do so my modifying your webpack or vite config.

What is the your use case for using `file:preprocessor` for component testing?

**Comment by mjhenkes** [comment]
This seems to be working as we expect it to be. Please open a new issue if there is new information to provide concerning the original issue and we can re-investigate.
