### ISSUE TITLE
textarea's values are not restored on hover of cy commands UI.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#22]
When I hover over previous commands, the value of textareas in the DOM are not restored. 

**Example**
This textarea should have value and previous assertion says textarea has value, but I can't see the value on hover of previous commands:
![screen shot 2015-04-16 at 11 46 50 am](https://cloud.githubusercontent.com/assets/1271364/7185064/9ac0be7e-e42e-11e4-92be-48874cd6666d.png)

**Comment by brian-mann** [comment]
Also `<select>` values are not restored as well.

**Comment by brian-mann** [comment]
After investigating the issue it seems to be resolved now. It might have been related to snapshotting too early in some cases, but after creating a series of tests they are all passing.

**Comment by brian-mann** [comment]
Actually there was a bug with this.

**Comment by brian-mann** [comment]
Fixed in [`0.11.11`](https://github.com/cypress-io/cypress/wiki/Changelog#01111-10042015).
