### ISSUE TITLE
Open interface cypress 10 mode getting error in windows 8.1

### ISSUE THREAD

**Issue by eduardoeberle** [cypress-io/cypress#22006]
### Current behavior

When try npm run cypress open

### Debug logs

```
It looks like this is your first time using Cypress: 10.0.0


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

[0601/152542.111:FATAL:v8_initializer.cc(508)] Error loading V8 startup snapshot file

----------

Platform: win32-x64 (6.3.9600)
Cypress Version: 10.0.0
```

### Cypress Version

10

### Package Manager

npm

### Operating system

Windows

### Other

Windowns version 8.1 Single Language 64 bit

https://www.loom.com/share/f0dcf5b06fe8438d99147e5b1feeb189

**Comment by jennifer-shehane** [comment]
Yeah my first suggestion was going to be to clear the cache, but it looks like you did that and it didn't work. 🤔

**Comment by flotwig** [comment]
@eduardoeberle Could you please try the command indicated above and let us know if it resolves your issue?

**Comment by eduardoeberle** [comment]
Solved.
