### ISSUE TITLE
cy.contains('foo', { yieldAll: true })

### ISSUE THREAD

**Issue by tjhillard** [cypress-io/cypress#2200]
### Current behavior:

cy.contains() yields only the first matched element and there is no config option to allow yielding of all matched elements. Only viable workaround for this is to use the `cy.get(el:contains(foo))` pseudo selector which is potentially deprecated (I couldn't find it mentioned in the current css3 spec) and kind of unknown/hacky. I had to dig to find out it was actually a thing.
 
### Desired behavior:

Add a new `yieldAll` property to the acceptable options config object for cy.contains. It's default state would be `false` and would behave as it currently does only returning first matched element. If set to a value of `true`, it will yield all matched elements, setting them as the subject and behave the same as a cy.get with the :contains pseudo selector currently does.

### Example

```js
 cy
    .get('.link')
    .contains('Sign Up', { yieldAll: true })
    .each(($el) => {
        expect($el).to.have.attr('href', '/sign_up');
    });
```

Idea inspired by [this gitter discussion.](https://gitter.im/cypress-io/cypress?at=5b56273eee530e4aac919a62)

**Comment by jennifer-shehane** [comment]
I think this would be a nice idea, but given the lack of interest over the years and since it has a workaround, we’ll be closing this issue.
