### ISSUE TITLE
Cypress 10 visual glitch in test runner

### ISSUE THREAD

**Issue by alvaromartmart** [cypress-io/cypress#22019]
### Current behavior

The pass/fail "badges" on the top of the specs runner don't display correctly on certain situations

![Screenshot 2022-06-01 at 23 47 27](https://user-images.githubusercontent.com/18287793/171507430-b889566c-482c-4542-8059-a86079e935a7.png)

### Test code to reproduce

* `npx cypress open`
* Select Chrome browser (I'm currently using v102)
* Run any spec. Badges display correctly
* Go to the "Runs" tab
* Go back to the "Specs" tab and run something again. The badges are not correctly displayed.

https://user-images.githubusercontent.com/18287793/171507962-f200add8-0f00-4dac-9910-e7ac9145009b.mov

### Cypress Version

10.0

**Comment by ZachJW34** [comment]
Yup we have a style leak. We have an [existing issue](https://github.com/cypress-io/cypress/issues/21931) and an [open PR](https://github.com/cypress-io/cypress/pull/22014) so going to close this as a duplicate. Thanks for checking out Cypress 10! We'll have this fixed soon
