### ISSUE TITLE
When specifying multiple test files to run the test result file only contains the results for last run spec

### ISSUE THREAD

**Issue by search8** [cypress-io/cypress#2201]
### Current behavior:

When running multiple specs from the CLI the test result file only contains entries from the last ran spec. 

### Desired behavior:

1. Either don't delete the test result file before every spec is run and just add them to the same file. 
2. Or allow for multiple files to be created, one per spec and then one can concatenate those when needed to. 

### Steps to reproduce:

I have been trying to get the second approach to work as a workaround but the filename is evaluated at the beginning and never adjusts after that. So even though it is a timestamp now the filename is still the same over the course of a test run. 

```
cypress run --spec 'cypress/integration/registration/registration_spec.js,cypress/integration/login/login_spec.js' --browser chrome --reporter junit --reporter-options mochaFile=./test-results/test-result_$(get-date -f yyyyMMdd_HHmmss).xml
```

I'm using the jUnit reporter because I want to integrate cypress in my TFS CI build which limits my options. 

### Versions

Windows 10, Chrome 67, Cypress 3.0.2

**Comment by jennifer-shehane** [comment]
I would suggest checking out this thread discussing reporters when running isolated spec files (as you are doing. https://github.com/cypress-io/cypress/issues/1824

**Comment by search8** [comment]
Thanks for the link. I searched under the wrong context.

[hash] is good enough for me for now, so that resolves my issue.

Thank you!

**Comment by lasithdilshan20** [comment]
Hi, 
Is there a way to maintain "cypress/integration/registration/registration_spec.js,cypress/integration/login/login_spec.js" this values in a variable?
