### ISSUE TITLE
Consider changing rules for determining whether a project uses TS

### ISSUE THREAD

**Issue by tgriesser** [cypress-io/cypress#22018]
### What would you like?

From #22004

> I don’t have a tsconfig, don’t use typescript in the project, I have a tsconfig.json.ignore from back when I did, but that’s clearly nothing

We should probably tighten [the algorithm](https://github.com/cypress-io/cypress/blob/369a865237df4388c6421d5eae7ed948dd606606/packages/scaffold-config/src/detect.ts#L75-L104) for determining whether to use `ts` or not in a project from:
```
IF `typescript` dependency in `package.json` OR `tsconfig.json` in `projectRoot/*`
```

to:

```
IF `typescript` dependency in `package.json` AND `tsconfig.json` in `projectRoot/*`
```

We should be detecting via existence in `dependencies / devDependencies / peerDependencies` as well as resolving it to confirm it's usable

cc @ZachJW34 / @lmiller1990 as I think y'all worked on this one the most.

### Other

Related: https://github.com/cypress-io/cypress/issues/21927

**Comment by jennifer-shehane** [comment]
Let's make sure to update the [tech-brief](https://github.com/cypress-io/tech-briefs/tree/main/briefs/is-project-using-js-or-ts) if we change this logic.

**Comment by lmiller1990** [comment]
> We should be detecting via existence in dependencies / devDependencies / peerDependencies rather than resolving it

I don't think we are resolving it anywhere. What gave you this impression?

We can easily make the suggested change. I think there are some outstanding issues in #22004 that are not related to the TS detection algorithm.

**Comment by lmiller1990** [comment]
Also @tgriesser I wonder if we want to rethink the brief a little as part of this. I made a PR: https://github.com/cypress-io/tech-briefs/pull/28. What do you think?

**Comment by tgriesser** [comment]
Yeah, let's make this change - seems it's a common enough issue that folks are running into

**Comment by tgriesser** [comment]
Actually, we probably should *also* be resolving it, because if they don't have it installed it'll immediately error for them when they scaffold
