### ISSUE TITLE
Cypress 10 - windows - project migration - files not scaffolded

### ISSUE THREAD

**Issue by modern-sapien** [cypress-io/cypress#22010]
### Current behavior

BUG: On a windows machine trying to migrate existing projects from an older Cypress version 8.x.x or 9.x.x to Cypress 10.0.0 leads to an incomplete migration. 

- Same behavior is not present for the two other mac users on the call.
- supportFiles for e2e & ct not created
- video is not displayed
- additional migration steps not present

![](https://files.slack.com/files-pri/T0DGMSL05-F03HT2LPXU5/image.png)

### Desired behavior

With the migration all appropriate files that are scaffolded for Mac should also be scaffolded and present for windows

### Test code to reproduce

1. create a project using an older Cypress version than 10.0.0 on a windows machine
2. npx open cypress
3. follow the steps to update appropriately
4. re-open cypress

### Cypress Version

8.x.x

### Other

9.x.x

**Comment by modern-sapien** [comment]
Yes, this was encountered with any other projects that had pre-existing Cypress repos as well.

**Comment by marktnoonan** [comment]
I migrated from 9.6.1 to 10.0.1 and got the expected migration landing page. Jonathan and I are going to sync later today and see if we can reproduce on his machine with logs, it does not appear to be a general Windows issue.

![Screen Shot 2022-06-02 at 10 32 41 AM](https://user-images.githubusercontent.com/8340719/171662642-f821579b-40c0-413d-8a7a-23399b0d8714.png)

**Comment by marktnoonan** [comment]
Status update: after meeting to review this, I could see that, for this project on Jonathon's computer, the issue was present in 10.0.0 but resolved in 10.0.1. I've done some experimenting on Windows with 10.0.0 and not yet been able to reproduce the bug in any situation on our Windows VM with the same project.
