### ISSUE TITLE
Cypress 10 - Windows - no default spec file type after creation of net new project

### ISSUE THREAD

**Issue by modern-sapien** [cypress-io/cypress#22016]
### Current behavior

I created a new Cypress project and when trying to run for the first time I chose to scaffold the example specs to see them run. What I found was that there were 0 matches for the spec pattern that Cypress scaffolds out. 

When trying to resolve clicking on the "need help" hyperlink takes me to the "Why Cypress?" docs and the "Update Spec Pattern" button just leads me to the cypress.config file but provides no explanation of how to set the pattern

![image (11)](https://user-images.githubusercontent.com/58672259/171491598-04ffbff1-5a32-43c0-b739-76a9326a63d8.png)

### Desired behavior

When I install a net new version the cypress.config should be configured to the recommended spec patterns for me and at minimum should align with the specs that are scaffolded out when a user wants to work with example spec files.

### Test code to reproduce

- install cypress on a project without
- npx cypress open and navigate to scaffolding out example spec files

### Cypress Version

10.0.0

### Other

- This behavior is not present on a Mac machine and the spec pattern also doesn't need to be explicitly set to run the scaffolded specs. 
- on a Windows machine

**Comment by jennifer-shehane** [comment]
That is pretty unusual. Can you show where the files are located for the scaffolded kitchensink files? The specPattern looks accurate to my understanding, so maybe it's some kind of paths reading incorrectly.

**Comment by modern-sapien** [comment]
![image (11)](https://user-images.githubusercontent.com/58672259/171511441-fec6b6ea-f38e-47fb-9eff-3d11ae9c6b7b.png)

**Comment by modern-sapien** [comment]
Didn't mean to have an extra huge image.

**Comment by marktnoonan** [comment]
Thanks @modern-sapien, some different points of feedback here that we might need to dig into separately - specifically, around the usability of the info/links that are intended to help you here. Let's capture that.

I tested on Windows and was able to scaffold e2e tests just fine on a brand new project, and also on an existing one, with and without a spec pattern set explicitly.

![Screen Shot 2022-06-02 at 10 00 25 AM](https://user-images.githubusercontent.com/8340719/171646798-fd89e668-0b1c-4f1c-b2b1-13c7ad06196e.png)

Could we get debug logs? My files look like they scaffolded in exactly the same place as yours.

**Comment by marktnoonan** [comment]
Just duplicating [this comment](https://github.com/cypress-io/cypress/issues/22010#issuecomment-1147386416) on a closely related issue for clarity: 

> Status update: after meeting to review this, I could see that, for this project on Jonathon's computer, the issue was present in 10.0.0 but resolved in 10.0.1. I've done some experimenting on Windows with 10.0.0 and not yet been able to reproduce the bug in any situation on our Windows VM with the same project.

**Comment by dchomedan** [comment]
Hey folks, I've just upgraded to Cypress 12.11.0 and think I'm what seems to be the same issue, except that it's not building out the 1-getting_started and 2-advanced-examples folders & files in the expected destination at all:
--after choosing to scaffold the examples, I get the message "Great! We added the following files to your project:" with no files shown

**Comment by dchomedan** [comment]
I also noticed that the "Create new spec" button is completely unresponsive; note also that this was the same behavior before updating from 12.10.0 to 12.11.0

**Comment by nagash77** [comment]
Hi @dchomedan Can you please open a new ticket with a reproducible example and our team will be happy to investigate.  Thank you!
