### ISSUE TITLE
Cypress 10 migration tool does not work with custom support file path

### ISSUE THREAD

**Issue by ddzz** [cypress-io/cypress#22012]
### Current behavior

Our project uses a custom directory structure for our Cypress tests. Our support file is in `repo/src/platform/testing/e2e/cypress/support/`. In the Cypress 10 migration tool, clicking on `Rename the support file for me` does nothing, and I can't proceed to the next step.

<img width="1200" alt="Screen Shot 2022-06-01 at 3 02 29 PM" src="https://user-images.githubusercontent.com/3535749/171491953-74d22559-e8a5-494f-a043-a613a5c05246.png">

### Desired behavior

I should be able to use the Cypress 10 migration tool with a custom directory structure.

### Test code to reproduce

Our project is open-source: https://github.com/department-of-veterans-affairs/vets-website

The Cypress configuration is in the `/config` directory.

### Cypress Version

10.0.0

**Comment by jennifer-shehane** [comment]
@ddzz Thanks for reporting and providing a reproducible example. We're getting a fix in for this now.
