### ISSUE TITLE
Config does not always reload as expect during CT setup

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#22024]
### Current behavior

This is slightly barebones, will add more detail tomorrow, but wanted to capture this issue.

Almost always, when a user saves their config file, the Cypress launchpad shows a loading screen and starts using the new config, but during the Component Testing setup, if we save the config file, here is what I see:

1. If I do it on the Framework picker or the Install Dev Dependencies screen, the spinner appears and I get kicked back to the testing type picker. This actually seems fine - the config update could have changed options in the testing type being set up.
2. If I save the config file while I am on the Configuration Files screen, it seems to update only if it hasn't already done so once, see this video around 30s in: https://www.loom.com/share/42e406c207e04731a099a4f4a60c5cc0

With debug logs turned on, I see activity from the watcher, so at a glance, we are still reacting to the file changes to some extent.

**TODO**

Verify if this can be reproduced in E2E setup, and with projects other than Vuetify.

### Desired behavior

Cypress should always reload the watched config file.

### Test code to reproduce

Clone https://github.com/vuetifyjs/vuetify/tree/next and switch to the `next` branch. In`packages/vuetify`, update Cypress to 10.0.0 and run `yarn cy:open`

### Cypress Version

10.0.0

### Other

First reported by @JessicaSachs. Will retest tomorrow with 10.0.1.

**Comment by lmiller1990** [comment]
Going through the CT backlog - I don't doubt there's some edge case (saving your config file during onboarding) but I can't imagine we will ever dedicate time to actually working on this - I'm going to close it as wontfix.
