### ISSUE TITLE
Browser view does not bypass the splash screen when running headless

### ISSUE THREAD

**Issue by radiobrain77** [cypress-io/cypress#2203]
Operating System: macOS High Sierra (also happens in docker container running through Jenkins)
Cypress:    3.0.2                                                                              │
Browser:    Electron 59 (headless)

### Current behavior:

The browser view does not bypass the splash screen. This happens when I run in headless.

The Ionic app I am testing on shows a logo panel over the top of the login page when first visiting the website. If I run this test in the Cypress test browser, it will clear the logo after a brief wait and then show the start page. From here I am able to click the sign in button.

However, in headless mode, the logo remains on the screen throughout all tests. When the test attempts to click on the 'sign in' button, the following error occurs:

```
CypressError: Timed out retrying: cy.click() failed because this element:

<h1>Sign in...</h1>

is being covered by another element:

<div style="background-color: rgb(185, 48, 66); position: absolute; z-index: 99999; width: 1000px; height: 660px; top: 0px; left: 0px;">...</div>

Fix this problem, or use {force: true} to disable error checking.
```

This is the test I am using to create this:

```js
describe('First test on first visit to page ', function () {
    it("Should open start page", function() {
        cy.visit('/');
        cy.wait(10000);
        cy.contains("Sign in").should('exist').click();
    })
})
```

### Desired behavior:

The app should just let the app move past the splash screen. Then I should be able to click on the 'sign in' button. 

Alternatively, I should be able to find out why Cypress is not letting the app progress. eg a notification that an event has failed to fire.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this - with test code + application code we can run locally to see the problem?

**Comment by radastojcevic** [comment]
I experienced the same problem with splash screen. Have you found its solution?
