### ISSUE TITLE
Cypress runner is broken with cypress/included version 10.0.0

### ISSUE THREAD

**Issue by LucasMarco2409** [cypress-io/cypress#22046]
### Current behavior

I try to execute `cypress run --headless --spec "cypress/e2e/**/*.cy.js" --reporter cypress-multi-reporters` within cypress included docker container in openshift. But I get following error in terminal:

```
The Test Runner unexpectedly exited via a exit event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Debian - 11.3)
Cypress Version: 10.0.1
```

The same command works properly with 9.7.0 image version and cypress version 9.7.0 within my project.

### Desired behavior

cypress runner will not crash with new version 10.0.0

### Test code to reproduce

N/A

### Cypress Version

10.0.0

**Comment by jennifer-shehane** [comment]
@LucasMarco2409 Can you provide a repo that we could run to reproduce this issue? Can you try removing the flags you passed and see if the run runs without them? Maybe it has to do with the options being passed?

**Comment by david-schopf** [comment]
Cypress 10.0.1 is still crashing on M1:

**Comment by LucasMarco2409** [comment]
Hi there I removed the options so that I just execute `cypress open` but still the same error. I can not provide the repository.

> > cypress run

The Test Runner unexpectedly exited via a exit event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Debian - 11.3)
Cypress Version: 10.0.2

**Comment by ZachJW34** [comment]
I was not able to reproduce this using the latest `cypress/included` docker image and a matching config file. @LucasMarco2409 if you can provide a minimal reproduction then we can dig in further.

@david-schopf if you are having issues on an M1, please create another issue and we can track it there.

**Comment by david-schopf** [comment]
@ZachJW34 it works with 10.0.2, so fine for me.

Thank you!

**Comment by karlhorky** [comment]
Interesting, this `dyld[58541]: Library not loaded` error came back for me in `10.0.3` 😱 @mjhenkes maybe it shouldn't be closed already?

```
It looks like this is your first time using Cypress: 10.0.3


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

dyld[32033]: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Users/k/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/MacOS/Cypress
Reason: tried: '/Users/k/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/Users/k/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (not a mach-o file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file)

----------

Platform: darwin-x64 (21.5.0)
Cypress Version: 10.0.3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/k/.nvm/versions/node/v16.11.0/bin/node
Arguments: /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js cy
```

**Comment by karlhorky** [comment]
## Workaround

Open the Cypress app folder with `open /Users/k/Library/Caches/Cypress` and then rename the `10.0.2` to `10.0.3` 😅

Gives you a warning about mismatching version numbers, but seems to work.
