### ISSUE TITLE
Bring back "Run all specs" GUI option

### ISSUE THREAD

**Issue by pjg** [cypress-io/cypress#22047]
### What would you like?

I'd like to be able to easily run all specs via the GUI as it was possible prior to the 10 version.

### Why is this needed?

It is needed because running specs via `cypress run` is extremely slow as it seems that every single spec spawns its own React app, which requires compilation. Also it is very convenient to see all specs as they are being run.

**Comment by conversaShawn** [comment]
@pjg Would you mind adding your feedback to this [GitHub discussion](https://github.com/cypress-io/cypress/discussions/21628) as well? This helps us keep all feedback in one area when considering what impacts our Users most.
