### ISSUE TITLE
Selector playground only copies the selector, not the command like before (v10)

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#22043]
### Current behavior

In the selector playground mode, clicking the "Copy" button used to copy the entire command. Now it only copies the selector

<img width="906" alt="Screen Shot 2022-06-02 at 10 14 36" src="https://user-images.githubusercontent.com/2212006/171649796-62ae44d7-39f6-4f18-aa32-ebd669869878.png">

Copied: `body`

Funny that "Print to console" button prints the entire command correctly
<img width="167" alt="Screen Shot 2022-06-02 at 10 16 21" src="https://user-images.githubusercontent.com/2212006/171650136-226fd717-2aba-4cd9-93f6-457fc2ac5270.png">

### Desired behavior

Copy the entire command like in v9

Also: the selector button itself should have "selector is opened" state

<img width="306" alt="Screen Shot 2022-06-02 at 10 16 54" src="https://user-images.githubusercontent.com/2212006/171650294-7a313e22-018c-4794-854e-59fca0928867.png">

### Test code to reproduce

- open selector playground
- select any element on the page
- click the "Copy" button
- check the Clipboard

### Cypress Version

v10.0.1

**Comment by jennifer-shehane** [comment]
@bahmutov Thanks for reporting. It should definitely not be doing that.

**Comment by ZachJW34** [comment]
Verified that we are not in parity with 9.x on this.

@ryanjwilke what do we want for the selector-playground button? 9.x has a gray background and a tooltip. I can throw the indigo state on the icon when selected, but do we want the tooltip?

**Comment by ryanjwilke** [comment]
@ZachJW34  Having a tooltip would probably make sense. Relying only on the icon isn't always intuitive for everyone.

**Comment by JawadM-TaiSoftware** [comment]
Released?

**Comment by rockhold** [comment]
@JawadM-TaiSoftware, we're working toward a 10.0.4 patch release for today. If all goes according to plan, this should be available later this afternoon. You'll see an automated update on this issue once it is released :)

**Comment by JawadM-TaiSoftware** [comment]
When will the update be pushed as of now?

**Comment by rockhold** [comment]
@JawadM-TaiSoftware, we've run into issues with failing Windows tests that are holding things up. The team is looking into whether they are just flaky or if something legitimately broken snuck through under the guise of flake in a previous merge. We run a team that spans several timezones and have intentionally remained mindful of the working hours we're requesting for those involved in these patches and releases. Today's code cutoff is 2pm EDT, with plans to release after that. Whether 10.0.4 is released today depends on whether we can get successful builds in time to complete the release by EOD (roughly 5pm EDT). If you don't see it by then, you can anticipate that we'll continue working towards the 10.0.4 release tomorrow.

In case you're interested, though, this [documentation PR](https://github.com/cypress-io/cypress-documentation/pull/4562) will progress with the actual release. You can follow along with that if you'd like. We're excited to get more fixes into this next patch and appreciate our users' patience as we continue our work at a sustainable pace :)
