### ISSUE TITLE
Cypress test hangs indefinetly when running in Azure Devops Pipeline

### ISSUE THREAD

**Issue by awallemo** [cypress-io/cypress#22044]
### Current behavior

I am trying to run a simple spec in the Azure DevOps release pipeline but it keeps hanging at this point:

Can any one help me?

### Test code to reproduce

Can not give the test code.

### Cypress Version

9.5.4

**Comment by awallemo** [comment]
@mschile how can I verify that Chrome is installed in the pipeline? Unfortunately I cannot reproduce the code as it is confidential..

**Comment by mschile** [comment]
@awallemo, thanks for the response. I was incorrect in my initial response as the message for when Chrome is missing is different.

What command are you running in the Azure DevOps pipeline? Does the same command work locally? Do other browsers work? Can you try Firefox and Electron?

Could you run Cypress in [debug mode](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) mode and include the logs here?

**Comment by awallemo** [comment]
@mschile Sorry for the late response. This is the command I am running (With Debug):
![image](https://user-images.githubusercontent.com/54357341/172312853-82ebc423-5426-47a0-b72b-2abfeb1159f7.png). It works completely fine when I run it locally. 

These are some of the outputs from running with debug. 
![image](https://user-images.githubusercontent.com/54357341/172313419-86e25c8a-8b93-41c7-8c5e-a14d6da7d831.png). I got 25000 lines of output when the debug was set and It just kept on running until the agent job cancelled it after 30 minutes. The screenshot of the debug is something that was logged several times over and over again..

**Comment by AtofStryker** [comment]
Hey @awallemo. It looks like the chrome process is running. This screenshot logs look mostly like the video screencasting and the process profiler, which unfortunately doesn't tell us too much. Would it be possible to run `cross-env DEBUG=cypress:*,-cypress:server:util:process_profiler cypress run --config-file <YOUR_CONFIG_FILE> --browser chrome --spec <YOUR_SPEC> --config video=false` and attach the full output with sensitive data omitted to this issue? Does running `cross-env DEBUG=cypress:*,-cypress:server:util:process_profiler cypress run --config-file <YOUR_CONFIG_FILE> --browser electron --spec <YOUR_SPEC> --config video=false` work and is it possible to attach that output as well?

Within your Azure Devops pipeline, are you able to share your pipeline tasks (or docker image if applicable) with sensitive data omitted? That would be incredibly valuable here to help us gain some context into what could possibly be occuring.

**Comment by awallemo** [comment]
@AtofStryker 
I ran the command you specified, I have set the task to time out after 5 minutes so it doesnt run indefinetly when it hangs. This is the output:
![Screenshot 2022-06-08 144219](https://user-images.githubusercontent.com/54357341/172623097-7db8288c-787c-4075-a58d-f1d8e5d8b101.png)
![Screenshot 2022-06-08 145110](https://user-images.githubusercontent.com/54357341/172623104-c5339fb2-cff7-40a0-853e-b58d67b39991.png)
![Screenshot 2022-06-08 145832](https://user-images.githubusercontent.com/54357341/172623106-18e4a86d-6b23-4d02-83ae-ea303d9890ac.png)

There are a lot more output 

And these are the tasks in the pipeline: 

![image](https://user-images.githubusercontent.com/54357341/172623304-528139da-03f6-4649-b697-fec890696f01.png)

**Comment by AtofStryker** [comment]
> I found that updating ngx-build-plus to version 14 made cypress hang. But with version 13 everything was just fine and completes.

@YoupHulsebos is there an issue open for this bug you are seeing? If not, I would strongly encourage you to open one so we can triage it appropriately. I want to make sure it gets logged someplace 😄 .

**Comment by YoupHulsebos** [comment]
No, I didn't create a issue for it just yet. The upgrade of the package was proposed by renovate automatically. As was the cypress update to v10.  But since that also included the angular upgrade to V14 I reverted some. As soon as we have some time to tackle all the upgrades and the issue is still present I will create a issue.
