### ISSUE TITLE
cy.mount is missing typescript definition

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#22048]
### Current behavior

Every `cy` command has TypeScript definition, but `cy.mount` is showing "any"

<img width="715" alt="Screen Shot 2022-06-02 at 11 41 13" src="https://user-images.githubusercontent.com/2212006/171667748-ecf56c24-d9fe-46d1-a346-d1dd14cdd2f9.png">

### Desired behavior

Add TS definition

### Test code to reproduce

Any component test with `cy.mount` and `/// <reference types="cypress" />` comment and hover over `cy.mount`

### Cypress Version

10.0.1

**Comment by jennifer-shehane** [comment]
@bahmutov There's instructions for adding types for `cy.mount()` here: https://on.cypress.io/mount#Adding-TypeScript-Typings-for-cy-mount-Commands Is this helpful? Is there something else that would help the experience be better?

**Comment by elylucas** [comment]
Hi @bahmutov, does this doc help with the issue? https://docs.cypress.io/guides/component-testing/component-test-troubleshooting#The-TypeScript-Types-for-cy-mount-is-Not-Working-in-Component-Tests

The generated mount command has the typings for it in the `cypress/support/component.ts` file, however those are not picked up by default for some frameworks when specs are in the `src` folder. The doc above talks about various ways to get the typings to pick up. We are looking at some ways to improve that soon.
