### ISSUE TITLE
Changing the baseUrl value in cypress.config.js will not take effect until restarting cypress

### ISSUE THREAD

**Issue by Ibrahim-Krasniqi** [cypress-io/cypress#22056]
### Current behavior

when changing the value of `baseUrl` in `cypress.config.js` both the cypress window as well as the cypress controlled instance of the browser reload giving the impression that the changes to configuration are taking effect, this is not the case however

Note: I did not test all values that can be altered in `cypress.config.js` however at least with `viewportWidth` and `viewportHeight`, altering them and saving does not require a restart of cypress for them to take effect. 

### Test code to reproduce

create cypress.config.js with the following code:
```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({

  e2e: {
    baseUrl: 'https://www.google.com/'
  }
})
```
`cypress open` in terminal 
change the contents of cypress.config.js to the following while cypress is running:

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({

  e2e: {
    baseUrl: 'https://www.cypress.io/'
  }
})
```

you will notice that even though the page reloads the test still go to the first url

### Cypress Version

v10.0.1

**Comment by jennifer-shehane** [comment]
@Ibrahim-Krasniqi Thanks for reporting, we'll investigate this. This is not the desired behavior.
