### ISSUE TITLE
Cypress 10.0.0 or 10.0.1 Migration tool doesn't load 

### ISSUE THREAD

**Issue by amartin1984** [cypress-io/cypress#22065]
### Current behavior

When I try to update to Cypress 10+ I am not given the option to use the migration tool 
![image](https://user-images.githubusercontent.com/19328404/171738701-d2875a9e-7497-4432-80e6-4d15a64bf17c.png)

The behavior is the same for both 10.0.0 and 10.0.1

We have thousands of files and I would prefer to not have to do the work manually for the upgrade. 

### Cypress Version

10.0.1

### Package Manager

npm

### Operating system

Mac

**Comment by jennifer-shehane** [comment]
@amartin1984 Can you provide the full message displayed in the error? Can you provide your the contents of your plugins file and ideally a repo we can run to reproduce?

**Comment by lmiller1990** [comment]
Assigning/commenting since I'm following the migration bugs closely, I can help work through this.

**Comment by amartin1984** [comment]
Error: ENOENT: no such file or directory, open '/Users/amartin/Cypress/Mosaic/integration_test/cypress/plugins/config/ci.json'

index.js
`const fs = require('fs-extra')
const chalk = require('chalk')
const configHandler = require('./config_handler')
const preAuth = require('./pre_auth')
const getGrades = require('./grades')
const parseXlsx = require('./parse_xlsx')
const setDefaultDownloadDir = require('./set_default_download')
const updateTransactionsBeforeCypressStarts = require('./updateTransactionsBeforeCypressStarts')
const { beforeRunHook, afterRunHook } = require('cypress-mochawesome-reporter/lib')

module.exports = async (on, config) => {
  const startTime = +new Date()
  const cypressConfig = config.env.configFile || 'ci'
  config = await configHandler.getConfigurationByFile(cypressConfig)
  await setDefaultDownloadDir.setDefaultDownload(config)
  on('before:run', async (details) => {
    console.log('override before:run')
    await beforeRunHook(details)
  })

  on('after:run', async () => {
    console.log('override after:run')
    await afterRunHook()
  })

  //See Cypress Issues #1872 and #3049
  //here https://github.com/cypress-io/cypress/issues/1872#issuecomment-450807452 for this workaround.
  //Eventually may be able to remove. Looks like not resolved in 3.2.0.
  on('before:browser:launch', (browser = {}, launchOptions) => {
    // when running locally, we create CSVs for every file import we do - clean them up before every spec here
    if (process.env.LOCAL_CSVS == 1) {
      console.log('Deleting CSVs from Previous Specs')

      // delete everything in the 'csvs' folder
      fs.removeSync('csvs')
    }
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      // ^ make sure this is your browser name, you may
      // be using 'canary' or 'chromium' for example, so change it to match!
      launchOptions.preferences.default['download'] = { default_directory: config.env.downloadDirectory }
      launchOptions.args.push('--proxy-bypass-list=<-loopback>')
      launchOptions.args.push('--auto-open-devtools-for-tabs')
      return launchOptions
    }
  })
  on('task', parseXlsx)

  if (process.env.LOCAL_CSVS == 1) {
    config.env.local_csvs = true
  }

  try {
    await getGrades.getGradesFromAPI(config)

    // When running locally, get the tokens from the API
    config.env.tokens = await preAuth.getTokensFromApi(config)

    // attempt to update any transactions in processing state to clean things up before we run
    updateTransactionsBeforeCypressStarts(config)
  } catch (ex) {
    console.log(ex)
    console.log(
      chalk.red(`
      ran into an issue in plugins/index.js while attempting to hit API.

      known causes:
      if you are targeting local, consider running the API
    `),
    )
    process.exit(1)
  }

  const endTime = +new Date()
  console.log(`\n\nTotal plugins file time: ${endTime - startTime}ms\n\n`)
  return config
}
`

I'll ask about the repo but I doubt I'll be allowed to share it.

**Comment by lmiller1990** [comment]
Thanks for the info. Just to confirm my understand, and forgive the obvious question - does `/Users/amartin/Cypress/Mosaic/integration_test/cypress/plugins/config/ci.json` exist prior to and **after** your migration? I just tried migrating a project with a file in `cypress/plugins/config/ci.json` and it worked fine (eg, file was not unexpectedly removed), but it'd be good to clarify that it's not unexpected removed during your migration.

**Comment by amartin1984** [comment]
there is no plugins/config/ci.json prior. 

Before we have 2 index files index.js and index-local.js and yes our configuration is dynamic over about 20ish enviroments. 

There has been no migration.  The tool never pops up.

**Comment by lmiller1990** [comment]
Interesting, I think the `require` is somehow getting fed the incorrect path. It's trying to require a `cypress/plugins/config/ci.json` which is supposed to be `cypress/config/ci.json`?

It's a little hard to debug more without more code but:

```js
  const cypressConfig = config.env.configFile || 'ci'
  config = await configHandler.getConfigurationByFile(cypressConfig)
  await setDefaultDownloadDir.setDefaultDownload(config)
```

and

```
const configHandler = require('./config_handler')
```

Seem like the best places to look. I am not too sure but somehow the module is no longer resolved correctly - I'll keep trying to reproduce it locally.

**Comment by amartin1984** [comment]
[config_handler.txt](https://github.com/cypress-io/cypress/files/8832431/config_handler.txt)

**Comment by jannegpriv** [comment]
I have exactly the same problem, we also use the old `cypress/plugins/index.js` for configuring a separate config folder on the same level as cypress folder, that config folder contains different json-files with config for different test environments.
Folder structure:
```
project/config/linkedin.json
project/cypress/
project/cypress.json
project/package.json
```

I tried to use your w.o. but I got the same error.

Our old index.js contains:

```
const fs = require('fs-extra')
const path = require('path')

function getConfigurationByFile (file) {
    const pathToConfigFile = path.resolve('.', 'config', `${file}.json`)
    return fs.readJson(pathToConfigFile)
}

module.exports = (on, config) => {
    // `on` is used to hook into various events Cypress emits
    // `config` is the resolved Cypress config
    const file = config.env.configFile || 'linkedin'
    return getConfigurationByFile(file)
```

and in the project/config folder we have e.g. the file linkedin.json containing specific config for that test site.

**Comment by amartin1984** [comment]
`const pathToConfigFile = path.resolve(path.join('../..', 'config', `${file}.json`))`

This did it for me!!   Thank you @jannegpriv

**Comment by amartin1984** [comment]
OK so now Cypress runs but it completely skipped the migration helper.   Does this mean I'm going to do everything manually? @lmiller1990

**Comment by lmiller1990** [comment]
Not at all @amartin1984 - it should show the migration helper, if you’ve still got a cypress.json file in your repo. 

You could try running with DEBUG=cypress* npx cypress open, the terminal should have more logs, which you copy paste here. You definitely do not need to migrate manually, once the pluginsFile runs, it should show the migration screen. What are you seeing?

**Comment by amartin1984** [comment]
I get this screen
![cypress](https://user-images.githubusercontent.com/19328404/172156124-261e73d6-f0ab-427f-b163-1dd6df07f438.jpg)
[Log.txt](https://github.com/cypress-io/cypress/files/8844238/Log.txt)
Debug Log attached

**Comment by lmiller1990** [comment]
Thanks for the debug log. Will look into this one first thing next week - please wait a few days.

**Comment by leilafi** [comment]
Im having the similar issue. Here are the logs. Please let me know if it isn't the same and to create a separate thread for it.
[cypresslogs.txt](https://github.com/cypress-io/cypress/files/8899717/cypresslogs.txt)

**Comment by lmiller1990** [comment]
@leilafi Thanks for the log - looking at your debug logs, I can see `/Users/leilafirouz/Library/Caches/Cypress/9.6.0/Cypress.app` - it looks like you are still launching Cypress 9 in your project. Did you install Cypress 10? You need to run `npm install cypress` and make sure v10 is installed before upgrading - it won't automatically install.

@amartin1984 I can't see much in your logs - can you try running it with `DEBUG=cypress:*` (note `cypress:*`, not `cypress*` - if you miss the `:`, you get the verbose logs, which have a lot of extra information). You might need to increase the scroll back on your terminal to make sure you capture everything - it should look like the ones in the above post (cypresslogs.txt). Make sure you reset your repo to the Cypress 9 state (remove any `cypress.config.js` that might have been created during a previous migration attempt). It looks like it's detecting `cypress.config.js` and thinks you've already migrated, which isn't the case.

**Comment by amartin1984** [comment]
New log file attached
[newLog.txt](https://github.com/cypress-io/cypress/files/8908946/newLog.txt)

**Comment by rachelruderman** [comment]
Hi @amartin1984 , thank you for the logs!! Looking through them, I see it's trying to launch Cypress 10.1.0, but it errors out when it looks for `'/Users/amartin/Cypress/Mosaic/integration_test/cypress/plugins/cypress.json'`. In version 10, `cypress.json` was deprecated in favor of `cypress.config.js` / `cypress.config.ts`. Can you tell me what you're doing with `cypress.json`, i.e. is it being imported or configured somewhere? Also, if you have a minimal repo with your setup where the problem is reproducible, that would be very helpful 🙏 🙂 

> [Error: ENOENT: no such file or directory, open '/Users/amartin/Cypress/Mosaic/integration_test/cypress/plugins/cypress.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/amartin/Cypress/Mosaic/integration_test/cypress/plugins/cypress.json'
}
      ran into an issue in plugins/index.js while attempting to hit API.
      known causes:
      if you are targeting local, consider running the API

**Comment by rachelruderman** [comment]
@amartin1984 by the way, a few things we'd like to highlight: 

1. The error thrown is not coming from Cypress -- it's coming from something internal on your end
> ran into an issue in plugins/index.js while attempting to hit API.
known causes:
if you are targeting local, consider running the API

2. Given that you had dynamic config imports elsewhere, there's a good chance you may have a few more dynamic configs floating around that are resulting in the file lookup for `/Users/amartin/Cypress/Mosaic/integration_test/cypress/plugins/cypress.json`

**Comment by rachelruderman** [comment]
@leilafi Thank you for sending the logs! From the logs it looks like you already have a `cypress.config.js`, which indicates migration completed. Our recommendation would be to `git reset` your way to before the migration, and go through migration again

**Comment by amartin1984** [comment]
Thank you so much @rachelruderman  I was able to get the migration help to run when I commented out some custom code in the index.js file for the migration.   Now I'm stuck on this screen.   
![image](https://user-images.githubusercontent.com/19328404/174295999-f909a3f3-9397-4fbc-a98d-35570ba3d1fe.png)

We have thousands of files and tests and I really don't want to do the migration effort by hand.

**Comment by amartin1984** [comment]
I did the conversion by hand because the way cypress has changed fundamentally is way different than the way we run.  I think at this point I'm good with the initial intent of this ticket.

**Comment by rachelruderman** [comment]
@amartin1984 thanks for the update, I'm glad you were able to migrate in the end, one way or another! Out of curiosity, when you said `"Now I'm stuck on this screen."`, what did you mean exactly by "stuck"? I.e. it was frozen, or button clicks didn't work, or it was perpetually loading, etc?

**Comment by rachelruderman** [comment]
Hi @leilafi , thank you as well for the update and for sharing these screenshots. The error messages seem to be pretty straightforward this time around:

1. It looks like an error is being thrown when trying to open `cypress/config/core.json`. If that's not the filepath you're expecting, then tweaking your `getConfigurationByFile` method to locate the expected path will work.
2. `testFiles` was renamed to `specPattern` and needs to go within the testing type property rather than the root, i.e. `e2e`

**Comment by amartin1984** [comment]
@rachelruderman  the button click didn't do anything to update the files.

**Comment by lmiller1990** [comment]
I thought about this more - I don't see any `cypress.json` files in this issue. It's possible this is a similar issue to https://github.com/cypress-io/cypress/issues/22461 which is fixed https://github.com/cypress-io/cypress/pull/22501. I think both users have ended up finding a way to migrate?

If not, maybe include your `cypress.json`, or check the other issue to see if it's potentially related.

**Comment by amartin1984** [comment]
I'm fine closing this as is.. I'm running into other problems but I think they are different already open issues.

**Comment by Dmitry-Boyko** [comment]
Guys, I will convert my Cypress 9.7.0 to current 12. Have the same pic shown on top here.
Do you have already real steps how to kill this?
`Your C:\workspace\px-opus-convert-to-12\e2e\cypress\plugins\index.js file threw an error.`
Thank you on front
