### ISSUE TITLE
Flaky server "integration" tests should be moved to e2e / system tests

### ISSUE THREAD

**Issue by tgriesser** [cypress-io/cypress#22062]
### Current behavior

There are tests that have a lot of flake: https://app.circleci.com/pipelines/github/cypress-io/cypress/38910/workflows/8e1b04ba-154b-4493-8f4a-2902dc8f2714/jobs/1583306

```
lib/cypress --run-project can change the reporter with cypress.config.js
```

We have better conventions around e2e/system tests

### Desired behavior

When we see flaky tests in the legacy "integration" style, we should port them over to e2e/system tests

### Test code to reproduce

N/A

### Cypress Version

10.0.0

**Comment by flotwig** [comment]
Closing since #23100 covers this
