### ISSUE TITLE
Circle CI build failed

### ISSUE THREAD

**Issue by saadaouad** [cypress-io/cypress#2207]
When I try to running the tests in Continuous Integration using `Circle CI` v2 with `npm`, the build is failed after running `npm ci`:
```
#!/bin/bash -eo pipefail
npm ci
/bin/bash: npm: command not found
Exited with code 127
```

This is my **circleci.yml** config:

```haml
version: 2
jobs:
  build:
    working_directory: /var/www
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/cci-demo-docker-primary:0.0.2
      - image: cypress/base:8
        environment:
          ...
          TERM: xterm
    parallelism: 1
    steps:
      - checkout
      - run:
          ...
      - restore_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v2-deps-{{ .Branch }}-
          key: v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run --record --key <my_record_key>
```

**Comment by bahmutov** [comment]
Remove the first image line - I think you are specifying two docker images and the first one takes precedence (- image: line)

**Comment by saadaouad** [comment]
Thanks, I removed it but I get another error: 
```
#!/bin/bash -eo pipefail
npm ci
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-24T19_12_29_424Z-debug.log
Exited with code 1
```

**Comment by jennifer-shehane** [comment]
@saadaouad You'll need to run `npm i` locally in order to generate and commit the `package-lock.json` file to be read by your CI. The `npm ci` command exclusively uses the `package-lock.json` file.

**Comment by saadaouad** [comment]
`npm i` Can not generate `package-lock.json` file @jennifer-shehane

**Comment by Bkucera** [comment]
@saadaouad npm install creates a package-lock by default. You must have configured npm to not generate one.

**Comment by saadaouad** [comment]
Correct @Bkucera, thanks 👍

**Comment by sshadmand** [comment]
https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.gitlab-ci.yml will create an error in gitlab if copied as is. 

`cipm can only install packages with an existing package-lock.json `

I believe `npm i` needs to be called first, which I found here https://github.com/cypress-io/cypress/issues/2207

**Comment by atz** [comment]
> @saadaouad You'll need to run `npm i` locally in order to generate and commit the `package-lock.json` file to be read by your CI. The `npm ci` command exclusively uses the `package-lock.json` file.

As the error message suggests, it `npm ci` also uses (preferentially) a `npm-shrinkwrap.json` file.

**Comment by anupamhaldkar** [comment]
> > @saadaouad You'll need to run `npm i` locally in order to generate and commit the `package-lock.json` file to be read by your CI. The `npm ci` command exclusively uses the `package-lock.json` file.
> 
> As the error message suggests, it `npm ci` also uses (preferentially) a `npm-shrinkwrap.json` file.

Thanks atz it work for me

**Comment by stephyswe** [comment]
If you wanna use yarn instead?? = /

**Comment by bioan** [comment]
@stephyswe Late reply, but you can replace `npm ci` with `yarn install --frozen-lockfile` . Rest should run just fine with npm commands used in the examples they provide, I believe.
