### ISSUE TITLE
Dynamically setting baseUrl with `TestConfigOverrides`

### ISSUE THREAD

**Issue by PepijnSenders** [cypress-io/cypress#22072]
### Current behavior

In v9 we were able to set the `baseUrl` but it has disappeared from the `TestConfigOverrides` type.

### Desired behavior

Add the `e2e` key to the `TestConfigOverrides` type.

### Test code to reproduce

https://github.com/cypress-io/cypress/blob/e6b2466f7b219a86da46c1ac720432ef75193ca4/cli/types/cypress.d.ts#L3006

### Cypress Version

10.0.2

**Comment by mschile** [comment]
The `baseUrl` option was removed with https://github.com/cypress-io/cypress/pull/20589. However, it is still listed as a [test configuration](https://docs.cypress.io/guides/references/configuration#Test-Configuration) option in the docs. 

Setting the `baseUrl` at the root succeeds:

```js
  it('should visit', { baseUrl: 'http://127.0.0.1:8080' }, () => {
    cy.visit('/')
  })
```

However, setting `baseUrl` within `e2e` fails:

```js
  it('should visit', { e2e: { baseUrl: 'http://127.0.0.1:8080' }}, () => {
    cy.visit('/')
  })
```
<img width="1361" alt="Screen Shot 2022-06-03 at 4 32 40 PM" src="https://user-images.githubusercontent.com/2002044/171962744-a8784d66-6901-4a7d-9f20-cd27bc6b89cd.png">

@estrada9166, do you know if we are intending to support `baseUrl` at the root level or within `e2e` for the per-test configuration?

**Comment by jennifer-shehane** [comment]
We want to support setting `baseUrl` at the root level in the testConfigOverrides, as we always know at this point which testing type we're in.
