### ISSUE TITLE
cypress 10 lost it's run - all - button

### ISSUE THREAD

**Issue by joelgrimberg** [cypress-io/cypress#22078]
### Current behavior

Fresh Cypress 10 install into a fresh npm project (only an npm init)  and opening Cypress with example files made me looking for the disappeared run-all button.
And I still haven't found what I am looking for.	

### Desired behavior

Give me a run-all - button to run all files 'at once' .

### Test code to reproduce

npm init
npm install cypress --save-dev
npx cypress open
..

### Cypress Version

10.0 && 10.0.2

**Comment by lmiller1990** [comment]
Hi! This was removed at part of Cypress 10. If it's really popular, we can definitely consider bringing this feature back.

You can still run all your specs, like this: `yarn cypress run --e2e`. You can show the UI with the `--headed` flag, and if you want it to stay open, you could use `--no-exit`. The full command I like to use it `yarn cypress run --browser chrome --e2e --headed --no-exit`.

Is there a specific reason you'd like a button in the UI, or just for convenience?

**Comment by Kolombiken** [comment]
Just migrated to 10.02 and tried the full command above and it only runs the first test and then it stops. 
Do I need to organize my tests differently? Right now they are structured according to what the migrator recommended e.g. `cypress/e2e/name of-the-test.cy.js`.

**Comment by lmiller1990** [comment]
@Kolombiken that's weird, I just tried it in a fresh project on 10.0.2 and it's working for me. I'll share the output below.

Can you share a repository reproducing the the behaviour (running only first spec)? If that's too much trouble, can you share:

- previous `cypress.json`
- `cypress.config.js` (or `ts`, whatever the migration created)
- contents of `cypress/e2e` 
- anything else that might be useful?

We can take a look and figure out what's going on.

My output:

```
$ yarn cypress run --e2e
yarn run v1.22.18
$ /Users/lachlan/code/dump/cypress-10-numeric/node_modules/.bin/cypress run --e2e
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped

==================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.0.2                                                                         │
  │ Browser:        Electron 100 (headless)                                                        │
  │ Node Version:   v16.14.2 (/Users/lachlan/.nvm/versions/node/v16.14.2/bin/node)                 │
  │ Specs:          2 found (spec.cy.ts, spec2.cy.ts)                                              │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  spec.cy.ts                                                                      (1 of 2)


  spec.cy.ts
    ✓ should visit (106ms)


  1 passing (233ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     spec.cy.ts                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/lachlan/code/dump/cypress-10-numeric/cypress/videos/    (0 seconds)
                          spec.cy.ts.mp4


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  spec2.cy.ts                                                                     (2 of 2)


  ✓ works (111ms)

  1 passing (302ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     spec2.cy.ts                                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/lachlan/code/dump/cypress-10-numeric/cypress/videos/    (0 seconds)
                          spec2.cy.ts.mp4


==================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  spec.cy.ts                               267ms        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  spec2.cy.ts                              289ms        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        556ms        2        2        -        -        -

✨  Done in 19.53s.
```

**Comment by Kolombiken** [comment]
@lmiller1990 Thanks for the feedback! Appreciated! 
Felt a little too much to open an issue if it was just something simple like folder structure or similar. 
Unfortunately I can not share a repository but I'll create an issue with more detailed info and output.

**Comment by jitenev** [comment]
return run all. it helps in debugging more complex scenarios

**Comment by lmiller1990** [comment]
@jitenev can you check the discussion here: https://github.com/cypress-io/cypress/issues/22085#issue-1259678037

You can still do `npx cypress run --e2e --headed` and run all the specs - this is basically what the "run all" button did. The only difference is now you don't have a button. Would this help with debugging the complex scenarios you mentioned?

**Comment by robport** [comment]
The "Run All" button was far superior to the the running this from the command line in the manner suggested.  I was able to open the the runner and just click run all over and over.  It opened a single chrome window and ran everything in there.  Hence, I could see all the resuls and errors.  Now it's just closing the window and opening another window.  That new window is just ignoring where I place it, so it's literally popping up over this chrome window as I type.  It's so annoying I have no option but to downgrade for now.

Please replace the run all button, and make it run all the tests in a single window as it did before.

**Comment by lmiller1990** [comment]
Thanks for the feedback! We will take it on board and see what the best solution is. I'll also include feedback from another thread to keep it all in one place, [ref](https://github.com/cypress-io/cypress/issues/22085#issuecomment-1145908243)

> I would really appreciate if you could keep (or add back) the possibility to be able to go back to an individual test via the UI after all the tests have finished running. That has helped me a lot in the past!
As it is now it doesn't help much even if i get all the tests to run via the command `cypress run --e2e --headed. I would still need to go back and manually inspect. And if everything closes after each spec then that's impossible. I understand the need for cleaning things up but maybe there can be a compromise?

**Comment by jmsherry** [comment]
That was a pretty big change! I just demo'd cypress to a class of web dev students, telling them that it was a favourite library and so easy to use: I then sat there looking foolish for a long time trying to work out where the run all button was! They were not sold...

Can we have the button back please? I can't see a single reason to remove it!

**Comment by lmiller1990** [comment]
@jmsherry thanks for the comment - if it's really problematic, maybe sticking with 9.x until Run All Specs is back is your best option.

Let's collect the feedback in https://github.com/cypress-io/cypress/discussions/21628.
