### ISSUE TITLE
When opening cypress scrolling acts weird

### ISSUE THREAD

**Issue by Dragod** [cypress-io/cypress#22083]
### Current behavior

The scrolling behavior of the tests is acting weird. Scrolling to the bottom it goes back to top, also clicking on the arrow ">" to expand/collapse folder does not work poperly.

### Desired behavior

Scrolling shouldn't take me back to top
Expand/collapse arrow on folder should work

### Test code to reproduce
```
npm init
npm install cypress@10.0.2 --save-dev
npx cypress open
```

### Cypress Version

10.0.2

**Comment by lmiller1990** [comment]
Definitely sounds like a bug. I'm not seeing this in any of my testing (window/linux/macOS).

Can you share what OS/browser you are using? Also, have you tried another browser, just to isolate the issue?

**Comment by Dragod** [comment]
> @Dragod Can you capture/share a video of this behavior? Thanks

https://x.pfcode.net/VujE3/reZuNELU91.gif

**Comment by Dragod** [comment]
> Definitely sounds like a bug. I'm not seeing this in any of my testing (window/linux/macOS).
> 
> Can you share what OS/browser you are using? Also, have you tried another browser, just to isolate the issue?

Didn't try other browser I can try that.

**Comment by lmiller1990** [comment]
Thanks for the reproduction, this is really useful. It looks like the mouse click is double-firing - I wonder if the click *and* the accessibility features (navigate w/o mouse) are somehow both triggering. Hopefully this idea will help as we debug it.

As for the scrolling issue, I don't have any immediate suspicions. We will investigate!

**Comment by Dragod** [comment]
Another reproduction of scrolling going back to top: https://x.pfcode.net/VujE3/jUSOFEKe91.mp4
