### ISSUE TITLE
Unable to run all the tests with --headed and --no-exit flag

### ISSUE THREAD

**Issue by Kolombiken** [cypress-io/cypress#22085]
### Current behavior

Just migrated to Cypress 10.02 and followed the suggested migration recommendations.
When running all my tests with the command `cypress run --e2e --headed --no-exit` only the first test runs. When running headless with `cypress run --e2e` all the tests runs. 

I have tried different combos with specifying a browser adding/removing `--no-exit` flag but it doesn't make any difference. Only one test runs. 

I did notice that I get a message regarding `WebSwapCGLLayer` but not sure it's related. Providing it in the output below.

### Desired behavior

I would like to be able to run all my tests while being able to inspect the ui. Previously there was a "run all" button. But since it's removed there needs to be another way of running all the tests headful. 

### Test code to reproduce

Inside the folder `cypress/e2e` there are four test-files all following the convention `name-of-test.cy.js`. 

### Previous `cypress.json`

`{ "chromeWebSecurity": false }`

### Current `cypress.config.js`

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  chromeWebSecurity: false,
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config)
    },
  },
})
```

### Output from the terminal 

When running `cypress run --e2e --headed --no-exit`:

````
> cypress run --e2e --headed --no-exit

objc[8029]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffa55f21318) and /Users/me/Library/Caches/Cypress/10.0.2/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10ef7c9c8). One of the two will be used. Which one is undefined.
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.0.2                                                                         │
  │ Browser:        Electron 100                                                                   │
  │ Node Version:   v16.15.0 (/Users/me/.nvm/versions/node/v16.15.0/bin/node)                     │
  │ Specs:          4 found (first-test.cy.js, second-test.cy.js, third-test.cy.js, four           │
  │                 th-test.cy.js)                                                                 │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  first-test.cy.js                                                               (1 of 4)


  View things in first test
    ✓ can run first test (23334ms)


  1 passing (25s)

not exiting due to options.exit being false
````

### Cypress Version

10.0.2

**Comment by Kolombiken** [comment]
Ok, cool!
Thank you for looking into this so quickly!

I have cloned the repo and I've been running `cypress run --e2e --headed`. 
And to get the details clear. I don't use yarn and I don't have cypress installed globally so I added a script in the package.json to run the command (have a similar setup in my other project). E.g. `"scripts": { "all": "cypress run --e2e --headed" }`.

All the tests do run here. Good! 👍 
But if I add a `--no-exit` flag only the first test runs. Just like you explained.
I guess I need to pick my own tests apart and diff the setup here with the setup in this repo to try and figure out what the issue is then. I'll do that later. And if I find anything useful I'll let you know!

I would really appreciate if you could keep (or add back) the possibility to be able to go back to an individual test via the UI after all the tests have finished running. That has helped me a lot in the past!
As it is now it doesn't help much even if i get all the tests to run via the command `cypress run --e2e --headed. I would still need to go back and manually inspect. And if everything closes after each spec then that's impossible. I understand the need for cleaning things up but maybe there can be a compromise?

**Comment by lmiller1990** [comment]
Ok, great. Just to clarify:

1. My repo with `yarn cypress run --e2e --headed` works the same for both of us. This is good 👍 
2. `--no-exit` does what it's supposed to do - not exit. It's different to Cypress 9.x, and not really what you'd expect, though. We should fix the DX around this.
3. Run all button was useful, so you can see which spec(s) fail then immediately start fixing them.

Thanks a lot, your feedback is really useful and we will discuss internally and find the best solution 👍

**Comment by Kolombiken** [comment]
**"Unable to run all the tests with --headed and --no-exit flag"** is a better description. 👍 

I've managed to run all of my tests with the only the `--headed` flag now. It's very slow and sometimes it takes a minute before a new browser sessions starts. I suspect that might be the issue. Maybe I didn't give it enough time when i tried it last time and just assumed that it has stopped while trying out different flags.

**Comment by jennifer-shehane** [comment]
>It's different to Cypress 9.x, and not really what you'd expect, though. We should fix the DX around this.

I'm running 9.x and 10.0 side by side with `--no-exit` and I'm not understanding what the difference is. There should be no difference in how this flag works. When I run it, it runs the first specfile and runs all of the tests within that one spec file. @Kolombiken Is this not the behavior you're seeing?

We'll need a repo to reproduce this if you are saying only the first test of the first spec file is executing with the --no-exit flag. Because that would be a bug.

**Comment by mjhenkes** [comment]
Please leave feedback on the removal of the run all feature over here on the discussion: https://github.com/cypress-io/cypress/discussions/21628

**Comment by DeveloperTheExplorer** [comment]
@Kolombiken did you find a solution to this problem? I'm still having to manually run the tests one by one because of the exit flag stopping after the first test file.

**Comment by DeveloperTheExplorer** [comment]
Also @mjhenkes the discussion you posted is not entirely relevant. This seems to be more of a bug rather than a post-update feature (or rather post-update removal of a useful feature). If I am in headed mode with the no-exit flag **AND** the cypress tests terminal indicates that it has found all the relevant test files and yet it only runs the first test file and nothing else, then this is a bug and an open issue.

Why is this being marked as `completed` when this is still relevant today?

**Comment by infiniteCreations-Studio** [comment]
I am currently experiencing this issue as of 9-17-2024 when running from a docker container.
