### ISSUE TITLE
The record key is obstructed in v10

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#22091]
### Current behavior

Setting up the Dashboard recording using v10.0.2 and cannot select just the key, need to select the entire command using the button and then trim it to use just the key 

![Screen Shot 2022-06-03 at 09 26 44](https://user-images.githubusercontent.com/2212006/171863714-c7e37505-b655-44fc-9645-ca8732e6951f.png)

### Desired behavior

Be able to select just the record key

### Test code to reproduce

add Dashboard to any project

### Cypress Version

10.0.2

**Comment by jennifer-shehane** [comment]
We should just make this an input so that the area is scrollable and you can copy any portion of the command you want.
