### ISSUE TITLE
Remove autocomplete from inputs in Cypress UI

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#22102]
### Current behavior

There are a few inputs inside the Cypress App with some not-so-great looking autocompletes. They look like tootlips and aren't aligned properly.

![Screen Shot 2022-06-03 at 3 55 45 PM](https://user-images.githubusercontent.com/25158820/171952204-1795a2d9-8d60-4a72-b509-cd9e643eaab7.png)
![Screen Shot 2022-06-03 at 3 59 07 PM](https://user-images.githubusercontent.com/25158820/171952206-e6c7536d-ba9d-4d5c-a518-04dbca26cb88.png)

### Desired behavior

We should disable autocomplete for our inputs.

### Test code to reproduce

Open up Cypress App and type in the spec search filter. Click on a spec and navigate back, the autocomplete should show in the spec search input.

### Cypress Version

10.0.2

**Comment by estefafdez** [comment]
+1 to this issue, sometimes you can't type properly the name of the specs because of that.

**Comment by marktnoonan** [comment]
@viniciuspietscher if you want to grab another small issue, this one requires adding the attribute `autocomplete="off"` to the `input` elements in the following files:

- packages/app/src/components/FileMatchInput.vue
- packages/app/src/runner/selector-playground/SelectorPlayground.vue
- packages/frontend-shared/src/components/Input.vue

And updating the component tests for each one to validate that the attribute is present.
