### ISSUE TITLE
> Unexpected token '<' error w/ cypress component testing

### ISSUE THREAD

**Issue by nadvolod** [cypress-io/cypress#22108]
### Current behavior

I'm trying to follow the [component testing docs](https://docs.cypress.io/guides/component-testing/testing-react#Selecting-the-Stepper-Component) to get started but facing the error below. This is [the code](https://github.com/nadvolod/js-code/tree/cypress_10/cy-10) .
```
The following error originated from your test code, not from Cypress.
  > Unexpected token '<'
```
```
at Object.runScripts (http://localhost:3001/__cypress/runner/cypress_runner.js:179586:63)
at $Cypress.onSpecWindow (http://localhost:3001/__cypress/runner/cypress_runner.js:167795:77)
at <unknown> (http://localhost:3001/__cypress/iframes//Users/nikolay/source/js/js-code/cy-10/cypress/component/Stepper.cy.js:59:18)
```

### Desired behavior

I believe that the component should mount just fine without issues.

### Test code to reproduce

https://github.com/nadvolod/js-code/tree/cypress_10/cy-10

### Cypress Version

10.0.2

### Other

Cy component testing
```
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^1.3.0",
    "cypress": "^10.0.2",
    "vite": "^2.9.9"
  }
```

**Comment by mschile** [comment]
@nadvolod, thanks for logging this issue. I checked out your code and since `jsx` is used within the test file, it should be named `Stepper.cy.jsx` not `Stepper.cy.js`. After making this change, the tests should pass.

**Comment by nadvolod** [comment]
@mschile beautiful! Thank you
