### ISSUE TITLE
Running Cypress unit tests erase e2e code coverage reports

### ISSUE THREAD

**Issue by SouroucheB** [cypress-io/cypress#22104]
### Current behavior

First, I generate Cypress e2e code coverage html by running `yarn cypress open` with the following configurations :

`cypress.config.ts` :
```
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:3000",
    setupNodeEvents(on, config) {
      require("@cypress/code-coverage/task")(on, config);

      return config;
    },
  },

  component: {
    setupNodeEvents(on, config) {
      require("@cypress/code-coverage/task")(on, config);

      return config;
    },
    devServer: {
      framework: "create-react-app",
      bundler: "webpack",
    },
  },
});
```

Until this point, everything works perfectly. I have the `.nyc_output/out.json` filled with data and a `coverage/lcov-report/index.html` perfectly filled as well.

BUT. When I use cypress to open the component testing window, regardless the test goes well and successfully ended, the `.nyc_output/out.json` and the `coverage/lcov-report/index.html`are emptied with the cypress log that is no code instrumentation setted up (but I did everything written here : https://github.com/cypress-io/code-coverage#instrument-unit-tests).

### Desired behavior

As it is mentionned in the doc, the both reports should be merged with this little configuration and not erased when cypress unit tests are launched.

### Test code to reproduce

Here is my failing test code and the app code to run the tests on https://github.com/SouroucheB/cypress-reproduce-error

### Cypress Version

10.0.2

**Comment by bobmccracken** [comment]
> This isn't documented well right now, so my apologies, but what you need to do is [import '@cypress/instrument-cra' at the top of your Cypress config file](https://github.com/elylucas/cypress-cra-code-coverage-example/blob/main/cypress.config.ts#L2), and that will take care of instrumenting your code for component tests.

Oh my dear lord here it is, the documentation I have been looking for. What a relief. I hope my hair grows back.

This desperately needs documentation somewhere.

**Comment by SouroucheB** [comment]
@bobmccracken I have to tell you something. It won't be easy but you should know that we both know the same issue.







Hair growing doesn't work that way.

**Comment by bjankord** [comment]
> When you run Cypress in run mode (cypress run --e2e or cypress run --component), the code coverage reports get appended instead of emptied. Running Cypress in run mode for both e2e and CT will allow you to get a comprehensive report from all your Cypress tests.

I had suspected that was the case from my testing, nice to hear that from someone working on cypress to confirm that is how component + e2e code coverage is meant to work.
