### ISSUE TITLE
Unable to login to the application, using Authorization services

### ISSUE THREAD

**Issue by charnism** [cypress-io/cypress#22115]
### Current behavior

Microsoft Azure portal. We are using Authorization services ( select the headers tab-> right click and copy the authorization header)to login into the application.
Having a huge issue login in using Cypress. 

```js
describe('authorizaton)', function(){
  it('authorizaton' , function() {
    const sentArgs = {authorization:'copy and paste' }  
    cy.origin('sardmts-sgsdep.test.ec.gc.ca',{ args: {sentArgs }}, ({authorization})=> {
    cy.visit('https://sardmts-sgsdep.test.ec.gc.ca/en/')
    })
  })   
});
```

And I'm receiving a popup screen Sign in (don't appear if you log in manually), type email address, press next - > This page isn't working.
Contacted the Microsoft support center, and I've been told that this is an issue with Cypress

### Desired behavior

Cypress should log in to the application front page 

### Test code to reproduce

```js
describe('authorizaton)', function(){
  it('authorizaton' , function() {
    const sentArgs = {authorization:'copy and paste' }  
    cy.origin('sardmts-sgsdep.test.ec.gc.ca',{ args: {sentArgs }}, ({authorization})=> {
    cy.visit('https://sardmts-sgsdep.test.ec.gc.ca/en/')
    })
  })   
});
```

### Cypress Version

v10.0.2

**Comment by mschile** [comment]
@charnism, thanks for logging this issue. Unfortunately, Microsoft login doesn't currently work due to frame busting. We have https://github.com/cypress-io/cypress/issues/21476 logged to investigate and address this issue.

I'm going to close this issue as a duplicate but please follow along on https://github.com/cypress-io/cypress/issues/21476 for any further updates.

**Comment by charnism** [comment]
Hi Matt,

Wanted to follow up with status in regards of #21476.

Currently the government looking forward and started as we speak to move many application to cloud. Being a strong advocate to introduce cypress among different testing teams, I hope that Authorization services issue will be resolved soon.

Thank you,

Mark

Division du support et livraison des produits ministériel et entreprise, Rapport internes et Entrepôt de données
Environnement et Changement climatique Canada, Gouvernement du Canada
***@***.******@***.***> / Tél. : 647-294-1459

Corporate and Enterprise Products and Services, EC Reporting and Data Warehouse
Environment and Climate Change Canada, Government of Canada
***@***.******@***.***> / Tel. : 647-294-1459

**Comment by mschile** [comment]
Hi @charnism, we are actively working on Microsoft login though I don't have an exact timeline of when it will be completed.

**Comment by charnism** [comment]
Hi Matt,
Do you have any updates n regards to /21476

Best,
Mark
