### ISSUE TITLE
Using cypress for application demonstration

### ISSUE THREAD

**Issue by torabian** [cypress-io/cypress#2212]
### Desired behavior:

I want to be able to use cypress for demonstration of app. For example, when I am going to a customer, I want run cypress, to go thorough all stories that I do have in the application.

At the moment it's possible, by reducing the speed of input.type(), or adding some delays, to make a video like. But I want to be able to make it as a slideshow, go to next story, or move back, maybe with a external controller even.

Please give me feedback how is this possible.

**Comment by bahmutov** [comment]
So this is very different from the regular use of the tool, so we don't have anything in mind right now. Except I did a small experiment where we generate videos clipped to the app and single test. With included toast library, one can "explain" what is going in the application. 

I suggest you follow this repo https://github.com/bahmutov/cypress-movie for any work, I will keep updating it with more work. Also follow https://www.cypress.io/blog/ where we will write a blog post once we get something useful going.

Thanks for a good suggestion @torabian, appreciate this!
