### ISSUE TITLE
Error occurs when referencing the upper hierarchy with specPattern

### ISSUE THREAD

**Issue by KiriRea** [cypress-io/cypress#22122]
### Current behavior

I execute test specs in the hierarchy above the folder specified by "--project".
By updating Cypress v10, integrationFolder option was removed and replaced with specPattern option.
When I replace integrationFolder option with specPattern option and execute test specs, below error is happened.

```console
Error: EINVAL: invalid argument, mkdir 'C:\Users\<user>\AppData\Roaming\Cypress\cy\production\projects\project-ebb3941567b10beb6f33096d39c6ad57\bundles\D:\ProgramData\workspace\sample\test'
```
![error-message](https://user-images.githubusercontent.com/106964165/172148677-45457e78-effa-4b4b-bc9f-772f4d552a38.png)

My project strucutre is separated with settings folder and test spcec folder.
So, I execute cypress with "--project" option.

* My project structure
```
<Project>
  ├─Path
  │  └─to
  │     └─project
  │         ├─fixtures
  │         ├─support
  │         └─cypress.config.js
  └─test
      └─spec.cy.js
```

* Execute command
``` console
npx cypress open --project .\path\to\project
```

* cypress.config.js
``` javascript
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    specPattern: "../../../test/*.cy.js"
  }
});
```

Cypress 9.x with integrationFolder don't happen this problem.

### Desired behavior

Cypress can execute test specs in the hierarchy above the folder specified by "--project"

### Test code to reproduce

* cypress.config.js

``` javascript
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    specPattern: "../../../test/*.cy.js"
  }
});
```

### Cypress Version

10.0.2 (happens 10.0.0 and above)

### Other

No response

**Comment by AtofStryker** [comment]
possibly related to #8599

**Comment by flotwig** [comment]
Definitely a regression in v10. However, I'd like to point out that this isn't "best practice" to set up your Cypress tests like this. You can use a central package to manage the `cypress` version and use `--project` to point to a `cypress.config.js` per package.

**Comment by yezhi780625** [comment]
I have the same problem, too. I exec the repo @AtofStryker provided on `windows 10 20H2`, and got the same error.
```cmd
Error: EINVAL: invalid argument, mkdir 'C:\Users\yezhi\AppData\Roaming\Cypress\cy\production\projects\project-b3e142614714d369e30e37c63b793cc4\bundles\D:\Practices\cypress-22122-reproduction\test'
```
The  `mkdir` path seems be an invalid path on windows
```cmd
mkdir 'C:\Users\yezhi\AppData\Roaming\Cypress\cy\production\projects\project-b3e142614714d369e30e37c63b793cc4\bundles\D:\Practices\cypress-22122-reproduction\test'
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by Sjeiti** [comment]
> use a central package to manage

@flotwig Does this mean [the Nx implementation](https://github.com/nrwl/nx/blob/master/packages/cypress/src/generators/cypress-project/files/v10-and-after/cypress.config.ts__tmpl__) of Cypress is not best practice? Were you referring to globs outside the cypress.config-directory or the use of a central package?
