### ISSUE TITLE
mocha-junit-reporter option doesn't work

### ISSUE THREAD

**Issue by Karolis92** [cypress-io/cypress#2214]
### Current behavior:

mocha-junit-reporter always sets `name="<fullTitle>"` and `classname="<title>"` regardless of `testCaseSwitchClassnameAndName` option value.

Option is described here: https://github.com/michaelleeallen/mocha-junit-reporter
Here is mocha-junit-reporter code: https://github.com/michaelleeallen/mocha-junit-reporter/blob/c55dc223886ec2cd050d5011e6e61c52d75d4371/index.js#L190

### Desired behavior:

should switch `name` and `classname` when `testCaseSwitchClassnameAndName`  is `true`

### Steps to reproduce:

cypress.json:
```json
{
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "results/[hash].xml",
    "testCaseSwitchClassnameAndName": true
  }
}
```

### Versions

Cypress:    3.0.2
Browser:    Electron 59 (headless)

**Comment by jennifer-shehane** [comment]
@Karolis92 Why is it that you have `reporter` option set to `junit` and not set to `mocha-junit-reporter`?

**Comment by Karolis92** [comment]
@jennifer-shehane , as you can see form snippet for `cypress.json` I provided, it is `junit`.

**Comment by Karolis92** [comment]
@jennifer-shehane because that what Cypress documentation states: https://docs.cypress.io/guides/tooling/reporters.html#Reporter-Options

**Comment by Karolis92** [comment]
Found a problem, Cypress uses `v1.13.0`, but this option was added only in `v1.14.0`....
Will have to add `mocha` and `mocha-junit-reporter` as project dependencies for now.

So this version update should be qualified as feature request? Maybe reporters should not be bundled if you don't update them? It's probably nothing wrong for each project to include what it only needs :)

**Comment by brian-mann** [comment]
We will update the reporter, but just so you know you can **always** use your own reporters.

https://docs.cypress.io/guides/tooling/reporters.html#

**Comment by jennifer-shehane** [comment]
This update went out in Cypress 3.0.3, could you confirm this is fixed in that issue?

**Comment by jennifer-shehane** [comment]
@Karolis92 Any update? We will close this issue if you do not respond.

**Comment by Karolis92** [comment]
Sorry, not working with that project anymore :) But like I said, we have put reporter dependencies to our project to be independent from cypress updates :)

**Comment by carlosfvp** [comment]
@brian-mann I am installing the last version of mocha-junit-repoter but it's ignored and cypress still uses the one on it's folder.

Is possible for the cypress team to remove this dependency? I truly need the "attachment" feature wich is on the last version of mocha-junit-repoter.

**Comment by jennifer-shehane** [comment]
Can you run the `cypress` command with the [DEBUG logs enabled](https://on.cypress.io/debugging#Print-DEBUG-logs) and print them here so we can see which reporter is it finding.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
