### ISSUE TITLE
nohoist config is ignored

### ISSUE THREAD

**Issue by br-kwon** [cypress-io/cypress#22147]
### Current behavior

when installing the cypress package via yarn, i get a warning saying the nohoist config is ignored

### Debug logs

warning nohoist config is ignored in "cypress" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.

### Cypress Version

10.0.3

### Package Manager

yarn

### Operating system

Mac

**Comment by willoliveira-air** [comment]
Seeing the same issue when installing Cypress

```
warning nohoist config is ignored in "cypress" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
warning nohoist config is ignored in "cypress" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
```

**Comment by mmaous** [comment]
Facing the same issue, On a Linux (ubuntu 20.04) machine, I have tried using npm instead and there is no issue, 

So the takeaway is the problem is with yarn not cypress ( I guess) :D 

btw, i'm using yarn 1.22.18

**Comment by mutoe** [comment]
Same issue here.

yarn: '1.22.18'
node: 14.9.3
macOS 12.3.1 (M1 Pro arm64)

**Comment by KatieMFritz** [comment]
Same. Yarn 1.22.17, Node 16.0.0

**Comment by parazitl2** [comment]
The same, yarn 1.22.19, node 16.14.2

**Comment by marktnoonan** [comment]
Thanks for for logging this. I've confirmed it locally as well, let's see what we can do to clean up this warning.
