### ISSUE TITLE
modifyObstructiveCode getting error in cypress v10 for cypress.config.ts

### ISSUE THREAD

**Issue by jenishgandhi7** [cypress-io/cypress#22146]
### Current behavior

modifyObstructiveCode getting error in cypress v10 for cypress.config.ts

### Test code to reproduce

![image](https://user-images.githubusercontent.com/8191015/172228652-8ce80a02-2870-46f8-bb74-268455fcb50f.png)

### Cypress Version

10.0.2

**Comment by lmiller1990** [comment]
Thanks for the report. Now we've got strongly typed config via `cypress.config.ts`, we are starting to see some of our types are not perfect.

**Comment by AtofStryker** [comment]
Hey @jenishgandhi7. It looks like the type is indeed missing from [cypress.d.ts](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L2816) and is a bug. The type likely needs to be added to `ResolvedConfigOptions`, but omitted from `ComponentConfigOptions` and `UserConfigOptions`. 

Once fixed, the `modifyObstructiveCode` option should only be available under `e2e` in the config. 

I think this value has always been missing in our types, but I think it is now noticeable now that we have `cypress.config.ts` as an option.

**Comment by mihaela-ioica** [comment]
I get this error too for modifyObstructiveCode: false in the cypress.config.ts file on Cypress version 10.6.0
