### ISSUE TITLE
Test runner become heavier and slowing down my device after installing Cypress V10

### ISSUE THREAD

**Issue by jaypoptin** [cypress-io/cypress#22160]
### Current behavior

Test runner become heavier and slowing down my device after installing Cypress V10

### Desired behavior

Should be light.

### Test code to reproduce

Open test runner using npx cypress open command. I am on a windows machine.

### Cypress Version

10

**Comment by rachelruderman** [comment]
Hi @jaypoptin! Thanks for reporting this issue. Can you provide us with your [DEBUG logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs)?

**Comment by rachelruderman** [comment]
By the way @jaypoptin, we were wondering what you mean by "heavier" in the title? Did you mean the same as "slowing down" or is it something else? Thx!

**Comment by jaypoptin** [comment]
Hi Rachel

I meant the same "slowing down" but it got fixed after I updated Cypress to
10.0.3 Version.
[image: logo] <https://www.poptin.com/>

Jayasankar K S
QA Manager
***@***.*** ***@***.***>
https://www.poptin.com
<https://www.facebook.com/www.popt.in/>
<https://www.linkedin.com/company/poptin/mycompany/>
<https://twitter.com/poptins>
<https://www.youtube.com/channel/UCSuxbVLRL5OqSo747GXKxrg?view_as=subscriber>
