### ISSUE TITLE
Cypress crashes when attempting to open after Update to 10.0.0 Release

### ISSUE THREAD

**Issue by glamanna-motional** [cypress-io/cypress#22164]
### Current behavior

In attempting to open cypress for the first time after update, it crashes.  While I am currently on 10.0.3, this issue has been persistent across the past three point releases.  This behavior **was not** seen on 9.7.

`It looks like this is your first time using Cypress: 10.0.3

✔  Verified Cypress! /home/gabriel.lamanna/.cache/Cypress/10.0.3/Cypress

Opening Cypress...
[556597:0607/103034.680436:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[556753:0607/103034.697579:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[556597:0607/103036.561349:INFO:CONSOLE(5960)] "Allow attribute will take precedence over 'allowfullscreen'.", source: http://localhost:41743/__launchpad/assets/index.d6342df5.js (5960)
[556597:0607/103036.618879:ERROR:nss_util.cc(169)] Error initializing NSS with a persistent database (sql:/home/gabriel.lamanna/.pki/nssdb): libsoftokn3.so: cannot open shared object file: No such file or directory
[556597:0607/103036.618933:ERROR:nss_util.cc(127)] Error initializing NSS without a persistent database: NSS error code: -5925
[556597:0607/103036.618944:FATAL:nss_util.cc(129)] nss_error=-5925, os_error=0
The Test Runner unexpectedly exited via a exit event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 10.0.3`

### Desired behavior

To be able to open cypress test runner and guide through setting up my configs for 10.

### Test code to reproduce

npx cypress open

### Cypress Version

10.0.3

**Comment by marktnoonan** [comment]
Hi @glamanna-motional, I've been attempting to reproduce this without success, using a slightly different version of Linux though.

This part of the log seems to be where the trouble is:

```
[556597:0607/103036.618879:ERROR:nss_util.cc(169)] Error initializing NSS with a persistent database (sql:/home/gabriel.lamanna/.pki/nssdb): libsoftokn3.so: cannot open shared object file: No such file or directory
[556597:0607/103036.618933:ERROR:nss_util.cc(127)] Error initializing NSS without a persistent database: NSS error code: -5925
[556597:0607/103036.618944:FATAL:nss_util.cc(129)] nss_error=-5925, os_error=0
The Test Runner unexpectedly exited via a exit event with signal SIGILL
```

does `home/gabriel.lamanna/.pki/nssdb` exist?

Also Cypress 10.1.0 has been released if you would like to try that and see if the same issue occurs?

**Comment by glamanna-motional** [comment]
Thanks for the response @marktnoonan, I took a deep dive with other eng's and looks like this was local to my machine.  Set LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/nss:$LD_LIBRARY_PATH in my .bashrc and now works as intended.  Hope this helps others!

**Comment by ogomez-at-wiris** [comment]
crashes on Windows as well! from 9.6 to 10.1.0. 

error Command failed with exit code 2147483651.

The Cypress browser pops up fir one second then disappears.

**Comment by glamanna-motional** [comment]
Might be related to your browser @ogomez-at-wiris, is there a longer stack trace?

**Comment by ogomez-at-wiris** [comment]
[trace.txt](https://github.com/cypress-io/cypress/files/8938105/trace.txt)
Here it is. Couldn't figure out much from it though. Sorry for taking so long.

**Comment by ogomez-at-wiris** [comment]
I also tried deleting cypress from appdata/roaming and appdata/local and nothing

**Comment by ogomez-at-wiris** [comment]
This might provide more info?
  cypress:data-context:sources:VersionsDataSource NPM release dates
received { modified: '2022-06-14T07:12:40.628Z' } +0ms
Received fatal exception EXCEPTION_BREAKPOINT
Backtrace:
        IsSandboxedProcess [0x00007FF7A2977947+1943559]
        IsSandboxedProcess [0x00007FF7A297752D+1942509]
        IsSandboxedProcess [0x00007FF7A2972A56+1923350]
        std::__1::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame>
>::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame>
> [0x00007FF7A1228453+47875]
        v8_inspector::V8StackTraceId::V8StackTraceId
[0x00007FF7A5A76649+2641593]
        v8_inspector::V8InspectorClient::currentTimeMS
[0x00007FF7A53EBEC1+1418193]
        v8_inspector::V8DebuggerId::operator= [0x00007FF7A1AC4C06+431462]
        v8_inspector::V8InspectorClient::currentTimeMS
[0x00007FF7A540A172+1541762]
        uv_timer_get_repeat [0x00007FF7A236A894+3139924]
        v8_inspector::V8StackTraceId::V8StackTraceId
[0x00007FF7A5CD7FA4+5138452]
        IsSandboxedProcess [0x00007FF7A2A06ADC+2529692]
        node::GetEnvironmentIsolateData [0x00007FF7A1FBE662+575906]
        node::GetEnvironmentIsolateData [0x00007FF7A1FBEA15+576853]
        uv_timer_get_repeat [0x00007FF7A22482AB+1950571]
        node::GetEnvironmentIsolateData [0x00007FF7A1FC25D3+592147]
        uv_sleep [0x00007FF7A2CAB279+126249]
        Cr_z_crc32 [0x00007FF7A4869860+626000]
        cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow
[0x00007FF7A47A11E8+3187976]
        Cr_z_crc32 [0x00007FF7A486A492+629122]
        cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow
[0x00007FF7A47AF495+3246005]
        uv_timer_get_repeat [0x00007FF7A2708D1D+6933981]
        uv_sleep [0x00007FF7A2CACBEA+132762]
        uv_timer_get_repeat [0x00007FF7A26E2C45+6778117]
        node::GetEnvironmentIsolateData [0x00007FF7A2011A12+916818]
        node::GetEnvironmentIsolateData [0x00007FF7A2013471+923569]
        node::GetEnvironmentIsolateData [0x00007FF7A200ED52+905362]
        v8::metrics::LongTaskStats::LongTaskStats [0x00007FF7A1487BAE+495230]
        v8::metrics::LongTaskStats::LongTaskStats [0x00007FF7A1488F72+500290]
        v8::metrics::LongTaskStats::LongTaskStats [0x00007FF7A14889D2+498850]
        v8::metrics::LongTaskStats::LongTaskStats [0x00007FF7A1484F3C+483852]
        v8::metrics::LongTaskStats::LongTaskStats [0x00007FF7A14852B0+484736]
        std::__1::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame>
>::__vector_base<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame>
> [0x00007FF7A1227F1D+46541]
        Cr_z_crc32 [0x00007FF7A4BBD8A2+4115858]
        BaseThreadInitThunk [0x00007FFC6B267034+20]
        RtlUserThreadStart [0x00007FFC6CB42651+33]
  cypress:cli child event fired { event: 'exit', code: 2147483651,
signal: null } +4s
  cypress:cli child event fired { event: 'close', code: 2147483651,
signal: null } +2ms

C:\Users\Oriol\work\cy>

On 17/06/2022, glamanna-motional ***@***.***> wrote:
> Might be related to your browser @ogomez-at-wiris, is there a longer stack
> trace?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/cypress-io/cypress/issues/22164#issuecomment-1158865237
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
Oriol Gómez
Software developer Math Type

***@***.***

-- 
www.wiris.com <https://wiris.com/> 
<https://www.facebook.com/wiris.science/>* 
<https://www.linkedin.com/company/maths-for-more/>** 
<https://twitter.com/wiris_science>** 
<https://www.facebook.com/WIRIS-145744615441413/>** 
<https://www.instagram.com/mathtype_by_wiris/>* 
<https://www.youtube.com/user/wirismath>




MathType Add-In for Microsoft 
365 is now available. Install it now *here 
<https://appsource.microsoft.com/en-us/product/office/WA104381909?tab=Overview>*
