### ISSUE TITLE
spec file last updated "52 years ago"

### ISSUE THREAD

**Issue by oliworx** [cypress-io/cypress#22188]
### Current behavior

Just upgraded to Cypress 10, now it says the spec files are 52 years old:

![image](https://user-images.githubusercontent.com/1712684/172622741-2682d6cf-914f-4523-b50f-828df195ea1e.png)

### Desired behavior

show the correct DateTime and not _x years/month or weeks ago_, this information is useless and my brain has to do the calculation to get the date

### Test code to reproduce

....

### Cypress Version

10.0.3

### Other

running on linux mint 20.3

**Comment by dmbartle** [comment]
Just sharing for info: 

52 years lines up with unix (epoch) time=0 (1 January 1970)

I'm not able to reproduce this issue on my machine which is running Windows

**Comment by oliworx** [comment]
sure, it is the same output for all 4 files: `Wed Jun 8 15:12:17 2022 +0200`

but I want to mention that this is the date of a commit and not the file modification date.

` git log` output is:
```
commit 0c56efb37117070990be364ba5d829bbdadfa9ac
Author: Oliver Kurmis <oliver@kurmis.com>
Date:   Wed Jun 8 15:12:17 2022 +0200

    Upgrade Cypress to v10.0.3

```
while `ls -l` shows this:
```
-rw-rw-r-- 1 oli oli 1842 Jun  3 11:55 10_team_register.spec.js
-rw-rw-r-- 1 oli oli 1905 Sep  9  2021 client_login.spec.js
-rw-rw-r-- 1 oli oli 5345 Jan  4 16:23 frontend_test.spec.js
-rw-rw-r-- 1 oli oli 3061 Jun  3 11:53 team_login.spec.js
```

in the commit these files were moved from the `integration` folder to the new `e2e` folder, but the files did noch change

**Comment by rachelruderman** [comment]
Yay I reproduced! 

On line 278 of [data-context/src/sources/GitDataSource](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/sources/GitDataSource.ts#L278), when the value of `stat.birthtime` is `0`, we get 52 years ago 🎉 

`const birthtime = dayjs(stat.birthtime)`

**Comment by mjhenkes** [comment]
I couldn't help myself any more.
![](https://media.giphy.com/media/7xZAu81T70Uuc/giphy.gif)
