### ISSUE TITLE
Downloading v3.8.3 actually downloads 7.1.10

### ISSUE THREAD

**Issue by rnegrin90** [cypress-io/cypress#22187]
### Current behavior

When getting version 3.8.3 from https://download.cypress.io/desktop/3.8.3?platform=linux&arch=x64 the version file reports v7.1.10 and the checksum does not match

### Test code to reproduce

- Download 3.8.3
- check `version` file

### Cypress Version

3.8.3

**Comment by rnegrin90** [comment]
Hi @marktnoonan, thanks for looking into this. that version of cypress is a dependency for `vue/cli-plugin-e2e-cypress`. We are running a fairly old version and on the process of upgrading to vue3, but it will take some time!

**Comment by marktnoonan** [comment]
Looking a little further, in that download I can see that the package.json specifies the requested version correctly, and only the `version` file appears to be different. What's the impact of the mismatched version file? Does it mean you can't set up Cypress on a Vue 2 project at the moment?

**Comment by marktnoonan** [comment]
After double checking, the  `version` file is the version of electron used by that build, and not the version of Cypress being downloaded, `7.1.10` is the expected version of electron in Cypress 3.8.3.
