### ISSUE TITLE
Cypress@10.0.3 migration helper stalls

### ISSUE THREAD

**Issue by anselmbradford** [cypress-io/cypress#22193]
### Current behavior

I run `yarn cypress open` on Cypress 10.0.3 for the first time and it hangs on this screen:

<img width="677" alt="Screen Shot 2022-06-08 at 11 14 57 AM" src="https://user-images.githubusercontent.com/704760/172653297-2c88bc7c-b331-498d-8744-dd0e9a6de9fe.png">

No error messages in the Terminal.

### Desired behavior

Migration assistant should not hang.

### Test code to reproduce

You can test in https://github.com/cfpb/consumerfinance.gov. Run:

From the repo root, run `yarn add cypress -D` and then `yarn cypress open`

### Cypress Version

10.0.3

**Comment by rachelruderman** [comment]
@anselmbradford thank you for reporting this issue! I can confirm it does hang. I let it hang for 5 minutes and observed these DEBUG logs:

<img width="1723" alt="Screen Shot 2022-06-09 at 2 37 27 PM" src="https://user-images.githubusercontent.com/26726429/172920193-117c3f4d-b95e-4318-b30c-2ba0582fd6c4.png">

**Comment by anselmbradford** [comment]
No longer an in Cypress 10.0.4 https://github.com/cfpb/consumerfinance.gov/pull/7188
