### ISSUE TITLE
Cypress 10.0.3 tries to load project-named file at root dir

### ISSUE THREAD

**Issue by yktoo** [cypress-io/cypress#22198]
### Current behavior

After a migration from 9.x to 10.0.3, `cypress open` reports a weird syntax error. After some investigation I concluded that it tries to parse and load a file that has the same name as the project - `once` - which happens to be a **compiled binary** (so no wonder it fails), hence the `ELF` line below.

If I delete that file, Cypress goes further, but that prevents me from running my backend, so it's not an option for me.

Error message:
```
/home/dk/code/GitLab/yktoo-solutions/once/once:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object. (/home/dk/code/GitLab/yktoo-solutions/once/node_modules/pump/index.js:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object. (/home/dk/code/GitLab/yktoo-solutions/once/node_modules/get-stream/index.js:3:14)
```

### Test code to reproduce

Here's my config:
```typescript
import { defineConfig } from 'cypress';

export default defineConfig({
    e2e: {
        baseUrl: 'http://localhost:8000',
        specPattern: 'cypress/e2e/**/*.cy.{ts,tsx}',
    },
});
```

### Cypress Version

10.0.3

### Other

This is apparently caused by some config defaults, but I failed to find which one. And the stack trace isn't really helpful here.

**Comment by romankhomitskyi** [comment]
https://link.medium.com/27VUqMYqHqb

**Comment by yktoo** [comment]
> https://link.medium.com/27VUqMYqHqb

Not sure how that is relevant to my problem...

**Comment by marktnoonan** [comment]
Hi @yktoo, thanks for reporting this. Are you able to create an isolated reproduction? I tried reproducing by placing a file in the root directory of a project with the same name as the directory itself to mimic your `once/once` path but everything worked as expected for me. I also tried a totally empty/fresh Cypress project with a similar setup. Your issue looks like real Cypress issue, I think I'm missing something in how to reproduce.

Some more details are needed to figure out where this issue might be. Please share details around your OS and version also. Thank you!

**Comment by yktoo** [comment]
Hi @marktnoonan, I managed to create a minimal project that reproduces the issue: [cypress-10.tar.gz](https://github.com/cypress-io/cypress/files/8876463/cypress-10.tar.gz).

What I figured out is that it's apparently down to `tsconfig.json` in the root:

```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "es2015",
        "module": "es2020",
        "lib": [
            "es2018",
            "dom"
        ]
    },
    "exclude": [
        "cypress/**/*"
    ]
}
```
If I remove this file (or `once`), Cypress goes on with the startup.

**Comment by marktnoonan** [comment]
Hi @yktoo I was able to reproduce after installing Cypress and Typescript with the example project. Cypress is definitely trying to parse that file as it loads the config:

<img width="1623" alt="Screen Shot 2022-06-13 at 10 09 09 AM" src="https://user-images.githubusercontent.com/8340719/173372615-558b0cbd-c222-4aae-9c5f-ef9aeaadaa8d.png">

We'll get this routed to the team to take a closer look.

**Comment by yktoo** [comment]
Can't reproduce anymore with Cypress 13.15.2. Closing the issue.
