### ISSUE TITLE
A test passes in UI mode and fails when run headlessly

### ISSUE THREAD

**Issue by HeshamMoneer** [cypress-io/cypress#22196]
### Current behavior

I have recently migrated my testing project from cypress 9 to cypress 10
I had a test that used to pass in both UI and headless modes. After the migration, it only passed in UI mode.

There is an error message that keeps showing in the console while tests are running headlessly 

[1788:0608/155331.144737:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for url8437.mytigate.com failed:
----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=url8437.mytigate.com) -----
ERROR: No matching issuer found

### Desired behavior

The tests shall pass in both UI and headless modes.

### Test code to reproduce

The issue happens specifically when an ethereal based task is called.
The task call
```javascript
cy.task('getMessage', key).then(message=>{
    cy.get('html').invoke('html', message.html);
});
```
This task queries an ethereal mailbox for the last message received. The error shown in headless mode 
```
 `cy.task('getMessage')` timed out after waiting `60000ms`
```

### Cypress Version

10

**Comment by rachelruderman** [comment]
Hi @HeshamMoneer, thank you for reporting! Can you provide a reproducible example in isolation? It looks like the current one requires internal implementation logic from your application with the ethereal mailbox call

**Comment by HeshamMoneer** [comment]
Hi @rachelruderman I have been trying to reproduce it and it was only reproducible on the app being tested
Maybe a new feature was added at the time I migrated to Cypress 10 I still need to make further investigations

**Comment by hansottowirtz** [comment]
We're having the same error on CI.

**Comment by rachelruderman** [comment]
> Since updating from 8.5.0 to 9.7.0 our tests are full of certificate errors in Gitlab CI/CD Pipeline (seeing the same thing in two separate projects)

Hi @intellix! Since this issue is specific to the app code of the reporter, it's been closed by the author. For your certificate errors, we welcome you to open a new issue with a reproducible example 🙂
