### ISSUE TITLE
Timed out retrying after 4000ms: cy.trigger() failed because this element:

### ISSUE THREAD

**Issue by mohamed-youssef-maaref** [cypress-io/cypress#22194]
Timed out retrying after 4000ms: cy.trigger() failed because this element:
is being covered by another element:

_Originally posted by @mohamed-youssef-maaref in https://github.com/cypress-io/cypress/discussions/22166_

**Comment by mjhenkes** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will consider reopening the issue.
