### ISSUE TITLE
window.getSelection() API improvement

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [cypress-io/cypress#22195]
### What would you like?

I've been testing a feature that's heavily relaying on **window.getSelection()** browser API and what I basically is is trying to do, is to trigger events that will be normally triggered by the user:

```
[cy.get('[data-cy="my_selector"]')
        .trigger('mousedown')
        .trigger('mousemove', {...args})
        .trigger('mouseup')](url)
```

Another approach I tried was is triggering drag and drop events:

```
cy.get('[data-cy="my_selector"]').trigger('dragstart');
cy.get('[data-cy="my_selector_2"]').trigger('drop');
```

The problem here is that window.getSelection() returning me null in this case, but would be a lot better if there is way we can get a selection as we can do in the browser

### Why is this needed?

I've been testing functionality that is heavily relying on window.getSelection API and have issues with testing it

### Other

I found a similar issue [here](https://github.com/cypress-io/cypress/issues/2839), with some workarounds, however as I understand cypress still doesn't support it

**Comment by jennifer-shehane** [comment]
Since this issue hasn’t had a lot of interest, we’ll close this as not planned.
