### ISSUE TITLE
[session] Spike into the differences between cypress-data-session and `cy.session`

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#22201]
Create a comparison between cacheing, validating and restoring cookies, local storage and session storage.

Brainstorm on what cypress-data-session offers beyond what `cy.session` can do (ie caching arbitrary values)

**Comment by emilyrohrbough** [comment]
https://www.notion.so/cypressdx/cy-session-vs-cypress-data-session-ba8b7cee689f45c695fad06f8948a26d
