### ISSUE TITLE
select outer element with cy.contains()

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#2220]
### Current behavior:
As you mentioned below we can reach an element with html tags:

https://docs.cypress.io/api/commands/contains.html#Selector

But if a tag name is exists more than one nested it select the innermost one. 

<img width="360" alt="screen shot 2018-07-27 at 12 57 32" src="https://user-images.githubusercontent.com/38225108/43316698-c6c8c0fa-91a2-11e8-96b3-e591fcbf866d.png">

Test code is below:
```js
cy.contains('tr', 'Semanta Murphy')
```

### Desired behavior:
But i need outer DOM object. How can I select it?

### Versions

Cypress 3.0.2
macOS 10
Electron 59

**Comment by jennifer-shehane** [comment]
Yes, this is the intended behavior of [`.contains()`](https://on.cypress.io/contains) when passed a selector - to find the deepest element containing the text, then go up to the first parent matching the selector passed. 

Some things that would get you the tr's parent tr:

```js
cy.contains('tr', 'Semanta Murphy').parent('td').parent('tr')
```

```js
cy.contains('tr', 'Semanta Murphy').parentsUntil('tr')
```

```js
cy.contains('tr.ember-view', 'Semanta Murphy')
```

Let me know if this helps.

**Comment by kutlaykural** [comment]
Hi @jennifer-shehane 
Thank you for answer. Here is the results;

```js
cy.contains('tr', 'Semanta Murphy').parent('td').parent('tr')
```
worked fine :)
```js
cy.contains('tr', 'Semanta Murphy').parentsUntil('tr')
```
not worked. Found the same deepest element :(

```js
cy.contains('tr.ember-view', 'Semanta Murphy')
```
worked fine :)

Best,

**Comment by jennifer-shehane** [comment]
Oh no, yeah, I should always try the code before typing it out. 😄 Thanks for posting your results.

**Comment by ArnaudPel** [comment]
I tried `parentsUntil('some-top-element')` as well, but the argument seemed to be ignored, and the command silently returned the exact same thing as `parent()`.

On the other hand, I don't see why `parent()` is accepting any selector: it looks like `parentsUntil()` again, doesn't it ? I mean, AFAICT a DOM element can have but one direct parent. And yet, `parent()` does indeed **use** the selector parameter if provided, just to fail if that selector doesn't match the direct parent.

I have a feeling these commands are work in progress that could do with more love. (Tested with Cypress 3.1.0)

**Comment by brian-mann** [comment]
The traversal commands ie: `parent` and `parentsUntil` match their jquery counterparts so you can always look at the equivalent jquery command (if one exists) like here: https://api.jquery.com/parentsUntil/

**Comment by elcsiga** [comment]
Also `parentsUntil(null, 'tr.ember-view')` worked for me. Second parameter is a filter, so if you have a selector which safely matches a single level, it's fine.

A `cy.safeContains()` command can be implemented this way: 

    Cypress.Commands.add('safeContains', (collectionSelector, searchSelector, searchString) => cy
        .get(collectionSelector)
        .contains(searchSelector, searchString)
        .parentsUntil(null, collectionSelector)); 

`cy.safeContains('tr', 'td.name', 'foo')` then returns a tr element which has the 'foo' match in his name column.
