### ISSUE TITLE
Cypress ignores [hash] when is run via modules API

### ISSUE THREAD

**Issue by Hollander** [cypress-io/cypress#2221]
### Steps to reproduce:
````js
let cypress = require("cypress");

return cypress.run({
   "reporter": "junit",
   "reporterOptions": { "mochaFile": dist + "/junit[hash].xml" }
}).then(() => mergeOutput(dist + "/*.xml", reports + "/junit.xml"));
````
Actually, I have the necessity to dynamically change the report path depending on the environment where the tests are run.

### Current behavior:

Cypress creates `*.hash.xml` and overwrites it after processing of each `*.spec.js` file.

### Desired behavior:

Cypress creates the report file with the unique name for every `*.spec.js` file.

### Versions

Cypress 3.0.2

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/2224
