### ISSUE TITLE
Being able to disable cypress verify step

### ISSUE THREAD

**Issue by johansatge** [cypress-io/cypress#22243]
Hello!

### What would you like?

I'd like to be able to disable the verification process (`cypress verify`) that is triggered on `cypress run`.

### Why is this needed?

Our app that is running in Docker/Jenkins suffers of the timeout issue that was raised a few times (#4624 #6082)

We recently increased the timeout to 60s thanks to the new [`CYPRESS_VERIFY_TIMEOUT`](https://github.com/cypress-io/cypress/blob/576519e465af28e2ed3f0b2c181fbe8f17e348a2/cli/lib/tasks/verify.js#L18) env variable; but the verification still timeouts from time to time.

Something that is not clear to me is the rationale behind this verification process 👇 

- Running it in a local environment as a "defensive" mechanism definitely makes sense, as:
  - Cypress may run on a broad range of configurations, and has specific requirements
  - The host configuration may have changed between two runs
  - The output is helpful to fix the host configuration if needed
- Running it in a containerized environment is debatable as, after said env has been properly configured once, subsequent builds are supposed to be identical
  - And in the case of a CI misconfiguration, I would also prefer the tests to start running and fail immediately, than waiting for the timeout to happen

Thank you for reading! 🌲

**Comment by debMan** [comment]
Any news?

**Comment by uklimaschewski** [comment]
I am experiencing this now too at our docker CI builds, I agree with @johansatge - it would be nice to be able to disable this verification for certain jobs.

**Comment by grushetsky** [comment]
Any chance to introduce an option which can be used to turn off the verification completely? It makes sense for CI environment.

**Comment by joshuajtward** [comment]
I've had a go at adding an optional escape hatch for this as it's causing a lot of false negatives for us in CI: #29836
