### ISSUE TITLE
baseUrl not in right place in a dynamically generated configuration 

### ISSUE THREAD

**Issue by lauterry** [cypress-io/cypress#22247]
### Current behavior

I have a dynamically generated configuration where I put my `baseUrl` at the root instead of the `e2e` object.

<img width="539" alt="Capture d’écran 2022-06-10 à 14 58 03" src="https://user-images.githubusercontent.com/1374238/173072133-0a612160-0855-4c31-a63e-fc1b793c1269.png">

<img width="457" alt="Capture d’écran 2022-06-10 à 14 57 59" src="https://user-images.githubusercontent.com/1374238/173072143-9015a98b-93a0-41c7-b129-4d4287324149.png">

My tests are still running correctly.

In my cypress.config.js, I do not put any `baseUrl`.

On the other hand, If I move my `baseUrl` in the `e2e` object of my dynamically generated configuration, the tests still run but the baseUrl seems to be an empty string

<img width="1263" alt="Capture d’écran 2022-06-10 à 15 18 21" src="https://user-images.githubusercontent.com/1374238/173073119-73426880-fb35-4268-9867-d308bde21ede.png">

### Desired behavior

I expect the `baseUrl` in the `e2e` node in a dynamically generated configuration to be taken into account for my tests

### Test code to reproduce

In the plugins/index.js

```js
module.exports = async (on, config) => {
	const configuration  = {
		e2e: {
			baseUrl: "http://localhost:8080/fr-FR",
			specPattern: `[common]*/{*,**/*}`
		},
	};


	return configuration;
};
```

### Cypress Version

1.0.3

**Comment by rachelruderman** [comment]
Hi @lauterry, thanks for reporting! There's a few ways to dynamically generate a config file, so I'd like to clarify which path you're taking 😸 Are you referring only to modifying the config via `plugins/index.js`? 

PS. It'd help a bunch if you could include a reproducible example, but if not I'll try to throw one together 🙂

**Comment by lauterry** [comment]
Hi

Indeed, I'm referring only to modifying the config via plugins/index.js.

I have already shared some code to reproduce in my first post. Have you tried it ? Is it enough ?

**Comment by rachelruderman** [comment]
Hi @lauterry ! I think the issue you're having is the way the plugins file is being imported / executed. In Cypress 10, the plugins file has been replaced by `setupNodeEvents`. `setupNodeEvents` needs to be nested inside the testing type, but your plugins file is setting the testing type. 

This is all a bit confusing so I've put together a small repro to demonstrate how you can set `baseUrl` from the `plugins/index.js` file. [Check it out here](https://github.com/rachelruderman/investigate-issue-22247)

Let me know if you have further questions or if the setup in my repro is not quite what you had in mind

**Comment by lauterry** [comment]
Ohhh I got it !

Since `setupNodeEvents` is already is the `e2e` node of `cypress.config.js` so there is no need for `baseUrl` to be in a `e2e` node in the `plugins/index.js`.

So there is no bug. 

Sorry for the noise.

I'll close this issue. 

Thank you @rachelruderman
