### ISSUE TITLE
Cypress run freeze

### ISSUE THREAD

**Issue by lugosium** [cypress-io/cypress#22251]
### Current behavior

Hello,

Launching cypress run provides sometimes freeze in middle of the tests:

I have no other choices than `ctrl+c` and relaunch tests hopping it will pass the next times. 
No error is shown.

`cypress run --browser chrome --spec 'tests/cypress/e2e/lugosium-*/**/*'` on MacOS 12.4 and project running under docker.

![Capture d’écran 2022-06-10 à 19 24 31](https://user-images.githubusercontent.com/6922469/173119537-1513aae3-0be0-42fb-9cbe-e7650107ea95.png)

### Desired behavior

Cypress run not freezing.

### Test code to reproduce

none.

### Cypress Version

10.0.3

**Comment by AtofStryker** [comment]
Hey @lugosium. Thank you for opening an issue. Would you be able to provide more details about your `cypress.config.js` as well as the OS you are running on? I created a reproduction repository [here](https://github.com/AtofStryker/cypress-issue-22251) and tried to fill in the blanks. Unfortunately, I was unsuccessful with reproducing the issue. Would you be able to clone that repository and reproduce the issue?

**Comment by lugosium** [comment]
Hello @AtofStryker,

Thank you for your help.

I am on MacOS 12.4. 

I am unable to reproduce the issue, i have no clue when it occurs... 
Unfortunately it occurs from time to time without reason. I just remember that it happened to me on another tests repository so it's not related to my tests i think but more specific to the environment with docker ou maybe chrome mac?

Just to be sure, there is no `-v` parameter for `run` to have more information when it freeze?

Can it be related to the fact that when i launch tests and don't use my computer, i never had the issue, i always had the issue when running tests and continue to navigate with chrome.

**Comment by AtofStryker** [comment]
@lugosium you could try passing in [`DEBUG=cypress:*`](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) before running cypress to get debug logs for when it actually crashes to get an idea of what might be happening. If you do that, would you mind posting the debug logs here?

**Comment by lugosium** [comment]
For example this evening i cannot get it working. Launched two times, two times frozen. 

I will add the env var and post here.

Thanks 👍

**Comment by lugosium** [comment]
Freeze again, here's the last logs:

```
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'google' } +0ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'google' } +0ms
cypress:network:cors Parsed URL { port: '8080', tld: 'localhost', domain: '' } +0ms
cypress:server:remote-states getting remote state: { auth: null, origin: 'https://localhost:8080', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '8080', tld: 'localhost', domain: '' } } for: https://localhost:8080 +0ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'google' } +0ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'google' } +0ms
cypress:network:cors Parsed URL { port: '8080', tld: 'localhost', domain: '' } +1ms
cypress:server:remote-states getting remote state: { auth: null, origin: 'https://localhost:8080', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '8080', tld: 'localhost', domain: '' } } for: https://localhost:8080 +1ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'gstatic' } +521ms
cypress:server:remote-states getting remote state: undefined for: https://www.gstatic.com/recaptcha/releases/some-id/recaptcha__en.js +521ms
cypress:network:cors Parsed URL { port: '8080', tld: 'localhost', domain: '' } +0ms
cypress:server:remote-states getting remote state: { auth: null, origin: 'https://localhost:8080', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '8080', tld: 'localhost', domain: '' } } for: https://localhost:8080 +0ms
cypress:server:stream_buffer stream buffer writeable final called +538ms
cypress:network:agent addRequest called { isHttps: true, href: 'https://www.gstatic.com/recaptcha/releases/some-id/recaptcha__en.js' } +538ms
cypress:network:agent got family { family: 4, href: 'https://www.gstatic.com/recaptcha/releases/some-id/recaptcha__en.js' } +0ms
cypress:server:request received status code & headers on request { requestId: 'request5305', statusCode: 200, headers: { 'content-type': 'text/javascript' } } +538ms
cypress:server:request successful response received { requestId: 'request5305' } +0ms
cypress:net-stubbing:server:intercept-response InterceptResponse { req: { url: '/recaptcha/releases/some-id/recaptcha__en.js' }, request: undefined } +539ms
cypress:network:cors Parsed URL { port: '8080', tld: 'localhost', domain: '' } +17ms
cypress:server:remote-states getting remote state: { auth: null, origin: 'https://localhost:8080', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '8080', tld: 'localhost', domain: '' } } for: https://localhost:8080 +17ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'gstatic' } +0ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'gstatic' } +0ms
cypress:network:cors Parsed URL { port: '8080', tld: 'localhost', domain: '' } +0ms
cypress:server:remote-states getting remote state: { auth: null, origin: 'https://localhost:8080', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '8080', tld: 'localhost', domain: '' } } for: https://localhost:8080 +0ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'gstatic' } +0ms
cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'gstatic' } +0ms
cypress:network:cors Parsed URL { port: '8080', tld: 'localhost', domain: '' } +0ms
cypress:server:remote-states getting remote state: { auth: null, origin: 'https://localhost:8080', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '8080', tld: 'localhost', domain: '' } } for: https://localhost:8080 +0ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51051 } +3s
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51007 } +2s
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51058 } +132ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51063 } +67ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51055 } +72ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51064 } +552ms
cypress:server:socket-base socket-disconnecting ping timeout +32s
cypress:server:socket-base socket-disconnect ping timeout +0ms
cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51010 } +25s
```

**Comment by AtofStryker** [comment]
@lugosium did these debug logs come from the reproduction link I posted or a different test suite? It almost looks like one of the web sockets is timing out. Are you running behind a proxy or VPN of any nature, or have software restrictions on your machine? Based on [disconnect reasons](https://socket.io/docs/v4/troubleshooting-connection-issues/#problem-the-socket-gets-disconnected), I wonder if it is related to the statement you made:

> Can it be related to the fact that when i launch tests and don't use my computer, i never had the issue, i always had the issue when running tests and continue to navigate with chrome.

When you say "navigate with chrome", what exactly do you mean by that? Changing/minifying tabs could potentially cause the websocket [heartbeat to fail](https://socket.io/docs/v4/troubleshooting-connection-issues/#the-browser-tab-was-minimized-and-heartbeat-has-failed), which might explain the freeze (especially in chrome)?

**Comment by lugosium** [comment]
> did these debug logs come from the reproduction link I posted or a different test suite? 

Yes it comes from your link and on the same tests suites (same command i put in description).

> It almost looks like one of the web sockets is timing out.

Yes i have a SSE request that timeout, it's a feature relevant only for multi tabs sync (e.g: if i open the notification center in tab B it delete the badge (1) on the tab A). 

> Are you running behind a proxy or VPN of any nature, or have software restrictions on your machine?

I am not running under proxy or vpn etc... but my project run under docker. 
I don't have software restrictions on my machine either.

> When you say "navigate with chrome", what exactly do you mean by that? Changing/minifying tabs could potentially cause the websocket [heartbeat to fail](https://socket.io/docs/v4/troubleshooting-connection-issues/#the-browser-tab-was-minimized-and-heartbeat-has-failed), which might explain the freeze (especially in chrome)?

i launch the command on my terminal, then, i continue to navigate via my chrome application like normally (openning and closing tabs etc) (i never touch the chrome instance used by the runner that pop)

I ran my tests few hours ago and don't touch my computer, it passed but it's not very practical.

**Comment by lugosium** [comment]
> Do you need to minify the chrome instance the runner is using in order to use the rest of your monitor?

No, it's always minified

**Comment by AtofStryker** [comment]
@lugosium are you using `cypress run` or `cypress open`? Minifying in headful mode could cause that websocket to disconnect in chrome

**Comment by lugosium** [comment]
I use the command in description:

`cypress run --browser chrome --spec 'tests/cypress/e2e/lugosium-*/**/*'`

I was talking about minified because even with run i see some chrome instance pop in the bottom right corner, next to the bin.

**Comment by AtofStryker** [comment]
> I use the command in description:
> 
> `cypress run --browser chrome --spec 'tests/cypress/e2e/lugosium-*/**/*'`
> 
> I was talking about minified because even with run i see some chrome instance pop in the bottom right corner, next to the bin.
> 
> EDIT: Do you think my websocket timeout is the cause?

Ah I missed that. It should be headless then and not cause a problem. I'm going to see if I can intermittently reproduce the issue. What does your docker setup look like?

**Comment by lugosium** [comment]
My bad @AtofStryker i do not have this behavior anymore with the v10 (great version btw!).

I really have a standard php docker configuration. The only "thing" is the project is running on 8080 port, and a sse request is not working (status 400).

**Comment by lugosium** [comment]
Keep freezing, about 7-8 times today :(

**Comment by minhduytran** [comment]
try to use electron might issue come from newest Chrome

**Comment by daminebenq** [comment]
Still freezing here on 12.8.1
I even tried it with firefox nightly the latest... and still reproducible...
cc @brian-mann

**Comment by daminebenq** [comment]
still reproducible on 12.8.1

**Comment by nemonemi** [comment]
I've been on a 12.9.0 for several weeks now, and have just experienced it today, for the first time. There was no change to my system or project in the meantime.

**Comment by nagash77** [comment]
@nemonemi please open a new issue with a reproducible example and we will be happy to investigate.

**Comment by nemonemi** [comment]
Actually, @nagash77 I found out that it is because of an infinite loop. Not a Cypress issue.
