### ISSUE TITLE
Windows build issues - resource class needed to be bumped to large

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#22259]
### Current behavior

In order to get the release out for v10.1.0, we had to bump the resource class on windows from `windows.medium` to `windows.large` (#22258 and #22234)

### Desired behavior

We should be able to reliably use the resource class of `windows.medium` if possible

### Test code to reproduce

Change circle.yml to revert #22234 and #22258 and see a variety of flaky failures

### Cypress Version

Seems to be 10.0.1 and higher but could be 10.0.0 as well

**Comment by rockhold** [comment]
Adding a link here to the CircleCI documentation around the various Windows executor configuration options. The move from medium to large doubles the CPUs and available RAM: https://circleci.com/docs/2.0/configuration-reference/#windows-executor

Also related (but an internal-to-Cypress doc) is our documentation on minimum CPU requirements for running Cypress. Sharing this here for visibility for the team: https://docs.google.com/document/d/1PINe7ZAhQjyI0A45ocVPolKtKzpiKBZdJK7ojhNUF9A/edit?usp=sharing
