### ISSUE TITLE
Aliases not working when visiting different websites

### ISSUE THREAD

**Issue by AlbertQM** [cypress-io/cypress#2225]
### Current behavior:

Used `.as('alias')` to set an alias
Visited another website with `cy.visit()` 
Tried calling the alias with `this.alias`
Resulted in `undefined`

### Desired behavior:

`this.alias` should have returned the actual value rather than `undefined`

### Steps to reproduce:

This small test will reproduce the issue. If you comment out the `Visits website B`, `this.alias` will work as intended.

```js
describe('Aliases', function() {
  let test = "changeme"

  it('Visits website A', function() {
    cy.visit("www.google.it")
    test = "changed"
    cy.wrap(test).as('text')
  })

  it('Visits website B', function() {
    cy.visit("www.amazon.co.uk")
  })

  it('Prints the value', function() {
    console.log(this.text)
  })

})

```

**Comment by jennifer-shehane** [comment]
I would suggest reading through this [document](https://on.cypress.io/variables-and-aliases), it should explain why the code above does not work. 

Also feel free to ask our community in our [gitter channel](https://gitter.im/cypress-io/cypress).

**Comment by AlbertQM** [comment]
Thanks for the prompt reply!

I had already read through that document and sadly I couldn't find a solution.

If you were referring to using `.then((value)=>{});`, due to the nature of the test I'm writing, that is not possible. 

However, I found a workaround for what I needed to do. I'm now storing the values I needed in a file, using `cy.writeFile` and `cy.readFile`.
