### ISSUE TITLE
Cypress 10.1.0 "Spec" UI not remembering settings

### ISSUE THREAD

**Issue by DobQA** [cypress-io/cypress#22263]
### Current behavior

Firstly after upgrading to Cypress 10.0 (macOS) Im little surprised at how the UI feels very unpolished. The UI and navigation should have been tested little more. There is a seperate thread on number of clicks required, for myself the biggest annoyance which I feel is a bug;

When opening my "Specs" list, it has multiple folders and .js files. 
I often use the "Search" or "Collapse" features within the "Specs" list.

1- I run the test I'm intrested in.
2- After the test finishes, on the left hand side I click "Specs" button
3- My search results are all cleared, my collapsed tests are uncollapsed

This then confuses one as beats the point of the features

### Desired behavior

User search and collapsed states are saved, "Specs" button should act as a back button to the "Specs" list.

### Test code to reproduce

1) Make sure you collapse some tests in spec list or do a search.
2) Run a test from long list of specs.
3) After the run finishes, on the left side click "Specs" button
4) All previous settings are cleared

### Cypress Version

10.1.0

**Comment by lmiller1990** [comment]
Hi! Thanks for trying out Cypress 10. This is very good suggestion, I think it should work like a text editor/IDE (like VS Code). I see two separate features/proposals here:

1. remember collapsed state in spec list (both on the landing page, and the run page)
2. remember search text (both pages)

I think these are both good ideas. I will forward them to the design team 👍 

We are collecting all the feedback around Cypress 10 (UI/UX, features, etc) and prioritizing accordingly. Please stay tuned for lots of updates in the near future.

Also, if you have any other ideas or feedback, please make them heard - issues are good (like this one) or you can also create a discussion (here: https://github.com/cypress-io/cypress/discussions). 👊

**Comment by marktnoonan** [comment]
Reading this carefully, at first I thought you were describing a bug with the Inline Specs List that appears on the left hand side of the runner. But that is working as expected, and I think instead you might not be aware of its existence at all. There are two things in the UI that could be called "the specs button on the left" and there are two kinds of "collapsing" that can happen, so it took me a second to put together.

But first, there is an [issue](https://github.com/cypress-io/cypress/issues/21837) open that should be done in some release fairly soon, that will save the search term on the main specs list page. Saving the collapsed folder state is a good one as well, and we will probably create a new issue for that, or roll it into the saved search feature.

But for now, I want to confirm you are aware of the specs list that opens with this button on the top left of the runner:

![Inline specs list](https://user-images.githubusercontent.com/8340719/173628213-22aba20c-2a5b-42ef-b5d9-525d12ba9423.png)

It can be opened and closed with that button or with the `f` hotkey, and the state is preserved whether it is expanded or collapsed. This is my main way of navigating between specs when I already have one open, and I find myself only using the main specs list if I'm just starting cypress or I'm coming back from the settings page or something.

I made a quick loom video to demo that feature: https://www.loom.com/share/6f4f3b03b9a3410bb79c87f40ea70fa5

**Comment by DobQA** [comment]
@marktnoonan Thank you Mark for your reply, I will be honest and did not even realise the above :-( - I was clicking the icon far left above the config button.  Perhaps the button in your screenshot need to be made a little lighter or different color.

The feature you just showed above does solve my issues, indeed its much better then the flow I was going through and a welcomed update :-), keep up the good work and polishing.

**Comment by marktnoonan** [comment]
Thanks @DobQA, glad it helps! Going to close this now. That screenshot it actually a little old, it's a brighter contrast now, but still appreciate the feedback that this was not easy to discover, your instinct is to go "back" to the specs list you were on before, which is fair enough.
