### ISSUE TITLE
Unexpected Error Your configFile threw an error from: cypress.config.js

### ISSUE THREAD

**Issue by Predrag** [cypress-io/cypress#22262]
### Current behavior

Hello,

I have just installed clear installation of Cypress 10.1.0. When I try to run the test spec file (spec.cy.js) the error message appear

Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/predrag/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/babel-loader/lib/index.js:59:71

Operating system: Fedora 36
NodeJs version: 16.14.0

package.json: 

{
  "name": "cypress",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^10.1.0"
  }
}

### Test code to reproduce

1. sudo dnf install  -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
2. npm install cypress --save-dev
3. npx cypress open

### Cypress Version

10.1.0

**Comment by brpaz** [comment]
I got the same error. Also on Fedora.

This started happening when I updated my system to Fedora 36.

Doing a search by this error `Error: error:0308010C:digital envelope routines::unsupported` it seems that it´s related to Node 17 and Open SSL 3 version - https://itsmycode.com/error-digital-envelope-routines-unsupported/.

I don´t have node 17, but I have Open SSL 3.0.3. So maybe in this case I will need to update my Node version.

**Comment by Predrag** [comment]
I agree on Fedora 35 Cypress works fine.

**Comment by Predrag** [comment]
I have installed latest version of Node 18.3.0 and Cypress run as expected. https://computingforgeeks.com/how-to-run-multiple-versions-of-node-js-on-linux/

**Comment by lmiller1990** [comment]
I found this comment about openssl and Node.js 17 in the code base: https://github.com/cypress-io/cypress/blob/develop/cli/lib/util.js#L307-L320. It looks like we patched this https://github.com/cypress-io/cypress/issues/18914, so it should work fine with Node.js 17 from my understanding.

Although there's a good workaround there with a cli flag and here (just get Node.js 18), I still think we should be able to handle both cases and have it work just fine on Node.js 17, too.

**Comment by brpaz** [comment]
@lmiller1990 I got this error with Node.js 16 and Open SSL 3.

**Comment by Predrag** [comment]
> @lmiller1990 I got this error with Node.js 16 and Open SSL 3.

Hello, I have tried to run Cypress with NodeJS 16.15.1 and Cypress runs smoothly. It looks everything below 16.15.1 want not work

**Comment by lmiller1990** [comment]
Cool, thanks for the info everyone - seems like specific versions of Node.js aren't happy, I wonder what happened at 16.15.1 that makes it work.

@marktnoonan is looking into this, happy to help out... these are the Node.js versions we test against: https://github.com/cypress-io/cypress/blob/develop/system-tests/test-binary/node_versions_spec.ts#L29-L32 so we could add some more there, maybe starting with 16.15.0 when we figure out what the problem is.

**Comment by brpaz** [comment]
ah ok, I have `v16.14.0`, which comes by default on Fedora 36. I will try to update it.

**Comment by marktnoonan** [comment]
@brpaz please confirm if that worked for you?

**Comment by brpaz** [comment]
@marktnoonan yes, v16.15.1 works fine.

**Comment by littlejon85** [comment]
Could we please get a cypress/* docker images with node ^16.15.1? We really don't want to move to node 17 yet and this problem crashes our component tests in CI with cypress/base:16.14.2 image. Thanks in advance.

**Comment by jrefior** [comment]
For those who ran into this on Fedora 36: on November 15, Fedora 37 was released, and that upgrades Node.js to 18.7.0 (as of this writing). I had this problem, upgraded to Fedora 37, and it resolved the issue.

**Comment by slavaGanzin** [comment]
Works on 19.8.1, but fails on 20.3.0

**Comment by robin-garnham** [comment]
Error:
`Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)`

Node: `v16.20.1`
Cypress: `v12.15.0`

**Comment by nagash77** [comment]
Hi @slavaGanzin and @robin-garnham can you all please provide a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) along with detailed steps on how you are encountering this problem?

**Comment by lmiller1990** [comment]
> Error: error:0308010C:digital envelope routines::unsupported

Did you see [this](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)? It comes up when you search for that error. It looks like it's related to open ssl.

**Comment by robin-garnham** [comment]
Created a repo with the issue shown: https://github.com/robin-garnham/cypress-issue

Steps:
- `yarn install`
- `yarn cypress:open`
- e2e testing
- Run the spec

**Comment by lmiller1990** [comment]
I tried it on MacOS 13.1 with Node.js v16.20.1 and it worked for me - no issues. Fedora specific?

```
$ openssl version                                                                                    
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
```

**Comment by robin-garnham** [comment]
I'm running `MacOS 13.3.1 (a) (22E772610a)`
`OpenSSL 3.1.0 14 Mar 2023 (Library: OpenSSL 3.1.0 14 Mar 2023)`

Interestingly I'm running a higher version of MacOS, but it's a lower version of OpenSSL?

**Comment by lmiller1990** [comment]
I'd be surprised if a patch version was enough to mess things up. I wonder if there's something else at work here.

Are you on Node.js 16.20?

**Comment by robin-garnham** [comment]
Node: `v16.20.1`

**Comment by lmiller1990** [comment]
Worth a try: `export NODE_OPTIONS=--openssl-legacy-provider` from https://www.datainfinities.com/49/error-0308010C-digital-envelope-routines-unsupported

Other than that, I'm not sure what else to suggest - it sounds like we are using the same core versions for all the libraries you'd expect to be relevant 🤔

**Comment by earlofhemsley** [comment]
> Worth a try: `export NODE_OPTIONS=--openssl-legacy-provider`

This worked for me. Thank you for the suggestion!

**Comment by robin-garnham** [comment]
That works for me also. In my package.json:

"cypress:open": "yarn run cypress open",
"cypress:legacy": "NODE_OPTIONS=--openssl-legacy-provider && yarn cypress:open",

**Comment by lmiller1990** [comment]
🎉

**Comment by abobija** [comment]
```
MacOS 13.4.1
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
node v16.20.1
cypress 12.17.1
```

Same error

```
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

Error: error:0308010C:digital envelope routines::unsupported
```

**Comment by nagash77** [comment]
@abobija please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.

**Comment by joshkaplan** [comment]
I'm getting this on both mac and CI (docker/linux) after upgrading from cypress `12.17.3` -> `13.6.0`. Node version is `18.6.1`

**Comment by joshkaplan** [comment]
in my testing, the breaking change appears to be in `12.17.4`. perhpas it has something to do with the webpack v5 upgrade?

**Comment by joshkaplan** [comment]
for additional context, we are using `@cypress/webpack-preprocessor` and webpack 4. ~~so it's unclear to me what triggerd the issue.~~

~~perhaps the bundled node version got upgraded in 12.17.4? (or it started using system node for building/reading the config?)~~

found the issue here: https://github.com/cypress-io/cypress/issues/27589
