### ISSUE TITLE
Cypress-grep has been broken when migrate to Cypress 10

### ISSUE THREAD

**Issue by eramanli** [cypress-io/cypress#22264]
### Current behavior

I was using grepOmitFiltered option on cypress-grep. Now, cypress-grep is working like grepOmitFiltered: false, it is reading my all spec files since I have upgraded the project to Cypress 10. When my project was cypress 9.X.X, it worked as expected.

![image](https://user-images.githubusercontent.com/40141895/173186376-88ae521c-1419-4d9a-8f29-a7e700732ee2.png)

### Desired behavior

I am running my tests with grepTags and pass the grepFilterSpecs parameter as true. So, it should not go into my untagged spec files, before it omitted them.

### Test code to reproduce

Here is my cypress.config.ts file: 

```
/// <reference types="cypress" />

import { defineConfig } from 'cypress'

export default defineConfig({
  projectId: '22eajy',
  reporter: 'cypress-multi-reporters',
  viewportWidth: 1280,
  viewportHeight: 720,
  reporterOptions: {
    configFile: 'reporter-config.json',
  },
  numTestsKeptInMemory: 1,
  videoUploadOnPasses: false,
  chromeWebSecurity: false,
  retries: 3,
  blockHosts: ['www.google-analytics.com', 'www.googletagmanager.com'],
  env: {
    grepOmitFiltered: true,
  },
  video: true,
  e2e: {
    setupNodeEvents(on, config) {
      return require('cypress-grep/src/plugin')(on, config)
    },
    specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
  },
})

```
Here is the my run command: 
`npx cypress run  --env grepTags=@browsing,grepFilterSpecs=true --spec $(node ./project-spec-finder.js web) --browser chrome`

### Cypress Version

10.1.0

### Other

Test execution starts with this error log and read my all spec files without omitting: 
```
Warning: We failed to trash the existing run results.

This error will not alter the exit code.

Error: spawn /Users/erdinc.ramanli/Library/Caches/Cypress/10.1.0/Cypress.app/Contents/Resources/app/node_modules/trash/lib/macos-trash EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by lmiller1990** [comment]
Thanks for the bug report - we have an issue tracking Cypress Grep, see here https://github.com/cypress-io/cypress-grep/issues/127. I'll close this in favour of that one, but we should fix Cypress Grep asap. It looks like there's a PR already open working on it: https://github.com/cypress-io/cypress-grep/pull/128 let's continue work and discussion there.
