### ISSUE TITLE
Cypress Download Url shows not found

### ISSUE THREAD

**Issue by KrisSodroski** [cypress-io/cypress#22286]
### Current behavior

When I try to download Cypress through my build agent, it attempts to download cypress from the following url: 

https://download.cypress.io/desktop/true?platform=win32&arch=x64

Navigating to this page shows that this url is "Not found"

![image](https://user-images.githubusercontent.com/75279046/173392857-4a6558c9-b786-4197-ab0e-f8741f52f9c0.png)

### Cypress Version

9+

### Package Manager

npm

### Operating system

Windows

**Comment by KrisSodroski** [comment]
That url does work, but running the install from the pipeline seems to pull the url I posted above.

**Comment by jennifer-shehane** [comment]
Yeah...can you run `cypress info` and print the information here?

**Comment by rachelruderman** [comment]
Perhaps somewhere you're setting `CYPRESS_INSTALL_BINARY=true`? This option expects to take a number value rather than a boolean. [See documentation](https://docs.cypress.io/guides/references/advanced-installation#Install-binary)
