### ISSUE TITLE
Cypress Testrail Reporter

### ISSUE THREAD

**Issue by jelimero** [cypress-io/cypress#22283]
### Current behavior

We updated cypress to the latest version, but it seems that this npm package doesn't work anymore with the latest changes: 

https://www.npmjs.com/package/cypress-testrail-reporter

We moved everything from cypress.json to cypress.config.js

Example: 

const { defineConfig } = require("cypress");

module.exports = defineConfig({
  projectId: "nsu9yj",
  viewportHeight: 1070,
  viewportWidth: 1910,
  video: false,
  defaultCommandTimeout: 2000,
  requestTimeout: 2500,
  chromeWebSecurity: false,
  reporter: "cypress-testrail-reporter", 
  reporterOptions: {
    domain: "",
    username: "",
    password: "",
    projectId: ,
    suiteId: 
  },

Not sure what I'm doing wrong and also cannot find anything in the documentation how to use plugins now in Cypress 10

### Desired behavior

Testrail Reporter should work as before. 

### Test code to reproduce

const { defineConfig } = require("cypress");

module.exports = defineConfig({
  projectId: "nsu9yj",
  viewportHeight: 1070,
  viewportWidth: 1910,
  video: false,
  defaultCommandTimeout: 2000,
  requestTimeout: 2500,
  chromeWebSecurity: false,
  reporter: "cypress-testrail-reporter", 
  reporterOptions: {
    domain: "",
    username: "",
    password: "",
    projectId: ,
    suiteId: 
  },

  e2e: {
    baseUrl: "",
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },

  component: {
    devServer: {
      framework: "nuxt",
      bundler: "webpack",
    },
  },
});

### Cypress Version

10.1.0

**Comment by rachelruderman** [comment]
Hi @jelimero, thanks for reaching out! Looks like this is an issue for the maintainer of `cypress-testrail-reporter`. Whenever a breaking change occurs, external packages may need to make a new release to remain compatible with the latest version. In the case of Cypress 10.0, the change in the configuration file (from JSON to JS) means any external packages reading that file need to update. The solution may be as simple as updating the logic looking for the filepath, but it's up to the maintainer of the package to do so.

**Comment by mjhenkes** [comment]
Closing this issue as it is a problem in the `testrail-reporter-plugin`
