### ISSUE TITLE
Words missing in viewport help message.

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#22299]
### Current behavior

When clicking the viewport size message, it seems some words are missing.

![image](https://user-images.githubusercontent.com/8130013/173511455-e825bf90-22bd-43b1-8789-d4cbc7e4c8c5.png)

What is `your`?

I guess it's `config file`, right?

### Desired behavior

Correct help message should be shown.

### Test code to reproduce

Click viewport button. 

### Cypress Version

10.1.0

**Comment by jennifer-shehane** [comment]
Yah, should say `Additionally, you can override this value in your cypress.config.js or via the cy.viewport() command.` Good catch.

**Comment by sainthkh** [comment]
It didn't work yesterday, but it somehow fixed today. I'll close it for now.
