### ISSUE TITLE
scrollTo('bottom') does fire scroll event listeners

### ISSUE THREAD

**Issue by linasmnew** [cypress-io/cypress#2229]
### Current behavior:
**Scenario 1**: When using `scrollTo('bottom')` (in my case on a div) while the scroll does reach the very bottom of the div it does not fire its `scroll` event listener unless I start scrolling manually in the interactive test view.

 **Scenario 2**: Same as above but this time prefixing `scrollTo` with a `pause`, i.e.: `pause().scrollTo('bottom')` then when the test pauses just before scrolling and I click on the resume button, it once again scrolls to the very bottom of the element but this time the `scroll` event listener does fire.

**_(It does work when adding a `wait`, however, this seems weird as I expect the listeners to already be registered before the tests start running)_**

### Desired behavior:
For the `scroll` event listener to always fire when using `scrollTo('bottom')`

### Steps to reproduce:
**Scenario 1**: 
1. Create a div
2. give it a fixed height
3. style it with `overflow: scroll`
4. add enough text into it to make it scrollable
5. add a button below it and make it `disabled`
6. add an event listener to this div element checking for scroll reaching the bottom 
7. once it does reach the bottom enable the button.
8. Now write a cypress test which selects this div element and fires `scrollTo('bottom')` on it and observe that while the bottom of the div is reached, the button is still disabled.

**Scenario 2**: Same as above, just change `scrollTo('bottom')` to `pause().scrollTo('bottom')` and observe that when the test pauses, and you click resume, the scroll reaches the bottom of the div, but this time the button has been enabled.

### Versions
Cypress: ^3.0.2
OS: macOS High Sierra 10.13.3
browser: Chrome 68

**Comment by jennifer-shehane** [comment]
@linasmnew We have some `scrollTo()` tests in our example-kitchen-sink repo. Is there any way you could clone that and update it to make one of our tests fail? That may be an better way to get the failing test case to us. 

https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/integration/examples/actions.spec.js#L219

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by dakur** [comment]
It happened to me as well, `.trigger('scroll')` after `.scrollTo()` fixed it, but still it looks like a bug.

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by cabarcaGAP** [comment]
Hi, not sure if the same/similar issue but:

When I scroll to the bottom, I expect the list to add more items. When executing in my local it works almost all the time. When executing it on GithubActions it does NOT work. 
``` 
        cy.get("ul#my-connections-list ._5DEPB4Zc").last().scrollIntoView({ duration: 2000 })
        cy.wait(3000)
        cy.get("ul#my-connections-list ._5DEPB4Zc").its('length').should('be.eq', 40)
```

that ^ code works in my local but Github Actions does not trigger the event after scrolling.

**Comment by jennifer-shehane** [comment]
@cabarcaGAP Please open a new issue with a reproducible example
