### ISSUE TITLE
Firefox browser is not running 

### ISSUE THREAD

**Issue by TejasSingh-CS** [cypress-io/cypress#22306]
### Current behavior

![image](https://user-images.githubusercontent.com/74040138/173580888-bd2d733a-93d8-4f0a-891c-231ca1144c07.png)

![image](https://user-images.githubusercontent.com/74040138/173580412-19115334-2d89-4391-a8e6-fbfb25afc9da.png)

### Test code to reproduce

a) Open cypress test runner "npx cypress open"
b) Click on e2e testing
b) Click on firefox browser

### Cypress Version

10.0.1

**Comment by AtofStryker** [comment]
Hey @TejasSingh-CS . Thank you for opening an issue. Are you able to provide a reproduction repository or test case to reproduce Firefox not connecting? What operating system are you using?

**Comment by mjhenkes** [comment]
Closing as a duplicate of #22086
