### ISSUE TITLE
Getting Error: CypressError: Timed out retrying: Expected to find element: 'input[Name=namebad2ed7c]', but never found it.

### ISSUE THREAD

**Issue by Ashok251285** [cypress-io/cypress#2230]
Code:

```js
describe ('Rediffmail Test',function()
          {
              it('Open Rediffmail',function() 
              {
              cy.visit('https://mail.rediff.com/cgi-bin/login.cgi')
              })

             it('Create New Account', function() 
              {
              cy.contains('Create a new account').click().wait(3000)
              cy.contains('Create a Rediffmail account')
              cy.get('input[Name=namebad2ed7c]').type('Admin')
              cy.get('input[Name=loginbad2ed7c]').type('Admin')
              cy.get('input[Name=DOB_Daybad2ed7c]').select('13')
              cy.get('input[Name=DOB_Monthbad2ed7c]').select('SEP')
              cy.get('input[Name=DOB_Yearbad2ed7c]').select('1988')
              cy.get('input[Value=F]').click()
              cy.get('input[Name=Registerbad2ed7c]').click()
             })
            
            })
```

**Comment by aldarund** [comment]
@Ashok251285 its not cy problem. In your html input name is generated and on each load it will be different

**Comment by Ashok251285** [comment]
Thank you so much for clarification.
Can you please provide the brief details about , how to close new popup window in cypress and close the current browser.

Sent from Yahoo Mail on Android 
 
  On Sun, 29 Jul 2018 at 9:37 p.m., Dmitry Molotkov<notifications@github.com> wrote:   
@Ashok251285 its not cy problem. In your html input name is generated and on each load it will be different

**Comment by jennifer-shehane** [comment]
@Ashok251285 You might try a more generic selector like:

```js
cy.get('input[Name=name*]').type('Admin')
```

Or potentially get some test on the screen, like the label and then it's sibling input.
```js
cy.contains('label', 'Name').siblings('input').type('Admin')
```

Although, these may not work - as I have no idea what your actual HTML looks like. Just suggestions.

**Comment by wasiqkhan786** [comment]
isOpened() {
       return this.poutils.hasClass(cy.get('sidebarWrapper'), "expanded"  .then(function(expanded) { return expanded === true; });
    };
CypressError: Timed out retrying: Expected to find element: '#sidebarWrapper', but never found it.
I am facing this error tried all solutions but no help . i created object and calling it in test
