### ISSUE TITLE
CI: External contributions are not distributed properly causing long and flaky builds

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#22308]
### Current behavior

Tests are doubled up on CI for external contributors, see [build](https://app.circleci.com/pipelines/github/cypress-io/cypress/39476/workflows/5c2c9690-bd4c-4271-9343-3ef759db4891/jobs/1613218). We ran into this problem pre-10.0 but did't apply the same test distribution rules to our new 10.0 tests https://github.com/cypress-io/cypress/pull/21305. This can lead to long and flaky builds for external contributors.

That job isn't the only one that is duplicating tests, so an audit of the [this build](https://app.circleci.com/pipelines/github/cypress-io/cypress/39476/workflows/5c2c9690-bd4c-4271-9343-3ef759db4891) should be made to find all the jobs that are not distributing properly.

![Screen Shot 2022-06-14 at 9 23 12 AM](https://user-images.githubusercontent.com/25158820/173601283-25d3077a-60c5-4d72-85a9-918e2335fa92.png)

### Desired behavior

CI should distribute tests properly for 10.0 builds

### Test code to reproduce

Check out an external contributors CI build

### Cypress Version

10.1.0

**Comment by emilyrohrbough** [comment]
This change has been completed. It's associated with the 10.3.0 release though there was no user-facing changes related to this change.
