### ISSUE TITLE
Pattern UKStagingJsonReports/.jsons/*.json matched no report files

### ISSUE THREAD

**Issue by aswine** [cypress-io/cypress#22310]
### Current behavior

```
Error: Pattern UKStagingJsonReports/.jsons/*.json matched no report files
```

I have my tests running as

> npx cypress run --browser chrome --headless --spec cypress/integration/uk/smoke/*.spec.js --env grepTags=@TryNow --reporter-options reportDir=UKStagingJsonReports,reportFilename=StagingTests,html=false,json=true,overwrite=false

Here I have given a folder name and the name of the json reports as per my test environment. 
After the execution I have my json reports for each individual tests in the folder "UKStagingJsonReports", but the execution fails saying `StagingJsonReports/.jsons/*.json` matched no report files. Is there a way to override this. Also my screenshots are getting copied from the default directory to the this custom report directory. Are there ways to override this.

Error message as it is:

Read and merge jsons from "UKStagingJsonReports/.jsons"
Copy screenshots folder from "/Users/aswinedavalath/Automation_Web/c*****/cypress/screenshots" to "UKStagingJsonReports/screenshots"
An error was thrown in your plugins file while executing the handler for the 'after:run' event.

### Desired behavior

User should be able to allowed to decide where to store the json reports and screenshots if the user wants to create a new folder for the same.

### Test code to reproduce

Unable to share the github repo

### Cypress Version

7.7.2

### Other

Issue is mostly with mochawesome report generator.

**Comment by rachelruderman** [comment]
Hi there @aswine , thanks for reaching out!

> After the execution I have my json reports for each individual tests in the folder "UKStagingJsonReports", but the execution fails saying StagingJsonReports/.jsons/*.json matched no report files.

Do you have a directory called `StagingJsonReports`? As far as I can tell from your code, the directory is called `UKStagingJsonReports` and that's why mochawesome can't find `StagingJsonReports`

> Also my screenshots are getting copied from the default directory to the this custom report directory. Are there ways to override this.

In Cypress you can customize the screenshot directory via the `screenshotFolder` config property. [See documentation here](https://docs.cypress.io/guides/references/legacy-configuration#Folders-Files)

Please let me know if this helps 🙂

**Comment by aswine** [comment]
![Screenshot 2022-06-16 at 09 36 43](https://user-images.githubusercontent.com/97105695/174030099-7a505ddd-52db-4bc2-8548-2e8f9925358e.png)

**Comment by aswine** [comment]
![Screenshot 2022-06-16 at 09 41 14](https://user-images.githubusercontent.com/97105695/174030256-0c5d47dd-00ef-4cde-8451-b84e4edcb4b7.png)
JSON reports are generated in the folder(UKStagingJsonReports/) which was configured in the CLI. But Cypress looks for a folder named UKStagingJsonReports/.jsons/

**Comment by rachelruderman** [comment]
> But Cypress looks for a folder named UKStagingJsonReports/.jsons/

1. The error you're seeing is being thrown by mochawesome during the report generation process, not Cypress
2. Can you share your `package.json` and plugins file? My hunch is that somewhere you are setting a configuration to `UKStagingJsonReports/.jsons`

**Comment by aswine** [comment]
Thank you for the response. I will raise the issue with mochawesome team. I am closing the issue for now and will update the response from mochawesome team
