### ISSUE TITLE
Subdomain configuration for component testing

### ISSUE THREAD

**Issue by andershoegh2** [cypress-io/cypress#22321]
### What would you like?

Hi! Thank you for all the great work all you maintainers do!

A configuration option for setting the url to open when running component tests.

### Why is this needed?

I'm working with a project that uses subdomains to handle which cloud projects to initialize. When running e2e tests we use the firebase emulator to initialize with a local environment and for that we've set the baseUrl to emulator.localhost... 

Would it be possible to have a config that would let developers decide which url should be opened when the component test runner starts. I've researched for other potential solutions to having the component test server start with a subdomain and, unfortunately, came up short. I'm happy to hear of any other solutions. We would need the right subdomain, so that we load the correct cloud project....so that when we load a component in that depends on, for example, authentication for showing/hiding specific elements, we can actually make that happen.

**Comment by andershoegh** [comment]
Solved this within the app config itself.

**Comment by lmiller1990** [comment]
This should be doable in `cypress.config.js` - as of Cypress 10+ it's a JS module, so you can do any kind of logic you'd like in there.

Happy to reopen if this doesn't solve this issue - I don't see any actionable feature request right - happy to take a proposal if you've got one.

Thanks!
