### ISSUE TITLE
Cypress Fails test on page load

### ISSUE THREAD

**Issue by atmullan** [cypress-io/cypress#22337]
### Current behavior

Fails to load page (page is loaded in video grab) on all visit commands, only in AWS codebuild container (Linux), was working previously with same release. Also runs fine locally (Windows)
<html>
<body>

1) "before all" hook for "Smoke Test Dashboard Page"
--
329 |  
330 | 0 passing (2m)
331 | 1 failing
332 |  
333 | 1) CR Page Smoke Tests
334 | "before all" hook for "Smoke Test Dashboard Page":
335 | CypressError: Timed out after waiting `120000ms` for your remote page to load.
336 |  
337 | Your page did not fire its `load` event within `120000ms`.
338 |  
339 | You can try increasing the `pageLoadTimeout` value in `staging.config.js` to wait longer.
340 |  
341 | Browsers will not fire the `load` event until all stylesheets and scripts are done downloading.
342 |  
343 | When this `load` event occurs, Cypress will continue running commands.
344 |  
345 | Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
346 | at timedOutWaitingForPageLoad (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:155456:74)
347 | at https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:156675:16
348 | at tryCatcher (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:13012:23)
349 | at https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:8134:41
350 | at tryCatcher (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:13012:23)
351 | at Promise._settlePromiseFromHandler (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:10947:31)
352 | at Promise._settlePromise (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:11004:18)
353 | at Promise._settlePromise0 (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:11049:10)
354 | at Promise._settlePromises (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:11125:18)
355 | at _drainQueueStep (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:7719:12)
356 | at _drainQueue (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:7712:9)
357 | at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:7728:5)
358 | at Async.drainQueues (https://stage-cloudranger.druva.com/__cypress/runner/cypress_runner.js:7598:14)
359 | From Your Spec Code:
360 | at Context.eval (https://stage-cloudranger.druva.com/__cypress/tests?p=cypress/support/e2e.js:26329:6)

</body>
</html>

### Desired behavior

Load pages in Tests running in Codebuild

### Test code to reproduce

 cy.visit(Cypress.env('baseUrlCR') + 'organizations/' + Cypress.env('orgId') + '/accounts/all-aws-accounts')

### Cypress Version

10.1.0

### Other

Tried adding more debugging (DEBUG=cypress*) but nothing stick out why this started failing in Codebuild. Network requests looks good

**Comment by atmullan** [comment]
Looks like the issue was caused by a api call to third party service that failed, I added it to the blockhosts ('*drtst*') and tests now running, puzzled though why it didn't fail locally only in aws has the api call was failing in both environments. 
I looking for a good way to output browser logs in codebuild (Linux) standard output, would welcome any ideas

**Comment by atmullan** [comment]
Thanks, please close

**Comment by easu** [comment]
I also encountered the same problem, how to solve it ？
in CI cypress run .... error
but in my macos PC is OK

cypress_version:  9.7.0
chrome_version: 100 headless
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/17491657/210131667-da1eda17-1ed0-4802-bda9-095b8f65f114.png">

**Comment by alecmestroni** [comment]
Same here, any news?

**Comment by svetlana-napris-elucid** [comment]
The issue is closed, I don't think anyone take a look on it anymore. But it happens with me as well (Cypress 13.15.0, AWS run(locally is OK), for sso login page, which is not actually our app under test, so I less care for now if it's loaded properly, but it block the tests run)
