### ISSUE TITLE
Chromium Browser: Uncaught EvalError when doing anything in the Browser console

### ISSUE THREAD

**Issue by samtsai** [cypress-io/cypress#22335]
### Current behavior

Run any test (e2e or component) and open DevTools after the test is finished. Start typing into the console and you'll receive errors.

```
Uncaught EvalError: The following error originated from your application code, not from Cypress.

  > Possible side-effect in debug-evaluate

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
makeErrFromObj @ cypress_runner.js:174852
errorFromErrorEvent @ cypress_runner.js:175201
errorFromUncaughtEvent @ cypress_runner.js:175222
(anonymous) @ cypress_runner.js:172049
```

### Desired behavior

Errors should not be triggered and console should behave normally.

### Test code to reproduce

Note: no special setup required, the repro has component boilerplate setup but not needed to reproduce

https://github.com/samtsai/cypress-10-console-errors

Fails in: Edge v102
Works in: Electron, Firefox

I'm on MacOS 12.4. I don't have Chrome installed so didn't test that.

### Cypress Version

10.1.0

### Other

Looks like this is actually a browser issue:
https://github.com/electron/electron/issues/34350#issuecomment-1137720001
https://github.com/electron/electron/pull/34403

**Comment by samtsai** [comment]
Found an issue reported in Electron repo, it seems like a bug in chromium v102 and will be resolved in v105.

**Comment by mjhenkes** [comment]
Closing this as it will be resolved by chromium
