### ISSUE TITLE
I have tried with proxy configuration of cypress however not able to access the client URL which is only accessible through VPN. Returns 403 forbidden. (Given - Tried when VPN is connected in PC)

### ISSUE THREAD

**Issue by navdeepdevrepublic** [cypress-io/cypress#22330]
I have tried with proxy configuration of cypress however not able to access the client URL which is only accessible through VPN. Returns 403 forbidden. (Given - Tried when VPN is connected in PC)

_Originally posted by @navdeepdevrepublic in https://github.com/cypress-io/cypress/discussions/22275_

For reference, the issue is https://github.com/cypress-io/cypress/issues/21595

**Comment by mjhenkes** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please log a new issue with the required information from our issue template.
