### ISSUE TITLE
Cypres open-ct doesn't works in global mode

### ISSUE THREAD

**Issue by Giorno-Giovana** [cypress-io/cypress#22333]
### Current behavior

I have a project where cypress installed globally (npm i -g cypress).

When i use `cypress open` everything works corrent, but when i use `cypress open-ct` i got `Instantiating lib/project requires a projectRoot!`

If i do `yarn add --dev cypress && git add . && git reset --hard`, everything works correct

### Test code to reproduce

Run `cypress open-ct` in project where there is no cypress in node_modules

### Cypress Version

9.5.0

**Comment by marktnoonan** [comment]
Hi @Giorno-Giovana, the new architecture of component testing that's part of Cypress 10 supports this. `open-ct` is deprecated in 10, since component testing can now be launched with a flag via `cypress open --component`.
