### ISSUE TITLE
Cypress doesn't detect dynamic tests when mixed with normal tests in the same file

### ISSUE THREAD

**Issue by mjgoeke** [cypress-io/cypress#22364]
### Current behavior

Minimal example:
copied and slightly modified from <https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Dynamically-Generate-Tests>

``` js
describe('if your app uses jQuery', () => {
    ['mouseover', 'mouseout', 'mouseenter', 'mouseleave'].forEach((event) => {
        it('triggers event: ' + event, () => {
            cy.log('test ran');
        })
    })

    it('normal test 1', () => {
        cy.log('test ran');
    })
})
```

The cypress runner (`cypress run --testFile example.ts` or `cypress open`) when executing the test file **only detects `normal test 1` and none of the dynamic tests.**

![image](https://user-images.githubusercontent.com/11726379/174146375-9941f28b-24d5-4c38-8fcd-875b4f38058c.png)

### Desired behavior

cypress should detect all tests, dynamic and normal.

### Test code to reproduce

Minimal example:
copied and slightly modified from <https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Dynamically-Generate-Tests>

``` js
describe('if your app uses jQuery', () => {
    ['mouseover', 'mouseout', 'mouseenter', 'mouseleave'].forEach((event) => {
        it('triggers event: ' + event, () => {
            cy.log('test ran');
        })
    })

    it('normal test 1', () => {
        cy.log('test ran');
    })
})
```

Note I'm using cypress 9.7.0 and typescript for test files, in case that makes a difference.

### Cypress Version

9.7.0

### Other

Workarounds:

This seems to have something to do with parsing the structure of the file to detect tests.

Structurally putting the code tree blocks closer together seems to help. E.g.
see comments in code blocks below:

``` js
describe('if your app uses jQuery', () => {
    ['mouseover', 'mouseout', 'mouseenter', 'mouseleave'].forEach((event) => // remove the {} block inside the forEach
        it('triggers event: ' + event, () => {
            cy.log('test ran');
        })
    )

    it('normal test 1', () => {
        cy.log('test ran');
    })
})
```

``` js
describe('if your app uses jQuery', () => {
    ['mouseover', 'mouseout', 'mouseenter', 'mouseleave'].forEach((event) => {
        //return in the forEach (what does that even do?! forEach is supposed to be void)
        return it('triggers event: ' + event, () => {
            cy.log('test ran');
        })
    })

    it('normal test 1', () => {
        cy.log('test ran');
    })
})
```

``` js
describe('if your app uses jQuery', () => {
//add { } block around all tests
  { //start block
    ['mouseover', 'mouseout', 'mouseenter', 'mouseleave'].forEach((event) => {
        it('triggers event: ' + event, () => {
            cy.log('test ran');
        })
    })

    it('normal test 1', () => {
        cy.log('test ran');
    })
  } //end block
})
```

**Comment by rachelruderman** [comment]
Hi @mjgoeke, thank you for reporting! Would you mind throwing together a repo demonstrating the failures? I just tried to repro on my end with Cypress 9.7.0 and it worked as expected:

<img width="1369" alt="Screen Shot 2022-06-16 at 9 06 16 PM" src="https://user-images.githubusercontent.com/26726429/174202162-b4ad54e2-c095-40dc-b639-44026266344c.png">

**Comment by mjgoeke** [comment]
In that case I suspect it's the Typescript setup in my repo.

I will plan to throw together a example repo demonstrating the failure but because of other priorities I will not get to it soon.
Would you be willing to try it out with the boilerplate typescript config?

Thank you for the prompt feedback!

**Comment by rachelruderman** [comment]
Hi @mjgoeke , sure thing! I put together a [TypeScript repo here.](https://github.com/rachelruderman/investigate-issue-22364). So far it seems to be working as expected 👀 

<img width="804" alt="Screen Shot 2022-06-17 at 5 28 45 PM" src="https://user-images.githubusercontent.com/26726429/174403531-e0afd96d-9311-432b-a2a3-3cbf82f8d40b.png">

**Comment by mjgoeke** [comment]
Thanks!  Go ahead and close this issue.  The repository I'm working against was set up years ago. I suspect the typescript transpilation process is old and crufty.
I'll get around to updating it when it's not crunch time and expect it'll work as expected then.

Thank you again :-)
