### ISSUE TITLE
configFile is invalid error

### ISSUE THREAD

**Issue by actionJacksonfv** [cypress-io/cypress#22369]
### Current behavior

When I try to download cypress version 10.0.0 to migrate from a previous version I get this error. configFile xxx is Invalid.
![image](https://user-images.githubusercontent.com/62029645/174185897-e089fb6b-54d1-421f-bfd7-63e0ee362bff.png)

I assume it's because there is a space in my name in the filepath but I'm not sure how to reconcile that. 

### Cypress Version

10.0.0

### Package Manager

yarn

### Operating system

Windows

**Comment by actionJacksonfv** [comment]
This is a similar issue I found just with a file extension error instead of Unsupported_esm_url_scheme
![image](https://user-images.githubusercontent.com/62029645/174392144-9f8a97ff-14d3-4397-8fe1-dd26708f566b.png)

**Comment by tbiethman** [comment]
Thank you for the report @actionJacksonfv. I noticed some of your comments on https://github.com/cypress-io/cypress/issues/22071, indicating that at that time you were still seeing issues with v10.1.0.

Can you re-iterate the problems you are still seeing and ideally provide a minimal reproduction to help with further debugging?

**Comment by actionJacksonfv** [comment]
Thanks. I'm planning on trying out fixes related to #22071
