### ISSUE TITLE
Keep the page state after user logs in when using cy.session()

### ISSUE THREAD

**Issue by vergjor** [cypress-io/cypress#22368]
### What would you like?

I think we could benefit from a small modification of the `cy.session()` command where after the user logs into the application or if the `validate()` method is run we could continue from that state in the tests, instead of the page being cleared.

### Why is this needed?

When we use `cy.session()` and we add a validation for the session like in my case by trying to open a specific page that is only accessible if the user is logged in, then I would have to use:

```ts
    validate() {
      cy.visit('/');
      cy.location('pathname', { timeout: 30000 }).should('equals', '/home');
    },
```

and this is the only way I can validate the login for our application. Then after the session we need to again use cy.visit() to navigate to the home page which is again extra time to re-load everything instead of just continuing from the validation or login state.. removing the blank page part would be amazing

**Comment by emilyrohrbough** [comment]
@devhid This request is to remove the last "Clear Page" step that executed in the `cy.session` command to remove the need to re-visit once a session has been established.

What you are describing is disabling test isolation for a set of tests to have better readability and more granular tests for a given point in your application. This actually requested in #22279 and the full extend of this work can be tracked on #22230.

**Comment by liambutler** [comment]
I personally like having isolation between `it()` blocks, so I'm glad to see that https://github.com/cypress-io/cypress/issues/22230 is working towards having an option to be configured, rather than one or the other
