### ISSUE TITLE
Using cy.get('body').click() should change the activeElement back to <body>

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2236]
Because `body` was not considered a focusable element (see #2235) it would not change the `activeElement` back to itself when being clicked.

This is obviously wrong, so we're fixing it to steal focus correctly now.

Here's a failing test:

![screen shot 2018-07-30 at 4 51 37 am](https://user-images.githubusercontent.com/1268976/43387386-4a9e41d0-93b4-11e8-8587-cf959b238420.png)

**Comment by quantuminformation** [comment]
If I try

        cy.get('body').click()


I get
![image](https://user-images.githubusercontent.com/216566/95846893-4f0f2400-0d4c-11eb-9d3d-a7aea5ba4523.png)
