### ISSUE TITLE
Component testing without valid baseUrl

### ISSUE THREAD

**Issue by larsk2009** [cypress-io/cypress#22372]
### Current behavior

When running the integration tests, I pass the baseUrl via npm to Cypress like this:

```
"test": "cypress run --config baseUrl=$npm_config_host"
```

which allows me to do this to run the tests:

```
npm run test --host=http://example-host.com
```

When running component tests I don't set the `--host`, so npm seems to just pass `$npm_config_host` to the baseUrl. This is offcourse not a valid URL, so Cypress shows this error:

![image](https://user-images.githubusercontent.com/7924568/174235015-66034fc1-443a-4c9c-ae26-217dcd9f9e06.png)

### Desired behavior

When running component testing, I would expect Cypress to ignore the baseUrl as it is not relevant in that case, as far as I am aware.

### Test code to reproduce

I think you can use my code above to reproduce, if not let me know.

### Cypress Version

10.0.3

### Other

Also tried with 10.1.0.

**Comment by lmiller1990** [comment]
I think we validate the entire `cypress.config.js`, regardless of testing type, which I think makes sense.

Would it make sense to add a separate script for running component testing, for example

```json
{
  "test": "cypress run:ct"
}
```

That does not pass the `--config baseUrl` argument?

**Comment by larsk2009** [comment]
Sorry, you are right. I was not doing `cypress run` but `cypress open`. I have no issues with the `cypress run` variant as that indeed doesn't pass the URL. I could make a separate target like you suggested for component testing, but that would open the same UI as for e2e testing, but e2e testing just wouldn't work. I think that is a bit confusing, but if you consider that outside the scope of cypress I can understand.

**Comment by lmiller1990** [comment]
I gave this one some more thought. There's another similar issue here: https://github.com/cypress-io/cypress/issues/22245 which suggest passing `--config baseUrl` is common. I am guessing we want to consider all CLI arguments w.r.t to the selected testing type, for both open and run mode.

If it's useful to you, another way you should be able to dynamically set config is like this:

```js
export default defineConfig({
  e2e: {
    setupNodeEvents (on, config) {
      config.baseUrl = '...'
      return config
    }
  }
})
```

Should work, too. This might be useful in the meantime, unless we address the core issue.

**Comment by larsk2009** [comment]
Yeah as a workaround, I just pass anything on the command line that is a valid URL.

**Comment by larsk2009** [comment]
I tried your workaround, and it is actually better than I though! That is exactly the behavior I was looking for, thanks!
