### ISSUE TITLE
Getting :gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by Rajesh-Kapur** [cypress-io/cypress#22376]
### Current behavior

Hi can anyone help am fairly new to cypress and was negotiating through fine, finding my elements i clicked on an ok button to go to the next webpage however ended up with the above 

Getting :gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is

Everything then seems to freeze 

![image](https://user-images.githubusercontent.com/107467792/174251699-b57b84ed-ff2f-4820-8781-dbb7f947ecb8.png)

### Desired behavior

in this situation i would expect cypress just to load the next page and not throw an error
but throwing this 
(uncaught exception)
TypeError: Cannot read properties of undefined (reading '956')

### Test code to reproduce

  cy.visit( "https://ce0550de.webitrent.com/ce0550de_web/wrd/run/etadm001gf.open");
    //cy.wait(10000); //desperation wait
    //cy.get('html > body.logon > div.logon-background > div.login-container > table#theme2_bg.login.ss > tbody > tr > td >form > table.login > tbody > tr > td > table#loginTab > tbody > tr > td#cyanUserfield > input#USER_NM\.TUSER\.TRENT_SEC\.1').type("kapurr");
    
    //Login to Itrent
    cy.get('input[name="USER_NM\.TUSER\.TRENT_SEC\.1"]').type("");    
    cy.get('input[name="USER_PWD.TUSER.TRENT_SEC.1"]').type("");

   // cy.get('input[name="BU_LOGIN.FRM_BUTTON.ET_BASE.1"]').click
   cy.get('#login_bu').click();

   // second Screen of logon
   cy.get('select[name="ROLE_ID\.TUSER\.TRENT_SEC\.1"]').select('Tech Team')
   .type('{downArrow}')

   cy.get('#login_bu').click();
loads the page then throws the error does say it is nothing to do with cypress but i am wondering how to get rid of it or handle the exception ?
   // Next going dealing with iframes on loaded page

### Cypress Version

9.6

**Comment by lmiller1990** [comment]
Hi! I think "Getting :gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE" is unrelated. It looks like the page your are running your test on in encountering a real error.

I tried visiting the page (it really does take around 10s to load) then entering "kapurr" for the username and hitting submit, but nothing happened. Was there supposed to be a password here (please don't paste sensitive information here)? I can't seem to reproduce your error.

**Comment by Rajesh-Kapur** [comment]
Ok well is there a way of handling an uncaught exception that might get me around this ?

**Comment by Rajesh-Kapur** [comment]
the bug is this ...
The following error originated from your application code, not from Cypress.

  > Cannot read properties of undefined (reading '956')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.[Learn more](https://on.cypress.io/uncaught-exception-from-application)
View stack trace
 Print to console
at <unknown> (https://ce0550de.webitrent.com/ce0550de_web/js/roster_summary.js:1:1105)

is there a way of listening to this or catching it and proceeding , i did not write the application someone else did i am just trying to test it , selenium does not throw an error

**Comment by Rajesh-Kapur** [comment]
ok setting something like this helps to overcome the uncaught exception ... 
Cypress.on('uncaught:exception', (err, runnable) => {
    cy.log(`Uncaught Exception: ${JSON.stringify(err)}`);
  
    return false;
  });
  

however i now know why its failing cypress and iframes --- 
![image](https://user-images.githubusercontent.com/107467792/176261697-e161a44b-e2b6-4a93-bfbf-fc11ca884756.png)

which is another issue i have now --how to handle ?!
