### ISSUE TITLE
Generic for request/response inside .then coming from .wait

### ISSUE THREAD

**Issue by mkbctrl** [cypress-io/cypress#22378]
### What would you like?

Hey, I have similar issue to this one: https://github.com/cypress-io/cypress/issues/9109

I would like to pass proper interface as a generic to `request.body` received from .then, example:

```
cy.wait('@someRequestAlias')
  .then(({request: { body }}) => {
    console.log(body) //=> any
 })
```

From what I currently see, request body is typed as `any` on line `78`. No generic allowed. 

I can create a PR, just wanted to confirm first, that it's not already underway or smth.

Cheers!

### Why is this needed?

Improves the dev experience

**Comment by lmiller1990** [comment]
Basically this: https://github.com/cypress-io/cypress/issues/9109#issuecomment-723001455

> We would be open to reviewing any Pull Requests made trying to improve the typings. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

Not sure on how complex this generic is to add - always happy to see a PR that improves our types :pray:

**Comment by JohnKalan** [comment]
Hi, I would like to take over this issue and be assigned so I can make the corresponding changes.

**Comment by lmiller1990** [comment]
Go for it, contributions to improving types are always welcome.
