### ISSUE TITLE
Proxy-Authorization header created with basic with a small "b"

### ISSUE THREAD

**Issue by Buluc-Celik-Ozbul** [cypress-io/cypress#22383]
### Current behavior

When I set up a proxy with username and password, the Proxy-Authorization header is created with basic type but it says "basic" with small "b" and this fails with some proxies 
![image](https://user-images.githubusercontent.com/88420915/174329823-f42ad6af-12eb-46d8-92ed-febcc63f3fa1.png)

### Desired behavior

The  Proxy-Authorization header should have been created with "Basic" keyword with a capital "B"

### Test code to reproduce

The script used: 
"set HTTP_PROXY=http://username:password@proxy_ip:8080 & cypress open --browser chrome --config-file cypress.json"

The test function:
And("I try cypress request", () => {

    var url = `https://www.somewebsite.com/`;

    const options = {
        method: 'GET',
        url: url
    };

    cy.request(options).then((response) => {
        console.log('cypress request: ', response);
    });
});

### Cypress Version

9.7.0

**Comment by lmiller1990** [comment]
My understanding is `Basic` is correct, and `basic` is not. Seems like a bug we should fix - I've marked it as such, and someone will look into it.

I'm not sure where the code that sets this is, but if you'd like to try make a PR, that'd be great, too - you can probably just do a full text, case sensitive search of the code base to find out where it's set.

**Comment by Buluc-Celik-Ozbul** [comment]
Hi, thanks for the quick response. I have prepared a commit, but I got this:
remote: Permission to cypress-io/cypress.git denied to Buluc-Celik-Ozbul.

I guess I need permission to push. Alternatively, here are the only needed changes if you could do it instead:

/packages/network/lib/agent.ts
line 41:     
- connectReq.push(`Proxy-Authorization: basic ${Buffer.from(proxy.auth).toString('base64')}`)
+ connectReq.push(`Proxy-Authorization: Basic ${Buffer.from(proxy.auth).toString('base64')}`)

/packages/network/test/unit/agent_spec.ts
line 611:
-        'Proxy-Authorization: basic YmF6OnF1dXg=',
+       'Proxy-Authorization: Basic YmF6OnF1dXg=',
