### ISSUE TITLE
cy.session without validate goes into a redirect loop

### ISSUE THREAD

**Issue by gajus** [cypress-io/cypress#22396]
### Current behavior

Receiving error when trying to access existing session:

> The application redirected to about:blank more than 20 times. Please check if it's an intended behavior.
> 
> If so, increase redirectionLimit value in configuration.

<img width="620" alt="Screen Shot 2022-06-19 at 12 08 22 PM" src="https://user-images.githubusercontent.com/973543/174492505-3c6edc09-b10b-49bb-819e-9094abaf0094.png">

This appears to happen only in tests with many steps. I wasn't able to create an isolated example.

Related to this, it also appears to happen only on a second test https://github.com/cypress-io/cypress/issues/22381.

### Test code to reproduce

Breaks:

```ts
cy.session(
  'CLIENT',
  () => {
    cy.registerNewTestUser({ onboardingType: 'CLIENT' }).as('CLIENT');
  },
);
```

Also breaks:

```ts
cy.session(
  'CLIENT',
  () => {
    cy.registerNewTestUser({ onboardingType: 'CLIENT' }).as('CLIENT');
  },
  {
    validate: () => {},
  }
);
````

Works:

```ts
cy.session(
  'CLIENT',
  () => {
    cy.registerNewTestUser({ onboardingType: 'CLIENT' }).as('CLIENT');
  },
  {
    validate: () => {
      cy.visit('/me');
    },
  }
);
```

### Cypress Version

10.1.0

**Comment by emilyrohrbough** [comment]
@gajus Thank you for opening an issues in regards to `cy.session()`. I have worked in the session code for a bit now and have not seen the behavior with the tests. 😢  Could you provide more information on the code you provided to reproduce this issue? A fully reproducible example would be best.
- Can you share what the `cy.registerNewTestUser()` custom command does?
- Is `cy.visit('/me')` a placeholder for any page?
- When you say "This appears to happen only in tests with many steps", can you share what a test might be doing in general leading up to creating or restoring a session within a test?

**Comment by emilyrohrbough** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment if there is new information to provide concerning the original issue and we can reopen.
