### ISSUE TITLE
npx cypress open command fails

### ISSUE THREAD

**Issue by VacantFuture** [cypress-io/cypress#22408]
### Current behavior

It looks like this is your first time using Cypress: 10.1.0

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

/home/jnobles/.cache/Cypress/10.1.0/Cypress/Cypress: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 10.1.0

### Desired behavior

It launches Cypress for the first

### Test code to reproduce

npm install cypress --save-dev
npx cypress opn

### Cypress Version

10.1

### Other

Ubuntu linux on WSL2 via command line. I did follow the link concerning dependencies and installed them via sudo apt-get

**Comment by emilyrohrbough** [comment]
@VacantFuture Can you try running `apt-get install libcups2` to see if you have a missing dependency on your system? We may need to update the documentation.

**Comment by ememisya** [comment]
`[INFO] > cypress run --headless --browser chrome --component`
`[INFO] /root/.cache/Cypress/12.17.1/Cypress/Cypress: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory`

I came across the same problem.  Is libcups.so.2 not a dependency?

It may be an issue with google-chrome however the message isn't quite clear.

**Comment by nagash77** [comment]
@ememisya please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
