### ISSUE TITLE
Can't exclude tests from command line in Cypress 10

### ISSUE THREAD

**Issue by ztulic** [cypress-io/cypress#22407]
### Current behavior

`npm run cy:run -- --browser chrome --headless --spec "**/!(test1.js|test2.js)"`
this will run all tests

### Desired behavior

`npm run cy:run -- --browser chrome --headless --spec "**/!(test1.js|test2.js)"`
This should ignore test1.js and test2.js from running

### Test code to reproduce

Have at least 4 tests
run command in terminal
`npm run cy:run --  --spec "**/!(test1.js|test2.js)"`
Only 2 tests should run. Tests test1.js and test2.js should be ignored.

### Cypress Version

10.0.3

### Other

This issue is discovered after migrating to Cypress 10, before that it was working as expected.

**Comment by tbiethman** [comment]
@ztulic thank you for the report, I am able to reproduce this. This is likely related in some way to https://github.com/cypress-io/cypress/issues/22272. We need to make sure we're supporting extglob patterns appropriately within the spec pattern.

**Comment by tbiethman** [comment]
Following up, formatting your glob like this will work as of 10.4.0: `**/!(test1|test2).js`

It seems like globby cannot handle fully qualified files within the negation pattern, or maybe a terminal negation pattern?

**Comment by melibe23** [comment]
This has not been fixed. Would it be possible to reopen it?

**Comment by MikeMcC399** [comment]
@melibe23 

- In addition to requesting that this issue be re-opened, you have opened a new issue https://github.com/cypress-io/cypress/issues/27367, so I assume that the request to re-open this issue is now obsolete.
