### ISSUE TITLE
When you open the TestRunner on a browser such as Chrome, Firefox etc, the favicon displayed is not from the browser itself or even Cypress.

### ISSUE THREAD

**Issue by estefafdez** [cypress-io/cypress#22404]
### Current behavior

With the new Cypress 10 version of the Test Runner, when you open the TestRunner on a browser such as Chrome, Firefox, etc, the favicon displayed is not from the browser itself or even Cypress.

![image](https://user-images.githubusercontent.com/6990209/174639609-4aa39950-c882-4301-87d3-7688d5b9dbe4.png)

### Desired behavior

Add the correct favicon of the browser to know exactly the browser where you are running the tests and add, at least a better title with the specs instead of `test`. 

### Test code to reproduce

Any project run on Chrome or Firefox. 

### Cypress Version

10.1.0

**Comment by nagash77** [comment]
@estefafdez this issue has been resolved.
