### ISSUE TITLE
Cypress.io more precise run time

### ISSUE THREAD

**Issue by kristofer-lp8f** [cypress-io/cypress#22402]
### What would you like?

On `cypress.io` looking at a test run from some days ago there is an item saying e.g. **Ran 4 days ago**

I would like to get a more specific time using mouse-over or clicking on the time.

### Why is this needed?

Faster debugging and generally better to have more precise information available

**Comment by jennifer-shehane** [comment]
@kristofer-lp8f You can hover over the time ago in the Cloud to see the exact time it ran. 
![Screenshot 2024-01-24 at 10 19 47 AM](https://github.com/cypress-io/cypress/assets/1271364/25eac6e5-3dc3-43c8-be4a-8ceb1d4682b1)
