### ISSUE TITLE
Migration Helper throws error and does not continue

### ISSUE THREAD

**Issue by Craig1f** [cypress-io/cypress#22403]
### Current behavior

```
CombinedError {name: 'CombinedError', message: "[GraphQL] ENOENT: no such file or directory, open …Users\\Craig\\dev\\project-name\\cypress\\plugins\\index'", graphQLErrors: Array(1), networkError: undefined, response: Response}
graphQLErrors: [GraphQLError: ENOENT: no such file or directory, open 'C:\Users\Craig\dev\project-name\cypress\plugin…]
message: "[GraphQL] ENOENT: no such file or directory, open 'C:\\Users\\Craig\\dev\\project-name\\cypress\\plugins\\index'"
name: "CombinedError"
networkError: undefined
response: Response {type: 'basic', url: 'http://localhost:60011/__launchpad/graphql/query-MigrationWizardQuery', redirected: false, status: 200, ok: true, …}
[[Prototype]]: Error
```

Contents of `C:\\Users\\Craig\\dev\\project-name\\cypress\\plugins\\index`: 
- ctSetup.js
- index.js

ctSetup.js is some reusable factory methods for setting up component tests in Cypress v9. 
index.js is configuration for the vite server, which is currently functional

If I create a new file called `index` without an extension, migration continues, but the configuration for both component tests and e2e tests is incorrect and I was not able to get tests to work after a day of trying to fix them. That can be covered in a separate ticket, because it's unclear how much of the misconfiguration was due to the hack of adding an empty `index` file to get past the issue described in this ticket. 

### Desired behavior

Migration should work, and I should have working e2e and component tests (with Vue2 and Vite) by the end of it.

### Test code to reproduce

Proprietary. May attempt to create a new repo if necessary. Will take time. 

### Cypress Version

10.1.0

### Other

Vue2
Javascript
Vite

**Comment by lmiller1990** [comment]
Hi! Can you share your `cypress.json` please? It looks like a similar issue to https://github.com/cypress-io/cypress/issues/22461. The issue there is the `cypress.json` points to a directory which contains `index.js`, as opposed to the actual file. I'm patching this now, but if that is the problem, you might be able to solve it by just changing `cypress.json` to explicitly point to your `pluginsFile` (if you have a custom one set).

**Comment by Craig1f** [comment]
@lmiller1990 You got it. Good catch. 

I'll close this issue and try to proceed with migration. Any other issues will be a separate ticket. 

Thanks!
