### ISSUE TITLE
Cypress visit onBeforeLoad is not updating react redux state

### ISSUE THREAD

**Issue by Rishyab** [cypress-io/cypress#22401]
### Current behavior

Till cypress 9.7, we are able to update initial redux state, which is not updating from version 10.

### Test code to reproduce
```js
cy.fixture(fixture-path.json)
  .as('initialState')
  .then(initialState) => {
    cy.visit(localhost:8080,{
          onBeforeLoad: (window: any){
            window.initialState = initialState
         },
     })
   })
```

### Cypress Version

10.1

**Comment by emilyrohrbough** [comment]
@Rishyab Can you please provide more information? A small reproducible example would be helpful for investigation what setup you are working with and how it appears to have been impacted from 9.7 to 10.1.

**Comment by Rishyab** [comment]
We have automated react application using cypress.

While loading our application (using cy.visit()), we use option onBeforeLoad to set a property initialState on window object.

We use this initialState property to set initial state of page (ie. page is loaded with preloaded data in redux store).
This mean the page loads we pre-populated data provided in fixture.

Till Cypress 9.7 option onBeforeLoad worked fine for us, the initialState property which we add to window object, which was used to set state of redux store and opens page with provided state or data.

Form Cypress 10 onwards, the page is opening without the initialState provided in onBeforeLoad. There can be a chance that onBeforeLoad is not working as expected

**Comment by hoguan** [comment]
We are encountering the same issue on Cypress 10.0.3. 

Here is a reproducible example if it helps.

```
it('onload', function() {
  cy.on('window:before:load', (e) => {
    console.log('window:before:load');
  });

  cy.on('window:load', (e) => {
    console.log('window:load');
  });

  cy.visit('/', {
    onBeforeLoad(win) {
      console.log('onBeforeLoad');
    },
    onLoad(win) {
      console.log('onLoad');
    }
  });
});
```

**Current behavior:**
Produces this logs:
```
window:load
onLoad
```

**Desired behavior:**
```
window:before:load
onBeforeLoad
window:load
onLoad
```

**Versions**
Cypress version: 10.0.3
Browser: Chrome 103
OS: macOS Monterey, Version 12.4

**Comment by emilyrohrbough** [comment]
@hoguan I am checking the code you provided against 10.3.0 and I am seeing the correct logs in the devtools console:
```
window:load
window:before:load
onBeforeLoad
window:load
onLoad
```
I have set `baseUrl: "https://www.cypress.io"`. Can you try upgraded to 10.3.0?

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
