### ISSUE TITLE
Component testing fails with configuration error when using array in e2e specPattern

### ISSUE THREAD

**Issue by Loosetooth** [cypress-io/cypress#22414]
### Current behavior

In the cypress app, when clicking on the "Component testing beta" button, the app stops showing the following error:

![image](https://user-images.githubusercontent.com/66420755/174751578-b079d86d-487a-4db6-a305-406a5e7c8b6a.png)

This only happens when we use an array in the `specPattern` prop for the `e2e` config.
When using just a string it works fine.

This is the full `cypress.config.js` that I use, as an example:

```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    specPattern: [
      "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}",
      "pages/**/*.cy.{js,jsx,ts,tsx}",
    ],
  },

  component: {
    devServer: {
      framework: "next",
      bundler: "webpack",
    },
  },
});
```

### Desired behavior

Cypress should be able to start component testing, even when an array is used in the `specPattern` e2e config property.

### Test code to reproduce

I forked the `cypress-tiny-test` repo and added a failing config, [code can be found here](https://github.com/Loosetooth/component-specpattern-bug).

### Cypress Version

10.1.0

**Comment by tbiethman** [comment]
@Loosetooth thank you very much for the report and the reproduction! We had another instance of this issue come in here (https://github.com/cypress-io/cypress/issues/22551). I've moved that issue to the appropriate feature team and will close this issue as a duplicate so we can track the work in one place. Thanks again!
