### ISSUE TITLE
`node_modules/cypress/types/net-stubbing.ts` should be a `.d.ts` file

### ISSUE THREAD

**Issue by Jym77** [cypress-io/cypress#22417]
### Current behavior

When using Cypress as a library, there is one file called `node_modules/cypress/types/net-stubbing.ts` which only contains type definitions.
Together with latest version of API extractor, this creates the error:
```
Error: <project>/node_modules/cypress/types/net-stubbing.ts:1:1 - (ae-wrong-input-file-type) Incorrect file type; API Extractor expects to analyze compiler outputs with the .d.ts file extension. Troubleshooting tips: https://api-extractor.com/link/dts-error
```

[Error description](https://api-extractor.com/pages/messages/ae-wrong-input-file-type/) advises to report the problem to the package maintainers…

This file seems to be created during build in the [post install](https://github.com/cypress-io/cypress/blob/e6b2466f7b219a86da46c1ac720432ef75193ca4/cli/scripts/post-install.js#L76-L78) script.

The error is not detected by older versions of API extractor (not present with 7.20.1 but present with 7.25.2).
This file was already here in older versions of Cypress (I can see the error on Cypress 8.4.1).

### Desired behavior

Cypress should export its typing in `.d.ts` files rather than in `.ts` ones.

### Test code to reproduce

[Github action failing on that problem](https://github.com/Siteimprove/alfa/runs/6983182879?check_suite_focus=true#step:8:6).

### Cypress Version

8.4.1, 10.1.0

**Comment by Jym77** [comment]
@mjhenkes @ZachJW34 Sorry, I realise I never got to look into it 😞 Thanks for the fix.

**Comment by ZachJW34** [comment]
@Jym77 all good! I had to fix this as a result of some other work, so this fix will be in the next release!
