### ISSUE TITLE
Cypress App reload in the middle of a test run if config file is updated at the same time

### ISSUE THREAD

**Issue by Deop** [cypress-io/cypress#22416]
### Current behavior

I was working on updating Cypress to v10 in our project and was running some tests with 'cypress open' locally. I noticed that if you start the test and update config file while it's still running it would immediately reload Cypress App without completing the test.

### Desired behavior

Cypress should wait until test finish before reloading with config file changes.

### Test code to reproduce

No specific code to reproduce. Just start a test and update config file while it's still running.

https://user-images.githubusercontent.com/7953144/174782712-3f668bf5-5d04-4679-ba2a-c5fed1742757.mp4

### Cypress Version

10.1.0

**Comment by emilyrohrbough** [comment]
@Deop Thanks you for opening this issues. The behavior you are describing is intended behavior for `cypress open` as it's intended to be used by developers to quickly make component/application changes and write tests to verify their component/app is working as intended.

If you'd prefer to by-pass this behavior, you can leverage `cypress run --headed --no-exit` to view your tests run without picking up the configuration changes.
