### ISSUE TITLE
Cypress_runner.js is not working after 10.1.0 upgrade

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#22421]
### Current behavior

I was using cypress_runner.js file to generate HTML reports.
After upgrade to 10.1.0 version this is crashing.
![obraz](https://user-images.githubusercontent.com/34089686/174818009-f54c0eb9-dade-43d1-860d-2a909dea4df2.png)

This is problematic for me, cause I was running this script to generate reports with Jenkins.
I'm pasting my cypress_runner.js file

### Test code to reproduce

```javascript
const cypress = require('cypress')
const yargs = require('yargs')
const { merge } = require('mochawesome-merge')
const marge = require('mochawesome-report-generator')
const rm = require('rimraf')
const cypressConfig = require('./cypress')
const ls = require('ls')
const argv = yargs.options({
  'browser': {
    alias: 'b',
    describe: 'choose browser that you wanna run tests on',
    default: 'chrome',
    choices: ['chrome', 'electron', 'firefox']
  },
  'spec': {
    alias: 's',
    describe: 'run test with specific spec file',
    default: 'cypress/endToEndTests/*.js'
  }
}).help()
  .argv

const reportDir = cypressConfig.reporterOptions.reportDir
const reportFiles = `${reportDir}/*.json`
// list all of existing report files
ls(reportFiles, { recurse: true }, file => console.log(`removing ${file.full}`))

// delete all existing report files
rm(reportFiles, (error) => {
  if (error) {
    console.error(`Error while removing existing report files: ${error}`)
    process.exit(1)
  }
  console.log('Removing all existing report files successfully!')
})

cypress.run({
  browser: argv.browser,
  spec: argv.spec
}).then((results) => {
  const reporterOptions = {
    reportDir: results.config.reporterOptions.reportDir,
  }
  generateReport(reporterOptions)
}).catch((error) => {
  console.error('errors: ', error)
  process.exit(1)
})

function generateReport(options) {
  return merge(options).then((report) => {
    marge.create(report, options)
  })
}
```

### Cypress Version

10.1.0

**Comment by tbiethman** [comment]
Your script is now failing to import what used to be your `cypress.json` file, as it is now named `cypress.config.js` with v10. 

Give this a try instead:
```
const cypressConfig = require('./cypress.config.js')
```

**Comment by zbigniewkalinowski** [comment]
I tried it before. Cypress migration changed this config file to `cypress.config.ts`
I chenged it to: const `cypressConfig = require('./cypress.config.ts')`
Now i'm getting this:
![obraz](https://user-images.githubusercontent.com/34089686/175476520-bb20d423-ba6e-4ea5-bc7e-b6b272f41d6d.png)

**Comment by tbiethman** [comment]
The javascript config file generated during migration uses ESM by default. Since you're requiring it into your node script, you'll need to convert the config file to use CommonJS requires/exports or execute your script with something like [ts-node](https://www.npmjs.com/package/ts-node#commonjs-vs-native-ecmascript-modules) instead.

**Comment by tbiethman** [comment]
@zbigniewkalinowski It seems like the problems here have been resolved, so I'm going to close this issue. Please open a new issue if you run into additional problems with your script.
