### ISSUE TITLE
Component testing with vite in a typescript monorepo causes TypeError

### ISSUE THREAD

**Issue by efossvold** [cypress-io/cypress#22422]
### Current behavior

Component testing in a typescript monorepo causes TypeError when a tested component in module (A) imports code from another module (B) within the same monorepo. 

Typescript paths is configured in tsconfig.json
```
"paths": {
  "@foo/*": ["packages/*/src"]
}

```
Yarn workspaces is setup in package.json
```
"workspaces": [
  "packages/*"
],
```

Testing a component in module A which imports from module B results in the following error:

> The following error originated from your test code, not from Cypress.
> Failed to fetch dynamically imported module: http://localhost:3000/__cypress/src/src/components/Footer.cy.tsx
> When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
> Cypress could not associate this error to any specific test.
> We dynamically generated a new test to display this failure.

Vite dev server works without a problem. vite.config.ts is configured to load typescript paths from with the "vite-tsconfig-paths" plugin.
```
import { join } from "path";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import react from "@vitejs/plugin-react";

export default defineConfig({
  envDir: join(__dirname, "../.."),
  plugins: [tsconfigPaths({ root: ".." }), react()],
});

```

Testing of components that does not import from other modules within the same monorepo work as expected.

I ran into this problem after upgrading to 10.1.0. On 9.6.1 component testing with vite worked fine.

### Desired behavior

Component testing should work within monorepos. 

### Test code to reproduce

I've set up a [repo here](https://github.com/efossvold/cypress-component-vite-issue.git) which reproduces there error. It's forked from the official cypress vite component testing example (https://github.com/cypress-io/cypress-component-testing-apps/tree/main/react-vite-ts).

The "Footer" component (in main) imports from utils. So Footer.cy.tsx fails when run in cypress, however, the other components which does not import from other modules in the repo work as expected.

To reproduce
1. Clone the repo (git clone https://github.com/efossvold/cypress-component-vite-issue.git)
2. yarn
3. cd packages/main
4. cypress open --component
5. Select component testing
6. Select "Button.cy.tsx" (works)
7. Select "Footer.cy.tsx" (fails)

### Cypress Version

10.1.0

### Other

Typescript
React
Vite

**Comment by lmiller1990** [comment]
Hi! 10/10 issue, very clear and reproduction works as expected, so thanks!

I created a PR showing you how to fix this: https://github.com/efossvold/cypress-component-vite-issue/pull/1

If you are importing files outside the root where Vite is running (eg, you want to reach up into `../utils`, you need to tell Vite it's okay to reach above the current working directory. Here's how: https://vitejs.dev/config/#server-fs-allow

We could potentially do something in Cypress to make this kind of problem and how to fix it more clear. I think Vite became more strict at some point with file system access - I wonder if you were on a previous version of Vite where it didn't have as much strictness around what Vite served, or maybe your project was configured differently? 

I hope this solves your issue. If so, please let me know. We could look into making this more clear, but I think that would be a separate issue.

**Comment by efossvold** [comment]
Perfect! This fixed the issue. It's been a few weeks since I used Cypress so it may be that I upgrade in the meantime, and that, as you say, Vite has become more restrictive with file system access. Anyway, Cypress and Vite are running smoothly together now. Thank you!
