### ISSUE TITLE
npx cypress run running on a random test case files 10.2.0

### ISSUE THREAD

**Issue by nomsokheng** [cypress-io/cypress#22438]
### Current behavior

Once we start running a test using `npx cypress run` we see a test case doesn't run as order by asc on a path & files like before. 

### Desired behavior

It should run order by path & file asc as before.

### Test code to reproduce

Have a multiple test case order by asc on a path and file start execute the test using `npx cypress run` 

### Cypress Version

10.2.0

**Comment by tbiethman** [comment]
@nomsokheng thank you for the report. Executing `cypress run` will use your defined `specPattern` (or the default `cypress/e2e/**/*.cy.{js,jsx,ts,tsx}` for e2e tests). to find and queue up the tests to run. When I run tests using 10.2.0, I see that the globbed specs found generally matches the sorting order on the filesystem. What you might be running into is specs in directories, which seem to be found in a breadth-first fashion.

Given a structure like:
![Screen Shot 2022-06-23 at 1 06 35 PM](https://user-images.githubusercontent.com/1711637/175365512-de93898d-894c-4708-8577-845364df6f09.png)

I'm seeing the specs execute in this order:
`spec-root.cy.js, spec-1.cy.js, spec-2.cy.js, spec-1-a.cy.js, spec-1-b.cy.js, spec-2-a.cy.js, spec-2-b.cy.js`

This does differ from the 9.x functionality, but I'm not sure the execution order was ever documented as API. Is this difference in ordering impacting your workflow?

**Comment by mjhenkes** [comment]
Closing, We do not guarantee the order of spec execution from globs.
