### ISSUE TITLE
Cy.origin not share token with subdomain

### ISSUE THREAD

**Issue by carol-oliveira** [cypress-io/cypress#22436]
### Current behavior

When using the cy.origin with a subdomin url, cypress first loads the domain URL (and save the local storage values) and after executing the visit on the subdomain(with local storage empty)  

Example: 
```javascript
cy.origin("https://mysubdomain.dev.mydomain.com", { args: { number} }, ({ number}) => {
  cy.visit("/test/cart/" + number ) 
})
```

Cypress create on local storage at two sites: 
1 - https://mydomain.com 
2 - https://mysubdomain.dev.mydomain.com

The issue is that I need the shared token value, and cypress put only on the first visit site (https://mydomain.com) even though I didn't pass that URL. subdomain

### Desired behavior

Cypress should save the local storage values on the second subdomain. 

### Test code to reproduce

```javascript
 cy.origin("https://mysubdomain.dev.mydomain.com", { args: { number} }, ({ number}) => {
  cy.visit("/test/cart/" + number )
})
```

### Cypress Version

9.7.0

**Comment by emilyrohrbough** [comment]
@carol-oliveira Could you expand a bit on the steps to reproduce this issue? I don't fully understand the test flow you or what you are trying to achieve.
