### ISSUE TITLE
Acer editor: cannot change field value

### ISSUE THREAD

**Issue by allangrds** [cypress-io/cypress#2244]
### Current behavior:
I have a project using [Ace Editor](https://github.com/thlorenz/brace), and I need to create a test that will change the text inside the editor.

To change the editor text, I need to find the element on DOM by id, and use a function from `ace`'s library. When I've runned the tests, the id isn't found.

![cypress](https://user-images.githubusercontent.com/4103305/43411705-61342f2a-9401-11e8-87dd-6bc5a4f28d25.png)

![code](https://user-images.githubusercontent.com/4103305/43411664-3d2be456-9401-11e8-901a-9cfd838bcabf.png)

### Desired behavior:
Find `#custom-panel` element and change its value.

### Steps to reproduce:
Access the open source repo [Artis](https://github.com/pagarme/artis/commits/add/cypress-custom-tests), and go to `cypress-custom-tests` branch.

### Versions
2.1.0

**Comment by brian-mann** [comment]
You are on an older version of Cypress, and in newer versions we print better error messages - but basically you're not using the commands correctly. You're using them as if they are synchronous but they are not.

For instance, it's literally impossible for that DOM element to be found. Right above it you're using a `cy.visit()` and as you can imagine visiting a website could take a long time.

This is documented in all the introductory guides and it explains exactly how to handle this:

- https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous
- https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#

**Comment by brian-mann** [comment]
Also there are known issues with Ace Editor - and they have all been fixed in `3.0.3` which I'd recommend you upgrade to.

**Comment by allangrds** [comment]
@brian-mann I've update the Cypress version to `3.0.3`, and made the follow test:
```
cy.visit('/')

setTimeout(() => {
  console.log('editor')
  console.log(document.getElementById('custom-panel'))
}, 6000)
```
The console result was `null`. I put `document.getElementById('custom-panel')` on `console` tab opened by Cypress and I got the element I was looking for.

**Comment by allangrds** [comment]
I need to use the function `ace.edit('id')`, to manipulate Ace's code container. But when its execute this line of get, return `Uncaught Error: ace.edit can't find div #custom-panel`, a message from the lib, because it's not possible to get the element by DOM tree.

**Comment by allangrds** [comment]
It works
```js
cy.get('#custom-panel').then((ele) => {
  const editor = ace.edit(ele[0])
  editor.setValue('hello world')
})
```

Thanks
