### ISSUE TITLE
On vite 3.0.0-beta-0 componet test throw error: "Package subpath './package.json' is not defined by 'exports'"

### ISSUE THREAD

**Issue by simcha** [cypress-io/cypress#22452]
### Current behavior

Upgrading vite to 3.0.0-beta.0 renders cypress component testing unusable.
After running  component mode user is greeted with message:
Error: Package subpath './package.json' is not defined by "exports" in /tmp/cypress-component-testing-apps/vue3-vite-ts/node_modules/vite/package.json

### Desired behavior

Cypress should start the component testing screen.

### Test code to reproduce

One can easly reproduce a bug:
`git clone  https://github.com/cypress-io/cypress-component-testing-apps/tree/main/vue3-vite-ts`
Replace the versions of "@vitejs/plugin-vue" and "vite" with "^3.0.0-beta.0"
`npm install`
`npx cypress open --component`
And you will be getting an error message.
![image](https://user-images.githubusercontent.com/53755/175043566-b2d7d455-c51c-4d73-be18-79c1f5f2f47c.png)

### Cypress Version

10.2.0

### Other

10.3.0

**Comment by lmiller1990** [comment]
Hey, thanks for pointing this out. I will look into Vite 3 support first thing next week.

**Comment by simcha** [comment]
Looks like it works with version 3.0.0-beta.7

**Comment by lmiller1990** [comment]
Nice!
