### ISSUE TITLE
@cypress/webpack-preprocessor: missing type dependencies and other type errors

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#22465]
### Current behavior

Reduced test case: https://github.com/OliverJAsh/cypress-10-ts-errors

This is a brand new Cypress project using the latest version of all libraries.

Run `yarn` and then `tsc`.

Result:

```sh-session
$ tsc
node_modules/@cypress/webpack-preprocessor/dist/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'webpack-dev-server'.

1 /// <reference types="webpack-dev-server" />
                        ~~~~~~~~~~~~~~~~~~

node_modules/@cypress/webpack-preprocessor/dist/index.d.ts:2:23 - error TS2688: Cannot find type definition file for 'webpack-dev-server-3'.

2 /// <reference types="webpack-dev-server-3" />
                        ~~~~~~~~~~~~~~~~~~~~

node_modules/@cypress/webpack-preprocessor/dist/index.d.ts:4:26 - error TS7016: Could not find a declaration file for module 'bluebird'. '/Users/oliverash/Development/temp/cypress-10-ts-errors/node_modules/bluebird/js/release/bluebird.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bluebird` if it exists or add a new declaration (.d.ts) file containing `declare module 'bluebird';`

4 import * as Promise from 'bluebird';
                           ~~~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/@cypress/webpack-preprocessor/dist/index.d.ts:1
```

I attempted to workaround these errors by installing some of the missing type dependencies: https://github.com/OliverJAsh/cypress-10-ts-errors/commit/0e602ffe9a4d89372e68c06e849d12fa32af23ff

However, now I have a different error:

```ts
$ tsc
cypress.config.ts:7:16 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"file:preprocessor"' is not assignable to parameter of type '"task"'.

7             on("file:preprocessor", webpackPreprocessor({}));
                 ~~~~~~~~~~~~~~~~~~~

  node_modules/cypress/types/cypress.d.ts:5521:5
    5521     (action: 'task', tasks: Tasks): void
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.

node_modules/@cypress/webpack-preprocessor/dist/index.d.ts:2:23 - error TS2688: Cannot find type definition file for 'webpack-dev-server-3'.

2 /// <reference types="webpack-dev-server-3" />
                        ~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  cypress.config.ts:7
     1  node_modules/@cypress/webpack-preprocessor/dist/index.d.ts:2
```

### Desired behavior

No type errors.

### Test code to reproduce

See above.

### Cypress Version

10.2.0

### Other

Related: https://github.com/cypress-io/cypress/issues/9570

**Comment by lmiller1990** [comment]
Hi!

I followed [the docs](https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfig-json) and got it to compile:

1. `tsconfig.json` in `cypress`
2. Contents:

```json
{
    "compilerOptions": {
        "moduleResolution": "Node",
        "outDir": "./target",
        "strict": true,
        "esModuleInterop": true,
        "types": ["cypress", "node"]
    }
}
```

Then I ran `yarn tsc -p cypress` and it compiled successfully (into a directory called `cypress/target`.

I'm kind of surprised your demo isn't working though - even if I add `types` to the top level `tsconfig.json`, I get the error, despite the types existing, eg `node_modules/cypress/types/bluebird/index.d.ts `.

**Comment by lmiller1990** [comment]
> Can you send me your test case so I can see how it compares to mine?

I copied pasted the `tsconfig.json` from [here](https://github.com/cypress-io/cypress/issues/22465#issuecomment-1165089201) into `cypress` then ran `yarn tsc --project cyperss`. I just realized it was not compiling `cypress.config.ts`, though - so actually, it's not type checking `cypress.config.ts`. :-1:, so disregard my initial comment.

I wonder if `webpack-preprocessor` even needs the `webpack-dev-server` (and `webpack-dev-server-3` types) at all. It doesn't [list those dependencies anywhere](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-preprocessor/package.json), so I think this is probably a bug in how we generate our types.

**Comment by OliverJAsh** [comment]
Note that once we fix the missing `bluebird` types I think we'll discover a different problem: https://github.com/cypress-io/cypress/issues/22465#:~:text=However%2C%20now%20I%20have%20a%20different%20error%3A

**Comment by lmiller1990** [comment]
I think we should try to solve all the typing issues (bluebird, webpack-dev-server (seems not needed)) in one shot.

**Comment by kevingorry** [comment]
@lmiller1990 when will this be addressed ?

**Comment by lmiller1990** [comment]
Not sure, I'm not able to prioritise this right now, unfortunately.

Another question that might help get some steam behind this: is there a compelling reason to type check `cypress.config.ts` at all? I only get these errors at compile time, not in my IDE. You don't actually need to even compile `cypress.config.ts` - definitely nice to have it type checked, but it should not block the general testing workflow, unless I'm missing something.

Happy to help facilitate some work around this if someone wants to pick it up.

**Comment by OliverJAsh** [comment]
> is there a compelling reason to type check `cypress.config.ts` at all?

To catch type errors in the config file. I want to be informed of any type errors in my application, no matter where they error, otherwise the wrong type at runtime could lead to obscure behaviour.

**Comment by OliverJAsh** [comment]
Also, if we don't type check this file and we only rely on type checking inside our editors, the next time someone opens it in their editor they might be surprised to find a type error left by someone else. We type check all files in our CI build to ensure that all files remain free of type errors so there are no nasty surprises.
