### ISSUE TITLE
Running multiple tests in the Cypress UI: we want this back!

### ISSUE THREAD

**Issue by dmolin** [cypress-io/cypress#22474]
### What would you like?

With previous versions of Cypress (9.x) it was possible to open the UI, filter the tests we were interested in and then "run" all those tests with a single click of a button.

With the new interface there's no possibility to select, as an example, an entire folder (or just the result of the search) and ask Cypress to "run" all those tests. that feature seems to have gone.

Can we have it back?

### Why is this needed?

Running multiple tests in the UI is a nice feature that was present before; I agree that we can still do the same from the command line but having them running visually is useful since if there's an error I can immediately look at each step; if done from the command line I would have to:

- take note of each individual test that failed
- open the Cypress UI and execute each one of them individually

**Comment by FrancoisCamus** [comment]
Yep! I just upgraded and that's the first thing I wanted to do. Where is the run all tests?

**Comment by dmolin** [comment]
> Yep! I just upgraded and that's the first thing I wanted to do. Where is the run all tests?

For me it's not even the biggest issue @FrancoisCamus : did you notice the issue with the search? https://github.com/cypress-io/cypress/issues/22463

**Comment by Benedict-Lojewski** [comment]
> Yep! I just upgraded and that's the first thing I wanted to do. Where is the run all tests?

Same thing here. It's a pain to test if all tests are running. Especially if you have more than 50 tests. CI works too but sometime you won't go to the screenshots folder to see the error happen. I wan't it real time and see when some code is broken or the sites crashes.

**Comment by dmolin** [comment]
don't tell me @Benedict-Lojewski ! We've more then 200 E2E tests here and we're just starting converting our old ones!

**Comment by mjhenkes** [comment]
Hey all, we definitely hear you and have a open discussion about this issue here. https://github.com/cypress-io/cypress/discussions/21628
