### ISSUE TITLE
Handle cross-origin document.cookie

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#22479]
The [cross-origin cookie handling](https://github.com/cypress-io/cypress/pull/22320) currently handles setting/getting cookies via http requests, but cookie setting/getting in-browser via `document.cookie` does not work if the AUT is on a different origin than top.

Need to monkey-patch `document.cookie` and override its setter and getter, so that it simulates what it would do if the AUT was run in the top frame.

**Comment by abin53** [comment]
Similar issue https://github.com/cypress-io/cypress/discussions/21509 But along with clearing cookie it takes other cookie attributes wrongly from other cookies present.
