### ISSUE TITLE
Address skipped tests in run_plugins_spec and run_spec in server package

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#22480]
All/most of the tests in the following files are disabled

https://github.com/cypress-io/cypress/blob/efede20d9ed1222139a68c4b6002d59abd872e8f/packages/server/test/unit/plugins/child/run_plugins_spec.js

https://github.com/cypress-io/cypress/blob/f669c101e13a40722b53e9556792b54dae9abbf2/packages/server/test/unit/modes/run_spec.js

We need to make sure that this coverage exists somewhere and if it doesn't create those tests and delete these ones. If the tests are completely irrelevant then they need to be deleted.

This issue resulted from [this PR](https://github.com/cypress-io/cypress/pull/22356)

**Comment by jennifer-shehane** [comment]
These tests have been unskipped since this was opened.
