### ISSUE TITLE
Address skipped tests in project_spec in server package

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#22487]
All/most of the tests in the following file are disabled

https://github.com/cypress-io/cypress/blob/e7efc10aed0156ce48d85507f3c4f60063f069cb/packages/server/test/unit/project_spec.js#L25%7Csmart-link

We need to make sure that this coverage exists somewhere and if it doesn't create those tests and delete these ones. If the tests are completely irrelevant then they need to be deleted.

This issue resulted from https://github.com/cypress-io/cypress/pull/22356

**Comment by jennifer-shehane** [comment]
This test has been unskipped since this was opened: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/unit/project_spec.js#L25%7Csmart-link
