### ISSUE TITLE
Visits with a hash (#) where you are visiting the same base url will not navigate.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#225]
Back to back `cy.visit` where the url contains a hash (#) and you are visiting the same base url (before the hash) does not navigate to the 2nd url.

This is a regression introduced in [`0.17.2`](https://github.com/cypress-io/cypress/wiki/changelog#0172-09062016), specifically the commits relating to "No longer forcing `cy.visit` to navigate to `about:blank` prior to navigating to the real url." to fix Issue #208.

**Example Code**
```javascript
describe("user", function() {
  it("visits user page", function() {
    cy.visit("http://localhost:8484/#/users/7832")
  });
  it("visits user page again", function() {
    cy.visit("http://localhost:8484/#/users/7832")
  })
})
```

**Command Log**
![screen shot 2016-09-12 at 4 33 59 pm](https://cloud.githubusercontent.com/assets/1271364/18451886/c6a335a8-7906-11e6-8ead-d93a7e8950fc.png)

**Comment by brian-mann** [comment]
Fixed in [`0.17.4`](https://github.com/cypress-io/cypress/wiki/Changelog#0174-09112016).
