### ISSUE TITLE
trigger a function after video processing

### ISSUE THREAD

**Issue by tahayk** [cypress-io/cypress#2250]
I'm running Cypress in a Docker container, and I'm trying to fetch as much infos as possible about the executed test before closing the container.
So I created a plugin that will upload the screenshots & videos to S3 after the execution of the test, this plugin is triggered by the `after` hook.
but I noticed that the uploaded video is the un-processed/un-compressed video.
is there any way to trigger the video upload after the processing is finished ? 
PS: I tried to put a listener on the `exit` event so it can upload the video before closing the application, but it didn't work for me.
this is a preview of the code I wrote:
- the hook:
```js
after(function () {
    cy.task('endMySession', null, {"log": false, "timeout": 180000});
});
```
- the plugin:
```js
module.exports = (on, config) => {
    // `on` is used to hook into various events Cypress emits
    // `config` is the resolved Cypress config

    on('task', {
        'endMySession': (args) => {
            let promises = [];

            promises.push(new Promise(function (resolve, reject) {
                fs.readdir("./cypress/videos", (err, files) => {
                    if (err) {
                        return reject(err);
                    }
                    files.forEach((file,i) => {
                        promises.push(new Promise(function (resolve, reject) {
                            console.log("uploading " + file);
                            uploadFileToS3('my-video-bucket', "./cypress/videos/" + file, function (err, data) {
                                if (err) {
                                    console.log('error uploading ' + file);
                                    return reject(err);
                                }
                                console.log('uploaded ' + file);
                                resolve();
                            });
                        }));
                    resolve();
                    });
                })
            }));
            return Promise.all(promises);
        },
    });
};
```

**Comment by mjhea0** [comment]
@tahayk why did you decide to use a plugin for this?

I implemented this by just grabbing all files in the "cypress/screenshots/" and "cypress/videos/" directories *after* the test run and uploading them to S3 then.

**Comment by tahayk** [comment]
@mjhea0 thank you for your answer,
yeah, I thought about the same solution, to execute a second command after the test, but I left it as a last resort.
I'm trying to do that inside a plugin because I've created a plugin that collects all the available data about each test (for reporting purposes) and uploads it to S3 (the code I posted is the simplified version of the plugin), so I want to do the same thing for videos, that way I have to maintain only 1 part.

**Comment by mjhea0** [comment]
@tahayk 

I'm going to try porting the following gist over to a plugin today and see how to get around the race condition with the compression.

https://gist.github.com/mjhea0/d84584e3a2bbd695b4b37164e33becbf

**Comment by jennifer-shehane** [comment]
You should also be able to do this from within the Module API, since it returns the videos after a run. https://on.cypress.io/module-api

**Comment by mjhea0** [comment]
@tahayk since there's not an [event](https://docs.cypress.io/api/events/catalog-of-events.html#Cypress-Events) or lifecycle method that gets triggered after the screenshots are processed, I would stick with the Module API as @jennifer-shehane suggested.  I put a basic repo together here -> https://github.com/testdrivenio/cypress-s3-upload.

It's worth noting that there is an `test:after:run` event, but I had trouble getting it to work. https://github.com/cypress-io/cypress/issues/2271
