### ISSUE TITLE
Migration issue - While trying to migrate V10

### ISSUE THREAD

**Issue by gmashokkumargm** [cypress-io/cypress#22504]
### Current behavior

When I click on continue to cypress 10, it just keeps loading the migration helper page.

### Desired behavior

Cypress should let me know the changes in the config file. 

### Test code to reproduce

Update cypress from V7 to V10
Run: npx cypress open
Click continue to cypress 10

### Cypress Version

10.2.0

**Comment by gmashokkumargm** [comment]
<img width="1219" alt="Screenshot 2022-06-24 at 2 15 15 PM" src="https://user-images.githubusercontent.com/68268604/175500095-81cd7f12-09c7-4afd-af70-a93d01c00858.png">

**Comment by mjhenkes** [comment]
@gmashokkumargm, could you provide your cypress.json?

**Comment by gmashokkumargm** [comment]
Hello @mjhenkes, Here it is 

{
  "baseUrl": "http://localhost:8080/#/",
  "integrationFolder": "cypress/flows/",
  "pluginsFile": "cypress/tasks/",
  "fixturesFolder": "assets",
  "reporter": "list",
  "taskTimeout": 90000,
  "viewportWidth": 1280,
  "defaultCommandTimeout": 20000
}

**Comment by lmiller1990** [comment]
@gmashokkumargm Hi! The issue might be how you are specifying `pluginsFile` in your config - it looks like your pointing to a folder with an `index.js`. This technically worked in Cypress 9, but it's ideal to point to a file - it's `pluginsFile`, as opposed to `pluginsFolder`.

I tried to patch this in 10.3.0, so you could try upgrading. An alternative would be to change your config to point to the `pluginsFile` - so ` "pluginsFile": "cypress/tasks/index.js"`, in this case, most likely.

I'd also generally recommend updating to Cypress 9 before attempting to migrate, but let's try the `pluginsFile` fix. If that doesn't help, try running the migration with `DEBUG=cypress:* npx cypress ...`. This will enable debug logs, which you can copy-paste here. That'll help with debugging.

Let me know how you go!

**Comment by gmashokkumargm** [comment]
@lmiller1990 Thank you very much for your comment, By the way, I updated everything manually instead of going through the migration and it works perfectly fine with the new version.
