### ISSUE TITLE
Command Line Arguments --env and --config do not override config files

### ISSUE THREAD

**Issue by briggsge** [cypress-io/cypress#22516]
### Current behavior

From Cypress 8.6.0 to 9.7.0, the following command line execution would override cypress.env.json and cypress.json variables

```
npx cypress run --env environment_url="https://deployed.nonprod.env",environment_name="stg",state="nv",application="app", --config defaultCommandTimeout=15000 --spec cypress/integration/specs/users/availability/roles-login.spec.js --headed
```

Since Cypress 10.x, the same command does not override the cypress.env.json file, but the config file is read in to the new Cypress.config.js file correctly since I set  ```config.env = JSON.parse(fs.readFileSync('./cypress.env.json'));``` in the e2e object.. Specifically, two issues occur:

1. --env is not overriding the cypress.env.json file 
2. defaultCommandTimeout=15000 is not functioning in the same manner. There are no other --config variables I need to set so I have not validated if any are read correctly or if it is just this this particular setting having issues.

### Desired behavior

Have the same behavior for --env and --config command line arguments as what existed pre-version 10.

### Test code to reproduce

1=1 // apologies, but want this to get out and I'll update later. 

### Cypress Version

10.2.0

**Comment by tbiethman** [comment]
@briggsge thank you for the report. We have a [couple](https://github.com/cypress-io/cypress/issues/22245) [issues](https://github.com/cypress-io/cypress/issues/22430) logged around the cli/config precedence; I'm going close this en lieu of those.
