### ISSUE TITLE
[Angular] Jest tests fail after updating to Cypress 10.2.0

### ISSUE THREAD

**Issue by rdogmartin** [cypress-io/cypress#22512]
### Current behavior

After updating from Cypress 9.7.0 to Cypress 10.2.0 in my Angular app, my jest tests are unable to resolve interfaces defined in the cypress folder.

I created the simplest possible repo that shows the issue. It's an empty Angular 14 app with jest 28.1.1 and Cypress 9.7.0.  The jest tests work until you update to Cypress 10.2.0.

### Desired behavior

Upgrading to Cypress 10.2.0 should not break existing jest tests.

### Test code to reproduce

1. Clone this repo: https://github.com/rdogmartin/ang14
2. Run `npm test` and confirm the single jest test passes.
3. Upgrade Cypress: `npm install cypress@latest -D`
4. Run `npm test` and notice the jest test now fails: `Cannot find module 'cypress/bank.fixture' from 'src/app/app.component.spec.ts'`

### Cypress Version

10.2.0

### Other

I spent quite a bit of time playing with the configuration to try to get the jest tests to "see" the interface in the cypress folder but couldn't get it. It's possible this issue can be solved with a config change and is not a bug with cypress. Hoping the community might be able to see what I'm missing.

**Comment by tbiethman** [comment]
@rdogmartin thank you for the report. I can reproduce this using the repo you provided.

**Comment by rdogmartin** [comment]
I can confirm the issue is still happening with Cypress 12.12.0. Note that I had to make sure I was using node 18.16.0 rather than 19.x (got an error "the service was stopped" with node 19.x).

This issue has blocked our ability to upgrade Cypress, so I hope the team is able to investigate.
