### ISSUE TITLE
Cypress 10 | SASS Global Style File Imports Within Next.js - Unable To Run Cypress Component Test

### ISSUE THREAD

**Issue by Sayvai** [cypress-io/cypress#22525]
### Current behavior

After launching Cypress Component Test application for the `Next.js` project, and importing multiple SASS (`.scss`) files from within the `cypress/component.ts` file, then i am unable to run a defined component test within the file `news-aggregator-article.cy.tsx` (link to [file](https://github.com/Sayvai/nextjs-playground/blob/cypress-integration/components/news-aggregator/news-aggregator-article.cy.tsx) on repo). On the test rendering panel, only the text `Cannot GET /__cypress/src/index.html` is rendered out.

See the highlighted screenshot below:
![cypress-10_import-scss_unable-to-run-component-test](https://user-images.githubusercontent.com/7581546/175823515-7201cae6-3aae-46c8-801f-d7abab54cfac.png)

Is it not currently possible to import / support SASS style files for component testing? Or am i missing a step? 🤔 

If SASS imports are currently not supported, are you able to advise or recommend how I may be able to render the styles within the component test?

> **Warning** - The component test will successfully run (without SASS styles) if the imported SASS (`.scss`) files are removed from within the `cypress/component.ts` file.

> **Note** - This is a Next.js project that was initially scaffolded via `npx create-next-app`, and then configured to use SASS afterwards (`npm install --save-dev sass`).

### Desired behavior

The component test should run within the Cypress Component Test application window, as well as successfully importing and rendering the styles defined within the SASS files (`.scss`)

### Test code to reproduce

You may reproduce the issue by cloning the project from the repo; [nextjs-playground](https://github.com/Sayvai/nextjs-playground), and then checkout the branch; `cypress-integration`

The relevant code files are listed below.

file: `component.ts`:

```js
...
import '../../styles/globals.scss'
import '../../styles/Index.module.scss'
import '../../components/news-aggregator/news-aggregator-article.module.scss'
...
```
file: `news-aggregator-article.cy.tsx` (component test):

```js
import NewsAggregatorArticle from "./news-aggregator-article"

describe('news-aggregator-article.tsx', () => {
  it('should render with article data', () => {
    // given
    const article = {
      id: 15547,
      title: 'InSight teams push for more science in lander’s final months, Curiosity continues trek around Gale Crater',
      url: 'https://www.nasaspaceflight.com/2022/06/insight-curiosity-june-2022/',
      imageUrl: 'https://www.nasaspaceflight.com/wp-content/uploads/2022/06/jpegPIA25287-1170x702.jpeg',
      summary: 'In May 2022, members of NASA’s InSight Mars lander team announced that power levels on the lander were diminishing and that they expected the lander to become inoperative by December 2022. However, InSight’s teams want to push the lander to do as much as possible in its final months and have chosen to operate the lander’s seismometer for longer than previously planned.',
      publishedAt: '2022-06-25T16:42:33.000Z',
      updatedAt: '2022-06-25T19:27:56.825Z',
      newsSite: 'Space Fight News',
      featured: false,
      launches: [
        {
            id: 'df8d4fdb-9add-4ce9-9f0e-aae1c61df212',
            provider: 'Launch Library 2'
        },
        {
            id: '3b633f7e-fad9-480e-9011-f38d1bb2f932',
            provider: 'Launch Library 2'
        }
      ],
      events: [],
  }

    cy.mount(<NewsAggregatorArticle article={article} />)
  })
})
```

### Cypress Version

10.2.0

**Comment by lmiller1990** [comment]
Import scss definitely works, I do it in some projects. We also have tests with Next.js that do it, eg: https://github.com/cypress-io/cypress/tree/develop/system-tests/project-fixtures/next (there is `Home.module.scss`).

I will look into this. Thanks for sharing a reproduction, that's really useful.

**Comment by fazo96** [comment]
We are having what I think is the same issue. Same error message inside cypress, and the terminal output shows this:

```
ERROR in ./app/components/AnimBox.module.css
No template for dependency: ModuleHotAcceptDependency
```

Repeated for every component that is loaded. We don't use SASS, but we have a couple global css imports in the style of `import './file.css'` plus Next.js CSS modules.

Currently we are using Cypress 9 and @cypress/react version 5 which are working correctly. Upgrading to Cypress 10 and @cypress/react 6 is causing this issue. Next.js version is 12.1.5, I tried upgrading to Next.js 12.2.0 but no change.

**Comment by fazo96** [comment]
Not sure what I did, but now all of a sudden it works again

**Comment by lmiller1990** [comment]
Having a look now, I ran the reproduction and got:

```
$ npx cypress open --component                              cypress-integration
[45804:0711/110922.230761:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[45958:0711/110922.277430:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[45958:0711/110922.305290:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
[@cypress/webpack-dev-server]: removing HotModuleReplacementPlugin from configuration.
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/lachlan/code/dump/nextjs-playground/public' directory
15 assets
90 modules

ERROR in ./styles/globals.scss
Module Error (from ./node_modules/next/dist/build/webpack/loaders/error-loader.js):
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: cypress/support/component.ts

ERROR in ./styles/globals.scss
Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String
    at processResult (/home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:49230:17)
    at /home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:49316:5
    at /home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:139505:3
    at iterateNormalLoaders (/home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:139331:10)
    at iterateNormalLoaders (/home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:139338:10)
    at /home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:139353:3
    at runSyncOrAsync (/home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:139236:12)
    at iterateNormalLoaders (/home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:139349:2)
    at /home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:139322:4
    at /home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:49290:15
    at eval (eval at create (/home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:14:1)
    at Array.<anonymous> (/home/lachlan/code/dump/nextjs-playground/node_modules/next/build/webpack/plugins/profiling-plugin.ts:154:15)
    at runCallbacks (/home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:134035:15)
    at /home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:134208:4
    at /home/lachlan/code/dump/nextjs-playground/node_modules/next/dist/compiled/webpack/bundle5.js:14502:16
    at /home/lachlan/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at /home/lachlan/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

Cannot proceed:

![image](https://user-images.githubusercontent.com/19196536/178170818-a7b1ebc7-ab27-4a60-80fc-817de0abb9f8.png)

**Comment by lmiller1990** [comment]
@Sayvai no problem - we will need to do a hack, but it'll be in the Cypress code base, so you don't need to.

I'm pretty swamped, I am not sure if I can do this during the next week or two, but I marked this as "ready for work" so someone at Cypress (or external, if someone is keen) wants to pick it up.

If anyone outside Cypress wants to take a stab, ping me and I can point you in the right direction.

**Comment by ZachJW34** [comment]
I have an open [PR](https://github.com/cypress-io/cypress/pull/22769) to remove the global style restrictions that Next enforces.

**Comment by Sayvai** [comment]
@ZachJW34 - Thank you very much for applying the underlying configuration enhancement 🙌 

I hope to test your changes at some point tomorrow, and will report back the status of your changes here 🤞
