### ISSUE TITLE
`cy.visit`: provide access to response

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#22520]
### What would you like?

I want to write a test that visits a URL and checks two things:

1. Did the response have a specific status code?
1. Did the rendered page include some text?

Unfortunately it seems `cy.visit` doesn't provide access to the response so I can't check the status code. I would need to make another request using `cy.request`, meaning I'd be making 2 requests for the same URL: one with `cy.visit` and another one with `cy.request`.

For this reason I think `cy.visit` should provide access to the response.

**Comment by GCHQDeveloper638** [comment]
This feature would be useful to us - we're trying to do similar to @OliverJAsh and assert that the returned page had a specific status code before we check the contents of the page.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest, we’ll close this as not planned.
