### ISSUE TITLE
cy.click() fails on 'illegal invocation' error after updating to 3.0.3

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#2252]
### Current behavior:

After update to 3.0.3, cypress started throwing errors on previously passing tests:

![snimka obrazovky 2018-08-01 o 10 11 20](https://user-images.githubusercontent.com/23213553/43509637-7cbf7484-9573-11e8-94ed-2018bf42ca07.png)

Works fine after downgrading to 3.0.2. 

### Desired behavior:

No reason to fail. Element is visible, actionable and works.

### Steps to reproduce:

You can run this code to replicate:

```js
describe('Replicate cypress bug', () => {

  beforeEach(() => {
			
    cy
      .server()
      .route({
        method: 'POST',
        url: `/api/v0.5/events/*/questions/*/like`
      }).as('likeSend');

    cy
      .clearLocalStorage();

  });

  it('Should be able to like a question', () => {

    cy
      .visit('https://app2.sli.do/event/ylzdusae');

    // click on like
    cy
      .get('.score--card [ng-bind=\'$ctrl.getScorePositive()\']')
      .get('.score--card button.score__btn--plus')
      .click();

    // like should be sent through api
    cy
      .wait('@likeSend')
      .its('status')
      .should('eq', 200);					
        
    // see like appear
    cy
      .get('.score--card [ng-bind=\'$ctrl.getScorePositive()\']')
      .get('.score--card button.score__btn--plus')
      .should('have.class', 'active');
      
  });
  
});
```

### Versions

3.0.3., Behavior is replicable on CI, Desktop or headless run. Downgrading back to 3.0.2 aids the issue.

**Comment by rgkeith3** [comment]
I was also experiencing this.
changing `.click()` to `.trigger('click')` seemed to work in some situations, but obviously not a good workaround.

switching back to 3.0.2 works

**Comment by jennifer-shehane** [comment]
This issue has been fixed and will go out in our next release. https://github.com/cypress-io/cypress/pull/2246
