### ISSUE TITLE
BeforeEach hook is executed several times (for each data set) before each test in the spec with data provider.

### ISSUE THREAD

**Issue by kzahozhy** [cypress-io/cypress#22533]
### Current behavior

I've noticed  that when I have spec file  with several data sets provided the beforeEach hook is executed several times - for each dataset - before each test in each data set run. 
So if we have dataset 1 and dataset2 and test1 and test2 then we have following order of execution:
beforeEach for dataset1 -> beforeEach for dataset2 -> test1
beforeEach for dataset1 -> beforeEach for dataset2 -> test2

### Desired behavior

I would expect beforeEach hook to run only once before each test in every dataset run:
beforeEach for dataset1 -> test1
beforeEach for dataset2 -> test2.

### Test code to reproduce
```js
describe('Subdomains', () => {
    const urlToLogoSelector = {
        'https://docs.cypress.io': 'img[alt="Cypress Docs Logo"]',
        'https://www.cypress.io': 'img[alt="Cypress.io"]',
    }

    const urls = Object.keys(urlToLogoSelector)

    urls.forEach((url) => {

        beforeEach(() => {
            cy.visit(url);
        })

        it(`Should display logo on ${url}`, () => {
            const selector = urlToLogoSelector[url]
            expect(selector, `logo selector for ${url}`).to.be.a('string')
            cy.get(selector).should('be.visible')
        })
    })
})
```
### Cypress Version

9.6.1

**Comment by Benedict-Lojewski** [comment]
Just move the visit inside, because you create dynamic tests. Therefore you don't need a beforeEach.

```javascript
const urls = Object.keys(urlToLogoSelector)

urls.forEach((url) => {
    it(`Should display logo on ${url}`, () => {
        cy.visit(url); // moved inside
        const selector = urlToLogoSelector[url]
        expect(selector, `logo selector for ${url}`).to.be.a('string')
        cy.get(selector).should('be.visible')
    })
})
```

**Comment by kzahozhy** [comment]
This is is just an example code to reproduce the problem. The real project code needs separate beforeEach()

**Comment by emilyrohrbough** [comment]
@kzahozhy, the behavior you are describing is correct. This is a result of how you are trying to create your dynamic tests.

To break down the problem a little so you understand why this is happening, before the test execution starts, your spec file is parsed to determine what hooks and suites and tests exists in the file to determine what needs to be executed. For the example you provided, you are looping the urls, however you aren't associated the hooks to a new suite, so they are associated with the current-level suite, which is why you are seeing multiple `beforeEach()` hooks for each test. The runner views your example like:

```js
suite - spec_name
  suite - "subdomains"
     beforeEach - https://docs.cypress.io
     beforeEach - https://www.cypress.io
     test - Should display logo on https://docs.cypress.io
     test - Should display logo on https://www.cypress.io
```

@Benedict-Lojewski's suggest is one option for solving the issue you are seeing.

An alternative is to associate each data set with it's own suite:
```diff
describe('Subdomains', () => {
    const urlToLogoSelector = {
        'https://docs.cypress.io': 'img[alt="Cypress Docs Logo"]',
        'https://www.cypress.io': 'img[alt="Cypress.io"]',
    }

    const urls = Object.keys(urlToLogoSelector)

    urls.forEach((url) => {
+       describe(url, () => {
            beforeEach(() => {
                cy.visit(url);
            })

            it(`Should display logo on ${url}`, () => {
                const selector = urlToLogoSelector[url]
                expect(selector, `logo selector for ${url}`).to.be.a('string')
                cy.get(selector).should('be.visible')
            })
        })
+   })
})
```

**Comment by kzahozhy** [comment]
@emilyrohrbough Thank you so much for your code example! This is what I need.
