### ISSUE TITLE
Bundled Node Version 8.2 is too old

### ISSUE THREAD

**Issue by Mikuu** [cypress-io/cypress#2253]
Any plan to upgrade the Cypress bundled node version to latest v8.11? The currently bundled version 8.2 is too old to prevent us easily create more useful plugins.

**Comment by bahmutov** [comment]
Yes good idea, we should do this. Can you make a pull request?

**Comment by brian-mann** [comment]
The bundled version of node comes from `Electron`. There is a newer update out, but we've been waiting for `3.0.0` to drop, which will upgrade Chromium and other things that are blockers for us on other features.

There's no way to upgrade node independently of that.

**Comment by mhelvens** [comment]
Eagerly waiting for this, especially now that `cy.task` is a thing.

Is there a workaround that would let me import a module that uses object spread notation? For example, can I use my own Node version, rather than the bundled one, or can I make Cypress pass the `--harmony` flag to Node 8.2?

**Comment by Jaemu** [comment]
`3.0.0` dropped two weeks ago, currently on `3.0.2` according to https://electronjs.org/releases

Is someone actively working on the electron upgrade?

**Comment by jennifer-shehane** [comment]
@Jaemu Yes. https://github.com/cypress-io/cypress/issues/3568
