### ISSUE TITLE
Cypress 10 version : Unable to give the snapshots for failed test cases in mocha report folder: The report is getting successfully saved but the snapshots are not appended  

### ISSUE THREAD

**Issue by M-Jyothi** [cypress-io/cypress#22549]
### Current behavior

Package.json
[12:06] Parimal Unde
"devDependencies": {
    "cypress": "^10.1.0",
    "cypress-file-upload": "^5.0.8",
    "cypress-mochawesome-reporter": "^3.1.0",
    "cypress-xpath": "^1.6.2",
    "mocha": "^10.0.0",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.2.1"
  },
  "dependencies": {
    "cypress-multi-reporters": "^1.6.1",
    "mochawesome-report-generator": "^6.2.0"
  }

cypressconfig .js 

======================
 reporter: "cypress-multi-reporters",
  reporterOptions: {
    reporterEnabled: "mochawesome",
        "mochawesomeReporterOptions": {
            "reportDir": "cypress/reports/mocha",
            "screenshotOnRunFailure": true,
            "quite": true,
            "overwrite": true,
            "html": true,
            "json": true,
            "embeddedScreenshots": true,
            "cypress-mochawesome-reporter": "[https://github.com/Venkateshkumar1234/cypress-mochawesome-reporter/tarball/refs/heads/master"](https://github.com/Venkateshkumar1234/cypress-mochawesome-reporter/tarball/refs/heads/master%22)
         }
    },
  screenshotsFolder: "cypress/reports/html/screenshots",

### Desired behavior

Expected the snapshot to get appended for failed test cases 

### Test code to reproduce

Package.json
[12:06] Parimal Unde
"devDependencies": {
    "cypress": "^10.1.0",
    "cypress-file-upload": "^5.0.8",
    "cypress-mochawesome-reporter": "^3.1.0",
    "cypress-xpath": "^1.6.2",
    "mocha": "^10.0.0",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.2.1"
  },
  "dependencies": {
    "cypress-multi-reporters": "^1.6.1",
    "mochawesome-report-generator": "^6.2.0"
  }

cypressconfig .js 

======================
 reporter: "cypress-multi-reporters",
  reporterOptions: {
    reporterEnabled: "mochawesome",
        "mochawesomeReporterOptions": {
            "reportDir": "cypress/reports/mocha",
            "screenshotOnRunFailure": true,
            "quite": true,
            "overwrite": true,
            "html": true,
            "json": true,
            "embeddedScreenshots": true,
            "cypress-mochawesome-reporter": "[https://github.com/Venkateshkumar1234/cypress-mochawesome-reporter/tarball/refs/heads/master"](https://github.com/Venkateshkumar1234/cypress-mochawesome-reporter/tarball/refs/heads/master%22)
         }
    },
  screenshotsFolder: "cypress/reports/html/screenshots",

### Cypress Version

cypress 10

**Comment by M-Jyothi** [comment]
Screenshots are available at the location but not appended in the report

**Comment by tbiethman** [comment]
@M-Jyothi thank you for the report. I see that [cypress-mochawesome-reporter](https://github.com/LironEr/cypress-mochawesome-reporter) released a 3.2.0 version recently that included cypress v10 support. Can you confirm that you're installing that version and that you've gone through the updated setup steps on the README? Providing a minimal reproduction would also be helpful in determining any issues present in the config or Cypress itself.

**Comment by tbiethman** [comment]
Unfortunately we have to close this issue due to inactivity. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
