### ISSUE TITLE
Cypress migration tool doesn't appear + stack trace in the console

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#22544]
### Current behavior

I'm currently following the instructions in the migration video and even the simplest steps aren't working. I upgraded from version 9 to version 10.2.0 and ran `npx cypress open`, as instructed. The migration video says that the migration helper will appear in the window, but it does not. Instead, I see the "Configuration Files" screen.

Also, there is a stack trace in the console:

```
$ npx cypress open
It looks like this is your first time using Cypress: 10.2.0

[STARTED] Task without title.
[TITLE]  Verified Cypress! C:\Users\Kyle Getz\AppData\Local\Cypress\Cache\10.2.0\Cypress
[SUCCESS]  Verified Cypress! C:\Users\Kyle Getz\AppData\Local\Cypress\Cache\10.2.0\Cypress

Opening Cypress...

node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module 'C:\Users\Kyle'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:785:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1292:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:486:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:77:3)
    at node:internal/main/run_main_module:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

It looks like Cypress is trying to access something in my home directory, but is failing when encountering a directory with spaces in it, which is pretty common in Windows. Was the new version of Cypress not tested on Windows at all?

### Desired behavior

No stack trace and I should see the migration tool in the window.

### Test code to reproduce

Upgrade from version 9 to version 10 on Windows.

### Cypress Version

10.2.0

**Comment by lmiller1990** [comment]
I thought we had resolved the "spaces in username" issue but apparently not.

I will fix this right now and hopefully this can get into the release in the next 24 hours. I'm sorry you encountered this problem.

Dup: https://github.com/cypress-io/cypress/issues/22297#issuecomment-1167898416

**Comment by lmiller1990** [comment]
Should be fixed in https://github.com/cypress-io/cypress/pull/22550
