### ISSUE TITLE
Released in [`7.2.0`](https://on.cypress.io/changelog#7-2-0).

### ISSUE THREAD

**Issue by yechezkela** [cypress-io/cypress#22558]
I'm trying to change my headers with cy.intercept with cypress, when I enter English entries everything's fine, But when I try to enter Hebrew entries I get: **"> Error: socket hang up"**

For example:

**Working**`:headers:{ lastname:"shalom"}
`
**Not working**:` headers:{ lastname:'שלום'}`

The file is encoded by utf-8, I tried everything and nothing works, If anyone can help me I would be very happy

I think its the same problem like this issue https://github.com/cypress-io/cypress/issues/15901 

I'm using cypress 9.5.1

**Comment by mjhenkes** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please open a new issue with the required information from our issue template.

**Comment by yechezkela** [comment]
Hi,
The links of the issue template
<https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md>
   and contributing guidelines
<https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template>
are
broken.

‫בתאריך יום ד׳, 29 ביוני 2022 ב-0:45 מאת ‪Matt Henkes‬‏ <‪
***@***.***‬‏>:‬
