### ISSUE TITLE
Migration helper is not renaming test files correctly

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#22573]
### Current behavior

The migration tool claims it will rename `spec` to `cy`, but that is not appearing in the window. For starters, see that I've enabled that setting:

![image](https://user-images.githubusercontent.com/10719780/176275456-9d8783bd-9df4-49b9-b3f6-0a4449b0591a.png)

But when I scroll down, only the directory is being renamed, and the files are not:

![image](https://user-images.githubusercontent.com/10719780/176275615-6b7bed73-27d4-4b41-85f9-7c011810430d.png)

### Desired behavior

According to the migration video, the filenames are supposed to be renamed from `spec` to `cy`.

### Test code to reproduce

Upgrade from version 9 to version 10 on Windows 10.

### Cypress Version

10.3.0

**Comment by lmiller1990** [comment]
Hi! Are you able to share your `cypress.json`? We do have some logic to not rename spec extensions if you've customized them via `testFiles`. In this case, we should not show a misleading message.

Please share your `cypress.json` (and any other relevant info) - I'll try to reproduce and look into this.

**Comment by kaiyoma** [comment]
@lmiller1990 Sure, here it is:

```
{
  "integrationFolder": "cypress/integration",
  "numTestsKeptInMemory": 0,
  "pageLoadTimeout": 300000,
  "reporter": "mochawesome",
  "reporterOptions": {
    "html": false,
    "json": true,
    "overwrite": false
  },
  "taskTimeout": 120000,
  "testFiles": "**/*.spec.js",
  "trashAssetsBeforeRuns": false,
  "video": true,
  "viewportHeight": 1080,
  "viewportWidth": 1920
}
```

Should I drop `testFiles` from my config? Anything else in there that we should remove or modify?

**Comment by lmiller1990** [comment]
Hi @kaiyoma!

Basically, if you have a custom `testFiles`, we assume you do **not** want our recommended `.cy.js` extension, so we leave it alone. We just migrate the `integration` -> `e2e` part. If you continue with the migration, it should create a new `cypress.config.js` automatically setting your `specPattern` to `cypress/e2e/**/*.spec.js`, which is the combination of the deprecated `integrationFolder` + `/` + `testFiles` configuration.

Does this make sense? You configuration looks pretty standard, so it should work just fine and move you from `cypress.json` to `cypress.config.js` without any manual changes.

**Comment by kaiyoma** [comment]
Okay, it sounds like I should remove `integrationFolder` and `testFiles` from my Cypress config, since our values are the same as the default values. I tried that and opened the migration tool, and now I'm seeing a new bug: the tool is incorrectly applying the rename to all files, including non-test files. You can see the bug here:

![image](https://user-images.githubusercontent.com/10719780/176483038-5cf39248-76bf-4140-b7ce-662c738f2166.png)

The red circles are files that should not have been renamed, because they aren't test files and they don't have `spec` in the name. The green circles are files that should be renamed.

**Comment by mjhenkes** [comment]
This is highlighting an issue with cypress 9 where our glob pattern was too open ended, the migration tool can't determine what is a test file vs what is not a test file. This is why we've created the naming convention in cypress 10. Were you able to upgrade despite this issue?
