### ISSUE TITLE
[9.5.0]Bug: cy.intercept does not accept Hebrew letters within headers values

### ISSUE THREAD

**Issue by yechezkela** [cypress-io/cypress#22585]
### Current behavior

The code includes GET request with Hebrew characters that i plant in req headers:

`cy.intercept({ url: '', middleware: true }, (req) => {
            req.headers['hebName'] = 'אא';
            req.headers['hebLastName'] = 'Cohen';
        }).as('headers');`

and falls in `cy.visit()`
with this error:

**
We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: socket hang up

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer**

But if I use English characters everything is fine and the test keeps running :
`cy.intercept({ url: '', middleware: true }, (req) => {
            req.headers['hebName'] = 'aa';
            req.headers['hebLastName'] = 'Cohen';
        }).as('headers');`

### Desired behavior

test needs to keep running like it does in english cahracters.

### Test code to reproduce

Sorry, I'm working with classified information running on a special network, I can not share the code, and even if it does, it will not work because the application is on a classified and special network, please do not close my issue beacuse it is a real issue, just try to implement hebrew letters in req headers please

### Cypress Version

9.5.0

### Other

OS : windows 10
node version: latest

I think its related to https://github.com/cypress-io/cypress/issues/15901

**Comment by chrisbreiding** [comment]
I was able to reproduce this with the following:

```js
it('hebrew header value', () => {
  cy.intercept({ url: 'http://jsonplaceholder.typicode.com/posts/1', middleware: true }, (req) => {
    req.headers['hebName'] = 'אא'
  })

  cy.visit('/html/post.html') // errors here with 'Failed to fetch' 
  cy.get('h1').invoke('text').should('include', 'sunt aut facere')
})
```

where `/html/post.html` is:

```html
<h1 id="post"></h1>
<script>
  fetch('http://jsonplaceholder.typicode.com/posts/1')
  .then((res) => res.json())
  .then((post) => document.getElementById('post').textContent = post.title)
</script>
```

I didn't get a socket hangup since I can't completely reproduce your setup, but it resulted in a `Failed to fetch` error. The error no longer occurred if I changed the value to non-hebrew characters, so I feel fairly confident it's the same issue.

As far as I can tell, [only a limited number of characters are valid in an http header value](https://www.theburningofrome.com/helpful-tips/what-characters-are-allowed-in-http-header-values/). Encoding the header value will fix the issue:

```js
it('hebrew header value (encoded)', () => {
  cy.intercept({ url: 'http://jsonplaceholder.typicode.com/posts/1', middleware: true }, (req) => {
    req.headers['hebName'] = encodeURIComponent('אא')
  })

  cy.visit('/html/post.html')
  cy.get('h1').invoke('text').should('include', 'sunt aut facere') // passes!
})
```
