### ISSUE TITLE
Spec data request batching

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#22599]
### What would you like?

Spec data request batching

Current behavior queries each spec row individually - this is the most responsive option (data shows up as quickly as possible for each individual row) but has potential load concerns on the backend (no opportunity to batch DB queries, lots of simultaneous small requests)

Ideally we can batch up the individual requests prior to dispatch in the GQL layer so a single query can be executed for a configurable "batch" of requests (5, 10, 25, etc). Need to balance the batch size against maintaining responsive UI (having a huge batch size might be more performant on the backend but makes UI show "empty" state for longer as it waits for the entire batch to resolve)

### Why is this needed?

* Reduce number of individual queries sent to backend, provide opportunity for backend to optimize queries across specs

### Other

Tim has an open PR to address this: #22457

**Comment by lmiller1990** [comment]
Closed in https://github.com/cypress-io/cypress/pull/22457
