### ISSUE TITLE
Do not enforce spec path in screenshot path

### ISSUE THREAD

**Issue by sharmarahul** [cypress-io/cypress#2259]
### Current behavior:

At present, when the `cy.screenshot('image.png')` is called, it saves the screenshot within the screenshotFolder with directories auto created relative to where the spec resides. Having the `spec_name.js` directory inserted into the screenshots folder creates issues when these screenshots need to be read for example for screenshot diffing with a base image as the screenshot path is not known due to its relativeness and each screenshot is in a different path.

### Desired behavior:

Screenshot should be saved directly in the screenshot folder and no automatic directories should be created. If screenshots need to be put in directories one can specify the full path like `cy.screenshot('/path/image.png')`. which should save as `/screenshotFolder/path/image.png` and not as `/screenshotFolder/$specPath/path/image.png`

### Versions

3.0.3

**Comment by greglds** [comment]
It has been reported in #2092

Here is my solution:

```
on('after:screenshot', (details) => {
        let a, newPath;

        a = path.dirname(details.path).split(path.sep);

        a.pop();

        a.push( path.basename(details.path) );

        newPath = a.join(path.sep);

        return new Promise((resolve, reject) => {
            fs.rename(details.path, newPath, (err) => {
                if (err) return reject(err)

                // remove prev folder
                fs.removeSync( path.dirname(details.path) );

                // because we renamed/moved the image, resolve with the new path
                // so it is accurate in the test results
                resolve({ path: newPath })
            })
        });
    } ); 
```

**Comment by brian-mann** [comment]
@sharmarahul we released a plugin event called `after:screenshot` that you can use to programmatically move around the screenshots however you like. It's much easier than trying to do it in the browser spec file.

https://docs.cypress.io/api/plugins/after-screenshot-api.html

We provide you all of the details in the object that are necessary to move it around.
