### ISSUE TITLE
cy.wait executed by a POST from BaseRoutes fails in circle ci when better-audit package is added

### ISSUE THREAD

**Issue by cristiandiazcmp** [cypress-io/cypress#22592]
### Current behavior

When waiting for a route/response, including the better-audit package is failing in circle ci and we can't figure out why. Also there are two request executed, one (xhr) and another one (other)
This leads to an error: Cannot read properties of undefined (reading 'statusCode')
<img width="1066" alt="screenshot" src="https://user-images.githubusercontent.com/92723787/176383253-3cd9868e-e91d-4c19-9ba0-94cce7cfe834.png">

In local I can't reproduce the error is working properly

### Desired behavior

Reproduce the same behaviour from local to circle ci

### Test code to reproduce

PaymentFormPage.PaymentFormRecurlyHasBeenLoadedCorrectly = () => {
  cy.wait('@recurlyForm')
    .then(data => {
      expect(data.response.statusCode).to.eq(201)
    });
  return PaymentFormPage;
};

### Cypress Version

Local machine: cypress 10.1 , os: macos 12.4 x64  CircleCi machine: cypress 10.1 os: linux

### Other

Only to keep it clear, this issue is only happening when we add the[ better-audit](https://www.npmjs.com/package/better-npm-audit) package

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Please provide a reproducible example with test code. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
