### ISSUE TITLE
Tooltip shows above overlays for login and switching testing type

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#22595]
Tooltip shows above overlays for login and switching testing type

**Comment by rockhold** [comment]
Screenshot and link to conversation in Slack: https://cypressio.slack.com/archives/C035VB3HVAL/p1656375090620839
![image](https://user-images.githubusercontent.com/4065848/176749293-8eb3a61f-dd88-4dfa-9830-f1d5ec950cd0.png)
