### ISSUE TITLE
'Request access' tooltip for average duration appears below header instead of above

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#22597]
### Current behavior

'Request access' tooltip for average duration appears below header

### Desired behavior

'Request access' tooltip for average duration appears above header

### Test code to reproduce

None

### Cypress Version

10.3.0

**Comment by rockhold** [comment]
![image](https://user-images.githubusercontent.com/4065848/176752615-4a929174-f05d-4879-b114-d1d1674c1474.png)

**Comment by mike-plummer** [comment]
Closed by #22650
