### ISSUE TITLE
Queued small status dot updates

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#22601]
### What would you like?

* Standardize coloration of icons in "Latest Runs" section of Specs Explorer
* Update "small status dot" to use the same "queued" icon as the latest run icon for queued/pending runs

### Why is this needed?

![Screen Shot 2022-07-11 at 10 58 02 AM](https://user-images.githubusercontent.com/11482842/178307071-472aa381-23cf-48ce-a22d-2c500d720928.png)

There are some permutations that result in similar but slightly different shades of gray being used to indicate different statuses. Concern is that:
* users may not notice the difference, in which case why not just make them the same?
* users **do** notice the difference and wonder why but not find any useful indication of actionable difference

### Other

See screenshot above

**Comment by mike-plummer** [comment]
Per UX the queued/pending status should be gray-100: https://cypressio.slack.com/archives/C035VB3HVAL/p1658252336300959?thread_ts=1658171200.055129&cid=C035VB3HVAL

**Comment by mike-plummer** [comment]
@abelb Regarding the "queued/pending" icon updates, I'm not sure whether updating the small icons will really be visible without some other changes (or I just have bad eyesight :laughing: ). We may need to look into increasing the size of the previous runs icons to make it more visible. In this screenshot there's 3 historical runs, the middle one being queued. I think we may just want to fix the gray color used here and call it good for now.

![Screen Shot 2022-07-22 at 12 41 31 PM](https://user-images.githubusercontent.com/11482842/181513965-79370167-7aed-4f12-809d-bbf82968f493.png)

**Comment by mike-plummer** [comment]
Final guidance is just to standardize the gray color to gray-200
