### ISSUE TITLE
Cypress unable to recognize a mobiscroll element during test run, but can be detected via selector

### ISSUE THREAD

**Issue by kymark12** [cypress-io/cypress#2260]
### Current behavior:
![image](https://user-images.githubusercontent.com/13220136/43578404-44129d5a-9681-11e8-9d7e-79e820deeac4.png)

An element is detected on the selector but not recognized when the test is ran.

### Desired behavior:

The element should be recognized, or should there be another way, kindly comment here, all suggestions are welcome.

**Comment by brian-mann** [comment]
We'd unfortunately need a simple and reproducible repo showing this problem. I understand what you're showing from the screenshot, but the selector itself is cut off, and it's possible there are other reasons that it's not being found in the DOM.

After your test runs, pop open your dev tools and try running `Cypress.$(selector here)` and see if that returns the element.

**Comment by kymark12** [comment]
Hi @brian-mann 

I ran the command you suggested, and it returned the element. Please see the screenshot below:
![image](https://user-images.githubusercontent.com/13220136/43579360-61c7b364-9684-11e8-8fbb-b9573bba86d8.png)

**Comment by brian-mann** [comment]
Nope, it returned a jquery wrapped element with `{ length: 0 }` which means it did not find the DOM element.

It could just be that for whatever reason/edge case the Selector Playground is returning an invalid selector. Can you try to simplify your selector.

**Comment by kymark12** [comment]
@brian-mann 

I'm having trouble simplifying it as well, since I tried using the aria-label as the contains, used the div. version of the selector, it seems that it can only find the long version. Any suggestions on how I can simplify it? Here's the full length default selector `#mobiscroll1533206539895_dw_pnl_0 > .dw-cal-pnl-i > .mbsc-w-p > .dw-cal > .dw-cal-header > .dw-cal-btnc > :nth-child(2) > .dw-cal-next-y > .dw-cal-btn-txt`

![image](https://user-images.githubusercontent.com/13220136/43579817-e2049636-9685-11e8-8842-188bae87c4db.png)

**Comment by kymark12** [comment]
I found out how to work around it, apparently you can use aria-label in this format `[aria-label=Next Year]` so that's what I used and worked like a charm. Although I had to add `multiple: true` and `force: true`, since the dev team duplicated the same containers for both Departure and Arrival datepickers. Thanks for the suggestions anyway
