### ISSUE TITLE
Cypress doesn't like parenthesis () in foldername

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#22600]
### Current behavior

When the parent of the "cypress" folder has parenthesis like the following: "INSERT (insert text)" in it, Cypress can't find my specs that are in this form: cypress\e2e\SPECNAME.cy.js and can't find my supportFile in cypress\support\e2e.js

### Test code to reproduce

*Do all the steps to install and run cypress in "TEST" folder - it will work
*Do all the steps to install and run cypress in "TEST (a)" folder - it will NOT work

### Cypress Version

10.3.0

### Other

Let me know if you need any other details.
If anyone else in the community has the same issue, please let me know that it is happening to you too

**Comment by tbiethman** [comment]
@alexsch01 thank you for the report. We've had some issues with parentheses in paths getting into our glob patterns and causing problems. Can you provide the following data so we can investigate further?

* The OS you're using with cypress
* The full path to the cypress project exhibiting this issue (you can replace sensitive data here, just try to persist any spaces/special characters)
* The cypress config you are using for this project

**Comment by tbiethman** [comment]
Thanks @alexsch01 ! I tried to reproduce a problem using a project in a similarly named directory, however cypress@10.3.0 was able to find the support file and specs within that project.

You said that specs can't be found; is Cypress presenting you with an error in this state, or just not finding your specs? In either case, can you try running cypress with the DEBUG logs enabled and providing the output?

```
DEBUG=cypress:*
```

**Comment by alexsch01** [comment]
@tbiethman Ahhh ok, I understand the difference....my command I am testing is this:
 
**npx cypress run --spec .\cypress\e2e\spec.cy.js**

![image](https://user-images.githubusercontent.com/5721147/176968123-3bbc1f17-250a-42fe-88bb-f886446a0dde.png)

![image](https://user-images.githubusercontent.com/5721147/176968253-d175b64b-0410-4d88-ad36-b8b1d9f43a7f.png)


I'm attaching a log file below, the only modification I did to this file was not showing my user account name.

[Cypress_Logs.txt](https://github.com/cypress-io/cypress/files/9031730/Cypress_Logs.txt)

**Comment by alexsch01** [comment]
Hope the information helps in figuring out the underlying issue

**Comment by alexsch01** [comment]
@tbiethman
Hope the information helps in figuring out the underlying issue
