### ISSUE TITLE
Firefox display bug

### ISSUE THREAD

**Issue by melsacramento** [cypress-io/cypress#22610]
### Current behavior

When running cypress 10 and using firefox(v102) as the browser. There is a problem with the display (see attached image)

This did not occur in cypress 9

One workaround to this is to minimize the browser display, but it can be very inconvenient as then its hard to see the test that are running

![image](https://user-images.githubusercontent.com/88633931/176597412-13041cd4-87f0-46d0-abd5-dad251ab6ba8.png)

### Desired behavior

Expect the display to look normal

### Test code to reproduce

Unable to give source code, though as long as its a lengthy one it seems to happen

### Cypress Version

10.3.0

### Other

I am also using kubuntu 22.04 if that helps

**Comment by marktnoonan** [comment]
Thanks for reporting @melsacramento, this looks like another manifestation of https://github.com/cypress-io/cypress/issues/21881, which I am actually testing a fix for right now, and expect it to be included in the next release of Cypress.

**Comment by melsacramento** [comment]
Thank you very much, looking forward to the fix
