### ISSUE TITLE
Form submission with Enter keypress broken in 3.0.3 when button other than submit button exists

### ISSUE THREAD

**Issue by Narretz** [cypress-io/cypress#2261]
### Current behavior:
Cypress currently doesn't allow you to submit a form when pressing Enter in a form's text input (and the form has a submit button).

See here for the exact configuration needed to trigger the bug: https://github.com/cypress-io/cypress/issues/2261#issuecomment-409919418

### Desired behavior:

Pressing enter must click the default submit button / fire the "submit" event on the form same as virtually every browser does: https://html.spec.whatwg.org/#implicit-submission

### Steps to reproduce:

```js
<form>
  <input type="email" id="email">
  <input type="password" id="password">
  <button type="submit">Submit me</button>
</form>
```

```js
cy.get('#email')
  .type('test@example.com');

cy.get('#password')
  .type('password')
  .type('{enter}');
```

### Versions

Tested in 3.0.3

I suspect this might be collateral introduced by https://github.com/cypress-io/cypress/issues/651 / https://github.com/cypress-io/cypress/pull/2016

**Comment by brian-mann** [comment]
Hrm, I haven't tried it yet but I am skeptical how this could have broken. We have 25 tests around this behavior with all of the edge cases mapped out... no tests are failing.

https://github.com/cypress-io/cypress/blob/whitelist-ci-build-id/packages/driver/test/cypress/integration/commands/actions/type_spec.coffee#L2253-L2449
 
![screen shot 2018-08-02 at 7 52 26 am](https://user-images.githubusercontent.com/1268976/43582128-48966bc0-9629-11e8-9da3-05b9b7475721.png)

**Comment by Narretz** [comment]
Ok, I will make some more tests on my side to see where the problem is.

**Comment by Narretz** [comment]
So the bug happens when the form looks like this:

```
   <form>
      <input id="email" type="email">
      <input id="password" type="password">
      <button type="button"></button>

      <button type="submit">Submit</button>
    </form>
```

The extra button before the submit button breaks the behavior.

**Comment by Bkucera** [comment]
@Narretz Was this working in previous Cypress versions? If you're saying this bug was recently introduced

**Comment by Narretz** [comment]
@bkucera it last worked in 3.0.1. I updated straight from 3.0.1 to 3.0.3 though so I don't know if it works in 3.0.2. Like I said above I assume the big PR that touched a lot of. Type() stuff might be responsible.

**Comment by crosscompile** [comment]
I am also experiencing this bug when there is an additional button in a form after updating from 3.0.2 to 3.0.3.

**Comment by faiz121** [comment]
I am also experiencing this bug, I had to change the test to instead click on the submit button
