### ISSUE TITLE
lunch firefox not working 

### ISSUE THREAD

**Issue by bilalSaidi** [cypress-io/cypress#22617]
### Current behavior

while lunching firefox i got this message : 
Still waiting to connect to Firefox, retrying in 1 second (attempt 56/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 57/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 58/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 59/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 60/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 61/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 62/62)
[23924:0630/143008.151:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 

### Test code to reproduce

not related to my code 

### Cypress Version

10.3.0

**Comment by tbiethman** [comment]
@bilalSaidi thanks for the report. We are currently tracking some Firefox connection issues on Windows with Firefox 101: #22086. Can you confirm your OS and FF version?

**Comment by bilalSaidi** [comment]
Hi 
Windows 10
Firefox latest version

**Comment by tbiethman** [comment]
Thanks @bilalSaidi, this seems to be the same root issue currently tracked with #22086. I will close this issue as a duplicate; please reference #22086 for more info.
