### ISSUE TITLE
(chrome) disabled Optimization Guide Prediction models

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#22622]
### What would you like?

While debugging chrome crashes yesterday, I saw some interesting requests from Google...after a bit of googling, looks like Google runs Optimization Guide Prediction models when it is opened. This is the [full list of optimization guide features.](https://source.chromium.org/chromium/chromium/src/+/main:components/optimization_guide/core/optimization_guide_features.cc;l=85)
We could (prob should?) disable these features by passing the following chrome argument on browser launch:
```
--disable-features=OptimizationGuideModelDownloading,OptimizationHintsFetching,OptimizationTargetPrediction,OptimizationHints
```

This might be one reason our windows resources suddenly tanked. There was a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1311753) logged 20 days ago against Chrome 100 and a fix supposedly went out in 102, though someone mentioned they were on 102 and experience this issue as well.

With our Electron bump to 18.0.4 we bumped Chromium to 100.0.4896.75 and users have logged issues against electron performance issues. This might be related....

Need to confirm if it’s really downloading a 45mb file every time chrome launches and disable this if it is.

### Other
Cypress 10.3.0

**Comment by jennifer-shehane** [comment]
Found a couple of references on this:
- https://go.dev/solutions/google/chrome
- https://chromium.googlesource.com/chromium/src/+/HEAD/components/optimization_guide/

I don't think I'd feel comfortable turning these off and the previous bug reported has been resolved.  [Puppeteer](https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:gen/arm-generic/chroot/var/cache/chromeos-chrome/chrome-src/src/out_arm-generic/Release/gen/third_party/devtools-frontend/src/front_end/third_party/puppeteer/package/lib/esm/puppeteer/node/ChromeLauncher.js;l=113?q=disable-client-side-phishing-detection&ss=chromiumos%2Fchromiumos%2Fcodesearch) does not turn off these features.

**Comment by Siteload** [comment]
i dno what this is but i have this 
found it in chrome://download-internals/

https://optimizationguide-pa.googleapis.com/downloads
/home/chronos/u-f662481de7e03628f27597be8e001eeb62f7ccf1/Download Service/Files/f1b7f3b0-d0c1-4d12-9077-0c81a3db94c0
