### ISSUE TITLE
Get a file stream

### ISSUE THREAD

**Issue by JamesRamm** [cypress-io/cypress#2262]
### Current behavior:

Cypress offers 'readFile' which returns a string with file contents

### Desired behavior:
I'd like to be able to get hold of a stream for a file on the file system which I can then uses with `cy.request`. The purpose is to test API endpoints which expect a binary stream as the POST content.

For example, from nodeJS with e.g. superagent I can do something like
```JS
const stream = fs.createReadStream('path/to/my.json');
stream.pipe(req)
```

I have tried doing

```JS
const data = cy.readFile(path, 'binary')
const blob = new Blob([data])
cy.request({
  url: '<url>'
  method: 'POST',
  json: false,
  body: blob
  headers: { ... }
})
```
But it doesn't work in the same manner

### Versions

cypress 3.0.3, Chrome 67, Ubuntu 18.04

**Comment by brian-mann** [comment]
You can use `cy.task` in order to implement this in `node`.

Also you aren't using cypress commands correctly. You cannot assign the return value of `cy.readFile` since its async. You have to use a `.then()`

https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#

**Comment by Jmaharman** [comment]
I believe I have a similar problem. I need to upload a binary file through cy.request, gathering the contents via cy.fixture provides me a string in return, which while correct, gets encoded by Cypress.io on it's way to the server.

The scenario is that I'm reading a pdf file from disk, as 'binary', the returned data that I'm logging appears correct and is the right length (115184), however it is a string. Once received at the server-end it has exploded to 174134 bytes. Upon saving the file I can see that the contents are being encoded.

Original: /Creator (Canon iR-ADV 4225 PDF)
Received: /Creator %28Canon iR-ADV 4225 PDF%29

I assume that the cy.request is encoding the body automatically. Is there any way of disabling this?

I get the impression I need to write a task that does *everything* to make this possible. Is that correct?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
