### ISSUE TITLE
Multiple `.not` calls are not parsed correctly

### ISSUE THREAD

**Issue by ChrisBAshton** [cypress-io/cypress#2263]
I can write an assertion like so:

`expect(image).to.not.be.visible;`

I can also write it like so:

`expect(image).not.to.be.visible;`

So, to check my test was working, I tried the following:

`expect(image).not.to.not.be.visible;`

### Current behavior:

If I expect something _not_ to _not_ be visible, then I expect it to be _visible_.

But, my test passed! So it doesn't seem as though the assertion is being parsed properly.

To test this even further, I tried this:

`expect(image).not.not.not.not.to.not.be.visible;`

Again, my test passed.

For avoidance of doubt, my test fails (as expected) when I run this: `expect(image).to.be.visible;`

### Desired behavior:

I would expect double-negatives to be disallowed from the application.

`expect(image).not.to.not.be.visible;`
->
`Error: multiple uses of 'not' detected. Please limit your assertion to one 'not' - it is far easier to read!`.

### Steps to reproduce:

Check out https://github.com/cypress-io/cypress-test-tiny/pull/33 (`ChrisBAshton:not-not` branch of [cypress-io/cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny/pull/33)).

### Versions

Cypress: 3.0.1
OS: OSX 10.12.3.

**Comment by jennifer-shehane** [comment]
This behavior essentially comes from [chai](http://www.chaijs.com/api/bdd/) and yes, the presence of `not` simply negates any assertions present, regardless of the amount of times `not` is included. 

I believe we could throw an error in the situation of chaining `not`, but this would be very low priority.

**Comment by Bkucera** [comment]
closing since this is desired behavior, as established by chai
