### ISSUE TITLE
cy.visit() "still" fails behind corporate proxy

### ISSUE THREAD

**Issue by saurabh021986** [cypress-io/cypress#22632]
### Current behavior

I have gone through numerous previous issues explaining incorrect behavior of cy.visit() behind corporate proxy and have already tried all mentioned workarounds like setting http proxy variables. Still i am not able to open the webpage i want to test behind my company proxy. Using Cypress v10.1.10 on Mac OS v11.5

Relevant log:
at timedOutWaitingForPageLoad (http://<ip:port>/__cypress/runner/cypress_runner.js:155456:75)
    at <unknown> (http://<ip:port>/__cypress/runner/cypress_runner.js:156675:17)
From previous event:
    at Context.visit (http://<ip:port>/__cypress/runner/cypress_runner.js:156674:62)
From Your Spec Code:
    at Context.eval ([webpack:///./cypress/e2e/spec.cy.js:3:8](http://<ip:port>/__/#))

### Test code to reproduce

describe("Login page test suite", () => {
  it('Navigates to login page', () => {
    cy.visit('http://<ip:port>/app/preprod/#/home')
  })

 
})

### Cypress Version

10.1.10

**Comment by saurabh021986** [comment]
Hi

Yes i had gone through the proxy config doc and had tried to implement both the mentioned commands in the format given below:

export HTTP_PROXY=http://username:password@my-company-proxy-IP:proxy-port
export NO_PROXY=localhost

but this did not work. Ultimately after may trial and errors i was able to run the code by giving only 
NO_PROXY=<internal company domain whose website i was trying to open>

Hope this helps someone trying very hard to get cypress run behind corporate proxy.

**Comment by chrisbreiding** [comment]
I'm happy to hear you found a solution. Just to clarify, so that we can potentially improve the documentation around this, was your solution the following:

```
export HTTP_PROXY=http://username:password@my-company-proxy-IP:proxy-port
export NO_PROXY=internal-company-domain
```

or was it only setting NO_PROXY and not setting HTTP_PROXY?

```
export NO_PROXY=internal-company-domain
```
