### ISSUE TITLE
Changes to `blockHosts` config value should trigger restart

### ISSUE THREAD

**Issue by tbiethman** [cypress-io/cypress#22634]
### Current behavior

The `blockHosts` config value does not trigger a server restart on change, which results in those values not getting picked up in the current Cypress instance. This is inconsistent with our controls around other values and will lead to confusion.

### Desired behavior

Cypress restarts when the `blockHosts` config value changes so that the new value is used.

### Test code to reproduce

* Open a project with specs that make requests to external hosts
* Run the specs and see those requests made in the reporter logs
* Add `blockHosts` config values that would block those requests, notice that cypress does not restart
* Run tests again, notice that the requests are still not blocked
* Quit and relaunch Cypress
* Run spec again, notice previous requests are now blocked and absent from the reporter log

### Cypress Version

10.3.0

### Other

Relevant config: https://github.com/cypress-io/cypress/blob/develop/packages/config/src/options.ts#L140-L143

**Comment by konnster99** [comment]
hi can i try this issue?

**Comment by emilyrohrbough** [comment]
@konnster99 That would be great!

**Comment by meisster** [comment]
Since there was almost a month of inactivity, I tried to take care of the issue in the linked PR.
