### ISSUE TITLE
yarn audit fails after updating @cypress/webpack-dev-server to v2

### ISSUE THREAD

**Issue by chrisrhymes** [cypress-io/cypress#22644]
### Current behavior

When I upgrade @cypress/webpack-dev-server to "^2" (which installs v2.0.0) I get the following error when running `yarn audit`.

```
~ yarn audit
yarn audit v1.22.17
error An unexpected error occurred: "Unexpected audit response (Missing Metadata): false".
info If you think this is a bug, please open a bug report with the information provided in "/my-project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/audit for documentation about this command.
```

If I rollback to the previous version constraint `"@cypress/webpack-dev-server": "^1.8.0",` then `yarn audit` works as expected. 

### Desired behavior

yarn audit should work as expected

### Test code to reproduce

Here are the Cypress dependencies in my package.json to reproduce the issue. 

```json
"devDependencies": {
    "@cypress/react": "^6",
    "@cypress/webpack-dev-server": "^2",
    "cypress": "^10",
    "html-webpack-plugin": "5",
    "start-server-and-test": "^1.14.0",
    "ts-loader": "^9.2.6",
    "webpack": "5",
    "webpack-dev-server": "^4.6.0"
  }
```

Yarn version: 
  1.22.17

Node version: 
  14.18.2

### Cypress Version

10

**Comment by emilyrohrbough** [comment]
@chrisrhymes I was unable to reproduce this issue when installing `@cypress/webpack-dev-server` in [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) using yarn v1.22.17.

This [yarn issue](https://github.com/yarnpkg/yarn/issues/6607) was logged a while back for v1.22.10. Please check your yarn version.
