### ISSUE TITLE
Custom command contains ReactElement will throw error

### ISSUE THREAD

**Issue by yuyic** [cypress-io/cypress#22643]
### Current behavior

If the custom command in support file contains ReactElement, then I get "CypressError: Cypress cannot execute commands outside a running test.", is this a bug?

### Test code to reproduce

https://github.com/yuyic/cypress-custom-mount-demo

### Cypress Version

10.3.0

**Comment by BlueWinds** [comment]
You're mixing testing types here. `mount` is for component testing - which looks like what you're trying to do - but you have your sample test set up as e2e.

You'll want to go back and run through component testing project setup, which should help you get started. https://docs.cypress.io/guides/component-testing/writing-your-first-component-test has docs about that and should help you get started.

![image](https://user-images.githubusercontent.com/3003404/178838539-a5180cc0-6504-429c-b194-b4c7d8dd9310.png)
