### ISSUE TITLE
Create Flaky badge component

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#22654]
https://www.figma.com/file/DgeFrhaX8N9ufrzvxzLnPg/app-cloud-int%3A-flake-tooltip?node-id=16539%3A146227

![Screen Shot 2022-07-01 at 11 28 41 AM](https://user-images.githubusercontent.com/11482842/176934210-d4738103-d4f5-4ee8-9a09-de8574b97588.png)

Badge will display if a spec retrieves data from the cloud indicating it is flaky. It will provide a tooltip on hover/focus (tracked separately under #22655) with additional information, and should be actionable by linking directly to flaky data in the dashboard using a url provided by the cloud

**Work Items**
1. Create Flaky Badge component to match Figma designs (see above)
2. Create component tests for Flaky Badge

**Acceptance Criteria**
1. Flaky Badge component is created with appropriate component tests
4. Component matches Figma designs (see above)

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22654?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34

**Comment by marktnoonan** [comment]
> should be actionable by linking directly to flaky data in the dashboard using a url provided by the cloud

Is this URL already available, or we know how to compute it? I don't see it as part of https://cypress-io.atlassian.net/browse/CLOUD-691 so it seems like like this ticket isn't blocked by any cloud work to make it available, just want to make sure.

**Comment by mike-plummer** [comment]
> Is this URL already available, or we know how to compute it? I don't see it as part of [cypress-io.atlassian.net/browse/CLOUD-691](https://cypress-io.atlassian.net/browse/CLOUD-691) so it seems like like this ticket isn't blocked by any cloud work to make it available, just want to make sure.

@marktnoonan I have added a comment to CLOUD-692 ticket to make sure that is covered - it is already called out in our "integrate with cloud-supplied data" ticket #22656
