### ISSUE TITLE
Integrate new Flaky API data via GQL

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#22656]
**CLOUD dependencies to provide the following data**

Data for indicator: [CLOUD-691](https://cypress-io.atlassian.net/browse/CLOUD-691)
* "isFlaky" attribute for spec

Data for tooltip: [CLOUD-692](https://cypress-io.atlassian.net/browse/CLOUD-692)
* "Flaky Rate" - low, medium, high and percentage
* "Flaky vs total runs" totals (2 flaky runs / 50 total)
* "Last Flaky" (Last flaky 2 runs ago)
* URL to take user directly to dashboard content

**Work Items**
1. GQL schema in app is updated
2. New "flaky" components are updated to pull data from GQL
3. GQL subscription(s) are updated to ensure Flaky fields are updated by existing ACI spec polling

**Acceptance Criteria**
1. Flaky Badge is displayed at runtime for applicable specs
2. Flaky Tooltip displays correct cloud-supplied data
3. Flaky badge/tooltip is actionable to take user to dashboard page
4. Flaky badge & tooltip are updated automatically by background polling as new run data is recorded

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22656?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34

**Comment by marktnoonan** [comment]
With `Accept data via props that can be mapped to GQL data supplied by cloud` in https://app.zenhub.com/workspaces/component-testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22655, I think we should use `mountFragment` to get the component tests up and running with mock gql data, which would move updating the schema to that ticket and get us ahead on the GQL stuff. We won't be able to use the component outside of test scenarios, but I'd suggest we don't need to have any point where the component that will have the gql data is created and tests but isn't using the `mountFragment` setup.

The tests referenced in `Component tests are created and passing` of #22655 should be testing the acceptance criteria for this ticket. I'd suggest we combine the two into a single step and maybe reserve this this ticket for final validation after the data is coming through from the cloud. But as long as the final shape of the data is known I don't think we're block from moving forward.
