### ISSUE TITLE
ACI: Flaky Annotation

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#22653]
App/Cloud Integration - Display "Flaky" indicator in Specs Explorer with actionable tooltip

PRD: https://docs.google.com/document/d/1u5cyqB6uDcGnhDnex49XKODJzZKdBpYr1xbgovS-bC8/edit#heading=h.shvspemfqn1w

Figma: https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/DgeFrhaX8N9ufrzvxzLnPg/Cypress-App?node-id=15539%3A191387

**Comment by lmiller1990** [comment]
Can we close this @mike-plummer? All the child issues are done.
