### ISSUE TITLE
Create Flaky data tooltip component

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#22655]
https://www.figma.com/file/DgeFrhaX8N9ufrzvxzLnPg/app-cloud-int%3A-flake-tooltip?node-id=16635%3A148374

![Screen Shot 2022-07-01 at 11 31 35 AM](https://user-images.githubusercontent.com/11482842/176934667-90627335-49ac-42a0-aa91-85525a5f55a5.png)

**Work Items**
1. Create tooltip content layout (similar to existing layout in `SpecRunSummary.vue` for Latest Runs data)
2. Integrate "graph" icons for displaying flaky level
3. Accept data via props that can be mapped to GQL data supplied by cloud
4. Create component tests

**Acceptance Criteria**
1. Tooltip component is created and matches Figma designs
    * Note that color shading is impacted by flaky rate "level" (low/medium/high)
2. Component tests are created and passing

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22655?planning-poker) with ZenHub @astone123 @marktnoonan @mike-plummer @lmiller1990 @ZachJW34

**Comment by lmiller1990** [comment]
Not sure if we've got a pre-existing popover/bubble component. It would be good to have one we can reuse.

**Comment by mike-plummer** [comment]
> Not sure if we've got a pre-existing popover/bubble component. It would be good to have one we can reuse. Making the little downwards pointing triangle bit with the correct box shadow is probably harder than anyone is expecting, I don't think you can have a box shadow that follows an outline like this.

We have something very similar in the "Latest Runs" column added in ACI phase 1 using the `Menu` component from `floating-vue`. My plan is to see about abstracting that a bit to provide a common base since it's visually very similar
