### ISSUE TITLE
Cypress web runner

### ISSUE THREAD

**Issue by AbrahamBrookes** [cypress-io/cypress#22669]
### What would you like?

I'd like to be able to install cypress on a project running on a remote web server (like AWS or Vultr) and access the test runner using a web browser interface.

Tools like Vue-cli and Jenkins allow this and it is really handy for portability and ease of use.

### Why is this needed?

I want this because I run my local projects in docker containers and staging sites on ubuntu VPSes and my only options are to just use the test runner (clunky and hard to human-read) or install an X server (complicated and a whole sphere of learning I'd like to avoid)

### Other

It wouldn't need to be the full simulated browser with time travelling and its own console etc, even just a nicer UI on top of the output of the runner would be fine - I'm thinking pipe the test runner output through a PHP parser and load it into a database and then put a laravel on top of it and show a nice UI - list runs and results, load screenshots and video elements, run specs

**Comment by lmiller1990** [comment]
This is something that's definitely been discussed/explored (internally and externally) in the past, at least, if I understand what you are asking for, or at least, partially. The idea of caching results then allowing them to be "replayed" is something I'd like to see.

As for running on a remote server - just to clarify - you'd be running Cypress on a server somewhere, but have the Cypress 10 UI (with the spec list, etc) that you can then click through and it will run the tests? What is this running against - a live staging environment (in contrast to when you run Cypress locally, you'd run against a locally running instance of your app?)

**Comment by AbrahamBrookes** [comment]
Ok I just checked out the cypress dashboard and that practically solves this issue for me, although it works in a different way it solves the same issue.

**Comment by lmiller1990** [comment]
Great! Let us know if you've got any ideas/suggestions for the dashboard.

I don't see any actionable info here at this point, so I'm going to close this. Let me know if I'm missing something, or you think we should keep it open (and what you think we need to do).
