### ISSUE TITLE
Cypress dashboard does not show all repos in dropdown box after integration with Gitlab

### ISSUE THREAD

**Issue by threehook** [cypress-io/cypress#22668]
### Current behavior

When I try to setup my Cypress project to integrate with Gitlab I am using the Application ID and Secret that I configured in Gitlab.
Then in the Cypress dashboard I want to link my Cypress project to the right repo.
In the Cypress dashboard it shows me that there are 54 repos to choose from.
![image](https://user-images.githubusercontent.com/442604/177053685-eba139b5-82ae-4b40-aea7-7670993cf922.png)

However when I try to choose one repo from the drop down box below it, it only shows 29 repos, and not the one I want.
![image](https://user-images.githubusercontent.com/442604/177053754-6b8305b5-3151-4560-8671-4f7831f0306c.png)

I also tried to sync a couple of times, but that did not gave me more repos.

### Desired behavior

From the Cypress dashboard under menu 'Integrations' I would expect that if there are 54 repos to choose from, that the dropdown box shows all 54 repos and not just 29.

### Test code to reproduce

My .gitlab-ci.yaml in which I defined the CI/CD to run my Cypress test is valid and shows all tests are green.
So the problem is not in the Cypress tests, it's in the integration part of the Cypress dashboard.

### Cypress Version

10.3.0

**Comment by conversaShawn** [comment]
@threehook Can you confirm if this is GitLab cloud or GitLab Enterprise (on-prem)?

**Comment by threehook** [comment]
Hi Conversa,

This concerns the **GitLab cloud**, not the GitLab for Enterprise.
Thanks for looking into the issue.
If you have more questions let me know.

**Comment by conversaShawn** [comment]
@threehook If you are still experiencing this issue, can you send me an email to shawn.harris@cypress.io with the following information:

> This GH Issue as the subject title
> Your Organization ID using the instructions here: https://docs.cypress.io/guides/dashboard/organizations.html#Organization-ID

Please @ me after sending

**Comment by threehook** [comment]
Hi Shawn,

We are still experiencing the issue. It was not solved.
My Organization ID is: 60dc76b4-3abd-40d6-b8c9-0876901c5f60

Kind regards,
Ton

On 27/07/2022 02:58:21, Shawn Harris ***@***.***> wrote:

@threehook<https://github.com/threehook> If you are still experiencing this issue, can you send me an email to ***@***.******@***.***> with the following information:

This GH Issue as the subject title
Your Organization ID using the instructions here: https://docs.cypress.io/guides/dashboard/organizations.html#Organization-ID

Please @ me after sending

**Comment by conversaShawn** [comment]
@threehook Would you mind recording your process for completely uninstalling the Cypress integration (including the permissions in GitLab) and the re-installing? Ideally if you could also catch anything in the dev tools console, that would be great.

If you have not seen them already, here are the instructions below:

> [Uninstall Cypress GitLab App](https://docs.cypress.io/guides/dashboard/gitlab-integration#Uninstalling-the-GitLab-integration).
> [Setup Cypress GitLab Integration](https://on.cypress.io/gitlab-integration#Installing-the-GitLab-integration).

**Comment by conversaShawn** [comment]
This issue has been resolved after completely uninstalling the Cypress integration (including the permissions in GitLab) and re-installing it.
