### ISSUE TITLE
10.3 broke support for oauth flow with Spotify

### ISSUE THREAD

**Issue by SilverLinings89** [cypress-io/cypress#22674]
### Current behavior

We have a test that redirects a user to Spotify to login, performs the login there and then returns on success. This test worked will in 10.2 but fails in 10.3.
We navigate to the login page using cy.origin and receive an error 
![image](https://user-images.githubusercontent.com/35356122/177216718-096c909b-07ec-4e2f-ae1b-23eec74e106b.png)

### Desired behavior

This worked before. 

### Test code to reproduce

Basically: 

cy.origin + visit to https://accounts.spotify.com/en/login (the exact url depends on the app you have registered and the callback you use)
cy.get('input#login-username').click().type(email);
cy.get('input#login-password').click().type(spotifyPw);
cy.get('#login-button').click();
-> in 10.2 this works like a charm, in 10.3 it fails with the message in the image above "Oops! Something went wrong, please try again or check out our help area"

### Cypress Version

10.3

### Other

The form uses a post request that failes with an error code 400.
POST https://accounts.spotify.com/login/password 400 (Bad Request)

From the changelog of version 10.3 I would suspect this to be related to this: 
Updated cross-origin cookie handling to align with browser behavior. This fixed various issues with cookies when testing across multiple origins. Fixed [#21363](https://github.com/cypress-io/cypress/issues/21363) and [#20685](https://github.com/cypress-io/cypress/issues/20685).

**Comment by chrisbreiding** [comment]
I confirmed this fails in 10.3.0 with the following:

```js
  it('logs in with spotify', () => {
    cy.origin('spotify.com', () => {
      cy.visit('https://accounts.spotify.com/en/login')
      cy.get('input#login-username').click().type(Cypress.env('spotify-username'))
      cy.get('input#login-password').click().type(Cypress.env('spotify-password'))
      cy.get('#login-button').click()
    })
  })
```

My hunch is that this is related to spotify using `document.cookie` to check if cookies are enabled. I checked and confirmed that this is fixed by https://github.com/cypress-io/cypress/pull/22594, so I think my hunch is correct. 

This issue will be resolved in the next release of Cypress, which will be this week or next week at the latest.

**Comment by SilverLinings89** [comment]
Thank you very much for your effort, I will evaluate this once the release is out and give feedback :)
