### ISSUE TITLE
Craco Webpack config not working with Component Testing

### ISSUE THREAD

**Issue by adi518** [cypress-io/cypress#22672]
### Current behavior

I'm using Craco to override CRA Webpack config and while Craco provides API to extract the overridden Webpack config, Cypress throws with the following:

```ts
Error: Cannot find module '/Users/x/dev/deepdubapp8/cypress/package.json'
Require stack:
- /Users/x/dev/deepdubapp8/node_modules/react-scripts/config/paths.js
- /Users/x/dev/deepdubapp8/node_modules/react-scripts/config/env.js
- /Users/x/dev/deepdubapp8/node_modules/@craco/craco/lib/cra.js
- /Users/x/dev/deepdubapp8/node_modules/@craco/craco/lib/features/jest/api.js
- /Users/x/dev/deepdubapp8/node_modules/@craco/craco/index.js
- /Users/x/dev/deepdubapp8/craco.config.ts
- /Users/x/dev/deepdubapp8/cypress/cypress.config.ts
- /Users/x/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js
- /Users/x/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename (/Users/x/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/x/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object. (/Users/x/dev/deepdubapp8/node_modules/react-scripts/config/paths.js:28:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions. [as .js] (/Users/x/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1445:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object. (/Users/x/dev/deepdubapp8/node_modules/react-scripts/config/env.js:13:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions. [as .js] (/Users/x/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1445:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
```

### Desired behavior

Boot Component Testing successfully.

### Test code to reproduce

Extract Craco config and pass it to Cypress config:

```ts
// craco.config.ts
export const webpackConfig = createWebpackDevConfig(cracoConfig);

// cypress.config.ts
export default defineConfig({
  component: {
    devServer: {
      framework: 'create-react-app',
      bundler: 'webpack',
      webpackConfig: webpackConfig,
    },
  },
});
```

### Cypress Version

^10.3.0

**Comment by chrisbreiding** [comment]
Could you provide your `craco.config.ts`, `tsconfig.json`, and `package.json`?

**Comment by adi518** [comment]
Sure. Meanwhile, someone on Discord posted a workaround. See https://discord.com/channels/755913899261296641/994988557162774609/994989129567830086.

I didn't confirm this workaround works, but I'm not particularly fond of it, as it's difficult to understand.

**Comment by vfritzon** [comment]
I've tried the same approach but got `[React Refresh] Hot Module Replacement (HMR) is not enabled!` from https://github.com/pmmmwh/react-refresh-webpack-plugin when running the tests.

Was hoping to get it to work while waiting for https://github.com/cypress-io/cypress/issues/21952

**Comment by mjhenkes** [comment]
@adi518, Could you provide us with a reproduction repo? I typically start use [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) template as a starting point but i'm not familiar enough with craco to know if that makes sense.

**Comment by adi518** [comment]
Extract the Webpack config from Craco (using their utility for that) and pass it to Cypress config.

**Comment by marktnoonan** [comment]
Hi @adi518, unfortunately until https://github.com/cypress-io/cypress/issues/21952 lands we don't officially support craco in CT, and I don't think we can get into wrangling with webpack for it until we pick up that issue. I'm not sure when that issue will get picked up.

I'd suggest going with the suggested workaround for now until official support lands, or if you would like to get ahead of us on the implementation https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/devServer.ts and https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/helpers/createReactAppHandler.ts might be good places to start looking.

**Comment by xanderfehsenfelddelhivery** [comment]
> Sure. Meanwhile, someone on Discord posted a workaround. See https://discord.com/channels/755913899261296641/994988557162774609/994989129567830086.
> 
> I didn't confirm this workaround works, but I'm already not fond of it, as it's a bit ambiguous.

For those of us without access to discord, do you mind pasting the solution here?

**Comment by vfritzon** [comment]
@xanderfehsenfelddelhivery 

I've got it to work with this workaround

`cypress.config.ts`:
```
import { createWebpackDevConfig } from '@craco/craco'
import { devServer } from '@cypress/webpack-dev-server'
import { defineConfig } from 'cypress'

import cracoConfig from './craco.config.js'

const webpackConfig = createWebpackDevConfig(cracoConfig)

export default defineConfig({
  component: {
    devServer(cypressConfig) {
      return devServer(cypressConfig, { webpackConfig })
    },
    specPattern: 'src/**/*.spec.tsx',
  },
})
```

Some relevant dependencies and their versions:
```
"@craco/craco": "6.4.5",
"@types/craco__craco": "^6.4.0",
"@cypress/webpack-dev-server": "1.8.4",
```

**Comment by xanderfehsenfelddelhivery** [comment]
@vfritzon I installed the dependencies like you specified but the test run just hangs and cypress never opens. I actually got this working without craco. The issue was a misconfigured tsconfig value that react-scripts didn't like.

**Comment by alecmerdler** [comment]
@vfritzon Awesome! your `cypress.config.ts` works for me. Thank you for sharing your solution.

**Comment by rmmanseau** [comment]
was hitting hot reload module missing error with  @cypress/webpack-dev-server@2.0.0

using @cypress/webpack-dev-server below version 2.0.0 as @xanderfehsenfelddelhivery suggested didn't work for my on Cypress 10.4.0. kept getting an error about not being able to find data-cy-root in component-index.html even though it was there.

after some trial and error i found that the below config works for me.

```js
// cypress.config.js

const { defineConfig } = require("cypress");
const { devServer } = require('@cypress/webpack-dev-server');
const { createWebpackDevConfig } = require("@craco/craco");

const cracoConfig = require("./craco.config.js");
const webpackConfig = createWebpackDevConfig(cracoConfig);
const filteredPlugins = webpackConfig.plugins.filter(plugin => (
  !["HotModuleReplacementPlugin",
    "HtmlWebpackPlugin",
    "ReactRefreshPlugin",
   ].includes(plugin.constructor.name)
));
webpackConfig.plugins = filteredPlugins;

module.exports = defineConfig({
  component: {
    devServer(devServerConfig) {
      return devServer({...devServerConfig, webpackConfig })
    },
    specPattern: "src/**/*.cy.js",
  },
});
```

```js
// cypress/support/component.js

window.$RefreshReg$ = () => {};
window.$RefreshSig$ = () => () => {};
```
