### ISSUE TITLE
Cypress component tests fail to run when using @react-data-table-component -- ^7.5.2

### ISSUE THREAD

**Issue by manishagupta016** [cypress-io/cypress#22678]
### Current behavior

Running Cypress component tests (Cypress ^10.3.0) results in the following error message for all the tests:
```js
"Cannot read properties of undefined (reading 'REACT_APP_SC_ATTR')"

at <unknown> (http://localhost:3000/__cypress/src/node_modules/.vite/deps/react-data-table-component.js?v=22eeef94:649:56)
```

<img width="519" alt="image" src="https://user-images.githubusercontent.com/106742436/177316482-0d7179cb-fc07-427e-a16e-e1256d5312d1.png">

### Desired behavior

The cypress component tests should run correctly

### Test code to reproduce
```js
 "@cypress/react": "^6.0.0",
 "cypress": "^10.3.0",
 "vite": "^2.9.9",
"react": "^18.1.0",
"react-data-table-component": "^7.5.2",
 "styled-components": "^5.3.5",
```
### Cypress Version

^10.3.0

### Other
cypress config
```js
 supportFile: "cypress/support/component.js",
        specPattern: "src/**/*.test.{js,jsx}",
        devServer  : {
            framework: "react",
            bundler  : "vite"
        },
        viewportHeight: 600,
        viewportWidth : 800,
        video         : false,
```
_No response_

**Comment by astone123** [comment]
This appears to be specific to Vite. Everything worked fine in my project using Webpack. I'm still looking into the issue

**Comment by astone123** [comment]
Was able to reproduce this issue using React 17 and Vite with the dependencies mentioned. It looks like the actual error might be happening in Styled Components [here](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/constants.ts#L5).

**Comment by lmiller1990** [comment]
Probably related: https://github.com/styled-components/styled-components/issues/3744

Seems this is a more general Vite problem than something specific to Cypress.

**Comment by lmiller1990** [comment]
Update: I went into `node_modules/styled-components/dist/styled-components.browser.esm.js` and did `console.log(typeof process)` which gives `object` - this is not what you'd expect, in a regular Vite app, it's undefined. Something, somewhere, is defining a `process` object.

**Comment by lmiller1990** [comment]
I couldn't find out what the problem is exactly, but I have a work around for now: https://github.com/cypress-io/cypress/compare/styled-components?expand=1

In your `vite.config.js`, you can rewrite `process.env` to `{}` to ensure this error doesn't occur using `@rollup/plugin-replace`. [Example commit](https://github.com/cypress-io/cypress/blob/50d50c386b65579e60a76fe790b9c6ce15fdc845/npm/react/vite.config.ts#L7-L11).

```js

import { defineConfig } from 'vite'
import replace from '@rollup/plugin-replace'
import reactPlugin from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [
    replace({
     values: {
        'process.env': `(process.env || {})`,
      }, 
    }),
    reactPlugin({
      jsxRuntime: 'classic',
    }),
  ],
})
```

**Comment by lmiller1990** [comment]
I think this was related to Vite. Vite 3 is out, I wonder if this is fixed?

Happy to reopen if needed.
