### ISSUE TITLE
Allow configuration of retry BaseUrl check intervals

### ISSUE THREAD

**Issue by skjnldsv** [cypress-io/cypress#22676]
### What would you like?

Allow us to define different intervals from the cypress config or ENV

https://github.com/cypress-io/cypress/blob/e6b2466f7b219a86da46c1ac720432ef75193ca4/packages/server/lib/server-e2e.ts#L405-L407

### Why is this needed?

3000, 3000, 4000 is very arbitrary. We might need some more testing or longer waiting times

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest, we’ll close this as not planned.
