### ISSUE TITLE
cy.type() - characters jump around when "//" is encountered

### ISSUE THREAD

**Issue by wwwd3v** [cypress-io/cypress#2268]
### Current behavior:

`cy.type('https://www.google.sk')` inserts `htotps://www.gogle.sk` into the input.

I guess it's the `//` characters that cause the problem, as dropping them gets rid of the problem.

### Versions

3.0.3

**Comment by Ancinek** [comment]
I guess this is not only the case of `//` as I'm getting same results when entering some numbers, like I specified the number to be `500500500` and I get `500050500`.

**Comment by jennifer-shehane** [comment]
@Ancinek Could you provide a reproducible example? Or, if not, give some info about the type of input you are typing into?

- What type of input (`type=??`)
- Are you using a plugin for the input to do something special?
- Do you know what events the input is listening to in your code?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
