### ISSUE TITLE
WHich directory should I add my cypress in monorepo

### ISSUE THREAD

**Issue by matart15** [cypress-io/cypress#22681]
### Current behavior

I opened [discussion](https://github.com/cypress-io/cypress/discussions/22179) a month ago. But no one answers. I am creating a Bug report

I have monorepo with following directory structure handled by `turborepo`.

```txt
/root
    /pacakge.json
    /app
        /user-site-next-js
            /pacakge.json
            /tsconfig
        /admin-site-vite
            /pacakge.json
            /tsconfig
    /packages
        /shared-ui
            /pacakge.json
            /tsconfig
```

## Problem : I want to add `component test` for `shared-ui`. where should I place it?
1. `<root>/packages/shared-ui/cypress`       : tried this `cypress open` gives error. can't find webpack config. because it is nor `nextjs` or `vite`
2. `<root>/cypress/`                  : tried this `cypress open` gives error. can't find webpack config.
3. `<root>/app/admin-site-next-js/cypress` : this feels awkward. Because, Component tests have to sit together with admin `integration tests`

### Test code to reproduce

very simple turborepo

### Cypress Version

10.3.0

**Comment by matart15** [comment]
@emilyrohrbough

Thank you. I tried that. But my shared folder does not have any `webpack`. Other side my app uses `vite`

```
/root
    /pacakge.json
    /app
        /admin-site-vite
            /pacakge.json
            /tsconfig
    /packages
        /shared-ui
            /pacakge.json
            /tsconfig
```

when `cypress open`,  i tried both `next` and `react`

next setting fails to find `html`, while react setting fail to find `webpack`

**Comment by matart15** [comment]
sorry for bad explaining.

My project structure 
```
/root
    /pacakge.json
    /turbo.json
    /app
        /admin-site-vite
            /cypress
                /component
                    /Component.cy.tsx
            /pages
                 /index.tsx
            /pacakge.json
            /tsconfig
    /packages
        /shared-ui
            /pacakge.json
            /tsconfig
```

PROBLEM 1. Ideally I want my components tests inside `/packages/shared-ui` folder. Looks like it is not possible. Because that folder does not have a `next`, `vite` or `webpack`. Is my understanding right?

**Comment by matart15** [comment]
My project structure 
```
/root
    /pacakge.json
    /turbo.json
    /app
        /admin-site-vite
            /cypress
                /component
                    /Component.cy.tsx      <--------------------- cannot solve turbo repo path alias
            /pages
                 /index.tsx
            /pacakge.json
            /tsconfig
    /packages
        /shared-ui
            /pacakge.json
            /tsconfig
```


PROBLEM 2: I tried to add `cypress` inside `/app/admin-site-vite` folder. Because it have `vite.config` there.

But cypress test can not resolve turborepo path alias.

**Comment by matart15** [comment]
I should have created demo rpo right away. I thought it is a very simple thing that I am missing.

This is [simple repo ](https://github.com/matart15/turborepo-cypress-vite-problem)]

```sh
yarn
yarn dev   <--- vite app works
cd apps/vite-app
npx cypress open
# select component
```


![Screen Shot 2022-07-15 at 11 00 34](https://user-images.githubusercontent.com/17027219/179131760-218cc68e-90ce-4603-a1a4-a5e8dc0a3e3a.png)

**Comment by matart15** [comment]
I see. thank you. I was not aware of this config.

**Comment by ahussein3** [comment]
@matart15 have you managed in any way to solve your Problem No.1 ?

**Comment by matart15** [comment]
@ahussein3 Sorry. I forgot which project it was. Recently I am writing tests with playwright
