### ISSUE TITLE
cypress Web crash

### ISSUE THREAD

**Issue by sharozraees802** [cypress-io/cypress#22694]
### Current behavior

![image](https://user-images.githubusercontent.com/52934734/177557885-783320dc-0733-4338-a996-48dcc8b98a0a.png)

### Desired behavior

im run cypress Test almost 6 to 7 time so few time cypress web crash the 

### Test code to reproduce

![Uploading image.png…]()
im run cypress Test almost 6 to 7 time so few time cypress web crash the 

### Cypress Version

10.3.0

### Other

im run cypress Test almost 6 to 7 time so few time cypress web crash the

**Comment by RiZKiT** [comment]
Because it seems there is a low memory issue:

1. What is the environment?
- local machine, remote, docker?
- RAM size?
- Chrome version?
2. Did you already tried selecting another browser from the dropdown, electron, chromium?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
