### ISSUE TITLE
"supportFile" and "pluginsFile" settings do not accept custom values on Windows

### ISSUE THREAD

**Issue by SecondFlight** [cypress-io/cypress#2270]
### Current behavior:

The following lines are in my `cypress.json` file:

```json
{
    "supportFile": "C:/Automation/cypress/HMI/support",
    "pluginsFile": "C:/Automation/cypress/HMI/plugins"
}
```

They are causing errors like this:

```
Error: C:\Users\joshwade\AppData\Roaming\Cypress\cy\production\projects\Cypress-npm-378858878f31806ab6b47b25d03837cf\bundles\C:\Automation\cypress\HMI\support contains invalid WIN32 path characters.
```

I'm not convinced this is limited to absolute paths, as `../Automation/cypress/HMI/support/` caused a similar error.

### Desired behavior:

No error should occur, and Cypress should allow an absolute path to be set for `supportFile` and `pluginsFile`, just like it allows for `fixturesFolder`, `integrationFolder`, etc.

### Steps to reproduce:

1) Add a folder called support somewhere on your hard drive.
2) Add the following line to your `cypress.json` file:
```
    ...
    ...
    "supportFile": "C:/(path-to-containing-folder)/support",
    ...
    ...
```
3) Run a test file using `cypress open`.

At this point you should see the error appear.

### Versions

Windows 10
Cypress 3.0.3
Electron 59

**Comment by jennifer-shehane** [comment]
Since you are using Windows, could you try using `\` instead of `/` as the path separators?

```json
{
    "supportFile": "C:\Automation\cypress\HMI\support",
    "pluginsFile": "C:\Automation\cypress\HMI\plugins"
}
```

We should normalize these path separators though.

**Comment by SecondFlight** [comment]
I believe I did actually try this, but I tried it again to be sure.

I tried the following, and it produces the same error:

```json
{
    "supportFile": "C:\\Automation\\cypress\\HMI\\support",
    "pluginsFile": "C:\\Automation\\cypress\\HMI\\plugins"
}

**Comment by Saibamen** [comment]
Works in Cypress 3.1.5

Please note that `pluginsFile` must export a function.

1. Create simple file for your `pluginsFile` from docs (https://docs.cypress.io/api/plugins/writing-a-plugin.html#Plugins-API):
```
// cypress/plugins/index.js

// export a function
module.exports = (on, config) => {
  // configure plugins here
}
```
2. `supportFile` can be empty

Working `cypress.json` values for both slashes, backslashes and with space in folder name:
```
"supportFile": "C:\\cypress test\\support",
"pluginsFile": "C:/cypress test/plugins"
```

![obraz](https://user-images.githubusercontent.com/905878/53271612-e393c100-36e6-11e9-8f6d-101e90d2f8b4.png)
