### ISSUE TITLE
inconsistant of scenarios in cypress tests

### ISSUE THREAD

**Issue by mtalhabalci** [cypress-io/cypress#22703]
### Current behavior

Hello,

We've been using cypress for our UI tests.

Let's say we have 100 tests in total.

When we run the tests two times consecutively without adding nothing, we see that there were different results in the number of scenarios were tested. I mean in the first test Cypress tested 100 tests and in the second, Cypress tested 99 tests.

What can be the main cause about this?

Please let me know if my question is not clear.

Thanks in help. 

### Desired behavior

Results had to be same because nothing new added before second run.

### Test code to reproduce

This question is not about code

### Cypress Version

8.0.0

**Comment by chrisbreiding** [comment]
Are there any failures in either test run?

**Comment by mtalhabalci** [comment]
No there is no test that fails.

**Comment by chrisbreiding** [comment]
A failure in a `beforeEach` or `before` hook is the only reason tests would get skipped. Without seeing your tests, it would be impossible to say why a test would not get executed from one run to the next.

**Comment by mtalhabalci** [comment]
So what is your suggestion, can we arrange an online meeting about this. If we find a logical reason for the problem, we can comment here and close the issue.

**Comment by nagash77** [comment]
@mtalhabalci , we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
