### ISSUE TITLE
Missing invocationDetails when tests are retried more than once

### ISSUE THREAD

**Issue by rafael-anachoreta** [cypress-io/cypress#22708]
### Current behavior

Cypress does not consistently add `invocationDetails` to retried tests. This makes using custom reporters that rely on the data of that object (such as `filePath`) fail. To be more specific, only the first retried test has information about the invocationDetails.

I've created a repository where I add a custom Mocha reporter and force two retries on a test. I've left the cases for Passing, Pending and Failed in there as well for comparison's sake. 

Here is the output I get after a run:
```
Retried (attempt #1): {
  function: 'Suite.eval',
  fileUrl: 'http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js',
  originalFile: 'webpack:///./cypress/e2e/spec.cy.js',
  relativeFile: 'cypress/e2e/spec.cy.js',
  absoluteFile: '/cypress-invocation-details/cypress/e2e/spec.cy.js',
  line: 6,
  column: 3,
  whitespace: '    ',
  stack: 'Error\n' +
    '    at Suite.eval (http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js:104:3)\n' +
    '    at Object../cypress/e2e/spec.cy.js (http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js:99:1)\n' +
    '    at __webpack_require__ (http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js:20:30)\n' +
    '    at Object.0 (http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js:118:18)\n' +
    '    at __webpack_require__ (http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js:20:30)\n' +
    '    at eval (http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js:84:18)\n' +
    '    at eval (http://localhost:61508/__cypress/tests?p=cypress/e2e/spec.cy.js:87:10)\n' +
    '    at eval (<anonymous>)'
}
Retried (attempt #2): undefined
Retried (attempt #3): undefined
Retried (attempt #4): undefined
Retried (attempt #5): undefined
Retried (attempt #6): undefined
Retried (attempt #7): undefined
Retried (attempt #8): undefined
Retried (attempt #9): undefined
Retried (attempt #10): undefined
```

### Desired behavior

All retried attempts should have the same invocation data. `stack` could be the result of the previous retried attempt (rather than the original spec's).

### Test code to reproduce

https://github.com/rafael-anachoreta/cypress-invocation-details

### Cypress Version

12.12.0

**Comment by BlueWinds** [comment]
Thank you for the clean repro! I've run into this myself (we have an internal cypress -> honeycomb reporter I wrote) but never tracked it down so precisely. Sending this over to the e2e team to look into it.

**Comment by rafael-anachoreta** [comment]
I've retested it on v12.12.0 and I can confirm it still happens. I've updated the repro repository and the OP to reflect that.
