### ISSUE TITLE
No error message when get 400 status on requests with formData

### ISSUE THREAD

**Issue by listana** [cypress-io/cypress#22705]
### Current behavior

Send reques with bad data, expecting error 400.
Here I upload file with no blob inclued in FormData
```
 cy.request({
        url: `${cameras}/v1/files`,
        method: 'POST',
        headers: {
          'content-type': 'multipart/form-data'
        },
        body: formdata
      })
```

In postman I see error message: `"Not supported blob", in cypress it is empty: {}`
![image](https://user-images.githubusercontent.com/47680964/177732154-a4dc27c7-0372-4585-98f5-947e849d70d9.png)
![image](https://user-images.githubusercontent.com/47680964/177732271-b6418879-6312-46b4-bb04-fe1e345f59cf.png)

So I cannot write negative tests in requests with formData.
If I send data in json format instead of formData, its OK.

### Desired behavior

```
{
    "error": "BadRequest",
    "description": "Not supported blob"
}
```

### Test code to reproduce

```
 cy.request({
        url: `${cameras}/v1/files`,
        method: 'POST',
        headers: {
          'content-type': 'multipart/form-data'
        },
        body: formdata
      })
```

### Cypress Version

Cypress binary version: 7.6.0

**Comment by BlueWinds** [comment]
https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/request.cy.js#L478 contains our tests around `cy.request`, which I hope will be helpful - it contains an example of sending both `FormData` and `Blob`. Hopefully this is some help, figuring out why your case differs from our existing automated test.

**Comment by listana** [comment]
I found that I'm using old version of cypress: 7.6.0. It is not reproducing in latest version: 10.3.0

**Comment by listana** [comment]
@BlueWinds 
Can't see negative test for getting error message in case of sending form-data in your autotests.

**Comment by BlueWinds** [comment]
We don't generally support quite old versions of Cypress like 7.6 - if you're not seeing the issue in 10.x, then upgrading sounds like a very reasonable solution. :)
