### ISSUE TITLE
NPM install of 10.3.0 is failing

### ISSUE THREAD

**Issue by LouisGinger** [cypress-io/cypress#22706]
### Current behavior

attempting to upgrade from 10.0.0 to 10.3.0
`npm install -D cypress@10.3.0` fails
`npm install -D cypress@10.2.0` succeeds=
errors shown below. Can't be  proxy issue as 10.2.0 succeeded

```
npm ERR! Cypress Version: 10.3.0
npm ERR! [FAILED] The Cypress App could not be downloaded.
npm ERR! [FAILED]
npm ERR! [FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR! [FAILED]
npm ERR! [FAILED] Otherwise, please check network connectivity and try again:
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] URL: https://download.cypress.io/desktop/10.3.0?platform=win32&arch=x64
npm ERR! [FAILED] Error: self signed certificate in certificate chain
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] Platform: win32-x64 (10.0.19044)
npm ERR! [FAILED] Cypress Version: 10.3.0
```

### Cypress Version

10.3.0

### Package Manager

npm

### Operating system

Windows

**Comment by astone123** [comment]
@LouisGinger could you try passing the `--verbose` flag in your install command for `10.3.0` and post the output here?
```
npm install --verbose -D cypress@10.3.0
```

This might give us more info about what's going on. Thanks!

**Comment by marktnoonan** [comment]
@LouisGinger we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
