### ISSUE TITLE
Cypress runner completely freezes when navigating to the particular page. 

### ISSUE THREAD

**Issue by valeria-chernikova** [cypress-io/cypress#22710]
### Current behavior

After upgrading from 9.5.0 to 10.0.3 Cypress freezes when navigating to a particular page. The runner doesn't react at all. I can only force close it. Nothing unusual in the console. 

### Test code to reproduce

![image](https://user-images.githubusercontent.com/81378319/177799431-d227c29b-cb6e-4e1f-8a69-ce02587bdd11.png)

### Cypress Version

10.0.3

**Comment by warpdesign** [comment]
I am also having some weird freezes since upgrading to v10.

@chrisbreiding are you using `testing-library`? I think it might be related to this, but if you are not using it I may rule that out as cause of the freezes.
