### ISSUE TITLE
Cypress does not follow redirect for CloudFlare Access

### ISSUE THREAD

**Issue by TeoTN** [cypress-io/cypress#22712]
### Current behavior

I have my environment protected by CloudFlare Access. It is configured so that when I pass service token credentials as headers, it will bypass the usual authentication, and will redirect to the underlying page.

For example, if I run `curl` with appropriate headers and a flag to follow redirects, it will get authenticated:
```
curl -H "CF-Access-Client-Id: [CLIENT_ID_REDACTED].access" -H "CF-Access-Client-Secret: [CLIENT_SECRET_REDACTED]" -I -L https://[PROJECT_DOMAIN]/

HTTP/2 302
# Prints response headers for first response

HTTP/2 200
# Prints response headers for redirected response
```

However, Cypress (`cy.visit`) does not follow the redirect and gets stuck on the login page.

### Desired behavior

In this situation Cypress should follow the redirects as directed by CloudFlare Access page.

### Test code to reproduce

```
  it('finds page title', () => {
    const clientId = Cypress.env('CLOUDFLARE_ACCESS_CLIENT_ID');
    const clientSecret = Cypress.env('CLOUDFLARE_ACCESS_CLIENT_SECRET');
    cy.visit('/', {
      headers: {
        'CF-Access-Client-ID': clientId,
        'CF-Access-Client-Secret': clientSecret,
      },
    });

    cy.contains('Page Title');
  });
```

### Cypress Version

10.3.0

**Comment by TeoTN** [comment]
My bad, apparently it's an issue within CloudFlare Access, after digging deeper I found out that it's not redirecting headers. Closing the issue.

**Comment by ypyrko-hb** [comment]
hey @TeoTN have you been able to solve this issue? Thanks!

**Comment by javaha74** [comment]
You need to tweak access settings in CloudFlare -> use serviceAuth action instead of allow or bypass. Here is another related chat in CloudFlare community that tells more about this same issue: https://community.cloudflare.com/t/cf-access-client-id-not-even-recognized/497497
