### ISSUE TITLE
Expect a button to be a button (assertion: 'to.be')

### ISSUE THREAD

**Issue by GremlinX** [cypress-io/cypress#22721]
### Current behavior

Cypress cannot find a button when I use method/assertion ".should('be.a', 'button')"
I couldn't find anything about it or how to fix it. 
![image](https://user-images.githubusercontent.com/50713742/178042420-e0f44d96-1d0f-4dd4-b08c-00a85902f80c.png)

### Desired behavior

Example: 
```html
<span>
    <input> <!-- I'm getting 'cy.get()' here and when i use '.next()' --> 
    <button> <!-- I'm expecting this button to be a button --> 
</span>
```
I'm expecting that the next attribute of <input> is a button

### Test code to reproduce

```js
cy.get('[formcontrolname="cdPaisOrigem"] input', {timeout:60000})
.should('exist')
.and('be.empty')
.next()
.should('be.a', 'button')
```

### Cypress Version

9.3.0

**Comment by astone123** [comment]
@GremlinX Thanks for filing an issue. I don't think that this assertion can be used to assert which type of element we're looking at. From looking at the [Chai documentation](https://www.chaijs.com/api/bdd/#method_a) for this method, it looks like it can only be used to assert a specific data type for a variable.

For the example provided, I would probably use the `get` function to imply that the element is a button, like this
```ts
cy.get('button')
```
but if you really need to assert that the element after the input is a button, you can check the `tagName` prop on the element like this
```ts
cy.get('input')
.should('exist')
.and('be.empty')
.next()
.should('have.prop', 'tagName', 'BUTTON')
```

**Comment by GremlinX** [comment]
Thank you very much! @astone123
