### ISSUE TITLE
Update from 10.2.0 to 10.3.0 produces flaky tests (only headless)

### ISSUE THREAD

**Issue by MrCube42** [cypress-io/cypress#22727]
### Current behavior

We updated from cypress 10.2.0 to 10.3.0. This makes 2 of our tests fail sometimes. I am currently not able to share some code but I'll try to get a minimal reproduction soon. As long as this is not yet available I'll describe what fails (in both of these tests):

- We visit a page
- A welcome screen appears in a modal dialog that we confirm (`click()`). There is a short close-animation for the modal.
- Afterwards we want click a specific button on the underlying UI page. We query and click the element with `contains('UI text').click()`. The button is not directly located in the visible area but is inside of the scrollable area down below.
- However since update to 10.3.0 the `contains` query fails most of the time

I could not find anything related to our setup in the changelog (https://docs.cypress.io/guides/references/changelog#10-3-0) but I suppose the issue must be somewhere in the diff between these 2 versions (https://github.com/cypress-io/cypress/compare/v10.2.0...v10.3.0).

Environment details:
- The E2E tests run agains a publicly deployed version of the application
- The E2E test itself runs in a Jenkins pipeline based on `cypress/browsers:node16.14.0-chrome99-ff97` or locally
- The test itself is run headless. Called with `cypress run` (uses Electron 100 by default)
- The tests won't fail with cy:open or firefox, only with cy:run and electron 100
- The tests only fail against the prod-ready deployed version, not when the app is run locally
- The tests won't fail with cy:run and electron 100 when 10.2.0 is used

### Desired behavior

Although there are some parts that may cause issues (like the close animation, the button at the bottom of the scroll page) these tests run reliably in 10.2.0. Only updating cypress dependency to 10.3.0 will make these tests fail. These tests should not fail in 10.3.0.

### Test code to reproduce

I'll try to prodive a more detailed repro soon.

### Cypress Version

10.3.0

**Comment by chrisbreiding** [comment]
A more detailed, reliable reproduction would be appreciated. Otherwise, it will be difficult to move forward with this and debug the issue.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by MrCube42** [comment]
Sorry, for being too slow. However, I just wanted to inform you that the problem is gone with the latest version `10.3.1` :shrug:
