### ISSUE TITLE
cy.request() url trailing slash turns POST request into GET

### ISSUE THREAD

**Issue by harjis** [cypress-io/cypress#22720]
### Current behavior

Hi! I noticed that trailing slash (`/`) in cy.request() url seems to turn all requests into GET even if some other method has been used.

### Desired behavior

My expectation was that the defined method would dictate type of request regardless if the url had trailing slash or not

### Test code to reproduce

Code which sends GET request:
```ts
describe("cy.request()", () => {
  it("should be POST request", () => {
    cy.request("POST", "/api/customers/", {
      name: "test",
    }).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body.name).to.eq("test")
    })
  })
})
```

Code which sends POST request:
```ts
describe("cy.request()", () => {
  it("should be POST request", () => {
    cy.request("POST", "/api/customers", {
      name: "test",
    }).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body.name).to.eq("test")
    })
  })
})
```

### Cypress Version

10.3.0

**Comment by BlueWinds** [comment]
I'm not seeing the behavior you described. Here's a completely self-contained example using a public server:

```
describe.only("cy.request()", () => {
  it("passes", () => {
    cy.request("POST", "https://httpbin.org/anything/foo", {
      name: "test",
    }).then((res) => {
      expect(res.body.json.name).to.eq("test")
      expect(res.body.method).to.eq("POST")
    })

    cy.request("POST", "https://httpbin.org/anything/foo/", {
      name: "test",
    }).then((res) => {
      expect(res.body.json.name).to.eq("test")
      expect(res.body.method).to.eq("POST")
    })
  })
})
```

According to the echo server (https://httpbin.org/#/Anything/post_anything__anything_), both requests are POSTs as expected. Seems like there might be something else going on, possibly in your server, rather than in Cypress?

**Comment by harjis** [comment]
That seems to be correct. It looks like this issue only happens when using Next.js server. I'll open issue on their side. Thanks for your help!

![Screenshot 2022-07-12 at 8 11 00](https://user-images.githubusercontent.com/2409276/178413739-59d9f1d5-831a-4740-9b67-865707c8c86b.png)

**Comment by BlueWinds** [comment]
Glad we could help! Tracking stuff down can always be tricky when there are so many moving parts.
