### ISSUE TITLE
Why does cypress attempt to contact a Cloudflare host during install?

### ISSUE THREAD

**Issue by afeinman-mitre** [cypress-io/cypress#22737]
### Current behavior

When I try to install cypress in a constrained environment (i.e. one with only whitelisted connections allowed), `yarn add cypress` hangs.

Investigation reveals that there is an attempt to connect to a Cloudflare IP (`104.16.17.35`) during the install step. 

What is this? Can it be removed from the install process? Can _install_ succeed without additional network dependencies, so I can at least compile my code?

### Debug logs

There are no debug logs generated from this step, as yarn never completes and cypress hasn't started yet (so DEBUG=cypress:* does nothing).

strace revealed the connections as the hang point.

### Cypress Version

10.3.0

### Package Manager

yarn

### Operating system

other

### Other

EC2 instance. No proxy, but constrained set of network connections allowed.

**Comment by emilyrohrbough** [comment]
Cypress is released in two parts. Part 1 - the Cypress CLI which is distributed to NPM. Part 2 - the binary built as an electron application which is stored in an ASWS S3 bucket. When you run `npm install cypress` the post install script will download the binary from AWS to allow you to run Cypress.

Given you are running on an EC2 instance, there are a few options you could explore to have Cypress preinstalled on the image used to initialize your EC2 instance. Check out our [Installing Cypress docs!](https://docs.cypress.io/guides/getting-started/installing-cypress#Installing).

**Comment by afeinman-mitre** [comment]
Hmm. We're trying to work around this using the docker images, but the code won't compile without cypress's libraries available in node_modules. Is there a way to tell cypress install just to install the CLI / types / etc. and not download the binary?

**Comment by BlueWinds** [comment]
@afeinman-mitre - Do the env variables here https://docs.cypress.io/guides/references/advanced-installation#Environment-variables work for you? Can disable downloading the binary, provide a mirror at a different URL, or use a local copy you've pre-provisioned onto your docker image.

**Comment by afeinman-mitre** [comment]
Potential lifesaver! I missed the "Advanced Installation" section of the installation instructions.
