### ISSUE TITLE
Cannot connect to Chrome after update cypress 10.3.0 on M1 Mac

### ISSUE THREAD

**Issue by cupcakepanda89** [cypress-io/cypress#22744]
### Current behavior

- Everytime when I run cypress v 10.3.0 with Chrome select it gives the error
`"Still waiting to connect to Chrome, retrying in 1 second" `
- So I switch to Electron but it gives this error 
`rosetta error: /var/db/oah/0535757b246044edaedd966c04e1e968410c569b39b1a7a5ecd33e84f293a1bd/a96de7596d034b44c47d68b1fa634c4d06d05e12214991ccbae6f77b1e125d61/fsevents.node.aot: attachment of code signature supplement failed: 1`
- I want to follow this blog for work around https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/ 
- But it doesn't work, and the blog mentioned that it should be fixed in 10.2 and 10.3
- Note: I also encounter this error. 
`Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb503e3948) and /Users/tit/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x111fa89c8). One of the two will be used. Which one is undefined.`
- which is similar to https://github.com/cypress-io/cypress/issues/21615 
### Desired behavior

I can run cypress v 10.3.0 with Chrome, Electron and Firefox

### Test code to reproduce

1. npm install 
2. cypress open 
3. run cypress with Chrome or Electron or Firefox

### Cypress Version

10.3.0

### Other

MacOS: Montery 12.4 (Apple M1 Pro)

**Comment by marktnoonan** [comment]
@cupcakepanda89  are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
