### ISSUE TITLE
Screenshot path is different when running headless and open

### ISSUE THREAD

**Issue by baronvonbirra** [cypress-io/cypress#22753]
### Current behavior

While using [cypress-image-snapshot](https://github.com/jaredpalmer/cypress-image-snapshot) I noticed that, since Cypress v10, the path where screenshots (or snapshots in this case) are saved differs when Cypress is run in headless and open modes. I only noticed this issue when having features organised inside folders.
So, imagine I have this structure for my tests:

```
- cypress
    - e2e
        - testFolder1
            - testFeature1.cy.feature
        - testFolder2
            - testFeature2.cy.feature
```

Now, if I run testFeature1 in open mode, snapshot is saved at _cypress/snapshots/testFeature1.png_, but when I ran headless mode, the snapshot is saved at _cypress/snapshots/testFolder1/testFeature1.cy.feature/testFeature1.png_ . 

An issue is open an cypress-image-snapshot [board](https://github.com/jaredpalmer/cypress-image-snapshot/issues/252), but it looks like this is the [expected behaviour](https://docs.cypress.io/guides/references/migration-guide#Generated-Files)?

### Desired behavior

Screenshots should be stored in the same folder, no matter if it's launched in open or headless mode.

### Test code to reproduce

Simply execute:
`cy.matchImageSnapshot(snapshot);` 

### Cypress Version

10.2.0

**Comment by marktnoonan** [comment]
Hi @baronvonbirra, you're correct that as of Cypress 10 and the switch from `testFiles` to `specPattern` this is currently expected. You're not the first person to mention this change is confusing so I'm going to keep this issue open as a feature request -- or possibly convert it to a GH discussion.

**Comment by imagoiq** [comment]
@marktnoonan is there an easy way to get this relative path in `Cypress.on("test:after:run", (test, runnable)`?

That would be very useful for that for example:
https://github.com/adamgruber/mochawesome-report-generator/issues/130#issuecomment-636368062

**Comment by marktnoonan** [comment]
@imagoiq I don't see a great way to grab it in `test:after:run` off the top of my head, but the `onAfterScreenshot` callback can provide the path which might be useful: https://docs.cypress.io/api/commands/screenshot#Get-screenshot-info-from-the-onAfterScreenshot-callback

For example:

```js
   cy.screenshot({
      onAfterScreenshot ($el, { path }) {
        console.log(path)
      },
    })
```

**Comment by imagoiq** [comment]
Thanks, I actually find out that I can access to the path through `Cypress.spec.relativeToCommonRoot`, but it isn't exposed into types. Is it a bug?

**Comment by marktnoonan** [comment]
@imagoiq this is not a but it's not part of the public API either, it looks like this is something we add to the spec object for internal use within Cypress. There's nothing to stop you using it, but the risk is it might be removed or changed in any release.

**Comment by 0xc0d3r** [comment]
@nagash77 @marktnoonan Can you suggest any workaround for now? Our internal test reports were broken as screenshots and videos are not loading.

**Comment by emilyrohrbough** [comment]
duplicate of https://github.com/cypress-io/cypress/issues/24052
