### ISSUE TITLE
Add loggedIn property to Check for Updates call

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22754]
### What is needed?

On network call to check for latest version for potential update, add a boolean `true`/`false` flag to request to indicate whether user is logged in.

### Why is it needed?

**Development Notes**
Can be passed through as an `x-*` header on the request made in this func?
`VersionsDataSource:#getLatestVersion()`

Will need to ensure logged-in state is available prior to this call being made without circular reference/blocking

**Comment by mike-plummer** [comment]
@pstakoun Planning to send thru a `x-logged-in` header on that request with value `true`/`false` if that works for you. Just to confirm, that request gets kicked off immediately after the launchpad is opened, so we'll just be capturing login state at the time of app launch

**Comment by mike-plummer** [comment]
> @mike-plummer is this the same way those other properties are sent? Anything we'd have to do differently to consume this one? Any chance the login state isn't there when this request kicks off or changes right after?

@pstakoun Correct, this is the same sort of change we made to track framework & dev server (`x-framework`, `x-dev-server` headers) under [UNIFY-1703](https://cypress-io.atlassian.net/browse/UNIFY-1703). There wasn't a corresponding backend ticket to reflect what if any changes were needed in analytics tools to grab those headers - is there a good contact person for the tooling you're using to analyze these hits that I could check with?

The Check for Updates request is made after the user state is resolved, so it should accurately reflect whether you're already logged in or not, but will not capture subsequent login attempts after the request is made. The update manifest request is actually made twice during a typical "cypress:open" flow - once when launchpad opens, and again once a testing type if selected, so there's a chance a user could open launchpad, not be logged in for the first request, then login and select a testing type causing a second request to reflect them as logged in

**Comment by pstakoun** [comment]
@mike-plummer perfect. @estrada9166 or @ax-vasquez would likely have context around whether or not this will be captured automatically. I believe that it will be and there is no action required on the backend, but would be good to confirm that.
