### ISSUE TITLE
Cannot find name 'cy'

### ISSUE THREAD

**Issue by dominikabieder** [cypress-io/cypress#22765]
### Current behavior

do I need to add `/// <reference types="cypress" />` in every cy file?

If I don't, despite the following config, I'm still getting `TS2304: Cannot find name 'cy'.` the error shows up only in webstorm, in cypress console it works ok.

tsconfig.json
`"types": ["cypress", "@testing-library/cypress", "node" ]`

package.json
```
"cypress": "10.3.0"
"@testing-library/cypress": "8.0.3",
"@types/node": "18.0.3",
```

### Desired behavior

not having to place `/// <reference types="cypress" />` in every file

### Test code to reproduce

given above

### Cypress Version

10.3.0

**Comment by dominikabieder** [comment]
ok, so turns out I wasn't including cypress folder in tsconfig. now that I do, it complains about isolatedModules. is there a fix to that without turning the isolatedModules to false and not having to write `/// <reference types="cypress" />` at the beginning of each file?

`'sof.cy.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.`

**Comment by chrisbreiding** [comment]
Have you tried the [recommended tsconfig.json configuration](https://docs.cypress.io/guides/tooling/typescript-support#Install-TypeScript)?

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by bryantobing12** [comment]
> 'sof.cy.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

@chrisbreiding I got the same error when running `tsc --noEmit --incremental false`



> Have you tried the [recommended tsconfig.json configuration](https://docs.cypress.io/guides/tooling/typescript-support#Install-TypeScript)?

I have tried that. but still got the same error. 

The only way to remove the error is to add `export {}` in every `cypress .ts` file which is I think is ugly.

I also notice that [nextjs example with cypress](https://github.com/vercel/next.js/blob/canary/examples/with-cypress/cypress/e2e/app.cy.ts) does that.
