### ISSUE TITLE
Version 102 of Firefox causes flaky tests when using `cy.type()` (only headless)

### ISSUE THREAD

**Issue by ducktordanny** [cypress-io/cypress#22760]
### Current behavior

If I'm running some of our tests in headless mode (or simply it's running in our pipeline) Firefox 102 causes the following error when I use cy.type() even though the element is not disabled and it has no issue inside Chrome:

```sh
 1) Adding new Something
       should create a new something:
     CypressError: `cy.type()` failed because it targeted a disabled element.

The element typed into was:

  > <input matinput="" class="mat-input-element mat-form-field-autofill-control ng-pristine ng-invalid cdk-text-field-autofill-monitored ng-star-inserted ng-touched" ng-reflect-id="formly_1_input_name_0" type="text" ng-reflect-type="text" ng-reflect-required="true" ng-reflect-error-state-matcher="[object Object]" ng-reflect-form="[object Object]" ng-reflect-field="[object Object]" tabindex="0" ng-reflect-placeholder="name" data-testid="somethingNameInput" id="formly_1_input_name_0" required="" data-placeholder="name" aria-required="true" aria-describedby="mat-error-0">

Ensure the element does not have an attribute named `disabled` before typing into it.

https://on.cypress.io/type
  ../driver/src/cy/commands/actions/type.ts/__webpack_exports__.default/type/handleFocused/onReady/<@https://localhost:8080/__cypress/runner/cypress_runner.js:152266:86
  tryCatcher@https://localhost:8080/__cypress/runner/cypress_runner.js:13012:23
  ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler@https://localhost:8080/__cypress/runner/cypress_runner.js:10947:31
  ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise@https://localhost:8080/__cypress/runner/cypress_runner.js:11004:18
  ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0@https://localhost:8080/__cypress/runner/cypress_runner.js:11049:10
  ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises@https://localhost:8080/__cypress/runner/cypress_runner.js:11129:18
  _drainQueueStep@https://localhost:8080/__cypress/runner/cypress_runner.js:7719:12
  _drainQueue@https://localhost:8080/__cypress/runner/cypress_runner.js:7712:24
  ../../node_modules/bluebird/js/release/async.js/</Async.prototype._drainQueues@https://localhost:8080/__cypress/runner/cypress_runner.js:7728:16
  ../../node_modules/bluebird/js/release/async.js/</Async/this.drainQueues@https://localhost:8080/__cypress/runner/cypress_runner.js:7598:14
  From Your Spec Code:
      shouldFn@https://localhost:8080/__cypress/runner/cypress_runner.js:152956:18
      should@https://localhost:8080/__cypress/runner/cypress_runner.js:153074:23
      ../driver/src/cy/assertions.ts/create/injectAssertion/<@https://localhost:8080/__cypress/runner/cypress_runner.js:148027:39
      assertions@https://localhost:8080/__cypress/runner/cypress_runner.js:148391:16
      tryCatcher@https://localhost:8080/__cypress/runner/cypress_runner.js:13012:23
      gotValue@https://localhost:8080/__cypress/runner/cypress_runner.js:12156:18
      gotAccum@https://localhost:8080/__cypress/runner/cypress_runner.js:12143:25
      tryCatcher@https://localhost:8080/__cypress/runner/cypress_runner.js:13012:23
      ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler@https://localhost:8080/__cypress/runner/cypress_runner.js:10947:31
      ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise@https://localhost:8080/__cypress/runner/cypress_runner.js:11004:18
      ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseCtx@https://localhost:8080/__cypress/runner/cypress_runner.js:11041:10
      _drainQueueStep@https://localhost:8080/__cypress/runner/cypress_runner.js:7723:12
      _drainQueue@https://localhost:8080/__cypress/runner/cypress_runner.js:7712:24
      ../../node_modules/bluebird/js/release/async.js/</Async.prototype._drainQueues@https://localhost:8080/__cypress/runner/cypress_runner.js:7728:16
      ../../node_modules/bluebird/js/release/async.js/</Async/this.drainQueues@https://localhost:8080/__cypress/runner/cypress_runner.js:7598:14
```

First, it happened in 9.6.0 then I upgraded to 10.3.0, but it was still the same issue and then I tried to run the exact same test with Firefox 101 and then it was successful.

One more thing that could be useful is that we are using angular with nx and I discovered that this issue (probably only) happens when we use Formly. If I'm running it in the browser with `npx cypress open` then it runs correctly.

### Desired behavior

It should be able to type into a field using Firefox 102 without any issue just like in chrome.

### Test code to reproduce

I'll try my best to reproduce this issue in a different repo very soon.
**Edit:** https://github.com/ducktordanny/cypress-firefox-flakiness

### Cypress Version

10.3.0

**Comment by lazurey** [comment]
I think I have a similar issue with Chrome headless, after upgrading from 10.0.1 to 10.2.0, the tests failed randomly while trying to click on a Material-UI select, it cannot open the panel after click on the select.

**Comment by nhcarrigan** [comment]
We're facing a similar issue over at freeCodeCamp - the rollout of Firefox 102 seems to cause a couple of our tests to fail but only in headless mode.

**Comment by BlueWinds** [comment]
> I'll try my best to reproduce this issue in a different repo very soon.

This would be fantastic when you have a chance, would definitely help us track down the problem to have a repro we can run directly. Same for anyone else here - if you have something I can run, it'll make it a lot easier to figure out (and fix) the problem.

@lazurey - What you're running into seems to be a separate issue. This one is particular to Firefox 102 - if you're seeing an issue in Chrome, I'd suggest a new ticket so we can look into it separately.

**Comment by marktnoonan** [comment]
Wonder if this is connected https://github.com/cypress-io/cypress/issues/22835

@BlueWinds or @tbiethman the example spec in that issue is small and suffers from the same "only errors in FF 102, in run mode, when running headlessly". Headless-only runmode errors seem quite challenging to debug!

```
describe('Reproduce the defect on webcomponent dropdown', () => {
  it('Click the angular dropdown and select the value', () => {
    cy.visit(
      'https://www.telerik.com/kendo-angular-ui/components/dropdowns/examples/dropdownlist/basic_usage/?theme=default-ocean-blue&themeVersion=5.5.0',
    )

    cy.get('button').click()

    cy.get('.k-list-item-text').contains('X-Small').click()
  })
})
```

**Comment by jpveooys** [comment]
Hi,

We had this problem in our repo and had to add some skips for Firefox as in this PR: https://github.com/defencedigital/mod-uk-design-system/pull/3357

So hopefully another potential repro there – I can list the steps to run Cypress in that repo if it helps.

**Comment by ducktordanny** [comment]
Finally, I was able to reproduce this issue, and like I've already said before it is only happening if I'm using angular formly with material and only when running Cypress in headless mode with Firefox 102.

The repo can be found here: https://github.com/ducktordanny/cypress-firefox-flakiness

**Comment by tbiethman** [comment]
@jpveooys @ducktordanny thank you both for the example reproductions. I pulled these down and confirmed your findings. It's pretty obvious there's something going wrong here.

**Comment by tbiethman** [comment]
A couple findings:
* The first FF Nightly build that exhibited the issue: https://archive.mozilla.org/pub/firefox/nightly/2022/06/2022-06-01-09-46-32-mozilla-central/
* Changeset for that build: https://hg.mozilla.org/mozilla-central/rev/a99cd6ce98c9ba944f98be7a030d760841bbd515
* This change from the set looks suspicious: https://hg.mozilla.org/mozilla-central/rev/f6b6083e77c9416f20659728143f136d4cd9f090

@ducktordanny I found that calling `.focus()` prior to `.type()` resulted in your command passing:

```js
  it('should type something', () => {
    cy.get('[data-test-id="name-input"]').focus().type('This is a test...')

    cy.get('[data-test-id="name-input"]').should('have.value', 'This is a test...')
  });
``` 

It also seems to work when forced:
```
  it('should type something', () => {
    cy.get('[data-test-id="name-input"]').type('This is a test...', { force: true })

    cy.get('[data-test-id="name-input"]').should('have.value', 'This is a test...')
  });
```

Still unsure how the linked changes are impacting headless mode specifically, but hopefully these workarounds can get you moving forward in the meantime.

**Comment by ducktordanny** [comment]
@tbiethman Thank you so much for the fast response!

FYI: I tried these suggestions of yours in our project too and unfortunately using `.focus()` wasn't enough, but forcing it did the job. I think this will be a good enough workaround for now. 💯

I'm looking forward to any other improvements related to this issue. Thank you again! 👍🏼

**Comment by mgmrx** [comment]
Hi,
we are having this issue as well with firefox in headless mode.

The workaround with focus before kind of worked. In some cases we needed to also click on the element before.
Another really strange thing is that strings that contain double apostrophes seem not to work and it looks like a newline is inserted instead. Couldn't further investigate because it's really hard to debug headless mode and video is also not working in firefox with cypress at the moment.

I just wanted to comment to give this issue more attention.

Thank you!

**Comment by mirobo** [comment]
I'm having the same issue with Cypress 10.7.0 and **Firefox 110** (headless) on Debian (Docker) also in conjunction with Angular Formly + Material.

@ducktordanny 
Did you solve this issue with upgrading to Cypress 12.1.0 (includes fix: _Fixed an issue where recent versions of Firefox in headless mode would behave inconsistently with headed_  https://github.com/cypress-io/cypress/issues/24900 .. though it concerns issues with "DOM detached" errors... but it couldn't hurt) or do you still use the mention workaround with "force: true"?

**Comment by ducktordanny** [comment]
@mirobo As I checked we don't use the `{force: true}` workaround anymore, and these were removed from our tests when we upgraded to Cypress 12.1.0, since then we had no issues related to this topic.
