### ISSUE TITLE
Forced click failing on image map

### ISSUE THREAD

**Issue by hally9k** [cypress-io/cypress#2277]
### Current behavior:
We have been using `click({ force: true })` in 3.0.2 to trigger interactions with an image map.
In 3.0.3 the test fails on the click command - `CypressError: Timed out retrying: Illegal invocation`

### Desired behavior:
Allow the forced click to interact with the image map.

Unfortunately I don't have time to reproduce this right now, apologies.

### Versions
Cypress: 3.0.3
macOS: 10.13.6
Electron 59

**Comment by brian-mann** [comment]
This has already been fixed and merged into the PR here: https://github.com/cypress-io/cypress/pull/2246

Will be released in the version.
