### ISSUE TITLE
Framework detection doesn't occur when opening Cy with `cypress open --component`

### ISSUE THREAD

**Issue by JessicaSachs** [cypress-io/cypress#22777]
### Current behavior

I have a project configured for e2e and I want to set CT up.

I ran:

```sh
cypress open --component --browser=chrome
```

and the framework is not detected.

**Workaround**: If you click "Back" on the Testing Type Selection page in the launchpad and click on the "Component Testing" testing type card, it correctly detects the framework as Vite + Vue 3.

### Desired behavior

Detect the correct framework.

### Test code to reproduce

This project, at this commit (has e2e, but not ct yet): https://github.com/vueschool/vuejs-forge-the-project/commit/4b10ffd7d74b391832b763a6b846c0c87a383137

In this project, E2E was already setup before I tried to open Cy CT 10.2.0 for the first time on this machine.

### Cypress Version

10.2.0

**Comment by astone123** [comment]
Thanks @JessicaSachs, I was able to reproduce this with the example that you provided.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22777?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
