### ISSUE TITLE
Your supportFile is missing or invalid error on Jenkins job for cypress 10 tests

### ISSUE THREAD

**Issue by hassankaz** [cypress-io/cypress#22776]
### Current behavior

I'm getting the error below in my Jenkins job for cypress 10 tests.  The file in question is there on the path.  The same config works fine locally. My cypress version is 10.1.0. Is it ok to use non default support file? 

+ NO_COLOR=1 ../../cypress/bin/cypress run --spec cypress/e2e/**/*.smoke.spec.js
Your supportFile is missing or invalid: cypress/support/commands.js

Thank you so much in advance for your help!

### Desired behavior

Be able to find support files and run tests on jenkins for cypress 10 tests. 

### Test code to reproduce

na

### Cypress Version

10.1.0

**Comment by hassankaz** [comment]
Related issue:
https://github.com/cypress-io/cypress/issues/22040

**Comment by BlueWinds** [comment]
Can you provide the contents of your cypress.config.js file and of your support file?

It looks like your support file is trying to import `cypress/support/commands.js` and not finding it, but I don't have enough information here to reproduce the issue or even take a guess at what might be going wrong.

**Comment by hassankaz** [comment]
commands.js is under cypress/support, along with e2e.js.

**Comment by tbiethman** [comment]
@hassankaz I took a look at your config/setup files, nothing there sticks out to me as troublesome. It would be helpful if you could execute a run with debug logs enabled, it might help us narrow down the issue.

```
DEBUG=cypress:* NO_COLOR=1 ../../cypress/bin/cypress run --spec cypress/e2e/**/*.smoke.spec.js
```

**Comment by hassankaz** [comment]
Thank you @tbiethman. I ran the job with the flag, and got the following in the log (more detailed version of the previous 'support file not found'. but the file is there on the Jenkins server;

https://on.cypress.io/support-file-missing-or-invalid
    at setSupportFileAndFolder (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/server/lib/config.js:341:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ProjectConfigManager.buildBaseFullConfig (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:283:26)
    at ProjectConfigManager.getFullInitialConfig (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:326:34)
    at ProjectConfigManager.setupNodeEvents (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:123:28)
 {
  isCypressErr: true,
  type: 'SUPPORT_FILE_NOT_FOUND',
  details: undefined,
  messageMarkdown: 'Your `supportFile` is missing or invalid: `./cypress/support/e2e.js`\n' +
    '\n' +
    'The supportFile must be a .js, .ts, .coffee file or be supported by your preprocessor plugin (if configured).\n' +
    '\n' +
    'Fix your support file, or set supportFile to `false` if a support file is not necessary for your project.\n' +
    '\n' +
    'If you have just renamed the extension of your supportFile, restart Cypress.\n' +
    '\n' +
    'https://on.cypress.io/support-file-missing-or-invalid',
  originalError: undefined,
  stackWithoutMessage: '    at setSupportFileAndFolder (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/server/lib/config.js:341:23)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at ProjectConfigManager.buildBaseFullConfig (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:283:26)\n' +
    '    at ProjectConfigManager.getFullInitialConfig (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:326:34)\n' +
    '    at ProjectConfigManager.setupNodeEvents (/root/.cache/Cypress/10.3.1/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:123:28)\n'
}
Your supportFile is missing or invalid: ./cypress/support/e2e.js

The supportFile must be a .js, .ts, .coffee file or be supported by your preprocessor plugin (if configured).

Fix your support file, or set supportFile to false if a support file is not necessary for your project.

If you have just renamed the extension of your supportFile, restart Cypress.

https://on.cypress.io/support-file-missing-or-invalid
2022-07-22T17:42:09.819Z cypress:server:cypress calling exit 1
2022-07-22T17:42:09.819Z cypress:server:cypress about to exit with code 1
2022-07-22T17:42:09.820Z cypress:server:browsers browsers.kill called with no active instance
2022-07-22T17:42:09.820Z cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 0, proxyRequestsReceived: 0, immediatelyMatchedRequests: 0, unmatchedRequests: 0, unmatchedPreRequests: 0 }
2022-07-22T17:42:09.870Z cypress:cli child event fired { event: 'exit', code: 1, signal: null }
2022-07-22T17:42:09.871Z cypress:cli Stopping Xvfb
2022-07-22T17:42:09.872Z cypress:cli child event fired { event: 'close', code: 1, signal: null }
[Pipeline] }

**Comment by tbiethman** [comment]
Thanks @hassankaz, where there any logs output prior to the error being thrown?

Another thing you can try is just removing your `supportFile` entry from the config altogether, as the default value is `cypress/support/e2e.{js,jsx,ts,tsx}` and should align with your setup. If that works, it would point to an issue in our config resolution or our globbing in certain environments.

**Comment by hassankaz** [comment]
Hi Tyler,

I ran the job with 'supportFile: false' and after that I don't see the
error about the support file, but then i see that it can't find the spec
files;

{
  isCypressErr: true,
  type: 'NO_SPECS_FOUND',
  details: undefined,
  messageMarkdown: "Can't run because `no spec files` were found.\n" +
    '\n' +
    'We searched for specs matching this glob pattern:\n' +
    '\n' +
    '  > ***@***.***/cl-cypresstests/cypress/e2e/**/*.smoke.spec.js',
  originalError: undefined,


However, the file are there on the server. I'm not sure why it can't
find both of my specs and support files.

This works fine locally, so I assume it has something to do with a
jenkins server (ubuntu).


Thank you again so much for your help with this.

kazue

**Comment by tbiethman** [comment]
@hassankaz thanks for following up. There's definitely something going wrong here that I'm not picking up on yet. I've tried recreating the issues you're seeing with similar setups similar to yours, but I haven't been able to recreate this.

Can you provide the `cypress:*` DEBUG logs for your execution with the supportFile disabled? Please include the full log, from start to end, as there is data to be gleaned from logs that aren't immediately related to the error.

You also mentioned that this same config works locally. Do the _commands_ you're executing differ locally and in CI? If so, could you provide both of those for reference? I see `../../cypress/bin/cypress` in the original post and it makes me wonder where that cypress installation is coming from.

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
