### ISSUE TITLE
Cypress throws an error trying to delete cookie without name

### ISSUE THREAD

**Issue by VanheeAyron** [cypress-io/cypress#22787]
### Current behavior

Since using the cypress session api I've been getting an error on one of my tests. This is because the session is trying to delete a cookie that doesn't have a name. Is there a workaround for this issue?

(The empty cookie is caused by a bug in our wysihtml5 editor and only occures in Firefox)

![image](https://user-images.githubusercontent.com/66973758/178941582-02387ef8-be42-48c9-b3a2-a31fe50602c8.png)

### Desired behavior

Delete the cookie, even though it doesn't have a name.

### Test code to reproduce

In the cypress app, run a test using sessions in Firefox. When the test is done add a cookie. In Firefox you can create a cookie and delete the name. Rerun the test and you will get the error.

![image](https://user-images.githubusercontent.com/66973758/178941086-45e8060e-d378-433e-9ad6-c4281732881e.png)

### Cypress Version

10.3.0

**Comment by chrisbreiding** [comment]
I was able to reproduce this with the following:

Server route:

```js
  app.get('/set-no-name-cookie', (req, res) => {
    res
    .header('Set-Cookie', '=value')
    .send('<html><body><h1>No-name cookie set</h1></body></html>')
  })
```

Spec:

```js
  describe('errors clearing no-name cookie', () => {
    beforeEach(() => {
      cy.session('foo', () => {
        cy.visit('/set-no-name-cookie')
      })

      cy.visit('/fixtures/generic.html')
    })

    it('test 1', () => {
      cy.get('body')
    })

    // this one fails with "Removing cookie failed"
    it('test 2', () => {
      cy.get('body')
    })
  })
```

Or without `cy.session()` more simply, since `cy.clearCookies()` uses the same mechanism:

```js
  it('errors clearing no-name cookie', () => {
    cy.visit('/set-no-name-cookie')
    cy.clearCookies()
  })
```
