### ISSUE TITLE
Cypress always crashed when updating code continuously

### ISSUE THREAD

**Issue by brianle1995** [cypress-io/cypress#22781]
### Current behavior

Write test script on first-test.cy.js file and update code. Ctrl+S and view the test run

### Desired behavior

Cypress is running properly with the latest source code.

### Test code to reproduce

```js

describe('My First Test', () => {
    let item = "Brian Le 19";
    beforeEach(( )=> {
      cy.visit('https://example.cypress.io/todo');
      cy.title().should('eq', 'Cypress.io: Kitchen Sink');
      cy.xpath('//a[text()="All"]').click().as("ClickAllTab")
    });

    it('Scenario 1', () => {
      //aliases
      cy.get('@ClickAllTab');
      cy.xpath('//input[@data-test="new-todo"]').type(item).type('{enter}');
      cy.xpath('//span[@class="todo-count"]').invoke('text').should('eq', '3 items left');
      cy.xpath('//input[@class="toggle" and @type="checkbox"]/following-sibling::label').should("contains.text", item);
      cy.xpath('//label[text()="'.concat(item).concat('"]//following-sibling::button')).invoke('show').click();
      cy.xpath('//span[@class="todo-count"]').invoke('text').should('eq', '2 items left');
    })

    it('Scenario 2', () => {
      //aliases
      cy.get('@ClickAllTab');
      cy.xpath('//input[@data-test="new-todo"]').type(item).type('{enter}');
      cy.xpath('//span[@class="todo-count"]').invoke('text').should('eq', '3 items left');
      cy.xpath('//label[text()="'.concat(item).concat('"]//following-sibling::button')).invoke('show').click();
      cy.xpath('//span[@class="todo-count"]').invoke('text').should('eq', '2 items left');
    })
  })
```

### Cypress Version

10.3.0

### Other

OS information:
![Screen Shot 2022-07-14 at 11 57 39](https://user-images.githubusercontent.com/104203034/178902424-ecd88d86-bb92-493d-8a3b-262e9048215d.png)

Issues:
![Screen Shot 2022-07-14 at 11 51 09](https://user-images.githubusercontent.com/104203034/178902262-f02777c2-8434-4cc2-ad37-1a27160f40b2.png)

![Screen Shot 2022-07-14 at 11 51 54](https://user-images.githubusercontent.com/104203034/178902284-add1ffd6-9d87-46ee-b497-63e104fb4222.png)

![Screen Shot 2022-07-14 at 11 56 21](https://user-images.githubusercontent.com/104203034/178902321-3e32116b-6fa9-47cd-b200-492f1061bbba.png)

**Comment by chrisbreiding** [comment]
Could you run Cypress with [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) and post the output? That might help diagnose the issue.

```sh
DEBUG=cypress:*,cypress-verbose:* cypress open 
```

**Comment by brianle1995** [comment]
Below is the output
![Screen Shot 2022-07-18 at 10 37 42](https://user-images.githubusercontent.com/104203034/179661416-a274c270-5431-4778-a626-69bad938aed7.png)
![Screen Shot 2022-07-18 at 10 39 45](https://user-images.githubusercontent.com/104203034/179661425-5a9e7bcd-2b43-4934-a231-1b6fcf43b6bb.png)

**Comment by sonudavidson** [comment]
> @brianle1995, i setup a repo and ran your test successfully with cypress 10.3.1 and cypress-xpath 2.0.0. If you're still seeing this issue with those versions, could you setup a reproducible repo for us? Generally I use the [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) template as good starting point.

Hi @mjhenkes, Could you please share the repo info you created for latest cypress and cypress-xpath. I'm getting runtime errors that cy.xpath is not a function.

**Comment by mjhenkes** [comment]
@sonudavidson, https://github.com/mjhenkes/issue-22781

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
