### ISSUE TITLE
Docker image cypress/included:10.2.0 fails on ARM with qemu: uncaught target signal 5

### ISSUE THREAD

**Issue by r3vans** [cypress-io/cypress#22783]
### Current behavior

docker run -it --rm cypress/included:10.2.0 fails on my Apple silicon Mac with 
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped 

### Desired behavior

I should be able to run Cypress in Docker on my MacBook Pro (16-inch, 2021)

### Test code to reproduce

```
docker run -it --rm cypress/included:10.2.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
```

### Cypress Version

10.2.0

### Other

Latest Docker  Engine: 20.10.17 on the latest MacOS Monterey 12.4
I have tried copying the Dockerfile and building on ARM but the build itself fails with the same error.

**Comment by astone123** [comment]
@r3vans the image for 10.2.0 won't be able to run on your M1 as it wasn't built to target ARM architecture. We just published [an image for 10.3.0](https://hub.docker.com/layers/included/cypress/included/10.3.0/images/sha256-729ab5cf9ea9111a3f88089a6dfa3b3fa09856d68167946a5a68afee8de78128?context=explore) that is multi-architecture for ARM and AMD and should be able to run on your machine.

Could you try using the `cypress/included:10.3.0` image instead? Thanks

**Comment by marktnoonan** [comment]
We are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.

**Comment by r3vans** [comment]
Sorry - a very belated thanks. 10.3.0 solved my problem!!
