### ISSUE TITLE
Optional chaining (?.) does not work when used inside of node_modules

### ISSUE THREAD

**Issue by tlakomy** [cypress-io/cypress#22788]
### Current behavior

If a file imported from node_modules uses [optional chaining operator (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in its code it causes cypress to crash with a Webpack error.

Example:

```
Module parse failed: Unexpected token (15:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const foo = {};
| 
>   console.log(foo?.bar?.baz);
|   return !isOdd(i);
| };
```

Optional chaining **does** work when used either in the test body directly or in a file imported outside of `node_modules` (e.g. `src` directory).

Example test:
```
it('works', () => {
    const foo = {};
    cy.visit('https://example.cypress.io')

    expect(foo?.bar?.baz).to.be.undefined
  })
```

Result:

![Screenshot 2022-07-14 at 12 51 40](https://user-images.githubusercontent.com/16646517/178966345-9bb664f2-ff8d-4f61-ab1e-4ef2d5810aaa.png)

This issue occurs both with JS and TS code (the reproduction example shown below uses JS to keep things minimal and help pinpoint the problem).

### Desired behavior

Optional chaining should be available in test code, files imported from the codebase and imported from `node_modules`.

### Test code to reproduce

1. Clone this repo: https://github.com/tlakomy/cypress-test-tiny
2. Open `node_modules/is-even/index.js` and modify it:
```js
/*!
 * is-even <https://github.com/jonschlinkert/is-even>
 *
 * Copyright (c) 2015, 2017, Jon Schlinkert.
 * Released under the MIT License.
 */

'use strict';

var isOdd = require('is-odd');

module.exports = function isEven(i) {
  const foo = {};

  console.log(foo?.bar?.baz); // this causes the issue
  return !isOdd(i);
};

```
3. `npm run cypress:run`
4. Result:
```bash
Error: Webpack Compilation Error
./node_modules/is-even/index.js 15:18
Module parse failed: Unexpected token (15:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const foo = {};
| 
>   console.log(foo?.bar?.baz);
|   return !isOdd(i);
| };
```

### Cypress Version

cypress@10.3.0

### Other

I went through other issues related to optional chaining, and this workaround: https://github.com/cypress-io/cypress/issues/16914#issuecomment-1179996139 is unfortunately not working (note that my example repo uses JS, not TS).

In addition to that I've tried modifying the default webpack configuration with https://github.com/cypress-io/cypress/tree/e6b2466f7b219a86da46c1ac720432ef75193ca4/npm/webpack-batteries-included-preprocessor with no success.

My understanding is that given cypress 10.3.0 expects node>16: https://github.com/cypress-io/cypress/blob/develop/package.json#L220 optional chaining should work out-of-the-box, without any webpack changes necessary.

Happy to help investigate/debug further!

**Comment by BlueWinds** [comment]
Before spec files are run, Cypress compiles them via webpack (or vite, if you configure that for component testing) - and by default, we don't run files in `node_modules` through babel. This is usually a sensible default, and results in much faster compile times (there's a reason Babel [has this as a default](https://babeljs.io/docs/en/babel-register#ignores-node_modules-by-default) as well).

If you want to compile spec files differently, the way to do this is via the [Preprocessor API](https://docs.cypress.io/api/plugins/preprocessors-api#Examples) - but you'll still take a performance hit of compiling it every time you start cypress (though of course the babel cache would mitigate this somewhat).

**Comment by tbiethman** [comment]
@tlakomy, we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.

**Comment by Srutherford2407** [comment]
Hello, 

I am experiencing the same issue with optional chaining that is contained inside of a node module. Also, I was able to reproduce this issue with the steps provided by @tlakomy using the repo provided as well.

@tbiethman @BlueWinds can you confirm that you did an `npm install` and then made the edit to the node_module file listed in the bug report? 

Attached is the full error from the repo above when reproducing this error. I have also tried the work around stated above but they do not appear to work when the optional chaining is contained inside of the node_module.  Any help would be greatly appreciated. 

![Full error](https://user-images.githubusercontent.com/35584848/231217361-4f61e9a6-7226-4aee-a6ba-b27a268d959e.png)

**Comment by mjhenkes** [comment]
Cypress tests must be transpiled to be able to run within the browser. Typically we transpile tests using webpack.

It is by design that we do not transpile node modules by default, it can be very costly to performance. If you wish to transpile node modules (or even just this file) you will have to supply custom webpack config to the webpack [Preprocessor API](https://docs.cypress.io/api/plugins/preprocessors-api#Examples).
