### ISSUE TITLE
Vite 3 not working with Cypress Component Testing

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#22784]
### Current behavior

Vite 3 does not work.

### Desired behavior

It should work.

### Test code to reproduce

I created a PR with a failing test: https://github.com/cypress-io/cypress/pull/22748

It has some info, but there's probably more to it than the one fix suggested by the Vite team: https://github.com/vitejs/vite/issues/9059. Let's track progress here.

### Cypress Version

10.3.0

**Comment by mHooshdar** [comment]
I tested it and the cypress was stuck on mounting in the component testing menu.

Do these changes fix the issue?

**Comment by wopian** [comment]
> I tested it and the cypress was stuck on mounting in the component testing menu.
> 
> Do these changes fix the issue?

Adding the following to `vite.config.*` from the Vite 3 migration guide has made Cypress run without issues for me:

```ts
server: {
  port: 3000,
  host: '127.0.0.1'
}
```

**Comment by lmiller1990** [comment]
Nice, we will make this change internally soon, so you don't need to 🎉

**Comment by reintroducing** [comment]
There is an additional issue I found after getting tests up and running with Vite 3. I am using msw to mock all endpoints (in development and during testing) and i'm achieving that by basically pre-loading all the mock files I have defined as such:
```js
const req = import.meta.globEager('./**/index.js');
const modules = [];

Object.keys(req).forEach(key => {
    modules.push(...req[key].default);
});

export default modules;
```
As of Vite 3, `globEager` [is deprecated](https://vitejs.dev/guide/migration.html#import-meta-glob). I upgraded my code to the following:
```js
const req = import.meta.glob('./**/index.js', {eager: true});
const modules = [];

Object.keys(req).forEach(key => {
    modules.push(...req[key].default);
});

export default modules;
```
This works great in development mode, but it fails when the mocks get loaded in Cypress. I'm not sure where the issue is, but I suspect that, because it's still using Vite < 3 under the hood somewhere, its trying to load using `import.meta.glob` instead of reading the `{eager: true}` option and thus its not resolving the modules correctly.

Is this an issue with Cypress or perhaps `@cypress/vite-dev-server` (since I see that is still using v2.9.x of Vite)?

**Comment by lmiller1990** [comment]
I tried updating to Vite 3.0.2 in my project, worked fine, no need for any workaround.

I'm not sure why Cypress internal tests are failing, likely due to some additional layer of complexity. 

Anyone else try 3.0.2 and find it works just fine?

**Comment by wopian** [comment]
Yes, `3.0.2` runs with the host workaround removed. I'm not sure what change would have fixed this from the changes listed in `3.0.1` or `3.0.2` though 🤔

**Comment by wopian** [comment]
`cypress run --component` works as expected, but I did discover an issue when I went to interactively run a component test today.

Cypress fails to load and run the individual specs with `cypress open --component`, it endlessly hung on loading the selected spec. Re-add the `host: '127.0.0.1'` option back to the Vite config allowed `cypress open` to run correctly again - so the changes in `3.0.2` only seems to have fixed the issues in headless mode 🤔

**Comment by lmiller1990** [comment]
@wopian are you using React and the `@vitejs/plugin-react? There's a bug with how we integrate plugins, I will post a patch PR today.

I'm able to do open mode with my Vue 3 + Vite 3 + Cypress 10 project, but I don't doubt there's some things we need to fix.

**Comment by wopian** [comment]
Vue 3. I'm travelling until Monday, but I'll see if I can put together a reproduction then 👍

**Comment by lmiller1990** [comment]
Should be solved by https://github.com/cypress-io/cypress/pull/22915/files#diff-5b3ea0fa70e7e1e8a968123451e3b68ad11cde664c56ef07e4ccdd02769887e5R56-R94

All our internal stuff works

**Comment by adamdehaven** [comment]
@lmiller1990 any news on when this will be merged? It's a blocker for our CI since we don't want to change all of our default `server.host` settings.

I reviewed your PR and I don't see anything that looks troublesome.

**Comment by lmiller1990** [comment]
@adamdehaven I have two debug two failing tests (pipeline: https://app.circleci.com/pipelines/github/cypress-io/cypress?branch=lmiller%2Fvite-bump-v2).

Once those are passing, I'll just need a few reviews. The goal is to merge this by the end of this week, so it will be released in the next Cypress version. Those are usually bi-weekly releases, so it would be within two weeks.

**Comment by lmiller1990** [comment]
Ok it's green :fist_oncoming:

**Comment by adamdehaven** [comment]
FWIW I solved temporarily for us by updating the config in `cypress.config.ts`

```ts
export default defineConfig({
  component: {
    devServer: {
      framework: 'vue',
      bundler: 'vite',
      viteConfig: {
        server: {
          host: '127.0.0.1'
        }
      }
    },
  }
})
```

**Comment by lmiller1990** [comment]
I wonder if we can do something so users don't need too add `server.host`. I didn't need it for my projects, I'm not entirely clear on why you do, but glad it's working for you. 

React users (and others, using plugins that inject things into `<head>` in a `<script>` tag won't be able to use that work around, though - they'll need to wait for the PR to merge, since Vite had some breaking changes around `transformIndexHtml` we needed to respond to in our code base.

**Comment by wopian** [comment]
@lmiller1990 I'm not able to reproduce `cypress run` working while `cypress open` fails to load component tests on Vite 3.0.2 - they both endlessly hang. So no idea what was happening last week when it started working briefly 🤔 

Here is a minimal setup where tests can only be run when you add `host: '127.0.0.1'` in `vite.config.ts` or `cypress.config.ts`:
- https://github.com/wopian/vite-vue-cypress

It is the generic Vue Typescript template created by `yarn create vite` with Cypress installed using the `cypress/support/*` files of our web apps (just some Vue shims for fewer imports in component tests)

**Comment by lmiller1990** [comment]
None of my projects need to set `host` explicitly, weird. I'll need to look into this more. Thanks for the reproduction!

The PR I made does not address the `host` issue specifically, but just upgrades our repo to Vite 3, and fixes the issue with plugins like `react` to work correctly. That said, since there's a known work around (adding `host`) I'm still happy to merge the Vite PR as is, and revisit/debug the `host` specific issue separately.

**Comment by lmiller1990** [comment]
It's merged and will be in the next Cypress release.

**Comment by ZachJW34** [comment]
Looks like the `host: '127.0.0.1'` is needed for projects using a Node version >= 17. I have a PR that defaults host to `127.0.0.1` which should allow all vite projects regardless of node version to work. https://github.com/cypress-io/cypress/pull/23048
