### ISSUE TITLE
Dashboard Integration banner state for "no projectId"/"connect your project" state

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22798]
This is an info banner as per the [designs in Figma](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/V0lCq4uBplf9J3GZRiD02m/Cypress-App?node-id=12097%3A68131).

The connect project CTA should send the user to the "connect project modal".
If the banner is dismissed, it should never be shown again.

The conditions for this banner to be visible are:
- The user is not logged in
- The user has at least 1 organization
- The current project is not connected (i.e. no projectId)
- The user has been using Cypress for at least 4 days (at least 96 hours since first open)
  - The automatic docs prompts should not pop up within 24 hours of the banners, the same way the docs do not pop up within 24 hours of each other (the banners get priority, so the docs prompts only pop up if no banners have been shown for 24 hours) - we will likely have to make this change in `shouldShowPrompt` in `HeaderBarContent.vue`
- There are no error, warning, or higher priority info banners present
- The banner has never been dismissed by the user

The copy for this banner should be the "A" variant described in [this doc](https://docs.google.com/document/d/1PFN79d3deDyqDVFmVIBe4cVMzWiEll0J6XCpesBZrSg/edit).

Please reference [this sheet](https://docs.google.com/spreadsheets/d/1_ejTVOv8zA9XAH69Eqa7bBrKqoQY__WeQ3Gqsk7fU0w/edit) for info about all relevant states.

**Comment by abelb** [comment]
https://app.clickup.com/t/364ru66

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22798?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by abelb** [comment]
[Figma Link](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18091%3A152804)

![image](https://user-images.githubusercontent.com/108173/182229903-9f5e706a-5593-4476-940b-09e4ec587405.png)

**Comment by marktnoonan** [comment]
This one is hard to estimate by itself, it really forms part of a larger system of managing what we show when:

> There are no error, warning, or higher priority info banners present

Is there an epic for the general work around creating this prioritized queue of errors/warnings/info message (I might just not have seen this yet). So it's not totally clear what work needs to be included under this ticket, or whether it would extend work done in other tickets.

**Comment by pstakoun** [comment]
@mike-plummer @warrensplayer do you guys want to create a separate "banner controller" issue of some sort? Will defer to you guys as to how to handle that. cc @marktnoonan

**Comment by mike-plummer** [comment]
Completed in #23256
