### ISSUE TITLE
{{force=True}} - restarts my test for click on item covered by another element 

### ISSUE THREAD

**Issue by shahbazqa** [cypress-io/cypress#22803]
### Current behavior

Hi , 

I am trying to click on Recent Reports Tab  
![image](https://user-images.githubusercontent.com/64419960/179057257-815ba037-1a03-4012-bcea-a053e7c955bb.png)
it is being covered by another item: 
![image](https://user-images.githubusercontent.com/64419960/179057389-7779aa66-bf63-414e-80e7-44e369e96926.png)

I have tried 
this.elements.RecentReportsTab().click({force:true})
it does click Recent Report but it restarts my test every single time from the start and i can't go further. 
I am utilizing cucumber with Cypress. 

### Desired behavior

Please if you could help me with another resolution instead of {{force:true}} 
I tried changing the screen size but that didn't help 

### Test code to reproduce

 RecentReportsTab: () => cy.xpath("(//a[@href='/Dashboard/Reports.aspx'])[2]"),   

 clickRecentReportsTab(){
        // cy.disableSmoothScroll
        // cy.location('pathname', {timeout: 4000})
        // .should('include', '/Dashboard/Default.aspx');
        this.elements.RecentReportsTab().click({force:true})

on the spec.js file: 
     OrderAReportPage.VerifyTextCreditReportStatusMessage('Finished')
                                // PartnersPortalPageTopNav.ClickTopRightDropdown()
                                // PartnersPortalPageTopNav.ClickLogoutButton()

                                cy.viewport(1000, 800)
                                PartnersPortalPageTopNav.clickRecentReportsTab()
                                recentreports.getAttributeofReportID()****

### Cypress Version

10.3.0

**Comment by BlueWinds** [comment]
Since it looks like the element is only partly covered, you could try setting the position - https://docs.cypress.io/api/commands/click#Arguments - to click in the bottom right of your element.

With that said, I'm not sure why clicking with force: true would cause a page refresh at all. Figuring out that might be another way to approach it. That's probably a sign there's something weird going on here.

**Comment by tbiethman** [comment]
@shahbazqa, we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
