### ISSUE TITLE
Error when using --e2e with Angular CLI on command line

### ISSUE THREAD

**Issue by merelrietbergen** [cypress-io/cypress#22829]
### Current behavior

With an `angular.json` using `@cypress/schematic:cypress` as `builder` for `e2e` tests, running `ng e2e` makes Cypress ask what type of tests should be run (e2e or component), and subsequently which browser to use. Per https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0, this can be fixed by passing `--e2e` and `--browser`. **Adding the `--e2e` results in an error**: "Error: Unknown argument: e2e"; adding `--browser` does work.

### Desired behavior

**When the `--e2e` flag is added to the `ng e2e` command, this should be used by Cypress to select e2e testing as the testing type automatically.**

This does already work when adding `"e2e": true` to the options in the `angular.json`, but with many (16 and counting) projects configured in the `angular.json`, this results in a lot of duplicate configuration. Adding `--e2e` to a script that runs `ng e2e` avoids the duplicate configuration and the need to add the configuration for every project we add.

### Test code to reproduce

Run `ng e2e --e2e` without adding `"e2e": true` to the options for "e2e" in the `angular.json`.

### Cypress Version

10.3.0

### Other

`@cypress/schematic` version: 2.0.0

**Comment by emilyrohrbough** [comment]
This was releases as `@cypress/schematic v2.0.2` on August 9th.
