### ISSUE TITLE
cypress Error : Step Implementation missing while implementing BDD: Scenario Outline feature

### ISSUE THREAD

**Issue by Sjain01** [cypress-io/cypress#2282]
Hello All ,

I have just started using cypress and was playing around with BDD : Scenario Outline feature.

hereby is my feature file :- 
`Scenario Outline: User success sign in
    Given Should be able to run on '<devicename>'`
`Examples:
    | devicename|
    | iphone-6  |`

And step definition is as follows:
`Given(/^Should be able to run on {string}/, devicename  => {
  viewportSize = devicename ;
});`

Where viewportSize is just a variable to be set as device name used within  Examples.

Even though the step definition is implemented , I am getting an error stating:
`cypress_runner.js:138498 Error: Step implementation missing for: Should be able to run on 'iphone-6'`

### Versions
Cypress version :- 3.0.1
Chrome browser version : 67

Note :- Other BDD scenarios including Scenario only are working fine. The problem is only with Scenario Outline.

**Comment by jennifer-shehane** [comment]
Hi @Sjain01, are you using the [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) for your Scenarios? I think this may be a more relevant issue for their project if that is the case.

**Comment by Sjain01** [comment]
@jennifer-shehane - Yes I am using cypress-cucumber-preprocessor.
