### ISSUE TITLE
Add Angular CT schematic and builder

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#22834]
Our Angular CT support will be targeted at users utilizing the Angular CLI. When it comes to scaffolding and executing tasks in an Angular CLI workspace, most of this work is handled via [schematics](https://angular.io/guide/schematics) and [builders](https://angular.io/guide/cli-builder). A schematic is a code generation script whereas a builder is a code execution script. 

These concepts are heavily used in the Angular CLI ecosystem, so having these tools to scaffold and serve Angular CT projects would be ideal. We already provide support for e2e so having the same level of support for CT makes sense

Requirements:

- Create a schematic that scaffolds support for Angular CT (similar to how it is done when setting up CT projects with the Launchpad/Wizard)
- Create a builder that invokes the Cypress Module API for CT (similar to the how the current e2e builder functions)
- Add tests verifying the code-generation and execution works in an Angular CLI workspace

What we need to scaffold is TBD, once #22813 and #22812 are finished we will have a clear picture of what files are necessary.

**Comment by d-koppenhagen** [comment]
Isn't it already available?

**Comment by admah** [comment]
@d-koppenhagen yes, it is. You can find it in the latest release - v2.1.1. 

I’ll go ahead and close this issue. Thanks!
