### ISSUE TITLE
Proposal: Add more plugin events to mirror driver events

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2283]
Add the following plugin events that mirror [the driver events](https://docs.cypress.io/api/events/catalog-of-events.html#Cypress-Events) that occur in the browser.

* test:before:run
* test:after:run

Related: #2177

**Comment by badeball** [comment]
Were these events removed at some point? Listening to `test:after:run` from a plugin is not allowed per v12.14.0.

**Comment by mike-plummer** [comment]
Hi @badeball - this was never actually released. This went into a feature branch that never ended up merging down

**Comment by badeball** [comment]
That’s a bummer. Any chance that this could be reconsidered?

**Comment by mike-plummer** [comment]
@badeball Since is from waaay back so I doubt it could be cleanly picked back up as-is. If there are specific events you're wanting exposed you're welcome to submit a feature request so we can review - would be helpful to know the use case, what event(s) are needed, etc
