### ISSUE TITLE
Grafana external API

### ISSUE THREAD

**Issue by conversayShawn** [cypress-io/cypress#22837]
### What would you like?

Customer feature:

> _Show data about when was the last run, graph of successes/failures history, errors counters (distinct counter for each error), average test time and things like that in Grafana Dashboard._

### Why is this needed?

Customer feedback:

> _I want to create a panel in my Grafana dashboard with data about my E2E results. Pretty much the same data as I see in your analytics (some of it), but on my main dashboard in Grafana, because I want to reduce the number of dashboards I need to monitor._

**Comment by ndua-globality** [comment]
Hi there! 

Any progress on this guy? Am also looking for this :)
