### ISSUE TITLE
Proposal: rename pluginsFile to backgroundFile

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2285]
The term `pluginsFile` is somewhat of a misnomer, since it is exclusive to the background node process, but a plugin could be created that solely affects the driver and events in the browser. 

We should rename the `pluginsFile` to the `backgroundFile` to make it clear it runs in the background process. We should also update the documentation to make it clear plugins can be implemented for the browser in the `supportFile`, for the background in the `backgroundFile`, or both. 

Code-wise, we should deprecate the `pluginFile` config option and log a warning that the user should rename it to `backgroundFile`. Then in a future version, remove `pluginsFile` entirely.

**Comment by chrisbreiding** [comment]
Need to update references to and use of plugins in the following repos:

* https://github.com/cypress-io/cypress-webpack-preprocessor
* https://github.com/cypress-io/cypress-watch-preprocessor
* https://github.com/cypress-io/cypress-browserify-preprocessor
* All cypress-example-* repos: https://github.com/cypress-io?utf8=%E2%9C%93&q=example&type=&language=

**Comment by chrisbreiding** [comment]
The code for this is complete, but not yet released. It will be released in [4.0](https://github.com/cypress-io/cypress/pull/2880).

**Comment by jennifer-shehane** [comment]
The work for this was never released.

**Comment by jennifer-shehane** [comment]
Closing due to recent changes we've decided to make for the configuration file.
