### ISSUE TITLE
[v10] CLI --spec does not use the configuration file specPattern to find specific files to run

### ISSUE THREAD

**Issue by arithon55** [cypress-io/cypress#22860]
### Current behavior

npx cypress run -b edge -s "cypress/e2e/ccptests.feature" does not use the configuration file specPattern: "**/*.feature" to find valid files to be run. The files are found if no --spec is used.  This used to work before the Cypress 10 name change for spec files. Not specifying the --spec option will run all feature files. The feature file uses the @badeball/cypress-cucumber-preprocessor which produces the actual spec files that are used by Cypress.

Error message is

> Can't run because no spec files were found.
> We searched for specs matching this glob pattern:
>  C:\dev\bi---cypress-tests\cypress\e2e\ccptests.feature

### Desired behavior

Cypress 10 should use the specPattern from the configuration to accept the .feature file instead of looking for a hard coded spec file naming convention which will never find any feature files.

### Test code to reproduce

package.json contains
```
"devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^11.5.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.3",
    "@deepakvishwakarma/cucumber-json-formatter": "0.0.1",
    "cypress": "^10.3.0",
    "cypress-file-upload": "^5.0.8",
    "cypress-localstorage-commands": "^2.1.0",
    "esbuild": "^0.14.49",
    "multiple-cucumber-html-reporter": "^1.21.4",
    "ts-loader": "^9.3.1",
    "typescript": "^4.7.3"
  }
```  

cypress.config.ts contains

```js
import { defineConfig } from "cypress";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";
import * as createBundler from "@bahmutov/cypress-esbuild-preprocessor";

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );
  return config;
}

export default defineConfig({
  e2e: {
    chromeWebSecurity: false,
    defaultCommandTimeout: 10000,
    specPattern: "**/*.feature",
    supportFile: false,
    video: false,
    setupNodeEvents,
  },
});
```

in e2e folder
ccptest.feature contains

```
Feature: Cypress Cucumber Preprocessor (BDD) test
  Scenario: Visit the cypress example page to check basic functionality
    When I visit cypress.com example page
    Then I am on Kitchen Sink page

ccptest.ts contains
import { When, Then } from "@badeball/cypress-cucumber-preprocessor";

When("I visit cypress.com example page", () => {
  cy.visit("https://example.cypress.io");
});

Then("I am on Kitchen Sink page", () => {
  cy.title().should('contain', 'Cypress.io: Kitchen Sink');
});
```

### Cypress Version

10.3.0

**Comment by tbiethman** [comment]
@arithon55 thank you for the report. I'm not sure I'm following your stated desired behavior: 

```
Cypress 10 should use the specPattern from the configuration to accept the .feature file instead of looking for a hard coded spec file naming convention which will never find any feature files.
```

We do use the specPattern from the config in both cases, as we won't allow you to provide a --spec option that does not match the specPattern in config. Or are you expecting an unknown/unfound --spec option to fall back to running all specs?

I'm also wondering if there's not another problem here? We have a few issues logged regarding `--spec` options and special characters in Windows, which seems to be your environment:

```
Can't run because no spec files were found.
We searched for specs matching this glob pattern:
C:\dev\bi---cypress-tests\cypress\e2e\ccptests.feature
```

Is that `---` section in the path a redaction? Does the actual path contain parentheses? If so, your issue might just be an occurrence  of this issue: https://github.com/cypress-io/cypress/issues/22272

**Comment by arithon55** [comment]
@[tbiethman](https://github.com/tbiethman) Thanks for your help. I have found the issue. It was nothing to do with Cypress (it was due to a typo).
