### ISSUE TITLE
--spec <file path> does not find spec file if path contains parenthesis.

### ISSUE THREAD

**Issue by sksajjan** [cypress-io/cypress#22865]
### Current behavior

when parent folder of "cypress" folder contains parenthesis like C:\Users\Santosh\Documents\TestAutomation(Cypress)\cypress\e2e" then, user would always see "no spec files found" when using --spec argument with cypress run.

### Desired behavior

As the OS where the cypress is being run is known, --spec code should handle the file path for special characters allowed within Windows OS.

### Test code to reproduce

Have cypress parent folder with ( ) and then try to run cypress run --spec "cypress/e2e/*.cy.js" this will end in error and report no spec files found.

### Cypress Version

10.3.1

**Comment by tbiethman** [comment]
@sksajjan thank you for the report. We are tracking this issue with parentheses here: https://github.com/cypress-io/cypress/issues/22272. I'm going to close this issue as a duplicate.
