### ISSUE TITLE
Proposal: add new plugin events 'before:spec', 'after:spec', 'before:run', 'after:run'

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2286]
~These would only be fired in `run` mode.~

~The `before:spec` event should include some type of behavior where if the users returns false and throws a cancellation error, it won't run that spec and move on to the next one.~

**Comment by amitzur** [comment]
why would this fire only in `run` mode?

**Comment by chrisbreiding** [comment]
That's a good question. We discussed this a bit and decided they _would_ fire in `interactive` mode as well, with some caveats. 

* `run:start` will fire when opening a project
* `spec:start` will fire when the browser opens
* `spec:end` will fire when the browser closes (and may not fire at all (if, for example, you force quit Cypress)
* `run:end` will fire when you close the project (and may not fire at all (if, for example, you force quit Cypress)

The `*:end` events will only receive results in `run` mode, since there's no way to aggregrate results from `interactive` mode.

**Comment by stephanmullerNL** [comment]
I'd love to be able to hook into the start and end of my run with a plugin.  +1

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/issues/6665
