### ISSUE TITLE
Cypress accessibility Automation 

### ISSUE THREAD

**Issue by prudhvinani** [cypress-io/cypress#22879]
### Current behavior

Hi All,

We are currently doing accessibility testing in cypress and while doing it we observed a different behavior from cypress in local while running cypress for accessibility is getting passed but in the CI/CD pipeline accessibility is facing for few scenarios  intermediately (not happening every time) 

I had listed down the error below .Can some lets us know why we are seeing this behaviour
 
![image](https://user-images.githubusercontent.com/31948706/180160285-d0ed5b02-5627-4699-90d0-10745b794e42.png)

### Desired behavior

No error

### Test code to reproduce

getting error

### Cypress Version

7.6.0

**Comment by nagash77** [comment]
@prudhvinani, we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
