### ISSUE TITLE
When using Yarn and PNP (plug-in-play), Cypress does not detect the framework/language correctly on set up for CT

### ISSUE THREAD

**Issue by elylucas** [cypress-io/cypress#22871]
### Current behavior

When creating a CRA app using yarn 3.2.1, yarn uses [PNP](https://yarnpkg.com/features/pnp) by default. When Cypress launches and you go into setup, Cypress does not detect the framework or language properly.  Presumably this is due to the fact that PNP does not use a local node_modules folder, which Cypress relies on.

### Desired behavior

Cypress should configure the app normally when using yarn and pnp.

### Test code to reproduce

When using [yarn 3.2.1](https://yarnpkg.com/getting-started/install), create a new CRA project:

`yarn create react-app cra-ts-test-yarnt --template typescript`

Install cypress:

`yarn add cypress`

Launch cypress and configure CT. Notice it doesn't pick up on the framework and has you select it.

### Cypress Version

10.3.1

**Comment by lmiller1990** [comment]
Dup/related https://github.com/cypress-io/cypress/issues/22747

**Comment by lmiller1990** [comment]
Close in favor: https://github.com/cypress-io/cypress/issues/22871
