### ISSUE TITLE
clicking on element causes Illegal Invocation error

### ISSUE THREAD

**Issue by danreale** [cypress-io/cypress#2288]
Some of the elements I am trying to click on now give me an illegal invocation error. In 3.0.2 this was not happening.
Happening on both chrome68 and electron 59 browsers.

3.0.3 - Mac - Chrome 68 /electron 59

![image](https://user-images.githubusercontent.com/37839370/43736092-7a0bad0a-998a-11e8-884a-4e8e4ec1dd97.png)

**Comment by brian-mann** [comment]
This is already fixed and merged into `develop` and will go out in the next release.

https://github.com/cypress-io/cypress/pull/2246
