### ISSUE TITLE
*Actual* timestamp for Dashboard

### ISSUE THREAD

**Issue by conversayShawn** [cypress-io/cypress#22885]
### What would you like?

Feedback from Customer:

> Can we please have the *actual* timestamp for when certain runs occurred? Maybe show the actual timestamp when you hover the text?

![Screen Shot 2022-07-21 at 7 57 32 AM](https://user-images.githubusercontent.com/48733734/180246131-83e52049-4c8d-4779-87cf-5dbfbcd7fc98.png)

### Why is this needed?

Feedback from Customer:

> Can we please have the *actual* timestamp for when certain runs occurred? "Ran 2 days ago" is not the most helpful thing in the world when you're trying to diagnose an issue. Maybe show the actual timestamp when you hover the text?

**Comment by jebbench** [comment]
Not having the timestamp of when a test ran makes finding the logs from a failure more difficult than it needs to be.

**Comment by zaq42** [comment]
I came here to raise this issue, but instead I'll add my +1 here.

Hovering over the runtime provides the duration to the nearest milli-second, but the dashboard remains very secretive about when it ran:
![image](https://user-images.githubusercontent.com/24503523/198948613-c80b45fa-2192-4f39-91a3-97090c981a08.png)

Even in the list of latest runs, millisecond accuracy is available on duration:
![image](https://user-images.githubusercontent.com/24503523/198949230-59008224-b206-4b06-b3c2-e543b810c27c.png)

**Comment by zaq42** [comment]
> Not having the timestamp of when a test ran makes finding the logs from a failure more difficult than it needs to be.

@jebbench: My workaround for this is to use the [cypress-timestamps](https://glebbahmutov.com/blog/cypress-timestamps/) plugin.  Timestamps are visible in screenshots on failure, making it trivial to match up with the logs.

**Comment by zaq42** [comment]
Hooray!
Not sure when this was fixed, I only just noticed it.  Current version is 12.9.0.

Images show the start time of a run, as requested above.

![image](https://user-images.githubusercontent.com/24503523/229995508-308049b9-121e-4d5d-be5c-87fd9192b3b4.png)

![image](https://user-images.githubusercontent.com/24503523/229995788-74d9e868-cab3-4ae0-a2ac-8c78fbab8311.png)

**Comment by bbartizek** [comment]
> Hooray! Not sure when this was fixed, I only just noticed it. Current version is 12.9.0.

Nice!  It's a change on Dashboard.  We have some pipelines running pretty old versions of Cypress and they're showing timestamps now too.
