### ISSUE TITLE
Timeout progress bar not representative of actual timeout value set

### ISSUE THREAD

**Issue by StanKatsyuk-at** [cypress-io/cypress#22896]
### Current behavior

If I override the timeout for a locator, the progress bar is not representative of the timeout value I selected and instead elapses within a few seconds and remains blank for the remainder of the timeout period. 

### Desired behavior

Timeout progress bar should represent the actual timeout I set

### Test code to reproduce

```
describe('timeout progress bar test', () => {
    it.only('verify timeout progress bar behavior', () => {
        cy.visit('www.google.com');
        cy.findByText('fooBar', {timeout: 40000}); // Observe progress bar behavior during this step
    });
});
```

### Cypress Version

10.3.0

### Other

Video recording: 
https://user-images.githubusercontent.com/102546369/180485822-99c70a74-8fb3-4af4-a606-0ed35468d31e.mov

**Comment by tbiethman** [comment]
@StanKatsyuk-at thank you for the report. Are you seeing this only commands provided by [cypress-testing-library](https://github.com/testing-library/cypress-testing-library)?

I believe the issue with those commands is that the log is not being provided with the `timeout` value: https://github.com/testing-library/cypress-testing-library/blob/main/src/index.js#L51-L54. So while functionally it waits, the log is assuming the default value is being used.

I recommend logging an issue to that repository. Or a PR, it should be a 1-liner and some tests 🚀

**Comment by StanKatsyuk-at** [comment]
@tbiethman sorry for the delayed response. It does not appear as it happens when I run `cy.contains('fooBar', {timeout: 40000});`, thus it does seem like this is a testing library bug. I will look into opening a PR/issue with them. 

Thank you!
