### ISSUE TITLE
required cypress.json file while running latest cypress command.

### ISSUE THREAD

**Issue by dldeshpande** [cypress-io/cypress#22899]
### Current behavior

when i try to run the cypress using command it requires the cypress.json file where as in latest cypress version 10.3.1 it is no longer support by cypress then how we can execute the cypress to run it using package.json file.

 "apolo-e2e-dev": "ng run frontend-apolo-e2e:e2e --config-file=apps/frontend/apolo-e2e/cypress.config.js --watch --devServerTarget= ",

instead of using older jsong file cypress.json, it works well.

 "apolo-e2e-dev": "ng run frontend-apolo-e2e:e2e --config-file=apps/frontend/apolo-e2e/cypress.json --watch --devServerTarget= ",

### Debug logs

> ng run frontend-apolo-e2e:e2e --config-file=apps/frontend/apolo-e2e/cypress.config.js --watch --devServerTarget= 

> ng run frontend-apolo-e2e:e2e --config-file=apps/frontend/apolo-e2e/cypress.config.js --configFile=apps/frontend/apolo-e2e/cypress.config.js --watch --devServerTarget= 
An unhandled exception occurred: ENOENT: no such file or directory, open '/home/dhananjay/Documents/update-olimpo/olimpo/apps/frontend/apolo-e2e/cypress.json'
See "/tmp/ng-LHlG0P/angular-errors.log" for further details.

>  NX   CLOUD  See run details at https://nx.app/runs/Ap8TyZ7ozgL

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! olimpo@0.0.0 apolo-e2e-dev: `ng run frontend-apolo-e2e:e2e --config-file=apps/frontend/apolo-e2e/cypress.config.js --watch --devServerTarget= `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the olimpo@0.0.0 apolo-e2e-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dhananjay/.npm/_logs/2022-07-22T18_45_16_798Z-debug.log

### Cypress Version

10.3.1

### Package Manager

npm

### Operating system

Linux

**Comment by tbiethman** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

One thing I would try off the bat is checking your [@cypress/schematic](https://www.npmjs.com/package/@cypress/schematic) version, if you're using it. You'll want to upgrade to V2 for Cypress 10.0 support.

**Comment by mirobo** [comment]
When using Cypress 10 the file "cypress.json" needs to be removed. Also maybe try to just set "cypressConfig" within your angular.json file; see also https://github.com/nrwl/nx/issues/10591#issuecomment-1165496623

I got it working as well with something like this:

          "options": {
            "cypressConfig": "apps/whatever/cypress.config.js",
            "tsConfig": "apps/whatever/tsconfig.e2e.json",
            "testingType": "e2e",
            "browser": "electron",
            "devServerTarget": "whatever"
          },

**Comment by dldeshpande** [comment]
> When using Cypress 10 the file "cypress.json" needs to be removed. Also maybe try to just set "cypressConfig" within your angular.json file; see also [nrwl/nx#10591 (comment)](https://github.com/nrwl/nx/issues/10591#issuecomment-1165496623)
> 
> I got it working as well with something like this:
> 
> ```
>       "options": {
>         "cypressConfig": "apps/whatever/cypress.config.js",
>         "tsConfig": "apps/whatever/tsconfig.e2e.json",
>         "testingType": "e2e",
>         "browser": "electron",
>         "devServerTarget": "whatever"
>       },
> ```

yes bro its working for me also i have created npm command using that command also it worked for me. Thanks.
