### ISSUE TITLE
Proposal: Allow Users To Set Custom Title for Integration Test for GUI

### ISSUE THREAD

**Issue by tjhillard** [cypress-io/cypress#2290]
### Current behavior:

In the Cypress GUI, the listed integration tests for a given workspace are labeled by their file name and there is no option to customize these labels/titles.

![screen shot 2018-08-06 at 3 22 08 pm](https://user-images.githubusercontent.com/6406400/43743982-da7189f6-998c-11e8-856b-4403b0b1ea4f.png)

### Desired behavior:

Inside of an integration file, allow users to indicate a label/title to be used with the given test when listing the integration files in the GUI.
```
/* cy:title: 'GET /users/:id' */
```
Including (something along the lines of) the above comment in an integration file would set the "title" for this test in the GUI to: 
`"GET /users/:id"`

This creates enhanced usability and customization when running tests via the GUI.

**Comment by jennifer-shehane** [comment]
Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
