### ISSUE TITLE
Duplicated dom elements when running e2e debug

### ISSUE THREAD

**Issue by kghaly** [cypress-io/cypress#22904]
### Current behavior

Sometimes when running tests using cypress debugger, the test runner will show screenshots where the element (for example a button) is duplicated and shown twice in the screenshot. This causes the test to fail and suggests using the parameter {multiple: true}, but in reality, the code is only supposed to have one button. Why is this happening and how can I avoid it?

### Desired behavior

Not duplicate dom elements and show the correct amount of elements displayed from the code

### Test code to reproduce

I am unable to share source code for this project.

### Cypress Version

9.7.0

**Comment by kjetilhammerseth** [comment]
@kghaly were you ever able to figure out what caused this? Having the exact same issue.

**Comment by marcthayer** [comment]
Also hoping someone else finds this and chimes in on a cause and/or resolution. We're getting random elements duplicated at least once a day during e2e testing. Haven't found a way to replicate it on purpose.

**Comment by Srizza93** [comment]
If anyone falls down on the same issue, I'm getting something similar.
While typing into an input within a layer, this last one is duplicated and causes the test to be flaky.
My solution at the moment is to use the option { force: true } on the type command, but it is not ideal.
