### ISSUE TITLE
dir is undefined

### ISSUE THREAD

**Issue by BTBMan** [cypress-io/cypress#22910]
### Current behavior

When use custom directive like `v-xxx` in vue component, It's error and print `dir is undefined`

<img width="508" alt="图片" src="https://user-images.githubusercontent.com/26108004/180682633-49b81960-0a75-46f7-8e7b-b99c65676a1a.png">

### Test code to reproduce

HelloWorld.cy.ts

```ts
import HelloWorld from '../HelloWorld.vue';

describe('HelloWorld', () => {
  it('playground', () => {
    cy.mount(HelloWorld, { props: { msg: 'Hello Cypress' } });
  });

  it('renders properly', () => {
    cy.mount(HelloWorld, { props: { msg: 'Hello Cypress' } });
    cy.get('h1').should('contain', 'Hello Cypress');
  });
});

```

HelloWorld.vue

<img width="487" alt="图片" src="https://user-images.githubusercontent.com/26108004/180682681-581f94ba-da68-45fe-baed-a9055efe4228.png">

### Cypress Version

10.3.0

**Comment by tbiethman** [comment]
@BTBMan thanks for the report. Where are you defining your custom directive? If you're doing so within your app/main component, it is likely not getting defined for your isolated component test.

If that doesn't seem to be the problem, please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by BTBMan** [comment]
@tbiethman [Here's a example](https://github.com/BTBMan/issue-demos)

Steps:

1. `pnpm i`
2. `pnpm run test:unit`

The test file is `./src/components/__test__/HelloWorld.cy.ts`
The test component is `./src/components/HelloWorld.vue`
Custom directive registered in `main.ts`

**Comment by tbiethman** [comment]
You main.ts app isn't being mounted for your component tests, so the directive is not currently defined there. You can define it within your test by modifying the global property of the mount options:

```js
// my-directive.js
const MyDirective = {
  mounted() {
    console.log('my-directive');
  },
}

export default MyDirective
```

```js
// main.ts
import MyDirective from './my-directive'
...
app.directive('my-directive', MyDirective);
```

```js
import MyDirective from './my-directive'

describe('HelloWorld', () => {
  it('playground', () => {
    cy.mount(HelloWorld, { 
      props: { msg: 'Hello Cypress' },
      global: {
        directives: {
          MyDirective
        }
      }
    });
  });
});
```

There's a bunch of ways to DRY this up, this is just an example. You could also look into creating a custom mount function if you have a bunch of directives/plugins that you're setting globally: https://docs.cypress.io/guides/component-testing/custom-mount-vue#Custom-Mount-Commands

**Comment by BTBMan** [comment]
It works, Thanks a lot!
