### ISSUE TITLE
Wrong installation number shows

### ISSUE THREAD

**Issue by gedeal** [cypress-io/cypress#22923]
### Current behavior

I downloaded Cypres 10.3.1 and Installed , the info shows that version 9.7.0 is installed.
_Found binary version 10.3.1 installed in: C:\Users\UIAB\AppData\Local\Cypress\Cache\9.7.0\Cypress_
![snap035](https://user-images.githubusercontent.com/26741991/180816480-a39e4d5a-6a44-477a-8d58-8f52be358d41.jpg)

But the right version is 10.3.1 (and it works)
![snap034](https://user-images.githubusercontent.com/26741991/180815952-834af779-9a1d-430c-a415-fe33ad3399dc.jpg)

### Cypress Version

10.3.1

### Package Manager

npm

### Operating system

Windows

**Comment by tbiethman** [comment]
@gedeal thank you for the report. That is definitely odd, but I'm unable to reproduce what your screenshots are showing me. 

I'm curious if you can reproduce this after running [`cypress cache clear`](https://docs.cypress.io/guides/guides/command-line#cypress-cache-clear) and re-installing both 9.7.0 and 10.3.1?

**Comment by gedeal** [comment]
Hej Tyler

I have clean
[cid:1e7fa55f-887f-467f-ba45-e8689cad4d96]


and install again, but with same issue:
[cid:0ae8b95f-bd66-4cc8-b2d9-d9f7efbd5c86]


/Gerson
________________________________

**Comment by tbiethman** [comment]
@gedeal thanks for confirming, I'll take another look. I imagine I know what your embeds are going to show, but can you update those image links to make sure I'm not missing anything?

**Comment by gedeal** [comment]
Hi
Here are the images
![snap036](https://user-images.githubusercontent.com/26741991/181187572-b98e4cdf-0400-4373-9fac-fb47a82871fe.jpg)


![snap037](https://user-images.githubusercontent.com/26741991/181187743-48b2805a-ac12-4a41-84a0-d1115b33a7cd.jpg)

**Comment by tbiethman** [comment]
@gedeal it looks like you are installing a downloaded version of cypress, not the version downloaded by NPM. Do you have the CYPRESS_INSTALL_BINARY env set in your shell?

**Comment by gedeal** [comment]
HI Tyler

I fixed the problem ( But do not know if this is the right solution )

I noticed that I had a wrong version at package.json
[cid:257eed88-eac1-45b8-9880-3411949f2be3]

I deleted the file and installed again:
$ direnv allow
$ rm -rf node_modules
$ npm init
$ npm install
$ npm install cypress --save-dev


my .envrc file has:
 export CYPRESS_INSTALL_BINARY=C:/Users/uiab/Downloads/Cypress.zip


and now I have

[cid:c54b021e-20ba-4dee-9818-11b31260b38c]


Thanks
I could not see and fix the problem without your help.

/Gerson

________________________________

**Comment by tbiethman** [comment]
Glad I could help! I would definitely unset the CYPRESS_INSTALL_BINARY env if you don't mean to intentionally install to a specific binary version. When that value is unset, the binary that is downloaded by NPM (matching the package version) will be used automatically.

**Comment by gedeal** [comment]
Hi Tyler

I have reported this problem before but have not received any response. (https://stackoverflow.com/questions/70680188/in-cypress-i-can-not-make-the-command-promt-to-work)
***@***.***?v=73d79a89bded]<https://stackoverflow.com/questions/70680188/in-cypress-i-can-not-make-the-command-promt-to-work>
in Cypress i can not make the command 'promt' to work<https://stackoverflow.com/questions/70680188/in-cypress-i-can-not-make-the-command-promt-to-work>
I am doing API testing with Cypress and I want to have a prompt that asks for a value. I use a function to try to get the value. The commands: Alert and Confirm shows a popup windows, but Prompt (or
stackoverflow.com

Can you help?

I am trying to have a popup prompt  in Cypress
Confirm and Alert does work, but Prompt does not, I get a NULL response.

Here is the code:

describe('Example to demonstrate handling of JavaScript Alerts, Confirm, Prompt in Cypress', () => {
  console.clear()


   it('get answer ', () => {
    var answer = window.confirm("Please confirm data?");
    if (answer) {
      console.log('YES')
    }
    else {
      console.log('NO')
    }
  });

  it('get answer ', () => {
    var name = alert("Please confirm");
      console.log(name)
  });

  it('get answer ', () => {
    var name = prompt("What is your name?");
    console.log("Hi " + name)
  });
})


Regards
Gerson


________________________________

**Comment by tbiethman** [comment]
Hey @gedeal, I did a quick search; this tutorial seems like it might be relevant: https://applitools.com/blog/testing-browser-alerts-confirmations-prompts-cypress/.

But if that's not helpful, go ahead and log a new issues (or in this case, new [discussions](https://github.com/cypress-io/cypress/discussions)) for topics unrelated to the original issue.
