### ISSUE TITLE
Migration to Cypress 10.3.1 lead to "cannot find root element to mount the component"

### ISSUE THREAD

**Issue by ElMenax** [cypress-io/cypress#22921]
### Current behavior

I am currently updating Cypress to 10.3.1. I have gone through the migration process but when running my component tests, I end with an error `[@cypress/react] 🔥 Hmm, cannot find root element to mount the component.`

Weird thing is that I used to have an event listener on `dev-server:start` to lunch my webpack server but now Cypress tells me to remove it because it is no longer required. 

I am not sure what I could have missed, any ideas?

### Test code to reproduce

My `cypress.config.js` file looks like this:
```js
const { defineConfig } = require('cypress');

module.exports = defineConfig({
  component: {
    devServer: {
      framework: 'create-react-app',
      bundler: 'webpack',
    },
    specPattern: '**/*.cypress.{jsx,tsx}',
    video: false,
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config);
    },
  },
});
```

My plugins/index.js looks like this:
```js
const findReactScriptsWebpackConfig = require('@cypress/react/plugins/react-scripts/findReactScriptsWebpackConfig');
const { startDevServer } = require('@cypress/webpack-dev-server');
const {
  addMatchImageSnapshotPlugin,
} = require('cypress-image-snapshot/plugin');

const injectDevServer = (on, config) => {
  const webpackConfig = findReactScriptsWebpackConfig(config);

  // disable "watch" functionality on CI, to avoid issue similar to the one
  // described here: https://github.com/cypress-io/cypress/issues/4283
  if (process.env.CI) {
    webpackConfig.devServer = {
      liveReload: false,
      watchFiles: {
        paths: [],
        options: {
          usePolling: false,
        },
      },
    };
  }

  /* on('dev-server:start', (options) =>
    startDevServer({
      options,
      webpackConfig,
    }),
  ); */

  config.env.reactDevtools = true;

  return config;
};

module.exports = (on, config) => {
  injectDevServer(on, config);
  addMatchImageSnapshotPlugin(on, config);
  return config;
};
```

### Cypress Version

10.3.1

**Comment by marktnoonan** [comment]
Hi @ElMenax, in version 10 there was a change to the way the root element is identified in Component Testing, to remove a conflict with some frameworks. We also began to bundle the `cypress/react` package with the Cypress binary. So you should be able to update your imports from `@cypress/react` to plain old `cypress/react`, and that would clear this error, letting you move on to any other adjustments that are needed.

**Comment by ElMenax** [comment]
Changing the import indeed solved the issue. Thank you for your help 😄
