### ISSUE TITLE
Dashboard Integration Smart Organization Creation Notification

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22934]
This is an info banner as per the [designs in Figma](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/V0lCq4uBplf9J3GZRiD02m/Cypress-App?node-id=12097%3A68131).

The create organization CTA should send the user to `/organizations` in the Dashboard, the same way the "Manage organizations" link does. UTM parameters should be included.
If the banner is dismissed, it should never be shown again.

The conditions for this banner to be visible are:
- The user is not logged in
- The user has 0 affiliated organizations (i.e. 0 memberships)
- The user has been using Cypress for at least 4 days (at least 96 hours since first open)
  - The automatic docs prompts should not pop up within 24 hours of the banners, the same way the docs do not pop up within 24 hours of each other (the banners get priority, so the docs prompts only pop up if no banners have been shown for 24 hours) - we will likely have to make this change in `shouldShowPrompt` in `HeaderBarContent.vue`
- There are no error, warning, or higher priority info banners present
- The banner has never been dismissed by the user

The copy for this banner should be the "A" variant described in [this doc](https://docs.google.com/document/d/1PFN79d3deDyqDVFmVIBe4cVMzWiEll0J6XCpesBZrSg/edit).

Please reference [this sheet](https://docs.google.com/spreadsheets/d/1_ejTVOv8zA9XAH69Eqa7bBrKqoQY__WeQ3Gqsk7fU0w/edit) for info about all relevant states.

**Comment by abelb** [comment]
https://app.clickup.com/t/364rtqz

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22934?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by abelb** [comment]
[Figma Link](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18326%3A163203)

![image](https://user-images.githubusercontent.com/108173/182231526-aad42486-9c0a-4866-8b1c-f429c6415891.png)

**Comment by mike-plummer** [comment]
Completed in #23256
