### ISSUE TITLE
Improved Dashboard Integration column hover interactions

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22932]
Improve experience of hovering over and interacting with the Latest runs and Average duration columns.

[Figma Prototype](https://www.figma.com/proto/PAOozuCxtfetqP8fUVvg0y/branch/V0lCq4uBplf9J3GZRiD02m/Cypress-App?page-id=16373%3A174946&node-id=18481%3A162161&viewport=-3529%2C-2113%2C0.5&scaling=min-zoom&starting-point-node-id=18481%3A162161)

**AC:**
- Replace empty run dots with dashes when user is not logged in or does not have a valid project connected
- User hovering over dashes, will see one of the following on hover, depending on the state:
  - Connect (for log in flow)
  - Connect project (for connect project flow, if no valid project)
  - Request access (for request access flow, if no access)
- When offline, no hover behavior, just show the --
- No connection to smart prompts, but the CTAs should map to those in the header tooltips
- Include UTM params for login

Here are the [states in Figma](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18493%3A162104)

[ClickUp](https://app.clickup.com/t/18033298/PM-2476)

**Comment by abelb** [comment]
Background hover triggers tooltip
https://app.clickup.com/t/18033298/DESIGN-1233

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22932?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by abelb** [comment]
Design: WIP

[Figma Link](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18272%3A162529)

**Comment by lmiller1990** [comment]
@abelb what are we supposed to be looking at? I just see

![image](https://user-images.githubusercontent.com/19196536/182265557-cf8adef1-1554-4ef9-bcf4-451990dadbe4.png)

It's not clear on what is required for delivery of this ticket.

**Comment by marktnoonan** [comment]
I'd agree, there is not currently a task here that can be estimated.

**Comment by pstakoun** [comment]
Added a few notes but need to sync with @abelb on the final iteration of this

**Comment by pstakoun** [comment]
We are moving this to a future sprint. Sorry about the incompleteness here.

**Comment by abelb** [comment]
OK Updated design

1. Replace empty run dots with dashes
2. When not logged in, user hovers over dashes and depending on state, will see one of the following on hover:

![image](https://user-images.githubusercontent.com/108173/182699078-08daf450-5b80-460d-a379-5e1f71ecfd44.png)



Here are the [states in Figma](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18493%3A162104)
![image](https://user-images.githubusercontent.com/108173/182698769-8bd660ea-9c0d-4cc1-b625-73589d405961.png)

**Comment by pstakoun** [comment]
@abelb what would 'Record a run' do here? Should that be the 'Request access' CTA to match tooltip logic?

**Comment by abelb** [comment]
@pstakoun good point. let me update

**Comment by abelb** [comment]
> Updated Design!! Away with that weird big hover target.
> 
> [Figma Prototype (Tooltips on column headers are broken in proto fyi _fixing_)](https://www.figma.com/proto/PAOozuCxtfetqP8fUVvg0y/branch/V0lCq4uBplf9J3GZRiD02m/Cypress-App?page-id=16373%3A174946&node-id=18481%3A162161&viewport=-3529%2C-2113%2C0.5&scaling=min-zoom&starting-point-node-id=18481%3A162161)
> 
> **Updates**
> 
> 1. Replace empty run dots with dashes
> 2. When not logged in, user hovers over dashes and depending on state, will see one of the following on hover:
> 
> **Here are the [states in Figma](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18493%3A162104)** ![image](https://user-images.githubusercontent.com/108173/182701329-37aeee27-f47b-4f8e-a753-c37b6da07fde.png)

**Comment by pstakoun** [comment]
@abelb can you add the finalized designs here based on our latest iterations?

**Comment by abelb** [comment]
![image](https://user-images.githubusercontent.com/108173/183487578-f3d5a70a-4af4-4c3f-bd64-6940d9c64bfc.png)

**Comment by pstakoun** [comment]
@abelb should this have an ease-in/out? Prototype currently doesn't and I think it did before. I honestly don't have an opinion re: whether or not to do this, just want to clarify.

**Comment by abelb** [comment]
I added some to the prototype - yes some ease in / out is good.

[Figma Prototype](https://www.figma.com/proto/PAOozuCxtfetqP8fUVvg0y/branch/V0lCq4uBplf9J3GZRiD02m/Cypress-App?page-id=16373%3A174946&node-id=18481%3A162161&viewport=-3529%2C-2113%2C0.5&scaling=min-zoom&starting-point-node-id=18481%3A162161)

**Comment by marktnoonan** [comment]
@warrensplayer this had been in blocked, was it intentionally moved to Open? I don't recall exactly what we were waiting on that made it blocked. 

If it's unblocked from what we saw as blocking on Tuesday, we might want to flag that there's a dependency here on #23379 which will attempt to consolidate the Login + "cloud connect" components in a way that will support this ticket - since this ticket would then be implementing a new stylistic variation of that new component and putting it into the specs list.
