### ISSUE TITLE
Firefox: Cypress version 10 and above, tests not being running in Firefox browser.

### ISSUE THREAD

**Issue by Zia-ullah** [cypress-io/cypress#22938]
### Current behavior

Hi,
My current system configurations are as under:
OS: Windows 11 Professional
RAM: 16GB
Processor: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz   2.50 GHz.
When I run my tests in any of browsers e.g. (Chrome, Edge, Canary, Electron) then they executed both from Cypress desktop app as well as from Cypress Terminal.

However when I attempted to test the same run the same tests in Firefox then
from desktop app only Firefox browser started but nothing loaded even nothing in the browser console, but terminal keep showing as "Still waiting to connect to Firefox, retrying in 1 second (attempt 23/62).
and in CLI mode same message shown.

Please see the attached images.
![CypressInfo](https://user-images.githubusercontent.com/53328142/181097029-51433eb4-9a05-4e6d-a3c5-dd1bc3b4db34.png)
![CypressInFirefox](https://user-images.githubusercontent.com/53328142/181097048-efb2d6cc-0bb0-4a86-b015-38af7992a000.png)
![CypressDesktopApp](https://user-images.githubusercontent.com/53328142/181097085-4b149b09-8379-4712-a82e-2bed7cf7c6ba.png)
![CypressCLI](https://user-images.githubusercontent.com/53328142/181097100-32c5ee6e-25b2-4c01-815b-d4244ebaff63.png)

Thanks
Ziaullah

### Test code to reproduce

// <reference types="cypress-downloadfile"/>

describe('fileDownload', () => {

it('', () => {    
    cy.downloadFile('https://s.yimg.com/rz/p/yahoo_homepage_en-US_s_f_p_bestfit_homepage.png','cypress/downloads','yahoo-logo.png')
});

### Cypress Version

10

**Comment by Zia-ullah** [comment]
It has started in Version 10.0.0. and now I have upgraded to version 10.3.1. but still unable to run testes in Firefox.

**Comment by tbiethman** [comment]
A fix was released with Firefox 103, which just released today. Please try updating Firefox to 103 seeing if this issue persists. Also see https://github.com/cypress-io/cypress/issues/22086 for more info regarding this issue.
