### ISSUE TITLE
Dashboard Integration Smart Login Notification

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22933]
This is an info banner as per the [designs in Figma](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/V0lCq4uBplf9J3GZRiD02m/Cypress-App?node-id=12097%3A68131).

The login CTA should send the user through the login flow. UTM parameters should be included.
If the banner is dismissed, it should never be shown again.

The conditions for this banner to be visible are:
- The user is not logged in
- The user has been using Cypress for at least 4 days (at least 96 hours since first open)
  - The automatic docs prompts should not pop up within 24 hours of the banners, the same way the docs do not pop up within 24 hours of each other (the banners get priority, so the docs prompts only pop up if no banners have been shown for 24 hours) - we will likely have to make this change in `shouldShowPrompt` in `HeaderBarContent.vue`
- There are no error, warning, or higher priority info banners present
- The banner has never been dismissed by the user

The copy for this banner should be the "A" variant described in [this doc](https://docs.google.com/document/d/1PFN79d3deDyqDVFmVIBe4cVMzWiEll0J6XCpesBZrSg/edit).

Please reference [this sheet](https://docs.google.com/spreadsheets/d/1_ejTVOv8zA9XAH69Eqa7bBrKqoQY__WeQ3Gqsk7fU0w/edit) for info about all relevant states.

**Comment by abelb** [comment]
https://app.clickup.com/t/364rrbv

**Comment by mike-plummer** [comment]
@pstakoun @abelb Just want to confirm the copy in the tagged ClickUp is final - I seem to recall some conversation around the time savings figure and parallelization reference

**Comment by pstakoun** [comment]
@mike-plummer the copy is not final. Will finalize by early next week.

**Comment by abelb** [comment]
Here is the figma link and design - Verbiage to be updated by @pstakoun. I will update the design when verbiage is final
https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=17622%3A150670

![image](https://user-images.githubusercontent.com/108173/182206043-c234566e-b881-4544-ac07-f773bdf388ab.png)

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22933?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by mike-plummer** [comment]
Initial conversations around the "A/B testing" behavior of this ticket were held - outcome was that a new service would need to be exposed by the cloud that would have two behaviors:
1. When the UI decides a banner should become visible, make a request to the service with an identifier like `machineId` to retrieve a segment/cohort ID that should be used. The UI then uses that cohort ID to decide which version of copy to display. Sending in `machineId` allows the cohort choice to be "sticky" for a given user so they aren't shown different content over time
2. When an action is taken from the banner, make a second request to the cloud service to record the fact - this way numbers can be gathered on "activations vs actions" for each cohort

**Comment by mike-plummer** [comment]
Completed in #23256
