### ISSUE TITLE
Project Modal: Pre-Select Existing Project

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22936]
In the "connect project" modal in the runs tab, pre-select the existing project if and only if there is only one.

**Comment by mike-plummer** [comment]
@pstakoun Does the "no runs" check add value in this state? If there's only one project in the menu we may as well default the menu to that option regardless of its runs status

**Comment by pstakoun** [comment]
@mike-plummer good point. I've been going back and forth on this one. Will think on it a bit...

**Comment by pstakoun** [comment]
@mike-plummer Updated with your suggestion - we will select the project if there is only one, regardless of whether or not it has runs.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22936?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by rockindahizzy** [comment]
@pstakoun, there is existing logic today that auto-selects a project if the local project name matches the cloud project name.  I'm curious if this new auto-select logic should be in `addition to` or `in place of` the existing logic.

**Comment by pstakoun** [comment]
@rockindahizzy nice catch, I didn't realize that. What I'm thinking is:
```
if there is a project that matches by name:
    pre-select the matching project
else if there is only one project:
    pre-select the first project
```
Does that make sense to you?

**Comment by rockindahizzy** [comment]
@pstakoun, yep that makes perfect sense, thanks!
