### ISSUE TITLE
Dashboard Integration Smart Record Run Notification

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22935]
This is an info banner as per the [designs in Figma](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/V0lCq4uBplf9J3GZRiD02m/Cypress-App?node-id=12097%3A68131).

The banner should show the record command.
If the banner is dismissed, it should never be shown again.

The conditions for this banner to be visible are:
- The user is logged in
- The user has at least 1 organization
- The current project is connected (i.e. has valid projectId)
- The user has been using Cypress for at least 4 days (at least 96 hours since first open)
  - The automatic docs prompts should not pop up within 24 hours of the banners, the same way the docs do not pop up within 24 hours of each other (the banners get priority, so the docs prompts only pop up if no banners have been shown for 24 hours) - we will likely have to make this change in `shouldShowPrompt` in `HeaderBarContent.vue`
- There are no error, warning, or higher priority info banners present
- The banner has never been dismissed by the user

The copy for this banner should be the "A" variant described in [this doc](https://docs.google.com/document/d/1PFN79d3deDyqDVFmVIBe4cVMzWiEll0J6XCpesBZrSg/edit).

Please reference [this sheet](https://docs.google.com/spreadsheets/d/1_ejTVOv8zA9XAH69Eqa7bBrKqoQY__WeQ3Gqsk7fU0w/edit) for info about all relevant states.

**Comment by mike-plummer** [comment]
@pstakoun Other "smart notification" issues don't reference the "only show if it's been 2 days" behavior - is that intended to be applied to those as well? Going to need a bit more info about how this applies - is the 2-day restriction based on showing a notification that "comes before" this one in the setup workflow, or does it also apply to itself (only show this prompt if it's been 2 days since we last showed it)? And I assume the dismiss behavior overrides the 2 day restriction so we never show it again regardless of time period?

**Comment by pstakoun** [comment]
@mike-plummer I would say no, only this one should have the "2 days" behavior, but I've been debating that a bit. You are correct in assuming the dismiss behavior overrides the 2 day restriction. Anything else unclear here?

**Comment by abelb** [comment]
[Figma Link](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18093%3A153388)

![image](https://user-images.githubusercontent.com/108173/182229069-94ade710-3ee9-4278-843b-2c29a9cc93dd.png)

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22935?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Looks like a few of the Dashboard Integration features have a "10 specs" requirement. If you pick this up, see if anyone else has implemented the "10 specs" check first, to avoid duplicate work :+1:.

**Comment by pstakoun** [comment]
@marktnoonan each prompt has A and B variants (one has a C as well) - this one has it for the CTA

**Comment by pstakoun** [comment]
This is high priority, so would push back against moving it out of the sprint and would rather move out others.

**Comment by marktnoonan** [comment]
Ah cool @pstakoun I was reading the document incorrectly, ty. Let's review priority/order as a whole when everything is estimated.

**Comment by pstakoun** [comment]
I have removed the "2 days" limitation to simplify logic

**Comment by mike-plummer** [comment]
@pstakoun To clarify this statement `The current project is connected (i.e. has valid projectId)`: I assume the intent is to exclude situations where the user has a valid projectId but lacks access to the project?

**Comment by mike-plummer** [comment]
Completed in #23256
