### ISSUE TITLE
Improved Dashboard Integration empty state

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#22931]
Improved empty state for Latest runs and Average duration columns with informative messaging, a login CTA, and dismissal CTA. This is the state shown when the user is not logged in to the Dashboard, does not have a project, does not have access to their project, etc. Basically any state wherein the user does not have data. To show this, the user must have at least 10 tests and at least 2 specs written that do not match the default Cypress scaffolded tests. CTA should be dynamic based on the current state (match banner and tooltip logic) and should include appropriate UTM params (TBD).

Dismissal behavior: When the dismissal CTA is clicked, the marketing empty state should be hidden forever (the user should not ever see it again in the future).

### **Empty state placeholder ACI Alert with Desktop & Mobile views**
[Figma Link
](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18315%3A156874)

**Banner shows:**
- After user has written 10 tests
- With at least 2 specs

![image](https://user-images.githubusercontent.com/108173/182209141-e65e6281-d260-4906-a18f-4b14670877c9.png)

**Comment by abelb** [comment]
Working on Product Marketing-ey dismissable card or modal.

**Comment by mike-plummer** [comment]
@pstakoun Regarding dismissal behavior, when you say "the user should not ever see it again" is that "for the current project" or "across any project on the current device" or some other condition?

@abelb Just a reminder that the two ACI columns get quite small at narrow viewports, so we'll need to make sure the overlay content plays nicely

**Comment by pstakoun** [comment]
@mike-plummer how does the docs menu auto-prompt work? Per-project or global? My gut says to do this one global, but the rest of the "smart prompts" per-project.

**Comment by abelb** [comment]
### **Empty state placeholder ACI Alert with Desktop & Mobile views**
[Figma Link
](https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=18315%3A156874)

**Banner shows:**
- After user has written 10 tests
- With at least 2 specs

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/22931?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34 @rockindahizzy @warrensplayer

**Comment by pstakoun** [comment]
This issue is being moved to the Aug 16 sprint.

**Comment by pstakoun** [comment]
Closing this due to product and design changes.
