### ISSUE TITLE
cy.origin cannot find selector if same origin as top.

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#22942]
### Current behavior

If you create a spec bridge in the same origin as top, you are unable to interact with the window.

### Desired behavior

I know this is a weird edge case but theoretically there shouldn't be a reason why someone couldn't write this example and have the spec bridge find the selector.

### Test code to reproduce

```js
it('cannot find the selector', () => {
  cy.visit('http://www.foobar.com:3500/fixtures/auth/index.html') // Establishes primary origin
  cy.origin('http://foobar.com:3500', () => {
    cy.get('[data-cy="login-idp"]') // It fails to find the selector.
  })
})
```

You can execute this test in the driver code.

### Cypress Version

10.3.1

**Comment by nagash77** [comment]
We will throw an error in this instance
