### ISSUE TITLE
blocking errors not present with manual tests

### ISSUE THREAD

**Issue by PeterL78** [cypress-io/cypress#22948]
### Current behavior

during the tests with cypress there are errors that I do not reproduce with the manual tests.

"TypeError: window .__ tcfapi is not a function"

cypress: 10.3.1
node: v16.15.1

simple code

```
describe ('step one', () => {
	it ('visit', () => {
		cy.visit (URL)
	})
})
```

P.S. the site I'm testing is internal but I found the same error on humanite.fr

### Test code to reproduce

describe ('step one', () => {
	it ('visit', () => {
		cy.visit (URL)
	})
})

### Cypress Version

 10.3.1

### Other

using experimentalSourceRewriting did not bring benefits

**Comment by tbiethman** [comment]
@PeterL78 from a cursory search, it looks like `window .__ tcfapi` is part of an API in the service of GDPR: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#how-does-the-cmp-provide-the-api

Within Cypress, your site will be loaded within an iframe, which may impact how you or third-parties execute code. Can you track down what logic should be defining `window .__ tcfapi` and whether or not it executes as expected when loaded in an `iframe`?

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by symn** [comment]
@AtofStryker I am now running into the same problem. Before the update to `cypress@10.9.0` on `cypress@5.0.0`, we were able to copy necessary functions into the `window` object that Cypress has access to via a workaround, like so:
```
Cypress.Commands.add('agreeQuantcastConsentModal', () => {
  const webUrl = getUiUrl('web');
  // Quantcast Consent v2.0 modal asynchronously creates functions on the `top`
  // window object that are not accessible from inside the Cypress test iframe. This
  // rewrites the functions from `top` window to the one Cypress tests can access.
  cy.on('window:before:load', win => {
    let __tcfapi;
    Object.defineProperty(win, '__tcfapi', {
      get: () => {
        if (!__tcfapi) {
          __tcfapi = win.top.__tcfapi;
        }
        return __tcfapi;
      },
      set: value => {
        __tcfapi = value;
      }
    });

    let __uspapi = undefined;
    Object.defineProperty(win, '__uspapi', {
      get: () => __uspapi,
      set: value => {
        __uspapi = value;
      }
    });
  });

  cy.visit(webUrl);
  cy.waitForDOMElement('qc-cmp2-ui');
  cy.contains('Agree', {matchCase: false}).click();
});
```
This fails now. There is no problem with copying or modifying the window object though. However, it seems like that Cypress internally now runs tests differently. `window.top` is no reliable frame anymore i guess. I noticed that the Cypress testing window does not refresh anymore for new tests but adds new (project) iframes. This might be a problem with my simple copy / paste mechanism

**Comment by nagash77** [comment]
@symn can you please open a new issue with details on how to reproduce the issue you are seeing.  Please be sure to try and replicate on the latest version of Cypress as well 11.1.
