### ISSUE TITLE
update lodash to v4.17.21  (in @cypress/webpack-preprocessor)

### ISSUE THREAD

**Issue by edvansab** [cypress-io/cypress#22949]
Operating System: All
Cypress Version: @cypress/webpack-preprocessor
Browser Version: n/a

### Current behavior

Security vulnerability, lodash 4.17.20 is vulnerable to Command Injection to snyk: https://snyk.io/vuln/npm:lodash@4.17.20

### Desired behavior

Update package to lodash 4.17.21

### Test code to reproduce

/

### Cypress Version

/

**Comment by edvansab** [comment]
Hi guys, do we have any progress for this issue? Thanks @nagash77

**Comment by nagash77** [comment]
@edvansab We do not have any progress on this issue.  Please feel free to submit a PR with this change. There is a Contributing guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md
