### ISSUE TITLE
cy.intercept() not intercepting fetch requests every 2nd or 3rd request

### ISSUE THREAD

**Issue by ezrag26** [cypress-io/cypress#22966]
### Current behavior

I noticed that while most of the time fetch requests were being intercepted, other times they were not, causing my tests to fail when wait timed out.

I ended up taking one of the tests and copying it many times to see if there was any pattern.

Each test has 2 fetch requests (only 1 of which is attempted to be intercepted), and at least every 3rd tests fails, meaning no more than 2 tests run successfully one after the other.

![image](https://user-images.githubusercontent.com/36003744/181478372-7b5ab391-9167-49c6-9edc-f9de2b759d74.png)

Running the test 22 times: 14 passed, 8 failed with `Timed out retrying after 5000ms: cy.wait() timed out waiting 5000ms for the 1st request to the route: foo. No request ever occurred.` even though the logs show the request was in fact made

### Desired behavior

`cy.intercept()` should intercept all matched routes from fetch requests

### Test code to reproduce

```js
// api.js
module.exports = {
  create: () => {
    return fetch('/foo', {
      method: 'POST',
      body: JSON.stringify({
        qux: 'qux'
      }),
      headers: {
        'Content-Type': 'application/json'
      }
    }
  },

  delete: ({ id } ) => {
    return fetch(`/foo/${id}`, {
      method: 'DELETE',
    }
  }
}
```

```js
describe('Intercept fetch', () => {
  it('Test intercept fetch', () => {
    cy.intercept('POST', '/foo').as('foo')
    api.create()

    // do some awesome test

    cy.wait('@foo').then(interception => {
      api.delete({ id: interception.response.body.id })
    })
  })

  // repeat test at least 2 more times
})
```

### Cypress Version

10.3.0

**Comment by ezrag26** [comment]
Was able to fix it with this:
```
describe('Intercept fetch', () => {
  it('Test intercept fetch', () => {
    cy.intercept('POST', '/foo').as('foo')
    .then(() => {
      api.create()
    })
    
    // do some awesome test

    cy.wait('@foo').then(interception => {
      api.delete({ id: interception.response.body.id })
    })
  })

  // repeat test at least 2 more times
})
```
So I guess the request was being made before `cy.intercept()` had finished setting up?

**Comment by AtofStryker** [comment]
> So I guess the request was being made before cy.intercept() had finished setting up?

@ezrag26 This is the likely guess, since Cypress commands do not execute synchronously, subjecting the code to a possible race condition. The solution you have provided should work consistently. Another option to try would be to use a `cy.then()` to fire the api request after the intercept to guarantee the intercept is set up before executing.

**Comment by ezrag26** [comment]
@AtofStryker Thank you for the reply, but I'm not sure what you mean in your option
> to use a `cy.then()`

According to the [documentation](https://docs.cypress.io/api/commands/then#Requirements) for `.then()`:
> `.then()` requires being chained off a previous command.

unless you mean to use a `.then()` chained off of the `.intercept()`, which is the solution I provided. Just tying to understand if I have another option that I can use or just the one.

**Comment by AtofStryker** [comment]
It is essentially the same thing. What I was saying is this is also a valid option: 

```
describe('Intercept fetch', () => {
  it('Test intercept fetch', () => {
    cy.intercept('POST', '/foo').as('foo')
    cy.then(() => {
      api.create()
    })
    
    // do some awesome test

    cy.wait('@foo').then(interception => {
      api.delete({ id: interception.response.body.id })
    })
  })

  // repeat test at least 2 more times
})
```

**Comment by ezrag26** [comment]
I was just confused because you were saying to use `cy.then()` which I thought was invalid since according to the documentation:
> .then() requires being chained off a previous command.

I see an older issue (#466) where it was planned to convert `.then` into a child command, but this never seemed to have actually happened.

So either the documentation is wrong or `cy.then()` is invalid, but in either case, the documentation should be updated to reflect that.

**Comment by AtofStryker** [comment]
> So either the documentation is wrong or cy.then() is invalid, but in either case, the documentation should be updated to reflect that.

To your point, I do not think this is well documented. FWIW we usually encourage things like this to be chained off of the existing command. I'll talk with the team to see if this is something we want to be more of a known behavior.
