### ISSUE TITLE
Cypress.env has changed behavior in v10 without any mention in the docs / changelog

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#22961]
### Current behavior

```js
it('first', () => {
  console.log('first test %o', Cypress.env())
  Cypress.env('name', 'Joe')
})

it('second', () => {
  console.log('second test %o', Cypress.env())
})
```

In Cypress v9 the first test run (using `cypress open`)
The first run
<img width="590" alt="Screen Shot 2022-07-27 at 16 01 51" src="https://user-images.githubusercontent.com/2212006/181361927-7a08bae5-76e6-4df3-ae28-d0113df50fc1.png">

The second run (while the test runner stays open using "R")
<img width="295" alt="Screen Shot 2022-07-27 at 16 02 05" src="https://user-images.githubusercontent.com/2212006/181361777-c1653041-4dd7-47a3-abac-4f21f9078b47.png">

The `Cypress.env` object keeps the changed / updated object.

The same test in Cypress v10
The first run:

<img width="454" alt="Screen Shot 2022-07-27 at 16 05 54" src="https://user-images.githubusercontent.com/2212006/181362376-ddfbef2a-0912-491a-8c2f-649783876192.png">

The second run (using "R")
<img width="230" alt="Screen Shot 2022-07-27 at 16 06 08" src="https://user-images.githubusercontent.com/2212006/181362400-31d07b9f-ea1e-4068-9e07-120e546471e0.png">

So the `Cypress.env` object is reset before running the spec, even if the test runner stays open, which is a huge change from v9, and I don't think it was mentioned anywhere in the docs.

### Desired behavior

I would love the old behavior, or at least some way to preserve values between the spec runs. Right now using the plugins process via `cy.task` or something seems to be the only solution to keep the data around

### Test code to reproduce

The tests shown

### Cypress Version

10.3.1

**Comment by bahmutov** [comment]
I worked around it by creating https://github.com/bahmutov/cypress-plugin-config which stores the values on `window.top` (with `Cypress.env` fallback). You can see it in action in https://github.com/bahmutov/cypress-slow-down plugin

**Comment by tbiethman** [comment]
@bahmutov thank you for logging this. I wasn't aware that Cypress.env had this behavior pre-10.x. I did a little digging in the code, seems like this has been a discussion point before:

https://github.com/cypress-io/cypress/blob/f0ae283b9278ee36c11fcc761a424800035baf5f/packages/driver/src/cypress.ts#L212-L213

And like you said, this change wasn't documented, but the current [env documentation](https://docs.cypress.io/api/cypress-api/env#Syntax) doesn't seem to regard either behavior as expected or valid. Personally, it feels odd that we would persist the env between soft re-runs and potentially introduce indeterminant tests, as your example shows. 

Your plugin seems like a reasonable middle-ground, though. Am I correct in that your plugin is most impacted by this change with its [Change from Command-Line](https://github.com/bahmutov/cypress-slow-down#change-the-command-delay-from-devtools) API? Or are there other impacts I'm not seeing?

**Comment by bahmutov** [comment]
Yeah it is just unexpected and might affect plugins that cache some data during the first run
