### ISSUE TITLE
Parallel cypress tests in circleCI 

### ISSUE THREAD

**Issue by agoldis** [cypress-io/cypress#2297]
### Current behavior:
All cypress tests are run sequentially in a single docker image. CircleCI has an ability to split tests automatically as appears here:
https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-test-files
I know there is some work done to allow simple parallel execution here
https://github.com/cypress-io/cypress/issues/1690

### Desired behavior:
I am looking for an easy way to speed up cypress test runs as part CI at circleCI, and use parallelism capabilities for both tools. 
And seems like just letting cypress to have list of files specified explicitly would do the job.

### Versions
- Cypress 3.0.2
- CircleCI environment

**Comment by bahmutov** [comment]
Will be done soon and released in 3.1.0

**Comment by brian-mann** [comment]
I am closing this because the work is already done and merged into `develop` - we just have to release it, and are currently updating the docs. 

The PR is here: https://github.com/cypress-io/cypress/pull/2154
