### ISSUE TITLE
cy.mount with Vue 2.7 + Vite JSX transform does not work

### ISSUE THREAD

**Issue by JessicaSachs** [cypress-io/cypress#22975]
### Context
Unable to mount any JSX components in the latest minor version of Vue (using Vite JSX transform). Vue 2.7 is critical in the upgrade path for all Vue users trying to get to Vue 3. It introduces `<script setup>`, etc. A standard upgrade path for a Vue user is usually like:

```
Vue CLI => Vite => Vue 2.7 => Vue 3
```

### JSX + Vue + Cypress
We've recommended and continue to recommend JSX in `*.cy.{jsx,tsx}` spec files because of how easy + nice it is to test slots and add spies and events. Playwright recommends the same.

### Current Behavior

Currently, when a user tries to upgrade to Vue 2.7 from Vue 2.6, any + all of their JSX/TSX tests will stop compiling with the following error...

**Stacktrace**

```
FAIL  src/components/__tests__/HelloWorld.spec.jsx > HelloWorld > renders properly
TypeError: Cannot read properties of undefined (reading 'props')
 ❯ normalizeProps node_modules/vue/dist/vue.runtime.common.dev.js:4802:27
 ❯ mergeOptions node_modules/vue/dist/vue.runtime.common.dev.js:4891:5
 ❯ Function.Vue.extend node_modules/vue/dist/vue.runtime.common.dev.js:5698:23
 ❯ createInstance node_modules/@vue/test-utils/dist/vue-test-utils.js:2646:26
 ❯ Proxy.mount node_modules/@vue/test-utils/dist/vue-test-utils.js:14051:18
```

**UI/UX**
![Screen Shot 2022-07-28 at 11 31 29 AM](https://user-images.githubusercontent.com/2801156/181577869-50ec8a23-1c1d-46cf-add4-b16fd9e78f79.png)

### Is this a Cy issue or a Vite issue?
I've tried to isolate the issue. It's also failing in Vue Test Utils + Vitest, so I suppose I'll file a sibling issue over there. We may or may not need to update the Cypress Vue 2 mounting library to patch this issue.

### Desired behavior

I can write JSX + TSX components in Cypress with Vue 2.7.

### Test Code
```tsx
it('works', () => {
  // either in Vitest or in Cy
  mount(() => <HelloWorld msg="Hello Vitest!"></HelloWorld>)
})
```

#### Cypress failing: https://github.com/JessicaSachs/vue-2-tsx-cypress

```shell
pnpm install
pnpm cypress open --component
```

#### Vitest failing: https://github.com/JessicaSachs/vue-2.7-vtu-jsx-vitest

```shell
npm install
npm run test:unit
```

### Cypress Version

10.3.1

### Other

I pinged within the Vue team chat to make sure that the render function I'm writing is valid in Vue. I don't know why it wouldn't be, but I'm double checking anyways.

**Comment by MKhasib** [comment]
Hello @JessicaSachs
Is this issue still valid in 2024? or you were able to find a workaround it

**Comment by gweesin** [comment]
Still doesn't working now:

![image](https://github.com/user-attachments/assets/1b4ad8e8-04b8-45e9-9397-823c0ccab62b)

**Comment by jennifer-shehane** [comment]
Closing as Vue 2 will no longer be supported in Cypress 14+
