### ISSUE TITLE
Incorrect spec path relayed to dashboard

### ISSUE THREAD

**Issue by rockhold** [cypress-io/cypress#22971]
### Current behavior

An issue was logged to the dashboard about an [incorrect GitHub link for specs](https://cypress-io.atlassian.net/browse/CLOUD-599), which upon further investigation, seems to suggest the test runner is at fault for the incorrect link. Speaking with @RobBickel about the issue, he shared some details of his investigation, noting the following:

> cypress-services derives it from the database. It is constructed from the codeframe. The codeframe is generated in the test runner. The test runner uses the error message to generate a stacktrace, and uses the file uri from where the occured in the error, applies some regex, and adds the relative path to the codeframe. Most of the time the regex and join work just fine, but sometimes we get an bad url which causes that to boil up to the customer clicking and getting 404 from the dash.

Looking at an example generated link that fails compared to what it SHOULD BE, it is possible that monorepo's mess with the current logic.

Bad Link:
[https://github.com/cypress-io/cypress-services/blob/5915dd88fd957431fbb1ee0642bf7e69292c62c1/cypress/integration/organizations/ProjectsList_spec.ts#L480](https://github.com/cypress-io/cypress-services/blob/5915dd88fd957431fbb1ee0642bf7e69292c62c1/cypress/integration/organizations/ProjectsList_spec.ts#L480)

Good Link:
[https://github.com/cypress-io/cypress-services/blob/5915dd88fd957431fbb1ee0642bf7e69292c62c1/frontend/packages/dashboard/cypress/integration/organizations/ProjectsList_spec.ts#L480](https://github.com/cypress-io/cypress-services/blob/5915dd88fd957431fbb1ee0642bf7e69292c62c1/frontend/packages/dashboard/cypress/integration/organizations/ProjectsList_spec.ts#L480)

For more information regarding internal conversations about this issue, see the Cloud issue referenced above.

### Desired behavior

When the dashboard displays a link for a failed spec, the URL is correct.

### Test code to reproduce

* Record a failing test to the dashboard (Note: this *may* have to be part of a monorepo)
* Within Latest Runs, find the run including your failed test and click on it
* Find and click on the failed test
* Within the overlay that displays to the right, find and click on the link to the failing spec file
* Note the 404 message

### Cypress Version

10.3.1

### Other

Here's a screenshot showing the specific link that is sometimes incorrect.
![image](https://user-images.githubusercontent.com/4065848/181572231-d7e62c22-86b0-44a7-b2f0-68952ff1b5c3.png)

**Comment by rachelruderman** [comment]
Here's the [dashboard link to the screenshotted run in the description](https://dashboard.cypress.io/projects/5b79905a-f894-4e91-b60c-fff4d94c218a/runs/66591/overview/87896233-c576-4833-9a65-75090a5acb3b)

**Comment by rachelruderman** [comment]
I agree with @RobBickel's assessment that this is related to monorepos given that...
1. Testing with cypress-examples-kitchensink single repo worked as expected. [See dashboard link](https://dashboard.cypress.io/projects/4b7344/runs/22864/overview/709727cd-57af-4be9-b62e-8ca4b9337eb5)
2. Our very own monorepo for the Cypress app is experiencing the same error. [See dashboard link](https://dashboard.cypress.io/projects/ypt4pf/runs/37373/overview/10e03fcd-e6ab-4ee5-8eb1-a716bb6272e8)

**Comment by rachelruderman** [comment]
The file with the logic in question is [data-context/src/sources/FileDataSource.ts](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/sources/FileDataSource.ts)
