### ISSUE TITLE
test succeeds, but prints "We expected to find the global Cypress in the parent window but it is missing" to console

### ISSUE THREAD

**Issue by constantlyk** [cypress-io/cypress#22977]
### Current behavior

the steps should be documented here: https://github.com/constantlyk/cypress-program-guide-demo#the-terribly-wrong-error

1. clone https://github.com/constantlyk/cypress-program-guide-demo
2. `npm install`
3. in terminal, enter `npm run cy:open:prod`
4. in the chrome instance opened by the test runner, open the chrome dev tools console
5. click the `intercept-graphql.cy.js` spec
6. the test does seem to succeed, but it prints this message to the console
```
Uncaught Error: Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue.
    at ./injection/main.js (VM69 authorize:3:1090)
    at n (VM69 authorize:3:179)
    at 0 (VM69 authorize:3:2416)
    at n (VM69 authorize:3:179)
    at VM69 authorize:3:971
    at VM69 authorize:3:980
```

### Desired behavior

i don't think i should be seeing concerning errors in the console

### Test code to reproduce

https://github.com/constantlyk/cypress-program-guide-demo, spec `intercept-graphql.cy.js` using `cypress/config/prod.env.config.js`.

(you can actually replicate this issue with an even simpler test: just remove the `beforeEach()` hook and the corresponding `cy.wait()` from the spec file.)

### Cypress Version

10.3.1

### Other

* the console message does not appear if i run this test through the command line: `npx cypress run --e2e --browser=chrome -C cypress/config/prod.env.config.js --spec cypress/e2e/intercept-graphql.cy.js --headed`
* i wonder if the test would actually fail if i added more meaningful assertions? in other tests in my suite, this console error shows up, and the page contents are blank ([in much the same way as i reported earlier,](https://github.com/cypress-io/cypress/discussions/22947), although in this case the blank is replicable in headed and interactive modes as well). are these both symptoms of the same disease?
* i suspect some of the issues i've found trying to test this domain through cypress are related to iframes, including an annoyingly persistent cross-origin security error triggering (spuriously, we believe) on or around the signin subdomain frame, and i hope that whatever the resolution to this ticket might be, that it solves all my other problems 😅

**Comment by mjhenkes** [comment]
@constantlyk, thanks for the great reproduction repo and steps. I can verify that this is indeed happening.

I bet that this is related to your signin subdomain. This error occurs when cypress injects a script into an html request but cannot find a cypress instance from the parent frame.

It appears we're injecting into the `https://signin.asco.org/oauth2/<id>/v1/authorize` request which i assume is loaded in an iFrame. This will likely be resolved by our upcoming iframe work (https://github.com/cypress-io/cypress/issues/136).

**Comment by constantlyk** [comment]
@mjhenkes amazing!! i suspected that signin request was the troublemaker here. thanks so much!

when do you think the iframe work will be released, and what workarounds would you suggest i implement or investigate in the meantime?

**Comment by mjhenkes** [comment]
As far as i know this is a benign error that you can safely ignore. I'm not as sure about the 'annoyingly persistent cross-origin security error'. iFrame work is currently scheduled to start after we get the work done to take cy.origin out of experimental. So roughly q1 2023, but lots can happen between then and now.
