### ISSUE TITLE
Add Angular CT Schematic

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/cypress#22976]
## Part 1
It would be great for users of Angular Component Testing to be able to use the angular CLI to generate component tests for them. We do something similar with the Cypress Angular Schematic for `e2e`:

```bash
ng generate @cypress/schematic:e2e
```

I would like to propose the same functionality but for component testing:

```bash
ng generate @cypress/schematic:ct button
```

This would essentially generate a file named `button.component.cy.ts` that looks like the following:

```ts
import { ButtonComponent } from './button.component'

describe('ButtonComponent', () => {
  it('can mount', () => {
    cy.mount(ButtonComponent)
  })
})
```

## Part 2
By having this, we could then also wrap the current Angular CLI component generator to also call `@cypress/schematic:ct` as well. This way users who use the angular CLI to generate a component would get the following files

```bash
ng generate component button
```

### Scaffolded Files:

- `button.component.ts`
- `button.component.css`
- `button.component.cy.ts`

This would also require a schematic that would also setup your Angular CLI project to use this schematic. Something that would look like the following:

```bash
ng add cypress-angular-ct
```

To increase adoption of Angular CT support we could also throw this as a prompt at the end of the Cypress Launchpad to ask users if they want to add this schematic or something like that

### Why is this needed?

This will improve the developer experience for users by making the generating of CT specs super simple and ultimately an after thought if we wrap around the `ng generate component` schematic. By implementing this we will increase users adoption of Angular CT and improve over DX by doing all the boilerplate work for  developers.

**Comment by d-koppenhagen** [comment]
Isn't it already implemented @jordanpowell88 ?

**Comment by jordanpowell88** [comment]
@d-koppenhagen yes this is mostly implemented but we still need to add this as part of the setup

**Comment by jordanpowell88** [comment]
We want to implement this: https://github.com/angular/angular-cli/pull/22860

**Comment by w0wka91** [comment]
So we still need 2 things for resolving this issue:

1. Implement part 2 of this issue and wrap the original Angular CLI component generator
2. Extend the angular.json configuration and add `@cypress/schematic` to the `schematicCollections` Array

Is there already work in progress on this one or can I work on it?

**Comment by jordanpowell88** [comment]
@w0wka91 Go for it!
