### ISSUE TITLE
Tests Run in Electron when Using V8 Snapshot Will Sometimes Crash

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#22985]
### What would you like?

When using v8 snapshots, electron should not crash when given a long running spec

### Why is this needed?

Each v8 context in the app uses a separate copy of the snapshot. That includes electron browsers and iframes within them. We also have a leaking iframe problem. So multiply a non trivial snapshot size times all of the iframes in a long running spec. And we run out of memory.

### Solution

* ~~Work with electron to provide a way to provide separate snapshots for main and renderer processes: https://github.com/electron/electron/issues/35170~~
* Upgrade to v21 once that issue is fixed and incorporate the changes

**Comment by sharozraees802** [comment]
"numTestsKeptInMemory": 0,
add this on cypress.json or cypress.config.js

**Comment by ryanthemanuel** [comment]
Closed with https://github.com/cypress-io/cypress/pull/24170
