### ISSUE TITLE
Investigate and Support logging into accounts.google.com with Firefox

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#22988]
### What would you like?

I would like to be able to log into accounts.google.com as an identity provider within cypress using Firefox as my browser. Google login should work with the merging of #22958 and #22963 inside of Cypress when using Electron and Edge.

**Comment by AtofStryker** [comment]
From @mschile 's investigation, it looks like the `network.proxy.allow_hijacking_localhost` and running insecure localhost in http is causing [Crypto.subtle](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) to be missing in firefox

#### The following errors show up when running with the Auth0 SDK:
![](https://user-images.githubusercontent.com/3980464/181607720-3a30e391-9f4d-4553-bc4b-49a37186f136.png)

#### And the following error shows up when running MSAL in an insecure localhost
![](https://user-images.githubusercontent.com/3980464/181608694-93e4b833-a819-4729-a276-7b06cb101c9c.png)

**Comment by AtofStryker** [comment]
Since I do not have the ability to trust certificates on my machine, I gave this a quick test with [ngrok](https://formulae.brew.sh/cask/ngrok) with https port forwarding enabled and it does look to solve the issue in firefox (tested with Auth0 and MSAL). This likely isn't a realistic step for users to configure as it would require changing OAuth configuration settings and some intervention for visiting through 

Next step might be to try trusted certificates on a non federated machine using [mkcert](https://github.com/FiloSottile/mkcert) to trust localhost?

**Comment by mschile** [comment]
I was able to use `mkcert` on my machine to create a trusted certificate for localhost and was able to successfully login to Google auth with Firefox.

**Comment by AtofStryker** [comment]
I am going to close this as we plan on including this in the `cy.origin` docs to run localhost with a cert (likely `mkcert`) with firefox. This is a more broad issue that is required by a lot of auth libraries, so we might want to open another issue in regards to this generally with insecure localhost
