### ISSUE TITLE
Add Angular Mount Support For Templates

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/cypress#22991]
### What would you like?

The current Angular `mount` function has support for the `Type<T>` or essentially the Component Class. This works great for most instances but it would be nice in others to be able to add support for the template itself. Given the following component

```ts
@Component({
  selector: 'app-selector',
  templateUrl: `
    <button (click)="clicked.emit()">
      <ng-content></ng-content>
    </button
  `
})
export class ButtonComponent {
  @Output() clicked = new EventEmitter()
}
```

We could support both of the following:

```ts
cy.mount(ButtonComponent, {
  componentProperties: {
    clicked: {
      emit: cy.spy().as('clickedSpy')
    } as any
  }
})
```

```ts
cy.mount(`<app-button (clicked)="cy.spy().as('clickedSpy')">Click Me</app-button>`)
```

We might be able to use something like [overrideTemplateUsingTestingModule](https://angular.io/api/core/testing/TestBed#overrideTemplateUsingTestingModule) to accomplish this but there isn't much documentation around what this method does at the moment.

The other option is to use overrides do something like the following:

```ts
TestBed.overrideComponent(ButtonComponent, {
  set: {
    template: `// the template passed to mount`
  }
}
```

### Why is this needed?

This is needed to improve the overall DX of the Angular CT mount. It also gives users more preference on how they mount there components to match there current use cases, team skill sets, long term goals, etc.

**Comment by mschile** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/23117, but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
