### ISSUE TITLE
Overriding tsconfig.json path

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#22993]
At the moment the ts-node configuration searches the tsconfig.json at the cypress config file location.
We are using different tsconfig.json files for local development and running on ci machines.
It would be nice to have the possibility to override the tsconfig.json path during the startup of cypress.

**Comment by nagash77** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will consider reopening the issue.
