### ISSUE TITLE
console.log on click of cy.focused() should more closely match console.log of click on cy.get()

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#23]
When I click on `cy.focused()` from command UI, only the command is logged in console. I would like the console to more closely match the console log of click on `cy.get()` from command UI including:

* Selector
* Returned
* Elements

**Console.log of cy.focused()**
![screen shot 2015-04-16 at 12 02 52 pm](https://cloud.githubusercontent.com/assets/1271364/7185499/f0698f2a-e430-11e4-8f0b-318d8eae90d6.png)

**Console.log of cy.get()**
![screen shot 2015-04-16 at 12 06 20 pm](https://cloud.githubusercontent.com/assets/1271364/7185513/09e43c0c-e431-11e4-852d-aa5506422d61.png)

**Comment by brian-mann** [comment]
It does return the same fields as `cy.get` when `cy.focused` returns an element.  When it returns nothing, it did not do a good job communicating this.  Thus, I've improved its response.

Fixed in `0.5.3`. [Changelog](https://github.com/cypress-io/cypress/wiki/Changelog#053-04192015)
