### ISSUE TITLE
cy.visit and cy.request doesn't submit current browser's User-Agent header

### ISSUE THREAD

**Issue by harz87** [cypress-io/cypress#230]
We are using ruby gem https://github.com/fnando/browser
to check if the browser is supported by our App. 
They are using request.headers["User-Agent"] to identify the browser.

In an normal chrome instance User-Agent is set correctly and Cypress "Chrome" it is suppressed and not submitted.

**Comment by brian-mann** [comment]
Can recreate.

**Comment by brian-mann** [comment]
The browser isn't the browser or the way we spawn the browser - we simply omitted (through sheer oversight) to manually set `User-Agent` headers when making a request *outside* of the browser.

During a `cy.visit` and `cy.request` we do just that.

The correct approach would be to pass along the current browser's user agent when these underlying API's are called so it's completely seamless.

**Comment by brian-mann** [comment]
Fixed in [`0.17.6`](https://github.com/cypress-io/cypress/wiki/Changelog#0176-10042016).
