### ISSUE TITLE
Incorrect string sent when there is no PR (Travis)

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2300]
@bahmutov commented on [Tue Aug 07 2018](https://github.com/cypress-io/cypress-api/issues/774)

When there is no PR, I see wrong url `#false`

<img width="566" alt="screen shot 2018-08-07 at 6 56 21 pm" src="https://user-images.githubusercontent.com/2212006/43806875-df3d8614-9a73-11e8-8c79-41fa9420eddb.png">

API returns bad information for this case

<img width="902" alt="screen shot 2018-08-07 at 6 57 19 pm" src="https://user-images.githubusercontent.com/2212006/43806891-f6a006ec-9a73-11e8-8149-b8e879dba2a2.png">

The test runner probably does not properly convert "false" into boolean

**Comment by bahmutov** [comment]
example: https://dashboard-staging.cypress.io/#/projects/4b7344/runs/1802/specs

**Comment by brian-mann** [comment]
This is an API issue, not test runner. Closing.

**Comment by bahmutov** [comment]
when printing travis env variables using `$(npm bin)/print-env TRAVIS` I see in https://travis-ci.org/cypress-io/cypress-example-kitchensink/builds/412825011 output

```
TRAVIS_PULL_REQUEST=false
```

I believe the env variable is string in this case

**Comment by amirrustam** [comment]
I can account for this "false" string in the API, but just for Travis of course. We have to surface each env var that needs special attention and handle them one-by-one as they are discovered.
