### ISSUE TITLE
Remove fs.sync calls from framework detection

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#23016]
### Current behavior

When detecting CT frameworks, we have to look at the user's package.json to detect what dependencies they have. We synchronously read this package.json multiple times. Code [here](https://github.com/cypress-io/cypress/blob/f147ebbcc63dcb8199472a9ae6a0b78a189ba428/packages/scaffold-config/src/frameworks.ts#L24). There is also a [globby.sync](https://github.com/cypress-io/cypress/blob/f147ebbcc63dcb8199472a9ae6a0b78a189ba428/packages/scaffold-config/src/frameworks.ts#L24) call that she be converted as well

### Desired behavior

Convert the fs read to be async and reduce the number of redundant package.json reads.

### Cypress Version

10.3.1

**Comment by brian-mann** [comment]
also these should not be sync calls because of the `EMFILE / ulimit` problem... needs to use graceful-fs aka regular `fs.readJson` since at this point we are already watching files and you could have crashes.

**Comment by lmiller1990** [comment]
Silly question, if we are at the max file watching limit, regardless of whether we do a sync or async `readJson`, what happens? Will it just wait eternally, or does `graceful-fs` have some kind of smart way to manage these situations?

As an aside - always good to avoid sync operations on the file system, but this logic is only used during detecting the frameworks/checking dependencies, from what I can see - at which point we should not be watching files, except for ones related to `cypress.config.js`. 

This refactor is still a good idea, but in this particular use case, we certainly should not be watching very many files. If we are, we likely have a bug somewhere.

**Comment by lmiller1990** [comment]
> retries them once something closes if there is an EMFILE

So basically what I said - if my system has a limit of N files, and they are all getting watched, and I want to read one more (N+1), it'll be in the queue eternally. Eg: if my N files were all related to my `cypress.config.js`, that would never happen. We watch these for the duration of the app lifecycle. so we can respond to changes.

Either way, the best solution to a problem is to eliminate the problem entirely, starting now: https://github.com/cypress-io/cypress/compare/lmiller/windows-vite-fix?expand=1.
