### ISSUE TITLE
Config file throws error on Windows only - cypress.config.ts

### ISSUE THREAD

**Issue by GeorgeXCV** [cypress-io/cypress#23017]
### Current behavior

Project runs fine on Mac but on Windows the config file throws error.

```
[Stack trace](http://localhost:53643/__launchpad/index.html#)
Error: Cannot find module 'C:\Users\George\Documents\Projects\project-name\cypress\config\'development'.json'
Require stack:
- C:\Users\George\Documents\Projects\project-name\cypress.config.ts
- C:\Users\George\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js
- C:\Users\George\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\require_async_child.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\George\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Users\George\Documents\Projects\project-name\cypress.config.ts:9:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async setupNodeEvents (C:\Users\George\Documents\Projects\project-name\cypress.config.ts:9:26)
```

### Desired behavior

I should be able to open Cypress without error, just like on Mac.

### Test code to reproduce

**Root file (cypress.config.ts):**
```
import { defineConfig } from "cypress";
import { checkGmail, CheckGmailParam } from "../project-name/cypress/plugins/checkGmail";
import * as path from "path";

export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      const version = config.env.version || 'development'
      const configFile = await import(path.join(
        config.projectRoot,
        'cypress/config',
        `${version}.json`
      ));
      config.baseUrl = configFile.baseUrl
      config.env = configFile.env
      config.defaultCommandTimeout = 10000
      config.chromeWebSecurity = false
      on("task", {
        async checkGmail(args: CheckGmailParam) {
          return await checkGmail(args);
        },
      });
      return config
    },
    reporter: 'mochawesome'
  },
});
```

**Development JSON path** = cypress/config/development.json

### Cypress Version

10.3.1

**Comment by tbiethman** [comment]
@GeorgeXCV thanks for the report. From your error:

```
Error: Cannot find module 'C:\Users\George\Documents\Projects\project-name\cypress\config\'development'.json'
```

It looks like there may be some incorrect/unexpected interpolation there? Have you tried using `require` rather than an awaited import?


But otherwise, there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by GeorgeXCV** [comment]
> @GeorgeXCV thanks for the report. From your error:
> 
> ```
> Error: Cannot find module 'C:\Users\George\Documents\Projects\project-name\cypress\config\'development'.json'
> ```
> 
> It looks like there may be some incorrect/unexpected interpolation there? Have you tried using `require` rather than an awaited import?
> 
> But otherwise, there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

If you use that config file in a Cypress project on a Windows machine you will be able to reproduce. I don't believe it is an issue with the code because project has no errors if run on Mac. Also it is using `import` due to TypeScript/ESLint.

**Comment by rockindahizzy** [comment]
Hey @GeorgeXCV, 

I tried to use the above config file on Windows and was not able to successfully reproduce this error. Could you possibly provide a reproduction via a public github repo?

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by GeorgeXCV** [comment]
> Hey @GeorgeXCV,
> 
> I tried to use the above config file on Windows and was not able to successfully reproduce this error. Could you possibly provide a reproduction via a public github repo?

Are you using TypeScript? Maybe try including the config folder also.
<img width="220" alt="Screenshot 2022-08-08 19 58 36" src="https://user-images.githubusercontent.com/13811547/183493521-4537c0c6-b50a-49df-8863-26274561a0db.png"> 

config json files are just values like this:
```
{
    "env": {
        "baseUrl": "https://test.web.app/",
        "stripeVisa" : "4242424242424242"
    }
}
```

**Comment by rockindahizzy** [comment]
@GeorgeXCV, thanks for the additional info. Unfortunately, I am still not able to recreate the issue with the information provided.

Could you provide a reproducible example of the issue you're encountering?

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by GeorgeXCV** [comment]
> @GeorgeXCV, thanks for the additional info. Unfortunately, I am still not able to recreate the issue with the information provided.
> 
> Could you provide a reproducible example of the issue you're encountering?
> 
> Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**tsconfig.json:**
```
{
    "compilerOptions": {
      "target": "es5",
      "lib": ["es5", "dom"],
      "types": ["cypress", "node"]
    },
    "baseUrl": "./cypress",
    "include": ["**/*.ts"]
  }
```

**Comment by rockindahizzy** [comment]
Hey @GeorgeXCV, I will try to see if I can run with this config. However it would be extremely helpful if you could provided a reproducible example in a public GitHub repo. This would remove variables such as versions, which could cause us to have different outcomes.

**Comment by GeorgeXCV** [comment]
> Hey @GeorgeXCV, I will try to see if I can run with this config. However it would be extremely helpful if you could provided a reproducible example in a public GitHub repo. This would remove variables such as versions, which could cause us to have different outcomes.

```
{
  "name": "e2e-automation",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cypress:open:dev": "cypress open --env version='development'",
    "cypress:run:dev": "cypress run --env version='development'",
    "cypress:open:production": "cypress open --env version='production'",
    "cypress:run:dev:nansen": "cypress run --env version='development' --spec 'cypress/e2e/nansen/*'",
    "cypress:run:dev:portfolio": "cypress run --env version='development' --spec 'cypress/e2e/portfolio/*'"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@this-dot/cypress-indexeddb": "^1.1.1",
    "@typescript-eslint/eslint-plugin": "^5.31.0",
    "@typescript-eslint/parser": "^5.31.0",
    "cypress": "^10.3.1",
    "cypress-mochawesome-reporter": "^3.1.0",
    "eslint": "^8.20.0",
    "eslint-plugin-cypress": "^2.12.1",
    "gmail-tester": "^1.3.5",
    "typescript": "^4.7.4"
  }
}
```

**Comment by mike-plummer** [comment]
@GeorgeXCV The issue here is how Windows and Mac command prompts treat quotation marks. If you look at your script entries from `package.json` you'll notice you're defining the value of "version" wrapped with single quotes - these are treated as "grouping" quotes on Mac (`development`) but as text content on Windows (`'development'`). I've verified that an e2e project with the config you've supplied loads successfully on Mac and Windows by making that adjustment.

`"cypress:run:dev": "cypress run --env version=development",`

**Comment by GeorgeXCV** [comment]
> @GeorgeXCV The issue here is how Windows and Mac command prompts treat quotation marks. If you look at your script entries from `package.json` you'll notice you're defining the value of "version" wrapped with single quotes - these are treated as "grouping" quotes on Mac (`development`) but as text content on Windows (`'development'`). I've verified that an e2e project with the config you've supplied loads successfully on Mac and Windows by making that adjustment.
> 
> `"cypress:run:dev": "cypress run --env version=development",`

Wow, great find! Yes, can confirm with that change the project now works on both operating systems. Thanks!
