### ISSUE TITLE
Cannot record by crypess 10.3.0

### ISSUE THREAD

**Issue by AngelaWanChina2021** [cypress-io/cypress#23012]
### Current behavior

I cannot find the tool to record script by cypress 10+, if anyone how to record in cypress 10? Thanks for any of your info

### Desired behavior

I cannot find the tool to record script by cypress 10+, if anyone how to record in cypress 10? Thanks for any of your info

### Test code to reproduce

I cannot find the tool to record script by cypress 10+, if anyone how to record in cypress 10? Thanks for any of your info

### Cypress Version

10.3.0

**Comment by Narretz** [comment]
What do you mean by "record script"? D you mean record screen (https://docs.cypress.io/guides/guides/screenshots-and-videos)?

**Comment by marktnoonan** [comment]
I believe this is in reference to Cypress Studio, which was technically an experimental feature and was removed in Cypress 10. If so @AngelaWanChina2021 you can see the discussion about it here and share your thoughts: https://github.com/cypress-io/cypress/discussions/21561

**Comment by AngelaWanChina2021** [comment]
> What do you mean by "record script"? D you mean record screen (https://docs.cypress.io/guides/guides/screenshots-and-videos)?

In previous version ,  we can add cypress commands  by recording just like the following picture
![image](https://user-images.githubusercontent.com/90311803/182148344-c061039e-7c17-4d57-8fc0-bb48be2fee42.png)

**Comment by marktnoonan** [comment]
@AngelaWanChina2021 thanks, that's definitely a Studio feature, please do add your voice or a thumbs up to https://github.com/cypress-io/cypress/discussions/21561

Going to close this for now.
