### ISSUE TITLE
Show "Connect project" CTA after login if projectId is unset

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#23022]
After being redirected from the login flow, if there is no projectId in the config, show a "Connect project" button instead of a "Continue" button that takes you to the connect project modal. In global mode where there is no active project, show "Continue" regardless.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23022?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
I have a few edge cases and questions to consider. Users can log in from the App or Launchpad - would this also apply when logging in from the Launchpad? Either way we might need to shuffle some code around to get this modal to be available in all the situations where a login can currently be triggered.

It also feels a bit abrupt from a UX standpoint as described here. A user would click Continue and then we'd say "whoops, no you can't continue", do this other thing.

![Screen Shot 2022-08-02 at 12.17.07 PM.png](https://images.zenhubusercontent.com/5bdc960898196e0c7295b593/86fcde3b-b435-44f5-b0b8-31505e46d8d9)

So it seems more like a modification we should make to this state 👆, not something where we close one modal and open the other. Like maybe a second button beside "Continue" to "connect project" or a little warning that the project is not connected.

It's also something we should remember for the user if they decide to not connect the project, it would be annoying to have a 'double-popup' like this every time you log in. Though it's not terribly useful to be logged in if the current project is not connected to the dashboard, in global mode it could be valid. Eg moving between projects that are connected and projects that are not.

**Comment by pstakoun** [comment]
@marktnoonan good call. maybe we should change the deliverable here to be: After being redirected from the login flow, if there is no projectId in the config, show a "Connect project" button instead of a "Continue" button that takes you to the connect project modal.

**Comment by marktnoonan** [comment]
@pstakoun that might be a bit smoother. And then if users don't want to, they can click away or use the X to close the modal. I would also suggest a little bit of copy explaining why connecting the project is a good idea.

**Comment by pstakoun** [comment]
@marktnoonan actually, I have another thought on this. What if we had the logic as follows:
```
If has projectId (project is connected)
    show "Continue" button
else if user is a member of exactly 1 organization and that organization has 0 projects
    automatically create project with default name (the name of the directory) and connect that project (write to config)
    show "Continue" button
else
    show "Connect project" button
```

**Comment by marktnoonan** [comment]
@pstakoun I don't have a strong opinion on the logic really, it just needs to be defined in a way that lets us estimate the work to implement this ticket and add the appropriate tests.

**Comment by pstakoun** [comment]
Will loop back shortly and update the issue once I validate this

**Comment by pstakoun** [comment]
Updates with the logic from one of my previous comments. We will go with this: "After being redirected from the login flow, if there is no projectId in the config, show a "Connect project" button instead of a "Continue" button that takes you to the connect project modal."

**Comment by marktnoonan** [comment]
@pstakoun can you confirm does this change in the login flow only apply when logging in via the browser app? Or would it also make it possible in the Launchpad, where the same login flow currently exists but the "connect a project" workflow doesn't? Inherently it seems like it might as well be the same in all places where a project exists and a user logs in, but it is probably a bit of a bigger lift to extend the launchpad at the moment.

**Comment by pstakoun** [comment]
Ah, I see what you mean @marktnoonan. Doing this in Launchpad at all would require bringing that 'connect project' modal into Launchpad, and it's not accessible in there now, is that pretty much accurate?

**Comment by marktnoonan** [comment]
Right @pstakoun, we'd move it into the `frontend-shared` package and import it both places, and likely get some new e2e coverage of the launchpad version. Possibly wrangle gql a bit to get data we didn't previously need in the launchpad. Not massive but not as simple as replacing one button with another at a certain part of the flow.

If we skip the launchpad, it's a simpler bit of conditional logic to show a "Connect project" only if the consumer of the Login Modal allows it AND the other conditions are met. Then maybe we do the move to launchpad in another ticket if desired.

**Comment by pstakoun** [comment]
I am tempted to ask for the former approach, since we do have a large percentage of logins that come in through Launchpad (though not as many as via browser). The decision criteria to me here is whether or not we can get the former (full solution) in for the release. If not, let's split it in two. If so, let's go for the full thing. @marktnoonan
