### ISSUE TITLE
CSS import in component is not respected

### ISSUE THREAD

**Issue by davidNHK** [cypress-io/cypress#23025]
### Current behavior

Styled has been ignored

<img width="1680" alt="Screen Shot 2022-07-30 at 13 23 01" src="https://user-images.githubusercontent.com/2247500/181914246-d4c3026e-487f-4dea-bcb0-4e4ee6a2ed33.png">

### Desired behavior

Same code in storybook

<img width="1680" alt="Screen Shot 2022-07-30 at 13 23 40" src="https://user-images.githubusercontent.com/2247500/181914256-a4a3d658-5b1a-450a-b626-d1b674f33a2a.png">

### Test code to reproduce

[Reproduce repo](https://github.com/davidNHK/cypress-reproduce)

### Cypress Version

10.3.1

### Other

Integrate with WebPack 5 and tailwindCSS

**Comment by davidNHK** [comment]
In case people get similar issue , below can fix it with trick

(Workaround)[https://github.com/davidNHK/cypress-reproduce/blob/abd647b18485d8171b6842093decb037c160b435/cypress/support/component.tsx#L37]

Use dynamic import to import CSS will make it work.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23025?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by amehta265** [comment]
@davidNHK I am trying to understand why `"./cypress/support/*.ts"` was added to the sideEffects in the package.json?

Looks like this is what is causing the issue. According to the Webpack documentation any file that is not added to sideEffects will be subject to tree shaking and will be dropped in production mode. Hence, adding `*.css` to the sideEffects in your package.json should also solve this problem as recommended here: [https://webpack.js.org/guides/tree-shaking/](url)

If you can provide more context around why you decided to include the Cypress support file in the sideEffects of your package.json that would be very helpful. Thanks

**Comment by neviaumi** [comment]
That because I am using Cypress on my components library and want to enable WP tree sharking for my component 

But for the reproduce repo , it no point to that ? Probably should be remove

**Comment by lmiller1990** [comment]
I think the reproduction repo is useful, definitely keep that. I'd agree that you should be able to simply do `import '../../style.css' (or whatever)` in `component.ts` without any additional work arounds.
