### ISSUE TITLE
A json file is not loaded when cypress is accessing the test endpoint

### ISSUE THREAD

**Issue by peppi-scaleforce** [cypress-io/cypress#23027]
### Current behavior

We are running an angular app that access a json file (referred in a javascript file). However running via cypress UI test this file is not loaded.

Cypress test:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/26489507/182041299-16d30418-84f6-4c47-af10-41bf74daa034.png">

Normal load:
<img width="1400" alt="182041396-00a5207f-4697-41f9-9da5-3dde69609920" src="https://user-images.githubusercontent.com/26489507/182419163-4129eecd-553a-4ba5-a601-b1f821a31fcd.png">

the file: https://dev-del-desk.excitel.in/assets/translations/en.json is loaded

Seems like the proxy is not handling well the json loaded from javascript. Also if the same angulat is deployed on localhost the test works.

### Desired behavior

Cypress should load the website as it is loading in normal browser. 

### Test code to reproduce

https://github.com/scaleforce/cypress_issue

### Cypress Version

10.3.1

**Comment by AtofStryker** [comment]
Hi @peppi-scaleforce. Thank you for opening an issue. From what I can see, it doesn't look like the request is even being made by the browser when the app is running with cypress, but works when I visit `dev-del-desk.excitel.in`. Is there any logic relating to how to send the request from the app, such as security policies or the application running in an iframe?

**Comment by peppi-scaleforce** [comment]
Thank you, Bill. 
This app can work in a iframe, please check the html below. Regarding security policy, there is none that I am aware of. Our research shows that the cypress proxy loads all the files on the server (login.css, logos..etc) except that one file **en.json** and it is not even sending a request to fetch it.

`<iframe src="https://dev-del-desk.excitel.in" style="border:0px #ffffff none;" name="myiFrame" scrolling="no" frameborder="1" marginheight="0px" marginwidth="0px" height="400px" width="600px" allowfullscreen></iframe>`

**Comment by AtofStryker** [comment]
I was able to inspect the request when making it from a standalone browser. There doesn't look to be anything restrictive about the request. However, when I run it with Cypress, it doesn't look like the browser is even making the request, so it isn't event reaching the proxy. Do you have access to the code which is making that request?

**Comment by peppi-scaleforce** [comment]
It's our production code, so I am not sure we can change it easily for test purposes. Do you have a suggestion in mind?

**Comment by AtofStryker** [comment]
Are you able to test against a development version with sourcemaps enabled and possibly debug from the line of code that has made the original request? You could try this with production but it might be difficult to parse.

**Comment by peppi-scaleforce** [comment]
I was able to execute the code on local machine against local cypress instance. On localhost the test is working, the missing file gets downloaded in the browser.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/26489507/183830110-30108a3f-776f-4580-994a-017c92a801a4.png">

**Comment by AtofStryker** [comment]
@peppi-scaleforce interesting. Are you able to see the requestor in the network panel and trace it back to the source code? I wonder what would be different between that vs a production build. That should give us some really good clues.

**Comment by peppi-scaleforce** [comment]
@AtofStryker I've found the following e.prototype.getResourcesFromJson=function(){var e=this;return this.http.get(this.resourceUrl+this.currentLanguage+".json").

Is it possible that the currentLanguage is empty in cypress? How can I set it to "en"?

**Comment by AtofStryker** [comment]
> @AtofStryker I've found the following: e.prototype.getResourcesFromJson=function(){var e=this;return this.http.get(this.resourceUrl+this.currentLanguage+".json").
> 
> Is it possible that the currentLanguage is empty in cypress? How can I set it to "en"?

I think it depends what `this` is in this case, but I don't believe it points to cypress. You might be able to see that with the debugger (maybe the window?). I would think in this case we would see a failed request to `undefined.json` if it wasn't defined. My guess would be `getResourcesFromJson` isn't being called?

**Comment by peppi-scaleforce** [comment]
Hi @AtofStryker, we have redeployed the code to an alternative environment http://procare-tests.excitel.tech/ where the offending json file loads correctly and the cypress works fine against it. We still haven't found what is the exact issue in the code but it is clearly not within cypress. One of the differences is that new environment uses nginx while the old is running apache.
Thank you for the kind support!

**Comment by AtofStryker** [comment]
@peppi-scaleforce of course! I wish you the best of luck figuring out what is causing that json file to not load.
