### ISSUE TITLE
Point yarn dev to production by default

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#23020]
In order to allow developers to work with accurate data in yarn dev, we want to point Cypress to the production environment of the Dashboard by default.

Right now when you hit login in the app (or launchpad) it defaults to https://dashboard-staging.cypress.io/organizations/new which is **staging**. Let's point everything at **production**, which is https://dashboard.cypress.io. by default so we can use the dashboard and ACI features more actively. 

One other thing we do is you can launch Cypress with `CYPRESS_INTERNAL_ENV` or `CYPRESS_INTERNAL_CLOUD_ENV` with either `staging` or `production`. This might help you find places in the code we have diverging behavior.

AC:

- when logging in, default to production
- should show latest production runs when logging in
  - You can see those [here](https://dashboard.cypress.io/projects/ypt4pf/runs?branches=%5B%7B%22label%22%3A%22develop%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22develop%22%7D%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D)
  - this is controlled by `projectId` in `cypress.config.js`

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23020?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Runs page is fine, why don't these guys show up?

![image](https://user-images.githubusercontent.com/19196536/187191231-17b9f091-501d-444a-89be-3d78f475bf6c.png)
