### ISSUE TITLE
Svelte Component Testing Support

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#23037]
### What would you like?

Add support for Svelte in Component Testing

#### Things to consider
1. Common setups around svelte. The `Getting Started` guide uses `Vite`
1. Documentation Updates
1. Tests

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23037?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by ZachJW34** [comment]
We have an [open source contribution](https://github.com/cypress-io/cypress/pull/22862) for the mount side of things. Depending on when we want to get this out, we can create another issue for [SvelteKit](https://kit.svelte.dev/) and focus the svelte + vite/webpack support

**Comment by baus** [comment]
Assume this does not include SvelteKit support

**Comment by slavco86** [comment]
Please, please, please - can we have official support for Svelte?
I've been trying to get Svelte Vite Cypress combination to work for days now and at the end of my tether with not much luck.
Been trying to follow this article, but the thing just doesn't want to work 
https://www.thisdot.co/blog/svelte-component-testing-with-cypress-vite

**Comment by lmiller1990** [comment]
@slavco86 we sure can, it's getting worked on https://github.com/cypress-io/cypress/pull/22862.

Are you using SvelteKit? I think Svelte + webpack combo will likely land before the full SvelteKit/Vite integration does.

**Comment by slavco86** [comment]
No, just vanilla Svelte +Vite.
I think I finally got it to work 😂

**Comment by lmiller1990** [comment]
Cool, maybe you can share your config for everyone else to see :100:

**Comment by slavco86** [comment]
The problem is that my config is tightly locked into Node 14 and Cypress 8.5
Updating any of these - inevitably breaks the setup.
Which specific config you want me to share?

**Comment by lmiller1990** [comment]
Right, I didn't realise you were on 8.5.

Definitely recommend upgrading first! When we release our Svelte support, it'll be with Cypress 10 (latest version) in mind.

**Comment by baus** [comment]
We will consider this implementation to be experimental
