### ISSUE TITLE
Spike: Nuxt 3 Component Testing Support

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#23036]
### What would you like?

Nuxt is working on version 3 and has recently released RC 6. We should look into the effort it will take to support this version.

#### Things to consider
1. Nuxt 3 will support both [vite and webpack](https://nuxtjs.org/announcements/nuxt3-rc#vite--webpack)
2. `tsconfig.ts` will live in [.nuxt/tsconfig](https://nuxtjs.org/announcements/nuxt3-rc#vue-3--typescript)

**Comment by ZachJW34** [comment]
Tech-brief of Nuxt 3 Support: https://github.com/cypress-io/tech-briefs/pull/42

**Comment by kingtimm** [comment]
@ZachJW34 hey is the tech-brief public? Couldn’t access the link but guessing it’s an internal repo
