### ISSUE TITLE
[Cypress 10] Fail to compile in CI - Cannot find module 'cypress'

### ISSUE THREAD

**Issue by aichichang** [cypress-io/cypress#23041]
### Current behavior

When upgrading to Cypress 10, Cypress is installed in the dev dependencies. 

- The upgrade first caused an [eslint error](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-extraneous-dependencies.md), not sure if this was expected... adding the rule to `.eslintrc` fixed the issue.
<img width='600' src='https://user-images.githubusercontent.com/72026367/182190304-fb46af4c-272f-4e29-b36a-2783e193079e.png' />

- When running in CI, our build is trying to import cypress from `cypress.config.ts` but since dev-dependencies are not installed during `production` build, it caused the build to fail in BuildKite
![image](https://user-images.githubusercontent.com/72026367/182197083-0bf85c28-6acd-4119-a6e0-9b747ccbecec.png)

The workaround we have now is to remove `ENV NODE_ENV=production` in Dockerfile and that seems to solve the issue, but I'm not sure if it is the best solution as now cypress is included in the production node_module file and it has increased our docker image size too...

The below screenshot is from [dive](https://github.com/wagoodman/dive), it allows you to inspect image layer content
![image](https://user-images.githubusercontent.com/72026367/182198331-4082b2b1-5e88-4d58-8d71-ea901fd122e1.png)

#### Dockerfile
```bash
FROM node:lts-alpine AS deps
WORKDIR /opt/app
ENV CI=true
# comment out production node env
# ENV NODE_ENV=production
COPY package.json yarn.lock ./
RUN yarn config set no-progress && yarn --frozen-lockfile

FROM node:lts-alpine AS builder
WORKDIR /opt/app
COPY . .
COPY --from=deps /opt/app/node_modules ./node_modules
ENV NODE_ENV=production
RUN yarn build

FROM node:lts-alpine AS runner
WORKDIR /opt/app
ENV NODE_ENV=production
COPY --from=builder /opt/app/next.config.js ./
COPY --from=builder /opt/app/public ./public
COPY --from=builder /opt/app/.next ./.next
COPY --from=deps /opt/app/node_modules ./node_modules
CMD ["node_modules/.bin/next", "start"]
```
#### cypress.config.ts
```typescript
import { defineConfig } from 'cypress';

export default defineConfig({
  projectId: ******,
  pageLoadTimeout: 80000,
  chromeWebSecurity: false,
  defaultCommandTimeout: 30000,
  requestTimeout: 30000,
  responseTimeout: 30000,
  viewportWidth: 1280,
  viewportHeight: 800,
  retries: {
    runMode: 2,
    openMode: 0
  },
  scrollBehavior: 'center',
  e2e: {
    setupNodeEvents(on, config) {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      require('cypress-fail-fast/plugin')(on, config);
      return config;
    },
    baseUrl: 'http://localhost:3000',
    specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}'
  }
});
```

### Cypress Version

10.3.1

### Package Manager

yarn

### Operating system

Mac

**Comment by AtofStryker** [comment]
Hi @aichichang . Thank you for opening an issue. Would you be able to share out your `package.json`? It looks like from the `dive` screenshot you shared, the `@cypress` scoped packages are installed, which we use internally for shared dependencies, but didn't see `cypress` from the screenshot. Can you verify that `cypress` is there?

**Comment by aichichang** [comment]
Hello @AtofStryker, thanks for looking into this, below is the package.json file

```bash
{
  "name": *****,
  "version": "1.3.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "start:cypress": "NODE_ENV='production' next start",
    "start:cypress:dev": "NODE_ENV='development' env-cmd -f .env.cypress.local next start",
    "test": "jest",
    "cy:open": "NODE_ENV='production' cypress open",
    "cy:open:dev": "NODE_ENV='development' cypress open",
    "cy:run": "cypress run",
    "cy:run:dev": "NODE_ENV='development' cypress run"
  },
  "dependencies": {
    "@babel/core": "^7.18.9",
    "@babel/eslint-parser": "^7.18.9",
    "@babel/preset-env": "^7.18.9",
    "@babel/preset-typescript": "^7.18.6",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "12.1.4",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/user-event": "13.5.0",
    "@types/babel__core": "^7.1.19",
    "@types/jest": "^27.5.1",
    "@types/jest-axe": "^3.5.3",
    "@types/node": "^18.6.2",
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "@types/testing-library__jest-dom": "^5.14.3",
    "@typescript-eslint/eslint-plugin": "^5.24.0",
    "@typescript-eslint/parser": "^5.24.0",
    "axios": "^0.27.2",
    "dotenv": "^16.0.1",
    "env-cmd": "^10.1.0",
    "eslint": "^8.20.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jest": "^26.1.5",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.5.0",
    "graphql": "^16.5.0",
    "graphql-tag": "^2.12.6",
    "jest": "^27.5.1",
    "jest-axe": "^6.0.0",
    "jest-canvas-mock": "^2.4.0",
    "jest-environment-jsdom": "^27.5.1",
    "jest-extended": "^2.0.0",
    "jest-mock": "^27.5.1",
    "mobx": "^6.6.1",
    "mobx-devtools-mst": "^0.9.30",
    "mobx-react-lite": "^3.4.0",
    "mobx-state-tree": "^5.1.5",
    "next": "^12.1.6",
    "next-compose-plugins": "^2.2.1",
    "next-cookies": "^2.0.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sass": "^1.54.0",
    "ts-jest": "^27.1.4",
    "ts-node": "^10.9.1",
    "typescript": "^4.6.4",
  },
  "devDependencies": {
    "@cypress/skip-test": "^2.6.1",
    "@percy/cli": "^1.6.4",
    "@percy/cypress": "^3.1.2",
    "cypress": "^10.3.1",
    "cypress-fail-fast": "^5.0.0",
    "jsonwebtoken": "^8.5.1"
  }
}
```

**Comment by aichichang** [comment]
Just checked dive and can see cypress is included in the node_module when `ENV NODE_ENV=production` is commented out from the Dockerfile
![image](https://user-images.githubusercontent.com/72026367/182817537-a0c44018-1393-4ba4-b2a1-6efdcbf53876.png)

This is from the same project without commenting out `ENV NODE_ENV=production` in the Dockerfile, and cypress is not installed
![image](https://user-images.githubusercontent.com/72026367/182817994-1d82addf-38df-4797-acab-f8318889aafc.png)

**Comment by AtofStryker** [comment]
@aichichang this is starting to make more sense. It almost looks like the tsconfig for your `next.js` project is type checking the `cypress.config.ts`. What does your `tsconfig.json` look like? Have you included the cypress [types](https://docs.cypress.io/guides/tooling/typescript-support#Using-an-External-Typings-File)? 

To possibly speed up cause identification, are you able to include a reproduction repo?

**Comment by aichichang** [comment]
Hey @AtofStryker, thank you for the advice! The problem is indeed from the Next.js tsconfig.json file.
Adding `cypress.config.ts` in `tsconfig.json - excludes` and `.eslintignore` fixed the issue.
Happy to close the issue, thanks again :)
