### ISSUE TITLE
CT + Vite 3.0 does not work with Node >= 17

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#23042]
### Current behavior

A Cypress CT project using the new Vite 3.0 support does not work out of the box if the user is using a node version >=17. There is a workaround by explicitly setting the `host` to `127.0.0.1` in the `vite.config.js` (or the overrides in `cypress.config.js`), but we should not have to rely on user workarounds.

For details, see the [vite migration guide](https://vitejs.dev/guide/migration.html#dev-server-changes) regarding dev-server changes.

### Desired behavior

Cypress CT projects using Vite 3.0.0 and Node version >=17 should work without user provided workarounds.

### Test code to reproduce

1. `nvm install 18`
2. `npx init vite` => I chose a react js app
3. cd into project and run `yarn add -D https://cdn.cypress.io/beta/npm/10.4.0/darwin-x64/develop-4d3ad9edaa9b4b19ed10094279f72ed5657b851c/cypress.tgz` (Vite 3.0 hasn't been released yet so I'm using a binary from develop)
4. `yarn cypress open` => walk through CT setup
5. Create a CT test => I created `src/App.cy.jsx` with contents:
```
import App from "./App";

it("should render", () => {
  cy.mount(<App />);
});

```
7. Click on CT test, runner will hang

https://user-images.githubusercontent.com/25158820/182201979-30c9ddf2-8cc1-4785-ad7c-8f68e61c1591.mov

### Cypress Version

10.4.0 (binary from develop)

### Other

We did the same change for webpack a while back, so it's makes sense to do it here as well.
https://github.com/cypress-io/cypress/pull/21430

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23042?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by OrenciucEvghenii** [comment]
Hey guys. Same issue hier.
vite: v3.0.4
cypress: v10.3.1
node: v18.6.0
