### ISSUE TITLE
Migration to Cypress 10 fails when converting cypress.json with the error "SyntaxError: Unexpected token ="

### ISSUE THREAD

**Issue by kodriscollics** [cypress-io/cypress#23043]
### Current behavior

I had Cypress 9.7.0 installed. 
I ran npm install -D cypress@latest which installed Cypress 10.3.1 with the following output:

> C:\dev\myProject>npm install -D cypress@latest
> 
> changed 1 package, and audited 1018 packages in 2m
> 
> 60 packages are looking for funding
>   run `npm fund` for details
> 
> 13 vulnerabilities (9 moderate, 3 high, 1 critical)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> Some issues need review, and may require choosing
> a different dependency.
> 
> Run `npm audit` for details.

I then ran npx cypress open to launch the new Cypress and the migration wizard.  This was the output:

> C:\dev\myProject>npx cypress open
> 
> It looks like this is your first time using Cypress: 10.3.1
> 
> 
> √  Verified Cypress! C:\Users\kodriscoll\AppData\Local\Cypress\Cache\10.3.1\Cypress
> 
> Opening Cypress...

The migration wizard appeared and prompted me to migrate my cypress.json file. When I clicked on the "Migrate for me" button, I got the following output and the "cy" spinner is still running after 20 minutes:

> [4008:0801/102904.039:ERROR:display_layout.cc(559)] PlacementList must be sorted by first 8 bits of display_id
> [4008:0801/102904.230:ERROR:display_layout.cc(559)] PlacementList must be sorted by first 8 bits of display_id
> [4008:0801/102915.751:ERROR:display_layout.cc(559)] PlacementList must be sorted by first 8 bits of display_id
> [4008:0801/103126.107:ERROR:display_layout.cc(559)] PlacementList must be sorted by first 8 bits of display_id
> [4008:0801/103338.724:ERROR:display_layout.cc(559)] PlacementList must be sorted by first 8 bits of display_id
> [4008:0801/103556.597:ERROR:display_layout.cc(559)] PlacementList must be sorted by first 8 bits of display_id
> C:\Users\kodriscoll\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:40
>   invoke = (eventId, args = []) => {
>               ^
> 
> SyntaxError: Unexpected token =
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (C:\Users\kodriscoll\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:6:24)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (C:\Users\kodriscoll\AppData\Local\Cypress\Cache\10.3.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\require_async_child.js:12:13)
> [4008:0801/103904.361:ERROR:display_layout.cc(559)] PlacementList must be sorted by first 8 bits of display_id

### Desired behavior

For the migration to finish successfully.

### Test code to reproduce

This is an upgrade using the Cypress migration wizard. Not really any test code to show.

### Cypress Version

10.3.1

**Comment by rockindahizzy** [comment]
Hey @kodriscollics, thanks for reporting the issue! Are you able to provide the `cypress.json` that is causing the error? I tried migrating with a couple different `cypress.json` files, but wasn't able to recreate this.

**Comment by kodriscollics** [comment]
@rockindahizzy ... sorry, should have done that originally. This is the contents of the cypress.json file:

{
  "integrationFolder": "C:/dev/myProject/cypress/tests",
  "projectId": "My Project UI Automation Testing",
  "baseUrl": "https://test.myOrg.org",
  "chromeWebSecurity": false,
  "viewportWidth": 1600,
  "viewportHeight": 1200,
  "watchForFileChanges": false,
  "screenshotOnRunFailure": true,
  "videoCompression": 32,
  "video": false,
  "nodeVersion": "bundled",
  "retries": {
    "runMode": 0,
    "openMode": 0
  },
  "codeCoverage": {
  },
  "env": {
    "User1": {
      "password": "password",
      "username": "username",
      "fullName": "fullname",
      "compoundName": "username (username)"
    },
    "apiEndPoint": {
      "apiEndPointUrl": "https://test.myOrg.org/apiEndpoint",
      "apiEndPointUsername": "apiUsername",
      "apiEndPointCred": "boguscreddoweiujwe8sojsdlfkjweoijsdfkjowiefslkdjfssdfsdfjl=",
      "apiEndPointAuth": "Basic boguscreddoweiujwe8sojsdlfkjweoijsdfkjowiefslkdjfssdfsdfjl="
    },
    "TestData": {
      "SearchOpt": "building",
      "searchString": "2919854",
      "Location": "United States"
    }
  }
}

**Comment by kodriscollics** [comment]
@rockindahizzy I reduced my cypress.json file to the following, and still have the same failure. Something else is causing the problem. Haven't isolated what it is yet, but I'll keep trying different configurations.

{
  "projectId": "My Project UI Automation Testing",
  "baseUrl": "https://test.myOrg.org"
}

**Comment by rockindahizzy** [comment]
@kodriscollics, thanks for the updates! Unfortunately, I haven't had a chance to try to reproduce with your json. Just in case it is helpful when I get to this, what version of `node` and `npm` are you using?

**Comment by kodriscollics** [comment]
node --version
v16.6.1

npm --version
7.20.3

**Comment by rockindahizzy** [comment]
@kodriscollics, thanks again for all the info so far! Unfortunately, I was not able to reproduce the error with either of those cypress.json files.

I have a few more questions
- What OS are you running the migration in?
- Are the `before` and `after` json files in the migration wizard valid json
  <img width="1135" alt="image" src="https://user-images.githubusercontent.com/25568640/183090024-2f187556-f18b-424e-b234-065a4d0c6659.png">
- Have you tried clearing `node_modules` in case there is something cached
- Are you able to share the project that this is occuring in? Or possibly try to recreate this in another public github repo?

**Comment by kodriscollics** [comment]
@rockindahizzy... running Windows 10 Ent., the before and after are the same, I have cleared the node_modues folder. I'll do more troubleshooting and try to create a project in which I can dupe it that is shareable. I'm unable to share current project code as it contains private corporate data.

**Comment by kodriscollics** [comment]
@rockindahizzy I found the cause for the install issue. My package.json file had a dependencies section that looks like this:

  "dependencies": {
    "dayjs": "^1.10.7",
    "mocha": "^9.1.3",
    "node": "^10.24.1"
  }

When I removed the  "node": "^10.24.1" line from the file, upgrade worked properly.
