### ISSUE TITLE
Support Firefox Developer Edition

### ISSUE THREAD

**Issue by macmladen** [cypress-io/cypress#23044]
### What would you like?

Firefox Developer Edition is not listed on E2E browser list

### Why is this needed?

Many developers use that version and it is practically the same, just it is not identified as Firefox.

### Other

Probably it is easy to add support for Developer Edition as well as ESRs.

**Comment by mirobo** [comment]
This would be great. Maybe the this code will be refactored somehow: https://github.com/cypress-io/cypress/blob/develop/packages/launcher/lib/windows/index.ts#L49
Shouldn't be this hard to read and understand.. basically it's just a list of paths which are prioritized..

I have installed Firefox 91 here: C:\Program Files\Mozilla Firefox
And a newer version here (which doesn't get detected): C:\Users\username\AppData\Local\Mozilla Firefox

**Comment by tbiethman** [comment]
@macmladen hmm, we do assume support for Firefox Developer Edition: https://github.com/cypress-io/cypress/blob/develop/packages/types/src/browser.ts#L117-L127

Though it's possible the lookup is failing in your environment? You can run cypress with debug logs enabled to see where Cypress is looking and what it finds more granularly: `DEBUG='cypress:launcher*,cypress-verbose:launcher*' cypress open`

@mirobo I imagine Cypress is detecting your first installation and running with it, as Cypress doesn't currently detect multiple versions of the same browser type by default. But you could add one version as a [custom browser](https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers) within your config. And if Mozilla has changed their default installation dirs, it might make sense to reprioritize the lookup paths?

**Comment by macmladen** [comment]
I am a new user in the learning process so I figured out better to ask than leave it.

I was just going through Lessons and was wondering _why would I need another instance eating up memory_ and then it came very clear to me by looking at the link on **custom browser** you provided so I understood that really **the best** option is to use **Electron** as it _eats_ memory the least.

Also, a separate environment is a much better idea than sharing my own account, history and such.

And yes, Cypress can recognise four basic browsers (chrome, chromium, firefox, edge) and once any is found, the second version is not automatically added but **can** be added manually (as I have both Firefox and Firefox Developer Edition).

However, I'd suggest you offer all of the found browsers so the user will not be confused about why some installed are missing and may prefer a specific version for some reason.

Multi-browser parallel testing would also be very welcome. 🙂

**Comment by jennifer-shehane** [comment]
Closing as resolved.
