### ISSUE TITLE
Different screenshot paths with npm and docker 

### ISSUE THREAD

**Issue by KuFain** [cypress-io/cypress#23060]
### Current behavior

Currently if tests are run with docker container the 
screenshot path includes folder.
Test actual path:
e2e/project/test spec.ts
Docker screenshot generated to:
e2e/project/test.spec.ts/...png
While with npm screenshot path:
e2e/test.spec.ts/...png

### Desired behavior

All paths should be the same in npm and docker.

### Test code to reproduce

-

### Cypress Version

10.3.1

**Comment by rockindahizzy** [comment]
Hey @KuFain thanks for opening this issue! Could you possibly provide a reproducible example in GitHub with a `dockerfile` that recreates this scenario? It would be extremely helpful!

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
