### ISSUE TITLE
iframe content not being visible in AUT

### ISSUE THREAD

**Issue by Muhammadhassanyamin** [cypress-io/cypress#23063]
### Current behavior

After upgrading cypress to the latest version. We are seeing iframe content not being visible in the application preview while running the tests.

It is working as expected in cypress version 9.5.1 (from which i upgraded from) And can even see the content of iframe while  tests are running.

### Desired behavior

- Preview element should be visible while running the tests.
- DOM should be interact-able and achieve the asserted results.

### Test code to reproduce

```
Cypress.Commands.add('verifyAggrNotiSales', (title, subTitle) => {

cy.get("iframe", { timeout: 30000 })
  .should((iframe) => expect(iframe.contents().find("body")))
  .then((iframe) => cy.wrap(iframe.contents().find("body")))
  .within({}, ($iframe) => {
  
cy.get('[id="abc-notification-box"]')
.find('[class="acb-image-box"]')
.should('be.visible');

cy.get('[id="abc-notification-box"]')
 .find('[class="abc-title"]')
  .contains(title)
  .should('be.visible');
  
cy.get('[id="abc-notification-box"]')
  .find('[class="abc-system-box"]')
   .find('.abc-system-timestamp-text')
   .contains(subTitle)
    .should('be.visible');
```

The same code for version 9.5.1 runs as expected.
For version 10.3.1, it yields this error.
**AssertionError**
Timed out retrying after 15000ms: Expected to find element: [id="abc-notification-box"], but never found it.

### Cypress Version

10.3.1

**Comment by AtofStryker** [comment]
Hey @Muhammadhassanyamin. Thank you for opening an issue. Would you be able to put together a quick reproducible example in a github repo?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
