### ISSUE TITLE
Jenkins CI using Headless Chrome

### ISSUE THREAD

**Issue by nobleach** [cypress-io/cypress#2307]
### Current behavior:

Since the included Electron browser just crashes when I try to use it in a Docker container (using the Cypress provided images from Dockerhub) I decided to try `--browser chrome`. That yields the following

```
Warning: Cypress can only record videos when using the built in 'electron' browser.

You have set the browser to: 'chrome'

A video will not be recorded when using this browser.

  It should load the page
The automation client disconnected. Cannot continue running tests.
```
Unfortunately, no further information is provided. I understand there are issues with Docker, and I've added the required params to allow more memory to my build. I'm not allowed to share IPC with the host however.

### Desired behavior:

I'd really like to be able to run my acceptance suite during a Jenkins build. When running the Electron browser, it crashes, runs another spec and allows the build to pass (a separate issue)

### Steps to reproduce:

Set shared memory size to 1 gigabyte. Use provided Docker image. Call `cypress install` then `cypress run --browser chrome`

### Versions

Cypress 3.0.2, Jenkins 2, Chrome 67 headless

**Comment by bahmutov** [comment]
Why does the Electron browser crash? We run 10k of tests using Docker images across CIs using Electron without problems - is it due to the memory limit?

- Non-electron browsers right now do no support video recording, but at least should not crash. Again, what happens when you run with higher memory limit? Browsers are memory-hungry, there is nothing Cypress can do to minimize that unfortunately.

**Comment by nobleach** [comment]
I'm doing a run with 2 gigabytes right now. We'll see if that helps. As far as why the electron runs crash, I have no idea. My output is:
```
 Running: load.spec.js...                                             (1 of 2) 


  It should load the page
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

  (Results)

  ┌────────────────────────────┐
  │ Tests:        0            │
  │ Passing:      0            │
  │ Failing:      1            │
  │ Pending:      0            │
  │ Skipped:      0            │
  │ Screenshots:  0            │
  │ Video:        true         │
  │ Duration:     0 seconds    │
  │ Spec Ran:     load.spec.js │
  └────────────────────────────┘


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /opt/jenkins/workspace/pipe_trix_master-OQ45GGQLUTTFPI3KYO2ZZBFCD7Z6XI26CFZ53VBMUVYIUUWMF6YA/cypress/videos/load.spec.js.mp4 (2 seconds)
```
`cypress run` runs just fine from my laptop... but admittedly, it has 16 gigs of memory.

**Comment by bahmutov** [comment]
The load test is trying to load your site, right?
Can I ask you to grab https://github.com/bahmutov/tiny-blog there is a Dockerfile and try running that in Docker? It installs Cypress and runs e2e tests. It runs fine on several platforms, including locally on Mac where my Docker is limited to 2GB of memory too

<img width="501" alt="screen shot 2018-08-08 at 10 28 06 am" src="https://user-images.githubusercontent.com/2212006/43843657-0f852ba6-9af6-11e8-9bcc-9700b03dfd23.png">

also, what's the Docker versions you are using?

**Comment by nobleach** [comment]
I can run everything just fine from a Docker image on my laptop. It's only when it's being run _inside_ Jenkins where the problem occurs. I'll give this a shot, but it's not quite indicative of the other pieces of this puzzle.

**Comment by bahmutov** [comment]
So then the problem seems in old / different Docker environment on Jenkins?

**Comment by nobleach** [comment]
Quite possibly, yeah. Jenkins itself is running in a Docker container, and I'm using the Cypress provided Docker image (with Chrome 67 and node 8.11) as a builder container. I build my app as its own container and then run it. Once it's running, I want to run my acceptance suite against it. It does appear that giving it 2 gigabytes for headless Chrome at least got to the first spec without crashing. It appears to have hung though. I'm now trying 2 gigabytes with the Electron browser. Perhaps that'll be enough.

**Comment by nobleach** [comment]
Since this appears to be more of an available memory issue, I'm going to close this. I appreciate your help.
