### ISSUE TITLE
Screenshot not capturing hover style

### ISSUE THREAD

**Issue by warri93** [cypress-io/cypress#23085]
### Current behavior

I am hovering a button for which I want to take a screenshot. 
In the generated video I can clearly see that the button is being hovered and the correct styling is applied. However when taking a screenshot after hovering, the styling gets lost.

### Desired behavior

Hover style applied when taking a screenshot

### Test code to reproduce

cy.get('button').realHover().screenshot('my-screenshot'); // not working
cy.get('button').realHover().matchImageSnapshot('my-screenshot'); // not working

### Cypress Version

9.5.0

### Other

Tried using cy.realHover and matchImageSnapshot from cypress-image-snapshot but both didn't work.

**Comment by AtofStryker** [comment]
Hi @warri93. Thank you for opening an issue. Would you be able to provide a reproducible example in a github repo so I can further investigate the issue?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
