### ISSUE TITLE
The React18 support in Component Testing doesn't work

### ISSUE THREAD

**Issue by joshwooding** [cypress-io/cypress#23081]
### Current behavior

Currently when running a CT using the new entry "cypress/react18" I get the following error:

![image](https://user-images.githubusercontent.com/12938082/182606863-86f99fed-21b6-4233-80b0-96de5c577ed9.png)

Which is thrown from https://github.com/cypress-io/cypress/blob/c058bf287861f36371ee2c589dd1e08213e5dfa9/npm/react/src/createMount.ts#L172 because the lastMountedReactDom is react-dom/client which only exports createRoot and hydrateRoot (https://github.com/facebook/react/blob/9fcaf88d58cfd942e2fdd303ae8291dbf4828969/packages/react-dom/client.js#L25)

### Test code to reproduce

~I can't provide a reproduction at the moment but will provide one soon. Using the react18 entry in a CT suite should cause it immediately.~
https://github.com/joshwooding/cypress-react18-repro

### Cypress Version

10.4.0

**Comment by joshwooding** [comment]
Just an update you need two tests in the spec to encounter the error.

**Comment by rockindahizzy** [comment]
> Just an update you need two tests in the spec to encounter the error. I've added the reproduction above @rockindahizzy.

Thanks for the reproduction, @joshwooding!

**Comment by lmiller1990** [comment]
Uh oh, I guess we forgot pass through the React 18 specific unmount: https://github.com/cypress-io/cypress/blob/c058bf287861f36371ee2c589dd1e08213e5dfa9/npm/react18/src/index.ts#L31-L41

The main test suite (which is huge) only runs against `cypress/react` right now, the smaller one for React 18 is not doing two `mount` in a single test: https://github.com/cypress-io/cypress/tree/develop/system-tests/project-fixtures/react/src

Big oversight, let's fix this and ship a patch in the next release.

**Comment by dartess** [comment]
Hey, for some reason I couldn't find this issue through a github search. It was only by chance that I was able to find it with my eyes. Maybe this comment will help the following seekers:

```
TypeError: lastMountedReactDom.unmountComponentAtNode is not a function
```

**Comment by lmiller1990** [comment]
PR is here to fix it: https://github.com/cypress-io/cypress/pull/23204/files
