### ISSUE TITLE
Persist alert banner state

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#23082]
# What is Needed

When the user is shown and/or dismisses certain banners (e.g. those shown to inform them of app/cloud features they may not be using) we want to persist the fact for later reference. Some banners may need to be tracked globally (per machine) while others should be tracked per machine per project

* Timestamp of the last time a user was shown a banner
* Whether user has manually dismissed a banner

# Why is it Needed

As we add more feature/information-level banners to the app we do not want to bombard users with the same content over and over. To do this we want the ability to track the last time a user was shown a banner so we can delay showing it again by "n" hours/days. We also want the ability to know whether the user dismissed the banner so we can not show it to them again in the future.

# Other

This should be able to integrate with the existing preferences framework, but we will need to consider how to ensure this doesn't grow unbounded as banners are added/removed going forward. Is there a way to clean up banner preferences for banners that we don't have anymore? Once a banner is dismissed we should clear the "last shown" preference for that banner since it won't be needed anymore.

**Comment by warrensplayer** [comment]
@mike-plummer What is your opinion on the state of this issue?  I know you implemented dismissal tracking for the smart notification issues (PR https://github.com/cypress-io/cypress/pull/23256).  What additional functionality (if any) do you think is missing at this point?

**Comment by warrensplayer** [comment]
@mike-plummer  Thanks for the update.  I am going to close this as a separate issue and address these concerns within ( #23083 )
