### ISSUE TITLE
"sync skip abort execution" cypress error is thrown while using tags in cypress cucumber execution 

### ISSUE THREAD

**Issue by gogoid88** [cypress-io/cypress#23086]
### Current behavior

while running command 
npx cypress-tags -e "TAGS=@rerun"

Cypress throws error "sync skip abort execution" on encountering a scenario in a feature file with no tag or not the specified tag.

The execeution goes into a loop without terminating.

cypress package version 9.5.3

cypress binary version 6.0.1

 

### Desired behavior

Cypress should skip the scenarios without the tag and execute those with the specified tag.

 

### Test code to reproduce

No code is needed. cypress execution engine issue with cypress-tags processor

### Cypress Version

9.5.3

### Other

Will be provided in comments if any.

**Comment by rockindahizzy** [comment]
Hey @gogoid88, 

There doesn't seem to be enough info to reproduce this issue. Can you create a small reproducible example of this issue using your specific dependencies? The latest version of `cypress-tags` seems to be setup for cypress `v10+`.

Feel free to use this template [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny).

**Comment by gogoid88** [comment]
@rockindahizzy , 

Thanks for your enquiry! :)
I am using cypress package version 9.5.2 
binary version 6.0.1
I have tagged some of my scenarios in the feature files with "@rerun" tag
I have below  command  in package.json
"Rerun" : "npx cypress-tags -e 'TAGS=@rerun' --headless"
I run it in cmd prompt using npm run Rerun
It throws the error "sync skip ; aborting execution" for scenarios with no @rerun tag 
but it gets stuck there and does not proceed to scenarios with the @rerun tag
Please let me know if any other info needed 

Thanks! :)

**Comment by rockindahizzy** [comment]
Hey @gogoid88 thanks for the additional information. 

Unfortunately I am still not able to reproduce this with the information provided. Specifically with regards to  the version of `cypress-tags` you are using. 

It would be extremely helpful if you could provide a small public Github repo that showcases this issue using the library versions that match your project. If possible, sharing your actual project would be fine as well.

**Comment by gogoid88** [comment]
@rockindahizzy,
 
The issue seems to be config-related not code related. The repo is private and protected so won't be able to share it.

Running - > "npx cypress-tags run -e 'TAGS=@rerun' --headless" command with configuration below works fine.
Cypress package version: 9.5.1
Cypress binary version: 9.5.1
Electron version: 15.3.4
Bundled Node version:
16.5.0

But running the same command with the below configuration gives the error "sync skip - aborting execution" 
Most probably an issue with the binary version of 6.0.1. Can you please check this? I narrowed it down.

Cypress package version: 9.5.3
Cypress binary version: 6.0.1
Electron version: 11.0.2
Bundled Node version:
12.18.6

**Comment by rockindahizzy** [comment]
This seems to be related to [`cypress-tags`](https://github.com/annaet/cypress-tags) and not `cypress`.  Have you tried opening an issue there?

**Comment by gogoid88** [comment]
@rockindahizzy/ @nagash77   where can this be raised?
