### ISSUE TITLE
Disable creating video on passing tests

### ISSUE THREAD

**Issue by stclairdaniel** [cypress-io/cypress#2308]
### Desired behavior:

Currently, running tests headless produces a video file for every test file. However, 99.9% of the time the only video file I am interested in viewing is one in which a test fails. It would be nice to have an option like `createVideoOnPassingTest` that I could set to false to avoid the time it takes to create and compress the video that will never be watched.

**Comment by jennifer-shehane** [comment]
Relevant conversation regarding videos only on failing tests. Let me know if this resolves what you wanted: https://github.com/cypress-io/cypress/issues/2217#issuecomment-410386771

**Comment by stclairdaniel** [comment]
@jennifer-shehane That's exactly what I was looking for! I'm so sorry - I thought I searched well, but I guess I didn't. Thanks for the link :)

**Comment by jennifer-shehane** [comment]
Don't worry - this has happened a few times, the docs need improving https://github.com/cypress-io/cypress-documentation/issues/815

**Comment by mattvb91** [comment]
@jennifer-shehane if I understand the documentation correctly this only applies to videos for the dashboard. Is it possible to add the same functionality to only add videos to the output folder on fails?

**Comment by jennifer-shehane** [comment]
@mattvb91 Yes, this only applies to videos when recording through the Dashboard. Could you open an new issue for this functionality when not recording to the Dashboard?
