### ISSUE TITLE
[ACI] Banner analytics

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#23084]
# What is Needed

A capability to communicate to the dashboard that a particular smart notification has been shown to the user and if the user completes the call to action (CTA) for that notification.  With the introduction of A/B testing for this notifications ( #23118 ), the cohort ID that represents the copy shown should also be communicated.  

The Cloud API is introducing a new endpoint to capture the "viewed" event for each of the four smart banner notifications.  For tracking the CTA completion, two methods will be used.  For the Login banner and the Create Organization banner, the UTM parameters currently being passed in the URL will be updated to include cohort information.  For the Create Project banner, new fields in theGraphQL mutation will be introduced to pass this information. 

## Deliverables
* Ability to call new Cloud API endpoint when a banner notification is shown for the first time to a user (see Cloud issue and PR below)
* Update URLS used from the banners for login (i.e. authentication) to the dashboard as well as opening the "Create Organization" page to pass new UTM parameters See [spreadsheet](https://docs.google.com/spreadsheets/d/1Cs933TLXcS63PmMlXA4wKLJtQSFH90dProvzI9oyEB4/edit#gid=0) lines 17-18
* Update GraphQL mutation for creating a project to accept new parameters defined in the cloud for tracking 

# Why is it Needed

Product desires a way to know how many times a given banner was displayed and how many times actions from a given banner were taken. By knowing how many times each cohort was shown vs acted on a banner Product can measure effectiveness of different versions of copy.

# Other

* Cloud Issue: https://cypress-io.atlassian.net/browse/CLOUD-772
* Cloud PR: https://github.com/cypress-io/cypress-services/pull/4709

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23084?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by astone123** [comment]
Branch in progress: https://github.com/cypress-io/cypress/commits/astone123/banner-analytics
