### ISSUE TITLE
[ACI] Cohort assignment and persistence to support A/B testing capability for Smart Notifications

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#23083]
# What is Needed

Capability to assign a user to selected "cohort" for a given "feature".  This cohort can be used by the app to vary the experience for the given users within a "feature".  The cohort functionality will encapsulate the logic for selecting a cohort for the user and persisting it in global state by "feature" so that once a cohort is selected, the user has a consistent experience each time it uses that "feature".  

See [tech brief](https://github.com/cypress-io/tech-briefs/tree/main/briefs/a-b-testing-app) for suggested implementation details.  Main goal for this issue would be to introduce reusable functionality for user cohorts that is not dependent on any part of the banner framework itself.

## Deliverable

* Reusable code that encapsulates the cohort functionality (proposed solution in tech brief calls for Vue composable)
  * See **Goals** section of [tech brief](https://github.com/cypress-io/tech-briefs/pull/45) for important implementation details

# Why is it Needed

Product desires a way to evaluate how different versions of copy might affect uptake/action on certain alert banners. To do this they want the ability to display different versions of copy and measure the rate at which users act on those versions. They can use this insight to improve phrasing in the future to ensure we're using language that resonates with our users.

See: #23118 

# Other

Should be able to persist the cohorts selected using the existing preferences framework. The "measure" aspect is covered by a separate analytics issue. Need to consider long-term cleanup - can we remove cohort information for banners we don't have anymore?

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23083?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
