### ISSUE TITLE
Teardown Angular Components Before Each Test

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/cypress#23096]
### Current behavior

Currently the previous component that was mounted is only torn down once the next `mount` function is called. This is problematic as it leaks state from the previous test into the next.

By default angular tears down tests after each test is run. The problem with this behavior is that we want the component to remain mounted so you can see the component, and interact with it after the test has run. Therefore we use the following flag when we call `initTestEnvironment()`

```ts
teardown: { destroyAfterEach: false }
```

However, this causes the state leak described above

### Desired behavior

We need a way to manually call `teardownTestingModule` & `resetTestingModule` on `TestBed` before every tests runs. We should be able to call `setupHooks()` from `@cypress/mount-utils` to achieve this behavior

### Test code to reproduce

if you add this to a spec file you will see each screenshot shows the previous tests component on the DOM

```ts
beforeEach(() => {
  cy.snapshot()
})
```

### Cypress Version

10.5

**Comment by mschile** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/23117, but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
