### ISSUE TITLE
Add support for custom reporters

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#231]
Add support for any mocha reporter, whether installed via npm or available locally in a user's project. Also, add support for the [mocha junit reporter](https://www.npmjs.com/package/mocha-junit-reporter) by default.

As has been the case until now, specifying a reporter only works in headless mode.

This partially addresses #203.

**Comment by brian-mann** [comment]
Fixed in [`0.17.5`](https://github.com/cypress-io/cypress/wiki/Changelog#0175-10022016).
