### ISSUE TITLE
Tests fail randomly due to partial input text into the form

### ISSUE THREAD

**Issue by devang-s** [cypress-io/cypress#23109]
### Current behavior

I am running the tests from here: https://github.com/devang-s/Cypress-VanGogh/blob/main/cypress/e2e/vanGogh.cy.js

For the third test, it is supposed to search for `Het Gele Huis` and then perform validations. However, sometimes, randomly only part of this text is entered and the search result is different from the one expected. This causes the test to fail. This only happens randomly, so try running it a few times back-to-back. 

As seen here, the "after" part shows the input text box as empty even though text was entered. Sometimes, it just enters "He" or "Het"

![NLGogh](https://user-images.githubusercontent.com/11354754/182847055-a09c7711-d534-4f27-bcaf-572893b91906.png)
![NLGogh2](https://user-images.githubusercontent.com/11354754/182848612-9fe0bc71-5cfa-497d-8a07-48b6608470c8.png)

### Desired behavior

The entire text should be input and searched.

### Test code to reproduce

https://github.com/devang-s/Cypress-VanGogh/blob/main/cypress/e2e/vanGogh.cy.js

Run the tests from this repo.

### Cypress Version

10.3.1

**Comment by AtofStryker** [comment]
Hi @devang-s. Thank you for opening an issue. I was able to fork your repository and recreate the issue. It almost looks like the search box is losing focus. I was only able to put in an `H` and then the textbox lost focus. I was using Electron. Does this happen in any other browser?

**Comment by AtofStryker** [comment]
is it possible something in your application is pulling focus from the searchbox?

**Comment by devang-s** [comment]
It happens with Chrome too. If you look at the second test , it does the exact same thing - searching for the same text. Somehow, just randomly, it does not work for the third one.

**Comment by AtofStryker** [comment]
> It happens with Chrome too. If you look at the second test , it does the exact same thing - searching for the same text. Somehow, just randomly, it does not work for the third one.

It sounds like something in the application is pulling focus away from the text input, regardless of browser. Is there something in your application code that may be pulling element focus away from the typing? You can probably verify this by setting `force: true` in [cy.type](https://docs.cypress.io/api/commands/type#Syntax)

**Comment by devang-s** [comment]
> > It happens with Chrome too. If you look at the second test , it does the exact same thing - searching for the same text. Somehow, just randomly, it does not work for the third one.
> 
> It sounds like something in the application is pulling focus away from the text input, regardless of browser. Is there something in your application code that may be pulling element focus away from the typing? You can probably verify this by setting `force: true` in [cy.type](https://docs.cypress.io/api/commands/type#Syntax)

Nope, if you look at the code of the second and the third test, both are doing the exact same thing of searching the same text in the first four-five lines of the code. This happens only in the third test only and that too randomly.

**Comment by devang-s** [comment]
I will try the force setting and see if it works and update here.

**Comment by devang-s** [comment]
I've tried with , `{force: true}` and it works okay with it.

**Comment by AtofStryker** [comment]
It does sound like something is likely pulling focus from the element in your application code. When I ran the test suite, I saw it intermittently creep up between tests. I can try it again and see if I yield different results.

**Comment by AtofStryker** [comment]
I'm seeing this on the second test as well. I'm fairly convinced this is the application pulling focus and not an issue with Cypress.
![](https://user-images.githubusercontent.com/3980464/183754550-d206ea61-3403-453e-ad63-fd69aa895339.png)

**Comment by AtofStryker** [comment]
meant to show the `after` screenshot but the result is the same

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by dpresiana** [comment]
We have the same issue and it seems like it does not wait until all triggered keyboard events are done before proceeding to the next method, which changes the focus to another element. It is working fine with `{ force: true }` but I believe there should be a better way to do that.
Can you please investigate this issue
