### ISSUE TITLE
Previous runs with server not started crashes proper runs with server running 1 minute later

### ISSUE THREAD

**Issue by emilgoldsmith** [cypress-io/cypress#23108]
### Current behavior

The error message is "Timed out after waiting 60000ms for your remote page to load." and I can continuously reproduce it by:

1. Try running my tests without my server started
2. Start my server some seconds later
3. Press restart on my tests
4. Wait about a minute (you need tests that last that long) and you'll see your tests crash at whatever point they're at with the error message "Timed out after waiting 60000ms for your remote page to load"

### Test code to reproduce

See above

### Cypress Version

10.4.0

**Comment by rockindahizzy** [comment]
Hey @emilgoldsmith, thanks for opening an issue! Would you be able to put together a reproducible example on a GitHub repo?

**Comment by emilgoldsmith** [comment]
Phew, that was a tough one to isolate. So many small parts interacting to create this bug, I can definitely understand it hasn't been caught by your tests haha.

The repo is here: https://github.com/emilgoldsmith/cypress-issue-23108 and reproduction steps are in the README.

To sum up the bug is an interaction between:
1. Running my code in a container that exposes a port even when the server isn't up
2. An intercept on the request
3. Overwriting the cy.visit command (but without changing any functionality)

Hopefully the fix is as easy as cancelling waits for requests when you restart tests and you won't have to go into specifics about all the entangled stuff in those cases though

**Comment by rockindahizzy** [comment]
Hey @emilgoldsmith, thanks for the recreation. Everything happened as you described. However, after rerunning another time, everything passes. So if you don't mind, can you give a little more explanation on the issue here?

**Comment by emilgoldsmith** [comment]
@rockindahizzy sure. So what you're saying is that you're recreating the unexpected failure of the tests, but that you don't see a problem because you can just rerun it again and then it passes, therefore not completely breaking Cypress, is that correct?

Assuming that's the case, then you're completely right. This is definitely an issue that is possible to overcome, and it's probably not the most pressing issue on Cypress' priority list, the fact that an unexpected failure occurs with a wrong and misleading error message is to me still problematic though. The first time it happened to me I genuinely thought that some of my tests were failing, and it confused me quite a lot. It also happens to me regularly as I frequently forget to start my server before opening Cypress, so while it's a quite specific edge case it seems, when this edge case arises it happens quite frequently.

Now that I understand the issue, yes I can just rerun and I can still use Cypress, but I still consider it a bug in the app.

Does that answer your question?

**Comment by emilgoldsmith** [comment]
@rockindahizzy, hi! I think we may be miscommunicating?

I would prefer there was no error, as right now a perfectly fine run that should succeed, gets stopped with an error because a previous run failed due to the server not being started at that previous time. It's a breach of what I imagine should be the sandbox between each different independent test run, and it's very confusing.

If one was capable of customizing the error message in this case I can't see why one couldn't just stop the error from happening at all and letting the test run continue uninhibited without any bugs in the software?

**Comment by mike-plummer** [comment]
Hi @emilgoldsmith . I took a quick look at your example (thanks so much for the extremely detailed reproduction case!) and I think this may be a frustratingly-simple issue: a missing `return`. If I add a return statement to the invocation of `originalFn` in your `visit` overwrite everything seems to work as expected. Can you confirm this resolves the issue for you as well?

```
Cypress.Commands.overwrite("visit", function (originalFn, ...args) {
  // make sure to add a return here!
  return originalFn(...args);
});
```

**Comment by emilgoldsmith** [comment]
@mike-plummer wow what a classic "semicolon" type of bug haha. Thanks so much for finding that, it did indeed fix my issue. I guess that the code internally awaits the result of the Cypress "Promise", and when it doesn't get it to await on then this kind of stuff can happen?

I'm ready to close the issue as this is fixable with better code though it's obviously very opaque that a return statement is needed here. My only thought for an improvement could be that the part that waits on this promise could error if visit was overwritten and doesn't return a Cypress value? 

It's a very small edge case though so completely understand if we don't want to explore that, but if you pointed me in the right direction in the codebase I could try to take a look, otherwise I'm just happy for this to be fixed.

Cheers,
Emil

**Comment by mike-plummer** [comment]
@emilgoldsmith I feel your pain, especially after you put so much work into the awesome reproduction case for us! In this case I think you ran smack into a "feature" - it isn't always the case (but _usually_ is) where a command needs to return a command chain to preserve the subject. There are some situations where a command can be used to kick off some async logic that doesn't need to hold up your cypress test, contionally-executed content, or a command designed to be "terminal" and not further-chainable. To support those situations the type definitions allow a `void` return. We added some hint language to the [Overwrite Command code examples on our website](https://docs.cypress.io/api/cypress-api/custom-commands#Overwrite-Existing-Commands) but obviously that isn't quite noticeable enough - I'll ping our DX group to see whether we need to add some extra language to that area to help other folks avoid this pothole

**Comment by emilgoldsmith** [comment]
Very fair, sounds good to me @mike-plummer, thanks again for diagnosing the issue, and in programming the solution to a problem is not always the type you’d like, so completely understandable if no big changes occur from this, especially as it seems like the return only breaks it if you’re also running in a dev container and intercepting the request
