### ISSUE TITLE
Tooltips can cover the "New Spec" button

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#23115]
### Current behavior

Currently there's a mildly annoying situation where users intending to click "New Spec" on the Spec Lists have to be mindful of avoiding the Column heading beneath it with their pointer so that the tooltip doesn't cover the button.

https://user-images.githubusercontent.com/8340719/182914074-d622ff37-aaf8-4235-b567-d28e57293884.mov

### Desired behavior

A small delay before tooltips open would avoid this. I'd suggest we increase the `show` delay above 0 in the main `Tooltip` Vue component so that simply passing over and element doesn't unintentionally trigger tooltips. A very unscientific test just now suggests 150 ms is a good starting point, and this is a good signal generally that the pointer has come to rest on an element, so it avoids a lot of scenarios where currently moving the mouse around can open many tooltips at once.

### Test code to reproduce

N/A

### Cypress Version

10.4.0

**Comment by pstakoun** [comment]
Good idea, I'd be ok with a small delay (100-150ms seems reasonable)

**Comment by ryanjwilke** [comment]
Agreed. A delay would be great. Even something up to 200-300ms may be appropriate. I trust you judgement though. Whatever you think feels right really.
