### ISSUE TITLE
[ACI] Implement analytics in Smart Notification banners

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#23119]
Once analytics capability is implemented for banner actions (#23084 ) we should implement the following additions to the Smart Notification banners:

**Generic update to `TrackedBanner.vue`**
- Ability to track when a banner notification is shown to a user for the very first time

**[Login Banner](https://github.com/cypress-io/cypress/issues/22933)**
- When it is viewed for the first time, call the new Cloud API endpoint defined in ( #23084 )

| Field | Value |
| ----- | ----- |
| medium | `Specs Login Banner`   |
| campaign | `Log In`  |
| cohort |  `A` or `B`  | 
| messageId | {uuid} | 

**Note** The `messageId` field will use a UUID as a nonce to allow the endpoint to filter out repeated requests if they should happen.  See notes in ClickUp task [here](https://app.clickup.com/t/18033298/PM-2477).

- When the CTA is clicked, pass the appropriate UTM parameters to the login URL

| UTM Params | Value |
| ----- | ----- |
| utm_medium | `Specs Login Banner`   |
| utm_campaign | `Log In`  |
| utm_content |  `A` or `B`  | 

**[Create Organization Banner](https://github.com/cypress-io/cypress/issues/22934)**
- When it is viewed for the first time, call the new Cloud API endpoint defined in ( #23084 )

| Field | Value |
| ----- | ----- |
| medium | `Specs Create Organization Banner`   |
| campaign | `Set up your organization`  |
| cohort |  `A` or `B`  | 
| messageId | {uuid} | 

**Note** The `messageId` field will use a UUID as a nonce to allow the endpoint to filter out repeated requests if they should happen.  See notes in ClickUp task [here](https://app.clickup.com/t/18033298/PM-2477).

- When the CTA is clicked, pass the appropriate UTM parameters to the Create Organization URL

| UTM Params | Value |
| ----- | ----- |
| utm_medium | `Specs Create Organization Banner`   |
| utm_campaign | `Set up your organization`  |
| utm_content |  `A` or `B`  | 

**[Connect Project Banner](https://github.com/cypress-io/cypress/issues/22798)**
- When it is viewed for the first time, call the new Cloud API endpoint defined in ( #23084 )

| Field | Value |
| ----- | ----- |
| medium | `Specs Create Project Banner`   |
| campaign | `Create project`  |
| cohort |  `A` or `B`  | 
| messageId | {uuid} | 

**Note** The `messageId` field will use a UUID as a nonce to allow the endpoint to filter out repeated requests if they should happen.  See notes in ClickUp task [here](https://app.clickup.com/t/18033298/PM-2477).

- When the CTA is clicked, pass the appropriate new fields in the GraphQL mutation. 

| Field | Value |
| ----- | ----- |
| source |  `Binary: App`  |
| medium | `Specs Create Project Banner`   |
| campaign | `Create project`  |
| cohort |  `A` or `B`  | 

**[Record Banner](https://github.com/cypress-io/cypress/issues/22935)**
- When it is viewed for the first time, call the new Cloud API endpoint defined in ( #23084 )

| Field | Value |
| ----- | ----- |
| medium | `Specs Record Runs Banner`   |
| campaign | `Record Runs`  |
| cohort |  `A` or `B`  | 
| messageId | {uuid} | 

**Note** The `messageId` field will use a UUID as a nonce to allow the endpoint to filter out repeated requests if they should happen.  See notes in ClickUp task [here](https://app.clickup.com/t/18033298/PM-2477).

- When the CTA is clicked, do not track at this time

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23119?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
> Note The messageId field will use a UUID as a nonce

Where do I get this uuid?

**Comment by warrensplayer** [comment]
@lmiller1990 
> > Note The messageId field will use a UUID as a nonce
> 
> Where do I get this uuid?

The requirements just ask for a UUID to be sent in this field which ultimately gets sent to Segment with the event information to be used in Segment to prevent duplicates.  I am not sure it is really needed, but do not know all the details of how Segment is configured and used.
