### ISSUE TITLE
[ACI] Implement A/B testing versions of copy in Smart Notification banners

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#23118]
# Update smart notification banners to use A/B versions of copy

Issue ( #23083 ) introduces an ability to generate cohorts for users to be used in different use cases within the app.  Use the new cohort feature to select a cohort per banner to use to control which version of copy as shown [here](https://docs.google.com/document/d/1PFN79d3deDyqDVFmVIBe4cVMzWiEll0J6XCpesBZrSg/edit)

See [tech brief](https://github.com/cypress-io/tech-briefs/pull/45)

Smart Notification banners 
| Banner | Section that changes |
| ------- | --------------------- |
| [Login](https://github.com/cypress-io/cypress/issues/22933) | body |
| [Create Organization](https://github.com/cypress-io/cypress/issues/22934) |  header |
| [Connect Project](https://github.com/cypress-io/cypress/issues/22798) |  body |
| [Record](https://github.com/cypress-io/cypress/issues/22935) | action |

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23118?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
To test these UTM params we'll need an e2e test that validates the utm params passed to the auth mutations. This could be done as part of this issue but could be its own ticket.
