### ISSUE TITLE
unable to add functions to `this` (Context)

### ISSUE THREAD

**Issue by iomedico-beyer** [cypress-io/cypress#23110]
### Current behavior

Adding functions to `this` (which is a Mocha `Context`) yields an error.

### Desired behavior

I want to add functions to have them on `this` in tests, so I can do e.g.
```
describe('my spec', () => {
  it('should work', function () {
    this.sayHelloWorld();
  })
})
```

### Test code to reproduce

In an empty folder I call
```
yarn add cypress
yarn cypress open
```
so that default config files are created. It also creates a sample test in `cypress/e2e/spec.cy.js`.

I can run the sample test without problem. But if I add
```
import { Context } from "mocha";
```
to `cypress/support/e2e.js` I get
```
Error: Webpack Compilation Error
./cypress/support/e2e.js
Module not found: Error: Can't resolve 'mocha' in '...\support'
resolve 'mocha' in '...\support'
  Parsed request is a module
```
So I installed Mocha, the same version which is in devDependencies of Cypress (see [package.json][1]):
```
yarn add mocha@3.5.3
```
My `package.json` now looks like this:
```
{
  "dependencies": {
    "cypress": "^10.4.0",
    "mocha": "3.5.3"
  }
}
```
Now that `import` line passes. But this fails:
```
import { Context } from "mocha";

Context.prototype.sayHelloWorld = () => console.log("hello world");
```
Error:
```
> Cannot read properties of undefined (reading 'prototype')
```
Why is that? In comparison adding something to `String.prototype` works.

And it also works in Mocha without Cypress. In **another** empty folder:
```
yarn add mocha@3.5.3
```
And in `test/test.js`:
```
const { Context } = require("mocha");
it("works", function () {
  Context.prototype.sayHelloWorld = () => console.log("hello world");
  this.sayHelloWorld();
});
```
Now `yarn mocha` works (says hello world).

Why does this work in Mocha but not in Cypress?

  [1]: https://github.com/cypress-io/cypress/blob/develop/package.json#L188

### Cypress Version

10.4.0

**Comment by rockindahizzy** [comment]
Hey @iomedico-beyer, I am interested to hear a little more detail about the specific use case you are trying to accomplish with this.

**Comment by iomedico-beyer** [comment]
> Hey @iomedico-beyer, I am interested to hear a little more detail about the specific use case you are trying to accomplish with this.

I am currently designing a high level API for our testing team. So far they are only used to manual tests and have no programming background. So I try to introduce as few tech concepts as possible, such as `import` statements in this case. In combination with module augmentation (typescript) and code completion (IDE) they would find all reasonable starting points on `this`, like ` this.visitStartPage()`, etc. with the corresponding IDE shortcut after the dot.

**Comment by rockindahizzy** [comment]
Hey @iomedico-beyer, thanks for the additional info!

I made a small repo showcasing how you might accomplish this pattern [here](https://github.com/rockindahizzy/global-func). The specific changes I made can be seen in [this commit](https://github.com/rockindahizzy/global-func/commit/e78fb3bdbf62aa1feebccfa351f0a1351e3fc747)

**Comment by rockindahizzy** [comment]
Rereading through your initial comments and wanted to clarify one thing. You shouldn't have to explicitly import `Context` from Mocha. By using `function` vs `() => {}` you'll have access to `this` which is a (modified) mocha context.

**Comment by iomedico-beyer** [comment]
Hi @rockindahizzy. `function` was not the problem. I was using that all along (see code above). But simply adding my stuff to `this` in `before` did the trick.  Thank you very much! Looks like I still have a lot to learn about JavaScript and TypeScript ...

**Comment by iomedico-beyer** [comment]
If you don’t mind: I have one last question. Why is `this` a `Context` within `() => {}` in Mocha but not in Cypress?

**Comment by iomedico-beyer** [comment]
> But simply adding my stuff to `this` in `before` did the trick. Thank you very much! 💚 Looks like I still have a lot to learn about JavaScript and TypeScript ...

I found another solution:

```
MochaContext.prototype.sayHelloWorld = function () {
    cy.log('hello world');
};
```
