### ISSUE TITLE
Make installing development NPM package by commit simpler

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2312]
We can install and test development versions of `cypress` using TGZ npm package and custom binary path, but it is a huge hustle.

```
CYPRESS_BINARY_PATH=https://cdn.cypress.io/beta/binary/3.1.0/mac64/buildkite-develop-4ead424d4c9e3d65422c71597496539290720057-32310/cypress.zip npm i https://cdn.cypress.io/beta/npm/3.1.0/circle-develop-4ead424d4c9e3d65422c71597496539290720057-32306/cypress.tgz
```

It would be so much simpler if we could install NPM package and binary by using just a single TGZ url with commit SHA or at least branch name plus SHA

Something like: `npm i -D https://on.cypress.io/beta/develop/4ead424d4c9e3d65422c71597496539290720057` where `develop` is branch name followed by SHA

The redirect service redirect to `cypress.tgz` stored on `cdn.cypress.io/beta/npm/...` then our NPM package would be smart to look at the original installation URL before looking at `CYPRESS_BINARY` etc

I did an experiment and NPM gives the original installation URL / path as an environment variable to the post install script, see https://github.com/bahmutov/test-npm-install-from-tgz. Thus the NPM package could determine its branch and SHA by inspecting `npm_config_argv` object, then download the right binary (we have to update `on.cypress.io` to make this more convenient)

This will make testing development version of test runner so so simple

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/issues/4525
