### ISSUE TITLE
Flaky test: must call #initializeConfig before accessing config

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23149]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/41402/workflows/68bc48c2-74e7-4588-97c3-fbc1b0bde495/jobs/1714672

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/server/test/integration/cypress_spec.js#L1661

### Analysis

<img width="886" alt="Screen Shot 2022-08-05 at 12 22 06 PM" src="https://user-images.githubusercontent.com/26726429/183146676-4d212cc9-9ccb-41a3-af71-3a8e0125ee85.png">

### Cypress Version

10.4.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by rachelruderman** [comment]
Added `.skip` to this test in https://github.com/cypress-io/cypress/pull/23167. Please remove `.skip` when test is stable

**Comment by flotwig** [comment]
Looked at this as part of #25671 - it seems to fail consistently locally now.
