### ISSUE TITLE
Flaky test: AssertionError: expected 'POST /runs/00748421-e035-4a3d-8604-8468cc48bdb5/instances' to equal 'POST /instances/e9e81b5e-cc58-4026-b2ff-8ae3161435a6/results'

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23151]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/41370/workflows/b5842bda-87dd-488c-ac98-4855e959a900/jobs/1713324

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/system-tests/test/record_spec.js#L395

### Analysis

<img width="1300" alt="Screen Shot 2022-08-05 at 12 26 27 PM" src="https://user-images.githubusercontent.com/26726429/183147285-63d8f397-13f7-4701-a14d-c501824c7493.png">

### Cypress Version

10.4.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by rachelruderman** [comment]
Added `.skip` to this test in https://github.com/cypress-io/cypress/pull/23167. Please remove `.skip` when test is stable

**Comment by flotwig** [comment]
Looked at this as part of #25671 - it works fine for me locally, but in CI it fails every time.
