### ISSUE TITLE
Flaky test: expected exit code 3 but got 1: expected 1 to equal 3

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23152]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/41370/workflows/b5842bda-87dd-488c-ac98-4855e959a900/jobs/1713324

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/system-tests/test/record_spec.js#L346

### Analysis

<img width="696" alt="Screen Shot 2022-08-05 at 12 27 20 PM" src="https://user-images.githubusercontent.com/26726429/183147389-c3748432-218f-4eae-b214-64f6c0307ceb.png">

### Cypress Version

10.4.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by rachelruderman** [comment]
Added `.skip` to this test in https://github.com/cypress-io/cypress/pull/23167. Please remove `.skip` when test is stable

**Comment by flotwig** [comment]
Looked at this as part of #25671 - it's mildly flaky for me locally, but it fails every time in CI.
