### ISSUE TITLE
Component Testing for Next.js Express apps

### ISSUE THREAD

**Issue by corysimmons** [cypress-io/cypress#23183]
### What would you like?

I'd like to be able to do component testing using this example: https://github.com/vercel/next.js/tree/canary/examples/custom-server-express

### Why is this needed?

I'm trying to add component tests to a large codebase that is serving Next.js via Express.

### Other

I don't care if these are slow or I have to open multiple tabs (one `yarn dev`, one `yarn cypress-component-tests`). I just want to be able to write tests.

**Comment by corysimmons** [comment]
The custom devServer docs are too vague to do anything with: https://docs.cypress.io/guides/component-testing/component-framework-configuration#Custom-Dev-Server

I saw this comment and the highlighted code, but couldn't make sense of it either: https://github.com/cypress-io/cypress/discussions/16977#discussioncomment-1203937

**Comment by rockindahizzy** [comment]
Hey @corysimmons thanks for reporting this issue.

Out of curiosity, could you provide some more info about what is preventing you from using the default `next.js` server? 

Could you also provide a little more detail in regards to the errors you are experiencing?

**Comment by corysimmons** [comment]
Hi @rockindahizzy,

Honestly, I would happily just use Next.js API Routes for everything, but this is a project from before API Routes were in Next.js so there are a ton of API routes still in an Express app.

The problem I'm facing is I need to be able to run headless tests by launching the Express app (that serves the Next app) via localhost:5000.

Currently, I can get it to work by opening a terminal tab, running `yarn dev` (which gets localhost:5000 running), then opening another tab and `yarn run cypress open` (at which point I can click on Component Testing and see my Next.js component tests).

In fact, we can probably just close this and I can open something up that is more specific later on. I'm sorry for wasting your time.
