### ISSUE TITLE
"not.have.class" passes for objects that do not exist

### ISSUE THREAD

**Issue by kamituel** [cypress-io/cypress#2318]
### Current behavior:

The following snippet passes:

```javascript
cy.get('.element-with-that-class-surely-doesnt-exist-in-the-dom')
  .should('not.have.class', 'waiting')
```

There's even an indication in the command log that that element does not exist, by the way:

<img width="633" alt="screen shot 2018-08-10 at 15 04 23" src="https://user-images.githubusercontent.com/642339/43959363-d805aff6-9cae-11e8-9ea3-066adb29c0a0.png">

### Desired behavior:

`.should('not.have.class, '...')` fails because element doesn't exist.

### Steps to reproduce:

Paste code above into any test and run it.

### Versions

Cypress 2.1.0.

**Comment by PKSpeleo** [comment]
Version 3.1.0 - same problem!

**Comment by brian-mann** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/205
