### ISSUE TITLE
Non-covered framebusting condition

### ISSUE THREAD

**Issue by ExLeonem** [cypress-io/cypress#23195]
### Current behavior

Similar to the already closed Issue [886](https://github.com/cypress-io/cypress/issues/886) I stumbled upon an Issue with a 3rd party website that is using old school framebusting. 

However the condition this specific website uses seems to not be covered by cypress. When running a test which redirects to this website, the entire test runner disappears leaving only the website, similar to Issue [3517](https://github.com/cypress-io/cypress/issues/3517)

Instead of

```javascript

if (top != self) {
  // Frame busting
}

```

This specific website uses 

``` javascript

if (self === top) {
  // Do something else 
} else {
  top.location = self.location;
}

```

### Desired behavior

Cypress opens the website and keeps the test runner open as well.

### Cypress Version

9.5.3

**Comment by AtofStryker** [comment]
Hey @ExLeonem. Thank you for opening an issue. We introduced a new flag in [10.4.0](https://docs.cypress.io/guides/references/changelog#10-4-0) called `experimentalModifyObstructiveThirdPartyCode`, that should mitigate the frame busting techniques you have mentioned here. Have you tried using the new experimental flag to verify it solves your issue?

**Comment by ExLeonem** [comment]
Totally overlooked that feature. Adding the flag resolved the Issue. Thank you!
