### ISSUE TITLE
Cypress.env() supporting objects

### ISSUE THREAD

**Issue by blasvicco** [cypress-io/cypress#2320]
### Current behavior:

If we try to set an object as env variable we get an error.

### Desired behavior:

It will be great if we can set objects in the env variables.

### Versions
Beta 3.0.3

**Comment by funnylookinhat** [comment]
As an example - we have an environment-specific options object that we frequently want to pass to `cy.visit` that include HTTP Auth, etc.; it'd simplify things greatly if we could just: `cy.visit('/foobar', Cypress.env('visitOptions'));`

**Comment by jennifer-shehane** [comment]
@blasvicco Could you explain how you are trying to set your env variable? There are 5 ways they can be set - so we want to make sure to address your issue appropriately. https://on.cypress.io/environment-variables#Setting

@funnylookinhat `Cypress.env()` should accept an object, as is [described in the docs](https://on.cypress.io/env#Arguments).  Make sure you are passing the object literal and not the string 'visitOptions'.

**Comment by blasvicco** [comment]
@jennifer-shehane Following [this](https://docs.cypress.io/api/plugins/configuration-api.html#Usage)
We have in our plugin js index file the next lines:
```JS
module.exports = (on, config) => {
  config.env.visit_options = {
      auth: {
        password: 'test',
        username: 'test_something',
      },
  };
  console.log(config);
  return config;
};
```
When we run cypress we are able to see that the config has the `env.visit_options` set properly but in the cypress window we are getting this error:
<img width="734" alt="screen shot" src="https://user-images.githubusercontent.com/1821068/44037968-fde0aaaa-9f15-11e8-95dc-1eb7c75e0882.png">

**Comment by jennifer-shehane** [comment]
Yes, this does throw this error. Console.log of env options in config:

```
{ 
  env: { visit_options: { auth: [Object] } }
 }
```

**Comment by jennifer-shehane** [comment]
Now that I see your use case, there is an open issue for this here: https://github.com/cypress-io/cypress/issues/1736

Going to close as duplicate.
