### ISSUE TITLE
Flaky test: Timed out after 4000ms. The done() callback was never invoked!

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23203]
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/runs/37593/test-results/62729875-b095-464d-8987-72f2535fced6

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cypress/proxy-logging.cy.ts#L106

### Analysis

We need to make sure `done()` is being called in the failure case. This won't fix the flake, but it will give us a more specific error message when this test flakes. 

### Cypress Version

10.4.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by rachelruderman** [comment]
Added `.skip` to this test in https://github.com/cypress-io/cypress/pull/23167. Please remove `.skip` when test is stable

**Comment by flotwig** [comment]
In 12.0.0 this test is invalidated by the removal of XHR monkey-patching in #24411, so I'm closing this since we won't do any work in this area between now and then.
