### ISSUE TITLE
Cypress consume much more memory on CI side than local machine

### ISSUE THREAD

**Issue by davidabap** [cypress-io/cypress#23207]
### Current behavior

We have a Cypress hangs issue on CI side recently alone with our spec count increased. But it never can be reproduced in local machine. We also enable the DEBUG info but nothing useful detect from our side. Cypress just randomly stop at different case on CI side without any infomation.

### Test code to reproduce

I just have one question related to the **chrome processCount parameter**, why the processCount is different between local(**_4_**) and CI side(**_8_**). Is there any way to config or control that ?
local(MAC):
![image](https://user-images.githubusercontent.com/25033055/183606155-85d37270-613d-4531-aa71-c644edd0bbc3.png)
CI side(*unix):
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/25033055/183606216-3c26e90e-7e66-48ec-8f6c-ae1a59bd17ee.png">

### Cypress Version

9.7.0

**Comment by AtofStryker** [comment]
Hi @davidabap. Thank you for opening an issue. Would you be able to share some details about your CI setup or provide a minimal reproduction example? Are you running any jobs in parallel on your CI machines?

**Comment by nagash77** [comment]
potentially related to https://github.com/cypress-io/cypress/issues/23207

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
