### ISSUE TITLE
Error while open Cypress using NPM: Network service crashed, restarting service.

### ISSUE THREAD

**Issue by dhaniqa** [cypress-io/cypress#23212]
### Current behavior

When i try to open Cypress using NPM : 

`npx cypress open`

My Cypress app is open but empty like this : 

![Screenshot 2022-08-09 201336](https://user-images.githubusercontent.com/105927124/183656240-e0ccaf28-238b-4653-aec3-5fee1cd29bdf.png)

and in NPM a mesage appears saying : 
[2964:0809/200042.666:ERROR:network_service_instance_impl.cc(470)] Network service crashed, restarting service.

![Screenshot 2022-08-09 201516](https://user-images.githubusercontent.com/105927124/183656195-8c81f62f-175f-4006-a5b0-cc67a2a07274.png)

Can anyone tell me the solution ??

### Cypress Version

10.4.0

### Package Manager

npm

### Operating system

Windows

**Comment by AtofStryker** [comment]
Hi @dhaniqa. Thank you for opening an issue. Are you running Cypress on a corporate managed device or through a VPN? Would you be able to run Cypress with debug logs enabled, such as `DEBUG=cypress:* npx cypress open`?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
