### ISSUE TITLE
Intermittent 'Error: Object has been destroyed' when running on Jenkins CI

### ISSUE THREAD

**Issue by JamesMilnerUK** [cypress-io/cypress#2321]
### Current behavior:

Currently we receive and error message intermittently when testing on Jenkins CI

```
  ┌─────────────────────────────────────────────────┐
  │ Tests:        2                                 │
  │ Passing:      2                               │
  │ Failing:      0                                 │
  │ Pending:      0                               │
  │ Skipped:      0                               │
  │ Screenshots:  0                             │
  │ Video:        true                              │
  │ Duration:     23 seconds                        │
  │ Spec Ran:     src/createUser.spec.js │
  └─────────────────────────────────────────────────┘

Error: Object has been destroyed

    at WebContents.<anonymous> (/var/lib/jenkins/.cache/Cypress/3.0.3/Cypress/resources/app/packages/server/lib/gui/windows.js:204:22)

    at emitOne (events.js:115:13)

    at WebContents.emit (events.js:210:7)

Error: Object has been destroyed

    at WebContents.<anonymous> (/var/lib/jenkins/.cache/Cypress/3.0.3/Cypress/resources/app/packages/server/lib/gui/windows.js:204:22)

    at emitOne (events.js:115:13)

    at WebContents.emit (events.js:210:7)

```
It seems strange that it's referencing anything to do with the Windows GUI, since we're running Jenkins on Ubuntu. Is it possible that the operating system is being detected incorrectly?

### Desired behavior:

The tests should pass consistently without this error, or if it is the case, provide an error that points to the causation of the problem.

### Steps to reproduce:

The error seems intermittent, but always seems to happen when switching to the second set of tests.

### Versions

Cypress 3.0.3 running on Ubuntu on Jenkins CI

**Comment by jennifer-shehane** [comment]
This has nothing to do with Windows the OS. This error is throwing from our 'windows' logic, which deals with handling the Electron browser window. 

This should not happen and I have not seen this error before. 

Could you run this with debug logs on so we can better track down where this is happening? 

```
DEBUG=cypress:* cypress run
```

**Comment by brian-mann** [comment]
This is a bug, I know why this is happening. We'll fix it.

**Comment by JamesMilnerUK** [comment]
@jennifer-shehane @brian-mann, my apologies, I should have actually checked the file! (https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/gui/windows.coffee for anyone interested). Sounds like you have an understanding of what it might be, but I will try and get a debug log for you (might be tricky as it's an intermittent bug).
