### ISSUE TITLE
Flaky test: Proxy performance

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#23214]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/41517/workflows/108f93c0-588c-46ff-b2db-efbdbee3ed7b/jobs/1720262/tests#failed-test-0

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/server/test/performance/proxy_performance_spec.js#L373

### Analysis

`Proxy Performance http://test-page-speed.cypress.io/index1000.html "before all" hook for "With Cypress proxy, Intercepted loads 1000 images less than 3x as slowly as Chrome"`

Not sure why this is flaky but it does seem to pass/fail inconsistently.

### Cypress Version

10.4.0

**Comment by rachelruderman** [comment]
Added `.skip` to this test in https://github.com/cypress-io/cypress/pull/23167. Please remove `.skip` when test is stable

**Comment by jueinin** [comment]
is there any progress？ Or if i can disable proxy？

**Comment by lmiller1990** [comment]
I think I reproduced this https://github.com/cypress-io/cypress/issues/22868#issuecomment-1357045428

It looks like there's some odd bottleneck that is kicking in after a couple hundred requests. In my case, 138 requests.

I also don't think this is flake - I think this test is failing for the right reasons, the network proxy regressed between Cy 9 and when this regressed.
