### ISSUE TITLE
Cypress Cross Origin error with Chrome despite the chromeWebSecurity to false

### ISSUE THREAD

**Issue by AurelienKun** [cypress-io/cypress#23238]
### Current behavior

We have a test that needs to click to an element leading to an external url. Once the url is loaded some checks happen.
We used to have the test working on 9.7. But since the migration to 10.4.0 we have this test failing with the error explaining to add the chromeSecurity flag to false but we already have it set on the cypress.config.js. 
Maybe a small detail here : we call cypress with our own config.js provided with a path.

### Desired behavior

The test should work as before since the security flag is disabled. 

### Test code to reproduce

```
    afterEach(() => {
      cy.url().should("include", EXTRA_INFORMATION);
    });

    it("Opens an external url with extra information on element click", () => {
      cy.get(SELECTOR)
        .first()
        .click();
    });
```

### Cypress Version

10.4.0

### Other

Running on windows 10

**Comment by AtofStryker** [comment]
Hi @AurelienKun. Thank you for opening an issue. Would you be able to provide a reproduction repository that we can run to see the issue? When did you start seeing the issue and what was the version is started in? What was the last version it worked in?

**Comment by AurelienKun** [comment]
Unfortunately I cannot upload any files on our company project. I'm gonna try if I can create a side project for that but it won't be able to provide you anything until next week.
As I told you: we were using v9.7.0 and everything ran perfectly fine on our CI.
I migrated our project to v10.4.0 and we got a lot of test flakiness. So when I tried to debug our tests using `cypress open` I saw among the errors this issue about cross origin on few test despite the correct flag set in the `cypress.config.js`

**Comment by AtofStryker** [comment]
OK I will be on the lookout! And I'm sorry that the v10 upgrade hasn't been going too smoothly. Hopefully we can get something figured out. This issue is interesting to me since we haven't really changed a whole lot around the `chromeWebSecurity` feature, but I'm hoping once I can see what is going on I will be able to provide some assistance.

**Comment by AurelienKun** [comment]
OK i found some little time and was able to easily reproduce :
https://github.com/AurelienKun/demo

**Comment by AurelienKun** [comment]
This is really weird. I tried this on other laptop running linux and it works like you. I will update on tuesday with a screenshot on my windows machine (from work)

**Comment by AurelienKun** [comment]
![Capture d’écran 2022-08-16 093857](https://user-images.githubusercontent.com/3368866/184824833-c6e125e4-f5ca-42ba-8cfe-41bdb2243ce5.png)
I have the error on my working station. Tell we how I can provide you more info about this @AtofStryker .

**Comment by AurelienKun** [comment]
Interesting fact : it works when run in headless mode...
![Capture d’écran 2022-08-16 100830](https://user-images.githubusercontent.com/3368866/184830612-892c0d97-26e5-468e-bbea-f50756e20a93.png)

**Comment by AtofStryker** [comment]
@AurelienKun did you have to do anything specific to reproduce it outside the reproduction repo provided? I can give it a shot on windows and see if I get similar results.

**Comment by AurelienKun** [comment]
@AtofStryker  No I just used the same repo. I updated few minor things on this demo project with correct script and the above screenshots. Nothing more.

**Comment by AtofStryker** [comment]
I wasn't able to reproduce on Windows 10 
![image](https://user-images.githubusercontent.com/3980464/184945243-c08b59be-9358-432a-90be-1712b9aa99fa.png)

@AurelienKun I wonder if you have a Corporate Security Policy that might be interfering (though it would seem strange for web security flags to play a part). Chrome does have the concept of isolated origins that can be [enterprise](https://support.google.com/chrome/a/answer/7581529?hl=en) regulated. Are you able to confirm if that is the case?

**Comment by AurelienKun** [comment]
@AtofStryker there are security policies applied to every computer of my company by the means of Microsoft InTunes but I cannot exactly tell what's going on there. Unfortunately, I cannot bypass those protections to check if cypress don't fails anymore... :(
If there is a way to get more useful logs for example, I'd be glad to provide them.

**Comment by rachelruderman** [comment]
Hi @AurelienKun ! It's interesting that it works in headless mode but not in open mode. Are you using the same browser when running headless and open? Which browser is it?

> If there is a way to get more useful logs for example, I'd be glad to provide them.

Here's instructions on [how to print debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) that you can then upload to this issue

**Comment by AurelienKun** [comment]
> Hi @AurelienKun ! It's interesting that it works in headless mode but not in open mode. Are you using the same browser when running headless and open? Which browser is it?

Same 104 version. You can see it on the screenshot I have provided :)

> Here's instructions on [how to print debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) that you can then upload to this issue

Great ! I'll give it a try soon. I'll keep you updated as soon as I get some logs.

**Comment by nagash77** [comment]
@AurelienKun have you had a chance to get those logs?

**Comment by AurelienKun** [comment]
@nagash77  Here are the logs but I don't see anything usefull with  `set DEBUG=cypress:*`
Tell me if I did it wrong.
[logs.txt](https://github.com/cypress-io/cypress/files/9460150/logs.txt)

**Comment by AurelienKun** [comment]
@nagash77 Here are the logs.
Please notice that with logs enabled, the first instance of chrome launched by cypress had its cypress plugin crashing. I had to close the browser, select chrome again then it worked. 
[logs.txt](https://github.com/cypress-io/cypress/files/9460212/logs.txt)

**Comment by emilyrohrbough** [comment]
@AurelienKun Do these log reflect when you see this error in the browser? Do you only see this error in the browser when the plugin? Can you specify what plugin you are adding that is crashing? I'm having a little trouble correlating these logs to your example

**Comment by AurelienKun** [comment]
@emilyrohrbough OK let me explain a little more. I previously copied too much log, I'm sorry about that.

1. The logs should have started at the line `npm run cy:view > logs.txt`. The command makes Cypress in headed mode with the chrome browser (specified with the `--browser` flag).
2. For some unknown reasons, when (and only when) the logging is enabled on my laptop, the chrome browser launched by cypress starts with a blank page and a bubble appears indicating that the cypress plugin has failed. User (me) must click on the bubble message to reload the browser/plugin but it fails every time.
I guess the logs related to these errors are with the lines `Error: Could not find url target in browser about:blank` ones maybe ? 
3. So I had to close the browser, select "Chrome" again on the main cypress windows. Then, everything ran OK and I could see the test listed in the browser.
4. Then I clicked on it to run the test.
5. Finally the test started and failed with the cross origin error then I closed everything and copy pasted the logs.   

I do not use extra config nor plugins. But as @AtofStryker pointed to me, there might be some corporate policies that would cause those issue but I can't really tell...

**Comment by emilyrohrbough** [comment]
@AurelienKun Thank you for the detailed explanation. Unfortunately I am unable to repo the issue either. Maybe you could try your simple example on another machine on a private network to verify if this is indeed related to your corporate policies. Also, verifying if another co-worker on the name network is also experiencing those issue might help verify that is the issue.

**Comment by emilyrohrbough** [comment]
@AurelienKun Any updates?

**Comment by AurelienKun** [comment]
@emilyrohrbough Hello Emily, sorry for the delay. I can confirm the same issue on my other colleague laptops so this error must be related to our compagny policies. 
For example I know that we can't log our browser to a gmail account, the synchronization is disabled. Also there is a plugin automatically added to chrome to disable Google Analytics. So it might have something to do when Cypress use Chrome I guess. 
Is there a workaround to force a browser without anything but the cypress plugin or maybe disguise the chrome identity to avoid the policies ?

**Comment by emilyrohrbough** [comment]
@AurelienKun I am unaware of a way to force a browser to ignore network policies.

**Comment by chrisbreiding** [comment]
This issue doesn't seem possible to reproduce on our end and there's no workaround we can introduce into Cypress to bypass network security policies. Unfortunately, we'll have to close this issue since there's no path forward.
