### ISSUE TITLE
When cypress runs in headless mode, it repeatedly requests the same image resources

### ISSUE THREAD

**Issue by lbq97** [cypress-io/cypress#23234]
### Current behavior

Use commands：cypress run --headed -b electron --no-exit
The browser will frantically request image resources during my assertion (to determine whether an element appears)，create hundreds of requests until the assertion is complete,in fact, there are only two image resources

![image](https://user-images.githubusercontent.com/81401010/183850371-87052820-f064-4e18-8697-aaa4432a9284.png)

When I run cypress with npx cypress open, the above situation will not occur

### Desired behavior

The running results of headless mode and interactive mode are consistent

### Test code to reproduce

The steps are as follows:
1、Sign in

2、Use the cy.visit() command to access a url that can only be accessed after login

### Cypress Version

9.6.0

**Comment by lbq97** [comment]
I need to use window. performance. getentries() to get all the resources requested by the current page,In headless mode,compared with the results returned in the interactive mode, the results returned by this command in the headless mode omit some API requests, I suspect it is caused by the above phenomenon

**Comment by nagash77** [comment]
@lbq97 can you provide a sample test that can reliably reproduce the issue so that we can further investigate?

**Comment by lbq97** [comment]
@nagash77 I'm sorry, but I can't provide you with an example because I'm testing a project of the company that needs an intranet to access，I can provide you with directions,this is the conclusion that I test three projects with the same process and only one of them appears，You can find an item that has resources requested by:
![image](https://user-images.githubusercontent.com/81401010/184048158-adb3d522-b8a3-46ca-8bd0-d9a284e0faf5.png)
The steps are as follows:
![image](https://user-images.githubusercontent.com/81401010/184048450-dcf9c0d5-0407-44cd-89fe-0c803b1d536b.png)
1、access project login address and login in
2、through cy.visit() accesses the page that can only be accessed after login, and the page has the method of requesting resources mentioned above
3、determine the completion of page loading through an element
through the above steps, maybe you can reproduce the scene I mentioned
thanks@nagash77

**Comment by rockindahizzy** [comment]
Hi @lbq97, can you provide some more details about your `cy.visit` calls above. Are they both visiting the same domain?

**Comment by lbq97** [comment]
@rockindahizzy Hello, they do not belong to the same domain. The login page of the project uses sso, and the page jumped after login belongs to another domain,thanks

**Comment by rockindahizzy** [comment]
Hey @lbq97, it sounds like you may want to use `cy.origin()` in this scenario. [Here is a blog post detailing `cy.origin()`](https://www.cypress.io/blog/2022/04/25/cypress-9-6-0-easily-test-multi-domain-workflows-with-cy-origin/)

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
