### ISSUE TITLE
Error with permission

### ISSUE THREAD

**Issue by grzech1991** [cypress-io/cypress#23239]
### Current behavior

[13:29:51]  Downloaded Cypress      [title changed]
[13:29:51]  Downloaded Cypress      [completed]
[13:29:51]  Unzipping Cypress       [started]
[13:29:51]  Unzipping Cypress       [failed]
[13:29:51] → The Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at

https://github.com/cypress-io/cypress/issues

----------

Error: EACCES: permission denied, mkdir '/home/node/.cypress/6.9.1'

----------

Platform: linux (Debian - 10)
Cypress Version: 6.9.1
The Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at

https://github.com/cypress-io/cypress/issues

----------

Error: EACCES: permission denied, mkdir '/home/node/.cypress/6.9.1'

----------

make[1]: *** [Makefile:18: yarn.lock] Błąd 1
make[1]: Opuszczenie katalogu '/home/it/pim'
make: *** [Makefile:78: prod] Błąd 2

### Cypress Version

6.9.1

### Package Manager

npm

### Operating system

Linux

### Other

Hi anyone can help me with this? Google no have solution.

**Comment by nagash77** [comment]
@grzech1991 I see you are using a pretty old version of Cypress.  Can you try upgrading to the latest and see if you are still seeing this same behavior?

**Comment by grzech1991** [comment]
You may be right, but this is an installation package that I run with make (akeneo). So the fault is probably in the package, even if I pick up on the cypress server it is ignored anyway.

**Comment by nagash77** [comment]
@grzech1991 Unfortunately we will need some more info in order to better investigate this issue.  Can you provide a repo demonstrating a reproduction of the problem?  

What happens when you run this with elevated permissions?

**Comment by grzech1991** [comment]
Thank you @nagash77 

I use akeneo pim with installation via docker.

https://docs.akeneo.com/master/install_pim/docker/installation_docker.html chose community edition or install from github (for me there are similar installations)

https://github.com/akeneo/pim-community-standard

After use

`make prod`

i have this error, it appears already in the final stage of the installation

**Comment by AtofStryker** [comment]
Hey @grzech1991. Thank you for opening an issue. I gave the steps above a try and ran into this 
![Screen Shot 2022-08-15 at 5 17 26 PM](https://user-images.githubusercontent.com/3980464/184720178-92dba757-732e-4f13-bc4b-5de2c430cc07.png)

It seems unrelated, but I'm having issues getting to the steps you reached. Would you be able to provide a full reproduction repository that includes explicit steps to reproduce the issue?

**Comment by grzech1991** [comment]
So i use chmod 777 for directory

"~/.cache/Cypress" and... works :)

**Comment by AtofStryker** [comment]
@grzech1991 glad you were able to find a solution. I am going to close this issue but let us know if you continue to have trouble.

**Comment by rajakvk** [comment]
@grzech1991 Fix worked for me as well. 
ie., `chmod 777` on the target directory.
