### ISSUE TITLE
`console.error` swallowed in component tests

### ISSUE THREAD

**Issue by amannn** [cypress-io/cypress#23242]
### Current behavior

Currently `console.error` calls are swallowed in component tests when a component makes such a call.

### Desired behavior

`console.error` calls should be visible in the browser.

### Test code to reproduce

See the reproduction here: https://github.com/amannn/cypress-component-testing-examples/tree/main/create-react-app. I took your component testing example and updated Cypress to the latest version.

When you run the interactive test for `App.spec.cy.js` and open the browser console, you only see the logs from `console.log` and `console.info` – not the one from from `console.error` ([link to the code](https://github.com/amannn/cypress-component-testing-examples/blob/16975d6944f02b5bc2e3f49403553747a93f9ebd/create-react-app/src/App.js#L5-L7)).

### Cypress Version

10.4.0

**Comment by rockindahizzy** [comment]
Hey @amannn, thanks for reporting the issue. 

It looks like we are moving away from [`cypress-component-testing-examples`](https://github.com/cypress-io/cypress-component-testing-examples), in favor of [`cypress-component-testing-apps`](https://github.com/cypress-io/cypress-component-testing-apps). Which is more up to date following v10.

I created a recreation of a similar scenario that you provided [here](https://github.com/rockindahizzy/cypress-component-testing-apps/commit/f1d150478d14cdf143daabba6e3517f7542de7b3). I am seeing the error log in my console. Can you confirm that this is still an issue using this repo?

**Comment by amannn** [comment]
Thanks for following up so quickly! I have to apologise, somehow in my Cypress Chrome runner the log levels were configured to omit errors. Now everything works as expected:

<img width="535" alt="Screenshot 2022-08-12 at 09 58 41" src="https://user-images.githubusercontent.com/4038316/184311181-ac78dd2e-d410-4797-87f5-0feaecbe9191.png">

Sorry for the false report and thank you for your work on Cypress! 🙂

**Comment by rockindahizzy** [comment]
Awesome! I've done that so many times 😆. Glad it's working for you again!
