### ISSUE TITLE
Missing rendered elements and cannot click elements because it is covered by its own iframe

### ISSUE THREAD

**Issue by johntran** [cypress-io/cypress#2324]
### Current behavior:

- Rendered page is missing left nav bar and top nav bar even though it shows up in Chrome
- Test cannot continue because Cypress says the button is covered by another element. It seems to be covered by an iframe that contains the app that Cypress is testing.

<img width="1355" alt="screenshot 2018-08-11 15 37 26" src="https://user-images.githubusercontent.com/3813391/43996669-78302b0a-9d7c-11e8-9f78-c3e932ad9fde.png">

### Desired behavior:

- Top nav bar and left nav bar should show up
- Cypress should be able to click the add to cart button beneath any item in the shop

### Steps to reproduce:

Here is the test file. It runs on our production app
https://gist.github.com/johntran/2f34a31933ff988d8789585e7c51d2d6

Let me know if you want a repo instead of this file.

### Versions

Cypress: 3.0.3
Mac OS High Sierra version 10.13.3
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

### Other considerations

This test used to work before on Cypress 3.0.0, but now something in our codebase broke this Cypress test even on versions 3.0.0-3.0.3. I'll investigate into past branches in our to see what was the breaking change.

**Comment by jennifer-shehane** [comment]
This is undoubtedly this issue: https://github.com/cypress-io/cypress/issues/2037#issuecomment-407898194

Do you happen to have the `--disable-blink-features=RootLayerScrolling` workaround in your plugins file directly? Because this can be and should be removed now in 3.0.3.

**Comment by johntran** [comment]
@jennifer-shehane Removing the workaround worked! Thanks! This can be closed
