### ISSUE TITLE
Vue Transition makes Cypress re-render the component

### ISSUE THREAD

**Issue by rasc-br** [cypress-io/cypress#23241]
### Current behavior

This is going to be complex to explain:

I have a component that works 100% in the application, but fails at Cypress, and I notices that is because I'm using Vue `<Transition>` component.
I have a `computed` outside the `Transition` that changes depending on 2 variables inside `Transition`, it's a simple `firstname` + `lastname`.
The `input` for those are inside a `Transition` element, and the `fullname` is outside `Transition`.
Everytime that I use `cy.type("something")` into one of those inputs inside `transition`, Cypress re-render everything and it looses focus of the input, therefore whatever I ask to be typed, it just types the first character and looses focus and fails.

If I remove `<Transition>` it works.
If I remove the `computed` it works.
If I move the `fullname` computed inside the `Transition` with the other inputs, it works.

### Desired behavior

Cypress should not re-render and lose focus of what it's been typed into the input element.

### Test code to reproduce

```
            <h5 data-cy="applicant-fullname">
                {{ fullName }}
            </h5>
            <Transition name="slide-fade">
              <div v-if="someCondition">
                 <input
                      v-model="firstName"
                      data-cy="applicant-firstname"
                  />
                 <input
                      v-model="lastName"
                      data-cy="applicant-lastName"
                  />
             </Transition>
```
```
const fullName = computed<string>(() => {
    return `${firstName} ${lastName}`;
});
```

### Cypress Version

10.4.0

**Comment by rockindahizzy** [comment]
@rasc-br, thanks for reporting this issue!

Unfortunately it doesn't seem like there is enough information here to recreate the issue. 

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
