### ISSUE TITLE
Flaky test: Timed out after 4000ms. The done() callback was never invoked! II

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23250]
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/runs/37673/test-results/8a41ed5b-35f6-4f04-a145-8ab29ec7ecff

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cypress/proxy-logging.cy.ts#L106

### Analysis

<img width="423" alt="Screen Shot 2022-08-10 at 9 45 00 AM" src="https://user-images.githubusercontent.com/26726429/183966740-dea6bd28-a1fc-4ed3-90f7-5842bc8a7c62.png">

### Cypress Version

10.4.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by rachelruderman** [comment]
Added `.skip` to this test in https://github.com/cypress-io/cypress/pull/23167. Please remove `.skip` when test is stable

**Comment by flotwig** [comment]
In 12.0.0 this test is invalidated by the removal of XHR monkey-patching in #24411, so I'm closing this since we won't do any work in this area between now and then.
