### ISSUE TITLE
Getting ERROR: Could not resolve "cypress-plugin-snapshots/commands" when running in Cypress 10

### ISSUE THREAD

**Issue by faith-berroya** [cypress-io/cypress#23272]
### Current behavior

I am getting this error when I am trying to run any of my specs file. It was working before. Am I missing a step here? How do I mark the path as external?

I removed parts of images that contain sensitive information.

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/101372793/184088708-c58d32d0-b582-49b4-a962-68c28c0b1742.png">

e2e.js

```
require('cypress-plugin-tab')
import './commands'

const dayjs = require('dayjs')
Cypress.dayjs = dayjs

import 'cypress-plugin-snapshots/commands'; 
```

### Test code to reproduce

Code was working until upgraded to Cypress 10. Last tested working in Cypress 9.6.0.

### Cypress Version

10.4.0

**Comment by nagash77** [comment]
@faith-berroya this seems to be related to a 3rd party plugin.  [this issue](https://github.com/meinaart/cypress-plugin-snapshots/issues/215) explains the problem and indicates it is unfortunately not supported in Cypress >10 at this time.

I suggest you open an issue with that project.  Here is a [link](https://github.com/meinaart/cypress-plugin-snapshots) to their repo in github
