### ISSUE TITLE
Paste via keyboard fails in CI, but passes in UI mode

### ISSUE THREAD

**Issue by nichit93** [cypress-io/cypress#23278]
### Current behavior

Paste via keyboard is consistently failing in CI, but passes in UI mode (fails sometimes).

test code:
it("Copy and paste tasks", () => {
        // Get the row count
        cy.get("rowClass").then(rows => {
            // Copy the last row
            cy.get("rowClass").eq(-1).find("class to select whole row").click();
            cy.get("body").type("{ctrl+c}");
            cy.get("rowClass").eq(-1).should("have.class", "cut-copy-animation");

            // Select the first row and paste
             cy.get("rowClass").eq(0).find("class to select whole row").click();
            cy.get("body").type("{ctrl+v}");

            // Row count should increase
            cy.get("rowClass").should("have.length", rows.length + 1);
        });

![image](https://user-images.githubusercontent.com/22310928/184104848-e9921ff7-8db3-4d9a-8dbd-5e03d28022ba.png)

### Desired behavior

On keyboard paste, it should paste the row above the first row.

![image](https://user-images.githubusercontent.com/22310928/184107783-87772238-5927-40ec-b715-58dbee107c90.png)

### Test code to reproduce

Repro would be specific to the app, not sure how to provide a repro.
Though so far what I investigated, it seems to be losing focus and only explicit click (while running tests in UI mode) seems to fix the issue.

Neither cy.get(id).focus() or cy.get(id).click() works.

### Cypress Version

9.6.1

### Other
Redirect me to the right forum, if this is not the right place
Thanks!

**Comment by rockindahizzy** [comment]
Hey @nichit93, it seems like you may be having an issue where CI shortcuts for copy and past may behave differently than when running in the UI on your machine.

I did some searching and found an article that provides a way to do copy and paste using cross-platform method: https://egghead.io/blog/handling-copy-and-paste-in-cypress

Are you able to try that out and see if it fixes the issue?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
