### ISSUE TITLE
Markdown rendering of initialization errors for bullets are not formatted properly

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#23294]
### Current behavior

- Error bullets are not formatted properly see below (indentation and bottom margin)
- When making CSS changes ya'll need to check the output with the internal diffing tool we created specifically for error formatting. It will tell you exactly how errors will look
- Additionally one or two of these error states should be captured in percy (pick an error that uses a significantly complex layout) so that CSS changes will be surfaced in percy and these problems will be caught before they get released

/cc @marktnoonan 
![Screen Shot 2022-08-11 at 3 38 14 PM copy](https://user-images.githubusercontent.com/1268976/184226827-e3effff0-c6b5-4cdd-81cd-5b0f13345a4a.png)
<img width="1109" alt="Screen Shot 2022-08-11 at 3 38 22 PM copy" src="https://user-images.githubusercontent.com/1268976/184226828-0f0c20b6-ec2f-402c-90de-b69a9296b146.png">

### Desired behavior

Errors render properly in markdown

### Test code to reproduce

N/A

### Cypress Version

10.4.0

### Node version

N/A

### Operating System

Mac

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23294?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
