### ISSUE TITLE
Errors during initialization of CT prevent "going back" to testing type selection

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#23293]
### Current behavior
- When there is an error opening the CT testing type, the link is disabled preventing me to go back to "testing type selection"
- When there is an error opening the E2E testing type, the link is enabled allowing me to go back to "testing type selection"

**CT Error**
<img width="1109" alt="Screen Shot 2022-08-11 at 3 38 14 PM" src="https://user-images.githubusercontent.com/1268976/184225989-eedab4b2-0431-4bca-8a20-cc022fbd4828.png">

**E2E Error**
<img width="1109" alt="Screen Shot 2022-08-11 at 3 38 22 PM" src="https://user-images.githubusercontent.com/1268976/184225955-34dcdfd7-6445-4059-80dd-8379ae9e62c8.png">

### Desired behavior

When there is an error opening the CT testing type I should be able to click the link navigating me back to testing type selection

### Test code to reproduce

N/A

### Cypress Version

10.4.0

### Node version

N/A

### Operating System

Mac

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23293?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
