### ISSUE TITLE
Improve how snapshots handle CSS

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#233]
Currently, a snapshot holds a copy of the `body` with any stylesheet `<link>` tags removed (so that no further requests are made when the snapshot is restored). When tests are finished, the iframe points to and contains the contents of the last page visited (**a**). When a snapshot (**b**) is restored (by hovering over a command in the command log), it replaces the body of the iframe with the copied, stylesheet-less body of the snapshot. 

There are a few problems with this:

* The CSS from the head of **a** is still there, so **b** will end up using those styles
* **b** is lacking any `<link>`ed styles that were in its `<body>`, so those styles are missing
* **b** is lacking any classes that were on its `<html>` tag

Solution:

When creating a snapshot:

* Grab any styles from `<link>`s or `<style>` tags, in order, and preserve them
* Remove all styles (`<link>` or `<style>` tags) from the copied body
* Grab any classes from the `<html>` tag and preserve them

When restoring a snapshot:

* Remove any styles in the `<head>` of the iframe (and preserve them for reverting), and restore the `<body>` of the snapshot, inserting the preserved styles
* Replace any classes on the `<html>` tag with those from the snapshot

When reverting to the last page visited:

* Put back any styles preserved from the `<head>` of the last page visited
* Replace any classes on the `<html>` tag with those from the last page visited

**Comment by brian-mann** [comment]
Fixed in [`0.17.5`](https://github.com/cypress-io/cypress/wiki/Changelog#0175-10022016).
