### ISSUE TITLE
Cypress v10 stuck loading on open, spinner loads forever

### ISSUE THREAD

**Issue by Saimis777** [cypress-io/cypress#23309]
### Current behavior

Hi,
I've upgraded from the 9.7.0 version of Cypress to v10.3.0, v10.4.0, but doing a npx cypress open gets stuck on loading , no errors in the terminal, when running v10.0.3 shows errors, any v9 works without any issues.

![image](https://user-images.githubusercontent.com/75423142/184305448-809d1cc1-e6cc-4c6e-bf68-cfd8d5608f95.png)
![image](https://user-images.githubusercontent.com/75423142/184306005-bcde9cc8-959f-4188-b6a7-19b44206d91a.png)

### Test code to reproduce

Install any v10 Cypress on the same version of ubuntu as me.

### Cypress Version

10.4.0

### Node version

6.14.4

### Operating System

Ubuntu 20.04.3 LTS

**Comment by AtofStryker** [comment]
Hey @Saimis777. Thank you for opening an issue. is your node version `6.14.4` or `16.14.4`? Just want to confirm it isn't extremely out of date. Would you also be able to provide a quick reproduction repository? It looks like the incorrect binary might be installed that you are referencing (says 10.0.3 but issue says 10.4.0). are you invoking the binary through `npx`? It might be good to try a `cypress cache clear` and rerun to see what happens.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by lunaisnotaboy** [comment]
@nagash77 I am unfortunately experiencing this same problem.

**Comment by AtofStryker** [comment]
@lunaisnotaboy I'm sorry to hear that. Would you be able to open a new issue to describe what you are seeing within reproducible steps?

**Comment by lunaisnotaboy** [comment]
@AtofStryker I will open an issue as soon as I return home. Thanks!

**Comment by lunaisnotaboy** [comment]
@AtofStryker Done! The issue's designation is #23499.
