### ISSUE TITLE
Flaky test: Too long with no output (exceeded 10m0s): context deadline exceeded

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23308]
### Link to dashboard or CircleCI failure

- https://app.circleci.com/pipelines/github/cypress-io/cypress/41757/workflows/edf97bff-eef3-4f3f-8057-4277aef7d046/jobs/1730766
- https://app.circleci.com/pipelines/github/cypress-io/cypress/42240/workflows/b213eedd-524b-4ef3-9170-b15bfc01d1c7/jobs/1753458

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/navigation.cy.js#L495

### Analysis

Tests hang during execution of `navigation.cy.js` file

<img width="700" alt="Screen Shot 2022-08-11 at 8 00 17 PM" src="https://user-images.githubusercontent.com/26726429/184276927-80c83a8d-e2f2-4b69-9794-a18255e7060d.png">

We also see this same error as seen in https://github.com/cypress-io/cypress/issues/23326
```
$ node ../../scripts/cypress run --config experimentalSessionAndOrigin=true,experimentalModifyObstructiveThirdPartyCode=true --record --parallel --group 5x-driver-chrome:beta-experimentalSessionAndOrigin --browser chrome:beta
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2032:0811/220636.124358:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```
### Cypress Version

10.4.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by rachelruderman** [comment]
[This linux CI job also timed out](https://app.circleci.com/pipelines/github/cypress-io/cypress/41989/workflows/71675e5d-acb5-4757-acc0-968283f1f074/jobs/1742094) with similar resource exhaustion:

<img width="1275" alt="Screen Shot 2022-08-16 at 2 12 37 PM" src="https://user-images.githubusercontent.com/26726429/184986102-83fe9a3a-d8c6-4150-824f-fa3d4f0bb69b.png">

**Comment by rachelruderman** [comment]
Anddddd [another linux CI job](https://app.circleci.com/pipelines/github/cypress-io/cypress/42014/workflows/db239753-ac71-4aad-910d-c413575e01fb/jobs/1743026/resources) with 100% CPU:
<img width="1278" alt="Screen Shot 2022-08-16 at 3 01 56 PM" src="https://user-images.githubusercontent.com/26726429/184992983-019a0dac-315a-48b0-9a8f-7f15822baaae.png">

**Comment by rachelruderman** [comment]
Closing as duplicate of https://github.com/cypress-io/cypress/issues/21300

**Comment by audriusnavickasDB** [comment]
Might be related to https://github.com/cypress-io/cypress/issues/21110 Also there are many more issues registered regarding Cypress hanging in CI.

**Comment by josekim** [comment]
I ran into this problem, "Too long with no output (exceeded 10m0s): context deadline exceeded" in circleci.

**I found that the best solution around this was just to log something to the Command line using cy.task in my test.  There is some setup involved, but you can [see it here](https://docs.cypress.io/api/commands/task).**

I think this may be a better solution than dealing with CircleCi Configs.
I had a test that takes about 20 minutes to complete, mainly because i'm waiting for some data to propagate through the backend before I check.  I broke up my 15 minute wait time and just logged a couple of things to the command line and that fixed my problem
