### ISSUE TITLE
Flaky test: `cy.click()` failed because this element is detached from the DOM.

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23305]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/41754/workflows/89edd596-de17-4dc1-8183-f4d037217241/jobs/1730646/tests#failed-test-1

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/specs_list_e2e.cy.ts#L240

### Analysis

Detached DOM error. @BlueWinds is working on a fix this quarter 😸 

<img width="1078" alt="Screen Shot 2022-08-11 at 6 51 51 PM" src="https://user-images.githubusercontent.com/26726429/184270523-0702266a-4215-4d78-aeaa-c8a8348ed7e2.png">

### Cypress Version

10.4.0

**Comment by rachelruderman** [comment]
Added `.skip` to this test in https://github.com/cypress-io/cypress/pull/23167. Please remove `.skip` when test is stable

**Comment by lmiller1990** [comment]
Cy 12 w/ detached DOM landed, which should alleviate this. I re-ran this a bunch of times on my local windows and it's passing. Also, we recently merged a PR removing this `skip`. This looks good to me now.

Will revisit if this flakes out again, but for now I'd say this is solved.
