### ISSUE TITLE
Tests Run in TestRunner but not in CLI

### ISSUE THREAD

**Issue by mikzerafa** [cypress-io/cypress#23311]
### Current behavior

![328_DynamicItBlocks](https://user-images.githubusercontent.com/19959516/184310168-919d3bb4-bb07-4854-84d7-e1f1b51278f0.png)

What is happening:
I have Dynamic It blocks to define which tests to run based on the URL. 
When I run tests in TestRunner they run accordingly, but in CLI they are skipped automatically.

### Desired behavior

For Tests to Run in CLI when defining an It() block as Dynamic
![329_DyanmicITBlock](https://user-images.githubusercontent.com/19959516/184310715-6df6a9f2-8c90-4247-a4e7-3dd0541c0f42.png)

### Test code to reproduce

N/A

### Cypress Version

9.0.0

### Node version

16.14.2

### Operating System

Windows 10

### Other

It was occurring with Cypress 10 also

**Comment by rockindahizzy** [comment]
@mikzerafa, are you able to confirm that your conditional is what you expect in your CI environment with a log statement?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
