### ISSUE TITLE
Analysis of Architectural difference between Cypress and Selenium as per Cypress documents and need inputs

### ISSUE THREAD

**Issue by svadivel0006** [cypress-io/cypress#23312]
### Current behavior

In this demo, I have summarized my analysis of Architectural difference between Cypress and Selenium.

Kindly provide your feedback as comments whether the “Real User Actions or Behaviors” should be part of functional, API and regression test automation or tweaking of HTML or DOM should be, too be a part.

[https://allthingsaboutuft.blogspot.com/2022/08/analysis-of-architectural-difference.html](url)

### Test code to reproduce

Provided in the video

### Cypress Version

10.4.0

### Node version

16.6.0

### Operating System

Windows

**Comment by nagash77** [comment]
@svadivel0006 Unfortunately we will not be able to assist you in this request at this time.  Good luck in your article.
