### ISSUE TITLE
Website load on separate browser and sidebar disappear that shows elements/locators on the left side

### ISSUE THREAD

**Issue by NoumanYns** [cypress-io/cypress#23314]
### Current behavior

When I visit website it loads on separate browser and test spec side bar disappear

### Desired behavior

It should load the website in cypress window 

### Test code to reproduce

describe('Url check', ()=>{
    it('Url load check', ()=>{

//         URL: https://prodtest.demosphere-secure.com/_/_officials-mgmt 
//                         OR
//              https://prodtest.demosphere-secure.com/_dashboard

        cy.visit('https://prodtest.demosphere-secure.com/_/_officials-mgmt')        
       
        cy.get('#user_login').type('alidem2')
        cy.get('#user_password').type('Alidem2')
        cy.get('[type="Submit"]').click()
     
    })

})

### Cypress Version

10.4.0

### Node version

v16.16.0

### Operating System

Windows 10

### Other

I have commented down issue here as well 
https://github.com/cypress-io/cypress/issues/8801

**Comment by AtofStryker** [comment]
Hi @NoumanYns. Thank you for opening an issue. Have to tried running this with the `experimentalModifyObstructiveThirdPartyCode`? It looks like you are running into a frame busting issue.

**Comment by NoumanYns** [comment]
Hi @AtofStryker ,I have tried running this with **experimentalModifyObstructiveThirdPartyCode : true**.
The problem that I am facing now is, after signing in and redirecting to dashboard cypress window closes.
Video:
https://www.loom.com/share/663cc14d5d914a35831037df5cf00462

**Comment by gurudattgd04** [comment]
There are few issues with the application 
1. The site is running in mixed content - If you open the chrome dev tools while running test you can see that. And even after you bypass, there is another issue
2. The following error originated from your application code, not from Cypress.

Permission denied to access property "document" on cross-origin object

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception

which is generated from below line of code

top.document.location='https://my.demosphere.com/oauth/authorize?client_id=ca6db3b02d704c287fecd155795f83e14c79651adcf30173892e7843c54955b4&redirect_uri=https%3A%2F%2Foauth.demosphere-secure.com%2F_chiron%2Fteamnet_callback&response_type=code&scope=public+club+club:contact+client+client:contact+household:details+household:members+user:profile+user:contact+user:households+user:roles+user:teams+user:members+team:rosters+team:activities+write&org=Demosphere';</script>

As i have already posted this in discord, thought to put it here which might help

**Comment by NoumanYns** [comment]
@gurudattgd04 I have used uncaught exception which is placed in **support/e2e.js** , but still not working .This is the code snippet 

import './commands'
Cypress.on('uncaught:exception', (err, runnable) => {

    return false
})

**Comment by rachelruderman** [comment]
Hi @NoumanYns ! I [created a reproduction](https://github.com/rachelruderman/issue-23314) and confirmed the behavior you're seeing. I'll route this one over to the team to take a look. Thank you for reporting this issue 🙏

**Comment by AtofStryker** [comment]
looks like this is still an issue in `12.7.0`

**Comment by aravithapa** [comment]
me also still facing same issue
