### ISSUE TITLE
Catching exceptions does not work

### ISSUE THREAD

**Issue by heddendorp** [cypress-io/cypress#23327]
### Current behavior

I have a login flow involving auth0. That page throws an exception sometimes when they can't start mfa enrollment.
This exception kills my test even though I am trying to ignore it.

### Desired behavior

Cypress should ignore the exception

### Test code to reproduce

https://github.com/heddendorp/tumi/blob/main/cypress/support/e2e.ts
Is my exact code, the tests form the repo can be used. Currently failing for me is the event-templates testcase

### Cypress Version

10.4.0

### Node version

17.9.1

### Operating System

Windows 11

**Comment by AtofStryker** [comment]
Hi @heddendorp. Thank you for opening an issue. Have you tried adding:

```
Cypress.on('uncaught:exception', (err) => !err.message.includes('whatever your error message is'));
```

to your test?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
