### ISSUE TITLE
Ads taking over the whole page

### ISSUE THREAD

**Issue by vladbondarenko97** [cypress-io/cypress#2332]
### Current behavior:
Currently we have a simple Cypress test where we load our page which contains ads. For some reason, Cypress lets the ads take over the whole page which breaks the whole website and test. See image below.

<img width="389" alt="screen shot 2018-08-13 at 1 05 46 pm" src="https://user-images.githubusercontent.com/12616782/44049514-f6e668b4-9ef9-11e8-9d33-a1c34f9c3e58.png">

This is similar to another issue that was closed:
https://github.com/cypress-io/cypress/issues/1403

However, the solution of blacklisting the ads is unacceptable because we want to assert that the ads are loading properly on the page.

**Comment by vladhq** [comment]
@jennifer-shehane we did that and the issue unfortunately still persists. The ads are taking over the page.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?
