### ISSUE TITLE
Cypress is not throwing exception or error message when wrong  “Event Types” are used

### ISSUE THREAD

**Issue by svadivel0006** [cypress-io/cypress#23328]
### Current behavior

**Issue:**

In the below screenshot, an incorrect “Event Type” such as “window:con” (not specified in the Cypress docs) is being used. Here the Cypress is not throwing any exception or error message while execution

**Screenshot:**

![EventTypes](https://user-images.githubusercontent.com/85741928/184477620-03f9f2aa-2cf0-4378-93e2-e529adf0c1fd.png)

### Desired behavior

Expections or Error messages should be displayed

### Test code to reproduce

cy.on('window:con', (str) =>
        {
            expect(str).to.equal('Hello , Are you sure you want to confirm?')
        })

### Cypress Version

10.4.0

### Node version

16.16.0

### Operating System

Windows 10 Pro

**Comment by AtofStryker** [comment]
Hi @svadivel0006. Thank you for opening an issue. We can't exactly lint event types, as they can be any string. However, you could use the following work around in your test if the event you expect isn't called:

```
it("runs the test", (done) => {
  cy.on("window:con", (str) => {
    expect(str).to.equal("Hello , Are you sure you want to confirm?");
    done();
  });
});

```
