### ISSUE TITLE
Unable to override `specPattern` using environment variables

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#23331]
### Current behavior

Overriding configuration values is possible using environment variables, EG. `CYPRESS_viewportHeight=100 cypress run`, but I can't override `specPattern` that way, IE. `CYPRESS_specPattern=foo cypress run` leaves me with a ` specPattern` as defined in `cypress.config.js`.

### Test code to reproduce

Open any Cypress any tests with `CYPRESS_specPattern=foo` and see that the resolved configuration does not contain `specPattern: "foo"`.

### Cypress Version

10.4.0

### Node version

18.7.0

### Operating System

Arch Linux

**Comment by AtofStryker** [comment]
Hey @badeball. Thank you for opening an issue. I put together a [reproduction repo](https://github.com/AtofStryker/cypress-issue-23331) that showcases how to do this. Have you tried using `CYPRESS_SPEC_PATTERN` instead of `CYPRESS_specPattern`?

**Comment by AtofStryker** [comment]
> Yeah, neither work.

@badeball have you tried the reproduction repository I have provided?

**Comment by badeball** [comment]
That did indeed work and it seems like it was fixed in 10.5.0! Sorry and please excuse me.

**Comment by AtofStryker** [comment]
No worries @badeball. I am just glad it it working for you 😄 !
