### ISSUE TITLE
Cypress opens x86 version of Google Chrome on M1 Mac 

### ISSUE THREAD

**Issue by noorsilkaredia1** [cypress-io/cypress#23335]
### Current behavior

Cypress is opening (x86_64 translated) version of Google Chrome even though native arm64 Chrome is installed. Browser loading and specs takes unusually longer and the browser window is very laggy.

Google Chrome installed on M1 mac
![Screen Shot 2022-08-14 at 3 54 13 PM](https://user-images.githubusercontent.com/58570333/184552723-7b470e69-62b2-4a42-bf21-7f6426324bab.png)

Chrome version used by Cypress 10.4
![Screen Shot 2022-08-14 at 3 50 36 PM](https://user-images.githubusercontent.com/58570333/184552752-4aa883af-166e-491c-bade-83af5d85375c.png)

Resolved config for Cypress has correct 'arch' info
<img width="311" alt="Screen Shot 2022-08-14 at 4 05 11 PM" src="https://user-images.githubusercontent.com/58570333/184553041-dddca431-a026-41e8-9e16-ff93e0a5642c.png">

### Desired behavior

Cypress should load correct Chrome build for M1 Mac which is "arm64"

### Test code to reproduce

- `npx cypress open`
- Click on Chrome
- Open Chrome settings and notice the build information

### Cypress Version

10.4.0

### Node version

14.20.0

### Operating System

macOS Monterey 12.5

**Comment by mike-plummer** [comment]
Hi @noorsilkaredia1 , sorry to hear you're having issues with using the arm64 version of Chrome from Cypress. It sounds like you may have both an x86 and arm64 version of Chrome installed, and Cypress is picking up the x86 version. Is this accurate?

We use app bundle identifiers as [documented here](https://docs.cypress.io/guides/references/troubleshooting#Mac) to identify the browsers you have installed, so is it possible the x86 version of Chrome is still lurking on your system? If you don't think the x86 version should be hanging around anymore you can check your [Cypress resolved configuration](https://docs.cypress.io/guides/references/configuration#Resolved-Configuration) which lists out every browser we were able to find and its location in the filesystem - this may tell you where the non-arm64 version is coming from.

As a workaround you should be able to use the `--browser` flag to tell Cypress the exact filepath to the browser executable you want to open with. More information on that is [available here](https://docs.cypress.io/guides/guides/command-line#cypress-run-browser-lt-browser-name-or-path-gt)

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
