### ISSUE TITLE
ReactJs Application - Type on datepicker control

### ISSUE THREAD

**Issue by anikumarcypress** [cypress-io/cypress#2334]
### Current behavior:
Default view:
![image](https://user-images.githubusercontent.com/42363536/44068565-a573f40c-9f48-11e8-99ad-342af1bffd16.png)
And code:
![image](https://user-images.githubusercontent.com/42363536/44121406-df753422-9fed-11e8-87cf-b14154957473.png)

After entering date by changing date to text:
![image](https://user-images.githubusercontent.com/42363536/44069105-4be20ed0-9f4b-11e8-9d0c-8127da72f447.png)

Code still sets value as blank:
![image](https://user-images.githubusercontent.com/42363536/44069120-57cc69e8-9f4b-11e8-858f-ff7ac83df265.png)

I am trying to set the value in datepicker field but cypress does not enter the data. I checked online and tried different options but still not working. I think below code is kind of work-around - I am looking for proper solution to handle datepicker in reactJS application.

With this code, enters the data but while submitting form, datepicker value resets.
```js
    cy
     .get('#datepickerDemo')
     .invoke('attr', 'type', 'text') // Cast
     .type('2020-06-15')
```

Same reset issue observed with below code:
```js
  cy
   .get('#datepickerDemo')
   .click()
  .then(input => {
    input[0].dispatchEvent(new Event('input', { bubbles: true }))
     input.val('2018-10-10')
   })
```

Also tried with tab..etc but nothing worked.

**I automated one complete feature but due to this date field, I am unable to use script as date field is required in the app. Please help.**

### Desired behavior:

Datepicker should accept user input.

### Steps to reproduce:

Provided screenshot and issue description.
Please let me know if you need more details.

### Versions
Using latest version 3.1.0
Windows 10, Chrome 68

**Comment by Tolsee** [comment]
There are ways we can actually provide value to input, but it seems we cannot trigger change event.

**Comment by jennifer-shehane** [comment]
@Tolsee You can always manually trigger a change event. See [docs here](https://on.cypress.io/trigger#Change-Event)

@anikumarcypress Did you try using `cy.type()` in the format specified for `type='date'` inputs [here](https://on.cypress.io/type#Date-Inputs)?

**Comment by jennifer-shehane** [comment]
Closing since no response given.

**Comment by pratik-domain** [comment]
I got it working using 
```
cy.get('input[type=date]').type('2019-08-07');
```
docs: https://docs.cypress.io/api/commands/type.html#Date-Inputs

**Comment by trainoasis** [comment]
Using react-datepicker and simple `.type()` doesnt work due to `onChange` firing prematurely with unfinished type and then date jumping to some random date recognized based on whatever was typed so far (not really random, I know, but still wrong). 

Any idea how we can trigger events without .type() ? 

For example, this also doesn't work: 

```
cy.get("input[id=from]")
              .trigger("focusin")
              .invoke("val", fromDateString)
              .trigger("input")
              .trigger("change")
              .trigger("focusout");
```

Not any other combination of these I've tried. In this last example, the value is reset to the default value that was in there onLoad after `focusout` ... 

Any idea how to resolve this?
