### ISSUE TITLE
cy.visit can not load page

### ISSUE THREAD

**Issue by minhui-foxtel** [cypress-io/cypress#23344]
### Current behavior

`cy.visit` can't not load page when run testing using `cypress run`.

What I've tried:

- Add an extra header `'Accept-Encoding': 'gzip, deflate, br'`. This can fix the issue that running by `cypress open`.
- Electron doesn't have the issue, but I encounter another issue in Electron.

The regions to access the web app are limited, my IP was whitelisted, I can access the web app by `cypress open`. I also wonder if the working way of network between `cypress run` and `cypress open` is the same or not?

### Desired behavior

`cy.visit` has the same behavior between `cypress run` and `cypress open`.
`cy.visit` has the same behavior between Chromium-based browsers and Electron.

### Test code to reproduce

Sorry, I can not provide the test code. Here's my logs, might be helpful.

<img width="1311" alt="1" src="https://user-images.githubusercontent.com/97143891/184619388-de95c4a5-9797-4ee0-8756-485da9b75292.png">

<img width="1309" alt="2" src="https://user-images.githubusercontent.com/97143891/184619201-a8f66942-bbad-4ca8-a261-a85d3c258db2.png">

### Cypress Version

10.4.0

### Node version

v14.19.0

### Operating System

macOS 12.2

**Comment by nagash77** [comment]
@minhui-foxtel Unfortunately we won't be able to do much without more detailed reproduction instructions.

**Comment by sosnowskijakub** [comment]
Hello I got the same problem on Cypress 10.6.0, IMO this problem occurs randomly because there is no pattern of when and with what parameters it's happens 
<img width="407" alt="Zrzut ekranu 2022-08-19 o 12 54 57" src="https://user-images.githubusercontent.com/48626087/185605669-6088f166-3753-4db4-afc3-2406a557e648.png">

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
