### ISSUE TITLE
@cypress/react18 does not properly rerender

### ISSUE THREAD

**Issue by hiebj** [cypress-io/cypress#23357]
### Current behavior

- The `rerender` function returned by `@cypress/react18` creates a new root on every render, forcibly recreating the component tree on rerender.
- The `rerender` functionality does not work (a mounted component's state can't be persisted from one render to the next).

### Desired behavior

- The `rerender` function returned by `@cypress/react18` should reuse the existing root if it has already been created but not yet cleaned up.
- The `rerender` functionality should work (a mounted component's state should be persisted from one render to the next).

### Test code to reproduce

The `rerender/input-accumulator` test from the adjacent `react` package fails. Also,

```ts
import React from 'react';

import { mount } from '@cypress/react18';

describe('rerender', () => {
  it('should persist state between rerender() calls', () => {
    mount(<StatefulComponent foo="baz" />).then(({ rerender }) => {
      cy.get('button').should('have.text', 'baz 0');
      cy.get('button').click().should('have.text', 'baz 1');
      rerender(<StatefulComponent foo="baz" />);
      cy.get('button').should('have.text', 'baz 1');
    });
  });
});

const StatefulComponent: React.FC<{ foo: string }> = ({ foo }) => {
  const [bar, setBar] = React.useState(0);
  return (
    <button
      onClick={() => {
        setBar(bar + 1);
      }}
    >
      {foo} {bar}
    </button>
  );
};

```

### Cypress Version

10.4.0

### Node version

v14.19.1

### Operating System

macOS 12.4

### Other

In the console, the following message is printed from React:

```
react-dom.development.js?61bb:86 Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.
```

I believe I know exactly what the issue is and how to fix it, I am creating this issue to accompany a PR.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23357?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
