### ISSUE TITLE
Issue running with electron and chrome : Issue:Passthrough is not supported, GL is disabled 

### ISSUE THREAD

**Issue by M-Jyothi** [cypress-io/cypress#23356]
### Current behavior

HI team recently while running my cypress code , I am not able to executed any test cases due to the below issue:

**[10600:0811/134826.439:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled,** need help asap .
The test cases where were executing in cypress no code was updated still getting this issue . 

### Desired behavior

It should not give this error 

### Test code to reproduce

[10600:0811/134826.439:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled,**

### Cypress Version

9.7

### Node version

9.7

### Operating System

windows 10

### Other

We have enabled webgl in chrome but still facing the issue

**Comment by mike-plummer** [comment]
Hi @M-Jyothi , I'm sorry to hear you're having trouble. It looks like this issue has been [previously reported](https://github.com/cypress-io/cypress/issues/22509). I would recommend you review the solutions presented in [this comment](https://github.com/cypress-io/cypress/issues/22509#issuecomment-1166057154).

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
