### ISSUE TITLE
10.5.0 - "Your supportFile is missing or invalid" even when hardcoded in the config

### ISSUE THREAD

**Issue by Abcmsaj** [cypress-io/cypress#23361]
### Current behavior

When we upgrade to Cypress 10.5.0 and run our E2E test suite through our pipelines, we get an error on each of docker containers:

> cypress_1  | Your project does not contain a default supportFile. We expect a file matching cypress/support/e2e.{js,jsx,ts,tsx} to exist.
> cypress_1  | 
> cypress_1  | If a support file is not necessary for your project, set supportFile to false.
> cypress_1  | 
> cypress_1  | https://on.cypress.io/support-file-missing-or-invalid

Even when we hardcode the location of the support file into the config, we get a similar error:

> cypress_2  | Your supportFile is missing or invalid: cypress/support/e2e.js
> cypress_2  | 
> cypress_2  | The supportFile must be a .js, .ts, .coffee file or be supported by your preprocessor plugin (if configured).
> cypress_2  | 
> cypress_2  | Fix your support file, or set supportFile to false if a support file is not necessary for your project.
> cypress_2  | 
> cypress_2  | If you have just renamed the extension of your supportFile, restart Cypress.
> cypress_2  | 
> cypress_2  | https://on.cypress.io/support-file-missing-or-invalid

When we downgrade to Cypress 10.4.0 - works again

### Desired behavior

Tests should just run as they did for 10.4.0

### Test code to reproduce

Not sure I can provide code - we didn't change anything. Initially, our configs did NOT have the supportFile location set

This is how our directory is structured - which is the default way, I believe:

![Screenshot 2022-08-16 at 10 51 49](https://user-images.githubusercontent.com/5143023/184851099-5f5f0897-2be3-4398-838b-f734c410a2dc.png)

### Cypress Version

10.5.0

### Node version

16.16.0

### Operating System

Docker - running the Cypress included image for 10.5.0

**Comment by esetnik** [comment]
@Abcmsaj I have the same issue. Downgrading to 10.4.0 for now.

**Comment by esetnik** [comment]
Possibly related to https://github.com/cypress-io/cypress/pull/22903

**Comment by emilyrohrbough** [comment]
@esetnik Is your root directory named `e2e`?

**Comment by esetnik** [comment]
> @esetnik / @Abcmsaj Is your root directory named `e2e`? We discovered a regression related to [this change](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/sources/FileDataSource.ts#L39) that we are working on a fix for.

yes it is. Thanks, i'll wait for an update.

**Comment by Abcmsaj** [comment]
> @esetnik / @Abcmsaj Is your root directory named `e2e`? We discovered a regression related to [this change](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/sources/FileDataSource.ts#L39) that we are working on a fix for.

Yeah it is, thanks Emily
