### ISSUE TITLE
Element fully covered by a sibling element is deemed "visible"

### ISSUE THREAD

**Issue by butlermd** [cypress-io/cypress#23373]
### Current behavior

Given two `position: absolute` elements that are siblings with different z-indexes, both are considered visible even though they overlap. 

### Desired behavior

Whichever element is under the other `should('not.be.visible')` and whichever is on top `should('be.visible')`.

### Test code to reproduce

https://github.com/butlermd/cypress-sibling-visibility-issue

### Cypress Version

Found in 8.1.0, confirmed in 10.5.0

### Node version

v16.16.0

### Operating System

macOs 12.5

### Debug Logs

```shell
I can add this if needed, but it doesn't seem relevant to this case.
```

### Other

This might be out of scope for Cypress.dom.isHidden/isVisible or there might just be a better way to assert it. But intuitively, I would think that those assertions would work here. Edit: it's worth noting, the above repo is a somewhat contrived and simplified example--the case that led to finding this uses animations to transition between states, which is why it's a swapping of z-indexes and not simply swapping display or visibility. 

Edit: clarifying cypress version

**Comment by mike-plummer** [comment]
Hi @butlermd , thanks for opening an issue! I believe what you're running into is that Cypress has a [very complex definition of "visible"](https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Visibility) that sometimes does not align with "currently in sight to a human looking at the screen". It can sometimes be helpful to think of "visible" as "could theoretically be interacted with by the user". In your example case, even though the second element is fully covered which prevents the user viewing or using the mouse on it they can use keyboard navigation to focus and type into those elements even though they're hidden from sight. It would likely be equally confusing in tests to say elements are "hidden" but still allow test logic to interact with them.

Hopefully this helps clear up the behavior you're seeing. I do recommend reviewing the [Cypress Core Concepts docs](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress), they have a ton of great info on how Cypress interacts and evaluates pages in tests.

**Comment by butlermd** [comment]
So then it sounds like the answer is essentially that this isn't possible to test using "be.visible" and an alternate method is going to be needed.
