### ISSUE TITLE
mousemove trigger with 0 position for x or y leads to unexpected behaviour

### ISSUE THREAD

**Issue by rooch84** [cypress-io/cypress#2338]
### Current behavior:

I'm trying to drag an object using the following: 
 ```js
 cy.get(".draggable-object")
      .first()
      .trigger("mousedown", x1, y1, { which: 1 })
      .trigger("mousemove", x2, y2, {
        which: 1,
        force: true
      })
      .trigger("mouseup", x2, y2, { force: true });
```

x1 and y1 are an offset so I mouse down on the handler.  x2 and y2 are the new position (plus the offset).   When x2 or y2 are 0, instead of moving to the top or left of the element, it moves to the centre of the element (the default behaviour if no x or y are specified). 

### Desired behavior:

0 for x2 or y2 should place the action at either the top or left of the element (not in the centre). 

### Steps to reproduce:

If you need a workable demo, let me know.

### Versions

Cypress 3.1.0
Windows 10

**Comment by chrisbreiding** [comment]
A demo would be appreciated. It'll be hard to debug without being able to reproduce the issue.

**Comment by rooch84** [comment]
Sorry, a bit rushed, but here it is... 

https://github.com/rooch84/cypress-trigger-issue

**Comment by sererejegede** [comment]
I'm a bit late to the party but this seems to have been forgotten...
