### ISSUE TITLE
'Cannot set property id of [object XMLHttpRequest] which has only a getter' when logging in to a Fiori UI5 application

### ISSUE THREAD

**Issue by lion9** [cypress-io/cypress#23395]
### Current behavior

When opening am SAPUI5 application at https://fiori-launchpad.com/fiori/mainapp/ClientBin?saml2=disabled#ZMyApp-Display white screen is shown and the error is printed out in the console:

```
Uncaught TypeError: Cannot set property id of [object XMLHttpRequest] which has only a getter
    at Server.add (cypress_runner.js:180017:12)
    at XHR.open [as _open] (cypress_runner.js:180160:28)

```

### Desired behavior

The runner is working smoothly, without crashing.

### Test code to reproduce

open an SAPUI5 application in Fiori Launchpad, and login, the application will not load

### Cypress Version

^10.3.0

### Node version

v14.17.6

### Operating System

12.5 (21G72)

**Comment by mike-plummer** [comment]
@lion9 The URL you provided in the issue does not resolve for me - is it possible it is internal to your company? I found a few other SAPUI5 applications that are publicly accessible on the web but I am not able to reproduce the issue you describe when loading them in Cypress.

Please provide a publicly-accessible, reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
