### ISSUE TITLE
3014 has a problem when Device exit CY_U3P_USB_EVENT_SUSPEND

### ISSUE THREAD

**Issue by ShaonWhite** [cypress-io/cypress#23396]
### Current behavior

    I 'm a employee of a Industrial Camera company. Last Month, our customer told me that our cameras has a bug. The operation to reproduct bug is listed below:
Connect the camera with NVIDIA TX2, then power on the TX2. Our camera will finish initialization before the TX2 finish initialization. So our camera will enter the CY_U3P_USB_EVENT_SUSPEND. After TX2 finish initialization, our camera should exit CY_U3P_USB_EVENT_SUSPEND and can be enumerated.However, our camera sometime can't archieve this action. Instead of exit CY_U3P_USB_EVENT_SUSPEND successfully, they stay in CY_U3P_USB_EVENT_SUSPEND. 
      I deleted the code about CY_U3P_USB_EVENT_SUSPEND to make camera ignore the command of entering CY_U3P_USB_EVENT_SUSPEND. After this operation, the camera can always be enumerated after the TX2 finish initialization. But I found the ubuntu18.04 of TX2 reported an error(“Maybe the USB cable is bad”) and I found the camera was enumerated as a USB2 camera(It should be enumerated as a USB3.0 camera). 
![IMG_0395](https://user-images.githubusercontent.com/48310776/185073070-c94f1094-41d2-4bb1-8fff-4b50d73c937c.jpg)

### Desired behavior

In this situation(Connect the camera with NVIDIA TX2, then power on the TX2), we hope that camera can enter/exit CY_U3P_USB_EVENT_SUSPEND successfully, and the camera can be enumerated correctly(When the camera connected with a USB3 port, it should be enumerated as a USB3 camera.)

### Test code to reproduce

[code.zip](https://github.com/cypress-io/cypress/files/9357858/code.zip)

### Cypress Version

SDK version is 1.3.1

### Node version

I did not use node.js

### Operating System

ubuntu 18.04

**Comment by mjhenkes** [comment]
@ShaonWhite I believe you may have the wrong github repo. Maybe you want this one? https://github.com/nickdademo/cypress-fx3-sdk-linux

**Comment by ShaonWhite** [comment]
Well, thank you for your advice. I 'll take a try.
