### ISSUE TITLE
Improve how snapshots handle iframes

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#234]
Currently, iframes are removed from snapshots, which is necessary because we don't want any requests made when restoring a snapshot. The problem is that the space taken up by the iframe is now empty, so the layout of the snapshot is not right. Whatever was below the iframe is now higher up in the place the iframe used to occupy. 

Solution:

When creating a snapshot, iterate through any iframes on the page and grab their box model properties and url. In their place, put a div with the same box model properties and labeled with the url. Style it like a "missing image" placeholder.

**Comment by brian-mann** [comment]
Fixed in [`0.17.5`](https://github.com/cypress-io/cypress/wiki/Changelog#0175-10022016).
