### ISSUE TITLE
Flaky test: 'by doing both' test in net_stubbing

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23407]
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/runs/38081/test-results/90257a8a-9a0d-4430-8aad-55848448eb85

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/net_stubbing.cy.ts#L1814

### Analysis

<img width="448" alt="Screen Shot 2022-08-17 at 1 03 36 PM" src="https://user-images.githubusercontent.com/26726429/185232254-1f7e748e-604d-4b0b-8955-6f3bc7c8f2d9.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
