### ISSUE TITLE
DevServer: Allow a way to tell where the next.config.js is located

### ISSUE THREAD

**Issue by bryanjos** [cypress-io/cypress#23405]
### What would you like?

Hi, we're upgrading from Cypress 8.3.0 to Cypress 10.4.0 and are running into an issue migrating the component tests and replacing `startDevServer` with the new `devSever` configuration.

We have a monorepo set up like so:

```
/
  /packages
    /app <-- nextjs 12 app
    /shared <-- the next.config.js file lives here
    /e2e <-- where our cypress tests live 
```

With the old version of `@cypress/webpack-dev-server` we could load the next.js config, get the webpack config and pass that into `startServer`.

We haven't found a way to migrate to the new way of starting a dev server in Cypress 10.

[Looking at the docs](https://docs.cypress.io/guides/component-testing/component-framework-configuration#Next-js), we tried to do:

```typescript
export default defineConfig({
  component: {
    devServer: {
      framework: 'next',
      bundler: 'webpack',
    },
  },
})
``` 

But when running our tests, we see errors about syntax that should have been transpiled in our webpack configuration for next.

We also tried doing a custom setup and passing in the webpack config like we did with `startDevServer`, but end up getting the error in the screenshoot below:

```typescript
          return devServer({
            ...devServerConfig,
            webpackConfig,
          });
```

<img width="905" alt="Screen Shot 2022-08-17 at 1 12 54 PM" src="https://user-images.githubusercontent.com/1257573/185212412-1110a9eb-a2ed-4457-a9ed-7c019b46e375.png">

So the last thing we tried was explicitly setting the path in [this line in `@cypress/webpack-dev-server`](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/helpers/nextHandler.ts#L56) and everything works as expected.

Obviously that's not a valid solution, but I think it's a hint to a way forward.

### Why is this needed?

So that with custom next.js set ups like ours, we can give a hint to the devServer a to where the next.config.js is located. 

Something like this maybe:

```typescript
// check to see if a path was given, if not default to projectRoot
const nextConfig = await loadConfig('development', devServerConfig.nextConfigPath || devServerConfig.cypressConfig.projectRoot);
```

Apologies in advance if this is something already possible or there is a change to passing in the webpackConfig that we aren't getting.

### Other

cypress: 10.4.0
@cypress/webpack-dev-server: 2.0.0
webpack: 5.72.0
next: 12.1.2

**Comment by mike-plummer** [comment]
Hi @bryanjos , thanks for opening this issue and for doing so much investigation! This is a really interesting use case that we hadn't considered, so you are correct there is not currently an out-of-the-box way to provide a custom location for a `next.config.js` file that isn't at your project root. I think it would be a good idea to support this, but I think we (Cypress team) are going to want to think about whether there's a way to do this in a way that doesn't customize parts of our API to be NextJS-specific if they don't have to be.

In the short term I can think of a couple options that might work:

1. Refactor your app/e2e directory structure

Not a great solution, I know 😁 . I would be very interested in understanding the benefits your project is trying to achieve by structuring your app in this way (separating your component tests from the project itself) so we have good context to ensure we get this solved in the future.

2. Duplicate your `next.config.js` file

Probably the easiest solution, just duplicate your config file at the Cypress project root. Obviously some duplication and maintenance issues here but should get you up and running.

2. `@cypress/webpack-preprocessor`

I think you may be able to accomplish what you want by using this package which allows you to intercept and customize the generated webpack config by hooking into the Cypress event stream in your `cypress.config.js` file. If all you need is to tweak a resolve rule or add some aliases this might be enough to get the job done, but not nearly as nice as just enabling custom config resolution to begin with

Rough example:

```
component: {
    setupNodeEvents(on, config) {
      on(
        'file:preprocessor',
        webpackPreprocessor({
          webpackOptions: resolveMyWebpackConfigsFromNext()
        })
      )
    },
    devServer: {
      framework: "next",
      bundler: "webpack",
    },
  },
```

**Comment by bryanjos** [comment]
Hey @mike-plummer thanks for the response and the insights! We'll do some work and see if any of those options are viable for us. 

Thanks again!

**Comment by mike-plummer** [comment]
@bryanjos One of my teammates just informed me that the `file:preprocessor` hook I pointed you to actually won't expose the component testing webpack configs I was hoping for, so not a viable solution 😢 

He did point me to the [`webpackConfig` field in the `devServer` config object](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/devServer.ts#L26) - this should give you the ability to provide webpack config customizations that [get merged in once the framework config is resolved](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/makeWebpackConfig.ts#L83).

Sorry for the bad lead!

**Comment by bryanjos** [comment]
@mike-plummer no problem. We actually have tried passing in the webpackConfig and that's where we were getting the error the `this.compiler.InfrastructureCompiler is not a function` What we passed in is pretty much what's [returned here](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/helpers/nextHandler.ts#L53-L75). But maybe that's not what it's expecting there?

**Comment by mike-plummer** [comment]
@bryanjos I apologize, I misunderstood where you were doing your custom dev server setup in that portion of your original explanation. What you were doing there should work (and you might even be able to simplify it a bit by just building and returning the devServer config object rather than building calling the `devServer` function yourself, but that's a separate issue). A quick googling of the "this.compiler.getInfrastructureLogger" seems to indicate a potential [dependency conflict involving multiple versions of webpack in the workspace](https://github.com/webpack/webpack/issues/9553), but I can't confirm whether that's the issue you ran into (that info might be in the rest of the stacktrace that was cut off from that screenshot). Any chance you're pulling in an older version of `webpack-dev-server` or `webpack` in your dependencies that might be incompatible with the versions used by the cypress package?

**Comment by bryanjos** [comment]
That could be it between what's in cypress, our project, and next itself. I'll take a look and see if setting that straight helps.

**Comment by lmiller1990** [comment]
Another alternative we might consider down the track if this comes up a lot would be:

```js
export default defineConfig({
  component: {
    devServer: {
      framework: 'next',
      options: {
        nextJsConfig: '/path/to/config'   
      }
    }
  }
})
```

Just an idea.
