### ISSUE TITLE
it.skip not working in Angular component test

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#23409]
### Current behavior

```
import { StepperComponent } from './stepper.component'

describe('StepperComponent', () => {
  it.skip('mounts', () => {
    cy.mount(StepperComponent)
    cy.contains('[data-cy=stepper]', 'works')
  })

  it('mounts using a template', () => {
    cy.mount(`<app-stepper data-cy=mounted [count]="101"></app-stepper>`, {
      declarations: [StepperComponent],
    }).then(console.log)
  })
})
```
<img width="986" alt="Screen Shot 2022-08-17 at 17 10 47" src="https://user-images.githubusercontent.com/2212006/185244105-10d1784a-e80c-484f-87e0-f3cd5ce05d8e.png">

Workaround: use `xit` instead of `it.skip` and it skips it

### Desired behavior

`it.skip` should work :)

### Test code to reproduce

Following https://docs.cypress.io/guides/component-testing/quickstart-angular in Cypress v10.6.0
package.json file

```json
{
  "name": "test-angular-component",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.1.0",
    "@angular/common": "^14.1.0",
    "@angular/compiler": "^14.1.0",
    "@angular/core": "^14.1.0",
    "@angular/forms": "^14.1.0",
    "@angular/platform-browser": "^14.1.0",
    "@angular/platform-browser-dynamic": "^14.1.0",
    "@angular/router": "^14.1.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.1.3",
    "@angular/cli": "~14.1.3",
    "@angular/compiler-cli": "^14.1.0",
    "@types/jasmine": "~4.0.0",
    "cypress": "^10.6.0",
    "jasmine-core": "~4.2.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "prettier": "^2.7.1",
    "typescript": "~4.7.2"
  }
}
```

### Cypress Version

10.6.0

### Node version

16

### Operating System

mac

**Comment by nickAdlard** [comment]
this is repro in `e2e` tests, `skip` no worky.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23409?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
I think the problem is `zone.js` is overriding `it` and not re-applying the `skip` property. I could be wrong - but this would explain why it's an Angular only problem, and also why it manifests in both E2E and CT if you are using Angular.

**Comment by ZachJW34** [comment]
The mocha overrides comes from `zone.js/testing`, which (to my knowledge) is only included in CT tests.

@nickAdlard if you are seeing an issue with Angular e2e, do you mind creating another issue with a reproduction so we can dig into what's going on?
