### ISSUE TITLE
Flaky test: shows offline alert then hides it after coming online

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23419]
### Link to dashboard or CircleCI failure

[CircleCI](https://app.circleci.com/pipelines/github/cypress-io/cypress/42125/workflows/d134eb62-4b9b-4fdc-a4cf-0dc558f61418/jobs/1747767/tests) and [dashboard](https://dashboard.cypress.io/projects/sehy69/runs/14714/test-results/bb6fc963-c531-44cb-b34c-1cc029b3a250) 

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/specs_list_latest_runs.cy.ts#L624

### Analysis

<img width="1076" alt="Screen Shot 2022-08-18 at 12 18 41 AM" src="https://user-images.githubusercontent.com/26726429/185333933-44dd6e3c-e55d-4758-b81a-f724c2328e8c.png">

<img width="446" alt="Screen Shot 2022-08-18 at 12 19 00 AM" src="https://user-images.githubusercontent.com/26726429/185333982-befc8485-b911-4f8d-ba65-c4ffdf46be1e.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
