### ISSUE TITLE
Flaky test: Port 4445 is already in use

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23418]
### Link to dashboard or CircleCI failure

All the "Choose a browser" tests failed in this run:

[Dashboard](https://dashboard.cypress.io/projects/sehy69/runs/14713/test-results/1f71f240-0299-4240-b5a4-ba61c0271c85) and [CircleCI](https://app.circleci.com/pipelines/github/cypress-io/cypress/42123/workflows/7d0adb1e-7cf9-4ce1-a5c6-36d8fd6c0dc0/jobs/1747717/tests)

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/launchpad/cypress/e2e/project-setup.cy.ts#L658

### Analysis

Looks like the port is already in use

<img width="1497" alt="Screen Shot 2022-08-17 at 11 47 51 PM" src="https://user-images.githubusercontent.com/26726429/185317691-b951eef1-b2df-4081-8c49-7436e44cf6e7.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by flotwig** [comment]
Looked at this as part of #25671 - the test is flaky, but we can't apply retries to it, because it fails after the first failure every time with "port in use 4455". Seems like a failure in cleanup in addition to the flake.
