### ISSUE TITLE
Flaky test: hide test duration for percySnapshot in screenshot.cy.tsx

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23424]
### Link to dashboard or CircleCI failure

[Percy dashboard](https://percy.io/cypress-io/cypress/builds/20715750/changed/1160143856?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=800%2C1280)

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/app/src/runner/screenshot/screenshot.cy.tsx#L56

### Analysis

Unfortunately this one is not as simple as adding the test duration element to the percy `elementOverrides`; perhaps related to the `removeGlobalStyles` function just before the snapshot

<img width="1711" alt="Screen_Shot_2022-08-18_at_1_43_17_AM" src="https://user-images.githubusercontent.com/26726429/185351942-fab4e91d-f6ad-46ca-bc5b-bc9885e1a112.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
