### ISSUE TITLE
Flaky test: net_stubbing define property

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23423]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/42129/workflows/c8932e30-c0eb-44cf-8772-795dfd311df0/jobs/1747987/tests

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/net_stubbing.cy.ts#L1913

### Analysis

<img width="1431" alt="Screen Shot 2022-08-18 at 1 39 21 AM" src="https://user-images.githubusercontent.com/26726429/185350900-c4332994-7f27-412f-b7c5-7f4fd2dde0cd.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
