### ISSUE TITLE
Flaky test: intercept log has consoleProps with intercept info

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23420]
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/runs/38109/test-results/c03474aa-51a8-4d9e-b9c9-d135446317bd

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cypress/proxy-logging.cy.ts#L268

### Analysis

<img width="459" alt="Screen Shot 2022-08-18 at 12 26 06 AM" src="https://user-images.githubusercontent.com/26726429/185335318-d1be49d6-a27c-40ac-b364-b025ab10d534.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by flotwig** [comment]
Fixed in https://github.com/cypress-io/cypress/pull/24124
