### ISSUE TITLE
Flaky test: can add a body to a request that does not have one

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23422]
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/runs/38111/test-results/602c694e-8827-4f36-86b5-3055b7908e6f?utm_source=github&isFlaky=%5B%7B%22value%22%3Atrue%2C%22label%22%3A%22Flaky%22%7D%5D

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/net_stubbing.cy.ts#L1633

### Analysis

<img width="446" alt="Screen Shot 2022-08-18 at 1 10 04 AM" src="https://user-images.githubusercontent.com/26726429/185344393-151f5bff-f3a5-4718-ab3c-eb4919c1ed7b.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
