### ISSUE TITLE
Updated specs list search in 10.6 is not working with forward slash

### ISSUE THREAD

**Issue by Deop** [cypress-io/cypress#23426]
### Current behavior

In 10.6 specs list search was updated to work file path. While it is working now if path contains back slash, it does NOT work with forward slashes in the path. For example if I copy file path from IntelliJ (on Windows) it copies it with forward slashes, so I can't just copy-paste file path but need to modify it with forward slashes

### Desired behavior

Specs list search works with both forward or back slashes

### Test code to reproduce

Just try search for files with path containing forward slash
![image](https://user-images.githubusercontent.com/7953144/185376386-d60fb2f5-97ae-48a8-bb98-506bc4575e44.png)
![image](https://user-images.githubusercontent.com/7953144/185376411-64151ffa-3229-4290-9cee-8552eb7016e0.png)

### Cypress Version

10.6.0

### Node version

16.7.0

### Operating System

Windows 10

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23426?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
We should just normalize all slashes to be the same (say `/` since we generally use posix everywhere else to avoid this problem).

**Comment by marktnoonan** [comment]
@lmiller1990 I agree, though for specs in particular we do _not_ normalize paths on the client as far as I recall. Without digging in more, on Windows, we could still replace `/` with `\` when used in searches. Though I'd prefer normalized paths for sure.
