### ISSUE TITLE
type should accept empty strings

### ISSUE THREAD

**Issue by wbolduc** [cypress-io/cypress#23428]
### What would you like?

I would like cy.type to allow input of empty strings.

if type is passed an empty string it just wont do anything

### Why is this needed?

We test our ui by inputting and submitting data from a list of valid data and intercepting the api

Some of our inputs accept empty strings and therefore our sample data for that field may be an empty string.
A really trivial example of sample data is as follows
`
[
  {
    custom_id: "My special id"
  },
  {
    custom_id: ""
  }
]
`

The problem with type is that in order to avoid
"cy.type() cannot accept an empty string. You need to actually type something."
with the above sample data I need to write the awkward
`
if(sample.custom_id) cy.find('[name="Custom id"]').type(sample.custom_id)
`

would be much nicer to just not have that limitation or have a way to disable it

### Other

This could be a config option or a flag on the type function

**Comment by mike-plummer** [comment]
Hi @wbolduc , thanks for opening an issue! The `type` command is designed as a mutation and, as such, if it receives an empty string it is almost certainly an error in the test logic and we want to surface that error as quickly as possible. It sounds like your use case might be better solved by making some tweaks in your project - here's a couple ideas:

1. Replace the empty strings in your test data with a type string that will be an effective no-op such as `"{backspace}"`
2. Write a [custom command](https://docs.cypress.io/api/cypress-api/custom-commands#Syntax) that implements the behavior you're looking for. You could hypothetically even [overwrite the built-in `type` command](https://docs.cypress.io/api/cypress-api/custom-commands#Overwrite-Existing-Commands) so you don't have to change your tests

**Comment by nagash77** [comment]
Adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
