### ISSUE TITLE
Flaky test: catch-all for net_stubbing flake

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23434]
### Link to dashboard or CircleCI failure

1. [empty string](https://dashboard.cypress.io/projects/ypt4pf/runs/38126/test-results/9c238974-bdf1-4ea1-9d5b-fcba767840b7)
2. UPDATE: ended up just skipping the whole file

### Link to failing test in GitHub

See skipped flaky tests in [packages/driver/cypress/e2e/commands/net_stubbing.cy.ts](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/net_stubbing.cy.ts)

### Analysis

We see A LOT of flake originating from tests in `net_stubbing.cy.ts`. Many have been individually logged and have the label `topic: net_stubbing.cy.ts`, the remainder will be logged under this catch-all issue.

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by rockhold** [comment]
Of the various flaky test issues that have been recently logged, these net_stubbing issues are some of the higher priority ones to address. Broadly within our community-reported issues, however, this seems lower. Marking as medium priority for now.

**Comment by emilyrohrbough** [comment]
@rachelruderman what were the common failures that needed to turn all of these off?

**Comment by rachelruderman** [comment]
> @rachelruderman what were the common failures that needed to turn all of these off?

Hi @emilyrohrbough ! [Here are the issues I logged before creating this catch-all issue](https://github.com/cypress-io/cypress/issues?q=is%3Aopen+label%3A%22topic%3A+net_stubbing.cy.ts%22+sort%3Aupdated-desc). It's not an exhaustive list -- after these skips, this file continued to flake randomly, ultimately resulting in the decision to skip the whole file, but the failures were all variations of `expected '<html><body>it worked!<br>request body:<br>{"quuz":""}</body></html>' to include '{"foo":"bar"}'`. The other issues all have CircleCI or dashboard links you can click into

Btw @flotwig hit me up earlier today about increasing retries for flaky tests (i.e. 10 instead of 2) instead of skipping them altogether, in light of a `cy.intercept` regression that slipped into 10.7.0 due to the skipped flaky tests. IMO it's an excellent idea and would help us keep our test coverage and maintain confidence in CI while we investigate the flake. This file is def a good candidate for that approach
