### ISSUE TITLE
Svelte Mount Support + dev-server integration

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#23431]
### What would you like?

New library for supporting Svelte component testing in `npm/svelte` and integration of Svelte into our webpack/vite-dev-server

### Why is this needed?

To support Cypress Svelte Component Testing

### Other

[Existing PR](https://github.com/cypress-io/cypress/pull/22862) for Svelte CT integration.

The implementation will depend upon https://github.com/cypress-io/cypress/issues/23429 where a spike outlining the Svelte mounting API will be defined.

Requirements:

- New `npm/svelte` package
- System tests for the `mount` API
- System tests for a webpack and vite based Svelte project

Note: This does not include `SvelteKit` support

**Comment by mike-plummer** [comment]
Completed in #23519
