### ISSUE TITLE
Svelte CT setup

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#23432]
### What would you like?

Svelte apps should be autodetected during CT setup and scaffolded with Svelte specific files

### Why is this needed?

To support Svelte Component Testing

### Other

The flow should be similar to how we detect/scaffold other frameworks for CT support:

![Screen Shot 2022-08-18 at 10 32 06 AM](https://user-images.githubusercontent.com/25158820/185435240-ad627b4d-994d-4c71-a864-343a025cfb00.png)

Requirements:

- Autodetects Svelte during CT setup
- Lists required dependencies
- Scaffolds Svelte specific CT files
- System tests verifying Svelte setup flow

**Comment by mike-plummer** [comment]
Completed in #23441
