### ISSUE TITLE
Flaky test: <Tooltip/> in Percy snapshots

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23436]
### Link to dashboard or CircleCI failure

[Percy dashboard](https://percy.io/cypress-io/cypress/builds/20730990/changed/1160812364?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1000&widths=800%2C1000%2C1200%2C1280%2C1500)

### Link to failing test in GitHub

Anywhere a Percy snapshot is taken with the `<Tooltip>` component, i.e. https://github.com/cypress-io/cypress/blob/develop/packages/frontend-shared/src/gql-components/HeaderBarContent.cy.tsx#L56

### Analysis

The tooltip sometimes disappears before Percy takes the snapshot, causing visual testing flake. We need to find a way to force it to stay open 

<img width="1162" alt="Screen Shot 2022-08-18 at 9 30 34 AM" src="https://user-images.githubusercontent.com/26726429/185447109-b6d290b7-9c4f-4cc5-8e65-069dde269fee.png">

### Cypress Version

10.6.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
