### ISSUE TITLE
Flaky test: catch-all issue for 'expecting an array or an iterable object but got [object Null]'

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23444]
### Link to dashboard or CircleCI failure
This failure has shown up for in a couple different cookies tests. All of the tests in question use `cy.setCookie` so I think that is likely the culprit. See cookie-related failures in this test run https://dashboard.cypress.io/projects/ypt4pf/runs/38138

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/cookies.cy.js#L73

### Analysis
<img width="617" alt="Screen Shot 2022-08-26 at 8 10 02 PM" src="https://user-images.githubusercontent.com/26726429/187012107-224b1c7b-8873-4a13-892f-4c5f62a7a702.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by chrisbreiding** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/23442
