### ISSUE TITLE
Flaky test: fetch log shows resource type, url, method, and status code and has expected snapshots and consoleProps

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23443]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/42164/workflows/11546f95-7c07-4094-91ce-a2488eb96281/jobs/1749488

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cypress/proxy-logging.cy.ts#L49

### Analysis

<img width="1428" alt="Screen Shot 2022-08-18 at 2 09 09 PM" src="https://user-images.githubusercontent.com/26726429/185495413-61f0899f-d6fe-47b6-8a7c-2f31420486ed.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by flotwig** [comment]
Fixed in https://github.com/cypress-io/cypress/pull/24124
