### ISSUE TITLE
Flaky test: AssertionError: Timed out retrying after 20000ms: Expected not to find content: 'Your tests are loading...' but continuously found it.

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23455]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/42194/workflows/aaaac972-2250-4490-9c70-b06dac2dcf0d/jobs/1751106

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/cypress/e2e/nuxt.cy.ts#L52

### Analysis

<img width="1235" alt="Screen Shot 2022-08-18 at 11 51 52 PM" src="https://user-images.githubusercontent.com/26726429/185560803-ea577634-5190-4db4-9f86-2f919fe26121.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
