### ISSUE TITLE
drag and drop via mousedown and mouseup doesn't seem to work? 

### ISSUE THREAD

**Issue by reallyusefulengine** [cypress-io/cypress#23450]
### Current behavior

On the following website there is a calendar that requires the user to click on a date and drag the mouse to the day they want to book to.  However the mouse down via trigger doesn't seem to work with this calendar.

### Desired behavior

Im able to select a date range via mousedown and mouseup.

### Test code to reproduce
```js
it.only("should be able to select dates", () => {
        cy.visit("https://automationintesting.online")
        cy.contains("Book this room").eq(0).click()
        cy.get(".rbc-now").children().then((res)=> {
            let today = res[0].textContent
            console.log(typeof today);
            cy.get('.rbc-button-link').eq(0).trigger('mouseover').trigger('mousedown', 'center')
            cy.wait(500)
            cy.get('.rbc-button-link').eq(3).trigger('mousemove').trigger('mouseup','center')
        })
```
### Cypress Version

Cypress package version: 10.6.0 Cypress binary version: 10.6.0 Electron version: 19.0.8 Bundled Node version: 16.14.2

### Node version

18.7.0

### Operating System

Mac OS m1 12.5

**Comment by rachelruderman** [comment]
Hi @reallyusefulengine , great GitHub handle 😸 I'm sorry to hear you're having issues. Have you tried the [cypress-drag-drop](https://www.npmjs.com/package/@4tw/cypress-drag-drop) package?

**Comment by reallyusefulengine** [comment]
Thanks Rachel.  I did try that I think: ```"@4tw/cypress-drag-drop": "^2.2.1",```
That didn't work, maybe I was using it incorrectly? Nothing seems to work with mouse events on that calendar.  Manually doing it is fine though.

**Comment by rachelruderman** [comment]
Oooh this is a toughie! I was able to get `"@4tw/cypress-drag-drop": "^2.2.1"` kind of working _sometimes_, but even then the behavior wasn't exactly what I was expecting to see -- I was able to see the selection, but not the selections I wanted 😅 

```
  it.only("should be able to select dates", () => {
    cy.visit("https://automationintesting.online")
    cy.contains("Book this room").eq(0).click()
    cy.get('.rbc-date-cell:not(".rbc-off-range")').eq(1).drag('.rbc-date-cell:not(".rbc-off-range"):nth(20)')
  })
```

Are you able to share the JS logic for the calendar? I wonder exactly what the events are that are being bound to the date cells 🤔

**Comment by reallyusefulengine** [comment]
I don't own the code, but it was for an automation challenge.  Do you think the issues are do to the calendar being poorly implemented?

**Comment by rachelruderman** [comment]
Hmmm I wouldn't say it's an issue with the calendar being poorly implemented given that the calendar works deterministically -- I didn't notice any unexpected behavior with it. That said, testing and developing often go hand-in-hand. Being able to add data attributes to easily target specific date cells and knowing exactly what events the date cells are listening for would help loads in finding the proper approach to test it

**Comment by reallyusefulengine** [comment]
There is an event on the button element but i tried that and i couldnt get that working

**Comment by SharrocksDA** [comment]
Have you tried cypress-real-events? This is the only thing that would work for me to drag and drop: https://www.npmjs.com/package/cypress-real-events

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
