### ISSUE TITLE
Flaky test: Permission denied to access property "addEventListener" on cross-origin object

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23451]
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/analytics/flaky-tests/b39bfe08-f947-620f-90b4-a6ed76d46bf8-4f6c827e-8383-89e6-ec1a-35fcf34abd14?branches=%5B%7B%22label%22%3A%22skip-or-fix-flaky-tests-2%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22skip-or-fix-flaky-tests-2%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222022-08-18%22%2C%22endDate%22%3A%222022-08-19%22%7D&viewBy=TEST_CASE

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/e2e/origin/validation.cy.ts#L210

### Analysis

<img width="426" alt="Screen Shot 2022-08-18 at 10 53 54 PM" src="https://user-images.githubusercontent.com/26726429/185552383-88db8e21-b61d-4d6a-86bc-88618c13aa75.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by nagash77** [comment]
i want to verify if this is still an issue post Cy12

**Comment by flotwig** [comment]
Looked at this as part of #25671 - seems like this test is persistently failing now. I'm not sure if this is a test issue or a real bug.

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
