### ISSUE TITLE
Flaky test: AssertionError: Timed out retrying after 4000ms: Expected to find content: '/(a few|[0-9]) seconds? ago/' within the element: <div.h-full.grid.grid-col-1.git-info-row.justify-start.items-center> but never did.

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23474]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/42258/workflows/bec5f1bd-84fa-46cd-95ad-e7061cdc20e3/jobs/1754508

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/specs_list_no_git_repo.cy.ts#L9

### Analysis

<img width="1424" alt="Screen Shot 2022-08-19 at 2 30 20 PM" src="https://user-images.githubusercontent.com/26726429/185709859-6c1e6fe8-3407-4ae5-a164-8c8cde1a31f2.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by marktnoonan** [comment]
Just a note for future folks who might pick this up. I bumped into this skipped test and was curious about the flake, I ran it 20 times on my mac just now and it passed every time. Since the failure linked is on Windows, I'm going to guess this is flaky due to specific issues running Cypress on Windows (maybe just speed) and would need to be reproduced there to fix.

**Comment by flotwig** [comment]
> Since the failure linked is on Windows, I'm going to guess this is flaky due to specific issues running Cypress on Windows (maybe just speed) and would need to be reproduced there to fix.

@marktnoonan ~coincidentally~ I was just looking at this for #25671 - I ran this 100x in Windows and it passed every time. gonna try unskipping it... :crossed_fingers:

**Comment by marktnoonan** [comment]
Oh nice @flotwig. I am unskipping a bunch of things to see what is still failing, it looks like there are at least a couple tests we can turn back on, and a few that have gotten super stale and need full rewrites (eg referencing UI that doesn't exist any more).

What I'm really looking for is anything we turned off as "flaky" that is now "100% failing" which would represent a new bug.

**Comment by flotwig** [comment]
Seems like it still fails in CI persistently, so never mind :/
