### ISSUE TITLE
Flaky test: The application redirected to http://localhost:3500/fixtures/redirection-loop-b.html more than 20 times

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23472]
### Link to dashboard or CircleCI failure

https://dashboard.cypress.io/projects/ypt4pf/runs/0e2e50f0-e1fa-41c8-bbf0-a8ec0bd01217/test-results/a552eddc-9a8b-4018-86ac-e73239fe9e8d

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/navigation.cy.js#L738

### Analysis

It could just be a matter of bumping our `redirectionLimit`. However, there's also a chance this is an intended error from an earlier test bleeding into a subsequent test. For the time being, I've skipped the earlier test to see if that helps. I think this may be the case because the earlier test is testing the redirection loop and expects to find the error we saw here.

<img width="442" alt="Screen Shot 2022-08-19 at 1 15 10 PM" src="https://user-images.githubusercontent.com/26726429/185700104-c19ecad6-4c9b-4316-8178-fb7624e517dd.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by mjhenkes** [comment]
Fixing this with #23297

I limit the number of times the test page can redirect to 21 using local storage.
