### ISSUE TITLE
Feature : Scenario Recorder

### ISSUE THREAD

**Issue by ssavajols** [cypress-io/cypress#2347]
### Feature

Some recorder exist with selenium which avoids writing manuel tests. It could be really great if cypress have a recorder or recorder compatibility with katalon for example.

### Current behavior:

No recorder provided

### Desired behavior:

Record scenarios with katalon, selenium IDE, or something like that.

**Comment by jennifer-shehane** [comment]
Thanks, we agree. 😄 This feature is requested here: https://github.com/cypress-io/cypress/issues/73
