### ISSUE TITLE
Cypress UI no longer displays spec files to run

### ISSUE THREAD

**Issue by NUlmerTS** [cypress-io/cypress#23486]
### Current behavior

From version 10.5.0 onwards, the specs section no longer displays any specs in the file.
![image](https://user-images.githubusercontent.com/89112159/185836821-d3eebfee-a8c7-43d6-b602-df09ca50253e.png)

However, when reviewing the project settings spec patterns, nine files can be found
![image](https://user-images.githubusercontent.com/89112159/185836878-389ddc0e-a9b8-4121-a8d3-6cc02cd743ec.png)

It should be noted that when the tests are run in headless mode, they continue to work as expected.

The current workaround is to downgrade to 10.4.0.

### Desired behavior

After opening the cypress to use the UI format.  Then selecting a  browser types the spec files should display.

![image](https://user-images.githubusercontent.com/89112159/185837905-8844ad0a-96ae-4b23-b812-07e638852a7d.png)

### Test code to reproduce

const { defineConfig } = require('cypress')

module.exports = defineConfig({
  projectId: 'f2y8fb',
  chromeWebSecurity: false,
  responseTimeout: 60000,
  blockHosts: '*.parsely.com',
  pageLoadTimeout: 90000,
  e2e: {
    setupNodeEvents(on, config) {
      require("cypress-grep/src/plugin")(config);
    },
    baseUrl: 'https://www.teachstarter.com/',
    //baseUrl: 'https://staging-prexit.teachstarter.com/',
    specPattern: 'cypress/e2e/teachStarterWeb/**/*.{js,jsx,ts,tsx,spec}',
  },

### Cypress Version

10.5.0

### Node version

v14.17.5

### Operating System

Windows 11:22000.856

### Debug Logs

```shell
No logs displayed
```

**Comment by lmiller1990** [comment]
Same as https://github.com/cypress-io/cypress/discussions/23460

**Comment by lmiller1990** [comment]
Hi @NUlmerTS 👋We both previously worked at @doseme, small world!

Is your `specPattern` correct? `cypress/e2e/teachStarterWeb/**/.{js,jsx,ts,tsx,spec}` does not look correct - it it supposed to be `cypress/e2e/teachStarterWeb/**/*.{js,jsx,ts,tsx,spec}` (note the extra `*` in `**/*`).

In your second screenshot, it **does** have the `**/*` glob. Can you please clarify the `specPattern`?

I made a new project and updated it to be `cypress/e2e/teachStarterWeb/**/*.{js,jsx,ts,tsx,spec}`. I could get some basic specs to show up:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/19196536/185841759-55475cb0-2b44-4592-8e7f-8bc247010eff.png">

**Comment by NUlmerTS** [comment]
sorry that was a copy and past mistake.  the spec pattern is in fact:

specPattern: 'cypress/e2e/teachStarterWeb/**/*.{js,jsx,ts,tsx,spec}',

**Comment by NUlmerTS** [comment]
Possiblly linked to https://github.com/mbolotov/intellij-cypress/issues/103

**Comment by magarwal19-wellsky** [comment]
This is happening for me also..
in project settings it shows the specs are found while in spec tab nothing is displaye
<img width="1333" alt="specs are not visible in the spec tab" src="https://user-images.githubusercontent.com/88789483/185856886-5b7cb776-5454-4415-af6b-c67253f56640.png">
<img width="1298" alt="specs are visible in settings" src="https://user-images.githubusercontent.com/88789483/185856894-6f4cec1e-4eca-40c8-8f3e-31d2a6fa16bb.png">
d

**Comment by lmiller1990** [comment]
Can you share your complete `cypress.config` @magarwal19-wellsky?

Some good bug hunting in https://github.com/mbolotov/intellij-cypress/issues/103.

**Comment by wayflyermike** [comment]
I am also seeing this issue today. GUI lists no spec files, console logs a GraphQL error `[GraphQL] Cannot read properties of undefined (reading 'framework')`
![Screenshot 2022-08-22 at 09 21 10](https://user-images.githubusercontent.com/80681360/185862582-3d329c25-2853-4566-bb01-3ed80b5196c3.png)

### cypress.config.ts
```typescript
import { defineConfig } from "cypress";

export default defineConfig({
  projectId: "xxxxxx",
  video: false,
  chromeWebSecurity: false,
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require("./cypress/plugins/index.js")(on, config);
    },
    baseUrl: "http://localhost:3000",
    specPattern: "cypress/e2e/**/*.spec.*",
  },
  component: {
    setupNodeEvents(on, config) {},
    specPattern: "cypress/**/*.spec.*",
  },
});

**Comment by magarwal19-wellsky** [comment]
Hi @lmiller1990 
please find below my config file. We are using cucumber preprocessor plugin for BDD approach
<img width="440" alt="package json screenshot" src="https://user-images.githubusercontent.com/88789483/185864905-fde10a21-53eb-4f79-9bc9-a3ca55531eff.png">

**config.js**


const { defineConfig } = require('cypress')
const cucumber = require('cypress-cucumber-preprocessor').default;

let data = {};

module.exports = defineConfig({
  e2e: {
    viewportWidth: 1920,
    viewportHeight: 1080,
    defaultCommandTimeout: 60000,
    pageLoadTimeout: 90000,
    requestTimeout: 60000,
    waitForAnimations: true,
    videoCompression: false,
    includeShadowDom: true,
    projectId: "",
    chromeWebSecurity : false,
    experimentalSessionAndOrigin : true,
    env: {
      dev: {
      
      },
      qa: {
      },
      runEnv: "qa",
      berthaRunAgency: ""
    },
    setupNodeEvents(on, config) {
      // implement node event listeners here
      on('file:preprocessor', cucumber());

      on('task', {
        setProfile({ feature, profileType, profileVal }) {
          if (data.hasOwnProperty(feature) !== false) {
            data[feature][profileType] = profileVal
          } else {
            data[feature] = { [profileType]: profileVal }
          }
          return null
        },
        getProfile({ feature, profileType }) {
          return data[feature][[profileType]]
        },
        getAllProfile({ feature }) {
          if (data[feature]) {
            return data[feature]
          }
          else {
            return null
          }
        }
      });
    },
    specPattern: "cypress/e2e/**/*.feature"
  },
  component: {
    setupNodeEvents(on, config) {
      // component testing node events setup code
    },
  },
})

**Comment by mirobo** [comment]
From the OPs first post
> ```
>  module.exports = defineConfig({ 
>    projectId: 'f2y8fb',
>    chromeWebSecurity: false,
>    responseTimeout: 60000,
>    blockHosts: '_.parsely.com', 
>    pageLoadTimeout: 90000, 
>    e2e: {
>        setupNodeEvents(on, config) { 
>          require("cypress-grep/src/plugin")(config); 
>    }, 
>   // baseUrl: 'https://www.teachstarter.com/', 
>    baseUrl: 'https://staging-prexit.teachstarter.com/', 
>    specPattern: 'cypress/e2e/teachStarterWeb/**/_.{js,jsx,ts,tsx,spec}', 
>}); ```

"specPattern is defined directly inside config and not in e2e-object
I mentioned here #23010 that the "specPattern" was not available in the Cypress NPM API but that it actually worked. This was in Cypress 10.3.1 or 10.4.0 when I created this ticket.

Also the cypress-grep Plugin uses "config.specPattern" and not the testingType-specific specPattern.
https://github.com/cypress-io/cypress-grep/blob/main/src/plugin.js#L120

I hope I don't bring more confusion to this issue.. but I'm sure the Cypress devs will figure it out :D

**Comment by larryh** [comment]
This is happening to me, too. Works in Cypress 10.4, but not 10.5 nor 10.6

Maybe it is related to a non-default installation directory structure?

My specs live in /tests/integration/`<two-directories>`/`<several-directories>`/`<individual-tests>`

So, for example, I have:

/tests/integration/pages/about/contact.spec.js
/tests/integration/pages/about/us.spec.js

/tests/integration/pages/support/forgot-password.spec.js
/tests/integration/pages/support/resend-confirmation.spec.js

/tests/integration/routes/middleware-guards.spec.js
/tests/integration/routes/pages-and-titles.spec.js

My cypress.config.js has `e2e.specPattern` set to `'tests/integration/**/*.spec.js'`

**Comment by marktnoonan** [comment]
There is an empty state for when no files match the `specPattern`, I think we'd be seeing that if something was changed that broke the ability to match specs properly (plus the screenshot of the settings page confirms specs are found).

My gut feeling is the `[GraphQL] Cannot read properties of undefined (reading 'framework'` error is preventing correct building of the specs list, I'm going to see if I can reproduce.

For reference I upgraded a simple project to 10.6.0 yesterday and did **not** see this problem, so it is likely to be a combination of things.

If anybody can create a standalone example using the cypress-test-tiny template it would be helpful to narrow down what the interaction is that leads to this: https://github.com/cypress-io/cypress-test-tiny

**Comment by marktnoonan** [comment]
Re: @mirobo's comment, I think it only appeared that `specPattern` was defined at the top level due the object being cut off, it is actually nested under `e2e`. At the top level I get the correct error in the UI.

I've tried with @NUlmerTS's config (without the grep plugin) and been successful loading the specs list. Wondered if it was a Windows issue but see one of the reports is from Mac.

**Comment by marktnoonan** [comment]
After playing around a bit with the config files posted here, it looks like this error is due to a missing null check for `component.devServer` in the config... if you have partially set up component testing you might be in this state, and the workaround for now will be to remove `component` from your config - or set up your `devServer` with the framework and bundler for component testing.

If anybody still has the problem after modify the config, please post here with details.

**Comment by larryh** [comment]
Removing the `component` section from my config file worked for me, in both 10.5 and 10.6 - thanks a lot!

I imagine a fix will be forthcoming so we don't have to do that.

Which is fine with me; I had high hopes for using Cypress for component testing, but bailed on it as the setup - providing mocks/stubs for Vuetify and Vuex and vuex-orm and vuex-orm-axios and Mirage - was just too daunting a task.

But that's a whole 'nother issue. Thanks for all of the GREAT WORK that you folks do!

BTW, if people reading this haven't checked out Mirage, you should. It's a fake server that runs in the client, and lets front-end developers mock out backend APIs. It can be used in both development and testing, and it is fantastic! And it works with Cypress Integration tests to boot! 

(For the record: I am not, and never have been, affiliated with Mirage in any way. I started out using Ember, and Mirage was built for that, which is how I got introduced to it.  But they've since expanded it to work with React and Vue, the latter being what I now use.)

Thanks again!

**Comment by shershen08** [comment]
I had the same issue
**downgrading to 10.4.0 helped**

**Comment by NUlmerTS** [comment]
I can confirm that removing the component in cypress.config enabled it to run.
