### ISSUE TITLE
Flaky test: AssertionError: expected 'queue.insert must be called with a valid index - the index (7) is out of bounds' to include 'rejected promise' (and Mocha's done() called multiple times)

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23484]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/42283/workflows/124197db-0bf3-406b-9e7c-5d4156f16e9a/jobs/1756005

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/e2e/origin/uncaught_errors.cy.ts#L250

### Analysis

<img width="1438" alt="Screen Shot 2022-08-21 at 2 29 19 AM" src="https://user-images.githubusercontent.com/26726429/185784688-49764737-bd5c-4688-9937-e02f725b4d8c.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
