### ISSUE TITLE
vue component testing not works in node 17.4.0

### ISSUE THREAD

**Issue by cll123456** [cypress-io/cypress#23483]
### Current behavior

hi, cy team;
  I currently use cy to test vue code.  My node environments as flower:
![image](https://user-images.githubusercontent.com/41314419/185774414-23d3a0a8-96ce-4d54-81c3-df370edfb132.png)

When i was  tested e2e, it's ok. But when i was tested vue components, it's Always loading and couldn't close loding to show testing result.

https://user-images.githubusercontent.com/41314419/185775805-a88aaada-7576-4961-8ce4-ed8077da97c0.mp4

 

### Desired behavior

In node 17, cy sholud normal testing

### Test code to reproduce

https://github.com/cll123456/cypress-test-tiny.git

please clone project.
- `in node 17.4.0`
- `pnpm install`
- `pnpm run dev ` start local serve
- `pnpm cy:open` open cy panel and choose test components
-  click testing `MessageInput` ， you can find the loading can't disappear 

### Cypress Version

10.4.0

### Node version

v17.4.0

### Operating System

win11

### Debug Logs

```shell
no any logs
```

**Comment by mike-plummer** [comment]
Hi @cll123456 , thanks for reaching out! I believe the issue you're reporting is related to #23042 and you should be able to resolve it by upgrading to Cypress >= 10.5.0

**Comment by cll123456** [comment]
@mike-plummer  Thank you for your reply😀😀😀，I will close the issue!!!
