### ISSUE TITLE
Chinese character rendered into blocks in github action

### ISSUE THREAD

**Issue by rick-yao** [cypress-io/cypress#23485]
### Current behavior

when github action run the cypress test, all Chinese characters are displayed with empty blocks.
But when I run tests locally , everything works fine.
![image](https://user-images.githubusercontent.com/59443488/185837607-9ebe354e-f8ba-4818-b9f1-fb96cfa16203.png)
I did below changes to fix it , but I failed.  
`cy.visit('http://localhost:3000/react/test/form',{onBeforeLoad(win) {
        Object.defineProperty(win.navigator, 'language', {
          value: 'zh-CN'
        })
      }})  `
`<meta name="viewport" content="initial-scale=1, width=device-width" charSet="UTF-8"/>`

### Desired behavior

cypress should display Chinese characters correctly

### Test code to reproduce

Internal project, I am sorry i cannot show you the code.

### Cypress Version

10.6.0

### Node version

16.14.2

### Operating System

ubuntu 20.04

**Comment by lmiller1990** [comment]
Hi!

From what you've shared, the OS you are running on GH Actions does not have a Chinese font installed (since it does work locally, where I'm guessing you do have a Chinese font installed).

**Comment by rick-yao** [comment]
> Hi!
> 
> From what you've shared, the OS you are running on GH Actions does not have a Chinese font installed (since it does work locally, where I'm guessing you do have a Chinese font installed).

Thanks for your quick reply , I will add Chinese font.

**Comment by rick-yao** [comment]
After adding Chinese, my issue has been solved. Thanks @lmiller1990 !

**Comment by hongdeyuan** [comment]
> After adding Chinese, my issue has been solved. Thanks @lmiller1990 !

   @rick-yao 
    I also encountered the same problem. Do you have detailed steps to solve it?  I think [add cypress/base:8.16.0 image with Chinese fonts](https://github.com/cypress-io/cypress-docker-images/pull/111) already supports it, but I still encounter this issue; 

  -  image version: [cypress/included: 12.3.0 image](https://github.com/cypress-io/cypress-docker-images/blob/master/included/12.3.0/Dockerfile)

**Comment by hongdeyuan** [comment]
Oh, I know how to do it; Simply copy the expected web expected font to the Docker container; like this:
`-v /usr/share/fonts/chinese:/usr/share/fonts/chinese`
