### ISSUE TITLE
Flaky test: Permission denied to access property "addEventListener" on cross-origin object

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23481]
### Link to dashboard or CircleCI failure

- https://dashboard.cypress.io/projects/ypt4pf/runs/38236/test-results/75a3f330-b6d7-464f-9a7f-50ef7719af72
- https://dashboard.cypress.io/projects/ypt4pf/runs/38239/test-results/bf287d97-2351-464d-8aa4-9c9f2e8b3560

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/e2e/origin/basic_login.cy.ts#L171

### Analysis

<img width="431" alt="Screen Shot 2022-08-20 at 9 04 44 PM" src="https://user-images.githubusercontent.com/26726429/185774981-ec841bb7-11f0-4c60-ab04-75559a650992.png">

### Cypress Version

10.5.0

### Other

Search for this issue number in the codebase to find the test(s) skipped until this issue is fixed

**Comment by todd-m-kemp** [comment]
Is there still a chance that this might get looked at? I'm curious to see the solution as we frequently see failed test attempts with this exact message in our Firefox test runs. We _never_ see this in Chrome. 🤔

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
