### ISSUE TITLE
"Create from Component" with special characters in component filename can scaffold incorrect spec name and non-working import/mount

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#23492]
### Current behavior

Currently if I choose the catchall route component named `[...all].vue` we scaffold the spec as normal, but with the name `l.spec.ts`, and our import statements are (pretty naturally) non-functional because the filename happens to include a `[`.

Later I noticed this also happens with filenames like `new-component.vue` where we generate `import new-component from './components/new-component.vue'` and `cy.mount(new-component)`, which are invalid JavaScript. Hyphens in filenames seem very common so we should handle them gracefully.

![Screen Shot 2022-08-22 at 10 47 38 AM](https://user-images.githubusercontent.com/8340719/185950645-be81eb5d-d69d-47d3-b9eb-168e73e2cd3e.png)
![Screen Shot 2022-08-22 at 10 31 31 AM](https://user-images.githubusercontent.com/8340719/185950148-7fc3ebeb-ecf3-41af-9380-6d3135ce76e3.png)
![Screen Shot 2022-08-22 at 10 33 03 AM](https://user-images.githubusercontent.com/8340719/185950146-374ee3bf-2220-4b95-93f7-fb1aed0db11d.png)

### Desired behavior

For the internal import name, Cypress should

- strip all characters from the file name that are not valid in JS variable names before generating `import ${filename}`, or
- name the import `component` or something predictable so that the filename will never be used as JS, and we don't have to think it about it.

This version of the spec is valid and runs:

```ts
import component from './pages/[...all].vue'

describe('<[...all] />', () => {
  it('renders', () => {
    // see: https://test-utils.vuejs.org/guide/
    cy.mount(component)
  })
})
```
![Screen Shot 2022-08-22 at 10 49 05 AM](https://user-images.githubusercontent.com/8340719/185951403-ab40626c-358a-42ae-ae9b-f22eeac5c410.png)

For the filename, `[...all].spec.ts` is a valid spec name, and we should preserve the literal name of the component. Seems possible the extra periods are running afoul of some regex we use for the extensions maybe. 

We have lots of tests around spec filenames displaying correctly in the Specs List with various characters and languages (e.g. `d~e(f)g.spec.js`), we could use some component files with those same non-English word names to test generating specs.

In general I think there are filename conventions using special characters beyond this specific case, so it would be good to handle them predictably, even if it's not possible to do it elegantly right away.

### Test code to reproduce

In the app package, open Cypress component testing and choose "New Spec" then "Create from Component", and attempt to create a spec from `[...all].vue`.

### Cypress Version

develop

### Node version

16.14.2

### Operating System

MacOS

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23492?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
