### ISSUE TITLE
Webpage not detecting cookie after redirect when link click from 9.0.0

### ISSUE THREAD

**Issue by mrecamales2222** [cypress-io/cypress#23511]
### Current behavior

We want to test the following flow:

1. We visit a website that to access it we need a cookie that is set before each test
2. We navigate to google.com
3. We go again to the first website clicking an <a> element that has the href pointing to the first website url. In this step it is not possible to access it, as our page is displaying our custom error for when the cookie is not set.

We checked and the cookie is still set correctly in step 3, but somehow the browser can’t detect it. 

### Desired behavior

1. We visit a website that to access it we need a cookie that is set before each test
2. We navigate to google.com
3. We go again to the first website clicking an <a> element that has the href pointing to the first website url.
4. We are able to see the page.

### Test code to reproduce

Here is how we set the cookie:
```
beforeEach(() => {
    cy.setCookie("AUTH-COOKIE", Cypress.env('AUTH_COOKIE'), {log: false, domain: domain})
});
```

And the test is like this:

```
cy.visit(productURL);

// go to google
cy.window()
    .then((window) => {
        window.location.href = 'https://google.de';
    });

// create link to original website and click it
cy.window()
    .then((window) => {
        let a = window.document.createElement('a');
        let linkText = window.document.createTextNode('This is a link to original web page');
        a.appendChild(linkText);
        a.className = 'link';
        a.href = originalWebsite + productURL;
        window.document.body.appendChild(a);
        a.click();
    });

// assert page has loaded
cy.get('.cinema')
    .should('be.visible')
```

Having originalWebsite the same value as the baseUrl in cypress.json, the config file, and the domain value is the same as baseUrl without the https:// part.

### Cypress Version

9.0.0

### Node version

14.8.0

### Operating System

MacOS 12.4

**Comment by mike-plummer** [comment]
Hi @mrecamales2222 , thanks for opening an issue! It sounds like the behavior you're looking for would be an ideal use case for our new [`cy.origin`](https://docs.cypress.io/api/commands/origin) and [`cy.session`](https://docs.cypress.io/api/commands/session) commands which were introduced in Cypress version 9.6.0. I think there's a couple directions you could go, depending on your use case:
1. `cy.origin` adds support for visiting multiple domains in a test (the described workaround using `window.location.href` is not officially supported) - this likely would resolve your missing cookie issue
2. `cy.origin` allows you to cache and quickly restore prepared user sessions (cookies, session/localStorage) so you wouldn't have to do the cookie setup repeatedly in your tests

**Comment by lmiller1990** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
