### ISSUE TITLE
Component Testing General Availability

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#23524]
Remaining issues for Component Testing GA

**Comment by lmiller1990** [comment]
Things I think we need for GA:

- consistent and well documented API (eg a third party should be able to make their own `mount` and it will comply to the "Cypress Mounting API" spec)
- no frameworks in alpha/beta/experimental
- documentation on required steps to adding a new mount adapter and/or dev server
- stack traces
- (tentative) make `singleTabRunMode` the default for CT, move out of experimental status
- "Create from Component" working as expected for all supported frameworks

Just some ideas, will keep updating as I think of more.

**Comment by lmiller1990** [comment]
I think we need a cohesive way to "test events/props". There's a ton of confusion see https://github.com/cypress-io/cypress/issues/23657 for an example.

Vue/React/Angular/Svelte all have something like

```js
it('should react to some user interaction in some fashion', () => {
  const something = cy.stub()
  cy.mount(<Foo onSomething={something} />)
    .get("#some-element)
    .click()
    .then(() => {
      expect(something).to.have.been.calledOnce
  })
})
```

This same example basically translates to all of our frameworks, and there are a number of pain points. It's slightly different for each framework. There's [many ways to do it in Vue](https://github.com/cypress-io/cypress/issues/23657) and probably other frameworks. This means we need to document a new thing for each framework - I hope we can have one cohesive way to do things like this.

As an aside, you need to do `.then` to assert against the stub, which is not ideal. It's the same as needing `await` in Testing Library etc - not sure this can be solved, but maybe we can explore this more.

**Comment by lmiller1990** [comment]
To follow on ^ I think the entire docs need a rethink, there's way too many ways to do the same thing, we need recommendations. 

Example: https://github.com/cypress-io/cypress/issues/23657 led to https://github.com/MichelMan/test-ct-vuetify-emit-event/pull/1 -> doing something like "testing a prop is called" should be dead simple and we should have a cohesive recipe. I think we should opt away from framework specifics (like Test Utils APIs) in favor of things that work on all frameworks, like Cypress APIs (cy.spy, etc).

**Comment by lmiller1990** [comment]
- We should not having linting or typing errors for common templates out of the box.

**Comment by lmiller1990** [comment]
It's GA now.
