### ISSUE TITLE
download.cypress.io Unavailable

### ISSUE THREAD

**Issue by jasonvooo** [cypress-io/cypress#23526]
### Current behavior

Within our github actions pipeline we are currently unable to download from `download.cypress.io`
<img width="947" alt="image" src="https://user-images.githubusercontent.com/14245160/186284664-ac9e521c-18d1-4031-8bd1-819b6654cc77.png">

### Debug logs
```
[STARTED] Task without title.
[FAILED] The Cypress App could not be downloaded.
[FAILED] 
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
[FAILED] 
[FAILED] Otherwise, please check network connectivity and try again:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] URL: https://download.cypress.io/desktop/10.6.0?platform=linux&arch=x64
[FAILED] Error: Failed downloading the Cypress binary.
[FAILED] Response code: 530
[FAILED] Response message:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Ubuntu - 20.04)
[FAILED] Cypress Version: 10.6.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/10.6.0?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 530
```

### Cypress Version

10.6

### Node version

16.14.2

### Package Manager

yarn

### Package Manager Version

1.22.17

### Operating system

Linux

### Operating System Version

ubuntu-latest

**Comment by EricBPower** [comment]
Also receiving this error from our CI:

[FAILED] URL: https://download.cypress.io/desktop/8.4.0?platform=linux&arch=x64
[FAILED] Error: Failed downloading the Cypress binary.
[FAILED] Response code: 530
[FAILED] Response message:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux (Ubuntu - 20.04)
[FAILED] Cypress Version: 8.4.0
The Cypress App could not be downloaded.

**Comment by mehcan-dh** [comment]
Follow up comment :)

**Comment by jasonvooo** [comment]
Resolved

**Comment by doubleflygofight** [comment]
> Resolved

how do you resolve that?

**Comment by jasonvooo** [comment]
> > Resolved
> 
> how do you resolve that?

download.cypress.io is available again

**Comment by mike-plummer** [comment]
Apologies everyone, one of our infrastructure providers had an incident yesterday and one of the impacted services was our CDN. Things should have gotten back to normal late evening yesterday (Eastern US time).

For future reference we do have a status tracker that can help you monitor any issues: https://www.cypressstatus.com/
