### ISSUE TITLE
Getting an Uncaught refrence error: $cookieExists is not defined

### ISSUE THREAD

**Issue by RamCreativeUI** [cypress-io/cypress#2352]
Hey guys, I just started using cypress and it was working pretty good for us, we did automate our ping page loign. Yesterday i tried cypress with cucumber for the same ping page login, the page is getting expired when we run our automated tests. Can someone help us with this, please let me know if you need more details. Thanks in advance!

**Comment by jennifer-shehane** [comment]
Yeah, it's definitely strange that there is only an issue when including `cypress-cucumber-preprocessor`, have you tried searching their repo's issue?

**Comment by RamCreativeUI** [comment]
@jennifer-shehane Yeah i did and i didn't find anything related to this.
Is it really with the preprocessor and is there someone that can help.

**Comment by jennifer-shehane** [comment]
No, the [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) is a 3rd party plugin and not under out development.

**Comment by jennifer-shehane** [comment]
Closing as a third party plugin issue.

Please comment in this issue if found to be a Cypress bug and we will reopen the issue. 🙏
