### ISSUE TITLE
Cypress download fails with a 530 error

### ISSUE THREAD

**Issue by nwalters512** [cypress-io/cypress#23527]
### Current behavior

Our CI job is failing with the following error:

```
[FAILED] The Cypress App could not be downloaded.
[FAILED] 
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
[FAILED] 
[FAILED] Otherwise, please check network connectivity and try again:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] URL: https://download.cypress.io/desktop/10.5.0?platform=linux&arch=x64
[FAILED] Error: Failed downloading the Cypress binary.
[FAILED] Response code: 5[30](https://github.com/PrairieLearnInc/PrairieTest/runs/7984786822?check_suite_focus=true#step:6:31)
[FAILED] Response message:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Ubuntu - 20.04)
[FAILED] Cypress Version: 10.5.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/10.5.0?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 530
Response message:
```

Visiting https://download.cypress.io shows a Cloudflare error message. Myself and my colleagues can reproduce this across all our devices, so it does not appear to be an issue with any particular device or network.

### Desired behavior

Cypress should be able to download successfully.

### Test code to reproduce

Visit https://download.cypress.io/ and observe the following error message:

<img width="760" alt="Screen Shot 2022-08-23 at 16 40 00" src="https://user-images.githubusercontent.com/1476544/186284709-d22fa4a2-5e29-43be-8ebd-83257efe661a.png">

### Cypress Version

10.5.0

### Node version

14.20.0

### Operating System

macOS + Linux

**Comment by nwalters512** [comment]
Looks like @jasonvooo beat me to this in #23526. I'll leave my duplicate open for now since it provides a little more info.

**Comment by EricBPower** [comment]
Also receiving the same error:  

[FAILED] URL: https://download.cypress.io/desktop/8.4.0?platform=linux&arch=x64
[FAILED] Error: Failed downloading the Cypress binary.
[FAILED] Response code: 530
[FAILED] Response message:
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux (Ubuntu - 20.04)
[FAILED] Cypress Version: 8.4.0
The Cypress App could not be downloaded.

**Comment by rodrigo-vazquez** [comment]
Same here!

**Comment by alameddinc** [comment]
Same here!

**Comment by hu-jin-aws** [comment]
Same too.

**Comment by mehcan-dh** [comment]
Follow up comment, same here :)

**Comment by caiorsantanna** [comment]
Here too

**Comment by viqueen** [comment]
Yey ! Not the only one

**Comment by nwalters512** [comment]
In case this is blocking deployments or other tasks that don't actually need Cypress to run, you should be able to set `CYPRESS_INSTALL_BINARY=0` in your environment variables to prevent Cypress from trying to download itself.

**Comment by alameddinc** [comment]
I found cypress discord channel and status checker website. you can track on there

https://www.cypressstatus.com/
discord.gg/cypress

**Comment by tuan-bui** [comment]
Same here!

**Comment by kiosion** [comment]
Spent 15mins going crazy checking my workflows, glad to see it's not just me :')

**Comment by issy123** [comment]
Meanwhile enjoy this gif..

![gif](https://user-images.githubusercontent.com/9143253/186289390-b71ea2e0-3bc4-4984-9851-80d4f5934908.gif)

**Comment by ImTheTom** [comment]
> In case this is blocking deployments or other tasks that don't actually need Cypress to run, you should be able to set `CYPRESS_INSTALL_BINARY=0` in your environment variables to prevent Cypress from trying to download itself.

Thanks man 👍

**Comment by viqueen** [comment]
Looks like it got fixed ?

**Comment by caiorsantanna** [comment]
Seems that is back to normal, lets go back to merging, good lock for you guys <3

**Comment by mike-plummer** [comment]
Apologies everyone, one of our infrastructure providers had an incident yesterday and one of the impacted services was our CDN. Things should have gotten back to normal late evening yesterday (Eastern US time).

For future reference in case folks didn't see it called out earlier in this issue we do have a status tracker that can help you monitor any issues: https://www.cypressstatus.com/
