### ISSUE TITLE
Refetch orgs and projects on connection modal open

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#23538]
If a project is created in the Dashboard before the project connection modal is opened, then it is not shown in the list of existing projects to connect. Similarly, if the modal is used to create a new project, then the projectId is deleted, it is not possible to then reconnect that same project.

A user's organizations and projects should be refetched whenever that modal is opened, so that the most up-to-date orgs and projects are shown as options to connect.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23538?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
