### ISSUE TITLE
Fix issue with the timing of setting cookies in the browser

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#23531]
Currently, if a cross-origin request sets a cookie and the app attempts to read the cookie via `document.cookie` synchronously on page load, the `document.cookie` value will not be correct / up-to-date.

Spec:

```js
it('document.cookie includes cookie set by http request', () => {
  cy.get('[data-cy="cookie-login-land-on-document-cookie"]').click()
  cy.origin('http://foobar.com:3500', { args: { username } }, ({ username }) => {
    cy.get('[data-cy="username"]').type(username)
    cy.get('[data-cy="login"]').click()
  })

  cy.origin('http://idp.com:3500', { args: { username } }, ({ username }) => {
    cy.get('[data-cy="document-cookie"]').invoke('text')
    .should('include', `user=${username}`)
  })
})
```

App:

```html
<p>
  <strong>document.cookie:</strong>
  <span data-cy="document-cookie"></span>
</p>
<script>
  document.querySelector('[data-cy="document-cookie"]').textContent = document.cookie;
</script>
```

**Comment by boylec** [comment]
I believe this is related to #23565 as I am seeing the same behavior as the OP in that issue and it appears that it due to a client side app not being able to read a cookie that was set on page load.

**Comment by boylec** [comment]
I rolled back to 10.2 and my test started working again.

**Comment by boylec** [comment]
Not sure how helpful this is, but my particular test is good to go up to 10.3.

When run from 10.3.1 my test fails in a unique way unlike 10.4+
When run from 10.4+ my test fails as described in #23565 

Let me know if any more detail would be helpful, I'll do the best I can.
