### ISSUE TITLE
cy.session does not save localStorage and sessionStorage but Cookies

### ISSUE THREAD

**Issue by lukitroe** [cypress-io/cypress#23548]
### Current behavior

In our test suite, we need to login to our web application utilizing Azure AD as identity provider. In the global before hook, we start a cy.request, getting the first `access_token` and `refresh_token`. With the `refresh_token`, subsequent API logins are made. In the source code, it looks like this:
```js
Cypress.Commands.add("doAdminLogin", () => {
    
    cy.session(Cypress.env("ADMINUSER"), () => {
    cy.azureAadLogin(loginCredsPassword, Cypress.env("ADMINUSER"), Cypress.env("ADMINPASSWORD"))
    .then((refreshTokenAdmin) => {
        doAPILogin("API_KEY", loginCredsApis.get("API_KEY"), refreshTokenAdmin);
    })
    });
});
```

In the Cypress Test Runner, the sessions look like this:
![image](https://user-images.githubusercontent.com/26189015/186589658-324a6187-5ab3-4ec0-b37c-90a2a4034972.png)

So, the tests executes two times the same procedure, once with an ADMINUSER and once as a basic user. Clicking in the Test Runner on one of the sessions, reveals this in the console:
![image](https://user-images.githubusercontent.com/26189015/186590327-7ab56067-e958-4257-9c73-b4d7cb7d5e6f.png)

The login is successful for all cy.requests. The `access_token`, `refresh_token` and many other information for authentication are saved in the session storage, which is not part of cy.session. At least it seems. 

### Desired behavior

The desired behavior should look similar to this https://docs.cypress.io/api/commands/session#Printing-to-the-console but with sessionStorage, instead of the localStorage.

### Test code to reproduce
```js
Cypress.Commands.add("doAdminLogin", () => {
    
    cy.session(Cypress.env("ADMINUSER"), () => {
    cy.azureAadLogin(loginCredsPassword, Cypress.env("ADMINUSER"), Cypress.env("ADMINPASSWORD"))
    .then((refreshTokenAdmin) => {
        doAPILogin("API_KEY", loginCredsApis.get("API_KEY"), refreshTokenAdmin);
    })
    });
});
```

### Cypress Version

10.6.0

### Node version

v16.15.0

### Operating System

Windows 10

**Comment by mike-plummer** [comment]
Hi @lukitroe , thanks for opening an issue! Unfortunately, I'm not able to determine the problem you're encountering without seeing more around how you're establishing the sessionStorage and localStorage items. Do you have a minimal reproduction that demonstrates the issue as you've described that I could pull down and run?

[I put together a small example](https://github.com/mike-plummer/23548-cypress-repro) showing a flow where we use `cy.session` to make a `cy.request` which establishes a Cookie, Session Storage, and Local Storage item, then validate those items are still present later in the test both when creating the session (first run) and restoring the session (subsequent runs). Perhaps that code will give you a hint to any potential setup or execution flow issues you may have?

**Comment by rlam3** [comment]
@mike-plummer looks like there is an issue with sessions. the cookies in session isn't persisted it seems. 

trying the repo you've given us, it seems like its failing with cypress 10.6
<img width="1422" alt="Screen Shot 2022-08-27 at 8 57 32 PM" src="https://user-images.githubusercontent.com/1154044/187053178-233ab98b-25fb-4c6c-b0de-0fc8cddd0a60.png">

**Comment by mike-plummer** [comment]
@rlam3 Oops, I forgot to push up my last commit. Sorry! I've verified the that project now succeeds with latest versions of Electron, Chrome, and Firefox.

**Comment by mike-plummer** [comment]
@lukitroe You might be getting tripped up by browser security restrictions regarding domains. It's important to remember that storage and cookies are domain-dependent, so you need to ensure your test is on the appropriate domain before you establish any of these. If your test starts on one domain (like `localhost`) it will establish values against that domain which won't be accessible if your test later switches domains. Take a look at the [default for the `domain` option on the `setCookie` command](https://docs.cypress.io/api/commands/setcookie#Arguments) - it defaults to where your test currently is, so it is helpful to ensure your test is on the correct domain prior to establishing these values. Similar constraints exist for `localStorage` and `sessionStorage` - the browser disallows code running on one domain from accessing values established under another domain. Depending on how your tests are set up this can be accomplished with an explicit `cy.visit` and/or using `baseUrl` in your configs. Regardless of where your `cy.request` retrieves data from it needs to be able to establish storage values within the domain where they will later be accessed

**Comment by lukitroe** [comment]
@mike-plummer Thank you for your reply and your time! 

OK, that I wasn't aware of. I think, then cy.session doesn't basically not work with my tests. Because the tests need to login via https://login.microsoftonline.com, however, with the API calls, I never visit the login page before. I do not even need to visit the page before. 
I then found this blog post here: https://www.cypress.io/blog/2022/04/25/cypress-9-6-0-easily-test-multi-domain-workflows-with-cy-origin/#usage-with-session and tried it like this, but it is even not working like this. Cypress and Azure do really not work well together, unfortunately. I think, that is the root cause of the issue and why it is not working. 

Thanks to all of you who helped me on this topic!
