### ISSUE TITLE
Navigator header menu is not visible in cypress

### ISSUE THREAD

**Issue by swethay** [cypress-io/cypress#2354]
### Current behavior:

![image](https://user-images.githubusercontent.com/2423004/44168848-6a584900-a087-11e8-9c63-3a47dba19557.png)

### Desired behavior:

![image](https://user-images.githubusercontent.com/2423004/44168887-97a4f700-a087-11e8-8f72-c87b645788cc.png)

Header Menu and Dropdown should be visible in cypress to select values

### Steps to reproduce:
1. Run simple login test in cypress
2. Login is successful

Issue : Header menu is not visible in cypress

Tried with different viewport sizes : (1440x900), (1280x720), (1000x660)
Please note that header menu and dropdown are visible in google chrome with these viewport sizes and not visible in cypress.

It looks like Header menu is hidden under Open Selector Playground

### Versions
Cypress Version : Version 3.0.1 (3.0.1)
Operating System : MacBook Pro (Retina, 15-inch, Mid 2015)
Browser : Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
> It looks like Header menu is hidden under Open Selector Playground

This is definitely not intended behavior within Cypress. 

Are you able to inspect your application's DOM using the developer tools and see the menu element at all? Does it highlight below the selector playground? Is there a class or style present that isn't normally (like a `.hide`)?

**Comment by swethay** [comment]
> Are you able to inspect your application's DOM using the developer tools and see the menu element at all?
Yes, i'm able to inspect using developer tools.  Attaching screenshot below 
![image](https://user-images.githubusercontent.com/2423004/44186629-5df7de80-a0cf-11e8-8be7-bdec5db18b5c.png)

**Comment by jennifer-shehane** [comment]
@swethay Sorry, I should have been more specific. Could you open the developer tools within Cypress - where it is being rendered incorrectly - and see that the header's DOM element is being rendered there under the selector playground as you're suggesting.

**Comment by jennifer-shehane** [comment]
Hey, I do see that the `nav-container` is present in the DOM - I also see that the height of the element is 0 pixels. 

I wonder if it is related to this in some way https://github.com/cypress-io/cypress/issues/2052

We are rendering your application within an iframe, but do try to workaround this, I wonder if there is any javascript in your application regarding being rendered outside of it's own frame that would set the height to 0 of this navbar?

**Comment by swethay** [comment]
@jennifer-shehane Thanks for the help. could you please let me know the workaround when the height of the element is 0 pixels?

**Comment by swethay** [comment]
@jennifer-shehane,  I worked with my developer and it looks like we have "Only show the nav if the page is not in an iFrame" in our application and that's the reason for not seeing the nav bar. Will work with my developers and get this fixed. Thank you so much for your help!

**Comment by jennifer-shehane** [comment]
@swethay Awesome, glad to hear you were able to determine the cause.
