### ISSUE TITLE
No tests found in file when importing react component.

### ISSUE THREAD

**Issue by Glinkis** [cypress-io/cypress#2356]
I have a project that is set up using Webpack, React, and Typescript.

When I try to import a react component in my spec file, cypress suddenly ignores my whole test file.

<img width="420" alt="screen shot 2018-08-16 at 15 08 58" src="https://user-images.githubusercontent.com/8037927/44210337-7961f880-a166-11e8-93f1-5b0990a43a61.png">

spec file:
```typescript
import { add } from "../../src/misc/add";
import { App } from "../../src/components/App";

describe("example unit test", function() {
  it("runs example unit test", function() {
    expect(add(2, 8)).to.equal(10);
    console.log(App);
  });
});
```

If I remove `import { App } from "../../src/components/App"` and `console.log(App)`, the test runs fine.

[The repo.](https://github.com/Glinkis/cypress-test)

**Comment by bahmutov** [comment]
Cypress is NOT built with component testing right out of the box, but with end-to-end testing in mind. Something is going wrong during transpiling your `App` component, but we do not see what. I suggest that you go through our _unofficial_ React component mount helper available here https://github.com/bahmutov/cypress-react-unit-test

But I honestly suspect that things go wrong in the TypeScript -> TSX -> ts-loader -> webpack chain, but why there is no error thrown is hard to say. Good thing you have provided the reproduction repo, @chrisbreiding can you take a look - the error "No tests found in your file" does happen, and there are no console or terminal errors. Maybe our webpack preprocessor could do something here?

**Comment by jennifer-shehane** [comment]
Ran this code in Cypress 3.4.0, I no longer get the 'no tests found' error. Closing as resolved.
