### ISSUE TITLE
Adding scrollBehavior setting to select() method

### ISSUE THREAD

**Issue by piotrpog** [cypress-io/cypress#23564]
### What would you like?

For some reason, unlike `click() method, select() method does not have `scrollBehavior` setting which can be used in its options. I thing such setting should be added to it.

### Why is this needed?

This settings is very useful if we deal with fixed or sticky elements that can cover element we want to interact with, in this case - `<select>` element.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest, we’ll close this as not planned.
