### ISSUE TITLE
Version 10.6.0 no longer shows code link and snippet on error in command log

### ISSUE THREAD

**Issue by MassimoLobrutto** [cypress-io/cypress#23563]
### Current behavior

This is the error in v 10.6.0

![image](https://user-images.githubusercontent.com/81157392/186930816-25a039fc-b5b2-4d5f-9002-e1fdf5f6c0a5.png)

Note how the link to the failing code and snippet of code are NOT present

This makes it harder to debug failures

### Desired behavior

This is the same error in 9.7.0 note how the link to the failing code and snippet of code are present

![image](https://user-images.githubusercontent.com/81157392/186931530-06158b30-6927-412a-82a7-6b617b6f3e58.png)

### Test code to reproduce

NA

### Cypress Version

10.6.0

### Node version

16.15.0

### Operating System

Windows 11

**Comment by mike-plummer** [comment]
Hi @MassimoLobrutto , thanks for opening an issue! In the newest versions of Cypress we do still attempt to display the context around the failing command the way you showed from 9.7.0, but we fall back to the situation in your screenshot when we aren't able to identify the exact code frame for the error. This can sometimes happen if there's intermediary transpilers/preprocessors in the mix, or if sourcemaps aren't being generated properly. I've confirmed the behavior works as expected in simple projects on Cypress 10.6.0, but based on your identified change in behavior from v9 to v10 we apparently aren't handling a more complex setup correctly anymore. Do you have a simple example that reproduces this issue you could share or more information about the command structure/libraries/other setup from your example above? Were there any changes made other than the upgrade to Cypress 10 (dependency updates, config changes, etc)?

**Comment by lmiller1990** [comment]
Just to clarify this is E2E or Component Testing?

Also if you click on "View Stack Trace" in the first image, does it not show the correct code frame?

**Comment by MassimoLobrutto** [comment]
@lmiller1990 its e2e and no the stack trace does not show the code block just the result the error had on cypress rather than the code in the test that caused it

**Comment by MassimoLobrutto** [comment]
@lmiller1990 @mike-plummer  please find a cut down cypress framework here. https://github.com/MassimoLobrutto/ErrorReproduction run the test.feature and it will reproduce the error

**Comment by lmiller1990** [comment]
Thanks for the reproduction!  I can see it now, too:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/19196536/188768100-f7d7a847-9a0c-43b5-af75-847f7172876b.png">

I think this is actually an issue in the cucumber plugin. It looks like the author is aware: https://github.com/badeball/cypress-cucumber-preprocessor/issues/692

**Comment by MassimoLobrutto** [comment]
@lmiller1990  thanks for that i also have a few defects i found (am QA by trade) that will use the same repo.  Will post them at some point.  :)

**Comment by badeball** [comment]
> I think this is actually an issue in the cucumber plugin. It looks like the author is aware: https://github.com/badeball/cypress-cucumber-preprocessor/issues/692

My issue is an entirely separate issue.

OP has to at the very least enable sourcemaps in esbuild if they wish to see a meaningful stacktrace. This is not enabled by default with `@bahmutov/cypress-esbuild-preprocessor`. Try something like

```js
createBundler({
  sourcemap: "inline",
  plugins: [nodePolyfills(), createEsbuildPlugin(config)]
})
```

**Comment by MassimoLobrutto** [comment]
Thanks @badeball that has fixed it :) @lmiller1990 you can close this defect now
![image](https://user-images.githubusercontent.com/81157392/188829861-793874ea-0a6c-4de3-a020-f4b0fd9cd644.png)

**Comment by lmiller1990** [comment]
Right, I missed he was using `esbuild`. Thanks @badeball 🙏
