### ISSUE TITLE
Define PR and Review process for the CT and E2E teams

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#23562]
### What would you like?

Create a well defined process for how the app teams handles PRs, Reviews and Merging

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23562?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by astone123** [comment]
maybe we can work off of this? https://github.com/cypress-io/prod-eng-docs/pull/77

**Comment by lmiller1990** [comment]
Yep that's the one!

**Comment by astone123** [comment]
@lmiller1990 yeah that's a good point. I'll leave this for you next sprint

**Comment by lmiller1990** [comment]
PR updated https://github.com/cypress-io/prod-eng-docs/pull/77

Expecting tons of feedback, one process to rule them all!
