### ISSUE TITLE
CypressError: Timed out after waiting `120000ms` for your remote page to load.

### ISSUE THREAD

**Issue by maddhruv** [cypress-io/cypress#23581]
### Current behavior

Some cypress tests fail with
```
CypressError: Timed out after waiting `120000ms` for your remote page to load.
Your page did not fire its `load` event within `120000ms`.
```
Which I assume is because the page wouldn't have loaded by 120000ms, but, if you check the screenshot - `Test information header` is failing with this page load issue, so if the page is not loading at all, how is the second test passing? the second test just does some assertion on the visited url in first.
All of these tests were working fine with cypress 7.6.0, I have just upgraded to 10.6.0, and they started failing. JFYI, this app is based on Vite (if that is of some issue, no we haven't updated vite)

<img width="762" alt="Screenshot 2022-08-27 at 14 05 16" src="https://user-images.githubusercontent.com/18121502/187022459-4854748f-ff76-4cd4-a7a7-dbe838df8a47.png">

<img width="890" alt="Screenshot 2022-08-27 at 14 14 38" src="https://user-images.githubusercontent.com/18121502/187022760-969400f4-630f-4a11-9443-19740b8dcace.png">

### Desired behavior

These tests should work the same with both our older cypress version as well as the newer

### Test code to reproduce

Attached screenshot above, not sure if I can create a reproducible example, as this is some flaky issue

### Cypress Version

10.6.0

### Node version

16.15.0

### Operating System

macOs 12.15.1

**Comment by maddhruv** [comment]
After going through this - https://github.com/cypress-io/cypress/issues/2938#issuecomment-549565158
Looks like it was very specific with Electron, as soon as I start using Chrome, this error doesn't happen.
But I still see some flakyness around tests, with very CI re-run a new random test fails for me

**Comment by lmiller1990** [comment]
Hi! This sounds similar to https://github.com/cypress-io/cypress/issues/22968

Are you running against Vite in dev mode or production? If you are running against Vite in dev mode, can you try building your production bundle and running against that? I have a theory that Vite in dev mode does something different causing massive network bottlenecks (see https://github.com/cypress-io/cypress/issues/22968 for more context).

Also -- Cypress 10 is the latest major. 9->10 is a bit of an upgrade, but you should be able to move to v8 and v9 relatively painlessly. I'd also recommend upgrading incrementally to see if that fixes the problem (possibly we fixed/improved something across one of those major versions).

**Comment by lmiller1990** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Happy to reopen if you can provide more information. Thanks!

**Comment by maddhruv** [comment]
Sorry, I missed the notification

> Are you running against Vite in dev mode or production?

No I am running vite in production mode and using the `vite preview` server to test

**Comment by lmiller1990** [comment]
Did you try going to Cypress 9 before going straight from 7->10? Without access to your actual code, I can only really make suggestions - I'm guessing this site is not publicly available? I'm trying to isolate if this is a Cypress 9->10 regression, or something else.

Another thing you can try is `DEBUG=cypress:* npx cypress run`. You should see lots of debug logs in the terminal, which you could copy+paste here.

**Comment by maddhruv** [comment]
No I didn't try v9 before v10, and the site is not publicly available :sad: 
let me try DEBUG mode and see if there is something

**Comment by ZachJW34** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by lukas-mertens** [comment]
@ZachJW34 @lmiller1990  Interestingly I just stumbled over this issue as I have this exact issue, with vite preview and cypress in chrome. Luckily the repo I am working on is open source so you should be able to reproduce this easily.

Here is a ci run with this issue: https://github.com/EVerest/everest-admin-panel/actions/runs/8492940914?pr=121
This is the PR: https://github.com/EVerest/everest-admin-panel/pull/121
And here is a video of the test run where the failing test is run in isolation where you can see that the page is loading properly and doing exactly what it is supposed to do:


https://github.com/cypress-io/cypress/assets/10901304/7b545088-1147-4078-8c4b-a2728dbd8079

The test spec which is failing is the following
```js
  it('should automatically connect if autoConnect is set to true', () => {
    cy.visit('/');
    cy.get('[data-cy="auto-connect-checkbox').click();
    cy.get('[data-cy="server-list-item').contains('Simulator').click();
    cy.get('[data-cy="hamburger-menu"]').click();
    cy.get('[data-cy="switch-instance"]').click();

    // should not reconnect automatically after switching instance, only on page reload
    cy.get('[data-cy="server-list-item"]', {timeout: 6000}).contains('Simulator').should('be.visible');
    cy.wait(1000);
    cy.get('[data-cy="server-list-item"]').contains('Simulator').should('be.visible');

    // check if automatically reconnected now
    cy.visit('/');
    cy.get('[data-cy="hamburger-menu"]', {timeout: 6000}).should('be.visible');
  });
```

As you can see in the video the application correctly auto-connects and goes to the main page, but cypress is still stuck in the `cy.visit('/')` command (the second one).

Interestingly the issue doesn't appear anymore after switching to `pnpm dlx http-server dist -p 4173`, only with vite preview (so don't be confused, I switched to this for now, to be able to continue working for now). Just replace that by pnpm preview in the ci to reproduce the issue
