### ISSUE TITLE
Auto Generate a Client From OpenAPI Specification / Swagger

### ISSUE THREAD

**Issue by dudiharush** [cypress-io/cypress#23583]
### What would you like?

I'd like to auto generate a client from open api, that calls the server, by using cy.request function, so i can call it from the cypress tests and update the server.

### Why is this needed?

it's easier to call the server with an auto-generated client, so we don't need to copy urls and apis from the server.

### Other

example project: https://github.com/ferdikoomen/openapi-typescript-codegen (not using cy.request)

**Comment by nagash77** [comment]
@dudiharush Can you provide more detail on what you are trying to accomplish.  It isn't clear to us what you are trying to accomplish with this request.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by bilarallen** [comment]
Hi @nagash77 I think me and @dudiharush want to achieve the same goal for this issue. Recently our team has wanted something like this.

What we want to achieve is to generate a JS/TS API client from Swagger (not sure if this is what they called CodeGen) ? I have a spec from swagger in a `.json` format and our team wants to create a class for it sort of like SDK so we can easily perform HTTP requests, I'm thinking if this is possible, and also I'm considering some future problems like we won't be able to use the `cy.request()` commands if ever we implement it this way (it will be beneficial not only for us but also to others if we can integrate codegen using the default `cy.request()` command). One reason why we are planning to do this is to avoid writing the `cy.request()`'s headers/body manually (particularly its 'key') given that we already have API definition from Swagger Documentation in json file. [Here's ](http://biercoff.com/my-small-investigation-about-swagger-codegen-generation-in-typescript/)a good short read about the codegen and hoping that something similar like this can be introduced in cypress 🙏

**Comment by jreimone** [comment]
Hey there, if you want to generate Cypress-compatible API clients please have a look at this project: https://github.com/QualityMinds/openapi-generator-typescript-cypress

We provide generator templates which extend the `typescript-fetch` templates. The result is API clients which can be used in Cypress tests. Let me know what you think.
