### ISSUE TITLE
Github Workflow || Firefox browser ||  Digits Scrambled when using type on Date Field

### ISSUE THREAD

**Issue by RemaKoul** [cypress-io/cypress#23589]
### Current behavior

1. Entering Date in MM/DD/YYYY format in our application
2. For ex, if I input Date as : 01/01/1990 , it gets entered as 01/01/0090
3. I have tried entering several Dates, but it ends up with entering 00 in YYYY
![image](https://user-images.githubusercontent.com/21169655/187221947-4a3a6438-e904-4788-b2b2-a69307c57f75.png)

Note  : 
1. Works fine on Firefox on my local runs  ( On Windows)
2. Issue only appears when run through github workflow  . Its being run on Windows 
3.  For Chrome and Edge browser , Date is entered as provided through Input. 

So issue is restricted to only Firefox browser being run on Pipeline

### Desired behavior

1. Date should be entered as provided by the Input 
2. There should not be any difference in behavior with change in browser

### Test code to reproduce

1. Log on to application ( React JS based) on Firefox Browser (  Firefox 103 (headless)  )
2. Enter Date in desired format, ie MM/DD/YYYY
3. Observe incorrect entry in application

### Cypress Version

10.5.0

### Node version

v16.13.0

### Operating System

Windows 10

**Comment by RemaKoul** [comment]
@emilyrohrbough Did you get a chance to look in the issue please? Please revert if you need any information.

**Comment by emilyrohrbough** [comment]
@RemaKoul Without a reproduction, it'll be hard for me to provide meaningful feedback.

Based on what you have shared, I am wondering if the date input is handling the events correctly. Can you share the code snippet? Also have you tried typing the entire input value vs one character at a time?
```
.type('11112012')
```

**Comment by RemaKoul** [comment]
Hi Emily ,

Sorry for responding late  . 
I have tried the suggestion you have shared, however same behavior is observed  .
Since its just data input  , code is pretty simple  ->

  static fillPatientDoB (dateOfBirth) {
    cy.get('[data-testid="dateOfBirth"]')
    .should('be.visible')
    .find('input')  // Emily , Have tried removing  this line . plays no difference
    .type(dateOfBirth)
  return this
}

Parameter **dateOfBirth** recieves its value from calling method . As mentioned in defect description i have tried  :
1. Different dates
2. Formats like 11112012 , 11/11/2012,11-11-2012,1111-20-12,1111/20/12,1 wait 1wait 1wait 1wait 2 wait 0 wait1 wait 2 wait, individual key strokes with wait added , individual key strokes without wait
3. Invalid values as well just to check behavior but 00 comes in place

Expected format is mm/dd/yyyy
![image](https://user-images.githubusercontent.com/21169655/189058569-cca30f1a-628b-4716-8328-7ead61f2b04c.png)

Please revert if you need more details

**Comment by conversaShawn** [comment]
@emilyrohrbough I can provide repro internally

**Comment by emilyrohrbough** [comment]
@RemaKoul Thank you for providing a reproducible example. I was able to repo this behavior. I am not sure why this is no longer working. I will flag as a bug and get it routed to my team. I am unsure when this will get picked up though.

In the mean time, you might try leveraging https://github.com/dmtrKovalenko/cypress-real-events#cyrealtype to see if this will allow you to type consistently in your test.

**Comment by RemaKoul** [comment]
https://user-images.githubusercontent.com/21169655/189890865-3473e71a-f8e6-4e91-95dc-8c81a02cc134.mp4

Hi @emilyrohrbough , Thanks for the workaround. However it does not work. The solution is limited to Chromium based browsers. Please advise further

**Comment by emilyrohrbough** [comment]
@RemaKoul Unfortunately, I have no further insights at this time. Is the application you are testing using React 18?

**Comment by RemaKoul** [comment]
Our application is based on React 17.  Will that pose any difference, please suggest . 

also, do we have any SLA when the bug would be resolved?

**Comment by emilyrohrbough** [comment]
@RemaKoul No one is actively working on this. If you have time, we would love a contribution for this fix! 🙏🏻

**Comment by RemaKoul** [comment]
HI @emilyrohrbough ,wanted to share an update on the FF date entry issue.

Our Development team made some changes to date picker library , and as a result the issue has been fixed on its own . We tried running a couple of times on FF on pipeline and Date was entered as per input. 
cc  : @conversaShawn

**Comment by emilyrohrbough** [comment]
@RemaKoul Great! I'm going to close this issue at this time.
