### ISSUE TITLE
Parallel execution on TravisCI results in different tests running in different environments

### ISSUE THREAD

**Issue by mb1069** [cypress-io/cypress#2359]
Hi,
I've implemented a large set of tests for our website, and we have been using multiple versions of node 8 to debug flakiness in our test designs.

After upgrading to Cypress 3.1, we've used the new parallel feature to speed up our tests, which is working very well! However, our tests are now being dispatched between node versions in TravisCI, as you can see below. Half the tests are run in node 8.11.1, half in 8.11.2, and the job for 8.11.3 is failing due to starting off too late. 

### Current behavior:
https://travis-ci.org/EBI-Metagenomics/ebi-metagenomics-client/jobs/416835626
https://travis-ci.org/EBI-Metagenomics/ebi-metagenomics-client/jobs/416835627
https://travis-ci.org/EBI-Metagenomics/ebi-metagenomics-client/jobs/416835628
### Desired behavior:

All tests should run on all node versions.

Thank you for an awesome testing framework!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
