### ISSUE TITLE
Cypress cancelling xhr request on chrome browser

### ISSUE THREAD

**Issue by snar13** [cypress-io/cypress#23607]
### Current behavior

0

I am trying to launch a URL using the CYPRESS tool. The issue here is when I try to launch the URL there are some XHR request which is getting canceled by cypress runner due to which the correct page is not getting loaded.

Please note that the issue is only happening on chrome browser and works fine on firefox

Also, these XHR request load just after the URL is launched ad takes very less time to respond. Not sure about what the exact issue is. enter image description here

### Desired behavior

XHR should not be blocked

### Test code to reproduce

can't share as its a test env

### Cypress Version

10.3.1

### Node version

14

### Operating System

Window 10

**Comment by nagash77** [comment]
@snar13 Unfortunately without more details and instructions on how to reproduce this issue we will be unable to help.

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by gopi-git-hub** [comment]
@emilyrohrbough ,Can you please provide the possible scenarios when cypress cancel a api call.If you check this link :https://stackoverflow.com/questions/73496431/cypress-cancelling-xhr-request-on-chrome-browser .you may find initiator is cypress.runner.js for that api call.

**Comment by emilyrohrbough** [comment]
We will cancel pending XHRs on window:unload
