### ISSUE TITLE
Cypress not working with PKI certificate

### ISSUE THREAD

**Issue by yashgandhi876** [cypress-io/cypress#23606]
### Current behavior

Background (without cypress): If I open the website in chrome, first it will show me a popup to select the certificate. once selected you will be logged in directly and for every other tab you need to again select the certificate. If I cancel the popup then I get this error - 
``` body: { error: "You must provide a cert to use this endpoint, you can not skip this request" } ```

Current behavior: I am passing the PKI certificate (CRT, key, passphrase) in the cypress.config.ts file in the clientCertificate, 

``` 
export default defineConfig({
      e2e: {....},
      clientCertificate: { url: "ACB.com", ca: [], certs: [{cert: "path/to/cert/file.crt", key: "path/to/key/file.key", passphrase: "password"}]}
})
```
now in the test case, I am visiting/requesting that same URL but I am getting this error
``` body: { error: "You must provide a cert to use this endpoint, you can not skip this request" } ```
also, that URL redirect twice one from login and second to auth and then returns 400 error

### Desired behavior

it should work properly once we have pass certs then it should not show any error and all test should pass.tests

### Test code to reproduce

pass certs in cypress.config.ts and access the website that needs a PKI certificate to log in. Run cypress headless
```
    cypress run --headless --browser edge --spec "cypress/test/file/location/**"
```

### Cypress Version

10.2.0

### Node version

v16.15.1

### Operating System

Windows 10 20H2

**Comment by yashgandhi876** [comment]
Got solution - After digging deeper into the network tab we found that our website URL was redirecting to another URL, and that URL needs certs not our website URL. Cypress does not pass cert to redirects, so we have to pass certs for that redirected URL in client Certification.

**Comment by emilyrohrbough** [comment]
@yashgandhi876 Glad you were able to get this figured out! Thank you.
