### ISSUE TITLE
Slow builds fail with parallel option on Codeship Basic

### ISSUE THREAD

**Issue by carloscheddar** [cypress-io/cypress#2361]
### Current behavior:
Slow builds fail after faster builds have completed the cypress process by triggering the `The run you are attempting to access is already complete and will not accept new groups.` error.

### Desired behavior:

Show a warning with the already complete message instead of sending an error code. Or allow us to set a flag to ignore this error.

### Steps to reproduce:
- Trigger multiple builds with the parallel option
- Slow one of the builds to allow cypress to finish on the other ones
- Wait for the slow build to fail

### Versions
Cypress: 3.1, Ubuntu, Chrome 68

**Comment by jennifer-shehane** [comment]
Hey - we do understand your issue and anticipated this needing configuration. How it works now is that the 'run' will stay open for 60000ms after it's last work has been completed - waiting for more groups to start. If no groups start within this time period - the run is then closed to new groups.  

We've already found the need in our own projects to increase this time period (to allow for build time)

Our short term plan is to offer a way to configure this time, to allow the run to stay 'open' longer to await any new groups. We're currently working on this, so will let you know when it is released.

**Comment by mb1069** [comment]
@jennifer-shehane Could this issue relate to #2359 ? I noticed the splitting across environments due to the issue mentioned above.

**Comment by jennifer-shehane** [comment]
Hi @carloscheddar, the Dashboard now allows you to edit the 'delay' that each run within a project should wait for new groups before completing. You can find this within your project settings:

<img width="1296" alt="screen shot 2018-08-22 at 6 24 09 pm" src="https://user-images.githubusercontent.com/1271364/44494161-c21f2300-a638-11e8-9558-63e72843d4f3.png">

Please let us know if you have any questions!
