### ISSUE TITLE
CLI Option to pass cypress env file

### ISSUE THREAD

**Issue by jwedel** [cypress-io/cypress#23617]
### What would you like?

I would like to call `cypress open --env-file cypress.env-qa.json` to specify a different env file than the default `cypress.env.json`.

### Why is this needed?

 We have multiple environments with around 15 env variables each that needs to be set. It is very tedious to specify that using individual -e environment variables.

Currently we have multiple env files and if we need to change the env, we overwrite the default env file with some other content.

**Comment by jwedel** [comment]
Hi @emilyrohrbough , were you able to look at my FR? Is it feasible to implement or is it maybe already possible and I just didn't find it in the docs?

Thx, Jan

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest, we’ll close this as not planned.
