### ISSUE TITLE
Incorrect work of setupNodeEvents

### ISSUE THREAD

**Issue by tamtakoe** [cypress-io/cypress#23626]
### Current behavior

I see `ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported` and I want to disable GPU by `--disable-gpu` flag. 
And I see logs
```
Opening Cypress...
ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

<...>

Cypress: 10.6.0
Browser: Electron 102 (headless)
Node Version: 16.16.0 (/usr/local/bin/node)

<...>     
                                                                                     
  Running: app.cy.ts (1 of 3)
// My console.log
browser {
  name: 'electron',
  channel: 'stable',
  family: 'chromium',
  displayName: 'Electron',
  version: '102.0.5005.148',

<...>
```

### Desired behavior

1. Browser should run after `before:browser:launch` event
2. I see browser: 'electron', but family: 'chromium'. Which docs where flags described I should read Chromium or Electron?
3. How to prevent `dri3 extension not supported` error for now?

### Test code to reproduce

```
e2e: {
    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser: any = {}, launchOptions) => {
        console.log('browser', browser, 'launchOptions', launchOptions)
        launchOptions.args.push('--disable-gpu')
```

How to Cypress running https://github.com/nrwl/nx/blob/c7249db3861d0ed1fa7d47b360825ee8f4d27b5f/packages/cypress/src/executors/cypress/cypress.impl.ts#L228

### Cypress Version

10.6.0

### Node version

16.16.0

### Operating System

Debian Linux 4.18.0-348.20.1.el8_5.x86_64 amd64 (Docker image: node:16.16.0-bullseye-slim)

**Comment by lmiller1990** [comment]
I think the gpu warning is coming from the Electron app we launch (where you choose your testing type), not the actual browser. You should be able to modify what flags that launches with [like this](https://docs.cypress.io/api/plugins/browser-launch-api#Modify-Electron-app-switches). I tried `ELECTRON_EXTRA_LAUNCH_ARGS=--disable-gpu` but it did not work - I still got the dri3 warning.

As for your questions

> Browser should run after before:browser:launch event

I think this is executing correctly. I added the event to my test app and threw an error in there - the browser was never launched.

> I  see browser: 'electron', but family: 'chromium'. Which docs where flags described I should read Chromium or Electron?

I'm not sure what you are asking here - can you clarify? Both chrome and chromium are of the `chromium` family - so if you want something to apply to both of those, check against `family`. If you want to do something Chrome or Electron specific, use `browser`.

> How to prevent dri3 extension not supported error for now?

I don't think you can do much right now - we need to add it to our list of "ok to swallow" warnings. We can put it here: https://github.com/cypress-io/cypress/blob/develop/cli/lib/exec/spawn.js#L47. I tested this locally, and you can too - in your `node_modules/cypress/lib/exec/spawn.js` you can add a check for your warning, and it will not be displayed.

I am unsure if it's actually okay to swallow this, or if the `--display-gpu` is even the correct flag to pass, though - it doesn't seem to prevent the warning.

**Comment by tamtakoe** [comment]
I set `ENV ELECTRON_EXTRA_LAUNCH_ARGS=--disable-gpu` inside my Dockerfile and don't have the error after `Opening Cypress...` but still have it after `before:browser:launch` of each test
```
CreatePlatformSocket() failed: Address family not supported by protocol
ERROR:gpu_memory_buffer_support_x11.cc dri3 extension not supported.
```
Hmm...

**Comment by lmiller1990** [comment]
Hm, that's a strange one. I am able to reproduce `dri3 extension not supported` on launch, and silence it with `ELECTRON_EXTRA_LAUNCH_ARGS`, but I do not see it prior to every spec - I tried both Electron and Chrome. I'm using GH Actions - I guess my environment is slightly different.

As an aside, is this preventing you from running tests or just a minor annoyance?

**Comment by tamtakoe** [comment]
I use NX for run cypress e2e tests. If I use `nx e2e web-e2e` I see
```                                                                                          
  Running:  app.cy.ts                                                                       (1 of 3)
62:0905/220021.136229:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
533:0905/220021.144641:ERROR:gpu_memory_buffer_support_x11.cc(44) dri3 extension not supported.
562:0905/220021.441206:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220021.485954:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220022.071935:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220022.098563:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220022.308979:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220022.312102:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220022.315451:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220022.319151:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220022.450923:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
  web
562:0905/220024.764710:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220024.769535:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220025.270594:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220025.857365:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220025.898499:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
562:0905/220025.905058:ERROR:socket_posix.cc(96) CreatePlatformSocket() failed: Address family not supported by protocol (97)
    ✓ should display welcome message (805ms)


  1 passing (849ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     app.cy.ts                                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```
If I use `nx e2e web-e2e --prod` I see the same errors, but
```
<...>

1) "before each" hook for "should display welcome message"


0 passing (1s)
1 failing

1) web
       "before each" hook for "should display welcome message":
        TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read properties of undefined (reading 'api')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

<...>
```

I still don't manage to which problem with `--prod` flag

**Comment by lmiller1990** [comment]
Can you please share your test - or better yet, minimal repro with your code set up, or instructions on how to configure it? This will help speed up debugging greatly.

**Comment by lmiller1990** [comment]
I'll need more info to continue debugging this. I suspect it's some kind of tooling conflict between NX, Cypress, etc... if you can reproduce and share a minimal reproduction, happy to reopen -- would be great to solve this, but there's only so much I can do without an example to debug. At this point, I do not see any actionable information to continue debugging, so I'll close this one out.

**Comment by jackykwandesign** [comment]
@lmiller1990 
I get the same error, and reproduce is really easy.
Just create a NX project in a remote cloud machine

My dev env: 
- local: window 10 + vscode + ssh remote
- remote server: ubuntu 20.04 server
i use vscode to dev in ubuntu, and website of my app show correctly, but cypress ui never shown in --watch flag

`nx e2e app-fe` / `nx e2e app-fe --prod` will work and generate report / screenshots / video
![image](https://user-images.githubusercontent.com/46065771/202521876-ac9aa7bc-5c7f-446d-920e-26175ba13efa.png)

but when running in `nx e2e app-fe --watch` mode, the cypress browser ui will never prompt, just stuck at the `[3192866:1117/175430.681089:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported`
![image](https://user-images.githubusercontent.com/46065771/202522052-0c8b5e4f-090b-4474-b724-a9211bfd4061.png)

**Comment by lmiller1990** [comment]
@jackykwandesign do you have the same problem locally or only in a Nx cloud machine?

**Comment by sbal5488** [comment]
how was this issue resolved. am getting the same problem 
2023-01-25T21:15:37.131+05:30 | │ Cypress: 12.4.0 │
-- | --
  | 2023-01-25T21:15:37.131+05:30 | │ Browser: Electron 106 (headless) │
  | 2023-01-25T21:15:37.131+05:30 | │ Node Version: v16.18.1 (/var/lang/bin/node) │
  | 2023-01-25T21:15:37.131+05:30 | │ Specs: 1 found (example.cy.js) │
  | 2023-01-25T21:15:37.131+05:30 | │ Searched: cypress/e2e/**/*.cy.{js,jsx,ts,tsx} │
  | 2023-01-25T21:15:37.131+05:30 | └────────────────────────────────────────────────────────────────────────────────────────────────┘
  | 2023-01-25T21:15:37.133+05:30 | ────────────────────────────────────────────────────────────────────────────────────────────────────
  | 2023-01-25T21:15:37.133+05:30 | Running: example.cy.js (1 of 1)
  | 2023-01-25T21:15:37.174+05:30 | [25:0125/154537.174131:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
  | 2023-01-25T21:15:37.189+05:30Copy[25:0125/154537.189162:ERROR:socket_posix.cc(93)] CreatePlatformSocket() failed: Address family not supported by protocol (97) | [25:0125/154537.189162:ERROR:socket_posix.cc(93)] CreatePlatformSocket() failed: Address family not supported by protocol (97)
  | 2023-01-25T21:15:37.602+05:30 | 2023-01-25T15:45:37.601Z 8ecff24b-add0-46d9-8090-70e90d50c8ad ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: The Test Runner unexpectedly exited via a exit event with signal SIGILL\n\nPlease search Cypress documentation for possible solutions:\n\nhttps://on.cypress.io\n\nCheck if there is a GitHub issue describing this crash:\n\nhttps://github.com/cypress-io/cypress/issues\n\nConsider opening a new issue.\n\n----------\n\nPlatform: linux-x64 (Amazon Linux - 2 (Karoo))\nCypress Version: 12.4.0","reason":{"errorType":"Error","errorMessage":"The Test Runner unexpectedly exited via a exit event with signal SIGILL\n\nPlease search Cypress documentation for possible solutions:\n\nhttps://on.cypress.io\n\nCheck if there is a GitHub issue describing this crash:\n\nhttps://github.com/cypress-io/cypress/issues\n\nConsider opening a new issue.\n\n----------\n\nPlatform: linux-x64 (Amazon Linux - 2 (Karoo))\nCypress Version: 12.4.0","known":true,"stack":["Error: The Test Runner unexpectedly exited via a exit event with signal SIGILL","","Please search Cypress documentation for possible solutions:","","https://on.cypress.io","","Check if there is a GitHub issue describing this crash:","","https://github.com/cypress-io/cypress/issues","","Consider opening a new issue.","","----------","","Platform: linux-x64 (Amazon Linux - 2 (Karoo))","Cypress Version: 12.4.0"," at /var/task/node_modules/cypress/lib/errors.js:264:17"]},"promise":{"isFulfilled":false,"isRejected":true,"rejectionReason":{"errorType":"Error","errorMessage":"The Test Runner unexpectedly exited via a exit event with signal SIGILL\n\nPlease search Cypress documentation for possible solutions:\n\nhttps://on.cypress.io\n\nCheck if there is a GitHub issue describing this crash:\n\nhttps://github.com/cypress-io/cypress/issues\n\nConsider opening a new issue.\n\n----------\n\nPlatform: linux-x64 (Amazon Linux - 2 (Karoo))\nCypress Version: 12.4.0","known":true,"stack":["Error: The Test Runner unexpectedly exited via a exit event with signal SIGILL","","Please search Cypress documentation for possible solutions:","","https://on.cypress.io","","Check if there is a GitHub issue describing this crash:","","https://github.com/cypress-io/cypress/issues","","Consider opening a new issue.","","----------","","Platform: linux-x64 (Amazon Linux - 2 (Karoo))","Cypress Version: 12.4.0"," at /var/task/node_modules/cypress/lib/errors.js:264:17"]}},"stack":["Runtime.UnhandledPromiseRejection: Error: The Test Runner unexpectedly exited via a exit event with signal SIGILL","","Please search Cypress documentation for possible solutions:","","https://on.cypress.io","","Check if there is a GitHub issue describing this crash:","","https://github.com/cypress-io/cypress/issues","","Consider opening a new issue.","","----------","","Platform: linux-x64 (Amazon Linux - 2 (Karoo))","Cypress Version: 12.4.0"," at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)"," at process.emit (node:events:513:28)"," at eventToObjectGenerator.promiseCreated (/var/task/node_modules/bluebird/js/release/debuggability.js:258:33)"," at activeFireEvent (/var/task/node_modules/bluebird/js/release/debuggability.js:301:44)"," at fireRejectionEvent (/var/task/node_modules/bluebird/js/release/debuggability.js:703:14)"," at Promise._notifyUnhandledRejection (/var/task/node_modules/bluebird/js/release/debuggability.js:90:9)"," at Timeout.unhandledRejectionCheck [as _onTimeout] (/var/task/node_modules/bluebird/js/release/debuggability.js:39:25)"," at listOnTimeout (node:internal/timers:559:17)"," at processTimers (node:internal/timers:502:7)"]}
  | 2023-01-25T21:15:37.609+05:30 | Unknown application error occurred Runtime.Unknown

**Comment by sbal5488** [comment]
How as this Resolved ? 
Cypress: 12.4.0 
```
2023-01-25T21:15:37.131+05:30	│ Browser: Electron 106 (headless) │

2023-01-25T21:15:37.131+05:30	│ Node Version: v16.18.1 (/var/lang/bin/node) │

2023-01-25T21:15:37.131+05:30	│ Specs: 1 found (example.cy.js) │

2023-01-25T21:15:37.131+05:30	│ Searched: cypress/e2e/**/*.cy.{js,jsx,ts,tsx} │



	Running: example.cy.js (1 of 1)
:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

2023-01-25T21:15:37.189+05:30

Copy
[25:0125/154537.189162:ERROR:socket_posix.cc(93)] CreatePlatformSocket() failed: Address family not supported by protocol (97)
[25:0125/154537.189162:ERROR:socket_posix.cc(93)] CreatePlatformSocket() failed: Address family not supported by protocol (97)
```

**Comment by lmiller1990** [comment]
Need a reproduction, and also an explanation - are you unhappy about the warning? Or is this preventing you from executing your tests?

> :ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

This should not prevent you from running Cypress on CI - what behavior are you seeing?

**Comment by sbal5488** [comment]
Attached is the log file which has debug information.

Let me explain the problem


  1.  Created a docker image and published to ECR  (followed this link, https://github.com/magJ/cypress-lambda-example)
  2.  Invoke docker image from lambda function, lambda handler got invoked successfully, but when we invoke cypress , it is giving permission denied


cypress.run({
    reporter: 'junit',
    browser: 'chromium',
    record: false,
    headless: true,
    chromeWebSecurity: false,
    key:'0f424505-76e2-402e-a539-5d4600e39df0',
    configFile: './cypress.config.js'
  })



  1.  AWS + Lambda + Docker + Cypress is my requirement.

After executing the lambda, it is throwing me an error as attached in the log file

Any suggestions to this problem is highly appreciated.

Please note, I have just started using cypress.




***@***.***
Srinivas Balivada | Associate Director, Software Development
Plot No. 43, Ground & First Floor
Hitech City, Madhapur
Hyderabad - 500 081, India
Mobile : +919701005454
