### ISSUE TITLE
Typo in viewport menu

### ISSUE THREAD

**Issue by pratiqdev** [cypress-io/cypress#23632]
### Current behavior

Dropdown menu for firefox browser dimensions has missing text or missing link.  

### Current text:

**Additionally, you can override this value 
in your or via the command.**

![Screenshot from 2022-08-30 18-04-16](https://user-images.githubusercontent.com/53705976/187552018-5ba8e16c-8c2d-47f9-ad19-bea26bb9531e.png)

### Expected text:

**Additionally, you can override this value 
in your ____ or via the command ____.**

**Additionally, you can override this value 
in your `cypress.config` or via the command `npx cypress something`.**

### Test code to reproduce

- `$ yarn add cypress`
- `$ yarn run cypress open`
- Select E2E testing
- Select Firefox browser
- Run example test `spec.cy.ts`
- Open then browser viewport dimensions dropdown menu

### Cypress Version

^10.7.0

### Node version

16.15.0

### Operating System

Ubuntu 20.04.5 LTS

### Other

- DEVICE: acer a515 laptop
- MEMORY: 5.7gib
- CPU: AMD® Ryzen 3 3200u with radeon vega mobile gfx × 4 
- GFX: AMD® Radeon(tm) vega 3 graphics
- OS NAME: Ubuntu 20.04.5 LTS
- OS TYPE: 64-bit
- GNOME: 3.36.8
- WINDOW: X11
- PKG MANAGER: yarn
- TERMINAL: vscode built-in

**Comment by nagash77** [comment]
@pratiqdev Great catch!  This should be a straight forward issue and we would love it if you could open a PR to resolve this issue.  See our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by kel-si** [comment]
Hello, I would happy to tackle this issue as a first-time contributor.

**Comment by pratiqdev** [comment]
I have already forked the repo and am currently looking for a fix

**Comment by nagash77** [comment]
Hi @pratiqdev, any updates on this issue?

**Comment by nagash77** [comment]
@kel-si I haven't heard back from @pratiqdev so I am not sure if they are going to be making a PR for this issue.  Feel free to take a stab at it if you have some time and we will try and get this over the line and merged to help folks out.

**Comment by FireNdIce3** [comment]
@nagash77  I have done something in the JSON file to change the config text but I am a bit confused about the use of numbers within curly braces in that.
My PR id is #23789

**Comment by nagash77** [comment]
@FireNdIce3 I see our Cypress devs have been working with you directly in the PR.

**Comment by pratiqdev** [comment]
@nagash77 - I assumed this would be a straight-forward issue as well...

PR #23789 provides a temporary solution, but the parsing / replacing error should be addressed directly.

I was unable to resolve the issue locally so I have not created a PR. I took some notes while testing / exploring and I will include them here.

## Files

1. `packages/frontend-shared/src/locales/en-US.json`
2. `packages/app/src/runner/SpecRunnerHeaderOpenMode.vue` 
3. `packages/app/src/runner/SpecRunnerHeaderOpenMode.cy.tsx` 
4. `packages/app/cypress/e2e/cypress-in-cypress-e2e.cy.ts`

---

## Origin 

The issue seems to originate within the function responsible for 
parsing and replacing in-string placeholder values with real values.
This text has string-vars like: `in string var like {this} replaced`.

The original (unreplaced) text segment exists in a locale source (file-1)
at `runner.viewportTooltip.configText`

The adjacent entry of `runner.viewportTooltip.infoText` has its 
placeholder values correctly replaced at `{0}`, `{1}` and `{2}`

---

The locale object values are passed to an `<i18n-t>` component as the 
`keypath` prop in (file-2)

```ts
<i18n-t
  tag="p"
  keypath="runner.viewportTooltip.configText"
  class="mb-24px"
>
```
The test file (file-3) contains a test at line 196 that checks for the 
existence and visibility of the correctly replaced string:


```ts
cy.contains('Additionally, you can override this value in your cypress.config.js or via the cy.viewport() command.')
                                                               ^^^^^^^^^^^^^^^^^            ^^^^^^^^^^^^^
.should('be.visible')
```

There is also an example cypress test in (file-4) that tests for the 
adjacent config text `runner.viewportTooltip.infoText` but, does not 
test for `runner.viewportTooltip.configText`

**Comment by emilyrohrbough** [comment]
@pratiqdev Can you move this to the PR thread?

**Comment by pratiqdev** [comment]
Yes, I commented this in PR  #23789
