### ISSUE TITLE
Spike: CT Stack Traces

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#23630]

**Comment by lmiller1990** [comment]
From catch up with Zach. This shows the problem.

<img width="1208" alt="Screen Shot 2022-08-31 at 7 13 26 am" src="https://user-images.githubusercontent.com/19196536/187544372-79682980-e3c0-4205-a7ff-f3ef5693ee35.png">

**Comment by ZachJW34** [comment]
Tech-Brief: https://github.com/cypress-io/tech-briefs/pull/49
