### ISSUE TITLE
Latest Cypress + TypeScript results in error due to out of date jquery type definitions imported by cypress

### ISSUE THREAD

**Issue by basarat** [cypress-io/cypress#2363]
### Current behavior:
TypeScript Error

```
node_modules/@types/jquery/index.d.ts:6107:66 - error TS2344: Type '"timeout" | "onreadystatechange"
 | "responseType" | "withCredentials" | "msCaching"' does not satisfy the constraint '"abort" | "ope
n" | "timeout" | "onreadystatechange" | "responseType" | "withCredentials" | "readyState" | "respons
e" | "responseText" | "responseURL" | "responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.

  Type '"msCaching"' is not assignable to type '"abort" | "open" | "timeout" | "onreadystatechange"
| "responseType" | "withCredentials" | "readyState" | "response" | "responseText" | "responseURL" |
"responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.

   interface XHRFields extends Partial<Pick<XMLHttpRequest, 'onreadystatechange' | 'respon
seType' | 'timeout' | 'withCredentials' | 'msCaching'>> { }
```

### Desired behavior:

No Error.

### Steps to reproduce:

```
npm init -y
npm install typescript cypress
npx tsc --init --lib es6,dom
npx tsc
```

![image](https://user-images.githubusercontent.com/874898/44249356-cc08e680-a232-11e8-86ba-303fefe66475.png)

### Versions

```
+ cypress@3.1.0
+ typescript@3.0.1
```

### Suggested fix
Bumping the jquery type definitions here : https://github.com/cypress-io/cypress/blob/68b9c91839e0ead57fcf17f8c161533bf7fd4497/cli/package.json#L42 *should* (because DefinitelyTyped is updated to TS 3.0) fix the issue :rose:

**Comment by jennifer-shehane** [comment]
Opened a PR to bump @types/jquery - could you try your example above within that fix? https://github.com/cypress-io/cypress/pull/2369

**Comment by basarat** [comment]
Verified fixed :rose:

# Steps for verification 

Get error:
```
npm init -y
npm install typescript cypress
npx tsc --init --lib es6,dom
npx tsc
```
Fix Error: 
```
rm -rf ./node_modules/@types/jquery
npm i @types/jquery@3.3.6
npx tsc
```

**Comment by sarink** [comment]
Is there a workaround until this gets merged?

**Comment by basarat** [comment]
@sarink stay on ts 2.9 🌹

**Comment by sindresorhus** [comment]
@jennifer-shehane Would you be able to do a patch release? It's currently impossible to use Cypress for anyone that's on TypeScript 3.

**Comment by martindzejky** [comment]
This is a problem for anyone using Angular 7 because it requires Typescript 3. 😢

**Comment by martindzejky** [comment]
Actually, I managed to fix my build by just explicitly adding types for jquery: `yarn add @types/jquery`.

**Comment by developer239** [comment]
Almost one year later this is still an issue. 🙂
