### ISSUE TITLE
@cypress/schematics: no spec file generated with schematic v2.1.0

### ISSUE THREAD

**Issue by cexbrayat** [cypress-io/cypress#23642]
### Current behavior

`ng add @cypress/schematic` no longer creates a `spec.cy.ts` file in `cypress/e2e`.

This is maybe the intended behavior, but I did not see it listed as a change.

The file is still created with v2.0.3

### Desired behavior

`cypress/e2e/spec.cy.ts` should still be created.

### Test code to reproduce

```
ng new no-cypress-spec --defaults
cd no-cypress-spec
ng add @cypress/schematic@2.1.0 --defaults --skip-confirmation
```

Listing the files in `cypress` we only have:
```
fixtures
support
tsconfig.json
```

### Cypress Version

v10.7.0

### Node version

v16.17.0

### Operating System

macOS

**Comment by lmiller1990** [comment]
Hi @cexbrayat - thanks for the bug report :+1: 

Not sure if this is intended or not -- @admah or @jordanpowell88 might be able to clarify?

**Comment by admah** [comment]
@cexbrayat there was an issue earlier with some files being ignored. Can you retry with `v2.1.1`?

**Comment by cexbrayat** [comment]
Thanks @admah and @lmiller1990 

The file is back with v2.1.1.

Two strange things though:

- `ng add @cypress/schematics --e2e` still asks about component support. You have to specify `--no-component` if you don't want it. I think it should not ask about the other type of support when one is specified?

- `ng add @cypress/schematics --e2e --no-component` now generates a config with `supportFile: false` but the support files are generated anyway which feels weird. I would either have the same config as before, or not have the unused support files generated.

**Comment by admah** [comment]
@cexbrayat thanks for reporting those issues. I'll take a look.

**Comment by admah** [comment]
@cexbrayat I'm going to close this issue and investigate the other things that you brought up separately.
