### ISSUE TITLE
login with cypress to salesforce- left pane is disappear

### ISSUE THREAD

**Issue by Zehava123** [cypress-io/cypress#23640]
### Current behavior

hi,
 am able to open the application but the test runner left pane closes after the salesforce application is open and execution stops without any error report.
before the left panel disappear, cypress write: (page load)--waiting for new page to load--

The desired application remains open with no execution.
We can see in RED that the browser is handled by automation(Cypress) but there is no Test Runner left pane.

I see there is exist conversation about this issue-
https://github.com/cypress-io/cypress/issues/14274
with no solution

do you have any solution for this issue?

### Test code to reproduce
```js
describe('Login', () => {
  it('Login to SalesForce', () => {
    cy.visit('salesforce link')
   cy.get('#username').type('user name')
   cy.get('#password').type('password')
   cy.get('#Login').click()
```
### Cypress Version

10.3.0

### Node version

v16.13.2

### Operating System

macOS 12.1

**Comment by giovanna-code** [comment]
I'm having the same problem and noticed it started happening since the latest Salesforce release (Winter 23), but still not sure that it could be related.

**Comment by emilyrohrbough** [comment]
@Zehava123 / @giovanna-code I do not have access to a salesforce account to try & repo this issue to determine why this is happening. Could you dig in a big to answer these questions?

- Does the login have a redirect/update which is setting itself to `top`?
- Is Cypress still available after login?
- Is the Cypress reporter UI in the dom at all or is the login completely busting out of the Cypress AUT (application under test) Iframe and replacing the entire dom with the salesforce application?

**Comment by giovanna-code** [comment]
@emilyrohrbough 
Does the login have a redirect/update which is setting itself to top? **No, it doesn't.**
Is Cypress still available after login? **Yes, after the succesful login it follows to the next step that is to visit the Salesforce home page, and right after finishing the home page render, the command log disappears and the execution stops.**
Is the Cypress reporter UI in the dom at all or is the login completely busting out of the Cypress AUT (application under test) Iframe and replacing the entire dom with the salesforce application? **It's in the dom and continues until completing the home page visit, and that's when the entire dom seems to be replaced with the Salesforce application.**

Also, we tried the following that didn't work out:
- tests changing the viewport (cypress version)
- tests after installing WSL certificates (in case it was a security problem)
- tests running in all browsers available (same results in all of them)

Cypress Version
9.5.4

Node version
v14.18.0

Operating System
Windows 10 Enterprise 20H2 v

**Comment by emilyrohrbough** [comment]
@rodriguesgio Thank you for getting back to me. It sounds like SalesForce is busting out of the frame we render your site in when testing. I spoke with a few individuals on my team and we are aware that Cypress & SalesForce do not play nicely together. We have been spiking into various auth/third-party sites to determine gaps we have and have been slowly making process on various aspects like tough cooking handling and the new `experimentalModifyObstructiveThirdPartyCode`. This. new flag, when enabled, will turn on additional `modifyObstructiveCode` options to prevent frame busting, as well as striping integrity tags out of <link> and <script> elements and remove the electron user agent. In the current state of this experimental flag.

You might give that a try and see if that option fixes this issue. If not, I'm not sure I have any other suggestions for you, though others might have some insights if you reach out to the community on discord (https://on.cypress.io/chat).

**Comment by rodriguesgio** [comment]
@emilyrohrbough thank you! Unfortunately the proposed flags were no success for me and my colleagues. We reached out the community on discord and will also keep trying to find some work around. If we get one, I'll come back here to share.

**Comment by Zehava123** [comment]
@rodriguesgio  
hi,
I found a work around :)
hope it will help you as well
first- login with POST request to login page, and then , visit specific salesforce page (for example- home page):
```js
cy.request({
        body: {
            display: 'page',
            hasRememberUn: 'true',
            height: '1080',
            local: '',
            locale: '',
            login: '',
            loginType: '',
            loginURL: '',
            lt: 'standard',
            oauth_callback: '',
            oauth_token: '',
            pw: password,
            qs: '',
            serverid: '',
            startURL: '',
            un: user email,
            useSecure: 'true',
            username: user email,
            width: '2560',
        },
        form: true,
        method: 'POST',
        url: 'insert the login URL'
    })
    })
```
now, after  login via POST request, we should visit home page/ account page or another specific page (not the login page)
for example:
```js
cy.visit(`sandbox.lightning.force.com/lightning/o/Home)`)
```
and SFDC open correct , left panel is exist and I can continue run with cypress

hope it will be helpfull for all  :)

**Comment by rodriguesgio** [comment]
@Zehava123 thank you so much, but unfortunately it didn't work out for us. Still on hold to find a work around.

**Comment by Brayxeh** [comment]
@rodriguesgio did you find a workaround?

**Comment by rodriguesgio** [comment]
@Brayxeh no. We've been running in Firefox, the only browser that we don't face this issue.

**Comment by Brayxeh** [comment]
> @Brayxeh no. We've been running in Firefox, the only browser that we don't face this issue.

The left panel also closes running on firefox. Do you use a request method and then goto any salesforce page?

**Comment by rodriguesgio** [comment]
@Brayxeh we login using the Salesforce Connected Apps configuration (https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_oauth_and_connected_apps.htm) and then we visit any page just to access the global search field and go from there.

**Comment by Zehava123** [comment]
@rodriguesgio ,
can you add more details what exactly you did?
which application did you add to Connected App configuration- Cypress application?
thanks,
Zehava

**Comment by AtofStryker** [comment]
Hey all. We are adding a new experimental flag in Cypress `12.4.0` called `experimentalSkipDomainInjection` that might fix this issue as mentioned in https://github.com/cypress-io/cypress/issues/24290#issuecomment-1376214221. Would anyone be willing to try on release a week from Tuesday and verify if it solves this issue?

**Comment by AtofStryker** [comment]
Going to close this due to inactivity / being solved with `experimentalSkipDomainInjection` and `experimentalModifyObstructiveThirdPartyCode`. If this continues to be an issue, please open another issue!

**Comment by sebaahumada1** [comment]
Buenas tardes, estoy padeciendo 

> @Brayxeh we login using the Salesforce Connected Apps configuration (https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_oauth_and_connected_apps.htm) and then we visit any page just to access the global search field and go from there.

Buenas estoy padeciendo el mismo problema, probe mil maneras desactive el cache , la seguridad del navedador etc, y nada.  Ustedes udieron solucionarlo?

**Comment by AtofStryker** [comment]
Buenas @sebaahumada1 . Sí, yo creo que tenemos una solución. Para el "framebusting", la opción de `experimentalModifyObstructiveThirdPartyCode` necesita estar activada. Para "Salesforce Winter '23", la opción de `experimentalSkipDomainInjection` necesita estar configurado. Lo explicamos en esta documentación [aquí](https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection). ¿Esta solución trabajando para usted?

Hi @sebaahumada1. Yes, I believe we have a solution. For "framebusting", the `experimentalModifyObstructiveThirdPartyCode` option needs to be enabled. For "Salesforce Winter '23", the `experimentalSkipDomainInjection` option needs to be configured. We explain it in this documentation [here](https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection). Is this solution working for you?

**Comment by jennifer-shehane** [comment]
This experimental flag will be made default behavior in Cypress 14 with `injectDocumentDomain` being `false`. https://github.com/cypress-io/cypress/pull/30770
