### ISSUE TITLE
testIsolation Config Throws on 2nd Test

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#23644]
### Current behavior

<img width="547" alt="Screen Shot 2022-08-31 at 9 18 31 AM" src="https://user-images.githubusercontent.com/14099737/187701242-0e8e0910-d7ca-4336-bf80-3f224c6bd003.png">

- quick debugging shows override level is "undefined" when it should be "suite"

### Desired behavior

Config validation correctly ensures which level the configuration is being applied from.

### Test code to reproduce

```js
describe('page', {testIsolation: 'legacy' }, () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
  })

  it('works', () => {
    cy.url().should('eq', 'https://example.cypress.io')
  })
})
````

### Cypress Version

10.5.0+

### Node version

n/a

### Operating System

n/a

### Debug Logs

```shell
n/a
```

**Comment by lewnelson** [comment]
We've also ran into this issue on `10.7.0` following the same setup, overwriting at the test suite level.
