### ISSUE TITLE
alias returns undefined when there is a customized get command for the alias and I visit the page again

### ISSUE THREAD

**Issue by haipinggong** [cypress-io/cypress#23652]
### Current behavior

1. Get an element by using a customized command called cy.get2 chained by a children command, then save it as an alias: 'container'.
2. Visit the page again.
3. Call cy.get('@container').

Cypress throws an error saying the cy.get2 returns undefined.

![image](https://user-images.githubusercontent.com/20938090/187851325-d28c95e6-6fb7-4bcf-87be-9d59a8c1a0c7.png)

### Desired behavior

In this situation, cy.get should still get the same element as I get in step 1.
The script worked on 10.4.0.

### Test code to reproduce

https://github.com/haipinggong/cypress-test-tiny/tree/alias-bug

```
describe("page", () => {
  it("works", () => {
    cy.visit("https://example.cypress.io");
    cy.get("body").children(".container").as("container");
    cy.visit("https://example.cypress.io");

    cy.get("@container");
  });

  it("does not work", () => {
    // The test case works in Cypress 10.4.0
    // The test case does not work in Cypress 10.5.0+

    cy.visit("https://example.cypress.io");
    cy.get2("body").children(".container").as("container");
    cy.visit("https://example.cypress.io");

    cy.get("@container");
  });
});
```

support/command.js file:

```
Cypress.Commands.add("get2", (selector, ...options) => {
  return cy.get(selector, ...options);
});
```

### Cypress Version

10.5.0+

### Node version

16.15.0

### Operating System

Windows 11

**Comment by emilyrohrbough** [comment]
@haipinggong Thank you for the reproducible example! I tried it out and it does appear that this is a regression in 10.5.0.

**Comment by BlueWinds** [comment]
That is a lovely short little test demonstrating the issue, was able to figure it out almost immediately. Opened a PR to fix it.

Was a regression introduced during some of my work related to https://github.com/cypress-io/cypress/issues/7306, that went out in 10.5.0.
