### ISSUE TITLE
enabling the experimentalSessionAndOrigin

### ISSUE THREAD

**Issue by PelinET** [cypress-io/cypress#23655]
### Current behavior

I added below option of the config.js:
_experimentalSessionAndOrigin: true,_

but I still get the same error below:

_CypressError
cy.session() requires enabling the experimentalSessionAndOrigin flag._

### Desired behavior

I expect the test to continue once I add below option to config.js
experimentalSessionAndOrigin: true 

### Test code to reproduce

```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    baseUrl: 'http://localhost:3000',
    experimentalSessionAndOrigin: true,
  setupNodeEvents(on, config) {
      
    },
  },
});
```

### Cypress Version

10.5.0

### Node version

not using it

### Operating System

macOS Monterey 12.5.1

### Debug Logs

```bash
CypressError
cy.session() requires enabling the experimentalSessionAndOrigin flag.Learn more
cypress/e2e/login.cy.js:10:10
   8 |   describe('login test', () => {
   9 |     it('should login', () =>{
> 10 |       cy.session(name, () => { 
     |          ^
  11 |         cy.visit('/login')
  12 |       cy.get('[data-test=name]').type(name)
  13 |       cy.get('[data-test=password]').type('acm.admin') 
View stack trace
 Print to console
    at throwIfNoSessionSupport (https://acm.adssets.com/__cypress/runner/cypress_runner.js:154861:77)
    at Context.session (https://acm.adssets.com/__cypress/runner/cypress_runner.js:154886:8)
    at wrapped (https://acm.adssets.com/__cypress/runner/cypress_runner.js:167331:44)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/login.cy.js:10:10)
```

**Comment by emilyrohrbough** [comment]
@PelinET I was unable to reproduce this issue with the configuration you have provided. This option requires the Cypress server to restart to work correctly. Please restart Cypress and verify this being set: by checking your Settings in open mode. 
<img width="1188" alt="Screen Shot 2022-09-01 at 3 35 06 PM" src="https://user-images.githubusercontent.com/14099737/188007557-61b59545-3a37-4800-9e16-8fb62d2a7ab7.png">

**Comment by PelinET** [comment]
How can I do that -> "by checking your Settings in open mode"

**Comment by emilyrohrbough** [comment]
@PelinET Please check out our documentation at https://docs.cypress.io/ for details. If you cannot find the information you are looking for, I suggest reaching out in our communicate discord chat room: https://on.cypress.io/chat.
