### ISSUE TITLE
Aliases from cy.intercept() are being ignored

### ISSUE THREAD

**Issue by zack-pronto** [cypress-io/cypress#23664]
### Current behavior

# Versioning Details
![CleanShot 2022-09-01 at 16 01 28](https://user-images.githubusercontent.com/63250712/188020649-439de5db-b631-4faa-b19f-d52b799461c0.png)
![CleanShot 2022-09-01 at 16 01 51](https://user-images.githubusercontent.com/63250712/188020656-c687df31-5c1c-4d44-9f96-5e081924466c.png)
![CleanShot 2022-09-01 at 16 02 13](https://user-images.githubusercontent.com/63250712/188020698-aa829fd2-15ff-4cf9-995d-38dad2aa2cca.png)
![CleanShot 2022-09-01 at 16 07 25](https://user-images.githubusercontent.com/63250712/188021357-2b88b47c-4507-42ac-8483-7ac117266cc3.png)

# Bug Explanation

For some reason, after upgrading to `10.7.0`, I am now getting failures where my registered aliases aren't getting registered properly so future calls to `cy.wait(...)` are failing with a cypress exception that the alias doesn't match a route. Here are two examples of this below:

### Setup
![CleanShot 2022-09-01 at 15 47 36](https://user-images.githubusercontent.com/63250712/188018816-e06342c8-aaba-46c7-aab4-1514872a8479.png)

### Test Code
![CleanShot 2022-09-01 at 15 40 52](https://user-images.githubusercontent.com/63250712/188018261-a551e731-bfed-4908-99a2-782f367b29c9.png)

### Test Failure
![CleanShot 2022-09-01 at 15 45 59](https://user-images.githubusercontent.com/63250712/188018747-e17e99ba-e76b-44a1-b5a3-b19e77bf8e47.png)

### Hacky Workaround

After some debugging, I realized that if I just threw in a dummy intercept call and gave it a dummy alias, then the tests just started passing again:

![CleanShot 2022-09-01 at 15 51 38](https://user-images.githubusercontent.com/63250712/188019293-5e8a8c63-870a-402b-8d35-0c54f25a01ba.png)
![CleanShot 2022-09-01 at 15 49 58](https://user-images.githubusercontent.com/63250712/188019208-b231d8df-e0c8-45e7-b7a7-b329afa07f99.png)

### Test Code
![CleanShot 2022-09-01 at 15 56 53](https://user-images.githubusercontent.com/63250712/188020265-9130178f-f1af-49f9-91f6-2111c2598d06.png)

### Test Failure
![CleanShot 2022-09-01 at 15 56 34](https://user-images.githubusercontent.com/63250712/188020328-58c1f324-d684-4e60-bce9-9e6dfcf7e0d7.png)

### Hacky Workaround
![CleanShot 2022-09-01 at 15 58 37](https://user-images.githubusercontent.com/63250712/188020900-0addcb23-ebc5-4ed4-9421-d317aa985e86.png)
![CleanShot 2022-09-01 at 16 05 47](https://user-images.githubusercontent.com/63250712/188021170-fe8435ae-a1c0-45b1-a0d6-f2fbcfe87dcd.png)

### Desired behavior

I have multiple examples of failures in my tests after upgrading to `10.7.0` where aliases aren't being registered properly. I would expect that if I set up an intercept and call `.as('verify')`, that the alias would get registered so that when I call `cy.wait('@verify')` later, the test passes successfully. 

### Test code to reproduce

I don't have time to come up with an example repo, but if you really hassle me on this, I will try to find the time. This should be fairly easy to reproduce on your end. 

### Cypress Version

10.7.0

### Node version

14.7.1

### Operating System

macOS 12.5

**Comment by emilyrohrbough** [comment]
@zack-pronto oh no! This is not a good issue. Could you share a few more details on your component testing setup? I wasn't able to repo on our example repo using vue2, nuxt2 and webpack. But it seems you've hit this issue a few times so I believe something weird is happening.

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please post a comment with a reproducible example and we will re-open this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
