### ISSUE TITLE
Network service crashed, restarting service.

### ISSUE THREAD

**Issue by meidinawh** [cypress-io/cypress#23666]
### Current behavior

When i try to open Cypress using NPM :

npx cypress open

My Cypress app is open but empty like this :
<img width="889" alt="cypress error" src="https://user-images.githubusercontent.com/55943139/188034228-3b0ba1f2-8399-45d0-a5b2-3824693b80ef.PNG">

and in NPM a mesage appears saying :
[5024:0902/072642.456:ERROR:network_service_instance_impl.cc(470)] Network service crashed, restarting service.
<img width="499" alt="network" src="https://user-images.githubusercontent.com/55943139/188034406-c101b387-6e34-4bc7-9dbf-d4f4bce799e0.PNG">

Please help me! Thank You

### Cypress Version

10.7.0

### Node version

16.17.0

### Package Manager

npm

### Package Manager Version

8.18.0

### Operating system

Windows

### Operating System Version

104.0

**Comment by nagash77** [comment]
@meidinawh what steps have you taken to narrow down the issue?  Was this previously working on an older version of Cypress?  Have you tried reaching out in the [Cypress Discord](https://on.cypress.io/chat) channel?  Unfortunately without more information we will not be able to help you.
