### ISSUE TITLE
TSConfig seemingly not used when passed in via angular's build options (see #23161)

### ISSUE THREAD

**Issue by yusijs** [cypress-io/cypress#23673]
### Current behavior

In https://github.com/cypress-io/cypress/issues/23161 we were allowed to pass in an Angular config object, which also includes a tsconfig-path. However, that tsconfig path seems to be fully ignored; if I pass in a random string, everything builds/tests as it should. I dug a bit through the code and looking at e.g https://github.com/cypress-io/cypress/blob/a9d97114073f0ddc2983d775bfef60145df99902/npm/webpack-dev-server/src/helpers/angularHandler.ts#L135, it always uses <projectroot>/tsconfig.json. 

### Desired behavior

In my Angular / NX apps I have:
- tsconfig.json (baseline)
- tsconfig.app.json
- tsconfig.jest.json
- tsconfig.editor.json

I would also like to have a tsconfig.cypress.json to ensure the correct paths etc are used without having to interfere with the rest of my tsconfig-setup.

### Test code to reproduce

```typescript
// cypress.config.ts
export default defineConfig({
  component: {
    video: true,
    videosFolder: root + 'dist/cypress/components/videos',
    screenshotsFolder: root + 'dist/cypress/components/screenshots',
    devServer: {
      framework: 'angular',
      bundler: 'webpack',
      options: { // temporary, this will be done automatically when we get it directly from nx
        projectConfig: {
          root: projectRoot,
          sourceRoot: projectRoot + 'src',
          buildOptions: {
            tsConfig: _projectRoot + 'tsconfig.app.json',
            ... more config (that works yay)
          },
        }
      }
    },
    specPattern: 'cypress/specs/**/*.cy.ts',
  },
});
```

### Cypress Version

10.7.0

### Node version

v18.4.0 (also tried with 16.2.0)

### Operating System

macOS 12.5

**Comment by lmiller1990** [comment]
Uh oh, regression - thanks for the reproduction. Knowing where it was introduced is really useful.

Are you interested in making a PR? If not I'll look for someone to pick it up internally.

**Comment by yusijs** [comment]
Will make a pr for it - I wasn't 100% certain if I misunderstood and it was working as intended ™️.
