### ISSUE TITLE
Formatted errors does not show as formatted in cypress test runner

### ISSUE THREAD

**Issue by Amitkahlon** [cypress-io/cypress#23679]
### Current behavior

Cypress 10 new test runner omits formatting on errors such as new lines, tabs, etc. 

![Capture](https://user-images.githubusercontent.com/50583120/188315282-29992ce6-ca56-44f0-9f96-59f4a3e40259.PNG)

### Desired behavior

To be able to throw an error with formattings such as new lines, and tabs.
*For example see how cypress dashboard prints the error below*

### Test code to reproduce

```
it.only('fail to format in test runner', { retries: 0 }, () => {
    Cypress.on('fail', (error, runnable) => {
      throw {
        ...error,
        message: `Failed to assert  event.\n\nExpectedValue:**${JSON.stringify(
          error.expected,
          null,
          4
        )}** \nActual args: **${JSON.stringify(error.actual, null, 4)}** \n
      `,
      };
    });

    cy.wrap({
      category: 'resources',
      name: 'action',
      label: 'copy_clipboard',
      target: 'keyboard',
      location: {
        title: 'favorites',
      },
      search: {
        clientSearchId: 'favorites',
        sessionId: 'favorites',
      },
      resources: {
        message: 'match(undefined)',
      },
      jsonData: {
        'action.trigger': 'command_bar',
      },
    }).should('deep.equal', {
      category: 'resources',
      name: 'action',
      target: 'keyboard',
      label: 'copy_clipboard',
      location: {
        title: 'favorites',
      },
      resources: [
        {
          id: 'UgfdGiIVw7NklNbHWSO-fw',
          list: 'favorites',
          appId: 'mockapp',
          type: 'mockapp:item',
          position: 0,
          linkId: '631483cead6377c7a8ef5c2e',
        },
      ],
      jsonData: {
        'action.trigger': 'command_bar',
      },
    });
  });
```

### Cypress Version

10.7.0

### Node version

16.14.2

### Operating System

windows 10

### Other

- It worked well with cypress 9 and was broken with Cypress 10.
- it actually works well in Cypress dashboard.
### Cypress Dashboard showing formatted error

![Capture](https://user-images.githubusercontent.com/50583120/188315236-86ae8c72-1561-475e-935f-693a3d9534de.PNG)

**Comment by emilyrohrbough** [comment]
@Amitkahlon It does appear this used to work in 9.6.0 and no longer works in Cypress 10.7.0. Thank you for providing a reproducible example! I will make as a regression. That being said, I don't anticipate this issue will be picked up anytime soon. Would you be interested in contributing a fix to restore this behavior?

**Comment by Amitkahlon** [comment]
> @Amitkahlon It does appear this used to work in 9.6.0 and no longer works in Cypress 10.7.0. Thank you for providing a reproducible example! I will make as a regression. That being said, I don't anticipate this issue will be picked up anytime soon. Would you be interested in contributing a fix to restore this behavior?

Yeah, that sounds interesting, can you point me in the right direction I will make my best attempt to fix it.

**Comment by emilyrohrbough** [comment]
@Amitkahlon Great!! I did a little digging and I suspect it could be tied to this change: https://github.com/cypress-io/cypress/pull/22537 which was made to enhance the markdown formatting.

If it were me, I'd start with verifying the message is in the format you expected before we attempt to format it for the UI.

**Comment by Amitkahlon** [comment]
> @Amitkahlon Great!! I did a little digging and I suspect it could be tied to this change: #22537 which was made to enhance the markdown formatting.
> 
> If it were me, I'd start with verifying the message is in the format you expected before we attempt to format it for the UI.

Thank you, I will give it a try this weekend

**Comment by perlo27** [comment]
Hi there,
i see this one being inactive for a while, i can fix it if no one mind

**Comment by Amitkahlon** [comment]
> Hi there, i see this one being inactive for a while, i can fix it if no one mind

Hi, yeah.. 
you can take it if you want

**Comment by perlo27** [comment]
i have a fix ready, just can't push the branch - have 403 when pushing. @emilyrohrbough could you please help me with it?
