### ISSUE TITLE
CYPRESS_DOWNLOAD_PATH_TEMPLATE only replace placeholder once

### ISSUE THREAD

**Issue by ChrisKuBa** [cypress-io/cypress#23670]
### Current behavior
```
CYPRESS_DOWNLOAD_PATH_TEMPLATE=http://tkeasydev.dst.tk-inline.net/nodejs/cypress/v${version}/cypress-${version}-${platform}-${arch}.zip

npm ERR! [FAILED] URL: http://tkeasydev.dst.tk-inline.net/nodejs/cypress/v10.7.0/cypress-${version}-win32-x64.zip
```

### Desired behavior
```
should replace all occurences of a value

CYPRESS_DOWNLOAD_PATH_TEMPLATE=http://tkeasydev.dst.tk-inline.net/nodejs/cypress/v${version}/cypress-${version}-${platform}-${arch}.zip

http://tkeasydev.dst.tk-inline.net/nodejs/cypress/v10.7.0/cypress-10.7.0-win32-x64.zip
```
### Test code to reproduce

no test available
failed on npm i

### Cypress Version

10.7.0

### Node version

18.8.0

### Operating System

Win 10

**Comment by lmiller1990** [comment]
Docs for this feature (didn't know this was a thing): https://docs.cypress.io/guides/references/advanced-installation

**Comment by lmiller1990** [comment]
I think this works just fine, though. I installed the latest version (v10.7.0). Then I did

```
$ CYPRESS_DOWNLOAD_PATH_TEMPLATE="https://cdn.cypress.io/desktop/10.5.0/darwin-x64/cypress.zip" yarn cypress install --force
yarn run v1.22.19
$ /Users/lachlan/code/dump/foo/node_modules/.bin/cypress install --force

Cypress 10.6.0 is installed in /Users/lachlan/Library/Caches/Cypress/10.7.0

Installing Cypress (version: 10.7.0)

✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation /Users/lachlan/Library/Caches/Cypress/10.7.0

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

✨  Done in 39.26s.
$ vi /Users/lachlan/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/package.json
$ cat /Users/lachlan/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/package.json
{
  "name": "cypress",
  "productName": "Cypress",
  "description": "Cypress.io end to end testing tool",
  "version": "10.5.0",
  "electronVersion": "19.0.8",
  "electronNodeVersion": "16.14.2",
  "main": "index.js",
  "env": "production"
}%
```

It's weird since you are installing a specific binary - so you've got a different cli version (the thing in `node_modules/cypress` to the actual binary, but it does what it's supposed to do (installs a specific version of the binary).

Let me know if I'm missing something, but it looks like this works as expected.

**Comment by ChrisKuBa** [comment]
Hi,

Problem: I'm behind a firewall at our company. Automatic downloading of many binaries is prohibited.
So the only option is to manually request a special download, verify the binary and store it internally. This is the only way to have all additional binaries used by nodejs dependencies available at install time.

Also, we use an internal path/filename format used by other companies, e.g
https://github.com/electron/electron/releases/
to store these binaries internally on a separate host/domain.

So I can't use your mirror https://cdn.cypress.io inside the CYPRESS_DOWNLOAD_PATH_TEMPLATE.

http://tkeasydev.dst.tk-inline.net is an internal domain. You cannot access it from the outside.

Before CYPRESS_DOWNLOAD_PATH_TEMPLATE, we use CYPRESS_INSTALL_BINARY with a hard-coded URI and version, and we often forgot to update this path as well when newer versions of Cypess were installed. So I'm grateful to have an option with dynamic/viriable parameters.

If replacing using the same variable multiple times is not an option for you, the only workaround I see is to change our internal storage format.

Thx

**Comment by lmiller1990** [comment]
Right, I understand the problem now.

I think we just need to use a regex [here](https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/download.js#L68-L76) instead of `replace`, and that should fix the problem.

If you'd like to make a PR, that'd be great! I'm going to mark this as an good first issue, so either someone can pick it up now, or it can go into our backlog for internal prioritization.

**Comment by ChrisKuBa** [comment]
Hi,

forking and running the repo on my windows machine fails completely. And yes I'm looking at CONTRIBUTING.md.
It fails on yarn start, because many commands start with "./" and Windows quit this with an error
**The command "." is either misspelled or could not be found.**
Even when dependency checks were ignored, many tests initially failed.

The fix is very simple:
extending all regular expressions by a ***g*** (global modifier)
https://github.com/cypress-io/cypress/blob/9cdb33b4c6415cf5ea3f95fce5b62339de3a51a0/cli/lib/tasks/download.js#L71-L74
to this
```javascript
        .replace(/\\?\$\{endpoint\}/g, endpoint)
        .replace(/\\?\$\{platform\}/g, platform)
        .replace(/\\?\$\{arch\}/g, arch)
        .replace(/\\?\$\{version\}/g, version)
```
Also a test should be add after this
https://github.com/cypress-io/cypress/blob/9cdb33b4c6415cf5ea3f95fce5b62339de3a51a0/cli/test/lib/tasks/download_spec.js#L77-L83

```javascript
    it('returns custom url from template with multiple replacements', () => {
      process.env.CYPRESS_DOWNLOAD_PATH_TEMPLATE = '${endpoint}/v${version}/${platform}/${arch}/cypress-${version}-${platform}-${arch}.zip'
      const url = download.getUrl('ARCH', '0.20.2')

      snapshot('desktop url from template with multiple variables', normalize(url))
    })
```
Hope it helps.

**Comment by lmiller1990** [comment]
I've done development on Windows (CI also running on windows).

If you'd like to become a contributor, happy to work through getting your environment setup - if you just want this fixed asap, I can grab your above fix and integrate it, if you like. Let me know what works for you!

**Comment by mohi-k** [comment]
Hey @nagash77, could you please assign this issue to me?

**Comment by mahdikhashan** [comment]
Hey @nagash77 , could you please assign it to me?

**Comment by lmiller1990** [comment]
@mahdikhashan done, I also set the status to "Contributor PR in Progress" so someone should be able to review it for you.
