### ISSUE TITLE
":has" selector changed its behaviour in Chrome 105

### ISSUE THREAD

**Issue by yuriiknowsjava** [cypress-io/cypress#23671]
### Current behavior

The following selector does not work when tests are run in Chrome of version 105
```js
cy.get('[data-test="bankaccount-bankName-input"]:has(:contains(Enter a bank name))')
```
At the same time, it works in Electron 102 and Firefox 104.

I suspect this issue might relate to [:has() the family selector in Chrome](https://developer.chrome.com/blog/has-m105/).

Will this selector work in the future? Is there a possible replacement?

### Test code to reproduce

HTML snippet:
```html
<div data-test="bankaccount-bankName-input">
    <div>
        <input aria-invalid="true" id="bankaccount-bankName-input" name="bankName" placeholder="Bank Name" required=""
               type="text" value="" aria-describedby="bankaccount-bankName-input-helper-text">
        <fieldset aria-hidden="true" style="padding-left: 8px;">
            <legend style="width: 0.01px;"><span>ssss</span></legend>
        </fieldset>
    </div>
    <p id="bankaccount-bankName-input-helper-text">Enter a bank name</p>
</div>
```

Test snippet:
```js
cy.get('[data-test="bankaccount-bankName-input"]:has(p)')
cy.get('[data-test="bankaccount-bankName-input"]:has(:contains(Enter a bank name))')
```

### Cypress Version

10.7.0, 9.7.0

### Node version

v16.14.0

### Operating System

Ubuntu 18.04

**Comment by emilyrohrbough** [comment]
@yuriiknowsjava I can confirm this behavior does appear to have changed in Chrome 105. Under the hood, `cy.get()` uses JQuery to query the element(s) on the page and this issue has been reported here: https://github.com/jquery/jquery/issues/5098.

In the mean time, I suggest updating your assert to use leverage Cypress's `.contains()` command:
```
  cy.get('[data-test="bankaccount-bankName-input"]')
    .contains('Enter a bank name')
```
