### ISSUE TITLE
Cannot load one page using cy.visit

### ISSUE THREAD

**Issue by MikeZ2022** [cypress-io/cypress#23678]
### Current behavior

Try to use cy,visit load  https://www.demo.bnz.co.nz/client/
but always failed to load this page.

### Desired behavior

Cypress should load the page

### Test code to reproduce

describe('Test',()=>{
    beforeEach(() => {
        cy.viewport('macbook-13')    
        cy.visit('https://www.demo.bnz.co.nz/demo')
})

### Cypress Version

10.7.0

### Node version

v16.16.0

### Operating System

Windows 11

**Comment by lmiller1990** [comment]
I tried it out and confirmed this is the case - it fails to load with socket hangup.

The problem is not entirely clear - will need to debug more. Do you control this website? If so, do you have the same issue when visiting the site running locally (as opposed to the live version)?

**Comment by MikeZ2022** [comment]
No, I don't own this website. I am applying for a tester role, and they give me this website to create some e2e automation test scripts as a skill assessment.

**Comment by lmiller1990** [comment]
Sure thing. I'm looking into what might prevent Cypress from loading this now. The site works fine in a regular iframe, so that's not the issue - I'll update when I've got more information for you. This is quite unusual - I'm surprised it isn't loading.

**Comment by lmiller1990** [comment]
I'm thinking the client has something in front of their website preventing automation tools like Cypress from visiting it... I also cannot curl the url:

```sh
$ curl https://www.demo.bnz.co.nz/client/

<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;www&#46;demo&#46;bnz&#46;co&#46;nz&#47;client&#47;" on this server.<P>
Reference&#32;&#35;18&#46;368cc817&#46;1662493391&#46;e30276e
</BODY>
</HTML>
```

I'll look into this more, but in the meantime, you may want to follow up with the owner of the website to see if they've got something in place to prevent bots/automation tools from visiting the site.

**Comment by lmiller1990** [comment]
I cannot visit this page in regular Node.js either:

```js
import { http, https } from 'follow-redirects'

const req = https.request(
  {
    hostname: "demo.bnz.co.nz",
    path: "/demo",
    method: "GET",
    port: 443,
  },
  (res) => {
    res.on("data", (d) => {
      process.stdout.write(d);
    });
  }
);

req.on("error", (error) => {
  console.error(error);
});

req.end();
```

Output:

```sh
$ DEBUG=* yarn ts-node req.ts
yarn run v1.22.19
$ /Users/lachlan/code/dump/foo/node_modules/.bin/ts-node req.ts
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'https:',
  hostname: 'demo.bnz.co.nz',
  path: '/demo',
  method: 'GET',
  port: 443,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function: __node_internal_],
      validateHeaderValue: [Function: __node_internal_],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms
  follow-redirects redirecting to https://www.demo.bnz.co.nz:443/demo +129ms
```

Hangs forever - I think the web server is preventing us from following the redirect. Can you follow up with the owner of the website?

**Comment by MikeZ2022** [comment]
Sorry, I can't reach out to the owner. I receive it from a job skill assessment, and as I know they are an outsourcing company, I suppose this website comes from their client.

**Comment by lmiller1990** [comment]
I don't know what else we can do without more information - it's not clear what's happening on the server but we request the URL but never get anything back.

Without more insight into how this site is hosted and served, I can't make any additional recommendations at this point in time. I'd recommend describing what you've tried and following up with the client, I suppose - generally we don't recommend running Cypress against websites you don't control. Some websites block tools like Cypress to prevent scraping and bots - if I had to guess, I'd say that could be what's occurring here.

**Comment by lmiller1990** [comment]
At this point, I don't think there's enough info to continue debugging - if you do get more info from the owner of the site, happy to reopen and investigate.
