### ISSUE TITLE
Cypress creates an incorrectly named screenshot for skipped tests

### ISSUE THREAD

**Issue by irfancharania** [cypress-io/cypress#2368]
I'd like to skip certain tests based on environment (e.g. not run a given test in Production environment). 

### Current behavior:

When I programmatically skip, Cypress creates a screenshot and names it failed.

<img width="704" alt="2018-08-17 21_11_59-c__windows_system32_cmd exe" src="https://user-images.githubusercontent.com/3255038/44295726-ec9d6480-a263-11e8-911a-12333db65a68.png">

### Desired behavior:

I don't mind the screenshot getting created, but it should be named "pending".

### Steps to reproduce:
Example repo: https://github.com/irfancharania/cypress-example/
Specifically: [test.spec.ts](https://github.com/irfancharania/cypress-example/blob/master/cypress/integration/test.spec.ts#L5-L9)

### Versions

Cypress: 3.1.0
Windows 10
Node v8.11.3

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by irfancharania** [comment]
Thanks! 😆
