### ISSUE TITLE
Faulty "uncaught expection" trigger in failing expect() in on('window:alert) 

### ISSUE THREAD

**Issue by actuallymentor** [cypress-io/cypress#23683]
### Current behavior

This assertion fails:

```
cy.on( 'window:alert', response => {
    expect( response ).to.contain( 'Invalid secret code' )
} )
```

Results in:

```
The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
```

This is not correct. It is not an application error, it is a cypress assertion.

![image](https://user-images.githubusercontent.com/9071382/188423704-a13ae9ce-0bc1-4a31-99d1-cd648b433db2.png)

### Desired behavior

Test should fail gracefully.

### Test code to reproduce

Clone and install dependencies:

```
https://github.com/actuallymentor/cypress-test-tiny-uncaught-bug.git
npm i
cd bug
npm i
cd ..
```

Inside `./bug/` run `npm start`
Then inside `.` run `npm run cypress:open`

Your result:

![image](https://user-images.githubusercontent.com/9071382/188425708-b53edc1b-d9a3-4b76-a3f6-981f16fb72c1.png)

### Cypress Version

10.7.0

### Node version

16

### Operating System

macOS 12

**Comment by emilyrohrbough** [comment]
@actuallymentor Thank you for opening an issue with a code snippet and clear error of the issue you are experiencing! It is super helpful with identifying what the root issue is.

Unfortunately I have not been able to reproduce the issue. Using Cypress 10.7.0, I verified the following example works as expected in Chrome 104, Chrome Beta 106, Edge 105, Electron 102 and Firefox 101.
```js
it('can assert on window.alert', (done) => {
  cy.on( 'window:alert', response => {
    expect( response ).to.contain( 'Invalid secret code' )
    done()
  })
  cy.window().then((win) => {
    win.alert('derp')
  })
})
```

![Image](https://user-images.githubusercontent.com/14099737/188731071-be441841-9b8c-465b-99a2-8ec311bbb66c.png)

Is there any other information I need to repo this?

**Comment by actuallymentor** [comment]
Are you using an M1 mac? The repo should show the issue verbatim (it does for me).

**Comment by emilyrohrbough** [comment]
@actuallymentor I am on a Mac (macOS Monterey 12.5.1) but its not an M1.

**Comment by chrisbreiding** [comment]
I was able to reproduce the issue with the given repo. We'll route this to a team to look into.

**Comment by actuallymentor** [comment]
Update: I'm seeing other cases of failed assertions triggering uncaught exceptions. This time in Github Actions:

```
2) Name of my section
       Name of my test
     AssertionError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  > expected 'a string I have' to include 'a substring I asked for'
  ```
