### ISSUE TITLE
I can't log in on an application while in cypress

### ISSUE THREAD

**Issue by Bariscanates404** [cypress-io/cypress#23684]
### Current behavior

Hello, I launch a web page to test some steps then I click a new page link which opens the linked document in the same frame as it was clicked. (_self) 

Then after web page loads 
```
Given('login maximo successfully', () => {
			cy.get('#username').type('username')
			cy.get('#password').type('password')
			cy.get('#loginbutton').click()
})
```
this is the web page that I try to log in with cypress.
![image](https://user-images.githubusercontent.com/103248330/188495949-aaaa7a34-fd48-41c7-8290-4614982d3aaa.png)
You can see there are no error messages or something interesting.
![image](https://user-images.githubusercontent.com/103248330/188495970-0d80cafe-6cb3-42c6-a691-0cc409295a38.png)
![image](https://user-images.githubusercontent.com/103248330/188496063-3c725cd4-c2f4-4d93-9f07-7b983d7eb53b.png)

username and password are correct, when I use my own browser and when I try to join as manually it login without problem.
cypress writes username and password then clicks login but just 

(form sub)--submitting form--
(page load)--page loaded--

wrotes on the cypress log.

### Desired behavior

 i want to cypress login as i do manually. 

### Test code to reproduce

Given('login maximo successfully', () => {
			cy.get('#username').type('username')
			cy.get('#password').type('password')
			cy.get('#loginbutton').click()
})

### Cypress Version

10.4.0

### Node version

 v18.6.0

### Operating System

 windows

**Comment by lmiller1990** [comment]
Do you see some error - or it just hangs?

One thing I've done in the past is wait for the url to change, indicating the form was submitted and the page is redirected. Here's a blog post explaining it: https://www.cypress.io/blog/2020/11/17/when-can-the-test-submit-a-form/

Just to get some more info - are you submitting to the same URL or to another origin? Once you log in, where (what domain - same or another) does it redirect to?

**Comment by Bariscanates404** [comment]
Hello, there is no error. The same URL moreover it's not about waiting because after the test is done I try to log in with my hand on the cypress interface still result is the same. It's not log in when I click the login button suddenly refreshing and doing nothing.

**Comment by lmiller1990** [comment]
In that case, you could try using `cy.origin` - [documentation here](https://docs.cypress.io/api/commands/origin). Although if you are going from HTTP to HTTPS, be aware any cookie set in [HTTPS will not be available in HTTP](https://stackoverflow.com/questions/2163828/reading-cookies-via-https-that-were-set-using-http).

Is this site publicly available by any chance? I could give it a try to debug it. One thing you might try is running the test with `DEBUG=cypress:*` set, that will give you lot of logs in your terminal. You could copy and paste those here - it might give some insight into what's going on under the hood in Cypress.

**Comment by Bariscanates404** [comment]
Hello, I will work on this issue next week's workdays. But I can say that I tried to use cy.origin but `experimentalSessionAndOrigin` makes my tests unworkable.

**Comment by lmiller1990** [comment]
Ok, let me know how you go. What makes `experimentalSessionAndOrigin` unworkable for you?

**Comment by Bariscanates404** [comment]
Hello again, I can give a website of course but I can't give a valid account. If it's okay I can share the webpage. 

Still i didn't find a clear solution  :(

**Comment by ZachJW34** [comment]
@Bariscanates404 please share the webpage, and providing the logs from running Cypress with `Debug=cypress:* npx cypress open` would be helpful. If you can, creating a minimal reproducible example that I can clone would be valuable.

**Comment by ZachJW34** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by Bariscanates404** [comment]
Yes please, I can't share any account and information. But if you need I can just share the URL. We are closing the post but that doesn't change the situation, unfortunately. :(

**Comment by ZachJW34** [comment]
Sharing the url would be helpful and posting the debug logs. You can even email the logs to me if privacy is a concern. The problem does seem to be related to the origin switch which `cy.origin` might help with. You said that `experimentalSessionAndOrigin` did not work for you, please elaborate as to why.

**Comment by Bariscanates404** [comment]
When I activate the experimental session all of my other tests are doesn't
work. in my tests, I needed to use scenarios, so the experimental session
tries to open a blank page after every test. my more than 100 tests doesn't
work. Know I having another problem with the headless test run. This is
lethal for me that's why I just left the origin problem.
https://stackoverflow.com/questions/73858772/cypress-headless-browser-test-run-fails-tests
Do you have any idea or should i open a new ticket on GitHub :(

 [image: image.png]

Thank you for your kind return and for trying to help me, I wish you best :)

**Comment by m-aouainia** [comment]
Hi @Bariscanates404 , have you found a solution for your problem. I have the same issue but with actual version 12.4.1 and also was in previous versions. I can confirm your szenario and the result. for me it did the same . The button is clickable and forward me to another url when I do that outside of cypress but inside cypress nothing will be happend and the test is green. It will be helpfull when you share your state untill now and how you did that. Thanks!

**Comment by Bariscanates404** [comment]
hello unfortunately, no.

**Comment by m-aouainia** [comment]
@nagash77  could you please check for this cypress issue ? is still always reproducible, I got the same result as @Bariscanates404  . Thank you !

**Comment by redzero2930** [comment]
still no?
same problem here

**Comment by nagash77** [comment]
@m-aouainia we still do not have a reproducible example.  If you have one please open a new ticket and include detailed instructions on how to reproduce the behavior and we will be happy to investigate.

**Comment by Hassan2419991** [comment]
Did you find any solution regarding this? I am facing the same issue.

**Comment by ZeeshanAliKharal** [comment]
@Bariscanates404 did you find any solution of it. im facing the same issue
