### ISSUE TITLE
Function type() doesn't write double backslash

### ISSUE THREAD

**Issue by Asac2142** [cypress-io/cypress#23707]
### Current behavior

I have an input, I need to type a specific value that has special characters in it, the whole of it, I have set it to `false` the property `parseSpecialCharSequences`, but when typing it doesn't type precisely as the desired value.

```
const specialValue = '$k_{el}\\degree$';
cy.log('value', specialValue) // it doesn't show as the value
cy.get('data-cy="editable-input"').type(specialValue, {  parseSpecialCharSequences: false });
```

![image](https://user-images.githubusercontent.com/12599968/188943003-42a97ed2-6d60-40ee-b3e0-f622b54a59bf.png)

![image](https://user-images.githubusercontent.com/12599968/188942472-2fd9b8d0-7d1b-4a07-a429-07216cc92981.png)

### Desired behavior

Cypress function `type()` should enter every single character if `parseSpecialCharSequences` is set to `false`.

### Test code to reproduce

This is a basic Angular application, only frontend stuff, it has some initial logic in it, the input element is within `app.component.html`, simple as that.

https://github.com/AndresCarvalloABM/Wizard-demo

### Cypress Version

10.7.0

### Node version

v14.17.4

### Operating System

macOS Big Sur 11.6.6

**Comment by nagash77** [comment]
this is a related to this issue - https://github.com/cypress-io/cypress/issues/17393.

**Comment by nagash77** [comment]
closing this issue as a dupe
