### ISSUE TITLE
[component testing v10] Unable to run Cypress component tests for app written in node 16.16.0

### ISSUE THREAD

**Issue by edwardzik** [cypress-io/cypress#23702]
### Current behavior

I'm unable to run Cypress component tests for my project build under node 16.16.0.

I was trying to build app and run it under two different Docker images from Cypress:
- cypress/included:10.7.0
- cypress/browsers:node16.14.2-slim

But for `yarn install` build I'm getting:

```
[1/5] Validating package.json...
error new-project-react@0.0.0: The engine "node" is incompatible with this module. Expected version "16.16.0". Got "16.14.2"
error Found incompatible module 
```
Afterwards I tried with **image: node:16.16.0** with installed Cypress but I'm getting missing dependencies issues, e.g. xvfb . I added all manually by `apt-get --yes install xvfb libnss3 libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2`, downloaded chrome and finally it is working BUT **is it a chance to get a docker image with Cypress 10.6.0 version with node:16.16.0** (+ older versions) + nvm: 0.38.0 + all supported browsers ? +other applications: wget, curl, ssh, zip, jq, tar, parallel, git, yarn, npm:8.11.0 etc.

### Cypress Version

v10.6.0

### Node version

v16.16.0

### Package Manager

yarn

### Package Manager Version

v1.22.15

### Operating system

Linux

### Operating System Version

Ubuntu 20.04.4 LTS

**Comment by emilyrohrbough** [comment]
@edwardzik Its unlikely we will release a new docker image with node 16.6.0. I suggest looking at our base images to create a docker image with the node version your project has defined.

Here is the repository you can use for reference: https://github.com/cypress-io/cypress-docker-images
