### ISSUE TITLE
Provide control over output of cypress run

### ISSUE THREAD

**Issue by virtualstyle** [cypress-io/cypress#2371]
### Current behavior:

Currently, no matter what reporter option is passed, cypress run spits out a bunch of formatted text. When running in a Jenkins job, it makes it far harder to review the console output and see what happened with the tests. The NO_COLOR=1 environment option helps to remove *some* of the formatting characters, but all those unnecessary boxes and cli formatting get spit out no matter what.

### Desired behavior:

Very simply, I'd like an option to get PLAIN TEXT output of the tests. Either a config option, or an env var like NO_COLORS that would suppress all the goofy formatted stuff. Even if the reporter options JUST used that reporter, rather than spitting out all the formatted gobbledygook with the reporter stuff in the middle would be nice. I get that someone wasted a good deal of time playing with CLI formatting, but that's no reason to force it on everyone.

### Versions

Cypress 3.1.0 running in Jenkins build job with console output.

**Comment by bahmutov** [comment]
@virtualstyle can you provide a snapshot of your output? Might be just a case of terminal set incorrectly and all the formatting control characters not being processed.

**Comment by virtualstyle** [comment]
Ha. I went back to a more recent run, and I don't know if it's the NO_COLORS or what, but now the output is readable:

![screen shot 2018-08-20 at 12 38 36 am](https://user-images.githubusercontent.com/2048179/44320676-835b5400-a411-11e8-8835-9519a3d7a8af.png)

Previously it was:

![screen shot 2018-08-20 at 12 38 57 am](https://user-images.githubusercontent.com/2048179/44320683-8d7d5280-a411-11e8-86e8-3885255866f9.png)

So, either the NO_COLORS env var or --reporter spec, or both, seem to have resolved the issue satisfactorily.
