### ISSUE TITLE
How can I support Node 16.16.0?

### ISSUE THREAD

**Issue by swhite194** [cypress-io/cypress#23726]
### What would you like?

My gitlab runner is configured to run NODE_IMAGE: 16.16.0
Using cypress/included 10.7.0, I can see that cypress runs NODE_VERSION: 16.14.2

Will there be a new version of cypress/included which will allow me to run 16.16.0?

### Why is this needed?

Our project needed to be updated to Node v16.16.0 to resolve a CVE issue. 
I would like the stages in my pipeline which utilise Cypress to be on the same version.

**Comment by lmiller1990** [comment]
Hi!

It's super easy to make a new Docker image like our existing ones, just see [CONTRIBUTING](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md).

By default Cypress will use the *system* Node.js version - not the bundled one. You can change this, though - [docs](https://docs.cypress.io/guides/references/configuration#Node-version).

So if your NODE_IMAGE is 16.16, when you run Cypress, it should use that version by default.

Does this help?

**Comment by ZachJW34** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
