### ISSUE TITLE
Audit consistent error handling DX for all CT frameworks / dev severs

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#23723]
# Issues created and their effect on GA

| Issue | Needed for GA | Breaking |
| ----- | :-------------: | :-------: |
| [fix: angular and nuxt ct tests now fail on uncaught exceptions](https://github.com/cypress-io/cypress/issues/24122) | x | (yes but not really since the frameworks are in alpha)
| [Normalize DevServer Config Resolution](https://github.com/cypress-io/cypress/issues/24133) | ? | x |
| [Normalize DevServer Compilation Error Reporting](https://github.com/cypress-io/cypress/issues/24135) | |
| [Hovering over mount in command log does not show the mounted component in AUT](https://github.com/cypress-io/cypress/issues/24138) | x | |
| [Better CT onboarding experience for projects with ESLint](https://github.com/cypress-io/cypress/issues/24153) | |
| [Add Export to commands.ts for projects with isolatedModules tsconfig flag](https://github.com/cypress-io/cypress/issues/24137) | |
| [Nuxt auto import component does not work in Component Testing](https://github.com/cypress-io/cypress/issues/24141) | |
| [Component name not displaying properly when importing Nuxt page component](https://github.com/cypress-io/cypress/issues/24140) | |
| [CT Mount Audit](https://github.com/cypress-io/cypress/issues/24142) | x | ? |

# Errors

## ESLint Warning

```ts
it("eslint warning", () => {
  5 + 5; // Unused expression
  cy.mount(<App />);
});
```

**Cypress**

|    Framework     | Terminal Log | Console Log | Reporter Error | Code Frame | DevServer Overlay | Test Failed |
| :--------------: | :----------: | :---------: | :------------: | :--------: | :---------------: | :---------: |
|     angular      |              |             |                |            |                   |             |
| create-react-app |      x       |             |                |            |                   |             |
|       next       |              |             |                |            |                   |             |
|       nuxt       |              |             |                |            |                   |             |
|    react-vite    |              |             |                |            |                   |             |
|     vue-cli      |              |             |                |            |                   |             |

**App**

|    Framework     | Terminal Log | Console Log | DevServer Overlay |
| :--------------: | :----------: | :---------: | :---------------: |
|     angular      |              |             |                   |
| create-react-app |      x       |             |                   |
|       next       |              |             |                   |
|       nuxt       |              |             |                   |
|    react-vite    |              |             |                   |
|     vue-cli      |              |             |                   |

- `create-react-app`
![create-react-app-eslint-warning](https://user-images.githubusercontent.com/25158820/193354983-2e51c35a-47e7-4e31-822a-9186d857d18f.png)

## ESLint Error

```ts
it("eslint error", () => {
  let thing = "Hello World!"; // Unused var
  cy.mount(<App />);
});
```

**Cypress**

|    Framework     | Terminal Log | Console Log | Reporter Error | Code Frame | DevServer Overlay | Test Failed |
| :--------------: | :----------: | :---------: | :------------: | :--------: | :---------------: | :---------: |
|     angular      |              |             |                |            |                   |             |
| create-react-app |      x       |             |                |            |                   |             |
|       next       |              |             |                |            |                   |             |
|       nuxt       |              |             |                |            |                   |             |
|    react-vite    |              |             |                |            |                   |             |
|     vue-cli      |              |             |                |            |                   |             |

**App**

|    Framework     | Terminal Log | Console Log | DevServer Overlay |
| :--------------: | :----------: | :---------: | :---------------: |
|     angular      |              |             |                   |
| create-react-app |      x       |             |         x         |
|       next       |              |             |                   |
|       nuxt       |              |             |                   |
|    react-vite    |              |             |                   |
|     vue-cli      |              |             |                   |

- `create-react-app`
![create-react-app-eslint-error](https://user-images.githubusercontent.com/25158820/193355210-4f3c0fb5-c7b0-46b8-bee0-aa847e1dd4dd.png)

## Typescript Warning

```ts
it("typescript warning", () => {
  let thing: number = "Hello World"; // number is not assignable to string

  cy.mount(<App thing={thing} />);
});
```

**Cypress**

|    Framework     | Terminal Log | Console Log | Reporter Error | Code Frame | DevServer Overlay |
| :--------------: | :----------: | :---------: | :------------: | :--------: | :---------------: |
|     angular      |      x       |      x      |                |            |                   |
| create-react-app |      x       |             |                |            |                   |
|       next       |              |             |                |            |                   |
|       nuxt       |      x       |      x      |                |            |                   |
|    react-vite    |              |             |                |            |                   |
|     vue-cli      |      x       |      x      |                |            |                   |

**App**

|    Framework     | Terminal Log | Console Log | DevServer Overlay |
| :--------------: | :----------: | :---------: | :---------------: |
|     angular      |      x       |      x      |         x         |
| create-react-app |      x       |             |         x         |
|       next       |              |             |                   |
|       nuxt       |      x       |             |                   |
|    react-vite    |              |             |                   |
|     vue-cli      |      x       |             |         x         |

- `angular`
![angular-typescript-warning](https://user-images.githubusercontent.com/25158820/193355246-9947f2f9-204f-4bb2-9e80-6132dd51a9c4.png)

- `create-react-app`
![create-react-app-typescript-warning](https://user-images.githubusercontent.com/25158820/193355262-d8c16c23-a0ad-4bf6-b537-7eff015f6cd4.png)

- `nuxt`
![nuxt-typescript-warning](https://user-images.githubusercontent.com/25158820/193355286-bcd4474e-58f2-4a9b-99f6-0c49292dec67.png)

- `vue-cli`
![vue-cli-typescript-warning](https://user-images.githubusercontent.com/25158820/193355387-d7deea7a-764c-4744-8c5e-6e0667c22ed2.png)

## Typescript Error (Compilation Error)

```ts
it('typescript error', () => {
  {}/()aa>

  cy.mount(<App />);
})
```

**Cypress**

|    Framework     | Terminal Log | Console Log | Reporter Error | Code Frame | DevServer Overlay | Test Failed |
| :--------------: | :----------: | :---------: | :------------: | :--------: | :---------------: | :---------: |
|     angular      |      x       |      x      |       x        |            |                   |      x      |
| create-react-app |      x       |             |       x        |            |                   |      x      |
|       next       |      x       |      x      |       x        |     x      |                   |      x      |
|       nuxt       |      x       |      x      |       x        |            |                   |      x      |
|    react-vite    |      x       |             |       x        |            |         x         |      x      |
|     vue-cli      |      x       |      x      |       x        |            |                   |      x      |

**App**

|    Framework     | Terminal Log | Console Log | DevServer Overlay |
| :--------------: | :----------: | :---------: | :---------------: |
|     angular      |      x       |      x      |         x         |
| create-react-app |      x       |             |         x         |
|       next       |      x       |      x      |         x         |
|       nuxt       |      x       |      x      |         x         |
|    react-vite    |      x       |      x      |         x         |
|     vue-cli      |      x       |             |         x         |

- `angular`
![angular-typescript-error](https://user-images.githubusercontent.com/25158820/193355419-286143fa-9b4e-4474-bcba-e35d863c035e.png)

- `create-react-app`
![create-react-app-typescript-error](https://user-images.githubusercontent.com/25158820/193355451-db4d3a4b-5d95-4467-9b1b-38e8fc777be2.png)

- `next`
![create-next-app-typescript-error](https://user-images.githubusercontent.com/25158820/193355477-297e9428-08d8-45ee-ab0f-4764c2f8b3f6.png)

- `nuxt`
![nuxt-typescript-error](https://user-images.githubusercontent.com/25158820/193355503-8cd08da4-74bb-478a-8b65-550e8ad5efec.png)

- `react-vite`
![react-vite-typescript-error](https://user-images.githubusercontent.com/25158820/193355532-11d44677-2b78-4c05-91f9-fe49977b2cf1.png)

- `vue-cli`
![vue-cli-typescript-error](https://user-images.githubusercontent.com/25158820/193355555-34ea8065-5c28-4264-805e-55cfaf849ab5.png)

## Runtime Error (App)

```ts
it("runtime error in component", () => {
  cy.mount(<App />);
  cy.get("button").click(); // Wired up to button that throws error
});
```

**Cypress**

|    Framework     | Terminal Log | Console Log | Reporter Error | Code Frame | DevServer Overlay | Test Failed |
| :--------------: | :----------: | :---------: | :------------: | :--------: | :---------------: | :---------: |
|     angular      |              |      x      |                |            |                   |             |
| create-react-app |              |      x      |       x        |     x      |                   |      x      |
|       next       |              |      x      |       x        |     x      |                   |      x      |
|       nuxt       |              |      x      |                |            |                   |             |
|    react-vite    |              |      x      |       x        |            |                   |      x      |
|     vue-cli      |              |      x      |       x        |    x\*     |                   |      x      |

**App**

|    Framework     | Terminal Log | Console Log | DevServer Overlay |
| :--------------: | :----------: | :---------: | :---------------: |
|     angular      |              |      x      |                   |
| create-react-app |              |      x      |                   |
|       next       |              |      x      |         x         |
|       nuxt       |              |      x      |        x\*        |
|    react-vite    |              |      x      |                   |
|     vue-cli      |              |      x      |                   |

- `angular`
![angular-runtime-error-app](https://user-images.githubusercontent.com/25158820/193355578-9131fb64-aba4-444e-adf1-91a061ac0128.png)

- `create-react-app`
![create-react-app-runtime-error-app](https://user-images.githubusercontent.com/25158820/193355641-ec025752-0fd5-48a1-99e9-edc1c37f35e3.png)

- `next`
![create-next-app-runtime-error-app](https://user-images.githubusercontent.com/25158820/193355672-7e1d05c0-3da0-43ad-b9d1-cf23a4178574.png)

- `nuxt`
![nuxt-runtime-error-app](https://user-images.githubusercontent.com/25158820/193355709-22386f07-31d0-4fef-b34c-1fb8c332a00f.png)

- `react-vite`
![react-vite-runtime-error-app](https://user-images.githubusercontent.com/25158820/193355725-e237e74a-3448-49f8-b210-6e02206aae70.png)

- `vue-cli`
![vue-cli-runtime-error-app](https://user-images.githubusercontent.com/25158820/193355755-9a362506-b61f-41be-814b-c03e72c5f935.png)

## Runtime Error (Test)

```ts
it("runtime error in spec", () => {
  throw new Error("uh oh");
  cy.mount(<App />);
});
```

**Cypress**

|    Framework     | Terminal Log | Console Log | Reporter Error | Code Frame | DevServer Overlay | Test Failed |
| :--------------: | :----------: | :---------: | :------------: | :--------: | :---------------: | :---------: |
|     angular      |              |             |       x        |     x      |                   |      x      |
| create-react-app |              |             |       x        |     x      |                   |      x      |
|       next       |              |             |       x        |     x      |                   |      x      |
|       nuxt       |              |             |       x        |     x      |                   |      x      |
|    react-vite    |              |             |       x        |     x      |                   |      x      |
|     vue-cli      |              |             |       x        |     x      |                   |      x      |

- `angular`
![angular-runtime-error-spec](https://user-images.githubusercontent.com/25158820/193355772-fb4c96fa-cd8f-4182-90e4-bdcb966ee5cb.png)

- `create-react-app`
![create-react-app-runtime-error-test](https://user-images.githubusercontent.com/25158820/193355802-b09d211c-4508-4cf3-925a-3d4f4a0dadcc.png)

- `next`
![create-next-app-runtime-error-test](https://user-images.githubusercontent.com/25158820/193355818-fbf317a1-9b31-48f4-acac-8cdf90e32b69.png)

- `nuxt`
![nuxt-runtime-error-spec](https://user-images.githubusercontent.com/25158820/193355839-30606b7a-c641-4aba-87a2-00a58cce9b56.png)

- `react-vite`
![react-vite-runtime-error-test](https://user-images.githubusercontent.com/25158820/193355862-ad666e0d-54f0-45d2-b193-671dc124de7a.png)

- `vue-cli`
![vue-cli-runtime-error-spec](https://user-images.githubusercontent.com/25158820/193355879-7429fa83-f12a-437e-9321-e173f03770d9.png)

## Summary

| Error Type | Summary |
| ---------- | ------- |
| ESLint warning | ESLint warnings had no effect on the outcome of the test. `create-react-app` is the only framework that has ESLint integrated into the compilation. There are ENV variables that can be used to change this behavior ([ESLINT_NO_DEV_ERRORS, DISABLE_ESLINT_PLUGIN](https://create-react-app.dev/docs/advanced-configuration)), but the defaults align with the behavior of apps that don't have ESLint integrated. |
| ESLint Error | ESLint errors had no effect on the outcome of the test. |
| Typescript Warning | Typescript Warnings had no effect on the outcomes of the test. |
| Typescript/Compilation Error | Typescript/Compilation Error caused every test to fail. Inline with expected behavior |
| Runtime Error (App) | Framework dependent. Desired behavior is that a runtime error in the component under test should fail the test, but Angular and Nuxt components swallowed the error. |
| Runtime Error (Test) | Runtime Errors caused all apps to report a failed test. Inline with expected behavior. |

### Webpack vs vite

The behavior of Webpack and Vite were functionally the same (disregarding framework outliers). The only difference noted was the error reporting due to compilation errors:
- Webpack: Reports error in Reporter, AUT is blank
- Vite: Reports error in Reporter, AUT has error overlay
  - The error in the reporter for Vite is barebones e.g. `Failed to request module`. The error in the AUT overlay contains what actually went wrong.

On compilation error, Webpack will: serve the asset containing the error, but replace the modules contents with `throw new Error(<node-stack-trace>)`.

On compilations error, Vite will: not serve the asset meaning the request will fail. The error is sent to the frontend via websocket and displayed in the overlay.

Though the behavior differs, the content is the same. Normalizing this behavior will not result in a breaking change.

### Outliers

- Angular: Runtime error in app did not cause test to fail
- Nuxt: Runtime error in app did not cause test to fail
- Vue-CLI: Relative Code Frame path did not link to correct location
- Next: Code-frame was shown for compilation error

# DevServer API

Webpack DevServer Config API:

```ts
type LowLevelFrameworks = 'react' | 'vue' | 'svelte'
type HighLevelFrameworks = 'angular' | 'create-react-app' | 'next' | 'nuxt' | 'vue-cli'

interface WebpackDevServerConfig {
  framework: LowLevelFrameworks | HighLevelFrameworks,
  bundler: 'webpack',
  webpackConfig: any,
  options?: Record<any, any>
}
```

Vite DevServer Config API:

```ts
type LowLevelFrameworks = 'react' | 'vue' | 'svelte'

interface ViteDevServerConfig {
  framework: LowLevelFrameworks
  bundler: 'vite',
  viteConfig: any
}
```

## Config Resolution

An inconsistency in how configs are sourced was found between `webpack-dev-server` and `vite-dev-server` when using the low-level frameworks (`vite-dev-server` does not have support for higher order frameworks, but will soon). The config resolution is outlined below for each:

- Webpack:
  - devServer.webpackConfig = {} | undefined
  - if (!devServer.webpackConfig) devServer.webpackConfig = require('<project-root>/webpack.config.js')
  - merge(webpack.devServerConfig, cypressWebpackConfig)
- Vite:
  - devServer.viteConfig = {} | undefined
  - let userConfig = require('<project-root>/vite.config.js')
  - merge(userConfig, viteConfig, cypressViteConfig)

They look similar, but differ by how the auto-detected webpack/vite config is used. If a user provides a `devServer.webpackConfig` property, we will **not** detect or merge their `<project-root>/webpack.config.js`. If a user provides a `devServer.viteConfig`, these options will be merged with their auto-detected `<project-root>/webpack.config.js`.

## `webpackConfig`/`viteConfig` Type

Currently, these are types as `any`. Some users have put strings here, thinking Cypress will resolve a file-system path for them. An improvement could be `Record<any, any>` to at least denote it is an object.

The outcome should be making a recommendation on how to address the consistency in the next sprint.

## Onboarding

General Issues:
1. When hovering over `Mount` in the command log, the AUT shows a blank view. This should probably display the mounted component

### `angular`

I did `npm install -g @angular/cli`. I made a new app and a simple component - works great. I included SCSS and Routing.

On-boarding worked as expected - all the files were generated in the correct places.

### `nuxt`

Nuxt's on-boarding experience did not have any configuration issues. Typescript and ESLint configurations did not need modified.
It was able to utilize Create Spec from Vue Component.

The issues experienced during the on-boarding experience were:
1. Page shows component name in the command log as `<f .../>` instead of the component name (See nuxt screenshots above)
2. The user has to add any children component into the `components` object in the exported object. This is not required when running the app in dev mode.

### `vue-cli`

Vue cli's on-boarding experience had a couple steps to get eslint and typescript happy. Typescript config needed to be updated for TS projects
by adding the cypress config to the `tsconfig.json` file. ESLint config needed to be updated for non typescript projects by adding the
`eslint-cypress-plugin` library.

### `next`

`create-next-app`

On-boarding Next using vanilla js did not have any configuration issues. Tests ran as expected on the 
first attempt.

`create-next-app --typescript`

`create-next-app` using typescript requires `export {}` to be added to commands.ts due to the tsconfig `isolatedModules` flag.

### `react`

`create-react-app`

On-boarding React using vanilla js did not have any configuration issues. Tests ran as expected on the
first attempt.

`create-react-app --typescript`

On-boarding React using typescript needed to add `export {}` to commands.ts due to the tsconfig `isolatedModules` flag.
IDEs are not happy with jest + cypress testing. This may require
reorganization and configuration changes if you need to keep existing jest tests in your project

**Comment by lmiller1990** [comment]
TODO: Verify what areas/things to do to verify (eg, what do we need to check).

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23723?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
This seems like a relatively small task but to @lmiller1990's point, we need to pin down the "etc" to a list of things that should be the same.

**Comment by baus** [comment]
We should audit this first, and provide recommendations for the implementation which will be in a future iteration.

**Comment by lmiller1990** [comment]
I'm yet to clarify if this is E2E or just CT, but we've got some common warnings in the console across all frameworks (and possibly E2E testing).

![image](https://user-images.githubusercontent.com/19196536/193161896-1aa48bef-4e9f-47de-9b36-061c9f0e1714.png)

It would be nice to get rid of these (at least, the warnings and error) even if they are harmless.
