### ISSUE TITLE
I am using cypress version 10.6.0. I am integrating cypress tests with Jenkins CI pipeline. I am stuck with because of following error message in Jenkins console.

### ISSUE THREAD

**Issue by DeepakB01** [cypress-io/cypress#23747]
I am using cypress version 10.6.0. I am integrating cypress tests with Jenkins CI pipeline. I am stuck with because of following error message in Jenkins console.

The Test Runner unexpectedly exited via a exit event with signal SIGILL

I would request community here and cypress support to help me fix this issue.

_Originally posted by @DeepakB01 in https://github.com/cypress-io/cypress/discussions/23746_

**Comment by nagash77** [comment]
@DeepakB01 please open this issue using the report an issue template in GitHub.  That will prompt you for the information we will need in order to best help as much as we can.  Thank you.
