### ISSUE TITLE
About Continous failure of test due to network issue

### ISSUE THREAD

**Issue by heyitsmesujan** [cypress-io/cypress#2375]
### Current behavior:
Every time I run my test, there occurs the error in the test cases that passed previously. This error is due to network fluctuation. I tried cy.wait() but the request time keep varying and which results is continuous failure of the spec in multiple places those passed previously.

### Desired behavior:
Is there any solution to overcome this issue other than cy.wait() ??

**Comment by jennifer-shehane** [comment]
Could you provide a sample of your test code where you are having timeouts?

**Comment by heyitsmesujan** [comment]
//Product Value
            cy.get('#term-value-1').click()
            cy.get('#term-value-2').click()
            cy.get('#term-value-3').click()
            cy.get('#term-value-6').click()
            cy.get(':nth-child(5) > .col-xs-12 > .pull-right').contains('Continue').click()
            cy.wait(10000)

             //Life Quotes
             
              **cy.get('#term-panel > div:nth-child(5) > div.col-xs-12.col-md-5 > div > div > div.col-lg-4.col-md-12 > div.btn.button.fit.btn-sm.plate-submit.continue-button').click()**
//Mostly issue has been faced on these lines

             //cy.get('button').contains('Continue').click()                 
            // cy.get('#term-panel .row:nth-child(3) [class="col-xs-12 col-md-8"] div').contains('Continue').click()
            cy.wait(5000)

//Perfect fit
			cy.get('#assur-value-1').click() 
			cy.get('#assur-value-2').click()
			cy.get('#assur-value-3').click()
			cy.get('#assur-value-5').click()
			cy.contains('Continue').click()
			cy.wait(5000)

_I have been using cy.wait(),but still facing following Error,This occur frequently but not always._

![timeouterror](https://user-images.githubusercontent.com/18730908/44568533-fe689580-a796-11e8-8062-0d763a2c2522.PNG)

**Comment by jennifer-shehane** [comment]
We typically do not suggest using `cy.wait()` commands with arbitrary milliseconds. There are some suggestions for handling 'waiting' for elements to appear in our docs:

- [Unnecessary Waiting](https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-Waiting)
- [How do I wait for my application to load?](https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-wait-for-my-application-to-load)

On first glance, it looks like that element you are trying to find may not appear within the application until a specific network request responds - you may try waiting for that specific network request first.
