### ISSUE TITLE
Test Runner can hang indefinitely on hot-reload

### ISSUE THREAD

**Issue by ax-vasquez** [cypress-io/cypress#23757]
### Current behavior

**Summary:** _The app-hosted browser can freeze when attempting to hot-reload, leading to an unrecoverable session; forces the user to kill the browser and restart._

When making edits to spec files in quick succession with VS Code's auto-save feature enabled, it appears to "overwhelm" the test runner's hot-reloading logic, leading it to hang indefinitely.

When this happens, the user has no choice but to force-kill the app-hosted browser (e.g., Chrome). Strangely, the App _launcher_ does not seem to be affected by this. If the test runner starts hanging, you can still interact with the App Launcher, **but it will not be able to close the app-hosted browser window if it's hanging; that can only be done with force-killing it**.

### Desired behavior

Live-edits to spec files in VS Code with auto-save enabled works as expected; when changes are made to a spec while it's running, the runner appropriate stops the running spec and restarts it with the new changes.

### Test code to reproduce

1. Enable auto-save in VS code
2. Launch the App
3. Select Chrome
4. Select an arbitrary spec to run > navigate to that file in VS code
5. Make several edits, but wait between each edit to see that the runner attempts to reload
   * **NOTE:** _It appears that a core part of replicating this depends on making a change right as the previous run starts (e.g., NOT when it's loading - changes made while the runner is in the loading state appear to be unaffected)_

_It's when the runner attempts to reload that the freezing will occur._

### Cypress Version

10.6.0

### Node version

v14.20.0

### Operating System

macOS 12.5.1

### Debug Logs

```shell
cypress:webpack warnings for /Users/armando/Library/Application Support/Cypress/cy/production/projects/dashboard-a84e65792b1c0314a73ba8a6c3a72704/bundles/cypress/integration/runs/tabs/RunOverview_TestsForReview_spec.ts.js [ 'EnvironmentPlugin - NODE_ENV environment variable is undefined.\n' + '\n' + 'You can pass an object with default values to suppress this warning.\n' + 'See https://webpack.js.org/plugins/environment-plugin for example.', 'EnvironmentPlugin - SERVER_ENV environment variable is undefined.\n' + '\n' + 'You can pass an object with default values to suppress this warning.\n' + 'See https://webpack.js.org/plugins/environment-plugin for example.', 'EnvironmentPlugin - SERVER_ENV environment variable is undefined.\n' + '\n' + 'You can pass an object with default values to suppress this warning.\n' + 'See https://webpack.js.org/plugins/environment-plugin for example.' ] +405ms
  cypress:webpack finished bundling /Users/armando/Library/Application Support/Cypress/cy/production/projects/dashboard-a84e65792b1c0314a73ba8a6c3a72704/bundles/cypress/integration/runs/tabs/RunOverview_TestsForReview_spec.ts.js +0ms
  cypress:webpack - compile finished for /Users/armando/Documents/Repositories/cypress-io/cypress-services/frontend/packages/dashboard/cypress/integration/runs/tabs/RunOverview_TestsForReview_spec.ts, initial? false +2ms
```

### Other

I tried to include as many logs as I could, but most seemed to be simple informational logs. I did see a warning from the webpack debug logs, though - provided that.

**Comment by lmiller1990** [comment]
I tried using CRA and webpack but no luck so far - I just created a basic test and spam cmd + save but it did not crash. I also tried with autosave.

Any other tips? I wonder if we have a race condition somewhere.

**Comment by ZachJW34** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
