### ISSUE TITLE
Cant start HTML5 Video due to autoplay policy - Cypress should disable requiring user gesture for video

### ISSUE THREAD

**Issue by frazboyz** [cypress-io/cypress#2376]
### Current behavior:
Unable to invoke the video play function in cypress but can in chrome dev tools.

### Desired behavior:
When invoking the play function on an html5 video element, it should play.

### Steps to reproduce:
I have tried numerous ways of playing the video. In dev tools, all you need to do is $('video').play(); and that works.

I have tried the below two options, neither plays the video.
```javascript
it('Watch video till the end', () => {
    cy.wait(3000);
    cy.get('video').then(() => {
      const video = Cypress.$('video');
      if (!video) {
        throw new Error('Cant find video');
      }
      video.play();
    });
});
```
```javascript
  it('Watch video till the end', () => {
    cy.get('video#introVideo')
      .then(video => {
        const videoElement = video.get(0);
        return new Promise((resolve) => {
          videoElement.oncanplay = () => {
            videoElement.play();
          };
          videoElement.onended = () => {
            resolve(true);
          }
        });
      })
      .get('button')
      .contains('I have everything ready. Let’s get started!')
      .click();
  });
```

### Versions
Cypress 3.0.2, 3.1.*
Chrome 68

**Comment by frazboyz** [comment]
I found the issue, it is due to chromes new auto-play video policies.

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

You can simply mute the video and then playing it is allowed like so.

```
cy.get('video#introVideo')
      .then(video => {
        const videoElement = video.get(0);
        videoElement.muted = true;
        return new Promise((resolve) => {
          videoElement.oncanplay = () => {
            videoElement.play();
          };
          videoElement.onended = () => {
            resolve(true);
          }
        });
      })
```

**Comment by jennifer-shehane** [comment]
> Top frames can delegate autoplay permission to their iframes to allow autoplay with sound.

iframe delegation instructions: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#iframe

Although it says 

> Note that autoplay is allowed by default on same-origin iframes.

**Comment by jennifer-shehane** [comment]
I came across this Chrome flag that may be relevant - and I think should be added to Cypress by default:

```
--no-user-gesture-required

Autoplay policy that does not require any user gesture.
```

Could you try adding this Chrome flag to your run to see if it works with the restriction removed? An example of how to do this can be found [here](https://on.cypress.io/browser-launch-api#Modify-the-arguments-based-on-the-browser-Cypress-is-launching)

**Comment by melbourne2991** [comment]
This was raised as unexpected behaviour, and I guess back when chrome changed their policies it would have been unexpected. I would argue that now, adding a special flag that differs from what has now become the expected browser behaviour leads to... well unexpected behaviour.

I ran into this issue and had to write some plugin code to override the behaviour and disable auto play:
https://github.com/cypress-io/cypress/issues/5015
