### ISSUE TITLE
[ACI post-project connection] Connect smart banners to new logic

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#23767]
Drive the SpecsListBanners behavior fully with the logic created in #23765.

**Acceptance Criteria**

1. Log In, Create Organization, and Connect Project variants should all open the Connect Dashboard Modal Flow, which should change state accordingly
2. Record Run variant should have a minimum 1 day delay from when any other Smart Prompt Banner variant is shown
3. Record Run variant should have a minimum 1 day delay from when the Connect Dashboard Modal Flow is shown
4. Record Run variant should show when logged_in && organizations > 0 && project_connected && runs === 0 && specs_written_not_matching_examples > 0 
5. All Smart Prompt Banners should have a minimum 1 day delay from when the Auto-Open Docs Menu is shown (confirm, is likely already implemented)

**References**
Whimsical: https://whimsical.com/get-to-first-run-TgixRWciqE1chPGDCHk5b2
Figma: https://www.figma.com/file/V0lCq4uBplf9J3GZRiD02m/ACI-Fast-Follows?node-id=19661%3A172759
Clickup: https://app.clickup.com/t/18033298/PM-2556

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23767?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
