### ISSUE TITLE
How do I test fabric.js with cypress?

### ISSUE THREAD

**Issue by nitingupta220** [cypress-io/cypress#2378]
I'm using fabric.js in my website.
I want to test it using cypress.
Can you tell me how to do it?
@jennifer-shehane @brian-mann

**Comment by frazboyz** [comment]
This is my best guess.
- Get an instance of the canvas
- Perform your mutations to the canvas the same way you would in normal javascript
- Serialize the canvas and compare it to a snapshot.

**Comment by nitingupta220** [comment]
@frazboyz I got the instance but then the actions that I want to do on it is not possible.
Because no command is working on the canvas.

**Comment by frazboyz** [comment]
cy.get('canvas').then(canvas => {
    const element = canvas.get(0);
   // Mutate the canvas using standard javascript, if you need to use another library, you will need to add that to your cypress project.
   return canvas;
});

**Comment by frazboyz** [comment]
I would also suggest reading the Cypress documentation further.

**Comment by sainthkh** [comment]
If you have any other questions, please use https://github.com/cypress-io/cypress/discussions
