### ISSUE TITLE
updateSnapshot for specific test 

### ISSUE THREAD

**Issue by 787681277** [cypress-io/cypress#23796]
### What would you like?

updateSnapshot for specific test  instead of all tests

### Why is this needed?

updateSnapshot for specific test  instead of all tests,
1) get a correct baseline image after specific fix, don't need to run all tests ,like use @tag or spec name ,which can save a lot of time

**Comment by emilyrohrbough** [comment]
Looks to be related to https://github.com/cypress-io/cypress/discussions/23795.

The `cypress-image-snapshot` plugin is not maintained by Cypress. Please ask on their repo: https://www.npmjs.com/package/cypress-image-snapshot or each out to the community in discord: https://on.cypress.io/chat.
