### ISSUE TITLE
ExperimentalWebkitSupport tooltip on the "Choose your Browser" page is flickering on: hover

### ISSUE THREAD

**Issue by amehta265** [cypress-io/cypress#23802]
In smaller screen sizes or when multiple browser options are shown, the tooltip on browser button renders multiple times leading to a flickering behavior. 
- The intended behavior is that on:hover, the information shown should display without flickering multiple times

https://images.zenhubusercontent.com/31629751/e536d5b5-bb74-4a2d-b349-7b81a43fa68f/screen_recording_2022_09_13_at_10_55_04_am.mov

**Comment by tbiethman** [comment]
The tooltip presenting under the pointer (and triggering multiple hover events) is likely the culprit. Might need to present the tooltip from the info icon rather than the browser icon, or the card itself?

**Comment by amehta265** [comment]
I was thinking along the same lines. After discussing with @marktnoonan we also believe the positioning of the tooltip is leading to consecutive hover events. My first attempt would be moving the description a little higher to prevent it overlapping the tooltip and we can take it from there

**Comment by marktnoonan** [comment]
Yeah @mapsandapps's design recommendation was to pop it from the tooltip and not have it point to the top of the browser as well 👍
