### ISSUE TITLE
Assertion shows as spinning after passing in interactive mode

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2380]
Cypress 3.1.0 on Mac

In one of the tests that uses a DOM alias, the assertion passes, but the command log keeps the spinner going

<img width="1398" alt="screen shot 2018-08-21 at 10 59 24 pm" src="https://user-images.githubusercontent.com/2212006/44440429-086f7600-a596-11e8-97a7-db9f31f456e5.png">

## Recreate

- clone https://github.com/cypress-io/testing-workshop-cph and switch to branch `mot-rio-demo`

```
git clone git@github.com:cypress-io/testing-workshop-cph.git
cd testing-workshop-cph
git checkout mot-rio-demo
npm install
```

- start local server `npm start`
- open Cypress from another terminal `npm run cy:open`
- select spec file `02-adding-items/spec.js`

The problem is the test "can alias items"

## second problem

When hovering or clicking over the alias, only the _initial_ elements in the alias are highlighted, not the later ones, that are actually passing the assertion

<img width="1198" alt="screen shot 2018-08-21 at 11 05 05 pm" src="https://user-images.githubusercontent.com/2212006/44440625-ef1af980-a596-11e8-990e-d35704031094.png">

**Comment by jennifer-shehane** [comment]
This is still an issue in Cypress 3.4.0

**Comment by emilyrohrbough** [comment]
This should have been fixed in https://github.com/cypress-io/cypress/pull/24511 when the assertion log handling was updated. This was released in [11.1.0](https://on.cypress.io/changelog#11-1-0).  Please let us know if you are still seeing this issue.

**Comment by rodrigocnascimento** [comment]
**UPDATE: discovered my problem when trying to reproduce. As I'm using React, the useEffect, will render twice making the API call twice as well. Either way the second API call gets hanging  beside the fact that the test is successful concluded. Don't know how much it could affect my tests, but seems to work pretty well.**

~~ 
I'm facing the same problem, but on Linux.
Should I open another issue? I could maybe try to reproduce the issue on a repository.

```
Cypress version: cypress@12.7.0
----
Linux
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
~~

**Comment by emilyrohrbough** [comment]
@rodrigocnascimento Please open a new issue with details
