### ISSUE TITLE
Cypress does not give a clean state to the browser you choose for e2e tests

### ISSUE THREAD

**Issue by AnthonyMadia** [cypress-io/cypress#23813]
### Current behavior

I was running e2e tests and noticed a failure because a database instance was already created even though I had just fired up the tests. 

### Desired behavior

In this situation, Cypress should present a clean state before launching the desired browser with no database instance already initiated from a past instance of the application run locally on localhost:3000 outside of e2e tests.  Would be nice for this to be wiped automatically when e2e tests are fired up.

### Test code to reproduce

N/A

### Cypress Version

10.3.1

### Node version

16.16

### Operating System

macOS 12.4

**Comment by nagash77** [comment]
@AnthonyMadia There isn't enough information here for us to assist.  Which repo are you running tests against?  Do you have a specific test that fails?  Do you have any logs that can give us insight into what is happening locally for you?  Without more information we will not be able to help very much.

**Comment by AnthonyMadia** [comment]
I have an application that create a db instance when I run it on localhost:3000 on chrome. When I run the e2e tests with chrome as my browser, the state that I have on localhost:3000 is used for the chrome browser. The issue is that I thought cypress would provide a clean browser state even though I had the process running on localhost:3000.

**Comment by AnthonyMadia** [comment]
It just took me a while to debug that the issue was that I had a an instance of the app running on localhost:3000 that was causing the problem and it was not any other issue wrong with my test code.

**Comment by AnthonyMadia** [comment]
Maybe the suggestion should be cypress should kill all other processes on localhost:3000 (or any other port tests are running on) before running the tests.

**Comment by chrisbreiding** [comment]
Cypress will provide a clean browser state, but that's limited to state that's in the browser. We'd rather leave it up to test authors to manage any state outside of the browser, including running processes.
