### ISSUE TITLE
Videos getting generated for all the test cases whether pass or fail with "videoUploadOnPasses": false

### ISSUE THREAD

**Issue by Sjain01** [cypress-io/cypress#2382]
### Current behavior:

I am running bunch of test scenarios with option "videoUploadOnPasses": false and for all those scenarios whether pass or fail , video recordings are getting generated.

### Desired behavior:
For example - in attached snapshot - forgot password has successfully executed but in next snapshot you can see the video is generated even though it has passed **which in this case the video should not be generated**
<img width="407" alt="screen shot 2018-08-22 at 14 52 14" src="https://user-images.githubusercontent.com/28809161/44464530-5084ac00-a61b-11e8-9710-a7f72c3be4b6.png">

<img width="277" alt="screen shot 2018-08-22 at 14 53 12" src="https://user-images.githubusercontent.com/28809161/44464538-54b0c980-a61b-11e8-8e59-d9601c3db005.png">

### Steps to reproduce:

Set "videoUploadOnPasses": false and execute any test. Irrespective whether it fails or pass , video recordings are done by default for all.

### Versions
Cypress:    3.1.0                                                                              │
Browser:    Electron 59 (headless)

**Comment by bahmutov** [comment]
so the video is generated, but not _uploaded_ to the Cypress dashboard. Do you think you want to just delete video file / not encode it on passing spec? Basically we have to record the video in case the spec fails...

**Comment by Sjain01** [comment]
@bahmutov - I can delete the video that is not an issue. But my issue here is as the cypress docs says setting "videoUploadOnPasses": false should **only generate videos when the test case fails** whereas in above case video is getting generated even if the test is passing.

**Comment by AlbertQM** [comment]
As mentioned by @bahmutov, videoUploadOnPasses != videoRecordOnPasses.

Although it'd be nice having Cypress deleting the video in case the spec passes.

In my case, I didn't need videos at all so I solved the problem by simply passing this flag.

```
config: {
        video:false
      }
```

**Comment by bahmutov** [comment]
@Sjain01 where do you see this in the docs, that seems wrong

https://docs.cypress.io/guides/references/configuration.html#Videos

![screen shot 2018-08-22 at 9 35 23 am](https://user-images.githubusercontent.com/2212006/44466632-bd358180-a5ee-11e8-91b4-64468a8c3c66.png)

**Comment by pmomot** [comment]
So now as I see, there is no option to have videos of only failing specs, is it correct?

**Comment by Sjain01** [comment]
@bahmutov - Yes , this is the one I was talking about. 

Can a change be made in docs then to clearly indicate the usage of the above said parameter.

**Comment by Sjain01** [comment]
@bahmutov - My bad,  I mixed up two things , thank you for your time and explanation.

**Comment by seyfer** [comment]
I think this one can be closed in favor of https://github.com/cypress-io/cypress/issues/2522 ?
