### ISSUE TITLE
Cypress 10 Version - Not Click the button by using click() Method

### ISSUE THREAD

**Issue by chandrakumar1988** [cypress-io/cypress#23837]
### Current behavior

I am not able to Click the button even though i have enter correct CSS Selector .
![image](https://user-images.githubusercontent.com/47958062/190376934-f604d191-83d2-40b3-8ea6-6f1a857f2d7b.png)
![image](https://user-images.githubusercontent.com/47958062/190377010-ab853bfd-7061-4948-8e8c-967455aa665c.png)

I have used both command - Its detecting the element but not click the button .
cy.get('#submitButton').click()
cy.get('.Submitbtn').contains('Log In').click()

### Desired behavior

Click () Function not working 

### Test code to reproduce

step1 : Launch the URL
step2 : Entered the User name 
step3: click the login button by using the below command 
 cy.get('#submitButton').click()
 //cy.get('.Submitbtn').contains('Log In').click()
Step 4: Cypress detect the login button but not Click the button
![image](https://user-images.githubusercontent.com/47958062/190377489-0a9d1fac-41ab-418f-a7e4-604a04dd5a0d.png)

### Cypress Version

10.8.0

### Node version

v10.8.0

### Operating System

windows 10

**Comment by admah** [comment]
@chandrakumar1988 is there any way that you could share the HTML markup that you're trying to select?

**Comment by chandrakumar1988** [comment]
Please find the HTML Markup for your reference.
![image](https://user-images.githubusercontent.com/47958062/191739056-9fc8e420-4ee2-4e4d-a854-af7d92143365.png)
-----------------------------------------------
And also one more issue I am using Azure cloud vdi machine ..if chrome browser was  already open then when i try to lunch Cypress - Its not launching the new chrome browser its open in an existing open chrome browser. 
![image](https://user-images.githubusercontent.com/47958062/191740104-da2e684c-fa8a-4d1a-9791-31fbb00d1761.png)
![image](https://user-images.githubusercontent.com/47958062/191740551-3b87eb7e-9924-431f-85d9-d291e5d818fd.png)
-------------------------

**Comment by mikespinks0401** [comment]
@chandrakumar1988 try chaining two clicks  elemtn.click().click() and see if it works. For some reason I had to do the same. It also worked with a wait(100) before the click

**Comment by chandrakumar1988** [comment]
cy.wait(5000)
 cy.get('#submitButton').should('be.visible').should('be.enabled').click()
![image](https://user-images.githubusercontent.com/47958062/191923839-09e69fa9-49ea-4ccb-a3ce-0f686d1e6012.png)
I have used the same but its not working in chrome but working in Edge

**Comment by astone123** [comment]
@chandrakumar1988 can you clarify what you are having trouble with? The issue title says that you can't click an element, but in the issue description there is a screenshot of a Cypress error saying that an element can't be found with `cy.get('[name=x]')`.

When you say it's not working in Chrome, what exactly do you mean? From the command log, it looks like the click actions are successfully being performed. Is the screenshot of the command log from Chrome or Edge?

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
