### ISSUE TITLE
Firefox Tooltip - Only Show when ChromeWebSecurity=false

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#23846]
### Current behavior

<img width="603" alt="Screen Shot 2022-09-15 at 12 54 59 PM" src="https://user-images.githubusercontent.com/14099737/190476399-59848741-8fd6-47f8-8c00-53cbf85b9f98.png">

when I have `chromeWebSecurity=true`
<img width="1683" alt="Screen Shot 2022-12-08 at 2 09 09 PM" src="https://user-images.githubusercontent.com/14099737/206558486-7f9a4af3-9820-4147-a402-3850ce723517.png">

when I have `chromeWebSecurity=false`
<img width="1676" alt="Screen Shot 2022-12-08 at 2 11 37 PM" src="https://user-images.githubusercontent.com/14099737/206558509-c4efb6b7-abfd-46b1-a552-e39953c26438.png">

### Desired behavior

Only present the firefox info icon when `chromeWebSecurity = false`

### Test code to reproduce

Launch Cypress with Firefox on machine.

### Cypress Version

10.8.0

**Comment by keremh** [comment]
hi can i work on this issue?

**Comment by Aleff13** [comment]
> Did u work on it?

**Comment by Aleff13** [comment]
@keremh did u work on it?
