### ISSUE TITLE
HTTP Status 304 (NOT MODIFIED) are treated as an error (empty string)

### ISSUE THREAD

**Issue by pbouamriou** [cypress-io/cypress#23853]
### Current behavior

HTTP Server implements ETag / If_None_Match mechanism.
index.html requires js ressource (<script type="text/javascript" src="app.bundle.js"></script>)

Behavior is identical for electron (v102) / firefox (v91) / chromium (v103). 
Without Cypress, behavior is ok with firefox (v91) and chromium (v103) 

Test Cypress : Just visit http://localhost

First run : Test is ok 
Second run (shortcut R) : Test is nok (app.bundle.js is not loaded, HTTP Status : 304).

In cypress console, i can see :
GET /app.bundle.js 304 8.770 ms - -

In dev-tools :

![error_app_bundle js](https://user-images.githubusercontent.com/19939670/190664612-3e834504-0a9a-4550-b1ed-26521cb5406d.png)

![error_app_bundle_detail js](https://user-images.githubusercontent.com/19939670/190664691-07f76996-eeb7-4a6e-a061-a9ab87bfda91.png)

### Desired behavior

Cypress should use the cache on HTTP Status 304.

### Test code to reproduce

HTTP Server implement ETag / If_None_Match mechanism

index.html requires js ressource (<script type="text/javascript" src="app.bundle.js"></script>)

Test Cypress : Just visit http://localhost

### Cypress Version

10.8.0

### Node version

16.13.0

### Operating System

Debian 11

**Comment by ZachJW34** [comment]
@pbouamriou could provide a reproduction of this issue using https://github.com/cypress-io/cypress-test-tiny as your template? A bare minimum repro is all I would need so I can see what requests are being made and why the assets found in `index.html` aren't being loaded properly.

**Comment by ZachJW34** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
