### ISSUE TITLE
experimentalWebKitSupport: Error invalid regular expression when using value from imported class.

### ISSUE THREAD

**Issue by BryanEdClark** [cypress-io/cypress#23857]
### Current behavior

1. I launch the playwright safari session using webkit experimental mode.
2. I select a spec that is using an imported string value and attempts to display it in a log statement.
3. Frame loads error before executing any code inside the it statement.

The following error originated from your test code, not from Cypress.

> Invalid regular expression: invalid group specifier name

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

### Desired behavior

The value from the other class should be pulled in and usable.

Note: This is working on Chrome/Firefox/Electron.

### Test code to reproduce

Test Class
--------------------
```
import { TestClass } from '{path to class here}';

it('Test Me.', () => {
  cy.log(TestClass.testValue});
});
```
---------------------
imported class
---------------------
```
export class TestClass {
  static testValue = 'Hello World!';
}
```

### Cypress Version

10.8.0

### Node version

16.3.0

### Operating System

MacOS Catalina - 10.15.7

**Comment by chrisbreiding** [comment]
I'm unable to reproduce this with the given code. I would expect an `Invalid regular expression` error to be tied to a regular expression. Is there a regular expression somewhere in your test code?

**Comment by BryanEdClark** [comment]
@chrisbreiding 
I would also expect that, however from the above code if I do cy.log(TestClass.testValue); (or a cy.get(TestClass.testValue) following page object modal abstracted methodology) it will fail however if I do cy.log('Hello World!'); it will work so I am fairly certain it is with the using the imported value itself.

I have been trying to grab a screenshot of it, however now when attempting to launch playwright browser session from the select browser screen it now gets stuck at about:blank, note it works for other browsers still.

**Comment by BryanEdClark** [comment]
@chrisbreiding Was able to get it working by going from     "playwright-webkit": "1.26.0", to 1.25 will close this ticket.
