### ISSUE TITLE
Excel plugin issue in v10.8

### ISSUE THREAD

**Issue by SushilPatilShj** [cypress-io/cypress#23874]
### Current behavior

When we upgrade from v9.7 to v10.8 there is an issue with excel plugin because in v10.8 there is no plugin folder and also there is no documentation for defining the plugin.
![image](https://user-images.githubusercontent.com/113010465/190982072-2f5935cf-ed61-47c5-9753-71b155b37c09.png)

### Desired behavior

There should be plugin folder inside cypress
![image](https://user-images.githubusercontent.com/113010465/190982740-50a065f4-ff88-4fef-821c-12c589a3af51.png)

### Test code to reproduce
```
const xlsx = require('node-xlsx').default; 
const fs = require('fs'); // for file
const path = require('path'); // for file path
module.exports = (on, config) => {
   on('task', { parseXlsx({ filePath }) 
   { return new Promise((resolve, reject) =>
     { try 
      {
         const jsonData = xlsx.parse(fs.readFileSync(filePath)); 
         resolve(jsonData);
         } catch (e) 
         {
            reject(e);
         } });
       }}); } 

       const readXlsx = require('./read-xlsx')
module.exports = (on, config) => {
   on('task', { 
'readXlsx': readXlsx.read
})
}
```
### Cypress Version

v10.8.0

### Node version

v16.17.0

### Operating System

Windows10

**Comment by admah** [comment]
@SushilPatilShj you're right about v10 removing the plugins file. [Here is the link](https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed) to documentation on that. 

Have you already tried using our v10 migrator? That should take your existing configuration and migrate it correctly.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
