### ISSUE TITLE
cy.get not working correctly with cy.origin

### ISSUE THREAD

**Issue by saldanaj27** [cypress-io/cypress#23886]
### Current behavior

I am attempting to log in to my sample application by federating to okta. I hoped to use cy.origin as it allows for me to visit multiple origins. 
This is the code I have. I visit the sample application and click the button that federates the login to okta.
<img width="500" alt="Screen Shot 2022-09-19 at 4 59 29 PM 1" src="https://user-images.githubusercontent.com/59155089/191115501-75bb017a-f87f-40c8-bb0b-f9d9e4627e1b.png">

From there I just want to grab the element to type in the username, but it doesn't find it. I check the page's body, and I can see that it was found through the cy.get function. I even went further and clicked on the 'get body' row on cypress to see what was there and to see if I can access any of the elements, so I tried to grab just the body, but through the class instead of the element and it throws an error.

<img width="439" alt="Screen Shot 2022-09-19 at 4 48 50 PM" src="https://user-images.githubusercontent.com/59155089/191115894-a53618b9-bdfe-4f06-bd42-a838beadeb43.png">
<img width="711" alt="Screen Shot 2022-09-19 at 4 49 10 PM" src="https://user-images.githubusercontent.com/59155089/191116226-89e0df6f-4741-485f-a311-3e7e3b16910f.png">

I don't know if the redirects from when I press the button to log in through okta affects cy.origin. Any help would be appreciated.

### Desired behavior

Cypress should be able to detect my elements when I use the cy.get function within cy.origin.

### Test code to reproduce

cy.origin("https://*****.okta.com", () => {
            cy.get('body')
            cy.get('[class="auth okta-container"]')
})

### Cypress Version

10.7.0

### Node version

v16.16.0

### Operating System

macOS Monterey 12.5.1

**Comment by chrisbreiding** [comment]
I tried reproducing this using our own Okta and the provided code, but Cypress was able to find the element and didn't error.

Unfortunately, unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

If you can provide an example we can run ourselves to reproduce, it will help us debug and solve this issue.

**Comment by saldanaj27** [comment]
I will try to see if it is possible to share more information for you to replicate this error. Is it possible that the redirects are why I am facing this error and why its not there on your side? Has there been an issue with cy.origin like this that you have come across?

**Comment by mjhenkes** [comment]
@saldanaj27, you could try again with cypress 10.9.0 (releasing today). It includes a fairly significant refactor of cy.origin that has resolved some other redirection problems that resulted in hangs. This might not solve your issue, but it's worth a shot.

**Comment by saldanaj27** [comment]
Hi, so I was able to resolve the issue on my side, but it didn't seem to solve my initial problem. 

I am trying to test a federated login with cypress. Unfortunately, something that has to do with cypress and the Google Chrome issue of the same-site cookies, some cookies being sent through requests are being filtered out. I was hoping using cy.origin would have resolved this issue, but I am getting the same as if I were to attempt logging in through the UI. 

Is there a way to manipulate all cookies being sent to adjust the same site attribute for them to be sent and not filtered out?

Is there any other solution that could help me with this issue? I have had no trouble with other automation frameworks, but we use cypress for all other testing.

**Comment by saldanaj27** [comment]
I was able to rewrite headers using cy.intercept()....thank you for your help regardless

**Comment by idanElitzur** [comment]
Hi @saldanaj27 
can you please post some reference for your solution?

I dealing with similar issue a lot of time.
trying to reach elements in redirected page in external origin (from my app -> google accounts)
also didn't able to do it by v10.9.0
so maybe your solution with the `cy.intercept` will solve my issue as well.
thanks
