### ISSUE TITLE
Property runner does not exist on type Cypress

### ISSUE THREAD

**Issue by AlbertoMontalesi** [cypress-io/cypress#2389]
` Cypress.runner.stop()`

This causes an error in typescript.

**Comment by bahmutov** [comment]
We have not documented internal properties inside `Cypress.runner` object, maybe in the future we will do this when the internal APIs solidify.

![screen shot 2018-08-28 at 12 39 38 pm](https://user-images.githubusercontent.com/2212006/44737264-7a2c5000-aabf-11e8-9ccf-2d756cf184b3.png)

For now, we advise to cast the object as `any` or whatever type you use internally.

**Comment by FaziRaj** [comment]
Hello,
@bahmutov did you get the solution for the Cypress.runner as it always says "Property 'runner' does not exist on type 'Cypress & EventEmitter'.". It doesn't find the property in typescript.

**Comment by wirsalt** [comment]
Hi, I'm also facing this issue since migrating to typescript. I have an idea to move the Cypress.runner.stop to function in another file with .js extension, maybe that'll help. But I'm not yet trying it myself

**Comment by vishalsinghcevo** [comment]
Were you able to make this work? Getting the same issue.

**Comment by LynyrdRoss** [comment]
Hi, it may not work on all scenarios, but I added the following code in my `*.d.ts`

```typescript
declare namespace Cypress {
    interface Cypress {
        runner: any;
    }    
}
```
