### ISSUE TITLE
Cy.visit() is setting Cypress headers automatically

### ISSUE THREAD

**Issue by SrHadeSito** [cypress-io/cypress#23893]
### Current behavior

Hello! 

I have set a custom user.agent for my cypress requests. 

When I launch it from interactive mode, and select Chrome, Electron, Mozilla, everything works fine, and all the requests are overwrited with my own user-agent in the header.

But when I launch it from headless mode, it is working property since it reaches the .visit() and sets a default user-agent
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/10.6.0 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36
```

This is not happening in all cy.visit() calls, so I'm a bit unconcerned, because the behaviour is the same, the difference is the content of the page, but nothing in the code is different from one test to another.

### Desired behavior

Having custom user-agent always launching from headless mode.

### Cypress config

````
export default defineConfig({
  projectId: 'test',
  waitForAnimations: true,
  animationDistanceThreshold: 50,
  pageLoadTimeout: 40000,
  defaultCommandTimeout: 40000,
  requestTimeout: 30000,
  chromeWebSecurity: false,
  watchForFileChanges: true,
  trashAssetsBeforeRuns: true,
  userAgent: 'cypress.user-agent',
  viewportHeight: 800,
  viewportWidth: 1280,
  reporter: 'cypress-multi-reporters',
  reporterOptions: {
    configFile: 'reporter-config.json',
  },
  retries: {
    runMode: 1,
    openMode: 0,
  },
  screenshotsFolder: 'cypress/results/screenshots',
  videosFolder: 'cypress/results/videos',
  e2e: {
    specPattern: 'cypress/e2e/**/*.test.ts',
    setupNodeEvents(on, config) {
      on('task', gmailGetMessagesTask);
      on('task', gmailCheckInboxTask);

      getCompareSnapshotsPlugin(on, config);
      addMatchImageSnapshotPlugin(on, config);

      const file =
        config.env.configFile !== undefined ? config.env.configFile : 'develop';

      return getConfigByFile(file);
    },
  },
});
````

### Cypress Visit Overwrite

````
Cypress.Commands.overwrite('visit', (originalFn, url, options) => {
  options = Cypress.config();

  return originalFn(url, options)
});
````

### Cypress Version

10.6.0

### Node version

v14.20.0

### Operating System

macOS 12.5.1

**Comment by ZachJW34** [comment]
@SrHadeSito would you be able to provide me with a reproduction using https://github.com/cypress-io/cypress-test-tiny? I tried visiting a few urls with
```js
cy.intercept("**", (req) => {
  expect(req.headers["user-agent"]).eq("cypress.user-agent");
});
```

And every request is passing. If you can't could you attach the DEBUG logs? You can do so by running `DEBUG=cypress:* npx cypress run &> logs.txt` and sharing the generated `logs.txt` file

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
