### ISSUE TITLE
allow configuring `forbid-only` in CI

### ISSUE THREAD

**Issue by cdaguerre** [cypress-io/cypress#239]
It would be nice to be able to configure `cypress ci` to fail if there is `it.only` in the specs to prevent successful builds because of accidental undesired commits.

**Comment by jennifer-mann** [comment]
Yes! We definitely intend to allow configuration to always fail in CI when there is an .only. We've discussed it before. 

Thanks for opening the issue.

**Comment by laurencehoess** [comment]
This could help with an issue I just ran into. A single test in one of my specs had .only; when I tried to "Run all specs" from the Cypress interactive test runner, only that one test would run. All the other specs were ignored. I would have thought .only would only influence the tests in that individual spec file.

**Comment by Bkucera** [comment]
@laurencehoess if it helps, we use an npm script for this called `stop-only`: https://github.com/cypress-io/cypress/blob/4bd3cf2c531bdbf1783493e8045c18f09dfc390b/package.json#L43

**Comment by jennifer-shehane** [comment]
This is possible today using outside packages. 

We use [stop-only](https://github.com/bahmutov/stop-only) package set up in a pre-commit hook using [husky](https://www.npmjs.com/package/husky). You can see our specific setup in this project here: https://github.com/cypress-io/cypress/blob/develop/package.json#L225:L225

Closing as this is achievable outside of Cypress and regarded as outside of the scope of the Cypress product itself.

**Comment by Bkucera** [comment]
I think it's worth re-opening this issue, since mocha supports a `forbid-only` option

**Comment by Bkucera** [comment]
and I recommend using https://github.com/lo1tuma/eslint-plugin-mocha and enabling the rule `no-exclusive-tests`:

```js
{
  "plugins": [
    "mocha"
  ],
  "rules": {
    "mocha/no-exclusive-tests": "error"
  },
},

```

**Comment by jennifer-shehane** [comment]
Closing since there are outside tools that provide this functionality. We don’t intend to build this in.
