### ISSUE TITLE
Hyperlink in log when code fails is incorrect

### ISSUE THREAD

**Issue by MassimoLobrutto** [cypress-io/cypress#23917]
### Current behavior

In debugger when a test fails and failing line of code is highlighted the path to the class/code block seems incorrect

![image](https://user-images.githubusercontent.com/81157392/191551084-6bb80907-53a0-423b-8d17-2230d4f0b05a.png)

clicking on this link unsurprisingly does not work as it seems to have too many ../../

### Desired behavior

Link on a failure in log should correctly open class and line of code when clicked on like the way it worked in v9xx of cypress

NB i understand that the source map for this error may be an issue with the bundler i am using @bahmutov/cypress-esbuild-preprocessor which is where i activated the sourcemap flag (sourcemap : inline) that allows the log to show the failing code block

![image](https://user-images.githubusercontent.com/81157392/191551878-d4172770-c981-495b-a22d-19bedcfe2aa4.png)

### Test code to reproduce

https://github.com/MassimoLobrutto/ErrorReproduction

### Cypress Version

10.8.0

### Node version

16.15.0

### Operating System

Windows 11

**Comment by ZachJW34** [comment]
I was able to reproduce this issue using just a simple app with `@bahmutov/cypress-esbuild-preprocessor`. I don't think is an issue on our end though, as the parsed source maps from the served specs contain the `../../../../`. Esbuild has some other source map specific options that might need to be tweaked, like https://esbuild.github.io/api/#sourcefile.

I would open this issue in https://github.com/bahmutov/cypress-esbuild-preprocessor and see what responses you get there.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
