### ISSUE TITLE
CT Stacktraces: Investigate Vite sourcemap mismatches

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#23919]
Sourcemaps generated by Vite are often shifted by 1-3 columns, resulting in misaligned code frames (errors point to incorrect part of line that generated the error). This is worked around in current system tests by providing multiple column mappings to accept (see `reporter-ct-vite.errors.cy.ts`), and at runtime users will sometimes see codeframes that are incorrectly positioned.

Need to investigate whether the sourcemaps themselves are incorrect, or whether we have logic in place that is breaking them due to Webpack-specific behaviors. This typically presents in JS-only files that are not transpiled by Vite (not JSX, TS, etc), so this may indicate an issue with the workaround we've added to `vite-dev-server` to always serve sourcemaps (see `transform` function of `cypress.ts` plugin under `vite-dev-server`)

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23919?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
