### ISSUE TITLE
Firefox 105

### ISSUE THREAD

**Issue by subiczadrian** [cypress-io/cypress#23912]
### Current behavior

Opening cypress tests using Firefox 105 does not work.

### Test code to reproduce

The user interface does not open.

### Cypress Version

10.8.0

### Node version

16.17.0

### Operating System

win10

**Comment by tester-at-bmi** [comment]
Duplicate of the following report #23897

**Comment by ZachJW34** [comment]
Going to close as the issue is a duplicate.
