### ISSUE TITLE
Cypress stops tracking XHR requests

### ISSUE THREAD

**Issue by runeabrahams1** [cypress-io/cypress#2391]
### Current behavior:
Calling `cy.server()` and `cy.route()` inside an `it()`, without calling `cy.visit()`.
This makes Cypress not track and XHR events and makes `cy.route()` useless.

### Desired behavior:
If I already am on the correct page from a previous test, then a new test should track XHR requests if I call `cy.server()` and `cy.route()`.

### Steps to reproduce:
```ts
it("test1, () => {
	cy.server();
    cy.route("POST", "**").as("postR");
    cy.visit("index/admin/status-settings"); //A new page in my Angular app
	cy.wait("@postR") // this tracks XHR reqests as expected
})

it("test2, () => {
	cy.server();
    cy.route("POST", "**").as("postR");
	// this does NOT tracks XHR reqests before I call cy.visit() again to refresh the page.
	// So if I call cy.wait("@postR") it will never complete,
 	// even if the call happens in chrome's "network" page and the app updates as expected
})
```

### Versions
Chrome
Windows 10 (latest)
Cypress: 3.1.0
Angular: 6.1.x

**Comment by minuwi** [comment]
Why do you initialise two times `cy.server()` and alias `postR`? 
Is it the same test? If yes, server and aliases should be instantiate on a before() hook for example...

**Comment by jennifer-shehane** [comment]
Hey @runeabrahams1, Each test - `it()` - runs independently of the other `it()` blocks. So, they do not run with any knowledge of the code ran in the previous `it()` block. 

If you wanted to share some commands across test, I suggest looking into using a [`beforeEach` hook](https://on.cypress.io/writing-and-organizing-tests#Hooks). 

You should probably go through a few of the test in our intro docs too: https://on.cypress.io/introduction-to-cypress
