### ISSUE TITLE
TS2345 error: testIsolation not in cypress.d.ts -> TestConfigOverrides

### ISSUE THREAD

**Issue by rafal-pomocnik-captivateiq** [cypress-io/cypress#23911]
### Current behavior

When trying to use `testIsolation` option in test suite at describe level like mentioned in https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Test-Isolation, typescript check marks it with below error:

`TS2345: Argument of type '{ testIsolation: string; }' is not assignable to parameter of type 'TestConfigOverrides'.   Object literal may only specify known properties, and 'testIsolation' does not exist in type 'TestConfigOverrides'.`

Even though - it is working fine when `testIsolation:'strict'` is added there and it utilizes this function properly.

### Desired behavior

`tsc` using `cypress.d.ts` not complaining about it.

### Test code to reproduce

```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"]
  },
  "include": ["**/*.cy.ts"]
}

// test.cy.ts
describe('test name', { testIsolation: 'strict' }, () => {})
```

### Cypress Version

10.8.0

### Node version

v16.14.0

### Operating System

macOS 12.6

**Comment by ZachJW34** [comment]
Thanks for opening the issue @rafal-pomocnik-captivateiq, I can verify that our types aren't properly reflecting this option. A change will need to be made [here](https://github.com/cypress-io/cypress/blob/3c8114027effc1e8080f8d1b67b85c75cd4a120b/cli/types/cypress.d.ts#L3040) to the `TestConfigOverrides`. Since it is a suite level override, maybe we change up the types such that it does not show up in the test level overrides (`it('should', { ...options }, () => { ... })`).

If you're interested in contributing, we would appreciate a PR!

**Comment by rafal-pomocnik-captivateiq** [comment]
@ZachJW34 both `describe/context` suite level and `it` test level though uses currently `TestConfigOverrides`, to have different interface for both it seems there would be a need for creating `TestSuiteConfigOverride` (extending `TestConfigOverrides`?) with the additional `testIsolation` option (at least) and updating `SuiteFunction/ExclusiveSuiteFunction/PendingSuiteFunction` interfaces with new `TestSuiteConfigOverride` - is that correct?

Or just extend `TestConfigOverrides` with additional `testIsolation` option that will actually work on suite level only, on test level though `tsc` check will accept it, but I guess it will just throw: _CypressError: The \`testIsolation\` configuration can only be overridden from a suite-level override._

**Comment by ZachJW34** [comment]
The latter is the easiest, looks like we don't have a pattern for suite level vs test level but like you said we do throw an error if provided. A simple `Omit<TestConfigOverrides, 'testIsolation'>` would work current pattern is ok for now, but ideally the types should reflect what options are valid

**Comment by rafal-pomocnik-captivateiq** [comment]
Cool, thanks @ZachJW34! I have some code prepared, but it seems I lack perms to push branch to remote - can you advise? 🙏

**Comment by ZachJW34** [comment]
@rafal-pomocnik-captivateiq We have a [contributing guide](https://github.com/cypress-io/cypress/blob/dd61385998eae0cdcc2485c37e16052bf5855d6c/CONTRIBUTING.md#L1) that I would recommend going through. Then, you can fork the repo and contribute a PR from the forked repo.

Glad you're looking to fix it, we appreciate it!
