### ISSUE TITLE
CT Stacktraces: Duplicate reporting of uncaught errors

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#23920]
Component tests improperly report the same uncaught error multiple times - likely caused by differences in architecture between e2e and ct which allows multiple error listeners to process the uncaught error. Logic changes were made to some tests to account for this during CT Stacktrace work (see `.should(mode === 'component' ? 'have.length.gte' : 'have.length', 1)` line of `verify-failures.ts`)

To reproduce, create a component that throws an error from a click listener then invoke that listener via a component test.

![Screen Shot 2022-09-20 at 8.59.59 AM.png](https://images.zenhubusercontent.com/6298d87ac2908848ab6764f3/5065b95b-119a-418a-b403-d9e007836dce
)

**Comment by lmiller1990** [comment]
fixed https://github.com/cypress-io/cypress/pull/23957
