### ISSUE TITLE
playwright-webkit not installable in W10 environment

### ISSUE THREAD

**Issue by PetMou** [cypress-io/cypress#23934]
### Current behavior

Is this Webkit experiment valid for a Windows 10 environment? I can't find a way to get the Webkit that the plugin tries to download.

### Test code to reproduce

At installing ine playwright-webkit, it tries to download Webkit 16.0. This gives a 'Socket is closed' error.
So I wonder if this is perhaps only working in a Mac or Linux environment

### Cypress Version

10.8.0

### Node version

16.15.1

### Operating System

Windows 10

**Comment by ZachJW34** [comment]
I was able to launch and run some Cypress tests on my Windows 10 machine using webkit 🤯.

Is the problem occurring when you try to download playwright-webkit e.g. when you run `npm i -D playwright-webkit` or is it happening when you try and launch the browser with Cypress? If it's the latter, providing some DEBUG logs would be valuable so I can try and find out what's going on.

**Comment by PetMou** [comment]
Sorry for the inconveniance. I found out it seems to be some nexus firewall setting.
