### ISSUE TITLE
Unable to login into salesforce 23 using session id

### ISSUE THREAD

**Issue by jpatil14** [cypress-io/cypress#23958]
### Current behavior

Until the salesforce 23 release which released around a month back, cypress was able to login into salesforce through soap request. However after salesforce 23 release, cypress is unable to log into salesforce which i believe is global issue as others too are facing it.

Below are the steps : 
1. soap request payload as 

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:partner.soap.sforce.com">  
     <soapenv:Body>  
        <urn:login>  
            <urn:username>username@example.com</urn:username>  
            <urn:password><<password>><<session_id>></urn:password>  
         </urn:login>  
     </soapenv:Body>  
</soapenv:Envelope> 
```

2. Then passing above payload as request to log into SF as below,

```javascript
Cypress.Commands.add("loginAsTestUser", () => {
  cy.readFile("soapRequestBodyTestUser.xml").then(
    (requestBody) => {
      cy.request({
        method: "POST",
        url: "https://test.salesforce.com/services/Soap/u/35.0",
        headers: {
          SOAPAction: "abc",
          ["Content-Type"]: "text/xml"
        },
        body: requestBody
      }).then((response) => {
        const sessionID = Cypress.$(response.body).find("sessionId").text();
        cy.visit("https://xxx--qa.sandbox.lightning.force.com/secur/frontdoor.jsp?sid="+sessionID);
      });
     }
  );
});
```

3. After calling above command in cypress runner, cypress is unable to move ahead of salesforce 23 logo
![cy_1](https://user-images.githubusercontent.com/31123657/205647593-5a37bf0d-a82c-4b79-b04b-54fb95ddfaba.png)

4. Also we could see below exception in cypress logs which was not there before salesforce 23 release,
![image](https://user-images.githubusercontent.com/31123657/191906738-faffc01e-4bfe-4d05-a50f-036a73bc3de4.png)

### Test code to reproduce

**SOAP request payload as** 

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:partner.soap.sforce.com">  
   <soapenv:Body>  
  <urn:login>  
      <urn:username><<salesforce_username>></urn:username>  
      <urn:password><<password>><<session_id>></urn:password>  
      </urn:login>  
   </soapenv:Body>  
</soapenv:Envelope>  
```

**Then passing above payload as request to log into SF as below,**

```javascript
Cypress.Commands.add("loginAsTestUser", () => {
  cy.readFile("soapRequestBodyTestUser.xml").then(
    (requestBody) => {
      cy.request({
        method: "POST",
        url: "https://test.salesforce.com/services/Soap/u/35.0",
        headers: {
          SOAPAction: "abc",
          ["Content-Type"]: "text/xml"
        },
        body: requestBody
      }).then((response) => {
        const sessionID = Cypress.$(response.body).find("sessionId").text();
        cy.visit("https://xxx--qa.sandbox.lightning.force.com/secur/frontdoor.jsp?sid="+sessionID);
      });
     }
  );
});
```

3. After calling above command in cypress runner, cypress is unable to move ahead of salesforce 23 logo
![cy_1](https://user-images.githubusercontent.com/31123657/205647694-8f7cdea2-bc09-4689-a7f3-410473ad3d97.png)

4. Also we could see below exception in cypress logs which was not there before salesforce 23 release,
![image](https://user-images.githubusercontent.com/31123657/191906738-faffc01e-4bfe-4d05-a50f-036a73bc3de4.png)

### Cypress Version

10.8.0

### Node version

v14.20.0

### Operating System

Windows 10 Enterprise

**Comment by Rogeriohsjr** [comment]
I am having the same issue.
This affects only Winter 23 so far. Summer 22 is working fine.

If you guys need an org to test please let me know I can send the credentials so you can test. You can also create your own org since that doesn't require any subscription. If you use the link below you have to change the code that jpatil4 provided to use the login.salesforce instead of test.salesforce. You will also need to reset the Security Token.

https://www.salesforce.com//form/signup/prerelease-winter23


Things that I try:
- Set the chromeWebSecurity to false
- Set the experimentalSessionAndOrigin to true and try to use origin.

These are the last things I see in the Browser Console with the Debug on.

![image](https://user-images.githubusercontent.com/3171587/192172629-35da0e8b-0707-49d3-a857-2fd4b1e37f80.png)

Let me know if you need anything I will be happy to help.
Thank you in advanced!

**Comment by astone123** [comment]
@jpatil14 @Rogeriohsjr are either of you able to log into Winter '23 using the SOAP API outside of a Cypress context? Wondering if this is an issue with Cypress specifically or a separate API issue

**Comment by astone123** [comment]
@jpatil14 @Rogeriohsjr another thing to try could be to enable the `experimentalModifyObstructiveThirdPartyCode` experiment and see if that helps

**Comment by Rogeriohsjr** [comment]
Hey @astone123 , 

1. SOAP api is used only to get the SessionId. I added a cy.log to display the session Id that we were generating through SOAP using Cypress, then I access the URL in the browser in the same way that Cypress access, like: 
https://test-mydomain-dev-ed.lightning.force.com/secur/frontdoor.jsp?sid=SessionIdFromLog
1.1. I could access Salesforce with no issue.
1.2. Cypress using the same SessionId and accessing the same URL, still not loading.

2. I enabled the experimentalModifyObstructiveThirdPartyCode into e2e cypress.config.js and still not working.

3. I created this project with very basic structure to access Salesforce, not sure if it helps. I added a config there to use SOAP or use straight the SessionId as well. Both approach works on Summer 22 but fails on Winter 23.
https://github.com/Rogeriohsjr/cypress-salesforce

Let me know if you need any help.
Thanks again for looking into this.

**Comment by astone123** [comment]
@Rogeriohsjr thanks so much for the test project! I was able to reproduce the issue with that. Going to route this to one of our internal teams to take a look at

**Comment by jpatil14** [comment]
Many thanks @Rogeriohsjr for supporting out here. Hope this issue gets resolved soon

**Comment by jpatil14** [comment]
@astone123 @cypress-app-bot Is there any update on this? This has been a blocker for us since last couple of months. If this is something cant be resolved do let us know so that we can switch to other tool? Kindly respond ASAP

**Comment by Aditya-AT** [comment]
@jpatil14 I am facing similar issue with the login, even I am using SOAP API for getting the session id, the issue seems to be due to multiple redirects (not sure about it), but has anyone found a fix/workaround for it?

**Comment by poponuts** [comment]
This is a blocker for most Salesforce tests. Once Salesforce roll out the latest Winter 23 across all environments then everyone using Cypress for Salesforce tests will be failing. Can the Cypress team prioritise this? Thanks.

**Comment by AtofStryker** [comment]
Hey all. We appreciate your patience on getting this issue resolved. I dropped a comment on https://github.com/cypress-io/cypress/issues/24290#issuecomment-1376214221 that should resolve this issue with a new experimental flag in Cypress `12.4.0`!

**Comment by jpatil14** [comment]
@AtofStryker thats great. any timeline on 12.4.0 release?

**Comment by AtofStryker** [comment]
@jpatil14 `12.4.0` should be released in a week on January 17th, 2023.

**Comment by jpatil14** [comment]
> @jpatil14 `12.4.0` should be released in a week on January 17th, 2023.

Hi, Any update on the release?

**Comment by AtofStryker** [comment]
Hi @jpatil14! Sorry for missing to update the thread here but we needed to postpone the `12.4.0` release until next Tuesday. I dropped an update on the main investigation issue [here](https://github.com/cypress-io/cypress/issues/24290#issuecomment-1387685333). I do not expect any other delays and next Tuesday should be good to go!
