### ISSUE TITLE
Spike: Automate nightly builds against supported frameworks

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#23951]
Automating builds to run against the latest versions of frameworks we support, including pre-release builds when available, can help us stay ahead of breaking changes.

Goals of the spike:
- Determine how we can automate builds against newest versions of the frameworks and dev servers we support. 
- Can we utilize free build minutes via GitHub actions?
- Are there regular maintenance activities that will need to take place? For example: Do we need to make a new project for every new major version of a framework
- Can we utilize the [Component Testing Examples Repo](https://github.com/cypress-io/cypress-component-testing-apps) as our test bed

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23951?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
Without a description I'm not sure what the right size for the spike is.

**Comment by warrensplayer** [comment]
@rockindahizzy Following what Mark commented, is this spike meant to actually setup the automated builds or to research and document what is needed?  More detail would be helpful to estimate.
