### ISSUE TITLE
Support using vue-remote-devtools within Cypress

### ISSUE THREAD

**Issue by alukos** [cypress-io/cypress#2396]
I try to use [Remote Vue DevTools](https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md) with Cypress.

When add `<script src="http://localhost:8098"></script>` in `index.html` as [nothingismagick suggests](https://github.com/cypress-io/cypress/issues/1742#issuecomment-393561644) **its work**, but then need to delete each time for production

When try add in spec `Cypress.on("window:before:load" ... ` as [brian-mann suggests](https://github.com/cypress-io/cypress/issues/1742#issuecomment-393597609) I get an error `body null`, when try add on `win.onload`:

```js
Cypress.on("window:before:load", win => {
  win.onload = () => {
    const script = win.document.createElement("script");
    script.src = "http://localhost:8098";
    win.document.body.appendChild(script);
  };
});
```

or

```js
    cy.visit('/', {
      onBeforeLoad: win => {
        win.onload = () => {
          const script = win.document.createElement('script');
          script.src = 'http://192.168.55.103:8098';
          win.document.body.appendChild(script);
        };
      },
    });
````
Vue DevTools are connected but the Vue components are not displayed

**Comment by jennifer-shehane** [comment]
I know this also may not be ideal, but I have a check within our web apps for `window.Cypress` - you could try adding the script only when `window.Cypress` is defined and it would only be inserted during testing.
