### ISSUE TITLE
Left side panel logs disappers after entering username 

### ISSUE THREAD

**Issue by TannyaT** [cypress-io/cypress#23972]
### Current behavior

Left side log panel opens when I open cypress, it shows log for few minutes. Then I enter username and new page is loaded for password field..left side panel dissapears.
Also , password field locator is not getting selected in new window.

### Desired behavior

Left side log should show all the time.
selectors should select the desired field and perform actions as written in code.

### Test code to reproduce

Steps to reproduce:
.ts file
```ts
import LandingPageSelectors from "../Selectors/LandingPageSelectors";

class LandingPage{

  LandingPageFS() {
    const email = Cypress.env('user');
    const pwd = Cypress.env('password');
    cy.visit('https://dev-baass.cat.com/#/fieldservice');
    cy.wait(10000);
    cy.get(LandingPageSelectors.signin).type('tomart',{force:true});
    cy.wait(10000);
    cy.get(LandingPageSelectors.nextbutton).click({force:true});
    cy.wait(10000);
    cy.get(LandingPageSelectors.password).type('admin123', {log: false});
    cy.wait(10000);
  }
}
```

.spec.ts
```ts
describe("Validate Landing pages" , () => {

  const LP = new LandingPage();


  it('LandingPage  FS',function(){
    LP.LandingPageFS();
  });
})
```

### Cypress Version

9.5.4

### Node version

14.17.3

### Operating System

windows 10

### Other

<img width="782" alt="login password" src="https://user-images.githubusercontent.com/114337520/192138866-fb847d64-f35d-4afc-9da3-5caf4ca33043.png">

**Comment by ZachJW34** [comment]
There is a very similar issue [here](https://github.com/cypress-io/cypress/issues/21307). We have a fix for this redirect behavior but you'll need to upgrade to Cypress >= 10.4.0. Going to close this as a duplicate, if there is anything that warrants re-opening this issue feel free to comment here and we'll take another look.
