### ISSUE TITLE
cy.wait() always gives a timeout error for ajax url call in cypress version 9+ : No request ever occurred.

### ISSUE THREAD

**Issue by shwetabodkhe** [cypress-io/cypress#23998]
### Current behavior

 I am always getting an error: 
"Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'create'. No request ever occurred".

The same code is working fine in cypress version 6.0.0 but in version 9+ its giving an error.....
Could you please help me with the issue?

### Desired behavior

if the code is working fine in version 6 then it should work fine in version 9+.

### Test code to reproduce

Code:
```
URL = 'account/ajaxgetaccounts'
cy.intercept(URL).as(GET_ACCOUNTS_ALIAS)
cy.wait(@GET_ACCOUNTS_ALIAS)
```
See screenshot
<img width="883" alt="Screenshot 2022-09-27 at 16 36 34" src="https://user-images.githubusercontent.com/42741583/192560511-d01236e6-2081-42ee-84a1-4aeec2cbd22e.png">

### Cypress Version

9.6.0

### Node version

16.13.0

### Operating System

12.0.2

**Comment by astone123** [comment]
Hey @shwetabodkhe, could you please provide a repository where the issue can be reproduced? What is triggering the network request to happen? Do you see the network request in the browser network tab?

**Comment by shwetabodkhe** [comment]
Hello @astone123 ,

Yes I can see the request in Network tab of browser. I am searching for any customer by entering the customer number and then the network request is being called to get the account of customer.
But cy.wait(@GET_ACCOUNTS_ALIAS) is not recognising the request so giving error at the end.

The same code is working fine when I am using cypress version 6. Is there anything needs to be done for intercepting ajax call in cypress version 9+?

I cannot share the repository, sorry for that.
Let me know if you need anything else.

**Comment by shwetabodkhe** [comment]
Issue is resolved by adding `"*"` at the end of URL .
old URL = `'account/ajaxgetaccounts'`
Working solution URL = `'account/ajaxgetaccounts*'`
