### ISSUE TITLE
passing in undefined to cy.contains() throws TypeError

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#24]
If a value of `undefined` is passed into `cy.contains()`, result is `TypeError: Cannot read property 'toString' of undefined`

Also, this results in the `contains` command being printed twice in the commands UI.

**Example**
```js
cy.contains(undefined)
```

*Result*
![screen shot 2015-04-16 at 2 45 37 pm](https://cloud.githubusercontent.com/assets/1271364/7188694/acdf61c8-e447-11e4-84b2-118c2a3074fc.png)

**Comment by brian-mann** [comment]
Fixed in `0.5.3`. [Changelog](https://github.com/cypress-io/cypress/wiki/Changelog#053-04192015)
