### ISSUE TITLE
Add cloud recommendation message to CI output

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#24000]
[ClickUp](https://app.clickup.com/t/18033298/PM-2552)

Add the following message to the CI output for `cypress run`:
```bash
-----------------------------------------------------------------------------------------

Having trouble debugging your CI failures?
Record your runs to the Cypress Cloud to watch video recordings for each test, debug failing and flaky tests, and integrate with your favorite tools.

>> https://on.cypress.io/cloud-get-started

------------------------------------------------------------------------------------------
```
This message should show after the test summary (in place of the recorded run link) in run mode if the following conditions are met:
- we are in run mode
- the run is **not** being recorded to the dashboard
- we are running in CI
- at least one test failed during the run
- `CYPRESS_NO_COMMERCIAL_RECOMMENDATIONS` environment variable is not set to `true` (users can opt out of seeing this message by setting this true)

**Comment by warrensplayer** [comment]
@astone123 I see suggestions in the click-up, but have the requirements for how to determine if it is running in CI been determined?

**Comment by astone123** [comment]
@warrensplayer we should be able to look at `process.env.CI` to determine whether the process is running in CI

**Comment by rockindahizzy** [comment]
Voting under the assumption that `process.env.CI` is the only indicator we plan to go off of for this issue.
