### ISSUE TITLE
testIsolation won't work

### ISSUE THREAD

**Issue by Michel73** [cypress-io/cypress#24014]
### Current behavior

I set the flag `testIsolation: 'legacy'`to suppress clearing the page after each test. But it doesn't have any effect. The page is cleared despise setting the flag. 
![image](https://user-images.githubusercontent.com/6614299/192760834-634c95ca-10c4-4d15-ba57-c7bed22d921b.png)

### Desired behavior

If the flag `testIsolation: 'legacy'`is set, then clearing the page before each test must be disabled.

### Test code to reproduce

I tried it as option in describe block:
```typescript
  describe('test',  {testIsolation: 'legacy'}, () => {...
```
and also as option in cypress.config.ts
```typescript
  e2e: {
    experimentalSessionAndOrigin: true,
    testIsolation: 'legacy'
  }
```
Within commands.ts we have a login function that uses the session like so:
```typescript
  cy.session([username, password], () => {
  cy.visit('/', {
    // ... login code here
  }
});
```
In spec files we do this login in `beforeEach` to restore the session and cookies as described here: https://docs.cypress.io/api/commands/session

### Cypress Version

10.9.0

### Node version

v16.16.0

### Operating System

macOS 12.5

**Comment by emilyrohrbough** [comment]
@Michel73 `testIsolation=legacy` removes the clear page that happens before each test. . It does not impact the behaviors of the `cy.session()` command.

When `testIsolation=strict` and the page is cleared before a test, we do not generate a log for this so  it won't be obvious when reviewing the logs in the reporter. We did not to generate a log because we don't log when aliases, intercepts, clock, mocks, etc are reset before the test and part of the Cypress behavior. It is possible it's something we should consider adding to make this clearer

**Comment by emilyrohrbough** [comment]
The reason the `cy.session()` command is clearing the page and the local storage, session storage, and cookies is to ensure you will always create or restore the same session data when your tests run - whether it is the first test run, a rerun or if the test failed and was retried due to another command failing in the test.

**Comment by Michel73** [comment]
@emilyrohrbough This seems inconsistent to me. I want to reduce the set-up time when loading my application. After logging in when the page first loads, many other things are loaded. So if the session is restored to speed up the login process and then a blank page is displayed, we have achieved almost nothing because we have to go back to the page that comes after the login and so the whole app-init process is gone through again.
So if `testIsolation: 'legacy'`is set, there shouldn't be clearing the page when session is restored.

**Comment by emilyrohrbough** [comment]
@Michel73 You aren't the first person to share you thoughts on who `cy.session()` should behave in relation to test isolation.
 
The reason `cy.session()` has it's own command-level behaviors that clear the page/session data is to ensure the command behaves consistently and to act as guards to potentially unexpected behaviors that could occur when the session applies. For example: when the session is applied, there is a chance the data populated on the browser is out-of-sync with the data sent/authorized by the server that would have been sync'd with the new page load. 

Based on multiple users feedback (and now your!) around this undesired behavior, I am in the process of syncing with our Product Team to determine what we might be able to offer users to give them the safest command behavior and/or an option remove this command-level isolation. At this time I can't say for sure if this is work will be willing to support, but it is a conversation that is happening.

**Comment by Michel73** [comment]
So in conjunction with using `cy.session()` for a login function, I can't see the point of the `legacy` setting.
The approach of dogmatically enforcing test isolation seems a bit overambitious to me. It clashes with the pattern of "separation of concerns" and "fast feedback". Suppose we want to test a page that is fully loaded. To test all the things the page represents, I don't want to write a huge "it" block. I like to write as small blocks as possible. But if it's forced to recreate the session and clear the page before every test, we don't have quick feedback on whether our app is working because we have to reload the app incredibly often. It should be left to the developer to decide whether the isolation of tests should be done so dogmatically  or on which parts (describe-blocks) makes it sense or not.
Those are just my thoughts.

**Comment by romankhomitskyi** [comment]
> So in conjunction with using `cy.session()` for a login function, I can't see the point of the `legacy` setting. The approach of dogmatically enforcing test isolation seems a bit overambitious to me. It clashes with the pattern of "separation of concerns" and "fast feedback". Suppose we want to test a page that is fully loaded. To test all the things the page represents, I don't want to write a huge "it" block. I like to write as small blocks as possible. But if it's forced to recreate the session and clear the page before every test, we don't have quick feedback on whether our app is working because we have to reload the app incredibly often. It should be left to the developer to decide whether the isolation of tests should be done so dogmatically or on which parts (describe-blocks) makes it sense or not. Those are just my thoughts.

Agree
