### ISSUE TITLE
experimentalWebkitSupport: System module not supported

### ISSUE THREAD

**Issue by KaterinaDimogiorgi** [cypress-io/cypress#24018]
### Current behavior

Cypress specs fail to be executed because System module is not supported by playwright-webkit. 
The error propagated in browser console is: `ReferenceError: Can't find variable: System`

### Test code to reproduce

ReferenceError: Can't find variable: System

### Cypress Version

10.8

### Node version

14.17.6

### Operating System

macOS 12.6

**Comment by astone123** [comment]
@KaterinaDimogiorgi could you link to some documentation about this `System` module? When I try to call it in Safari I see the same error. Is it supposed to be supported in Safari?

**Comment by KaterinaDimogiorgi** [comment]
@astone123 https://www.npmjs.com/package/systemjs

**Comment by KaterinaDimogiorgi** [comment]
@astone123 according to the above documentation, maybe **SystemJS Babel Extension** (https://github.com/systemjs/systemjs-babel) is required? 
Alternatively, **systemjs-webpack-interop** package might be required in order to dynamically set the webpack public path based on the URL that a SystemJS module was downloaded from (https://www.npmjs.com/package/systemjs-webpack-interop).

**Comment by astone123** [comment]
@KaterinaDimogiorgi can you try those options and see if they work? If not, please re-open this issue. Thanks
