### ISSUE TITLE
When entering text into form using .type(typedText) where typedText is a constant the value changes from the original text

### ISSUE THREAD

**Issue by anealbening** [cypress-io/cypress#24035]
### Current behavior

When entering text into form (email address) using .type(typedText) where typedText is a constant the value changes from the original value so the test fails. The screenshot of the code is below (the filename is testing.spec.js).

![Screenshot 2022-09-29 at 12 57 02](https://user-images.githubusercontent.com/6642705/193025223-2a4ca381-d1cc-4393-a56a-b633efa98e2b.png)

The photo of the issue is here:

![Screenshot 2022-09-29 at 12 57 41](https://user-images.githubusercontent.com/6642705/193025322-ec129913-c54b-470b-b375-951edf7c6360.png)

As you can see it inputs a different value to my stated value. Strangely when the test is first run it passes but subsequent runs result in failure as the input value has changed.

### Desired behavior

In this situation, Cypress should input the email address entered in the typedText field and it should pass as the values match.

### Test code to reproduce

![Screenshot 2022-09-29 at 12 57 02](https://user-images.githubusercontent.com/6642705/193025367-75f02ba5-7505-4a9b-9a41-39800939527f.png)

Sorry couldn't copy and paste code in as it was incorrectly formatting it.

### Cypress Version

3.5.0

### Node version

v6.14.3

### Operating System

macOS 11.6

**Comment by mjhenkes** [comment]
The sample test succeeded for me.



![Image](https://user-images.githubusercontent.com/1588747/193643271-265f82ba-fab4-4259-8586-acbdbc122c8f.png)



```javascript
describe('Input form', () => {
  it('focuses on load', () => {
    cy.visit('https://black-glacier-04bf38603.1.azurestaticapps.net/')

    cy.focused()
    .should('have.class', 'form-control')
  })

  it.only('accepts input', () => {
    const typedText = 'anealbening@hotmail.com'

    cy.visit('https://black-glacier-04bf38603.1.azurestaticapps.net/')

    cy.get('.form-control')
    .type(typedText)
    .should('have.value', typedText)
  })
})
```

**Comment by anealbening** [comment]
Hi - I can confirm the issue did occur for me but it would often need to be run a few times before noticing the issue (i.e it doesn't have the issue on the first execution of the code but does subsequently).

**Comment by mjhenkes** [comment]
@anealbening, unfortunately after trying a couple of times i haven't been able to recreate the behaviour. Perhaps your running on a slower machine and some sort of focus issue on the site is dropping characters? have you tried introducing a wait before you start typing to ensure the page is done loading?
