### ISSUE TITLE
Add option to remove command-level isolation from cy.session()

### ISSUE THREAD

**Issue by rkhomi** [cypress-io/cypress#24033]
### What would you like?

I would like to have the possibility to cache session across tests to speed up things

### Why is this needed?

Consider this example, we have simple crawler test suite, I just wanna go over sidebar and navigate to a bunch of pages and just check page title

To have this more readable I split it into several it's() to have nice report and know exactly where the page title was changed

```
Cypress.addCommand('login', () => {
  cy.session('authenticatedUser', () => {
     cy.visit('/login')
     cy.get('username').type('user', { log: false })
     cy.get('password').type('password', { log: false })
     cy.get('submit').click()
}, {
  validate: () => {
      cy.visit('/home')
      cy.contains('Welcome User')
      cy.window().then((win) => {
        expect(win.localStorage.length).to.eq(2)
     })
  }),
})


before(() => {
 cy.login()
})

it('test page 1', () => {
  sidebar.goToPage(1)
  cy.contains(Page 1)
})

it('test page 2', () => {
  sidebar.goToPage(2)
  cy.contains(Page 2)
})

it('test page 3', () => {
  sidebar.goToPage(3)
  cy.contains(Page 3)
})

it('test page 3', () => {
  sidebar.goToPage(3)
  cy.contains(Page 3)
})
```

but this won't work since each sidebar click changes the url
However this test suite is independent as possible,
So cy.session makes me change spec file like this

```
before(() => {
 cy.login()
})

it('Check pages', () => {
  sidebar.goToPage(1)
 cy.contains(Page 1)

  sidebar.goToPage(2)
 cy.contains(Page 2)
 
 sidebar.goToPage(3)
 cy.contains(Page 3)
 
 sidebar.goToPage(4)
 cy.contains(Page 4)
})
```

I also do not want to use  login in beforeEach hook because  it will make this test suite slower))
It makes no sense to use log in in beforeEach in this case

I mean, why do I have to use login request and cy.visit(/) when it takes let's say 5 seconds every time, if I could end entire test suite in 5 seconds?

**Comment by nagash77** [comment]
@rkhomi Check out our latest release [10.9.0](https://docs.cypress.io/guides/references/changelog#10-9-0).  This functionality was just added!

**Comment by romankhomitskyi** [comment]
> @rkhomi Check out our latest release [10.9.0](https://docs.cypress.io/guides/references/changelog#10-9-0). This functionality was just added!

I meant across it() not specs

**Comment by romankhomitskyi** [comment]
@nagash77 I create different users in each spec, so I don't think that it will work in my case

**Comment by emilyrohrbough** [comment]
@nagash77 This topic has been brought up on our experimental feedback discussion: https://github.com/cypress-io/cypress/discussions/17887#discussioncomment-2835987

Re-opening & routing. As mentioned here (as @romankhomitskyi has found), based on multiple users feedback around this undesired behavior, I am in the process of syncing with our Product Team to determine what we might be able to offer users to give them the safest command behavior and/or an option remove this command-level isolation. At this time I can't say for sure if this is work will be willing to support, but it is a conversation that is happening.

**Comment by romankhomitskyi** [comment]
> @nagash77 This topic has been brought up on our experimental feedback discussion: [#17887 (comment)](https://github.com/cypress-io/cypress/discussions/17887#discussioncomment-2835987)
> 
> Re-opening & routing. As mentioned here (as @romankhomitskyi has found), based on multiple users feedback around this undesired behavior, I am in the process of syncing with our Product Team to determine what we might be able to offer users to give them the safest command behavior and/or an option remove this command-level isolation. At this time I can't say for sure if this is work will be willing to support, but it is a conversation that is happening.

Thanks for feedback

**Comment by emilyrohrbough** [comment]
@rkhomi / @romankhomitskyi We have taken this feedback and as at team we evaluated the test isolation behavior and found it wasn't behaving how users expected and have made adjustments.

In [Cypress 10.11.0](https://docs.cypress.io/guides/references/changelog#10-11-0), the way that Cypress handles [test isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation) changed. The previous modes of `legacy` and `strict` have been replaced with on and off. Now,
- The default mode is on when [experimentalSessionAndOrigin](https://docs.cypress.io/guides/references/experiments) is enabled.
- The [cy.session()](https://docs.cypress.io/api/commands/session) command now inherits the test isolation behavior for the suite it runs in.

To accomplished the example provided in this issue, you will need to set `testIsolation="off"` in the suite or in the root-level configuration. Be understand there are risks with turning `testIsolation="off"` and it will be on you to ensure your browser context maintain a clean slate for independent tests.

I am closing this issue. Please feel free to open a new issue if you experience other issues with cy.session() and/or test isolation in Cypress.
