### ISSUE TITLE
Getting (uncaught exception)TypeError: Cannot read properties of undefined (reading 'guided tours') while launching ServiceNow url

### ISSUE THREAD

**Issue by shalinirakesh** [cypress-io/cypress#24031]
### Current behavior

I am getting the below error while launching service now url.Please find the screenshot attached:
I have tried the below workarounds but nothing worked.

1. I am using cypress version 10.4.0 currently.I have tried older version like 9.5.0 and 8.5.0 and i am getting the same error in older versions too.
2. Added the below code to e2e.js file.
Cypress.on('uncaught:exception', (err, runnable) => {
    return false
})
**Browser used:**Electron and chromium
**cypress version:**10.4.0,9.5.0,8.5.0
**Error Message:**
(uncaught exception) TypeError: Cannot read properties of undefined (reading 'guided [tours')
![Screenshot 2022-09-27 at 5 38 (1)](https://user-images.githubusercontent.com/25221923/192958917-e2b4bea4-ad7d-4f20-8400-82a3e6c3b8ab.png)

### Desired behavior

Login page should get loaded and username and password input fields should be visible

### Test code to reproduce

Launch service now url

### Cypress Version

10.4.0

### Node version

v16.16.0

### Operating System

macOS11.6.8

**Comment by astone123** [comment]
@shalinirakesh it looks like this error is being thrown inside of the application that you are testing. I don't see anywhere in the Cypress codebase where we read a property called `guided_tours`. The error needs to be fixed within the application that is being tested.

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
