### ISSUE TITLE
Angular Component Testing: providing of transitive dependencies fails

### ISSUE THREAD

**Issue by rainerhahnekamp** [cypress-io/cypress#24047]
### Current behavior

If I use a service in a component that has a dependency to `HttpClient` and I provide the `HttpClient`, the mounting fails.

The error message is 
````
NullInjectorError
...
NullInjectorError: No provider for HttpClient!
````

If the component under test depends directly on the `HttpClient` and I provide the `HttpClient`, the mounting works.

### Desired behavior

Providing of transitive dependencies should work.

### Test code to reproduce

https://github.com/rainerhahnekamp/cypress-component-angular

```typescript
@Component({
  template: '',
})
class NonTransitiveServicesComponent {
  constructor(private httpClient: HttpClient) {}
}

@Injectable({ providedIn: 'root' })
class LoaderService {
  constructor(private httpClient: HttpClient) {}
}

@Component({
  template: '',
})
class TransitiveServicesComponent {
  constructor(private loaderService: LoaderService) {}
}

describe('Component Testing', () => {
  it('succeeds to mount', () => {
    cy.mount(NonTransitiveServicesComponent, {
      providers: [{ provide: HttpClient, useValue: null }],
    });
  });

  it('fails to mount', () => {
    cy.mount(TransitiveServicesComponent, {
      providers: [{ provide: HttpClient, useValue: null }],
    });
  });
});

```

### Cypress Version

10.9.0

### Node version

16.15.0

### Operating System

Windows 11 Professional

**Comment by astone123** [comment]
@rainerhahnekamp thanks for the detailed issue. This is a known issue with Angular CT, see the discussion on #23427. For the time being, you can work around this by doing something similar to what is mentioned in [this comment](https://github.com/cypress-io/cypress/issues/23427#issuecomment-1228680459).

**Comment by yjaaidi** [comment]
I totally agree with Rainer!

I think that I mislead us with this issue https://github.com/jordanpowell88/angular-ct/issues/37

We actually need both: providers and componentProviders

This will be a breaking change so it might be better to do it while we're in the early stage.

What do you think?
cc. @astone123 @jordanpowell88
