### ISSUE TITLE
Utilize Firefox user profile WebDriverBiDi.json to read the host and port for Cypress to connect to

### ISSUE THREAD

**Issue by cgraham-rs** [cypress-io/cypress#24059]
### What would you like?

As documented in [#23897](https://github.com/cypress-io/cypress/issues/23897) Cypress cannot currently connect to Firefox 105. Mozilla has proposed changes to enable Cypress to successfully connect to the right host and port.

Per Mozilla:

> Henrik Skupin: Over on [bug 1792875](https://bugzilla.mozilla.org/show_bug.cgi?id=1792875) I'm working on a patch to store the WebSocket connection details in the Firefox user profile as WebDriverBiDi.json. Maybe this could be a way for Cypress to read the host and port and connect to the right address.

Related tickets:
Original Cypress bug report: https://github.com/cypress-io/cypress/issues/23897
Related Mozilla bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1792088
Mozilla ticket exposing connection details in WebDriverBiDi.json: https://bugzilla.mozilla.org/show_bug.cgi?id=1792875
Cypress feature request to try additional hosts to connect to Firefox: https://github.com/cypress-io/cypress/issues/24058

### Why is this needed?

Cypress cannot connect to Firefox 105

**Comment by nagash77** [comment]
@cgraham-rs Thanks for the update.  Can you please add these updates to that ticket so that everyone can follow along in the same place?  I am going to close this issue so people are all funneled into the same area when looking for updates on this issue.  Thank you.
