### ISSUE TITLE
.select() on form

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#2405]
hi guys,

How Can I select the value "Afrique du Sud" on this kind of div.

```html
<div class="form-validate form-validate--inline">
	<label>Destination*</label>
	<select class="form-control" data-val="true" data-val-required="Veuillez renseigner la destination" id="GroupQuotationDestinations" name="SelectedDestination">
		<option value="">Destination</option>
		<option value="ZAF|AF">Afrique du Sud</option>
		<option value="ARG|NA">Argentine</option>
		<option value="AUS|OC">Australie</option>
	</select>
	<span class="field-validation-valid" data-valmsg-for="SelectedDestination" data-valmsg-replace="true"></span>
</div>
```

Best regards.

**Comment by jennifer-shehane** [comment]
Hi @mandriao84, we recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Issues in our GitHub repo are reserved for potential bugs or feature requests. We want our team to spend all the time we have building a better product and hope you understand. ☺️
