### ISSUE TITLE
Jira details missing from dashboard

### ISSUE THREAD

**Issue by jehoffm** [cypress-io/cypress#24057]
### Current behavior

The test result section of the dashboard indicates that there is an associated Jira, but the detail view on the right column doesn't show the Jira info anymore
![2022-09-30_7-50-14](https://user-images.githubusercontent.com/39063542/193273937-e68cc0f1-32ca-4969-87ac-5a1806bb3a46.png)

### Desired behavior

We were able to see the Jira details

### Test code to reproduce

Dashboard

### Cypress Version

10.7

### Node version

v16.15.1

### Operating System

Windows

**Comment by nagash77** [comment]
Hello @jehoffm , I'm sorry to hear you are having issues with the Dashboard.  I have forwarded this request to our support staff who will follow up with you shortly.

**Comment by conversayShawn** [comment]
Moving this to the support queue.

**Comment by conversayShawn** [comment]
This issue has been resolved after completely uninstalling the Cypress integration (including the permissions in Atlassian) and re-installing it.
