### ISSUE TITLE
Cypress browser is crashing frequently during the execution

### ISSUE THREAD

**Issue by vasanthiraman** [cypress-io/cypress#24053]
### Current behavior

Cypress browser is crashing frequently during the execution, it becomes a blank screen suddenly and we need to close the browser window and start the execution again. It is being a major issue since we face it very frequently, especially after the upgrade to 10.6. previously we were using version 9.5 we faced that crash very rarely only when the execution time exceeds 6 or 7 mins. but in the upgraded version we face it even after 3 mins.

### Desired behavior

Cypress browser should be stable for the execution.

### Test code to reproduce

cannot share the code as it is confidential to client data.

### Cypress Version

10.6

### Node version

v14.16.0

### Operating System

windows 10 (it is a VDI accessed through VPN)

### Debug Logs

```shell
developer tools nothing is working as the entire screen goes blank.
```

**Comment by nagash77** [comment]
@vasanthiraman Unfortunately with the information provided we will not be able to assist you.  If you can provide a reproducible example please update this ticket and we will take a look.
