### ISSUE TITLE
cy.get('element').should('be.visible')  not correctly yielding element

### ISSUE THREAD

**Issue by gtugwell** [cypress-io/cypress#24070]
### Current behavior

Currently when chaining :
`cy.get('element').should('be.visible').then(($element) => {$element.click({force: true})})`, nothing will happen. This appears to be because whatever is yielded from `.should('be.visible')` is not able to be operated on by `.click({force: true})`, however .click() works for this.

### Desired behavior

`cy.get('element').should('be.visible').then(($element) => {$element.click({force: true})})` should result in the `$element` being clicked. I realize that `.should('be.visible')` shouldn't require a `{force: true}`, however doing something like `cy.get('element').should('be.visible').click({force: true})` works just fine.

### Test code to reproduce

```js
cy.get('element')
    .should('be.visible')
    .then(($element) => {
        $element.click({force: true})
    })
```
### Cypress Version

10.8.0, 10.9.0

### Node version

18.10.0

### Operating System

Windows 11

**Comment by mjhenkes** [comment]
I can confirm this behaviour. To summerize

inline works ✅ 
```javascript
cy.get('element').should('be.visible').click()
```

inline with force true works ✅ 
```javascript
cy.get('element').should('be.visible').click({force: true})
```

with then works ✅ 
```javascript
cy.get('element').should('be.visible').then(($element) => {
  $element.click()
})
```

with then force true fails ❌ 
```javascript
cy.get('element').should('be.visible').then(($element) => {
  $element.click({force: true})
})
```

We will route this as a bug.

Is there anything preventing you from using the 'inline with force true' variation as a work around?

**Comment by gtugwell** [comment]
The main use case for using:
```
cy.get('element').should('be.visible').then(($element) => {
  $element.click({force: true});
});
```
 was to have a different flow depending on what the $element was doing, the bug was initially discovered when I was doing some initial testing of ways to avoid using static wait(). Was able to get around this by doing something like this:
```
cy.get('element').should('be.visible').then(($element) => {
  cy.get('element').should('be.visible').click({force: true});
});
```
 Obviously that is super hacky and not the way to go, so went ahead and just rewrote the code to avoid this issue.

**Comment by BlueWinds** [comment]
The element yielded to the `.then()` callback is a DOM element wrapped in jQuery - it's not a Cypress chainer, you can't chain cypress commands off of it. When you do

```
cy.get('element')
  .should('be.visible')
  .then(($element) => {

    $element.click() // This is the jQuery .click() method!
    cy.wrap($element).click({force: true}) // This is now the Cypress .click() command.
  })
```

Generally speaking though, you don't want to pass subjects around like this. It'd be a lot better to write something like

```
cy.get('element')
  .as('elmnt')
  .then(($element) => {  ...whatever you need to do with the element in a callback?... })

cy.get('@elmnt').click({ force: true})
```
