### ISSUE TITLE
10.9.0 broke cy.origin() requests

### ISSUE THREAD

**Issue by EvHaus** [cypress-io/cypress#24073]
### Current behavior

After upgrading from 10.8.0 to 10.9.0 my `cy.origin()` requests no longer complete. They timeout instead.

### Desired behavior

`cy.origin()` requests should work as in 10.8.0

### Test code to reproduce

In my app, once you enter a username/password on the sign up page, it redirects to a third-party page where I need to press an "Accept" button. My code is:

```js
cy.visit('/sign-up');

// Fill out the sign up form
cy.get('#signup-email').type(email);
cy.get('#signup-password').type(password);
cy.get('#btn-signup').click();

// At this point, my app redirects to https://some.sub.domain.auth0.com/some_url

// Wait until we're redirected to Auth0, and click "Accept" there
cy.origin('auth0.com', () => {
    cy.get('button').contains('Accept').click();
});
```

This would work in 10.8.0 but in 10.9.0 is times out with:

```
Timed out retrying after 40000ms: Expected to find content: 'Accept' within the element: [ <button#btn-login.btn.btn-primary.btn-block>, 5 more... ] but never did.
```

Rolling back to 10.8.0 makes the problem go away.

### Cypress Version

10.9.0

### Node version

16.14.1

### Operating System

macOS 12.6

### Other

I see that the [changelog](https://docs.cypress.io/guides/references/changelog#10-9-0) for 10.9.0 includes a bunch of changes to `cy.origin()` but after reviewing the changes I don't see why my simple usage of `cy.origin()` would break completely.

**Comment by mjhenkes** [comment]
It may be fairly hard to diagnose this issue without having a reproducible example that we can run. Based on what you're showing, it looks like you're in in the correct origin but are unable to find the accept button. What does the AUT look like when you run the test? Is it on the correct page?

For example you can use this to double check you're all the right url.

```javascript
cy.visit('/sign-up');

// Fill out the sign up form
cy.get('#signup-email').type(email);
cy.get('#signup-password').type(password);
cy.get('#btn-signup').click();

// Wait until we're redirected to Auth0, and click "Accept" there
cy.origin('auth0.com', () => {
    cy.url().should('eq', 'https://some.sub.domain.auth0.com/some_url')
    cy.get('button').contains('Accept').click();
});
```

**Comment by EvHaus** [comment]
So interestingly `cy.url()` check passes. It gets the right URL. However, if I change:

```
cy.get('button').contains('Accept').click();
```

to

```
cy.get('button').debug()
```

It shows the buttons from the previous URL. So then I added a timeout:

```
cy.origin('auth0.com', () => {
    cy.wait(1000);
    cy.get('button').contains('Accept').click();
});
```

And now it works!

So looks like there's a race condition of some sort where the content inside `cy.origin()` runs before the page change has completed.

**Comment by mjhenkes** [comment]
@EvHaus thats great news! A couple of things could be happening here. In 10.9.0 we improved the performance of cy.origin by removing logic that would delay cross origin requests. What I suspect is happening is that after click the cy.origin call runs prior to the page being marked as unloading which would naturally pause the command. So you'll have to account for that transition.

Try this as your command to retry getting the button until it's visible. I think this will work but it's possible you have to get the button by id instead of using the contains.

```javascript
cy.get('button').contains('Accept').should('be.visible').click()
```

**Comment by yanyan666666** [comment]
I have the same issue after using 10.9.0 in mac, the external page could not be uploaded, even I add wait() and should().
 cy.origin('stripe.com', () => {
    |            ^
  4 |             cy.wait(3000);
  5 |             cy.url().should('include', 'stripe');
  6 |             cy.get('#cardNumber').should('be.visible)

**Comment by mjhenkes** [comment]
@yanyan666666, could you put together an example repo? Your comment doesn't give me much to debug with.

**Comment by yanyan666666** [comment]
> @yanyan666666, could you put together an example repo? Your comment doesn't give me much to debug with.
Thank you for your answer.  The spec needs to buy a course, and after clicking "buy now" button, the spec will direct to the other origin for payment. The current issue is the payment webpage could not be shown.
```
cy.visit(https://exams.shenyuncreations.com/course/CF3M1jbQURs)
cy.get('button.btn').click()
cy.origin('stripe.com', () => {
     cy.wait(3000);
     cy.url().should('include', 'stripe');
     cy.get('#cardNumber').should('be.visible);
})
```

**Comment by AtofStryker** [comment]
@yanyan666666 this looks to pop up a modal and I do not see a redirect to stripe. Is this still correct?

**Comment by AtofStryker** [comment]
@EvHaus is this still an issue for you? I did want to bring up with Cypress `10.10.0` you will likely need to include the full origin for your `auth0` tenant to keep things working smoothly 😃 .

**Comment by EvHaus** [comment]
So interestingly upgrading to 10.10.0 made the problem go away entirely without any code changes. 🤷 

Will close the issue.

**Comment by EvHaus** [comment]
🤯 Frustratingly -- this issue has started happening again. Now I'm getting:

> Timed out retrying after 40000ms: The command was expected to run against origin https://auth0.com but the application is at origin https://dev-f9asd0.us.auth0.com.

I had to change `cy.origin('auth0.com')` to `cy.origin('https://dev-f9asd0.us.auth0.com')`

I'm not sure why this is needed all of a sudden. 🤷

**Comment by AtofStryker** [comment]
Hi @EvHaus it's due to the changes in [10.10.0](https://docs.cypress.io/guides/references/changelog#10-10-0) requiring a strict origin over a super domain origin. In other words, the super domain now needs to be included. Did updating the origin fix the issue?

**Comment by EvHaus** [comment]
> Did updating the origin fix the issue?

Yes. I would recommend updating the docs though. At the moment they say:

> `url`: A URL specifying the secondary origin in which the callback is to be executed. This should at the very least contain a hostname, and may also include the protocol, port number & path.

I would change to "and MUST include protocol, subdomains, ...."

**Comment by AtofStryker** [comment]
> > Did updating the origin fix the issue?
> 
> Yes. I would recommend updating the docs though. At the moment they say:
> 
> > `url`: A URL specifying the secondary origin in which the callback is to be executed. This should at the very least contain a hostname, and may also include the protocol, port number & path.
> 
> I would change to "and MUST include protocol, subdomains, ...."

That's my fault on that one 😅 . Thank you for pointing that out. I must have missed it when combing through the docs. I should be able to get something opened this afternoon into [cypress-documentation](https://github.com/cypress-io/cypress-documentation)

**Comment by AtofStryker** [comment]
@EvHaus I am thinking something like this:

> A URL specifying the secondary origin in which the callback is to be executed.
This should contain the full hostname, which includes the subdomain (if applicable), domain, 
and top-level domain. This may also include the protocol, port number & path. 
Query params are not supported.

Is this a bit clearer in your opinion?

**Comment by EvHaus** [comment]
That looks great!
