### ISSUE TITLE
Endless UI Cypress client loading after automation remaking from 9.7 to 10.9 version

### ISSUE THREAD

**Issue by 36const** [cypress-io/cypress#24075]
### Current behavior

1. I make `git clone` of my project with Cypress 9.7.0
2. Launch `npm install cypress --save-dev` in its directory 
3. Launch `npx cypress open`
4. Make 3 steps for upgrade to version 10.9.0

But after the 3rd step it begin endless loading, without any error or messages.
If you close client and reopen it, that endless loading will continue.
Changes which were shown in upgrading procees, really were made.

If I try to create new project in other directory by `npx cypress open` then there wi be happen the same after clicking `E2E` or `Component` button

![image](https://user-images.githubusercontent.com/13105138/193468579-bb954f4f-cdb3-4d9f-867f-e37032cd3eac.png)

### Cypress Version

10.9.0

### Node version

10.19.0

### Package Manager

npm

### Package Manager Version

6.14.4

### Operating system

Linux

### Operating System Version

20.04

**Comment by marktnoonan** [comment]
@36const Thanks for reporting this! I see you are on node 10.19.0. Would you be able to upgrade your version of node to 12, or 14+? https://docs.cypress.io/guides/getting-started/installing-cypress#Node-js

**Comment by 36const** [comment]
@marktnoonan really, it helped 
Thanks!
