### ISSUE TITLE
Running the cypress test cases getting failed with the Jenkins build "Error:read ECONNRESET"

### ISSUE THREAD

**Issue by kkris010119** [cypress-io/cypress#24086]
### Current behavior

Running the cypress tests (node v14.16.0, cypress 7.7.0) part of the Jenkins CICD pipeline and after successfully running couple of test cases getting the below error and the build is failing, please share if any resolution for the below issue.

Error Details:
```
Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
{
 errno: -104,
 code: 'ECONNRESET',
 syscall: 'read'
}
Error: Command failed with exit code 1: npx cypress run --browser=chrome --env coverage=true --config video=false --spec **/*.spec.ts
```
### Desired behavior

All the test cases should be executed without breaking with an error "Error: read ECONNRESET"

### Test code to reproduce
```
"test:ci": "cross-env CYPRESS_CRASH_REPORTS=0 start-server-and-test test:ci:http-server http-get://localhost:4200/../index.html \"npx cypress run --browser=chrome --env covergae=true --config video=false --spec '**/*.spec.ts'\""
"test:ci:http-server": "angular-http-server --silent --path ./client/+build --baseHref xxx/xxx/xxxxx -p 4200
```
### Cypress Version

7.7.0

### Node version

v14.16.0

### Operating System

Linux

### Debug Logs

```shell
Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
{
 errno: -104,
 code: 'ECONNRESET',
 syscall: 'read'
}
Error: Command failed with exit code 1: npx cypress run --browser=chrome --env coverage=true --config video=false --spec **/*.spec.ts
```

### Other

Had the issue in windows machine, and it is working fine by setting the cypress environment variable "CYPRESS_CRASH_REPORTS=0", but the similar fix does not work for the Jenkins build

Also tried upgrading some of the dependencies like "cypress", "start-server-and-test", angular-http-server" with the latest version but that does not resolve the build issue.

**Comment by nagash77** [comment]
@kkris010119 I see you are using a pretty old version of Cypress.  Please try upgrading to the latest and see if the issue persists.

**Comment by kkris010119** [comment]
@nagash77 Tried with cypress 8.4.1 and 9.5.1 but still have the issue. Looks like the cypress 10.9.0 requires changes in the way test cases are organized so could not run the existing test cases with this version.

**Comment by nagash77** [comment]
@kkris010119 Can you please include an example test file you running that causes this issue to happen please?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
