### ISSUE TITLE
Specific controls of application which is being tested are not working during Cypress Execution which works in some scenario

### ISSUE THREAD

**Issue by vasanthiraman** [cypress-io/cypress#24088]
### Current behavior

Specific controls of application which is being tested are not working during Cypress Execution.

such as dropdown, text box. If there is click operation on dropdown element, the click action is completed, but the dropdown is not responding (not expanded with the list of values). If I manually interrupt and click (when the url is still active in cypress before exe stops) also the dropdown is not responding.  not only dropdown, few textbox in the same page is also not responding when clicked, but few other controls like back button, select button and all working. 

ITs completely weird, because the same step with same control is working fine, during the second scenario in the same feature file, in cypress execution.

Note - this is not application issue, because the same scenario I tried manually step by step, all the controls are working fine.

### Test code to reproduce

code cannot be shared, client confidential. but it is normal cypress click only, nothing complex.

### Cypress Version

10.6

### Node version

v14

### Operating System

Windows 10

**Comment by nagash77** [comment]
@vasanthiraman Unfortunately without a reproducible example we will not be able to assist you.  I am going to close this issue, but please do post here a reproducible example if you are able to share one and we will be happy to take a look.
