### ISSUE TITLE
Cypress 10.9.0 on MacOS gets shy when you watch it

### ISSUE THREAD

**Issue by crates** [cypress-io/cypress#24096]
### Current behavior

This is probably the strangest thing I've seen in a long time with Cypress, after many years of using it.

I have a React app (using React Admin) with Material UI v5 in it. Inside is a fairly normal dropdown.

I'm clicking the dropdown, and then, I'm trying to click the first item in the list that it opens on click.

When I run the tests headlessly, or simply do not leave the Cypress test runner focused, it runs fine.

Here's the really strange part: when I have the test window focused and watch it run, it frequently either takes a VERY long time to find the `<li>` that gets spawned by MuiList, or alternatively, it completely times out.

I have one test file that has three instances of searching for a list item and clicking it. If I run the tests and quickly CMD+TAB away from the test runner, it will very quickly finish all the tests successfully, 100% of the time - in about 3-4 seconds or less.

However, consistently, if the test window is actively focused, it will crawl along and often fail to find the reference.

I've never seen anything quite like this in my life. I have no idea what could be causing it.

### Desired behavior

Test runs should happen identically, whether or not the test runner is actively focused in view.

### Test code to reproduce

```
// test code follows:
const getDropdown = () => cy.get('[data-testid="mui-dropdown"]');
const getOpenListReference = () => cy.get('div ul.MuiList-root li').as('openDropdown');

getDropdown().click().then(() => {
  getOpenListReference(); // this successfully aliases the open list items
  cy.get('@openDropdown').eq(1).click(); // this line is where things fail
});
```

### Cypress Version

10.9.0

### Node version

18.9.0

### Operating System

MacOS Monterey 12.6

**Comment by crates** [comment]
Update: we're seeing similar flaky behavior when the tests are running headlessly.

However, when the tests run interactively (and the window isn't focused), they work 100% of the time.

**Comment by crates** [comment]
Another note: Cypress is able to find the correct selector for the aliased list item. It translates the selector correctly into its longer form. It's just unable to click on it afterwards, when the test runner is focused in view or when running headlessly. It fails even when using `{force: true}` in the click method's options.

**Comment by crates** [comment]
Here's how we are temporarily working around this strange Cypress behavior.

Instead of trying to click the list item inside of Material UI's `<Select>` element, we are using their accessibility options to select the item using the keyboard. This is working fine regardless of whether the tests are running with the window focused, unfocused, or headlessly.

Here's the code that is working around the problem for us, for now:

```
cy.get('body').type('{downArrow}{enter}');
```

**Comment by astone123** [comment]
@crates thanks for filing this. Could you provide a project that I could use to reproduce this issue?

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
