### ISSUE TITLE
Cypress open process hangs during execution

### ISSUE THREAD

**Issue by kzahozhy** [cypress-io/cypress#24107]
### Current behavior

Steps: 
1. Run npx cypress open in CLI
2. Select E2E testing
3. Select Chrome as target browser.

After that step process hangs permanently on opening E2@ testing in chrome.

![изображение](https://user-images.githubusercontent.com/13750682/193789631-f3f18df4-b02d-471b-8c84-7e78b94db629.png)

![изображение](https://user-images.githubusercontent.com/13750682/193789724-8fc68b93-0d4f-46ec-8c31-9e1971df20df.png)

### Test code to reproduce

no code

### Cypress Version

10.4.0/10.6.0

### Node version

16.14.2

### Operating System

Windows 10Pro 19044.2006

**Comment by nagash77** [comment]
@kzahozhy Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by kzahozhy** [comment]
The problem was in a local project config
