### ISSUE TITLE
How to select a dynamic option?

### ISSUE THREAD

**Issue by FrontendSophie** [cypress-io/cypress#2410]
### Current behavior:

`select(value)` works fine but what if I cannot get the `value` ?  I've tried using `$` to get current option value and then use it as a parameter but it doesn't work.

### Desired behavior:

At least I can select the first option without knowing value or any other workaround ? Thanks.

### Versions

Cypress: ^3.1.0

**Comment by raphaelcunha** [comment]
@FrontendSophie I think this code can help you, it selects the first option of the select.

` cy.get('.select').then(($select) => {
        const opt = $select.find('option:nth-child(2)')
        $select.val(opt.attr('value'))
        return $select
      }).trigger('change')`

**Comment by FrontendSophie** [comment]
@raphaelcunha  cheers
