### ISSUE TITLE
CT related npm packages failing to release

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#24112]
### Current behavior

Since we moved away from deploying npm packages on master, several of the ct related npm packages have been [failing to publish](https://app.circleci.com/pipelines/github/cypress-io/cypress/44335/workflows/83cbd8fc-7f53-491f-882c-e7b2e555d36d/jobs/1857039). Strangely, the automated changelog process thinks it is succeeding, causing the changelogs to have duplicated entries.

### Desired behavior

Fix `npm-release` and verify all npm packages are publishing correctly. Clean up the changelogs and investigate why the changelog automation runs even when the publish fails (this might make sense as a followup issue).

### Test code to reproduce

https://app.circleci.com/pipelines/github/cypress-io/cypress/44335/workflows/83cbd8fc-7f53-491f-882c-e7b2e555d36d/jobs/1857039

### Cypress Version

10.9.0

### Node version

v16.16.0

### Operating System

CI

### Other

@chrisbreiding ran into this issue recently while trying to publish webpack-preprocessor. [Thread](https://cypressio.slack.com/archives/C011BAPC614/p1664895881944049) identifying the issue and another [Thread](https://cypressio.slack.com/archives/C01TQQCQLJY/p1664325004153349) of him debugging that should help.

**Comment by astone123** [comment]
Example https://app.circleci.com/pipelines/github/cypress-io/cypress/44608/workflows/48edb229-84e2-4189-96a6-bbe768dca285/jobs/1869680
