### ISSUE TITLE
Cypress tells server returns 404 when its not right

### ISSUE THREAD

**Issue by matiasgarcia** [cypress-io/cypress#24113]
### Current behavior

Cypress tells html is 404:

![Screenshot from 2022-10-04 12-25-49](https://user-images.githubusercontent.com/2261869/193860834-aa500fec-8c5a-48bb-b118-7f8c3c55e42d.png)

Yet if you click the link (https://onboarding.remitex-staging.online/token) it works.

What I am suspecting is that when you click that link, the page does a in browser history rewrite to https://onboarding.remitex-staging.online/natural-person, so that might confuse Cypress somehow?

In my cypress test I have forced the baseUrl: 

`it("Start with a profile", { baseUrl: 'https://onboarding.remitex-staging.online' }, () => {`

### Desired behavior

Should not return 404 and follow redirect?

### Test code to reproduce

```
it("Start with a profile", { baseUrl: 'https://onboarding.remitex-staging.online' }, () => {
   cy.visit(`/02aa29ca4dffe9c02b399f031b475b21d809886a084e6edcbf79ea29d99dac35`);
})
```

### Cypress Version

9.7.0

### Node version

v16.13.1

### Operating System

Linux 18

**Comment by mjhenkes** [comment]
@matiasgarcia I'm sorry you're seeing this issue. Before you run your test could you open the inspector and watch the network tab as the test runs? This should let you know if you're really getting a 404 or not and may shed some light on why your network request is failing.

What status code does the request return with?

**Comment by matiasgarcia** [comment]
After reviewing this, indeed our app is returning 404. We serve our SPAs with S3, which returns 404 with the proper index.html and JS to handle routes.

**Comment by matiasgarcia** [comment]
Indeed the solution is using failOnStatusCode: false when visiting the site.
