### ISSUE TITLE
After saving open test, cypress does not rerun the test script

### ISSUE THREAD

**Issue by chrisbillups** [cypress-io/cypress#2411]
### Is this a Feature or Bug?

This appears to be a bug.  I had it happen to myself and also a co-worker of mine working at a different location.  The behavior appeared to start earlier this afternoon.  

This issue DID NOT occur around 830am Eastern Standard Time (occurred afterward)

### Current behavior:

I am using Visual Studio Code to write tests for Cypress:

1. ran a test from Cypress
2. then i modified the test script in Visual Studio Code and saved it
3. the test case DID NOT rerun in Cypress (i had to close Cypress, and reopen it and then manually run the test case again)

### Desired behavior:

1. ran a test from Cypress
2. then i modified the test script in Visual Studio Code and saved it
3. the test case DOES rerun in Cypress

### Steps to reproduce:

1.  Create a test case in Visual Studio Code for Cypress
2.  Run the test case in Cypress
3.  Now modify the test case in Visual Studio Code and save it (the test case should rerun in Cypress - when the bug occurred it DID NOT rerun the test case)

### Versions

Cypress Beta Version 3.0.1
Chrome 68

**Comment by jennifer-shehane** [comment]
We have not had any releases today that would have affected this behavior. 

What OS are you using? There is an issue with watching in Windows that has a fix ready to go out. https://github.com/cypress-io/cypress/issues/712

**Comment by chrisbillups** [comment]
Ok thanks.  This is with Windows 10.  Hopefully when that fix is read to go
it will resolve the problem.

**Comment by joaohcopetti** [comment]
I had this problem and I figured out if you run the cypress command with the flag `--e2e` it won't rerun the tests after saving the file for some reason. I was running `npx cypress open --e2e`. Removing the flag `--e2e` makes it work again.
