### ISSUE TITLE
Wrong 'AttemptResult' TS type

### ISSUE THREAD

**Issue by bass3l** [cypress-io/cypress#24110]
### Current behavior

Hi and thank you for this great work.

Just want to report a **tiny issue** with the `CommandLine.AttemptResult` type. The [type definition](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress-npm-api.d.ts#L183) is:

```js
interface AttemptResult {
  state: string
  error: TestError | null
  startedAt: dateTimeISO
  duration: ms
  videoTimestamp: ms
  screenshots: ScreenshotInformation[]
}
```

But `duration` and `startedAt` don't exist in the actual object, instead the following should be defined `wallClockDuration` and `wallClockStartedAt` respectively, I've attached a sample `AttemptResult` object.

Not sure if `screenshots` property exist in the actual object, and there is `failedFromHookId` and `timings` missing in the type definition which exist. Anyway, if this is confirmed, I could take a look into fixing it. 👍 

### Test code to reproduce

Here is a TS example accessing mentioned properties:

```js
export default (on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('after:spec', async (spec, results) => {
    results.tests.forEach(cypressTestResult => {
      const attempt = cypressTestResult.attempts.pop();
      console.log(attempt);
      // This will complain that the property doesn't exist
      const wallClockDuration = attempt.wallClockDuration;
      // This will complain that the property doesn't exist
      const wallClockStartedAt = attempt.wallClockStartedAt;
    });
  });
}
```

### Cypress Version

10.9.0

### Node version

16.3.0

### Operating System

macOS 12.1

### Debug Logs

```shell
{
  state: 'passed',
  error: null,
  timings: { lifecycle: 7, test: { fnDuration: 9805, afterFnDuration: 0 } },
  failedFromHookId: null,
  wallClockStartedAt: '2022-10-04T10:39:19.792Z',
  wallClockDuration: 9817,
  videoTimestamp: 1584
}
```

**Comment by itiarom** [comment]
Hello, I am really interested in contributing and I am in the process of learning Vue and TypeScript. I see that this is still an active issue, do you think I could tackle this? @emilyrohrbough

**Comment by emilyrohrbough** [comment]
@Ioanna2001 Please feel free to pick this up!

**Comment by mahdikhashan** [comment]
@emilyrohrbough Hi, can I open a PR to improve the typing? if yes, please assign the issue to me.
