### ISSUE TITLE
Unable to access the url on chrome, firefox and edge except electron

### ISSUE THREAD

**Issue by LegendShola** [cypress-io/cypress#24126]
### Current behavior

Currently, when I try to do a simple log in test on chrome, firefox and edge, it always throwing an error occured but this doesn't happen in electron, I've been managing it using electron for my tests but I need to use the "realClick" function which only works with chrome.
Below is the behavior on chrome
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93574000/194031506-567af1df-2fbc-477c-81a0-5ae9c56294f0.png">
and below is the behavior when I try opening it on edge
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93574000/194032360-a98edeb7-7254-458e-bc83-e2f56a92f0c6.png">
While on firefox it shows the below
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93574000/194038369-d70dba70-e958-4511-8571-1731311a25fe.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93574000/194038450-0f394ca7-41a3-4eb1-822e-14eeaa722beb.png">

### Desired behavior

It should display like this as on electron
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93574000/194039172-66154d57-a46d-4691-8803-3946220af490.png">

### Test code to reproduce

beforeEach('Login', () =>{
        cy.viewport(1280, 720)
        cy.visit('https://alat-web-.1.7-dev.surge.sh/')
        loginPage.typeUsername(data.Test26.email);
        loginPage.typePassword(data.Test26.currentPassword);
        loginPage.clickLogin();
    })

### Cypress Version

10.9.0

### Node version

v16.15.1

### Operating System

Edition	Windows 10 Enterprise Version	21H2 Installed on	‎6/‎8/‎2022 OS build	19044.1889 Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by LegendShola** [comment]
In addition, when I try it with edge, it shows this, "warningfailed to access session localStorage data on origin(s): https://ntp.msn.com"

**Comment by mjhenkes** [comment]
@LegendShola, I'm trying to decipher what is happening in your screenshots. are you saying the chrome browser doesn't load, edge fails the request and the firefox browser hangs? These all seem like they could be very different problems.

**Comment by AtofStryker** [comment]
@LegendShola would you also be able to provide a reproduction repository? The snippet provided is not enough to reproduce this issue. Can you help me fill in the blanks with this [reproduction](https://github.com/AtofStryker/cypress-issue-24126)?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
