### ISSUE TITLE
Add Export to commands.ts for projects with isolatedModules tsconfig flag

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24137]
### Current Behavior
When a project has the `isolatedModules` flag set to `true`, a typescript error is shown in `cypress/support/commands.ts`. 

<img width="947" alt="image" src="https://user-images.githubusercontent.com/25568640/194138066-958b70c2-26fa-423d-bd2f-1d65d1467b27.png">

### Desired behavior
When scaffolding files for a typescript project, check the tsconfig for the `isolatedModules` flag. We should add `export {}` to the bottom of `commands.ts` in this situation.

**Comment by JessicaSachs** [comment]
Do you also expect to write your spec files with `export {}` at the bottom? I turned off this compilerOption for the `cypress` folder and for files matching my spec pattern.

**Comment by ZachJW34** [comment]
Specs will normally have an `import` which appeases the `isolatedModules` flag. Can you clarify what you mean by `turned off this compilerOptions for files matching my spec pattern`? I don't think this is an option for projects like `create-react-app` as the only way to get custom compilerOptions per file is to use separate tsconfigs which cra isn't happy with.

Adding `export {}` might not be the best way to solve this. Maybe commenting out the `commands` file would work. In the end, we need a better way of onboarding users that have this option set (which a lot of frameworks set out of the box)

**Comment by ZachJW34** [comment]
Found another common issue (eslint + typescript related)
![Screen Shot 2022-10-06 at 10 49 00 AM](https://user-images.githubusercontent.com/25158820/194359443-6f318ced-c356-40a0-a0b5-0016ab3512ef.png)

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24137?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
