### ISSUE TITLE
Normalize DevServer Config Resolution

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#24133]
### Current behavior

The config resolution for `@cypress/webpack-dev-server` and `@cypress/vite-dev-server` differ.

`@cypress/vite-dev-server` will always source a `<project-root>/vite.config.js` and merge the properties with the `devServer.viteConfig` value if supplied.

`@cypress/webpack-dev-server` will only source a `<project-root>/webpack.config.js` if and only if `devServer.webpackConfig` is undefined.

### Desired behavior

The config resolution should be equivalent across dev-servers. I'd argue the `@cypress/webpack-dev-server` is the proper config resolution, as it allows the user to opt out of Cypress trying to merge in their project root config (which might be a config they don't want to use for CT testing).

### Test code to reproduce

Run `DEBUG=cypress:vite-dev-server:resolve-config npx cypress open` on a Vite based project that has a `<project-root>/vite.config.js`. Look in the terminal after clicking on CT testing in the launchpad and the resolved config will be logged. Close Cypress and edit the `cypress.config.js -> component.devServer.viteConfig` property (add a plugin, change port). The changes made will be merged with the properties defined in `<project-root>/vite.config.js`.

Run `DEBUG=cypress:webpack-dev-server:makeWebpackConfig npx cypress open` on a Webpack based project that has a `<project-root>/webpack.config.js`. Follow similar steps described above. Notice that after adding a `cypress.config.js -> component.devServer.webpackConfig`, the contents of `<project-root>/webpack.config.js` are no longer merged.

https://user-images.githubusercontent.com/25158820/194119332-f72cc2dd-2f4a-4a3e-bc82-b689b3999d3c.mov

__NOTE__: This would be a breaking change

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24133?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
Just noting from the sync with Brian last Wednesday, we have agreed that 

> the @cypress/webpack-dev-server is the proper config resolution 

and that that is the plan for this ticket. It should come with warnings for Vite users.

My suggestion for the vite warnings is to use our existing alert pattern in the app at the top of the specs list, so there’s one place to surface the error, and it’s definitely in the path of the user opening a spec. We would persist their dismissal of the alert in saved state.

When tests are run from the terminal, we would also print a warning to Vite users that config resolution has changed. The text for both warnings would be something like:

> The process Cypress uses for Vite config resolution has changed. This may cause unexpected behavior related to your project's Vite config. See our latest docs[link] for more information.

**Comment by ZachJW34** [comment]
@marktnoonan for run mode, is the warning always displayed or displayed only once? When do we stop showing the warning?
