### ISSUE TITLE
Hovering over mount in command log does not show the mounted component in AUT

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24138]
## Current Behavior
When hovering over `mount` in the command log of a component test, the AUT shows a blank white view instead of the mounted component.

<img width="1939" alt="image" src="https://user-images.githubusercontent.com/25568640/194139170-c481a64b-f07c-4a7b-a35e-85958cef63b7.png">

## Desired Behavior

The mount command shows the mounted component in the AUT

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24138?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
