### ISSUE TITLE
Normalize DevServer Compilation Error Reporting

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#24135]
### Current behavior

When using `@cypress/webpack-dev-server` and there is a compilation error, the error is displayed in the reporter and a blank AUT is shown:
![create-react-app-typescript-error](https://user-images.githubusercontent.com/25158820/194122856-d0a1c317-fbd6-4c17-9bd3-c27666f43cd8.png)

When using `@cypress/vite-dev-server` and there is a compilation error, one error is displayed in the reporter and an overlay displays another over the AUT:
![react-vite-typescript-error](https://user-images.githubusercontent.com/25158820/194123697-a9e2ff1f-1e37-4022-86ad-e8f6cd4a2b0e.png)

### Desired behavior

Compilation errors should be consistent across dev-servers. For Webpack, the useful information is found in the reporter. For Vite, the overlay contains the pertinent information. This also carries over to run-mode, as the errors are displayed differently when logging to the terminal.

### Test code to reproduce

Two configured apps, one Webpack and one Vite based. Inside a spec file, cause a compilation error:

```js
it('should break' , = { })
```

Webpack will have error in reporter, Vite will have error in reporter and overlay.

### Other

Information in this [tech-brief](https://github.com/cypress-io/tech-briefs/tree/main/briefs/ct-architectural-improvements#compilationlint-error-handling) regarding error handling and overlay changes.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24135?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
