### ISSUE TITLE
Unable to Write Consecutive Component Tests which Navigate to Other URLs

### ISSUE THREAD

**Issue by danadajian** [cypress-io/cypress#24131]
### Current behavior

In the component test runner, when a test runs that clicks a link to another URL/path, the subsequent test fails due to the page's HTML being in a bad state.

Here is the default HTML response when an interaction with the component changes the URL path to `/endpoint`:
```html
<html lang="en">
  <head>
    <meta charset="utf-8">
      <title>Error</title>
  </head>
  <body>
    <pre>Cannot GET /endpoint</pre>
  </body>
</html>
```

Even when using `cy.intercept()` to return a custom response, there is no way to return to the original URL the test was running at.

I even tried "hacky" work-arounds such as using `cy.go('back')`, but this results in the test runner entering an infinite loop.

The only current workaround appears to be to separate these tests into separate spec files and run each test at the very end of the file.

### Desired behavior

In this situation, Cypress should reset the component test runner to the original `window.location.href` and not persist the URL/path I visited in a previous test.

### Test code to reproduce

Code:
```tsx
export const MyComponent = () => (
  <div>
    <a href="/endpoint">Click me!</a>
    <p>some text</p>
  </div>
)
```

Test:
```tsx
describe('MyComponent', () => {
  it('clicks a link which brings us to a new URL', () => {
    cy.mount(<MyComponent />);

    cy.intercept('/endpoint', 'success');
    cy.findByRole('link', { name: 'Click me!' }).click();
  });

  it('I want to test something else about my component now', () => {
    cy.mount(<MyComponent />);

    cy.findByText('some text').should('be.visible'); // this assertion fails since the DOM is empty
  });
});
```

### Cypress Version

10.9.0

### Node version

14.19.1

### Operating System

macOS 12.6

**Comment by danadajian** [comment]
@JessicaSachs Do you think this is actually a bug? Or is it more of a feature request for the capability to "intercept" a URL change and prevent it?

Is there a way you would recommend working around this in the meantime? Right now all I can do is separate these tests into different files and ensure that they are the very last test to run in a test suite. I should also mention that my use case here is testing that a certain method is called when a link is clicked (obviously I don't need to test that clicking an `<a>` tag navigates to its `href`)

**Comment by ncknuna** [comment]
For the purposes of my tests, I only care about resetting the query params and the hash, so I did this as a workaround:
```javascript

// Remove hash and query/search string from url before each test
beforeEach(() => {
  cy.window().then(window => {
    const parsed = queryString.parseUrl(window.location.href)
    window.history.pushState({}, '', parsed.url)
  })
})
```
I imagine most people also care about resetting the path, which could be done in a similar way

**Comment by danadajian** [comment]
@ncknuna Thanks for the suggestion! Unfortunately, that doesn't actually work. Even when explicitly navigating to the URL from the beginning of the previous test, the subsequent test cannot reset its state once it has navigated to another path.

Basically once you navigate to any URL within a test, the component test runner is "stuck" at that URL and cannot test anything else.

**Comment by JessicaSachs** [comment]
Unfortunately you cannot navigate between pages in Cy component tests unless you're using an in-memory router that doesn't change top's URL. That's the moment where you'll want to write an end-to-end test.

I've tried many "workarounds" to prevent this top-level navigation, but we decided at the time of building Cypress CT that it was out of scope and that most people can get what they need from using a test-only in memory router, spying on route navigation, and using router hooks to prevent page navigation.

If I come up with a workaround, I'll let you know.

**Comment by ncknuna** [comment]
Hmmm, interesting. I don't know why what I did works for me then. The two things I can think of are:
1. My code is changing the URL programmatically via `history`, using the `history` package
2. I'm not changing the path, just the query params and hash

Not sure if that's helpful, but regardless, best of luck finding something that will work!

**Comment by danadajian** [comment]
After giving it some thought, I think I found a decent workaround for links at least.

```ts
cy.findByRole('link', { name: 'Click me' }).invoke('removeAttr', 'href').click();
```

Since this is using testing-library, we know the link is clickable and accessible, and we don't really need to test that clicking a link with an `href` will navigate to that URL. But we can still test that clicking the click achieves a certain side effect, which is the only reason to click a link in a component test anyway.

**Comment by JessicaSachs** [comment]
I’m going to use this in my workshop tomorrow :-)

Great workaround. Should find it’s way into the docs.

**Comment by blessanm86** [comment]
I was bit by this today. Trying out cypress component testing as an alternative to Jest in our MFE.
In our case we call `window.location.href = ***` after a form submission in the onSubmit handler.

We don't use any kind of routers. The only work around I could think of is using maybe an env variable like

```
const shouldRedirect = process.env.CypressComponentTest ? false: true; 
if(shouldRedirect) {
  window.location.href = ***
}
```

Would be great if some sorta memory router was provided within cypress. 

We don't use e2e because its a library of complex components with business logic. The consuming apps are the host for it.

**Comment by rstoneIDBS** [comment]
We've just been bitten by this issue, thanks to this page I was able to come up with the following fix for our use case which involves a component modifying the location.hash value via `location.assign`. This feels like something Cypress should be doing really as part of the test setup/teardown to ensure a fresh browser state for each test.

```
  let initialHref: string;

  beforeEach(() => {
    cy.window().then((window) => {
      initialHref = window.location.href;
    });
  });

  afterEach(() => {
    cy.window().then((window) => {
      window.history.pushState({}, '', initialHref);
    });
  });
```

**Comment by xserjiox** [comment]
Faced with the same problem and I was looking for possible workarounds. For me `window.history.back()` inside `afterEach` worked but it seems more like a crutch then a normal solution. Also the approach with storing `initialHref` that @rstoneIDBS provided worked fine, so I took it, thank you! But I agree that Cypress have to ensure that its fresh browser state for each component test.
