### ISSUE TITLE
Component name not displaying properly when importing Nuxt page component

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24140]
### Current Behavior

When importing a page component in nuxt the component name displays as `<f ... />` in the command log

<img width="416" alt="image" src="https://user-images.githubusercontent.com/25568640/194169462-00e4db28-a8a8-4ac4-9673-b8f1527d66ef.png">

### Desired Behavior

The component name is displayed

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24140?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Worth noting we spent time/effort in test utils already to solve the problem of "what is this component named", see https://github.com/vuejs/test-utils/blob/864e9e2b3a1e65d19b9e748c0af5d4b26698d99c/src/utils/componentName.ts.
