### ISSUE TITLE
Audit CT Mount API

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#24142]
### What would you like?

An audit of the existing mount frameworks.

### Why is this needed?

To determine how consistent we are and to gleam a pattern for moving forward with a standard API that all mounts can share. Things to look for are:
* What is exported (just mount or are there other utilities)
* What does the API look like for each mount -> `cy.mount(component, options)`
* What does the log look like in the reporter (Component name, snapshot)
* What does the mount return
* Where does the mounted component end up in the dom
* Do the mounts cleanup properly
* What happens when you try and mount multiple components inside one test
* Are the types working properly e.g. do you get intellisense for props
* More...

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24142?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
