### ISSUE TITLE
select option value

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#2414]
Hello, I want to select a specific value but I have the following result =

```
<div id="departureCityContainer"><select class="form-control" data-refresh="DepartureCity" id="ddl-DepartureCity" name="Value" onchange="refreshDdlSearch(this)"><option value="">Ville de départ</option>
<option value="BES">Brest</option>
<option value="BOD">Bordeaux</option>
<option value="CFE">Clermont Ferrand</option>
<option value="DOL">Deauville</option>
<option value="ETZ">Metz / Nancy</option>
<option value="GVA">Genève</option>
<option value="LIL">Lille</option>
<option value="LUX">Luxembourg</option>
<option value="LYS">Lyon</option>
<option value="MRS">Marseille</option>
<option value="NCE">Nice</option>
<option value="NTE">Nantes</option>
<option selected="selected" value="PAR">Paris</option>
<option value="RNS">Rennes</option>
<option value="SXB">Strasbourg</option>
<option value="TLS">Toulouse</option>
</select></div>
```

I want to select Marseille so I did =
`cy.get('select[id="ddl-DepartureCity"]').select('Brest', { force: true })`

In the console I have that =
![image](https://user-images.githubusercontent.com/42767419/44841638-21d28b00-ac44-11e8-9972-d1153fa8c402.png)

And I can't select the city.

**Comment by smartHasmukh** [comment]
Hello @mandriao84 I have resolved you issue and tested also

> HTML Code

```
<div>
            <select class="form-control" data-refresh="DepartureCity" id="ddl-DepartureCity" name="Value">
              <option value="">Ville de départ</option>
              <option value="BES">Brest</option>
              <option value="BOD">Bordeaux</option>
              <option value="CFE">Clermont Ferrand</option>
              <option value="DOL">Deauville</option>
              <option value="ETZ">Metz / Nancy</option>
              <option value="GVA">Genève</option>
              <option value="LIL">Lille</option>
              <option value="LUX">Luxembourg</option>
              <option value="LYS">Lyon</option>
              <option value="MRS">Marseille</option>
              <option value="NCE">Nice</option>
              <option value="NTE">Nantes</option>
              <option selected="selected" value="PAR">Paris</option>
              <option value="RNS">Rennes</option>
              <option value="SXB">Strasbourg</option>
              <option value="TLS">Toulouse</option>
            </select>
          </div>
```

> Cypess code

```
cy.get('#ddl-DepartureCity').select('BOD');
```

You will get reference from [here](https://docs.cypress.io/api/commands/select.html#Syntax)

**Comment by smartHasmukh** [comment]
@jennifer-shehane @brian-mann Please close this one issue

**Comment by carobernat** [comment]
Hello! I'm having the same problem:
> HTML code:
`<select class="excess-select" id="excess">
  	<option value="franchise_6500">$6500</option>
  	<option value="franchise_7000">$7000</option>
</select> `

>Cypress code:
` cy.get('#excess').select('option').should('have.value', 'franchise_')`

>Cypress error:
`CypressError: Timed out retrying: cy.select() failed because it could not find a single <option> with value or text matching: 'option'`

**Comment by kartikupreti** [comment]
@carobernat 

as you can see from the example on top, you just need to provide the `value` in the tag to the select
in your case 
`cy.get('#excess').select('franchise_6500').should('have.value', 'franchise_')`

**Comment by akshaykapoor-ct** [comment]
Hi, I want to select the option from the drop down but not able to select as value attribute is not given
![image](https://user-images.githubusercontent.com/60504184/75518651-71576a00-5a27-11ea-9602-adc12d6f803b.png)

Code Using:
     cy.get("#provideQuoteTableResponse>tbody>tr:nth-of-type("+i+")>td:nth-of-type(11) #toStand-select").select("Yes")
![image](https://user-images.githubusercontent.com/60504184/75518757-a9f74380-5a27-11ea-80e7-6015fe3fc335.png)

**Comment by albertdugba** [comment]
I have the same problem
