### ISSUE TITLE
Can't Access my Dashboard

### ISSUE THREAD

**Issue by Julia-Casciato** [cypress-io/cypress#24152]
### Current behavior

Unable to access Cypress dashboard.
<img width="1133" alt="Screen Shot 2022-10-06 at 5 23 42 PM" src="https://user-images.githubusercontent.com/8583192/194354140-4cd04a11-2e53-4376-a9bc-faa1b69d41d3.png">

An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command

### Test code to reproduce

Logged into my dashboard earlier, and now I can no longer access it. This is happening across users in my team.

### Cypress Version

9.6.1

### Node version

v15

### Operating System

macOS

**Comment by astone123** [comment]
@Julia-Casciato Sorry for the inconvenience, we've resolved the issue so your team should have access again. Going forward you can track the dashboard status at https://www.cypressstatus.com/. 

If you're still having trouble accessing the dashboard, please contact support@cypress.io. Thanks!
