### ISSUE TITLE
Better CT onboarding experience for projects with ESLint

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#24153]
### What would you like?

Title

### Why is this needed?

When adding Cypress CT to a new project that has ESLint enabled, ESLint will most likely complain about missing global Cypress types. This warnings/errors are made worse when frameworks have eslint integrated into their build pipeline (looking at you `create-react-app` and `vue-cli`).

We have [documentation](https://docs.cypress.io/guides/component-testing/component-test-troubleshooting#ESLint-Global-Errors) around making ESLint happy which boils down to adding and configuring `eslint-plugin-cypress`.

If we could integrate this into the CT onboarding experience, it would reduce the friction a user experiences when getting up and running.

### Other

Ideas:
- Detect if they have eslint installed and install and configure `eslint-plugin-cypress`
- Detect is they have eslint installed and add UI pointing them to docs or a small blurb on how to configure it.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24153?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
It seems like this one isn't defined enough to estimate precisely, estimating based on the two solutions suggested & a guess about what the UI would look like, though this would need to go through design.

**Comment by lmiller1990** [comment]
Agreed with Mark, a bit ambiguous, I'll try to consider that in my vote. You need to find all the common templates that have eslint, see what the DX is like, and then figure out what to do.

If this is too expensive, maybe a generic solution with some docs is more appropriate?

**Comment by lmiller1990** [comment]
None of our *default* templates like Vue CLI or CRA are showing linting errors now - I don't see any work to be done, I'm going to close this. If we want to tackle something similar in a future, I'll file a new issue with a reproduction and more targeted, actionable deliverables.
