### ISSUE TITLE
Race condition using cy.route(...)

### ISSUE THREAD

**Issue by mb1069** [cypress-io/cypress#2416]
### Current behaviour:
Repeated execution in travisCI of test results in varying behaviour due to inconsistent routing of POST request. These tests pass consistently locally, leading me to believe a race condition could be occurring in cypress? Is this due to the way I setup cy.server and cy.route?

See duplicate jobs below;
These passed:
https://travis-ci.org/EBI-Metagenomics/ebi-metagenomics-client/jobs/422592548
https://travis-ci.org/EBI-Metagenomics/ebi-metagenomics-client/jobs/422592642
This one failed:
https://travis-ci.org/EBI-Metagenomics/ebi-metagenomics-client/jobs/422592733

The failing test is named 'Should display success message on successful request', at line 40 of the file here;
https://github.com/EBI-Metagenomics/ebi-metagenomics-client/blob/EMG-644-RT-Integration/cypress/integration/submit.js 

### Desired behavior:
Routing is consistent across executions.

### Versions
Cypress 3.0.1, travisCI

**Comment by jennifer-shehane** [comment]
Have you looked at the video / screenshots of the run? Oftentimes when I am debugging something "randomly" failing in CI - looking at the Command Log (the Cypress commands that ran on the left) is most helpful - comparing the passed run's command log with the failed run's command log usually reveals some minor difference in timing that I wasn't taking into account and can then react to to write a more stable test next time.

**Comment by mb1069** [comment]
Hi Jennifer, 
I've looked at the console below but could not find any usable debugging info. The request is not displayed in the cypress console, though the on-screen error is only displayed on the callback of an AJAX request, so I'm struggling to figure out why this isn't reflected in cypress?

![image](https://user-images.githubusercontent.com/9156542/44864371-6592b800-ac77-11e8-9b89-8c9533cd1688.png)

**Comment by mb1069** [comment]
I'm having the same issue in other tests on my project; is there any reason why the routing setup may be taking place asynchronously?

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?
