### ISSUE TITLE
Run All Specs for E2E

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#24168]
Adds back the ability to run all specs in cypress open mode for End to End testing.

Edit (@lmiller1990) this will be something we incrementally improve over time. The initial implementation will be similar to how it worked in Cypress 9, and focused on supporting End to End testing. Support for Component Testing, and more advanced workflows, will come as the experiment continues and we get feedback.

**Comment by vukobrat** [comment]
Hello fellas, no pushing just asking, any updates about this one? Cheers

**Comment by marktnoonan** [comment]
@vukobrat we expect to start the development work in the next couple of sprints, this epic will move to "in progress" when that work starts.

**Comment by lmiller1990** [comment]
@vukobrat Keep an eye on https://github.com/cypress-io/cypress/pull/24745, should have an experimental feature next release.
