### ISSUE TITLE
Remove test isolation

### ISSUE THREAD

**Issue by santanakrishnan** [cypress-io/cypress#24165]
### What would you like?

I want to turn off test isolation as in the next test block I can continue the test step from the previous block. I want to test my application as a flow like one step after another step. In test isolation we want to visit the page in each test so that the flow of the steps to test are cleared. Can you please make an option to turn off test isolation. 

I am seeing this only from cypress 10+. If you can help mw with this that would be very helpful to test our application

### Why is this needed?

In my application it works like to do configuration of a thing one after the another. So i cant able to visit the page for each test case and also i can not write long test steps in each test block.

**Comment by nagash77** [comment]
@santanakrishnan Can you try using `testIsolation: "legacy"` in your cypress.config.js which should stop visiting blank between tests which should help you accomplish what you are looking to do.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by irensoltan** [comment]
We are facing the same issue. First of all looks like on/off options are not available, it is either legacy/strict.
We are not able to make it work.
