### ISSUE TITLE
Investigate undesirable auto-scrolling behavior

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#24171]
Users are reporting that the command log stops auto-scrolling during test execution unexpectedly. We haven't been able to reproduce this issue reliably, so it has been difficult to investigate. The goal of this issue should be to come up with a way to reliably reproduce the issue and/or document how we might fix it.

Related issues:
https://github.com/cypress-io/cypress/issues/16098
https://github.com/cypress-io/cypress/issues/24015

The command log shouldn't stop auto scrolling during test execution unless it is supposed to (like a user scrolls up in the command log)

@marktnoonan suggested a way to look into this [here](https://github.com/cypress-io/cypress/issues/24015#issuecomment-1264675831)

> I wonder if we could act on this by adding some more guards around what is considered "user scrolling". The root cause of this seems to be that in certain situations, elements being added to the command log, and cypress autoscrolling, get interpreted as user scrolling. A user taking control by scrolling the command log to look at something while a test is running makes sense intuitively and I think it would be really disruptive (to a greater number of users) to change that behavior.

> To tighten this up though, after `user:scroll:detected` we could check if the pointer is over the scroll container in the command log. If it's not, the user most like was not intending to scroll the command log. Keyboard scrolling is unlikely since the Application Under Test almost always grabs keyboard focus.

> So we could skip `temporarilyDisableAutoScrolling` using that or some similar rubric, and only do it when we have extra signals that the user actually triggered the scroll event.

**Comment by egucciar** [comment]
Experiencing this issue in the cypress experimental studio without me having scrolled at all. Just open a new studio, pick a spec, and it does not scroll :( 

Editted to add gif

![2022-11-08 15-29-55 2022-11-08 15_31_51](https://user-images.githubusercontent.com/2848185/200669263-bfb5ed10-4095-4f67-a060-4875b26b4756.gif)

**Comment by emilyrohrbough** [comment]
@AtofStryker & I have identified the (or one) cause for the Autoscrolling bug. If you scroll & click on a command while tests are running, autoscroll is disabled for the user. The only way to re-enable it is to know you have to turn it back on in the preferences.

1. Autoscroll should always reset to the user’s preferences on test restart/refresh - the user preferences should not be updated magically. This should only be changed/set by the user.
2. @AtofStryker  (and prob many users) was not aware that Autoscroll is a user preference that could be toggled at all, so when it was magically disabled, it appears to be completely broken behavior.
