### ISSUE TITLE
@cypress/react18@1.1.0 does not contain a fix that is in its changelog

### ISSUE THREAD

**Issue by hiebj** [cypress-io/cypress#24174]
### Current behavior

`@cypress/react18@1.1.0` does not contain the fix implemented in #23360.

### Desired behavior

According to [the changelog](https://github.com/cypress-io/cypress/blob/develop/npm/react18/CHANGELOG.md#cypressreact18-v110-2022-10-06), it should.

### Test code to reproduce

`npm install @cypress/react18@1.1.0`

Look at the code in `node_modules/@cypress/react18/dist/cypress-react.cjs.js:582`, or in `cypress-react.esm-bundler.js:555`. Neither contains the code that was included in #23360, and which can be [seen here in `master`](https://github.com/cypress-io/cypress/blob/master/npm/react18/src/index.ts#L20).

### Cypress Version

10.8.0

### Node version

14.19.1

### Operating System

macOS 12.4

**Comment by hiebj** [comment]
There appear to be 10 separate entries in the [changelog](https://github.com/cypress-io/cypress/blob/develop/npm/react18/CHANGELOG.md#cypressreact18-v110-2022-10-06) for `1.1.0`. Is that normal?

I also do not see #23360 in [this list of commits](https://github.com/cypress-io/cypress/compare/@cypress/react18-v1.0.1...@cypress/react18-v1.1.0)

**Comment by nagash77** [comment]
Hi @hiebj , thanks for creating an issue around this problem.  We currently have this issue that is already in the teams backlog - https://github.com/cypress-io/cypress/issues/24112.  I am going to close this issue as a dupe.  Feel free to comment if you feel that is in error and we can address your feedback

**Comment by astone123** [comment]
@hiebj We just released `@cypress/react18@1.1.1`. If you look at that version, you should see the expected changes. There's an issue with our release of these packages that I'm currently working through. I'm in the process of fixing the changelog as well. 

This new version will be bundled with the next release of Cypress. Thanks for reporting this
