### ISSUE TITLE
safari webkit fails to interact with iframes

### ISSUE THREAD

**Issue by zecarrera** [cypress-io/cypress#24197]
### Current behavior

Safari webkit is unable to interact with iframes

### Desired behavior

Spec should be able to interact with elements within iframes

### Test code to reproduce

I've created a public repo, using the iframe example from the example-recipes repo
https://github.com/zecarrera/cypress-10-example-recipes-iframe

### Cypress Version

10.9.0

### Node version

v16.10.0

### Operating System

macOS 12.6

**Comment by nagash77** [comment]
@zecarrera iframes currently are not supported for any browsers in Cypress.  Please follow this issue for updates https://github.com/cypress-io/cypress/issues/136.  I am closing this issue as expected behavior at this point.
