### ISSUE TITLE
unable to launch tests runner window

### ISSUE THREAD

**Issue by Dan5123** [cypress-io/cypress#24199]
### Current behavior

I am unable to launch cypress test runner, I have followed many different routes to open and install cypress but no luck, here I am raising issue to see if I can get some support.
I can not configure proxy or even go to settings since all these options are in test runner window which I am unable to get to.

![1](https://user-images.githubusercontent.com/106591615/195104202-97d9d0f8-2ddc-4c58-8761-8ea9c7aad876.png)
![2](https://user-images.githubusercontent.com/106591615/195104228-29a26f1b-672c-429e-9f04-0c5541233a63.png)
![3](https://user-images.githubusercontent.com/106591615/195104250-0e6c2bb9-e204-4413-9195-82fcc7046a17.png)
![5](https://user-images.githubusercontent.com/106591615/195104454-a266afc8-7bb7-4110-9ed2-566ad70ce373.png)
![config](https://user-images.githubusercontent.com/106591615/195104472-1b14014d-329a-4ee5-971b-5bc7d50567f6.png)

### Cypress Version

10.9.0

### Node version

18.2.0

### Package Manager

npm

### Package Manager Version

8.9.0

### Operating system

Windows

### Operating System Version

windows 10, version 21h1

**Comment by AtofStryker** [comment]
Hi @Dan5123 . Thank you for opening an issue. Would you be able to provide a reproduction repository that I can run on my windows machine to see if I can reproduce the issue you are seeing?

**Comment by Dan5123** [comment]
Hello @AtofStryker  I strongly believe this behaviour has something to do with limited network permissions in the company laptop and proxy settings, because I was not able to reproduce the same error in personal laptop.

I would like to close this issue (or leave it open) if it does not get solve by dev ops team I will come back and open this issue again here.
