### ISSUE TITLE
cy.screenshot() has impact on test results, intercepted aliases, work as cy.wait(500)

### ISSUE THREAD

**Issue by rdwentmp** [cypress-io/cypress#24202]
### Current behavior

During using cy.screenshot() in method updateScope between cy.intercept() and cy.wait() the returned alias request in assertUpdateScope alias for that update is correct. The issue occur after removing cy.screenshot from that method, then the returned aliases are wrong and the assertion fails on response body.
In our case cy screenshoot works as cy.wait(500) which mean screenshoot may have impact on test results
The updateScope method is run couple times and for each should return a new alias with different request body

```
updateScope(scopeIndex: number, dftStdHours: string) {
    this.interceptBeforeAddEngDftHours()
    this.getAdditionalActivityDftStdHoursValueInput(scopeIndex)
      .type(dftStdHours)
      .should('have.value', dftStdHours)
    this.blurElementFocus()
    cy.screenshot()
    this.assertUpdateScope(dftStdHours)
    cy.waitMessageNotExist()
  }
```
without cy.screenshoot()
<img width="643" alt="image" src="https://user-images.githubusercontent.com/33515840/195115065-196789c9-bb08-4517-8337-25ee63ff9f93.png">

with cy.screenshoot()
<img width="635" alt="image" src="https://user-images.githubusercontent.com/33515840/195114569-4a1912fa-0cb8-4008-8c94-239dc150861b.png">

### Test code to reproduce
```
updateScope(scopeIndex: number, dftStdHours: string) {
    this.interceptBeforeAddEngDftHours()
    this.getAdditionalActivityDftStdHoursValueInput(scopeIndex)
      .type(dftStdHours)
      .should('have.value', dftStdHours)
    this.blurElementFocus()
    cy.screenshot()
    this.assertUpdateScope(dftStdHours)
    cy.waitMessageNotExist()
  }
```
### Cypress Version

v10.6.0

### Node version

v14.18.2

### Operating System

macOS 12.3.1

**Comment by AtofStryker** [comment]
Hi @rdwentmp. Thank you for opening an issue. Would you be able to provide a full reproduction example that I can run in order to reproduce the issue? The examples provided look to contain functions that are not defined.

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
