### ISSUE TITLE
Support For Chrome Native Messaging

### ISSUE THREAD

**Issue by shadhaval** [cypress-io/cypress#2421]
Hi All,
I am new to Cypress and find it very useful for testing my javascripts.
I have created a chrome extension and I am using Chrome Native Messaging to communicate with my Chrome Extension with my Host.

I want to know whether Cypress uses Chrome Native Messaging to perform automation on Chrome Browser or not.

Link to get information about Chrome Native Messaging : https://developer.chrome.com/apps/nativeMessaging.

Also if possible please give the code-snippets for the same.

**Comment by srbagg** [comment]
Hi Cypress team,
Any update on support of Native messaging?

**Comment by AgustinReyes** [comment]
Hi team, 

Anyone knows if there is an ETA for this?

Thanks!

**Comment by jennifer-shehane** [comment]
This issue is still in the 'proposal' stage, which means no work has been done on this issue as of today, so we do not have an estimate on when this will be delivered.

**Comment by jennifer-shehane** [comment]
Since this has not gotten a lot of interest over the years, we’ll close this as not planned.
