### ISSUE TITLE
i cant able to preserve the cookies and session storage as preserve cookies are deprecated. Any idea how to achieve it without cy.session.

### ISSUE THREAD

**Issue by santanakrishnan** [cypress-io/cypress#24221]
### What would you like?

i cant able to preserve the cookies and session storage as preserve cookies are deprecated. Any idea how to achieve it without cy.session.

**Comment by emilyrohrbough** [comment]
@santanakrishnan Can you share why `cy.session` does not work for you?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
