### ISSUE TITLE
Module not found: Error: Can't resolve '@cypress/xpath'

### ISSUE THREAD

**Issue by JGarnettMtab** [cypress-io/cypress#24224]
### Current behavior

Followed instructions for installing `@cypress/xpath` included `require('@cypress/xpath')` in support file. Encountered error running tests in Electron (but browser isnt really relevent):

```
Error: Webpack Compilation Error
Module not found: Error: Can't resolve '@cypress/xpath'
```

### Desired behavior

Update [package.json](https://github.com/cypress-io/cypress/blob/develop/npm/xpath/package.json) in @cypress/xpath to export correctly

### Test code to reproduce

1. npm install -D @cypress/xpath
2. add `require('@cypress/xpath');` to support file
3. run tests

### Cypress Version

10.6.0

### Node version

v16.14.0

### Operating System

macOS 12.6

**Comment by jordanpowell88** [comment]
Hey @JGarnettMtab are you able to provide a link to your repo or a Gist?

**Comment by JGarnettMtab** [comment]
@jordanpowell88 Thank you for taking a look at this issue, the repo unfortunately is private.  I can set up a minimal example if needed.

Examining the node packages installed though, in the package.json for @cypress/xpath `main` is set to `scripts` and `scripts` is not supplied in the package.

![Screenshot 2022-10-13 at 14 26 08](https://user-images.githubusercontent.com/35131716/195609921-584c0b64-163c-454a-ae4e-de81984790fd.png)

**Comment by olga-fluence** [comment]
I'm also facing the same issue, following steps in readme

**Comment by adyz** [comment]
Same here and it looks like there is no way to install an older version.

**Comment by git-randy** [comment]
I followed the README and installed @cypress/xpath
Then I added `require(@cypress/xpath)` in my `cypress/support/e2e.js` support file

I get error `Module not found: Error: Can't resolve '@cypress/xpath' in /path/to/cypress/support`

I have this in my package.json
`{
  "devDependencies": {
    "@cypress/xpath": "^2.0.2",
    "cypress": "^10.10.0"
  }
}`

**Comment by alexmm9528** [comment]
Hello, same issue here, Cypress version 10.10 and installing in a "clean" project, following the official tutorial

**Comment by joh-kepler** [comment]
Hello, the same one. Cypress 9.7.0, a "clean" project, installing following the official tutorial. Error same : "Module not found: Error: Can't resolve '@cypress/xpath' in" then path to "cypress/support" folder

**Comment by hugohhernandez76** [comment]
I was able to resolve the issue by:

1. ran command npm install -D cypress-xpath
2. in the folder cypress/support/e2e at the top of the file typed require('cypress-xpath'); 
![Screen Shot 2022-10-22 at 9 17 10](https://user-images.githubusercontent.com/84982212/197344129-3dca97f8-4c17-497a-8f17-96f45348d008.png)

3. and at the cypress/e2e in my test at the top I placed the following command /// <reference types="cypress-xpath" />
![Screen Shot 2022-10-22 at 9 18 00](https://user-images.githubusercontent.com/84982212/197344139-5e5e9445-400f-464a-8838-7807aabeb9e3.png)

**Comment by jpcampos24** [comment]
I'm facing this issue as well I think the reason is the plugin is no being storing the package on /node_modules folder so the e2e.js doesn't find the data

**Comment by jpcampos24** [comment]
@hugohhernandez76 solution is good in case you need to install the previous version

**Comment by hugohhernandez76** [comment]
> @hugohhernandez76 solution is good in case you need to install the previous version

It is working for me in the 10.10 version 
![Screen Shot 2022-10-24 at 15 50 38](https://user-images.githubusercontent.com/84982212/197626911-d370aaa8-e848-41b4-a870-020489f70134.png)

**Comment by jpcampos24** [comment]
Yes! I mean, you installed the previous cypress-xpath version, we're facing this issue trying to install the latest 2.0.2. But while they fix this issue we can install the previous version with your steps this could help to @adyz in the meantime

**Comment by hugohhernandez76** [comment]
> Yes! I mean, you installed the previous cypress-xpath version, we're facing this issue trying to install the latest 2.0.2. But while they fix this issue we can install the previous version with your steps this could help to @adyz in the meantime

Oh yes I guess I did not understand your post. Yes this is only a temp fix to continue working with xpaths

**Comment by Diogoazevedo235** [comment]
I solved it by putting the following require in e2e.js
`require('@cypress/xpath/src');`

**Comment by djogoaz** [comment]
e2e.js
`require('@cypress/xpath/src');`

...spec.cy.js
`/// <reference types="@cypress/xpath" />`

**Comment by atul2909** [comment]
@cypress-app-bot - when it's expected in main/master branch??

**Comment by Malini081** [comment]
@cypress-app-bot  i'm using 12.7.0, installing cypress xpath is still throwing error. 
also tried downgrading to cypress 10.0.0, still didnt work
when can we expect the fixes to be merged.?
please confirm
