### ISSUE TITLE
Cypress not loading test files.

### ISSUE THREAD

**Issue by joseph-luketelo** [cypress-io/cypress#24222]
### Current behavior

When I try to run cypress using `npx cypress open` I get the attached screen which does not load the tests but keeps on spinning forever.
![Screenshot from 2022-10-12 11-35-54](https://user-images.githubusercontent.com/15190671/195293721-71f75523-3049-4788-886a-cbcd51e073f9.png)
What might be the issue?

### Cypress Version

10.3.1

### Node version

10.19.0

### Package Manager

npm

### Package Manager Version

6.14.4

### Operating system

Linux

### Operating System Version

20.04.3 LTS

**Comment by nagash77** [comment]
Hello @joseph-luketelo Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by joseph-luketelo** [comment]
@nagash77  How do I run in debug mode?

**Comment by nagash77** [comment]
Try following [these instructions](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs)

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
