### ISSUE TITLE
cypress: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vish-pandey** [cypress-io/cypress#24220]
### Current behavior

We are getting maximum call stack size exceeded error while running cypress cases from the terminal on my local using docker image.
![Uploading Screenshot 2022-10-12 at 12.56.53 PM.png…]()

### Test code to reproduce

N/A

### Cypress Version

6.9.1

### Node version

v17.4.0

### Operating System

macOS 12.6

**Comment by Narretz** [comment]
You should update to the latest version, Cypress 10.10 and see if the error persists.

**Comment by nagash77** [comment]
@vish-pandey As @Narretz suggested, please upgrade to the latest Cypress version and see if the problem persists.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
