### ISSUE TITLE
New cy.origin handling causes issues with urls containing basic auth

### ISSUE THREAD

**Issue by DotCoyote** [cypress-io/cypress#24225]
### Current behavior

When opening an url with cy.origin() that contains basic auth information, the cookie/session handling results in a failing login. It worked well before v10.10.0.

### Desired behavior

Well... being able to handle basic-auth-urls

### Test code to reproduce

```ts
Cypress.Commands.add('loginBackend', (username = Cypress.env('userAdmin'), password = Cypress.env('passwordAdmin')) => {
    cy.session([username, password], () => {
        cy.origin(
            `https://${Cypress.env('adminBasicAuthUser')}:${Cypress.env('adminBasicAuthPassword')}@${Cypress.env(
                'adminUrl',
            )}/`,
            {
                args: {
                    username,
                    password,
                },
            },
            ({ username, password }) => {
                cy.visit('/');
                cy.get('input#auth_username').type(username);
                cy.get('input#auth_password').type(password);
                cy.get('button[type="submit"]').click();

                cy.get('.login-box').should('not.exist');
            },
        );
    });
});
```

### Cypress Version

10.10.0

### Node version

16.14.0

### Operating System

macOS 12.6

**Comment by user1m** [comment]
Can confirm similar experience - had to downgrade to 10.8.0

**Comment by AtofStryker** [comment]
Hi @DotCoyote & @User1m . I am sorry to hear you all are having some issues with basic auth. We changed the implementation of the origin that is used to interact with the AUT in this case to be an exact origin match. I wonder if that is affecting you both here. Are either of you able to provide a full reproduction , and if not, are you able to tell me if the url you are visiting contains a subdomain?

**Comment by DotCoyote** [comment]
Yeah, we're also using a subdomain. Unfortunately, I can't provide a test-repo to that project. I will see, if I can setup a dummy-project

**Comment by AtofStryker** [comment]
@DotCoyote I completely understand. If I get some time today, I can try to throw something together that showcases the problem

**Comment by AtofStryker** [comment]
@DotCoyote I put together a quick reproduction repository [here](https://github.com/AtofStryker/cypress-issue-24225). I added a test in there that leverages the [`cy.visit` basic auth api](https://docs.cypress.io/api/commands/visit#Add-basic-auth-headers) that might work for you. Can you let me know if that is the case?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
