### ISSUE TITLE
Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise

### ISSUE THREAD

**Issue by parmarravi** [cypress-io/cypress#24238]
### Current behavior

I am trying to check the value from the Custom Error Text on the Ui. And once the condition gets failed I am capturing the screenshot.

But due to the Cypress Error, the screenshot code is not getting triggered. Is there any alternative way to achieve a similar task or fix the Cypress Error issue?

### Desired behavior

We should not get Cypress Command Error. As we are only comparing the values this should only fail the test which will also trigger the below code. Due to the error, it looks like the developer has not coded correctly which is causing cypress to crash.

```
 Cypress.on("fail", (err, runnable) => {
            console.log("invalid", err);
            cy.get("#form-customer-mobile").screenshot("login/customer-pan-pattern-entered");
            return false;
        });
```

### Test code to reproduce

```
 Cypress.on("fail", (err, runnable) => {
            console.log("invalid", err);
            cy.get("#form-customer-mobile").screenshot("login/customer-pan-pattern-entered");
            return false;
        });


      cy.get(".error-text").invoke("text").should("contain", "Please enter a valid dasd PAN card number"); 
```

### Cypress Version

10.6.0

### Node version

v14.18.3

### Operating System

Ubuntu 20.04.5 LTS

### Debug Logs

```shell
invoke.text()

assert expected Please enter a valid PAN card number to include Please enter a valid dasd PAN card number CypressError

Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

cy.invoke()

The cy command you invoked inside the promise was:

cy.get()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.Learn more
```

**Comment by warrensplayer** [comment]
@parmarravi The stack trace for this error is pointing you in the wrong direction.  What the error message is actually complaining about is the `cy.get()` call in the custom error handler.  You are experiencing the same issue reported here: https://github.com/cypress-io/cypress/issues/1217. Cypress automatically takes a screenshot after failures.  Try to use the screenshot API documented here [on.cypress.io/after-screenshot-api](https://on.cypress.io/after-screenshot-api) to customize any behavior you need to change for the screenshot.
