### ISSUE TITLE
Subfolder with dots in their name are recognized as spec files, not as folders

### ISSUE THREAD

**Issue by testquantilope** [cypress-io/cypress#2423]
### Current behavior:

If folders contain a dot `.` Cypress recognizes subfolders as spec files in the application as well as in CI.

![image](https://user-images.githubusercontent.com/35334883/44914986-0645ae00-ad32-11e8-9fcd-724d5f0d8e75.png)
In this screenshot the yellow highlighted lines are folders within my integration folder.

On CI, cypress attempts to run these:

![image](https://user-images.githubusercontent.com/35334883/44915126-7bb17e80-ad32-11e8-9bce-650a4609b7e5.png)

### Desired behavior:

Folders should be recognized as such, even if the name contains a dot.

### Steps to reproduce:

In your integration folder, create a subfolder containing a dot, e.g. `1.1_General`

### Versions

Issue found on cypress 3.1.0

### Workaround
Rename folders not to contain dots.

**Comment by chrisbreiding** [comment]
Confirmed this as a bug. I think this could potentially be fixed by setting `nodir: true` [when we glob for spec files](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/specs.coffee#L47).
