### ISSUE TITLE
Cypress 10 shows "The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()"

### ISSUE THREAD

**Issue by imaginekhalid** [cypress-io/cypress#24246]
### Current behavior

In the cypress.config.js , I'm trying to register tasks / plug in events and set my env configuration exactly as documented on their guide.

However, when trying to use "on" inside setupNodeEvents I'm getting the error in the title about needing to register it.

Also, to note when passing both arguments (on, config), the config file does not pick up the env variable. Only when I put config first or config by itself, do the env variables pass.

Also, my tasks are properly coded inside the test classes. I know this because they work just fine for previous versions of cypress 9 but I can share them if someone thinks that's where the

### Desired behavior

Want cypress tasks to be registered and working

### Test code to reproduce

/// <reference types="cypress" />
const { defineConfig } = require('cypress');

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on,config) {
      
      if (config.env == undefined) {
        return {
          baseUrl: "intentionally blank",
          env: {
            env: "test",
            schedulerBaseUrl: "intentionally blank",
            signInUrl: "intentionally blank",
            enableAccessibility: true,
            takeScreenShot: false,
            suites: "",
          },
        };
      }
      else if (config.env == 'development') {
        return {
          baseUrl: "blank",
          env: {
            environment: "development",
            schedulerBaseUrl: "intentionally blank",
            signInUrl: "intentionally blank",
            enableAccessibility: false,
            takeScreenShot: false
          },
        }
      }
      
      on('task', {
        log(message) {
          console.log(message)
          return null
        },
        table(message) {
          console.table(message)
          return null
        }
      })

      on('before:browser:launch', (browser, launchOptions) => {
        if (browser.name === 'chrome' && browser.isHeadless) {
          launchOptions.args.push('--disable-gpu');
          launchOptions.args.push('--disable-dev-shm-usage');
          launchOptions.args.push('use-fake-device-for-media-stream');
          return launchOptions;
        }
      });
    },
    chromeWebSecurity: false,
    screenshotOnRunFailure: false,
    trashAssetsBeforeRuns: true,
    numTestsKeptInMemory: 0,
    video: true,
    videoCompression: false,
    enableAccessibility: false,
    takeScreenShot: false,
    defaultCommandTimeout: 10000,
    execTimeout: 500000,
    pageLoadTimeout: 500000,
    retries: {
      runMode: 1,
      openMode: 0
    },
    blockHosts: [
      "*intentionally blank"
    ],
    redirectionLimit: 199,
    projectId: "intentionally blank",
  }
})
require('@applitools/eyes-cypress')(module);

### Cypress Version

10.8.0

### Node version

16.14.2

### Operating System

macOS 12.4

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Please provide a reliable reproduction that includes your `setupNodeEvents` code in your Cypress config as well as one test that contains the `cy.task` call that is failing.

Also, what "guide" are you referring to when you said:

> In the cypress.config.js , I'm trying to register tasks / plug in events and set my env configuration exactly as documented on their guide.

Can you provide a link to that?

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by amehta265** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by 596050** [comment]
I'm getting the same error and trying to use `"cypress-autorecord": "^3.1.2"` plugin.

It gives this error:
<img width="535" alt="Screenshot 2022-12-15 at 19 46 58" src="https://user-images.githubusercontent.com/19141517/207953015-7bd44ec9-0d9e-4436-ade1-357154a2eb16.png">


![Screenshot 2022-12-15 at 19 47 50](https://user-images.githubusercontent.com/19141517/207953280-a2ecb273-267b-4209-b14a-7c88205b6b1b.png)

**Comment by nagash77** [comment]
Hi @596050 , can you provide a reproducible example?  If so I will reopen this issue for investigation.

**Comment by shama1995** [comment]
@nagash77 
I am also getting same error
cypress version - 13.2.0
node version - 18.15.0

Error is like below:
**The task "excelToJsonConverter' was not handled in SetUpNodeEvents. Following tasks are registered: isFileExist, findFiles, excelToJsonConverter, log.readFile
Fix this in your SetUpNodeEvents**


Steps to Reproduce:
run _npm install convert-excel-to-json_

*****************env.config******************

```js
e2e: {
 setupNodeEvents(on, config) {
on('task', tasks);  

 on('task',{
        excelToJsonConverter(filePath)
        {
          const result = excelToJson({
          source: fs.readFileSync(filePath) // fs.readFileSync return a Buffer
        });
        return result;
        }
  })
return require(./cypress...xxxxxxx.../index.js)
```

*************spec file**************

```
const filePath = Cypress.config("fileServerFolder")+"/cypress/downloads/test.xlsx"
    cy.task('excelToJsonConverter',filePath).then(function(result)
    {
      cy.log(result.data[1].A);

    })**
```

**Comment by nagash77** [comment]
Hi @shama1995 please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
