### ISSUE TITLE
[Feat] Add option to disable writing bundling

### ISSUE THREAD

**Issue by Toxicable** [cypress-io/cypress#2425]
### Current behavior:
Cypress will always write a bundle even if the files require no pre processing.

### Desired behavior:
Option to disable it so that Cypress's input is your raw files
The limitation is that Cypress will not be able to take TS files (or other files that require pre-processing)

The reason for this are the same as stated in this issue: #1281 

### Versions
This started happening on Cypress v3.1.0
Everything was fine on v3.0.3

Ubuntu 16.04
Chrome 68

**Comment by chrisbreiding** [comment]
You can essentially disable any preprocessing/writing of files with the [watch preprocessor](https://github.com/cypress-io/cypress-watch-preprocessor).

**Comment by Toxicable** [comment]
Ahhhh yes! I think you're right about that, thanks for the heads up.
