### ISSUE TITLE
After upgrade I could not initially figure out how to run tests, still can't actually

### ISSUE THREAD

**Issue by tomachinz** [cypress-io/cypress#24260]
### Current behavior

The big "run" button seems to have disappeared in this version upgrade. Where I can see the browser doing it's thing.

If I click a test, it runs, and the terminal seems to indicate a run, but it not show in the runs list. 

I will confess I do not use the program as often as I should. Anyhow no tests done first and second days. 

But I re-open ed it, found the strange [command] icon, saw the help it says [r] to  run, to I pressed [r] and no tests ran. So still stuck. Probably a UI thing. 

### Debug logs

```Text
tom@putin:~/funk_symlink$ npm run test

> funk.co.nz@1.0.3 test
> CYPRESS_BASE_URL=https://cypress:robot@www.funk.co.nz cypress open

GET /__/ 200 135.721 ms - -
GET /__/assets/polyfills.dabe60b8.js 200 7.940 ms - -
GET /__/assets/index.42ea0b38.css 200 14.185 ms - -
GET /__/assets/index.fcb7159a.js 200 13.668 ms - -
GET /__cypress/runner/cypress_runner.css 200 1.288 ms - -
GET /__/assets/Specs.9d386832.js 200 4.703 ms - 485
GET /__/assets/CreateSpecModal.315eb5ce.css 200 3.045 ms - 368
GET /__/assets/Index.4a5d64fb.css 200 3.582 ms - -
GET /__/assets/Index.7617f0bc.js 200 2.908 ms - -
GET /__/assets/ResultCounts.fca65b30.js 200 2.346 ms - -
GET /__/assets/CreateSpecModal.572b4416.js 200 2.606 ms - -
GET /__/assets/user-outline_x16.8d0edc3e.js 200 0.754 ms - -
GET /__/assets/SpecPatterns.9c16fff4.js 200 1.567 ms - -
GET /__/assets/settings_x16.4201d9cf.js 200 0.751 ms - -
GET /__/assets/cypress_s.29af549a.png 200 0.550 ms - 4425
GET /__/assets/chromium.8e77d142.svg 200 2.828 ms - 517
GET /__/assets/electron.fb07f5cc.svg 200 4.743 ms - -
GET /__/assets/firefox.9be61e66.svg 200 2.650 ms - -
GET /__cypress/runner/cypress_runner.js 200 1.758 ms - -
GET /avatar/52f93a3995749453c8bc28849414357a?size=48&default=mm 200 5575.309 ms - -
GET /__/assets/Runs.b6df4180.css 200 4.059 ms - 707
GET /__/assets/CloudConnectButton.cf75de6d.js 200 1.224 ms - -
GET /__/assets/refresh_x16.ae860103.js 200 0.734 ms - -
GET /__/assets/Runs.5683a7f2.js 200 2.081 ms - -
```

### Cypress Version

10.9.0

### Node version

v16.17.0

### Package Manager

npm

### Package Manager Version

8.19.2

### Operating system

Linux

### Operating System Version

Linux putin 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Other

New version looks amazing. But last time I checked (on the old version) I could do 'npm run test' and they'd start running straight away.

**Comment by AaronVikta** [comment]
I think the big **Run all** button got removed some versions before now, for me I had to import the other spec files into the a single spec file say **all.cy.js** and then I ran the **all.cy.js**

**Comment by tomachinz** [comment]
OK, well I guess i better get with the times and create this index type of file. Maybe this is a feature request not a bug then. Anyhow, generally, Cypress has impecable ease of use. Am running `npm install -D cypress@10.10.0` presently

**Comment by nagash77** [comment]
As @AaronVikta mentioned we did remove the Run All button several versions ago.  We are currently engaging with customers to determine if and how this functionality could come back in the future in this ticket https://github.com/cypress-io/cypress/issues/24168
