### ISSUE TITLE
cy.state('runnable')._currentRetry always returns 0 if called from before hook

### ISSUE THREAD

**Issue by nonkor** [cypress-io/cypress#24273]
### Current behavior

`cy.state('runnable')._currentRetry` always returns 0 if called from before hook (ignoring the current attempt). In comparison, in `it` section it returns the correct attempt number.

I consider this as a bug because I need to differentiate sessions between attempts – `it` may contain mutable actions that would make the current session invalid for new attempts. I am intentionally not relying on the `validate` method in this case as my `session` function is common for most specs and it's placed in the login command (as it's recommended [in the doc](https://docs.cypress.io/api/commands/session#Where-to-call-cy-session)). I don't want to define dozens of unnecessary sessions just to track minor differences between user states in different specs, I'd prefer to save them as spec name + attempt number.

![image](https://user-images.githubusercontent.com/6322897/196179933-9da3c800-3df3-4c9c-8d48-9641dcf6d49e.png)

### Desired behavior

`cy.state('runnable')._currentRetry` should return correct attempt number even if called from before hook

### Test code to reproduce

1. Write errored spec.
2. Set some retry number for it.
3. Log currentRetry from before hook and from the test body.
4. Check if numbers are equal.

### Cypress Version

10.9.0

### Node version

16.14.2

### Operating System

macOS 12.4

**Comment by emilyrohrbough** [comment]
@nonkor The reason you are seeing this behavior is that the `beforeEach` hook is it's own runnable, separate from the Test runnable and we are only incrementing the test runnable's `_currentRetry` count when Cypress reattempts to run the test. I agree this is a bit confusing, and aligning this would be helpful for debugging and determining the retry attempt.

You can work around this in your hook with:
```js
Cypress.state('runnable').ctx?.currentTest
```

> I consider this as a bug because I need to differentiate sessions between attempts – it may contain mutable actions that would make the current session invalid for new attempts.  I am intentionally not relying on the validate method in this case

I would like to understand why you need to differentiate your sessions when a test is retired through... can you expand on your use-case? Even when a `validate` function is not leveraged, your test should not be altering the session that is created and persisted between tests and test retries. The restored session is static.

**Comment by nonkor** [comment]
@emilyrohrbough thanks for answering!
So, I have the next situation. There is a login method wrapped under `session`. Smth like:
```
function createUser () {
...
}

Cypress.Commands.add('createUserAndLoginViaApi', (...) => {
  cy.session(helper.sessionId(), createUser)
  // I am going to add validation to check authorization but it's not important here.
})

class Helper {
  sessionId() {
    return Cypress.spec.baseName + ': attempt #' + cy.state('runnable').toString()
  }
}


```

I have to use this user (which means sessions) in all tests in the current file. But let's say in the **test** body we have some actions that mutate the user state and make it unreliable for this test (but it's ok for leftovers). Add a product to the basket, for example. If my test fails **after** this line - a new retry wouldn't help, as the previously created session will be used - but now adding to the basket wouldn't happen (this item is added already).

What I want - is to create a unique session per spec to ensure a new retry will start with a new session. I use specName as it allows me to put this line in cypress command file and don't bother to create something unique on a spec level (like user email which should be defined upfront before calling `createUserAndLoginViaApi`).

I hope I explained the issue :)

BWT, `Cypress.state('runnable').ctx?.currentTest` returns the same object for retries and cannot be used as unique identifier for every retry. `Cypress.spec.baseName + ': attempt #' + cy.state('runnable').ctx?.currentTest` is the same for all of them.

**Comment by emilyrohrbough** [comment]
> I have to use this user (which means sessions) in all tests in the current file. But let's say in the test body we have some actions that mutate the user state and make it unreliable for this test (but it's ok for leftovers). Add a product to the basket, for example. If my test fails after this line - a new retry wouldn't help, as the previously created session will be used - but now adding to the basket wouldn't happen (this item is added already).

I'm not sure I am completely following your use-case. Can you expand a bit more? Maybe share pseudo code on how you have this setup? The sessions command should be clearing the current session and re-applying the saves sessions state at the beginning of each test, so a unique session id shouldn't be needed. Is this action to move an item to the basket happening during validation? Or is your test altering the the active sesison state?

> BWT, Cypress.state('runnable').ctx?.currentTest returns the same object for retries and cannot be used as unique identifier for every retry. Cypress.spec.baseName + ': attempt #' + cy.state('runnable').ctx?.currentTest is the same for all of them.

If you look at the object attributes, you can use `_currentRetry` to pull the current retry count.
```js
    describe('demo', { retries: 2 }, () => {
      beforeEach(function () {
        cy.log(Cypress.state('runnable').ctx?.currentTest._currentRetry)
      })

      it('always fails', () => {
        cy.get('body).should('not.exist')
      })
  })
```

**Comment by emilyrohrbough** [comment]
@nonkor any updates?

**Comment by emilyrohrbough** [comment]
Closing this issue. Exposing the current retry via Cypress.currentRetry (#25239) will make this information easier to access.
