### ISSUE TITLE
10.10.0 introduced issues with self signed certificates in chain for connection with dashboard api.

### ISSUE THREAD

**Issue by Jenson3210** [cypress-io/cypress#24298]
### Current behavior

We're seeing this on connection to dashboard api. 
We have self signed corporate certificates in between. 
In 10.10.0 I get 
```
We encountered an unexpected error talking to our servers.
We will retry 3 more times in 30 seconds...
The server's response was:
RequestError: Error: self signed certificate in certificate chain
We encountered an unexpected error talking to our servers.
...(retries logged)
```

Also `https.get('https://api.cypress.io/', res => console.log(res.statusCode))` works (I get same 404 as browser) via regular node terminal (added company certificates through NODE_EXTRA_CA_CERTS env variable)

When our vpn is disabled (hence no man-in-middle self signed corporate certificates) it is working fine.

### Desired behavior

In 10.9.0 everything is fine and self signed certificates are validated by own CA.

### Test code to reproduce

I could work on an example. 
But just doing a https call in startup of tests towards dashboard is failing.
So startup icw dashboard api link on company netwrok with self signed certificates

### Cypress Version

10.10.0

### Node version

 v16.15.0

### Operating System

MacOS 12.6

**Comment by mschile** [comment]
@Jenson3210, thanks for opening this issue. Starting with Cypress 10.10.0, we are now verifying the dashboard cert for API calls from the app. I believe you'll need to either set `NODE_OPTIONS=--use-openssl-ca` or add the self-signed certs with the `NODE_EXTRA_CA_CERTS` env variable.

**Comment by Jenson3210** [comment]
@mschile both options I tried. As mentioned, `https.get('https://api.cypress.io/', res => console.log(res.statusCode))` is working fine in node “terminal” because I added self-signed cert’s through `NODE_EXTRA_CA_CERTS` env variable.

**Comment by Jenson3210** [comment]
Sorry for closing (phone issue)

**Comment by siglp** [comment]
We have the same problem. Our test ENV is behind transparent proxy :-(.

`We encountered an unexpected error talking to our servers.`
`We will retry 3 more times in 30 seconds...`
`The server's response was:`
`RequestError: Error: self signed certificate in certificate chain`
`We encountered an unexpected error talking to our servers.`
`We will retry 2 more times in 1 minute...`
`The server's response was:`
`RequestError: Error: self signed certificate in certificate chain`
`We encountered an unexpected error talking to our servers.`
`We will retry 1 more time in 2 minutes...`
`The server's response was:`
`RequestError: Error: self signed certificate in certificate chain`
`We encountered an unexpected error talking to our servers.`
`We will retry 0 more times in ...`
`The server's response was:`
`RequestError: Error: self signed certificate in certificate chain`
`We encountered an unexpected error talking to our servers.`
`The --group flag you passed was: Edge`
`The server's response was:`
`RequestError: Error: self signed certificate in certificate chain`
`Cypress could not execute tests`
`Could not find Cypress test run results`
`Cypress test returns exit code: 1`

**Comment by mschile** [comment]
@Jenson3210, thanks for the update. I was also able to recreate the issue locally using a proxy with a self-signed cert. I will discuss with the team on how we want to proceed.

**Comment by mschile** [comment]
It appears Electron does NOT honor the [NODE_EXTRA_CA_CERTS](https://github.com/electron/electron/issues/10257) env variable.

I am going to revert the change that introduced verifying the cert until we come up with a solution that also works for self-signed certs.
