### ISSUE TITLE
Potentially catch global `onunhandledrejection` as errors?

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#243]
Currently Cypress taps into `window.onerror` for failing tests which have script errors.

But we don't tap into `onunhandledrejection` events. I believe we should, but enable this to be configurable.

**API Idea:**

```
Cypress.Errors.listenForUncaughtExceptions(false)
```

```
Cypress.Errors.listenForUnhandledRejections(false)
```

**Comment by bahmutov** [comment]
It would be nice to turn off the Cypress global exception handler per test.
For example, we have our own exception handler that sends the errors to the remote crash reporting server. We could write an e2e test to make sure it works as expected. We can
stub the server route and then raise an error in the window's context on purpose.
```js
cy.window()
        .then(win => {
          function raise () {
            throw new Error(`E2E test error`)
          }
          win.setTimeout(raise, 100)
        })
        .wait('@error')
```
The route is working, but the Cypress own crash handler thinks this error was unhandled and fails the test. If we could turn the Cypress crash handler just for this test, it would make a lot of sense.

**Comment by brian-mann** [comment]
ref #254

**Comment by cezarlz** [comment]
Any progress?
