### ISSUE TITLE
Coverage for Unit test is showing red line

### ISSUE THREAD

**Issue by hebaibrahim76** [cypress-io/cypress#24301]
### Current behavior

I forked the following repo https://github.com/bahmutov/demo-battery-api, in order to check the coverage for unit tests,
Here's my fork https://github.com/hebaibrahim76/demo-battery-api/tree/coverage-step
I checked out to the branch called coverage-step
In that branch I updated cypress version to 10.10.0 and let cypress do all the necessary configuration migration

After I ran cypress  my test passed
![Screenshot 2022-10-19 102609](https://user-images.githubusercontent.com/61517870/196626402-07effdcb-48b5-4025-9b78-48ff042bebba.png)

 Then I opened the coverage report, this is how it showed 

![Screenshot 2022-10-19 103738](https://user-images.githubusercontent.com/61517870/196626882-66d5651f-b74c-4273-b1a4-d050d91b6ca2.png)

![Screenshot 2022-10-19 103230](https://user-images.githubusercontent.com/61517870/196626346-ce9dcea7-6a89-403c-ae4d-91125f9fdff2.png)

### Desired behavior

I was expecting the coverage to be 100% and the line to be green, since I fully covered the function

### Test code to reproduce

clone https://github.com/hebaibrahim76/demo-battery-api/tree/coverage-step
checkout to coverage-step

### Cypress Version

10.10.0

### Node version

v16.13.1

### Operating System

Windows 11

**Comment by nagash77** [comment]
Hi @hebaibrahim76 , this seems to be an issue with your 3rd party plugin.  You should file an issue in this repo  https://github.com/bahmutov/demo-battery-api.
