### ISSUE TITLE
Test alternatively succeeds and fails in WebKit 

### ISSUE THREAD

**Issue by Giacomo-Papaluca** [cypress-io/cypress#24305]
### Current behavior

I have a simple test that I want to execute and it alternatively switches from a success to a fail with error `expecting an array or an iterable object but got [object Null]` as you can see in the screenshots.

1st run success:
<img width="432" alt="Schermata 2022-10-19 alle 11 46 08" src="https://user-images.githubusercontent.com/18098347/196657819-d8c50677-dcf7-474f-ad1d-1586863b6a49.png">

second run fail:
<img width="429" alt="Schermata 2022-10-19 alle 11 45 52" src="https://user-images.githubusercontent.com/18098347/196657838-7bb9c272-e083-42a1-ac57-6de889a0bbef.png">

### Desired behavior

The same test should return the same result every time you execute it. I noticed that in webkit that error occasionally comes out, independently from the test and in an alternating manner. For example in a suite with more tests on the same localhost "domain", the tests alternatively succeeded and failed. 

### Test code to reproduce

This is the test:

``` javascript
it('T001020: should redirect from /bla to /login', () => {
    cy.visit('http://localhost:3000/bla')
    cy.location('href').should('eq', 'http://localhost:3000/login' )  
  })
```

The website at localhost has a simple login page and a mechanism that redirects the user to it if looking for other pages.

### Cypress Version

10.10.0

### Node version

v14.15.5

### Operating System

macOS 11.6 (M1)

**Comment by nagash77** [comment]
@Giacomo-Papaluca Can you please include the code for the landing page and its redirection logic or provide a link to a github repo with a reproducible example?

**Comment by Giacomo-Papaluca** [comment]
The repository is private and I don't really know if I have the permission to give the code right now, I will ask and let you know. Anyway I don't think it is really linked to the code It feels like the execution of one test compromises the next execution. I noticed a curious pattern that seemed interesting to me and maybe is useful to share.

Premise: every test succeeds on other browsers like chrome or edge and the errors on webkit are always the same error and the execution throws even before running the test (note the "no commands were issued on this test").
Now for webkit, every test in my suite if executed singularly alternates between fail and success (even if changing the test between a fail and a success, the pattern is "fail, success" every time). More interesting, if I execute a test and it fails and then execute 3 tests of the suite it will give "success, fail, success" like this:
<img width="440" alt="Schermata 2022-10-19 alle 15 49 24" src="https://user-images.githubusercontent.com/18098347/196718309-005cb378-c5ba-4466-8b31-f9084b1f0297.png">

instead if I run a single test and it succeeds, executing the same 3 tests gives "fail, success, fail":
<img width="446" alt="Schermata 2022-10-19 alle 15 48 52" src="https://user-images.githubusercontent.com/18098347/196718624-c893adc9-038a-4203-879c-2c714714c3b0.png">

It seems to me that the execution of a test compromises the execution of the next one (given that if taken singularly they can succeed and that they succeed every time in other browsers).
Sorry for the long message but this pattern seemed kind of curious to me.

**Comment by lucasdonato** [comment]
I have the same problem

**Comment by mschile** [comment]
Possibly related to #23832. Could you please upgrade to Cypress 10.11.0 to see if that fixes the issue.

**Comment by lucasdonato** [comment]
show

**Comment by Giacomo-Papaluca** [comment]
Yes, version 10.11.0 seems to fix it. Thank you @mschile 👍
