### ISSUE TITLE
v10.10.0 testIsolation = legacy is clearing page on cy.session

### ISSUE THREAD

**Issue by jrockefeller** [cypress-io/cypress#24307]
### Current behavior

See the following unexpected behavior when using testIsolation: legacy.
The provided simple code examples showcase the issue.

**Use case**: The page stays open and multiple it() can be run. This is useful for a multistep wizard UI.
**Requirements**: need to keep session data to complete the last it()

```
const login = () => {
  cy.session('1', () => {
      cy.setCookie('testCookie', 'this is a test cookie value 12345')
  })
}

describe('test', {testIsolation: 'legacy'}, () => {
  before(() => {
    login()
    cy.visit('./test.html')
  })

  it('page is loaded and session exists', () => {
    expect(Cypress.config('testIsolation')).to.be.eq('legacy')
    cy.location('pathname').should('eq', '/test.html')
    cy.getCookie('testCookie').should('have.property', 'value', 'this is a test cookie value 12345')
  })

  it('page is still loaded and session exists', () => {
    cy.location('pathname').should('eq', '/test.html')
    cy.getCookie('testCookie').should('have.property', 'value', 'this is a test cookie value 12345')
  })

})
```
![image](https://user-images.githubusercontent.com/16764966/196694426-d75914bd-3c76-4d04-9a4e-fd00aca84a49.png)

**Result**:
1. Test 1 passes. Page is loaded, cookie exists
2. Test 2 fails: Page is loaded but cookie no longer exists.

This is expected behavior according to documentation that the session storage gets cleared before each test now that Cypress.Cookies.defaults({ preserve: true }) is not used when experimentalSessionAndOrigin: true.

Ok now test 2. Lets restore the session for test 2 so we can perform the action that requires the cookies to exist.

```
const login = () => {
  cy.session('1', () => {
      cy.setCookie('testCookie', 'this is a test cookie value 12345')
  })
}

describe('test', {testIsolation: 'legacy'}, () => {
  before(() => {
    login()
    cy.visit('./test.html')
  })

  it('page is loaded and session exists', () => {
    expect(Cypress.config('testIsolation')).to.be.eq('legacy')
    cy.location('pathname').should('eq', '/test.html')
    cy.getCookie('testCookie').should('have.property', 'value', 'this is a test cookie value 12345')
  })

  it('page is still loaded and session exists', () => {
    login()
    cy.location('pathname').should('eq', '/test.html')
    cy.getCookie('testCookie').should('have.property', 'value', 'this is a test cookie value 12345')
  })

})
```
![image](https://user-images.githubusercontent.com/16764966/196694598-06d3dd2b-869d-4cf8-b6d1-b7dc2e3340c7.png)

**Result**:
1. Test 1 passes. Page is loaded, cookie exists
2. Test 2 fails: Cookie exists BUT the page is now about.blank.

To sum up. 
testIsolation: legacy is not respected in the session() call causing the page to be reset. This is making it impossible to perform a multi step validation test.

### Desired behavior

cy.session() respects testIsolation: true and does not clear out the page when called.

### Test code to reproduce

```
const login = () => {
  cy.session('1', () => {
      cy.setCookie('testCookie', 'this is a test cookie value 12345')
  })
}

describe('test', {testIsolation: 'legacy'}, () => {
  before(() => {
    login()
    cy.visit('./test.html')
  })

  it('page is loaded and session exists', () => {
    expect(Cypress.config('testIsolation')).to.be.eq('legacy')
    cy.location('pathname').should('eq', '/test.html')
    cy.getCookie('testCookie').should('have.property', 'value', 'this is a test cookie value 12345')
  })

  it('page is still loaded and session exists', () => {
    login()
    cy.location('pathname').should('eq', '/test.html')
    cy.getCookie('testCookie').should('have.property', 'value', 'this is a test cookie value 12345')
  })

})
```

### Cypress Version

10.10.0

### Node version

16.16.0

### Operating System

Windows 11

**Comment by AtofStryker** [comment]
Hi @jrockefeller. Thank you for opening an issue. I threw together a quick [reproduction](https://github.com/AtofStryker/cypress-issue-24307) to validate the behavior. I was able to reproduce the behavior you were describing, but I do not think it's a bug which I think is better described in https://github.com/cypress-io/cypress/issues/24014#issuecomment-1260983078. However, I think this will be addressed in the future with https://github.com/cypress-io/cypress/issues/24206, as `testIsolation` set to `off` will no longer  clear the page or clear cookies, local storage or session storage between tests and will only clear cookies, local storage and session storage when `cy.session` is invoked, which I think is the behavior you desire here.

**Comment by jrockefeller** [comment]
perfect. 
The best of both worlds in that case

**Comment by AtofStryker** [comment]
going to go ahead and close this issue. Once `testIsolation` releases into it's `on`/`off` state, please let us know if you continue to run into issues!
