### ISSUE TITLE
cy.mount should remove the last mounted component if called multiple times in same test

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#24329]
### Current behavior

Scenario:

```ts
it('calls mount twice', () => {
  cy.mount(MyApp)
  cy.mount(MyApp)
})
```

Framework dependent behavior:

- Angular: Throws error upon second mount
- Vue: Mounts multiple components
- Svelte: Mounts multiple components
- React: Removes and remounts
- Vue2: Mounts multiple components

### Desired behavior

The last component mounted should be removed from the DOM/cleaned up.

### Test code to reproduce

```ts
import HelloWorld from "./components/HelloWorld.vue";

it("default", () => {
  cy.mount(HelloWorld, { props: { msg: "Component 1" } });
  cy.mount(HelloWorld, { props: { msg: "Component 2" } });
  cy.mount(HelloWorld, { props: { msg: "Component 3" } });
});
```

![Screen Shot 2022-10-20 at 5 11 51 PM](https://user-images.githubusercontent.com/25158820/197068902-3339c4e4-f49f-48da-a5a7-5a842a06c021.png)

### Cypress Version

10.10.0

### Node version

v16.17.1

### Operating System

macOS 12.4

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24329?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
