### ISSUE TITLE
Removal of erraneous functionality in CT

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24328]
We want to remove functionality that was deemed as erraneous with regards to critical functionality in Component Testing. Use the `no-dead-code` paradigm when practical to ensure users don't experience unnecessary blockers. 

### Global
- deprecate style injections (including impl in `mount-utils`).

### React
- `mountHook` function
- `unmount` function should no longer be exported
- Auto aliasing of mounted component

### Vue
- Remove mount callback

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24328?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by ZachJW34** [comment]
I feel like this has been answered but wanted an explicit answer to this: For functionality that is being removed, do we deprecate, deprecate + throw error when used or deprecate + noop/log when used?

**Comment by rockindahizzy** [comment]
> I feel like this has been answered but wanted an explicit answer to this: For functionality that is being removed, do we deprecate, deprecate + throw error when used or deprecate + noop/log when used?

@ZachJW34, my vote is to deprecate + throw.

@marktnoonan, could you give us the preferred method?

**Comment by lmiller1990** [comment]
It looks like we didn't share the final conclusion to the question in the post above by @rockindahizzy.

We will deprecate `styles`,`stylesheets`, `mountCallback` and `unmount`. Those will throw **errors** in Cypress 11. The error will explain the deprecation, and link to the migration guide.
