### ISSUE TITLE
abnormal view on yuque.com

### ISSUE THREAD

**Issue by yihuineng** [cypress-io/cypress#24323]
### Current behavior

abnormal view in cypress:

![image](https://user-images.githubusercontent.com/10104168/196915753-863632d9-a81e-425e-9f97-cda368a9e63e.png)

### Desired behavior

expect：
![image](https://user-images.githubusercontent.com/10104168/196915472-354d3142-f65b-48d0-8c18-45902ac22020.png)

### Test code to reproduce

describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://yuque.com')
  })
})

### Cypress Version

10.10.0.1868416

### Node version

v14

### Operating System

macOS 12.6

### Debug Logs

```shell
none
```

**Comment by amehta265** [comment]
@yihuineng Thank you for your posting this issue.
I suspect the reason for the header bar not loading has to do with [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) through the use of [nonce](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce) on the www.yuque.com website. Upon further investigation, the content served on the website is a react app that implements content security policy which ensures that any scripts served by the website have to be from certain specific origins. I have a feeling that this disallows certain scripts from being served where one of the scripts not being loaded maybe serving the header bar section.

We are currently investigating this and looking for alternatives

**Comment by amehta265** [comment]
@yihuineng I am wondering if somehow you can disable Content Security Policy for [www.yuque.com](http://www.yuque.com/) to see if that solves the issue?

**Comment by marktnoonan** [comment]
I'll close this for now due to inactivity, @yihuineng if you still have a problem, please comment again in the issue.
