### ISSUE TITLE
Salesforce issues after login

### ISSUE THREAD

**Issue by solaa-kkr** [cypress-io/cypress#24325]
### What would you like?

Hi guys,

I'm trying to create a new script related with salesforce, but after login the cypress panel is closed. More details related this issue https://github.com/cypress-io/cypress/issues/2367

### Why is this needed?

Looks like everybody have this problem and we are trying to create new script to automate some testing related with salesforce app

**Comment by nagash77** [comment]
@solaa-kkr as you mentioned this issue has been entered previously.  Please feel free to follow this ticket https://github.com/cypress-io/cypress/issues/24290 for updates.  Closing this issue as a duplicate.

**Comment by AtofStryker** [comment]
related to #2367 #23958, #24303 and #24290
