### ISSUE TITLE
CT mount types relying on `@cypress/` don't work

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#24330]
### Current behavior

`cypress/react18` has types defined in `node_modules/cypress/react18/dist/index.d.ts` that look like:

```ts
/// <reference types="cypress" />
/// <reference types="cypress" />
import React from 'react';
import type { MountOptions, UnmountArgs } from '@cypress/react'; // NOT GOOD
export declare function mount(jsx: React.ReactNode, options?: MountOptions, rerenderKey?: string): Cypress.Chainable<import("@cypress/react").MountReturn>;
export declare function unmount(options?: UnmountArgs): Cypress.Chainable<undefined>;
```

Notice the `@cypress/react` import (`@` prefix). The types won't be found unless the user happens to have installed the mount package from npm which is unlikely. The lack of the types leads to `any` typing of the options.
![Screen Shot 2022-10-20 at 5 20 51 PM](https://user-images.githubusercontent.com/25158820/197070081-94b2aa6f-1bce-4e97-a2c0-0d7957fae3ea.png)

### Desired behavior

The types for `cypress/react18` (using mount from cypress npm module) should be equivalent to the types for `@cypress/react18`. This problem also exists for our other mount packages as they have a reliance on `@cypress/mount-utils`, so they should be cleaned up as well. In summary, the types should work regardless of where the mount is coming from.

### Test code to reproduce

Create a react18 project outside of our repo with `npm init vite`. Choose TS and create a test.

### Cypress Version

10.10.0

### Node version

v16.17.1

### Operating System

macOS 12.4

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24330?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by ZachJW34** [comment]
For `cypress/react18` I would expect the types to be copied over to the disted output, similar to how the source code is copied. If it were copied, this would ensure that both `cypress/react18` and `@cypress/react18` have equivalent types. Unless `@cypress/react` is listed as a dependency, the published package won't have proper types.
