### ISSUE TITLE
Cypress crashes (Chromium renderer process) using headed mode

### ISSUE THREAD

**Issue by poponuts** [cypress-io/cypress#24331]
### Current behavior

 Running a test suite for 14mins visiting multiple sub-pages but under the same domain crashes Cypress runner:
 `Aw snap! Error code: 5`
`We detected that the Chromium Renderer process just crashed.`

![image (4)](https://user-images.githubusercontent.com/36245304/197106430-b27fddb8-59d2-4889-9e6f-83eb94aa835d.png)

From the Devtools, I can see heaps of the following in the console:
`Cypress Warning: `cy.state('subject')` has been deprecated and will be removed in a future release. Consider migrating to `cy.currentSubject()` instead.`

### Desired behavior

The tests will finish without crashing the Cypress runner.

### Test code to reproduce

Running the test suite (1 file but with multiple tests) in headed mode using Chrome.

### Cypress Version

10.10.1

### Node version

v16.15.1

### Operating System

macOS Monterey 12.6 M1 chip

### Debug Logs

```shell
Running the tests in headless mode looks fine (`DEBUG=cypress:* npx cypress run`) shows: 
It has completed successfully with the following snippets (too long to show the whole log): `cypress:cli child event fired { event: 'exit', code: 3, signal: null } +15m
  cypress:cli child event fired { event: 'close', code: 3, signal: null } +1ms`
![Screen Shot 2022-10-21 at 2 48 58 pm](https://user-images.githubusercontent.com/36245304/197107383-53f58758-15d1-4f84-87fb-31d85fd00a71.png)

  
cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'ffmpeg'      │      1       │    '19937'     │   636.4    │     61.56      │  33.98   │    19.72     │    33.98    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │    '17372'     │    0.1     │     124.1      │  29.63   │    22.77     │    31.68    │
  cypress:server:util:process_profiler │    2    │ 'electron-shared' │      2       │ '17442, 17379' │     0      │     13.14      │  12.87   │    12.79     │    15.22    │
  cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │    '17384'     │     0      │       0        │   4.13   │     4.81     │    26.77    │
  cypress:server:util:process_profiler │    4    │      'other'      │      2       │ '19992, 19993' │     0      │      0.06      │   0.38   │     0.37     │     0.4     │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      7       │      '-'       │   636.5    │     231.63     │  80.99   │    111.59    │   259.05    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
```
```


### Other

Troubleshooting done so far:
- Downgraded to `10.8.0` and still same issue
- Running on either Chrome or Electron show same issue
- commenting out `numTestsKeptInMemory: 0,` on `cypress.config.ts`

**Comment by nagash77** [comment]
@poponuts I'm sorry you are having issues.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by poponuts** [comment]
oh wow... seems like a standard response nowadays with just one missing piece from a long checklist of rejected issues. I thought the logs would be helpful enough (and would be a good start to look at first before outright rejecting) as it used to with the cypress core team when its challenging to reproduce it with another repo. I guess I just have to rely with the community who encountered the same issue.

**Comment by nagash77** [comment]
@poponuts We have many users and trying to investigate every problem is challenging without the information we request.  I am sorry you are encountering issues, but if the problem is hard for you to recreate, you can imagine it is significantly harder for us to recreate given we have a fraction of the context you have in your own project and implementation.  I am closing this issue pending a reproducible example.

**Comment by sergiu-hojbota-dotmatics** [comment]
why was this closed? it's still an issue and it's very annoying
