### ISSUE TITLE
Import multiple test inside specific test

### ISSUE THREAD

**Issue by Abdel-Monaam-Aouini** [cypress-io/cypress#24334]
### What would you like?

something like this :)
`import('blabla.spec.js').then(anotherTest => { .....})`

### Why is this needed?

for example, if I will get posts with her users, I will create a test for creating users and then creating posts (this is an easy example), but imagine if I have a lot of related things (storing, updating, deleting) to get the result of my API, 
I found myself, repeating many tests

**Comment by nagash77** [comment]
@Monaam12 Can you help me understand a little bit more about your use case?  Perhaps some more mock example specs?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
