### ISSUE TITLE
cypress/vue should return object containing vueWrapper and component

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24342]
## Current Behavior
Currently vue mount returns the vue wrapper object.

## Desired Behavior
vue mount should return an object with the wrapper and component

```js
{
  wrapper: VueWrapper
  component: VueWrapper.vm
}
```

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24342?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
