### ISSUE TITLE
Gracefully handle failures when deriving component name during mount

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24344]
## Current Behavior
When passing a component to mount in `React` as an object, the mount function cannot derive the component name and throws an error. The error that is surfaced to the user does not point to the cause or solution of the scenario and is confusing for the user. 

## Expected  Behavior
Instead of throwing the error at this stage we should verify that the component is the correct type and throw the error if that is not the case with better messaging for the user

## Additional considerations
Verify that other frameworks handle this situation gracefully and address it in a similar way if this is not the case.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24344?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
