### ISSUE TITLE
Improve or Add JSDoc for mount other exported functions

### ISSUE THREAD

**Issue by rockindahizzy** [cypress-io/cypress#24343]
## Current Behavior
Currently not all of the CT libraries have JSDoc for their exported functions.

## Desired Behavior
- All of the exported functions have JSDoc added 
- Ensure new and existing JSDoc contains the example stepper mount from the docs website
- Include a link to the documentation in the JSDoc

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24343?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
