### ISSUE TITLE
cy.session does not respect cucumber scenario outlines

### ISSUE THREAD

**Issue by aomaryus** [cypress-io/cypress#24353]
### Current behavior

Cucumber Scenario Outlines do not work with cy.session().
### Desired behavior

With cy.session , only the first scenario outline work.
The subsequent scenario outlines do not. 

### Test code to reproduce

Any simple cucumber scenario outline.

### Cypress Version

10.10

### Node version

16

### Operating System

Any

**Comment by aomaryus** [comment]
Please let me know if you need any further details.
We need this feature. It will make our work much simpler.
Please also note that cacheAcrossSpecs option is only available in 10.2 so I cannot make use of that in any other release.

Thank you.

**Comment by mschile** [comment]
@aomaryus, unfortunately, I was unable to replicate your issue using an [example project](https://github.com/mschile/issue-24353). Do you have a project I could look at?

**Comment by aomaryus** [comment]
OK
I will put together a sample project
Thank you

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
