### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by 0618** [cypress-io/cypress#24356]
### Current behavior

I'm trying to validate plenty of links by using `cy.request` or `cy.visit`, but the memory leaks after doing about 49 requests(sometimes less, sometimesmore).

```
<--- Last few GCs --->

[32438:0x7fac2e200000]   392862 ms: Mark-sweep 4081.6 (4123.6) -> 4081.6 (4120.9) MB, 627.7 / 0.1 ms  (average mu = 0.133, current mu = 0.000) allocation failure GC in old space requested
[32438:0x7fac2e200000]   393491 ms: Mark-sweep (reduce) 4088.7 (4124.6) -> 4088.0 (4120.4) MB, 40.3 / 0.1 ms  (+ 451.0 ms in 53 steps since start of marking, biggest step 23.7 ms, walltime since start of marking 541 ms) (average mu = 0.186, current mu = 0

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10f896a25 node::Abort() (.cold.1) [/Users/xxxxx/.nvm/versions/node/v16.14.2/bin/node]
...
```

### Desired behavior

It should make all the requests without memory leak, especially after using `cy.clearLocalStorage`

### Test code to reproduce

```
for (let i = 0; i < 100; i++) {
  describe(`check page ${i}`, () => {
    const baseUrl = 'http://localhost:5001';

    it(`all links on ${i} link should work`, () => {
      const link = allLinks[i];
      cy.task('log', `[TESTING...] page ${baseUrl}/${link}`);
      cy.request(link || '/').then(({ status }) => {
        expect(status).to.eq(200);
        cy.clearLocalStorage();
      });
    });
  });
}
```

It works if I change the `baseUrl` from localhost to a pre-prod environment....so must be some compiling issue.

### Cypress Version

10.10.0

### Node version

v16.14.2

### Operating System

macOS 12.6

**Comment by lmiller1990** [comment]
You mentioned it works against a pre-prod env but not locally. What are you running locally? It is something like Vite?

I seem to recall something similar happening on a project that loaded hundreds and hundreds of JS modules in development mode on the first page visit, which was cause massive network slowdown, since Cypress blows away the cache for each spec, and does lots of network inspection for the `cy.intercept` feature.

**Comment by 0618** [comment]
Thanks for following up. I found it was `cy.request` takes a lot of memory. So I reduced `cy.request` usage and also use `HEAD` instead of `GET`, which helped.

My Mac has 16GB memory and the pre-prod build environment is on a Docker image on a host with 4 vCPU, 7GB memory 😂

**Comment by lmiller1990** [comment]
> pre-prod build environment is on a Docker image 

It sounds like you should have plenty of memory to spare, if you are only running Cypress locally against a remote machine. I wonder why `cy.request` is taking so much memory? 

Also, how did you reduce `cy.request` usage? What are you doing instead? I wonder if there's another way to write your tests. That said, if there's a memory leak, it'd be great to isolate and fix it.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
