### ISSUE TITLE
Problem interacting with iframe

### ISSUE THREAD

**Issue by minopica** [cypress-io/cypress#24359]
### Current behavior

I'm trying to interact with some elements inside an iframe with cypress. If I use the approach in https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/ for only one element per test, everything is fine.
If I try to perform 2 consecutive commands on the iframe in a single test then the second command fails.

If I add cy.wait(10000) between the two commands in iframe it works fine.
How can I solve this issue without using cy.wait() ?

### Test code to reproduce

# command.js

```
Cypress.Commands.add('getIframe', () => {
    return cy
        .get('iframe[title="Windtre"]')
        .its('0.contentDocument.body').should('not.be.empty')      
        .then(cy.wrap)
    })
```

# WindayPage.js
```
/// <reference types="Cypress-iframe" />
import 'cypress-iframe'

class WindayPage {

    elements = {
        // firstArrow: () => cy.iframe('iframe[title="Windtre"]').find('.right > img').eq(0),
        firstArrow: () => cy.getIframe().find('.right > img').eq(0),
        // back: () => cy.iframe('iframe[title="Windtre"]').find('img.back-button')
        back: () => cy.getIframe().find('img.back-button')
    }

    clickFirstCard()
    {
        // cy.frameLoaded('iframe[title="Windtre"]')
        this.elements.firstArrow().click()
        //cy.pause()
        cy.wait(10000)
        this.elements.back().click()
    }
    
}

module.exports = {WindayPage}
```
# winday_registrato.spec.js
```
it('Winday linea registrata', function()
{
    const poManager = new POManager()
    const loginPage = poManager.getLoginPage()
    cy.log(data.username)

    loginPage.goTo("https://priv:P3rz0nal!@pwa.bs.windtre.it/oa/auth/login")
    loginPage.validLogin(data.username,data.password)

    const homePage = poManager.getHomePage()
    homePage.goToWinday()

    const windayPage = poManager.getWindayPage()
    windayPage.clickFirstCard()
})
```
-----------------------------------

### Cypress Version

10.10

### Node version

16.17.0

### Operating System

macOS 12.5.1

**Comment by mschile** [comment]
@minopica, I am able to successfully access an iframe twice in this [example project](https://github.com/mschile/issue-24359). Do you have a project I can look at? You may also want to check out this community [iframe plugin](https://gitlab.com/kgroat/cypress-iframe).

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by T-Auto-1** [comment]
Hopefully this will help: https://github.com/cypress-io/cypress/issues/136#issuecomment-1369913899
