### ISSUE TITLE
Allow `cypress run` to run without printing stack traces.  

### ISSUE THREAD

**Issue by dwjohnston** [cypress-io/cypress#24360]
### What would you like?

My workflow sometimes has me running the full suite of tests using `cypress run` on my development machine. I'm basically just checking that all the tests are passing before creating a PR. 

In the case that there are test errors, I don't want to see the stack traces. I just want to see the summary tables of suites, with the failing tests shown in red. (A single line error message would be fine). 

### Why is this needed?

The problem that the stack traces have, is that they can be very long (I have an input that has every timezone listed, and that's showing up, when an element isn't found), and it makes it hard to quickly see which tests are erroring. 

Usually my process if tests are erroring, is that I run them individually using `cypress open`, so I can watch them run. I just want to use the `cypress run` output to quickly see which ones are erroring. 

### Other

Suggested solution is a flag to add to `cypress run` like `--no-error-output` or `--output-results-only`

**Comment by marktnoonan** [comment]
Thanks for this request. This doesn't seem like something that would require a change to Cypress as is only affects reporting. Have you looked into using custom mocha reporter for this?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
