### ISSUE TITLE
(component) Clicking "Open in IDE" is broken

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#24366]
### Current behavior

Clicking "Open in IDE"  in the reporter does not take user to hook/test definition that ran.

In Prod - this does nothing. It doesn't open the IDE or launch to the file that ran. See video:

https://user-images.githubusercontent.com/14099737/197545580-7280e228-7018-438c-9077-436ece1fe3d0.mov

In dev - this opens to the current IDE / branch & opens the stack_utils file in the driver. See video:

https://user-images.githubusercontent.com/14099737/197545624-5512a12a-2a74-43f4-b6e8-0e9d52aa2907.mov

### Desired behavior

Opens to hook / test when "Open in IDE" is clicked.

### Test code to reproduce

Open any CT test and click "Open in IDE" after test runs.

### Cypress Version

10.10.0

### Node version

16.16.0

### Operating System

MacOS 12.5.1

**Comment by baus** [comment]
Remove the button for CT for initial implementation.

**Comment by warrensplayer** [comment]
This was originally a hold over from unification: https://github.com/cypress-io/cypress/issues/21684
