### ISSUE TITLE
Links on @cypress/vue2 are broken

### ISSUE THREAD

**Issue by agentdon** [cypress-io/cypress#24384]
Most of the links on the @cypress/vue2 [homepage](https://www.npmjs.com/package/@cypress/vue2) are broken. Specifically, I'm trying to get access to the links under the "Global Vue Options."

**Comment by astone123** [comment]
Transferring this issue to https://github.com/cypress-io/cypress since these links will need to be updated in the `@cypress/vue2` package readme
