### ISSUE TITLE
Missing typings when Cypress is installed globally

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2438]
Cypress v3.1.0

- create new folder
- install Cypress globally with `npm i -g cypress`
- create new NPM project `npm init -y`
- add custom command for example to open Cypress

```json
{
  "name": "test-cypress-global",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cy:open": "cypress open"
  },
  "keywords": [],
  "author": "Gleb Bahmutov <gleb.bahmutov@gmail.com> (https://glebbahmutov.com/)",
  "license": "ISC"
}
```

- open Cypress in the current folder with command `npm run cy:open -- --project .`
  * Cypress creates examples in the current folder
- open example files in VSCode and the typings are not there (for example `cypress/examples/actions.js`)

<img width="767" alt="screen shot 2018-09-05 at 4 21 22 pm" src="https://user-images.githubusercontent.com/2212006/45119023-286f6f80-b128-11e8-844f-c9a60bf47a0f.png">

**Comment by bahmutov** [comment]
Triple slash types documentation: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

For now I could not discover a way to specify globally installed module, and the only solution was to use absolute path like this

```
/// <reference path="/Users/gleb/.nvm/versions/node/v8.9.4/lib/node_modules/cypress/types/index.d.ts" />
```

So the only workaround or recommended long term is to install Cypress as a normal local NPM package

```text
npm i -D cypress
```

**Comment by rohit-gohri** [comment]
Is there a way to install the module locally but only for the types? The reason I want to do this is because the adding the whole package makes the first install really slow. And not everyone in my team is using cypress right now, so not everyone needs it.

**Comment by bahmutov** [comment]
@rohit-gohri you can skip the Cypress binary download and install using an environment variable https://on.cypress.io/installing#Environment-variables

**Comment by rohit-gohri** [comment]
> @rohit-gohri you can skip the Cypress binary download and install using an environment variable [on.cypress.io/installing#Environment-variables](https://on.cypress.io/installing#Environment-variables)

Thanks!
