### ISSUE TITLE
Skipped tests should be visually indicative

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#244]
Currently when Mocha skips tests (such as failed hooks, uncaught exceptions, etc) you can't really visually "tell" that the tests were skipped.

They just look like they haven't run yet.

We should visually indicate they're skipped by ~~strikethrough~~ or something else.

**Comment by brian-mann** [comment]
Strikethrough test 2 and test 3, and we probably should add a gray color to the sidebar.

![screen shot 2018-04-13 at 3 27 32 pm](https://user-images.githubusercontent.com/1268976/38754298-38901826-3f2f-11e8-9fd4-e69a5371934b.png)

**Comment by chrisbreiding** [comment]
Here are some options for styling:

Strikethrough, same icon as 'processing':

![screen shot 2018-04-13 at 3 39 32 pm](https://user-images.githubusercontent.com/1157043/38754776-1ac0ba88-3f31-11e8-9b33-b996d17230b2.png)

Strikethrough, ban icon:

![screen shot 2018-04-13 at 3 40 00 pm](https://user-images.githubusercontent.com/1157043/38754777-1ad2a9b4-3f31-11e8-81cd-4ad5c6599b6e.png)

No strikethrough, ban icon:

![screen shot 2018-04-13 at 3 40 10 pm](https://user-images.githubusercontent.com/1157043/38754778-1ae53368-3f31-11e8-88b9-1634313a26a9.png)

minus-circle icon:

![screen shot 2018-04-13 at 3 46 17 pm](https://user-images.githubusercontent.com/1157043/38754936-def46238-3f31-11e8-8042-cde8ae5f6b44.png)

times icon:

![screen shot 2018-04-13 at 3 49 00 pm](https://user-images.githubusercontent.com/1157043/38755020-347afd2a-3f32-11e8-9fb8-be9e9efb10ea.png)

**Comment by chrisbreiding** [comment]
step-forward icon:

![screen shot 2018-04-13 at 3 53 43 pm](https://user-images.githubusercontent.com/1157043/38755219-f05fba08-3f32-11e8-8470-736942180729.png)

**Comment by jennifer-shehane** [comment]
I like step-forward icon + no strikethrough

**Comment by brian-mann** [comment]
I like "strikethrough, ban" but I'll take "graying out the text, and ban icon"

**Comment by chrisbreiding** [comment]
@brian-mann, @jennifer-shehane A couple more options, both with greyed-out text:

`fa-share`:

![screen shot 2018-05-11 at 5 06 07 pm](https://user-images.githubusercontent.com/1157043/39947222-1b0631b6-553f-11e8-8a6a-e1bb3e25495a.png)

`fa-repeat fa-rotate-90`:

![screen shot 2018-05-11 at 5 15 59 pm](https://user-images.githubusercontent.com/1157043/39947226-24c76918-553f-11e8-87d6-1d536d850348.png)
