### ISSUE TITLE
Cypressio 3.1.0 give an empty junit report

### ISSUE THREAD

**Issue by bentrole** [cypress-io/cypress#2440]
### Current behavior:

I just made an update from Cypressio 2.1.0 to 3.1.0 and all tests are done perfectly but in 3.1.0, I have an empty report for junit.

Same test with 2.1.0:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="5.825" tests="1" failures="0">
  <testsuite name="Root Suite" timestamp="2018-09-06T08:45:16" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="1 - BO initial automation (Create all on Shop)" timestamp="2018-09-06T08:45:16" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="a001-Create Tags" timestamp="2018-09-06T08:45:16" tests="1" failures="0" time="5.825">
    <testcase name="1 - BO initial automation (Create all on Shop) a001-Create Tags tag (uid:1a32b035-d308-4a59-9612-26400d4b3faa)" time="5.825" classname="tag (uid:1a32b035-d308-4a59-9612-26400d4b3faa)">
    </testcase>
  </testsuite>
</testsuites>
```

Same test with 3.1.0:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="0" failures="0">
</testsuites>
```

My config file: (Notice that I just changed the cypress version and reinstall cypress.
```json
  "scripts": {
    "cypress:run": "cypress run --reporter mocha-junit-reporter",
  },
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^1.1.2",
    **"cypress": "^3.1.0",**
    "mocha": "^5.0.5",
    "mochawesome": "^3.0.2",
    "pre-push": "^0.1.1",
    "prettier": "^1.9.2",
    "ts-loader": "^3.2.0",
    "tslint": "^5.8.0",
    "typescript": "^2.6.2"
  },
  "optionalDependencies": {},
  "pre-push": {
    "run": [
      "pre-push-msg",
      "typescript",
      "lint"
    ],
    "color": true
  },
  "dependencies": {
    "mocha-junit-reporter": "^1.17.0"
  }
}
```

### Desired behavior:

I would like to have a junit report like in cypressio 2.1.0 but I don't know if I missed something in my configuration

### Steps to reproduce:

-Use my `pakage.json` file to run a cypress test in 2.1.0: You should have a junit report with a good contain
-Use my `pakage.jso`n file to run a cypress test in 3.1.0: You will not have a junit report with a good contain

### Versions
Same result for:
Electron 59 and chrome 69

**Comment by bentrole** [comment]
Oups, my xml result is not printed.
Cypressio 2.1.0 junit file:

`<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="5.825" tests="1" failures="0">
  <testsuite name="Root Suite" timestamp="2018-09-06T08:45:16" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="1 - BO initial automation (Create all on Wynd Shop)" timestamp="2018-09-06T08:45:16" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="a001-Create Tags" timestamp="2018-09-06T08:45:16" tests="1" failures="0" time="5.825">
    <testcase name="1 - BO initial automation (Create all on Wynd Shop) a001-Create Tags tag (uid:1a32b035-d308-4a59-9612-26400d4b3faa)" time="5.825" classname="tag (uid:1a32b035-d308-4a59-9612-26400d4b3faa)">
    </testcase>
  </testsuite>
</testsuites>`

and Cypressio3.1.0 junit file:
`<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="0" failures="0">
</testsuites>`

**Comment by minuwi** [comment]
It's working with `Cypress` `3.1.0` and `mocha-junit-reporter` `1.18.0`. 
Provide us more informations... 

What is your `cypress.json` files ?

**Comment by bentrole** [comment]
I have nothing special in my cypress.json (only {} ), I just tried to use 1.18.0 because I had 1.17.0 but nothing changed for me, I always got an empty file. This is my package.json
[package.zip](https://github.com/cypress-io/cypress/files/2361491/package.zip)

**Comment by minuwi** [comment]
You need specify the output folder.

Add thoses lines in `cypress.json`

```
 "reporter": "mocha-junit-reporter",
    "reporterOptions": {
        "mochaJunitReporterReporterOptions": {
            "mochaFile": "your_path/results.xml"
        }
    }
```

**Comment by bentrole** [comment]
I just understand why I have this issue, it is because I have 3 js files into the folder and each run test overwrite the previous result file and finally, I just have the last file which is empty because the last test file does not contain cypress codes but only some functions. 

Thanks a lot, I don't know if it is a Bug or not because finally, if I run 3 real tests, I ll have only 1 report xml.

**Comment by jennifer-shehane** [comment]
Please see [this issue](https://github.com/cypress-io/cypress/issues/1824) regarding breaking reporter changes in version 3 and other user's workarounds.
