### ISSUE TITLE
Debug Page - M0 and M1.0

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#24438]
Enable users to see the results of a cloud recorded run directly in the app and interact with those results.

**NOTE**  Previously known as In App Test Results (IATR)

M0 (Milestone 0) will not be released to the customers and held in a feature branch

M1.0 released on 01/31/2023

Clickup: https://app.clickup.com/t/18033298/PM-2546

**Comment by lmiller1990** [comment]
We did M0, M1 and M1.1. Closing! 🚀
