### ISSUE TITLE
Delay for Non-Stubbed Responses not supported

### ISSUE THREAD

**Issue by saron3** [cypress-io/cypress#2444]
Cypress does not delay non-stubbed responses e.g. responses to API endpoints.

**Comment by TomGroeneboer** [comment]
Hey @jennifer-shehane,

Even though the original report does not have much information and next to no upvotes, I would really like to have this feature. We have a use case where we want to add a delay to a non-stubbed request. We would like to keep our backend implementation and not having to update our fixtures when we change the endpoints response. However, we still want to validate loading spinners/labels on those calls.

Can you shine some light on whether you guys think this feature is feasible? And maybe give us some pointer where to make the change to PR this? We would be happy to contribute.

Best,
Tom Groeneboer
Fonto

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
