### ISSUE TITLE
[IATR](M0) Debug Page and Tab in left nav

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#24441]
Add a new navigation item in the app left nav for "Debug" which will navigate to a new page

**NOTE:** M0 issues will be committed against a feature branch and not released 

### UI Design

* Left nav will have new item below Runs and above Settings for "Debug" that will have a corresponding icon
* The page component will render the [header component](https://github.com/cypress-io/cypress/issues/24442) followed by a list of [failed specs components](https://github.com/cypress-io/cypress/issues/24443)
* Page should have a blank empty state (just text that says "Not logged in") when not logged in
* Page should have a blank empty state (just text that says "Not connected") when logged in but no project connected
* Page should have a blank empty state (just text that says "No runs") when there are no matching runs

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/1702361/198724068-ac8ce7e1-361d-4d2e-afe4-505dfa95d569.png">

_Wireframe from Whimsical. Final design is in progress._

### Inputs

Pull relevant run information from the `login-connect-store` and then fetch failed spec information for that run. See https://github.com/cypress-io/cypress/issues/24440

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24441?planning-poker) with Zenhub @rockindahizzy @lmiller1990 @ZachJW34 @marktnoonan @amehta265 @astone123

**Comment by ZachJW34** [comment]
This should be internal right? Should the issue be updated to include "Only show new tab in local dev"?

**Comment by warrensplayer** [comment]
> This should be internal right? Should the issue be updated to include "Only show new tab in local dev"?
@ZachJW34 I am adding a note to the IATR M0 issues to indicate that these will be held in a feature branch and not released
