### ISSUE TITLE
Only Run One Test in a Suite

### ISSUE THREAD

**Issue by DPC15038** [cypress-io/cypress#24451]
I'm not sure if this is by design, but I have a test file like this:

```
describe('My Test', { tags: '@myTag' }, () => {
     it('checks some data', { tags: '@tag1' }, () => {
       ...
     },

     it('checks some different data', { tags: '@tag2' }, () => {
       // I only want this specific test to run 
       ...
     }
```
When I run this command
`npx cypress run --env grepTags=@tag2,grepFilterSpecs=true,grepOmitFiltered=true,env=dev`
both of the `it` tests run.

Is there any way to only run the exact tests that match the `grepTag`?

**Comment by nyghtly-derek** [comment]
This looks like a bug to me. I think your test is getting filtered out by `grepFilterSpecs` based on the `describe` block without evaluating the inner tags. It might work if `grepFilterSpecs=false`. 

Anyways, here is a potential work around for you: `grepTags=@myTag+@tag2`

**Comment by DPC15038** [comment]
The workaround doesn't work unfortunately, because the `describe` does not contain `@tag2`, so the file gets filtered out. This does really feel like a bug to me.

**Comment by nyghtly-derek** [comment]
Hm, I thought of something else to try. What if you add both @tag1 and
@tag2 to the describe block? That way, it will always get included whenever
you use one of those. You can still exclude the entire file against @myTag.

So it would be:

`@myTag @tag1` = Include "checks some data"
`@myTag @tag2` = Include "checks some different data"
`@tag1` = Include "checks some data"
`@tag2` = Include "checks some different data"
`@myTag` = no operation? (Maybe it includes both but I'm not sure)
`--@myTag` = exclude everything

In fact, the first two might work already.

Unfortunately, I'm not at my computer so I can't test it out, but hopefully
you can find something in there that works for you.

Also, I would recommend making a fork if you need to. I needed a bug fix
for my project and that's what I did. You can see it in the pull requests
for this repo.

This repo seems a bit slow to maintain right now but hopefully that will
improve once it gets integrated into the default Cypress repo.

We all love gleb but unfortunately his bandwidth is limited!

**Comment by DPC15038** [comment]
After reading through the codebase, im fairly confident that what I want isn't possible with the way this library is written. I think it would be really useful, but it isnt like this is a "bug" because it just isnt the way that this works,

**Comment by rovervannispen** [comment]
This feature would be really useful! Currently all `it`s within a `describe` block are executed regardless of the given tags
