### ISSUE TITLE
[Run All Specs] - Inline Spec Explorer - Add "run N specs" button to folder rows

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#24468]
### Summary

Currently, users can filter specs and choose a single one to run in open mode. They need the ability to run the currently-filtered list of specs, which replicates the functionality of Run All in 9.x. This implementation adds an extra ability not possible in 9.x: to further select only a specific folder, to run the subset of specs _currently matching the filter_ in that folder (child folders included). This is achieved with a "play" button present on each folder in the inline spec explorer.

#### Empty state, no visual change
<img width="385" alt="Screen Shot 2022-11-08 at 7 31 03 AM" src="https://user-images.githubusercontent.com/8340719/200564761-985c6347-b485-4812-a271-22fe0ba7e724.png">

#### Hover on row but not button
<img width="364" alt="Screen Shot 2022-11-08 at 7 31 18 AM" src="https://user-images.githubusercontent.com/8340719/200564806-fd247e08-9e61-49a5-a8ba-fba7e7664bb7.png">

#### Hover on button itself
<img width="566" alt="Screen Shot 2022-11-08 at 7 31 44 AM" src="https://user-images.githubusercontent.com/8340719/200564843-de652e06-f741-4253-8228-c0fb2c1d6e0d.png">

### Acceptance Criteria

**In e2e mode only:**

1. "Play" buttons should exist on all folders
2. On top-level folder, have the tooltip "Run N specs" and run all specs that match the current search
3. On all other folders, have the tooltip "Run N specs" where N is the number of specs in the folder that match the current search and those should be the ones run
4. The button appears when the folder row is hovered
5. Buttons have their own hover state and are activated on click
6. The behavior of clicking the row is still to toggle the open/closed state of the folder
7. When clicked, the button takes the user to the Spec Runner page and runs the selected specs.
8. Button should be reachable by the keyboard and appear when focussed with the tab key

### Resources

Figma prototype: https://www.figma.com/proto/PAOozuCxtfetqP8fUVvg0y/branch/WpNw4mG3LvD1J3zLj80KCr/Cypress-App?node-id=20720%3A150686&starting-point-node-id=20668%3A150076

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24468?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
I voted, but I think we should reconsider the design of this feature.

I think this is overly complex for an initial implementation and going to muddy the goal of getting something useful in the hands of users.  A cheaper and more discoverable alternative would be to just place a single button at the top under the spec filter that runs everything that's filtered. If they want a sub directory, they can just type it in - this would be in line with 9.x parity (which worked great), and also much cheaper and easier to implement. What do you think?

**Comment by lmiller1990** [comment]
This could just be the UI I think? The logic should be free, done in https://github.com/cypress-io/cypress/issues/24467
