### ISSUE TITLE
[Run all specs] restore legacy "run all" behavior and add "folder level" filter

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#24469]
### Summary

In the [Run All Specs spike](https://github.com/cypress-io/cypress/issues/23471) @lmiller1990 discussed several options for restoring this behavior. We've chosen Option 1, "Port the exact implementation from Cypress 9." - with one extra wrinkle, the ability to narrow the filtered specs to just those contained underneath a particular folder. So this feature needs to understand "filter + folder" and run a subset of the filtered specs, unless the folder is root of all filtered specs.

To answer some of the question's Lachlan raised in the epic:

> 1. We support Component Testing now. Do we need the same behavior for Component Testing? One point of different is Component Testing works with Vite and Webpack, and uses a dev server. I'm not sure how much complexity this adds, but it's complexity we will need to consider.

The initial implementation does not need to support component testing unless it's very low complexity. It will be fine for the scope of the experiment to expand over time to CT. CT didn't have "run all" in 9.x so there is no issue of parity.

> 2. Where does the "run all specs" button go? Does it go on the first page you see (the "specs" page) or on the "runner" page?
> 3. How can I choose multiple specs? We need checkboxes. Where do those go?

#24467 and #24468 provide the UI

> 4. What if I want to run a different set of specs? One of the main problems with Run All Specs is memory usage. In Cypress 9, when you choose a new combination of specs to run, we re-launch the browser, which releases all the memory. In Cypress 10, you only open the browser once.

For the experimental release, we will match the 9.x behavior and relaunch the browser.

### Acceptance Criteria

1. When all specs in a folder are run, all specs in its child folders that also match the current search are also run
2. When all specs are run, they use "legacy" Run All Specs behavior and simply concat all the specs into a single mega-spec
3. Run All Specs should be behind an experimental flag called `experimentalRunAllSpecs` at the root level of the config

Future note: We will then iterate on this behavior to make it "correct" and deterministic, but for the context of the experiment, the old behavior is correct.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24469?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
What is the deliverable? Or is this just an epic for tracking? It's not clear what we are estimating.

**Comment by marktnoonan** [comment]
@lmiller1990 this is the non-ui part of the work, the code from 9.x that will be called to actually combine the spec files and run them.

**Comment by baus** [comment]
Just FYI this for E2E only
