### ISSUE TITLE
[Run All Specs] - Spec Explorer - Add "run N specs" button to folder rows

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#24467]
### Summary
Currently, users can filter specs and choose a single one to run in open mode. They need the ability to run the currently-filtered list of specs, which replicates the functionality of Run All in 9.x. This implementation adds an extra ability not possible in 9.x: to further select only a specific folder, to run the subset of specs _currently matching the filter_ in that folder (child folders included). This is achieved with a "Run N specs" button present on each folder in the Spec Explorer, instead of a single "Run All"/"Run Filtered" button.

#### Empty state, no visual change
<img width="600" alt="empty state" src="https://user-images.githubusercontent.com/8340719/200563048-64c396b3-0141-42b2-925e-2cc6aca7181c.png">

#### Hover on row but not button
<img width="600" alt="hover on row" src="https://user-images.githubusercontent.com/8340719/200562962-e5bfeb0f-2e6f-479b-94c4-29f27b701f5b.png">

#### Hover on button itself
<img width="600" alt="hover on button" src="https://user-images.githubusercontent.com/8340719/200562661-8eb0ecd8-61c0-4db3-956b-44e08f7d8e38.png">

### Acceptance Criteria

**In e2e mode only**:

1. Buttons should exist on all folders
2. On top-level folder, it should be called "Run N specs" and run all specs that match the current search
3. On all other folders, it should be called "Run N specs" where N is the number of specs in the folder that match the current search and those should be the ones run
4. The button appears when the folder row is hovered
5. Buttons have their own hover state and are activated on click
6. The behavior of clicking the row is still to toggle the open/closed state of the folder
7. When clicked, the button takes the user to the Spec Runner page and runs the selected specs.
8. Button should be reachable by the keyboard and appear when focussed with the tab key

### Resources

Figma prototype: https://www.figma.com/proto/PAOozuCxtfetqP8fUVvg0y/branch/WpNw4mG3LvD1J3zLj80KCr/Cypress-App?node-id=20668%3A150076&starting-point-node-id=20668%3A150076

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24467?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Posted similar thoughts here: https://github.com/cypress-io/cypress/issues/24468#issuecomment-1309257898

I went ahead and estimated, but I don't like the fact you need to hover too much. What's the reasoning here? I miss having a "Run N specs button". Is there any room for feedback or discussion here?

Also, if I type a filter and hit enter on my keyboard, should that run all the filtered specs? This would be really useful.

**Comment by amehta265** [comment]
When you filter you would be able to `run N specs` depending on the folder structure that results from your search.
So in this example you could run the two specs that show up. In a more complicated case, if your search results yields say 3 distinct folders then you could `run N specs` for your intended folder
<img width="1755" alt="Screenshot 2022-11-09 at 3 19 19 PM" src="https://user-images.githubusercontent.com/65267668/200933415-fc294996-0dd0-478c-bc9b-aa03904fb414.png">

**Comment by marktnoonan** [comment]
I do like the suggestion of running all with a keyboard shortcut, though I think "enter" might be a bit unexpected, people may intuitively and harmlessly hit "enter" to "submit" the search. We could get around that with a little message "Hit enter to run all matching specs". That would be slick.

**Comment by lmiller1990** [comment]
I am picking this up along with @amehta265, going to work on the data structure and refactor a bit as part of this - the tree is getting a bit complex and starting to leak into the component layer a bit too much. Right now we don't have the info we need to easily get the # of specs, so I'll do this while @amehta265 works on the UI end of things.
