### ISSUE TITLE
Allow cy.wait command to accept "requestTimeout" and "responseTimeout" option.

### ISSUE THREAD

**Issue by ryanhaney** [cypress-io/cypress#2446]
### Current behavior:

The `cy.wait` command does not respect the "requestTimeout" option. The following command will still timeout waiting for a request to begin after 5000ms:
```js
cy.wait('@completeUpload', {requestTimeout: 20000})
```

### Desired behavior:

The following command should wait up to `20000ms` for a request to start before timing out.
```js
cy.wait('@completeUpload', {requestTimeout: 20000})
```

### Steps to reproduce:

```js
cy.wait('@completeUpload', {requestTimeout: 20000})
```

### Versions

Cypress: 3.1.0
OS: macOS 10.13.6
Browser: Chrome 68

### Workaround

Setting timeout, as the documentation states, appears to set both `requestTimeout` and `responseTimeout`.

```js
cy.wait('@completeUpload', {timeout: 20000})
```

**Comment by jennifer-shehane** [comment]
`cy.wait()` only accepts a `timeout` option which sets both the `requestTimeout` and `responseTimeout` as stated in the docs and in your workaround. 

I thought there was an issue already opened to split these options out, but it seems [it was never created](https://github.com/cypress-io/cypress/issues/176). 

Updating this issue to reflect feature request to split `timeout` options into 2 seperate arguments: `requestTimeout` and `responseTimeout`.

**Comment by ryanhaney** [comment]
Sorry, I misunderstood the docs for cy.wait. Am I correct that the current requestTimeout and responseTimeout settings are global and that cy.wait's timeout option overrides both for scope of the current call? If so, then yes, I would like to be able to set requestTimeout and responseTimeout _independently_ for the scope of the current call.

Thanks!

**Comment by jennifer-shehane** [comment]
Yes, the `timeout` option sent to `cy.wait()` currently overrides both, which is not ideal and we would like to allow both request and response timeout options.

**Comment by brian-mann** [comment]
Fixes https://github.com/cypress-io/cypress/pull/2829

**Comment by bvanderneut** [comment]
Hello everyone,

Can it be that this is broken somewhere in the latest version?
I have a small test where you can reproduce the issue we have.
Both ways of overriding the default value do not work.

context('Cypress.config()', () => {
  it('Get and set configuration options', () => {
    // this will change the config for the rest of your tests!
    //Cypress.config('responseTimeout', 40000);
    //expect(Cypress.config('responseTimeout')).to.eq(40000);

    cy.visit('https://independer.free.beeceptor.com/my/api/path').as('slowy'); // API Path is setup to respond after 35seconds
    cy.wait('@slow', { responseTimeout: 40000 });
  })
})

**Comment by jtymes** [comment]
Hi @bvanderneut - when I implemented this, I ensured that existing tests did not break when passing the option, so I would be surprised that your use case would be having problems. 

I notice in your example you have the alias set to `as('slowy')` but you are waiting on `@slow`, without the `y`. It may have been a copy error and there may be an actual issue with the implementation, but I thought I'd double-check!

**Comment by jennifer-shehane** [comment]
Hey @bvanderneut, [`cy.wait()`](https://on.cypress.io/wait) should only be used to accompany `cy.route()` definitions, not accompany `cy.visit()`. If you want to increase the time that `cy.visit()` waits for your page to load, you can pass a `timeout` option to `cy.visit()` or update the [`pageLoadTimeout`](https://on.cypress.io/configuration#Timeouts)

If you're trying to do a request to an api and just want the bare results, look at [`cy.request()`](https://on.cypress.io/request)

**Comment by bvanderneut** [comment]
Sorry for the bad example and indeed this works :)

'''
cy.request({ url: 'https://independer.free.beeceptor.com/my/api/path', timeout: 40000 }); // API Path is setup to respond after 35seconds
'''

Or this way

'''
Cypress.config('responseTimeout', 40000);
    expect(Cypress.config('responseTimeout')).to.eq(40000);

    cy.request('https://independer.free.beeceptor.com/my/api/path'); // API Path is setup to respond after 35seconds
'''

Thanks for the good help!
