### ISSUE TITLE
npm install cypress --save-dev DELETED a NECESSARY npm package (specifically react-scripts)

### ISSUE THREAD

**Issue by metasean** [cypress-io/cypress#2447]
1. I ran a standard `npx create-react-app myapp` command.
2. Then I successfully added a [wallaby.conf.js](https://wallabyjs.com/) file. (fwiw: I used the clean create-react-app config file shown at https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app .)  Everything was going as expected at this point.
3. Then I ran:
```
npm install cypress --save-dev 
```

### Current behavior:

I got the following output, but **_most importantly it deleted my `react-scripts` directory!_** (If you don't know, this is kind of a *_critical_* package for a create-react-app.)

```bash
npm WARN rm not removing /Users/me/lerna-app/packages/app/node_modules/.bin/jest as it wasn't installed by /Users/me/lerna-app/packages/app/node_modules/jest
npm WARN rm not removing /Users/me/lerna-app/packages/app/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/me/lerna-app/packages/app/node_modules/fsevents/node_modules/node-pre-gyp
npm WARN rm not removing /Users/me/lerna-app/packages/app/node_modules/.bin/esvalidate as it wasn't installed by /Users/me/lerna-app/packages/app/node_modules/esprima
npm WARN rm not removing /Users/me/lerna-app/packages/app/node_modules/.bin/esparse as it wasn't installed by /Users/me/lerna-app/packages/app/node_modules/esprima
npm WARN rm not removing /Users/me/lerna-app/packages/app/node_modules/.bin/browserslist as it wasn't installed by /Users/me/lerna-app/packages/app/node_modules/browserslist

> cypress@3.1.0 postinstall /Users/me/lerna-app/packages/app/node_modules/cypress
> node index.js --exec install


Cypress 3.1.0 is already installed in /Users/me/Library/Caches/Cypress/3.1.0

npm notice created a lockfile as package-lock.json. You should commit this file.
+ cypress@3.1.0
added 59 packages, removed 1115 packages, updated 137 packages and moved 1 package in 94.708s
```

Why would Cypress remove 1115 packages, on a project not even 15 minutes old — that many packages certainly weren't outdated yet, and they weren't packages that it had previously installed.

### Desired behavior:

Not to delete `react-scripts` from `node_modules`.

### Steps to reproduce:

Presumably just:
`npx create-react-app myapp` - obviously you must have create-react-app installed
`npm install cypress --save-dev`

### Versions

Cypress 3.1.0
MacOS 10.12.3

---

# Follow-up Info

To get back to my pre-cypress state, I ended up having to do:
1. `git reset --hard HEAD`
2. delete my `node_modules` directory
3. `npm install` again

I guess I'm a gluten, because I then decided to try install Cypress again.  

This second time went as originally expected, with the following output (notice that it is distinctly different than the previous time I ran it):

```
> cypress@3.1.0 postinstall /Users/me/lerna-app/packages/app/node_modules/cypress
> node index.js --exec install


Cypress 3.1.0 is already installed in /Users/me/Library/Caches/Cypress/3.1.0

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ cypress@3.1.0
added 69 packages in 48.012s

```

I have no idea what the difference was between the two installs. 🤷‍♂️

I'm going to leave this issue here in case anyone else runs into a similar situation and (a) needs to get out of it and (b) has any additional info to add so that it might be avoided altogether.

**Comment by brian-mann** [comment]
I understand your cause for concern, and I'm not discounting your experience - but there is no way that the cypress package has anything to do with deleting or removing any folder from your file system. 

Cypress is open source and specifically the CLI (which is what is installed via the NPM package) is all right here: https://github.com/cypress-io/cypress/tree/develop/cli

There is nothing in there that deletes or removes anything. Without more information there's likely no way to pinpoint why exactly this happened to you, perhaps it is some kind of system issue, a git issue, an npm issue, or something else that's not immediately obvious. Cypress is downloaded and installed from npm on average over 20,000 times a day, and I can't imagine why that would have happened on that particular install. Sorry we can't be of more help, I'm going to close the issue for now, but reopen if we can get more details.

**Comment by bahmutov** [comment]
Just an idea of what might be happening here (and it is not cypress install, cause it does not touch node_modules but installed in global cache folder) - somehow you installed dependencies for React app, then installed Cypress (saving it as dev dependency) and did “npm prune”, removing most dependencies installed by create-react-app. I don’t know why it would have happened or if this is some setting in your .npmrc file, but we are 100% this is not Cypress doing it.

**Comment by metasean** [comment]
@brian-mann & @bahmutov 

First, thanks for doing such awesome work with Cypress! 💙

Second, thanks for looking into this and providing detailed responses! 🙏

Third, I _definitely_ didn't run `npm prune`.  

Before I posted this issue, I actually went back to my bash history, and —other than really basic git commands, specifically `git status`, `git add .`, `git commit`, & `git log`— I didn't do anything on the command line between `npx create-react-app myapp` and `npm install cypress --save-dev`.  

None of the git commands appeared to have any impact on my project, and I had `react-scripts test --env=jsdom --watchAll` running, so it would have been clear pretty quickly if they had.

I also hadn't heard of `npm prune` before this thread, so I can say with equal confidence that I've ever explicitly run it 😉.  Of course, that doesn't rule out some other command including it.  As previously mentioned, I checked my bash logs; the only command after `npx create-react-app myapp` that appeared to change anything in my repo, was `npm install cypress --save-dev`.  And it had just finished logging out the `npm WARN rm not removing ...` series of messages when my `react-scripts test --env=jsdom --watchAll` terminal blew up with error messages, namely letting me know that there was no `react-scripts`.

I have no idea what actually caused the deletion of the `npm-scripts` directory, but it _sure looked like it was something that the `npm install cypress --save-dev`_ command did.

**Comment by bahmutov** [comment]
Just to confirm, I did the following on my Mac

```
/tmp
$ npx create-react-app my-app
npx: installed 67 in 8.095s

Creating a new React app in /private/tmp/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.9.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-scripts > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > babel-preset-react-app > babel-preset-env > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 757 new dependencies.
info Direct dependencies
├─ react-dom@16.5.0
├─ react-scripts@1.1.5
└─ react@16.5.0
info All dependencies
├─ abab@1.0.4
├─ abbrev@1.1.1
├─ acorn-dynamic-import@2.0.2
├─ acorn-globals@3.1.0
....
✨  Done in 21.77s.

Success! Created my-app at /private/tmp/my-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app
  yarn start

Happy hacking!
```

Then 
```
$ cd my-app
$ ls -la
total 744
drwxr-xr-x    9 gleb  wheel     306 Sep  8 21:23 .
drwxrwxrwt   37 root  wheel    1258 Sep  8 21:23 ..
-rw-r--r--    1 gleb  wheel     285 Sep  8 21:23 .gitignore
-rw-r--r--    1 gleb  wheel  121322 Sep  8 21:23 README.md
drwxr-xr-x  966 gleb  wheel   32844 Sep  8 21:25 node_modules
-rw-r--r--    1 gleb  wheel     342 Sep  8 21:23 package.json
drwxr-xr-x    5 gleb  wheel     170 Sep  8 21:23 public
drwxr-xr-x    9 gleb  wheel     306 Sep  8 21:23 src
-rw-r--r--    1 gleb  wheel  247741 Sep  8 21:23 yarn.lock
```
`npm start` is working, serving app at port 3000
```
$ npm i -D cypress
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN rm not removing /private/tmp/my-app/node_modules/.bin/jest as it wasn't installed by /private/tmp/my-app/node_modules/jest
npm WARN rm not removing /private/tmp/my-app/node_modules/.bin/esvalidate as it wasn't installed by /private/tmp/my-app/node_modules/esprima
npm WARN rm not removing /private/tmp/my-app/node_modules/.bin/esparse as it wasn't installed by /private/tmp/my-app/node_modules/esprima
npm WARN rm not removing /private/tmp/my-app/node_modules/.bin/browserslist as it wasn't installed by /private/tmp/my-app/node_modules/browserslist

> fsevents@1.2.4 install /private/tmp/my-app/node_modules/fsevents
> node install

[fsevents] Success: "/private/tmp/my-app/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /private/tmp/my-app/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> cypress@3.1.0 postinstall /private/tmp/my-app/node_modules/cypress
> node index.js --exec install


Cypress 3.1.0 is already installed in /Users/gleb/Library/Caches/Cypress/3.1.0

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ cypress@3.1.0
added 243 packages from 265 contributors, removed 92 packages, updated 1091 packages and audited 13070 packages in 51.77s
found 0 vulnerabilities
```
```
$ cat package.json 
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.5.0",
    "react-dom": "^16.5.0",
    "react-scripts": "1.1.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "cypress": "3.1.0"
  }
}
```
Tried `npm start` - still working and serving app at port 3000.
Then just to check I ran
```
$ npm ls
npm ERR! extraneous: jest-cli /private/tmp/my-app/node_modules/jest-cli
npm ERR! error in /private/tmp/my-app/node_modules/jest-cli: ENOENT: no such file or directory, open '/private/tmp/my-app/node_modules/jest-cli/package.json'
npm ERR! extraneous: babel-loader@7.1.2 /private/tmp/my-app/node_modules/babel-loader
npm ERR! extraneous: node-pre-gyp@0.10.3 /private/tmp/my-app/node_modules/node-pre-gyp
npm ERR! extraneous: regexpu-core@2.0.0 /private/tmp/my-app/node_modules/regexpu-core
npm ERR! error in /private/tmp/my-app/node_modules/react-scripts/node_modules/babel-loader: ENOENT: no such file or directory, open '/private/tmp/my-app/node_modules/react-scripts/node_modules/babel-loader/package.json'
npm ERR! invalid: babel-loader /private/tmp/my-app/node_modules/react-scripts/node_modules/babel-loader
npm ERR! error in /private/tmp/my-app/node_modules/babel-plugin-transform-es2015-unicode-regex/node_modules/regexpu-core: ENOENT: no such file or directory, open '/private/tmp/my-app/node_modules/babel-plugin-transform-es2015-unicode-regex/node_modules/regexpu-core/package.json'
npm ERR! invalid: regexpu-core /private/tmp/my-app/node_modules/babel-plugin-transform-es2015-unicode-regex/node_modules/regexpu-core
npm ERR! error in /private/tmp/my-app/node_modules/svgo/node_modules/js-yaml: ENOENT: no such file or directory, open '/private/tmp/my-app/node_modules/svgo/node_modules/js-yaml/package.json'
npm ERR! invalid: js-yaml /private/tmp/my-app/node_modules/svgo/node_modules/js-yaml
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
```

Ok, so `npx create-react-app` uses yarn to install its dependencies, then I used `npm -D cypress`, so maybe the mixing of yarn and npm v6.3.0 is creating this weirdness?
```
$ yarn install
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 13.29s.
```
and then
```
$ npm ls
No error messages!
```
```
$ yarn list
No error messages!
```
so try using yarn commands with Cypress to be consistent?

**Comment by jennifer-shehane** [comment]
I also was not able to replicate. Did:

```
npm i -g create-react-app
npx create-react-app myapp
cd myapp
npm install cypress --save-dev
```

The `react-scripts` is still present after those directions.

**Comment by carlosrodriguezlumira** [comment]
Did the same thing to me, blew away 191 packages, thankfully the instructions to recover are right here.  _Maybe_ not instruct the user to use npm-install if this is incompatible with yarn?

**Comment by jennifer-shehane** [comment]
Hey @carlos-granados, Cypress is not incompatible with `yarn` and we do document how to install via `yarn` in our [install instructions](https://on.cypress.io/installing-cypress#yarn-add). 

It's generally not good practice to mix `yarn` and `npm` due to their differences in how they handle installing `node_modules`. There's actually nothing that Cypress can do to affect this.

**Comment by carlos-granados** [comment]
@jennifer-shehane you tagged me (@carlos-granados) but I think you wanted to tag @carlosrodriguezlumira

**Comment by jennifer-shehane** [comment]
Sorry! @carlosrodriguezlumira ^^
