### ISSUE TITLE
cy.origin() feature for cross domain not working

### ISSUE THREAD

**Issue by CypressBeginer05** [cypress-io/cypress#24485]
### Current behavior

Hi Everyone, 
I am trying to use Cypress v10.11.0 for one of my application. 
I am trying to use cy.origin() feature , but it simply gets timeout. I have gone through many existing related issues, but they are at least using login button when they gets landed to their application home page. 
But here in my case i want to internally redirect to  microsoftonline for authentication **without any click**, once use hits to application.com as mentioned below.

Here is my flow:
User hits www.application.com
User is redirected to www.login.microsoftonline.com **without any additional click**
User enters email and click on NEXT button,  password screen appears.
User enters password and click on Sign In button, user gets authenticated and redirected to www.application.com.

I am trying to script in cypress to test this flow .

I have used `before()` as I want to get login only once to application, and then it should not ask me for login for my other pages.
Does cypress supports such navigations?

### Test code to reproduce

Here is my code:
_commands.js_

```
Cypress.Commands.add('login', (email,password)=> {
  cy.session([email,password],()=>{
    cy.visit('https://application.com/'); // our application
    cy.origin('https://login.microsoftonline.com', () => {  
      cy.visit('/');
       
      cy.get('[name="loginfmt"]').type(email);
      cy.get('#idSIButton9').click();  // next button
      cy.get('#i0118').type(password);
      cy.get('#idSIButton9').should('be.visible').click({force: true});
    });

    cy.get("h1").should("contain","MyApp");
  });
});
```

_myLogin.cy.js_

```
describe('Authenticate', () => {
    before(() => {
       cy.login('tst.user01@test.com','Test@12345');        
    });

    it('Show homepage once logged in', () => {
     //  cy.visit('/');
    });
});
```

### Cypress Version

v10.11.0

### Node version

v14.18.1

### Operating System

ubantu 5.15

**Comment by mschile** [comment]
Hi @CypressBeginer05 👋 , yes, you should be able to login to microsoft even when the application redirects. Before you optimize with `cy.session` and the custom login command, I would suggest getting the microsoft login to work first.

Here is some sample code to try. I'm also setting [`experimentalModifyObstructiveThirdPartyCode`](https://docs.cypress.io/guides/references/experiments#Configuration) since I believe microsoft does some framebusting.

**cypress.config.js:**
```js
export default defineConfig({
  // your other config here

  e2e: {
    baseUrl: 'https://application.com',
    experimentalSessionAndOrigin: true,
    experimentalModifyObstructiveThirdPartyCode: true,
    // your other config here
  }
})
```

**test.cy.js:**
```js
it('Show homepage once logged in', () => {
  cy.origin('https://login.microsoftonline.com', () => {  
    // visit the application inside cy.origin since we automatically redirect to microsoft login and we don't want to change the top url
    cy.visit('https://application.com/')
       
    cy.get('[name="loginfmt"]').type(email);
    cy.get('#idSIButton9').click();  // next button
    cy.get('#i0118').type(password);
    cy.get('#idSIButton9').should('be.visible').click({force: true}); // I'm assuming this redirects back to your application
  });

  cy.get("h1").should("contain","MyApp");
})
```

**Comment by CypressBeginer05** [comment]
Thank you @mschile for quick suggestion. After your suggestions now I am able to login to my application after microsoft authentication.
I have used cy.session here as I want to keep my session live and this login will get called only once, and not required for other test scripts of my application.
Here is code 
**cypress.Config.js**

 
` export default defineConfig({`
  ` e2e: {`
`    baseUrl: 'https://application.com',`
`    experimentalSessionAndOrigin: true,`
`    experimentalModifyObstructiveThirdPartyCode: true,`
  
  `}`
`})`

**Command.js**
`Cypress.Commands.add('loginSession', (email,password)=> {`

`cy.session([email,password],()=>{`
` cy.origin('https://login.microsoftonline.com', () => {  `
 `    cy.visit('https://application.com/')`
       
    cy.get('#i0116').type(email
    );
    cy.wait(3000);
    cy.get('#idSIButton9').click();
    cy.wait(3000);
         cy.get('#i0118').type(password);
         cy.wait(3000);
         cy.get('#idSIButton9').click();
         cy.wait(3000);
         cy.get('#idSIButton9').click(); });
 `cy.wait(3000);`
`cy.get('.MuiBox-root > .MuiToolbar-gutters > :nth-child(1)')
.should("contain","Hallo!");`
`cy.on('uncaught:exception',()=>{`

`return false;})`   
  `}); });`

**login.cy.js**

`describe('Authenticate', () => {`
`    before(() => {`
`       cy.loginSession('YourEmailid','password');`
        
`    });`

    it('Show homepage once logged in', () => {
       cy.visit('/');
     
    });
   `});`

**Comment by simmimourya** [comment]
I had a similar issue, but with Okta, this is what worked for me. Follow this documentation for more details: https://docs.cypress.io/api/commands/origin

command.ts

```
declare global {
  namespace Cypress {
    interface Chainable<Subject> {
      login(username, password): Chainable<any>;
    }
  }
}

// Use the custom login command to log in via Okta
Cypress.Commands.add('login', (username, password) => {
  const sentArgs = {
    username: username,
    password: password,
  };

  cy.origin(
    'https://okta.com',
    { args: sentArgs },
    ({ username, password }) => {
      cy.visit('https://application.com');
      cy.get('#input28').type(username);
      cy.get('#input36').type(password);
      cy.get(
        'input.button.button-primary[type="submit"][value="Sign in"]',
      ).click();
      cy.wait(3000);
      cy.on('uncaught:exception', () => {
        return false;
      });
    },
  );
});

export {};
```

This two flags are turned on in cypress.config.json

```
experimentalOriginDependencies: true,
experimentalModifyObstructiveThirdPartyCode: true
```
    
    
  test.spec.ts
  
  ```  
  before(() => {
  const username = 'user';
  const password = 'pass';
  cy.login(username, password);
});

  it('should successfully visit application', () => {
    cy.visit('/');
  });
 ```
