### ISSUE TITLE
Performance issue with the cypress

### ISSUE THREAD

**Issue by RohithQualiT** [cypress-io/cypress#24487]
### Current behavior

Tool is taking very much longer time than usual to run the test cases on both locally & dashboard. Tool is making much irritation with lots of flaky tests that are caused due to cypress. Please go through the video once: https://www.loom.com/share/04324e2221034e24819e7401ca168048

### Test code to reproduce

 enterSearchTerm(searchText) {
    cy.get(selectors.searchField).clear().type(searchText);
    cy.get(selectors.searchField).type('{enter}');
  }   where searchField:'input.search-input',

### Cypress Version

10.10.0

### Node version

16.16.0

### Operating System

Win 64

**Comment by lmiller1990** [comment]
That looks painful, quick question:

> longer time than usual

Suggests this was not always the case, do you know when this was introduced (eg, did you update Cypress version, update some dependency, something changed)?

Also any way we can access the test instance you are using (if we cannot reproduce, hard to debug).

**Comment by amehta265** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
