### ISSUE TITLE
enable typing in  browser console 

### ISSUE THREAD

**Issue by mudit94** [cypress-io/cypress#24482]
### What would you like?

to be able to execute commands which we run in browser console, and use assertions on the output

### Why is this needed?

to be able to run browser console commands in cypress

**Comment by mschile** [comment]
@mudit94, I'm not sure I am following your request. Could you please go into more detail about your request and possibly provide code examples of what you are trying to do. Thanks!

**Comment by mschile** [comment]
Unfortunately we have to close this request due to inactivity. Please comment if there is new information to provide concerning the original request and we can reopen.
