### ISSUE TITLE
how to use regex on contains()

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#2449]
Hello,

I'm sorry, this is not a bug or feature but I just want a confirmation.

If I want to get any special character and maj character on the function `.contains('aaa')` should I write the function this way : 
`.contains(/aaa/gi)` without the ''

Best regards.

**Comment by jennifer-shehane** [comment]
I'm not familiar with what regex to use for those special characters, but yes, you write `.contains(/aaa/gi)` without the quotes `''`

In the future, we recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Issues in our GitHub repo are reserved for potential bugs or feature requests. We want our team to spend all the time we have building a better product and hope you understand. ☺️
