### ISSUE TITLE
Cypress crashes in Docker in servercore:ltsc2022

### ISSUE THREAD

**Issue by rasmusrim** [cypress-io/cypress#24496]
### Current behavior

The tests do not run.

This problem will turn up:

    cypress:server:browsers:browser-cri-client error finding browser target, maybe retrying { delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:49191 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 49191 } }

And then crash with this message:

```
2022-11-02T10:02:16.549Z cypress:server:cypress exiting with err Error: connect ECONNREFUSED 127.0.0.1:49191
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
 {
  isCypressErr: true,
  type: 'CDP_COULD_NOT_CONNECT',
  details: 'Error: connect ECONNREFUSED 127.0.0.1:49191\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n',
  messageMarkdown: 'Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.\n' +
    '\n' +
    'This usually indicates there was a problem opening the Edge browser.\n' +
    '\n' +
    'The CDP port requested was `49191`.',
  originalError: Error: connect ECONNREFUSED 127.0.0.1:49191
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
   {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 49191
  },
  stackWithoutMessage: '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n'
}
2022-11-02T10:02:16.549Z cypress:server:cypress calling exit 1
2022-11-02T10:02:16.549Z cypress:server:cypress about to exit with code 1
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Edge browser.

The CDP port requested was 49191.

Error: connect ECONNREFUSED 127.0.0.1:49191
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

### Desired behavior

The tests should run 

### Test code to reproduce

Run a Cypress test suite inside a servercore:ltsc2022 container.

I have created a repo to reproduce here: https://github.com/rasmusrim/cypress-crash

### Cypress Version

10.11.0

### Node version

18.12.0

### Operating System

Windows servercore:ltsc2022 through docker

### Debug Logs

```shell
Log too big to paste here. You can find it here: https://raw.githubusercontent.com/rasmusrim/cypress-crash/main/log.txt
```

**Comment by mschile** [comment]
Hi @rasmusrim 👋, thanks for taking the time to log this issue. Unfortunately, we don't offer support for `servercore:ltsc2022` images. We do offer linux based images in our [cypress-docker-images](https://github.com/cypress-io/cypress-docker-images) repo if you are able to use those.

Otherwise, you may want to check out [community chat](https://on.cypress.io/chat) to see if anyone has been successful in creating a `servercore:ltsc2022` image.
