### ISSUE TITLE
Jira Cloud integration is broken

### ISSUE THREAD

**Issue by kevin-tst** [cypress-io/cypress#24500]
### Current behavior

Step 5 of your instructions doesn't work.
https://docs.cypress.io/guides/dashboard/jira-integration#Installing-the-Jira-integration

### Cypress Version

10.3.1

### Node version

16.16.0

### Package Manager

npm

### Package Manager Version

5.0 

### Operating system

Mac

### Operating System Version

5.0

**Comment by conversayShawn** [comment]
Hi @kevin-tst 
Thanks for getting the requested information.

**Comment by conversayShawn** [comment]
This issue has been resolved by an internal PR.

If you continue to experience this issue, kindly open a new ticket.
