### ISSUE TITLE
Mismatch of function signatrues for `.each` method between cypress and jQuery

### ISSUE THREAD

**Issue by jeffscottward** [cypress-io/cypress#24502]
### Current behavior

Flip flopping back and fourth between return value types depending on if you are working on a Cypress object or a JQuery object caused major confusion for me.

<img width="1022" alt="Screenshot 2022-11-02 at 11 05 59 AM" src="https://user-images.githubusercontent.com/1263486/199526806-9c50f6d5-a5fe-486c-a4b7-6c9b059c4d16.png">
<img width="999" alt="Screenshot 2022-11-02 at 11 06 45 AM" src="https://user-images.githubusercontent.com/1263486/199526807-605ddabc-0fd9-4b20-9bd6-db7de0b6540d.png">

### Desired behavior

Have the signatures be the same.

### Test code to reproduce

```
  cy.get("*").each(($topEl) => {
    cy.log('$topEl', $topEl)
```     
```
  $topEl.each(($innerEl) => {
    cy.log('$innerEl', $innerEl)
```

`innerEl` will actually be an index, not a an element.

Perhaps this is a faulty design choice on the part of the jQuery team long ago, but this confused the hell out of me for a minute.

### Cypress Version

latest

### Node version

latest LTS

### Operating System

Mac Ventura

**Comment by emilyrohrbough** [comment]
@jeffscottward This is quite confusing! I hadn't noticed this before. However, this isn't a change we want to make in the codebase. The iterible structure matches `Array.forEach` which is `forEach((element, index, array) => { /* … */ })`. Changing this behavior would be a breaking change we don't want to take on.
