### ISSUE TITLE
Implement Create from React Component

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#24515]
### What would you like?

Implement Create from React Component based on designs and [tech brief](https://github.com/cypress-io/cypress/issues/23525).

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24515?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by astone123** [comment]
I'm not sure that this is the ticket we want. Once the tech brief is complete I think we should create multiple implementation issues to complete the feature.
