### ISSUE TITLE
Implement CT Nightly Builds Spike

### ISSUE THREAD

**Issue by amehta265** [cypress-io/cypress#24532]
Related: [spike documentation](https://github.com/cypress-io/tech-briefs/tree/main/briefs/ct-automated-nightly-builds)

To do:
1. Create testing repository with single framework/bundler projects and basic component tests
2. Update the [spike implementation](https://github.com/cypress-io/cypress-component-testing-apps/tree/spike-nightly-frameworks)

Note: The branch name for this spike is `spike-nightly-frameworks`. The Tech brief will be updated in the future to reflect this

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24532?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by astone123** [comment]
using the https://github.com/cypress-io/ct-automation repo for this issue
