### ISSUE TITLE
[Run All Specs] implement experimentalRunAllSpecs config flag

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#24548]
We need an `experimentalRunAllSpecs` Boolean property in the config. Its default value should be `false`. When configured, by users, as `true` it will allow the UI features for running groups of specs to be displayed.

## Acceptance Criteria

`experimentalRunAllSpecs` is a valid top-level boolean config option. The experiment might not support component testing at the outset but it's the kind of option that could apply to both testing types, so no need to nest it under `e2e`.

`experimentalRunAllSpecs` should appear in the Experiments section of the settings page:

<img width="1135" alt="Screen Shot 2022-11-08 at 7 46 36 AM" src="https://user-images.githubusercontent.com/8340719/200571853-e4babb40-189c-44ad-8456-588bd33fe5dd.png">

A PR to the Cypress docs must be made at the same time as this flag is added.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24548?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by baus** [comment]
Add docs PR
