### ISSUE TITLE
Upgrade request dependency

### ISSUE THREAD

**Issue by asantos3026** [cypress-io/cypress#2455]
### Current behavior:
We are getting a request dependency error when using Cypress version 2.1
```warning cypress > request > hawk > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer```

This is preventing us from installing Cypress and running our UI tests in our build pipeline.

### Desired behavior:

We would like this dependency to be updated

**Comment by maciejmyslinski** [comment]
I'd love to take over this one.
Today I speak about Open Source at meet.js Kraków meetup to encourage peeps to engage.
I'd like to show them live how to contribute using this ticket as an example.
Thank you for creating this opportunity! ❤️

**Comment by jennifer-shehane** [comment]
@maciejmyslinski Sounds great! Please let us know if you have any questions.

**Comment by brian-mann** [comment]
Released in [`3.1.3`](https://docs.cypress.io/guides/references/changelog.html#3-1-3).
