### ISSUE TITLE
Debug log for module api

### ISSUE THREAD

**Issue by yousuftelus** [cypress-io/cypress#24554]
### What would you like?

I'd like to have the feature that we currently have when running cypress in command line **[Enable debug logs](https://docs.cypress.io/guides/guides/command-line#Enable-Debug-Logs)**  : `DEBUG=cypress:* cypress run` in the module api meaning when running cypress via code base ( `cypress.run` or `cypress.open` ). So basically to be able to add a config option like this: 
```
cypress.run({
  reporter: 'junit',
  browser: 'chrome',
  config: {
    baseUrl: 'http://localhost:8080',
    video: true,
  },
 debugLog: "*" ( possible values: `*`, `cli`, `launcher` ...etc )
})
```

### Why is this needed?

Currently am using [cypress image](https://hub.docker.com/r/cypress/base) to dockerize my app and run cypress tests but when app deployed on openshift cypress is failing to run even though locally running the same docker image and running cypress tests works perfectly so would like to be able to see detailed log of why cypress is failing to run in order to be able to debug this issue.

**Comment by webInRoad** [comment]
+1

**Comment by emilyrohrbough** [comment]
@yousuftelus Can you share how you are running this file? You should be able to set the environment variable on the script that is programmatically running the Cypress module. I would expect something like this to work:

```bash
DEBUG=cypress:* node run-cypress.js
```

**Comment by yousuftelus** [comment]
@emilyrohrbough Indeed that works 👍  and on my side found an alternative where I export it as an environment variable `ENV DEBUG=cypress:*` in dockerfile and works as well. Thanks closing the issue.

**Note**: Unfortunately couldn't fix my main issue even with more info with Debug mode so creating a new issue: https://github.com/cypress-io/cypress/issues/25372
