### ISSUE TITLE
App crash with no explanation during Quick configuration

### ISSUE THREAD

**Issue by NabeelFz** [cypress-io/cypress#24561]
### Current behavior

After clicking "continue" on the "Configuration files" page, the application closes and the following message is displayed:

Opening Cypress...

UNKNOWN: unknown error, watch
Error: UNKNOWN: unknown error, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
If I reopen the application, I return to the "Welcome to Cypress!" page and I have a lot of alerts that say:
Warning: Unexpected Internal Error

We encountered an unexpected internal error. Please check GitHub or open a new issue if you don't see one already with the details below:

clicking on "E2E Testing" closes the application and displays the following messages:

UNKNOWN: unknown error, watch
Error: UNKNOWN: unknown error, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)

But in the CLI mode this is working fine as expected.

### Test code to reproduce

1. Enter the command to open the cypress in vs code terminal
2. Click on continue
3. after loading multiple error seen 
4. after click the e2e the window crashes and closed.

### Cypress Version

10.11.0

### Node version

v14.15.0

### Operating System

windows 10 pro

**Comment by ryanthemanuel** [comment]
Thanks for opening this issue @NabeelFz. `UNKNOWN: unknown error, watch` appears to be an issue with chokidar, which is what we use to track on file changes in your project. After looking around a bit, it seems like there can be issues on Windows with using chokidar on network drives or non-C: drives. Can you verify what the path is to your project?

**Comment by ryanthemanuel** [comment]
@NabeelFz, we have a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.

**Comment by birenjack** [comment]
I have same problem
