### ISSUE TITLE
Migrate Cypress WebExtension to use Manifest v3

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#24566]
Chrome will begin disabling Manifest v2 extensions by June 2023: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

The Cypress WebExtension currently uses Manifest v2, so we need to migrate it to v3. We shouldn't wait until the last minute to do this since many users use old versions of Cypress with newer versions of Chrome.

If Manifest v3 breaks our use case for the WebExtension in Firefox, we may need to continue building a v2 extension while also building a v3 extension for Chrome.

Migration guide: https://developer.chrome.com/docs/extensions/mv3/mv3-migration/

**Comment by flotwig** [comment]
Firefox 101 has beta support for v3: https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

Unless we want to bump the minimum FF version (and possibly Chrome version, can't find good info on the first version of Cr that supported v3), we'll have to maintain a v2 as well.

**Comment by flotwig** [comment]
It may also be possible for us to pass a CLI flag or Blink feature to Chrome to delay this as long as possible and normalize this behavior through the versions.

**Comment by jennifer-shehane** [comment]
This work is completed in https://github.com/cypress-io/cypress/pull/27888 and will be released in our next release.
