### ISSUE TITLE
Cypress typescript custom command not working v10.11.0

### ISSUE THREAD

**Issue by CypressBeginer05** [cypress-io/cypress#24578]
### Current behavior

Hi Cypress Team,
I am trying to create a simple test using typescript along with Command.ts .But its giving me error as **typeLogin(my command)is not a function** as mentioned in below.
![typescript_not_working](https://user-images.githubusercontent.com/117148580/200493728-20f6067c-5cbe-486a-9fda-f86b1c117087.png)

**Basically I am also looking for all required configuration required for typescript for cypress version 10.11.0.** May be I am missing some config and due this I am getting this error.

### Desired behavior

My Practice2.ts should be able to call my custom command using typescript.

### Test code to reproduce

**_tsconfig.json_**

`{`
`  "compilerOptions": {`
`   "target": "es5",`
 `  "outDir": "dist",`
`   "lib": ["es5", "dom"],`
`   "types": ["cypress","node"]`
` },`
` "include": ["**/*.ts"]`
`}`

**_cypress.config.ts_**

` import { defineConfig } from 'cypress'`
`export default defineConfig({`
`  e2e: {`
`    baseUrl: 'https://dev.path.vodafone.de/',`
 `   experimentalSessionAndOrigin: true,`
  `  experimentalModifyObstructiveThirdPartyCode: true,`
  `}
`})`

**_command.ts_**

`const typeLogin = (username,password)=>{`
`    cy.visit('https://webgit.kabeldeutschland.de/login');`
    cy.get('#j_username').should('be.visible').type('Username');
`    cy.get('#j_password').should('be.visible').type('userpwd');`
`   cy.get('#submit').click();`
`cy.url().should('contain', '/dashboard');`

`}`
`Cypress.Commands.add("typeLogin",typeLogin);`

**_index.ts_**

`declare namespace Cypress{`
`    interface Chainable{`

`        typeLogin: (username: string,password: string)=> void;`
`    }`
`}`

**practice2.ts**

`describe('Authenticate', () => {`
`  before(() => {`
`     cy.typeLogin('Pravin.Gate1','Ichimoku@07');`
`  });`
`  it('Show homepage once logged in', () => {`
`    cy.url().should('contain', '/dashboard');`
`     cy.wait(1000);`
`     cy.get('#repositories-menu-trigger')`
`     .click(); `
 `    cy.wait(1000);`
  `   cy.get(':nth-child(1) > .repository-link > .item-wrapper > .item-name')`
   `  .click();`
   `});`
`});`

### Cypress Version

10.11.0

### Node version

v14.18.1

### Operating System

ubantu5.15

**Comment by lmiller1990** [comment]
Your code looks fine. Can you post a repository with the exact code?

The default in Cypress 10 for commands is `cypress/support/e2e.js` (or `ts`). Can you try renaming your commands file?

**Comment by CypressBeginer05** [comment]
Thank you @lmiller1990 , issue is resolved now. Yes my code was correct. I just created again a new cypress typescript project and then it worked without any issue. Earlier I had created only cypress project and then added manually ts files and typescript.
