### ISSUE TITLE
Flaky test: "App: should re-query for executing runs" (windows mainly)

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#24575]
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/45562/workflows/8510305c-0f92-41d6-b8fb-2abaa50db11a/jobs/1914521/tests#failed-test-2

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/963e184446dffe627c7c412c72c428be0da388b0/packages/app/cypress/e2e/runs.cy.ts#L888-L955

These two are flaky on windows.

Edit: First one is fixed  https://github.com/cypress-io/cypress/pull/24833

### Analysis

Not sure if it's race condition, I've seen it flake on linux too, but much less.

These tests override `window.setTimeout` and stub out multiple GraphQL requests - it's quite confusing since there's so much stubbing going on, it's not entirely clear if the flake is in the app code or the test code.

I think we should consider an alternative way to orchestrate these tests that relies less on stubbing, and is more deterministic.

### Cypress Version

10.11

### Other

It's particularly bad on windows, I can reproduce it locally about 90% of the time.

**Comment by lmiller1990** [comment]
Works great in linux! :linux master race:

![image](https://user-images.githubusercontent.com/19196536/200463947-3bc4b91d-a256-4207-895f-aad2b5595211.png)

**Comment by lmiller1990** [comment]
On windows, the stubbed GraphQL response is missing the expected properties. `commitInfo`, `totallDuration` etc are `null`. This is not the case on linux and macOS. I do not know why - I went down to the underlying `cross-fetch` and `node-fetch`, everything is fine and present.

At this point, the data is present - this is the last part before the stubbed response is returned. https://github.com/cypress-io/cypress/blob/e3de5e77b51ee215e4bb9aa5cb161daccf874550/packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts#L242

On the other end, in the browser, it's missing properties. I cannot see any other layer in between the above line and the browser where I can debug this, though.

## MacOS - has all properties, runs are rendered

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/19196536/204957936-c9abde9d-6967-41a3-8e7d-1a8603c8a4bd.png">

## Windows - missing properties, not rendered

![image](https://user-images.githubusercontent.com/19196536/204957442-35a29db8-adf7-4ef5-a36d-1628bed67790.png)

**Comment by lmiller1990** [comment]
I tried changing urql to go over HTTP instead of Web Sockets. It works better, but the tests are still not reliable. The way they are written is confusing and unideal. Basically, this page has two ways to get runs:

1. initial query
2. refetch latest w/ a mutation

Here's a screenshot of a bunch of requests running on this page in this test:

![image](https://user-images.githubusercontent.com/19196536/205198814-fb0632a6-5039-4225-bbe4-72277c10f1f1.png)

The way this is currently handled is conditionals, [here](https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/runs.cy.ts#L898-L907) (took a long time to figure out exactly how this worked)

```js
cy.remoteGraphQLIntercept(async (obj) => {
        await new Promise((resolve) => setTimeout(resolve, 100))

        if (obj.result.data?.cloudNode?.newerRuns?.nodes) {
          obj.result.data.cloudNode.newerRuns.nodes = []
        }

        if (obj.result.data?.cloudNodesByIds) {
          obj.result.data?.cloudNodesByIds.map((node) => {
            node.status = 'RUNNING'
          })

          obj.result.data.cloudNodesByIds[0].status = 'PASSED'
        }

        return obj.result
      })
```

It's really difficult to look at these tests and figure out what is going on. You also need to grok we overwrite `window.setTimeout`, but only for the one polling timeout:

https://github.com/cypress-io/cypress/blob/05dc4a5ecdffbb30b49e100857c4bffe36f86d16/packages/app/cypress/e2e/runs.cy.ts#L878-L885

What would be nicer (and what I tried, but no luck, since there's so many requests going, it's hard to reliably intercept and make a deterministic test):

```js
cy.intercept(`query-Runs`, { 
  return [passingRun, runningRun]
})

cy.runQuery()

cy.intercept(`mutation-LatestRuns`, { 
  return [passingRun, passingRun]
})

cy.runMutation()
```

Something more declarative - I think we need more fine grained control over the GraphQL stuff. Just 'patch the flake' isn't going to cut it - I think we might want to re-examine how we do this testing.

**Comment by marktnoonan** [comment]
Confirmed this is still passing locally 👍 

@lmiller1990 or @warrensplayer do we have an epic for upcoming gql e2e tests?

#23474 seems likely related

**Comment by lmiller1990** [comment]
Not yet -- upcoming work is more for App<>Cloud testing, not to fix flake in general, but we might get some free flake-fixes for free.

Docs issue: https://github.com/cypress-io/cypress/issues/25653

**Comment by jennifer-shehane** [comment]
Closing since this is likely stale
