### ISSUE TITLE
White screen after running large set of test cases in cypress test runner 

### ISSUE THREAD

**Issue by Kname80** [cypress-io/cypress#24570]
### Current behavior

Im running 150 test cases locally in cypress test runner but when the test get close to finish the test runner turn into white page as displayed in the image. I could not find any information that can help with the issue.
![image](https://user-images.githubusercontent.com/41926411/200399447-f2e469b0-bc87-4db4-858c-384aa5e6e2dc.png)

### Test code to reproduce

Unfortunately , I can not share the code since is private .

### Cypress Version

8.3.0

### Node version

v14.18.1

### Operating System

windows 10

**Comment by nagash77** [comment]
Hi @Karim10k .  Im sorry you are having difficulties.  Unfortunately, with the provided information we will not be able to provide much assistance.  I would also suggest you try running on the latest Cypress to see if the problem resolves itself by upgrading.  In the mean time I am going to close this issue until you can provide us more information that would enable us to recreate your problem internally.  Feel free to comment on this issue and we will see it.
