### ISSUE TITLE
Cypress 10 throws error reading js config file: SyntaxError: /frontend/cypress.config.js: Unexpected token c in JSON at position 0

### ISSUE THREAD

**Issue by jraigosaOC** [cypress-io/cypress#24574]
### Current behavior

Hello, I'm trying to transition our CI e2e runs to run Cypress 10.x.  It runs on a Docker container via BuildKite and it's currently loading 10.11.0.  It was previously complaining that it couldn't find the config file (using js format cypress.config.js).  I pointed the cypress run CLI to the file using --config-file param and now the file is being found but I'm getting an error that seems to be expecting the old json config file format

SyntaxError: /frontend/cypress.config.js: Unexpected token c in JSON at position 0

Cypress versions on the container show as:
Cypress package version: 10.11.0
Cypress binary version: 10.11.0
Electron version: 21.0.0
Bundled Node version: 16.16.0

I don't see a config file format flag in the cypress run CLI documentation but it seems like Cypress 10 should not be having this issue.  Don't see this exact issue when I search github/SO/google.

The config file works fine when I run Cypress locally

### Desired behavior

Cypress should run and use the existing config file.

### Test code to reproduce

Dont know if I can give repro steps w/out overspecifying CI build env.

Loading the docker image below and running cypress run command:

cypress run -s cypress/e2e/focusfire/**/* --config-file=./frontend/cypress.config.js -e test_domain=test

the command works to start the test run locally

### Cypress Version

10.11.0

### Node version

v16.16.0

### Operating System

https://hub.docker.com/r/cypress/included:10:11

**Comment by ryanthemanuel** [comment]
Thanks for opening this issue @jraigosaOC. Is there any way you could share the contents of the `cypress.config.js` file that you are using? Even if you need to redact anything that shouldn't be shared publicly?

**Comment by jraigosaOC** [comment]
Thanks for the response @ryanthemanuel    Yes I can:

So I pared it down to just what the Cypress 10 migration UI generated, plus baseUrl for developing on local

const { defineConfig } = require('cypress')

module.exports = defineConfig({
  e2e: {
    baseUrl: 'https://focusfire.local.opcity.com'
  }

**Comment by jraigosaOC** [comment]
Initially I had copied some values from cypress.json. I could post those, but I get the same error w the config file above.  It seems to be expecting json from the error.

**Comment by jraigosaOC** [comment]
@ryanthemanuel this turned out to be

**Comment by jraigosaOC** [comment]
This turned out to be an issue w/ CI setup.
