### ISSUE TITLE
[Run All Specs] Spike: Handle "Run All Specs" for Component Testing

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#24585]
### What would you like?

This was not a feature of Cypress 9 and below. Once https://github.com/cypress-io/cypress/issues/24469 is implemented and working for e2e we should see what the level of effort is to get "Run All" working for component testing.

### Outcome of the spike

Create an issue detailing the changes needed to support "run all" for CT that can be estimated.

**Comment by ZachJW34** [comment]
Spiked into this, got something rough working for both Webpack and Vite


https://user-images.githubusercontent.com/25158820/202501358-442f68f3-0e6f-44e1-9278-a6cf10be21fe.mov



https://github.com/cypress-io/cypress/tree/zachw/run-all-specs-ct

### Summary

The mechanism by which specs are loaded on the frontend are similar between e2e and ct. Whenever a user chooses a spec, an iframe is created with the url containing the path to the spec file to execute. This in turn makes a network request to the backend that resolved an html file that executes:

```js
// e2e 
Cypress.onSpecWindow([
  { requestUrl: 'http://localhost:xxxx/<path-to-support-file>' },
  { requestUrl: 'http://localhost:xxxx/<path-to-spec-file>' },
])

// ct
Cypress.onSpecWindow([
  { load: () => import('<path-to-support-file>') },
  { load: () => import('<path-to-spec-file>') },
])
```

Run all specs relies on changing the payload given to `onSpecWindow` to contain not just `support + spec` but `support + all specs selected`. This is done by changing the iframe url to contain the `__all` keyword allowing the backend to generate an html containing this expanded payload.

Cypress e2e is a bit more straightforward as specs are compiled on demand with Webpack. As you as the `requestUrl` resolves a javascript file, we will attempt to compile and serve it.

Cypress ct differs in that the dev-server is already up and running, so the list of specs needs to be injected into the currently running compilation (either Vite or Webpack). This process is not much different from how the dev-server gets alerted to specs that have been added or deleted, utilizing the dev-server ipc to communicate from the main Cypress process to the config/dev-server process.

### Implementation

#### Webpack

The process of injecting the `runAllSpecs` list into the dev-server is very similar to the `dev-server:specs:changed` event wherein the main Cypress process, upon detecting a new spec, sends the dev-server process this event and a payload containing all of the valid specs. These specs are then injected into the Webpack process via the `CypressCTWebpackPlugin`, and the Cypress entry file is _touched_ to trigger a new compilation. Upon compilation success, the IPC is again used to communicate back to the parent process, triggering a rerun of the current spec (if applicable).

We can setup a very similar event to communicate when the `runAllSpecs` event occurs and inject the list of specs into the webpack compilation. The determinant for running a single spec vs this `runAllSpec` is again the iframe url with the `__all` key.

#### Vite

Unlike Webpack, Vite compile on demand similar to e2e. We can utilize the same dev-server IPC event for when the `runAllSpecs` event occurs to communicate to the vite dev-server process and inject into the compilation. Some refactor is required of the Vite entry file as it only relies on browser data as to how to decide to choose the spec to run. The `runAllSpecs` list is available at build time, so this list needs to be injected into the entry similar to how Webpack handles the specs to run. Then, once an iframe with a url containing the `__all` key is requested, this list of specs will be sent to `onSpecWindow`.
