### ISSUE TITLE
No tests found when directory name has [] (Component Testing with Next.js)

### ISSUE THREAD

**Issue by levaleks** [cypress-io/cypress#24588]
### Current behavior

Hello, I encountered a similar issue previously reported here https://github.com/cypress-io/cypress/issues/20573 
Running tests inside a square-bracket folder lead to a "No tests found." error.
![Screenshot 2022-11-08 at 16 28 23](https://user-images.githubusercontent.com/16807233/200591937-cac1b1fe-9d27-46ba-b1cc-b5cd52a24e7c.png)

### Desired behavior

Tests inside square-bracket folders work in a usual way.

### Test code to reproduce

Just wrap a folder name containing component tests in [].

### Cypress Version

10.11.0 and 11.0.1

### Node version

16.15.0

### Operating System

macOS 12.6

### Other

Next – 12.3.0
dev server framework – 'next'
dev server bundler – 'webpack'

**Comment by levaleks** [comment]
Update – the problem reproduces for Cypress 11 as well :(

**Comment by marktnoonan** [comment]
.Thanks @levaleks, I was able to reproduce, routed to CT team.
