### ISSUE TITLE
Regression with cy.origin ?

### ISSUE THREAD

**Issue by GeryDuComptoirDesPharmacies** [cypress-io/cypress#24589]
### Current behavior

Hi,

I got a test case who pass in cypress 10.9.0 and now failed in cypress 10.10.0 and above.

I try to validate payment information from my payment provider and I got the payment provider API return an error 500 only for cypress 10.10.0 and above and my test failed.

The snippet I'm running in both version 10.9.0 and 10.10.0 : 
```			
cy.origin('https://api.sandbox.mangopay.com', { args: { url } }, ({ url }) => {
	cy.visit(url)
	cy.get('.btn-confirm').click()
})
```

`url = /public/mandates/xxxxxx/xxxxxxxxx`

### Desired behavior

The test should pass like in 10.9.0

### Test code to reproduce

```
cy.origin('https://api.sandbox.mangopay.com', { args: { url } }, ({ url }) => {
	cy.visit(url)
	cy.get('.btn-confirm').click()
})
```

### Cypress Version

10.10.0 and 10.11.0

### Node version

v16.16.0

### Operating System

macOS 12.4 and Linux Debian - 11.4

### Debug Logs

```shell
I have this log boucle in infini :


  cypress:server:socket-base automation:request get:cookies {} +250ms
  cypress:server:automation:cookies getting:cookies {} +249ms
  cypress:server:automation:cookies received get:cookies [ { <coockies> }]
```
```


### Other

_No response_

**Comment by ryanthemanuel** [comment]
Hi @GeryDuComptoirDesPharmacies . Thank you for logging an issue. What is your baseUrl in your project? Is it publicly available so I can test it?

**Comment by ryanthemanuel** [comment]
@GeryDuComptoirDesPharmacies, we have a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Hi everyone,

We succeeded workaround the problem, adding `samesite=none` + `secure` on the `set-cookie` instruction returned by the server.

Original `set-cookie` header :
```
Set-Cookie:
TS0149b4e3=XXXXUUIDXXXX; Path=/; Domain=.api.sandbox.mangopay.com
Set-Cookie:
my_ps=YYYYHASHYYYY; expires=Tue, 24-Oct-2023 08:13:05 GMT; path=/; Httponly; Secure
```

Our code : 
```
Cypress.Commands.add('disableSameSiteCookieRestrictions', () => {
   cy.intercept('*', (req) => {
      req.on('response', (res) => {
         if (!res.headers['set-cookie']) {
            return;
         }

         const disableSameSite = (headerContent) => {
            let newValue;
            if (headerContent.includes("samesite")) {
               newValue = headerContent.replace(/samesite=(lax|strict)/ig, 'samesite=none');
            } else {
               newValue = headerContent + ';samesite=none';
            }
            if (!newValue.includes("secure")) {
               newValue = newValue + ';secure';
            }
            return newValue;
         }

         if (Array.isArray(res.headers['set-cookie'])) {
            res.headers['set-cookie'] = res.headers['set-cookie'].map(disableSameSite);
         } else {
            res.headers['set-cookie'] = disableSameSite(res.headers['set-cookie']);
         }
      })
   });
});
```

So the new `set-header` become : 
```
Set-Cookie:
TS0149b4e3=XXXXUUIDXXXX; Path=/; Domain=.api.sandbox.mangopay.com; samesite=none; secure
Set-Cookie:
my_ps=YYYYHASHYYYY; expires=Tue, 24-Oct-2023 08:13:05 GMT; path=/; Httponly; Secure; samesite=none
```

And then you call `disableSameSiteCookieRestrictions` before opening the new window.

Yours faithfully,
LCDP
