### ISSUE TITLE
cy.request is not able to handle response with large size

### ISSUE THREAD

**Issue by ibrahimsTailorMed** [cypress-io/cypress#24581]
### Current behavior

I'm working on backend code coverage, the node module @cypress/code-coverage sends a cy.request to the coverage API in order to get the JSON object that represents the code coverage.
The file size is 16 MB, I tried manually with POSTMAN and I was able to retrieve the file. Also I tried using CURL in the terminal and dump the output to a file and it works. 
I saw other people having the same issue like this one here: 
https://github.com/cypress-io/code-coverage/issues/129 

### Desired behavior

The response should be handled despite its size

### Test code to reproduce

node_modules/@cypress/code-coverage/support.js Line 181

### Cypress Version

9.6.0

### Node version

14

### Operating System

12.6

**Comment by rockindahizzy** [comment]
Hey @ibrahimsTailorMed thanks for reporting this issue! Could you provide the error logs you are seeing when this happens?

**Comment by rockindahizzy** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
