### ISSUE TITLE
Videos not viewable on Cypress Dashboard when videoCompression is set to 0

### ISSUE THREAD

**Issue by liambutler** [cypress-io/cypress#24595]
### Current behavior

I imagine that this is related to [this issue](https://github.com/cypress-io/cypress/issues/5191)

I've been trying to debug video frame skip issues when running Cypress via GitHub Actions ([issue here](https://github.com/cypress-io/cypress/issues/20468)). One thing that was suggested to me was to set the `videoCompression` to `0` in `cypress.config.ts`.

According to the GitHub Action's execution log, the upload was successful:

<img width="804" alt="Screenshot 2022-11-08 at 16 49 20" src="https://user-images.githubusercontent.com/24389501/200611738-c5b940f8-654d-4ab4-aa38-6162e0b0061c.png">

However, when looking at [this run](ttps://dashboard.cypress.io/projects/iyj7ts/runs/75/) on the dashboard, the video is not watchable: 

<img width="1104" alt="Screenshot 2022-11-08 at 16 51 31" src="https://user-images.githubusercontent.com/24389501/200612128-b7849e12-d7b1-4bda-ad09-5b2297bfcebe.png">

And there is this error in the console:
<img width="1162" alt="Screenshot 2022-11-08 at 16 51 12" src="https://user-images.githubusercontent.com/24389501/200612188-5b396900-e621-49ee-b286-bbe1fde30818.png">

### Test code to reproduce

Relevant config items:

```js
{
  videoCompression: 0,
  viewportHeight: 800,
  viewportWidth: 1250,
}
```

### Cypress Version

10.11.0

### Node version

v16.18.0

### Operating System

ubuntu-20.04

### Debug Logs

```shell
I can email the run log if required, but would rather not share on here
```

**Comment by liambutler** [comment]
Same issue when `videoCompression` is set to `false`:

![Screenshot 2022-11-09 at 15 16 20](https://user-images.githubusercontent.com/24389501/200853772-7a7a8883-1914-4ac3-a4ed-cd807b86aa93.png)

**Comment by ryanthemanuel** [comment]
Hi @liambutler. Thank you for logging this. I am unable to recreate it with my own test projects. When you see the issue is the video corrupt locally? Or just on the dashboard?

**Comment by liambutler** [comment]
Hi @ryanthemanuel, thanks for getting back to me

> When you see the issue is the video corrupt locally? Or just on the dashboard?

Both, unfortunately! You can see other folks encountering the problem in [this issue](https://github.com/cypress-io/cypress/issues/5191)

Some more info about my setup:

Local machine:
M1 MacBook Pro
Quicktime as default video player (this is important as the uncompressed videos are playable when using VLC)

CI:
GitHub Actions default runner

[Here's a run where you can see that the dashboard is unable to play the uncompressed recordings](https://dashboard.cypress.io/projects/iyj7ts/runs/85/)

Hope that helps. Let me know if you need any more info

**Comment by ryanthemanuel** [comment]
Aha. Thanks for the additional information @liambutler. I was able to reproduce this. Key differences from when I tried before:

* videoCompression = 0 in the config
* Using quicktime to try and open the file locally
* Using safari to try and load the file in the dashboard (it seems to work in chrome but not safari).

I will go ahead and route this to the e2e team.
