### ISSUE TITLE
[sessions] cy.session validate() TypeScript Types not consistent with documentation

### ISSUE THREAD

**Issue by alvaromartmart** [cypress-io/cypress#24593]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The `cy.session` documentation says:
> If the validate function return false, throws an exception, **returns a Promise that resolves to false or rejects**, or contains any failing Cypress command, the session will be considered invalid, and setup will be re-run.

However, the return type of the validate function is actually `false | void`, so it is not possible to *return a Promise that resolves to false or rejects*
```ts
cy.session( [user, pwd] => {
    /**/
}, {
    /* Typescript complains about this as the return type of validate is `false | void` */
    validate: () => Promise.reject('Invalid session)
}
```

I've assumed this is a documentation issue, but I might be wrong. I'd be up to submitting a PR if needed.

**Comment by emilyrohrbough** [comment]
Looks like there are incorrect Types for validate
