### ISSUE TITLE
Automatic ES6 support with babel

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#246]
Cypress should support ES6.

**Comment by brian-mann** [comment]
This has basically been thought out and is ready for implementation in the next couple versions.

**Comment by chrisbreiding** [comment]
* Add ES6 support through babel with default 
* Add JS modules/CommonJS support with browserify
* Use watchify for watching scripts
* Handle compile errors gracefully and show in UI
* Add options for changing babel presets, plugins
* Write docs explaining how it all works and default configuration for babel, cjsx

Add caching in future:
* On boot, pre-emptively browserify everything
* If spec option is passed, only browserify the spec passed
* The spec controller streams from the files on disk, waits if browserify is still working

**Comment by brian-mann** [comment]
Fixed in [`0.18.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0180-11272016).
