### ISSUE TITLE
Request to wrong URL

### ISSUE THREAD

**Issue by onur9779** [cypress-io/cypress#24612]
### Current behavior

I am now writing e2e test for a login page. I basically used get.type and get.click but when cypress clicks the submit button it sends the request to wrong URL. URL path is being changed. It is normally .../Gateway/api/Authentication/Login but it changes "Gateaway" with "Null". Like I said I don't send request by using .request(), I just use .click() and watch it by devtools. I don't get this error when I login with browser. I get the error in cypress.

### Test code to reproduce

describe("Login Tests", function () {
    context("Valid username/password", function () {

        it("Visit site", function () {
            

            cy.visit(site)
            
        })

        it("Type valid username/password", function () {
            cy.get(".v-enter-to > .md-form > .form-control").type("username")
            cy.get('input[type=password]').type("password")
        })

         it("Click submit button", function () {

         cy.get(':nth-child(1) > .btn-block').trigger('mouseover').click({force:true})

         })

          })
    })
})

### Cypress Version

10.11.0

### Node version

v16.18.0

### Operating System

Windows 11

**Comment by stychu** [comment]
I highly recommend going through `best practices` docs https://docs.cypress.io/guides/references/best-practices#Creating-tiny-tests-with-a-single-assertion

Instead of this
```
describe("Login Tests", function () { context("Valid username/password", function () {
     it("Visit site", function () {
         
 
         cy.visit(site)
         
     })
 
 
     it("Type valid username/password", function () {
         cy.get(".v-enter-to  .md-form  .form-control").type("username")
         cy.get('input[type=password]').type("password")
     })
 
 
 
      it("Click submit button", function () {
 
      cy.get(':nth-child(1)  .btn-block').trigger('mouseover').click({force:true})
 
      })
 
       })
 })
 ```
 
 try this
 
 ```js
 describe("Login Tests", function () { context("Valid username/password", function () {
     it("Visit site", function () {
         cy.visit(site)
         cy.get(".v-enter-to  .md-form  .form-control").type("username")
         cy.get('input[type=password]').type("password")
         cy.get(':nth-child(1)  .btn-block').trigger('mouseover').click({force:true})
     })
 })
 ```

or this

 ```js
 describe("Login Tests", function () { context("Valid username/password", function () {
beforeEach(() => {
         cy.visit(site)
  })
     it("Visit site", function () {

         cy.get(".v-enter-to  .md-form  .form-control").type("username")
         cy.get('input[type=password]').type("password")
         cy.get(':nth-child(1)  .btn-block').trigger('mouseover').click({force:true})
     })
 })
 ```

**Comment by onur9779** [comment]
It solved the problem thank you but do you know why this happens?
