### ISSUE TITLE
Cypress can't run tests using big forEach loop, Chrome crashes and other browsers stuck on "tests loading"

### ISSUE THREAD

**Issue by GeorgeXCV** [cypress-io/cypress#24610]
### Current behavior

I have a big JSON file (1000 entries). I have a test within a forEach loop of the JSON file. If I only have a few entries in the JSON file the test runs without issue. But with all the entries the test doesn't even start due to the error: "We detected that the Chromium Renderer process just crashed.".  If I switch to Firefox it doesn't crash but remains stuck on "Tests are loading". Why can't Cypress handle a big forEach loop? 

### Test code to reproduce

JSON file (duplicate the entry lots):
```json
[
 {
   "address": "0x123",
   "nof_sales": 4656,
   "projects_sold": 1044
 },
]
```

Test:
```js
import * as wallets from "../../fixtures/wallets.json"

describe('Wallet - Counterparties', () => {
  before(() => {
    cy.loginAPI(Cypress.env("vipUserEmail"), Cypress.env("vipUserPassword"))
  })

  wallets.forEach(wallet => {
      beforeEach(() => {
        cy.visit(Cypress.env("baseUrl"))
        cy.clickWalletProfiler()        
        cy.enterWalletAddress(wallet.address)
        cy.clickShowWalletData()
      })

      it(`Verify Counterparties - ${wallet.address}`, () => {
        cy.verifyCounterparties()
      })
  })
```

### Cypress Version

10.11.0

### Node version

16.16.0

### Operating System

Ventura 13.0

### Debug Logs

```shell
[4010:0x13000b30000]    36126 ms: Mark-sweep 3945.6 (4089.7) -> 3941.7 (4094.0) MB, 1376.4 / 0.0 ms  (average mu = 0.069, current mu = 0.006) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

[4010:259:1109/103712.149372:ERROR:v8_initializer.cc(731)] V8 javascript OOM (MarkCompactCollector: young object promotion failed). +26s
  cypress:server:socket-base socket-disconnecting transport close +38s
  cypress:server:socket-base socket-disconnect transport close +0ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50060 } +21s
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50057 } +0ms
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.
```

**Comment by jennifer-shehane** [comment]
Which version of Chrome are you using?

**Comment by GeorgeXCV** [comment]
> Which version of Chrome are you using?

Version 107.0.5304.87

**Comment by mjhenkes** [comment]
@GeorgeXCV, could you put together a simplified example repo? The test code you provided seems to rely on your specific project. I'm unclear on how you're loading the json file on your page. Is it as simple as loading the page once or is it related visiting the page for each 'wallet' and loading the page? How many times is the test able to be run?

This may be related to #23391

**Comment by GeorgeXCV** [comment]
> @GeorgeXCV, could you put together a simplified example repo? The test code you provided seems to rely on your specific project. I'm unclear on how you're loading the json file on your page. Is it as simple as loading the page once or is it related visiting the page for each 'wallet' and loading the page? How many times is the test able to be run?
> 
> This may be related to #23391

The JSON is loaded by just importing the file and using `forEach`, updated code with the import statement. The browser crash happens before a single test starts so the contents shouldn't matter when trying to reproduce.

**Comment by BlueWinds** [comment]
You are running out of memory and Chrome is crashing - 1000 entries is simply too many tests for one spec file. While we're working on improving it, the command log (and cypress in general) are very memory hungry, and the larger a file grows, the more likely you'll run into issues.

My suggestions, in order, would be:
1. Do you really need 1000 tests? This suggests that you might be able to test 'at the seams' better in some other way. How many of these 1k cases are actually *unique*, in need of being tested separately? Perhaps you can test your UI in 5 different ways, then test your API in 5 different ways, and that's enough.
2. Break up your tests across multiple spec files. `000-099.cy.js`, `100-199.cy.js`, etc. Load your entries in batches, one set per file, and run them sequentially.
3. Try reducing the number of command log entries per test. Use `{log: false}` on a bunch of your commands inside Cypress commands to stop them showing up. Command log entries, and especially the snapshots they generate and maintain, are memory-intensive. Cut down a bit, and you'll be able to run more tests / commands per spec file.

We're looking at improving performance and reducing memory usage, but not really a single big bug we can directly address here.
