### ISSUE TITLE
Module Api - Missing title of suite / describe hook

### ISSUE THREAD

**Issue by Konstruktour** [cypress-io/cypress#2462]
### Current behavior:
Using the module api command `cypress.run({...})` returns a promise containing the test results (#2141). This object contains information about the all tests, - title of the tests (description of `it` hook) but it does not contain the title of the whole suite (description of the `describe` hook).

### Desired behavior:
The object in the result promise of  `cypress.run({...})` should also contain the title of the suite (`describe` hook).

### Versions
Cypress 3.1.0
Windows 10
Electron

**Comment by jennifer-shehane** [comment]
Could you provide an example of the test title returned? I am familiar in our backend API that the test title is returned as an array (which is all hooks + the `it` description) like so:

```json
"title": [
    "Projects",
    "lists projects",
    "displays all"
]
```

@gleb does it not return this for cypress.run as well?

**Comment by bahmutov** [comment]
It should. Please provide code example and output and expected output

**Comment by Konstruktour** [comment]
Thx for clearifying. You are right. I had an issue in a (json) reporter which overwrote/removed somehow the title of the suite... 
You can either close this issue or consider it as a bug that a reporter can have an influence on the result of the cypress.run promise.
