### ISSUE TITLE
When running a cypress test,  I only see the running browser, not the details in the left

### ISSUE THREAD

**Issue by zaalgol** [cypress-io/cypress#24624]
### Current behavior

after normal working with cypress for a few days, suddenly when running a test, it runs, but only shows the visualized browsing part, not the left side of the textual description (VISIT, GET, FIND, failures of asserts, etc), so I can't see the steps, and not if a test failed.

I added a screenshot of the expected view, as I only have the left side of it.

### Desired behavior

When running the test, show the textual details on the left, and the browsing simulation in the right.  on

### Test code to reproduce

regular running cypress with npm in a react project, and choosing to run - one or all tests in the cypress GUI screen.

### Cypress Version

6.14.9

### Node version

v15.3.0

### Operating System

macOS 12.6

### Other

example of a correct cypress screen. In my running cypress, there is only the right side.
![Screen Shot 2022-11-09 at 20 57 13](https://user-images.githubusercontent.com/21083266/200921930-c734a8f2-7ac0-497c-b8c3-37a383bc03e3.png)

I restart my computer, deleted the project and cloned it again from the repo, uninstall and install the cypress, and cleared the cypress cache, but the bug remains.

**Comment by nagash77** [comment]
Hi @zaalgol , I am sorry to hear you are having issues.  I see you are using a very old version of Cypress.  Can you try upgrading to the latest and see if the issue persists?

**Comment by zaalgol** [comment]
Hi @nagash77,

I upgraded the version, and the bug was fixed.

Thanks!
