### ISSUE TITLE
The Cypress Dashboard scrolls out of view when tests startup

### ISSUE THREAD

**Issue by kodriscollics** [cypress-io/cypress#24620]
### Current behavior

After I bring up the Cypress dashboard and click on one of the file specs to run, the test launches just fine, as shown in this first picture (CypressDashboardIssue-0.PNG):

![CypressDashboardIssue-0](https://user-images.githubusercontent.com/75755773/200893697-e2af6845-0187-49f7-8719-7345d14b610b.PNG)

However, shortly into the test (it appears at the first "get" statement) the entire dashboard view scrolls upward--the browser, the history, the Cypress command buttons, everything, as you can see in this picture (CypressDashboardIssue-1.PNG):

![CypressDashboardIssue-1](https://user-images.githubusercontent.com/75755773/200894660-af4b7e54-b7d0-4e8f-8023-dddd29a27d55.PNG)

The final state after a test runs is shown in this next pic  (CypressDashboardIssue-2.PNG). Again, the view and access to the full browser, the Cypress history, the Cypress commands, etc are all gone:

![CypressDashboardIssue-2](https://user-images.githubusercontent.com/75755773/200936473-979facb3-7272-4a63-acbc-0f638c68ef39.PNG)

I noticed this happening with version 10.11.0. I upgraded to version 11.0.0 but the problem persists.
I have tried using Firefox and Edge in addition to Chrome. The browser made no difference.
I have tried resizing the browser window in the cypress.config.ts file, which made no difference.
I have tried resizing the Cypress dashboard window itself, which made no difference.
I have tried multiple monitor, but to no avail.

### Desired behavior

Give me access to the full browser, Cypress history and Cypress control buttons. As it is, I can not debug any new tests I'm creating nor any existing tests that fail for whatever reason.

### Test code to reproduce

I have dozens of tests and the problem happens no matter which test I run. Also, the tests themselves all finish just fine. So, the problem I have is not the result of any specific test.

### Cypress Version

11.0.0

### Node version

node --version yields v16.6.1

### Operating System

Windows 10 enterprise, version 21H2, OS build 19044.2006

**Comment by ryanthemanuel** [comment]
Hi @kodriscollics. You mentioned this was happening on 10.11 and up. Does that mean that it is not happening on version 10.10? Or has that been tried? It would be helpful to know when this was potentially introduced.

**Comment by kodriscollics** [comment]
@ryanthemanuel I have not tried with other versions before 10.11. When I noticed it happening, I was on version 10.11. When I have some spare time, I'll try back rev'ing.

**Comment by mjhenkes** [comment]
@kodriscollics, is the issue specific to your website or can you recreate it elsewhere? Is the website that causes this problem public?

**Comment by kodriscollics** [comment]
@ryanthemanuel I have discovered the cause. I had installed:

npm install --save-dev `@alexmagnus/cypress-full-dark-mode

which added the entry:

require('@alexmagnus/cypress-full-dark-mode')

to the e2e.ts file. After commenting this out, the dashboard behaves as it should.

**Comment by mjhenkes** [comment]
@kodriscollics, I'm glad you found the issue. Maybe some day we'll get our own dark theme 😅

**Comment by kodriscollics** [comment]
I have opened the following issue on the cypress-full-dark-mode github site:

https://github.com/AlexTheMagnus/cypress-full-dark-mode/issues/8
