### ISSUE TITLE
Cypress 11 fails on alias imports (shorthand imports)

### ISSUE THREAD

**Issue by cope** [cypress-io/cypress#24638]
### Current behavior

Cypress 10.11.0 worked just fine, when I upgrade to Cypress 11.0.1 it no longer understands alias import (shorthand imports).

When I revert back to Cypress 10.11.0 everything works again.

### Desired behavior

Cypress 11.0.1 should understand alias import (shorthand imports) just like Cypress 10.11.0 does.

### Test code to reproduce

It's a simple enough explanation. Cypress 10.11.0 worked just fine, when I upgrade to Cypress 11.0.1 it no longer understands alias import (shorthand imports).

### Cypress Version

11.0.1

### Node version

v18.9.0

**Comment by ryanthemanuel** [comment]
Thank you for logging this issue @cope. What error are you seeing when you try to use alias imports?

**Comment by cope** [comment]
@ryanthemanuel this is weird because I was 200% sure that I copied the log output :(

I will grab it again, but have to reupgrade to 11 to get it...

**Comment by cope** [comment]
Upgrading to Cypress 11.0.1:
```
14:10:05 [vite] Internal server error: Failed to resolve import "@/stores" from "cypress\support\component.js". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/git/systools/systools-client/cypress/support/component.js:19:28
  17 |  import './commands';
  18 |
  19 |  import {createPinia} from '@/stores';
     |                             ^

```
and
```
    ×  4 of 4 failed (100%)
```

and by simply reverting back to Cypress 10.11.0:
```
    √  All specs passed!
```

**Comment by cope** [comment]
My cypress.config.js:
```
const {defineConfig} = require('cypress');

module.exports = defineConfig({
	watchForFileChanges: false,
	component: {
		video: false,
		devServer: {
			framework: 'vue',
			bundler: 'vite',
			viteConfig: {
				server: {
					host: '127.0.0.1'
				}
			}
		}
	}
});

```

**Comment by cope** [comment]
Just to be clear, if I change `import from '@/stores'` to `import from '../../src/stores'` then it simply breaks on the next `import from '@...`.

And if I change all those inside the cypress folder, it breaks on the first one in the test/ folder - which means I simply cannot use @ in ALL my tests - which is not really acceptable...

**Comment by ryanthemanuel** [comment]
I see what's going on now. Thanks for the additional info. It looks like you're running into one of the breaking changes in [11.0.0](https://docs.cypress.io/guides/references/changelog#11-0-0). Specifically, when providing an inline viteConfig inside of cypress.config, any vite.config.js file is not automatically merged. Can you try following these steps and see if it fixes your issue? https://docs.cypress.io/guides/references/migration-guide#Vite-Dev-Server-cypress-vite-dev-server

**Comment by cope** [comment]
That's not a nice breaking change 😢.

I tried it but it now has a problem with import vs require 😢.

If I use `import viteConfig from './vite.config';` I get this error:
```
C:\git\systools\systools-client\cypress.config.js:2                     
import viteConfig from './vite.config';                                 
^^^^^^                                                                  
                                                                        
SyntaxError: Cannot use import statement outside a module  
```

And if I change that to `const viteConfig = require("./vite.config");` then the same error just moves to vite.config:
```
C:\git\systools\systools-client\vite.config.js:1                        
import dns from 'dns';                                                  
^^^^^^                                                                  
                                                                        
SyntaxError: Cannot use import statement outside a module
```

So, vite is able to `import`, but cypress is not... 😢

**Comment by marktnoonan** [comment]
@cope I'm checking on workarounds and one may to be to use a dynamic import, viteConfig can be an async function. I haven't tested, but something like this?

```js
viteConfig: async () => {
  const { default: viteConfig } = await import('./vite.config')

  viteConfig.server.host = '127.0.0.1'

  return viteConfig
}
```

Also, we override `server.host` to be `127.0.0.1` so you could you try removing the inline `viteConfig` option entirely? Without one specified, it will source the config located at your project-root.

**Comment by cope** [comment]
Ah! YES!

I gotta say, I was confused to see a breaking change that would make things worse 😃 

So, I actually needed to remove viteConfig completely, cool.

This works like a charm:
```
const { defineConfig } = require("cypress");
module.exports = defineConfig({
	watchForFileChanges: false,
	component: {
		video: false,
		devServer: {
			framework: "vue",
			bundler: "vite"
		}
	}
});
```
And I reverted vite.config back to use imports as before.

All is good.

Thank you!
