### ISSUE TITLE
Add native mobile device browser support

### ISSUE THREAD

**Issue by tracyzhang-stn** [cypress-io/cypress#24634]
### What would you like?

I would like Cypress to add native mobile device browser support.

Thanks!

Tracy Zhang from STN Video

### Why is this needed?

Nowadays, more and more people are using mobile web browser to watch video , search content and read news, even shopping. And running testing and automation on native mobile device browser is becoming more and more important now. 

Currently Cypress only provides mobile user-agent or viewport feature to simulate mobile device browser. However, in some case in our project (e.g test network calls for video playing with Ads), these simulators are not exact same as using native mobile device browser.

Thanks!

**Comment by emilyrohrbough** [comment]
@tracyzhang-stn Thank you for taking the time to open a feature request. The details you provided helped us understand the ask.

At this time, Cypress is not interested in supporting native mobile testing. The way Cypress is built, a completely different set of APIs would be needed to support native testing and how Cypress runs and displays test results would not work in mobile given the small screen space.

At this time we are focused on improving the web testing experience.
