### ISSUE TITLE
Search textfield does not clear after restart

### ISSUE THREAD

**Issue by Zuks86** [cypress-io/cypress#24637]
### Current behavior

When you have searched/filtered the tests on cypress and then you restart the search textfield persists the last search field.

This can result in a person mistakenly thinking only few tests are showing.
<img width="407" alt="Screenshot 2022-11-09 at 16 25 06" src="https://user-images.githubusercontent.com/5233337/201044461-614fd5b5-03b0-443f-b6c9-a20fd2b15b97.png">

### Desired behavior

When you restart cypress this search text field should be cleared

### Test code to reproduce

No tests

### Cypress Version

8.1.0

### Node version

16.4.1

### Operating System

macOs Big Sur

**Comment by emilyrohrbough** [comment]
@Zuks86 Thank you for opening an issue! This is a design decision we purposely made in the App to allow users to pick-up where they left off when testing in open mode.
