### ISSUE TITLE
afterEach function is not executed if one of the tests are failed

### ISSUE THREAD

**Issue by romankhomitskyi** [cypress-io/cypress#24640]
### Current behavior

My afterEach function should logout after each test no matter if its failed or not. But when test failed - I am getting `CypressError: cy.click() failed because it requires a DOM element.`
```
The subject received was:

  > `undefined`

The previous command that ran was:

  > `cy.get()`
```
 cause it cant find an element although the element is presented on the screen.

![image](https://user-images.githubusercontent.com/57874507/201062247-a03365f9-3247-46e0-a695-d1df4d2903a1.png)

### Test code to reproduce

```
before(() => {
   login()

})

afterEach(() => {
  cy.get('[id="settings-main"]').should('be.visible').click();
  cy.get('[data-test="Log out"]').click();
	});
	
it(Test 1)
it(Test 2)
it(Test 3)
```

### Cypress Version

10.11.0

### Node version

node16.18.0

### Operating System

cypress/browsers:node16.18.0-chrome107-ff106-edge

**Comment by nagash77** [comment]
Hi @romankhomitskyi we consider using afterEach to clean up state an anti-pattern that should be avoided.  Check out our documentation around [afterEach()](https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks).
