### ISSUE TITLE
Component Test fails due to Cannot use 'in' operator to search error

### ISSUE THREAD

**Issue by onthespotqa** [cypress-io/cypress#24648]
### Current behavior

So this only happened when running in circleci using the cypress/base:16.13.0 image.

There seems to be a pre-processor error with one of our component test files. 

`
TypeError: The following error originated from your test code, not from Cypress.

  > Cannot use 'in' operator to search for '()=>{u(),cy.contains("Linking in Progress")}' in shows text

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at it (http://localhost:33693/__cypress/src/vendors~spec-3.js:1:231)
    at Suite.<anonymous> (webpack:///./src/components/Settings/Profile/BankAccountsBlock/__component_tests__/ActionButton.spec.tsx:29:4)
    at Object.create (http://localhost:33693/__cypress/runner/cypress_runner.js:103460:19)
    at context.describe.context.context (http://localhost:33693/__cypress/runner/cypress_runner.js:103236:27)
    at createRunnable (http://localhost:33693/__cypress/runner/cypress_runner.js:162465:31)
    at <unknown> (http://localhost:33693/__cypress/runner/cypress_runner.js:162533:14)
    at Suite.<anonymous> (webpack:///./src/components/Settings/Profile/BankAccountsBlock/__component_tests__/ActionButton.spec.tsx:27:2)
    at Object.create (http://localhost:33693/__cypress/runner/cypress_runner.js:103460:19)
    at context.describe.context.context (http://localhost:33693/__cypress/runner/cypress_runner.js:103236:27)
    at createRunnable (http://localhost:33693/__cypress/runner/cypress_runner.js:162465:31)
`

I think it's a preprocessor issue as even skipping the describe block still causes the error.

### Desired behavior

There should be no error.

### Test code to reproduce
```
import { Button } from '@appfolio-im/react-gears-cypress';
import { mount } from 'cypress/react';
import getGiven from 'givens';
import React from 'react';
import ActionButton from '../ActionButton';
import { BankAccountStatus } from '../index';

const given = getGiven<{
  status: BankAccountStatus;
}>();

describe('Action Button', () => {
  given('status', () => 'status_1');
  function render() {
    return mount(
      <ActionButton
        editBankAccount={() => {}}
        reload={() => Promise.resolve()}
        bankAccountId={5}
        status={given.status}
        isTest
      />
    );
  }
  describe('linking in progress', () => {
    given('status', () => 'status_2');
    it('shows text', () => {
      render();
      cy.contains('Linking in Progress');
    });
  });
});
```

### Cypress Version

10.11

### Node version

16.13.0

### Operating System

Debian 10.9

### Other

It might be something with our webpack setup. we have a similar component that we're testing in another app that runs just fine.

However i don't even know where to begin starting to look into the issue, since it does not reproduce when i run on my mac.

**Comment by marktnoonan** [comment]
Thanks for reporting this @onthespotqa. You've given us a good deal of information. It will be difficult to address it, and *know* we've fixed it, without a full repro but let's see. If it's possible to grab the problematic component and reproduce this using https://github.com/cypress-io/cypress-test-tiny that would give us something to go on.

A couple of questions:

- What version of node are you running locally on your mac, where this doesn't happen?
- Would you mind trying the latest version of Cypress (11.0.1 or later)? There are several changes in 11 that make it worth at least validating there before going too much further.

Thanks!

**Comment by marktnoonan** [comment]
Since there has been a week without a response, I'll close this issue to help keep our backlog under control. If you do have more information to share, you can comment below and we can re-open this issue.

**Comment by onthespotqa** [comment]
@marktnoonan sorry i'll try to reproduce. I missed the first comment. But i'm not sure how i'm supposed to reproduce a component test problem using a repo that's setup for e2e tests.

we are using node 16.14.2.

using cypress 11 if happens when run in ci but not locally. my team will try to see if we can get you more info.

**Comment by marktnoonan** [comment]
@onthespotqa you would need to add your framework and the related code then set up component testing, it's just a starting point that's easy to copy & pull down, then modify and push back up.

Definitely interested in fixing this if we can figure out how to reproduce, I'll wait for an update before re-opening but I'll keep myself assigned.
