### ISSUE TITLE
Remove hooks: afterEach(), beforeEach() from test failure report in Analytics

### ISSUE THREAD

**Issue by MKR-3M** [cypress-io/cypress#24641]
### What would you like?

Hooks are included in the failed test results, the number of failures is overstated because of afterEach() (and another) hooks.
I'd like to remove the afterEach() entries from the test report results and not show them in the results.

Current behavior:

![image](https://user-images.githubusercontent.com/102219083/201095680-75a55f11-dbd7-40a2-b43d-8087162f1c52.png)
![image](https://user-images.githubusercontent.com/102219083/201095594-f647e3cd-2c9b-4685-bdd0-a3e1614f03ec.png)

### Why is this needed?

I would like the number of failed tests to reflect the actual number of tests, without the hooks.

### Other

I moved the afterEach() hooks from each tests to the cypress support file, but the display of the failure tests is the same - it displays test failure and, in addition, afterEach() failure.

**Comment by emilyrohrbough** [comment]
@MKR-3M Can you share where you are seeing these results? Is this output from a mocha reporter?

**Comment by marktnoonan** [comment]
Just a note that this is not behavior of Cypress itself. It looks like you are using some kind of custom reporter, maybe that is being fed JSON stats or something else. You can try to use the [Cypress module API](https://docs.cypress.io/guides/guides/module-api) (see the [Result section](https://docs.cypress.io/guides/guides/module-api#Results)) or the [After Run API](https://docs.cypress.io/api/plugins/after-run-api) as the source of data for the report with the modified test titles.

Closing this for now as it is not a request for a feature of Cypress as such, has more to do with mocha reports.
