### ISSUE TITLE
Click does not work on old jquery pages?

### ISSUE THREAD

**Issue by elranu** [cypress-io/cypress#2464]
### Current behavior:
I cannot make work a simple click on an anchor. The following script is a test on an audio player. I have tried many ways to do click, as it can bee seen on the following example.
cypress.json:
```json
{
    "baseUrl": "http://blogtalkradio.com",
    "chromeWebSecurity": false,
    "blacklistHosts": ["https://sync.search.spotxchange.com"]
}
```
test:
```js
describe('Should play the episode', function () {
  it('play episode',
    function () {
      cy.visit('http://www.blogtalkradio.com/dan-zupansky1/2018/09/06/the-alaska-mail-bomb-conspiracy-burl-barer');

      cy.contains('audio');
      cy.wait(5000);

      cy.get('audio#player-audiotag').then(($audioElem) => {
        expect($audioElem[0].duration).to.be.gt(0);
      });

      cy.get('a.player-play').click({ force: true });
      cy.get('a.player-play').dblclick();
      cy.get('a.player-play').invoke('click');
      cy.get('#play-call-to-action').trigger('mouseover').click();
      cy.wait(100);
      cy.get('audio#player-audiotag').then(($audioElem) => {
        var $player = Cypress.$('#play-call-to-action');
        Cypress.cy.wrap($player).click();
        $audioElem[0].play();
        expect($audioElem[0].paused).to.be.eq(false);
      });
    });
});
```

### Desired behavior:

The click should work as you can do it on the web browser.

### Steps to reproduce:

Just execute the test

### Versions

Beta Version 3.1.0 - Windows

**Comment by jennifer-shehane** [comment]
It's quite likely this is related to the `<audio>` element and not jQuery itself. I remember @Bkucera looked into playing audio in Cypress some time ago. https://github.com/cypress-io/cypress/issues/1750#issuecomment-390751415

**Comment by elranu** [comment]
Thanks. But it seems that not. If I do the click with the console (dev tools), it works.

**Comment by elranu** [comment]
hello. Nobody can help me ? :( If you just run the code you see the error

**Comment by Bkucera** [comment]
> I cannot make work a simple click on an anchor. 
@elranu are you sure the click is not happening? It would be great if you could tell us the exact behavior that Cypress isn't doing what you expect.

**Comment by elranu** [comment]
@Bkucera unfortunately I'm sure the click is not happening. In the browser it marks the button but is not being click. Also for that button jquery is unbinding and the binding again the event. Can that be the problem?
Also if you execute the script you will be able to reproduce the error.

**Comment by jennifer-shehane** [comment]
Closing this issue as resolved. Please reopen with a reproducible example if you are still encountering.
