### ISSUE TITLE
A callback was provided to intercept the upstream response, but a network error occurred while making the request

### ISSUE THREAD

**Issue by HeshamMoneer** [cypress-io/cypress#24654]
### Current behavior

I am using a method to log network failures that occur while the tests are running. I basically intercept every failing request and its response and log it in some array as follows:

```javascript
cy.intercept('*', (request) => {
    request.continue(response => {
      if(response.statusMessage !== "OK") {
        networkFails.push({request, response})
      }
    })
  })
```
The tests run perfectly when I comment out this logging section. However, when I leave it as a part of the tests, I often get this error message 
![image](https://user-images.githubusercontent.com/83174696/201313228-ed8db6e7-9036-42bf-b318-262edf081893.png)

### Desired behavior

I should not get this error, and be able to log network failures for further investigation, and the tests should continue normally if they encounter any network failure.

### Test code to reproduce

```javascript
cy.intercept('*', (request) => {
    request.continue(response => {
      if(response.statusMessage !== "OK") {
        networkFails.push({request, response})
      }
    })
  })
```

### Cypress Version

10.7.0

### Node version

12.22.9

### Operating System

Ubuntu 22.04.1 LTS

**Comment by ryanthemanuel** [comment]
Hi @HeshamMoneer. Thank you for logging this issue. When you use `continue` there's an implicit assumption that a response will be received which doesn't happen on timeouts and socket hang ups. Instead of `continue`, can you try using the `response` event or the `after:response`? See [this](https://docs.cypress.io/api/commands/intercept#Request-events) for more information.

Out of curiosity, what is your use case for gathering all of these failures?

**Comment by HeshamMoneer** [comment]
@ryanthemanuel Thank you for your answer. I will check the link that you provided now. I am logging all these network failures for further investigation because in our system a lot of API calls fail indicating that there should be a problem, but the UI does not show that any problem actually happened.

**Comment by tobiasgrossmann** [comment]
What is the default behavior?  I run in the same error. Is there any central config parameter to dissable Cypress failing on a network error? As you see, I'm not using "continue". 

**Cypress 12.6** 



` cy.intercept("GET", "**/api/requests/", (req) => {
      req.reply((res) => {
        const body = res.body;
        try {
          if (res.body != "") {
            body.length = 10;
            res.send(body);
          }
        } catch (ex) {
          res.send(body);
        }
      });
    }).as("requests");
`

**Comment by SylvainFI** [comment]
Hi @tobiasgrossmann, did you solve the issue and how?
