### ISSUE TITLE
Cypress v11 `cypress run` crashes when assertion in test fails

### ISSUE THREAD

**Issue by niklasvieth** [cypress-io/cypress#24652]
### Current behavior

If an assertion in a test fails by running `cypress run --browser chrome` the whole process fails instead of showing the result of one failing test in the console as report. 
Fails with following error:
```bash
u(...).generateDiff is not a function
TypeError: u(...).generateDiff is not a function
    at T.getTestcaseData (<embedded>:1144:21700)
    at T.<anonymous> (<embedded>:1144:19702)
    at R.emit (node:events:539:35)
    at S.emit (<embedded>:2755:16640)
    at Object.onMocha (<embedded>:2802:338633)
    at p.<anonymous> (<embedded>:2802:66203)
    at p.emit (node:events:527:28)
    at p.emitUntyped (<embedded>:2527:41392)
    at <embedded>:2527:48899
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### Desired behavior

Show the failing test result in the report table same as in v10.11

### Test code to reproduce

```js
it("Faulty test", () => {
   expect(3).to.equal(4);
}
```

### Cypress Version

11.0.0 or 11.0.1

### Node version

v16.14.2

### Operating System

macOS Ventura 13.0

**Comment by petergaal91** [comment]
Same issue here. And I have a strange message at the start:

`Couldn't determine Mocha version`

**Comment by fabian-froehlich** [comment]
I am experiencing the same issue when running tests in cli. The cypress GUI runner works as before.

```
import {defineConfig} from "cypress"

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:3001"
  },
  reporter: "junit",
  reporterOptions: {
    mochaFile: "cypress/results/junit-report-[hash].xml",
    testCaseSwitchClassnameAndName: true
  },
  video: false,
  viewportHeight: 1080,
  viewportWidth: 1920
})

```

**Comment by handerss-spotfire** [comment]
We experience the same issue, also using "junit" reporter with "mochaFile" option.

**Comment by BoreasMun** [comment]
Same here, "junit" with "mochaFile"

**Comment by mbiggs-gresham** [comment]
Same issue here. It was working fine, and then I modified a test and see the same error every time on just that test file.
