### ISSUE TITLE
Allow configuring `angular.json` from `component` configuration for 

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#24666]
### What would you like?

Related: https://github.com/cypress-io/cypress/discussions/24400

Right now, Cypress Component Testing assumes Angular projects place their `angular.json` at the root of the project. This might not be the case, for example if you are using Nx to manage your Angular project. They recommend putting Cypress tests in a separate directory, which I learned here: https://nx.dev/angular-tutorial

### Why is this needed?

This might be required for Nx to integrate with Cypress in a first class fashion, like they do with E2E.

### Other

- GH Discussion: struggling to configure CT with Nx: https://github.com/cypress-io/cypress/discussions/24400
- Issue in Nx about Cypress CT: https://github.com/nrwl/nx/issues/13148

I got it working with my own `angular.json`, but we should really grab the one that is likely buried in the `node_modules/@nx/angular-preset` (or whatever directory).

I did get it working eventually: https://github.com/lmiller1990/angular-nx-cypress but I had to create a new `angular.json` and mess around a lot, not the first class DX Nx or Cypress wants to offer.

**Comment by jordanpowell88** [comment]
We currently have the options API to allow users to configure without an `angular.json` https://docs.cypress.io/guides/component-testing/angular/overview#Options-API

**Comment by lmiller1990** [comment]
That seems fine - I think we can close this as  unnecessary.
