### ISSUE TITLE
 cy.writeFile should resolve to null

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#2466]
Currently, `cy.writeFile` return [the contents written to the file](https://docs.cypress.io/api/commands/writefile.html#Yields_), which is not the same behavior as fs. In the case of appends, it yields only what was appended and not the entire file. 

It should return null, to align with libraries with similar functionality.

**Comment by chrisbreiding** [comment]
The code for this is complete but has not yet been released. It will be released in [4.0](https://github.com/cypress-io/cypress/pull/2880).
