### ISSUE TITLE
Cypress open browser doesnt show any data

### ISSUE THREAD

**Issue by erakki27** [cypress-io/cypress#24673]
### Current behavior

When i open cypress using npx cypress open and configure End to End testing the browser which is launched with localhost dont show any data but in documentation i see spec, setting should load, what could be the reason as i followed all the setup steps

This is what i see when browser launch:-

![image](https://user-images.githubusercontent.com/118168131/201677848-e604bda0-2341-43d1-83c1-2c297c06cd86.png)

but doc says this:-

![image](https://user-images.githubusercontent.com/118168131/201677953-bb3dbb3c-75eb-49b5-9bf0-522e3fd3555b.png)

### Cypress Version

11.0.1

### Node version

18.12.1

### Package Manager

npm

### Package Manager Version

18.12.1

### Operating system

Windows

### Operating System Version

Windows 10

**Comment by ryanthemanuel** [comment]
Hi @erakki27. Thank you for logging this issue. Do you see any errors in the JavaScript console in the blank browser?

**Comment by erakki27** [comment]
Hi Ryan,

Yes i do see socket failed error in console:-

![image](https://user-images.githubusercontent.com/118168131/201702828-9519d9ea-13cb-43b1-9fff-23a2e9977cd7.png)

**Comment by ryanthemanuel** [comment]
Hi @erakki27, can you expand those errors in the console to see if there is more information? Also, does this happen on previous versions of cypress or only version 11?

**Comment by erakki27** [comment]
Hi @ryanthemanuel , i realize that browser is opening with http:// which is not loading so i changed it to https:// and now its loading fine, now sure why automatically its not taking https://

i just started using cypress so not aware of older version

**Comment by nagash77** [comment]
@erakki27 I'm glad you have figured out the problem.  I am going to close this issue.  If you find yourself having more questions as you start working with Cypress, I would encourage you to check out our [Cypress Discord](https://discord.gg/cypress).  You can often get help much quicker from all the folks who hang out there.
