### ISSUE TITLE
Cypress dashboard filtering by AND for a filter

### ISSUE THREAD

**Issue by rayeedanwar** [cypress-io/cypress#24670]
### What would you like?

We would like to be able to filter better on Cypress Dashboard.

Specifically, to filter by multiple tags together. At the moment, if I select multiple tags, the filter is treated as an `OR`, but I'd like for it to be treated as an `AND`.

### Why is this needed?

We want to see the reliability (hence, analytics) of different runs in different gitlab pipelines (schedule, merge train, non merge train, codebase). We cannot do this well because of the current `OR` filtering mechanism.

### Other

The workaround for this is to concatenate multiple tags, but this leads to unnecessarily long tags which are unwieldy.

**Comment by nagash77** [comment]
Hi @rayeedanwar , can you expand on this a bit more?  where/what are you trying to filter?  are you referring to the Cypress runner or to the Cypress Cloud dashboard?

**Comment by rayeedanwar** [comment]
> 

Cypress Cloud dashboard

We have multiple tags per run, things like: repository name, pipeline job name, pipeline type

The reason we added these tags is to have better stats on which test runs are unreliable. For example, gitlab has a merge train pipeline, in which we would expect test runs to have a pass rate close to 100%. If this is not a reality, we'd like to drill down to the common errors (via analytics), which pipeline jobs are the cause of this

**Comment by nagash77** [comment]
@rayeedanwar I have passed this along to our cloud product manager.  They are tracking this in our internal product management tool.

**Comment by rayeedanwar** [comment]
Thanks @nagash77 - what's a good way of keeping tabs on this? I'm aware of the [public roadmap](https://github.com/orgs/cypress-io/projects/13/views/1), but I imagine this won't be there

**Comment by danjohansenconsulting** [comment]
Cypress has just released a new capability to choose "Any" or "All" when filtering by Tags in Cloud. This enhancement is now available on both project analytics and the Latest Runs.

@rayeedanwar Thank you for the feedback!
