### ISSUE TITLE
Cypress Studio - ability to create tests after the first one without visiting new URL prompt

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#24691]
### What would you like?

In Cypress Studio currently (I'm on Cypress 11.0.1), every new test (after the 1st one) requires the user to input a URL to visit a new page. The way I'm currently using Cypress is visiting the page in the first spec of the describe/context and in the other specs I actually make the tests without visiting again. Is it possible to make a config option to change this behavior of Cypress Studio?

![image](https://user-images.githubusercontent.com/5721147/201957444-03b7109c-4456-45ad-a2b9-985b3280b5a1.png)

**Comment by nagash77** [comment]
We consider this approach to be an. anti-pattern.  Each test should be able to run independently and reliably produce the same state and result regardless of the order of tests being executed.  As such we most likely will not add this feature unless there is substantial community feedback around wanting to support this anti-pattern.
