### ISSUE TITLE
Login failed due to HTTP mixed content. Blocked by Cypress but not by neither Chrome nor Electron

### ISSUE THREAD

**Issue by IagoParisDev** [cypress-io/cypress#24690]
### Current behavior

Cypress blocks my login test prompting:
![image](https://user-images.githubusercontent.com/109851533/201950896-22aff17e-b32f-4f01-b4a3-85c9d4a428e7.png)

### Desired behavior

Login should proceed without said error, as it does in Chrome outside of Cypress, these are the requests made (selected is the first one over HTTP, which Chrome does not block):
![image](https://user-images.githubusercontent.com/109851533/201951395-0b54aacd-fc8e-4292-ba6d-b01c6b133dbc.png)

Then you should be greeted by this page:
![image](https://user-images.githubusercontent.com/109851533/201951938-e0f0d480-9e1e-43d7-84f6-d4cc52708c80.png)

### Test code to reproduce

```
describe('Workshop', () => {
    it('simpleLogin', () => {
        cy.visit('https://www.test.profe.com/entrar')
    
        var mail = "iago.paris+cypress@profe.com"
        var password = "cypress"
        var isparent = true
  
        cy.get('input#email.form-control')
          .type(`${mail}`)
          .should('have.value', `${mail}`)
    
        cy.get('input#password.form-control')
          .type(`${password}`)
          .should('have.value', `${password}`)
    
        if (isparent) {
          cy.wait(4000)
          cy.get('button#login-submit')
            .click()
          cy.get('li[data-test-id="parent-multilogin-box"]').click()
        } else {
          cy.wait(4000)   
          cy.get('button#login-submit')
            .click()
        }            
        cy.get('#sidebar-container').should('exist')
    })
})
```

### Cypress Version

10.7.0

### Node version

16.16.0

### Operating System

Windows 10.0.19044

**Comment by nagash77** [comment]
Hi @IagoParisDev , because you are starting with a visit to https, any visit to something other than https is considered cross-origin.  Please check out [cy.origin](https://docs.cypress.io/api/commands/origin) as an experimental feature which should address this specific scenario.  If you need further support in using cy.origin please check out our [Cypress Discord](https://discord.gg/cypress).
