### ISSUE TITLE
@cypress/grep readme references previous cypress-grep package

### ISSUE THREAD

**Issue by BenShelton** [cypress-io/cypress#24696]
### Subject

readme

### Description

The documentation at https://github.com/cypress-io/cypress/tree/develop/npm/grep has mostly been copied from the previous `cypress-grep` repo. Apart from the initial installation instructions a lot of references to the older package still exist so are confusing. For example:

- Support File installation instructions are wrong, commands should be `import cypressGrep from '@cypress/grep'`
  - Also worth noting here is that types are incorrect in this case as no declaration is provided for this export
- Similar issue with the Config File section
- Typescript support section again mentions the wrong package `cypress-grep` instead of `@cypress/grep`
- Debugging section mentions wrong package name when searching for the package
- The example repos use the older package which is also confusing, perhaps they can be marked with a warning about that until updating to work with the newer package

Hopefully these are all simple changes to make to avoid any confusion during the migration like we had.

**Comment by emilyrohrbough** [comment]
@BenShelton Is this something you'd be interested in correcting?

**Comment by jordanpowell88** [comment]
I was just noticing this yesterday. This should be a pretty simple fix

**Comment by modern-sapien** [comment]
It looks like our internal readme is correct, but the npm @cypress/grep readme has not been updated.

https://github.com/cypress-io/cypress/issues/24967

**Comment by samtsai** [comment]
Some of these were addressed in: #24844 

I didn't touch the "Debugging section" but that could be a in a follow up.
