### ISSUE TITLE
Add snapshot pinning

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#247]
Currently, snapshots are ephemeral and can only be viewed while mousing over a command, and as soon as you mouse out, the snapshot is replaced by another snapshot or the original state of the DOM. This leaves something to be desired, as it may be useful to inspect the DOM of a snapshot or interact with the page (e.g. by scrolling).

Snapshot pinning would add a button (with a pin icon) to each command, that when clicked, locks the snapshot so that it is not reverted on mouse out and no other snapshots are shown while it is pinned. 

Some requirements:

* A pin button on each command. It should probably only appear on hover
* An indication on the pinned command that it is pinned
* UI over or near the App Under Test, perhaps utilizing the current snapshot message, that indicates that a snapshot is pinned
* UI for unpinning. This should probably be in 2 places:
  - The pin button on the command, which will unpin the snapshot if clicked a 2nd time
  - A universal location, probably near the message mentioned in the previous bullet
* UI for switching between different states of the snapshot (e.g. before and after)
* UI for toggling on/off hitboxes and element highlighting

**Comment by brian-mann** [comment]
Fixed in [`0.17.6`](https://github.com/cypress-io/cypress/wiki/Changelog#0176-10042016).
