### ISSUE TITLE
Cypress often gets stuck when Mackbook executes test cases, especially when the test cases are written and re executed

### ISSUE THREAD

**Issue by sufangyu** [cypress-io/cypress#24707]
### Current behavior

Cypress often gets stuck when Mackbook executes test cases, especially when the test cases are written and re executed

### Test code to reproduce

```
describe("empty spec", () => {
  it("passes", () => {
    cy.visit("https://example.cypress.io");

    cy.get("button").click({ force: true });
  });
});

```

### Cypress Version

11.1.0

### Node version

v16.18.0

### Operating System

macOS 13.0.1

**Comment by nagash77** [comment]
Hi @sufangyu I'm sorry to hear you are encountering issues.  Can I ask what type of Mac hardware are you using?  What kind of processor does it have?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
