### ISSUE TITLE
Docker image cypress/included:11.0.1 fails on ARM with qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped

### ISSUE THREAD

**Issue by normanmunge** [cypress-io/cypress#24706]
### Current behavior

docker run -it --platform linux/amd64 cypress/included:11.0.1 fails on my Apple Mac M1 with
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped

### Desired behavior

I should be able to run Cypress in Docker

### Test code to reproduce

docker run -it --platform linux/amd64 cypress/included:11.0.1

### Cypress Version

11.0.1

### Node version

v14.19.1

### Operating System

macOs 12.6

### Other

Output after trying to run image is:

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
The Test Runner unexpectedly exited via a exit event with signal SIGKILL

**Comment by ryanthemanuel** [comment]
Hi @normanmunge. Thank you for logging this issue. What version of docker are you using? I did some digging and it seems like upgrading docker *might* fix this particular issue.

**Comment by normanmunge** [comment]
Using Docker version 20.10.21 which seems to be the latest.

**Comment by ryanthemanuel** [comment]
Hi @normanmunge. I misread your command earlier. I believe you will need to update it to:

```
docker run -it --platform linux/arm64 cypress/included:11.0.1
```

Note `arm64` instead of `amd64`. This is necessary since you are on an M1. Let me know if that works. Thanks!

**Comment by normanmunge** [comment]
Thanks. This works now.

**Comment by tony-garcia** [comment]
It works, but on the arm platform the cypress/included images don't actually include Chrome or Firefox
