### ISSUE TITLE
Cypress folder not generated after installing cypress & running cypress open

### ISSUE THREAD

**Issue by srinu-kodi** [cypress-io/cypress#2471]
I am facing an issue with Cypress. The issue is, Cypress folder not generated after installing cypress & running cypress open.

The steps what I followed are below.
1. `npm install cypress --save-dev` (Cypress of v3.1.0)
2. `./node_modules/.bin/cypress open`

Node version: 8.9.4
npm: 5.6.0

Log info:

```
./node_modules/.bin/cypress open
It looks like this is your first time using Cypress: 3.1.0

 ✖  Verifying Cypress can run /Users/srinuk/Library/Caches/Cypress/3.1.0/Cypress.app
   → Cypress Version: 3.1.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Users/srinuk/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/MacOS/Cypress
Reason: no suitable image found.  Did find:
/Users/srinuk/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
/Users/srinuk/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
----------

Platform: darwin (17.7.0)
Cypress Version: 3.1.0
```

 I am unable to run the tests as I do not see any alternative other than cypress open. It would be really great if you can provide any alternative, just in case.

**Comment by lilaconlee** [comment]
Have you tried removing `/Users/srinuk/Library/Caches/Cypress/` and reinstalling? I haven't been able to replicate this.

**Comment by drewbrend** [comment]
I saw this before, but I was recently issued a new laptop from IT and this issue is gone on it with the same version of cypress, so it'll be something on your machine, not cypress.  Try cleaning out the cache and reinstalling as @lilaconlee recommended.

**Comment by srinu-kodi** [comment]
Working now after multiple uninstallations & reinstallations of node & npm. 
Closing the issue.

**Comment by srinu-kodi** [comment]
Hi,

I have tried all sorts of options. Moreover, I have deleted node & npm and
reinstalled on my machine and it didn't work

But not sure now, after clearing the cache, it started working.

You can close the ticket and thanks for the support.


Thanks
Srinu

**Comment by basickarl** [comment]
@drewbrend This is an issue from Cypress. You would expect either Cypress cleaning out the cache or in Cypress a command which does it. This messing about yourself isn't exactly good.

**Comment by ManbirJaspal** [comment]
Thanks basicKarl. it worked !!

**Comment by basickarl** [comment]
No problem @ManbirJaspal, the unicorn is here to serve the dumbest solutions known to mankind.
