### ISSUE TITLE
console.error is printed properly on a mac terminal, but not on linux terminal

### ISSUE THREAD

**Issue by firmanserdana** [cypress-io/cypress#24713]
### Current behavior

if we catch a nodejs error on cy.task, and attempt to print its error using console.error, the message would not be printed on Linux terminal, but somehow it's printed on a mac terminal.

Console.logs though is working okay.

### Desired behavior

Making it possible to see console.error message on linux machine's terminal

### Test code to reproduce

```
// function file
public static async anyfunction(): Promise<void> {
   
    return new Promise((resolve, reject) => {
         if (err) {
                return reject(err);
                     }
      //any function
            function (err, ret) {
              if (err || !ret.success) {
                return console.error(err, ret);
              }
              return resolve(anyvar);
            },
          );
        },
      );
    });
  }

// cypress/plugins/index.ts
 async anyfunction() {
      await function.anyfunction();
      return {
        anyvar,
      };
    },

// test file
.....
cy.task('anyfunction');
....
```

### Cypress Version

10.11.0

### Node version

v18.11.0

### Operating System

Nobara OS, Manjaro OS any Linux machine

**Comment by ryanthemanuel** [comment]
Hi @firmanserdana. Thank you for logging this issue. I confirmed this is happening and will route this to the e2e team for further prioritization and work.

Specifically I could recreate this by creating a task:

```js
setupNodeEvents(on, config) {
  on('task', {
    'errorLog': () => {
      console.error('logged!')
      return null
    }
  }
}
```

and then in a test called `cy.task('errorLog')`. On my mac I could see the log. On my linux vm I could not. Note that console.log works on both platforms.

**Comment by firmanserdana** [comment]
Thank you @ryanthemanuel 👍
