### ISSUE TITLE
First test can pass via `cypress open` (purely local) but first test times-out via `cypress run` (local with dashboard uploading).

### ISSUE THREAD

**Issue by JohnLukeBentley** [cypress-io/cypress#24711]
### Current behavior

Using E2E testing I have multiple tests in multiple spec fails that can execute fine locally, via `cypress open`. They generally pass or fail based on whether the target form has the right or wrong business rules.

However, when I try to execute the same cypress script with a view to uploading results to the dashboard, via a `cypress run`, the first test partly runs but times-out part way through. The timeout point is reliably at the same location every time. After a portal login (using Auth0), a link click through to a target form, and before the target form loads. 

### Desired behavior

For the same cypress script to execute identically whether locally (`cypress open`) or with upload to the dashboard (`cypress run`).

### Test code to reproduce

Currently can't provide either a production example or a minimal working example.

### Cypress Version

11.1.0

### Node version

18.12.1

### Operating System

Windows 10 Pro 64bit; Ver: 21H2; OS Build: 19044.2251

### Debug Logs

```shell
## $Env:DEBUG="cypress:*" log

  The following is the end of the log, with anonymized links

      ...
      cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'somesubdomain', domain: 'example', tld: 'io' } +1ms
      cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'somesubdomain', domain: 'example', tld: 'io' } +0ms
      cypress:server:remote-states getting primary remote state: { auth: null, origin: 'https://somesubdomain.example.io', strategy: 'http', fileServer: null, domainName: 'example.io', props: { port: '443', protocol: 'https:', subdomain: 'somesubdomain', domain: 'example', tld: 'io' } } +1ms
      cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'somesubdomain', domain: 'example', tld: 'io' } +0ms
      cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'somesubdomain', domain: 'example', tld: 'io' } +0ms
      cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'example', tld: 'io' } +1ms
      cypress:server:remote-states getting remote state: { auth: null, origin: 'https://somesubdomain.example.io', strategy: 'http', fileServer: null, domainName: 'example.io', props: { port: '443', protocol: 'https:', subdomain: 'somesubdomain', domain: 'example', tld: 'io' } } for: https://example.io +2ms  
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50361 } +165ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50366 } +241ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50379 } +89ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50348 } +549ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50360 } +2ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50368 } +0ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50380 } +1ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50377 } +1ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50378 } +0ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50393 } +0ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50391 } +0ms
      cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
      cypress:server:util:process_profiler ┌─────────┬───────────┬──────────────┬───────────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
      cypress:server:util:process_profiler │ (index) │   group   │ processCount │                           pids                            │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
      cypress:server:util:process_profiler ├─────────┼───────────┼──────────────┼───────────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
      cypress:server:util:process_profiler │    0    │ 'Chrome'  │      7       │ '8484, 23808, 23268, 21584, 29972, 9576 ... 1 more items' │   16.92    │     17.63      │  626.85  │    601.03    │   663.72    │
      cypress:server:util:process_profiler │    1    │ 'cypress' │      1       │                          '19248'                          │    1.7     │      2.97      │  284.82  │    282.74    │   304.89    │
      cypress:server:util:process_profiler │    2    │  'other'  │      6       │         '19064, 22704, 8752, 24792, 30588, 29368'         │     0      │      0.02      │  145.5   │    165.93    │   335.73    │
      cypress:server:util:process_profiler │    3    │ 'ffmpeg'  │      1       │                          '15892'                          │    5.6     │      5.38      │  125.76  │     96.9     │   125.76    │
      cypress:server:util:process_profiler │    4    │ 'plugin'  │      2       │                      '27616, 13772'                       │     0      │      0.54      │   113    │    127.8     │   163.91    │
      cypress:server:util:process_profiler │    5    │  'TOTAL'  │      17      │                            '-'                            │   24.23    │     18.79      │ 1295.93  │   1020.46    │   1341.14   │
      cypress:server:util:process_profiler └─────────┴───────────┴──────────────┴───────────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +12s

## Browser Dev tools >  Console tab

cypress_runner.js:150678 An invalid form control with name='' is not focusable. 

    <input type=​"text" class=​"form-control" id=​"firstname" maxlength=​"30" placeholder=​"Enter first name" validationexpression=​"^[a-zA-Z0-9_]​*$" required>​
...
cypress_runner.js:150678 An invalid form control with name='' is not focusable. 

    <input type=​"text" class=​"form-control" id=​"lastname" maxlength=​"30" placeholder=​"Enter last name" validationexpression=​"^[a-zA-Z0-9_]​*$" required>​
...
cypress_runner.js:150678 An invalid form control with name='' is not focusable. 

    <input type=​"email" class=​"form-control" placeholder=​"Enter email address" id=​"emailAddress" controltovalidate=​"email" validationexpression=​"^([\w-\.]​+)​@((\[[0-9]​{1,3}​\.[0-9]​{1,3}​\.[0-9]​{1,3}​\.)​|(([\w-]​+\.)​+)​)​([a-zA-Z]​{2,4}​|[0-9]​{1,3}​)​(\]​?)​$" errormessage=​"Invalid email address" required causesvalidation=​"True">​


## Browser Dev tools >  Issues tab

    Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute.
```

#### Detailed steps

The steps when I execute locally:
*  `npx cypress open`
* The cypress initial screen opens > [E2E Testing] > Chrome v107 > [Start E2E Testing in Chrome]
* The cypress test runner > Specs > [Click on one of MyTestSpec.cy.ts files]
* The test successfully: logins to the target form, loads it, and begins to click various elements according to the script. An initial run of about 6 tests pass.
* Everything works as expected.

The steps when I try to execute locally, with a recording of results to the Cypress Dashboard
* `$Env:CYPRESS_RECORD_KEY="f4466038-70c2-4688-9ed9-106bf013cd73"` # This Guid is hypothetical, not the GUID for the current project.
* `npx cypress run --spec ".\cypress\e2e\*" --browser chrome --headed --record` 
* The cypress script open up the cypress runner, using a headed chrome browser ...
* The target environment is is logged into (an opening form behind a login).
* A button to the ultimate target form is successfully clicked by the script.
* However, the script reliably stalls (times out) apparently on initial ultimate target form load. The developers of the form have a loading animation which spins indefinitely (until time out).
* At the loading animation the relevant log DEBUG lines start with ....
 
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50361 } +165ms
      cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50366 } +241ms

#### Further notes

* Among the many things I've tried I've downgraded Cypress to 10.0.3; and tried Chromium 103.
* The same script used to work to upload to the Dashboard (via `cypress run`). 
* I know what I've given so far doesn't provide much to narrow down the issue. I'll try to provide more information as I'm able.
* In the end, though, it does seem to be a cypress side problem that the same script can execute via `cypress open` (purely local) but not via `cypress run` (local with upload to the Dashboard).

**Comment by ryanthemanuel** [comment]
Hi @JohnLukeBentley. Thank you for logging this issue. You mentioned that you tried with Cypress 10.0.3. To be clear did that work or did it have the same problem?

**Comment by JohnLukeBentley** [comment]
Hi @ryanthemanuel, thanks for your attention. Indeed I had the same problem when I downgraded to Cypress 10.0.3 yesterday.

The script was working about 2 months ago, both locally and to the dashboard. Since then there has been minor changes to the Cypress script (unlikely to make a difference at the point of the timeout). There has also been some changes to the target form, including a sever migration.

My current, overly broad, suspicion is that a recent change to the target form (and/or environment within it lives) constitutes a rare case that cypress could never handle.

I should also clarify I'm not a dev of the form. I am in communication with the devs and intend for them to have some input here (whether directly or through me).

**Comment by JohnLukeBentley** [comment]
I'm closing this as my specific problem was solved and it is not possible to reproduce the original problem (using code to demonstrate the problem in general).

My specific problem was solved by moving a custom function to clear/reset saved form data: from `beforeEach()` to `afterEach()`.

```TypeScript
Cypress.Commands.add('clearAutoSave', () => {
  try {
    const db = window.indexedDB.open('TheFormName')
    if (!db) return
    console.log(db)

    db.onsuccess = function () {
      try {
        const tx = this.result.transaction('SomeID', 'readwrite')
        if (!tx) return
        tx.objectStore('SomeID').clear()
        console.log('clearAutoSave done');
      } catch (e) {
        console.log(e)
      }
    }
  } catch (e) {
    console.log(e)
  }
})
```

Apparently having this at the beginning of each test run caused some kind of conflict on load of the form (when using `cypress run`).

I'm aware that this "solution" probably violates the [ Clean up state before tests run](https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks) best practice. So I'll probably need to rework the solution.

It is still strange that it worked on a local Cypress open but not when `run`ing Cypress with a view to upload results to the cloud. However, I have no adquete information to shed light on any Cypress level problem.
