### ISSUE TITLE
Cypress Test Runner - v10.3.1 - unable to view previous tests in the runner

### ISSUE THREAD

**Issue by GeetaD09** [cypress-io/cypress#24710]
### Current behavior

Hello, I'm using cypress 10.3.1 and for some reason in the test runner after running all the tests - I am unable to go back to previous tests and go through it step by step and follow asserts visually in the test runner.  is there a setting I need to set?

### Desired behavior

In the past I was able to trace my steps in every test case.  Not able to do that now.

### Test code to reproduce

run tests and after it finishes running I select a previous test and try to trace through it - but unable to view it in the runner.  the view remains at the end of the test last ran.

### Cypress Version

10.3.1

### Node version

14.15.1

### Operating System

Windows 10 Enterprise

**Comment by marktnoonan** [comment]
Hi @GeetaD09 thanks for reporting. Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. You can also use https://github.com/cypress-io/cypress-test-tiny as a template to get started.

What you've described does sound a like a bug, but without any way to recreate it on our end it's not possible to offer any suggestions.

**Comment by GeetaD09** [comment]
Hi Mark,

So here is an example:

I have ran my test cases in the test runner - all passed but some will fail.
I used to be able to go BACK into each test cases and open and trace all watching on the right hand side... fields being populated
As I trace through.  With 10.3.1 version of Cypress, I am unable to trace through the test cases.


***@***.***

Clicking on 'Canadian citizen' - should take me to that test cases and field but it doesn't - seems to stay at the final outcome of the last testcase

***@***.***

Is there a setting I need to enable?  I have auto scrolling enabled.

Currently my setting is this:
***@***.***

Thanks

Geeta

**Comment by marktnoonan** [comment]
@GeetaD09 something is not coming through in your comment, are there supposed to be screenshots? All I see is `***@***.***`.

**Comment by GeetaD09** [comment]
Attaching the screenshots.

**Comment by marktnoonan** [comment]
Hi @GeetaD09 This is not working, please click through to the github issue and edit your comments to add the screenshots. It seems that you are sending them by email and they are getting stripped out.

**Comment by GeetaD09** [comment]
![screenshot1](https://user-images.githubusercontent.com/114174283/203165669-0e5ae19f-102a-4f7e-8d6d-fed391e3f377.jpg)
![screenshot2](https://user-images.githubusercontent.com/114174283/203165685-e96e953f-2e38-4ce9-83a3-63e2315030f2.jpg)

**Comment by GeetaD09** [comment]
Hi Mark,

I attached the screenshots too the issue.

thanks

**Comment by GeetaD09** [comment]
Hi Mark,

Did you get my last email - I attached the screenshots to the issue itself.

Thanks

Geeta

**Comment by mike-plummer** [comment]
Hi @GeetaD09 , it's not obvious from the screenshots what might be causing your issue. We need a [simple, reproducible example](http://sscce.org/) to help diagnose your issue. Without an example, my guess would be that the number of tests you're running is exceeding the [`numTestsKeptInMemory` config parameter](https://docs.cypress.io/guides/references/legacy-configuration#Global) - once you exceed that number we start discarding the snapshots and other low-level details in order to minimize our memory footprint for large test suites. You can try either running a subset of your tests so that you stay under that parameter value, or increase that limit at the cost of higher memory consumption to identify whether this is the issue.

**Comment by GeetaD09** [comment]
Hi mike,

Does say 'snapshots are missing'

What should the 'numTestsKeptInMemory' in cypress.json be set at?
Thanks

Geeta

**Comment by mike-plummer** [comment]
@GeetaD09 There's no "right" value, it depends on the resources available in your local environment and how resource-intensive your tests are. Depending on how you structure your tests you could have many small tests or one massive test that accomplish the same validations. Without a reproduction that I can examine I won't be able to help narrow down potential fixes beyond looking at restructuring & reconfiguring your tests to optimize memory usage vs snapshot retention in "open" mode.

The other way to look at this is whether you really need the full "snapshot" (ability to examine the DOM, see before/after for each command, etc), or whether you're just wanting to see what happened during the spec. Cypress does have the [ability to record all spec runs to video](https://docs.cypress.io/guides/guides/screenshots-and-videos#Videos) which would allow you to review the full spec run regardless of snapshot availability. Note that videos are disabled by default in "open" mode and you would need to make some config changes if you wanted videos to record when running specs via the Cypress UI.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by GeetaD09** [comment]
Can we do a zoom call and I can show you?

**Comment by nagash77** [comment]
Hi @GeetaD09 , Can you provide a reproducible example as Mike requested?  That will be the best way for us to be able to investigate this issue.  Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
