### ISSUE TITLE
how to import certificate in Chrome and cy.visit to URL ?

### ISSUE THREAD

**Issue by kanadev** [cypress-io/cypress#2472]
how to import certificate in Chrome and `cy.visit` to URL ?

### Current behavior:

Cypress is not able to open my login page.

Its throwing following error on chrome:-

```
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.
```

Tried adding following in cypress.json:-
```json
{
  "chromeWebSecurity": false
}
```

### Desired behavior:

Normally cypress should open up the login page of my portal, by accepting the certificate.

### Steps to reproduce:
Visit any HTTPS enable site which needs a certificate to be accepted , a HTTPS site.

### Versions

latest from your site,
Browser:- Chrome- Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
May be related: https://github.com/cypress-io/cypress/issues/771

**Comment by hardikrana437** [comment]
@jennifer-shehane is there any way now to add certificates to cypress?

**Comment by GCHQDeveloper911** [comment]
Hi @jennifer-shehane - can you comment on @hardikrana437 's question please? I think this is a major issue for a lot of people. Are we just missing the solution that's been implemented? Thanks!

**Comment by joeytall** [comment]
Hey @jennifer-shehane, what's the status of this issue? Is it fixed?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue, like a reproducible example, and we'd be happy to reopen.

**Comment by DannyFeliz** [comment]
I need to add a certificate to run my tests in the dev environment; I would love to have this feature.

**Comment by henricook** [comment]
Did you ever find a solution to this @DannyFeliz @kanadev @jennifer-shehane ?

**Comment by DannyFeliz** [comment]
@henricook Sadly, I didn't find a solution at that time, the team bypassed this by using a different environment just for the tests.

**Comment by mihaif0** [comment]
Is there a solution for this ?
