### ISSUE TITLE
Cypress ignores the normalize property of a redux form Field

### ISSUE THREAD

**Issue by carobernat** [cypress-io/cypress#2473]
### Current behavior:

I shouldn't be able to type numbers into that field because of the normalizer, but when I use `cy.get('field').type('123')` it actually types '123' into the field

### Code:

```html
<Field
  name = "firstName"
  type = "text"
  maxLength = "30"
  placeholder = "Ej.: Juan"
  normalize = { names }
  component = { renderInputField }
  label = "¿Cuál es tu nombre?"
/>

<Field
  name="lastName"
  type="text"
  maxLength="30"
  normalize={names}
  placeholder="Ej.: Perez"
  component={renderInputField}
  label="¿Tu apellido?"
/>
```

### Normalizer:
```js
export const names = (value, previousValue) =>  {
  return (value === '' ||
(/^[^±!@£$%^&*_+§¡€#¢§¶•ªº«\\/<>?:;|=.,0123456789-]{1,200}$/.test(value)
  && value.trim() !== '' && (value.length - value.trim().length)<2) ? value : previousValue);
}
```

**Comment by jennifer-shehane** [comment]
Do you know what event the Field is listening for to trigger the normalize code?

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue unless a complete reproducible example is provided. Can you provide a way to reproduce this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
