### ISSUE TITLE
Introduce new chainer .should('include.any.text', ['text1', 'text2'])

### ISSUE THREAD

**Issue by sszemer** [cypress-io/cypress#24731]
### What would you like?

I'd like to be able to verify if text on page satisfies some dictionary/enum

### Why is this needed?

I don't always know the value that should be visible, but i know the possibilities are finite.

### Other

```
  private verifyText() {
    const acceptableValues = ['text1', 'text2'];
    return cy.get('#someId').should('include.any.text', acceptableValues);
  }
```
or even going further, work on enums:
```
  private verifyText() {
    return cy.get('#someId').should('include.any.text', AcceptableValuesEnum);
  }
```

**Comment by brian-mann** [comment]
We'd need to do this for virtually every single assertion method, which would create an almost infinite amount of combinations. You can achieve this today yourself by using a `should(fn)` or an `invoke()` and compose existing chai assertion methods together.

http://www.chaijs.com/api/bdd/#method_oneof

## Examples (I did not test this)

```js
private verifyText() {
  const acceptableValues = ['text1', 'text2']
  
  return cy.get('#someId').should(($el) => {
    const text = $el.text()
    expect(text).to.contain.oneOf(acceptableValues)
  })
}
```

Or you could do something like this to yield the `$el.text()` for you without needing the callback function

```js
private verifyText() {
    const acceptableValues = ['text1', 'text2']

    return cy.get('#someId').invoke('text').should('contain.oneOf', acceptableValues)
  }
```
