### ISSUE TITLE
Queued commands silently skipped when using cy.once() in a custom command

### ISSUE THREAD

**Issue by SecondFlight** [cypress-io/cypress#2474]
I have a custom command, shown below, that ensures that an element cannot be clicked. Using this command causes all remaining commands in the test step to be silently skipped.

HTML:

```html
<html>
  <body>
    <div id='covered' style='position:absolute;background:red;'>asdf</div>
    <div id='uncovered' style='position:absolute;background:blue;'>asdf</div>
  </body>
</html>
```

index.js:

```javascript
Cypress.Commands.add("shouldNotBeClickable", {
    prevSubject: true
}, function(subject) {
    let errorMessage = "shouldNotBeClickable: element click succeeded, but it souldn't have";
    
    let done = false;
    cy.wrap(subject[0]).click({ force: true });
    cy.once('fail', (err) => {
        if (err == errorMessage)
            throw errorMessage;

        expect(err.message).to.include('cy.click() failed because this element');
        expect(err.message).to.include('is being covered by another element');
        done = true;
    });
    cy.wrap(subject[0]).click({timeout: 1000});

    cy.get('html').then(() => {
        if (!done)
            throw errorMessage;
    });
});
```

Cypress test:

```javascript
describe('Test', () => {
    it('Tests z position', () => {
        cy.log("This log should happen.");
        cy.get("#covered").shouldNotBeClickable();
        cy.log("This log should also happen, but it doesn't.");
    });
});
```

### Current behavior:

![inkedchrome_2018-09-14_10-19-28_li](https://user-images.githubusercontent.com/6700184/45555908-0486ea80-b808-11e8-9b96-a048bdeec6b1.jpg)

The last log message does not occur.

Here's what happens when I comment out the call to my command:

![image](https://user-images.githubusercontent.com/6700184/45571009-d8cd2a00-b832-11e8-8613-e99463033970.png)

### Desired behavior:

The custom command should not clear the command queue as a side effect.

### Versions

Cypress 3.1.0
Windows 10
Electron 59

**Comment by JessefSpecialisterren** [comment]
Apparently, this is expected behavior. To quote [https://glebbahmutov.com/blog/cy-metaprogramming/](https://glebbahmutov.com/blog/cy-metaprogramming/): "the first failed assertion stops the test execution." So even if you catch and ignore the failure, it will still stop the test anyway.

**Comment by jennifer-shehane** [comment]
Closing as expected behavior.
