### ISSUE TITLE
When i run a test, during the first execution it doesn't eliminate cache and local storage

### ISSUE THREAD

**Issue by alessandrostassalpitour** [cypress-io/cypress#24752]
### Current behavior

When i run a test with the command "npx cypress open", during the first execution it doesn't eliminate cache and local storage and it access to the site without log-in. But, if i start again the same test through the re-start arrow in cypress-console, it eliminates the cookies and the local storage and it makes the log-in correctly.

My cypress/support/e2e.js's code: 
```
// ***********************************************************
// This example support/e2e.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************
```
// Import commands.js using ES2015 syntax:
```
import './commands'


before(()=> {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.window().then((win) => {
        win.location.href = 'about:blank'
      })
})


beforeEach(()=>{   
    cy.window().then((win) => {
    win.location.href = 'about:blank'
    })
    cy.clearCookies()
    cy.clearLocalStorage()    
    cy.visit("http://mainstream-b2x.tfwb-alca01.alpicn.local/")    
})



afterEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
})

Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  })
```
// Alternatively you can use CommonJS syntax:
// require('./commands')

How i could fix this bug?

### Desired behavior

Eliminate the cookies and the local storage, then make the log-in correctly with insertion of email and password, at the first access. Not only in the next runs of the test

### Test code to reproduce

My cypress/support/e2e.js's code: 
```
// ***********************************************************
// This example support/e2e.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************
```
// Import commands.js using ES2015 syntax:
```
import './commands'


before(()=> {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.window().then((win) => {
        win.location.href = 'about:blank'
      })
})


beforeEach(()=>{   
    cy.window().then((win) => {
    win.location.href = 'about:blank'
    })
    cy.clearCookies()
    cy.clearLocalStorage()    
    cy.visit("http://mainstream-b2x.tfwb-alca01.alpicn.local/")    
})



afterEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
})

Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  })
```
// Alternatively you can use CommonJS syntax:
// require('./commands')

### Cypress Version

11.0.1

### Node version

16.17.0

### Operating System

Windows 10

**Comment by emilyrohrbough** [comment]
@alessandrostassalpitour Can you share more information on the issue you are having? Is it that cookies and local storage are persisting from other domains? I am unable to use the example provided given the private URL. It seems like you are trying to mimic the Test Isolation behavior which will be introduced in our upcoming v12 release. Have you tried leveraging the `experiementalSessionAndOrigin` flag to opt-in to test isolation?

**Comment by alessandrostassalpitour** [comment]
Hi, I have to create a test that controls if it's already logged in our business website (www.alpit*ur.it) and then do a specific navigation. If not, the test makes the log-in and continue with the navigation. It works correctly every time but when i start the test at the first time from cypress console, after i have opened it with "npx cypress console", i landed in the webpage and when i click the log-in button, it doesn't do it cause of it results already logged. But the strange behavior there is when i re-start the test: if the test re-clicks the button to do the log-in, it makes it correctly.

This is my config.js code:
```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
     //General var  
     "GeneralUrl" : "http://mainstream-b2x.t**b-alca01.alpicn.local/",
    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.log(message)     
          return null
        },
      }) 
      // implement node event listeners here
    },
    experimentalSessionAndOrigin: true,
    chromeWebSecurity: false,
    defaultCommandTimeout : 60000,
  },
});
```

As it possible to see, i have already tried to use experimentalSession flag and testIsolation:

```js
describe('Alpitour Maldive Test', {testIsolation : "on"} ,  () => {

  let plpPrice1;
  let pdpPrice1;

  it("Clean cache", ()=>{
    cy.task('log', 'Clean cache')

  })

  it('Navigation Test prova', () => {
    cy.task('log', 'Visits Alpitour site')

    //cy.visit('http://mainstream-b2x.tfwb-alca01.alpicn.local/') 

    cy.task('log', 'Should check correct url')

    if (cy.url().should('include', 'alca01.alpicn')){
      cy.log('URL confirms we are in test environment')
    } else {
      cy.log('WARNIGN: you are not in test ')
    }
```

**Comment by mike-plummer** [comment]
@alessandrostassalpitour I took a quick look at the code you posted. You may want to double-check how you're trying to configure `testIsolation` - [it's a boolean `true`/`false` flag](https://docs.cypress.io/api/commands/session) but it appears you're attempting to provide an `'on'` string value. My suspicion is that your manual adjustment of the window location is causing issues with the cookie & storage clearing since those are domain-specific storage media. As @emilyrohrbough recommended I would advise looking into `cy.origin` and `cy.session` to handle situations where you need to manage cookies/login state/etc. Note: Cypress v12 came out earlier this week and officially released the session & origin APIs so they are no longer behind the experimental flag

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
