### ISSUE TITLE
Receiving cy.xpath is not a function

### ISSUE THREAD

**Issue by VaghasiyaKrupal** [cypress-io/cypress#24764]
### Current behavior

Receiving `cy.xpath` is not a function

I have my `pakage.json` file like below
```
{
  "dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^14.0.0",
    "@cypress/webpack-preprocessor": "^5.15.5",
    "@cypress/xpath": "^2.0.3",
    "cypress": "^11.1.0"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  }
}
```
And my `support/e2e.js` file is 
```
import './commands';
import "cypress-real-events/support";
require('@cypress/xpath');
```
And in my test I have used like that
`cy.xpath(//h6[normalize-space()='Competitors']).click()`

### Test code to reproduce

Install cypress/x[ath plugin using `npm i cypress-xpath`

Put the below line into `support/e2e.js` file
`require('@cypress/xpath');`
and used `cy.xpath` in the test

### Cypress Version

11.1.0

### Node version

16.17.0

### Operating System

Windows 10 Pro

**Comment by mjhenkes** [comment]
@VaghasiyaKrupal, I setup a simple repo setting up xpath but was unable to recreate the issue. 

https://github.com/mjhenkes/xpath

Does this repo run for you?

**Comment by VaghasiyaKrupal** [comment]
@mjhenkes can you please follow the below repo for reproduction? Please run `brain.feature` file
`https://github.com/VaghasiyaKrupal/cucumber-issue`

**Comment by mjhenkes** [comment]
@VaghasiyaKrupal, thanks for the reproduction. I was able to reproduce this. There must be some negative interaction between xpath and cucumber.

**Comment by VaghasiyaKrupal** [comment]
@cypress-app-bot May i know when will be fixed this issue? because I am stuck there.

**Comment by VaghasiyaKrupal** [comment]
@jennifer-shehane Please give me update

**Comment by mrbacky** [comment]
I have the same issue here... 

package.json
```json
"@badeball/cypress-cucumber-preprocessor": "^15.0.0",
"@cypress/webpack-preprocessor": "^5.16.0",
"@cypress/xpath": "^2.0.3",
"cypress": "^12.2.0",
```

xpath works on cypress e2e tests. With cucumber feature tests - xpath is not a function.

**Comment by edgarchm** [comment]
@VaghasiyaKrupal  aren't you missing quotes here?
`cy.xpath(//h6[normalize-space()='Competitors']).click()`  ... should be:
`cy.xpath("//h6[normalize-space()='Competitors']").click()`

**Comment by VaghasiyaKrupal** [comment]
@edgarchm Thanks for your interest actually it is my silly mistake, actually I have your `cy.xpath("//h6[normalize-space()='Competitors']").click()` in my test but I forgot to add in my issue. you can check in below image
![image](https://user-images.githubusercontent.com/45596703/213713626-9a5c77f9-60c2-49cf-9af8-5a4c3f9f795c.png)

**Comment by chethanalb** [comment]
Hey, you got fixed on this one?

**Comment by VaghasiyaKrupal** [comment]
@chethanalb not yet

**Comment by VaghasiyaKrupal** [comment]
Hello @benpatterson @brian-mann @colebrumley @elylucas @emilyrohrbough @estrada9166 @flotwig @jaffrepaul @lmiller1990 @mjhenkes @MuazOthman @rockhold @tgriesser @jennifer-shehane Can you please give me an update on when this issue was fixed? Many users is waiting for a long time and have no updates from the @cypress-github-team-services-sa @cypress-app-bot.

**Comment by Balu14** [comment]
I am facing the same issue, if any one have some solution for this please help

**Comment by Balu14** [comment]
Please follow this.

https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md

It has been resolved my issue.

**Comment by lmiller1990** [comment]
@VaghasiyaKrupal did you try ^

**Comment by madmacc** [comment]
I have the same issue with the same config as @mrbacky but I'm not using cucumber.
```
    "@cypress/schematic": "^2.4.0",
    "@cypress/xpath": "^2.0.3",
    "cypress": "latest", 

    Cypress 12.8.1
```

support/e2e.ts:
`import '@cypress/xpath';`

support/component.ts:
`import '@cypress/xpath';`

Did anyone figure out a solution to this?
![image](https://user-images.githubusercontent.com/43654472/228684995-fdb21b2a-ef1e-41a8-8c33-dfc0d71fbd1c.png)

**Comment by lmiller1990** [comment]
Can you share a minimal reproduction? Looking at the code, as long as you import that file, it should register:

https://github.com/cypress-io/cypress/blob/develop/npm/xpath/src/index.js#L161-L165

**Comment by madmacc** [comment]
@lmiller1990 I have managed to replicate this in a repo.
https://github.com/madmacc/Cypress-xpath-example

Initially I used "@cypress/schematic": "^2.5.0" and this did not have the issue however it will not let me use this with my existing project and it uses 2.4.0.

Commands I used:
```
ng add @cypress/schematic
npm i @cypress/xpath --save-dev
Add import '@cypress/xpath'; to support/e2e.ts and support/component.ts
npm i -D @types/cypress@latest --save-dev
ng e2e
```

**Comment by lmiller1990** [comment]
Is this an issue in the schematic then, perhaps 🤔 ?

Thanks for the repro!

**Comment by balaji2711** [comment]
I have installed version 2.0.1 of the cypress-xpath plugin, but I am still encountering the same issue.

**Page Object Class:**

class GoogleSearch {
    get googleSearch() {
      return cy.xpath("//textarea[@title='Search']").first();
    }
    get googleSearchBtn() {
      return cy.get('input[name="btnK"]').first();
    }
    get searchResults() {
      return cy.get('h3').first();
    }
    get searchFifthResult() {
      return cy.xpath("//a[contains(@href,'https://en.wikipedia.org/wiki')]").first();
    }
  }
  
  export default new GoogleSearch();
  
**Tests:**

import search from "../page-objects/google.search.page";

describe('Google Navigation', () => {
    it('Google Search', () => {
    cy.visit('https://www.google.com')
    search.googleSearch.type("Something");
    search.googleSearchBtn.click({force:true});
    search.searchResults.should('be.visible');
    });
});

![image](https://github.com/cypress-io/cypress/assets/15344129/45229287-63ec-48bd-b2be-c1de256d029c)

**Comment by jennifer-shehane** [comment]
We’ve made a decision to no longer support the [cypress/xpath](https://www.npmjs.com/package/@cypress/xpath/access) plugin. See https://github.com/cypress-io/cypress/pull/26893 for more context. We'll close this issue as we will not be releasing any more changes to the xpath plugin.
