### ISSUE TITLE
after:spec no longer fired after end of test in open mode

### ISSUE THREAD

**Issue by 123elias** [cypress-io/cypress#24776]
### Current behavior

When running a test in open mode the after:spec event is not fired when a test is completed. It is fired when you close the browser.

### Desired behavior

Before it was fired. This event is used by us to trigger cleanup code.

### Test code to reproduce

on('after:spec', async (spec) => {
    console.log('event fired');
});

### Cypress Version

10.11.0

### Node version

v16.17.1

### Operating System

Windows 10

**Comment by mjhenkes** [comment]
Based on our documentation, this is the expected behaviour.

>The after:spec event fires after a spec file is run. When running cypress via cypress open, the event will fire when the browser closes.

https://docs.cypress.io/api/plugins/after-spec-api#Syntax

Can you use the 'after' hook to trigger clean up code instead?

**Comment by anne-gaelle123inkt** [comment]
Hey, 
it is the same bug than this one, which was for before:spec but for after:spec
https://github.com/cypress-io/cypress/issues/22360

it was also working before and now it's not working anymore
