### ISSUE TITLE
Build 'create from React component' UI

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#24773]
Create from React Component requires a slightly different user flow from Create from Vue Component. This is because we need to parse the selected file to determine whether there are any React components defined in the file that we can create a spec for.

Create all of the UI necessary to match the designs [in Figma](https://www.figma.com/file/gq6zQUQ1bx2uqfnF64lwX9/Create-from-React-Component?node-id=0%3A1&t=Psd6euLyYiR2aCKd-0) and mock the API interactions if it isn't completed yet.

Most of the UI is the same as Create from Vue except for the "Select a Component" view. This view should be created with a loading (for when we are parsing the file) and empty state (for when there are no React components defined in the file).

See the [Create from React Component tech brief](https://github.com/cypress-io/tech-briefs/tree/main/briefs/ct-create-from-react-component) for guidance

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24773?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by baus** [comment]
As part of this issue, update the user docs to explain this feature. Should be similar to the work for Create from Vue Component
