### ISSUE TITLE
Implement 'create from React component' logic

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#24774]
Implement all of the server-side logic that we need for Create from React Component feature. This should include

- React component spec file template (see `packages/data-context/src/codegen/templates/vue-component/vue-component.ejs` for example)
- Query that takes a path to a file and returns a list of React components in that file, using [react-docgen](https://github.com/reactjs/react-docgen) to parse the file

See the [Create from React Component tech brief](https://github.com/cypress-io/tech-briefs/tree/main/briefs/ct-create-from-react-component) for guidance

[Figma designs](https://www.figma.com/file/gq6zQUQ1bx2uqfnF64lwX9/Create-from-React-Component?node-id=0%3A1&t=4zY13RAbZqIikzLH-0) for reference

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24774?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
