### ISSUE TITLE
Mixing cy.on()/cy.once() with a one-argument it() function causes test to hang

### ISSUE THREAD

**Issue by SecondFlight** [cypress-io/cypress#2478]
Giving the lambda passed into the `it()` block a single argument will cause Cypress to pass a function in that must be called for the test to finish.

If you use the `cy.on()` command inside an `it()` block with a single-argument function, the test will hang when it reaches `cy.on()`.

HTML:

```html
<html>
  <body>
    <div id='covered' style='position:absolute;background:red;'>asdf</div>
    <div id='uncovered' style='position:absolute;background:blue;'>asdf</div>
  </body>
</html>
```

Test:

```javascript
describe('Test', () => {
  it('Tests done()', done => {
    let shouldCallDone = false;

    cy.log('This log should happen.');

    cy.once('fail', (err) => {
      shouldCallDone = true;
    });

    cy.get('#covered').click({ timeout: 1000 });

    cy.log('This log should also happen, but it doesn\'t.');

    cy.get('html').then(() => {
      if (shouldCallDone)
        done();
      else
        throw "done() was never called."
    });
  });

  it('Tests cy.log', () => {
    cy.log('This log should happen too, but it also doesn\'t.');
  });
});

```

### Current behavior:

![image](https://user-images.githubusercontent.com/6700184/45574467-2307d880-b83e-11e8-822f-90f8c000a3d8.png)

Notice how the test has been running for almost 14 minutes.

### Desired behavior:

This code should not cause Cypress to hang.

### Versions

Cypress 3.1.0
Windows 10
Electron 59

**Comment by Bkucera** [comment]
I believe this bug is caused by Cypress clearing the timeout erroneously, so the test hangs forever.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
