### ISSUE TITLE
Stubbed Responses still hitting Server

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#2479]
### Current behavior:

I am attempting to stub responses to our analytics endpoints so that our requests do not hit analytics endpoints (which charge us per event). I thought, why not use stubbing? 

![image](https://user-images.githubusercontent.com/2848185/45577294-23997280-b830-11e8-8930-4936bcad29ce.png)

![image](https://user-images.githubusercontent.com/2848185/45577316-39a73300-b830-11e8-828b-3c2237a03c44.png)

![image](https://user-images.githubusercontent.com/2848185/45577506-2d6fa580-b831-11e8-9ff3-b327d124a77e.png)

![image](https://user-images.githubusercontent.com/2848185/45577331-52174d80-b830-11e8-9fea-3b336ebe5193.png)

![image](https://user-images.githubusercontent.com/2848185/45577344-652a1d80-b830-11e8-9574-5ef27f3af561.png)

![image](https://user-images.githubusercontent.com/2848185/45577363-7b37de00-b830-11e8-8dca-d69b8e9a35f5.png)

Yet in Mix Panel:

![image](https://user-images.githubusercontent.com/2848185/45577388-94d92580-b830-11e8-80e2-518579dd7965.png)

**PS: I Only switched the localhost domain to `poop.localhost` after ensuring all test cases were setup

Expectation: Stubbed requests shouldn't actually hit my server...right?

**Comment by Narretz** [comment]
Just to check, are you using fetch? stubbing fetch is not supported.

**Comment by egucciar** [comment]
@Narretz nope. This is an XHR im able to capture and assert against. See the way its setup and the screenshot which shows its both stubbed and invoked multiple times. And that the stub returned as well in the network response.

yet still, these requests hit the real server, despite us receiving the stubbed responses.

**Comment by jennifer-shehane** [comment]
I would suggest using `blacklistHosts` to prevent the requests from going to the analytics server. 

[Docs here](https://on.cypress.io/configuration#blacklistHosts)

**Comment by jennifer-shehane** [comment]
Hey @egucciar, did `blacklistHosts` help your problem here?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
