### ISSUE TITLE
`window.__tcfapi` is undefined in Cypress' testing iframe for sites with Quantcast Consent Modal

### ISSUE THREAD

**Issue by symn** [cypress-io/cypress#24796]
### Current behavior

Follow-up from here: https://github.com/cypress-io/cypress/issues/22948#issuecomment-1322388915

We test a site that contains a Quantcast consent modal and receive an error which says that `window.__tcfapi` is undefined.

This comment sums up the problem (https://github.com/cypress-io/cypress/issues/22948#issuecomment-1197375703):

>  it looks like window .__ tcfapi is part of an API in the service of GDPR: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#how-does-the-cmp-provide-the-api

> Within Cypress, your site will be loaded within an iframe, which may impact how you or third-parties execute code. Can you track down what logic should be defining `window .__ tcfapi` and whether or not it executes as expected when loaded in an iframe?

Before the update to `cypress@11.1.0` on `cypress@5.0.0`, we were able to copy necessary functions into the window object that Cypress has access to via a workaround, like so:

```
 cy.on('window:before:load', (win) => {
    let __tcfapi;
    Object.defineProperty(win, '__tcfapi', {
      get: () => {
        if (!__tcfapi) {
          __tcfapi = win.top.__tcfapi;
        }
        return __tcfapi;
      },
      set: (value) => {
        __tcfapi = value;
      }
    });

    let __uspapi = undefined;
    Object.defineProperty(win, '__uspapi', {
      get: () => {
        if (!__uspapi) {
          __uspapi = win.top.__uspapi;
        }
        return __uspapi;
      },
      set: (value) => {
        __uspapi = value;
      }
    });
  });
```

However, this fails now **except** on the first run. I think it has something to do with how Cypress handles multiple test runs now. I noticed that the Cypress testing browser window does not refresh anymore for new tests but adds new (project) iframes. This might be a problem with my simple copy / paste mechanism? 

### Desired behavior

It should load the test page without causing an error. Basically, it should be possible for the test page to create an iframe (`__tcpapiLocator`) and/or properties on `window` and have access to them even though they are created on runtime.

### Test code to reproduce

Important to note that you might need a European IP to have the consent modal show up in the first place.
Just visit this URL: https://www.baeldung.com and see if a modal pops up (this is not our page but uses Quantcast and throws the same error as our site).

Add custom command to `support/index.js`
```
Cypress.Commands.add('visitSiteWithQuantcastConsentModalAndAgree', (url) => {
  // Quantcast Consent v2.0 modal asynchronously creates functions on the `top`
  // window object that are not accessible from inside the Cypress test iframe. This
  // rewrites the functions from `top` window to the one Cypress tests can access.
  cy.on('window:before:load', (win) => {
    let __tcfapi;
    Object.defineProperty(win, '__tcfapi', {
      configurable: true,
      get: () => {
        if (!__tcfapi) {
          __tcfapi = win.top.__tcfapi;
        }
        return __tcfapi;
      },
      set: (value) => {
        __tcfapi = value;
      }
    });

    let __uspapi = undefined;
    Object.defineProperty(win, '__uspapi', {
      get: () => {
        if (!__uspapi) {
          __uspapi = win.top.__uspapi;
        }
        return __uspapi;
      },
      set: (value) => {
        __uspapi = value;
      }
    });
  });
  cy.visit(url);

  cy.waitForDOMElement('qc-cmp2-ui');
  cy.contains('Agree', {matchCase: false}).click();
});
```
Add test:
```
describe('web', () => {
  it('loads without an error', () => {
    cy.visitSiteWithQuantcastConsentModalAndAgree('https://www.baeldung.com/');
  });
});
```

Run the test two times

### Cypress Version

11.1.0

### Node version

16.0.0

### Operating System

macOS 12.0.1 Monterey

**Comment by BlueWinds** [comment]
> However, this fails now except on the first run. I think it has something to do with how Cypress handles multiple test runs now. I noticed that the Cypress testing browser window does not refresh anymore for new tests but adds new (project) iframes. This might be a problem with my simple copy / paste mechanism?

This seems like a good analysis - we've had a variety of changes around how the AUT is created recently in order to speed up tests, and you may have been bitten by one of them.

I get 403 forbidden when I try to visit `https://www.baeldung.com/`, so can't run this locally to be sure, but it looks to me like `win.top` isn't the right place to be reading `__tcfapi` from. `top` is probably the Cypress app, rather than any location where `__tcfapi` is defined. I'm guessing we have an iframe structure like

Cypress App
-- Your application under test
---- The iframe you're trying to mess with

so .top() isn't pointing the right place.

More robust iframe support is at the top of our [roadmap](https://github.com/orgs/cypress-io/projects/13/views/1), but that's not much help right now, I know!

**Comment by chrisbreiding** [comment]
Going to close due to inactivity. Looks like we don't have enough information to reproduce this issue on our end. Please comment with a reliable reproduction and we can re-open.
