### ISSUE TITLE
xhr race condition cause test result to be undeterministic

### ISSUE THREAD

**Issue by khanhlu2013** [cypress-io/cypress#2480]
### Current behavior: 
In my test i have

```js
   search.exe(searchStr); //ajax request to remove server 
   search.getLoadingIcon().should("be.visible"); 
```

if i purposely delay my server response around `60ms`, it is likely to pass. However, if i reduce my latency to around `50ms`, test sometimes will not be able to catch `LoadingIcon` visibility because it disappear too quickly.

### Versions
version 3.1.0, osx, chrome browser

**Comment by jennifer-shehane** [comment]
Hey @khanhlu2013, I'm unfamiliar with this exact api that you're using? Could you explain what `search.exe` and `search.getLoadingIcon` does and include the entirety of the code from any custom commands?

**Comment by khanhlu2013** [comment]
Hi

```
search.exe = (email)=> {
    cy.get("#inputId")
    .clear()
    .type(`${email}{enter}`);
}

search.getLoadingIcon = ()=> cy.get("#loadingIcon")

```

Context: I have an email search box. When i fill out the search email and hit enter, my app will hit the back end. While waiting for the backend to response i will start a `LoadingIcon` and stop it when the backend response with data. 

As you can see, i expect my `LoadingIcon` to be visible as soon as I hit enter in my search input. If my backend response too quickly, the LoadingIcon will start and stop too quickly and cypress will not be able to notice that the `LoadingIcon` is visible at all. When put a setTimeout in the backend to fake delay response, I can see that my test start to fail more often at 50ms delay.

**Comment by jennifer-shehane** [comment]
@khanhlu2013 Were you able to resolve your issue?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
