### ISSUE TITLE
Testing services

### ISSUE THREAD

**Issue by dvkuenssberg** [cypress-io/cypress#24809]
### What would you like?

Hello,

in my Angular project I am looking to replace existing Karma tests with Cypress tests, which works for components. However, is there a way to test the logic of services (e.g. a service which performs backend calls) in a similar isolated manner? If not, is this something which may be provided in the future?

Thanks!

### Why is this needed?

Having Cypress as an all-around testing solution instead of working with different frameworks would simplify the development process.

**Comment by ZachJW34** [comment]
You should be able to test your services in a very similar way that you were testing them in your Karma tests. Mounting Angular components utilizes `TestBed` under the hood but there is nothing preventing the user from importing this into their tests then using `TestBed.configureTestingModule({...})` + `service = TestBed.inject(TodosService);`.

If you want to it feel more real-world, you could create a Test component that lives inside your spec file that you can mount that injects the Service.

@jordanpowell88 think we should add some documentation around this?

**Comment by dvkuenssberg** [comment]
That makes sense, thank you for the explanation!
