### ISSUE TITLE
Applet Error while Clicking on hyperlink in Siebel application

### ISSUE THREAD

**Issue by vinoth5261** [cypress-io/cypress#24808]
### Current behavior

Does Cypress supports automating Siebel application? I can login to application & navigate different pages. When clicking on hyperlink, it shows Applet error

Error: The applet field with name "s_1_1_76_0" doesn't exist.(SBL-UIF-00289)

While manually, I can click on the hyperlink and navigate

### Desired behavior

Clicking on hyperlink should navigate or drilldown further

### Test code to reproduce
```
cy.visit("[https://vega.test2.swissptt.ch/fe1_oui_enu_sec/"](https://vega.test2.swissptt.ch/fe1_oui_enu_sec/%22));
cy.get('input[name="SWEUserName"]').type('username');
cy.get('input[name="SWEPassword"]').type('password');
cy.get('.siebui-login-btn').click();
cy.url().should('include', '/siebel');
 cy.viewport(1000,660);
cy.get('li[title="Execute Query"]').click();
cy.get('.siebui-search-option').click();
cy.get('#srch_adv_find').click();
cy.get('#searchtoolbar').click();
cy.get('#searchtoolbarsrch').click();
cy.get('.siebui-advance-find-fields').should('be.visible');
cy.get('#find_field_reset_button').should('be.visible').click();
cy.get('input[title="Reference #"]').type('6101513166');
cy.get('#find_field_button').should('be.visible').click();
cy.wait(5000);
cy.get('a').contains('Quote Nr.').click();
```
### Cypress Version

10.3.1

### Node version

V16

### Operating System

Windows

**Comment by chrisbreiding** [comment]
Sorry to see you're encountering an issue and for the delayed response. Unfortunately I can't reproduce your issue because the site at `https://vega.test2.swissptt.ch/fe1_oui_enu_sec/` doesn't seem to be operational. Is there maybe an updated URL I could use to run your reproduction against?

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
