### ISSUE TITLE
Cypress Docker The Test Runner unexpectedly exited via a exit event with signal SIGKILL

### ISSUE THREAD

**Issue by webInRoad** [cypress-io/cypress#24805]
### Current behavior

The Test Runner unexpectedly exited via a exit event with signal SIGKILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Debian - 11.3)
Cypress Version: 10.7.0

### Desired behavior

Execute code normally

### Test code to reproduce
```js
 const { caseId, groupName, timeStamp } = params
  const fileName = caseId + '-' + timeStamp
  const sourceReport = {
    reportDir: `public/ucase/mocha/${fileName}`,
  };
  
  fse.ensureDirSync(sourceReport.reportDir);
  const specName = groupName || "other"
  cypress.run({
    spec: `cypress/e2e/mock/${specName}.spec.js`,
    config: {
      screenshotsFolder: `${sourceReport.reportDir}/screenshots`,
      video: false,
      videosFolder: `${sourceReport.reportDir}/videos`,
    },
    reporter: 'cypress-mochawesome-reporter',
    reporterOptions: {
      reportDir: sourceReport.reportDir,
      overwrite: false,
      html: true,
      json: false,
      embeddedScreenshots: true,
      inlineAssets: true,
      autoOpen: false,
      saveAllAttempts: false,
      reportPageTitle: '用例执行报告'
    }
  }).then(function(results) {
    if(results.totalFailed) {
      console.error('Could not execute tests')
      console.error(results.message)
    } 
    res.json(results)
  }).catch(err => {
    console.error(err.message)
    process.exit(1)
  });
```
### Cypress Version

10.7.0

### Node version

v16.14.2

### Operating System

Linux version 5.4.117-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) 

### Other

There is a problem when triggering cypress.open ({...}) multiple times.

**Comment by webInRoad** [comment]
Help to see

**Comment by jennifer-shehane** [comment]
Unfortunately there’s not enough to reproduce this issue on our side. Please try a newer version. If the issue persists, open an issue with a full repo we can run and reproduce.
