### ISSUE TITLE
Cypress is reading <iframe> tag as text

### ISSUE THREAD

**Issue by StefanTegeltija** [cypress-io/cypress#24807]
### Current behavior

Cypress is reading <iframe> tag as text

### Desired behavior

<iframe> doesn't suppose to be read as text

### Test code to reproduce
so if you have something like this 
```
<div data-testid=content> 

<h1>Some title</h1> 

<iframe width="560" height="315" src="https://www.youtube.com/watch?v=sXxzOPqyk-E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe> 

<p>dummy text</p></div> 
```
and if you have assertions for eg. 
```
cy.get('[data-testid="content"]').should('contain.text', 'Some title dummy text');
}); 
```
You will get error I already tried the following: should(have.text, 'Some title dummy text'), (include.text, 'Some title dummy text') and cy.get('[data-testid="content"]').contains('Some title dummy text')

### Cypress Version

11.2.0

### Node version

16.16.

### Operating System

Mac OS

**Comment by nagash77** [comment]
Hi @StefanTegeltija,  Can you help me understand what behavior you are seeing that is incorrect?  From what I see in the ticket you have a ```div``` that has an ```iframe```within it and a ```<p>dummy text</p>```  tag.  You are looking for ```Some title dummy text``` which does not exist in the example you provided so it should be failing.  Am I missing something?

**Comment by StefanTegeltija** [comment]
Hey @nagash77 

No. This assertion has to be true
```
cy.get('[data-testid="content"]').should('contain.text', 'Some title dummy text');
}); 
```
but cannot be because cypress is reading iframe as text , so in this case cypress will return something like
```
Some title(function(){window.pagespeed=window.pagespeed||{};var b=window.pagespeed;function c(){}c.prototype.a=function(){var a=document.getElementsByTagName("pagespeed_iframe");if(0<a.length){for(var a=a[0],f=document.createElement("iframe"),d=0,e=a.attributes,g=e.length;d<g;++d)f.setAttribute(e[d].name,e[d].value);a.parentNode.replaceChild(f,a)}};c.prototype.convertToIframe=c.prototype.a;b.b=function(){b.deferIframe=new c};b.deferIframeInit=b.b;})();\npagespeed.deferIframeInit();dummytext
```
instead 

Some title dummy text


https://ibb.co/hBF8whJ
https://ibb.co/QYcp7Cf

Please check this 2 images. On them you can see that cypress is reading video as text.

Please contact me again if you'd need more information.

**Comment by emilyrohrbough** [comment]
@StefanTegeltija I used the following [example](https://github.com/cypress-io/cypress-test-tiny/tree/issue-24807) to try and reproduce the error you are seeing. I added an example with the iframe content you provided and I also removed the iframe to try & produce the passing assertion that you are expected. I am not seeing the iframe content being picked up like you are seeing -- though I am noticing the youtube content that is loaded does not match the screenshots you shared. Here are the errors I am seeing for both cases:
<img width="456" alt="Screen Shot 2022-12-23 at 9 26 03 AM" src="https://user-images.githubusercontent.com/14099737/209359903-6a567dd4-3d6b-4e5a-9fb1-ac7ea7bc2b08.png">

Can you please update the branch I shared to provide an example that demonstrates the issue you are having?

**Comment by StefanTegeltija** [comment]
Hi Emily,

I have tried to reproduce this issue on your example and I have gotten the same results as you. So I don't know what is problem. If I find out in the future I will let you know. Thank you for your help. I appreciate.

**Comment by emilyrohrbough** [comment]
@StefanTegeltija I wonder what was happening! Glad you are able to get this working. I'm going to close this issue for now. If you are able to reproduce this later, please add a comment to this issue and we can re-open to investigate.
