### ISSUE TITLE
CLI borders are all noise on Windows Azure CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2481]
- running Cypress tests on Windows hosted VM on Azure CI https://glebbahmutov.visualstudio.com/cypress-example-kitchensink-fork/_build/results?buildId=29&view=logs
- the step `Run Cypress tests` shows non-ascii characters for all CLI boxes
<img width="1114" alt="screen shot 2018-09-15 at 4 58 48 pm" src="https://user-images.githubusercontent.com/2212006/45590570-e359f300-b908-11e8-9227-03b1eb597802.png">

Command goes through
```
[section]******************************************************************************
[section]Starting: Run Cypress tests
[section]******************************************************************************
==============================================================================
Task         : Command Line
Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
Version      : 2.136.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
Generating script.
Script contents:
npm run test:ci:record
[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\d29ef00f-42d4-4f38-ac23-80844a524e1b.cmd""

> cypress-example-kitchensink@1.0.2 test:ci:record D:\a\1\s
> run-p --race start:ci e2e:record
```

I would be ok with an environment flag to disable graphical lines

Cypress 3.1.0

**Comment by jennifer-shehane** [comment]
This appears to no longer be happening in our Azure CI build: https://cypress-io.visualstudio.com/cypress-example-kitchensink/_build/results?buildId=389

Refer to our Azure configuration here: https://github.com/cypress-io/cypress-example-kitchensink#ci-status
