### ISSUE TITLE
Unable to change the source root

### ISSUE THREAD

**Issue by kpayson** [cypress-io/cypress#24827]
### Current behavior

There is an error opening cypress component testing if the source root folder is not called "src"

In my case the "src" folder is named "ui"
The sourceRoot folder setting is updated in angular.json to reflect the folder name.

`      "root": "",
      "sourceRoot": "ui",
      "prefix": "app",`

When I open cypress and go to component testing, I get the following error.  I can reproduce this on a brnad new angular application. 

![image](https://user-images.githubusercontent.com/923449/204148979-9c971fd6-120a-4e79-a1b6-8fddddf46b1f.png)

### Test code to reproduce

Brand new angular app.

Change name of "src" folder to "ui"

update angular.json sourceRoot setting

open cypress

goto component tests

### Cypress Version

11.2.0

### Node version

16.15.0

### Operating System

macOS 12.5.1

**Comment by rockindahizzy** [comment]
Hey @kpayson thanks for reporting this issue. I was able to recreate this issue. It looks like there is a difference when we start the dev server compared to how Angular is doing it. I've routed this to the component testing team to look into. Thanks!

**Comment by rockindahizzy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24827?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by ZachJW34** [comment]
@kpayson I ran into some issues with a custom `srcRoot` but couldn't reproduce your exact issue. Could you provide a reproduction of the issue? I have a fix for the issues I saw (assets/favicon loading) but I want to verify that it fixes the issue your facing as well.

**Comment by ZachJW34** [comment]
@kpayson Here are some binaries with my changes that should fix your problem. If you are able, could you try to reproduce your issue with the binary to see if it's fixed

https://github.com/cypress-io/cypress/commit/191e140ce3ba677757b5d39e3b894fe86f0178b6#comments
