### ISSUE TITLE
Incorrect/misleading error messages when passing wrong arguments

### ISSUE THREAD

**Issue by Dragas** [cypress-io/cypress#24826]
### Current behavior

Cypress schedules actions that would be executed later during actual testing. This in turn causes an issue where the parameters for those actions are validated only during the execution step, rather than the scheduling step. As a result, when passing invalid argument types (object for a string, ex.) cypress outputs internal stacktrace, rather than pointing to the user written test.

### Desired behavior

Cypress would save a stacktrace of place that scheduled the action, and output that instead of internal stacktrace.

### Test code to reproduce

```js
beforeEach(() => {
    cy.fixture(document, "binary"). then((file) => {});
})
describe("misleading error message", () => {
  it("I shall now output misleading error", () => {

  });
});
```

### Cypress Version

Cypress/included:8.6.0 docker image

### Node version

Cypress/included:8.6.0 docker image

### Operating System

Cypress/included:8.6.0 docker image

### Debug Logs

```shell
cypress_1               |      TypeError: The "path" argument must be of type string. Received an instance of Object
cypress_1               | 
cypress_1               | Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `I shall now output...`
cypress_1               |   TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
cypress_1               |       at validateString (internal/validators.js:124:11)
cypress_1               |       at Object.join (path.js:1110:7)
cypress_1               |       at Object.get (/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/lib/fixture.js:38:20)
cypress_1               |       at getFixture (/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/lib/socket-base.js:129:62)
cypress_1               |       at backendRequest (/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/lib/socket-base.js:276:36)
cypress_1               |       at tryCatcher (/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
cypress_1               |       at Function.Promise.attempt.Promise.try (/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
cypress_1               |       at Socket.<anonymous> (/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/lib/socket-base.js:314:46)
cypress_1               |       at Socket.emit (events.js:376:20)
cypress_1               |       at Socket.emitUntyped (/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
cypress_1               |       at /root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
cypress_1               |       at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by Dragas** [comment]
Same issue can be reproduced by moving fixture action to the test out of beforeEach block.

**Comment by nagash77** [comment]
Hi @Dragas I see you are using an older version of Cypress.  Do you see the same issues on the latest version of Cypress?

**Comment by Dragas** [comment]
I'm afraid I can't upgrade cypress in our current project, but i'll try
reproducing in the newer versions.

**Comment by nagash77** [comment]
@Dragas Would you mind elaborating on why you are unable to upgrade your version of Cypress?  Community usage feedback can help us identify impediments to regular upgrading of Cypress which is something we want to encourage.  Our thinking being if it is easy and smooth, then more folks will upgrade to the latest and greatest.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
