### ISSUE TITLE
Error: Incompatible SockJS! Main site uses: "1.1.5", the iframe: "1.1.4".

### ISSUE THREAD

**Issue by Kerumen** [cypress-io/cypress#2483]
### Current behavior:

I have a `create-react-app` app not ejected (react-scripts v2.17.0) and when I open my app in Cypress to test it the call `/sockjs-node/009/snavibkq/xhr_streaming?t=1537201023204` fails and I have this error in the console:

<img width="578" alt="screen shot 2018-09-17 at 18 22 22" src="https://user-images.githubusercontent.com/5436545/45635941-a75c9480-baa6-11e8-8565-60823db23b02.png">

### Desired behavior:

No errors should be logged.

### Steps to reproduce:

Will try to setup a reproducible test case but I wanted to open the issue to let you start investigate and to know if there is a simple solution available.

### Versions

cypress v3.1.0
react-scripts v2.17.0

**Comment by Kerumen** [comment]
Okay I solved my own problem, I had a conflict with the `sockjs-client` in my dependencies. Removing the `1.1.4` version fixed it.

**Comment by tnrich** [comment]
@Kerumen can you explain more about this problem. I think I might be running into something similar with 
https://github.com/cypress-io/cypress/issues/2823

I am really confused by this error..

**Comment by tnrich** [comment]
```
thomass-mbp:openVectorEditorTgen tnrich$ yarn why sockjs-client
yarn why v1.10.1
[1/4] 🤔  Why do we have the module "sockjs-client"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "sockjs-client@1.1.5"
info Reasons this module exists
   - "nwb#webpack-dev-server" depends on it
   - Hoisted from "nwb#webpack-dev-server#sockjs-client"
info Disk size without dependencies: "1.11MB"
info Disk size with unique dependencies: "1.56MB"
info Disk size with transitive dependencies: "1.88MB"
info Number of shared dependencies: 9
✨  Done in 0.92s.
```

**Comment by tnrich** [comment]
Oh.. hmm this error is probably coming from my nwb app server throwing an error for some reason. I am still confused as to why it would be doing that. Maybe something to do with hot module reloading..?

**Comment by techiechap** [comment]
> Okay I solved my own problem, I had a conflict with the `sockjs-client` in my dependencies. Removing the `1.1.4` version fixed it.

Could you pls let us know the sockjs-client configuration,
