### ISSUE TITLE
Not able to redirect to application on test after google authentication using cy.origin() on cypress 10.10.0

### ISSUE THREAD

**Issue by MounikaBodicherla** [cypress-io/cypress#24836]
### Current behavior

 I upgraded to cypress 10.10.0 to use cy.origin() for google authentication (accounts.google.com). I am able to proceed with entering my email id and password. After that, the main application is not loading. Again, it is showing the page with the Google Login button. Could you please help me with the solution?

### Test code to reproduce

I used the below code:
```js
cy.visit('Main application URL');
cy.findAllByText('google-saml').eq(1).click();
cy.origin('https://accounts.google.com/o/oauth2/auth/identifier', () => {
  //Google Authentication
  cy.get('input[type="email"]').type('email');
  Cypress.on('uncaught:exception', (err) => {
  if (err.message.includes('ResizeObserver')) {
    return false;
  }
});
cy.get('.VfPpkd-vQzf8d').eq(1).click(); //click on Next
cy.wait(2000);
cy.get('input[type="password"]').type('password');
cy.get('.VfPpkd-vQzf8d').eq(1).click(); //click on Signin
});
```
### Cypress Version

10.10.0

### Node version

v18.11.0

### Operating System

macOS13

**Comment by mjhenkes** [comment]
How does your page verify that you have logged in? Cookies? Can you verify if those are present or not after logging in with chrome?

**Comment by BlueWinds** [comment]
With not enough information to reproduce or help, we're going to have to close this. Feel free to comment here or open another issue with more details.
