### ISSUE TITLE
Getting Error BabelLoaderError: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by maamounapprise** [cypress-io/cypress#2484]
### Current behavior:

Getting Error BabelLoaderError: SyntaxError: Unexpected token when I run all cypress versions. I even tried browserify and without webpack-preprocessor. 
Below you can see a forked repo that reproduce the issue. I think this has something to do with the library flow-typed and babel? @chrisbreiding 
### Steps to reproduce:
Adding flow types and using spread operator.

Repo that has the issue: 
https://github.com/maamounapprise/cypress-cra-issue

### Versions
Node: 8.11.3
react-scripts: 1.1.5
Cypress: 3.1.0
Cypress/webpack-preprocessor: 1.1.3
flow-bin: 0.81.0
styled-components: 3.4.6

**Comment by chrisbreiding** [comment]
The default preprocessing does not support Flow types, so you'll need to configure it to work by adding the babel Flow preset.

[Here's a solution using the browserify preprocessor]https://github.com/cypress-io/cypress/issues/2350#issuecomment-419772427). Configuring it for the webpack preprocessor should be similar.

**Comment by maamounapprise** [comment]
@chrisbreiding Thanks!
