### ISSUE TITLE
[IATR](M1.1) Open In IDE button for debug spec component header

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#24850]
Update Spec header on the Debug page to include an option to click the icon and open the spec in the user's IDE.

* Icon in front of Spec name should be a link that calls the existing function to open the spec in the user's IDE
  * Should show tooltip on hover that says "Open in IDE"	
* If Spec cannot be found in the local project
  *  Icon should be the one shown in the Figma 
  *  The user should not be able to click the icon, and instead it should show a tooltip on hover that says "Opening in IDE is disable because the spec is not found in this project"
* If they do not have a IDE selected, open the modal

![image](https://user-images.githubusercontent.com/1702361/215821032-2775ce87-1f84-4355-8766-0a2dd1fc89e5.png)

Figma: https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=23976%3A230871&t=8aknVEZZAwkm7HVg-1

Clickup: https://app.clickup.com/t/18033298/PM-2546

**Comment by mike-plummer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24850?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @warrensplayer @ZachJW34
