### ISSUE TITLE
[IATR](M1.0) Debug sidebar status count

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#24852]
Update the sidebar nav to show a count of failed tests from the cloud

### New icon
* Update the icon for the Debug page to be the new "bug" icon

_Before_
<img width="180" alt="Screen Shot 2022-12-06 at 12 15 19 PM" src="https://user-images.githubusercontent.com/1702361/205978441-f21ebf3e-9d40-443c-897e-d229f464be6c.png">
 _After_
<img width="187" alt="Screen Shot 2022-12-06 at 12 15 39 PM" src="https://user-images.githubusercontent.com/1702361/205978463-37a28297-7485-430c-9b62-d5d93d53e991.png">

### Badges

Note: The presence of a run, the failed test count and run status will be available to the badge through either a store or an existing GQL query.

#### Add "New" badge
* The "New" badge is shown when there is no Cloud project connected or no runs (states: not logged in, no project, project has no runs at all) and the feature was released <= 2 months ago (hard coded is fine; e.g. current time <= release date + 2 months)
* The "New" badge should not be shown if there a relevant run has been determined and a failed count badge is being shown
<img width="197" alt="Screen Shot 2022-12-06 at 12 25 18 PM" src="https://user-images.githubusercontent.com/1702361/205980765-5586c106-43da-47fa-93b1-5e902a5025ea.png">

#### Add failed test count badge

* Green badge 	
	* If the run shown in/used by Debug has status passed, then show the number 0 in that run in a green badge
<img width="197" alt="Screen Shot 2022-12-06 at 12 26 06 PM" src="https://user-images.githubusercontent.com/1702361/205980900-4a1bc9d3-265c-4540-829a-3700c22a88a7.png">

* Red badge	
	* If the run shown in/used by Debug has status failed, then show the number of failed tests in that run in a red badge
	* If the run shown in/used by Debug has status has error statuses and at least 1 failure, then show the number of failed tests in that run in a red badge
<img width="197" alt="Screen Shot 2022-12-06 at 12 26 16 PM" src="https://user-images.githubusercontent.com/1702361/205980985-5161b091-a3ee-4e52-afe3-deb7e7cb10df.png">

* Orange badge
	*	If the run shown in/used by Debug has status has error statuses and 0 failures, then show the number 0 in an orange badge
<img width="197" alt="Screen Shot 2022-12-06 at 12 26 27 PM" src="https://user-images.githubusercontent.com/1702361/205981496-7579ab12-23c9-4179-8793-5b3f477aac3f.png">
 
**Collapsed side nav**

* When the side nav is collapsed, badges should still appear.
* If the count badge has a number > 10, then change the text to say `9+`
<img width="145" alt="Screen Shot 2022-12-06 at 12 59 03 PM" src="https://user-images.githubusercontent.com/1702361/205986825-16e1b4c9-8360-4e50-b04e-c8605bcd4da9.png">

Clickup: https://app.clickup.com/t/18033298/PM-2546
[Figma designs](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=21998%3A208933&t=0OHOefQTzf0GCexU-1)

**Comment by ZachJW34** [comment]
Is there a use case for the darker-red color of the badge?
