### ISSUE TITLE
[IATR](M1.1) Specs list query update to sync logic with debug page

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#24858]
TODO 
Clickup: https://app.clickup.com/t/18033298/PM-2546

**Comment by mike-plummer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24858?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @warrensplayer @ZachJW34

**Comment by ZachJW34** [comment]
Is this ready for work? Maybe I'm not great at navigating Clickup but I couldn't find any clear requirements as to what we are supposed to accomplish with this issue (and thus it's hard to estimate)

**Comment by warrensplayer** [comment]
This is not ready for work yet.  Removing from estimating.

**Comment by warrensplayer** [comment]
Will not work right now pending discussions around the runs page.
