### ISSUE TITLE
[IATR](M1.1) Empty state tour for Debug page

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#24857]
TODO 
Clickup: https://app.clickup.com/t/18033298/PM-2546

**Comment by mike-plummer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24857?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @warrensplayer @ZachJW34

**Comment by warrensplayer** [comment]
This is not ready for estimating yet.  Will not be considered for this release.

**Comment by warrensplayer** [comment]
Replaced by https://github.com/cypress-io/cypress/issues/25768
