### ISSUE TITLE
Cypress spy not being called when VueJS component emits event

### ISSUE THREAD

**Issue by joeczucha** [cypress-io/cypress#24879]
### Test code to reproduce

Vue SFC:

    <script setup>
    </script>

    <template>
      <button data-testid="credits" @click="$emit('onCredits')">Click</button>
    </template>

Cypress test:

    import { createTestingPinia } from '@pinia/testing';

    import Button from './Button.vue';

    describe('<Button />', () => {
      it('renders', () => {
        const pinia = createTestingPinia({
          createSpy: cy.spy(),
        });

        cy.mount(Button, {
          props: {
            onCredits: cy.spy().as('onCreditsSpy'),
          },
          global: {
            plugins: [pinia],
          },
        });

        cy.get('[data-testid=credits]').click();
        cy.get('@onCreditsSpy').should('have.been.called');
      });
    });

### Current behavior

After following the guide [here](https://docs.cypress.io/guides/component-testing/vue/examples#Testing-Event-Handlers), my test is failing with:

> expected onCreditsSpy to have been called at least once, but it was never called

### Desired behavior

The test should pass.

### Cypress Version

11.2.0

### Node version

16.14.0

### Operating System

macOS 12.6.1

**Comment by mike-plummer** [comment]
Hi @joeczucha, thanks for opening an issue and sorry it took us a minute to get back to you. I think this may be a simple naming issue - Vue has some special rules around the "on" prefix. The event being emitted is generally "eventName" and the prop registering for that event would be "onEventName". In your example, you would emit `credits` and the handler would be `onCredits`. If you update your SFC to emit `credits` I think it should work

**Comment by mike-plummer** [comment]
Since we have a solution and there hasn't been activity on this issue I'm going to go ahead and close this as resolved. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by joeczucha** [comment]
Hi @mike-plummer, apologies for my slow reply. 

Yes - that did the trick.

Thanks again for your response.
