### ISSUE TITLE
Running cypress on GitHub actions will run test twice

### ISSUE THREAD

**Issue by nitinchalopadho** [cypress-io/cypress#24872]
### Current behavior

I am running a test using Cypress 9.5.7 and GitHub actions and every time I run an action GH will run the test twice one on Chrome and the other on Electron. Second test always fails on Electron. Electron browser seems to be a default browser for Cypress. The intersting thing is that when I run on Cypress Dashboard the test runs only once on Chrome. But twice on GitHub actions.

I talked to a few developers and we couldn't find a solution. Anybody has ever expeerince this issue and how did you resolve it??

I tried just removing / bypass electron

@brian-mann @jennifer-shehane @nagash77 @ryanthemanuel @marktnoonan 

### Test code to reproduce

```
return {
    browsers: config.browsers.filter(
      (b) => b.name === 'chrome'
    ),
  }
```

### Cypress Version

10.9.0

### Node version

12.18.0

### Operating System

macOs 10.15.7

**Comment by emilyrohrbough** [comment]
@nitinchalopadho Sorry to hear you are having troubles with running Cypress in Github actions. At this time, there isn't enough information for me to help you uncover the issue you are experiencing. A few questions:
- Are you using the [Cypress Github Action](https://github.com/marketplace/actions/cypress-io) or are you using a custom workflow?
- Can you please share your setup and the command(s) you are using to run Cypress in chrome and electron?
- To confirm, do you want to run both tests in both chrome and electron?

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
