### ISSUE TITLE
Access component functions when testing components

### ISSUE THREAD

**Issue by dvkuenssberg** [cypress-io/cypress#24870]
### What would you like?

When writing Angular component tests, it is possible to access the instance of the rendered component as described [here](https://docs.cypress.io/guides/component-testing/angular/examples#Accessing-the-Component-Instance). However, using this approach I cannot access any functions that the component provides (using `cy.spy(wrapper.component, 'function')`). I am only able to access properties which are defined in `componentProperties`, however I do not want to implement every function twice in order to test it.

My goal is to spy on a function in the component which performs some logic, ensure that it has been called with the correct arguments and delivers the correct result. This could for example be a function which performs a backend request after a button click.

Is it possible to directly access a component's functions and spy/perform assertions on them?

### Why is this needed?

This would allow testing a component's function's behavior in a straightforward manner.

**Comment by mike-plummer** [comment]
Hi @dvkuenssberg , thanks for reaching out. The behavior you describe is possible, I just did a quick reproduction locally that worked using Cypress 12.0.1:

Component: simple button that calls a public function which in turn calls a private function
```
import { Component } from '@angular/core'

@Component({
  selector: 'clicker',
  template: `
    <div>
      <button data-cy="click" (click)="onClick()">Click Me!</button>
    </div>
  `,
})
export class ClickerComponent {
  constructor() {}

  onClick(): void {
    this.internalOnClick()
  }

  private internalOnClick() {
    console.log('I was clicked!')
  }
}
```

Spec: mounts component, spies public and private functions. Clicks button and validates both spies were called. Note that we have to keep the Typescript compiler happy, so I had to do a hard cast to allow spying the `private` function
```
import { ClickerComponent } from './clicker.component'

describe('ClickerComponent', () => {
  it('calls internal function when expected', () => {
    cy.mount(ClickerComponent)
    .then((wrapper) => {
        cy.spy(wrapper.component, 'onClick').as('onClick')
        cy.spy(wrapper.component, 'internalOnClick' as any).as('internalOnClick')
    })

    cy.get('@onClick').should('not.have.been.calledOnce')
    cy.get('button').click()
    cy.get('@onClick').should('have.been.calledOnce')
    cy.get('@internalOnClick').should('have.been.calledOnce')
  })
})
```

**Comment by dvkuenssberg** [comment]
Hi @mike-plummer, thank you for the clarification!

I also noticed the other day that it is possible to do this (and to access any component property) when mounting the component as `cy.mount(MyComponent)`, however it does not work if it is mounted using the Angular template syntax, e.g. `cy.mount('<app-my-component></app-my-component>')`, which I mainly used so far, leading me to open this issue.

When mounting the component with the Angular template syntax, I can only access properties which have been declared in the `componentProperties` field. Therefore this includes not being able to access any functions, since they were not declared in `componentProperties`. Is this this intentional?

Currently using Cypress 11.2.0.

**Comment by jordanpowell88** [comment]
Try giving it a type `cy.mount<MyCompoment>('<app-my-component></app-my-component>')`

**Comment by mike-plummer** [comment]
@dvkuenssberg I tinkered with this a bit and found a way that appears to work. Doesn't feel quite as elegant as my original solution and relies on additional Angular platform logic which may or may not be an issue depending on your setup, but this works for me and allows use of template strings in the mount:

```
import { By } from '@angular/platform-browser'
import { ClickerComponent } from './clicker.component'

cy.mount<ClickerComponent>(
  `<clicker></clicker>`, {
  declarations: [ClickerComponent],
})
.then((wrapper) => {
  const fixture = wrapper.fixture
  const clickerDebugElement = fixture.debugElement.query(By.directive(ClickerComponent))
  const clickerInstance = clickerDebugElement.componentInstance

  cy.spy(clickerInstance, 'onClick').as('onClick')
```

**Comment by dvkuenssberg** [comment]
Thank you for suggesting this, I will keep it in mind!

**Comment by georgyevv** [comment]
> 

Wow just thank you! 

And why is this `wrapper.component.writeValue('test')` not working when I even have an autocomplete :/

Cypress please update your documentation and add more examples. Every line is a struggle because there is no information on how you must do things...

**Comment by kddsultan** [comment]
Pleas update the docs for angular too. The [documentation](https://docs.cypress.io/guides/component-testing/angular/api#MountResponse) is really misleading for `MountResponse`:


The returned value does not have either the `fixture` & `component`

**Comment by jennifer-shehane** [comment]
@kddsultan Our docs are open source, we'd be open to a PR to improve any docs. https://github.com/cypress-io/cypress-documentation
