### ISSUE TITLE
Raise minimum TypeScript version to 3.7

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#24875]
### What would you like?

Raise the minimum TypeScript version to 3.7.

### Why is this needed?

This would allow certain TypeScript features like recursive types, useful for typing things like JSON. 

### Other

This would be a breaking change.

Would need to document this and update the dtslint config to not check version less than 3.7.

**Comment by lmiller1990** [comment]
What makes this a breaking change? Not disagreeing in general (it's a major version bump) but do we know what would break users when bumping this dependency?

**Comment by jennifer-shehane** [comment]
This was addressed in 13.0.0 and raised to 4.0+ See https://docs.cypress.io/guides/tooling/typescript-support#History
