### ISSUE TITLE
Snapshot is missing. Displaying current state of the dom.

### ISSUE THREAD

**Issue by oaktree4** [cypress-io/cypress#24882]
### Current behavior

Hello everyone, getting into cypress and stumbling upon the following issue.

Im tryng to run this simple test (visit a webapp which uses a third party identification servicr)
```js
describe('empty spec', () => {
   it('Test', () => {
    cy.visit('https://test.app.sequello.com/')
  })
})
```
Although, what happens in cypress is the following. The screen is blank and when I hover over the test body I get the following error message "The snapshot is missing. Displaying current state of the DOM"

![image](https://user-images.githubusercontent.com/63807087/204624821-2f32159d-5e15-4701-b348-b99661669e98.png)

Can someone tell me what is the issue here and how can I solve it?

Kind regards

### Desired behavior

Successfully opening the third party application service, authenticating and navigating back to the inital webapp

### Test code to reproduce
```js
describe('empty spec', () => {
  it('Test', () => {
    cy.visit('https://test.app.sequello.com/')
  })
})
```
cypress.config.js looks like this:
```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    watchForFileChanges: false,
    defaultCommantTimeout: 5000,
    experimentalSessionAndOrigin: true,
   
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

### Cypress Version

11.2.0

### Node version

16.16.0

### Operating System

Windows 10 Home

**Comment by emilyrohrbough** [comment]
Hi @oaktree4. The message `"The snapshot is missing. Displaying current state of the DOM"` is displayed if the log associated in the reporter did not take a DOM snapshot when the log was generated. That is not an issue on your end, but behavior of the navigation events logs as they captures and reported as they come in.
