### ISSUE TITLE
Update references to plugins in example repos / preprocessor repos

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2488]
In anticipation of changing the `plugins` nomenclature to `background`, need to update all example repos and repos like the preprocessor repos that references plugins.

**Comment by chrisbreiding** [comment]
- [cypress-webpack-preprocessor](https://github.com/cypress-io/cypress-webpack-preprocessor/pull/25)
- [cypress-browserify-preprocessor](https://github.com/cypress-io/cypress-browserify-preprocessor/pull/16)
- [cypress-parcel-preprocessor](https://github.com/cypress-io/cypress-parcel-preprocessor/pull/38)
- [cypress-watch-preprocessor](https://github.com/cypress-io/cypress-watch-preprocessor/pull/3)
- [cypress-example-recipes](https://github.com/cypress-io/cypress-example-recipes/pull/205)
- [cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink/pull/123)
- cypress-example-todomvc (need access for PR)
- cypress-example-api-testing (need access for PR)
- cypress-example-docker-codeship (need access for PR)
- cypress-example-group (need access for PR)
- [cypress-example-parallel](https://github.com/cypress-io/cypress-example-parallel/pull/1)

**Comment by emilyrohrbough** [comment]
Changes coming in 10.0 will replaces `plugins` with a `nodeEvents` concept. This is no longer applicable.
