### ISSUE TITLE
[Cypress-Dashboard-AnalyticsTab]The last column popup in the run status chart flickers when you hover over it.

### ISSUE THREAD

**Issue by priyankvadaliya753** [cypress-io/cypress#24895]
### Current behavior

When the user hovers over the last column of the Run Status chart, the popup flickers, and the status is not clearly visible.

https://user-images.githubusercontent.com/82139164/204705503-21766ab8-97d3-4a5c-8ca8-371ae0c43e8e.mov

### Test code to reproduce

1) log in to Cypress Dashboard
2) click on Analytics - >Run status
3) on the run status chart try to directly hover on the last column 
4) observe the Status Popup

### Cypress Version

11.2.0

### Node version

v16.13.1

### Operating System

MacOS 13.0.1

**Comment by rockhold** [comment]
@priyankvadaliya753, thanks for reporting the issue and sharing the video. That is very helpful! I can reproduce this if I resize my browser window to make it smaller. Can you confirm if your window is at all resized? Or are you seeing this without resizing?

**Comment by priyankvadaliya753** [comment]
> @priyankvadaliya753, thanks for reporting the issue and sharing the video. That is very helpful! I can reproduce this if I resize my browser window to make it smaller. Can you confirm if your window is at all resized? Or are you seeing this without resizing?

Hello, @rockhold. This happens when I resize my browser window

Thanks

**Comment by ryanpei** [comment]
we've released a fix, thanks for pointing this out!
