### ISSUE TITLE
Migrate from WindiCSS to mainline TailwindCSS

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#24907]
### What would you like?

Migrate from WindiCSS to TailwindCSS in the main repo.

### Why is this needed?

- WindiCSS looks dead https://github.com/windicss/windicss/issues
- docs are quite a bit worse
- Tailwind has some new features like named groups that aren't supported in Windi
- Windi will eventually slow us down, using a non maintained library isn't ideal when better, updated version exists

### Other

I think we've got a icon plugin for WindiCSS. The rest of the migration is almost 1:1, I think it should be pretty smooth.

**Comment by adarshmadrecha** [comment]
Also, Windi CSS is Sunsetting
ref: https://windicss.org/posts/sunsetting.html

**Comment by lmiller1990** [comment]
We did it, it wasn't too difficult, here's the PR https://github.com/cypress-io/cypress/pull/26516
