### ISSUE TITLE
Cypress Google Authentication doesn't return consistent result across different browsers

### ISSUE THREAD

**Issue by srkrish** [cypress-io/cypress#24906]
### Current behavior

Followed the setup prescribed in [https://docs.cypress.io/guides/end-to-end-testing/google-authentication](url) and executed the test in Electron (v106) and after setting up the `window.localStorage.setItem('googleCypress', JSON.stringify(userItem))` and executing `cy.visit('/')` the following chain of requests is performed,

```
visit / -> 302: https://accounts.google.com/o/oauth2/v2/auth?client_id=<IAP-client-id>.apps.googleusercontent.com&response_type=code&scope=openid+email&redirect_uri=https://iap.googleapis.com/v1/oauth/clientIds/<IAP-client-id>.apps.googleusercontent.com:handleRedirect&code_challenge=<some-code>&code_challenge_method=<some-code>cred_ref=true&state=<some-long-gibberish-code>
-> 302: https://accounts.google.com/AccountChooser?oauth=1&continue=https%3A%2F%2Faccounts.google.com%2Fsignin%2Foauth%2Flegacy%2Fconsent%3Fauthuser%3Dunknown%26part%<som-long-gibberish-code>%26client_id%3D<IAP-client-id>.apps.googleusercontent.com%23"
-> 302: https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Faccounts.google.com%2Fsignin%2Foauth%2Flegacy%2Fconsent%3Fauthuser%3Dunknown%26part%3DAJi8hAO82MlkiFSABeZR2fRTrOrWnM2kbehai8V0hmO4-TmkOBm6BCakTIiOaHMNgFMRj-24glwCdx2fHOyv
```
And displayed the default Google login page within the Cypress iFrame. Tried with Firefox and Chrome Headless, it returned the same result

### Desired behavior

Surprisingly when I tried Chrome (v107), I got the expected outcome and the redirection is as follows,

```
visit / -> 302: https://accounts.google.com/o/oauth2/v2/auth?client_id=<IAP-client-id>.apps.googleusercontent.com&response_type=code&scope=openid+email&redirect_uri=https://iap.googleapis.com/v1/oauth/clientIds/<IAP-client-id>.apps.googleusercontent.com:handleRedirect&code_challenge=<some-code>&code_challenge_method=<some-code>cred_ref=true&state=<some-long-gibberish-code>
-> 302: https://iap.googleapis.com/v1/oauth/clientIds/<IAP-client-id>.apps.googleusercontent.com:handleRedirect?state=<some-long-gibberish-code>code=<some-code>&scope=email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&hd=<OrgDomain>.com.au&prompt=none"
-> 302: https://<baseUrl>/?gcp-iap-mode=AUTHENTICATING&redirect_token_v2=<some-long-gibberish-code>
```

Post this I'm able to execute other cy commands

### Test code to reproduce

Exactly followed the instructions mentioned under https://docs.cypress.io/guides/end-to-end-testing/google-authentication and made no additional configuration apart from what is mentioned in the doc

### Cypress Version

10.11.0

### Node version

v16.13.0

### Operating System

macOS 13.0.1

### Other

Cleared the app data as suggested in https://docs.cypress.io/guides/references/troubleshooting#Clear-App-Data and the Chrome (v107) which was working earlier started reflecting the "Current Behavior "

**Comment by srkrish** [comment]
I can supply the Debug Logs but they're really verbose and long. Please let me know the specific Log Source and I can supply here. Thanks

**Comment by srkrish** [comment]
Hi Team, the standard procedure discussed https://docs.cypress.io/guides/end-to-end-testing/google-authentication is on the basis the target application uses Local Storage to authenticate sessions and in my case it was done through session cookies by associating id token to a particular key. I'd request the Cypress team to update the below statement to reflect this. Thanks for creating this awesome tool!

> With our Google app setup properly, necessary environment variables in place, and our loginByGoogleApi command implemented, we will be able to authenticate with [Google](https://google.com/) while our app is under test. Below is a test to login as a user via Google, complete the onboarding process and logout

**Comment by emilyrohrbough** [comment]
@sainthkh 
Per the issue you opened, it is unclear to me the issue you are experiencing. Are you just noting the redirect routes differ between browsers? or are you having issues because of this behavior? 

> I'd request the Cypress team to update the below statement to reflect this.

Please feel free to open a Pull Request in cypress-documentation with the suggestions you have to clarify this guide. It's not a one-size-fits all but we hope that it overall provides a general and easy-to-follow example users can modify to fit their needs.

**Comment by sainthkh** [comment]
@emilyrohrbough it's @srkrish, not me, right?

**Comment by srkrish** [comment]
@emilyrohrbough I'm calling out that applications are either using LocalStorage or Cookiesession to authenticate the login and the cypress documentation explains only about LocalStorage, whereas in this [blog](https://filiphric.com/google-sign-in-with-cypress) it explains about how to set a Cookie session and enable Programattic authentication. I'll raise a pull request to suggest in the documentation. Thanks

**Comment by emilyrohrbough** [comment]
sorry @sainthkh .... meant for @srkrish.

@srkrish I see what you are saying. Are you okay if I close this issue if you plan to open a PR to add this information to the guide?

**Comment by chrisbreiding** [comment]
Going to close this and look forward to a PR for the cypress-documentation repo.
