### ISSUE TITLE
cypress run not respecting specPattern config

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#24912]
### Current behavior

I've got a head scratcher here. I think a screenshot is worth a 1000 words: 
![image](https://user-images.githubusercontent.com/2730609/204930123-58d1641d-236d-4961-b2e7-fff0a3a065e0.png)

As you can see I'm passing: 
```
--config specPattern="/Users/tnrich/Sites/teselagen-react-components/cypre
ss/e2e/UploadCsvWizard.spec.js"
```

But for some reason the test runner is running a completely different test

### Test code to reproduce

```
git clone https://github.com/TeselaGen/teselagen-react-components ~/teselagen-react-components
cd ~/teselagen-react-components;
yarn;
npx cypress run --headed --no-exit --e2e --browser chrome --config specPattern="~/teselagen-react-components/cypre
ss/e2e/UploadCsvWizard.spec.js"
```

It runs the editableCellTable spec instead..

To clean up after repro-ing: 
```
rm -rf ~/teselagen-react-components
```

??? Very weird one ??? What's going on ??

Thanks in advance!

### Cypress Version

11.2.0

### Node version

v16.13.0

### Operating System

macOS 12.6

**Comment by emilyrohrbough** [comment]
@tnrich This was definitely a weird/confusing issue! However I have tracked it down to your project's configuration setup. The [resolved configuration](https://docs.cypress.io/guides/references/configuration#Resolved-Configuration) order of precedence is:
- Default value
- [Cypress configuration file](https://docs.cypress.io/guides/references/configuration)
- The [Cypress environment file](https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypress-env-json)
- System [environment variables](https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS)
- [Command Line arguments](https://docs.cypress.io/guides/guides/command-line)
- [setupNodeEvents](https://docs.cypress.io/guides/references/configuration#setupNodeEvents)

Looking at your configuration setup, the specPattern is being set in the [setupNodeEvents callback](https://github.com/TeselaGen/teselagen-react-components/blob/master/cypress.config.js#L7) which has the "final" say in what pattern is used. After I moved this configuration to the top-level in your project:
```js
module.exports = defineConfig({
  e2e: {
   specPattern: "cypress/e2e/**/.js",
    setupNodeEvents(on, config) {
...
```
I can successful run:
```bash
yarn test --headed --no-exit --e2e --browser chrome --config specPattern="~/teselagen-react-components/cypress/e2e/UploadCsvWizard.spec.js"
```

Closing this issues. Please leave a comment or open another issue if something else becomes troublesome.

**Comment by tnrich** [comment]
@emilyrohrbough good digging thanks for figuring this out and writing such a clear answer!

**Comment by emilyrohrbough** [comment]
My pleasure 😃
