### ISSUE TITLE
cy.stub is not working for functions on an iframe's content window

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#2491]
I need to stub analytics functions from test cases so that we do not spam our analytics server. 

So far the work was going well until I hit a snag with my `iframes`. After much head banging against the desk, I realized all the code as correct, so it must be Cypress. 

Fortunately, I don't have a big need to actually *use* the sinon stub for its intended purpose in an` iframe`, but i still want to override the function itself so it doesnt call our services. Now everything works, but I would be much happier if I could actually use `cy.stub` to stub out functions within the window of an iframe:

```js
      ANALYTICS_METHODS.forEach(method => {
        if (isIframe) {
          // annoyingly, cy.stub just doesnt work with iframe
          // so let's just surpress analytics events like so:
          window.analytics[method] = () => {};
        } else {
          stubs[method] = cy.stub(window.analytics, method, (...args) => {
            // console.log('[analytics-stub]', method, ...args);
          });
        }
      });
```

PS - This just silently Errors with `cy.stub`. I've confirmed 100 times over all the logic was correct so it was narrowed down to `cy.stub` not actually stubbing.

**Comment by egucciar** [comment]
Sure thing. I'll check it out. But be advised stub doesn't work and fails silently in iframes so you may want to handle it, but it's probably lower priority.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
