### ISSUE TITLE
Cypress prints `(uncaught exception) undefined: undefined` when promise rejects with a string

### ISSUE THREAD

**Issue by geritol** [cypress-io/cypress#24915]
### Current behavior

When the app code rejects with a string:
- developer console displays the error properly
- cypress displays `(uncaught exception) undefined: undefined` and fails the test

### Desired behavior

- cypress displays the exact error cause (reject's string content) and fails the test

### Test code to reproduce

https://github.com/geritol/cypress-bug-repro

### Cypress Version

11.2.0

### Node version

v16.18.1

### Operating System

macOS 12.6

**Comment by mike-plummer** [comment]
Hey @geritol , thanks for opening an issue! I can certainly see how that would be annoying - we do print the rejection with appropriate error message to the browser console, but you're right that we don't always parse out the correct message for the Cypress command log resulting in the "undefined: undefined" behavior. I'll go ahead and forward this enhancement on to the team, but there's no guarantee if/when they'll have bandwidth to dig into it.

In the interim, we always welcome [open source contributions](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) if you (or anyone else) if interested in taking a stab at this! I did a little investigation and it should be a fairly trivial issue for a first-time contributor. It appears that the logic in `packages/driver/src/cypress/error_utils.ts` needs to be updated - the `logError` function assumes that the uncaught error is an `Error` object, but in this case it's a `string`. The logic building the `message` string needs to be updated to detect whether the `err` param is a string and if so use that as the message, then add/update tests as needed
