### ISSUE TITLE
`indexedDB.databases()` doesn't resolve when running through `Cypress open` using Electron

### ISSUE THREAD

**Issue by frankieyan** [cypress-io/cypress#24914]
### Current behavior

Take this test snippet:

```TypeScript
cy.visit('https://google.ca')

cy.window().then((win) => {
  return win.indexedDB.databases().then(db => {
    cy.log(db.toString())
  })
})
```

When this is executed with `cypress run`, the `databases` promise resolves correctly:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/8531248/204962718-95057639-6ec0-4ebc-8439-e24749b1abb0.png">

However, when running with `cypress open`, the promise is never resolved:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/8531248/204962760-987cc221-8572-4c5e-96be-b1741eeb8fe6.png">

In both cases, Electron is used headedly. 

When Chrome is used with `cypress open`, the test passes successfully, so it looks like it only affects Electron.

### Desired behavior

Both cases should succeed, whether `open` or `run` is used.

### Test code to reproduce

Repo with reproduction: https://github.com/frankieyan/cypress-indexeddb-repro

### Cypress Version

v12.1.0

### Node version

v18.12.1

### Operating System

macOS 13.0

**Comment by frankieyan** [comment]
Hi, I tested the latest v12.1.0 release and the issue persists there. Please let me know if there's anything else we need to debug this 🙏

**Comment by emilyrohrbough** [comment]
@frankieyan Thank you for providing a reproducible example! It's super helpful for verifying the issue and determining the root-cause of the issue. Unfortunately, the example you provided appears to be working as expected on my machine in both open and run mode. I am running this on macOS Monterey v12.6 with Cypress 12.1.0. Below is a video of this working in open mode:

https://user-images.githubusercontent.com/14099737/208928490-c3e9d251-d7e1-43b6-8770-8fd616557063.mov

I'll be honestly, I'm not sure why it's working for me and causing you issues. Have you tried increasing the `.then()` timeout to see if it helps? I know indexeddb can be slow.

**Comment by frankieyan** [comment]
Hi @emilyrohrbough, thanks for testing this out! Unfortunately, I've tried a 12 second timeout with no luck. Although after testing some more, I think the issue was introduced in v10.10.0. I'm able to consistently reproduce while the test passes on v10.9.0 on repeated runs.

v10.9.0
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/8531248/208981014-3641688d-3bb7-42a9-ad3a-ea6efc4c5321.png">

v10.10.0
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/8531248/208981249-92e0cbd4-4e3c-4a40-b0a1-d98b7cf6c3de.png">

v12.2.0:
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/8531248/208979033-1527d72b-04ac-4870-a21f-bc6f20074d36.png">

Looking at the changelog, nothing obvious jumps out other than the Electron upgrade: https://github.com/cypress-io/cypress/issues/23843

Might be hard to get to the bottom of this one, could it be OS dependent? I'm currently on Ventura 13.0 without access to another machine, but I could ask my colleagues to help reproduce as well.

**Comment by emilyrohrbough** [comment]
@frankieyan Interesting...Wonder if it could be? I was running just fine with Cypress 12. I did hear to wait on the Ventura upgrade 😅 If you could check if any of your colleagues are having this issue, that'd be great. Also I assume you've opened the chrome dev tools to check for errors in the terminal?

**Comment by frankieyan** [comment]
Some of my colleagues were also able to get the test to pass while on macOS > 13.0, so it sounds like it's just a problem on my end. Unfortunately, I still have no idea what it could be.

There is nothing in the console but various warnings thrown by the site under testing, e.g. google's trackers. The promise just never resolves, nor does it get rejected.

Since Chrome and `cypress run` are both still working options for me, let's close this issue for now 👍 thanks for your help!
