### ISSUE TITLE
Searched word reverted after re-opening the chrome window

### ISSUE THREAD

**Issue by mohanbabu-zumen** [cypress-io/cypress#24936]
### Current behavior

1. Open the chrome browser from the cypress window.
2. Search the feature file name
3. Run the same
4. Close the browser
5. Now, again open the chrome browser from the cypress window.
6. It's not showing the recently searched word. It's showing the last searched word

### Desired behavior

It should show the recently searched word

### Test code to reproduce

https://user-images.githubusercontent.com/102032328/205221110-0abf318b-d91a-4563-9e13-ddf4ee064428.mp4

### Cypress Version

11.2.0

### Node version

16.17.0

### Operating System

Windows 11

**Comment by lmiller1990** [comment]
I have noticed this happening too, only sometimes, though.

**Comment by mohanbabu-zumen** [comment]
> I have noticed this happening too, only sometimes, though.

Can you consider this to fix?

**Comment by lmiller1990** [comment]
Yes, I'll route it to the team responsible for this part of the application to get it investigated. Does this always happen to you, or just sometimes?

**Comment by mohanbabu-zumen** [comment]
> Yes, I'll route it to the team responsible for this part of the application to get it investigated. Does this always happen to you, or just sometimes?

Thanks for the response @lmiller1990

**Comment by mohanbabu-zumen** [comment]
> just sometimes?

It always happens to me.

**Comment by marktnoonan** [comment]
@mohanbabu-zumen, do you have this problem in 11.1.0 or did it start in 11.2.0? I see where some code changes in 11.2.0 might be related to this, if you don't mind it would be good if you can confirm.

**Comment by mohanbabu-zumen** [comment]
> @mohanbabu-zumen, do you have this problem in 11.1.0 or did it start in 11.2.0? I see where some code changes in 11.2.0 might be related to this, if you don't mind it would be good if you can confirm.

I am facing this issue since 11.2.0
