### ISSUE TITLE
My company blocks chrome extensions

### ISSUE THREAD

**Issue by benmonro** [cypress-io/cypress#2494]
### Is this a Feature or Bug?
both maybe?

I'm unable to launch cypress because my company blocks chrome extensions. any workarounds?  If not, can you add support for cypress for users like me? :)

**Comment by jennifer-shehane** [comment]
Hey @benmonro, are you aware of the mechanism your company is using to block chrome extensions? What happens when you try to launch Cypress now? What do you see?

**Comment by benmonro** [comment]
hi @jennifer-shehane, yeah I believe we're using the chrome enterprise policies. 
 https://support.google.com/chrome/a/answer/7517624

Since the cypress extension isn't in the chrome marketplace there's no way for me to get it approved /whitelisted that I know of.  any guidance would be much appreciated.

**Comment by benmonro** [comment]
I can't seem to upload a screenshot (company policy again I think - I'm new here).

What i see is browser with all my whitelisted extensions and a page that says:

```
Whoops, we can't run your tests.

This browser was not launched through Cypress. Tests cannot run.

 Why am I seeing this message?
```

**Comment by jennifer-shehane** [comment]
The only thing I've ever seen remotely related to chrome extensions and permissions was this comment. Not sure it it's relevant though https://github.com/cypress-io/cypress/issues/672#issuecomment-338104225

**Comment by benmonro** [comment]
Yeah the problem is it doesn't even get to the point where the extension is
installed so I can't see it in the settings.

**Comment by benmonro** [comment]
electron does work!  we were also able to get it working with SRWare Iron which uses chromium under the hood. Still it'd be nice to be able to run tests in chrome directly w/out having to use an extension if possible.

**Comment by Bkucera** [comment]
@benmonro that's a good idea! We may make the chrome extension optional, as we have already had to engineer that for headless chrome, which doesn't support extensions

**Comment by jennifer-shehane** [comment]
The code for this is done in [cypress-io/cypress#3674](https://github.com/cypress-io/cypress/pull/3674), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
