### ISSUE TITLE
Cypress result video is null when test is successful

### ISSUE THREAD

**Issue by tommy0831** [cypress-io/cypress#24958]
### Current behavior

Cypress.run result object:

```js
{
  "stats": {
    "suites": 1,
    "tests": 1,
    "passes": 1,
    "pending": 0,
    "skipped": 0,
    "failures": 0,
    "duration": 30222,
    "startedAt": "2022-12-04T04:28:53.803Z",
    "endedAt": "2022-12-04T04:29:24.025Z"
  },
  "reporter": "cypress-multi-reporters",
  "reporterStats": {
    "suites": 1,
    "tests": 1,
    "passes": 1,
    "pending": 0,
    "failures": 0,
    "start": "2022-12-04T04:28:53.809Z",
    "end": "2022-12-04T04:29:24.062Z",
    "duration": 30253,
    "testsRegistered": 1,
    "passPercent": 100,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "hooks": [

  ],
  "tests": [
    {
      "title": [
        "Example",
      ],
      "state": "passed",
      "displayError": null,
      "attempts": [
        {
          "state": "passed",
          "error": null,
          "videoTimestamp": 6713,
          "duration": 30175,
          "startedAt": "2022-12-04T04:28:53.831Z",
          "screenshots": [           
          ]
        }
      ]
    }
  ],
  "error": null,
  "video": null,
  "spec": {
    "fileExtension": ".ts",
...
  },
  "shouldUploadVideo": false
}`
```
### Desired behavior

This used to work. When running  the tests with video turned on, a video is recorded.  what we want to do is remove the video if the test passes to save space.

expected: video object should not be null even when the test passes if video is turned on

### Test code to reproduce

Run a test that passes with video turned on.  Below is the configuration we use,
```js
{
  headless: true,
  browser: process.env.CYPRESS_BROWSER,
  config: {
    reporter: "cypress-multi-reporters",
    reporterOptions: {
      configFile: "reporter-config.json",
    },
    video: process.env.CYPRESS_VIDEO === "true",
    numTestsKeptInMemory: 0,
  },
  env: {
    configFile: `${process.cwd()}/cypress.config.ts`,
  }
}
```

### Cypress Version

10.11

### Node version

v16.14.0

### Operating System

FROM cypress/browsers:node16.14.0-chrome99-ff97

**Comment by emilyrohrbough** [comment]
@tommy0831 Can you confirm that the video recording was successful for your run - regardless of the test pass/fail state? Sometimes if the video fails to record or process, this value can be null.

Also can you confirm which browser you are testing?

**Comment by chrisbreiding** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
