### ISSUE TITLE
Cypress Component Testing Errors after Angular 15 upgrade

### ISSUE THREAD

**Issue by donta** [cypress-io/cypress#24953]
### Current behavior

When I select component testing I get the following error...
![image](https://user-images.githubusercontent.com/13527297/205385194-ff1a0e55-2691-4502-922c-4a2c8ee502e1.png)

### Desired behavior

Take me to the list of browsers to select...

### Test code to reproduce

Never make it to a test .. fails on the config page in cypress.

### Cypress Version

11.2

### Node version

18.12.1

### Operating System

Win11

**Comment by Celtian** [comment]
Same for me:
```
Node: v16.18.1
Angular: 15.0.2
Cypress: 11.2.0
OS: Ubuntu 20.04 (inside WSL on Win 10)
```

**Comment by ZachJW34** [comment]
@donta Is this a fresh workspace? and like @Celtian are you using WSL? Providing a reproduction would be a great help.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by donta** [comment]
Ok, we were never able to get it to work so switched over to jest for
component testing.
