### ISSUE TITLE
Alias for future elements

### ISSUE THREAD

**Issue by dotherightthing** [cypress-io/cypress#2495]
I'm a front-end developer and just getting started with Cypress. Perhaps my technique is not correct, but I'm finding that use of aliases makes my tests much easier to read.

I'd love to put all my aliases at the top of the test, then use them as needed. But if I create an alias for an element that doesn't exist yet, an error will be generated when the alias is created.

I'm experimenting with different ways around this, including splitting tests and using long timeouts. I understand why this happens, but it would be nice if there was a flag for `cy.get` or an alternative method that could be used to store a complex selector for future use.

### Current behaviour:

```
cy.get('.some-element-that-doesn't-exist-yet > .with ~ .a-really [name="complex"] + .selector').as('element');
...
// element is created as a result of interactions
...
cy.get(@element).should('have.class', 'supported'); // cy error
```

### Desired behavior:

```
cy.get('.some-element-that-doesn't-exist-yet > .with ~ .a-really [name="complex"] + .selector').as('element');
...
// element is created as a result of interactions
...
cy.get(@element).should('have.class', 'supported'); // no cy error
```

### Versions

Cypress 3.1.0
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
MacOS Sierra 10.12.6

**Comment by jennifer-shehane** [comment]
We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Issues in our GitHub repo are reserved for potential bugs or feature requests. We want our team to spend all the time we have building a better product and hope you understand. ☺️
