### ISSUE TITLE
Cypress.log to display line break

### ISSUE THREAD

**Issue by nilgaar** [cypress-io/cypress#24964]
### Current behavior

When logging some text with Cypress.log, the "\n" does not break line for message (nor for displayName), just leaves a space.

```
Cypress.log({
              name: "",
              displayName: "",
              message: "I'm the first line!" + "\n" + "I'm the second line",

```

output
`
<span class="command-message-text">I'm the first line!
I'm the second line</span>
`

<img width="397" alt="image" src="https://user-images.githubusercontent.com/73447234/205551358-f33cd00e-f22c-4e3f-bd36-9519632c8e3d.png">

### Desired behavior

Would be nice that the log view can display the break lines correctly when a string contains "\n"

### Test code to reproduce

```
Cypress.log({
              name: "",
              displayName: "",
              message: "I'm the first line!" + "\n" + "I'm the second line",
            });
```

### Cypress Version

11.2.0

### Node version

16.17.0

### Operating System

13.0.1

**Comment by emilyrohrbough** [comment]
@nilgaar This seems like a reasonable request. This likely isn't something we will be able to prioritize anytime soon. Are you interested in contributing this change?

**Comment by nilgaar** [comment]
absolutely @emilyrohrbough, I can work in a PR for this
