### ISSUE TITLE
@cypress/grep internal read.me is correct - NPM references deprecated cypress-grep package

### ISSUE THREAD

**Issue by modern-sapien** [cypress-io/cypress#24967]
### Current behavior

When searching for cypress grep online you're correctly pointed to [@cypress/grep npm package](https://www.npmjs.com/package/@cypress/grep), but the readme is referencing the deprecated cypress-grep plugin that is no longer maintained specifically how to import in the support file & setup in the config file.  

### Desired behavior

The current npm package should be updated to reflect what is in the Cypress @cypress/grep readme. 

### Test code to reproduce

none

### Cypress Version

11.2.0

### Node version

16

### Operating System

windows 11

### Debug Logs

```shell
none
```

### Other

none

**Comment by jennifer-shehane** [comment]
https://github.com/cypress-io/cypress/tree/develop/npm/grep#support-file This is different
