### ISSUE TITLE
Assertions are incorrectly applying markdown and adding asterisks

### ISSUE THREAD

**Issue by JamShady** [cypress-io/cypress#24960]
### Current behavior

Given the current basic code:
```javascript
        cy.get('input')
            .should('have.value', initial)

            .clear()
            .type(update)
            .then(() => {
                expect(field.value()).to.equal(update)
            })
```
The following output is generated:
![image](https://user-images.githubusercontent.com/167395/205506920-62fce744-4245-430d-9988-c5be72032eb9.png)

As you can see, the required value is displayed with asterisks, which I assume is a formatting error and it's actually supposed to make the value bold.

### Desired behavior

Presumably the required value should show up as bold, rather than surrounded by asterisks.

### Test code to reproduce

```
expect('foo').to.equal('bar')
```
should generate
![image](https://user-images.githubusercontent.com/167395/205507057-587ff2bc-0a56-408e-b01f-95f296ea3aaa.png)

### Cypress Version

11.2

### Node version

19

### Operating System

Win 11

**Comment by jennifer-shehane** [comment]
### Current behavior

Assertions are incorrectly applying markdown and adding asterisks.
![image (6)](https://github.com/cypress-io/cypress/assets/1271364/3b4f71b9-0ca1-4711-84fa-54c72ddf43d9)


### Desired behavior

Shouldn't show asterisks, instead it should bold the text.

### Test code to reproduce

```js
it("test", () => {
    expect("smooth").to.eq("smooth")
});
```

### Cypress Version

13.6.0

**Comment by jennifer-shehane** [comment]
There was a comment in the other thread that this may be a regression from https://github.com/cypress-io/cypress/pull/22537
