### ISSUE TITLE
The specs search term keeps coming back after clearing it

### ISSUE THREAD

**Issue by dustin-rcg** [cypress-io/cypress#24979]
### Current behavior

<img width="1430" alt="Screen Shot 2022-12-05 at 2 41 34 PM" src="https://user-images.githubusercontent.com/12749340/205728014-a0bbe128-13bd-487f-987e-a3d579336b1c.png">

Whenever I open cypress, the old search term is populated in the specs search. When I clear it, the change is not saved.

Also when I run a spec, and then click the button to go back to specs, the old search term is populated again. 
<img width="63" alt="Screen Shot 2022-12-05 at 2 43 11 PM" src="https://user-images.githubusercontent.com/12749340/205728270-21fa456b-b2db-4bfb-9836-8c2dc600a054.png">

### Desired behavior

Remember that the spec search is cleared.

### Test code to reproduce

No code, just the cypress UI

### Cypress Version

11.2.0

### Node version

16.17.0

### Operating System

macOs 12.6 (21G115)

**Comment by lmiller1990** [comment]
Dup of https://github.com/cypress-io/cypress/issues/24936

Will get this fixed in the next release (should be mid Dec).
