### ISSUE TITLE
Devtools window size when undocked is super tiny / disappears 

### ISSUE THREAD

**Issue by nazar** [cypress-io/cypress#2497]
### Is this a Feature or Bug?

Bug

### Current behavior:

I've noticed this this morning after my Chrome updated to `Version 69.0.3497.100 (Official Build) (64-bit)`.

I was not able to open the dev tools window from the incognito Chrome browser which was managed by cypress. On closer inspection, the devtools window was opening but it was squeezed into the top left corner of the screen.

![screen shot 2018-09-20 at 12 54 33](https://user-images.githubusercontent.com/6967/45816781-9002ee80-bcd4-11e8-9e48-3c3e4aeaed9f.png)

This window can be resized (but it is fiddly) but the new window position are not saved and the same has to be done again when I re-open chrome dev tools. Note, this only occurs when devtools are configured to "Undock into separate window". 

### Desired behavior:

Chrome devtools should be visible when configured to "Undock into separate window" and previous undocked window position be (I hope) saved.

### Steps to reproduce:

1. open chrome inspector tools
2. in "Customize and control Devtools" hamburger menu, choose "Undock into separate window"
3. devtools are no longer visible
4. close chrome window and rerun a cypress test
5. open dev tools
6. devtools window edge is barely visible in the top left of the primary monitor as in the above screenshot.

### Versions

Cypress: 3.1.0
Chrome: 69.0.3497.100
OS: MacOS 10.12.6

**Comment by lyonsbp** [comment]
In case anyone else encounters the scenario where the devtools gets "stuck" invisible while undocked, you can use the following shortcut to re-dock.
`cmd+shift+D (mac)`
`Control+Shift+D (Windows)`

**Comment by nazar** [comment]
I think I stumbled onto a fix on macOS.

When the Cypress UI is running, from the menu select File -> View App Data. I had a few folders there from year or two ago. Remove all files/folders then restart the Cypress UI.

Chrome Dev tools now display correctly when undocked.

**Comment by nazar** [comment]
I jumped the gun on that one. Although the undocked chrome dev window shows correctly if I delete all files under "View App Data" then restart Cypress, the reported behaviour returns when cypress is subsequently closed and restarted.

**Comment by jennifer-shehane** [comment]
Oh my gosh, this has been happening to me! I thought it was just my computer from updating. 🙈

**Comment by DonSkokie** [comment]
> In case anyone else encounters the scenario where the devtools gets "stuck" invisible while undocked, you can use the following shortcut to re-dock.
> `cmd+shift+D (mac)`
> `Control+Shift+D (Windows)`

Thank you, this was driving me nuts!

**Comment by jennifer-shehane** [comment]
I don't have any leads on where this issue originates. Is happening on Chrome 69 -> Canary 73.

Can you all share the OS you are on experiencing this problem?

**Comment by nazar** [comment]
>Can you all share the OS you are on experiencing this problem?

Since Chrome 69.0.3497.100
OS: MacOS 10.12.6

**Comment by jennifer-shehane** [comment]
Mentioned from another thread here https://github.com/cypress-io/cypress/issues/3389#issue-408191497

>the only way I found is to completely remove the `~/Library/Application Support/Cypress/cy/` (completely, not only the `~/Library/Application Support/Cypress/cy/production/browsers/` folders), relaunch Cypress and everything works again. Obviously you lose every customisation of Chrome

I actually tried this, deleting everything possible and never did get the DevTools undocked back to a workable size.

**Comment by tzimmermann** [comment]
This issue is finally fixed for me on 

- Canary 76 (`Version 76.0.3797.0 (Official Build) canary (64-bit)`)
- Mac OS 10.14.5 (18F132)

but might be fixed as of Chrome v75 already according to https://bugs.chromium.org/p/chromium/issues/detail?id=783199

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by Andre-h76** [comment]
> In case anyone else encounters the scenario where the devtools gets "stuck" invisible while undocked, you can use the following shortcut to re-dock. `cmd+shift+D (mac)` `Control+Shift+D (Windows)`

Ok, it works (docks devtools back), but what if I still need to have devtools undocked?

**Comment by zsmithjc** [comment]
I'm running into the same issue as @Andre-h76. I can re-dock it using the previous solution, but when I undock again, it "disappears" again.

Edit: I believe when you undock it again, it might appear as a small window in the top right corner of the screen. Look real hard for it, it might blend in.
