### ISSUE TITLE
Quietly stub XHR requests

### ISSUE THREAD

**Issue by JustChapman** [cypress-io/cypress#24977]
### What would you like?

I would like to have the ability to intercept and QUIETLY stub requests/responses. Meaning, NOT have them show up in the spec runner column.

### Why is this needed?

I'm working with an app that uses a TON of external XHR requests. For those services that I'm not concerned with, I'd love for a way to intercept and filter them from being displayed in the spec runner column of the Cypress app. They take up a tremendous amount of space and are just noise. Screenshot attached as an example.

<img width="634" alt="Screen Shot 2022-12-05 at 11 09 22 AM" src="https://user-images.githubusercontent.com/38143581/205722402-77785d54-e079-46f4-a5ff-1cb81463720c.png">

### Other

Maybe create a filtered spec runner view?

**Comment by nagash77** [comment]
Hi @JustChapman , this problem will be resolved by this ticket - https://github.com/cypress-io/cypress/issues/9358.  Please follow along there for updates on its impending release in the near future.
