### ISSUE TITLE
@cypress/grep Does not work, every test is always run

### ISSUE THREAD

**Issue by GeorgeXCV** [cypress-io/cypress#24974]
### Current behavior

`npx cypress run --env grepTags=@smoke`   
Tags don't work at all, 100% of tests are always run in every spec file.

### Desired behavior

Only run tests with tags.

### Test code to reproduce

Test Suite with Tags:
```
describe('Test Suite', { tags: '@smoke' }, () => {
 
    it('Test 1', () => {
       cy.clickAccountButton()
    })
 
    it('Test 2', () => {
      cy.clickAccountButton()
   })
 })
```

cypress/support/index
```
import './commands/index.ts';
import registerCypressGrep from '@cypress/grep'
registerCypressGrep()
```
tsconfig.json:
```
{
    "compilerOptions": {
      "target": "es5",
      "lib": ["es5", "dom"],
      "types": ["cypress", "node", "@cypress/grep"],
      "resolveJsonModule": true
    },
    "include": ["**/*.ts"]
  }
```

### Cypress Version

11.2.0

### Node version

16.16.0

### Operating System

13.0.1

**Comment by Narretz** [comment]
I would expect all tests in your example to run. The tag is on the describe, so both tests inside the describe run.

**Comment by GeorgeXCV** [comment]
> I would expect all tests in your example to run. The tag is on the describe, so both tests inside the describe run.

Yes but every spec runs, regardless of tags.

**Comment by Narretz** [comment]
you mean all spec files run? But the tests inside should be skipped then. You can also filter them from running by using `grepFilterSpecs=true`

**Comment by GeorgeXCV** [comment]
> you mean all spec files run? But the tests inside should be skipped then. You can also filter them from running by using `grepFilterSpecs=true`

I'm aware how tags work, unless behaviour has changed since [this ](https://www.npmjs.com/package/cypress-grep) repo was depreciated. 

I have a test suite with a tag as seen in the original post, I run command with `grepTags`, only tagged test suite / tests should run, not everything in the project.

**Comment by GeorgeXCV** [comment]
Moving this code from `index.ts` to `e2e.ts` seems to have fixed it. I did have that code originally there though and had deliberately moved it when migrating the package, maybe Cypress upgrade played a part, not sure.
```
import * as registerCypressGrep from '@cypress/grep'
registerCypressGrep()
```
