### ISSUE TITLE
Technical brief for public CT API

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#24991]
### What would you like?

The CT team discussed defining a better public API for plugging into Cypress for third parties. This would mean:

- third parties can "embed" in the launchpad setup
- provide their own custom `component-index.html` and `mount`

We'd rework our code, so all our first party integrations use public APIs - we shouldn't have access to anything a third party cannot access. 

I've got a bunch of ideas on how this API might look - let's chat before we do the technical brief.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24991?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
https://github.com/cypress-io/engineering-documentation/pull/45
