### ISSUE TITLE
afterEach hook bug

### ISSUE THREAD

**Issue by rausanualex** [cypress-io/cypress#24995]
### Current behavior

When we run a suite of tests that include an afterEach hook at failed attempt the second attempt will run 2 times at the same time. 

### Desired behavior

If 1st attempt is failing at the second attempt should run the test 1 time.
<img width="132" alt="image" src="https://user-images.githubusercontent.com/105510012/205945189-e05b8675-e672-4b17-b7fb-d4136775f083.png">
<img width="130" alt="image" src="https://user-images.githubusercontent.com/105510012/205945294-2022bb14-a9bb-437d-b772-8fe3331ba7bb.png">

### Test code to reproduce

-

### Cypress Version

11.0.1

### Node version

19.0.1

### Operating System

mac

### Debug Logs

```shell
-
```

### Other

nop

**Comment by nagash77** [comment]
Hi @rausanualex , can you please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
