### ISSUE TITLE
Cypress browser luncher UI does not render all browser options panel with the same height

### ISSUE THREAD

**Issue by owen26** [cypress-io/cypress#24997]
### Current behavior

Small issue.

If users have Firefox Developer Edition installed, the card becomes taller than other cards. Could be nicer if they are the same height.

<img width="859" alt="Screenshot 2022-12-06 at 15 01 03" src="https://user-images.githubusercontent.com/385786/205947747-0a932281-ee98-4013-a66d-136f0efe1e72.png">

### Test code to reproduce

- Install Firefox Developer Edition
- Run cypress
- Observe the difference same as screenshot above

### Cypress Version

11.1.0

### Node version

16

### Operating System

macOS 12.6.1

**Comment by jennifer-shehane** [comment]
I believe this was fixed at some point. 
![Screenshot 2024-12-12 at 12 56 48 PM](https://github.com/user-attachments/assets/897a901f-3cfa-4626-a6b5-f80921c4686f)
