### ISSUE TITLE
Commands UI assert errors should clearly delineate integers from strings.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#25]
The ASSERT error (in red background) on the commands UI does not signify whether my value is a string or not. The AssertionError (in yellow background) more clearly defines my error (that the integer 25 does not equal "25").

**Example**
![screen shot 2015-04-20 at 11 57 25 am](https://cloud.githubusercontent.com/assets/1271364/7234411/edd38b90-e754-11e4-91ee-c9dda3f2b38c.png)

### To reproduce:

```js
it('test', () => {
  expect(25).to.eq('25')
})
```

**Comment by verheyenkoen** [comment]
Could this be a first-timers-only issue?
