### ISSUE TITLE
Mock http Backend

### ISSUE THREAD

**Issue by jdnichollsc** [cypress-io/cypress#250]
Hi guys,

Please, work in this feature to Cypress!

Check my example with Protractor! https://github.com/jdnichollsc/Game-of-Drones/blob/master/FrontEnd/tests/e2e-tests/mocked-backend.js

Regards, Nicholls

**Comment by brian-mann** [comment]
I'm not seeing anything new in your example that you can't already do in Cypress right now.

- https://on.cypress.io/guides/network-requests-xhr
- https://on.cypress.io/api/server
- https://on.cypress.io/api/route

Is there something more specific you wish to do?

**Comment by jdnichollsc** [comment]
Ohh sorry! Cypress is beautiful! 💯
