### ISSUE TITLE
Allow users to change spec path before it is created from component

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#25005]
### What would you like?

Currently when users create a spec from a component, we auto-generate a file name and path for them. There are some edge cases where this can lead to confusing experiences with specs being placed in an unexpected location or with a confusing spec name.

Before the spec file is created, we should show the "blank spec" modal with the path where we _would_ put the generated spec file and give the user the opportunity to change the path (as long as it conforms to the spec pattern) before proceeding with generating the spec file.

This screen already exists for generating blank specs, so we should be able to re-use the UI for this purpose.

![Screen Shot 2022-12-06 at 1 18 45 PM](https://user-images.githubusercontent.com/14275198/205990570-da0d6e3b-8b26-473d-bafa-53162d5d0142.png)

![Screen Shot 2022-12-06 at 1 18 56 PM](https://user-images.githubusercontent.com/14275198/205990585-b3840253-67e7-4318-908b-37dcfc2d81f0.png)

**Comment by astone123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25005?planning-poker) with Zenhub @amehta265 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Can't you already do this? What are the edge cases?

I just tried it out - you choose your component, then you can change the spec path to whatever you like. I don't understand the change - are we just swapping the order of the two steps?

**Comment by ZachJW34** [comment]
Do we always show the user-editable path after clicking on a component or only when an error occurs when generating a name?

**Comment by astone123** [comment]
@ZachJW34 i think the idea was to always show it
