### ISSUE TITLE
API latency issue causes tests fail

### ISSUE THREAD

**Issue by predictiveXu** [cypress-io/cypress#2500]
Not sure if cypress has the feature or not.

I am writing an integration test right now. And the tests use `post` API call in `before()` function. The API call is used to create a person. In test, I will use the person created in `before()` function. However, I can't search out this person sometimes because of API latency. In other words, the person's name is not in searching result page. Before using cypress, I was using a while loop and checked whether the searching page had the name. If not, it reloaded the page in the while loop until it found the name. But I don't think I can do it in cypress. I tried to use `cy.get('table').should($t => {do something(like reload) })`, but it didn't work since `$t` won't change after reload so I am stuck for this problem. 

The current solution for me is to `cy.wait(30000)` before searching the name. However, it still fails sometimes.  Is there anything suggestion to this issue? Thank you.

**Comment by jennifer-shehane** [comment]
I'd recommend checking out our guide on [conditional testing](https://on.cypress.io/conditional-testing#Element-existence)

I believe something like this would work for the exact situation you are trying to run, you'd have to set a number of time to run the check though so that it doesn't run forever. 

```js
it('test', function () {
  let count = 0;

  const findTable = () => {
    count +=1

    cy.visit(url)
    cy.get('body').then(($body) => {
      if ($body.find('table')) {
        cy.get('table') // whatever you wanted to do here
      } else {
        if (count > 3) return
        findTable()
      }
    })
  }

  findTable()
})
```
