### ISSUE TITLE
Typo in cypress runner viewport popper

### ISSUE THREAD

**Issue by AbrahamBrookes** [cypress-io/cypress#25018]
### Current behavior

![image](https://user-images.githubusercontent.com/8340776/206072652-4ca2225e-7dc5-4e4b-9de8-1ae7e4476735.png)

❤️ 

### Test code to reproduce

Open the cypress chrome runner and click the viewport size dropdown

### Cypress Version

10.3.0

### Node version

v17.8.0

### Operating System

Windows10

**Comment by Pashozator** [comment]
It's already fixed in newest version 12.0.1.

**Comment by marktnoonan** [comment]
Thanks for reporting this - I do believe it has been fixed somewhere in between 10.3.11. I'll close this issue for now but if you are able to reproduce this in the latest version of Cypress please comment and we can reopen.
