### ISSUE TITLE
Cypress 12.0.1 - contains(element,text) inside within fails

### ISSUE THREAD

**Issue by swannypp** [cypress-io/cypress#25019]
### Current behavior

I find I often target content via an element and it's text inside a container with this pattern. but it fails in cypress 12.0.1
```
cy.get('form').within(() => {
    cy.contains('label', text).parent().find('input').type('some text')
});
```

<img width="1595" alt="image" src="https://user-images.githubusercontent.com/92280460/206088110-d043e064-1567-4248-a87d-8e1db0ea4931.png">

### Desired behavior

Targeting content with a `cy.contains(element, 'text')` should work inside a within, as it has done with previous Cypress versions and as indicated in the documentation.

### Test code to reproduce

```
describe('Within Test', () => {
    it('Should be able to target elements within a form', () => {
        cy.visit('https://www.demoblaze.com/');
        cy.contains('a', 'Log in').click();

        cy.get('#logInModal').within(() => {
            cy.get('form').should('be.visible');
            cy.get('label').should('be.visible');

            cy.get('form').within(() => {
                // these work
                cy.contains('Username:').should('be.visible');
                cy.contains('Username').parent().should('be.visible');
                cy.get('input').first().should('be.visible');

                // this doesn't
                cy.contains('label', 'Username').parent().find('input').type('aUsername')
            })
        })
    });
})
```

### Cypress Version

12.0.1

### Node version

v14.18.0

### Operating System

macOS 12.6

### Other

This fault is able to be replicated easily with the given test code supplied.

**Comment by BlueWinds** [comment]
We have some regressions around `.contains()` in Cy12 - looking into this now. Thank you for the clear repro!

**Comment by BlueWinds** [comment]
Looks like we have a regression around `.contains()`  and `<form>` elements in particular (in addition to the other regression over at https://github.com/cypress-io/cypress/issues/25025). Fix in the linked PR; we're planning to get 12.0.2 out in the next day or two containing several quick fixes.
