### ISSUE TITLE
Cypress 12.0.0 | 12.0.1 - the chained cy.next() command is not being recognized by Cypress

### ISSUE THREAD

**Issue by Hayk-S** [cypress-io/cypress#25028]
### Current behavior

Cypress throws AssertionError on `.next()` command and obviously doesn't recognize it.

![image](https://user-images.githubusercontent.com/48865647/206184610-fca81d60-8685-40e1-9cae-d09b36ec2916.png)

### Desired behavior

Before Cypress 12.0.0  (11.2.0), the exact same command was working perfectly fine and Cypress was able to navigate to the next() element of the DOM

### Test code to reproduce

```js
  this.getServiceRowColumns(name)
    .contains(exactName)
    .nextAll()
    .contains(protocol)
    .should('be.visible')
    .then((currentEl) => {
      cy.wrap(currentEl).parent().next().contains(host).should('be.visible')
    })
```

Cypress fails at `.next()` with the following error:

```
Timed out retrying after 10000ms: Expected to find element: next, but never found it. Queried from:

> <td> -> .parent()
```

### Cypress Version

12.0.0 and 12.0.1

### Node version

v16.17.0

### Operating System

macOS Monterey 12.6

**Comment by BlueWinds** [comment]
https://deploy-preview-4835--cypress-docs.netlify.app/guides/core-concepts/retry-ability#Actions-should-be-at-the-end-of-chains-not-the-middle explains why this test will run into problems.

Consider rewriting your test like

```
  this.getServiceRowColumns(name)
    .contains(exactName)
    .nextAll()
    .contains(protocol)
    .should('be.visible')
    .as('row')

cy.get('@row').parent().next().contains(host).should('be.visible')
```

With that said, when reporting issues, here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/). I can't run the pasted code locally - it doesn't contain a pointer to the page you're testing or to the custom command you're using. Basically, I can't run it myself to be 100% sure what's going on.

**Comment by Hayk-S** [comment]
I will try to provide a reproducible example but the suggested workaround didn't work, I get the same error.

**Comment by Hayk-S** [comment]
Alright, I have tried a couple of times and could make this work by skipping the `parent()` part which comes from how in the latest version Cypress differentiates between types of actions/queries/assertions and retrials.

**Comment by Hayk-S** [comment]
FYI, the problem was not in `.next()`, the regression was in `contains()` and after [Cypress 12.0.2 fixes](https://docs.cypress.io/guides/references/changelog#12-0-2), the exact same code works now as expected.

**Comment by BlueWinds** [comment]
Glad you figured it out! We definitely did have some issues in 12.0.0, and thanks for your patience as we worked through them. :)
