### ISSUE TITLE
Restarting a failing parallelised test job results in restarting all tests in one single job

### ISSUE THREAD

**Issue by joelgrimberg** [cypress-io/cypress#25021]
### Current behavior

All my Cypress tests are spread on 10 Gitlab runners through the epic Cypress Parallelisation feature, resulting in a spread of all my tests over 10 jobs.

When one job fails, my pipeline fails. which is 👍 .
When I restart my failed job, the entire testsuite will run in the restarted job,
instead of only the tests that where designated for that failed job

### Desired behavior

When a failing parallelised job is being restarted (rerun),
run only the tests that have been designated to that job.

### Test code to reproduce

I will setup a repo and then add it to this ticket

### Cypress Version

all

### Node version

all

### Operating System

Cypress image (10, 11, 12)

**Comment by ThomasTrepanier** [comment]
This is a major issue for us too, preventing us from adopting Cypress Cloud fully. This issue has been tackled in `cypress-split`, and we currently use that for our parallelization. It would hurt to lose that feature by moving to Cy Cloud.

**Comment by jennifer-shehane** [comment]
Thanks for the feedback. We've received a lot of feedback around this and it's on our radar. A lot of changes will need to be done to accommodate it. I'll close this issue since it's being tracked on the Cloud and this repo is for App issues.
