### ISSUE TITLE
Enable to click to  input number -webkit-inner-spin-button 

### ISSUE THREAD

**Issue by MehmetCanBOZ** [cypress-io/cypress#25022]
### What would you like?

I want to be able to click the input number -webkit-inner-spin-button and -webkit-inner-outer-button to change the value of the input.

### Why is this needed?

I design an input number component that only changes with the -webkit-inner-spin-button and -webkit-inner-outer-button between the min and max value which was given the input, if the user types a value with the keyboard, I  control with custom handler function and give an error, not the change the value of the input. 
But the problem is I can not test it, because I can not select -webkit-inner-spin-button and -webkit-inner-outer-button  and click it.

### Other

[Example React Code](https://codesandbox.io/s/input-number-spin-button-l9mi4?file=/src/App.js)

**Comment by BlueWinds** [comment]
Consider using `cy.trigger()` with the [`beforeinput`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event) and [`input`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) events - they're the  ones that fire when a user clicks on the up and down arrows. React is probably listening to one of these, though I'm not sure which one.

I examined the native events by setting a listener on all events, and then scrolling the number manually.

```
    cy.$$('body')[0].innerHTML = `<input
      type="number"
      value="3"
      min="1"
      max="5"
      aria-label="item-quantity"
    />`

    const inpun = cy.$$('input')[0]

    Object.keys(window).forEach(key => {
        if (/^on/.test(key)) {
            input.addEventListener(key.slice(2), event => {
                console.log(key, event);
            });
        }
    });
```

![image](https://user-images.githubusercontent.com/3003404/206523798-41524bb3-0c77-4403-9599-9046d1d960b2.png)

**Comment by MehmetCanBOZ** [comment]
I used a couple of commands just like the bottom, but it is not worked. Can you give an example about it?
`cy.get('input').trigger('beforeinput').trigger('mouseup'); 
  cy.get('input').trigger('beforeinput').trigger('mousemove').trigger('mouseup');
  cy.get('input') .trigger('beforeinput').scrollIntoView({offset: { top: 150, left: 0 } });
`

**Comment by BlueWinds** [comment]
`cy.get('input').type(6, { force: true })` is probably your best bet. Users may not be able to type in your component, but Cypress still can with `{force: true}` enabled.

Definitely right that it's not simple or straightforward to trigger the events directly though. This led me down quite a rabbit hole learning about react internals! In the end, I put together this test which seems to work:

```
    cy.get('input').then((i) => {
      const input = i[0]
      var nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set;
      nativeInputValueSetter.call(input, '6');

      var ev2 = new Event('input', { bubbles: true});
      input.dispatchEvent(ev2);

      i.val(6)
    })
```

https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js was what finally helped me figure this out. Basically, react overrides the default setter, leading to us needing rather messy code to trigger the react onChange handler.

You still probably want something like `cy.get('input').type(6, { force: true })`, but if you absolutely must bypass the "type" step, then the above code should work.

**Comment by MehmetCanBOZ** [comment]
Thanks, the "type" step does not work but the other code block work.
