### ISSUE TITLE
@cypress/schematic: Upgrade @schematics/angular to 15

### ISSUE THREAD

**Issue by feodorar** [cypress-io/cypress#25024]
### What would you like?

Please upgrade @schematics/angular to 15. 
Currently, after upgrading my app to Angular 15, the @cypress/schematic package overrides Angular schematics with version 14 leading to [this issue](https://github.com/angular/angular-cli/issues/24352).

**Comment by lmiller1990** [comment]
@feodorar sorry about the slow action here - getting a grip on the backlog, we will fix this during our next sprint, which is start late feb, finish early march.

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25024?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by jordanpowell88** [comment]
@feodorar Can you provide an example repo? I'm having trouble trying to replicate this issue

**Comment by lmiller1990** [comment]
Happy to re-open once we've got a reproduction - until then, no actionable info, so I need to close this one out.
