### ISSUE TITLE
cy.contains with selector and cy.get as a subject stopped working on v12

### ISSUE THREAD

**Issue by KrzGruszcz** [cypress-io/cypress#25025]
### Current behavior

```cy.get(<parent_locator>).contains(<child_locator>, <text>)``` was finding elements, but with Cypress v12.0.1 is not finding anything:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/86097671/206171105-f2dda293-b68a-4507-9cb7-8a12d6cd742e.png">

The changelog was not mentioning anything about cy.contains updates.

### Desired behavior

should work like before changes

### Test code to reproduce

```js
describe("cy.contains bug Cypress v12.0.1", () => {
  beforeEach(() => {
    cy.visit("https://example.cypress.io");
  });

  it("passes", () => {
    cy.get(".container").eq(2).contains("p", "Commands ");
  });

  it("passes", () => {
    cy.get(".container").contains("Commands ");
  });

  it("fails", () => {
    cy.get(".container").contains("p", "Commands ");
  });
});
```

### Cypress Version

12.0.1

### Node version

v16.18.0

### Operating System

macOS 13.0.1

**Comment by Develliot** [comment]
I'm also seeing issues with contains, especially inside within or when text is more than one level deep

**Comment by BlueWinds** [comment]
Oh dear. Looking into this now; Somehow it looks like we didn't have a test case covering this case *at all* in our own suite.

**Comment by BlueWinds** [comment]
Linked a PR to address this. Basically, the new version of `.contains()` was only looking inside the first subject element - if there were multiple, everything past the first was being ignored.

Thank you for the simple repro, made this a lot easier to track down and fix quickly. Expect a patch release today or tomorrow.
