### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by evoytenkoapps** [cypress-io/cypress#25029]
### What would you like?

how to enable debbugging mode, like `DEBUG=cypress:*`
like here https://docs.cypress.io/guides/references/troubleshooting#To-clear-App-Data

### Why is this needed?

to debugging cypress work, for exmaple find errors like
`cypress:network:agent Creating proxied request for http://localhost:8080/ through http://proxy.some.ru:8080/ +0ms`

**Comment by nagash77** [comment]
Hi @evoytenkoapps , I am sorry to hear you are having problems using Cypress.  Can you describe what issue you are encountering a bit more please?  If you are encountering an error please attach it to the ticket and I can reopen this issue.

If this is a question on how to use Cypress I would also suggest you check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.
