### ISSUE TITLE
Cucumber does not work cypress 12 or higher 

### ISSUE THREAD

**Issue by jaime1702** [cypress-io/cypress#25027]
### Current behavior

cucumber stopped working in cypress 12

![image](https://user-images.githubusercontent.com/61567212/206184579-8d772d60-7ccd-4c55-94ef-67c3d805edfb.png)

### Desired behavior

works normally, just like it did in cypress 11 or lower

### Test code to reproduce

-------------------------------------
Lib:     "cypress-cucumber-preprocessor": "^4.3.1",
-------------------------------------
package
,
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/e2e/",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".json"
    }

-------------------------------------------------------
index.js

/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */
// eslint-disable-next-line no-unused-vars
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
};

const cucumber = require('cypress-cucumber-preprocessor').default;
// eslint-disable-next-line no-unused-vars
module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
};

### Cypress Version

12.0.1

### Node version

v16.15.1

### Operating System

Ubuntu 22.04.1 LTS

**Comment by gurudattgd04** [comment]
This isn't from Cucumber Preprocessor. If you see the exception, its thrown from plugin cypress-if

**Comment by jaime1702** [comment]
sorry
