### ISSUE TITLE
I cannot fix the Cypress.Cookies.defaults() was removed in cypress version 12.0.0 error

### ISSUE THREAD

**Issue by adrian-maciuc** [cypress-io/cypress#25030]
### Current behavior

![Screenshot 2022-12-07 at 16 41 12](https://user-images.githubusercontent.com/106149016/206209458-2b41920c-cac3-4e1a-ba59-48ee8c16ef1e.png)

Please provide some ideas on where to look and try to fix this

Here are the things I tried:
1. I followed the https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-12-0
2. I tried to look for anything related to cookies, sessions
3. I looked at the config file. I commented out experimentalSessionAndOrigin: true
4. I commented out the only overwrite custom command we have for cy.visit

### Desired behavior

Have it work like in previous version.

### Test code to reproduce

None of the tests run

### Cypress Version

12.0.1

### Node version

v16.15.0

### Operating System

macOS 13.0.1

**Comment by adrian-maciuc** [comment]
Nevermind, I've found out eventually. We are doing programmatic login using `cypress-nextjs-auth0` library, and this one uses the `Cypress.Cookies.preserveOnce` and `Cypress.Cookies.defaults` .

**Comment by emilyrohrbough** [comment]
@adrian-maciuc Thank you for reporting! I am sorry this is causing you issues. I made a note on the plugin repository: https://github.com/sir-dunxalot/cypress-nextjs-auth0/issues/59.

Since this required fixed on their end, I'm going to go ahead and close this.

**Comment by theodiablo** [comment]
@adrian-maciuc, did you find any solution for this issue?

**Comment by adrian-maciuc** [comment]
@theodiablo , we were looking into adapting the library to fit our needs. First attempts didn't go well. Still working on.

**Comment by harshbakori** [comment]
any updates on this?

**Comment by theodiablo** [comment]
> any updates on this?

I guess we'll have to stop using `cypress-nextjs-auth0` library in order to update to Cypress 12+.

Does anyone have any other suggestions to handle Auth0 authentication nicely from Cypress 12?

**Comment by adrian-maciuc** [comment]
Our company took the decision to stop using `cypress-nextjs-auth0` . No alternative found yet.

**Comment by nagash77** [comment]
@theodiablo have you read through our guide on using Auth0 [here](https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication)?

**Comment by theodiablo** [comment]
> @theodiablo have you read through our guide on using Auth0 [here](https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication)?

Thanks @nagash77, that's a great doc I totally missed!
This will be just fine 🙏
