### ISSUE TITLE
Add --forbid-only and --forbid-pending options

### ISSUE THREAD

**Issue by irfancharania** [cypress-io/cypress#2503]
Is there any chance of exposing the "--forbid-only" and "--forbid-pending" Mocha flags in Cypress CLI?
mochajs/mocha#2696

Looking for a way to easily identify/prevent accidental commits of tests marked as "only" or "skip"

**Comment by bahmutov** [comment]
We use this little helper to detect `.only` in the spec files https://github.com/bahmutov/stop-only and maybe you can add ".skip" detection there?

**Comment by irfancharania** [comment]
Found another workaround: 

The "mocha-avoid-only" rule in this tslint ruleset solves the issue:
https://github.com/Microsoft/tslint-microsoft-contrib

**Comment by Floriferous** [comment]
What is preventing cypress from using the native `--forbid-only` flag in mocha? Would it work now with v4?

It'd be great to use them directly instead of using another library
