### ISSUE TITLE
ERROR: Transforming const to the configured target environment ("es5") is not supported yet

### ISSUE THREAD

**Issue by ZampaglioneGaston** [cypress-io/cypress#25031]
### What would you like?

Hi! We've been trying to get cucumber to work on cypress >11 for some time already, and we are getting always the same result. Are es5 going to be supported any time soon?
![cy error](https://user-images.githubusercontent.com/83976674/206226241-76c81c7b-35b6-4a78-9063-72c489d88bbd.JPG)

### Why is this needed?

A lot of people use cucumber when testing, is kind of an standard if you want to do things the correct way.

### Other

Cypress version: "cypress": "^12.0.1",
Preprocessor version: "@badeball/cypress-cucumber-preprocessor": "^14.0.0",
Node version: "version": "19.2.0",

**Comment by mike-plummer** [comment]
Hi @ZampaglioneGaston , thanks for opening an issue. As described, the issue you're encountering appears to be a [limitation of ESBuild](https://github.com/evanw/esbuild/issues/1380) - ES5 is relatively old at this point and [ESBuild does not support transpiling down to that level for many newer JS features](https://esbuild.github.io/content-types/#es5). Are you attempting to force ES5 compatibility on the ESBuild process via the `target` parameter? If so you may need to see about bumping that up to ES2015+, or using an alternative bundler.

If you don't think that is the issue you're encountering I'd be happy to dig in a bit further. Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by ZampaglioneGaston** [comment]
@mike-plummer! Thank you for your answer. Gonna be honest, wasn't expecting one🤣. I'll walkthrough all the documentation you left me, I think that after reading some I might have an idea how to make a workaround!

**Comment by ZampaglioneGaston** [comment]
Back at you! It seems that the `import createBundler = require("@bahmutov/cypress-esbuild-preprocessor")` was the problem. 
We where using https://github.com/badeball/cypress-cucumber-preprocessor. After getting back to https://www.npmjs.com/package/cypress-cucumber-preprocessor, all is working correctly. Thank you for your answer, I gave me the lead I needed!

**Comment by mike-plummer** [comment]
Glad to hear you got your issue resolved @ZampaglioneGaston !
