### ISSUE TITLE
Undocked chrome dev tools disappears

### ISSUE THREAD

**Issue by Francis-Moreau-adsk** [cypress-io/cypress#2504]
### Current behavior:
Undocked dev tool disappears. 

### Desired behavior:
Undocked dev tool window should be visible

Note: If the dev tool window still shows,  try closing it and reopening a new one. 

### Steps to reproduce:
-Open the Cypress test launcher
-run a test (using Chrome 69)
-Open the chrome dev tools from the nested browser in cypress runner (... more tools- >  developper tools)
- Undock the dev tool window
![undock](https://user-images.githubusercontent.com/15613768/45899346-8cda3200-bdaa-11e8-975b-75707b5e7b5e.png)

Workaround: 
Re dock the window using the shortcut keys (cmd+shift+D) to make it appear once more. 

### Versions
Cypress Version 3.1.0 (3.1.0)
Chrome 69
Mac 10.13.4

**Comment by Francis-Moreau-adsk** [comment]
youps 
looks like a dup of 
https://github.com/cypress-io/cypress/issues/2497

**Comment by Bkucera** [comment]
Hi @Francis-Moreau-adsk, I'm closing this in favor of #2497

**Comment by edelgado** [comment]
@Francis-Moreau-adsk thanks for the workaround! I just ran into this issue as well.

**Comment by JesusLopezCh** [comment]
thanks!.. couldn't find a way to bring it back

**Comment by nahumzs** [comment]
Posting workaround from the question here to make it more prominent:

> Workaround:
> Re dock the window using the shortcut keys (cmd+shift+D) to make it appear once more.
