### ISSUE TITLE
Cypress memory error for V12.0.1 

### ISSUE THREAD

**Issue by ryanborhoo** [cypress-io/cypress#25042]
### Current behavior

Upgrading Cypress from V9.7.0 to V12.0.1, and Cypress crashed in CI env with following errors. 

```
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

```

### Desired behavior

Test run should pass, because there is no test code changes before and after Cypress upgrade.  

### Test code to reproduce

Cann't share the tests in public repo

### Cypress Version

12.0.1

### Node version

16.5

### Operating System

ubuntu-2004:2022.07.1

### Debug Logs

```shell
Cann't share the debug log in public repo
```

### Other

The same upgrade for V10.11.0 did not running into this issue.

**Comment by nagash77** [comment]
Hi @ryanborhoo , Im sorry you are having issues running Cypress.  This issue is already being tracked in [this issue](https://github.com/cypress-io/cypress/issues/23391).  I am going to close this issue as a duplicate.  Please be sure to follow the linked tickets for updates.  The team is currently investigating.
