### ISSUE TITLE
Introducing Vitest for Unit Testing in App and Frontend Shared

### ISSUE THREAD

**Issue by amehta265** [cypress-io/cypress#25043]
As the Cypress app gets more complex it becomes more important to create tests that will check specific sections of code such as functions and complicated classes. 
The current approach for Unit testing is to create "Example" Vue applications that use specific sections of code and running component tests on the application e.g.[here](https://github.com/cypress-io/cypress/blob/develop/packages/frontend-shared/src/composables/examples/UseMarkdownExample.cy.tsx) and [here](https://github.com/cypress-io/cypress/blob/0e457b8235458bde22bb5eb0118a2cca259f85f1/packages/app/src/runner/selector-playground/SelectorPlayground.cy.tsx#L55)

Using Vitest would allow for a quicker development cycle where we can properly test sections of code.

**Comment by lmiller1990** [comment]
I tried adding this, it's a bit weird. The latest Vitest needs a newer version of esbuild than we've got. I bumped Vite to 3.2.5 (latest) but 2 tests are failing https://app.circleci.com/pipelines/github/cypress-io/cypress?branch=lmiller%2Fupdate-vite-and-reload-module-api

For some reason bumping Vite causes the reactivity between App and Reporter to not work as expected. I have no idea why, but if we want to use Vitest, we will need to update Vite. We need to update Vite anyway. I tried debugging but I'm not sure why this happens, I suspect esbuild bundles *slightly* differently. 

I hope we can start moving to Vitest in general - mocha's watch mode never seems to work well for me.

**Comment by lmiller1990** [comment]
Looks like Vite 4 fixed whatever issue I was having https://github.com/cypress-io/cypress/pull/25101

Once https://github.com/cypress-io/cypress/pull/25101 is merged, I think we should be able to add Vitest, too.

**Comment by lmiller1990** [comment]
I thought this was a good idea, but now I suspect we should probably just stick with Mocha, which we are using in the rest of the code base. It's watch mode doesn't seem to work well, but it's probably better to be consistent at this point than have half the code base on Mocha and the rest on Vitest.
