### ISSUE TITLE
Define test suites to be skipped inside config file.

### ISSUE THREAD

**Issue by ItsWasteD** [cypress-io/cypress#25055]
### What would you like?

I'd like to be able to define the test suites I want to skip (normally with `describe.skip`) inside the config file.

### Why is this needed?

So that I can skip the test for one environment but dont skip it in the other one. At the moment I only have the possibility to use the `exludeSpecPattern` option but if I use this option, the test suites is not visible in the list at all. I would like it to be visible but shown as skipped.

### Other

I'm sorry if this is already possible but I didn't find a way to do that yet.

**Comment by emilyrohrbough** [comment]
@ItsWasteD Can you share what type of environment checks you are trying to use to determine if a test should be ran or not?

We currently support skipping by browser using this syntax:
```js
describe('suite', { browser: 'chrome' }, () => {}) // only run for chrome
describe('suite', { browser: '!chrome' }, () => {}) // any browser but chrome

it('test', { browser: 'chrome' }, () => {})
it('test', { browser: '!chrome' }, () => {})
```

Alternatively,  you can also a test skip-inline using mocha's build in `this.skip()`:
```js
it('test, function () {
  if (Cypress.env('ENV') !== desiredEnv) {
    this.skip()
  }
  ...
})
```

**Comment by ItsWasteD** [comment]
Hello @emilyrohrbough I wasn't aware that I can just use `this.skip()` but I think that should work for me thank you very much!

**Comment by ItsWasteD** [comment]
Is it right that I can't use `this.skip()` for the whole suite? I'm trying to use it right after the `describe` block:

```
describe("TESTING-365 ...", () => {

    //Conditional skip
    if(["DEVE","INTE"].includes(Cypress.env("name"))) {
        this.skip()
    }
```

**Comment by nagash77** [comment]
Hi @ItsWasteD 

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress). I am going to close this issue since it is not related to a bug or feature request.

**Comment by ItsWasteD** [comment]
I got it to work like this:

```
(Cypress.env("name") == "TEST" ? describe.skip : describe)(
	"DMSTESTING-152 - Customview & Appearances Startseite",
	() => {
```
