### ISSUE TITLE
Improvement: When we double click the wrapped value, It's selected the whole word including wrap

### ISSUE THREAD

**Issue by mohanbabu-zumen** [cypress-io/cypress#25054]
### Current behavior

**It might be an improvement.**

While we are wrapping any value, It should log in cypress logs left side.

If we double-click the wrapped value, "wrap" also selected. 

See the attached video for more reference. 

### Desired behavior

It should select the value only without wrap

### Test code to reproduce

https://user-images.githubusercontent.com/102032328/206394347-fb7c499e-0aa7-48f4-b1ad-af0cc638c9c1.mp4

### Cypress Version

11.2.0

### Node version

16.17.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
Since this has not gotten a lot of interest, we’ll close this as not planned.
