### ISSUE TITLE
Cypress not targeting error message element that is removed from the DOM too quickly

### ISSUE THREAD

**Issue by skekauoha** [cypress-io/cypress#2506]
### Current behavior:

In our app, we have an error message that shows in the UI for 3 seconds and then is removed from the dom after those 3 seconds have elapsed. I'm trying to use cypress to validate that the error message is visible using `cy.get('selector').should('be.visible');`.  However, I believe the error message is being removed from the DOM quicker than cypress can validate that it actually did show.  Is there a work around to validate this error message in cypress?

### Desired behavior:

I would like to test for an error message that is only visible for a short amount of time.

### Steps to reproduce:

1. create an event that adds an element to the dom.
2. set a timeout for the element to be removed from the dom after 3 seconds.
3. attempt to test that the element was visible during the 3 seconds it was in the dom.

### Versions

Cypress: 3.1.0
OS: MacOS High Sierra Version 10.13.6
Chrome: Electron 69

**Comment by chrisbreiding** [comment]
Your best bet is using [cy.clock()](https://docs.cypress.io/api/commands/clock.html) 
and [cy.tick()](https://docs.cypress.io/api/commands/tick.html) to control the timing mechanism of the element. I would guess your app uses `setTimeout` to remove the element after 3 seconds. With `cy.clock()`, you can 'stop time', assert the error message is there, tick time 3000ms, then assert it has properly disappeared.

**Comment by skekauoha** [comment]
@chrisbreiding Thank you for replying to my issue.  `cy.clock()` and `cy.tick()` worked exactly as you described for my use case.  I'll go ahead and close this issue.
