### ISSUE TITLE
Timed out retrying after 4000ms: The command was expected to run against origin {{AUTHENTIFICATIONSERVICE}} but the application is at origin {{MYWEBAPP}}.

### ISSUE THREAD

**Issue by oaktree4** [cypress-io/cypress#25060]
### Current behavior

Hello everyone! My webapp uses a thirdparty authentification service (SAP IAS). Im tryng to navigate to authorize successfully and navigate to my app to perform test actions. Although I keep on stumbling on the following error while running the spec:

Timed out retrying after 4000ms: The command was expected to run against origin {{AUTHENTIFICATIONSERVICE}} but the application is at origin {{MYWEBAPP}}. This commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.
11 |    cy.visit('{{MYWEBAPP}}');
  12 |   
> 13 |     cy.get('.classfromwebapp').click()
     |        ^
  14 |   })
  15 | 
  16 |

Also, when Im on my web app within the cypress UI, cypress does not recognise any elements. This is a screenshot of my webapp while tryng to select elements:
![image](https://user-images.githubusercontent.com/63807087/206431106-e76e17f0-ea7c-48d1-b13e-8554dba9d68a.png)

Can anyone help me out here. Why is this happening and how to solve it? Atm didnt inserted the links/login data out of privacy reasons.

_Additional note_: I noticed that the webapp and authentication service have the following behaviour:

 Usually, when I navigate to my web app in the UI via browser and type in the webapp URL -> for a brief part of a second I get redirected to a URL that looks like this:
 
 https://{{SYSTEM}}.authentication.{{DOMAIN}}/saml/login/alias/gateway.aws-live-eu10?disco=true&idp=https%3A%2F%2F{{HOSTNAME}}

and immediately to this one, where I acutally enter my username and password:

https://{{HOSTNAME}}/saml2/idp/sso/{{HOSTNAME}}

After entering my username and password here, I get redirected to my webapp again.

### Test code to reproduce

Original try:

it('Open webapp with cypress and perform action', () => { //Define the application. Always in combination with a function ()=>{}
    cy.visit('https://{{AUTHENTICATIONSERVICE}}.com');
    cy.get('#j_username').type('{{USEREMAIL}}');
    cy.get('#j_password').type('{{PASSWORD}}');
    cy.get('#logOnFormSubmit').click();
    
  cy.visit('https://{{MYWEBAPP}}.com');
  cy.get('.{{ELEMENTFROMWEBAPP}}').click();
  })

### Cypress Version

11.2.0

### Node version

16.16.10

### Operating System

Windows Home

**Comment by nagash77** [comment]
Hi @oaktree4 , have you read over the usage of [cy.origin](https://docs.cypress.io/api/commands/origin)?  I would suggest you download the latest version of Cypress (12.0.1) and explore that command.  Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by oaktree4** [comment]
hi @nagash77 , I did as recommended. I updated cypress as well and tackled the origin topic. Solved now.
