### ISSUE TITLE
Testing electron apps with Cypress

### ISSUE THREAD

**Issue by zsolt-dev** [cypress-io/cypress#25076]
### What would you like?

Hi,

I know testing electron apps was once supported with Cypress (via plugin) but then discontinued.

Is electron app testing ever coming back?

If not, what are the best practices mocking electron API? Is there some library for that?

I like Cypress much more than Playwright because of features such as time travel, component testing...

Thank you

**Comment by nagash77** [comment]
Hi @zsolt-dev , We have investigated this feature in the past and ultimately could not find a way to make it work that was satisfactory to us.  Please see this thread - https://github.com/cypress-io/cypress/issues/4964.  We of course would love to be able to support this use case, we just do not have it as a high priority at this time given the impediments past investigation have revealed.  We are of course open source and always open to PRs from the community. 😺
