### ISSUE TITLE
screeshot - blackout not blanking out multiple instances when using a jQuery class selector.

### ISSUE THREAD

**Issue by awcoats** [cypress-io/cypress#2508]
### Current behavior:

![home -- visit us 2](https://user-images.githubusercontent.com/748080/45922821-a30fed00-be93-11e8-9641-17a5687e5127.png)

### Desired behavior:

`.headerMain-navMainLink` should select multiple items to be blacked out. Only the first item is being blacked out. In the above screen shot, the top nav items (6) should be blacked out.

### Steps to reproduce:

https://github.com/awcoats/cypress-test-tiny/blob/master/cypress/integration/spec.js

### Versions

Cypress package version: 3.1.0
Cypress binary version: 3.1.0
Windows 10
Electron 59 (headless)

**Comment by chrisbreiding** [comment]
Thanks for reporting this. I confirmed it's a bug and found the root cause. Should be a pretty simple fix.
