### ISSUE TITLE
.invoke('pop') starts failing on v12.0.2

### ISSUE THREAD

**Issue by KrzGruszcz** [cypress-io/cypress#25085]
### Current behavior

by adding ``.then(console.log)`` after invoking .pop() method:

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/86097671/206673338-2069dad4-093d-441d-8773-f974576c444c.png">

In Cypress v11 ``.then(console.log)`` was not changing the subject.

### Desired behavior

adding ``.then(console.log)`` should not change the subject

### Test code to reproduce

```js
it("fails", () => {
  cy.wrap([2, 1])
    .invoke("pop")
    .then(console.log)
    .should("eq", 1);
});

it("passes", () => {
  cy.wrap([2, 1])
    .invoke("pop")
    .should("eq", 1);
});

it("passes", () => {
  cy.wrap([2, 1])
    .then(console.log)
    .should("deep.eq", [2, 1]);
});

it("passes", () => {
  cy.wrap([2, 1])
    .should("deep.eq", [2, 1]);
});
```

### Cypress Version

12.0.2

### Node version

v16.18.0

### Operating System

mac OS 13.0.1

**Comment by BlueWinds** [comment]
Cypress 12.0.0 contains a breaking change around .invoke():

> If you chain further commands off of .invoke(), it will be called multiple times. If you only want the method to be called once, end your chain with .invoke() and start fresh with cy afterwards.

https://docs.cypress.io/api/commands/invoke

Simply put, invoke should not be used with functions that aren't idempotent anymore. Use `.then()` instead, if you only want the function to be called once.

```
it("fails", () => {
  cy.wrap([2, 1])
//    .invoke('pop') // Don't do this!
    .then(subject => subject.pop()) // Do this instead.
    .then(console.log)
    .should("eq", 1);
});
```
