### ISSUE TITLE
Cypress doesn't catch element changes

### ISSUE THREAD

**Issue by alexander-miroch** [cypress-io/cypress#25095]
### Current behavior

In the test below 'user' enters an incorrect email address in the form field. After catching the error it enters more characters in the form to make the email address correct. The error visually disappears from the screen but the next element query still shows the error message

Everything starts working correctly If I put a delay between making the email address valid and querying the error field again.

 

### Desired behavior

Pass the test

### Test code to reproduce

```
it.only('Enters invalid email and then enters a valid email address', () => {
  cy.get('input[aria-label=Email]').type('aaa@aaa') // Enter incorrect email
  cy.get('input[aria-label=Password]').click() // just to change the focus
  cy.get('label:has(input[aria-label=Email]) div.q-field__bottom').as("emailField").should('contain', 'Invalid Email Address')
  cy.get('input[aria-label=Email]').type('.com')  // make the email address correct
  // cy.wait(10000)  // If we uncomment this line then everything starts working as expected
  cy.get('@emailField').invoke('text').then(r => {
      cy.log(r)  // Shows 'Invalid Email Address' 
      cy.log(r.length).then(() => r) // Logs 21
    }).should('have.lengthOf', 0) // The test fails here. The length is still 21
 })
 ```

### Cypress Version

12.0.2

### Node version

v18.12.1

### Operating System

Ubuntu 22.04

**Comment by BlueWinds** [comment]
https://docs.cypress.io/guides/core-concepts/retry-ability#Only-queries-are-retried

> Any command that isn't a query, such as cy.click(), follows different rules than queries do. Cypress will retry any queries leading up to a command, and retry any assertions after a command, but commands themselves never retry - nor does anything leading up to them after they've resolved.

In your case, `.then()` is not a query, and does not retry. So it executes immediately - as soon as `cy.get('@emailField').invoke('text')` resolves, with the first possible value.

If you want .then() to wait for a specific state before executing, put an assertion before it.
