### ISSUE TITLE
Snapshots show box model layers of non-displayed elements

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#251]
If an element is styled `display: none`, the snapshot that includes it still shows the margin and padding of the element, but should not since the margin and padding are not applied to the page.

![display none margin and padding](https://cloud.githubusercontent.com/assets/1157043/18914842/b23dccf6-855c-11e6-8146-1ae5708e3c51.png)

In the example above, there are 4 `<p>` tags, but one is `display: none`, and when the snapshot is restored, it shows that elements margin in padding in the top left of the viewport. 

We need to take non-displayed elements into account and not show their box model layers with the snapshot.

**Comment by brian-mann** [comment]
Fixed in [`0.17.5`](https://github.com/cypress-io/cypress/wiki/Changelog#0175-10022016).
