### ISSUE TITLE
Problem cancelling old XHRs after cy.visit()

### ISSUE THREAD

**Issue by mustafahamid** [cypress-io/cypress#2510]
Operating System: window 10
Cypress Version: 3.1.0
Browser Version: Electron 59
Is this a Feature or Bug?
Bug

Current behavior:
```js
cy.visit("page number one")
```
Do user interaction that will generate XHRs 
```js
cy.visit("page number two")
```

Some of XHRs will be aborted that generated by page one
![image](https://user-images.githubusercontent.com/38086105/45943930-a1a40900-bfe8-11e8-972a-f1cdfbc0f45b.png)

![image](https://user-images.githubusercontent.com/38086105/45943916-905afc80-bfe8-11e8-9800-51116896415c.png)

Desired behavior:
The XHR should not be cancelled before the next visite starts

**Comment by jennifer-shehane** [comment]
Hey @mustafahamid, the test is going to abort any outstanding XHR requests when the page is navigated away (as would happen in any browser)

If you want to wait for the XHR's to finish, then we recommend using a `cy.wait()` to wait for any defined routes to finish first.
