### ISSUE TITLE
Why is the keyboard tab not supported?

### ISSUE THREAD

**Issue by doocal** [cypress-io/cypress#25105]
### What would you like?

Why is the keyboard tab not supported?

**Comment by sagar-maheshwari** [comment]
There is an open issue on this for the past 6 years: https://github.com/cypress-io/cypress/issues/299

Meanwhile, there is a plugin mentioned here which can be used as a workaround: https://docs.cypress.io/api/commands/type#Tabbing

**Comment by nagash77** [comment]
Hi @doocal please see the ticket @sagar-maheshwari linked (thank you for helping on that!).  If you have thoughts to share please do add them to https://github.com/cypress-io/cypress/issues/299. 

I am going to close this ticket as a duplicate.

Please be sure to follow along on that ticket for updates.
