### ISSUE TITLE
Fixture support inside JS class and call it to main test

### ISSUE THREAD

**Issue by AdarshKumarGM** [cypress-io/cypress#25106]
### What would you like?

Currently we have to provide fixture inside main test under "beforeEach" or "before" in the describe block. What if we want to have a clean test i.e., no arguments in the methods but is purely driven by fixture test data from classes or even keep the arguments to a very minimal from the 'it' block
As on date, Cypress doesn't allow to pass on the fixture file from outside the running test and we receive an error.

1. Main Test:

![image](https://user-images.githubusercontent.com/46774573/206981758-fc7c5f02-7551-4184-9b58-5f2a9e0922db.png)

2. JS Class file:

![image](https://user-images.githubusercontent.com/46774573/206983797-ea30cda4-f89b-4b82-b055-225af0cdf8af.png)

3. Error received in the test:

![image](https://user-images.githubusercontent.com/46774573/206982199-a5db39ea-fd70-4a57-8f92-39a251af32ba.png)

### Why is this needed?

1. This would help in having a clean looking main test file instead of adding lot of "this.testdata" as arguments to the methods in the main "it" block tests
2. We can drive the entire thing through fixture data without having to look into each class files.

**Comment by brian-mann** [comment]
Is there any reason why you couldn't `import {...} from 'cypress/fixtures/AEM/Environment'` at the top of your spec file? It seems like all you want is static data at the top of the spec to work off of. If you import normally the spec will be built just fine.

Also your code for `visitPage` is using async cypress commands and then synchronous code underneath it, which won't work. You'd need to move that code into the `then(...)` block.

Ultimately I think we're a little confused as to what your intention is or what you're trying to solve for, and it's very likely there is a better approach here than the path you're taking. It may be helpful to put together a reproducible repo or simplify what you're trying to do in order for us to give you guidance on the right approach here.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
