### ISSUE TITLE
TypeError: Failed to resolve module specifier

### ISSUE THREAD

**Issue by directcuteo** [cypress-io/cypress#25125]
### Current behavior

Suddenly, every test in my **Angular** application is failing due to next error:

```
(uncaught exception)TypeError: Failed to resolve module specifier "rxjs".
Relative references must start with either "/", "./", or "../".
```

I am using:
```
    "webpack": "^5.75.0",
    "cypress": "^12.1.0",
    "@angular-devkit/build-angular": "^14.0.2",
    "typescript": "~4.7.2",
    "rxjs": "~7.6.0",
    "@angular/animations": "^14.0.0",
    "@angular/cdk": "^14.2.1",
    "@angular/common": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/core": "^14.0.0",
```

### Desired behavior

Tests should work. I appreciate any guidance. Thank you!

### Test code to reproduce

Running any test fails. Even this one:

```
describe('TEST', () => {
  beforeEach(() => {
    cy.visit(Cypress.env('baseUrl') + '/dashboard');
  });

  it('displays dashboard title', () => {
    cy.get('toolbar span')
      .then((span: any) => expect(span).contain('Dashboard'));
  });
});
```

### Cypress Version

12.1.0

### Node version

v18.12.1

### Operating System

Windows 11

**Comment by mike-plummer** [comment]
Hi @directcuteo , sorry to hear you're having trouble. Unfortunately you haven't provided quite enough information to help diagnose your issue - a simple app scaffolded with `@angular/cli@14.0.0` seems to work fine on my local using Cypress v12.1.0. Could you provide a reproducible example of the issue you're encountering, ideally in the form of a simple Git repo we could pull down and run on our end to see the problem? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

If you aren't able to provide a runnable reproduction it will be much harder for us to assist with your issue, but not impossible. We would ask that you [provide Debug Logs from Cypress](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) so we can get some more detail about potential configuration/environment issues that might be happening.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by RobbieTheWagner** [comment]
I'm hitting the same issue. How are we supposed to get cypress to find packages? If your code ships ESM, but depends on another dependency that it imports, you hit this issue. For example, we are hitting `Failed to resolve module specifier "deepmerge". Relative references must start with either "/", "./", or "../".` in shepherd.js which depends on `deepmerge`.
