### ISSUE TITLE
Changing viewport sometimes doesn't work?

### ISSUE THREAD

**Issue by SwimmingPolar** [cypress-io/cypress#25123]
### Current behavior

https://gist.github.com/SwimmingPolar/89c6a1172b1e1b03ec8159b8c7ce0672

I have this hook to run a single test against devices with different width. It runs the same test but with different viewport size altered when the test was initialized.

I notice sometimes changing viewport doesn't take effect so it stays as the initial viewport size causing the test to fail.
For example, if there's an element that is visible or exists only on mobile devices. Cypress just throws timeout error.
But when I run test multiple times, most of the time it passes.

Is it maybe I'm changing the viewport size too often? Have no clue.

![image](https://user-images.githubusercontent.com/53928959/207232136-42997473-fa96-4a72-80b3-d05faa014129.png)
![image](https://user-images.githubusercontent.com/53928959/207232213-1cd2a4ff-8818-4d3c-9d46-483f74690599.png)
![image](https://user-images.githubusercontent.com/53928959/207232275-a14c72be-7936-4d5b-8a27-61efafe11e94.png)

Just ran 3 test continously and 1 out 3 failed. No code changed. Just clicked refresh 3 times.

### Desired behavior

Should change viewport size properly.

### Test code to reproduce

Unfortunately, the test was ran under e2e test so there isn't short version of code for reproduction.

### Cypress Version

10.11.0

### Node version

v16.16.0

### Operating System

WSL2 under Windows 11

**Comment by nagash77** [comment]
Hi @SwimmingPolar ,  Unfortunately without a reproducible example the team won't be able to debug effectively. I am going to close this issue until we can get a reproducible example.

I would also add that we do not currently offer first class support for WSL and I have seen issues running WSL before. Do you see the same problems on native windows or native linux?

**Comment by SwimmingPolar** [comment]
> Hi @SwimmingPolar , Unfortunately without a reproducible example the team won't be able to debug effectively. I am going to close this issue until we can get a reproducible example.
> 
> I would also add that we do not currently offer first class support for WSL and I have seen issues running WSL before. Do you see the same problems on native windows or native linux?

As you mentioned, the problem may have to do with cypress and wsl not playing along smoothly. Never tried running the code under native OS. I just found workaround and I'm satisfied with it.

For those of you having the similar problem, my problem was that cypress didn't give enough time for viewport to change causing some viewport(media/device) specific elements to not load properly. And the 'action' couldn't take place. The way to solve this is to add an extra assertion between the viewport change code and execution code of any 'actions'. That way we have extra delay between switching the viewport and those device specific elements can be fully loaded.

before
```javascript
      cy.viewport(viewports[device].width, viewports[device].height)
      cy.get('[data-cy="signup-page"]').find(`a[href="/login"]`).click()
```
after
```javascript
      cy.viewport(viewports[device].width, viewports[device].height)
      // extra assertion
      cy.get('[data-cy="signup-page"]').contains("Go to login")
      cy.get('[data-cy="signup-page"]').find(`a[href="/login"]`).click()
```

As the doc says, 'find' will also wait for the element to show up but without the extra assertion it didn't work.
