### ISSUE TITLE
cypress-vue: cannot override `mount` command with custom type: error: cypress Duplicate identifier 'mount'

### ISSUE THREAD

**Issue by cmcleese** [cypress-io/cypress#25144]
### Current behavior

When following the guide on how add a custom mount method for example to use vue router here:
https://docs.cypress.io/guides/component-testing/vue/examples#Vue-Router

The following error on typing is displayed: `cypress Duplicate identifier 'mount'`
![image](https://user-images.githubusercontent.com/2061466/207598358-87f6b49c-5cff-4459-ab17-4b96ce170524.png)

Subsequently when defining the command, it doesn't pick on the new params defined in the type definition.
```js
// cypress/support/commands.ts

Cypress.Commands.add('mount', (component, options = {}) => {
...
});
```

### Test code to reproduce

```ts
// cypress/support/index.d.ts

import { mount } from 'cypress/vue';
import { Router } from 'vue-router';
// load type definitions that come with Cypress module
/// <reference types="cypress" />

declare global {
  namespace Cypress {
    type MountParams = Parameters<typeof mount>;
    type OptionsParam = MountParams[1] & { router?: Router };
    interface Chainable {
      mount(component: any, options?: OptionsParam): Chainable<any>;
    }
  }
}

```

### Cypress Version

11.2.0

### Node version

16.18.1

### Operating System

win10x64

**Comment by mike-plummer** [comment]
Hi @cmcleese , sorry to hear you're having trouble. By default we automatically add `mount` as a command in the `/support/component.ts` file - I suspect you're conflicting with that definition by attempting to define two different `mount` commands. Could you try replacing the default declaration with your custom implementation (including the types)?

**Comment by cmcleese** [comment]
Yes I can write a new mount command declaration such as `mount2` which doesnt give TS errors.
I think I have a different issue as I'm using bootstrapped cypress setup from Quasar v2 library.
If there is something other than issue that comes up and I'll leave it to being a new potential issue.

Thanks for the insight. this can be closed
