### ISSUE TITLE
Cypress doesn't set cookies properly from Post requests

### ISSUE THREAD

**Issue by GrayedFox** [cypress-io/cypress#2515]
### Current behaviour:

I thought this was originally due to white-listing cookies, but after removing that from my test suite I can see now that the way Cypress sets cookies from post requests is inherently flawed.

~~Doing a POST request which returns a cookie only sets this cookie once the command has run twice. This behaviour is exhibited when retrying the test suite (all tests now pass) or can be worked around, in some (but not all cases), by visiting a page before doing the login command.~~

After further debugging, it is clear that this bug is actually about where the log in request is being made. When logging in at the beginning of each individual `it()` block and running the test inside the callback of the login, the tests pass as expected.

If placing the login command inside a `beforeEach()` block, the test fails, with the cookie being rejected by our server. This would suggest that the `it()` blocks inside each `describe()` block are actually new sessions, making logging in inside a `beforeEach()` block redundant (and counter intuitive).

### Desired behaviour:

Cypress allows the session to login inside a `beforeEach()` block so that the code can be kept DRY.

### Steps to reproduce:

1. Write a custom command which sends a POST request to log you in to your app/service
2. Inside a test file, inside the beforeEach block, execute the custom command
3. Try accessing an authenticated page inside an `it()` block or sending a request

```
let authToken = ''

describe('/meters', () => {
  // this should work, but Cypress cookie handling is bugged, see:
  // https://github.com/cypress-io/cypress/issues/2515
  // beforeEach( () => {
  //   cy.login('mgm')
  // })

  it('retrieves booked meters as an account manager', () => {
    // this works, but now I have to login inside every single it() block
    cy.login('mgm', (response) => { 
      const options = {
        filter: ['parent_id', 'null'],
        fields: ['real-properties', 'id,name,installation-complete'],
        include: 'booked-meters,booked-meter-modules'
      }

      cy.api('GET', 'users', options, authToken).then( (response) => {
        cy.log(response)
      })
    })
  })
})
```

Ideally, for sending authenticated API requests (as seen in the above example) - we would need only to login during the beforeEach block and not need to wrap our api tests inside a login callback every time.

Keep up the great work!

### Further Info

Interestingly, if logging in via the custom command, later requests do have a cookie attached (but it is invalid/expired):

```
The request we sent was:

Method: GET
URL: https://ourservice.com/users/25?filter[parent_id]=null&fields[real-properties]=id,name,i...
Headers: {
  "accept": "application/vnd.api+json",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.1.0 Chrome/59.0.3071.115 Electron/1.8.2 Safari/537.36",
  "cookie": "_mh-platform_session=UlEwMnU3ajJwRHdYV0cvWEd4YUgyMzhXR2dBYzNyT1EwOFViOURCczhLNXJnSjVjZ3JqMC9XSnNWcE5tNzlrcGM1YkxGT2QrYVV2S0tMTWUzUlRCbjhjNnJJcTR2aG4yREpwVDBVZmp0c1o4ZWpacHJXQWpPN1VCMkw1US8xZCtoYmNYKzdyRnRrT1YvaW9uakRiazJ3PT0tLTBteUorSFlQOVUzSW9KMGV3c0tRTHc9PQ%3D%3D--57ad066beabad4fdfc816c955edb72abc2f4cbcc",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
...
```

I think this confirms my suspicion - that Cypress is in fact attaching the cookie gained from the beforeEach() block to requests made in the `it()` blocks, but the new session means it's invalid.

### Versions

Cypress 3.1.0
Ubuntu 18.04 LTS
Chrome 69
Electron 59

**Comment by GrayedFox** [comment]
Closing - made this thinking the correct cookie was not being used but later realised that the correct cookie is, in fact, being sent. It's no longer clear whether this is perhaps an error on our end, will re-open if I can confirm and reproduce this on the Cypress side.

**Comment by GrayedFox** [comment]
Any tips on authenticating against a Rails backend would be very welcome, attaching the `authentication_token` hidden inside the form when using the browser is still failing me.

**Comment by jennifer-shehane** [comment]
You may find [`cy.task()`](https://on.cypress.io/task) useful, depending on what you need to do.
