### ISSUE TITLE
Update Release Process to kick off from PR with Version Bump

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#25162]
@emilyrohrbough commented on [Tue Sep 20 2022](https://github.com/cypress-io/cypress-internal/issues/489)

After verifying the pre-release binary works as expected. This is a quick smoke test to verify at a minimum:

Release should kick off by creating PR in the cypress repo against `develop`. PR changes:
- Bump version in package.json
- Update cypress-kitchen-sink version (if needed)
- Update changelog verbiage (if needed)

on merge, the release workflow kicks off in CI

**Comment by wojtekxtx** [comment]
Hello from passerby:

We have done something similar in [our project](https://github.com/nslabspl/storybook). It works as expected and helps us greatly.

However, there is one trap (we've found and reported it upstream) here: while configuring action that will trigger release, just **dont use** `[]` brackets.
