### ISSUE TITLE
Move monorepo CT suite to use experimentalSingleTabRunMode

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#25165]
### What would you like?

Working towards making `experimentalSingleTabRunMode` the default. Next step is using it more internally - all CT suites should use it.

### Why is this needed?

Dogfooding our experiment

**Comment by rockindahizzy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25165?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @mike-plummer @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Should this include `system-tests/*`? I think it should.
