### ISSUE TITLE
Can't login with Azure SAML application

### ISSUE THREAD

**Issue by hshimmex** [cypress-io/cypress#25169]
### Current behavior

Hi,

Our application uses SAML - azure authentication.
That means after login to the application, redirect to azure is done with SAML response, like that:

https://login.microsoftonline.com/<tenantId>/saml2?SAMLRequest=SAML response&sso_reload=true

When I tried to login into our application, the redirect to azure login is done, but the request above run in a loop until getting 'url too long' error:

![image](https://user-images.githubusercontent.com/90679351/207588131-ef0bb305-711c-4965-a987-51dcd0e9b7e0.png)

My cypress.config.ts looks like this:

 e2e: {

    experimentalSessionAndOrigin: true,
    experimentalModifyObstructiveThirdPartyCode: true,
    chromeWebSecurity: false, 
    

### Desired behavior

After successful redirect to azure login, this screen shown:

![image](https://user-images.githubusercontent.com/90679351/207594514-70ce0559-1ef1-4552-9a3b-4f132ea6cc47.png)

### Test code to reproduce

unfortunately, I can't give the url. So I just run cy.visit:

   
 cy.visit(<My url>, {
        failOnStatusCode: false, headers: {
            "sec-ch-ua": "' Not A;Brand';v='99', 'Chromium';v='101', 'Google Chrome';v='101'",
        }
    })

### Cypress Version

10.9.0

### Node version

v16.0

### Operating System

Windows

**Comment by AtofStryker** [comment]
Hi @hshimmex. Thank you for opening an issue. Are you on a company or corporate laptop? Would you be able to try [standalone chromium](https://chromium.cypress.io/) to see if the issue persists? 

We have seen this infinite redirect issue before, but it is usually solved by `experimentalModifyObstructiveThirdPartyCode`, which you have configured. I know the URL is private, but are you able to share a reproduction repository, private or public?

**Comment by hshimmex** [comment]
Hi @AtofStryker 
The problem isn't reproduce in chrome standalone.

I can't share a repository, but I see this exception thrown in console log:

![image](https://user-images.githubusercontent.com/90679351/208394650-39622d12-ebc6-4235-b125-965b041fd0b8.png)

Does this information help?

Thanks

**Comment by AtofStryker** [comment]
> Hi @AtofStryker The problem isn't reproduce in chrome standalone.
So you are able to log in fine in standalone chrome? How about edge, electron, or firefox? Are you on a corporate managed device? It might explain why it works in standalone chromium but not chrome if chrome has a lot of Corporate Security Policies (CSP) added by your sysadmin

> I can't share a repository, but I see this exception thrown in console log:
> 
> ![image](https://user-images.githubusercontent.com/90679351/208394650-39622d12-ebc6-4235-b125-965b041fd0b8.png)
> 
> Does this information help?

It could be useful, but it's going to be difficult to say what exactly could be going on here without a reproduction. It almost looks like the Cypress code that wires up `cy.origin` and attaches cypress to the window is failing. @mjhenkes any ideas?

**Comment by hshimmex** [comment]
Hi,

I found the solution. The issue was I tried to do the first navigation outside the origin, and not inside him. 

Thanks,
Hagit
