### ISSUE TITLE
Cypress not waiting for async describe callback to finish

### ISSUE THREAD

**Issue by naturedamends** [cypress-io/cypress#25172]
### Current behavior

It won't wait for async describe callback before starting the tests.

```javascript
describe(async () => {
  await waitN(3000);   
  it(... // use result of await to create the its.
})
```

And will register no tests

### Desired behavior

The promise that describe returns is waited on before starting the test flow. 

Ability to pass serialised data to `cypress run` or use environment variables? seems haky

i'm having to pass data in via environment variable, which makes using `npx cypress run`, hard since I need to write a script to create the env var

### Test code to reproduce

....

### Cypress Version

10.11.0

### Node version

v16

### Operating System

linux

**Comment by mike-plummer** [comment]
Hi @naturedamends , thanks for reaching out. What you have shown is actually expected behavior in the Mocha test runner that Cypress is built upon - you may want to review the [docs on Mocha here](https://docs.cypress.io/guides/references/bundled-libraries#Mocha).

It's not clear from your writeup exactly how you're trying to load and use data, but here are a couple examples of how you can execute and await async code prior to a test executing:

**Execute once and only once before a given test**
Place your async code within the `it` block itself
```
it('does async stuff', async () => {
  const data = await loadData()
  ....
  // do test
})
```

**Execute once and only once per test suite**
Place your async code within a `before` block, store results to a contextual variable
```
describe('my suite', () => {
  let data

  before('do this once', async () => {
    data = await loadData()
  })

  it('tests stuff', () => {
    // use `data` here
    // Important to not mutate `data` since it's used by other tests and execution order isn't guaranteed
  })
})
```

**Execute once before each and every test in the suite**
Place your async code within a `before` block, store results to a contextual variable
```
describe('my suite', () => {
  let data

  beforeEach('do this once per test', async () => {
    data = await loadData()
  })

  it('tests stuff', () => {
    // use `data` here
    // Do what you want with it here because it will be reloaded before the next test
  })
})
```

**Comment by naturedamends** [comment]
@mike-plummer Hi thanks for the quick response. Your snippets don't accomplish what I was truing to do. I have since found a solution that works. Although to me is just feels wrong?

```javascript
const cypress = require('cypress')

const routing = require('./routing')


async function main() {
    const routes = await routing();

    cypress.run({
        reporter: 'junit',
        browser: '',
        headed: true,
        config: {
            baseUrl: 'http://localhost:1313',
        },
        env: {
            routes: JSON.stringify(routes) 
        }
    })
}

main()
```

```javascript
// specjs.js
describe('Visuals', async () => {
    const routes = JSON.parse(Cypress.env('routes'))

    routes.forEach(r => it(r.path, () => {
        cy.visit(r.path)
        const retryOptions = {
            limit: 5,
            delay: 500
        }
        cy.compareSnapshot(r.uniqueName, 0, retryOptions)
    }))

})
```


I'm trying to generate the tests. I know I could generate files and include in the webpack bulid, but just tried this clean looking way, and it didn't work. Not sure if this is a issue ,perhaps a enhancement . I'lll leave for you to close.

Would the required change be complex? i'm looking for something open source to write?

What I was attempting with await was to query a server

```javascript
describe(async () => {
  const routes = await feedToRoutes(await axios.get('localhost:1313/sitemap.xml'))
  routes.forEach(() => it(...
```

**Comment by mike-plummer** [comment]
@naturedamends Ah, I understand what you're wanting to do now - dynamically generate test cases based on asynchronously-loaded data. I assumed you just needed to *use* the data in your tests, not leverage it to scaffold the tests dynamically.

We actually have a couple recipes for doing this using the [`setupNodeEvents`](https://docs.cypress.io/guides/references/configuration#setupNodeEvents) API in your Cypress config file. This logic executes in Node before the test suite loads and can be used to asynchronously fetch data from a file, API, etc and store it onto a variable which can then be referenced to scaffold out test cases.

Examples:

- [Load & use data from CSV file](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests-from-csv)
- [Load & use data from API call](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests-from-api)
- [Using `cy.task` for more complex Node-side data fetching](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests)
