### ISSUE TITLE
Clearer message when expectation fails between string an numbers

### ISSUE THREAD

**Issue by maxime1992** [cypress-io/cypress#2517]
### Current behavior:

As an image is worth a 1000th words:

![image](https://user-images.githubusercontent.com/4950209/45967793-f23a5700-c026-11e8-97a6-cac200b8c61f.png)
"Wut"?

![image](https://user-images.githubusercontent.com/4950209/45967808-fd8d8280-c026-11e8-952b-0156f76c7007.png)
"Oh fine"

### Versions

Cypress 3.1.0

**Comment by jennifer-shehane** [comment]
This has already been fixed in a more recent version. 
<img width="498" alt="Screen Shot 2021-03-31 at 2 11 17 PM" src="https://user-images.githubusercontent.com/1271364/113190985-ffa1af00-922a-11eb-94fe-0a90a190883b.png">
