### ISSUE TITLE
Compilation error when using `import.meta`

### ISSUE THREAD

**Issue by cmcleese** [cypress-io/cypress#25187]
### Current behavior

Using `import.meta` to import my .env vars in my project works fine with Vite but when running Cypress the following error is shown

ex: `const VITE_APP_WEBAPI = import.meta.env.VITE_APP_WEBAPI;`

Error:
```
Error: Webpack Compilation Error
./src/services/environmentVariables.ts 1:37
Module parse failed: Unexpected token (1:37)
File was processed with these loaders:
 * C:\Users\USER\AppData\Local\Cypress\Cache\12.1.0\Cypress\resources\app\node_modules\@packages\server\node_modules\ts-loader\index.js
You may need an additional loader to handle the result of these loaders.
> export const VITE_APP_WEBAPI = import.meta.env.VITE_APP_WEBAPI;
 @ ./src/services/LocalStorage/localStorage.ts 1:0-72 3:10-29 4:15-34 5:14-33
 @ ./test/cypress/support/commands.ts
 @ ./test/cypress/support/e2e.ts
    at Watching.handle [as handler] (C:\Users\USER\AppData\Local\Cypress\Cache\12.1.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-preprocessor\dist\index.js:231:23)
```

### Test code to reproduce

add  import.meta.env anyway in project code

### Cypress Version

12.1.0

### Node version

16.18.1

### Operating System

win10x64

**Comment by mike-plummer** [comment]
Hi @cmcleese , thanks for reaching out. It's difficult to say for sure without a reproduction, but it appears that you're trying to import and execute Vite-specific code within Cypress. From the logs it appears that you're indirectly using Vite-specific code from within a custom `localStorage`-related command. Under the covers Cypress uses Webpack which [does not support this syntax](https://github.com/webpack/webpack/issues/15833).

The easiest way to resolve this is to not import this code into your Cypress tests - if it's not imported, it won't be executed by Cypress. If you need to import it then I can suggest a couple workarounds:

### If you are trying to import that file to get direct access to environment variables in your specs
Cypress has dedicated support and APIs for [Environment Variables](https://docs.cypress.io/guides/guides/environment-variables) - I would recommend using these instead to improve the stability and portability of your specs.

### If this file is incidentally imported and you *do* rely on it resolving variables correctly
1. Restructure your code to use an "environment variables manager" struct which can, in production, be populated from the Vite location or, in tests, from Cypress
2. You can add a new babel plugin to automatically transpile the Vite-specific `import.meta*` fields
[Potential plugin option](https://www.npmjs.com/package/babel-plugin-transform-vite-meta-env)
[Updating Cypress config](https://docs.cypress.io/guides/tooling/plugins-guide#Preprocessors)

### If this file is incidentally imported and you *do not* rely on it actually resolving variables
See if you can restructure your code or use a guarded dynamic import so it is not executed from within your Cypress tests.

**Comment by lmiller1990** [comment]
To add onto the above points, if you can share a minimal example of what you are doing, that would be great.

Another alternative would be using the webpack `DefinePlugin` to define these, but you'd be duplicating your config a bit.
Edit: another work around: https://github.com/webpack/webpack/issues/15833#issuecomment-1232750814

To add another alternative -  there is `esbuild-preprocessor` which should support this https://github.com/bahmutov/cypress-esbuild-preprocessor (and is quite fast). I also saw a new project, Cypress Vite - https://github.com/mammadataei/cypress-vite. This looks quite fresh, but might be another alternative to keep an eye on, if you want to use a more modern, ESM oriented preprocessor.

**Comment by cmcleese** [comment]
Thanks for all the info.
To clarify a bit more, I've changed the naming be a bit more clear:

this is just for easy use of env vars
```js
// src/services/environmentVariables.ts

export const APP_WEBAPI = import.meta.env.APP_WEBAPI;
export const LS_DATA_PREFIX = import.meta.env.LS_DATA_PREFIX;
```

this is just a generic ref file for LS key lookups
```js
// src/services/LocalStorage/localStorage.ts

import { LS_DATA_PREFIX } from 'src/services/environmentVariables';

export const LS = {
  USER: LS_DATA_PREFIX + 'USER',
  TOKEN_EXP: LS_DATA_PREFIX + 'TOKEN_EXP',
  LANGUAGE: LS_DATA_PREFIX + 'LANGUAGE',
};
```

in `cypress.config.ts`
```js
devServer: {
      framework: 'vue',
      bundler: 'vite',
    },
```

I'm using the format `import.meta.env` because I'm using a https://iendeavor.github.io/import-meta-env/ which allows me to change imbedded env variables in compiled dist Frontend code when building Docker containers.

I'm not quite sure this error is showing up as using webpack when I have it set in cypress config to use 'vite' bundler.


ERROR:
```
Error: Webpack Compilation Error
./src/services/environmentVariables.ts 1:32
Module parse failed: Unexpected token (1:32)
File was processed with these loaders:
 * C:\Users\USER\AppData\Local\Cypress\Cache\12.1.0\Cypress\resources\app\node_modules\@packages\server\node_modules\ts-loader\index.js
You may need an additional loader to handle the result of these loaders.
> export const APP_WEBAPI = import.meta.env.APP_WEBAPI;
| export const LS_DATA_PREFIX = import.meta.env.LS_DATA_PREFIX;
| 
 @ ./src/services/LocalStorage/localStorage.ts 1:0-67 3:10-24 4:15-29 5:14-28
 @ ./test/cypress/support/commands.ts
 @ ./test/cypress/support/e2e.ts
    at Watching.handle [as handler] (C:\Users\USER\AppData\Local\Cypress\Cache\12.1.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-preprocessor\dist\index.js:231:23)
```

**Comment by cmcleese** [comment]
I removed the imports for `import.meta.env` as suggested and used cypress env variables instead in the `cypress.config.ts`
```js
  env: {
    APP_WEBAPI: process.env.APP_WEBAPI,
    LS_DATA_PREFIX: process.env.LS_DATA_PREFIX,
  },
```

and this appears to work as described. 
Thank you again for the insight and help!
