### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

### ISSUE THREAD

**Issue by gonjavi** [cypress-io/cypress#25180]
### Current behavior

Cypress Version: 9.7.0
node version v16.13.2
npm version 9.2.0
os: Ubuntu 20.04 -using wsl on windows

I run: npx cypress run

and I've got this message of failure:

The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 9.7.0

### Test code to reproduce

Run the tests

### Cypress Version

 9.7.0

### Node version

v16.13.2

### Operating System

Ubuntu 20.04 -using wsl on windows

### Debug Logs

```shell
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 9.7.0
```

### Other

![image](https://user-images.githubusercontent.com/49737160/207921654-8eed954b-6e5c-479f-b2e1-788a234d6c10.png)

**Comment by nagash77** [comment]
Hi @gonjavi , I am sorry to hear you are having difficulties running Cypress.  I see you are using WSL.  Unfortunately at this time we do not have official support for WSL.  I am going to close this issue until you can provide us with a reproducible example on windows, macOS, or native ubuntu.  If you are able to replicate this issue on a native OS please do comment back on this issue with the reproducible example and we can reopen.
