### ISSUE TITLE
Microsoft Login not redirecting to the BaseURL of the application

### ISSUE THREAD

**Issue by Praveen20K** [cypress-io/cypress#25194]
### Current behavior

Currently I'm facing Cookies Disabled issue when I tried to do Microsoft Login. Due to which the page is not redirecting back to the Base URL of my application.
![image](https://user-images.githubusercontent.com/58627337/208051618-796bb277-b3a1-412b-a5ad-e930eb9502ed.png)
![Microsoftloginissue](https://user-images.githubusercontent.com/58627337/208052968-3ce62145-a1c7-4532-87ca-e78d1335689e.jpg)
![networkcallfailure](https://user-images.githubusercontent.com/58627337/208058533-9b2dfbb6-e60f-45c7-86a1-6a999c45f2e0.png)

### Desired behavior

After the Microsoft login is successful the page should redirect back to the BaseUrl of my application and shouldn't throw Cookies Disabled issue.

### Test code to reproduce
```js
//Microsoft Login Scenario:

cy.session([Email, password], ()=>{
  cy.on('uncaught:exception', (e) => { 
    return false
  })
  cy.origin('https://login.microsoftonline.com',{ args: { Email, password } }, ({ Email, password }) => {
    cy.on('uncaught:exception', (e) => { 
        return false
    }) 
    cy.visit('/{{TenantID}}/oauth2/v2.0/authorize?client_id={{client_id}}&scope={{scope}}&redirect_uri={{redirect_url}}')
    cy.get('input[type="email"]').type(Email)
    cy.get('div input[type="submit"]').click()
    cy.wait(3000)
    cy.get('input[name="passwd"]').type(password)
    cy.get('div input[type="submit"]').click()
    cy.wait(1000)
    cy.get('div input[type="submit"]').click()
    cy.wait(5000)
  })
  cy.visit('/dictionary-attributes/locationtype')
})
```
```js
//cypress_config.ts:

import { defineConfig } from 'cypress';
import browserify from '@badeball/cypress-cucumber-preprocessor/browserify';
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const addCucumberPreprocessorPlugin = require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;

export default defineConfig({
  e2e: {
    
    baseUrl: '{{base_url}}',
    specPattern: '**/*.feature',
    async setupNodeEvents(on, config){
      const bundler = createBundler({
        plugins: [createEsbuildPlugin(config)],
      });
      on("file:preprocessor", bundler);
      await addCucumberPreprocessorPlugin(on, config);
      on("file:preprocessor",
      browserify(config, {
        typescript: require.resolve('typescript')
      }))
      return config;
    },
    experimentalSessionAndOrigin: true,
    experimentalModifyObstructiveThirdPartyCode: true,
    experimentalInteractiveRunEvents: true,
    chromeWebSecurity: false,
    pageLoadTimeout: 180000,
  },
  experimentalModifyObstructiveThirdPartyCode: true,
  experimentalInteractiveRunEvents: true,
  chromeWebSecurity: false,
  pageLoadTimeout: 180000,
  defaultCommandTimeout: 10000,
});
```

### Cypress Version

11.2.0

### Node version

8.3.0

### Operating System

Windows 10 Pro

**Comment by AtofStryker** [comment]
possibly related to #25169

**Comment by AtofStryker** [comment]
Hi @Praveen20K. Thank you for opening an issue. I tried giving this a quick reproduction on my end with different tenant/application IDs and wasn't able to reproduce the issue. Some of the selectors are different though on our end, and makes we wonder if we have different instance versions. I do have a few questions:
* Does this work in other browsers besides Chrome 108, such as firefox, electron, or edge? Have you tried installing [standalone chromium](https://chromium.cypress.io/) to see if the issue persists? I am wondering if you are on a corporate managed device and if Corporate Security Policies in the browser, specifically chrome, are problematic
* I know you likely cannot share the portal URL, but are you able to create a full reproduction repository? This could tell us more about the azure setup and how it is different from our testbed to unblock you. Without a reproduction, I do not think we will be able to help much. Shared private reproductions are always an option. 
* Is your node version actually `8.2.0`? I wouldn't suspect this to be an issue, but we would recommend upgrading to at least node `14.x.x` as that is the minimum we support.

**Comment by AngelCampa** [comment]
Just updated from 10.6.0 to 12.1.0 and came here because I have the same issue lol it happens to me in both chrome and edge

**Comment by Praveen20K** [comment]
> Hi @Praveen20K. Thank you for opening an issue. I tried giving this a quick reproduction on my end with different tenant/application IDs and wasn't able to reproduce the issue. Some of the selectors are different though on our end, and makes we wonder if we have different instance versions. I do have a few questions:
> 
> * Does this work in other browsers besides Chrome 108, such as firefox, electron, or edge? Have you tried installing [standalone chromium](https://chromium.cypress.io/) to see if the issue persists? I am wondering if you are on a corporate managed device and if Corporate Security Policies in the browser, specifically chrome, are problematic
> * I know you likely cannot share the portal URL, but are you able to create a full reproduction repository? This could tell us more about the azure setup and how it is different from our testbed to unblock you. Without a reproduction, I do not think we will be able to help much. Shared private reproductions are always an option.
> * Is your node version actually `8.2.0`? I wouldn't suspect this to be an issue, but we would recommend upgrading to at least node `14.x.x` as that is the minimum we support.

@AtofStryker Our team is working on the questions you have asked. Will update you shortly here.

**Comment by Praveen20K** [comment]
@AtofStryker Is there any other place where we can share our reproduction repository instead of sharing here as it is open to public?

**Comment by AngelCampa** [comment]
I went back to 10.6.0 and it worked @Praveen20K , you might want to try that

**Comment by Praveen20K** [comment]
> I went back to 10.6.0 and it worked @Praveen20K , you might want to try that

I tried to downgrade to 10.6.0 even then I get the same issue

**Comment by AtofStryker** [comment]
I have a feeling this is related / is the same issue as #25148

@Praveen20K if you want to invite me to a repository I can confirm if the naive fix for #25148 works with the repro.

**Comment by mschile** [comment]
@Praveen20K, a [pre-release binary](https://docs.cypress.io/guides/references/advanced-installation#Install-pre-release-version) with a potential fix is available [here](https://github.com/cypress-io/cypress/commit/6ef6f2ecea1bd2771c600bce379abaeb747ee5b7) for each OS. Could you please try it out and let me know if it solves your issue. Thanks!

**Comment by Praveen20K** [comment]
@AtofStryker @mschile I tried to install the fix. Though Cookies issue is resolved the token call is failing due to which the application is not loading. We are currently looking into the issue if anything we can do from our side. I provide the update here if anything. Thanks.

**Comment by Praveen20K** [comment]
@AtofStryker @mschile below is the issue we are facing when we try to login to Microsoft Authenticator after installing this fix https://github.com/cypress-io/cypress/commit/6ef6f2ecea1bd2771c600bce379abaeb747ee5b7 
![image](https://user-images.githubusercontent.com/58627337/217217991-8431b88a-f3f6-4ce8-b377-6bb78e6e7809.png)
![image](https://user-images.githubusercontent.com/58627337/217218116-71ea62ea-dc6f-4532-a5a9-2d7695caf71d.png)
![image](https://user-images.githubusercontent.com/58627337/217218227-21ca967d-8bc1-48b5-b89d-874683cf3eeb.png)

**Comment by mschile** [comment]
@Praveen20K, could you compare the `token` request between this Cypress request and from one outside of Cypress to see if there is anything different in the headers.

**Comment by Praveen20K** [comment]
@mschile below are the screenshot for the request header of token call for Cypress and the application. Also, if possible please provide your Email Id where I can share you the full reproduction repository so that you can try it out in your local.

Cypress:
![image](https://user-images.githubusercontent.com/58627337/217522426-511c9b71-3819-44c1-b193-800e183ee7ed.png)

Application UI:
![image](https://user-images.githubusercontent.com/58627337/217522870-948b8d61-58c4-4657-af35-f1ad387ec9cd.png)

**Comment by mschile** [comment]
You can email it to mschile@cypress.io

**Comment by mschile** [comment]
@Praveen20K , could you please try this [pre-release binary](https://github.com/cypress-io/cypress/commit/38a65a6d7c04dff8e5663d9fee1b7df1b5828fb4#comments) that contains a few cookie fixes to see if it resolves your issue.

**Comment by Praveen20K** [comment]
> @Praveen20K , could you please try this [pre-release binary](https://github.com/cypress-io/cypress/commit/38a65a6d7c04dff8e5663d9fee1b7df1b5828fb4#comments) that contains a few cookie fixes to see if it resolves your issue.

@mschile I tried to install the pre-release binary but I could see the token call is failing due to which the application is not loading. Screenshot for your reference.
![image](https://user-images.githubusercontent.com/58627337/218786524-30b53bbf-7844-4c58-8480-022759f8d234.png)

**Comment by jvereecken** [comment]
FYI: I had the exact same problem and was able to fix it by enabling chromeWebSecurity. When this property is set to false the Origin header is not sent which leads to Microsoft rejecting the token.

**Comment by Praveen20K** [comment]
> FYI: I had the exact same problem and was able to fix it by enabling chromeWebSecurity. When this property is set to false the Origin header is not sent which leads to Microsoft rejecting the token.

Thank you @jvereecken. It worked for me as well after I made the chromeWebSecurity to true and I have this pre-release binary fix https://github.com/cypress-io/cypress/commit/38a65a6d7c04dff8e5663d9fee1b7df1b5828fb4#comments in my package.json. Now I don't see the token call failure and the application is loading.
CC: @mschile @AtofStryker

**Comment by jvereecken** [comment]
@Praveen20K Glad it worked for you too! I'm also running the latest version of Cypress (12.6.0) so you don't have to be on the pre-release version ;)

**Comment by w4dd325** [comment]
@jvereecken that fixed my issue thanks for the detail!
