### ISSUE TITLE
cypress fails on ubuntu 20.04 under WSL 2 with Windows 11 when no X server

### ISSUE THREAD

**Issue by alexpmay** [cypress-io/cypress#25200]
### Current behavior

A fresh project with only cypress will fail when running under WSL/Windows 11 and no X server. The error is:

> The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
>
>Please search Cypress documentation for possible solutions:
>
>https://on.cypress.io
>
>Check if there is a GitHub issue describing this crash:
>
>https://github.com/cypress-io/cypress/issues
>
>Consider opening a new issue.

I tried on several version of cypress (all failed). The end of the debug log from version 10.1 looked interesting 

> (EE) Backtrace:
>
>2022-12-16T20:48:43.065Z cypress:xvfb (EE) 0: Xvfb (OsLookupColor+0x13c) [0x556b0450e17c]
>
>2022-12-16T20:48:43.065Z cypress:xvfb (EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x60) [0x7f9a03ce3420]
>
>2022-12-16T20:48:43.066Z cypress:xvfb (EE) 2: >/usr/lib/wsl/drivers/nv_dispig.inf_amd64_ee20464bb4ac57f4/libnvwgf2umx.so (_ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initIPmEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeES9_S9_+0x8aed91) [0x7f99f9f8a581]
>
>2022-12-16T20:48:43.066Z cypress:xvfb (EE)
>(EE) Segmentation fault at address 0x7f99f8322000
>(EE)
>Fatal server error:
>(EE) Caught signal 11 (Segmentation fault). Server aborting
>(EE)

That said, I tried a few options with `xvfb-run`, and it didn't solve the issue. 

### Desired behavior

Cypress should successfully complete without an error

### Test code to reproduce

1. ssh into the ubuntu environment *without* X forwarding

2. 
```
mkdir test-dir
cd test-dir
npm init
npm install cypress
```

3. Create a spec file:

```
describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})
```

4. `npx cypress run'. 

It will fail about 90% of the time with the error above. It happens consistently for both me and my coworker.

Notes:
1. This did not occur under Windows 10
2. This does not occur when you SSH with X forwarding
3. I tried a few xvfb-run options with no success
4. I tried on various versions of cypress (various version of 12, 11, and 10) with no success.
5. I tried with node 18.12.1 and 16.15.0  with no success.

### Cypress Version

12.1.0

### Node version

18.12.1

### Operating System

Windows 11 Pro, OS Build 22621.963, Ubuntu 20.04, WSL 2

### Debug Logs

```shell
The logs are too long for github. I get:
> There was an error creating your issue: body is too long, body is too long (maximum is 65536 characters).

Happy to provided them some other way. The most interesting thing I saw in the 10.1 logs was:


(EE) Backtrace:

2022-12-16T21:10:17.004Z cypress:xvfb (EE) 0: Xvfb (OsLookupColor+0x13c) [0x555a934ab17c]

2022-12-16T21:10:17.004Z cypress:xvfb (EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x60) [0x7f8a3dbf3420]

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
```

In the 12.1 logs, I didn't see anything of note. When I ran this
`xvfb-run -al -e xerr.out --server-args="-screen 0 102x786x24" npx cypress run`

The xerr.out files was:

```
D3D12: Removing Device.
(EE)
(EE) Backtrace:
(EE) 0: Xvfb (OsLookupColor+0x13c) [0x562b2d79e17c]
(EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x60) [0x7fb60baee420]
(EE) 2: /usr/lib/wsl/drivers/nv_dispig.inf_amd64_ee20464bb4ac57f4/libnvwgf2umx.so (_ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initIPmEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeES9_S9_+0x8aed91) [0x7fb602246581]
(EE)
(EE) Segmentation fault at address 0x7fb6005de000
(EE)
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE)
```
```


### Other

_No response_

**Comment by alexpmay** [comment]
Another way to repo is to force cypress to run under Xvfb.

```
xvfb-run -a npx cypress run
```

**Comment by nagash77** [comment]
Hi @alexpmay , unfortunately WSL is not an officially supported environment.  Are you seeing the issue on native windows 11 or native ubuntu?

The [Cypress Discord](https://discord.gg/cypress) may have some folks who have worked through these same problems.  But currently we do not have plans to support WSL or WSL2.
