### ISSUE TITLE
UI logs don't collapse when only one test is run

### ISSUE THREAD

**Issue by adrianblynch** [cypress-io/cypress#25206]
### What would you like?

If a spec has only one test, the logs don't collapse. automatically:

<img width="748" alt="Screenshot 2022-12-18 at 18 06 00" src="https://user-images.githubusercontent.com/4160967/208312553-59d5a616-0099-4655-9884-c270b1314bba.png">

If there are more than one tests, they do:

<img width="765" alt="Screenshot 2022-12-18 at 18 07 57" src="https://user-images.githubusercontent.com/4160967/208312564-f6c553c8-29f4-435f-b2a0-1d4a7776adc6.png">

The examples above are simple cases but when the single test spec has more steps it bulks up the output and seeing a pass/fail is harder.

Single test specs should also automatically collapse.

### Why is this needed?

This change will make the output/UI more consistent regardless of tests in a spect.

A passing spec will be more obvious if the log output is collapsed the same as for multi-test specs.

**Comment by emilyrohrbough** [comment]
Hi @adrianblynch the behavior you are describe above where a single test is expanded to show the log details is intended behavior. It's meant to provide quick visibility and debugging when executing a single test case. This is particularly helpful when using `it.only` in large specs. 

I see you are finding it difficult to quickly determine if a test passed or failed. We have a few different visuals indicators in the report to try and quickly share this information. The easiest reference point for an overall view of total pass/fail is this:

![Image](https://user-images.githubusercontent.com/14099737/208786703-a8208e1a-d3be-4d73-b892-b8ae020ff49e.png)
