### ISSUE TITLE
[Next 13] [component testing] brackets in folder name breaks the test detection

### ISSUE THREAD

**Issue by raphaelbadia** [cypress-io/cypress#25221]
### Current behavior

In my new next 13 application, I have a folder that contains brackets.

```
/app
    [postId]
        Explainer.tsx
        Explainer.cy.tsx
```

Explainer.cy.tsx contains :

```
describe('ComponentName.cy.ts', () => {
  it('playground', () => {
    cy.mount(<Explanation />);
  });
});

```
The test file is detected perfectly :
<img width="585" alt="CleanShot 2022-12-20 at 11 19 17@2x" src="https://user-images.githubusercontent.com/1901628/208643452-1d2e3b9c-ebbd-442d-bcc1-6e66deae0723.png">

However when opening it I see this error :

<img width="461" alt="CleanShot 2022-12-20 at 11 19 46@2x" src="https://user-images.githubusercontent.com/1901628/208643637-14018e03-dfc3-416f-a7ea-270283fc5005.png">

### Desired behavior

When I remove the brackets, the test runs correctly : 

<img width="716" alt="CleanShot 2022-12-20 at 11 23 50@2x" src="https://user-images.githubusercontent.com/1901628/208644349-a4e530bf-8995-49d2-a58a-758115e6eb7e.png">

Having brackets in the filename should work the same way.

### Test code to reproduce

You can reproduce here https://github.com/raphaelbadia/cypress-brackets/tree/master/cypress/component

### Cypress Version

12.1.0

### Node version

v16.16.0

### Operating System

macOS 12.6

**Comment by mike-plummer** [comment]
@raphaelbadia Whoops 😬 Thanks for pointing that out! I'll have the team take a look

**Comment by mike-plummer** [comment]
This was previously reported under #24588, closing this as a duplicate. I'm working a fix under that issue
