### ISSUE TITLE
Problem with cy.contains(). It find two elements. It should find one

### ISSUE THREAD

**Issue by SkubisMilo** [cypress-io/cypress#25225]
### Current behavior

After update to Cypress 12.1.0 some tests stop working. The problem is with cy.contains(). 

Before this code: `cy.dataCy("OpenAddFormsButton.label").contains("Zadanie").click();` found only one element. Now it finds two elements: 
![Screenshot_154](https://user-images.githubusercontent.com/34268855/208680913-0b39642e-c812-45c3-9cca-3d51df0b4fa8.png)

### Desired behavior

In this situation it should find only element which contains only word "Zadanie" not "Zadanie Cykliczne" also. 

### Test code to reproduce

![Screenshot_154](https://user-images.githubusercontent.com/34268855/208681363-8a8a0182-f958-48a6-af70-35016967807e.png)

  it("adds new task", () => {
    cy.dataCy("OpenAddFormsButton.add").contains("Dodaj").click();
    cy.dataCy("OpenAddFormsButton.label").contains("Zadanie").click();
  });
![Screenshot_155](https://user-images.githubusercontent.com/34268855/208681676-d536fce1-aa1f-4442-82ce-d351fff49a70.png)

### Cypress Version

12.1.0

### Node version

16.14.2

### Operating System

Windows 11

**Comment by jmitchell-figure** [comment]
I have had to deal with contains finding multiple before so can't speak on why it was working for you previously, but a simple `.first()` or using regex will work https://docs.cypress.io/api/commands/contains#Syntax

**Comment by emilyrohrbough** [comment]
@SkubisMilo This appears to be a regression from 12.0.1 to 12.0.2. I was able to reproduce with the following example:
```js
    it('issue ', () => {
      cy.visit('https://example.cypress.io')
      cy.get('a').contains('next').click()
    })
```
In 12.0.1 - passes
In 12.0.2 - fails with `cy.click() can only be called on a single element. Your subject contained 3 elements. Pass { multiple: true } if you want to serially click each element.[Learn more](https://on.cypress.io/click)`

`.contains()` should be returning the first matched subject: https://docs.cypress.io/api/commands/contains#Only-the-first-matched-element-will-be-returned.

**Comment by BlueWinds** [comment]
Tracked this down - basically we're running into a problem when .contains() is passed multiple subjects that match the filter (but no child element of any of the subjects does).

Opened a PR to fix it, should go out in the next patch release.

**Comment by SkubisMilo** [comment]
@BlueWinds thanks for looking at this problem. I hope that your fix resolve this problem :).

**Comment by bondar-artem** [comment]
I have also had problems because of this issue. Hoping for the fix to be released soon.
