### ISSUE TITLE
Unable to run the Code Coverage Report with cypress 9.7.0 & cucumber

### ISSUE THREAD

**Issue by anchalbhanwala** [cypress-io/cypress#25223]
### Current behavior

I am unable to generate the coverage report data in cypress(9.7.0) . As suggested in the cypress docs & git [https://github.com/cypress-io/code-coverage](url) , i have updated the index files , support files but on running the command
npx nyc report --reporter=text-summary , i see below 
![image](https://user-images.githubusercontent.com/85665536/208665383-516753dc-d722-4da6-b6e1-ca1fea55a9e7.png)

The code is compiled successfully , test runs as expected but the coverage report shows unknown.

### Desired behavior

The coverage report should fetch the data received on running the test and should show the report.

### Test code to reproduce

**cypress > support > index.js**
_import '@cypress/code-coverage/support';_

**cypress > plugins > index.js**
_module.exports = (on, config) => {
  require('@cypress/code-coverage/task')(on, config)

  // add other tasks to be registered here

  // IMPORTANT to return the config object
  // with the any changed environment variables
  return config
}_

command using to run the test
For compilation - ng serve
To run test as below
 "test": "npm run cy:test2 || npm run deletexml && npm run posttest ",
 "cy:test2": "npx cypress run --headed --spec 'cypress/integration/features/*.feature' ",
"posttest": "allure generate allure-results --clean -o allure-report && allure open",

### Cypress Version

9.7.0

### Node version

v16.14.2

### Operating System

windows 10

**Comment by lmiller1990** [comment]
What version of the code-coverage and the cucumber plugin are you on? 

- v2 -> Cypress 9.x
- v3 -> Cypress 10.x

Please share your `package.json` so I can ensure I'm using the same version of dependencies as you are. A minimal reproduction would help speed up debugging, so if you could include a repo, that'd be great, too.

**Comment by anchalbhanwala** [comment]
Hi , i am using 
v2 -> Cypress 9.7.0
 "cypress-cucumber-preprocessor": "^4.3.1"
Package.json
![image](https://user-images.githubusercontent.com/85665536/209277647-024ba88c-6230-4233-9460-2d9d7595419a.png)
![image](https://user-images.githubusercontent.com/85665536/209277698-602991ef-0825-4c9c-955a-1ca0c4968806.png)
![image](https://user-images.githubusercontent.com/85665536/209277764-e78a102a-791e-4cc8-91b4-b9b201d12e6a.png)

I cannot share the repo as its organizations repo , but sharing the folder structure that i am using. I am using Cypress-Cucumber framework .
![image](https://user-images.githubusercontent.com/85665536/209279306-72331497-e7e6-4f74-ba2a-e9725a895c57.png)

**Comment by lmiller1990** [comment]
I'm not sure if you can, but updating to Cy 12 and the new version of the cucumber plugin (v15) [find here](
https://github.com/badeball/cypress-cucumber-preprocessor) might help.

If you can't, check this issue: https://github.com/badeball/cypress-cucumber-preprocessor/issues/198. Someone else had a similar problem. 

Try seeing what they did. If you can't get it working in a fresh repo, please upload the repo anyway, and I can take a look. I don't have the bandwidth to create a minimal reproduction for a third party plugin right now, but if you can put one together, I can take a look. Thanks!

**Comment by astone123** [comment]
@anchalbhanwala were you able to try upgrading to Cypress 12 and cucumber plugin v15? Also, like Lachlan said, a repo would help us debug. Thanks

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
