### ISSUE TITLE
Auth Token from local storage is restored in cy.session

### ISSUE THREAD

**Issue by kiran4coachhub** [cypress-io/cypress#25232]
### Current behavior

With the new cy.session() command, All keys are not getting restored in the window to resume testing as a user. In the screenshots attached below, we can see that the browser uses a token key to make API calls. It is being set into the browser's local storage when the session is created but during the session is restored for another test case, The token key is missing from the local storage. Hence, I am unable to land on the required URL. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/108738432/208720798-7e9e078d-8a1a-484a-95bd-ca853750e06c.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/108738432/208720858-382a20e5-50d8-4d3c-ae9f-f8c085228cc2.png">

### Desired behavior

As explained by the documentation, Cypress should restore all the key values as present in the local storage of window/browser

### Test code to reproduce
```
Cypress.Commands.add("improvedLogin", (email: string, password: string) => {
  cy.session(
    email,
    () => {
      cy.visit("/");
cy.get("#username").type(email, { log: false });
    cy.contains("Continue").click();
    cy.get("#password").type(password, { log: false });
    cy.contains("Continue").click();
    }
  );
});

Cypress.Commands.add("loginAsCoachee", () => {
  cy.improvedLogin(users.validCoacheeEmail, env.validCoacheePassword);
});

it("Some test", () => {
    cy.loginAsCoachee();
    cy.visit("/coachee/line-manager"); })

it("Some test", () => {
    cy.loginAsCoachee();
    cy.visit("/coachee/profile"); })
```
### Cypress Version

12.1.0

### Node version

v18.3.0

### Operating System

macOS 12.6

**Comment by emilyrohrbough** [comment]
@kiran4coachhub Hello! Sorry to hear you are having unexpected results when using `cy.session()`. I took a look at the code you provided and it's likely that the command is finishing and saving the session data prematurely before you application as actually finished applying the local storage values to the page. Once the command ends, the current session data will be persisted.

This is where the validate function is super helpful for ensure the session has been fully established before saving the session data and moving on.

```diff
  cy.session(
    email,
    () => {
      cy.visit("/");
cy.get("#username").type(email, { log: false });
    cy.contains("Continue").click();
    cy.get("#password").type(password, { log: false });
    cy.contains("Continue").click();
    },
+  {
+    validate() {
+      cy.window().its('localStorage', { timeout: 5000 }).should('have.property', nameOfStorageItem)
+   }
  );
```
I recommend using the validate callback so the session can be recreated if for whatever the data is corrupt and/or the validation logic fails when re-using the session later on. If you'd prefer to only use a setup function, those lines can be added after `cy.contains('Continue').click()`.

This is something that we need to expand on in our documentation as it seems to be the most common "gottchya" with `cy.session()`. Theres a small section covering this behavior but it's easily missed...

Please give this a try and see if this resolves your issue.

**Comment by kiran4coachhub** [comment]
Thanks for the response, I will check this and let you know if I face any issues. I will close it with a comment if I don't find any issue.

**Comment by kiran4coachhub** [comment]
This is working now, Thanks for the resolution.

**Comment by HJK181** [comment]
@emilyrohrbough I've tried to validate a localStorage key as well, but this fails because Cypress navigates to the Default About Page before every test to clear the session state:

Cypress version: ^14.2.1

custom command:
```
Cypress.Commands.add("kcLogin", ({ email }) => {
  cy.session(
    email,
    () => {
      cy.intercept(/\/uaa\/api\/user\/authenticate/)
        .as("authenticate")
        .intercept(/\/uaa\/api\/user\/account/)
        .as("account")
        .visit("/")
        .url()
        .should("contain", ":9080")
        .get("#username")
        .clear()
        .type(email)
        .get("#password")
        .clear()
        .type("password")
        .get("#kc-login")
        .click()
        .wait(["@authenticate", "@account"])
        .url()
        .should("contain", ":8080")
        .window()
        .then((win) => {
          console.error("e2e: saving localstorage on domain", win.location);
          win.localStorage.setItem("langKey", "de");
        });
    },
    {
      cacheAcrossSpecs: false,
      validate: () => {
        cy.window().then((win) => {
          console.error("e2e: validating localstorage on domain", win.location);
          const item = win.localStorage.getItem("langKey");
          console.error("e2e: langKey from localstorage", item);
          if (!item) return false;
        });
      },
    },
  );
});
```
This results in a failed validation and a session recreation on every test.

![Image](https://github.com/user-attachments/assets/d8fc2acb-48a4-485e-a8e5-e88d8da129af)

Any tips? I could check for the `win.location.pathname` in my validate function, but this just disabled the whole validation process as Cypress doesn't call the function after leaving the about page.

**Comment by HJK181** [comment]
@mschile CC because I saw you fixed https://github.com/cypress-io/cypress/pull/30864 :)

**Comment by jennifer-shehane** [comment]
@HJK181 I'm not sure that PR would fix your issue here - that issue we fixed was where Cypress would hang. Perhaps check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by HJK181** [comment]
I'm not a Discord user. I just noticed that the accepted workaround for this issue behaves strangely and doesn't seem applicable. Should I create a new issue from my post?
