### ISSUE TITLE
cypress not work in docker node:current-alpine

### ISSUE THREAD

**Issue by andresgarcia0313** [cypress-io/cypress#25236]
### Current behavior

docker show:
web:/usr/src/app# npm install cypress@12.0.2 --save
npm ERR! code 1
npm ERR! path /usr/src/app/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c -- node index.js --exec install
npm ERR! Cypress cannot write to the cache directory due to file permissions
npm ERR! 
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Failed to access /root/.cache/Cypress:
npm ERR! 
npm ERR! EACCES: permission denied, mkdir '/root/.cache/Cypress'
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Platform: linux-x64 (Alpine Linux - 3.17.0)
npm ERR! Cypress Version: 12.0.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-20T18_46_31_703Z-debug-0.log
web:/usr/src/app# whoami
root

### Test code to reproduce

FROM node:current-alpine
RUN apk add --no-cache bash 
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 80
CMD [ "/bin/bash"]

### Cypress Version

12.0.2

### Node version

19.2.0

### Operating System

alpine 3.17

**Comment by lmiller1990** [comment]
Hi!

We have this line in our Dockerfiles: https://github.com/cypress-io/cypress-docker-images/blob/master/included/10.0.0/Dockerfile#L18-L20

Can you give that a try?

**Comment by astone123** [comment]
@andresgarcia0313 were you able to try what Lachlan suggested above?

**Comment by lmiller1990** [comment]
Let us know how you go @andresgarcia0313 - if that doesn't work, we can explore some other options. Cypress should work on any standard linux distro (like alpine) with the right dependencies.

If this didn't solve your problem, let us know and we will reopen.

**Comment by damianobarbati** [comment]
@lmiller1990 is there a way today to run cypress on alpine? I didn't get your reference to this line <https://github.com/cypress-io/cypress-docker-images/blob/master/included/10.0.0/Dockerfile#L18-L20>

Thanks.

**Comment by lmiller1990** [comment]
I think that the error "npm ERR! EACCES: permission denied, mkdir '/root/.cache/Cypress'" can be addressed by setting `  CYPRESS_CACHE_FOLDER=/root/.cache/Cypress \`, is what I meant.
