### ISSUE TITLE
Release command log items in run mode

### ISSUE THREAD

**Issue by mschile** [cypress-io/cypress#25230]
### What would you like?

In headless run mode, the command log cannot be interacted with, as such, the logs in the command log do not need to be retained and can be released. See this [comment](https://github.com/cypress-io/cypress/issues/23391#issuecomment-1357904950) for additional details.

### Why is this needed?

Don't unnecessarily consume memory.

**Comment by hegeds** [comment]
Hey,
just curious what are the plans for this? I'm just wondering, because from my perspective it would be great, if the number of retained commands would be user configurable 🤔

**Comment by mschile** [comment]
Hi @hegeds 👋, my plan is to remove the logs from the reporter for any successful tests in `run` mode. In this context, I'm not sure there will be a lot of benefit to have the number of retained commands to be user configurable. That may be something to consider for `open` mode though.

**Comment by hegeds** [comment]
oh I see, this can be a major improvement in suites where there are multiple quick test cases! However we also have quite a few longer test cases, where we have OOM crashes. This is why I would be interested in a solution, where one could set that only the last x number of logs are kept even in headless mode

**Comment by mschile** [comment]
Thanks for the clarification @hegeds. We are hopefully releasing this change today. If you are still receiving OOM crashes after updating, could you please log a new [memory issue](https://github.com/cypress-io/cypress/issues/new?assignees=&labels=&template=2-memory-issue.yml). We have discussed single tests that consume large amounts of memory but we would like some more metrics before we make any changes.
