### ISSUE TITLE
Automatic spec-pattern behaviour

### ISSUE THREAD

**Issue by Shaegi** [cypress-io/cypress#25243]
### Current behavior

Following https://github.com/cypress-io/cypress/discussions/25126#discussioncomment-4463552

Current component testing documentation states: 
**Note that any files found matching the e2e.specPattern value will be automatically excluded.** (ref: https://docs.cypress.io/guides/references/configuration#component) 

In my case I have a pretty global pattern for my e2e tests since I'm working in a monorepo which has some performance issues with too specific glob patterns. Therefore I wanted to exclude component specPatterns via ```excludeSpecPattern```-config, but it seems like automatic exclusion doesn't respect ```excludeSpecPattern```.

To be more precise my e2e-config is the following: 
``` 
    specPattern: '**/*.cy.{js,jsx,ts,tsx,feature,features}',
    excludeSpecPattern: [
      '**/node_modules/**',
       '**/components/**'
    ]
```

my component-config is the following: 
```
specPattern: '**/*.cy.{js,jsx,ts,tsx,feature,features}'
excludeSpecPattern: [
  '**/node_modules/**',
   '**/e2e/**'
]
```

But in component testing it won't find any tests because of the current behaviour.

`glob`-Search with `**/e2e/**/*.cy.{js,jsx,ts,tsx,feature,features}` takes around 12s  in my case.
`glob`-Search with `**/*.cy.{js,jsx,ts,tsx,feature,features}` takes around 2s in my case.

### Desired behavior

- Only tests which are found in the combination of `specPattern` and `excludeSpecPattern`  of e2e should be exluded in component-Testing
- To be more consistent I'd suggest that e2e should also not display any tests which are found by the combination of `specpattern` and  `exludeSpecPattern` of component testing 

### Test code to reproduce

```javascript
e2e: {
  specPattern: '**/*.cy.{js,jsx,ts,tsx,feature,features}'
  excludeSpecPattern: [
    '**/node_modules/**',
     '**/e2e/**'
  ]
},
components: {
  specPattern: '**/*.cy.{js,jsx,ts,tsx,feature,features}'
  excludeSpecPattern: [
    '**/node_modules/**',
     '**/components/**'
  ]
}
```

### Cypress Version

11.0.0

### Node version

16.14.2

### Operating System

Windows 10

**Comment by emilyrohrbough** [comment]
@Shaegi Are you asking for this request purely for a performance improvement or is there another reason you want to share the specPatterns between component and e2e testing?

**Comment by Shaegi** [comment]
My original problem is performance but not within cypress but within [@badeball/cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) which is using the `specPattern` config in combination with `excludeSpecPattern`. 
Its still confusing to me that `excldueSpecPattern` doesn't have any effect on automatic exclusion of e2e-Tests in component-tests which is why I opened this ticket. 
With these patterns and a structure like that: 

/tests/e2e/foo.cy.ts
/tests/components/bar.cy.ts

the second test is not showing up in either testing modes.

**Comment by emilyrohrbough** [comment]
@Shaegi Can you confirm your configuration? You provided two versions of your configuration...If it is the following,
```js
e2: {
    specPattern: '**/*.cy.{js,jsx,ts,tsx,feature,features}',
    excludeSpecPattern: [
      '**/node_modules/**',
       '**/components/**'
    ]
},
component: {
	specPattern: '**/*.cy.{js,jsx,ts,tsx,feature,features}'
	excludeSpecPattern: [
	  '**/node_modules/**',
	   '**/e2e/**'
	]
}
```
That explains why `/tests/components/bar.cy.ts` doesn't show up in your spec list for either case.
- e2e tests, the exclude pattern filters it out with this pattern: `'**/components/**'
- component tests always adds the e2e spec pattern as the exclude pattern , so the full exclude pattern applied is:
```js
	excludeSpecPattern: [
      '**/*.cy.{js,jsx,ts,tsx,feature,features}',
	  '**/node_modules/**',
	   '**/e2e/**'
	]
```
so in your case, no component tests will be picked up because it's using the same spec pattern as e2e.

**Comment by Shaegi** [comment]
`component tests always adds the e2e spec pattern as the exclude pattern , so the full exclude pattern applied is:`

Thats exactly the confusing part. I'd suggest that only tests that are found in combination of `specPattern` and `excludeSpecPattern` of e2e are exluded in compontent-testing and vice versa. 
It's kinda missleading that only `specPattern` has effect on automatic exclusion and `exludeSpecPattern` has no effect.
