### ISSUE TITLE
Cypress is no loading after migration from 9.7 to 12

### ISSUE THREAD

**Issue by YagoCastroWorks** [cypress-io/cypress#25252]
### Current behavior

Hello, I'm trying to migrate to Cypress 12, but I'm having difficulties, I work with different environments, so I was using this strategy (https://docs.cypress.io/api/plugins/configuration-api#Switch-between-multiple-configuration-files) to deal with it, however this no longer works for this new version, could someone help me? in addition i also use two plugins (Cucumber(https://github.com/badeball/cypress-cucumber-preprocessor) and Grep (https://github.com/cypress-io/cypress/tree/develop/npm/grep ) ) 

When i try to open Cypress (screen below) it keep loading 
![image](https://user-images.githubusercontent.com/61571471/209138219-e2c6ed7d-65a0-4f32-91a1-ac63570ee442.png)

im not sure why it is happening, so im sharing (img below) my config.js
![image](https://user-images.githubusercontent.com/61571471/209138746-011420fe-bdcb-46d3-abd8-a614d9a88d4a.png)

Thanks

### Desired behavior

I'd like to keep working with multiple config envFiles using Cucumber and Grep

### Test code to reproduce

```
import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

async function setupNodeEvents(on, config) {

  require('@cypress/grep/src/plugin')(config)

  const fs = require('fs-extra');
  const path = require('path');
  function getConfigurationByFile(file) {
    const pathToConfigFile = path.resolve(
      path.join('../..', 'web-ui/cypress/envFiles', `${file}.json`)
      );
     return fs.readJson(pathToConfigFile);
  }
  const file = config.env.fileConfig || 'SaaS';
  getConfigurationByFile(file);
   
  await addCucumberPreprocessorPlugin(on, config);
  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );
  return config;
}

module.exports = defineConfig({
  video: false,
  requestTimeout: 100000,
  numTestsKeptInMemory: 0,
  defaultCommandTimeout: 100000,
  pageLoadTimeout: 100000,
  viewportWidth: 1920,
  viewportHeight: 1080,
  reporter: 'junit',
  reporterOptions: {
    mochaFile: 'cypress/results/results-[hash].xml',
    toConsole: true,
  },
  e2e: {
    setupNodeEvents,
    specPattern: ["**/*.feature", "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}"]
  }
})
```

### Cypress Version

12.2.0

### Node version

16.13.2

### Operating System

Windows 10

**Comment by lmiller1990** [comment]
Hi! Can you run with `DEBUG=cypress:* npx cypress open` and share the logs in the terminal (there will be a lot). This will help with debugging.

Another thing I'd try is removing those two plugins from your `cypress.config.js`, one by one, and see if either one of those is responsible for the problem. That would greatly reduce the surface area and help isolate the issue.

One thing that might be of interest is the `path.join(...)` call you do. Previously plugins where in `cypress/plugins/index.js`, but now it's at the top level in `cypress.config.js`. I wonder if that path needs to be adjusted?

**Comment by YagoCastroWorks** [comment]
@lmiller1990 tks for helping!

So, after some tries Cypress worked, i reinstalled all plugins again, but apparently what is causing the crashes is my env configuration, in the previous version it works fine, i use this envFiles to overwrite the config.json, but for this new version i really dont know how handle this.

[logcy12.txt](https://github.com/cypress-io/cypress/files/10303651/logcy12.txt)
[saas.txt](https://github.com/cypress-io/cypress/files/10303636/saas.txt)
![image](https://user-images.githubusercontent.com/61571471/209553194-fbbd3f85-d387-4381-bc50-ffe6f588cdd1.png)

**Comment by lmiller1990** [comment]
The error log has

```
cypress:lifecycle:child:run_require_async_child:18112 unhandled rejection: [Error: ENOENT: no such file or directory, open 'C:\Users\W00112631\Desktop\TestingCypress12\web-ui\cypress\envFiles\SaaS.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\W00112631\\Desktop\\TestingCypress12\\web-ui\\cypress\\envFiles\\SaaS.json'
} +301ms
  cypress:lifecycle:ProjectConfigIpc unhandled error in child process {
  name: 'Error',
  message: "ENOENT: no such file or directory, open 'C:\\Users\\W00112631\\Desktop\\TestingCypress12\\web-ui\\cypress\\envFiles\\SaaS.json'",
  stack: "Error: ENOENT: no such file or directory, open 'C:\\Users\\W00112631\\Desktop\\TestingCypress12\\web-ui\\cypress\\envFiles\\SaaS.json'",
  code: 'ENOENT'
} +9s
```

Looking at your config:

```
path.join('../..', 'web-ui/cypress/envFiles', ${file}.json)
```

I think the path is not correct post-migration. I guess this code was originally in `cypress/plugins` but now it's at the top level. Should this be `path.join('cypress', 'envFiles', ${file}.json)` or something along those lines?

**Comment by YagoCastroWorks** [comment]
@lmiller1990 tks again! using this (path.join('cypress', 'envFiles', ${file}.json)) the Cypress found the correct path, but it is not overwriting the configuration as it used to.
I`m sharing the new log.
[logCy12_1.txt](https://github.com/cypress-io/cypress/files/10305456/logCy12_1.txt)

**Comment by lmiller1990** [comment]
I must be missing something. What is supposed to happen?

Looking at your code:

```js
  function getConfigurationByFile(file) {
    const pathToConfigFile = path.resolve(
      path.join('../..', 'web-ui/cypress/envFiles', `${file}.json`)
      );
     return fs.readJson(pathToConfigFile);
  }
  const file = config.env.fileConfig || 'SaaS';
  getConfigurationByFile(file);
```

You call `getConfigurationByFile(file);` but it doesn't assign anything. That line doesn't do anything. 

This whole block is effectively a no-op. `file` is assigned to but never actually used. It doesn't look like it does anything. What's it supposed to do?

**Comment by YagoCastroWorks** [comment]
Hmm, you're correct, getConfig should be a return, but i cant do it on this setupNodeEvents, right? because its is returning Config.

Once the fileConfig variable is set, i need the Cypress fetch environment variables from as well as the baseURL

**Comment by lmiller1990** [comment]
You can modify `config` in a few ways.

```js
setupNodeEvents (on, config) {
  config.viewportWidth = 1000
  return config
}
```

All you need to do is modify `config` however you like, and return the new value.

**Comment by YagoCastroWorks** [comment]
yes, but the problem is that all my environment settings are inside JSON files, separated by environments, something like

cypress/envFiles/envA.json
cypress/envFiles/envB.json

each with its particularities, such as baseURL, apiURL.

So, i was using this "plugin" to fetch the envFiles to Config

`function getConfigurationByFile(file) {
    const pathToConfigFile = path.resolve(
      path.join('../..', 'web-ui/cypress/envFiles', `${file}.json`)
      );
     return fs.readJson(pathToConfigFile);
  }
  const file = config.env.fileConfig || 'SaaS';
  getConfigurationByFile(file);`

But now its not working, so do you think this stratagy is no longer supported on this new Cypress version? And if it works, i really dont know how to do it :/

**Comment by YagoCastroWorks** [comment]
@lmiller1990 
Solved!
I followed yout comment and managed to apply the following solution?

`config.baseUrl=envConfig.baseUrl
  config.env={
    ...envConfig.env
  }`

With this solution all env configuration was applied!

Tks a lot!
