### ISSUE TITLE
Cypress 12 fails to correctly process cookie headers

### ISSUE THREAD

**Issue by Bertg** [cypress-io/cypress#25253]
### Current behavior

Because this is a multi-request issue, involving browser state, headers etc... I have created a miro board to explain the issue more visually: https://miro.com/app/board/uXjVP3EbcAE=/?share_link_id=414736048106 

In text form:

During a specific test run I can pin-point a request where `Set-Cookie` headers are not (completely) being processed. In subsequent requests the value of this cookie is now an unexplainable value. I verified in the test run if the cookie has had that value before, which it hadn't.

These tests worked as expected in the last version of Cypress 11.

### Desired behavior

Cypress 12 should correctly parse and manage its cookies.

### Test code to reproduce

Test suite is to extensive, and bound to our proprietary code that reproducing this is a very big ask.

### Cypress Version

12.1.0.1980487

### Node version

v16.18.1

### Operating System

macOS 13.0.1 (22A400)

### Debug Logs

```shell
To long to provide
```

### Other

This is most likely related to #25174 (visible in miro board as well) #25205 #25247

**Comment by emilyrohrbough** [comment]
@Bertg I understand your code is proprietary, but small reproducible example (at least pseudo code) of what you are seeing will be needed to dig in to reproduce. There's not enough information from your screenshots to fully understand what is happening vs what is expected.

**Comment by Bertg** [comment]
@emilyrohrbough I'm not sure what I could provide in more detail?
I can produce an exact sequence of HTTP requests + their responses, with the associated cypress commands... would that suffice?

However, I think the screenshots are very clear that there is a race condition in how Cypress 12 handles cookies. Dropping a cookie and replacing it with a "random" value is a clear indication of an issue. All to the facts hat cookies for invalid domains show up (starting with a `.` see #21574) is further evidence of this issue.

**Comment by emilyrohrbough** [comment]
@Bertg Yes, providing the request with the associated test code would be helpful to try & understand what you are seeing and possible create a reproduction on our end. As it is, I am not sure what test code your miro board diagram might be representing or if this is just your application's requests.

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering and we will re-open this issue.

**Comment by Bertg** [comment]
This issue got resolved with [12.7.0](https://on.cypress.io/changelog#12-7-0).

As expected it was related to the cookie related issues that got fixed in that release.
