### ISSUE TITLE
cy.screenshot() is saving the image direct in screenshot folder

### ISSUE THREAD

**Issue by pehguerra** [cypress-io/cypress#25258]
### Current behavior

Using cy.screenshot() with npx cypress open or npx cypress run, the image is being saved in the root folder screenshot.

```
// cypress/e2e/testScreenshot.cy.js

describe('my tests', () => {
  it('takes a screenshot', () => {
    cy.visit('https://example.cypress.io')

    // cypress/screenshots/test.png
    cy.screenshot('test')
  })
})
```

### Desired behavior

The picture should be saved inside a folder that contains the same name of the spec file

Example:

```
// cypress/e2e/testScreenshot.cy.js

describe('my tests', () => {
  it('takes a screenshot', () => {
    cy.visit('https://example.cypress.io')

    // cypress/screenshots/testScreenshot.cy.js/test.png
    cy.screenshot('test')
  })
})
```

### Test code to reproduce

```
describe('my tests', () => {
  it('takes a screenshot', () => {
    cy.visit('https://example.cypress.io')
    cy.screenshot('test')
  })
})
```

### Cypress Version

12.2.0

### Node version

17.3.0

### Operating System

Windows 10 Pro 22H2

**Comment by emilyrohrbough** [comment]
@pehguerra In Cypress 10.0.0 an update was made to how screenshot paths are determined. The paths of generated files inside both the video and screenshot folder will be stripped of any common ancestor paths shared between spec files found by the specPattern option and may no longer be deterministic.  This change was made in [#19319](https://github.com/cypress-io/cypress/pull/19319). So you will likely see different screenshot paths in open mode vs run mode. This can be a bit unexpected but it is the current behavior. 

You might explore the [After Screenshot API](https://docs.cypress.io/api/plugins/after-screenshot-api#Modify-screenshot-path) to modify the screenshot path set a deterministic screenshot path.

**Comment by emilyrohrbough** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/24052
