### ISSUE TITLE
Why does FollowRedirect does not work

### ISSUE THREAD

**Issue by pi3natt** [cypress-io/cypress#25269]
### Current behavior

The FollowRedirect optional does not work as expected, It should get the 30x response instead of 20x ,But not so sure how does it work.
<img width="1252" alt="Screen Shot 2565-12-26 at 11 19 46" src="https://user-images.githubusercontent.com/51312768/209527604-d3137e39-fb6e-4067-a0a0-1951ad29534a.png">

### Desired behavior
Deny to automatically follow redirects when FollowRedirect set as false

### Test code to reproduce
```

  await new Promise((resolve, reject) => {
    cy.request({
      method: 'GET',
      url: `${loginServer}/oauth2/auth?`,
      qs: params,
      followRedirect: false
    }).then((response) => {
      const login_challenge = response.headers.location.split('login_challenge=')[1]
      storeCookie(response.headers['set-cookie'])
      resolve(login_challenge)
    })
  }).then((resolve) => {
    loginChallenge = resolve
  })

  await new Promise((resolve, reject) => {
    cy.request({
      method: 'PUT',
      url: `${authServer}/oauth2/auth/requests/login/accept?login_challenge=${loginChallenge}`,
      followRedirect: false,
      body: JSON.stringify({
        subject: userID
      })
    }).then((response) => {
      console.log(response)
      resolve(response.data.redirect_to)
    })
  }).then((resolve) => {
    redirectURL = resolve
  })

```
### Cypress Version

v11.1.0

### Node version

v16.15.0

### Operating System

macOS 12.4

### Debug Logs
<img width="936" alt="Screen Shot 2565-12-26 at 16 55 13" src="https://user-images.githubusercontent.com/51312768/209535901-f6153084-6045-4d22-81dc-4f68d5e222fd.png">

**Comment by lmiller1990** [comment]
If you have a minimal server with OAuth2 setup I could clone, that'd be really useful too. Is that something you can share? In the meantime, I will try and make one.

Another question: what is the end goal for this test? Can you share your use case? There might be a better way. You can use `cy.origin` to authenticate using a standard browser workflow for most providers. [`cy.origin()`](https://docs.cypress.io/api/commands/origin). This might be a better fit for your use case.

**Comment by lmiller1990** [comment]
Also, do you have a minimal server implementation for your OAuth2 workflow? I tried making one locally but it's quite a bit of work to reproduce. Do you know of any templates or minimal apps I could run locally to reproduce your exact error?

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
