### ISSUE TITLE
CypressError: This session already exists

### ISSUE THREAD

**Issue by Floriferous** [cypress-io/cypress#25272]
### Current behavior

I'm trying really hard to make cy.session work for us, but it seems like I'm running into some weird issues.

Every now and then, cypress starts to fail with the following error:

```
CypressError: This session already exists. You may not create a new session with a previously used identifier. If you want to create a new session with a different validate function, please call cy.session() with a unique identifier other than *admin*.
```

Once this error appears, it will keep failing everytime `cy.session()` is called. There is no way out of it except by closing google chrome, and restarting it.

### Desired behavior

Except if I misunderstood how sessions work, a cy.session() should never fail like this, as it is _always_ either `created` or `restored` if it already exists. It should not be possible for cypress to try to create it twice..?

If this scenario can happen for some reason, then it should be able to restore it, as it quite literally says the session already exists.

### Test code to reproduce

<details><summary>Here is the entire test suite</summary>

```js
import { ADMIN_EMAIL, USER_PASSWORD } from '../e2eConstants';

const visitAndWaitToBeReady = url => {
  cy.visit(url);
  cy.window().should('have.property', 'appReady', true);
  cy.checkConnection();
};

describe('Cypress setup', () => {
  before(() => {
   visitAndWaitToBeReady('/setupTest');
    cy.callMethod('resetDatabase');
    cy.callMethod('generateScenario', {
      scenario: {
        users: [
          {
            _id: 'advisor1',
            emails: [{ address: ADMIN_EMAIL, verified: true }],
          },
        ],
      },
    });
    cy.callMethod('setPassword', {
      userId: 'advisor1',
      password: USER_PASSWORD,
    });
    cy.callMethod('checkUser');
  });

  beforeEach(() => {
    cy.session(
      'admin',
      () => {
        visitAndWaitToBeReady('/login');
        cy.meteorLogin(ADMIN_EMAIL, USER_PASSWORD);
      },
      {
        cacheAcrossSpecs: true,
        validate() {
          cy.window().then(win => {
            const loginToken = win.localStorage.getItem('Meteor.loginToken');
            return !!loginToken;
          });
        },
      },
    );
    visitAndWaitToBeReady('/');
  });

  it('logs in and saves the session', () => {
    cy.routeTo('/loans');
    cy.contains('Loans');
  });

  it('is already logged in', () => {
    cy.routeTo('/users');
    cy.contains('Accounts');
  });
});

```
</details>

### Cypress Version

12.2.0

### Node version

14.21.1

### Operating System

macOS 12.6

**Comment by Floriferous** [comment]
Alright, it seems like the issue comes from the runner caching sessions across spec reruns, as explained in the docs. Our server generates new random login tokens for every re-run as we clean our database, so this feature isn't useful to us anyways.

There doesn't seem to be an official way to disable this, but the following trick did it:

```js
beforeEach(() => {
  // cy.id is a different string for every spec rerun, so it will always create a new session in the first beforeEach hook.
  cy.session([sessionName, cy.id], () => {});
});
```

**Comment by emilyrohrbough** [comment]
@Floriferous A few options would be to remove `cacheAcrossSpecs: true` if the database is resetting before each spec. You can also leverage [`Cypress.session.clearAllSessionData()`](https://docs.cypress.io/api/cypress-api/session#Examples) to "reset" the stored sessions. It wouldn't be useful for caching across specs or re-runs but would enable re-using a session in a long spec.

Just curious, is there more to your validate function that you shared? Not seeing where the re-generated token is being pulled in and used here.

**Comment by chrisbreiding** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by bubafinder** [comment]
The same thing happened to me today. All worked as expected, and once it was throwing this error constantly. After I used `Cypress.session.clearAllSavedSessions()` it works again. I will remove `cacheAcrossSpecs: true` and see if I will see this issue again.

**Comment by DanielMateosLab** [comment]
I had this error when using a command with a session, like this:
```
Cypress.Commands.add("login", () => {
  cy.session("jhonnydeep@gmail.sup", loginFn, {
    cacheAcrossSpecs: true,
  });
});
```
If I update `loginFn` after running the tests, I get the aforementioned error. Surprisingly, if I undo the changes, the error disappears. Also, restarting cypress solves the error. 
Maybe it's related to how cypress handles sessions under the hood and maybe to some Hot Module Replacement stuff.

**Comment by begrs** [comment]
[Floriferous](https://github.com/Floriferous) answer, using cy.id as part of the session key, works wonders. disabling cacheAcrossSpecs did not work for us.

Please add cy.id to session keys by default in cypress itself. This issue is 2 years old, everyone working with sessions will stumble on it eventually and the fix is literally just to add cy.id in the cy.session commands original code.
