### ISSUE TITLE
Upgrade mocha to latest version

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2528]
We currently use [a forked version of mocha at 2.5.3](https://github.com/cypress-io/mocha/blob/58f6eac05e664fc6b69aa9fba70f1f6b5531a900/package.json#L3). Upgrade to the latest version, 5.2.0.

**Comment by pvdyck** [comment]
@bahmutov ready for Sprint 5 or postpone ?

**Comment by jennifer-shehane** [comment]
@chrisbreiding Is this going to be a breaking change? 4.0? or?

**Comment by chrisbreiding** [comment]
Yes, I'd say it's a breaking change.

**Comment by chrisbreiding** [comment]
The code for this is complete, but has not yet been released. It will be released in [4.0](https://github.com/cypress-io/cypress/pull/2880).

**Comment by calvinballing** [comment]
Note that an additional issue that this will solve is that '.only' currently works based on string matching, so if multiple tests have the same description, they both run if .only is applied to only one.   The same occurs if you have multiple tests that share the same starting description. If the first is called 'Admin' and the second is called 'Admin - Page 2', then applying only to the first will cause both to run.  Mocha stopped using string matching in v3 https://mochajs.org/

**Comment by dwelle** [comment]
@calvinballing yep, see https://github.com/cypress-io/cypress/issues/2828
