### ISSUE TITLE
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by m3tarayz** [cypress-io/cypress#25290]
### Current behavior

CRA with TS
Cypress 12.2.0

I've recently updated my project from react 16 to 18 and cypress 6.x.x to 12.2.0 and having trouble running my e2e tests.
I'm using `@cypress/webpack-preprocessor` and `find-webpack` in my `cypress\plugins\index.js` file.
However, upon running cypress tests I'm presented with the following error 
```WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.``` 

Has anyone come across this? 
Any help is appreciated.

### Desired behavior

Being able to run cypress e2e tests.

### Test code to reproduce

Here is my `plugins/index.js` file straight from the CRA example here https://github.com/cypress-io/cypress/tree/develop/npm/webpack-preprocessor#readme

```const webpackPreprocessor = require('@cypress/webpack-preprocessor')
const findWebpack = require('find-webpack')

/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on) => {
    // find the Webpack config used by react-scripts
    const webpackOptions = findWebpack.getWebpackOptions()

    if (!webpackOptions) {
        throw new Error('Could not find Webpack in this project 😢')
    }

    // if we just pass webpackOptions to the preprocessor
    // it won't work - because react-scripts by default
    // includes plugins that split specs into chunks, etc.
    // https://github.com/cypress-io/cypress-webpack-preprocessor/issues/31

    // solution 1
    // blunt: delete entire optimization object
    // delete webpackOptions.optimization

    // solution 2
    // use a module that carefully removes only plugins
    // that we found to be breaking the bundling
    // https://github.com/bahmutov/find-webpack
    const cleanOptions = {
        reactScripts: true,
    }

    findWebpack.cleanForCypress(cleanOptions, webpackOptions)

    const options = {
        webpackOptions,
        watchOptions: {},
    }

    on('file:preprocessor', webpackPreprocessor(options))
}
```

### Cypress Version

12.2.0

### Node version

v19.3.0

### Operating System

Windows 11

**Comment by lmiller1990** [comment]
> cypress 6.x.x to 12.2.0

Woah, big jump. Can you share your `package.json`? I'm interested in what versions of `react-scripts`, Cypress, `@cypress/webpack-preprocessor`, and `webpack` you've got, among other things.

This error suggests a webpack 4.x config is getting used with webpack 5.x, or a similar incompatibility.

**Comment by m3tarayz** [comment]
Ha yeah, the project was due for an upgrade for a while.
I've had a look at some of the packages used based on your suggestion (webpack 4 vs webpack 5 mismatch) and I've removed packages that could pose a problem.

It solved the error! BUT!

Now I'm presented with a different issue. Let me know if I need to open a new ticket please. The issue is following:

```Error: Webpack Compilation Error
Module parse failed: Unexpected token (6:8)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.

> declare global {
|     namespace Cypress {
|         interface Chainable {
```

The block of code highlighted comes from the `commands.ts` file where I'm declaring some global types as follows

```
declare global {
    namespace Cypress {
        interface Chainable {
            setupMocks: typeof setupMocks
            setMockCookie: typeof setMockCookie
            getByTestId: typeof getByTestId
            findByTestId: (selector: string) => Chainable<JQuery<HTMLElement>>
        }
    }
}
```

Do I need a specific loader to handle this? If so do you know what one?

from my `package.json`

```
"@cypress/webpack-preprocessor": "^5.16.0",
"react-scripts": "5.0.1",
"cypress": "^12.2.0",
"webpack": "5.75.0", (via react-scripts)
```

Thanks again for all your help

**Comment by astone123** [comment]
@Samuel-Celko apologies for the delayed response. Could you share what you have in `tsconfig.json`, specifically for the `target` field? I wonder if that needs to be updated now that you're using Webpack 5. Thanks

**Comment by lmiller1990** [comment]
You will need `ts-loader` to load TypeScript files. That said, it looks like you aren't using TypeScript? If that's the case, just change the file to `js` instead of `ts` and delete the `declare module` part.

**Comment by ZachJW34** [comment]
@Samuel-Celko I wouldn't recommend following the documentation for setting up the webpack-preprocessor to utilize the `react-scripts` webpack config. The only use case for doing so would be if you need to import jsx components into your e2e tests. The default preprocessor should be enough to handle your js/ts files as it relates to your Cypress e2e tests.

I'm going to close this issue as there hasn't been any activity for a while.
