### ISSUE TITLE
Div translated out of parent with overflow hidden should not be visible but is

### ISSUE THREAD

**Issue by pbrzosko** [cypress-io/cypress#25295]
### Current behavior

When div in provided example is evaluated with .should("not.be.visible") it fails saying, that div is visible.

### Desired behavior

In this situation div should be considered as invisible.

### Test code to reproduce

[test-cypress.zip](https://github.com/cypress-io/cypress/files/10316065/test-cypress.zip)

### Cypress Version

12.2.0

### Node version

18.12.1

### Operating System

Windows 10 Enterprise 10.0.19044 Build 19044

**Comment by chrisbreiding** [comment]
Thanks for providing a reproducible example. I was able to verify the reported behavior. Looks like a bug in our visibility algorithm. I'll route this to my team for further investigation.

**Comment by briggsge** [comment]
Any workaround or updates? This is one of the bread and butters of visibility testing and ran into this with mobile viewport testing resulting in false-positives.
