### ISSUE TITLE
Upgrade chai to latest version

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2529]
We currently use 3.5.0. Latest version is 4.1.2.

**Comment by pvdyck** [comment]
@bahmutov ready for Sprint 5 or postpone ?

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/2862, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
