### ISSUE TITLE
Search should ignore dashes or spaces

### ISSUE THREAD

**Issue by Pashozator** [cypress-io/cypress#25303]
### What would you like?

Tests files are often name with "-" or "_" between words like "products-details" or "products_details". Search specs bar should be able to find those when you type "products details".

### Why is this needed?

I want this because it will be a lot easier to find desire specs.

**Comment by nilgaar** [comment]
I can take care of this @emilyrohrbough

**Comment by Pashozator** [comment]
@nilgaar how is going?

**Comment by nilgaar** [comment]
I'm waiting for the confirmation from @emilyrohrbough to start with this... Guess I can wait until next week for it, otherwise I'll just go for it.

**Comment by Pashozator** [comment]
@nilgaar no need to hesitate I guess

**Comment by Pashozator** [comment]
anything? @nilgaar

**Comment by Pashozator** [comment]
@nagash77 anything on this issue?

**Comment by jennifer-shehane** [comment]
We're open to accept a pull request for this, including proper tests around it.

**Comment by janlengyel** [comment]
Hello, can I try to work on this issue? I see there was some work done already. Are the tests the only thing missing in the previous PR?

This is my first contribution, is there anything in particular I should be aware of (other than reading CONTRIBUTING.md)?

**Comment by janlengyel** [comment]
@jennifer-shehane Can you please have a look at the PR?
