### ISSUE TITLE
POST Response body is undefined when using cypress

### ISSUE THREAD

**Issue by Kris-Pelteshki** [cypress-io/cypress#25313]
### Current behavior

The response body is undefined when inspecting with a breakpoint in dev tools. However, in the network tab, I can clearly see the response does have a body with values. Also, Cypress asserts that the `response.body` does have the property in the test. 
The body of the response is lost somewhere only when using Cypress. It works as expected without cypress. 

---

I am trying to add cypress to a codebase that does not have any previous E2E tests. 

The following test enters the credentials into a login form. 
![image](https://user-images.githubusercontent.com/40208044/210014327-386122e2-e1b9-4ae3-a8ae-fe9831057e66.png)

Everything works fine in a normal browser when I manually enter the same credentials and submit the form to login. The issue only occurs when running the code with cypress.

---

1.  `yarn cypress open`

1.  I've tried with the following 4 browsers with cypress — Had the same issue with all.
![image](https://user-images.githubusercontent.com/40208044/210014972-6d062709-f45a-47a4-a38c-4db769d9b60f.png)

1. The login request is sent and the response is a successful `200` with JWTs in the body. Cypress even successfully asserts that the body contains an `idToken` property — All good so far. 
![image](https://user-images.githubusercontent.com/40208044/210017211-cda71ed4-633a-42b1-b321-7c75bb7efab6.png)

1. However, in dev tools, I can see that the response body is being lost somewhere. Alternatively, there's a race condition when using cypress that I don't understand, but this is `async/await` code so it must have received the response. 
![image](https://user-images.githubusercontent.com/40208044/210015983-1d273504-9b20-44aa-8505-bc6f41ef8811.png)

### Desired behavior

Async/await code should work as normal in cypress' browser environments. The expected behavior is that the response should not be undefined. 

### Test code to reproduce

.

### Cypress Version

12.2.0

### Node version

v16.16.0

### Operating System

Windows 10.0.19044

**Comment by chrisbreiding** [comment]
Would you be able to provide a minimal reproduction of the issue that I can run? Without that, it will be difficult to verify the issue or validate any fix for it.

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by mdo5004** [comment]
@Kris-Pelteshki did you ever find a solution to this? I'm having the same problem. If not, I will create a reproducible example.

**Comment by Kris-Pelteshki** [comment]
> @Kris-Pelteshki did you ever find a solution to this? I'm having the same problem. If not, I will create a reproducible example.

I don't have good news sorry. I never found an answer.

**Comment by makdv** [comment]
1. You should put intercept before visiting page
2. I had a similar issue and after visiting page  wrapping further actions and checks into "setTimeout" helped me
