### ISSUE TITLE
How to incress connection retry count?

### ISSUE THREAD

**Issue by khteh** [cypress-io/cypress#25325]
### Current behavior

```
We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...
```

### Desired behavior

`cypress run` to specify the connection retry count.

### Test code to reproduce

None

### Cypress Version

12.2.0

### Node version

v18.8.0

### Operating System

Ubuntu 22.10

**Comment by nagash77** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress).
