### ISSUE TITLE
[IATR](M1.0) - Add tooltip for ellipsis when test title is shortened due to smaller breakpoints

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25339]
_Current Behavior_

In the `DebugFailedTest` component, there is responsive behavior to help reduce the width of the test titles at smaller breakpoints.  At a certain small size, if there are more than 3 title parts, part of the test title parts are removed and hidden by an ellipsis in the UI. (See arrow screenshot)  The user does not know what tile parts are hidden. 

![image.png](https://images.zenhubusercontent.com/5e25f9721016beda9c509196/a1ec6d48-ffc0-489c-b0bf-09e610dbc8f9)

_Desired Behavior_
The ellipsis should have a tooltip that shows the missing parts.  The title parts should be separated by a `>`.

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25339?planning-poker) with Zenhub @marktnoonan @astone123 @mike-plummer @ZachJW34 @rockindahizzy

**Comment by marktnoonan** [comment]
@warrensplayer can I confirm that in this ticket we are only doing the tooltip for whole sections that are omitted, where the arrow is pointing, not for any section that is being truncated but is still displayed?

https://www.loom.com/share/bf890a035084435e9b3493d5bfc7d487
