### ISSUE TITLE
REMOVE ATTRIBUTE BLANK DOESN'T WORK

### ISSUE THREAD

**Issue by alessandrostassano** [cypress-io/cypress#25330]
### Current behavior

When i click a specific button to continue the navigation in our booking application, i use the ".invoke(remove attribute target)" function to denied to the button the possibility to open a new chrome tab. This solution doesn't work because the properties that open new tab is contained in a javascript function, despite the target:blank properties is correctly contained in html element.
I put the screen of the chrome dev tools. 
Is there an alternative workaround to fix this behavior and switch off a javascript function contained the target blank?

### Desired behavior

Switch off the blank properties and stay in the current chrome page. 

### Test code to reproduce

cy.xpath(e_PlpPageElements.PrimoBottoneProsegui).invoke("removeAttr","target").click()

![image](https://user-images.githubusercontent.com/77775894/210330294-417a0780-fe3f-4b0f-930d-82c1c8bb74d9.png)

In "e_PlpPageElements.PrimoBottoneProsegui" is contained the xpath of the button "Prosegui" that i have to click. 
![image](https://user-images.githubusercontent.com/77775894/210330396-6f73952c-75c9-431a-916e-622fe22ff210.png)

The properties of Prosegui are these: 

![image](https://user-images.githubusercontent.com/77775894/210326495-6c58bd0c-dfab-4d67-be98-d3292e5d70fe.png)

I switch off target, but it doesnt work. I have to switch off ng-click="openPacketDetails(hotel, '').
Is there a workaround?

### Cypress Version

11.0.1

### Node version

16.17.0

### Operating System

Windows 10

### Other

I attached the screen.
The button "prosegui" has these properties, but the function _blank is contained in ng-click=""openPacketDetails"

<img width="759" alt="Cattura" src="https://user-images.githubusercontent.com/77775894/210252207-48491d34-5e67-4c13-a7fc-047cfb5016f7.PNG">

**Comment by chrisbreiding** [comment]
Can you share the contents of the `openPacketDetails` function? 

If removing `target="_blank"` doesn't work, my best guess is that `openPacketDetails`calls [window.open()](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) to open the page in a new tab. In that case, you should be able to patch `window.open()` to stop it from being called with a `_blank` target argument.

```js
// after visit, but before click

cy.window().then((win) => {
  const orig = win.open

  win.open = function (url, target, features) {
    return orig.call(this, url, '_self', features)
  }
})

// click the link
```

**Comment by alessandrostassano** [comment]
> Can you share the contents of the `openPacketDetails` function?
> 
> If removing `target="_blank"` doesn't work, my best guess is that `openPacketDetails`calls [window.open()](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) to open the page in a new tab. In that case, you should be able to patch `window.open()` to stop it from being called with a `_blank` target argument.
> 
> ```js
> // after visit, but before click
> 
> cy.window().then((win) => {
>   const orig = win.open
> 
>   win.open = function (url, target, features) {
>     return orig.call(this, url, '_self', features)
>   }
> })
> 
> // click the link
> ```

Hi, 
This is the content of the function.
I'm not sure what i have to do: the parameters indicated have to be customized?
![image](https://user-images.githubusercontent.com/77775894/210751195-52f979cc-28af-4b92-8309-63f67d1be2cb.png)

**Comment by chrisbreiding** [comment]
As I suspected, the function uses `window.open()`. Can you try putting the following code before the relevant `click()` in your test and see if it fixes the issue?

```js
cy.window().then((win) => {
  const orig = win.open

  win.open = function (url, target, features) {
    return orig.call(this, url, '_self', features)
  }
})
```

**Comment by alessandrostassano** [comment]
> As I suspected, the function uses `window.open()`. Can you try putting the following code before the relevant `click()` in your test and see if it fixes the issue?
> 
> ```js
> cy.window().then((win) => {
>   const orig = win.open
> 
>   win.open = function (url, target, features) {
>     return orig.call(this, url, '_self', features)
>   }
> })
> ```

It works, thanks a lot!!! What a great workaround!!
So grateful

**Comment by mohd-faisel** [comment]
@chrisbreiding  Hey chris, I am stuck at same problem since 3 days, can you help me, I tried above code but that didn't work for me

**Comment by mohd-faisel** [comment]
Here is my development code, in which they using window.open
![image](https://github.com/cypress-io/cypress/assets/94177317/f5a93531-de16-459e-9c53-ea720ed5e80d)

**Comment by mohd-faisel** [comment]
Here is what i tried in cypress
![image](https://github.com/cypress-io/cypress/assets/94177317/a179224e-5b48-488b-8bbb-1ccead7affd3)

**Comment by mohd-faisel** [comment]
@chrisbreiding  please look into my problem, this is very important me to handle this. Thanks in advance

**Comment by nagash77** [comment]
@mohd-faisel please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.  I also want to level set that open source issues have no guarantee around when and even if we will be able to solve them. 

If you are looking for other ways to get help using Cypress check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.
