### ISSUE TITLE
`xpath` should be a query command

### ISSUE THREAD

**Issue by JessefSpecialisterren** [cypress-io/cypress#25337]
### Current behavior

Under the new command logic introduced in Cypress 12, I would expect `xpath` to be a query command. However, it is currently added as a normal command:

https://github.com/cypress-io/cypress/blob/ede8ba418f419900eaf35d79d376b1c5b6167f41/npm/xpath/src/index.js#L161-L165

This means that if you chain a query command on `xpath`, the `xpath` will not be retried when the query command fails. Additionally, if `xpath` is itself chained on a query command (e.g. `cy.get('div').xpath('./span')`), the query command will not be retried when the `xpath` fails

### Desired behavior

I'd expect `xpath` to behave like a query command. I'd expect it and any surrounding query commands to be retried when an assertion fails

### Test code to reproduce

index.html
```html
<div>
  <span>foo</span>
</div>
<script>
  setTimeout(() => {
    document
      .querySelector('div')
      .insertAdjacentHTML(
        'afterend',
        '<div><span>bar</span></div>'
      )
  }, 1000)
</script>
```

spec.cy.js
```js
it('retries xpath when chaining a query command on it', () => {
  cy.visit('cypress/e2e/index.html')
  cy.xpath('//div[last()]').find('span').should('have.text', 'bar')
})

it('retries a query command when chaining xpath on it', () => {
  cy.visit('cypress/e2e/index.html')
  cy.get('div:last').xpath('./span').should('have.text', 'bar')
})
```

### Cypress Version

12.2.0

### Node version

v16.16.0

### Operating System

Windows 10.0.19044.2364

### Other

I imagine this change will bump `@cypress/xpath` to version `3.0.0` as it's a backwards-incompatible change (it will no longer work with older Cypress versions)

Also: happy new year 🎉! Thanks for continuing to develop and maintain this awesome testing tool!

**Comment by BlueWinds** [comment]
You're absolutely right it should be - I'll add it to the stack of things needing migration. Shouldn't take too long to get to.

If anyone else want to give this a try, I'd be happy to provide guidance and reviews! Writing queries isn't that bad once you understand how they work.

**Comment by jennifer-shehane** [comment]
We’ve made a decision to no longer support the [cypress/xpath](https://www.npmjs.com/package/@cypress/xpath/access) plugin. See https://github.com/cypress-io/cypress/pull/26893 for more context. We'll close this issue as we will not be releasing any more changes to the xpath plugin.
