### ISSUE TITLE
cacert configuration not picked up for test runs

### ISSUE THREAD

**Issue by chbiel** [cypress-io/cypress#25334]
### Current behavior

As described in the docs, `NODE_EXTRA_CA_CERTS` should be picked up by cypress (https://docs.cypress.io/guides/references/proxy-configuration#Using-a-custom-certificate-authority-CA).

It looks like this is the case for runtime stuff but not for the actual test suites.

And although client certificates can be configured (https://docs.cypress.io/guides/references/client-certificates) only providing a ca-file (needed in remote tests with a corporate proxy) is not possible and will fail with an error, that the `certs` array is empty.

It looks like corporate proxies are partially supported but not implemented fully.

### Desired behavior

Pick up `NODE_EXTRA_CA_CERTS` also for test runs, or make it somehow configurable.

Or allow to configure cacerts through the configuration without the need to provide client certificates.

### Test code to reproduce

No test necessary

### Cypress Version

12.1.0

### Node version

16.3.1

### Operating System

Ubuntu 20

**Comment by nagash77** [comment]
Hi @chbiel , Im sorry to hear you are having issues running Cypress.  Can you elaborate more on what you are actually seeing to lead you to the conclusions you mentioned - `It looks like corporate proxies are partially supported but not implemented fully.`.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
