### ISSUE TITLE
Failing NPM audit for @cypress/grep

### ISSUE THREAD

**Issue by rojalbati-cf** [cypress-io/cypress#25336]
### Current behavior

This package is failing a npm audit at ^3.1.3. A dependency relies on got <11.8.5. See https://www.npmjs.com/advisories/1080920.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/78461090/210356028-cf1e5609-ae01-40c7-b76d-f287e54095e4.png">

### Test code to reproduce

<img width="468" alt="image" src="https://user-images.githubusercontent.com/78461090/210356042-eed15611-d857-4a60-93ce-7ddcc0dd7ff0.png">

### Cypress Version

12.2.0

### Node version

v16.18.1

### Operating System

macOS 13.1 (22C65)

### Debug Logs

```shell
# npm audit report

got  <11.8.5
Severity: moderate
Got allows a redirect to a UNIX socket - https://github.com/advisories/GHSA-pfrx-2q88-qq97
No fix available
node_modules/got
  package-json  <=6.5.0
  Depends on vulnerable versions of got
  node_modules/package-json
    latest-version  0.2.0 - 5.1.0
    Depends on vulnerable versions of package-json
    node_modules/latest-version
      update-notifier  0.2.0 - 5.1.0
      Depends on vulnerable versions of latest-version
      node_modules/update-notifier
        simple-bin-help  >=1.3.0
        Depends on vulnerable versions of update-notifier
        node_modules/simple-bin-help
          find-test-names  >=1.1.0
          Depends on vulnerable versions of simple-bin-help
          node_modules/find-test-names
            @cypress/grep  *
            Depends on vulnerable versions of find-test-names
            node_modules/@cypress/grep

7 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```
```


### Other

_No response_

**Comment by rojalbati-cf** [comment]
@emilyrohrbough are we fixing it anytime soon ?

**Comment by rojalbati-plerion** [comment]
Fixed thanks!
https://github.com/cypress-io/cypress/pull/25699

**Comment by rojalbati-cf** [comment]
Seems like it was fixed in this PR
- https://github.com/cypress-io/cypress/pull/25699
