### ISSUE TITLE
cy.exec("node ./foo.js") failing on Travis CI

### ISSUE THREAD

**Issue by topheman** [cypress-io/cypress#2533]
### Current behavior:

When using `cy.exec("node ./foo.js")` on Travis CI, it fails with:

```
Error: The program 'node' can be found in the following packages:
 * node
 * nodejs-legacy
Ask your administrator to install one of them
```

You can find the source code at: https://github.com/topheman/react-fiber-experiments/blob/master/cypress/integration/about.spec.js#L24-L35

You can find the failing build at: https://travis-ci.org/topheman/react-fiber-experiments/builds/433978705#L565

### Desired behavior:

Be able to execute some JavaScript file with `node`, using `cy.exec()` like: `cy.exec("node ./foo.js")`

### Versions

```
$ node --version
v8.12.0
$ npm --version
6.4.1
$ nvm --version
0.33.11
Cypress:    3.1.0
Browser:    Electron 59 (headless)
```

More infos at: https://travis-ci.org/topheman/react-fiber-experiments/builds/433978705#L422

### Hint

This might be due to `cy.exec()` spawning a process where the `node` cli is not available on Travis (it works well on my laptop in Cypress GUI or headless mode).

**Comment by chrisbreiding** [comment]
> This might be due to cy.exec() spawning a process where the node cli is not available on Travis (it works well on my laptop in Cypress GUI or headless mode).

Sounds like it. Is Node installed on the Travis you're running?

**Comment by topheman** [comment]
> Sounds like it. Is Node installed on the Travis you're running?

Node is installed, as I mentioned in my question. Here are the versions of node, npm and Cypress:

```
$ node --version
v8.12.0
$ npm --version
6.4.1
$ nvm --version
0.33.11
Cypress:    3.1.0
Browser:    Electron 59 (headless)
```

https://travis-ci.org/topheman/react-fiber-experiments/builds/433978705#L429

**Comment by gmalicky** [comment]
Hi,
same issue happens for me with npm when trying to setup db in before hook:
`cy.exec('npm run db:reset && npm run db:seed');`
Is there a way to pass the npm path to travis somehow?
It may be related to https://github.com/travis-ci/travis-ci/issues/3894

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
