### ISSUE TITLE
Allow cypress to discover globally installed webkit

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#25344]
### What would you like?

I would like cypress to be able to discover webkit when installed as a global

`npm install -g "playwright-webkit@${1}"`

### Why is this needed?

This is needed to allow us to pre-install webkit in a docker container without relying on the project to install it prior to testing.

### Other

Theoretically is is fairly simple change, remove `{ paths: [process.cwd()] }` from the following two locations below, this should allow the require to search all default paths instead of limiting it.

https://github.com/cypress-io/cypress/blob/563617f73557a611da57737d6cdd2a4f75f2168c/packages/server/lib/browsers/webkit.ts#L59-L60

https://github.com/cypress-io/cypress/blob/563617f73557a611da57737d6cdd2a4f75f2168c/packages/server/lib/browsers/utils.ts#L211

**Comment by emilyrohrbough** [comment]
related to: https://github.com/cypress-io/cypress/issues/25375
