### ISSUE TITLE
[IATR] E2E Tests for IATR

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#25351]
When working through the IATR M0 and M1 stories, the focus was on writing component tests for the new front end features and updating existing end-to-end tests.  To complete the milestone, the CT tests need to be supported with E2E tests focused on the new functionality.  

These tests should be branched off the `stokes/IATR-M0-cloud-run-data` branch for the https://github.com/cypress-io/cypress/pull/25316 PR unless it is been merged to the feature branch `feature/IATR-M0`

The following areas need to be covered:

* Sidebar
  * See https://github.com/cypress-io/cypress/pull/25152
* Debug page
  * Empty states
    * These are similar if not the same as the Runs page.  So scenarios can be copied from there
    * See https://github.com/cypress-io/cypress/pull/25219
  * Non failure run statuses
  	* See https://github.com/cypress-io/cypress/pull/25286
  	* See https://github.com/cypress-io/cypress/pull/25361
  * Failed build showing failed specs
	* Failed build with only one group
  	* Failed build with multiple groups
  	* See https://github.com/cypress-io/cypress/pull/25263
  * Banners shown for "next" run
    * Completed state with running next state
    * Completed state with running next state that completes while on the page
    * See https://github.com/cypress-io/cypress/pull/25282
  * Navigating to external link for Cypress Cloud
  * Using the "Run failures button"
    * Opening test runner to run failed tests
    * Opening tooltip to change test type
    * See https://github.com/cypress-io/cypress/pull/25234

**Comment by lmiller1990** [comment]
I have moved this back to the Sprint Backlog from In Progress.
