### ISSUE TITLE
Permission denied to open binaries

### ISSUE THREAD

**Issue by Christianlance85** [cypress-io/cypress#25354]
### Current behavior

When using github actions to run cypress, I am getting permission denied when running cypress.

![image](https://user-images.githubusercontent.com/54050111/210450681-8ac0aa08-703a-45d5-a440-f27889ee969d.png)

![image](https://user-images.githubusercontent.com/54050111/210450546-1e3736c8-60f6-46d1-8e00-7e0f730bf49d.png)

### Test code to reproduce

![image](https://user-images.githubusercontent.com/54050111/210450745-3bee39cd-4d01-4b2a-9b9d-5db721bcc401.png)

### Cypress Version

12.2.0

### Node version

16

### Operating System

linux-x64 (Debian - 10.5)

**Comment by astone123** [comment]
@Christianlance85 can you set `DEBUG="cypress:*"` before running `cypress verify` and then post those logs? That would probably give us more information to go off of. Thanks!

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by e-fedosser** [comment]
Do you resolved this problem [Christianlance85](https://github.com/Christianlance85)?>
