### ISSUE TITLE
[IATR](M1.0) - Use new Cloud fields for isHidden determination

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25352]
_Current behavior_

The App is determining when to show an empty state on the Debug page for when the results should be hidden by current looking at an `isHiddenByUsageLimits` field as well as for a run status of 'OVERLIMIT'.  This is happening in the `DebugPageDetails` component here:  https://github.com/cypress-io/cypress/blob/0a3ee16087283590f902b76e795bfea846658f03/packages/app/src/debug/DebugPageDetails.vue#L26-L30

There is also an additional state that is not currently being handled that is due to data retention limits on free plans.  There is currently no way in the App to determine this state.  Instead, the Cloud just does not return any items in the `specs` field.

_Desired Behavior_
The Cloud PR [[CYCLOUD-748] Updating CloudRun with isHidden and related fields](https://github.com/cypress-io/cypress-services/pull/5150/files) introduces additional fields on `CloudRun` to encapsulate the logic for determining if the run should be "hidden".
* `isHidden` is the one boolean to check instead of having to do conditional logic in the app
* `reasonsRunIsHidden` is a union type field that is either type `DataRetentionLimitExceeded` or `UsageLimitExceeded`.  These two types have additional information needed to construct the correct messaging shown in the App

~*Note* Until the above PR is merged, you can check out the branch `muaz/CYCLOUD-748-reasons-run-hidden` for the `cypress-services` project.~

*NOTE* The PR has been merged and these changes are now available on the main Cloud feature branch: `feature/CYCLOUD-665-IATR`

_Updates Needed_

Replace the conditional logic in `DebugPageDetails` to use the new `isHidden` field to show the `DebugOverLimit` .  Then use the data returned in the `reasonsRunIsHidden` to show the appropriate messaging for either the "usage limit" or the "data retention" scenarios.  This can either be done in the existing component or add an additional component for the "data retention" use case.

The `reasonRunIsHidden` types have fields for the potential variable portions of the messages:
* `dataRetentionDays` - https://github.com/cypress-io/cypress-services/pull/5150/files#diff-4d081635bf3fca6e0a14c54b8943221997c052f52ec542165e41b7521596524cR1094-R1099
* `monthlyTests` - https://github.com/cypress-io/cypress-services/pull/5150/files#diff-4d081635bf3fca6e0a14c54b8943221997c052f52ec542165e41b7521596524cR1299-R1304

Figma designs:
* Over limit
  * [Is admin](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=21687%3A213116&t=jaAfdAZZXaA9I3kf-1)
  * [Not admin](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=21687%3A213116&t=jaAfdAZZXaA9I3kf-1)
* Data retention
  * [Is admin](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=23388%3A222416&t=jaAfdAZZXaA9I3kf-1)
  * [Not admin](https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=23388%3A222416&t=jaAfdAZZXaA9I3kf-1)

[CYCLOUD-748]: https://cypress-io.atlassian.net/browse/CYCLOUD-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CYCLOUD-748]: https://cypress-io.atlassian.net/browse/CYCLOUD-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mike-plummer** [comment]
Closed by #25361
