### ISSUE TITLE
Not able to Pass URL to docker 

### ISSUE THREAD

**Issue by ajays01061991** [cypress-io/cypress#25369]
### Current behavior

I am trying to passing URL using .env and Cypress.json and gitlab environment variable.
But URL is not getting passed from any option I tried in Cypress thought url get passed to docker but not to cypress using CLI as well.

### Desired behavior

URL should get passed to cypress either by using .env file or through CLI.

### Test code to reproduce

Test code is available in github: https://github.com/ajays01061991/CypressAutomation .

I am trying to passing URL using .env and Cypress.json and gitlab environment variable.
But URL is not getting passed from any option I tried.

### Cypress Version

9.7.0

### Node version

16.17.1

### Operating System

Windows

**Comment by chrisbreiding** [comment]
I'm not able to access the `PresortQACypressAutomation` folder in that repo, which appears to be a symlink or a submodule that I don't have permissions to view.

**Comment by chrisbreiding** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can re-open.
