### ISSUE TITLE
Video processing either takes too long or gets stuck

### ISSUE THREAD

**Issue by kpratik0912** [cypress-io/cypress#25366]
### Current behavior

Im using circle ci to run my tests and I have faced the issue multiple times where the build gets stuck at 
"Started processing:  Compressing to 32 CRF   "

Running:  Widgets/Grid/C874.percentage-input-cell.cy.js                                 (46 of 95)
  Estimated: 54 seconds

  Input %
    ✓ C874 Input % (56942ms)

  1 passing (58s)

 (TestRail Reporter)

  - Results are published to https://****.testrail.io/index.php?/runs/view/***

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     58 seconds                                                                       │
  │ Estimated:    54 seconds                                                                       │
  │ Spec Ran:     Widgets/Grid/C874.percentage-input-cell.cy.js                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     

Build was canceled

as per the log the test run took 58 sec but the build was stuck at view processing for more than hour. build was manully cancelled later

### Desired behavior

If any error processing video then cancel process instead of being stuck

### Test code to reproduce

not related to any specific test script/code

### Cypress Version

12.3.0

### Node version

v16.14.2

### Operating System

Windows 10

**Comment by astone123** [comment]
@kpratik0912 could you run this again but with [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) and then post those here? This might give us a better idea about what is happening during the video processing. Thanks

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
