### ISSUE TITLE
Newly created spec file requires restarting the Cypress process to run it

### ISSUE THREAD

**Issue by joshribakoff-sm** [cypress-io/cypress#25374]
### What would you like?

Create a new file in the e2e tests while Cypress is currently running, and have it show up either automatically or upon refreshing the page.

### Why is this needed?

Undue burden on the end user to kill & restart the Cypress process each time a file is added, renamed, or deleted

**Comment by emilyrohrbough** [comment]
@joshribakoff-sm Cypress will automatically pick up new tests when they are added unless your spec pattern is not matching on that file path. What version of Cypress and what OS are you experiencing this issue on?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by joshribakoff-sm** [comment]
> Cypress will automatically pick up new tests when they are added unless your spec pattern is not matching on that file path.

There seems to be a bug then, because it does not.


> What version of Cypress and what OS are you experiencing this issue on?

2.88.10, mac


> new information to provide

I'm just copy pasting an existing spec, not only does it not 'hot reload' `http://localhost:3001/__/#/specs`, if I force reload this page it still doesn't show up, until I take the nuclear option of entirely killing the process and launching it again, then it shows.

**Comment by emilyrohrbough** [comment]
@joshribakoff-sm This is currently working with Cypress 12.5.0. It seems at some point in time we fixed this behavior. I suggested upgrading to a newer version that 2.88.10.

**Comment by joshribakoff-sm** [comment]
Ah sorry I meant `12.3.0`.

`@cypress/request` is what was at `2.88`. Good to know its fixed in 12.5, thanks!
