### ISSUE TITLE
Command was killed with SIGKILL (Forced termination)

### ISSUE THREAD

**Issue by yousuftelus** [cypress-io/cypress#25372]
### Current behavior

**Locally on my machine macOS Ventura 13.1**:  Running cypress test via CTA ( by clicking a button ) on an App that is running in docker container ( which i have built an image based on different cypress images or node image where i installed cypress dependencies) works perfectly fine.

**Remotely**: The same docker image mentioned above is running on `Openshift` with the App running perfectly but when I trigger cypress via CTA it fails immediately with the following error below

```
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGKILL (Forced termination): /home/node/.cache/Cypress/12.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=640

----------

Platform: linux-x64 (Debian - 10.13)
Cypress Version: 12.3.0
```

**Solutions attempted**

`Running cypress with the following images:`

- cypress/included:10.11.0
- cypress/browsers:latest
- cypress/base:16.18.0 => => installed cypress dependencies 
- node:16.17.1-buster-slim => installed cypress dependencies 
- cypress/included:12.1.0
- cypress/included:12.2.0 => Latest at the moment of writing this

`Running cypress via npm with the following version:`

- cypress: ^10.8.0
- cypress: ^10.11.0
- cypress: ^12.1.0
- cypress: ^12.3.0 => Latest at the moment of writing this

`Tried running cypress via node_modules & directly from the binary`

`Tried clearing cypress cache and reinstall it again with all it’s dependencies`

 

**Outcome of the above attempts**: Same error of `SigKill` which translate to a process being killed immediately. By who? Good question.

**Details of the OS of the container**: 

`cat /etc/os-release`:

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Desired behavior

**Goal**: Run cypress via CTA to run e2e tests while the App is running in a docker container which is hosted remotely by `Openshift`

### Test code to reproduce

Unfortunately can't share everything since the code belongs to the company but in order to reproduce the bug you need to dockerize a simple node app with `npm init -y` by using any `cypress/included` image mentioned above or `npm i cypress` and deploy it on `Openshift` `stage env` and run `cypress verify` in the terminal of the container if you using a `cypress/included` image or in the same terminal run `./node_modules/cypress/bin/cypress verify` if you installed cypress via npm and finally you should see the error of `SigKill`

Here is a trimmed version of my `Dockerfile`

**When using cypress image:**

```
FROM cypress/included:12.2.0

ENV HOME=/home/node
ENV DEBUG=cypress:*

RUN chmod -R 777 /home/node/

WORKDIR $HOME/app

RUN mkdir -p /tmp/.X11-unix \
  && chmod 1777 /tmp/.X11-unix

RUN mkdir ./node_modules \
  && chown -R node:root ./node_modules

RUN chmod -R 777 /home/node/*

USER node

RUN npm ci

ENV PORT=4000

EXPOSE ${PORT}

ENTRYPOINT ["npm"]
CMD ["start"]
```

**When using node image and installing cypress dependencies:**

```
FROM node:16.17.1-buster-slim

ENV HOME=/home/node
ENV DEBUG=cypress:*

RUN chmod -R 777 /home/node/

WORKDIR $HOME/app

RUN mkdir -p /tmp/.X11-unix \
  && chmod 1777 /tmp/.X11-unix

RUN apt update
RUN echo y | apt install libgtk2.0-0 libgtk-3-0 libgbm-dev \
  libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 \
  libxtst6 xauth xvfb

RUN mkdir ./node_modules \
  && chown -R node:root ./node_modules

RUN chmod -R 777 /home/node/*

USER node

RUN npm ci

ENV PORT=4000

EXPOSE ${PORT}

ENTRYPOINT ["npm"]
CMD ["start"]
```

**Please Note**:  The issue here should not be about the code base of the app or the Dockerfile used to dockerize the app but should be the different behaviour we get when running container locally and triggering cypress works but not when the same container is running remotely in this case on `Openshift` where the app runs perfectly but triggering cypress fails

### Cypress Version

12.3.0

### Node version

v16.17.1

### Operating System

Debian GNU/Linux 9

### Debug Logs

```shell
./node_modules/cypress/bin/cypress verify  
  cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/home/node/app/node_modules/cypress/bin/cypress","verify"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli parsed cli options {} +3ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/node/.cache/Cypress/12.3.0/Cypress/Cypress +3ms
  cypress:cli Binary is executable? : true +2ms
  cypress:cli binaryDir is  /home/node/.cache/Cypress/12.3.0/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/node/.cache/Cypress/12.3.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 12.3.0 installed in: /home/node/.cache/Cypress/12.3.0/Cypress +5ms
  cypress:cli could not read binary_state.json file at "/home/node/.cache/Cypress/12.3.0/binary_state.json" +7ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +2ms
  cypress:cli force verify +0ms
  cypress:cli running binary verification check 12.3.0 +1ms


  cypress:cli clearing out the verified version +42ms
  cypress:cli undefined DISPLAY environment variable +0ms
  cypress:cli Cypress will spawn its own Xvfb +0ms
  cypress:cli needs Xvfb? true +2ms
  cypress:cli Starting Xvfb +1ms
  cypress:cli disabling Electron sandbox +20ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/node/.cache/Cypress/12.3.0/Cypress/Cypress +1ms
  cypress:cli smoke test command: /home/node/.cache/Cypress/12.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=193 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command was killed with SIGKILL (Forced termination): /home/node/.cache/Cypress/12.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=193
    at makeError (/home/node/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/node/app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command was killed with SIGKILL (Forced termination): /home/node/.cache/Cypress/12.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=193',
  command: '/home/node/.cache/Cypress/12.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=193',
  exitCode: undefined,
  signal: 'SIGKILL',
  signalDescription: 'Forced termination',
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +1s
  cypress:cli error message: Command was killed with SIGKILL (Forced termination): /home/node/.cache/Cypress/12.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=193 +2ms
  cypress:cli detecting arch { osPlatform: 'linux', osArch: 'x64' } +1s
  cypress:cli arm uname -m result: { stdout: 'x86_64' }  +12ms

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGKILL (Forced termination): /home/node/.cache/Cypress/12.3.0/Cypress/Cypress --no-sandbox --smoke-test --ping=193

----------

Platform: linux-x64 (Debian - 10.13)
Cypress Version: 12.3.0
```

### Other

**Commands in the running container terminal**

`cypress -v`

```
Cypress package version: 12.3.0
Cypress binary version: 12.3.0
Electron version: 21.0.0
Bundled Node version: 16.16.0
```

`cat /etc/os-release`

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Openshift runs on Red Hat Enterprise Linux:** ( From Google search )

```
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

**Comment by AtofStryker** [comment]
@yousuftelus thank you for opening an issue. Any idea what permissions the docker daemon has inside of openshift? Looks like the user should have permissions to `home/node/`...I don't have too much experience with openshift but is it possible to get a local cluster running on macOS without too much trouble?

**Comment by yousuftelus** [comment]
@AtofStryker in order not to have any issues of permissions I made sure to give in all files under `home/node/` the ability to read, write & execute for all users ( `RUN chmod -R 777 /home/node/` ) so i believe that could not be the issue.

For your second question I think it is possible according to this link https://developers.redhat.com/products/openshift-local/overview#:~:text=Local%20development%20with%20OpenShift&text=With%20OpenShift%20Local%2C%20you%20can,testing%20on%20an%20OpenShift%20cluster.

I gave enormous amount of time debugging this issue in order to stay with `cypress` as a testing library but if you believe this would require the collaboration of `Openshift` & `Cypress` devs to figure out & fix this issue please let me know. I have to switch to another testing library in the meantime in order not to be blocked completely.

**Comment by mjhenkes** [comment]
@yousuftelus, do you know what command specifically is used to start the docker container? I suspect similar to the related issue below the container may be running as a non root user `-u 1001:0`. I'm not very faimilar with open shift, but do you know if there is a way to run the container as root? baring that could it be run as a known non root user? say `-u 1000:0`(node). I suspect either of those solutions will work. We still need to fix this bug but haven't been able to prioritize it yet.

Related: https://github.com/cypress-io/cypress/issues/23962

**Comment by yousuftelus** [comment]
@mjhenkes Good question I have tried to run as root by changing the USER=root in Dockerfile or trying to switch to root user once the container is running by changing the password in the Dockerfile with `chpasswd` both failed. Looks like it is not possible to run as root in Openshift due to security reasons. 

But good news with the help of a developer in the company we found the issue was due to an insufficient CPU memory allocated to the container by Openshift which cypress needed more so upgrading it solved the issue. That being said is it possible to output a specific error like `insufficient memory` when this occurs? If not maybe something to consider as a source of problem when we get process being killed or specifying the amount of CPU memory each cypress version need to be able to run smoothly.

**Note**: Not quite sure if just upgrading the CPU memory was the only solution or the combination of another solution which is to override the UID given by Openshift to the container by the UID specified in the Dockerfile. Will test & post the command we used if indeed this played a role in the fix when I will be able to deploy as we are facing some other issue concerning the pipeline. If you don't see any post that means only upgrading CPU memory solved the issue.

Thank you so much for caring about this issue & I hope this solves other issues related to this.
Closing issue!

**Comment by lmiller1990** [comment]
I got this

```
 cypress:cli {} +1ms
  cypress:cli is Verified ? undefined +3ms
  cypress:cli running binary verification check 12.9.0 +1ms
It looks like this is your first time using Cypress: 12.9.0


  cypress:cli clearing out the verified version +13ms
  cypress:cli undefined DISPLAY environment variable +0ms
  cypress:cli Cypress will spawn its own Xvfb +1ms
  cypress:cli needs Xvfb? true +3ms
  cypress:cli Starting Xvfb +0ms
  cypress:cli disabling Electron sandbox +49ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /root/.cache/Cypress/12.9.0/Cypress/Cypress +1ms
  cypress:cli smoke test command: /root/.cache/Cypress/12.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=876 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command was killed with SIGKILL (Forced termination): /root/.cache/Cypress/12.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=876
    at makeError (/root/vuetify/node_modules/cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/root/vuetify/node_modules/cypress/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command was killed with SIGKILL (Forced termination): /root/.cache/Cypress/12.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=876',
  command: '/root/.cache/Cypress/12.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=876',
  exitCode: undefined,
  signal: 'SIGKILL',
  signalDescription: 'Forced termination',
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +3s
  cypress:cli error message: Command was killed with SIGKILL (Forced termination): /root/.cache/Cypress/12.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=876 +5ms
  cypress:cli detecting arch { osPlatform: 'linux', osArch: 'x64' } +4s
  cypress:cli arm uname -m result: { stdout: 'x86_64' }  +52ms

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGKILL (Forced termination): /root/.cache/Cypress/12.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=876

----------

Platform: linux-x64 (Ubuntu - 22.10)
Cypress Version: 12.9.0
```

I did this by running Cypress on a machine w/ 512 mb of ram - maybe a separate issue, but in my case it is likely caused by not having a powerful enough machine.
