### ISSUE TITLE
Empty suites showing in UI

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#25385]
### Current behavior

If you have a test with an empty suite and at least one valid test in the spec file, the suite is shown in the reporter as an empty expandable element. If you don't have any tests and just an empty suite, the reporter shows the "No tests found" state.

A `.only` on an empty suite with at least one valid test in the spec file only shows the empty expandable element.

### Desired behavior

I would expect empty suites to not show in the reporter. They are colored green which gives the indication that they passed. If a `.only` is added to an empty suite, the "No tests found" state should shoq.

### Test code to reproduce

Create a spec with the contents:

```js
describe('s1', () => {})
```
"No test found" state shows

---

```js
describe('s1', () => {})

it('t1', () => { 
  expect(true).eq(true)
})
```
Normal `t1` and empty `s1` suite shows

---

```js
describe.only('s1', () => {})

it('t1', () => { 
  expect(true).eq(true)
})
```
Empty `s1` suite shows

### Cypress Version

12.3.0

### Node version

v16.17.1

### Operating System

macOS 12.4

### Other

https://user-images.githubusercontent.com/25158820/211103961-e729905b-dd82-4c3d-9386-a9bb3d2d407d.mov

**Comment by emilyrohrbough** [comment]
I'd expect empty suites to be displayed to show you don't have tests written 😅

**Comment by ZachJW34** [comment]
@emilyrohrbough I think there could be a different context shown, maybe a `There were no test found in this suite`. There is a discrepancy between having a spec file with only an empty suite and a spec file with an empty suite + test. I like seeing the suite as well so not sold on what should be shown but the consistency could be improved.
