### ISSUE TITLE
After initial Auth0 successful login, using cy.visit() redirects to Auth0 login page

### ISSUE THREAD

**Issue by fznsakib** [cypress-io/cypress#25393]
### Current behavior

I am using Auth0 for user authorisation, so when the website is accessed, it redirects to the Auth0 login page before redirecting back to the website as a logged in user.

With the introduction of `cy.origin` in Cypress v12, I was hoping change the tests to login to the website via username/password as a user would rather than doing it programatically since multiple origins weren't allowed before.

The tests successfully login via Auth0 with this method, however any execution of `cy.visit` seems to break the authorised state and triggers the callback flow leading to the Auth0 login page.

### Desired behavior

Since authorisation is successful at the start of the test, using `cy.visit` thereafter within the site should work as expected

### Test code to reproduce

Followed the [Auth0 for Cypress documentation](https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication#What-you-ll-learn) which works correctly for initial authorisation

Any `cy.visit` command executed after initial authorisation leads to the issue

### Cypress Version

12.3.0

### Node version

v14.20.0

### Operating System

macOS 12.6

### Other

there are a few issues that could relate to this: [1](https://github.com/cypress-io/cypress/issues/25289), [2](https://github.com/cypress-io/cypress/issues/20476), [3](https://github.com/cypress-io/cypress/issues/25373) however in my instance, initial authorisation is actually successful

I have tried the workaround of [modifying the cookies with an intercept](https://github.com/cypress-io/cypress/issues/20476#issuecomment-1298486439) but this didn't work either

**Comment by valscion** [comment]
Can you check what cookies are saved when doing this? This sounds similar to what we have here:

* https://github.com/cypress-io/cypress/issues/25174#issuecomment-1372123187

**Comment by Bertg** [comment]
Possibly also relates to:
* #25253 
* #25247

**Comment by chrisbreiding** [comment]
@fznsakib Sorry to see you're encountering an issue. Are you able to provide a minimal reproduction of your issue? That will help us verify if it's related to other similar issues, debug the issue, and validate any solution to the issue.

**Comment by chrisbreiding** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can re-open.
