### ISSUE TITLE
Chrome Extension v3 Service Worker is removed while running specs

### ISSUE THREAD

**Issue by umanghome** [cypress-io/cypress#25408]
### Current behavior

Chrome Extension v3 installs background scripts as service workers. When the first test file runs, the service worker is present. However, the service worker is cleared after the first test file is run. So, when the second test file is run, the service worker does not exist.

This makes it difficult to test Chrome Extensions using Cypress.

### Desired behavior

Service Workers belonging to extensions should not be cleared between test files. If it is difficult to determine if a service worker belongs to an extension or not, then there should be an option to tell Cypress to not clear service workers altogether.

### Test code to reproduce

https://github.com/umanghome/cypress-extension-sw-repro

### Cypress Version

12.3.0

### Node version

v16.17.1

### Operating System

macOS 12.3

### Other

The issue seems to be that Cypress calls Chrome's `Storage.clearDataForOrigin` with `storageType: 'all`.
https://github.com/cypress-io/cypress/blob/1d0d2c8db19b2ad5a1fb8818ec7d2afd5b0e5f6a/packages/server/lib/browsers/cdp_automation.ts#L347

This means that the service workers are also cleared. Replacing "all" with "appcache,cookies,file_systems,indexeddb,local_storage,shader_cache,websql,cache_storage,interest_groups,shared_storage" fixes the issue. The value of this string can be found here: https://chromedevtools.github.io/devtools-protocol/tot/Storage/#type-StorageType
```diff
-this.sendDebuggerCommandFn('Storage.clearDataForOrigin', { origin: '*', storageTypes: 'all' }),
+this.sendDebuggerCommandFn('Storage.clearDataForOrigin', { origin: '*', storageTypes: 'appcache,cookies,file_systems,indexeddb,local_storage,shader_cache,websql,cache_storage,interest_groups,shared_storage' }),
```

Since replacing "all" with the working string feels hacky and won't cover everyone's use-cases, I would prefer being able to provide the value of this string via the config (`options.cdpStorageTypesToClear`?).

**Comment by chrisbreiding** [comment]
Sorry to see you're encountering an issue. Thank you very much for the reproduction. I was able to verify the behavior you've reported.

I'll route this to my team for further investigation.

**Comment by umanghome** [comment]
Maybe if the `origin` was set to `baseUrl`, that wouldn't remove the extension-related service workers?

**Comment by garrett-thompson** [comment]
Hey @chrisbreiding any update from the team? Thanks for taking a look.

**Comment by gonzae** [comment]
Hi, I'm getting the same behavior  Any update @chrisbreiding?

Any workaround @umanghome?

Thanks in advance!

**Comment by umanghome** [comment]
@gonzae For now we are planning to fork Cypress, apply the patch that I have mentioned in the issue description, and then [build the binary](https://github.com/cypress-io/cypress/blob/89cc70dad76e32ff7151a84c7ef4a0a9f4bcd500/guides/building-release-artifacts.md). Then we will install this custom binary using [CYPRESS_INSTALL_BINARY](https://docs.cypress.io/guides/references/advanced-installation#Install-binary).

That's the plan for now, at least. And only for CI so that we don't have to build for multiple OSes and architectures.

**Comment by gonzae** [comment]
@umanghome thank you!

**Comment by dylanb** [comment]
We are also encountering this issue - any plan for a fix? Also @chrisbreiding if we submit a PR to fix this, will the team work with us to get it resolved?

**Comment by chrisbreiding** [comment]
@dylanb We'd happily accept a PR to fix this issue.

**Comment by thuey** [comment]
@chrisbreiding I am putting together a PR now. Is there a preferred approach here? For example, @umanghome suggested a configuration option like `options.cdpStorageTypesToClear`. Would that be an acceptable solution?

**Comment by chrisbreiding** [comment]
@thuey That's a good question. I briefly discussed this with the team, and at the moment, we're not inclined to add a global configuration option for this. We plan to discuss it further and try to decide if service workers should be handled differently in regards to test isolation and what the best way to enable any configuration would be. 

I appreciate the willingness to submit a PR for this and I'm sorry to delay a solution, but for the moment I'd hold off on any more work on it until we come to a decision on what exactly that solution should be. I hope to get back to you with a way forward soon.

**Comment by thuey** [comment]
@chrisbreiding Thanks for following up with the team about this. I appreciate the transparency and explanation. If there's a way we can help with this effort, please let us know. I had started on a very rough PR for this involving a new `keepServiceWorkers` config flag: https://github.com/cypress-io/cypress/pull/26659.

This is a pretty major blocker for us right now, and I suspect others as well as Chrome is going to start requiring v3 extensions in the near feature.

Please keep us posted!

**Comment by dylanb** [comment]
@chrisbreiding this fix https://chromium-review.googlesource.com/c/chromium/src/+/4257067 and this https://chromium-review.googlesource.com/c/chromium/src/+/4354471 resolve the issue in Chrome 112. I think you can close this issue.

**Comment by chrisbreiding** [comment]
@dylanb Thanks for posting that! I agree that we should close this issue. It's clearly a bug with Chrome that it wipes out an extension's service worker and doesn't restore it. On Cypress's end, we still want to clear browser state between specs, including service workers, in order to prevent any cross-spec pollution via state buildup.
