### ISSUE TITLE
cy.visit() and cy.request() are failing on working URL

### ISSUE THREAD

**Issue by nunep87** [cypress-io/cypress#25414]
### Current behavior

```js
cy.visit('https://www.questrade.com/learning/questrade-basics/funding-your-account/funding-overview')
```

is failing with the error 

```
CypressError
cy.visit() failed trying to load:

https://www.questrade.com/learning/questrade-basics/funding-your-account/funding-overview?_ga=2.235994883.309396280.1673358144-414125501.1666079355

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

> Error: read ECONNRESET

Common situations why this would fail:
- you don't have internet access
- you forgot to run / boot your web server
- your web server isn't accessible
- you have weird network configuration settings on your computer

Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: 
```

### Test code to reproduce

```js
describe("Broken Links Detection Test", () => {
    before(() => {
        cy.visit('https://www.questrade.com/learning/questrade-basics/funding-your-account/funding-overview?_ga=2.235994883.309396280.1673358144-414125501.1666079355')
    })

    it('should check broken links on Online Banking page', () => {
...
    })

})
```

### Cypress Version

12.3.0

### Node version

v14.21.0

### Operating System

Windows

**Comment by chrisbreiding** [comment]
Sorry to see you're encountering an issue. I was able to replicate the issue with the provided code.

I'll route this to my team for further investigation.

**Comment by nunep87** [comment]
Hi here, any update on this ?

**Comment by edgartagharyan92** [comment]
Hi guys,
Do have any updates regarding this issue ?

**Comment by OwaisAD** [comment]
Any updates? @chrisbreiding

**Comment by lhotovy** [comment]
I am experiencing this too when I test links via cy.request. I am pulling list of links from fixture and then making request on each of them. However, everytime some of the requests fail, usually on different link than in previous attempts.

**Comment by koentibben** [comment]
+1 [lhotovy](https://github.com/lhotovy), it's very inconvenient :-(

**Comment by bradleybeighton** [comment]
I'm also experiencing this running in v10 in headless mode

**Comment by ToshaBely** [comment]
The issue still exists on Cypress version `13.11.0`.

In order to reproduce it you should run `cy.request()` first and then `cy.visit()`.
