### ISSUE TITLE
Can't access test result in dashboard

### ISSUE THREAD

**Issue by shwarcu** [cypress-io/cypress#25410]
### Current behavior

I try to open test results from slack notification (Dashboard slack integration) and webapp is not working. Heroku error page is shown.
<img width="1724" alt="Screenshot 2023-01-10 at 11 08 52" src="https://user-images.githubusercontent.com/58426925/211522766-99a1156b-30c7-4d8a-a96a-35e8894fcbe4.png">

### Desired behavior

I should be able to open test results from slack notification.

### Test code to reproduce

Not applicable.

### Cypress Version

11.2

### Node version

16.18

### Operating System

MacOS 13.1

**Comment by swatisharma0303** [comment]
Same

**Comment by nagash77** [comment]
Hi @shwarcu , Im sorry you are having problems using Cypress Cloud.  Are you still having this issue?  There was some performance issues with heroku yesterday which may have caused this behavior.

**Comment by shwarcu** [comment]
@nagash77 Hi, at the moment it's working fine 👍
