### ISSUE TITLE
The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection

### ISSUE THREAD

**Issue by gplusdotgr** [cypress-io/cypress#25417]
### Current behavior

```
 CypressError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  > 
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
https://on.cypress.io/uncaught-exception-from-application
Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Profile Page`
  Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
```

### Desired behavior

no error

### Test code to reproduce

all tests

### Cypress Version

10.9.x

### Node version

16.x.x

### Operating System

ubuntu

### Other

In completely identical code and tests this error started happening. We tried everything, nothing works

**Comment by gplusdotgr** [comment]
Test is also on cypress cloud for support, video: 

https://user-images.githubusercontent.com/1768834/211625256-701ce48c-403c-4d2f-a76a-90f4d14e23c3.mp4

**Comment by chrisbreiding** [comment]
Can you try this on the latest version of Cypress? There was a fix in 12.2.0 involving the display of unhandled promise rejections. It won't fix your issue, but it will hopefully show us what the error message is instead of it being an empty string.

Also, we'll need a reliable reproduction we can run in order to debug this.

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by arunachala-prabu** [comment]
for me also having same issue i unable to fix this issue so my build getting failed
