### ISSUE TITLE
cy.session is cached across spec files when experimentalRunAllSpecs=true

### ISSUE THREAD

**Issue by Waterstraal** [cypress-io/cypress#25416]
### Current behavior

According to the [docs](https://docs.cypress.io/api/commands/session#Session-caching) a session is cached for the duration of a spec file:

> Once created, a session for a given id is cached for the duration of the spec file. You can't modify a stored session after it has been cached, but you can always create a new session with a different id.

When I run multiple spec files using the cypress open command, I see that the session is restored in the second spec file. I would expect that the first test in each spec file would create a new session.

### Desired behavior

Cypress creates a new session for each new spec file, as described in the docs.

### Test code to reproduce

- Have multiple specs files with tests that use cy.session with the same id
- Run Cypress with `cypress open`
- Run those spec files
- See that the session is restored in the second spec file

### Cypress Version

12.3.0

### Node version

16.13.2

### Operating System

Win 10

**Comment by astone123** [comment]
@Waterstraal I could only get this to happen one of two ways

- running the specs together with the [`experimentalRunAllSpecs`](https://docs.cypress.io/guides/references/experiments#End-to-End-Testing) feature
- specifying [`cacheAcrossSpecs: true`](https://docs.cypress.io/api/commands/session#Caching-session-data-across-specs) when calling `cy.session`

Are you doing either of those things, or are you seeing this when running specs generally in open mode? Thanks

**Comment by Waterstraal** [comment]
@astone123 Yes I have the `experimentalRunAllSpecs` enabled which allows me to run multiple spec files in one go.

**Comment by astone123** [comment]
Yeah, we should be clearing cached sessions in between specs in run all specs mode. Thanks for reporting this

**Comment by vaibhavganatraTR** [comment]
Is there any update on this bug?
