### ISSUE TITLE
cy.visit() diagnostic for 404 server response might be misleading

### ISSUE THREAD

**Issue by ngladitz** [cypress-io/cypress#25424]
### Current behavior

When cy.visit() gets a 404 server response it provides the following log information:
```
The response we received from your web server was:

  > 404: Not Found
```

This is also reflected in the frame that normally shows the website being tested:
![image](https://user-images.githubusercontent.com/4358176/211758430-3afae463-eb4e-4440-a1ae-c93d3c582207.png)

The status code (404) and mime type (text/html) match what the original server itself responded with.

"Not Found" is presumably added to explain the status code (404) but I initially assumed (given the phrasing in the log) that this was part of the literal response from my server; leading to some confusion.

My server responded with a custom body that contained more detail / context on why / how the request failed but this information is neither visible in the log nor in the frame for the website being tested.

### Desired behavior

Preferably I would like to see the actual server response in the frame containing the website being tested.

The actual body of the response in the log would also be nice.
Alternatively more accurate phrasing indicating that only the response status code (rather than the full server response) is output to the log would be appreciated.

### Test code to reproduce

```
git clone https://gist.github.com/ngladitz/03292fe70cdfa7c213882cc7ff95de1c testcase
cd testcase
npm install
node test.js
```

### Cypress Version

12.3.0

### Node version

v16.16.0

### Operating System

Ubuntu 22.10

**Comment by chrisbreiding** [comment]
You can [keep Cypress from automatically failing on visit](https://docs.cypress.io/api/commands/visit#Arguments) when it receives a non-200 or 300 response by passing `failOnStatusCode: false`:

```js
  cy.visit('/', { failOnStatusCode: false })
```

Then your custom 404 response will render and you can assert on its contents.

**Comment by ngladitz** [comment]
@chrisbreiding Thank you. Can I have it both though? I want it to fail based on the status code not body content. Do I have access to the status code to manually assert on it?

**Comment by chrisbreiding** [comment]
Yes, you can get the statusCode using [cy.intercept()](https://docs.cypress.io/api/commands/intercept) like so:

```js
cy.intercept('/').as('page')

cy.visit("/", { failOnStatusCode: false })

cy.wait('@page').its('response.statusCode').should('not.equal', 404)
```

**Comment by ngladitz** [comment]
Thank you that does look promising but plugging this verbatim into my testcase's `spec.cy.js`:
```js
describe("foo", () => {
    it("bar", () => {
        cy.intercept('/').as('page')
        cy.visit("/", { failOnStatusCode: false })
        cy.wait('@page').its('response.statusCode').should('not.equal', 404)
    });
})

```

gets me:

```
  0 passing (5s)
  1 failing

  1) foo
       bar:

      Timed out retrying after 4000ms
      + expected - actual
```

... I've only gotten started using cypress so I might be missing something obvious.

**Comment by chrisbreiding** [comment]
That test is supposed to fail since the status code is 404, but it should say: "Timed out retrying after 4000ms: expected 404 to not equal 404". 

There's clearly an issue with how error messages are output, but that's a separate issue. I'll make sure to log it.

**Comment by chrisbreiding** [comment]
Created this issue for the full error message not printing to stdout: https://github.com/cypress-io/cypress/issues/25458
