### ISSUE TITLE
Cypress command logs does not scroll to bottom in Cypress runner on Mac

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#25420]
### Current behavior

* Use a macbook, use Cypress studio (v11, v12, v12.2, v12.3)
* Run any spec
* Cypress command runner doesnt scroll to bottom. Have to manually scroll

### Desired behavior

* Match the behavior we see when viewing headless videos from our Cypress dashboard -> runner to automatically scroll to the bottom

### Test code to reproduce

https://github.com/egucciar/cypress-test-tiny

### Cypress Version

12.3.0

### Node version

16.15.0

### Operating System

MacOs 13.1

### Other

Note: It doesnt matter if i do or dont hover over the left sidebar - the sidebar NEVER scrolls no matter what I do. Also this is happening to other people in my company (ObserveInc). We are paying dashboard customers.

https://user-images.githubusercontent.com/2848185/211669615-9f0cc61e-9f56-48ce-b10f-c95671219c91.mov

**Comment by astone123** [comment]
@egucciar if you click the dropdown arrow to the left of the re-run button, you should see an option for auto-scrolling there. Is that option enabled?

![Image](https://user-images.githubusercontent.com/14275198/212166736-019888fd-4655-49d2-a3e7-6aebc392a282.png)

**Comment by egucciar** [comment]
yes, thank you very much @astone123 . Had no idea this was a setting that was getting turned off by default. My aggravation has been solved!
