### ISSUE TITLE
White Page after run cypress

### ISSUE THREAD

**Issue by shadirok** [cypress-io/cypress#25425]
### Current behavior

When i start cypress with cmd " npm run cypress" Cypress app opened with blank page

![image](https://user-images.githubusercontent.com/25399900/211824000-bbd5740a-578b-444f-bff1-c9fd3b70eebc.png)

![image](https://user-images.githubusercontent.com/25399900/211823668-5ca9c63f-8d2d-4032-b1c4-54cd5879a67e.png)

### Debug logs

```Text
PS C:\Users\AburokEx\own\projects\shared-rms-app> ./node_modules/.bin/cypress --version
Cypress package version: 10.7.0
Cypress binary version: 10.7.0
Electron version: 19.0.8
Bundled Node version:
16.14.2
PS C:\Users\AburokEx\own\projects\shared-rms-app> npm --version
8.15.0
PS C:\Users\AburokEx\own\projects\shared-rms-app> node --version
v16.17.1
PS C:\Users\AburokEx\own\projects\shared-rms-app> npm run cypress --debug

> rms@0.0.1-SNAPSHOT cypress
> cypress open --e2e
```

### Cypress Version

 10.7.0

### Node version

v16.17.1

### Package Manager

npm

### Package Manager Version

8.15.0

### Operating system

Windows

### Operating System Version

64-Bit

**Comment by astone123** [comment]
@shadirok could you follow the instructions [here](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) to run Cypress with debug logging enabled and post those logs here? This will give us a better idea about what might be happening when you launch Cypress. Thanks

**Comment by shadirok** [comment]
Hi, Thank you.
attached the debug file 
[debug.txt](https://github.com/cypress-io/cypress/files/10424182/debug.txt)

**Comment by ZachJW34** [comment]
I don't see anything in the provided debug logs that is out of order. Are you able to provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

You might also try running `npx cypress open --global` and opening the dev-tools. If you don't see a white screen, you can then select your project and see if there is anything in the console that could reveal the issue.

**Comment by shadirok** [comment]
Thank you for your reply. 
Unfortunately i still have the same problem with **Powershell**.
Today i have tried to start cypress from cmd and it does work.

**Comment by ZachJW34** [comment]
Does it work if you run `Powershell` as admin?

**Comment by shadirok** [comment]
No, unfortunately not.

**Comment by ZachJW34** [comment]
There are many things that can differ between cmd and powershell (env variables, security). You have a workaround for running Cypress via `cmd` so the issue lies with how your PowerShell environment is configured. I was not able to reproduce this on my machine running PowerShell so going to close.
