### ISSUE TITLE
Self Signed certificates in chain show RequestError: Error: certificate signature failure

### ISSUE THREAD

**Issue by darwinmak11** [cypress-io/cypress#25422]
### Current behavior

We run cypress in gitlab and get connection error to dashboard api showing certificate signature failure.
Everything works fine in 10.4.0. 
With the version 12.3.0 we started to see error in Error: self signed certificate in certificate chain as mentioned in https://github.com/cypress-io/cypress/issues/24298
So we added the following parm:
    - npm config set cafile $ZAP_PUB
    - npm config set strict-ssl false

Once we added these parm we have new errors:
We encountered an unexpected error talking to our servers.
We will retry 3 more times in 30 seconds...
The server's response was:
RequestError: Error: certificate signature failure
We encountered an unexpected error talking to our servers.
We will retry 2 more times in 1 minute...
The server's response was:
RequestError: Error: certificate signature failure
We encountered an unexpected error talking to our servers.
We will retry 1 more time in 2 minutes...
The server's response was:
RequestError: Error: certificate signature failure
We encountered an unexpected error talking to our servers.
We will retry 0 more times in ...
The server's response was:
RequestError: Error: certificate signature failure
We encountered an unexpected error talking to our servers.
The server's response was:
RequestError: Error: certificate signature failure

We used openssl to verify the CA files 
openssl verify -verbose -CAfile $ZAP_CA $ZAP_PUB
/builds/qa/cypress-e2e-automation.tmp/ZAP_PUB: OK

### Desired behavior

In 10.4.0 everything is fine and self signed certificates are validated by own CA.

### Test code to reproduce

    - export http_proxy=http://<proxy with self-sign CA>:8080
    - export https_proxy=http://<proxy with self-sign CA>:8080
    - npm config set cafile $ZAP_PUB
    - npm config set strict-ssl false
    - npm config set registry http://registry.npmjs.org
    - openssl verify -verbose -CAfile $ZAP_CA $ZAP_PUB

### Cypress Version

12.3.0

### Node version

v16.14.0

### Operating System

docker image cypress/browsers:node16.14.0-slim-chrome99-ff97

**Comment by darwinmak11** [comment]
Please let me know if additional info is needed.

**Comment by AtofStryker** [comment]
hi @darwinmak11. Thank you for opening an issue. Is it possible to get a reproduction repository up with some junk self signed certs with openssl? What is consuming the `http_proxy` `https_proxy`  variables here and is it even possible to stub out? Even if whatever is doing the proxying goes to a local server that I would think would suffice. What do you think?

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
