### ISSUE TITLE
Not able to connect to Chrome 109 on Windows

### ISSUE THREAD

**Issue by jjohnston-roomandboard** [cypress-io/cypress#25436]
### Current behavior

After updating to Chrome 109 the behavior of Cypress is different when running tests locally. If Chrome is not open then it launches and everything runs fine. If Chrome is already open then a new tab is opened to a blank page and we get an error that  it is unable to connect to Chrome. This only started happening when our company rolled out the Chrome 109 update. Things were fine before that. 

This also only happens on Windows. It does not happen on machines running Ubuntu Linux or Mac with the exact same version of Chrome.

This is in the terminal over and over:
```
Still waiting to connect to Chrome, retrying in 1 second
Still waiting to connect to Chrome, retrying in 1 second
Still waiting to connect to Chrome, retrying in 1 second
Still waiting to connect to Chrome, retrying in 1 second
Still waiting to connect to Chrome, retrying in 1 second
Still waiting to connect to Chrome, retrying in 1 second
Still waiting to connect to Chrome, retrying in 1 second
Still waiting to connect to Chrome, retrying in 1 second
```

### Test code to reproduce

Have Chrome 109 running and then try running a cypress test using Chrome. You should get a black tab in the existing Chrome instance and your terminal window should say "Still waiting to connect to Chrome, retrying in 1 second".

### Cypress Version

10.8.0

### Node version

17.3.0

### Operating System

Windows

**Comment by AtofStryker** [comment]
Hi @jjohnston-roomandboard. Congrats on opening your first issue! Would you be able to try running Cypress with either node `16.x` or `18.x` or one of our [supported node versions](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs)? We do not support `17.x`. Also, what version of windows are you running?

**Comment by jjohnston-roomandboard** [comment]
It is our QA team on Windows having the problems. We have them updated to node v18.13.0 now and get the same issue. Our devs all use Linux or Mac and we cannot reproduce the problem regardless of which version of node.

I asked QA how they are dealing with it and this is what they said. "I close all of my instances of chrome. Then I open cypress and it launches the browser. It also asks me if I want to restore the other tabs and I click yes. So now I have a working cypress tab AND my other tabs. This works fine until you need to change environments. And this requires you to start from the beginning."


This is the Windows version:
```
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎1/‎3/‎2022
OS build	19045.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0
```

**Comment by AtofStryker** [comment]
@jjohnston-roomandboard I wonder if there is additional Corporate Security Policies (CSP) on window's enterprise chrome that are administration managed. 

To further diagnose, does it work in Electron? Would they be able to try downloading standalone [chromium](https://chromium.cypress.io/) and see if they get the same behavior?

**Comment by jjohnston-roomandboard** [comment]
Yes. It works fine in the Electron and Firefox. We are really sure it was the Chrome 109 update. It was working on Chrome 108 and then immediately after getting the Chrome 109 update it started getting this behavior. We have 4 people on our QA team and they all experienced the same behavior with the same timing. Are you not able to reproduce the problem? 

If your not able to reproduce then we can try standalone chromium. We could maybe even roll back to Chrome 108, although I'll have to get our IT administrators in the mix for that.

**Comment by AtofStryker** [comment]
I am unable to reproduce on Windows 10, Chrome 109 with Cypress 12.3.0. My guess is there is something interfering with the binary from running, but it almost sounds like its reusing the existing process. If chromium works, I think it could be possible CSP interference or something else

**Comment by jjohnston-roomandboard** [comment]
Interesting. Sounds like its something on our side after all. We will keep working through it.

**Comment by jjohnston-roomandboard** [comment]
It does work with Chromium 109. I think your right that some Corporate Security Policies must have been put in place. I'll just close this then. Thank you for looking.
