### ISSUE TITLE
cypress 12.3.0The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by emilylei** [cypress-io/cypress#25439]
### Current behavior

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### Test code to reproduce

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### Cypress Version

12.3.0

### Node version

v12.16.2

### Operating System

macos

**Comment by nagash77** [comment]
@emilylei Unfortunately there is not enough information to go off of in this ticket so I am going to close it until a reproducible example is provided. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

I would also suggest you search through our open issues to see if another user has already encountered the same or similar issues.  For example - https://github.com/cypress-io/cypress/issues/18464 and https://github.com/cypress-io/cypress/issues/22338

**Comment by LaxmipriyM** [comment]
Hi everyone,
I am facing the same issue while running a test using cypress 12:
- Cypress package version: 12.3.0
- Platform: linux-x64 (Ubuntu - 22.04)

- I tried running the test with npx cypress open
but I am getting error message as:- 
```

The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 22.04)
Cypress Version: 12.3.0`
```
Thanks in advance....

**Comment by nagash77** [comment]
Hi @LaxmipriyM , can you provide a reproducible example?
