### ISSUE TITLE
Improve Run Performance when Recording to the Cloud

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#25435]
### What would you like?

Improve Run Performance when Recording to the Cloud.

We need to do breakdown analysis of how we are sending data to the cloud and make improvements to ensure test times when recording to the dashboard are similar (ideally the same) as non-recorded runs.

 It's been reported:
- time to run test increased when connected to Cloud, in comparison to running locally on the runner.  - https://app.clickup.com/t/18033298/PM-2717
- disabling video uploads for passing tests via `videoUploadOnPasses: false` significantly improve record times - https://github.com/cypress-io/cypress/issues/16524
- Large payloads have caused slowness (sometimes timeout) with an observed an extra 10-20 second delay between one spec finishing and a new one starting 
  - a deep dive investigation it was estimated 11 seconds * 533 specs = 97 extra minutes to record when a large configuration payload was sent.

Thinks we know we should look at and addressed:
- We know
  - Before a spec
    - The suite-/test-level config overrides & runtime config (Cypress.config() / Cypress.env()) is sent upfront.
  - After spec completes, its:
    - post results
    - once finished upload videos / screenshots
    - once finished, update test output
- Can address by:
  - Only record cypress configuration at the beginning of the run - currently we recorded this after each spec. Large configuration payloads have caused timeouts in the past.
  - Test results / video uploads should not block the start of the next spec

### Why is this needed?

Recording to the Cloud should add value without excessive time increase in runs. This allows for faster CI turnaround times and reduced CI cost for consumers.

**Comment by brian-mann** [comment]
I was talking to @chrisbreiding about this and recommended that me, chris, @emilyrohrbough and @tgriesser get on a call to discuss these. These are definitely some of the "right" problems to look at, but I have concerns they are not the right suggested solutions. There are a few data model assumptions here which would be very problematic to implement. I believe there are better and more direct ways to address the underlying problems that we can cover in a quick call.
