### ISSUE TITLE
Component specs sometimes don't live reload

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#25438]
### Current behavior

So far I can only reproduce when running open with flags, like this:
```bash
npx cypress open --component --browser chrome
```

I was able to get this to happen in both 12.2.0 and 12.3.0, haven’t tested others.

If I do an `open` with no flags and click through the Launchpad UI to start component testing, reloading is fine, I’m not able to reproduce this.

[Loom video demonstrating opening with/without flags](https://www.loom.com/share/b7c8317881bd431bbb7d1ceacb1af0e4).

As can be seen in the video, the recompilation happens as usual, it just never hits the browser. The is reminiscent of a similar bug that was previously traced down to a race condition at startup caused by dependencies in the v8 snapshot not being deferred properly (or something like that). Different behavior when opening with flags seems to suggest some sort of race condition also.

Likely we can narrow it down following the troubleshooting guidelines here: https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#troubleshooting

### Desired behavior

Cypress should always correctly live reload component specs after changes are saved in the test file or the component itself.

### Test code to reproduce

I am testing in this Vue 3/Vite app on [this branch](https://github.com/marktnoonan/cy-validators-example/tree/what-component).

### Cypress Version

12.2.0, 12.3.0

### Node version

16.18.0

### Operating System

mac os monterey 12.6

**Comment by astone123** [comment]
I haven't been able to reproduce this yet. I tested using the branch that you linked in the description and I opened Cypress using the flags. This might point to it being a race condition like you said @marktnoonan

**Comment by marktnoonan** [comment]
Investigating this, so far I have been able to reproduce consistently in every release since 11.0.0 (including 11.0.0). I can only reproduce it when opening with flags. v10.11.0 works fine with flags, consistently, in the same conditions where other things fail.

This must have overlapped with the other live reloading bug from 11.0.0, since it is present both before and after the fixes made in https://github.com/cypress-io/cypress/pull/24630.

Conclusion so far is only that this was introduced at the same time as v8 snapshots and the GA of component testing.

Next I'm going to work from develop and see what circumstances allow it to be reproduced there.

**Comment by marktnoonan** [comment]
Frustratingly I could not reproduce this again, after being able to consistently reproduce easily for several days. So I have not been able to do any of the troubleshooting guide in the monorepo. Cypress 12.3.0 works perfectly for me now, even with CPU under heavy heavy load.

I'm going to move this to blocked and will plan to pick up the troublshooting if I see this again in the wild.

The comments in #25477 about firefox make that issue seem like it is probably unrelated.

**Comment by marktnoonan** [comment]
Just a documenting that @astone123 saw this as well yesterday, at least once.

**Comment by lmiller1990** [comment]
I think we should close this - no update or reproduction, no work to be done.
