### ISSUE TITLE
The running cypress browser crashes

### ISSUE THREAD

**Issue by DoraemonSandy** [cypress-io/cypress#2544]
### Is this a Feature or Bug?
Yes

### Current behavior:
Cypress browser always crashes in some specific scenarios. 
For example: 
1. Running spec contains more than 6-7 hundred lines of codes.
2. Running all specs but every single spec has codes less than 500 lines

### Desired behavior:

The browser should not crash anyway.
### Steps to reproduce:
Create a spec with more than seven hundred lines of codes and run it.

### Versions
Cypress: beta 3.0.2,
operating system: win 10,
browser: chrome 69.

**Comment by andriilazebnyi** [comment]
Try to decrease value or `numTestsKeptInMemory` in `cypress.json`. As cypress keeps tests in memory, it could lead to browser crashes. Especially when you run a large number of tests.

**Comment by jennifer-shehane** [comment]
@DoraemonSandy Were you able to decrease the `numTestsKeptInMemory` for your test run?

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment to reopen if this is still happening.

**Comment by iboughalem** [comment]
Hello, 

I have the same problem, but my tests are really short 100 lines of code max.
Even after decreasing (to 5) the value of ```numTestsKeptInMemory``` the browser keeps crashing.

### Version 
Cypress: 3.1.5
Operating system: win 10,
Browser: chrome 72

**Comment by jennifer-shehane** [comment]
@iboughalem Please open a new issue detailing exactly how to reproduce the crashing behavior.
