### ISSUE TITLE
@alias.all Throws An Error When Defining Alias in Intercept With Route Handler in Version 12

### ISSUE THREAD

**Issue by blabute** [cypress-io/cypress#25448]
### Current behavior

Currently, if you use `cy.intercept` with a route handler to define the alias, grabbing all instances of the alias `@alias.all` throws an error. This worked before upgrading to version 12 (verified it works with 11.2.0).

There error is:

```
cy.get() could not find a registered alias for: @alias.
You have not aliased anything yet.
```

### Desired behavior

Regardless of if you define an alias using `.as` or `request.alias`, you should still be able to access all of the alias instances using `@alias.all`.

### Test code to reproduce

I grabbed https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/net_stubbing.cy.ts#L3678-L3691 and changed the way we alias the request to expose the issue.

```js
let routeCount = 0
const uniqueRoute = (route) => {
  routeCount += 1

  return `${route}-${routeCount}`
}

it('gets all aliased Interceptions by alias.all', function () {
    const url = uniqueRoute('/foo')

    cy.intercept(`${url}*`, (request) => {
      request.alias = 'alias';
      request.reply({ bar: 'baz' });
    })
      .then(() => {
        Cypress.$.get(url)
        Cypress.$.get(url)
      })
      .wait('@alias').wait('@alias')

      cy.get('@alias.all').then((interceptions) => {
        expect(interceptions).to.have.length(2)
      })
  })
  ```

### Cypress Version

12.*

### Node version

v16.19.0

### Operating System

Debian GNU/Linux 11 (bullseye)

### Other

I was following https://github.com/cypress-io/cypress/issues/24653 and https://github.com/cypress-io/cypress/issues/25210 which seem to be related but not exactly the same. Since one issue was closed, I decided to raise this issue which shows a specific example that was working before upgrading to version 12.

**Comment by chrisbreiding** [comment]
Is it documented somewhere that setting `request.alias = 'alias'` should work? As far as I know, the only supported method for aliasing a request is with `.as()`.

**Comment by blabute** [comment]
> Is it documented somewhere that setting `request.alias = 'alias'` should work? As far as I know, the only supported method for aliasing a request is with `.as()`.

Yup! [Here](https://docs.cypress.io/guides/end-to-end-testing/working-with-graphql#Alias-multiple-queries-or-mutations) is a guide to working with graphql which happens to be our use case.

With the test I linked in the issue, `cy.wait('@alias')` works without error (which seems like the alias is getting created). It's only when accessing `cy.get('@alias.all')` that the issue happens.

**Comment by chrisbreiding** [comment]
TIL! Definitely not working as documented then. I'll route this to my team to investigate.

**Comment by fznsakib** [comment]
I'm getting the same issue when trying to access the last instance of the alias (`@alias.last`) even though the alias does come up in the list of available aliases

**Comment by blabute** [comment]
Good day!
Any updates on this issue?

**Comment by blabute** [comment]
Hello @chrisbreiding! 

Can we please have a status update on this issue?

**Comment by ittaibaratz** [comment]
Also seeing this issue with 12.14.0

**Comment by jnunez95** [comment]
Also seeing this issue with 12.15.0, have same problem before reported?

**Comment by y88huang** [comment]
Same issue with 12.17.4

**Comment by adsl88788190-QwQ** [comment]
Same issue with v13.1.0 😢

**Comment by arto80** [comment]
Same issue with v13.2.0
