### ISSUE TITLE
Cypress tests are slower when updating from 10.6 to 12.3

### ISSUE THREAD

**Issue by antti-peltola-refined** [cypress-io/cypress#25440]
### Current behavior

Test runs on macOs 13.1:
Successful test run with 10.6: 15 - 16min
Successful test run with 10.11: 16 - 17min
Successful test run with 11.2: 16 - 17min
Successful test run with 12.3: 21 - 22min
(Video disabled on all runs, 106 tests in a run)

Test runs are considerably slower when updating from 10.6 to 12.3 on macOs and similar slowdown is also happening in the CI pipelines. Seems that every test in the set is somewhat slower causing the total time to be considerably slower.

--
Originally had problem of updating 10.6 -> 10.8 that caused the tests in CI to run a lot slower and was hoping that [#23830 ](https://github.com/cypress-io/cypress/issues/23830) would solve the issue. With that fixed tests are still a lot slower than in 10.6

### Test code to reproduce

-

### Cypress Version

12.3

### Node version

v16.13.0

### Operating System

macOs 13.1

**Comment by nagash77** [comment]
Hi @anttiref , Are you able to share anything more about your specific scenario?  Unfortunately with the information you have provided there isn't much to go off of and thus I will have to close this issue until you can provide specific replication of the issues for us to troubleshoot.  Please do post back to this ticket if you are able to give specific scenarios and tests that you are seeing slower run times for.

That being said, we have work slated for this quarter and throughout the year aiming to get better performance metrics around how long tests are taking to run and making sure we do not see any further degradation.  Be sure to keep an eye on the [Cypress App Priority Board](https://github.com/orgs/cypress-io/projects/13) for future updates.
