### ISSUE TITLE
app in iframe fails when running under cypress

### ISSUE THREAD

**Issue by glendaviesnz** [cypress-io/cypress#2545]
### Current behavior:

We have an Angular SPA that has a pdf viewer running in an iframe - all running on the same domain. When running under Cypress the pdf viewer fails with some web worker errors. The viewer runs ok under Cypress if run direct rather than in an iframe. I suspect it is some issue with the proxying that Cypress is doing.

### Desired behavior:

The pdf viewer runs without errors when the app is tested under Cypress

### Steps to reproduce:

A repro of the issue can be found at https://github.com/glendaviesnz/cypress-error

### Versions

Cypress:  3.1.0
Browser - fails on chrome 69, canary 71 &, electron

**Comment by jennifer-shehane** [comment]
Error encountered:

```
cypress_runner.js:139459 Uncaught Error: [object Object] (The worker has encountered an error:Worker encountered an error. This is most likely due to browser incompatibility or memory constraints.)

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```

The error only happens when the `cy.wait(3000)` code is added like so:

```
it('fails to load reader in iframe', () => {
    cy.visit('http://localhost:4200');
    cy.wait(3000);
})
```

The error appears to be uncaught from within the PDFReaderController.js at this line:

```
me.docViewer.loadAsync(partRetriever, options);
```

Also, when I attempt to get the iframe's `<body>`, the error prints within the app's iframe.

![screen shot 2018-10-10 at 5 01 59 pm](https://user-images.githubusercontent.com/1271364/46765886-4a6f8b00-ccae-11e8-8eea-f487c08de200.png)

**Comment by glendaviesnz** [comment]
Did some more investigation on this, and after upgrading the underlying pdf redendering library the issue went away, so closing. For anyone else looking at for resolution to pdfnetjs 3.* issues with cypress then pdfnetjs 4.* resolves the issue
