### ISSUE TITLE
RangeError: offset is out of bounds when trying to render 3d objects in Cypress

### ISSUE THREAD

**Issue by addie293** [cypress-io/cypress#25453]
### Current behavior

So I am using Cypress test runner for end to end testing for an Angular application that uses threeJS to render 3d objects in the scene. Everything works fine until I ask for the 3d scene to be rendered, which is giving the error 'RangeError: offset is out of bounds' and the 3d objects are not rendered. Note, this particular error is only showing up when I am using the chrome browser/Electron for Cypress testing. Otherwise it is being rendered on chrome without Cypress.

[Chrome being controlled by Cypress](https://i.stack.imgur.com/tu6p0.png)

### Desired behavior

(https://i.stack.imgur.com/d06Td.png)

### Test code to reproduce

Try rendering anything using threeJS in a web browser controlled by Cypress.

### Cypress Version

12.3.0

### Node version

v16.15.0

### Operating System

Windows

**Comment by mike-plummer** [comment]
Hi @addie293 , thanks for opening an issue! It's not clear whether you're trying to do this using an E2E or Component Test - could you clarify? I took a quick look and was able to successfully load a variety of the threejs examples hosted at [their Examples site](https://threejs.org/examples) within a Cypress E2E test. Unfortunately we can't see this in a Component Test without a reproduction case - if you could provide one that would greatly help us diagnose and assist with your issue.

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by addie293** [comment]
Hi. I was trying E2E testing not component testing. I saw this particular workaround:https://github.com/cypress-io/cypress/issues/1194#issuecomment-528276591. But the plugin/index.js no longer exist in the latest Cypress version. So I am still wondering on how to go about this. :(

**Comment by mike-plummer** [comment]
@addie293 Plugins were removed in Cypress v10. [Here is the section of the migration guide](https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed) for that version with some information on how to port legacy plugins logic into the new `setupNodeEvents` function of your `cypress.config.js` file

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
