### ISSUE TITLE
Cypress not finding beta/dev builds of Edge on linux

### ISSUE THREAD

**Issue by CarbonCollins** [cypress-io/cypress#25455]
### Current behavior

After installing Edge Beta and Edge Dev on my machine I do not see them listed as an option to run my E2E tests against. The Stable version does appear in the UI with no issues.

### Desired behavior

After installing Edge Beta and Edge Dev on my machine I should see them listed as an option to run my E2E tests against

### Test code to reproduce

There is no test code to run as the bug appears before any tests are run.

### Cypress Version

12.3.0

### Node version

v18.12.1

### Operating System

Manjaro Linux 6.0.15-1-MANJARO

### Other

After looking into how Cypress knows about browsers I noticed two potential issues with the version regex in the `packages/launcher/lib/browsers.ts` file and the binary names.

For the version regex I'm not sure if this would be the cause of the issue but the regex for Edge Dev is `/Microsoft Edge Dev (\S+)/m` and for Edge Beta is `/Microsoft Edge Beta (\S+)/m` but when running `/usr/bin/microsoft-edge-dev --version` it returns `Microsoft Edge 110.0.1587.6 dev` which would not match the regex string. This is the same for the beta version where it returns `Microsoft Edge 109.0.1518.49 beta`

The second potential issue I see is that the Edge Beta is missing a listing for `microsoft-edge-beta` which is present for the stable and dev versions. This looks like it was done in #8931 but the beta and canary channels were missed.

**Comment by CarbonCollins** [comment]
I have raised #25456 to add the alternate binary names for Edge Beta and Edge Canary

**Comment by CarbonCollins** [comment]
#25457 was also raised to potentially resolve the version string matching

**Comment by chrisbreiding** [comment]
Thanks for posting this issue and particularly for the PRs to fix it. We'll take a look at them and get back to you with any feedback.

**Comment by CarbonCollins** [comment]
This issue still has an open PR, there were two issues found causing Cypress not to be able to find the Edge binaries. One being Manjaro linux has `microsoft-` as a prefix to the binary names and that Cypress version regex is not matching the format that Edge is returning when running `edge --version`
