### ISSUE TITLE
Environment variable `CYPRESS_PULL_REQUEST_URL` not respected

### ISSUE THREAD

**Issue by alexandervandekleutab** [cypress-io/cypress#25464]
### Current behavior

I am running Cypress in Docker in AWS ECS. When passing the `CYPRESS_PULL_REQUEST_URL`, the URL does not show up in the cloud run. 

I can see that the following environment variables are successfully passed to Docker.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/85703747/212424005-22f15e06-efcc-498d-90c4-45ce0b0f4fd6.png">

When I check Cypress cloud I can see the following:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/85703747/212424169-557a95ed-deff-4a15-9d0c-1afd556a3b8c.png">

Everything I passed seems to be working and picked up, except for the PR url.

### Test code to reproduce

The system I am testing is too complicated to provide a minimum working example... I just want to confirm if this behaviour is still expected to work or of I'm not passing the right values.
Cypress package version: 12.3.0
Cypress binary version: 12.3.0
Electron version: 21.0.0
Bundled Node version: 16.16.0

### Cypress Version

12.3.0

### Node version

14

### Operating System

Linux using node:14 as base

**Comment by davidr-cy** [comment]
@alexandervandekleutab

Could you by any chance confirm your Cypress version? Currently looking in the cloud and seeing `8.5.0` for your version in the project provided.

**Comment by alexandervandekleutab** [comment]
That's correct, it says 8.5.0. I see this environment variable was added in 12.3.0 (https://docs.cypress.io/guides/references/changelog#12-3-0). Does the cloud version need to be upgraded? Is there some documentation you can link me?

**Comment by davidr-cy** [comment]
@alexandervandekleutab I'd start with trying to make sure you're installing the most recent version of Cypress. Assuming the `8.5.0` is correct you're running an older version of Cypress that doesn't push environment variables to the cloud.

If you could confirm the version being installed in CI that'd be great.

https://docs.cypress.io/guides/references/migration-guide
