### ISSUE TITLE
websockets should be closed/disconnected when test isolation is on

### ISSUE THREAD

**Issue by bixelbg** [cypress-io/cypress#25476]
### Current behavior

I'm currently implementing logic that uses sockjs to open web socket channels in the background to read messages from. I have also implemented a logic that disconnects all web sockets in beforeEach, but that logic cannot close the channels opened by the UI insde the test, which sometimes produce issues like for example same message is read twice and counted as 2 instead of 1, when the test just wants to see how many messages have arrived in a certain channel

### Desired behavior

Web-socket channels are dsconnected and cleared on each test when test isolation is on

### Test code to reproduce

Cannot provide code, but i can provide a clip with console open to show what i mean,[ heres a link](https://www.youtube.com/watch?v=LToERg-_Us0&ab_channel=BixelBG)

### Cypress Version

12.3.0

### Node version

16.16

### Operating System

windows 11

**Comment by AtofStryker** [comment]
hi @bixelbg. Thank you for opening an issue. I know you cannot share the code, but is there anyway here to get a small reproducible example together using [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny)? It would help us greatly in debugging and figuring out what is possibly going on here.

**Comment by bixelbg** [comment]
Well I dont have access to the project code, but my cypress code contains a function that opens a websocket that goes llike this 
```js
    const onMessage = (message) => {
         //logic
      }
    };

    socket.onConnect = (frame) => {
      if (destination && onMessage) {
        socket.subscribe(destination, onMessage);
      }
    };

    socket.onStompError = (frame) => {
      console.log("ERROR", frame);
    };

    socket.activate();
```
And theres the command that closes all web socket channels i have opened:
```js
Cypress.Commands.add("closeWebSockets", () => {
  for (const socket of Cypress.env().openSockets) { 
    socket.deactivate();
  }
  env.openSockets = [];
});

```

**Comment by AtofStryker** [comment]
@bixelbg you should be able to fork [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny). Is there something else keeping you from accessing it?

**Comment by mschile** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
