### ISSUE TITLE
Add tooltip on date indicator for recorded runs in Dashboard

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#25478]
### What would you like?

In Cypress Dashboard, if you select a run and hover the time, a popup shows revealing some more info about the recorded duration. On the run date it would also be handy to have such a tooltip as the displayed date is now in relative format "4 days ago". It would be handy if the tooltip would display the actual date, eg. "Friday January 13th 2023".

<img width="736" alt="image" src="https://user-images.githubusercontent.com/599538/212851258-697254a4-d4fe-46b8-81b7-043ce81ef1e7.png">

### Why is this needed?

The current displayed info "4 days ago" may be harder for interpretation. If a test fails we sometimes need to check internal logs from a specific date. As of today (January 17th 2023) "4 days ago" is not absolutely clear on what date that was and is open for interpretation errors.

**Comment by benpatterson** [comment]
This is in the Cloud / Dashboard now. Let us know if you've got additional feedback and thanks for reporting.

![image](https://user-images.githubusercontent.com/2004678/233797327-c2754d1c-ae74-4ec0-b274-763e0981a70e.png)

**Comment by verheyenkoen** [comment]
Awesome, thanks! Also works in the overview of recorded runs I see. Brilliant!
