### ISSUE TITLE
We detected that the Chromium Renderer process just crashed

### ISSUE THREAD

**Issue by alessandrostassano** [cypress-io/cypress#25474]
### Current behavior

I need to run a single test, that is the one in the first picture. 
![image](https://user-images.githubusercontent.com/77775894/212721784-c8683316-7fad-425c-8c88-553aa5739f4a.png)

As you can see there are two nested for loops, and inside the called functions there is a recursive method that calls itself. The goal is to, given a json file with a variable number of structures, check the availability of rooms for those structures in two predefined months, and produce a report. 
The goal is that in the json file 40 structures will be indicated for 2 months approximately, and a report will be produced with the extracted data (we are talking about at least 150/160 lines of final data generated in the log file). Unfortunately, Cypress crashes right after the second structure indicated in the json is searched(after 6.30 minutes of execution) it doesn't even come close to the fortieth, and responds a blank page and sad face. How can I fix this problem? what workarounds can I use?
Is Cypress capable of handling around 480 operations, or even more?

### Desired behavior

The script runs for all the destinations specified in the json and does not crash.

example of report before it crashed:
![image](https://user-images.githubusercontent.com/77775894/212722956-31087be2-6091-4138-bc1b-ff33a54962fd.png)

### Test code to reproduce

describe('Prova Test', function () {
    it('Visit B2B', () => {

        s_CommonStep.GoToProdEasybook()

        cy.writeFile(Cypress.env('fileLogPath'), '', { flag: 'w+' })

        s_LoginStep.makeEasybookLogin()

        cy.fixture('hotels').then((file) => {

            for (const hotel of file.data.hotels) {

                let i = 0

                for (const month of file.data.months) {

                    s_HomePageSteps.SearchEveryDateAvailable(hotel, i > 0 ? false : true)

                    s_HomePageSteps.clickCorrectMonth(hotel, month, 12)

                    i++
                }
            }
        })
    }
    )
})

### Cypress Version

11.0.1

### Node version

16.17.0

### Operating System

Windows 10

**Comment by ZachJW34** [comment]
Could you share the debug logs of the run following the documentation found [here](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs).

In the next release we are introducing a feature called `experimentalMemoryManagement` that you can opt into which might help in this scenario. If you're able, could you try downloading one of our pre-release binaries found [here](https://github.com/cypress-io/cypress/commit/d1dc1258eafa6ff047abc913ebb930984e02a38d#comments) that matches your system and enable this feature in your cypress config and giving it another run?

**Comment by ZachJW34** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

We've done some work on memory management in the latest releases so please update and give it a try.
