### ISSUE TITLE
Multitude of video playing at same time

### ISSUE THREAD

**Issue by Akxe** [cypress-io/cypress#2548]
I have tried testing video playback using cypress and I am not really sure what it did, but it started the video a dozen times. I can't see more than one video at a time, but I hear the dozen. Is there anything I can do about this? Playing multiple videos at once is problematic for performance...

What is really happening and can I solve it somehow?

### Current behaviour:

I hear a dozen video playing.

### Desired behaviour:

I want to hear only one video and I need the other not to play, as that means a big performance hit for my machine otherwise.

### Steps to reproduce:
``` js
Cypress.Commands.add('playVideo', { prevSubject: 'element' }, playVideo)
/**
 * @param {JQuery<HTMLElement>} subject
 * @param {Partial<Cypress.Timeoutable>} userOptions
 */
function playVideo (subject, userOptions) {
	const options = Object.assign({ log: false }, userOptions);
	cy.wrap(subject, options).as('localVideo');
	cy.get('@localVideo', options).should('have.attr', 'aria-label').get('.vjs-big-play-button', options).click(options);
	cy.get('@localVideo', options).within($videoContainer => {
		const video = $videoContainer.find('video')[0]
		if (video.paused) {
			cy.wait(100)
			cy.get('.vjs-big-play-button', options).click()
		}
		cy.get('@localVideo', options).should('have.class', '.vjs-has-started')
	})
}

context('Video', () => {
	beforeEach(() => {
		cy.visit('https://uloz.to/live/!ueZ01YDOmTTa/lindsey-stirling-mirage-feat-raja-kumari-full-hd-mp4')
		cy.get('.video-js').as('video').playVideo()
	})

	it('Seek video', () => {
		cy.get('@video').get('.vjs-remaining-time-display').as('timeDisplay')
		cy.get('@timeDisplay').then($time => {
			const text = $time.text()
			cy.wrap(text).should('not.be.empty')

			cy.get('@video').get('.vjs-progress-control').invoke('hover').click()
			cy.get('@video').should('not.have.class', '.vjs-seeking')

			cy.get('@timeDisplay').then($time => $time.text()).should('not.equal', text)
		})
	})

	afterEach(() => {
		cy.get('.video-js').as('video').within($player => {
			/** @type {HTMLVideoElement} */
			const video = $player.find('video').get(0)
			if (video.paused) {
				cy.log('video is paused')
			} else {
				cy.get('@video').click(50, 50)
			}
		})
	})
})
```

Any test that tests video on a web page.

### Versions

Cypress: 3.1.0
OS: Windows 10
Browser: Chrome 69.x.x

**Comment by jennifer-shehane** [comment]
@Akxe Hi, could you post the test code you ran?

**Comment by Akxe** [comment]
@jennifer-shehane Any video with autoplay. Is there a way to run the whole test only once? Meaning, not to run every step in a new frame or what is done behind the scene.

**Comment by jennifer-shehane** [comment]
@Akxe When I run the code you pasted above, I get this error:

<img width="491" alt="screen shot 2018-10-04 at 2 17 29 pm" src="https://user-images.githubusercontent.com/1271364/46494214-548e1700-c7e0-11e8-839c-04c0b39ed331.png">

I also did see and hear only 1 video playing while running the test. Did you include all of the relevant test code to reproduce your issue?

**Comment by Akxe** [comment]
It is for some unknown reason very unstable... but running it multiple times it'll get trough, feel free to fix the error inside, I made it up just for demonstration purposes.

**Comment by jennifer-shehane** [comment]
Running these tests in cypress v3.2.0, I still do not get the behavior your originally described. 

<img width="406" alt="Screen Shot 2019-04-25 at 1 05 40 PM" src="https://user-images.githubusercontent.com/1271364/56714465-e5b3e380-675a-11e9-9803-af8cbb21c3fb.png">

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
