### ISSUE TITLE
Generates multiple test runs in testrail instead of a single test run

### ISSUE THREAD

**Issue by swethay** [cypress-io/cypress#2550]
### Current behavior:

<img width="1426" alt="cypress_testrail_run_1" src="https://user-images.githubusercontent.com/2423004/46313811-b13dc780-c57d-11e8-8554-d61732b32f86.png">
<img width="1429" alt="cypress_testrail_run_2" src="https://user-images.githubusercontent.com/2423004/46313813-b3a02180-c57d-11e8-90c3-68d4e52285c5.png">

### Desired behavior:

Would like to have the status of all tests to be updated in a single testrun in testrails. 

<img width="1439" alt="cypress_testrails_testrun_desired" src="https://user-images.githubusercontent.com/2423004/46313926-02e65200-c57e-11e8-9cf7-c5bcf6c3593b.png">

### Steps to reproduce:

Command used to run Past Rentals tests : cypress run  -s 'cypress/integration/ridecell/pastRentals/**/*'

Configured tests in the below format:

describe("Past Rentals Regression Suite", function () {

  it("C9748003 should be able to validate icons on Past Rentals filtered by All Services", function () {

### Versions

Cypress : 3.0.1
Operating System : MAC V 10.11.6
Browser : chrome V 69

**Comment by brian-mann** [comment]
I don't think we have anything to do with this - you're likely using a custom reporter or a custom integration which would be up to you to control on your end.

I'm going to close this issue as I don't believe its actionable for us - you likely need to open this issue with the plugin/reporter author who you're using for your TestRails service.

**Comment by katsiaryna-yurasova-zefr** [comment]
> ### Current behavior:
> <img alt="cypress_testrail_run_1" width="1426" src="https://user-images.githubusercontent.com/2423004/46313811-b13dc780-c57d-11e8-8554-d61732b32f86.png">
> 
> <img alt="cypress_testrail_run_2" width="1429" src="https://user-images.githubusercontent.com/2423004/46313813-b3a02180-c57d-11e8-90c3-68d4e52285c5.png">
> 
> ### Desired behavior:
> Would like to have the status of all tests to be updated in a single testrun in testrails.
> 
> <img alt="cypress_testrails_testrun_desired" width="1439" src="https://user-images.githubusercontent.com/2423004/46313926-02e65200-c57e-11e8-9cf7-c5bcf6c3593b.png">
> 
> ### Steps to reproduce:
> Command used to run Past Rentals tests : cypress run -s 'cypress/integration/ridecell/pastRentals/**/*'
> 
> Configured tests in the below format:
> 
> describe("Past Rentals Regression Suite", function () {
> 
> it("C9748003 should be able to validate icons on Past Rentals filtered by All Services", function () {
> 
> ### Versions
> Cypress : 3.0.1
> Operating System : MAC V 10.11.6
> Browser : chrome V 69

Hello. I fixed this issue for me and loaded into a separate package:
https://www.npmjs.com/package/cypress-testrail-accumulative-reporter

**Comment by mdp27** [comment]
Also faced the same issue and the updated reporter above fixed the problem.
