### ISSUE TITLE
Unable to start Cypress 12.2 / 12.3 due to missing module

### ISSUE THREAD

**Issue by darioackermann** [cypress-io/cypress#25515]
### Current behavior

After installing cypress `npx cypress verify` runs through with
`√  Verified Cypress! C:\Users\username\AppData\Local\Cypress\Cache\12.3.0\Cypress`

`npx cypress open` fails with

```[33984:0119/162225.116:ERROR:resource_bundle.cc(991)] Failed to load C:\Users\username\AppData\Local\Cypress\Cache\12.3.0\Cypress\resources.pak
Some features may not be available.
Error: Cannot find module 'socket.io-client/dist/socket.io.js'
Require stack:
- C:\Users\username\AppData\Local\Cypress\Cache\12.3.0\Cypress\resources\app\packages\socket\index.js
```

### Desired behavior

Cypress should start

### Test code to reproduce

* Be on a windows machine
* Install cypress 12.2 / 12.3 via npm
* Run `npx open cypress`

### Cypress Version

v.12.2.0 / 12.3.0

### Node version

v.18.13.0

### Operating System

Windows 10

### Other

Downgrading to 12.1 resolves the issue.

**Comment by ZachJW34** [comment]
I wasn't able to reproduce your error on my Windows machine. There is a possibility that something went wrong when downloading the binary, can you try running `npx cypress cache clear` from within your project and then reinstalling?

Also, did you download Cypress directly or via `npm i cypress`?

**Comment by darioackermann** [comment]
It looks like that something during the installation of both, v.12.2 and v.12.3 went wrong and I incorrectly assumed that `npx cypress verify` would perform checksum tests or some sort of these. Clearing the cache worked. Thank you!

**Comment by MikeMcC399** [comment]
I also hit this issue and I suspect it was because I interrupted the installation.
`npx cypress install --force` or
`yarn cypress install --force` (depending on the package manager in use)
should make sure that the installation of Cypress is complete.

**Comment by SARAN369** [comment]
Thanks a lot !!! @MikeMcC399 i would be working now
