### ISSUE TITLE
Cypress with microsoft edge on mac os

### ISSUE THREAD

**Issue by stephenjason89** [cypress-io/cypress#25511]
### Current behavior

<img width="918" alt="image" src="https://user-images.githubusercontent.com/3810177/213365118-604ee88d-bf2b-40c3-a21e-d44752fc9723.png">

### Desired behavior

I expect that it would have no errors on microsoft edge.
It is working great with chrome and electron

### Test code to reproduce

Platform: darwin-arm64 (22.2.0)
Cypress Version: 12.3.0
Microsoft Edge Version 109.0.1518.52 (Official build) (arm64)

### Cypress Version

12.3.0

### Node version

v18.10.0

### Operating System

mac os 13.1

### Debug Logs

```shell
read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT
```

**Comment by AtofStryker** [comment]
@nagash77 do we have anyone on firewatch who might be able to try this on M1 mac? I think we have had a few internal team members run into this issue.

**Comment by mschile** [comment]
Hi @stephenjason89 👋, I was able to successfully load Edge on an M1 Mac. Are you still having this issue?

**Comment by stephenjason89** [comment]
Hello @mschile I can confirm that everything is working well on my other MacOS Intel i9
However, let me get back to you tomorrow to check on my m1 Mac. Will be updating to the latest cypress first.

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by stephenjason89** [comment]
@mschile Sorry, must have completely forgotten this.
I just tested it now with 12.5.1 component testing. 
And everything seems to work just fine now.
Thank you so much
