### ISSUE TITLE
The email svc_responsible-disclousure@cypress.io does not exists.

### ISSUE THREAD

**Issue by mauriciocarnieletto** [cypress-io/cypress#25524]
### Current behavior

In the page 

https://www.cypress.io/security/

The "[Report a security issue](mailto:svc_responsible-disclousure@cypress.io?subject=Report%20a%20Security%20Issue&body=I%20would%20like%20to%20report%20a%20security%20issue%20with%20one%20of%20the%20Cypress%20services)" button, redirect us to an email hyperlink.

The email doesn't exist, as it's returned.

### Desired behavior

The email should exists.

### Test code to reproduce

Go to the page 

https://www.cypress.io/security/

Click in the "Report a security issue"

Write anything

Wait a little bit

Check your e-mail account.

### Cypress Version

N/A

### Node version

N/A

### Operating System

N/A

**Comment by nagash77** [comment]
Hi @mauriciocarnieletto , Thank you so much for entering this ticket and bringing this to our attention.  We have an update going out today that should fix that.  Thank you again.
