### ISSUE TITLE
is being covered by another element:

### ISSUE THREAD

**Issue by nameetjambla** [cypress-io/cypress#25525]
#### Here is My code and I am facing the error display in the screenshot can you please provide me the solution
for the same 

![cypress bug](https://user-images.githubusercontent.com/79189939/213670229-abd690e5-17a6-41b7-8dd5-26718d023fd1.png)

### Desired behavior

Not Sure why It is picking the child element 

### Test code to reproduce

```js
it.only('Edit Websites', () => {
   
    Cypress.on('uncaught:exception', (err, runnable) => {
        // returning false here prevents Cypress from
        // failing the test
        return false
    })
    require('@4tw/cypress-drag-drop')
    const dataTransfer= new DataTransfer()
    cy.viewport(1280, 720)
    cy.visit('https://rapify.com/index.php/auth/login')
    cy.get('input[id="icon_prefix"]').clear()
    cy.get('input[id="icon_prefix"]').type('minakshi.mahajan@ajdevtech.com')
    cy.get('input[id="icon_telephone"]').clear()
    cy.get('input[id="icon_telephone"]').type('kn1e#f_$Sm6A')
    cy.get('button[type="submit"]').click()
    cy.wait(5000)
    cy.get('ul#nav-mobile > li:nth-of-type(1) > .nav-icon1').click()
    cy.get('input#search_filter_sites').type('nameetjambla')
    cy.get('a#search_sites').click()//search website
    cy.get('.dash-niche-btns-inner.my-site > a:nth-of-type(2)').click()
    cy.get('h3#sectionH3').click()
    cy.get('ul#bigmenuscrollspy  a#images').click().should('have.text','Images')// click on Images section
    cy.wait(3000)
    cy.get('ul#imagesspy  h1').should('contain','Images')
    // cy.get('#pageList').should('be.hidden')
    // cy.get('#page1').should('be.visible')
    cy.get('ul#imagesspy > li:nth-of-type(5) > img[alt="Loading Image..."]').drag('div#pageList > .rapify_ul_index.ui-sortable')
    //cy.get('#start').trigger('drop',{dataTransfer})   
    
   // cy.get('a#close_menus_right > .fa.fa-times').click()
```

### Cypress Version

11.2.0

### Node version

8.1.2

### Operating System

Windows 10

**Comment by nameetjambla** [comment]
Instruction

When You run my test case at first it gets failed because some of the API takes time to load. However, I suggest you to wait until the entire page is loaded, and after that refresh the test page and then you will get the error that I have mentioned.

**Comment by ZachJW34** [comment]
Have you tried using `cy.drag('...', { force: true })`? 

I ran the test and adding that worked fine. There isn't a bug with Cypress, the drop-zone is covered by an element that disappears as you drag an item over it so `{ force: true }` is the solution here.

If there are issues with the drag, you should open an issue in `@4tw/cypress-drag-drop`.

**Comment by pillsi** [comment]
I am seeing the same issue, have you found any resolution?
