### ISSUE TITLE
Custom command add with prevSubject = 'optional' missing from typescript definition

### ISSUE THREAD

**Issue by stef-demesel** [cypress-io/cypress#25526]
### Current behavior

Can't use 'optional' as a string using the typescript definitions for parameter prevSubject when adding a custom command, even though it's in the api documentation.
https://docs.cypress.io/api/cypress-api/custom-commands

![image](https://user-images.githubusercontent.com/9214329/213691766-2865cf10-1d20-4ffa-b95e-d541cb8dc28f.png)

### Test code to reproduce

```js
Cypress.Commands.add(
  'typescriptBroken',
  {
    prevSubject: 'optional',
  },
  (): Cypress.Chainable<JQuery<HTMLElement>> => {
    return cy.get('');
  }
);
```
### Cypress Version

12.3.0

### Node version

16.19.0

### Operating System

Windows 10.0.19045

**Comment by mschile** [comment]
Hi @stef-demesel 👋, thanks for logging this issue. The typescript definition for `optional` (along with `element`, `window`, and `document`) is located here:

https://github.com/cypress-io/cypress/blob/dfb28b0369c0b25f567a458f344d0a507ff23ac4/cli/types/cypress.d.ts#L588-L590

Let me know if you are still having issues with the definition.

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by mycarrysun** [comment]
I'm getting the exact same error and I think there may be something wrong with the typescript types - this only started happening after upgrading to v13.1.0.

I'm trying to use the example from the documentation website:
```ts
declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Custom command to type a few random words into input elements
       * @param count=3
       * @example cy.get('input').typeRandomWords()
       */
      typeRandomWords(
        count?: number,
        options?: Partial<TypeOptions>
      ): Chainable<JQuery<HTMLElement>>
    }
  }
}

Cypress.Commands.add(
  'typeRandomWords',
  {
    prevSubject: 'element',
  },
  (subject, count = 3, options?) => cy.wrap(subject).type('some random words', options),
);
```

And it gives me this error:
![Screen Shot 2023-09-01 at 1 49 19 PM](https://github.com/cypress-io/cypress/assets/9121901/5abe1b23-23c3-4c7f-8cf0-bba00ba5e26c)

**Comment by javifm86** [comment]
Same here, v.12.4.0.
