### ISSUE TITLE
Feat: support android platform

### ISSUE THREAD

**Issue by SunPodder** [cypress-io/cypress#25532]
### What would you like?

I'd like to be able to run cypress on an android device. Maybe by compiling the cypress executable on our own and manually providing that to the install script if you can't officially support it?

For now the post-install script throws an error saying platform android is not supported.

### Why is this needed?

I see many people nowadays learning programming who can't afford a computer but have a mobile phone. I hope it will be helpful to them all.

**Comment by nagash77** [comment]
Hi @SunPodder ,  Thank you for submitting this feature request.  Unfortunately, this feature is not something Cypress is currently prioritizing and will not be addressing any time soon.
