### ISSUE TITLE
beforeEach - (uncaught exception)

### ISSUE THREAD

**Issue by pedrogomes97** [cypress-io/cypress#25545]
### Current behavior

The beforeEach hook contains actions to login to a product and it works correctly
![image](https://user-images.githubusercontent.com/71712582/214082091-dcb8df02-73eb-402b-a77e-222cb0d4c4e3.png)

But for some reason when starting a the second test, it fails with the error: 
(uncaught exception)TypeError: Cannot read properties of undefined (reading 'createRange')

![image](https://user-images.githubusercontent.com/71712582/214081667-60d49387-86a9-41e8-b41c-f86aaa708a97.png)

Even if you don't put any command (or just a cy.log) inside the beforeEach() and pass the login inside the it() of the 2 tests, the error happens in the beforeEach when starting the second test.

![image](https://user-images.githubusercontent.com/71712582/214086241-063a284b-18bc-42be-ae60-c778915c0aff.png)

If I remove the beforeEach() the tests pass. I could remove the beforeEach() hook, but this is not a solution. The command exists to avoid code replication.

![image](https://user-images.githubusercontent.com/71712582/214089852-69ddc508-3e1b-420d-8da5-7b53e2be8535.png)

I tried adding cy.wait(100) at the end of the first test and it works every time. So I can conclude that the beforeEach problem must be related to some dependency of the previous test, which should not happen.

![image](https://user-images.githubusercontent.com/71712582/214098752-4413fc4b-2c28-4991-9950-e56f96dc91d5.png)

I have tests with beforeEach working correctly, only this one fails with this constant error, although I have already managed to reproduce it in other scenarios.

### Desired behavior

It would be expected that beforeEach works correctly and does not need to replicate the login in all tests.

### Test code to reproduce

This scenario is only reproduceable on our company test solution, so I can't share a reproduceable scenario,  but I can schedule a call to be reviewed if you want so.

### Cypress Version

12.3.0

### Node version

v16.19.0

### Operating System

Windows 10

### Debug Logs

```shell
VM1511 polyfills.2269035e20e0ae82cc9c.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'createRange')
    at p (VM1605 tinymce.min.js:9:229210)
    at Object.getNode (VM1605 tinymce.min.js:9:231820)
    at o (VM1605 tinymce.min.js:9:150805)
    at VM1605 tinymce.min.js:9:151838
    at VM1605 tinymce.min.js:9:35351
    at m.<computed> (VM1511 polyfills.2269035e20e0ae82cc9c.js:1:41149)
    at v.invokeTask (VM1511 polyfills.2269035e20e0ae82cc9c.js:1:8279)
    at v.runTask (VM1511 polyfills.2269035e20e0ae82cc9c.js:1:3337)
    at v.invokeTask (VM1511 polyfills.2269035e20e0ae82cc9c.js:1:9413)
    at invoke (VM1511 polyfills.2269035e20e0ae82cc9c.js:1:9304)
```

**Comment by nagash77** [comment]
Hi @pedrogomes97 , I'm sorry to hear you are having issues running Cypress.  Unfortunately we will not be able to dig deeper into this issue without a reproducible example.  Is it possible to create an example using a fork of https://github.com/cypress-io/cypress-test-tiny which points to externally facing resources?  An example spec file would be very helpful.  Screenshots of the code are difficult to work with for our engineers.

**Comment by pj-alves** [comment]
There is a workaround for that

Add to e2e.js the following code

```
 Cypress.on('uncaught: exception', (err, runnable) => {
    if (err.message.includes('Cannot read properties of undefined')) {
      return false
    }    
  })
```
  
  This will cause cypress to ignore every uncaught exception with a message like the one you are getting and continue the test as nothing happened.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
