### ISSUE TITLE
Cy.contains ignoring timeout

### ISSUE THREAD

**Issue by tymoteusz-duraj** [cypress-io/cypress#25542]
### Current behavior

Inside custom command I've added `contains` method with timeout, but it's look like Cypress is ignoring this config. 
It's immediately returns info "0 matched elements" and moving to next commands. It happens in afterEach hook

<img width="410" alt="image" src="https://user-images.githubusercontent.com/69631387/214028666-2216dbd3-d832-4f22-881b-4876f01dc723.png">

### Desired behavior

Wait for the element be visible

### Test code to reproduce

```
Cypress.Commands.add("getElementByText", (text) => {
  cy.visit("/example-route");

  cy.contains(text, { timeout: 20000 });
  cy.contains(text, { timeout: 20000 }).should("exist");
});
```

### Cypress Version

12.3.0

### Node version

14.17.5

### Operating System

macOS 13.0

**Comment by nagash77** [comment]
@tymoteusz-duraj Can you help me understand your use case a bit more?  Cypress will wait for the DOM to be ready before searching for the given element so you should not need to set a timeout.  Have you read through the [best practices on using cy.contains](https://docs.cypress.io/api/commands/contains#docusaurus_skipToContent_fallback)?

**Comment by tymoteusz-duraj** [comment]
So it's look like this: This is the page with table. Table is invisible until the data from 3 endpoint will return response. I want to find specific record in that table and do another operations. That's why I added long timeout to `contains`. 
I tried also to intercept those records and wait until all will be complete using `cy.wait(["@req1", "@req2", "@req3"])`, but this also not work. In that case as soon as first request will complete Cypress is moving to another commands (arguments in `.then` are `[response, undefined, undefined]`;
Both of cases (contains and wait) work fine in e.g `beforeEach` hook

**Comment by mschile** [comment]
@tymoteusz-duraj, I was unable to reproduce your reported issue. I wrote a custom command that used `cy.within` with a custom timeout and it correctly waited for the command in an `afterEach` hook. Here is the example [repo](https://github.com/mschile/cypress-test-tiny/tree/issue-25542) I used. Would you be able to recreate the issue in a reproduction repository by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny)?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
