### ISSUE TITLE
Cypress for linux not available under request URL

### ISSUE THREAD

**Issue by wiedehoeft** [cypress-io/cypress#25565]
### Current behavior

Cypress tries to download from here: https://download.cypress.io/tools/cypress/12.3.0.zip?platform=linux&arch=x64
But the versions seems missing here: `Cannot GET /tools/cypress/12.3.0.zip`

### Cypress Version

12.3.0

### Node version

18.13.0

### Package Manager

npm

### Package Manager Version

8.19.3

### Operating system

Linux

### Operating System Version

20.04.5 LTS

**Comment by ZachJW34** [comment]
How are you downloading cypress, via `npm i cypress` and are seeing this error? Does the error occur with the latest released version of Cypress (12.4.1 at the time of writing this)?

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
