### ISSUE TITLE
Interleave logging statements from e.g. Redux/redux-observable

### ISSUE THREAD

**Issue by haf** [cypress-io/cypress#2556]
It would be great if I could inject log messages into the "list" of commands that cypress does, in order to get an immediate idea of what redux (or otherwise) actions have been run at the time of a wait for command to complete, or inbetween running promises inside cypress. Put another way: support logs outside of commands. Useful for correlation of events in you UI.

### Current behavior:

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/193115/46365069-e4fd1800-c677-11e8-9fe6-3f4458d47c97.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/193115/46365087-edede980-c677-11e8-92e1-947bdca31565.png">

### Desired behavior:

I'd like to interleave logging statements; having them show up as parallel to a Promise executing, for example.

This would allow me to understand the sequence of events in the app (besides the DOM changes) that led to the state I'm debugging. E.g. "Did an action fire before or after the Promise resolved?"

### Versions

Latest AFAIK

**Comment by Bkucera** [comment]
@haf try using [Cypress.log](https://docs.cypress.io/api/cypress-api/cypress-log.html#Syntax)

**Comment by jennifer-shehane** [comment]
Hey @haf were you able to solve your issue?

**Comment by haf** [comment]
How is this awaiting a response?

**Comment by jennifer-shehane** [comment]
Awaiting hearing if changing code to `Cypress.log` resolves the issue - or testing this ourselves.

**Comment by haf** [comment]
That said; perhaps Cypress.log does what it says on the tin, perhaps it doesn't. I've only received a comment to try Cypress.log but no reason or indication as to why I should expect it to work any better than with my window.Cypress.cy.log.

**Comment by haf** [comment]
Just to be clear; no this is not the solution @jennifer-shehane because you don't have access to `Cypress.log` from your browser-JS code, only from the unit test code. So you can kindly remove the `awaiting response` label.

**Comment by Bkucera** [comment]
@haf you have access via `window.Cypress.log`. using that, you should be able to log messages without getting the error you originally posted. 

Thanks for your patience!

**Comment by haf** [comment]
Finally a real answer @Bkucera ! Awesome. Thanks.
