### ISSUE TITLE
IATR - M1.0 Add links to documentation to empty states

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25570]
In order to provide more context around the value for the Debug page, the user should see links out to our documentation to better explain the feature and the steps needed to take advantage of it.

Slack thread: https://cypressio.slack.com/archives/C042Y29PWCD/p1674568897232099

Add links to the docs site to each empty state page.  Add the link to the end of the body copy.  See linked Figma designs below

| Page | Link to add | On link tag |
| --- | ---- | ---- |
| Logged out empty state |  Learn about debugging CI failures in Cypress | `debug-page` 
No project empty state | Learn about project setup in Cypress | `adding-new-project`
No recorded run | Learn about recording a run to Cypress Cloud | `cypress-run-record-key`

Figma link to empty states: https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=21167%3A199979&t=pgCiFSsUyFVY0bLh-1

**Comment by pstakoun** [comment]
@astone123 quick note on this, these links should all include UTM parameters
