### ISSUE TITLE
Blocker - XLSX.readFile - Cannot access file

### ISSUE THREAD

**Issue by Anne4444** [cypress-io/cypress#25604]
### Current behavior

If I run the XLSX.readFile command, when starting the specification on the browser runner I always get the error Cannot access file.
![image](https://user-images.githubusercontent.com/123552370/215037172-ad9e79ce-433b-45b9-9bab-b8b59d949e47.png)

### Desired behavior

There should be no error.

### Test code to reproduce

**Cypress Script which does not work:** 
```js
function getDataFromHtmlWatchlistIntoJson() {
  const XLSX = require("xlsx");
  // Pfad zur Excel-Datei
  const filePath = "C:\\downloads\\Mappe1.xlsx";
  // Lesen der Excel-Datei
  const workbook = XLSX.readFile(filePath);
  // Erste Arbeitsmappe auswählen
  const sheetName = workbook.SheetNames[0];
  const worksheet = workbook.Sheets[sheetName];
  // Konvertieren der Arbeitsmappe in JSON
  const jsonData = XLSX.utils.sheet_to_json(worksheet);
  // Setzen des Debug-Punkts
  debugger;
  // Ausgabe der Daten auf der Konsole
  console.log(jsonData);
}

describe("template spec", () => {
  it("passes", () => {
    getDataFromHtmlWatchlistIntoJson();
  });
});

```
----------------------------------------

**Java Script with which it works fine on node v18.13.0 (note: The version is higher than the one used by Cypress.)**
```js
const XLSX = require("xlsx");
// Pfad zur Excel-Datei
const filePath = "C:\\downloads\\Mappe1.xlsx";
// Lesen der Excel-Datei
const workbook = XLSX.readFile(filePath);
// Erste Arbeitsmappe auswählen
const sheetName = workbook.SheetNames[0];
const worksheet = workbook.Sheets[sheetName];
debugger;
// Konvertieren der Arbeitsmappe in JSON
const jsonData = XLSX.utils.sheet_to_json(worksheet);
// Ausgabe der Daten auf der Konsole
console.log(jsonData);
```
### Cypress Version

12.4.0

### Node version

16.16.0

### Operating System

Windows 11

### Debug Logs

```shell
**Stack trace from cypress:**
at read_binary ([webpack:///./node_modules/xlsx/xlsx.mjs:3234](http://localhost:62430/__/#))
at readSync ([webpack:///./node_modules/xlsx/xlsx.mjs:23811:63](http://localhost:62430/__/#))
at Module.readFileSync ([webpack:///./node_modules/xlsx/xlsx.mjs:23851](http://localhost:62430/__/#))
at getDataFromHtmlWatchlistIntoJson ([webpack:///./cypress/e2e/lib.cy.js:80:24](http://localhost:62430/__/#))
at Context.eval ([webpack:///./cypress/e2e/lib.cy.js:109:6](http://localhost:62430/__/#))


**Debug logs from js-Skript on node:**
(2) [{…}, {…}]
0:
{name: 'jhjhjh', alteri: 987, __rowNum__: 1}
1:
{name: 'tztzt', alteri: 55, __rowNum__: 2}
length:
2
[[Prototype]]:
Array(0)
[[Prototype]]:
Object
```

**Comment by AtofStryker** [comment]
Hi @Anne4444. Thank you for opening an issue. I think the issue you are running into is trying to run `xlsx` in the browser with the `readFile` method, which is a node only method. To work around this, you can leverage `cy.task` in your test to read the file and import its results into the test. I put together an example [here](https://github.com/AtofStryker/cypress-issue-25604/blob/main/cypress.config.js#L27) to show how to do this. I hope this helps and let us know if you run into any other trouble.

**Comment by Anne4444** [comment]
Thanks, great, it works now with 
jsonData = cy.task('readXlsxFile')

**Comment by swagajulcisco** [comment]
> assignment

Inspite of doing a copy paste of this exact code in the on('task') in cypress.config, it says that cy.task is not registered. Can someone help. This reading from excel is taking over a week and no resolution

**Comment by AtofStryker** [comment]
@swagajulcisco can you open a new issue with a reproduction?

**Comment by danilogacevic** [comment]
I'm getting this error 

`file:///C:/Users/Daco/OneDrive/Desktop/upisivanje_racuna/node_modules/xlsx/xlsx.mjs:3234
        throw new Error("Cannot access file " + path);
              ^

Error: Cannot access file tabela/Potrosnja_el_en_nove_tabele.xlsx
    at read_binary (file:///C:/Users/Daco/OneDrive/Desktop/upisivanje_racuna/node_modules/xlsx/xlsx.mjs:3234:8)
    at readSync (file:///C:/Users/Daco/OneDrive/Desktop/upisivanje_racuna/node_modules/xlsx/xlsx.mjs:23811:69)
    at Module.readFileSync (file:///C:/Users/Daco/OneDrive/Desktop/upisivanje_racuna/node_modules/xlsx/xlsx.mjs:23851:9)
    at file:///C:/Users/Daco/OneDrive/Desktop/upisivanje_racuna/index.mjs:11:23
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)`

I'm running file _index.mjs_ with node.je command `node index.mjs` locally on my pc (OS Windows 10). Here is my code:

`// index.mjs
import * as XLSX from 'xlsx/xlsx.mjs';

import { extractDataFromPDF } from "./extractDataFromPDF.mjs";
import { insertDataToExcelFile } from "./insertDataToExcelTable.mjs";


let tabela = 'tabela/Potrosnja_el_en_nove_tabele.xlsx'


const workbook = XLSX.readFile(tabela);`

**Comment by millionbug** [comment]
have you resolve this error, i have encountered the same problem

**Comment by hookdump** [comment]
Same issue!

**Comment by owjoel** [comment]
According to the SheetJS docs, when using ES modules, you have to manually load the fs for xlsx.

import fs as "fs";
set_fs(fs);

**Comment by rachid-debu-prbob** [comment]
> According to the SheetJS docs, when using ES modules, you have to manually load the fs for xlsx.
> 
> import fs as "fs"; set_fs(fs);

you just solved me a big hastle, i was wondering what was going on
