### ISSUE TITLE
Always giving socket timeout running from virtual machine for cypress-ntlm

### ISSUE THREAD

**Issue by akeeramp** [cypress-io/cypress#25602]
### Current behavior

We are having an application using window authentication and we are using cypress-ntlm to run the test. Every time we run the test from a virtual machine it fails  and working fine in local machine. The config and setup are same as the local machine in VM. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/94591893/215027458-44622530-7b43-431c-b073-a7cf2df9254a.png)

### Test code to reproduce

This is an intranet application which will not be able to test publicly.

describe('Testing',()=>{  it('Opening Website... ',()=>{       
cy.ntlmReset();      
 cy.ntlmSso(['*.internaldomain.com'])  
 cy.visit('https://internalWebsite.internaldomain.com/',{timeout: 1800000});    
  Cypress.on('uncaught:exception',(err,runnable)=>{        
return false      })
  })})

### Cypress Version

cypress:10.11.0 , cypress-ntlm-auth:4.1.1

### Node version

v14.15.4

### Operating System

Windows

**Comment by nagash77** [comment]
Hi @abhilash-keerampara , this sounds like it is a problem with this external plugin you are using.  You should open an issue with the plugin author.

**Comment by akeeramp** [comment]
Thanks  and will raise a issue there
