### ISSUE TITLE
Custom commands with callbacks

### ISSUE THREAD

**Issue by jamesarosen** [cypress-io/cypress#25617]
### What would you like?

I'd love to be able to write a custom command that takes a callback. The built-in [within command](https://github.com/cypress-io/cypress/blob/95ee9b9005e9ad013039b99bb7177dba203c9fcd/packages/driver/src/cy/commands/querying/within.ts#L28) takes a callback, but the queue-manipulation APIs it uses are not public.

### Why is this needed?

I want to write a command that combines `cy.intercept`, `cy.wait`, and `cy.url` to group together some behavior and expectations about page transitions.

Example:
```js
cy.shouldTransition("/next-page", () => {
  cy.contains("a", "Next").click();
});
cy.contains("h2", "Next Page");
```

This would be a wrapper for
```js
cy.intercept("/next-page**", req => req.continue()).as("pageLoad");

// callback:
cy.contains("a", "Next").click();

cy.wait("@pageLoad");
cy.url().should("eq", "/next-page");

// after custom command
cy.contains("h2", "Next Page");
```

But no matter how I write `shouldTransition`, Cypress will move on to `cy.contains("h2", "Next Page");` before I get to the callback.

**Comment by emilyrohrbough** [comment]
@jamesarosen Can you please share details on how you have written your custom command?

**Comment by jamesarosen** [comment]
I'm not longer working on that project, so I don't have access to the source code, but I believe it looked something like this:
```js
Cypress.commands.add("shouldTransition", (newPath, callback) => {
  cy.intercept(`${newPath}**`, req => req.continue()).as("pageLoad");
  callback();
  cy.wait("@pageLoad");
  cy.url().should("eq", newPath);
});
```

Looking at that, I don't see why the `cy.contains("a", "Next").click();` (within the `callback`) wouldn't be added to the Cypress queue before the `cy.wait("@pageLoad")`.

I wonder if I'm forgetting a `.then` or `.should` somewhere in there.

**Comment by emilyrohrbough** [comment]
I was able to successfully use the custom command you provided and the queue executed in the correct order:

```js
// cypress/support/commands.js
Cypress.Commands.add("shouldTransition", (newPath, callback) => {
  cy.intercept(`${newPath}**`, req => req.continue()).as("pageLoad");
  callback();
  cy.wait("@pageLoad");
  cy.url().should("eq", newPath);
});
```

```js
// cypress/e2e/spec.cy.js
  it('use custom command with callback', () => {
    cy.visit('https://example.cypress.io')

    cy.shouldTransition("https://example.cypress.io/commands/querying", () => {
      cy.contains("a", "Querying").click({ force: true });
    });
    cy.contains("h1", "Querying")
  })
```

![Image](https://user-images.githubusercontent.com/14099737/230649207-1c1ed49e-3e94-4df7-980e-4d7dfcab76c6.png)


Closing as this is supported today.
