### ISSUE TITLE
Login button is in enabled state when it is not in use

### ISSUE THREAD

**Issue by mMARUF** [cypress-io/cypress#25629]
### Steps to Reproduce

1. Install Cypress 12.4.1
2. Open cypress dashboard
3. Press on the Login button
4. After click the Login button goes to enabled state and becomes blue and a pop-up opens
5. Now close the pop-up

### Current behavior

Thought the pop-up is closed and the Login button is not clicked /selected, the Login button is blue as if the Login button is enabled.

### Desired behavior

After the pop-up is closed, the Login button should not look Blue. 

### Cypress Version

12.4.1

### Node version

16.15.0

### Operating System

macOS Ventura 13.1

### Note
Same issue happens with other buttons also. Though the buttons are not selected, the buttons look Blue as if those buttons are in selected state.

### Attachment
![Login button is in enabled state when it is not in use](https://user-images.githubusercontent.com/45368054/215550329-bb0eaf67-def8-46c3-9b20-210f7b36d2f4.gif)

**Comment by warrensplayer** [comment]
@ mMARUF I believe what you are seeing is the "focus" state of those buttons.  So once you click on the button, it is now the element in focus on the page. If you tab around on the page, you can see the focus move between the buttons.  This is the current expected behavior for those button states.

**Comment by mMARUF** [comment]
When we click on the **Login** button, it makes sense that the **Login** button should be in focus state. But, when we have closed the Login dialog, then the **Login** button should not be in focus state.

This issue is in other buttons also. For example- if you click on the **Docs** button, the button is on focus and becomes blue and a dropdown opens. Then, if you press on **Docs** button again, the dropdown closes, but the button is still in focus (and looks blue).

So, the point is, when the user has closed the Login dialog, that means, the user is not working with the **Login** button anymore and that is why it should go out of focus. Also, for DOCS button – when the dropdown is closed, that means that the user is not interacting with the button anymore and the button should go out of focus.

**Comment by warrensplayer** [comment]
@mMARUF You can think of the behavior like a menu. When a user clicks the login button, it opens the nested part of the menu which is the Login dialog.  Then, when the dialog is closed, the focus stays on the menu.  That design is currently the intended pattern.
