### ISSUE TITLE
Option to run tests only against staged files

### ISSUE THREAD

**Issue by MikeDupree** [cypress-io/cypress#25628]
### What would you like?

I'de like to be able to run cypress tests for only changed files under git. The goal would be to have an argument I could pass to the CLI ie `cypress run --component --staged` which would parse the `git diff` output and run tests based on the output

For example if I had a diff that looked like this 

```
src/component/ComponentA
src/component/ComponentB
```

the functionality would read this from the diff and build a string `src/component/ComponentA,src/component/ComponentB`

which would be used to filter what tests to run.

Same as running `cypress run --component --spec src/component/ComponentA,src/component/ComponentB`

### Why is this needed?

I find this functionality useful in some projects I work on which contain many tests and having to run tests for files which havent changed is unecessary. Currently we have our own custom script for handling parsing and running the tests but would be interested in building this into Cypress itself.

### Other

This issue is mainly to determine interest from the team. I would be willing to contrib this feature but would like to understand if it's something the team thinks is valid to add to Cypress core codebase.

**Comment by mirobo** [comment]
Had the same idea too and ended with this

```
  var specList = execSync(`git diff --name-only --diff-filter=AM HEAD **/folder-with-specs/**/*.e2e.spec.ts`)
    .toString('utf-8')
    .split('\n')
    .filter((s) => s?.length > 0)
    .map((s) => s.replace('base-path-until-folder-with-specs', '**'));

  const config = {
   ..
    config: {
      e2e: {
        specPattern: specList
      },
  ...
  };
```

I started to look into how the Cypress UI was built and thought of adding a toggle button near the spec search input (in the first search input and in the search input within the runner UI). It was so crazy complicated... the spec list displays the Git data in a column but I couldn't reuse it in an easy way to add more elaborate filtering... doesn't seem fun to develop in there at first sight :D

I'd be happy to see a toggle button "Show only untracked/modified files" and - as you suggest - a command line option.

**Comment by MikeDupree** [comment]
I do something very similiar, essentially just a script that checks diff, has some project configurations for when it's used in a monorepo vs a single project repo. It seems like a good feature to implement. I haven't taken the time yet to start reviewing the codebase for cypress to see how difficult it would be to implement. I plan to start later this week/ weekend.

**Comment by marktnoonan** [comment]
Hi @MikeDupree thanks for this suggestion. I like the idea of running specs for staged files only. That said, we've reviewed it and this is **not** something we would bring into the Cypress CLI. The main reason is, as you point out, this is already possible in userland with the `--spec` parameter, so folks who choose to do this can already do it without expanding the Cypress CLI. 

I do think open mode is a different story, and this may be something we can factor into the future expansion of "run all specs" functionality. Since "run all" runs whatever is filtered, if users are able to filter with the git status in the UI, we would be able to get this behavior in open mode, which might ultimately be more useful.

For now I'm just going to link this issue to the Run All discussion https://github.com/cypress-io/cypress/discussions/21628

**Comment by MikeDupree** [comment]
Understandable! Thanks for reviewing this @marktnoonan

**Comment by marktnoonan** [comment]
Appreciate your suggestion also @mirobo 👍

**Comment by mirobo** [comment]
@marktnoonan 
> I do think open mode is a different story, and this may be something we can factor into the future expansion of "run all specs" functionality. Since "run all" runs whatever is filtered, if users are able to filter with the git status in the UI, we would be able to get this behavior in open mode, which might ultimately be more useful.

I've added a small (and ugly) proposition here for the UI: https://github.com/cypress-io/cypress/discussions/21628#discussioncomment-5740911

It frees up more horizontal space and leaves space for spec filtering presets

Personally I also think that it makes a lot more sense to have this feature in open mode. But once you add the option for "open" mode, I don't see any harm in also adding the same option to the CLI :-P.

I wanted to personally contribute to my UI suggestion above, but it was quite difficult for me to find the correct entry point where the Git information is gathered and bubbled up to the actual UI component..

**Comment by marktnoonan** [comment]
@mirobo thanks for that suggestion. I think it's logged in the right place and we can bear it in mind for future changes to these parts of the UI. I'm not sure we will be able to do away with the main specs list view any time soon, so I'm glad you had not gone to the trouble of a full-on PR for this. But I totally appreciate the clarity of a screenshot as you did it.

> But once you add the option for "open" mode, I don't see any harm in also adding the same option to the CLI :-P.

Fair point, we could re-asses then.
