### ISSUE TITLE
.click() clicks but there is no change.

### ISSUE THREAD

**Issue by brockahutchings** [cypress-io/cypress#2562]
### Current behavior:
I have tested the button in three browsers and in the cypress iframe, all of which when i click on the button, the list elements on the left are moved to the right. In cypress however using .click() does click but there is no change.

things i have tried:
-clicking on the various elements of the button (icon, wrap)
-waiting before various steps
-testing the width of the button
-clicking on the x, y coordinated of the button
-ensuring the button is not disabled etc...
-mousing over the button etc...
-ensuring the page has the proper cookies

![image](https://user-images.githubusercontent.com/11707009/46479257-b177d600-c7bc-11e8-9a3e-3d9352cdce4b.png)

The following is the cypress code used:
```js
	describe('Choose Data', function() {
		it('Select data to be used in Adhoc View', function() {
                        //check cookies and status of button to get to next page
			cy.getCookies()
			cy.get('#goToDesigner').should('be.disabled')
			
			//mouse over and click
			cy.get('#toRight').trigger('mouseover')
			cy.wait(2000)
			cy.get('#toRight').click({force: true})
			
			//attempted ensuring width
			cy.get('#toRight').should('be.visible').click();
			cy.get('#toRight').should('be.visible').invoke('width').should('be.greaterThan', 0)
			cy.get('#toRight').should('be.visible').invoke('height').should('be.greaterThan', 0)

                        //attempt to click on the button that should lead to next page
			cy.get('#goToDesigner').should('be.enabled')
			cy.get('#goToDesigner').click()
```

The following is the code for the button:

&lt;button id="toRight" class="button action square move toRight up" title="Add all"&gt;
&lt;span class="wrap"&gt;
&lt;b class="icon"&gt;
&lt;/b&gt;
&lt;/span&gt;
&lt;/button&gt;

### Desired behavior:

I expect the `.click()` action to cause the button to trigger and move list items from the list on the left of the page to the list on the right. 

### Versions

Cypress version 2.0.3 
Windows 10

**Comment by vrockai** [comment]
It looks to me like this may just be a typo, using `#goToDesigner` instead of `#toRight`. Is that right?

**Comment by brockahutchings** [comment]
The #toRight is the button in the middle of the page that would shift the list items from the list on the left to the selected items list on the right of the page.  Typically when there is anything present in the selected items list the #goToDesigner button becomes clickable.  In short the #toRight button needs to be triggered first which .click() does not cause.

**Comment by jennifer-shehane** [comment]
@brockahutchings Are you familiar with what event is being listened to to trigger the movement of the items? Are you using a plugin for this? Cypress may not be executing the exact event your application is listening to.

**Comment by Bkucera** [comment]
@brockahutchings do you have a reproducible example you could show us? It's possible your app has event listeners on `mouseover, mouseenter, mousemove, or pointerdown`, but we do not fire those events

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
