### ISSUE TITLE
If else /switch case doesn't work. 

### ISSUE THREAD

**Issue by nikhiletc** [cypress-io/cypress#2563]
I am trying to add else if /switch case in my test , but 
else if - it goes to only if case, if 'if' fail it doesn't go in else if 
its happen in switch case also.
 `module.exports.selectEnviroment = function(env) {
  //console.log(env);
  //Beta
  switch (env) {
    case 'alpha':
      cy.get('[role="presentation"]')
        .find('[href="#/company-detail/5bb3765e64f66ca0027e15245"]')
        .click();
      break;
    case 'beta':
      cy.get('[role="presentation"]')
        .find('[ng-href="#/company-detail/5bb62c019ee36000273a6e2b"]')
        .eq(0)
        .click();
      break;
  } ``

  `// if (
  //   cy
  //     .get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5bb62c019ee36000273a6e2b"]')
  // ) {
  //   cy.get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5bb62c019ee36000273a6e2b"]')
  //     .eq(0)
  //     .click();
  // } //alpha
  // else if (
  //   cy
  //     .get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5bae05a39af4a90027fcdf43"]')
  // ) {
  //   cy.get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5bae05a39af4a90027fcdf43"]')
  //     .eq(0)
  //     .click();
  // } //QA
  // else if (
  //   cy
  //     .get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5b855022323d37000f48bcdc"]')
  // ) {
  //   cy.get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5b855022323d37000f48bcdc"]')
  //     .eq(0)
  //     .click();
  // } //Gamma
  // else if (
  //   cy
  //     .get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5bb62ccf5cb043002737d929"]')
  // ) {
  //   cy.get('[role="presentation"]')
  //     .find('[ng-href="#/company-detail/5bb62ccf5cb043002737d929"]')
  //     .eq(0)
  //     .click();
  // }
}; ``

switch case test --
`it('Booking should be done using invoice', () => {
    cy.visit(`${blah_url}#/blah/`);
    let env = blah_url.split('.')[1];
    selectEnviroment(env);
}``
if else test--- 

`it('Booking should be done using invoice', () => {
    selectEnviroment();
}``

both test doesn't work ,it work only for beta ,if beta case failed then it doesn't work

**Comment by RadhikaVytla** [comment]
I am facing the same issue. Can you let me know the solution here.

**Comment by rakutenRandhir** [comment]
I am also facing the same issue

**Comment by nandini-ramesh-cko** [comment]
I am also facing the same issue

**Comment by muhilEdvoy** [comment]
Im also facing this isssue
