### ISSUE TITLE
Cypress 13.0.0 Release

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#25630]
Issue to track planned work associated with Cypress 13.0.0. Issues / PR will be added as changes for 13.0.0 are identified and prioritized.

- https://github.com/cypress-io/cypress/issues/448
- https://github.com/cypress-io/cypress/issues/26160
- https://github.com/cypress-io/cypress/issues/26157
- https://github.com/cypress-io/cypress/issues/26899
- https://github.com/cypress-io/cypress/pull/25595
- https://github.com/cypress-io/cypress/issues/26725

**Comment by dwhieb** [comment]
Will webpack 5 support be added in v13?

**Comment by MikeMcC399** [comment]
@dwhieb 

> Will webpack 5 support be added in v13?

I'm seeing webpack `v5` listed in the [changelog for Cypress 12.17.4](https://docs.cypress.io/guides/references/changelog#12-17-4).

**Comment by chrisbreiding** [comment]
Closed by https://github.com/cypress-io/cypress/pull/27040

**Comment by hridoydas** [comment]
Cannot properly connect cucumber stepdef in cypress 13. showing the following error.
Error: We've tried to resolve your step definitions at ./e2e/examples/Cucumber_bdd_test/astaLogin, but that doesn't seem to exist. As of version 2.0.0 it's required to set step_definitions in your cypress-cucumber-preprocessor configuration

**Comment by MikeMcC399** [comment]
@hridoydas 

This is really the wrong place to report your problem, however I noticed that a new version has just been released https://github.com/badeball/cypress-cucumber-preprocessor/releases/tag/v18.0.5.
