### ISSUE TITLE
Implement Public API for Component Testing Onboarding

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#25638]
### What would you like?

Based on the work done in the technical brief: https://github.com/cypress-io/cypress/issues/24991 (Cypress team only), implement the proposed public API.

Documentation: (public post 12.7 release): https://docs.cypress.io/guides/component-testing/third-party-definitions

**Comment by baus** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25638?planning-poker) with Zenhub @astone123

**Comment by baus** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25638?planning-poker) with Zenhub @lmiller1990

**Comment by baus** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25638?planning-poker) with Zenhub @marktnoonan

**Comment by baus** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25638?planning-poker) with Zenhub @mike-plummer

**Comment by baus** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25638?planning-poker) with Zenhub @warrensplayer

**Comment by baus** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25638?planning-poker) with Zenhub @ZachJW34

**Comment by astone123** [comment]
@lmiller1990 Does this include reworking the existing adapters to use the API?

**Comment by lmiller1990** [comment]
Yeah it does - this single ticket will manage all the work, I don't think it's too large for a single PR. Reworking them should not be much work - the actual API/format isn't changing for internal adapters. Most of the work will be around grabbing a third party one (via `cypress-ct-*`) exposing the right exports, and integrating it to the workflow.

I wonder if we should stop naming things `WIZARD` and install call them something more generic. `WIZARD` is an internal implementation detail. Worth doing if it's not much work as part of this PR.

**Comment by lmiller1990** [comment]
Splitting this in to two tickets:

1. https://github.com/cypress-io/cypress/issues/25680
2. https://github.com/cypress-io/cypress/issues/25681

**Comment by lmiller1990** [comment]
I'm removing this from the sprint in favor or the above two tickets. I split the points here between the two tickets.
