### ISSUE TITLE
Clicks do not always trigger event in Chrome

### ISSUE THREAD

**Issue by JWvP** [cypress-io/cypress#25644]
### Current behavior

When using `cy.contains('Restaurants', {timeout: 10000}).click();`  9 out of 10 times the click does not register, either because for some reason it say's the click is not visible or for some other more elusive reason. 
I've seen this behavior of cypress in our app, using both versions 11.2 and 12.3, the results are the same.
In an effort to recreate this I've turned to the google maps app as visually it is comparable 
Both screenshots show how Cypress clicked on the 'Restaurant' filter in google maps, but there never was a result/change after clicking. 
![image](https://user-images.githubusercontent.com/49518947/215793567-6faf7439-5da6-485f-a709-109cd21853fb.png)
![image](https://user-images.githubusercontent.com/49518947/215794001-4d9bc3ce-5e07-4db7-abba-6374f9a1c721.png)

### Desired behavior

the click should correctly register, and google should show a list of local restaurants.

### Test code to reproduce
```js
describe('test to see if click registers', () => {
    it('can visit google maps and click on a filter, thus giving results', () => {
        cy.visit('maps.google.com');
        // next you may need to use the first time when running this.
        // cy.contains('Accept all).click();
        cy.contains('Restaurants', {timeout: 10000}).click();
    });
});
```

### Cypress Version

12.3

### Node version

v18.12.1

### Operating System

windows 10 Enterprise 10.0.19045 Build 19045

### Debug Logs

```shell
index-d7b02282.js:101712 Command:  debug
index-d7b02282.js:101712 Yielded:  <button aria-label=​"Restaurants" jsaction=​"pane.wfvdle44;​ keydown:​ ripple.play;​ mousedown:​ ripple.play;​ ptrdown:​ ripple.play;​" jslog=​"120714;​track:​click" jstcache=​"832" class=​"e2moi" jsan=​"7.e2moi,0.aria-label,0.jsaction,0.jslog">​ flex <span jstcache=​"833" class=​"tXNTee L6Bbsd T7HQDc" jsan=​"7.tXNTee,7.L6Bbsd,7.T7HQDc">​ flex <div class=​"Vo1fsd">​</div>​<div jstcache=​"834" style=​"display:​none">​</div>​<img alt draggable=​"false" jstcache=​"835" src=​"/​/​www.gstatic.com/​images/​icons/​material/​system_gm/​1x/​restaurant_black_18dp.png" class=​"k48Abe" jsan=​"7.k48Abe,8.src,0.alt,0.draggable">​<span jstcache=​"836" class=​"uEubGf fontTitleSmall" jsan=​"7.uEubGf,7.fontTitleSmall">​Restaurants​</span>​<span jstcache=​"837" style=​"display:​none">​</span>​<img jstcache=​"838" style=​"display:​none">​<div jstcache=​"839" style=​"display:​none">​</div>​</span>​</button>​
```

**Comment by mschile** [comment]
Hi @JWvP 👋, thanks for providing the reproduction. I believe you are running into a race condition between when the UI displays and when the javascript has loaded to handle the button click. What happens if you add a wait before clicking the button?

`cy.contains('Restaurants', {timeout: 10000}).wait(2000).click();`

**Comment by JWvP** [comment]
Hi @mschile It seems you are correct about the race condition, you wouldn't happen to have a more elegant solution so as to avoid a hard wait?

**Comment by mschile** [comment]
I would suggest looking for another 'signal' to indicate the page is ready. Is there another element that you query for? You could also look into using [cy.intercept](https://docs.cypress.io/api/commands/intercept#Waiting-on-a-request) to wait for the request that loads the javascript to complete.

**Comment by liuliu-dev** [comment]
Hi @mschile, I'm experiencing similar issues. Tried adding wait, but waiting for arbitrary time periods won't work every time, also it adds a large amount of running time when running a big test suite. Is there a better way to handle this?

**Comment by timsehn** [comment]
We experienced this issue as well for DoltHub Cypress tests (https://www.dolthub.com). It only happens on 12.2+ Cypress. Should we wait for a fix? Or stay on the old version indefinitely?

Adding a `wait()` after every click is not a viable solution. Something changed in the runner that triggered this.

**Comment by mschile** [comment]
@timsehn, there are no changes planned for this issue. However, it sounds like you are experiencing a different issue as the reproduction provided in this issue fails in versions prior to Cypress 12.2. Could you please log a new issue. Thanks!

**Comment by timsehn** [comment]
Sure thing.

**Comment by timsehn** [comment]
@liuliu-dev on my team will make one.

**Comment by JWvP** [comment]
@mschile Hi,
Sorry, for the late response, I was on holiday. 
As for other elements, etc, the challenge here is that the app uses a websocket and after the initial loading is done, everything else goes over the websocket. So no, no other elements or javascript to latch on to. 
I guess I'll have to dive in to the world of websockets and testing.
