### ISSUE TITLE
Page constantly refreshes after logging into external application using cy.origin command

### ISSUE THREAD

**Issue by Ralkage** [cypress-io/cypress#25654]
### Current behavior

When using the cy.origin command to log into another application, the application will endlessly refresh and eventually produce the following error:

![image](https://user-images.githubusercontent.com/2059356/215887062-73c2b16d-3e64-4d89-bf4a-a4bec9cc0ca6.png)

I've tried extending the pageLoadTimeout, but that doesn't seem to make a difference, and Cypress continues to refresh the page.

### Desired behavior

After logging into the application (CUCM), we should be able to navigate to any other page, but we aren't able to.

### Test code to reproduce

https://github.com/Ralkage/cypress-test-tiny

### Cypress Version

12.4.1

### Node version

v16.17.0

### Operating System

Windows 11 Build 22621.1105 (22H2)

### Debug Logs

```shell
The browser console logs constantly clear, so I am unable to capture any logs it produces even as a screenshot because of how quickly it disappears.
```

### Other

This issue didn't start to occur until version 10.11.0 and works as intended on version 10.10.0.

**Comment by mschile** [comment]
Hi @Ralkage 👋, unfortunately, I wasn't able to reproduce your issue since it appears the test is connecting to a local instance of CUCM. My initial guess is that a cookie is missing which is causing your application to continuously refresh. What happens if you put a wait (e.g. `cy.wait(2000)`) inside of the `cy.origin` block after the form submittal? Are you able to compare the cookies from a normal login and one from the Cypress login? If you have a way for me to run the CUCM application (maybe invite me to a private project) I would be happy to investigate further.

**Comment by Ralkage** [comment]
Hey @mschile, adding `cy.wait(2000)` didn't fix the problem and it looks like there is a difference in cookies between a normal login and Cypress, but that seems to be the same case for when `cy.origin` works on version 10.10.0 for the application in question (CUCM). We are looking into getting something reachable from the outside set up, so let me get back to you, and let you know if that's possible on our end.

<details>
<summary>Normal Session</summary>

![image](https://user-images.githubusercontent.com/2059356/216635025-8cd377ab-1ab3-4c64-b9a0-e7ab3ee45898.png)

</details>

<details>
<summary>Cypress Session</summary>

![image](https://user-images.githubusercontent.com/2059356/216635199-4d6d9502-a5c5-44e7-b31e-180a59b7fcdc.png)

</details>

**Comment by Ralkage** [comment]
@mschile would it be possible to setup a Cisco WebEx session so you can see it through out network? CUCM does not exist in the cloud without some kind of VPN access, so the best way would be to troubleshoot remotely over a call. If this is something that requires paid support, please let me know, so I can discuss with my superiors.

**Comment by mschile** [comment]
@ralkage, unfortunately, I won't be able to help troubleshoot remotely. We do offer direct email support for our paid [Cypress Cloud](https://www.cypress.io/pricing/) customers.

Would you be able to recreate the issue by any other means? Does the issue happen in all browsers?

This is the only change between Cypress 10.10.0 and 10.11.0 that is related to cookies, https://github.com/cypress-io/cypress/commit/f9272bbd22147ace447da8ea98c1a01eb6a84c2d

**Comment by Ralkage** [comment]
@mschile we have no other way and yes, it does look to happen in all browsers.

I can't find any other applications that is experiencing this issue on the latest version, but how would I be able to validate if the changes from https://github.com/cypress-io/cypress/commit/f9272bbd22147ace447da8ea98c1a01eb6a84c2d may be what's causing this behavior?

**Comment by mschile** [comment]
In Developer Tools, on the `Network` tab, there is an `Initiator` column. Can you click that for one of the page refresh requests and see what is causing the page to be refreshed? You may need to check the `Preserve Logs` checkbox if the requests are getting cleared on refresh.

**Comment by Ralkage** [comment]
I can't really find where the refresh happens, but this is where the errors start to occur and it just loops through the same resources each time and sometimes, they don't always load because of the constant refreshing.

<img width="1255" alt="Cypress_CdgTLttlTI" src="https://user-images.githubusercontent.com/2059356/217393912-d0968deb-e819-406d-8f6d-8de3445f22af.png">

I've also attached the HAR for reference because I don't know which request does the refresh happen after.

[cy-12-5-1-CUCM-HAR.zip](https://github.com/cypress-io/cypress/files/10680448/cy-12-5-1-CUCM-HAR.zip)

**Comment by mschile** [comment]
@Ralkage, could you please try this [pre-release binary](https://github.com/cypress-io/cypress/commit/38a65a6d7c04dff8e5663d9fee1b7df1b5828fb4#comments) that contains a few cookie fixes to see if it resolves your issue.

**Comment by Ralkage** [comment]
@mschile doesn't look to have resolved my issue, but here is a video if it helps any. It looks like after Cypress finally gives up, it also causes the "Choose a browser" screen to not show any available browsers to switch or choose from.

https://user-images.githubusercontent.com/2059356/217978110-8bdf2958-15a0-4c5a-b9ff-79a8d4fbe1d6.mp4

**Comment by mschile** [comment]
Hi @Ralkage, you would have to click 'Close' to choose another browser on the 'Choose a browser' screen.

Unfortunately, right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by Ralkage** [comment]
Hi @mschile thank you so much for your help. Although you closed this issue this is severely impacting our automation testing and planning with Cypress. We chose Cypress because of its flexibility and powerful capabilities, and we haven't looked back since switching from another tool we used. Can we escalate this issue to someone else who can help us look into this further?  don't understand how this was working in version 10.10.0 and immediately stopped working in version 10.11.0. We are basically stuck on this version, and we really don't want to switch to a different tool again. We have considered Cypress Cloud, but if we are stuck on this version, what sense does it make to pursue a product that works in one version and then breaks our workflow immediately in the next version? As I mentioned, we as an organization planned on using Cypress, but this is a sever blocker for us. Thank you for your continued help.

**Comment by nagash77** [comment]
Hi @Ralkage ,  Have you tried running with the latest version of Cypress ([12.5.1](https://docs.cypress.io/guides/references/changelog#12-5-1) as of today)?  We are also doing more work to address some more cookie issues that have been uncovered since the release of 10.10.  Those fixes will be out in the next release of Cypress.  If you could hold out until then and try using that latest version once it releases it may solve your problem.  Even if we get to the bottom of what is causing this problem, we will not backport a fix for it to previous versions so upgrading to the latest will be necessary even in the case where we can determine the issue.

**Comment by Ralkage** [comment]
@nagash77 I just tried on 12.6.0 and still experiencing the same issue and it will eventually timeout like before.

<img width="1273" alt="Cypress_HxqrRDFJGm" src="https://user-images.githubusercontent.com/2059356/219970515-06ab1d77-f039-4bfd-8708-32577af2cbad.png">

**Comment by mjhenkes** [comment]
@Ralkage, I know you've heard this before 😓, but we do have some new cookie fixes out with cypress 12.7.0. You could give that a try, though I can offer no guarantees.

**Comment by Ralkage** [comment]
> @Ralkage, I know you've heard this before 😓, but we do have some new cookie fixes out with cypress 12.7.0. You could give that a try, though I can offer no guarantees.

12.7.0 didn't fix the issue either :( hanging in there but thank you all for keeping this open and not giving up either!

**Comment by mschile** [comment]
A few other suggestions to try:

1. try turning on [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/references/experiments)
2. Set up a [cy.intercept](https://docs.cypress.io/api/commands/intercept) for the url that keeps refreshing so you can stop the refresh and investigate what is causing the refresh.

```js

let count = 0

it('intercepts reload', () => {
  // TODO: update to the url that keeps refreshing
  cy.intercept('http://localhost:8080', (req) => {
    // let the first request go to the server
    if (count === 0) {
      count++
      return req.continue()
    }

    // stub the reply for the second request to stop the continuous reload
    req.reply(200, 'ok', { 'content-type': 'text/html' })
  })

  cy.visit('http://localhost:8080')
})
```

**Comment by Ralkage** [comment]
@mschile [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/references/experiments) did not fix it sadly :(

In regard to using cy.intercept, how would that work when using the cy.origin command? I'd like to mention again that logging into the application outside of the cy.origin command works, but as soon as I run the same commands to log in after using the cy.origin command, that's when it refreshes constantly until Cypress finally throws an error.

**Comment by mschile** [comment]
@Ralkage, thanks for trying and thanks for the update that it works outside of `cy.origin`.

Since the `cy.intercept` operates at a lower level, you can setup the intercept outside of the `cy.origin` block to intercept the request.

```js
it('intercepts reload', () => {
  cy.intercept(<origin intercept url>, (req) => {
    ...
  })

  cy.origin(<origin url>, () => {
    cy.visit('/')
  })
})
```

@mjhenkes is also working on creating a custom binary based off of Cypress v10 that removes commit https://github.com/cypress-io/cypress/commit/f9272bbd22147ace447da8ea98c1a01eb6a84c2d to verify that is the commit that caused the regression.

**Comment by mjhenkes** [comment]
@Ralkage, In an attempt to narrow down the exact commit causing the problem here is a binary for  commit 1b29ce74aafa0bc5015a93cb618b7fbda243e07a which is just prior to https://github.com/cypress-io/cypress/commit/f9272bbd22147ace447da8ea98c1a01eb6a84c2d. If that works for you I will create a 10.11.0 binary that excludes the cookie commit and we can test that too.

`npm install https://cdn.cypress.io/beta/npm/10.11.0/linux-x64/matth/test/binary-for-25654-63cbe4993b85afe6da0230901e8c56ab324ab550/cypress.tgz`

**Comment by Ralkage** [comment]
> @Ralkage, In an attempt to narrow down the exact commit causing the problem here is a binary for commit [1b29ce7](https://github.com/cypress-io/cypress/commit/1b29ce74aafa0bc5015a93cb618b7fbda243e07a) which is just prior to [f9272bb](https://github.com/cypress-io/cypress/commit/f9272bbd22147ace447da8ea98c1a01eb6a84c2d). If that works for you I will create a 10.11.0 binary that excludes the cookie commit and we can test that too.
> 
> `npm install https://cdn.cypress.io/beta/npm/10.11.0/linux-x64/matth/test/binary-for-25654-63cbe4993b85afe6da0230901e8c56ab324ab550/cypress.tgz`

@mjhenkes, just installed that binary and it works!

<img width="1273" alt="Cypress_oGbw0eO6Cr" src="https://user-images.githubusercontent.com/2059356/224145438-c90f354a-00e4-4cec-9946-ce6e983bd228.png">

**Comment by mjhenkes** [comment]
@Ralkage Great! Now try this one: 
> npm install https://cdn.cypress.io/beta/npm/10.11.0/linux-x64/matth/test/binary-for-25654-894314a60e9074dc4b0192ae011b1d09ddfa82ef/cypress.tgz

If our theory holds this one will introduce the refreshing. And if thats the case we can look closer at the changes and try to theorize what is causing the issue.

**Comment by Ralkage** [comment]
@mjhenkes hmmm that build looks to work just fine as well 🤔no constant refreshing.


<img width="1273" alt="Cypress_aHKROtVYvC" src="https://user-images.githubusercontent.com/2059356/224848984-7978f681-d7cc-4665-9f20-eb0df6cb083a.png">

**Comment by mjhenkes** [comment]
Ok lets try this one: 
> npm install https://cdn.cypress.io/beta/npm/10.11.0/linux-x64/matth/test/binary-for-25654-aedaa02bb6c0732a3e856dc25a3ce6f5a2e5f28e/cypress.tgz

This has the next commit and we'll keep going till we find the binary with the commit that causes the issue.

**Comment by Ralkage** [comment]
> Ok lets try this one:
> 
> > npm install https://cdn.cypress.io/beta/npm/10.11.0/linux-x64/matth/test/binary-for-25654-aedaa02bb6c0732a3e856dc25a3ce6f5a2e5f28e/cypress.tgz
> 
> This has the next commit and we'll keep going till we find the binary with the commit that causes the issue.

@mjhenkes yup, that's the one! The constant refresh happens on that build 😵

**Comment by AtofStryker** [comment]
@Ralkage sounds like we know the commit that caused the issue. Is there a way to update the reproduction so it doesn't use a local instance of CUCM?

**Comment by Ralkage** [comment]
> @Ralkage sounds like we know the commit that caused the issue. Is there a way to update the reproduction so it doesn't use a local instance of CUCM?

@AtofStryker unfortunately, CUCM/Call Manager is a Cisco product that isn't available in the cloud and hosted on an on-prem server :( (or rather there is no official cloud version or service I can point your team to). Is there a way I can assist in reproducing this issue using the commit and applying any suggested changes to the code?

**Comment by AtofStryker** [comment]
@Ralkage is there a dockerized version of the service or something we can use to get the reproduction up and running? I'm mainly trying to get something together that we can run on our end to reproduce the issue to possibly fix (hopefully)

 It sounds like moving from the websocket directly inside `cy.origin` and leverage `postMessage` to communicate to the primary instance of cypress might be the culprit.

**Comment by Ralkage** [comment]
> @Ralkage is there a dockerized version of the service or something we can use to get the reproduction up and running? I'm mainly trying to get something together that we can run on our end to reproduce the issue to possibly fix (hopefully)
> 
> It sounds like moving from the websocket directly inside `cy.origin` and leverage `postMessage` to communicate to the primary instance of cypress might be the culprit.

@AtofStryker I can try to get an instance of the service up and running on my local network and invite you to a private repo since it'll have my IP address in the cy.origin command. I'll probably proxy it using Clouldflare and add one of my domain names into the mix to make things easier for the both of us. Let me get back to you in a few days while I attempt to get that working :)

**Comment by Ralkage** [comment]
@AtofStryker I've successfully set up the CUCM instance and invited @emilyrohrbough, @mjhenkes, and yourself as collaborators since it's a private repo :) https://github.com/Ralkage/cypress-origin-bug-with-cucm

Please let me know if anything else is required on my end so we can finally put this baddie to rest 🙏

**Comment by emilyrohrbough** [comment]
@Ralkage my invite expired 😓 can you resend?

**Comment by Ralkage** [comment]
> @Ralkage my invite expired 😓 can you resend?

Done 🫡

**Comment by emilyrohrbough** [comment]
@Ralkage Thank you for the repo! and it looks like we know where the issue was introduced! Will route this to the team.

**Comment by Ralkage** [comment]
@emilyrohrbough do you know what release this fix will be in or if there is a temporarily fix we can apply to at least be closer to the latest version of Cypress?

**Comment by AtofStryker** [comment]
@Ralkage we currently don't have an ETA on a fix for this and a workaround seems improbable since the main thing that is causing this issue is an underlying implementation swapping out websockets for postMessage (If I remember correctly).

**Comment by Ralkage** [comment]
> @Ralkage we currently don't have an ETA on a fix for this and a workaround seems improbable since the main thing that is causing this issue is an underlying implementation swapping out websockets for postMessage (If I remember correctly).

Hi @AtofStryker,

I know it's been a few months since your last reply, but I wanted to check in to see if there are any updates on the issue we're discussing here. My team and I are still using Cypress v10.10.0, and we're eager to upgrade to the latest stable version to take advantage of any new features, performance improvements, and other enhancements that you and your team have introduced in subsequent releases.

Our decision to upgrade is also related to our interest in purchasing your cloud product, which could enhance our automation reporting capabilities and provide access to useful features like Flake Detection. Therefore, having an idea of when this issue might be resolved is important for our planning.

I appreciate the fantastic work you and your team have done with Cypress. It offers an easy-to-learn syntax and has a supportive ecosystem, making it our preferred testing tool. 

Thank you for your assistance, and I look forward to any updates you can provide.

**Comment by emilyrohrbough** [comment]
@Ralkage We do not have any new updates at this time. I attempted to re-run the reproduction you provided to compare against the commit we have identified to determine if we can narrow in on the bug a bit more. It seems the page in the repo is down. Is there an updated simple test I can use that you can push to the repo?

**Comment by Ralkage** [comment]
> @Ralkage We do not have any new updates at this time. I attempted to re-run the reproduction you provided to compare against the commit we have identified to determine if we can narrow in on the bug a bit more. It seems the page in the repo is down. Is there an updated simple test I can use that you can push to the repo?

Thank you for getting back to me! Unfortunately, I had to dismantle the testing environment I initially set up because Cisco's CUCM application is resource-intensive and isn't typically made accessible outside of internal networks for security reasons mostly. The good news is that I can rebuild it, and once I do, I'll update the repository with the new link. Please give me a few days to get the environment up and running again. I'll notify you here when it's ready :)

**Comment by Ralkage** [comment]
@jennifer-shehane @emilyrohrbough, we can probably go ahead and close this issue, considering that I won't be able to spare time to set up my Cisco Unified Call Manager instance for a while. However, I did come up with a workaround for the time being, as CUCM has its API called AXL. I created custom commands for Cypress to interact with it and perform assertions on the data it returns or doesn't return.


For any future onlookers looking to validate data using CUCM, I used a combination of my own custom commands and the [cypress-recurse](https://github.com/bahmutov/cypress-recurse) package.

<details>
<summary>Click to reveal code</summary>

```js
// cypress/support/custom-commands/cucm.js

/**
 * Custom Cypress command to retrieve end user details in CUCM.
 *
 * @param {string} axlApiUrl - AXL API URL for CUCM.
 * @param {string} axlApiVersion - AXL API version.
 * @param {string} username - CUCM App User ID for authentication.
 * @param {string} password - CUCM App User password for authentication.
 * @param {string} endUserId - User ID of CUCM end user.
 * @param {boolean} positiveCheck - If true, perform a positive assertion; if false, perform a negative assertion.
 * @param {boolean} recurseLogging - If true, log recursion details; if false, do not log.
 * @param {number} recurseIterations - Number of recursion iterations.
 * @param {number} recurseLimit - Maximum number of recursion calls.
 * @param {number} recurseTimeout - Maximum time (in milliseconds) for each recursion call.
 * @param {number} recurseDelay - Time (in milliseconds) to wait between recursion calls.
 *
 * @example
 * cy.searchForEndUserInCUCM(
 *   'https://cucm.example.com/axl/',
 *   '11.5',
 *   'admin',
 *   'adminPassword',
 *   'john_doe',
 *   true,
 *   true,
 *   5,
 *   10,
 *   5000,
 *   1000
 * );
 */
Cypress.Commands.add(
  'searchForEndUserInCUCM',
  (
    axlApiUrl,
    axlApiVersion,
    username,
    password,
    endUserId,
    positiveCheck = true,
    recurseLogging,
    recurseIterations,
    recurseLimit,
    recurseTimeout,
    recurseDelay,
  ) => {
    // SOAP request payload to retrieve end user details in CUCM
    const soapPayload = `
          <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/${axlApiVersion}">
            <soapenv:Header/>
            <soapenv:Body>
              <ns:getUser>
                <userid>${endUserId}</userid>
              </ns:getUser>
            </soapenv:Body>
          </soapenv:Envelope>
        `

    // Make a recursive POST request to AXL API to retrieve end user details in CUCM.
    cy.recurse(
      () =>
        cy.request({
          method: 'POST',
          url: axlApiUrl,
          failOnStatusCode: false,
          headers: {
            'Content-Type': 'text/xml',
            SOAPAction: 'CUCM:Axl',
          },
          body: soapPayload,
          auth: {
            username: username,
            password: password,
          },
        }),
      (res) => {
        if (positiveCheck) {
          // Positive assertion: Check for the presence of the user ID in the response body
          return expect(res.body).to.include(`<userid>${endUserId}</userid>`)
        } else {
          // Negative assertion: Check for the absence of the user ID in the response body
          return expect(res.body).to.not.include(
            `<userid>${endUserId}</userid>`,
          )
        }
      },
      {
        log: recurseLogging,
        iteration: recurseIterations,
        limit: recurseLimit,
        timeout: recurseTimeout,
        delay: recurseDelay,
      },
    )
  },
)

/**
 * Custom Cypress command to initiate LDAP synchronization in CUCM.
 *
 * @param {string} axlApiUrl - AXL API URL for CUCM.
 * @param {string} axlApiVersion - AXL API version.
 * @param {string} username - CUCM App User ID for authentication.
 * @param {string} password - CUCM App User password for authentication.
 * @param {string} ldpaConfigName - Name of the LDAP configuration to sync.
 *
 * @example
 * cy.performLDAPSyncInCUCM(
 *   'https://cucm.example.com/axl/',
 *   '11.5',
 *   'admin',
 *   'adminPassword',
 *   'ldapConfig1'
 * )
 */
Cypress.Commands.add(
  'performLDAPSyncInCUCM',
  (axlApiUrl, axlApiVersion, username, password, ldpaConfigName) => {
    // SOAP request payload for LDAP synchronization
    const soapPayload = `
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/${axlApiVersion}">
          <soapenv:Header/>
          <soapenv:Body>
            <ns:doLdapSync>
              <name>${ldpaConfigName}</name>
              <sync>true</sync>
            </ns:doLdapSync>
          </soapenv:Body>
        </soapenv:Envelope>
      `

    // Make a POST request to AXL API for LDAP synchronization in CUCM
    cy.request({
      method: 'POST',
      url: axlApiUrl,
      failOnStatusCode: false,
      headers: {
        'Content-Type': 'text/xml',
        SOAPAction: 'CUCM:Axl',
      },
      body: soapPayload,
      auth: {
        username: username,
        password: password,
      },
    }).then((res) => {
      expect(res.status).to.eq(200)
    })
  },
)

/**
 * Custom Cypress command to check CUCM LDAP synchronization status.
 *
 * @param {string} axlApiUrl - AXL API URL for CUCM.
 * @param {string} axlApiVersion - AXL API version.
 * @param {string} username - Username for authentication.
 * @param {string} password - Password for authentication.
 * @param {string} ldpaConfigName - Name of the LDAP configuration to check.
 * @param {boolean} recurseLogging - If true, log recursion details; if false, do not log.
 * @param {number} recurseIterations - Number of recursion iterations.
 * @param {number} recurseLimit - Maximum number of recursion calls.
 * @param {number} recurseTimeout - Maximum time (in milliseconds) for each recursion call.
 * @param {number} recurseDelay - Time (in milliseconds) to wait between recursion calls.
 *
 * @example
 * cy.checkLDAPSyncStatusInCUCM(
 *   'https://cucm.example.com/axl/',
 *   '11.5',
 *   'admin',
 *   'adminPassword',
 *   'ldapConfig1',
 *   true,
 *   5,
 *   10,
 *   5000,
 *   1000
 * )
 */
Cypress.Commands.add(
  'checkLDAPSyncStatusInCUCM',
  {
    prevSubject: false,
  },
  (
    axlApiUrl,
    axlApiVersion,
    username,
    password,
    ldpaConfigName,
    recurseLogging,
    recurseIterations,
    recurseLimit,
    recurseTimeout,
    recurseDelay,
  ) => {
    // SOAP request payload for getting LDAP synchronization status in CUCM
    const soapPayload = `
          <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/${axlApiVersion}">
            <soapenv:Header/>
            <soapenv:Body>
              <ns:getLdapSyncStatus>
                <name>${ldpaConfigName}</name>
              </ns:getLdapSyncStatus>
            </soapenv:Body>
          </soapenv:Envelope>
        `

    // Make a recursive POST request to AXL API for LDAP synchronization status in CUCM
    cy.recurse(
      () =>
        cy.request({
          method: 'POST',
          url: axlApiUrl,
          failOnStatusCode: false,
          headers: {
            'Content-Type': 'text/xml',
            SOAPAction: 'CUCM:Axl',
          },
          body: soapPayload,
          auth: {
            username: username,
            password: password,
          },
        }),
      (res) => {
        return expect(res.body).to.include('Sync is performed successfully')
      },
      {
        log: recurseLogging,
        iteration: recurseIterations,
        limit: recurseLimit,
        timeout: recurseTimeout,
        delay: recurseDelay,
      },
    )
  },
)

/**
 * Custom Cypress command to initiate LDAP synchronization in CUCM.
 *
 * @param {string} axlApiUrl - AXL API URL for CUCM.
 * @param {string} axlApiVersion - AXL API version.
 * @param {string} username - CUCM App User ID for authentication.
 * @param {string} password - CUCM App User password for authentication.
 * @param {string} endUserId - User ID of CUCM end user.
 *
 * @example
 * cy.convertLDAPUserToLocalUserInCUCM(
 *   'https://cucm.example.com/axl/',
 *   '11.5',
 *   'admin',
 *   'adminPassword',
 *   'john_doe'
 * )
 */
Cypress.Commands.add(
  'convertLDAPUserToLocalUserInCUCM',
  (axlApiUrl, axlApiVersion, username, password, endUserId) => {
    // SOAP request payload to convert an LDAP Syncronized User to a Local User in CUCM
    const soapPayload = `
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/${axlApiVersion}">
          <soapenv:Header/>
          <soapenv:Body>
            <ns:updateUser>
              <userid>${endUserId}</userid>
              <ldapDirectoryName></ldapDirectoryName>
              <userIdentity></userIdentity>
            </ns:updateUser>
          </soapenv:Body>
        </soapenv:Envelope>
      `

    // Make a POST request to AXL API to convert an LDAP Syncronized User to a Local User in CUCM
    cy.request({
      method: 'POST',
      url: axlApiUrl,
      failOnStatusCode: false,
      headers: {
        'Content-Type': 'text/xml',
        SOAPAction: 'CUCM:Axl',
      },
      body: soapPayload,
      auth: {
        username: username,
        password: password,
      },
    }).then((res) => {
      expect(res.status).to.eq(200)
    })
  },
)

/**
 * Custom Cypress command to initiate LDAP synchronization in CUCM.
 *
 * @param {string} axlApiUrl - AXL API URL for CUCM.
 * @param {string} axlApiVersion - AXL API version.
 * @param {string} username - CUCM App User ID for authentication.
 * @param {string} password - CUCM App User password for authentication.
 * @param {string} endUserId - User ID of CUCM end user.
 *
 * @example
 * cy.deleteEndUserInCUCM(
 *   'https://cucm.example.com/axl/',
 *   '11.5',
 *   'admin',
 *   'adminPassword',
 *   'john_doe'
 * )
 */
Cypress.Commands.add(
  'deleteEndUserInCUCM',
  (axlApiUrl, axlApiVersion, username, password, endUserId) => {
    // SOAP request payload to convert an LDAP Syncronized User to a Local User in CUCM
    const soapPayload = `
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/${axlApiVersion}">
          <soapenv:Header/>
          <soapenv:Body>
            <ns:removeUser>
              <userid>${endUserId}</userid>
            </ns:removeUser>
          </soapenv:Body>
        </soapenv:Envelope>
      `

    // Make a POST request to AXL API to delete an end user in CUCM
    cy.request({
      method: 'POST',
      url: axlApiUrl,
      failOnStatusCode: false,
      headers: {
        'Content-Type': 'text/xml',
        SOAPAction: 'CUCM:Axl',
      },
      body: soapPayload,
      auth: {
        username: username,
        password: password,
      },
    }).then((res) => {
      expect(res.status).to.eq(200)
    })
  },
)
```
</details>

To import this custom command file, add `import './custom-commands/cucm'` to `cypress/support/commands.js`.
