### ISSUE TITLE
Debug M1.1 - Correct responsiveness of DebugNewRelevantRunBar

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25664]
**Current behavior**

When the breakpoint is really narrow, the DebugNewRelevantRunBar does not wrap and looses a lot of information.

![image.png](https://images.zenhubusercontent.com/5e25f9721016beda9c509196/32472093-3118-4aff-a0df-aa7547f8f803)

**Desired behavior**
The DebugNewRelevantRunBar should wrap when the breakpoint is narrow instead of staying on one line and being truncated.

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25664?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34

**Comment by lmiller1990** [comment]
Just use your intuition and design sense to make sure we don't hide any info.
