### ISSUE TITLE
Runnable instance not passed to test:after:run

### ISSUE THREAD

**Issue by drabikowy** [cypress-io/cypress#25663]
### Current behavior

It seems that after the update from 12.4.1 to 12.5.0, runnable instance is not passed to "test:after:run" event. Boolean is returned instead. 

### Test code to reproduce

```js
// index.js

Cypress.on('test:after:run', (test, runnable) => {
    console.log(runnable) // Shall show runnable instance, "true" is being returned instead
});
```

### Cypress Version

v12.5.0

### Node version

v16

### Operating System

macOS 13

**Comment by mschile** [comment]
Thanks for reporting this issue @drabikowy. I'm working on a fix now.
