### ISSUE TITLE
Cypress commands redefine element in function sent via parameter

### ISSUE THREAD

**Issue by orajov** [cypress-io/cypress#25660]
### Current behavior

When Im using element as parameter in function, Cypress rewrite element when I use for example .parent() command, on next command Im working with parent element and not element I sent to the function via parameter. 

### Desired behavior

If I send cy.get('myElement') to function via parameter called and use element.parent() I should work with cy.get('myElement') on next step and not with cy.get('itsParentElement'). I doesnt work even when I use variable and redefine it back to parameter after each step.

### Test code to reproduce
```js
checkInput(element) {
      element.type('{selectAll}{backspace}').missclick();
      element.parentsUntil('okb-form-field').contains('Input cannot be empty');
      element.type(hodnota).missclick();
      element.parentsUntil('okb-form-field').contains('Input cannot be empty').should('not.exist');
}
```
### Cypress Version

10.11.0

### Node version

16.17.1

### Operating System

Windows Pro 10.0.19044

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by marktnoonan** [comment]
Hi @orajov, I think I understand the issue. It's fair to say we need more information to reproduce the exact problem, so I'm going to close this with a suggestion:

>Cypress rewrite element when I use for example .parent() command, on next command Im working with parent element and not element I sent to the function via parameter.

I suspect what's confusing here is that `parent()` changes the subject in the chain and yields that parent element, which makes it the subject for subsequent commands in a given chain. You can see more in [the docs for `.parent()`](https://docs.cypress.io/api/commands/parent#Yields-Icon-namequestion-circle) and learn about [subject management](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Subject-Management).

If this is understood already, and you think you have identified either a bug in Cypress, please comment with more details and we can reopen this issue. We would need to see the exact usage of the `checkInput` function in a test and the code for custom commands invoked in such a way that we can reproduce it ourselves.
