### ISSUE TITLE
Debug M1.1 - Update sidebar badge count display

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25662]
**Current behavior**
The Debug page badge in the sidebar will show the failed test count up to 9 and then shows "9+" when the count is above 9.  

**Desired behavior**
The Debug page badge in the sidebar will show up to 99 and then show "99+" if the count is higher than 99.

* Show the actual count up to 99
* When above 99, show "99+"
* Offset the badge in the collapsed mode so that it has consistent right margin from the edge of the sidebar (see Figma).  

Figma: https://www.figma.com/file/PAOozuCxtfetqP8fUVvg0y/branch/QkCp2F69X0qyLo7qnYQ67e/Cypress-App?node-id=23899%3A229781&t=AeAPEJnkNCEES56e-1

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25662?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34

**Comment by lmiller1990** [comment]
This part. Width of sidebar should not change.

<img width="173" alt="image" src="https://user-images.githubusercontent.com/19196536/216164433-9111179f-1c61-4397-b391-aac06d172ef9.png">

**Comment by mike-plummer** [comment]
This is intended to only change badge behavior for *failed count* badge when sidebar is collapsed - other badge types ("New" and "0") should not change: https://cypressio.slack.com/archives/C042Y29PWCD/p1675782997330079
