### ISSUE TITLE
Add date tooltip in Cypress Cloud run

### ISSUE THREAD

**Issue by zachz-indeed** [cypress-io/cypress#25670]
### What would you like?

An additional tooltip in a Cypress Cloud run that displays the actual date than a run occurred.

### Why is this needed?

On a run page in Cypress Cloud, the top bar shows various info about the run. One of those is the run date, but it is shown in an "X days ago" format. When debugging failures, it is often helpful to see exactly what day a failure began. Therefore it would be helpful to add a hover tooltip that shows the exact day the run occurred, or even better, edit this field to just show the actual date rather than "X days ago"

No tooltip:
![Screen Shot 2023-02-01 at 12 22 13 PM](https://user-images.githubusercontent.com/103957219/216129439-ca7cf3ed-7f0a-4863-8a18-8c515bff5876.png)

Example of existing tooltip:
![Screen Shot 2023-02-01 at 12 22 39 PM](https://user-images.githubusercontent.com/103957219/216129516-2ea50e16-db7e-4d43-8b56-3a79ccf7abeb.png)

**Comment by benpatterson** [comment]
This is available now. Linking similar ticket: https://github.com/cypress-io/cypress/issues/25478
