### ISSUE TITLE
Iframe url update via top.window.location.href lets Cypress close window

### ISSUE THREAD

**Issue by Ranitzky** [cypress-io/cypress#25683]
### Current behavior

If an iframe updates the `top.window.location.href` Cypress tests are aborted.

Using `cypress open`: 
The test view crashes.

Using `cypress run`:
Execution does not finish,  cypress:server:util:process_profiler is still running. See logs

Tried with Chrome, Electron and Firefox. Same error for all 3.

### Desired behavior

If I ran the same test, but instead using `window.parent.location` to update the url, Cypress works fine.

### Test code to reproduce

see https://github.com/Ranitzky/iframe-sample

### Cypress Version

10.4.1 / 10.5.0

### Node version

19.4.0

### Operating System

MacOS 12.5.1

### Debug Logs

```shell
see https://github.com/Ranitzky/iframe-sample/tree/main/logs
```

### Other

It does not matter, if I follow the [iframe blog tutorial](https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/) or use the recommended [iframe-plugin](https://gitlab.com/kgroat/cypress-iframe).

**Comment by mschile** [comment]
Hi @Ranitzky 👋, thanks for logging this issue. Since Cypress runs your application in an iframe, framebusting code can be problematic. We try to solve this problem with the [modifyObstructiveCode](https://docs.cypress.io/guides/references/legacy-configuration#modifyObstructiveCode) configuration option which is enabled by default but unfortunately doesn't apply to pages loaded within your iframe.

The easiest way to solve your problem would be the following intercept:

```js
  beforeEach(() => {
    cy.intercept('/iframe.html', (req) => {
      req.on('response', (res) => {
        // iframe is attempting to change window.top location so change it to window.parent
        res.body = res.body.replaceAll('top.window', 'window.parent')
      })
    })

    cy.visit('/');
  });
```

**Comment by Ranitzky** [comment]
Thanks @mschile ,

I can confirm, that your suggested workaround works fine in my example.
But this was much simplified from my real testcase, which (I know by today) works a little different. Still trying to get it running with this workaround.

The point is, I have no control, how the iframe actually calls the url. It is a coming from a third party 
(Payment Service Provider).
Unfortunately, I am not able to share the actual example.

So, I will close this bug, as it is not an actual issue with Cypress.

**Comment by Ranitzky** [comment]
Replacing an old-school `target='_top'` on the iframe's form with `target='_parent'` solved my issue. Thanks for the solution.

**Comment by mschile** [comment]
@Ranitzky, glad to hear you were able to resolve your issue! As an alternative, you could also try enabling [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/references/experiments#Configuration).
