### ISSUE TITLE
test using cy.origin fails in headless mode

### ISSUE THREAD

**Issue by alexandrabusu1** [cypress-io/cypress#25696]
### Current behavior

I have a simple test that is using the cy.origin , the issue is that the test passes in cypress open, but fails in headless mode....

tested on Chrome v. 110
cypress v. 12.5.0

If the test runs on cypress open. - ELECTRON browserr. I get 404 as in the showed picture...
<img width="573" alt="Screenshot 2023-02-03 at 11 49 55" src="https://user-images.githubusercontent.com/124351316/216568566-61d0498d-f270-4be5-a3ee-ecde121a0c99.png">

### Desired behavior

Tests should also run in headless mode

### Test code to reproduce

```js
describe ('[Sign In ]', () =>{
  it ('login with google', () => {
   // this command is doing a cy visit and a click on the login button from the app
    cy.clientSideApp();
   // the app was redirected to a page with the same superdomain , this will click on the login with google button from the login page
    commonIdentifiers.googleLoginButton().click();
    cy.origin('https://accounts.google.com', () =>{
    /// this will check that the google form is displayed on the page
      cy.get('#initialView').should('be.visible');
    })
  })
}) 
```

### Cypress Version

v12.5.0

### Node version

v16.16.0

### Operating System

macOs 12.4

**Comment by nagash77** [comment]
Hi @alexandrabusu1 , Im sorry you are having difficulties using Cypress.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by alexandrabusu1** [comment]
Hello Ben, 
i have the following code in a simple cypress project 

```
describe('Sign in', () =>{
    it('sign in google', () =>{
        cy.visit('https://www.nationalgeographic.org/society/');
        cy.get('.sfm-rollback .sfm-navicon-button').click()
        cy.get('.extra-menu-link.split-menu-account').click();
        cy.get('[data-test-id="ngs-qa-google-oauth2-button"]').click();
        cy.origin('https://accounts.google.com', () =>{
            cy.get('#initialView').should('be.visible');
        })
    })
})
```
 an this is the command used for running the test
```
   "scripts": {
    "cypress:open": "npx cypress open",
    "cypress:run": "npx cypress run --browser chrome"
  },
```
For cypress:open using Electron is throwing the 403 error on the page, but works when run with Chrome:)
And headless always fails:)
<img width="960" alt="Screenshot 2023-02-06 at 11 15 57" src="https://user-images.githubusercontent.com/124351316/216932968-bea04f36-488b-4ef5-a651-9458d66c987a.png">

**Comment by mschile** [comment]
@alexandrabusu1, can you try enabling [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/references/experiments#Configuration) in your Cypress config.

**Comment by alexandrabusu1** [comment]
Hello Matt,
 I've tried enabling the `experimentalModifyObstructiveThirdPartyCode` and the test still fails in headless mode
 this is the cypress.config file

```
module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    requestTimeout: 10000,
    responseTimeout: 10000,
    pageLoadTimeout: 20000,
    experimentalModifyObstructiveThirdPartyCode: true,
    video: false,
    screenshotOnRunFailure: false,
    experimentalSkipDomainInjection:[
      '*.google.com'
    ],
    chromeWebSecurity: false,
    viewportHeight: 1500,
    viewportWidth: 1440,
  },
});
```
and the tsconfig file if this helps...
```
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */
    "target": "es2016",
    "lib": ["es2016"],
    "module": "commonjs",
    "types": ["cypress", "node"],
    "skipLibCheck": true
  },
  "include": [
    "cypress", "**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by mschile** [comment]
This is the view displayed in headless Chrome which may be different than headed mode. You could turn on video in your config so you can see the test execution.

![Image](https://user-images.githubusercontent.com/2002044/218169159-531065cf-6ad5-42c4-ab5c-31eb242a5671.png)

**Comment by bubafinder** [comment]
Have the same issue 😔
This is a big one, we can't run our tests in the CircleCI job.

**Comment by alexandrabusu1** [comment]
> This is the view displayed in headless Chrome which may be different than headed mode. You could turn on video in your config so you can see the test execution.
> 
> ![Image](https://user-images.githubusercontent.com/2002044/218169159-531065cf-6ad5-42c4-ab5c-31eb242a5671.png)

So...on Chrome, something is happening differently when running the test in cypress dashboard vs headless mode...
You can see in the attached file, that at redirect to account google there is a different URL/google form and that is why the #initialView element is not found:)...(please see the attached file) 
<img width="1628" alt="Screenshot 2023-02-16 at 13 55 20" src="https://user-images.githubusercontent.com/124351316/219359243-dcd2dc2a-9103-4892-8ca5-6c00153d3426.png">

Just tested and if the test is running on Firefox headless mode, everything is ok:) (this helps a bit....but we also want to run the tests on Chrome)

**Comment by bubafinder** [comment]
The test is not running correctly in any browser in headless mode for me.

**Comment by flotwig** [comment]
@alexandrabusu1 could you please try updating to Cypress 12.7.0? We included some bugfixes related to session, origin, and cookies that may resolve your issues: https://docs.cypress.io/guides/references/changelog#12-7-0

**Comment by mjhenkes** [comment]
@alexandrabusu1, this appears to be a known issue with headless chrome and google auth

https://groups.google.com/a/chromium.org/g/headless-dev/c/D1Fzxe4SH0A?pli=1

Check the end of that thread, there is a suggestion to modify the user agent

Check our config for the ability to override the user agent:
https://docs.cypress.io/guides/references/configuration#Browser

**Comment by alexandrabusu1** [comment]
@flotwig updating cypress version to 12.7.0 doesn’t fix the issue
@mjhenkes it works in Chrome headless if the user agent is set in the cypress config:) 

Thank you all:)

**Comment by mjhenkes** [comment]
@alexandrabusu1 thats great news! I'm glad it helped.
