### ISSUE TITLE
Add error message when `testIsolation` is on and user doesn't visit a page

### ISSUE THREAD

**Issue by mschile** [cypress-io/cypress#25707]
### What would you like?

Add error message when `testIsolation` is on but user doesn't visit a page prior to executing commands against the page. This is useful for when users put the `visit` in a `before()` hook instead of a `beforeEach()` hook.

### Why is this needed?

Improve user experience when `testIsolation` is on and the user doesn't visit a page in a test.

**Comment by emilyrohrbough** [comment]
We will have to be a bit mindful with how this is handled but there are several cypress commands that are valid to execute before a visit is made that shouldn't be impacted on the page being cleared.
