### ISSUE TITLE
Salesforce - VisualForce Page using canvas app is not loading the iframe

### ISSUE THREAD

**Issue by tzioprodly** [cypress-io/cypress#25709]
### Current behavior

Hi all,

I can successfully login in to salesforce using the latest version 12.5.1
After that, I am trying to redirect to a specific salesforce tab which should load the iframe app. The app is using VisualForce page and it's a canvas app for anyone who is aware of how salesforce works.

All the other tabs in salesforce can open, but not the tabs with the canvas app. Even manually when I click in Cypress GUI, it doesn't load the iframes. Everything else is working fine.

I can see that the tab is clicked, but nothing happens.

### Desired behavior

To open the tab and load the app as the other tabs.

### Test code to reproduce
```js
describe("Salesforce Simple Login", () => {
  beforeEach(() => {
    // Before each Test we will login into Salesforce.
    cy.salesforceLoginSOAP();
  });

  it("Just login into Salesforce and load any page.", () => {
    cy.contains('My Tab Name').click()
    cy.wait(50000)
  });
});
```

### Cypress Version

12.5.1

### Node version

16.15.1

### Operating System

macOs

### Other
```js
 e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    baseUrl: "https://myUrl.lightning.force.com/",
    chromeWebSecurity: false,
    experimentalModifyObstructiveThirdPartyCode: true,
    experimentalSkipDomainInjection: ['*.salesforce.com', '*.force.com', '*.scratch.my.site.com']
  },
```

**Comment by mschile** [comment]
Hi @tzioprodly 👋, unfortunately, I was unable to reproduce your issue. I created a VisualForce page and was able to successfully load the tab in Cypress. Is there any other information you can provide about the page? Are you able to create a reproduction outside of Salesforce by using the [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny/) project?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
