### ISSUE TITLE
MountOptions and MountReturn interfaces not exported from cypress/react18

### ISSUE THREAD

**Issue by samtjo** [cypress-io/cypress#25705]
### Current behavior

When trying to import interfaces `MountOptions` and `MountReturn` from `cypress/react18` it gives this error, as they're not actually exported: 

![image](https://user-images.githubusercontent.com/14963680/216670949-ce0f2d70-960c-4e43-a3c4-4f490563b6a3.png)

These are both exported from `cypress/react` and they're both documented on the React API page: https://docs.cypress.io/guides/component-testing/react/api#mount  

### Desired behavior

Could you export these from `cypress/react18` as well please?

### Test code to reproduce

`import type { MountOptions, MountReturn } from 'cypress/react18';`

### Cypress Version

12.4.1

### Node version

16.15.0

### Operating System

macOS Montery 12.4

**Comment by lmiller1990** [comment]
@samtjo how about this? https://github.com/cypress-io/cypress/pull/25714

Please take a look, thanks!

**Comment by samtjo** [comment]
Looks good to me @lmiller1990 - thanks!
