### ISSUE TITLE
Custom Command added is not a function error

### ISSUE THREAD

**Issue by alextoma-QE** [cypress-io/cypress#25704]
### Current behavior

Currently an error is given when a Custom Command is used.

`cy.get(...).iframe is not a function`

### Desired behavior

The custom function should be reachable.

### Test code to reproduce

cypress\e2e\1-orders\logged_in_orders.cy.js

```
...
        cy.origin('https://myredirectedurl', () => {
            cy.get('[id="buy-button"]').click()
            cy.get('iframe').iframe().then(body => {
                cy.wrap(body).find('#onContinue').click()
            });
        })
```

cypress/support/commands.js

```
Cypress.Commands.add(
    'iframe',
    { prevSubject: 'element' },
    ($iframe) => {
        return new Cypress.Promise(resolve => {
            $iframe.on('load', () => {
                resolve($iframe.contents().find('body'))
            })
        })
    })
```

cypress/support/e2e.js
```
import './commands.js'

Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from failing the test on app fail
    return false
})
```

cypress/support/index.js
```
export * from "./e2e";
import './commands.js';

```

cypress.config.js
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  defaultCommandTimeout: 10000,
  pageLoadTimeout:10000,
  watchForFileChanges: false,
  e2e: {
    supportFile: 'cypress/support/index.js',
  },
});
```

I also tried pointing to     supportFile: 'cypress/support/e2e.js', or just removing any supportFile line from config.

### Cypress Version

12.5.1

### Node version

v18.13.0

### Operating System

Windows 10.0.19041.2486

**Comment by warrensplayer** [comment]
@alextoma-QE In order to use custom commands inside `cy.origin` calls, you will have to follow the instructions here: https://docs.cypress.io/api/commands/origin#Dependencies--Sharing-Code

The main changes to make are to add `experimentalOriginDependencies` to your cypress config under `e2e`:

cypress.config.js
```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  defaultCommandTimeout: 10000,
  pageLoadTimeout:10000,
  watchForFileChanges: false,
  e2e: {
    experimentalOriginDependencies: true,
    supportFile: 'cypress/support/index.js',
  },
});
```

And to add a `before` to your test file to require the commands file.  See docs [here](https://docs.cypress.io/api/commands/origin#Custom-commands).

```js
before(() => {
  cy.origin('https://myredirectedurl', () => {
    require('../support/commands')
  })
})

```

Give that a try and let me know if you get it working.

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by Igor-kswr** [comment]
Hello, I have the same issue

**Comment by nagash77** [comment]
@Igor-kswr please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
