### ISSUE TITLE
Bad Request Error after click on button and redirect on Cypress versions above 10.9.0

### ISSUE THREAD

**Issue by perrsikk** [cypress-io/cypress#25700]
### Current behavior

After clicking on the button which should redirect to another domain Bad Request Error appears
On version 10.9.0 and lower all working fine

### Desired behavior

Click on the button should redirect to another domain without an error

### Test code to reproduce
```js
 cy.visit(Cypress.env('clientIdTokenEndpoint'));
 cy.get('[id="LocalAccountSigninExchange"]').click();
 cy.get('[id="signInName"]').type(Cypress.env('clientSigninName'));
 cy.get('[id="password"]').type(Cypress.env('clientPassword'));
 cy.get('[id="next"]').click();

 cy.url().should('contain', Cypress.env('clientIdTokenRedirectUri')); // Test fails here due to Bad Request Error
 cy.location().then((location) => {
     const parsedIdToken = location.search.replace('?code=', '');
     Cypress.env('ID_TOKEN', parsedIdToken);
     window.localStorage.setItem('authToken', parsedIdToken);
  });
```
### Cypress Version

12.5.0

### Node version

16.14.2

### Operating System

Windows 10

**Comment by mschile** [comment]
Hi @perrsikk 👋, thanks for logging this issue. Would you be able to recreate the steps you posted above in a reproduction repository by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) or by other means? If you are switching domains, you may also want to try using [cy.origin](https://docs.cypress.io/api/commands/origin). Do you know what is invalid with the request causing it to return a Bad Request (400)?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
