### ISSUE TITLE
Cypress clock + joi validation

### ISSUE THREAD

**Issue by Goues** [cypress-io/cypress#2570]
### Current behavior:

When using joi library for validating user input with joi-date-extensions, joi internally checks date for either being an instance of Date or being a string or number to validated the input. When using cypress to test the entire flow of user input to output, we need to use Cypress clock to snapshot tests to a specific datetime, otherwise calculation get wrong over time.

But using Cypress clock makes the return value of `new Date()` not be an instance of `Date` :

`value instanceof Date === false`

see joi library here: https://github.com/hapijs/joi/blob/master/lib/types/date/index.js#L64

This means that using Cypress clock makes all dates invalid and not using it means all tests are wrong when a month passes.

### Desired behavior:

The mocked output of calling `new Date()` when Cypress clock is used should be an instance of Date.

`(new Date()) instanceof Date === true`

### Steps to reproduce:

1. call `cy.clock()` in test suit
2. call `(new Date()) instanceof Date` in tested code, it yields `false`

### Versions

Cypress 3.1.0
Chrome 69
Ubuntu 17

**Comment by chrisbreiding** [comment]
I verified this and think it can be solved by upgrading `lolex` to the latest version and [using withGlobal](https://github.com/sinonjs/lolex#lolexwithglobal).
