### ISSUE TITLE
"Corrupted Download" started appearing in GitLab CI as of 2023-02-06

### ISSUE THREAD

**Issue by peteygao** [cypress-io/cypress#25716]
### Current behavior

The CI script hasn't changed, we simply run a normal `npm ci` in our GitLab Runner CI instance, and today we started seeing:
```
URL: https://download.cypress.io/desktop/12.0.1?platform=linux&arch=x64
Error: Corrupted download
Expected downloaded file to have checksum: e5eb2c7ab64c81795b621058f756d026d176be6fc4b10f29fb0be8cf18bfbacbf4ab4dd7c1dd693a352153648c6fb3c713[172](https://gitlab.com/nextpayph/nextpay/-/jobs/3719106054#L172)497718c75322e408bd8bad3079d
Computed checksum: df13361d1b68af544365d2845aee19b3e467682b733a4668b99ec374b55402477b172520d465a6f081bec[174](https://gitlab.com/nextpayph/nextpay/-/jobs/3719106054#L174)22afc6ead7cc4d19b371d1c6b471429e129cef41
Expected downloaded file to have size: 172118384
Computed size: 2432345
----------
Platform: linux-x64 (Debian - 11)
Cypress Version: 12.0.1
```

_Some_ amount of downloading is occurring (about 2MiB, `2432345 bytes`), but it gets stuck at that point and the runner automatically times out after 30 minutes of waiting. The entire .zip file is over 164MiB, so something is failing with downloading the .zip file from Cypress's CDN.

We're using AWS Spot Instances for our GitLab Runner instances, and I checked `status.aws.amazon.com` and there's no reported issues/network outages at the time of me writing this Github issue on 2023-02-06.

### Debug logs

```Text
URL: https://download.cypress.io/desktop/12.0.1?platform=linux&arch=x64
Error: Corrupted download
Expected downloaded file to have checksum: e5eb2c7ab64c81795b621058f756d026d176be6fc4b10f29fb0be8cf18bfbacbf4ab4dd7c1dd693a352153648c6fb3c713[172](https://gitlab.com/nextpayph/nextpay/-/jobs/3719106054#L172)497718c75322e408bd8bad3079d
Computed checksum: df13361d1b68af544365d2845aee19b3e467682b733a4668b99ec374b55402477b172520d465a6f081bec[174](https://gitlab.com/nextpayph/nextpay/-/jobs/3719106054#L174)22afc6ead7cc4d19b371d1c6b471429e129cef41
Expected downloaded file to have size: 172118384
Computed size: 2432345
----------
Platform: linux-x64 (Debian - 11)
Cypress Version: 12.0.1
```
```


### Cypress Version

12.0.1

### Node version

14.17.4

### Package Manager

npm

### Package Manager Version

6.14.14

### Operating system

Linux

### Operating System Version

Ubuntu 20.04

### Other

_No response_

**Comment by warrensplayer** [comment]
@peteygao Are you still having this issue?  I have verified the URL `https://download.cypress.io/desktop/12.0.1?platform=linux&arch=x64` and I can download the file.  I also reported the file size and checksum the same way that the Cypress download command is doing and those checkout as well.  

Are you able to see if there are any other errors happening in your GitLab runner instance?  Is the disk filling up causing the Cypress app to not be able to fully download?  Can you see if upgrading your Cypress version to the latest fixes it for you?

**Comment by marktnoonan** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
