### ISSUE TITLE
Cypress Component Testing: Support for Nuxt 3

### ISSUE THREAD

**Issue by floroz** [cypress-io/cypress#25719]
### What would you like?

A documented process or a plugin/addon to integrate Cypress Component Testing with Nuxt 3.

### Why is this needed?

Nuxt is the most popular meta-framework within the Vue.js community, competing in the same space as other meta-frameworks such as Next.js or SvelteKit.

Support for Nuxt 3 can further increase the Cypress appeal when evaluating testing frameworks amongst the Vue community. 

### Previous discussions

This [initial discussion](https://github.com/nuxt/nuxt/issues/14534) has been closed as the [Nuxt team confirmed that the Vite config can be exposed](https://github.com/nuxt/nuxt/issues/14534#issuecomment-1419025107).

### Reproduction Repository

I attempted to combine the suggestions coming from the Nuxt and Cypress teams into this reproduction repo: https://github.com/floroz/nuxt3-starting-template

However, I get the following error when trying to load Component Testing

![Screenshot 2023-02-06 at 14 38 57](https://user-images.githubusercontent.com/45793869/216985876-a3926cba-8dcc-400b-9484-7f256b94a113.png)

I am not familiar with the Cypress code so I couldn't tell whether the two configs (the one exposed from `@nuxt/kit`, and the one parsed from the `cypress.config.ts` `components.devServer.viteConfig` function.

### Feature Request

Could you please have a look and consider whether an _unsupported_ but _documented_ approach to integrating the two technologies can be implemented?

cc @lmiller1990

**Comment by lmiller1990** [comment]
Hi!

I think this is a dup of https://github.com/cypress-io/cypress/issues/23619. In an effort to minimize issues (around 2.8k right now). I will need to close it.

This doesn't mean nothing is happening. Quite the contrary - I am working on https://github.com/cypress-io/cypress/issues/25637 *right now*. This will let third parties slot their own integrations into Cypress.

Then, we can write a community plugin that makes Nuxt work. I'll try to do this in parallel with #25637. Please follow #23619 for progress. I'll post an update there now.

Thanks!
