### ISSUE TITLE
When comparing two jquery elements, expected value is rendered inside runner logs panel

### ISSUE THREAD

**Issue by shwarcu** [cypress-io/cypress#25710]
### Current behavior

I compare two jquery elements in my test.

It goes more or less like this:
```ts
    cy.get('#element-1').then(($container) => {
      cy.get('#element-2').should(($element) => {
        expect($container.contents()[2], 'Third node is player').to.eq($element[0]);
      });
    });
```

In Cypress runner `$element` (my expected value) is rendered (in a weird way). 
![comparing two jquery elements](https://user-images.githubusercontent.com/58426925/216769268-77e64f5b-140d-4d89-8f38-176d9d07a071.png)

### Desired behavior

I would like to have expected element to not be rendered in runner, but displayed as string, just like actual value that is tested.

So something like `<div#v105599. bla bla bla>` instead of rendering that element in Cypress runner UI.

### Test code to reproduce

I don't have it yet, if it's **really** necessary I can try to setup a repo with repro.

### Cypress Version

12.5.1

### Node version

v18.4.0

### Operating System

Linux, I use Arch btw

**Comment by nagash77** [comment]
Hi @shwarcu I'm sorry to hear you are having difficulties using Cypress.  We do require a reproducible example in entered tickets.  Our engineers will not have the bandwidth to recreate every issue entered on their own.  Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by shwarcu** [comment]
Ok, I will try to find minimal reproducible example and share it in a form of a repository. But that's not my top priority at the moment, the bug is not severe

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
