### ISSUE TITLE
Cypress headless mode does not exit after finishing the tests

### ISSUE THREAD

**Issue by TheRealWaleed** [cypress-io/cypress#25721]
### Current behavior

We have faced this issue with an old version of cypress (v9), so during our troubleshooting we have decided to test if the issue remains with a simple application using the newest version of Angular and Cypress.  
- Create new angular Project with `ng new demo`
- Add cypress with `ng add @cypress/schematic`
- run `ng e2e --headless`
=> cypress will run the tests without exiting the process after he is done.
Even with the flag _--exit_ which is true by default, we had the same result.

### Test code to reproduce

- Create new angular Project with `ng new demo`
- Add cypress with `ng add @cypress/schematic`
- run `ng e2e --headless`

### Cypress Version

latest

### Node version

18.13.0

### Operating System

13.1

**Comment by warrensplayer** [comment]
There is a `watch` option for Cypress that defaults to true.  So when you run with `ng e2e --headless`, it will run the tests and then wait and rerun the tests if it sees a change.  If you would like it to exit, you can run `ng e2e --headless --watch false` to get it to run once and exit.

Let me know if that works for you.

**Comment by TheRealWaleed** [comment]
Yaeh, it works ! Thanks for your time and support :)
