### ISSUE TITLE
Add "Start-with" to Cypress in order to get DOM elements

### ISSUE THREAD

**Issue by achelonmm** [cypress-io/cypress#2572]
### Feature

Other frameworks like Selenium or Katalon have an option to search IDs, classes or elements not only by their whole text but parts from them using the "startWith" command.

This is really helpfull when dealing with dynamic IDs.

In my particular case, I am creating a document in one of my test cases, and the ID of that test changes on every iteration of the test suite. At the moment I cannot control it with the tools available, however, if I could search by startWith('row_') I could filter the search so it only offers one result and the search would be a success.

### Current behavior:

There is no native way to search a DOM element by a startWith command and you are required to make a perfect match.

### Desired behavior:

Add a command that allows to search elements by a part of their ID or class, ideally startWith.

**Comment by chrisbreiding** [comment]
You can use a [CSS attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) to achieve this:

```javascript
cy.get('[id^=row_]')
```

will select an element with an `id` that starts with `row_`.

You can [create a custom command](https://docs.cypress.io/api/cypress-api/custom-commands.html#Syntax) to abstract it into something like `cy.startsWith('id', 'row_')` if you'd like.

**Comment by achelonmm** [comment]
Thanks a lot, that will definetly help, specially the custom commands for future cases!
