### ISSUE TITLE
E2E test window won't open

### ISSUE THREAD

**Issue by thednp** [cypress-io/cypress#25722]
### Current behavior

"npx cypress open" doesn't run the tests, it just hangs with an error

### Desired behavior

"npx cypress open" should open my specs and run them properly

### Test code to reproduce

I've updated from cypress 12.4.1 to 12.5.1 and everything went bad. No setting have been changed. Also a full reinstall (remove node_modules) and restart PC wont help.

The repo in question:
https://github.com/thednp/bootstrap.native

### Cypress Version

12.5.1

### Node version

16

### Operating System

Windows 10

### Debug Logs

```shell
Error: Build failed with 1 error:
error: Invalid option in build() call: "watch"
    at failureErrorWithLog (OpenSource\bootstrap.native\node_modules\esbuild\lib\main.js:1636:15)
    at OpenSource\bootstrap.native\node_modules\esbuild\lib\main.js:953:16
    at responseCallbacks.<computed> (OpenSource\bootstrap.native\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket OpenSource\bootstrap.native\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (OpenSource\bootstrap.native\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Other

The spec list also shows this strange and never seen before error:

![image](https://user-images.githubusercontent.com/6761246/217042465-2c2c164b-ed6e-42c4-95b4-1ac06c63bf4d.png)

**Comment by thednp** [comment]
**Update**:

I've replaced `@esbuild` and `esbuild` folders from a previous cypress 12.2.0 installation and it works with latest version 12.5.1

**Comment by mschile** [comment]
Hi @thednp 👋, thanks for logging this issue. I see the described error on multiple versions of Cypress (I tried 12.5.1, 12.4.1, 12.2.0, 11.2.0) and not just 12.5.1 with the current `master` branch. If I change to your `5.0.0-alpha1` tag, then all of the Cypress versions work.

![Image](https://user-images.githubusercontent.com/2002044/217105193-95917cf8-e5f7-4139-bf06-3cdbf5218720.png)

**Comment by thednp** [comment]
@mschile Thanks for the input. I've renamed the version tag back to 5.0.0-alpha1, removed node_modules and package-lock.json, reinstalled everything and error persists for some reason I don't understand.

**Comment by mschile** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by thednp** [comment]
@mschile just to let you guys know, I've updated to latest Cypress and Vite today, removed `node_modules` and `package-lock.json`, reinstalled everything, and just like that, the problem went away. I think there was a conflict of esbuild version between the two.
