### ISSUE TITLE
cy.clearLocalStorage should clear all localStorage of all domains

### ISSUE THREAD

**Issue by pieterdd** [cypress-io/cypress#2573]
### Summary of this thread so far
`cy.clearLocalStorage` doesn't behave the way I assumed it would. It doesn't clear _all_ local storage. The docs have since been updated to reflect this.

---

### Current behavior:

I was trying to write a simple test for some to do list website when I noticed that certain state wasn't being cleared correctly between tests. So I added some sanity checks like `cy.clearCookies()` and `cy.clearLocalStorage()` - which in theory should be redundant - and then I observed this: https://youtu.be/x6Yeh6WM5fM

Oddly enough, it looks like local state is magically reappearing for reasons I don't understand. Any idea what's going on? Here's the code snippet I executed:

```javascript
describe('Hello world', () => {
    before(function () {
        cy.viewport(1200, 660)
        cy.clearCookies()
        cy.clearLocalStorage()
        cy.wait(20000)
        cy.visit('https://www.any.do/').contains('Login').click()
        cy.contains('ALREADY A MEMBER?', {
            'timeout': 10000
        }).click()
        cy.get('#emailSignin #email').type('spam@pieterdedecker.be')
        cy.get('#emailSignin #password').type('badpassword')
        cy.contains('SIGN IN').click()
    })

    it('Is a test', () => {
        cy.log('Look!')
    })
})
```

Even going into the developer tools, Application tab, clicking 'Clear storage' and then clearing everything doesn't reset it. The only workaround I have found is selecting the local storage data for https://web.any.do and clicking 'Clear All'.

### Desired behavior:

The old local storage data should not reappear when the test reaches the domain https://web.any.do.

### Steps to reproduce:

1. Run this script with valid credentials. I've changed my example account's password, but you can use anydo@mailinator.com with password 'anydone'. The script should work even without the `cy.wait`; that was just to give me time to inspect cookie/local storage beforehand.
2. The test will pass.
3. Rerun the test.
4. The test will fail because it suddenly remembers the login.

### Versions

Cypress v3.1.0, Electron 59

**Comment by pieterdd** [comment]
Interesting... if this is correct it'd definitely be good to add to the documentation. But ideally I'd like _all_ local storage to be cleared by this command (or a similar one).

**Comment by pieterdd** [comment]
Thank you for your analysis!

I see that a documentation update has already been released. Assuming I'm able to figure out how to alter the behavior of `cy.clearLocalStorage` so that it clears everything, would you and the other maintainers be open to that? Or is there a specific reason for the current behavior?

**Comment by jennifer-shehane** [comment]
Oh, yes, we agree it should clear localStorage for all domains, or at least be controllable in some way to choose which domains they're cleared for.

**Comment by pieterdd** [comment]
I'm having lots of trouble setting up a development environment for the cypress repo (the `npm install` command fails), so I think I'll leave this code change up to you guys.

In the meantime, is there some sort of workaround you'd recommend? I'm assuming it's best to call `cy.visit` and then run `cy.clearLocalStorage` or `win.localStorage.clear` for every website I'd like to clear the storage of?

**Comment by vikasg52** [comment]
I am also having similar issue - Cypress not clearing the localStorage using cy.clearLocalStorage().

Any update- when  are we going to fix it?

**Comment by k-randstad** [comment]
I'm also having this issue, is there an update ??

**Comment by swathisham** [comment]
any update or workaround ?

**Comment by cle-skov-dk** [comment]
This is still an issue,

**Comment by BirgitPohl** [comment]
So I have cy.visit() on a beforeEach and the cy.clearLocalStorage() on the actual test. In this case.
It clearly does not reflect, what it says and I'm having a little staging/production miss-match:
I wonder, if there is a way to clear cookies and local storage when ending the browser as one might need a clean browser to start the tests.

**Comment by rzegnam** [comment]
Still here...

**Comment by rzegnam** [comment]
Any news on this?

**Comment by benjaminbours** [comment]
I really need this feature as well. I was looking at the codebase of the function, but I'm not an expert of coffee script and it seems like it is the same as adding a custom command. So I rather tried to implement it in my project. My idea was to use the `window.frames` or to select all the iframes in the page to execute the `localStorage.clear()` on every window. But it doesn't seems to work, I don't know why.

Maybe you can tell me why this approach is apparently wrong and how should I approach it so everyone can have this feature, which is by the way, very needed in case of OAuth.

Thank you in advance the Cypress team 👍

**Comment by BradRyan** [comment]
I was getting burned by this as well.  We run on a different domain during development.  You could try:
```
cy.on('window:before:load', window => {
    window.localStorage.clear();
});
```
Not sure if it's the right approach, but I ended up just writing an overwrite so that `cy.clearLocalStorage` it had the desired effect
```
Cypress.Commands.overwrite('clearLocalStorage', () => {
  cy.on('window:before:load', window => {
    window.localStorage.clear();
  });
});```

**Comment by cjost1988** [comment]
Hi,

I came across with another issue where this need to be addressed: Cookie Consent Management.
Would be glad if there is any solution around this?
Otherwise I've the feeling this is a dealbreaker :S 

Cheers and ty for the nice testing environment.

**Comment by anirudhmurali** [comment]
Any update on this?

**Comment by zeptonaut** [comment]
I'm curious how this interacts with the documentation on [`cy.clearLocalStorage`](https://docs.cypress.io/api/commands/clearlocalstorage.html#Syntax):

> Cypress automatically runs this command before each test to prevent state from being shared across tests. You shouldn’t need to use this command unless you’re using it to clear localStorage inside a single test.

I'm seeing behavior where adding a global:

```js
beforeEach(() => {
  cy.clearLocalStorage();
});
```

is changing a test from flaky to not flaky. Specifically, it looks like there are stale login tokens hanging around in `localStorage` between tests. When I run the test in isolation (`it.only()` for only that test), it passes 100% of the time. When I run the test alongside one other test that logs in to the app (put both in a `describe.only()` block together), the same test fails >50% of the time.

**Comment by zeptonaut** [comment]
I also tried adding a:

```js
beforeEach(() => {
  cy.visit('/');
});
```

based on this issue. In some tests, my team was setting local storage before visiting a URL, which I realized might be confusing given that local storage operates on a per-domain basis. In conjunction with this bug, it seemed like it was possible that this meant the local storage wasn't getting correctly cleared between tests because the local storage we were setting wasn't attached to a domain. In practice, though, that didn't matter and the test was still flaky even with that.

(In retrospec, it makes sense that this would have no effect: clearly Cypress has to have _some_ concept of what domain to attach the local storage entries to even before a `cy.visit()` call, or else the entries that we were setting (e.g. login) wouldn't have had the intended effects in our tests.)

**Comment by jfhector** [comment]
I'm also blocked with this issue. Anyone has found a reliable workaround?
@zeptonaut the issue description you gave matches exactly what I'm seeing.

**Comment by vldvld** [comment]
Any updates here?

**Comment by MLKiiwy** [comment]
If you want to clear the localstorage of an iframe that is not on your domain:
```js
  cy.get('#iframe-id', { log: false })
    .its('0.contentWindow.localStorage', { log: false })
    .then((localStorage) => localStorage.clear());
```
Of course this will work only with  "chromeWebSecurity": false, see https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/#application-with-iframe

**Comment by dominik-fielmann** [comment]
This workaround works for me:

```typescript
  beforeEach(() => {
    cy.window().then((window) => {
      window.sessionStorage.clear();
      window.localStorage.clear();
    });
  });
```

**Comment by uweku** [comment]
Awesome, @dominik-fielmann ! Your workaround worked for me, too, though I needed to "point" Cypress to the correct domain via cy.visit(...) upfront...

**Comment by ronhks** [comment]
So, after a lot of time, we realized the problem.
The `cy.clearLocalStorage()` cleans only the local storage under the `baseUrl` definition.
If you would like to open multiple pages, you have to explicit define the clearing in the `cy.visit()` call, like that:
```js
    cy.visit(`subdomain.another.domain`, {
      onBeforeLoad(win) {
        win.localStorage.clear();
      },
    });
```

I hope, this workaround helps.

**Comment by jacktomlinson** [comment]
Been trying this workaround but no luck yet... trying to clear a particular local storage value of a Typeform survey. The local storage items are set against `https://companyname.typeform.com` which isn't an actual page you can visit. 

Tried your workaround above @ronhks but in my scenario `https://companyname.typeform.com` just redirects to `https://typeform.com` if you try to visit it in the test and therefore doesn't clear the local storage.

Any ideas?

**Comment by ronhks** [comment]
in this case, can you tried to delete exactly the spcified local storage?
You can specify it in the `cy.localStorage.clear(<APP_DEFINITION>)`?

**Comment by jacktomlinson** [comment]
Tried that one I believe, but it doesn't clear it as the item of local storage is not on the same domain as where I am running the test from 😞.

**Comment by denysgalyuk-epicentrm** [comment]
Hi! @jennifer-shehane . Are you planning to add the possibility to clear all storages but not the main only? Is it in the roadmap?

As you can see it clears only main domain. The additional one has data even if I close the runner. It is hardly cached. `cy.clearLocalStorage()` fails to clear it also.
![image](https://user-images.githubusercontent.com/74910683/117442861-01544600-af40-11eb-8bde-8dd6136df79b.png)

**Comment by zekedellavechia** [comment]
this issue still present. I am working with multiple logins and cleaning the local storage and cookies is not working. I couldnt find a workaround but basically I have to execute case by case instead of a complete run, has someone found a workaround?

**Comment by LeoForLearning** [comment]
Hello, i do see this issue is open still . Any plans for a fix of this issue?
how ever the workarounds mentioned here did not help me much

**Comment by csimpi** [comment]
Facing with the same issue too

**Comment by the-bmc-dev** [comment]
I have the same issue too!

**Comment by hridyanshdugar** [comment]
Hi am facing the same issue, any helpful workaround?

**Comment by MehranShafqat** [comment]
is there any update on this, please?  this is causing huge issues as when we talk about E2E testing this is common stuff and common use case :(  facing huge issue due to this :(

**Comment by emilyrohrbough** [comment]
The new `cy.clearAllLocalStorage()` command will handle clearing local storage across all origin. This will be available in Cypress 12.
