### ISSUE TITLE
Cypress could not install Xvfb and run cypress again

### ISSUE THREAD

**Issue by kkislay** [cypress-io/cypress#25743]
### Current behavior

We are running Cypress (11.1.0) tests in parallel in Jenkins on the Chrome browser. 
The tests are failing consistently complaining about xvfb plugin not being installed. 

> If you are trying to pass multiple arguments, separate them with commas instead:
> 
> cypress run --spec arg1,arg2,arg3
> 
> The most common cause of this warning is using an unescaped glob pattern. If you are
> 
> trying to pass a glob pattern, escape it using quotes:
> 
> cypress run --spec "**/*.spec.js"
> 
> It looks like this is your first time using Cypress: 11.1.0
> 
> [STARTED] Task without title.
> 
> [SUCCESS] Task without title.
> 
> Opening Cypress...
> 
> Your system is missing the dependency: Xvfb
> 
> Install Xvfb and run Cypress again.
> 
> Read our documentation on dependencies for more information:
> 
> https://on.cypress.io/required-dependencies
> 
> If you are using Docker, we provide containers with all required dependencies installed.`

However, xvfb plugin is installed in the container. Sample dockerfile is as following:- 

> RUN microdnf -y install python38 python38-pip python38-devel python38-libs python38-setuptools \
>    zip \
>     bzip2 \
>    unzip \
>    tar \
>     xorg-x11-server-Xvfb \
>     gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib \
>    vim \
>    vi \
>    wget \
>    yum \
>    procps \
>    java-11-openjdk-devel && \
>    microdnf -y update && microdnf clean all
> RUN Xvfb-run -a -screen 0 1024x768x24 :99 &

We were using Cypress 9.7.0 in the past where xvfb command was - **RUN Xvfb -screen 0 1024x768x24 :99 &**
But after migrating to 11.1.0 hitting the above error. 

### Desired behavior

Cypress should open normally and tests should run without complaining about the xvfb plugin.

### Test code to reproduce

**cypress run  --browser chrome**

Code in the container for xvfb :- 

1. Xvfb-run -a -screen 0 1024x768x24 :99 &
2. RUN Xvfb -screen 0 1024x768x24 :99 & 

They both are failing. 

### Cypress Version

11.1.0

### Node version

16.18.0

### Operating System

RedHat docker container with All dependencies installed

**Comment by nagash77** [comment]
Hi @kkislay , have you tried using one of the Cypress provided docker containers?  This appears to be a problem with how you have your docker container setup.

**Comment by kkislay** [comment]
Yes it is an issue with the Docker container setup.
So we had been running tests on the same Docker image since last two years. We had Cypress 8.6.0 and 9.7.0 . There wasn't any issue at all. 
But now since we need to migrate to 11.1.0 the docker issue is popping up. 
We tried using the Cypress docker images but it has vulnerabilities. Hence we thought of building our own images on the fly with RedHat base image and all the dependencies baked in it. 

**If there is any specific way to install xvfb then I can try that too.**

**Comment by mschile** [comment]
@kkislay, here is some documentation that might be of interest:

https://docs.cypress.io/guides/continuous-integration/introduction#Xvfb
https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites

**Comment by flotwig** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
