### ISSUE TITLE
QS array in request no longer works

### ISSUE THREAD

**Issue by marina-mosti** [cypress-io/cypress#25745]
### Current behavior

When updating from Cypress 11 to 12, a bug was introduced with query strings within request.

On cypress 11:
```
qs: {
 myParam: [1]
}
```

Would correctly generate a query string `?myParam[]=1`

On cypress 12 this no longer occurs, and the array value is unwrapped from the array and treated as a single value
producing: `?myParam=1`

### Desired behavior

The QS parsing should understand array values, a "fix" currently is to force this behavior by doing:

```
qs: {
   'myParam[]': 1
}
```

Related possibly to: https://github.com/cypress-io/cypress/issues/17921

### Test code to reproduce

https://github.com/marina-mosti/cypress-request-11-bug

Run the test and check on the console log the request, you will see that the param is not an array

### Cypress Version

12.x.x

### Node version

16.14.2

### Operating System

mac 13.1

**Comment by mschile** [comment]
Hi @marina-mosti 👋, thanks for logging this issue. This change was listed in the breaking changes in the [changelog for 12.0.0](https://docs.cypress.io/guides/references/changelog#12-0-0):

> The [cy.request()](https://docs.cypress.io/api/commands/request) command now uses [querystringify](https://www.npmjs.com/package/querystringify) to stringify & parse the qs options. This change aligns with how the [cy.visit()](https://docs.cypress.io/api/commands/visit) command generates urls with query parameters. Addressed in [#20302](https://github.com/cypress-io/cypress/pull/20302).

This change also aligns with how the built-in [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) handles arrays.

```
const query = { arr: [1, 2, 3] }
const params = new URLSearchParams(query)
params.toString() // 'arr=1%2C2%2C3'
```

If needed, you can include your own query string parsing library to format the query string differently.

```js
const qs = require('qs')

describe('page', () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')

    const query = qs.stringify({ shouldBeAnArray: [1] }, { arrayFormat: 'brackets' })
    const url = `https://cypress.io?${query}`

    cy.request(url)
  })
})
```

**Comment by comrade-che** [comment]
Hi @mschile!
What to do if, in addition to the array, the URL contains other parameters. Is it possible to understand the syntax using my example?
https://rk.dev.nspd.rosreestr.gov.ru/api/actors/v2/actors?since=2006-01-02T15%3A04%3A05.999999999Z07%3A00&page=0&count=10&type=&ids=6bd2994e-c6b5- 4b28-800e-6a17f54131ea&ids=03386dbe-5185-4b96-900d-c2b1bb368ed6&ids=5df251fe-c046-4c1e-a98a-ec4d81c5ebf9'

**Comment by mschile** [comment]
Hi @comrade-che 👋, if you use the [qs](https://github.com/ljharb/qs) package I used in the previous example, you should be able to do something like:

```
// outputs 'since=2006-01-02&page=0&count=10&ids=abc&ids=def&ids=ghi'
const query = qs.stringify({ since: '2006-01-02', page: 0, count: 10, ids: ['abc', 'def', 'ghi'] }, { arrayFormat: 'repeat' })
```

You may also want to join our [discord](https://on.cypress.io/discord) server for help with any further questions.
