### ISSUE TITLE
Cypress is not able to find elements after the re-login dialog in iframe

### ISSUE THREAD

**Issue by Sashi999** [cypress-io/cypress#25758]
### Current behavior

I am stuck with an interesting issue where our application has a re-login dialog that has an iframe in it which launches the Ping federation login prompt. I am able to access the iframe using the iframe plugin. After the clicking the Sign in button in the real application the authentication happens and the dialog will be closed.
During the test case execution it looks like Cypress is getting stuck in the redirect authentication page which is inside the login dialog and it is not able to identify any elements on the next page. Can you please help me with this? This is a blocker for our testing 

### Test code to reproduce
```js
cy.frameLoaded(_4473GeneralPage.LoginIframe)
        cy.iframe().find(_4473GeneralPage.AssociateUserID).type(userId, { sensitive: true },{log: false})
        cy.iframe().find(_4473GeneralPage.AssociatePassword).type(password,{ sensitive: true },{log: false})
        cy.iframe().find('select#domainName option:selected').should('have.value', 'US')
        cy.iframe().find('select#domainName').select('US').invoke('val').should('eq', 'US')
        cy.iframe().find('select#BU option:selected').should('have.value', 'ho')
        cy.iframe().find('select#BU').select('ho').invoke('val').should('eq', 'ho')
        cy.iframe().find('.ping-button').click().wait(2000)
```

### Cypress Version

10.11.0

### Node version

v16.6.2

### Operating System

macos12.6.2

**Comment by mschile** [comment]
Hi @Sashi999 👋, unfortunately there doesn't seem to be enough information to reproduce the problem on our end. Would you be able to recreate the issue using the [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny/) project?

**Comment by Sashi999** [comment]
@mschile Thank you for the prompt response. We are creating a test app to recreate the scenario and will share the project here in few days.

**Comment by flotwig** [comment]
Unfortunately we have to close this issue due to inactivity. @Sashi999 Please comment once the repro is ready and we can re-open.
