### ISSUE TITLE
cy.request() : I hope support "Content-Type:multipart/form-data"

### ISSUE THREAD

**Issue by Xweirdo** [cypress-io/cypress#2576]
### Current behavior:
response:
     Status: 500 - Server Error

### Desired behavior:

cy.request() : I hope support "Content-Type:multipart/form-data"

**Comment by jennifer-shehane** [comment]
Could you provide the test code you have written, the behavior you are trying to test, and also a screenshot or the text of error that you are seeing?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
