### ISSUE TITLE
Wrongly styled header in Best Practices guide

### ISSUE THREAD

**Issue by korneevaed** [cypress-io/cypress#2577]
### Is this a Feature or Bug?
Bug

### Current behavior:

https://docs.cypress.io/guides/references/best-practices.html
Header "## Setting a global baseUrl" looks like paragraph text.

### Desired behavior:
It should look like a header. Please add styling

### Steps to reproduce:

1. https://docs.cypress.io/guides/references/best-practices.html
2. Scroll to the second last section

### Versions
Just docs

**Comment by chrisbreiding** [comment]
Issue moved to [cypress-io/cypress-documentation #1028](https://github.com/cypress-io/cypress-documentation/issues/1028) via [**ZenHub**](https://www.zenhub.com/)
