### ISSUE TITLE
page loads successfully, but cypress throws, pageload timeout error

### ISSUE THREAD

**Issue by ejjaganisairam** [cypress-io/cypress#25778]
### Current behavior

Timed out after waiting 1000ms for your remote page to load.
Your page did not fire its load event within 1000ms.
You can try increasing the pageLoadTimeout value in cypress.config.js to wait longer.
Browsers will not fire the load event until all stylesheets and scripts are done downloading.
When this load event occurs, Cypress will continue running commands.

### Desired behavior

pageload timeout should not be seen, after page load is success

### Test code to reproduce

```js
/// <reference types="cypress"/>
describe("suite",() => {
    beforeEach(() => {
        cy.visit("http://localhost:8080/Servlet_Project/")
    })
    it("test",() =>{
    cy.get('#num1').type(12)
    cy.get('#num2').type(12)
    cy.get("button").click();
   cy.url().should("include","/Servlet_Project/add")

    })

})
```

appcode used :  Request
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<form action ='add'>
Enter number 1 : <input id="num1" type ='text' and name ="num1"><br>
Enter number 2 : <input id="num2" type ='text' and name ="num2"><br>
<button type="submit">next</button>
</form>

</body>
</html>
```

output URL : http://localhost:8080/Servlet_Project/add?num1=12&num2=34

body : result46

### Cypress Version

12.5.1

### Node version

18.13.1

### Operating System

Windows 11

### Debug Logs

```shell
Timed out after waiting 1000ms for your remote page to load.
Your page did not fire its load event within 1000ms.
You can try increasing the pageLoadTimeout value in cypress.config.js to wait longer.
Browsers will not fire the load event until all stylesheets and scripts are done downloading.
When this load event occurs, Cypress will continue running commands.
```

**Comment by mschile** [comment]
Hi @ejjaganisairam 👋, unfortunately, I was unable to recreate your issue. I created a [reproduction project](https://github.com/mschile/cypress-test-tiny/tree/issue-25778) using your supplied spec and html response but the page loaded as expected. Please feel free to fork the reproduction project and make any changes to recreate the issue.

![Image](https://user-images.githubusercontent.com/2002044/218580252-925e3d36-c511-46c9-8781-e9241f446702.png)

**Comment by ejjaganisairam** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/68274020/218953190-b5dc4699-e297-4321-8343-b29346a677ae.png)
Expected : 
input URL : http://localhost:8080/Servlet_Project/
Out[ut URL : http://localhost:8080/Servlet_Project/add?num1=12&num2=12
Observed :
input URL : http://localhost:8080/Servlet_Project/
Output URL : http://localhost:8080/__/add?num1=12&num2=12
@mschile  ,
a) i don't understand why Servlet_Prioject is missing in the URL,  but the same runs good in normal browser on submission  of form, 
b) why this clear page triggered here in the logs ? and
c)it seems you have  used output url as  http://localhost:8080/add?num1=12&num2=12

Note : i don't know why cypress runner is not holding /Servlet_Project/ , i don;t know whether it is my mistake (if any)

**Comment by flotwig** [comment]
@ejjaganisairam could you try using the `experimentalSourceRewriting` feature? This sounds like a bug we've seen before where `__` is added to URLs: https://github.com/cypress-io/cypress/issues/6749#issuecomment-631932833

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open comment on this issue with a reproducible example, and we can look into it further. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by SriAbi20** [comment]
Hi ,
Even I faced the same issue  and i just cleared the advanced browsing data " I mean I cleared the browsing history in which all my tests are running " .

**Comment by reymarte07** [comment]
> Hi , Even I faced the same issue and i just cleared the advanced browsing data " I mean I cleared the browsing history in which all my tests are running " .

Thanks for advice, I just cleared browsing history of the Chrome.
