### ISSUE TITLE
Wrong type definition for 'match' - removes 'string', should be 'RegExp'

### ISSUE THREAD

**Issue by Akxe** [cypress-io/cypress#2578]
### Current behaviour:

'match' requires its argument be a 'RegExp'. You passed 'https://example.com'.

### Desired behaviour:

Since in type anotation is as fallow:
```
/**
 * Asserts that the target matches the given regular expression `re`.
 * @example
 *    cy.wrap('foobar').should('match', /^foo/)
 * @see http://chaijs.com/api/bdd/#method_match
 * @see https://on.cypress.io/assertions
 */
(chainer: 'match', value: string | RegExp): Chainable<Subject>
```
I would assume it would take string. Since it is `match` I thought it would use String.match function...

### Steps to reproduce:

```js
context('test', () => {
	it('test', () => {
		cy.wrap('hello world').should('match', 'wolrd')
	})
})
```

### Versions

Cypress: 3.1.0
OS: Windows 10
Browser: Chrome 69.x.x

**Comment by chrisbreiding** [comment]
Looks like we have [the type annotation wrong](https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L2491). 

This is part of chai and is [documented to only accept a RegExp](https://www.chaijs.com/api/bdd/#method_match). This follows the [String.prototype.match signature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match). 

For matching a substring, you can use `include` instead:

```javascript
cy.wrap('hello world').should('include', 'wolrd')
```

**Comment by Akxe** [comment]
Sure I used contain, but it should be corrected non the less. 

---------- Původní zpráva ----------
Od: Chris Breiding 
Datum: 9. 10. 2018 v 18:49:30
Předmět: Re: [cypress-io/cypress] 'match' requires its argument be a 
'RegExp' (#2578)


Looks like we have the type annotation wrong
(https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L2491)
.

This is part of chai and is documented to only accept a RegExp
(https://www.chaijs.com/api/bdd/#method_match). This follows the String.
prototype.match signature
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match)
.

For matching a substring, you can use include instead:


<span>cy</span>.<span>wrap</span>(<span><span>'</span>hello world<span>'</span></span>).<span>should</span>(<span><span>'</span>include<span>'</span></span>, <span><span>'</span>wolrd<span>'</span></span>)


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/cypress-io/cypress/issues/2578#issuecomment-428266228), 
or mute the thread

**Comment by Manishku99251** [comment]
Hi I am learning Cypress and new to it just wanted to know how can I achieve the Following 
: want to check the font-family value of the button but match is expexcting a Regexp

it('finds the Submit Button and Submits it', function(){

      cy.get('input[type="submit"]').should('have.css','font-family').and('match','inherit')

     cy.get('input[type="submit"]').click().then((submitobj)=>{

         //cy.get(obj).should('have.value')
         expect(submitobj).to.have.value('LOGIN')
     })

  })

**Comment by Akxe** [comment]
Either use `.and('match', /inherit/)`, or I think there is contain keyword.

**Comment by Manishku99251** [comment]
@Akxe I am still unable to make it work could you please give an example or something. my requirement is like to match something with the url? eg. cy.url().should('match','/adfs/ls/')

**Comment by jennifer-shehane** [comment]
@Manishku99251 This annotation for using cypress is correct, I would suggest using a [regexp checker](https://regex101.com/) to determine how to write the regexp against what you want to check.
