### ISSUE TITLE
v12.2.0 ignore watchForFileChanges config when running test via command line

### ISSUE THREAD

**Issue by hoa-pham82** [cypress-io/cypress#25793]
### Current behavior

I'm trying to run a specific test file by the command line: 
`cypress run --spec 'cypress/e2e/API/getPetStatus.test.js' --headed --no-exit`

I don't set watchForFileChanges, but modifying the test file will not trigger a re-run test against the new changes.

### Desired behavior

Trigger a rerun

### Test code to reproduce

Reproduce using npm project:

- npm init
- Create a sample test
- Run cypress run --spec 'cypress/e2e/API/getPetStatus.test.js' --headed --no-exit

### Cypress Version

12.2.0

### Node version

v16.19.0

### Operating System

Window 11

**Comment by mike-plummer** [comment]
@warrensplayer For context, this was an intentional change introduced by #24097. Idea was the improve performance by not watching filesystem since `run` mode is most often a one-and-done execution. Feels odd to use `--headed --no-exit` rather than just using `open` mode, but maybe there's a valid use case. I'd want to see how e2e handles this scenario to ensure we have parity

**Comment by warrensplayer** [comment]
@hoa-pham82 Any particular reason you are trying to run your test this way versus using Cypress in open mode?

**Comment by hoa-pham82** [comment]
> @hoa-pham82 Any particular reason you are trying to run your test this way versus using Cypress in open mode?

No particular reason, for the first approach to cypress, I just wanted to run specific test spec via a custom command line.

**Comment by marktnoonan** [comment]
Thanks @hoa-pham82, I'm going to treat this this to a feature request. 

I think the experience you are looking for would be enabled more naturally if we supported `cypress open --spec 'cypress/e2e/API/getPetStatus.test.js'`. `open` mode doesn't currently support starting at a specific spec file. 

In the mean time the closest thing might be for you to open with testing type and browser flags, for example:

`cypress open --e2e --browser chrome` - which will bring you right to the E2E specs list in Chrome. You'll still have to search/click on your chosen spec, but then you will have live-reloading while you work.

**Comment by tnrich** [comment]
@marktnoonan this is related to the ask here - https://github.com/cypress-io/cypress/issues/23228 

I've been waiting for years (no exaggeration) to have a way to click a **_single_** link in VSCode (or some other editor) to open cypress **_and_** have it auto launch the spec in question. I still think this would be amazing to have. I don't care if it happens via `cypress open` or `cypress run`

Please consider making this functionality a possibility 🙏

**Comment by crfresneda** [comment]
I also realize the importance of open cypress by one click on VS CODE with a specific file .js. 

Sad that this issue was closed.
