### ISSUE TITLE
Debug 1.1 - Include avatar in Debug page header if available

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25796]
#### Current Behavior

The avatar for the commit author shown in the Debug page header is hardcoded to a fixed user icon.

<img width="1056" alt="header" src="https://user-images.githubusercontent.com/1702361/218600902-ded957f1-40d0-44cc-8a62-07890efe7b9f.png">

#### Desired behavior

Update the code to use the `commitInfo.authorAvatar` url  under the run if present.  If not, fallback to the icon.

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25796?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34

**Comment by astone123** [comment]
Do we know if `authorAvatar` is an email address or a URL? Currently the way that we do this in other areas of the app is by using the `UserAvatar` component which tries to get a Gravatar for the email address. If it doesn't find one then it falls back to the default icon.

**Comment by marktnoonan** [comment]
Based on services repo, it's a gravatar url already so we just need to render the provided image.

**Comment by astone123** [comment]
@marktnoonan okay, we can probably just update the `UserAvatar` component to accept a URL rather than an email
