### ISSUE TITLE
Missing X server or $DISPLAY

### ISSUE THREAD

**Issue by harikrishnankr-solace** [cypress-io/cypress#25792]
### Current behavior

when I tried to start my podman using the below command
`podman run -it -v $PWD:/e2e -v /tmp/.X11-unix:/tmp/.X11-unix -w /e2e -e DISPLAY=192.168.1.6:0.0 --env-file=podman.env --shm-size=8g --memory=0 --entrypoint cypress cypress/included:10.0.3 open --project . --config baseUrl=http://192.168.1.6:9000,responseTimeout=120000,pageLoadTimeout=180000`

Getting below error

`[14:0213/163944.771658:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
[14:0213/163944.773308:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
The Test Runner unexpectedly exited via a close event with signal SIGSEGV`

### Desired behavior

Podman should start and cypress window should be up and running

### Test code to reproduce

`podman run -it -v $PWD:/e2e -v /tmp/.X11-unix:/tmp/.X11-unix -w /e2e -e DISPLAY=192.168.1.6:0.0 --env-file=podman.env --shm-size=8g --memory=0 --entrypoint cypress cypress/included:10.0.3 open --project . --config baseUrl=http://192.168.1.6:9000,responseTimeout=120000,pageLoadTimeout=180000`
This is the command I used to run the podman

### Cypress Version

10.0.3

### Node version

v16.19.0

### Operating System

macOS 13.0

### Debug Logs

```shell
WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })
[14:0213/163944.771658:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
[14:0213/163944.773308:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
The Test Runner unexpectedly exited via a close event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Debian - 11.3)
Cypress Version: 10.0.3
```

### Other

I have added xquarts and it's working. added podman and given sufficient permission

**Comment by marktnoonan** [comment]
Hi @harikrishnankr-solace, thanks for reporting this.

Something that would help would be knowing if things are any different on the latest version of Cypress, there have been some major changes to the binary since 10.0.3. If this is related to a problem within Cypress it's possible it has been fixed in one of the later releases.

**Comment by harikrishnankr-solace** [comment]
@marktnoonan I have upgraded cypress to 11.0.0
but same issue exists
`podman run -it -v $PWD:/e2e -v /tmp/.X11-unix:/tmp/.X11-unix -w /e2e -e DISPLAY=192.168.1.6:0.0 --env-file=podman.env --shm-size=8g --memory=0 --entrypoint cypress cypress/included:11.0.0 open --project . --config baseUrl=http://192.168.1.6:9000,responseTimeout=120000,pageLoadTimeout=180000`

`Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

[12:0213/235004.427783:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[12:0213/235004.428506:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.

----------

Platform: linux-arm64 (Debian - 11.4)
Cypress Version: 11.0.0`

**Comment by marktnoonan** [comment]
Thanks @harikrishnankr-solace, would you mind running with `DEBUG=cypress:*` and sharing the logs? I'd be curious to compare them with this old issue that might be related https://github.com/cypress-io/cypress/issues/18183

Do you have any other context you can share about the problem - is it your first time running Cypress in this podman environment, or did it used to work before and something has changed?

**Comment by marktnoonan** [comment]
@harikrishnankr-solace I'm going to close this now due to inactivity, please comment if you are still having an issue and believe it to be a problem on the Cypress side and we can re-open this.

**Comment by dht** [comment]
```
unset DISPLAY && cypress run --headless
```
