### ISSUE TITLE
Inconsistent cookie/local storage persistence behavior

### ISSUE THREAD

**Issue by cgutierrezpa** [cypress-io/cypress#25805]
## Context
We are using Cypress to perform E2E tests over a React app that uses an Auth0 flow with the [auth0-spa-js](https://github.com/auth0/auth0-spa-js) library, that works as follows:
- Visiting our app `/login` page (named `app.domain.com`) redirects to Auth0 login page (named `login.app.domain.com`)
  - Note that both pages share the same `domain.com`
- User enters login data
- Auth0 redirects to the App (the one named `app.domain.com`) and saves the following in the browser:
  - Local storage key: `@@auth0spajs@@::<access_token>::<other_auth0_data>`
  - A Cookie with key: `auth0.<access_token>.is.authenticated`
- Upon redirect, the React App uses the `auth0-spa-js` library to fetch this data transparently and retrieve the `access_token`
- App uses the `access_token` to fetch data from the server

Until now, we were using Cypress `9.7.0` with `experimentalSessionAndOrigin: true` in the Cypress config. The way we handled the login phase in our tests is by simply clicking through the UI, as follows:
- `cy.visit("/login"); // This visits our app login page which redirects to Auth0 page if user is not logged in`
- Typing and clicking in the Auth0 page, and clicking on the `Continue` button
- The flow then redirects to our App and continues without problem, i.e. the browser contains the above-mentioned cookies and local storage keys and sends the `access_token` correctly to the server

**This has been working seamlessly without any problems**, and without  any `cy.session` nor `cy.origin` calls

## Problem
When upgrading to Cypress 12, we noticed that the flow **inconsistently stores the local storage and cookies keys** that were mentioned above, meaning that, **in some executions, these keys will not persist in the browser through the flow**, and hence `auth0-spa-js` library cannot retrieve the `access_token` coming from the Auth0 flow, preventing the app from working as it cannot send the token to the server at that point
I have been debugging many versions and this is what I discovered so far:
- This happens more often than not, and greatly increases the number of flaky tests we have for our app (40 flaky out of ~100). It also makes several tests to fail even with 3 attempts per test, like in the order of ~10 more failures (see screenshot below, the bottom execution is for Cypress `9.7.0`; execution on top is for Cypress >= 12)
![image](https://user-images.githubusercontent.com/20757456/218701271-67a21c89-3d0c-46b9-af60-7cce76c168d2.png)
- This behavior started happening since version `10.10.0`. My guess is that it may have something to do with what is mentioned in the [changelog](https://docs.cypress.io/guides/references/changelog#10-10-0)
> More accurately send/set cookies in [cy.origin()](https://docs.cypress.io/api/commands/origin) when `experimentalSessionAndOrigin` is enabled. Addresses [#23551](https://github.com/cypress-io/cypress/issues/23551), [#22670](https://github.com/cypress-io/cypress/issues/22670), and [#23603](https://github.com/cypress-io/cypress/issues/23603).
- Changing `experimentalSessionAndOrigin` to `false` in versions `>= 10.10.0 && < 12.0.0` seemed to mitigate this, in the sense that **the issue still happens**, but it happens way _less frequently_. This results in having a similar number of flaky tests as above, but keeping the number of failures to a minimum, almost similar to the failures we were having before
- Since Cypress v12, as `experimentalSessionAndOrigin` is set to `true` by default and the config option is removed from the config, we can no longer disable it to mitigate this, making it impossible for us to work with newer versions of Cypress
- We've tried wrapping the process within `cy.session()` and still fails

### Desired behavior

I'm not really sure if this behavior is expected, but I would expect Cypress to consistently keep the keys in local storage and cookies mentioned in the context above every time Auth0 redirects to the app 

### Test code to reproduce

Providing test code to reproduce this is not trivial. Let me know if it is really needed and I can try to prepare some

### Cypress Version

10.10.0 and above

### Node version

v16.19.0

### Operating System

macOS 12.6

**Comment by flotwig** [comment]
@cgutierrezpa thanks for the detailed report. I understand a repro is not trivial, so could you please try updating to Cypress 12.7.0? We included some bugfixes related to session, origin, and cookies that may resolve your issues: https://docs.cypress.io/guides/references/changelog#12-7-0

**Comment by cgutierrezpa** [comment]
I will try to test it soon! Thanks for the update!

**Comment by AtofStryker** [comment]
@cgutierrezpa is this still an issue for you? I am going to close this ticket. But, if you are still experiencing issues, just drop a comment on this ticket and I will re open
