### ISSUE TITLE
How do I get a self signed local domain be trusted in Cypress?

### ISSUE THREAD

**Issue by TimPchelintsev** [cypress-io/cypress#25802]
### What would you like?

I want to get self signed local domain be trusted in Cypress

### Why is this needed?

I am developing over https on localhost manually, and with mkcert help chrome accept certificate as trusted.
Common approach in Cypress is some manual testing after test finishes, so it will be nice to have local certificate trusted in Cypress too.

**Comment by flotwig** [comment]
Hi @TimPchelintsev, Cypress intercepts HTTPS traffic for its core functionality, so there is currently no way to do this. More information: https://docs.cypress.io/faq/questions/using-cypress-faq#Is-there-a-way-to-give-a-proper-SSL-certificate-to-your-proxy-so-the-page-doesnt-show-up-as-not-secure

**Comment by raylu** [comment]
this definitely seems possible. mkcert creates a CA key at `~/.local/share/mkcert/rootCA-key.pem` and adds the corresponding cert to the system's trust store (`/etc/ssl/certs/` on linux). all cypress needs to do is use that CA to sign the certs it generates at https://github.com/cypress-io/cypress/blob/c1a7467d7caa5f5423c81aa311db6743e8bb5066/packages/https-proxy/lib/ca.js#L283
