### ISSUE TITLE
V12.5.1 - Unable to move the window on the spec list after I have opened Cypress

### ISSUE THREAD

**Issue by pistolpete101** [cypress-io/cypress#25803]
### Current behavior

1. Update Cypress to V12.5.1 on Windows 11
2. Run Cypress
3. Select Configured
4. Select Browser type and select Start E2E Testing in <browser>
5. Spec list screen opens
6. User is unable to move that screen and can only minimise.
![cypress1251](https://user-images.githubusercontent.com/23387965/218690917-93e44425-460c-4e1e-87b6-9e498c58853b.png)

### Desired behavior

User should have full control of screen, minimise close, resize etc

### Test code to reproduce

None needed just open Cypress

### Cypress Version

12.5.1

### Node version

v16.15.0

### Operating System

Windows 11

### Debug Logs

```shell
None to output
```

### Other

Couldn't run the logs for some reason but you can see the issue when following the steps, more visual behaviour than back end.

**Comment by flotwig** [comment]
That's strange. It looks just like you pressed F11 to put it in fullscreen, but I'm unable to do that on Cypress 12.5.1 on Windows 11, so I'm not sure how you would've got into fullscreen mode in the first place.

Try clearing your Cypress application state, the window size is saved across sessions: https://docs.cypress.io/guides/references/troubleshooting#Clear-App-Data

**Comment by flotwig** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
