### ISSUE TITLE
Video results directory structure differ on specific spec run

### ISSUE THREAD

**Issue by hpccpatest** [cypress-io/cypress#25815]
### Current behavior

Prerequisite to Reproduce: 
A test exists with the following directory structure - `e2e/tests/spec2.cy.js`.

Running `cypress run --spec ./cypress/e2e/tests/spec2.cy.js` generates the following directory structure for the result video file (missing the `tests` folder):
![image](https://user-images.githubusercontent.com/125404947/218856233-5396e333-700e-48d8-bf25-eaca17067c02.png)

### Desired behavior

Running `cypress run --spec ./cypress/e2e/tests/spec2.cy.js` should generate the following directory structure for the result video file i.e. the `tests` folder should be present (similar to how it's created on running all tests via `cypress run`):
![image](https://user-images.githubusercontent.com/125404947/218856505-521f685a-a3fa-45b0-abde-397d21e5bf43.png)

### Test code to reproduce

Forked test tiny repo here with reproducible example: https://github.com/hpccpatest/cypress-test-tiny

### Cypress Version

10.7.0

### Node version

v14.15.1

### Operating System

macOS 12.6.3

**Comment by Fanch-** [comment]
We got into the same "trouble".

It seems it is a wanted evolution, see https://github.com/cypress-io/cypress/pull/23794#issue-1370986480

But it broke our video path after upgrading, because we used to do a matching between **file** from the junit reporter and the default video path. (taking your directory structure to stay linked) 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="20.2390" tests="2" failures="0">
  <testsuite name="Root Suite" timestamp="2023-02-13T16:18:59" tests="0" file="cypress/e2e/tests/spec2.cy.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Describe spec 2" timestamp="2023-02-13T16:18:59" tests="2" time="20.2010" failures="0">
    <testcase name="Describe spec 2 test 1" time="7.0140" classname="test 1">
    </testcase>
    <testcase name="Describe spec 2 test 2" time="6.3660" classname="test 2">
    </testcase>
  </testsuite>
</testsuites>
```
So file cypress/e2e/**tests/spec2.cy.js** <-> videos/**tests/spec2.cy.js**.mp4

But as you mention, with the _relativeToCommonRoot_ we get "just" videos/**spec2.cy.js.mp4**.

Plus for different run configuration, which might get different _relativeToCommonRoot_, we will have the same video file name, but with different paths. It might be confusing in local in my opinion.

For the moment we tried different solution to be backward compatible with our flow.


1) Dynamically modify videosFolder config in _before spec_ from e2e conf :x: 

```js
        setupNodeEvents(on, config) {
          // *** modify video folder to get relative path instead of relativeToCommonRoot 'iso < v10' ***
          on('before:spec', (spec) => {
            // spec.name = 'cypress/e2e/tests/spec2.cy.js'
            config.videosFolder = 'cypress/videos/tests'
            // doesn't work

            // goal is to do :
            config.videosFolder = path.dirname(spec.relative.replace(spec.specType, 'videos'));
            // from 'cypress/e2e/tests/spec2.cy.js' to 'cypress/videos/tests/'
          })
        },
```
2) Change video location in _after spec_ :heavy_check_mark: 

```js

  // 1) it deletes a video file if test success
  // see https://github.com/cypress-io/cypress/issues/2522#issuecomment-749316813
  // 2) it switches video location if needed
  // see https://github.com/cypress-io/cypress/pull/23794#issue-1370986480
  on('after:spec', (spec, results) => {
    // results.video : ${pwd}/cypress/videos/spec2.cy.js.mp4
    if (results.stats.failures === 0 && results.video) {
      console.log('*Deleting passing videos*')
      // `del()` returns a promise, so it's important to return it to ensure
      // deleting the video is finished and we are not going further
      return del(results.video, { force: true })
    }


    // do not change video location if it's already what we want -> for us ft_ is the common first level structure
    const isVideoCompletePath = results.video.includes('ft_')
    if (!isVideoCompletePath){
      switchVideoLocation(spec, results);
    }


    function switchVideoLocation(spec, results) {
      // spec.absolute : ${pwd}/cypress/e2e/tests/spec2.cy.js
      // spec.specType : "e2e"
      console.log('*Switching video location*')

      const absoluteVideoLink = spec.absolute.replace(spec.specType, 'videos')
      // From ${pwd}/cypress/e2e/tests/spec2.cy.js
      // To -> ${pwd}/cypress/videos/tests/spec2.cy.js

      const newFileDir = path.dirname(absoluteVideoLink);
      // ${pwd}/cypress/videos/tests
      console.log(newFileDir)
      if (!fs.existsSync(newFileDir)) {
        fs.mkdirSync(newFileDir, {recursive: true});
      }

      // oldPath, newPath
      fs.renameSync(results.video, `${absoluteVideoLink}.mp4`);
    }

   // we don't delete empties folders, not a problem for us (CI)
  })
```

It could be nice to have an easier way to behave like before though.

**Comment by marktnoonan** [comment]
It's correct that this behavior is currently "as intended". I'm going to capture this as a feature request and keep it open for now, it's likely there's an issue that already captures this, when I find that I'll close this one as a duplicate.
