### ISSUE TITLE
Component Testing can sometimes hang after machine sleeps and wakes

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#25816]
## Description

Cypress can hang and require restarting after waking computer from sleep.

## More Information

This seems to happen in Vite projects and can be largely avoided with `experimentalSingleTabRunMode`.

To reproduce, open a component test for a project that uses Vite and put your computer to sleep, then let it wake. My experience is that Cypress hangs in the following state:

![Screenshot 2023-02-13 at 11.15.11 AM.png](https://images.zenhubusercontent.com/5bdc960898196e0c7295b593/9e1a8d55-27ad-4874-ae14-31d33367649b)

[More details in Slack](https://cypressio.slack.com/archives/C011BAPC614/p1676305160242889).

## Acceptance Criteria

- establish if CT unique, or E2E and CT
- bundler specific?
- OS specific?
- try to isolate fix it!

**Comment by lmiller1990** [comment]
Does this happen for E2E?

**Comment by lmiller1990** [comment]
I've seen this happen. Something like:

1. Using Cypress CT
2. Shut macbook
3. Come back some hours later
4. Need to restart Cypress

I have not confirmed if this happens for End to End or not.

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25816?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by astone123** [comment]
I've done some testing with this and I can only reproduce the bug in the following scenario:

- Running component testing
- Vite project
- Chrome browser

This doesn't appear to affect webpack projects, e2e testing, Electron or Firefox.

**Comment by lmiller1990** [comment]
Good to know, this is useful for estimating.

**Comment by eelibra** [comment]
i'm having the same issue on e2e, i'm on mac using chrome and my project only has cypress as the webapp is made in vaadin

**Comment by benjgil** [comment]
Also seeing this issue, e2e tests on windows with chrome
Vite app
