### ISSUE TITLE
v-on="$listeners" improvements if it is used

### ISSUE THREAD

**Issue by AmirrezaVasseghi** [cypress-io/cypress#25827]
### What would you like?

What we have seen:

We used a listener in our code, and what it did was that it disabled the fields for the user, so they could not put any string in those specific fields manually, but you were able to put a string in the fields using JS, as Cypress is doing. 
Thus testcases were passing via Cypress, where it should actually fail, as the user is not able to put anything in the fields.

Vue is being used.
*****
resources/assets/js/components/money.vue

...
```
  @keyup="perform_formatting"
    @click="click_handler"
    @blur="clean_decimals"
    v-on="$listeners"
  >
</template>
```
*****

The issue starts and ends in that money.vue component. If you notice, there are some other explicit directives there, such as @click="click_handler" , @blur="clean_decimals" , and so on. The bug was introduced when we added v-on="listeners". What v-on="listeners" does is essentially pass down a parent component’s (in this case <money> ) listeners* to the child component. What we did not account for is that in doing so, it overrode the aforementioned explicit directives, and therefore the @click , @blur, and so on were now overridden with nothing, basically.

You can reproduce this by add a test case for a component such as that to have v-on="listeners" set with any other explicit directives. 

Code Line:
******
```
                                <segment-blade-helper inline-template>
                                    <money type="text" class="form-control" v-on:focus="trackAnalyticsEvent('Offering Dashboard - Invite Investor - commitment_amount - focused - Client')" name="commitment_amount" />
                                </segment-blade-helper>
```
                                
******

### Why is this needed?

To make testcase execution accurate, and give correct result if they are passing or failing.

**Comment by lmiller1990** [comment]
Hi, are you able to provide a minimal reproduction repo we can clone and run? That would be greatly. You could reproduce this with either End to End or Component Testing.

**Comment by AmirrezaVasseghi** [comment]
Hello,
Unfortunately I can not share any repo with you due to company policies.
Below is the code slice where we added the v-on="listeners"

```
<template>
  <input
    ref="input"
    :id="id"
    :name="name"
    :class="classes"
    v-model="money"
    @keyup="perform_formatting"
    @click="click_handler"
    @blur="clean_decimals"
    @focus="$emit('focus')"
  >
</template>
```

You should be able to reproduce the issue by add a test case for a component such as that to have v-on="listeners" set with any other explicit directives.

**Comment by lmiller1990** [comment]
I think it will be much faster if you create a fresh repository and upload it with the necessary reproduction - you know this issue you'd like to solve better than I do. If you can do this, it'll be much faster to get 👀 on it. Try to add an example test that illustrates the problem.

You could use https://github.com/cypress-io/cypress-test-tiny as a starting point.

**Comment by AmirrezaVasseghi** [comment]
The Cypress test is simple, just locate the field and put an amount in it.

`		cy.get('#amount')
			.clear()
			.type('100')`
			
For that specific field, just add `v-on="listeners"`, so it overrides the aforementioned explicit directives. Thus when trying to put anything in the field manually, you are not able to do that.

What I can suggest is that, add a test case for a component such as that to have `v-on="listeners"` set with any other explicit directives. Then you should be able to reproduce it.

**Comment by lmiller1990** [comment]
I made https://github.com/lmiller1990/issue-25827. Run the `App` test. It passes.

Can you please fork this and show me how to reproduce the problem?

**Comment by AmirrezaVasseghi** [comment]
@lmiller1990 I checked the repo, and tried to reproduce the issue by setting `v-on="$listeners"` on the App.vue file, but could not, so I checked with our FE Engineer and he said:

`click_handler` , `clean_decimals`, and `perform_formatting` all need to be defined methods on the Vue component. 

That’s what’s being overridden by `v-on="$listeners` . The example repo you sent just has other directives being set when the component is called (from outside the component).

I hope the above info helps.

**Comment by lmiller1990** [comment]
@AmirrezaVasseghi Please ask your team member to fork the repo and illustrate the problem. Thank you!

**Comment by AmirrezaVasseghi** [comment]
@lmiller1990 A team member will look into the repo in near future. Meanwhile please place this ticket on hold.

**Comment by marktnoonan** [comment]
Hi @AmirrezaVasseghi, I'm going to close this issue until we have the reproduction - this is the closest thing to "on hold" that we have. When you comment with an update on the closed issue, it will be flagged for us and we can re-open and pick up investigating.
