### ISSUE TITLE
There is no option to remove default command line argument while launch browser through Cypress

### ISSUE THREAD

**Issue by PrashantKashid** [cypress-io/cypress#25821]
### Current behavior

Currently We have option to push command line argument while launching browser through cypress.config file, but there is no option to remove any default argument while launching browser, same like launchOptions.args.push, there should be option to remove any command line argument or option to launch browser with passing argument which user want.

**in cypress.config file** 

```js
setupNodeEvents(on, config) {
     
  on('before:browser:launch', (browser = {}, launchOptions) => {
     
       if (browser.family === 'chromium' && browser.name !== 'electron') {
 
     launchOptions.args.push('--disable-ipc-flooding-protection')
}
       return launchOptions
       console.log(launchOptions.args)  

   })
}
```

### Desired behavior

for adding argument there is launchOptions.args.push function same way there should be function to remove argument while launching browser.

### Test code to reproduce

**in cypress.config file** 
```js
setupNodeEvents(on, config) {
     
  on('before:browser:launch', (browser = {}, launchOptions) => {
     
       if (browser.family === 'chromium' && browser.name !== 'electron') {
 
     launchOptions.args.push('--disable-ipc-flooding-protection')
}
       return launchOptions
       console.log(launchOptions.args)  

   })
}
```
### Cypress Version

12

### Node version

16

### Operating System

windows 10

**Comment by PrashantKashid** [comment]
Any Update on this?

**Comment by marktnoonan** [comment]
Hi @PrashantKashid. Thanks for opening this issue. This should be already possible from what I can tell. `launchOptions.args` is an array, you should be able to remove any item from it using standard array methods (that's where the existing `push` method comes from). 

For example, picking one at random, to remove the `--use-mock-keychain` flag, you can do something like this:

```js
    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser = {}, launchOptions) => {

        if (browser.family === 'chromium' && browser.name !== 'electron') {
          launchOptions.args.push('--disable-ipc-flooding-protection')
          // get index of an item
          const useMockKeychainIndex = launchOptions.args.indexOf('--use-mock-keychain')
          // remove that index
          launchOptions.args.splice(useMockKeychainIndex, 1)
        }
        console.log(launchOptions.args)
        return launchOptions
      })
      return config
    }
```

**Comment by marktnoonan** [comment]
Hi @PrashantKashid, I'm going to close this one now due to inactivity, and because it seems like you can do what you want to using existing array methods. If this does not work for you, please comment back with more information.
