### ISSUE TITLE
Unable to run tests with a cloud project after upgrading to 12.6.0

### ISSUE THREAD

**Issue by kolaente** [cypress-io/cypress#25829]
### Current behavior

Upgrading to 12.6.0, running Cypress in CI fails with the following error:

```
We could not find a Cypress Cloud project with the projectId
```

Full CI run: https://drone.kolaente.de/vikunja/frontend/12622/1/8

### Test code to reproduce

Not sure if that's applicable here, I think this is not about a test per se?

### Cypress Version

12.6.0

### Node version

18.12

### Operating System

Docker image cypress/browsers:node18.12.0-chrome107

**Comment by marktnoonan** [comment]
@kolaente thanks for reporting, does this still work correctly on the previous version of Cypress?

**Comment by marktnoonan** [comment]
We may have a lead on the issue here. Could you confirm if you are passing CYPRESS_API_URL environment variable in this run?

**Comment by marktnoonan** [comment]
Update: We will have a fix for this shortly, I'm not sure of the exact timeline. If you would like a workaround in the meantime, you could rename your `API_URL` env variable to something else, that appears to be where the conflict exists. Otherwise, we will close this issue when the fix is ready.

**Comment by kolaente** [comment]
Yeah we have that environment variable defined.

**Comment by kolaente** [comment]
Since the issue was closed, is this fixed and released in a new version? Or do I need to use the latest build from main to test this?

**Comment by emilyrohrbough** [comment]
@kolaente This was a bug on in the Cloud and has been fixed. You should be able to continue to use Cypress 12.6.0. Please let us know if you have any other issues! Sorry!

**Comment by kolaente** [comment]
@emilyrohrbough Awesome, thank you very much for the fast fix!
