### ISSUE TITLE
Show warnings for invalid CT Framework Definition

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#25838]
## Description

https://github.com/cypress-io/cypress/pull/25780 introduces a public API for CT Framework definitions. 

It is possible a third party definition might be invalid or incorrectly identified, either:

- developer made a mistake
- the package was called `cypress-ct-*` but is not intended to be a framework adapter

In these cases, we should show a warning on the onboarding screen using our usual patterns. You probably want to catch or warn here, where we detect the frameworks: https://github.com/cypress-io/cypress/blob/feature/ct-public-api/packages/data-context/src/actions/WizardActions.ts#L169-L176. 

![ss](https://user-images.githubusercontent.com/19196536/219249064-3172491c-5c4d-418e-b184-dd137b9b9ad6.png)

Note: specifically wording isn't locked in - use your best judgement, and we will make a proposal to the design team. 

## Acceptance Criteria

- shows warning for malformed packages
- shows warning for correctly formatted but incorrect packages (does not comply to API)
- ~~ideally each package that is shown as errored, the text should should link to the relevant link on npm, eg `npmjs.com/package/<name here>`. If this is hard to implement, we can drop this requirement.~~
- has link to docs for framework definitions (https://on.cypress.io/component-integrations)
- update cypress documentation under the "Testing" header on the "Integrating with Third Parties" to show how to use these warnings to debug during framework definition development.

## Resources

- Whimsical: https://whimsical.com/app-component-testing-setup-KhaixCtPrqi5v2tGeBZQSD

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25838?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
Update on this one: 

- code is done (also added a component test)
- going to finalize with Design before updating the description and requesting PR review
- struck the npm link requirement for now
- will make the docs PR before we move this to Done.
