### ISSUE TITLE
Cypress app hangs and freezes on MacOs Ventura 13

### ISSUE THREAD

**Issue by ScaryBobo** [cypress-io/cypress#25843]
### Current behavior

Cypress app hangs and freezes, with no error logs shown, anyone facing this issue as well? 

### Desired behavior

Should run as per normal in headed mode without hanging 

### Test code to reproduce
```js
describe('My First Test Suite', function() 

{
 
    it('My FirstTest case',() => {
        cy.visit("https://www.google.com/");
        cy.get('img[alt="Google"]').should('be.visible');
        
    })
 
})
```
### Cypress Version

11.2.0

### Node version

v19.0.1

### Operating System

macOs Ventura 13.2.1

### Debug Logs

```shell
cypress:server:cypress about to exit with code 0 +6s
  cypress:server:browsers browsers.kill called with no active instance +4s
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 93, proxyRequestsReceived: 20, immediatelyMatchedRequests: 11, unmatchedRequests: 1, unmatchedPreRequests: 74 } +0ms
  cypress:cli child event fired { event: 'exit', code: 0, signal: null } +7s
  cypress:cli child event fired { event: 'close', code: 0, signal: null } +1ms
```

**Comment by marktnoonan** [comment]
Hi @ScaryBobo I haven't seen this error before, and I'm curious if you still experience this on 12.6.0. What command are you using to run Cypress?

**Comment by ontononton** [comment]
I have the same issue. Old projects work fine, creating new ones with cypress examples, starts hanging in a few runs. 
cypress 12.6.0 and older versions

using npx cypress open

**Comment by marktnoonan** [comment]
Thanks @ontononton, would you mind capturing debug logs with `DEBUG=cypress:* npx cypress open` on one of the projects that hangs and sharing the logs?

Also, to clarify, _old_ projects using the same version of Cypress and the same version of Ventura work fine for you?

And when you say "cypress 12.6.0 and older versions" - do you know the oldest version where you've seen this behavior?

**Comment by ontononton** [comment]
[Terminal Saved Output.txt](https://github.com/cypress-io/cypress/files/10794379/Terminal.Saved.Output.txt)

1. Launched cypress with "npx cypress open"
2. Ran example tests in chrome 110
3. Closed chrome 
Received result: Cypress hangs, can be closed only with force quit 


old projects running with 10.8.0 cypress and venture run fine

new projects with 12.6.0 or 10.8.0 have this issue. Did not try earlier version. 

Sorry if anything is misleading or just wrong in my set up.

**Comment by marktnoonan** [comment]
Hi @ontononton and thanks. I did see several errors log in the file you sent over, but those are logged for me as well and do not cause Cypress to hang for me when running a spec.

I am on Ventura, MacOs 13.2, Apple M1 Max, with 32 GB memory. Is anything different about your machine compared to mine?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by storableLuke** [comment]
I see the same thing, and have for a while now.

**Comment by nagash77** [comment]
@storableLuke In order to give our engineers the best chance at recreating your problem, are you able to create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by IonelLupu** [comment]
@nagash77 just use "cypress": "^13.6.1", and run it on a Macbook Pro M1 (Sonoma)
