### ISSUE TITLE
Problem with tags

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#25847]
### Current behavior

I'm using `cypress-tags 1.1.2` plugin to run tests in different environments.
I'm running few tests in loop (example code attached).
The problem is that these tests always run, no matter what the tags are.

### Desired behavior

My tags are added to `desribe` not to separate `it` so it should be filtered.

### Test code to reproduce

[test.txt](https://github.com/cypress-io/cypress/files/10755570/test.txt)
```js
const modules = ['module1', 'module2', 'module3']

describe(['staging'], 'test', () => {
  modules.forEach(module => {

    it('Test something in ' + module, () => {
      //my test
    });
  });
});
```
### Cypress Version

12.5.1

### Node version

14.15.1

### Operating System

Windows 10/11

**Comment by jennifer-shehane** [comment]
cypress-tags is a community plugin, have you tried opening an issue with their repository on the functionality of the plugin? https://github.com/infosum/cypress-tags

**Comment by zbigniewkalinowski** [comment]
I just reported it: https://github.com/infosum/cypress-tags/issues/252

**Comment by nagash77** [comment]
Closing as this is an issue with a 3rd party plugin.  Please comment back here if new information arises that would require Cypress attention and we can reopen.
