### ISSUE TITLE
API for adding UI plugins

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#25856]
### What would you like?

One of the best features of Cypress is the ability to write plugins and expand its functionality. It would be nice to open Cypress UI for adding features as well, in a similar way as e.g. VS code does.

I have written several plugins that add stuff to UI, but it is done in a hacky way, here are some of them:
https://www.npmjs.com/package/cypress-plugin-xhr-toggle
https://www.npmjs.com/package/cypress-plugin-steps
https://www.npmjs.com/package/cypress-plugin-api

They all take advantage of the fact that Cypress runs in browser and you can get pretty much to any part. But Cypress can easily make a change that would make these plugins non-functional in an instant.

There are some other plugins that do this as well, e.g.:
https://www.npmjs.com/package/cypress-light-theme
https://www.npmjs.com/package/cypress-command-chain

There’s actually a really nice place for these types of plugins to be enabled:
![Screenshot 2023-02-16 at 18 27 24](https://user-images.githubusercontent.com/23213553/219441916-6ed04678-26fe-40ac-a876-0eb1706b9fa2.png)

or they could work similarly to experimental features, basically there are many ways you could go about this.

### Why is this needed?

Being able to add new UI elements, style them, or modify the behavior of browser could open up a whole another area of customizing Cypress ecosystem. I imagine community-driven Cypress Studio Recorder (fakerjs data generator anyone?), toggle buttons (like the XHR plugin I made), debugging tools, themes, helpers and other customizations

**Comment by emilyrohrbough** [comment]
This is a great idea and would provide value, but we unfortunately do not have the resources or capacity to consider implementing this type of feature at this time. We are happy to try & work with you to communicate larger UI changes that could impact your plugin(s). Thank you!
