### ISSUE TITLE
Cypress.Spec TypeScript definition differs from Actual object

### ISSUE THREAD

**Issue by hpccpatest** [cypress-io/cypress#25857]
### Current behavior

The TypeScript typings definition file for Cypress.Spec is missing some fields from the actual `Spec` object:

Definition:
![image](https://user-images.githubusercontent.com/125404947/219208568-919dec6d-84ba-41f4-bb70-f9b93002c7cb.png)

Actual Spec Object Contents:
![image](https://user-images.githubusercontent.com/125404947/219460122-1ddad536-56d5-47c0-8f00-2e009398e759.png)

### Desired behavior

The typings definition file for Cypress.Spec should resemble the actual object and contain the fields `baseName`, `fileName` and `specFileExtension`.

### Test code to reproduce

https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L279

### Cypress Version

10.9.0

### Node version

14.15.1

### Operating System

macOS 12.6.3

**Comment by marktnoonan** [comment]
Hi @hpccpatest, thanks for this report. Currently this is as intended, those properties are used internally by other Cypress code don't form part of the public API for `Cypress.spec`.

I'll keep this issue open a little longer as it might be possible to clear this up to avoid the confusion. And our docs for this aren't very fleshed out so maybe we can do more there.

Does this affect you in that you want to use these values somehow yourself, or did you just happen to notice the discrepancy?

**Comment by hpccpatest** [comment]
Hi @marktnoonan, thank you for taking the time to look into this. 

> Does this affect you in that you want to use these values somehow yourself, or did you just happen to notice the discrepancy?

I want to use these values in my project as a workaround for https://github.com/cypress-io/cypress/issues/25815. 
Since you mentioned that these are internal values, is there a possibility that they can/will be removed in the future?

Thanks again for your help with this.

**Comment by marktnoonan** [comment]
> Since you mentioned that these are internal values, is there a possibility that they can/will be removed in the future?

Yes, this is possible. I don't think it's likely to happen any time soon, we use them plenty in the codebase. It seems like if you use them, it would be OK, and worse case, one day you might unexpectedly have to roll your own parsing after a minor or patch update of Cypress.

I would like to document this better before they are removed though, and either commit to keeping them around or explicitly say they are not a part of the public API in our docs.
