### ISSUE TITLE
cy.contains('#something', 'text').should('be.visible') failed because "This element `<wc-icon-button-v3>` is not visible because it has an effective width and height of: `0 x 0` pixels."

### ISSUE THREAD

**Issue by anurag28** [cypress-io/cypress#25866]
### Current behavior

Hi there,

I'm encountering some flaky tests due to an element not being considered visible by Cypress, though the same is working fine on my local but not at all working through CI.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/32695350/219610046-9015f098-038e-494c-8d39-28f571734c9d.png">

I am using Cypress version 9.x

### Test code to reproduce

<img width="311" alt="image" src="https://user-images.githubusercontent.com/32695350/219611033-ccb90ca6-d823-40f2-9909-770b09a57d75.png">

### Cypress Version

9.6.1

### Node version

18.12.1

### Operating System

Ubuntu

**Comment by nagash77** [comment]
Hi @anurag28 , I see you are using a pretty old version of Cypress.  Can you please try upgrading to the latest version and see if the problem still occurs?  Any fixes found will not be backported to older versions so upgrading will be necessary in any event.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
