### ISSUE TITLE
Error running proxy middleware: Cannot call this.next() more than once in the same middleware function.

### ISSUE THREAD

**Issue by matys84pl** [cypress-io/cypress#25864]
### Current behavior

We run our Cypress component tests on CI (this issue is not reproducible when running locally).

Every test run fails every time with the following errors (one at a time), with the first two being most common.

Unfortunately we could not track specific test case as it's failing on random tests.

As far as I understand those are from the http proxy implementation (we use `cy.intercept` in every test case).

The merged PR https://github.com/cypress-io/cypress/pull/25702 was suppose to add some additional logging details to this error, however it did not change anything for us. Still the same error message, without any details about which particular command is causing it.

I've tried running it with DEBUG=cypress:*, increasing stack-trace-limit, etc,  but there was nothing that could give any idea of the reason.

```
Error running proxy middleware: Cannot call this.next() more than once in the same middleware function. Doing so can cause unintended issues.
Error: Error running proxy middleware: Cannot call this.next() more than once in the same middleware function. Doing so can cause unintended issues.
    at p.next (<embedded>:4515:179166)
    at e.continueResponse (<embedded>:4311:112116)
    at e.onResponse (<embedded>:4311:112012)
    at D (<embedded>:4311:97448)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async d.handleSubscriptions (<embedded>:4311:101367)
    at async Object.f (<embedded>:4311:110738)
```

```
onResponse cannot be called twice
Error: onResponse cannot be called twice
    at onResponse (<embedded>:4363:98636)
    at D (<embedded>:4363:96927)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async d.handleSubscriptions (<embedded>:4363:100846)
    at async Object.f (<embedded>:4363:110217)
```

```
Cannot read properties of undefined (reading 'testsuite')
TypeError: Cannot read properties of undefined (reading 'testsuite')
    at n (<embedded>:2861:19018)
    at E.<anonymous> (<embedded>:2861:19631)
    at R.emit (node:events:539:35)
    at S.emit (<embedded>:4592:16654)
    at Object.onMocha (<embedded>:4639:425416)
    at p.<anonymous> (<embedded>:4639:66799)
    at p.emit (node:events:527:28)
    at p.emitUntyped (<embedded>:4350:84346)
    at <embedded>:4350:91863
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

```
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at D (<embedded>:2861:18626)
    at E._onSuiteEnd (<embedded>:2861:19429)
    at E.<anonymous> (<embedded>:2861:19568)
    at R.emit (node:events:527:28)
    at S.emit (<embedded>:4592:16654)
    at Object.onMocha (<embedded>:4639:425416)
    at p.<anonymous> (<embedded>:4639:66799)
    at p.emit (node:events:527:28)
    at p.emitUntyped (<embedded>:4350:84346)
    at <embedded>:4350:91863
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### Desired behavior

Cypress should not throw these errors.

Cypress should include larger stack trace and include a reason of failure in error logs.

### Test code to reproduce

Unfortunately I don't have the code that reproduces it, as it only happens on our CI pipeline. It happens for random tests (we have hundreds of them). We cannot reproduce locally.

### Cypress Version

12.6.0

### Node version

16.19.0

### Operating System

gitlab runner/docker

### Debug Logs

```shell
cypress:net-stubbing:server:intercept-request request/response finished, cleaning up { requestId: 'interceptedRequest2435' } +100ms
  cypress:net-stubbing:server:util sending event to driver { eventName: 'after:response', data: { eventId: 'event2440', subscription: { eventName: 'after:response', await: false, routeId: '1676623707106-1564' }, browserRequestId: '3633.379', requestId: 'interceptedRequest2435', data: {} } } +93ms
  cypress:net-stubbing:server:util sending event to driver { eventName: 'after:response', data: { eventId: 'event2441', subscription: { eventName: 'after:response', await: false, routeId: '1676623705855-1449' }, browserRequestId: '3633.379', requestId: 'interceptedRequest2435', data: {} } } +1ms
  cypress:net-stubbing:server:util sending event to driver { eventName: 'after:response', data: { eventId: 'event2442', subscription: { eventName: 'after:response', await: false, routeId: '1676623705763-1424' }, browserRequestId: '3633.379', requestId: 'interceptedRequest2435', data: {} } } +0ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 34592 } +188ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 34580 } +1ms
  cypress:server:socket-base backend:request { eventName: 'net', args: [ 'event:handler:resolved', { eventId: 'event2417', headers: [Object], body: '......', method: null, httpVersion: null, statusCode: 200, statusMessage: null } ] } +54ms
  cypress:net-stubbing:server:driver-events received driver event { eventName: 'event:handler:resolved', args: [ 'event:handler:resolved', { eventId: 'event2417', headers: [Object], body: '......', method: null, httpVersion: null, statusCode: 200, statusMessage: null } ] } +54ms
Error running proxy middleware: Detected `this.next()` was called more than once in the same middleware function, but a middleware can only be completed once.
Error: Error running proxy middleware: Detected `this.next()` was called more than once in the same middleware function, but a middleware can only be completed once.
    at f.next (<embedded>:5146:265746)
    at e.continueResponse (<embedded>:4942:117690)
    at Object.b (<embedded>:4942:118691)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  cypress:server:lib:util:suppress_warnings suppressed emitWarning from node: { process: process { version: 'v16.16.0', versions: { node: '16.16.0', v8: '10.6.194.11-electron.0', uv: '1.43.0', zlib: '1.2.12.1-motley', brotli: '1.0.9', ares: '1.18.1', modules: '109', nghttp2: '1.47.0', napi: '8', llhttp: '6.0.7', openssl: '1.1.1', cldr: '41.0', icu: '71.1', tz: '2022b', unicode: '14.0', electron: '21.0.0', chrome: '106.0.5249.51' }, arch: 'x64', platform: 'linux', release: { name: 'node', lts: 'Gallium', sourceUrl: 'https://nodejs.org/download/release/v16.16.0/node-v16.16.0.tar.gz', headersUrl: 'https://nodejs.org/download/release/v16.16.0/node-v16.16.0-headers.tar.gz' }, _rawDebug: [Function: _rawDebug], moduleLoadList: [ 'Internal Binding native_module', 'Internal Binding errors', 'NativeModule internal/errors', 'Internal Binding config',... 131 more items ], binding:
```

**Comment by marktnoonan** [comment]
Thank you for continuing to follow up! Sounds like we need to continue work around the logging.

Some other ideas for unblocking in the meantime below. Forgive me if these were already suggested and dismissed in previous discussion.

The scenario - CI only, unpredictable - and the range of error message makes me wonder if there is any pattern in CI with resource usage - does it point to an underlying issue with memory usage or something? Does bumping the resource class fix it? 

Also curious, since this is only in component testing for you, if there is a difference when using `experimentalSingleTabRunMode: true` in your component testing config?

Another option for debugging is to run without the command log, using `CYPRESS_NO_COMMAND_LOG=1 cypress run` which might reveal some information, since Cypress will consume slightly less resources when not using the command log. If it's a marginal resource thing.

**Comment by mike-plummer** [comment]
@matys84pl It would be _**extremely**_ helpful if you could share a reproduction case. This has been quite difficult to reproduce which indicates to me that there is a very particular structure of overlapping intercepts doing specific things to trigger this issue. If there's a set of tests that only fail when running in CI we can try to emulate that if you're able to share them.

The debug log you shared may indicate you have multiple intercepts firing for a single request - are they doing anything unique (using `middleware: true`, trying to do async requests/processing, etc)? Are there any plugins or other third-party Cypress libs being used in your setup? Are you using [CI Parallelization](https://docs.cypress.io/guides/guides/parallelization), if so does this still occur if it's disabled?

**Comment by matys84pl** [comment]
@marktnoonan we've tried different docker images but without any results. We still get the `.next()` error.

I tried using `experimentalSingleTabRunMode` and `CYPRESS_NO_COMMAND_LOG` as you suggested but no luck also.

@mike-plummer unfortunately I cannot. We've tried so many things to actually track it down, but couldn't find a single reason for it... we're at the stage of basically .skip(ing) every instance of it.. but it keeps returning on new (random) tests.

Regarding our usages of `cy.intercept`:
- we have a quite large number (~100) of intercepts in `beforeEach`
- all of them now being simple `cy.intercept('url', resultObject)` or `cy.intercept('url', (req) => req.reply(resultObject)`
- yes, we have cases where we intercept the same request again in test body 
- we don't have any `middleware: true`
- nothing unique (everything unique was already removed to fix the issue...)
- we use `@testing-library/cypress@9.0.0`
- yes, we use Parallelization but it also fails if we run a single job

IMHO, at this point, we really need a very detailed log that could tell us:
- which exactly intercept (if this is really because of it) caused this .next error
- why it's trying to call .next and why it called .next previously

If you could provide us a version with very detailed log I'm happy to run it and post the results  here immediately.

**Comment by BlueWinds** [comment]
I'm currently working on getting a binary with additional logging. Having combed through the code, it's unclear to me by which path and why we've hit the point where this error is thrown. I've added some logs around the calls to .next() - it can get called in a couple of ways, and my suspicion is that multiple of these ways are occurring.

One suspicion I have is that it's a race condition between test cleanup and test initialization, where an identical intercept might be registered multiple times.

Once I have a new binary built with additional debug logs in some places I suspect are related, I'll ask you for another run with DEBUG enabled, and we can hopefully get more information about what's going on, and can look at actually fixing the issue!

**Comment by BlueWinds** [comment]
@matys84pl - A new build with additional logs is available here: https://github.com/cypress-io/cypress/commit/38b560f69f066a4b14a3a2203bfcb7ed30930c21#commitcomment-101682422. If you can reproduce the issue with DEBUG logs again using that build, it should help me track down what's going on here.

**Comment by matys84pl** [comment]
Thanks for that build, will post results soon. 

But before that, something I noticed yesterday:

```
[31;1mcypress:server:reporter [0mtrying to load reporter: junit [31m+53ms[0m
  [31;1mcypress:server:reporter [0mjunit is built-in reporter [31m+0ms[0m

  [34;1mcypress:server:project [0monMocha start [34m+8ms[0m

  [31;1mcypress:server:reporter [0mgot mocha event 'start' with args: [ { start: [32m'2023-02-22T16:56:47.050Z'[39m } ] [31m+4ms[0m

  [34;1mcypress:server:project [0monMocha start [34m+10ms[0m

  [31;1mcypress:server:reporter [0mgot mocha event 'start' with args: [ { start: [32m'2023-02-22T16:56:47.071Z'[39m } ] [31m+9ms[0m

  [34;1mcypress:server:project [0monMocha suite [34m+11ms[0m
  [31;1mcypress:server:reporter [0mgot mocha event 'suite' with args: [ { id: [32m'r1'[39m, title: [32m''[39m, root: [33mtrue[39m, pending: [33mfalse[39m, type: [32m'suite'[39m, file: [32m'.TEST_FILE.cy.ts'[39m, retries: [33m-1[39m, _slow: [33m250[39m } ] [31m+11ms[0m

  [34;1mcypress:server:project [0monMocha suite [34m+7ms[0m
  [31;1mcypress:server:reporter [0mgot mocha event 'suite' with args: [ { id: [32m'r1'[39m, title: [32m''[39m, root: [33mtrue[39m, pending: [33mfalse[39m, type: [32m'suite'[39m, file: [32m'TEST_FILE.cy.ts'[39m, retries: [33m-1[39m, _slow: [33m250[39m } ] [31m+7ms[0m
```
And then I see all the logs twice - it definitely runs the same test case twice, as it hits our mock server, and I also see logs from the server twice. I even noticed once case when it was running 3 times the same at the same time.

That might be a reason for double .next() calls. However, however, not limited to it. As I remember we also had tests failing with `.next()` without doubled logs.

The good news is the problem with `.next` was solved, once we updated our pipelines resources (better CPU - 16core, 32 RAM). So this is IMHO some race condition happening only in slow environment. It also seems to be limited only to electron.

There were also some other logs that might be related:

```
[33;1mcypress:server:browsers:utils [0msearching for browser { nameOrPath: [32m'electron'[39m, filter: { name: [32m'electron'[39m, channel: [32m'stable'[39m }, knownBrowsers: [ { name: [32m'electron'[39m, channel: [32m'stable'[39m, family: [32m'chromium'[39m, displayName: [32m'Electron'[39m, version: [32m'106.0.5249.51'[39m, path: [32m''[39m, majorVersion: [33m106[39m } ] } [33m+508ms[0m

  [31;1mcypress:server:profilecleaner [0mfound 0 root level profile matches: [] [31m+0ms[0m
  [31;1mcypress:server:profilecleaner [0mfound 0 profile folders: [] [31m+1ms[0m
  [31;1mcypress:server:profilecleaner [0mfound 0 profile folders: [] [31m+0ms[0m

  [34;1mcypress:snapshot:error [0mTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
  [34;1mcypress:snapshot:error [0m    at new NodeError (node:internal/errors:372:5)
  [34;1mcypress:snapshot:error [0m    at validateString (node:internal/validators:120:11)
  [34;1mcypress:snapshot:error [0m    at Object.resolve (node:path:1098:7)
  [34;1mcypress:snapshot:error [0m    at Object.resolve (evalmachine.<anonymous>:1:751467)
  [34;1mcypress:snapshot:error [0m    at resolvePathsAndParent (<embedded>:5225:1347831)
  [34;1mcypress:snapshot:error [0m    at customRequire (<embedded>:5225:1346887)
  [34;1mcypress:snapshot:error [0m    at c (<embedded>:3169:237617)
  [34;1mcypress:snapshot:error [0m    at <embedded>:3169:238152
  [34;1mcypress:snapshot:error [0m    at <embedded>:5225:17619
  [34;1mcypress:snapshot:error [0m    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) [34m+0ms[0m
```

```
[33;1mcypress:server:browsers:utils [0mWebKit is enabled, but there was an error constructing the WebKit browser: { err: Error: Cannot find module 'playwright-webkit' Require stack: - /repo/cache/Cypress/12.6.0/Cypress/resources/app/packages/server/lib/browsers/utils.ts [90m    
at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)[39m [90m    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)[39m [90m    
at resolve (node:internal/modules/cjs/helpers:108:19)[39m 
at Function.resolve (evalmachine.<anonymous>:1:733924) 
at P (<embedded>:5146:307637) 
at Object.N [as getBrowsers] (<embedded>:5146:308472) 
at b.machineBrowsers (<embedded>:4803:46866) 
at E._setCurrentProject (<embedded>:4916:78351) 
at new E (<embedded>:4916:71597) at new N (<embedded>:4916:122779) 
at P (<embedded>:5218:437758) at s.exports (<embedded>:5218:530039) 
at <embedded>:5225:2607 at tryCatcher (/repo/cache/Cypress/12.6.0/Cypress/resources/app/node_modules/[4mbluebird[24m/js/release/util.js:16:23) at Function.<anonymous> 
```

**Comment by BlueWinds** [comment]
Good finds and information! Since `.next()` the error is occurring in the network proxy, I'd be surprised if it's browser specific - but it could very well be *slowness* specific. Electron is the slowest browser we have - Firefox and Chrome are significantly faster (eg, use less resources). So if it's a race condition made worse by low resources, it's possible that the other browsers are simply not as CPU hungry and it doesn't manifest there.

We do have a known issue where if a browser is slow to start, Cypress can start up multiple browsers and connect to them all; we already have a fix for that in https://github.com/cypress-io/cypress/pull/25898 for the next release. Could be what you're seeing with the duplicated logs, especially if increasing the CPU count reduces how frequently you see it. I'd be surprised if this were the root cause of the `.next()` error though. Feel free to try the prerelease build from develop - https://github.com/cypress-io/cypress/commit/7ea8285ef9260193b2e2f7e5cf0fa11e7033f677#commitcomment-101804510 - to see if the duplicated logs go away.

If you're not seeing the initial `.next()` error anymore after increasing your pipeline resources, are you still interested in tracking down the root cause here, or want to call it good and move on (especially if it's not reproing anymore for you)?

**Comment by matys84pl** [comment]
Hi,
when I try the prerelease build our test case that was consistently failing on low resource (.next() error) is now passing around 20% of the time, while 80% of the time failing with:

```
  cypress:server:socket-base backend:request { eventName: 'reset:server:state', args: [] } +6s
  cypress:proxy:http:util:buffers resetting buffers +48s
  cypress:server:remote-states resetting remote state +46s
  cypress:server:socket-base backend:request { eventName: 'get:rendered:html:origins', args: [] } +6ms
  cypress:server:socket-base automation:request get:cookies {} +1ms
  cypress:server:automation:cookies getting:cookies {} +0ms
  cypress:server:project onMocha fail +25ms
  cypress:server:reporter got mocha event 'fail' with args: [ { id: 'r5', title: '"before each" hook for "OUR TEST CASE NAME"', hookName: 'before each', hookId: 'h1', err: { message: "Cannot read properties of undefined (reading 'cookies')\n" 
```

But at least the .next() error is gone :D

**Comment by AtofStryker** [comment]
@matys84pl are you still running into this issue, or is it something entirely different now with the `Cannot read properties of undefined (reading 'cookies')` error?

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by fgouvea10** [comment]
has anyone managed to resolve the error? mine remains like the friend's, only when running the CI and in random tests. I don't believe I have to improve the CI environment for the tests to pass. this happened after I migrated from Cypress 10 to 12.

**Comment by ghost** [comment]
We kinda managed to fix this issue (at least it hasn't showed up during the last 5 runs while it failed 50/50 in the best case scenario before that)
I don't still fully understand what happened or why but here're some key conclusions:
1. We used a dynamic import inside one of our interceptors in the format:
```
export const myInterceptor = () => {
  return cy.intercept('GET', /url/, req => {
    return import('../path-to-json-file').then(file => {
      req.reply(file);
    })
  })
}
```
2. It happened **only** headlessly but not only in CI, I could consistently reproduce it locally when using `cypress run`
3. It always failed in 2 specs that are pretty different from each other and don't really have any common traits they don't share with other specs that never failed
4. We record videos of failed specs and I noticed that the error showed up after the request intercepted by the interceptor in step 1
5. It definitely didn't fail before we upgraded the repo to use Cypress >= v12
6. I didn't see any duplicate logs (no wonder since the duplicate issue seems to have been fixed in a past version and we're on the newest version)

As for the fix, I just refactored the interceptor from point 1 not to import the json files asynchronously and the issue seems t be gone so it's definitely related to some kind of async operations although I still have no clue as to why

@fgouvea10, is this situation similar to yours?

**Comment by jrutila** [comment]
I have encountered this exact problem.
```
  │ Cypress:        12.17.4                                                                        │
  │ Browser:        Chrome 116 (headless)                                                          │
  │ Node Version:   v18.17.1 (/opt/hostedtoolcache/node/18.17.1/x64/bin/node)                      │
  │ Specs:          9 found (Breadcrumbs.cy.ts, FeatureCarousel.cy.ts, Guide.cy.ts, GuideList.cy.t │
  │                 s, HintBody.cy.ts, HintCarousel.cy.ts, ProgressButton.cy.ts, Search.cy.ts, Uhs │
  │                 Reader.cy.ts)                                                                  │
  │ Searched:       **/*.cy.{js,jsx,ts,tsx}         
```

I have three tests that are failing to this, only in CI (Azure DevOps). I tried to enable the `experimentalSingleTabRunMode: true,` and one of the tests passed! But two are still failing.
```
 Running:  Search.cy.ts                                                                    (8 of 9)
[info] ✨ new dependencies optimized: markdown-it-plain-text
[info] ✨ optimized dependencies changed. reloading


  <NSearchField />
    ✓ renders (222ms)
    ✓ starts searching after three letters (661ms)
    1) renders the results
    2) emptying causes list to disappear


  2 passing (3s)
  2 failing

  1) <NSearchField />
       renders the results:
     Error: An error was thrown while processing a network event: Error running proxy middleware: Detected `this.next()` was called more than once in the same middleware function, but a middleware can only be completed once.
  Error: Error running proxy middleware: Detected `this.next()` was called more than once in the same middleware function, but a middleware can only be completed once.
      at f.next (<embedded>:4489:28281)
      at e.continueResponse (<embedded>:4471:133635)
      at e.onResponse (<embedded>:4471:133531)
      at D (<embedded>:4471:118597)
      at async (<embedded>:4471:124921)

  2) <NSearchField />
       emptying causes list to disappear:
     Error: An error was thrown while processing a network event: Error running proxy middleware: Detected `this.next()` was called more than once in the same middleware function, but a middleware can only be completed once.
  Error: Error running proxy middleware: Detected `this.next()` was called more than once in the same middleware function, but a middleware can only be completed once.
      at f.next (<embedded>:4489:28281)
      at e.continueResponse (<embedded>:4471:133635)
      at e.onResponse (<embedded>:4471:133531)
      at D (<embedded>:4471:118597)
      at async (<embedded>:4471:124921)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  4                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     Search.cy.ts                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```
  
The `Search.cy.ts` test looks like this:
```
describe("<NSearchField />", () => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  let historyStore
  beforeEach(() => {
    cy.intercept("/search/**", (req) => {
      req.reply({
        statusCode: 200,
        fixture: "search_results.json,null",
      })
    })
    createTestingPinia({ createSpy: cy.spy })
    historyStore = useHistoryStore()
  })
  it("renders", () => {
    cy.mount(NSearchField, {
      props: { gameId: "test", guideId: "/" },
    })
    cy.get("input").click()
  })
  it("starts searching after three letters", () => {
    cy.mount(NSearchField, {
      props: { gameId: "test", guideId: "/" },
    })
    cy.get("input").click().type("abb")
    cy.contains("typeMoreChars").should("be.visible")
    cy.get("input").click().type("a")
  })
  it("renders the results", () => {
    cy.mount(NSearchField, {
      props: { gameId: "test", guideId: "/" },
    })
    cy.contains("SR: GR1").should("not.exist")
    cy.get("input").click().type("abba")
    cy.contains("SR: GR1").should("be.visible")
    cy.contains("Only this text visible").should("be.visible")
  })
  it("emptying causes list to disappear", () => {
    cy.mount(NSearchField, {
      props: { gameId: "test", guideId: "/" },
    })
    cy.contains("SR: GR1").should("not.exist")
    cy.get("input").click().type("abba")
    cy.contains("SR: GR1").should("be.visible")
    cy.get(".v-field__clearable").click()
    cy.contains("SR: GR1").should("not.exist")
  })
})
```
So, it is using intercept with the fixture. And so was the other test that now passes with the experimental option.

I am using Azure DevOps for this and haven't yet figured out how to increase the resources. But the failure is constant at the moment.

**Comment by adamlusted-wiq** [comment]
Also encountered this issue.

**Comment by alexh-vaultplatform** [comment]
I had this issue running Cypress component tests headlessly (both locally and in the CI) but they passed when running in the browser. In my tests I had nested `describe` blocks. For some reason changing the nested blocks to `context` fixed the issue

**Comment by silipi** [comment]
I'm also having this issue in Cypress 12.9.0, it only occurs in CI, 70% of the time some random tests fail.

**Comment by aedryan** [comment]
Hello, in case this is useful to anyone in this thread or who finds it in the future, we had the same problem.  We were able to reproduce it locally by ensuring our local conditions matched those of CI, e.g.: running the app locally within the same container image that CI ran it in.  We found that [Mirage JS](https://miragejs.com/) mocks and Cypress mocks were conflicting and added a guard around starting the Mirage mocks, i.e.: only start Mirage if `(window as any).Cypress === undefined`.  I hope this helps!

**Comment by Raphael-U** [comment]
## Bug: `req.reply()` in function-based intercept handlers causes "this.next() was called more than once" error in Component Tests

### Current behavior

When using `cy.intercept()` with a function handler that calls `req.reply()` to stub a response in **Component Tests**, Cypress throws a middleware error:

```
Error running proxy middleware: Detected this.next() was called more than once in the same middleware function, but a middleware can only be completed once.
```

This error occurs even when:

- The intercept is only registered once
- The `times: 1` option is used
- The handler calls `req.reply()` exactly once

### Desired behavior

Function-based intercept handlers with `req.reply()` should work in Component Tests the same way they do in E2E tests, without middleware errors.

### Test code to reproduce

```tsx
import { mount } from "cypress/react18";
import MyComponent from "./MyComponent";

describe("Intercept Issue Reproduction", () => {
  beforeEach(() => {
    cy.intercept("GET", "**/api/csrf-cookie", { statusCode: 204 });
  });

  it("fails with middleware error when using req.reply()", () => {
    // Function-based intercept that causes the error
    cy.intercept("PUT", "**/api/resource/*", (req) => {
      const components = req.body.components || [];

      // Build dynamic response based on request
      const tempIdMap: Record<string, string> = {};
      components.forEach((c: any, index: number) => {
        if (c._tempId) {
          tempIdMap[c._tempId] = String(1001 + index);
        }
      });

      req.reply({
        statusCode: 200,
        body: {
          data: {
            taskData: {
              id: 456,
              components: components.map((c: any, i: number) => ({
                ...c,
                id: c._tempId ? 1001 + i : c.id,
              })),
            },
            tempIdMap,
          },
        },
      });
    }).as("updateResource");

    mount(<MyComponent />);

    // User action that triggers PUT request
    cy.get('[data-testid="add-item"]').click();

    // Error occurs when waiting for the intercept
    cy.wait("@updateResource");
  });
});
```

### Workaround

Using a **static response object** instead of a function handler avoids the error:

```tsx
// This works without error
cy.intercept("PUT", "**/api/resource/*", {
  statusCode: 200,
  body: {
    data: {
      taskData: {
        id: 456,
        components: [{ id: 1001, type: "item" }],
      },
      tempIdMap: {},
    },
  },
}).as("updateResource");
```

**Limitation**: Static responses cannot read the request body to construct dynamic responses, which limits testing scenarios where the response structure depends on request payload (e.g., mapping temporary IDs to real IDs).

### Cypress Version

15.9.0

### Node version

v22.x

### Operating System

Ubuntu 24.04 (WSL2)

### Debug Logs

N/A - The error is displayed in the Cypress UI test runner.

### Other

**Environment Details:**

- React: 19.1.0
- Vite: 7.0.0
- Testing Mode: Component Testing
- cypress-real-events: 1.15.0
- @4tw/cypress-drag-drop: 2.3.1

**Additional observations:**

1. The error persists even with `{ method: 'PUT', url: '**/api/resource/*', times: 1 }` configuration
2. Moving the intercept to different lifecycle hooks (`beforeEach` vs `it`) does not resolve the issue
3. The error appears to be in the component test proxy middleware layer, not the intercept handler itself

**Questions:**

1. Is there a recommended pattern for dynamic intercept responses in Component Tests?
2. Is this a known limitation of the Component Testing proxy implementation?
3. Are there alternative approaches (e.g., `req.continue()` with modification) that work in Component Tests?

**Comment by shemetz** [comment]
I've had the same issue now (2026), I agree with Raphael-U that the culprit seems to be the usage of `req.reply()` inside `cy.intercept()`.  removing it (replacing with a static object) made the test less flaky and prone to failure in the pipeline.
