### ISSUE TITLE
Cypress 12.6.0 is not on npmjs.com

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#25869]
### Current behavior

The latest release as of yesterday, v12.6.0 is not yet available on [npmjs.com](https://www.npmjs.com/package/cypress)

<img width="919" alt="image" src="https://user-images.githubusercontent.com/599538/219676455-7d2ed8cd-dc8d-4210-a0b6-da1dcfd63ff0.png">

Executing: 

    yarn add cypress --dev

leaves me with the previous release (12.5.1).

### Cypress Version

12.6.0

### Node version

18

### Package Manager

yarn

### Package Manager Version

1.22.19

### Operating system

Mac

### Operating System Version

13.1

**Comment by emilyrohrbough** [comment]
@verheyenkoen Oh wow! I ran the release and must have missed this step. I apologize. Thanks you for notifying! The npm latest tag is now pointing to Cypress 12.6.0.

**Comment by emilyrohrbough** [comment]
@verheyenkoen Shoot! I was mistaken... So YES we released 12.6.0, however we identified an issue internally with the 12.6.0 release that prevents some users from recording to the Cloud. A patch is being worked on to be released in a patch fix as soon as possible, but in the mean time, we are rolling the `latest` tag back to 12.5.1 to prevent users from accidentally pulling this in. If you'd like to use 12.6.0, please specify in your package.json for the time being.
