### ISSUE TITLE
cy.request fails with "> Error: incorrect header check" on response that should be ok.

### ISSUE THREAD

**Issue by ndonnellan** [cypress-io/cypress#2587]
### Current behavior:

I'm trying to call an API endpoint prior to running any tests to verify my starting data (including authentication) is valid. I'm using `cy.request` but when I pass what should be valid information, I get a cryptic error about `incorrect header check`. I can verify that if I pass bogus authentication information, i do get a 401, as expected. And I verify that using something like Postman to make the exact same request results in a 200 with a JSON response.

Here is my approximate code:
```js
      const url = "some-valid-url.example.com";

      const headers = {
        Authorization:
          'Bearer ...longstringhere...'
      };

      cy.request({
        url,
        headers
      });
```

### Desired behavior:

`cy.request` should return a 200 for this request

### Extra information
The response headers  include something like
```
Assembly-Version: 18.10.04.00
Content-Encoding: deflate
Content-Type:  application/json; charset=utf-8
Date: Wed, 10 Oct 2018 15:12:26 GMT
ETag: 9C257CF722FF66085F4DE5D56A7BE7A4
Server: Microsoft-HTTPAPI/2.0
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
```

I'm wondering if cypress doesn't handle these properly. I can try to set up a mock API server and see if that makes it easy to repro, but is there any documentation on what types of responses can't be parsed?

### Complete error output
```
CypressError: cy.request() failed trying to load:

some-valid-url.example.com

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: incorrect header check
```
### Versions

Beta Version 3.1.0

**Comment by jennifer-shehane** [comment]
I feel like this is possibly related to the Response headers `Content-Encoding: deflate`, but yes, having a reproducible example would be ideal for tracking this down.

**Comment by facebookdevbim** [comment]
I have this same error but I currently work around it by passing optional object {gzip: false}

**Comment by wassansalih** [comment]
cy.request({
method: 'GET',
 url, 
headers 
});
