### ISSUE TITLE
Open Selector Playground is not working in   cypress": "^9.6.1"

### ISSUE THREAD

**Issue by obelixFI** [cypress-io/cypress#25879]
### Current behavior

Open Selector Playground is not working in   cypress": "^9.6.1"

Clicking on 'Open Selector Playground' does not do anything 

### Desired behavior

In this situation, it should open and I should be able to find the locators of elements

### Test code to reproduce

cy.visit() to any site and try to open the Selector Playground

### Cypress Version

9.6.1

### Node version

v14.17.0

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hello @obelixFI , I see you are running on an old version of Cypress.  Are you able to reproduce this issue using the latest release?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by obelixFI** [comment]
Sorry for not responding earlier Ben , I upgraded to 12.3, it is working
fine now.

But, I am facing challenges with using cy.session now. Earlier, I was using
Cypress.cookies.preserveOnce, which was working smoothly for 2 years.

Thanks
BhaSha

**Comment by nagash77** [comment]
@obelixFI I'm glad your one problem is now solved.  If you are having further issues using cy.session feel free to open a new issue and we can investigate.  Check out [this guide on doing auth0 logins](https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication) for some examples of using cy.session.  Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.
