### ISSUE TITLE
Aliases no longer work as before (after update to Cypress 12.4.0)

### ISSUE THREAD

**Issue by HeshamMoneer** [cypress-io/cypress#25872]
### Current behavior

I had the following two segments of code in my testing scripts:
1) Aliasing two values 
```javascript
cy.get('#role_0').invoke('text').invoke('trim').as(`role_0`);
cy.wrap(index + 1).as('noRows');
```
2) Accessing the aliased values 
```javascript
cy.get('@noRows').then(noRows => {
    cy.get(`#row`).should('have.length', noRows);
});
cy.get(`@role_0`).should('eq', shipment_ST);
```
The script used to work fine before upgrading to cypress 12, but now the value of `noRows` is accessible and `role_0` is not.

### Desired behavior

Both aliases should be accessible in the code.

### Test code to reproduce

I attempted to change the `type` of the aliases in the `as` command call from the default `query` to `static`
```javascript
cy.get('#role_0').invoke('text').invoke('trim').as(`role_0`, {type: 'static'});
```
But this change needed to be applied in several other parts of my code. In order to avoid all these changes, I had overwritten the default `type` property to be `static` instead by adding the following code to my `commands.js` file:
```javascript
Cypress.Commands.overwriteQuery('as', function (originalFn, _, options) {
  if(!options) options = {};
  if(!('type' in options)) options.type = 'static';
  return originalFn.call(this, _, options);
});
```
The default I think should be static in Cypress since this is the old behavior upon which many testing scripts were based.

### Cypress Version

12.6.0

### Node version

18.12.1

### Operating System

WSL2

**Comment by nagash77** [comment]
Hi @HeshamMoneer  , I'm sorry to hear you are having issues using Cypress. We will have this investigated by our triage team and get back to you. We have some staff out at the moment so response times may be a bit delayed, please bear with us.

**Comment by flotwig** [comment]
@HeshamMoneer could you please refer to the Migration Guide for 12.x? There were some changes surrounding alias resolution: https://docs.cypress.io/guides/references/migration-guide#Behavior-Changes-in-Alias-Resolution

Possibly adding `{ type: 'static' }` to your aliases, as described in the guide, will solve your issue. Let us know how it goes and if this resolves your issue.

**Comment by HeshamMoneer** [comment]
@flotwig I already did that but overwriting the `as` query as mentioned above, but I was reporting because I thought that the type should be `static` by default in cypress in order for tests that already use aliases that way not to fail

**Comment by mjhenkes** [comment]
@HeshamMoneer, we looked at defaulting to static but decided it would cause more issues than not.
