### ISSUE TITLE
cypress reloads in infinite loop when calling cy.visit to http URL that upgrades to https.

### ISSUE THREAD

**Issue by Jsijbel** [cypress-io/cypress#25891]
### Current behavior

When visiting a page that triggers certain redirects, the test runner keeps reloading and looping endlessly.

https://user-images.githubusercontent.com/39823861/220307457-9c30ff6e-a37d-4abf-b370-2431082d3aae.mp4

### Desired behavior

Not reload the test runner and follow redirects.

### Test code to reproduce

```
describe('example cypress reload issue', () => {
  it('keeps reloading', () => {
    cy.visit('https://enexis.nl/mijn-enexis/mijn-aanvragen')
  })
})
```

### Cypress Version

12.6

### Node version

18.12.1

### Operating System

Win 11

**Comment by flotwig** [comment]
Thanks for opening an issue @Jsijbel. Confirmed that I can reproduce this behavior. Is there a specific version this started occurring on for you?

It seems like there is a 301 and two 302's before landing back on `inloggen`, possibly this redirect chain is causing Cypress to become confused: 
![image](https://user-images.githubusercontent.com/1151760/221624811-dc097493-ade5-4a77-9ed5-c9da64649264.png)

I'll get this routed and prioritized for a fix.

**Comment by Jsijbel** [comment]
Thank your for your response and acknowledgement. 
I honestly can't remember when this issue wasn't present, and we have been working with cypress in our teams for several years now. Normally this isn't a real issue for us as we collect the authentication programmatically in most cases, however for a new test case this is causing issues for us.

**Comment by krpatter-intc** [comment]
Was curious if there was a workaround ever found for this issue? I think I am perhaps hitting a similar issues (v12.9.0)

**Comment by wikstfre** [comment]
I am also curious about some workaround. Also having this issue (12.11.0) with an Angular app (redirects when authenticating).

**Comment by joaconigro** [comment]
Hi, I'm having the same issue. Is there any news about this problem? or any workaround? Thank you

**Comment by StefanSakovic** [comment]
I have the same problem..any news about this bug?

**Comment by BevanR** [comment]
We observed this unexpected looping behaviour when Cypress was running on https:// in the Chrome browser that it was driving. The server for our system under test (SPA web app) only supports the http:// protocol. When we manually removed the s in the URL bar in the Cypress-driven Chrome, it began behaving as expected again (no looping).

**Comment by StefanSakovic** [comment]
> We observed this unexpected looping behaviour when Cypress was running on https:// in the Chrome browser that it was driving. The server for our system under test (SPA web app) only supports the http:// protocol. When we manually removed the s in the URL bar in the Cypress-driven Chrome, it began behaving as expected again (no looping).

As first, 
Thanks a lot for solving our problem..
But need to ask..is it correct to leave tests like that...I mean is it good to work
only on http protocol instead of both? Thanks

**Comment by corydeppen** [comment]
Between our tests running fine on Firefox and the comment above by @BevanR (thank you!), I'm wondering if this may be related to Chrome's recent change to [use HTTPS by default](https://blog.chromium.org/2023/08/towards-https-by-default.html).

**Comment by nathan5x** [comment]
@flotwig - Our team is also facing the same issue. URL starts with `https`. This problem is happening only on Chrome. Firefox works perfectly fine.

**Comment by SimonFryPH** [comment]
Also having this issue - Chrome only

**Comment by StefanSakovic** [comment]
> htt



> Also having this issue - Chrome only

Cypress suport only http protocol.
Use http protocol instead of https..like this example:
--------------------------------------------------------------
**EROR*

httpS://www.someexampe.com(when u test  website with https its strating realoding)

**acceptable :**

http://www.someexampe.com   (when u test  website with http its **NOT** reloading)

**Comment by StefanSakovic** [comment]
> Also having this issue - Chrome only


Cypress suport only http protocol.
Use http protocol instead of https..like this example:
--------------------------------------------------------------
**EROR*

httpS://www.someexampe.com(when u test  website with https its strating realoding)

**acceptable :**

http://www.someexampe.com   (when u test  website with http its **NOT** reloading)

**Comment by burkedavid** [comment]
exactly same issue here on Cypress [13.5.0]

**Comment by mpoetzsch** [comment]
To summarize, the issue arises only with newer versions of Chrome (it worked for me with an older version). The problem likely started with the introduction of https://blog.chromium.org/2023/08/towards-https-by-default.html.

Workaround:
change the URL from https to http in the address bar of chrome and reload the web specs runner. After that, the tests run smoothly.

or a more permanent workaround is here:
https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome/881431
(the solution with the most upvotes)

**Comment by jennifer-shehane** [comment]
We would recommend having your cy.visit visit the correct protocol (http/https) to avoid the redirection loop for now to get around this issue. We're looking into if anything can be done with the Chrome's new logic.

**Comment by alexsch01** [comment]
I am only seeing this with `cypress open`, I don't see this with `cypress run`

Does anyone see the same?

**Comment by alexsch01** [comment]
> I am only seeing this with `cypress open`, I don't see this with `cypress run`

Nevermind.....I am now seeing this issue with `cypress run`

**Comment by JohnnyTheBoy** [comment]
does any of you have a solution for headless mode.... since I upgraded chrome to v120 I can't find a solution for making chrome use http instead of https and yes it falls in loop in headless mode. I tried all above mentioned possible solutions but no success yet.

**Comment by joaconigro** [comment]
@JohnnyTheBoy in my case I solved it by using this configuration

```js
export default defineConfig({
  video: false,
  e2e: {
    baseUrl: 'http://localhost:4273',
    specPattern: '**/*.feature',
    chromeWebSecurity: true, //using true prevents the page reload loop
    defaultCommandTimeout: 10000, //Extended the default timeout, might be slower in docker
    experimentalModifyObstructiveThirdPartyCode: true,
    setupNodeEvents
  }
});
```

the `chromeWebSecurity: true` fixed the loop issue

**Comment by pjg** [comment]
Well, the problem with setting `chromeWebSecurity` to `false` is that I can no longer manipulate iframes (as described in this post: https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress), so unfortunately that is not an option for me.

**Comment by JohnnyTheBoy** [comment]
@joaconigro It's not working for me.... Can you confirm that you have chrome v120

**Comment by joaconigro** [comment]
> @joaconigro It's not working for me.... Can you confirm that you have chrome v120

Actually, I'm not using Chrome, but Microsoft Edge v120. I thought it should work as well :(

**Comment by alexsch01** [comment]
I updated the workaround here: https://github.com/cypress-io/cypress/issues/25891#issuecomment-1861098656

**Comment by alexsch01** [comment]
FYI: this workaround doesn't work for Microsoft Edge

**Comment by JohnnyTheBoy** [comment]
@alexsch01  Nope..... still not working with Cypress v 13.6.1 and Chrome v120 .... you can test that by adding code to the scaffolded cypress tests.

**Comment by jennifer-shehane** [comment]
Hi, I'd like to get some understanding on why this workaround doesn't work for people. To visit the correct URL to begin with. Is there a reason you need to visit the `http` or `https` and have it resolve to the other protocol?

>We would recommend having your cy.visit visit the correct protocol (http/https) to avoid the redirection loop for now to get around this issue.

**Comment by alexsch01** [comment]
> Hi, I'd like to get some understanding on why this workaround doesn't work for people. To visit the correct URL to begin with. Is there a reason you need to visit the `http` or `https` and have it resolve to the other protocol?
> 
> > We would recommend having your cy.visit visit the correct protocol (http/https) to avoid the redirection loop for now to get around this issue.

Internal (not exposed to the Internet) company apps generally use http
- I am using the correct protocol (http) for the URL I'm visit'ing

**Comment by jennifer-shehane** [comment]
Yah I can recreate this infinite loop with this example which has no `https` protocol. 

![Screen Shot 2023-12-14 at 2 42 13 PM](https://github.com/cypress-io/cypress/assets/1271364/831c6b7a-9750-402c-8aab-c94e895ed226)

```js
it('loops forever', () => {
  cy.visit('http://http.badssl.com/')
})
```

![http://g.recordit.co/YPnzoQlmU1.gif](http://g.recordit.co/YPnzoQlmU1.gif)

**Comment by alexsch01** [comment]
Is there a chance this a Chromium bug?
The only place I've seen this behavior is Cypress so probably not

**Comment by alexsch01** [comment]
More testing....`cy.visit('http://LOCAL_IP_ADDRESS')` does not produce the looping issue where there is a nodejs HTTP web server on 0.0.0.0:80

**Comment by alexsch01** [comment]
> @alexsch01 Nope..... still not working with Cypress v 13.6.1 and Chrome v120 .... you can test that by adding code to the scaffolded cypress tests.

hmm works for me with http://httpforever.com......I'm using E2E in cypress

**Comment by alexsch01** [comment]
Lets say `test1` and `test2.com` are both in the host file and they go to the same IP Address
and there is no https version

cy.visit('http://test') - won't have the looping issue
cy.visit('http://test2.com') - will have the looping issue

for the httpforever.com example

cy.visit('http://146.190.62.39') - won't have the looping issue
cy.visit('http://httpforever.com') - will have the looping issue

**Comment by alexsch01** [comment]
In Chrome DevTools of Cypress Chrome
`location.href="http://http forever.com"`
It automatically upgrades it to https and loops

**Comment by alexsch01** [comment]
@jennifer-shehane In DevTools running in Cypress Chrome window,
`location.href = location.href.replace(location.origin, 'http://httpforever.com')`
It automatically upgrades it to https

**Comment by VolodymyrDmytriukhin** [comment]
I have also issue with opening `http` protocol - tried `chromeWebSecurity: true` - but strange that in 1 application it worked, but in another doesn't. 
Issue occurred after updating to chrome 120 
Not reproducible on Firefox 120

**Comment by jennifer-shehane** [comment]
We're narrowing in on a solution. So will hopefully have some updates soon on this.

**Comment by alexsch01** [comment]
### UPDATED
Below instructions works around the issue, until a proper solution is made

**Both** PART1 and PART2 are required

---
PART1 - in `it` block
```
if(top.location.protocol == 'https:') {
    top.history.replaceState('', '', top.location.href.replace('https://', 'http://'))
}
cy.visit('http://httpforever.com')
```
PART2 - in cypress config
```
chromeWebSecurity: false,
```

**Comment by VolodymyrDmytriukhin** [comment]
> ### UPDATED
> Below instructions works around the issue, until a proper solution is made
> 
> **Both** PART1 and PART2 are required
> 
> PART1 - in `it` block
> 
> ```
> if(top.location.protocol == 'https:') {
>     top.history.replaceState('', '', top.location.href.replace('https://', 'http://'))
> }

@alexsch01  this part of code is not working - because `top` is not a variable or function - looks like it should be executed as a browser JS injection

**Comment by alexsch01** [comment]
@VolodymyrDmytriukhin just tested on Linux, NodeJS 12.16.3, Cypress 10.0.0 - it works for me with chromium and electron

**Comment by alexsch01** [comment]
@jennifer-shehane I have this repo: https://github.com/alexsch01/testing where I'm trying to reproduce this

**Comment by alexsch01** [comment]
With further testing, it is definitely some issue between the Cypress proxy/server and newer versions of Chrome with http URLs

![image](https://github.com/cypress-io/cypress/assets/5721147/aea49c9d-5383-43e3-8616-cca3af249677)
```
console.log(port)
await new Promise(() => {})
```

Then, I launch Chromium with https://github.com/alexsch01/testing

Same result

**Comment by alexsch01** [comment]
@jennifer-shehane I made repo to reproduce the issue: https://github.com/alexsch01/testing

**Comment by jennifer-shehane** [comment]
Yah we can reproduce the issue and are working on a solution which requires some changes on the App as well as some manual changes to Chrome settings for users who have already encountered this issue to their hsts domain settings. It shouldn't cause an infinite loop for users in the future who haven't encountered it once though. Most of our team is on holiday this week however, so the solution will be delayed.

**Comment by alexsch01** [comment]
@jennifer-shehane Thanks. I made a bug report with Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1513507, since it could be a Chromium bug

**Comment by jennifer-shehane** [comment]
@alexsch01 Thanks for opening the issue. It does seem like they're not doing something correctly here.

**Comment by tudorgabriel** [comment]
> @jennifer-shehane Thanks. I made a bug report with Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1513507, since it could be a Chromium bug

just FYI the issue is also present on the Chromium version < 100.

**Comment by tudorgabriel** [comment]
https://github.com/cypress-io/cypress/assets/19550143/2fbb926b-f79c-4d1f-892a-28dcfbc2686d

Still not working properly

**Comment by alexsch01** [comment]
@tudorgabriel the fix on Cypress's side isn't released yet

**Comment by ir2508front** [comment]
> We observed this unexpected looping behaviour when Cypress was running on https:// in the Chrome browser that it was driving. The server for our system under test (SPA web app) only supports the http:// protocol. When we manually removed the s in the URL bar in the Cypress-driven Chrome, it began behaving as expected again (no looping).

I removed the 's' from https then it works for me. Thank you

**Comment by jennifer-shehane** [comment]
We're trying to get a release out for this today.
