### ISSUE TITLE
Support lazy evaluation for routes

### ISSUE THREAD

**Issue by TerrenceLJones** [cypress-io/cypress#259]
Instead of only using a glob or regexp, it be nice to also have the ability to do the following: 

```
 route('/myURL//:lazy_param', function () {})
```

**Comment by TerrenceLJones** [comment]
@brian-mann I've opened this issue as per our conversation on Gitter. My understanding of what really needs to be implemented is lacking. If I missed something can you help me formulate a more in depth description of this issue?

**Comment by andersthorbeck** [comment]
This seems to be a variant of the feature suggestion in https://github.com/cypress-io/cypress/issues/387

**Comment by jennifer-shehane** [comment]
Closing as duplicate of https://github.com/cypress-io/cypress/issues/387
