### ISSUE TITLE
Fail to mount a react component in component testing

### ISSUE THREAD

**Issue by dualeoo** [cypress-io/cypress#25902]
### Current behavior

- Issue: Fail to mount a react component in component testing
- Cause: React points to incorrect module
- How to reproduce:
  - Install cypress as instructed on website
  - `cypress open`
  - Configure the cypress app in component testing mode
  - Run test for a simple component
- Technical details:
  - When mount a react component using `cy.mount()`, I got this error: `Cannot read properties of undefined (reading 'version')`. 
  - When debugging, I learnt that this error is thrown by this line `if (major_1(React__default.version) === 18) {` in `cypress/react/dist/cypress-react.esm-bundler.js`. 
  - By `console.log()`, I learnt that `React__default` is `undefined` and `React` points to this incorrect module:
<img width="336" alt="Screenshot 2023-02-22 at 00 13 32" src="https://user-images.githubusercontent.com/21116459/220414020-cbe216ae-e77c-4b4e-8ac4-7ea95c962386.png">
Instead of pointing to the correct react module:
<img width="664" alt="Screenshot 2023-02-22 at 00 14 48" src="https://user-images.githubusercontent.com/21116459/220414265-11262440-e358-4281-9c03-a5ddf3dd19b0.png">

  - The main idea of `if (major_1(React__default.version) === 18) {` is to check react version by accessing the version field of React__default. As `'react'` is resolved to incorrect module, React__default points to undefined.

### Desired behavior

Can run component testing

### Test code to reproduce

https://github.com/dualeoo/cypress-bug-report

### Cypress Version

12.6.0

### Node version

16.13.0

### Operating System

macOS 13.0.1

**Comment by lmiller1990** [comment]
I couldn't tell you the exact reason, but this line is the issue: https://github.com/dualeoo/cypress-bug-report/blob/master/webpack.config.ts#L52. I don't think this is a bug in Cypress per-se. 

Do you need that line of code in your `webpack.config`? If you remove it, everything works. I am also not sure how much performance benefit these are giving you - if you've got some benchmarks, I'd be interested in seeing them.

**Comment by dualeoo** [comment]
@lmiller1990 Thank you so much! It works like a charm. 

Seems like this is what happened previously:
- I told webpack to resolve files under 3 different modules: node_modules, src/js, and cypress

```
  resolve: {
    extensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],
    modules: ['node_modules', 'src/js', 'cypress'],
  }
```

- As a consequent, when webpack execute line 8 of `node_modules/cypress/react/dist/cypress-react.esm-bundler.js` (`import * as React from 'react';`), it would search for any module with name `react` in this order
  - node_modules/cypress/react/dist/node_modules
  - node_modules/cypress/react/dist/src/js
  - node_modules/cypress/react/dist/cypress
  - node_modules/cypress/react/node_modules
  - node_modules/cypress/react/src/js
  - node_modules/cypress/react/cypress
  - node_modules/cypress/node_modules
  - node_modules/cypress/src/js
  - node_modules/cypress/node_modules
  - node_modules/node_modules
  - node_modules/src/js
  - node_modules/cypress => bingo! webpack found that inside this folder, there is an exported module named `react` as indicated by line 94 of node_modules/cypress/package.json:

```
 "exports": {
...
    "./react": {
      "import": "./react/dist/cypress-react.esm-bundler.js",
      "require": "./react/dist/cypress-react.cjs.js",
      "types": "./react/dist/index.d.ts"
    },
```

As a result: 
- `node_modules/cypress/react/dist/cypress-react.esm-bundler.js:8` import itself!
- `React__default` is undefined and `React` points to `node_modules/cypress/react/dist/cypress-react.esm-bundler.js`

By removing the `module.resolve` line, 


It works stop searching for module inside `node_modules/cypress` and thus correct module is imported!
