### ISSUE TITLE
CT Blog Issue

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#25905]
## Description

As per [O6, KR1](https://docs.google.com/spreadsheets/d/1D0HBIfoP9yMtV7z0hlqSI-hDy8u_duAAzk40T0kDkXI/edit#gid=757833314), we'd like to write a blog post every sprint about Component Testing.

So far we've written about Next.js and TDD with React. The content is open ended - as long as it relates to CT in Cypress. It'd be great if you share your idea before writing it - just a basic outline, or a quick summary of the content and why it's useful.

## AC

- Write blog post in Google Doc
  - Review [Style Guide](https://docs.google.com/document/d/1pOZ0Ntm4b1Eev_iY5vLBPhOxx66Z8Njrvvg6WMCvWRI/edit#heading=h.ok2apo8hzldd) for guidance on tone, phrasing, and vocabulary
- Get at least 2 reviews
- Handoff to Jess Sweet

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25905?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
Possibly @jordanpowell88 writing about angular?

**Comment by jordanpowell88** [comment]
I have a few Angular blogs in the back of my head that I'd love to write whenever we're able to fit them into an upcoming sprint

**Comment by lmiller1990** [comment]
I think it's fine to write a blog post anytime, we can either publish multiple per sprint or save it for a rainy day :)

**Comment by marktnoonan** [comment]
Assigning @baus for clarity, writing abut what CT means for managers.

**Comment by marktnoonan** [comment]
@lmiller1990 was this completed or are we not doing the management blog post anymore?

**Comment by lmiller1990** [comment]
I think blog posts was mainly a q1 OKR - we can do said blog post, I'm not sure if @baus has bandwidth for this right now -- it's not in any of our upcoming sprints at this point. WDYT? I'm fine to close this and focus on q2 OKRs, but if @baus does decide he'd like to do this, we can schedule time.
