### ISSUE TITLE
Remove "New" badge in sidebar for Debug page

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25925]
### What would you like?

Remove the "New" badge shown in the sidebar for the Debug page (as well as the dot shown when the sidebar is collapsed).

_New Badge_
![image](https://user-images.githubusercontent.com/1702361/220763765-461d7d0d-613e-4647-ac92-d378321f9bfa.png)

_Dots shown when sidebar collapsed_
![image](https://user-images.githubusercontent.com/1702361/220764444-7ebb41d8-0e57-4d7e-ade5-ab8843daf49e.png)

### Why is this needed?

For a user that never plans to use Cypress Cloud, the "New" indication will remain until a hardcoded date of 2 months after the initial Debug page release has passed. This will be on March 31, 2023.  Since there is no other way to dismiss the notification, we will go ahead and sunset this early instead of doing additional work to provide additional ways to dismiss the notification. 

### Other

Also make sure to remove the no longer needed test in `isAllowedFeature`

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25925?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34

**Comment by lmiller1990** [comment]
Seems like a minor one, we could bundle w/ https://github.com/cypress-io/cypress/issues/25926 (one PR, one review).
