### ISSUE TITLE
Error npx cypress open

### ISSUE THREAD

**Issue by kyhamanaka** [cypress-io/cypress#25921]
### Current behavior

Erro ao digitar npx cypress open no meu projeto
```
[23308:0222/160030.291:ERROR:backend_impl.cc(2020)] Invalid file version or magic
[23308:0222/160118.680:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
````

### Test code to reproduce

Ao digitar o comando npx cypress open
```
23308:0222/160030.291:ERROR:backend_impl.cc(2020)] Invalid file version or magic
[23308:0222/160118.680:ERROR:network_service_instance_impl.cc(978)] Network service crashed, restarting service.
````
### Cypress Version

10.3.1

### Node version

19.7.0

### Operating System

windows

**Comment by nagash77** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by kyhamanaka** [comment]
All my projects were working and all of a sudden they all started with this error.
Anyway, I did a new test and managed to reproduce the error.
Thanks
[Versao.zip](https://github.com/cypress-io/cypress/files/10823805/Versao.zip)

**Comment by flotwig** [comment]
@kyhamanaka It sounds like your Cypress App is corrupted. Could you try following these steps to delete your local Cypress cache and re-install?

1. Run `cypress cache clear`
2. Run `cypress install`
3. Try running Cypress again.

**Comment by kyhamanaka** [comment]
showing message below


![image](https://user-images.githubusercontent.com/96090298/221622359-6d59d9a7-f342-4b61-b849-8b4e9a813bf1.png)

**Comment by flotwig** [comment]
@kyhamanaka try using `npx cypress cache clear` and `npx cypress install`, instead.

**Comment by kyhamanaka** [comment]
The error continues, I'm going to put two evidences where one is with the old version of my project and the other with the most recent version
- Recent version
![image](https://user-images.githubusercontent.com/96090298/221687668-7ab9bf98-b44b-43f4-87bd-4ea322dedf9b.png)

- Old version
![image](https://user-images.githubusercontent.com/96090298/221687810-26a760f1-6817-4802-b99e-f00a71d39752.png)

**Comment by flotwig** [comment]
@kyhamanaka this seems like it could be an upstream bug in Electron, I see some old reports of a similar issue on their repo: https://github.com/electron/electron/issues/31675

Can you try 2 things for me please?

1. Run `npx electron@latest` - you should see a little Electron window pop up, and it should not crash.
2. Run `npx electron@21.0.0` - you should see a little Electron window pop up, and it should not crash.

Both of these should show a screen similar to this: 

![Image](https://user-images.githubusercontent.com/1151760/221932513-c4b0c4ae-ebb2-4030-a056-8b3c9b7e76ac.png)

Let me know if you have success here.

E: Could possibly be happening if your local firewall doesn't allow listening on `localhost`, since we use an internal HTTP server for running Cypress.

**Comment by kyhamanaka** [comment]
**Same error follow the log:

If the problem is the firewall what do I need to request so that this error does not occur.**

PS C:\Users\kelly.hamanaka\Documents\Projetos\Telemed - QA> npx electron@latest


Electron 23.1.1 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:      
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
PS C:\Users\kelly.hamanaka\Documents\Projetos\Telemed - QA> npx electron@latest


Electron 23.1.1 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
PS C:\Users\kelly.hamanaka\Documents\Projetos\Telemed - QA> npx electron@21.0.0


Electron 21.0.0 - Build cross platform desktop apps with JavaScript, HTML, and CSS
A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -a, --abi             Print the Node ABI version.
PS C:\Users\kelly.hamanaka\Documents\Projetos\Telemed - QA> npx cypress open
No version of Cypress is installed in: C:\Users\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: C:\Users\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe

----------

Platform: win32-x64 (10.0.19042)
Cypress Version: 12.6.0
PS C:\Users\kelly.hamanaka\Documents\Projetos\Telemed - QA> npx cypress cache clear
PS C:\Users\kelly.hamanaka\Documents\Projetos\Telemed - QA> npx cypress install
Installing Cypress (version: 12.6.0)

✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation C:\Users\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0

You can now open Cypress by running: node_modules\.bin\cypress open

https://on.cypress.io/installing-cypress

PS C:\Users\kelly.hamanaka\Documents\Projetos\Telemed - QA> npx cypress open
It looks like this is your first time using Cypress: 12.6.0

✔  Verified Cypress! C:\Users\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress      

Opening Cypress...

**[8832:0228/164200.808:ERROR:network_service_instance_impl.cc(499)] Network service crashed, restarting service.
Error: ERR_FAILED (-2) loading 'http://localhost:52796/__launchpad/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
    at EventEmitter.emit (node:events:527:28) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'http://localhost:52796/__launchpad/index.html'**
}

**Comment by mjhenkes** [comment]
This might be a dumb question, but did you verify that cypress exists at this location?
"C:\Users\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe"

**Comment by kyhamanaka** [comment]
Yes, follows the evidence
![image](https://user-images.githubusercontent.com/96090298/222728880-d744d824-38ef-4a03-89d1-d09c7b09b8f1.png)

**Comment by mjhenkes** [comment]
I wonder if the language is tripping up where cypress is looking, `users` instead of `usuarios`

try setting the run binary env to: `CYPRESS_RUN_BINARY=C:\Usuários\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe`

https://docs.cypress.io/guides/references/advanced-installation#Run-binary

**Comment by kyhamanaka** [comment]
view the message below:

PS C:\Users\kelly.hamanaka\Documents\Projetos\Versao> npx CYPRESS_RUN_BINARY=C:\Usuários\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\kelly.hamanaka\Documents\Projetos\Versao\CYPRESS_RUN_BINARY=C:\Usuários\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\kelly.hamanaka\Documents\Projetos\Versao\CYPRESS_RUN_BINARY=C:\Usuários\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe\package.json'
npm ERR! enoent This is related to npm not being able to find a file.        
npm ERR! enoent
[2023-03-06T12_53_37_696Z-debug-0.log](https://github.com/cypress-io/cypress/files/10898442/2023-03-06T12_53_37_696Z-debug-0.log)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kelly.hamanaka\AppData\Local\npm-cache\_logs\2023-03-06T12_53_37_696Z-debug-0.log

**Comment by kyhamanaka** [comment]
This is the log correct:

PS C:\Users\kelly.hamanaka\Documents\Projetos\Versao> npx CYPRESS_RUN_BINARY="C:\Usuários\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe"
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\kelly.hamanaka\Documents\Projetos\Versao\CYPRESS_RUN_BINARY=C:\Usuários\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\kelly.hamanaka\Documents\Projetos\Versao\CYPRESS_RUN_BINARY=C:\Usuários\kelly.hamanaka\AppData\Local\Cypress\Cache\12.6.0\Cypress\Cypress.exe\package.json'
npm ERR! enoent This is related to npm not being able to find a file.        
npm ERR! enoent 
[2023-03-06T14_00_04_502Z-debug-0.log](https://github.com/cypress-io/cypress/files/10898966/2023-03-06T14_00_04_502Z-debug-0.log)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kelly.hamanaka\AppData\Local\npm-cache\_logs\2023-03-06T14_00_04_502Z-debug-0.log

**Comment by kyhamanaka** [comment]
the error no longer occurs

**Comment by kyhamanaka** [comment]
Thank you for your help

**Comment by totovelo10** [comment]
\node_modules\.bin\cypress.cmd install

npx cypress open -b electron

**Comment by bravewasp** [comment]
@kyhamanaka and everyone else coming here from google.

We had a similar issue, cypress simply crashed on startup with a similar message. It seems like cypress has problems when the computer is set to enery saving mode (Windows 11). 

Perhaps the startup takes to long an cypress decides to kill the electron process.

**Comment by afahmiparidin** [comment]
> @kyhamanaka try using `npx cypress cache clear` and `npx cypress install`, instead.

This works for me

**Comment by t-ashraf** [comment]
This issue keeps happening again and again and again. Cypress works and then fails again with the same error next time I start it.
