### ISSUE TITLE
"New" icon badge should disappear after visiting page once

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#25923]
## Description

Icon badge icon should disappear after visiting page once.

![image](https://user-images.githubusercontent.com/19196536/220747093-bfedebc9-c092-4b0c-9364-83e58f137343.png)

## Acceptance Criteria

Once I click the Debug page icon once, or visit there, it should go away. This is global - not per-project.

**Comment by pstakoun** [comment]
This issue conflicts with work in-flight cc @warrensplayer

**Comment by pstakoun** [comment]
Related issue that will address this: https://github.com/cypress-io/cypress/issues/25739

**Comment by pstakoun** [comment]
https://github.com/cypress-io/cypress/issues/25925
