### ISSUE TITLE
Remove hover CTAs on Specs List for Cloud columns

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#25926]
#### Current behavior

When not connected to the cloud, the Specs list page will show links when hovering over the empty states in the "Latest Runs" and the "Average Duration" columns (the button that says "connect").

![Screenshot 2023-02-22 at 4.59.02 PM.png](https://images.zenhubusercontent.com/5e25f9721016beda9c509196/96d70324-e0af-4820-a7ad-7c3193234374)![Screenshot 2023-02-22 at 4.58.45 PM.png](https://images.zenhubusercontent.com/5e25f9721016beda9c509196/84798985-52de-454c-aa03-6dcf8ceae116)

#### Desired behavior

These CTA links have not been converting, so they should be removed.   Hovering over the empty states of the "Latest Runs" and the "Average Duration" columns when not connected to the cloud should no longer show the links. 

Note: Clean up any unused components after removing these from the Specs list .

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25926?planning-poker) with Zenhub @astone123 @lmiller1990 @marktnoonan @mike-plummer @ZachJW34

**Comment by lmiller1990** [comment]
Could combo w/ https://github.com/cypress-io/cypress/issues/25925 (one PR, get it all done in one shot).

**Comment by mike-plummer** [comment]
@warrensplayer I assume we want to remove the "question mark" icon when there isn't a corresponding tooltip to display, but retain when there is?
