### ISSUE TITLE
Make browser selectable for 'cypress open' 

### ISSUE THREAD

**Issue by meeroslav** [cypress-io/cypress#2594]
### Current behavior:

User cannot change browser when running `cypress open`. If Chrome exists, cypress app will always run tests in Chrome.

### Desired behavior:

There should be a `browser` param for configuration or CLI flag to choose different browser, just like it's possible with `cypress run`.

### Versions

Chrome/Chromium/Canary/Safari, 
Linux Ubuntu/OSX, 
Cypress v3.0.3

**Comment by chrisbreiding** [comment]
You can choose the browser in the top right corner of the Cypress app. It will list any supported browsers we find on your system.

![screen shot 2018-10-11 at 11 40 42 am](https://user-images.githubusercontent.com/1157043/46816287-a38cfc80-cd4a-11e8-9501-39fa8bac2526.png)

**Comment by meeroslav** [comment]
It could be an issue in Ubuntu only.
In my cypress app I see the following browsers:

![screenshot from 2018-11-21 11-55-04](https://user-images.githubusercontent.com/881612/48836928-586ffb80-ed84-11e8-9e57-d13c9351219f.png)


On my system I have installed following browsers:
- Firefox v63
- Chrome v70
- Chromium v70

While Firefox is unsupported, why can't I see Chromium?

**Comment by anuragipankaj** [comment]
In my case there are no options visible :
![image](https://user-images.githubusercontent.com/39908261/48939082-20f68000-ef39-11e8-8afe-fd6e12f9a045.png)
