### ISSUE TITLE
Angular CT does not mount component within div[data-cy-root]'s original html element hierarchy  

### ISSUE THREAD

**Issue by mv740** [cypress-io/cypress#25956]
### Current behavior

Angular components are correctly mounted into the div[data-cy-root] root element but they aren't respecting the div's original position. 

component-index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>Components App</title>
  </head>
  <body>
    <div id="outside">
      <div id="inside">
        <div data-cy-root></div>
      </div>
    </div>
  </body>
</html>

```

![image](https://user-images.githubusercontent.com/1993293/221420560-14bb8b3b-f6a8-4959-bc47-59f28889ebbc.png)

the issue is caused by the [following line of code ](https://github.com/cypress-io/cypress/blob/develop/npm/angular/src/mount.ts#L182)

```ts
       document.body.appendChild(rootElement)
```

### Desired behavior

The components should be mounted inside of `div data-cy-root></div>` and still keep it's original position. 

```html
<div class="outside">
      <div id="inside">
          <div data-cy-root="" id="root0" _nghost-a-c12="" ng-version="14.2.12"><div _ngcontent-a-c12="">yep, it works</div><button _ngcontent-a-c12="" data-cy="get-comp-name">Get component name</button></div>
      </div>
</div>
```

###  possible solution 

update the [following method](https://github.com/cypress-io/cypress/blob/develop/npm/angular/src/mount.ts#L176)

```ts
override insertRootElement (rootElId: string) {
    this.removeAllRootElements()

    const rootElement = getContainerEl()
    const parentElement = rootElement.parentElement

    rootElement.setAttribute('id', rootElId)

    if(parentElement && parentElement?.tagName !== 'HTML') {
        parentElement.appendChild(rootElement)
    } else {
        document.body.appendChild(rootElement) 
   }
    
  }
```

### Test code to reproduce

Any angular app with CT setup. You just need to edit the component-index.html file. 

`<div data-cy-root></div>` add the root div inside another div. 

```html
...
  <body>
      <div id="container">
        <div data-cy-root></div>
      </div>
  </body>
```

### Cypress Version

12.7.0

### Node version

v18.12.1

### Operating System

ubuntu 22.04

**Comment by mv740** [comment]
is there a specific command to scaffold the angular ct Project (13|14|15)? I think there is supposed to be a way to automatically copy the fixtures folder into the projects.

if someone could point me in the right direction, I will create the MR for my issue.

**Comment by lmiller1990** [comment]
Saw https://github.com/cypress-io/cypress/pull/25807 was in 12.7. It touches some of the same code. Was this a regression introduced in 12.7 or a pre-existing bug?

To scaffold Cypress CT, you just run `npx cypress open` in your Angular project and hit Component Testing - it should do the rest for you. There's no CLI scaffolding at this point.

If you'd like to make a PR fixing the bug you've found, that'd be great! Something like:

1. clone this monorepo
2. yarn (takes a while...)
3. You could use [this test](https://github.com/cypress-io/cypress/blob/0cdd8d195f9660f1c6bb357b5fbe1ec32b16c54b/system-tests/test/component_testing_spec.ts#L139) and do `systemTests.it.only` to run just that one. `cd system-tests && yarn test component_testing` to run it.
4. It points to [this project](https://github.com/cypress-io/cypress/blob/0cdd8d195f9660f1c6bb357b5fbe1ec32b16c54b/system-tests/projects/angular-custom-root/cypress/support/component-index.html). You could change that to match your reproduction.
5. Update `npm/angular` to fix it. I think you can do `yarn tsc -w` in there to auto recompile the Angular `mount` function.

Let me know if you need any more pointers.
