### ISSUE TITLE
Strip card test case 

### ISSUE THREAD

**Issue by rajalatejashwini** [cypress-io/cypress#25961]
### Current behavior

I have written the test case for a stripe card it's working fine in chrome but when i try to run it on WebKit browser it throws an error 
![IMG_20230224_160121](https://user-images.githubusercontent.com/60687099/221496247-4fa3044b-401f-449d-99ea-2b75fdc1470e.jpg)

### Test code to reproduce

Unfortunately I can't provide the test case repo 

### Cypress Version

12.5.1

### Node version

18.13.0

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @rajalatejashwini unfortunately without a reproduction we will have to close this issue.  If you are able to share it in the future please do and we can reopen.
