### ISSUE TITLE
Cypress module API should return dashboard URL of recorded run

### ISSUE THREAD

**Issue by shcallaway** [cypress-io/cypress#2596]
### Current behavior:

I'm running Cypress programmatically with the module API. I want to send a Slack message with the dashboard URL for failed runs. Currently, the dashboard URL of the recorded run is printed to stdout but not included in the return value of `cypress.run`.

### Desired behavior:

`cypress.run` return value should include a key called `dashboardUrl` with the a value like `https://dashboard.cypress.io/#/projects/asdf/runs/123`.

### Versions

Cypress 3.0.2

**Comment by brian-mann** [comment]
Agreed - it should be yielded to you in the `results` object that Cypress resolves with for sure.

**Comment by brian-mann** [comment]
@chrisbreiding and @lilaconlee this one is pretty easy - as `runUrl` is already received in `run.coffee` and would be available to be set in the final results object. Already tests around this, so likely just needs some snapshot updates.

Ya'll should take a crack at it.
