### ISSUE TITLE
Dependencies are not detected during onboarding when using Yarn 3

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#25960]
Related: https://github.com/cypress-io/cypress/issues/22747 -> https://github.com/cypress-io/cypress/issues/22747#issuecomment-1440647617

Repro: 
[yarn3.zip](https://github.com/cypress-io/cypress/files/10836696/yarn3.zip)

I have Vue and Vite installed (specified via `package.json`) but no `node_modules` since I'm using Yarn 3 PnP. The dependences are not detected.

You can skip them and continue, but it's not a great experience.

![image](https://user-images.githubusercontent.com/19196536/221489719-5c79b80c-dcab-4545-9409-c339d91decf3.png)

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25960?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @jordanpowell88

**Comment by astone123** [comment]
Should be able to use the [PnP API](https://yarnpkg.com/advanced/pnpapi) for this

**Comment by mike-plummer** [comment]
@astone123 It looks like the `resolve-package-path` package we're using for dependency resolution [already tries to use `pnpapi` if it's available](https://github.com/stefanpenner/resolve-package-path/blob/0e5457e6cb730600e548c27c6d772a77be2f7cbf/src/index.ts#L117) - maybe there's some additional config we need to enable to make sure the pnp system is enabled?

**Comment by lmiller1990** [comment]
It looks like `pnpapi` isn't found - it hits this line: https://github.com/stefanpenner/resolve-package-path/blob/b50d56f270ee3625cf7d96420f630b23510fefc8/src/index.ts#L30

According to [yarn docs](https://classic.yarnpkg.com/lang/en/docs/pnp/troubleshooting/)

> This error message is not generated by Plug’n’Play. Ever. If you get it, it very likely means that your application is not running with the PnP resolver, meaning that your require calls won’t be able to load files from your dependencies (since the node_modules needed for the regular Node resolution won’t have been generated). Make sure to either run your code using NODE_OPTIONS="--require /path/to/.pnp.js" or to call it using yarn node which does the right thing transparently (whether you’re using PnP or not).

I tried adding NODE_OPTIONS

```sh
 NODE_OPTIONS=-"-require=../../dump/y3/.pnp.cjs"  yarn cypress:open --project ~/code/dump/y3
```

Same thing:


```
error An unexpected error occurred: "Cannot find module 'pnpapi'
Require stack:
- /Users/lachlanmiller/.cache/node/corepack/yarn/1.22.19/lib/cli.js
- /Users/lachlanmiller/.cache/node/corepack/yarn/1.22.19/bin/yarn.js
Require stack:
- /Users/lachlanmiller/.cache/node/corepack/yarn/1.22.19/lib/cli.js
- /Users/lachlanmiller/.cache/node/corepack/yarn/1.22.19/bin/yarn.js".
info If you think this is a bug, please open a bug report with the information provided in "/Users/lachlanmiller/code/work/cypress2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation
```

Not sure what's next - it looks like when Cypress runs, the electron process needs to be aware that

1. user is on yarn 3
2. where to find `.pnp.cjs`
3. where to look for node_modules (usually in `<HOME>.yarn/berry/cache` - not sure if this info is available from `.pnp.cjs` or elsewhere

**Comment by lmiller1990** [comment]
I found out `pnpapi` is available if I do `yarn node`. Read that here: https://yarnpkg.com/features/pnp#initializing-pnp

Might need a special check for PnP when we kick off Cypress.
