### ISSUE TITLE
Pass framework and bundler types when recording CT runs to the Cloud

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#25976]
### What would you like?

Currently there is no conclusive way to determine which Framework or bundler is being used when recording runs to the Cloud. This should be set by the app and captured by the cloud with the run data.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25976?planning-poker) with Zenhub @jordanpowell88 @astone123 @mike-plummer @marktnoonan @lmiller1990 @warrensplayer

**Comment by lmiller1990** [comment]
Note: we may need a security review for capturing additional data.

This will require 2 PRs - one App, one Cloud.

**Comment by astone123** [comment]
We aren't going to move forward with these changes. The framework and bundler info is already stored in the Cloud database with the Cypress configuration, so instead of adding fields, we'll do the work on the back end to make this configuration data query-able.
