### ISSUE TITLE
cy.session() along with cacheAcrossSpecs enabled does not preserve cookies throughout the tests

### ISSUE THREAD

**Issue by VishwaramH** [cypress-io/cypress#25973]
### Current behavior

I am trying to preserve cookies in the application throughout all the test cases. In older versions (8.5.0), I used to do like this
Cypress.Cookies.defaults({
  preserve: ['session_id','cookie1','cookie2']
}); 

I started exploring the latest versions and checked the migration guide for the same. In the current version that I'm using (**12.5.1**), it's mentioned in the changelog that the **Cypress.Cookies.defaults** and **preserve** are all removed. Instead, it's mentioned to use **cy.session()** as an alternative like the following:
![image](https://user-images.githubusercontent.com/55096085/221857318-0eae5115-5f69-4d9a-81d8-aa6c3a34b5c5.png)

Here, it's mentioned that **cacheAcrossSpecs: true** is used to preserve the cookies.
Link to migration guide: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-12-0

And this is how I am doing it in my code
```js
Cypress.Commands.add('EnterTheApp', () => {
  const login = () => {
  
    cy.visit(<app_url>);
    cy.wait(7 * 1000);
  
    cy.get('#loginbtn').click();
    cy.wait(2 * 1000);
  
  
    cy.get('#emailid').clear().type(<username>);
    cy.get('#password').clear().type(<password>);
  
    cy.get('#submit').click();
  };
  
  
  cy.session(
      <unique_id>,
      () => {
        return login();
      },
      {
        validate() {
          cy.getCookies().should('have.length.at.least', 3);
        },
        cacheAcrossSpecs: true,
      }
    );
});
```

In the above piece of code, **login** is the function which logins to the application. I use the **cy.EnterTheApp()** command as common one in all my spec suites (.spec.js files). username and password are the Amazon Cognito credentials.
The above code is not working as expected and it's throwing 401 error code when it moves from one test case to another.

### Desired behavior

The cookies need to be preserved throughout all the test cases of the end to end testing.
Also, there should be a way to mention only few cookies that needs to be preserved.

### Test code to reproduce

```js
Cypress.Commands.add('EnterTheApp', () => {
  const login = () => {
  
    cy.visit(<app_url>);
    cy.wait(7 * 1000);
  
    cy.get('#loginbtn').click();
    cy.wait(2 * 1000);
  
  
    cy.get('#emailid').clear().type(<username>);
    cy.get('#password').clear().type(<password>);
  
    cy.get('#submit').click();
  };
  
  
  cy.session(
      <unique_id>,
      () => {
        return login();
      },
      {
        validate() {
          cy.getCookies().should('have.length.at.least', 3);
        },
        cacheAcrossSpecs: true,
      }
    );
});
```

### Cypress Version

12.5.1

### Node version

v16.17.0

### Operating System

Windows 10 64-bit OS

**Comment by mjhenkes** [comment]
I think the issue may be that you're assigning a unique id to the session when you should think of it more like a key. To restore the session you need to provide the same key.

In this example here: https://docs.cypress.io/api/commands/session#Switching-sessions-inside-tests we show switching between sessions by using the username as a key.

Let me know if i'm misunderstanding your example, but we should be able to get something worked out here.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open comment on this issue with a reproducible example, and we can look into it further. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by imaad57** [comment]
Hi, I am facing the same issue. Have you already got a solution to it? It would be a great help

**Comment by nagash77** [comment]
@imaad57 , we do not currently have a reproducible example as mentioned in the last comment before yours.  If you have one to share please open a new issue and we will be happy to investigate.

**Comment by theTestingApproach** [comment]
I tried the cacheAcrossSpecs: true and facing same issue..Has anyone been able to find an alternative please..Thanks
