### ISSUE TITLE
`cy.stub` cannot be called from two tests

### ISSUE THREAD

**Issue by basarat** [cypress-io/cypress#2597]
From the docs : https://docs.cypress.io/api/commands/stub.html#Restores

> cy.stub() creates stubs in a sandbox, so all stubs created are automatically reset/restored between tests without you having to explicitly reset/restore them.

However it doesn't work. 

### Steps to reproduce:

File `example.ts` containing a function we want to stub: 

```ts
export function bar(_: string) {
  // Nothing to do
}
```

File `foo.ts` that uses the example function: 

```ts
import { bar } from './example';

export function foo(something: string) {
  bar(something);
}
```

Tests: Want to ensure that whatever gets passed to `foo` is successfully propogated to `bar`: 

```ts
/// <reference types="cypress"/>

import { foo } from '../../../src/app/foo';
import * as example from '../../../src/app/example';

describe('should work', () => {
  it('should stub it once', () => {
    cy.stub(example);
    foo('first');
    expect(example.bar).to.have.been.calledWith('first');
  });

  it('should stub it again', () => {
    cy.stub(example);
    foo('second');
    expect(example.bar).to.have.been.calledWith('second');
  });
});
```

### Current behavior:

First test succeeds, second test errors with `TypeError: Attempted to wrap bar which is already wrapped`. Here is a screenshot that shows it as well: 

![image](https://user-images.githubusercontent.com/874898/46839186-6424e580-ce08-11e8-8938-9361e757ea1f.png)

### Desired behavior

Second test should succeed as well.

### Versions

* `"cypress": "3.1.0"`

Tested on multiple computers.

**Comment by basarat** [comment]
# Workaround 

* Don't use `cy.stub` on a module (`cy.stub(example)`), which calls `cy.wrap` internally.
* Instead, use the value from `cy.stub` as variable to manually assign to what you want to mock. 

Example, the following is the workaround for the provided test :rose: : 

```ts
import { foo } from '../../../src/app/foo';
import * as example from '../../../src/app/example';

describe('should work', () => {
  it('should stub it once', () => {
    (example as any).bar = cy.stub();
    foo('first');
    expect(example.bar).to.have.been.calledWith('first');
  });

  it('should stub it again', () => {
    (example as any).bar = cy.stub();
    foo('second');
    expect(example.bar).to.have.been.calledWith('second');
  });
});
```

**Comment by chrisbreiding** [comment]
The usage posted in your original post is not really supported. [`cy.stub()` takes an object and a method](https://docs.cypress.io/api/commands/stub.html#Syntax) and passing only the object to stub all methods is not recommended. Your 'workaround' could use the following instead:

```javascript
cy.stub(example, 'bar')
```
