### ISSUE TITLE
cy.xpath is not a function

### ISSUE THREAD

**Issue by bachhavdipak** [cypress-io/cypress#25983]
### Current behavior

I am trying to use xpath to locate my elements using cypress but while doing that I am getting error. I already done required changes based on the documents https://www.npmjs.com/package/@cypress/xpath

I am using cucumber along with cypress 

### Desired behavior

![image](https://user-images.githubusercontent.com/77110618/222157922-cad71999-556c-4a9f-88a4-14f56dd73ed0.png)

### Test code to reproduce

https://github.com/bachhavdipak/CypressTesting

```
import { When, Then } from "@badeball/cypress-cucumber-preprocessor";
import '@shelex/cypress-allure-plugin';

When("I visit duckduckgo.com", () => {
  cy.visit("https://www.duckduckgo.com");
});

Then("I should see a search bar", () => {
  cy.get("input").should(
    "have.attr",
    "placeholder",
    "Search the web without being tracked"
  );
  cy.xpath('//body')
});
```

### Cypress Version

12.0.2

### Node version

v18.13.0

### Operating System

Windows 10

**Comment by mike-plummer** [comment]
Hi @bachhavdipak , sorry to hear you're having issues. In this case I believe it's a simple misconfiguration - in your `cypress.config.js` file you have specified `supportFile: false` which means the content in `cypress/support/e2e.js` is not being executed, thus the `@cypress/xpath` plugin isn't being loaded. Removing this line allows your test to work as expected

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by shubham-maersk** [comment]
> Hi @bachhavdipak , sorry to hear you're having issues. In this case I believe it's a simple misconfiguration - in your `cypress.config.js` file you have specified `supportFile: false` which means the content in `cypress/support/e2e.js` is not being executed, thus the `@cypress/xpath` plugin isn't being loaded. Removing this line allows your test to work as expected

@mike-plummer you made my day easy , thanks for helping millions of people .
