### ISSUE TITLE
Get the error cy.origin() requires the first argument to be a different domain than top.You passed https://domain.eu.auth0.com/ to the origin command, while top is at https://domain.eu.auth0.com

### ISSUE THREAD

**Issue by beccavittoria** [cypress-io/cypress#25982]
### Current behavior

When I run a test sometimes I get this error:
![image](https://user-images.githubusercontent.com/87660243/221227573-516fb741-98b6-4a7d-bebe-d85abce835bf.png)

Both with the same domain.

But after that, if I run the same test again without changing anything in the code this problem doesn't happen anymore.

### Desired behavior

Redirect corretly from auth login page to the domain

### Test code to reproduce
```js
Cypress.Commands.add('loginCy', (user, pass) => {
    
  const args = { user, pass }
        
  cy.origin('https://LoginDomain.auth0.com/', { args }, ({ user, pass }) => { })

  cy.request({
      method: "POST",
      url: Cypress.env('authenticationAPI'), 
     
      headers : {
        "x-api-key" :   Cypress.env('x-api-key')
      },
      
       body:{
          "username": user,
          "password": pass
        },
      
    }).then(res => {
      expect(res.status).to.eq(200)
      window.localStorage.setItem("token",JSON.stringify(res.body))
      cy.visit('domain.net/login?token='+ res.body.token)  
      
    })        
    cy.visit("https://domain.net");
  },)



it('Click Menu Camera', function() {
  cy.loginCy(user, pass)

it('Click Menu Camera', function() {

  cy.loginCy(user, pass)

)}
```
### Cypress Version

11.2.0

### Node version

v18.14.0

### Operating System

Windows 11 Home

### Other

The redirection happens as soon as I access the page, if I type de url domain.net automactly redirects to LoginaAuthDomain.com

**Comment by mjhenkes** [comment]
@beccavittoria, I'm not sure i totally understand your reproduction code but based on the description it sounds like you may have a similar issue to this https://github.com/cypress-io/cypress/issues/25373#issuecomment-1450755381

Check out my comment over on that issue and see if it helps.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open comment on this issue with a reproducible example, and we can look into it further. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by iomedico-beyer** [comment]
I am sorry for reopening this. My fault. I used the same top-level domain for both request and auth, so the error message seems correct in my case.
