### ISSUE TITLE
parseSpecialCharSequences: false is not working

### ISSUE THREAD

**Issue by skumarigit** [cypress-io/cypress#25990]
I currently have a function `function() {return "test" }` that types in a string with the special character and runnnig the test without setting 
`parseSpecialCharSequences` option to false cypress throws an error `CypressError: Special character sequence: '{return "test" }' is not recognized. Available sequences are: {selectall}, {del}, {backspace}, {esc}, {{}, {enter}, {leftarrow}, {uparrow}, {rightarrow}, {downarrow}, {alt}, {option}, {ctrl}, {control}, {meta}, {command}, {cmd}, {shift}` and it gives the suggestion to pass the option parseSpecialCharSequences option to false. 

And when I set the parseSpecialCharSequences option to false then also it throws the same error.

Could you please suggest the alternative way to type a function in a text field

**Comment by mike-plummer** [comment]
Hi @skumarigit , sorry to hear you're having trouble. I suspect you may not be applying the `parseSpecialChartSequences` option correctly - I set up a local example and am able to use `cy.type` to input your provided function text example like so:

```js
cy.get('input')
  .type('function() {return "test" }', { parseSpecialCharSequences: false })
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
