### ISSUE TITLE
Cookies not getting cleared

### ISSUE THREAD

**Issue by nemonemi** [cypress-io/cypress#25999]
### Current behavior

I am using `cy.setCookie` to set a cookie in a test. Until recently, as defined in the documentation, cookies were being cleared after each test, however, that is no longer the case.

I have tried removing it manually, but it doesn't work. `clearCookie` and `clearCookies`.

### Desired behavior

The cookies should be removed automatically, and also by manually invoking those methods.

### Test code to reproduce

it('test cookie setting', () => {
  cy.setCookie('some-cookie', 'cookie-value');
})

it('assert that cookie is not here', () => {
  cy.getCookie('some-cookie').should('be.null')
})

### Cypress Version

12.2.0

### Node version

v16.14.0

### Operating System

Ubuntu

### Debug Logs

```shell
cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬──────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │       pids       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼──────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │     '270939'     │     0      │       0        │  345.39  │    345.39    │   345.39    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      2       │ '270942, 270943' │     0      │       0        │  99.22   │    99.22     │    99.22    │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '271090, 271091' │     0      │       0        │   3.84   │     3.84     │    3.84     │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      5       │       '-'        │     0      │       0        │  448.46  │    448.46    │   448.46    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴──────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
  cypress:launcher:linux Could not extract version from stdout using regex: { stdout: 'Mozilla Firefox 110.0.1', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m } +0ms
```

### Other

I believe this is a regression issue.

**Comment by mike-plummer** [comment]
Hi @nemonemi , sorry to hear you're having issues.

I set up a very basic test which works as expected in Firefox v110, so there must be some other configuration or behavior that we need to account for.

```js
describe('cookie clearing', () => {
  beforeEach(() => {
    cy.visit('https://example.cypress.io')
  })

  it('should set and maintain cookie within test', () => {
    cy.getCookie('some-cookie').should('be.null')
    cy.setCookie('some-cookie', 'cookie-value');
    cy.getCookie('some-cookie').should('not.be.null')
  })

  it('cookie from other test should not exist here', () => {
    // assumes tests are run in order
    cy.getCookie('some-cookie').should('be.null')
  })

  it('should be able to clear cookie within test', () => {
    cy.setCookie('some-cookie', 'cookie-value');
    cy.getCookie('some-cookie').should('not.be.null')
    cy.clearCookie('some-cookie');
    cy.getCookie('some-cookie').should('be.null')
  })
})
```

- The test example above is using Cypress v12.7.0 - can you check whether your test fails if you upgrade to the latest version?
- Can you confirm that you haven't disabled [Test Isolation](https://docs.cypress.io/guides/core-concepts/test-isolation) in your test suite? if `testIsolation` is disabled then cookies will not be reset between tests
- There were changes in Cypress v12 around the domain used for `cy.getCookie` and `cy.clearCookie` - is it possible your test could be impacted by no longer using `superdomain`? See the Breaking Changes section of the [Changelog](https://docs.cypress.io/guides/references/changelog#12-0-0)

**Comment by nemonemi** [comment]
Hi, @mike-plummer.
I have simulated the same setup and can confirm your assertions as well, however, the fact is still that in the browser the cookie remains, and I would expect that if it was added to the `document.cookies` to also get removed from there as well.

```ts
  it('sets the cookie', function () {
    cy.setCookie('my-cookie', 'some-value');
    cy.getCookie('my-cookie').should('not.be.null');
  });

  it('should be null', () => {
    cy.getCookie('my-cookie').should('be.null');
  });
```

**Comment by mike-plummer** [comment]
@nemonemi In order to identify what is causing the cookies to not clear as expected I'll need some more information on your setup, evidently there's something unique in your project or use case that differs from the base example. Can you answer the questions I posed in my [previous comment](https://github.com/cypress-io/cypress/issues/25999#issuecomment-1452271237)?

**Comment by nemonemi** [comment]
Sure thing.
This is a part of the NX project. I have updated my Sypress from 12.2.0 to 12.7.0 and there was no improvement, but it could be that the case is the test isolation was turned on during the NX framework automation. I'll check it out.

**Comment by nemonemi** [comment]
I can confirm that `testIsolation` was the culprit. It was added during a framework update. Turning it back on, logically, resolved the issue. Thanks @mike-plummer
