### ISSUE TITLE
Vue slots seems to not be working

### ISSUE THREAD

**Issue by Ericlm** [cypress-io/cypress#26006]
### Current behavior

I'm trying to test a Vue component using a default slot, and I can't make it render its content when testing. I got my `CustomButton.vue` like so:
``` vue
<template>
  <div>
    <div class="content">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
defineEmits<(e: 'click') => void>()
</script>
```

And then a `CustomButton.cy.ts` like this one:
``` ts
import CustomButton from '../CustomButton.vue'

describe('<CustomButton />', () => {
  it('renders', () => {
    cy.mount(CustomButton, {
      slots: {
        default: 'Hello there!',
      },
    })
    cy.get('div.content').should('have.text', 'Hello there!')
  })
})
```
<img width="711" alt="Capture d’écran 2023-03-03 à 09 32 05" src="https://user-images.githubusercontent.com/19361503/222671054-0b37597e-d71b-4b66-8352-d1cdf9a8c65f.png">

It is identical to the [example in the docs](https://docs.cypress.io/guides/component-testing/vue/examples#Default-Slot), but it doesn't seems to work. When launching Component testing, the slot is empty, and so the `should` command fails.
I also tried what is suggested in [this issue](https://github.com/cypress-io/cypress/issues/18219), with the callback syntax (`default: () => 'Hello there!',`), but it didn't change anything.

### Desired behavior

Cypress should render the slot inside the component, and the test should be passing.

### Test code to reproduce

Trying the [Vue examples](https://docs.cypress.io/guides/component-testing/vue/examples#Default-Slot) from the docs with a default slot.

### Cypress Version

12.7.0

### Node version

18.14.0

### Operating System

macOS 13.2.1 (22D68)

**Comment by mike-plummer** [comment]
Hi @Ericlm , I'm sorry you're having issues with your Vue test. I just tried your code in a brand new Vue + Vite project (`vue@3.2.45`, `vite@4.1.0`) and it worked perfectly without any adjustments, so this might be a version and/or bundler issue. Can you share what version of Vue and what bundler you're using?

**Comment by Ericlm** [comment]
I'm using `vue@3.2.47` and `vite@4.1.4` ; I will try to downgrade to the version you use to check if it still not working.

**Comment by Ericlm** [comment]
Alright, I believe I found it out @mike-plummer. In `component.ts`, I override the `mount` command like the following : 
```ts
Cypress.Commands.add('mount', (component) => {
  const store = createPinia()
  return mount(component, {
    global: {
      plugins: [fluent, router, { install: (app): App => app.use(store) }],
    },
  })
})
```
I do that to add a translation, routing, and store modules, and I guess it overrides the "local" config passed to the `CustomButton`. I will try to find a workaround to set these global plugins 👨‍💻

**Comment by Ericlm** [comment]
### For people who would have similar issue:
To keep the global plugins while enabling local config for components, do the following in `component.ts`:
```ts
// Customize the mount command type
interface Chainable {
    mount(component: any, options?: Record<string, any>): Chainable<any>
}

// Customize the mount command
Cypress.Commands.add('mount', (component, options = {}) => {
  const augmentedOptions = {
    ...options,
    global: {
      plugins: [
        router,
        fluent,
        { install: (app: App): App => app.use(createPinia()) },
      ],
    },
  }
  return mount(component, augmentedOptions)
})
```

**Comment by mike-plummer** [comment]
@Ericlm Glad you found a fix, and thanks for sharing your findings with the community!
