### ISSUE TITLE
Missing type=module in Cypress script tag makes component tests hang

### ISSUE THREAD

**Issue by bnheise** [cypress-io/cypress#26013]
### Current behavior

No component tests execute -- they just hang because of this error:
<img width="563" alt="スクリーンショット 2023-03-04 12 14 34" src="https://user-images.githubusercontent.com/92563897/222873102-c332a274-b788-4c37-aa00-35a9a10a63ed.png">

This is caused by the following line of code in the html file:
<img width="563" alt="スクリーンショット 2023-03-04 12 15 24" src="https://user-images.githubusercontent.com/92563897/222873128-dff0a319-3f52-49ba-a8a0-0fbf811380dd.png">

The type should be "module" but it's not set so it throws this error.

### Desired behavior

I want my tests to run, so please add "type=module" to the script tag.

### Test code to reproduce

This happens with any component test. It's not related to the tests at all, it's the script tag.

### Cypress Version

12.5.1

### Node version

v18.14.2

### Operating System

macOS ventura

**Comment by mike-plummer** [comment]
Hi @bnheise , sorry to hear you're having issues. Can you share more information about your Component Testing setup (framework, bundler, package manager, typescript yes/no, ejs/mjs/etc use)? I'm able to create new Component Testing projects using a variety of frameworks and webpack/vite, so there must be something unique about your setup that is generating a `main.js` bundle improperly. A reproduction case would help us track down the issue and identify a fix much faster

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
