### ISSUE TITLE
Unable to configure Visual regression test scripts using typescript

### ISSUE THREAD

**Issue by Balu14** [cypress-io/cypress#26019]
### Current behavior

No proper document available 

### Desired behavior

Except the document

### Test code to reproduce

https://github.com/meinaart/cypress-plugin-snapshots

Followed all these steps for type script but no luck.
I am using Cypress 12 and above

### Cypress Version

12.2.2

### Node version

9.4.1

### Operating System

Windows

### Debug Logs

```shell
Property 'toMatchImageSnapshot' does not exist on type 'Chainable<JQuery<HTMLElement>>'.ts(2339)
```

**Comment by nagash77** [comment]
Hi @Balu14 that is not a repo maintained by Cypress.  You will need to open an issue that that repo owner.
