### ISSUE TITLE
Issues with restoring sessions

### ISSUE THREAD

**Issue by wongk** [cypress-io/cypress#26028]
### Current behavior

Cypress sometimes fails to restore the session properly between tests. The Cypress log shows that it thinks the session was restored, but in fact, the app under test is displaying the login page.

This had been working well for us but has started to become a problem recently. We use Auth0 for authentication and our full test suite uses a handful of different users. Within our signout function used in the test suite, the user will be signed out of the app, and we call

`cy.wrap(Cypress.session.clearAllSavedSessions());`, followed by
`cy.visit("/logout");`

To ensure Cypress does not try to reuse a signed-out session.

### Test code to reproduce

Here is our login command:

```js
Cypress.Commands.add("login", (username: string, password: string) => {
  const log = Cypress.log({
    displayName: "AUTH0 LOGIN",
    message: [`🔐 Authenticating | ${username}`],
    autoEnd: false,
  });
  log.snapshot("before");

  const args = { username, password };
  cy.session(
    args,
    () => {
      cy.visit("/");

      const auth0Domain = Cypress.env("AUTH0_DOMAIN");
      const isDifferentOrigin = !auth0Domain.endsWith("anthemiq.com");
      const loginFn = ({ username, password }) => {
        cy.get("input#username").type(username);
        cy.get("input#password").type(password, {
          log: false,
        });
        cy.get('button[type="submit"]').click();
      };
      if (isDifferentOrigin) {
        cy.origin(auth0Domain, { args }, loginFn);
      } else {
        loginFn(args);
      }
      cy.url().should("contain", Cypress.config().baseUrl);
      // This doesn't prevent the test from proceeding, it just gives the Auth0
      // SDK time to save everything (cookies, etc...) before the session is saved.
      // Because we're using the in-memory cache, there's no implicit wait we can
      // use instead.
      cy.wait(1000);
    },
    {
      cacheAcrossSpecs: true,
    }
  );
  cy.visit("/");

  log.snapshot("after");
  log.end();
});
```

I am seeing this fail both when `isDifferentOrigin` is true and false.

### Cypress Version

12.7.0

### Node version

v16.19.1

### Operating System

macOS 12.5

**Comment by mjhenkes** [comment]
Have you tried using the validate parameter?

https://docs.cypress.io/api/commands/session#Validating-the-session

If the session fails to validate it will be recreated.

**Comment by wongk** [comment]
I can certainly investigate this. This does seem like a workaround in this case, however, and I think ideally we'd like to understand why the session isn't restoring correctly. Invalidating the session will come with an obvious performance penalty.

**Comment by wongk** [comment]
So in order to validate the session, we need to check whether or not the user is redirected to the login page when visiting "/". Due to the way `session` works, we end up visiting "/" in a before each handler for each test, then at the start of the session block, then within the validate block (since this is cleared before the session is validated), and then for a 4th time after the session is validated. Perhaps we could get rid of the global before each handler. That still leaves 3 visits to "/" when the session is created, and 2 thereafter.

**Comment by wongk** [comment]
It looks like using:
```
      validate: () => {
        cy.visit("/");
        cy.url().should("contain", Cypress.config().baseUrl);
      },
```
actually breaks our tests. For some unknown reason, this prevents the page from loading after the session block is complete. Removing these two lines from the validate function allows it to work again.

**Comment by wongk** [comment]
So it occurred to me that we do not need to sign users out while running our tests. I removed this completely. Now it seems we are no longer having these issues, so I suspect `clearAllSavedSessions` was at the root of the problem. I'll leave this issue open as I still believe there's an issue with `clearAllSavedSessions`, as well as using the `validate` function as I mentioned previously.

**Comment by emilyrohrbough** [comment]
@wongk If you are signing users out, I would expect your server-side back-end to revoked the restored session values and show your applications login page.

`cy.session()` will have no context of the session being correctly restored without a `validate` function because it is simply applying the cookies, local_storage and session_storage to the page. The correctness of those applied values will depend on the application under test which is why `validate` is needed and recommended.

It is not recommended to do visits/DOM assertions within the `validate` function because of the multi-visit behavior you described above. Really a quick ping to ensure your front-end is authenticated with the back-end would be ideal. This shouldn't be a performance penalty but a quality check to skip login each time.

When you execute `clearAllSavedSessions` will actually delete the saved sessions used by `cy.session()` so any further use of `cy.session()` should result in a new session.

**Comment by wongk** [comment]
> @wongk If you are signing users out, I would expect your server-side back-end to revoked the restored session values and show your applications login page.
> 

It does.

> `cy.session()` will have no context of the session being correctly restored without a `validate` function because it is simply applying the cookies, local_storage and session_storage to the page. The correctness of those applied values will depend on the application under test which is why `validate` is needed and recommended.
> 

Now we just need to figure out how to actually validate.

> It is not recommended to do visits/DOM assertions within the `validate` function because of the multi-visit behavior you described above. Really a quick ping to ensure your front-end is authenticated with the back-end would be ideal. This shouldn't be a performance penalty but a quality check to skip login each time.

I don't have any other way to validate. If a visit to "/" gets redirected to our Auth0 login page, then the user is not logged in. Otherwise, they are.

> 
> When you execute `clearAllSavedSessions` will actually delete the saved sessions used by `cy.session()` so any further use of `cy.session()` should result in a new session.

Except this is not working properly.

**Comment by emilyrohrbough** [comment]
@wongk can you provide a reproducible example of `clearAllSavedSessions` not working correctly?

**Comment by wongk** [comment]
I am afraid the time commitment required by me to provide such an example is too high.

**Comment by AtofStryker** [comment]
@wongk if we do not have a reproduction for the `clearAllSavedSessions` issue, I am afraid we aren't going to be able to help with this specifically.

When it comes to your validation method, you mentioned that the following breaks your test?

```js
 validate: () => {
    cy.visit("/");
    cy.url().should("contain", Cypress.config().baseUrl);
  },
```

Do you have anything else you can possibly validate on to determine a authenticated user? You might be able to leverage the `auth0` [management api](https://github.com/auth0/auth0.js/#auth0management-1) in your validation method if you'd prefer to determine if a user has an active session with auth0. Or assert on display names in the UI if they exist, or possible session/localstorage keys/values present

**Comment by wongk** [comment]
The authenticated state is encapsulated by the Auth0 SDK, with the Auth guard being the primary control point for Angular applications. The tokens and related state are stored in memory, not in session or local storage (for security reasons). All routes go through the Auth guard first. This is why visiting "/" is required - to invoke the Auth guard, and refresh the token or redirect if necessary.

It's possible that a dummy request could be sent to the backend, which will always validate the JWT token and return a 401 if validation fails. At this point, our tests are working w/o validation, though, so it seems that would add no value in our case.

**Comment by AtofStryker** [comment]
I think that is what @emilyrohrbough is recommending. Your Cypress validate function can ping your back end which will validate your JWT, and if invalid return a 401, which should fail the validate. Is that what you are referring to? If the JWT is encapsulated, I am not sure how you will get it directly to run this validation. Unless you hack around it with a `cy.intercept`, which seems like an antipattern.

**Comment by AtofStryker** [comment]
I am going to close this issue due to inactivity. If this is still an issue @wongk let us know and we can re open and discuss.

**Comment by fleks-dev** [comment]
@AtofStryker , same happening to me. Can we review this and open this issue again?

I posted the questions [here](https://stackoverflow.com/questions/76006412/cypress-12-log-in-once-for-whole-test-run), but the sessions are not restored. Every `it` block when ran, has to log in again.

I can accomplish this using `testIsolation` but then cy.session does not make sense?

**Comment by emilyrohrbough** [comment]
@ktxxt Please review this [frequently asked question](https://docs.cypress.io/api/commands/session#Why-am-I-seeing-401-errors-after-calling-cysession). Based on your linked example, I imagine the session details have not fully been returned and updated on the page before the session command finishes so it's not storing all of the values your page expects. I suggested inspecting the data that is associated with the session and verifying all tokens/cookies are being collected and persisted when compared to a successful login.
