### ISSUE TITLE
Vite server not working in monorepo

### ISSUE THREAD

**Issue by radoslavirha** [cypress-io/cypress#26035]
### Current behavior

Project root is not recognised in monorepo (Vite dev server).

### Desired behavior

Work correctly in monorepo.

Add `searchForWorkspaceRoot(process.cwd())` to https://github.com/cypress-io/cypress/blob/434e6eec6e54461041774059b2d4ef5143b56a3d/npm/vite-dev-server/src/resolveConfig.ts#L114

### Test code to reproduce

Similar to https://stackoverflow.com/questions/74902697/error-the-request-url-is-outside-of-vite-serving-allow-list-after-git-init

### Cypress Version

12.7.0

### Node version

18.13.0

### Operating System

macOO

### Other

Vite docs: https://vitejs.dev/config/server-options.html#server-fs-allow

**Comment by lmiller1990** [comment]
Can you please provide more information on how to reproduce this? This code base is a monorepo with Vite but it is functioning as expected. What package manager are you using? What happens if you add your monorepo root to your `vite.config` under `fs.allow`?

**Comment by radoslavirha** [comment]
HI @lmiller1990 ,

basically when I run Vite dev server (Quasar), everything works fine. But when I start component tests, I'm getting [the same error as here](https://stackoverflow.com/questions/74902697/error-the-request-url-is-outside-of-vite-serving-allow-list-after-git-init) in tests (UI mode).

I described my workaround in [Quasar repo](https://github.com/quasarframework/quasar-testing/issues/326#issue-1604552590).

and I'm using yarn.

Thanks

**Comment by lmiller1990** [comment]
Should be fixed by https://github.com/cypress-io/cypress/pull/26036. This will be in the next release, which is in two weeks (prior to end of March).
