### ISSUE TITLE
[HANG/STUCK/JAM]Test Not Getting Executed

### ISSUE THREAD

**Issue by eonhealthqa** [cypress-io/cypress#26048]
### Current behavior

Once i run cypress it gets stuck/jam on the screen ""Your Tests are loading......""

my fan also started making noise once i invoke cypress and unable to execute my tests...

After 10 minutes it gives me this error
```
{
"
The following error originated from your test code, not from Cypress.

process is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
[node_modules/ci-info/index.js:5:1](http://localhost:61239/__/#)

3 | const vendors = require('./vendors.json')
4 |

5 | const env = process.env
| ^
6 |
7 | // Used for testing only
8 | Object.defineProperty(exports, '_vendors', {

"
}
```

Hardware Specifications Are
Processor 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz 2.42 GHz
Installed RAM 32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor

Cypress Version 12.7.0
node version is 18.13.0
ci-info = 3.7.1

### Desired behavior

available test cases should get executed 

### Test code to reproduce

even builtin examples are not getting executed 

### Cypress Version

12.7.0

### Node version

18.13.0

### Operating System

windows

### Other

![222085777-f91a1329-d4b8-438e-a11c-eec61af0c76e](https://user-images.githubusercontent.com/80677547/223677037-267d305b-b571-4e9e-b45e-e6da5bf2d05b.png)
![222085574-55f0282a-286f-4951-9a12-dae2a00252b8](https://user-images.githubusercontent.com/80677547/223677048-2ec17865-7e02-4c48-8e9a-f3d7254905c2.png)

**Comment by lmiller1990** [comment]
It's this line https://github.com/watson/ci-info/blob/master/index.js#L5

This package is for Node.js, you cannot use it in a browser like this. Are you importing this somewhere (maybe support/index.js)?

What's the goal here - are you trying to get some specific info about your CI in your test? One way to execute Node.js code is using `cy.task`, docs: https://docs.cypress.io/api/commands/task. Something like

```js
// in test
cy.task('ciInfo').then(res => {
  // res contains the data
})
```

Then...

```js
// cypress.config.js (runs in Node.js context)
const { defineConfig } = require('cypress')
var ci = require('ci-info')

module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
      on('task', {
        // deconstruct the individual properties
        ciInfo() {
          return ci
        },
      })
    },
  },
})
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
