### ISSUE TITLE
Add System Tests for Nx

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/cypress#26045]
### What would you like?

Add a new Nx workspace to `system-tests/nx-monorepo` and create  `angular`, `react-vite` and `react-webpack` projects that use CT (_we can add more in the future_). This will also generate `angular-e2e`, `react-vite-e2e` and `react-webpack-e2e` applications as well for E2E testing. Then we need a way to configure `system-tests` to run the appropriate tests for each project:

- Example script: `nx run react-vite:component-test` for CT app
- Example script: `nx e2e react-webpack-e2e` for E2E apps

### Why is this needed?

Nx is a 1st class adopter of both Cypress E2E & CT. Currently we do not have any system-tests setup to assure that changes to Cypress do not break Nx. The `@nrwl/cypress` package has ~900K weekly downloads on npm and represents a large number of users. Adding `system-tests` around Nx can help mitigate any breaking changes for Nx and our users.

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/26045?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @jordanpowell88

**Comment by marktnoonan** [comment]
Have we established that is feasible or do we need to do a spike and confirm? I recall some discussion about the way that NX wraps the Cypress binary not necessarily being easy to system test but I don't remember the details. @jordanpowell88 what do you think?

**Comment by jordanpowell88** [comment]
Yeah Nx uses the `@nrwl/cypress` executor. I'm not quite sure if we can still use their executor but target our binary instead of the `cypress` npm package.

**Comment by lmiller1990** [comment]
We've decided to spent max 1 day to see if there's any unknowns before doing the entire thing.

**Comment by lmiller1990** [comment]
WIP - I started on it.  https://github.com/cypress-io/cypress/pull/new/issue-26045

**Comment by jordanpowell88** [comment]
> WIP - I started on it. https://github.com/cypress-io/cypress/pull/new/issue-26045

FYI, we can add all of our projects in one nx monorepo. Ie: Angular, React, Vue, etc

Also the difficult part is actually executing the tests. Let me know if you need any additional context

**Comment by lmiller1990** [comment]
Ran into some issues, Nx expects a real binary, not a symlinked one, not sure why I can't just symlink like other tests.

I'll try write a binary-system test, but I'll be doing this later on - got a few other higher priority issues to do first.

**Comment by barbados-clemens** [comment]
@lmiller1990 Nx just runs the node apis from cypress

https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.ts#L20

https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.ts#L297-L299

is there a way we could change the Cypress executor to make it easier to work with the simlinked packages?

**Comment by lmiller1990** [comment]
There might be - the next thing I'm going to try is writing what we are calling "binary tests" that run against a real, built version of the Cypress binary. No symlinks or anything - it's the real deal. That should avoid this problem. The tests run quite a bit slower, but it's also more production like.

Those tests are in this directory, for reference: https://github.com/cypress-io/cypress/blob/develop/system-tests/test-binary/node_versions_spec.ts

If this doesn't work out, I'll look more into what we can do in Cypress and/or the Nx plugin to facilitate this.
