### ISSUE TITLE
Cypress.env('ENV_NAME') does not work in interactive mode

### ISSUE THREAD

**Issue by wlsf82** [cypress-io/cypress#2605]
I am defining "secrets" for usage on tests, and exporting them as environment variables locally and on our continuous integration server, using `export CYPRESS_SOME_SECRET=somesecrethere`, then, in the tests files I'm doing something like `cy.get('.secret-field').type(Cypress.env('SOME_SECRET'));`, and when running such test in interactive mode the test fails with the following error: `CypressError: cy.type() can only accept a String or Number. You passed in: 'undefined'`, but if I run the tests in headless mode (using `cypress run`), the test works.

### Current behavior:

The test fails with `CypressError: cy.type() can only accept a String or Number. You passed in: 'undefined'` when running in interactive mode due to not find exported environment variable.

### Desired behavior:

The test should work in interactive mode precisely as it works when using `cypress run`.

### Steps to reproduce:

1. Export an environment variable through the command line, or on ~/.bash_profile (e.g.: `export CYPRESS_SOME_SECRET=somesecrethere`;
2. In the test file, after visiting a page with a form where you will fill some secret information, type the secret using something like `cy.get('.secret-field').type(Cypress.env('SOME_SECRET'));`
3. Run the test in interactive mode.

### Versions

Cypress: 3.1.0
Operating system: macOS High Sierra 10.13.6
Chrome: 69.0.3497.100

**Comment by jennifer-shehane** [comment]
Hey @wlsf82, I've tested this and the environment variable is able to be read when in interactive mode when passed in properly. 

**There are a few ways you could do this.**

1. Export the env var in the same line as cypress open. `export CYPRESS_SOME_SECRET=somesecrethere cypress open` 
2. Export the env var in a separate line. You'll have to make sure you're within the same session when running the commands separately. 

    ```
    export CYPRESS_SOME_SECRET=somesecrethere
    cypress open
    ```
3. `cypress open --env SOME_SECRET=somesecrethere`

**There are a few places you can check to help debug whether the environment vars are being set correctly.**

1. In your terminal, type `printenv` - this will print all the env vars that are set for the session. For example, in my terminal I can set an env var in one tab and see it in `printenv`, but when I open a new tab that env var is no longer printed in `printenv`.
2. Check the **Settings** tab and click **Configuration** within the Cypress runner during interactive mode. You'll see any env vars that were set listed here under `env: {}`

<img width="912" alt="screen shot 2018-10-15 at 3 34 52 pm" src="https://user-images.githubusercontent.com/1271364/46973676-f12da000-d08f-11e8-9562-493069014659.png">

**Comment by ked1** [comment]
Hi @jennifer-shehane 

I face the same as @wlsf82 .

Your advice isn't a solution for me. I want to be able to set the environment variable independently on the "environment" to store a secret without commiting it to the repository. The run/open command is configured in file which is part of the repository.

If I read [https://docs.cypress.io/guides/guides/environment-variables.html#Option-3-CYPRESS](https://docs.cypress.io/guides/guides/environment-variables.html#Option-3-CYPRESS)
The first sentence clearly says that "Any environment variable on your machine that starts with either CYPRESS_ or cypress_ will automatically be added and made available to you."...

Why Cypress.env() doesn't return any value (CYPRESS_*) which I see with printenv on my bash console?

Thanks for your help!

**Comment by ked1** [comment]
fdf

**Comment by UncleGus** [comment]
We are experiencing the same frustration at the moment. We thought perhaps it was intentional that the `--env` switch doesn't work with `cypress open` since the documentation only refers to `cypress run`, but by your answer above, @jennifer-shehane I get the impression that it should work with `cypress open`.

Can you please confirm if this should work with `cypress open`? At the moment, it is not working in this way for us.

**Comment by UncleGus** [comment]
Sorry, this is unrelated to the original issue, and I have just determined that our problem was (I think) with how we were passing the command line parameters through npm. In any case, it is working as we want now.

**Comment by dethmasque** [comment]
I am seeing the same issue whether or not I `export` the environment variable or pass it to `cypress run` via `--env`. `cy.visit()` is able to successfully read in env vars, but `cy.type()` complains about being passed `undefined`. `printenv` shows that the env var exists.

**Comment by jennifer-shehane** [comment]
If you believe you are experiencing a bug in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) providing a fully reproducible example - a repo showing the issue is preferred.
