### ISSUE TITLE
TS reports an error when the second parameter of the nextUntil method is filter

### ISSUE THREAD

**Issue by a1burning** [cypress-io/cypress#26051]
### Current behavior

When I use the nextUntil method, see the documentation for the second parameter, which supports filter, but the TS type only supports options as the second parameter, and does not support passing the third parameter.

https://docs.cypress.io/api/commands/nextuntil

### Test code to reproduce

cy.get('#auxId1').nextUntil('#auxId3', '.auxClass')
cy.get('#auxId1').nextUntil('#auxId3', '.auxClass', { log: true })

### Operating System

Mac

### Debug Logs

```
Cypress.Chainable<JQuery<HTMLElement>>.nextUntil<keyof HTMLElementTagNameMap>(selector: keyof HTMLElementTagNameMap, options?: Partial<Cypress.Loggable & Cypress.Timeoutable> | undefined): Cypress.Chainable<...> (+2 overloads)

没有与此调用匹配的重载。
  第 1 个重载(共 3 个)，“(selector: keyof HTMLElementTagNameMap, options?: Partial<Loggable & Timeoutable> | undefined): Chainable<JQuery<HTMLElement | ... 67 more ... | HTMLUListElement>>”，出现以下错误。
    类型“"#auxId3"”的参数不能赋给类型“keyof HTMLElementTagNameMap”的参数。
  第 2 个重载(共 3 个)，“(selector: string, options?: Partial<Loggable & Timeoutable> | undefined): Chainable<JQuery<HTMLElement>>”，出现以下错误。
    类型“".auxClass"”的参数不能赋给类型“Partial<Loggable & Timeoutable> | undefined”的参数。ts(2769)
```

**Comment by mike-plummer** [comment]
Hi @a1burning , thanks for opening an issue. What version of Cypress are you using? The Typescript types for `cy.nextuntil` were updated in version 12.2.0 to support the `filter` parameter (#24772).

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
