### ISSUE TITLE
Electron won't run tests

### ISSUE THREAD

**Issue by leeuwd** [cypress-io/cypress#2608]
### Current behavior:

Electron (v59) won't run tests. Running tests in Chrome (v69) works fine. 

This yields and empty report:

```xml
<?xml version="1.0" encoding="UTF-8"?>
   <testsuites name="Mocha Tests" time="0" tests="0" failures="0">
</testsuites>
```

And the console output looks like:

<img width="790" alt="schermafbeelding 2018-10-15 om 16 09 23" src="https://user-images.githubusercontent.com/1755190/46956109-bf6b0800-d094-11e8-8a70-7f655e9841a1.png">

Electron screens:

<img width="1792" alt="schermafbeelding 2018-10-15 om 16 36 23" src="https://user-images.githubusercontent.com/1755190/46957911-e4617a00-d098-11e8-82cc-f0d3f4030fb7.png">
<img width="1348" alt="schermafbeelding 2018-10-15 om 16 34 38" src="https://user-images.githubusercontent.com/1755190/46957912-e4617a00-d098-11e8-9ba5-4e8a03df57b6.png">

As you can see, a request to a tests file (e.g. `tests?p=tests/e2e/specs/*.js`) stays pending forever.

### Desired behavior:

Tests should run, regardless of `--headless` mode.

### Steps to reproduce:

All fails (and yes, the local server is running 👀):

```bash
cypress run --headed
cypress run --headed --config baseUrl=http://localhost:8080
cypress run --config baseUrl=http://localhost:8080
```

Or, since the project is a Vue CLI 3 project, this also fails:

```bash
vue-cli-service test:e2e --headless
vue-cli-service test:e2e --mode=development --headless --headed
```

Note: `--headless` is a Vue CLI 3 option and `--headed` a [Cypress CLI option](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-headed) to force Electron to be shown.

### Versions

```txt
macOS Mojave

vue@2.5.17
vue-router@3.0.1
vuex@3.0.1
vue-jest@3.0.0
webpack@4.20.2
mocha@5.2.0
mocha-junit-reporter@1.18.0
mocha-multi-reporters@1.1.7
cypress@3.1.0
node@10.12.0
```

**Comment by jennifer-shehane** [comment]
@leeuwd Can you confirm that this only happens when passing the `--headed` flag?

Also, just to understand your use case, why are you passing the `--headed` flag?

**Comment by leeuwd** [comment]
@jennifer-shehane: thanks for getting back. I've spend another day on the issue, and it seems the `--headed` flag is not the core issue. I was using `--headed` to make Electron visual. 

Another symptom: it seems that when the console output contains the following, the tests work (also in Electron!). Talking about the `Check if application is alive...` here. If the console does not contain this, tests's won't run, as described in my opening post.

![Uploading Schermafbeelding 2018-10-16 om 13.43.59.png…]()

It now looks like random succeeding/failing, even with an almost deconstructed application (to rule things out). As if my OS is interfering.

**Comment by leeuwd** [comment]
It now looks Vue CLI scaffolding is somehow in play. https://github.com/cypress-io/cypress/issues/2564#issuecomment-427439976 contains a fix that seems to work for me.

I changed `tests/e2e/plugins/index.js` from:

```js
// https://docs.cypress.io/guides/guides/plugins-guide.html
/* eslint-disable import/no-extraneous-dependencies global-require */
const webpack = require('@cypress/webpack-preprocessor')

module.exports = (on, config) => {
  on('file:preprocessor', webpack({
    webpackOptions: require('@vue/cli-service/webpack.config'),
    watchOptions: {}
  }))

  return Object.assign({}, config, {
    fixturesFolder: 'tests/e2e/fixtures',
    integrationFolder: 'tests/e2e/specs',
    screenshotsFolder: 'tests/e2e/screenshots',
    videosFolder: 'tests/e2e/videos',
    supportFile: 'tests/e2e/support/index.js'
  })
}
```

to:

```js
// https://docs.cypress.io/guides/guides/plugins-guide.html
const webpack = require('@cypress/webpack-preprocessor');

module.exports = (on, config) => {
  const webPackOptions = {
    watchOptions: {},
  };

  // Not for Cypress
  // @see https://github.com/cypress-io/cypress/issues/2564
  // @see https://github.com/cypress-io/cypress/issues/2608
  if (!process.env.CYPRESS_ENV) {
    webPackOptions.webpackOptions = require('@vue/cli-service/webpack.config');
  }

  on('file:preprocessor', webpack(webPackOptions));

  return Object.assign({}, config, {
    fixturesFolder: 'tests/e2e/fixtures',
    integrationFolder: 'tests/e2e/specs',
    screenshotsFolder: 'tests/e2e/screenshots',
    videosFolder: 'tests/e2e/videos',
    supportFile: 'tests/e2e/support/index.js',
  });
};
```

This must break something too, but I'm not sure what (yet).

**Comment by leeuwd** [comment]
Based on further research, I guess we can conclude this is an issue in Vue CLI's scaffolding, not Cypress.
