### ISSUE TITLE
root level "beforeEach" hook doesn't run before "before" hook inside the block

### ISSUE THREAD

**Issue by bondom** [cypress-io/cypress#26098]
### Current behavior

root-level `beforeEach` hook is executed **after** `before` hook inside the test block

### Desired behavior

According to [docs](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Hooks):

root-level `beforeEach` hook should run **before** every test block

### Test code to reproduce

```
// works if "before" is used instead of "beforeEach" here
beforeEach(() => {
  cy.intercept('GET', '**/comments/*', {
      fixture: 'comment.json'
  }).as('myAlias');
})

describe('My test', () => {
    before(() => {
      cy.visit('./index.html')
      // this wait fails with: cy.wait() could not find a registered alias for: @myAlias.
      cy.wait('@myAlias');
    })
  
    it('test', () => {
        cy.get('[id="content"]').should('contain', 'My comment name');
    })
  })
```

### Cypress Version

12.7.0

### Node version

v16.17.0

### Operating System

macOS 11.15.2

**Comment by mike-plummer** [comment]
Hi @bondom , thanks for opening an issue. The behavior you're seeing is expected and [described here](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#The-order-of-hook-and-test-execution-is-as-follows). For any given test, all associated `before` blocks will run first, followed by associated `beforeEach` blocks. Regardless of where it is declared, a `beforeEach` is relative to individual tests (each of which is a "block"), not suites of tests (such as a `describe`).

**Comment by bondom** [comment]
@mike-plummer Thanks! Was seeing that, but for some reason haven't paid so much attention to this piece as comparing to doc that I linked, maybe because current behaviour didn't work out for me and didn't seem so logical, Thanks!
