### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module 'graphql-request'

### ISSUE THREAD

**Issue by billy-reify** [cypress-io/cypress#26092]
### Current behavior

Currently I have several tests that utilize the graphql-request library. When tests execute, the following error occurs locally and as well as within CircleCi.

Upgrade to latest Cypress but that had no effect on error generated

> Error: Can't walk dependency graph: Cannot find module 'graphql-request' from '/Users/.../Documents/GitHub/sponsor-test-automation-cypress/cypress/support/GraphQL/Sponsor/queries/abstractQuery.js'
    required by /Users/.../Documents/GitHub/sponsor-test-automation-cypress/cypress/support/GraphQL/Sponsor/queries/abstractQuery.js
    at /Users/../Documents/GitHub/sponsor-test-automation-cypress/node_modules/resolve/lib/async.js:146:35
    at processDirs (/Users/.../Documents/GitHub/sponsor-test-automation-cypress/node_modules/resolve/lib/async.js:299:39)
    at isdir (/Users/.../Documents/GitHub/sponsor-test-automation-cypress/node_modules/resolve/lib/async.js:306:32)
    at /Users/.../Documents/GitHub/sponsor-test-automation-cypress/node_modules/resolve/lib/async.js:34:69
    at callback (/Users/.../Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:299:20)
    at callback (/Users/.../Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:299:20)
    at FSReqCallback.oncomplete (node:fs:194:21)

Currently running 
Cypress 11.2
Node v18.15.0
NPM v9.5.0

When I drill into the graphql-request module index.ts, I see the following broken lines
![Screenshot 2023-03-13 at 7 00 47 PM](https://user-images.githubusercontent.com/82397475/224851285-7eea6aaa-8a67-4a76-993b-66825e64a3b0.png)

![Screenshot 2023-03-13 at 7 00 33 PM](https://user-images.githubusercontent.com/82397475/224851313-259c6e17-b0a7-4c20-903e-be7c1caa6cb4.png)

### Desired behavior

Need any one of my tests that reference this library to work.

### Test code to reproduce

`import { gql } from "graphql-request";

export class AbstractQuery {
  /**
   * Constructor
   * @param {String} query GraphQL query
   * @param {Map} variables GraphQL variables
   * The config internal variables is a map with these parameters:
   * { username: String,
   *   password: String,
   *   clientId: String,
   *   clientSec: String,
   *   refreshToken: boolean
   * };
   */
  constructor(query, variables) {
    this.config = {};
    this.query = query;
    this.variables = variables;
  }

  /**
   * Set the configs of the query
   * @param {Map} config configuration to use for the get token
   * @return instance of this object
   */
  withConfig(config) {
    this.config = config;
    console.log("CONFIG " + config)
    return this;
  }

  /**
   * Execute the query
   * @return yielded request
   */
  doQuery() {
    return cy
      .wrap(null, { log: false })
      .then(() => {
        TokenGetter.getAccessToken(this.config);
      })
      .then((token) => {
        cy.log("TOKEN: " + token.tokenValue)
        return cy.request({
          method: "POST",
          url: `https://testme.com/gql`,
          headers: {
            Authorization: `Bearer ${token.tokenValue}`,
            "Context-Type": "application/graphql",
            Accept: "application/json",
          },
          body: {
            query: gql`
              ${this.query}
            `,
            variables: this.variables,
          },
        });
      });
  }
}
`

### Cypress Version

11.2

### Node version

18.15.0

### Operating System

Ventura 13.2.1 (22D68)

**Comment by lmiller1990** [comment]
I got something similar when I tried to reproduce:

![image](https://user-images.githubusercontent.com/19196536/225206231-23475f1b-9f46-4899-a0e1-570160ca6b7a.png)

**Comment by lmiller1990** [comment]
Hi! This looks like a combination of problems:

1) library is not compatible with webpack v4, which doesn't specify `main` in `package.json`
2) cypress ships webpack v4 by default

Here's a minimal repository that uses webpack 5, the latest `@cypress/webpack-preprocessor`, and it works as expected: https://github.com/lmiller1990/cypress-test-tiny/pull/1

Let me know if you run into any troubles getting this working in your own project.

**Comment by billy-reify** [comment]
Unfortunately upgrading via npm install @cypress/webpack-preprocessor to version "@cypress/webpack-preprocessor": "^5.17.0",did not fix the error. I also upgraded Cypress as well to 12.8 and that didn't resolve the issue either. Still seeing same errors within the index.ts file of the graphql-request module

**Comment by lmiller1990** [comment]
Did you try registering the latest preprocessor in `cypress.config.js`:

```js
const preprocessor = require('@cypress/webpack-preprocessor')

module.exports = {
  e2e: {
    setupNodeEvents(on, config) {
      on('file:preprocessor', preprocessor())
    },
  },
}
```

You will need to do this explicitly, like I did in the PR example, or it will use the default bundled version.

**Comment by billy-reify** [comment]
So I've gotten my self into a hole where I've been upgrading and uninstalling, reinstalling that now when I go to launch a test I get this:
`The following error originated from your test code, not from Cypress.

> Suite argument "title" must be a string. Received type "object"

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.`

Any idea how to just uninstall and reinstall cypress or get past this situation??

**Comment by billy-reify** [comment]
`at createInvalidArgumentTypeError (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:100096:13)
    at new Suite (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:106264:11)
    at ../driver/node_modules/mocha/lib/suite.js.Suite.create (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:106244:15)
    at Object.create (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:100458:27)
    at context.describe.context.context (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:100251:27)
    at createRunnable (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:156160:31)
    at <unknown> (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:156221:14)
    at <unknown> (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:158835:23)
From previous event:
    at evalScripts (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:158830:58)
    at <unknown> (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:158839:152)
From previous event:
    at runScriptsFromUrls (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:158839:136)
    at Object.runScripts (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:158853:12)
    at $Cypress.onSpecWindow (https://staging.studyteamapp.com/__cypress/runner/cypress_runner.js:147490:75)`

**Comment by billy-reify** [comment]
So now I'm at cypress 12.8.1 but when I attempt to execute " npm install @cypress/webpack-preprocessor" I get this error:
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: cypress-real-events@1.7.1
npm ERR! Found: cypress@12.8.1
npm ERR! node_modules/cypress
npm ERR!   cypress@"*" from @types/cypress@1.1.3
npm ERR!   node_modules/@types/cypress
npm ERR!     peer @types/cypress@"^1.1.0" from cypress-iframe@1.0.1
npm ERR!     node_modules/cypress-iframe
npm ERR!       cypress-iframe@"^1.0.1" from the root project
npm ERR!   peer cypress@">= 6.0.0" from cypress-tags@1.1.2
npm ERR!   node_modules/cypress-tags
npm ERR!     cypress-tags@"^1.1.2" from the root project
npm ERR!   1 more (the root project)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x || ^10.x" from cypress-real-events@1.7.1
npm ERR! node_modules/cypress-real-events
npm ERR!   cypress-real-events@"^1.7.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: cypress@10.11.0
npm ERR! node_modules/cypress
npm ERR!   peer cypress@"^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x || ^10.x" from cypress-real-events@1.7.1
npm ERR!   node_modules/cypress-real-events
npm ERR!     cypress-real-events@"^1.7.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by billy-reify** [comment]
I did added the code you suggested and originally was able to install the
@cypress/webpack-preprocessor but after it didn't work I tried upgrading to
Cypress to 12.8.1, then back to 11.2 and when I tried to reinstall
@cypress/webpack-preprocessor it gives me this message about conflicts

[image: Screenshot 2023-03-15 at 8.21.21 PM.png]

**Comment by billy-reify** [comment]
So after resetting my environment, I implemented the code and installed npm module just as you specified but now when I execute any of my tests, not just ones that reference graphql-requests, I get this error:

<img width="1218" alt="Screenshot 2023-03-15 at 9 51 01 PM" src="https://user-images.githubusercontent.com/82397475/225489842-2968e246-c546-4776-902a-a55901139024.png">

Looking at the graphql-requests module I see an additional error as well as the other noted above:

<img width="1218" alt="Screenshot 2023-03-15 at 9 58 34 PM" src="https://user-images.githubusercontent.com/82397475/225490280-9388144e-948b-4985-99c9-c56421e45953.png">

**Comment by lmiller1990** [comment]
What's that `vitest` import? Looks unintentional.

Can you please create a minimal version of your project and upload the repository? I was able to correctly import the module in my minimal example; I suspect something else in your environment is off, but I can't help much more until you share more code.

**Comment by billy-reify** [comment]
Hi Lachlan.
I will be out of the office today but will return tomorrow and provide the
files you require.
Thanks
Bill

**Comment by lmiller1990** [comment]
We resolved it in https://github.com/lmiller1990/cypress-test-tiny/pull/1. It was an issue relating to the fact Cypress still ships webpack 4.
