### ISSUE TITLE
cy.get(selector).type('HIDDEN', {log:false}) does not hide 'HIDDEN' in certain situations

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#26101]
### Current behavior

If the selector is pointing to a disabled element or a non-valid typeable element, it will just expose 'HIDDEN' in the Cypress Command Log and screenshots in the cypress/e2e/screenshots folder

![image](https://user-images.githubusercontent.com/5721147/225024946-d4c830a7-aafb-4ad1-9752-876af2d1eff5.png)

### Test code to reproduce

cy.get('html').type('credential', {log:false})

### Cypress Version

12.6.0

### Node version

v18.13.0

### Operating System

Windows 10.0.19044.2604

**Comment by alexsch01** [comment]
Cypress 12.8.0 running in Debian 11 also has this issue.

**Comment by alexsch01** [comment]
[cypress/e2e/spec.cy.js]

```node
describe('template spec', () => {
        it('passes', () => {
                cy.on('fail', () => { return false })
                cy.get('html').type('SECRET', { log: false })
        })
})
```

Command used

```bash
npx cypress run --headed --no-exit
```

![image](https://user-images.githubusercontent.com/5721147/225157509-9136f662-3bec-49eb-9261-c473216c235c.png)

**Comment by lmiller1990** [comment]
I reproduced it: https://github.com/cypress-io/cypress-test-tiny/compare/master...lmiller1990:cypress-test-tiny:issue-26101?expand=1 (branch: `issue-26101`). It only happens if you do a `cy.log` **before** `cy.visit`.
