### ISSUE TITLE
Docker cypress/factory Couldn't determine Mocha version

### ISSUE THREAD

**Issue by romankhomitskyi** [cypress-io/cypress#26109]
### Current behavior

Getting this error on CI  when using cypress/factory

`Couldn't determine Mocha version`

### Desired behavior

Should be no errors

### Test code to reproduce

Docker file

```
ARG NODE_VERSION='18.13.0'
ARG CHROME_VERSION='110.0.5481.177-1'
ARG FIREFOX_VERSION='110.0.1'
ARG YARN_VERSION='1.22.19'


FROM cypress/factory

ENV TZ=Etc/UTC

WORKDIR /app/tests/Cypress
```

Docker compose file

```
  cypress:
    image: registry.gitlab.com/cypress:1.0.0
    env_file:
      - .env
    environment:
      СYPRESS_numTestsKeptInMemory: 0
      CYPRESS_VERIFY_TIMEOUT: 100000
      CYPRESS_CACHE_FOLDER: "/app/tests/Cypress/.cache/Cypress"
    volumes:
      - app:/app
```

Package json

```
"devDependencies": {
		"@cypress/grep": "3.1.3",
		"@cypress/skip-test": "^2.6.1",
		"@cypress/webpack-batteries-included-preprocessor": "2.4.0",
		"@cypress/webpack-preprocessor": "5.17.0",
		"@faker-js/faker": "^7.6.0",
		"@types/luxon": "3.2.0",
		"@types/node": "^18.15.0",
		"@typescript-eslint/eslint-plugin": "5.54.1",
		"@typescript-eslint/parser": "5.54.1",
		"cypress": "12.5.0",
		"cypress-fail-on-console-error": "4.0.2",
		"cypress-localstorage-commands": "2.2.2",
		"cypress-multi-reporters": "1.6.2",
		"cypress-recurse": "1.27.0",
		"dotenv": "16.0.3",
		"eslint": "8.35.0",
		"eslint-plugin-cypress": "^2.12.1",
		"junit-report-merger": "5.0.0",
		"luxon": "3.3.0",
		"mocha-junit-reporter": "2.2.0",
		"prettier": "2.7.1",
		"ts-node": "10.9.1",
		"typescript": "4.9.5",
		"uuid": "9.0.0",
		"yarn-upgrade-all": "^0.5.4"
	},
	"dependencies": {
		"mongodb": "5.1.0"
	}
```

Reporter config
```
{
	"reporterEnabled": "spec, mocha-junit-reporter",
	"mochaJunitReporterReporterOptions": {
		"mochaFile": "results/junit/[hash].xml"
	}
}
```

Typescript config

```
{
	"compilerOptions": {
		"outDir": "./dist",
		"target": "ES2019",
		"moduleResolution": "Node",
		"esModuleInterop": true,
		"resolveJsonModule": true,
		"noUnusedParameters": true,
		"experimentalDecorators": true,
		"types": [
			"cypress",
			"cypress-localstorage-commands",
			"node",
			"@cypress/grep"
		],
		"noEmit": true,
		"allowJs": true,
		"baseUrl": ".",
		"paths": {
			"@src/*": ["src/*"],
			"@global/*": ["src/global/*"]
		}
	},
	"include": ["./src/**/*"]
}

```

### Cypress Version

12.5.0

### Node version

18.13.0

### Operating System

Debian

### Other
<img width="393" alt="Screenshot 2023-03-14 at 20 12 35" src="https://user-images.githubusercontent.com/57874507/225099088-5df7b48f-7e23-44a9-9500-f93e165c97ca.png">

<img width="426" alt="Screenshot 2023-03-14 at 20 13 24" src="https://user-images.githubusercontent.com/57874507/225099252-f83c5a7a-0b4a-40d5-a0e3-ea8e0ccc8a4c.png">

<img width="482" alt="Screenshot 2023-03-14 at 20 39 23" src="https://user-images.githubusercontent.com/57874507/225105275-65bf81d0-47c2-4b82-973b-193556d1a7a1.png">

**Comment by lmiller1990** [comment]
I reproduced this here https://github.com/cypress-io/cypress-test-tiny/compare/master...lmiller1990:cypress-test-tiny:issue-26109?expand=1

Branch is `issue-26109`. I did not need Docker to reproduce it. Seems all you need to do is add `reporter: "cypress-multi-reporters"` as the reporter.

The reporter(s) still work as expected.

**Comment by lmiller1990** [comment]
Duplicate? https://github.com/cypress-io/cypress/issues/9439

**Comment by lmiller1990** [comment]
I looked into it more - we can't do anything about this warning, it's from a third party library. See my comment: https://github.com/cypress-io/cypress/issues/9439#issuecomment-1469376858
.
