### ISSUE TITLE
When reading a zip file Cypress removes the last character from the file name inside that folder

### ISSUE THREAD

**Issue by antosha-85seequent** [cypress-io/cypress#26114]
### Current behavior

According to my testing procedure, I am required to download a zip file and verify its contents. 
Specifically, I am working with a zip file named `File-Topography.zip`, which includes a file named `Object-Topography.dxf`. To read this file, I utilized Cypress's built-in `readFile` function. 
However, upon inspecting the output file, I noticed that the filename was incorrect, displaying as `Object-Topograph.dxf`. 
Initially, I attempted to resolve the issue by using the `adm-zip` package, assuming it was responsible for the problem. However, after examining the raw output, I determined that the issue is actually related to Cypress itself.

### Desired behavior

Cypress should read the correct file name

### Test code to reproduce

I'm not gonna share the whole file but I'll leave this snippet here

```
cy.readFile(`./cypress/downloads/${exportFileName}.zip`, "binary").then(
  (content) => {
    expect(content.includes(`${exportArtifactName.slice(0, -1)}.dxf`)).to.be
      .true; //have to slice to make my test pass
    return cy.wrap(null);
  }
); 
```            

### Cypress Version

Cypress package version: 10.11.0 Cypress binary version: 10.11.0 Electron version: 21.0.0

### Node version

Bundled Node version: 16.16.0

### Operating System

macOS Ventura 13.2

**Comment by AtofStryker** [comment]
Hi @antosha-85seequent. Thank you for opening an issue. I tried giving this a reproduction [here](https://github.com/AtofStryker/cypress-issue-26114), but wasn't able to reproduce the issue. Is there something I am missing in my code?

**Comment by antosha-85seequent** [comment]
Hey @AtofStryker 
I believe I have identified the cause of the issue. Initially, when I tested your code, it appeared to be functioning correctly, but I suspected that you may have used a smaller file than the one I had, which was about 20 times larger. Upon reviewing the files in cypress's `downloads` folder, I discovered four files, one of which had a truncated last character. Additionally, I came across another file with the same name but with the correct `Artifact-Topography.dxf` name, which led to confusion.

After cleaning up the `downloads` folder, the code started working properly when executed locally. However, when I ran the code through `GitHub Actions`, it failed to run. I got the help of two colleagues, and they experienced the same issue with the code failing to run locally due to the last character being sliced off.

To provide more context about our test, we entered the Artifact name into an `<input type="text"/>` element and then clicked on a button to submit the data. After that, we were able to download a zip file. Further investigation revealed that Cypress was too fast and unable to retain the input form's state due to the quick transition.

To work around this issue, we had two options: 1) click on another element before clicking the Submit button or 2) remove focus from the input element after typing by using `type('...').blur()`. Implementing either of these options enabled our test to pass both locally and with `GitHub Actions`.

Please let me know if you require additional information or if you can close this ticket. Alternatively, you may want to review my version of what occurred.

**Comment by AtofStryker** [comment]
@antosha-85seequent interesting. It sounds like a race condition in that case. If you think the work around is suitable, we can close the issue. Otherwise, I might need some help reproducing this directly, but even then I am not entirely sure what a solution might look like. Let us know what you would like to do!

**Comment by antosha-85seequent** [comment]
@AtofStryker I don't mind if you close the ticket as the workaround works fine for us. Thank you.
