### ISSUE TITLE
Using rewire inside a test

### ISSUE THREAD

**Issue by lkaratun** [cypress-io/cypress#2611]
Hi everyone!
I'm trying to test some private functionality of my app using rewire (which works without cypress), but importing it inside a test fails. 

### Current behavior:

Running `const rewire = require("rewire");` produces an error:

> Error: Cannot find module 'coffee-script' from '<app_root>\node_modules\rewire\lib'

Installing coffee-script doesn't help, but throws a different error: 

> Uncaught TypeError: fs.readdirSync is not a function

### Desired behavior:

rewire gets imported successfully

### Steps to reproduce:

`npm i rewire`

Make a test file with the following line:
`const rewire = require("rewire");` 
Run the test

### Versions

cypress 3.1.0, rewire 4.0.1, Win 8.1, Chrome 69

Thanks in advance for having a look at the issue!

**Comment by chrisbreiding** [comment]
Can you describe your use-case for rewire a bit more and maybe an example of how you'd like to use it? It looks like a tool for unit tests that run in Node. Cypress runs your tests in the browser and is primarily for integration tests, so that mismatch is likely what's causing issues. I see [rewire-webpack](https://github.com/jhnns/rewire-webpack) exists for client-side code, so that might be an option if your app code is bundled with webpack.

**Comment by lkaratun** [comment]
Hi @chrisbreiding, I'm trying to test a function that pulls data from the DOM and stores it in a data structure that is not exported from the app (so I can't just import it in the test). I was hoping to use Cypress for that to leverage the ease of DOM interaction in the tests.
To use rewire-webpack, it would have to be included into Cypress, not my app bundle (since I need it for testing, not for the app functionality). I tried just requiring rewire-webpack from the test file, and it works fine but trying to rewire the app module returns undefined. 
I was wondering if cypress is built with webpack (sorry if that's a stupid question)? If it is, is it possible to add the rewire-webpack plugin to the cypress webpack config?

**Comment by chrisbreiding** [comment]
Cypress does not use webpack by default, but you can [configure it to use webpack](https://github.com/cypress-io/cypress-webpack-preprocessor) and add the rewire-webpack plugin.

**Comment by jennifer-shehane** [comment]
Closing as resolved.
