### ISSUE TITLE
Binded attributes are not set after cy.mount() on `cypress run` but are set on `cypress open` [Angular]

### ISSUE THREAD

**Issue by ger88555** [cypress-io/cypress#26119]
#### 1. Cypress test

```js
it('generates unique id', () => {
    const generatedIds: any[] = []

    cy.mount(
        `
            <app-custom-input></app-custom-input>
            <app-custom-input></app-custom-input>
        `,
        {
            declarations: [CustomInputComponent], 
        }
    )

    cy.get('app-custom-input > input')
        .each($component => generatedIds.push($component.attr('id')))
        .then(() => {
            expect(generatedIds[0]).not.to.equal(generatedIds[1]);
        })
})
```

The above Cypress test case asserts that two components with `<input />` tags that are rendered on the same template have different **id** properties.

The underlying component class implements this requirement using Angular’s [attribute binding](https://angular.io/guide/property-binding) on the HTML element’s **id** property to assign a computed value on runtime:

```js

<input [id]="nativeID" type="text" /> // `nativeID` is initialized on the component's constructor
```

The logic of this test case is the following:
1. Declare the `generatedIds` array
2. Mount the components (with **cy.mount()**)
3. Select the rendered HTML `input` elements that should have unique **id** properties (with **cy.get()**)
4. Iterate over the selected HTML `input` elements and push their **id** properties to the `generatedIds` array (with Cypress **.each()** command)
5. Assert that the first pushed **id** is different from the second pushed **id**

#### 2. Output

This test case **PASSES** when executed with `cypress open`:
![cypress open](https://user-images.githubusercontent.com/30606722/225250205-7985f3ab-a55f-4b6f-9fe6-005d8a11dd7c.png)
This test case **FAILS** when executed with `cypress run`:
![image](https://user-images.githubusercontent.com/30606722/225250845-0c33b2b8-e858-4402-a560-95b6a66d28ec.png)

#### 3. Root cause

It turns out that, inside a `cypress run` execution both **ids** pushed to the `generatedIds` array will be `undefined`.

If we **console.log** the selected HTML elements, these will exist, but invoking **attr(‘id’)** on them will return undefined.
This is because, when calling **cy.mount()** on a `cypress run` execution, the next cypress query or command in the test case will be dispatched before the component’s class instance has initialized any binded attributes. Therefore, all Angular binded attributes in the rendered DOM tree will be `undefined`. This [Angular initial render is so quick](https://stackoverflow.com/questions/55091522/component-rendered-before-calling-constructor-or-ngoninit) that it’s not perceived by the human eye, but Cypress tests (only in `cypress run` executions) do read this initial DOM tree.

On the other hand, calls of **cy.mount()** inside `cypress open` executions **wait until Angular has initialized the binded attributes** before the next Cypress query or command in the test is dispatched.

### Desired behavior

On `cypress open` executions,  a **cy.mount()** statement will end _after_ the Angular component's binded attributes have been initialized. This means that the first **cy.get()** query _will always_ have the initial values of the binded attributes available on the DOM tree.

On `cypress run` executions, a **cy.mount()** statement will end _before_ the Angular component's binded attributes have been initialized, but _after_ the first DOM render. This means that the first **cy.get()** query _will never_ have the initial values of the binded attributes available on the DOM tree.

Nowhere in the documentation is this caveat mentioned. **cy.mount()** calls inside `cypress open`  create the reasonable expectation that a component's initial attribute values are rendered on the DOM before the first Cypress query.

The behavior of **cy.mount()** should be the same on `cypress open` and `cypress run`.

### Test code to reproduce

https://github.com/ger88555/angular-cypress

### Cypress Version

12.8.0

### Node version

v16.15.0

### Operating System

Windows 10

### Current Workaround of the Issue

The following version of the same test case **PASSES** in both `cypress open` and `cypress run` executions:
```js
it('generates unique id', () => {
            const generatedIds: any[] = []

            cy.mount(
                `
                    <app-custom-input></app-custom-input>
                    <app-custom-input></app-custom-input>
                `,
                {
                    declarations: [CustomInputComponent], 
                }
            )

            cy.get('app-custom-input > input').as('components')

            // On executions of 'cypress run', binded attributes are undefined when Cypress queries start running,
            // so we do a 'should' assertion before the test logic that implicitly waits until the 'id' attributes
            // have been initialized in the component's constructor and set in the DOM tree.
            // This behavior is NOT present on 'cypress open' executions.
            cy.get('@components').should(($components) => {
                $components.each((index, $component) => {
                    expect($component.getAttribute('id')).not.to.be.null;
                })
            })

            cy.get('@components')
                .each($component => generatedIds.push($component.attr('id')))
                .then(() => {
                    expect(generatedIds[0]).not.to.equal(generatedIds[1]);
                })
        })
```

This last version adds a **should()** assertion that implicitly waits until the **id** attributes of the found HTML elements have been initialized in the component's constructor, before using them.

**Comment by lmiller1990** [comment]
Hi! Great bug report!

I don't think there's any actual difference in the *code that executes* between open mode and run mode - I think it's likely a race condition, and open mode runs slightly slower (rendering more DOM nodes, etc) which leaves enough time for the Angular component to complete initialization.

To test this, I added `cy.wait(50)`:


```js
    describe('will ONLY pass on `cypress open`', () => {
        it('generates unique id', () => {
            const generatedIds: any[] = []

            cy.mount(
                `
                    <app-custom-input></app-custom-input>
                    <app-custom-input></app-custom-input>
                `,
                {
                    declarations: [CustomInputComponent], 
                }
            )

            cy.wait(50)  // <========= added this

            cy.get('app-custom-input > input')
                .each($component => generatedIds.push($component.attr('id')))
                .then(() => {
                    expect(generatedIds[0]).not.to.equal(generatedIds[1]);
                })
        })
    })

```

Now the test passes in run mode. This definitely isn't ideal, though - it's still a race condition that can randomly fail if the component takes more than 50ms to initialize the `id`. Another more idiomatic way to tell Cypress to wait until the `id` attrs exist might be using `should`, which will retry until the condition is true (or time out after 5000ms):

```js
  it("generates unique id", () => {
  const generatedIds: any[] = [];

  cy.mount(
    `
      <app-custom-input></app-custom-input>
      <app-custom-input></app-custom-input>
    `,
    {
      declarations: [CustomInputComponent],
    }
  );

  cy.get("app-custom-input > input").as("components").should("have.attr", "id");
  cy.get("@components")
    .each(($component) => {
      generatedIds.push($component.attr("id"));
    })
    .then(() => {
      expect(generatedIds[0]).not.to.equal(generatedIds[1]);
    });
});
```

What might be more ideal, long term, would be eliminating this issue entirely. It would be nice if we could tell `cy.mount()` to wait until Angular has finished doing all the initialization. It looks like we don't [do anything like that right now](https://github.com/cypress-io/cypress/blob/ea8173f6d9bc41657987349abcff44f7d14d1777/npm/angular/src/mount.ts#L337-L359). Does Angular have some kind of lifecycle hook we could observe for this?

I'll cc in @jordanpowell88 as well, who has deep knowledge on Angular.
