### ISSUE TITLE
Cypress does not correctly terminate SSE connection leaving SSE connections to accumulate on server for duration of run.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#2612]
### Is this a Feature or Bug?

Bug

### Current behavior:

We are currently experiencing serious issues with SSEs on Cypress. We
suspect that the Cypress proxy implementation has a bug that is holding
connections for the entire duration of the test run causing SSE connections
to accumulate on the server. We have clearly reproduced this and
consistently confirmed the behaviour.

### Steps to reproduce:

See instructions in the README of repo below.

https://github.com/hally9k/cypress-sse

Previous older issue with SSE here: https://github.com/cypress-io/cypress/issues/1440

### Versions

Cypress 3.1.0

**Comment by brian-mann** [comment]
I'm looking into how difficult this will be to fix and release with `3.1.2`

**Comment by brian-mann** [comment]
Released in [`3.1.2`](https://docs.cypress.io/guides/references/changelog.html#3-1-2).
