### ISSUE TITLE
Type into datetime-local input: time markers not accepted

### ISSUE THREAD

**Issue by cornshuckin2** [cypress-io/cypress#26122]
### Current behavior

Related https://github.com/cypress-io/cypress/issues/22884

Typing into a datetime-local field doesn't support AM/PM time markers. Example, `1959-09-13T10:12:13AM` `yyyy-MM-ddThh:mma` is not accepted as an input. 

Cypress throws the following error when attempting to use time markers 
`
Typing into a datetime input with cy.type() requires a valid datetime with the format YYYY-MM-DDThh:mm or YYYY-MM-DDThh:mm:ss, for example 2017-06-01T08:30. You passed: 2022-03-03T10:11:12AM
`

### Desired behavior

Typing into a datetime-local field allows for AM/PM time markers. This is useful for when needing to specify a date in the future. 

### Test code to reproduce

```js
context("Datetime-Local picker", () => {
  it("insert a date with time marker", () => {
    cy.visit(
      "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_datetime-local"
    );

    cy.get("#iframeResult", { timeout: 10000 })
      .its("0.contentDocument")
      .should("exist")
      .its("body")
      .should("not.be.undefined")
      .then((body) => {
        cy.wrap(body)
          .find("#birthdaytime")
          .clear()
          .type("2022-03-03T10:11:12PM");
      });
  });
});
```

### Cypress Version

12.7

### Node version

18.13.0

### Operating System

macOS 13.2.1

**Comment by lmiller1990** [comment]
I confirmed the issue - I'm tagging this as a feature request. I'll see if I can get some 👀 on this internally. If we decide to move forward with this feature, would you be interested in making a PR to implement it?

**Comment by cornshuckin2** [comment]
> I confirmed the issue - I'm tagging this as a feature request. I'll see if I can get some 👀 on this internally. If we decide to move forward with this feature, would you be interested in making a PR to implement it?

Yea I can get a PR up to remedy this.

**Comment by cornshuckin2** [comment]
After some digging, this can be resolved by simply using 24 hour time in your date object. IE`2023-03-16T18:54` will result as `03/16/2023, 06:54 PM` in the field.
