### ISSUE TITLE
cy.wrap() is causing Cypress to get stucked

### ISSUE THREAD

**Issue by daminebenq** [cypress-io/cypress#26136]
### Current behavior

This video record explains it all...
https://user-images.githubusercontent.com/5144311/225745844-0028968f-c37e-444a-9138-5bb35eee25eb.mp4

<img width="482" alt="image" src="https://user-images.githubusercontent.com/5144311/225746613-bc327421-ec58-43cb-a3f6-735fcaa453db.png">

it gets stuck after arriving to this step when the wrapped function gets stuck:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/5144311/225746486-575cc1b6-1ef4-4004-bec6-a566ae974161.png">

### Test code to reproduce

described above

### Cypress Version

10.8.0 and above

### Node version

14.16.1 and above

### Operating System

macOS and others

**Comment by lmiller1990** [comment]
Hi, looks like there's an infinite loop. Can you share the code for that test? It's difficult to offer any suggestions without a little more information. Thanks!

**Comment by lmiller1990** [comment]
Happy to reopen once we've got more information to continue debugging. Until then, I'll close this, since I don't see any actionable work in Cypress relating to this issue.
