### ISSUE TITLE
MSW with Angular Component Testing: Failed to register a Service Worker

### ISSUE THREAD

**Issue by inigoiparragirre** [cypress-io/cypress#26131]
### Current behavior

For Angular Component Testing, I want to use MSW (Mock Service Worker), using msw request handlers instead of cy.intercept().
The tested component is not working as expected

### Desired behavior

MSW needs to be registered succesfully. But this is what happens:

![component-testing-msw-angular](https://user-images.githubusercontent.com/4726310/225560004-24d18bdc-204a-46f9-982c-953a22d06f60.png)

Steps to reproduce:
- Install msw as dependency.
- Execute 'npx msw init src/'
- Add msw setup inside test.

### Test code to reproduce

I forked the repository cypress-component-testing-apps in https://github.com/inigoiparragirre/cypress-component-testing-apps with an example for AppComponent using MSW (main branch).

### Cypress Version

12.8.1

### Node version

18.14.1

### Operating System

Linux Ubuntu 22.10

**Comment by lmiller1990** [comment]
Hi, perhaps duplicate of this issue in the msw repo: https://github.com/mswjs/msw/issues/744

Looks like someone might have a solution in: https://github.com/cypress-io/cypress/issues/16742

Also related: https://github.com/mswjs/msw/issues/744

**Comment by inigoiparragirre** [comment]
Hi @lmiller1990, this issue is specific to Angular Component Testing. React Component Testing with MSW is working perfectly fine in this repository: [cypress-component-testing-apps]( https://github.com/cypress-io/cypress-component-testing-apps),  so I think the issue is in the configuration files for Webpack in an Angular environment. So not sure about this is duplicated. Thank you!

**Comment by lmiller1990** [comment]
I am not able to get it to work in the other project in the repository - I'm not seeing the same error, but I'm also not getting back the expected response. Which project(s) did you see it working in?

**Comment by lmiller1990** [comment]
Actually, it's working now in my Vite project - I can use msw to intercept and respond to `/blah` as shown here:



![Image](https://user-images.githubusercontent.com/19196536/226230351-caa476ff-9ce9-4999-9d1e-304cc4f49d14.png)

**Comment by lmiller1990** [comment]
Seems Angular specific. The other issue has an Angular example that is also not working: https://github.com/mswjs/msw/issues/744#issuecomment-1351491630 but I got this to work in a simple project (both webpack and Vite).

**Comment by lmiller1990** [comment]
I spent a few hours trying to figure this out but I am still unsure. I suppose it's something to do with how Angular routes publicPath requests, but I'm yet to figure out how/what is different compared to other webpack based toolchains.

**Comment by mct-dev** [comment]
I am having the exact same issue but with NextJs instead of Angular.  Would love to hear if anyone's been able to get this working! :)

**Comment by lydemann** [comment]
I tried with the esbuild builder in Angular 16 and it still went looping when I was fetching the MSW service worker.

**Comment by M-a-c-Carter** [comment]
Well I think this needs to stay open, if the issue is fixed maybe esbuild can be added as an option instead of webpack since angular v17 is now on that. rather not rely on a 3rd party pacakge to use esbuild.
