### ISSUE TITLE
`cy.url` doesn't determine the current URL if it's different from the base one

### ISSUE THREAD

**Issue by Dexx01** [cypress-io/cypress#26132]
### Current behavior

I am testing the integration of two systems through their client side. This implies that my test starts with one site, then through the button I go to another site (using cy.click(), cy.visit() is not my case). To make sure that the redirect is correct, I use the following methods: `cy.url().should('eq', 'https://example.com')`, but Cypress can't find the second URL. I have the next message: `expected '' to include https://example.com`

### Desired behavior

After redirecting to a new address, Cypress successfully detects it and URL checks are successful done.

### Test code to reproduce

My code contains secret information, I can't provide it.

### Cypress Version

12.8.1

### Node version

v18.12.1

### Operating System

macOS 13.0.1

**Comment by nagash77** [comment]
Hi @Dexx01 please review our documentation around [cy.origin](https://docs.cypress.io/guides/guides/cross-origin-testing).  I believe that will point you in the right direction.

**Comment by Dexx01** [comment]
Thanks, it worked for me, everything is great now!
