### ISSUE TITLE
Throw error when exec `cypress run` after update Vite to 4.2.0 version

### ISSUE THREAD

**Issue by uni-zheng** [cypress-io/cypress#26149]
### Current behavior

![image](https://user-images.githubusercontent.com/9986421/226083216-407f3002-1f81-4c61-a0f0-db92d001556e.png)

### Test code to reproduce

https://github.com/uni-zheng/vite-vue2-cypress-test

### Cypress Version

12.8.1

### Node version

16.14.0

### Operating System

macOS 13.2.1

### Other

Before Vite@4.2.0, Cypress with Vite@4.1.4 not working because this issue https://github.com/vitejs/vite/issues/9986#issuecomment-1414907809 .

**Comment by lmiller1990** [comment]
Hi, thanks for the bug report. Fixed in https://github.com/cypress-io/cypress/pull/26139. This will be in the next release, within 2 weeks.

You can use Vite 4.1 in the meantime. Thanks!
