### ISSUE TITLE
Cypress is not able to fully mimic the behavior of my web application

### ISSUE THREAD

**Issue by jnovoadeuna** [cypress-io/cypress#26140]
### Current behavior

As we can see in the video, the current behavior is as follows:

I click a button

A modal opens with the "Loading"

This modal with loading stays infinitely and never loads the content of the modal.

It should be noted that the same test has been done manually and the modal loads correctly, so it is ruled out that it is a problem with the web application under test.

I have tried multiple browsers with Cypress and all get the same behavior. Apparently Cypress is not able to render the content of the modal which should work as the desired behavior.

Another interesting fact: When I continue to interact in the browser that Cypress launches and navigate to open the modal, it doesn't load either, it keeps loading infinitely, so I doubt it's something in my code steps.

https://user-images.githubusercontent.com/125294233/225794978-09dee043-be7d-40a3-8bc8-09045cf12d68.mov

### Desired behavior

As we can see in the video, the desired behavior (Executed manually) It shows the "Loading" modal and after a few seconds it shows the loaded content that corresponds to the inputs to enter the otp code.

The only point that does NOT finish loading the modal is when I run Cypress (cypress open). I have done endless tests, I have put eternal waiting times, I have checked with the development team in charge of this component, I have investigated but I have not obtained any solution.

In my company they are seriously thinking about stopping using Cypress due to said blocker, since the application that I have to Automate is vital for the company.

https://user-images.githubusercontent.com/125294233/225795894-75840c27-c945-4b2c-9ea0-9efd9f07c461.mov

### Test code to reproduce

I just click the button which opens the modal
`private readonly buttonBuyNow = '#payment-data-submit';`
`cy.get(this.buttonBuyNow).click({ force: true });`

then i have a wait

`cy.wait(35000)`

### Cypress Version

12.6.0

### Node version

18.15.0

### Operating System

macOS 13.0

### Debug Logs

```shell
The Cypress logs show absolutely nothing unusual.

The browser console does not show absolutely weird.
```

### Other

If they see it necessary, I can grant test url and credentials since it is in a test environment.

**Comment by jnovoadeuna** [comment]
If they see it necessary, I can grant test url and credentials since it is in a test environment.

**Comment by lmiller1990** [comment]
Hi! Sorry to see you are running into this problem. Have you seen this on other Cypress tests, or just this one? It looks like it's getting stuck on creating a session. What does that step do? Can you share that part of the test, or, ideally, the entire test you've written?

Another thing you could try is running the same test with `DEBUG=cypress:*` as an environment variable. The terminal should show a lot more logging. You could copy and paste the logs here - they might have some useful information to help debug.

**Comment by lmiller1990** [comment]
I wonder if we broke something around sessions in Cypress 12.6. Similar issue: https://github.com/cypress-io/cypress/issues/26147

Can you please try downgrading to Cypress 12.5 and see if the issue persists?

**Comment by jnovoadeuna** [comment]
Hello @lmiller1990, thank you very much for your answer. I have tried different versions of Cypress and still get the same behavior. I have done the test without using cy.session and I still get the same result.

**Comment by jnovoadeuna** [comment]
> ¡Hola! Lamento ver que te estás encontrando con este problema. ¿Ha visto esto en otras pruebas de Cypress, o solo en esta? Parece que se está atascando al crear una sesión. ¿Qué hace ese paso? ¿Puede compartir esa parte de la prueba o, idealmente, la prueba completa que ha escrito?
> 
> Otra cosa que podría intentar es ejecutar la misma prueba con `DEBUG=cypress:*`una variable de entorno. El terminal debería mostrar mucho más registro. Puede copiar y pegar los registros aquí; es posible que tengan información útil para ayudar a depurar.



> Hi! Sorry to see you are running into this problem. Have you seen this on other Cypress tests, or just this one? It looks like it's getting stuck on creating a session. What does that step do? Can you share that part of the test, or, ideally, the entire test you've written?
> 
> Another thing you could try is running the same test with `DEBUG=cypress:*` as an environment variable. The terminal should show a lot more logging. You could copy and paste the logs here - they might have some useful information to help debug.

I really appreciate your help.

It is the first time I see this error, our tests that are run on other websites work correctly, the error only happens with this mobile application and in that specific part, the rest works fine.

I have executed with DEBUG where I see the following error:

```
cypress:launcher:browsers chrome stderr: [27634:27399:0321/075449.647785:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for safebrowsing.googleapis.com failed:
----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=safebrowsing.googleapis.com) -----
ERROR: No matching issuer found +8s
```
Do you think this error is the reason why the modal doesn't finish loading?

I also attach all the log that generated the moment where it fails.

[cypress_debug.log](https://github.com/cypress-io/cypress/files/11028581/cypress_debug.log)

The current code snippet that performs the function of opening the modal is the following:

`  selectSendCodeToEmail(): void {

    cy.wait(4000)
    cy.get(this.buttonBuyNow).click({force: true});
    cy.wait(40000); // I put this wait intentionally to wait for the modal to finish opening... which never opens.
    
    const testStart = new Date();
    cy.get('button').contains(this.buttonSendCodeToEmail).click();
    // get access code
    cy.mailosaurGetMessage(
      Cypress.env('mailosaurServerId'),
      {
        sentTo: Cypress.env('REGISTERED_USER')
      },
      { receivedAfter: testStart }
    ).then(email => {
      let code = email.html.codes[0].value;
      cy.get('input').contains(this.inputAccessCode).type(code);
    });`

**Comment by lmiller1990** [comment]
Thanks for the logs and code, this is useful. Hard to say if that's the error preventing the modal from closing - I think we need more knowledge about your application. 

Next question... what happens when 

```js
cy.get(this.buttonBuyNow).click({force: true});
```

Is executed? Eg - in your app - what happens here? Does it try to authenticate, or maybe a request to a merchant (such as Stripe?) One potential way to solve this would be commenting out the code in your app, bit by bit, until you find the line that is causing the issue. What is the condition in your code that allows the modal to finish showing?

I'm guessing something (maybe an API request or auth request) is triggered, failing when running in Cypress, and timing out. 

If we can figure out what exactly is preventing the code from continuing, we can solve the issue. Happy to keep giving you ideas, but I think to figure out the exact problem, in depth understanding of your code is required. I think we are getting closer.

**Comment by jnovoadeuna** [comment]
> Thanks for the logs and code, this is useful. Hard to say if that's the error preventing the modal from closing - I think we need more knowledge about your application.
> 
> Next question... what happens when
> 
> ```js
> cy.get(this.buttonBuyNow).click({force: true});
> ```
> 
> Is executed? Eg - in your app - what happens here? Does it try to authenticate, or maybe a request to a merchant (such as Stripe?) One potential way to solve this would be commenting out the code in your app, bit by bit, until you find the line that is causing the issue. What is the condition in your code that allows the modal to finish showing?
> 
> I'm guessing something (maybe an API request or auth request) is triggered, failing when running in Cypress, and timing out.
> 
> If we can figure out what exactly is preventing the code from continuing, we can solve the issue. Happy to keep giving you ideas, but I think to figure out the exact problem, in depth understanding of your code is required. I think we are getting closer.

Hello very good evening, an apology for the delay in answering you.

In the current company where I work, I have the role of qa automation and I don't currently have access to the application code itself.

I have spoken with the developers and they tell me that for the modal to be rendered, an initial configuration is sent so that it can initialize it in the SDK and thus be able to render it successfully.

I am also attaching a link to notion where there are the instructions to run my automation project and replicate the error live and so maybe you can help me with the questions you have about this strange behavior with Cypress. Because I did the test with Playwright and it worked correctly, from what I deduce it may be a Cypress issue.

Notion link: *redacted by @lmiller1990*

I'm still waiting for the error, let me know if I can help you a little more.

Thank you very much for your arrangement.

**Comment by lmiller1990** [comment]
Hi -- thanks for the instructions. I removed the notion link, since it's got some potentially sensitive information.

I am running into this error:
![image](https://user-images.githubusercontent.com/19196536/227844419-c5c3a109-d951-41e9-9076-6728462d3c04.png)

**Comment by jnovoadeuna** [comment]
hello. The error that you present at the time of the test, was due to the fact that some credentials of the mail server that we use had already expired. I updated the notion file by updating the environment variables and with the test working again. Apologies. And thanks for removing my Notion link, I missed it

**Comment by lmiller1990** [comment]
I ran the test. I'm seeing this error:

![image](https://user-images.githubusercontent.com/19196536/228113916-159d855d-9a07-4c7c-9ae2-3e1e74038316.png)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/428

**Comment by lmiller1990** [comment]
Can you share this with your dev team and see if they've got any ideas what might cause this? I wonder if it's possible the CDN (looks like AWS CloudFront) is blocking Cypress - some CDNs block automation tools, this could be the case - you might need a rule to make an exception for Cypress?

See if your dev team has any insight relating to this. I do not think there's anything we can do on the Cypress side to make this work without some configuration on your end as well, but happy to go back and forth until we sort this out.

**Comment by lmiller1990** [comment]
I'm  guessing this failure (the 428) is also leading to the following 404 which is required for the modal to show:

![image](https://user-images.githubusercontent.com/19196536/228115581-69865698-8acf-44c0-9422-b827c8b19ffa.png)

PS: If anyone else at Cypress wants to look into this, message me for the notion doc with the credentials to run this locally.

**Comment by jnovoadeuna** [comment]
Thank you so much. I greatly appreciate your great help! I'm in touch with the development team and see how all this turns out.

As soon as I have an update I comment here.

**Comment by astone123** [comment]
I'm going to close this out for now. @jnovoadeuna feel free to leave a comment here when you have an update and the issue will re-open. Thanks!
