### ISSUE TITLE
Component tests fail with React + TS + Vite 4.2.0

### ISSUE THREAD

**Issue by ae9is** [cypress-io/cypress#26153]
### Current behavior

All component tests seem to fail when using React + TS + Vite 4.2.0 (4.1.4 is fine) if the mount command in `cypress/support/component.ts` is defined.

A generic error message is thrown:
```
An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Failed to fetch dynamically imported module: http://localhost:5173/__cypress/src/cypress/support/component.ts

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```

If cypress/support/component.ts is modified to comment out the custom mount comment (`Cypress.Commands.add('mount', mount)`), then the issue does not occur. (Simple tests without using mount() can pass.) With the mount command, all tests error.

### Desired behavior

Component tests using mount ideally should work with Vite 4.2.0

### Test code to reproduce

See: https://github.com/ae9is/cypress-component-testing-apps

This is just a fork of the React + Vite + TS component testing example app https://github.com/cypress-io/cypress-component-testing-apps/tree/main/react-vite-ts modified to bump Cypress to 12.8.1 and Vite to 4.2.0.

### Cypress Version

12.8.1

### Node version

18.12.1

### Operating System

Ubuntu 22.04

**Comment by lmiller1990** [comment]
Yep, please see: https://github.com/cypress-io/cypress/issues/26149#issuecomment-1475437561


Fixed in https://github.com/cypress-io/cypress/pull/26139. This will be in the next release, within 2 weeks. You can use Vite 4.1 in the meantime. Thanks!

I'll leave this open to prevent duplicates, since a lot of people are running into this. Please be patient 🙏

**Comment by ae9is** [comment]
Great, thanks! Sorry about the duplicate, wasn't sure if those were the same issue and wanted to save people some time in case they also ran into this.

**Comment by Ancient-Dragon** [comment]
We get this with vue and vite. It fails the first run then because we have retires we get another error:

`Cannot read properties of undefined (reading 'prevAttempts')
    at replacePreviousAttemptWith (http://localhost:5173/__cypress/runner/cypress_runner.js:167740:40)
    at Object.onRunnableRun (http://localhost:5173/__cypress/runner/cypress_runner.js:167879:11)
    at $Cypress.action (http://localhost:5173/__cypress/runner/cypress_runner.js:157260:28)
    at Runnable.run (http://localhost:5173/__cypress/runner/cypress_runner.js:166040:13)
    at ../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:5173/__cypress/runner/cypress_runner.js:115099:10)
    at http://localhost:5173/__cypress/runner/cypress_runner.js:115225:12
    at next (http://localhost:5173/__cypress/runner/cypress_runner.js:115008:14)
    at http://localhost:5173/__cypress/runner/cypress_runner.js:115018:7
    at next (http://localhost:5173/__cypress/runner/cypress_runner.js:114920:14)
    at http://localhost:5173/__cypress/runner/cypress_runner.js:114986:5
    at timeslice (http://localhost:5173/__cypress/runner/cypress_runner.js:108912:27)`

Cypress version: 12.17.2
Vite version: 4.4.7
Vue version: 3.3.4

**Comment by jennifer-shehane** [comment]
Fixed in https://github.com/cypress-io/cypress/pull/26139. Closing as resolved.

**Comment by SirCameron** [comment]
This is now an issue with Vite 7.2.4 and Cypress 15.9.0.. Anyone else having this problem?
