### ISSUE TITLE
Error when trying to display help for --spec flag

### ISSUE THREAD

**Issue by AmarokSama** [cypress-io/cypress#2615]
### Current behavior:

![error_cypress](https://user-images.githubusercontent.com/14308103/47009832-bb46f500-d13d-11e8-80f0-2a990071f137.PNG)

### Desired behavior:

It should show help for the spec flag or print an error

### Steps to reproduce:

error occure when typing the command `yarn cypress run -s -h`

### Versions

- Cypress: 3.1.0
- Windows 10
- yarn

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
