### ISSUE TITLE
`after:spec` event handler error

### ISSUE THREAD

**Issue by adamalston** [cypress-io/cypress#26150]
### Current behavior

A linting error is shown for the `after:spec` event. I copied this event handler from https://docs.cypress.io/api/plugins/after-spec-api#Delete-the-recorded-video-if-no-tests-retried.

![after:spec error](https://user-images.githubusercontent.com/18297826/226122234-d98ce6a9-2d9d-4ccf-8112-6f2fe1ea6d72.png)

### Desired behavior

I don't expect to see errors for this event based on the type definitions for the functions involved.

```ts
/**
 * Handle Cypress plugins
 */
setupNodeEvents: (on: PluginEvents, config: PluginConfigOptions) => Promise<PluginConfigOptions | void> | PluginConfigOptions | void
```

```ts
interface PluginEvents {
  (action: 'after:run', fn: (results: CypressCommandLine.CypressRunResult | CypressCommandLine.CypressFailedRunResult) => void | Promise<void>): void
  (action: 'after:screenshot', fn: (details: ScreenshotDetails) => void | AfterScreenshotReturnObject | Promise<AfterScreenshotReturnObject>): void
  (action: 'after:spec', fn: (spec: Spec, results: CypressCommandLine.RunResult) => void | Promise<void>): void
  (action: 'before:run', fn: (runDetails: BeforeRunDetails) => void | Promise<void>): void
  (action: 'before:spec', fn: (spec: Spec) => void | Promise<void>): void
  (action: 'before:browser:launch', fn: (browser: Browser, browserLaunchOptions: BrowserLaunchOptions) => void | BrowserLaunchOptions | Promise<BrowserLaunchOptions>): void
  (action: 'file:preprocessor', fn: (file: FileObject) => string | Promise<string>): void
  (action: 'dev-server:start', fn: (file: DevServerConfig) => Promise<ResolvedDevServerConfig>): void
  (action: 'task', tasks: Tasks): void
}
```

### Test code to reproduce

https://docs.cypress.io/api/plugins/after-spec-api#Delete-the-recorded-video-if-no-tests-retried

```ts
import { defineConfig } from 'cypress'
// need to install these dependencies
// npm i lodash del --save-dev
import _ from 'lodash'
import del from 'del'

export default defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
      on('after:spec', (spec, results) => {
        if (results && results.video) {
          // Do we have failures for any retry attempts?
          const failures = _.some(results.tests, (test) => {
            return _.some(test.attempts, { state: 'failed' })
          })
          if (!failures) {
            // delete the video if the spec passed and no tests retried
            return del(results.video)
          }
        }
      })
    },
  },
})
```

### Cypress Version

12.8.1

### Node version

v14.18.3

### Operating System

macOS 12.6.3

### Debug Logs

```shell
N/A
```

### Other

I encountered this error while using a custom `after:spec` event handler. To rule out the possibility of the error being caused by my implementation, I substituted my custom handler with one of the provided handlers from the Cypress documentation. However, the same error persisted, indicating that the issue is not related to my implementation.

**Comment by lmiller1990** [comment]
Hi! Great bug report.

Your code looks fine. I wasn't able to reproduce. I also copy pasted your code as-is into a branch new project, no issues. Do you get any IDE recommendations if you do `on('` ?

Here's what I'm seeing:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/19196536/226260193-9e8c3d17-9e99-4e4c-9df4-3d0a7eb192ff.png">

**Comment by adamalston** [comment]
Yes, the code completions show up.

<img alt="code-completions" src="https://user-images.githubusercontent.com/18297826/226415736-f14538b3-98a1-40c0-9ef0-fe66babf36d7.png" width="500" />

I am using VS Code with TypeScript version 4.9.5. If I downgrade TypeScript to version 4.2.4, the error still shows up.

**Comment by adamalston** [comment]
I am using VS Code with TypeScript version 4.9.5. If I downgrade TypeScript to version 4.2.4, the error still shows up.

**Comment by lmiller1990** [comment]
Ah, I reproduced it. See below. It does not like `return del(...)`. What about calling `del` then returning null or undefined? Do you need to return the value of `del()` from the `after:run` task?



![Image](https://user-images.githubusercontent.com/19196536/226524799-c1c3c9c4-0103-4ff9-a398-20498169840e.png)

**Comment by adamalston** [comment]
This code belongs to Cypress (since it came from https://docs.cypress.io/api/plugins/after-spec-api#Delete-the-recorded-video-if-no-tests-retried), not me, so I can't say what's needed and/or expected. I think it's best if the Cypress team defines that.

The `PluginEvents` type says this function should return `void | Promise<void>`. I think Cypress should clarify what is expected here either via the interface or the examples in their documentation.

```tsx
interface PluginEvents {
  (action: 'after:run', fn: (results: CypressCommandLine.CypressRunResult | CypressCommandLine.CypressFailedRunResult) => void | Promise<void>): void
  (action: 'after:screenshot', fn: (details: ScreenshotDetails) => void | AfterScreenshotReturnObject | Promise<AfterScreenshotReturnObject>): void
  (action: 'after:spec', fn: (spec: Spec, results: CypressCommandLine.RunResult) => void | Promise<void>): void
  (action: 'before:run', fn: (runDetails: BeforeRunDetails) => void | Promise<void>): void
  (action: 'before:spec', fn: (spec: Spec) => void | Promise<void>): void
  (action: 'before:browser:launch', fn: (browser: Browser, browserLaunchOptions: BrowserLaunchOptions) => void | BrowserLaunchOptions | Promise<BrowserLaunchOptions>): void
  (action: 'file:preprocessor', fn: (file: FileObject) => string | Promise<string>): void
  (action: 'dev-server:start', fn: (file: DevServerConfig) => Promise<ResolvedDevServerConfig>): void
  (action: 'task', tasks: Tasks): void
}
```

**Comment by lmiller1990** [comment]
I made a PR correcting this in the docs: https://github.com/cypress-io/cypress-documentation/pull/5134

We should not have code that does not compile in our documentation. I wonder if we can lint for this.

We can also look to make a PR to improve the type definitions as well, but I think we should get the docs in line with what's in production right now before we do that.

**Comment by lmiller1990** [comment]
I updated the docs. We can have a PR to improve the types, too. For now, I don't think there's a bug per-se - the docs are now compatible with the types, so I'll close this one.

**Comment by adamalston** [comment]
@lmiller1990 I think there's one more issue in the doc. The code comment says:
> `del()` returns a promise, so it's important to return it to ensure deleting the video is finished before moving on

However, the code is not returning `del()`. I think that part of the doc needs to be updated as well. and maybe some of the other code comments.

**Comment by lmiller1990** [comment]
Good point. I made a quick update ➡️  https://github.com/cypress-io/cypress-documentation/pull/5144

We need to reaudit the entire docs soon, to make sure it uses the latest versions of everything.
