### ISSUE TITLE
Turn off video recording by default

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#26157]
### What would you like?

Cypress has always [recorded video by default](https://docs.cypress.io/guides/guides/screenshots-and-videos#Videos) by default during `cypress run`. Video recording can be turned off by users by updating their configuration file or passing in an environment variable to change config at runtime to set `video: false`.

We'd like to have `video: false` set by default for all users, so that video recording is turned off by default. Any user can set `video: true` to record video.

### Why is this needed?

Videos are oftentimes not the best source for debugging Cypress tests that ran in a non-local environment because in some situations videos can be choppy or unavailable (especially in under resourced machines). Videos are also not as useful as the feature to [capture and display all logs](https://github.com/cypress-io/cypress/issues/448) for debugging that our team is working on. Additionally recording video on lower resourced machines impacts the performance of tests, resulting in slower runtime.

### Other

Release and implementation strategy has yet to be determined, but this could be result in a breaking change for existing users.

**Comment by margarita-markova** [comment]
Also same will be helpful for other artifacts. I want to have a turn on/turn off option for every artifact: screenshots, videos, report files, etc.

**Comment by samvloeberghs** [comment]
> Additionally recording video on lower resourced machines impacts the performance of tests, resulting in slower runtime.

FYI: this is the main reason we would like this feature.
The compression part is the slow part on typical CI/CD machines like those of Github actions.
We would only turn it on in case we need to debug during CI/CD flows only. 

Does an option exist to turn it on dynamically with an flag, that would be nice as well. Using ENV variables?

**Comment by MDG-JHowley** [comment]
> Does an option exist to turn it on dynamically with an flag, that would be nice as well. Using ENV variables?

```
CYPRESS_video=false
CYPRESS_videoCompression=false
```

ref: https://docs.cypress.io/guides/references/configuration#Environment-Variables

**Comment by jennifer-shehane** [comment]
We have made the decision to have `video` set to `false` for all users by default. This will go out in a breaking change (likely v13) and will be released alongside our feature to [capture and display all logs](https://github.com/cypress-io/cypress/issues/448) for users recording to the Cypress Cloud.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by jennifer-shehane** [comment]
Released in [Cypress 13.0.0](https://docs.cypress.io/guides/references/changelog#13-0-0).
