### ISSUE TITLE
Cypress log out after 3DS check for checkout.com

### ISSUE THREAD

**Issue by umerzaman** [cypress-io/cypress#26165]
### Current behavior

Im writing a test for the payment section on Cypress after clicking on the payment button page goes to the external URL. e.g. from http://localhost:64574/ to "https://3ds2-sandbox.ckotech.co/interceptor/3ds_ibgzskqjjfqevj4w3gwmdptp4m/device-information"

after completing the 3ds check the page to redirect back and went to the login page. I'm wrapping my code in cy.session you can see below.

```js
beforeEach(() => {
  cy.fixture("example.json").then(function (data) {
    configdata = data;
  });
  cy.fixture("3dsCard.json").then(function (data) {
    configdata3DS = data;
  });
  cy.session("session", () => {
    cy.visit(Cypress.env("localURL"));
    cy.get("#onetrust-accept-btn-handler").click();
    cy.get("#VoucherNo").type("myvoucher-no");
    cy.get("#PinCode").type("my-pin");
    cy.get(".btn").click();
    cy.getCookie("ASP.NET_SessionId").should("exist"),
      {
        cacheAcrossSpecs: true,
      };
  });
});

```

### Desired behavior

After the 3ds redirect check should remain login and need to go on confirmation.

### Test code to reproduce

https://www.youtube.com/watch?v=Fohrq5GZSD8

### Cypress Version

^12.8.0

### Node version

16.15.1

### Operating System

windows 11

**Comment by nagash77** [comment]
Hi @umerzaman have you read up on using [cy.origin](https://docs.cypress.io/guides/guides/cross-origin-testing) to do cross origin testing?  

We also have extensive documentation on using [cy.session](https://docs.cypress.io/api/commands/session).

Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by umerzaman** [comment]
@nagash77  yeah, I had a look at cy.origin documentation there is nothing to test on another origin it will automatically redirect me back. but when I get back session is changed.

**Comment by AtofStryker** [comment]
Hi @umerzaman. Thank you for opening an issue. Would you be able to provide a working reproduction repository that I can run on my machine to verify the issue? The example provided is incomplete and the test code to reproduce seems to just be the explainer on `cy.origin`.

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
