### ISSUE TITLE
Add a way to disable Cypress's script injection for certain HTML pages

### ISSUE THREAD

**Issue by sethfowler** [cypress-io/cypress#2617]
### Current behavior:

Cypress automatically injects scripts into all HTML pages. These scripts exist to e.g. set `document.domain` to prevent iframes from becoming cross-origin.

It would be helpful to be able to disable this for certain URLs. These scripts can cause problems in several ways:
 - The script is injected before `<!DOCTYPE>`, which prevents the doctype node from taking effect. (`document.doctype` is null.) We need to be able to set the doctype reliably, alas.
 - The script's presence alters the structure of the DOM, which breaks code that depends on a certain structure. (That's unfortunately unavoidable for our app.)
- Setting `document.domain` throws in a sandboxed iframe.

### Desired behavior:

Ideally there'd be a way to disable this via e.g. `cy.route()` or `cy.server()`. We currently have to work around this in our app itself in a pretty brittle way.

### Versions

Cypress 3.1, macOS 10.14, Chrome 69.

**Comment by sethfowler** [comment]
The documents in question contain only a `<!DOCTYPE>` declaration. (That’s because they’re programmatically populated.) Perhaps that’s a case that the existing algorithm doesn’t account for?

The fact that the script gets injected at an unexpected place is just one aspect of the problem, though. Ideally we’d be able to just disable the script injection altogether when necessary.

**Comment by schmidtk** [comment]
@brian-mann I encountered this because [our app](https://master-branch-opensphere-ngageoint.surge.sh/) omits `html`, `head`, and `body` in its `index.html` for simplicity. These tags aren't required by spec, but when absent from the page Cypress will insert the `document.domain` script before `<!DOCTYPE>`.

**Comment by jennifer-shehane** [comment]
I have created a repo to demonstrate this behavior here: https://github.com/jennifer-shehane/empty-doctype-html

### When no `<html>`

#### Application html

```html
<!DOCTYPE>
```

#### HTML in Cypress (WRONG)

```html
<head> 
  <script type='text/javascript'> document.domain = 'localhost'; </script> 
</head>
<!DOCTYPE>
```

### When `<html>`

#### Application html

```html
<!DOCTYPE>
<html>
</html>
```

#### HTML in Cypress (CORRECT)

```html
<!DOCTYPE>
<html> 
  <head> 
    <script type='text/javascript'> document.domain = 'localhost'; </script> 
  </head>
</html>
```

### Failing test in repo

<img width="437" alt="screen shot 2019-01-15 at 2 30 45 pm" src="https://user-images.githubusercontent.com/1271364/51166512-30a79a80-18d2-11e9-80d4-6c0099ca7b8f.png">
