### ISSUE TITLE
why i use click() method to download ,the file name is download located in cypress/downloads?i want the other name in the same dir

### ISSUE THREAD

**Issue by Danny5487401** [cypress-io/cypress#26189]
### Current behavior

i run the code in docker using node-18.14.1-chrome-111.0.5563.64-1-ff-111.0-edge-111.0.1661.43-1 as my base image

### Desired behavior

hope to use the filename in content-disposition as do in chrome.

### Test code to reproduce

just to click to download the pdf 
```shell
root@hr-staging-test-everyday-1679468340-4cdmh:/work/cypress/downloads# ls
download
```

### Cypress Version

9.7.0

### Node version

v18.14.1

### Operating System

Linux 976f34065b76 4.4.0-140-generic #166~14.04.1-Ubuntu SMP Sat Nov 17 01:52:43 UTC 2018 x86_64 GNU/Linux

### Other

no

**Comment by nagash77** [comment]
Hi @Danny5487401 Can you please elaborate on what you are trying to do and why?

**Comment by Danny5487401** [comment]
it is ok right now because of locale for Chinese.
```
[bridge]➜  ~ docker exec -it 1e0f5e0d52e3 bash
root@1e0f5e0d52e3:/work# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
root@1e0f5e0d52e3:/work# locale -a
C
C.UTF-8
POSIX
```

i changed to C.UTF-8,then fixed.
