### ISSUE TITLE
ACI - Runs page empty state tour/slideshow

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#26184]
Add an empty state tour/slideshow to the Runs page

Clickup - https://app.clickup.com/t/18033298/PM-2889

*edits below by @lmiller1990* according to ClickUp:

> Empty states
> Style should match that of Debug

It looks like this is still marked as "building": https://app.clickup.com/t/18033298/DESIGN-1526. For estimates, assume it's similar to Debug - you can use the existing components and it'll just be a static "slideshow" of images. I found a [loom](https://www.loom.com/share/a7507984950d4aa99596e2d0dd9ef9e9) demo  in  the #initiative-app-runs channel, but I'm not sure if this 100% locked in.

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/26184?planning-poker) with Zenhub @astone123 @jordanpowell88 @marktnoonan @mike-plummer @warrensplayer

**Comment by warrensplayer** [comment]
Moving out of this sprint and will put out for estimation when the design is complete.

**Comment by warrensplayer** [comment]
Merging this work in with https://github.com/cypress-io/cypress/issues/26181
