### ISSUE TITLE
`after:run` or `after:spec` is not able to read the custom command method and failing to execute my api call code

### ISSUE THREAD

**Issue by bheemaanilconvex** [cypress-io/cypress#26185]
### Current behavior

getting below error.. 
I'm using 12.8.1 version 

```bash
TypeError: Cannot read properties of undefined (reading 'postToSlack')
    at Function.ApiCypressUtils.postToSlackChannel (/Users/anil.bheema/Documents/workspace/convex/e2e_tests/cypress/orca/cypress/src/utilities/api-cypress.utils.ts:7:12)
    at /Users/anil.bheema/Documents/workspace/convex/e2e_tests/cypress/orca/cypress.reg.config.ts:77:34
    at step (/Users/anil.bheema/Documents/workspace/convex/e2e_tests/cypress/orca/cypress.reg.config.ts:33:23)
    at Object.next (/Users/anil.bheema/Documents/workspace/convex/e2e_tests/cypress/orca/cypress.reg.config.ts:14:53)
    at /Users/anil.bheema/Documents/workspace/convex/e2e_tests/cypress/orca/cypress.reg.config.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/anil.bheema/Documents/workspace/convex/e2e_tests/cypress/orca/cypress.reg.config.ts:4:12)
    at Object.handler (/Users/anil.bheema/Documents/workspace/convex/e2e_tests/cypress/orca/cypress.reg.config.ts:74:44)
    at RunPlugins.invoke (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:183:25)
    at /Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at RunPlugins.execute (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:164:21)
    at EventEmitter.<anonymous> (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:56:12)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:26)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/anil.bheema/Library/Caches/Cypress/12.8.1/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at emit (node:internal/child_process:944:14)
```

### Desired behavior

should not throw error perform my action 

### Test code to reproduce

 ```js
 
 on("after:run", async (results) => {
                if (results) {
                    try {
                        apiUtils.postToSlackChannel(
                            "ORCA Cypress Automation: \n" +
                            
                        );
                    } catch (error) {
                        console.log(error)
                    }
                }
            });
            return config;
        },


calling 
  static postToSlackChannel(text: string) {
        cy.postToSlack(text);
    }
```

### Cypress Version

12.8.1

### Node version

v19.2.0

### Operating System

macOd 13.2.1 (22D68)

**Comment by lmiller1990** [comment]
Hi!

I think I see the problem. It looks like this is defined in your `cypress.config.js`.

```js
on("after:run", async (results) => {
  apiUtils.postToSlackChannel()
}
```

This runs in Node.js - not the browser. [Docs](https://docs.cypress.io/api/plugins/after-run-api).

> This code is part of the [setupNodeEvents](https://docs.cypress.io/guides/tooling/plugins-guide#Using-a-plugin) function and thus executes in the Node environment. **You cannot call Cypress or cy commands in this function**, but you do have the direct access to the file system and the rest of the operating system.

I'm assuming that 

```js
static postToSlackChannel(text: string) {
  cy.postToSlack(text);
}
```

Is in your `cypress/support/commands.ts` file. Those are loaded in the browser, on the `cy` object. If you need to access `postToSlack` in both a browser and on Node.js, what you could is put it in separate file, and import it. Eg 

```ts
// shared.ts
import fetch from 'cross-fetch'

export function postToSlack(text: string) {
  // ensure this code works on the browser and in Node.
  // eg cross-fetch: https://www.npmjs.com/package/cross-fetch
  fetch(...) // request
}
```

Make sure that works in both a browser and Node.js. Then in `commands.ts`

```ts
import { postToSlack } from './shared'

Cypress.Commands.add('postToSlack', postToSlack)
```

And in `cypress.config.ts`:

```ts
import { defineConfig } from 'cypress'
import { postToSlack } from './cypress/commands/shared'

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      on("after:run", async (results) => {
        await postToSlack(results)
      })
    }
  }
})
```

You might need to rework the code a bit. Basically, `setupNodeEvents` (and everything in `cypress.config.ts` is in Node.js - things like `cy.get()`, and your custom commands, are in the browser, so you cannot access them using `cy`. You can extract a function to share the functionality.

Also worth remembering:

> When running via cypress open, the after:run event only fires if the [experimentalInteractiveRunEvents flag](https://docs.cypress.io/guides/references/configuration#Experiments) is enabled.

**Comment by lmiller1990** [comment]
I don't think there's a bug here, just a bit of confusion about what runs in Node.js vs a browser. Happy to help and continue advising you, but since there's no bug in Cypress from what I can see, I'll close this. Thanks!

**Comment by bheemaanilconvex** [comment]
thanks @lmiller1990 for the suggestion, just looking at your comment now...will try and get back to you

**Comment by bheemaanilconvex** [comment]
@lmiller1990 can you please help me on this, something I'm doing silly
Unfortunately,  still getting issue, not sure what I'm making the mistake
` ReferenceError: Cypress is not defined
    at /Users/e2e_tests/cypress/orca/cypress.reg.config.ts:79:47 `
    
  

Custom Command
```
import {postToSlackApi} from "@utils/api-cypress.utils";

Cypress.Commands.add('postToSlack', postToSlackApi)
```

and in my Utilities folder 
``` export class ApiCypressUtils {

    static async postToSlackChannel(text: string) {
        cy.postToSlack(text);
    }
}

export function postToSlackApi(text: string) {
    cy.api({
        method: "POST",
        url: Cypress.env('slack')["url"],
        headers: {"Content-type": "application/json"},
        body: {text},
    }).then((res) => {
        cy.log("Status : " + res.statusText);
    });
}
```

and in my config file 

```    
on("after:run", async (results) => {
                await apiUtils.postToSlackChannel(
                    "ORCA Cypress Automation: \n" +
                     
                );
            })

```

and same code is working absolutely fine. when I call it in

```
after(function () {
    apiUtils.postToSlackChannel(  "ORCA Cypress Automation: \n" +
                     
                );
            })`
```

**Comment by lmiller1990** [comment]
You cannot use `cy` or `Cypress` in code that runs in `cypress.config.js`. Those are only in the browser, for example in a spec file (`cy.js`) or `commands.js` or `support.js` (those get bunded in with your spec file, when it runs in the browser).

If you want to do something using `after:run` in your `cypress.config.js` file using `setupNodeEvents`, it won't be able to use `Cypress` or `cy`. So, if you want to make a request using the`postToSlackChannel` method, it'll need to use something like `node-fetch`, `cross-fetch` or `axios`, which are HTTP libraries that work in both Node.js and in a browser. I'd recommend rewriting your `postToSlackChannel` to use one of those, maybe `axios`, so something like:

```js
import axios from 'axios';

export function postToSlackApi(url: string, text: string) {
  return axios.post(url, {
    headers: {"Content-type": "application/json"},
    body: {text},
  })
}
```

Register:

```js
import { postToSlackApi } from './utils'

Cypress.Commands.add('postToSlackApi', postToSlackApi)
```

When you call this, you'll need to pass in the `url`. In a spec, you can do:

```js
cy.postToSlackApi(Cypress.env('slack')['url']
```

But in `cypress.config.js`, you cannot access `Cypress` (browser only!) but you could do something like `process.env`:

```js
import { postToSlackApi } from './utils'

setupNodeEvents(on, config) {
  on("after:run", () => {
    postToSlackApi(process.env.slack.url, 'blah')
  })
})
```
