### ISSUE TITLE
websocket testing

### ISSUE THREAD

**Issue by ivanhara** [cypress-io/cypress#26190]
### Current behavior

cypress is not working with websocket
![image](https://user-images.githubusercontent.com/108190964/227140113-dc97d468-dfc8-4a0d-a561-e5e9b7523352.png)

### Desired behavior

cypress to work with that or update your documentation here 
https://docs.cypress.io/faq/questions/general-questions-faq#We-use-WebSockets-will-Cypress-work-with-that

### Test code to reproduce
```js
  it('websocket test', () => {
    cy.intercept({ resourceType: /websocket/ }).as('ws')
    cy.visit('https://www.twitch.tv/')
    cy.wait('@ws')

  });
```

### Cypress Version

12.8.1

### Node version

v16.15.1

### Operating System

Windows 10 Pro Version	10.0.19044 Build 19044

**Comment by lmiller1990** [comment]
Hi. My understanding of that part of the docs is that you can use Cypress to test applications _using_ websockets in a seamless manner. When testing applications using websockets, the general strategy is either test against the result of the websocket call (eg, did something change on the page) or if you need fine grained control, either 

1. set up your database/application in the way you want and test against that or 
2. set up a websocket server and use something like `cy.task` to push events to manipulate what it does (this will make your test more deterministic)
3. stub/mock the `window.WebSocket` constructor's `onmessage` to stream whatever you like over it.

In general, Cypress assumes you control the application you are testing. If you can explain your use case, I can make some recommendations.

I will double check if this should be working, but my understand is it you won't be able to listen in for the websocket stream using `cy.intercept()`. The documentation for `cy.intercept()` doesn't make this clear, though, so let me clarify.  Related: https://github.com/cypress-io/cypress/issues/2492

**Comment by ivanhar** [comment]
![image](https://user-images.githubusercontent.com/34136871/227716091-be99db70-38f3-4b8a-940c-7558bb3e69b4.png)
i will use https://websocketstest.com/ as an example. 
I need to verify there are messages send/received from this 3rd party server, containing the word 'time' 
I don't have to mock the server, I don't need to connect explicitly via Cypress. Only check the messages.

**Comment by lmiller1990** [comment]
I don't think we support intercepting ws yet - just http requests.

> I don't have to mock the server, I don't need to connect explicitly via Cypress. Only check the messages

If you just need to watch a third party web socket, and not make any assertions against the actual page or even use a web browser, perhaps a simple script using something like Node.js or Python would be a better option? 

We generally don't recommending [testing third parties](https://docs.cypress.io/guides/references/best-practices#Visiting-external-sites), unless the behavior is essential to your app, in which case we'd generally recommend asserting the impact of the web socket on your page.

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
