### ISSUE TITLE
Cypress server mock "intercept" usage times out with "wait()"

### ISSUE THREAD

**Issue by erkanisuf** [cypress-io/cypress#26199]
### Current behavior

I cant find solution for this issue it times out all the time.  I checked other threads but yet not a clean solution. 

Version: "cypress": "^12.8.1",

```js
 beforeEach(() => {
        cy.intercept(
            {
                method: "POST",
                url: "/isActive",
                query: {
                    email: "asdff@email.com",
                },
            },
            "false"
        ).as("isActive");
        cy.intercept("POST", "/", "djhashjdsahjdashjda").as("login");
        cy.intercept("POST", "/user/current", fakeData).as("current");
    });
    it("passes", () => {
        cy.wait("@isActive");
        cy.visit("http://localhost:8085/ui/login");
        cy.get("input[type=text]").type("secretname").trigger("change");
        cy.get("#password").type("secretpasw").trigger("change");
        cy.get("input[type=submit]").click();
cy.wait(["@isActive","@login","@current"])
        cy.contains("Random text");
    });
 ```   
<img width="666" alt="Screenshot 2023-03-23 at 19 21 24" src="https://user-images.githubusercontent.com/63913743/227285930-8abee363-fe1e-46fa-b82e-8cb57094f3d6.png">

    

### Desired behavior

It should not time out.

### Test code to reproduce

```
beforeEach(() => {
cy.intercept(
{
method: "POST",
url: "/isActive",
query: {
email: "[asdff@email.com](mailto:asdff@email.com)",
},
},
"false"
).as("isActive");
cy.intercept("POST", "/", "djhashjdsahjdashjda").as("login");
cy.intercept("POST", "/user/current", fakeData).as("current");
});
it("passes", () => {
cy.wait("@isActive");
cy.visit("http://localhost:8085/ui/login");
cy.get("input[type=text]").type("secretname").trigger("change");
cy.get("#password").type("secretpasw").trigger("change");
cy.get("input[type=submit]").click();
cy.wait(["@isActive","@login","@current"])
cy.contains("Random text");
});
```

### Cypress Version

12.8.1

### Node version

16.14.0

### Operating System

macOS 13.2

### Debug Logs

```shell
at cypressErr (http://localhost:8085/__cypress/runner/cypress_runner.js:154824:18)
    at Object.errByPath (http://localhost:8085/__cypress/runner/cypress_runner.js:154879:10)
    at checkForXhr (http://localhost:8085/__cypress/runner/cypress_runner.js:141777:92)
    at <unknown> (http://localhost:8085/__cypress/runner/cypress_runner.js:141800:28)
From previous event:
    at whenStable (http://localhost:8085/__cypress/runner/cypress_runner.js:146742:65)
    at <unknown> (http://localhost:8085/__cypress/runner/cypress_runner.js:146183:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/1-getting-started/todo.cy.js:92:11)
```

**Comment by josephzidell** [comment]
I wonder if is this the same issue I'm experiencing where on a dev build, Cypress intercepts correctly, but on a prod build Cypress does not. Also, this issue goes away with HMR, if after running it once (and failing), you resave a file, triggering Cypress' HRM causing the test to rerun. In that scenario, it intercepts even when the frontend is a prod build.

**Comment by lmiller1990** [comment]
It looks like the POST request is never triggered, and so it's waiting to intercept a request that never occurs. Is there any way to strip down your code and provide something I can run?

It's hard to provide much more advice without seeing the code for the app. If you open the network tab, do you see that request?

**Comment by erkanisuf** [comment]
I changed the first url to:
`/isActive?*`

And then re run the cypress interface and it started to work. No idea why

**Comment by lmiller1990** [comment]
Strange! Anyway, glad you found a fix.
