### ISSUE TITLE
Cypress hangs if procps is not installed

### ISSUE THREAD

**Issue by chabb** [cypress-io/cypress#26193]
### Current behavior

On a linux distribution, the doc states that you do not need to install procps, but cypress will hang at the end of test run if it's not installed

### Desired behavior

I had to install to make cypress works on docker

### Test code to reproduce

-

### Cypress Version

12.8.1

### Node version

16.16.0

### Operating System

debian

**Comment by nagash77** [comment]
Hi @chabb Im sorry to hear you are having issues running Cypress.  Unfortunately you have not provided enough information for us to investigate further.  I am closing this issue for the time being.  Please feel free to comment on this issue with reproduction steps and we can reopen and investigate.
