### ISSUE TITLE
Enable users to turn off web security

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#262]
Chrome gives us the ability to turn off origin security (used specifically for testing purposes). Additionally we can turn of https -> http request restrictions.

While this will *not* be a cross browser fix, it will work in both headed and headless modes, which could provide users a temporary workaround in the case of a Cypress bug, or a permanent workaround in other situations.

There is an inherent restriction in Cypress that a single test can never span across two different **super domains*. Different subdomains are okay, different superdomains are not.

It's possible such as the case with single-sign-on (SSO) that users may need this behavior. While there are generally always work-arounds in Cypress-land, many users immediately hit this barrier and assume Cypress does not work.

Therefore this option could also be helpful for those situations.

We'll likely expose this in `cypress.json` as something like `{ chromeWebSecurity: false }`.

**Comment by brian-mann** [comment]
Fixed in [`0.17.7`](https://github.com/cypress-io/cypress/wiki/Changelog#0177-10122016).

**Comment by elgubenis** [comment]
this does not work when running headless, is that a bug? or is there some place to define it for the headless runner?

**Comment by elgubenis** [comment]
i tried running
```sh
$ cypress ci -c chromeWebSecurity=false
```
but it did not work either

**Comment by Reimann-bitcoin** [comment]
Does this work for Chromium? or do you have to do
{
chromiumWebSecurity: false 
}
and also this cypress.json should be in home/me/cypress/integration/cypress.json correct?

Thanks
