### ISSUE TITLE
Page content error after login

### ISSUE THREAD

**Issue by matus1331** [cypress-io/cypress#26201]
### Current behavior

Hey. Hey,
I'm testing the Siebel app that's inside the VPN. I am able to open the login page enter username and password and click on the login button. The cypress runner log shows that a page load is in progress and this is where the problem occurs. A white page is displayed with no content, only the loading wheel is visible.

![image](https://user-images.githubusercontent.com/22473674/227307337-9bf77d08-2585-4f73-b40b-03781f61e139.png)

I tried the following options in cypress.config.ts
modifyObstructiveCode: true/false
experimentalModifyObstructiveThirdPartyCode: true/true,

None of them helped

### Desired behavior

The expected behavior is that the page content is displayed.
Manual login displays the page with full content, it only happens when cypress is running in open or run mode and the page is not displayed

### Test code to reproduce
```js
describe("Open siebel", () => {
  Cypress.on("uncaught:exception", (err, runnable) => {
    return false;
  });
  it("Siebel", function () {
    const url = "XXX"; // cant share this URL
    cy.visit(url);
    cy.get('[name="SWEUserName"]').type("username");
    cy.get('[name="SWEPassword"]').type("passwrod");
    cy.contains("Přihlášení").click({ force: true });
    cy.wait(7000);
    cy.url().should("contain", "something");
    cy.wait(25000);
    cy.screenshot("Siebel");
  });
});


```
### Cypress Version

12.7.0

### Node version

v18.14.1

### Operating System

Win 10

**Comment by AtofStryker** [comment]
Hi @matus1331. Thank you for opening an issue. Are you able to share some type of reproduction repository that we can run on our end to reproduce the issue? If not, have you tried [experimentalSkipDomainInjection](https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection)?

**Comment by matus1331** [comment]
> Hi @matus1331. Thank you for opening an issue. Are you able to share some type of reproduction repository that we can run on our end to reproduce the issue? If not, have you tried [experimentalSkipDomainInjection](https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection)?

Unfortunately I can't provide anything to help you reproduce the error. I understand that this is not ideal.

So I tried to set experimentalSkipDomainInjection. I have moved forward gently but only to another error. 
From what I've gathered it seems that cypress is not ideal for testing CRM applications.

In the experimentalSkipDomainInjection documentation there is an example of salefroce which is a CRM and my problem is the Siebel application which is also a CRM.  So I decided not to force cypress to do something it doesn't like and not to use it.

Sad story :)

Ticket can be closed
Thank you

**Comment by AtofStryker** [comment]
@matus1331 I am sorry to hear that there were issues using cypress with your CRM applications. I have tested CRM applications with cypress in the past, and it can be difficult to get the configuration dialed in. If there are other issues we can help with, including this one if you are able to provide a reproduction at some point, let us know and we will be more than happy to help!
