### ISSUE TITLE
Component Testing: `typescript ^=5.0.0` support

### ISSUE THREAD

**Issue by OrbisK** [cypress-io/cypress#26204]
### Description

When I setup component testing typescript 5 is not detected as typescript.

### URL of Issue(s)

https://docs.cypress.io/guides/component-testing/vue/quickstart

### Steps to replicate

```shell
npm i typescript -D
npx cypress open
```

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by OrbisK** [comment]
![image](https://user-images.githubusercontent.com/37191683/227242941-4820520f-02e7-4f6d-93cb-f17eef29321f.png)

**Comment by lmiller1990** [comment]
Related: https://github.com/cypress-io/cypress/issues/26148

Might be fixed in https://github.com/cypress-io/cypress/pull/26173

**Comment by marktnoonan** [comment]
I'm going to re-open this one, I was [setting up CT](https://github.com/TechIsHiring/techishiring-website/pull/140) in a Next.js project for a friend this weekend and TS 5 was not detected as valid:

![Screenshot 2023-05-16 at 10 10 34 AM](https://github.com/cypress-io/cypress/assets/8340719/579e265b-7ad5-414f-9f41-d6e1725ec9bc)

I just double checked against develop and it was the same. #26413 added support for this so I was surprised.

To reproduce: clone https://github.com/TechIsHiring/techishiring-website and attempt to setup component testing (you may need to remove the CT config if my PR was already merged there).

**Comment by mike-plummer** [comment]
In `packages/scaffold-config/src/dependencies.ts`, Typescript version string needs to have extra quotes removed:

`'^=3.4.0 || ^=4.0.0' || '^=5.0.0'`
should be
`'^=3.4.0 || ^=4.0.0 || ^=5.0.0'`
