### ISSUE TITLE
Cypress Component Testing: No spy for Angular Component that uses a Subject as an @Output property 

### ISSUE THREAD

**Issue by Waterstraal** [cypress-io/cypress#26213]
### Current behavior

It is possible to use a Subject as an @Output property in Angular. However, Cypress doesn't register a spy for it. This means we can't do assertions on those properties.

### Desired behavior

Cypress should register a spy for @Output Subjects.

### Test code to reproduce

```typescript
import {Component, EventEmitter, Output} from "@angular/core";
import {CommonModule} from "@angular/common";
import {Subject} from "rxjs";

@Component({
  selector: 'app-subject-as-output',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button (click)="eventEmitter.emit('Some value on the EventEmitter')">Emit a value on an EventEmitter</button>
    <button (click)="subject.next('Some value on the subject')">Emit a value on a Subject</button>
  `,
})
export class SubjectAsOutputComponent {
  @Output() eventEmitter: EventEmitter<string> = new EventEmitter<string>();
  @Output() subject: Subject<string> = new Subject<string>();
}

describe(`${SubjectAsOutputComponent.name}`, () => {
  it(`should render a ${SubjectAsOutputComponent.name}`, () => {
    cy.mount(SubjectAsOutputComponent, {autoSpyOutputs: true});

    cy.get('button').click({ multiple: true });

    cy.get('@eventEmitterSpy').should('have.been.calledWith', 'Some value on the EventEmitter');
    
    // This fails: could not find a registered alias for: @subjectSpy
    cy.get('@subjectSpy').should('have.been.calledWith', 'Some value on the subject'); 
  });
});
```

### Cypress Version

12.8.1

### Node version

18.14.2

### Operating System

Win 10

### Debug Logs

```shell
index-da5ba0a6.js:104176 CypressError: `cy.get()` could not find a registered alias for: `@subjectSpy`.
Available aliases are: `eventEmitterSpy`.
```

**Comment by jordanpowell88** [comment]
Hey @Waterstraal thank you for the issue. With the introduction of `signals` and how `Output()`s are going to be handled in Angular moving forward, we as a team need to do some investigation into how we want to support `outputs`.

With that being said `autoSpyOutputs` is currently an experimental feature. Adding support for what you are requesting would have some tradeoffs as we would have no way of supporting this feature in Angular 13. We will explorer deeper and try to provide a clearer path forward

**Comment by Waterstraal** [comment]
Thanks for the reply @jordanpowell88. To clarify: even without `autoSpyOutputs` is is impossible to spy on output Subjects.

**Comment by jordanpowell88** [comment]
> Thanks for the reply @jordanpowell88. To clarify: even without `autoSpyOutputs` is is impossible to spy on output Subjects.

Nope not at all. You would do something like the following:


```ts
it('should respond to onClick event', () => {
  cy.mount(ButtonComponent, {
    componentProperties: {
      subject: {
        next: cy.spy().as('onButtonClickSpy'),
      } as any,
    },
  });
  cy.get('button').click();
  cy.get('@onButtonClickSpy').should('have.been.called');
});

**Comment by Waterstraal** [comment]
@jordanpowell88 I did not know this, thanks! :)
