### ISSUE TITLE
Application stops running at same point in all runs and displays 'Your tests are loading' for infinite time 

### ISSUE THREAD

**Issue by sonajoseph96** [cypress-io/cypress#26223]
### Current behavior

My application (hosted on Azure) runs in Cypress fine for a certain number of steps and then simply refuses to progress

1) Open application URL (works fine)
2) Click on Sign in button (works fine)
3) Enter username and click on Next (works fine)
4) Enter password and click on Sign in  (cypress test stops at this stage and displays 'Your tests are loading for infinite amount of time. No logs available)

### Desired behavior

Ideally at this stage the 'Stay Signed in?' popup should display; instead, cypress displays 'your tests are loading' and sits infinitely at this stage

### Test code to reproduce
```js
describe('template spec', () => {

  it('jjsLogin', () => {

    cy.visit('https://videoportaluat.azurewebsites.net/home')
    cy.wait(2000)

    cy.get('.btn').click()   //Sign In button
    cy.wait(1000)

    
    cy.get('#i0116')
    .invoke('val', 'myusername')
    .trigger('input')

    cy.wait(2000)
    cy.get('#idSIButton9').click()   //Next button


    cy.get('#i0118')
    .invoke('val', 'mypassword')
    .trigger('input')

  
    cy.wait(3000)
    cy.get('#idSIButton9').click()  // Sign In button ---- it stops here and shows 'Your tests are loading' for infinite amount of time

   
  })
})
```
### Cypress Version

12.8.1

### Node version

16.16.0

### Operating System

Windows 11

### Debug Logs

```shell
No logs available
```

### Other

Reproducible any number of times
Same behaviour across all browsers
I am using Cypress v12.8.0. (note: the npx cypress - v command in Visual Source Code shows v12.8.0 but in command prompt it shows v12.7.0) 
Have tried increasing wait time / timeout etc. Nothing helps
The application runs correctly without using Cypress

**Comment by AtofStryker** [comment]
Hi @sonajoseph96. Thank you for opening an issue. I tried giving this a reproduction, but I can't seem to get past the first click. Is there something special needed or is this what you are experiencing? I have pushed up a reproduction [here](https://github.com/AtofStryker/cypress-issue-26223) to fill out the missing details.


https://user-images.githubusercontent.com/3980464/228125494-8a8e648b-af87-49e6-88b3-bba59c35b735.mp4


UPDATE: scratch that, I think I need `experimentalModifyObstructiveThirdPartyCode` enabled, but the origin command is not used? Can you help fill out the additional details in the reproduction repository? Is there a reason you are not using `cy.origin`? is `chromeWebSecurity` disabled?

**Comment by sonajoseph96** [comment]
Hi @AtofStryker, thanks for responding. Yes you are right, the `experimentalModifyObstructiveThirdPartyCode` is required. `chromeWebSecurity` is disabled also. There is no specific reason for not using `cy.origin`.  I shall try using `cy.origin` also and provide an update in case it resolves the issue. (please also let me know if you need any further information)

My `config.js` files looks like below

```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    //Network and Security
    experimentalSessionAndOrigin: true,
    experimentalModifyObstructiveThirdPartyCode: true,
    modifyObstructiveCode: false,
    testIsolation: false,
    chromeWebSecurity: false,
    experimentalNetworkStubbing: true,
    experimentalInteractiveRunEvents: true,

   //Timeout and Logging in
    defaultCommandTimeout: 30000,
    requestTimeout: 30000,
    responseTimeout: 30000,
    pageLoadTimeout: 60000,
    viewportHeight: 1080,
    viewportWidth: 1920,

  //Base URL and environment variables
    baseUrl: 'https://videoportaluat.azurewebsites.net/home',
    //supportFile: 'support/commands.js',
    maxUrlLength: 7000,

  //Other Options
     watchForFileChanges: true,
    // waitForAnimations: false,
    // animationDistanceThreshold: 50,
    // retries: 3,  
    // waitForUrl: false,
    setupNodeEvents(on, config) {

    },
  },
});
```

**Comment by sonajoseph96** [comment]
Please let me know if any further information is required from me.

**Comment by emilyrohrbough** [comment]
@sonajoseph96 I removed `chromeWebSecurity: false` and updated your example to use origin and it appears to work (or get past the loading state). Each login click is navigating to a new domain, (Sign in -> (new domain) entered user name -> (new domain) enter password) which would require the use of the [cy.origin()](https://docs.cypress.io/api/commands/origin) command.

```js
describe('template spec', () => {
  it('jjsLogin', () => {
    cy.visit('https://videoportaluat.azurewebsites.net/home')

    cy.contains('Sign In').click()   //Sign In button
    
    cy.origin('https://login.microsoftonline.com', () => {
      cy.get('#i0116')
      .invoke('val', 'myusername')
      .trigger('input')

      cy.get('#idSIButton9').click()   //Next button
    })
    
    cy.origin('https://login.live.com', () => {
      cy.get('#i0118')
      .invoke('val', 'mypassword')
      .trigger('input')
    
      cy.get('#idSIButton9').click()  // Sign In button ---- it stops here and shows 'Your tests are loading' for infinite amount of time
    })
  })
})
```

https://user-images.githubusercontent.com/14099737/229629192-d86fcc9c-01ca-4b5a-a274-b679424c40dc.mov

**Comment by sonajoseph96** [comment]
Thank you so much @emilyrohrbough ! Much appreciated !!
It seems to be crossing the original issue
