### ISSUE TITLE
cypress runner does not displays when external monitor is removed and remain hidden, even with the fresh start

### ISSUE THREAD

**Issue by sandeepcoder097** [cypress-io/cypress#26230]
### Current behavior

cypress runner does not displays when external monitor is removed and remain hidden even with the fresh start of the cypress runner.

### Desired behavior

the runner should open and display correctly irrespective of the screens.

### Test code to reproduce

Given I attach a external monitor
And I move the cypress runner to the second monitor
When I remove the second monitor
Then the cypress runner disappears and is not displayed even when I try to start it again

### Cypress Version

9.7.0

### Node version

v14.17.5

### Operating System

Windows 10 Enterprise

**Comment by nagash77** [comment]
Hi @sandeepcoder097 Are you seeing the same behavior on the latest version of Cypress?

**Comment by nagash77** [comment]
@sandeepcoder097 , we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
