### ISSUE TITLE
Cannot read properties of null (reading 'statusText')

### ISSUE THREAD

**Issue by alessandrostassalpitour** [cypress-io/cypress#26233]
### Current behavior

The test, as soon as it lands on the Login Page as shown in the photo, crashes 1 time out of 2 with the error contained in the title. The method in question is this:

```js
makeEasybookLogin(){
      cy.xpath(e_LoginElements.EasybookEntraComeAlpitourButton).click()
      cy.wait(5000)
      cy.xpath(e_LoginElements.EasybookUsernameButton).then($button => {
        const button = $button[0];
        button.dispatchEvent(new MouseEvent('click', {bubbles: true}));
        cy.scrollTo('top');
      })
      cy.xpath(e_LoginElements.EasybookUsernameButton).type('')
      cy.xpath(e_LoginElements.EasybookPasswordButton).type('')
      cy.xpath(e_LoginElements.EasybookEntraComeAlpitourButtonDue).then($button => {
        const button = $button[0];
        button.dispatchEvent(new MouseEvent('click', {bubbles: true}));
      })    
    }
    
```    
    
    The xpath of the elements are:
```js
export class LoginElements {
     EasybookUsernameButton = "//*[@id='easybook-username']"
     EasybookPasswordButton = "//*[@id='easybook-password']"
     EasybookEntraComeAlpitourButton = "//*[@id='cy-lgn-alpi']"
     EasybookEntraComeAlpitourButtonDue = "//*[@id='cy-lgn-alpi']"
}
```
The error is the one visible in the photo:

![image](https://user-images.githubusercontent.com/116876841/228063098-b7a4c744-39b4-480f-a025-e5422845f2f8.png)

How can I fix this strange bug? I have tried to select the elements in every way: with the xpath from chrome inspect, with absolute xpath, relative xpath, with cy.get.

PS. This problem is seen mainly when I run my test executed from the pipeline on Azure DevOps, could it be an additional element?

### Desired behavior

Correct clicking of the elements both locally, in the Cypress GUI, and on Azure DevOps.

### Test code to reproduce

```js
makeEasybookLogin(){
      cy.xpath(e_LoginElements.EasybookEntraComeAlpitourButton).click()
      cy.wait(5000)
      cy.xpath(e_LoginElements.EasybookUsernameButton).then($button => {
        const button = $button[0];
        button.dispatchEvent(new MouseEvent('click', {bubbles: true}));
        cy.scrollTo('top');
      })
      cy.xpath(e_LoginElements.EasybookUsernameButton).type('')
      cy.xpath(e_LoginElements.EasybookPasswordButton).type('')
      cy.xpath(e_LoginElements.EasybookEntraComeAlpitourButtonDue).then($button => {
        const button = $button[0];
        button.dispatchEvent(new MouseEvent('click', {bubbles: true}));
      })    
    }
```
### Cypress Version

11.0.1

### Node version

16.17.0

### Operating System

Windows 10

### Debug Logs

```shell
TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read properties of null (reading 'statusText')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
    at x.onload (https://test.easybook.it/easybook/assets/js/easybook-fe.min.js?rel=1679659559959:15:3294)
    at XMLHttpRequest.eval (https://test.easybook.it/__cypress/runner/cypress_runner.js:161790:10)
    at window.CookieControl.Cookie.applyOverrideEventListeners (https://consent.cookiebot.com/uc.js:2:99294)
    at <unknown> (https://consent.cookiebot.com/uc.js:2:26599)
    at i (https://test.easybook.it/easybook/public/login/:7:1401)
    at <unknown> (https://test.easybook.it/easybook/public/login/:7:1774)
```

**Comment by AtofStryker** [comment]
Hi @alessandrostassalpitour. Thank you for opening an issue. Would you be able to help us get a reproduction together to reproduce the issue? Does this only happen when you use `cy.xpath` with [@cypress/xpath](https://www.npmjs.com/package/@cypress/xpath) or sporadically when you load the page? I wonder if it is unrelated to `xpath` as the issue throws from the application itself. Are you able to provide the visit URL?

**Comment by alessandrostassalpitour** [comment]
Hi @AtofStryker  , thanks for your attention. I am not able to provide you with the URL of this page because it can only be accessed through a VPN-enabled connection. However, this error occurs intermittently and I can't figure out the cause. It shouldn't be the XPath because the developers added IDs to the elements specifically. Could it be a problem with shadow body or hidden frames? If so, how could I resolve it? Thank you.

**Comment by alessandrostassalpitour** [comment]
@AtofStryker The elements that I have taken into consideration are: in 90% of cases, if the same tests are launched in a production environment, they do not create these problems or give this error. Additionally, they do not appear from the Cypress GUI, but they do from the command line, and especially from the Azure pipeline, this error occurs. My suspicion is that this is because the environment is more unstable and therefore Cypress itself has difficulty loading that page, but I cannot explain why the error code is the one in the post title. Is there a way to understand the level of efficiency of a test in Cypress or to fix these problems (assuming that the error is not due to an xpath)?

**Comment by alessandrostassalpitour** [comment]
![image](https://user-images.githubusercontent.com/116876841/228276651-d9e3da33-7fbc-41c1-8b78-c9dfba3196bf.png)

![image](https://user-images.githubusercontent.com/116876841/228277815-199ef616-e2e1-4ef1-b0d3-aecee6a4db70.png)


From CMD same error in Azure container pipeline.

**Comment by AtofStryker** [comment]
@alessandrostassalpitour what happens if you configure the error as suggested in the error message, something like:

```js
cy.on('uncaught:exception', (e) => !e.message.includes('statusText'))
```

Do your tests still run? Have you tried running `--headed`?

**Comment by alessandrostassalpitour** [comment]
Where i must put this `cy.on('uncaught:exception', (e) => !e.message.includes('statusText'))` ? In wich file?

The headed mode is fantastic, I didn't know about it! Anyway, the situation is even more strange: generally, the first test contained in the first 'it' block completes until the end, but as soon as the second test starts, it generates this error in just a few seconds!

**Comment by AtofStryker** [comment]
you can put that line likely at the beginning of your test or `beforeEach` handler, like:

```js
beforeEach(() => {
 cy.on('uncaught:exception', (e) => !e.message.includes('statusText'))
})

```

**Comment by alessandrostassalpitour** [comment]
Hi @AtofStryker, I have added what was written and it seems that for the moment that error is no longer being generated, but another one has appeared, I don't know if directly related, during the execution of all the tests:

TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection. > Cannot read properties of undefined (reading 'map') When Cypress detects uncaught errors originating from your application it will automatically fail the current test. This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event. https://on.cypress.io/uncaught-exception-from-application at createWidget (https://alpitourdev.cloudando.com/livechat/default/lib/livechatsdk.js:140:40) at <unknown> (https://alpitourdev.cloudando.com/livechat/default/lib/livechatsdk.js:347:16)

![image](https://user-images.githubusercontent.com/116876841/228480718-9ca0787e-1c9f-433a-b3a6-2eceb1e0e1f3.png)

![image](https://user-images.githubusercontent.com/116876841/228480842-b430fb3a-d521-4ca8-90cc-893a97076647.png)



Could it be caused by what I added? In that case, how could I fix this new error that seems conceptually similar to the previous one?

To visibility i send the foto of my config file:
![image](https://user-images.githubusercontent.com/116876841/228481020-03277835-43da-44e4-a688-c4cbdeb039f9.png)

**Comment by alessandrostassalpitour** [comment]
Small note: I never use the map method or widgets associated with it in my tests:
```js
 it('Pacchetto Charter - MAINSTREAM - 2 adulti 1 under18', () => {


    cy.request('GET', q_querySolr.queryPrices('Mainstream', '5', 'AA00', '0'))
      .its('body')
      .then((response) => {
        const keyd = response.response.docs[0].cara.filter((value) => value.startsWith('KEYD/')).slice(-1)[0].substring(5);
        const departureDate = response.response.docs[0].departureDate;
        const regex = /\d{4}-\d{2}-\d{2}/;
        const extractedDate = departureDate.match(regex)[0];
        let data = new Date(extractedDate);
        let formatter = new Intl.DateTimeFormat('it', { day: 'numeric', month: 'long', year: 'numeric' });
        cy.log(formatter)
        let nomeMese = formatter.format(data)
        let dataDivisa = nomeMese.split(' ');
        let day = dataDivisa[0]
        if (day.length == 1) {
          day = "0" + day
        }
        let month = dataDivisa[1]
        cy.addContext(response)

        cy.request('GET', q_querySolr.queryDestinazione(keyd))
          .its('body')
          .then((response) => {
            const destinationName = response.response.docs[0].name;

            cy.addContext(destinationName)

            cy.addContext(month)

            cy.addContext(day)

            s_CommonStep.GoToProdEasybook()

            //cy.writeFile('log/vacanze/pacchettoITC/' + ' Pacchetto ITC due camere doppie.txt', '', { flag: 'w+' })

            s_LoginStep.makeEasybookLogin()

            s_HomePageSteps.chiudiCoockie()

            s_HomePageSteps.searchDestination(destinationName)

            s_HomePageSteps.selectAdultsChildsInfants(2, 1)

          })
      })
  })
  ```
![image](https://user-images.githubusercontent.com/116876841/228492098-da6e0e9c-f013-40e4-8cf3-e59572605a2b.png)

**Comment by HOPELESSNESSLYR** [comment]
> 

Is this problem solved？I have a same problem and need help.

**Comment by alessandrostassalpitour** [comment]
> > 
> 
> Is this problem solved？I have a same problem and need help.

Not yet. I hope to get an answer as soon as possible!

**Comment by alessandrostassalpitour** [comment]
> > 
> 
> Is this problem solved？I have a same problem and need help.

Hi @HOPELESSNESSLYR!
I have solved the problem simply by using, even before the beforeEach and describe, this command:
```js
Cypress.on('uncaught:exception', (err, runnable) => {
return false;
})
```
Please update me if it works for you as well.

**Comment by nagash77** [comment]
@HOPELESSNESSLYR , if the approach @alessandrostassalpitour doesn't work for you please open a new issue with reproduction steps and we will look into it.
