### ISSUE TITLE
Takes too long before starting the test execution

### ISSUE THREAD

**Issue by helkatz** [cypress-io/cypress#26250]
### Current behavior

when starting cypress with npx cypress run or even from within a code with cypress module cypress.run
it takes really long to start the first test > 10 secs 
i call it with only one specific spec file
this time period is really annoying and was mentioned some time ago but the ticket was closed for any reason

### Desired behavior

when i call cypress.run it should immediate start with the test

### Test code to reproduce

just call npx cypress run with whatever u want even when there is just one terstcase in e2e

# npx cypress run

>>>>>after 20secs it starts testing

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.8.1                                                                         │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v16.14.0 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          5 found (mytests/register.cy.js, smoke/register.cy.js, mytests/login.cy.ts, my │
  │                 tests/test1.cy.ts, smoke/login.cy.ts)                                          │
  │ Searched:       cypress/api/**/*.cy.js, cypress/api/**/*.cy.ts                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

### Cypress Version

2.8.0

### Node version

16.14.0

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @helkatz , can you provide more details about your experience?  What are the specs of the machine you are running Cypress on?  Can you provide reproduction example tests that our engineers can use to investigate?  Have you seen an increase in time taken between versions?  I understand wanting everything to be as fast as possible but we need more information before we can properly investigate and respond to your request.

**Comment by nagash77** [comment]
Hi @helkatz , we are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.
