### ISSUE TITLE
Remove support for non-operational CI provider "Shippable" 

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#26253]
### What would you like?

Remove redundant code in:

- [Cypress](https://github.com/cypress-io/cypress)
- ~~[cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink)~~ Edit: done

and other repositories owned by https://github.com/cypress-io/

which supported the CI provider "Shippable".

### Why is this needed?

The provider is no longer operating and the CI domain https://app.shippable.com which was previously hosting https://app.shippable.com/github/cypress-io/cypress-example-kitchensink no longer exists.

Removing the code is a clean-up activity.

## Background

The former CI provider "Shippable" no longer provides a service.

- https://app.shippable.com/ is no longer reachable.
- http://docs.shippable.com/ is no longer reachable.
- Shippable's GitHub repositories under https://github.com/Shippable have not been updated since September 2021.

- See [We’ve Acquired Shippable to Complete DevOps Pipeline Automation From Code to Production](https://jfrog.com/blog/weve-acquired-shippable-to-complete-devops-pipeline-automation-from-code-to-production/) February 21, 2019. JFrog stated they would replace shippable with [JFrog Pipelines](https://www.jfrog.com/confluence/display/JFROG/JFrog+Pipelines) however it seems there is no simple migration from a `Shippable` workflow to a `JFrog Pipelines` workflow. `JFrog Pipelines` would have to be treated like a completely new CI provider.

### Related PRs

- https://github.com/cypress-io/cypress-example-kitchensink/pull/601
- https://github.com/cypress-io/cypress-documentation/pull/5145
- https://github.com/cypress-io/cypress-example-kitchensink/pull/603

**Comment by jennifer-shehane** [comment]
@MikeMcC399 We’re open to a PR to clean this up in Cypress.

**Comment by MikeMcC399** [comment]
Considering that the latest releases of the following npm modules used by Cypress `13.3.0` continue to list "Shippable" as an active CI provider, it may generate unexpected problems to remove Shippable from the Cypress code base. The potential risk does not justify the benefits of a clean-up attempt in this case, since the continued presence of the "Shippable" code in Cypress is not known to generate any issues.

| Module                                                                 | Cypress uses |
| ---------------------------------------------------------------------- | ------------ |
| [ci-info@3.9.0](https://github.com/watson/ci-info/releases/tag/v3.9.0) | `3.8.0`      |
| [is-ci@3.0.1](https://github.com/watson/is-ci/releases/tag/v3.0.1)     | `3.0.1`      |

Additionally used in the Cypress repo by `semantic-release@19.0.3`:

| Module                                                                           | Cypress uses |
| -------------------------------------------------------------------------------- | ------------ |
| [env-ci@10.0.0](https://github.com/semantic-release/env-ci/releases/tag/v10.0.0) | `5.0.2`      |
| [@npmcli/ci-detect@3.0.2](https://github.com/npm/ci-detect/releases/tag/v3.0.2)  | `2.0.0`      |

(`@npmcli/ci-detect` is deprecated and replaced by [ci-info](https://github.com/watson/ci-info/))

Closing this issue.

Edit: [ci-info@4.0.0](https://github.com/watson/ci-info/releases/tag/v4.0.0) removed "Shippable CI".
