### ISSUE TITLE
.click() waits for load event for launch of external event handlers

### ISSUE THREAD

**Issue by sudarsunperu** [cypress-io/cypress#26282]
### Current behavior

When trying to launch an external event like opening New mail upon click of button, Cypress still waits for new page to load ( load event to be triggered)

Cypress expects load event to be triggered for below code
```js
window.location.href = 'mailto:test@mail.com' 
```

![image](https://user-images.githubusercontent.com/18679720/228535846-ebdb0760-b243-4595-ac15-da6ea5cb67bf.png)

### Desired behavior

Upon click of button which triggers an external Handler like open a new mail window (among other things), Cypress should know that browser load event would not be triggered in this case and resume execution.

there is a console log that confirms launch of external event. Please refer to the screenshot.

Related Ticket #20385

### Test code to reproduce

I've forked and reproduced the issue here.
https://github.com/sudarsunperu/cypress-test-tiny/tree/click_always_looks_for_load_event

### Cypress Version

11.2.0

### Node version

16.13.2

### Operating System

Windows 10 Pro

**Comment by astone123** [comment]
@sudarsunperu thanks for the reproduction. What exactly are you trying to test by clicking on the `mailto` button? It would probably be more helpful to assert visibility than to actually click the button.

**Comment by sudarsunperu** [comment]
@astone123 after clicking on the button, I want to test that the external handler is launched with the correct details. e.g. Mail Subject, email, and body of the mail. I believe chrome confirms the launch of external handler via a console log.

**Comment by jordanpowell88** [comment]
@sudarsunperu There isn't a way to do what you are suggesting in Cypress but you could do something like the following to assert that the link that you click is visible and contains the correct href.

```html
 <a class="button small borderless regular" name="Mail" aria-label="button" type="button" href="mailto:test@mail.com?subject=Testing out mailto!&body=This is only a test!">
        <span class="button__content icon-before">
            <span class="button__content__label ng-star-inserted">Open New Mail</span>
            <span class="button__content__icon la-envelope la-las las ng-star-inserted"></span>
        </span>
    </a>

```

```ts
it('Open New Mail', () => {
  cy.visit('../index.html')
  cy.get('a[name=Mail]').invoke('attr', 'href').should('equal', 'mailto:test@mail.com?subject=Testing out mailto!&body=This is only a test!')
  // validate Launch of external handler
});
```

(example: https://www.computerhope.com/issues/ch000056.htm#:~:text=If%20you%20want%20to%20add,similar%20to%20the%20example%20below.&text=You%20can%20also%20add%20body,shown%20in%20the%20example%20below.)
