### ISSUE TITLE
Cypress Crash on windows 10

### ISSUE THREAD

**Issue by nicolasbernard01** [cypress-io/cypress#26287]
### Current behavior

Hello colleagues how are you?

I am having a problem with cypress

It turns out that I install everything Perfect and I enter the graphical interface of cypress, I choose E2E, it creates all the tests and Perfect, but when I start interacting with the tests in the interface, everything crashes And it throws me a message that cypress does not respond I looked for a thousand solutions but I couldn't solve it.

It should be noted that I do not think it is something from the PC since it is a pretty good computer i7 10gen and 16 ram. Please if you can help me I would appreciate it.

Cypress version = 12.8
node version = 19
![IMG_5135](https://user-images.githubusercontent.com/96329004/228629766-0b08a9be-1ab4-4e27-ac57-dad29629e0d9.jpeg)
![IMG_5134](https://user-images.githubusercontent.com/96329004/228629776-8a3a4fff-3924-458f-b4c0-710a682c3654.jpeg)

### Test code to reproduce

i am learning cypress so, the code is the first one cypress created when you chose E2E tests.

### Cypress Version

12.8

### Node version

 19.8.1

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @nicolasbernard01 Can you try running using node 16 and see if you encounter the same problem?

Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nicolasbernard01** [comment]
@nagash77  thanks for your help but the problem continue i dont know what happen. if have another solution i am here for try!

thanks!

**Comment by nagash77** [comment]
@nicolasbernard01 can you outline in detail the steps you took to install and launch Cypress?  Right now the information provided does not give us enough to go off of. Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by nicolasbernard01** [comment]
@nagash77  thanks for try to help me, here i show you the complete steps.


<h2>1- npm init<h2>

![npm init](https://user-images.githubusercontent.com/96329004/228907183-ea0800f7-6cc7-4ef4-9068-f4cb5c2fbf16.jpg)


<h2>2- Cypress install<h2>

![Cypress install](https://user-images.githubusercontent.com/96329004/228907277-7729e059-f183-4eed-a5b0-4c0cf915bc9c.jpg)

<h2>3- npm run test<h2>

![run test](https://user-images.githubusercontent.com/96329004/228907731-23d4cdc7-a178-40ae-b765-7f7e561b92b1.jpg)



<h2>4- Cypress ok and chose E2E testing<h2>

![ok and chose e2e testing](https://user-images.githubusercontent.com/96329004/228908348-e0116411-52f6-48c7-9378-0327d41eb0a6.jpg)

<h2>5- Cypress configuration files<h2>

![cypress folder and continue](https://user-images.githubusercontent.com/96329004/228909194-3d900602-8dd3-44d3-bb83-7225e096a769.jpg)


<h2>6- Choose chrome brownser <h2>

![chose chrome and start](https://user-images.githubusercontent.com/96329004/228908654-2f8068ed-1ae3-47e1-b520-efcf22757df0.jpg)



<h2>7- Select scaffold example specs <h2>

![scaffold example specs](https://user-images.githubusercontent.com/96329004/228909932-db1673a2-ea4d-4e62-bd65-c57c99c69670.jpg)


<h2>8- Select the first test "to-do" <h2>

![select todo](https://user-images.githubusercontent.com/96329004/228910255-a57b239a-d187-499e-bafa-2ac2ea7c40e5.jpg)


<h2>8- Finally cypress crash <h2>


![finally cypress crash](https://user-images.githubusercontent.com/96329004/228910349-b227cbc7-89b7-4d3f-9b1c-9f43c1478572.jpg)


<h2>9-Extra thing: Sometimes, Cypress runs the test, but later crashes again. Here, I am attaching a photo because Chrome shows me in red HTTP. I don't know if that can be a problem, but I am adding the photo here <h2>


![extra](https://user-images.githubusercontent.com/96329004/228911746-cc73683c-515f-4b0f-bf52-23cef25dc804.jpg)


<h2>Thanks!!! <h2>

**Comment by MikeMcC399** [comment]
Another user found issues running on Windows OneDrive. This may not be the cause of your issue however.

**Comment by nicolasbernard01** [comment]
@MikeMcC399 Hi Mike!! thanks a lot for help with my problem!!! i can resolve it!! the problem was i running cypress on OneDrive! now cypress work perfect!!! thanks a lot!!

**Comment by MikeMcC399** [comment]
@nicolasbernard01 I'm glad it is now running. OneDrive will continually try to sync its contents so it is not good for system software. It might have worked if you had just waited, but it is better to have Cypress on a non-sync'ed drive.

You can click on the close button now if you don't need any more help.
