### ISSUE TITLE
Record timer in dashboard keeps running even tests are stopped

### ISSUE THREAD

**Issue by ilamparithiNatarajan** [cypress-io/cypress#2630]
<img width="1306" alt="cypress recorder keeps running" src="https://user-images.githubusercontent.com/28389350/47242853-0dab3e80-d3e8-11e8-880a-e77ce5ba5442.png">

### Current behavior:

record timer keeps running even after I killed the test

### Desired behavior:

record timer should stop when i kill the test

### Steps to reproduce:

1. run any test in cli
./node_modules/.bin/cypress run --record --key ***

2. kill the test
3. go see the dashboard

### Versions
cypress 3.10

**Comment by jennifer-shehane** [comment]
Thanks for opening this issue! 

Any cancelled runs are cleaned up and closed every 90 minutes. 

I understand this is not made very clear though, our team is working on a solution for cleaning runs quicker. I will keep this issue open to keep track of when that solution is in. 

Also related to cancelling: https://github.com/cypress-io/cypress/issues/1691

**Comment by ilamparithiNatarajan** [comment]
thanks for the response!

**Comment by jennifer-shehane** [comment]
Closing as resolved.
