### ISSUE TITLE
.RightClick() on macbook does not activate context menu

### ISSUE THREAD

**Issue by mwardGresham** [cypress-io/cypress#26303]
### Current behavior

On a mac, using .rightClick() does not open a context menu

This appears to work fine on windows and our circleci builds, just not when running locally on macbooks

### Desired behavior

On a mac, using .rightClick() should open a context menu

### Test code to reproduce

    it.only('should open context menu on right-click', () => {
        // Navigate to site
        cy.visit('https://example.com');

        // Find the element on which we want to right-click
        cy.get('#example-element').rightclick();

        // Verify that the context menu was opened
        cy.get('.context-menu').should('be.visible');
    });

### Cypress Version

11.1.0

### Node version

18.5.0

### Operating System

macOS 12.3

**Comment by emilyrohrbough** [comment]
@mwardGresham I tried running the example you provided, however am seeing `Timed out retrying after 4000ms: Expected to find element: #example-element, but never found it.` so cannot get to the `.rightClick()` command. Is this the repo correct?



![Image](https://user-images.githubusercontent.com/14099737/228991006-bf455747-3046-4f92-affe-6c3d5ac3e6e8.png)

**Comment by mwardGresham** [comment]
Hi, the domain and example element are not real, i dont have a site to use as an example, but if you use the code swap out example url and example element, it should fail to show the context menu

**Comment by mwardGresham** [comment]
Here is an example using wikipedia 
```js
it.only('should open context menu on right-click', () => {
        // Navigate to site
        cy.visit('https://www.wikipedia.org/');

        // Find the element on which we want to right-click
        cy.contains('Commons').rightclick();

        // Verify that the context menu was opened
        cy.get('.context-menu').should('be.visible');
    });
```

**Comment by emilyrohrbough** [comment]
@mwardGresham I have looked at this a bit and we call out in our documentation that [`.rightClick()`](https://docs.cypress.io/api/commands/rightclick) will not open the context menus native to the browser. 


![Image](https://user-images.githubusercontent.com/14099737/229630142-133cec80-7617-45a5-9682-0e9ba2688094.png)

Closing as this is expected and you happen to be lucky this is working on Windows/in CI. If I am mis-understanding the issue report, please adding more details and we can re-evaluate.
