### ISSUE TITLE
Cypress Cloud Uses Wrong Branch in Semaphore CI

### ISSUE THREAD

**Issue by leightjohnson93** [cypress-io/cypress#26309]
### Current behavior

In Sempahore CI, on pull requests, Cypress Cloud test runs show up under the target branch.

### Desired behavior

Test runs should show up as being run on the current branch.

### Test code to reproduce

Cypress uses `SEMAPHORE_GIT_BRANCH` as the branch to report test runs.  However, for a pull request this points to target branch.  This is a problem, because we want the current branch.

https://github.com/cypress-io/cypress/blob/a5b0cad9f0b7a49674c79747cc2616e788a3b2da/packages/server/lib/util/ci_provider.js#L573

https://docs.semaphoreci.com/ci-cd-environment/environment-variables/#semaphore_git_branch

### Cypress Version

12.8.1

### Node version

16.13.0

### Operating System

Ubuntu 20.04.6 LTS (Focal Fossa)

**Comment by emilyrohrbough** [comment]
I confirmed we are using the wrong ENV. Per the docs: 

> In builds triggered by a Pull Request, the value of the SEMAPHORE_GIT_BRANCH is the name of the git branch targeted by the Pull Request.
