### ISSUE TITLE
Possibility to use CTRL+click on canvas map

### ISSUE THREAD

**Issue by tascioglu** [cypress-io/cypress#2637]
Hi all.. Need your really your help, because I'm stuck with this some months now.. I already put this on the chat already, but nobody could help..

With testing some new features, I need to draw/trigger (with angular) an extent on the map with ctrl-key. 

- action is CTRL-key+ Click (left mouse-button)

It's already working for me for just clicking with code below:
```js
cy.get('canvas')
   .trigger('pointerdown', 250, 250)
   .trigger('pointerdown', 250, 250)
```

Can somebody help me with this one?

Thanx...

**Comment by akapitoha** [comment]
Hi,
I've smth similar to your case with cmd + click
```
cy.get('body').type('{cmd}', {release: false}).then(($cmd) => {
    cy.get('element').click()
})
```
maybe that helps

**Comment by Bkucera** [comment]
The solution @akapitoha posted should work. The following should also work:
```js
cy.get('body').type('{cmd}', {release: false})
cy.get('element').click()
```

**Comment by helenvn** [comment]
@Bkucera  cy.get('body').type('{cmd}', {release: false}).then(($cmd) => {
                    cy.get('canvas').click(450, 300);
                    cy.wait(6000)
                })
but it does not click a label in canvas map
Could you please help me? Thanks
