### ISSUE TITLE
CT framework detection can fail due to `open` mode not waiting for DataContext to initialize

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#26388]
### Current behavior

See `packages/server/lib/modes/index.ts` - this file kicks off an initialization of the data context for the current mode and executes a script based on the mode to launch the UI. The promise is passed into those scripts.
In `run.ts` the promise is awaited prior to reporting a "ready" state, but in `interactive.ts` it is not. This allows the UI to initialize prior to the data context being ready which can result in odd race conditions since not all GQL queries are reactive/subscriptions.

We need to evaluate whether an `await` is needed in `interactive.ts` to ensure this data is resolved prior to launching UI, or whether this is intentionally ignored for performance reasons

### Test code to reproduce

1. Add an arbitrary delay to `packages/scaffold-config/src/detect.ts` in the `detectFramework` function of several seconds
2. Create a new CT project but do not initialize with a cypress config: `npm create vite@latest`. Install dependencies in project.
3. Open project directly into CT mode: `yarn dev --component --project <path to new project>`
4. Delay will prevent auto-detection of CT framework from resolving prior to UI being initialized

5. Add an `await` of the `_loading` promise in `interactive.ts`
6. Repeat test above, observe framework is now properly resolved

### Cypress Version

12.8.1

### Node version

16.17.1

### Operating System

any

**Comment by emilyrohrbough** [comment]
@mike-plummer FYI - We def do not want to await for this before launching the launchpad. We have found this to be is quite "slow"  when analyzing our timings and this would make the open mode experience pretty "non-responsive".

**Comment by mike-plummer** [comment]
@emilyrohrbough Was just going to ping you on this today to see if you remembered why it was structured that way 😆 . Thanks for the info (and amazing memory!). This was my assumption/fear, so we can work around it with a GQL subscription to get updated data once the context settles down behind the UI. I will plan to add some comments under this issue to `interactive.ts` to make it clear that we don't want to wait for that loading promise and why just for posterity
