### ISSUE TITLE
Getting Webpack Compilation Error after importing the a method in test file from the other file 

### ISSUE THREAD

**Issue by Hani264** [cypress-io/cypress#26384]
### Current behavior

I'm trying to do integration testing by using the API response from the ReactJs Component instead of calling API in cypress tests. So, I have created a method that exports the response from the component and importing the method in cypress test file.
After importing the method in cypress test file, I'm getting the "Webpack Compilation error".
![image](https://user-images.githubusercontent.com/50475874/229140876-978243f8-d708-49c2-9976-a8617c3f7adc.png)

### Desired behavior

The tests should run without compilation error after importing the method/response in cypress tests.

If this is the expected behavior from the cypress then could you please suggest a way to get the response from the React component to cypress test file to write test using the response from the component.

### Test code to reproduce

**Component.jsx**
```js
   export const passResponse = () => {
       return apiResponse;
   }
```
**CypressTestFile.cy.jsx**
 ```js 
  import {passResponse} from '../../Component.jsx';

describe('Component Mounts', ()=>{
  beforeEach('Check API Reponse', ()=>{
    cy.wrap(passResponse()).then( response => console.log(response))
  });
});
```
### Cypress Version

12.3.0

### Node version

v14.15.4

### Operating System

win10

### Debug Logs

```shell
Error: Webpack Compilation Error
./node_modules/react-dates/lib/css/_datepicker.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .PresetDateRangePicker_panel {
|   padding: 0 22px 11px
| }
```

**Comment by jordanpowell88** [comment]
@Hani264 The good news is what you are requesting is a built in functionality with Component Testing. You just need to do the following to reproduce what you are doing above

```ts
cy.mount(<Component />).then(response => console.log(response))
```
