### ISSUE TITLE
babel.config.js causes TypeError: programPath.hub.addHelper

### ISSUE THREAD

**Issue by giorgio-zamparelli** [cypress-io/cypress#2638]
### Bug
cypress doesn't work with the new Babel configuration file named `babel.config.js`

### Current behavior:

Naming the Babel configuration file as `babel.config.js` will cause error
```
TypeError: programPath.hub.addHelper is not a function while parsing file
```

`babel.config.js` is a new configuration file available since Babel 7:
[https://babeljs.io/docs/en/config-files](https://babeljs.io/docs/en/config-files)

### Desired behavior:

Cypress should work with `babel.config.js` as well

### Steps to reproduce:

1. Open a project with Cypress and Babel
2. Rename the configuration file from `.babelrc.js` to `babel.config.js`
3. One of the tests in `cypress/integration` uses a ESM import `import`
4. execute `npx cypress open` and then launch the test with the ESM import

### Versions
cypress 3.1.0
@babel/core 7.1.2",
@babel/preset-env 7.1.0
@babel/register 7.0.0

cypress 3.1.0 (3.1.0)
Chrome 53 and Electron 59
macOS 10.13.6

**Comment by chrisbreiding** [comment]
Can you post the contents of your `babel.config.js`? It will help reproduce the issue.

Also, are you utilizing the `file:preprocessor` event in `cypress/plugin/index.js` at all? If so, can you post the contents of `cypress/plugins/index.js`?

**Comment by giorgio-zamparelli** [comment]
<pre><code>//babel.config.js
module.exports = {
	plugins: [
		'@babel/plugin-transform-modules-commonjs',
	],
	presets: [
		['@babel/preset-env', {
			targets: {
				node: '8.10',
			},
			shippedProposals: true,
		}],
	],
}
</pre></code>

I'm not utilizing any file:preprocessor, I've the left the `/cypress/plugin` folder identical to the one generated by `npm install cypress`

**Comment by giorgio-zamparelli** [comment]
Removing `@babel/plugin-transform-modules-commonjs` from `babel.config.js` fixes the problem
