### ISSUE TITLE
Using a community/custom component framework definition causes a TypeScript error

### ISSUE THREAD

**Issue by kgroat** [cypress-io/cypress#26394]
### Current behavior

When you use an unofficial framework in your cypress.config.ts, TypeScript complains.

### Desired behavior

You should be allowed to use framework definitions that fit the format `cypress-ct-[name]` or `@[scope]/cypress-ct-[name]`.

### Test code to reproduce

cypress.config.ts
```ts
import { defineConfig } from 'cypress';
import { defineConfig as defineViteConfig } from 'vite';

export default defineConfig({
  component: {
    devServer: {
      framework: 'cypress-ct-lit-element', // Error on this line
      bundler: 'vite'
    }
  }
});

```

### Cypress Version

12.9.0

### Node version

16.16.0

### Operating System

MacOS 13.2.1

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/26394?planning-poker) with Zenhub @astone123 @jordanpowell88 @lmiller1990 @marktnoonan @mike-plummer @warrensplayer

**Comment by lmiller1990** [comment]
**Note there is a PR already**, #26396 - the goal here is to find out why CI is failing and help the contributor get the PR merged.
