### ISSUE TITLE
Double run of a spec when clicking on it

### ISSUE THREAD

**Issue by euge** [cypress-io/cypress#264]
It seems that when clicking on a specific spec to run, the browser is opened and begins to run, but is then interrupted and restarted again. I noticed that initially there's no "https" in the url, but when it is restarted there is one in red. 
![cypressbug](https://cloud.githubusercontent.com/assets/52219/19335064/3a416a50-90b5-11e6-8c45-9176b68c3a1e.gif)

**Comment by brian-mann** [comment]
This is the intended and correct behavior of Cypress. What is happening is that Cypress is redirecting itself to be on the `origin` that matches the application under test (in order words what you `cy.visit`).

Subsequent test runs will not cause Cypress to swap to the new origin - it will stay there until a `cy.visit` changes the origin again.

This is documented under our newly written Web Security guide here: https://docs.cypress.io/docs/web-security
