### ISSUE TITLE
cy.request can't send x-www-form-urlencoded

### ISSUE THREAD

**Issue by GeorgianStan** [cypress-io/cypress#26401]
### Current behavior

I am trying to create a login command where a POST request is sent to a Keycloak server.
The request is created as follows:
```
const body = new URLSearchParams();

body.append("username", username);
body.append("password", password);
body.append("grant_type", grant_type);
body.append("client_id", client_id);

cy.request({
  method: "POST",
  url: `${AUTH_URL}/auth/realms/my-realm/protocol/openid-connect/token`,
  body,
  headers: {
    "Content-Type": "application/x-www-form-urlencoded",
  },
});
```

### Desired behavior

I expect a POST request to be sent to the supplied URL with the correct body.

### Test code to reproduce

```
const body = new URLSearchParams();

body.append("username", '');
body.append("password", '');
body.append("grant_type", '');
body.append("client_id", '');

const AUTH_URL = ''

cy.request({
  method: "POST",
  url: `${AUTH_URL}/auth/realms/my-realm/protocol/openid-connect/token`,
  body,
  headers: {
    "Content-Type": "application/x-www-form-urlencoded",
  },
});
```

### Cypress Version

12.2.0

### Node version

18.10

### Operating System

Windows 10

### Debug Logs

```shell
The response we received from your web server was:

  > 400: Bad Request

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request that was sent was:

Method: POST
URL: https://MY-URL/auth/realms/my-realm/protocol/openid-connect/token
Headers: {
  "Connection": "keep-alive",
  "Content-Type": "application/x-www-form-urlencoded",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-length": 0
}
Body: 
```
The request failed, and that's because `Body' appears to be empty.

**Comment by emilyrohrbough** [comment]
@GeorgianStan I did a bit of digging on this, and I think I understand why you are experiencing this issue. It appears the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) class implements JavaScript’s iterator interface, where as `cy.request()` is expecting an object or string to be passed as the body.

It can be observed with:
```js
  const body = new URLSearchParams();

  body.append('username', 'GeorgianStan');

  console.log('face value: ', body)
  console.log('as string: ', body.toString())
  console.log('as object: ', Object.fromEntries(body))
```

When I update to use either, I am seeing the body populated in the request in the cy.request() console details. 

```js
it('try it out', function () {
  const body = new URLSearchParams();

  body.append("username", 'x');
  body.append("password", 'hi');
  body.append("grant_type", 'cy_issue');
  body.append("client_id", '369');

  cy.request({
    'method': 'POST',
    'url': 'https://jsonplaceholder.cypress.io/comments',
    'headers': {
      'Accept': 'application/json',
      'content-type': 'application/x-www-form-urlencoded',
    },
    body: Object.fromEntries(body),
  })
```


![Image](https://user-images.githubusercontent.com/14099737/229641943-e2bf284b-87a4-4c05-84a0-b138f7b493a7.png)

Can you give this a try and see if this resolves your issue?

**Comment by GeorgianStan** [comment]
Hi @emilyrohrbough thank you for this workaround. Is this something that we need to address from our side or it will be handled by Cypress?

**Comment by emilyrohrbough** [comment]
@GeorgianStan This would need to be handled on your side as the API is expecting a string or object, not a class instance.
