### ISSUE TITLE
After changing to "https" Cypress tests stopped working and return ECONNRESET error

### ISSUE THREAD

**Issue by achelonmm** [cypress-io/cypress#2641]
### Current behavior:

I am testing our application, and until now, we had been using `http` and everything was working perfectly. 
We use a redirection to Identity Server in order to manage the login.

Yesterday we changed to `https` and the tests stoped working. 
Whenever I test it manually everything works as expected, but once I try testing it using Cypress, I get this error:

```
> CypressError: cy.visit() failed trying to load:

> https://hc2int.c-salud.com/

> We attempted to make an http request to this URL but the request failed without a response.

> We received this error at the network level:

> Error: read ECONNRESET

> Common situations why this would fail:
>   - you don't have internet access
>   - you forgot to run / boot your web server
>   - your web server isn't accessible
>   - you have weird network configuration settings on your computer

> The stack trace for this error is:

> Error: read ECONNRESET
>     at exports._errnoException (util.js:1024:11)
>     at TLSWrap.onread (net.js:610:25)
```

Since we are doing external navigation I tried setting `chromeWebSecurity:false` but even with that option set, the tests still fail and I get the same error.

I'm completely lost at the moment as I don't know what else to do. I've asked in gitter but no one replied and searching on internet didn't offer any help.

I cannot provide access to our application for testing as it's a private environment.

### Versions
Cypress 3.1.0

**Comment by achelonmm** [comment]
Additional information:

After more specific testing and research it seems the problem is in Cypress cache. I've tested visiting an https url and the first time I have an OK response (GET 200) but then it's followed by GET 500). 

If I refresh Cypress to rerun the test after several attempts it finally works one time again and the cycle repeats.

I've tried this using cy.request() and attacking an API url that provides me with plain text and the first time I get an ok but if I rerun the test, for a while it gives me the same ECONNRESET error but with more stack trace:

> RequestError: Error: read ECONNRESET
>     at new RequestError (C:\Users\74374894R\AppData\Local\Cypress\Cache\3.1.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\errors.js:14:15)
>     at Request.plumbing.callback (C:\Users\74374894R\AppData\Local\Cypress\Cache\3.1.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:87:29)
>     at Request.RP$callback [as _callback] (C:\Users\74374894R\AppData\Local\Cypress\Cache\3.1.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:46:31)
>     at self.callback (C:\Users\74374894R\AppData\Local\Cypress\Cache\3.1.0\Cypress\resources\app\packages\server\node_modules\request\request.js:185:22)
>     at emitOne (events.js:115:13)
>     at Request.emit (events.js:210:7)
>     at Request.onRequestError (C:\Users\74374894R\AppData\Local\Cypress\Cache\3.1.0\Cypress\resources\app\packages\server\node_modules\request\request.js:877:8)
>     at emitOne (events.js:120:20)
>     at ClientRequest.emit (events.js:210:7)
>     at TLSSocket.socketErrorListener (_http_client.js:401:9)
>     at emitOne (events.js:115:13)
>     at TLSSocket.emit (events.js:210:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jennifer-shehane** [comment]
@achelonmm Could you be more specific about how you came to the conclusion that the issue involves "Cypress cache"?

**Comment by achelonmm** [comment]
Hi @jennifer-shehane . 
It's only a supposition as the only information I have are the stack traces and mainly the fact that after several seconds of trying it works once and then it fails again for several seconds, so it's kind of a loop:

Success run -> Several seconds of fail runs -> Success run -> Several seconds of fail runs -> rinse and repeat.

This never happened when we were using http.

As I said, it's a supposition as the amount of information I have is quite limited. However, manual testing does not detect anything at all, and neither does unit tests nor integration tests.

We are running stress and performance tests using native VSTS tool and it doesn't have problems either, so it's only Cypress the one having problems with the change from http to https.

I know Cypress supports this as I've read carefully the documentation, and as I said in my first post, I even included the chromeWebSecurity: false line in the cypress.json file in case it was a problem of navigation.

Nothing is working.

**Comment by achelonmm** [comment]
Issue can be closed.
Pinpointed the origin of the problem, and backend devs messed everything up. 

Glad to know Cypress still works as amazingly as it has been working these past months.

**Comment by jennifer-shehane** [comment]
@achelonmm Thanks for updating!

**Comment by rasmusvhansen** [comment]
> Issue can be closed.
> Pinpointed the origin of the problem, and backend devs messed everything up.
> 
> Glad to know Cypress still works as amazingly as it has been working these past months.

@achelonmm Can you elaborate a bit on what the error was. 
I am seeing something very similar, where a manual submit of a form works fine, but when doing it through Cypress, it fails with ECONNRESET error from Cypress.

**Comment by achelonmm** [comment]
> > Issue can be closed.
> > Pinpointed the origin of the problem, and backend devs messed everything up.
> > Glad to know Cypress still works as amazingly as it has been working these past months.
> 
> @achelonmm Can you elaborate a bit on what the error was.
> I am seeing something very similar, where a manual submit of a form works fine, but when doing it through Cypress, it fails with ECONNRESET error from Cypress.

Sadly I cannot, this was quite a long time ago and neither I nor my team remembers what the problem was.
If by any chance I remember something about it I will send you a private message. Sorry!
