### ISSUE TITLE
dropdown primeng-v13 stays open after item selection

### ISSUE THREAD

**Issue by aichingerstefanie** [cypress-io/cypress#26425]
### Current behavior

I have prepared a test for webpage: '//www.primefaces.org/primeng-v13/dropdown'.
[https://www.primefaces.org/primeng-v13/dropdown](url)
see below : testSelectFromDropdownPrimeng.txt

The test selects from different dropdowns of this webpage quite often. 
(I skipped Group dropdown, as we do not use it in our applications.)

The test does following steps quite often:
1. click on dropdown or dropdown trigger, opens the dropdownlist (OK)
2. click on a dropdown-item (OK)
4. check selection on drop down label (OK)
5. dropdownlist does not exist (does not allways work)

	Run the test for several times.
	In my case in the second or third run one of the dropdowns will not be closed after an item has been selected.
	From this time on the test might never pass again on repetition for the same reason. The error mignt  not necessarily occur at the same dropdown.
	I have to restart my machine first if want a clean run for the next test.

	I tested with Chrome (Version 111.0.5563.147 (Offizieller Build) (64-Bit))
	and Firefox (108.0.2 (64-Bit)), no difference.

Error Screenshot:
![dropdownErrorScreenshot](https://user-images.githubusercontent.com/124276654/229793235-29d46617-729f-4cb3-889c-4e47b2376578.PNG)

I tried a wait after Selection, I tried with and without scroll into view but it did not prevent the error.
I tried some other variations with small changes in my selectFromDropdown-Funkction, however non of them did prevent the error.

Sometimes I found this Error as a error info on screen:
![image](https://user-images.githubusercontent.com/124276654/229795540-19280d1e-e37b-46db-8800-a090ac4d6dc2.png)
in words: Node.removeChild: the node to be removed is not a child of this node

It seems cypress would prevent or disturbs the closing/removing process.

Problem: 
The open dropdown list covers other elements. Dropdown list is found more than one times at the next dropdown selection. Testsuite with many tests having forms with a lot of dropdowns can not be run successfully.

Error:
15 getdiv.ng-trigger-overlayAnimation
16 assertexpected <div.ng-trigger.ng-trigger-overlayAnimation.ng-tns-c33-3.p-dropdown-panel.p-component.ng-star-inserted.ng-animating> not to exist in the DOM
AssertionError
Timed out retrying after 10000ms: Expected <div.ng-trigger.ng-trigger-overlayAnimation.ng-tns-c33-3.p-dropdown-panel.p-component.ng-star-inserted.ng-animating> not to exist in the DOM, but it was continuously found.
cypress/e2e/dropdown_prime_eng_v13.cy.ts:22:1
  20 |             .find('.p-dropdown-label')
  21 |             .should('have.text', filterValue);
> 22 |         cy.get('div.ng-trigger-overlayAnimation').should('not.exist');
     | ^
  23 |     }
  24 |     function selectCountry(country) {
  25 |         cy.get('h5')
  
  
  stack Trace
  at selectFromDropdown (webpack:///./cypress/e2e/dropdown_prime_eng_v13.cy.ts:22)
at Context.eval (webpack:///./cypress/e2e/dropdown_prime_eng_v13.cy.ts:71)

` Dropdown Itmes HTML starts like this: <div onoverlayanimationend="" class="ng-trigger ng-trigger-overlayAnimation ng-tns-c33-3 p-dropdown-panel p-component ng-star-inserted" style="z-index: 1001; transform-origin: center top; top: 42px; left: 0px;">
	
	<div class="p-dropdown-items-wrapper ng-tns-c33-3" style="max-height: 200px;">
		<ul role="listbox" class="p-dropdown-items ng-tns-c33-3" id="pr_id_2_list">
		
			<p-dropdownitem class="p-element ng-tns-c33-3 ng-star-inserted" style="">
				<li role="option" pripple="" class="p-ripple p-element p-dropdown-item" id="" aria-label="New York" aria-selected="false">
					<span class="ng-star-inserted">New York</span>
				
					<span class="p-ink" style="height: 177px; width: 177px; top: -79.25px; left: 24.5px;"/>
				</li>
			</p-dropdownitem>
	

### Desired behavior

Cypress should always close the dropdown list of a (primeng) dropdown. 

### Test code to reproduce

Testfile:

[testSelectFromDropdownPrimeng.txt](https://github.com/cypress-io/cypress/files/11148553/testSelectFromDropdownPrimeng.txt)

### Cypress Version

12.7.0

### Node version

v18.15.0

### Operating System

Windows 10 Business version: 22H2, build: 19045.2728

**Comment by warrensplayer** [comment]
@aichingerstefanie The URL you supplied seems to have changed since you created this issue. Can you confirm and update this issue?  Even better would be a zipped up reproduction. Attached is one I started with your test script but had to point it at a different URL. I did not totally get it completed, but the dropdowns seemed to be working.  You can use it to start.

[26425.zip](https://github.com/cypress-io/cypress/files/11347377/26425.zip)

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
