### ISSUE TITLE
Cypress Not Rendering Placeholder Text In Browser

### ISSUE THREAD

**Issue by briggsge** [cypress-io/cypress#26436]
### Current behavior

A test is configured to verify placeholder text exists. The text is not being rendered and the test if failing, as expected. However, Cypress' browsers rendering of the element does not show the placeholder text and an actual browser does showr the placeholder text.

Verified in Chrome and Edge Cypress do not display placeholder text and actual MacOS and Windows Edge and Chrome browsers do display the placeholder text. Images below.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/84735697/230108476-3d76258a-3e34-4741-b388-c3ac7e3f6d0b.png">
Actual Browser

<img width="263" alt="image" src="https://user-images.githubusercontent.com/84735697/230108523-1093a3c6-ecbd-471a-93ee-b76117f2071c.png">
Cypress renderings

### Desired behavior

Cypress should correctly display elements and text that mirrors actual browser behavior.

### Test code to reproduce

Unfortunately, the issue is not with Cypress detection of elements, so providing example code will not be useful. The Cypress assertions are working correctly based on the element not being rendered on the screen.

### Cypress Version

12.9.0, 12.8.1

### Node version

v19.8.1, v16.13.0

### Operating System

MacOS

**Comment by nagash77** [comment]
@briggsge can you provide same HTML that exhibits the behavior you are referring to?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by briggsge** [comment]
@nagash77 - this was due to some react state management ultimately. Did not capture the code before/after so apologies and I apologize for the incomplete/poor issue report. Thanks!
