### ISSUE TITLE
Provide working recommendation for contributor Node.js switching

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#26441]
### What would you like?

I would like to be able to follow the recommendations in [CONTRIBUTING: Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) to switch Node.js.

---

### Requirements

You must have the following installed on your system to contribute locally:

- [`Node.js`](https://nodejs.org/en/) (See the root [.node-version](.node-version) file for minimum version requirements. You can use [avn](https://github.com/wbyoung/avn) to automatically switch to the right version of Node.js for this repo.)

---

### Why is this needed?

This is convenient when contributing to multiple Cypress repositories with different Node.js requirements.

### Other

The recommendation to use [avn](https://github.com/wbyoung/avn) is outdated. It no longer works.

- The issues list https://github.com/wbyoung/avn/issues indicate that it is incompatible with the versions of Node.js supported by the current version of Cypress i.e. Node.js 14 and later.
- I tried it on Ubuntu 22.04 with [nvm](https://github.com/nvm-sh/nvm) [v0.39.3](https://github.com/nvm-sh/nvm/releases/tag/v0.39.3) and it shows errors when installing and does not switch Node.js when changing to a directory containing `.node-version`.
- The last update to the repository [avn](https://github.com/wbyoung/avn) was three years ago.

## Suggestion

Either:

- recommend a substitute for [avn](https://github.com/wbyoung/avn) which is compatible with Node.js 14 and later or
- consider switching to using `.nvmrc` which is compatible with the POSIX-shell version of nvm. See [.nvmrc](https://github.com/nvm-sh/nvm#nvmrc).

## Related discussion

This follows on from https://github.com/cypress-io/github-action/pull/853#discussion_r1159072711 from @emilyrohrbough which drew my attention to this section.

**Comment by MikeMcC399** [comment]
- See also https://github.com/cypress-io/cypress/issues/26443

**Comment by shadowspawn** [comment]
For interest, there are a variety of node-version managers which support the `.node-version` file: https://github.com/shadowspawn/node-version-usage

(`nvm` does not directly support changing node when change directory, and does not support the `.node-version` file.)

**Comment by lmiller1990** [comment]
I have been using `n` - [here](https://github.com/tj/n) to manager my Node.js versions. It works with `.node-version` and `.nvmrc` by the looks of things.

**Comment by MikeMcC399** [comment]
@lmiller1990 / @emilyrohrbough 

Is there consensus to recommend that contributors to this repo use:

- [n](https://www.npmjs.com/package/n) (n – Interactively Manage Your Node.js Versions) instead of the outdated 
- [avn](https://www.npmjs.com/package/avn) (Automatic Version Switching for Node.js)?

(I bet that would please @shadowspawn 😃!) 

I can't weigh in on this at the moment since I have been using [nvm](https://github.com/nvm-sh/nvm) on Ubuntu and [nvm-windows](https://github.com/coreybutler/nvm-windows) on Windows 11.

If [n](https://www.npmjs.com/package/n) (n – Interactively Manage Your Node.js Versions) is considered the tool of choice for POSIX-based systems then I would migrate and submit a PR to document this.

For Windows (where I am not using WSL2) I would stay with [nvm-windows](https://github.com/coreybutler/nvm-windows). But in any case I had extreme issues trying to build Cypress on Windows and I have abandoned it for that use-case, although it is perfectly good for other repos.

**Comment by lmiller1990** [comment]
Do we need to make a recommendation? I think most developers probably prefer to decide how they'd like to manage their Node.js version on their own. WDYT? We could add a list - eg "You need to use Node.js version XXX, here are some tools you can consider which will help manage the Node.js versions your machine has installed".

**Comment by MikeMcC399** [comment]
If you don't want to make a specific recommendation, then my suggestion for a replacement text would be:

---

### Requirements

You must have the following installed on your system to contribute locally:

- [`Node.js`](https://nodejs.org/en/) (See the root [.node-version](.node-version) file for version requirements. For a list of available tools that can assist switching to the version of Node.js specified by `.node-version` see https://github.com/shadowspawn/node-version-usage.)

**Comment by MikeMcC399** [comment]
I tried out [n](https://www.npmjs.com/package/n) (n – Interactively Manage Your Node.js Versions) on Ubuntu and found it was better than [nvm](https://github.com/nvm-sh/nvm) in respect to pnpm and Yarn in that I did not need to reinstall the other package managers globally after installing a new Node.js version. So I plan to use [n](https://www.npmjs.com/package/n) on Ubuntu in future. (I need all three package managers (npm, pnpm and Yarn) when I'm working on [cypress-io/github-action](https://github.com/cypress-io/github-action)).

**Comment by MikeMcC399** [comment]
- I've submitted PR #26652 now, which resolves the issue and hopefully meets everyone's needs!
