### ISSUE TITLE
Test runner is failing to open. 

### ISSUE THREAD

**Issue by kakkarsk** [cypress-io/cypress#26445]
### Current behavior

<img width="1134" alt="Screenshot 2023-04-06 at 10 28 42 AM" src="https://user-images.githubusercontent.com/36343650/230435892-6bfb7050-0162-4ac6-8bc3-06ed3bb68dd9.png">
<img width="883" alt="Screenshot 2023-04-06 at 10 27 55 AM" src="https://user-images.githubusercontent.com/36343650/230435930-59f96d7a-72e8-4802-bec8-41e9c3933f70.png">

Tried clearing cache, and closed all other Chrome browsers, still the same issue. 

### Desired behavior

When running this command, : node_modules/.bin/cypress open : It should open up the Cypress for me in Chrome browser.

### Test code to reproduce

When running this command, : node_modules/.bin/cypress open : It should open up the Cypress for me in Chrome browser.

### Cypress Version

12.9.0

### Node version

18.15.0

### Operating System

macOS ventura 13.3

**Comment by astone123** [comment]
@kakkarsk could you try launching cypress with `npx cypress open` to see if the behavior is different? Thanks

**Comment by jordanpowell88** [comment]
Does this work @kakkarsk ☝ ?

**Comment by lucasSnovais** [comment]
I still have the same issue. Did you find anything to solve it?

**Comment by jordanpowell88** [comment]
We are not replicate this. Can you send an example repo?

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
