### ISSUE TITLE
Specify Node.js without npm --local deprecation bug

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#26443]
### What would you like?

I would like to be able to use the version of Node.js specified in [.node-version](https://github.com/cypress-io/cypress/blob/develop/.node-version) to install yarn without receiving an error message.

### Why is this needed?

Executing `npm install yarn -g` should not produce warnings.

### Other

[.node-version](https://github.com/cypress-io/cypress/blob/develop/.node-version) currently contains `16.16.0`.

```text
$ node -v
v16.16.0
$ npm -v
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.11.0

$ npm install yarn -g
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
```

## Suggestion

This issue was solved in [npm v8.12.1](https://github.com/npm/cli/releases/tag/v8.12.1).

So perhaps you could bump to at least Node.js `16.17.0` (includes npm `8.15.0`), if not Node.js 16.20.0 (includes npm `8.19.4`)?

**Comment by emilyrohrbough** [comment]
@MikeMcC399 The current node version is `16.16.0` because this is the node version shipped with the version of electron we currently use. When that version bumps, this will bump as well. We care because you can use the `system` node version or the `shipped` node version when running Cypress. 

This will update when #26246 or #26416 is merged. If we get onto electron@23/electron@24,  this will be node `18.12.1`.

**Comment by MikeMcC399** [comment]
@emilyrohrbough 

Thank you very much for the explanation! Good to know what the reason behind the setting is and that there is a prospect that Electron `21` will be updated to `23` or `24`, especially as Electron `21` is officially coming to its end of life.

 ~~https://releases.electronjs.org/release/v24.0.0 is a bit contradictory. At the top it says Node.js `18.14.0` and in the text it lists `18.12.1`. Either one would be good though!~~

Edit: Now consistently showing Node.js `18.14.0` against Electron `v24.0.0` on https://releases.electronjs.org/release/v24.0.0.
https://releases.electronjs.org/release/v24.1.2 is currently latest `stable`.

**Comment by nagash77** [comment]
@MikeMcC399 that electron upgrade is something we are planning as we speak.  Hopefully will happen soon.

**Comment by MikeMcC399** [comment]
@nagash77 

According to https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline Electron 21 entered end-of-life status on April 4, 2023. Did you come to any decision about migrating to a supported version?

**Comment by MikeMcC399** [comment]
@emilyrohrbough

> The current node version is 16.16.0 because this is the node version shipped with the version of electron we currently use. When that version bumps, this will bump as well. We care because you can use the system node version or the shipped node version when running Cypress.

[CONTRIBUTING: Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) says:

---

### Requirements

You must have the following installed on your system to contribute locally:

- [`Node.js`](https://nodejs.org/en/) (See the root [.node-version](.node-version) file for minimum version requirements. You can use [avn](https://github.com/wbyoung/avn) to automatically switch to the right version of Node.js for this repo.)

---

From your explanation it sounds like that should not be "minimum version requirements" but rather "exact version requirements".

Did I understand this correctly?

**Comment by emilyrohrbough** [comment]
@MikeMcC399 Cypress maintains a minimum node requirement that is specified [here](https://github.com/cypress-io/cypress/blob/develop/cli/package.json#L118). For development aligned, we use the same node version shipped with the electron version. If you'd like to update this verbiage, that would be great.

As for migrating to the next Electron version, it's always a time-consuming effort and we are intended to update soon. Cypress typically does not bump minor versions (often) so it reaching EOF only means we lose out on fixes that would be provided in a newer version. We will get updated soon 😄

**Comment by MikeMcC399** [comment]
@emilyrohrbough 

Many thanks again for your response. I'm going to close this issue because it is basically tied to the Electron update for which there are already open PRs:

- https://github.com/cypress-io/cypress/pull/26246
- https://github.com/cypress-io/cypress/pull/26416

The question about the wording in [CONTRIBUTING: Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) is best followed up through the following and I will look at providing new verbiage there:

- https://github.com/cypress-io/cypress/issues/26441
