### ISSUE TITLE
Not able to launch private window for Mozilla firefox browser using Cypress

### ISSUE THREAD

**Issue by anand-naik** [cypress-io/cypress#26457]
### What would you like?

We need to launch application under test using private window for firefox browser. But, Cypress does not provide any way for that.

### Why is this needed?

For Windows Native Authentication for our application(website), we need to launch our application using private window for firefox browser. But, Cypress does not provide any way for that.
Note: Our application needs Private Window. Private Browsing feature of firefox does not help

**Comment by nagash77** [comment]
@anand-naik Can you explain what you mean by private browser? Do you mean incognito mode?

**Comment by anand-naik** [comment]
@nagash77   Thanks for looking into the issue.

Private Browsing is similar to incognito mode. 

Firefox provides a way to work all the instances of firefox to use private browsing (incognito mode) : https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history#:~:text=You%20can%20also%20pin%20Firefox,the%20Private%20Browsing%20mode%20icon. 
I tried that approach but my application does not work with it.

Instead I need to launch private window of firefox and use application there. Private Window of firefox can be launched by:
Opening regular Firefox browser and clicking key combination: CTRL + SHIFT + P

<img width="960" alt="Firefox_PrivateWindow_02" src="https://user-images.githubusercontent.com/60295289/231379845-967949d0-50e9-40b2-98e9-b2dfd32b6218.png">

**Comment by nagash77** [comment]
ah got it @anand-naik !  I'lk forward this on to our product folks for consideration.  Thanks for submitting this idea!

**Comment by emilyrohrbough** [comment]
@anand-naik This can be accomplished today by using the [Before Browser Launch API](https://docs.cypress.io/api/plugins/browser-launch-api) and passing the [`-private-window`](https://wiki.mozilla.org/Firefox/CommandLineOptions#-private-window) firefox launch argument.

```js
module.exports = {
  e2e: {
    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'firefox') {
          // https://wiki.mozilla.org/Firefox/CommandLineOptions#-private-window
          launchOptions.args.push('-private-window')
        }

        // whatever you return here becomes the launchOptions
        return launchOptions
      })
    },
  },
}
```

**Comment by anand-naik** [comment]
@emilyrohrbough The solution you mentioned does not work. 
When any script execution is started, it gives below error message:
![image](https://github.com/cypress-io/cypress/assets/60295289/cf109a12-5f80-46aa-8876-e89b052d1e37)
@nagash77 could you also please look into it.

Cypress Version used: 12.12.0
Firefox version used:  113.0 (64-bit)

**Comment by nagash77** [comment]
@anand-naik please open a new issue with a reproducible example and our team will be happy to investigate.

**Comment by anand-naik** [comment]
@nagash77  as you suggested, I have opened new issue with reproducible example (https://github.com/cypress-io/cypress/issues/27188)
Thanks !!
