### ISSUE TITLE
Cy.visit does not work on this certain websites and I dunno why

### ISSUE THREAD

**Issue by justme6666** [cypress-io/cypress#26454]
### Current behavior

Hello Cypress community,

I am trying to surf my favorite club Fc Bayern Munich using cypress and get all the interesting news daily...

I am trying cy.visit('https://fcbayern.com/en') and unlike the other pages I am visiting, this one never loads...I don't understand why cy.visit doesn't work....

Your help would be greatly appreciated, if you ever manage to use cy.visit to work on this website, please tell me how...

I tried the standard cy.visit command and unline other websites this one doesn't load...

Thank you

### Desired behavior

In this situation cy.visit should load the specified page....

### Test code to reproduce

cy.visit('https://fcbayern.com/en')

### Cypress Version

latest versio

### Node version

latest version

### Operating System

windows 10

**Comment by nagash77** [comment]
Hi @justme6666 , This is not an intended use of Cypress.  I am closing this issue.  There are any number of reasons a site you don't control would be preventing Cypress from connecting.
