### ISSUE TITLE
Cypress V12 error: /root/.cache/Cypress/12.0.0/Cypress/Cypress: error while loading shared libraries: libatk-bridge-2.0.so.0

### ISSUE THREAD

**Issue by ralex7** [cypress-io/cypress#26455]
### Current behavior

I recently bumped the version of Cypress from 10 to 12 in my AWS codebuild project and now get the following error: `/root/.cache/Cypress/12.0.0/Cypress/Cypress: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory.` 

### Debug logs

```Text
I have done some debugging and have ran `ldd /root/.cache/Cypress/12.0.0/Cypress/Cypress` and came across this: 

libatk-bridge-2.0.so.0 => not found
libgtk-3.so.0 => not found
libatspi.so.0 => not found
libxkbcommon.so.0 => not found

I've tried Running command yum install at-spi2-atk but just get a timeout error.
Loaded plugins: ovl, priorities
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.corretto.aws/x86_64/repodata/repomd.xml: (28, 'SSL connection timeout').

How do I fix this so that Cypress runs as it did before with version 10 in codebuild?
```

### Cypress Version

12.0.0

### Node version

16.19.0

### Package Manager

npm

### Package Manager Version

8.19.3

### Operating system

Linux

### Operating System Version

Amazon Linux 2

**Comment by lmiller1990** [comment]
Hm, weird you hit this when upgrading. Not aware of any deps that would have changed from v10 to v12 around this. 

Take a look, maybe one of these works for you? https://github.com/puppeteer/puppeteer/issues/1598, I had a similar issue recently on Ubuntu, just had to install https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian.

**Comment by ralex7** [comment]
Nothing is really working. I have done additional debugging and have come across this 

2023-04-10T13:44:00.623Z cypress:cli clearing out the verified version
--
102 | 2023-04-10T13:44:00.623Z cypress:cli undefined DISPLAY environment variable
103 | 2023-04-10T13:44:00.624Z cypress:cli Cypress will spawn its own Xvfb
104 | 2023-04-10T13:44:00.624Z cypress:cli needs Xvfb? true
105 | 2023-04-10T13:44:00.624Z cypress:cli Starting Xvfb
106 | 2023-04-10T13:44:00.624Z xvfb lock filename /tmp/.X99-lock
107 | 2023-04-10T13:44:00.624Z xvfb lock filename /tmp/.X99-lock
108 | 2023-04-10T13:44:00.624Z xvfb setting DISPLAY :99
109 | 2023-04-10T13:44:00.625Z xvfb all Xvfb arguments [ ':99', '-screen', '0', '1280x1024x24' ]
110 | 2023-04-10T13:44:00.669Z xvfb checking if started by looking for the lock file /tmp/.X99-loc


2023-04-10T13:44:02.013Z cypress:cli error message: /root/.cache/Cypress/12.0.0/Cypress/Cypress: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
--
238 | 2023-04-10T13:44:02.014Z cypress:cli detecting arch { osPlatform: 'linux', osArch: 'x64' }
239 | 2023-04-10T13:44:02.018Z cypress:cli arm uname -m result: { stdout: 'x86_64' }
240 | 2023-04-10T13:44:02.021Z cypress:cli Stopping Xvfb
241 | 2023-04-10T13:44:02.021Z xvfb restoring process.env.DISPLAY variable
242 | 2023-04-10T13:44:02.021Z xvfb lock filename /tmp/.X99-lock
243 | 2023-04-10T13:44:02.021Z xvfb lock file /tmp/.X99-lock
244 | 2023-04-10T13:44:02.587Z xvfb lock file /tmp/.X99-lock not found when stopping
245 | [FAILED] Cypress failed to start.



`apt-get` and `yum install` don't work during the command phase of the buildspec. 

I also tried just --browser electron and --browser chrome and it doesn't affect the error.

I also want to mention it works just fine locally but only failing during the codebuild process which worked just fine with cypres v10. The command I'm running is `npm run cypress:run --browser electron`

**Comment by ralex7** [comment]
It seems I can fix the error with `- yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib`, however, during the codebuild build process this takes very very long to load and not ideal. 

Any thoughts on why this is happening? Is it a bug with cypress v12 + node 16 + codebuild? Is there a more efficient workaround?

**Comment by lmiller1990** [comment]
I have no idea, that's really strange. My next steps to debug would be finding the major/minor that introduces this - eg, 10.1, 11.2, 12.4? It'll be a bit of detective work and could take some time, but the surface area between 10.x and 12.x is large. I think we bumped Electron between those two, I suspect this is an issue with our of our upstream deps, electron is my guess. we updated Electron in Cypress 10.9 from v19 to v21: https://github.com/cypress-io/cypress/commit/f9ef9600fb49885c8825213ac863a813f5c7142f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L144 so that might be a good place to compare - Cypress 10.8 and 10.9.

**Comment by jordanpowell88** [comment]
@ralex7 are you able to provide a reproducible example?

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by mbaquerizo** [comment]
I came across this after upgrading from nodejs 12 to 16, which necessitated moving our builds from Amazon Linux 2 v3 to v4. Our Cypress version didn't change (v8). I suspect the linux version update was the cause, because installing the dependencies [per the docs/error message](https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies) fixed the issue.
```
yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
```

Hope this helps anyone else who might come across this.
