### ISSUE TITLE
Cypress browser becomes unresponsive when testing components if webpack-dev-server `static` option is used

### ISSUE THREAD

**Issue by ConnorHome** [cypress-io/cypress#26477]
### Current behavior

In a React + Webpack project, when using the `devServer.static = "./"` option the browser that Cypress is running will crash when any file that isn't directly used by the current component test is changed. For example, if I have a test which mounts a `<Button>` component, if I make changes to the component `.jsx` file or the `.cy.jsx` test file then Cypress will successfully re-run the test after changes; If however I were to edit any other file that isn't directly related to the test, then the browser will effectively crash - it becomes completely unresponsive and the only way to get it working again is the quit out of the test command from the command line or force close the effected browser and re-open from the Cypress app. 

I've managed to find a way around this for now by making use of the `webpackConfig` option in the Cypress component config.

**cypress.config.js**
```
…
component: {
  devServer: {
    framework: "react",
    bundler: "webpack",
    // The following function has "fixed" the issue
    webpackConfig: async () => {
      const modifiedConfig = await injectCustomConfig(webpackConfig);
      return modifiedConfig;
    },
  },
},
…
injectCustomConfig = (baseConfig) => {
  return new Promise((resolve) => {
    const modifiedConfig = { ...baseConfig };
    modifiedConfig.devServer.static = false;
    resolve(modifiedConfig);
  });
};
```

**webpack.config.js**
```
`…
devServer: {
    historyApiFallback: true,
    static: './',
    hot: true,
    open: true
},
…
```

Some other things I've noticed whilst troubleshooting:
- Any nested components of the mounted component can also be changed without causing the crash.
- It is an issue in Chrome, Electron and Firefox.
- There doesn't appear to be anything in the logs or in the browser that stands out as being an obvious issue.

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/1759352/231158807-92ec2ae9-f2bb-4d1e-a8a1-a5f112b0a168.png">

### Desired behavior

Cypress app shouldn't become unresponsive - if there is an issue it should report it.

### Test code to reproduce

Working on it.

### Cypress Version

12.8.0

### Node version

16.14.2

### Operating System

macOS 13.3.1

**Comment by jordanpowell88** [comment]
@ConnorHome thanks for creating an issue. I spent some time trying to reproduce but was unable to. Can you provide an example repo?

**Comment by ConnorHome** [comment]
Hi @jordanpowell88, thank you for attempting to reproduce. I'm afraid I haven't had any luck with a minimal repo either; the repo where this issue has reared its head is fairly old and has quite a few oddities so I think recreating it will be tricky. As I have the workaround I think I'll close this one.
