### ISSUE TITLE
Session cookie changes after first API call in vue.js app ngnix 

### ISSUE THREAD

**Issue by jay61189** [cypress-io/cypress#26486]
### Current behavior

After login into my app in cypress, which is developed in vue.js framework and uses Ngnix, 3 API's are called. First API has a correct  session cookie which I can verify in postman. Subsequent API's are having incorrect session ID and are failing because of that. All API's are called when I log into my app.

### Desired behavior

Session ID should remain same for all the API's which are called from UI

### Test code to reproduce

    context('Desktop view', () => {
        before(() => {
            cy.login(uName, pword);
        });
        //Additonal posts
        it('Check Additonal posts', () => {
            cy.wait(80000);
            feedvar.getpost().its('length').should('eq', 25);
            feedvar.getpost().eq(24).scrollIntoView();
            feedvar.getpost().its('length').should('eq', 50);
        });
    });

### Cypress Version

12.9.0

### Node version

v16.17.1

### Operating System

Windows 10 pro

**Comment by jordanpowell88** [comment]
@jay61189 Can you provide a reproducible gist or perhaps provide some more context in what your `cy.login()` command is actually doing. Vue version, etc

**Comment by jay61189** [comment]
@jordanpowell88 
cy.login() command is login in to the app. below is the code:

Cypress.Commands.add('login', (email, password) => {
	cy.visit(----------My Login URL-----------);
	cy.get('div.head-link > a').contains('Log in').click({ force: true });
	cy.get('div.input-group').find('input[name="userId"]').type(email);
	cy.get('div.password-eye').find('input[name="password"]').type(password);
	cy.get('button.mdscp-button--submit.mdscp-button--medium').click({ force: true });
});

Vue version: 2.6.8

**Comment by jordanpowell88** [comment]
> @jordanpowell88 cy.login() command is login in to the app. below is the code:
> 
> Cypress.Commands.add('login', (email, password) => { cy.visit(----------My Login URL-----------); cy.get('div.head-link > a').contains('Log in').click({ force: true }); cy.get('div.input-group').find('input[name="userId"]').type(email); cy.get('div.password-eye').find('input[name="password"]').type(password); cy.get('button.mdscp-button--submit.mdscp-button--medium').click({ force: true }); });
> 
> Vue version: 2.6.8

@jay61189 nothing looks abnormal to me and I'm unable to reproduce on my end. Can you provide me a reproducible example?

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
