### ISSUE TITLE
Cypress installs to wrong directory when updating while running

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#265]
I have a project in ~/Projects/my-project/src and it is added to Cypress. The Cy server is running.
When I click Update, the update is downloaded, Cypress quits and it gets installed.

After installing I'm still on the old version and Cypress is installed to ~/projects/my-projects/Content. My src folder is removed by Cypress :(

When I update Cypress when no runner is open, everything gets installed correctly.

**Comment by brian-mann** [comment]
Fixed in [`0.17.8`](https://github.com/cypress-io/cypress/wiki/Changelog#0178-10122016).
