### ISSUE TITLE
Cypress voltando para tela de specs

### ISSUE THREAD

**Issue by renanfabbris** [cypress-io/cypress#26500]
### Current behavior

Estou realizando um teste de click e o cypress está me redirecionando para a página de specs, não retornando nenhum erro ou log. Após passar o comando  cy.get(btnEditarAnuncio).click({force:true}), está acontecendo esse cenário.

### Test code to reproduce

import 'cypress-iframe';
import 'cypress-file-upload';
require('cypress-plugin-tab');
require('cypress-xpath');

import { nome_conmpleto_produto } from '../../../support/funcoes_automacao_painel_login';

var menuMarketing = '//*[@class="menu-content grid-wrapper list list-horizontal"]/li[5]'
var marketingMercadoLivre = '//*[@class="pointer list-item"]/ul[@id="Ferramentas5"]/li[@id="Item262"]/a'
var btnBuscar = '#btnBuscar'
var campoBusca = 'input[id="txtBusca"]'
var btnEditarAnuncio = '.icon-edit-circled.icon-size-24.text-secondary.table-cell'
var campoEditarPrecoAnuncio = 'input[name="txtPrecoAnuncio"]'
var precoAnuncio = '20000'
var btnBuscar = '//*[@class="inline-group"]/a[@id="btnBuscar"]'
var btnEnviarParaMercadoLivre1 = '#enviarAnuncioParaML'
var btnAnunciar = '#anunciar'

describe('Teste_Pool_2', () => {  
  //Editar Anuncio Mercado Livre
  it('Teste: 2- Editar Anúncio Mercado Livre',{pageLoadTimeout: 120000}, () => {
    cy.viewport(1920, 1920)
    cy.login()
    //Menu Configurações
    cy.xpath(menuMarketing).click()
    cy.xpath(marketingMercadoLivre).click({force: true})
    cy.get(campoBusca).click()
      .type(nome_conmpleto_produto)
    cy.xpath(btnBuscar).click()
    //cy.pause()
    cy.get(btnEditarAnuncio).click({force:true})
    cy.wait(10000)
    cy.get(campoEditarPrecoAnuncio).click().clear()
      .type(precoAnuncio)
    cy.get(btnEnviarParaMercadoLivre1).click()
    cy.wait(5000)
    //Validar mensagem de sucesso
    cy.contains('ANÚNCIO(S) ENVIADO(S) COM SUCESSO!', { matchCase: false })

   
   
  })
})

### Cypress Version

12.8.1

### Node version

v18.12.1

### Operating System

Windows 11 Pro

**Comment by nagash77** [comment]
Hi @renanfabbris , Unfortunately we do not offer support in languages other than english.  I am going to close this ticket.  Please feel free to update to include an english description of your problem and we will be happy to investigate.
