### ISSUE TITLE
Component Testing banner

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress#26511]
### What would you like?

This will be a new banner using out existing banner system, like this (Design is accurate in this screenshot, for text please use the requirements below).

<img width="1176" alt="Screenshot 2023-05-03 at 9 00 26 AM" src="https://user-images.githubusercontent.com/8340719/235941505-368ca3f1-46a0-4e56-b615-93b3fd31aed5.png">

Example variations:

![Screenshot 2023-05-03 at 10 12 22 AM](https://user-images.githubusercontent.com/8340719/235941766-7823825d-f868-41c2-b6cd-eed11936d52c.png)

## Rules

- CT banner shows if:
- there is no warning, error, or cloud banner to show
- at least 1 day since the docs CI prompt was shown
- at least 2 days since any cloud banner was dismissed
- at least 4 days since first using Cypress
- we detect a framework and bundler that would have automated setup
- the banner has not already been dismissed
- Cypress is in E2E mode
- CT is not configured

Note: using the existing TrackedBanner component with isAllowedFeature and isBannerAllowed in SpecsListBanners.vue will provide some of this behavior out of the box. A new set of rules like isAllowedFeature('ctAvailableBanner') could be added just for this, which would allow the bannerToShow computed value to return a new CtAvaiableBanner component only if it would otherwise return null

### Confirming CT banner was seen
We will add a new Banner ID ([here](https://github.com/cypress-io/cypress/blob/develop/packages/types/src/config.ts#L45)) called CT_052023_AVAILABLE: 'ct_052023_available'
Make a new CtBannerAvailable component. Follow a similar pattern to how TrackedBanner is used in LoginBanner.vue
eventData for the TrackedBanner
```
{
      campaign: 'CT Available',
      medium: 'Specs CT Available Banner',
      cohort: ''
}
```

### CT banner content

- Title: {framework} component testing is available for this project
- Title Icon: {framework} icon
- Body: You can now use Cypress to develop and test individual components without running your whole application. Generate the config in just a few clicks.
- Button 1: Quick setup
	- Goes to Project Setup in launchpad
	- Documents this via event-collect
	- see [Cloud PR](https://github.com/cypress-io/cypress-services/pull/5636) and [internal issue](https://github.com/cypress-io/cypress-internal/issues/585)
	- medium: CT Available Banner
	- cohort: ''
	- campaign: Quick setup
	- messageId
	- machineId
	- payload
	  - framework
	  - bundler
- Link: Read our guide
	- Onlink to docs
	- [on.cypress.io/component](http://on.cypress.io/component-survey)
	- UTM params to identify this banner was the source:
		- utm_medium: CT Available Banner
		- utm_source: default (Binary: App)
		- utm_campaign: Read our guide
		- utm_content: {framework}-{bundler}
	- Documents this via `/event-collect` with `campaign` `Read our guide` 
- Link: Give feedback
	- Onlink to Maze survey
		- [on.cypress.io/component-survey-q2-23](http://on.cypress.io/component-survey-q2-23)
		- https://t.maze.co/159701261
		- utm_medium: CT Available Banner
		- utm_source: default (Binary: App)
		- utm_campaign: Give feedback
		- utm_content: {framework}-{bundler}
		- machine_id: {machineId}
	- Documents this via `/machine-collect` with `campaign` `Provide feedback`

## Dismissing the banner

- Clicking the X
- Clicking the Not Interested link
- Dismissal is persisted in saved state at the project level

**Comment by marktnoonan** [comment]
@baus I mentioned I would tag you in this one before I got out of town!

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/26511?planning-poker) with Zenhub @astone123 @jordanpowell88 @marktnoonan @mike-plummer @warrensplayer

**Comment by lmiller1990** [comment]
Let's make sure we document the conditions under which this shows and share with CX - customers might reach out based on this CTA.

**Comment by lmiller1990** [comment]
It looks like some requirements are still not locked in - who do we need to unblock this?

**Comment by mike-plummer** [comment]
@lmiller1990 @marktnoonan Implementation is mostly done, pending reqs are visual/analytics items
1. Design & copy is not yet finalized - looking to nail this down by noon tomorrow
2. ~Need UTM params for two links in this banner~
3. ~Need survey link so an onlink can be configured~
4. Potential new requirement around recording an event when users click the button to try setting up CT so we can track machines that have tried vs succeeded - new endpoint being implemented in cloud, Mark is going to decide whether it's targeted for this sprint or for a later sprint
