### ISSUE TITLE
Add support for "text/x-html-parts"

### ISSUE THREAD

**Issue by suyashsingh12** [cypress-io/cypress#26514]
### What would you like?

Some web servers return response with type "x-html-parts". Cypress fails with following error

`

The content-type of the response we received from your web server was:
> text/x-html-parts

This was considered a failure because responses must have content-type: text/html
`

### Why is this needed?

This is needed to support web servers that return responses with content type as 'text/x-html-parts'

**Comment by nagash77** [comment]
I have never heard of this header type.  Can you please link to the documentation in the protocol standards?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
