### ISSUE TITLE
Not able to use cypress hook before fluently

### ISSUE THREAD

**Issue by AKumaarr** [cypress-io/cypress#26515]
### Current behavior

I  have added visit command in before hook, but the visit command runs only once in before hook.
For next test, there is no page loaded and test fails

### Desired behavior

Wanted that we can load the page once in before hook which can be used across different tests.

### Test code to reproduce
```js
describe('Test', () => {
  beforeEach(() => {
    cy.viewport(VIEWPORT_SIZE.XXL, 1000);
    cy.visit(HOMEPAGE_URL);
  });

    it('Homepage has hero image', () => {
      cy.get(heroImage).should('be.visible');
    });

// Test fails here as it does not load homepage for this test.
    it('should have footer on homepage', () => {
      cy.get(footer).should('be.visible');
  });
```

### Cypress Version

12.9.0

### Node version

18.13.0

### Operating System

macOS 13.3 (22E252)

### Other

Using beforeEach works but it increases the time of tests. I have 1000 tests running which took around 20 mins to complete.
Need to reduce this time.

**Comment by jordanpowell88** [comment]
@AKumaarr I wanted to clarify are you using a `before` hook like you mention in your description or are you using a `beforeEach` hook? The former will behave the way you are describing whereas the latter would be a bug. Can you provide a reproducible example?

**Comment by AKumaarr** [comment]
@jordanpowell88  I am using `before` hook. But what I remember , Before cypress version 10, if I use the visit command in `before`  hook , it was being passed to all the tests. With latest versions, we are isolating the tests, So in that case, it is also removing the webpage that was loaded for test1.
So previously, I load the webpage on `before` hook , then I need not to reload it for every tests in that suite. So iit took only 7 or 8 seconds for 10 tests
Now, I have to load the webpage using `beforeEach`, and it is taking around a minute to complete. With 1000 tests , my execution time is remarkable increased from 5-6 mins to 20 mins.

**Comment by jordanpowell88** [comment]
@AKumaarr Ok, I understand what you are describing now. We implemented Test Isolation in version 12 (see https://docs.cypress.io/guides/core-concepts/test-isolation). You can certainly turn this feature off but their are some tradeoffs. 

If you are doing something like a `login` in your `before` hook you should consider using `cy.session()` https://docs.cypress.io/api/commands/session
