### ISSUE TITLE
[Cypress grep] Error using grepFilterSpecs

### ISSUE THREAD

**Issue by nam-edi** [cypress-io/cypress#26530]
### Current behavior

When I use the grepFilterSpecs option, I have this error (@cypress/grep: 3.1.5):

<img width="1238" alt="Capture d’écran 2023-04-18 à 15 51 48" src="https://user-images.githubusercontent.com/16478637/232798876-2e56a8c0-128d-4c69-811d-7f58ba98122a.png">

The trouble comes from this code:
```
const options = {
			...taskOptions,
			ignore : taskOptions.ignore.concat(ignore)
		} ;
```
because ignore is undefined.

### Test code to reproduce

Here are the variables I use:

- grepTags: 'filter'
- grepOmitFiltered: true
- grepFilterSpecs: true

### Cypress Version

12.9.0

### Node version

v19.5.0

### Operating System

macOS 13.3.1

### Other

I managed to solve the problem by modifying it like this:
```
const options = {
			...taskOptions,
			ignore : (taskOptions.ignore || []).concat(ignore)
		} ;
```

**Comment by jordanpowell88** [comment]
@nam-edi can you provide an example repo?

**Comment by nam-edi** [comment]
Hello, sorry for the delay, no I can't share the repo, it is not public.

**Comment by nam-edi** [comment]
it works when switching to cypress 12.11, but it didn't work in 12.9. Thanks a lot for your help
