### ISSUE TITLE
Cypress isn't shared objects between "it" with cy.wrap

### ISSUE THREAD

**Issue by PavelRybalko** [cypress-io/cypress#26538]
### Current behavior

Can get string values but can't get object values stored by cy.wrap() between "it". Can't get alias in after hook with cy.get("@alias")
![image](https://user-images.githubusercontent.com/60709039/233057668-d2add1cd-44b4-432a-9524-fe729b768114.png)

### Desired behavior

Can get string object values by cy.wrap() between "it". Can get alias in after hook with cy.get("@alias")

### Test code to reproduce
```js
describe("Cypress isn't stored objects longer then one it", () => {
  before(function () {
    cy.wrap("sadsadas").as("string");
    cy.wrap([1, 2, 3]).as("array");
    cy.wrap({ a: "obj" }).as("obj");
  });

  after(function () {
    console.log(this.string);
    cy.get("@string").then((s) => console.log(s));
    cy.get("@array").then((s) => console.log(s));
    cy.get("@obj").then((s) => console.log(s));
  });

  it("first", function () {
    cy.get("@string").then((s) => console.log(s));
    cy.get("@array").then((s) => console.log(s));
    cy.get("@obj").then((s) => console.log(s));
  });

  it("second", function () {
    cy.get("@string").then((s) => console.log(s));
    cy.get("@array").then((s) => console.log(s));
    cy.get("@obj").then((s) => console.log(s));
  });
});
```
### Cypress Version

12.9.0

### Node version

18.14.0

### Operating System

Windows 10 19044.2364

**Comment by mjhenkes** [comment]
Aliases are cleared between tests: https://docs.cypress.io/guides/core-concepts/test-isolation#What-is-Test-Isolation


Are you able to change your `before` hooks to a `beforeEach`? That will fix your example code.

```js
describe("Cypress isn't stored objects longer then one it", () => {
  beforeEach(function () {
    cy.wrap("sadsadas").as("string");
    cy.wrap([1, 2, 3]).as("array");
    cy.wrap({ a: "obj" }).as("obj");
  });

  afterEach(function () {
    console.log(this.string);
    cy.get("@string").then((s) => console.log(s));
    cy.get("@array").then((s) => console.log(s));
    cy.get("@obj").then((s) => console.log(s));
  });

  it("first", function () {
    cy.get("@string").then((s) => console.log(s));
    cy.get("@array").then((s) => console.log(s));
    cy.get("@obj").then((s) => console.log(s));
  });

  it("second", function () {
    cy.get("@string").then((s) => console.log(s));
    cy.get("@array").then((s) => console.log(s));
    cy.get("@obj").then((s) => console.log(s));
  });
});
```

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by RuiSetwin** [comment]
"Unfortunately we have to close this issue due to inactivity" very nice.... or not...

**Comment by jennifer-shehane** [comment]
@RuiSetwin We'll look at your issue if you have new information. No response was provided to the original issue. Do you have a reproduction to share?
