### ISSUE TITLE
should("have.css") returns a pixel value when using inline percentage

### ISSUE THREAD

**Issue by ConnorHome** [cypress-io/cypress#26540]
### Current behavior

Given a React component with an inline percentage width, asserting `should("have.css", "width", "20%")` is failing as it asserts against the computed pixel width - is this a bug or expected behaviour?

```
it.only("has correct width", () => {
  cy.mount(<div className="root" style={{ width: "20%" }} />);

  cy.get(".root").should("have.css", "width", "20%");
});

Timed out retrying after 4000ms: expected '<div.root>' to have CSS property 'width' with the value '20%', but the value was '100px'
```

I can get around this with the following assertion, but I would expect the above to also pass.
```
cy.get(".root").should(
  "have.attr",
  "style",
  "width: 20%;"
);
```
  

### Test code to reproduce

N/A

### Cypress Version

12.9.0

### Node version

16.14.2

### Operating System

macOS 13.3.1

**Comment by jordanpowell88** [comment]
@ConnorHome thanks for creating the issue. Actually this is working as expected in returning the number of pixels. This would be valuable if you wanted to make sure `20%` at certain viewports equal a specific number of pixels.

You could accomplish the same type of test by changing your assertion just a bit to something like this:

`.should('have.attr', 'style').and('include', '20%')`
