### ISSUE TITLE
Paths from jsconfig.json doesn't work 

### ISSUE THREAD

**Issue by Marcelinna** [cypress-io/cypress#26571]
### Current behavior

I set path in jsconfig.json file 
```js
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "fixtures/*": ["cypress/fixtures/*"],
      "support/*": ["cypress/support/*"]
    }
  }
}

```

View in Visual Studio Code
![obraz](https://user-images.githubusercontent.com/59872096/234001722-e74c56d6-f2cd-4669-9386-64f745cce0c4.png)

Cypress
![obraz](https://user-images.githubusercontent.com/59872096/234002022-6ebd3719-292b-4b3c-a1fd-7c630adeda77.png)

### Test code to reproduce

```js
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "fixtures/*": ["cypress/fixtures/*"],
      "support/*": ["cypress/support/*"]
    }
  }
}
```
### Cypress Version

10.0.0

### Node version

v16.17.1

### Operating System

Windows 11

**Comment by jordanpowell88** [comment]
@Marcelinna can you provide me a reproducible example?

**Comment by Marcelinna** [comment]
@jordanpowell88 https://github.com/Marcelinna/CypressPath
when I run the test I see 
![image](https://user-images.githubusercontent.com/59872096/234387392-614751b5-53cc-4bb1-985c-f87d169a7d8a.png)


![image](https://user-images.githubusercontent.com/59872096/234387553-72f260ee-8471-419a-9531-b73152e5822f.png)

**Comment by warrensplayer** [comment]
@Marcelinna Thanks for the sample repo.

In order to use aliases for paths when importing files in your tests, you will have to configure a preprocessor.  You can follow the instructions here:  https://docs.cypress.io/api/plugins/preprocessors-api

If you do not wish to include a preprocessor, then you can use relative paths to files for your imports.

**Comment by Marcelinna** [comment]
@warrensplayer 
honestly I tried to add the webpack-preprocessor but i didn't manage to configure it properly. It seems to me that the documentation is more adapted to the older version of cypress.

**Comment by marktnoonan** [comment]
Hi @Marcelinna could you be more specific about what you tried in configuring the preprocessor, and how the docs are geared towards older versions? That's a problem we should fix. Also are you blocked at his point or is the workaround of using relative paths sufficient to let you move forward, even though it would be more convenient to use aliases?

**Comment by marktnoonan** [comment]
I'm going to close this for now since there has been 7 days of inactivity. Please comment with more details when you are ready and we can re-open the issue.

**Comment by Marcelinna** [comment]
@marktnoonan I want to configure webpack-preprocessor/ and use webpack alias in my project
https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor

I have Cypress version above 10 and I don't have plugin file any more,
![image](https://github.com/cypress-io/cypress/assets/59872096/70ec0803-3d1d-4670-bc2e-c2740037d981)
and I don't know how to configure webpack alias in cypress.config.js properly

![image](https://github.com/cypress-io/cypress/assets/59872096/fe628050-20d6-4513-8722-5a18c385f753)

**Comment by marktnoonan** [comment]
Thanks @Marcelinna, inside your `setuNodeEvents` function you can do exactly the same code as used to be in plugins. Looks like we should update the README in the webpack-preprocessor package.

Something like this should work the same as it would have before: 

```js
 const webpackPreprocessor = require('@cypress/webpack-preprocessor')
 const { defineConfig } = require('cypress')

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
		on('file:preprocessor', webpackPreprocessor())
    },
  },
})
 ```
 
 Let me know if this helps with your issue.

**Comment by Marcelinna** [comment]
@marktnoonan 
after this, I can create webpack.config.js in my test folder and set webpack alias ?


```
const path = require('path');


module.exports = {
  //...
  resolve: {
    alias: {
      Utilities: path.resolve(__dirname, 'src/utilities/'),
      Templates: path.resolve(__dirname, 'src/templates/'),
    },
  },
};

```

**Comment by Marcelinna** [comment]
@marktnoonan ?
