### ISSUE TITLE
Strange problem solved: Cypress failed to start. This is usually caused by a missing library or dependency. (Version Cypress 3.1.0 on Windows 10)

### ISSUE THREAD

**Issue by mlc-mlapis** [cypress-io/cypress#2657]
For several hours I struggled with the following problem when trying to run Cypress. After many tries, with all published tips and issues, I found out that the problem was related to the environment on my computer. Because my case could be very helpful to others, I posted it here.

Concretely the problem was the setting: **NODE_OPTIONS=--trace-warnings** (that setting was related to a totally different case 2 years ago). When I ... `set NODE_OPTIONS=` ... all problems disappeared.

```
Cypress failed to start.
This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
Command failed: C:\Users\...\AppData\Local\Cypress\Cache\3.1.0\Cypress\Cypress.exe --smoke-test --ping=558
```

**Comment by jennifer-shehane** [comment]
Hey @mlc-mlapis, thanks for sharing!

**Comment by 123ab123** [comment]
In which file/directory is this setting?

**Comment by cozmy** [comment]
This problem still occurs in 3.2.0;  `set NODE_OPTIONS=` worked!

**Comment by shlomiassaf** [comment]
Can confirm that `unset NODE_OPTIONS` worked for me in **Azure Devops** using `Hosted Ubuntu 1604`.

Without it I got the same error.

**Comment by aonomike** [comment]
I am facing this issue but when running a CI build on an ubuntu server. On which file should I add the `set NODE_OPTIONS= ` ? Thanks!

**Comment by jennifer-shehane** [comment]
**Here is the existing issue for this - https://github.com/cypress-io/cypress/issues/1676 This will be fixed in our next release (3.3.0) as we are upgrading Electron to 2.0.18.**

**Comment by realtebo** [comment]
I've the same issue but on Windows 10. Could it be the same cause? If yes, where/how to unset NODE_OPTIONS ?

I'm running Cypress using

    yarn run cypress run

I get his

```
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed: C:\Users\Utente\AppData\Local\Cypress\Cache\3.4.1\Cypress\Cypress.exe --smoke-test --ping=732

----------

Platform: win32 (10.0.18362)
Cypress Version: 3.4.1
error Command failed with exit code 1.
```

Same esit running `verify`

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
