### ISSUE TITLE
Adding to the documentation a description of how to use the webpack path alias in Cypress

### ISSUE THREAD

**Issue by Marcelinna** [cypress-io/cypress#26572]
### What would you like?

I want to use webpack alias in Cypress project, to avoid to long relative path.
 
const path = require('path');

```
module.exports = {
  //...
  resolve: {
    alias: {
      Utilities: path.resolve(__dirname, 'src/utilities/'),
      Templates: path.resolve(__dirname, 'src/templates/'),
    },
  },
};
```

I can't find clear solution for Cypress 10.0.0 and above

**Comment by emilyrohrbough** [comment]
@Marcelinna Can you please provide more information on what you are trying to accomplish and what you would expect to see? It is unclear what you are looking for.

**Comment by Marcelinna** [comment]
@emilyrohrbough I want avoid this import 
![obraz](https://user-images.githubusercontent.com/59872096/234780220-cd3b8a48-834f-47f8-a5af-54ce76c1004d.png)

I can use webpack alias? webpack.config.js ?

**Comment by adsl88788190-QwQ** [comment]
Hi @Marcelinna  , We can use  https://docs.cypress.io/api/plugins/preprocessors-api#Examples resolve it ^^
Example : https://github.com/cypress-io/cypress/tree/develop/npm/webpack-preprocessor#examples

```js
const webpackPreprocessor = require('@cypress/webpack-preprocessor')
module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
      const options = {
        webpackOptions: require('./webpack.config')
      }
      on('file:preprocessor', webpackPreprocessor(options))
    },
  },
})
```

**Comment by jennifer-shehane** [comment]
Closing as resolved.
