### ISSUE TITLE
Timeout override causing problems with Chrome 70/Electron 59 headless on MacOS

### ISSUE THREAD

**Issue by AaronRohrbacher** [cypress-io/cypress#2658]
### Current behavior:
Specific to MacOS: When using the `{timeout: xxxxx}` override, Chrome 70 and Electron 59 headless do not continue repeating GET requests as usual, causing a massive delay in actually rendering the element, well beyond my reasonable timeout override. This also ends up throwing off the afterEach function, weirdly. The problem does not happen in Electron 59 headed (cypress open), only headless (cypress run), and Chrome 70 (cypress open). Also does not seem to affect Windows versions (same version of Cypress, 3.1.0). 

### Desired behavior:

When waiting for an element to load, a GET request repeats until it renders when working in Electron 59 headless/Chrome 70 headed Windows, and the element loads when it should. Would expect the same behavior on MacOS version.

*Electron 59:*
The GET request repeats until the element loads. This is what I expect.
![image](https://user-images.githubusercontent.com/30248832/47525415-09e94300-d852-11e8-8ad0-c4f48c80886e.png)

*Chrome 70:*
The GET request hangs here with a spinner, and does not repeat. The element doesn't load when expected (well over two minutes, will generally load within about 30 seconds). 
![image](https://user-images.githubusercontent.com/30248832/47525546-5b91cd80-d852-11e8-8769-60c1571f5d3b.png)

### Steps to reproduce:

This is only happening when using the {timeout} override. Code example, where .fa-download is a button that loads after processing a pdf file:

```js
    cy.get('.fa-download', { timeout: 120000 }).should((button) => {
      expect(button).to.be.visible;
    });
```
### Versions

Cypress 3.10, MacOS Mojave (Windows not affected), Chrome 70/Electron 59 Headless (headed not affected)

**Comment by AaronRohrbacher** [comment]
Update: For whatever reason, applying MacOS Mojave's most recent security update fixed the problem in Chrome 70. The problem, however, persists in Electron headless (cypress run). Any ideas out there? As you can see, the app should be repeating the the GET when it gets a 202 back until the 200 appears.

**Comment by jennifer-shehane** [comment]
We'll need a reproducible example in order to look into this further.

**Comment by AaronRohrbacher** [comment]
@jennifer-shehane I think this function in our app might be the culprit:
```javaScript
    function _onSuccess(data,status,headers,config) {
      svc.response.status = status;
      if (status == 202) {
        svc.response.state = 'working';
        setTimeout(_pollRender.bind(null, data.id), 5000);
      }
      if (status == 200) {
        svc.response.state = 'completed';
        svc.response.url = data.download_url;
        svc.response.name = data.download_name;
        svc.response.processTime = data.elapsed_time;
        svc.response.is_final = data.is_final;
        resolveDeferred(svc.response);
      }
    }
```
The browser should wait 5 seconds between requests for a successful PDF generation, looking for a response of 200 instead of 202; In Cypress, I'm just waiting for the button to appear with `{ timeout: 60000 }`. This works fine (now) everywhere but in Electron Headless, and only on MacOS Mojave 10.14.1. So I'm just wondering why that browser wouldn't follow these instructions hah!

**Comment by AaronRohrbacher** [comment]
To be clear, when this problem presents, the browser does not repeat the GET request after 5 seconds when running Cypress. The first screenshot above is what I expect to happen, the headless browser does the second.

**Comment by jennifer-shehane** [comment]
If you know there will be a set timeout of 5 minutes waiting for an element to appear, I'd suggest utilizing `cy.clock()` to instantly jump ahead 5 minutes. Will save you the wait time in your tests. https://on.cypress.io/clock

That being said, I'm still not sure why this would fail in Chrome 70.

**Comment by AaronRohrbacher** [comment]
No set timeouts, the function shoots the request again every 5 seconds to see if wkhtml is done, usually 20-30 seconds (we shoot the 202 in the meantime). Very strange indeed, especially because this doesn't present on Windows machines. I'm nearly positive that that function is what's being ignored through Cypress- why is beyond me! For now, my workaround is to make the same request with `cy.request()` and poll it for the 200.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
