### ISSUE TITLE
cy.visit is not working while navigating from `https` url to `http` url

### ISSUE THREAD

**Issue by rakeshnambiar** [cypress-io/cypress#26586]
### Current behavior

cy.visit is not working while navigating from `https` url to `http` url. Here's the sample code.

```
  cy.visit('https://www.bbc.co.uk/')
  cy.visit('http://europepmc.org/')
  cy.visit('https://www.bbc.co.uk/')
  cy.visit('http://europepmc.org/')
```

However the below code block works well because the very first url is `http` url
```
  cy.visit('http://europepmc.org/')
  cy.visit('https://www.bbc.co.uk/')
  cy.visit('http://europepmc.org/')
  cy.visit('https://www.bbc.co.uk/')
```

### Desired behavior

It should able to redirect from `https` to `http` and `http` url to `https`

### Test code to reproduce

  cy.visit('https://www.bbc.co.uk/')
  cy.visit('http://europepmc.org/')
  cy.visit('https://www.bbc.co.uk/')
  cy.visit('http://europepmc.org/')

### Cypress Version

12.10.0

### Node version

v19.4.0

### Operating System

macOS Monterey

### Debug Logs

```shell
It just fails without any error message
```

**Comment by MikeMcC399** [comment]
@rakeshnambiar 

There is a JavaScript error on the site http://europepmc.org/. You would need to fix this to allow Cypress to run.

With `cypress/e2e/spec.cy.js` containing

```js
describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://europepmc.org/')
  });
});
```

then executing

`npx cypress run -s cypress/e2e/spec.cy.js`

shows the error

```text
  template spec
    1) passes


  0 passing (3s)
  1 failing

  1) template spec
       passes:
     ReferenceError: The following error originated from your application code, not from Cypress.

  > Wicket is not defined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at <unknown> (http://europepmc.org/:76:1)
```

Google Chrome also shows an error when accessing http://europepmc.org/

![image](https://user-images.githubusercontent.com/66998419/234478531-36bdd7e6-977a-4c44-b392-3cfdcc9e1f82.png)

**Comment by rakeshnambiar** [comment]
@MikeMcC399 Thanks for your reply. I agree that there's an error in the console. However, that's not the real problem which I am trying to highlight. Let me give you another example.

The below code works as expected:
```JavaScript
describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://www.columbia.edu/~fdc/sample.html')
    cy.visit('https://www.bbc.co.uk/')
  });
});
```

However, if I change the order this code doesn't work
```JavaScript
describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://www.bbc.co.uk/')
    cy.visit('http://www.columbia.edu/~fdc/sample.html')
  });
});
```

Please could you help me with it?

**Comment by MikeMcC399** [comment]
@rakeshnambiar 

Which browser are you testing with? Are you using the default Electron browser?

When you say it doesn't work, what do the logs show when you run `npx cypress run -s cypress/e2e/spec.cy.js`?

**Comment by MikeMcC399** [comment]
@rakeshnambiar 

This is not a bug. You need to refer to the Cypress documentation

[Cross Origin Testing](https://docs.cypress.io/guides/guides/cross-origin-testing)

**Comment by rakeshnambiar** [comment]
@MikeMcC399 the error which I can see it on Electrin browser is:

```
 CypressError: Timed out after waiting `60000ms` for your remote page to load.

Your page did not fire its `load` event within `60000ms`.

You can try increasing the `pageLoadTimeout` value in `cypress.config.js` to wait longer.

Browsers will not fire the `load` event until all stylesheets and scripts are done downloading.

When this `load` event occurs, Cypress will continue running commands.
      at timedOutWaitingForPageLoad (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:149324:72)
      at <unknown> (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:150298:16)
      at tryCatcher (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:20941:23)
      at <unknown> (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:16063:41)
      at tryCatcher (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:20941:23)
      at Promise._settlePromiseFromHandler (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:18876:31)
      at Promise._settlePromise (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:18933:18)
      at Promise._settlePromise0 (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:18978:10)
      at Promise._settlePromises (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:19054:18)
      at _drainQueueStep (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:15648:12)
      at _drainQueue (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:15641:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:15657:5)
      at Async.drainQueues (https://www.bbc.co.uk/__cypress/runner/cypress_runner.js:15527:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/samples.cy.js:4:7)
```

I have also the same issue on FF and Chrome browsers in the open mode. Moreover, I tried the `cy.origin()` command yesterday and that works only for domains and not the HTTP sites.

**Comment by rakeshnambiar** [comment]
Here's the error message while trying the `cy.origin` command

```
originhttp://www.columbia.edu/~fdc/sample.html
CypressError
cy.origin() failed to create a spec bridge to communicate with the specified origin. This can happen when you attempt to create a spec bridge to an insecure (http) frame from a secure (https) frame.
```

**Comment by MikeMcC399** [comment]
@rakeshnambiar 

Thank you for confirming that you get a timeout.

I don't think I can help you further here, so I have to leave it to the Cypress.io team to comment.

If you want to get help from the Cypress community you can reach them at https://on.cypress.io/discord. You would probably need to explain what you are trying to achieve and why you need two domains in the same test.

**Comment by rakeshnambiar** [comment]
Thanks a lot, @MikeMcC399 for your help. I found with the below settings it's working on Chrome. However, I will have the same issue on other browsers.

```
    chromeWebSecurity: false,
    experimentalModifyObstructiveThirdPartyCode: true,
```

**Comment by rakeshnambiar** [comment]
I am wondering if the Cypress.io team could provide me with a solution for other browsers too.

**Comment by mschile** [comment]
Hi @rakeshnambiar 👋, by default Cypress does not allow navigating between secure (https) and insecure (http) content. You can read more about it [here](https://docs.cypress.io/guides/guides/web-security#Insecure-Content). You could try putting the visits in `cy.origin` blocks:

```js
    cy.origin('https://www.bbc.co.uk/', () => {
      cy.visit('/')
    })

    cy.origin('http://www.columbia.edu/~fdc/', () => {
      cy.visit('/sample.html')
    })
```

**Comment by rakeshnambiar** [comment]
@mschile Thanks and that solves my issue. However, I noticed the error `props is undefined` when I use `cy.screenshot()` right after the `cy.origin()` command. Any idea?

![Screenshot 2023-04-27 at 09 10 59](https://user-images.githubusercontent.com/20258636/234801056-92497cb4-b9cf-44b1-8b6f-21705992c784.png)

**Comment by mschile** [comment]
Hmm, could you try moving the `cy.screenshot` to be within the `cy.origin` block:

```js
cy.origin('http://www.columbia.edu/~fdc/', () => {
  cy.visit('/sample.html')
  cy.screenshot({ capture: 'viewport' })
})
```

**Comment by rakeshnambiar** [comment]
Thanks @mschile that did the trick. Previously also it was working within the `cy.origin` block. However, the game changer here is `{ capture: 'viewport' }`

**Comment by rakeshnambiar** [comment]
@mschile I have another issue now connected to the same use case.

I understand by default the `cy.origin` command expects all the targetted commands must be mentioned underneath it. However, I am using `cucumber-preprocessor` and the cypress test flow belongs to many cucumber steps. This means it is not practical to put all the e2e scenario steps underneath of `cy.origin` command. 

What I observed here is : 

```javascript
  cy.visit('http://www.columbia.edu/~fdc/'')

  cy.origin('https://www.bbc.co.uk', () => {
    cy.visit('/')
  })

  cy.origin('https://docs.cypress.io/', () => {
    cy.visit('/')
  })
  ```
this works because it's a switch from `http` to `https`. But it won't work when the very first command is `https` navigation like : 

```javascript
  cy.visit('https://docs.cypress.io/')

  cy.origin('https://www.bbc.co.uk', () => {
    cy.visit('/')
  })

  cy.origin('http://www.columbia.edu/~fdc/', () => {
    cy.visit('/sample.html')
  })
  ```
 Do you think is this something the Cypress team could fix? 

Btw - I am using cypress version `12.12.0` and I know the below script also works but that doesn't solve my problem as I need to do lots of other steps as part of E2E tests and cannot include them in the `cy.origin` block.

```javascript
  cy.origin('http://www.columbia.edu/~fdc/', () => {
    cy.visit('/')
  })

  cy.origin('https://www.bbc.co.uk', () => {
    cy.visit('/')
  })

  cy.origin('https://docs.cypress.io/', () => {
    cy.visit('/')
  })
  ```
Attaching some screenshots for your reference : 
![Screenshot 2023-05-13 at 19 05 42](https://github.com/cypress-io/cypress/assets/20258636/4865727d-57cb-4fb5-a148-993201639de4)

![Screenshot 2023-05-13 at 19 07 17](https://github.com/cypress-io/cypress/assets/20258636/750ac009-3810-4b93-8c36-7abcd986c853)

**Comment by rakeshnambiar** [comment]
I forgot to mention that, by disabling the web security it works fine on Chrome. But doesn't work on FF. Is there any similar command like `chromeWebSecurity: false,` for FF too?

**Comment by chrisbreiding** [comment]
> I need to do lots of other steps as part of E2E tests and cannot include them in the cy.origin block.

What steps are there that can't be included in the cy.origin block?

> Is there any similar command like chromeWebSecurity: false, for FF too?

Afraid not. We really don't recommend `chromeWebSecurity: false` either since it introduces security vulnerabilities.

**Comment by rakeshnambiar** [comment]
@chrisbreiding Usually in the cucumber tests, mainly for the E2E scenarios, the scripts are scattered across multple `give` `when` and `then` blocks right? It is hard to copy all of them into the `cy.origin` block and we cannot call its a cucumber tests then. That's the issue I am currently facing.

**Comment by rakeshnambiar** [comment]
@chrisbreiding apologies for insisting too much on this. I really don't have any choice here. The latest issue which I am facing connected to this, I have `chromeWebSecurity: false,` on my cypress.config file and it is working fine in the `OPEN` mode. However, when I execute the test in `RUN` mode on chrome browser, I am unable to bi-pass the security. Is this expected? I tried passing something like `--config '{"chromeWebSecurity": false}'` in case the config is not read from the cypress.config file. Any thoughts on this is really appreaciated.

**Comment by chrisbreiding** [comment]
> Usually in the cucumber tests, mainly for the E2E scenarios, the scripts are scattered across multple give when and then blocks right? It is hard to copy all of them into the cy.origin block and we cannot call its a cucumber tests then. That's the issue I am currently facing

Unfortunately, I don't know if there's anything we can do within Cypress to make that easier. If there's a specific way we can, please open a new issue for it. Outside of that, it may be a good topic for [Discord](https://on.cypress.io/chat), since other members of the community might have suggestions on how to integrate Cucumber tests and cy.origin.

> The latest issue which I am facing connected to this, I have chromeWebSecurity: false, on my cypress.config file and it is working fine in the OPEN mode. However, when I execute the test in RUN mode on chrome browser, I am unable to bi-pass the security. Is this expected? 

No, that's not expected. Can you open a new issue with a reproducible example of that happening?

**Comment by chrisbreiding** [comment]
Since the original issue is resolved, I'm going to close this issue. Please open new issues for any additional problems you encounter.
