### ISSUE TITLE
The element does not respond to clicks on it when the software tests

### ISSUE THREAD

**Issue by VladysZav** [cypress-io/cypress#26593]
### Current behavior

The element does not respond to clicks on it when the software tests, in the same window this element does not respond to manual clicks. If you open a new window in the browser, the element responds to manual clicks. Browser Chrome.  The work takes place with Shadow Dom. Code works fine without errors. In Microsoft Edge browser it works fine.

https://user-images.githubusercontent.com/108288355/234553365-267ce89e-b628-47b5-8662-b2503be8c05a.mp4

### Desired behavior

The element must respond to a click from the software

### Test code to reproduce

Sorry, I can't provide

### Cypress Version

12,10,0

### Node version

18.16.0

### Operating System

Windows 19044.2846

**Comment by mschile** [comment]
Hi @VladysZav 👋, unfortunately, without a way to reproduce the issue it's going to be difficult for us to troubleshoot. Would you be able to recreate the necessary parts of the application in a reproduction repository by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) or by other means? Possibly related to https://github.com/cypress-io/cypress/issues/19260. Could you try the workaround suggested on that issue:

`.click({ position: 'top' })`

**Comment by VladysZav** [comment]
Hello! I tried the way you wrote, but it gives an error

![Screenshot_1](https://user-images.githubusercontent.com/108288355/234761257-a5e69cdd-bc3d-4d10-82a9-64c713556ca9.png)

**Comment by mschile** [comment]
Sorry, try `.click('top')`

https://docs.cypress.io/api/commands/click#Position

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
