### ISSUE TITLE
Missing page section after cy.visit() performed

### ISSUE THREAD

**Issue by alenocera** [cypress-io/cypress#26596]
### Current behavior

Top header of my web-app is not loaded at all and this happens only in Cypress interface.
<img width="1240" alt="cypress_runner" src="https://user-images.githubusercontent.com/104006742/234624688-0218b1dd-3665-4d50-ae31-53cafd7fd8d7.png">

No code issue or other weirds trace (console error for instance), just the header is not shown at all.

```js
const { defineConfig } = require("cypress");
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");

async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

module.exports = defineConfig({
  e2e: {
    setupNodeEvents,
    specPattern: "cypress/e2e/features/*.feature",
    //baseUrl: "https://www.saucedemo.com",
    baseUrl: "https://my-web-app.domain.io",
    chromeWebSecurity: false,
    env: {},
  },
});
```

### Desired behavior

Top header must be shown.
<img width="1967" alt="chrome_standard" src="https://user-images.githubusercontent.com/104006742/234624728-e722c1f7-af42-486b-92dc-ae78af8ef929.png">

### Test code to reproduce

Unfortunally I cannot complete this part due to internal company policy.

### Cypress Version

12.10.0

### Node version

18.16.0

### Operating System

macOS 13.3.1

**Comment by mschile** [comment]
Hi @alenocera 👋, unfortunately, without a way to reproduce the issue it's going to be difficult for us to troubleshoot. Would you be able to recreate the necessary parts of the application in a reproduction repository by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) or by other means? Could you try enabling [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/references/experiments) to see if that helps. Does the header flex its display in anyway such as being in an iframe?

**Comment by alenocera** [comment]
Hi @mschile 
thanks for the quick reply! I cannot push on repo because the web-app is not handled by me (as a SDET in my company) and I don't have access to the source.
Anyway I've enabled the key you wrote above but still the same behaviour, unfortunally. The header is not into an iframe. Seems a very strange behaviour. I spent a lot of hours to look around without results.

**Comment by mschile** [comment]
@alenocera, I would suggest debugging the web app to see if you can determine what triggers the header to not display. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
