### ISSUE TITLE
Cypress test runner is not responding frequently on Windows

### ISSUE THREAD

**Issue by OsmanEgretli** [cypress-io/cypress#26599]
### Test code to reproduce

![image](https://user-images.githubusercontent.com/99646672/234689567-0e053a38-d1c8-413a-84ac-2bdf2bdc9f71.png)
I just started learning on Cypress and opened a new project. I have two computers, one is a mac book pro and one is a windows 10 pc. I ran the same project on cypress in both. While it works properly and smoothly on my Mac computer, I experience heavy hang ups on my Windows computer.

```js
describe('My First Test Suite', function(){

it('My First Test Case',function(){

    cy.visit("https://rahulshettyacademy.com/seleniumPractise/#/");
    cy.get('.search-keyword').type("cuc");
})

})
```
 this is my only test
 
 can anybody help me?
 
![image](https://user-images.githubusercontent.com/99646672/234690902-6d3b01ee-4c73-443f-bba6-aac78960d9e0.png)

### Cypress Mode

cypress run

### Cypress Version

12.11.0

### Browser Version

Chrome 112.0.5615.138

### Node version

v18.16.0

### Operating System

Windows 10

### Memory Debug Logs

```shell
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\Osmane\OneDrive\Desktop\gitRepo\CypressAutomation\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\Osmane\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Osmane\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 10ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm exec cypress open
21 verbose argv "exec" "--" "cypress" "open"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 3ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:C:\Users\Osmane\AppData\Local\npm-cache\_logs\2023-04-26T19_58_42_125Z-
26 verbose logfile C:\Users\Osmane\AppData\Local\npm-cache\_logs\2023-04-26T19_58_42_125Z-debug-0.log
27 timing npm:load:logFile Completed in 5ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 20ms
31 silly logfile done cleaning log files
32 timing command:exec Completed in 100588ms
33 verbose exit 3489660927
34 timing npm Completed in 100624ms
35 verbose code 3489660927
```

**Comment by nagash77** [comment]
Hi @OsmanEgretli , can you explain a bit more about what you are seeing in your windows machine when you say "heavy hang ups"?

I would also suggest check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by Oegretli** [comment]
Hi Nagash , thanks for the interest. I've formatted my windows 10 and it is running real smooth now. It was running without format straight two years and i installed so many things. they caused it i suppose.

**Comment by nagash77** [comment]
Glad to hear you are up and running!
