### ISSUE TITLE
@cypress/grep Filter tests using substring is not working properly

### ISSUE THREAD

**Issue by suman8025** [cypress-io/cypress#26590]
### Current behavior

![image](https://user-images.githubusercontent.com/64846367/234520604-13a57863-4d25-42e0-b957-fa5751b89cae.png)

### Desired behavior

npx cypress run --env grep="-There is my test"

@cypress/grep: tests with "-There is my test" in their names

### Test code to reproduce

just install cypress grep and run : npx cypress run --env grep="auth user"
grep is not taking full substring only taking "auth" here

### Cypress Version

12.10.0

### Node version

14.18.0

### Operating System

windows 10

**Comment by suman8025** [comment]
Please help anyone

**Comment by mschile** [comment]
Hi @suman8025 👋, unfortunately, I wasn't able to reproduce your issue. The entire string is used to grep when I try it on Windows in PowerShell. Are you able to try using a different terminal?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
