### ISSUE TITLE
Cypress freezes all the time

### ISSUE THREAD

**Issue by matvlesia** [cypress-io/cypress#26608]
### Current behavior

When running any test, Cypress freezes and does not respond.
[logs.docx](https://github.com/cypress-io/cypress/files/11342029/logs.docx)

https://user-images.githubusercontent.com/118187575/234826176-00b8b48d-cd2f-4c46-9f29-240908a2a3cf.mov

### Desired behavior

Should run smoothly 

### Test code to reproduce

```
describe('first test', () => {
    beforeEach(() =>{
        cy.visit('https://example.cypress.io/')
    })

    it('verify link', () => {
        //cy.visit('https://example.cypress.io/')
        cy.contains('next').click()
        cy.url().should('include', '/commands/traversal')
        cy.get('div.container h1').should('have.text', 'Traversal')
    }) 

    it('verify link2', () => {
       // cy.visit('https://example.cypress.io/')
        cy.contains('assert').click()
        cy.url().should('include','/commands/assertions')
    })

    it('verify link3', () => {
       // cy.visit('https://example.cypress.io/')
        cy.get('a[href="/commands/actions"]').contains('select').click()
        cy.url().should('include','/commands/actions')
    })
})
```

### Cypress Version

12.11.0

### Node version

v18.16.0

### Operating System

macOs Ventura 13.3.1

**Comment by emilyrohrbough** [comment]
@matvlesia If you open the devtools in the browser, do you see any errors? Are there any errors surfaced in the launchpad?

**Comment by matvlesia** [comment]
> @matvlesia If you open the devtools in the browser, do you see any errors? Are there any errors surfaced in the launchpad?

Hi Emily
<img width="592" alt="Снимок экрана 2023-04-27 в 14 33 19" src="https://user-images.githubusercontent.com/118187575/234878243-a63fb1c0-1dfc-4c4e-8fc2-cd705be1a2cb.png">

**Comment by matvlesia** [comment]
<img width="596" alt="Снимок экрана 2023-04-27 в 15 01 06" src="https://user-images.githubusercontent.com/118187575/234885983-2f3a72ab-75c5-405a-a212-9c81c266e490.png">
