### ISSUE TITLE
Get 'uncaught:exception' for Clipboard API 

### ISSUE THREAD

**Issue by ymekhovs** [cypress-io/cypress#26609]
### Current behavior

I'm trying to execute tests for EV according to copying selected filters to url. and I faced that when I'm trying to click on the button, I have Uncaugh exception. I see that success notification is appeared after click, but no data is copied and test failed on this exception. I can catch this exception only in cypress frame and if I'm trying it to copy on staging without cypress frame, it works fine.
Also I tried to skip this exception not to fail test, yes its passed but still no data is copied.
![Screenshot 2023-04-27 at 14 01 58](https://user-images.githubusercontent.com/110389574/234845044-d783079e-5d7c-4b70-9ad8-50360050086e.png)
![Screenshot 2023-04-27 at 14 02 08](https://user-images.githubusercontent.com/110389574/234845111-8232d42b-9595-401a-a7f1-c6207524d4f7.png)

### Desired behavior

After clicking on button, data should be copied and I should be able to use this data. 

### Test code to reproduce
```js
it('Verify Successfully copying time range filters', () => {
        cy.get(S_DATE_PICKER).click()
        cy.get(S_QUICK_FILTER).contains('Last 48 hours').click();
        cy.get(S_DATE_PICKER_POPUP).contains('Select range').click()
        cy.get(ICON_COPY).click();
    });
```
### Cypress Version

12.8.0

### Node version

12.22.7

### Operating System

macOS Ventura

**Comment by nagash77** [comment]
Hi @ymekhovs , Can you share the full test?  It is helpful to know what URL this test is being run against.

**Comment by ymekhovs** [comment]
Unfortunately, you are not able to visit my application as for now its only possible to run with VPN. do we have any other options to validate it?

**Comment by nagash77** [comment]
@ymekhovs Unfortunately without a way to reproduce this problem or even see the website it is happening on we will not be able to debug this efficiently.  You might want to check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

I am closing this issue pending a reproducible example.  If you can eventually share one, please comment back ehre and we can reopen the issue.
