### ISSUE TITLE
SyntaxError: The following error originated from your test code, not from Cypress

### ISSUE THREAD

**Issue by varshanharshank** [cypress-io/cypress#26604]
### Current behavior

We have handled the uncaught exception code in the e2e.js file. Still, we are getting the below error frequently. It is happening for random test cases. 

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/81335781/234745610-6721773b-c79d-4c8a-b869-5369ddac5878.png">

### Desired behavior

This error should be caught in the Cypress.on('uncaught:exception' block

### Test code to reproduce

Unable to share repo due to security reasons

### Cypress Version

12.7.0

### Node version

v18.11.0

### Operating System

Linux (running scripts in jenkins)

### Debug Logs

```shell
cypress project is configured with cucumber and allure reports. Using the below dependency

 "@badeball/cypress-cucumber-preprocessor": "15.0.0",
 "@shelex/cypress-allure-plugin": "^2.28.0",
```

**Comment by nagash77** [comment]
Hi @varshanharshank Unfortunately without a reproducible example we will not be able to investigate this issue.  If at some point you can share an example please do and we can reopen.
