### ISSUE TITLE
Defining an event handler for 'fail' causes every test to pass

### ISSUE THREAD

**Issue by beaugunderson** [cypress-io/cypress#2661]
### Current behavior:

```js
//  in support/index.js
Cypress.on('fail', (error, runnable) => { return error; });

// in a test spec
describe('ugh', () => {
  it('should fail', () => {
    cy.get('nope').should('have.length', 50);
  });
});
```

this passes!

### Desired behavior:

it should not pass, or the documentation should be updated (but ideally it should not pass, because I'd like to send test failures somewhere to track flaky tests).

### Versions

macOS Mojave
Cypress 3.1.0

**Comment by beaugunderson** [comment]
https://github.com/cypress-io/cypress-documentation/issues/1045 was opened to fix the documentation issue but returning the error does not fix the issue. This is technically a duplicate of https://github.com/cypress-io/cypress/issues/2538.

**Comment by beaugunderson** [comment]
```js
Cypress.on('fail', (error, runnable) => { throw error; });
```

throwing seems to have the desired effect.

**Comment by beaugunderson** [comment]
the documentation issue is fixed, thanks! 👍

**Comment by folmert** [comment]
What if I want to mark a single test as failed but continue to run other subsequent tests?

Currently when a single test in `it()` block fails Cypress halts completely.

**Comment by jennifer-shehane** [comment]
@folmert Cypress should not halt on an `it()` block failure. It will halt if there was a failure in a `beforeEach`, `before` hook that is required to run before subsequent tests.

**Comment by shokaul** [comment]
> @folmert Cypress should not halt on an `it()` block failure. It will halt if there was a failure in a `beforeEach`, `before` hook that is required to run before subsequent tests.

: I am putting it in simple IT block : still it halts the test : i want it to list the error and then proceed to next it block : next function .and DO NOT halt the complete test : what is the best way here : please
