### ISSUE TITLE
Two tabs testing 

### ISSUE THREAD

**Issue by kirangaonkar016** [cypress-io/cypress#26611]
### What would you like?

Hi, I would like to be able to open 2 tabs and test it.
We have an application which opens up another application in a new tab and a connection is established via plexus interop. 

Users would enter some data in the first tab and it will reflect in the next tab for further operation. 

The most important thing we would like to test here is the connection. We want to check if the data from one application reflects in another or not.

Note: Stubbing, or avoiding opening the second tab and force open in the same tab is not helpful and will not test the required use case.

Please provide the capability of opening 2 tabs and verify this.

Thanks in advance.

### Why is this needed?

Since this is the most important thing we test in our application, and any subsequent test can only be tested if we can keep the 2 tabs open and test them.

**Comment by emilyrohrbough** [comment]
@kirangaonkar016 Please review: https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs

**Comment by kirangaonkar016** [comment]
@emilyrohrbough 

I have gone through the documentation. 

It's mentioned that there are apis to switch tabs. But not exposed.

I have a genuine use case to have 2 tabs open.

There is no workaround for the use case I mentioned above. Please suggest the workaround if you know.

**Comment by nagash77** [comment]
@kirangaonkar016 is this request different than this existing feature request for multi-tab support? https://github.com/cypress-io/cypress/issues/6251

**Comment by kirangaonkar016** [comment]
Yes. This is the same request.

It's a shame that cypress doesn't satisfy a necessary feature and say testing with two tabs  open is not a use case.

**Comment by nagash77** [comment]
@kirangaonkar016 we definitely understand this use case and I am sure there are valid scenarios where someone might desire this functionality.  Unfortunately at this point though we are not prioritizing this feature for development.  Doing a quick google search I found several posts talking about working around this limitation that you might want to check out.

Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by kirangaonkar016** [comment]
@nagash77 

How can you say those workarounds are end to end test?
If we mock something, it's not really end to end test at all. You can never say the application is tested end to end..

Cypress can not be used as an end to end testing tool. But may be a component testing tool.

**Comment by nagash77** [comment]
Hi @kirangaonkar016 If you feel that your specific use case cannot be tested adequately by Cypress in a way that you feel is appropriate you may need to explore other options.  However many people feel Cypress is a great tool for testing their application end to end.
