### ISSUE TITLE
Cached session not updated during test

### ISSUE THREAD

**Issue by DylannCordel** [cypress-io/cypress#26655]
### Current behavior

I use persistent session to avoid re-log users during tests. It works fine for some tests but my app update the sessionid of the user after changing it's password. Next test will file because cypress will restore the session with the old id, not the updated-one.

### Desired behavior

When a cookie is set during a nav with session : update the session and re-cache it.

### Test code to reproduce

```js
// command to login a user
Cypress.Commands.add('login', (user_type, location_to_check) => {
    cy.fixture('users/'+user_type+".json").then((user) => {
        cy.session(
            user,
            () => {
                cy.visit(Cypress.env("login_url"))
                cy.get('#id_email').type(user.email)
                cy.get('#id_password').type(user.password ? user.password : "*********")
                cy.get('form').submit()
                if(location_to_check){
                    cy.location('pathname').should('eq', location_to_check)
                }
            },
            {
                validate: () => {
                    cy.getCookie("sessionid").should("exist")
                },
                cacheAcrossSpecs: true,
            }
        )
    })
})
```

```js
describe('login / logout / change profile and password…', () => {
  it('login', () => {
    Cypress.session.clearAllSavedSessions()
    cy.login("customer", "/mon-compte/")
    cy.login("advisor", "/crm/")
    cy.login("scout", "/crm/")
  })
  // test above is ok

  
  it('change password for customer', () => {
    cy.login("customer")
    cy.visit("/mon-compte/profil/")
    // change password with the form
    cy.getCookie("sessionid").should("exist")  // session_id is still the old-one
    cy.get('.btn-td').click();
    cy.get('.alert > p').should('have.text', 'Le mot de passe a été modifié avec succès.');
    cy.getCookie("sessionid").should("exist")  // session_id is now the new-one (it's ok, BUT next test will fail)
  })
  
  it('fail', () => {
    cy.login("customer")  // cypress restore the session, BUT with the old session -id
    cy.visit("/mon-compte/profil/")  // so the server will consider the user logged out
  })
```
### Cypress Version

12.11.0

### Node version

18.16

### Operating System

Debian Bullseye

**Comment by emilyrohrbough** [comment]
@DylannCordel The behavior you have describe is the correct behavior of `cy.session()`. 	`cy.session()` will only capture and persist the cookies that are set within the session setup and validation. If a cookie is updated during the test, outside of the session command, it will not persist when the session is re-applied.

**Comment by DylannCordel** [comment]
Yes I understood it from the doc, but we sometime need to UPDATE the cached data and currently, cypress does not allow it.

**Comment by fnavarrodev** [comment]
so? what's the approach to fix this problem? I think is quiet common to modify a cookie or sessionStorage during the test.

**Comment by adrixgc** [comment]
I think this should be reopened and reconsidered. In our case, we store the JWT and it gets updated during the test, therefore it should be also updated in the localstorage. In the next test, the previous localstorage is restated so the JWT is incorrect.

**Comment by abhilash-ghosh** [comment]
Upvote for this!

We have some usecases where the cookie should be updated while running the test. For example, we store locale information in browser cookie. The user can update language and therefore locale in cookie should be also update. Since, cypress is restoring the outdated session, currently our tests are failing!
