### ISSUE TITLE
Cypress extension not working in chrome

### ISSUE THREAD

**Issue by jammsen** [cypress-io/cypress#26654]
### Current behavior

- We use virtual machines via Citrix to develop. 
- In that VM we have Chrome and Edge as browsers installed.
- Our proxy configuration is via System/IE/Edge settings and it includes wpad/pac scripts, which is not supported in Electron, so that browser isnt working
- Our IT team has policies via GPO in AD for Chrome and Edge to blacklist everything, unless the Chrome-Extension-ID is whitelisted. 

In the begining, before IT had whitelist the extension ID for Cypress ( caljajdfkjjjdehjdoimjkkakekklcck ), the addon could not be loaded in both browsers. After we added the ID, the addon can now be loaded. But both browser error in different ways: 
- Chrome: Browser starts but at start Cypress is still giving an error - "Whoops, we can't run your tests. This browser was not launched through Cypress. Tests cannot run." - CLI gives no errors, but i see a sub header in the browser saying "its beein remote controlled"
- Edge: Browser starts but does nothing and has the addon loaded when i look into extensions, the CLI of "npx cypress open" reads: "Still waiting to connect to Edge, retrying in 1 second (attempt 39/62)" - No header information of beeing remote controlled

### Desired behavior

Cypress extension can be loaded and we can test out of your VM with Chrome and Edge

### Test code to reproduce

- Fresh directory
- npm init - hit return until wizard is done
- npx cypress open - let the simple be created
- changed the standard testfile to "cypress/e2e/0-remote-environments/google-de.js"
- add following code:

```
/// <reference types="Cypress" />

describe('We visit google germany', () => {
  beforeEach(() => {
    cy.visit('https://www.google.de');
  });
  it('Should be able to open google main page', () => {
    cy.title().should('eq', 'Google');
  });

  it('Should be able to search for 1234 with agreeing to the cookie-agreement-layer', () => {
    cy.get('#L2AGLb').click();
    cy.get('textarea.gLFyf').click().type('1234').closest('form').submit();
    cy.get('#result-stats').should('exist');
    cy.title().should('eq', '1234 - Google Suche');
  });
});
```

### Cypress Version

12.11.0

### Node version

18.15.0

### Operating System

Windows 10 Enterprise - 22H2

### Debug Logs

```shell
npx cypress open fails to deliver to do the initial page, while there is no error log in the CLI.

When i "run" a test this happends:

$ npx cypress run --browser chrome --headed

Cypress detected policy settings on your computer that may cause issues. 

The following policies were detected that may prevent Cypress from automating Chrome:
 - HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ProxyMode 

For more information, see https://on.cypress.io/bad-browser-policy 

==================================================================================================== 

  (Run Starting)
  
 ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 │ Cypress: 12.11.0
 │ Browser: Chrome 113
 │ Node Version: v18.15.0 (C:\Program Files\nodejs\node.exe)
 │ Specs: 1 found (google.cy.js)
 │ Searched: cypress/e2e/**/*.cy.{js,jsx,ts,tsx} │ 
 └────────────────────────────────────────────────────────────────────────────────────────────────┘ 
 
 ────────────────────────────────────────────────────────────────────────────────────────────────────    Running: google.cy.js (1 of 1) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 18/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 19/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 20/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 21/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 22/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 23/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 24/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 25/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 26/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 27/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 28/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 29/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 30/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 31/62) 
 Still waiting to connect to Chrome, retrying in 1 second (attempt 32/62)
```

### Other

Please help

**Comment by jammsen** [comment]
I observed another behavior difference. I installed locally a clean Windows 10 Home VM with no proxies and tried my code and problems there too.

When i start Chrome over Cypress, in my local VM, i can have an existing Chrome open, it starts a new Process in its own window AND the normal extensions wont be loaded and the --user-data-dir parameter in Taskmanager is totally different.

Compared to when i do the same in the Citrix VM, i can either have normal Chrome open with tabs and when i try to start  Chrome over Cypress, it just opens a new tab, the new tab is just white, no extension side-loading and all of my extensions are already loaded in from before, when i now close the Chrome and start it again over Cypress it loads the Cypress extension, but also all of my others extensions, then it redirects to localhost and gives me "This browser was not launched through Cypress" error. When i look in taskmanager i see mixed --user-data-dir entries in that processes, compared to local.

**Local VM:**
Browser-compare:
![image](https://user-images.githubusercontent.com/2270806/236129365-5d4a3923-ea54-4471-bf3c-861eda9922e8.png)

Taskmanager:
![image](https://user-images.githubusercontent.com/2270806/236129712-baa067c8-98f4-412d-b32c-6f932973638c.png)

**Company Proxy in Citrix VM:**
Browsers:
![image](https://user-images.githubusercontent.com/2270806/236131372-33ed597f-c4f9-419a-936f-696924e56132.png)

Taskmanager:
Normal Chrome processes
![image](https://user-images.githubusercontent.com/2270806/236130991-7b9707f9-e33e-4e97-b710-5453c0d9492e.png)
Cypress Chrome processes
![image](https://user-images.githubusercontent.com/2270806/236132824-566ad9b0-5b90-473a-99a0-1fa3d69a8e0b.png)

**Comment by warrensplayer** [comment]
@jammsen Did you try any of the suggestions here? https://docs.cypress.io/guides/references/error-messages#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues

Usually, if cypress opens a new tab in an existing browser, that is because it is reusing a process that it previously started.  Can you try your test again with all Chrome instances stopped?

**Comment by jammsen** [comment]
Hey @warrensplayer 

> Usually, if cypress opens a new tab in an existing browser, that is because it is reusing a process that it previously started. Can you try your test again with all Chrome instances stopped?

Yeah i did already try that, in my last answer i wrote already that when all Chrome instances are closed it still injects some --user-data-dir stuff fromt he regular Chrome into it, which in itself gets company policies and fills in all extensions that should not be there.

> @jammsen Did you try any of the suggestions here? https://docs.cypress.io/guides/references/error-messages#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues

I cant really try or comment on that, because its a Citrix VM basically from a golden image with company policies via GPO in there, but afaik my IT-collegues are loonking into that. If it helps i can try to get an answert with more details for you.

**Comment by marktnoonan** [comment]
> If it helps i can try to get an answert with more details for you.

Hi @jammsen just curious if you got any follow up there. These types of problems with policies are difficult to track down from a distance. I'm not sure from this thread so far if there is a specific problem with Cypress that could be addressed to fix this.

**Comment by jammsen** [comment]
Hey @marktnoonan
after trying much more stuff out and talking to our IT-guys im pretty sure its down to GPOs and how we try to start Edge and Chrome and make them safe, that the procces-isolation is getting mangled and therfore a clean browser for Cypress getting started isnt done. I have to follow up with more testing with the IT-guys before i can rule out any Cypress need to fix something. When i habe new information i will reach out here, sorry for the delay.

**Comment by marktnoonan** [comment]
Got it @jammsen - for the time being I'm going to close this, just to clean up my incoming issues. But that is not intended to cut off discussion - If you comment back with more details this will show back up for us to triage again, and we can reopen it, so please do.
