### ISSUE TITLE
Change 'Processing' to 'Compressing' in terminal video output

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#26657]
### What would you like?

In the context of users being confused around where time is going into 'Processing' videos (is it compression, saving to disk, uploading to cloud?), we want to change the word 'Processing' to 'Compressing' in the terminal output when video's are compressed

Also ensure any other terminal or debug output is accurate in communicating 'compression' or 'upload' as appropriate, as opposed to the terminology of 'processing'. For example, there is a debug log about 'video not found - skipping processing', could this be more explicit to what is being skipped?

### Why is this needed?

This is a low effort fix that will allow users to know that changing the videoCompression option directly affects this action Cypress takes that's printed to the terminal.

**Comment by mahdikhashan** [comment]
@jennifer-shehane could you assign it to me?

**Comment by jennifer-shehane** [comment]
@mahdikhashan If you'd like to open a PR, our team will review the work. So feel free to implement.

**Comment by jennifer-shehane** [comment]
Adding additional requirements in the original comment: "Also ensure any other terminal or debug output is accurate in communicating 'compression' or 'upload' as appropriate, as opposed to the terminology of 'processing'. For example, there is a debug log about 'video not found - skipping processing', could this be more explicit to what is being skipped?"
