### ISSUE TITLE
Unable to visit outlook login page

### ISSUE THREAD

**Issue by Amplify367** [cypress-io/cypress#26666]
### Current behavior

Cypress browser test closes itself when clicking on sign in button

### Test code to reproduce
```js
cy.visit('https://outlook.live.com');

// Click the "Sign in" button
cy.contains('Sign in').click();

// Enter login credentials and submit form
cy.get('#i0116').type('username');
cy.get('#idSIButton9').click();
cy.get('#i0118').type('password');
cy.get('#idSIButton9').click();
```
### Cypress Version

v12. 9.0

### Node version

v12. 22.5

### Operating System

macOS

**Comment by nagash77** [comment]
Hi @Amplify367 , are you trying to login from your site using microsoft authentication?  Have you read through our [guides on using 3rd party auth](https://docs.cypress.io/guides/end-to-end-testing/azure-active-directory-authentication)?

**Comment by Amplify367** [comment]
Hi @nagash77 , I have tried using it through cy.origin also and making experimentalModifyObstructiveThirdPartyCode:true, 
Now browser does not closes but i am getting error at cy.origin can you help me with the coding part? 
I want to login to outlook.

**Comment by Amplify367** [comment]
```js
cy.visit('https://outlook.live.com');

// Click the "Sign in" button
cy.contains('Sign in').click();
cy.origin(
    'login. live.com', 
{
      args: {
        username,
      },
    },
    ({ username }) => {
      cy.get('input[type="email"]').type(username, {
        log: false,
      })
      cy.get('input[type="submit"]').click()
    }
  )
```
If you can help it would be a  great assist for me, getting error same domain.

**Comment by Amplify367** [comment]
Now failing at 
cy.origin(
    'login.live.com',
    {
      args: {
        password,
      },
    },
    ({ password }) => {
      cy.get('input[type="password"]').type(password, {
        log: false,
      })
      cy.get('input[type="submit"]').click()
      cy.get('#idBtn_Back').click()
    }
  )
Page not loading

**Comment by Amplify367** [comment]
Hi @mschile , I am able to login but on visiting outlook page getting chunk load error

**Comment by Amplify367** [comment]
@mschile @nagash77 
Failed resource: https://res.cdn.office.net/owamail/20230421002.17/scripts/owa.ven.graphql.m.js
Back Filled Errors: Unhandled Rejection: ChunkLoadError: Loading chunk 203918 failed.
(error: https://res-h3.public.cdn.office.net/owamail/20230421002.17/scripts/owa.ven.graphql.m.js):undefined%7CUnhandled Rejection: ChunkLoadError: Loading chunk 203918 failed.
(error: https://res-h3.public.cdn.office.net/owamail/20230421002.17/scripts/owa.ven.graphql.m.js):undefined%7CUnhandled Rejection: ChunkLoadError: Loading chunk 203918 failed.
(error: https://res-h3.public.cdn.office.net/owamail/20230421002.17/scripts/owa.ven.graphql.m.js):undefined%7CUnhandled

Can you assist me  here, "outlook mail home page not loading", able to automate login process failing at outlook home page with  above errors
Url at which it is failing:-https://outlook.live.com/mail/0

**Comment by mschile** [comment]
Hi @Amplify367 👋, I was able to reproduce your issue using the following test:

```js
it('should load outlook', () => {
  cy.on('uncaught:exception', () => {
    return false
  })

  cy.origin('https://outlook.live.com/owa', () => {
    cy.visit('/')
    cy.contains('Sign in').click()
  })
  
  cy.origin('login.live.com', () => {
    cy.get('input[type="email"]').type('<username>', { log: false })
    cy.get('input[type="submit"]').click()
    cy.get('input[type="password"]').type('<password>', { log: false })
    cy.get('input[type="submit"]').click()
    cy.get('#idBtn_Back').click()
  })

  cy.origin('https://outlook.live.com', () => {
    cy.contains('Outlook', { timeout: 20000 })
  })
})
```

Looking at the console errors there appears to be an issue with sub-resource integrity failing which is causing the `ChunkLoadError`. A change to `experimentalModifyObstructiveThirdPartyCode` may be needed.

What is your use-case for testing Outlook? Typically, we don't recommend testing websites that are not in your control.

**Comment by Amplify367** [comment]
Hey @mschile , thanks for responding! 
experimentalModifyObstructiveThirdPartyCode already set it to true, still facing the ChunkLoadError. 
Use case for outlook is that I have to read a particular email for my test flow using Outlook UI. 
It would a great help for me if you assist me to solve the ChunkLoadError issue. 
Thanks!

**Comment by mschile** [comment]
> A change to experimentalModifyObstructiveThirdPartyCode may be needed

> experimentalModifyObstructiveThirdPartyCode already set it to true, still facing the ChunkLoadError.

Sorry, I should've been clearer, I was saying that we (Cypress) would probably need to make changes to the `experimentalModifyObstructiveThirdPartyCode` functionality to support this workflow.

You could try using a `cy.intercept` to rewrite the [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity):

```js
cy.intercept('https://outlook.live.com/mail/0/**', (req) => {
  req.on('response', (res) => {
    res.body = res.body.replaceAll('s.integrity=a.sriHashes[i]', 's["stripped-integrity"]=a.sriHashes[i]')
  })
})
```

**Comment by Amplify367** [comment]
@mschile , Thanks a lot man !! It works, thank you so much for your assistance in this matter.
Now Outlook home page  is loading properly but when I want to click on search element getting error:- redirected more than 20 times , even cypress crashes. 
Can you please help me over this also?
