### ISSUE TITLE
Unable to create a new session

### ISSUE THREAD

**Issue by MariaPavithra17** [cypress-io/cypress#26665]
### Current behavior

So my application uses Microsoft login and then redirects back to the application.

I am trying to execute two test case files(.js) one after the other. I am doing so by importing them into a spec file and running it. The first step in both files is to login and then perform some task. Each file has different user credentials to login to. The first file with the first user, logs in and executes cases, but when the second file needs a different user login with his credentials, an error is thrown while creating the new session. I am calling a common login function for both files.

![error](https://user-images.githubusercontent.com/129038931/236105711-c1e6cb9c-03b2-4af3-980f-766ff01de6b3.png)

### Desired behavior

I expect a session created for the first user and then create another session for the next user. Right now, the second user session is not getting created.

### Test code to reproduce

This is the login command.
```js
Cypress.Commands.add("login", (user) =>

 {

 cy.sqlServer(select USERID, password from table name where User=${user}).then(function (result) { 

   var userID = result[0]
   var password = result[1] 
   const credentials = { userID, password }

   cy.session([userID, password], () => {
   cy.viewport('macbook-16')
   cy.visit('https://websitename.com/')
   cy.get('.login-btn').click()

   //clicking accept cookie button
   cy.get('#onetrust-accept-btn-handler').should('be.visible').click()

   //clicking microsoft login button
   cy.get('#microsoft-external-auth-button').should('be.visible').click()

   //redirected to microsoft login
   cy.origin('https://login.microsoftonline.com/', { args: credentials }, ({ userID, password }) => {

   //entering username

   //clicking next

   //entering password

    //clicking 'login' button

    cy.wait(1000)      })    })  })})
-------------------------------------------------------------------------------------------------------------------------------------
#This is how I am executing the two files in a separate spec.js file

import 'file1 path'
import 'file2 path'
```

### Cypress Version

12.11.0

### Node version

v18.12.0

### Operating System

windows

**Comment by mschile** [comment]
Hi @MariaPavithra17 👋, thanks for logging this issue! Do you log the first user out before the second test? Is the behavior any different if you don't use `cy.session`?

Would you be able to recreate the steps you posted above in a reproduction repository by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) or by any other means?

**Comment by MariaPavithra17** [comment]
Hi @mschile . Thanks for responding. I have tried logging out the first user and it still did not work. I HAVE to use cy.session because unlike the example I have given, I have 6 files that needs to run one after the other. The first 3 files need user1 so I use session and restore the user1 details for all 3 files. The 4th, 5th and 6th files need user2. I am expecting that after file 3, a new session for user 2 has to be created. 

I do have to mention that it does work as expected maybe once in like 50 runs or more. I make no changes in the code.

Another fact is that this issue is not observed in electron browser. But in chrome.

Unfortunately, I cannot recreate the issue for you because my code contains user credentials and website info that I would not be able to share publicly. Please let me know if you need any more information on the scenario.

**Comment by mschile** [comment]
> I HAVE to use cy.session because unlike the example I have given, I have 6 files that needs to run one after the other. The first 3 files need user1 so I use session and restore the user1 details for all 3 files. The 4th, 5th and 6th files need user2. I am expecting that after file 3, a new session for user 2 has to be created.

I would suggest trying to reduce what you are testing. In a single spec file, can you run two separate tests that log in with different users without `cy.session`. Then add in `cy.session` and so forth.

**Comment by MariaPavithra17** [comment]
@mschile I tried running without session and I get the same error.

"Then add in cy.session and so forth". Sorry, could you please explain more on what this means?

**Comment by mschile** [comment]
> Sorry, could you please explain more on what this means?

I'm trying to reduce the code/steps down to the minimum necessary to reproduce the issue. Have you had a chance to read over our [Microsoft auth guide](https://docs.cypress.io/guides/end-to-end-testing/azure-active-directory-authentication)?

Does a spec with the following structure fail:

`microsoft.cy.js`
```js
describe('Microsoft login', () => {
  afterEach(() => {
    // Do log out steps
  })

  it('logs user 1 in', () => {
    // Do steps to log user 1 in
  })

  it('logs user 2 in', () => {
    // Do steps to log user 2 in
  })
})
```

Note, I was able to log into Microsoft with two different users in one of our test projects.

**Comment by MariaPavithra17** [comment]
@chrisbreiding Hi, issue still exists, 
My file structure is as follows:

**file1.js**
```
`describe('Microsoft login', () => {
  after(() => {
    // Do log out steps
  })

before(()=>{
//Logs in with user1
}

  it('task 1', () => {
    // Do task1 with user 1
  })

  it('task 2', () => {
     // Do task2 with user 1
  })
})`
```
---------------------------------------------------------------------------------------------------

**file2.js**
```
`describe('Microsoft login', () => {
  after(() => {
    // Do log out steps
  })

before(()=>{
//Logs in with user2
}

  it('task 1', () => {
    // Do task1 with user 2
  })

  it('task 2', () => {
     // Do task2 with user 2
  })
})`
```
---------------------------------------------------------------------------------------------------------
**testFile.spec.js**

`import file1.js`
`import file2.js`

**Comment by chrisbreiding** [comment]
@MariaPavithra17 If you put all the tests into the spec file without importing them, does it still fail?

For example:

**testFile.spec.js**

```js
describe('Microsoft login - user 2', () => {
  after(() => {
    // Do log out steps
  })
  
  before(()=>{
	// Logs in with user1
  })

  it('task 1', () => {
    // Do task1 with user 1
  })

  it('task 2', () => {
     // Do task2 with user 1
  })
})

describe('Microsoft login - user 1' , () => {
  after(() => {
    // Do log out steps
  })

  before(()=>{
    // Logs in with user2
  })

  it('task 1', () => {
    // Do task1 with user 2
  })

  it('task 2', () => {
     // Do task2 with user 2
  })
})
```

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please post a minimal reproduction of the issue we can run and we'll re-open this issue.
