### ISSUE TITLE
writing into an existing json file

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#2666]
Hi,

It's possible the feature already exists but I don't know how to use it.

Let's say I have a json file like this >
```
[
	{
		"number1": "1",
		"number2": "2",
		"number3": "3",
		"number4": "4",
		"number5": "5",
		"number6": "6"
	}
]
```
And I want to replace the value of "number5" to "test5" (5 to test5).
Is there a way to do this ?
When I use the cy.writeFile function, it always erase the all content of the file before writing it.

Best regards.

**Comment by bahmutov** [comment]
Read the file, change the object and write it back

**Comment by mandriao84** [comment]
Can you give me an example pls

**Comment by bahmutov** [comment]
See http://on.cypress.io/readfile and http://on.cypress.io/writefile
