### ISSUE TITLE
Yarn Modern (3) using default pnp hangs at Initializing config...

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#26676]
### Current behavior

After installing Cypress with Yarn Modern (3.5.1) using the default Yarn Plug'n'Play the first start of `cypress open` hangs at "Initializing config..." after selecting E2E Testing.

Edit: The issue also affects Component Testing. I have however only given repro steps for the simpler case of E2E Testing.

### Desired behavior

If the app finds configuration errors it should not hang. Instead it should output an error message.

After opening the Cypress app for the first time, it should provide default configuration parameters and allow selection of example tests.

### Test code to reproduce

Execute the following in a `bash` terminal window:

```bash
mkdir cy-yarn-pnp
cd cy-yarn-pnp
npm install yarn@latest -g
yarn init -y
yarn set version berry # finds and installs 3.5.1
yarn add cypress@latest -D -E
yarn cypress open
```

Select E2E Testing
Click Continue (to accept addition of  `cypress.config.js`, `cypress/support/e2e.js`, `cypress/support/commands.js` and `cypress/fixtures/example.json`)

![image](https://user-images.githubusercontent.com/66998419/236487514-6dcfa18a-9418-40d9-8e2c-b4a4d9699924.png)

Note that `.yarnrc.yml` contains only:

```text
yarnPath: .yarn/releases/yarn-3.5.1.cjs
```

### Cypress Version

12.11.0

This issue is a regression from Cypress [12.9.0](https://docs.cypress.io/guides/references/changelog#12-9-0).

### Node version

18.16.0

### Operating System

Ubuntu 22.04

### Debug Logs

Debug logs go into an endless loop including

```text
'Error', message: 'Your configFile is invalid: /xxx/github/cy-yarn-pnp/cypress.config.js\n'
```

### Other

- This issue is related to https://github.com/cypress-io/cypress/issues/26567

### Workaround

Revert to Cypress [12.9.0](https://docs.cypress.io/guides/references/changelog#12-9-0).

**Comment by PilotConway** [comment]
I tried your steps here and a few others and was able to reproduce this. But interestingly its only under one condition: you install cypress locally then run yarn dlx. Likely theres something conflicting in yarn when you have cypress installed in the project locally but try to run dlx which like npx will download and run a different copy of cypress than the one installed in the repo. If I don't install cypress and just use yarn dlx or I install and use the installed copy, I don't get the infinite spinner. 

Not sure if this is helpful or not, but might help someone follow a lead to what might be the issue. 

These commands work (or at least get you to the bluebird error from #26567): 

```bash
mkdir cy-yarn-pnp
cd cy-yarn-pnp
yarn init -2 # shortcut to init a yarn app with berry by default
yarn dlx cypress open # download and run cypress, no cypress installed locally
```

```bash
mkdir cy-yarn-pnp
cd cy-yarn-pnp
yarn init -2 # shortcut to init a yarn app with berry by default
yarn add -D cypress
yarn cypress open # run the locally installed cypress
```

And like you posted, this one doesn't work: 

```bash
mkdir cy-yarn-pnp
cd cy-yarn-pnp
yarn init -2 # shortcut to init a yarn app with berry by default
yarn add -D cypress
yarn dlx cypress open # download and run a different cypress than the one in the package
```

**Comment by MikeMcC399** [comment]
@PilotConway 

Thanks for pointing out that `yarn dlx cypress open` will interpret that as cypress@latest, whatever has been previously installed by yarn. I had assumed `dlx` worked like `npx` and that is not the case.

Is there some other way in Yarn PnP to start exactly the version of Cypress which has been install by `yarn add`?

**Comment by PilotConway** [comment]
Yeah, running `yarn cypress` will just run what's locally installed.

**Comment by MikeMcC399** [comment]
@PilotConway 
> Yeah, running yarn cypress will just run what's locally installed.

Thank you! I've taken `dlx` out of the steps to reproduce and I've removed the workaround section, since it doesn't seem to always work.

**Comment by PilotConway** [comment]
@MikeMcC399 Are you still seeing the error when running `yarn cypress open`? Because running it that way worked for me (in terms of this bug, and not #26567), and I didn't get the infinite spinner. 

The _only_ way I'm able to reproduce this specific bug is the combination of `yarn add -D cypress` and `yarn dlx cypress open`.

**Comment by MikeMcC399** [comment]
@PilotConway 

I can reproduce on Ubuntu 22.04 and Windows 11 with exactly

```bash
mkdir cy-yarn-pnp
cd cy-yarn-pnp
npm install yarn@latest -g
yarn init -y
yarn set version berry # finds and installs 3.5.1
yarn add cypress@latest -D -E
yarn cypress open
```
then

- Select E2E Testing
- Click Continue to accept the default file generation

and on both operating systems I get the Cypress rotating spinner.

It only hangs up the **first** time it is opened when immediately previously the config onboarding has been carried out.

**Comment by PilotConway** [comment]
@MikeMcC399 Interesting. Well then, guess it's not just mismatched cypress versions. 🤷‍♂️

**Comment by MikeMcC399** [comment]
This is a regression from Cypress [12.9.0](https://docs.cypress.io/guides/references/changelog#12-9-0), so the workaround would be to revert to Cypress `12.9.0`. It appears to be related to extensive Yarn Plug'n'Play changes made in Cypress PR https://github.com/cypress-io/cypress/pull/26452 for Cypress [12.10.0](https://docs.cypress.io/guides/references/changelog#12-10-0).

If Cypress has already been successfully set up using version `12.9.0` or earlier and then Cypress is updated to version `12.10.0` or `12.11.0` then starting the Cypress App with `yarn cypress open` does not lead to the app hanging at "Initializing config...", instead, when "E2E Testing" is selected in the Cypress App, "Cypress configuration error" appears and no test can be run. On Ubuntu `22.04` the error message is:

```text
Your application tried to access bluebird, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: bluebird Required by: packages/config/src/project/

Require stack:

./packages/config/src/project/utils.ts
```

The `bluebird` error message is also reported in https://github.com/cypress-io/cypress/issues/26567#issuecomment-1536178066 for E2E testing.

**Comment by MikeMcC399** [comment]
The hang is also reproducible on Cypress `12.10.0` & `12.11.0` when selecting Component Testing after Framework dependencies have been installed and on the first time of confirming the Cypress config files to set up by clicking on Continue.

On subsequent starts of `yarn cypress open` on Ubuntu 22.04 the `bluebird` error is displayed and there is no hang.

**Comment by chrisbreiding** [comment]
Thanks for reporting and looking into this. I was able to reproduce it as well. I'll forward it to the appropriate team. They'll evaluate the priority of this ticket and consider their capacity to pick it up. Please note that this does not guarantee that this issue will be resolved.
