### ISSUE TITLE
Update workflows with deprecations

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#26674]
This issue concerns the GitHub repository, not the released Cypress product:

### What would you like?

GitHub workflows should not start failing due to removal of `node12` (May 18, 2023) and `set-output` (June 1, 2023) support.

### Why is this needed?

Cypress relies on workflows for CI purposes. If these fail, it may not be possible to update or release the product as desired.

### Other

Some GitHub workflows generate deprecation warnings due to using old versions of GitHub JavaScript actions. They threaten to fail after May 18, 2023 if they are not updated in time.

In addition to the above problem, [.github/workflows/update-browser-versions.yml](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/update-browser-versions.yml) is also using `set-output` which is scheduled to stop working on June 1, 2023.

## Suggestions

In affected workflows in [.github/workflows](https://github.com/cypress-io/cypress/blob/develop/.github/workflows):

1. change `actions/checkout@v2` to `actions/checkout@v3`
2. replace `set-output` by `$GITHUB_OUTPUT` in the form

    ```yml
    run: echo "{name}={value}" >> $GITHUB_OUTPUT
    ```

### node12

https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

"Node 12 has been out of support since April 2022, as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023.
Following on from our warning in workflows using Node 12, we will start enforcing the use of Node16 rather than Node12 on the 18th of May.

What you need to do
For Actions maintainers: Update your actions to run on Node 16 instead of Node 12 (Actions configuration settings)
For Actions users: Update your workflows with latest versions of the actions which runs on Node 16 (Using versions for Actions)"

### save-state / set-output

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

"To avoid untrusted logged data to use save-state and set-output workflow commands without the intention of the workflow author we have introduced a new set of environment files to manage state and output.

Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error."

**Comment by emilyrohrbough** [comment]
@MikeMcC399 Closing as the node version doesn't appear to be impacting any of our workflows. If I am mistaken, please specify which ones need updated.

**Comment by MikeMcC399** [comment]
@emilyrohrbough 

> Closing as the node version doesn't appear to be impacting any of our workflows. If I am mistaken, please specify which ones need updated.

I believe you are indeed mistaken and if no action is taken then workflows which are currently working and providing deprecation warnings will soon fail.

![image](https://user-images.githubusercontent.com/66998419/236527390-d8e61602-5825-4a5e-986c-514aef99db3c.png)

![image](https://user-images.githubusercontent.com/66998419/236527848-0f6dc4f3-84da-43b1-973b-60cd5dc95a7a.png)

![image](https://user-images.githubusercontent.com/66998419/236528196-3094c42c-57d9-4485-94c5-c36ed7efa34a.png)

**Comment by MikeMcC399** [comment]
## Workflows in danger

1. https://github.com/cypress-io/cypress/blob/develop/.github/workflows/snyk_sca_scan.yaml
2. https://github.com/cypress-io/cypress/blob/develop/.github/workflows/snyk_static_analysis_scan.yaml
3. https://github.com/cypress-io/cypress/blob/develop/.github/workflows/update-browser-versions.yml

## Deprecated usage

```text
$ grep actions/checkout@v2 .github/workflows/*
.github/workflows/snyk_sca_scan.yaml:      - uses: actions/checkout@v2
.github/workflows/snyk_static_analysis_scan.yaml:      - uses: actions/checkout@v2
.github/workflows/update-browser-versions.yml:        uses: actions/checkout@v2

$ grep set-output .github/workflows/*
.github/workflows/update-browser-versions.yml:          echo "::set-output name=branch_name::${{ env.BRANCH_NAME }}"
.github/workflows/update-browser-versions.yml:          echo "::set-output name=branch_exists::$(git show-ref --verify --quiet refs/remotes/origin/${{ env.BRANCH_NAME }} && echo 'true')"
.github/workflows/update-browser-versions.yml:          echo "::set-output name=needs_pr::${{ steps.get-versions.outputs.has_update == 'true' && steps.check-branch.outputs.branch_exists != 'true' }}"
.github/workflows/update-browser-versions.yml:          echo "::set-output name=needs_branch_update::${{ steps.get-versions.outputs.has_update == 'true' && steps.check-branch.outputs.branch_exists == 'true' }}"
```
