### ISSUE TITLE
Invalid or unexpected token -  An uncaught error was detected outside of a test

### ISSUE THREAD

**Issue by varshanharshank** [cypress-io/cypress#26682]
### Current behavior

Getting the below error while running the script in Jenkins. We are running around 200+ test cases with 13 parallel stages. We noticed that this issue is occurring frequently but not for the same test cases. Every run, this error occurs of different test cases and rarely one or two times this error is not showing up. 

If this error throws corresponding failed test cases are not showing in the allure report.

**Note:** 
We already updated the below code in the e2e.ts file and still this error is coming up
**Cypress.on('uncaught:exception', (err, runnable, promise) => {
  //to handle unhandled promise rejectio
  if (promise) {
    return false
}
return false
  })**

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/81335781/236557151-72bbc958-943f-402a-be0d-72e48fa944b4.png">

### Test code to reproduce

This is private repo. I am unable to share the repo

### Cypress Version

12.11

### Node version

node 12:18

### Operating System

unix

### Other

This project is integrated with **cypress+Cucumber+allure with Typescript** 

we are running all the test cases in the below docker image
**cypress/browsers:node12.18.3-chrome89-ff86**

**Dependencies are provided below**

  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "15.0.0",
    "@cucumber/cucumber": "^8.4.0",
    "@cypress/browserify-preprocessor": "^3.0.2",
    "@shelex/cypress-allure-plugin": "2.38.4",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.30.7",
    "allure-commandline": "^2.17.2",
    "cypress": "12.11.0",
    "eslint": "^8.3.0",
    "eslint-config-prettier": "^8.3.0",
    "mock-socket": "^9.1.2",
    "moment": "^2.29.4",
    "prettier": "2.5.0",
    "random-profile-generator": "^2.3.0",
    "typescript": "^4.5.3",
    "ts-node": "^10.9.1"
  }

**Comment by nagash77** [comment]
Hello @varshanharshank , are you using Cypress Cloud for your parallelization?  Do you see these same problems when running in a single process?  How are you narrowing down which test is throwing the error?

**Comment by varshanharshank** [comment]
@nagash77  No. we are not using Cypress Cloud for our parallelization. We are using the declarative pipeline syntax to run scripts in parallel in Jenkins.

Not tried yet to run scripts in a single process.

In the Jenkins logs, we could see the above-specified error with feature file name 

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/81335781/236850211-22616d4a-fc59-46e8-81de-305d3d669e9e.png">


**Note:**
When we re-run the build and see this kind of error in the different feature files (it means that this issue is not happening for specific feature files). sometimes, it ran all test cases without the above error.

**Comment by nagash77** [comment]
@varshanharshank please try running as a single process and see if the tests pass.  Try disabling as many variables as possible to simplify what we are trying to see is the root of the problem.

**Comment by varshanharshank** [comment]
When I try to run the single process and not see this issue (Single process will not work out for our project. it takes to complete the job more than 4 hours, so we must go for a parallel run). It Is happening this issue during the parallel run. 

The below solution is not working for latest cypress version.

Reference link 
https://davidwcai.medium.com/fix-cypress-invalid-or-unexpected-token-errors-in-parallel-runs-e887d7efa945

https://github.com/sorry-cypress/sorry-cypress/issues/40

**Comment by nagash77** [comment]
It looks like you are using sorry-cypress.  Any problem you encounter in their dashboard must be addressed by them.  I know they have limitations.  I would urge you to check out the official [Cypress Cloud](https://www.cypress.io/cloud/) which is developed in house at Cypress and offers the functionality you are looking for.
