### ISSUE TITLE
Task Execution Improvements

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#26699]
## Cypress should benefit from its monorepo structure
The Cypress monorepo has many packages, each depending on other packages which depend on other packages and so forth. These packages all have tasks that need to be executed - building, linting, testing, etc. We currently do a lot of manual orchestrating of these tasks via scripts in our monorepo. This results in a negative developer experience and oftentimes the duplication of many tasks.

### Problems
- The build processes in the Cypress monorepo are complex and difficult to understand
- We are often running tasks that don't need to be run (e.g. building packages that haven't changed)
- We have a lot of redundant code and scripts that we could replace with the use of a more sophisticated build tool
- We have many circular dependencies that should be addressed
- We are using many different tools currently to execute tasks (ex: `gulp`, `node`, `tsc`, etc)

### Goals
- Reduce build times (locally and in CI) 🏎️ 💨
- Lower CI Costs 💸 📉
- Make CI more reliable and less flaky ✅
- Simplify build process by extracting away task orchestration logic 🧠
- Delete redundant code and any outdated execution tools  🔥

### Strategy
- Leverage our monorepo structure and Lerna (Nx) features like:
  - [Task result caching](https://nx.dev/core-features/cache-task-results)
  - [Distributed task execution](https://nx.dev/core-features/distribute-task-execution)
- Unify scripts across all of our packages to make task outcomes more predictable

**Comment by lmiller1990** [comment]
Can we start doing these right now? What's next?

**Comment by astone123** [comment]
@lmiller1990 yes, the first thing we want to do is [enable caching for the `lint` task](https://github.com/cypress-io/cypress/issues/26701) which should be a good introduction to making these types of changes, and demonstrate how Cypress can benefit from task caching at a basic level

**Comment by jordanpowell88** [comment]
@lmiller1990 I have PRs just about ready to open but we didn't take these tickets into this sprint.

**Comment by lmiller1990** [comment]
All good @jordanpowell88, let's move it into review. In future let's try and make sure the tickets are in the sprint and in progress before we do the work, it'll help with our reporting and estimates. If you've got any others you think are valuable, can you add them to the next sprint's backlog?
