### ISSUE TITLE
Support for http2

### ISSUE THREAD

**Issue by muratkeremozcan** [cypress-io/cypress#26698]
### What would you like?

Cypress uses http, and the serial nature of it takes a bit of time when loading tests and switching between them.
Support for http2 would enable parallel calls for resources, significantly improving the time to load tests and switch between them.

### Why is this needed?

Performance is where Cypress falls short at scale. Developers want to have a snappy experience, load test fast and be able to switch between them without having to wait 5-10 seconds for the new test to finish loading.

### Other

I have shared a large project with Cypress support, the one being demoed here https://www.youtube.com/watch?v=bb0XR92AUNc. At around minute 5:20 you can see all the resources being fetched via http serially and this taking time for the component test to start.

**Comment by nagash77** [comment]
Hi @muratkeremozcan http2 support has been on our radar for awhile.  Unfortunately we have not been able to get around to implementing quite yet.  We do have an [existing feature ticket](https://github.com/cypress-io/cypress/issues/3708) tracking this requested functionality.  As such I am going to close this issue and ask that you follow along on that issue for updates on progress.
