### ISSUE TITLE
cy.exec() fails when a command with string literals (`dotnet ..`) is passed 

### ISSUE THREAD

**Issue by ramizalhaddad** [cypress-io/cypress#26703]
### Current behavior

When passing a command with backticks `dotnet ...` , the following error is thrown: 

     CypressError: `cy.exec('dotnet ...` failed because the command exited with a non-zero code.

Pass `{failOnNonZeroExit: false}` to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program...

### Test code to reproduce

pass a string literal into cy.exec()

### Cypress Version

11.2.0

### Node version

v14.17.3

### Operating System

Windows 10

**Comment by wolfpackt99** [comment]
same issue here trying to call a pwsh command:

v: 13.1.0

cy.exec just doesn't seem to work when i use a template literal or concatenated string

does not work
```
const someString = `pwsh script.ps1 ${thing1} ${thing2}`;
cy.exec(somestring);
```
works
`cy.exec("pwsh script1.ps1 value1 value2");`
