### ISSUE TITLE
Cypress doesn't run tests when using cypress/included:12.9.0

### ISSUE THREAD

**Issue by Thebarda** [cypress-io/cypress#26724]
### Current behavior

Hello,
Seems there is a bug while using Cypress docker image.

When starting the container in order to run component tests, the socket hangs up for any reason. Is the dev server not started?
<img width="1439" alt="Screenshot 2023-05-10 at 22 07 38" src="https://github.com/cypress-io/cypress/assets/12515407/5b4d9b8a-6fc4-4f65-83f3-1bedffe83e97">

### Desired behavior

Tests are launched

### Test code to reproduce

Here is my config
```
/* eslint-disable @typescript-eslint/no-var-requires */
const { defineConfig } = require('cypress');
const {
  addMatchImageSnapshotPlugin
} = require('@simonsmith/cypress-image-snapshot/plugin');

module.exports = defineConfig({
    component: {
      devServer: {
        bundler: 'webpack',
        framework: 'react',
      },
      setupNodeEvents: (on, config) => {
        addMatchImageSnapshotPlugin(on, config);
      },
      specPattern,
      supportFile: `cypress/support/component.tsx`
    },
    env: {
      ...env,
      baseUrl: 'http://localhost:9094'
    },
    reporter: 'mochawesome',
    reporterOptions: {
      html: false,
      json: true,
      overwrite: true,
      reportDir: `cypress/results`,
      reportFilename: '[name]-report.json'
    },
    video: true,
    videosFolder: `cypress/results/videos`
  });
};

```

And the command: `docker run --shm-size 4gb -v "$PWD:/tmp" -w "/tmp" -e DEBUG=cypress:* cypress/included:12.9.0 --component --browser=chrome`

### Cypress Version

12.9.0

### Node version

18.11.0

### Operating System

Macos 13.3.1

**Comment by Thebarda** [comment]
Small precision: When I run `cypress run --component --browser=chrome` locally, it works.

**Comment by warrensplayer** [comment]
@Thebarda Thanks for including your cypress config, but are you able to create a simple reproduction project to make sure we test the same scenario that you have?  That would make this the easiest to reproduce.  Thanks!

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
