### ISSUE TITLE
On trello application, after creating new board, I can't find side menu or navigation menu in cypress browser.

### ISSUE THREAD

**Issue by AbdelazizNassif** [cypress-io/cypress#26731]
### Current behavior

On trello application, after creating new board, I can't find side menu or navigation menu in cypress browser.

On normal browser, there is navigation menu and side menu to interact with.

### Desired behavior

Cypress browser view should be same as normal browser view

### Test code to reproduce
```js
/// <reference types="Cypress" />
import { faker } from '@faker-js/faker';

describe("template spec", () => {
  beforeEach( () => {
    cy.visit("https://trello.com/login");
    cy.get("#user").type("{{EMAIL}}");
    cy.get("#login").click();
    cy.origin("https://id.atlassian.com/" , ()=> {
      cy.get("#password").type("{{PASSWORD}}" + "{enter}")
    })
    cy.get('.boards-page-section-header-name').should('be.visible')
    cy.get('.boards-page-section-header-name').should('have.text', "YOUR WORKSPACES")
  });

  it('creates new board' , ()=>{
    cy.xpath("//span[text()='Create new board']").click()
    cy.get("[data-testid='create-board-title-input']").type("new board")
    cy.xpath("//div[contains(@id, 'create-board-select-visibility' )]" ). click()
    cy.xpath("//*[text()='Private']").click()
    cy.get("[data-testid='create-board-submit-button']").click()
  })


});
```
### Cypress Version

12

### Node version

16

### Operating System

Windows 11

**Comment by chrisbreiding** [comment]
I was able to reproduce the issue. It is happening because Trello is detecting that it's in an iframe and rendering differently. I found that setting `experimentalModifyObstructiveThirdPartyCode: true` in `cypress.config.js` fixes the issue.

**Comment by AbdelazizNassif** [comment]
Fixed. Thanks a lot.
