### ISSUE TITLE
Proposal: Make base path for cy.readFile / cy.writeFile configurable

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2673]
Address #2672 by adding a configuration option for the base path of `cy.readFile` and `cy.writeFile`. Currently, it's hard-coded as the project's root. With a configuration option, it makes it easier to have different base paths for different environments.

**Comment by jennifer-shehane** [comment]
Closing since this hasn’t gotten a lot of interest over the years.
