### ISSUE TITLE
Keypress events accumulates for each test

### ISSUE THREAD

**Issue by joelsson77** [cypress-io/cypress#26767]
### Current behavior

We are running Cypress component tests in a Angular monorepo using NX.

The problem i have noticed is that keypress events accumulates per test. 
For example, if i run a cy-file with 5 tests (mounting a component with a keypress event in it's constructor) then there will be 5 listeners of the same "type" when the fifth test runs.

The consequence will be, if i type downArrow in the fifth test, it will jump five steps down. 

If you run the code below, you will see that the number of fired events (in the browser console log) will be 15 (1+2+3+4+5) 
instead of 5. 
But if i use e.stopImmediatePropagation() the number of fired events will be as expected = 5

Another way to verify this behaviour is by setting breakpoints when running cypress in open mode

Is it a bug or is it just med doing bad?

### Desired behavior

That keypress events are not stacked up.

### Test code to reproduce
```js
//------------------TS-----------------------------

import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Observable, filter, fromEvent } from 'rxjs';

let total_nr_of_triggered_events = 1;


@Component({
  selector: 'myproblem-problem',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './problem.component.html',
  styleUrls: ['./problem.component.css'],
})

export class ProblemComponent {
  keyPress$: Observable<KeyboardEvent>;
    constructor() {
      this.keyPress$ = fromEvent<KeyboardEvent>(document, 'keydown');

      this.keyPress$.pipe(filter((e: KeyboardEvent) => e.key === 'ArrowDown')).subscribe(e => {
        //e.stopImmediatePropagation()
        this.someMethod()
      })
   }

  someMethod(){
    console.log('Total number of fired events ' + total_nr_of_triggered_events)
    total_nr_of_triggered_events++;
  }
}
```
```html
//--------------------HTML---------------------------

Just something with id #fname

<p>problem works!</p>
<form action="/action_page.php">
    <label for="fname">First name:</label>
    <input type="text" id="fname" name="fname"><br><br>
</form>
 ``` 

```js  
//--------------------CY---------------------------
  
import { TestBed } from '@angular/core/testing';
import { ProblemComponent } from './problem.component';

describe(ProblemComponent.name, () => {

  beforeEach(() => {
    TestBed.overrideComponent(ProblemComponent, {
      add: { 
        imports: [],
        providers: []
      }
    }) 
  })

  it('After this we have 1 event handler', () => {
    cy.mount(ProblemComponent,);
    cy.get('#fname').type('{downArrow}')
  })
  it('After this we have 2 event handlers', () => {
    cy.mount(ProblemComponent,);
    cy.get('#fname').type('{downArrow}')
  })
  it('After this we have 3 event handlers', () => {
    cy.mount(ProblemComponent,);
    cy.get('#fname').type('{downArrow}')
  })
  it('After this we have 4 event handlers', () => {
    cy.mount(ProblemComponent,);
    cy.get('#fname').type('{downArrow}')
  })
  it('After this we have 5 event handlers', () => {
    cy.mount(ProblemComponent,);
    cy.get('#fname').type('{downArrow}')
  })
})
```

### Cypress Version

12.11.0

### Node version

16.18.0

### Operating System

Windows 11 Education, 22H2

### Other

NX: 16.1.4

_No response_

**Comment by joelsson77** [comment]
I realized i don't unsubscribe from the keypress event. But should Cypress manage that?

**Comment by joelsson77** [comment]
I belive we can close this issue, my mistake, sorry. Problem solved by unsubscribing keypress event.

**Comment by marktnoonan** [comment]
Thanks for the report anyway @joelsson77, I was about to reply that setting event listeners on the `document` is not something Cypress currently cleans up, it seems like you have found a solution by unsubscribing so that's good! I think if you had the listener attached to some element rendered by the component, that would be fine too and the natural cleanup process before mounting would avoid this even if you didn't explicitly unsubscribe.
