### ISSUE TITLE
403 error and frozen test ?

### ISSUE THREAD

**Issue by Thomas-Cdi** [cypress-io/cypress#2676]
I have a spec which takes screenshots of a page, which display is modified based on the cookie from another website. I test several different profiles, which means I have a loop containing the two tests.

- First one visits settings page and sets the cookie so it persists into next test
- Second one visits the tested website and takes the screenshots

First version (`generic_test` in the provided repository) works fine. But in the second version (`generic_test_2`), I add a loop between several pages in the tested website, and suddenly cypress displays a `403` error when coming back to the settings page. It's not just a `403` response from the settings page, but something different. Furthermore, it freezes the test but stopping and relaunching it makes it starting at the point it froze. When running headless, it freezes at the same point.

Here is a repository to reproduce the problem
https://github.com/Thomas-Cdi/cypress-iti/

(Sorry for the bad styling, it's a first for me... and thanks)

**Comment by jennifer-shehane** [comment]
Hey @Thomas-Cdi, thanks for providing a reproducible repo!

Could you possibly reduce the amount of test code to as small as possible to reproduce the issue? There is a lot involved currently with the viewports and screenshots, etc. It would help a lot on our side in debugging the problem.

**Comment by Thomas-Cdi** [comment]
Done. I made different versions. It looks more and more like some kind of memory problem, because removing each one of my two inner loops prevents the problem, so does removing the "take screenshot" phase.
Buggy test is the third one, but I can also make it work by removing elements in the "pages" and "viewports" parts of the cypress.json file...

**Comment by Thomas-Cdi** [comment]
![cypress](https://user-images.githubusercontent.com/29724942/47794911-b4b1a380-dd21-11e8-9917-638999ddea26.png)

This is what I get in the console, so the 403 comes from the first site, but it still is an unexpected behaviour, as far as I can tell.

**Comment by jennifer-shehane** [comment]
The original repository linked above containing the reproducible code no longer exists.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by telangn** [comment]
@jennifer-shehane Hi, I am having this issue, below is my debug log. White screen
` cypress:server:stream_buffer appending chunk to buffer { bytesWritten: 0, chunkLength: 102 } +2s
  cypress:network:agent addRequest called { isHttps: true, href: 'https://login.globalmeet.com/users/authenticate' } +2s
  cypress:network:agent got family { family: 4, href: 'https://login.globalmeet.com/users/authenticate' } +0ms
  cypress:server:stream_buffer stream buffer writeable final called +1ms
  cypress:server:video:frames writing video frame +25ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video capture stderr log { message: 'frame=  459 fps= 33 q=13.0 size=    1792kB time=00:00:17.80 bitrate= 824.7kbits/s dup=154 drop=0 speed=1.29x    ' } +554ms
  cypress:server:video:frames writing video frame +40ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video:frames writing video frame +51ms
  cypress:server:video:frames video stream drained +1ms
  cypress:server:request received status code on request { requestId: 'request46', statusCode: 200 } +2s
  cypress:server:request successful response received { requestId: 'request46' } +0ms
  cypress:server:proxy received response for { url: 'https://login.globalmeet.com/users/authenticate', headers: { 'content-encoding': 'gzip', 'content-security-policy': 'object-src \'none\'; script-src \'unsafe-inline\' \'unsafe-eval\' https:; base-uri login.globalmeet.com https://identity-login.globalmeet.com login.yourcenturylinkworkplace.com login.pgiid.com', 'content-type': 'application/json', date: 'Thu, 10 Oct 2019 04:25:49 GMT', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'set-cookie': [ 'pgiid=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/; Secure', 'pgiid-cookie-optin=2020-10-09T04:25:45.682681Z; Max-Age=31535996; Expires=Fri, 09 Oct 2020 04:25:45 GMT; Path=/; Secure; HTTPOnly', 'pgiid-ul-remote=id=04034e61-fedb-4382-9576-a77e1c6c1a5a&token=b665d4f4-9e56-4a5b-b2a5-8df47ef592c4; Max-Age=5183999; Expires=Mon, 09 Dec 2019 04:25:48 GMT; Path=/; Secure; HTTPOnly' ], vary: 'Accept-Encoding,Origin', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-permitted-cross-domain-policies': 'master-only', 'x-pgi-xaction-transactionid': 'b798e13f-3514-48bf-a45d-a1cae80cfd6a', 'x-xss-protection': '1; mode=block', 'content-length': '191', connection: 'keep-alive' }, statusCode: 200, isGzipped: true, wantsInjection: false, wantsSecurityRemoved: false } +116ms
  cypress:server:server Got CONNECT request from director-na.globalmeet.com:443 +127ms
  cypress:https-proxy Writing browserSocket connection headers { url: 'director-na.globalmeet.com:443', headLength: 0, headers: { host: 'director-na.globalmeet.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' } } +10s
  cypress:https-proxy Got first head bytes { url: 'director-na.globalmeet.com:443', head: '\u0016\u0003\u0001\u0000�\u0001\u0000\u0000�\u0003\u0003$\u0014ѶO�\u0000(��\u0013��\u001b¤�\f$��Y�^�\u0010�����\u0000\u0000\u001c**�+�/�,�0̨̩�\u0013�\u0014\u0000�\u0000�' } +1ms
  cypress:server:cors Parsed URL { port: '443', tld: 'com', domain: 'globalmeet' } +5s
  cypress:server:server HTTPS request does match URL: https://director-na.globalmeet.com:443 with props: { port: '443', tld: 'com', domain: 'globalmeet' } +1ms
  cypress:https-proxy Not making direct connection { url: 'director-na.globalmeet.com:443' } +0ms
  cypress:https-proxy Making intercepted connection to 35669 +0ms
  cypress:https-proxy getting proxy URL { port: 35669, serverPort: 45545, sniPort: 35669, url: 'https://localhost:35669' } +0ms
  cypress:network:connect successfully connected { opts: { port: 35669, host: 'localhost', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +10s
  cypress:https-proxy received upstreamSocket callback for request { port: 35669, hostname: 'localhost', err: undefined } +2ms
  cypress:server:server Getting remote state: { auth: null, props: { port: '443', tld: 'com', domain: 'globalmeet' }, origin: 'https://web-na.globalmeet.com', strategy: 'http', visiting: false, domainName: 'globalmeet.com', fileServer: null } +7ms
  cypress:server:proxy handling proxied request { url: '/exchange?code=J1DeEf2ZOnu7CpksZeCRatJDOiJNXQyl&state=f385efff20eb51413026eb5bd3a2ff090f5280303f65ce2ad7034fb3f486b26b', proxiedUrl: 'https://director-na.globalmeet.com/exchange?code=J1DeEf2ZOnu7CpksZeCRatJDOiJNXQyl&state=f385efff20eb51413026eb5bd3a2ff090f5280303f65ce2ad7034fb3f486b26b', headers: { host: 'director-na.globalmeet.com', connection: 'keep-alive', 'upgrade-insecure-requests': '1', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36', accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', referer: 'https://login.globalmeet.com/', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-US', cookie: '__cypress.initial=true' }, remoteState: { auth: null, props: { port: '443', tld: 'com', domain: 'globalmeet' }, origin: 'https://web-na.globalmeet.com', strategy: 'http', visiting: false, domainName: 'globalmeet.com', fileServer: null } } +19ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://director-na.globalmeet.com/exchange?code=J1DeEf2ZOnu7CpksZeCRatJDOiJNXQyl&state=f385efff20eb51413026eb5bd3a2ff090f5280303f65ce2ad7034fb3f486b26b' } +134ms
  cypress:network:agent got family { family: 4, href: 'https://director-na.globalmeet.com/exchange?code=J1DeEf2ZOnu7CpksZeCRatJDOiJNXQyl&state=f385efff20eb51413026eb5bd3a2ff090f5280303f65ce2ad7034fb3f486b26b' } +0ms
  cypress:server:stream_buffer stream buffer writeable final called +134ms
  cypress:server:video:frames writing video frame +49ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video:frames writing video frame +49ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:request received status code on request { requestId: 'request47', statusCode: 403 } +99ms
  cypress:server:request successful response received { requestId: 'request47' } +0ms
  cypress:server:proxy received response for { url: 'https://director-na.globalmeet.com/exchange?code=J1DeEf2ZOnu7CpksZeCRatJDOiJNXQyl&state=f385efff20eb51413026eb5bd3a2ff090f5280303f65ce2ad7034fb3f486b26b', headers: { date: 'Thu, 10 Oct 2019 04:25:48 GMT', 'set-cookie': [ 'JSESSIONID=447ECE51B5DFE594CC9951E83BE352D0; Path=/; Secure; HttpOnly' ], 'www-authenticate': 'Basic realm="Realm"', 'x-pgi-xactn': 'd9efb89a-e7d2-4e50-931f-89397534bf5b', 'content-length': '0', connection: 'keep-alive' }, statusCode: 403, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false } +80ms
  cypress:server:video:frames writing video frame +46ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video:frames writing video frame +48ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video:frames writing video frame +55ms
  cypress:server:video:frames video stream drained +1ms
  cypress:server:video:frames writing video frame +57ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video:frames writing video frame +49ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video:frames writing video frame +43ms
  cypress:server:video:frames video stream drained +0ms
  cypress:server:video:frames writing video frame +50ms
  cypress:server:video:frames video stream drained +0ms
`

**Comment by jennifer-shehane** [comment]
@telangn If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
