### ISSUE TITLE
CORS error bypassed in Chrome even if webSecurity is set to true

### ISSUE THREAD

**Issue by madbreena** [cypress-io/cypress#26766]
### Current behavior

Hello all!

We have been testing our integration with an API through UI using Cypress. We recently discovered a bug where we get a CORS error when calling an event request (due to custom headers). This is the expected behaviour since there was something missing from the API implementation. 

However, our automated tests never failed as the preflight request was never made so we had false positives.
In our configuration, we have set `chromeWebSecurity: true` but the CORS error would only occur when requesting outside Cypress runner and never when running tests (both head/headless).

Here is how the event is sent via Cypress Runner - Chrome Version 113.0.5672.93:
![Screenshot_52](https://github.com/cypress-io/cypress/assets/23477928/24845bd9-3de9-42b9-bd55-99ba56b635f4)

Here is how the event is sent via Chrome Version 113.0.5672.93 (outside Cypress):
![Screenshot_53](https://github.com/cypress-io/cypress/assets/23477928/f31cd6c0-8c6c-41a2-8130-66386f9779f7)

The only workaround I have so far is by intercepting the OPTIONS request to get the preflight check on Cypress. I am wondering whether this is a Cypress' bug and/or there is a better solution or workaround to this that you could suggest.

Thank you!

### Desired behavior

Since `chromeWebSecurity: true` I would expect CORS errors to occur as they do outside Cypress.

### Test code to reproduce

We intercept the event request as follows:

`cy.intercept('https://requestURL/endpoint').as('sendEvent');`
and then access it by:
`cy.wait('@sendEvent');`

The only way I managed to workaround this issue and get the preflight check on Cypress Chrome was to also intercept the OPTIONS request:
`cy.intercept('OPTIONS', 'https://requestURL/endpoint').as('sendEventOPTIONS');`

![Screenshot_56](https://github.com/cypress-io/cypress/assets/23477928/5c9ca08b-3694-4b43-b58a-834874b61d8b)

### Cypress Version

10.11.0

### Node version

16.16.0

### Operating System

Windows 10 Pro

**Comment by chrisbreiding** [comment]
@madbreena Would you be able to create a minimal reproduction that we can use to debug this issue? I recommend using [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) as a basis for it.

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
