### ISSUE TITLE
Replaced element causing test to fail

### ISSUE THREAD

**Issue by callumacrae** [cypress-io/cypress#2677]
I think this is a less a bug and more some unexpected behaviour, but figured I'd let you know…

### Current behavior:

See test case below. The test fails as `.get()` has found the old element, but the child doesn't exist on that element, and never will.

### Desired behavior:

The test should pass.

### Steps to reproduce:

Here is a shorter version of my test:

```html
<ul class="some-element"><li>Some old text</li></ul>

<button onclick="handleClick">Change element</button>

<script>
  function handleClick() {
    document.querySelector('.some-element').outerHTML = '<ul class="some-element"><li>Some new text</li></ul>';
  }
</script>
```

```js
cy.get('button').click();
cy.get('.some-element').contains('Some new text');
```

It's not actually like this, the real version is in Vue, but something like this is happening.

### Versions

cypress 3.1.0, chrome on OS X - seems fairly fundamental though so imagine it happens everywhere

**Comment by callumacrae** [comment]
Also, my workaround for now:

```js
cy.get('.some-elements-parent').contains('Some new text');
cy.get('.some-element').contains('Some new text');
```

`.some-elements-parent` isn't being replaced, so this causes it to wait until `Some new text` exists, and then the second line checks that it's actually in the correct element.

**Comment by jennifer-shehane** [comment]
What is the error that you see when the `.get()` fails?

**Comment by callumacrae** [comment]
> CypressError: Timed out retrying: Expected to find content: 'Some new text' within the element: <ul.some-element> but never did.

**Comment by jennifer-shehane** [comment]
I can't recreate this issue from the HTML provided. Closing.
