### ISSUE TITLE
Cypress- strict-origin-when-cross-origin error

### ISSUE THREAD

**Issue by chaitali-diwanji** [cypress-io/cypress#26780]
### Current behavior

I'm facing the 401 (Unauthorized) error while navigating through sites on SSO login on the application. I am already using the cy.origin() to navigate to the other domain(production) on authentication but still can see '401 (Unauthorized)' on debug console &  and 'strict-origin-when-cross-origin' error on the header on network panel. However, the same navigation for the QA SSO is working. There is just the timeout error on Cypress console and nothing regarding the cross-origin navigation

### Desired behavior

Cypress should behave the same for any cross-origin navigation

### Test code to reproduce

cy.origin('PROD_SSO_CONNECT_URL', (username) => {
                cy.get('element').click({ force: true })
                cy.get('element').type(username)
                cy.get('element').click()
             })

### Cypress Version

"cypress": "^12.11.0"

### Node version

v16.17.0

### Operating System

Windows

### Debug Logs

```shell
Timed out retrying after 4000ms: Expected to find element: 'element', but never found it.
```

### Other

I'm using Cypress App for this execution. Let me know if you need any further details.

**Comment by nagash77** [comment]
Hi @chaitalid70 , unfortunately the test code you provided wont allow our engineers to replicate this problem.  Can you provide a reproducible example in a fork of [Cypress Test tiny](https://github.com/cypress-io/cypress-test-tiny) that illustrates the problem?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
