### ISSUE TITLE
Fix OS notification settings on Windows

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#26786]
There is an issue on Windows where when a user clicks the action to turn off notifications for Cypress, the Cypress app does not appear in the Windows notification settings. 

<img width="387" alt="Screenshot 2023-05-17 at 3 07 46 PM" src="https://github.com/cypress-io/cypress/assets/14275198/999d2fd2-9d9e-43f3-a0e3-0efd5dc40686">

This means that users cannot re-enable notifications for the Cypress app once they have been disabled at the OS level by clicking on the option above, because Cypress doesn't appear as an application that has notification settings.

<img width="478" alt="Screenshot 2023-05-17 at 3 07 58 PM" src="https://github.com/cypress-io/cypress/assets/14275198/c63667f0-c3ed-4fbd-aae9-8d3b664a5356">

I suspect that this has to do with the way that Cypress is installed. Most applications have a Windows installer that sets up shortcuts for the applications, but Cypress doesn't do this because it is launched from the command line.

There are also some issues with the notification's display that I suspect are related
- Windows displays `electron.app.Cypress` which is not our `appId` (it is `com.electron.cypress`)
- We have to specify an icon in order for the Cypress icon to appear on the notification

It's my understanding that if the app is configured correctly, Windows will show the app name as "Cypress", and will automatically show the shortcut icon on the notification without us having to specify it.

**Acceptance Criteria**:
- Cypress notifications display as from "Cypress"
- Cypress icon shows in notification without us specifying it in code
- Cypress appears in the Windows notification settings panel, allowing users to re-enable notifications after disabling them

Related reading:
- https://stackoverflow.com/questions/63933737/electron-app-not-showing-in-notification-settings
- https://github.com/electron/electron/issues/24330
- https://github.com/Automattic/simplenote-electron/pull/2483

**Comment by astone123** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/26786?planning-poker) with Zenhub @dkasper-was-taken @jordanpowell88 @lmiller1990 @marktnoonan @mike-plummer @warrensplayer

**Comment by lmiller1990** [comment]
This is a 3 - spend 2-3 days max, note what you learned - if we can't solve this, we will do the initial M1 without windows support and continue exploring in Q3.

**Comment by lmiller1990** [comment]
With our recent resource reallocation, I am de-prioritizing this. We will polish linux/macos for the M1. If we get time, we can do it, but we do not have time to do it in the June 6-20 sprint.
