### ISSUE TITLE
Browser isn't fired the load event after loading page

### ISSUE THREAD

**Issue by PavelRybalko** [cypress-io/cypress#26792]
### Current behavior
The page visually is loaded but the cypress is still waiting for the loading.
![image](https://github.com/cypress-io/cypress/assets/60709039/b72f47d3-019a-4d93-9848-4302b0fa1cc6)
![image](https://github.com/cypress-io/cypress/assets/60709039/c937cf72-0705-4551-ab53-9b495b79a3be)

### Desired behavior

Browser is fired the load event after loading page

### Test code to reproduce
```js
 it.only("can authenticate with Google UI", () => {
      Cypress.on(
        "uncaught:exception",
        (err) =>
          !err.message.includes("ResizeObserver loop") &&
          !err.message.includes("Error in protected function")
      );
      cy.visit("https://app.inkit.com/");
      cy.contains("Continue with Google").click();
      cy.origin("https://accounts.google.com", {}, () => {
        Cypress.on(
          "uncaught:exception",
          (err) =>
            !err.message.includes("ResizeObserver loop") &&
            !err.message.includes("Error in protected function")
        );

        cy.get("button:visible").eq(3).click();
        cy.get('input[type="email"]').type("test@gmail.com", {
          log: false,
        });
      });
    });
```
### Cypress Version

12.12.0

### Node version

v18.16.0

### Operating System

Windows 10 LTSC, 21H2, 19044.2364

**Comment by marktnoonan** [comment]
Hi @PavelRybalko, thank you for reporting this. The code provide does not allow us to reproduce the issue. Specifically, there is no initial `cy.visit()` so `cy.contains("Continue with Google").click();` will not work.

If possible please create a test using https://github.com/cypress-io/cypress-test-tiny that reaches this problematic state, then we can pull that down and debug.

I would be curious if, in the network tab, there is some resource that is not loading which prevents the browser `load` event from firing.

**Comment by PavelRybalko** [comment]
Hi @marktnoonan, thank you for you answering. I fixed the example code and added the initial cy.visit. I realized that this bug only appears in Chrome. Made a repository https://github.com/PavelRybalko/endless-google-loading/tree/master

**Comment by marktnoonan** [comment]
Thanks for the reproduction. I get a page load event but unfortunately I get it on a 403 error page, I'm not sure why.

<img width="1182" alt="Screenshot 2023-05-21 at 8 14 08 PM" src="https://github.com/cypress-io/cypress/assets/8340719/aa542776-b9bf-426a-94ab-6641853b6b97">

**Comment by PavelRybalko** [comment]
I got this error when "chromeWebSecurity" or "experimentalModifyObstructiveThirdPartyCode" option was false. The error disappeared when I ran the project without the "experimental ModifyObstructiveThirdPartyCode: true" option, and then with it.

**Comment by warrensplayer** [comment]
@PavelRybalko I can see the same thing you are seeing.  

Is this really what you want to test or do you just want to be able to authenticate with Google to get access to your app for testing?

Have you looked at our guide to authenticated with Google?  https://docs.cypress.io/guides/end-to-end-testing/google-authentication

If this test was part of your CI, then I believe Google would eventually block it by throwing up captchas, etc.

**Comment by PavelRybalko** [comment]
I need to test Google login via UI. I watched your guide to authenticated with Google, but I can't use it because in our application, authorization goes through firebase.

**Comment by warrensplayer** [comment]
Have you looked at this library: https://github.com/prescottprue/cypress-firebase

I don't think Google will let you drive your tests through the create account flow for very long with your tests before it starts to block it.

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
