### ISSUE TITLE
Upgrade Lerna to latest version

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#26798]
In order to take advantage of the most recent Nx features and to get the best support from the Nx team, Cypress should upgrade to use the latest version of Lerna (v6, or v7, whichever is latest when we work this ticket).

We've had issues upgrading past v5 before, see https://github.com/cypress-io/cypress/pull/26716. There are some issues with our existing dependencies that don't play well with the lock file changes that are made when we upgrade Lerna. We need to fix these problems, or just find a way to upgrade Lerna.

**Acceptance Criteria**:
Cypress is using the latest major version of Lerna

**Comment by bastiansmn** [comment]
Hello, currently trying to work on this to upgrade to Lerna v6.6.1 (https://yarnpkg.com/package/lerna)
