### ISSUE TITLE
"Expected to find the global Cypress in the parent window but it is missing" error thrown after upgrading Cypress from 10.6 to 12.12

### ISSUE THREAD

**Issue by ehyka** [cypress-io/cypress#26794]
### Current behavior

The case in hand can be described as follows:

I have a POST request that is made against a rest endpoint which uploads a file. That method is included in a Before Each hook. The response I see in the Cypress runner is this: 

```html
<head> <script type='text/javascript'> document.domain = '[ommited]'; !function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=0)}({"./injection/main.js":function(e,t,n){"use strict";n.r(t);const r=window.Cypress=parent.Cypress;if(!r)throw new Error("Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue.");const o=(()=>{let e,t,n,r;const o=()=>{e=!1,t=!1,n=[],r={}},i=(e,t=[])=>"function"==typeof e?e.apply(window,t):window.eval(e);return o(),{wrap:()=>{const o={setTimeout:window.setTimeout,setInterval:window.setInterval,requestAnimationFrame:window.requestAnimationFrame,clearTimeout:window.clearTimeout,clearInterval:window.clearInterval},a=(e,t)=>o[e].apply(window,t),s=e=>n=>(t&&(r[n]=!0),a(e,[n])),u=t=>(...r)=>{let o,[s,u,...l]=r;return o=a(t,[(...r)=>{if(!e)return i(s,r);n.push({timerId:o,fnOrCode:s,params:r,type:t})},u,...l]),o};window.setTimeout=u("setTimeout"),window.setInterval=u("setInterval"),window.requestAnimationFrame=u("requestAnimationFrame"),window.clearTimeout=s("clearTimeout"),window.clearInterval=s("clearInterval")},reset:o,pause:a=>{e=Boolean(a),e||(t=!0,n.forEach(e=>{const{timerId:t,type:n,fnOrCode:o,params:a}=e;"setInterval"===n&&r[t]||i(o,a)}),o())}}})();r.removeAllListeners("app:timers:reset"),r.removeAllListeners("app:timers:pause"),r.on("app:timers:reset",o.reset),r.on("app:timers:pause",o.pause),o.wrap(),r.action("app:window:before:load",window)},0:function(e,t,n){e.exports=n("./injection/main.js")}}); </script> </head>{"success":true,"message":"List Import started successfully."}`
```
What points to a Cypress bug is the error thrown `throw new Error("Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue.` 

Note that the request is actually executed correctly and the expected response is returned as a JSON at the very end.
This problem appeared only after upgrading Cypress from 10.6 to 12.12

### Desired behavior

The html code should not be returned as part of the response. That part is clearly added by Cypress and not by the web service.

### Test code to reproduce

Unfortunately I don't have a valid test code to repro this case, I hope I have given enough details. 

### Cypress Version

12.12.0

### Node version

16.13.0

### Operating System

macOS 13.3.1

**Comment by nagash77** [comment]
Hi @ehyka , unfortunately without a reproducible example it will be very difficult to diagnose the problem.  I have a couple questions that might be able to shed some light:

1.  Can you share the URL against which your tests are being run?
2.  When you say you don't have a valid test case to repo this issue does that mean this isnt happening every time?  Does it happen when you only run a specific test?
3. Does your website have framebusting measures?  Check out this guide on handling frame busting sites - https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection

**Comment by ehyka** [comment]
Hi @nagash77

1. The tests are being run against a private project that is not open source and therefore unaccessible to you. That is the reason I cannot provide a repro test case.
2. In our test code we have a bunch of tests that execute the same request and the response is always the same. The one I have added in the issue description. This happens every time these tests are run. Note that these tests have run without issues in Cypress version 10.6.0, this appeared after I attempted to update Cypress to 12.12.0. Worth mentioning that other tests that use other endpoints in their Before Each hooks are working properly.
3. No that is not the case.

**Comment by nagash77** [comment]
Hi @ehyka , Unfortunately without a reproducible example we will not be able to investigate this issue further.  I am going to close this issue at this point as we do not have a way forward without that.  If you can think of a way to replicate the behavior using [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) please comment back here linking to that example and we can reopen and investigate.

**Comment by ranamowbey** [comment]
Hello can you please let me know , if any workaround for this proble,m..

![image](https://github.com/cypress-io/cypress/assets/145969468/d0a7eaee-95fe-4bd6-a987-decfbb527ebc)
