### ISSUE TITLE
How to preserve access_token in cypress 12.12.0

### ISSUE THREAD

**Issue by rohitb2310** [cypress-io/cypress#26805]
### What would you like?

As we all know that we cannot open a new tab while performing tests using cypress, for that purpose I am preserving a access_token in before() function so that we can open that url in same tab.

In cypress 10.X we are suing following code and it is working fine.

``` js
before(function () {
  // cy.viewport(1024, 768)
  cy.Cookies.defaults({
    preserve :"access_token"
  })
})
```

but after update to cypress 12.0.3 code isn't migrated and it stop working for cy.cookies.defaults are deprecated.

### Why is this needed?

I have tried below code but it still doesn't working

```js
before(function () {
  cy.viewport(1024, 768)
  Cypress.Cookies.debug({
     preserve: "access_token"
  })
})
```

**Comment by nagash77** [comment]
Hi @rohitb2310 I have assigned this ticket out to an engineer to take a look at.  But in the mean time I would suggest you check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by chrisbreiding** [comment]
Asking in community chat is a great idea. I'd also recommend reading the [migration guide to v12](https://docs.cypress.io/guides/references/migration-guide#Command--Cypress-API-Changes) and its guidance on migrating from the removed `Cypress.Cookies.defaults()` method.

**Comment by hiepluong2205** [comment]
@rohitb2310 
This has been working for us. Hope it helps. 
```
const writeAccessTokenToFile = (operationName: string) => {
  aliasGql(operationName);
  cy.visit('/');
  waitGql(operationName).then((res: any) => {
    const bearerToken = res.request.headers.authorization;
    const accessToken = bearerToken.split(' ')[1];
    cy.writeFile('fixtures/gql/access-token.txt', accessToken);
  });
};
const readAccessTokenFromFile = () => cy.fixture('gql/access-token.txt');
```
