### ISSUE TITLE
Only the first index of destructed object is typed

### ISSUE THREAD

**Issue by mmonfared** [cypress-io/cypress#26803]
### Current behavior

Given there is a destructed object (e.g. arrays of string),
When we try to type them in an input with destruction 
Then only first index will type there

### Desired behavior

Given there is a destructed object (e.g. arrays of string),
When we try to type them in an input with destruction 
Then all the values should be typed

### Test code to reproduce

`/index.html` 
```html
<html>
    <head></head>
    <body>
        <div>
            <textarea id="note"></textarea>
        </div>
    </body>
</html>
```

`/cypress/e2e/spec.cy.js`

```js
it("test", () => {
    let myFriends = ['Jack', 'Frank']
    cy.visit('index.html')
    cy.log(...myFriends ) // "Jack Frank"
    cy.get("#note").type(...myFriends).should('have.value', "Jack Frank") // failed - Actual text is "Jack"
})
```

### Cypress Version

12.11.0

### Node version

16.14.2

### Operating System

Windows 11

**Comment by chrisbreiding** [comment]
[`cy.type()`](https://docs.cypress.io/api/commands/type) only accepts one string argument by design. It will ignore any subsequent arguments. The following will work instead:

```js
let myFriends = ['Jack', 'Frank']

cy.get("#note").type(myFriends.join(' ')).should('have.value', "Jack Frank")
```
