### ISSUE TITLE
Remove snap CI provider, add GoCD provider

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#2680]
Snap CI is no longer available: https://snap-ci.com/

They recommend looking at GoCD: https://www.gocd.org

Should be updated in our CI Provider file here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.coffee#L31

Standard GoCD environment variables listed here: https://docs.gocd.org/current/faq/environment_variables.html#standard-gocd-environment-variables

**Comment by sog01** [comment]
Sorry, this https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.coffee#L31 is not found

**Comment by jennifer-shehane** [comment]
Yes! We have been converting our coffeescript files to js 🙌
