### ISSUE TITLE
How to test salesforce lightning components using cypress?

### ISSUE THREAD

**Issue by tayyabaftk** [cypress-io/cypress#26804]
### Current behavior

When I try to test the salesforce lightning component. Cypress is not able to find the locators. The only component which is accessible is body component. I have tried to invoke show all elements but nothing work out.  can anyone please help me that how I can find/get  the lightning components locator

### Cypress Version

12

### Node version

v18.16.0

### Package Manager

npm

### Package Manager Version

not sure

### Operating system

Windows

### Operating System Version

10

**Comment by MikeMcC399** [comment]
@tayyabaftk 

For help using Cypress you can reach out to the community of experienced users on 
<a href="https://on.cypress.io/discord">
    <img src="https://img.shields.io/badge/chat-on%20Discord-brightgreen" alt="Discord chat"/>
</a>

Look for the Forum "i-need-help".

PS to find out the version of npm you are using type
`npm -v`
in a terminal window.

**Comment by nagash77** [comment]
@tayyabaftk please do follow @MikeMcC399 links and ask this question in Discord.  Github issues are reserved for reproducible bugs and feature requests.  All questions on how to use Cypress should be directed to chat.
