### ISSUE TITLE
Inability to Select Menu Item in Cypress Test due to POM Parameterisation Limitation

### ISSUE THREAD

**Issue by ecvanlare** [cypress-io/cypress#26823]
### Current behavior

When attempting to navigate to the Admin levels by selecting the 'Admin' menu item using the Cypress test, the following error occurs: "Timed out =retrying after 10000ms: Cannot read properties of undefined (reading 'toLowerCase')". This issue is believed to be caused by a limitation encountered when trying to parametrise the string value from the BDD step down to the page element in the Cypress test. 

### Desired behavior

The 'Clubs' menu item should be successfully selected without any errors.

### Test code to reproduce

Run the Cypress test with the following feature scenario:
vbnet

Feature: Admin Menu Navigation

   Scenario: Navigate Clubs Page
    And I select the 'Clubs' tab
Observe the Cypress Test Runner GUI.
Expected Result:
The 'Clubs' menu item should be successfully selected without any errors, allowing navigation to the Clubs Page.

Expected Behavior:
Upon selecting the "Clubs" tab, it should successfully navigate to the corresponding page without any errors.

Actual Behavior:
The "Clubs" tab selection fails, and the expected navigation does not occur. The test execution does not proceed as expected, leading to a test failure.

Additional Information:

This issue is believed to be a limitation experienced when trying to parametrise the string value from the BDD step down to the page element in the Cypress test.

The parameter value provided in the BDD step is not being passed correctly or is not matching the element on the page, resulting in the undefined property error.

The test code consists of the following files:

players_page.feature

```
javascript

import { When } from 'cypress-cucumber-preprocessor/steps';
import { playersPageDefinitions } from './playersPageDefinitions';

When('I select the {string} tab', (menuItem) => {
	PlayersPageDefinitions.selectMenu(menuItem)
})

```
playersPageDefinitions.js

```
javascript

import playersPage from './playersPage';

export const playersPageDefinitions = {
  selectMenu(sideMenu) {
    cy.get(navigationMenu.menuElements.menuBar(menuItem))
      .should('be.visible')
      .click();
  },
};
```
navigationMenu.js

```
javascript

const navigationMenu = {
	get pageElements() {
		return {
			menuBar(menu) {
				return cy.xpath(`//a[@role='menuitem'][.='${menu}']`)
			},
		}



export default adminPage;
```
The error occurs at the line cy.get(navigationMenu.menuElements.menuBar(menuItem)).should('be.visible').click(); in the playersPageDefinitions.js file.

Manually inspecting the page confirms that the menu item with the label "Clubs" exists and is visible.

Code Snippets:
Step 14: And I select the 'Clubs' tab
15: xpath//a[@role='menuitem'][.='Clubs']
16: get{specwindow: <window>, chainerid: ch-[https://www.premierleague.com-167}](https://www.premierleague.com-167%7D/)
17: assertexpected { Object (0, length) } to be visible
18: get.fantasySignInLabel
19: assertexpected <span.fantasySignInLabel> to be visible

### Cypress Version

12.12.0

### Node version

19.2

### Operating System

mac OS Ventura 13.3.1

### Other

Additional Information:

This issue may be related to a limitation in parameterising the string value from the BDD step down to the page element in Cypress tests.
The relevant code consists of the following files:

players_page.feature with the step definition for selecting the menu.
playersPageDefinitions.js with the method for selecting the menu item using the page object.
playersPage.js defining the page object with the menu item selector.
Manually inspecting the page confirms the existence and visibility of the 'Clubs' menu item.
In the third testcase i've shown the workaround in the step 'And I navigate to the 'Clubs' page'

**Comment by chrisbreiding** [comment]
> This issue is believed to be caused by a limitation encountered when trying to parametrize the string value from the BDD step down to the page element in the Cypress test

This seems like it might be an issue with [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) rather than Cypress itself. I would recommend creating an issue in that repo.

In any case, it would be helpful to have a minimal reproduction of the issue contained within its own repo, since there are dependencies and setup involved in reproducing this that are not present in the given code. I recommend using [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) as a starting point to create a reproduction.

**Comment by ecvanlare** [comment]
as requested reproducible example 
[CypressPrem-Tiny.zip](https://github.com/cypress-io/cypress/files/11612151/CypressPrem-Tiny.zip)

**Comment by AtofStryker** [comment]
@ecvanlare I wasn't able to run into the `Timed out =retrying after 10000ms: Cannot read properties of undefined (reading 'toLowerCase')` issue when running the reproduction. Some of the tests did fail but the failures looked unrelated. Is this expected?

https://github.com/cypress-io/cypress/assets/3980464/3bee3a66-5a52-479f-aba2-9030b85a6419

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
