### ISSUE TITLE
Input value truncated

### ISSUE THREAD

**Issue by stefanoeduardo** [cypress-io/cypress#2682]
### Current behavior:
When my test attempts to input a value of '000f72e' into an entry field it *usually* (say 90% of the time) truncates the value to '00f72e'. Occasionally, the correct value is input and once or twice I have seen the first 2 characters removed.

This screenshot shows what's happening:
![000f72e_truncated](https://user-images.githubusercontent.com/43175463/47783297-3a215d80-dcfa-11e8-8cf7-5da767ff03a6.png)

As you can see, I've introduced a delay for the type command and tried different values, but with no discernible difference.

This screenshot shows the html for the input field:
![html](https://user-images.githubusercontent.com/43175463/47785146-b7030600-dcff-11e8-8394-fa6e5395f2df.png)

I've also seen this happening with a string without leading zeroes ('7e60b0fbf2391a489dafdea4a8bc204b' in this case being truncated to 'b0fbf2391a489dafdea4a8bc204b'):
![md5sum_truncated](https://user-images.githubusercontent.com/43175463/47785905-05190900-dd02-11e8-9fec-d739102eb602.png)
...and here's the html for the input field:
![html2](https://user-images.githubusercontent.com/43175463/47786019-53c6a300-dd02-11e8-9458-19c0f5e6d402.png)

### Desired behavior:
I'd like the value I selected to be consistently input without truncation.

### Steps to reproduce:
Execute the statement:
cy.get('#q185').type('000f72e')
or:
cy.get('#q58').type('7e60b0fbf2391a489dafdea4a8bc204b')

My code actually gets the values to input from a config file - in JSON format. Here's the relevant snippets...

    "qandas": [
      {
        "questionId": "q185",
        "answerType": "textInput",
        "answer": "000f72e"
      },

and

    "qandas": [
      {
        "questionId": "q58",
        "answerType": "textInput",
        "answer": "7e60b0fbf2391a489dafdea4a8bc204b"
      }
    ]

### Versions
I have the following versions installed:
Chrome Version 70.0.3538.77, running on LinuxMint 19 (64-bit)
Cypress version 3.1.0
node.js version 10.10.0
npm version 6.4.1

**Comment by Bkucera** [comment]
@stefanoeduardo sorry, I can't reproduce this on a vanilla text input. Are you using a library like React or Angular? It would be best if you'd provide a minimal reproducible repo or webpage for us. Thanks

**Comment by stefanoeduardo** [comment]
I think this is down to me not having verified that the relevant page element was loaded before attempting to input. I've tightened up on that and it all seems fine now so I'll close this issue. Sorry!
