### ISSUE TITLE
Mocha hooks doesn't work on root level (when added to index.js file)

### ISSUE THREAD

**Issue by kapalkat** [cypress-io/cypress#2683]
### Current behavior:
When I try to add `before` hook to `index.js` file according to your recipe:

> Hooks you add to the root will always run on all suites!
// cypress/support/index.js

> beforeEach(function () {
>     // now this runs prior to every test
>     // across all files no matter what
>     console.log('before every test in every file')
> })

I got the following: "Can't start server" error.

> Can't start server
> The plugins file is missing or invalid.
> 
> Your pluginsFile is set to '/Users/kapalkat/projects/westshore/westshore-tms-frontend/cypress/plugins/index.js', but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.
> 
> Please fix this, or set 'pluginsFile' to 'false' if a plugins file is not necessary for your project.
> 
> The following error was thrown:
> 
> ReferenceError: before is not defined
> at Object. (/Users/kapalkat/projects/westshore/westshore-tms-frontend/cypress/plugins/index.js:19:1)
> at Object. (/Users/kapalkat/projects/westshore/westshore-tms-frontend/cypress/plugins/index.js:23:3)
> at Module._compile (module.js:569:30)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:503:32)
> at tryModuleLoad (module.js:466:12)
> at Function.Module._load (module.js:458:3)
> at Module.require (module.js:513:17)
> at require (internal/module.js:11:18)
> at module.exports (/Users/kapalkat/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:107:15)
> at Object. (/Users/kapalkat/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js:14:25)
> at Object. (/Users/kapalkat/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js:16:3)
> at Module._compile (module.js:569:30)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:503:32)
> at tryModuleLoad (module.js:466:12)

### Desired behavior:
The root hook should work

### Steps to reproduce:
Add `before` or `beforeEach` hook to `index.js` file

### Versions

Cypress: 3.1.0
OS: MaxOS
Browser: Chrome

**Comment by chrisbreiding** [comment]
From what I can tell from that error, it looks like you're trying to define a `before` hook in `cypress/plugins/index.js`, when you want to put it in `cypress/support/index.js`.

**Comment by kapalkat** [comment]
You are right. Haven't noticed that! Thanks for your help; it's working fine when the hook is in proper file.
