### ISSUE TITLE
Tests passing in local env but failing at git env

### ISSUE THREAD

**Issue by hadarpinto** [cypress-io/cypress#26831]
### Current behavior

hey everyone, 
I'm having trouble with cypress testing in git env.
In local env all tests are passing successfully:
![image](https://github.com/cypress-io/cypress/assets/42929491/83fab5ea-4e0b-48f9-996f-c25e74b462b4)

the same test are running with a git action, yet they are failing due to element-covering.
![image](https://github.com/cypress-io/cypress/assets/42929491/6d21adab-1854-4a15-8e65-63dd633a0783)

### Desired behavior

i've tried this soluiton: https://github.com/cypress-io/cypress/issues/17159
I have tried to run test in git env with headed mode as well and nothing seems to getting me closer to the answer.
I do not wish to use the {force: true} suggestion.
appreciate all help i can get.

### Test code to reproduce

![image](https://github.com/cypress-io/cypress/assets/42929491/9f94047b-fafa-4e5c-997c-ded5487b011f)

### Cypress Version

12.8.1

### Node version

v12.22.7

### Operating System

mac

**Comment by MikeMcC399** [comment]
@hadarpinto 

Can you explain why you do not want to use [Force click](https://docs.cypress.io/api/commands/hover#Force-click)?

When you write "git env" are you referring to GitHub Actions perhaps?

By the way, your version of Node.js (`v12.22.7`) is no longer supported. See https://github.com/nodejs/Release and https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs. You may want to update your system.

**Comment by hadarpinto** [comment]
@MikeMcC399 
some of the checks in the test are on disabled elements, it might be breakable for me
when i wrote git env , i do refer to gitHub actions
about the node version, i'll upgrade and will update if there was any difference 

yet, i still try to found out why is behavior different between the two environments

**Comment by AtofStryker** [comment]
@hadarpinto did you have any luck upgrading the node version?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
