### ISSUE TITLE
Single Quotes missing from error message.

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#2684]
### Current behavior:
This error message does not display the single quotes that should be surrounding ":nth-child(2) > a". The single quotes are present in the code.
![image](https://user-images.githubusercontent.com/5534029/47806691-b757cd00-dd10-11e8-8459-2964bdc6fec0.png)

### Desired behavior:
This error message (and any like it) correctly display the code as it is written in the file.  In this case, it should include single quotes at the beginning and end.

### Steps to reproduce:
Make a call like "cy.click(':nth-child(2) > a')"
This error message does not display the single quotes that should be surrounding ":nth-child(2) > a". 

### Versions
Cypress 3.1.0
Chrome
Windows 10

**Comment by jennifer-shehane** [comment]
Somewhat related: https://github.com/cypress-io/cypress/issues/1360

**Comment by jennifer-shehane** [comment]
This was released in [3.1.5](https://on.cypress.io/changelog#3-1-5)
