### ISSUE TITLE
Typescript tests are not visible in the Cypress UI (v12.13.0)

### ISSUE THREAD

**Issue by balaji2711** [cypress-io/cypress#26855]
### Current behavior

The installed version of Cypress is v12.13.0.

I have included my TypeScript tests within the e2e directory, along with the tsconfig file. However, when I launch the Cypress UI, the newly added tests are not visible.

PFA for the screen-shots

![image](https://github.com/cypress-io/cypress/assets/15344129/6658761d-a98c-4cb9-b1ac-bddbad935875)

Project Structure:

![image](https://github.com/cypress-io/cypress/assets/15344129/c752a6af-a05a-4e2f-b2ec-2da22e09fa6f)

### Desired behavior

I should be able to run my tests without any issue

### Test code to reproduce

**Tests.ts:**

describe("Google Tests",()=> {
    it("enter some value", () => {
        cy.visit("https://www.google.com")
        cy.get("#search").type("Apple")
    })
})

**tsconfig.json:**

{
    "compilerOptions": {
      "target": "es5",
      "lib": ["es5", "dom"],
      "types": ["cypress", "node"]
    },
    "include": ["**/*.ts"]
  }

### Cypress Version

12.13.0

### Node version

v20.1.0

### Operating System

Windows 10 Enterprise

**Comment by MikeMcC399** [comment]
@balaji2711 

Check your configuration. Cypress may be looking for `tests.cy.ts` not `tests.ts`

![image](https://github.com/cypress-io/cypress/assets/66998419/24384ddb-1b64-4eff-8ea8-4642ee131f0c)

**Comment by MikeMcC399** [comment]
This is the default value according to the documentation [Configuration > e2e](https://docs.cypress.io/guides/references/configuration#e2e).

**Comment by balaji2711** [comment]
@MikeMcC399, Thanks Mike, I have just updated the configuration and it works fine now.

**Comment by warrensplayer** [comment]
Thanks @MikeMcC399!
