### ISSUE TITLE
Token set inside the localStorage is getting cleared during the cypress run

### ISSUE THREAD

**Issue by kiran4coachhub** [cypress-io/cypress#26856]
### Current behavior

The token set in the localStorage of the browser by the Application is getting cleared or set to null during the run of test case. 

### Desired behavior

The token should not be removed during any run as the application takes care of the token. 

### Test code to reproduce

cy.get('[data-testid=timezone-select-container] > .MuiFormControl-root > .MuiInputBase-root input').type('berlin');
    cy.get('li.MuiAutocomplete-option').click();
    cy.wait(10000);
cy.get('.MuiButton-label').should('not.be.disabled');
    cy.get('.MuiButton-label').click(); // continue button

https://github.com/cypress-io/cypress/assets/108738432/2ba6eaa5-9d8d-488d-a2c3-d825201406af

### Cypress Version

12.13.0

### Node version

v18.3.0

### Operating System

macOS 13.3.1(a)

**Comment by AtofStryker** [comment]
Hi @kiran4coachhub . Thank you for opening an issue. Would you be able to create a reproduction repository that we can use to reproduce the issue? Do the results change if `testIsolation` is disabled?

**Comment by kiran4coachhub** [comment]
It was an issue from the automation script, closing this.
