### ISSUE TITLE
Cypress config error after CT migration to Yarn Plug'n'Play

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#26865]
### Current behavior

If a working Cypress Component Testing environment is converted to use [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp), Cypress fails to start and reports "Your config file is invalid". In this case neither CT nor E2E testing can be carried out.

The exact error depends on which framework was configured.

The previous working environment could be `npm`, Yarn Classic (version 1) or Yarn Modern (version 3 or 4) configured with `nodeLinker: node-modules`. Each of these environments works with CT.

Environment | Error
--- | ---
Angular 17 |  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" 
React | Error: require() of ES Module cypress.config.js from Cypress\Cache\13.6.4\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js not supported.
Svelte | as for React
Vue | as for React

### Desired behavior

Cypress component testing should be compatible with [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp).

If a project is correctly configured, then the command `yarn cypress run --component` should execute without errors.

### Test code to reproduce

From clone of https://github.com/MikeMcC399/component-testing-quickstart-apps (fork of https://github.com/cypress-io/component-testing-quickstart-apps)

```bash
git clone --branch yarn-berry-pnp https://github.com/MikeMcC399/component-testing-quickstart-apps
npm install yarn@latest -g
cd component-testing-quickstart-apps/react/my-awesome-app
yarn set version stable
yarn add cypress -D -E
yarn cypress run --component
```

alternatively 
```bash
yarn cypress open --component
```

### Cypress Version

First reported on Cypress `12.13.0`
Continues to be reproducible on Cypress `13.13.0`

### Yarn version

~~4.0.2~~ 4.3.1

### Node version

`18.18.2` / `20.11.1`

### Operating System

Ubuntu `22.04.3` (also on Windows 11)

### Debug Logs

[debug.log](https://github.com/cypress-io/cypress/files/11575273/debug.log)

Regular log on https://github.com/MikeMcC399/component-testing-quickstart-apps/actions/runs/5903678483.

### Other

Branch `yarn-berry-node` in https://github.com/MikeMcC399/component-testing-quickstart-apps demonstrates Yarn Modern (~~3.5.1~~ 4.0.2) with `nodeLinker: node-modules` configured in `.yarnrc.yml` successfully running Component Testing.

The other examples in the repository are also set up for testing:

```bash
cd angular/my-awesome-app
yarn install
yarn cypress run --component
```

```bash
cd svelte/my-awesome-app
yarn install
yarn cypress run --component
```

```bash
cd vue/my-awesome-app
yarn install
yarn cypress run --component
```

to access and test them.

**Comment by mike-plummer** [comment]
Thanks @MikeMcC399! This will likely be related to work needed to resolve #26859.

I will forward this ticket to the appropriate team. They will evaluate the priority of this ticket and consider their capacity to pick it up. Please note that this does not guarantee that this issue will be resolved. The ticket will indicate any status changes. Thanks!

**Comment by MikeMcC399** [comment]
https://github.com/MikeMcC399/component-testing-quickstart-apps/actions/runs/5903678483 shows failure logs on GitHub

**Comment by MikeMcC399** [comment]
@mike-plummer 

This is assigned to you, however there hasn't been any movement on it. Is Yarn Plug'n'Play going to get any attention?

**Comment by waldemarennsaed** [comment]
Is this issue still to be worked on? I still face issues using Yarn 4, PnP and Cypress 13.13.2 .

**Comment by jennifer-shehane** [comment]
Not currently

**Comment by MikeMcC399** [comment]
- Moved to consolidated request #30011 for better transparency
