### ISSUE TITLE
Cypress Grep: The env variable should not be case sensitive

### ISSUE THREAD

**Issue by josefsmrz** [cypress-io/cypress#26880]
### What would you like?

As per the below documentation the env variables will be given in "upper snake case" while the same in the env field in config will be in camel case

https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_

The plugin works if the env is exported like following:

export CYPRESS_grepTags="@smoke"

but does not work if it is in upper snake case:

export CYPRESS_GREP_TAGS="@smoke"

### Other

This is a migrated issue from https://github.com/cypress-io/cypress-grep/issues/141

**Comment by nagash77** [comment]
Hi @josefsmrz , Cypress no longer is actively fixing issues with cypress grep.  I would suggest you check out https://github.com/bahmutov/cy-grep as a replacement.
