### ISSUE TITLE
browser detection fails for Chrome variants

### ISSUE THREAD

**Issue by orangecms** [cypress-io/cypress#269]
When running tests through the CLI, an Xvfb instance is spawned with child processes of the Cypress desktop app, but nothing really happens.
When I directly open the desktop app and I open a project, I get the message

```
 Can't Launch Any Browsers
We couldn't find any Chrome browsers to launch. To fix, please download Chrome.
```

I have Chromium and Chrome Developer Edition installed on Arch Linux. I found out that having `google-chrome` in `$PATH` fixes the issue. It would be easier to have an env var or a config parameter to set which binary to use.

**Comment by brian-mann** [comment]
Yup this is a known issue. Also opened here: https://github.com/cypress-io/cypress-core-launcher/issues/1

**Comment by brian-mann** [comment]
At the moment just symlink to the named binaries we expect to find.

https://github.com/cypress-io/cypress-core-launcher/blob/master/lib/detect.coffee

**Comment by orangecms** [comment]
Ah, sorry, I hadn't seen the cypress-core-launcher repo. I'm happy though to be able to actually use Cypress now and toy with it.
I'm not sure whether to close this issue or keep it open for reference in case others don't find the other repo. Feel free to do so if you want, it would be fine by me @brian-mann

Thanks! :)

**Comment by brian-mann** [comment]
It's okay - we are actually in the process of consolidating into a single repo partly due to this issue.

We'll keep it open until its fixed.
