### ISSUE TITLE
Vue Router Access via mountedComponent.$route broken in Cypres 12.12 and 12.13

### ISSUE THREAD

**Issue by ppuetsch** [cypress-io/cypress#26902]
### Current behavior

We have a setup equal to https://docs.cypress.io/guides/component-testing/vue/examples#Vue-Router. 
Until Cypress 12.11 we could do the following:
```
    cy.mount(myComponent, {}).then((mounted) => {
      cy.wrap(mounted.component).its("$route.path").should("eq", "/someUrl");
    });
```
However, in Cypress 12.12 and 12.13, mounted.component.$route is undefined.

### Desired behavior

`mounted.component.$route` should contain the `$route` object of vue 

### Test code to reproduce

```
    cy.mount(myComponent, {}}).then((mounted) => {
      cy.wrap(mounted.component).its("$route.path").should("eq", "/someUrl");
    });
```

### Cypress Version

12.13

### Node version

18.16.0

### Operating System

Windows 10 22H2 OS build 19045.2965 Experience Windows Feature Experience Pack 1000.19041.1000.0

**Comment by mike-plummer** [comment]
@ppuetsch I'm not able to reproduce your issue on Cypress 12.12 through 12.14; it appears that `mounted.component.$route` is defined in my spec in all of those versions. Is it possible you lost the customizations to your `support/component.js` file from the [`vue-router` example](https://docs.cypress.io/guides/component-testing/vue/examples#Vue-3) during your upgrade? Can you provide a reproduction case for me to look at?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
