### ISSUE TITLE
cy.session allows me to keep cache across specs and avoid logging in again using Electron, but not using Chrome

### ISSUE THREAD

**Issue by asier-perez** [cypress-io/cypress#26903]
### Current behavior

I have several specs and want to run them with `npx cypress run --browser chrome`. Also, I want the first test to perform the login, and then keep the session in order to avoid logging in again on next specs. To achieve this, I am using `cy.session()` with the `cacheAcrossSpecs: true` option.

Currently, when I run the tests using `npx cypress open`, the first spec creates the session, and the following ones restore it and execute as desired, without logging in again. This correct behavior occurs regardless of the browser.

However, when I use `npx cypress run`, the behavior is inconsistent. With Electron, it works as desired, but with Chrome (`npx cypress run --browser chrome`), this happens:

1. The first spec creates the session correctly and it is executed as normal
2. The second spec restores the session correctly
3. The `cy.visit()` just after restoring the session takes me to the login screen, instead of the main screen that should appear once logged in
4. Tests fail because they are not logged in

This behavior, as said, does not happen with Electron, but only with other browsers. I am using Electron v106 and Chrome v113, but I have tried it also with previous Chrome versions such as v106. In case of Firefox and Chrome Dev, it happens the same as with Chrome.

### Desired behavior

I want to run all tests with `npx cypress run --browser chrome` keeping the session between specs to avoid logging in each time a spec starts. The desired behavior only occurs with Electron or with `npx cypress open`.

### Test code to reproduce

This is the function I am using to log in, which is executed during beforeEach hooks.
```js
cy.logInSession = () => {
   cy.session('username', () => {
      cy.visit(Cypress.env('baseUrl'))
      cy.get('user-textField').type(Cypress.env('username'))
      cy.get('password-textField').type(Cypress.env('password'))
      cy.get('login-button').click()
   }, {
      cacheAcrossSpecs: true
   })
   cy.visit(Cypress.env('baseUrl'))
   cy.contains('[data-cy=profile]', Cypress.env('username')).should('be.visible')
 }
```

### Cypress Version

12.7.0

### Node version

16.17.1

### Operating System

Ubuntu 20.04.5 LTS

**Comment by AtofStryker** [comment]
Hi @asier-perez. Thank you for opening an issue. Would you be able to create a reproduction repository that we can run on our end to reproduce and verify the issue?

**Comment by asier-perez** [comment]
Hi @AtofStryker, thank you for the response. I cannot share the repository I am using currently, and I am not sure if I will be able to reproduce the error on a new one, but I will try to do it.

**Comment by mschile** [comment]
Hi @asier-perez, right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by asier-perez** [comment]
Hi @mschile, I cannot reproduce the error on a new example-app repository, so it seems that the bug is caused by the application I was using. It is not a real issue of Cypress.
