### ISSUE TITLE
Stubbing window.open not working in cypress

### ISSUE THREAD

**Issue by mohd-faisel** [cypress-io/cypress#26904]
**Current Behaviour ;**
When i click a edit button in our application, it opens a edit page in new tab, developers using window.open method to open the new tab. I tried using stubbing window.open. This solution doesn't work because the properties that open new tab is contained in a javascript function, and they are passing some properties in their window.open function. Cypress is opening url in same tab but its blank, it is not showing body in UI
Note - there is no target attribute in this and they denied to put target attribute.
Is there an alternative workaround to fix this behavior and how can i pass those same properties in our stub method so that page opens correclty

**My cypress script**
![image](https://github.com/cypress-io/cypress-test-tiny/assets/94177317/5abc6a9c-a6d8-4666-9c21-6ba984b5ca12)

**Development side window.open method below**
![image](https://github.com/cypress-io/cypress-test-tiny/assets/94177317/9591ed54-1d89-43dd-84d6-1d89c7be49d0)

@chrisbreiding @bahmutov @nagash77 can you please provide solution to this as I am stuck since 3 days. Thanks

**Comment by bahmutov** [comment]
You can find my solutions to stubbing `window.open` by searching https://cypress.tips/search

**Comment by mohd-faisel** [comment]
Thanks for reply @bahmutov , but I have already tried your methods, now it is opening in same tab but data is missing. There is nothing in the UI. I shared the development code above, i think they are passing some values in window.open. How can I pass those values inside our stub method?

**Comment by bahmutov** [comment]
You mean attaching the properties to the returned window object?Sent from my iPhoneOn Jun 1, 2023, at 07:12, mohd-faisel ***@***.***> wrote:﻿
Thanks for reply @bahmutov , but I have already tried your methods, now it is opening in same tab but data is missing. There is nothing in the UI. I shared the development code above, i think they are passing some values in window.open. How can I pass those values inside our stub method?

**Comment by mohd-faisel** [comment]
Yes attaching the properties.

I guess they are sending some properties in their window.open code, which
helps to load the new page. As I am not passing those properties that's why
my page is not loading and its blank.

**Comment by bahmutov** [comment]
If you can provide an actual runnable example that shows the problem, then it would be possible to show the solution. As of now, I cannot help, I am sorry.

One more example: https://glebbahmutov.com/cypress-examples/recipes/window-open.html#return-a-popup-object

**Comment by nagash77** [comment]
@mohd-faisel , can you please replicate the problem using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny)?  This will be needed in order for our developers to properly replicate the issue and investigate.

**Comment by mohd-faisel** [comment]
@nagash77 @bahmutov Hey there, my issue was resolved last week. I found a way to pass the properties to window object, it helped my page to load and now it is working fine,
I used below code :- 
`Cypress.on("window:before:load", (win) => {
    win.foo.any = true;   // your custom properties here
  });`
and then stub window.open
`cy.window().then((win) => {
    cy.stub(win, "open").callsFake((url) => {
        return win.open.wrappedMethod.call(win, url, "_self");
      }).as("open");
  });`

Thanks @bahmutov, your stub code was really useful. Thanks for help @nagash77 and @bahmutov
