### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by Timbo1979** [cypress-io/cypress#26907]
### Current behavior

Currently getting this when trying to use Angular 16. Looks like Angular 15 is supported.

![image](https://github.com/cypress-io/cypress/assets/16131014/3c18c7a1-cbae-4fa4-b8bd-7dfb5be4ee54)

### Desired behavior

I would like Angular 16 to be supported.

### Test code to reproduce

Install latest version of Angular using CLI and install latest version of Cypress.

### Cypress Version

12.13.0

### Node version

18.16.0

### Operating System

MacOS (13.4) / Windows 10

**Comment by MikeMcC399** [comment]
@Timbo1979 

- I already reported this issue in https://github.com/cypress-io/cypress/issues/26852

**Comment by Timbo1979** [comment]
> @Timbo1979
> 
> * I already reported this issue in [Angular 16 not detected by CT #26852](https://github.com/cypress-io/cypress/issues/26852)

Okay thanks. I did look for a bug for this… obviously not very well.

**Comment by MikeMcC399** [comment]
@Timbo1979 

> I did look for a bug for this… obviously not very well.

Don't worry about that!

`is:issue is:open angular 16 in:title`

is a good search string for this set of issues.

**Comment by MikeMcC399** [comment]
@Timbo1979 

[Cypress 12.14.0](https://docs.cypress.io/guides/references/changelog#12-14-0) has been released, so you should be good to go! The detection for Angular 16 in Component Testing has been fixed.

- See PR https://github.com/cypress-io/cypress/pull/26908

**Comment by Timbo1979** [comment]
@MikeMcC399 thanks for letting me know! It will be great to have Angular 16 and Cypress playing nicely together again.
