### ISSUE TITLE
Retry if assertion fail and issue with .each

### ISSUE THREAD

**Issue by kamiloski88** [cypress-io/cypress#26916]
### Current behavior

Case:
We have table which is filtered by 'market name'. If filter is not applied, then different markets are displayed in table, after filtering by market name, table is feeded with only markets name that was filtered.
I want to check that after filtering by market name, all rows from column 'Market Name' contains filtered market name, but between apply filter and load markets in table cypress catch and perform assertion on names which were displayed before applying filters. 

So I decided to use assertion with 'retry' and here are 2 issues.

1. if I use .each then assertion is not retrying. It's run only once, and what is more if this assertion FAIL, then the test is marked as PASSED.
2. If i use each inside should like in example code (.each) takes parameters in a different order 
```js
JQuery<HTMLElement>.each(     funсtion: (this:HTMLElement, index: number, element: HTMLElement) => (false | void)):    JQuery<HTMLElement>
```

- first is index, 2nd element,

### Desired behavior

assertion in .each loop ` expect(marketName).to.contain.text(market.Name);` should be retried till will pass or timeout

### Test code to reproduce
```js
cy.get('td[hubsharedtableelement="marketName"]').should(( $marketNameColumnValues) => {
      $marketNameColumnValues.each((_, marketName) => {
        expect(marketName).to.contain.text(market.Name);
      });
    });
```
### Cypress Version

12.9.0

### Node version

18.14.0

### Operating System

Windows 11

**Comment by AtofStryker** [comment]
Hi @kamiloski88. Thank you for opening an issue. Would you be able to create a reproduction repository that we can run on our end to observe the behavior?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
