### ISSUE TITLE
The Cypress App could not be unzipped at Jenkins

### ISSUE THREAD

**Issue by vasiabraun** [cypress-io/cypress#2691]
Hello, trying to run Cypress through Jenkins throws me an error:
Installing Cypress (version: 3.1.0)
[?25l[17:45:21]  Downloading Cypress     [started]
[17:45:23]  Downloading Cypress     [completed]
[17:45:23]  Unzipping Cypress       [started]
[17:45:23]  Unzipping Cypress       [failed]
[?25hThe Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at

https://github.com/cypress-io/cypress/issues
----------

Error: Target directory is expected to be absolute
----------

Platform: linux (Debian - 8.11)
Cypress Version: 3.1.0
[?25hnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.1.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@3.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>

**Comment by vasiabraun** [comment]
Resolved this one myself, you have to specify absolute path to directory on workspace where cypress is unzipped - HOME="${env.WORKSPACE}"

**Comment by jsonhp** [comment]
Hi, please, can you help me?; how can i specific the absolute path?. Thanks

**Comment by itamarsky** [comment]
@jsonhp 

pipeline {
. . .
 stages {
    stage('build and test') {
      environment {
        CYPRESS_RECORD_KEY = credentials('cypress-example-kitchensink-record-key')
        **HOME="${env.WORKSPACE}"**
      }
. . .
