### ISSUE TITLE
Pull request status checks are not set if using custom COMMIT_INFO_MESSAGE env variable

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#26917]
### Current behavior

If I use Cypress cloud with pull request status checks, all is working. BUT I have the default `Merge SHA into SHA` dashboard run title. Thus I set `COMMIT_INFO_MESSAGE` environment variable.

But then the pull request status checks do not work (they don't appear at all), and the pull request comment is not created/updated.

The full situation is described in the blog post https://glebbahmutov.com/blog/pull-request-title/

### Desired behavior

status checks and pull request comment should be posted when using `COMMIT_INFO_MESSAGE` environment variable

### Test code to reproduce

See repo https://github.com/bahmutov/cypress-pull-request-title/pull/2 and its different commit status checks. Read https://glebbahmutov.com/blog/pull-request-title/

### Cypress Version

12.13.0

### Node version

18

### Operating System

linux

**Comment by conversayShawn** [comment]
It's possible there is a workaround [here](https://github.com/cypress-io/github-action/issues/124#issuecomment-1076826988), but we need to verify if the issues are the same.

@bahmutov Can you try adding `COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}` as an env var

**Comment by bahmutov** [comment]
It worked. Setting to HEAD SHA did the trick
```yml
COMMIT_INFO_MESSAGE: My pull request ${{ github.event.number }}
COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
```
<img width="974" alt="Screenshot 2023-06-02 at 15 08 19" src="https://github.com/cypress-io/cypress/assets/2212006/0c78b0aa-e45b-4f26-b5ce-bb9584c7f51e">

I would suggest grabbing these SHA commits or documenting them
