### ISSUE TITLE
Salesforce applauncher detection 

### ISSUE THREAD

**Issue by CYPRESSSA** [cypress-io/cypress#26937]
### Current behavior

while runing my test on salesforce environement , after connecting to my salesforce page i try to select applauncher but my test stop showing the right hand console and i even can t pursue the code error to understund what s the problem source and it couldn t select app launcher element 
<img width="926" alt="eerr" src="https://github.com/cypress-io/cypress/assets/135593723/a2fddea2-934d-4ceb-8f9e-e53b34b8f67a">

```
describe("My First Test", () => {
  it("Login salesforce!", () => {
    cy.visit("https://login.salesforce.com/");

    // Get an input, type into it
    //cy.get('.action-email').type('safae.aarab2@usmba.ac.ma')

    //  Verify that the value has been updated

    cy.get("#username").type("xxxxxxxxx");
    cy.get("#password").type("xxxxxx");
    cy.get("#Login").click();

    cy.get("body").click().type("sales").click;
  });
});
```

### Desired behavior

pouvoir selectionner le app launcher sur la pages salesforce afin de pouvoir taper salesforces , et toujours avoir sur la console test runner les commandes et leurs descriptions au fur et à mesure 

### Test code to reproduce
```
describe("My First Test", () => {
  it("Login salesforce!", () => {
    cy.visit("https://login.salesforce.com/");

    // Get an input, type into it
    //cy.get('.action-email').type('safae.aarab2@usmba.ac.ma')

    //  Verify that the value has been updated
    cy.get("#username").type("xxxxxxxxxxxx");
    cy.get("#password").type("xxxxx");
    cy.get("#Login").click();

    cy
      .xpath(
        "/html/body/div[4]/div[1]/section/div[1]/div/div[1]/div[1]/div/div/div[1]/button"
      )
      .click()
      .type("sales").click;
  });
});
```    
    
### Cypress Version

v12.13.0

### Node version

v18.16.0

### Operating System

Windows 10

### Debug Logs

```shell
i dont have the debug log ,it stop showing the details as the picture on the description .
```

**Comment by AtofStryker** [comment]
Hi @CYPRESSSA. Thank you for opening an issue. Have you tried setting the following true in your `e2e` config inside `cypress.config.js`?
```
experimentalModifyObstructiveThirdPartyCode: true,
experimentalSkipDomainInjection: ['*.salesforce.com', '*.force.com']
```

This should resolve your issue. Can you let us know if it works/ does not work? 

Here is some more info on [experimentalSkipDomainInjection](https://docs.cypress.io/guides/references/experiments#Experimental-Skip-Domain-Injection) and [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/guides/web-security#Modifying-Obstructive-Third-Party-Code).

**Comment by CYPRESSSA** [comment]
YEAH THANK U  i modified the true configuration and now it show the right hand console but my script give me the error i didnt really understund it?
<img width="941" alt="BUG1" src="https://github.com/cypress-io/cypress/assets/135593723/fff88edb-eaf1-4ae9-9725-4d2a774a3b19">

**Comment by AtofStryker** [comment]
@CYPRESSSA great to hear! From what I can see from the screenshot, the error looks related to a bad xpath selector. I would recommend using something less brittle to select an element rather than direct xpath. Using an [ID or selecting on text](https://docs.cypress.io/guides/references/best-practices) would likely work much better, and if you need to use xpath there are some [tricks](https://devhints.io/xpath) you can use to help make that xpath less brittle and prone to breakages. 

I am going to close this issue since it looks resolved, but please let us know if you run into any other issues!
