### ISSUE TITLE
Cypress 12.13.0 with Typescript 5.1 fails to compile

### ISSUE THREAD

**Issue by holgergp** [cypress-io/cypress#26930]
### Current behavior

When I use Cypress in version 12.13.0 with TypeScript 5.1.3 compiling with TypeScript fails:
```
error TS2688: Cannot find type definition file for 'cypress'.
  The file is in the program because:
    Entry point of type library 'cypress' specified in compilerOptions
```
I set up the repo using the guide https://docs.cypress.io/guides/tooling/typescript-support

Please see the minimal repo: https://github.com/holgergp/typescript51AndCypress and the test run: https://github.com/holgergp/typescript51AndCypress/actions/runs/5175463023/jobs/9323074464

### Desired behavior

Please provide docs to circumvent this issue. (or maybe fix this)

### Test code to reproduce

Please see the minimal repo: https://github.com/holgergp/typescript51AndCypress and the test run: https://github.com/holgergp/typescript51AndCypress/actions/runs/5175463023/jobs/9323074464

### Cypress Version

12.13.0

### Node version

18.16.0

### Operating System

Github Actions: ubuntu-latest

### Debug Logs

```shell
https://github.com/holgergp/typescript51AndCypress/actions/runs/5175463023/jobs/9323074464
```

**Comment by MoSattler** [comment]
Same problem here - anyone found a workaround?

**Comment by warrensplayer** [comment]
This seems to be a problem with a breaking change with Typescript 5.1.3.  See: https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#explicit-typeroots-disables-upward-walks-for-node_modules-types

@holgergp  I have replicated your problem in the latest version of Cypress and will forward this ticket to the appropriate team. They will soon evaluate the priority of this ticket and consider their capacity to pick it up. Please note that this does not guarantee that this issue will be resolved. The ticket will indicate status changes during evaluation, so we ask that you please refrain from asking for updates. Thanks!

**Comment by lmiller1990** [comment]
Let's pick this up asap, and update our ecosystem pipeline so we can catch these earlier.

**Comment by jordanpowell88** [comment]
The solution for this is to specify path to the type files in `typeRoots`.  For example `cypress` types  from the root directory would look like the following:


I recommend viewing our documentation around [Configuring typescript](https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfigjson). However, if you need to specify `typeRoots` in your project you will need to implement the solution below. It is important to note that this is not an issue with Cypress itself but a breaking change in [Typescript 5.1](https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#explicit-typeroots-disables-upward-walks-for-node_modules-types). This change in Typescript does not exclusively affect Cypress types but any library that ships types as part of the library.

```ts
"typeRoots": ["./node_modules", "./node_modules/@types"],
```

The TDLR: Don't use `typeRoots` or add a path to `node_modules` where `cypress` is installed.
