### ISSUE TITLE
Cypress crash issue for version 11.2.0 and 12.12.0

### ISSUE THREAD

**Issue by Pipul-Pant** [cypress-io/cypress#26960]
### Current behavior

While executing certain specs and in case of failure maybe assertion failure or iframe loading, the electron browser is crashing locally as well as in Jenkins. I have tried all the fixes but the issue is happening too frequetly. 

### Desired behavior

In case of any failure, maybe element not found or iframe loading issue , it should display the failure message. It should never crashing in case it is not getting any element or performing any action .

### Test code to reproduce

it is confidentials test case. but i have used it in the format like:

describe('',()=>{
describe1('',()=>{
describe2('',()=>{
describe3('',()=>{
})
})

### Cypress Version

11.2.0

### Node version

v16.14.2

### Operating System

Jenkins

### Debug Logs

```shell
<--- Last few GCs --->

[872:0x450003e4000]   755052 ms: Scavenge 495.2 (665.2) -> 489.1 (665.2) MB, 2.7 / 0.0 ms  (average mu = 0.998, current mu = 0.998) task; 
[872:0x450003e4000]   757111 ms: Scavenge 495.5 (665.2) -> 489.4 (665.2) MB, 3.2 / 0.0 ms  (average mu = 0.998, current mu = 0.998) task; 
[872:0x450003e4000]   759110 ms: Scavenge 495.7 (665.2) -> 489.7 (665.2) MB, 2.9 / 0.0 ms  (average mu = 0.998, current mu = 0.998) task; 


<--- JS stacktrace --->

[872:0607/132230.133410:ERROR:v8_initializer.cc(730)] V8 process OOM (Oilpan: Reserving memory.).

We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed
```

**Comment by nagash77** [comment]
Hi @Pipul-Pant , I am sorry to hear you are having issues upgrading Cypress.  Can you try setting the [experimentalMemoryManagement](https://docs.cypress.io/guides/references/experiments#Configuration) flag to true and see if that solves your issue?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by chestermjr** [comment]
I'm having this problem as well. Enabling `experimentalMemoryManagement` did not help. Any other thoughts? Thanks in advance!

**Comment by nagash77** [comment]
Hi @chestermjr without the details of your specific use case I cannot say.  Do you have a reproducible example you can share in a fork of [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny)?

Check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
