### ISSUE TITLE
Yarn install bug when update in 12.14.0

### ISSUE THREAD

**Issue by arochard** [cypress-io/cypress#26971]
### Current behavior

When I try to install the new version (12.14.0), I get stuck at the 'Building fresh packages' step. This works when downgrading to 12.13.0.

<img width="747" alt="Capture d’écran 2023-06-08 à 15 22 40" src="https://github.com/cypress-io/cypress/assets/4533756/8a4db650-28cf-4128-a264-1207e1ff849a">

### Cypress Version

12.14.0

### Node version

18.12.1

### Package Manager

yarn

### Package Manager Version

1.22.19

### Operating system

Mac

### Operating System Version

12.2

**Comment by MikeMcC399** [comment]
@arochard 

You may be able to see better where the problem is coming from if you execute:

```bash
yarn add cypress -D --verbose
```

In some cases it may also help to delete the `node_modules` directory and run the `yarn` command again.

**Comment by arochard** [comment]
Thanks for your answer.

But I've already tried to delete `node_modules`, clear the yarn cache and run the `yarn` command. 

I've also tried changing the node version (v16.20.0), or using `npm`.

But despite all these attempts, the results are the same

**Comment by MikeMcC399** [comment]
@arochard 

Did you also try using `--verbose` to get a more detailed log? In your screenshot `[18/18] cypress` it looks like Cypress has finished and that it may be stuck somewhere else.

**Comment by arochard** [comment]
Yes, I tried with `--verbose`, and to make sure it wasn't a conflict with another package, I tried with a new project.

Output from `yarn add cypress -D --verbose` (last lines) :

<img width="1510" alt="Capture d’écran 2023-06-08 à 17 41 51" src="https://github.com/cypress-io/cypress/assets/4533756/499c3d8e-5043-4e12-bff3-cac07f6d168c">

**Comment by MikeMcC399** [comment]
@arochard 

I wasn't able to reproduce on Ubuntu 22.04 (I don't have macOS available), so unfortunately I probably can't help you much more:

Node.js is `18.12.1`

The following executed without a problem:

```bash
npm install yarn@latest -g
mkdir cy-yarn-new
cd cy-yarn-new
git init
npm init -y
yarn add cypress -D -E
```

log:

```text
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning cypress > @cypress/request > qs@6.10.5: when using stringify with arrayFormat comma, `[]` is appended on single-item arrays. Upgrade to v6.11.0 or downgrade to v6.10.4 to fix.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 151 new dependencies.
info Direct dependencies
└─ cypress@12.14.0
info All dependencies
... (not listed)
```

**Comment by MikeMcC399** [comment]
I don't know whether it will help very much, but you could check to see if Cypress 12.14.0 has been installed if you execute:

```bash
yarn cypress verify
yarn cypress info
```

**Comment by arochard** [comment]
I don't know why, but this morning it worked... 
Thanks for your help !

**Comment by MikeMcC399** [comment]
@arochard 

> I don't know why, but this morning it worked...

Perhaps you just didn't wait long enough? The first time you install a new version of Cypress it has to download and unzip it into cache. Especially the unzip can take quite a time without any console output.

> Thanks for your help !

You are welcome! I always learn something new on every new issue!
