### ISSUE TITLE
Cypress dashboard not displaying image correctly for image snapshots

### ISSUE THREAD

**Issue by adamchenwei** [cypress-io/cypress#2697]
### Is this a Feature or Bug?
Bug

### Current behavior:
The image is displayed narrower than it originally is.

### Desired behavior:

Allow image diff snapshots to display in the correct ratio as its taken.
### Steps to reproduce:
Go to repo https://dashboard.cypress.io/#/projects/a16q3n/runs/1/failures
and open the screenshot to see the image display in a squished ratio
<img width="1315" alt="screen shot 2018-10-31 at 4 57 03 pm" src="https://user-images.githubusercontent.com/4201698/47818260-0ceea280-dd2e-11e8-9ed9-15b59066317a.png">

<img width="1679" alt="screen shot 2018-10-31 at 4 54 41 pm" src="https://user-images.githubusercontent.com/4201698/47818267-10822980-dd2e-11e8-824a-0d44152e5a3a.png">

### Versions
Latest (3.1.0)

MacOS

Chrome Latest 70.0

**Comment by jennifer-shehane** [comment]
This is indeed a bug in the Dashboard's screenshot preview. I'll look into this and let you know of any updates.

**Comment by jennifer-shehane** [comment]
Actually, this appears to be a bug in our API. The Dashboard displays the screenshot at the size specified when the request to the image was made. The natural dimensions of this image are `2952 x 44`, yet the API sends the dimensions as:

```
height: 44
width: 984
```

**Comment by adamchenwei** [comment]
@jennifer-shehane thank you for taking the intiate to look into this. Plz let me know if anything else I can help with. thanks!

**Comment by adamchenwei** [comment]
@jennifer-shehane its been a while. any update?

**Comment by jennifer-shehane** [comment]
@adamchenwei I've followed up on the API, the issue doesn't appear to have originated from there - and instead the Test Runner is sending the wrong dimensions to the API.

We'll have to investigate how these dimensions are originally calculated within the Test Runner (which is this repo's open source code)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
