### ISSUE TITLE
404 Not Found - GET https://repo.huaweicloud.com/repository/npm/@types/node/-/node-14.18.48.tgz

### ISSUE THREAD

**Issue by VladimirAstafievInDrive** [cypress-io/cypress#26981]
### Current behavior

Cant install cypress

npm ERR! code E404
npm ERR! 404 Not Found - GET https://repo.huaweicloud.com/repository/npm/@types/node/-/node-14.18.48.tgz
npm ERR! 404 
npm ERR! 404  '@types/node@https://repo.huaweicloud.com/repository/npm/@types/node/-/node-14.18.48.tgz' is not in this registry.

### Test code to reproduce

npm install cypress --save-dev

### Cypress Version

12.13.0

### Node version

v18.13.0

### Operating System

macOS 13.3.1 (a) (22E772610a)

**Comment by MikeMcC399** [comment]
@VladimirAstafievInDrive 

After executing

```bash
npm install cypress@12.13.0 --save-dev
```

on a standard npm configuration `package-lock.json` contains the following entry:

```json
    "node_modules/@types/node": {
      "version": "14.18.48",
      "resolved": "https://registry.npmjs.org/@types/node/-/node-14.18.48.tgz",
      "integrity": "sha512-iL0PIMwejpmuVHgfibHpfDwOdsbmB50wr21X71VnF5d7SsBF7WK+ZvP/SCcFm7Iwb9iiYSap9rlrdhToNAWdxg==",
      "dev": true
    },
```

Possibly you have set `npm` to use an alternate registry and this is causing an issue.

The default registry is https://registry.npmjs.org/ (see https://docs.npmjs.com/cli/v9/using-npm/registry and https://docs.npmjs.com/cli/v9/using-npm/config#registry).

**Comment by nagash77** [comment]
Hi @VladimirAstafievInDrive I cannot reproduce this behavior.  I don't know why your npm is pointed towards a huaweicloud.com URL.  You should check with your network admins to see if they are overriding settings on your machine and network. 

Can you try installation on another machine/network?

**Comment by VladimirAstafievInDrive** [comment]
Thanks everyone for the response. The problem was solved by a complete reinstalling.
