### ISSUE TITLE
Cypress times out on "(page load) --waiting for new page to load--" when navigating from https to http

### ISSUE THREAD

**Issue by gkreitz** [cypress-io/cypress#26982]
### Current behavior

When viewing a `https://` page, most types of navigation to a `http://` URL seem to hang Cypress on page load, causing it to eventually time out after 60 seconds with the message (adding it all to make this easier to find for people searching error messages)
```
Timed out after waiting 60000ms for your remote page to load.

Your page did not fire its load event within 60000ms.

You can try increasing the pageLoadTimeout value in cypress.config.js to wait longer.

Browsers will not fire the load event until all stylesheets and scripts are done downloading.

When this load event occurs, Cypress will continue running commands.
```
While waiting for the page to load, the GUI displays `(page load) --waiting for new page to load--`.

I've found this to happen both on 302 responses, as well as simply clicking a link. There are some subtleties involved though, for instance navigation to `http://127.0.0.1/` works as expected.

### Test code to reproduce

The following spec should be enough to reproduce the issue:
```
describe('page', {baseUrl: 'https://github.com/'}, () => {
  it('works', () => {
      cy.visit('/gkreitz/cypress-test-tiny')
      cy.get('a[href="http://google.com/"]').click()
  })
})
```

Repo at: https://github.com/gkreitz/cypress-test-tiny . Note that I run Cypress via docker, so I did not add a dependency to `package.json`. For completeness, I added a script `./run_cypress.sh` with the exact command line for running in docker.

### Cypress Version

12.14.0

### Node version

Whatever version comes with your docker image

### Operating System

Linux from your docker image. Host OS: Linux, Ubuntu 22.04.2 LTS

### Debug Logs

```shell
Debug logs are huge, I put them on https://github.com/gkreitz/cypress-test-tiny/blob/master/debug.log
```

**Comment by MikeMcC399** [comment]
@gkreitz 

Please see https://docs.cypress.io/guides/guides/web-security#Insecure-Content

> Insecure Content
>
> Because of the way Cypress is designed, if you are testing an HTTPS site, Cypress will error anytime you attempt to navigate back to an HTTP site. This behavior helps highlight a pretty serious security problem with your application.

https://github.com/cypress-io/cypress/issues/26586#issuecomment-1524145388 may also help you.

**Comment by gkreitz** [comment]
Thanks for the pointer, apparently I completely failed to Google the right thing when I ran into this and started debugging!

**Comment by rafaelcavalcante** [comment]
Cypress just started to fail in some tests written for more than 2 years ago with this same issue. In my case the page is fetching an image that does not exist anymore and the browser tries to load the image and fails, thats why it does not dispatch the onload event 👍
