### ISSUE TITLE
Unable to use javascript toISOstring() method in cypress, console displays "Invalid time value"

### ISSUE THREAD

**Issue by AK1699** [cypress-io/cypress#26986]
### Current behavior

![MicrosoftTeams-image (12)](https://github.com/cypress-io/cypress/assets/99952032/a44e25e2-8cda-4de4-a4cc-9fa5f73dbf75)

### Desired behavior

Im expecting the ISO string method should work in cypress as well

### Test code to reproduce
```js
  export const automatedDates = (start_Date, end_Date) => {
  var startDate = new Date(start_Date);
  var endDate = new Date(end_Date);

  var startTimestamp = startDate.getTime();
  var endTimestamp = endDate.getTime();

  console.log(startTimestamp)
  console.log(endTimestamp)

  var randomStartTimestamp = startTimestamp + Math.floor(Math.random() * (endTimestamp - startTimestamp));
  var randomEndTimestamp = randomStartTimestamp + Math.floor(Math.random() * (endTimestamp - randomStartTimestamp));

  var randomStartDate = new Date(randomStartTimestamp);
  var randomEndDate = new Date(randomEndTimestamp);
  cy.log(randomStartDate)
  var start_date = randomStartDate.toISOString().split('T')[0];
  var end_date = randomEndDate.toISOString().split('T')[0];

  console.log("Random Start Date:", randomStartDate.toISOString().split('T')[0]);
  console.log("Random End Date:", randomEndDate.toISOString().split('T')[0]);

  return { start_date, end_date }
}
```

### Cypress Version

12.13

### Node version

v18.12.1

### Operating System

Windows 10.0.19044.1889

**Comment by mike-plummer** [comment]
Hi @AK1699 , sorry to hear you're having trouble. I took a look and your example function works just fine for me using Cypress v12.13 *provided* a valid numeric value (or parse-able date string) is passed in for both `start_Date` and `end_Date` - can you confirm what sort of value you're attempting to provide for those parameters?

The "Invalid time value" is a built-in error message that occurs when you try to do something like the following in JS, so I suspect you may just have an issue with how you're initializing your input date values:

`new Date('').toISOString()` => `Invalid time value`

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
