### ISSUE TITLE
No Log section showing in Cypress

### ISSUE THREAD

**Issue by forgetso** [cypress-io/cypress#26985]
### Current behavior

I have logs in my tests but no log section appears in the test runner. This happens in Firefox and Electron. I've tried clearing the app data as per https://github.com/cypress-io/cypress/issues/2107.

```
  └── cypress@12.14.0
```

```
    it.only("Captchas load when 'I am human' is pressed", async () => {
        const captchas = await cy.clickIAmHuman().promisify()
        cy.log('wtfff')
        expect(captchas.length).to.be.gt(0)
    })
```

![image](https://github.com/cypress-io/cypress/assets/7630866/dc4e9068-1cf5-41f8-ba69-518a82d50686)

### Desired behavior

Logs will show

### Test code to reproduce

```bash
git clone https://github.com/prosopo/captcha
cd captcha
git checkout 97-enable-cypress-testing
npm i
npm run bd dev
docker compose --file docker/docker-compose.development.yml up -d
cp ./dev/env.development ./dev/.env.development
cp ./demos/client-example-server/env.development ./demos/client-example-server/.env.development
cp ./demos/client-example/env.development ./demos/client-example/.env.development
npm run setup:all
```

If the last command (`setup:all`) fails, try running setup afterwards.

```bash
npm run setup
```

In 4 different terminals run

#### Terminal 1
```bash
npm run start:server
```

#### Terminal 2
```bash
npm run start:provider
```

#### Terminal 3
```bash
npm run start:demo
```

#### Terminal 4
```bash
cd demos/client-example
npm run cypress:open
```
### Cypress Version

12.14.0

### Node version

v18.14.2

### Operating System

Linux 5.4.0-150-generic #167-Ubuntu

**Comment by forgetso** [comment]
Hi, I've added details for reproduction.

**Comment by mschile** [comment]
Hi @forgetso 👋, thanks for taking the time to log an issue. Unfortunately, I was unable to run the test using the reproduction steps provided. 

I received the following error when running: `npm run bd dev`

```shell
../packages/procaptcha-react/src/components/ExtensionAccountSelect.tsx:38:13 - error TS2304: Cannot find name 'env'.
38             env
               ~~~
../packages/procaptcha-react/src/components/ExtensionAccountSelect.tsx:42:13 - error TS2304: Cannot find name 'env'.
42             env
               ~~~
../packages/procaptcha-react/src/components/ExtensionAccountSelect.tsx:58:21 - error TS2304: Cannot find name 'env'.
58                     env
                       ~~~
../packages/procaptcha-react/src/components/ExtensionAccountSelect.tsx:61:21 - error TS2304: Cannot find name 'env'.
61                     env
                       ~~~
```

I commented out the `env` lines in that file and built successfully but then running `npm run start:server` I received the following error:

```
Error: No mnemonic found
    at main (/Users/mschile/Projects/captcha/demos/client-example-server/dist/app.js:39:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Simiilar mnemonic error when running `npm run start:provider`:

```
undefined ProsopoEnvError: No mnemonic or seed provided
```

**Comment by forgetso** [comment]
Hi @mschile, sorry I had missed a couple of lines in the setup script. There are two additional env files that need copied before the `setup:all` script is run. I've added them to the description above.

Also the build errors were simply a mistake caused by a find & replace. I've corrected these.

If you pull again now you will have a working build. Let me know if it works for you! Thanks

**Comment by mschile** [comment]
@forgetso, when running any of the following commands (`npm run setup`, `npm run setup:all`, `npm run start:server`, `npm run start:provider`) I receive the following error continuously:

```
2023-06-13 16:06:28          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
2023-06-13 16:06:30          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
2023-06-13 16:06:33          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
2023-06-13 16:06:35          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
2023-06-13 16:06:38          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
2023-06-13 16:06:40          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
2023-06-13 16:06:43          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
2023-06-13 16:06:45          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
```

Clicking on the "I am a  human" box just results in a infinite spinner.
![Image](https://github.com/cypress-io/cypress/assets/2002044/b9e82bce-013d-4d2b-91d2-5afab1d80504)

Just looking at your test, have you tried removing `cypress-promise` to verify that is not causing any issues?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
