### ISSUE TITLE
Alias of `cy.focused()` follows `document.activeElement`

### ISSUE THREAD

**Issue by DaviDevMod** [cypress-io/cypress#26998]
### Current behavior

According to [the docs](https://docs.cypress.io/api/commands/focused), `cy.focused()` should:

> Get the DOM element that is currently focused.

So one would expect that aliasing `cy.focused()` would create an alias for the element that is currently focused, not for an ever changing `document.activeElement`.

### Desired behavior

Aliasing `cy.focused()` should create an alias for the element that is currently focused.

### Test code to reproduce

```js
cy.focused().as('activeElement');
// Follows `document.activeElement`.
cy.get('@activeElement');

cy.focused().then(($focused) => $focused).as('currentlyFocused');
// Gets always the same element.
cy.get('@currentlyFocused');
```

### Cypress Version

12.14.0

### Node version

16.14.0

### Operating System

Ubuntu 22.04.2

**Comment by DaviDevMod** [comment]
So it looks like (luckily for me, I never had to use jQuery) the jQuery [`.wrap()`](https://api.jquery.com/wrap/#wrap-function) method can accept a function as argument.

So I believe that in here:

https://github.com/cypress-io/cypress/blob/0d26b0fa23b438cee71f36a13cd3cc508fd5a220/packages/driver/src/cy/focused.ts#L281

What's being wrapped is the actual getter function [`activeElement`](https://html.spec.whatwg.org/multipage/interaction.html#dom-documentorshadowroot-activeelement).

So a fix could be [this](https://github.com/DaviDevMod/cypress/commit/51edba7be303819ebc1cbd4ed2943162a7c36172):

```ts
const activeElement = Object.getOwnPropertyDescriptor(document, 'activeElement')!.get!.call(document);
```

Though I haven't tested it yet and I am not even sure that it's the best approach.

**Comment by warrensplayer** [comment]
I believe what you are experiencing is related to the behavior of the `alias` command as described here: https://docs.cypress.io/guides/references/migration-guide#Behavior-Changes-in-Alias-Resolution

I will confirm with the team and get back to you.

**Comment by DaviDevMod** [comment]
@warrensplayer using `{ type: 'static' }` to opt into the old behavior does work.

However, for how the latest behaviour is explained, it looks like `.as()` creates an alias for the whole chain of commands leading to it, rather than for the subject it was given.
If that's the case, then the alias:

```ts
cy.focused().then(($focused) => $focused).as('currentlyFocused');
```

from my original post, should also yeld `document.activeElement` rather than always the same static element.

**Comment by warrensplayer** [comment]
@DaviDevMod In this case, the `.then` is what breaks the "retryability" of the chain of commands.  It is not retried.  See the last paragraph of the "Yields" section for `.then()` here: https://docs.cypress.io/api/commands/then#Yields-Icon-namequestion-circle

**Comment by DaviDevMod** [comment]
@warrensplayer thank you very much for the clarifications.
