### ISSUE TITLE
Angular component test is not triggering autoDetectChanges

### ISSUE THREAD

**Issue by NicolasCaous** [cypress-io/cypress#26990]
### Current behavior

I encountered the following situation: I had to test what would happen when a component that uses observables as input changed data. Here is the component:

```typescript
class MyService {
  getData(): Observable<boolean> {
    return of(true); // Not important, is going to get mocked
  }
}

@Component({
  selector: 'my-component',
  template: `<ng-container *ngIf="vm$ | async as data">{{ data.myData ? 'true' : 'false' }}</ng-container>`,
  styles: ['.my-class {}'],
})
export class MyComponent {
  myData$: Observable<boolean> = this.myService.getData();

  vm$ = combineLatest({
    myData: this.myData$,
  }); // I'm using the VM pattern: https://medium.com/@maxmumford/use-the-view-model-pattern-for-more-reactive-angular-programming-507751a8349e

  constructor(private myService: MyService) {}
}
```

Here is the test:

```typescript
describe('My Component', () => {
  let inputDisabled$: ReplaySubject<boolean>;

  beforeEach(() => {
    inputDisabled$ = new ReplaySubject<boolean>(1);
    inputDisabled$.next(true);

    cy.mount('<my-component></my-component>', {
      declarations: [MyComponent],
      imports: [NoopAnimationsModule],
      providers: [
        {
          provide: MyService,
          useValue: {
            getData: () => inputDisabled$.asObservable().pipe(tap(console.log)),
          } as Partial<MyService>,
        },
      ],
      autoDetectChanges: true,
    })
  });

  it('Should show "false" before data loads and "true" after', () => {
    cy.then(() => inputDisabled$.next(false));
    cy.get('my-component').should('have.text', 'false');

    cy.then(() => inputDisabled$.next(true));
    cy.get('my-component').should('have.text', 'true');
  });
});
```

However, when inputDisabled emits a new value for the second time, the data detection cycle is not starting. Resulting in a broken stale state. The logs show that RxJS processed the data correctly:

![image](https://github.com/cypress-io/cypress/assets/24411365/646317f6-0381-4688-8c10-8588106379dd)

However, the result rendered on the DOM is not the latest value emitted 

![image](https://github.com/cypress-io/cypress/assets/24411365/9a756bf1-3da0-4c8b-a003-ec4a9f844fd0)

After manually triggering the change detection, it works:

```typescript
describe('My Component Fixed', () => {
  let inputDisabled$: ReplaySubject<boolean>;
  let componentFixture: ComponentFixture<unknown>;

  beforeEach(() => {
    inputDisabled$ = new ReplaySubject<boolean>(1);
    inputDisabled$.next(true);

    cy.mount('<my-component></my-component>', {
      declarations: [MyComponent],
      imports: [NoopAnimationsModule],
      providers: [
        {
          provide: MyService,
          useValue: {
            getData: () => inputDisabled$.asObservable().pipe(tap(console.log)),
          } as Partial<MyService>,
        },
      ],
      autoDetectChanges: true,
    }).then((wrapper) => {
      componentFixture = wrapper.fixture;
    });
  });

  it('Should show "false" before data loads and "true" after', () => {
    cy.then(() => inputDisabled$.next(false));
    cy.then(() => componentFixture.detectChanges());
    cy.get('my-component').should('have.text', 'false');

    cy.then(() => inputDisabled$.next(true));
    cy.then(() => componentFixture.detectChanges());
    cy.get('my-component').should('have.text', 'true');
  });
});
```

![image](https://github.com/cypress-io/cypress/assets/24411365/c16b57d1-29cd-4ec3-914e-8dcc32c5e737)
![image](https://github.com/cypress-io/cypress/assets/24411365/f2ee80b7-f306-49c5-afe8-6fc9d3445bba)

### Desired behavior

`autoDetectChanges` should work

### Test code to reproduce

```typescript
import { combineLatest, Observable, of, ReplaySubject } from 'rxjs';
import { Component } from '@angular/core';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { tap } from 'rxjs/operators';
import { ComponentFixture } from '@angular/core/testing';

class MyService {
  getData(): Observable<boolean> {
    return of(true); // Not important, is going to get mocked
  }
}

@Component({
  selector: 'my-component',
  template: `<ng-container *ngIf="vm$ | async as data">{{ data.myData ? 'true' : 'false' }}</ng-container>`,
  styles: ['.my-class {}'],
})
export class MyComponent {
  myData$: Observable<boolean> = this.myService.getData();

  vm$ = combineLatest({
    myData: this.myData$,
  }); // I'm using the VM pattern: https://medium.com/@maxmumford/use-the-view-model-pattern-for-more-reactive-angular-programming-507751a8349e

  constructor(private myService: MyService) {}
}

describe('My Component', () => {
  let inputDisabled$: ReplaySubject<boolean>;

  beforeEach(() => {
    inputDisabled$ = new ReplaySubject<boolean>(1);
    inputDisabled$.next(true);

    cy.mount('<my-component></my-component>', {
      declarations: [MyComponent],
      imports: [NoopAnimationsModule],
      providers: [
        {
          provide: MyService,
          useValue: {
            getData: () => inputDisabled$.asObservable().pipe(tap(console.log)),
          } as Partial<MyService>,
        },
      ],
      autoDetectChanges: true,
    })
  });

  it('Should show "false" before data loads and "true" after', () => {
    cy.then(() => inputDisabled$.next(false));
    cy.get('my-component').should('have.text', 'false');

    cy.then(() => inputDisabled$.next(true));
    cy.get('my-component').should('have.text', 'true');
  });
});


describe('My Component Fixed', () => {
  let inputDisabled$: ReplaySubject<boolean>;
  let componentFixture: ComponentFixture<unknown>;

  beforeEach(() => {
    inputDisabled$ = new ReplaySubject<boolean>(1);
    inputDisabled$.next(true);

    cy.mount('<my-component></my-component>', {
      declarations: [MyComponent],
      imports: [NoopAnimationsModule],
      providers: [
        {
          provide: MyService,
          useValue: {
            getData: () => inputDisabled$.asObservable().pipe(tap(console.log)),
          } as Partial<MyService>,
        },
      ],
      autoDetectChanges: true,
    }).then((wrapper) => {
      componentFixture = wrapper.fixture;
    });
  });

  it('Should show "false" before data loads and "true" after', () => {
    cy.then(() => inputDisabled$.next(false));
    cy.then(() => componentFixture.detectChanges());
    cy.get('my-component').should('have.text', 'false');

    cy.then(() => inputDisabled$.next(true));
    cy.then(() => componentFixture.detectChanges());
    cy.get('my-component').should('have.text', 'true');
  });
});

```

### Cypress Version

v12.14.0

### Node version

v18.10.0

### Operating System

windows 10

**Comment by warrensplayer** [comment]
@NicolasCaous Are you able to create reproducible example of the issue you're encountering with the code you included above? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

That would be a big help to get us to be able to reproduce your issue the quickest.  Thanks!

**Comment by NicolasCaous** [comment]
Hi @warrensplayer, I need to wait for https://github.com/cypress-io/cypress/pull/27030 before doing that. I tried doing it now, but Cypress kept throwing errors for angular 16.1.0.

**Comment by mike-plummer** [comment]
Hey @NicolasCaous , just wanted to let you know that Angular 16.1.0 support was released yesterday in [Cypress 12.16.0](https://docs.cypress.io/guides/references/changelog#12-16-0). Looking forward to a reproduction case whenever you have a few minutes to upgrade and take a look

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by muhamedkarajic** [comment]
I have issues with cypress I just don't understand how to await something when its about an observable. I get the points when its about UI but what if I have a subject which I want to await for the next object or I have just a 'store' which I expect a value to be. It seems like somehow the async code executes after the sync.

**Comment by nagash77** [comment]
@muhamedkarajic Issues in repo are reserved for bug reports and feature requests. Check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by AronHoxha** [comment]
I would like to reopen this issue. I have created a reproducible fork of the cypress-test-tiny repo [here](https://github.com/AronHoxha/cypress-test-tiny).
Personally I have experienced this when utilizing angular routing, but in general the issue seems to be with using the async pipe

Edit: It seems that it is required to detect changes after navigation, this causes observable changes to update properly
