### ISSUE TITLE
Cypress with Next.js and Auth0 authentication is making tests behave weird.

### ISSUE THREAD

**Issue by gripzyyy** [cypress-io/cypress#26999]
### Current behavior

Hi! Here is a demo of my app that uses next.js, auth0 and cypress for testing: https://github.com/gripzyyy/cypress-auth0-nextjs-issue
I want to authenticate my user, then visit / before all tests.
If you clone the repository, complete the .env variables so that auth0 works then run the tests, you will see that cypress correctly logs that it tries to authenticate the user, then navigates to / then the navigation continues, the flow of everything being weird. It ends with a timeout error. This is all using the code from: https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication

### Desired behavior

Cypress should authenticate the user then go to /.

### Test code to reproduce

https://github.com/gripzyyy/cypress-auth0-nextjs-issue
test is:
```js
describe("Auth", () => {
  beforeEach(() => {
    cy.loginToAuth0(
      Cypress.env('auth0_username'),
      Cypress.env('auth0_password')
    )
    cy.visit("/");
  });
  it("check login", () => {
    //cy.get("[data-cy=login-btn]").click();
    //cy.get("[data-cy=logout-btn]").should("be.visible");
  });
});
```
### Cypress Version

12.14.0

### Node version

18.16.0

### Operating System

Windows 10.0.19045.2965

**Comment by mschile** [comment]
Hi @gripzyyy 👋, the [cy.loginToAuth0](https://github.com/gripzyyy/cypress-auth0-nextjs-issue/blob/main/cypress/support/auth-provider-commands/auth0.ts#L2-L3) command in your repository is assuming your application's landing page is redirecting to your Auth0 tenant's login page. You'll want to setup your application to ensure that it is properly redirecting. I would suggest working on your application outside of Cypress first and verify you are able to correctly navigate to your homepage, login, and then get redirected back logged in.

**Comment by gripzyyy** [comment]
Hi @mschile, thanks for the quick response!
I updated the repo so things are clear, you just have to fill in the .env variables according to the guide for auth0 testing.
The application works perfectly outside of Cypress, the login and logout button both work perfectly.
Why do you say that the cy.loginToAuth0 command is assuming that the route "/" is redirect to my Auth0 login page? I do cy.visit('/') then run cypress commands to another origin using cy.origin, and there I get the inputs, I fell them and I click the Continue Button, which then should login the user and redirect automatically to "/".

There is another 2 problems I found out: (all the code is in the repo and can be tested on a sample auth0 app)
Firstly, following the guide, when I try to login using the UI via cy.origin() it will give me this:
![image](https://github.com/cypress-io/cypress/assets/38363307/ba95c410-8f1a-49f6-b002-38e7bf429fd8)
The cy.loginToAuth0 correctly visits '/', then makes the origin the auth0_domain, but then when it wants to get the input for the username it times out, it seems that the auth0_domain page is not rendering or there is some problem with cy.origin().

Secondly, I tried going the other route and doing the auth programatically, using a POST request, not the UI. 
![image](https://github.com/cypress-io/cypress/assets/38363307/81ae9a50-26f1-4038-b679-7e5a1219c5bc)
The POST request times out which is really strange. I am quite sure my app is well set up, I put "http://localhost:3000" in allowed origins and allowed web origins, the auth works perfectly outside cypress. The only thing I did not set up is an audience.

I am looking forward to solving this issue or finding out if there is a cypress problem or really an auth0 one.

**Comment by mschile** [comment]
Hi @gripzyyy, as you can see in your first screenshot above, your application doesn't automatically redirect to the login page which is what your [cy.loginToAuth0](https://github.com/gripzyyy/cypress-auth0-nextjs-issue/blob/main/cypress/support/auth-provider-commands/auth0.ts#L2-L3) command is assuming and leads to the origin error. If your application isn't going to redirect, you'll want to click the login button first before proceeding to the `cy.origin` command. Something like:

```js
function loginViaAuth0Ui(username: string, password: string) {
  // Since App landing page doesn't redirects to Auth0, click the Login link.
  cy.visit('/').contains('Login').click()
  
  // Login on Auth0.
  cy.origin(
    Cypress.env('auth0_domain'),
    { args: { username, password } },
    ({ username, password }) => {
      cy.get('input#username').type(username)
      cy.get('input#password').type(password, { log: false })
      cy.contains('button[value=default]', 'Continue').click()
    }
  )

  // Ensure Auth0 has redirected us back to the RWA.
  cy.url().should('equal', 'http://localhost:3000/')
}
```

**Comment by gripzyyy** [comment]
Hi! Thanks you for the responses.
Yes that was the problem! I think this should be updated then: https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication
Also, you can not get the 'Continue' button with that selector anymore, cause there is another one containing the text 'Continue' with value default, so you'd have to maybe do: 
cy.contains('button[data-action-button-primary=true]', 'Continue').click()

That's what working for me!

**Comment by mschile** [comment]
Thanks for the heads-up on the guide, I'll take a look at it.

**Comment by juanzuluagag** [comment]
@mschile Do you have an advice for logging-In with the passwordless configuration? 

Basically, what is happening to me is: 

1. First screen ask the user for the email address. (Redirecting from `http://localhost:3000/` to `https://myapp.us.auth0.com/u/login/identifier?state=hKFo2SBleElVaHIwQVM4UHNYQUs0ME5zUGtibzR4dUx3eGtIOKFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIFdLeXFHQlVWb1U1XzlLMzR0QnRYNHVJbXpmQXVwYi05o2NpZNkgRlhXSGk5TXc0ZGZIa3JiMXBqcUY2dzJWNlYxQUdhS1A`)
2. A verification code is being sent to that email address (Redirecting to `https://myapp.us.auth0.com/u/login/passwordless-email-challenge?state=hKFo2SBnWVItVEJDT3FGTUFvWG1GRFVjQmdHLUR5YkVPaU14b6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIHY4ZmVjVzZpT3BZb0hHaXo1RXVCY1B3LXhmd3BFVEdjo2NpZNkgRlhXSGk5TXc0ZGZIa3JiMXBqcUY2dzJWNlYxQUdhS1A`). 
3. The user needs to type the "Verification code" in a second screen. 
4. Landing page is finally shown to the user. (Redirected to `http://localhost:3000/`)

What I need to find, is a way to be able to go to the landing page, without accessing the user email inbox and get the "verification code", mainly, because I am not the owner of the inboxes to be used.

**Comment by nagash77** [comment]
@juanzuluagag Check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
