### ISSUE TITLE
If cypress doesn't know the number of failures, exit with 1 instead of 0

### ISSUE THREAD

**Issue by ianrose14** [cypress-io/cypress#270]
This addresses the case where the headless browser crashes unexpectedly before cypress accumulates any errors, and then cypress (wrongly) exits with code 0 as though everything passed successfully.

related: https://github.com/cypress-io/cypress/wiki/changelog#0165-07312016

from @brian-mann in chat:

> likely we'd also need to log out a message saying that
> Cypress sub-process exited without a valid number of failures. We're assuming something went wrong or crashed and so we're exiting with 1 to indicate this run failed.

**Comment by brian-mann** [comment]
Related to #348

**Comment by brian-mann** [comment]
Fixed in [`0.18.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0183-12182016).

**Comment by bahmutov** [comment]
such a great fix!
