### ISSUE TITLE
Strange behaviour when completing a multi-step registration form

### ISSUE THREAD

**Issue by waqas-khan-news** [cypress-io/cypress#27004]
### Current behavior

To log into our site a user must complete a 2 step registration process. The first step is to open a registration form (labelled Step 1 of 2). They complete the required fields and checkboxes, then click the submit, which should take them to Step 2. When I run this scenario with a simple test in Cypress, we never reach Step 2. 

The exact behaviour seen varies depending on the version of Cypress installed.  For example, using version 11.1.0, when we click the submit button the cypress browser redirects to the sign in page, and not Step 2 of registration:

<img width="794" alt="Screenshot 2023-06-12 at 15 42 25" src="https://github.com/cypress-io/cypress/assets/88845629/9cb2c549-32b7-48a5-ab5e-c2614c7d6a23">

we also tested this against version 12.14.0 (the latest version of Cypress as of writing this ticket). IN that case when we navigate to Step 1 of the registration page, some of the text fields and check boxes are not rendering at all, making it impossible to complete the form and reach Step 2:

<img width="795" alt="Screenshot 2023-06-12 at 15 44 42" src="https://github.com/cypress-io/cypress/assets/88845629/eddf0e96-647b-49be-b0d0-0e238b55a122">

### Desired behavior

We should move to Step 2 of the registration process.

### Test code to reproduce
```js
  describe('Register a new user', () => {
    cy.visit('https://staging.talk.tv/');

    cy.get('[data-testid="SIGN_IN"]').click();
    cy.url().should('include', '/login?');
    
    cy.get('li').contains('Register').click();
    cy.get('.message').should('contain.text', 'Step 1');
    
    cy.get('input[name="firstName"]').should('be.empty').type('AutoFiststname');
    cy.get('input[name="lastName"]').should('be.empty').type('AutoLastname');
    cy.get('input[name="email"]')
      .should('be.empty')
      .type(`AutoEM${Math.random().toString().substr(2, 9)}@gmail.com`);
    cy.get('input[name="password"]').should('be.empty').type('Timespass1!');
    cy.get('#terms-input').check();
    cy.get('#no-thanks-checkbox').check();

    cy.get('button[name="submit"]').click();
  });
```
### Cypress Version

v11.1.0, v12.14.0 

### Node version

v16.13.2

### Operating System

macOS 12.5

### Debug Logs

```shell
I'd prefer not to share the logs publicly to protect company secrets.
```

**Comment by mschile** [comment]
Hi @waqas-khan-news 👋, thanks for taking the time to log this issue. Unfortunately, when running your test code to reproduce the issue, the test failed trying to locate the `SIGN_IN` element. Would you be able to recreate the steps you posted above in a reproduction repository by forking [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) or by other means?

![Image](https://github.com/cypress-io/cypress/assets/2002044/7b4781c2-be65-47a9-9219-4d707d597371)

As a side note, you can reduce a lot of the noise in the command log by disabling logs for xhr/fetch requests:
`cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })`

**Comment by waqas-khan-news** [comment]
Hi @mschile, thank you very much for taking a look at the issue. The problem you are experiencing is caused by the responsive design of our website; namely the screen width has been set to medium (or tablet), which hides the SIGN_IN button behind the burger menu. The quickest way to solve the issue would be to set `viewportWidth: 1440` in your cypress.config file. That way the SIGN_IN button will appear in the nav bar and the test should work.

**Comment by cacieprins** [comment]
Hi @waqas-khan-news , it looks like your sign in click redirects the browser to a different domain. The [cy.origin command](https://docs.cypress.io/api/commands/origin) should allow cypress to connect to your login form as expected.
