### ISSUE TITLE
Cypress hanging indefinitely if Browser closes

### ISSUE THREAD

**Issue by romanofski** [cypress-io/cypress#27000]
### Current behavior

We are currently investigating random stalls in our CI after upgrading from Cypress 10.4 to 12.14 (seems v10.11+ affected). The cypress process never exits stalling indefinitely until CI kills the agent. It always seems to happen after the last test ran.

Furthermore there seems to be a difference between running the tests against an instance hosted online (e.g. cloud instance) and locally.

If the tests run against the cloud instance and you simply close the browser (we use chrome) during a test session and after ffmpeg started, that the main cypress process never quits. I'm not sure whether this is intended behaviour?

The ffmpeg process then sits there I presume expecting input which will never arrive. I've had a look at open files of the process:

```
$ lsof -p 315472

COMMAND    PID   USER   FD      TYPE             DEVICE  SIZE/OFF    NODE NAME
ffmpeg  315472 user  cwd       DIR               8,48      4096 4269330 /home/user/e2e_tests
ffmpeg  315472 user  rtd       DIR               8,48      4096       2 /
ffmpeg  315472 user  txt       REG               8,48  68174760 4317847 /home/user/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@ffmpeg-installer/linux-x64/ffmpeg
ffmpeg  315472 user    0u     unix 0x0000000000000000       0t0 1491439 type=STREAM
ffmpeg  315472 user    1u     unix 0x0000000000000000       0t0 1491441 type=STREAM
ffmpeg  315472 user    2u     unix 0x0000000000000000       0t0 1491443 type=STREAM
ffmpeg  315472 user    3r      REG               8,48  10451040  945873 /home/user/.cache/Cypress/12.14.0/Cypress/icudtl.dat
ffmpeg  315472 user    4r      REG               8,48 119697912 4319100 /home/user/.cache/Cypress/12.14.0/Cypress/browser_v8_context_snapshot.bin
ffmpeg  315472 user    5u     unix 0x0000000000000000       0t0 1469970 type=SEQPACKET
ffmpeg  315472 user    6u     unix 0x0000000000000000       0t0 1469971 type=SEQPACKET
ffmpeg  315472 user    7r     FIFO               0,12       0t0 1469972 pipe
ffmpeg  315472 user    8w     FIFO               0,12       0t0 1469972 pipe
ffmpeg  315472 user    9u     unix 0x0000000000000000       0t0 1469973 @0007a type=SEQPACKET
ffmpeg  315472 user   10u     unix 0x0000000000000000       0t0 1469975 @0007b type=SEQPACKET
ffmpeg  315472 user   11w      REG               8,48    524336 1160212 /home/user/e2e_tests/src/videos/team/example.feature.mp4
ffmpeg  315472 user   12r     FIFO               0,12       0t0 1469978 pipe
ffmpeg  315472 user   13w     FIFO               0,12       0t0 1469978 pipe
ffmpeg  315472 user   31u  a_inode               0,13         0   18342 [eventpoll]
ffmpeg  315472 user   44u     unix 0x0000000000000000       0t0 1441646 type=STREAM
ffmpeg  315472 user   48u     unix 0x0000000000000000       0t0 1486525 type=STREAM
ffmpeg  315472 user   51r     FIFO               0,12       0t0 1469996 pipe
ffmpeg  315472 user   52w     FIFO               0,12       0t0 1469996 pipe
ffmpeg  315472 user   56r      REG               8,48    130050  945878 /home/user/.cache/Cypress/12.14.0/Cypress/chrome_100_percent.pak
ffmpeg  315472 user   57r      REG               8,48    181273  945866 /home/user/.cache/Cypress/12.14.0/Cypress/chrome_200_percent.pak
ffmpeg  315472 user   58r      REG               8,48    309156  945675 /home/user/.cache/Cypress/12.14.0/Cypress/locales/en-US.pak
ffmpeg  315472 user   59r      REG               8,48   5433396  945871 /home/user/.cache/Cypress/12.14.0/Cypress/resources.pak
ffmpeg  315472 user   60r  a_inode               0,13         0   18342 inotify
ffmpeg  315472 user   62u  netlink                          0t0 1498243 ROUTE
ffmpeg  315472 user   63u     unix 0x0000000000000000       0t0 1469997 type=STREAM
ffmpeg  315472 user   64r      REG               8,48    727600  945876 /home/user/.cache/Cypress/12.14.0/Cypress/v8_context_snapshot.bin
ffmpeg  315472 user   65u     unix 0x0000000000000000       0t0 1486519 type=STREAM
ffmpeg  315472 user   66u      REG               8,48         4 4261673 /tmp/.org.chromium.Chromium.lPZzsX (deleted)
ffmpeg  315472 user   67r      REG               8,48    131072 4261623 /tmp/.org.chromium.Chromium.UXRk1W (deleted)
ffmpeg  315472 user   74u     IPv4            1484579       0t0     TCP localhost:46073 (LISTEN)

```

If I then kill `ffmpeg` the main process exits too.

### Desired behavior

Cypress exits when the browser exits.

### Test code to reproduce

1. Use a longer running test (just so it's easier to close it "mid point")
2. Make sure the test runs against a remote webapp (e.g. cloud instance) - not a locally hosted app.
3. Start the test run (Preferably use `DEBUG=cypress:*` to gauge when the video recording is started)
4. Just close the browser with a click
5. See cypress and ffmpeg never exit

### Cypress Version

12.14.0

### Node version

v16.13.1

### Operating System

Ubuntu 20.04

### Debug Logs
I'd prefer not to share logs to do the possibility of leaking company secrets.

However what difference I did found between a run against a local instance and a remote instance is this (logs from a test run against a localhost hosted instance):

```shell

2023-06-12T01:06:35.218Z cypress:server:browsers:cri-client disconnected, attempting to reconnect... { closed: false }
2023-06-12T01:06:35.220Z cypress:server:request aborting { requestId: 'request436' }
2023-06-12T01:06:35.221Z cypress:server:request aborting { requestId: 'request426' }
2023-06-12T01:06:35.223Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33416 }
2023-06-12T01:06:35.223Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 41034 }
2023-06-12T01:06:35.224Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 33434 }
2023-06-12T01:06:35.227Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 53162 }
2023-06-12T01:06:35.227Z cypress:server:browsers:cri-client connecting { target: 'ACE12BE1F6EA5E61EF389E8846040DC7' }
2023-06-12T01:06:35.230Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 53168 }
2023-06-12T01:06:35.230Z cypress:server:cypress exiting with err Error: connect ECONNREFUSED 
2023-06-12T01:06:35.231Z cypress:server:cypress calling exit 1
2023-06-12T01:06:35.231Z cypress:server:cypress about to exit with code 1
2023-06-12T01:06:35.233Z cypress:server:browsers killing browser process
2023-06-12T01:06:35.233Z cypress:server:browsers:chrome closing remote interface client
2023-06-12T01:06:35.233Z cypress:server:browsers:chrome closing chrome
```

and remote:
```
2023-06-12T01:07:31.832Z cypress:launcher:browsers chrome exited: { code: 0, signal: null }
2023-06-12T01:07:31.833Z cypress:server:preprocessor removeFile /home/user/tests/src/integration/regression/team/example.feature
2023-06-12T01:07:31.833Z cypress:server:preprocessor base emitter plugin close event
2023-06-12T01:07:31.833Z cypress:server:preprocessor base emitter native close event
2023-06-12T01:07:31.833Z cypress:server:preprocessor base emitter native close event
2023-06-12T01:07:31.833Z cypress:server:browsers:chrome closing remote interface client
2023-06-12T01:07:31.834Z cypress:launcher:browsers chrome stderr: [0612/110731.833823:ERROR:nacl_helper_linux.cc(318)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
The automation client disconnected. Cannot continue running tests.
2023-06-12T01:07:41.376Z cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
[process group dump here]
```
```


### Other

_No response_

**Comment by mschile** [comment]
Hi @romanofski 👋, thanks for taking the time to log this issue. For your reproduction steps, are you running `cypress open` or `cypress run` in headed mode? I created a [test project](https://github.com/mschile/cypress-test-tiny/tree/issue-27000) that has a single spec to try and reproduce the issue. Could you checkout that project (branch `issue-27000`) and see if you can reproduce the issue. Does the issue go away if you disable [video](https://docs.cypress.io/guides/references/configuration#Videos) in the cypress config?

**Comment by romanofski** [comment]
@mschile thanks for looking into this. Much appreciated! You're raising good questions.

First off, I do use `cypress run`. So a typical command line looks like this: `yarn cypress run --specs [specs here] --browser chrome --headed`.

I've cloned the reproducer and can reproduce the issue. I used:

```
DEBUG=cypress:* yarn cypress run --browser chrome --headed
```

waited for the `cy.wait` then closed the Chrome browser. Interestingly, no difference if I disable video recording. The `ffmpeg` process doesn't show up anymore (expected), but cypress doesn't close. When debug is enabled I can see the profiler printing information still. I've used an `lsof` on the cypress process to see what open files there still are. Apart from - I presume - the typical IPv4 sockets open, the deleted files from Chrome appeared again I saw on the `ffmpeg` process.

```
Cypress 17664 rjoost   66u      REG               8,48         4 5676502 /tmp/.org.chromium.Chromium.LTUsWP (deleted)
Cypress 17664 rjoost   67r      REG               8,48    131072 4418432 /tmp/.org.chromium.Chromium.b2634T (deleted)
```

Perhaps this is nothing really. I guess just wonder what would usually initiate the shut down when running the client against a localhost hosted system under test.

**Comment by mschile** [comment]
@romanofski, I updated the [reproducer](https://github.com/mschile/cypress-test-tiny/tree/issue-27000) to also include a local server and the same behavior is observed (which is what I would've expected). I believe if you actually quit the browser instead of just closing the browser window that should terminate the Cypress process (at least that's what it does on my Mac).

**Comment by romanofski** [comment]
@mschile thank you for this update. I'm on leave for about 3 weeks and don't have access to my computer. Let me check and reply once I'm back. Thanks again!

**Comment by mschile** [comment]
@romanofski, I am going to go ahead and close the issue for now. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by romanofski** [comment]
@mschile sorry to ask since I don't understand what you mean by "closing" and "quitting" the browser. Process wise concerned closing the browser with the mouse, I suspect should be the same as a SIGTERM. The process should just naturally shut down without any problems. 

Are you saying that in that case it's normal that the Cypress control process is still running? The same is observed with an app running on localhost?

**Comment by romanofski** [comment]
@mike-plummer Would it be possible to clarify why this issue is closed again?

I like to understand whether this is normal that the main process doesn't exit if chrome was closed with a `SIGTERM` signal?
