### ISSUE TITLE
Cannot stub child component

### ISSUE THREAD

**Issue by dvkuenssberg** [cypress-io/cypress#27015]
### Current behavior

Hello,

I have issues with stubbing a child component in a test class. In order to stub the child component, I followed [this](https://angular.io/guide/testing-components-scenarios#stubbing-unneeded-components) guide and declared the stub in the `declarations` array. However this does not seem to work.

I would appreciate any help!

### Desired behavior

I want to be able to stub the child component using the `declarations` array.

### Test code to reproduce

This is the simplified setup:

Parent Component:

```typescript
@Component({
  selector: 'app-parent-component',
  template: '<app-button-component [url]="downloadUrl"></app-button-component>',
})
export class ParentComponent {
	// Implementation
	downloadUrl = '/a/path';
}
```
Child Component (DownloadStore is an implementation of NgRx Component Store):

```typescript
@Component({
  selector: 'app-button-component',
  template: '<button (click)="download()">Click me</button>',
  providers: [DownloadStore]
})
export class ButtonComponent {
	@Input()
	url: string = '';
	constructor(downloadStore: DownloadStore){}
	download(){
		this.downloadStore.download(url);
	}
}
```
Child Component Stub:
```typescript
@Component({
  selector: 'app-button-component',
  template: '',
})
export class ButtonStubComponent {
	@Input()
	url: string = '';
}
```

Parent Component Test:
```typescript
describe('Parent Component Test', () => {
	it('should mount', () => {
		// fails!
		cy.mount(ParentComponent,{
			declarations: [ButtonStubComponent],
		})
	})
})
```

Running this test will throw an error that it cannot find providers for the dependencies of `DownloadStore`, therefore it is still using the real `ButtonComponent` despite declaring the stub. Did I miss something or is this a bug?

I also tried to declare a mocked `DownloadStore` in the `providers` field of the stub like so:
```typescript
@Component({
  selector: 'app-button-component',
  template: '',
  providers: [{provide: DownloadStore, useValue: MockDownloadStore.store}]
})
export class ButtonStubComponent {
	@Input()
	url: string = '';
}
```
but to no avail.

Note: since `ButtonStubComponent` is in another module `TestModule` I also tried adding this to the `imports` array when mounting but the error also occurs.

I managed to workaround this problem by using the `TestBed.overrideComponent` API to explicitly declare a mocked `downloadStore` on the `ButtonComponent`, however I would prefer to use a stub instead to avoid dealing with dependencies of child components altogether.

### Cypress Version

12.14.0

### Node version

16.15.1

### Operating System

Windows

**Comment by dvkuenssberg** [comment]
I think I found the problem...I imported the module which contained the component that I want to test. I'm guessing the error originated from there. After excluding that module from the `imports` the stub is displayed as expected.

**Comment by tispBe** [comment]
I am using the TestBed to override the component imports in standalone components and created a custom cypress mount function to facilitate the usage of this. you can find more information about my implementation [here](https://software-engineering-corner.zuehlke.com/shallow-component-tests-in-cypress-with-angular-standalone-components). Hope this helps!
