### ISSUE TITLE
Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise

### ISSUE THREAD

**Issue by suhanagm09** [cypress-io/cypress#27012]
### Current behavior

  it("Deploy", () => {
    Cypress.on('fail', (error, runnable) => {

          console.log(error.message)
          cy.wrap(cy.enableGateway());
          throw error
    })
      cy.enableGateway()

      })

as per the functionality when error is thrown in cy.enableGateway() ,     
cy.wrap(cy.enableGateway()); should be executed again which is within Cypress.on()
![image](https://github.com/cypress-io/cypress/assets/136438948/f10ede89-99ab-431c-9124-510805a9e14f)

### Desired behavior

in the above code while  error is returned in cy.enableGateway() then commmands within Cypress.on() should be executed

### Test code to reproduce

Cypress.Commands.add("enableGateway", () => {

  cy.get(architectPage.devicedeploybuttons).should('be.visible');
  cy.get(architectPage.networkButton).click({ force: true });
  cy.contains('Enable Networking').should('be.visible').click({ force: true })  
 cy.get(architectPage.loader).should('be.visible');
  cy.waitForLoaderToDisappear()
  cy.wait('@authorizeGateway', { timeout: 5000 });
  cy.wait(5000)
  cy.get('div.device-deploy >div').eq(0).invoke('attr','class').should('contain','active');
});

### Cypress Version

Cypress package version: 9.7.0 Cypress binary version: 9.7.0 Electron version: 18.0.4 Bundled Node version: 16.13.2

### Node version

v16.15.0

### Operating System

WIndows 10

**Comment by nagash77** [comment]
Hi @suhanagm09 I see you are on an older version of Cypress.  Do you see the same behavior on the latest version of Cypress?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
