### ISSUE TITLE
Getting mTLS certificate error when trying to use PFX certificate

### ISSUE THREAD

**Issue by harikabuddaraju** [cypress-io/cypress#27027]
### Current behavior

We are doing API testing using pfx certificate and added it to the config file. When we are trying to send a post request getting "mTLS certificate is missing" error.

### Desired behavior

We expect to get some response instead of error.

### Test code to reproduce
```js
describe('API Testing ', function () {
  it('API - POST details', () => {
    
      cy.request({
          method: 'POST',
          url: '',
          header: { 
          ContentType: 'application/x-www-form-urlencoded',
          pfx: 'cypress/certs/OBWAC_AISP_PISP_CBPII_Transport.pfx',
          passphrase: ''
        },
          body: {
           
         
            },
       
        }).then((response) => {
          cy.log(JSON.stringify(response))
             
        })
  })
})  
```
### Cypress Version

12.14.0

### Node version

v18.14.0

### Operating System

windows 10

**Comment by mike-plummer** [comment]
Hi @harikabuddaraju , I'm sorry you're having trouble getting client certificates working. From your code example I suspect you're attempting to provide your certificate configuration in the wrong place. The [`cy.request`](https://docs.cypress.io/api/commands/request) command does not accept the `pfx` or `passphrase` fields (see the [list of accepted parameters here](https://docs.cypress.io/api/commands/request#Arguments)) - those need to be established in your `cypress.config.js` file. There is additional information (and a code example) [in our docs here](https://docs.cypress.io/guides/references/client-certificates).

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
