### ISSUE TITLE
Getting 401 unauthorized becuase client secret contains special character (asterisk)

### ISSUE THREAD

**Issue by marijana-rukavina** [cypress-io/cypress#27032]
### Current behavior

```Typescript
cy.request({
method: 'POST',
body: {
client_id: Cypress.env('id_oauth_clientid'),
client_secret: "secret*",
grant_type: Cypress.env('id_oauth_granttype'),
},
url: Cypress.env('baseurl') + Cypress.env('id_oauth_path'),
})
```  
When the request is made we get a 401 error and we can see that in the body client's secret is only secret without the asterisk *

### Desired behavior

I would like to have a way to deal with the special characters in the client secret for the API request

### Test code to reproduce

```Typescript
cy.request({
method: 'POST',
body: {
client_id: Cypress.env('id_oauth_clientid'),
client_secret: "secret*",
grant_type: Cypress.env('id_oauth_granttype'),
},
url: Cypress.env('baseurl') + Cypress.env('id_oauth_path'),
})
```  

### Cypress Version

12.7.0

### Node version

19.8.1

### Operating System

Mac OS 13.3

**Comment by mschile** [comment]
Hi @marijana-rukavina 👋, thanks for taking the time to log this issue. Unfortunately, I wasn't able to reproduce the issue. I created a [test project](https://github.com/mschile/cypress-test-tiny/tree/issue-27032) (branch `issue-27032`) that starts a server and echo backs the request body and the `*` was included in the payload. Would you be able to update the test project to demonstrate the issue you are seeing?

![Image](https://github.com/cypress-io/cypress/assets/2002044/1db69d74-b973-4e33-b12b-c6a6838f7904)

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
