### ISSUE TITLE
How To Resolve the Following issue DevTools listening on ws:// 

### ISSUE THREAD

**Issue by prabakaran-yorosis** [cypress-io/cypress#27031]
### Current behavior

Getting this warning start of every test cases DevTools listening on ws:// 

### Test code to reproduce

a

### Cypress Version

12.14.0

### Node version

node18.12.0-chrome107

### Operating System

"Debian GNU/Linux" : 11 (bullseye)

**Comment by nagash77** [comment]
@prabakaran-yorosis When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will consider reopening the issue.

If you have questions on using Cypress check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.
