### ISSUE TITLE
Cypress 12.14.0/Angular 16.0.4/playwright-webkit 1.35.0/Node 16.20.0 fails Webkit tests with "A network error occurred"

### ISSUE THREAD

**Issue by thekarlbrown** [cypress-io/cypress#27042]
### Current behavior

I have a set of Cypress tests that run perfectly on every Web Browser but Webkit. When I run on WebKit, I get the following error for every single test:

```
NetworkError: The following error originated from your application code, not from Cypress.

  >  A network error occurred.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
```

I have tried running via GUI and command line with similar results. I have tried running my tests locally and targeting a Dev URL.

I am on macOS 12.5.1
Cypress 12.14.0
Angular 16.0.4
playwright-webkit 1.35.0

### Desired behavior

I am hoping that the tests will succeed similar to all other browsers.

### Test code to reproduce

Here is my current cypress.config.ts:

```
// esbuild config
import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin. 
  return config;
}


export default defineConfig({
  e2e: {
    // enable Cypress Dashboard recordings.
    projectId: "CENSORED", 
    // run and record Cypress tests: 'npx cypress run --record --key <key>' This command will increase our recorded test run count, which can affect how much we're billed. Only use this command when necessary.
    //baseUrl: "http://localhost:4200",
    baseUrl: "CENSORED",
    defaultCommandTimeout: 20000,
    specPattern: "cypress/e2e/**/*.feature",
    env: {
      "TAGS": "not @web_skip and not @web_manual"
    },
    // supportFile: false,
    supportFile: "cypress/support/e2e.ts",
    setupNodeEvents,
    retries: {
      // Configure retry attempts for `cypress run`
      // Default is 0.
      "runMode": 3,
      // Configure retry attempts for `cypress open`
      // Default is 0
      "openMode": 3
    },
    experimentalWebKitSupport: true
  },
});
```

### Cypress Version

12.14.0

### Node version

16.20.0

### Operating System

macOS 12.5.1

**Comment by nagash77** [comment]
Hi @thekarlbrown , can you please provide a [reproducible example](https://github.com/cypress-io/cypress-test-tiny)?  Cypress engineers will not be able to effectively replicate your issue with the information provided thus far.

**Comment by thekarlbrown** [comment]
`import { Given, Then, When } from '@badeball/cypress-cucumber-preprocessor';
import { HomePage, BasePage } from '../pages';
import { context, ContextKeys } from '../../fixtures/feature-context';
import { users } from '../../fixtures/users.const';

const homePage = new HomePage();
const basePage = new BasePage();

Given(/I'm logged in as "(.*)" user/,(userType: string) => {
  let user;

  cy.visit('/');`

Even this most basic code fails

> Hi @thekarlbrown , can you please provide a [reproducible example](https://github.com/cypress-io/cypress-test-tiny)? Cypress engineers will not be able to effectively replicate your issue with the information provided thus far.

**Comment by thekarlbrown** [comment]
```import { Given, Then, When } from '@badeball/cypress-cucumber-preprocessor';
import { HomePage, BasePage } from '../pages';
import { context, ContextKeys } from '../../fixtures/feature-context';
import { users } from '../../fixtures/users.const';

const homePage = new HomePage();
const basePage = new BasePage();

Given(/I'm logged in as "(.*)" user/,(userType: string) => {
  let user;

  cy.visit('/');```



Even this most basic test fails

**Comment by mike-plummer** [comment]
@thekarlbrown Unfortunately it's difficult to attempt to reproduce your problem due to the multiple third-party plugins you're using. It is often hard to separate errors caused by plugins vs those coming from Cypress. Are you able to temporarily remove use of the esbuild preprocessor or try a vanilla Cypress test (no Cucumber preprocessor) to see if the same issue is encountered? If not we would ask you provide a reproducible example (ideally in the form of a `git` repo we can clone and run ourselves) or, failing that, [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) from a failing run so we can attempt to troubleshoot your issue.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by KyleVassella** [comment]
@thekarlbrown and @mike-plummer I believe the issue may be that Cypress' experimental support of Webkit depends on the Playwright Webkit Browser. From my brief research, it seems the Playwright Test Runner is incompatible with Cucumber. Even users of Playwright (not Cypress) who insist on using Cucumber must make the tradeoff of losing the benefits of the Playwright Test Runner and instead utilize a different test runner. Perhaps this Cucumber limitation also exists in the Playwright Webkit Browser?

If that's the case, as long as Cypress' solution to Webkit relies on Playwright solutions (or as long as Playwright solutions don't support Cucumber) it seems like Cucumber is not an option if Safari is needed, or vice versa. Tradeoffs all around.

@mike-plummer have you heard of anyone who has successfully utilized Cypress' experimental Webkit support while also running Cucumber?
