### ISSUE TITLE
Migration to Cypress 12 - error

### ISSUE THREAD

**Issue by Petra-N** [cypress-io/cypress#27056]
### Current behavior

Hello everyone, I'm trying to migrate from cypress 9 to cypress 12 but getting this Cypress configuration error. 

> Your /Users/......../GitHub/........../cypress/plugins/index.js file threw an error.
> 
> Please ensure your pluginsFile is valid and relaunch the migration tool to migrate to Cypress version 10.0.0.
> 
> [Stack trace](http://localhost:51848/__launchpad/index.html#)
> Error: spawn /Users/.............../Library/Caches/Cypress/12.14.0/Cypress.app/Contents/Frameworks/Cypress Helper.app/Contents/MacOS/Cypress Helper ENOENT
>     at Process.onexit (node:internal/child_process:283:19)
>     at onErrorNT (node:internal/child_process:478:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

First I was getting this error in terminal - code: 'ERR_REQUIRE_ESM', I've sorted it with updating the strip-ansi file in node-modules. I've tried clearing the Caches/Cypress, deleting node-modules and installing yarn and cypress again, with no success. I've tried all sort of things but nothing worked so far. Could you please help me how to sort out this error message and migrate to cypress 12?
Thanks

### Cypress Version

12.14.0

### Node version

14.21.3

### Package Manager

yarn

### Package Manager Version

1.22.19

### Operating system

Mac

### Operating System Version

Ventura 13.4

**Comment by nagash77** [comment]
Hi @Petra-N I have assigned this to one of our engineers to investigate but we are a bit backed up on tickets at the moment so it may be a while before someone can investigate.

In the meantime I would suggest you check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by Petra-N** [comment]
Thanks for the update, maybe a bit more info if needed, before deleting cache (in the Library folder) I'm getting this Cypress configuration error: 
Your /Users/…………../GitHub/........./cypress/plugins/index.js file threw an error.
Please ensure your pluginsFile is valid and relaunch the migration tool to migrate to Cypress version 10.0.0.

> ../../Library/Caches/Cypress/12.14.0/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/register.js:75:40
>   73 |         }
>   74 |         // tslint:disable-next-line:no-invalid-this
> > 75 |         return originalResolveFilename.apply(this, arguments);
>      |                                        ^
>   76 |     };
>   77 |     return function () {
>   78 |         // Return node's module loading to original state.
>   79 |         Module._resolveFilename = originalResolveFilename;

[Stack trace](http://localhost:62975/__launchpad/index.html#)
Error: Cannot find module 'file:///Users/.........../GitHub/............/cypress/plugins/index.js'
Require stack:
- /Users/…………/Library/Caches/Cypress/12.14.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js
- /Users/…………/Library/Caches/Cypress/12.14.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._resolveFilename (/Users/…………./Library/Caches/Cypress/12.14.0/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/…………GitHub/........../node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/……………./Library/Caches/Cypress/12.14.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:106:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

The path for the index.js file is correct, the pluginsFile is set in cypress.json like this: "pluginsFile": "cypress/plugins/index.js",
Thanks.

**Comment by ThibautMarechal** [comment]
Hi @Petra-N, could you share how you get away with the Error [ERR_REQUIRE_ESM]: require() of ES Module ? 
I'm also getting this error in multiple reposiotry ? 
I'm using the Cypress 12.5.1 (But I also get the error with the latest 12.17.1) & Node 18.16.1

```
error C:\Workspace\evs-react-form\node_modules\cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: C:\Workspace\evs-react-form\node_modules\cypress
Output:
C:\Workspace\evs-react-form\node_modules\string-width\index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Workspace\evs-react-form\node_modules\strip-ansi\index.js from C:\Workspace\evs-react-form\node_modules\string-width\index.js not supported.
Instead change the require of C:\Workspace\evs-react-form\node_modules\strip-ansi\index.js in C:\Workspace\evs-react-form\node_modules\string-width\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\string-width\index.js:2:19)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\cli-truncate\index.js:3:21)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\listr2\dist\renderer\default.renderer.js:4:21)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\listr2\dist\utils\renderer.js:4:28)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\listr2\dist\lib\task.js:11:20)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\listr2\dist\listr.js:7:16)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\listr2\dist\index.js:13:14)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\cypress\lib\tasks\install.js:10:5)
    at Object.<anonymous> (C:\Workspace\evs-react-form\node_modules\cypress\index.js:12:5) {
  code: 'ERR_REQUIRE_ESM'
  ```
  
It's not comming from cypress itself but from dependencies of it.

**Comment by ahayes91** [comment]
Came across a similar error today, and I _think_ it's because the `listr2` dependency in Cypress is a a few major versions behind (https://www.npmjs.com/package/listr2).
Adding a resolution for that in my package.json sorted it for me, but ideally, that should be bumped in Cypress instead 🤞 

```
  "resolutions": {
    "listr2": "6.6.1"
  },
```

Edit: the strip-ansi package was actually the one I had to pin, it might be causing issues with other modules (not just Cypress), but I haven't quite tracked that down yet. The error the second time for me came from `nx`:

```
  "resolutions": {
    "strip-ansi": "6.0.0"
  },
```
