### ISSUE TITLE
Debug filter DEBUG=cypress:server:util:process_profiler doesn't work for cypress 12.13.0  version

### ISSUE THREAD

**Issue by Razmik1991** [cypress-io/cypress#27053]
### Current behavior

The DEBUG=cypress:server*  option doesn't show any info(log), however the DEBUG=cypress:cli filter works properly.

### Desired behavior
```
The test is executing with pass result, but there is nor output for debug option. Here my output
│ Cypress:        12.13.0                                                                        │
  │ Browser:        Chrome 114 (headless)                                                          │
  │ Node Version:   v16.16.0 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (sequenced-tests.cy.js)                                                │
  │ Searched:       cypress/tests/basic/sequenced-tests.cy.js    


---------------------------------------------------
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     27 seconds                                                                       │
  │ Spec Ran:     sequenced-tests.cy.js   

--------------------------------------------------------
 ✔  All specs passed! 
```
### Test code to reproduce

`DEBUG=cypress:server:* cypress run --browser chrome  --spec=cypress/tests/basic/sequenced-tests.cy.js`
OR
`DEBUG=cypress:server:util:process_profiler cypress run --browser chrome  --spec=cypress/tests/basic/sequenced-tests.cy.js`

### Cypress Version

12.13.0

### Node version

v16.16.0

### Operating System

Linux, Ubuntu

### Other

Dear Cypress team could you please quickly respond to my question? Is the wrong working behavior(bug) caused to my cypress version? 

Thanks

**Comment by mschile** [comment]
Hi @Razmik1991 👋, unfortunately, I haven't been able to reproduce your issue. When running the following command (`DEBUG=cypress:server:* cypress run --browser chrome  --spec cypress/e2e/1-getting-started/todo.cy.js`) using Cypress 12.13.0 on my Mac I was able to see all of the appropriate debug logs.

![Image](https://github.com/cypress-io/cypress/assets/2002044/5a1666ff-4e77-46ba-be34-c937be343f2f)

For questions like this, I would suggest checking out our [community chat](https://discord.gg/cypress), it can be helpful for debugging and answering questions.

**Comment by mschile** [comment]
I am going to go ahead and close this issue. Please comment if there is new information to provide concerning the original issue and we can reopen.
