### ISSUE TITLE
Cucumber-Cypress: tests incorrectly show as failing when running via command line

### ISSUE THREAD

**Issue by ijaved** [cypress-io/cypress#27064]
### Current behavior

Using [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) with cypress to run cucumber test scenarios via command line. When there is an undefined scenario the command line shows the test as failing:
![image](https://github.com/cypress-io/cypress/assets/7203790/cffa2713-7209-4b99-bb0a-905b864819a7)
![image](https://github.com/cypress-io/cypress/assets/7203790/693e2330-3864-437b-9cff-66a85e35b1a0)
![image](https://github.com/cypress-io/cypress/assets/7203790/33d75936-d98c-4a6a-a748-c451cc1299a8)

If the after hook fails and the last test was passing it is shown as failing:
![image](https://github.com/cypress-io/cypress/assets/7203790/433e2d29-6297-4a7f-a2bf-099395c0e705)
![image](https://github.com/cypress-io/cypress/assets/7203790/8535a4fe-13ec-4c81-ae06-06d780812646)
![image](https://github.com/cypress-io/cypress/assets/7203790/15f75594-e089-423a-b52d-622263a3b426)

### Desired behavior

- Undefined tests should show as `Pending` when running tests via command line
- If the last test is passing and the After hook fails, then the last test should still show and be counted as `Passing` when running tests via command line

### Test code to reproduce

Run following examples from README in https://github.com/ijaved/cypress-cucumber-preprocessor-reporting-example
- Pass/undefined report
- Pass/After hook fail report

### Cypress Version

14.14.0

### Node version

18.16.0

### Operating System

Linux-Ubuntu 18.04 / Windows 11

**Comment by nagash77** [comment]
Hi @ijaved Cucumber-Cypress is not plugin that Cypress owns.  You will need to open an issue with the maintainer of the repo for the plugin you are using.
