### ISSUE TITLE
Contributing > Getting started `--run-project` fails with unknown option

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#27068]
### Current behavior

Executing an instruction according to the scheme provided in [CONTRIBUTING > Getting started](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started) which shows the following command:

```bash
yarn dev --run-project /project/folder --record --key <key>
```

results in the error message

"error: unknown option: --run-project"

### Desired behavior

[CONTRIBUTING > Getting started](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started) should provide working instructions for testing using Cypress in run / headless mode.

### Test code to reproduce

Clone https://github.com/cypress-io/cypress

```bash
cd cypress
yarn
```

Use a separate terminal window to clone https://github.com/cypress-io/cypress-example-kitchensink into the same directory as the [cypress](https://github.com/cypress-io/cypress) repo was cloned in to.

```bash
cd cypress-example-kitchensink
npm install
npm start
```

In the `cypress` terminal window

```bash
yarn dev --run-project ../cypress-example-kitchensink
```

Note message:

"error: unknown option: --run-project"

### Cypress Version

12.14.0

### Node version

16.16.0

### Operating System

Ubuntu 22.04

### Debug Logs

[run-project.log](https://github.com/cypress-io/cypress/files/11781209/run-project.log)

#### Replacement command

If instead of

```bash
yarn dev --run-project ../cypress-example-kitchensink
```

the following command is executed, then Cypress successfully runs the tests from [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) using the checked out branch from the [cypress-io/cypress](https://github.com/cypress-io/cypress) repo:

```bash
yarn cypress run --dev --project ../cypress-example-kitchensink
```

#### Comments

[CONTRIBUTING > Getting started](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started) says:

> If you want to bypass the CLI entirely, you can use the `yarn dev` task and pass arguments directly. For example, to headlessly run a project in a given folder, while trying to record to Cypress Cloud.
>
>```text
>yarn dev --run-project /project/folder --record --key <key>
>```

The replacement suggestion `yarn cypress run --dev --project ../cypress-example-kitchensink` does not use `yarn dev` so the suggestion is not a one-to-one replacement. I'm unsure what is needed here, so I have submitted this as an issue rather than a PR.

**Comment by lmiller1990** [comment]
PR: https://github.com/cypress-io/cypress/pull/27173

This should be fine for now -- main things to avoid is commands in the docs that simply don't work / outdated.

**Comment by mike-plummer** [comment]
@MikeMcC399 Really appreciate all the work and bug-hunting you've been doing! Sorry we've been a bit slow handling your stuff recently, lots of folks on vacation. Thanks for your patience!

**Comment by MikeMcC399** [comment]
@mike-plummer 

Thanks for the kind words! It's been fun and challenging so far and I understand if folks are out on vacation that you're not running at full power. (Anyway, it's good for them to get a break!)
