### ISSUE TITLE
Travamento do Cypress após utilizar "While" nos testes

### ISSUE THREAD

**Issue by Jeremias-Souza** [cypress-io/cypress#27073]
### Current behavior

Após acrescentar um While no meu código, e iniciar os testes através do Cypress Open, o mesmo quando chega na função trava e fecha a execução, tendo que inicializar novamente o Cypress novamente.

### Desired behavior

Que execute o código normalmente, sem causar quebras no Cypress.

### Test code to reproduce

    let assinature = 0;
    let confirmation = false;

    while(confirmation === false){
        cy.xpath("(//i[normalize-space()='autorenew'])[1]").click();
    }

    if(cy.xpath("(//button[normalize-space()='Assinado'])[1]").contains('Assinado').should('be.visible'))
    {
        assinature ++;
        confirmation = true;
    }

    while (assinature > 0 && assinature < 2){
        cy.xpath("//span[normalize-space()='Assinaturas']").click({force:true});
        cy.xpath("(//button[normalize-space()='Assinado'])[1]").contains('Assinado').should('be.visible');
    }

### Cypress Version

v11.0.1

### Node version

v9.5.1

### Operating System

macOs v13.3.1

**Comment by MikeMcC399** [comment]
@Jeremias-Souza 

See Cypress documentation

https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Avoid-loops

Also you might find the Cypress-BR Telegram channel https://t.me/cypress_br useful:

> Grupo BR para usuários e entusiastas do Cypress (cypress.io). https://telegra.ph/Regras-do-Canal-Cypress-BR-06-26
