### ISSUE TITLE
invoke() a function is calling the js function twice when follwed with .then() 

### ISSUE THREAD

**Issue by SurapuRamaKrishna** [cypress-io/cypress#27081]
### Current behavior

 i reference to this doc https://docs.cypress.io/api/commands/invoke#Function 
I have created a custom function with some return value and invoked it and capturing the returned value .then() in this case the function is called twice. where in case of using .should() then the function is called once.

### Desired behavior

The function call should be done once even when the invoke() id followed by .then() also. 

### Test code to reproduce

    it('invoked js function with then() to get return value', ()=> {
        cy.wrap({ fn: (args) => { function add() {
            console.log("performing JS function call with then()");
            return 'x';
        } return eval(args);}}).invoke('fn', 'add()').then((val) => {
            expect(val).to.eql('x')
        });					
    })

    it('invoked js function with out then', ()=> {
        cy.wrap({ fn: (args) => { function add() {
            console.log("performing JS function call with out then()");
            return "x";
        } return eval(args);}}).invoke('fn', 'add()').should('eq', 'x')				
    })
![invoke_fn](https://github.com/cypress-io/cypress/assets/41903517/b393b986-1851-4d2c-a569-4e221d5216c2)

### Cypress Version

12.14.0

### Node version

18.11.0

### Operating System

windows 10, Linux

**Comment by mike-plummer** [comment]
Hi @SurapuRamaKrishna , thanks for using Cypress! This is actually intended behavior:

From the [`cy.invoke` docs](https://docs.cypress.io/api/commands/invoke)
> If you chain further commands off of .invoke(), it will be called multiple times. If you only want the method to be called once, end your chain with .invoke() and start fresh with cy afterwards.

In your example `.then` is a command, causing the duplicate invocation, while `.should` is an assertion
