### ISSUE TITLE
Cypress hangs when attempting to launch Chrome

### ISSUE THREAD

**Issue by MelaAxel** [cypress-io/cypress#27091]
### Current behavior

Selecting Chrome (or Chrome Beta) from the launchpad looks to hang when clicking 'start e2e testing'

![image](https://github.com/cypress-io/cypress/assets/137118191/94c99227-510b-4436-8be9-f8274ef0d7a6)

### Desired behavior

Chrome should launch as expected

### Test code to reproduce

This is happening at the launchpad before the browser executes any testing code

### Cypress Version

12.14

### Node version

19.9.0

### Operating System

Windows 11 Pro 22621.1848

**Comment by MelaAxel** [comment]
Log file was too long to paste - attached here instead
[cypress_12.14.log](https://github.com/cypress-io/cypress/files/11805804/cypress_12.14.log)

**Comment by MikeMcC399** [comment]
@MelaAxel 

I'm seeing which looks like there may be something wrong with your baseUrl combining two different URLs as `https://urldefense.com/v3/__http://localhost:50506`
which may be a security measure, and perhaps this is affecting Cypress?

`cypress:server:windows creating electron window with options { url: 'https://urldefense.com/v3/__http://localhost:50506/__launchpad/index.html__;!!IqVVtZ4-Sw!7ddV9GHYNat2O08vOvhSeTkOfyN_nLceeDgM-vT2pRayY8R3jXS1RBDQpdmiUu1mFvSNp-qMBIxYJqx5n8O9SOBML7Y$ ', backgroundColor: 'white', width: 1552, height: 832, minWidth: 597, minHeight: 400, x: -8, y: -8, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, webPreferences: { contextIsolation: true, partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false }, frame: true, contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms`

One other point for your consideration is that Node.js `19` entered end-of-life a few days ago on June 1, 2023, so you might want to update that version at some point.

**Comment by MelaAxel** [comment]
Awesome! Thank you for the direction here @MikeMcC399! This is currently only happening on a contractor's machine and I can verify that I do not have any reference to 'https://urldefense.com/' when debugging on my machine.

I'll pass this along to have them review what may be blocking, redirecting, etc to urldefense.com and see if they can poke a hole in that security layer on their side to get this up and going.

Let's go ahead and close this out; in the event we have more questions, I'll add them for additional review.

**Comment by MelaAxel** [comment]
We were able to get the security policies resolved but unfortunately that didn't allow chrome to launch. Here is the new log file for additional review: 
[cypress.log](https://github.com/cypress-io/cypress/files/11840313/cypress.log)

**Comment by MikeMcC399** [comment]
@MelaAxel 

~~- Are you able to re-open this issue?~~ Edit: @mike-plummer handled this
- For the problematic contractor's machine, is it only Chrome which is causing an issue, or does it fail to start for Electron as well?
- Have you compared the log files from the failing machine with log files on a machine where it works?
- Can you explain why there is still a reference to `https://urldefense.com/v3/__http://localhost:12478` in the log files when you write "We were able to get the security policies resolved"?

```
'https://urldefense.com/v3/__http://localhost:12478__;!!IqVVtZ4-Sw!4z6c3fNTFrm0H0PO4QtYP-_WydlDQCVTTqu1lM8QNXy0SnlsKJY8j7dZKcKrv9HU8EZKR8DTe84qEKckGMmsiD67s2M$ ', browserUrl: 'https://urldefense.com/v3/__http://localhost:12478/__/__;!!IqVVtZ4-Sw!4z6c3fNTFrm0H0PO4QtYP-_WydlDQCVTTqu1lM8QNXy0SnlsKJY8j7dZKcKrv9HU8EZKR8DTe84qEKckGMms88YVop8$ ', reporterUrl: 'https://urldefense.com/v3/__http://localhost:12478/__cypress/reporter__;!!IqVVtZ4-Sw!4z6c3fNTFrm0H0PO4QtYP-_WydlDQCVTTqu1lM8QNXy0SnlsKJY8j7dZKcKrv9HU8EZKR8DTe84qEKckGMmsVZ0f1iI$ ', proxyServer: 'https://urldefense.com/v3/__http://localhost:12478__;!!IqVVtZ4-Sw!4z6c3fNTFrm0H0PO4QtYP-_WydlDQCVTTqu1lM8QNXy0SnlsKJY8j7dZKcKrv9HU8EZKR8DTe84qEKckGMmsiD67s2M$ ' } +56ms
  cypress:network:cors Parsed URL { port: '12478', protocol: 'http:', subdomain: null, domain: '', tld: 'localhost' } +58ms

```

**Comment by MelaAxel** [comment]
> * For the problematic contractor's machine, is it only Chrome which is causing an issue, or does it fail to start for Electron as well?

Only Chrome; he's using Electron as a stopgap


> * Have you compared the log files from the failing machine with log files on a machine where it works?

I started to, initially, but it became a bit overwhelming at that time - I'm very happy to do more of this next week


> * Can you explain why there is still a reference to `https://urldefense.com/v3/__http://localhost:12478` in the log files when you write "We were able to get the security policies resolved"?

That's a great question and I'm sorry I missed that in my rushed review of this log when it was sent to me - I'll loop back with our contractor and work with him early next week to make sure this is all cleared up before I next reply

**Comment by msesun** [comment]
I think I'm having a similar issue. Today, when trying to run Cypress, it hangs when using Chrome. I am using MacOS Monterray

Every time I run `npx cypress open` this screen pops up and creates unnecessary files in our directory (and doesn't detect existing config files that haven't been changed in 4 months):
<img width="1170" alt="Screen Shot 2023-06-28 at 17 13 03" src="https://github.com/cypress-io/cypress/assets/54280057/bf3597e3-b290-471d-ba8e-033e2695adc6">

I was using 11.2.0 for 4 months now and never had this issue. It just started today. I upgraded Cypress to 12.13.0 in case an old version was the issue, but it still occurs

After hitting Continue in the screenshot above, I am taken to this page that never finishes initializing:
<img width="1171" alt="Screen Shot 2023-06-28 at 17 15 47" src="https://github.com/cypress-io/cypress/assets/54280057/deafc41c-544a-4eeb-9afb-f82b3e037575">

When I restart Cypress, I get this and have to manually clean up the files again:
<img width="1129" alt="Screen Shot 2023-06-28 at 17 22 00" src="https://github.com/cypress-io/cypress/assets/54280057/0db02682-563c-491b-bee3-cbb7ccb7cdac">

I'm using Typescript so I shouldn't even need these .js files. Not sure why I'm getting prompted all of a sudden and what to do to fix this. Any ideas?

**Comment by MelaAxel** [comment]
After additional debugging, we were able to isolate the issue to the machine itself. Using the exact same config/setup on other hardware worked without issue... so we can close this out.

Thank you again for the help and direction here!

**Comment by MikeMcC399** [comment]
@msesun 

You describe a different problem. If you want your problem followed up you should open your own separate issue.
