### ISSUE TITLE
Go to Setting page after enabling notifications

### ISSUE THREAD

**Issue by warrensplayer** [cypress-io/cypress#27090]
**Current behavior**
After enabling in-app notifications with the banner at the top of the page, the user will see a success notification and the banner will close.  The user will remain on the page where they are.

![image.png](https://images.zenhubusercontent.com/5e25f9721016beda9c509196/96d021e1-1f8a-404b-aeec-899a367d92cf)

**Expected behavior**
After enabling in-app notifications with the banner, the user will be taken to the "Desktop notifications" section of the the Settings page so that they can update the settings and be aware that they have this ability.

Potential solution: Pass a url parameter when routing to the page that will open and scroll the user to the correct part of the page.

Requirement: https://app.clickup.com/18033298/docs/h6amj-43107/h6amj-41927?block=block-c337b5f9-edce-429f-9795-415bf3dee92c

![image.png](https://images.zenhubusercontent.com/5e25f9721016beda9c509196/6ec00bf9-b47b-4cf8-91e9-9b79703c8ab9)

**Comment by warrensplayer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/27090?planning-poker) with Zenhub @astone123 @dkasper-was-taken @jordanpowell88 @lmiller1990 @marktnoonan @mike-plummer

**Comment by lmiller1990** [comment]
We may have a pattern/code for this, take a look.
