### ISSUE TITLE
Snapshots not displaying due to InvalidCharacterError.

### ISSUE THREAD

**Issue by menden** [cypress-io/cypress#271]
![snapshot](https://files.gitter.im/cypress-io/cypress/F0rC/Screen-Shot-2016-10-19-at-1.31.46-PM.png)

![click-expcetion](https://cloud.githubusercontent.com/assets/1778812/19531118/7d6dde72-9604-11e6-84c3-5f605dc28bc0.png)

This was cause by the openning html tag `<html ">`
Error occured when hovering over or clicking on test steps.

**Comment by brian-mann** [comment]
Fixed in [`0.17.9`](https://github.com/cypress-io/cypress/wiki/Changelog#0179-10132016).
