### ISSUE TITLE
Cypress failed to load due to socket hang up

### ISSUE THREAD

**Issue by Enigmaderockz** [cypress-io/cypress#27119]
### Current behavior

When I am trying to launch a website (which is company website so I can't mention it here), I am getting below error

We attempted to make an HTTP request to this URL but the request failed without a response. We received this error at network level > Error: socket hang up.

Here is the image of error:

![socket](https://github.com/cypress-io/cypress/assets/39618909/57279943-49b7-4303-8291-b477c4f21d33)

### Desired behavior

It should launch the website. 

### Test code to reproduce

That's my code to launch website.

![code](https://github.com/cypress-io/cypress/assets/39618909/6c61fb13-e24a-433f-bffa-e9f121c24012)

### Cypress Version

9.7.0

### Node version

12.20.1

### Operating System

Windows 10

### Debug Logs

```shell
[31628:0623/114018.790: ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is

/chrome-variations/seed?osname=win&channel-stable&milestone=114 304 541.634 ms - -

GET

GET // 200 1.286 ms --

GET /__cypress/runner/cypress_runner.css 200 1.404 ms --

POST

/ListAccounts?gpsia=1&source=ChromiumBrowser&json-standard 200 605.732 ms --

GET /__cypress/runner/cypress_runner.js 200 1.638 ms --

GET / cypress/runner/favicon.ico 200 1.334 ms --
```

**Comment by MikeMcC399** [comment]
@Enigmaderockz 

The information you provided isn't enough to find out the reason for your problem. Here are some hints to help you:

You may be able to check your company website using 

```bash
curl -I http://your-company-website
```

You could check both `http:` and `https:`.

If you enable debug logs you can get more information . See the https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs for this.

Your version of Cypress `9.7.0` is a legacy version.
Node.js `12.20.1` entered [end-of-life](https://github.com/nodejs/release#release-schedule) last year on Apr 30, 2022.

Although it will probably not resolve your issue, you should look to updating to current versions.

The active Cypress community is available on 

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)

where you can share your issues and ask for help.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by Enigmaderockz** [comment]
Sorry. I wasn't available. I am getting this error while launching Azure SDA website link. I am not getting this error with any other websites. can you guide me reg. this?

**Comment by MikeMcC399** [comment]
@Enigmaderockz 

Did you look at the previous suggestions in https://github.com/cypress-io/cypress/issues/27119#issuecomment-1604187297? Did they help you?

Note that Node.js `12.20.1` passed into [end-of-life](https://github.com/nodejs/release#release-schedule) on April 30, 2022.
Cypress `9.7.0` is a legacy version.

**Comment by nagash77** [comment]
@Enigmaderockz please try upgrading your Cypress to the latest and Node to >=16 and see if the problem still persists.

**Comment by aisyahhz163** [comment]
Got the same error of socket hang up, and the error is totally random, sometimes the test cases will pass, and sometimes it will show the socket hang up error. 
![Screenshot (23)](https://github.com/cypress-io/cypress/assets/96767417/1722c0ec-b8ed-499f-b359-9b5bf04094b7)

**Comment by notcold** [comment]
got the same error too, the page is totally fine, but tests in cypress run sometimes will happen, cy.visit got nothing cypress show socket hang up finally
