### ISSUE TITLE
Iframe package throwing unable to read location error.

### ISSUE THREAD

**Issue by arslan-zafar1** [cypress-io/cypress#27110]
### Current behavior

![cypress_err](https://github.com/cypress-io/cypress/assets/80097815/dddb11ec-9850-4c83-a8b9-5184e9704b89)

### Test code to reproduce

Load any iframe on web app.

### Cypress Version

12.12.0

### Node version

16.16.0

### Operating System

windows 10

**Comment by mike-plummer** [comment]
Hi @arslan-zafar1 , sorry that you're having trouble. It appears your issue is with the [cypress-iframe](https://gitlab.com/kgroat/cypress-iframe#readme) library which is maintained by a different group. You may want to reach out to them for help
