### ISSUE TITLE
Make presence of the cypress config optional

### ISSUE THREAD

**Issue by markelog** [cypress-io/cypress#2711]
For some projects config might be empty, but cypress nevertheless requires its presence. It seems it would makes to not require it

**Comment by jennifer-shehane** [comment]
You are referring to the presence of the `cypress.json` file?

**Comment by markelog** [comment]
I am :)

**Comment by jennifer-shehane** [comment]
This feature would roll into this issue: https://github.com/cypress-io/cypress/issues/1369

**Comment by markelog** [comment]
How this will be resolved with #1369? Are you going to implement it with provision of the new flag, or?

**Comment by markelog** [comment]
Awesome :)
