### ISSUE TITLE
system-test browser_crash_handling_spec does not behave as expected in chrome with video off

### ISSUE THREAD

**Issue by nizar787** [cypress-io/cypress#27126]
### Current behavior

with video off, the system-test browser_crash_handling_spec -> [when the browser process crashes in chrome](https://github.com/cypress-io/cypress/blob/develop/system-tests/test/browser_crash_handling_spec.js#L31) does not behave as expected and launches the chrome_process_crash.cy.js over and over again when it should move onto simple.cy.js

### Desired behavior

When the browser crashes, Cypress should move onto the next test

### Test code to reproduce

test code 

### Cypress Version

13

### Node version

16

### Operating System

win 11

**Comment by mike-plummer** [comment]
@nizar787 Where are you seeing this failure? System tests are meant to validate internal Cypress behaviors and seem to be working as expected in our CI environment. Your bug report references using version 13 which has not been released yet - was this a typo?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
