### ISSUE TITLE
Tests are not getting recorded

### ISSUE THREAD

**Issue by samyakshah** [cypress-io/cypress#2712]
I would like to record video of the test I run.
I have a test suite which used to record videos of every run. I was using 3.0.2 version and I upgraded to 3.1.0. I am still not able to capture videos of all the runs.

**Comment by jennifer-shehane** [comment]
Hey @samyakshah, we'll need a lot more information. How are you running your tests? Can you provide a reproducible example? Can you give versions of your OS? Filling out the questions asked in our [Issue template](https://github.com/cypress-io/cypress/issues/new?template=bug_report.md) weill help give us a good start in debugging your problem.

**Comment by samyakshah** [comment]
Jennifer,

Thanks for reaching out. It was my mistake, I wasn't running test by
executing "npm run cypress". Once I rectified it, I am able to get videos.
No further action needed.

Thanks
Samyak
