### ISSUE TITLE
cy.writeFile() doesn't work with new Cypress version 12.15.0

### ISSUE THREAD

**Issue by KristinaV-Spotos** [cypress-io/cypress#27131]
### Current behavior

<img width="240" alt="image" src="https://github.com/cypress-io/cypress/assets/105720314/5f415aff-e9ba-4765-8080-1114b6061fa6">

With the latest Cypress version 12.15.0 cy.writeFile() is broken when trying to write response contents to pdf. It says "cy.writeFile() must only be invoked from the spec file or support file."

Started happening after this got fixed: https://github.com/cypress-io/cypress/issues/27099

### Desired behavior

File written successfully/blank file written

### Test code to reproduce

 it('Download Pdf', () => {
          const pdfUrl = 'http://www.pdf995.com/samples/pdf.pdf';

          cy.request({ url: pdfUrl})
              .then((response) => {
                  const fileName = 'test';
                  const filePath = 'downloads/' + fileName + '.pdf';
                  cy.writeFile(filePath, response.body, 'binary');
      });

### Cypress Version

12.15.0

### Node version

v16.15.0

### Operating System

Windows

**Comment by bimanpathirage** [comment]
Hi @KristinaV-Spotos, were you able to find a workaround for this? I'm also facing the same issue with no luck

**Comment by Jacek-fstack** [comment]
Same issue for me!

**Comment by mike-plummer** [comment]
Hi @bimanpathirage @Jacek-fstack - there is some [more info available here](https://github.com/cypress-io/cypress/issues/27097#issuecomment-1611422688) with potential causes & solutions

**Comment by Jacek-fstack** [comment]
oh thanks @mike-plummer I'll check it out
FYI: this only occurs in headless mode for me
