### ISSUE TITLE
Out of memory when there have a lot of test cases such as 3000+

### ISSUE THREAD

**Issue by chengkun-kang** [cypress-io/cypress#27142]
### Test code to reproduce

Out of memory when there have a lot of test cases such as 3000+

### Cypress Mode

cypress run

### Cypress Version

12.15.0

### Browser Version

Electron 106 (headless) 

### Node version

14.18.1

### Operating System

linux (Debian - 11.6)

### Memory Debug Logs

```shell
<--- Last few GCs --->

[1615:0x3100003e4000]   203981 ms: Scavenge 265.6 (277.9) -> 264.8 (277.9) MB, 1.4 / 0.0 ms  (average mu = 0.928, current mu = 0.991) allocation failure; 
[1615:0x3100003e4000]   206257 ms: Scavenge 265.7 (277.9) -> 264.9 (277.9) MB, 1.4 / 0.0 ms  (average mu = 0.928, current mu = 0.991) allocation failure; 
[1615:0x3100003e4000]   210627 ms: Scavenge 265.7 (277.9) -> 264.9 (277.9) MB, 1.7 / 0.0 ms  (average mu = 0.928, current mu = 0.991) allocation failure; 


<--- JS stacktrace --->

[1615:0626/052523.642020:ERROR:v8_initializer.cc(730)] V8 process OOM (Oilpan: Reserving memory.).

We detected that the Chromium Renderer process just crashed.

This can happen for a number of different reasons.

If you're running lots of tests on a memory intense application.
  - Try increasing the CPU/memory on the machine you're running on.
  - Try enabling experimentalMemoryManagement in your config file.
  - Try lowering numTestsKeptInMemory in your config file during 'cypress open'.
```

### Other

3.7GB memory left in the sever

**Comment by chengkun-kang** [comment]
2023-06-26T06:01:04.168Z cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
`
┌─────────┬───────────────────┬──────────────┬──────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
│ (index) │       group       │ processCount │           pids           │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
├─────────┼───────────────────┼──────────────┼──────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
│    0    │     'cypress'     │      1       │          '4124'          │    0.32    │      1.82      │  476.18  │    436.75    │   483.96    │
│    1    │ 'electron-shared' │      4       │ '4164, 4351, 4165, 4412' │    0.02    │      1.2       │  180.09  │    160.35    │   181.11    │
│    2    │     'ffmpeg'      │      1       │          '4479'          │     0      │      1.25      │  119.36  │    99.86     │   119.36    │
│    3    │     'plugin'      │      1       │          '4400'          │     0      │      0.06      │  63.96   │    72.21     │   113.48    │
│    4    │      'other'      │      2       │       '5045, 5046'       │     0      │       0        │   2.13   │     2.13     │    2.13     │
│    5    │    'Electron'     │      1       │          '4464'          │    1.09    │      4.93      │    0     │   1436.18    │   2862.02   │
│    6    │      'TOTAL'      │      10      │           '-'            │    1.43    │      8.38      │  841.72  │   1977.73    │   3704.41   │
└─────────┴───────────────────┴──────────────┴──────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘
`

**Comment by mike-plummer** [comment]
Hi @chengkun-kang , sorry to hear you're having issues with memory. Cypress [12.4.0](https://docs.cypress.io/guides/references/changelog#12-4-0) introduced a new [`experimentalMemoryManagement` flag](https://docs.cypress.io/guides/references/experiments#Configuration) that can be enabled to more aggressively preserve memory in Chromium browsers. Can you try enabling that in your `cypress.config.js` file to see if there's any improvement?

**Comment by chengkun-kang** [comment]
> Hi @chengkun-kang , sorry to hear you're having issues with memory. Cypress [12.4.0](https://docs.cypress.io/guides/references/changelog#12-4-0) introduced a new [`experimentalMemoryManagement` flag](https://docs.cypress.io/guides/references/experiments#Configuration) that can be enabled to more aggressively preserve memory in Chromium browsers. Can you try enabling that in your `cypress.config.js` file to see if there's any improvement?

Hi @mike-plummer , 

I tried this flag as below:
`
numTestsKeptInMemory: 0, // default: 50, seems not work
`
`
experimentalMemoryManagement: true, // default: false
`

Environments:
```
NodeJS: v14.18.1
Cypress Version: 12.15.0 (stable)
System Platform: linux (Debian - 11.7)
System Memory: 33.7 GB free 2.41 GB
Chrome
  - Name: chrome
  - Channel: stable
  - Version: 114.0.5735.198
```

Below is the process_profiler log:
2023-06-27T15:22:24.140Z cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
```
│ (index) │ group │ processCount │ pids │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
│    0    │     'cypress'     │      1       │          '7784'          │    0.06    │      3.36      │  393.02  │    397.58    │   466.11    │
│    1    │     'ffmpeg'      │      1       │         '21459'          │   36.76    │      2.96      │  338.7   │    116.32    │    338.7    │
│    2    │ 'electron-shared' │      4       │ '7824, 8012, 7825, 8080' │     0      │       0        │  116.73  │    116.7     │   116.73    │
│    3    │     'plugin'      │      1       │          '8060'          │     0      │       0        │  65.66   │    65.72     │   114.46    │
│    4    │      'other'      │      2       │      '24478, 24479'      │     0      │       0        │   2.13   │     2.13     │    2.13     │
│    5    │      'TOTAL'      │      9       │           '-'            │   36.82    │     21.12      │  916.25  │    3061.8    │   5968.41   │
```

So much memory used in the server, we run same. tests(3000+) at local machine with `cypress open`, the process will only take 2.7GB memory(Activity Monitoring tool)

Any idea?

Thanks

**Comment by mike-plummer** [comment]
@chengkun-kang Have you taken a look at the free memory on the system this is being run on? From the logs you've posted I'll point out this line:

`System Memory: 33.7 GB free 2.41 GB`

If your tests take at least 2.7GB when run locally but there's only 2.4GB available on the system you may run into memory exhaustion issues

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
