### ISSUE TITLE
Custom Browser Launching -> Vivaldi

### ISSUE THREAD

**Issue by tester-at-bmi** [cypress-io/cypress#27145]
### Current behavior

When you open the cypress test runner with the browser Vivaldi the url opened is the URL of the application under test. 

It refuses to open `http://localhost:8080/__/#/specs` .

**Chromium based browsers**
1. Vivaldi browser
2. Blink browser (Same behavior as Vivaldi)

### Desired behavior

That it opens the correct url.

`http://localhost:8080/__/#/specs`

Instead of the url of the application under test.

### Test code to reproduce

```
setupNodeEvents(on, config) {
	config.browsers.push(
		{
			name: 'vivaldi',
			channel: 'stable',
			family: 'chromium',
			displayName: 'Vivaldi',
			version: '6.1.3035.100',
			path: 'C:\\Users\\USERNAME\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe',
			majorVersion: 6,
			isHeaded: true,
			isHeadless: false
		},
	);
	return config;
}
```

### Cypress Version

12.16.0

### Node version

16.14

### Operating System

Windows

### Other

I was checking an old configuration that i used in the past how to use custom browsers. These browsers all worked in the past.

Tested today (27-06-2023):
- Brave ✅ 
- Vivaldi 🔴 https://github.com/cypress-io/cypress/issues/27145
- Opera ✅  https://github.com/cypress-io/cypress/issues/27146
- SRWare Iron ✅ 
- Chromium ✅ 

2 Browsers fail with different type of issues.

**EDIT** For the Opera browser it was a mistake on my end so the only issue involves the Vivaldi browser.

**Comment by lmiller1990** [comment]
I reproduced it, I see

```
  cypress:server:browsers:browser-cri-client Attaching to target url about:blank +105ms
  cypress:server:browsers:browser-cri-client error finding browser target, maybe retrying { delay: 100, err: Error: Could not find url target in browser about:blank. Targets were [{"targetId":"292EA0594BF0F50F81667ECC7C23F311","type":"service_worker","title":"Service Worker chrome-extension://mpognobbkildjkofajifpdfhcoklimli/background-service-worker-4d942915b37819f13765afe65a261bee.js","url":"chrome-extension://mpognobbkildjkofajifpdfhcoklimli/background-service-worker-4d942915b37819f13765afe65a261bee.js","attached":false,"canAccessOpener":false,"browserContextId":"BF6B793D9488AEFDC484D7E323AFD788"},{"targetId":"425E84BBBD98FB1A6BF1D055FE81D86D","type":"background_page","title":"Cypress","url":"chrome-extension://caljajdfkjjjdehjdoimjkkakekklcck/_generated_background_page.html","attached":false,"canAccessOpener":false,"browserContextId":"BF6B793D9488AEFDC484D7E323AFD788"},{"targetId":"CBC38CDFCE32ECC119FC1AF6072E6CA2","type":"app","title":"Vivaldi","url":"chrome-extension://mpognobbkildjkofajifpdfhcoklimli/main.html","attached":false,"canAccessOpener":false,"browserContextId":"BF6B793D9488AEFDC484D7E323AFD788"}] at <embedded>:4613:316525 at async t (<embedded>:4613:315689) at async Object.open (<embedded>:4619:50360) at async Object.open (<embedded>:4619:26066) at async v.relaunchBrowser (<embedded>:4685:433130) at async Object.launchProject (<embedded>:4685:438487) at async g.launchProject (<embedded>:4383:59721) at async resolve (<embedded>:4389:62538) at async <embedded>:2609:936890 } +1ms
```

in the logs.

I do not know much about the Vivaldi browser, but it looks like we are unable to access the CDP. The error is somewhere around this function: https://github.com/cypress-io/cypress/blob/12823cd59771ebf40b095cc8c49063f5f4109adf/packages/server/lib/browsers/browser-cri-client.ts#L96-L115

I don't think we can prioritize this relative to our other issues (niche browser, not official supported) but if you want to take a poke around and see if you can figure it out, I can give some tips or review a PR. Most likely you need to find out what's preventing us from connecting to the remote interface.
