### ISSUE TITLE
Resurfacing of command 'must only be invoked from the spec file or support file.'

### ISSUE THREAD

**Issue by RobHannay** [cypress-io/cypress#27149]
### Current behavior

- Running `selectFile` with `action: 'drag-drop'` throws `Error:       CypressError: `cy.selectFile()` must only be invoked from the spec file or support file.` 

### Desired behavior

Fixture would be 'dropped' on the file input without erroring

### Test code to reproduce

https://github.com/RobHannay/cypress-test-tiny

```
  cy.get('input[type=file]')
    .first()
    .selectFile('cypress/fixtures/videos/Koala1.mp4', { force: true }, { action: 'drag-drop' });
```

### Cypress Version

12.16.0

### Node version

18.16

### Operating System

macOS 13.4.1

### Debug Logs

```shell
(Has some possibly sensitive info on our corporate codebase; can make available privately)
```

### Other

Continuation of #27099.

**Comment by chrisbreiding** [comment]
Sorry to see you're encountering this issue. Thanks for reporting it with a reproduction.

`cy.selectFile()` only takes one options argument, so this can be fixed by calling it like so:

```js
cy.get('input[type=file]')
    .first()
    .selectFile('cypress/fixtures/videos/Koala1.mp4', { force: true, action: 'drag-drop' });
```

Regardless, calling it with an extra argument should not trigger that error, so this is a bug that we'll look into fixing.

**Comment by elGatoMantocko** [comment]
Still able to reproduce https://github.com/cypress-io/cypress/issues/27099 via `cypress-localstorage-commands`.

https://github.com/cypress-io/cypress/issues/27099#issuecomment-1601573400

**Comment by RobHannay** [comment]
> Sorry to see you're encountering this issue. Thanks for reporting it with a reproduction.
> 
> `cy.selectFile()` only takes one options argument, so this can be fixed by calling it like so:
> 
> ```js
> cy.get('input[type=file]')
>     .first()
>     .selectFile('cypress/fixtures/videos/Koala1.mp4', { force: true, action: 'drag-drop' });
> ```
> 
> Regardless, calling it with an extra argument should not trigger that error, so this is a bug that we'll look into fixing.

Ah, of course!! 🤦 Thanks @chrisbreiding. Will leave this open as I guess a change in 12.15/12.16 has started causing this to error
