### ISSUE TITLE
While executing scripts in headless mode, I can hear the audio

### ISSUE THREAD

**Issue by Nikhil-OW** [cypress-io/cypress#27148]
### Current behavior

During the execution of my scripts in headless mode using the command `npx cypress run`, I noticed that one of my scripts automatically plays a video with audio, and I am able to hear the audio output.

I should not hear the audio

### Desired behavior

Since the audio output is not a standard feature in headless mode, we should not hear any audio during test execution

### Test code to reproduce

To reproduce the issue, create a test that visits a website containing a video. Upon launching the page, the video should play automatically, allowing us to test the audio. Unfortunately, I'm unable to provide a code snippet due to security concerns.

`e2e: {
    experimentalSessionAndOrigin : true,
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    specPattern: ["**/**/*.spec.js"],
    baseUrl: "",
    viewportWidth: 1920,
    viewportHeight: 1080,
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    screenshotOnRunFailure: true,
    projectId: "",
    defaultCommandTimeout: 30000,
    videoUploadOnPasses: false,
    video: false,
    chromeWebSecurity: false,
    modifyObstructiveCode: false,
    requestTimeout: 30000,`
    
    `env: {
      browserPermissions: {
        camera: "allow",
        microphone: "allow",
        notifications: "allow",
        javascript: "allow",
      },`

### Cypress Version

11.2.0

### Node version

18.14.1

### Operating System

Windows 10

**Comment by mike-plummer** [comment]
Hi @Nikhil-OW , thanks for reaching out. There has been some discussion previously around muting audio - here is an example of a [configuration you can apply in your Cypress config file](https://github.com/LibreLingo/LibreLingo/issues/753#issuecomment-1429562617) to disable audio if that is desired (assuming you're using a Chromium browser). Would this meet your needs?

**Comment by alexsch01** [comment]
```
on('before:browser:launch', (browser, launchOptions) => {
                if (browser.family == 'chromium') {
                    if (browser.name == 'electron')
                        launchOptions.preferences.webPreferences.autoplayPolicy = "user-gesture-required"
                    else
                        launchOptions.args.push('--mute-audio')
                    return launchOptions
                }
            });
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
