### ISSUE TITLE
Custom Browser Launching -> Opera

### ISSUE THREAD

**Issue by tester-at-bmi** [cypress-io/cypress#27146]
### Current behavior

When you run `npx cypress open` and select the custom browser opera.

The browser doesn't open and the following message is shown within the console.

```
DevTools listening on ws://127.0.0.1:59495/devtools/browser/276aedc2-a21a-4e34-8f51-eecabbc8fe16
spawn "C:\Users\USERNAME\AppData\Local\Programs\Opera\opera.exe" ENOENT
Error: spawn "C:\Users\USERNAME\AppData\Local\Programs\Opera\opera.exe" ENOENT
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Desired behavior

That it opens successfully Opera (Chromium based browser).

### Test code to reproduce

```
setupNodeEvents(on, config) {
	config.browsers.push(
		{
			name: 'opera',
			channel: 'stable',
			family: 'chromium',
			displayName: 'Opera',
			version: '100.0.4815.21',
			path: '"C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Opera\\opera.exe"',
			majorVersion: 100,
			isHeaded: true,
			isHeadless: false
		}
	);
}
```

### Cypress Version

12.16.0

### Node version

16.14

### Operating System

Windows

### Other

I was checking an old configuration that i used in the past how to use custom browsers. These browsers all worked in the past.

Tested today (27-06-2023):
- Brave ✅ 
- Vivaldi 🔴 https://github.com/cypress-io/cypress/issues/27145
- Opera 🔴 https://github.com/cypress-io/cypress/issues/27146
- SRWare Iron ✅ 
- Chromium ✅ 

2 Browsers fail with different type of issues.

**Comment by mike-plummer** [comment]
Hi @tester-at-bmi , sorry to hear you're having issues with custom browsers. The `ENOENT` error you're getting stands for "No Entry" which typically indicates a file cannot be found - either because it doesn't exist or because the user lacks sufficient permissions to see it. Can you double-check the filepath you specified for your Opera executable and ensure it has correct filesystem permissions? Is there a reason you're using double-quotes inside single-quotes for the `path` config value?

**Comment by tester-at-bmi** [comment]
@mike-plummer Now you're mentioning it i will double check that in a bit! 

I didn't notice it so could be a mistake on my end there. Will report back and see if that makes a difference.

About the filepath i'm pretty sure it's the correct one.

**Comment by tester-at-bmi** [comment]
@mike-plummer thanks that was a mistake on my end and will close this bug report for that. 🔥
