### ISSUE TITLE
cy.exec() doesn't work with new Cypress version 12.16.0

### ISSUE THREAD

**Issue by rashmiranjanbhoi** [cypress-io/cypress#27156]
### Current behavior

cy.exec() is not working in 12.16.0 version of cypress 
![image](https://github.com/cypress-io/cypress/assets/57247500/b499912f-ec90-4146-a4d9-72ea17d74dfe)

### Test code to reproduce

context('UI', () => {

     describe('testing', () => {
          it('testing', () => {
                    cy.exec('node index.js', {
                         failOnNonZeroExit: false
                    }, {
                         timeout: 20000
                    }).then(function (result) {
                         var stdout = result.stdout;
                         var stderr = result.stderr;
                         if (!stderr) {
                              cy.log('stdout: ', stdout);
                         } else {
                              throw stderr;
                         }
                    })
             
          });

     })
})

### Cypress Version

12.16.0

### Node version

v14.18.0

### Operating System

window 10

**Comment by mike-plummer** [comment]
@rashmiranjanbhoi It appears you are passing three parameters to `cy.exec` but it [only accepts two](https://docs.cypress.io/api/commands/exec#Syntax) - try combining your two options arguments:

```js
cy.exec('node index.js', {
  failOnNonZeroExit: false,
  timeout: 20000
}).then(function (result) {
```

This allows you test to pass. The error handling here is misleading and is being worked in #27149 - I'm going to close this as a duplicate

**Comment by rashmiranjanbhoi** [comment]
@mike-plummer but same code is working on lower version of cypress(v10.11)

**Comment by mike-plummer** [comment]
@rashmiranjanbhoi That's what I meant by this part of my comment:

> The error handling here is misleading and is being worked in https://github.com/cypress-io/cypress/issues/27149 - I'm going to close this as a duplicate

The code you referenced is invalid, but earlier versions of Cypress likely just ignored the extra parameter you sent

**Comment by rashmiranjanbhoi** [comment]
@mike-plummer  Could you suggest to me how to construct the following code so that it runs in the most recent Cypress version?

 cy.exec('node index.js', {
                     failOnNonZeroExit: false
                }, {
                     timeout: 20000
                }).then(function (result) {

**Comment by mike-plummer** [comment]
@rashmiranjanbhoi Please review my comment [above](https://github.com/cypress-io/cypress/issues/27156#issuecomment-1611367134) which contains a valid code example. You can only pass a single `options` argument, but you're passing two
