### ISSUE TITLE
Something creates fixtures/example.json repeatedly ...

### ISSUE THREAD

**Issue by mlc-mlapis** [cypress-io/cypress#2715]
I am trying to find out what / why creates `fixtures/example.json` file with the following content even if it's not the first run of `cypress open` or `cypress run` on a project.

```json
{
  "name": "Using fixtures to represent data",
  "email": "hello@cypress.io",
  "body": "Fixtures are a great way to mock data for responses to routes"
}
```

We removed the example tests (created on the first run of `cypress open`) from our repository (because of it's not necessary / misleading for the app) but `fixtures/example.json`  file is repeatedly created accidentally during following runs of `cypress`  on that project.

Can anybody explain why it happens? Is it a real bug? Or there are some reasons?

**Environment:**
Cypress 3.1.1
Windows 10
NodeJS 10.2.1

**Comment by mattbgold** [comment]
I had the same issue. A workaround is to explicitly set the fixturesFolder in cypress.json.
`"fixturesFolder": "cypress/fixtures"`

For some reason this prevents cypress from regenerating the example file.

**Comment by mlc-mlapis** [comment]
@mattbgold ... thanks for your advice. 😄  I set it ... and we'll see if it helps.

**Comment by jennifer-shehane** [comment]
This issue will be fixed at the introduction of `cypress init` outlined here: https://github.com/cypress-io/cypress/issues/619

Going to close since you've found a temporary workaround and would be covered with the linked issue.

**Comment by blamay** [comment]
This workaround didn't work for me and `cypress init` still hasn't been added.

**Comment by ianjamieson** [comment]
> I had the same issue. A workaround is to explicitly set the fixturesFolder in cypress.json.
"fixturesFolder": "cypress/fixtures"

Didn't work for me on Cypress `3.8.3

**Comment by smeijer** [comment]
Running Cypress `4.0.2`, and the issue still exists.

I've added a `.gitignore` to the `cypress` folder:

```
/fixtures/example.json
/screenshots
/videos
```

**Comment by AlphaHydrae** [comment]
Encountered the same issue with version`4.8.0`. The workaround in `cypress.json` did not work either.

**Comment by KiwiKilian** [comment]
Keeping the generated folders (not the generated files) with a `.gitkeep` seems to help.

**Comment by ptokarski** [comment]
I have the same issue. cypress v `^6.1.0`. The workaround in `cypress.json` sounds ugly and did not work either.

**Comment by ShadyTrilogy** [comment]
Same issue exists in `6.3.0`

**Comment by dpatz** [comment]
For anyone still trying to figure this out, there is now a [config option](https://docs.cypress.io/guides/references/configuration#Folders-Files) you can add to your `cypress.json`:

```
fixturesFolder: false
```

prevents the example fixtures from being generated.
