### ISSUE TITLE
Cypress fails to register MSW

### ISSUE THREAD

**Issue by dvtschachinger** [cypress-io/cypress#27162]
### Current behavior

Hi, with the changes of version 12.15, I'm facing the issue that cypress can't register msw anymore:

![Screenshot from 2023-06-29 10-05-09](https://github.com/cypress-io/cypress/assets/79898881/189a4d78-efdc-4f7f-a4ef-22bc098b9b1a)

I saw that there were changes in CSP. In the cypress.config.ts I already set the CSP allow list to `experimentalCspAllowList: true`, `experimentalCspAllowList: false` and tried different array combinations but in all cases I always got the error from above. When using 12.14 the tests run through perfectly fine. 

### Desired behavior

Cypress registers MSW

### Test code to reproduce

![Screenshot from 2023-06-29 10-05-09](https://github.com/cypress-io/cypress/assets/79898881/189a4d78-efdc-4f7f-a4ef-22bc098b9b1a)

### Cypress Version

12.16.0

### Node version

v 16.16.0

### Operating System

Ubuntu 22.04.2 LTS

**Comment by mike-plummer** [comment]
@dvtschachinger In order to assist you with your issue I would ask that you prepare a minimal reproduction case that we can use to troubleshoot. Unfortunately, I'm not intimately familiar with the `msw` library and the example projects in their repo I could use as a starting point are fairly out of date, which means I likely wouldn't be attempting to use the library the same way you are.

**Comment by mikekubn** [comment]
@mike-plummer 
Hi guys,
I can confirm the error mentioned above, we got same error on our project with cypress version `12.16.0` and `"msw": "^1.2.2"`.

The command - `"cy:e2e": "cypress run --e2e -b chrome"`, which run in terminal cause error:

```
Failed to register a ServiceWorker: The provided scriptURL ('http://localhost:3000/mockServiceWorker.js') violates the Content Security Policy.
```

<img width="1005" alt="image" src="https://github.com/cypress-io/cypress/assets/80623950/73770c91-f27a-4a93-a160-eedd0f2c1068">

When we use command `"cy:open": "cypress open --config-file ./cypress.config.ts -b chrome"` the tests run without error. I don't know why... . 

Our stack is last version nextjs, cypress and msw. 

In root layout we use simple condition for load msw, when is enabled. 

```
// Use api mocks for testing
if (process.env.NEXT_PUBLIC_API_MOCKING === "enabled") {
  require("../../__mocks__");
}
```

In e2e test we use before hook for load mocks.
```
describe("Foo testing", () => {
  beforeEach(() => {
    const { worker } = window.msw;
    worker.use(firstMock);
    worker.use(secondMock);
    worker.use(lastMock);
  });

.....
```

For mocking data we use little factories as:
```
export const firstMock = rest.get<
  null,
  Record<string, never>,
  Array<MockedTypes>
>(marketApiUrl + "endpoint", (_req, res, ctx) => {
  return res(
    ctx.json(
      getFirstMock({
        amount: 1,
      })
    )
  );
});
```

**Comment by lmiller1990** [comment]
Please post a minimal reproduction. You could use https://github.com/cypress-io/cypress-test-tiny/ to make it.

I understand this is a real issue. Unfortunately I don't have the bandwidth to scaffold our an app and piece together a setup with the hopes of reproducing it. If you can post a minimal reproduction with instructions on how to clone and run, I will reopen and help as best I can.

**Comment by oberhamsi** [comment]
the issue is really, that CSP can't be disabled. i can see that the runner HTML has CSP in the <head> and there is no way to change it or disable it.

i have the same issue when testing a videoplayer which sets data: urls on <video src>

**Comment by kubmir** [comment]
@mikekubn have you found any solution for this ? I have latest cypress and the same issue. I tried `chromeWebSecurity` and `experimentalCspAllowList` but it does not help.

**Comment by verydanny** [comment]
@dvtschachinger @oberhamsi @kubmir It seems that Cypress 12.17.3 fixes this for me, but I have other massive errors on 13.2.0. 

Funny enough, 12.17.4 is broken because of a missing dependency for me. It might have to do with my Yarn 3 setup though.

In summary, use Cypress@12.17.3
