### ISSUE TITLE
Interactive test runner randomly restarts tests

### ISSUE THREAD

**Issue by vpume** [cypress-io/cypress#27161]
### Current behavior

We are using the interactive test runner with Chrome. Since upgrading to a recent Cypress version (12.14.0), the currently executing test often suddenly restarts out of nowhere. Cypress does **not** close and re-open the Chrome window, as it happens when I change a cypress config file. Also, the `watchForFileChanges` flag is turned off.

### Desired behavior

The test should not restart itself randomly.

### Test code to reproduce

cannot provide a repo

### Cypress Version

12.14.0

### Node version

18.15.0

### Operating System

Windows 22H2 19045.3086

### Debug Logs

```shell
I get the error `There was an error creating your issue: body is too long, body is too long (maximum is 65536 characters).` when I paste the entire log here. Should I specifiy a specific DEBUG value to get a smaller debug log? If yes, which one?
```

**Comment by mike-plummer** [comment]
@vpume Sorry to hear you're having issues with Cypress. In order to help you I will need some more information:
1. Are you seeing this issue with e2e or component tests, or both?
2. You mentioned you starting seeing this after upgrading to v12.14.0 - what version did you upgrade *from* where this wasn't an issue?
3. You can save the debug logs to a text file and attach to a Github issue using drag-and-drop, or save as a gist and link the gist
4. When you say you cannot provide a reproduction is that because you haven't been able to reproduce the issue outside your project?
5. You said "we are using the interactive runner" - does that mean that multiple individuals are reproducing the same behavior on the same project with different machines? Or is this just happening for you?

**Comment by vpume** [comment]
Hi @mike-plummer 
1. we only use e2e tests
2. I just checked with the previous version, which was 12.5.1. The problem is also with this version. Maybe it also has to do with an OS or IDE update (we are using Rider). ~~It seems to me that if I close all open files in Rider, and then start the tests, the problem does not happen~~ (Update: It still happens). But the problem remains - it didn't exist until around 1 or 2 weeks ago. And I don't see any reason why Cypress should just restart the currently running test without any user invention.
3. Attached is the debug log
[cypress-debug-output.log](https://github.com/cypress-io/cypress/files/11947501/cypress-debug-output.log).
The restart in this case happened around 5 seconds after I started the test "winscribe-sync-add-users.cy.ts"
4. It doesn't seem to be reproducable using a simple project.
5. Yes, all team members have the same problem when using the interactive runner. It's not only me.

What I find suspicious in the debug log is that Cypress seems to watch winscribe-sync-add-users.cy.ts (it says `shouldwatch: true` in the log entry `2023-07-04T09:20:00.407Z`), altough the config flag `watchForFileChanges` is `false`. Why is that? My guess is that the IDE for some reason auto-saves the file because it thinks something changed (which according to the documentation can not be completely turned off), which might cause Cypress to restart the test.

**Comment by vpume** [comment]
@mike-plummer 
I also recorded a test session, where you can see that the test is restarted after a few seconds.
![Animation](https://github.com/cypress-io/cypress/assets/127740228/7109bec6-b7c4-483e-80f4-e45565b40e59)

**Comment by lmiller1990** [comment]
I cannot imagine what is causing this. Does this happen when you launch Cypress manually from the terminal, or only when you launch it from the Rider IDE?

**Comment by vpume** [comment]
It happens also if I launch Cypress manually from the terminal. It even happens when I close Rider altogether. I also turned off the Virus Scanner - but it still happens. Don't you see anything unusual in the debug log?

**Comment by lmiller1990** [comment]
> What I find suspicious in the debug log is that Cypress seems to watch winscribe-sync-add-users.cy.ts (it says shouldwatch: true in the log entry 2023-07-04T09:20:00.407Z), altough the config flag watchForFileChanges is false. 
> Why is that? My guess is that the IDE for some reason auto-saves the file because it thinks something changed (which according to the documentation can not be completely turned off), which might cause Cypress to restart the test.

Good debugging -- I wondered if we were not observing this flag correctly. I just tried it out - with `watchForFileChanges` set to `false`, it does not watch / re-run for me. I think the log is probably just showing the default, which is overwritten later on.

Which would support your initial theory, but then:

> It even happens when I close Rider altogether

Just to clarify - if you open the spec in another editor without any kind of auto-save, it *still* happens? Do you observe this in even a basic spec, or is project specific?

This is certainly a strange one. All your team is using similar tools? I wonder if it's project specific, or something to do with how your test is written. I'm guessing this did not always happen - do you know of a Cypress version that did not exhibit this behavior?

Any chance you could share the spec here? Or does it happen for all specs (in this case, is there something common, maybe in the support file?)

Sorry I haven't got a good answer or debugging strategy here -- happy to help out, just need to get something reproducible so we can narrow down the issue.

**Comment by vpume** [comment]
Hi Lachlan,
I found out that this only happens on tests which are visiting an external website.

It can be reproduced as follows:

```
context('Google test', () => {
  it(`Google test`, () => {
    cy.log('waiting for 3 seconds...');
    cy.wait(3000);
    cy.visit('https://www.google.com');
    cy.log('visited google');
  });
});
```

![google-test](https://github.com/cypress-io/cypress/assets/127740228/35a4ba84-bb55-4c3a-a335-d322895b3f64)

Now the question remains, what could be the problem here? These tests _need_ to navigate to the external website to create some data in a 3rd party app, which our app uses in the tests.

**Comment by lmiller1990** [comment]
Oh, I see. I don't think it's restarting. When the domain changes, the browser will refresh, as you are seeing. If you then click "re-run", it won't - it only does that flash when you change domain. It keeps your test state between refreshes, though, so it should not be a problem.

You can avoid this refresh, though. How about setting `baseUrl` in your `cypress.config`? First line in the [table here](https://docs.cypress.io/guides/references/configuration#e2e).

```js
// cypress.config.js

const { defineConfig } = require('cypress')

module.exports = defineConfig({
  e2e: {
    baseUrl: 'http://localhost:1234',
  },
})
```

Then you just do `cy.visit("/foo")` and it goes to `http://localhost:1234'/foo`, for example.

If you need to change domains during a test (like halfway through), you'll need to use the [`cy.origin`](https://docs.cypress.io/api/commands/origin#docusaurus_skipToContent_fallback) command. It'll do the flash / refresh, but your test state is maintained, so it does not impact the actual execution or results.

Does this help?

**Comment by kadamagithub** [comment]
i also see this issue and it is extremely irritating and frustating. cypress runner keeps refreshing. some days it works and some days it just keeps refreshing.

**Comment by lmiller1990** [comment]
It will only "refresh" for a new domain. State is maintained, though, so it should not impact your tests. What is frustrating - have you got a bug due to this behavior?

**Comment by kadamagithub** [comment]
see attached video and you will see reason for frustation. cypress runner keeps refreshing without any change.

[video1666166782.zip](https://github.com/cypress-io/cypress/files/13978962/video1666166782.zip)

**Comment by kadamagithub** [comment]
and the same setup works fine on my colleague's machine.
