### ISSUE TITLE
Blank GUI

### ISSUE THREAD

**Issue by henriquedevelops** [cypress-io/cypress#27160]
### Current behavior

I decided to implement E2E tests on my Next.JS app. So I followed the instructions in their [documentation](https://nextjs.org/docs/pages/building-your-application/optimizing/testing):

1. I installed Cypress by running `npm install --save-dev cypress`
2. I updated the scripts on the package.json file and ran the command `npm run cypress`

This opens a blank window, as shown in the screenshot below:
![Screenshot from 2023-06-29 01-37-39](https://github.com/cypress-io/cypress/assets/47286998/d0e1fb77-8fa9-4f2c-a6a0-a3cbfcf0720d)

I did some research and I found [this issue](https://github.com/cypress-io/cypress/issues/7140), which is very similar, but with no solution.

I thought the issue may be due to the fact that I am using Linux Ubuntu, but then I found [this other issue](https://github.com/cypress-io/cypress/issues/9572) that is also very similar, but on Windows.

### Cypress Version

12.16.0

### Node version

v19.9.0

### Package Manager

npm

### Package Manager Version

9.7.1

### Operating system

Linux

### Operating System Version

22.04

**Comment by mike-plummer** [comment]
Hi @henriquebuzon , sorry to hear you're having trouble. By any chance did you review [this part of our docs](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) regarding extra dependencies required when running in Linux?

If you have installed those dependencies and still have this issue then I would ask that you collect [Debug Logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) from a launch attempt so I can try to troubleshoot your issue.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
