### ISSUE TITLE
cy.task not working with ArrayBuffer

### ISSUE THREAD

**Issue by theJ3H** [cypress-io/cypress#27163]
### Current behavior

When using a task with a ArrayBuffer as argument, I get the error message `cy.task() must only be invoked from the spec file or support file.` 

Using an array or a string as an argument works fine.

This is a problem when using cy.intercept and trying to send the `intercept.body.response` as an argument for a task, like validating the content of a intercepted pdf file.

This worked fine in Cypress 12.14.0

### Desired behavior

Cypress should also allow ArrayBuffer to be passed as an argument. Alternatively there should be an explaination+documentation why ArrayBuffer is no longer supported as an argument, as the current error message is misleading.

### Test code to reproduce

`spec.cy.js`

```
describe("Test for bug ", () => {
    it(`doesnt work`, () => {
        			
		const buffer = new ArrayBuffer(10);				
		cy.task("log", buffer)
		
    })
		
    it(`works`, () => {
        			
		const array = new Array(10);
		cy.task("log", array)
		
    })
	
});
```

`cypress.config.js`

```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.log(message)

          return null
        },
      })
    },
  },
})
```

### Cypress Version

12.16.0

### Node version

v18.12.1

### Operating System

Win11

### Other

Worked fine with older versions, the fix in 12.16.0 didn't help.

**Comment by chrisbreiding** [comment]
Thanks for the error report. I verified this is a bug and a fix should be out for it in the next release.
