### ISSUE TITLE
Cannot focus element inside content editable element

### ISSUE THREAD

**Issue by mitar** [cypress-io/cypress#2717]
### Current behavior:

If I try to `.get` a content editable `p` element, I cannot use `.focus()` to focus it, since calling `.focus` on a DOM element inside a contenteditable will not give focus nor set `document.activeElement`

### Desired behavior:

I should be able to focus content editable element to set cursor position to that element

### Versions

Cypress: 3.1.1
OS: Linux Ubuntu 18.04

**Comment by lilaconlee** [comment]
I'm able to focus and type into a content editable paragraph with the following:
```js
cy.get("p")
.focus()
.type("hello")
```

Do you have a code sample or any additional information that could help us debug?

**Comment by mitar** [comment]
So typing works, but focus does not. For example, if you check [this ProseMirror example](https://prosemirror.net/examples/collab/) if you focus on the content editable which is for example all text bold, you will see that the toolbar changes and detect that editor is focused and that content is bold. But if I do `.focus()` I do not get anything.

It does work if I create a selection manually:

```js
    cy.window().then((window) => {
      cy.get('.editor p').then(($el) => {
        const el = $el.get(0);
        const range = window.document.createRange();
        range.setStart(el, 0);
        range.setEnd(el, 0);

        const selection = window.getSelection();
        selection.removeAllRanges();
        selection.addRange(range);
     });
   });
```

**Comment by mitar** [comment]
I mean, focus on content edible is this. From the user perspective. If I click on content editable as an user, it makes a selection in the browser.

So is Cypress API mimicking the user or the events? I thought high level calls like `click`, `type` and `focus` are more about user, and only `trigger` is about events? If I want focus event, then I can call `trigger('focus')`, no? But I want focus behavior, so I call `focus`?

**Comment by Bkucera** [comment]
@mitar focus does not imply selection. for example, for text inputs, we have `.focus()` and we have `.select()`. Focus simply places the cursor in the input, while `.select` makes a selection on the existing text. 
	If you want to select arbitrary text inside a contenteditable, we do not yet offer such a fine-grained API, but are planning to. In the meantime, your current strategy is best practice

**Comment by Bkucera** [comment]
@mitar calling `.focus()` does in fact make a selection. 
![image](https://user-images.githubusercontent.com/14625260/48792405-2c8c4180-ecc2-11e8-83f2-91b11f3dba3d.png)

calling .focus() places the cursor at the very start of the contenteditable.

We do not cause a click side-effect because that would lead to a lot of confusion. 

We are actually changing this API in the next iteration:
-  Currently, if you ask to `.type()` without having the element in focus, we issue a click (moving the cursor to the end of the text input)
- In cypress-next, we will focus and move the cursor to the end without issuing a `click`
