### ISSUE TITLE
Skipped tests (it.skip(…)) aren't skipped when using @cypress/grep and grepOmitFiltered

### ISSUE THREAD

**Issue by symn** [cypress-io/cypress#27174]
### Current behavior

This relates to this issue: https://github.com/cypress-io/cypress-grep/issues/88
Tests that should be skipped, aren't skipped. All other tests in the spec file are skipped.

Cypress version: 12.14.0
"@cypress/grep": "^3.1.5"

### Desired behavior

Skip all tests and don't run skipped tests only.

### Test code to reproduce

use the config env variables, or via cli:
```
        grepTags: 'readOnly',
        grepOmitFiltered: true,
        grepFilterSpecs: true
```

add a spec file:

```
describe('grep test', () => {
  it('should not run', () => {
     cy.log("it doesn't run");
  });

  it.skip('should not run this skipped test', () => {
     cy.log('it runs a skipped test');
  });
});

```

### Cypress Version

12.1.0

### Node version

16.20.0

### Operating System

macOS 12.0.1 Monterey

**Comment by mike-plummer** [comment]
@symn I'm trying to reproduce the issue you describe and I've managed to see that tests defined with `it.skip` are not getting completely filtered out despite using `grepOmitFiltered` (still show up as "Pending" in the output), but I can't find a situation where a test with `it.skip` is actually executed. Based on your description, I presume you mean tests are being executed when you say "not skipped".

If you actually meant they are skipped, just not filtered from the output then we can update this issue accordingly and send it along to the team. If you are actually seeing tests execute that are defined with `it.skip` I would ask you put together reproducible example I can clone and run locally to help diagnose the problem.

**Comment by halilibrahimayhan** [comment]
yes i am facing this problem too. Do you have any suggestions for solution?

**Comment by lmiller1990** [comment]
Can you please post a minimal reproduction I can clone and run? I'll reopen this issue once we have that. There's too many issues for us to create a rerproduction, one by one.

Fork this repo and make a minimal reproduction: https://github.com/cypress-io/cypress-test-tiny/
