### ISSUE TITLE
Set video config to false by default

### ISSUE THREAD

**Issue by sindresorhus** [cypress-io/cypress#2718]
### Current behavior:

The first time I run Cypress, it spams my project with lots of directories and files I don't need nor want. Merely running Cypress should not produce anything. I wasted a lot of time searching the docs for ways to disable this behavior.

### Desired behavior:

Cypress should only produce these files if I explicitly ask for it. For example, `npm init cypress` or `cypress init`.

The `video` option should default to `false`. You should not assume people want this.

Cypress should not automatically scaffold stuff into `cypress/fixtures`, `cypress/plugins`, `cypress/support`. I could not find a way to disable this (which is very surprising), so I ended up forcing these directories to exist in Git so Cypress wouldn't do the scaffolding (`touch cypress/plugins/.keep`).

### Steps to reproduce:

Can be reproduced by just running `cypress run` in a project.

### Versions

Cypress 3.1.1

**Comment by konekoya** [comment]
Is this what you'd like to see? #619

**Comment by sindresorhus** [comment]
Yes, and also changing the default of the `video` option.

**Comment by jennifer-shehane** [comment]
Issue for `cypress init` to prevent scaffolding everything https://github.com/cypress-io/cypress/issues/619

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding the default for video config to false is not currently within our scope of feature work.

The `cypress init` work is something we intend to do and we have some team members working on improving the initial Cypress experience.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
