### ISSUE TITLE
Cypress is not able to execute tests in private window of Mozilla Firefox browser

### ISSUE THREAD

**Issue by anand-naik** [cypress-io/cypress#27188]
### Current behavior

**Issue** : Cypress is not able to execute tests in private window of Mozilla Firefox browser.

Cypress Version used: 12.16.0  
Mozilla Firefox version used: 114.0.2 (64 bit)  

**Below Cypress configuration is used:**
![image](https://github.com/cypress-io/cypress/assets/60295289/ac8deceb-56c3-44e9-93f6-0dc427febfbd)

Using above configuration, cypress launches firefox browser in private window but when the script execution starts, it gives below error:
![image](https://github.com/cypress-io/cypress/assets/60295289/d31a2fcd-41c0-47af-bc98-c4d8750e73ce)

### Desired behavior

Cypress should be able to execute tests in private window of Mozilla Firefox browser

### Test code to reproduce

Please refer github repo: https://github.com/anand-naik/firefox-private-window

### Cypress Version

12.16.0

### Node version

18.15.0

### Operating System

Windows 10 Home

**Comment by lmiller1990** [comment]
Cypress requires an extension to run in Firefox, and private windows launch without those. 

This is not something we will look to support. I'd recommend using a standard, non private Firefox browser. If you need a separate one or specific version for whatever reason, - you can customize the path as [documented here](https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers
