### ISSUE TITLE
"Cypress verify" does not return anything

### ISSUE THREAD

**Issue by luischre** [cypress-io/cypress#27198]
### Current behavior

I am trying to use cypress within kubernetes and am currently running into some issues trying to migrate from version 9.2.1 to 12.13.0.

Just for giving some background context (**This is not the failure for which I am filing this issue**): the failure I am encountering is related to the cypress verify step or more specifically:

> Cypress failed to start.
> 
> This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
> 
> Please refer to the error below for more details.
> 
> ----------
> 
> Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=334
> 
> ----------

What I am currently doing is trying to narrow down the issue, what I did so far:

1. Disabled everything test related, purely started a kubernetes pod with the docker image (Used the cypress/factory image to create the docker image). Accessed the pod and executed `cypress verify`. First three times hit the above shown error and then nothing, it just returns not printing anything.
2. Removed kubernetes out of the equation to narrow it down further, started my custom image with docker. Did not encounter the error above but directly nothing on `cypress verify`.
3. Got my custom image out of the equation and used the `cypress/included:12.13.0` image instead and yet again nothing: `docker run -it --entrypoint=cypress cypress/included:12.13.0 verify`
4. Executing it with DEBUG=cypress:* did the trick, it seems it's indeed successful but would expect that information also without DEBUG

### Desired behavior

Some information about what is going on. I am currently really unsure whether nothing means success or not. Executing the same on a windows machine returns the expected output that is also mentioned within the documentation: https://docs.cypress.io/guides/guides/command-line#cypress-verify

From what can be seen with DEBUG it is indeed equivalent with success but as said would expect the success message also without DEBUG enabled.

### Test code to reproduce

docker run -it --entrypoint=cypress cypress/included:12.13.0 verify

### Cypress Version

12.13.0

### Node version

18.16.0

### Operating System

Linux 3.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)

**Comment by MikeMcC399** [comment]
@luischre 

`cypress verify` succeeds silently when running in a CI environment. This should probably be added to the documentation you mentioned 
https://docs.cypress.io/guides/guides/command-line#cypress-verify

- see also https://github.com/cypress-io/cypress/issues/26768 and the workflow https://github.com/MikeMcC399/cypress-verify/blob/main/.github/workflows/test-verify.yml which demonstrates `cypress verify` running successfully and failing in a GitHub CI environment.

Try also

```bash
npx cypress verify
export CI=1 npx cypress verify
```

shows:

```text
$ npx cypress verify

✔  Verified Cypress! C:\Users\mikem\AppData\Local\Cypress\Cache\12.16.0\Cypress

$ export CI=1 npx cypress verify
<no output>
```

**Comment by luischre** [comment]
@MikeMcC399

Thanks for the fast feedback and the explanation! I guess this issue can be closed then as it's kind of covered by the issue you linked anyways.
