### ISSUE TITLE
Iterations over list of items results in blank screen

### ISSUE THREAD

**Issue by jacco-juriblox** [cypress-io/cypress#27194]
### Test code to reproduce

My data (csv) object contains about 90 items, part of the functions that addresses this list during the creation of my test in Cypress Desktop (macOS, v 12.16.0)

```
...
        cy.fixture('privacyverklaring').then(function (testdata) {
            this.testdata = testdata
            })
...
        cy.get(this.testdata).each((item) => {
            cy.contains('New variable').click();
            cy.get("#variable").type(item.variable);
            cy.contains('Save').click();
            cy.log("next record");
            cy.clearLocalStorage()
            // jump to next row
        })
...
```

### Cypress Mode

cypress run

### Cypress Version

12.16.0

### Browser Version

Elektron 106

### Node version

Node.js v20.3.0

### Operating System

macOS 13.4

**Comment by nagash77** [comment]
Hi @jacco-juriblox can you describe your problem a bit more?  In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by jacco-juriblox** [comment]
Hi @nagash77 , this issue is not replicatable via the Cypress Test Tiny with a simple html form. The GUI crash must come from memory exhaustion or so, but I'm not sure how to even debug that from the macOS Cypress.app

**Comment by nagash77** [comment]
@jacco-juriblox perhaps you can describe the the data a bit more and the size of the csv.  I see you said there are roughly 90 rows int he csv, but are any of the fields unique in any way (big, weird data, etc)?

**Comment by jacco-juriblox** [comment]
The data being used is single column CSV with a variable name per row, which is being entered row for row in our staging version webapp, by means of a form that accepts the data and saves it. After +/- 50 iterations the complete app goes blank. See your email as example.
