### ISSUE TITLE
wrapTimer changes browser's setTimeout behaviour

### ISSUE THREAD

**Issue by karel1980** [cypress-io/cypress#2719]
### Current behavior:
I have an application which calls setTimeout(undefined, 0). (This itself is not very good, but just for now, consider that this does nothing in Chrome (no errors).

Link to the setTimeout(undefined, 0) call: https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design/issues/97

Before cypress 3.1.1 this did not cause any errors. Since 3.1.1 this causes tests to fail in wrapTimer -> invoke (it tries to call 'apply' on the undefined argument).

### Desired behavior:
Silently do nothing, just as a user's browser would do.

### Steps to reproduce:
Build an application which calls setTimeout(undefined, 0) & run a test with cypress 3.1.1.

### Versions
Cypress 3.1.1, reproduced on recent osx and ubuntu versions.
ps cypress 3.1.1 is available on npmjs.com, but not tagged on github? Is that intentional?

**Comment by chrisbreiding** [comment]
Yeah, I think we only handle a string or a function being passed in. We need to handle other types of values as well.

**Comment by brian-mann** [comment]
Released in [`3.1.2`](https://docs.cypress.io/guides/references/changelog.html#3-1-2).
