### ISSUE TITLE
Issue in Overwrite Customized command

### ISSUE THREAD

**Issue by RaoInam07** [cypress-io/cypress#27191]
### Current behavior
```js
// click on link by using a label
Cypress.Commands.add("clickLink",(label)=>{
    cy.get("a").contains(label).click()
})
// overwrite 
 Cypress.Commands.overwrite("contains", (originalFn, subject, filter, text, options = {}) => {
    if (typeof text == 'Object') {
        options = text
        text = filter
        filter = undefined
      }
  
      options.matchCase = false
    return originalFn(subject, filter, text, options);
  });
```
### Desired behavior

> Cannot overwite the contains query. Queries can only be overwritten with Cypress.Commands.overwriteQuery().

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.[Learn more](https://on.cypress.io/api/custom-queries)
[cypress/support/commands.js:38:18](https://demo.nopcommerce.com/__/#)
  36 | })
  37 | 
> 38 | Cypress.Commands.overwrite("contains", (originalFn, subject, filter, text, options = {}) => {
     |                  ^
  39 |   
  40 |     if (typeof text == 'Object') {
  41 |       options = text

### Test code to reproduce
```js
 describe('Custom Commands', () => {   
it.only("Custom command",()=>{
        cy.visit("https://demo.nopcommerce.com/")
    cy.clickLink("APPLE MACBOOK PRO 13-inch")
    cy.get("div[class='product-name'] h1").should("have.text", "Apple MacBook Pro 13-inch");
})
})
```
### Cypress Version

12.14.0

### Node version

16.16.0

### Operating System

Windows

**Comment by MikeMcC399** [comment]
@RaoInam07 

You seem to be trying to overwrite a query, which is not allowed. See the error message which you posted and the documentation

https://docs.cypress.io/api/cypress-api/custom-commands#Overwrite-Existing-Commands

The documentation section
https://docs.cypress.io/api/cypress-api/custom-queries#Overwriting-Existing-Queries

contains an example of how to overwrite `contains`
