### ISSUE TITLE
Node 18 | Unable to install Cypress 12

### ISSUE THREAD

**Issue by TellCVickers** [cypress-io/cypress#27213]
### Current behavior

When attempting to install Cypress 12 while running Node 18, I receive the following error message:

```
Installing Cypress (version: 12.16.0)


The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/12.16.0?platform=win32&arch=x64
Error: write EPROTO D4360000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:

----------

Platform: win32-x64 (10.0.19045)
Cypress Version: 12.16.0
```

Starting with Node 17 and 18, Legacy Renegotiation is no longer supported, which is what's causing this error message. If I revert to Node 16 and attempt to install, Cypress installs without any issues.

### Debug logs

```Text
Installing Cypress (version: 12.16.0)


The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/12.16.0?platform=win32&arch=x64
Error: write EPROTO D4360000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:

----------

Platform: win32-x64 (10.0.19045)
Cypress Version: 12.16.0
```

### Cypress Version

12.16.0

### Node version

18.15.0

### Package Manager

npm

### Package Manager Version

9.5.0

### Operating system

Windows

### Operating System Version

10.0.19045

**Comment by MikeMcC399** [comment]
@TellCVickers 

I checked on my own Windows system and it is connecting to https://download.cypress.io with TLS `1.3` on a `cloudflare` server.

It looks like you have OpenSSL installed. Do you have any restrictions about which network protocol(s) are allowed on your system?

**Comment by TellCVickers** [comment]
@MikeMcC399 good question; currently connecting via a corporate VPN, though I'm unsure if we have restrictions on network protocols.

**Comment by MikeMcC399** [comment]
@TellCVickers 

> good question; currently connecting via a corporate VPN, though I'm unsure if we have restrictions on network protocols.

If you Google on `error:0A000152:SSL` you may find some hints about problems that intermediate systems can cause.

**Comment by TellCVickers** [comment]
@MikeMcC399 I had taken a look at that error and the related articles, but wanted to check in here to confirm whether the Cypress team was able to replicate this. I was able to successfully install Cypress 12.17.0 on Node 18 outside of the network just now, so it sounds like this is most likely down to network config. I'll see what I can figure out on my end. Thanks!

**Comment by nagash77** [comment]
@TellCVickers we are not seeing the same error you are reporting internally at Cypress.  I am glad you are up and running now though!  I am going to close this issue for the time being.  If you find future bugs feel free to comment back here or open a new issue and we will be happy to investigate.

If you have general questions I would also highly recommend you check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
