### ISSUE TITLE
I can't delete an image from Cypress

### ISSUE THREAD

**Issue by MiouMiou-afk** [cypress-io/cypress#27219]
### Current behavior

Hello, for an e2e test, I have to upload an image and then delete it. The upload works fine but cypress does not see the trash to delete the image. I tried .trigger(), .invoke() or cy.wrap() as written on the documentation but it doesn't work.

my (handelbars)

<div class="imgcontainer">
                                                    <div class="hoverbox">
                                                        <img class="rounded w-100" src="/_programs/{{../program_data.program}}/thumbs/m/{{fn}}">
                                                    </div>
                                                    <button class="btn btn-trash" type="button" data-toggle="modal" data-target="#deleteImg{{_id}}" data-e2e="delete-image"><i class="fas fa-trash" ></i></button>
                                                    <button class="btnn btn-check" type="button" data-toggle="modal" data-target="#selectImg{{_id}}"><i class="fas fa-check"></i></button>
                                                </div>

### Desired behavior

I would simply like to delete the image using the trash can that appears on mouse over

### Test code to reproduce

` 
//my view (handelbars)

<div class="imgcontainer">
                                                    <div class="hoverbox">
                                                        <img class="rounded w-100" src="/_programs/{{../program_data.program}}/thumbs/m/{{fn}}">
                                                    </div>
                                                    <button class="btn btn-trash" type="button" data-toggle="modal" data-target="#deleteImg{{_id}}" data-e2e="delete-image"><i class="fas fa-trash" ></i></button>
                                                    <button class="btnn btn-check" type="button" data-toggle="modal" data-target="#selectImg{{_id}}"><i class="fas fa-check"></i></button>
                                                </div>
                                                
                                                //My cypress test :
                                                it('i can delete a image', () => {
        cy.get('[data-e2e="program-search"]').click();
        cy.get('[data-e2e="admin-program"]').eq(1).click();
        cy.get('[data-e2e="delete-images"]').click({force:true});
        cy.get('.btn-danger').click();
        cy.get('[data-e2e="apply-changes"]').click();

    });
                                                `

### Cypress Version

v12.12.0

### Node version

16.13.2

### Operating System

Windows 11

**Comment by MiouMiou-afk** [comment]
my view (handelbars)

<div class="imgcontainer">
                                                    <div class="hoverbox">
                                                        <img class="rounded w-100" src="/_programs/{{../program_data.program}}/thumbs/m/{{fn}}">
                                                    </div>
                                                    <button class="btn btn-trash" type="button" data-toggle="modal" data-target="#deleteImg{{_id}}" data-e2e="delete-image"><i class="fas fa-trash" ></i></button>
                                                    <button class="btnn btn-check" type="button" data-toggle="modal" data-target="#selectImg{{_id}}"><i class="fas fa-check"></i></button>
                                                </div>

**Comment by MiouMiou-afk** [comment]
`
<div class="imgcontainer">
                                                    <div class="hoverbox">
                                                        <img class="rounded w-100" src="/_programs/{{../program_data.program}}/thumbs/m/{{fn}}">
                                                    </div>
                                                    <button class="btn btn-trash" type="button" data-toggle="modal" data-target="#deleteImg{{_id}}"><i class="fas fa-trash" data-e2e="delete-image"></i></button>
                                                    <button class="btnn btn-check" type="button" data-toggle="modal" data-target="#selectImg{{_id}}"><i class="fas fa-check"></i></button>
                                                </div>
`

**Comment by MiouMiou-afk** [comment]
<div class="imgcontainer">
                                                    <div class="hoverbox">
                                                        <img class="rounded w-100" src="/_programs/{{../program_data.program}}/thumbs/m/{{fn}}">
                                                    </div>
                                                    <button class="btn btn-trash" type="button" data-toggle="modal" data-target="#deleteImg{{_id}}"><i class="fas fa-trash" data-e2e="delete-image"></i></button>
                                                    <button class="btnn btn-check" type="button" data-toggle="modal" data-target="#selectImg{{_id}}"><i class="fas fa-check"></i></button>
                                                </div>

**Comment by nagash77** [comment]
Hi @MiouMiou-afk your images are not showing in the issue.  I just see broken links.  In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by MiouMiou-afk** [comment]
I'm sorry but I can't do it on Cypress test tiny. This is private software. I did not want to give you a link it is an src tag for the image and a delete button:
`<div class="imgcontainer">
                                                    <div class="hoverbox">
                                                        <img class="rounded w-100" src************     >
                                                    </div>
                                                    <button class="btn btn-trash" type="button" data-toggle="modal" data-target="#deleteImg{{_id}}" data-e2e="delete-image"><i class="fas fa-trash"></i></button>
                                                    <button class="btnn btn-check" type="button" data-toggle="modal" data-target="#selectImg{{_id}}"><i class="fas fa-check"></i></button>
                                                </div>`

**Comment by nagash77** [comment]
@MiouMiou-afk 

I am still not understanding what you are trying to accomplish.  You upload an image to your site via a form on a webpage correct?  And then you want to delete it?  You mention emptying the trash.  Do you mean the trash can on your windows OS?  Or do you mean there is an image of a trashcan on the page you want to click which would delete the image?  If you are having problems finding an element on the page we will not be able to help you without access to the page.

You can also try joining our Cypress Discord community which has many knowledgable users that may be able to help as well. [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)

**Comment by MiouMiou-afk** [comment]
sorry I am French, my English is not perfect. I meant to press a trash can image on my webpage. I manage to do it "manually" but on my e2e tests it doesn't work, I do have an attribute on my "delete" tag, I also added a {force:true} on the clik and followed all the recommendations of the doc but it does not work. I will try to go on discord

**Comment by nagash77** [comment]
Hi @MiouMiou-afk I think I am following what you are saying now.  Can you provide an [reproducible example](https://github.com/cypress-io/cypress-test-tiny) in a fork of this repo?  Without that, it will be very difficult if not impossible for our engineers to understand exactly what is going on and how to fix it.

**Comment by nagash77** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment back here with a reproducible example and we can revisit this issue.
