### ISSUE TITLE
Cypress v12.17.0 crashes when notifications are enabled

### ISSUE THREAD

**Issue by wlsf82** [cypress-io/cypress#27228]
### Current behavior

I've just upgraded Cypress to v12.17.0 on a sample project, to test the desktop notifications.

I've enabled all the possible notifications, and pushed the change with the upgrade.

When the run finished, the Cypress App crashed, closed automatically, and left me with the following error in the logs. Also, now, when I open the Cypress App, it automatically crashes with the same error.

```sh
o.includes is not a function
TypeError: o.includes is not a function
    at m.sendRunCompletedNotification (<embedded>:4344:95669)
    at m.maybeSendRunNotification (<embedded>:4344:94952)
    at D.x (<embedded>:4225:4181)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D.checkRelevantRuns (<embedded>:4225:2179)
    at async g.callback (<embedded>:4225:2495)
    at async g.p (<embedded>:4201:16922)
    at async Timeout._onTimeout (<embedded>:4201:17125)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-x64 (22.5.0)
Cypress Version: 12.17.0

 *  The terminal process "/bin/zsh '-c', 'npm run cy:open'" terminated with exit code: 1.
```

### Desired behavior

No crash should happen.

### Test code to reproduce

https://github.com/wlsf82/testes-e2e-com-cypress-tat-v2

### Cypress Version

12.17.0

### Node version

v18.15.0

### Operating System

macOS Ventura 13.4.1

**Comment by wlsf82** [comment]
Cc @emilyrohrbough.

**Comment by warrensplayer** [comment]
@wlsf82 Can you share your `state.json` file under `~/Library/Application Support/Cypress/cy/production/projects/__global__`?  That is where those notification preferences are stored.

Also, can you run Cypress and set the debug environment variable to `DEBUG=cypress:data-context:NotificationActions` and share those logs? 

Finally, you can also edit that file and change `desktopNotificationsEnabled` to `false` to disable the notifications and you should be able to open the Cypress app again without error while we look into this issue.

**Comment by warrensplayer** [comment]
@wlsf82 I was able to reproduce this error.  When enabling the notifications for the first time, it is possible that the `notifyWhenRunCompletes` value in the `state.json` file gets set as a boolean value when checked instead of an array of values that the code expects. Please share your `state.json` file that a mention above to confirm that is what is happening to you. 

_Temporary workaround_ 
If you change the `notifyWhenRunCompletes` value from a boolean to an empty array (`[]`), then you should be able open Cypress, go back to your settings page, and enable the individual statuses that you want for notifications.

I am working on a fix to correct this going forward and update any bad `state.json` entires as well.

**Comment by wlsf82** [comment]
Hi @warrensplayer, this is what my `state.json` looks like;

```
{
  "showedStudioModal": true,
  "preferredOpener": {
    "id": "code",
    "name": "Visual Studio Code",
    "openerId": "code",
    "isOther": false
  },
  "firstOpenedCypress": 1624573527459,
  "preferredEditorBinary": "code",
  "isSpecsListOpen": false,
  "autoScrollingEnabled": true,
  "browserX": 15,
  "browserY": 27,
  "isBrowserDevToolsOpen": false,
  "browserWidth": 1479,
  "browserHeight": 974,
  "majorVersionWelcomeDismissed": {
    "11": 1668085987610,
    "12": 1670352724766
  },
  "reporterWidth": 375,
  "appX": 15,
  "appY": 32,
  "desktopNotificationsEnabled": true,
  "notifyWhenRunStarts": true,
  "notifyWhenRunCompletes": true
}
```

For now, I've changed `desktopNotificationsEnabled` to `false` and `notifyWhenRunCompletes` to `[]`.

I'm looking forward to the patch release.

**Comment by wlsf82** [comment]
By the way, by changing `desktopNotificationsEnabled` to `true` and correctly configuring `notifyWhenRunCompletes` as an array, the notifications work great!
