### ISSUE TITLE
Slow starting cypress tests

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#27226]
### Discussed in https://github.com/cypress-io/cypress/discussions/26901

<div type='discussions-op-text'>

<sup>Originally posted by **RobbeCl** June  1, 2023</sup>
When running Cypress locally, everything runs blazingly fast, but in CI/CD the startup time takes around 4 minutes (consistently between chrome/firefox/electron headless). 

We are using the docker image [cypress/browsers:node18.12.0-chrome107](https://hub.docker.com/layers/cypress/browsers/node18.12.0-chrome107/images/sha256-50959d1166a52276536e5535d1671692b83c097921685fe6a17f020d0b0f6ccf?context=explore). We are also using a strong AWS machine (t3a.2xlarge) so processing should be a problem I think. Besides that we are using an [esbuild preprocessor](https://github.com/bahmutov/cypress-esbuild-preprocessor). 

Some logging info:
It hangs around 4 minutes and then prints "Run Starting" (with all the browser infromation + test suites). After it launches the browser (after 4 minutes) everyting runs fast and smooth. It just the startup-time which is slow. Behaviour is the same on e2e tests as component tests.

Could it be the esbuild preprocessing step which takes a long tome or is it something browser-related? </div>

**Comment by jrnail23** [comment]
@lmiller, I had a very similar issue, so let me start by asking, are you by chance using pnpm?
I am, and it turns out that the thing causing my Cypress startup to hang was Cypress checking git for the latest changes to my test files.
That check was taking 4 minutes, and it was because in CircleCI, I was caching my pnpm store in my project workspace without gitignoring it.  So when that git check was happening, it was inspecting LOTS more files than it thought it would need to.
After adding `.pnpm-store` to `.gitignore`, the startup delay was completely fixed.
My next step after that, FWIW, was to pull my `.pnpm-store` into the my project's parent dir, so `git` wouldn't try to track it at all.

**Comment by RobbeCl** [comment]
That was it!! Amazing thanks @jrnail23 . How did you found out that was the problem?

**Comment by jrnail23** [comment]
@RobbeCl mostly grinding through lots of verbose cypress logs (`DEBUG=cypress-verbose:*` and `DEBUG=cypress:*`).  I ran through the debug timings and among the innocuous `+32ms` and `+1s` values, a couple of `+4m` timings started showing up.
From the `+4m` entries I was able to rule out issues with Firefox loading, then I started seeing stuff involving git, and I dug into the Cypress source code.
Not gonna lie, that was a tough one to figure out though.  I had lots of other extraneous factors to rule out leading up to that point.

**Comment by AlexGuironnetRTE** [comment]
Hello! We're having a kind-of-similar problem with cypress open hanging for a while at startup (see https://github.com/cypress-io/cypress/issues/29171). 
We're not using pnpm so it's probably not related, but you [mentioned](https://github.com/cypress-io/cypress/discussions/26901#discussioncomment-6389779) that at some point the issue occurred on your colleague's computer and not on yours.
That's the case for our problem too. Have you been able to figure out what caused this difference by any chance?

**Comment by PaulACoroneos** [comment]
> @lmiller, I had a very similar issue, so let me start by asking, are you by chance using pnpm? I am, and it turns out that the thing causing my Cypress startup to hang was Cypress checking git for the latest changes to my test files. That check was taking 4 minutes, and it was because in CircleCI, I was caching my pnpm store in my project workspace without gitignoring it. So when that git check was happening, it was inspecting LOTS more files than it thought it would need to. After adding `.pnpm-store` to `.gitignore`, the startup delay was completely fixed. My next step after that, FWIW, was to pull my `.pnpm-store` into the my project's parent dir, so `git` wouldn't try to track it at all.

Thank you so much this helped my team immensely

**Comment by lmiller1990** [comment]
It sounds like this is not really something that can be fixed here. I am happy someone not only solved, at least for themselves, and shared it here!

I think we can close this. If you do have performance issues, you should definitely try these solutions, then make a new issue reproducing your own issue as best you can, and please include your setup, like package manager, OS, etc.

**Comment by supuwoerc** [comment]
> @lmiller, I had a very similar issue, so let me start by asking, are you by chance using pnpm?，我有一个非常相似的问题，所以让我首先问一下，你是否偶然使用了 pnpm？ I am, and it turns out that the thing causing my Cypress startup to hang was Cypress checking git for the latest changes to my test files.我是的，事实证明，导致我的 Cypress 启动挂起的原因是 Cypress 检查 git 以获取测试文件的最新更改。 That check was taking 4 minutes, and it was because in CircleCI, I was caching my pnpm store in my project workspace without gitignoring it. So when that git check was happening, it was inspecting LOTS more files than it thought it would need to.该检查花费了 4 分钟，这是因为在 CircleCI 中，我在项目工作区中缓存了我的 pnpm 存储，而没有 gitignoring 它。因此，当 git 检查发生时，它检查的文件比它想象的需要多得多。 After adding `.pnpm-store` to `.gitignore`, the startup delay was completely fixed.将`.pnpm-store`添加到`.gitignore`后，启动延迟完全修复。 My next step after that, FWIW, was to pull my `.pnpm-store` into the my project's parent dir, so `git` wouldn't try to track it at all.之后我的下一步，FWIW，是将我的`.pnpm-store`拉入我的项目的父目录中，这样`git`就不会尝试跟踪它了。

Thank you very much for your answer, I solved the problem!

**Comment by loedolff** [comment]
One more "Thank you!!!" for @jrnail23 !

I'm adding some details about my situation to hopefully help others find this solution.

We started seeing delays and timeout errors in Gitlab-CI after switching our project to `pnpm`.  The errors varied. Here are the errors from different jobs that failed:

```
We encountered an unexpected error communicating with our servers.
RequestError: Error: ETIMEDOUT
```

```
Timed out waiting for the browser to connect. Retrying...
There was an error reconnecting to the Chrome DevTools protocol. Please restart the browser.
```

```
Timed out waiting for the browser to connect. Retrying...
Runtime.enable will not run as browser CRI connection was reset
Error: Runtime.enable will not run as browser CRI connection was reset
    at c.send (<embedded>:2743:68055)
    at async Object.initializeCDP (<embedded>:2743:174919)
    at async Promise.all (index 3)
    at async Object.attachListeners (<embedded>:2749:55092)
    at async Object.open (<embedded>:2749:56956)
    at async Object.open (<embedded>:2749:30921)
    at async v.relaunchBrowser (<embedded>:2858:42658)
```

```
Timed out waiting for the browser to connect. Retrying...
Missing browserCriClient in attachListeners
Error: Missing browserCriClient in attachListeners
    at Object.attachListeners (<embedded>:2749:54774)
    at Object.open (<embedded>:2749:56967)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.open (<embedded>:2749:30921)
    at async v.relaunchBrowser (<embedded>:2858:42658)
```

```
Timed out waiting for the browser to connect. Retrying...
Still waiting to connect to Chrome, retrying in 1 second (attempt 18/62)
...
Still waiting to connect to Chrome, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.
This usually indicates there was a problem opening the Chrome browser.
```

```
Timed out waiting for the browser to connect. Retrying...
Runtime.addBinding will not run as browser CRI connection was reset
Error: Runtime.addBinding will not run as browser CRI connection was reset
    at c.send (<embedded>:2743:68055)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async p.init (<embedded>:2754:26957)
    at async c.attachCDPClient (<embedded>:2754:24691)
    at async Object.open (<embedded>:2749:56913)
    at async Object.open (<embedded>:2749:30921)
    at async v.relaunchBrowser (<embedded>:2858:42658)
```

The error always happened after a 4 1/2 to 5 minutes gap in the logs. For example, here's a ~4.5 minute gap in the gitlab-ci log output:

``` 
...                                                              
440 22:36:52  Running:  test.cy.ts
441 22:41:34 Timed out waiting for the browser to connect. Retrying...
442 22:41:35 Runtime.addBinding will not run as browser CRI connection was reset
443 22:41:35 Error: Runtime.addBinding will not run as browser CRI connection was reset
...
```

Our CI job would fail about half the time. The above errors were printed when the job failed.  The following errors were printed when the job succeeded. These errors also appeared after a 4.5 to 5 minute gap in the logs:

```
We encountered an unexpected error communicating with our servers.
RequestError: Error: socket hang up
We will retry 3 more times in 30 seconds...
```

```
Timed out waiting for the browser to connect. Retrying...
```

When we enabled debug logging in Cypress (using `DEBUG=cypress:*`) and saw this log entry directly after the ~5 minute gap in the logs:

```
cypress-verbose:data-context:sources:GitDataSource stdout [...]
```

(`[...]` contained commit details, which I redacted).

The above log entry was a hint that the delay had something to do with git.

FWIW, I also saw the following errors right before the time gap , but I don't believe it was indicative of the problem:

```
  cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:45737     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 45737 } } +153ms
```

The issue might be related to using `@cypress/grep` but I wasn't able to confirm it.

Anyway, adding `.pnpm-store` to `.gitignore` solved it!
