### ISSUE TITLE
Cypress crash after submitting in iframe

### ISSUE THREAD

**Issue by SimonGiraudMVMS** [cypress-io/cypress#27244]
### Current behavior

When I run a Cypress test that involves making a payment within an IFRAME, the Cypress window closes and the test does not complete.

### Desired behavior

When I run a Cypress test that involves making a payment within an IFRAME, the Cypress test works and I have results

### Test code to reproduce

```js
    cy.get('.__PrivateStripeElement > iframe').then(($iframe) => {

      const iframeContent = $iframe.contents();


      const cardNumberInput = iframeContent.find('[id="Field-numberInput"]');
      const expiryInput = iframeContent.find('[id="Field-expiryInput"]');
      const cvcInput = iframeContent.find('[id="Field-cvcInput"]');


      cy.get(cardNumberInput).type('4242424242424242');
      cy.get(expiryInput).type('1224');
      cy.get(cvcInput).type('123');


      cy.sleep(5000)

      cy.get(BUTTON_SUBMIT).click()
```

https://github.com/cypress-io/cypress/assets/97966610/04b01d97-014b-4062-9d06-7d1ff18153cd

### Cypress Version

v11.2.0

### Node version

6.9.0

### Operating System

macOS 12.6.1 

### Debug Logs

```shell
None
```

**Comment by nagash77** [comment]
Unfortunately at this time Cypress does not support testing within an iframe (see [this ticket](https://github.com/cypress-io/cypress/issues/136)).  

You might want to check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) to see if other folks in the community have found a way to accomplish what you are looking to do.

**Comment by SimonGiraudMVMS** [comment]
That's why the test is shut down ? 
Because I can type in my inputs

**Comment by nagash77** [comment]
Sorry @SimonGiraudMVMS I did not see that part of the issue.  Do you see the same behavior using the latest version of Cypress?  Can you run with debug logs on and see what error message is being printed there?

**Comment by nagash77** [comment]
Closing since user opened another bug with more information
