### ISSUE TITLE
Cannot spy on imported function

### ISSUE THREAD

**Issue by dvkuenssberg** [cypress-io/cypress#27250]
### Current behavior

Hello,

I am testing a service class which uses an imported function `http.ts` that I would like to spy on, however this does not seem to be possible.

I would appreciate any help!

### Desired behavior

I would like to spy on imported functions using Cypress Spies.

### Test code to reproduce

This is the function in a file called `http.ts`:
```typescript
export function handleError(error: HttpErrorResponse) {
// implementation
}
```
In the test, I would like to ensure that this function is called. However, I am not sure how to spy on it. I tried as follows:

```typescript
import * as http from 'path/to/http.ts';

describe('service test', () => {
    let service: HttpService;
    let httpMock: HttpTestingController;

    beforeEach(() => {
        TestBed.configureTestingModule({ imports: [HttpClientTestingModule] });
        service = TestBed.inject(HttpService);
        httpMock = TestBed.inject(HttpTestingController);
        cy.spy(http, 'handleError').as('errorSpy');
    });
});
```

but it gives me the following error: `Attempted to wrap undefined property handleError as function`.

When trying to stub the function, the real function is called and an assertion about it fails:
```typescript
// ...
    cy.stub(http, 'handleError').as('errorStub');
// ...

it ('should call stub function', () => {
    // service call that triggers the handleError function
    cy.get('@errorStub).should('have.been.called'); // fails, was never called
});
```
Is it possible to spy on/stub a standalone function like this using Cypress?

### Cypress Version

12.17.0

### Node version

16.15.1

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
Check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
