### ISSUE TITLE
Not responding in windows

### ISSUE THREAD

**Issue by SageZheng** [cypress-io/cypress#27275]
### Current behavior

The program will die after about 10 seconds, when I click E2E testing, and then do nothing. And there is no error reported, and CPU was occupied about 10% for Cypress. And all package is latest version.

### Test code to reproduce

No code here, even with a blank program

### Cypress Version

v16.17.0

### Node version

12.17.1

### Operating System

Windows 11 Pro 22H2

**Comment by SageZheng** [comment]
If it doesn't have any tests or it is just a new empty project, it will not end, but if I add any test( i.e. create new empty spec) the cypress will come to the not responding status within 10 seconds.

**Comment by MikeMcC399** [comment]
@SageZheng 

I tested the example repository https://github.com/cypress-io/cypress-example-kitchensink using your configuration, and everything worked as expected.

Perhaps you would also like to try this?

Clone https://github.com/cypress-io/cypress-example-kitchensink (or you can fork and clone it)

```bash
cd cypress-example-kitchensink
npm install
npm run local:open
```

**Comment by nagash77** [comment]
Hi @SageZheng , I'm interested if @MikeMcC399 suggestion worked for you?  I also want to make sure you aren't running WSL or WSL2 type environments correct?

Can you also try running Cypress with [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) turned on and see what it logs there?

**Comment by SageZheng** [comment]
Hi Mike,

Thanks for reaching out. I have use debug mode before, nothing special log here, the program will die with no reason no error in about 10 second, when I click E2E testing. And first 10 seconds works properly.

Best regrads,
Sage

**Comment by SageZheng** [comment]
I will do it now and record a video for you

**Comment by SageZheng** [comment]
Your example is good.

Here is my example:
https://drive.google.com/file/d/12fyzleUPe24Theyr0zjGuVfKTnHD9A7u/view?usp=sharing

**Comment by SageZheng** [comment]
Hi Mike,

It’s the video record for a empty example, If I add test

https://drive.google.com/file/d/12fyzleUPe24Theyr0zjGuVfKTnHD9A7u/view?usp=sharing

But anyway I can execute your example, and it works great in ubuntu, I guess it might have some issue to my environment, but I don’t want to reinstall my system.

**Comment by nagash77** [comment]
@SageZheng Can you share that `action.cy.js` file you are clicking on in the video?

**Comment by SageZheng** [comment]
Just a normal file and it can be executed in other environments, and even if it's a default blank file, the test runner will die.

**Comment by MikeMcC399** [comment]
@SageZheng 

> Your example is good.

Did I understand you correctly that the example https://github.com/cypress-io/cypress-example-kitchensink works for you?

In that case there would be two explanations for your problem:

1. There is a bug in Cypress
2. You have a configuration problem in your project

To troubleshoot further in both cases you would need to provide a reproducible example to allow your project to be run by somebody else. Note that the issue list is only intended for Cypress bugs, not for user issues which are not bugs. You may be able to get help from the Cypress technical community in Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

for problems with using Cypress which are not suspected to be Cypress bugs.

You can also troubleshoot on your own by comparing the working project https://github.com/cypress-io/cypress-example-kitchensink with your non-working project.

**Comment by SageZheng** [comment]
Thanks!

Cause all my example is unreproducible, all others can run these examples. And I change the configuration and test in “cypress-example-kitchensink” to mine , and it works. But I have no idea why my example didn’t work. I mean even I create a new blank project.

But, never mind, I just try to learn to use cypress and I can do it on other machine.

**Comment by MikeMcC399** [comment]
@SageZheng 

If I understood you correctly it doesn't sound like you think there is a bug in Cypress. You say that you are learning and can use another machine.

In that case I suggest to close this issue.

**Comment by SageZheng** [comment]
Thank you! It's a bug but doesn't require fixing.
