### ISSUE TITLE
Flaky test: Tests fail in azure devops pipeline

### ISSUE THREAD

**Issue by Abdul-abdulwahab** [cypress-io/cypress#27289]
### Link to Cypress Cloud or CircleCI failure

I have an uncaught error in the app and I was handled the error using below code in e2e.js file

Cypress.on('uncaught:exception', (err, runnable) => {
// returning false here prevents Cypress from
// failing the test

return false
})

Tests are running in test runner or headless mode no issues however when I run same tests in Azure devops pipeline nothing working. see below:

![image](https://github.com/cypress-io/cypress/assets/136711268/9701721a-a5b8-4fe0-bb82-73feef77a263)

### Link to failing test in GitHub

I have an uncaught error in the app and I was handled the error using below code in e2e.js file

Cypress.on('uncaught:exception', (err, runnable) => {
// returning false here prevents Cypress from
// failing the test

return false
})

Tests are running in test runner or headless mode no issues however when I run same tests in Azure devops pipeline nothing working. see below:
![image](https://github.com/cypress-io/cypress/assets/136711268/3412a044-7c7a-489e-a1ed-e13da0e3edda)

### Analysis

Tests are running in test runner or headless mode no issues however when I run same tests in Azure devops pipeline nothing working.

### Cypress Version

 12.16.0

**Comment by jennifer-shehane** [comment]
@Abdul-abdulwahab Please try updating to v13+ and using Test Replay in Cypress Cloud to see your run in CI vs local. It’s helpful for debugging flake like this and narrowing down what in your environment may have caused it. If you can narrow this down to a specific bug in Cypress, plz reopen an issue explaining the bug.
