### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by bhanuprakash026** [cypress-io/cypress#27280]
### Current behavior

https://test2.glams.com/cms/api/cms/getall?studio=GLAMSQ&project=GLAMSQ&entity=Models&from=0&size=1000

https://test2.glams.com/cms/api/cms/get?key=DynamicQueryEntity_c4d76642-8f2d-417d-939c-eb44c7ac0c46

These are the API's 

I wrote command line like this cy.get('.e-diagram.e-droppable').should('have.length', 1);
Above line of code is executing between above two API's, Below I am attaching my img

![image](https://github.com/cypress-io/cypress/assets/115440658/1c0b9d6b-04a2-4ee3-bd78-2c0c872dafb3)

### Desired behavior

I want to execute cy.get('.e-diagram.e-droppable').should('have.length', 1) this line of code after above 2 API's calls are done

### Test code to reproduce

/// <reference types="cypress"/>
import LoginPage from "../PageObjects/LoginPage"

describe("Test suites", () => {
    const loginApplication = new LoginPage()
    let data;
    before(() => {
        cy.fixture("testdata.json").then((testData) => {
            data = testData
        })    
    })
    beforeEach("Visit the application", () => {
        loginApplication.visit();
        cy.saveLocalStorage();
    })

    it('Should drag and drop DataModel', () => {
        cy.get('[data-uid="Database"] > .e-text-content > .e-icons', {timeout: 5000}).click();
        cy.get('[data-uid="ModelViews"] > .e-text-content > .e-icons').click();
        cy.get('li.e-list-item').contains('CyDepDataModelViewTest').click();
        // cy.wait(1000)
        const object = cy.get('.e-droppable.e-tooltip').should('have.length', 1)
        cy.log(object)
        cy.get('.list-group-item:last-child()')
            .trigger('mousedown', {button: 0}, {force: true})
            .trigger('mousemove', 320, -77, {force: true})
            object.should('have.length', 1).click()
            .trigger('mouseup', {force: true});
    })
})

### Cypress Version

12.17.1

### Node version

18.15.0

### Operating System

Windows

**Comment by nagash77** [comment]
Hi @bhanuprakash026 , Issues in the repo are reserved for bugs and feature requests.  Questions on using Cypress should be directed to Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
