### ISSUE TITLE
Your tests are loading... 

### ISSUE THREAD

**Issue by smarianglc** [cypress-io/cypress#27296]
### Current behavior

I'm currently having a problem that when I open the e2e test for the second time, it's just 'your tests area loading...'

### Desired behavior

You should run the tests

### Test code to reproduce

_cypress/e2e/comprar.cy.js_
```js
describe('ACESSANDO PÁGINA PRINCIPAL', () => {
    it('Compra com saldo', () => {
        cy.visit('/')
            .get('button')
            .contains('Como Parcticipar')

    });
});
```

_cypress.config,js_
```js
const { defineConfig } = require('cypress');
module.exports = defineConfig({
  reporter: 'cypress-mochawesome-reporter',
  e2e: {
    baseUrl:'',
    setupNodeEvents(on, config){
      require('cypress-mochawesome-reporter/plugin')(on);
}
},
});
```

### Cypress Version

12.17.1

### Node version

v9.5.1

### Operating System

Windows 11 Home Single Language

**Comment by SunithaShivananjaiah** [comment]
I was also facing test loading issue, installed cypress via command npm install cypress --save-dev and relaunched cypress test runner for java script e2e testing, it worked for me please check once

**Comment by smarianglc** [comment]
@SunithaShivananjaiah Thanks! I've done this many times and the problem still remains.
