### ISSUE TITLE
Unknown file extension ".ts"

### ISSUE THREAD

**Issue by Alessandroinfo** [cypress-io/cypress#27294]
### Current behavior

After the installation of Cypress when i open it i receive this error:

<img width="1198" alt="image" src="https://github.com/cypress-io/cypress/assets/6276276/46dd8b41-0ad0-46f1-b55b-51e2c6058639">

It's reproducible here https://github.com/Alessandroinfo/angular-boilerplate

After npm i try to open cypress with cypress open.

### Desired behavior

I expect that everything it's configured correctly and after cypress open i can configure test without problem.

### Test code to reproduce

https://github.com/Alessandroinfo/angular-boilerplate on master

### Cypress Version

12.6.0

### Node version

16.21.0

### Operating System

macOS Ventura 13

**Comment by nagash77** [comment]
@Alessandroinfo thank you for opening an issue and providing a repro repo!  I will forward this onto an engineer to investigate.

**Comment by lmiller1990** [comment]
Hey, there's no `cypress.config.ts` file in the project I can find. Did you forget to push a commit @Alessandroinfo? I see `cypress/cypress.json`, which is the older format (Cypress 9 and below).

**Comment by Alessandroinfo** [comment]
The file `cypress.config.ts` is created at the open of Cypress.  The error that is generated by `cypress open` has nothing to do with the missing configuration file but because it cannot manage the file with the .ts extension.

**Comment by lmiller1990** [comment]
I cannot see a `cypress.config` getting created. Here's what I see:


![image](https://github.com/cypress-io/cypress/assets/19196536/4c72d985-79aa-4c3f-85c6-6a448edb51cf)

**Comment by Alessandroinfo** [comment]
Hi @lmiller1990 i have updated the repo and added the config for cypress but still i have the same issue.

**Comment by lmiller1990** [comment]
I looked into it. It's hitting here:
https://github.com/cypress-io/cypress/blob/0336922c3a84af2ce6c65be9e889da47b279a1f0/packages/data-context/src/data/ProjectConfigIpc.ts#L296

and returning false - so it should be - you are not using ESM, but CommonJS. I'm unsure why this works as expected in our own repo, though. I wonder if you need a `ts-node` specific config.

**Comment by lmiller1990** [comment]
Some common issues that point to the issue here: https://typestrong.org/ts-node/docs/troubleshooting

The easiest solution if you just want it to work is changing your file to `.js` and using `require`, or `.mjs` and not using TypeScript.

**Comment by Alessandroinfo** [comment]
Hi @lmiller1990, I tried both methods but didn't work.


<img width="855" alt="image" src="https://github.com/cypress-io/cypress/assets/6276276/57dfd42d-c44f-48e8-ab92-77cc5534ba30">
<img width="855" alt="image" src="https://github.com/cypress-io/cypress/assets/6276276/78d5fffa-99cf-41fa-8ff4-d870118ec3a9">

**Comment by lmiller1990** [comment]
What is going on here! Weird.

![image](https://github.com/cypress-io/cypress/assets/19196536/7a3ab9a0-fc0b-43bf-80d0-66c5aab6f503)

**Comment by lmiller1990** [comment]
Oh, dependency issue. You have `cli-trunucate@3` in your `node_modules`, which is ESM only. Cypress needs the CJS compatible one, which is v2.

I tried `npm i cli-truncate@2 --force`, got

```
yarn run v1.22.19
$ /Users/lachlanmiller/code/dump/angular-boilerplate/node_modules/.bin/cypress open
/Users/lachlanmiller/code/dump/angular-boilerplate/node_modules/cypress/node_modules/commander/index.js:472
      throw new Error(`option '${option.name()}' clashes with existing property '${option.attributeName()}' on Command
      ^

Error: option 'version' clashes with existing property 'version' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name

Read more on https://git.io/JJc0W
    at Command._checkForOptionNameClash (/Users/lachlanmiller/code/dump/angular-boilerplate/node_modules/cypress/node_modules/commander/index.js:472:13)
    at Command._optionEx (/Users/lachlanmiller/code/dump/angular-boilerplate/node_modules/cypress/node_modules/commander/index.js:499:10)
    at Command.option (/Users/lachlanmiller/code/dump/angular-boilerplate/node_modules/cypress/node_modules/commander/index.js:622:17)
    at Object.init (/Users/lachlanmiller/code/dump/angular-boilerplate/node_modules/cypress/lib/cli.js:325:13)
    at Object.<anonymous> (/Users/lachlanmiller/code/dump/angular-boilerplate/node_modules/cypress/bin/cypress:3:23)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
New issue, but this might help you a bit. It's now a dependency issue.

**Comment by jennifer-shehane** [comment]
Is this resolved? @Alessandroinfo

**Comment by Alessandroinfo** [comment]
> Is this resolved? @Alessandroinfo

I couldn't test now.  But the last time it still gave the same problem.
