### ISSUE TITLE
WebKit browser blank page on Ubuntu

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#27292]
### Current behavior

The Cypress app opens with a blank window when started with
`npx cypress open --e2e --browser webkit`

`playwright-webkit@1.34`

`baseUrl` is undefined.

This is reproducible on Ubuntu 22.04.4. On Windows 11 with exactly the same project setup there is no problem.

Screenshot Ubuntu 22:
![webkit on ubuntu 22 04](https://github.com/cypress-io/cypress/assets/66998419/fd6ccd19-24eb-4a1b-9b38-4715ff37cacf)

or

![image](https://github.com/cypress-io/cypress/assets/66998419/51f61aca-9810-460b-8c5f-a067e093c8ce)

### Desired behavior

Show the regular contents in the Cypress app when Cypress is started with `npx cypress open --e2e --browser webkit`

For comparison, here is the WebKit browser window from Windows 11:

![webkit on windows 11](https://github.com/cypress-io/cypress/assets/66998419/b273e920-6b31-4bad-aa69-4b75d12c6634)

### Test code to reproduce

Source code: https://github.com/MikeMcC399/github-action/tree/webkit/examples/webkit

Execute locally:

```bash
npx playwright install-deps webkit
git clone --branch webkit https://github.com/MikeMcC399/github-action
cd github-action/examples/webkit
npm ci
npx cypress open --e2e --browser webkit
```

### Cypress Version

First reported on Cypress version `12.17.1`
Still reproducible on Cypress version `13.6.6`

### WebKit version

Still reproducible with WebKit v17 (`17.4`)
`playwright-webkit@1.41.2` (`latest`)

### Node version

`18.16.1` & `20.11.1`
The results may be slightly different on other Node.js versions, such as 18.17.1, where the left panel is displayed and the main panel, which would normally show specs by default, is empty. It has also been observed that the WebKit browser window opens with the Cypress logo in the middle and nothing else in the body of the WebKit browser window.

### Operating System

Ubuntu 22.04.4 LTS

### Debug Logs

F12 in the WebKit browser shows

> WebSocket connection to 'ws://localhost:38067/__socket-graphql' failed: The server did not accept the WebSocket 
(Note this is a different run compared to the screen shot above, so the port numbers don't tie up.)

### Related issues

- This issue looks very similar to https://github.com/cypress-io/cypress/issues/24767 logged for macOS
- https://github.com/cypress-io/cypress/issues/24175

### Other

- Refer to [WebKit (Experimental)](https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental) documentation which specifies using `playwright-webkit@1.34` currently corresponding to [playwright release v1.34.3](https://github.com/microsoft/playwright/releases/tag/v1.34.3) using WebKit `16.4`.

**Comment by nagash77** [comment]
Thanks for entering this ticket @MikeMcC399 .  I think you might be right about those other tickets being related.

@lmiller1990 opened [this PR](https://github.com/cypress-io/cypress-documentation/pull/5375/files) with a suggested workaround until we can address this issue.  If other folks are encountering this in the meantime please try the change suggested in the linked PR.

**Comment by MikeMcC399** [comment]
@nagash77 
 
> @lmiller1990 opened [this PR](https://github.com/cypress-io/cypress-documentation/pull/5375/files) with a suggested workaround until we can address this issue. If other folks are encountering this in the meantime please try the change suggested in the linked PR.

- I already applied the workaround of installing `playwright-webkit@1.34` according to PR #5375. (See my comment in the Other section above.) This is actually only a workaround for https://github.com/cypress-io/cypress/issues/27141. It does not solve the blank webkit window in Ubuntu unfortunately.

**Comment by MikeMcC399** [comment]
This should probably also be documented as a current restriction for Ubuntu in the

[Webkit (Experimental)](https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental)

documentation. Let's wait first for feedback from @lmiller1990 before taking any actions about the documentation.

**Comment by lmiller1990** [comment]
What about `npx cypress run`? The main thing webkit is used for is running tests on CI. I'm more concerned about that -- if it's purely for local development, it's less of an issue.

**Comment by MikeMcC399** [comment]
@lmiller1990 

> What about npx cypress run? 

That works correctly:

```
$ npx cypress run --e2e --browser webkit


DevTools listening on ws://127.0.0.1:57675/devtools/browser/90d38eb7-fd95-4c97-afdd-e9979e1f7e78

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.17.1                                                                        │
  │ Browser:        WebKit 16 (headless)                                                           │
  │ Node Version:   v18.16.1 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          1 found (spec.cy.js)                                                           │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  │ Experiments:    experimentalWebKitSupport=true                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  spec.cy.js                                                                      (1 of 1)
before launching browser
{
  name: 'webkit',
  channel: 'stable',
  family: 'webkit',
  displayName: 'WebKit',
  version: '16.4',
  path: 'C:\\Users\\mikem\\AppData\\Local\\ms-playwright\\webkit-1848\\Playwright.exe',
  majorVersion: '16',
  warning: 'WebKit support is currently experimental. Some functions may not work as expected.',
  isHeadless: true,
  isHeaded: false
}


top window inner w, h is 1280x720
  √ works (4138ms)

  1 passing (7s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  3                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     spec.cy.js                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  C:\Users\mikem\github\cypress-io\github-action\examples\webkit\cypress\screensho     (1280x720)
     ts\spec.cy.js\runner.png
  -  C:\Users\mikem\github\cypress-io\github-action\examples\webkit\cypress\screensho     (1000x660)
     ts\spec.cy.js\viewport.png
  -  C:\Users\mikem\github\cypress-io\github-action\examples\webkit\cypress\screensho    (1000x5050)
     ts\spec.cy.js\fullPage.png


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  spec.cy.js                               00:06        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:06        1        1        -        -        -

```

**Comment by lmiller1990** [comment]
It is working on MacOS. Seems Linux specific. Good to know it's only open mode - this will help debugging.

**Comment by Bohdan-Hevlich** [comment]
This issue is present for me. Cypress v12.17.2 / playwright-webkit v1.34 / MacOS Ventura 13.1. Also if trying to run in headless mode getting this error 
page.goto: An SSL error has occurred and a secure connection to the server cannot be made.
=========================== logs ===========================
navigating to "url.dev/__/#/specs/runner?file=cypress/e2e/tests/test.cy.js", waiting until "load"

**Comment by MikeMcC399** [comment]
@Bohdan-Hevlich 

- https://github.com/cypress-io/cypress/issues/25840 deals with your other issue. I see that you found it. This is just for anybody else who needs the link.

**Comment by MikeMcC399** [comment]
@lmiller1990 

I understood that you are not working for Cypress.io anymore, so I wonder if it's correct that this issue is still assigned to you.

**Comment by MikeMcC399** [comment]
I am no longer able to reproduce this issue.

Nobody else has verified it as an issue or confirmed the repro steps.

I suspect there may have been an NVIDIA video driver compatibility problem on my system where I run Ubuntu under VMware Workstation in a Windows 11 Pro host. I can't say for sure though.

So, I'm now closing as not reproducible.
