### ISSUE TITLE
Issues with the commands before, beforeEach, after, and afterEach in headless mode.

### ISSUE THREAD

**Issue by massayoshi-campos** [cypress-io/cypress#27306]
### Current behavior

I am integrating Cypress with TestRail, and I have created the integration code using the APIs. The behavior is very strange when the test is run for the first time using the browser. However, when the test is run for the second time, the flow works perfectly, and I can run it multiple times without any issues. However, during the first test, only the test run is created, and the command inside the 'after' block doesn't seem to be recognized.

In headless mode, only the test run is created, and the 'after' command also doesn't work. I have performed numerous tests, but without success. Then I ran Cypress in headless mode with the visible browser by passing the '--headed' flag. I noticed in the log that indeed the 'after' command was not being called at the end of the test. I updated Cypress to the latest version, v12.17.1, and repeated the same test. Now, the 'after' command is visibly being called and appears in the browser log. However, there still seems to be an issue because even though the log appears in the browser, the command is not being executed. The strange part is that when there is an error in the test and the same failed item is retested, then it works. It's a very strange behavior, isn't it?

There seems to be a problem with the 'before', 'beforeEach', 'after', and 'afterEach' commands that I cannot identify and analyze. This problem occurs only the first time the test is run in the browser and consistently happens in headless mode. The issue doesn't occur when there is a test failure, and the test needs to be rerun. In that case, the command inside the 'after' block is recognized.

Another issue is with the 'before' block. When executed for the first time using the browser, it is called for all 'it()' tests, but only the first time. When we run the test for the second time and subsequent times, the flow works perfectly. However, this behavior doesn't occur in headless mode. The 'before' block is always called for every test. This also seems to be a problem. Can you identify it?

### Desired behavior

The expected behavior would be for the 'before' block to be recognized in any call, whether using the browser or in headless mode. The block should always be executed, and as the function itself explains, it should only be executed once in the code. It shouldn't appear in every test.

Similarly, the expected behavior for the 'after' block would be for it to be recognized in any call, whether using the browser or in headless mode. The block should always be triggered, and as the function itself explains, it should only be triggered once in the code, at the end of the test. An interesting idea would be to have a method to make the function inside the 'after' block synchronous. That would be the basic concept.

### Test code to reproduce

```javascript
/// <reference types="cypress" />

// Retrieve TestRail credentials from environment variables
// Log in to Testrail

// Declare global variables
let testRunId
let resultRunId
let statusId
let testCaseIds = []
let testStatuses = {}

// **Custom Cypress command to create a test run in TestRail ****
Cypress.Commands.add('createTestRun', (suiteId, name, description, assignedToId, caseIds) => {
    const payload = {
        suite_id: suiteId,
        name: name,
        description: description,
        assignedto_id: assignedToId,
        include_all: false,
        case_ids: caseIds,
    }

    return cy
        .request({
            method: 'POST',
            url: 'https://{server}/index.php?/api/v2/add_run/{project_id}',
            headers: {
                'Content-Type': 'application/json',
                Authorization: auth,
            },
            body: payload,
        })
        .then((response) => {
            testRunId = response.body.id
            console.log('Test run created with ID:', testRunId)
            return response
        })
})

// Custom Cypress command to add test results to a test run in TestRail
Cypress.Commands.add('addTestResults', (results) => {
    const { testStatuses, testCaseIds, testRunId } = results
    const mappedResults = testCaseIds.map((caseId) => {
        const statusId = testStatuses[caseId] === 'passed' ? 1 : 5
        const comment = testStatuses[caseId] === 'passed' ? 'This test passed' : 'This test failed'

        return {
            case_id: caseId,
            status_id: statusId,
            comment: comment,
        }
    })

    cy.request({
        method: 'POST',
        url: `https://{server}/index.php?/api/v2/add_results_for_cases/${testRunId}`,
        headers: {
            'Content-Type': 'application/json',
            Authorization: auth,
        },
        body: { results: mappedResults },
    }).then((response) => {
        resultRunId = response.body[0].id
        console.log('Test results added for test run:', resultRunId)
        return response
    })
})

// Custom Cypress command to close a test run in TestRail
Cypress.Commands.add('closeTestRun', (runId) => {
    cy.request({
        method: 'POST',
        url: `https://{server}/index.php?/api/v2/close_run/${runId}`,
        headers: {
            'Content-Type': 'application/json',
            Authorization: auth,
        },
    }).then(() => {
        console.log('Test run closed:', runId)
    })
})

// **Test in the spec file ****
let testRunId = null
let testCaseIds = []
let testStatuses = {}
var caseId1 = 3237859
var caseId2 = 3237862
var caseId3 = 3237861

describe('test account', () => {
    beforeEach(() => {
        // Login and perform necessary setup before each test
        cy.login({ username: Cypress.env('userEmail'), password: Cypress.env('userPassword') })
        cy.visit('/')
    })

    afterEach(() => {
        // Collect test case results after each test
        const currentTest = Cypress.mocha.getRunner().suite.ctx.currentTest
        const caseId = extractTestCaseId(currentTest.title)
        testCaseIds.push(caseId)
        testStatuses[caseId] = currentTest.state
    })

    after(() => {
        // Add test results to the test run and close the test run
        if (!testRunId) {
            return
        }

        const results = {
            testStatuses: testStatuses,
            testCaseIds: testCaseIds,
            testRunId: testRunId,
        }

        cy.wrap(results).then((wrappedResults) => {
            cy.addTestResults(wrappedResults).then(() => {
                cy.wait(40000)
            })
            cy.closeTestRun(testRunId)
            console.log(testRunId)
        })
    })

    it(`${caseId1} - Test 1`, () => {
        // Create a test run and set the testRunId
        cy.createTestRun(
            {suiteId},
            `New test run - ${new Date().toLocaleString()} - ${Cypress.spec.name}`,
            'Test run description',
            {user number},
            [{caseID}, caseID, caseID, caseID] // Enter the test case number
        ).then((response) => {
            testRunId = response.body.id
        })
        // Include test block here
    })

    function extractTestCaseId(title) {
        // Helper function to extract test case ID from test title
        const matches = title.match(/\d+/)
        if (matches && matches.length > 0) {
            return parseInt(matches[0])
        }
        return null
    }
})
```

### Cypress Version

v12.17.1

### Node version

v18.16.1

### Operating System

Windows 22h2 19045.0386

### Debug Logs

```shell
I can't put the logs because it has confidential information
```

### Other

The problem is certainly in the call of the blocks before, beforeEach, after and afterEach, in the first test call and in headless mode it always happens, could you check the problem? Thanks.

**Comment by nagash77** [comment]
@taraske that sounds very odd indeed!  Would you be able to illustrate the issue in a fork of [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) so that our developers would be able to see this problem in action?

**Comment by massayoshi-campos** [comment]
@nagash77 I can indeed, and I will proceed with the procedure as soon as possible.

Let me provide further details about the issue to ensure there is no misunderstanding. The problem lies in the 'BEFORE' and 'AFTER' blocks. There are certain flows that can be reproduced multiple times.

1. Cypress: 12.17.1
2. Browser: Chrome 114
3. Node Version: v18.16.1

- Flow 1: UI Browser - 'Before' block

When the test is executed for the first time using the browser, the code inside the 'Before' block is executed for all tests within the spec. This only occurs when you start the test execution for the first time. From the second test onwards, the problem does not occur. After the second test, you can execute the tests as many times as you want without encountering the problem. However, on the first test execution, the problem always occurs. To reproduce the first test, after finishing the test execution, close all programs related to Cypress that are running, then open Cypress again, and the problem will occur again. Remember, this is very specific and only happens on the first execution.

[**Result of the first test run**]
![BeforeAll](https://github.com/cypress-io/cypress/assets/28022257/8fb01cd1-a7da-4362-81c0-3299e107425c)

- Flow 2: UI Browser - 'After' block

When the test is executed for the first time using the browser, the code inside the 'After' block is not executed within the spec. This only occurs when you start the test execution for the first time. From the second test onwards, the problem does not occur. After the second test, you can execute the tests as many times as you want without encountering the problem. However, on the first test execution, the problem always occurs. To reproduce the first test, after finishing the test execution, close all programs related to Cypress that are running, then open Cypress again, and the problem will occur again. Remember, this is very specific and only happens on the first execution.

[**Result of the first test run**]
![first test - Browser](https://github.com/cypress-io/cypress/assets/28022257/b11e1a91-6fea-4241-884e-be2c1b960175)

[**Result of the second test run**]
In the second test, you can notice that the code inside the After block is recognized.
![second test - Browser](https://github.com/cypress-io/cypress/assets/28022257/c60b8c4e-1784-44ae-876d-9b6559893739)



- Flow 3: Headless - 'Before' block

When the test is executed using headless mode, the code inside the 'Before' block is executed for all tests within the spec. The experience is different here, as this always happens in headless mode. By checking the log in the browser using the '--headed' flag, you can observe the 'before' block being executed for each test. To address this issue, I inserted the 'createTestRun' command within the IT() test block as a temporary solution, but the 'After' problem remains.

- Flow 4: Headless - 'After' block

When the test is executed using headless mode, the code inside the 'After' block is not executed within the spec. The experience is different here, as this always happens in headless mode. By checking the log in the browser using the '--headed' flag, you can see that the 'after' block is executed but doesn't work. I noticed that when a test within the spec fails, it will automatically be re-executed due to the runMode configuration, which in my case is set to '2' in the cypress.config.js file. In this scenario of failure, the 'After' block works successfully. Only in this case, the code inside the 'After' block works. I have conducted numerous tests and seek your help because it appears to be a problem with Cypress.

**Comment by massayoshi-campos** [comment]
cy.createTestRun({suiteId}, ..., ..., {user number}, [{caseID}, caseID, caseID, caseID]):

1. {suiteId}: It is an identifier for a specific test suite. It associates the test run with a particular suite or group of tests. Indicates that this test run belongs to the suite with the specified ID.
2. New test run - ${new Date().toLocaleString()} - ${Cypress.spec.name}: This parameter sets the title of the test run. The title is generated using the current date and time (new Date().toLocaleString()) along with the name of the current Cypress spec file (Cypress.spec.name).
3. 'Test run description': This is an optional parameter that sets a description for the test run.
4. {user number}: This is the {user number} or user identifier, such as a user ID or username, associated with the test run. Indicates who triggered or executed the test run.
5. [{caseID}, caseID, caseID, caseID]: This parameter expects an array of test case IDs (case numbers). Each element of the array represents a test case associated with the test run.
6. .then((response) => { ... }): This part of the code is a promise that handles the response returned by the cy.createTestRun method. Once the test run is created, the response is captured.
7. testRunId = response.body.id: The test run ID is extracted from the response body and stored in the testRunId variable. The test run ID is essential for further interactions with the test run, such as adding test results or closing the test run.

```
cy.createTestRun(
            {suiteId},
            `New test run - ${new Date().toLocaleString()} - ${Cypress.spec.name}`,
            'Test run description',
            {user number},
            [{caseID}, caseID, caseID, caseID] // Enter the test case number
        ).then((response) => {
            testRunId = response.body.id
        })
```

afterEach(() => { ... }):
The afterEach block, the code inside afterEach collects the test case results after each test. It extracts the currentTest being executed and retrieves its title. The title is then processed to extract the caseId, which is added to the testCaseIds array, and its test status (state) is recorded in the testStatuses object.

```
afterEach(() => {
        // Collect test case results after each test
        const currentTest = Cypress.mocha.getRunner().suite.ctx.currentTest
        const caseId = extractTestCaseId(currentTest.title)
        testCaseIds.push(caseId)
        testStatuses[caseId] = currentTest.state
    })
```

after(() => { ... }):
The after block, after all the tests in the current spec file have been executed. It is responsible for adding the test results to the test run and closing the test run. The code checks if a testRunId is available. If a test run ID exists, it proceeds to assemble the results object with testStatuses, testCaseIds, and testRunId. Then, it adds the test results using cy.addTestResults() and waits for 40 seconds before closing the test run with cy.closeTestRun(testRunId). Finally, the testRunId is logged to the console.

```
after(() => {
        // Add test results to the test run and close the test run
        if (!testRunId) {
            return
        }

        const results = {
            testStatuses: testStatuses,
            testCaseIds: testCaseIds,
            testRunId: testRunId,
        }

        cy.wrap(results).then((wrappedResults) => {
            cy.addTestResults(wrappedResults).then(() => {
                cy.wait(40000)
            })
            cy.closeTestRun(testRunId)
            console.log(testRunId)
        })
    })
```

**Comment by nagash77** [comment]
Hi @taraske sorry for the delay, I am trying to find the right resource to help troubleshoot this issue.  It will take some time.  I appreciate your patience.

**Comment by nagash77** [comment]
Hi @taraske have you had a chance to reproduce this behavior in a fork of [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) so that our developers would be able to see this problem in action?

**Comment by massayoshi-campos** [comment]
So far, I haven't had the opportunity to replicate this behavior in a fork of cypress-test-tiny. However, I plan to conduct tests as soon as possible, including tests with the new version of Cypress, to check if the issue still persists. It's worth noting that the nature of the interactions with TestRail involves sensitive data, which will require a careful approach.

Once I figure out a solution to ensure the protection of this sensitive information, I'll get back with the results. Nevertheless, the detailed information I've provided so far should be helpful for analysis. I'm available to assist with any issues that may arise.

Thank you for your help and attention.

**Comment by massayoshi-campos** [comment]
@nagash77 I've completed the setup for my API tests, and the integration worked flawlessly. It seems that in the "cypress": "^13.5.0" version, the issue no longer occurs. I'm pleased with the fix, and now Cypress is working perfectly with 'before', 'beforeEach', 'after', and 'afterEach' commands. Thank you for the support and attention provided. I believe we can consider this item successfully closed.

**Comment by chrisbreiding** [comment]
@massayoshi-campos That's great to hear! Happy testing!
