### ISSUE TITLE
Step Definition Missing Error while upgrading cypress version

### ISSUE THREAD

**Issue by hemanthbrane** [cypress-io/cypress#27300]
### Current behavior

We are migrating from cypress version 9.0 to 12.x.x, While upgrading we have encountered issue of step resolution missing for cucumber statements, the current directory where we are calling the step definition was attached below at the last.

Issue facing :  Step definition missing error for cucumber statements(Feature files), Almost tried all the methods from internet

Directory: (^ level of descent from cypress directory)

cypress
  ^e2e
     ^^features
         ^^^A2A
                ^^^^firsttest.feature
     ^^step_definations
         ^^^login.js
In package.json:

We have added step defination directory here in package.json

"cypress-cucumber-preprocessor": {
    "step_definitions": "cypress/e2e/step_definitions/**"
  }

In cypress.config.js:

we have declared spec in config file

e2e : {

specPattern: 'cypress/e2e/**/*.feature'

}

Versions:

Cypress : 12.x.x
NodeJs : 16.x.x
Cucumber : 8.9.4

[output.pdf](https://github.com/cypress-io/cypress/files/12047104/output.pdf)

### Desired behavior

1) Detailed Explanation of issue why it was happening

2) That error should be resolved

3) What are the other issue, we might find during upgrade 

### Test code to reproduce

As per company policy, we can't provide code but detailed explanation provided in current behaviour box

### Cypress Version

12.3.0

### Node version

v16.4.0

### Operating System

linux

**Comment by nagash77** [comment]
Hi @hemanthbrane right now there is not enough information for our engineers to reproduce this issue.  Can you please provide a reproducible example in a fork of [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) that demonstrates the issue?  Otherwise we will not be able to investigate further.

**Comment by hemanthbrane** [comment]
Hey,

It will be appreciable if anyone was able to connect with us to solve the issue, Please reply the available dates and timings, So that we will schedule a call.

Thanks and Regards
Hemanth
________________________________

**Comment by nagash77** [comment]
Hi @hemanthbrane we do not offer synchronous support services for the open source repo at this time.  If you are a paying customer please reach out to your account manager and they will be able to assist you.  I would also suggest you check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.  I am going to close this issue at this time.
