### ISSUE TITLE
Unable to use the plugin @cypress/grep for selective execution of spec files

### ISSUE THREAD

**Issue by T-e-j-k-u-m-a-r** [cypress-io/cypress#27310]
### Current behavior

Gettring below: 

![image](https://github.com/cypress-io/cypress/assets/54025065/9be23cf5-56d3-48e1-99ef-baaa0339e3c6)

Instead of executing only 1st spec file in login module which is SE-2949_TC1, It tries to exeucte all. May its because of the error thrown. 

e2e.ts file: 
![image](https://github.com/cypress-io/cypress/assets/54025065/99b52a8f-3442-462a-b452-eac86984c721)

spec file with smoke tag in it: 
![image](https://github.com/cypress-io/cypress/assets/54025065/411c9816-a3e7-4d52-b2f5-8c288a896036)

![image](https://github.com/cypress-io/cypress/assets/54025065/a6ec6284-df8a-4699-98e1-e8d6bb0782de)

### Desired behavior

Grep functionality should work allowing the execution of the only 1st spec file from the login module., 

### Test code to reproduce

![image](https://github.com/cypress-io/cypress/assets/54025065/88d9092f-9e72-4e5d-b71f-893f9174fd4a)

![image](https://github.com/cypress-io/cypress/assets/54025065/4e4d6bc1-3a94-4137-a8d7-a797200df705)

![image](https://github.com/cypress-io/cypress/assets/54025065/38dd7a92-93e1-48c1-98bd-30b19c25c107)

### Cypress Version

12.16.0

### Node version

14.15.0

### Operating System

Windows

**Comment by nagash77** [comment]
Hi @T-e-j-k-u-m-a-r , cypress/grep is not actively being worked on at this time so a fix may not happen in the near future.  I would suggest you try out this plugin [bahmutov/cy-grep](https://github.com/bahmutov/cy-grep) and see if that meets your needs and unblocks you in the meantime.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
