### ISSUE TITLE
include flow type definitions

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2732]
It would be nice to ship at least basic Flow definitions in addition to TypeScript definitions. From my experiments, we can just add `index.js.flow` file for example to the NPM package, something like this

```js
// to point flow at these type declarations in .flowconfig set
//
// [libs]
// node_modules/cypress/index.js.flow

// Mocha functions
declare function describe(name:string, callback:Function):void;
declare function before(callback:Function):void;
declare function beforeEach(callback:Function):void;
declare function it(name:string, callback:Function):void;
declare function after(callback:Function):void;
declare function afterEach(callback:Function):void;

// Cypress own types
declare interface subject {
  should(x: string, y: any): void;
  should('have.length', n: number): void
  // a lot more
}

declare interface cypress {
  visit(url: string): cypress;
  wrap(x: any): subject
  // a lot more
}

declare var cy: cypress
```

Then user projects has to include in `.flowconfig`

```
[ignore]

[include]

[libs]
node_modules/cypress/index.js.flow

[lints]

[options]

[strict]
```
and it gets IntelliSense and type checks

<img width="579" alt="screen shot 2018-11-06 at 9 48 46 pm" src="https://user-images.githubusercontent.com/2212006/48107468-c73e4800-e20d-11e8-9265-594567e7447c.png">

Of course it is a lot of work to properly describe all available API functions and assertions, but if we get the ball rolling, users can contribute.

**Comment by k7n4n5t3w4rt** [comment]
This is a good idea.

**Comment by lukeapage** [comment]
We have flow definitions we found on a gist and have been improving as we need to. I was going to contribute to flow-typed - as I believe is more normal for flow.

**Comment by lukeapage** [comment]
I don’t think that is possible? Flow-typed copies the types locally. In our setup we even ignore all flow coming from node_modules and rely only on flow-typed since it’s faster

**Comment by lukeapage** [comment]
WIP: https://github.com/flow-typed/flow-typed/pull/3028
