### ISSUE TITLE
Cypress Test Runner is Redirect to Full screen couldn't Automate that Page

### ISSUE THREAD

**Issue by abhiarnikar** [cypress-io/cypress#27330]
### Current behavior

When I click on the Makepayment button Cypress test runner is Redirect and Open in Full screen so i couldn't see the Execution and Couldn't Automate that Page.

https://github.com/cypress-io/cypress/assets/103327125/a150a798-3617-46e0-9ec5-429feb3508d5

### Desired behavior

I want to 2 solution 
1. That page should open within Test runner and want to Automate that Page.
2. Or Automate that page while opening in full screen and this is difficult.
So i prefer 1. option to do.

### Test code to reproduce

I Have used this code

cy.window().then(win => {
            cy.stub(win, 'open').callsFake((url, target) => {
                //cy.log(url)
                SecondUrl = url
                return win.open.wrappedMethod.call(win, url, '_self')
            }).as('open');
            cy.get(this.makepayment2)).click() //whiel clicking on this button Full screen is open
             cy.get('@open'); 
        });

I want to do Automation in this Page and this page should open in Test Runner

### Cypress Version

10.3.1

### Node version

18.16.1

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @abhiarnikar I see you opened a very similar issue #27329 .  I am going to close this issue as they both appear to related to your use same use case on different websites.
