### ISSUE TITLE
HTTP2 fetch streaming fails on cypress test run

### ISSUE THREAD

**Issue by markbeaman44** [cypress-io/cypress#27333]
### Current behavior

Our project as switched over to using http2 to take advantage of streaming - but this has had a knock on effect running the automation tests. As they fail due to `net::ERR_H2_OR_QUIC_REQUIRED`.

Outline:
When the body of a PUT or POST request made using fetch contains a stream (as opposed to text or a Blob) fetch requires the connection to be HTTP/2. We need to use a stream for certain endpoints so we can get an approximation of the upload progress. Initially all PUT and POST requests were made using streams and 100% of them failed in Cypress. 

Workaround: We switched to only use streams when we wanted to track progress. Requests that didn't use streams then started to work because they were all downgraded to HTTP/1.1, but 20% of our tests still fail as streaming is required.

<img width="842" alt="image" src="https://github.com/cypress-io/cypress/assets/30801986/18ccb858-f2ce-4cc3-95be-4fd97d5b2040">
<img width="1010" alt="image" src="https://github.com/cypress-io/cypress/assets/30801986/cc72f70d-04f1-4ead-a1cb-0029b11bcaa5">

### Desired behavior

Automation tests to run and complete like normal

### Test code to reproduce

N/A - as this is code within project

### Cypress Version

12.16.0

### Node version

18.15.0

### Operating System

macOS 12.5.1

### Debug Logs

```shell
cypress:server:socket-base backend:request { eventName: 'get:fixture', args: [ 'entity/imports/success_human UI.csv', { encoding: 'utf8' } ] } +5s
  cypress:server:fixture fixture exact name exists /Users/markbeaman/Documents/workspace/platform-e2e-tests/cypress/fixtures/entity/imports/success_human UI.csv +6m
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'test.platform', domain: 'bla', tld: 'com' } +2s
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'test.platform', domain: 'bla', tld: 'com' } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'test.platform', domain: 'bla', tld: 'com' } +2ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://test.platform.bla.com', strategy: 'http', fileServer: null, domainName: 'bla.com', props: { port: '443', protocol: 'https:', subdomain: 'test.platform', domain: 'bla', tld: 'com' } } for: https://test.platform.bla.com/api/entities/v1/entity-imports/94d03a3e-bce1-443d-85ff-13836ab1cc1e +2s
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'bla', tld: 'com' } +0ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://test.platform.bla.com', strategy: 'http', fileServer: null, domainName: 'bla.com', props: { port: '443', protocol: 'https:', subdomain: 'test.platform', domain: 'bla', tld: 'com' } } for: https://bla.com +0ms
  cypress:server:stream_buffer appending chunk to buffer { bytesWritten: 0, chunkLength: 145 } +2s
  cypress:network:agent addRequest called { isHttps: true, href: 'https://test.platform.bla.com/api/entities/v1/entity-imports/94d03a3e-bce1-443d-85ff-13836ab1cc1e' } +2s
  cypress:network:agent got family { family: 4, href: 'https://test.platform.bla.com/api/entities/v1/entity-imports/94d03a3e-bce1-443d-85ff-13836ab1cc1e' } +0ms
  cypress:server:stream_buffer stream buffer writeable final called +0ms
  cypress:server:request received status code & headers on request { requestId: 'request128', statusCode: 201, headers: { 'content-type': 'application/json' } } +2s
  cypress:server:request successful response received { requestId: 'request128' } +0ms
  cypress:net-stubbing:server:intercept-response InterceptResponse { req: { url: '/api/entities/v1/entity-imports/94d03a3e-bce1-443d-85ff-13836ab1cc1e' }, request: undefined } +2s
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'bla', tld: 'com' } +145ms
```

### Other

Looking at the debug - its not showing the request that failed - only the requests leading up to it.

**Comment by nagash77** [comment]
Currently Cypress does not support HTTP/2.  Please follow [thus ticket](https://github.com/cypress-io/cypress/issues/3708) for updates.  Closing this issue as a duplicate.

**Comment by markbeaman44** [comment]
@nagash77 I was told to create a ticket as per this comment in the ticket you mentioned: https://github.com/cypress-io/cypress/issues/3708#issuecomment-1639358812

**Comment by nagash77** [comment]
Oh I see that @lmiller1990 suggested you log your use case where HTTP/2 was breaking your tests.  Sorry for the confusion.  Are you able to provide a [reproducible example](https://github.com/cypress-io/cypress-test-tiny)?

**Comment by markbeaman44** [comment]
@nagash77 Sorry for the delay - it took some time to replicate it locally - please see attached.
[cypress-test.zip](https://github.com/cypress-io/cypress/files/12159784/cypress-test.zip)
