### ISSUE TITLE
Can folders be collapsed by default or hold the last set status?

### ISSUE THREAD

**Issue by TomDvorsky** [cypress-io/cypress#27334]
### What would you like?

This relates to https://github.com/cypress-io/cypress/issues/14528 which works in cypress < 10. I have a huge project, in e2e folder I have many more folders, each of them containing tests for different features. When I need to run a specific one, if it is in the last folder it takes much needed time ...
![image](https://github.com/cypress-io/cypress/assets/139970106/3903cb87-58ee-4cc7-80c4-7da22cc5e064)

As noted above, the linked ticked did add this
![image](https://github.com/cypress-io/cypress/assets/139970106/b9044a47-12e7-4848-9bc2-bd644ece0f93)

Now, when a test is run, one has to click on the "Specs" in sidebar and the page is always with uncollapsed folders - would be really nice if it could keep the latest user's setting ...

### Why is this needed?

Speed up work. Occasionally a test needs to be updated & run manually. Not everyone likes starting tests via command line.

**Comment by nagash77** [comment]
How is this request different than the issue linked in the description?

**Comment by TomDvorsky** [comment]
Well, the older request was closed, done for version with different UI. There, when a user had only 1 folder uncollapsed, a particular test could run - and the user still had only that folder uncollapsed. Now, if I collapse everything, uncollapse only the folder I need, run the test, click Specs - all is uncollapsed again ...
On the picture in the 1 post there's e2e folder which contains the subfolders. If I click that - all the subfolders are hidden, so I cannot click on the particular one I am interested in. I have to uncollapse e2e - and there's everything uncollapsed ...

**Comment by nagash77** [comment]
I see that other issue as still open.  I would suggest you add your suggestions to that thread so it is all contained in one place.  I am going to close this issue as a duplicate and ask folks to comment/follow https://github.com/cypress-io/cypress/issues/14528.
