### ISSUE TITLE
Cypress 10 really slow, only in Chrome v114

### ISSUE THREAD

**Issue by alpo22** [cypress-io/cypress#27344]
### Current behavior

To run one of the sample specs included with Cypress:

Chrome v114 takes 1:06
Firefox v113 takes 0:04
Electron v102 takes 0:03

### Desired behavior

Chrome is usable

### Test code to reproduce

Reproduce with this repo (which is just Create React App and the tests created by Cypress). Instructions in the readme.

https://github.com/alpo22/cypress-chrome-test

### Cypress Version

10.4.0

### Node version

v18.16.0

### Operating System

Mac Ventura 13.4.1

**Comment by nagash77** [comment]
possibly related to https://github.com/cypress-io/cypress/issues/22868

**Comment by Narretz** [comment]
You should test with the latest 12.x version and not with an old 10.4

**Comment by phoenixeliot** [comment]
I came here because our tests were horrendously slow on Cypress 9 with Chrome 114, and updating to Cypress 12 sped them up by about 20x. Nice!

**Comment by jennifer-shehane** [comment]
Plz try latest 13 versions, we’ve improved some perf there as well.
