### ISSUE TITLE
Run tests asynchronously

### ISSUE THREAD

**Issue by nobuttsseb** [cypress-io/cypress#2734]
### Current behavior:

I have some code that I'm testing that communicates to an API under the hood (so I cannot use request() or aliases). There is a method `load(callback)` in which I wish to do the assertions in the callback after it has gotten the data and processed it from the server. Currently Cypress runs synchronously and just runs the next test while the current test is still communicating with the server. When the assertion is finally called it ends up being logged in the next test (or the test after that). I use cy.wait(200) as a hack but I cannot rely on a timeout as the connection may be slower on some days.

### Desired behavior:

To have a way to control Cypress's sync process. It would be good to have something like pause() before the hidden async server call then use continue() after the assertions have been made. Something similar to how QUnit works:

```js
QUnit.test( "assert.async() test", function( assert ) {
  var done = assert.async();
  setTimeout(function() {
    done();
  });
});
```

**Comment by chrisbreiding** [comment]
Cypress uses [mocha](https://mochajs.org) as its test runner, which [has the same concept using a `done` callback](https://mochajs.org/#asynchronous-code):

```javascript
it('async test', function (done) {
  setTimeout(function() {
    done();
  });
});
```

You can also return a promise and it will be awaited.
