### ISSUE TITLE
Cypress Dashboard Headless Mode: When a test fails, on the 2nd try; skips over before block. 

### ISSUE THREAD

**Issue by HappyMan0001** [cypress-io/cypress#27365]
### Current behavior

I am using the Cypress Dashboard with 4 VMs (parallelization). When I review the video results of any of the failed tests, I noticed: Cypress on the 2nd try, will skip over the before or beforeEach() block. If the before/beforeEach block is skipped then it will cause my tests to fail. My tests need to be ran from the start which I assume would be the before block. Not skip over the before block if the test fails the 1st round. 

### Desired behavior

Need the tests, to be ran from before() block on the 1st and 2nd try. 

### Test code to reproduce

none

### Cypress Version

11.1

### Node version

18.13

### Operating System

Windows 10 Enterprise

### Debug Logs

```shell
NOne
```

### Other

None

**Comment by jennifer-shehane** [comment]
@HappyMan0001 Could you provide a reproducible example? I haven’t seen this behavior so need to narrow down what’s happening in your case.

**Comment by HappyMan0001** [comment]
@jennifer-shehane, hi I reviewed this issue figured out when this started to happen. Reviewed PR with the engineer who pushed the changed. Found and updated error. I am back up and running. Thank you for your reply. 👍
