### ISSUE TITLE
Couldn't find a way to off the iframe.

### ISSUE THREAD

**Issue by sdhimanshu** [cypress-io/cypress#27371]
### Current behavior

I have a button inside iFrame after clicking on it redirects to the test runner dashboard page.
It means clicking a button inside iFrame stops the test execution.

### Desired behavior

Button available inside iframe should redirect to the linked page.

### Test code to reproduce

Follow these steps to reproduce:
1. Visit website - Nykaa.com
2. Add any product to the bag.
3. Click on cart icon so you can see cart and this cart is itself an iframe.
4. Now try to click on Proceed button from cart. Then it will stop the test execution.

Here i am providing my code so you can use this code directly-
```
it('visit the nykaa and search one product', () => 
{ 
    cy.visit('https://www.nykaa.com/'); 
    cy.get('[name="search-suggestions-nykaa"]').type('Facewash{enter}'); 
    cy.get('[#product-list-wrap').should('exist');
    cy.get('[#product-list-wrap a').eq(0).invoke('removeAttr','target').click(); 
    cy.wait(1000);
    cy.get(' .css-f81pz4 button.css-13zjqg6').click(); 
    cy.get('button.css-aesrxy').click(); \
    cy.get('.css-acpm4k').its('0.contentDocument.body').as('iframeBody'); 
    cy.get('@iframeBody').find('[data-test-id="footer"] button').click()
})
```

### Cypress Version

12.15.0

### Node version

18.16.0

### Operating System

Win 11

### Debug Logs

```shell
Logs can't found because it quit the log page.
```

**Comment by nagash77** [comment]
Hi @sdhimanshu unfortunately at this time Cypress does not support this use case.  Please follow along with [this issue](https://github.com/cypress-io/cypress/issues/136) for updates on this functionality.

You may want to check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
