### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#2737]
### Current behavior:

I pinned a snapshot from a previous test, then clicked to 'Hide Highlights' so I could see the DOM element. The entire webpage went blank and the error below logged in the console:

<img width="1679" alt="screen shot 2018-11-07 at 12 02 31 pm" src="https://user-images.githubusercontent.com/1271364/48152993-39a53b80-e293-11e8-903d-2956580d2cc3.png">

<img width="557" alt="screen shot 2018-11-07 at 12 02 50 pm" src="https://user-images.githubusercontent.com/1271364/48152992-39a53b80-e293-11e8-87f3-1d215f28f148.png">

### Desired behavior:

Should probably add a check to the Node is a child before calling `removeChild` to prevent err.

### Steps to reproduce:

I tried to run the same scenario again and wasn't able to reproduce it :/ 

### Versions

Cypress 3.1.1

**Comment by sainthkh** [comment]
It's been fixed by [adding try...catch in cypress/react-tooltip](https://github.com/cypress-io/react-tooltip/blob/master/src/portal.jsx#L32). Right?

**Comment by chrisbreiding** [comment]
@sainthkh, I think you're right. Going to close this issue, since it appears it has been fixed since Cypress `3.4.1`. 

If anyone encounters this again, let us know and we can re-open it.

**Comment by davidmnoll** [comment]
I just encountered this

**Comment by darrylsepeda** [comment]
I also encounter this...
v12.14.0
![image](https://github.com/cypress-io/cypress/assets/135600186/573ebd31-6d1e-41d2-9178-ad72d238a40f)
