### ISSUE TITLE
Cypress Job taking long duration to run

### ISSUE THREAD

**Issue by gitsachin** [cypress-io/cypress#27382]
### Current behavior

- I have an active "Team" subscription for cypress
- Currently i have 10 jobs setup on the pipeline to run tests in parallel
- When the cypress run is conducted, at random one of those jobs take more ~ 1 hour to complete
- Rest of the 9 jobs completed within ~ 15 mins
- Job contains only few spec files which take about ~7 minutes to run but the job container itself continues to run for more than an hour 
- This issue is faced intermittently, but still occurs too often to be ignored
- 
![github SS](https://github.com/cypress-io/cypress/assets/8189025/666ca692-659e-42e5-9d29-2b4bfa7a4f53)

### Desired behavior

All of the jobs should take approximately the same time to be completed

### Test code to reproduce

No code specifically, the test repo is fine

### Cypress Version

11.2.0

### Node version

16.2.0

### Operating System

Windows 11

### Debug Logs

```shell
No logs
```

**Comment by eswanny22** [comment]
Hi @gitsachin, could you please send this to support@cypress.io? In the email, could you also add:
- How much RAM and CPU your machines have?
- The debug logs from a time this happens will also be helpful.

**Comment by nagash77** [comment]
I am going to close this issue since it will be handled internally at this point.
