### ISSUE TITLE
After migrate Cypress 9 to 12 facing issue 

### ISSUE THREAD

**Issue by VaishaliPaigavan** [cypress-io/cypress#27381]
### Current behavior

After migration I'm facing issue when I run spec file. Spec file not run facing issue in Then function... please guide what can I do
![image](https://github.com/cypress-io/cypress/assets/58266411/e4f8aeed-423c-4c40-af5c-13af13a31554)

### Test code to reproduce
```js
import moment from 'moment';
const faker = require('faker');
const firstName = faker.name.firstName();
const lastName = faker.name.lastName();
const phone = faker.phone.phoneNumber();
const adress = faker.address.streetName();
const city = faker.address.state();
const numbers = faker.random.number();
const words = faker.random.words(10,11);
const Oneword = faker.random.word(6,15);
const hudredword= faker.random.words(101,150)
const lessThanSixChar= faker.random.words(1,5)

var num1=Math.random().toString(9).substr(2,1);
var num2=Math.random().toString(6).substr(2,1);
var num3=Math.random().toString(6).substr(2,1)

Then('Regional Comparison Data Widget contents and funtionality', () => {  
    // ------------------------------------------------
   
    cy.xpath("//div[contains(text(),'Regional Comparison Data')]").scrollIntoView()
    cy.xpath("//th[contains(text(),'YTD As Of')]").should('be.visible')
    cy.screenshot()
    cy.xpath("//th[contains(text(),'Avg Clean Price')]").should('be.visible')
    cy.screenshot()
    cy.xpath("//th[contains(text(),'Term %')]").should('be.visible')
    cy.screenshot()
    cy.xpath("//th[contains(text(),'Closing %')]").should('be.visible')
    cy.screenshot()
    cy.xpath("//th[contains(text(),'CGS %')]").should('be.visible')
    cy.screenshot()




})
```
### Cypress Version

12.17.0

### Node version

v16.13.2

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @VaishaliPaigavan In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by VaishaliPaigavan** [comment]
I'm facing this issue....


The following error originated from your test code, not from Cypress.

  > Then is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

**Comment by VaishaliPaigavan** [comment]
Hi @nagash77 can I create new repository or directly put my code https://github.com/cypress-io/cypress-test-tiny here?

**Comment by nagash77** [comment]
@VaishaliPaigavan you should fork the linked repo and then add your test to that repo and run that repo in Cypress.  If it reproduces the error then link back to that repo for our developers to investigate.  Please make sure you run the test once its in the new repo to ensure it still displays the described behavior.

**Comment by tester-at-bmi** [comment]
I wonder where the `Then` is coming from? It that a thing? Never looked much into it but have used `describe`, `context` and `it` blocks for test cases.

Guess you're using gherkin or something with `given`, `when`, `then`? You probably have issues configuring your project and plugins.

**Comment by VaishaliPaigavan** [comment]
Yes right I have use gherkin... I have written feature files using gherkin

**Comment by VaishaliPaigavan** [comment]
My issue is resolve I have use specPattern:'cypress/integration/**/*.feature' in cypress.config.js file

**Comment by VaishaliPaigavan** [comment]
Close
