### ISSUE TITLE
 When visiting a path on the same domain that redirects to another domain all variables are cleared

### ISSUE THREAD

**Issue by khashaba** [cypress-io/cypress#27395]
### Current behavior

Currently I'm testing a domain with a path like this: `https://identity.test.myCompany.com/` but when I tried to visit a different path: `https://controls.test.myCompany.com/` I found that Cypress reloads the browser and all the variables that I set through the previous test are cleared to the default values.
 the second link I used is a link that redirects to Microsoft authentication, 

I already managed to change my test to overcome this issue. but I think it's a bug that need to be fixed

### Desired behavior

Cypress shouldn't clear any variables as long as it's on the same test - `describe()=>{ // all variables here should always be here}`-

I can understand that I will fail because of cross origin with Microsoft authentication but not clearing the variables

### Test code to reproduce

```
describe('Bug - variables are cleared', () => {
  context('my context', () => {
    let normalLink = '';
    let linkThatRedirectToAuthintication = '';
    let myVar = '';
    let myVar2 = '';

    before(() => {
      // you can use a proper link
      // but i used this for showing what i mean
      cy.visit(normalLink);
    });

    it('set variable 1', () => {
      myVar = 'value1';
    });
    it('set variable 2', () => {
      myVar2 = 'value2';
    });

    it('visit different path', () => {
      cy.visit({
        url: linkThatRedirectToAuthintication,
        followRedirect: false,
      });
    });

    it('see the error', () => {
      expect(myVar).to.eq('value1'); //shows that myVar = ''
      expect(myVar2).to.eq('value2'); //shows that myVar2 = ''
    });
  });
});

```

### Cypress Version

12.17.1

### Node version

18.15.0

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @khashaba I would suggest you read through our [cy.origin](https://docs.cypress.io/api/commands/origin#Syntax) documentation and perhaps also [disabling chromeWebSecurity](https://docs.cypress.io/guides/guides/web-security#Set-chromeWebSecurity-to-false) and see if that helps your use case.

Also check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by khashaba** [comment]
I appreciate your patience as we work through this issue. Unfortunately, disabling ChromeWebSecurity doesn't seem to be the solution we need.

As you mentioned, using cy.origin() isn't an option because you're working within the same domain. However, when you visit the second link that uses Microsoft authentication, it triggers a browser reload. This reload operation results in the clearing of all variables, including ones like `const randomNumber = Cypress._.random(0, 1e6)`.

For instance, if the random number was originally set to 10034, after the redirection, it gets reset to a different number, like 123213.

I hope this clarifies the situation, and if you have any further insights or suggestions, please feel free to share them. We're working together to find a resolution.
