### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'KeyboardEvent')

### ISSUE THREAD

**Issue by suyash3010** [cypress-io/cypress#27398]
### Current behavior

I am getting the above error, and the text is not typed in the element that is provided.

It does not throw this error when tests are ran on local machine headless , error is only thrown intermittently when tests are ran on Azure devops pipeline. 

### Desired behavior

Text should be typed and no error to be displayed

### Test code to reproduce

    cy.get('#editor_ifr').then(($iframe) => {
      const $body = $iframe.contents().find('body');

      cy.wrap($body).type(text, {
        parseSpecialCharSequences: false,
      });

### Cypress Version

12.7.0

### Node version

16.15

### Operating System

macOS 13.4.1

**Comment by nagash77** [comment]
@suyash3010 is this iframe in the same domain and sub-domain as the page you are visiting?  Here is a [link to cross-origin testing guides](https://docs.cypress.io/guides/guides/web-security#Cross-origin-iframes) that may be helpful.

**Comment by suyash3010** [comment]
@nagash77 This is in the same domain and as described earlier it runs correctly in interactive mode and also headless on local machine. it is only failing on Azure pipeline

**Comment by nagash77** [comment]
Hi @suyash3010 unfortunately we cannot replicate your azure pipeline to reproduce this problem.  That means at this point we do not have a path forward for our engineers to investigate this issue further at this moment.  I am going to close this issue at this time.

I would suggest you check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress and others may have setups similar to your own.

**Comment by hannamakarychak** [comment]
I also had this issue in cypress 14.4.1. I decided to skip typing altogether and manually invoke change, and it worked:

it('should type into text input ticket number', () => {

    const testValue = 'BA12345';
     
    cy.get('input[name="ticket-number"]', { timeout: 6000 })
      .should('exist')
      .should('be.visible')
      .should('not.be.disabled')
      .invoke('val', testValue)
      .trigger('input')
      .trigger('change');
       
    cy.get('input[name="ticket-number"]').should('have.value', testValue);
  });
