### ISSUE TITLE
Using old electron version results in Failed to execute 'matches' on 'Element': ':autofill' is not a valid selector.

### ISSUE THREAD

**Issue by yuwu9145** [cypress-io/cypress#27393]
### Current behavior

Run `document.documentElement.matches(':autofill')` in electron V106 console, get error:

`VM29:1 Uncaught DOMException: Failed to execute 'matches' on 'Element': ':autofill' is not a valid selector.`

But it works in chrome

### Desired behavior

No error

### Test code to reproduce

Run `document.documentElement.matches(':autofill')` in electron V106 console, get error:

`VM29:1 Uncaught DOMException: Failed to execute 'matches' on 'Element': ':autofill' is not a valid selector.`

But it works in chrome

### Cypress Version

12.17.2

### Node version

v16.19.0

### Operating System

Windows 11 Business 22621.1848

### Other

Probably upgrading electron to new versions could resolve the issue, I tried Electron Fiddle with Electron v25.2.0 no issue

**Comment by nagash77** [comment]
Hi @yuwu9145 , thank you for submitting this ticket.  We are currently working through an electron upgrade for Cypress.  Unfortunately I do not have an estimated release date but we will be sure to update this ticket when it is out.

**Comment by MikeMcC399** [comment]
- Electron was updated in #27715 and released with [Cypress `13.2.0`](https://docs.cypress.io/guides/references/changelog#13-2-0).
