### ISSUE TITLE
grepFilterSpecs:true was not working

### ISSUE THREAD

**Issue by hemanthbrane** [cypress-io/cypress#27392]
### Current behavior

We are using cypress 12 version and while using cypress-grep for tag filteration for cucumber tests, grepFilterSpecs was not working, the command was not filtering spec based on the tags instead it was running all the feature files and checking for the tags inside the file, how to resolve that

![InkedScreenshot 2023-07-26 152251](https://github.com/cypress-io/cypress/assets/139533323/e1c0868c-a745-4ed4-b613-446c450de8d0)

### Desired behavior

We just want to filter all the tags and then run instead going into each and every feature file and run, everything configured just like in the manual

### Test code to reproduce

cypress.config.js:

```js
e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {

      require('@cypress/grep/src/plugin')(config);
      //require('../cypress/plugins/index.js')(on, config);
        return require('../cypress/plugins/index.js')(on, config);
      
    },
    specPattern: 'cypress/e2e/features/**/*.feature',
```
### Cypress Version

12.8

### Node version

18.x

### Operating System

ubuntu

**Comment by nagash77** [comment]
Hi @hemanthbrane your screenshot is not showing for me.  Can you update that please?  Can you also clarify what you mean by it's not filtering by the tags?

**Comment by hemanthbrane** [comment]
Updated the image, Not filtering in the tags means, lets suppose I have 10 feature files where the tag which I want to search was only found in 3 feature files, I just want to run only those 3 feature files and omit the rest

our code structure is:

```
`config
    qa.config.js
cypress
   e2e
      features
          A2A
            login.feature
package.json
`
```

We are running the the cypress with command:

npx cypress run --config-file config/qa3.config.js --env grepTags=@REG1,grepFilterSpecs=true  --browser chrome

**Comment by hemanthbrane** [comment]
edited to clear out duplicate comment

**Comment by nagash77** [comment]
@hemanthbrane Can create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.  I want to make sure you are tagging tests correctly and passing in the tag args correctly.

Reading through the [docs on cypress/grep filtering with tags](https://github.com/cypress-io/cypress/tree/develop/npm/grep#filter-with-tags) I wonder if your command line string is causing issues.

What if you simplify the command to try and narrow down causes?

Does running `npx cypress run --config-file config/qa3.config.js --env grepTags='@reg1' --browser chrome` change anything?

What if you try a simple test and just filter down to one name just to make sure cypress/grep is working at all.?

`npx cypress run --config-file config/qa3.config.js --env grep='Sample Test Name' --browser chrome`

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
