### ISSUE TITLE
cypress.request is inserting null into the request url.

### ISSUE THREAD

**Issue by menden** [cypress-io/cypress#274]
A null is being injected into the request url.
## Cypress.json

```
{
  baseUrl: 'http://localhost:3003/'
}
```
## Test code

```
cypress.request('POST', 'v2/some/url', {name: 'jane'})
```
## Resulting request

```
POST  http://localhost:3003/null/v2/some/url
```

**Comment by brian-mann** [comment]
Fixed in [`0.17.10`](https://github.com/cypress-io/cypress/wiki/Changelog#01710-11072016).
