### ISSUE TITLE
Setting up component testing - laravel-vue

### ISSUE THREAD

**Issue by whitespacecode** [cypress-io/cypress#27408]
### Current behavior

I had the issue that component tests did not load so i followed this:
https://github.com/cypress-io/cypress/issues/22505#issuecomment-1352240759
And indeed when removing laravel-vue plugin from vite the component test are working. 

So i needed to convert my cypress.config.js to .ts so i can use import instead of require.
Now i get `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" ` 
when using `import viteConfig from './vite.config';`

Also seen here, but since he didn't needed to import his vite file he just converted everything to .js
https://github.com/cypress-io/cypress/discussions/22950

When adding `"type": "module"` to package.json i can then continue the component tests but my app doesn't work properly anymore.

Anything i can do so cypress can import vite.config.ts file correct ? 

### Test code to reproduce

/

### Cypress Version

12.17.0

### Node version

v18.8.0

### Operating System

macOS 13.4

**Comment by nagash77** [comment]
Hi @whitespacecode issues in the repository are reserved for bugs and feature requests.  Without any reproduction steps we will be unable to investigate this issue.  If you are new to Cypress and have questions on how to use it check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity.
