### ISSUE TITLE
Cypress Not Responding

### ISSUE THREAD

**Issue by kchandranaik** [cypress-io/cypress#27429]
### Current behavior

I am Unable to use Cypress app. Every time I have to run the code through visual studio code.
I am not able to run the code inside the cypress app, It shows Cypress not responding.
<img width="721" alt="Screenshot 2023-08-01 135223" src="https://github.com/cypress-io/cypress/assets/101552926/9183e17b-8a2d-44c8-9cb9-90d9aa6339c0">

### Desired behavior

We can run the testcases from cypress app directly, But I am not able to do that

### Test code to reproduce
```js
describe("template spec", () => {
  it("passes", () => {
    cy.visit("https://rahulshettyacademy.com/seleniumPractise/#/");
    cy.get(".search-keyword").type("ca");
    cy.wait(2000);
    
    cy.get('.products').as('ProductLocator')
    cy.get("@ProductLocator").find(".product").should("have.length", 4); 

    //iterate through 4 items, if condition
    cy.get("@ProductLocator")
      .find(".product")
      .each(($el, index, $list) => {
        let textveg = $el.find("h4.product-name").text();

        if (textveg.includes("Carrot")) {      // if text contains carrot
          cy.wrap($el).find("button").click();  //button is the locator for add to cart button
          cy.get("img[alt='Cart']").click()
          cy.contains("PROCEED TO CHECKOUT").click()
          cy.contains('Place Order').click()
        } 
        
      })
     
    })
})
```

### Cypress Version

v12.17.2

### Node version

v18.17.0

### Operating System

Microsoft windows 11 pro  Version	10.0.22000 Build 22000

### Debug Logs

```shell
I am not getting any error, Cypress app itself not working, Says Cypress not responding
```

**Comment by nagash77** [comment]
@kchandranaik what happens when you simplify your test down to just a cy.visit command?  Do you see this on other browsers?  Try to get down to the simplest test possible to see if can narrow down the potential problem.

**Comment by kchandranaik** [comment]
For simple cy.visit command also it says Cypress not responding. Some Time I am not able to click on the Spec files also.
![Screenshot (165)](https://github.com/cypress-io/cypress/assets/101552926/2be49dc5-9023-4064-a528-1d6ec4aa7223)

**Comment by kchandranaik** [comment]
Sometime, In Browser Selection page only issue persist

![Screenshot (166)](https://github.com/cypress-io/cypress/assets/101552926/ed16314e-9661-4ae9-bc7f-8ec18235e389)

**Comment by nagash77** [comment]
Hi @kchandranaik are you able to share your debug logs?  This Cypress crashing on a simple test of just a visit, it makes me think this is something related to your specific environment, becuase otherwise we would be flooded with reports of Cypress crashing in such a simple scenario.  Can you try running the same tests on another machine or a VM to see if those work?

**Comment by kchandranaik** [comment]
Yeah it will work on other machines without any interruption.

**Comment by nagash77** [comment]
I think that confirms my suspicions.  Unfortunately we will not be able to reproduce this problem on our end and thus will need to close this ticket.  You may want to try disabling any anti-virus software you have running and see if that helps (kind of a shot in the dark).

Also check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by bledardakaj** [comment]
@kchandranaik hey, I am facing same issue and can not find any solution. By any chance you have the solution, can you help me?

**Comment by kchandranaik** [comment]
I didn't get any solution for that
