### ISSUE TITLE
Fake video for webcam testing not working in Chrome 115

### ISSUE THREAD

**Issue by ioanabrooks** [cypress-io/cypress#27424]
### Current behavior

Fake video for webcam testing is not loaded, no errors present, just black screen in place of video.

### Desired behavior

Fake video should load.

### Test code to reproduce

```
 on('before:browser:launch', (_browser, launchOptions) => {
        launchOptions.args.push(
          '--use-file-for-fake-video-capture=cypress/fixtures/myFixtureHere'
        );

        return launchOptions;
      });
```

Run on chrome 115 locally or in CI (Github actions).

Works with Chrome 114.

### Cypress Version

10.11.0

### Node version

16.16.0

### Operating System

macOS 12.6 locally, linux in CI

**Comment by nagash77** [comment]
Hi @ioanabrooks , I see you are using an older version of Cypress.  Are you seeing the same behavior on the latest version?

**Comment by nickls** [comment]
@nagash77  -- I'm also seeing this issue with Cypress 12.17.3 with Chrome 115.0.5790.170.

The test pattern loads normally if I don't specify a video path.

**Comment by JoseAmbiser** [comment]
Try using the **y4m** file extension instead of mjpeg.
`ffmpeg -i file.mjpeg file.y4m`

**Comment by nickls** [comment]
@JoseAmbiser -- that fixes it. thank you!
