### ISSUE TITLE
Install via pnpm

### ISSUE THREAD

**Issue by inblossoms** [cypress-io/cypress#27422]
### Current behavior

Initializing the project through pnpm, the entire installation process takes an extremely long time to complete, and component test cases are still missing from the final project.

### Cypress Version

@latest

### Node version

v16.17.1

### Package Manager

pnpm

### Package Manager Version

8.5.1

### Operating system

Windows

### Operating System Version

11

### Other

I mentioned PR for the problem at hand：[#5402](https://github.com/cypress-io/cypress-documentation/pull/5402), even though it might not be appropriate.

**Comment by MikeMcC399** [comment]
@inblossoms 

You are describing two problems:

1) Initializing takes a long time
2) There are no component test cases

You may need to separate these into two different issues and provide logs / reproducible examples.

---

## Initialization time

What did you mean by "initializing"? Is that the same as installing Cypress?

On a Windows 11 system with your versions of Node.js and pnpm and an empty package.json it took 23 seconds to install Cypress.

How long did it take on your system? 
What command did you use to install Cypress? or whatever you did to "initialize"?
Did you have other dependencies installed before you installed Cypress?

```text
node -v
v16.17.1
pnpm -v
8.5.1

pnpm add cypress -D
Packages: +174
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 174, reused 174, downloaded 0, added 174, done

devDependencies:
+ cypress 12.17.2

Done in 18.9s
```

## Component test cases

Could you describe what you mean by missing component test cases?

Installing Cypress does not add any component test cases.

**Comment by jordanpowell88** [comment]
@inblossoms I just created a new pnpm project using vite and everything appears to working very snappy to me. Can you provide a working example of the problem you are experiencing?

**Comment by inblossoms** [comment]
After I passed `pnpm i`, the root directory did not produce a new file: the cypress folder (including the subfiles under the cypress, of course). 

I tried to enable cypress: 'npx cypress open' when I didn't notice I was missing the cypress file, and I got the following error:
```
No version of Cypress is installed in: /Users/UserName/Library/Caches ........

Please reinstall Cypress by running: cypress install

-----------

Cypress executable not found at: /Users/UserName/LibraryCaches/Cypress .........
```

I have forgotten more details, I'm sorry that I don't want to repeat it again. Since it should be 'pnpm add', I think I should close this issue.

**Comment by inblossoms** [comment]
@ MikeMcC399

> Could you describe what you mean by missing component test cases?

Should be a question of my presentation, I want to talk about the example of testing Cypress provides to users.
I had so many flaws just in my description of what was wrong with me, like a kid. uh, thank you for your time. I'm tired.
