### ISSUE TITLE
data-testid not showing in cypress ui, but does show in our html

### ISSUE THREAD

**Issue by rmnrdi** [cypress-io/cypress#27431]
### Current behavior

The current behavior is the attribute data-testid (supposedly supported by cypress) added by our dev team is not visible when using cypress. 
When we open the app in chrome, it's there.
![image](https://github.com/cypress-io/cypress/assets/23411447/bab14afb-2f6a-4b3b-a087-ba906fa9b19f)
![image](https://github.com/cypress-io/cypress/assets/23411447/3b25378e-958c-4cb6-a807-42921be27646)

### Desired behavior

The data attribute data-testid isn't visible in cypress.io UI. Where we need it most.

### Test code to reproduce

No code, it just isn't recognized when we go to the page using Cypress. See pictures

### Cypress Version

12.17.0

### Node version

18.17.0

### Operating System

Windows 11

### Debug Logs

```shell
I don't know where those are.
```

**Comment by rmnrdi** [comment]
I found out the issue, the cache was being stubborn and wouldn't clear.
I had to shut everything down, then clear the cache, local storage and disable caching the storage.

Only then would the new selectors show

**Comment by Yuri-Lima** [comment]
> I had to shut everything down, then clear the cache, local storage and disable caching the storage.

@rmnrdi 
Hi. Mas i am having the same issue. Where did you do the -> clear the cache, local storage and disable caching the storage.

I mean, it would be done when cypress open his ui interface or you mean in the normal browser like my local one?
