### ISSUE TITLE
Inconsistent behavior of cy.session clearing when test isolation is turned off.

### ISSUE THREAD

**Issue by jedieaston** [cypress-io/cypress#27430]
### Current behavior

Background: We use a pattern in our tests of looping over several sets of test data and creating a `describe` block for each, where there are several small `it` tests that rely on the same cookies being around, like so:

```
TestDataDefinitions.ActiveCases.forEach((case, index) => {
  describe(`Customer login for test case ${index}`, () => {
    /**
     * Login as a customer
     */
    before(() => {
      cy.login(case.credentials);
      cy.visit('/');
    });

    it('should successfully login as a customer', () => {
      cy.data('e2e', 'CustomerLandingPage_WelcomeMessage').should('contain', case.userFullName);
    });
  });
});

```

Since multiple tests need to share the same session data, I've turned off test isolation. 

Anyway, between describe blocks when we call our `login` command (which invokes `cy.session()` with a new test credential), _sometimes_ the session isn't cleared before it tries to log in, causing our login to fail because it verifies that we are starting without valid cookies. 

![image](https://github.com/cypress-io/cypress/assets/21368066/d7a8dca2-795a-43cb-b607-6f75b8088bbe)

(note that we are doing the same thing for all three cases, and if I re-run the tests sometimes the second one passes but the third one fails, sometimes they all pass, etc.)

It _might_ have something to do with our login process redirecting to a couple of pages one after the other, maybe sometimes Cypress doesn't clear the cookies for the right domain?

```
# clear cookies before failure, this is our app's site
2023-08-01T14:47:10.864Z cypress:server:socket-base automation:request clear:cookies [ { domain: 'my.dev.corp.symetra.com', <...> }}
# clear cookies before pass, we redirect to cognito when you aren't logged in
2023-08-01T14:47:19.011Z cypress:server:socket-base automation:request clear:cookies [ { domain: 'mode2hdev2.auth.us-west-2.amazoncognito.com'<...>
```

### Desired behavior

In this situation, I'd expect Cypress to act consistently, always clearing the local/session storage and cookies completely before attempting to create or restore a new session (or alternatively, never clearing it, and requiring test isolation to be enabled for that to work along with documentation to that effect. but sometimes it works, so I assume test isolation isn't a requirement).

Specifically, I suppose it should be clearing cookies for all domains visited during the test.

### Test code to reproduce

The test is the one given above, however, here's the login command: 

```
Cypress.Commands.add('login', (credentials: { name: string; password: string }) => {
  cy.session(
    [credentials.name, credentials.password],
    () => {
      cy.intercept('/v1/user/authorizations').as('authorizations');
      cy.visit('/');

      // wait for redirection to settle on the login page
      cy.wait('@authorizations').its('response.statusCode').should('eq', 401);
      cy.url().should('contain', '/nidp/saml2/sso');

      cy.get<HTMLInputElement>('input[name="Ecom_User_ID"]').type(credentials.name);
      cy.get<HTMLInputElement>('input[name="Ecom_Password').type(credentials.password);

      // submit credentials
      cy.get('[name="loginButton2"]').click();
      // }
      // wait for login process to complete
      cy.wait('@authorizations');
      cy.url().should('contain', '/dashboard/policy');
    },
    {
      validate: () => {
        // validate the session when it is restored to make sure the tokens are still good.
        cy.request('/v1/user/info').its('status').should('eq', 200);
      },
    }
  );
});
```

I can't provide app code, unfortunately, since the app isn't public. My guess is that this has little to do with the app though and is a Cypress bug (although, if there's something that it could be in the app I can try to make a small app to reproduce the bug). 

### Cypress Version

12.17.2

### Node version

16.20.0 (bundled version is 16.16.0 though)

### Operating System

Ubuntu 22.04 (WSL) and Windows 11 22H2. 

### Debug Logs

Attached below.

### Other

Doesn't seem to matter what browser or whether we are running interactively vs headless. 
Logs attached:
[test.log](https://github.com/cypress-io/cypress/files/12231216/test.log)

**Comment by nagash77** [comment]
Hi @jedieaston is there a reason for `cy.wait('@authorizations').its('response.statusCode').should('eq', 401);` to be checking for a 401 status code?  That would mean the request failed as unauthorized.  Your error message says the request returned a status code of 200 which means it succeeded (but the test fails because you were asserting that the status code should  be 401)

**Comment by jedieaston** [comment]
It's asserting 401 to make sure that we are redirecting to the login page (our app redirects to the login page upon getting a 401). Otherwise we'd have to do a long timeout on the line under that asserting the redirect.

It should be a 401 in this case, since no cookies should exist, since we're creating a new session.

**Comment by jedieaston** [comment]
Turns out this was a race condition with our app (we were starting a new session while XHR requests were in flight from the previous session, and those XHR responses sometimes had valid session cookies in them so they landed in the new session). It would be cool if Cypress could kill all of those requests somehow when starting a new session, but not a bug as such. Thanks.

**Comment by akus062381** [comment]
@jedieaston what did you end up doing to solve the race condition issue? I am running into this problem and I've spent a good chunk of time trying to find a fix. Thank you!

**Comment by pmcg86** [comment]
> Turns out this was a race condition with our app (we were starting a new session while XHR requests were in flight from the previous session, and those XHR responses sometimes had valid session cookies in them so they landed in the new session). It would be cool if Cypress could kill all of those requests somehow when starting a new session, but not a bug as such. Thanks.

Any chance you could share the fix for the race condition?
