### ISSUE TITLE
Chrome profile issue

### ISSUE THREAD

**Issue by dpunna-ut** [cypress-io/cypress#27432]
### Current behavior

Recently we have noticed for  Cypress version 12.17.0, every time when we run yarn cypress open it started complaining about select your google chrome profile before it launch on the browser. 

This was never an issue, this only started happening few weeks ago. Some of our company users facing this issue but not all of them, could you please confirm what is the cause of the issue?

### Desired behavior

Cypress should not ask for the chrome profile to login it should launch chrome in headed mode and run the tests

### Test code to reproduce

<img width="1251" alt="Screenshot 2023-07-31 at 22 06 54" src="https://github.com/cypress-io/cypress/assets/73844343/4277490b-67ca-43fd-912f-1dcd33831f8a">

![Screenshot 2023-07-31 at 21 38 03](https://github.com/cypress-io/cypress/assets/73844343/8d555879-9e0a-42bc-b9fc-56b8daa3088f)

![Screenshot 2023-07-31 at 21 43 43](https://github.com/cypress-io/cypress/assets/73844343/9fea9ab5-b460-4256-9461-8991dd89c2dc)

![Screenshot 2023-07-31 at 21 43 53](https://github.com/cypress-io/cypress/assets/73844343/b3660069-47ac-41f5-abe6-65ff7147c778)

### Cypress Version

12.17.0

### Node version

v16

### Operating System

macOS 13.4.1 (c) 
Processor 2.4 GHz 8-Core Intel Core i9

### Debug Logs

```shell
attached the screenshot
```

**Comment by nagash77** [comment]
Hi @dpunna-ut , we have not heard of this problem and I have not seen it myself either.  The screenshots seem to suggest there might be some administrator permissions needed in how your business is configuring your chrome browsers.  I would suggest you reach out to them to see if they have enacted any new policies.

**Comment by dpunna-ut** [comment]
> Hi @dpunna-ut , we have not heard of this problem and I have not seen it myself either. The screenshots seem to suggest there might be some administrator permissions needed in how your business is configuring your chrome browsers. I would suggest you reach out to them to see if they have enacted any new policies.

Thanks for the update. I will check with my IT and let you know. I will keep it open for now

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by ls-jacob-lawrence** [comment]
We have the same problem. 
It is indeed due to managed chrome profiles enacted by IT.

We've been using firefox for many months to work around this. Eventually we'll probably be pushed to electron due to new security features in firefox.

IT did try to give us guest profile access to help with Cypress, but Cypress doesn't seem to be able to connect to Chrome when Chrome is running in a guest profile, even when navigating directly to e.g., http://localhost:3000/__/#/specs
