### ISSUE TITLE
bug:  RangeError: The value of "offset" is out of range. regression

### ISSUE THREAD

**Issue by TeemuKoivisto** [cypress-io/cypress#27443]
### Current behavior

Cypress `12.17.3` all the way to `12.15.0` crashes at times using screenshots with `RangeError: The value of "offset" is out of range.` similar to these old bugs https://github.com/cypress-io/cypress/issues/2034 https://github.com/cypress-io/cypress/issues/8415

https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/actions/runs/5738092910/job/15550990695#step:5:468

However, using version `<=12.14.0` the tests pass so there must have been a regression introduced in `12.15.0` https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/actions/runs/5738388471/job/15551877605#step:5:495

It seems it could be a memory error, since removing tests from the test run can fix it.

### Desired behavior

Cypress should not throw `RangeError: The value of "offset" is out of range.`

### Test code to reproduce

Minimal reproduction is somewhat difficult to create but running tests in this branch https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/tree/cypress-bug should cause it.

1. `pnpm i`
2. `pnpm --filter prosemirror-dev-toolkit build`
3. `pnpm --filter site dev`
4. `pnpm --filter prosemirror-dev-toolkit test:e2e`

And downgrading to `12.14.0` should allow tests again to pass

### Cypress Version

12.17.3

### Node version

v18.13.0

### Operating System

macOS 12 and Linux

### Debug Logs

```shell
https://raw.githubusercontent.com/TeemuKoivisto/prosemirror-dev-toolkit/cypress-bug/packages/prosemirror-dev-toolkit/log-12.15.0.txt
```

**Comment by jordanpowell88** [comment]
@TeemuKoivisto thank you for taking the time to create this issue. I have validated that this does appear to be a regression that was introduced in `12.15.0` by [this PR](https://github.com/cypress-io/cypress/issues/25972). 

Fortunately, in the meantime you can follow [this guide](https://docs.cypress.io/api/plugins/browser-launch-api#Disable---headlessnew-for-Chrome) to disable `--headless=new` in Chrome `112+` and no longer receive this error.

**Comment by TeemuKoivisto** [comment]
@jordanpowell88 thanks for the swift response and validation! I'm in no hurry to upgrade my version so it's at the moment relatively minor inconvenience. It'd be nice though to have it fixed.

**Comment by jennifer-shehane** [comment]
@TeemuKoivisto I'm not able to recreate this bug with the branch provided. I get this error running it.
![Screenshot 2024-01-24 at 10 16 01 AM](https://github.com/cypress-io/cypress/assets/1271364/3f7b84a9-aa46-4c14-bf6c-d69bf36c9694)

**Comment by TeemuKoivisto** [comment]
Hey @jennifer-shehane yeah it seems something definitely has changed since the last time I ran them. Also the action logs have disappeared so can't really see what went wrong in the first place. Perhaps Chrome had some update, that's really the only thing that I can think of that has changed.

But happy though if it works now! I'll update this issue whether I see it popping up again.
