### ISSUE TITLE
My CypressTest runner is very slow and is getting stuck on "Your Tests are loading"

### ISSUE THREAD

**Issue by manpreet769630** [cypress-io/cypress#27451]
### Current behavior

My CypressTest runner is very slow and is getting stuck on "Your Tests are loading"
<img width="1335" alt="image" src="https://github.com/cypress-io/cypress/assets/99402804/6a8d0e71-33f2-4be6-8a73-b9c0f4e0a657">

### Desired behavior

On my other system it is working as expected and running smoothly

### Test code to reproduce

I am not using my code. I am using the default spec files

### Cypress Version

 12.17.3

### Node version

v16.15.0

### Operating System

MAC Os13.4.1 (c) (22F770820d)

**Comment by nagash77** [comment]
Hi @manpreet769630 , Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by manpreet769630** [comment]
Thank you Ben for your quick response!

Here are the debug logs, console error and screen recording:

*Debug Logs*:
https://docs.google.com/document/d/1wiU2yBCVrAePd0HGgIxAs-9jcCDchMigW2fJx3xq-AM/edit
*Console Error Logs: *
https://docs.google.com/document/d/1U8Q9NqwRzzK-NtPqW0pURXCqUuVixzd-h7K-rw_9X8U/edit
*Screen-Recording: *
https://www.loom.com/share/a87d6cb90b554cc5b9292f2068879417


Thanks and Regards,
Manpreet Singh Nagi

**Comment by CiaranDwyer** [comment]
Hi Guys,

I am getting the same as issue as above, I am also using a MAC on the same OS, Node, and Cypress version. I cannot seem to run any tests in a browser, I can only intermittently run my tests using headless mode!!! Can you advise ??

**Comment by manpreet769630** [comment]
Hello Team,

Is there any update on this?

**Comment by nagash77** [comment]
Hi @manpreet769630 looking at the logs it seems like something is closing the websocket before Cypress can connect to it.  Are you running any antivirus software?  Do you see the same behavior if you fork https://github.com/cypress-io/cypress-test-tiny and try running that?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by manpreet769630** [comment]
I am using Norton Antivirus
