### ISSUE TITLE
Unable to pass --js-flags to electron browser

### ISSUE THREAD

**Issue by FDIM** [cypress-io/cypress#27454]
### Current behavior

When I set env value `ELECTRON_EXTRA_LAUNCH_ARGS` to `--js-flags="--expose-gc --max-old-space-size=8192"` it is not correctly forwarded to the process.

Here is what I can see in process explorer:

```
"<redacted>AppData\Local\Cypress\Cache\12.7.0\Cypress\Cypress.exe" --type=renderer --user-data-dir="<redacted>AppData\Roaming\Cypress" --app-path="<redacted>AppData\Local\Cypress\Cache\12.7.0\Cypress\resources\app" --enable-sandbox --autoplay-policy=no-user-gesture-required --enable-precise-memory-info --use-fake-ui-for-media-stream --js-flags="\"--expose-gc" --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=6 --time-ticks-at-unix-epoch=-1691047945249108 --launch-time-ticks=17259285088 --mojo-platform-channel-handle=9644 --field-trial-handle=1724,i,7189473835567745350,10601196281146343367,131072 --disable-features=SpareRendererForSitePerProcess,WinRetrieveSuggestionsOnlyOnDemand /prefetch:1
```

Please note that `--js-flags` value is not formatted correctly to work.

### Desired behavior

I'd expect that all supported formats here: https://www.electronjs.org/docs/latest/api/command-line-switches#--js-flagsflags would work.

### Test code to reproduce

N/A

I don't want to sound pushy/bad, but looking at develop branch in environment.js, it is visible from code that multiple switches cannot be passed to the underlying process:

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/environment.js#L77

Excerpt:
```ts
if (process.env.ELECTRON_EXTRA_LAUNCH_ARGS) {
    const electronLaunchArguments = process.env.ELECTRON_EXTRA_LAUNCH_ARGS.split(' ')
```

It will split the value incorrectly. Maybe there could be a special workaround to pass it with semicolons instead.

### Cypress Version

12.7

### Node version

v18.15.0

### Operating System

Windows

### Other

I'm tinkering with this because one of our tests that involves huge form is crashing due to memory limit and there is no way for me to split it into multiple steps. 

I'm not able to use chrome/edge on the workstation in enterprise environment as the cypress extension is blocked and cannot be side loaded to chrome.

If it's OK, I could also work on a PR :) Seems like a somewhat straightforward change.

EDIT: Turns firefox consumed 8gb for the same test :(

**Comment by nagash77** [comment]
Hi @FDIM , thanks for submitting this ticket.  We would love to accept a PR for this functionality!  Check out our [Contributing guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) for details on that process.
