### ISSUE TITLE
Cypress report on pull request is not very elegant

### ISSUE THREAD

**Issue by MarcosPereira1** [cypress-io/cypress#27455]
### Current behavior

I have set up Cypress and I'm using Cypress Cloud. I noticed that the report during pull request execution is not very elegant. Is there any way we can improve this report?
![image](https://github.com/cypress-io/cypress/assets/100098827/c2c42e26-bbad-4210-a896-24be076953ee)

### Test code to reproduce

name: PR Tests End-to-End

on:
  push:
    branches:
      - main
      - beta
      - staging
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  install-dependencies-tests:
    runs-on: ubuntu-22.04
    steps:
      # ... (unchanged steps)

  run-unit-tests:
    needs: install-dependencies-tests
    runs-on: ubuntu-22.04
    steps:
      # ... (unchanged steps)

  run-cypress-tests:
    needs: install-dependencies-tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cypress_target: [smoke, critical]
      max-parallel: 2
    steps:
      # ... (unchanged steps)

      - name: Run Cypress Tests
        run: |
          yarn dev &
          sleep 5 
          yarn cypress run --record --key=${{ secrets.CYPRESS_RECORD_KEY }} --env grepTags=@${{ matrix.cypress_target }}

### Cypress Version

10.17.0

### Node version

16

### Operating System

Windows 10

**Comment by MikeMcC399** [comment]
@MarcosPereira1 

It looks like you may be using GitHub Actions, so the the documentation page

[Pull requests commit message is `merge SHA into SHA`](https://docs.cypress.io/guides/continuous-integration/github-actions#Pull-requests-commit-message-is-merge-SHA-into-SHA)

may be relevant and helpful to you.

You can also connect to the Cypress technical community on Discord to exchange experience on using Cypress

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button)

**Comment by ryanpei** [comment]
@MarcosPereira1 please let us know if the above suggestion works for you,

**Comment by MarcosPereira1** [comment]
@ryanpei  Thank you for the suggestion, I will test it here and come back to let you know if it worked.

**Comment by MarcosPereira1** [comment]
@MikeMcC399 @ryanpei Thank you very much, it worked.
