### ISSUE TITLE
Unused files warning

### ISSUE THREAD

**Issue by andreaslarssen** [cypress-io/cypress#27452]
### Current behavior

When the running command for component tests, I get several warnings like this:
```
[filename].ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

I've tried to resolve it by modifying my ts.config file, but nothing seems to help. When looking around to find a solution, I came across [this video](https://www.youtube.com/watch?v=R5bVnLc3RL4) from ng-conf. If you see around the e 17:58 mark, you'll notice that Jordan has the same issue as well.

### Desired behavior

Not complain

### Test code to reproduce

Set up the component tests through the GUI

### Cypress Version

12.17.2

### Node version

v16.17.1

### Operating System

Win10

**Comment by nagash77** [comment]
@andreaslarssen , just to confirm you are seeing warnings only correct?  Are these messages impeding your ability to run tests?

**Comment by andreaslarssen** [comment]
@nagash77 Yes, no
