### ISSUE TITLE
CT detect and support Svelte version 4

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#27465]
### What would you like?

Experimental support for Svelte 3 should be extended to support Svelte 4. (See npm module [svelte](https://www.npmjs.com/package/svelte).)

### Why is this needed?

Attempting to update to Svelte 4 with component testing shows a warning.

![image](https://github.com/cypress-io/cypress/assets/66998419/b517749d-bdfb-47ea-ae37-5fe2788f0192)

### Other

The example https://github.com/cypress-io/component-testing-quickstart-apps/tree/main/svelte runs successfully with Svelte 4, despite the warning.

**Comment by MikeMcC399** [comment]
- The Cypress documentation [Supported Frameworks](https://docs.cypress.io/guides/component-testing/overview#Supported-Frameworks) says that Svelte 3+ is supported, which implies that Svelte 4 would also be supported.

- There is a mismatch between software and documentation here. See also https://github.com/cypress-io/cypress-documentation/issues/5412

**Comment by lmiller1990** [comment]
Thanks for the report, should be fixed in https://github.com/cypress-io/cypress/pull/27473

**Comment by jennifer-shehane** [comment]
Released in [Cypress 13.0.0](https://docs.cypress.io/guides/references/changelog#13-0-0).
