### ISSUE TITLE
CT: Fix semver syntax in `dependencies.ts` file when defining CT frameworks

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress#27475]
File `packages/scaffold-config/src/dependencies.ts` uses improper syntax for many version ranges

`^=` is not technically valid and appears to work through a fluke of the library. Should just be `^` when defining compatible ranges. Update syntax and validate expected CT frameworks are still treated as supported.

**Comment by MikeMcC399** [comment]
This is about [packages/scaffold-config/src/dependencies.ts](https://github.com/cypress-io/cypress/blob/develop/packages/scaffold-config/src/dependencies.ts)  `minVersion`, for instance

https://github.com/cypress-io/cypress/blob/68a2976565042fc2352f53d062b895b509c877fb/packages/scaffold-config/src/dependencies.ts#L7

 used in https://github.com/cypress-io/cypress/blob/68a2976565042fc2352f53d062b895b509c877fb/packages/scaffold-config/src/frameworks.ts#L72-L74

As mentioned in https://github.com/cypress-io/cypress/pull/27473#discussion_r1285594585

[node-semver > versions](https://github.com/npm/node-semver#versions) states

> A leading "=" or "v" character is stripped off and ignored.

so the "=" does not belong in the syntax, however it does not appear to cause any harm (apart from possibly being confusing to the human reader🙂)! Nevertheless it should probably be cleaned up.

**Comment by MikeMcC399** [comment]
@DevJSter 

Was your post created by AI, like ChatGPT? It seems that your post is in answer to a question which was not raised here. Dependency resolution is not relevant at the scaffolding stage.

Did you consult the relevant npm package [node-semver > README](https://github.com/npm/node-semver) before you posted?

Edit: The post referred to here has since been deleted.

**Comment by MikeMcC399** [comment]
@mike-plummer 

- PR #28152 from @jordanpowell88 corrected the syntax in [packages/scaffold-config/src/dependencies.ts](https://github.com/cypress-io/cypress/blob/develop/packages/scaffold-config/src/dependencies.ts)

There are no more occurrences of the incorrect syntax `^=` in that source file, so this issue can be closed.

The issue should be mentioned in the [CHANGELOG.md](https://github.com/cypress-io/cypress/blob/develop/cli/CHANGELOG.md) as being resolved.
