### ISSUE TITLE
cypress viewport not changing via command line in newer cypress versions

### ISSUE THREAD

**Issue by lucasbeninca** [cypress-io/cypress#27478]
### Current behavior

I've noticed that when I specify a viewport in the **cypress.config.js** file, even when running the command `cypress open --config viewportWidth=410 viewportHeight=880`, it doesn't overwrite correctly. However, when I remove the viewport from the **cypress.config.js** file, I can successfully overwrite it via the command line without any issues. Is this the expected behavior, or should I be able to change it even when a viewport is defined in **cypress.config.js**?

### Desired Behavior

What I expected was that Cypress would adjust the viewport to the dimensions defined in the command line: `cypress open --config viewportWidth=410 viewportHeight=880`.

### Test Code to Reproduce

The following repository can be used as an example: [https://github.com/lucasbeninca/cypress-basico-v2](https://github.com/lucasbeninca/cypress-basico-v2). It has a viewport specified in the cypress.config.js file as shown in image 1 and can be used as a reference for the scripts defined in package.json (image 2).

![Image 1](https://github.com/cypress-io/cypress/assets/27087257/30bfd82c-586d-45a8-9642-36874b94a64d)
![Image 2](https://github.com/cypress-io/cypress/assets/27087257/3572314f-d088-49bf-b39a-87fc1e238ee3)

**I've verified that in Cypress version 9.5.1, the behavior is as expected, and the viewport is indeed replaced by the dimensions provided in the command line.**

### Cypress Version

12.17.3

### Node Version

v18.16.1

### Operating System

Windows 10 Home 19045.3271

**Comment by wlsf82** [comment]
Same here using macOS Ventura 13.4.1 (c).

Cc. @emilyrohrbough.

**Comment by nagash77** [comment]
Hi @lucasbeninca as far as I know the command line arguments should take precedence if both are present.  Thanks for reporting this issue.

**Comment by wlsf82** [comment]
@nagash77 and @lucasbeninca, I've some new information.

If the viewports are configured globally (see below), not specifically for `e2e`, then the command line correctly overrides the config file viewports.

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  viewportHeight: 880,
  viewportWidth: 1280,
  e2e: {},
})

```

And as per the docs (on the [Default sizing page](https://docs.cypress.io/api/commands/viewport#Default-sizing)), it appears that the viewports are really global configurations, not `e2e` or `component` related.

**Comment by lucasbeninca** [comment]
That's correct. I just checked it in my project. When configuring the viewport globally, the transition to the command line view actually takes place. In this scenario, I no longer see the need to address this issue unless you have some other points to discuss. I will consider it resolved.

**Comment by wlsf82** [comment]
> That's correct. I just checked it in my project. When configuring the viewport globally, the transition to the command line view actually takes place. In this scenario, I no longer see the need to address this issue unless you have some other points to discuss. I will consider it resolved.

Cc. @emilyrohrbough
