### ISSUE TITLE
Could not resolve "@angular-devkit/build-angular/src/tools/webpack/configs/common.js"

### ISSUE THREAD

**Issue by Giusort** [cypress-io/cypress#27488]
### Current behavior

Running

npx cypress run --component

or using the component testing wizard with

npx cypress open

execution fails with this message:

Error: Could not resolve "@angular-devkit/build-angular/src/tools/webpack/configs/common.js". Do you have "@angular-devkit/build-angular" and "@angular-devkit/core" installed?

### Desired behavior

Run with no error.

### Test code to reproduce

devDependencies": {
    "@angular-devkit/build-angular": "~15.2.9",
    "@angular-devkit/core": "^16.1.4",
    "@angular/cli": "^15.2.9",
    "@angular/compiler-cli": "15.2.9",
    "@angular/language-service": "^15.2.9",
    "@types/dragula": "^2.1.33",
    "@types/file-saver": "^2.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "^2.0.6",
    "@types/jquery": "^3.3.29",
    "@types/knockout": "^3.4.65",
    "@types/lodash": "^4.14.121",
    "@types/node": "12.12.6",
    "@types/requirejs": "^2.1.31",
    "@types/xml2js": "^0.4.5",
    "cypress": "^12.17.3",
    "gitex-flow": "^2.3.8",
    "grunt-cli": "^1.4.3",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^15.2.2",
    "node-sass": "^8.0.0",
    "sonar-scanner": "^3.1.0",
    "ts-node": "^7.0.1",
    "tslint": "~6.1.0",
    "typescript": "^4.8.2"
  }

### Cypress Version

12.17.3

### Node version

14.20.1 / 16.20.1

### Operating System

Windows 10 (18362.1256)

### Debug Logs

```shell
DevTools listening on ws://127.0.0.1:59400/devtools/browser/b78f113b-a25a-488d-a42b-76f3f7b80dfb
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

Error: Could not resolve "@angular-devkit/build-angular/src/tools/webpack/configs/common.js". Do you have "@angular-devkit/build-angular" and "@angular-devkit/core" installed?
    at Local\Cypress\Cache\12.17.3\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:106:19
    at Array.map (<anonymous>)
    at getAngularCliModules (Local\Cypress\Cache\12.17.3\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:100:151)
    at async getAngularCliWebpackConfig (Local\Cypress\Cache\12.17.3\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:159:101)
    at async angularHandler (Local\Cypress\Cache\12.17.3\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:205:27)
    at async getPreset (Local\Cypress\Cache\12.17.3\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:91:20)
    at async Function.devServer.create (Local\Cypress\Cache\12.17.3\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:108:61)
    at async Local\Cypress\Cache\12.17.3\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:25:24
```

### Other

It seems the same as in #27049

**Comment by MikeMcC399** [comment]
@Giusort 

The Angular 15 example on https://github.com/cypress-io/cypress-component-testing-apps/tree/main/angular runs correctly with Cypress `12.7.0` and with `12.17.3`.

You may like to compare with your repo.

Note Node.js `14` can no longer be recommended, since it already reached its [end-of-life](https://github.com/nodejs/release#release-schedule) earlier this year.

**Comment by MikeMcC399** [comment]
@Giusort 

It would probably require a repro example posted to a fork of https://github.com/cypress-io/cypress-test-tiny in order to investigate this issue further as the excerpt of your `package.json` file is not sufficient to reproduce your problem. It would need your lock file from whichever package manager you are using and your Cypress config files as well. Before posting individual files, a complete simple reproduction would be much better.

Using `"@angular-devkit/core": "^16.1.4",` together with Angular `15` dependencies may be causing an issue here.

**Comment by Giusort** [comment]
> Using `"@angular-devkit/core": "^16.1.4",` together with Angular `15` dependencies may be causing an issue here.

Bingo!

Thank you @MikeMcC399 !
