### ISSUE TITLE
Network tab and cypress route reporting different request payloads

### ISSUE THREAD

**Issue by peterscottsa** [cypress-io/cypress#2749]
### Current behavior:

I'm trying to write a test that checks if a request is made with certain parameter in the request body. However the assertion fails even though in the network tab, the property is actually there.

From the cypress logs
`{ categoryId: null }`

From the network tab in the console:
`{ categoryId: '12345-5678' }`

I have the following assertion:

```js
cy.wait('@expenses_post').then( req => {
            const request = req.requestBody
            console.log(request.categoryId) <---- Reports null, even though it has a value in the network tab
            expect(request.categoryId).to.not.be.null
        })
```

I have triple checked the route, its the only request and it matches correctly. Does anyone know why this is happening?

### Desired behavior:

`request.body.categoryId` should have a value, cypress does not see it. The test fails

### Versions
3.1.1, High Sierra

**Comment by jennifer-shehane** [comment]
Hey @peterscottsa, I don't see anything that seems wrong with the current test code provided. 

Is there more than 1 request that may be matching? So that 1 is returning null and the other the categoryId?

Either way, we would need more test code or a reproducible example to track this down.

**Comment by peterscottsa** [comment]
@jennifer-shehane I suspect that this might be something on my side, honestly I am not sure how to reproduce this so I will close for now. Thanks anyway though :)
