### ISSUE TITLE
Move check-ts step away from Gulp and cache

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#27491]
Currently we run `check-ts` using a Gulp task named `checkTs`. This is undesirable for a few reasons:
- Running this step checks the TS types for every single package that has a `check-ts` script defined **every single time** even if the package's source code hasn't changed
- Each step runs sequentially

The result is that this check takes a long time (see [this example](https://app.circleci.com/pipelines/github/cypress-io/cypress/55225/workflows/1251245f-55d1-4ab1-b2af-d0959fea1446/jobs/2285083) from `develop`, where checking types takes almost 8 minutes).

Remove this task from Gulp and run it with Lerna (Nx) in a way that
- caches the output of the task for each package so that the check only runs if the source code has changed
- runs the TS checks in parallel to speed up the runs

**Comment by lmiller1990** [comment]
What is worse is due to circular deps, the same code is ts-checked many times - you often get the same TS error for the same code multiple times, once for each repo that imports it.
