### ISSUE TITLE
Verbiage on `visible` error message is wrong when asserting an element to NOT be visible

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#275]
The sentence "Cypress could not determine why this element is **not** visible" does not make sense when the actual assertion is for the element to not be visible. The element is actually visible at the time of error.

**Example Test Code**

``` javascript
cy.get('.modal-content').should('not.be.visible')
```

**Command Log Screenshot**
![screen shot 2016-10-24 at 10 58 44 am](https://cloud.githubusercontent.com/assets/1271364/19652973/c931ba06-99e0-11e6-985f-f87945892492.png)

**Comment by brian-mann** [comment]
Fixed in [`0.17.10`](https://github.com/cypress-io/cypress/wiki/Changelog#01710-11072016).
