### ISSUE TITLE
Angular Component Test: Load asset for Image not working

### ISSUE THREAD

**Issue by B34v0n** [cypress-io/cypress#27529]
### Current behavior

Currently, assets for images are not loaded correctly.
The image is located in a sister-folder to my Angular-Code. (I need that in my specific case).
It is used like following:
`<img src="../icons/test.gif" alt="patrick" title="patrick" />`

But it is also reproducable in the asset folder.

In the angular.json I added the picture like so:
```json
"assets": [
  "src/favicon.ico",
  {
    "glob": "*",
    "input": "../icons",
    "output": "icons"
  },
  "src/assets"
],
```
I tried the same in the cypress.config.ts, but neither works.

I always get a 404-Error `GET http://localhost:8080/__cypress/icons/test.gif 404 (Not Found)`
(or with the picture in the asset folder and no ../ path: `GET http://localhost:8080/__cypress/src/assets/test.gif 404 (Not Found)`
The testpage looks like this:
![image](https://github.com/cypress-io/cypress/assets/88542001/3dfbdf1f-15b5-4e76-b218-729fbe010097)
while in the Angular-App (with ng serve) it looks like this:
![image](https://github.com/cypress-io/cypress/assets/88542001/04e945e4-6a11-4cd0-aa47-017d02975e68)

It kinda relates to https://github.com/cypress-io/cypress/issues/24361, but the solution there didn't work for me.

### Desired behavior

The image should be loaded and shown correctly. It should work like in the regular Angular-app.

### Test code to reproduce

I created a small reproduceable example:
https://github.com/B34v0n/CypressAssetTest

The Test works, but the image (gif) is not rendered and the 404-Error is shown.

### Cypress Version

12.17.3

### Node version

v18.17.0

### Operating System

Windows 11 22H2

### Other

Kind of related to https://github.com/cypress-io/cypress/issues/24361

**Comment by jordanpowell88** [comment]
Hey @B34v0n thanks for opening this issue. I took a look at this and it appears that your asset path is incorrect in your code example. Your `angular.json` assets set `./icons` to `../icons` and then your `img src` is trying to go back a path as well. If you load the image using like `<img src="icons/test.gif" alt="patrick" title="patrick" />` it works as expected. 

We do have a [PR](https://github.com/cypress-io/cypress/pull/26844) that will landing in `cypress 13` that will add support for relative paths so you can do the following:

![Screenshot 2023-08-11 at 11 14 20 AM](https://github.com/cypress-io/cypress/assets/3605268/aa8b3a06-4d13-433c-8a6d-4fe52ee0e399)


It does appear that Angular is resolving incorrect paths which is something we could consider doing in the future but the immediate fix would be to set your image source to something like `icons/test.gif`

**Comment by B34v0n** [comment]
Hi @jordanpowell88, thank you for the fix. Now I feel like patrick in the gif.
With the changed path it works like a charm. Thank you very much.
