### ISSUE TITLE
assert error in should('have.text','your text here')

### ISSUE THREAD

**Issue by lucasbeninca** [cypress-io/cypress#27527]
### Current behavior

I have observed that when making assertions on an element using `cy.get().should('have.text', 'your text here')`, where I provide a valid element in the `get` command and an exact text matching what I see in the HTML, Cypress interprets it as incorrect.

html pure  github: 
![image](https://github.com/cypress-io/cypress/assets/27087257/54825329-b185-47fd-b8ba-d6f2e9a994be)

### Desired behavior

The verification process should be straightforward: if the GitHub page contains the specified text and the text extracted from the HTML matches the parameter in the `should('have.text', 'your text')` assertion, Cypress should consider the verification successful. However, in my experience, Cypress marks the verification as incorrect and the test fails, despite the text being an exact match.

### Test code to reproduce

You can find the test code at the following GitHub repository: https://github.com/lucasbeninca/cyFrame 

### Cypress Version

12.17.3

### Node version

v18.16.1

### Operating System

Windows 10 home 19045.3271

**Comment by B34v0n** [comment]
I had the same problems a while ago, but it kinda looks like there is an extra space at the end.
Either you add that space in your expected text or you use `should.contain`, then the extra spaces are irrelevant

Here you can see, that there is one space more in the original text, than in your expected text:
![image](https://github.com/cypress-io/cypress/assets/88542001/22070b01-e1bb-40ee-a001-9cfb237b8b09)

**Comment by lucasbeninca** [comment]
eu tive umproblema parecido utilizando o contais em outra aplicação que possui ifram: 
![1a711018-1989-4cf8-b608-c065e60e3bb7](https://github.com/cypress-io/cypress/assets/27087257/59777dff-9d8d-4dc9-996e-c0628db7d461)
vou verificar isso, referente ao espaço ou tentar fazer algo com then expect

**Comment by lucasbeninca** [comment]
> I had the same problems a while ago, but it kinda looks like there is an extra space at the end. Either you add that space in your expected text or you use `should.contain`, then the extra spaces are irrelevant
> 
> Here you can see, that there is one space more in the original text, than in your expected text: ![image](https://user-images.githubusercontent.com/88542001/259954195-22070b01-e1bb-40ee-a001-9cfb237b8b09.png)

even with the additional space the error persists, what makes me thoughtful is the fact that cypress returns me in the log the value found equal to the expected value
![image](https://github.com/cypress-io/cypress/assets/27087257/65f0231f-e85f-49f5-b628-12f3fdd53926)

**Comment by cooperelly** [comment]
I've just copied the text found by Cypress, inserted it in .should('have.text', '\n        \n          This branch is 5 commits ahead of wlsf82:main.\n        \n  ') and test passed:
![image](https://github.com/cypress-io/cypress/assets/78543595/e924604c-e5cb-4960-a690-8860c253b74b)


Just copy it as it is from this AssertionError:
![image](https://github.com/cypress-io/cypress/assets/78543595/4f40b5db-4a66-4abf-aaf6-767b34e3e425)

Do not copy it from here:
![image](https://github.com/cypress-io/cypress/assets/78543595/3cf8d1e6-b351-4f9e-b037-3fa463bc00ce)

**Comment by lucasbeninca** [comment]
I had already worked around the situation and I wanted to forget to change it here, but thank you very much for your contribution and I will close @cooperativamente
