### ISSUE TITLE
I am unable to install cypress with error

### ISSUE THREAD

**Issue by ejjaganisairam** [cypress-io/cypress#27530]
I am unable to install cypress with error 

npm ERR! code 1
npm ERR! path D:\cypress\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! Installing Cypress (version: 12.17.3)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be downloaded.

_Originally posted by @ejjaganisairam in https://github.com/cypress-io/cypress/issues/19250#issuecomment-1674519810_

**Comment by MikeMcC399** [comment]
@ejjaganisairam 

Please check your network connection and as a test try to download Cypress from https://download.cypress.io. You should be offered a file `cypress.zip` to download.

**Comment by KRajeshBabu** [comment]
Facing same issue and details were same as above. 
Here are my environment details, 

Error:
npm ERR! code 1
npm ERR! path C:\ProgramData\aatestautomation\ui_automation\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! Installing Cypress (version: 10.11.0)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! node:assert:124
npm ERR!   throw new AssertionError(obj);
npm ERR!   ^
npm ERR!
npm ERR! AssertionError [ERR_ASSERTION]: 273 == 0
npm ERR!     at ClientRequest.onConnect (C:\ProgramData\aatestautomation\ui_automation\node_modules\tunnel-agent\index.js:160:14)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at Socket.socketOnData (node:_http_client:582:11)
npm ERR!     at Socket.emit (node:events:513:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR!     at Readable.push (node:internal/streams/readable:234:10)
npm ERR!     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
npm ERR!   generatedMessage: true,
npm ERR!   code: 'ERR_ASSERTION',
npm ERR!   actual: 273,
npm ERR!   expected: 0,
npm ERR!   operator: '=='
npm ERR! }
npm ERR!
npm ERR! Node.js v18.15.0

Node: v18.15.0
NPM: 9.8.1
Cypress as in package.json: ^10.10.0

**Comment by MikeMcC399** [comment]
@KRajeshBabu 

You have a different error message with a different version of Cypress, so I suggest that you don't try to combine your problem with the original issue.  Instead you should open a new issue and provide all the information which the issue template asks for.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
