### ISSUE TITLE
Chromium renderer crashed cypress ci error

### ISSUE THREAD

**Issue by adit-shah-devrev** [cypress-io/cypress#27544]
### Test code to reproduce

It's fails in my production app in circleci. I can't really share it here.

### Cypress Mode

cypress run

### Cypress Version

12.17.0

### Browser Version

Chrome 115 (headless)  

### Node version

v18.14.2

### Operating System

linux v1.24.15-eks-a5565ad

### Memory Debug Logs

```shell
CYPRESS_INTERNAL_MEMORY_SAVE_STATS is not working. Is it part of public API?
```

**Comment by nagash77** [comment]
Unfortunately there is not enough information for us to move forward with this ticket. I am going to close this until such time that a reproducible example can be shared.
