### ISSUE TITLE
rounding large numbers up in json

### ISSUE THREAD

**Issue by DavesPlanet** [cypress-io/cypress#27543]
### Current behavior

If you create a web server which returns "Content-Type", "application/json" with body

{"myJsonId":709101314839936238,"myOtherNumber":878582244564511966}

and manually test it from multiple locations (browsers, postman, unit tests) and it looks perfect, but in cypress the numbers will round to 709101314839936300 and 878582244564512000

the following code
    cy.request({
      method: "GET",
      url: "http://localhost:8080/hello"
    }).then(response => {
      cy.log(JSON.stringify(response.body))
    });

will log this:

request GET 200 http://localhost:8080/v1/hello
log {"myJsonId":709101314839936300,"myOtherNumber":878582244564512000}

### Desired behavior

not modify the value of json numbers

### Test code to reproduce

create a web server that returns  "Content-Type", "application/json" with body

{"myJsonId":709101314839936238,"myOtherNumber":878582244564511966}

create the following in a cypress test

    cy.request({
      method: "GET",
      url: "http://localhost:8080/hello"
    }).then(response => {
      cy.log(JSON.stringify(response.body))
    });

### Cypress Version

12.17.3

### Node version

v16.13.1

### Operating System

Windows 10

### Debug Logs

```shell
I followed the instructions to create the logs and I get this error when posting the issue:

There was an error creating your issue: body is too long, body is too long (maximum is 65536 characters).

The results of the cypress run for just this one test was 250k
```

**Comment by MikeMcC399** [comment]
@DavesPlanet 

You have probably hit the precision limit for the [JavaScript `Number`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#number_encoding) data type, which the documentation states is about 15 to 17 decimal places.

Could you use a [`String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) instead?

**Comment by DavesPlanet** [comment]
They are unsigned int 64, a common key in some simple nosql databases. I got the code working in dev mode by switching the key generator to uint32. I completely agree it is because they are too large, but when I view it in chrome or anything else it gives me back the raw text of the json unmodified. In the demo I am dumping the entire json text body and cypress has manipulated small bits of my overall payload. Took a very long time to notice that minor changes in the IDs were the  reason for test failures. Took longer to prove it was because of cypress and to convince myself I wasn't crazy and the test framework was really making subtle changes to my ids before I even tried to parse the json.

**Comment by DavesPlanet** [comment]
They are unsigned int 64, a common key in some simple nosql databases. I got the code working in dev mode by switching the key generator to uint32. I completely agree it is because they are too large, but when I view it in chrome or anything else it gives me back the raw text of the json unmodified. In the demo I am dumping the entire json text body and cypress has manipulated small bits of my overall payload. Took a very long time to notice that minor changes in the IDs were the  reason for test failures. Took longer to prove it was because of cypress and to convince myself I wasn't crazy and the test framework was really making subtle changes to my ids before I even tried to parse the json.

**Comment by MikeMcC399** [comment]
@DavesPlanet 

I'm not sure what Cypress could do about this, since if I just put your expression into the Console of Google Chrome Dev Tools, then I get the same result, so Cypress has basically no influence on this:


![Image](https://github.com/cypress-io/cypress/assets/66998419/79643cb0-ec6a-4925-806f-09a7fffc0566)


or am I completely missing something here?

**Comment by DavesPlanet** [comment]
Mike, that is so cool, thanks for doing that! You matched **exactly** what I was seeing. I can only assume that cypress is delivering a fully intact payload to my test and my use of JSON.stringify caused the error. Assigning the values to variables also causes this error. Cypress did its job and it is a limitation of javascript to handle it. This also tells me I would have run into issues trying to parse the javascript later on in a frontend app. Thank you again for helping me understand exactly where the issue is happening.
