### ISSUE TITLE
Wrong element tested in not.exist assertion

### ISSUE THREAD

**Issue by tpict** [cypress-io/cypress#27556]
### Current behavior

A failing `should("not.exist")` assertion is seemingly testing an element unrelated to the one the assertion was made against. Here's a screenshot–should make sense with the test code below

![Untitled](https://github.com/cypress-io/cypress/assets/12588098/fec98319-401d-472d-bbb0-6756e91fa70f)

### Desired behavior

Make the assertion against the right element.

### Test code to reproduce

Install React and run this as a component test:

```tsx
import { useEffect, useRef, useState } from "react";

const ExampleComponent: React.FC = function () {
  const [isOpen, setOpen] = useState(false);
  const dialogRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const dialogElement = dialogRef.current;
    if (!dialogElement) {
      return;
    }

    function handleClickOutside(event: PointerEvent): void {
      if (isOpen && !dialogElement?.contains(event.target as HTMLElement)) {
        setOpen(false);
        event.preventDefault();
        event.stopPropagation();
      }
    }

    document.body.addEventListener("pointerdown", handleClickOutside, true);
    return () =>
      document.body.removeEventListener(
        "pointerdown",
        handleClickOutside,
        true,
      );
  }, [isOpen]);

  return (
    <>
      <button id="open" onClick={() => setOpen(true)}>
        Open me
      </button>
      {isOpen && (
        <div ref={dialogRef} role="dialog" aria-label="Look at me" id="dialog">
          Hello
        </div>
      )}
    </>
  );
};

describe("Weirdness", () => {
  it("exists", () => {
    cy.mount(
      <>
        <ExampleComponent />
        <button id="outside">I&apos;m outside</button>
      </>,
    );

    cy.get("#open").click();
    const dialog = cy.get("#dialog");
    cy.get("#outside").click();
    dialog.should("not.exist");
  });
});
```

### Cypress Version

12.17.3

### Node version

18.15.0

### Operating System

macOS 13.4

### Other

Adding a short `cy.wait` before the assertion fixes the issue.

I guess it could be a React reconciliation issue? Apologies if so

**Comment by jennifer-shehane** [comment]
@tpict Please read out getting started docs. You can’t assign const to Cypress chains in this way since the commands are Promise like. You’ll want to use our alias command instead.
