### ISSUE TITLE
Cypress fails to verify start up and gives a JavaScript Error of EBADF

### ISSUE THREAD

**Issue by thomas-m-andrus** [cypress-io/cypress#2756]
### Current behavior:
When I try to run ./node_modules/.bin/cypress run, I receive the following error
![image](https://user-images.githubusercontent.com/7082603/48288872-31840200-e433-11e8-9b53-d5902b6c5a9e.png)

I am running windows 10, I have deleted and installed cypress multiple times without any success. I can access the program going into \AppData\Local\Cypress\Cache\3.1.1\Cypress and clicking on the icon. But when I try to do run or verify from the command line with the node_modules, it gives me that error message.

### Desired behavior:

I would like cypress to start up normally.

### Steps to reproduce:
./node_modules/.bin/cypress run

### Versions

3.1.1, windows 10, google chrome

**Comment by thomas-m-andrus** [comment]
Here Is the full error:
![image](https://user-images.githubusercontent.com/7082603/48290034-1b784080-e437-11e8-9b42-bdcfdf01137a.png)

**Comment by jennifer-shehane** [comment]
@thomas-m-andrus Does your `node_modules` folder still exist within the directory you tried to run this within? Did they get deleted somehow?

**Comment by thomas-m-andrus** [comment]
Hey Jennifer,

No, the node_modules folder still exists with both the cypress folder and the .bin cypress command. I have tried uninstalling and reinstalling cypress multiple times. I tried creating a pure new project with cypress and running it but I still encounter the same issue. 

When I run the .bin/cypress run command, it states this is my first time using cypress, it then tries to verify and that is when the error occurs. I feel that it is probably an error with my installation of cypress, but I just can’t figure out where the error is. Because the error message is being outputed to the error box, I am having trouble figuring out the location or command of what the issue is.

I hope that helps, let me know if I can provide more clarification. Thank you for your time and a consideration!

**Comment by thomas-m-andrus** [comment]
Okay, I just tried it again and for some reason it is now working, I did uninstall vscode, but I don't really think that had anything to do with it. If it is still working tomorrow morning, I will close this issue. Thank you Jennifer for assisting me!

**Comment by jennifer-shehane** [comment]
Ok, if you encounter it again - before running the command try running it with debug logs:

```
setx DEBUG "cypress/*"
```

**Comment by thomas-m-andrus** [comment]
Thank you very much, it seems to be working now, but I will do that first if I run into the problem again. Thank you for the assistance!

Tom
