### ISSUE TITLE
.Find command is not working with cy.xpath.

### ISSUE THREAD

**Issue by PRAMENDER23** [cypress-io/cypress#27580]
### Current behavior

I am trying to use find chained with xpath:
cy.xpath('xpath).find('.class'), But its not finding the class here.

### Desired behavior

It should find the class name.

### Test code to reproduce

cy.xpath('xpath).find('.class')

### Cypress Version

12.2.0

### Node version

18.17.0

### Operating System

Windows10

**Comment by nagash77** [comment]
I noticed you are missing a closing quote in your command.  Perhaps that is causing your problem?

**Comment by jennifer-shehane** [comment]
We no longer are supporting cy.xpath. Closing.
