### ISSUE TITLE
Adding new test file results in "No tests found"

### ISSUE THREAD

**Issue by prudhvi-sdet** [cypress-io/cypress#27588]
### Current behavior

Whenever i do whatever change to spec file, cypress will not pick up those changes and will execute older version of code in spec file. Also, if I create new spec file and open in cypress run then getting 'No test found'

### Test code to reproduce

N/A

### Cypress Version

12.17.3

### Node version

v16.14.0

### Operating System

macOS ventura 13.5

**Comment by nagash77** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will consider reopening the issue.

Check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
