### ISSUE TITLE
Please update to latest Electron version

### ISSUE THREAD

**Issue by eugenet8k** [cypress-io/cypress#27587]
### Current behavior

We are having issues with Chrome 106 which is part of the built-in to Cypress Electron, which was released a year ago. The issue is with creating PNG snapshots in the built-in Electron browser for long pages, there is a visual distortion in the end. It seems the tool concatenates pieces losing 30-40px of data etc.

### Desired behavior

It is only observed in the built-in Electron, whereas with the latest external Chrome or Chromium, there is no such issue. We would use an external browser, but we run in ARM env and there is a known problem that Chrome is not built for ARM64 still. So having Cypress natively using Electron is a big help, but the version is very outdated as mentioned.

### Test code to reproduce

Just install it and see

### Cypress Version

12.17.3

### Node version

16.13.0

### Operating System

macOS  and Linux

**Comment by MikeMcC399** [comment]
@eugenet8k 

You did not give any details of what problem you are seeing, so it's difficult to know if an Electron update would help you. Cypress `12.17.4` bundles [Electron version `21.0.0`](https://releases.electronjs.org/release/v21.0.0). `v106` is the associated Electron version shown in the Cypress desktop app.

You can test against a newer version of Chrome. See [Cypress > Guides > Launching browsers](https://docs.cypress.io/guides/guides/launching-browsers).

**Comment by nagash77** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will consider reopening the issue.

**Comment by eugenet8k** [comment]
@MikeMcC399 @nagash77 Thank you for the quick response. I have added the details. I got the impression that updating a year-old dependency is trivial, but I see your point. Sorry for missing information ahead of time.

**Comment by nagash77** [comment]
Updating dependancies can be tricky depending on what changed and is required to upgrade.  But you are in luck and we are currently working on upgrading the version of Electron within Cypress.  It may be a couple of weeks before it is released though so hang in there.

**Comment by eugenet8k** [comment]
Thank you @nagash77 we will gladly wait. I tried to use external Chrome, but you get into a vicious play with Docker and realization that installing Chrome on a Linux ARM64 container is hell. Google still does not publish ARM builds, so it's not a part of `puppeteer` and generally is a major downer. Cypress is a godsend with having built-in Electron, but it's pretty old now, hence my ticket.

Thank you for the good news.
