### ISSUE TITLE
ViewPort is not setting the view of the page according to parameters

### ISSUE THREAD

**Issue by jbonnin-pcty** [cypress-io/cypress#27581]
### What would you like?

For Cypress to implement things necessary for mobile viewing

### Why is this needed?

Because "Over 55% of website traffic comes from mobile devices. 92.3% of internet users access the internet using a mobile phone. There are approximately 4.32 billion active mobile internet users." Source: https://explodingtopics.com/blog/mobile-internet-traffic

### Other

I found this other issue: https://github.com/cypress-io/cypress/issues/5398

It went from ready to work -> closed, and I have the latest Cypress but I still don't get it to work and any site I visit will show the same cropped view, not a responsive view

**Comment by nagash77** [comment]
Hi @jbonnin-pcty is there a specific use case that you are trying to test that you cannot?  Have you read [this article](https://www.cypress.io/blog/2020/07/08/end-to-end-testing-mobile-apps-with-ionic-and-cypress/) about testing mobile apps that might have some approaches that are helpful for your situation?

**Comment by jbonnin-pcty** [comment]
Hello @nagash77, thank you for your fast reply! I saw this article while researching this topic but dismissed it because it read 'End-to-end Testing Mobile Apps', and I don't need to test a mobile app (as in an application that a user would download from the Google Store / App Store), but I would like to go on some website with Cypress and check its responsiveness, as if I was a user on a mobile.

After reading the article, I am confused, can Ionic help me achieve that? If yes, this issue can be closed and my bad for not understanding it earlier 

**Edit:** tried it the next day work, and it's what I needed, thank you!

**Comment by jbonnin-pcty** [comment]
The tool mentioned by @nagash77 works for me

**Comment by jbonnin-pcty** [comment]
The tool mentioned by @nagash77 works for me
