### ISSUE TITLE
Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.

### ISSUE THREAD

**Issue by dustinhorton** [cypress-io/cypress#2761]
It seems like the combo of Cypress/Electron doesn't like:

```js
window.scrollTo({
   behavior: 'smooth',
   top: 0,
})
```

as I get this error:

```console
Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.
```

To get around this, I'm currently doing:

```javascript
try {
  window.scroll({
    behavior: 'smooth',
    top: 0,
  })
} catch(err) {
  if (err instanceof TypeError) {
    window.scroll(0, 0)
  } else {
    throw err
  }
}
```

### Current behavior:

```
Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
  Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.
  
  This error originated from your application code, not from Cypress.
  
  When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
  
  This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.
```

### Desired behavior:

Similar behavior to Chrome—work without error.

### Steps to reproduce:

Run a headless test on code that has the following:

```javascript
window.scrollTo({
   behavior: 'smooth',
   top: 0,
})
```

### Versions

```
"cypress": "^3.1.1",
```

**Comment by Uniiq** [comment]
I have the same problem with cypress version 3.1.1. So i decided to stay at cypress version 3.1.0.

**Comment by dustinhorton** [comment]
Tried downgrading but no change for me.

**Comment by chrisbreiding** [comment]
This looks like a browser support issue. Cypress currently uses a version of Electron that uses Chrome 59. As far as I can tell, support for smooth-scrolling landed in Chrome 61. We'll be upgrading Electron and its Chrome version in the future, which will fix this.

**Comment by dustinhorton** [comment]
Thanks @chrisbreiding 

Believe I've just confirmed that it's not technically the smooth-scrolling, but [passing in options](https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions) to `window.scroll()` or `window.scrollTo()`, because this similarly fails:

```javascript
window.scroll({ top: 0 })
```

Think I'm personally going to remove this in favor of [CSS `scroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior).

**Comment by felixpk** [comment]
Why is this issue closed?
`cypress: 3.1.4` and the problem still exists

**Comment by jennifer-shehane** [comment]
The issue was closed by the original person who opened this. We can reopen until newer version of Electron is released.

**Comment by shaunswales** [comment]
So is this something that is going to be looked into quickly?

It's a big difference between the versions, Electron 59 and Chrome 71, why hasn't Electron been updated alongside the Chrome browser?

**Comment by chrisbreiding** [comment]
The version of Electron is tied to the Cypress binary itself, since it uses Electron itself. Updating Electron means issuing a new version of Cypress, which we'll be doing with [4.0](https://github.com/cypress-io/cypress/issues/2840). When you run Chrome, it uses the Chrome installed on your system, which means you must have Chrome installed, but also means you can control the version separate from Cypress. 

There are various reasons we use Electron for `run` mode. The biggest ones are that it allows us to easily do video recording of your runs for debugging and that, since headless runs are mostly used in CI, it doesn't require you to have to install Chrome in your CI environment. You can just install Cypress and have it work. (By the way, you _can_ use Chrome in `run` mode with the `--browser` flag, but video recording will be disabled).

**Comment by jennifer-shehane** [comment]
Related issue: https://github.com/cypress-io/cypress/issues/3200

**Comment by jennifer-shehane** [comment]
Electron was updated to Chrome 61 in Cypress version [3.3.0](https://on.cypress.io/changelog#3-3-0) and this issue should be fixed.
