### ISSUE TITLE
Your configFile threw an error from: cypress.config.js  We stopped running your tests because your config file crashed.  error when i am tring to install cypress in my react project

### ISSUE THREAD

**Issue by nisargadhvaryu** [cypress-io/cypress#27619]
### Current behavior

Your configFile threw an error from: cypress.config.js  We stopped running your tests because your config file crashed.  error when i am tring to install cypress in my react project

### Debug logs

```Text
Your configFile threw an error from: cypress.config.js  We stopped running your tests because your config file crashed.  error when i am tring to install cypress in my react project
```

### Cypress Version

10.3.1

### Node version

16.13.1

### Package Manager

npm

### Package Manager Version

8.1.2

### Operating system

Linux

### Operating System Version

21.0

### Other

![Screenshot from 2023-08-22 16-24-24](https://github.com/cypress-io/cypress/assets/130731666/192f7f78-5ce2-4a36-9096-82e64b8c15a5)

**Comment by nagash77** [comment]
Hi @nisargadhvaryu There is not enough information to go off of to provide any useful insights.  Can you share your config?  Have you tried simplifying your config to an absolute minimum and then slowly adding in back options until the error appears?  It is likely you have a typo or misnamed config option.

Check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
