### ISSUE TITLE
i am trying to install cypress after installing i have seen all ts file but i want js files in my project and my project is also in react .

### ISSUE THREAD

**Issue by nisargadhvaryu** [cypress-io/cypress#27620]
### Current behavior

i am trying to install cypress after installing i have seen all ts file but i want js files in my project and my project is also in react .

### Debug logs

```Text
i am trying to install cypress after installing i have seen all ts file but i want js files in my project and my project is also in react .
```

### Cypress Version

10.3.1

### Node version

16.13.1

### Package Manager

npm

### Package Manager Version

8.1.2

### Operating system

Linux

### Operating System Version

21.0

### Other

[
![Screenshot from 2023-08-22 16-28-40](https://github.com/cypress-io/cypress/assets/130731666/4c4c86ef-621a-4d46-a4bb-57f39d82dc5e)
](url)

**Comment by MikeMcC399** [comment]
@nisargadhvaryu 

If you have `typescript` installed, then Cypress assumes you would like to have a TypeScript project set up.
