### ISSUE TITLE
RxJS Issue while installing Cypress

### ISSUE THREAD

**Issue by AaronVikta** [cypress-io/cypress#27629]
### Current behavior

Hi all,

On a new cypress project, after running npm init and npm install -D cypress.

The process never completes, I have attached a screenshot
![image](https://github.com/cypress-io/cypress/assets/21356678/e1944489-6319-405a-b987-a2f1d511745e)

I am wondering what I am doing wrong as this had always worked for me

### Cypress Version

12.7

### Node version

16.17.1

### Package Manager

npm

### Package Manager Version

9.7.1

### Operating system

Windows

### Operating System Version

Windows 10 and Windows 11

**Comment by MikeMcC399** [comment]
@AaronVikta 

The symptoms you describe are typically network issues. You may be able to find out more if you run in debug mode:

```bash
npm install cypress@latest --save-dev --ignore-scripts
npx cypress cache clear
export DEBUG=cypress:*
npx cypress install
```

For PowerShell substitute `export` line above with:
```bash
$Env:DEBUG='cypress:*'
```

For CMD substitute `export` line above with:
```bash
set DEBUG=cypress:*
```

**Comment by nagash77** [comment]
In addition to Mike's suggestion, you should also check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by AaronVikta** [comment]
Thanks guys @MikeMcC399 @nagash77. The suggestion work for me.
