### ISSUE TITLE
Calendar select in Cypress IO

### ISSUE THREAD

**Issue by raval1986** [cypress-io/cypress#2762]
Hi!
Dear Friends, I have problem with cypress io.
I am looking for request about select date from calendar.

```
input data-v-628c5b10="" type="date" id="startDate" name="startDate" class="form-control"
```

Date on website looks:
```
From date:
2018-11-11
To date:
2018-11-13
```

```
input data-v-628c5b10="" type="date" id="endDate" name="endDate" class="form-control"
```

How I can write code to my test to select for example:
```
start date 2016-01-01
finish date 2019-01-01
```

Thank You for Your help.

**Comment by raval1986** [comment]
I paste code from site in first post.
Down, You have how its look on website.

![github](https://user-images.githubusercontent.com/43434011/48351968-e7498d80-e68b-11e8-9b5d-08eaabf605dd.png)

**Comment by jennifer-shehane** [comment]
[Docs for typing into date input](https://docs.cypress.io/api/commands/type.html#Date-Inputs)

```js
cy.get('#startDate').type('2016-01-01')
cy.get('#endDate').type('2019-01-01')
```

You can ask questions about Cypress in our online chat: https://gitter.im/cypress-io/cypress

**Comment by jaideepsinghchauhan** [comment]
How to click on the calendar icon of this input. i want to open the calendar once we click on the calendar , but it's HTML element

<input type="datetime-local" id="meeting-time"
       name="meeting-time" value="2018-06-12T19:30"
       min="2018-06-07T00:00" max="2018-06-14T00:00">
