### ISSUE TITLE
Recorded Video Freezes and Loses Content

### ISSUE THREAD

**Issue by nkalupahana** [cypress-io/cypress#27633]
### Current behavior

I currently have a set of tests where the recorded video freezes about 10 seconds in when the site is loading, and doesn't unfreeze for three minutes. The job logs clearly show tests running during this time.

### Test code to reproduce

The video can be viewed in the artifacts of this run: https://github.com/nkalupahana/baseline/actions/runs/5945554858
The specific job run is here: https://github.com/nkalupahana/baseline/actions/runs/5945554858/job/16124811848

To test locally:
- npm ci
- In one terminal: PORT=8100 npm run serve
- In another terminal: open cypress and run E2E test

### Cypress Version

10.11.0

### Node version

v16, actions/setup-node@v3 16.x

### Operating System

Ubuntu, GitHub Actions Runner 2.308.0

**Comment by nagash77** [comment]
Hi @nkalupahana are you seeing the same behavior in the latest version of Cypress?

**Comment by MikeMcC399** [comment]
@nkalupahana 

As @nagash77 mentioned, it would be worth checking the lastest Cypress 12.x version as the [Changelog](https://docs.cypress.io/guides/references/changelog) references some improvements around video capture.

You didn't say exactly which type of GitHub Actions runner you are using. If it is the default Ubuntu runner, then according to [Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) you get:

- 2-core CPU (x86_64)
- 7 GB of RAM
- 14 GB of SSD space

and that may not be enough. If you have the option to test using a so-called [Larger runner](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#machine-specs-for-larger-runners) you may find that video capture works better.

**Comment by nkalupahana** [comment]
I updated to v12 and it's fixed, thanks!
