### ISSUE TITLE
CSS disappears after mousing over the snapshot links

### ISSUE THREAD

**Issue by nick-true-dev** [cypress-io/cypress#27632]
### Current behavior

After running cypress e2e tests, the target site gets rendered as expected.

However, if you over the mouse cursor over any of the test snapshot links in the cypress desktop app, then certain css styles unexpectedly disappear from these snapshots. 

More specifically, the `<link>` elements used to import dark/light theme css files will disappear from the `<head>` section after you hover the mouse over a snapshot.

This causes the background color to change from dark gray to white.

For example, this is before hovering the mouse over `1 visit /`:

![before mouse over](https://github.com/cypress-io/cypress/assets/64568525/120e8966-e298-43de-b066-955d52cbaf07)

...and this is after:

![after mouse over](https://github.com/cypress-io/cypress/assets/64568525/76467e50-a550-4f03-a46b-fa12b2bf346f)

### Desired behavior

The website's background color should remain gray/black whether or not the user hovers over the snapshot link.

### Test code to reproduce

https://github.com/nick-true-dev/cypress_css_issue_example

### Cypress Version

12.17.4

### Node version

16.20.1

### Operating System

macOS 12.6.8

### Other

Note that the <link> elements get added dynamically by addLinkElt() in App.vue in this example.

**Comment by jennifer-shehane** [comment]
@nick-true-dev Is this still occurring in v13 latest?

**Comment by nick-true-dev** [comment]
Hi Jennifer. I still see the issue with cypress 13.6.1.

**Comment by mfgabriel92** [comment]
I am facing the same thing, except the entire page, with its elements, go invisible, not only the styling.
