### ISSUE TITLE
Allow passing arguments to opened browser 

### ISSUE THREAD

**Issue by marklagendijk** [cypress-io/cypress#2763]
### Current behavior:
It is currently to possible to specify arguments which should be passed to the browser that will be opened.

### Desired behavior:
Create a new [browser configuration option](https://docs.cypress.io/guides/references/configuration.html#Browser) which allows specifying browser arguments, which will be passed to the browser that will be opened.
Example `cypress.json`:
```json
{
  "browserArguments": ["--proxy-server", "http://localhost:1234"]
}
```
I think having this option will be useful because it would, presumably, be easy to implement and it would allow specifying any of the arguments which a browser supports.

**Background story**
Cypress is really awesome! I first saw it in action at Angular Connect this week and became enthusiastic right away.
After that I did some research to find out if we could use it for our use case.
Our use case is testing that several systems integrate well together. These systems are on different super domains and the only way to test them is to do the complete flow from system to system.
Unfortunately it turns out that Cypress does explicitly not support this use case.

Now I am a bit stubborn, and really want to get it working anyway.
The first problem I encountered was that Cypress normally does not work with multiple super domains. This I could fix by [disabling web security](https://docs.cypress.io/guides/guides/web-security.html#Disabling-Web-Security).

The second problem is that Cypress has functionality for removing security mechanisms (frame busting Javascript code, and removing the 'X-Frame-Options' header), but only does this for the primary domain, not for all domains.

I tried solving this by creating a proxy using [hoxy](http://greim.github.io/hoxy/) where the proxy would remove these headers.
Unfortunately I found out that when I pass the proxy (`HTTPS_PROXY=http://localhost:8080 HTTP_PROXY=http://localhost:8080 https_proxy=http://localhost:8080 http_proxy=http://localhost:8080 cypress open`) it only uses the proxy for requests to the primary domain.
So the issue remains.

Currently my guess is that I would be able to get it working as soon as I am able to pass proxy settings to the opened browser. It seems that environment variables are not passed along to the opened browser, so I am stuck.
Because there is [no architectural documentation](https://github.com/cypress-io/cypress-documentation/issues/872) yet, it is hard to find out if this would actually work.  

Note: when I can get this working, I will release the proxy code as NPM module, so other people can easily apply the same solution.

**Comment by marklagendijk** [comment]
I looked into the code a bit and found out the following:
`packages/server` is the one which orchestrates the starting of the browser.
Passing args is supported all the way down:
- https://github.com/cypress-io/cypress/blob/6bb8250532a72a1ed679177fc8b9b3e74427e676/packages/server/lib/browsers/index.coffee#L66
- https://github.com/cypress-io/cypress/blob/6bb8250532a72a1ed679177fc8b9b3e74427e676/packages/server/lib/browsers/utils.coffee#L89
- https://github.com/cypress-io/cypress/blob/6bb8250532a72a1ed679177fc8b9b3e74427e676/packages/launcher/lib/browsers.ts#L49

**Comment by chrisbreiding** [comment]
Have you tried using the [`before:browser:launch` plugin event](https://docs.cypress.io/api/plugins/browser-launch-api.html)?

**Comment by marklagendijk** [comment]
@chrisbreiding thanks! I missed that.
It indeed allows to modify browser args. 
However, I saw that Cypress itself also already specifies a proxy. Do you happen to know what this proxy does exactly?
I know that one of the things it does is removing some security headers, and framebusting Javascript code. But it's not clear to me why it only does this for the AUT, instead of for every url.

I think maybe I can achieve something by loading custom extensions (if I can find the right extensions to disable problematic security features).

I'm closing this issue because the actual feature request is not necessary, because the event already allows doing this.l

**Comment by henrik242** [comment]
@marklagendijk  Did you figure out how to pass arguments to the browser?  I specfically need `— explicitly-allowed-ports=6000` (ref. https://medium.com/@msinha2801/why-are-some-ports-considered-unsafe-restricted-c3c22d0596c0 )
