### ISSUE TITLE
Change in behaviour from 12.17.3 to 12.17.4

### ISSUE THREAD

**Issue by marmaladebacon** [cypress-io/cypress#27641]
### Current behavior

Hi,
Upgrading from cypress@12.17.3 to cypress@12.17.4 introduces a breaking change whereby if you have `sideEffects:false` set in your package.json, and you're using TypeScript, custom cypress commands will not be registered using the recommended/scaffolded path mentioned in the docs: https://docs.cypress.io/api/cypress-api/custom-commands#__docusaurus_skipToContent_fallback

Should we add a note to the documentation so that users are aware of the need to either have `sideEffects` undefined, set to 'true', or set to the array  containing the path for the command files eg `['cypress/**/*']` .

Alternatively, we liked wrapping the commands in a exported function and then importing and calling that function in the supportFile so that we don't rely on importing for side-effects in the first place.
``` ts
// cypress/support/commands.ts
export function registerCommands() {
  Cypress.Commands.add('drag', { prevSubject: 'element'}, (subject, options) => { ... });
  //other commands here
}
```

``` ts
// cypress/support/e2e.ts
import {registerCommands} from './commands';
registerCommands();
```
At the very least we think that a documentation update should be made to clarify this change in behavior regarding `sideEffects: false` in a package.json.

It might be nice if cypress would automatically flag the cypress directory for side effects.

### Desired behavior

In this situation, Cypress should work even with sideEffects set to false in a TypeScript project, or it should be documented.

### Test code to reproduce

forked from https://github.com/cypress-io/cypress-test-tiny
https://github.com/marmaladebacon/cypress-repo-tiny-sideeffects/pull/1

git clone and run `npm run cypress:run`

### Cypress Version

12.17.4

### Node version

v18.16.1

### Operating System

macOs 13.4.1

**Comment by nagash77** [comment]
Hi @marmaladebacon , thanks for opening this issue.  It may be helpful to add something in the documentation around this specific use case.  If you are interested you could open a PR in https://github.com/cypress-io/cypress-documentation which we could look over.

**Comment by blakek** [comment]
IMO this is a breaking change that'd be helpful to list in the migration guide. Thanks @marmaladebacon cause I would have never found this as the issue.
