### ISSUE TITLE
为什么我在VC code上修改了代码后，保存后运行的还是旧代码呢

### ISSUE THREAD

**Issue by saber-sun** [cypress-io/cypress#27652]
### Current behavior

version：12.17.

### Test code to reproduce

import 'cypress-xpath';
import {expect} from 'chai';

import {
  Given,
  When,
  Then,
  Before,
  // After,
} from "@badeball/cypress-cucumber-preprocessor";

Before(() => {
  cy.clearCookies();
  cy.clearLocalStorage();
  cy.visit("/");
})

Given("the 101 official website homepage is opened", () => {
  });

When("the user is not logged in and views the course category tags", () =>{
    cy.get('.ant-dropdown-trigger.style_dropdown__6Cmlq').trigger("mouseover");
    
})

Then('verify that the course categories is displayed', (categories) =>{
    categories.forEach(category =>{
      cy.contains(category).should('be.visible');

    });
});

### Cypress Version

12.17.4

### Node version

v16.18.1

### Operating System

windows10

**Comment by nagash77** [comment]
Sorry but we are unable to offer support in Chinese at this time.  I am going to close this issue at this time.  If you so desire please open a new ticket with an english description and completed issue template.
