### ISSUE TITLE
cy.intercept not working in component test, works in e2e test

### ISSUE THREAD

**Issue by aleksey-ilin** [cypress-io/cypress#27654]
### Current behavior

I have integration tests in my project. I rewrote one to component testing. Not working some intercept in it.
In the integration test Request URL is `http://localhost:8080/api/my-api/information`, but in the component test Request URL for same request is `http://localhost:8081/__cypress/iframes//Users/user/projects/my-project/src/shared/components/side-panel/api/my-api/information`. I added prefix ** in the path to intercept:
```
  cy.intercept(
      { method: 'GET', path: '**/api/my-api/information' },
      async (req) => {
          req.reply({
              body: { name: 'test },
              statusCode: 200,
          });
      },
  ).as('getInformation);
```
 Cypress intercept request in the integration test, but not intercept in the component. It is true for only GET request. PUT request work properly.

Why added prefix `http://localhost:8081/__cypress/iframes//Users/user/projects/my-project/src/shared/components/side-pane` in component test?
Why not working intercept in component test?

### Test code to reproduce

I created demo https://github.com/aleksey-ilin/cypress-component-testing-with-intercept

![image](https://github.com/cypress-io/cypress/assets/32348899/e6a6d005-fc9e-4a0c-bf58-ccdb6d156a8e)

### Cypress Version

12.17..4

### Node version

14.19.1

### Operating System

macOs 13.5

**Comment by mike-plummer** [comment]
@aleksey-ilin Sorry to hear you're having trouble. Thanks for providing a reproduction; unfortunately, it is incomplete and does not demonstrate the issue you describe. Neither your E2E nor CT tests actually *click* the buttons, thus your XHR requests are never made.

I made a few updates to your project and cannot reproduce the issue you describe. What I can see both PUT and GET requests can be successfully intercepted in both E2E and CT tests
1. Use host-relative URLs for service calls (shouldn't attempt to call back into the running instance of Cypress)
2. Gave unique identifiers to both buttons (to make them easy to get & click)
3. Add steps to E2E and CT tests to get & click both buttons
4. Add a `cy.wait('@alias')` for both service call aliases after the button clicks so the test doesn't terminate before the requests are complete

**Comment by aleksey-ilin** [comment]
My bad. I forgot to describe how makes a request. Need to click the buttons manually after the test pass. But anyway I created two tests. They contain click the buttons. One of them makes a get request and not pass. Another makes put request and pass. I pushed this changes. You can try to check.
![image](https://github.com/cypress-io/cypress/assets/32348899/5d6c05ee-5a7d-4e88-a0cc-24bff62ad39f)
I can not use relative URLs, because I don know where do prefixes (`http://localhost:8081/__cypress/iframes//Users/user/projects/my-project/src/shared/components/side-pane`) come from.
There is no prefix in my integration test in my project.
![image](https://github.com/cypress-io/cypress/assets/32348899/b3f65251-eb31-4675-abef-b590c7d5b703)
And there is the prefix in the same my component test in my project.
![image](https://github.com/cypress-io/cypress/assets/32348899/a766e2b7-e582-43c4-9b65-55d7c2bee086)
I printed in console axios config. It contains URL and not contains the prefix.
![image](https://github.com/cypress-io/cypress/assets/32348899/6e2c9397-8ed0-4bec-b54e-1b756ae1d5ad)
And I printed in console response. It contains response url with prefix
![image](https://github.com/cypress-io/cypress/assets/32348899/ca3c3fae-57dd-497e-8b13-abd6ac383a32)

I found an issue https://github.com/cypress-io/cypress/issues/23479. @bahmutov make a request. In a log we can see that the url contains similar prefix. But in this issue not describe about this prefix.

**Comment by mike-plummer** [comment]
@aleksey-ilin Requests made by the test runner are proxied through Cypress by the browser - that's where the prefix you're referring to comes from. I suspect you need to use a host-relative path for the API requests made by your button - the URL you're attempting to use is a special path used to perform internal Cypress communication; that is likely causing your GET request to be incorrectly handled. If I take your latest update and change the URLs to this everything works as expected - the protocol, host, and port will be derived from the current browser location when running in Cypress and standalone.

```js
const handleClick1 = () => {
    const xhr = new XMLHttpRequest();

    xhr.open('GET', '/api/my-api/view/123');
    xhr.send();
  };

  const handleClick2 = () => {
    const xhr = new XMLHttpRequest();

    xhr.open('PUT', '/api/my-api/view/123');
    xhr.send();
  };
```
