### ISSUE TITLE
Cypress is running a super slow on Apple M2 Max Mac

### ISSUE THREAD

**Issue by AlexanderTunick** [cypress-io/cypress#27650]
### Precondition
A few days ago I bought a new Apple M2 Max Macbook pro and transferred data from my old 2019 intel MacBook pro (including all Webstorm projects with Cypress)

### Situation
When I launched Cypress on my new MacBook it appeared to be super slow and many tests failed due to timeout. Also, the controlled Chrome instance itself was laggy and slow, it barely reacted to my UI actions in the right specs sidebar and Auto-scrolling was glitchy as it was difficult to output the action logs.

### Debugging
1. I had Cypress version 9.7.0 at that time, and I thought that it might be related. And I started gradually upgrading the version till 10.3.0 where `"Fixed a memory leak in Chromium-based browsers caused by storing data: urls containing base64 encoded files unnecessarily. Fixed [#17853](https://github.com/cypress-io/cypress/issues/17853) and [#22462](https://github.com/cypress-io/cypress/issues/22462)."` was addressed. I cleared cypress cache and ran the tests - **didn't help**.
2. I turned off my VPN - **didn't help**.
3. I ran the exact same tests on my intel MacBook pro and everything worked fine.

### Reproducible case to double confirm my problem
I decided to create a small project (Cypress v10.3.0) with a simple API login and visit to test without project-specific plugins initiating and ran this project on both Macbooks.

Speed results for the first run appeared to be: 
* Apple M2 Max Macbook pro - **39s** 
* Intel i7 Macbook pro - **4s**

### Tech notes
1. Cypress v10.3.0
2. Chrome instance v116
3. Macbook -  Apple M2 Max, Ventura 13.0
4. Node v16.15.0

### Desired behavior

Could run much faster

### Test code to reproduce

spec.cy.js
```
describe('empty spec', () => {
  it('passes', () => {
    cy.loginBrandDashboard('klickly.e2e+development-performance@gmail.com');
    cy.visit('https://giftly.klickly-dev.com/reward/5617905c-04f2-4995-952b-de3cd1ac08a5')
  })
})
```

commands.js
```
Cypress.Commands.add('loginBrandDashboard', (email, password = 'test123') => {
    cy.session(email, () => {
        cy.request({
            method: 'POST',
            url: 'https://brands-dashboard-api.klickly-dev.com/auth/login',
            body: {
                email,
                password
            },
            timeout: 60000
        }).then((resp) => {
            expect(resp.status, 'Brand Dashboard login').to.eq(200);
        });
    });
});
```

e2e.js
`import './commands'`

cypress.config.js
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  downloadsFolder: 'cypress/downloads',
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    baseUrl: 'https://brands.klickly-dev.com/',
    experimentalSessionAndOrigin: true
  }
});
```

package.json
```
{
  "name": "cypress-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "cypress:open": "cypress open"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "10.3.0"
  }
}
```

### Cypress Version

10.3.0

### Node version

16.15.0

### Operating System

Ventura 13.0

### Debug Logs

```shell
Unfortunately the entire log set exceeds the allowed number of characters.
```

### Other

Can just and show on a call or any other was suitable for developers

**Comment by nagash77** [comment]
Can you try upgrading to the latest version of Cypress?  We have done a lot to address performance since 10.3.0.

**Comment by AlexanderTunick** [comment]
> Can you try upgrading to the latest version of Cypress? We have done a lot to address performance since 10.3.0.

Thanks, will do soon

**Comment by AlexanderTunick** [comment]
Yes, the last version fixed it. Now took 3 seconds instead 39s.

Thanks!, it can be closed.
