### ISSUE TITLE
ignoreTestFiles being ignored on Travis CI

### ISSUE THREAD

**Issue by Orlandohub** [cypress-io/cypress#2765]
### Current behavior:

on my cypress config file `cypress.json` I added this:

```json
{
  "baseUrl": "http://localhost:8000/",
  "ignoreTestFiles": "*.spec.js"
}
```
So this way I can ignore the example `.spec.js` files. Localy works. On Travis ci it's completely ignored and runs all the `.specs.js`

I just installed Cypress latest version on my project with Gatsby.

**Comment by jennifer-shehane** [comment]
Hey @Orlandohub, can you provide the full command and all arguments that you pass within TravisCI to run cypress?

**Comment by Orlandohub** [comment]
Hey @jennifer-shehane, I managed to work it out, it seems there was an issue on travis side!
Thanks for the quick reply and keep up with the great work, enjoying to use Cypress a lot!!
