### ISSUE TITLE
Hii all , i am trying to install cypress when i add cypress version 10 it give me ts files . and when i add cypres version 9 its give js files .i want to js file in cypress version 10 is this possible?? or i have to use 9 version for js files.                               

### ISSUE THREAD

**Issue by nisargadhvaryu** [cypress-io/cypress#27662]
### Current behavior

Hii all , i am trying to install cypress when i add cypress version 10 it give me ts files . and when i add cypres version 9 its give js files .i want to js file in cypress version 10 is this possible?? or i have to use 9 version for js files.                               

### Debug logs

```Text
Hii all , i am trying to install cypress when i add cypress version 10 it give me ts files . and when i add cypres version 9 its give js files .i want to js file in cypress version 10 is this possible?? or i have to use 9 version for js files.
```

### Cypress Version

10.0.0

### Node version

14.18.1

### Package Manager

npm

### Package Manager Version

9.1.0

### Operating system

Linux

### Operating System Version

20

**Comment by MikeMcC399** [comment]
@nisargadhvaryu 

- This is a duplicate of the issue you opened in https://github.com/cypress-io/cypress/issues/27620

You should check if you have typescript installed, directly or indirectly.

```bash
npm ls typescript
```

You will need to uninstall it, if you want Cypress onboarding to create a JavaScript configuration and not a TypeScript configuration.

Note that this issue list is for bugs, and not for getting advice about how to use Cypress. For advice, you can contact the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button).

Also if you are starting a new project, you should probably try to use the current version of Cypress `12.x`, not the older `10.0.0`.

Node.js `14` has already reached end-of-life and is no longer supported. Node.js `18` (LTS) or `20` would be the better versions to use.
