### ISSUE TITLE
cy.intercept not working in component test, works in e2e test

### ISSUE THREAD

**Issue by aleksey-ilin** [cypress-io/cypress#27663]
### Current behavior

This issue is continuing https://github.com/cypress-io/cypress/issues/27654. Issue [27654](https://github.com/cypress-io/cypress/issues/27654) closed very quickly, I didn't have time to answer.

I changed my demo https://github.com/aleksey-ilin/cypress-component-testing-with-intercept. Rewrite request from `xhr.open('GET', 'http://localhost:3000/__cypress/iframes//Users/user/projects/ui/src/shared/components/side-panel/api/my-api/view/123');` to `xhr.open('GET', 'api/my-api/view/get');`. In the tests cypress put prefix in the URL: `http://localhost:8080/__cypress/iframes//Users/user/projects/cypress-component-testing-with-intercept/src/api/my-api/view/get`. And test with GET request not pass, but with PUT request pass.
![image](https://github.com/cypress-io/cypress/assets/32348899/8b7f1524-5a3b-4ca7-b510-da8fa444d8ba)

I noticed if add `/` in the URL request `xhr.open('GET', '/api/my-api/view/get');`, cypress does not put its prefix `http://localhost:8080/__cypress/iframes//Users/user/projects/cypress-component-testing-with-intercept/src/` in the request URL.

Why cypress puts prefix? And why do not work intercept like this
```
  cy.intercept(
    { method: 'GET', path: '**/api/my-api/view/get' },
    async (req) => {
        req.reply({
            body: { key: 'get' },
            statusCode: 200,
        });
    },
  ).as('get');
```
for GET request, but work for PUT?

### Test code to reproduce

https://github.com/aleksey-ilin/cypress-component-testing-with-intercept

### Cypress Version

12.17.4

### Node version

14.9.1

### Operating System

macOs 13.5

**Comment by mike-plummer** [comment]
@aleksey-ilin You can comment on closed issues if you feel they should be reopened, you don't need to open a new one.

The path `api/a/b/c` is location-relative (it appends to the current browser path), whereas `/api/a/b/c` is host- or context-relative. This is not something unique being done by Cypress - it is a basic behavior of all browsers. When making XHR requests you need to either provide a fully-qualified external URL (`https://my-api-domain/api/a/b/c`) or a host/context-relative path if you want the API request to be made back into the hosted application (`/api/a/b/c`). Your component test is hosted on an internal dev server within Cypress, and using a location-relative path will not work and will likely cause issues.

**Comment by aleksey-ilin** [comment]
@mike-plummer thank you for explanation.

> This is not something unique being done by Cypress - it is a basic behavior of all browsers.

I started the project with `yarn start` and made request by click on the button. Request URL has not any prefix:
`http://localhost:3000/api/my-api/view/get` In dev tools. But in tests Request URL:
http://localhost:8080/__cypress/iframes//Users/user/projects/cypress-component-testing-with-intercept/src/api/my-api/view/put

Why didn't the browser add anything before location-relative url?

**Comment by mike-plummer** [comment]
@aleksey-ilin When running in a component test Cypress creates a dev server instance and hosts a very simple web application containing your component. This web application exists at a different path than the one you would get when running your entire application like you would for an e2e test (hence the Cypress-related URL you keep referencing). This is the reason why location-relative URLs are a bad idea - they only work if your component exists at a specific, known location which is not the case here.

Location-relative URLs are *relative to the page that is currently displayed*. When launched via `yarn start` you have a specifically crafted config including a port and set of pages to comprise the hosting page. Component tests are deliberately taking your component *out* its normal location in your application to test it in isolation.

**Comment by aleksey-ilin** [comment]
@mike-plummer ok, thanks for the help.
