### ISSUE TITLE
Cypress wait until object is created inside Map

### ISSUE THREAD

**Issue by muhamedkarajic** [cypress-io/cypress#27669]
### What would you like?

I have a global store, how can I await the created object in the store using cypress in Angular? I can inject the service but when I use cypress I just don't understand what method I can call. The creation of that object will happen asynchronous at some point later in time. 

So what I need is kind of that I have a interval which checks every 1_000ms if the object was created and when it was proceed.

I think this should not be so hard however it just dosen't allow me to do it.

### Why is this needed?

Cause I use signalr connection and I really really don't wanna mock the messages, I simply want when the object is in state requested to return what is the next state.

**Comment by nagash77** [comment]
Check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by muhamedkarajic** [comment]
I realised that I was supposed to await the UI changes, using cy.get, cy.contains, etc.  Then simply inject the service and provide (mock) the response. Therefore this issue is solved for me and it had nothing directly to do with cypress.

Injecting was done by using TestBed e.g. and adding a cy method such as:
```typescript
declare global {
// eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    interface Chainable<Subject> {
      inject: <T>(token: ProviderToken<T>) => Cypress.Chainable<T>
    }
  }
}

Cypress.Commands.add('inject', <T>(token: ProviderToken<T>): Cypress.Chainable<T> => 
  cy.wrap(TestBed.inject(token))
);
```
