### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGABRT and SIGAKILL

### ISSUE THREAD

**Issue by matsgabe** [cypress-io/cypress#27679]
### Current behavior

Ao rodar o projeto E2E do cypress tanto npx open quanto npx run, está crashando ao tentar rodar alguns testes, que antes não estavam apresentando estes problemas.
Ao tentar rodar os testes, gera o erro abaixo:

The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 22.10)
Cypress Version: 12.17.4

### Desired behavior

Deve rodar os testes normalmente.

### Test code to reproduce

Esta é a configuração vinculada ao meu projeto
```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  e2e: {
    baseUrl: 'http://localhost:3000/',
    experimentalRunAllSpecs: true,
    defaultCommandTimeout: 10000,
    numTestsKeptInMemory: 0,
    testIsolation: false,
    video: false,
    screenshotOnRunFailure: false,
    trashAssetsBeforeRuns: false,
    setupNodeEvents (on, config) {},
    chromeWebSecurity: false,
    chromeWebPreferences: {
      notifications: false
    },
    includeShadowDom: true,
    experimentalSourceRewriting: true,
    viewportHeight: 768,
    viewportWidth: 1366,
    onBeforeRun (browser, args) {
      if (browser) {
        browser.clearCookies()
      } else {
        Cypress.browser.clearCookies()
      }
    },
    env: {
      CYPRESS_PARALLEL: true,
      chrome: 'cypress run --browser chrome',
      firefox: 'cypress run --browser firefox'
    }
  },
  component: {
    specPattern: '**/*.cy.js',
    devServer (cypressConfig) {
      return {
        port: 3000,
        close: () => {}
      }
    }
  }
})
```

### Cypress Version

12.17.4

### Node version

14.19.3

### Operating System

Linux Ubuntu 22.10

**Comment by nagash77** [comment]
Hi @matsgabe , are you able to describe your problem in english?  Unfortunately we do not offer support in other languages at this time.  In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by matsgabe** [comment]
Hi @nagash77 
I’m having trouble trying to run e2e tests both when running npx open and when trying to run npx run. I try to run a simple test, where I allocate some locators data to extract a report, and is returning the error below:

The Test Runner unexpectedly exited via a exit event with signal SIGABRT, or returning a exit event SIGAKILL.

My configuration is adjusted as follows:
```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  e2e: {
    baseUrl: 'http://localhost:3000/',
    experimentalRunAllSpecs: true,
    defaultCommandTimeout: 10000,
    numTestsKeptInMemory: 0,
    testIsolation: false,
    video: false,
    screenshotOnRunFailure: false,
    trashAssetsBeforeRuns: false,
    setupNodeEvents (on, config) {},
    chromeWebSecurity: false,
    chromeWebPreferences: {
      notifications: false
    },
    includeShadowDom: true,
    experimentalSourceRewriting: true,
    viewportHeight: 768,
    viewportWidth: 1366,
    onBeforeRun (browser, args) {
      if (browser) {
        browser.clearCookies()
      } else {
        Cypress.browser.clearCookies()
      }
    },
    env: {
      CYPRESS_PARALLEL: true,
      chrome: 'cypress run --browser chrome',
      firefox: 'cypress run --browser firefox'
    }
  },
  component: {
    specPattern: '**/*.cy.js',
    devServer (cypressConfig) {
      return {
        port: 3000,
        close: () => {}
      }
    }
  }
})
```

**Comment by botond-eles-intland** [comment]
Hello @nagash77!
I am having similar problems. The cypress open mode run nowadays frequently quits closing the opened Chrome window. Sometimes this crash happens 1 minute after the test has ended.

**Comment by jennifer-shehane** [comment]
Without a reproducible example to run, there's nothing we can do to address this.
