### ISSUE TITLE
Setting port on cypress config does not propagate to component devServers

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#27675]
### Current behavior

When `config.port` is set and `devServer.port` is set Cypress opens it will open on the `devServer.port` but will not be able to proxy requests to the devServer.

### Desired behavior

Cypress should open on 9999 and be able to proxy requests into the component devServer.

### Test code to reproduce

```js
// cypress.config.js
module.exports = {
  port: 9999,
  component: {
    devServer: {
       bundler: 'webpack',
       framework: '...',
       webpackConfig: {
          port: 8888
       }
    }
  }
}

### Cypress Version

12.17.4

### Node version

default

### Operating System

all

### Debug Logs

_No response_

### Other

_No response_

**Comment by jennifer-shehane** [comment]
Released in [Cypress 13.0.0](https://docs.cypress.io/guides/references/changelog#13-0-0).
