### ISSUE TITLE
code-coverage micro-frontend

### ISSUE THREAD

**Issue by Atul78** [cypress-io/cypress#27688]
### What would you like?

Subject: Assistance Needed: Code Coverage Issue for Micro-Frontend with Next.js and Webpack 5

Hello Team,

I'm Atul Kumar Srivastav, and I'm reaching out to address a challenge we're facing with our micro-frontend project that utilizes Next.js and Webpack 5. We're currently struggling to generate code coverage for this setup, encountering a "code is not instrumented" error.

While we've successfully implemented code coverage for React.js and Next.js projects before, the micro-frontend architecture combined with Next.js and Webpack 5 seems to present a unique obstacle. Despite reviewing online resources and instructional videos, we haven't been able to resolve this issue.

I'm seeking your expertise in troubleshooting and resolving this challenge. If you have experience with micro-frontends, Next.js, and Webpack 5, your insights could be invaluable. Additionally, if you're aware of relevant communities or forums, your guidance in connecting with them would be much appreciated.

Our commitment to continuous improvement remains strong, and I believe overcoming this code coverage challenge will not only benefit our current project but also enhance our overall development practices.

Thank you for your time and assistance.

Best regards,

Atul Kumar Srivastav

**Comment by nagash77** [comment]
Hi @Atul78 issues in the repo are reserved for bugs and feature requests.  If you are a paying cloud customer I suggest you reach out to your account manager for assistance.  If you are not a paying cloud customer, check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
