### ISSUE TITLE
Can't reuse environment variable in spec file

### ISSUE THREAD

**Issue by hoa-pham82** [cypress-io/cypress#27701]
### Current behavior

Given the scenario:
I wanted to sign up for an account, so I input the email and password -> I got an email with an OTP code -> I got an OTP, and continued the signup page. 

I'm using a custom command to send a chaining API request to the mail provider and extract the OTP and I set it as an environment variable via Cypress.env('varName', 'value')
After getting an OTP, I'll continue to put it into the signup form and complete the signup flow (in the spec file)

The issue is when I access this environment variable in the spec file, it returns as `undefined`, but I still can log it with a value when invoking that custom command. 

### Desired behavior

I can use the environment variable that I've set in my spec file. Please refer to the code below for more details:

### Test code to reproduce

**In my `commands.js`:**

```
let messageId;

function getCode(message) {
  const otpPattern = /\d+/;
  const otpMatch = message.match(otpPattern);
  if (otpMatch) {
    console.log('extracted OTP', otpMatch[0]);
    return otpMatch[0];
  } else {
    console.log('no OTP in the message');
  }
}

Cypress.Commands.add('getOTP', (email, key) => {
  cy.request({
    method: 'GET',
    url: 'https://mailsac.com/api/addresses/' + `${email}` + '/messages',
    headers: {
      'Mailsac-Key': key,
    },
  }).as('getMessageId');

  cy.get('@getMessageId')
    .then((res) => {
      expect(res.status).to.eq(200);
      messageId = res.body[0]._id;
      cy.log(messageId);
    })
    .then(() => {
      cy.request({
        method: 'GET',
        url: 'https://mailsac.com/api/text/' + `${email}/` + `${messageId}`,
        headers: {
          'Mailsac-Key': key,
        },
      });
    })
    .then((res) => {
      expect(res.status).to.equal(200);
      Cypress.env('OTP', getCode(res.body));
      cy.log(Cypress.env('OTP'));
    });
});
```

**In my `test.cy.js`:**

```
describe('Email OTP', { baseUrl: 'https://playground.mailslurp.com' }, () => {
  let username = 'hoa.pham' + Math.floor(Math.random() * 10000).toString();
  let password = Math.floor(Math.random() * 100000000).toString();

  it('Register account in Mailslurp', () => {
    cy.visit('/');
    // cy.get('[data-test="username-input"]');
    // cy.get('[data-test="sign-in-password-input"]');
    cy.get('[data-test="sign-in-create-account-link"]').click();

    cy.get('[name=email]').type(`${username}` + '@mailsac.com');
    cy.get('[name=password]').type(`${password}`);
    cy.log('username', `${username}@mailsac.com`);
    cy.log('password', `${password}`);

    cy.get('[data-test="sign-up-create-account-button"]').click();

    cy.contains('Confirm Sign Up');

    cy.getOTP(
      `${username}@mailsac.com`,
      'this_is_key'
    )
      cy.log(Cypress.env('OTP'));

      cy.get('[name=code]').type(Cypress.env('OTP'));

      cy.get('[data-test="confirm-sign-up-confirm-button"]').click();

  });
});
```

**To clarify, I want to use the env Cypress.env('OTP') but I got `undefined`.**

### Cypress Version

12.17.1

### Node version

v16.19.0

### Operating System

Window 11

**Comment by nagash77** [comment]
Hi @hoa-pham82 , unfortunately we likely won't have the bandwidth to investigate this issue in the near future.  I would suggest you check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by hoa-pham82** [comment]
Thanks @nagash77 for the comment. I found a way to workaround by wrapping the test step inside a `then()`.

**Comment by mariamaslam** [comment]
Hi @hoa-pham82 i am facing the same issue, please can you share the code.
I am very desperately looking for a solution to define a global variable and access it everything in all my test files. This is my commands.js. Here i am generating a random mobile number using faker.js. I am doing APIs automated testing but the APIs are executed in a sequence which means there should be one mobile number and one user ID that should be used throughout the test execution.

    import { faker } from '@faker-js/faker';
    Cypress.Commands.add('generateAndSetMobileNumber', () => {
      // Check if the mobile number is already set in the Cypress environment
      if (!Cypress.env('mobileNumber')) {
        const mobileNumber = faker.datatype.number({ min: 5700000000, max: 5899999999 });
        Cypress.env('mobileNumber', mobileNumber.toString());
      }
    });
    
    Cypress.Commands.add('createUser', () => {
      cy.generateRandomMobileNumber().then((mobileNumber) => {
    
        return cy.api({
          failOnStatusCode: false,
          method: 'POST',
          url: '/products/users/',
          body: {
            "countryCode": "971",
            "mobileNo": mobileNumber,
            "viewId": "createView",
            "agentCode": "",
            "language": "EN",
          }
        }).then((response) => {
          expect(response.status).to.eq(201);
          Cypress.env('prospectId', response.body.userId);
        });
      });
    });

Now these commands are defined here and are working perfectly fine but when I use it in my test classes everything generates a new mobile number and new userID whereas I want one UserID and mobileNumber that can be used throughout the execution.

This is my test file

    describe("Generating OTP", () => {
    before(() => {
     cy.createUser() => {
         
        });
      it("Verify user is able to generate OTP by entering their mobile number", () => {
                   UserId = Cypress.env('UserId');
                   mobileNumber = Cypress.env('mobileNumber');
    
    
        cy.api({
          failOnStatusCode: false,
          method: 'POST',
          url: 'products/otp',
          body: {
            "action": "generate",
            "prospectId": prospectId,
            "countryCode": "971",
            "mobileNo": mobileNumber,
          }
        }).then((response) => {
          // Assert that the OTP was generated successfully
          expect(response.status).to.eq(200);
          expect(prospectId).to.have.length(5);
          // Assert that the OTP is valid
          expect(response.body.verified).to.eq(true);
        });
      });
    });

I have tried multiple options as follow, but nothing seems to be working for me:

1. cypress-localstorage-commands plugin
2. setLocalStorage
3. getAllSessionStorage
4. cy.wrap
I look forward to prompt support

**Comment by hoa-pham82** [comment]
Hi @mariamaslam, my suggestion is to wrap up them in the chaining command by `thenable`. You can try to put it in `before` setup, or directly in the test block. 

Something like this: cy.generateAndSetMobileNumber().then(cy.createProspectId).then(cy.anotherRequest...)

I used that workaround for my test here.
https://github.com/hoa-pham82/email-otp-with-cypress/blob/main/cypress/e2e/getOTPFromEmail.cy.js

**Comment by mariamaslam** [comment]
Hi @hoa-pham82 Thank you answering. I went through your solution.
Please would you be able let me know how to do it exactly with theanble if you help in rewriting the code.  I have been stuck on this for months n very desperate for a solution.
Lookig forward to your kind support

**Comment by mariamaslam** [comment]
hi @hoa-pham82 please can you check once. I desperately need HELP

**Comment by hoa-pham82** [comment]
```
`describe("Generating OTP", () => {
    let prospectId;
    let mobileNumber;

    before(() => {
        cy.createUser().then(() => {
             prospectId = Cypress.env('prospectId');
             mobileNumber = Cypress.env('mobileNumber');
        })
    });
    it("Verify user is able to generate OTP by entering their mobile number", () => {

    cy.api({
      failOnStatusCode: false,
      method: 'POST',
      url: 'products/otp',
      body: {
        "action": "generate",
        "prospectId": prospectId,
        "countryCode": "971",
        "mobileNo": mobileNumber,
      }
    }).then((response) => {
      // Assert that the OTP was generated successfully
      expect(response.status).to.eq(200);
      expect(prospectId).to.have.length(5);
      // Assert that the OTP is valid
      expect(response.body.verified).to.eq(true);
    });
  });
});`
```

@mariamaslam  Can you change your test file to this? If still not working, you can ping me via skype to easier to debug. 
live:phamtthanhhoa
