### ISSUE TITLE
Fix typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by S-Tornqvist** [cypress-io/cypress#27708]
### Subject

Guides (CONTRIBUTING.md)

### Description

The sentence "If you make changes to an npm package that can't be published until the binary is also updated, you should make a pull request against specifying this is not be merged until the scheduled Cypress app release date." in file [CONTRIBUTING.md](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) is hard to understand because of incorrect grammar.

**Comment by S-Tornqvist** [comment]
Related to [documentation issue 5452](https://github.com/cypress-io/cypress-documentation/issues/5452)

**Comment by jennifer-shehane** [comment]
@S-Tornqvist We're open to a Pull Request if you want to fix the language in the Contributing guide.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/cypress/pull/27705 has already been submitted with a suggestion for changing the wording.
