### ISSUE TITLE
Angular schematic generate component testing files by default

### ISSUE THREAD

**Issue by geromegrignon** [cypress-io/cypress#27703]
### Current behavior

By answering 'No' to component testing support when adding Cypress for Angular with `ng add @cypress/schematics`, the schematic added still overrides the generic component schematic and creates a `cy.ts` test file in place of the `spec.ts` file.

### Desired behavior

If Component Testing support is not chosen by adding Cypress, creating a new component with `ng g generate` should create a `spec.ts` file by using `ng generate component` schematic.

### Test code to reproduce

- create a Angular project `npx -p @angular/cli ng new projectName`
- move to your root folder with `cd projectName`
- add Cypress with `ng add @cypress/schematics`
- answer 'No' to component testing support
- create a Angular component with `ng generate component home`
- a `home-component.cy.ts` file is created.

### Cypress Version

13.0.0

### Node version

v18.16.1

### Operating System

macOS 13.5

**Comment by pgates-brownadvisory** [comment]
I'm seeing this, too. Angular CLI v15.1.6, Cypress v12.10.0. 

Of note (perhaps) is that I didn't have this problem when I was using Angular CLI v13.3.0.

**Comment by miguelarcjr** [comment]
I have the same problem.

**Comment by Jhamu21** [comment]
Same problem

**Comment by altso** [comment]
I started having the same problem at some point in an old project and was able to "fix" it by reordering schematics in `angular.json` file.

Before:
```json
  "cli": {
    "schematicCollections": [
      "@cypress/schematic",
      "@angular-eslint/schematics",
      "@schematics/angular"
    ],
    "analytics": false
  }
```

After:
```json
  "cli": {
    "schematicCollections": [
      "@schematics/angular",
      "@angular-eslint/schematics",
      "@cypress/schematic"
    ],
    "analytics": false
  }
```

**Comment by Jhamu21** [comment]
> I started having the same problem at some point in an old project and was able to "fix" it by reordering schematics in `angular.json` file.
> 
> Before:
> 
> ```json
>   "cli": {
>     "schematicCollections": [
>       "@cypress/schematic",
>       "@angular-eslint/schematics",
>       "@schematics/angular"
>     ],
>     "analytics": false
>   }
> ```
> 
> After:
> 
> ```json
>   "cli": {
>     "schematicCollections": [
>       "@schematics/angular",
>       "@angular-eslint/schematics",
>       "@cypress/schematic"
>     ],
>     "analytics": false
>   }
> ```

Thankyou it worked!
