### ISSUE TITLE
cy.request with no Dom Content

### ISSUE THREAD

**Issue by matt212** [cypress-io/cypress#2770]
**Current behavior:**

`cy.request()`  provides with updated response `html`  not actual DOM updated content
like if click on `href` it redirect to page and page have some dynamic values based upon `href` parameter and we need to assert it now we are only getting `html` not the `dom` 

- go to page
- get list of links
- go to each link
- check `<some content>`
- verify that the initial page had the same content?
Please refer below highlighted screenshot for same since the highlighted section when we use `cy.visit` it has some value it `span`
![](https://i.imgur.com/ZWGoUmc.png)

 
Desired behavior:
`cy.request` should provide with updated Dom in same manner as `cy.visit` .

Versions
3.1.1

**Comment by jennifer-shehane** [comment]
Hey @matt212, could you provide the test code you are running please? Thanks!

**Comment by matt212** [comment]
sure @jennifer-shehane  give me sometime , i revert with an update accordingly , closing it for now and then reopening it when i post the running code
