### ISSUE TITLE
Cypress 13 Replay - CSS not loading 

### ISSUE THREAD

**Issue by kevingorry** [cypress-io/cypress#27704]
### Current behavior

I installed Cypress 13 and when I watch my tests via Replay through the Cypress Dashboard none of the CSS are loading for any of my pages 
![image](https://github.com/cypress-io/cypress/assets/100594946/f5735a86-f475-46b3-864b-98047801f4d9)

### Test code to reproduce

I cannot share internal information

### Cypress Version

13

### Node version

16

### Operating System

Windows 10

**Comment by AtofStryker** [comment]
Hi @kevingorry. Thank you for opening an issue. For `Test Replay`, to open an issue, you should see a `Report an issue` button in the top right of the replay that is giving you trouble. If you submit an issue through this button, it will give the replay team everything they need to help diagnose and troubleshoot your issue. 

![](https://github.com/cypress-io/cypress/assets/3980464/c0d08fb6-fe78-425b-a491-f3b657856e00)

I am going to close this issue as it will need to go through a different workflow, but if you continue to have any trouble please let us know!

**Comment by sammi-ds** [comment]
I've also ran into issues with CSS not being applied properly while running Test Replay. Its so unreadable that we can barely discern what is happening in the application when the failure occurs. I've submitted a support ticket through the Cypress Cloud UI, but wanted to post here in case anyone else is experiencing this same issue & wondering if they are alone!!

**Comment by nagash77** [comment]
Hi @sammi-ds thank you for submitting your issue through the app UI.  We are indeed looking at those and working to address as many as possible.  I do want to clarify though that we have seen a couple of different reasons for CSS not being applied inside of Test Replay that are not the same so one solution may not address all scenarios where that it happening.
