### ISSUE TITLE
Error: Webpack Compilation Error cypress v 13.0.0

### ISSUE THREAD

**Issue by nand1234** [cypress-io/cypress#27702]
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/31034303/f5004d15-fadc-4a05-b5bb-81f726d1b473)

### Test code to reproduce

Run test with latest cypress docker image cypress/included:13.0.0

### Cypress Version

v13.0.0

### Node version

v20.5.0

### Operating System

Gitlab CI

**Comment by jennifer-shehane** [comment]
@nand1234 Thanks for reporting. What was the previous Cypress version that was working without this error? Could you also provide the contents of your cypress/support/e2e.js file and also your package.json file please? Thanks.

**Comment by nand1234** [comment]
everything work till cypress/included:12.17.2 version. 

cypress/support/e2e.js
```js
// ***********************************************************
// This example support/index.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************

// Import commands.js using ES2015 syntax:
import './commands'
import 'cypress-plugin-stripe-elements';
import 'cypress-iframe';
import "cypress-real-events";
import registerCypressGrep from '@cypress/grep/src/support'
registerCypressGrep()
// import addContext from "mochawesome/addContext";
// // Alternatively you can use CommonJS syntax:
// // require('./commands')

// Cypress.on("test:after:run", (test, runnable) => {  
//     if (test.state === "failed") {    
//       const screenshot =`../cypress/reports/mochareports/assets/${Cypress.spec.name}/${runnable.parent.title} -- ${test.title} (failed).png`;    
//   addContext({ test }, screenshot);  
//     }
//   });
```


package.json file
```json
{
  "name": "nandpoc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  },
  "author": "Nandkumar Ghatge",
  "license": "ISC",
  "dependencies": {
    "cypress-real-events": "^1.7.6"
  },
  "devDependencies": {
    "@cypress/grep": "^3.1.5",
    "cypress-iframe": "1.0.1",
    "cypress-image-diff-js": "^1.23.0",
    "cypress-multi-reporters": "1.6.3",
    "cypress-plugin-stripe-elements": "1.0.2"
  }
}
```

**Comment by AtofStryker** [comment]
@nand1234 is the issue present in Cypress [included](https://hub.docker.com/layers/cypress/included/12.17.4/images/sha256-73d43b53212b353a56147b29397892192fb96a47b74a218de7e26f83d36b268c?context=explore) `12.17.4`?

**Comment by nand1234** [comment]
@AtofStryker  yes.

![image](https://github.com/cypress-io/cypress/assets/31034303/c03012ba-041c-4615-abc9-97f251b4cf0f)

**Comment by AtofStryker** [comment]
@nand1234 I have created https://github.com/AtofStryker/cypress-issue-27702 to try and reproduce the issue, but I am not able to recreate the problem. Are you able to help me fill in some of the blanks here?

I am running the docker image like `docker run -it -v $PWD:/e2e -w /e2e cypress/included:12.17.4`

**Comment by nand1234** [comment]
@AtofStryker  looks like the issue was with plugin->  import registerCypressGrep from '@cypress/grep/src/support'
registerCypressGrep(). 

after installing module manually,   npm i process

test works fine.

**Comment by AtofStryker** [comment]
@nand1234 that issue seems strange because it should fail in that case for me as well, unless there is something different about your installed dependency tree? If you are satisfied with the work around, I can close the issue. Or we can see if I can reproduce on our end and see what the issue/fix would be.

**Comment by nand1234** [comment]
@AtofStryker indeed it’s strange. I would suggest if this issue is not reproducible for other then we can close it.

**Comment by timoklingenhoefer** [comment]
This error occurs when you use `process.env` in the command files.

In my use-case we use our api-package to setup the application with the state the tests expect. When running the tests against our staging environment it needs some env-variables for authentication. These are set by `process.env` calls with data from `Cypress.env(...)`. This is done as the package expects the credentials in `process.env`, but Cypress does not allow direct access to `process.env`, so we set in this round-about way. 

When i commented out the `process.env` calls, the error does not occur (but the tests fail without the vars).

**Comment by AtofStryker** [comment]
@timoklingenhoefer that shouldn't be happening since those files are fed into Cypress' `webpack-batteries-included-preprocesor` where the `process` is polyfilled. It sounds like there is a case where that is not happening and I am assuming you aren't using a custom preprocessor. Are you able to provide a reproduction?
