### ISSUE TITLE
Receiving Error When Attempting to Upload Test Replay

### ISSUE THREAD

**Issue by kinson** [cypress-io/cypress#27712]
### Current behavior

I recently upgraded to 13.0.0 of Cypress and tried viewing a test replay in Cypress cloud. However, in the GitHub action run, I received the following error related to Test Replay:

```
  - Test Replay - Failed Capturing - [
  {
    "code": "invalid_type",
    "expected": "boolean",
    "received": "undefined",
    "path": [
      "response",
      "securityDetails",
      "encryptedClientHello"
    ],
    "message": "Required"
  }
]
```

### Desired behavior

The desired behavior is for the test replay to upload and be viewable in Cypress cloud.

### Test code to reproduce

I don't have a test file to share, this seems to be more of a GitHub <-> Cypress cloud issue unless I am misunderstanding.

### Cypress Version

13.0.0

### Node version

16

### Operating System

ubuntu-latest (in GH Actions)

**Comment by cupcakepanda89** [comment]
I encountered the same issue with AWS Codebuild and following this trouble shoot below and they are all checked 

1. Confirm runs have been recorded to Cypress Cloud using Cypress v13 or later.
2. Ensure tests were recorded using a Chromium-based browser (Chrome, Edge, Electron).
3. Check that Test Replay is enabled in Cypress Cloud project settings.
4. Review the standard output of the test run to ensure there was not an error capturing Test Replay. If you encounter an error capturing Test Replay, please open an issue so that we can investigate.

**Comment by javgarr** [comment]
Experiencing same issue on **Chrome 80** (using cypress/browsers image)

```
====================================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.0.0                                                                         │
  │ Browser:        Chrome 80 (headless)                                                           │
  │ Node Version:   v18.12.0 (/usr/local/bin/node)                                                 │
```

```
 (Uploading Cloud Artifacts)
  - Video - Nothing to upload 
  - Screenshot - Nothing to upload 
  - Test Replay - Failed Capturing - [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "associatedCookies"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "connectTiming"
    ],
    "message": "Required"
  }
]
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  account/logout.feature                                                         (2 of 14)
  Estimated: 10 seconds
  Logout
    ✓ A user can logout and see the WWW homepage (8444ms)
  1 passing (9s)
```

Tests hang after this, cypress cloud timeouts. We are forced to rollback to Cypress 12 until this is fixed.

EDIT: Tests are hanging also on electron and chrome106 in all cases prior to uploading Cloud Artifacts.

**Comment by jennifer-shehane** [comment]
If you’re encountering an error capturing Test Replay, please include the error code printed to the terminal output, we’ll follow up if more information is needed on our side to understand the reason for the error. I know we’re working on fixing some of these already. 

@javgarr Can you open a separate issue regarding the run hanging please.

**Comment by jennifer-shehane** [comment]
We have a fix for this coming out in 13.1.0. We'll try to get this out today. After that release you'll need to upgrade to 13.1.0 to avoid these errors.

**Comment by jennifer-shehane** [comment]
The code for this is done in  https://github.com/cypress-io/cypress/pull/27709, but this has yet to be released.

**Comment by kinson** [comment]
Thanks for the update @jennifer-shehane ! I noticed that I was able to view a test replay this morning after another set of tests ran and it looks rad!

Once 13.1.0 is out I'll upgrade to it as well 🙌🏻

**Comment by kzs61** [comment]
I'm having this issue with version 13.3.0 Verified everything @cupcakepanda89 suggested [here](https://github.com/cypress-io/cypress/issues/27712#issuecomment-1699998675)

**Comment by jennifer-shehane** [comment]
@kzs61 Could you open an issue with the exact error message you're seeing? [DEBUG logs](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) would be helpful too. This exact cause was fixed, so likely there is something specific with your run that we need to investigate. We're prioritizing these errors and will prioritize if you can get us the details. Thanks!

**Comment by kzs61** [comment]
> @kzs61 Could you open an issue with the exact error message you're seeing? [DEBUG logs](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) would be helpful too. This exact cause was fixed, so likely there is something specific with your run that we need to investigate. We're prioritizing these errors and will prioritize if you can get us the details. Thanks!

@jennifer-shehane It's 'GLIBC_2.29' not found (Alpine image latest version 3.18, node v16)

**Comment by jennifer-shehane** [comment]
@kzs61 You can track the GLIBC error here: https://github.com/cypress-io/cypress/issues/27902 We have a fix that we hope to release soon for this.
