### ISSUE TITLE
After upgrading to cypress 13, all test fail with blank page after the first IT

### ISSUE THREAD

**Issue by albanx** [cypress-io/cypress#27726]
### Current behavior

After I upgrade to Cypress 13, my test start failing, due to the testIsolation concept introduced.

I really believe the testIsolation is fine as far as the isolation is applied between test runs (ex, a full spec file) but I really not understand how this helps inside the same test file, for each IT.

[While I like and I understand the test isolation concept, I really do not understand ](https://docs.cypress.io/guides/core-concepts/test-isolation)

testIsolation should be applied at spec level not at IT level, all my tests now are broken due to this change, and also becomes harder now to chunk a single test in steps.

### Test code to reproduce

Run this test

For example how would this test look now in Cypress 13 to pass?
```js
describe('Test home page', () => {
  before(() => {
    cy.visit('http://localhost:4200');
  });

  it('shows nav menu on top', () => {
    cy.get('.desktop-only .main-nav.nav li').should('have.length', 8);
    cy.get('.desktop-only .main-nav.nav li').eq(1).should('have.text', 'Shitje');
    cy.get('.desktop-only .main-nav.nav li').eq(6).should('have.text', 'Hyr');
  });

  it('can search cities in the input select with autosuggest', () => {
    const newItem = 'Tiran';
    cy.get('.xselect-input-wrapper input').focus();
    cy.get('.xselect-input-wrapper input').type(`${newItem}`, { scrollBehavior: false });
    cy.get('.xselect-option').should('length.gte', 1).first().contains(newItem);
  });

  it('loads the featured properties', () => {
    cy.get('.featured-properties').scrollIntoView();
    cy.get('.featured-properties a').should('have.length', 3);
  });

  it('loads the recent property card', () => {
    cy.get('[data-testid="recent-props"]').scrollIntoView();
    cy.get('.homepage-recent-properties .property-card').should('have.length', 7);
  });

  it('loads the most searched locations', () => {
    cy.get('.home-popular').scrollIntoView();
    cy.get('.popular-area').should('have.length', 10);
  });
});
```

### Cypress Version

13

### Node version

v18.15.0

### Operating System

Window12

**Comment by nagash77** [comment]
Hi @albanx you are able to [disable  test isolation](https://docs.cypress.io/guides/core-concepts/test-isolation#Test-Isolation-Disabled) if it does not suit your use case.

**Comment by albanx** [comment]
I know, but even if I disable the test isolation, it is still breaks. The test isolation before was by default per test file.

Now if I disable it, it keeps the session for all tests, mixing up everything. I cannot find a config way to have the test isolation per spec

**Comment by AtofStryker** [comment]
@albanx what version of cypress are you upgrading from?

**Comment by albanx** [comment]
version 6 :D

**Comment by albanx** [comment]
The workaround I am using to fix this problem right now is adding these lines to every tests that uses login:

```
  before(() => {
    cy.visit('http://localhost:4200');
    cy.clearAllLocalStorage()
    cy.visit('http://localhost:4200');
    cy.get('a[data-testid="account-link"]').click();
  });
```

**Comment by AtofStryker** [comment]
@albanx that is quite the jump, which makes sense why you are seeing this as we incorporated testIsolation and other defaults in Cypress `v12`.  You likely will need to refactor your tests to work to some degree as there has been several breaking changes since then.

**Comment by albanx** [comment]
I have just 6 tests in my projects, the issue is no upgrading cypress, tests still pass correctly now with some trick.

My issue is that now testIsolation, does not make sense at `it` level. From a point of view of organizing the code, and having the tests splitting in steps, which help to write clean tests. testIsolation means that you have to put everything inside the same `it` statement, not allowing to apply separation of concern or some minimal code organisation.

While I can adopt page object patter to organize common tests, code, still for me an E2E test should have clear separate steps on `it` statement, ex
```
it('user clicks on change profile`)
it('user clicks input and adds new alias..')
it('user saves profile...')
```

**Comment by AtofStryker** [comment]
@albanx you should be at to turn off test isolation at the describe level which should allow you to handle your test the way you like.

```
describe('no test isolation', { testIsolation: false }, () => {
  it('user clicks on change profile`)
  it('user clicks input and adds new alias..')
  it('user saves profile...')
})
```

**Comment by albanx** [comment]
@AtofStryker I was pretty sure I tried that and did not work, but I will give another try now, that would be the prefect solution

**Comment by the0neWhoKnocks** [comment]
Just wanted to say thanks for this ticket. I was in the same boat (upgraded from `6.3.0` to `13.3.0`), and could not figure out why the page that I loaded in a top level `before` was being unloaded after the first `it` had run.

Not sure what the thinking was behind `testIsolation`, but I'm glad I could easily disable it. States and data bleeding into tests unexpectedly seems like code smell. Generally I just have setup/teardown functions for `describe`s so I know what's being set up or removed for each test context.

**Comment by albanx** [comment]
Sorry for commenting again, since I cannot write really good test code with this feature. Right now I have two issues:
1) Test Isolation should not be at `it` level. I am wondering how does a E2E test file look today. For example a test like this:
```js
/// <reference types="cypress" />

describe('Homezone.al account login', () => {
  before(() => {
    cy.visit('http://localhost:4200');
    cy.clearAllLocalStorage();
    cy.clearLocalStorage();

    cy.window().then((win) => {
      win.sessionStorage.clear()
    });
  });

  it('open login page', () => {
    cy.get('a[data-testid="account-link"]').click();
  });

  it('login', () => {
    cy.intercept('POST', '/auth*').as('login');

    cy.get('input[data-testid="email"]').type('test@email.com');
    cy.get('input[data-testid="password"]').type('12345xxx');
    cy.get('button[data-testid="login-button"]').click();
    cy.wait('@login').its('response.statusCode').should('eq', 200);
  });

  it('Property page opens', () => {
    cy.get('.toolbar-left').should('length.gte', 1);
    cy.get('.free-text-filter').should('length.gte', 1);
  });

  it('logs out', () => {
    cy.get('.spinner-wrapper', { timeout: 10000 }).should('not.exist');
    cy.get('[id="mat-tab-link-1"]').click();
    cy.get('button[data-testid="logout-btn"]').click();
    cy.get('button[data-testid="confirm-btn"]').click();
  });
});
```
does not work anymore with test isolation.
y
2) Issue number 2 is that after disabling test isolation, I have no way to clear the localstorage. If the above test fails, the user remains logged in, even if I try to clear all the storages.

**Comment by HofmannZ** [comment]
@albanx - Over the past few months, we've transitioned our test suite to Playwright, as we no longer feel that Cypress aligns with our evolving needs. They have great test isolation 🙌

**Comment by albanx** [comment]
@HofmannZ I do use Playwright at work (kind of a must since I work for microsoft), but for my side projects I still use Cypress, I like a bit more the syntax and the UI, and more mature. 
will probably evaluate too

**Comment by jennifer-shehane** [comment]
@albanx You would remove the clearing of localStorage since this is done automatically between tests. Add a visit to each it block. To optimize further, make use of `cy.session` to define the 'login steps' so that you don't need to login on every test. https://docs.cypress.io/api/commands/session

```js
/// <reference types="cypress" />

describe('Homezone.al account login', () => {
  it('open login page', () => {
    cy.visit('http://localhost:4200/');
    cy.get('a[data-testid="account-link"]').click();
  });

  it('login', () => {
    cy.visit('http://localhost:4200/');
    cy.intercept('POST', '/auth*').as('login');

    cy.get('input[data-testid="email"]').type('test@email.com');
    cy.get('input[data-testid="password"]').type('12345xxx');
    cy.get('button[data-testid="login-button"]').click();
    cy.wait('@login').its('response.statusCode').should('eq', 200);
  });

  it('Property page opens', () => {
    cy.visit('http://localhost:4200/');
    cy.get('.toolbar-left').should('length.gte', 1);
    cy.get('.free-text-filter').should('length.gte', 1);
  });

  it('logs out', () => {
    cy.visit('http://localhost:4200/');
    cy.get('.spinner-wrapper', { timeout: 10000 }).should('not.exist');
    cy.get('[id="mat-tab-link-1"]').click();
    cy.get('button[data-testid="logout-btn"]').click();
    cy.get('button[data-testid="confirm-btn"]').click();
  });
});
```

**Comment by albanx** [comment]
@jennifer-shehane That is repeating code, violating the DRY principle.

An E2E test, it is usefull to organise the code with separate `it` statement, for better readability and separation. I can understand in unit testing we want `it` to be isolated, but that is not the case of an E2E test, which can be long and can require many steps.

I really think the testIsolation at `it` level was a wrong decision in Cypress. An E2E test is a full user flow made of steps.

**Comment by jennifer-shehane** [comment]
@albanx That's why I would recommend adding the login steps within session and just calling that code in each test as mentioned in my first comment: https://docs.cypress.io/api/commands/session
