### ISSUE TITLE
Add a configuration option to fail the build on CI if you accidentally left test.only in the source code.

### ISSUE THREAD

**Issue by longmauriceproj** [cypress-io/cypress#27728]
### What would you like?

Add a boolean configuration option to exit with an error if any tests or groups are marked as [`.only`](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Excluding-and-Including-Tests). Useful on CI.

### Why is this needed?

Helps catch if `.only` was accidentally left in test suite on CI--this can prevent you from committing focused `.only` tests to CI, which may prevent your entire test suite from running.

There is an eslint plugin that can provide warnings i.e. [no-only-tests](https://www.npmjs.com/package/eslint-plugin-no-only-tests) but I believe that this should be a native configurable option. Developers shouldn't need an extra dependency to do something specific and integral to cypress.

This configuration is natively supported with the `forbidOnly` option in playwright.

**Comment by jennifer-shehane** [comment]
Hi, since there are tools that provide this functionality today, we won’t be considering this as a feature. Thanks for the input!
