### ISSUE TITLE
Element detached from DOM

### ISSUE THREAD

**Issue by mmonteiroc** [cypress-io/cypress#27739]
### Current behavior

In cypress 12.17.4
We have the following code

```
Cypress.Commands.add('safeClick', { prevSubject: true }, $element => {
  cy.get($element).scrollIntoView();
  cy.get($element).click();
});
```

And we are getting the following error 
```
CypressError: Timed out retrying after 4050ms: `cy.click()` failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:
> cy.get(<label.filter-item-label>)
We initially found matching element(s), but while waiting for them to become actionable, they disappeared from the page. Common situations why this happens:
- Your JS framework re-rendered asynchronously
- Your app code reacted to an event firing and removed the element
You can typically solve this by breaking up a chain. For example, rewrite:
> `cy.get('button').click().click()`
to
> `cy.get('button').as('btn').click()`
> `cy.get('@btn').click()`
```
The problem comes that we already separated the query of the element into 2 as proposed in your documentation / error

### Test code to reproduce

Cypress.Commands.add('safeClick', { prevSubject: true }, $element => {
  cy.get($element).scrollIntoView();
  cy.get($element).click();
});

### Cypress Version

12.7.4

### Node version

v18.17.1

### Operating System

Azure Pipelines - windows-latest

**Comment by jennifer-shehane** [comment]
@mmonteiroc You’ll need to provide a fully reproducible example where we can run and see the errors in order for us to investigate.

**Comment by jennifer-shehane** [comment]
Closing as stale.
