### ISSUE TITLE
Cypress couldn't able to detect tests

### ISSUE THREAD

**Issue by SanthoshS20** [cypress-io/cypress#27734]
### Current behavior

Cypress couldn't able to detect tests in my project folder with the latest cypress version. I tried to implement basic api testing with cypress, but its ruined my whole day. When i switch to the version 12.4.0, its worked fine

GUI mode result
```
Error: Webpack Compilation Error
Module build failed (from ../../../.cypress-cache/13.1.0/Cypress/resources/app/node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'fs/promises'
```

Headless mode result
```
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

### Test code to reproduce

api.cy.js file
```
/// <reference types="cypress" />

describe("API Testing", () => {
    it("POST Request", ()=> {
        cy.request({ url: 'auth', body: {"username" : "admin","password" : "password123"}, headers: {"Content-Type": "application/json"}, method: 'POST'}).as('create_token')
        cy.get('@create_token').its('status').should('equal', 200)
        cy.get('@create_token').then((response) => {
            cy.log(response)
            cy.log(JSON.stringify(response))
            expect(response.body.token).should('contain', 'abc123')
        })
    })
})
```

cypress.config.js file
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    baseUrl: 'https://restful-booker.herokuapp.com/',
    video: false,
    screenshotOnRunFailure: false,
    testIsolation: false
  },
});
```

### Cypress Version

13.1.0

### Node version

12.22.1

### Operating System

Windows 10

**Comment by MikeMcC399** [comment]
@SanthoshS20 

- Node.js `12` reached [end-of-life](https://github.com/nodejs/release#release-schedule) on Apr 30, 2022 and is no longer supported by Cypress. See Cypress documentation [Getting Started > Installing Cypress > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs). Support for Node.js `12` was dropped in cypress@12.0.0 according to the [Cypress 12.0.0 changelog](https://docs.cypress.io/guides/references/changelog#12-0-0).

- [Cypress 13.0.0 changelog](https://docs.cypress.io/guides/references/changelog#13-0-0) says:
> Node 14 support has been removed and Node 16 support has been deprecated. Node 16 may continue to work with Cypress `v13`, but will not be supported moving forward to closer coincide with [Node 16's end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) schedule. It is recommended that users update to at least Node 18.

- See also related comment in https://github.com/cypress-io/cypress/pull/27668#issuecomment-1693722639

**Comment by MikeMcC399** [comment]
Attempting to install `cypress@13.1.0` using npm under Node.js `12.22.1` gives the following warning:

> npm WARN notsup Unsupported engine for cypress@13.1.0: wanted: {"node":"^16.0.0 || ^18.0.0 || >=20.0.0"} (current: {"node":"12.22.1","npm":"6.14.12"})
> npm WARN notsup Not compatible with your version of node/npm: cypress@13.1.0

Yarn will refuse to install `cypress@13.1.0` under Node.js `12.22.1`

> error cypress@13.1.0: The engine "node" is incompatible with this module. Expected version "^16.0.0 || ^18.0.0 || >=20.0.0". Got "12.22.1"
> error Found incompatible module.

**Comment by MikeMcC399** [comment]
@SanthoshS20 

Please update to at least Node.js `18`, retest and then let us know if that solves your issue.

**Comment by marwadi-rovi** [comment]
Is anybody facing the same issue for Node.js 14, is NodeJS 14 is feasible with Cypress 13?

**Comment by MikeMcC399** [comment]
@marwadi-rovi 

> Is anybody facing the same issue for Node.js 14, is NodeJS 14 is feasible with Cypress 13?

Cypress `13.x` is not compatible with Node.js `14`.

**Comment by EmilyThomasPCTY** [comment]
I stumbled upon this issue while researching an issue I am having while upgrading from 9.7.0 to 13.13.3 (don't judge!) I thought everything was configured correctly, but when I attempt to run tests, an error is thrown from babel-loader. I am on node 18.18.0. Any advice is appreciated!

`Webpack Compilation Error
Module build failed (from ../../../../xxx/xxx/AppData/Local/Cypress/Cache/13.3.3/Cypress/resources/app/node_modules/babel-loader/lib/index.js):
TypeError: Ajv is not a constructor`
