### ISSUE TITLE
Getting reference error using @cypress/grep 

### ISSUE THREAD

**Issue by chandresh-appdirect** [cypress-io/cypress#27737]
### Current behavior

```javascript
ReferenceErrorStack Trace Viewer
Stack Trace Viewer
ReferenceError: it is not defined
 in @cypress/grep/src/support.js — line 12

```

### Desired behavior

It should run properly

### Test code to reproduce

https://npm.runkit.com/%40cypress%2Fgrep

```js
require("cypress/package.json"); // cypress is a peer dependency. 
var grep = require("@cypress/grep")

// Test case with a "smoke" tag
it('test1', { tags: '@smoke' }, () => {
  cy.log('test1');
});

// Test case without any tags
it('test2', () => {
  cy.log('test2');
});
```
### Cypress Version

12.9.0

### Node version

v14.21.3

### Operating System

macOS Ventura 13.5

**Comment by AtofStryker** [comment]
Hi @seekchandresh . Thank you for opening an issue. I created a small reproduction repository  https://github.com/AtofStryker/cypress-issue-27737 as I am not sure what the runkit is trying to accomplish as it doesn't have full access to the context I believe. The project seems to work. Can you help me fill in the blanks to reproduce the failure?

**Comment by chandresh-appdirect** [comment]
Somehow its working for me as of now after npm install (again). So closing this issue.
