### ISSUE TITLE
Cypress intercept stops at some point

### ISSUE THREAD

**Issue by berse2212** [cypress-io/cypress#27748]
### Current behavior

Currently we have the problem of flaky tests on our Jenkins especially if the Jenkins is rather busy. After some investigation the problem could be identified to a missing "X-E2E-User" header that we add to every request via cy.intercept (in a global beforeEach in e2e.js):

```
beforeEach( function () {
  const user = "user";
  cy.intercept({ url: '*', resourceType: /xhr/ }, (req) => {
    req.headers['X-E2E-User'] = user;
  }).as('setUser');
});

```

Since this only sometimes occurs the root of the problem is really hard to identify, but I tried to emulate the problem inside a cypress-test-tiny project.

After playing around for a bit I figured that at a certain (random) point the cy.intercept just stops working. Neither do the requests appear in the gui nor the header gets added. However this only happens if I send out a lot of requests. The amount is different each time and also changes depending on my machines load (e.g. cy gui or writing debug logs to console make it break earlier).

Sadly I cannot 100% confirm is this is really the problem we are facing currently (due to the complex and random nature) but it's at least similar.

### Desired behavior

cy.intercept should always intercept requests and not break at some point.

### Test code to reproduce

https://github.com/berse2212/cypress-test-tiny

The cypress-test-tiny project I found my results in.

### Cypress Version

13.1.0

### Node version

v18.15.0

### Operating System

10.0.19044.0

### Debug Logs

```shell
too long see appended file
```

### Other

This problem existed on version 12 and 13 problably also earlier since we deal with it quite so time now.
[logs.txt](https://github.com/cypress-io/cypress/files/12524175/logs.txt)

**Comment by nagash77** [comment]
Hi @berse2212 this seems to me to be the same issue as reported here https://github.com/cypress-io/cypress/issues/26431.  Are you seeing the same behavior as described in that issue?  If so, can you close this issue and add your experience to that ticket to better organize and keep track of the impact of this behavior.

**Comment by berse2212** [comment]
Hello @nagash77 ,

I am not quite sure if this issue is the same however it seems unlikely. I tried adding cy.wait and a similar assertion to my tests but those always ran into a timeout. It's probably more similar to #27648 but I couldn't find any reset:server:state nor does waiting an arbitrary time fix my issue.

**Comment by schrew-pfizer** [comment]
We've got the same issue currently when we use cy.intercept and call the same route multiple times where the intercept is triggered. During our jenkins builds we see randomly some tests start failing because the entire app is frozen and other checks get timeouts. Often just making a new build without even doing any codechange suddenly fixes the failing test.
