### ISSUE TITLE
Error in absolute file path of component-index.html

### ISSUE THREAD

**Issue by wiegell** [cypress-io/cypress#27750]
### Current behavior

This issue tried to solve the resolution of component-index.html:
https://github.com/cypress-io/cypress/issues/26400

However the problem is still present. When setting:
```
  component: {
    indexHtmlFile: <SOME ABSOLUTE PATH>,
  }
```

You get an error along the lines of:
```
ERROR in   Error: Child compilation failed:
  Module not found: Error: Can't resolve 'USERHOME/cypress-example/  someorg/libs/my-standalone-lib/USERHOME/cypress-example/someorg/li  bs/my-standalone-lib/cypress/support/component-index.html' in '/USERHOME/t  rifork/cypress-example/someorg'
  ModuleNotFoundError: Module not found: Error: Can't resolve '/USERHOME/cypress-example/someorg/libs/my-standalone-lib/USERHOME/cypre  ss-example/someorg/libs/my-standalone-lib/cypress/support/component-index.html  ' in '/USERHOME/cypress-example/someorg'
```

The problem is resolved if instead you use a relative path to the component-index.html:
```
  component: {
    indexHtmlFile: './cypress/support/component-index.html',
  },
```

The issue is bad because nx uses an absolute path, so no component testing is working via nx

### Test code to reproduce

Repro:
https://github.com/wiegell/cypress-bug
Run:
`yarn nx run my-standalone-lib:component-test`

This repro has been made with:
- Fresh nx repo
- Generated standalone angular component via nx
- Generated nx component testing into that lib via nx

### Cypress Version

13.1.0, also tried 12.17.4, same problem.

### Node version

v18.17.1

### Operating System

macos 13.4.1

### Debug Logs

[gist](https://gist.github.com/wiegell/f79c99c522f973351cfc6464f4ae06af)

**Comment by wiegell** [comment]
@lmiller1990 sorry for the ping, but since you solved the original issue you might find this relevant.

**Comment by lmiller1990** [comment]
Thanks for filing this issue. I'm not working on Cypress any more, so I'm not sure I'll be able to look at this one in the immediate future. It should be a reasonably easy fix though, take a look at the previous PR and see if we can check if it's absolute path, and handle that correctly.

**Comment by Roemer** [comment]
Is this working with Cypress 12.17.3? We have a very similar issue, where we define the indexHtmlFile like: `indexHtmlFile: __dirname + '/cypress/support/component-index.html'` which seems to work up until 12.17.3 and now with 12.17.4 or higher it fails because it tries to lookup the component-index.html in a combined path from the current project + the absolute path from our config.

**Comment by Roemer** [comment]
After further analysis, the fix from https://github.com/cypress-io/cypress/issues/26400 actually introduced this bug.
The fix just plain simply joins the project path and the defined file path, if it happens to be absolute, it just breaks.

**Comment by lstkz** [comment]
I have the same issues. Upgraded from v10 to v13.5.

indexHtmlFile throws error
```js
indexHtmlFile: path.join(__dirname, 'cypress/index.html'),
```

supportFile works in the same way
```js
supportFile: path.join(__dirname, 'cypress/support.js'),
```

**Comment by Roemer** [comment]
I created a very simple fix for it in the PR: https://github.com/cypress-io/cypress/pull/28324 but I could not yet test it.
