### ISSUE TITLE
Cypress stuck on Your tests are loading after upgrade

### ISSUE THREAD

**Issue by epacke** [cypress-io/cypress#27769]
### Current behavior

I'm trying to bump cypress version from 9.5.2 to 13.1.0 and followed the upgrade guide (renaming files from .spec.ts to .cy.ts etc).

When I launch cypress and try to start an e2e test it gets stuck at "Your tests are loading".
Tests worked in 9.5.2.

### Desired behavior

Ideally the tests would run :)

### Test code to reproduce

I created a branch and pushed the code there:
https://github.com/net-utilities/BigIPReport/tree/Bumping-cypress

To reproduce you can:

1. Check out the branch
2. Start the app by running `npm run start` (optional, Cypress gets stuck anyhow)
3. The start cypress with npx cypress open
4. Pick E2E Testing
5. Start in Chrome
6. Click on ie. direct-links
7. Cypress is stuck in "Your tests are loading..."

### Cypress Version

13.1.0

### Node version

v18.16.0

### Operating System

macOS 13.5.1

### Debug Logs

[cypress-debug.log](https://github.com/cypress-io/cypress/files/12552913/cypress-debug.log)

### Other

I do not run any security software at the moment to remove that from the equation.
I have tried to restart the computer just to be sure.

**Comment by muratkeremozcan** [comment]
+1

Reproduced in a large repo: [400+ CyCT examples](https://github.com/muratkeremozcan/cypress-react-component-test-examples/pull/790).

In CI it hangs in some of the machines. If you have a small test suite, perhaps you can get away without seeing the hang.

Locally, running headless it will hang half way through a large test suite.

In open mode, it will hang after switching a few tests, infinitely showing "Your tests are loading".

```bash
git clone https://github.com/muratkeremozcan/cypress-react-component-test-examples

cd cypress-react-component-test-examples

# uses node 16
nvm use

yarn install

yarn cy:run-ct-fast

# or in open mode, switch a few tests, you will see it eventually

yarn cy:open


```

The master branch has 12.17.4, working stably.
We also had the repo stable during v13 beta.

**Comment by audriusnavickasDB** [comment]
I and my team are facing the same issue as well. It is working fine on any 12.12.0+ version just fine, but when upgrading to 13.0.0+ it breaks down and we are seeing the same "Your tests are loading" screen and nothing is happening. Tried to investigate and found out that the main issue for us is that for baseUrl we use url with authentication. For example: https://admin:admin@anywebsite.com this would break everything. If the credentials are removed and plain url is used, everything just works fine.

As I see from the provided repo I assume there is such usage as well and it might be identical case. I had registered such issue for Firefox browser specifically a while back: https://github.com/cypress-io/cypress/issues/24236, but it had not much attention. Now it looks like now it affects all of the browsers :) 

So just wondering if such syntax is not supported anymore by the Cypress and it is not documented anywhere or it is a serious bug :)

**Comment by nagash77** [comment]
Hi folks, I believe this is similar to this ticket that is open https://github.com/cypress-io/cypress/issues/27722.  [Sharing your debug logs](https://github.com/cypress-io/cypress/issues/27722#issuecomment-1709132398) would help us troubleshoot.

**Comment by SquirrelCoder** [comment]
We're experiencing the same issue, and our application uses Basic HTTP Auth with credentials sent in the standard HTTP 'Authorization' header. Everything works smoothly with Cypress 12, but when we upgraded to Cypress 13, we encountered a problem where the test just hangs indefinitely.

**Comment by ryanthemanuel** [comment]
Hi @epacke thanks for the repo. I'm wondering if there was something that didn't get pushed on the branch you linked to? I'm still seeing Cypress as 9.5.2: https://github.com/net-utilities/BigIPReport/blob/Bumping-cypress/package.json#L36

**Comment by epacke** [comment]
Oh darn, let me fix that!

**Comment by epacke** [comment]
I pushed the latest code now. Apologies!

**Comment by mschile** [comment]
Hi @muratkeremozcan 👋, I was able to reproduce your hang using your repro. We will be making changes to Cypress to address these hangs so they no longer occur but in the meantime you can make the following changes to prevent the hangs.

The [EffectOnceComponent](https://github.com/muratkeremozcan/cypress-react-component-test-examples/blob/a0a97286d1d3a1ab3873abc9bc79da32d9afb9da/cypress/component/hooks/kyle-wds/custom-hooks/20-useEffectOnce/EffectOnceComponent.js#L7) should not be returning a non-function for it's [useEffect](https://react.dev/reference/react/useEffect#parameters). It should be:

```js
- useEffectOnce(() => alert("Hi"))
+ useEffectOnce(() => { alert("Hi") })
```

This was causing an error when unmounting the component that in turn caused Cypress to hang by not moving onto the next test.

The other issue was with this [intercept](https://github.com/muratkeremozcan/cypress-react-component-test-examples/blob/a0a97286d1d3a1ab3873abc9bc79da32d9afb9da/cypress/component/redux-FP-arch-with-React-Redux-book/ch12-weather-Rpipe-Rcompose-partial-curry/App.cy.jsx#L14). Instead of intercepting all requests, you can intercept the requests you are interested in:


```js
- cy.intercept('GET', '*', { body: response }).as('axios-response')
+ cy.intercept('GET', 'http://api.openweathermap.org/**/*', { body: response }).as('axios-response')
```

After making these changes, I was able to run all of the component tests without any hangs.

**Comment by mschile** [comment]
Hi @epacke 👋, I took a look at your project and the issue doesn't appear to be related to Cypress 13 as I was able to reproduce it in earlier versions. The issue appears to be related to the typescript config. Can you try removing your [baseUrl](https://github.com/net-utilities/BigIPReport/blob/Bumping-cypress/tsconfig.json#L24) config and see if that resolves the issue?

**Comment by mschile** [comment]
Hi @audriusnavickasDB 👋, thanks for your investigation. We were able to reproduce your hang in v13 when setting the baseUrl to a url with authentication. We are currently working on a fix.

**Comment by epacke** [comment]
That did it. Thanks a bunch!

**Comment by ryanthemanuel** [comment]
@audriusnavickasDB I believe your issue will be fixed with: https://github.com/cypress-io/cypress/pull/27781

**Comment by muratkeremozcan** [comment]
> Hi @muratkeremozcan 👋, I was able to reproduce your hang using your repro. We will be making changes to Cypress to address these hangs so they no longer occur but in the meantime you can make the following changes to prevent the hangs.
> 
> The [EffectOnceComponent](https://github.com/muratkeremozcan/cypress-react-component-test-examples/blob/a0a97286d1d3a1ab3873abc9bc79da32d9afb9da/cypress/component/hooks/kyle-wds/custom-hooks/20-useEffectOnce/EffectOnceComponent.js#L7) should not be returning a non-function for it's [useEffect](https://react.dev/reference/react/useEffect#parameters). It should be:
> 
> ```js
> - useEffectOnce(() => alert("Hi"))
> + useEffectOnce(() => { alert("Hi") })
> ```
> 
> This was causing an error when unmounting the component that in turn caused Cypress to hang by not moving onto the next test.
> 
> The other issue was with this [intercept](https://github.com/muratkeremozcan/cypress-react-component-test-examples/blob/a0a97286d1d3a1ab3873abc9bc79da32d9afb9da/cypress/component/redux-FP-arch-with-React-Redux-book/ch12-weather-Rpipe-Rcompose-partial-curry/App.cy.jsx#L14). Instead of intercepting all requests, you can intercept the requests you are interested in:
> 
> ```js
> - cy.intercept('GET', '*', { body: response }).as('axios-response')
> + cy.intercept('GET', 'http://api.openweathermap.org/**/*', { body: response }).as('axios-response')
> ```
> 
> After making these changes, I was able to run all of the component tests without any hangs.

Thanks for the suggestions. They worked.
https://github.com/muratkeremozcan/cypress-react-component-test-examples/pull/792

**Comment by GhostX101** [comment]
Please what's the solution? 

I'm actually facing the same issue here. ![image](https://github.com/user-attachments/assets/bd62ec06-ad65-476d-90cb-b497625262c3)

**Comment by martinsdad** [comment]
> Please what's the solution?
> 
> I'm actually facing the same issue here. ![image](https://github.com/user-attachments/assets/bd62ec06-ad65-476d-90cb-b497625262c3)

I have same issue
