### ISSUE TITLE
.should('contain.text') fails when checking if number is formatted with blankspace 'NN NNN' 

### ISSUE THREAD

**Issue by o92design** [cypress-io/cypress#27760]
### Current behavior

We're trying to verify cell value in an angular table '<td.mat-cell.cdk-cell.atom-app-table-cell.cdk-column-totalConsumptionUsed.mat-column-totalConsumptionUsed.ng-star-inserted>'

When making a .should('contain.text', '188 875') we get a failed assertion even though the text contains the value.
Message:  expected '<span>' to contain text '188 875', but the text was '&nbsp;188 875'

The expect does work however if we utilize dates / timestamps etc

### Desired behavior

The assert should pass when having a string number like '188 875'

### Test code to reproduce

```
function retrieveColumnCell(columnId: string, rowNumber = 1) {
    columnId = columnElement + columnId;
    return cy.get(`:nth-child(${rowNumber})` + ' > ' + columnId);
}
```

```
retrieveColumnCell(
                    this._columnId,
                    this._rowNumber
                ).should('contain.text', this._correctValue);
```

### Cypress Version

13.1

### Node version

v18.17.1

### Operating System

Windows 11 Pro 22621.2134

**Comment by o92design** [comment]
I asked chatgpt to make me a small code snippet to reproduce the problem:
A snippet which was generate but I couldn't get to run was
`cy.get('body').then(($body) => {
  const $tempElement = Cypress.$('<div></div>').text('188 875');`
  
`  $body.append($tempElement);`
`  cy.wrap($tempElement).should('contain.text', '188 875');`
  
`  $tempElement.remove();`
`});`

Chai snippet which does work as expected however:
`const textElement = '188 875';
        expect(textElement).to.contain('188 875');`

**Comment by nagash77** [comment]
Hi @o92design are you seeing the same behavior in version 13.1?

**Comment by o92design** [comment]
Yes @nagash77 , tested today and the same behaviour is in 13.1

**Comment by o92design** [comment]
Anyone who can review this? or maybe test out in [partial match test](https://github.com/cypress-io/cypress/blob/356edfc5e9b52bdf4dc42654314c9aa0ab829bbc/packages/driver/cypress/e2e/commands/assertions.cy.js#L1854C40-L1854C40)?

**Comment by astone123** [comment]
@o92design I was unable to reproduce this immediately. 

Could you provide the HTML markup for the element that you are asserting against? If you click on the "get" command in the command log, it should print the markup for the element to your browser console.

**Comment by o92design** [comment]
The dom is an angular table cell where I make a contain:
/html/body/app-root/app-shell/mat-sidenav-container/mat-sidenav-content/mat-sidenav-container/mat-sidenav-content/mat-sidenav-container/mat-sidenav-content/main/section/app-counters-and-sensors/app-atom-report-presenter/div/mat-card/mat-card-content/div/app-atom-realtime-table/form/div/div/table/tbody/tr[2]/td[8]
```js
cy.get('.atom-app-table-title-row > .cdk-column-totalConsumptionUsed')
```
```html
<td role="cell" mat-cell="" class="mat-cell cdk-cell atom-app-table-cell cdk-column-totalConsumptionUsed mat-column-totalConsumptionUsed atom-table-indent-first-child ng-star-inserted"><!----><app-atom-styled-table-cell _nghost-ng-c2544097498="" class="ng-star-inserted"><div _ngcontent-ng-c2544097498="" class="atom-styled-table-text-container ng-star-inserted"><div _ngcontent-ng-c2544097498="" class="atom-styled-table-text-and-icon-subcontainer"><!----><!----><span _ngcontent-ng-c2544097498="" data-cypress-el="true"> 188&nbsp;875</span></div><div _ngcontent-ng-c2544097498="" class="atom-styled-table-cell-subvalue"> 2013-08-28 02:00:00 </div></div><!----><!----><!----><!----><!----><!----></app-atom-styled-table-cell><!----><!----><!----><!----><!----></td>
```

expected '< span >' to contain text '188 875', but the text was ' 188 875'

EDIT: I also checked the hmtl value and there is the html space inside - tested to add `&nbsp;` to the verification but it still fails
