### ISSUE TITLE
Running cypress from Raspberry bullseye with firefox-esr

### ISSUE THREAD

**Issue by sahar1989** [cypress-io/cypress#27772]
### Current behavior

Hello , 
I have problem with lunching cypress in raspberry bullseye through firefox-esr,

I append a firefox-esr object to the cypress.config.object.browsers
it appears in the browser lists but when I click to run test
it displays this error , and I am wondering sometimes I works ?!!!! 
![image](https://github.com/cypress-io/cypress/assets/24430120/be094412-484c-44c9-9e2f-1417b4820b76)

firefox-esr versions: 102.15.0esr (64-bit)

Thanks in advanced,

### Test code to reproduce

Only install firefox-esr in rapberry with 
sudo apt install firefox-esr

then define and append the object browser to config.browsers objects
"browser": {
    "name": "firefox-esr",
    "channel": "esr",
    "family": "firefox",
    "path": "/usr/bin/firefox-esr",
    "displayName": "Firefox ESR",
    "version": "102.15.0esr",
    "majorVersion": "102"
  }

### Cypress Version

cypress 11, 12, and 13

### Node version

v20.5.1

### Operating System

Raspberry Bullseye

**Comment by jennifer-shehane** [comment]
We don’t guarantee testing will work on this OS/browser. Closing as this is not part of our supported environments.
