### ISSUE TITLE
Certain website not opening in Cypress

### ISSUE THREAD

**Issue by mohdbilal2000** [cypress-io/cypress#27783]
### Current behavior

I tried to open "https://raceuat.yesbank.in/ybl-qr/" in cypress using cy.visit(). For some reason this website is not opening in cypress but other websites are opening in it.

### Desired behavior

In this situation, the application should run the website and should not show any errors in it.

### Test code to reproduce

it("Google Search", () => {
cy.visit("https://raceuat.yesbank.in/ybl-qr/");
});

### Cypress Version

16.16.0

### Node version

18.16.0

### Operating System

Windows 11

**Comment by MikeMcC399** [comment]
@mohdbilal2000 

Can you confirm which version of Cypress you are using, as the one you stated `16.16.0` is not a valid version. The current latest version is `13.1.0`.

Do you control the website https://raceuat.yesbank.in/ybl-qr/?

If not, then the following documentation is relevant to you:

https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test#Step-1-Visit-a-page which offers the website https://example.cypress.io for training purposes.

It explains also about "Testing Apps You Don't Control" and mentions:

- They may detect you are a script and block your access.
- They may have security features enabled which prevent Cypress from working.

There is also a section https://docs.cypress.io/guides/references/best-practices#Visiting-External-Sites regarding "Anti-Pattern: Trying to visit or interact with sites or servers you do not control."

**Comment by mohdbilal2000** [comment]
16.16.0 @MikeMcC399 
Can you try this opening in your machine?

**Comment by MikeMcC399** [comment]
@mohdbilal2000 

> 16.16.0

What was the meaning of this number? To find out the version of Cypress you can look at the top of the Cypress desktop app which you start with
```bash
npx cypress open
```
or execute

```
$ npx cypress version
Cypress package version: 13.2.0
Cypress binary version: 13.2.0
Electron version: 25.8.0
Bundled Node version:
18.15.0
```

> Can you try this opening in your machine?

I can't see an answer to the question "Do you control the website https://raceuat.yesbank.in/ybl-qr/?", however the site does not respond, so there is nothing that Cypress can do about this.

**Comment by mohdbilal2000** [comment]
@MikeMcC399 . Well I have been testing this website as a manual tester thus thought to go with automation to save time and make work more efficient, but this website is not supported by cypress i guess that too, still would like to know more about the url supported by cyrpess.io for better understanding.

**Comment by MikeMcC399** [comment]
@mohdbilal2000 

You can check with the maintainers of the website server if you are employed as a manual tester.

Compare executing this command, which never responds

```shell
curl https://raceuat.yesbank.in/ybl-qr/ -v
```

to the same command on the Cypress learning site

```shell
curl https://learn.cypress.io
```

which displays the contents of the website in raw format. This is all independent of Cypress testing. `curl` is a standard URL testing utility. If your website does not respond to curl, then Cypress will not be able to work with it either.

If you need any additional help, you can also engage with the Cypress technical community on Discord:
[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

**Comment by mohdbilal2000** [comment]
thanks for the help, really appreciate your help, kind of started with open source and you are the first person I have talked. Will be glad if I got to return the favor, but now I have been released from the project so won't work on it in future and now trying to automate linkedin.

**Comment by MikeMcC399** [comment]
@mohdbilal2000 

Good luck with your future project!

I suggest to close this issue now since it cannot be solved by Cypress and you have said that it is not relevant to you anymore.
