### ISSUE TITLE
Basic auth in baseUrl not working since v13

### ISSUE THREAD

**Issue by manuelriveragax** [cypress-io/cypress#27789]
### Current behavior

Passing Basic Auth in baseUrl inside of `cypress.config.ts` 
`baseUrl: 'https://username:password@google.com'`  does not load specs or other menus in the runner.

`baseUrl: 'https://google.com'` Cypress correctly loads the specs when opened

### Desired behavior

Passing Basic Auth in baseUrl inside of `cypress.config.ts` before v13 correctly loads and runs specs.

### Test code to reproduce

Any random test using the mentioned base URLs above, the issue happens after `npx cypress open` not in a test code itself

### Cypress Version

13.1.0

### Node version

v18.16.1

### Operating System

macOS

**Comment by nagash77** [comment]
Hi @manuelriveragax what was the last version this was working?  Can you share the test you are seeing this problem please?  I know you said it happens in any test but I would like to verify there isn't more going on.  It would be great if you create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by nagash77** [comment]
Hi @manuelriveragax just did a little bit of digging and it appears this problem is getting fixed with this PR https://github.com/cypress-io/cypress/pull/27781.  That will be going out in the next release.

**Comment by manuelriveragax** [comment]
> @nagash77 

Ok thanks a lot!, unfortunately, I can't share any test code due to company policies, but after reading the comments on that PR it seems that I don't need to provide any more insight

**Comment by nagash77** [comment]
Hi @manuelriveragax 13.2.0 was released yesterday.  Give it a try and report back if that addresses your problem.  🤞 it does!

**Comment by manuelriveragax** [comment]
> Hi @manuelriveragax 13.2.0 was released yesterday. Give it a try and report back if that addresses your problem. 🤞 it does!

Thank you @nagash77 it is now working correctly 👍

**Comment by manuelriveragax** [comment]
Fixed with: https://github.com/cypress-io/cypress/pull/27781
