### ISSUE TITLE
Test names are not shown on specs tab once test runs

### ISSUE THREAD

**Issue by rnb-web-dev** [cypress-io/cypress#2779]
### Current behavior:

When we are running our test suite from Jenkins in parallel mode, the test names disappear as soon as the test completes when you are on the specs tab.  You can still see the names on the failures tab.

![image](https://user-images.githubusercontent.com/43965482/48496767-622fb700-e7f8-11e8-9ef0-863197bc57b0.png)

### Desired behavior:

The test names are available regardless of whether the test has completed or not.

### Steps to reproduce:

I haven't had much luck finding other people talking about this but this is what we did.

1. Setup project to run in parallel on Jenkins red hat box.
2. Use a custom plugins/index.js to update the baseUrl of the test depending on parameters sent in.
3. Run build.

### Versions

v: 3.1.0, 3.1.1
os: red hat

**Comment by jennifer-shehane** [comment]
Hey @rnb-web-dev, I'm looking into this. I believe I've already narrowed down the issue.

**Comment by rnb-web-dev** [comment]
Awesome!  That was super fast!

Thank you @jennifer-shehane!

**Comment by jennifer-shehane** [comment]
@rnb-web-dev Can you check and see if your spec names are displaying correctly now?

**Comment by rnb-web-dev** [comment]
@jennifer-shehane Yep!  Thank you for the help!
