### ISSUE TITLE
cy.screenshot() makes different screenshot size on cypress open and cypress run

### ISSUE THREAD

**Issue by 4knort** [cypress-io/cypress#27799]
### Current behavior

If we use cy.screenshot, we will get different screenshots on cypress open and cypress run

### Desired behavior

on cypress run and cypress open we get same size screenshots

### Test code to reproduce

any test with cy.screenshot()

### Cypress Version

13.1.0

### Node version

18.17.0

### Operating System

windows 11

**Comment by MikeMcC399** [comment]
- There is a related discussion in https://github.com/cypress-io/cypress/issues/27260

**Comment by nagash77** [comment]
Hi @4knort as @MikeMcC399 posted this is a known issue.  I am going to close this issue as a duplicate.  Please follow that other issue for updates.
