### ISSUE TITLE
Unable to load the JS script due to CSP issue 

### ISSUE THREAD

**Issue by nand1234** [cypress-io/cypress#27809]
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/31034303/341521bc-0719-4363-a6ee-6554e9d0d8ad)

### Desired behavior

should be able to load JS script

### Test code to reproduce

var scr  = document.createElement('script'),
        head = document.head || document.getElementsByTagName('head')[0];
        head.appendChild(scr)
        scr.src = 'https://www.google.com/recaptcha/enterprise.js?render=<captchakey>&render=explicit';

### Cypress Version

13.0.0

### Node version

18.5.0

### Operating System

ubantu

### Other

same code works on cypress 12.12.0

**Comment by nagash77** [comment]
In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by nand1234** [comment]
@nagash77  I've created pull request with my test 
https://github.com/cypress-io/cypress-test-tiny/pull/85

**Comment by nand1234** [comment]
The issue is reproducible with latest cypress version too. @nagash77 


Add below script to test file

var scr = document.createElement('script'),
head = document.head || document.getElementsByTagName('head')[0];
head.appendChild(scr)
scr.src = 'https://www.google.com/recaptcha/enterprise.js?render=&render=explicit';


Run the cypress test in open mode
Check the console
You will see error
