### ISSUE TITLE
After using Cypress replay, I noticed that in the video it shows my application broken due to using an iframe

### ISSUE THREAD

**Issue by MarcosPereira1** [cypress-io/cypress#27805]
### Current behavior

I use Cypress Cloud and was very pleased with the availability of Cypress Replay; it's a feature that will truly be of great help. However, I encountered a bug that's hindering my use of this amazing feature.

Basically, when I view the video in Cypress Replay of my test run, the section of my application that uses an iframe appears broken during playback. Indeed, it seems to be an issue with the tool itself, because this disruption doesn't occur in the videos of other executions.

### Desired behavior

Cyoress cloud

### Test code to reproduce

name: Tests Chat

on:
  push:
    branches:
      - [SANITIZED-BRANCH-NAME]
  pull_request:
    branches:
      - [SANITIZED-BRANCH-NAME]

env:
  NODE_VERSION: 16

jobs:
  install-dependencies-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.[SANITIZED-SECRET] }}
          GH_TOKEN: ${{ secrets.[SANITIZED-SECRET] }}

  run-cypress-tests:
    needs: install-dependencies-tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
        with:
          command: yarn cypress run --browser chrome --record --key=[SANITIZED-KEY] --spec cypress/e2e/gui/chat-commerce --config-file [SANITIZED-PATH-TO-CONFIG-FILE] --parallel --group 'Chat'
          cache-key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

### Cypress Version

13.2.0

### Node version

16

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @MarcosPereira1 , can you link to the Test Replay you are seeing this in?

**Comment by MarcosPereira1** [comment]
Hi @nagash77 , Yes, I can, but can we leave this issue private?

**Comment by nagash77** [comment]
@MarcosPereira1 not a problem.  Feel free to send me an email.
