### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by rupesh1395kumar** [cypress-io/cypress#27817]
### Current behavior

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io/

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.
 Platform: linux-x64 (Ubuntu - 22.04)
 Cypress Version: 12.17.3

### Desired behavior

It should run without any error

### Test code to reproduce

N/a

### Cypress Version

12.17.3

### Node version

18.17.0

### Operating System

WSL with Ubuntu

**Comment by nagash77** [comment]
Hi @rupesh1395kumar we do not officially support WSL and I have seen some bugs with its usage.  I would also try upgrading to the latest version of Cypress and see if that resolves your problems.

**Comment by rupesh1395kumar** [comment]
> Hi @rupesh1395kumar we do not officially support WSL and I have seen some bugs with its usage. I would also try upgrading to the latest version of Cypress and see if that resolves your problems.

Thank You Let me know if issue is resolved

**Comment by wizzer129** [comment]
I experienced a similar issue, it was related to the fact that my VcXsrv wasn't launched so cypress didn't have GUI to launch in. Starting that up worked for me.
