### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

### ISSUE THREAD

**Issue by mekhron** [cypress-io/cypress#27823]
### Test code to reproduce

While running my suite, Cypress fails on the same test every time with the following error. This was not happening with Cypress v12. Happening in Ubuntu and Mac OS. Any solution on this? Thanks.

```
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  admin/attachments.spec.js                         (17 of 70)
  Estimated: 2 minutes, 28 seconds

<--- Last few GCs --->

[1647082:0xa4003a8000]   696678 ms: Scavenge (reduce) 2029.1 (2070.5) -> 2029.1 (2071.5) MB, 3.44 / 0.00 ms  (average mu = 0.706, current mu = 0.581) allocation failure; 
[1647082:0xa4003a8000]   698546 ms: Mark-Compact (reduce) 2030.0 (2071.5) -> 2030.0 (2072.5) MB, 1866.66 / 0.00 ms  (+ 108.0 ms in 46 steps since start of marking, biggest step 31.9 ms, walltime since start of marking 1997 ms) (average mu = 0.515, current

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io/

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 13.2.0
Error: The process '/home/ubuntu/actions-runner/_work/_tool/node/16.19.0/x64/bin/npx' failed with exit code 1
```

### Cypress Mode

cypress run

### Cypress Version

13.2.0

### Browser Version

Chrome 117

### Node version

v18.8.0

### Operating System

Ubuntu 20.04, Mac 12.6

**Comment by nagash77** [comment]
Hi @mekhron , are you seeing the same behavior when running on the version of v12 you said was working with Chrome 117?  Trying to eliminate variables.  Have you tried increasing the memory on the machine running the tests?

You may also want to try turning on [`experiementalMemoryManagement`](https://docs.cypress.io/guides/references/experiments#Configuration) and see if that helps.

**Comment by mekhron** [comment]
@nagash77 I am not getting this issue on Cypress v12 with Chrome 117.
Turning ON `experiementalMemoryManagement` didn't fix the issue.

**Comment by hooman-mirghasemi** [comment]
I am writing for someone who may face this problem:

I had this problem this morning. With the latest version of Cypress, which is now: 13.5.1
It doesn't solve with any solutions!!
BTW by restarting the GitLab Runner server (docker gitlab runner), the problem solved!
