### ISSUE TITLE
Blocked a frame with origin: XXX from accessing cross origin frame

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2784]
This is happening when the current subject is `<window>`, there is a cross origin iframe within the application under test, and there is an assertion off of a parent command like:

```js
cy.get('a').should('be.visible')
```

Why? Because apparently accessing `window[0]` now returns the cross origin `window`. I can't find where in the spec it defines this behavior, and perhaps this is a recent change to chrome? 

At any rate, this is happening because we have some naive internal checks to determine whether a value is an element, the document, or the window.

![screen shot 2018-11-14 at 7 38 28 pm](https://user-images.githubusercontent.com/1268976/48521997-ead44480-e844-11e8-93e1-81a029df4438.png)

**Comment by bahmutov** [comment]
Hmm I pretty much use electron only and also the tests on CI use electron so cannot be recent chrome change

**Comment by brian-mann** [comment]
@bahmutov 	that's true, didn't think to test in electron, smh - oh well its fixed now

**Comment by bahmutov** [comment]
Even that test that was causing problems in blog cypress.io?! If you remove “.first()”

**Comment by bahmutov** [comment]
Oh I see the PR now! Great catch

**Comment by brian-mann** [comment]
Released in [`3.1.2`](https://docs-staging.cypress.io/guides/references/changelog.html#3-1-2).

**Comment by zinglax** [comment]
Switched from chrome to electron and my error went away. Glad there was a solution to this. Thanks!
