### ISSUE TITLE
Can't build v13.0.0+ from source without ```g++``` and ```make```

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#27846]
### Current behavior

I ran ```npm i -g yarn```
I ran ```git clone https://github.com/cypress-io/cypress```
I ran ```cd cypress```
I ran ```yarn```

This works for versions v12.17.4 and below, but fails for versions v13.0.0 and up

#### Without ```g++``` installed
```
make: g++: No such file or directory
```

#### Without ```make``` installed
```
Error: not found: make
```

### Cypress Version

develop - https://github.com/cypress-io/cypress/commit/2247ffd79b226a7fe00dd3252020becf2c22b110

### Node version

v18.18.0

### Package Manager

yarn

### Package Manager Version

1.22.19

### Operating system

Linux

### Operating System Version

- **Operating System:** Debian GNU/Linux 11 (bullseye)
- **Kernel:** Linux 5.15.124-20260-g158060cabb35
- **Architecture:** x86-64

### Non-documented fix

Installing ```g++``` and ```make``` packages seem to be required as of v13.0.0 in order to build Cypress from source - this was not the case with v12.17.4 and earlier versions

### Other

If the above packages are intended to be required now, the [CONTRIBUTING file](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) should be updated to state this

**Comment by MikeMcC399** [comment]
Hi @alexsch01 

When I set this up for Ubuntu 22.04 I installed:
```bash
sudo apt install make
sudo apt install build-essential
sudo apt install cmake
```

I don't know if this is exactly the same for your OS and if that will help you.

You write Node.js `v18.18.0`, however it is better to use exactly what is in [.node-version](https://github.com/cypress-io/cypress/blob/develop/.node-version) i.e. `18.15.0`. This is the same version that Electron is built with. If you use `n` then `n auto` does it for you - see [CONTRIBUTING > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements). 

```text
$ npx cypress version
Cypress package version: 13.2.0
Cypress binary version: 13.2.0
Electron version: 25.8.0
Bundled Node version:
18.15.0

```

**Comment by MikeMcC399** [comment]
I checked on Ubuntu 22.04 and using Node.js `18.18.0` instead of the required `18.15.0` does not affect the ability to build Cypress from source.

**Comment by alexsch01** [comment]
```
sudo apt install make
sudo apt install build-essential
sudo apt install cmake
```

@MikeMcC399 This should be in the [CONTRIBUTING file](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) if these packages are needed for Cypress to build

This is only an issue since v13.0.0
v12.17.4 doesn't have this behavior

**Comment by MikeMcC399** [comment]
@alexsch01 

Did that solve your issue?

I didn't feel experienced enough to make suggestions to change the [CONTRIBUTING > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) section in this regard, especially as the Cypress build is very complex and I don't really understand a lot of what it does.

**Comment by alexsch01** [comment]
Yes, it did solve the issue. But this isn't documented in the CONTRIBUTING file @jennifer-shehane 

Summary: ```make```, ```build-essential```. and ```cmake``` packages seem to be required as of v13.0.0 in order to build Cypress from source - this was not the case with v12.17.4 and earlier versions

**Comment by jennifer-shehane** [comment]
@alexsch01 We're open to a PR to update the contributing guide to reflect this.

**Comment by Crustum7** [comment]
I can update the contributing guide if nobody else is working on this

**Comment by MikeMcC399** [comment]
@Crustum7

> I can update the contributing guide if nobody else is working on this

I was going to make an attempt, but I'd be happy if you want to do it.

My suggestion would be to add the following to the bottom of the list below `python`:

- [CMake](https://cmake.org/) (for Unix `sudo apt install cmake`)

as it is not covered by the `node-gyp` requirements. The list is supposed to be generic and not for a specific operating system, however I think the hint about installing `cmake` would be OK. On Ubuntu it is also available as a `snap` package.

[CONTRIBUTING > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements)

- [`Node.js`](https://nodejs.org/en/) (See the root [.node-version](.node-version) file for the required version. You can find a list of tools on [node-version-usage](https://github.com/shadowspawn/node-version-usage) to switch the version of [`Node.js`](https://nodejs.org/en/) based on [.node-version](.node-version).)
- [`yarn`](https://yarnpkg.com/en/docs/install)
- [`python`](https://www.python.org/downloads/) (since we use `node-gyp`. See their [repo](https://github.com/nodejs/node-gyp) for Python version requirements.)

**Comment by Crustum7** [comment]
Thank you @MikeMcC399! That sounds accurate and concise

**Comment by MikeMcC399** [comment]
As far as I can see whilst cross-checking on Ubuntu `22.04`, the requirements for modules supporting the use of `node-gyp` in the build process (`yarn install`) did not change between Cypress `v12.17.4` and `v13.0.0`. The main problem seems to be that the documentation is not so helpful and could be improved.

`make` was already recommended through
[README > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) > [node-gyp > On Unix](https://github.com/nodejs/node-gyp#on-unix)

`gcc` and `make` alone are not enough and there is no explicit information in the documentation that you also need `g++` and `cmake`. This is also true for  Cypress `v12.17.4`.

- The revised PR https://github.com/cypress-io/cypress/pull/27878 should fix this, which now suggests:
    - Note for Debian-based systems: `python` is pre-installed.<br>`sudo apt install g++ make cmake` meets the additional requirements to run `node-gyp` in the context of building Cypress from source.

## Repro

To demonstrate:

```bash
sudo apt remove g++ cmake
sudo apt install gcc make
sudo apt autoremove

git clone https://github.com/cypress-io/cypress
cd cypress

git checkout v12.17.4
n auto # or similar to set node to 16.16.0
yarn # error messages note that g++ and cmake are missing

git checkout v13.0.0
n auto # or similar to set node to 16.16.0
yarn # error messages note that g++ and cmake are missing
```

Now run again after executing
```bash
sudo apt install g++ cmake
```

**Comment by alexsch01** [comment]
@MikeMcC399 On Debian, installing `cmake` will also install `make` since `make` is a recommended package - NOT a dependency 

On other operating systems like Mac I don't know how that works

**Comment by MikeMcC399** [comment]
@alexsch01 

> On Debian, installing `cmake` will also install `make `since make is a recommended package

Thank you for that hint. I will suggest a change to the PR in that case.

**Comment by alexsch01** [comment]
@MikeMcC399 I meant that the install command should have g++, make, and cmake for the good path

**Comment by MikeMcC399** [comment]
@alexsch01 

Well I checked:

```bash
sudo apt remove g++ gcc cmake make
sudo apt install g++ cmake
```

and that was OK for `yarn install`

If you know some reason why:

```bash
sudo apt install g++ cmake
```

is not enough then please let us know.

**Comment by alexsch01** [comment]
Just being more explicit since make is not technically a dependency of cmake

**Comment by MikeMcC399** [comment]
I've reverted the suggestion to remove `make` from the command. If you think the PR is now OK, then you could approve it.

**Comment by alexsch01** [comment]
@MikeMcC399 just did, thanks for the reminder

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> We're open to a PR to update the contributing guide to reflect this.

- The community has prepared https://github.com/cypress-io/cypress/pull/27878 for review and merge to resolve the documentation issue in the [CONTRIBUTING > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) section.

It is suggested to add the following line to the document:
  - Note for Debian-based systems: `python` is pre-installed.<br>`sudo apt install g++ make cmake` meets the additional requirements to run `node-gyp` in the context of building Cypress from source

**Comment by MikeMcC399** [comment]
- Due to PR https://github.com/cypress-io/cypress/pull/28726 `cmake` is no longer required on Ubuntu in order to build Cypress.
