### ISSUE TITLE
Cypress env vars not persisting values outside 'then' block

### ISSUE THREAD

**Issue by rsde21** [cypress-io/cypress#27856]
### Current behavior

I have my `cypress.env.json` file at the root directory. And the initial value of this env var is blank. let's say the name of the env var is TOKEN

````js
  cy.log('pre');
  cy.log(Cypress.env('TOKEN'));            // "" logged

  cy.request({
    method: 'GET',
    url: `/xsrf-token`,
  })
    .its('body')
    .then((data) => {
      Cypress.env('TOKEN', data.token);
      cy.log('mid');
      cy.log(Cypress.env('TOKEN'));     // the correct token value is logged
    });
  cy.log('post');
  cy.log(Cypress.env('TOKEN'));   // "" logged

````

### Desired behavior

I was expecting the cypress env value to persist even outside of the "then" block. 

### Test code to reproduce

1. Run any cy.request function
2. In the `then` block, set the value of an env var
3. log the env var after the cy.request

### Cypress Version

13.2.0

### Node version

18

### Operating System

MacOS

**Comment by Crustum7** [comment]
Hello! I would recommend using `before` if you want to set the environment variable before running your tests in your spec file like so
```js
before(() => {
   cy.request({
	   method: 'GET',
	   url: `/xsrf-token`,
	 })
   .its('body')
   .then((data) => {
     Cypress.env('TOKEN', data.token);
     cy.log('mid');
     cy.log(Cypress.env('TOKEN'));     // the correct token value is logged
   });
 })

 it('test', function () {
   cy.log(Cypress.env('TOKEN'))
 })
```
Do you have a special use case where this does not work? Please let me know
