### ISSUE TITLE
We detected that the Chromium Renderer process just crashed

### ISSUE THREAD

**Issue by dragu95** [cypress-io/cypress#27852]
### Current behavior

We detected that the Chromium Renderer process just crashed.

 This is the equivalent to seeing the 'sad face' when Chrome dies.

 This can happen for a number of different reasons:
 - You wrote an endless loop and you must fix your own code
 - You are running Docker (there is an easy fix for this: see link below)
 - You are running lots of tests on a memory intense application.
 - Try enabling experimentalMemoryManagement in your config file.
 - Try lowering numTestsKeptInMemory in your config file.
 - You are running in a memory starved VM environment.
 - Try enabling experimentalMemoryManagement in your config file.
 - Try lowering numTestsKeptInMemory in your config file.
 - There are problems with your GPU / GPU drivers
 - There are browser bugs in Chromium
You can learn more including how to fix Docker here:
https://on.cypress.io/renderer-process-crashed

### Desired behavior

I click on the link and there is no "easy fix for this: see link below)" while running cypress in docker like stated in 
You are running Docker (there is an easy fix for this: see link below).

### Test code to reproduce

No Code needed.

### Cypress Version

12.4.0

### Node version

14.18.51

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @dragu95 I am not sure what you are asking for in this ticket.  Can you please clarify?

**Comment by dragu95** [comment]
Hi @nagash77 ,

I am asking for the solution in the link regarding this point;
You are running Docker (there is an easy fix for this: see link below)

I can not find the easy fix in the given link. https://on.cypress.io/renderer-process-crashed

Can you please tell me what the easy fix is?

**Comment by valeraine** [comment]
@nagash77 Same for our team, even the smallest tests we have became completely useless recently, they crash all of the time with Chromium. We're tried granulating the tests, setting up the experimentalmemorymanagement to true. By switching to electron they are running better now but still tons of them are failing. With latest Chromium updates in became detrimentally worse. 

Is your team doing some proper investigation into this? We are considering switching to a different framework because of these issue.

**Comment by MikeMcC399** [comment]
@dragu95 

You are right that the text of the error message

> You are running Docker (there is an easy fix for this: see link below)

does not match the contents of the website section, which does not mention anything about Docker.

https://on.cypress.io/renderer-process-crashed

![image](https://github.com/cypress-io/cypress/assets/66998419/bba8bb84-c566-4599-89ba-28f664135fa8)

---

Are you using a Docker image?

If yes, which Docker image are you using?

Is it an image from https://github.com/cypress-io/cypress-docker-images?

You posted that you are using Node.js `14.18.51`.  That version does not exist.
The complete list of available versions can be found at https://nodejs.org/dist/index.json.
In any case Node.js `14` has reached end-of-life and you should be using either of Node.js `18` or `20`.

Which browser and which browser version were you using when the crash occurred? 

Also you wrote that you are using Cypress `12.4.0`. This is not the latest version of Cypress. If possible you should try using Cypress `13.2.0`.

**Comment by MikeMcC399** [comment]
@valeraine

> Same for our team, even the smallest tests we have became completely useless recently, they crash all of the time with Chromium

I would recommend opening a separate issue so that you can describe your environment, especially the versions of software components you are using. If you can provide a reproducible example for investigation that would also help a lot.

**Comment by dragu95** [comment]
Hello @MikeMcC399 , can you please let me know what the "easy fix for this" in docker is if it is printed when the error occurs?

**Comment by MikeMcC399** [comment]
@dragu95 

> can you please let me know what the "easy fix for this" in docker is if it is printed when the error occurs?

- The error message is incorrect and needs to be changed. This error message was added as part of a very large feature PR https://github.com/cypress-io/cypress/pull/25488, so it is not obvious what was intended with this text. I do not know what is meant by an "easy fix" in this context.

If you can answer the questions I posted previously we can try to help you further:

Are you using a Docker image?

If yes, which Docker image are you using?

Is it an image from https://github.com/cypress-io/cypress-docker-images?

You posted that you are using Node.js `14.18.51`.  That version does not exist.
The complete list of available versions can be found at https://nodejs.org/dist/index.json.
In any case Node.js `14` has reached end-of-life and you should be using either of Node.js `18` or `20`.

Which browser and which browser version were you using when the crash occurred?

**Comment by dragu95** [comment]
@MikeMcC399 

thank you for your response.
I will provide more details:

we are using the following components/versions:
Cypress:        12.4.0     
Browser:        Chrome 113 (headless)                                                                      
Node Version:   v18.16.0 
image: node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1       

Environment:
Windows System which runs docker in WSL (Ubuntu Ubuntu 22.04.2 LTS)

If you need more information please let me know.

Edit: I also tried the solutions we can find in google, starting the chromium browser with following args:
args.push('--disable-webgl');
args.push('--no-sandbox');
args.push('--disable-gpu');
args.push('--disable-dev-shm-usage');

I also tried the experimentalMemoryManagement = true and setting numTestsKeptInMemory to 0.
Our WSL got 16 CPU and 50 GB RAM.

Some runs are successful while others are failing with the chromium renderer error completely random.
Small test suites with only 1-10 feature files never have the chromium renderer crash error.

**Comment by MikeMcC399** [comment]
@dragu95 

Many thanks for your extra details!

Unfortunately according to https://github.com/cypress-io/cypress/issues/27858#issuecomment-1729598898 from @nagash77 "WSL/2 is not officially supported by Cypress at this time. Please try using one of our supported OSes and see if that resolves your issues."

It sounds like you might be using `cypress-cucumber-preprocessor`. If that is the case, then you might try migrating to   `@badeball/cypress-cucumber-preprocessor` instead. That however is just a guess from my side.

**Comment by dragu95** [comment]
Thank you @MikeMcC399 , I will try to run it under Windows without WSL. 
I will give feedback if I changed the environment.

**Comment by dragu95** [comment]
@MikeMcC399 I have made several testruns with a big testsuite and I was not able to see the chromium renderer crash when not using WSL directly. I used Docker Desktop for the tests.
