### ISSUE TITLE
CSS not rendering properly in Cloud Test Replay when running in CI

### ISSUE THREAD

**Issue by vicwomg** [cypress-io/cypress#27861]
### Current behavior

Our CSS is not rendering properly in the test replays from tests that were kicked off in CI (GitHub Actions using the official Cypress Docker image `cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1`). 

Example:
<img width="545" alt="Screenshot 2023-09-20 at 11 38 13 AM" src="https://github.com/cypress-io/cypress/assets/4107190/6fce7b28-7c1c-47bf-917d-d4757d5f4c08">

### Desired behavior

The screen should render like this:

<img width="1116" alt="Screenshot 2023-09-20 at 11 40 38 AM" src="https://github.com/cypress-io/cypress/assets/4107190/54555781-57c8-4274-98a1-713b4ea90642">

### Test code to reproduce

Example cloud run:

https://cloud.cypress.io/projects/y1f866/runs/b1b2c7fe-64c7-40c4-ab8b-ba561c6c7639/test-results/1f0b780a-571b-4854-9354-eaceddcc432b/replay?att=1

### Cypress Version

13.2.0

### Node version

v16.14.2

### Operating System

Linux

### Other

- Next.js 12
- We use intercepts on all calls to inject Google authorization headers.
- If I run locally on macOS 13.1 and send the results to the Cypress cloud, they seem render fine, though there are a couple of missing images. https://cloud.cypress.io/projects/y1f866/runs/1600/test-results/e74adf8e-d477-4b01-b9c7-b94f4a92e223/replay
- No errors were observed on the replay console that would indicate assets are missing
- Using docker image `cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1`
- Using `cypress-io/github-action@v6.4.0`

**Comment by liambutler** [comment]
Seeing similar on my project, running Next 13.4.2

<img width="1653" alt="Screenshot 2023-09-21 at 11 55 07" src="https://github.com/cypress-io/cypress/assets/24389501/b661de7d-3f93-448c-b6aa-5ddad917d126">

Couple more things to note:

- I was able to replicate the issue on my M1 Mac, running macOS 13.5.2
- The issue appears from Cypress 13.0 onwards, and does not appear for the version that was released during the Test Replay beta (13.0.0/linux-x64/release/13.0.0-5d1e07a7aa228745b5e742aa3e912fcbd4cb217f/cypress.tgz)

**Comment by nagash77** [comment]
HI @vicwomg thank you for submitting this issue.  I have forwarded it along to our Cloud team for investigation.

**Comment by valeraine** [comment]
Same on our side, some elements of the application are comletely invisible

**Comment by paulfalgout** [comment]
To add some potential context here.. locally when we build our css ends up in `link` tags like: `<link rel="stylesheet" type="text/css" href="/20230912-app-frame-a772fb96d49a4df6a5ba.css">` but in the cypress replay those are replaced with `style` tags where the value of those tags is the file.. you can see those at the bottom of the screen... but the styles never load

<img width="1158" alt="Screenshot 2023-09-20 at 3 54 48 AM" src="https://github.com/cypress-io/cypress/assets/2028470/d4ee8bf0-5e79-4628-95de-c9b58da3bce2">

**Comment by vicwomg** [comment]
Did something change today? My latest cloud run rendered much better (one missing logo image, but css looks good), even though we haven't updated any cypress code.

**Comment by hugues-m** [comment]
Same problem, using next 13.4 and 13.5
External Css file loaded using @import in an application css file is downloaded (I can see the request), but styles are not applied

**Comment by liambutler** [comment]
> Did something change today? My latest cloud run rendered much better (one missing logo image, but css looks good), even though we haven't updated any cypress code.

Echoing @vicwomg. Our output looks as it should

**Comment by geryit** [comment]
We have the issues still:

![Screenshot by Dropbox Capture](https://github.com/cypress-io/cypress/assets/514149/2b5b5bfc-460a-4085-967c-2b219ddcb7fb)

![Screenshot by Dropbox Capture](https://github.com/cypress-io/cypress/assets/514149/91152465-46a2-4b4b-8477-b6c201cd7e8a)

https://carbonhealth.com/es

**Comment by paulfalgout** [comment]
I'm not sure if this is v13.3 or simply a cloud update, but I got a notification that this is resolved and when I ran a new test it does look like it works now.

**Comment by jennifer-shehane** [comment]
@vicwomg Is this issue still occuring for you? We've fixed several CSS issues with Test Replay. There are A LOT of different ways to include CSS into an application though, so it's possible fixing those ways didn't address your issue. 

If you update and rerun and check the Test Replay and it's still not rendering properly, link to the Test Replay link in the Cloud so we can track down the issue.

**Comment by vicwomg** [comment]
@jennifer-shehane  Most of my issues were resolved per [this comment](https://github.com/cypress-io/cypress/issues/27861#issuecomment-1732137798). But I am still seeing some issues where some images are not being rendered (broken link) example is the logo image here:  https://cloud.cypress.io/projects/y1f866/runs/1656/test-results/9c0a547c-a97a-414d-91bd-af6a78d5e5be/replay?att=1

**Comment by jennifer-shehane** [comment]
We've fixed several CSS rendering issues since this was opened and will close this issue for tracking. 

If you're still experiencing any issues with CSS rendering in a Test Replay, please use the button within the top right of the Test Replay screen to 'Report an issue' as this will report the issue directly to the correct team.
