### ISSUE TITLE
Cypress type() not input the value on the element

### ISSUE THREAD

**Issue by lthfndra** [cypress-io/cypress#27870]
The test is PASSED but it's not typed in the element

### Desired behavior

Cypress should typed the value on the input field.

### Test code to reproduce

```

**Comment by nagash77** [comment]
Hi @lthfndra this is a very common use case and we are not seeing reports of anyone else encountering this problem.  In order for us to be able to debug this we will need a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
