### ISSUE TITLE
Customization of React `cy.mount` is ignored by `rerender` function

### ISSUE THREAD

**Issue by Falcowoski** [cypress-io/cypress#27884]
### Current behavior

Assuming I have customized the **React** `cy.mount` command to load **Styled Components** global styles via the `GlobalStyle` component, I expect the following to happen:

- The component mounted by `cy.mount` is loaded with the styles from **Styled Components** :white_check_mark:
- The component re rendered by `rerender` is loaded with the styles from **Styled Components** :x: 

#### Component style by `mount`

![image](https://github.com/cypress-io/cypress/assets/85199880/100bbaea-6652-489b-bdfa-c4666d74fb4e)

#### Same component style by `rerender`

![image](https://github.com/cypress-io/cypress/assets/85199880/50dc383e-6046-4201-987e-53e91e59c9cb)

### Desired behavior

Replicate customization from `cy.mount` to `rerender`, so the **Styled Components** styles are loading during the rerender and the component is rendered with the same UI as when it was mounted.

#### Component style by `mount`

![image](https://github.com/cypress-io/cypress/assets/85199880/100bbaea-6652-489b-bdfa-c4666d74fb4e)

#### Same component style by `rerender`

![image](https://github.com/cypress-io/cypress/assets/85199880/100bbaea-6652-489b-bdfa-c4666d74fb4e)

### Test code to reproduce

```tsx
// support/component.tsx

import { styled, createGlobalStyle } from 'styled-components';

const GlobalStyle = createGlobalStyle`
  :root {
    --primary-color: red;
  }
`

Cypress.Commands.add('mount', (component, options = {}) => {
  const wrapped = (
      <Fragment>
          <GlobalStyle />
          {component}
      </Fragment>
  );
  
  return mount(wrapped, options);
})

const Button = styled.button`
  background-color: var(--primary-color);
`;

cy.mount(<Button  />).then(({ rerender }) => {
    // Button background is red!
    cy.get('button').click();

    rerender(<Button />).then(() => {
        // Button background is not red :cry: 
        cy.get('button').should('have.css', 'background-color');
    });
});

```

### Cypress Version

12.12

### Node version

16.20.1

### Operating System

Linux Mint 20.2 Cinnamon

### Other

The example code has been simplified to make it easier to understand.

**Comment by stephenarra** [comment]
fwiw, something along these lines worked for me:
```js
const RenderWithProviders = () => (
    <Fragment>
        <GlobalStyle />
        {children}
    </Fragment>
);

Cypress.Commands.add('mount', (component, options = {}) => {
  return mount(<RenderWithProviders>{component}</RenderWithProviders>, options)
    .then(({ rerender, ...props }) => ({
      ...props,
      rerender: (component: React.ReactNode) => rerender(<RenderWithProviders>{component}</RenderWithProviders>)
    }));
});
```
