### ISSUE TITLE
test

### ISSUE THREAD

**Issue by hello202222** [cypress-io/cypress#27889]

**Comment by ankurjindal2022** [comment]
I saw this issue was raised many times but never addressed . it may be something related to service workers and cypress interaction but not sure

**Comment by MikeMcC399** [comment]
@ankurjindal2022 

The website https://jimmybrings.com.au/ has implemented security restrictions which affect access and JavaScript execution. Are you employed by this company and do you have their permission to be testing this website?

If you are not part of the `jimmybrings.com.au` organization then the following may apply to you:

https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test#Step-1-Visit-a-page which offers the website https://example.cypress.io for training purposes.

It explains also about "Testing Apps You Don't Control" and mentions:

- They may detect you are a script and block your access.
- They may have security features enabled which prevent Cypress from working.

There is also a section https://docs.cypress.io/guides/references/best-practices#Visiting-External-Sites regarding "Anti-Pattern: Trying to visit or interact with sites or servers you do not control."

**Comment by ankurjindal2022** [comment]
not relevant
