### ISSUE TITLE
Cypress overlay closes upon redirection to a SSO Server

### ISSUE THREAD

**Issue by lucas2350d** [cypress-io/cypress#27894]
### Current behavior

After pressing the login button on my Page, I am redirected to the SSO login page , which closes the Cypress overlay. I haven't found a way to be directed to the login screen without closing Cypress.

In the following Video you can see how the login button is pressed followed by the redirection, and then the Cypress UI closes.
https://github.com/cypress-io/cypress/assets/69628182/a4d819e9-b2a8-4446-81d3-6f83cbfd66b0

### Test code to reproduce

cy.get('#loginButton').click()

### Cypress Version

13.2.0

### Node version

v16.18.1

### Operating System

Windows 10, Docker

**Comment by nagash77** [comment]
Hi @lucas2350d issues int he repo are reserved for bugs and feature requests.  For help using Cypress check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

I am going to close this issue at this point.  If you feel this is a bug please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.
