### ISSUE TITLE
windows CI service

### ISSUE THREAD

**Issue by benmonro** [cypress-io/cypress#2790]
In the current documentation, all of the CI examples are using linux CI agents. We are trying to run cypress on an Azure DevOps (VSTS) build which is running on windows and using apt-get is not an option.  Was hoping you could add an example to the list of CI examples which shows how to set this up for windows build services.

**Comment by jennifer-shehane** [comment]
There is a VSTS setup for CI in our documentation here: https://on.cypress.io/continuous-integration#What-is-supported

**Comment by benmonro** [comment]
@jennifer-shehane yes but the VSTS example is using hosted linux: https://github.com/bahmutov/cypress-example-kitchensink/blob/master/vsts-ci.yml#L5

I need to run this on a windows build agent and the documents and examples all are using apt-get like this: https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies

Wondering if you can add instructions/examples for doing this on a windows CI agent.

Thx
Ben

**Comment by bahmutov** [comment]
@benmonro I have tested Windows Container on Azure - just comment out the Linux `apt-get` and go. Of course, then there are other problems: #2481 and #2812
