### ISSUE TITLE
Able to cancel any one of the spec during the execution via cypress cloud 

### ISSUE THREAD

**Issue by KakaniSantosh** [cypress-io/cypress#27928]
### What would you like?

It would be great if a feature allowed the user to cancel the execution of even one spec in the total list of specs 

As we can see most of the time some specs will never stop at that time we want to release the resource that is occupying in a vm during parallelization so an option like canceling the execution of a single spec will help us 

These kinds of things the Paid Users will expect rather than normal and very few options 

### Why is this needed?

To help paid users manage other resources and save resources from unnecesary usage

### Other

Useful and also attracts when huge big and complex projects are in place

**Comment by jennifer-shehane** [comment]
@KakaniSantosh I've forwarded this request to our Cloud team for consideration. Thanks for sharing your ideas!

**Comment by KakaniSantosh** [comment]
Any update on this?

**Comment by jennifer-shehane** [comment]
@KakaniSantosh We'll update the issue when an update is available. This is not something that could ever be built in a week and I'm not sure this is something the Cloud team will decide to prioritize.
