### ISSUE TITLE
Getting error while running cypress on Jenkins - some dependencies missing

### ISSUE THREAD

**Issue by euZebe** [cypress-io/cypress#2792]
### Current behavior:
I am trying to launch my cypress tests from Jenkins, using docker image cypress/base:8. Here are a few lines of my log and the error I get on `cypress run` instruction:
```
> Running shell script
+ docker inspect -f . cypress/base:8
[...] // checkout code, install node modules 
> start-server-and-test start:dev http://localhost:4000 cypress:run
[...] // application is starting
> cypress run
It looks like this is your first time using Cypress: 3.1.1
[?25l[15:25:16]  Verifying Cypress can run /home/node/.cache/Cypress/3.1.1/Cypress [started]
[15:25:16]  Verifying Cypress can run /home/node/.cache/Cypress/3.1.1/Cypress [failed]
[?25hCypress failed to start.
This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
Command failed: /home/node/.cache/Cypress/3.1.1/Cypress/Cypress --smoke-test --ping=836
----------
Platform: linux (Debian - 8.11)
Cypress Version: 3.1.1
```
What is that --smoke-test option ? 
Anyone, any idea why it could fail ?

**Comment by dario-colombo** [comment]
you need to npm install cypress before start:dev,
 the dockerimage cypress/base:8  does not have cypres installed afik,

**Comment by euZebe** [comment]
Well, I do it ; here is my jenkinsfile:
```
pipeline {
    agent none
    stages {
        stage('Checkout and Execute Tests ') {
            agent { docker { image 'cypress/base:8' } }
            steps {
                checkout(...)
                sh("npm ci")
                sh("npm run ci-e2e")
            }
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr:"5"))
        timeout(time: 1, unit: "HOURS")
    }
}
```

with package.json containing
`    "ci-e2e": "start-server-and-test start http://localhost:4000 cypress:run",`
and cypress being a devDependency

**Comment by euZebe** [comment]
The problem came from our jenkins configuration ; DISPLAY environment property was set, which created some trouble with the following line:
https://github.com/cypress-io/cypress/blob/24e9315e38d1e3d97918962cbdc0252f339e658d/cli/lib/exec/xvfb.js#L43

**Comment by darkyndy** [comment]
@euZebe you are a life saver.

I spent today about 10 hours until I found this, tried and it worked.

Now this should be documented directly in Cypress for other to know that this may be the issue.

cmd that I'm executing from jenkins is:
```
unset DISPLAY && DEBUG=cypress:* npm run test-e2e-ci
```

where `test-e2e-ci` is an npm script as: `"test-e2e-ci": "cypress run"`

**Comment by jennifer-shehane** [comment]
Existing issue for `DISPLAY` env var is here. PRs are welcome! https://github.com/cypress-io/cypress/issues/4034
