### ISSUE TITLE
`intercept` with stubbed response is hitting the origin server

### ISSUE THREAD

**Issue by jcampbell-chime** [cypress-io/cypress#27935]
### Current behavior

I've written an intercept on PUTS to a given endpoint in my application. The cypress logs say that the response is stubbed and that the request was not sent to the origin. However, I can see the network request being made, am not receiving the data I stubbed using a `StaticResponse` object, and I can see the test user being created through my server logs. Note: this is an issue when running through Chrome but not Electron.

### Desired behavior

The intercept should work as expected and consistently across all browsers.

### Test code to reproduce

Unfortunately this is a work project so can not link it because of security. Hopefully the following code snippets and screenshots will suffice.

The intercept looks as follow. It is registered in a beforeEach hook that runs before each test:
```
 cy.intercept('PUT', '**/user/**', handleEnrollmentData).as('updateUser');
```

The `handleEnrollmentData` method definition is:
```
export const handleEnrollmentData = () => {
  console.warn('REQUEST WAS INTERCEPTED. RETURNING STUBBED RESPONSE');

  return req.reply({
    statusCode: 200,
    body: {
      enrolled_at: '2021-03-05',
      login_token: 'aca981e30e5f14beef41b15168e5c2f3',
      order_id: 'fabca24914eee1e3e153403a8e404d7645e05550',
      redirect_url: '/member/getting_started/welcome',
      status: true,
     }
  })
}
```

Here are the test logs that I grabbed from the "Test Body" pane when running the specs:
- Showing the request was actually stubbed:
  - ![Screenshot 2023-09-28 at 3 24 26 PM](https://github.com/cypress-io/cypress/assets/141789333/cdb88e8d-6750-4c3e-a028-ff9ce468a0a4)
  - ![Screenshot 2023-09-28 at 3 25 11 PM](https://github.com/cypress-io/cypress/assets/141789333/2895d620-8804-4d59-a837-483f139cb861)

To contrast, here's the intercept working as expected when launching the Electron browser:
- ![Screenshot 2023-09-28 at 3 40 22 PM](https://github.com/cypress-io/cypress/assets/141789333/2a530813-76c7-47a1-b5dd-77a73d16d34f)

- Showing the network tab detailing the request and response from the server
  - ![Screenshot 2023-09-28 at 3 28 32 PM](https://github.com/cypress-io/cypress/assets/141789333/6d44fd05-85aa-4659-9776-6ed5cab34753)
  - ![Screenshot 2023-09-28 at 3 29 16 PM](https://github.com/cypress-io/cypress/assets/141789333/cffab507-5d04-4680-80d9-bfd91361fae0)

### Cypress Version

12.17.2

### Node version

16.20.2

### Operating System

macOS Venture 13.6

**Comment by ghost** [comment]
I'm having the same issue with Chrome 117 and Cypress 12.7.4.

Given the following code:
```
cy.intercept('POST', '**/api, { body: {} }).as('request');
callToRoute();
cy.wait('@request');
```

The alias is detected, but the request isn't stubbed and I get the following error:
```
The following error originated from your application code, not from Cypress.
  > Http failure response for http://localhost:8080/api: 404 Not Found
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.
```

At first I was suspecting that the error was caused by the fact that the component test dev server runs on port 8080 by default, which is the same as my API, but changing it didn't solve my issue.

The error goes away when I have a single `it` statement inside my test, but comes back as soon as I have multiple. Switching to Electron also solves my issue.
