### ISSUE TITLE
Constructors in testing suite are not the same as in the app: instanceof fails

### ISSUE THREAD

**Issue by mitar** [cypress-io/cypress#2794]
### Current behavior:

If I have a function in the app attached to `window` which calls `instanceof Date` to control the logic, and if I then do:

```js
cy.window().then((window) => {
  window.foobar(new Date());
});
```

The value provided to `foobar` fails the `instanceof` test.

### Desired behavior:

The value passes the `instanceof` test.

**Comment by chrisbreiding** [comment]
Since your tests run in a different window from your app code, a date created in from the test window will not be able to pass an `instanceof` check. You can create the date off your app's window instead to make it work.

```javascript
cy.window().then((window) => {
  window.foobar(new window.Date());
});
```

**Comment by mitar** [comment]
Sure. But this makes it very hard to reuse some code which traditionally just assumes same global context. If that helper code comes from the app itself, now app has to have everywhere `window.` prefix.

Also, this should at least be documented somewhere.
