### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by fid37is** [cypress-io/cypress#27949]
### Current behavior

Can't run npx cypress open command. I keep getting this Error: spawn UNKNOWN.

### Test code to reproduce

\cypress-tau-course>npx cypress open
An unexpected error occurred while verifying the Cypress executable.

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Error: spawn UNKNOWN

----------

Platform: win32 (10.0.22621)
Cypress Version: 6.6.0

C:\Users\agbap\cypress-tau-course>

### Cypress Version

6.6.0

### Node version

latest

### Operating System

win 11

**Comment by jennifer-shehane** [comment]
@fid37is Are you sure you’re using Cypress 6.6.0? Because this is an extremely old version. Please try updating to our latest version. We don’t patch fixes back to this version.

**Comment by MikeMcC399** [comment]
@fid37is 

- Another user reported a similar issue and mentioned that Windows Group Policy was blocking the execution of Cypress (https://github.com/cypress-io/cypress/issues/20842#issuecomment-1104948749). You might like to investigate if that applies to your machine and if you need to get Cypress whitelisted.
- You will probably get the same error message if you try to execute `npx cypress verify`
- It looks like you are using https://github.com/filiphric/cypress-tau-course. Although this uses a legacy version `"cypress": "^6.6.0"` it will normally start.
- To fill in the details, what version of Node.js is displayed when you execute `node --version`?
- Although training courses using legacy Cypress versions (`9.x` and earlier) can still teach you fundamentals. You might want to look for courses based on the current version (`13.x`) or a minimum of `10.x`.

**Comment by MikeMcC399** [comment]
@fid37is 

Were you able to make any progress based on the previous comments?

**Comment by Ekenendidi** [comment]
Couldn't find tsconfig.json. tsconfig-paths will be skipped
