### ISSUE TITLE
click should allow to configure which meta keys are pressed during the click

### ISSUE THREAD

**Issue by mitar** [cypress-io/cypress#2795]
### Current behavior:

It is not possible to configure additional meta keys to be pressed during a click. I have logic in the app which uses meta keys and I would like to test that.

### Desired behavior:

I can configure which meta keys are pressed.

**Comment by vitaliysobur** [comment]
Hi @mitar, please try the following:

```javascript
// execute a META + click on the first <li>
// {release: false} is necessary so that
// META will not be released after the type command
cy.get('body').type('{meta}', { release: false }).get('li:first').click()
```

Will it solve your issue? You can find more information on `.type()` method here: https://docs.cypress.io/api/commands/type.html

**Comment by brian-mann** [comment]
@mitar 	yes, @vitaliysobur 	is correct - I've opened an issue in our documentation repo to make sure we do a better job explaining this in the docs: https://github.com/cypress-io/cypress-documentation/issues/1151

**Comment by mitar** [comment]
Thanks!
