### ISSUE TITLE
Multiple unsupported / non-working Cypress Cloud workflow templates

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#27951]
### Current behavior

Several Cypress Cloud templates include selections which lead to the use of unsupported Node.js versions < `18`, including Node.js `12`, `14` and `16`.

| CI Provider    | Current                                      | Suggestion                                                                            |
| -------------- | -------------------------------------------- | ------------------------------------------------------------------------------------- |
| GitHub Actions | `action/checkout@v3`                         | `action/checkout@v4`                                                                  |
| GitLab CI      | `cypress/browsers:node12.14.1-chrome85-ff81` | `cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1` |
| CircleCI       | `cypress-io/cypress@3`                       | no change needed                                                                      |
| Azure          | `ubuntu-16.04`                               | `ubuntu-latest`                                                                       |
| Bitbucket      | `cypress/base:14.16.0`                       | `cypress/base:20.9.0`                                                                 |
| AWS CodeBuild  | `nodejs: latest`                             | no change needed                                                                      |

### Desired behavior

See suggestion column above.

Templates should align to documentation on
- [Continuous Integration > CI Provider Examples](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples) links.
- https://docs.cypress.io/guides/continuous-integration/gitlab-ci

### Test code to reproduce

Open https://cloud.cypress.io/
Click "New project"
Enter a project name, click "Create project"
Under section 3 "Finish CI setup", click a template selection.

### Cypress Version

N/A - The cloud templates are not Cypress version-specific

### Node version

unsupported versions suggested by Cypress Cloud templates

### Operating System

various according to CI provider

### Debug Logs

N/A

#### References

- https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Thanks for pointing this out and adding suggestions. I've forwarded this to the Cloud team.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

- [x] I couldn't see any change to the templates yet and Node.js `20.x` moved to be the active LTS version on Oct 24, 2023 (see [Node.js release schedule](https://github.com/nodejs/release#release-schedule))
- [X] I would change my suggestion to migrate the templates to use Node.js `20.x` Cypress Docker images instead of Node.js `18.x` ones.
- [x] Docker examples on https://docs.cypress.io/ should also be updated then to refer to the new LTS version as well.

Edit: updated text above

**Comment by MikeMcC399** [comment]
- See also https://github.com/cypress-io/cypress-docker-images/issues/986

**Comment by MikeMcC399** [comment]
- See also https://github.com/cypress-io/cypress-documentation/pull/5545

**Comment by MikeMcC399** [comment]
The Azure template mentioned above uses Ubuntu version `16.04`.
- Ubuntu `16.04`  support ended in April 2021
- [Azure](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) appears to no longer offer this version.
- The minimum version of Ubuntu required to run current versions of Cypress is `20.04` (see Cypress documentation 
[Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System)).

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Is your Cloud team planning to fix this soon? I would guess that first-time Cypress Cloud users would be the major user group affected by the non-working templates, so they would have a less than ideal onboarding experience if they try to use the existing templates.

When I prepared the PRs to update the [CI documentation](https://docs.cypress.io/guides/continuous-integration/introduction) it was about an hour's work. I can't do the same for the templates, since they're not housed in a public GitHub repo, but I imagine it would be about the same amount of effort. So I wonder what organizational barriers are preventing getting this fixed?

**Comment by jennifer-shehane** [comment]
@MikeMcC399 It looks like it's on the Cloud teams board for next sprint, but I don't work on that team so can't commit to that timeline.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> It looks like it's on the Cloud teams board for next sprint, but I don't work on that team so can't commit to that timeline.

I'll close the issue here, since the contents which need to be changed are not part of this repo, so it's not the right place to track it.

**Comment by MikeMcC399** [comment]
The templates have been updated.
