### ISSUE TITLE
Sudden Error Message : We've detected that you're using a 3rd party library that is not supported by Cypress: ***-cloud

### ISSUE THREAD

**Issue by david-ic3** [cypress-io/cypress#27955]
### Current behavior

We get an error and the test are stopping : 

- We've detected that you're using a 3rd party library that is not supported by Cypress: ***-cloud

Even though the library and any reference have been deleted

### Test code to reproduce

-

### Cypress Version

13.3.0

### Node version

node18.12.0-chrome107

### Operating System

ubuntu-22.04

### Debug Logs

```shell
We get the following error running Cypress on Github : 

found 0 vulnerabilities
/usr/local/bin/npx *** cache list
┌─────────┬───────────────────┐
│ version │ last used         │
├─────────┼───────────────────┤
│ 13.3.0  │ a few seconds ago │
└─────────┴───────────────────┘

DevTools listening on ws://127.0.0.1:44473/devtools/browser/0169b9ad-8b3f-4957-b726-6f8723a[38](https://github.com/ic3-software/ic3-dashboard-testing/actions/runs/6382263151/job/17320465582#step:5:39)c3a

We've detected that you're using a 3rd party library that is not supported by Cypress: ***-cloud

To continue running Cypress, please remove this library or reach out for help migrating.

[https://on.***.io/unsupported-third-party-library?c=1](https://on.%2A%2A%2A.io/unsupported-third-party-library?c=1)

Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

### Package.json

```
{
  "name": "@ic3/ic3-dashboard-testing",
  "version": "8.4.4",
  "private": true,
  "devDependencies": {
    "@4tw/cypress-drag-drop": "2.2.5",
    "@types/node": "20.6.3",
    "@types/pdf-parse": "1.1.1",
    "cypress": "13.3.0",
    "cypress-log-to-output": "1.1.2",
    "cypress-pipe": "2.0.0",
    "cypress-real-events": "1.10.3",
    "dotenv-json": "1.0.0",
    "node-fetch": "3.3.2",
    "pdf-parse": "1.1.1",
    "read-excel-file": "5.6.1",
    "typescript": "5.2.2",
    "compatibility": "1.0.1"
  },
  "scripts": {
    "cypress:open localhost": "cypress open --config baseUrl=http://localhost:3000",
    "cypress:run localhost": "cypress run --headless --config baseUrl=http://localhost:3000",
    "build All Dashboards": "node ./etc/build_all_dashboards.mjs"
  }
}
```

**Comment by jennifer-shehane** [comment]
Hi @david-ic3, can you provide this information via the link provided in the error message? That's the channel to seek help for migrating. We can assist you there.

**Comment by yahorkazharnovich** [comment]
https://github.com/cypress-io/cypress/discussions/27924
Related discussion with latest stable version 12.17.4.

**Comment by david-ic3** [comment]
@jennifer-shehane , the link is not working (it's actuall https://on.%2A%2A%2A.io/unsupported-third-party-library?c=1 what we get in the logs).

**Comment by david-ic3** [comment]
For info, it's currently solved downgrading to "cypress": "12.17.4"

**Comment by jennifer-shehane** [comment]
@david-ic3 Your CI is obfuscating the middle of the link, thinking it's sensitive info. The link is https://on.cypress.io/unsupported-third-party-library?c=1

**Comment by jennifer-shehane** [comment]
@david-ic3 Please make sure to remove the 3rd party library and all configuration files associated with the library. Let me know if this resolves the error.

**Comment by david-ic3** [comment]
@jennifer-shehane , we removed  "compatibility": "1.0.1" and searched on all files for 'cloud'. Is there a kind of memory that remembers on cypress side that we used this library ? if no I'm out of ideas (besides downgrading versions)

**Comment by jennifer-shehane** [comment]
@david-ic3 For the `cypress-cloud` library that is indicated in the error message, their configuration file is called `currents.config.js` and does not include the word 'cloud' in it actually.

**Comment by julien-sarazin** [comment]
FYI https://currents.dev/posts/v13-blocking

**Comment by david-ic3** [comment]
@julien-sarazin , it's understandable and it's fine for us.

**Comment by david-ic3** [comment]
@jennifer-shehane , deleting the file - was empty - solved the issue. Thanks a lot.

**Comment by jennifer-shehane** [comment]
Closing as resolved

**Comment by Rebaiahmed** [comment]
Hey we have this issue and we are using sorry-cypress, so cypress-cloud is important for us 
```
 "cypress": "^12.17.3",
 "cypress-cloud": "^1.9.6",
```
We are experiencing this issue after upgrading to mdc components and no way how to resolve this error

**Comment by jennifer-shehane** [comment]
@Rebaiahmed the cypress-cloud plugin by sorry-cypress can no longer be used with Cypress. You'll need to remove the plugin and its configuration to continue using Cypress.
