### ISSUE TITLE
Variables set on the window object are undefined with Chrome and Electron

### ISSUE THREAD

**Issue by edgarkanyes** [cypress-io/cypress#27952]
### Current behavior

Variables set on the `window` object return undefined when accessed from Cypress tests using Chrome and Electron browsers.

Also during Cypress testing, the variables are undefined when accessed from the testing browser console in Firefox, Chrome and Electron.

### Desired behavior

The variables set on the window object should not be undefined, both in Cypress and the testing browser console.

### Test code to reproduce

https://github.com/edgarkanyes/cypress-window-issue

### Cypress Version

13.3.0

### Node version

v18.18.0

### Operating System

MacOS Ventura 13.6

### Other

I am adding screenshots from the linked repository for context.

<img width="1440" alt="chrome" src="https://github.com/cypress-io/cypress/assets/75629102/dec96ff0-3a9f-4a0a-813f-dcd5d5fb5c59">
<img width="1440" alt="electron" src="https://github.com/cypress-io/cypress/assets/75629102/944568cf-ee3b-4f79-af05-ac0d04597391">
<img width="1440" alt="firefox" src="https://github.com/cypress-io/cypress/assets/75629102/f3d5b59f-83ee-43b1-ae1e-42e6ce497568">

**Comment by jennifer-shehane** [comment]
I keep getting issues trying to run this project. 
<img width="1139" alt="Screen Shot 2023-12-13 at 11 21 21 AM" src="https://github.com/cypress-io/cypress/assets/1271364/109d1d13-d0e9-4e3b-9249-adea6dfbb2dd">


<img width="910" alt="Screen Shot 2023-12-13 at 11 15 36 AM" src="https://github.com/cypress-io/cypress/assets/1271364/c8212d0b-4b25-4323-a232-1d9d228660a6">

**Comment by edgarkanyes** [comment]
Not exactly sure where it could be going wrong for you. I've tested it with both Node v18 and v20. Could it be an environment issue? Which Node version are you using? Also, which OS are you using?
