### ISSUE TITLE
Cypress failed to verify that your server(http://localhost: 8080) is running error for Cypress Component  testing in Jenkins CI pipeline (Uses Linux)

### ISSUE THREAD

**Issue by mdlkumaran** [cypress-io/cypress#27967]
### Current behavior

Hi Cypress team and good day!

I am new to Cypress component testing and was able to follow the official steps and able to successfully run the component tests locally using React and webpack.

![component fail-3](https://github.com/cypress-io/cypress/assets/13125981/533ed065-0564-4f4e-a421-ae6f9f45d9d3)

![component fail 4](https://github.com/cypress-io/cypress/assets/13125981/37010276-ea31-4e9f-9ac6-f56eb7db23de)

![component fail 2](https://github.com/cypress-io/cypress/assets/13125981/7120589d-57c7-45d9-93ae-57eaf351b67e)

However, running the same code in the Jenkins CI pipeline, I am facing this error as below:

18:19:52 DevTools listening on ws://127.0.0.1:39521/devtools/browser/eaff2479-7355-421-ae4f -71b25c94c30b
18:19:53 Missing baser in compilerOptions. tsconfig-paths will be skipped
18:19:56 <i> [webpack-dev-server] Project is running at:
18:19:56 <i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
18:19:56 <i> [webpack-dev-server] Content not from webpack is served from " /home/jenkins/agent/workspace/DOM-Github_feature_ECSCAEA-1652/public' directory
18:19:57 Cypress could not verify that this server is running:
18:19:57
18:19:57
**> http://localhost: 8080
18:19:57
18:19:57 We are verifying this server because it has been configured as your baseUrl.
18:19:57
18:19:57 Cypress automatically waits until your server is accessible before running tests
18:19:57
18:19:57 We will try connecting to it 3 more times.
18:20:00 We will try connecting to it 2 more times
18:20:03 We will try connecting to it 1 more time...**
18:20:03
18:20:07 Cypress failed to verify that your server is running.
18:20:07
18:20:07 Please start this server and then run Cypress again.

![component test fail](https://github.com/cypress-io/cypress/assets/13125981/7eeda15c-483d-411e-a36f-c7b65c235397)

I searched all through the internet and did not find anything that helps me specifically for component testing and all the solutions are around e2e testing like using wait-on or start-server-and-test and I don't think it is applicable to the cypress component testing as I do not see we have control on making the dev server wait in the cypress.config.js.

I also found this link similar to the error message and also a fix for it but for e2e and fixed 2 years back 

https://github.com/cypress-io/cypress/issues/8870 - Issue
https://github.com/PostHog/posthog/pull/14539 - Fix

Could someone let me know if there is already a fix/steps to handle this in the pipeline or a bug that needs to be addressed?

It would be great if I could get some help if anyone else faced this issue and found a workaround for this in the pipeline for Cypress component testing. Knowing the awesomeness of Cypress e2e testing for our project,  we started this effort to migrate from React testing library unit tests to Cypress component testing. We are stuck here at this point and do not want to stick with the React testing library unit tests again. Thanks for your help in advance.

### Desired behavior

Cypress should wait/have config to increase the timeout for the wepack-dev-server (Local server in pipeline) to launch the localhost successfully and then try to run the cypress component testing.

### Test code to reproduce

I have posted the necessary screenshots for reproducing this issue.

### Cypress Version

13.3.0

### Node version

v18.17.0

### Operating System

Ubuntu20

### Debug Logs

```shell
NA
```

### Other

NA

**Comment by BuschMartin** [comment]
Any update to this? We are facing exact problem when we try to run the component tests on our Jenkins CI

**Comment by jimmux** [comment]
This looks like the same issue as https://github.com/cypress-io/cypress/issues/28338

The workaround documented there worked in my case.

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/28338

**Comment by mdlkumaran** [comment]
I tried to downgrade cypress dependency to 13.1.0 and the issue still exists and hasn't resolved yet based on @jimmux suggestion based on [28338](https://github.com/cypress-io/cypress/issues/28338). This issue doesn't look like the exact same issue as referenced above. Can you please reopen this ticket again please @jennifer-shehane? Thanks

**Comment by jennifer-shehane** [comment]
@mdlkumaran There hasn't been independent verification that that is the version this issue was introduced in, but the majority of people say it's resolved in v12 latest version.

**Comment by mdlkumaran** [comment]
@jennifer-shehane : I did try downgrading to v12.7 for cypress and I see this is resolved as you mentioned. But looks like v12.7 has  2 critical vulnerability reported which makes me not to use that version in our current organization. Could you help with any other suggestions? Thanks

**Comment by mdlkumaran** [comment]
@jennifer-shehane : This is possibly related to https://github.com/cypress-io/cypress/issues/27990
