### ISSUE TITLE
E: Unable to locate package libgconf-2-4

### ISSUE THREAD

**Issue by ChrisJBurns** [cypress-io/cypress#27972]
### Current behavior

We are trying to create a base image for all services that will be installing Cypress via `npm`, however, what worked before now doesn't work. Specifically, the package `libgconf-2-4` cannot be installed which is a pre-req for us before we install Cypress.

Dockerfile code:
```Dockerfile
FROM internal.registry.com/ubuntu/ubuntu:23.10
RUN apt-get update \
     && apt-get -y install jq git python3 \
     # the following are system dependencies we have to install to support Cypress
     # https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites
     libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

### Debug logs

```Text
We get the following errors

#0 0.105 Get:1 http://security.ubuntu.com/ubuntu mantic-security InRelease [90.7 kB]
#13 0.255 Get:2 http://archive.ubuntu.com/ubuntu mantic InRelease [255 kB]
#13 0.775 Get:3 http://archive.ubuntu.com/ubuntu mantic-updates InRelease [90.7 kB]
#13 0.892 Get:4 http://archive.ubuntu.com/ubuntu mantic-backports InRelease [90.7 kB]
#13 1.009 Get:5 http://archive.ubuntu.com/ubuntu mantic/main amd64 Packages [1812 kB]
#13 1.325 Get:6 http://archive.ubuntu.com/ubuntu mantic/multiverse amd64 Packages [293 kB]
#13 1.335 Get:7 http://archive.ubuntu.com/ubuntu mantic/restricted amd64 Packages [208 kB]
#13 1.346 Get:8 http://archive.ubuntu.com/ubuntu mantic/universe amd64 Packages [18.8 MB]
#13 2.625 Fetched 21.7 MB in 3s (8574 kB/s)
#13 2.625 Reading package lists...
#13 3.248 Reading package lists...
#13 3.837 Building dependency tree...
#13 3.955 Reading state information...
#13 3.963 E: Unable to locate package libgconf-2-4
```

### Cypress Version

N\A

### Node version

N\A

### Package Manager

npm

### Package Manager Version

N\A

### Operating system

Linux

### Operating System Version

Ubuntu

**Comment by MikeMcC399** [comment]
@ChrisJBurns 

Does this relate to a beta build of Ubuntu `23.10`?

https://wiki.ubuntu.com/Releases marks this as a future release planned for Oct ~~10~~12, 2023.

**Comment by ChrisJBurns** [comment]
Ahhh good spot @MikeMcC399 . We use Renovate to let us know when new versions of our images are available, and it must have been a bit too quick with this one. I tell you what I'll do, because the Docker image for Ubuntu 23.10 is already available but may be doing some OS checks when pulling packages, I can wait until the 10th October and see if anything changes? 

Will comment back on this ticket!

**Comment by jennifer-shehane** [comment]
Closing since this does not appear to be related to something under Cypress's control.

**Comment by ChrisJBurns** [comment]
@jennifer-shehane  I'lll comment back on this ticket if the Ubuntu 23:10 doesn't work because I imagine it will affect the guidance on the [Cypress website](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) for Linux Ubuntu Pre req's.

**Comment by MikeMcC399** [comment]
@ChrisJBurns 

I looked into this issue and it appears that the Cypress dependency on `libconf-2-4` was removed with the release of [Cypress 3.5.0](https://docs.cypress.io/guides/references/changelog#3-5-0) on Oct 23, 2019. This release updated electron from `2.0.18` to `5.0.10`.

Although the Ubuntu `23.10` version is still in beta and has not been formally released yet, it is already frozen.  https://answers.launchpad.net/ubuntu/mantic/arm64/libgconf2-dev/3.2.6-8ubuntu1 shows Status: Deleted and therefore  `libconf-2-4` can not be expected to ship with this latest upcoming Ubuntu release.

https://packages.ubuntu.com/search?keywords=libgconf-2-4 shows the releases where it is included and this does not include `mantic` / future `23.10`.

This is now a documentation issue for [Getting Started > Installing Cypress > System requirements > Linux Prerequisites > Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) where it gives the following instructions:

```bash
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

It looks to me very much like the package `libgconf-2-4` can simply be removed from the list of packages.

**Comment by MikeMcC399** [comment]
- I have submitted the documentation PR https://github.com/cypress-io/cypress-documentation/pull/5528 to remove the obsolete `libgconf-2-4` package from the list of prerequisites for using Cypress on Ubuntu/Debian.

**Comment by MikeMcC399** [comment]
@ChrisJBurns 

>  because the Docker image for Ubuntu 23.10 is already available but may be doing some OS checks when pulling packages, I can wait until the 10th October and see if anything changes?

On https://hub.docker.com/_/ubuntu the `mantic` image is tagged along with `devel` so that would not yet be the final release

![image](https://github.com/cypress-io/cypress/assets/66998419/727763c5-468c-4544-9c52-1627e1b16b91)

**Comment by ChrisJBurns** [comment]
Hi @MikeMcC399 

Thanks for the investigation on this! I'm just confirming with my team on if they use versions of Cypress later than `3.5.0` and then will be removing that dependency from our Docker builds. I expect they are, if they're not we will revert the Ubuntu version back to `22`.

Good thing is, the docs have been updated in relation to this issue which is great! I believe we can close this now if you're happy? On our side, we will either update Cypress so we don't need the dependency, or we will downgrade Ubuntu if we do.

**Comment by ChrisJBurns** [comment]
Our UI engineers have confirmed we are using Cypress 12.x.x, so I will remove that dependency from the Dockerfile. Thanks @MikeMcC399 ! Although I wonder if there are other dependencies in the docs that may not be needed now?

**Comment by MikeMcC399** [comment]
@ChrisJBurns 

Unless you have a specific need to be on the latest Ubuntu version it is often better for testing to settle on the LTS version, which will be Ubuntu `22.04` for a while.

According to https://ubuntu.com/about/release-cycle I would expect `24.04` to be released next year and to take over the LTS role from `22.04`.

>  Although I wonder if there are other dependencies in the docs that may not be needed now?

That is possible. I only looked at the one dependency causing an issue and I'm not the Subject Matter Expert on this. That would be a separate documentation question for the Cypress team to answer.

Edit: I took a brief look and didn't see any others which needed to be removed. Note that some of the packages may be installed already by default, depending what options are chosen when the operating system is installed.

**Comment by ChrisJBurns** [comment]
Yep, we've added a renovate rule to ignore `23` releases for further upgrades. Can confirm our Docker builds successfully also!
I don;t have privs to close this, but am happy for it to be closed!

**Comment by MikeMcC399** [comment]
@ChrisJBurns 

> Yep, we've added a renovate rule to ignore 23 releases for further upgrades. Can confirm our Docker builds successfully also!
I don;t have privs to close this, but am happy for it to be closed!

It sounds like you're now in great shape! 🎉 

Actually this issue is already closed, but not locked, so there is nothing more to do here!

- The Cypress team is now called on to review and merge the documentation change I proposed in https://github.com/cypress-io/cypress-documentation/pull/5528 if they approve it.

**Comment by MikeMcC399** [comment]
The Cypress documentation section [Getting Started > Installing Cypress > System requirements > Linux Prerequisites > Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) has been updated to remove the obsolete `libgconf-2-4` packages and it now recommends:

```shell
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

for Ubuntu/Debian

and this should be fine for all supported versions of Ubuntu from `20.04` LTS up to and including yesterday's `23.10` release.

The Ubuntu `23.10` version ("Mantic Minotaur") was [announced released](https://canonical.com/blog/canonical-releases-ubuntu-23-10-mantic-minotaur) on Oct 12, 2023.

**Comment by lbraz-c24h** [comment]
> Yep, we've added a renovate rule to ignore `23` releases for further upgrades. Can confirm our Docker builds successfully also! I don;t have privs to close this, but am happy for it to be closed!

How did you remove it with dockerfile?
