### ISSUE TITLE
After the update to version 13, the component tests do not work.

### ISSUE THREAD

**Issue by cosimogaloi** [cypress-io/cypress#27975]
### Current behavior

After updating to version 13 of Cypress, some tests are giving me the following error. 

No tests found.
Cypress could not detect tests in this file.

They worked in Version 12

### Test code to reproduce

```js
import {defineConfig} from 'cypress';

export default defineConfig({
    e2e: {
        baseUrl: 'http://localhost:4200',
        supportFile: false,
        video: false
    },
    component: {
        devServer: {
            framework: 'angular',
            bundler: 'webpack'
        },
        specPattern: '**/*.cy.ts'
    }
});

```

### Cypress Version

13.2.0

### Node version

18.11.0

### Operating System

Mac OS

**Comment by jennifer-shehane** [comment]
@cosimogaloi Could you be more specific about the last working version of Cypress? We had a webpack update towards the end of 12.x versions, and I wonder if that’s impacting this. We haven’t had much in 13 that would affect this to my knowledge.

**Comment by cosimogaloi** [comment]
**This is how it works**
```
"cypress": "12.17.4",
` "dependencies": {
        "@angular/common": "^16.2.7",
        "@angular/core": "^16.2.7",
        "@angular/forms": "^16.2.7",
        "@angular/platform-browser": "^16.2.7",
        "@angular/platform-browser-dynamic": "^16.2.7",
        "@angular/router": "^16.2.7",
        "@angular/service-worker": "^16.2.7",
        "@capacitor/app": "5.0.6",
        "@capacitor/core": "5.4.2",
        "@capacitor/haptics": "5.0.6",
        "@capacitor/keyboard": "5.0.6",
        "@capacitor/status-bar": "5.0.6",
        "@ionic/angular": "7.4.3",
        "@ionic/angular-server": "7.4.3",
        "@ionic/cli": "7.1.1",
        "@ionic/storage-angular": "4.0.0",
        "rxjs": "7.8.1",
        "tslib": "^2.6.2",
        "zone.js": "~0.13.3"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "16.2.4",
        "@angular-eslint/builder": "16.2.0",
        "@angular-eslint/eslint-plugin": "16.2.0",
        "@angular-eslint/eslint-plugin-template": "16.2.0",
        "@angular-eslint/schematics": "16.2.0",
        "@angular-eslint/template-parser": "16.2.0",
        "@angular/cli": "^16.2.4",
        "@angular/compiler": "^16.2.7",
        "@angular/compiler-cli": "^16.2.7",
        "@angular/language-service": "^16.2.7",
        "@angular/localize": "16.2.7",
        "@capacitor/cli": "5.4.2",
        "@cypress/schematic": "2.5.1",
        "@ionic/angular-toolkit": "10.0.0",
        "@types/jasmine": "~4.3.5",
        "@types/jasminewd2": "~2.0.10",
        "@types/node": "20.8.2",
        "@typescript-eslint/eslint-plugin": "6.7.4",
        "@typescript-eslint/parser": "6.7.4",
        "cypress": "12.17.4",
        "eslint": "^8.48.0",
        "eslint-plugin-autofix": "1.1.0",
        "eslint-plugin-import": "2.28.1",
        "eslint-plugin-jsdoc": "46.8.2",
        "eslint-plugin-prefer-arrow": "1.2.3",
        "firebase-tools": "12.6.1",
        "http-server": "14.1.1",
        "jasmine-core": "~5.1.1",
        "jasmine-spec-reporter": "~7.0.0",
        "karma": "~6.4.2",
        "karma-chrome-launcher": "3.2.0",
        "karma-coverage": "~2.2.1",
        "karma-coverage-istanbul-reporter": "~3.0.3",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "^2.1.0",
        "leasot": "13.3.0",
        "npm-check-updates": "16.14.4",
        "prettier": "3.0.3",
        "rimraf": "5.0.5",
        "stylelint": "15.10.3",
        "stylelint-config-prettier-scss": "1.0.0",
        "stylelint-config-standard-scss": "11.0.0",
        "stylelint-order": "6.0.3",
        "stylelint-prettier": "4.0.2",
        "ts-node": "~10.9.1",
        "typescript": "~5.0.4",
        "wait-on": "7.0.1"
    },
```

**Comment by jennifer-shehane** [comment]
@cosimogaloi Are you saying that Cypress 12.17.4 works? But 13.0.0 is broken?

**Comment by cosimogaloi** [comment]
Exactly the same test, I'm just updating the Cypress to version 13. 


I also did a npm cache clean and a cypress cache clean. I can't explain it.

**Comment by niklashauschel** [comment]
I have a similar issue. In the UI it displays the warning "cannot connect base url"
![image](https://github.com/cypress-io/cypress/assets/38029973/6165e547-16fd-4178-ab63-eb321de6744e)
But here it is possible to ignore and execute the tests.

With the CLI it fails:
![image](https://github.com/cypress-io/cypress/assets/38029973/ff682f9d-f5f8-4af7-ac15-19eb84f2d15b)

Before I updated it to version 13 it was working and it was not required to define the baseUrl for component tests

dep:
    "nx": "15.7.2",
    "cypress": "^13.2.0",

**Comment by tomdglenn91** [comment]
Also getting this with Cypress 13, but also with some later versions of 12. Mac OS and Node18 too. I will try 12.17.4 to see if that lines up with @cosimogaloi

**Comment by tomdglenn91** [comment]
After checking, I still don't get my spec files found.

```
We searched for specs matching this glob pattern:

  > /Users/<user>/code/projects/<project>/apps/<app_name>/src/**/*.cy.js
```

Using the following config:
```
component: {
    devServer: {
      bundler: 'webpack',
      framework: 'react',
      webpackConfig: require('../webpack.common.js'),
    },
```

I am wondering if there are things in my webpack or tsconfig that I need to be cautious of? Does webpack need to know about the .cy files, and cypress reads them from the web server rather than the file system?

**Comment by cosimogaloi** [comment]
I found the problem with the route for the test
src/app/+auth/* doesn't work for me
if I change the route to
src/app/auth/* it works

So if I remove the "+" in the route, all the tests work

@jennifer-shehane  I understand that this is a bug or did I configure something wrong?

**Comment by jennifer-shehane** [comment]
@cosimogaloi Sounds like we're getting closer, I have a few questions to clarify:

- Could you specify where in your code this file is with the `+` character? Is this in the source code?
- Did you try 12.17.4 version to see if it works or does not work in that version? That would help narrow down the issue
- Can you provide a repo of code that recreates the issue with the `+` character?

Thanks.

**Comment by cosimogaloi** [comment]
I can't promote the code, unfortunately, but I can provide you with the path.

src/app/+auth/login/auth-login-form/auth-login-form.cy.ts
In that case, the + is in the name of a folder +auth.

In version 12.17.4, it works, and after installing any version of 13.x, it no longer works.

**Comment by ShellyDCMS** [comment]
I also experienced the same problem. updating node version fixed it. @cosimogaloi , what node version (node -v) are you using? It should be 18 or greater.

**Comment by cosimogaloi** [comment]
My version is 18.11 but thanks for the input.

**Comment by KarineBrandelli** [comment]
Same issue here!
Updated from 12.17.4 to 13.5.0 and the tests are 'not found'.

I'm using React + Webpack and Node 18.12.1.

I'm also using @badeball/cypress-cucumber-preprocessor and my `cypress.config.ts` looks like this:

```ts
import { defineConfig } from 'cypress'
import type * as Webpack from 'webpack'
import { devServer } from '@cypress/webpack-dev-server'
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor'

const webpackConfig = (
  cypressConfig: Cypress.PluginConfigOptions
): Webpack.Configuration => {
  return {
    resolve: {
      extensions: ['.tsx', '.jsx', '.ts', '.js']
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: [/node_modules/],
          use: [
            {
              loader: 'ts-loader',
              options: { transpileOnly: true }
            }
          ]
        },
        {
          test: /\.ts$/,
          exclude: [/node_modules/],
          use: [
            {
              loader: 'babel-loader'
            }
          ]
        },
        {
          test: /\.feature$/,
          use: [
            {
              loader: '@badeball/cypress-cucumber-preprocessor/webpack',
              options: cypressConfig
            }
          ]
        }
      ]
    }
  }
}

export default defineConfig({
  component: {
    specPattern: './cypress/integration/**/*.feature',
    devServer(devServerConfig) {
      return devServer({
        ...devServerConfig,
        framework: 'react',
        webpackConfig: webpackConfig(devServerConfig.cypressConfig)
      })
    },
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config)

      return config
    },
    env: {
      codeCoverage: {
        exclude: ['cypress/**/*.*']
      },
      TAGS: '@focus'
    }
  }
})
```

My tests are in my `cypress/integration` folder

![image](https://github.com/cypress-io/cypress/assets/108953489/f92725bf-06ec-46d3-8a7b-c19cb37510aa)

@jennifer-shehane any thoughts? 🥲

**Comment by rexizam** [comment]
I'm facing the same problem with Cypress v13.6.0, NX v16.9.1, Node v18 and rspack core v0.3.14

Here is my cypress config:

```
component: {
    supportFile: "cypress/support/index.ts",
    specPattern: "**/*.component-test.{ts,tsx}",
    experimentalSingleTabRunMode: false,
    defaultCommandTimeout: 10000,
    devServer: {
      framework: "react",
      bundler: "webpack",
    },
    setupNodeEvents(on, config) {
      failFast(on, config);

      config.env.GRAPHQL_SCHEMA = schema;
      return config;
    },
  },
```

rspack server configuration:

```
devServer: {
      allowedHosts: "all",
      historyApiFallback: true,
      port: PORT,
      hot: true,
      client: {
        overlay: false,
      },
    },
    mode: "development",
    devtool: "source-map",
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /(node_modules)/,
          use: {
            loader: "swc-loader",
            options: {
              jsc: {
                transform: {
                  react: {
                    runtime: "automatic",
                  },
                },
                paths: {
                  "@instrument-ui": [`${root}/apps/instrument-ui`],
                  "@packages/*": [`${root}/packages/*`],
                },
                parser: {
                  syntax: "typescript",
                  tsx: true,
                },
                baseUrl: root,
              },
            },
          },
        },
      ],
    },
    plugins: [new DotenvPlugin({ path: `${root}/apps/instrument-ui/.env`, systemvars: true }), new NodePolyfill()],
    resolve: {
      extensions: [".ts", ".tsx", ".mjs", ".js", ".jsx"],
      tsConfigPath: `${root}/tsconfig.base.json`,
      fallback: {
        path: false,
      },
    },
```

When I run the tests with webpack v5.88.2 everything works fine.

![image](https://github.com/cypress-io/cypress/assets/50618325/820cc576-b076-4659-a2ca-6c68235071c1)
![image](https://github.com/cypress-io/cypress/assets/50618325/6442d3d9-6a9f-4ccc-9b5e-dbdebde06196)

**Comment by xfsnowind** [comment]
> I'm facing the same problem with Cypress v13.6.0, NX v16.9.1, Node v18 and rspack core v0.3.14
> 
> Here is my cypress config:
> 
> ```
> component: {
>     supportFile: "cypress/support/index.ts",
>     specPattern: "**/*.component-test.{ts,tsx}",
>     experimentalSingleTabRunMode: false,
>     defaultCommandTimeout: 10000,
>     devServer: {
>       framework: "react",
>       bundler: "webpack",
>     },
>     setupNodeEvents(on, config) {
>       failFast(on, config);
> 
>       config.env.GRAPHQL_SCHEMA = schema;
>       return config;
>     },
>   },
> ```
> 
> rspack server configuration:
> 
> ```
> devServer: {
>       allowedHosts: "all",
>       historyApiFallback: true,
>       port: PORT,
>       hot: true,
>       client: {
>         overlay: false,
>       },
>     },
>     mode: "development",
>     devtool: "source-map",
>     module: {
>       rules: [
>         {
>           test: /\.tsx?$/,
>           exclude: /(node_modules)/,
>           use: {
>             loader: "swc-loader",
>             options: {
>               jsc: {
>                 transform: {
>                   react: {
>                     runtime: "automatic",
>                   },
>                 },
>                 paths: {
>                   "@instrument-ui": [`${root}/apps/instrument-ui`],
>                   "@packages/*": [`${root}/packages/*`],
>                 },
>                 parser: {
>                   syntax: "typescript",
>                   tsx: true,
>                 },
>                 baseUrl: root,
>               },
>             },
>           },
>         },
>       ],
>     },
>     plugins: [new DotenvPlugin({ path: `${root}/apps/instrument-ui/.env`, systemvars: true }), new NodePolyfill()],
>     resolve: {
>       extensions: [".ts", ".tsx", ".mjs", ".js", ".jsx"],
>       tsConfigPath: `${root}/tsconfig.base.json`,
>       fallback: {
>         path: false,
>       },
>     },
> ```
> 
> When I run the tests with webpack v5.88.2 everything works fine.
> 
> ![image](https://private-user-images.githubusercontent.com/50618325/291935788-820cc576-b076-4659-a2ca-6c68235071c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTM4MTIsIm5iZiI6MTcwMzE1MzUxMiwicGF0aCI6Ii81MDYxODMyNS8yOTE5MzU3ODgtODIwY2M1NzYtYjA3Ni00NjU5LWEyY2EtNmM2ODIzNTA3MWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEwMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNjY1Y2ExNzNlOGQ3MjY4ZTEyYTRjZGI4MGMxMTZlYmZjMDUwNGU1NmJiNmZhNmJmM2I1MGM0NjdhYzhkMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmiP8-NbSsks_d2wJfvlmgLWvrUc8pPhs7HQIZ-zd1o) ![image](https://private-user-images.githubusercontent.com/50618325/291935876-6442d3d9-6a9f-4ccc-9b5e-dbdebde06196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTM4MTIsIm5iZiI6MTcwMzE1MzUxMiwicGF0aCI6Ii81MDYxODMyNS8yOTE5MzU4NzYtNjQ0MmQzZDktNmE5Zi00Y2NjLTliNWUtZGJkZWJkZTA2MTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEwMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNzJmMGI1NzQ5YjA3MjZjZjBjNWU5ODQzYjE0OGMxYjMyZmE1YmY1MWRlOTk3MTU2MmVjYzdlNWQxNTQ1NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CEd-XjdGDxv3935qJAnbQ7NmsWF56IFmMgDtWL2YazM)

@rexizam  I had similar config with you, Cypress 13.0.0, Nx 16.0.3, Rspack 0.3.14 and cypress-rspack-dev-server 0.0.3. Everything works on Cypress 12.17.4, but got this `No tests found` after upgrading to 13.0.0

**Comment by jordanpowell88** [comment]
@cosimogaloi can you create an example repo? I'd love to take a look at this

**Comment by xfsnowind** [comment]
I found the reason of this `no tests found` here, it can be fixed by this [commit](https://github.com/cypress-io/cypress/commit/87ce14a70f5534ec80a2cdc9a5084fc36a0b3c5a) of cypress/webpack-dev-server of this [new loader](https://github.com/cypress-io/cypress/blob/d6f356f561a5ebdc42ee80632c2daf6990760c9d/npm/webpack-dev-server/src/loader.ts#L21).
For rspack, with the dev-server [cypress-rspack-dev-server](https://github.com/th3fallen/cypress-rspack-dev-server/tree/main), old and new loader are both applied: https://github.com/th3fallen/cypress-rspack-dev-server/blob/5165ecb220afc4489d5ef72ef0a4eb582fe01cc1/src/loader.ts#L27

**Comment by rexizam** [comment]
> I found the reason of this `no tests found` here, it can be fixed by this [commit](https://github.com/cypress-io/cypress/commit/87ce14a70f5534ec80a2cdc9a5084fc36a0b3c5a) of cypress/webpack-dev-server of this [new loader](https://github.com/cypress-io/cypress/blob/d6f356f561a5ebdc42ee80632c2daf6990760c9d/npm/webpack-dev-server/src/loader.ts#L21). For rspack, with the dev-server [cypress-rspack-dev-server](https://github.com/th3fallen/cypress-rspack-dev-server/tree/main), old and new loader are both applied: https://github.com/th3fallen/cypress-rspack-dev-server/blob/5165ecb220afc4489d5ef72ef0a4eb582fe01cc1/src/loader.ts#L27

Can you publish the updated version of [cypress-rspack-dev-server](https://github.com/th3fallen/cypress-rspack-dev-server/tree/main) on npm please ? 🙂

**Comment by xfsnowind** [comment]
> > I found the reason of this `no tests found` here, it can be fixed by this [commit](https://github.com/cypress-io/cypress/commit/87ce14a70f5534ec80a2cdc9a5084fc36a0b3c5a) of cypress/webpack-dev-server of this [new loader](https://github.com/cypress-io/cypress/blob/d6f356f561a5ebdc42ee80632c2daf6990760c9d/npm/webpack-dev-server/src/loader.ts#L21). For rspack, with the dev-server [cypress-rspack-dev-server](https://github.com/th3fallen/cypress-rspack-dev-server/tree/main), old and new loader are both applied: https://github.com/th3fallen/cypress-rspack-dev-server/blob/5165ecb220afc4489d5ef72ef0a4eb582fe01cc1/src/loader.ts#L27
> 
> Can you publish the updated version of [cypress-rspack-dev-server](https://github.com/th3fallen/cypress-rspack-dev-server/tree/main) on npm please ? 🙂

Yes, done
