### ISSUE TITLE
Cross Origin XHR OPTIONS not intercepted when route has no response body

### ISSUE THREAD

**Issue by ncjones** [cypress-io/cypress#2798]
### Current behavior:

Given an application that makes an XHR POST request to "https://otherdomain/resource" on page load then the following route will result in an OPTIONS request being made to the real "otherdomain":

```js
  cy.route({
    method: 'POST',
    url: `https://otherdomain/resource`,
    status: 401,
  })
```

This makes the test dependent on the availability of the remote service. The workaround is to add the response body to the route options:

```js
  cy.route({
    method: 'POST',
    url: `https://otherdomain/resource`,
    status: 401,
    response: {},
  })
```

### Desired behavior:

`HTTP OPTIONS` request to cross origin domain should be automatically intercepted even if the route does not define the response body.

### Versions

* Cypress 3.1.1
* MacOS 10.13.6
* Chrome 70.0.3538.77

**Comment by ncjones** [comment]
I just realized that this is because the route is not "stubbed". From the docs: 

```
If you do not pass a response to a route, Cypress will pass the request through without stubbing it. We can still wait for the request to resolve later.
```
This is a little counter intuitive since in my mind the request was "stubbed" because the desired response status was set.

**Comment by jennifer-shehane** [comment]
I do not think we will support partial stubbing - stubbing the status without the body defined. What would the body be? Cypress would have to guess and likely this would lead to unexpected behavior based on what we set the body to be.

**Comment by ParkerD559** [comment]
This behavior is confusing. Specifying only a response status code should not be considered a "partial stub" because a response body is [not required](https://stackoverflow.com/a/8628757/6922497) for all methods/status codes.

**Comment by jennifer-shehane** [comment]
Yeah, I suppose the question is - if a `body` is not set, but a `status` is set, are you expecting Cypress to pass through the `body` from a non-stubbed response - the server's response? Or are you expecting the `body` to be `undefined` (since it is optional).
