### ISSUE TITLE
Unexpected Screen Cropping and Scroll Bars in Screenshots Using --record Option

### ISSUE THREAD

**Issue by michalstanczyk** [cypress-io/cypress#27993]
### Current behavior

I've come across an anomalous behavior wherein screenshots taken during Cypress test runs using the `--record` option are cropping the page content and unexpectedly presenting with scroll bars. Interestingly, this issue does not manifest in test runs where the `--record` option isn't utilized.

I've attempted to rectify this by setting screenshot defaults in the `e2e.js` file as follows:

```javascript
Cypress.Screenshot.defaults({ capture: 'runner', scale: false });
Cypress.Screenshot.defaults({ scale: true });
Cypress.Screenshot.defaults({ capture: 'fullPage', scale: true });
```

However, none of these default configurations seem to affect the state of the issue.

The screenshots taken with `--record` are cropped and present with unintended scroll bars. 

Example Result with `--record`: 

![Run with --record](https://github.com/cypress-io/cypress/assets/88309614/0df13a7f-66ca-4800-a8fa-f7442671fc57)

### Desired behavior

In contrast, when running tests without the `--record` option, the screenshots captured are displaying as intended, without any cropping or unwanted scroll bars.

Example Result without `--record`: 

![Run without --record](https://github.com/cypress-io/cypress/assets/88309614/a321c4de-bf9e-4e9b-8b64-d971f44eb769)

### Test code to reproduce

Can't provide as it's only for the `--record` tests in our private repository. options related to screenshots / video:
```
  video: true,
  viewportWidth: 1900,
  viewportHeight: 1200,
```

### Cypress Version

13.3.0

### Node version

18.17.1

### Operating System

macOS and linux Debian (latest cypress/browsers image)

**Comment by jennifer-shehane** [comment]
When you `--record` and have Test Replay enabled, starting in v13 we remove the Command Log from the UI and attempt to take the screenshots, we default use `cy.screenshot({ capture: runner })`. 

Likely this is highlighting a bug with our capture: runner option, where it does not capture properly. I'll leave this bug report open. 

If you are recording to the Cloud, I would recommend referring to Test Replay for the representation of your App at the time it ran. If screenshots are still important to be captured, I would recommend passing the [`--runner-ui`](https://docs.cypress.io/guides/guides/command-line#cypress-run-runner-ui) flag when running tests. This use the behavior you're seeing when you don't record. It will however render the command log during runs and it will show up in the screenshot, which we did remove in v13 to improve performance.

**Comment by michalstanczyk** [comment]
Thank you for your response and the suggestions provided earlier. I was aware of the `--runner-ui` option, but I wanted to prevent the slowdown it brings to our test execution on the CI. 

Upon further exploration in the Cypress documentation, I found relevant information that explains the screenshot-sizing problem we're experiencing in headless mode. 

It turns out that the screenshots crop issue is associated with the default window size when running Cypress in headless mode, which is 1280x720. This margining issue can be resolved by manually setting the screen resolution.

Here is a link to the specific documentation page where this is detailed: [Set Screen Size When Running Headless](https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless)

I believe it would be quite helpful if this pertinent information were made more visible. I suggest considering the addition of this detail in references like the Changelog and the Migration guide.

**Comment by jennifer-shehane** [comment]
I'm glad you found a solution!

Yah, the screenshot/video sizing is very complex and confusing today since there's so many factors that contribute to what's visible, including the machine you're running on, the screen size that's set at, any xvfb options someone may have passed, the viewport size, device pixel ratio. It's a lot of keep in mind and maintain when you just want to see your app as it rendered. Another reason we think Test Replay offers a better debugging experience than screenshots.

I'll close this as resolved.

**Comment by michalstanczyk** [comment]
I agree that it's not the easiest part. However, I believe it's worth mentioning in the migration guide, as there will likely be more people like me who start using Test Replay and run into the same issue. This seems to be a generic problem, as running Cypress tests on Chrome in headless mode always defaults to a 1280x720 resolution. At higher viewports, screenshots will always be cropped.
