### ISSUE TITLE
Upgrade react-docgen from 6.0.0-alpha.3 to 6.0.0

### ISSUE THREAD

**Issue by dkasper-was-taken** [cypress-io/cypress#27999]
### Current behavior

In order to all facilitate the security vulnerability resolution [here](https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795)  the completion of the upgrade from 6.0.0-alpha.3 to 6.0.0 for react-docgen shoudl be completed.

Breaking changes need to be addressed in [CodegenActions.ts](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/actions/CodegenActions.ts) and [babelTransform.js](https://github.com/cypress-io/cypress/blob/develop/npm/create-cypress-tests/src/component-testing/babel/babelTransform.ts) to handle the breaking changes, and needs time allocated to address.

https://react-docgen.dev/docs/release-notes/react-docgen#600
`parse` & `resolvers` renamed
`FindAllDefinitionsResolver` renamed and now a class
`FileState` is new resolved parameter

### Desired behavior

Security upgrade react-docgen from 6.0.0-alpha.3 to 6.0.0

### Test code to reproduce

Run `yarn` following version bump.

### Cypress Version

13.3.0

### Node version

v18.15.0

### Operating System

macOS

### Debug Logs

```shell
create-cypress-tests: src/component-testing/babel/babelTransform.ts(101,59): error TS2345: Argument of type 'Node' is not assignable to parameter of type 'NodesInsertionParam<never>'.
create-cypress-tests:   Type 'AnyTypeAnnotation' is not assignable to type 'NodesInsertionParam<never>'.
create-cypress-tests: src/component-testing/babel/babelTransform.ts(104,61): error TS2345: Argument of type 'Statement | Statement[]' is not assignable to parameter of type 'NodesInsertionParam<never>'.
create-cypress-tests:   Type 'BlockStatement' is not assignable to type 'NodesInsertionParam<never>'.
error Command failed with exit code 2.
```

```
@tooling/v8-snapshot: ../../packages/data-context/src/actions/CodegenActions.ts(8,40): error TS2724: '"react-docgen"' has no exported member named 'resolver'. Did you mean 'Resolver'?
@tooling/v8-snapshot: ../../packages/data-context/src/actions/CodegenActions.ts(24,78): error TS2554: Expected 1-2 arguments, but got 4.
@tooling/v8-snapshot: error Command failed with exit code 2.
```
```


### Other

_No response_

**Comment by MikeMcC399** [comment]
@dkasper-was-taken 

- `create-cypress-tests` listed in your debug logs appears to be an unmaintained component. See #28457.

**Comment by jennifer-shehane** [comment]
Closing as resolved. I don't see this alpha version of react-docgen in our repo anymore.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/cypress/pull/28063 updated `react-docgen`  from `6.0.0-alpha.3` to `6.0.4`.
