### ISSUE TITLE
npm install cypress fails with Corrupted Download

### ISSUE THREAD

**Issue by jeanflower** [cypress-io/cypress#27997]
### Current behavior

I am unable to complete the command "npm install cypress"
on a clean node project without failure "Error: Corrupted download"
 

### Debug logs

```Text
cypressTest % npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (cypresstest) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /Users/jeanflower/outsideICloud/git/cypressTest/package.json:

{
  "name": "cypresstest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) yes
cypressTest % npm install cypress
npm ERR! code 1
npm ERR! path /Users/jeanflower/outsideICloud/git/cypressTest/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c -- node index.js --exec install
npm ERR! Installing Cypress (version: 13.3.0)
npm ERR! 
npm ERR! [STARTED] Task without title.
npm ERR! [TITLE]  Downloading Cypress      0% 0s
npm ERR! [TITLE]  Downloading Cypress      1% 20s
npm ERR! [TITLE]  Downloading Cypress      1% 30s
npm ERR! [TITLE]  Downloading Cypress      1% 40s
npm ERR! [TITLE]  Downloading Cypress      2% 25s
npm ERR! [TITLE]  Downloading Cypress      2% 33s
npm ERR! [TITLE]  Downloading Cypress      3% 25s
npm ERR! [TITLE]  Downloading Cypress      4% 21s
npm ERR! [TITLE]  Downloading Cypress      5% 18s
npm ERR! [TITLE]  Downloading Cypress      5% 20s
npm ERR! [TITLE]  Downloading Cypress      6% 18s
npm ERR! [TITLE]  Downloading Cypress      6% 20s
npm ERR! [TITLE]  Downloading Cypress      7% 18s
npm ERR! [TITLE]  Downloading Cypress      7% 20s
npm ERR! [TITLE]  Downloading Cypress      8% 18s
npm ERR! [TITLE]  Downloading Cypress      8% 19s
npm ERR! [TITLE]  Downloading Cypress      9% 18s
npm ERR! [TITLE]  Downloading Cypress      9% 19s
npm ERR! [TITLE]  Downloading Cypress      9% 20s
npm ERR! [TITLE]  Downloading Cypress      9% 21s
npm ERR! [TITLE]  Downloading Cypress      10% 20s
npm ERR! [TITLE]  Downloading Cypress      10% 21s
npm ERR! [TITLE]  Downloading Cypress      11% 19s
npm ERR! [TITLE]  Downloading Cypress      11% 20s
npm ERR! [TITLE]  Downloading Cypress      11% 21s
npm ERR! [TITLE]  Downloading Cypress      12% 20s
npm ERR! [TITLE]  Downloading Cypress      13% 19s
npm ERR! [TITLE]  Downloading Cypress      13% 20s
npm ERR! [TITLE]  Downloading Cypress      13% 21s
npm ERR! [TITLE]  Downloading Cypress      14% 20s
npm ERR! [TITLE]  Downloading Cypress      15% 19s
npm ERR! [TITLE]  Downloading Cypress      15% 20s
npm ERR! [TITLE]  Downloading Cypress      16% 19s
npm ERR! [TITLE]  Downloading Cypress      16% 20s
npm ERR! [TITLE]  Downloading Cypress      17% 19s
npm ERR! [TITLE]  Downloading Cypress      17% 20s
npm ERR! [TITLE]  Downloading Cypress      18% 19s
npm ERR! [TITLE]  Downloading Cypress      18% 20s
npm ERR! [TITLE]  Downloading Cypress      19% 19s
npm ERR! [TITLE]  Downloading Cypress      19% 20s
npm ERR! [TITLE]  Downloading Cypress      20% 19s
npm ERR! [TITLE]  Downloading Cypress      21% 18s
npm ERR! [TITLE]  Downloading Cypress      21% 19s
npm ERR! [TITLE]  Downloading Cypress      22% 18s
npm ERR! [TITLE]  Downloading Cypress      22% 19s
npm ERR! [TITLE]  Downloading Cypress      23% 18s
npm ERR! [TITLE]  Downloading Cypress      24% 18s
npm ERR! [TITLE]  Downloading Cypress      25% 17s
npm ERR! [TITLE]  Downloading Cypress      25% 18s
npm ERR! [TITLE]  Downloading Cypress      26% 17s
npm ERR! [TITLE]  Downloading Cypress      26% 18s
npm ERR! [TITLE]  Downloading Cypress      27% 17s
npm ERR! [TITLE]  Downloading Cypress      27% 18s
npm ERR! [TITLE]  Downloading Cypress      28% 17s
npm ERR! [TITLE]  Downloading Cypress      29% 17s
npm ERR! [TITLE]  Downloading Cypress      30% 16s
npm ERR! [TITLE]  Downloading Cypress      30% 17s
npm ERR! [TITLE]  Downloading Cypress      31% 16s
npm ERR! [TITLE]  Downloading Cypress      32% 16s
npm ERR! [TITLE]  Downloading Cypress      33% 16s
npm ERR! [TITLE]  Downloading Cypress      34% 15s
npm ERR! [TITLE]  Downloading Cypress      34% 16s
npm ERR! [TITLE]  Downloading Cypress      35% 15s
npm ERR! [TITLE]  Downloading Cypress      36% 15s
npm ERR! [TITLE]  Downloading Cypress      37% 15s
npm ERR! [TITLE]  Downloading Cypress      38% 14s
npm ERR! [TITLE]  Downloading Cypress      38% 15s
npm ERR! [TITLE]  Downloading Cypress      39% 14s
npm ERR! [TITLE]  Downloading Cypress      40% 14s
npm ERR! [TITLE]  Downloading Cypress      41% 14s
npm ERR! [TITLE]  Downloading Cypress      42% 14s
npm ERR! [TITLE]  Downloading Cypress      43% 14s
npm ERR! [TITLE]  Downloading Cypress      44% 13s
npm ERR! [TITLE]  Downloading Cypress      44% 14s
npm ERR! [TITLE]  Downloading Cypress      45% 13s
npm ERR! [TITLE]  Downloading Cypress      45% 14s
npm ERR! [TITLE]  Downloading Cypress      46% 13s
npm ERR! [TITLE]  Downloading Cypress      46% 14s
npm ERR! [TITLE]  Downloading Cypress      47% 14s
npm ERR! [TITLE]  Downloading Cypress      48% 13s
npm ERR! [TITLE]  Downloading Cypress      48% 14s
npm ERR! [TITLE]  Downloading Cypress      49% 13s
npm ERR! [TITLE]  Downloading Cypress      49% 14s
npm ERR! [TITLE]  Downloading Cypress      50% 13s
npm ERR! [TITLE]  Downloading Cypress      51% 13s
npm ERR! [TITLE]  Downloading Cypress      52% 13s
npm ERR! [TITLE]  Downloading Cypress      53% 12s
npm ERR! [TITLE]  Downloading Cypress      53% 13s
npm ERR! [TITLE]  Downloading Cypress      54% 12s
npm ERR! [TITLE]  Downloading Cypress      55% 12s
npm ERR! [TITLE]  Downloading Cypress      56% 12s
npm ERR! [TITLE]  Downloading Cypress      57% 12s
npm ERR! [TITLE]  Downloading Cypress      58% 12s
npm ERR! [TITLE]  Downloading Cypress      59% 12s
npm ERR! [TITLE]  Downloading Cypress      60% 12s
npm ERR! [TITLE]  Downloading Cypress      61% 11s
npm ERR! [TITLE]  Downloading Cypress      61% 12s
npm ERR! [TITLE]  Downloading Cypress      62% 11s
npm ERR! [TITLE]  Downloading Cypress      63% 11s
npm ERR! [TITLE]  Downloading Cypress      64% 11s
npm ERR! [TITLE]  Downloading Cypress      65% 10s
npm ERR! [TITLE]  Downloading Cypress      66% 10s
npm ERR! [TITLE]  Downloading Cypress      67% 10s
npm ERR! [TITLE]  Downloading Cypress      68% 9s
npm ERR! [TITLE]  Downloading Cypress      68% 10s
npm ERR! [TITLE]  Downloading Cypress      69% 9s
npm ERR! [TITLE]  Downloading Cypress      70% 9s
npm ERR! [TITLE]  Downloading Cypress      71% 9s
npm ERR! [TITLE]  Downloading Cypress      72% 8s
npm ERR! [TITLE]  Downloading Cypress      73% 8s
npm ERR! [TITLE]  Downloading Cypress      74% 8s
npm ERR! [TITLE]  Downloading Cypress      75% 7s
npm ERR! [TITLE]  Downloading Cypress      76% 7s
npm ERR! [TITLE]  Downloading Cypress      77% 7s
npm ERR! [TITLE]  Downloading Cypress      78% 6s
npm ERR! [TITLE]  Downloading Cypress      78% 7s
npm ERR! [TITLE]  Downloading Cypress      79% 6s
npm ERR! [TITLE]  Downloading Cypress      80% 6s
npm ERR! [TITLE]  Downloading Cypress      81% 6s
npm ERR! [TITLE]  Downloading Cypress      82% 5s
npm ERR! [TITLE]  Downloading Cypress      83% 5s
npm ERR! [TITLE]  Downloading Cypress      84% 5s
npm ERR! [TITLE]  Downloading Cypress      85% 4s
npm ERR! [TITLE]  Downloading Cypress      86% 4s
npm ERR! [TITLE]  Downloading Cypress      87% 4s
npm ERR! [TITLE]  Downloading Cypress      88% 3s
npm ERR! [TITLE]  Downloading Cypress      88% 4s
npm ERR! [TITLE]  Downloading Cypress      89% 3s
npm ERR! [TITLE]  Downloading Cypress      90% 3s
npm ERR! [TITLE]  Downloading Cypress      91% 3s
npm ERR! [TITLE]  Downloading Cypress      92% 2s
npm ERR! [TITLE]  Downloading Cypress      93% 2s
npm ERR! [TITLE]  Downloading Cypress      94% 2s
npm ERR! [TITLE]  Downloading Cypress      95% 1s
npm ERR! The Cypress App could not be downloaded.
npm ERR! 
npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR! 
npm ERR! Otherwise, please check network connectivity and try again:
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! URL: https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64
npm ERR! Error: Corrupted download
npm ERR! 
npm ERR! Expected downloaded file to have checksum: abdd5bcc04a982707754202ed4a1066ab4f1c5af524a27791d7d3de5ac6494f7eeae1243a957b2b2a5c5f38f25e95c779d8e2f42ce356bffd040b935fb346845
npm ERR! Computed checksum: 545e04f91535d2199e7183bd414832d310b0e5899c37c83c3b3531f475262075ff9b13147e7991eabdf6b692fa41fab14f7b920bfe5becbced942928d4297638
npm ERR! 
npm ERR! Expected downloaded file to have size: 173285369
npm ERR! Computed size: 165493021
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Platform: darwin-x64 (22.6.0)
npm ERR! Cypress Version: 13.3.0
npm ERR! [FAILED] The Cypress App could not be downloaded.
npm ERR! [FAILED] 
npm ERR! [FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
npm ERR! [FAILED] 
npm ERR! [FAILED] Otherwise, please check network connectivity and try again:
npm ERR! [FAILED] 
npm ERR! [FAILED] ----------
npm ERR! [FAILED] 
npm ERR! [FAILED] URL: https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64
npm ERR! [FAILED] Error: Corrupted download
npm ERR! [FAILED] 
npm ERR! [FAILED] Expected downloaded file to have checksum: abdd5bcc04a982707754202ed4a1066ab4f1c5af524a27791d7d3de5ac6494f7eeae1243a957b2b2a5c5f38f25e95c779d8e2f42ce356bffd040b935fb346845
npm ERR! [FAILED] Computed checksum: 545e04f91535d2199e7183bd414832d310b0e5899c37c83c3b3531f475262075ff9b13147e7991eabdf6b692fa41fab14f7b920bfe5becbced942928d4297638
npm ERR! [FAILED] 
npm ERR! [FAILED] Expected downloaded file to have size: 173285369
npm ERR! [FAILED] Computed size: 165493021
npm ERR! [FAILED] 
npm ERR! [FAILED] ----------
npm ERR! [FAILED] 
npm ERR! [FAILED] Platform: darwin-x64 (22.6.0)
npm ERR! [FAILED] Cypress Version: 13.3.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeanflower/.npm/_logs/2023-10-06T19_15_24_492Z-debug-0.log
cypressTest %
```

### Cypress Version

latest

### Node version

v16.18.1

### Package Manager

npm

### Package Manager Version

8.19.2

### Operating system

Mac

### Operating System Version

Ventura Version 13.5.1 (22G90)

### Other

I have been using cypress on another project successfully and I was working to get a clean result from "npm audit".  That led me to try to update cypress, where I first met this failure.

I have tried switching to a different network connection.

**Comment by MikeMcC399** [comment]
@jeanflower 

Sometimes these types of errors are due to network security. You can try the following, which may work or it may just give a little more information about where the problem lies:

```bash
npm install cypress@latest --save-dev --ignore-scripts
npx cypress cache clear
export DEBUG=cypress:*
npx cypress install
```

Note that Node.js `16` has reached end-of-life and you should be using Node.js `18` or `20`. I don't expect this has any influence on your installation issue however.

**Comment by jeanflower** [comment]
Thanks for helping out, Mike.
I'll take your nudge to upgrade Node, but maybe try to sort this cypress issue first.
Here's the outcome from your suggestion: still seeing checksum differences.

cypressTest % npm install cypress@latest --save-dev --ignore-scripts

added 178 packages, and audited 179 packages in 9s

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
cypressTest % npx cypress cache clear
cypressTest % export DEBUG=cypress:*
cypressTest % npx cypress install
  cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/Users/jeanflower/git/cypressTest/node_modules/.bin/cypress","install"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli parsed cli options {} +358ms
  cypress:cli installing with options {} +0ms
  cypress:cli detecting arch { osPlatform: 'darwin', osArch: 'x64' } +1ms
  cypress:cli rosetta check result: { stdout: undefined } +25ms
  cypress:cli version in package.json is 13.3.0, version to install is 13.3.0 +26ms
  cypress:cli Reading binary package.json from: /Users/jeanflower/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/package.json +0ms
  cypress:cli no binary installed under cli version +4ms
  cypress:cli checking local file /Users/jeanflower/outsideICloud/13.3.0 cwd /Users/jeanflower/git/cypressTest +4ms
  cypress:cli preparing to download and unzip version  13.3.0 to path /Users/jeanflower/Library/Caches/Cypress/13.3.0 +0ms
Installing Cypress (version: 13.3.0)


  cypress:cli needed Cypress version: 13.3.0 +0ms
  cypress:cli source url https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64 +0ms
  cypress:cli downloading cypress.zip to "/var/folders/15/pjjq6dlj57b0ymly4stcnr900000gn/T/cypress-12481.zip" +0ms
  cypress:cli Downloading package {
  url: 'https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64',
  proxy: null,
  downloadDestination: '/var/folders/15/pjjq6dlj57b0ymly4stcnr900000gn/T/cypress-12481.zip'
} +2ms
  cypress:cli expected file size 82 +475ms
  cypress:cli redirect version: 13.3.0 +0ms
  cypress:cli redirect url: https://cdn.cypress.io/desktop/13.3.0/darwin-x64/cypress.zip +0ms
  cypress:cli Downloading package {
  url: 'https://cdn.cypress.io/desktop/13.3.0/darwin-x64/cypress.zip',
  proxy: null,
  downloadDestination: '/var/folders/15/pjjq6dlj57b0ymly4stcnr900000gn/T/cypress-12481.zip'
} +0ms
  cypress:cli expected checksum abdd5bcc04a982707754202ed4a1066ab4f1c5af524a27791d7d3de5ac6494f7eeae1243a957b2b2a5c5f38f25e95c779d8e2f42ce356bffd040b935fb346845 +169ms
⠧  Downloading Cypress      95% 1s
  cypress:cli downloading finished +15s
⠹  Downloading Cypress      95% 1s
  cypress:cli raising error: checksum or file size mismatch +479ms
  cypress:cli Corrupted download
  cypress:cli 
  cypress:cli Expected downloaded file to have checksum: abdd5bcc04a982707754202ed4a1066ab4f1c5af524a27791d7d3de5ac6494f7eeae1243a957b2b2a5c5f38f25e95c779d8e2f42ce356bffd040b935fb346845
  cypress:cli Computed checksum: 4d3c57e3f74ef431015b5f3eca8c6a77a1d891c27d701b83aa2f19e3d465d2e301f4e2abf200952bb173e9258cfe3684b9086ab53031304c1e343f175342b108
  cypress:cli 
  cypress:cli Expected downloaded file to have size: 173285369
  cypress:cli Computed size: 165542184 +1ms
  cypress:cli URL: https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64
  cypress:cli     Error: Corrupted download
  cypress:cli 
  cypress:cli Expected downloaded file to have checksum: abdd5bcc04a982707754202ed4a1066ab4f1c5af524a27791d7d3de5ac6494f7eeae1243a957b2b2a5c5f38f25e95c779d8e2f42ce356bffd040b935fb346845
  cypress:cli Computed checksum: 4d3c57e3f74ef431015b5f3eca8c6a77a1d891c27d701b83aa2f19e3d465d2e301f4e2abf200952bb173e9258cfe3684b9086ab53031304c1e343f175342b108
  cypress:cli 
  cypress:cli Expected downloaded file to have size: 173285369
✖ The Cypress App could not be downloaded.
  Does your workplace require a proxy to be used to access the Internet? If s…
  Otherwise, please check network connectivity and try again:
  ----------
  URL: https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64
  Error: Corrupted download
  Expected downloaded file to have checksum: abdd5bcc04a982707754202ed4a1066a…
  Computed checksum: 4d3c57e3f74ef431015b5f3eca8c6a77a1d891c27d701b83aa2f19e3…
  Expected downloaded file to have size: 173285369
  Computed size: 165542184
  ----------
  Platform: darwin-x64 (22.6.0)
  Cypress Version: 13.3.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: abdd5bcc04a982707754202ed4a1066ab4f1c5af524a27791d7d3de5ac6494f7eeae1243a957b2b2a5c5f38f25e95c779d8e2f42ce356bffd040b935fb346845
Computed checksum: 4d3c57e3f74ef431015b5f3eca8c6a77a1d891c27d701b83aa2f19e3d465d2e301f4e2abf200952bb173e9258cfe3684b9086ab53031304c1e343f175342b108

Expected downloaded file to have size: 173285369
Computed size: 165542184

----------

Platform: darwin-x64 (22.6.0)
Cypress Version: 13.3.0

**Comment by MikeMcC399** [comment]
Hi Jean @jeanflower !

Thanks for running with DEBUG enabled! This has just confirmed your previous results with a little more detail.

Your logs show again that the file is too small, consistent with the download being interrupted at around 95% before Cypress had downloaded the complete file:

```text
cypress:cli Expected downloaded file to have size: 173285369
cypress:cli Computed size: 165542184 +1ms
```

If the file is incomplete, then the checksum will fail too and that will prevent the contents being unzipped.

I can successfully download the Cypress binary from
https://download.cypress.io/desktop/13.3.0?platform=darwin&arch=x64
using Google Chrome which delivers a valid `cypress.zip` file that I can examine and extract from with a zip utility.

I could also generate the expected checksum with

```bash
cat cypress.zip | npx hasha-cli
```

`abdd5bcc04a982707754202ed4a1066ab4f1c5af524a27791d7d3de5ac6494f7eeae1243a957b2b2a5c5f38f25e95c779d8e2f42ce356bffd040b935fb346845
`

Workflows on GitHub using `macos-13` with Cypress `13.3.0` run successfully and so far I have not seen any other related problem reports regarding download and installation issues, so the first area to suspect is your system and network environment.

You might also like to try downloading the zip file in a web browser and examining it outside of Cypress. Perhaps you also have an alternative system to try and perhaps also another alternative network?

Possible problems may come from proxy servers, network security software and VPNs. There is a small probability that the distributed Cloudflare CDN network may be at fault, however https://www.cloudflarestatus.com/ and https://www.cypressstatus.com/ both show all systems operational.

**Comment by jeanflower** [comment]
Thanks Mike.  

I have managed to get through this issue by
 - manually downloading cypress using the 'Direct Download" link from here https://docs.cypress.io/guides/getting-started/installing-cypress
 - then unzipping the downloaded file and putting cypress.app here /Users/jeanflower/Library/Caches/Cypress/13.3.0
 
I now have a clean result from npm audit and my cypress tests are running and completing.
 
I appreciate you taking a look, glad to be up and running again now.  
Jean

**Comment by MikeMcC399** [comment]
Hi again Jean @jeanflower 

It's good to hear you are up and running!

I was not able to reproduce your installation issue, however I'm not a macOS user as such and I don't have the hardware to test on. I can only run tests on GitHub `macos` runners. I did try that, using `macos-13` and `node16`, and it all worked correctly.

I would tend to close this issue now unless you think it should be double-checked in a native macOS environment.

For reference, if you run into this problem again, you can find additional instructions for supported ways to install from a successfully downloaded `cypress.zip` file on the page https://docs.cypress.io/guides/references/advanced-installation. That would avoid manually unzipping and copying files.

**Comment by mattgibson** [comment]
Same issue for me. MacOS. Not used a project for a while, so it was downloading from npm with an empty cache. Switching to a different network that does not have any sort of content security policy (home wifi --> phone tethering) fixed it. Possibly, Cypress has been blacklisted somewhere, but it would seem weird for the download to start but not finish in that case.

**Comment by MikeMcC399** [comment]
@mattgibson 

What was reported back in a similar case was that network security was getting triggered at a certain point in the download and then rejecting further packets. It has been noted elsewhere (see below) that the Cypress binary has content which triggers other security scans. That may be the reason that the download fails to complete on a corporate network with protection.

I would assume that if Cypress were blocked completely, then the download would not even start. There may be a case for allowlisting Cypress in your network if this turns out to be a regular hindrance.

- #27762 
- #27763
- #27764
- #27765
- #27766

**Comment by jennifer-shehane** [comment]
Closing as stale. If you're encountering a similar issue, please open a new issue.
