### ISSUE TITLE
Screenshot location differs for `run` vs `open`

### ISSUE THREAD

**Issue by richardmward** [cypress-io/cypress#27992]
### Current behavior

When running Cypress using `cypress open`, screenshots are stored directly in the screenshots folder, e.g. `screenshots/myscreenshot.png`. When running Cypress using `cypress run`, screenshots are stored based on the name of the spec being run, e.g. `screenshots/screenshot.cy.js/myscreenshot.png`.

### Desired behavior

The location to be the same for both `cypress open` and `cypress run`, with `cypress run`'s being the preferable outcome.

### Test code to reproduce

```js
describe('Test screenshots', () => {
    it('Should take a screenshot', () => {
        cy.visit('http://example.com/')
        cy.screenshot("myfile", {
            overwrite: true,
        })
    })
})
```

### Cypress Version

13.3.0

### Node version

v18.16.0

### Operating System

Windows 11

**Comment by Joao-VictorF** [comment]
I resolved it verifying if the test is running in open mode ("isInteractive") or not. 

```
function buildScreenshotPath(page, viewport) {
  const pathSegments = [];

  if(Cypress.config('isInteractive')) // open mode
    pathSegments.push(`${page.testName}.cy.ts`)

  // other paths you may need to add

  return pathSegments.join('/');
}```

**Comment by jennifer-shehane** [comment]
This does seem unexpected. I would say the open mode behavior is a bug. 

I verified this behavior in Cypress 13.6.0, but the same behavior is seen in Cypress 10.0

```js
describe('Test screenshots', () => {
    it('Should take a screenshot', () => {
        cy.visit('https://example.com/')
        cy.screenshot("myfile", {
            overwrite: true,
        })
    })
})
```

`cypress open`
<img width="162" alt="Screen Shot 2023-11-29 at 1 53 55 PM" src="https://github.com/cypress-io/cypress/assets/1271364/0dc61c54-290c-43d8-9db9-be6a0f1b1f5e">

`cypress run`
<img width="321" alt="Screen Shot 2023-11-29 at 1 54 36 PM" src="https://github.com/cypress-io/cypress/assets/1271364/5670982e-eb45-4bc2-bd6f-c51d6eb9ff12">
