### ISSUE TITLE
Prevent reverting the DOM on hover of commands UI while tests are running

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#28]
If multiple tests are being run and I happen to hover over the commands UI (which triggers reverting the DOM), it has the potential to affect the currently running tests (in that my current test cannot find the elements it should from the reverted DOM).

**Prevent reverting the DOM if there are currently running tests.**

*Also*: There could be a potential for affecting currently running tests with interaction in the iframe. Suggest also preventing interaction in the iframe if tests are currently running.

**Comment by brian-mann** [comment]
This is fixed in [`0.5.7`](https://github.com/cypress-io/cypress/wiki/Changelog#057-04232015).  Have not done preventing user interaction in the iframe, open a 2nd issue for that if it becomes a problem.
