### ISSUE TITLE
Expose mocha and chai instance on Cypress

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#280]
Attach the bona fide mocha and chai instances to the `Cypress` namespace as `Cypress.mocha` and `Cypress.chai`. Rename the internally-used wrappers to `Cypress._mocha` and `Cypress._chai`.

Add documentation and a recipe for extending chai (`chai.use()`, etc).

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this feature request.

**Comment by badeball** [comment]
I'd love for mocha to be exposed (eg. `require("cypress").Mocha`). My use case is custom reporters - which are just classes extending `Mocha.reporters.Base`. Without Mocha exposed, my custom reporter has to depend on Mocha itself and always ensure that the Mocha version it depends on is compatible with whatever Cypress uses.
