### ISSUE TITLE
Unable to disable Enterprise SSO after switching from Enterprise to Free plan

### ISSUE THREAD

**Issue by tkociemba** [cypress-io/cypress#28008]
### Current behavior

When accessing the list of integrations for my org I see that Enterprise SSO is enabled
![Screenshot 2023-10-09 at 09 28 16](https://github.com/cypress-io/cypress/assets/72245899/66b43a1b-0233-427d-8974-384d44b5c5f6)
However, when clicking on "Configure" button I'm briefly redirected to `integrations/sso` before coming back to `/integrations` list.

### Desired behavior

There should be a way to disable SSO integration while being in Free plan

### Test code to reproduce

No test available

### Cypress Version

not related

### Node version

not related

### Operating System

not related

**Comment by stake25** [comment]
I am unable to do the same thing, and until we get SSO issues worked out we cannot invite anyone

**Comment by jennifer-shehane** [comment]
I forwarded this to our Cloud team.
