### ISSUE TITLE
Protocol: [upload] "socket hang up" error when uploading replay test in Cypress Cloud

### ISSUE THREAD

**Issue by mhnasajpour** [cypress-io/cypress#28004]
### Current behavior

Hello, when we run the tests by Cypress and upload their results to the Cypress cloud, we get the following result.

Test Replay - Failed Uploading 8/8 - request to https://capture.cypress.io/upload/... failed, reason: **socket hang up**

When we go to that URL, we get this result 

![image](https://github.com/cypress-io/cypress/assets/76098865/5a5c96ab-4da0-4422-9453-174fb6588dd4)

### Desired behavior

Test reply file uploads to Cypress cloud

### Test code to reproduce

1. npx cypress run --record --key ...
2. we got Test Replay - Failed Uploading 8/8 - request to https://capture.cypress.io/upload/... failed, reason: socket hang up

### Cypress Version

13.3.0

### Node version

18.17.1

### Operating System

windows 10

### Debug Logs

```shell
Test Replay - Failed Uploading 8/8 - request to https://capture.cypress.io/upload/... failed, reason: socket hang up
```

**Comment by jennifer-shehane** [comment]
@mhnasajpour Are you still encountering this error? Could you send a URL link to the Cloud run where the Test Replay failed uploading?

**Comment by jennifer-shehane** [comment]
Closing since we can't find indication of this error still occurring from our logs on recent versions of Cypress.

**Comment by mhnasajpour** [comment]
https://cloud.cypress.io/projects/modg8a/runs/2/overview/8eea55d6-39dc-4ec1-ba38-5490128436ae?roarHideRunsWithDiffGroupsAndTags=1

I still have this problem

**Comment by jennifer-shehane** [comment]
@mhnasajpour The link to this project if not inspectable, I believe the project may have been deleted. Do you have another example? Ensure it's using the latest Cypress version please.
