### ISSUE TITLE
Cypress test gets stuck/ hang during the executions

### ISSUE THREAD

**Issue by hhamumtaz** [cypress-io/cypress#28007]
### Test code to reproduce

Hi Team,

I am facing an issue while running the Cypress tests. This is exactly happening at a very same page. 

My script routine:
1. Opens an ERP portal
2. Navigates to a particular page
3. Search for an entity

As soon as I try to search it hangs up and never recovers from there.

Tried resolutions:

-   pageLoadTimeout: 60000,
-   requestTimeout: 30000,
-   responseTimeout: 30000,
-   defaultCommandTimeout: 30000,
-   experimentalMemoryManagement: true,
-    numTestsKeptInMemory: 0,

I am using Cypress 13.3.0 and Chrome 117. Previously, I was experiencing Aw snap out of memory issue while working with Chrome. That is not happening anymore but still the hanging is very frequent. I tried to use CYPRESS_NO_COMMAND_LOG=1 but still it shows the same behavior.

My assumption for this issue is the RAM size of my machine. I am using Macbook M1 with 16GB of RAM. Its peaking out to around 13GB of utilization while running the tests thus can be a issue. But the same behavior has been observed while working with 32GB of RAM on windows machine (thats more than ample). 

Please provide any suggestion or way around to cater this. 

### Cypress Mode

cypress run

### Cypress Version

13.3.0

### Browser Version

Chrome 117

### Node version

18

### Operating System

MacOS

**Comment by hhamumtaz** [comment]
@CypressAdam @CypressCecelia

**Comment by Luiz-EduardoPinheiro** [comment]
I'm facing the same problem on several browsers, and after a while, the interactive mode becomes all white.
![image](https://github.com/cypress-io/cypress/assets/51784489/19e04410-4033-4473-a01a-0e890fd35178)

I also have a problem where Chrome keeps loading several times


Cypress: 13.3.0 

Node: v18.16.1

NPM: 9.5.1

**Comment by hhamumtaz** [comment]
HI @Luiz-EduardoPereira 

I have been facing these performance issues for two years now. Cypress consumes a lot of memory specially on mac operating systems. 

As a quick fix, you can try working with the following configurations under your cypress.json file:

    numTestsKeptInMemory: 0,

See if that can help. Else, we have no solution and we have to wait for Cypress team to resolve it. 

Thanks,

**Comment by Luiz-EduardoPinheiro** [comment]
Hello @hhamumtaz, my operating system is Windows, and I already set this configuration, however, it didn't work. :(
![image](https://github.com/cypress-io/cypress/assets/51784489/4b30bcfb-3c46-478c-9903-efcc21d23c1c)
