### ISSUE TITLE
Create default CODE_OF_CONDUCT for all Cypress repos

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28003]
### What would you like?

Move the [CODE_OF_CONDUCT.md](https://github.com/cypress-io/cypress/blob/develop/CODE_OF_CONDUCT.md) from this repository to an organization-wide location at https://github.com/cypress-io/.github/CODE_OF_CONDUCT.md, using GitHub's feature for [default community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) to standardize on one common `CODE_OF_CONDUCT.md` file for the whole [cypress-io](https://github.com/cypress-io/) organization.

### Why is this needed?

There is inconsistent use and non-use of `CODE_OF_CONDUCT.md` files in the [cypress-io](https://github.com/cypress-io/) organization.

If there are multiple copies of `CODE_OF_CONDUCT.md` used in the set of [cypress-io](https://github.com/cypress-io/) organization's repos instead of keeping one copy, the maintenance effort is significantly higher to keep each copy identical.

If some repositories have no `CODE_OF_CONDUCT.md` attached to them, then expected conduct is unclear and has no basis for enforcement.

The [cypress-io](https://github.com/cypress-io/) organization contains more than 100 non-archived GitHub repositories. If all repositories were to be set up without using a central copy of the `CODE_OF_CONDUCT.md` it would be unmanageable.

The following can be found:

- Repositories with their own `CODE_OF_CONDUCT` that is (more or less) a copy of the file in the [cypress](https://github.com/cypress-io/cypress) repo. An example is [CODE_OF_CONDUCT.md](https://github.com/cypress-io/cypress-realworld-app/blob/develop/CODE_OF_CONDUCT.md) in the [cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app) repo.
- Repositories which link back to the file in the [cypress](https://github.com/cypress-io/cypress) repo, for example [CODE_OF_CONDUCT.md](https://github.com/cypress-io/cypress-documentation/blob/main/CODE_OF_CONDUCT.md) in the [cypress-documentation](https://github.com/cypress-io/cypress-documentation/) repo.
- Repositories with no `CODE_OF_CONDUCT`, for instance [cypress-docker-images](https://github.com/cypress-io/cypress-docker-images)

### Other

GitHub's documentation: [Creating a default community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) says:

> You can create default community health files, such as CONTRIBUTING and CODE_OF_CONDUCT. Default files will be used for any repository owned by the account that does not contain its own file of that type.

and explains in detail how to set this up. (The setup would require privileges which community members would not normally hold.)

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Thanks for suggesting this. I didn't know this existed. This is now located here, so we could clean up the code of conduct files across the repo as needed. https://github.com/cypress-io/.github
