### ISSUE TITLE
Can't find an element that includes specific string in href 

### ISSUE THREAD

**Issue by KWorke** [cypress-io/cypress#2801]
I tried to find an element that includes specific string in href:

```js
if (acceptButton.href.should('include', `/path/proposals/${jobId}`)) {
  acceptButton.click()
}
```
and it didn't work

**Comment by jennifer-shehane** [comment]
`.should()` and `.click()` are only chainable off of previous cypress commands - and not able to be chained to an arbitrary `acceptButton` or `href`.

**Comment by jennifer-shehane** [comment]
We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Issues in our GitHub repo are reserved for potential bugs or feature requests. We want our team to spend all the time we have building a better product and hope you understand. ☺️
