### ISSUE TITLE
Investigate why no timing information is sent to CircleCI for internal system tests

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#28019]
### What would you like?

We run our internal tests in CircleCI. Currently many of our tests in the Cypress App are not utilizing CircleCI's [test splitting](https://circleci.com/docs/parallelism-faster-jobs/#how-test-splitting-works) due to our timings not being correctly sent to CircleCI. This can results in slower tests runs for parallelized runs since the parallel runs can't be optimized based on their timings. 

See 'Run system tests' task in a system-tests job in the `linux-64` workflow. https://app.circleci.com/pipelines/github/cypress-io/cypress/57400/workflows/bca19f48-03b4-4656-a353-042f6e7827a3/jobs/2382024/parallel-runs/1?filterBy=ALL

The following errors show:
![Screen Shot 2023-10-10 at 12 06 32 PM](https://github.com/cypress-io/cypress/assets/1271364/345e2388-83c5-4cb5-897a-12bed7cd5c9d)

We need to investigate why the timings are not being sent and hopefully fix it or prioritize the work to fix it.

**Comment by mschile** [comment]
I took a look at the system-test CI jobs and determined why the timings were not found. For the screenshot in the description, all of those specs don't have any tests that run electron so they don't have any timings. If you look at the chrome job, it has a different list. So, I believe it is behaving appropriately right now. If a timing is missing, the spec is assigned a [random small value](https://circleci.com/docs/use-the-circleci-cli-to-split-tests/#set-the-default-value-for-missing-timing-data). 

We could:
* do nothing
* evaluate if some of these specs should be running in other browsers as well
* explicitly exclude specs where there aren't any tests being run
* explicitly set the default timing to be a really low value but I'm not sure it would gain us much

**Comment by jennifer-shehane** [comment]
@mschile Yah I can't totally understand why the tests wouldn't be better distributed. I'm not seeing any one test take longer than a minute in the system tests, but the longest parallel job is 15 min and the shortest one is 8 min. Doesn't look like this is an avenue to go down that would help solve that though.
