### ISSUE TITLE
Test never fails if test starts with Cypress.Promise

### ISSUE THREAD

**Issue by huseyin-tumer** [cypress-io/cypress#28016]
### Current behavior

I am having issue when running test on Cypress.

My test function following is failing but the test status is passed. This happens if the test test starts with Cypress.Promise command. Could you please help?

```
    it('test 1', () => {
        new Cypress.Promise((resolve) => {
            resolve('ok')
        }).then((response) => {
            cy.visit('www.google.com')
            cy.get('x')
        })
    })
```

![image](https://github.com/cypress-io/cypress/assets/45070155/06f3eb4f-a22f-4c39-8919-fff432ba00d3)

Note: it is working truly if the test not stars with Cypress.Promise command like below.

```
it('test 1', () => {
        cy.request('www.google.com').then((response) => {
            new Cypress.Promise((resolve) => {
                resolve('ok')
            }).then((question) => {
                cy.get('x')
            })
        })
    })
```

### Test code to reproduce

```
/// <reference types="cypress" />
describe('New Test', () => {

    it('test 1', () => {
        new Cypress.Promise((resolve) => {
            resolve('ok')
        }).then((response) => {
            cy.visit('www.google.com')
            cy.get('x')
        })
    })

    it('test 2', () => {
        new Cypress.Promise((resolve) => {
            resolve('ok')
        }).then((response) => {
            cy.visit('www.google.com')
            cy.get('x')
        })
    })

})
```

### Cypress Version

13.3.0

### Node version

v16.15.0

### Operating System

macOS Ventura 13.6

**Comment by MikeMcC399** [comment]
@huseyin-tumer 

I'm not experienced with `Cypress.Promise` however it looks like the documenation https://docs.cypress.io/api/utilities/promise#Rejected-test-promises-do-not-fail-tests
covers your case. You might like to check it out.

**Comment by huseyin-tumer** [comment]
@MikeMcC399 thanks for comment, but it did not worked :(
