### ISSUE TITLE
Cypress/grep - All spec is run when only one test has the given tag

### ISSUE THREAD

**Issue by Olavarry** [cypress-io/cypress#28011]
### Current behavior

When I set a tag for one specific test inside a describe block(see below code example), then when I run command to run tests with a tag, I expect that only that one test with a tag is executed, and any other test inside describe block will be ignored.

### Desired behavior

I'd expect that only test with the given tag is executed.

### Test code to reproduce

```
describe('Describe block',{ tags: '#smoke' }, () => {
		before('before block', () => {
			cy.navigate('test.htm');
		});

		beforeEach(function () {
			// before
			console.log('before')
		});

		it('test 1', () => {
			cy.get('.class').should('be.visible')
		});

		
		it('test 2', { tags: '#newTag' }, function () {
			cy.get('#Id').should('be.visible')
		});
	}
);

```
`npx cypress run --env grepTags=#newTag`

In above example, I would expect that only test 2 is run.

### Cypress Version

13.2.0

### Node version

20.7

### Operating System

ventura 13.4.1

**Comment by Crustum7** [comment]
Hello @Olavarry ! I can't find the documentation for using tags in tests this way. Can you provide a link for me to research? In the meanwhile I would recommend using .only ([docs](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Excluding-and-Including-Tests) for temporary isolation of tests or divide the tests into separate files if you seldom want to test them at the same time.

**Comment by Olavarry** [comment]
Hello @Crustum7! 
> https://www.npmjs.com/package/@cypress/grep?activeTab=readme

**Comment by Crustum7** [comment]
Sorry for getting back to you so late @Olavarry. I've tried recreating your setup and loaded the required modules at the top of the spec file which worked. Does the following code work for you?

```
// cypress/support/index.js
// load and register the grep feature using "require" function
// https://github.com/cypress-io/cypress/tree/develop/npm/grep
const registerCypressGrep = require('@cypress/grep')
registerCypressGrep()

describe('Describe block',{ tags: '#smoke' }, () => {
  beforeEach(function () {
    // before
    console.log('before')
  });

  it('test 1', () => {
    cy.log('test1')
  });

  
  it('test 2', { tags: '#newTag' }, function () {
    cy.log('test2')
  });
}
);
```

**Comment by Olavarry** [comment]
Hey @Crustum7 thanks forr looking at this, cypress grep actually works for me, maybe my explanation wasn't clear enough, the issue I see is how it works.
 I have 2 different `it `statemens within a `describe` block, only one of those `it` statements has the **tag** I want to run, when I use this tag to run tests I expect only that one `it` statement to be executed but instead all the `it` statements are executed.

**Comment by Crustum7** [comment]
No problem! 'test 1' was ignored when I ran this test and only 'test 2' was executed which is what I've understood is the expected behavior. What output do you get if you run the code in my previous comment?

**Comment by jennifer-shehane** [comment]
Closing due to no response and inability to recreate issue.
