### ISSUE TITLE
Ensure that deflate/brotli is filtered out in Accept Encoding by the Cypress proxy

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#28025]
Currently, Cypress [tries to filter down](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/request-middleware.ts#L348-L374) Accept-Encoding headers to just gzip. This works when the header is present, but when it is blank according to the [standards for the header](https://www.rfc-editor.org/rfc/rfc9110#field.accept-encoding):

```
If no Accept-Encoding header field is in the request, any content coding is considered acceptable by the user agent.
```

Thus, we need to update the logic to specify `identity` when there is no Accept Encoding header.

The problem would manifest itself in the following scenario:

1. No Accept-Encoding header is sent on a request
2. The server sends back the response encoded in an unsupported encoding (e.g. brotli/deflate)
3. Something in Cypress relies on the decompressed body (this could include `cy.intercept` or CSS, font, and image assets in Test Replay)

**Comment by csvan** [comment]
Wouldn't a more scalable solution be to just support brotli? This encryption is extremely common on the modern web, and Cypress insisting on Gzip actually leads to compression issues when e.g. talking to CloudFront endpoints.

https://github.com/cypress-io/cypress/issues/6197
