### ISSUE TITLE
keyboard function f10 passed in type doesnot work. shift+f10 should give a right click

### ISSUE THREAD

**Issue by debender495** [cypress-io/cypress#2803]

**Comment by jennifer-shehane** [comment]
Could you provide the test code you ran that did not work?

**Comment by Bkucera** [comment]
@debender495 using `trigger` simply sends an event. It will not perform any actions unless you have appcode that specifically listens to that event like so: 
`el.addEventListener('keydown', ()=>...)`

or in React:
`<div onKeydown={...}>`

Feel free to leave a comment if you have any more questions!
