### ISSUE TITLE
We've detected that you're using a 3rd party library that is not supported by Cypress: @deploysentinel/cypress-recorder

### ISSUE THREAD

**Issue by kbouguezzi** [cypress-io/cypress#28044]
### Current behavior

could you help me please? 

When i am running my tests on CI I faced this problem:

**We've detected that you're using a 3rd party library that is not supported by Cypress: @deploysentinel/cypress-recorder

To continue running Cypress, please remove this library and its configuration files or contact us for help migrating.**

https://on.cypress.io/unsupported-third-party-library?p=wrrDnsOfw6rDpsOpw7PDrcOfw6jDrsOjw6jDn8OmwqnDncOzw6rDrMOfw[63](https://github.com/dktunited/sphere-qa-automation/actions/runs/6496283730/job/17644513865#step:5:64)DrcKnw6zDn8Odw6nDrMOew5%2FDrMK6wqrCqMKrwqjCqg%3D%3D

Error: The process '/usr/local/bin/npx' failed with exit code 1

### Test code to reproduce

no

### Cypress Version

13.3.0

### Node version

v18.17.1

### Operating System

windows

**Comment by jennifer-shehane** [comment]
@kbouguezzi To continue running Cypress, you'll need to remove the third party library listed and all configuration files. Our team will follow up again with more information via the email you already sent.

**Comment by wimme** [comment]
Unbelievable. This makes Cypress less "open" and makes us lose trust in the platform. Now we have to stay on version 12 and we will gradually move towards Playwright.
