### ISSUE TITLE
Cypress test with webkit tests fail with "page.goto: An SSL error has occurred and a secure connection to the server cannot be made"

### ISSUE THREAD

**Issue by gurupreeth6** [cypress-io/cypress#28043]
### Current behavior

When I try to run cypress scripts with playwright-webkit, I m getting following error
`page.goto: An SSL error has occurred and a secure connection to the server cannot be made.
=========================== logs ===========================
navigating to "https://{url}/__/#/specs/runner?file=cypress/e2e/BDD/{FeatureName}.feature", waiting until "load"`

### Desired behavior

Tests should run in Safari

### Test code to reproduce

Added following line to cypress.config.js under module.exports
`experimentalWebKitSupport: true,`
and running script with --browser webkit

### Cypress Version

12.17.4

### Node version

v20.8.0

### Operating System

macOS Ventura (13.2.1)

**Comment by gurupreeth6** [comment]
Hi @jennifer-shehane Could you please share if there are any update on this ticket and ETA?

**Comment by ngankimdo** [comment]
Hello @gurupreeth6 @jennifer-shehane has there been any traction on this issue? I'm encountering this also

**Comment by jennifer-shehane** [comment]
No updates to share on this issue. If we pick this issue up, we will comment updates in here.

**Comment by smykserhi** [comment]
Facing the same issue for using webKit. All api calls failed **`An SSL error has occurred and a secure connection to the server cannot be made.`**

**Comment by s-chathuranga-j** [comment]
Getting the same error on Cypress 13.15.2

**Comment by foxracle** [comment]
Getting the same error on Cypress 13.17.0
