### ISSUE TITLE
Cypress 12 upgrade altering request response data affecting app functionality

### ISSUE THREAD

**Issue by ccannawright** [cypress-io/cypress#28047]
### Current behavior

We're working on upgrading to Cypress 13, and have run into an issue that looks to be a bug. We're intercepting a request as such: 
```js
cy.intercept('DELETE', 'URL', (req) => {
                    req.reply({
                        statusCode: 400
                    });
                }).as('alias');
```

In our app we are looking at the method of the request to decide on which error message to display. Specifically we look at response.request.method (this is just looking at the object returned when running the request via axios). But for some reason in Cypress 13, that field along with response.request.url and response.request.id are missing, as opposed to when running in Cypress 11 those three fields are there. 
          
<img width="1627" alt="Screenshot 2023-10-12 at 12 11 50 PM" src="https://github.com/cypress-io/cypress/assets/31831424/04c182af-1fb2-4d49-a3db-3f9d3a89377d">

                

### Desired behavior

Cypress should not be altering what would be returned via axios in our application. 

### Test code to reproduce

Use axios to send a request in an app and log the return from axios. Set up a test to intercept that request 
```js 
cy.intercept('DELETE', 'URL', (req) => {
                    req.reply({
                        statusCode: 400
                    });
                }).as('alias');
```
run the test and check out the log of that request.

### Cypress Version

13.2

### Node version

v18.15.0

### Operating System

macOS 13.6

**Comment by jennifer-shehane** [comment]
@ccannawright Which version were you on previously where this was working? Can you provide a reproducible example?

**Comment by ccannawright** [comment]
I can't share our actual app code - but there was no change in our app code in the branch where we upgraded Cypress. The issue is not occurring on 11.2 and previous versions. We're upgraded from 11.2 to 13.2. I can hop on a call to illustrate the issue though.

**Comment by jennifer-shehane** [comment]
@ccannawright If you have a Cloud account, which includes email support, you can send an email to support@cypress.io.

Outside of that, I'd suggest upgrading to v12 or other versions inbetween 11.2 and 13.2 to first see which version this was introduced.

**Comment by ccannawright** [comment]
okay looks like it's actually the upgrade to 12 that causes it
