### ISSUE TITLE
Cypress open goes out of memory after certain time

### ISSUE THREAD

**Issue by ANSHUL786** [cypress-io/cypress#28040]
### Current behavior

Everytime when my spec run for longer time or i used fixtures large data and lot of assertion it goes to out of memory.

Also, after 30-40 min of uses it start hanging while executing the files.

### Desired behavior

As i am running cypress on my local, i have lot of memory space it should never go into its out of memory case.

### Test code to reproduce

Write a longer test having logs greater than 800 action and run multiple times.

### Cypress Version

13.3.0

### Node version

18.17.1

### Operating System

Windows 11

**Comment by DVersavel** [comment]
This still occurs in version 13.6.0

**Comment by jennifer-shehane** [comment]
@ANSHUL786 We'll need a reproducible example in order to investigate this specifically. We are however investigating many performance improvements at this time.
