### ISSUE TITLE
TypeScript errors - building Cypress from source - 13.3.1 regression

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28049]
### Current behavior

`yarn` outputs multiple errors when executing `tsc` building Cypress from source concerning:

- `@cypress/vite-dev-server:build`
- `@cypress/webpack-dev-server:build`
- `@cypress/vite-plugin-cypress-esm:build`

This is a regression in Cypress `13.3.1` compared to Cypress `13.3.0`.

### Desired behavior

The following subsections should show in the yarn log without any errors listed after them:

```text
@cypress/vite-dev-server: $ tsc || echo 'built, with type errors'
```

```text
@cypress/webpack-dev-server: $ rimraf dist
$ tsc || echo 'built, with type errors'
```

```text
> @cypress/vite-plugin-cypress-esm:build

@cypress/webpack-preprocessor: $ rimraf dist && tsc || echo 'built, with errors'
@cypress/vite-plugin-cypress-esm: $ tsc || echo 'built, with type errors'
```

### Test code to reproduce

```bash
git clone https://github.com/cypress-io/cypress
cd cypress
git checkout v13.3.1 # or checkout develop branch to test the current version
n auto  # to set Node.js to 18.15.0 (or 18.17.1 for current version)
yarn
```

to revert to Cypress `v13.3.0` where the problem does not occur

```bash
git checkout v13.3.0
git clean -xfd
n auto # to set Node.js to 18.15.0
yarn
```

### Cypress Version

First reported on version: `13.3.1`
Reproducible also on version: `13.7.2`

### Node version

~~`18.15.0`~~ `18.17.1`

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

```shell
> @cypress/vite-dev-server:build  [remote cache]

$ tsc || echo 'built, with type errors'
../../cli/types/cy-bluebird.d.ts(4,35): error TS2307: Cannot find module './bluebird' or its corresponding type declarations.
../../cli/types/cy-chai.d.ts(3,22): error TS6053: File '/root/cypress/cli/types/chai/index.d.ts' not found.
../../cli/types/cy-chai.d.ts(6,25): error TS2304: Cannot find name 'Assertion'.
...
...
../../cli/types/index.d.ts(29,22): error TS6053: File '/root/cypress/cli/types/net-stubbing.d.ts' not found.
built, with type errors

> @cypress/webpack-preprocessor:build  [remote cache]

$ rimraf dist && tsc || echo 'built, with errors'

> @cypress/webpack-dev-server:build  [remote cache]

$ rimraf dist
$ tsc || echo 'built, with type errors'
../../cli/types/cy-bluebird.d.ts(4,35): error TS2307: Cannot find module './bluebird' or its corresponding type declarations.
../../cli/types/cy-chai.d.ts(3,22): error TS6053: File '/root/cypress/cli/types/chai/index.d.ts' not found.
../../cli/types/cy-chai.d.ts(6,25): error TS2304: Cannot find name 'Assertion'.
...
...
../../cli/types/index.d.ts(19,22): error TS6053: File '/root/cypress/cli/types/chai-jquery/index.d.ts' not found.
../../cli/types/index.d.ts(29,22): error TS6053: File '/root/cypress/cli/types/net-stubbing.d.ts' not found.
built, with type errors
```

Full log: [yarn_install_13.3.1.zip](https://github.com/cypress-io/cypress/files/12886546/yarn_install_13.3.1.zip)

### Other

Also occurring on CircleCI, go to https://app.circleci.com/pipelines/github/cypress-io/cypress, select

-> linux-x64
    -> build
        -> Build packages

**Comment by MikeMcC399** [comment]
The TypeScript errors output by executing `yarn` against the Cypress `13.5.1` source have changed.

Section | Error for Cypress `13.5.1`
--- | ---
`@cypress/vite-dev-server:build` | error TS2688: Cannot find type definition file for 'cypress'.
`@cypress/webpack-dev-server:build` | error TS2307: Cannot find module './bluebird' or its corresponding type declarations.
`@cypress/vite-plugin-cypress-esm:build` | error TS2307: Cannot find module './bluebird' or its corresponding type declarations.

**Comment by MikeMcC399** [comment]
I am having difficulty consistently reproducing this issue, however I am still seeing it from time to time, including on the current latest commit https://github.com/cypress-io/cypress/commit/7bcb0746e1feb1276fa99caea69a8bd21fd70aea

**Comment by samtsai** [comment]
I'm also facing the same on the latest commit in [`develop`](c6f5e9a5c9bdda6827c37595197ac7048e69faf9).

https://nx.app/runs/O0bfKbUEIl

```
  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 448.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /var/folders/_d/tdzsj0j17bx0sxts7w0n3r6r0000gn/T/yarn--1704726768035-0.2721839805899806/node
    Yarn: 1.22.21 - /var/folders/_d/tdzsj0j17bx0sxts7w0n3r6r0000gn/T/yarn--1704726768035-0.2721839805899806/yarn
    npm: 8.12.1 - ~/Code/cypress/node_modules/.bin/npm
    pnpm: 8.12.0 - ~/Library/pnpm/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Managers:
    Cargo: 1.70.0 - ~/.cargo/bin/cargo
    Homebrew: 4.2.3 - /opt/homebrew/bin/brew
    pip3: 23.3.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.43.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Monorepos:
    Yarn Workspaces: 1.22.21
    Lerna: 6.6.2
```

**Comment by MikeMcC399** [comment]
This issue is labeled https://github.com/cypress-io/cypress/labels/stage%3A%20ready%20for%20work and current CircleCI logs confirm a continuing problem in the default [develop](https://github.com/cypress-io/cypress) branch.

For CircleCI, go to https://app.circleci.com/pipelines/github/cypress-io/cypress, select

-> linux-x64
    -> build
        -> Build packages

![image](https://github.com/cypress-io/cypress/assets/66998419/3f6c1df1-e036-456c-88a0-a7493dda5ae4)

**Comment by MikeMcC399** [comment]
The issue is also reproducible running `yarn build` in a GitHub runner where the errors show as annotations:

![image](https://github.com/cypress-io/cypress/assets/66998419/7caffec1-c306-4824-aa7a-71918a823341)

**Comment by MikeMcC399** [comment]
This issue is no longer reproducible after merge of the following PRs into the `develop` branch:

- https://github.com/cypress-io/cypress/pull/29568
- https://github.com/cypress-io/cypress/pull/29617

cc: @AtofStryker
