### ISSUE TITLE
Loading webassembly dlls is a lot slower after updating Cypress V13.3.0 to V13.3.1

### ISSUE THREAD

**Issue by MelvinBaaijAviva** [cypress-io/cypress#28054]
### Current behavior

In our application we are generating and previewing pdf's and for this purpose we are using Webassembly .
I updated Cypress from V13.3.0 to V13.3.1
Getting the dll's needed from Webassembly takes a lot longer than before (on my local environment it takes 2000ms (V13.3.1) per dll instead of 500ms in V13.3.0)
(using chrome browser V118.0.5993.70 )

### Desired behavior

Updating to a higher version should not impact the performance of loading the Webassembly dlls

### Test code to reproduce

No specific test code to reproduce upgrading and downgrading from the stated versions results in the behaviour

### Cypress Version

13.3.1

### Node version

v16.20.0

### Operating System

Windows 10 Enterprise 10.0.1904b Build 19045

### Debug Logs

```shell
example with Cypress V13.3.0 getting some of these dlls:

GET /js/wasm/managed/System.Threading.Thread.dll 304 563.580 ms - -
GET /js/wasm/managed/System.Threading.ThreadPool.dll 304 563.870 ms - -
GET /js/wasm/managed/System.Threading.Timer.dll 304 564.543 ms - -
GET /js/wasm/managed/System.Threading.dll 304 562.591 ms - -

example with Cypress V13.3.1 getting same dlls:
GET /js/wasm/managed/System.Threading.Thread.dll 304 2049.957 ms - -
GET /js/wasm/managed/System.Threading.ThreadPool.dll 304 2066.895 ms - -
GET /js/wasm/managed/System.Threading.Timer.dll 304 2062.693 ms - -
GET /js/wasm/managed/System.Threading.dll 304 2063.532 ms - -
```

**Comment by ryanthemanuel** [comment]
Hi @MelvinBaaijAviva. Thanks for logging this. We inadvertently introduced a performance regression for this specific scenario as a result of fixing another bug in our proxy correlation logic (see #28056 ). We are currently looking into a fix.

**Comment by ryanthemanuel** [comment]
@MelvinBaaijAviva we are working on a patch release for this. Note that this may end up making the requests even faster than they were previously (i.e. faster than 500 ms)

**Comment by MelvinBaaijAviva** [comment]
@ryanthemanuel 
Thanks for solving this. I'm not at the office at the moment. Will try it next week and report back if needed.
