### ISSUE TITLE
Previously working tests no longer work after 3.1.1 -> 3.1.2

### ISSUE THREAD

**Issue by mchapman** [cypress-io/cypress#2805]
My test suite starts with a test that signs in (in much the same way as your tutorial advises, using a cy.request POST) updates a few forms then stops - leaving some unsaved changes.  The next test does the same.  This was working fine in 3.1.0 and 3.1.1.

Since the upgrade to 3.1.2 the second test fails, as it seems to carry on with the session from the first test (which was previously not the case) and a dialog asking whether to save changes comes up.

### Versions

Cypress 3.1.2
Ubuntu 16.04
Chrome and Electron

**Comment by L-four** [comment]
I think I am having the same issue and have create a project with a minimal example https://github.com/L-four/cypress_cookie_bug
 It's seems to happen when working with many subdomains in the test i use `http://too.many.sub.domains.local`

**Comment by mchapman** [comment]
FWIW I just tried 3.1.5 and it works fine on (essentially) the same tests, so my problem is gone.  @L-four may not find it fixes their problem though, so leaving open.

**Comment by L-four** [comment]
I am still seeing this issue. As per my example.

**Comment by jennifer-shehane** [comment]
@L-four I'm no longer able to run the provided repo from the provided instructions.

Could anyone facing this run Cypress in our [latest version](https://on.cypress.io/changelog). We've fixed lots of cookies issues since then and we believe this to be fixed. Closing as resolved.
