### ISSUE TITLE
Release SHA256 hash keeps changing

### ISSUE THREAD

**Issue by pullard** [cypress-io/cypress#28078]
### Current behavior

To verify the binary being installed a sha256 check is used to confirm that the release is unchanged. I have noticed on 2 separate occasions that the hash has been altered for `v13.3.0`.

For `linux-x64` it has been hosted under these 3 hashes thus under far via the same URL:
https://cdn.cypress.io/desktop/13.3.0/linux-x64/cypress.zip

**SHA256 Hashes:**
```
527dde8c3a8b3a1ae892167599b661da2a9ffed32e8e3457822110805c3c2443 (until Oct 4th)
041c0bed4db3e015026beac5c0afdc687caf5d515eef083637d1d03ee7134fb5 (after Oct 4th)
889c05c3e47df2840d592a3a70b91cd8df703f8f183d9f5ad2a01692071ac77f (current)
```

This problem also exists for `linux-arm64` but, I do not have the hashes off-hand for that. Although, they're always modified in pairs.

### Desired behavior

This hash should not change & a given release should not be modified unless announced. Preferably a patch should be administered instead of modifying the server package.

### Test code to reproduce

```sh
echo "889c05c3e47df2840d592a3a70b91cd8df703f8f183d9f5ad2a01692071ac77f ./cypress.zip" | sha256sum --check
./cypress.zip: OK
```

### Cypress Version

13.3.0

### Node version

16.19.0

### Operating System

Ubuntu 18.04

**Comment by jennifer-shehane** [comment]
@pullard There are very rare circumstances where the binary hash is updated. This is not the norm and typically fixes come via official App releases or via the Cloud (if it’s relevant to that service). We’ve been working on resolving a couple of issues that were originally introduced around our binary build process, so this is what is reflected here. I don't anticipate any more changes at this time as I'm hopeful we fixed the original issues 🙏🏻
