### ISSUE TITLE
Reload page after a test failure (and before a retry)

### ISSUE THREAD

**Issue by alecmestroni** [cypress-io/cypress#28082]
### Current behavior

When a test fails there is no possibility to reload the page and retry the tests. 
I have already opened this is issue (https://github.com/cypress-io/cypress/issues/26774) but in the meanwhile I'm trying to find a solution.
I'm trying to use location.reload() instead of  cy.reload() inside a cy.on('fail').
But a strange loop starts to happen and cypress didn't fail anymore (in the example Cypress doesn't checks for the cy.get('pippo') item in the DOM)

### Desired behavior

I just want the ability, in case of failure, to reload the page and run the same test again. Occasionally it happens that every component doesn't load correctly, but a reload is enough to make them ok again.
Considering this need I understand why the cy.reload() command does not work within the cy.on('fail) command. But I don't understand this behavior of cypress when I try to do a location.reload()

### Test code to reproduce

```js
describe('My Describe', { testIsolation: false }, () => {
	it('My first It', { retries: 1 }, () => {
		cy.visit('https://www.google.com').then(() => {
			cy.get('pippo')
		})
		cy.on('fail', (error, runnable) => {
			window.location.reload();
			throw error
		})
	})
	it('My Second It', () => {
		expect(true).to.equal(true);
	})
})
```

### Cypress Version

13.3.1

### Node version

v18.18.0

### Operating System

Windows 11 Enterprise 22H2 22621.2428

**Comment by jennifer-shehane** [comment]
@alecmestroni What is it that the `retries` option is not satisfying in this case? Why does your test require the entire browser to reload?

**Comment by alecmestroni** [comment]
@jennifer-shehane  for example in my company we have one webcomponent that's a little bit flaky.
Sometimes it's load correctly sometimes not loaded at all (1 on 20)
Have the possibility to reload the page before retrying the test, would be the best option in my case
