### ISSUE TITLE
invoke('removeAttr', 'target').click() test for new tab not working on cypress run

### ISSUE THREAD

**Issue by anjeff1225** [cypress-io/cypress#28088]
### Current behavior

Since the cypress not support test on multiple tab. I used the work around to test new tab by using. I use the below work around

If the target value is “_blank”, we can remove the attribute and the link will open in the same tab. This is because, as mentioned in the table above, when “target=_blank”, the link is set to open in a new tab or window.

Sample Code:

cy.get(‘.example > a’)

.invoke(‘removeAttr’,’target’).click();

It works perfectly when using cypress open, but not working for cypress run. Error log for cypress run
```
CypressError: Timed out after waiting `60000ms` for your remote page to load.

Your page did not fire its `load` event within `60000ms`.

You can try increasing the `pageLoadTimeout` value in `cypress.config.js` to wait longer.

Browsers will not fire the `load` event until all stylesheets and scripts are done downloading.
```

Cypress version:
```
$ npx cypress --version
Cypress package version: 10.11.0
Cypress binary version: 10.11.0
Electron version: 21.0.0
Bundled Node version:
16.16.0
```

### Test code to reproduce

    elementInvokeandClick(elem) {
        return this.elementIsExist(elem).invoke('removeAttr', 'target').click()
    }

### Cypress Version

10.11.0

### Node version

16.16.0

### Operating System

windows10

**Comment by jennifer-shehane** [comment]
@anjeff1225 Could you try updating and using the latest version of Cypress to test this? It's possible this issue has already been fixed.

**Comment by AbuOx** [comment]
> @anjeff1225 Could you try updating and using the latest version of Cypress to test this? It's possible this issue has already been fixed.

I'm currently using Cypress v. 12.14.0, and this issue is still reproducible. Is there any known alternative way we can use instead in these scenarios that can also work on cypress run?

**Comment by anjeff1225** [comment]
@jennifer-shehane  Since it still reproduceable by @AbuOx  on version 12.14.0. Can this be reopen and someone take a look?
