### ISSUE TITLE
Windows 10 installs cypress through NPM and cannot open cypress. Execution. / node_modules/.bin/cypress open does not respond and does not open the GUI of cypress.

### ISSUE THREAD

**Issue by xiaoxu12** [cypress-io/cypress#2809]

**Comment by xiaoxu12** [comment]
cypress在window10上的问题

**Comment by aldarund** [comment]
Its https://github.com/cypress-io/cypress/issues/2667 which wasnt really fixed...

**Comment by lgraziani2712** [comment]
Cypress v3.1.2 fixes the issue. I had nodejs v11.0.0, and cypress v3.1.2 didn't work, but after upgrading to nodejs v11.2.0 everthing was fine.

If you have Node v11, try upgrading to v11.2.0++

**Comment by aldarund** [comment]
indeed, it work in 11.2.0 although dont work in 11.1 and 11.0

**Comment by brian-mann** [comment]
Released in [`3.1.3`](https://docs.cypress.io/guides/references/changelog.html#3-1-3).
