### ISSUE TITLE
Cypress doesn't start my Angular tests

### ISSUE THREAD

**Issue by directcuteo** [cypress-io/cypress#28099]
### Current behavior

When I start any e2e test for my Angular application I am getting the following error and the test doesn't start:

![image](https://github.com/cypress-io/cypress/assets/37619567/a249ce37-146f-40cf-88dc-d01e81b8a15d)

### Desired behavior

I would expect Cypress to start my test.

### Test code to reproduce

The code is not even reached...

### Cypress Version

13.3.2

### Node version

18.18.0

### Operating System

macOS 14

### Other

Angular v16.1.8

**Comment by jennifer-shehane** [comment]
@directcuteo Can you provide a reproducible example so that we can debug?

**Comment by kevinhng** [comment]
I am also getting this same error after installing all the required dependencies for 'angular' component testing. Our angular project utilises both e2e tests and component tests. If you don't install the component testing dependencies , the E2E tests will function normally and you won't get this error FYI. @jennifer-shehane 

Cypress Version: 13.5.0
Node: 18.10.0
Angular: V16

Did you manage to solve this @directcuteo ?

**Comment by jennifer-shehane** [comment]
Unfortunately we’ll have to close this issue as we haven’t been given enough information to assist.
