### ISSUE TITLE
Cypress interprets underscores in URL as formatting instructions on frontend

### ISSUE THREAD

**Issue by josh-atkins** [cypress-io/cypress#28100]
### Current behavior

When I visit a page in a Cypress test that includes underscores, such as "http://localhost:3000/__testing__/", the Cypress frontend interprets the underscores as formatting instructions (i.e. as markdown). This causes the frontend to report the URL as "http://localhost/testing/", with "testing" displayed in bold.

This is problematic because it provides a distraction when debugging e.g. it suggests that Cypress is following a different route than what is provided in the test.

<img width="367" alt="image" src="https://github.com/cypress-io/cypress/assets/143029067/12bc25b9-866c-4e0d-a72b-8b4b673e0ccd">

<img width="280" alt="image" src="https://github.com/cypress-io/cypress/assets/143029067/3afe87c7-801c-4207-b95f-86a1c364e831">

### Desired behavior

The Cypress frontend should interpret the URL literally and not interpret any formatting instructions from the original string.

### Test code to reproduce

A simple test should demonstrate the error when viewed in the Cypress frontend.

```
describe('the http://localhost:3000 website', () => {

    it('should visit /__testing__/', () => {

        cy.visit("http://localhost:3000/__testing__/");

    })

});
```

### Cypress Version

13.3.1

### Node version

20.5.1

### Operating System

macOS 13.3.1

**Comment by jennifer-shehane** [comment]
I agree, this is not great. We're open to a pull request to fix it. Not sure how straightforward that may be.
