### ISSUE TITLE
CypressError not included in JSON reporter

### ISSUE THREAD

**Issue by pascalism** [cypress-io/cypress#2810]
Seems like the JSON reporter does not include the actual CypressError otherwise displayed in terminal output.

### Current behavior:

Output in default reporter stack: 
```
CypressError: cy.click() failed because it requires a DOM element.

The subject received was:

  > undefined

The previous command that ran was:

  > cy.get()
```

### Desired behavior:

Also include the CypressError in the output of the JSON reporter:
```
 CypressError: Timed out retrying: Expected to find element: '[data-cy=fooBar]', but never found 
```

**Comment by jennifer-shehane** [comment]
The error you are getting in your terminal may also be relevant to this issue: https://github.com/cypress-io/cypress/issues/2199

Thanks for reporting the issue!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
