### ISSUE TITLE
Trying to run test in Jenkins- got "Cypress executable not found at: /var/lib/jenkins/.cache/Cypress/3.1.2/Cypress/Cypress" error

### ISSUE THREAD

**Issue by KWorke** [cypress-io/cypress#2811]
The root should be: `/usr/local/lib/node_modules` instead of `/var/lib/jenkins/.cache/Cypress/3.1.2/Cypress/Cypress`.
Where do I configure the right path?

**Comment by jennifer-shehane** [comment]
There are some cache configurations explained here: https://on.cypress.io/installing-cypress#Advanced

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having trouble and we can reopen.
