### ISSUE TITLE
cy.visit() times out 

### ISSUE THREAD

**Issue by EkkurNe-EV** [cypress-io/cypress#28114]
### Current behavior

Current behavior:
Upon running cy.visity() and inputing a URL, the request times out.
```
Timed out after waiting 60000ms for your remote page to load.
Your page did not fire its load event within 60000ms.
You can try increasing the pageLoadTimeout value in cypress.config.ts to wait longer.
Browsers will not fire the load event until all stylesheets and scripts are done downloading.
```

Desired behavior:
Trying to run a simple cy.visit() command but unable to

Steps to reproduce: (app code and test code)
Versions
running 13.3.2. Note: The same script worked couple days back or a week back. Might be Release version.

System: MAC PRO

### Test code to reproduce
```js
const urls = ['atlanta', 'victoria']

describe('Validating all', () => {

    //for each URL do the thing in here
    urls.forEach(url => {
        describe(`url: ${url}`, () => {
            it(`Should display logo on ${url}`, () => {
                cy.visit(`http://${url}.our-website`);
            });
        });
    })
});
```

### Cypress Version

13.3.2

### Node version

v19.8.0

### Operating System

macOS 13.5.2

**Comment by Maximilian94** [comment]
Same problem here :/

**Comment by jennifer-shehane** [comment]
@EkkurNe-EV Can you revert your Cypress version and ensure this same test works in an earlier version of Cypress and verify that version? That would help narrow down the issue quite a bit for us. 

Also if someone could provide a piece of code with some public url we could run to see the problem occur in the new version of Cypress and not in older version, we could track down the bug if there is one. Thanks!

**Comment by EkkurNe-EV** [comment]
will do. I am very curious too. I have been playing around with node versions but no luck. Will update in a while

**Comment by EkkurNe-EV** [comment]
Cypress Version 9. Same issue . Now I guess the issue might be Cypress runner since when we run npm run Cypress it has the latest runner

**Comment by EkkurNe-EV** [comment]
![image](https://github.com/cypress-io/cypress/assets/120519565/dfe077eb-fac3-4509-ba05-b28fdaf1e841)

**Comment by jennifer-shehane** [comment]
@EkkurNe-EV We'll need a way to run and reproduce this in order to investigate. Since the issue started a couple days ago and is not relevant to Cypress version, then I would suggest narrowing down what changed within that time on your side.

**Comment by EkkurNe-EV** [comment]
The only change is I updated Chrome. I am going to troubleshoot more and will try to give as much information as I can. We are in between release so please expect delay.

**Comment by EkkurNe-EV** [comment]
@jennifer-shehane Troubleshooted the issue and resolved it with node 20.9.0 version and cy v12.9.0. 
Here are the steps: uninstalled node and cypress. Cy v12.9.0 doesnt give any errors mentioned in the screenshot above. Test run succesful.

Reproduced with Node 20.9.0 and cy v13.3.2. 
Hope this helps.

**Comment by jennifer-shehane** [comment]
Since we haven’t been provided a way to reproduce this to investigate, we’ll have to close this issue as it’s not actionable on our side.

**Comment by Mandla-SM** [comment]
I have what I think is the same issue.
```
describe('Home page', function() {
    beforeEach(() => {
        cy.visit("http://192.168.0.115:8000/")
    });
    it('check navbar', function() {
        ...
    it('main section', function() {
        ...
    it('featured section', function() {
        ...
    it('testimonial section', function() {
        ...
    it('bottom section', function() {
        ...
    it('footer section', function() {
        ...
```

80% of the time it stops running at testimonial section', 10% at bottom section' and 10% works fine.

<img width="436" height="128" alt="Image" src="https://github.com/user-attachments/assets/ad7815df-93eb-41bc-8e24-5ac0d848f383" />

This does not happen in version 12.9.0
I have experienced it in these versions:
14.2.1
14.5.4
15.0.0
15.2.0
15.9.0

I'm running it on Ubuntu 22, cypress 15.9.0, npm: '11.7.0', node: '25.3.0', bun 1.3.6
whether started with bunx or npx

It works 100%, If I run the tests one at a time like:
```
describe('Home page', function() {
    beforeEach(() => {
        cy.visit("http://192.168.0.115:8000/")
    });
    it.only('testimonial navbar', function() {
        ...
```
