### ISSUE TITLE
Google Chrome for testing - version not parsed correctly

### ISSUE THREAD

**Issue by jannesep** [cypress-io/cypress#28123]
### Current behavior

When using Google Chrome for testing, Cypress cannot parse the browser version correctly:
```
bash-5.1$ chrome --version
Google Chrome for Testing 118.0.5993.70
```

`browser: { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', version: 'for', path: 'chrome', minSupportedVersion: 64, majorVersion: 'for', isHeadless: true, isHeaded: false }`

### Desired behavior

Cypress should add "Google Chrome for Testing" for the browser detection.

### Test code to reproduce

Not applicable

### Cypress Version

13.3.2

### Node version

18.18.2

### Operating System

Red Hat Enterprise Linux release 9.2 (Plow)

**Comment by jennifer-shehane** [comment]
Oh, that is not great. Open to a PR to fix this.

**Comment by MikeMcC399** [comment]
Not yet resolved. On Ubuntu `22.04.4` browser is identified as

"Custom Chrome for"

and fails to complete a run.
> The browser never connected. Something is wrong. The tests cannot run. Aborting...

https://on.cypress.io/chromium-downloads > https://www.chromium.org/getting-involved/download-chromium/
Follow instructions to download
Download the latest available Chrome for Testing binary corresponding to the Stable channel.
`npx @puppeteer/browsers install chrome@stable`

Browser is installed in current directory e.g. under sub-directory:

chrome/linux-124.0.6367.207/chrome-linux64/chrome

`npx cypress run --e2e --browser chrome/linux-124.0.6367.207/chrome-linux64/chrome`


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.9.0                                                                         │
  │ Browser:        Custom Chrome for (headless)                                                   │
  │ Node Version:   v20.13.1 (/home/mike/n/bin/node)                                               │
  │ Specs:          1 found (spec.cy.js)                                                           │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by MikeMcC399** [comment]
- This issue is related to https://github.com/cypress-io/cypress/issues/28554
