### ISSUE TITLE
Computed SHA-384 integrity error - failed to run tests

### ISSUE THREAD

**Issue by robrecht-vanmelckebeke** [cypress-io/cypress#28122]
### Current behavior

Tests are currently failing in my Angular project. Issue narrowed down to usage of npm package azure-maps-control

<img width="1322" alt="Screenshot 2023-10-24 at 12 23 57" src="https://github.com/cypress-io/cypress/assets/7600560/ac45b346-3a39-462b-9514-06461164654c">

This error only occurs when running my application with cypress, when browsing to the app manually it works smoothly and no errors are in console

I tried with experimentalModifyObstructiveThirdPartyCode: true but same errors

### Desired behavior

Tests should run the same in cypress as manually

### Test code to reproduce

I don't have this available yet

### Cypress Version

13.3.1

### Node version

20.2.0

### Operating System

Amazon Linux 2

**Comment by jennifer-shehane** [comment]
@robrecht-vanmelckebeke Can you provide a reproducible example that we can run?

**Comment by jennifer-shehane** [comment]
Closing as stale.
