### ISSUE TITLE
Icons rendering issue

### ISSUE THREAD

**Issue by martakarwacka** [cypress-io/cypress#28126]
### Current behavior

Sometimes when performing tests, the icons do not render correctly and it is impossible to click on them - the test fails.

![image](https://github.com/cypress-io/cypress/assets/17450157/4348ef8d-25c0-4b26-8bed-af5a939b837a)

### Test code to reproduce

-

### Cypress Version

10.3.2

### Node version

-

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
@martakarwacka Could you try updating to our most recent version of Cypress? We may have already fixed this issue. After verifying it still exists in a recent issue, please provide a reproducible example we can run to see the issue. There's nothing we can do with the information provided as is.

**Comment by martakarwacka** [comment]
13.3.3 version helps. thanks
