### ISSUE TITLE
Error: Session with given id not found.

### ISSUE THREAD

**Issue by remarkablemark** [cypress-io/cypress#28148]
### Current behavior

Cypress is failing in GitHub Actions workflow:

```
Session with given id not found.
Error: Session with given id not found.
    at <embedded>:2466:519827
    at _._handleMessage (<embedded>:2466:521860)
    at A.<anonymous> (<embedded>:2466:521673)
    at A.emit (node:events:513:28)
    at g.U (<embedded>:2466:506953)
    at g.emit (node:events:513:28)
    at g.dataMessage (<embedded>:2466:487328)
    at <embedded>:2466:486860
    at <embedded>:2466:478182
    at <embedded>:2466:479134
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.<anonymous> (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

### Desired behavior

Cypress GitHub Action passes

### Test code to reproduce

https://github.com/remarkablemark/cypress-cucumber-steps/pull/537

### Cypress Version

13.3.3

### Node version

18.18.2

### Operating System

Ubuntu 22.04.3

### Other

Related to https://github.com/cypress-io/cypress/issues/28136#issuecomment-1779617812

**Comment by joel-jo-querypie** [comment]
I have the same issue

**Comment by priya-mani-2308** [comment]
Facing same issue from my end as well.

**Comment by utkuperlego** [comment]
facing the same issue for the first time on our ci/cd pipeline on AWS

**Comment by StevenVanbrielRosa** [comment]
I have the same issue together with https://github.com/cypress-io/cypress/issues/28142

**Comment by Shankar-Goit** [comment]
I am also facing the same issue, it was working fine jut before one day.

**Comment by dowlaszewicz** [comment]
Same issue here

**Comment by theumann** [comment]
Same issue after 13.3.3 upgrade.

**Comment by bleepax8** [comment]
Ditto

**Comment by Znakki** [comment]
came across the same issue with cypress 13.3.3 , headless mode, gitlab-runner 16.2.0, image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
Running tests on Chrome

**Comment by MikeMcC399** [comment]
@remarkablemark 

I was able to reproduce this locally as a regression in Cypress `13.3.3`. The crash does not depend on GitHub Actions, nor does it depend on Chrome.

On Ubuntu `22.04.3` with the following steps:

```bash
git clone --branch dependabot/npm_and_yarn/cypress-13.3.3 https://github.com/remarkablemark/cypress-cucumber-steps
cd cypress-cucumber-steps
n 18.18.2 # to set Node.js to 18.18.2
npm ci
npx cypress info
npx cypress run --browser chrome
```

The crash shows itself as:

```text
  Cypress docs
    ✓ Alt text (43265ms)
Session with given id not found.
```

and this only appears when using Cypress `13.3.3`.

Testing with `npx cypress open` and selecting 
`cypress/e2e/cypress/docs.feature` with 3 scenarios:

| Browser  | Version        | Result `13.3.2` | Result `13.3.3`    |
| -------- | -------------- | ------------- | ---------------- |
| Electron | v114           | 1/3 fail      | crash            |
| Chrome   | 118.0.5993.117 | 0 fail        | crash            |
| Chromium | 118.0.5993.117 | 1/3 fail        | crash            |
| Edge     | 118.0.2088.69  | 0 fail        | crash            |
| Firefox  | 119.0          | 0 fail        | 2/3 tests failed |

**Comment by MikeMcC399** [comment]
- Cypress `13.3.3` also crashed testing against Electron with Node.js `v20.9.0` and `v21.1.0` on Ubuntu `22.04.3`.

- On Windows 11 22H2, the same test ran without issue using Cypress `13.3.3`, Electron `v114` and Node.js `18.18.2`.
- Testing against Chrome `118.0.5993.118` on Windows 11 22H2 / Node.js `18.18.2` was also successful.

**Comment by ryanthemanuel** [comment]
This was fixed with #28147 and will be released ASAP.

**Comment by remarkablemark** [comment]
Thank you for the quick fix!

**Comment by MikeMcC399** [comment]
@remarkablemark 

Let us know if [cypress@13.4.0](https://docs.cypress.io/guides/references/changelog#13-4-0) fixes this for you!

**Comment by Shankar-Goit** [comment]
Hi @MikeMcC399 ,
I can able to run the scripts in chrome browser after upgrading the cypress version to 13.4.0.
Thanks team for quick support!.

**Comment by remarkablemark** [comment]
@MikeMcC399 Thanks, I can confirm it is fixed in https://github.com/remarkablemark/cypress-cucumber-steps/pull/543
