### ISSUE TITLE
@cypress/grep crashing Chrome

### ISSUE THREAD

**Issue by irbrad** [cypress-io/cypress#28145]
### Current behavior

The @cypress/grep module crashes Chrome in my CI/CD pipeline after about 20 burns on the same two tests running on the same container.  The passes incrementally slow down as the burn cycle progresses.  I tried setting `experimentalMemoryManagement` to `true` and `numTestsKeptInMemory` to `0` with no luck.  

Running: 
* Cypress 12.17.4
* @cypress/grep 4.0.0
* node: 16.18.1
* Chrome 109.0.5414.74-1

### Desired behavior

For the burn run to not crash Chrome and for the test suite to finish.

### Test code to reproduce

Internal code, can not share.  Basically logs in, clicks around to 3-4 pages, runs assertions on each to determine that they rendered properly, and finally logs out.

### Cypress Version

12.17.4

### Node version

16.18.1

### Operating System

ubuntu 22.04

**Comment by jennifer-shehane** [comment]
@irbrad This behavior does not crash if you’re not using the grep plugin and running the exact same tests?

there won’t be much we can do without a reproducible example. We’ve never had crashes reported with this plugin before so it’s likely very specific to something with your code or setup. If you can provide any more detail or a reproducible example, this will be needed in order for us to diagnose the problem.

**Comment by jennifer-shehane** [comment]
Clsoing since no repro example is provided.
