### ISSUE TITLE
Assertion does not run on all elements after calling invoke

### ISSUE THREAD

**Issue by upman** [cypress-io/cypress#2814]
### Current behavior:
![screen shot 2018-11-20 at 6 10 03 pm](https://user-images.githubusercontent.com/5287426/48790422-94a54c80-ecef-11e8-85bb-527fbf03fcc7.png)

```js
cy.get('img').invoke('attr', 'src').should('not.be.empty');
```
This runs the assertion only on the first image

### Desired behavior:

Should tun the non-empty assertion on all the img elements on the page.

### Steps to reproduce:

Run the above cypress code on any page with images.

### Versions
cypress@3.1.0, mac 10.14.1, Google Chrome 70.0.3538.102 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Yeah, this is definitely confusing since it seems to show '48' src attributes being shown but only asserts on one. 

You may want to use a `.each()` on the elements. 

```js
cy
  .get('img')
  .each(($img) => {
      cy.wrap($img).invoke('attr.src').should('not.be.empty')
  })
```

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
