### ISSUE TITLE
Scrolling elements into view broken when using scroll-behavior: smooth

### ISSUE THREAD

**Issue by aKzenT** [cypress-io/cypress#28150]
### Current behavior

Starting with version 13.3, the scrolling of elements into view, triggered e.g. by "click" no longer works when using scroll-behavior: smooth. This causes actionability checks to fail.

We are setting scroll-behavior: smooth directly on the "html" tag.

I noticed that there were some changes done in that area in the 13.3 version which are probably causing the issue.
https://github.com/cypress-io/cypress/pull/27860/files#diff-10c3dbee8439d9d33f63478cc0b81d1e87bf6e50530c3669f159bdf5c97bb7a6

### Desired behavior

Scrolling should work as it has worked until version 13.2

### Test code to reproduce

no repo, sorry

### Cypress Version

13.3

### Node version

20.2

### Operating System

Windows 11

**Comment by sizzle168** [comment]
Same issue here!

**Comment by jennifer-shehane** [comment]
@aKzenT @sizzle168 Please provide a reproducible example of the behavior, including what the HTML is, how scroll-behavior is being added, etc. We have tests around this behavior, so likely it's an edge case. We won't be able to begin fixing it until we get an idea of this edge case to fix.

**Comment by aKzenT** [comment]
@jennifer-shehane I added a repro here: https://github.com/aKzenT/cypress-scroll-bug/ . It seems the problem occurs, when the body element uses "overflow-y: auto;"

**Comment by jennifer-shehane** [comment]
@aKzenT Thanks! We'll take a look.
