### ISSUE TITLE
Add Angular 17 Support for CT

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/cypress#28153]
### What would you like?

Angular 17 is set to launch on November 6. Ideally we will have support in CT on day 1.

### Why is this needed?

Supporting the newest versions of our frameworks is crucial for overall adoption and trust in the long term state of CT

**Comment by MikeMcC399** [comment]
@jordanpowell88 

Good move! Angular 16 suffers from the disadvantage that it does not officially support Node.js `20`, which has now become the active LTS version. 

Please also include updating https://github.com/cypress-io/component-testing-quickstart-apps with Angular 17.

(~~And whilst I'm on the subject of that repo, there are two PRs at https://github.com/cypress-io/component-testing-quickstart-apps/pulls waiting for attention.~~) Edit: Thanks for merging!

## References

- https://angular.io/guide/versions
- https://github.com/nodejs/release#release-schedule

**Comment by MikeMcC399** [comment]
Angular 17 has been announced for release this week. Right now it is still in RC status:

```text
$ npm view @angular/cli dist-tags
{
  latest: '16.2.9',
  next: '17.0.0-rc.4',
  'v6-lts': '6.2.9',
  'v8-lts': '8.3.29',
  'v7-lts': '7.3.10',
  'v9-lts': '9.1.15',
  'v10-lts': '10.2.4',
  'v11-lts': '11.2.19',
  'v12-lts': '12.2.18',
  'v13-lts': '13.3.11',
  'v14-lts': '14.2.13',
  'v15-lts': '15.2.10'
}
```
