### ISSUE TITLE
Issue with  loading webassembly dlls (non cached- performance) in version 13.3.2 and issue showing pdf preview in version 13.3.3

### ISSUE THREAD

**Issue by MelvinBaaijAviva** [cypress-io/cypress#28162]
### Current behavior

Hi,

I previously created issue #28054 .This one should be fixed and therefore I updated to V13.3.2
V13.3.2 solves the issue for the cached calls, but not when the dlls are not yet cached (and the webassembly calls are resulting in 200 response codes). The duration of these calls is still about 2000 ms. But after waiting a long time the pdf preview is shown .

I updated to V13.3.3 since I saw some of shared worker / performance issues are fixed in this version. But now the pdf preview is not loading /showing the pdf at all.
Could you please have a look into this

### Desired behavior

All situations etc are working as expected without any negative impact on the performance .

- situation as described in #28054 
- situation as described in Current Behevior part of this issue
-- showing the pdf preview file
-- no negative impact on performance for webAssembly dlls that are not cached yet

V13.3.0 is working fine.

### Test code to reproduce

Not available

### Cypress Version

13.3.2 and 13.3.3

### Node version

16.20.0

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
@MelvinBaaijAviva Can you provide a reproducible example of the issue? Or a video of the behavior? Something to see and in the best case recreate the issue ourselves.

**Comment by jennifer-shehane** [comment]
@MelvinBaaijAviva Are you using an object tag for the PDF? This issue has been identified where we're working on a fix. Can't tell if that would address your issue at this point.

**Comment by MelvinBaaijAviva** [comment]
@jennifer-shehane  Unfortunately I can not provide a reproducible example or video (due to company regulations) . I can give you some more info.
As described in #28054 . We are using Webassembly for generating and previewing pdf files inside the Chrome browser . 
A lot of dlls are loaded, every dll takes about and after some time the pdf is shown in the chrome browser

V13.3.0 
the first time It takes about 500 ms to get the dll and after some time the pdf is generated and shown inside the browser. (I can assert on the pdf src by using a third party dependency)
The next time I run this scenario it takes about the same time to get a dll, but in this scenario all the dlls have the response status 304 (I think because the dlls are cached somewhere inside the browser the first time I requested the dlls)

V13.3.3 and also V13.4.0 
is a lot faster the first time getting those dlls (about 120 ms per dll), after some time the pdf is generated and i can assert the text inside the pdf. But the pdf is not shown on screen (not a very big problem for now).  But, the next time I run this scenario I dont see any calls getting dlls and it takes forever loading the pdf (the only call which has something to do with wasm is a get on js/wasm/sharedworker.js resulting in a 200 response). I can not assert on the pdf its src since the src is not available. Also the pdf is not shown in the browser.

Maybe @ryanthemanuel can help ? fixed a lot of stuff regarding shared workers and also #28054,

**Comment by MelvinBaaijAviva** [comment]
> @MelvinBaaijAviva Are you using an object tag for the PDF? This issue has been identified where we're working on a fix. Can't tell if that would address your issue at this point.

The pdf is shown using an embed tag

**Comment by ryanthemanuel** [comment]
@MelvinBaaijAviva this will be fixed along with https://github.com/cypress-io/cypress/pull/28229
