### ISSUE TITLE
How to ignore "Error: The adapter rejected the commit because it was invalid"

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#2817]
### Is this a Feature or Bug?

Hi all, while testing a ember web application if server gives code 422 cypress gives error and i want to ignore it. Because application is already ignore it and go to its way.
Error: The adapter rejected the commit because it was invalid
<img width="688" alt="screen shot 2018-11-21 at 11 22 47" src="https://user-images.githubusercontent.com/38225108/48828058-d4b41000-ed7f-11e8-830b-557bc1aa7a4f.png">

### Versions
Cypress 3.1.0
Electron 59

**Comment by jennifer-shehane** [comment]
Have you looked at trying to catch uncaught exceptions? Docs here: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by kutlaykural** [comment]
Hey, is there any update about it?

**Comment by kutlaykural** [comment]
as far as i understood your shared link if
```js
Cypress.on('uncaught:exception', (err, runnable) => {
  return false
})
```
does not work for an error (especially for status code 422) we can use this;
```js
Cypress.on('fail', (error, runnable) => {
    
    if (error.message.includes('The adapter rejected the commit because it was invalid')) 
       return false
    else
        throw error
})
```
 am i right?

**Comment by jennifer-shehane** [comment]
This workaround looks correct, but I would just try it and see.

As far as addressing the initial error, we would need a reproducible example to look further into it, so we'll have to close this issue if none can be provided.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by sajjadhossain** [comment]
I am experiencing this now @jennifer-shehane. 

Steps to reproduce:

**Comment by jennifer-shehane** [comment]
@sajjadhossain The error you printed is `SyntaxError: Unexpected token < in JSON at position 1`, this does not look related to this original issue. 

Have you looked at trying to catch uncaught exceptions? Docs here: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by saurabhp-onit** [comment]
```
Cypress.on('fail', (error, runnable) => {
    
    if (error.message.includes('The adapter rejected the commit because it was invalid')) 
       return false
    else
        throw error
})
```

isn't working.
