### ISSUE TITLE
Ability to hide steps in Test Runner during test execution

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#28176]
### What would you like?

To have ability to hide steps in Test Runner, during test execution.

### Why is this needed?

Sometimes, viewing steps under execution is not required, especially on small/split screens. It will be usefull to have ability to hide steps during test exection, leaving only view for application under test.

**Comment by jennifer-shehane** [comment]
You can do this by passing `--no-runner-ui` via the CLi. https://docs.cypress.io/guides/guides/command-line#cypress-run-no-runner-ui
