### ISSUE TITLE
How to avoid relaunch of browser in between each BDD file execution?

### ISSUE THREAD

**Issue by ketulsha** [cypress-io/cypress#28186]
### Current behavior

We have multiple cases in form of BDD (cucumber feature files). Every time the Cypress runs tests from one feature file to another one, it relaunches the runner.
Relaunching clears all data and starts from clean state. The application under tests uses browser local storage to store some identities and it is not retained in next feature file execution. I tried cy.session() also but didn't work.

Is there any way where I can run all the scenarios from all /multiple feature file without relaunching the test runner in pipeline?

Please note, the test cases are in form of BDD (cucumber tests and not spec.js file).

### Desired behavior

Need any setting / way where we can avoid relaunching the test runner after one feature file tests are over. OR open in new tab instead of relaunching runner.

Relaunching clears all data and starts from clean state

### Test code to reproduce

<img width="914" alt="Screenshot 2023-10-31 at 4 20 58 PM" src="https://github.com/cypress-io/cypress/assets/101400542/85d219f6-614a-4300-b42c-7a1db9c16142">

### Cypress Version

13.4.0

### Node version

v18.18.

### Operating System

MacOS

**Comment by jennifer-shehane** [comment]
@ketulsha No, there's no built in way to carry over the state from one file to another. The entire browser relaunches, the old browser is killed so there is no way to get it. You could open a feature request to have cy.session state maintained across test files, but it currently does not do that.
