### ISSUE TITLE
Cypress.Cookies.preserveOnce no longer works

### ISSUE THREAD

**Issue by robert-smith135** [cypress-io/cypress#2819]
Using chrome 70

### Current behaviour:
When using Cypress.Cookies.preserveOnce() it should preserve the named cookie between visits but after each cy.visit() all cookies are reset.

### Desired behaviour:
The named cookie passed to preserveOnce() will persist between tests

### Steps to reproduce:
describe('test describe', () => {
    context('test context', () => {
        beforeEach(() => {
            Cypress.Cookies.debug(true, { verbose: false });
            Cypress.Cookies.preserveOnce('locserv');
        });

        it('One', () => {
            cy.visit('www.google.com');
            cy.setCookie('locserv', 'locservcookie');
            cy.wait(1000)
        });

        it('Two', () => {
            cy.visit('www.google.com');
            cy.getCookies();
            cy.wait(10000);
        });
    });
});

The get cookies call in the second test doesn't show the 'locserv' cookie in the getCookies call. Because I called Cypress.Cookies.preserveOnce('locserv'); in the before each block I expected this cookie to persist.

I have also tried setting the global cypress config:

Cypress.Cookies.defaults({
    whitelist: function(cookie) {
        return true
    }
});

Cypress.Cookies.defaults({
    whitelist: 'locserv'
  })

Unless I'm missing something, according to the documentation either these methods should work. 

### Versions
The versions I tried were: 3.1.0, 3.0.1, 2.1.0

**Comment by jennifer-shehane** [comment]
@robert-smith135 Did you find a solution you could share?

**Comment by scaryguy** [comment]
I thought I had the same problem. But after some more digging I realized that the feature was working _but_ I had forgotten to add another cookie to the list of the cookies that I had to preserve. So it was my bad.

If you're here; make sure that you have _**all**_ cookies listen within the `preserveOnce` function arguments.
