### ISSUE TITLE
on('fail') not reliably continuing test after failure

### ISSUE THREAD

**Issue by sebastianclavijo** [cypress-io/cypress#28218]
### Current behavior

The cy.on('fail') code below should catch the 2 failed assertions (and print in the console, and and finalize the test as passed.
However the test fails/stops in the first failed assertion, and even do not enter in the cy.on('fail') function:

```js
/// <reference types="Cypress" />
describe('suite', () => {
    it('test', () => {
        cy.on('fail', (err,runnable) => {
            console.log("*****Error")
            console.log(err)
            return false
        })
        cy.visit('https://google.com')
        cy.get('[data-cy]') // Assertion fails (but should continue testing)
        cy.wrap(false).should('be.false') // Assertion pass
        cy.wrap(false).should('be.true') // Assertion fails (but should continue testing)
    });
});

```

BTW: I also tried Cypress.on('fail') within the describe outside de test and in the e2e.js with no success.

![image](https://github.com/cypress-io/cypress/assets/3597525/a2952515-6939-449e-9468-28952e9cfc0c)

### Test code to reproduce
```js
/// <reference types="Cypress" />
describe('suite', () => {
    it('test', () => {
        cy.on('fail', (err,runnable) => {
            console.log("*****Error")
            console.log(err)
            return false
        })
        cy.visit('https://google.com')
        cy.get('[data-cy]') // Assertion fails (but should continue testing)
        cy.wrap(false).should('be.false') // Assertion pass
        cy.wrap(false).should('be.true') // Assertion fails (but should continue testing)
    });
});
```
### Cypress Version

13.4.0

### Node version

18.14.2.

### Operating System

Windows 10

**Comment by csvan** [comment]
"Title" should be a short text describing the issue, not your professional title.

**Comment by jennifer-shehane** [comment]
Yah I'm seeing some different, but similar behavior when I run this.

This code does not run the cy.wrap commands. I feel like this may be expected, but maybe poorly documented in our docs. 
```js
/// <reference types="Cypress" />
describe('suite', () => {
    it('test', () => {
        cy.on('fail', (err,runnable) => {
            console.log("*****Error")
            console.log(err)
            return false
        })
        cy.visit('https://google.com')
        cy.get('[data-cy]') // Assertion fails (but should continue testing)
        cy.wrap(false).should('be.false') // Does not run at all
        cy.wrap(false).should('be.true') 
    });
});
```

![Screen Shot 2023-11-02 at 9 21 50 AM](https://github.com/cypress-io/cypress/assets/1271364/5c07275c-d0dd-458a-aed2-f929f0761bd8)

**Comment by MikeMcC399** [comment]
According to the comments in 

https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__errors/cypress/e2e/test-fails.cy.js 

this would be expected:

```js
    cy.visit('index.html')
    cy.get('button#does-not-exist', { timeout: 1000 }).click()

    // note: after the cy.get fails and the test fails
    // the remaining commands are NOT executed
    // thus this failing assertion never gets to run
    cy.wrap(false).should('be.true')
```

(Issue is also posted to https://discord.com/channels/755913899261296641/1168655650994270339/1168655650994270339.)

**Comment by jennifer-shehane** [comment]
Opened a PR to docs to clarify this: https://github.com/cypress-io/cypress-documentation/pull/5554

**Comment by sebastianclavijo** [comment]
There is a pretty good article https://www.lambdatest.com/learning-hub/exception-handling-in-cypress#fail describing the expected result when catching an error with cy.on('fail').
As you can see in the screenshots of the article, the tests finish gracefully as not failed in green (what is in red is only the assertion that failed).

![image](https://github.com/cypress-io/cypress/assets/3597525/326e8590-7655-4dfb-8750-07e3446934e1)

However in the screenshots of my sample, the test fails (in red), and even more in the screenshot you can see in the console that it never enters in the handler function associated to the cy.on('fail'). So independently if the rest of assertions are not run, the event is not properly handled (even more, if the code is aborted, what's the point of capturing the 'fail' event?).

![image](https://github.com/cypress-io/cypress/assets/3597525/be89c305-b1f8-4bcb-86de-7744146f0a9c)

Is it missing some configuration option somewhere, to get the 'fail' event captured?
