### ISSUE TITLE
Spurious Google translate modal appearing when running headless tests

### ISSUE THREAD

**Issue by panstromek** [cypress-io/cypress#28225]
### Description

When I run tests with `npx cypress run --browser chrome`, a small google translate modal popups somewhere on the screen

### URL of Issue(s)

No idea how to do that in web environment

### Steps to replicate

1. Run `npx cypress run --browser chrome` with some tests that use browser
2. wait

### Browser

Chrome 1

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

Here's how it looks like. Notice the little popup on top.
The modal disappears if I alt+tab somewhere else.

![image](https://github.com/cypress-io/cypress-documentation/assets/25121817/c94b45b7-4499-4138-acb2-37bd93a96221)

Cypress 13, Windows 10

**Comment by jennifer-shehane** [comment]
We should be passing `--disable-features=Translate` to ensure this doesn't pop up.
