### ISSUE TITLE
SVG errors are emitted when hovering over steps

### ISSUE THREAD

**Issue by joelzimmer** [cypress-io/cypress#2822]
### Current behavior:

Cypress currently emits an `<Error: <svg> attribute height: A negative value is not valid. ("-45")` when you hover over the pin icon in the sidebar, see:
![screen recording 2018-11-21 at 01 24 pm](https://user-images.githubusercontent.com/156871/48861147-e81ba700-ed90-11e8-9dab-a38ca019c2f3.gif)

### Desired behavior:

Don't emit an error when hovering over step in the sidebar

### Steps to reproduce:

Run a test using Electron, and wait for it to complete, hover over the steps with the Developer Console open and see the errors come flying through

### Versions

Cypress: 3.1.2
Operation System: Mac OS High Sierra
Browser: Electron

**Comment by kylerob** [comment]
Is anyone able to reproduce this in 3.4.1?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
