### ISSUE TITLE
Protocol: [Performance] Add a progress indicator for uploads

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#28239]
If protocol uploads take a long time for files, this could cause CI systems to time out. A possible solution to this would be to provide an iterative update to standard out (e.g. dots or something) that at least indicate that progress is being made and triggering CI not to time out

**Comment by cacieprins** [comment]
In considering what would benefit noninteractive shells, like in CI, while also allowing for effective masking for the console output in our system test snapshots, the formatting for the upload report will likely have to change dramatically. Currently, we print a list of artifacts that were uploaded, along with their filesize and with https://github.com/cypress-io/cypress/pull/28226, the duration of the upload.

I'm proposing the following output formatting:

```
(Uploading Cloud Artifacts)

- Video - Nothing to upload
- Screenshot - [filepath] [filesize]
- Test Replay - [filesize]

Uploading 2 files ([total filesize])
Progress: . . . . . [print a dot every 15 seconds]
Screenshot (1/1) complete 
Progress: . . . . .
Test Replay complete

Uploaded 2 files in [duration]
```

In cases of failure:

```
(Uploading Cloud Artifacts)

- Video - Nothing to upload
- Screenshot - [filepath] [filesize]
- Test Replay - [filesize]

Uploading 2 files ([total filesize])
Progress: . . . . . [print a dot every 15 seconds]
Screenshot [filepath] (1/1) failed after [duration]:
  [error]
Progress: . . . . .
Test Replay complete after [duration]

Uploaded 1 file in [duration]. 1 file upload failed.
```

These dots would service as an activity indicator, rather than a full progress indicator.  An ASCII spinning indicator would not work, due to noninteractive shell use.

**Comment by jennifer-shehane** [comment]
Maybe clean it up a bit.

```
(Uploading Cloud Artifacts)

- Video - Nothing to upload
- Screenshot - [filepath] [filesize]
- Test Replay - [filesize]

Uploading 1 Screenshot ([total filesize]) . . . . . [print a dot every 15 seconds]
Screenshot (1/1) uploaded in [duration]

Uploading Test Replay ([total filesize]) . . . . . [print a dot every 15 seconds]
Test Replay uploaded in [duration]
```

**Comment by cacieprins** [comment]
Uploads currently happen in parallel rather than serial - we could display in that way, but it would necessitate making the uploads serial instead.

**Comment by jennifer-shehane** [comment]
@cacieprins What would be the implications of printing all of the upload results once all of the artifacts are done? Is that possible to do? Or way more complicated?

```
(Uploading Cloud Artifacts). . . . . [print a dot every 15 seconds]

- Video - 1 kB /XXX/XXX/XXX/cypress/videos/record_error.cy.js.mp4
- Screenshot - 1 kB 2/2 /XXX/XXX/XXX/cypress/screenshots/record_fail.cy.js/record fails -- fails 1 -- before each hook (failed).png
- Test Replay - 432 kb

(Uploaded Cloud Artifacts)

- Video - Uploaded 1 kB 1/1 /XXX/XXX/XXX/cypress/videos/record_error.cy.js.mp4 in [duration]
- Screenshot - Uploaded 1 kB 2/2 /XXX/XXX/XXX/cypress/screenshots/record_fail.cy.js/record fails -- fails 1 -- before each hook (failed).png in [duration]
- Test Replay - Uploaded 432 kb in [duration]
```

**Comment by cacieprins** [comment]
Completely possible, and actually a little easier. We'd just need the activity indicator between the (Uploading) and (Uploaded) message blocks, to accommodate noninteractive terminals

**Comment by jennifer-shehane** [comment]
Oh right. What is the intention of listing all the stuff we're uploading before it's uploaded? I guess there could be failures somewhere? Seems like we're listing info twice...for what benefit?

**Comment by jennifer-shehane** [comment]
Breaking it up

```
(Cloud Artifacts to Upload)

- Video - 1 kB /XXX/XXX/XXX/cypress/videos/record_error.cy.js.mp4
- Screenshot - 1 kB 2/2 /XXX/XXX/XXX/cypress/screenshots/record_fail.cy.js/record fails -- fails 1 -- before each hook (failed).png
- Test Replay - 432 kb

Uploading Cloud Artifacts. . . . . [print a dot every 15 seconds]

(Uploaded Cloud Artifacts)

- Video - Uploaded 1 kB 1/1 /XXX/XXX/XXX/cypress/videos/record_error.cy.js.mp4 in [duration]
- Screenshot - Uploaded 1 kB 2/2 /XXX/XXX/XXX/cypress/screenshots/record_fail.cy.js/record fails -- fails 1 -- before each hook (failed).png in [duration]
- Test Replay - Uploaded 432 kb in [duration]
```
