### ISSUE TITLE
UI Tweak - Latest Runs refresh

### ISSUE THREAD

**Issue by zaq42** [cypress-io/cypress#28231]
### What would you like?

Refresh the Latest Runs page by clicking on Latest Runs...
Clicking Latest Runs should show the latest runs, regardless of where you start.

Alternatively (or better), the auto-update reflected in the Last Updated timestamp should refresh the runs list to show new runs.

![image](https://github.com/cypress-io/cypress/assets/24503523/e35956b1-4994-4dfb-9668-c61459aa64b0)

### Why is this needed?

If I'm on any other page, such as a specific run, 'Latest Runs' in the sidebar is my habitual action to get back to, well, Latest Runs.

If I'm already on that page and a new run has started:
1. the icon just above that link (next to the project name) will show a spinner,
2. the message at the top right of the page shows: 'Last updated' with a timestamp that is usually only a few seconds ago and a tiny button to 'Refresh runs'

It seems that the automatic update indicated by the 'last updated' updates the status of runs that are already visible, but does not update the page to show new runs.

By the time, I habitually click latest runs (often after noticing the spinner just above it), and eventually realise that it does nothing, I then have to find the tiny click target on the other side of the large page... it's often quicker to leave the page and come back (e.g. click Branches, then Latest Runs)

**Comment by jennifer-shehane** [comment]
@zaq42 Thanks for the suggestion. I've forwarded this to our Cloud team.
