### ISSUE TITLE
Empty href attr gets added to a tags missing href

### ISSUE THREAD

**Issue by KantiKuijk** [cypress-io/cypress#28241]
### Current behavior

When a page is visited that has an anchor tag (`<a></a>`) without href at all, every e2e browser tried adds an empty href attribute, even when the same browser wouldn't do that.

### Desired behavior

In this situation, cypress should act the same as the browser would, keeping the anchor tag as in the served html. It shouldn't add an empty href attribute.

### Test code to reproduce

when `page` is the url to a html page containing at least 1 anchor tag without an href attribute (not even an empty one), the following:
```
cy.visit(page);
cy.get("a:not([href])").should("not.exist")
```
should result in a failed test, but it succeeds.

### Cypress Version

13.4.0

### Node version

v18.18.0

### Operating System

macOS Sonoma 14.0

**Comment by jennifer-shehane** [comment]
@KantiKuijk Please provide a reproducible example. Cypress doesn't have any code that would add href tags to the application under test. 

```js
  it('failes', () => {
    cy.visit('index.html');
    cy.get("a:not([href])").should("not.exist")
  })
```

```html
<body>
  <div>
    Main Page
  </div>
  <a>Link</a>
</body>
```

![Screen Shot 2023-11-03 at 3 35 19 PM](https://github.com/cypress-io/cypress/assets/1271364/5a508ccd-36ee-4c3e-822b-8311784032f7)

**Comment by KantiKuijk** [comment]
Well, I guess good practices are there for a reason, even when they take more time.
In the process of making a separate minimal repo made me find a bug on my end.
Thus I will close this issue as it wasn't a cypress issue at all.
I am sorry for wasting anyone's time, will do better in the future!
