### ISSUE TITLE
Cypress cy.visit fails with Error: ESOCKETTIMEDOUT error, but I can access website fine outside of Cypress

### ISSUE THREAD

**Issue by miken-hg5** [cypress-io/cypress#28246]
### Current behavior

1. I can browse website [Error: https://www.cmegroup.com in normal brwoser no problem
2. cy.visit('https://www.cmegroup.com/') fails with ESOCKETTIMEDOUT
3. Have tried adding additional options such as 
      retryOnNetworkFailure: true,
      retryOnStatusCodeFailure: true
4. I have suspicions that this might be a HTTP/2 Protocol error

### Desired behavior

cy.visit('https://www.cmegroup.com/') should not fail with ESOCKETTIMEDOUT

### Test code to reproduce
```js
describe('template spec', () => 
{
  it('passes', () => 
  {
    cy.visit('https://www.cmegroup.com')
  })
})
```

### Cypress Version

12.17.1

### Node version

18.17.0

### Operating System

Windows 11 and Windows 2016 Serevr

**Comment by miken-hg5** [comment]
Amended a few typos

**Comment by miken-hg5** [comment]
IF I access the URL in the browser and run Dev Tools ... Network ... I don't see anything unusual in there. _the page opens fine in a browser that is not under automation control_. I also tried running the same URL lookup in Puppeteer - as it also node based. That fails too with a more explicit error than ESOCKETTIMEDOUT. Puppeteer errors with net:**:ERR_HTTP2_PROTOCOL_ERROR**

**Comment by miken-hg5** [comment]
Stack trace

at <unknown> (http://localhost:60182/__cypress/runner/cypress_runner.js:147833:82)
    at visitFailedByErr (http://localhost:60182/__cypress/runner/cypress_runner.js:147225:12)
    at <unknown> (http://localhost:60182/__cypress/runner/cypress_runner.js:147832:11)
From previous event:
    at visit (http://localhost:60182/__cypress/runner/cypress_runner.js:147798:17)
    at Context.visit (http://localhost:60182/__cypress/runner/cypress_runner.js:147849:14)
    at wrapped (http://localhost:60182/__cypress/runner/cypress_runner.js:160808:43)
From Your Spec Code:
    at Context.eval ([webpack:///./cypress/e2e/cme_grains_spec.cy.js:5:7](http://localhost:60182/__/#))
From Node.js Internals:
  Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (<embedded>:1969:100506)
      at Object.onceWrapper (node:events:641:28)
      at ClientRequest.emit (node:events:527:28)
      at TLSSocket.emitRequestTimeout (node:_http_client:771:9)
      at Object.onceWrapper (node:events:641:28)
      at TLSSocket.emit (node:events:539:35)
      at Socket._onTimeout (node:net:516:8)
      at listOnTimeout (node:internal/timers:559:17)
      at process.processTimers (node:internal/timers:502

**Comment by MikeMcC399** [comment]
@miken-hg5 

As mentioned on https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test if https://www.cmegroup.com is a site that you don't control, then:

- They may detect you are a script and block your access.
- They may have security features enabled which prevent Cypress from working.

If on the other hand you are employed by `cmegroup.com` then you should contact their webmaster and check on the security protection against Cypress.

See also [Visiting External Sites](https://docs.cypress.io/guides/references/best-practices#Visiting-External-Sites) which may apply to your case.

**Comment by DobQA** [comment]
This is a known bug thats been logged before, we are also waiting for a fix. 

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: ESOCKETTIMEDOUT

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

It happens at random times on our test environment that has multiple sites. We running CircleCI tests and many fail because of this, we then manually have to re-run failed tests, at this point some of the ones that had this issue will pass, its more of annoyance right now. It seems to happen less on headed mode which is weird. Headless it happens frequently.

**Comment by zeyupan888** [comment]
following, having the same issue.

**Comment by zeyupan888** [comment]
I tried to debug by 
```
curl localhost:8081


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8081: Connection refused

```

looks like the server in gitlab is not responding.

**Comment by zeyupan888** [comment]
any update?
