### ISSUE TITLE
Shared Workers no longer work after page reload

### ISSUE THREAD

**Issue by ebbejan** [cypress-io/cypress#28248]
### Current behavior

Shared Workers no longer work in E2E tests after a cy.reload().

Steps to reproduce:
1. Visit page with shared worker
2. Reload page

The Shared Worker works correctly when the page is initially loaded. The error only occurs after the reload.

Only the latest Chrome versions (tested with 119) seem to be affected. The problem does not occur in Firefox 119.

### Desired behavior

Shared workers continue to function correctly in E2E tests even after a page reload.

### Test code to reproduce

Minimal example: https://github.com/ebbejan/cypress-shared-worker

### Cypress Version

13.4.0

### Node version

20.9.0

### Operating System

Windows 11 Pro, Version: 22H2, Build: 22621.2428

**Comment by jennifer-shehane** [comment]
@ebbejan Thank you for the reproducible example. I can see the test you provided is failing starting in 13.3.3. I'd suggest downgrading to 13.3.2 for the time being while we investigate.

**Comment by ryanthemanuel** [comment]
@ebbejan the fix on https://github.com/cypress-io/cypress/pull/28254 should resolve your issue. We are hoping to have that released in the next few days.
