### ISSUE TITLE
Create Use Facing Video (crop the test framework info)

### ISSUE THREAD

**Issue by wxtim** [cypress-io/cypress#28250]
### What would you like?

An option to produce videos of the tests being run on the app without the test framework information appearing.

### Why is this needed?

I use Cypress screenshots as part of a workflow which keeps documentation for my project up-to-date. Don't you hate it when the GUI screenshot is ancient?

I would like to do the same with videos.

**Comment by jennifer-shehane** [comment]
@wxtim You can do this by passing [`--no-runner-ui`](https://docs.cypress.io/guides/guides/command-line#cypress-run-no-runner-ui), which is a newer feature.

**Comment by wxtim** [comment]
> @wxtim You can do this by passing [`--no-runner-ui`](https://docs.cypress.io/guides/guides/command-line#cypress-run-no-runner-ui), which is a newer feature.

That;s brilliant @jennifer-shehane  - thanks for sharing!
