### ISSUE TITLE
Bug after click event

### ISSUE THREAD

**Issue by mistercookie** [cypress-io/cypress#2826]
### Current behavior:
I am testing one of my websites in production.  And want to test product is added to the cart.
after i click button add to cart I am getting strange POST request error and test stops.

![screenshot from 2018-11-22 16-40-54](https://user-images.githubusercontent.com/15631655/48909306-8f720a00-ee75-11e8-8e5a-e53912a1ba21.png)

### Versions

latest cypress on vue in linux ubuntu 18.04

**Comment by jennifer-shehane** [comment]
Can anyone provide a way to reproduce this?

**Comment by mistercookie** [comment]
so I am testing this page and want just first product add to Cart and if I do in browser everything looks okay but in test it stucks after click event
the page: https://www.intersport.no/

**Comment by jennifer-shehane** [comment]
Please provide the test code you have already tried to run that is throwing this error. This will get your issue addressed quicker as we cannot write the test suite from scratch to reproduce this.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
