### ISSUE TITLE
Get an error message when running a cypress run in the cloud

### ISSUE THREAD

**Issue by MiriamStokka** [cypress-io/cypress#28260]
### Current behavior

I am running a github action to start a run in cypress cloud. I then get this error message.
```
Cypress Version: 13.3.3 (stable)
System Platform: linux (Ubuntu - 22.04)
System Memory: 16.8 GB free 15.6 GB

DevTools listening on ws://127.0.0.1:35[81](https://github.com/elkjopnordic/ecommerce-frontend-e2e-tests/actions/runs/6784657201/job/18441400219#step:9:82)5/devtools/browser/36bf9098-c69f-4cc1-a321-5db9fe036729
[2756:1107/124547.989336:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type: 
@cypress/grep: filtering using tag(s) "seonavigation plp pdp cms ratings marketplace cart delivery checkout mypage payment auth subscription promotion popup service external alwaysruns"
@cypress/grep: will omit filtered tests
You passed the --parallel flag, but this run group was originally created without the --parallel flag.

The existing run is: undefined

The --group flag you passed was: e2e test default
The --ciBuildId flag you passed was: e2e test default

You can not use the --parallel flag with this group.

https://on.cypress.io/parallel-disallowed
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```
The problem started randomly for both me and my colleagues yesterday. Today it has happened more frequently. Some of my colleagues can run tests from time to time, but it often fails, but for me, for example, it is currently not possible to run anything. We have not made any changes to the structure or code before this error appeared. Do you know the problem?

It was not possible to post pictures here, maybe I can send a print screen of the error message by email or something?

### Desired behavior

I lead the e2e testing time for Elkjøp. We have an extensive cypress project where we test all four of our websites using cypress. I expected to start the test in github action, and see it run in cypress cloud.

### Test code to reproduce

It's not relevant to add code here because we have used the previous code for a year without any problems. No change has been added. 

### Cypress Version

13.3.0

### Node version

16.17.1 

### Operating System

Lenovo

### Debug Logs

```shell
It works to run the test locally. Therefore i don't have any debug log.
```

**Comment by jennifer-shehane** [comment]
@MiriamStokka I haven't seen this error before honestly with `The existing run is: undefined`. Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and email the logs over to support@cypress.io for assistance debugging?
