### ISSUE TITLE
The font-size doesn't change when we set a different resolution using `viewport()`

### ISSUE THREAD

**Issue by nenadtripunovic85** [cypress-io/cypress#28273]
### Current behavior

When we run Cypress automation tests, the font size doesn't change when we set a different resolution (e.g., for Tablet) using the viewport() option. However, if we run the tests and then press keyboard shortcuts 'Ctrl+Shift+i' and 'Ctrl+Shift+m' during the execution, it will recognize the window size, and the tests will pass. I also tried to implement the following commands in Cypress tests:
```
    cy.viewport('ipad-mini');
    cy.get('body').focus().type('{ctrl}{shift}i', { release: true });
    cy.wait(5000);
    cy.get('body').focus().type('{ctrl}{shift}m', { release: true });
```
But, these commands didn't work as well. Here is a link to a video that describes the behavior: https://app.screencast.com/6p2VLuKfoB1QX?conversation=Bq02GSEotu4yKNCxj1iMez
![2023-11-08_13-16-01](https://github.com/cypress-io/cypress/assets/105376154/832062f5-e3ec-4604-ad00-b528a73ea357)

### Desired behavior

Judging by the Cypress docs, the font-size should also change in accordance with the changes of the entire page.

### Test code to reproduce

```
    cy.viewport('ipad-mini');
    cy.get('body').focus().type('{ctrl}{shift}i', { release: true });
    cy.wait(5000);
    cy.get('body').focus().type('{ctrl}{shift}m', { release: true });
```

### Cypress Version

v12.17.1

### Node version

v16.15.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
It's weird, watching the video. Maybe there's some kind of event we're not triggering in the resize of the viewport, so that when you open devTools it triggers the window resize or something that makes it shift. I'm not sure about this one. Will leave it open as a bug.
