### ISSUE TITLE
Cypress programming don't work with windows 10

### ISSUE THREAD

**Issue by JimmyD007** [cypress-io/cypress#28281]
### Current behavior

I used the command line cyfwstorprog.exe -vid:04B4 -pid:0053 -delpar and an error comes back "Couldn't open the Usb Device. Invalid VID, PID. but works on windows 7 machine.

### Desired behavior

clear the partitions

### Test code to reproduce

cyfwstorprog.exe -vid:04B4 -pid:0053 -delpar

### Cypress Version

CYUSB2024-BZX

### Node version

CYUSB2024-BZX

### Operating System

windows 10 pro

### Debug Logs

```shell
"Couldn't open the Usb Device. Invalid VID, PID.
```

### Other

"Couldn't open the Usb Device. Invalid VID, PID.

**Comment by MikeMcC399** [comment]
@JimmyD007 

Your issue looks like it involves an unrelated product named "Cypress" from Infineon.

No guarantees, but you might be able to find help in

https://community.infineon.com/

instead.

**Comment by JimmyD007** [comment]
has Cypress updated their cyfwstorprog.exe since Windows-7 ?? It appears like the part is being programmed, the output of the application even says SUCCESS. However, when I cycle power, it appears as if it was never programmed. what is different between windows 7 and 10 ? am I missing some type of driver (USB or other) that needs to be installed? It has been about a month and I still cannot program the Cypress (CYUSB2024 or CTUSB3025).  This project has fallen behind! Please Help!

**Comment by MikeMcC399** [comment]
@JimmyD007 

You are in the wrong place with your problem. 

Have you tried asking Infineon?

You will need to take your problem to the correct vendor. Infineon sells USB technology. See https://www.infineon.com/cms/en/product/universal-serial-bus/ and
https://community.infineon.com/t5/USB-superspeed-peripherals/bd-p/usb-superspeed-peripherals
