### ISSUE TITLE
window.navigator.clipboard cannot use on cypress 13.5

### ISSUE THREAD

**Issue by panduanNew2534** [cypress-io/cypress#28291]
### Current behavior

I use this one on Cypress script and it does not work anymore with the error below 

<img width="1075" alt="image" src="https://github.com/cypress-io/cypress/assets/146902009/0b27acc0-89e5-4c92-87a4-02c39be6be22">

### Test code to reproduce

>                 cy.window().then(win => {
>                     cy.stub(win.navigator.clipboard, 'writeText').as('copy');
>                     cy.get(selector.hamburgerMenuWalletCopy).should('be.visible').click()
>                     cy.get('@copy').should('have.been.calledOnce').then((spy: unknown) => {
>                         expect((spy as SinonSpy).lastCall.args[0]).not.equal('');
>                         expect((spy as SinonSpy).lastCall.args[0]).not.equal(data.miniApp.orgQa01.walletAddressId);
>                     });
>                 })

### Cypress Version

13.5.0

### Node version

v21.1.0

### Operating System

12.1

**Comment by yann-combarnous** [comment]
Same here, using cypress 13.5.0. Last known version to work: 13.3.0.

**Comment by panduanNew2534** [comment]
> Same here, using cypress 13.5.0. Last known version to work: 13.3.0.

Do you find any solution for solving this?

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this with a simple example. Can you provide an example that recreates this?

```js
it("test", () => {
    cy.visit('index.html')
    cy.window().then(win => {
        cy.stub(win.navigator.clipboard, 'writeText').as('copy');
        cy.get('button').click()
        cy.get('@copy').should('have.been.calledOnce').then((spy) => {
            expect((spy).lastCall.args[0]).equal('Hello World');
        });
    })
});
```

```html
<html>
<script>
  function myFunction() {
    // Get the text field
    var copyText = document.getElementById("myInput");

    // Select the text field
    copyText.select();
    copyText.setSelectionRange(0, 99999); // For mobile devices

    // Copy the text inside the text field
    navigator.clipboard.writeText(copyText.value);

    // Alert the copied text
    alert("Copied the text: " + copyText.value);
  }
  </script>
<body>
  
<!-- The text field -->
<input type="text" value="Hello World" id="myInput">

<!-- The button used to copy the text -->
<button onclick="myFunction()">Copy text</button>
</body>
</html>
```

![Screen Shot 2023-11-30 at 4 04 44 PM](https://github.com/cypress-io/cypress/assets/1271364/7ffced6c-4f3f-4ad2-b8f9-d6f3129ba077)

**Comment by panduanNew2534** [comment]
Apologies for the confusion earlier. Upon further investigation with the implementation team, it appears that they've discontinued the use of navigator.clipboard.writeText(copyText.value); in the code.
Instead, It is using library copy-text-to-clipboard which is causing the issue. I'm now exploring alternative commands to solve this.

Thank you a lot for investigating it.

**Comment by themarcel** [comment]
What is the final solution for this case then?

**Comment by eleanorlatus** [comment]
Is there a solution for this?

**Comment by jamesharv** [comment]
`navigator.clipboard.writeText` actually returns a Promise, so when you're stubbing it you probably want to do something like this:

```javascript
    cy.window().then((win) => {
      cy.stub(win.navigator.clipboard, "writeText").as("copy").resolves();
    });
```

Note `.resolves()` which makes the stub return a promise that resolves immediately.
