### ISSUE TITLE
Cypress 13.5.0 - can't go to website in new tab manually

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#28293]
### Current behavior

```
mkdir cypress-test
```

```
cd cypress-test
```

```
npm i cypress@13.5.0
```

```
npx cypress open --e2e --browser chrome
```

Click `Continue` button at `Configuration files` screen
Click on new tab button
Enter `https://google.com` in the URL bar

![image](https://github.com/cypress-io/cypress/assets/5721147/c8a37321-7aae-4101-88e0-18a69f6449dd)

### Test code to reproduce

// No code required to reproduce - See **Current behavior** section above

### Cypress Version

13.5.0

### Node version

v18.13.0

### Operating System

Microsoft Windows [Version 10.0.19045.3570]

**Comment by jennifer-shehane** [comment]
@alexsch01 Thanks for reporting so quickly. We're investigating to see what were intended changes vs not intended.

We are intending to change the behavior of opening new tabs in the near future, where some of that work went into 13.5.0. This is in efforts to offer better support for multiple tabs testing with a plugin we plan to release.

We never intended to support the use of new tabs within the Cypress browser - and encourage everyone to use their default browser instead. Opening new tabs could interfere with currently running tests. 

That being said, there is some strange behavior that I'll put here.

When I opened a new tab in the Cypress App, this popup showed up which I've never seen - I clicked ‘Keep It’ (*EDIT: This seems to have been pre-existing behavior that I haven't seen. I wonder if we could prevent this*)
![Screen Shot 2023-11-09 at 9 46 34 AM](https://github.com/cypress-io/cypress/assets/1271364/0ac05fdc-dba9-41d8-8622-cee408afffb4)

When I put in a URL to visit, it just doesn’t visit it and it downloads something into the downloads area.
![Screen Shot 2023-11-09 at 9 47 33 AM](https://github.com/cypress-io/cypress/assets/1271364/8a838fbf-819a-47f0-be6a-5bb47f15b1ca)

Additionally, on the new tab there are these logs in the terminal that continuously print.
<img width="1505" alt="Screen Shot 2023-11-09 at 9 48 28 AM" src="https://github.com/cypress-io/cypress/assets/1271364/e9cd5a98-e44c-4874-8a1a-60022889da66">

**Comment by Benoit-Vasseur** [comment]
It breaks our Lighthouse librairy :/. We launch Lighthouse through Cypress (to handle the login / cookies) and Lighthouse open a new tab to do its audit. Please go back to allow the new tab :) 

Edit : more related to this one : https://github.com/cypress-io/cypress/issues/28303
