### ISSUE TITLE
Sudden '3rd party library that is not supported' warning in Cypress v12

### ISSUE THREAD

**Issue by bettblake08** [cypress-io/cypress#28307]
### Current behavior

Our Jenkins CI builds have started failing since yesterday with the folllowing error

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

[572:1110/100351.479999:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 797: Permission denied (13)

DevTools listening on ws://127.0.0.1:44687/devtools/browser/b8138821-dacf-4c7b-94f2-15ae4841d099

[797:1110/100351.482328:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

We've detected that you're using a 3rd party library that is not supported by Cypress: -c

To continue running Cypress, please remove this library and its configuration files or contact us for help migrating.

https://on.cypress.io/unsupported-third-party-library?b=wqfDnQ%3D%3D
script returned exit code 1
```

I've taken a look at the communications from the Cypress team concerning the use of cypress-cloud and other 3rd party libs but this doesn't seem to apply with our project. I've confirmed that:
1. We're not using any of the unsupported Cypress libs
2. We don't have any setup for the Currents platform (`currents.config.js`)
3. We've checked & cleared cached Cypress binaries in our CI 

The following is the project's package deps:

```
...
"dependencies": {
    "@ant-design/icons": "^5.1.4",
    "@splitsoftware/splitio-react": "^1.8.3",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^12.6.0",
    "@types/lodash": "^4.14.195",
    "@types/node": "20.3.1",
    "@types/react": "18.2.12",
    "@types/react-dom": "18.2.5",
    "antd": "^5.9.3",
    "canvas-confetti": "^1.4.0",
    "classnames": "^2.3.1",
    "cookies": "^0.8.0",
    "dayjs": "^1.11.9",
    "eslint": "8.43.0",
    "eslint-config-next": "13.4.6",
    "http-proxy": "^1.18.1",
    "lodash": "^4.17.21",
    "luxon": "^2.0.1",
    "next": "13.4.6",
    "pino": "^8.16.1",
    "pretty-quick": "^3.1.1",
    "react": "18.2.0",
    "react-beautiful-dnd": "^13.1.0",
    "react-dom": "18.2.0",
    "react-i18next": "^13.0.0",
    "react-redux": "^7.2.4",
    "react-zoom-pan-pinch": "^2.1.3",
    "redux": "^4.1.1",
    "redux-thunk": "^2.3.0",
    "sharp": "^0.32.1",
    "typescript": "5.1.3"
  },
  "devDependencies": {
    "@ant-design/static-style-extract": "^1.0.2",
    "@cypress/code-coverage": "^3.10.0",
    "@cypress/snapshot": "^2.1.7",
    "@testing-library/cypress": "^9.0.0",
    "@types/cookies": "^0.7.9",
    "@types/http-proxy": "^1.17.13",
    "babel-plugin-istanbul": "^6.1.1",
    "cross-env": "^7.0.3",
    "cypress": "^12.17.4",
    "encoding": "^0.1.13",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.2",
    "husky": "^7.0.0",
    "prettier": "^2.8.8",
    "sass": "^1.63.4",
    "ts-node": "^10.9.1",
    "tslib": "^2.6.2"
  }
```

**Environment**

CI: Jenkins (Kubernetes)
Container Docker Image: `cypress/included:cypress-12.17.4-node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1`

### Desired behavior

Cypress component tests should run in Jenkins CI

### Test code to reproduce

N/A

### Cypress Version

12.17.4 & 12.9.0

### Node version

20.5.0

### Operating System

linux

**Comment by jennifer-shehane** [comment]
@bettblake08 Can you share Debug logs of your full run and your package.json file.

**Comment by moshe-shaham-lumigo** [comment]
This happened to me also, using cypress 12.17.3
We are using cypress-cloud, which is a blocked package, but I thought using version 12.17.3 shouldn't block it.

But anyway even after removing this package, I'm getting this error

**Comment by ghost** [comment]
We're getting the same error, we've never used cypress-cloud, and do pay for cypress.io.

These are our dependencies in package.json.
We're using the docker image `cypress/included:12.17.4`.

```
{
  "devDependencies": {
    "husky": "^4.3.8",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "serve": "^11.3.2"
  },
  "dependencies": {
    "cypress": "^12.17.4",
    "cypress-downloadfile": "^1.2.0",
    "cypress-file-upload": "5.0.8",
    "cypress-iframe": "^1.0.1",
    "cypress-wait-until": "^1.7.2",
    "faker": "^4.1.0",
    "fs": "0.0.1-security",
    "graphql": "^15.5.0",
    "mysql": "^2.18.1",
    "path": "^0.12.7",
    "pdf-parse": "^1.1.1"
  }
}
```

**Comment by jennifer-shehane** [comment]
@moshe-shaham-lumigo Ensure that you remove all configuration files also.

@cm3lindsay Can you share Debug logs of your full run?

**Comment by bettblake08** [comment]
@jennifer-shehane 

Here -> [logs.txt](https://github.com/cypress-io/cypress/files/13349302/logs.txt)

Concerning the package.json file, what I've shared is our package.json, minus the sensitive info

```
{
  "version": "2.0.0",
  "engines": {
    "node": ">=20.0.0"
  },
   ...
 "dependencies": {
    "@ant-design/icons": "^5.1.4",
    "@splitsoftware/splitio-react": "^1.8.3",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^12.6.0",
    "@types/lodash": "^4.14.195",
    "@types/node": "20.3.1",
    "@types/react": "18.2.12",
    "@types/react-dom": "18.2.5",
    "antd": "^5.9.3",
    "canvas-confetti": "^1.4.0",
    "classnames": "^2.3.1",
    "cookies": "^0.8.0",
    "dayjs": "^1.11.9",
    "eslint": "8.43.0",
    "eslint-config-next": "13.4.6",
    "http-proxy": "^1.18.1",
    "lodash": "^4.17.21",
    "luxon": "^2.0.1",
    "next": "13.4.6",
    "pino": "^8.16.1",
    "pretty-quick": "^3.1.1",
    "react": "18.2.0",
    "react-beautiful-dnd": "^13.1.0",
    "react-dom": "18.2.0",
    "react-i18next": "^13.0.0",
    "react-redux": "^7.2.4",
    "react-zoom-pan-pinch": "^2.1.3",
    "redux": "^4.1.1",
    "redux-thunk": "^2.3.0",
    "sharp": "^0.32.1",
    "typescript": "5.1.3"
  },
  "devDependencies": {
    "@ant-design/static-style-extract": "^1.0.2",
    "@cypress/code-coverage": "^3.10.0",
    "@cypress/snapshot": "^2.1.7",
    "@testing-library/cypress": "^9.0.0",
    "@types/cookies": "^0.7.9",
    "@types/http-proxy": "^1.17.13",
    "babel-plugin-istanbul": "^6.1.1",
    "cross-env": "^7.0.3",
    "cypress": "^12.17.4",
    "encoding": "^0.1.13",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.2",
    "husky": "^7.0.0",
    "prettier": "^2.8.8",
    "sass": "^1.63.4",
    "ts-node": "^10.9.1",
    "tslib": "^2.6.2"
  }
}

```

**Comment by jennifer-shehane** [comment]
@bettblake08 Thanks - could you provide your email or send an email to jennifer@cypress.io, so we can assist with a solution.

**Comment by gorlug** [comment]
We're also seeing this on our AWS CodePipeline run with version 12.7.4:

```
We've detected that you're using a 3rd party library that is not supported by Cypress: -c

To continue running Cypress, please remove this library and its configuration files or contact us for help migrating.

https://on.cypress.io/unsupported-third-party-library?b=wqfDnQ%3D%3D
```

We have never used any Cypress plugins in this project.

**Comment by ghost** [comment]
> @moshe-shaham-lumigo Ensure that you remove all configuration files also.
> 
> @cm3lindsay Can you share Debug logs of your full run?

[log.txt](https://github.com/cypress-io/cypress/files/13454940/log.txt)

edit: apologies, here is the debug log 
[debug.log](https://github.com/cypress-io/cypress/files/13508107/debug.log)

**Comment by askhanna-mdsol** [comment]
We are also experiencing the same issue, do we have a solution for this? 

Nove Version: v20.9.0
Cypress: 13.2.0

We are experiencing this while running test through Githhub workflows on image cypress/included:cypress-13.6.0-node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

Also I am new to cypress so I tried running it on a lower version 12.17 but was getting the same error

![Uploading Screenshot 2023-12-05 at 19.10.13.png…]()

[cypress_logs 2.pdf](https://github.com/cypress-io/cypress/files/13562296/cypress_logs.2.pdf)

**Comment by askhanna-mdsol** [comment]
> e've detected that you're using a 3rd party library that is not supported by Cypress: -c
> 
> To continue running Cypress, please remove this library and its configuration files or contact us for help migrating.

I got it resolved on my end, thanks.

**Comment by jennifer-shehane** [comment]
We'll close this issue as resolved. Largely our recommendations when seeing this error are:

- If you have a 3rd party installed that is listed in the error message, remove that library and all configuration / env vars related to it.
- If you have used `record: false` in some way, update your code to omit the `record` flag altogether.
