### ISSUE TITLE
Expose jQuery.expr and potentially other jQuery attributes & methods on Cypress.$

### ISSUE THREAD

**Issue by mwtorkowski** [cypress-io/cypress#2830]
While working on extending Cypress and hammer it to our needs (via custom commands, plugins, etc), I got stuck as I wanted to add a custom matcher to jQuery (via jQuery.expr - example here https://stackoverflow.com/a/18462522). Unfortunately, there's no way to do as only a handful of items are exposed (proxied) by cypress. This doesn't seem like a smart thing to do unless I'm missing something.

### Current behavior:

There's only a small subset of jQuery module exposed on the `Cypress.$`

### Desired behavior:

All jQuery properties & methods should be available for general use (`jQuery.expr` for instance). 

### Versions

Cypress 3.1.2, Ubuntu 18.04

**Comment by jennifer-shehane** [comment]
The jQuery version included in Cypress is version 2.2.4. See [this issue](https://github.com/cypress-io/cypress/issues/1215). Is it possible this has something to do with the lack of `jQuery.expr`?

**Comment by mwtorkowski** [comment]
It's not that it's lacking from jQuery object, but rather it's not being exposed on the `Cypress.$` object. To my understanding, you currently proxy only a handful of jQuery commands, not the module in its entirety.

See https://docs.cypress.io/api/utilities/$.html#Syntax -- there's even a comment there, stating "other proxied methods". So in my case, I can't use jQuery.expr for as long as Cypress hides majority of jQuery object power behind a facade.
