### ISSUE TITLE
Error occured while using cypress+BDD

### ISSUE THREAD

**Issue by wanghaomiao27** [cypress-io/cypress#28315]
### Current behavior

Hi there,

I am a chinese user of Cypress.Recently I have encountered a issue of Cypress.The cypress version is V13.4.0.The problem is that when I was trying to use cypress+BDD(cucumber),after I did some configurations and
run the feature file,it popued up below erros,I tried to search some solutions on internet,but there was no proper answers there.So I need your help here.Belows are some configurations and error steps.By the way,if you have
wechat,we can talk on wechat.
![1](https://github.com/cypress-io/cypress/assets/20040189/51e2e135-2594-4fc1-a259-695a0f5cb6f5)
![2](https://github.com/cypress-io/cypress/assets/20040189/e5291cc4-990f-4c25-b0b4-2ef643bd5154)
![3](https://github.com/cypress-io/cypress/assets/20040189/800ae68f-2765-49c4-b771-74b9825a71a0)
![4](https://github.com/cypress-io/cypress/assets/20040189/8da6c728-f69b-4839-809f-ecf884e8753e)
![5](https://github.com/cypress-io/cypress/assets/20040189/57071136-61d8-4b89-80fd-a9efebaa74cc)

### Desired behavior

cypress should execute the login.feature successfully

### Test code to reproduce

import {loginURL} from "../../testData/initHomePage.data";
import{Given,When,And,Then} from "cypress-cucumber-preprocessor/steps";

Given('User is at the login page',()=>{
    cy.initHomePage(loginURL[0].URL);
})

When('User enters username as {string} and password as {string}',(username,password)=>{
   cy.get('#login_username').type(username);
   cy.get('#login_password').type(password);
})

And('User clicks on login button',()=>{
    cy.get('button[type=button]').click()
})

Then('User is able to see the page"product center" ',()=>{
    cy.url().should('include','/aimarketer/usercenter/productcenter')
})

Feature: Login
  Scenario Outline: Login to test environment of http://wolf.test.datatist.cn/
    Given User is at the login page
    When User enters username as '<username>' and password as '<password>'
    And User clicks on login button
    Then  User is able to see the page"product center"
    Examples:
      | username                 | password |
      | analyzer@datatist.com    | abcd1234 |

### Cypress Version

13.4.0

### Node version

18.18.2

### Operating System

Windows 11 家庭中文版

### Other

pls contact me via wechat w232915796 or Email:wanghaomiao27@aliyun.com

**Comment by wanghaomiao27** [comment]
@thomassjogren @PavanGurram-DevOps [aurabhj89](https://github.com/Saurabhj89)  can you guys help?

**Comment by wanghaomiao27** [comment]
@Narretz  hello,buddy,could you please also take a look for above issue?

**Comment by krisodb** [comment]
For your dependencies only use @badeball/cypress-cucumber-preprocessor
--> Remove line 19 in your first screenshot.
In your test code just do: import { Then, When } from '@badeball/cypress-cucumber-preprocessor';

Ref: https://github.com/badeball/cypress-cucumber-preprocessor
