### ISSUE TITLE
How to get the token from the response header?

### ISSUE THREAD

**Issue by wanghaomiao27** [cypress-io/cypress#28317]
### Current behavior

Hi There,

Recently I have been researching and studying cypress for API test.There was one problem about how to get the token from the response header?I searched on internet,but it seems that there is no proper answers there.Below is a login request,but the token is generated on response header.See below picture.Could anyone tell me a detailed code snippets for getting the token from response header?
![image](https://github.com/cypress-io/cypress/assets/20040189/37663138-dc3f-4e57-954d-6425dff99c63)

![image](https://github.com/cypress-io/cypress/assets/20040189/63805f00-5ee0-4eab-82ab-d7febcbcd26c)

### Desired behavior

I can get the token from response header

### Test code to reproduce

context("接口依赖测试",function (){
    let responseBody  //定义接口返回结果为变量
    let responseToken //定义token变量，让下游使用
    it('登录请求',()=>{
        //cy.wrap(localStorage.getItem())
            cy.request({
                method:'POST',
                url:'http://wolf.test.datatist.cn/analyzer/analyzer/account/login.do',
                headers:{"Project-Id":"Jevf4ghaKT091r5E",
                        "Content-Type":"application/json"
                },
                failOnStatusCode:false,
                body:{
                    "password": "abcd1234",
                    "rememberMe": true,
                    "scope": "",
                    "username": "analyzer@datatist.com"
                }
            }).then((response)=>{
                expect(response.status).to.eq(200)
            }
    )

            });
    it('调用手动计算接口',()=>{
        cy.window().then((window)=>{
           cy.request({
              method:'POST',
              url:'http://wolf.test.datatist.cn/analyzer/tag/engine/calculateTaskManuallyByBatch.do',
               headers:{
                  "Project-Id":"Jevf4ghaKT091r5E",
                   "Content-Type":"application/json",
                   "Authorization":window.localStorage.getItem('token')
               },
               body:{
                  "taskId":"11528466840224",
                   "labelId":892
               }
           }).its('body')
               .as("resp")
               .then(function(){
                   //expect(this.resp.code).to.eq(0);
            })
        })
    })
        }
    )

### Cypress Version

13.4.0

### Node version

v18.18.2

### Operating System

Windows 11 家庭中文版

### Other

Pls reach me through wechat w232915796

**Comment by Narretz** [comment]
```
       cy.request({
       ....
       }).its('headers').should('equal', {myHeader: 'etc'})

      // or

       cy.request({
       ....
       }).then(response => {
         cy.wrap(response).its('headers').should('equal', {myHeader: 'etc'});
        // or

      expect(response.headers.myHeader).to.equal('etc')
})
```

BTW usage questions are better asked in https://github.com/cypress-io/cypress/discussions

**Comment by wanghaomiao27** [comment]
@Narretz thanks for your response.Let me try this.By the way,I have another question about cypress+BDD,could you also take a look?

**Comment by wanghaomiao27** [comment]
@Narretz Hi buddy,I just want to get the token from login request,and the token should be used for next request.So for this scenario,could you give me some code snippets?

**Comment by Narretz** [comment]
Well the token must be in the `response.headers` object and the snippet shows how to get the response. So 

```
       cy.request({
       ....
       }).then(response => {
           cy.request({
           headers: {
            myHeader: response.headers.myToken
           }
           })
```

I really have the feeling you're missing the basics here ... this stuff is definitely in the docs.
