### ISSUE TITLE
13.5.0 - GUI - Only Chrome - URL's opened in new tabs do not work

### ISSUE THREAD

**Issue by melibe23** [cypress-io/cypress#28312]
### Current behavior

Download a file and the url is not open in a new tab.

### Desired behavior

A URL should open in a new tab.
Not reproducible on 13.4.0
Only happens in latest version and Chrome.

### Test code to reproduce

https://github.com/cypress-io/cypress/assets/32499737/2e415815-f531-4a15-b63a-47ca83b2bded

### Cypress Version

13.5.0

### Node version

20

### Operating System

macOs Sonoma

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/28293
