### ISSUE TITLE
Does cypress support iframe record

### ISSUE THREAD

**Issue by wanghaomiao27** [cypress-io/cypress#28316]
### Current behavior

Hi there,

I am using the record function of cypress.But I found it that for the current version(V13.4.0),it doesn't support the iframe record.Will the record function be enhanced later?

### Test code to reproduce

I wish the record function would be better for later cypress versionn

### Cypress Version

13.4.0

### Node version

18.18.2

### Operating System

Windows 11 家庭中文版

**Comment by jennifer-shehane** [comment]
@wanghaomiao27 Can you provide the URL of the Test Replay where the iframe should have been recorded? Iframes should be recorded and replayed, so we'd like to investigate if there's a bug.

**Comment by wanghaomiao27** [comment]
@jennifer-shehane Hi jennifer,  for this URL     http://wolf.test.datatist.cn/aimarketer/home/iframe?src=/tag/aimarketer/iframe/labelmanage,I found that the iframe could not be recorded.Can you take a look?

**Comment by wanghaomiao27** [comment]
@jennifer-shehane   
![image](https://github.com/cypress-io/cypress/assets/20040189/9971c301-ad9b-4a57-849b-c1db9add4fa1)
you can also see from the screenshot that there is iframe there.But I tried to use record function,it doesn't work

**Comment by jennifer-shehane** [comment]
@wanghaomiao27 Can you provide the URL in the Cloud of the run recording where the iframe is not present? I am assuming you are talking about Test Replay.

**Comment by wanghaomiao27** [comment]
@jennifer-shehane it's not about test replay,it is about record the scripts.Let me give you a screenshot

**Comment by jennifer-shehane** [comment]
We’ll have to close this issue as we haven’t been given enough information to reproduce the issue.
