### ISSUE TITLE
Interceptor fails to Match GET Requests with Relative Paths in cypress component testing

### ISSUE THREAD

**Issue by mlueckech21** [cypress-io/cypress#28325]
### Current behavior

In a Vue.js application with Cypress component testing, the cy.intercept method successfully intercepts POST requests but fails to intercept GET requests with relative paths. While POST requests are correctly intercepted and modified, GET requests to a similar relative path are not intercepted, leading to failed assertions in our tests. This inconsistency suggests a potential issue in handling GET request interceptions in the framework.

### Desired behavior

The expected behavior is that Cypress's cy.intercept method should consistently intercept both GET and POST requests, regardless of whether they are made to absolute or relative paths. In the context of our application, this means that when a GET request is made to a relative path, the interceptor should be able to capture and modify the request/response in the same way it does for POST requests.

![Screenshot 2023-11-13 160108](https://github.com/cypress-io/cypress/assets/141722296/910048f3-0ae0-4b7a-ae71-e4bc996e8cbe)

The interceptor is not matching the GET request altough it should match every GET request.

### Test code to reproduce

https://github.com/mlueckech21/cypress-intercepts-relative-get

### Cypress Version

13.4.0

### Node version

v16.17.0

### Operating System

Windows 11 Pro 22621.2283

**Comment by nelli91** [comment]
@mlueckech21 I think I have the same problem, did you find any solution for this? Thanks!

**Comment by AAndonio** [comment]
Hi all! Does anyone found a solution for this problem? I'm using the latest version of Cypress (13.14.0) and still have it
