### ISSUE TITLE
How to assert that a get should fail

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#2832]
I'm wondering how to assert that a given element should not be on the page, aka the `cy.get(myEl)` should fail. 

Thanks!

**Comment by tnrich** [comment]
whoops wasn't trying to make an issue. sorry closing this now

**Comment by StanFisher** [comment]
Try `cy.get('myEl').should('not.exist')`.

**Comment by tnrich** [comment]
@StanFisher thanks I'll try that.

**Comment by tnrich** [comment]
Cheers that works! 
![image](https://user-images.githubusercontent.com/2730609/49043497-2265b980-f180-11e8-916a-d47a13e254bd.png)
