### ISSUE TITLE
Recommended books about Cypress

### ISSUE THREAD

**Issue by kev2718** [cypress-io/cypress#2833]
Heyho, I'm writing an essay about automated frontend testing and would like to extend my book list with books about cypress. 
Thanks in advance for any book, paper or article you can recommend! :)

**Comment by jennifer-shehane** [comment]
Hey @kev2718, we have some blogs, screencasts, podcasts, and talks people have given on the topic of Cypress. I don't know of any published books on the subject. 

https://on.cypress.io/blogs-media
