### ISSUE TITLE
Since Cypress 12.15.0 (and on 13.5.0 still), "cy.readFile must only be invoked..." when using basic auth credentials in baseUrl

### ISSUE THREAD

**Issue by adrienharnay** [cypress-io/cypress#28336]
### Current behavior

```
CypressError: Timed out retrying after 10000ms: `cy.readFile()` must only be invoked from the spec file or support file.
```

When defining a baseUrl with basic auth.

Since 12.15.0, also tested on 13.5.0.

### Test code to reproduce

Here is the smallest possible reproduction: https://github.com/Brigad/cypress-test-tiny

Commit that introduced the bug: https://github.com/Brigad/cypress-test-tiny/commit/e947d47aa9cb684370fcf2eac4924063b3383e33

### Cypress Version

13.5.0

### Node version

20.6.0

### Operating System

macOS

### Debug Logs

```shell
CypressError: Timed out retrying after 10000ms: `cy.readFile()` must only be invoked from the spec file or support file.
```

**Comment by jennifer-shehane** [comment]
Thanks for filing an issue @adrienharnay, we'll give this a look.

**Comment by Markus-Ende** [comment]
we have the same issue on Cypress 13.5.0 with cy.task in combination with cyLog ( see original issue https://github.com/cypress-io/code-coverage/issues/667)

**Comment by AlexejKunz-Witt** [comment]
I have the same issue but its only the case on my CI-Pipeline. I tried to run tests on my CI-Pipeline on Cypress Version 12.12.0 and it worked, now I tried it again with the newest version 13.5.1 and I am getting the error:
"CypressError: Timed out retrying after 10000ms: `cy.readFile()` must only be invoked from the spec file or support file."

**Comment by Uriyay2** [comment]
Facing the dame issue in version 13.6.0

**Comment by jennifer-shehane** [comment]
We're investigating this situation.
