### ISSUE TITLE
browser option : chrome not found

### ISSUE THREAD

**Issue by anuragipankaj** [cypress-io/cypress#2834]
I'm trying to run my testcases through  cypress though the following command :

---------------------------------------------------------------------------------------------
```
$- npx cypress run --browser chrome --headed

and it gives the following output for the same:

$-Warning: We failed to remove old browser profiles from previous runs.
This error will not alter the exit code.
[object Object]
Can't run because you've entered an invalid browser.
Browser: 'chrome' was not found on your system.
Available browsers found are: electron
```
---------------------------------------------------------------------------------------------

and also by UI : 
```
$- npx cypress open
```
![image](https://user-images.githubusercontent.com/39908261/49013589-4d153980-f1a3-11e8-924b-58667bd29135.png)

its not showing chrome as option.
any idea how i can solve this issue ? is there any path info i need to add in my code?
as electron is working fine.

-----------------------------------------------------------------------------------------------
windows: 10
cypress : 3.1.2
chrome: 70.0

**Comment by jennifer-shehane** [comment]
Could you explain what you did before running into this issue? Has Chrome worked for you previously? Did you recently update?

I believe that clearing the AppData may solve the problem. To do this:

- open up the cypress app
- Go to `File` -> `View App Data`
- Delete everything in here
- Close cypress and open it up again
- And it should recreate all the browser profiles + extension

**Comment by DovRine** [comment]
Confirmed on arch linux: 4.19.2-arch1-1-ARCH running google-chrome-stable.
Creating a symlink to /usr/bin/chrome did not help.
Clearing app data did not help.

**Comment by anuragipankaj** [comment]
@jennifer-shehane  i just installed cypress newly on my system and chrome was not showing. then i tried re-install chrome but still facing same issue.
then i also tried to re-install cypress but still no chrome option was found.

**Comment by xiaoxu12** [comment]
I have the same problem.

**Comment by chli283** [comment]
>cypress run --browser chrome 

and it gives the following output for the same:
....
Can't run because you've entered an invalid browser.
Browser: 'chrome' was not found on your system.
Available browsers found are: electron

NOTES:
win 7 
chrome 71 in my system

**Comment by chli283** [comment]
Command `cypress open `   can open cypress with default electron chrome 59.
Our application only supports browser above chrome 64. 
So that I would like to cypress run with system chrome, not default chrome59.
Run 'cypress run --browser chrome'
Error:
Can't run because you've entered an invalid browser.
Browser: 'chrome' was not found on your system.
Available browsers found are: electron

**Comment by sebastiansalinasm** [comment]
This problem only appairs in Windows apparently, i tried on Ubuntu and Debian and not fail.

**Comment by sebastiansalinasm** [comment]
> Command `cypress open ` can open cypress with default electron chrome 59.
> Our application only supports browser above chrome 64.
> So that I would like to cypress run with system chrome, not default chrome59.
> Run 'cypress run --browser chrome'
> Error:
> Can't run because you've entered an invalid browser.
> Browser: 'chrome' was not found on your system.
> Available browsers found are: electron

check your versions of NPM, i have 6.4.1 and Works!

**Comment by zhengbli** [comment]
I made symbol link `/usr/bin/google-chrome` to `/usr/bin/google-chrome-beta` now it works.

**Comment by flotwig** [comment]
Hi everyone, we're working on a fix for the "browser not found" issue. In the meantime, try using the workaround in this comment, linking your binaries to google-chrome for Chrome or chromium-browser for Chromium:

https://github.com/cypress-io/cypress/issues/3217#issuecomment-45738211

The issue mentioned in the OP is a different problem, I'll investigate it as part of the ongoing browser detection changes.

**Comment by 76creates** [comment]
You could debug Cypress with https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs and see which binary its trying to run its one of the last lines, in my case it was 'google-chrome`, I've created a symbolic link `/usr/bin/google-chrome -> /opt/google/chrome/chrome` and it worked quite fine.
That or add `/opt/google/chrome` to $PATH.
Cheers.

**Comment by JorgeRamosZavala** [comment]
Hi, was there a fix or workaround for the error from the OP? I am getting the same, although it does not seem to break anything it would be nice to clear that warning. (I am also using the workaround from https://github.com/cypress-io/cypress/issues/3912)

**Comment by flotwig** [comment]
@JorgeRamosZavala 	Could you share your DEBUG logs, [as described here](https://on.cypress.io/debugging#Print-DEBUG-logs)? I don't believe we were ever able to reproduce this issue.

**Comment by yuantops** [comment]
@flotwig I also meet this problem. Tried clearing AppData https://github.com/cypress-io/cypress/issues/2834#issuecomment-441956393 , didn't work. 

Environment:
> OS: Windows 10 (64bit)
> Chrome installed: 75.0.3770.100 (64bit)
> cypress: 3.3.2

Command: 
> D:\cypressProjects\sample>node_modules\.bin\cypress open

Debug log(excerpt):
>   cypress:server:updater checking for new version of Cypress. current version is 3.3.2 +0ms
  cypress:launcher checking one browser chrome +0ms
  cypress:launcher looking up chrome on win32 platform +2ms
  cypress:launcher exe path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe +0ms
  cypress:launcher found C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ? true +0ms
  cypress:launcher browser chrome not installed +37ms
  cypress:launcher checking one browser chromium +1ms
  cypress:launcher looking up chromium on win32 platform +1ms
  cypress:launcher exe path C:\Program Files (x86)\Google\chrome-win32\chrome.exe +0ms
  cypress:launcher found C:\Program Files (x86)\Google\chrome-win32\chrome.exe ? false +1ms
  cypress:launcher browser chromium not installed +1ms
  cypress:launcher checking one browser canary +0ms
  cypress:launcher looking up canary on win32 platform +0ms
  cypress:launcher exe path C:\Users\HP\AppData\Local\Google\Chrome SxS\Application\chrome.exe +1ms
  cypress:launcher found C:\Users\HP\AppData\Local\Google\Chrome SxS\Application\chrome.exe ? false +1ms
  cypress:launcher browser canary not installed +0ms
...

**Comment by flotwig** [comment]
@yuantops Could you try the fix mentioned in [this comment](https://github.com/cypress-io/cypress/issues/4260#issuecomment-507767328)?

**Comment by JorgeRamosZavala** [comment]
> @yuantops Could you try the fix mentioned in [this comment](https://github.com/cypress-io/cypress/issues/4260#issuecomment-507767328)?

I just tried that and worked, the warning message is now gone, I added C:/Windows/System32/Wbem; to my PATH variable.
