### ISSUE TITLE
Starting from cypress 13.0.0 using cy.session() triggers keycloak silent sso check 

### ISSUE THREAD

**Issue by Treyeyer** [cypress-io/cypress#28345]
### Current behavior

Login is done through the UI on beforeEach, so after the session was created we visit the root url and then the test fails. Sometimes the first test in the test suite passes, but on the second test after the session is restored it fails.

### Test code to reproduce

Simple login test
"vue": "^2.7.15",
"keycloak-js": "^21.1.2",
"vite": "^4.5.0"

### Cypress Version

13.0.0

### Node version

18.14-bullseye

### Operating System

Ubuntu 22.04

**Comment by NormalCrazy000** [comment]
I am experiencing the same problem
