### ISSUE TITLE
Testing via Cyress returns 401 error when calling an API

### ISSUE THREAD

**Issue by sananaik511** [cypress-io/cypress#28341]
Hello, 
Thank you for looking into my issue. 
I am currently testing an application using Cypress. One of the test cases involves entering an email ID and clicking on the 'Next' button, after which a verification code should be sent to the entered email ID on the previous screen. This process involves making a call to an API, which returns the data into a field. 

However, the problem I am facing is that when testing through Cypress and clicking on the 'Next' button, I am not receiving the OTP code in the testing application from Mailosaur. Instead, I receive a 401 unauthorized error. I am unsure about the cause of this issue. 

Note: The same code is working for other applications to retrieve the OTP from Mailosaur, and manually the application functions as expected.

![code](https://github.com/cypress-io/cypress-example-kitchensink/assets/149161525/a7ac487b-91f1-4a72-bcc4-239a7d8c6698)

attached response: 
![Error_recaptha](https://github.com/cypress-io/cypress-example-kitchensink/assets/149161525/6f629157-2340-4fc4-83ab-5446aa59cf46)

**Desired behavior:**
Otp should be sent to application from mailosaur. 

Versions
Cypress - 13.3.0
Windows -10
Chrome - v1199

**Comment by MikeMcC399** [comment]
@sananaik511 

This issue list is for reporting bugs in the [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink/) not for requesting assistance in using Cypress.

For "how-to" questions and problems using Cypress you can reach out to the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

Topics including Cypress plugins can also be discussed on Discord.
