### ISSUE TITLE
'400 Bad Request Request Header Or Cookie Too Large' error displayed while login to web application for a particular user role

### ISSUE THREAD

**Issue by DeepaQA1** [cypress-io/cypress#28357]
### Current behavior

1. Manually I am able to login to web app for a particular role.
2. Through Cypress for the same user role getting '400 Bad Request
Request Header Or Cookie Too Large' error.
3. Same web app login works fine through Cypress for the different user role.

![image](https://github.com/cypress-io/cypress/assets/151118420/e0e6341d-d6a9-416d-8615-6e8079c7db5d)

### Desired behavior

Login to web application should be successful for different user roles through Cypress.

### Test code to reproduce
```js
describe('Verify Login Page', () => {
    it('Login page title check',()=>{
        cy.visit("https://abc/")
       
        cy.get('.btn').click()

        cy.get('input[name="username"]:visible').type("email id1") 
        //Failing email - email id1
        //Passing email - email id2

        cy.get('input[name="password"]:visible').type("pass1")

        cy.get('input[name="signInSubmitButton"]:visible').click()

        cy.wait(2000)

    })
})
```

### Cypress Version

  "cypress": "^13.5.0"

### Node version

v18.16.1

### Operating System

Windows 10.0.19045.3570

**Comment by alex-hedley** [comment]
Are these all linked?
#76 #3708 #8601

**Comment by jennifer-shehane** [comment]
@DeepaQA1 Hi, we'd need a provided reproducible example that we can run in order to investigate.

**Comment by riowijaya77** [comment]
Hi, i've got the same issue, is there any solution for that?
