### ISSUE TITLE
Cypress 13.5.1 - Header not transmited to new tabs open in chromium navigator

### ISSUE THREAD

**Issue by FabienBounoir** [cypress-io/cypress#28350]
### Current behavior

When I need to download a file, it opens another tab in the chromium browser, the credentials are not passed to the new tab, so I have my api asking me to authenticate again, 

on the other hand, it works fine using the firefox browser.

![image](https://github.com/cypress-io/cypress/assets/71253960/03ef5b03-bdaf-4c0b-b9b8-7d8627b7aaac)

### Desired behavior

What I'd like to see again is the header in the new tab, as it was in version 13.4.0.

currently this prevents me from downloading the file and validating my functional test.

### Test code to reproduce

```js
    cy.visit('/file?filename=test.txt')
    cy.contains('download').click()
    const downloadsFolder = Cypress.config('downloadsFolder')
    cy.readFile(path.join(downloadsFolder, 'test.txt')).should('exist')
```

### Cypress Version

13.5.1

### Node version

v18.17.1

### Operating System

Ubuntu 22.04 LTS

### Debug Logs

```shell
AssertionError
Timed out retrying after 4000ms: cy.readFile("/home/fabien/Git/project/cypress/downloads/test.txt") failed because the file does not exist at the following path:



/home/fabien/Git/project/cypress/downloads/test.txtLearn more
cypress/e2e/project/file-download/file-download.cy.ts:25:1
  23 |         cy.contains('download').click();
  24 |         var downloadsFolder = Cypress.config('downloadsFolder');
> 25 |         cy.readFile(path.join(downloadsFolder, 'test.txt')).should('exist');
     | ^
  26 |     });
  27 |     afterEach(function () {
  28 |         cy.visit('/file?filename=test.txt');
```

**Comment by Nayboko** [comment]
Hi, I got the same issue since 13.5.0 on Chromium 119.0.6045.159  when I try to upload then download for finally read a simple txt file. It works fine on Firefox 119.0.1.

The 13.5.1 update did not change anything.
