### ISSUE TITLE
Cypress origin callback issue

### ISSUE THREAD

**Issue by StefanTegeltija** [cypress-io/cypress#28365]
### Current behavior

Hi, everyone! I'm encountering a callback issue during login when using Cypress exclusively. I've tried all the solutions available on the internet to fix this problem, but none of them have worked. I attempted authentication with Auth0 and Next.js auth, and even added different cookies, but it didn't help.

Please note that my company uses Auth0 and Next.js auth in combination.

I've created a reproducible example of the issue: https://github.com/StefanTegeltija/callback-issue-example.

To reproduce the issue, simply download the project and run npm run run:dev.

Thank you in advance for your help.

### Test code to reproduce

https://github.com/StefanTegeltija/callback-issue-example

### Cypress Version

12.17.4

### Node version

16.18.1

### Operating System

Mac OS

**Comment by Ribeiro-Tiago** [comment]
could you describe what exactly the issue is as well so we don't need to download and run your reproduceable to find out

**Comment by StefanTegeltija** [comment]
https://github.com/cypress-io/cypress/assets/26068374/f29c5162-a99d-409a-adc8-aff1759b25f2

**Comment by StefanTegeltija** [comment]
Please check the video, the problem is that in Cypress Im getting Callback error what is not case in Manual testing.

**Comment by StefanTegeltija** [comment]
Guys, have you found some solution for this? @jennifer-shehane @Ribeiro-Tiago

**Comment by Ribeiro-Tiago** [comment]
> Guys, have you found some solution for this? @jennifer-shehane @Ribeiro-Tiago

I have no idea tbh. Have you tried not adding the trailing slash to the URL? xD 

In my case I just have the domain, no https or / at the end

**Comment by StefanTegeltija** [comment]
It's not the problem. The problem is whatever I do, Cypress isn't sending info to Auth0 or Next.js that I'm authorised user. I tried all solutions from this page: https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication but any of them doesn't work.
