### ISSUE TITLE
TeamCity reporter displays NaN for test suite duration when using describe blocks

### ISSUE THREAD

**Issue by downeyfe** [cypress-io/cypress#2837]
### Current behavior:
When running tests grouped in `describe` blocks with the TeamCity reporter the duration for each block is output as `NaN`.

Example test:
```js
describe('Describe Test', () => {
    it('renders page', () => {
        cy.visit('www.google.com')
        cy.title().should('equal', 'Google');
    });
});
```

Output:
```
##teamcity[testSuiteStarted name='Describe Test']
##teamcity[testStarted name='renders page' captureStandardOutput='true']
##teamcity[testFinished name='renders page' duration='1208']
##teamcity[testSuiteFinished name='Describe Test' duration='NaN']
##teamcity[testSuiteFinished name='mocha.suite' duration='3506']
```

### Desired behavior:

For the duration of 'Describe Test' to be shown as the real value.

### Steps to reproduce:

Wrap a test with a describe block and run with the TeamCity reporter.
I [forked cypress-test-tiny](https://github.com/downeyfe/cypress-test-tiny) and added a basic test which shows the problem. Run `npm run cypress:run:ci` to see the output.

### Versions

Cypress: 3.1.2
OS: Windows 10 (10.0.17134)

### Notes
I wanted to report this on the [reporter repo](https://github.com/cypress-io/mocha-teamcity-reporter) but it's not accepting issues, so I hope this is the next best place.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
