### ISSUE TITLE
Proposal: rename events to be more consistent

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2838]
All events have no more than 2 parts and are generally namespaced with their domain (page, internal, test, etc).

- [x] `window:alert`          -> `page:alert`
- [x] `window:confirm`        -> `page:confirm`
- [x] `before:window:load`    -> `page:start`
- [x] `window:load`           -> `page:ready`
- [x] `window:unload`         -> `page:end`
- [x] `url:changed`           -> `page:urlChange`
- [x] `file:preprocessor`     -> `browser:filePreprocessor`
- [x] `before:browser:launch` -> `browser:launch`
- [x] `command:end`           -> `internal:commandEnd`
- [x] `command:enqueued`      -> `internal:commandEnqueue`
- [x] `command:retry`         -> `internal:commandRetry`
- [x] `command:start`         -> `internal:commandStart`
- [x] `after:screenshot`      -> `screenshot`
- [x] `before:test:run`       -> `test:start`
- [x] `after:test:run`        -> `test:end`
- [x] `fail`                  -> `test:fail`
- [x] `viewport:changed`       -> `viewport:change`

**Comment by jennifer-shehane** [comment]
The work for this was never released.
