### ISSUE TITLE
Cypress 12.8.0 cli suddenly produces different binaries causing cypress run to fail

### ISSUE THREAD

**Issue by HarryAnkers** [cypress-io/cypress#28393]
### Current behavior

Cypress isn't working after running yarn install --frozen-lockfile with a node:16.17.0 image. After this step when we run cypress run it exits with code 1.
This use to work and has had no code changes on our side. When we compare the binaries in CYPRESS_CACHE_FOLDER we see it has been fully updated (attached rough diff below)
<img width="1347" alt="Screenshot 2023-11-23 at 15 46 42" src="https://github.com/cypress-io/cypress/assets/32963840/ac521480-c1df-497b-90d3-41fe8fc83521">

### Desired behavior

Cypress 12.8.0 cypress run works with older binary version.

### Test code to reproduce

Unsure of how to do this. Please may you just verify the binary installation on your side:

cypress@12.8.0:
  version "12.8.0"
  integrity sha512-+zblUeRIesOwpZ/E0HT0YE19STwbZy/ySJZIW6BHxX/eVX258gs4t9hP3sE4Opw9y0RfhJeoE8oa1wF/WhIb0A==
  dependencies:
    "@cypress/request" "^2.88.10"
    "@cypress/xvfb" "^1.2.4"
    "@types/node" "^14.14.31"
    "@types/sinonjs__fake-timers" "8.1.1"
    "@types/sizzle" "^2.3.2"
    arch "^2.2.0"
    blob-util "^2.0.2"
    bluebird "^3.7.2"
    buffer "^5.6.0"
    cachedir "^2.3.0"
    chalk "^4.1.0"
    check-more-types "^2.24.0"
    cli-cursor "^3.1.0"
    cli-table3 "~0.6.1"
    commander "^5.1.0"
    common-tags "^1.8.0"
    dayjs "^1.10.4"
    debug "^4.3.4"
    enquirer "^2.3.6"
    eventemitter2 "6.4.7"
    execa "4.1.0"
    executable "^4.1.1"
    extract-zip "2.0.1"
    figures "^3.2.0"
    fs-extra "^9.1.0"
    getos "^3.2.1"
    is-ci "^3.0.0"
    is-installed-globally "~0.4.0"
    lazy-ass "^1.6.0"
    listr2 "^3.8.3"
    lodash "^4.17.21"
    log-symbols "^4.0.0"
    minimist "^1.2.6"
    ospath "^1.2.2"
    pretty-bytes "^5.6.0"
    proxy-from-env "1.0.0"
    request-progress "^3.0.0"
    semver "^7.3.2"
    supports-color "^8.1.1"
    tmp "~0.2.1"
    untildify "^4.0.0"
    yauzl "^2.10.0"

### Cypress Version

12.8.1

### Node version

v16.17.0

### Operating System

linux docker image

**Comment by jennifer-shehane** [comment]
The binaries were updated for 12.8.0.. Could you print the error message that you're encountering when running `cypress run`?

**Comment by jennifer-shehane** [comment]
Closing as stale.
