### ISSUE TITLE
Cypress giving 404 not found after authentication

### ISSUE THREAD

**Issue by eoin-roll-out** [cypress-io/cypress#28402]
### Current behavior

Hi - I am a QA working on a new application that uses an oidc flow with a third party for authentication to the app which means the subdomains are different. Currently when I navigate through this journey I receive a 404 from cypress. 

I have got around this in the past by setting session details directly into the cypress window but this is not now working. I think this is absolutely an issue to address as cypress currently penalises testers on apps that have greater security due to it's problem with subdomains.

In the meantime any workarounds would be appreciated. 

### Desired behavior

I am able to login to cypress and conduct my tests.

### Test code to reproduce

Please ask for this as I would not like to provide code visible to everyone.

### Cypress Version

13.0.0

### Node version

16.19.0

### Operating System

macOS 13.6

### Debug Logs

```shell
404 webpage
```

**Comment by jennifer-shehane** [comment]
@eoin-roll-out We've made several changes with Cypress with the introduction of Cypress 12 including [Test Isolation](https://docs.cypress.io/guides/core-concepts/test-isolation#__docusaurus_skipToContent_fallback), [cy.session](https://docs.cypress.io/api/commands/session) and [cy.origin](https://docs.cypress.io/api/commands/origin). The combination of which are useful for testing login flows. I'd suggest reading through these docs.
