### ISSUE TITLE
No support firefox 120.0（or 119.0）in Ubuntu 22.04

### ISSUE THREAD

**Issue by RosyCloudsLee** [cypress-io/cypress#28415]
### Current behavior

When running _**npx cypress run --e2e --browser firefox**_，CLI shows 

> Can't run because you've entered an invalid browser name.
> 
> Browser: firefox was not found on your system or is not supported by Cypress.

### Desired behavior

Use cypress with firefox normally

### Test code to reproduce

It shouldn't be necessary

### Cypress Version

13.6.0

### Node version

20.9.0

### Operating System

ubuntu 22.04

### Debug Logs

```shell
Use firefox 120.0（or 119.0）

/usr/bin/firefox -h      -->
    Usage: firefox [ options ... ] [URL]
       where options include:

/usr/bin/firefox -v  --->
  empty
```

### Other

Cypress with firefox 113.0.2 can  work normally.
When use firefox 113.0.2, use 
/usr/bin/firefox -v  --> Show Specific version

**Comment by jennifer-shehane** [comment]
@RosyCloudsLee I'm not encountering this error when running with Firefox 120 on 13.6.0

<img width="847" alt="Screen Shot 2023-11-28 at 11 13 11 AM" src="https://github.com/cypress-io/cypress/assets/1271364/334214e6-9101-4b94-bdaf-988125c88af7">

You can see our troubleshooting guide for launching browsers. Sometimes I see this situation if you've renamed the browser in some way.

**Comment by RosyCloudsLee** [comment]
Use https://ftp.mozilla.org/pub/firefox/releases/120.0  to reinstall firefox -->  Cypress can work normally.

Use Ubuntu Software app(snap) to installl firefox --> Abnormal
Refer to [this url](https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04) to install firefox --> Abnormal

So firefox in the apt repository (ppa:mozillateam/ppa or ppa:ubuntu-mozilla-security/ppa) has a problem
