### ISSUE TITLE
When Cypress tries to access an iframe element under cy.origin(), it fails with "(uncaught exception) Error: Script error".

### ISSUE THREAD

**Issue by Sunnyraj042** [cypress-io/cypress#28417]
### Current behavior

Cypress fails to detect iframe elements in cross origin and fails with error "(uncaught exception) Error: Script error".
![Screenshot ](https://github.com/cypress-io/cypress/assets/41203725/277a05f9-218d-460c-a088-062fc66d799d)

### Desired behavior

Shouldn't fails with the error "(uncaught exception) Error: Script error" and able to proceed to perform actions on iframe element.

### Test code to reproduce

```js
describe('Authenticate', () => {

   beforeEach(() => {
       cy.restoreLocalStorage();
       cy.preserveSession();
   });

   afterEach(() => {
       cy.saveLocalStorage();
   })

   it('Show homepage once logged in', () => {
       cy.origin('https://authentication.net/', () => {
           cy.visit('https://authentication.net/legacyLogin.html?source=accSelLgcy&stId=47848661');
           cy.get('#userName').type('userName');
           cy.get('#sitePass').type('password');
           cy.get('input[name="loginButton"]').click({ force: true });
       });
       cy.origin('https://z1-a.le.net/', () => {
           cy.get("h1").should("contain", "Workspace");
           cy.get('.nb-s-icon').click({ force: true });
           cy.wait(10000);
           cy.get('.nav-list__item__title').contains('Automate').click({ force: true });
           cy.wait(12000);
           cy.get('.nav-list__item__title').contains('Manager').click({ force: true });
           cy.wait(20000);
           cy.get('.nb-s-icon').click({ force: true });
           cy.wait(12000);
           cy.get('.imanager-navigation').should('contain', 'Analyze');

// Here i start getting the error
           cy.get('#liveintent-iframe').should('be.visible').should('not.be.empty').then(($iframe) => {
               const $body = $iframe.contents().find('body')
               cy.wrap($body)
                   .find('span[title="Insurance"]').click();
           })
       })
   })
})

```
cypress.config.js
```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
 experimentalModifyObstructiveThirdPartyCode: true,
 defaultCommandTimeout: 80000,
 viewportHeight: 1080,
 viewportWidth: 1920,
 e2e: {
   testIsolation: false,
   experimentalOriginDependencies: true,
   setupNodeEvents(on, config) {
     // implement node event listeners here
   },
 },
});

```

### Cypress Version

Tested with version 12.17.4, 13.3.3 and 13.6.0

### Node version

v16.13.2

### Operating System

macOS 12.6.3

### Debug Logs

```shell
(uncaught exception)Error: Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the crossorigin attribute and setting a CORS header.
```

**Comment by ANSHUL786** [comment]
Use below code in command.js file

Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
})

**Comment by Sunnyraj042** [comment]
> Use below code in command.js file
> 
> Cypress.on('uncaught:exception', (err, runnable) => { // returning false here prevents Cypress from // failing the test return false })

Thanks @ANSHUL786 for Suggestion but it didn't work.

**Comment by ANSHUL786** [comment]
make sure **return false** is not commented out.

Can you reconfirm this?

Cypress.on('uncaught:exception', (err, runnable) => {
return false;
})

**Comment by Sunnyraj042** [comment]
> make sure **return false** is not commented out.
> 
> Can you reconfirm this?
> 
> Cypress.on('uncaught:exception', (err, runnable) => { return false; })
@ANSHUL786 Yes, it hasn't been commented even though I tried with in the same test (it block), but it didn't help.
