### ISSUE TITLE
Cypress crash when starting the second test case

### ISSUE THREAD

**Issue by manphannvg** [cypress-io/cypress#2841]
### Current behavior:

Cypress crash after finished the first test case, when it starts the second test case, Cypress get crashed

### Desired behavior:

Cypress should not crash

### Steps to reproduce:

See video
https://youtu.be/GB1B3_6D6TY

### Versions
It worked properly before with version 3.1.1 but it occurs on 3.1.2

**Comment by manphannvg** [comment]
You can use this script to reproduce.

  it('first case',function(){
    cy.visit('https://www.immoscout24.ch/de/immobilien/mieten/ort-zuerich?webtest=true')
  })
  
  it('second case', function () {
    cy.visit('https://www.immoscout24.ch/de/immobilien/mieten/ort-zuerich?webtest=true')
  })

**Comment by Bkucera** [comment]
@manphannvg i'm able to reproduce the crash in all 3.x versions of cypress. 

I'm not sure why it's happening, but it only seems to occur with the `?webtest=true` param, so maybe there's something affecting cypress in there.
