### ISSUE TITLE
Property 'mount' does not exist on type 'cy & CyEventEmitter'.

### ISSUE THREAD

**Issue by Gennady77** [cypress-io/cypress#28420]
### Current behavior

I wrote test accordingly instruction and got TS error - Property 'mount' does not exist on type 'cy & CyEventEmitter'.
my tsconfig file
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "useDefineForClassFields": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "jest",
      "cypress",
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "node_modules/cypress/types/cypress-global-vars.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

### Desired behavior

there should be no error

### Test code to reproduce
```js
import Button from '@/components/Button/Button.vue';

describe('<Button />', () => {
  it('mount', () => {
    cy.mount(Button);
  });
});
```
### Cypress Version

10.3.1

### Node version

16.18.0

### Operating System

macOS 14.1.1

**Comment by thevladisss** [comment]
Yes, Cypress ships Vue test utils out of the box, however, it is not types as property of "cy" global constant. You have to make a module augmentation. You can read more about augmentation here: https://docs.cypress.io/guides/tooling/typescript-support

However for your issue you can use following code placed somewhere in "src" or "tests" folder as they are resolved by tsconfig, hence included into the compilation

https://docs.cypress.io/guides/tooling/typescript-support
```js
src/cypress-augmentation.d.ts

import { mount } from "cypress/vue"
declare global {
  namespace Cypress {
    interface Chainable {
      mount: typeof mount;
    }
  }
}

```

**Comment by jennifer-shehane** [comment]
@Gennady77 Does this help resolve your issue?

**Comment by cbrgpl** [comment]
> @Gennady77 Does this help resolve your issue?

I had the same problem and your answer helped me to resolve the problem. Thx

**Comment by abaraev** [comment]
I had this problem. Create a separate TypeScript configuration file for Cypress, and it's important that its name differs from the main application file. For example:
The main file is **tsconfig.json** And for Cypress, it's **tsconfig.spec.json**
