### ISSUE TITLE
require not working

### ISSUE THREAD

**Issue by ErezSchwartz** [cypress-io/cypress#2842]
### Current behavior:

I am trying to import a module that I wrote to a cypress spec, but no matter what I tried i kept getting the error `Cannot convert undefined or null to object`.(in other files that aren't using cypress that I tried to `export` it to  the function worked)

the error:
```
tests?p=cypress\integration\email_spec.js-570:40227 Uncaught TypeError: Cannot convert undefined or null to object

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
    at Function.getPrototypeOf (<anonymous>)
    at module.exports (tests?p=cypress\integration\email_spec.js-570:40227)
    at Object.451.axios (tests?p=cypress\integration\email_spec.js-570:191360)
    at o (tests?p=cypress\integration\email_spec.js-570:1)
    at tests?p=cypress\integration\email_spec.js-570:1
    at Object.238../jwtaccess (tests?p=cypress\integration\email_spec.js-570:38529)
    at o (tests?p=cypress\integration\email_spec.js-570:1)
    at tests?p=cypress\integration\email_spec.js-570:1
    at Object.<anonymous> (tests?p=cypress\integration\email_spec.js-570:37526)
    at Object.235.../transporters (tests?p=cypress\integration\email_spec.js-570:38269)
```

### Desired behavior:

the `require` to import the function that is required 

### Steps to reproduce:

have a cypress test.
 create a node file in the same folder and write a function(even just having a `console.log` does the bug). export that function.
import/require that function in the cypress file. 
the error appears when you run the cypress test

**Comment by jennifer-shehane** [comment]
Could you provide the test code you wrote with the require statement?

**Comment by ErezSchwartz** [comment]
I am using the google api, and the import of the googleapi is the problematic part is this line-
`const {google} = require('googleapis');`
when I change this line to a comment my code works

**Comment by haimyyy** [comment]
+1

**Comment by AnandGanesh-Reflektion** [comment]
+1

**Comment by brian-mann** [comment]
This is likely the same issue as this: https://github.com/cypress-io/cypress/issues/2902

If `googleapis` utilizes `node` specific modules under the hood that aren't available in the browser, it will not work.

You need to switch to using `cy.task(...)` and write the implementation in your `pluginsFile` and it'll work.

**Comment by ErezSchwartz** [comment]
thank you

**Comment by jennifer-shehane** [comment]
I know that we preprocess the spec files with babel and browserify, not sure if that's involced with this error. https://on.cypress.io/using-cypress-faq.html#How-do-I-require-or-import-node-modules-in-Cypress
