### ISSUE TITLE
Issue with Cypress and Nextjs CI?CD Pipeline

### ISSUE THREAD

**Issue by Eshwar1212-maker** [cypress-io/cypress#28447]
### Current behavior

Hey guys. I added my Cypress tests to my Nextjs 13 app. Cypress works totally fine in the cypress app(which I use npx cypress open to open), but Im having annoying issues when hooking it up to my Github actions CI/CD pipeline that deploys to Vercel. The tests are passing in my local machines Cypress app but im getting random errors on Github Actions saying things like this: 

 ```> Build error occurred
Error: Failed to collect page data for /api/conversations
    at /home/runner/work/Sports-Sync/Sports-Sync/node_modules/next/dist/build/utils.js:1161:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
Error: Process completed with exit code 1.
```
Which doesnt make any sense since this API route works perfectly in my app.

### Desired behavior

I just want to be informed if one of the tests I ACTUALLY WROTE passes or fails in my CI/CD pipeline before I make a pull request to main. Even if I get other random errors like this its fine as long as im informed my tests I wrote work. 

### Test code to reproduce

The application has alot of code but you can get the env variables to run it: https://github.com/Eshwar1212-maker/Sports-Sync/tree/development.   

Also, I could be making a mistake in my github/workflows folder with my cy.yml or main.yml file. 

### Cypress Version

13.5.1

### Node version

18

### Operating System

Mac

### Debug Logs

```shell
35s
1m 19s
Run npm run build

> basketballfitnext@0.1.0 build
> next build

- warn No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

- info Creating an optimized production build...
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
- info Compiled successfully
- info Linting and checking validity of types...
- info Collecting page data...
You must pass your app key when you instantiate Pusher.

> Build error occurred
Error: Failed to collect page data for /api/conversations
    at /home/runner/work/Sports-Sync/Sports-Sync/node_modules/next/dist/build/utils.js:1161:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
Error: Process completed with exit code 1.
0s
```

**Comment by adidoes** [comment]
what version of nextjs are your running? I get this too but only on 14.0.4

**Comment by jennifer-shehane** [comment]
Going to close this as Next.js issues will be tracked here: https://github.com/cypress-io/cypress/issues/28185
