### ISSUE TITLE
Uncaught Error: Attempting to use a disconnected port object

### ISSUE THREAD

**Issue by MaksuCode** [cypress-io/cypress#28443]
### Current behavior

**Problem** : On Cypress UI, sometimes I have the problem that test cases fail to finish and run forever. It happens on a random basis.

**Steps to reproduce** : 
1 - Open Cypress UI with browser Chrome 119
2 - Run a spec file 

**Actual result** : Sometimes test cases fails to finish and runs forever due to the uncaught error that is mentioned below

**Console log** :

![image](https://github.com/cypress-io/cypress/assets/60291378/1d3ce1f9-56fd-476f-a77c-525c26c0f46e)

**The breaking code block** : 

![image](https://github.com/cypress-io/cypress/assets/60291378/13821d6d-0fdb-4908-bbd6-5ed07406cc5e)

### Desired behavior

The test cases should be executed properly.

### Test code to reproduce

I will try to add it as soon as I could reproduce it on the forked repo.

### Cypress Version

v13.6.0

### Node version

v18.18.0

### Operating System

Windows 23H2

**Comment by clewott** [comment]
I am seeing this issue as well on 13.6.1.

**Comment by akselil** [comment]
We have also this issue with Cypress 13.6.4

**Comment by jennifer-shehane** [comment]
Could you all try to update to 13.6.6 and let us know if you're still experiencing this issue? We fixed an issue in 13.6.5 that was introduced in 13.6.0 and we want to understand if this has also resolved this issue. Thank you!

**Comment by MaksuCode** [comment]
I am not facing this issue anymore with v13.12.0

**Comment by lukascivil** [comment]
I am facing this issue with v13.13.0 on macOS with chrome 126.

**Comment by jennifer-shehane** [comment]
@lukascivil Please provide an example and way to reproduce in a new issue.
