### ISSUE TITLE
Cypress Not executing the test cases via brave browser

### ISSUE THREAD

**Issue by jeromedoss** [cypress-io/cypress#28441]
### What would you like?

I want run my test cases on chromium based browsers so for the first step of this process i've tried to execute via brave browser the browser launches simply and doesn't executing my test cases

my config.js file
![image](https://github.com/cypress-io/cypress/assets/139545420/208b5e41-4a2d-4349-9efb-1a590593f6f0)

 

I've executed the below command
npx cypress run --headed --spec cypress/e2e/Suites/LaunchGoogle.cy.js 

But result, it just launches the brave browser simply 
![image](https://github.com/cypress-io/cypress/assets/139545420/4041e45b-3fbc-435b-a5bb-a33640186b69)

"cypress": "^13.6.0"

**Comment by jennifer-shehane** [comment]
@jeromedoss What do you see when you run `cypress open`? Could you use a simple test case you know launches in another browser, just expect(true).to.be.true to narrow down the spec?

**Comment by jeromedoss** [comment]
@jennifer-shehane Cypress launches as usual once i navigate to **E2ETesting** It simply launches the brave browser and no scripts were executing.
