### ISSUE TITLE
Spacing of error message is too long with <br>

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#28452]
### Current behavior

![image (4)](https://github.com/cypress-io/cypress/assets/1271364/ab2efc54-0274-4781-abdf-339fde3a9641)
![image (5)](https://github.com/cypress-io/cypress/assets/1271364/f1000b28-b248-4953-bfc3-4343810d8c4c)

The error messages appear to have really wide spacing. They didn't used to have this. Maybe it changed in 10.0. 

### Desired behavior

Spacing should not be so far apart in error messages. We should look at older versions of Cypress and how it used to look to compare when it changed and reduce spacing. Will have to update a lot of snapshots.

### Test code to reproduce

cy.click on non-visible element

### Cypress Version

13.6.0

### Node version

18

### Operating System

Mac

**Comment by saarimshaikh** [comment]
I'm working on it

**Comment by jennifer-shehane** [comment]
This was introduced in 12.4.0. 

Screenshot from 12.3.0:

![Screen Shot 2023-12-11 at 11 22 18 AM](https://github.com/cypress-io/cypress/assets/1271364/f99fef0a-8e42-4748-b649-1d1a69dbf8a6)

![Screen Shot 2023-12-11 at 12 12 39 PM](https://github.com/cypress-io/cypress/assets/1271364/5b63f8c7-19a9-4725-9503-44f4c7905573)
