### ISSUE TITLE
Cypress not pulling out of Date Picker Dom element to iterate to next input.

### ISSUE THREAD

**Issue by Shailth** [cypress-io/cypress#2845]

**Comment by jennifer-shehane** [comment]
You may want to add an assertion after the click that ensures the datepicker closes properly, something like...

```
cy.wrap($el)
  .click()
  .find('[aria-label=day-13]')
  .click()
cy.get('.react-datepicker__time-container')
  .find('.react-datepicker__time')
  .find('.react-datepicker__time-list')
  .contains('00:45')
  .click();
cy.get('.react-datepicker__time-container')
  .should('not.be.visible')
```

This way Cypress will not continue into the next step until the datepicker 'modal' is not visible.

**Comment by Shailth** [comment]
Hi J,

Thanks for the reply, however the issue i am facing is that once the selection is made on the date picker for the time and date, the date picker popup doesn't go away. Which it actually does when in the 
 actual app. Let's say for example https://github.com/cypress-io/cypress/issues/2037.
I've seen your posts on this link and the rest of the discussion, this i believe is to do with the covered element because the date picker pop up doesn't go away. I hope i have explained this adequately. Let . me know if i need to add in more details.

Thanks!

**Comment by pratik-domain** [comment]
I got it working using 
```
cy.get('input[type=date]').type('2019-09-18');
```
Docs here: https://docs.cypress.io/api/commands/type.html#Date-Inputs

**Comment by jimpriest** [comment]
This is still an issue.  Datepicker covers other elements and does not go away despite waiting, etc.

**Comment by jennifer-shehane** [comment]
@jimpriest If you believe your have encountered a bug in Cypress, open a new issue with a fully reproducible example we can run.

**Comment by Ali-Arabpour** [comment]
give a try to another selector... i have had such a this problem by angular material datepicker and i changed my selector from :

tbody td button span 

to:

tbody td button

all in all try clicking on a html DOM element which originally clickable ist
