### ISSUE TITLE
Archive `create-cypress-tests` as it's not compatible with Cypress > 9.x

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28457]
### Current behavior

Executing the npm package [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) hangs at the step "Creating config files" after previously outputting a message referring to a missing file `node_modules/create-cypress-tests/dist/initial-template/plugins/index.js`.

It appears that [npm/create-cypress-tests](https://github.com/cypress-io/cypress/tree/develop/npm/create-cypress-tests) was never converted to run on non-legacy Cypress versions > `9.x` including component testing in its GA version which was released with Cypress [11.0.0](https://docs.cypress.io/guides/references/changelog#11-0-0).

The Migration guide includes the advice [Plugins File Removed](https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed).

### Desired behavior

[create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) should set up a working Cypress test environment for Cypress `13.x` e2e and component testing.

OR

The package [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) should be retired.

### Test code to reproduce

```shell
mkdir cy-create-cypress-tests
cd cy-create-cypress-tests
npm install yarn@latest -g
yarn init -y
npm install create-cypress-tests@latest -g
npx create-cypress-tests
```

### Cypress Version

Cypress `13.6.0`
`create-cypress-tests@2.0.4`

### Node version

`v20.10.0`

### Operating System

Ubuntu `22.04.3 LTS`

### Debug Logs

```shell
✔ Installing cypress (yarn add cypress --dev)
⠋ Creating config files[Error: ENOENT: no such file or directory, stat '/home/mike/n/lib/node_modules/create-cypress-tests/dist/initial-template/plugins/index.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/mike/n/lib/node_modules/create-cypress-tests/dist/initial-template/plugins/index.js'
}
⠦ Creating config files
```

**Comment by jennifer-shehane** [comment]
@MikeMcC399 I'd recommend archiving this project. I can't even remember the intention behind this package's existence, but I don't think we use it anymore.

**Comment by jennifer-shehane** [comment]
I don't know, maybe I just don't understand its utility. I'll have to look through. @MikeMcC399 How did you run into this?

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

>  How did you run into this?

- I noticed that there was an issue https://github.com/cypress-io/cypress/issues/27999 from @dkasper-was-taken which planned to update this module.

[create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) is not mentioned in https://docs.cypress.io anywhere and if you don't want to update it, then removing it from Cypress and marking it as deprecated in the npm registry as [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) would be the logical step.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

You may want to [unpublish](https://docs.npmjs.com/unpublishing-packages-from-the-registry):

- https://www.npmjs.com/package/create-cypress-tests-beta
- https://www.npmjs.com/package/create-cypress-tests-alpha

from the npm registry.

The same goes for

- https://www.npmjs.com/package/create-cypress-tests

if / when it is removed first from https://github.com/cypress-io/cypress/tree/develop/npm/create-cypress-tests

**Comment by jennifer-shehane** [comment]
I found where the create-cypress-tests was removed and cleaned up in v10 release. So planning to remove this package code and deprecate the npm package. https://github.com/cypress-io/cypress/pull/21438/files

I'm not sure I have access to those beta/alpha packages. Tracking it down.

**Comment by MikeMcC399** [comment]
- Follow-on issue #28499 submitted, since the failing npm module [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) remains published.
