### ISSUE TITLE
Out of memory issue is frequent in 13.6.1 as compared to previous version

### ISSUE THREAD

**Issue by ANSHUL786** [cypress-io/cypress#28468]
### Test code to reproduce

Write a spec file with  lot of assertion or cypress commands and use data in fixture file. 

### Cypress Mode

cypress run

### Cypress Version

13.6.1

### Browser Version

Chrome 118

### Node version

18.17.1

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
@ANSHUL786 What was the previous version you were using? Is it possible to provide a reproducible example for us to run?

**Comment by marshallsanders** [comment]
We're also seeing this after upgrading to Cypress 13.6.1 from 13.6.0.  We're running in a container on the docker image cypress/base:18.16.0.  In a suite of about 400 tests that are running parallel on 12 of these containers about 1/3 of the containers  will crash with the following error message.  Downgrading from 13.6.1 to 13.6.0 fixed the issue.

```
(Cypress:1324): dconf-CRITICAL **: 16:14:59.417: unable to create directory '/home/node/.cache/dconf': Permission denied.  dconf will not work properly.



(Cypress:1324): dconf-CRITICAL **: 16:14:59.417: unable to create directory '/home/node/.cache/dconf': Permission denied.  dconf will not work properly.



(Cypress:1324): dconf-CRITICAL **: 16:14:59.417: unable to create directory '/home/node/.cache/dconf': Permission denied.  dconf will not work properly.

URI malformed

URIError: URI malformed

    at decodeURI (<anonymous>)

    at u.addPending (<embedded>:4454:27423)

    at A.addPendingBrowserPreRequest (<embedded>:4454:37977)

    at a.addPendingBrowserPreRequest (<embedded>:4454:38767)

    at Q.addBrowserPreRequest (<embedded>:4526:13193)

    at c.onBrowserPreRequest (<embedded>:4526:27079)

    at T.onNetworkRequestWillBeSent (<embedded>:4454:49453)

    at _.emit (node:events:525:35)

    at _._handleMessage (<embedded>:2466:580235)

    at A.<anonymous> (<embedded>:2466:579669)

    at A.emit (node:events:513:28)

    at g.U (<embedded>:2466:564853)

    at g.emit (node:events:513:28)

    at g.dataMessage (<embedded>:2466:545228)

    at g.getData (<embedded>:2466:544410)

    at g.startLoop (<embedded>:2466:541117)

    at g._write (<embedded>:2466:540472)

    at writeOrBuffer (node:internal/streams/writable:392:12)

    at _write (node:internal/streams/writable:333:10)

    at Writable.write (node:internal/streams/writable:337:10)

    at Socket.H (<embedded>:2466:565539)

    at Socket.emit (node:events:513:28)

    at addChunk (node:internal/streams/readable:324:12)

    at readableAddChunk (node:internal/streams/readable:297:9)

    at Readable.push (node:internal/streams/readable:234:10)

    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

We detected that the electron tab running Cypress tests closed unexpectedly.
```

**Comment by josego1984** [comment]
I have a similar issue, it started with Chrome 117, it's impossible to run a single test in open mode with numTestsKeepInMemory = 1 and experimentalMemoryManagement: true, it crashes all the time. Changing the value numTestsKeepInMemory to 0 fixes it, but then I can't debug anything.

**Comment by mschile** [comment]
@marshallsanders, would you be able to run with the following [DEBUG](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) log turned on (I'd like to know which URL is causing the URI malformed error):

`DEBUG=cypress*:proxy:http:util:prerequests`

**Comment by mschile** [comment]
@marshallsanders, since your issue doesn't seem related to the OOM error this issue was logged for, I logged a new issue for yours. https://github.com/cypress-io/cypress/issues/28521

**Comment by OleksandrRakovets** [comment]
@jennifer-shehane 

We started experiencing the same issue on 
```
Cypress:        13.6.0
Browser:        Chrome 107 (headless)
Node Version:   v16.16.0 (/usr/local/bin/node)
```

Locally fresh Chrome is consistently crashing OOM, in CI we specifically kept the older version that did not have reports to be subject to OOM issue. But today it started happening ofter in CI as well.

CircleCI reports there is plenty of free memory during the run.

<img width="848" alt="CleanShot 2023-12-26 at 16 36 40@2x" src="https://github.com/cypress-io/cypress/assets/5619390/8f517390-f004-4fb8-aec3-810d49ea0162">

**Comment by jennifer-shehane** [comment]
We'll need more information in order to track down this issue. I don't doubt it is an issue, but we'll need a way to reproduce it on our end.

**Comment by ivanharalampiev** [comment]
at this point imo the best solution is to migrate to playwright like the rest of the world. cypress is just shrugging issues under the rug and calling it a day. just search for all the OOM issues reported before and you'll have pretty good idea what will happen to this one.

**Comment by xgao-lyra** [comment]
I run into the same issue. i don't have much helpful debug info, but i can say the repro stops if i downgrade to `13.6.0`
