### ISSUE TITLE
Empty Testcases after Clicking Download Link

### ISSUE THREAD

**Issue by khashaba** [cypress-io/cypress#28471]
### Current behavior

When attempting to download a file by clicking a download link, the page continuously loads due to Cypress waiting for a load event to be triggered by the application. As there's no actual redirection occurring, Cypress encounters a page load timeout error, causing test failures, and that was the case before version 13.5 release.
Previously I was using the workaround in the previous ticket: https://github.com/cypress-io/cypress/issues/14857
but after updating to 13.5 or later version I get a different issue, which is making any testcases or commands after clicking on the download to be empty with the message: "No commands were issued in this test."
 as in the next screenshot
![image](https://github.com/cypress-io/cypress/assets/12282832/33c1ed18-0559-476e-898e-3d856090b848)

Workaround Attempted:
A previously implemented workaround (as mentioned in GitHub issue #14857) was applied, and it temporarily resolved the issue. After upgrading to Cypress version 13.5, I removed the workaround as it should be fixed by that release, but I got this new issue

**This issue has escalated further as it now fails silently, causing a substantial number of test cases to remain unexecuted**

### Desired behavior

Upon clicking the download link, the file should be triggered for download, and Cypress should not encounter a page load timeout error. Subsequent test cases should continue to execute without interference.

### Test code to reproduce

Steps to Reproduce:

Launch Cypress tool.
Navigate to the test case that involves clicking on a download link to fetch a file.
Execute the test case.
(you can also the [previous ticket](https://github.com/cypress-io/cypress/issues/14857) to reproduce the issue)

### Cypress Version

13.6.1

### Node version

18.15.0

### Operating System

Windows 10

**Comment by LentoMan** [comment]
My machine had an issue with tests stalling after we upgraded and removed a workaround for downloads, turns out it was caused by a setting in Chrome. 

Under the chrome settings for download, ```chrome://settings/downloads```, the option to show downloads when they're done was enabled, disabling it fixed the issue for me.
