### ISSUE TITLE
Cypress forcing install of `@types/node` to specific version (18.17.5)

### ISSUE THREAD

**Issue by joshkaplan** [cypress-io/cypress#28473]
### Current behavior

Cypress is currently being shipped with a dependency on `@types/node^18.17.5` (not a `devDependency`).

However, Cypress lists engine compatibility with 16, 18, or 20. 

The most recent change came from https://github.com/cypress-io/cypress/pull/27715 and shipped in cypress v13.2. [The changelog explicitly states](https://docs.cypress.io/guides/references/changelog#13-2-0): 
> This does NOT have an impact on the node version you are using with Cypress and is merely an internal update

So, I _think_ Cypress should not be forcing users to install such a strict version of these types, if at all.

(On our end, this is causing some issues with our builds + package deduplication.)

### Desired behavior

Don't force such a specific version of `@types/node`. 

Some possible implementations:
1. Don't have the distribution depend on @types/node at all (it's listed as a `devDependency` in package.json, so not sure why it's making it into the distribution)
2. Have the dependency be `"@types/node":  "*"` (this is pretty common; it's how ~90% of our current packages handle it)
3. Have the dependency be `^16.0.0 || ^18.0.0 || >=20.0.0` to match engine compatibliity
4. If there's some reason it needs to be a non-dev dependency, _and_ needs to be 18, at least loosen to `^18.0.0`

### Test code to reproduce

n/a

### Cypress Version

13.16.1

### Node version

18.16

### Operating System

all

**Comment by sharmilajesupaul** [comment]
Another thing to callout -- 
It looks like the this repo's CI build uses a different version of node than the specified @types/node package: https://github.com/cypress-io/cypress/blob/687dc63538bc94c7052e349c2c9e7297fcde7185/.circleci/workflows.yml#L97 (18.15.0 vs 18.17.5 which is what is defined in [dependencies](https://github.com/cypress-io/cypress/blob/afd11edeae8e911f007bbac965aaeca586227116/cli/package.json))

So it would be great to at least correct this for this repository's infrastructure too!
