### ISSUE TITLE
Upgrade commit-info dependency to >= v2.1.0

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2848]
https://github.com/cypress-io/commit-info/releases/tag/v2.1.0 adds fallback environment variables. For setups where `git` is missing or `.git` folder is missing, this could be the "polyfill" to provide commit information via environment variables

**Comment by brian-mann** [comment]
Released in [`3.1.4`](https://docs.cypress.io/guides/references/changelog.html#3-1-4).
