### ISSUE TITLE
Workflow "Handle Issue/PR Comment Workflow" fails (projectId is not defined)

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28491]
### Current behavior

- Follow-on from https://github.com/cypress-io/cypress/issues/28479

[.github/workflows/triage_handle_new_comments.yml](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/triage_handle_new_comments.yml) fails with

> Error: Unhandled error: ReferenceError: projectId is not defined

see [Workflow runs](https://github.com/cypress-io/cypress/actions/workflows/triage_handle_new_comments.yml)

for instance

https://github.com/cypress-io/cypress/actions/runs/7163825997/job/19502869415

### Desired behavior

No error when commented on issue / PR

### Test code to reproduce

Add a comment to an issue

### Cypress Version

N/A

### Node version

N/A

### Operating System

N/A

### Debug Logs

```shell
Run actions/github-script@v6
not from an org member
ReferenceError: projectId is not defined
    at /home/runner/work/cypress/cypress/scripts/triage/comment_workflow.js:115:83
    at Array.find (<anonymous>)
    at Object.handleComment (/home/runner/work/cypress/cypress/scripts/triage/comment_workflow.js:115:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:4:1)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:20)
Error: Unhandled error: ReferenceError: projectId is not defined
```

**Comment by MikeMcC399** [comment]
- Commenting on previous issue #28479 also provoked this error, see https://github.com/cypress-io/cypress/actions/runs/7165945081

**Comment by jennifer-shehane** [comment]
I wish there was a better way to debug these things.
