### ISSUE TITLE
using a 3rd party library that is not supported by Cypress: cypress-cloud"

### ISSUE THREAD

**Issue by air2** [cypress-io/cypress#28495]
### Current behavior

Our devops run started failing recently with the message :

We've detected that you're using a 3rd party library that is not supported by Cypress: cypress-cloud
To continue running Cypress, please remove this library and its configuration files or contact us for help migrating.
https://on.cypress.io/unsupported-third-party-library?p=w53Ds8Oqw6zDn8Otw63Cp8Odw6bDqcOvw54%3D

Locally it runs fine.

### Test code to reproduce

npx cypress run --record false --key 'xxxxxx-xxx-xxx-xxx-xxxx' --spec 'e2e/staging/**/*.cy.ts'

### Cypress Version

13.6.1

### Node version

18.x

### Operating System

Ubuntu 

### Debug Logs

```shell
Will be provided later
```

### Other

This only occurs in Microsoft Devops, not when I run locally (which makes producing debug logs a lot harder because I have to modify the pipeline for this)

**Comment by air2** [comment]
See also: #28386
See also: #28307

**Comment by jennifer-shehane** [comment]
@air2 If you are not utilizing the cypress-cloud plugin, you could try omitting the `--record` flag altogether instead of passing `--record: false`?

**Comment by air2** [comment]
The issue is solved
