### ISSUE TITLE
Unpublish `create-cypress-tests`

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28499]
### Current behavior

- Issue https://github.com/cypress-io/cypress/issues/28457 is not yet resolved.
> Executing the npm package [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) hangs at the step "Creating config files" after previously outputting a message referring to a missing file `node_modules/create-cypress-tests/dist/initial-template/plugins/index.js`.

- PR https://github.com/cypress-io/cypress/pull/28472 removes the source of the npm module [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) from its location in https://github.com/cypress-io/cypress/tree/develop/npm. Also, new versions of the npm modules will not be published.

The npm module [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) however remains published to the [npm registry](https://www.npmjs.com/) https://www.npmjs.com/. If it is used, it will fail to function, and the link in the [README](https://www.npmjs.com/package/create-cypress-tests?activeTab=readme) to

- [Homepage](https://github.com/cypress-io/cypress/blob/develop/npm/create-cypress-tests/#readme) now produces a 404 error

This is in addition to the previous link problems in the published [README](https://www.npmjs.com/package/create-cypress-tests?activeTab=readme)

- [demo](https://github.com/cypress-io/cypress/blob/HEAD/demo.gif) - 404 error
- [Changelog](https://github.com/cypress-io/cypress/blob/HEAD/CHANGELOG.md) - links to wrong `CHANGELOG`

### Desired behavior

[unpublish](https://docs.npmjs.com/unpublishing-packages-from-the-registry):

- https://www.npmjs.com/package/create-cypress-tests
- https://www.npmjs.com/package/create-cypress-tests-beta
- https://www.npmjs.com/package/create-cypress-tests-alpha

from the npm registry.

### Test code to reproduce

npm view create-cypress-tests

### Cypress Version

`13.6.1`

**Comment by jennifer-shehane** [comment]
I deprecated the package: https://www.npmjs.com/package/create-cypress-tests

Going to wait a bit to unpublish I think since I don't want to unknowingly break some dependency. 

We don't have access to [npmjs.com/package/create-cypress-tests-beta](https://www.npmjs.com/package/create-cypress-tests-beta) or [npmjs.com/package/create-cypress-tests-alpha](https://www.npmjs.com/package/create-cypress-tests-alpha)  to unpublish. They're not owned by our organization or any of our team.

**Comment by MikeMcC399** [comment]
@dmtrKovalenko

Please consider unpublishing

- https://www.npmjs.com/package/create-cypress-tests-beta
- https://www.npmjs.com/package/create-cypress-tests-alpha

```
$ npm view create-cypress-tests-beta maintainers
dmtr.kovalenko <dmtr.kovalenko@outlook.com>
$ npm view create-cypress-tests-alpha maintainers
dmtr.kovalenko <dmtr.kovalenko@outlook.com>
```

These npm packages link to back to https://github.com/cypress-io/cypress and the source for `create-cypress-tests` has now been removed.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I deprecated the package: https://www.npmjs.com/package/create-cypress-tests
> 
> Going to wait a bit to unpublish I think since I don't want to unknowingly break some dependency.

Deprecation is a good first step.

> We don't have access to [npmjs.com/package/create-cypress-tests-beta](https://www.npmjs.com/package/create-cypress-tests-beta) or [npmjs.com/package/create-cypress-tests-alpha](https://www.npmjs.com/package/create-cypress-tests-alpha) to unpublish. They're not owned by our organization or any of our team.

I've pinged the owner in the previous post.

**Comment by MikeMcC399** [comment]
I'm going to close this issue following on from the deprecation:

```text
$ npm view create-cypress-tests deprecated
Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

This is sufficient warning for users of [create-cypress-tests](https://www.npmjs.com/package/create-cypress-tests) belonging to the very low number of weekly downloads (28).

It is left up to @dmtrKovalenko if he will deprecate or unpublish [npmjs.com/package/create-cypress-tests-beta](https://www.npmjs.com/package/create-cypress-tests-beta) and [npmjs.com/package/create-cypress-tests-alpha](https://www.npmjs.com/package/create-cypress-tests-alpha). The package names (including `beta` & `alpha`) are also enough warning about the support level of the packages.
