### ISSUE TITLE
Improve scaffolding

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#285]
New rules:

* Stop scaffolding every time by default
* Only scaffold when project is new
* Do not scaffold if `integrationFolder` option has been modified in cypress.json

This will prevent having to pass `integrationFolder: false`, etc.

Take into account that `config.integrationFolder` may have value, but the folder at that path may not exist.

**Comment by brian-mann** [comment]
Fixed in [`0.18.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0180-11272016).
