### ISSUE TITLE
Cypress doesn't like parenthesis () in filename

### ISSUE THREAD

**Issue by kazakevich-alexei** [cypress-io/cypress#28509]
### Current behavior

  > E:\Work_galaktika\TMS.Agent.Cypress\tms.agent.cypress\cypress\e2e\Наличие в поисковиках\YandexSearch_CorpGal().cy.js
PS E:\Work_galaktika\TMS.Agent.Cypress\tms.agent.cypress> npx cypress run --spec "cypress/e2e/Наличие в поисковиках/YandexSearch_CorpGal().cy.js"

DevTools listening on ws://127.0.0.1:4846/devtools/browser/c773b362-8b8a-40e9-8f8a-5e06968b6350
Can't run because no spec files were found.

We searched for specs matching this glob pattern:
 > E:\Work_galaktika\TMS.Agent.Cypress\tms.agent.cypress\cypress\e2e\Наличие в поисковиках\YandexSearch_CorpGal().cy.js

[Cypress_Debug_log_error.txt](https://github.com/cypress-io/cypress/files/13649432/Cypress_Debug_log_error.txt)

### Test code to reproduce

test file with parenthesis () in filename
execute command  npx cypress run --spec  "cypress/e2e/filename"

### Cypress Version

13.5.1

### Node version

18.16.1

### Operating System

windows 11

**Comment by jennifer-shehane** [comment]
This is specific to the `--spec` arg. In `cypress open` and `cypress run`, the test with the parenthesis in the filename will run, but it won't be found via the `--spec` arg.

<img width="397" alt="Screen Shot 2023-12-12 at 1 30 09 PM" src="https://github.com/cypress-io/cypress/assets/1271364/4d3cd3d5-bab5-4d5f-9d6c-99180a9926a7">

<img width="840" alt="Screen Shot 2023-12-12 at 1 31 16 PM" src="https://github.com/cypress-io/cypress/assets/1271364/ec6328d8-1c56-4aac-85ea-c3e8856a0dbb">

![Screen Shot 2023-12-12 at 1 31 39 PM](https://github.com/cypress-io/cypress/assets/1271364/6de4eb8a-2bf0-48bb-b150-6fb3821ce890)

It's also specific to the presense of both an opening and closing parenthesis and not the presense of a single paren. 
<img width="700" alt="Screen Shot 2023-12-12 at 1 33 55 PM" src="https://github.com/cypress-io/cypress/assets/1271364/ca5077f7-4a04-40d8-b0b7-382b50db6cff">

**Comment by jennifer-shehane** [comment]
This will run if you escape the paren in the --spec arg. I think it's trying to read a glob. 

```
cypress run --spec cypress/e2e/2-advanced-examples/File\().cy.js
```
