### ISSUE TITLE
stuck on waiting processes

### ISSUE THREAD

**Issue by huseyin-tumer** [cypress-io/cypress#28507]
### Current behavior

Tests pauses (not pause icon, I mean tests stuck, browser is not frozen) don't continue when cy.wait or cy.request command.

### Test code to reproduce

cy.wait command or cy.request command

### Cypress Version

13.6.1

### Node version

20.10.0

### Operating System

macOS Ventura 13.6

**Comment by jennifer-shehane** [comment]
@huseyin-tumer We'll need more information to reproduce this issue since this does not occur for other projects. Please provide a reproducible example or we will need to close the issue since we can't investigate.

**Comment by huseyin-tumer** [comment]
> @huseyin-tumer We'll need more information to reproduce this issue since this does not occur for other projects. Please provide a reproducible example or we will need to close the issue since we can't investigate.

it sometimes stops on before, not continue with test

ex script:
```
before(() => {
        cy.request({method: 'post', url: '', body: {}})
    })


    it('a test', () => {
        cy.request({method: 'post', url: '', body: {}})
        cy.request({method: 'get', url: '', body: {}})
    })
```
