### ISSUE TITLE
Cypress freezes on MacOS Sonoma

### ISSUE THREAD

**Issue by alxndrpro** [cypress-io/cypress#28519]
### Test code to reproduce
```js
/// <reference types="Cypress" />

describe('Cypress E2E Testing Demo', () => {
  it('Assert URL', () => {
    cy.visit('https://example.com')
    cy.url().should('contain', 'example.com')
  })

  it('Assert Title', () => {
    cy.visit('https://example.com')
    cy.title().should('contain', 'Example Domain')
  }
  
  
  
  )
})
```
### Cypress Mode

cypress open

### Cypress Version

13.6.1

### Browser Version

Electron 14

### Node version

21.4

### Operating System

Sonoma 14.1.2

### Other

<img width="410" alt="image" src="https://github.com/cypress-io/cypress/assets/75493574/b7785c8d-f556-4b51-bb02-b18f266fae41">

**Comment by jennifer-shehane** [comment]
@alxndrpro Hmm, we haven't had this freezing reported for anyone else on Sonoma. There is this [hanging issue](https://github.com/cypress-io/cypress/issues/28459) in 13.6.0+, but it doesn't cause the process to freeze like this. 

Is there any improvement when using other versions of Cypress?

**Comment by alxndrpro** [comment]
Hi! I've tried v13.6.0 and v13.5.0

No improvement.

I've ran 'npx cypress open' (tried both from VS Code terminal, and OS terminal), and after choosing configured Electron v114 the workspace opens next and after 10-15 seconds it freezes like this.

So far that simple sample project I have and plugin 'prettier' installed, nothing more.

**Comment by steveatkoan** [comment]
Not sure if its related, but Cypress 13.6.0 and above hang when hot reloading. The test runs fine first time, but if I change the code or test script, Cypress hangs when it tries to auto re-run the test and I need to force quit cypress and restart. 13.5.1 works fine.
Mac OS Sonoma, testing in Chrome, Vue + Vuetify project. All packages updated to latest except vite is 4.5.1

**Comment by jennifer-shehane** [comment]
@steveatkoan It looks like you're likely encountering this issue: https://github.com/cypress-io/cypress/issues/28392

You could downgrade to 13.5.1 or follow [these steps](https://github.com/cypress-io/cypress/issues/28392#issuecomment-1852735772) to get around the issue in our newer version.

**Comment by steveatkoan** [comment]
thanks. that solved my problem. much appreciated
