### ISSUE TITLE
Response 404 for random endpoints 

### ISSUE THREAD

**Issue by gustawx** [cypress-io/cypress#28555]
### Current behavior

Hello Cypress team and community,

I face strange problem where during execution in GitLab pipeline some of the tests fail and responses to all API requests return 404 with following details:

```
"Response Body": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST {my url here}</pre>\n</body>\n</html>\n",
  "Response Headers": {
    "content-security-policy": "default-src 'none'",
    "content-type": "text/html; charset=utf-8",
    "date": "Tue, 19 Dec 2023 12:36:23 GMT",
    "server": "nginx",
    "x-content-type-options": "nosniff",
    "x-powered-by": "Express",
    "content-length": "212",
    "connection": "keep-alive"
  },
  "Response Status": 404
```

and now some details:
I have a set of API tests, the problem occurrs quite rarely, maybe once every 2 weeks. It never occur for all tests, always tests are running fine then 5-8 test specs fail in a row with responses 404 for all requests and then it goes to "normal" state back again.

I don't start any server nor proxy, my services are deployed in AWS and these requests are not reaching them at all so problem occurs before. Actually because I don't run any other server the idea I have is Cypress. The request I send is a "normal" cy.request()

This issue started to occur quite recently (~1,5 month ago), I'm not sure but could be after upgrade to 13.5.0

So here is the question:
does this response that I got (above) may be returned by Cypress "internals".

Thank you very much for any help.

### Test code to reproduce

just simple cy.request({...}), I can't Include full code here

### Cypress Version

13.5.0

### Node version

18.16.1

### Operating System

docker image cypress/base:18.16.1

**Comment by jordanpowell88** [comment]
@gustawx I'm sorry to hear you are having issues. Can you provide an example repo of this happening so we can investigate further?

**Comment by gustawx** [comment]
@jordanpowell88 sorry for late response. I missed your comment.
I can't share the repo, it belong's to the company I work for, however this issue occurred again recently.

**Comment by jennifer-shehane** [comment]
We'll need some way to reproduce in order for us to investigate. There could be a lot of causes.
