### ISSUE TITLE
Chrome for Testing - we can't run your tests

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#28554]
### Current behavior

`npx cypress run --browser ~/chrome120/chrome --headed --no-exit`

![image](https://github.com/cypress-io/cypress/assets/5721147/7040cbd8-37e2-4822-a015-b2f812890fc7)
![image](https://github.com/cypress-io/cypress/assets/5721147/475598f4-f8a8-484a-87e9-59480ba8e3fa)

Chrome for Testing version: **120.0.6099.109** from https://alexsch01.github.io/chromefortesting/
- I am using https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-linux64.zip

### Test code to reproduce

cypress/e2e/spec.cy.js
```
$ mkdir cypress
$ mkdir cypress/e2e
$ touch cypress/e2e/spec.cy.js
```

---
cypress.config.js
```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
	e2e: {
		supportFile: false,
	},
})
```

### Cypress Version

13.6.1 **See **Other**

### Node version

v20.10.0

### Operating System

Linux 6.1.60 x86_64 GNU/Linux

### Other

Same result testing with Cypress Version=10.0.0

**Comment by alexsch01** [comment]
Related: https://github.com/cypress-io/cypress/issues/28123

Definitely caused by the `browser.majorVersion` being equal to "for"
```
{
  name: 'chrome',
  family: 'chromium',
  channel: 'stable',
  displayName: 'Custom Chrome',
  version: 'for',
  path: 'PATH TO Chrome for Testing',
  minSupportedVersion: 64,
  majorVersion: 'for'
}
```

This allows user to launch browser with cypress open

```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      config.browsers.push({
        name: 'chrome',
        family: 'chromium',
        channel: 'stable',
        displayName: 'Custom Chrome',
        version: 'for',
        path: 'PATH TO Chrome for Testing',
        minSupportedVersion: 64,
        majorVersion: '120',
      })
      return config
    },
  },
});
```

**Comment by MikeMcC399** [comment]
@alexsch01 

I was able to reproduce your issue on Ubuntu 22.04.

Cypress running under Windows 11 does not have a problem to test using Chrome for Testing, and the name of the browser is parsed differently:

![image](https://github.com/cypress-io/cypress/assets/66998419/4e66ea23-8a4a-45dd-8280-4766daf8eb0e)

So it seems you have put your finger on the cause of the issue on Linux when you note that the browser name and version is incorrectly parsed.

Compare to Ubuntu where the version number is missing

![image](https://github.com/cypress-io/cypress/assets/66998419/30f39d47-5759-48e7-b6f2-6b8ac6e4fd37)

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/cypress/pull/28243 would resolve this issue. Using this branch I was able to successfully run Cypress tests under Ubuntu 22.04 using Chrome for Testing `r120.0.6099.109` installed with `npx @puppeteer/browsers install chrome@stable`

**Comment by alexsch01** [comment]
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      config.browsers.push({
        name: 'cft',
        family: 'chromium',
        channel: 'stable',
        displayName: 'Custom Chrome',
        version: 'for',
        path: 'PATH TO Chrome for Testing',
        minSupportedVersion: 64,
        majorVersion: '120',
      })
      return config
    },
  },
});
```

With the above, you can use `npx cypress run --browser cft` and it will launch correctly
- so it's not just for cypress open

**Comment by alexsch01** [comment]
Still happening

**Comment by MikeMcC399** [comment]
- The related PR https://github.com/cypress-io/cypress/pull/28243 has made no progress for many months

**Comment by Roemer** [comment]
Pitty, I am now running into the same issue.

**Comment by lancefaler** [comment]
I am running into this issue as well.

**Comment by MikeMcC399** [comment]
This issue prevents using [browser-actions/setup-chrome](https://github.com/browser-actions/setup-chrome)  in GitHub Actions to install an alternate version of Chrome, since the action installs Chrome for Testing, which fails to run with Cypress.
