### ISSUE TITLE
Cypress opening full screen view in wrong Chrome Window

### ISSUE THREAD

**Issue by UglyHobbitFeet** [cypress-io/cypress#28579]
### Current behavior

I have a Chrome Window running with x number of tabs (Ex: google, stackoverflow, etc). I will refer to this below as my **OLD** Chrome Window

I run the following command in a terminal:
cypress: open

It brings up a cypress app that allows me to choose a browser. I choose Chrome (via 'Select E2E testing in Chrome' button)

Cypress then opens a **NEW** Chrome Window

I then click on the 'Specs' tab and execute my tests. The right-side of the screen shows an embedded browser with URL at top.

If I click on the URL in the embedded browser, cypress opens the embedded browser content in my **OLD** Chrome Window.  My **OLD** Chrome window does not have the test content/context (aka loaded json files, etc) and is useless to me.  I cannot get the URL to open in the **NEW** Chrome window that Cypress spawned when I clicked the 'Select E2E testing in Chrome' button.

This used to work fine (opened in the **NEW** Chrome Browser) from Cypress v12.17.4 up until v13.3.0
testing with v13.4.0 it still worked but took exponentially longer to load the tab with the data (minutes vs seconds)
testing with v13.5.0 it opened in the **NEW** browser as expected but with no data (didn't load fixtures etc)
testing with v13.6.1 it opened in the **OLD** browser and with no data

FWIW I have Chrome v120

### Desired behavior

That the behavior I saw in v12.17.4/v13.3.0 would still exist in v13.6.1 where opening the embedded browser URL would launch the tab in the cypress spawned Chrome window instead of my own personal Chrome tab window

### Test code to reproduce

Shown in description above

### Cypress Version

13.6.1

### Node version

v16.20.2

### Operating System

CentOS7

### Debug Logs

```shell
N/A
```

**Comment by jennifer-shehane** [comment]
We changed this behavior intentionally. We do not recommend manually opening new tabs in Cypress as it could interfere with tests. Additionally we close tabs between tests now. If you want to test something in a new browser window, you could utilize our [cypress/puppeteer](https://github.com/cypress-io/cypress/tree/develop/npm/puppeteer) plugin.

**Comment by UglyHobbitFeet** [comment]
@jennifer-shehane 

Unfortunately, the puppeteer plugin is not what I'm looking to do.  I have
a suite of cypress tests. After I run cypress (and ALL tests have completed) I like to
open the latest state in a separate tab and navigate around.  The cypress
tests set up a bunch of mocked up endpoints, which I would not have
available otherwise. If clicking on the test now opens it in a completely
separate window from where cypress launched (Note: different window,
instead of same window but different tab) I lose the functionality to
navigate around AFTER tests have completed because the mocked up endpoints 
don't exist in that browser window.

Is there any way to restore that functionality as it is extremely useful.

Thanks!
