### ISSUE TITLE
cy.now('task', ...) is not working anymore if cy.state('current') is null

### ISSUE THREAD

**Issue by KleaTech** [cypress-io/cypress#28575]
### Current behavior

The code below is not working, `cleanUpRepositories` is not getting called.
```
Cypress.on('test:after:run', async () => {
    await cy.now('task', 'cleanUpRepositories');
});
```
Instead an error is received: `Cannot read properties of null (reading 'get')`.
So even though this usecase might not be supported, it was not handled gracefully and was difficult to debug.

### Desired behavior

The code above was working previously, eg. on `v12.8.1`.

Suggested solutions:
- make it work again as it was working previously
- fail gracefully with a straight forward error message
- provide an official way for this usecase as it was requested in #6316

### Test code to reproduce

As seen above.

### Cypress Version

12.17.4

### Node version

v18.15.0

### Operating System

macOS 14.2

### Debug Logs

```shell
I tried to run Cypress with DEBUG mode, but got no meaningful messages.
```

### Other

Issue probably comes from https://github.com/cypress-io/cypress/blob/d6f356f561a5ebdc42ee80632c2daf6990760c9d/packages/driver/src/util/privileged_channel.ts#L24C55-L24C55

I checked cy.state('current') and it was null.

**Comment by jennifer-shehane** [comment]
`cy.now` and `cy.state` were never documented as official APIs within Cypress and are no longer supported.
