### ISSUE TITLE
Unable to Run Tests in Cypress Test Runner - No Response on Clicking Tests

### ISSUE THREAD

**Issue by artbajrami** [cypress-io/cypress#28587]
### Current behavior

When using Cypress Test Runner, clicking on any test script does not initiate the test run.
After selecting a browser (like Chrome) and clicking on a specific test file, there is no response - the test does not start, and there are no visible changes or error messages in the Cypress UI.
This issue persists across different test files.
No relevant error messages are observed in the developer console, except for a 404 error for a source map file (unrelated).

### Desired behavior

Clicking on a test script in the Cypress Test Runner should start the execution of the test.
The Cypress Test Runner should respond appropriately to interactions and provide feedback or error messages if a test cannot be run.

### Test code to reproduce

Open Cypress using npx cypress open.
Select a browser to run the tests.
Click on any test script in the Cypress Test Runner.
Observe the lack of response or test execution.

### Cypress Version

13.6.1

### Node version

21.2.0

### Operating System

Windows 11 - 22H2

**Comment by jennifer-shehane** [comment]
@artbajrami Can you provide an example of a project where this behavior happens? Are there any errors in devTools when you click on the spec if you open them? I haven't heard of this issue before.

**Comment by artbajrami** [comment]
Hi @jennifer-shehane  thank you for responding and sorry for late reply.

This issue is happening each time I try to run  the scripts on browser because on the terminal they all are running as it's expected. 

On terminal I see this error:

GET /__cypress/runner/escape.js.map 404 0.593 ms - 136 

On browser:
Devtools failed to load source map: Could not load content for httP://localhost:59246/cypress/escape.js.mapp: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

If you need more details please let me know. I can't still figure out how to resolve this issue.

**Comment by jennifer-shehane** [comment]
@artbajrami Could you provide some screenshots or video of what you're seeing?
