### ISSUE TITLE
Problem with json-server

### ISSUE THREAD

**Issue by ifarnami** [cypress-io/cypress#28584]
### Current behavior

Hi there, i have a simple todo app using vanilla js and i connected my app to json-server, when running cypress, it's like cypress is not connecting to json-server at all, it doesnt send any response and it just fails.
This is what is expected to be in document by default(the task is stored in databse by default and on document load it should be rendered)
![normal](https://github.com/cypress-io/cypress/assets/66572957/6cce7845-c8e6-43d5-9f17-cce11917d6c3)
Running json-server:
![json-server](https://github.com/cypress-io/cypress/assets/66572957/13161d0b-418c-42f0-972b-7fb7010f1172)
Failed test case:
![test](https://github.com/cypress-io/cypress/assets/66572957/654029c0-e4a4-405c-8066-7f5d0ecc14ce)
Network tab in console when test is running:
![console](https://github.com/cypress-io/cypress/assets/66572957/ddd9cad5-621a-4953-a391-dbed4895da06)

### Desired behavior

In this situation cypress should show default task when visiting the document
![normal](https://github.com/cypress-io/cypress/assets/66572957/10b29cb3-d15f-41f3-bae4-3209793fdca8)

### Test code to reproduce

```javascript  
it("Should render previous task from server on page load", () => {
    cy.getByTestId("todosContainer").contains(/Saved task on server/i);
  });
```

### Cypress Version

7.7.0

### Node version

v 20.10.0

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment]
@ifarnami Can you provide a repo that reproduces the issue using simple json-server for us to recreate?

**Comment by ifarnami** [comment]
@jennifer-shehane unfortunately the project is private and i don't have permission to share it, but i will create a demo of the problem, thank you so much for responding to this issue
