### ISSUE TITLE
Cypress crashes for test runtime more than 5-10 minutes

### ISSUE THREAD

**Issue by abhisheksiddhu** [cypress-io/cypress#2858]
### Current behavior:

For long running tests cypress is crashing, this is happening pretty frequently, once every hour or so

### Desired behavior:

No crashing, it was working, in earlier versions for the same set of tests

### Steps to reproduce:

It's possibly due to a memory leak, as i get this error when the dev tools are open in cypress runner.

![](https://lh6.googleusercontent.com/ankCm23P2WRzdd2pig56_Vlb0ZB7Kp18W_obXux4Rgm7f7M-ZNYKAPGYLynDz5mC1R66gNViLBOIaxUSp67v=w3356-h1834-rw)

### Versions

Operating System: macOS Mojave
Cypress version: 3.1.2

**Comment by jennifer-shehane** [comment]
Could you provide a reproducible example of this crash? Unfortunately we'll have to close this issue if no reproducible example is provided.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
