### ISSUE TITLE
Get the selector of the specified element on the GUI runner

### ISSUE THREAD

**Issue by ay5399** [cypress-io/cypress#28596]
### What would you like?

I want to get the selector of a specified element on the GUI runner.
It is even better if it can be obtained using multiple patterns such as ID and data-* selector.

### Why is this needed?

・ I want to check if there is an error in the selector when an error occurs during the test.
・I want to get the ID of the element when implementing it. When you try to refer to it with developer tools, it is difficult to check the ID of the element inside the iframe.

**Comment by jennifer-shehane** [comment]
@ay5399 Have you looked at using [Cypress Studio](https://docs.cypress.io/guides/references/cypress-studio#__docusaurus_skipToContent_fallback) or our [Selector Playground](https://docs.cypress.io/guides/core-concepts/cypress-app#Selector-Playground)?

**Comment by ay5399** [comment]
@jennifer-shehane 
sorry. I used Cypress Studio, but I didn't know about Selector Playground. It's exactly the feature I was looking for. thank you. I fell in love with Cypress again.

**Comment by emilyrohrbough** [comment]
@ay5399 that is great news!
