### ISSUE TITLE
The app redirects the user to the wrong path.

### ISSUE THREAD

**Issue by tudorgabriel** [cypress-io/cypress#28599]
### Current behavior

The app redirects me on the wrong path after cy. visit and the engine returns 404 not found

Steps : 
Create a basic test file
Start with cy. visit(https://wallet.multiversx.com/unlock)

Actual result : 

![image](https://github.com/cypress-io/cypress/assets/19550143/182c1547-e64b-4943-a5b6-1bc6b918ff93)

### Desired behavior

The app should access the URL from cy.visit and start the test

### Test code to reproduce

describe('test', () => {
  it('should', () => {
    cy.visit('http://wallet.multiversx.com/unlock');
  });
});

### Cypress Version

13.3.0

### Node version

16.20.2

### Operating System

macOS 14.2.1

**Comment by jennifer-shehane** [comment]
@tudorgabriel I think this may be a manifestation of this issue. https://github.com/cypress-io/cypress/issues/25891 I saw it load the first time I visited - and subsequent loads are trying to upgrade to `https` on the main window which is 404'ing...... I'm not sure why the inifite load wouldn't happen here though.
