### ISSUE TITLE
Cypress Hangs only on jenkins with version 9.7

### ISSUE THREAD

**Issue by vzvijay** [cypress-io/cypress#28597]
### Current behavior

20:14:09  2023-12-27T14:44:09.452Z cypress:server:task result is: null
20:14:12  2023-12-27T14:44:11.944Z cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
20:14:12  ┌─────────┬───────────────────┬──────────────┬───────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
20:14:12  │ (index) │       group       │ processCount │                         pids                          │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
20:14:12  ├─────────┼───────────────────┼──────────────┼───────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
20:14:12  │    0    │     'Chrome'      │      8       │ '1951, 1956, 1957, 1959, 1976, 1961 ... 2 more items' │    7.57    │      6.94      │ 1890.58  │   1416.87    │   1917.25   │
20:14:12  │    1    │     'plugin'      │      1       │                        '1922'                         │    0.02    │      0.38      │  461.64  │    374.55    │    476.9    │
20:14:12  │    2    │     'cypress'     │      1       │                        '32732'                        │    0.47    │      1.03      │  218.33  │    223.94    │   244.42    │
20:14:12  │    3    │ 'electron-shared' │      4       │              '1718, 32734, 1763, 32735'               │     0      │       0        │  174.52  │    173.13    │   174.52    │
20:14:12  │    4    │      'other'      │      2       │                    '21654, 21663'                     │     0      │       0        │   3.89   │     3.96     │    4.12     │
20:14:12  │    5    │      'TOTAL'      │      16      │                          '-'                          │    8.05    │      8.23      │ 2748.96  │    2164.9    │   2787.85   │
20:14:12  └─────────┴───────────────────┴──────────────┴───────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘
20:14:13  2023-12-27T14:44:13.032Z cypress:server:request aborting { requestId: 'request1963' }
20:14:13  2023-12-27T14:44:13.032Z cypress:server:request aborting { requestId: 'request1964' }
20:14:13  2023-12-27T14:44:13.033Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51946 }
20:14:14  2023-12-27T14:44:13.757Z cypress:server:request aborting { requestId: 'request1965' }
20:14:14  2023-12-27T14:44:13.757Z cypress:server:request aborting { requestId: 'request1966' }
20:14:14  2023-12-27T14:44:13.758Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51952 }
20:14:17  2023-12-27T14:44:16.711Z cypress:launcher chrome stderr: <--- Last few GCs --->
20:14:17  
20:14:17  [1980:0x3ed700000000]   673989 ms: Scavenge 1664.4 (1701.6) -> 1656.7 (1701.6) MB, 0.6 / 0.0 ms  (average mu = 0.998, current mu = 0.993) allocation failure 
20:14:17  [1980:0x3ed700000000]   673998 ms: Scavenge 1664.4 (1701.6) -> 1656.7 (1701.6) MB, 0.7 / 0.0 ms  (average mu = 0.998, current mu = 0.993) allocation failure 
20:14:17  [1980:0x3ed700000000]   674007 ms: Scavenge 1664.4 (1701.6) -> 1656.7 (1701.6) MB, 0.6 / 0.0 ms  (average mu = 0.998, current mu = 0.993) allocation failure 
20:14:17  
20:14:17  
20:14:17  <--- JS stacktrace --->
20:14:17  2023-12-27T14:44:16.999Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 49034 }
20:14:22  2023-12-27T14:44:22.424Z cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
20:14:22  

### Desired behavior

Should work without hanging

### Test code to reproduce

Try with version 9.7.0 in headless mode on jenkins

### Cypress Version

9.7.0

### Node version

16.20.0

### Operating System

linux

**Comment by jennifer-shehane** [comment]
@vzvijay We've fixed several issues since 9.7.0 and we do not patch back versions for fixes. We recommend you try upgrading to resolve the hanging.
