### ISSUE TITLE
Execution Terminated on Windows

### ISSUE THREAD

**Issue by zubairrshahidd** [cypress-io/cypress#28592]
### Current behavior

I have a tabular page where data is listed in multiple columns.
The table test data verification part involves multiple Horizontal and vertical scrolls.
On a Mac machine, this verification runs smoothly. Execution time is 14 mins.
But on Windows machines, the browser crashes due to which execution terminates/stuck.
I have not been able to find any error since the browser crashed. Tested on Chrome and Electron browser.minutes
![Uploading Screenshot 2023-12-27 at 1.37.40 PM.png…]()

### Desired behavior

Since this execution never fails on a Mac machine, so its should run smoothly on a Windows machine also.
I am not sure what could be the issue that is causing this crash on the Windows browser.

### Test code to reproduce

- 

### Cypress Version

13.1.5

### Node version

v20.10

### Operating System

Windows 11 Pro

**Comment by jennifer-shehane** [comment]
@zubairrshahidd Your screenshot did not upload for me to view. 

Is this occurring during `cypress open` or `cypress run`?

Could you try updating to the latest version of Cypress to see if this resolves the issue?

Please provide a way for us to run and reproduce the issue.

**Comment by zubairrshahidd** [comment]
<img width="1471" alt="Screenshot 2023-12-27 at 1 37 40 PM" src="https://github.com/cypress-io/cypress/assets/33728786/4e08d108-144e-41e0-b74a-e5aa292f3a38">

I hope the picture is visible to you now.

**Comment by zubairrshahidd** [comment]
<img width="1463" alt="Screenshot 2023-12-27 at 11 44 16 PM" src="https://github.com/cypress-io/cypress/assets/33728786/f128a1e1-0b4a-4799-9b52-d4ab174ed56d">
I hope the picture is visible to you now

**Comment by jennifer-shehane** [comment]
@zubairrshahidd Could you try updating to the latest version of Cypress to see if this resolves the issue?

Please provide a way for us to run and reproduce the issue.
