### ISSUE TITLE
Remove magic support folder script handling

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#286]
* Remove cypress.json `supportFolder` option
* Add `supportScripts` cypress.json option
  - Creates separate script bundle(s) that is/are included before the spec file bundle
  - Can be a string or an array of strings
  - Each string can be path to file or glob pattern
  - If does not exist, error on project boot
    * This will catch current users that need to transition
    * Tell user they need to create `support/index.(js|coffee)` or explicitly set `supportScripts` option
    * Tell user they can disable with `supportScripts: false`
    * Link user to error docs for this message

**Comment by brian-mann** [comment]
Fixed in [`0.18.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0180-11272016).
