### ISSUE TITLE
Cypress - Cookies not transmitted to other tabs upon submitting my form.

### ISSUE THREAD

**Issue by FabienBounoir** [cypress-io/cypress#28600]
### Current behavior

When I click a button, it creates a hidden form to open another tab and download a file. Currently, during testing with Cypress, the new tab opens successfully; however, the cookies are not passed, and consequently, the API prompts me to log in again.
![image](https://github.com/cypress-io/cypress/assets/71253960/8b05ccc5-9e13-46b4-b652-4430d37bc56d)

### Desired behavior

The desired behavior would be for the cookies to be passed to the new tab, enabling the direct download of the file.

### Test code to reproduce

```
cy.visit('/file?filename=test.txt')
    cy.contains('download').click()
    const downloadsFolder = Cypress.config('downloadsFolder')
    cy.readFile(path.join(downloadsFolder, 'test.txt')).should('exist')
```

### Cypress Version

13.6.2

### Node version

v18.17.1

### Operating System

Ubuntu 22.04 LTS

### Debug Logs

```shell
AssertionError
Timed out retrying after 4000ms: cy.readFile("/home/fabien/Git/project/cypress/downloads/test.txt") failed because the file does not exist at the following path:



/home/fabien/Git/project/cypress/downloads/test.txtLearn more
cypress/e2e/project/file-download/file-download.cy.ts:25:1
  23 |         cy.contains('download').click();
  24 |         var downloadsFolder = Cypress.config('downloadsFolder');
> 25 |         cy.readFile(path.join(downloadsFolder, 'test.txt')).should('exist');
     | ^
  26 |     });
  27 |     afterEach(function () {
  28 |         cy.visit('/file?filename=test.txt');
```
```


### Other

_No response_

**Comment by jennifer-shehane** [comment]
@FabienBounoir Cypress does not support interaction with other tabs out of the box, so things like cookies are not persisted.

You can try using our beta [cypress/puppeteer plugin](https://github.com/cypress-io/cypress/tree/develop/npm/puppeteer) to interact with other tabs, but you would have to juggle the cookies over and set them in the new tab that way.
