### ISSUE TITLE
cypress run produces error resize:  can't open terminal /dev/tty if started via ssh or cronjob on linux

### ISSUE THREAD

**Issue by FrankL-git** [cypress-io/cypress#28612]
### Current behavior

Running the following command (for easy reproduction I use an empty empty.spec.ts) on bash:

    $ hostname
    arnika
    $ cd /home/fl/project_dir && npx cypress run -b firefox --spec /home/fl/project_dir/cypress/e2e/empty.spec.ts

produces

    ...
    ================================================================================
    
      (Run Starting)
    
      │ Cypress:        13.6.2                                                                         │
      │ Browser:        Firefox 120 (headless)                                                         │
      │ Node Version:   v20.10.0 (/usr/bin/node)                                                       │
      │ Specs:          1 found (empty.spec.ts)                                                        │
      │ Searched:       cypress/e2e/empty.spec.ts                                                      │
  
    ...
    
      Running:  empty.spec.ts                                                                   (1 of 1)
    
      0 passing (2ms)
    ...

The same comand run via ssh:

    $ ssh arnika "cd /home/fl/project_dir && npx cypress run -b firefox --spec /home/fl/project_dir/cypress/e2e/empty.spec.ts"

produces

    ...
    resize:  can't open terminal /dev/tty
    tput: No value for $TERM and no -T specified
    ================================================================================
    
      (Run Starting)
    ...

The same two errormessages appear if cypress run is started via cronjob.

### Desired behavior

The two errormessages of resize resp. tput should not appear

### Test code to reproduce

see above

### Cypress Version

13.6.2

### Node version

v20.10.0

### Operating System

linux (Ubuntu - 22.04)

### Other

The error appears with chrome instead of firefox, too. As a workaround I set the three enviromentvariables TERM, COLUMNS and LINES as follows:

    $ ssh arnika "export TERM=xterm && export COLUMNS=80 && export LINES=80 && cd /home/fl/project_dir && npx cypress run -b firefox --spec /home/fl/project_dir/cypress/e2e/empty.spec.ts"

which let the error messages disappear. It seem's that the cypress run expects a terminal "connected" to the process.

**Comment by Costin10** [comment]
The error messages you are encountering (resize: can't open terminal /dev/tty and tput: No value for $TERM and no -T specified) indicate that the command being executed via SSH or cronjob expects to interact with a terminal, but it is not finding one.

**Comment by FrankL-git** [comment]
@Costin10 As I wrote: "cypress run expects a terminal "connected" to the process". The problem is that jobs started via ssh or cronjob don't have a terminal as you could verify with:

    $ ssh myhost tty
    not a tty
