### ISSUE TITLE
Upgrade Chai in non-driver packages

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#2863]
Chai was upgraded to 4.x in the driver #2529, we should upgrade it elsewhere as well.

[Chai migration guide](https://github.com/chaijs/chai/issues/781)

**Comment by lilaconlee** [comment]
Think this'll just be updating dev dependencies, so gonna remove breaking change/4.0 release but lemme know if that's wrong.

**Comment by jennifer-shehane** [comment]
Closing as stale
