### ISSUE TITLE
Cypress DashBoard : IS NOT RESPONSDING & will get Struck.

### ISSUE THREAD

**Issue by rajkubasad** [cypress-io/cypress#28645]
### Current behavior

I have installed cypress and opened (npx cypress open). while accessing dashboard it will get struck and will show not responding.
I have tried couple of times with multiple laptop. But same response.
Could you please help me to understand what's the issue is:

Node version: v18.16.0
cypress: latest version 

Please find the below screenshot:
![image](https://github.com/cypress-io/cypress/assets/55633029/1ae86d86-1d91-403d-8c83-df0dcc3e6c18)
![image](https://github.com/cypress-io/cypress/assets/55633029/5b1b6b07-123b-4349-97b8-b975e718fa73)
[cypressIssues.docx](https://github.com/cypress-io/cypress/files/13840870/cypressIssues.docx)

### Desired behavior

It should work as normal without any load.

### Test code to reproduce

Cypress initial generated code only

### Cypress Version

13.6.2

### Node version

v18.16.0

### Operating System

Windows 10 Pro 64 bit

### Debug Logs

```shell
PS C:\Users\ABC\Desktop\Cypress2024> npx cypress open


DevTools listening on ws://127.0.0.1:57459/devtools/browser/1cbcc8a5-27e8-4556-98be-856175f090a0
GET /__/ 200 8.566 ms - -
GET /__/assets/polyfills-93a39af8.js 200 47.178 ms - -
GET /__/assets/index-90d5d7af.css 200 3.843 ms - -
GET /__/assets/index-f74a2fdb.js 200 4.735 ms - -
GET /__cypress/runner/cypress_runner.css 200 3.893 ms - -
GET /__/assets/Specs-9520c76e.js 200 9.294 ms - 523
GET /__/assets/route-block-c0a8bdd8.js 200 7.546 ms - 45
GET /__/assets/InlineCodeFragment-c3583692.css 200 7.175 ms - 315
GET /__/assets/TrackedBanner.vue_vue_type_script_setup_true_lang-0c310c4b.js 200 6.489 ms - -
GET /__/assets/Index-8e09cf1c.js 200 12.449 ms - -
GET /__/assets/InlineCodeFragment.vue_vue_type_script_setup_true_lang-965f89ab.js 200 8.416 ms - -
GET /__/assets/box-open_x48-939815cc.js 200 5.205 ms - -
GET /__/assets/SpecPatterns.vue_vue_type_script_setup_true_lang-d8e0c8d1.js 200 4.588 ms - -
GET /__/assets/graphql-b2b2f6fa.js 200 9.535 ms - 535
GET /__/assets/SpecNameDisplay.vue_vue_type_script_setup_true_lang-242b47cd.js 200 9.420 ms - -
GET /__/assets/Index-401d105a.css 200 3.973 ms - -
GET /__/assets/PromoHeader.vue_vue_type_script_setup_true_lang-c308356e.js 200 4.612 ms - -
GET /__/assets/settings_x16-87f5c70e.js 200 7.874 ms - -
GET /__cypress/runner/cypress_runner.js 200 4.995 ms - -
GET /__/assets/cypress_s-29af549a.png 200 4.365 ms - 4425
GET /__/assets/electron-fb07f5cc.svg 200 11.861 ms - -
GET /__/assets/chrome-98045c79.svg 200 10.850 ms - -
GET /__/assets/edge-e54a3dc2.svg 200 5.370 ms - -
GET /__/assets/firefox-9be61e66.svg 200 1.948 ms - -
GET /avatar/32a03a56db901684612443f71d13ebda?size=48&default=mm 200 219.357 ms - -
```

**Comment by jennifer-shehane** [comment]
@rajkubasad Is this your first time using Cypress? Or did Cypress previously run for you before? Could you try a lower version of Cypress to see if that resolves the issue somehow? Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by rajkubasad** [comment]
Hi @jennifer-shehane,
No, it is not the first time, 
previously it was running fine. Just I have created the new folder then installed the cypress; This issue is occurring.

As per your suggestion I tried lower version.12.17.3 . Same response you can find in the below screenshot.
 
![image](https://github.com/cypress-io/cypress/assets/55633029/c0250f2b-362a-4ca4-baa2-77e3203fa799)

If I use npx cypress run in command line it is working fine but cypress dashboard is the problem
 
![image](https://github.com/cypress-io/cypress/assets/55633029/65ea24c9-9572-4335-ac31-ead9e10ad007)

**Comment by raj-kubasad** [comment]
Any Update on this @jennifer-shehane

**Comment by rajkubasad** [comment]
Hi @jennifer-shehane .
I tried all ways but not at all working. Could you please help me to resolve this?
It will be very helpful for me to do move forward.

![image](https://github.com/cypress-io/cypress/assets/55633029/a1dec028-a09e-4e16-8483-65b1308c03ef)

**Comment by jennifer-shehane** [comment]
@rajkubasad I'm not sure why this would be locking up. I'd assume Cypress is using a lot of CPU to lock up like this, is there some other running processes that may be interferring?

**Comment by rajkubasad** [comment]
Hi @jennifer-shehane , 

It's 8 GB RAM. and not running any background process also. Thanks,
