### ISSUE TITLE
Improve/fix event binding

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2865]
Currently, it's possible we bind to window events ('load', 'hashchange', etc) before users bind to them. 

We need to ensure better control over how/when we bind to window events, with the following requirements:

* We capture events even if a user cancels them / stops propagation of them.
  - We should be able to achieve this by injecting a handler into the capture phase
* We fire handlers users bind to in their test last
  - This way, they receive the final result of what their page's handlers do

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
