### ISSUE TITLE
When we run the Cypress command to open getting error as Error: EACCES: permission denied 

### ISSUE THREAD

**Issue by Yeshvk18** [cypress-io/cypress#28663]
### Current behavior

Have Properly Installed Node and checked the version as well which is quite perfect 

Problem Statement : Unable to Open the Cypress by using cypress commands -node_modules/.bin/cypress open

The version which i am using 13.6.2 

Error : 
```
An unexpected error occurred while verifying the Cypress executable.

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.
----------
Error: EACCES: permission denied, open '/Users/yeshwanthvankina/Library/Caches/Cypress/13.6.2/binary_state.json'
----------
Platform: darwin-arm64 (23.2.0)
Cypress Version: 13.6.2
```
### Desired behavior

Basically have clear Setup on Node Modules and did configuration successfully, 
Basically After creating the Package.json file post installing the Cypress when we try to Open the cypress it should get launch 

### Test code to reproduce

[package-lock.json](https://github.com/cypress-io/cypress/files/13868584/package-lock.json)

### Cypress Version

13.6.2

### Node version

v20.2.0

### Operating System

MACOS Sonoma 14.2.1

**Comment by oeem1011** [comment]
Same with version 12.7.4

**Comment by nathan-nusign** [comment]
Same with 13.6.3 (running on gitlab hosted runners). For what its worth, I started having this issue from one day to the next, with no change to my lock file.

**Comment by jennifer-shehane** [comment]
Typically this has to do with some permissions issue with these folders/files.

**Comment by catiarodriguescosta** [comment]
`sudo npx cypress open` worked for me!
