### ISSUE TITLE
forceNetworkError causes multiple requests

### ISSUE THREAD

**Issue by thril** [cypress-io/cypress#28679]
### Current behavior

When stubbing a network call using `cy.intercept` and forcing a network error, the request is being made 5 times instead of the expected _just 1_. I am unable to find any options which would prevent the retries.

```javascript
const url = "https://example.com";

describe("page", () => {
  it("fails", () => {
    let count = 0;
    cy.intercept("GET", url, (req) => {
      count++;
      console.info(`[${count}] requesting ${url}...`);
      req.reply({ forceNetworkError: true });
    }).as("stub");

    cy.visit(url);

    cy.wait("@stub");
  });
});
```

Along with the test body output showing 5 requests, you can see in the console that the request is made 5 times.

![5 requests](https://github.com/cypress-io/cypress/assets/484948/6d454b68-cc0c-4b7d-b19c-9c3a9455c5a5)

### Desired behavior

Don't make the request 5 times, but just once.

### Test code to reproduce

https://github.com/thril/cypress-test-tiny/tree/force-network-error

### Cypress Version

12.17.4

### Node version

v18.18.0

### Operating System

macOS 14.2.1

**Comment by thril** [comment]
Sigh

**Comment by jennifer-shehane** [comment]
`cy.visit` has an option for `retryOnNetworkFailure` that is set to `true` by default. 

>Whether Cypress should automatically retry transient network errors under the hood. Cypress will retry a request up to 4 times if this is set to true.

You can set this to false if you'd like to disable this behavior.
