### ISSUE TITLE
cy.saveHar is not a function | cypress-har-generator

### ISSUE THREAD

**Issue by zubairPlanera** [cypress-io/cypress#28677]
### Current behavior

**Description:**
Encountering an issue where the cy.saveHar function is not recognized in my Cypress setup, despite following the correct implementation steps.
**Environment:**

- Cypress version:  13.5.1
- Operating System: macOs Monterey
- Error Message: Cypress throws an error, stating that` cy.saveHar is not a function` when attempting to utilize it in the test file.

**Steps Taken:**

- Installed @neuralegion/cypress-har-generator as a development dependency.
- Updated cypress/plugins/index.js and cypress.config.js as per the plugin documentation.
- Registered commands in cypress/support/index.js.
- Implemented code in the test file to generate and save a HAR file.

**Additional Information:**

- Confirmed correct plugin installation.
- Cypress plugin setup appears to be correctly configured.
- cypress/support/index.js is properly set up.
- Other plugin functions (e.g., cy.recordHar()) are working as expected.

### Desired behavior

Expect cy.saveHar to be recognized as a valid Cypress command and save the generated HAR file.

### Test code to reproduce

describe.only('Project Creation', () => {

  let projectName

  before(() => {
    cy.viewport(viewportsize)
    cy.recordHar();
    cy.loginDevPlanera()
    projectName = createProjectPageConstant.generateProjectName()
  })
  
  after(() => {
    cy.logout();
    cy.saveHar();
    })

  it('TC1| Create Project, [Smoke-Test]', { tags: ['Smoke'] }, () => {
    cy.log('Project Creation Initiated')
    createCanvasObject.createProject(projectName)
    cy.log('Project Creation completed')

  })

})

### Cypress Version

13.5.1

### Node version

18.4.0

### Operating System

macOS  12.0

### Other

**Possible Solutions Attempted:**

- Restarted Cypress.
- Verified Cypress version compatibility.
- Checked and ensured correct plugin implementation based on documentation.

**Comment by zubairPlanera** [comment]
Any Update on this @jennifer-shehane @chrisbreiding

**Comment by jennifer-shehane** [comment]
@zubairPlanera I would suggest opening an issue or asking the plugin. We don't own this plugin. neuralegion/cypress-har-generato

Also, you can check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

Our issues are reserved for bugs in the cypress product, so this issue will be closed since it doesn't appear to be a clear bug with cypress.
