### ISSUE TITLE
Dynamic expressions in import() doesn't work

### ISSUE THREAD

**Issue by piothPaproKee** [cypress-io/cypress#28699]
### Current behavior

Parametrized dynamic import() doesn't work. Dynamic import with static path works fine tho.

I have a repo with cypress 8 and there the parametrized dynamic imports works. Stopped when i upgraded cypress.
I tested cypress 13 and cypress 12 and in both versions it doesn't work.

### Desired behavior

Dynamic expressions in import() should work.

### Test code to reproduce

Forked from template. More info in the readme
https://github.com/piothPaproKee/cypress-dynamic-import

### Cypress Version

13, 12

### Node version

20.10

### Operating System

ubuntu 20.04

### Debug Logs

![image](https://github.com/cypress-io/cypress/assets/90191473/9d2218a3-496b-41e1-86dd-813915553751)

### Other

Initially i started with the question: https://github.com/cypress-io/cypress/discussions/28620

But then i reproduced it on the sample cypress project, and it doesn't work there as well.

Thanks :)

**Comment by jennifer-shehane** [comment]
Which exact version did this used to work in in 8? I'm looking at version 8.0.0 and this error still displays from the project you provided.

<img width="754" alt="Screen Shot 2024-01-11 at 3 03 19 PM" src="https://github.com/cypress-io/cypress/assets/1271364/a0d221f9-a8f5-4999-a2ec-799112901fd1">

**Comment by piothPaproKee** [comment]
Indeed. It's not an issue with cypress, but with typescript >4.9.1. Dynamic import doesn't work as expected there (for `module: 'commonjs'`) https://github.com/webpack/webpack/issues/16793 

thanks for the fast reply, closing.
