### ISSUE TITLE
Python 3.12 build error "No module named 'distutils'"

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28695]
### Current behavior

Executing `yarn` to build Cypress from source causes build errors when using the current version of [Python](https://www.python.org/) `3.12.1`. The following npm modules are affected:

- [registry-js](https://www.npmjs.com/package/registry-js)
- [cpu-features](https://www.npmjs.com/package/cpu-features)

The error messages include the following line caused by a breaking change in Python `3.12` which is incompatible with the version of `node-gyp` currently used by Cypress:

> ModuleNotFoundError: No module named 'distutils'

### Desired behavior

[CONTRIBUTING > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) should correctly list working prerequisites. The current text says:

- [`python`](https://www.python.org/downloads/) (since we use `node-gyp`. See their [repo](https://github.com/nodejs/node-gyp) for Python version requirements.)
  - Note for Debian-based systems: `python` is pre-installed.<br>`sudo apt install g++ make cmake` meets the additional requirements to run `node-gyp` in the context of building Cypress from source.

The text should be changed to state that Python `3.11` is the highest version compatible with Cypress install / build from source.

### Test code to reproduce

See https://github.com/MikeMcC399/cypress/blob/prime/.github/workflows/build-test.yml

### Cypress Version

`13.6.2` develop branch https://github.com/cypress-io/cypress/commit/9e1f1e77416cb262ef121d1595cc4c5d2ba0334c

### Node version

`18.15.0`

### Operating System

Ubuntu 22.04 and Windows 2022

### Debug Logs

```shell
[5/6] Building fresh packages...
warning Error running install script for optional dependency: "/home/runner/work/cypress/cypress/node_modules/@cypress/get-windows-proxy/node_modules/registry-js: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /home/runner/work/cypress/cypress/node_modules/@cypress/get-windows-proxy/node_modules/registry-js
info This module is OPTIONAL, you can safely ignore this error
Output:
prebuild-install WARN install No prebuilt binaries found (target=18.15.0 runtime=node arch=x64 libc= platform=linux)
Traceback (most recent call last):
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py\", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 9, in <module>
    import gyp.input
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.2.0-1018-azure
gyp ERR! command \"/opt/hostedtoolcache/node/18.15.0/x64/bin/node\" \"/home/runner/work/cypress/cypress/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/runner/work/cypress/cypress/node_modules/@cypress/get-windows-proxy/node_modules/registry-js
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok"
warning Error running install script for optional dependency: "/home/runner/work/cypress/cypress/node_modules/registry-js: Command failed.
Exit code: 1
info This module is OPTIONAL, you can safely ignore this error
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /home/runner/work/cypress/cypress/node_modules/registry-js
Output:
prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc= platform=linux)
Traceback (most recent call last):
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py\", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 9, in <module>
    import gyp.input
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.2.0-1018-azure
gyp ERR! command \"/opt/hostedtoolcache/node/18.15.0/x64/bin/node\" \"/home/runner/work/cypress/cypress/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/runner/work/cypress/cypress/node_modules/registry-js
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok"
warning Error running install script for optional dependency: "/home/runner/work/cypress/cypress/node_modules/cpu-features: Command failed.
info This module is OPTIONAL, you can safely ignore this error
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/runner/work/cypress/cypress/node_modules/cpu-features
Output:
Traceback (most recent call last):
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py\", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 9, in <module>
    import gyp.input
  File \"/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/runner/work/cypress/cypress/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.2.0-1018-azure
gyp ERR! command \"/opt/hostedtoolcache/node/18.15.0/x64/bin/node\" \"/home/runner/work/cypress/cypress/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/runner/work/cypress/cypress/node_modules/cpu-features
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok"
```

### Other

[Python version overview](https://devguide.python.org/versions/)

According to https://endoflife.date/python Python 3.11 is supported until Oct 24, 2027, so there should not be any urgent need for Cypress to support Python 3.12 and later.

#### Defaults

| OS \ Distribution | native    | GitHub runner |
| ----------------- | --------- | ------------- |
| Ubuntu `22.04`    | `3.10.12` | `3.10.12`     |
| Windows 2022      | -         | `3.9.13`      |
| Windows 11        | -         | N/A           |

#### Deprecations

[Python `3.12`](https://docs.python.org/3.12/whatsnew/3.12.html) introduces a breaking change:

> [PEP 632](https://peps.python.org/pep-0632/): Remove the `distutils` package. See [the migration guide](https://peps.python.org/pep-0632/#migration-advice) for advice replacing the APIs it provided. The third-party [Setuptools](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html) package continues to provide `distutils`, if you still require it in Python 3.12 and beyond.

Support for Python `3.12` was added to [node-gyp@10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) (see issue https://github.com/nodejs/node-gyp/issues/2869) in `gyp@0.16.1` taking care of the breaking change in Python. [node-gyp@10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) is however not (yet) used by Cypress, meaning that Python `3.12` cannot yet be used cleanly either.

**Comment by MikeMcC399** [comment]
I can offer to submit a PR to update the text in [CONTRIBUTING > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) accordingly.

There is also a related issue that the version of `node-gyp` used by Cypress is not compatible with the Windows 11 SDK. For clarity I will submit that as a separate issue.

- Edit: See also https://github.com/cypress-io/cypress/issues/28703

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Thanks, that does seem like the most reasonable PR to start.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

- The Python default on Ubuntu is version 3.10, which works fine. It's only Windows where a user might install Python 3.12 (latest) and run into issues, however since I couldn't find a solution for https://github.com/cypress-io/cypress/issues/28703 so far, it won't be very helpful to add the Python version restriction if it still doesn't work. I'll come back to this issue if I find something more complete and usable which can be documented.

**Comment by MikeMcC399** [comment]
- Issue https://github.com/cypress-io/cypress/issues/28703 is resolved through PRs https://github.com/cypress-io/cypress/pull/28726 and https://github.com/cypress-io/cypress/pull/28760
- This issue is planned to be resolved through the documentation PR https://github.com/cypress-io/cypress/pull/28759

**Comment by MikeMcC399** [comment]
Comment: According to https://endoflife.date/python Python 3.11 is supported until Oct 24, 2027, so there should not be any urgent need for Cypress to support Python 3.12 and later.
