### ISSUE TITLE
Unable to test grid layouts

### ISSUE THREAD

**Issue by ttsoares** [cypress-io/cypress#28693]
### Current behavior

Using TailwindCSS:

```html
<div cy-test="creations_grid" className="w-full grid grid-cols-1 md:grid-cols-4 gap-4 ">
```

If screen size is small (SM) how to test that there is just one column ?

### Desired behavior

```js
cy.get('[cy-test="creations_grid"]')
  .should( "have.css", "grid-template-columns", "repeat(1, minmax(0, 1fr))" );
```

This should work...  But the return to the should is a number, the window width in pixels.

### Test code to reproduce

Test Creations component to have one column at SM sizesfailed
```
BEFORE ALL
1
visit/
2
viewportiphone-8, portrait
TEST BODY
1
get[cy-test="creations_grid"]
2
invoke.css()
3
assertexpected 327.029px to equal **repeat(1, minmax(0, 1fr))**
AssertionError
Timed out retrying after 4000ms: expected '327.029px' to equal 'repeat(1, minmax(0, 1fr))'
[cypress/e2e/app.cy.js:158:8](http://localhost:3000/__/#)
  156 |     cy.get('[cy-test="creations_grid"]')
  157 |       .invoke("css", "grid-template-columns")
> 158 |       .should("eq", "repeat(1, minmax(0, 1fr))");
      |        ^
  159 |   });
  160 | });
  161 |
```
### Cypress Version

13.6.2

### Node version

18.17.1

### Operating System

Linux Mint  21.2

### Debug Logs

```shell
The page used can be reached at:

https://studios-loop.vercel.app/

The object of interest there is the "Our Creations"
```

### Other

The "computed" style shown by the inspect tool shows:
```
grid-template-columns: 
409px;
Best Match .grid-cols-1
repeat(1, minmax(0px, 1fr))
```

Cypress is receiving this number (409px) that is the actual window width.

**Comment by jennifer-shehane** [comment]
Please check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress. We'll close this issue as it does not appear to be a reported bug in Cypress, but rather a question on usage.

**Comment by ttsoares** [comment]
Even an Udemy Cypress course teacher was unable to answer that...

I pose this question in the Discor channel. No answer.

Also:
https://github.com/cypress-io/cypress/discussions/28660


Em qui., 11 de jan. de 2024 às 12:41, Jennifer Shehane <
***@***.***> escreveu:
