### ISSUE TITLE
Unable to install Cypress version 13

### ISSUE THREAD

**Issue by mahadi087** [cypress-io/cypress#28708]
### Current behavior

Hello, upgrading to Cypress version 13 from version 12 by: **npm install -D cypress@13.6.2** having non stop WARN and installation never completed. Operating system: Windows 10 Pro Any idea what it could be. Thanks in advanced.

### Debug logs

```Text
npm WARN Could not resolve dependency:
npm WARN peerOptional cypress@">= 3 < 13" from @nrwl/cypress@15.9.2
npm WARN node_modules/@nrwl/cypress
npm WARN dev @nrwl/cypress@"15.9.2" from the root project
npm WARN 2 more (@nrwl/angular, @nrwl/storybook)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: abcxyz@0.0.0
npm WARN Found: cypress@13.6.2
npm WARN node_modules/cypress
npm WARN dev cypress@"13.6.2" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional cypress@">= 3 < 13" from @nrwl/cypress@15.9.2
npm WARN node_modules/@nrwl/cypress
npm WARN dev @nrwl/cypress@"15.9.2" from the root project
npm WARN 2 more (@nrwl/angular, @nrwl/storybook)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: abcxyz@0.0.0
npm WARN Found: cypress@13.6.2
npm WARN node_modules/cypress
npm WARN dev cypress@"13.6.2" from the root project
```

### Cypress Version

13

### Node version

v18.13.0

### Package Manager

npm

### Package Manager Version

 ...

### Operating system

Windows

### Operating System Version

10

**Comment by jennifer-shehane** [comment]
@mahadi087 It seems this error is being thrown from @nrwl/cypress and not cypress itself. Looking at that package it seems they have a new @nx/cypress package that they suggest using: https://www.npmjs.com/package/@nrwl/cypress So I would try that.
