### ISSUE TITLE
Visiting any auth0 login page with passkey enabled results in "Please select a passkey" crash loop

### ISSUE THREAD

**Issue by vmandrychenko** [cypress-io/cypress#28705]
### Current behavior

1. Run a test that has a visit to the auth0 login page with the passkey enabled
2. The page erroneously shows: "Please select a passkey" without any user action. 
<img width="1777" alt="image" src="https://github.com/cypress-io/cypress/assets/4511527/669a942f-6a21-4df3-8679-81942044f374">

The page loops automatically ten more times with the same condition before the "I give up" page shows:

<img width="1791" alt="image" src="https://github.com/cypress-io/cypress/assets/4511527/2f324e15-4ee0-4a32-8345-a3e50edc5a9a">

### Desired behaviour

1. Run a test that has a visit to the auth0 login page with passkey enabled
2. Login normally (passkey message doesn't interfere with normal behaviour).

### Test code to reproduce

1. Please clone the repo with minimal case to reproduce: https://github.com/GarnerCorp/cypress-passkey-auth0-failure-example
2. cd src
3. yarn install
4. yarn cypress open

### Cypress Version

13.6.2

### Node version

16.14.0

### Operating System

Sonoma 14.1.1

### Debug Logs

```shell
Logs: https://gist.github.com/vmandrychenko/35e41977ea0715e354ebf710249a3a67


code/cypress-passkey/src $ yarn cypress info                                                 

DevTools listening on ws://127.0.0.1:50800/devtools/browser/9987a076-584e-46f1-82bb-aaf1ddeaa526
2024-01-11 16:46:22.406 Cypress[11539:1472849] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Displaying Cypress info...

Detected 1 browser installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 120.0.6099.216
  - Executable: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile: /Users/vman/Library/Application Support/Cypress/cy/production/browsers/chrome-stable

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser chrome

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /Users/vman/Library/Application Support/cypress/cy/development
Browser Profiles: /Users/vman/Library/Application Support/cypress/cy/development/browsers
Binary Caches: /Users/vman/Library/Caches/Cypress

Cypress Version: 13.6.2 (stable)
System Platform: darwin (23.1.0)
System Memory: 68.7 GB free 10.7 GB
```
```


### Other

_No response_

**Comment by lzm0** [comment]
A workaround is to include
```JavaScript
Cypress.automation("remote:debugger:protocol", {
    command: "WebAuthn.enable"
});
```
before `cy.visit(...)`.

This solution was found in https://discord.com/channels/755913899261296641/1110655231638917272/1110655231638917272

**Comment by jsoref** [comment]
Fwiw, we filed a ticket and auth0 has acknowledged this is their fault and assigned it to engineering to fix.

**Comment by jennifer-shehane** [comment]
@jsoref Has this been resolved? Is there a link to the auth0 ticket?

**Comment by jsoref** [comment]
My records show:
> Auth0 Developer Support
> 25 days ago
> New comment for Case: https://support.auth0.com/tickets/02335097

> Engineering has created a backlog item to address this issue, which will be included in an upcoming deployment. They were not able to provide an ETA on the fix at this time, but did mention that a solution is already in the works and awaiting review/testing. Until then, the workaround you've already mentioned should disabled this behavior for the time being.

I can see about having someone check to see if this is resolved -- possibly tomorrow.

**Comment by jsoref** [comment]
Yes, it appears to be fixed. You can close this.
