### ISSUE TITLE
Whole Cypress window freezes after I wisit .asp page

### ISSUE THREAD

**Issue by mikoca** [cypress-io/cypress#28707]
### Current behavior

If I use cy.visit('https://portal.youforce.com/verzuimmanagerz/system/login.asp?'); then after few second Whole Cypress window freezes. Please see [video](https://youtu.be/IZps2nFRe38). Link for video: https://youtu.be/IZps2nFRe38.

### Desired behavior

Test should run normally and I can inspect element.

### Test code to reproduce

Link for video: https://youtu.be/IZps2nFRe38 , where you can see code, I can not share code.

### Cypress Version

13.6.2

### Node version

20.10.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
This is very weird that is completely freezes. I haven't seen this behavior in a long time before. Is it possible to narrow down to provide test code we could run to recreate on our side?

**Comment by jennifer-shehane** [comment]
Closing since no reproducible example was provided to investigate.
