### ISSUE TITLE
Dependency Conflict with Semantic Release and Chai Versions

### ISSUE THREAD

**Issue by UzaeirAzhar** [cypress-io/cypress#28723]
### Current behavior

I am encountering a dependency conflict while attempting to install Cypress dependencies using `npm install`. The issue appears to be related to conflicting versions of semantic-release and chai.

### Desired behavior

Dependencies should be installed without encountering dependency conflicts.

### Test code to reproduce

- Clone repo from here `git@github.com:cypress-io/cypress.git`
- Install dependencies using `npm i`
- Observe the error

### Cypress Version

13.6.2

### Node version

18.17.1

### Operating System

macOS (Ventura - 13.5.1)

### Debug Logs

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cypress@13.6.2
npm ERR! Found: semantic-release@19.0.3
npm ERR! node_modules/semantic-release
npm ERR!   dev semantic-release@"19.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer semantic-release@">=15.8.0 <18.0.0" from @semantic-release/changelog@5.0.1
npm ERR! node_modules/@semantic-release/changelog
npm ERR!   dev @semantic-release/changelog@"5.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.


If I change semantic-release version then got this chai dependency issue:


npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cypress@0.0.0-development
npm ERR! Found: chai@3.5.0
npm ERR! node_modules/chai
npm ERR!   dev chai@"3.5.0" from cypress@0.0.0-development
npm ERR!   cli
npm ERR!     cypress@0.0.0-development
npm ERR!     node_modules/cypress
npm ERR!       workspace cli from the root project
npm ERR!       4 more (@cypress/react, @cypress/react18, @cypress/vue, @cypress/webpack-preprocessor)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer chai@"^4.1.2" from chai-string@1.5.0
npm ERR! node_modules/chai-string
npm ERR!   dev chai-string@"1.5.0" from cypress@0.0.0-development
npm ERR!   cli
npm ERR!     cypress@0.0.0-development
npm ERR!     node_modules/cypress
npm ERR!       workspace cli from the root project
npm ERR!       4 more (@cypress/react, @cypress/react18, @cypress/vue, @cypress/webpack-preprocessor)
```

**Comment by MikeMcC399** [comment]
@UzaeirAzhar 

Cypress does not use npm to build from source. It uses Yarn Classic.

See the [CONTRIBUTING](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) document, sections

- [Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) 
- [Getting started](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started)

You should therefore not be using npm to build Cypress from source. Also, according to the [Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) document you should be using the version of Node.js specified in the file [.node-version](https://github.com/cypress-io/cypress/blob/develop/.node-version) which is currently set to

https://github.com/cypress-io/cypress/blob/8a02c2de8365cf0a042ac153368985d044821c37/.node-version#L1

not `18.17.1` which you listed in your issue.

**Comment by UzaeirAzhar** [comment]
@MikeMcC399 Thanks for your reply.

Read your mentioned link. its works,
