### ISSUE TITLE
get('#someID') won't work but get('[id="someID"]') does

### ISSUE THREAD

**Issue by FearlessBadger7** [cypress-io/cypress#28727]
### Current behavior

I am trying to use `cy.get('#instructions:Notification').should('be.visible')` but it fails to find it.
If I use `cy.get('[id="instructions:Notification"]').should('be.visible')` it works fine.
I tried `cy.get('#instructionsNotification')` and it failed.
I tried `cy.get('#instructions')` and it worked.
<img width="703" alt="image" src="https://github.com/cypress-io/cypress/assets/22543643/94ac039e-b54a-4a04-a9af-93e801777173">

### Desired behavior

`cy.get('#instructions:Notification')` should find the component.

### Test code to reproduce

```js
const MyComp = () => <div>
  <h1>Do this:</h1>
  <div id='instructions:Notification'>
    <h2>Instructions:</h2>
    <p>Hey make sure you pay attention</p>
  </div>

  <h2>Step 1</h2>
  <p>Blah Blah Blah</p>

</div>

describe('Test code', () => {
  it.only('ID is NOT found', () => {

    cy.mount(<MyComp />)

    cy.get('#instructions:Notification').should('be.visible')
      .within(() => {
        cy.contains('Instructions:').should('be.visible')
      })
  })

  it.only('ID is found', () => {

    cy.mount(<MyComp />)

    cy.get('[id="instructions:Notification"]').should('be.visible')
      .within(() => {
        cy.contains('Instructions:').should('be.visible')
      })
  })
})
```
Proof of this demoing this code:
<img width="1227" alt="image" src="https://github.com/cypress-io/cypress/assets/22543643/3654749e-208c-475d-9680-a0b3ed64e359">

### Cypress Version

13.6.2

### Node version

v18.8.0

### Operating System

macOS 14.0

**Comment by jennifer-shehane** [comment]
@FearlessBadger7 You'll need to escape the `:` since that is also used as a selector indicator. The below selector would work.

```js
cy.get('#instructions\\:Notification').should('be.visible')
```
