### ISSUE TITLE
How to prevent going to the Specs folder when the page URL changes during the test

### ISSUE THREAD

**Issue by DaniilKonarev** [cypress-io/cypress#28730]
Colleagues, greetings.
I must say right away, I have never been a guru or an automator at all, but I use Cypress to automate routine checks.

In general, there is a problem that I cannot find a solution to.
There is a small test that checks the presence of the word "Electronic" on the page.
```js
it.("Название", () => {
cy.visit("someUrl");
cy.getEl("field-login").type(v.operrtest);
cy.getEl("field-password").type(v.operrtestpass);
cy.getEl("button-save").click();
cy.getEl("field-name-docSeries").type(v.validPassSer);
cy.wait(500);
cy.getEl("field-name-docNumber").type(v.validPassNum);
cy.contains("Найти").click();
cy.get(".preloader-container").should("not.exist");
cy.wait(2000);
//---Переход на новый фронт---
cy.contains("Перейти на новую версию").click();
//---ввод реквизитов---
cy.getEl("overflow-menu-button-overflow-menu-button").click();
cy.contains("Выпустить дебетовую карту").click();
cy.contains("Запуск процесса").should("not.exist");
cy.pause();
cy.getEl("tariffPlan").type(v.tariffname).type("{enter}");
cy.getEl("cardTypepersonal").click();
cy.getEl("personalCardPaySystem")
.type(v.personalCardPaySystem)
.type("{enter}");
cy.getEl("personalCardCategory")
.type(v.personalCardCategory)
.type("{enter}");
cy.getEl("buttonComplete").click();
//---ЭФ корзины---
cy.contains("Единое заявление");
cy.getEl("button-goForward").click();
//---ЭФ печать---
cy.contains("Электронный");
});
```

The problem occurs after we get to the line
```js
cy.contains("Запуск процесса").should("not.exist");
```

Here we are waiting for the preloader to load, after which we get to a new URL and a form opens with the inputs, which we fill out next.
But after the above line is processed, we are simply thrown into the Specs folder in the Cypress interface.

I have no idea how to fix this, maybe someone has encountered this problem, I ask for help.

**Comment by jennifer-shehane** [comment]
@DaniilKonarev If you're being routed to another URL entirely, you might want to look at how [cy.origin](https://docs.cypress.io/api/commands/origin) works, if you need to use that in your tests. 

There are some websites also that do frame busting, where [modifyObstructiveCode](https://docs.cypress.io/guides/references/configuration#modifyObstructiveCode) should help the page work properly. Sometimes it doesn't though and it will bust out of the Cypress iframe.

I can't be sure of the cause without a way to run and reproduce, but these are a couple of ideas. If you need us to investigate an issue - please provide a reproducible example.

**Comment by DaniilKonarev** [comment]
@jennifer-shehane Hello, thank you very much for your reply.
here is the code that can be run

`it.only("Проверяем наличие электронного способа подписания (НОВЫЙ ФРОНТ)", () => {
    cy.visit("https://test03.rshb.ru/efr/");
    cy.getEl("field-login").type("rf_m_oper3@rf.rshbank.ru");
    cy.getEl("field-password").type("!!!QQQ222");
    cy.getEl("button-save").click();
    cy.getEl("field-name-docSeries").type("1704");
    cy.wait(500);
    cy.getEl("field-name-docNumber").type("456445");
    cy.contains("Найти").click();
    cy.get(".preloader-container").should("not.exist");
    cy.wait(1000);
    //---Переход на новый фронт---
    cy.contains("Перейти на новую версию").click();
    //---Старт операции, ЭФ ввода реквизитов---
    cy.getEl("overflow-menu-button-overflow-menu-button").click();
    cy.contains("Выпустить дебетовую карту").click();
    cy.wait(5000);
    cy.contains("Запуск процесса").should("not.exist");
    cy.getEl("tariffPlan").type(v.tariffname).type("{enter}");
    cy.getEl("cardTypepersonal").click();
    cy.getEl("personalCardPaySystem")
      .type(v.personalCardPaySystem)
      .type("{enter}");
    cy.getEl("personalCardCategory")
      .type(v.personalCardCategory)
      .type("{enter}");
    cy.getEl("buttonComplete").click();
    //---ЭФ корзины ЕЗБП---
    cy.contains("Единое заявление на банковские продукты");
    cy.getEl("button-goForward").click();
    //---ЭФ печать---
    cy.contains("Электронный");
  });`

**Comment by DaniilKonarev** [comment]
https://github.com/cypress-io/cypress/assets/82046213/c2c1253b-9f74-4783-8e26-b1223e077118

if you can't run the code, then I'm attaching a video

**Comment by DaniilKonarev** [comment]
> @DaniilKonarev If you're being routed to another URL entirely, you might want to look at how [cy.origin](https://docs.cypress.io/api/commands/origin) works, if you need to use that in your tests.
> 
> There are some websites also that do frame busting, where [modifyObstructiveCode](https://docs.cypress.io/guides/references/configuration#modifyObstructiveCode) should help the page work properly. Sometimes it doesn't though and it will bust out of the Cypress iframe.
> 
> I can't be sure of the cause without a way to run and reproduce, but these are a couple of ideas. If you need us to investigate an issue - please provide a reproducible example.


https://github.com/cypress-io/cypress/assets/82046213/c2c1253b-9f74-4783-8e26-b1223e077118

@jennifer-shehane Hello, thank you very much for your reply.
it seems to me that I might have formulated the description of the problem incorrectly. I can show video
Will this information be enough?


I tried adding 
`experimentalModifyObstructiveThirdPartyCode: true `
to the cypress.config.js, but it didn't give a result

**Comment by jennifer-shehane** [comment]
Yah, this is certainly a bug. :/ I've seen this reported a few times for other sites, there is something that is making the webpage bust out of Cypress iframe to the main window. I can't find the other issue however.

**Comment by DaniilKonarev** [comment]
It's a pity(

I'll be waiting for a correction
