### ISSUE TITLE
significant proxy regression since v13.3.2

### ISSUE THREAD

**Issue by krishantaylor** [cypress-io/cypress#28734]
### Current behavior

Something changed internally where requests that used to finish in under 100ms now take over 2s. Depending on how tests and data calls are structured, this results in a number of flaky and consistent timeouts.

### Desired behavior

Requests shouldn't consistently take an additional 2s beyond the server time.

### Test code to reproduce

Cannot provide, but I've narrowed it down to v13.3.2 where the regression starts. Requests still complete as expected through v13.3.1.

### Cypress Version

13.6.2

### Node version

v18.19.0

### Operating System

macOS 14.2.1

**Comment by jennifer-shehane** [comment]
@krishantaylor Hi, we’re especially interested in any performance regressions like described. Are you recording to the Cloud for these runs with perf issues? Could you share a link to a Test Replay exhibiting this behavior?

if not recording to the Cloud, could you share information around what types of requests are slower, how many requests, maybe a snapshot of the requests in devtools?  Ideally a project to run and reproduce the issue would be ideal.

**Comment by mschile** [comment]
Hi @krishantaylor 👋, we just released Cypress [13.6.3](https://docs.cypress.io/guides/references/changelog#13-6-3) that includes a proxy performance regression fix. Could you please upgrade to the newest version to see if that helps. I am also working on addressing a couple other proxy performance issues that should be in the next release.

**Comment by vinassefranche** [comment]
Hi! We also have the same issues on our side. Here are some thoughts on our issue if it can help you:

- From what I've seen the issue occurred on our side when updating to 13.6.0. and every patch version of 13.6 has the same issue, including 13.6.3. I'm currently reverting this last version because of flakiness
- We are using graphql and I can see that the first calls take a normal amount of time. Starting from some random moment, all the graphql requests take 2s. It's mostly causing flaky tests and not consistent failures which makes me thing that the issue does not occur every time
- We are recording in the cloud so I have some replays available when I go to our cypress account. How can I tell you where to look?

Thanks in advance for your investigation!

**Comment by jennifer-shehane** [comment]
@vinassefranche Just replying with a Cloud URL of the Test Replay where you see the 2 sec slowdown in this issue. Or you can click this purple "Report an Issue" button in the top right of the Test Replay window.

![Screen Shot 2024-01-17 at 9 27 20 AM](https://github.com/cypress-io/cypress/assets/1271364/2d264cf9-9d49-42b2-8563-f6144aae0311)

**Comment by vinassefranche** [comment]
I reported the issue there. Thanks!

**Comment by jennifer-shehane** [comment]
@vinassefranche Thanks, we got your report and are looking into it. There is a current issue @mschile is investigating that looks like it could be the cause here.

**Comment by krishantaylor** [comment]
@mschile, v13.6.3 still sees an extra ~2s on many requests. This is happening on both REST and graphql style requests, but usually the same ones (when comparing multiple test runs).

**Comment by mschile** [comment]
@krishantaylor and @vinassefranche, I've built a [pre-release](https://github.com/cypress-io/cypress/commit/6d6d1241213dd6c2c93f34fd94c5fe3c02e76b2f#comments) binary with the changes that I believe will fix this issue. If you could install it and try it out to make sure it addresses your issue that would be great. Thanks!

```
npm install https://cdn.cypress.io/beta/npm/13.6.4/linux-x64/mschile/protocol/proxy_correlation-6d6d1241213dd6c2c93f34fd94c5fe3c02e76b2f/cypress.tgz --save-dev
```

**Comment by krishantaylor** [comment]
@mschile, that seems to have done it. Thanks!
