### ISSUE TITLE
Snyk failures from contributor fork submissions

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28736]
### Current behavior

CI fails with Snyk errors in PRs from contributor forks

![image](https://github.com/cypress-io/cypress/assets/66998419/80acee06-6780-4fef-8e76-49181928223d)

The error in the logs is:

> Error: Input required and not supplied: token

This prevents such PRs from ever achieving a successful CI run.

### Desired behavior

Ensure that Snyk does not cause a general failure of CI checks in PRs from contributor forks, for instance by disabling such checks.

### Test code to reproduce

See for instance https://github.com/cypress-io/cypress/pull/28726

### Cypress Version

develop branch

### Node version

N/A

### Operating System

N/A

### Debug Logs

```shell
Current runner version: '2.311.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Download action repository 'actions/setup-node@v3' (SHA:1a4442cacd436585916779262731d5b162bc6ec7)
Download action repository 'snyk/actions@master' (SHA:3e2680e8df93a24b52d119b1305fb7cedc60ceae)
Complete job name: Snyk_SCA_Scan (18.x)
Run actions/checkout@v3
  with:
    fetch-depth: 0
    repository: cypress-io/cypress
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-tags: false
    lfs: false
    submodules: false
    set-safe-directory: true
Error: Input required and not supplied: token
```

### Other

Contributor PRs do not have access to GitHub secrets from the main repo.

The workflows:

- [.github/workflows/snyk_static_analysis_scan.yaml](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/snyk_static_analysis_scan.yaml)
- [.github/workflows/snyk_sca_scan.yam](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/snyk_sca_scan.yaml)

contain a step which will always fail when run from a fork:

```yml
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_GITHUB_ACTION_TOKEN }}
```

**Comment by jennifer-shehane** [comment]
We had a PR to skip the snyk job, which I believe was just forgotten: https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview

We did some investigation on how we could do this check without giving contributors access to keys and didn't land on anything.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> We had a PR to skip the snyk job, which I believe was just forgotten: https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview
> 
> We did some investigation on how we could do this check without giving contributors access to keys and didn't land on anything.

- You're right. https://github.com/cypress-io/cypress/pull/28093 from @astone123 was closed without being merged. Could this be reactivated? There wasn't any comment to say why it was closed.

**Comment by jennifer-shehane** [comment]
Yah he reactivated it.

**Comment by MikeMcC399** [comment]
Thank you!

- This issue was resolved by https://github.com/cypress-io/cypress/pull/28093
