### ISSUE TITLE
focused() returns wrong element

### ISSUE THREAD

**Issue by plweil** [cypress-io/cypress#28757]
### Current behavior

I'm testing a page where a button closes a modal window and the focus is placed on the button element that originally triggered the modal. Chrome DevTools confirms that the focus is being placed on this element (`a.wi-county-link`). But logging `focused()` to the console in Cypress returns the wrong element (`select#county-selector`)

### Desired behavior

correctly recognize which element has focus

### Test code to reproduce

```javascript
    cy.get('#modal-links-wrapper')
      .contains('button', 'Return')
      .click()
        cy.focused().then(focusedElement => {
          console.log(focusedElement);
        }
        )
```

### Cypress Version

12.17.2

### Node version

v18.17.1

### Operating System

macOS 12.7.2

### Other

The modal is a native `dialog` element that is opened with the built-in `showModal()` and `close()` methods

**Comment by jennifer-shehane** [comment]
@plweil There likely is a situation where this happens. Could you provide a full example we can run to see the situation? It's likely an edge case we need to handle, but we'll need to be able to recreate it ourselves in order to fix.

**Comment by TheoAnastasiadis** [comment]
I was able to reproduce this as follows;

index.html
```html
<body>
    <button id="prev">open</a>
    <button id="next">next</button>
    <dialog id="dialog">
        <p>Opened!</p>
        <button id="close">Close</button>
    </dialog>
     <script>
        const dialog = document.querySelector("dialog");

        const prevBtn = document.getElementById("prev");
        const closeBtn = document.getElementById("close");
        const nextBtn = document.getElementById("next");

        const timeout = 51;

        prevBtn.addEventListener("click", function (e) {
            dialog.showModal(); // opens modal
        });

        dialog.addEventListener('close', () => {
            setTimeout(() => {
                nextBtn.focus();
            }, timeout) //see below
        })

        closeBtn.addEventListener('click', () => {
            dialog.close() // start the closing phase
        });
    </script>
</body>
```

spec.cy.js
```javascript
it('passes', (done) => {
  cy.visit('http://192.168.56.1:8080/');
  cy
    .get('#prev')
    .click()
    .get('#close')
    .click()
    .focused().then(el => {
      if (el[0].id !== 'next') throw new Error('...'); // this throws for timeouts larger than 50ms
      else done();
  })
})
```
My idea would be it is caused by some kind of animation or lag in cases where the `button#next` is not the button that caused the dialogue to open. 

**If** this is the case, I do not know if it should be considered a bug since an assertion like 
```javascript 
//...
.focused().should("have.id", "next")
``` 
would succeed within the timeout.

**Comment by plweil** [comment]
Thanks @TheoAnastasiadis. I don't have any timeouts or animation in my code. It's just straight `dialog.close()`. The original trigger button (in this case, an `<a role="button">` element inside an svg map with turns red because it is focused, which Chrome DevTools confirms via `document.ActiveElement`.

**Comment by plweil** [comment]
thanks @jennifer-shehane I'm not sure whether this is possible, but I'll see. Right now this is an app under development with IP restrictions. May I ask why you say that "There likely is a situation where this happens"?
