### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/var/lib/jenkins/.cache/Cypress/12.9.0/Cypress/resources/app/packages/runner/dist/injection.js

### ISSUE THREAD

**Issue by Autobots631** [cypress-io/cypress#28765]
### Current behavior

cypress run command getting failed with ENOENT issue.
This happens when we run Cypress, and it takes a longer time (more than 24hr).

```
[31mENOENT: no such file or directory, open 
'/var/lib/jenkins/.cache/Cypress/12.9.0/Cypress/resources/app/packages/runner/dist/injection.js'[39m
[31mError: ENOENT: no such file or directory, open '/var/lib/jenkins/.cache/Cypress/12.9.0/Cypress/resources/app/packages/runner/dist/injection.js'[39m
+ true
```

Any suggestions will be appreciated.

### Desired behavior

Cypress should work.

### Test code to reproduce

npx cypress run in linux with longer duration.

### Cypress Version

12.9.0

### Node version

v16.17.0

### Operating System

Linux

**Comment by jennifer-shehane** [comment]
You are running the Cypress process for more than 24 hours? Is your CI cache set up so that it is not clearing at an internal that is 24 hours or less?

>This happens when we run Cypress, and it takes a longer time (more than 24hr).

**Comment by mattweberio** [comment]
Our team has experienced this issue in 50% of our 1.5-hour runs. Is there a known issue regarding caching that could provide insight into a solution?

ENOENT: no such file or directory, open '/home/ubuntu/.cache/Cypress/10.3.0/Cypress/resources/app/packages/runner/dist/injection.js'

**Comment by Autobots631** [comment]
After doing some investigation we figure out there was a parallel jenkins job was getting triggered which causing clearing cache. After deleting that job our 24 hr run executed without any issues.

**Comment by jennifer-shehane** [comment]
@mattweberio I suspect this is likely something in the CI or machine config and not directly related to something Cypress is causing - like evidenced in @rimadas3994 comment.

**Comment by mattweberio** [comment]
Thank you, @rimadas3994 and @jennifer-shehane - it seems feasible we have another job that uses the same cache.
