### ISSUE TITLE
Cloud RUN_ALREADY_COMPLETE error not providing run url

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress#28783]
### Current behavior

RUN_ALREADY_COMPLETE error is not providing full run url

see: https://app.circleci.com/pipelines/github/cypress-io/cypress/59476/workflows/33bab90b-986f-45dc-bd7e-a96ca9a126ed/jobs/2472245

```md
The run you are attempting to access is already complete and will not accept new groups.

The existing run is: https://cloud.**********/projects/ypt4pf/runs

When a run finishes all of its groups, it waits for a configurable set of time before finally completing. You must add more groups during that time period.

The --tag flag you passed was: 
The --group flag you passed was: win32-x64-launchpad-e2e
The --parallel flag you passed was: true
The --ciBuildId flag you passed was: b83421b9-8f75-4efd-84fd-a647732f5159

https://on.**********/already-complete
```

### Desired behavior

Should link to the run, not to the runs page.

### Test code to reproduce

Create Run two runs of Cypress that should belong to the same run, where the second group has already "time out" the wait for more tests threshold.

### Cypress Version

13.6.3

### Node version

18.15.0

### Operating System

MacOS 12.5.1

**Comment by jennifer-shehane** [comment]
@emilyrohrbough We'd need to deduce whether this is because we're not displaying the correct arg or the Cloud is not sending the correct meta data.

**Comment by gargshashank0107** [comment]
I get the same issue when I run my test using a manually executed GitHub action 
the link is https://cloud.cypress.io/projects/***/runs/84
I am assuming Cypress in not decoding the project in this case 

The link is correct when the workflow runs a part of PR and has bot writing results back to the PR

**Comment by jennifer-shehane** [comment]
This is a Cloud (server-side) data problem, not a client bug. For the ALREADY_COMPLETE (422) case, the Cypress Cloud API is returning a payload.runUrl that points to the project’s /runs index page rather than the specific run URL (/runs/<buildNumber>). Cypress faithfully displays whatever runUrl the Cloud sends.
