### ISSUE TITLE
Cypress.minimatch treats timezone's slash as new route separator 

### ISSUE THREAD

**Issue by asadaj** [cypress-io/cypress#2878]
### Current behavior:
While stubbing a response for a route containing a timezone, slash present in the timezone's value is treated like a separator in the path.

Below are the minimatch results to explain:

```js
Cypress.minimatch('/api/export?timezone=Europe/Warsaw', '**/export*/**', {
  matchBase: true
}) // true

Cypress.minimatch('/api/export?timezone=Europe/Warsaw', '**/export**', {
  matchBase: true
}) // false
```

The second example shows that you have to use the stars twice if you don't care about the timezone's actual value. It is non intuitive, as user has to use two sets of stars to stub the response for the parameters like timezone, when in reality it is only one parameter, so one would anticipate that only one star would be enough.

### Desired behavior:
Consistent way of stubbing route's parameters - i.e. timezone is just one parameter, so one star should be enough to tell Cypress not to care about it's value.

### Steps to reproduce:
Stub any route that contains a timezone query parameter. Reproducible 100% times.

### Versions
Cypress 3.1.0
Cypress-testing-library 2.2.1
Chrome 70
MacOS Mojave 10.14.1

**Comment by jennifer-shehane** [comment]
Hey @asadaj, thanks for opening the issue. We are using the latest version of minimatch for our glob matching. I think this may be an issue to open on their repo - see what feedback we get there. https://github.com/isaacs/minimatch/issues

**Comment by asadaj** [comment]
Sure, thanks for the guidance!
