### ISSUE TITLE
Cypress Window isn't shown when coming from multi-display mode

### ISSUE THREAD

**Issue by asashour** [cypress-io/cypress#28812]
### Current behavior

1. Open Cypress in multi-display (monitor) mode
2. Ensure the cypress window is open in the non-default display (monitor)
3. Close Cypress
4. Disconnect from the monitors (to have a single display/monitor)
5. Open Cypress

Actual behavior: the Cypress window cannot be shown, it seems to be shown in the non-visible display

### Desired behavior

When the location of the Cypress window is outside the available display/monitor, the old location should be discarded.

### Test code to reproduce

N/A

### Cypress Version

13.6.3

### Node version

N/A

### Operating System

Windows 10

**Comment by MikeMcC399** [comment]
@asashour 

This is a known issue with Microsoft Windows 10 (and 11) that is unrelated to Cypress.

You may find the Microsoft support article [Some Programs Are Displayed Off the Screen](https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4) helpful. Or Google "windows 10 move window to current monitor" for a selection of articles and videos on this topic.
