### ISSUE TITLE
Installation gif outdated in README

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28815]
### Current behavior

The [animated gif](https://user-images.githubusercontent.com/1271364/31740846-7bf607f0-b420-11e7-855f-41c996040d31.gif) embedded in the [README > Installation](https://github.com/cypress-io/cypress?tab=readme-ov-file#installing) is outdated.

1. The version demonstrated is the legacy Cypress version [cypress@0.20.3](https://docs.cypress.io/guides/references/changelog#0-20-3) released on Oct 6, 2017. The current version of Cypress is `13.x`.
2. `npm install cypress --save-dev` does not echo the postinstall steps on currently supported versions of Node.js (`18`, `20` and later). These steps are silent unless the npm option `--foreground-scripts` is used.
3. It is no longer necessary to open Cypress with `./node_modules/.bin/cypress open`. This has been replaced by `npx cypress open` or `yarn run cypress open` (see [Opening the App](https://docs.cypress.io/guides/getting-started/opening-the-app)). 
4. Cypress no longer automatically scaffolds examples. The choice is left to the user.
5. The launcher and Component Testing are not shown.
6. The folder structure shown corresponds to legacy implementations.

### Desired behavior

Either 
- the [animated gif](https://user-images.githubusercontent.com/1271364/31740846-7bf607f0-b420-11e7-855f-41c996040d31.gif) should be removed from [README > Installation](https://github.com/cypress-io/cypress?tab=readme-ov-file#installing) or
- it should be replaced by an up-to-date recording of installing Cypress.

### Test code to reproduce

Go to [README > Installation](https://github.com/cypress-io/cypress?tab=readme-ov-file#installing) and view the animated gif in this section.

### Cypress Version

0.20.3

### Other

- This issue corresponds to the documentation issue https://github.com/cypress-io/cypress-documentation/issues/5340

**Comment by jennifer-shehane** [comment]
Good ole version 0.20.3. 😅 Yah I don't think we've taken a close look at this past the first couple frames in a while. Welcome to a PR to update.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Good ole version 0.20.3. 😅 Yah I don't think we've taken a close look at this past the first couple frames in a while. Welcome to a PR to update.

I don't have the tools / experience to make a professional-looking recording. Perhaps the original author, which looks like it was @brian-mann, could be persuaded to re-record with a current version?

**Comment by TheoAnastasiadis** [comment]
That's a nice creative opportunity haha 😁
