### ISSUE TITLE
erro ResizeObserver loop limit exceeded 

### ISSUE THREAD

**Issue by AlanaFFreytass** [cypress-io/cypress#28822]
### Current behavior

Atualmente ao executar a ação de clique para finalizar a ação desejada 
Além da ação não ser finalizada, a seguinte mensagem de erro aparece 
erro ResizeObserver loop limit exceeded 
![image](https://github.com/cypress-io/cypress/assets/157754814/53e39714-c845-4e24-a52b-4cbbee47ad83)

### Desired behavior

Espero que o clique seja finalizado e a mensagem de erro não apareça. 
No final da criação do insumo, a seguinte página surge:
![image](https://github.com/cypress-io/cypress/assets/157754814/85f8292b-e843-4c4a-9e7b-b3c62ba56d00)
Porém não está sendo passada para a 2 página após clicar em finalizar pois surge o erro ResizeObserver loop limit exceeded 
. 

### Test code to reproduce

Sem codigo para disponibilizar pois não quero disponibilizar os acessos da minha empresa, porém deixo aqui parte do código 
![image](https://github.com/cypress-io/cypress/assets/157754814/5624fe40-e793-414d-b70a-1d69d215a5ca)

### Cypress Version

"cypress": "^13.6.3"

### Node version

v18.18.0

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/22113
