### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by Sagy31** [cypress-io/cypress#28839]
### Current behavior

not able to go past loading screen after npm run command
![image](https://github.com/cypress-io/cypress/assets/132455776/3bcee04b-ae8d-4ac4-86d0-0415411983c4)

### Test code to reproduce

test

### Cypress Version

13.6.4

### Node version

v20.9.0

### Operating System

win 11

**Comment by jennifer-shehane** [comment]
@Sagy31 Could you open the developer tools within the Cypress App to see if there's anything printed there?

Please also ensure that there are no blockers running behind the scenes on Windows that may be blocking the App or requests.

**Comment by jennifer-shehane** [comment]
Closing as stale
