### ISSUE TITLE
Cypress is unable intercept API calls and wait until it finishes , even if the API call is visible in the side menu

### ISSUE THREAD

**Issue by git-ashutosh-das** [cypress-io/cypress#28834]
### Current behavior

Cypress version : 13.6.4
Chrome version : v120 
```js
cy.intercept('www.something.com/Api/todos').as('todos') 
cy.visit('/')  
cy.wait('@todos')  
                    
Cypress is unable to intercept the 'todos' Api call even if it is visible in the side menu - This issue has been happening multiple times and I tried using multiple versions of cypress but the issue remains .
Should I use
 cy.intercept('www.something.com/Api/todos').as('todos').then(()=>{
  cy.visit('/')
  cy.wait('@todos')
}) 
```
Also `cy.waituntill(todos)` does not completely wait for the intercepted API call 

![imagecypp](https://github.com/cypress-io/cypress/assets/158279407/186aa338-6c03-428f-9ea2-7d466200727e)

### Desired behavior

Cypress should be able to intercept api and wait untill it finishes

### Test code to reproduce
```js
cy.intercept('www.something.com/Api/todos').as('todos') 
cy.visit('/')  
cy.wait('@todos') 
```

### Cypress Version

13.6.4

### Node version

v18.15.0

### Operating System

windows 10.0.19045

**Comment by jennifer-shehane** [comment]
@git-ashutosh-das Have you tried some of these debugging techniques to ensure the glob you're setting up match the URL? https://docs.cypress.io/api/commands/intercept#Cypressminimatch

**Comment by git-ashutosh-das** [comment]
I have verified the url multiple times as a fix to this I had tried adding the intercept in beforeeach , 
Recently I have not been facing this issue I think the working has improved since the time I raised the bug

**Comment by jennifer-shehane** [comment]
Going to close as resolved. Please open a new issue if you see similar behavior in our most recent version of Cypress.
