### ISSUE TITLE
Run e2e and component test in same cloud run

### ISSUE THREAD

**Issue by gajraj-gan** [cypress-io/cypress#28833]
### What would you like?

We have slack setup for the e2e and component testing of cypress.

First of all, the slack bot of cypress comment twice on completion of a cypress run. (idk if this is a know bug)

But why aren't the e2e and component tests done in one cloud run, is it possible?

### Why is this needed?

This will a better organization method for the UI.

**Comment by jennifer-shehane** [comment]
If you have run component and e2e tests within the same build, on different machines in parallel, they should be associated within the same run. They just need to be within the same CI Build, determined by the ci-build-id. https://docs.cypress.io/guides/cloud/smart-orchestration/parallelization#CI-Build-ID-environment-variables-by-provider

Job 1:
cypress run —component

Job 2:
cypress run —e2e
