### ISSUE TITLE
[Firefox] Typing is causing double characters for every key stroke.

### ISSUE THREAD

**Issue by tester-at-bmi** [cypress-io/cypress#28840]
### Current behavior

When using firefox, when typing into a input field will cause double characters for every keystroke.

![image](https://github.com/cypress-io/cypress/assets/100684771/34a4478e-151e-4ec2-8c5e-f0599a3d2977)

### Desired behavior

When using firefox, when typing into a input field will type a single character for every keystroke.

### Test code to reproduce

`loginViaGui(Cypress.env('admin'), Cypress.env('password_admin'));`

```
export function loginViaGui(username: string, password: string): void {
	cy.session(
		[username, password],
		() => {
			cy.visit('/');
			cy.origin(Cypress.env('BMI_AIP_KEYCLOAK'), { args: { username, password } }, ({ username, password }) => {
				cy.get('#username').should('be.visible').type(username);
				cy.get('#password').should('be.visible').type(password);
				cy.get('#kc-login').should('be.visible').click();
			});
		},
		{ cacheAcrossSpecs: true },
	);
	cy.visit('/');
	cy.url().should('eq', `${Cypress.config('baseUrl')}/`);
}
```

### Cypress Version

12.17.4

### Node version

18.17

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
@tester-at-bmi Could you try updating to the latest Cypress version? Your issue may already be fixed. 

I have to say, I haven't seen this before. This behavior doesn't occur in Chrome? Have you ensured your website doesn't have a bug in Firefox when typing outside of Cypress?

**Comment by tester-at-bmi** [comment]
> @tester-at-bmi Could you try updating to the latest Cypress version? Your issue may already be fixed.
> 
> I have to say, I haven't seen this before. This behavior doesn't occur in Chrome? Have you ensured your website doesn't have a bug in Firefox when typing outside of Cypress?

@jennifer-shehane On Chrome/Edge this behavior is not there when running the tests. 
When i test the login manually everything is ok on firefox. 
Wil report back later this week doing the test on the latest version of Cypress.

**EDIT** Also with the latest version of Cypress (13.6.4) i have te same issue/result. 
Could it be an issue because of cy.session/cy.origin somehow where the typing is hapening?

I'm going to create another test later today that test the application itself to see if i can rule that out.

**Comment by tester-at-bmi** [comment]
@jennifer-shehane 👌 so it seems that it has to do with my current setup that i provided urlier. 

I tried the test directly on keycloak and that seems to work just fine. 

So my best guess is it is an issue with my code that i provided that uses `cy.session`/`cy.origin`.

This code fails

```js
export function loginViaGui(username: string, password: string): void {
	cy.session(
		[username, password],
		() => {
			cy.visit('/');
			cy.origin(Cypress.env('BMI_AIP_KEYCLOAK'), { args: { username, password } }, ({ username, password }) => {
				cy.get('#username').should('be.visible').type(username);
				cy.get('#password').should('be.visible').type(password);
				cy.get('#kc-login').should('be.visible').click();
			});
		},
		{ cacheAcrossSpecs: true },
	);
	cy.visit('/');
	cy.url().should('eq', `${Cypress.config('baseUrl')}/`);
}
```

So this will work.
```js
describe('Keycloak', () => {
	context('Login with valid user credentials', () => {
		beforeEach('Visit login page', () => {
			cy.visit('KEYCLOAK_URL');
		});

		describe('Should be able to login with a valid user account', () => {
            it('Should be able to login with a admin account', () => {
                cy.get('#username').should('be.visible').type('ADMIN');
                cy.get('#password').should('be.visible').type('PASSWORD');
                cy.get('#kc-login').should('be.visible').click();
            });
		});
	});
});
```

**Comment by jennifer-shehane** [comment]
It's a bit strange. 🤔

**Comment by tester-at-bmi** [comment]
Have a workaround for the 1st part.

```js
export function loginViaGui(username: string, password: string): void {
	// eslint-disable-next-line @typescript-eslint/no-shadow
	cy.session(
		[username, password],
		() => {
			cy.visit('/');
			cy.url().should('eq', `${Cypress.config('baseUrl')}/`);
			cy.origin(Cypress.env('BMI_AIP_KEYCLOAK'), { args: { username, password } }, ({ username, password }) => {
				//Cypress.on('uncaught:exception', () => false);
				if (Cypress.isBrowser({ family: 'chromium' })) {
					cy.get('#username').should('be.visible').type(username, {
						log: false,
					});
					cy.get('#password').should('be.visible').type(password, {
						log: false,
					});
				} else {
					cy.get('#username').should('be.visible').invoke('val', username).trigger('input');
					cy.get('#password').should('be.visible').invoke('val', password).trigger('input');
				}
				cy.get('#kc-login').should('be.visible').click();
			});
		},
		{ cacheAcrossSpecs: false },
	);
	cy.visit('/');
	cy.url().should('equal', `${Cypress.config('baseUrl')}/`);
	cy.get(SIDEBAR_LEFT.sidebarLeft, { timeout: 5000 }).should('be.visible');
}
```

1st test succeeds now and session is created. 
All following test fails... 
The session gets restored (seems that way) and then it goes to the application url and than i'm thrown back at the origin url (should have sticked at the application url).
