### ISSUE TITLE
Content-Type and other headers missing in gRPC requests in Cypress with Connect-ES

### ISSUE THREAD

**Issue by robertwenquan** [cypress-io/cypress#28849]
### Current behavior

In Cypress E2E test, a few HTTP headers are not set. 
Specifically, `Content-Type` header is not set along with other headers with running with cypress that lead to 415 Content not supported error returned from the API gateway. 
The request doesn't reach the API server bacause of this.

### Desired behavior

`Content-Type` and other headers are set just like it behaves in a normal Chrome browser.

### Test code to reproduce

```js
describe("LoginForm component test", () => {
    it("normal login", () => {
        cy.visit("/login");
        cy.get("[data-cy='input-email']").type("[user@gmail.com](mailto:user@gmail.com)");
        cy.get("[data-cy='input-password']").type("password.123{enter}");
    });
});
```

### Cypress Version

13.6.3

### Node version

v20.10.0

### Operating System

macOS 14.2.1 (23C71)

### Browser console

![img_v3_027m_e33aba24-cad2-41d1-bcbf-a10a8c45136g](https://github.com/cypress-io/cypress/assets/8893623/1046fef6-d4e4-441e-a70a-fd4688a98a7e)

### Running console

![img_v3_027m_2bf823e2-463a-4fac-a1ac-324cfce4f20g](https://github.com/cypress-io/cypress/assets/8893623/cad57351-b195-4169-b805-7b2afddb4ccb)

### Business Logic code

![img_v3_027m_f9b34815-86df-4bb6-b304-c3341a424b7g](https://github.com/cypress-io/cypress/assets/8893623/177b177d-deee-4f12-b9b7-f822e6533f04)

### Expected Good Behavior on a regular browser

![img_v3_027m_95ac6e5e-076d-4177-bb9d-7e026200a3cg](https://github.com/cypress-io/cypress/assets/8893623/95d95dda-1306-405e-b085-09e18f1503c2)

### The behavior with cypress:open

missing headers with cypress

![img_v3_027m_01f634e3-4aa7-44a5-afdd-09befeb395dg](https://github.com/cypress-io/cypress/assets/8893623/122a7153-5163-469b-b7c1-d16608ee30d1)

**Comment by senpl** [comment]
Does it worked in previous cypress version ???

**Comment by robertwenquan** [comment]
this was cleared by either:
1. changed the ConnectTransport to WebTransport (grpc-web)
2. removed `experimentalFetchPolyfill: true` while keeping the ConnectTransport

But in the end we changed to WebTransport and disabled the `experimentalFetchPolyfill` as well.

**Comment by robertwenquan** [comment]
> Does it worked in previous cypress version ???

seems not related to previous version.

this was cleared by either:

1. changed the ConnectTransport to WebTransport (grpc-web)
2. removed experimentalFetchPolyfill: true while keeping the ConnectTransport

In the end we changed to WebTransport and disabled the experimentalFetchPolyfill as well.

**Comment by yordis** [comment]
Hey @jennifer-shehane any opportunity to get some attention from Cypress? I am trying my best to figure out the situation but I am not sure what else to try. The changes suggested by @robertwenquan didn't work me
