### ISSUE TITLE
Fail to run multiple test cases.

### ISSUE THREAD

**Issue by Ansab-Sajjad** [cypress-io/cypress#28853]
### Current behavior

Dear Cypress.io Team,

I hope this message finds you well. I am writing to bring to your attention an issue I have encountered while working with the latest versions of Cypress. It seems that the support for running multiple test cases has been impacted in the recent releases, particularly in version 11.

Bug Summary:
The problem arises when attempting to run multiple test cases concurrently in versions 11 and above. Unlike the previous versions, the execution of multiple test cases seems to be encountering unexpected behavior.

I am attaching 2 files of screen-recorded videos for reference at the bottom of this message. The one run with the older version (10.11.0) in which you can see that I have multiple test cases and all the test case runs perfectly. In the second one with the latest version (13.6.4) as you can see as Cypress moves to the second test case it loses all the URL which is in the first test case. I am facing this issue after V 10.11.0. I don't why this issue has not been fixed till now. 

This issue is affecting our testing workflow, and I believe it is crucial to bring it to your attention. I have checked the GitHub repository for similar issues but couldn't find one that precisely matches this problem.

I understand that you are likely busy, and I appreciate the effort you put into maintaining Cypress. Your assistance in addressing and resolving this matter would be highly valuable to the community.

If there are any additional details needed or if further clarification is required, please feel free to reach out. I am willing to provide any assistance necessary to help resolve this issue.

Thank you for your time and dedication to the Cypress.

Best regards,

Ansab Sajjad
ansab@troontechnologies.com.

[new version.webm](https://github.com/cypress-io/cypress/assets/115165376/9cebeb09-1809-4e8d-a5a7-827e18c4d53d)

[Older Version.webm](https://github.com/cypress-io/cypress/assets/115165376/1d4b37c7-ca57-4758-bb15-3ba9f8da0261)

### Test code to reproduce
```js
/// <reference types="cypress" />

describe("", () => {
  before(() => {
    // Save local storage before the test suite runs
    cy.saveLocalStorage();
  });

  beforeEach(() => {
    // Restore local storage before each test
    cy.restoreLocalStorage();
  });

  afterEach(() => {
    // Save local storage after each test
    cy.saveLocalStorage();
  });

  it("Visit to the URL", () => {
    cy.visit("https://practicetestautomation.com/practice-test-login/", {
      failOnStatusCode: false,
    }); // Local host HHH Server
  });

  it("Enter Username.", () => {
    cy.get("#username").type("student");
  });

  it("Enter Password.", () => {
    cy.get("#password").type("Password123");
  });

  it("Click on the Submit button.", () => {
    cy.get("#submit").click();
  });
});
```

### Cypress Version

13.6.4

### Node version

18.13.0

### Operating System

Window 11

**Comment by nickAdlard** [comment]
Going from v10 to 13 is a big jump, there might be a few gotchas in the changelog. Probably https://docs.cypress.io/guides/references/changelog#12-0-0 with `testIsolation`, there is a migration guide to help.
I think your style with building state from test to test in the same spec is more an antipattern with this test isolation on by default.
You might be able to mess with turning test isolation off, or condense all those individual tests into one larger test. I do build state up and go with the latter approach, just one big test in a spec that logs in and does a bunch of clicking and typing.

**Comment by Ansab-Sajjad** [comment]
@nickAdlard thanks for your reply. But it is my Client's requirement. I have to add multiple test cases. As you said for long test cases. If I am using it in long cases, as Cypress moves from one to the next it clears everything. In this situation, I'm not even able to run 2 cases in it.

**Comment by jennifer-shehane** [comment]
You can turn off `testIsolation` by setting it in your Cypress config to `false`. This should solve your issue although we do recommend running with isolated test cases for better stability.
