### ISSUE TITLE
Mac OS Chrome does not close after Cypress Run

### ISSUE THREAD

**Issue by Loren-Johnson** [cypress-io/cypress#28857]
### Test code to reproduce

I used the cypress example repo to replicate. experimentalMemoryMangement did not seem to affect anything

### Cypress Mode

cypress run

### Cypress Version

Cypress package version: 13.6.4 Cypress binary version: 13.6.4 Electron version: 25.8.4 Bundled Node version: 18.15.0 (also tried 13.5.1)

### Browser Version

Chrome Version 121.0.6167.139 (Official Build) (arm64)

### Node version

Bundled Node version: 18.15.0 but I have v20.11.0 install locally

### Operating System

MacOS Sonoma 14.3

**Comment by Loren-Johnson** [comment]
Memory Debug Logs for the two tests in the `examples/blogs__a11y`:
[{"checkMemoryPressureDuration":0.1779169999063015,"testTitle":"loads","testOrder":1,"garbageCollected":false,"timestamp":1706907733361}]

[{"checkMemoryPressureDuration":0.08091599959880114,"testTitle":"accessibility check","testOrder":1,"garbageCollected":false,"timestamp":1706907734452},{"getAvailableMemoryDuration":54.03462499938905,"getRendererMemoryUsageDuration":117.91429200023413,"jsHeapSizeLimit":4294705152,"totalMemoryLimit":17179869184,"rendererProcessMemRss":305823744,"rendererUsagePercentage":7.12094854422267,"rendererMemoryThreshold":2147352576,"currentAvailableMemory":10328670208,"maxAvailableRendererMemory":4294705152,"shouldCollectGarbage":false,"timestamp":1706907734579,"calculateMemoryStatsDuration":117.94237500056624}]

**Comment by wojciechpolak** [comment]
I just noticed the same thing recently. Google Chrome doesn't quit after the Cypress run (MacOS).

Cypress: 13.6.4
Chrome: 121

You can see it with `ps ux | grep -i chrome`

Before Cypress run:
`ps ux | grep -i chrome | wc -l` gives 1 (just the grep itself)

After Cypress run:
`ps ux | grep -i chrome | wc -l` gives 7 (including grep itself again)

I have to call `pkill -f 'Google Chrome'` to clean up.

**Comment by Loren-Johnson** [comment]
I'm not seeing this issue anymore with Chrome v122
