### ISSUE TITLE
significant proxy regression since v13.6.4

### ISSUE THREAD

**Issue by BWHoeben** [cypress-io/cypress#28867]
### Current behavior

When we upgraded from 13.6.3 to 13.6.4 we saw that some intercepts which usually took about 1 second to complete, suddenly took around 3 to 4 seconds to complete.

13.6.4 aimed to fixed this issue: https://github.com/cypress-io/cypress/issues/28734 which also mentions regression in performance. I suspect that the fix in 13.6.4 broke some other stuff

### Desired behavior

Reversal of the regression in performance

### Test code to reproduce

-

### Cypress Version

13.6.4

### Node version

20.6.1

### Operating System

ubuntu latest

**Comment by jennifer-shehane** [comment]
@BWHoeben Hi, we did identify a performance regressions around service workers that is tied to 13.6.4. https://github.com/cypress-io/cypress/issues/28868 Please read over the issue and let us know if this seems likely that it's contributing to your issue. 

If you're unsure if the above issue explains your issue, please send over a Test Replay link of a run where you saw the performance issue and we'll investigate.

**Comment by BWHoeben** [comment]
@jennifer-shehane we don't use Cypress could so I can not provide a Test Replay link.

What I've noticed: the request that are taking longer are POST-requests. They spend the majority of the time wait for server response. The issue doesn't occur when I run the affected tests in isolation

**Comment by jennifer-shehane** [comment]
@BWHoeben Do you have any service workers registered on your site? This describes why this could happen: https://github.com/cypress-io/cypress/issues/28868
