### ISSUE TITLE
Click event of an anchor within ul li not triggering the further events

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#28864]
### Describe the bug

Kindly consider the below HTML structure
```html
<div>
<a id="dropDown">Click Here To Open Dropdown</a>
<ul  id="selectoptions">
<li id="opt1" click-"CallServerAndUpdateStatus(1)"><a href="javascript:void(0);"> Option 1</a></li>
<li  id="opt2" click-"CallServerAndUpdateStatus(2)"><a href="javascript:void(0);">Option 2</a></li>
<li  id="opt3" click-"CallServerAndUpdateStatus(3)"><a href="javascript:void(0);">Option 3</a></li>
</ul>
</div>
```

```
.js
function  CallServerAndUpdateStatus(paravalue) {
 // console.log(324);
// alert(3443);
// call server api and on success or failure show respective message of passed and failed
}
```
When user click on an anchor with id dropDown. it opens the ul li dropdown. 
but then when user click on li button using below code. 

```js
cy.get("#dropDown").click().siblings(`ul#selectoptions").within(() => {
            cy.get("opt2").click();
        });
```        
 Click event didn't trigger. Though it closes the dropdown but expected behaviour is to trigger the server call and do the needful. 
     
It works fine in the previous version of cypress till 12.17.0 while in the current version after v13 its not working
     
     
![image](https://github.com/storybookjs/storybook/assets/17109022/92cd4f5e-cc9a-4696-8746-3414d94defb7)

### Desired behavior

Click event should trigger the respective handler and perform the actions. 

### Test code to reproduce

Already added in the description

### Cypress Version

13.6.0

### Node version

21.1.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
It's showing the actual element clicked as an `<a href="javascript">` element. Where is this on your page at the time of the click? We click at the middle of the location of the element, but sometimes the element may not be there at the time of click. 

We'd need a reproducible example in order to investigate whether this is a bug we can fix on our end.

**Comment by Prashant-Kan** [comment]
Updated.
Sorry, Forgot to add the anchor tag inside li.

**Comment by Prashant-Kan** [comment]
@jennifer-shehane I have updated the html content in the issue description 

let me know if its reproducible at your end or not

**Comment by jennifer-shehane** [comment]
Can you provide a failing test for us to run? I ran the given code and it passes and looks like it would require some css/js to recreate. 

`index.html`
```html
<html>
  <script>
  </script>
<body>
  <div>
    <a id="dropDown">Click Here To Open Dropdown</a>
    <ul id="selectoptions">
      <li id="opt1"><a href="javascript:void(0);"> Option 1</a></li>
      <li id="opt2"><a href="javascript:void(0);">Option 2</a></li>
      <li id="opt3"><a href="javascript:void(0);">Option 3</a></li>
    </ul>
  </div>
</body>
</html>
```

`test.js`
```js
it("Select dropdown", () => {
  cy.visit('index.html') 
  cy.get("#dropDown").click().siblings(`ul#selectoptions`).within(() => {
    cy.get("#opt2").click()
  })
})
```

![Screenshot 2024-02-27 at 4 31 31 PM](https://github.com/cypress-io/cypress/assets/1271364/7b1513a6-d777-46da-be41-cdeac24f0261)

**Comment by Prashant-Kan** [comment]
Thanks @jennifer-shehane spending time on this

It will not throw exception on click. 

if you setup something when user click on anchor like show some message or any other activity and assert that message text after click it will fail there 

I will try to send you the test code for the same. Meanwhile this is the steps to reproduce

**Comment by Prashant-Kan** [comment]
Hello @jennifer-shehane 

in your example. If you write a function and write some console.log or alert code (for us we are calling server side function).
Click => Command will get trigger and the testcase will pass but the function logic will not trigger./executed 

Scenario:-
By default the options (ie. li tags would be display:none). When click on dropdown arrow they will get display. 

Now, if there are 5-6 li then it will create problem. If there are less than 5 then its working fine. 

if there are more than 5 options (li) then first two will not able to select but rest other when trigger click its function logic gets executed

i.e in our case we are doing server call and updating some field or show message value which gets failed in assert. 

Could you try at your end ?

I would appreciate if you spend some time in this. 
we are waiting for this since long
