### ISSUE TITLE
`its` type should exclude `null` and `undefined`

### ISSUE THREAD

**Issue by eostrom-livefront** [cypress-io/cypress#28872]
### Current behavior

A Cypress test that relies on `its` to yield a value that is not `null` or `undefined` will be flagged as an error in TypeScript, even though the [docs assert](https://docs.cypress.io/api/commands/its#Assertions) that "`.its()` will automatically retry until it has a property that is not `null` or `undefined`."

### Desired behavior

Tests shouldn't have to handle values that can't occur.

### Test code to reproduce

```ts
describe('contrived example', () => {
  specify('log frameElement', () => {
    cy.window()
      .its('frameElement')
      .then(frameElement => {
        cy.log(frameElement.id)
      })
  })
})
```

This test runs (and passes, for what it's worth). But TypeScript reports:

```
cypress/e2e/scenarios/contrived.cy.ts:6:16 - error TS18047: 'frameElement' is possibly 'null'.

6         cy.log(frameElement.id)
                 ~~~~~~~~~~~~
```

In this example, I can work around it by logging `frameElement?.id || ''`, but it would be better not to have to. And although workarounds are probably always possible, they're not always that simple.

(My actual code involves a third-party analytics library that adds a property to `window` with an object I want to stub, but the property isn't available immediately on page load, so I have to wait for it. In JavaScript, `its` is great for that! But I'm converting the tests to TypeScript, and TypeScript doesn't know it's great in that way.)

### Cypress Version

13.6.4

### Node version

18.17.0

### Operating System

MacOS 14.2.1

### Other

It looks to me like this can be fixed by making the resulting `Chainable` subject non-nullable – changing:

```ts
    its<K extends keyof Subject>(propertyName: K, options?: Partial<Loggable & Timeoutable>): Chainable<Subject[K]>
```

to:

```ts
    its<K extends keyof Subject>(propertyName: K, options?: Partial<Loggable & Timeoutable>): Chainable<NonNullable<Subject[K]>>
```

I did that as a local override, and my TypeScript errors went away. That may or may not be the best solution.

**Comment by AkshatHotCode** [comment]
@eostrom-livefront Yes, your proposed fix makes sense and is a reasonable solution to address the TypeScript error. By changing the return type of its to Chainable<NonNullable<Subject[K]>>, you are explicitly stating that the property accessed with its will not be null or undefined. This aligns with the behavior documented in Cypress, where it automatically retries until it has a property that is not null or undefined. 
Created a PR as well.
