### ISSUE TITLE
Cypress stop to open e2e test url

### ISSUE THREAD

**Issue by alunov-equinix** [cypress-io/cypress#28870]
### Current behavior

Cypress stop to open e2e test url in a new cypress browser tab since version 13.5.0 and later. Instead it opens it in default browser

### Desired behavior

Clicking url should open a new tab within cypress browser with app running based on mocks(cy.intercept) form the latest test

### Test code to reproduce

Use any cypress version after 13.4.0, open any e2e test and click on url in the window with app.

### Cypress Version

From 13.5.0

### Node version

18.18.0

### Operating System

macOS 13.6.3

**Comment by jennifer-shehane** [comment]
We changed the behavior of opening new tabs, where some of that work went into 13.5.0. This was in efforts to offer better support for multiple tabs testing with the puppeteer plugin.

We never intended to support the use of new tabs within the Cypress browser - and encourage everyone to use their default browser instead. Opening new tabs could interfere with currently running tests.
