### ISSUE TITLE
On executing the cypress test cases for safari browser using webkit getting tcp errors in github actions

### ISSUE THREAD

**Issue by deepankar-sajwan** [cypress-io/cypress#28889]
### Current behavior

<img width="859" alt="image" src="https://github.com/cypress-io/cypress/assets/96309135/82ea7d85-3406-4ac5-bfdd-a5d2746aef9f">

### Desired behavior

The cypress test cases should execute in github

### Test code to reproduce

Not able to provide repo as it is not open source

### Cypress Version
12.16.0

### Node version

16.20.0

### Operating System

ubuntu-latest

### Debug Logs

File containing debug logs
https://docs.google.com/document/d/1bFpZ2Zx-BizlrsvNAe_viCixBwE5G7L6PddNHuZLxek/edit?usp=sharing

### Other

Using playwright-webkit-1.34 for running test cases on safari

**Comment by MikeMcC399** [comment]
Also discussed in https://discord.com/channels/755913899261296641/1202932321238646874

**Comment by deepankar-sajwan** [comment]
Please refer below file for cypress logs
https://docs.google.com/document/d/1bFpZ2Zx-BizlrsvNAe_viCixBwE5G7L6PddNHuZLxek/edit?usp=sharing

**Comment by deepankar-sajwan** [comment]
Tried the cypress and webkit package version available in below github task
https://github.com/cypress-io/cypress/issues/26996

It did not resolved the issue, getting same error

**Comment by deepankar-sajwan** [comment]
Hi can anybody provide a solution for resolving this issue

**Comment by MikeMcC399** [comment]
@deepankar-sajwan 

I looked at your logs and I saw that you are using `cypress-io/github-action@v3`. This version is no longer supported and you should be using  [cypress-io/github-action@v6](https://github.com/cypress-io/github-action) instead. I don't expect this will solve your issue, however when troubleshooting it is best to rule out any influence from using old versions.

I'm sorry that I don't have the in-depth experience with WebKit to help you further here. Good luck!

**Comment by MikeMcC399** [comment]
@deepankar-sajwan 

Have you tried updating to [cypress-io/github-action@v6](https://github.com/cypress-io/github-action)?
