### ISSUE TITLE
Cypress dashboard always returns a Passing test run result if the ci-build-id is reused

### ISSUE THREAD

**Issue by matt-misiurak** [cypress-io/cypress#28880]
### Current behavior

After a test run has been executed and completed in CI with a `ci-build-id`, the Cypress dashboard will always return a Passing test run result if the `ci-build-id` is reused.

### Desired behavior

After a test run has been executed and completed in CI with a `ci-build-id`, the Cypress dashboard returns the previous result. (If the test run was already executed and Failed, the Cypress dashboard should return a failing result)

### Test code to reproduce

Any repo that is utilizing the Cypress dashboard with parallel testers in CI should see this issue. Execute the command below in CI against a repo which contains a test that you know will fail. Wait for the test run to complete then re-execute the command below. No tests will be ran (expected), but the test run result will always be a Pass (unexpected). 

`yarn cypress run --record --key=${CYPRESS_RECORD_KEY} --parallel --ci-build-id=${CI_BUILD_ID}`

### Cypress Version

13.5.0

### Node version

18.5.0

### Operating System

macOS 14.3

**Comment by jennifer-shehane** [comment]
@matt-misiurak You need to pass a unique ci-build-id for any new runs that are starting beyond the [run completion delay](https://docs.cypress.io/guides/cloud/smart-orchestration/parallelization#Run-completion-delay).
