### ISSUE TITLE
Cypress does not retry tests after a hot reload

### ISSUE THREAD

**Issue by shennan** [cypress-io/cypress#28917]
### Current behavior

Running the specs in Cypress's Chrome test runner, when I make changes to a spec file and save, Cypress acknowledges the save by dumping the current test results, white-screening the preview area and moving to the first test in the current spec; but does not run the tests again. I need to press the "Stop Running (S)" button at the top of the spec sheet and then the "Run All Tests (R)" button before all tests are run again.

If I don't press these buttons then it stays like the below image, with a continuously animated loading sprite next to the first test:

<img width="414" alt="Screenshot 2024-02-11 at 10 38 40" src="https://github.com/cypress-io/cypress/assets/1840398/5d7f91f5-7830-400b-8a3b-03f4c236e48b">

It will do this indefinitely until further actual is taken.

### Desired behavior

The tests are simply re-run once a file has changed. Or, at least, the test runner is put in a "stopped" state such that only one button click is needed to restart.

### Test code to reproduce

Works on any tests. My config:

```typescript
export default defineConfig({
  watchForFileChanges: true,
  e2e: {
    /** nothing **/
  }
})
```

### Cypress Version

13.6.4

### Node version

16.19.1

### Operating System

macOS Ventura 13.1

**Comment by mszkb** [comment]
Duplicate of #28392

**Comment by shennan** [comment]
Thanks @mszkb, you're correct this does appear to be a duplicate. Using the [current workaround](https://github.com/cypress-io/cypress/issues/28392#issuecomment-1852735772) does indeed fix the issue. I'll subscribe to the other thread for updates on a permanent fix.

Closing.
