### ISSUE TITLE
cypress stuck on installation

### ISSUE THREAD

**Issue by Venki4746l** [cypress-io/cypress#28927]
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/81453194/8c5cdb2c-a276-48ca-bcf2-a26a34485230)
When I Try to install Cypress it does not start the downloading show above message for a long time 

### Cypress Version

10.11.0

### Node version

12.14.1

### Package Manager

npm

### Package Manager Version

6.13.4

### Operating system

Windows

### Operating System Version

10

**Comment by MikeMcC399** [comment]
@Venki4746l 

Cypress `10.11.0` is an older version (the current version is `13.6.4`)
Node.js `12.14.1` is no longer supported. The minimum is Node.js `18`.

You can try the following, assuming you are using Windows PowerShell

```shell
npm install cypress --save-dev --ignore-scripts --verbose
$env:DEBUG = "cypress:*"
npx cypress install
```

This will output debug information so you can see what it is doing and the reason for any delay.

If it is not installing successfully, then the most likely reason is your environment, such as network connection, proxy, network security, etc.

**Comment by ikbenpinda** [comment]
Hello, I was having a similar issue, but with a newer version of Cypress(`13.6.4`), Node(`18.17.0`), and Yarn(`4.1.0`) instead of npm.
I'm using Windows 10. In my case I expect it's an issue with the VPN/VDI I'm using, similar to what's mentioned above.

In case it helps, I had to do the following:

```shell
# using git-bash instead of cmd/powershell
export DEBUG=cypress:*
export HTTP_PROXY=http://YOUR_USERNAME_HERE:YOUR_PASSWORD_HERE@YOUR_PROXY_URL_HERE:YOUR_PROXY_PORT_HERE/
yarn install cypress

# < check the URL it's downloading from and click on it / paste it in your browser for a direct download that isn't latest >
# hit CTRL+C to cancel as it will remain stuck as mentioned, then:

cd ~/AppData/Local/Cypress
mkdir 13.6.4
cp ~/Downloads/cypress.zip ~/AppData/Local/Cypress/13.6.4
cd ~/AppData/Local/Cypress/13.6.4
unzip cypress.zip

# cleanup
rm cypress.zip
export DEBUG=
```

After this, I was able to run cypress as usual.

**Comment by wigy** [comment]
It still does the same. Node v18.19.0, Cypress 13.11.0. Tested on Linux.

**Comment by MikeMcC399** [comment]
@wigy 

> It still does the same. Node v18.19.0, Cypress 13.11.0. Tested on Linux.

This is generally a network issue. It is not a general problem with the release. You can try the debug steps I posted in https://github.com/cypress-io/cypress/issues/28927#issuecomment-1942006888.

You can also request assistance from the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

**Comment by ntalamdotcom** [comment]
stuck at:
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1303ms   
npm info run cypress@13.14.2 postinstall node_modules/cypress node index.js --exec install    
npm info run cypress@13.14.2 postinstall { code: 0, signal: null }

added 72 packages, changed 55 packages, and audited 883 packages in 13m

187 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

it is not a network issue. tried 2 different connections

**Comment by MikeMcC399** [comment]
@ntalamdotcom 

The same comments apply as previously and you can check https://github.com/cypress-io/cypress/issues/28927#issuecomment-1942006888 for some debug steps. It's almost always an individual local system, security or network issue if Cypress does not install.

This is a closed issue, so it's unlikely to get further attention. You can open a new issue with your full details and debug logs if you think it is a Cypress bug.  If you need community assistance use https://on.cypress.io/discord.
