### ISSUE TITLE
Test Runner doesn't close and auto relaunch in Version 13.6.4

### ISSUE THREAD

**Issue by gurudattgd04** [cypress-io/cypress#28929]
### Current behavior

When we Close the Test runner window by clicking on Close button, the test runner closes but again auto launches.

This is not observed in version 13.6.3 and hence this is something introduced in 13.6.4

### Desired behavior

 Test runner window should close and shouldn't auto relaunch when clicked on Close button

### Test code to reproduce

Click on the Close button from cypress window
<img width="1055" alt="image" src="https://github.com/cypress-io/cypress/assets/5640396/896254f8-55a6-4a8f-9252-40a905ac830a">

Observe that Test runner where specs are listed, closes and again auto relaunch

### Cypress Version

13.6.4

### Node version

18.19.0

### Operating System

14.3

**Comment by MikeMcC399** [comment]
- This is a duplicate of issue https://github.com/cypress-io/cypress/issues/28852
- The issue is fixed by PR https://github.com/cypress-io/cypress/pull/28860 and queued for the next release of Cypress

**Comment by gurudattgd04** [comment]
Thanks @MikeMcC399  For confirming.

**Comment by gurudattgd04** [comment]
Closing this based on the confirmation
