### ISSUE TITLE
Cypress does not clear `cookies` and `localStorage` on startup when `testIsolation` is `false`

### ISSUE THREAD

**Issue by nbouvrette** [cypress-io/cypress#28935]
### Current behavior

I am starting tests, and I would expect that when launching Chrome is starts without any cookies (and local storage) but it keeps the same infromation as the previous test run.

This issue only seems to happen when setting `testIsolation` to `false` since otherwise `cookies` and `localStroage` will be cleared before every test.

### Desired behavior

I would expect that when launching Cypress, the environment starts without any state from previous test runs.

### Test code to reproduce

Just install the latest Cypress version, run test on an application that has cookies. Close the test, re-open Cypress and inspect your cookies.

### Cypress Version

latest

### Node version

v20.5.0

### Operating System

macOS 14.2.1

**Comment by jennifer-shehane** [comment]
How are you closing the test in this case? 

> Close the test, re-open Cypress and inspect your cookies.

**Comment by nbouvrette** [comment]
@jennifer-shehane I tried both closing Chrome and Cypress "normally" and also doing a `CTRL-C` in my console - both arrive at the same result in my case which is that session cookies are cleared but cookies with an expiry date from the previous tests are still there, including the `localStorage`

This is even worse for cookies that are set by API calls (`httpOnly`) since Cypress cannot clear those cookies as far as I am aware... so the only way to get Cypress back into a usable state is to manually clear cookie in the browser as far as I am aware.

**Comment by nbouvrette** [comment]
Just to clarify, this issue only occurs when using `testIsolation: false`. Here are more details on how to replicate:

```ts
before(() => {
    console.log('getAllCookies')
    cy.getAllCookies()
      .then((cookies) => {
        console.log(`inside getAllCookies`)
        console.dir(cookies, { depth: null })
      })
      .then(() => {
        cy.clearAllCookies().then(() => {
          console.log(`after clearAllCookies`)
        })
      })
      .then(() => {
        cy.getAllCookies().then((cookies) => {
          console.log(`inside getAllCookies (after clearAllCookies)`)
          console.dir(cookies, { depth: null })
        })
      })
      .then(() => {
        cy.visit(`/`)
      })
      .then(() => {
        cy.getAllCookies().then((cookies) => {
          console.log(`inside getAllCookies (after visiting page)`)
          console.dir(cookies, { depth: null })
        })
      })
      .then(() => {
        throw new Error('stop')
      })
  })
```

Of course, in this example, visiting `/` will set cookies - here is what my console looks like when running this on the first run:

<img width="306" alt="image" src="https://github.com/cypress-io/cypress/assets/6453322/72395f93-9c54-44d6-823f-1bf3865fca1d">

Now, if I stop Cypress, and restart it and run the same test again:

<img width="298" alt="image" src="https://github.com/cypress-io/cypress/assets/6453322/c96a1ebb-b956-4bf9-b354-fb4936771996">

We can see that even at startup, before visiting any page, it still has a cookie.

I tried closing Cypress by quitting Chrome and Cypress, by using the "Close" button in the Cypress app, and using `CTRL-C` in the console, and they all ended up with the same result.

I think it would be expected that when Cypress starts, it clears all cookies and local storage without having to do it manually or without having to use sessions or test isolation.

Otherwise, this means that if any test fails and we restart Cypress, the previous browser state will be persisted, and it's impossible to guarantee reliable tests.

Right now, I am planning to use [session](https://docs.cypress.io/api/commands/session) as a workaround, but I still think that this behavior is probably not expected.

I'm also updating the issue with those new details for clarity.
