### ISSUE TITLE
V13.6.4: DOM constantly switching between request and response

### ISSUE THREAD

**Issue by PetMou** [cypress-io/cypress#28931]
### Current behavior

After running a test in open mode, wanting to inspect the screen at a certain point in the test, the screen is constantly toggling between request and response, thus making it very difficult analyze. I have found no way to stop the constant toggling.
Cypress on Windows, chrome version 121.0.6167.161.

### Test code to reproduce

This happens in all tests. 

### Cypress Version

13.6.4

### Node version

v18.18.2

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment]
@PetMou We haven't seen an issue described like this before. Could you share a video? Could you share an example code that reproduces the issue?

**Comment by PetMou** [comment]
I found the cause of the error. Between my keyboard and the back of my chair...

**Comment by airhorns** [comment]
@PetMou what was causing this for you? This happens to me all the time and I don't know why or what I am doing wrong, and I have to hard refresh to fix it! I will try to record it next time for the cypress team.

**Comment by ReginkaD** [comment]
Is it because of mouse is over some GET for example in SPECS section?

**Comment by gabrielhpugliese** [comment]
What's the fix to this? It's terribly annoying and I am not doing anything different. I am not hovering any line.

**Comment by ReginkaD** [comment]
Hm... if you are not hovering anything on the left, so I don't really know

**Comment by russell-knight** [comment]
I'd also like to know what you did to cause/fix this? Same issue is happening to me now

**Comment by stephenfrench9** [comment]
seemed to help me:

```
  e2e: {
    hideXHRInCommandLog: true,
  },
```
