### ISSUE TITLE
Cannot install cypress on Ubuntu 22.04

### ISSUE THREAD

**Issue by nicfv** [cypress-io/cypress#28944]
### Current behavior

Hello! There is something strange going on with the installation, whenever I run `npm install` or `npm i`, I get this error (with verbose option.) It does not create `package-lock.json` nor `node_modules` and of course, nothing is actually installed. Here's where the error actually starts:

```log
1002 verbose stack Error: command failed
1002 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
1002 verbose stack     at ChildProcess.emit (node:events:518:28)
1002 verbose stack     at maybeClose (node:internal/child_process:1105:16)
1002 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
1003 verbose pkgid cypress@13.6.4
1004 verbose cwd /home/nic/Desktop/grafana-v10.3.3/data/plugins/test-npm
1005 verbose Linux 6.5.0-17-generic
1006 verbose node v20.11.1
1007 verbose npm  v10.4.0
1008 error code 1
1009 error path /home/nic/Desktop/grafana-v10.3.3/data/plugins/test-npm/node_modules/cypress
1010 error command failed
1011 error command sh -c node index.js --exec install
1012 verbose exit 1
```

This is with an absolutely clean directory with only a `package.json` file created by `npm init -y`. I've also tried installing other versions of cypress, but with similar results. I have no idea what the issue may be- please help!

### Desired behavior

I expect to be able to install this dependency with no errors.

### Test code to reproduce

```shell
npm init -y
npm install --verbose cypress@13.6.4
```

### Cypress Version

Any (I've tried many versions including latest)

### Node version

Node 20.11.1, NPM 10.4.0

### Operating System

Ubuntu 22.04

### Debug Logs

```shell
N/A
```

### Other

See the installation log here: [log.log](https://github.com/cypress-io/cypress/files/14289528/log.log)

**Comment by nicfv** [comment]
These issues _may_ be related:
- https://github.com/cypress-io/cypress/issues/28862
- https://github.com/cypress-io/cypress/issues/27384

**Comment by MikeMcC399** [comment]
@nicfv 

Your installation is failing in the postinstall phase. Try the following to get debug information for this phase as well.

```shell
npm install cypress --save-dev --ignore-scripts --verbose
export DEBUG=cypress:*
npx cypress install
```

**Comment by MikeMcC399** [comment]
@nicfv 
Did you make progress here?

**Comment by jennifer-shehane** [comment]
Closing as stale.

**Comment by lucasazevedo01** [comment]
I also need help, I can install Cypress on Ubuntu 22.04 LTS but it simply stops responding and consequently crashes and displays the following error


The Test Runner unexpectedly exited via a close event with signal SIGKILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 22.04)
Cypress Version: 13.7.0
