### ISSUE TITLE
[Electron 28] - EPIC - Upgrade

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#28943]
### What would you like?

Electron 28 released on Dec 4, 2023. https://releases.electronjs.org/releases/stable?page=5&limit=2

After we update to Electron 27, we should update to Electron 28 to get the latest updates and newer Chromium version for our users. 

[See instructions on updating Electron](https://github.com/cypress-io/cypress/blob/ad99300a5f1a23d336c317600e702a6406fea4a6/packages/electron/README.md#upgrading-electron)

**Comment by nnaydenow** [comment]
Hi @jennifer-shehane,

When we can expect that upgrade to be done?

**Comment by jennifer-shehane** [comment]
@nnaydenow There's a PR open for it here: https://github.com/cypress-io/cypress/pull/28959

Unfortunately there is a breaking change in Electron 28 that would affect our users. That breaking change has been fixed in Electron 29, but Electron 29 contains a bug in v8 that we've had to raise with Chromium here: https://issues.chromium.org/issues/345280736 We're awaiting to see what their response is as we need a resolution to continue our upgrade.
