### ISSUE TITLE
Flake: errors ui assertion failures

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#28942]
We have a lot of 'Error UI' failures and flake in our internal Cypress tests, especially within running in Windows. 

- [Example failing CI run ](https://app.circleci.com/pipelines/github/cypress-io/cypress/59793/workflows/1dcc7ec4-0def-4945-a47b-d85ecb39f641/jobs/2487508/tests)
- [Example Test Replay - Failing](https://cloud.cypress.io/projects/ypt4pf/runs/54020/overview/916da185-ef06-4a3d-80d1-79c659b29100/replay?att=1&pc=log-http%3A%2F%2Flocalhost%3A4455-6811__command-logs&roarHideRunsWithDiffGroupsAndTags=1&ts=1707937275739.9)
- [Example Test Replay - Passing - Linux](https://cloud.cypress.io/projects/ypt4pf/runs/54017/test-results/6d285ef9-3bcb-48ec-972d-d32ef4ec450b/replay?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22runner%2Freporter.command_errors.cy.ts%22%2C%22value%22%3A%22%5B%5C%2276882abe-8357-4ed8-bfaa-fe1a027fdcd7%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)
- [Example Test Replay - Passing - Windows](https://cloud.cypress.io/projects/ypt4pf/runs/53872/test-results/6d225547-21d3-4c3a-84ee-5a96235aee2e/replay?actions=%5B%5D&att=1&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%7B%22label%22%3A%22Windows%22%2C%22value%22%3A%22win32%22%7D%5D&specs=%5B%7B%22label%22%3A%22cypress%5C%5Ce2e%5C%5Crunner%5C%5Creporter.command_errors.cy.ts%22%2C%22value%22%3A%22%5B%5C%223bc66b1b-1eb6-4f55-93ab-bb531534d148%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D&ts=1707164701139.5)

### Failing
![Image](https://github.com/cypress-io/cypress/assets/1271364/e596f159-10da-4526-88a3-f2455d885485)

### Passing
![Screenshot 2024-02-14 at 2 43 05 PM](https://github.com/cypress-io/cypress/assets/1271364/47034003-7bb7-4a2d-bcad-a70b443d68a1)

The test is expecting to find this area, where the error frame is rendered with the filepath `cypress/e2e/errors/spread.cy.js`

![Screenshot 2024-02-14 at 2 44 24 PM](https://github.com/cypress-io/cypress/assets/1271364/312bd349-3c95-4c6d-9283-0e97ebe69d9f)

But the page is actually rendering this, with a different error and no error frame.

![Screenshot 2024-02-14 at 2 45 37 PM](https://github.com/cypress-io/cypress/assets/1271364/cde223ae-375a-4c9b-9d2f-5b5d5afe07c5)

**Comment by AtofStryker** [comment]
This is currently really hard to see in Windows CI due to the errors with the app server not being reachable. I'm trying to figure out why this is happening first in order to be able to investigate this issue further. 
![Screenshot 2024-03-01 at 9 43 24 AM](https://github.com/cypress-io/cypress/assets/3980464/477d9892-928f-4033-b736-5ddcf7cd270f)
