### ISSUE TITLE
ENOTDIR Error when i launched cypress run

### ISSUE THREAD

**Issue by DcComicsansms** [cypress-io/cypress#2894]
Hello, 

I have installed Cypress on Debian 9 (fresh install) with NPM.

When i launched `cypress run`, i get an error 

### Current behavior:

```
/opt/cypress/node_modules/.bin# ./cypress run

ENOTDIR: not a directory, mkdir '/opt/cypress/node_modules/.bin/cypress/plugins'
Error: ENOTDIR: not a directory, mkdir '/opt/cypress/node_modules/.bin/cypress/plugins'
```

### Steps to reproduce:

```
cypress run
```

### Versions

Cypress package version: 3.1.3
Cypress binary version: 3.1.3

**Comment by jennifer-shehane** [comment]
Hey @DcComicsansms Could you elaborate more on your project's file structure? What directory you were in when installing Cypress? 

The node_modules are not typically within the `cypress` folder itself and usually within the project root.

**Comment by kwoxer** [comment]
Got the same error. But got it running with the following commands.
1. removing cypress again via "sudo rm -r *"
2. npm install cypress --save-dev
3. ./node_modules/cypress/bin/cypress run

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by shravanrai** [comment]
I got the same issue. the mistake I was doing was running "./cypress open" command from the leaf folder.  Resolution: run " ./node_modules/cypress/bin/cypress open" from project root folder.

**Comment by EngErik** [comment]
> I got the same issue. the mistake I was doing was running "./cypress open" command from the leaf folder. Resolution: run " ./node_modules/cypress/bin/cypress open" from project root folder.

Works for me!

**Comment by tejprakash-mehta** [comment]
> I got the same issue. the mistake I was doing was running "./cypress open" command from the leaf folder. Resolution: run " ./node_modules/cypress/bin/cypress open" from project root folder.

It worked for me
