### ISSUE TITLE
action commands support for web components

### ISSUE THREAD

**Issue by nnaydenow** [cypress-io/cypress#28963]
### What would you like?

Currently, Cypress encounters limitations when interacting with custom web components provided by third-party libraries. While attempting to utilize Cypress interaction commands such as .focus() and .type(), Cypress may encounter issues, especially with web components that encapsulate native input elements within their Shadow DOM.

For instance, when attempting to focus on a custom <my-input> element and type text into it, Cypress may incorrectly determine that the element is not focusable, even if it contains a native input element within its Shadow DOM.

Similarly, when dealing with custom buttons like <my-button>, Cypress may fail to recognize them as focusable elements, hindering the ability to simulate interactions such as pressing the Enter key.

Enhanced Interaction Commands: Interaction commands such as .focus() and .type() should seamlessly interact with web components, allowing testers to simulate user actions effectively.

### Why is this needed?

We want to test our application, which relies heavily on a web components library.

**Comment by jennifer-shehane** [comment]
@nnaydenow Are you able to provide examples where Cypress doesn't behave as expected. We have the cy.shadow command to interact with Shadow DOM: https://docs.cypress.io/api/commands/shadow And would need examples in order to fix these specific bugs as we do have intended support for this already.

**Comment by nnaydenow** [comment]
Hi @jennifer-shehane,

I've prepared example with type where you can test:
https://github.com/nnaydenow/cypress-example

Overall, since we regularly update and we can't rely on the shadom DOM structure I want to ask if it's expected from us to regularly align all of our test even if the components provide focus delegation to the correct element and etc.. ?

**Comment by jennifer-shehane** [comment]
@nnaydenow I see. In this case, we don't know whether a web component is typeable given the element name and attributes. You could try adding a `tabindex` to the typable element - that allows typing. I'm not sure how else we would determine a web component is typeable. 

![Screenshot 2024-02-19 at 1 22 19 PM](https://github.com/cypress-io/cypress/assets/1271364/ead0136b-3590-4fae-8c54-ab5fff119c29)

**Comment by nnaydenow** [comment]
Hi @jennifer-shehane,

Thanks for the proposal, but this requires a lot of works again. Writing custom commands that work with current shadow DOM and to reuse them everywhere seems like a better solution so we can align them on a single place after update.

Do you plan somehow to add special handling of web components in the actions?

I'm closing the issue since we have to handle it on our side. :)

Regards,
Nayden

**Comment by jennifer-shehane** [comment]
I'm not sure on initial thinking how we would distinguish between a web component that is typeable vs any other element that is not typeable without some other attribute like tabindex or contenteditable. If we can't determine what a typeable element is definitively, then we can't properly catch errors where users may have chosen a wrong target to type. We don't have any plans right now to update this logic.

**Comment by rstoneIDBS** [comment]
Just found this issue while investigating the same problem. 

In our case we have web components that take advantage of https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#delegatesfocus to specify that focus should be transferred into the shadow dom. You can check for this via ``shadowRoot.delegatesFocus`` so this could be an option for Cypress maybe?

The alternative would be to add a ``force`` option on the focus() call (just like you do for other interaction types) which overrides the check in Cypress
