### ISSUE TITLE
force quit

### ISSUE THREAD

**Issue by tamilsandro** [cypress-io/cypress#28965]
### Current behavior

After installing it to Ubuntu for the first time run the sample file the next time It says vs code is not responding Cypress also freezes

### Cypress Version

8.15.0

### Node version

v16.17.0

### Package Manager

npm

### Package Manager Version

v16.17.0

### Operating system

Linux

### Operating System Version

22.04

**Comment by tamilsandro** [comment]
![Screenshot from 2024-02-19 17-44-42](https://github.com/cypress-io/cypress/assets/160408606/2303b428-00ea-4dca-befa-a20e383b0e9f)

**Comment by tamilsandro** [comment]
/__cypress/assets/favicon.png?v2 404 0.621 ms - 136
I do know exactly in cypress@11.2.0 self cypress is not working in Ubuntu vs code shows force quiet

**Comment by MikeMcC399** [comment]
@tamilsandro 

Your versions are a little confusing, in your original post, you write that you are using Cypress `8.15.0`. This version does not exist.
In your screenshot https://github.com/cypress-io/cypress/issues/28965#issuecomment-1952327596 it shows you are using Cypress 13.6.4, which is the latest version.
In https://github.com/cypress-io/cypress/issues/28965#issuecomment-1953531021 you write that you are using `cypress@11.2.0 `

You write also that you are using Node.js `v16.17.0`. This version is no longer supported. The current Long Term Support version according to https://nodejs.org/en is `20.11.1`.

Are you able to test with Cypress `13.6.4` and Node.js `20.11.1`?

Are you running Ubuntu directly or are you using some virtualization like Microsoft WSL2 or VMware Workstation?

**Comment by tamilsandro** [comment]
@MikeMcC399  I acknowledge that the issue is on my end, as you mentioned that the cypress and node versions are functioning properly
