### ISSUE TITLE
Run Timer Doesn't Stop on Run Completion on the Latest Runs Dashboard

### ISSUE THREAD

**Issue by samelawrence** [cypress-io/cypress#28972]
### Current behavior

When viewing the Latest Runs view in the Cypress Dashboard, if a Run completes, the app UI will update to show a green check-mark, but the timer will not stop running. The timer will show the correct time after a page reload.

[Video](https://youtu.be/ne7x4O6zrVs)

### Desired behavior

The timer should stop running and display the correct elapsed time.

### Test code to reproduce

n/a

### Cypress Version

13.6.4

### Node version

18.19.0

### Operating System

macOS 13.5.1

**Comment by jennifer-shehane** [comment]
@samelawrence Thanks for the feedback. I've forwarded this report to our Cloud team and will close the issue on the OS repo since this is reserved for issues around the OS products.
