### ISSUE TITLE
Not able to use timeout with cy.xpath()

### ISSUE THREAD

**Issue by artste14** [cypress-io/cypress#28983]
### Current behavior

- When using `cy.xpath('xpath', { timeout: 3000 })` the timeout that is taken is the one set in "`defaultCommandTimeout:`" (which in this case is 20000) in the `cypress.config.js` file and not the 3000 that I am actually interested in

### Desired behavior

Cypress should take into account the timeout I set at `cy.xpath('xpath', { timeout: 3000 }) ` 

### Test code to reproduce

`cy.xpath('xpath', { timeout: 3000 }) `where as a 'xpath' you should put any correct xpath selector. In addition, you need to set the value of defaultCommandTimeout in the `cypress.config.js` file to something other than 3000 to see if what the behavior will be

### Cypress Version

13.6.4

### Node version

v14.18.1

### Operating System

Windows 11 Business Version	22H2

**Comment by MikeMcC399** [comment]
@artste14 

See https://github.com/cypress-io/cypress/tree/develop/npm/xpath

# @cypress/xpath

> @cypress/xpath has been deprecated and is no longer supported.

Also Node.js `14` has passed end-of-life and is no longer supported.
