### ISSUE TITLE
Cypress not opening links clicked within the Test Runner in a new tab of same browser window

### ISSUE THREAD

**Issue by shubhamladhe15** [cypress-io/cypress#28984]
### Current behavior

Cypress not opening links clicked within the Test Runner in a new tab of same browser window. It is opening in new default browser.
<img width="1679" alt="Screenshot 2024-02-21 at 6 03 12 PM" src="https://github.com/cypress-io/cypress/assets/127134338/fd0efde0-6269-449f-a2a5-f2242ab70b6e">

### Desired behavior

Cypress should open the ongoing visiting link with the test runner in the new tab within the same browser.

### Test code to reproduce

1. Visit any link in the test.
2. Open Headed mode.
3. In test runner click on the current page visit link.
4. Link should get opened within new tab within same browser window.

### Cypress Version

13.6.5

### Node version

18.17.0

### Operating System

macOS 14.1.2

**Comment by jennifer-shehane** [comment]
This was an intentional change introduced in 13.5.0.

**Comment by shubhamladhe15** [comment]
@jennifer-shehane How to keep this behavior as same as earlier? is there any way to retain this? Can you please guide me?

**Comment by jennifer-shehane** [comment]
@shubhamladhe15 There's not. What's the use case for this? We want to discourage using the Cypress browser as a regular browser and isolate it to just testing.

**Comment by shubhamladhe15** [comment]
@jennifer-shehane We have 2FA enabled for the users we are using in the automation as per software requirement. The 2FA tokens are generating on run time and we don't have any control over the manual login of those users. Suppose if any issues encountered related to specific user then for debugging purpose we were using that session of the user who has logged in using the automation test and we were performing debugging for same. So simply we were getting active sessions to check for same issues manually in cypress browser.
