### ISSUE TITLE
Security issue: Prototype Pollution in async

### ISSUE THREAD

**Issue by pavikrishna** [cypress-io/cypress#28989]
### Current behavior

A vulnerability exists in Async through 3.2.1 for 3.x and through 2.6.3 for 2.x (fixed in 3.2.2 and 2.6.4), which could let a malicious user obtain privileges via the mapValues() method.

### Desired behavior

Bump async to non vunerable version 

### Test code to reproduce

Run, yarn why async -R, give the below results. 
─ cypress@npm:13.6.4 (via npm:^13.6.4)
   │  └─ getos@npm:3.2.1 (via npm:^3.2.1)
   │     └─ async@npm:3.2.0 (via npm:^3.2.0)

### Cypress Version

cypress@npm:13.6.4

### Node version

v18.17.0

### Operating System

macos

**Comment by MikeMcC399** [comment]
@pavikrishna 

Have you tried running
```shell
yarn up async -R
```
to update the dependency in your project?

```text
$ yarn why async -R
└─ example-yarn-modern@workspace:.
   └─ cypress@npm:13.6.6 (via npm:13.6.6)
      └─ getos@npm:3.2.1 (via npm:^3.2.1)
         └─ async@npm:3.2.5 (via npm:^3.2.0)
```

**Comment by MikeMcC399** [comment]
@pavikrishna 

Please let us know if the suggestion has solved your issue.

**Comment by pavikrishna** [comment]
yes , the above suggestion fixed it! thank you!
