### ISSUE TITLE
Cypress is not running on Chrome 71

### ISSUE THREAD

**Issue by lourenci** [cypress-io/cypress#2899]
### Current behavior:

After the upgrade to Chrome 71, Cypress is throwing a cross-origin frame error (image below). If I downgrade my Chrome to 70 or run the tests with the Electron version, the tests run.

![image](https://user-images.githubusercontent.com/2339362/49479802-75d4a900-f80b-11e8-9d34-87d36b5dd16a.png)

### Versions

* Chrome 71
* Cypress 3.1.2
* OS: Mac and Linux

**Comment by lourenci** [comment]
@jennifer-shehane it breaks on `cy.visit('/')`, the spec's very first line. 

In my codebase, I have an interceptor that if the user is not logged, I redirect him to `/#/login`. If he is logged, it will be redirected to `/#/dashboard`. It is the beginning of the test, so the user is not logged and he will be redirected to login page. Here, the Cypress breaks.

If in my tests I set the `cy.visit` to `/#/login`, the Cypress does not break.

I'll try to post a very simple example with that as soon as possible.

**Comment by mullah1** [comment]
I just upgraded from 3.1.1 to 3.1.3 and I experienced this same issue.

**Comment by smmdd** [comment]
Happening with me in 3.1.4

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by smmdd** [comment]
My STR:
Initial:
No chrome installed.
No Cypress installed.

1. Install the latest chrome (7.1)
2. Install Cypress (3.1.4)
3. Run Cypress `cypress open`
4. In the Test Runner, instead choosing Electron 59, I chose Chrome 71.
![screen shot 2019-01-18 at 09 37 06](https://user-images.githubusercontent.com/46756006/51378277-d6425000-1b04-11e9-82a0-ac2c07a54d6a.png)

5. Run any test
6. The Chrome browser will be opened with the error message
"Whoops, we can't run your test"
![screen shot 2019-01-18 at 09 38 43](https://user-images.githubusercontent.com/46756006/51378302-e22e1200-1b04-11e9-8584-7089679c2809.png)


But if the test is run on Electron 59, it's okay.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem - following the steps provided does not cause the error shown for us.

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by dor-fried** [comment]
Anyone know how to solve this problem?
