### ISSUE TITLE
ids being inserted into strings that match a title

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#29]
A cypress generated id is being inserted after any strings that match a test title. In the example below, you can see that my `cy.get()` command has had an id inserted at `[name='comment [0eo]']`. This is due to the fact that later I have a test titled "comment".

```coffee
describe "paragraph questions", ->
    it "prefills comment with value [1eq]", ->
        cy.get("textarea[name='comment [0eo]']").should("have.value", "Hello world")

describe "comment [0ep]", ->
    it "appends resources [0ei]", ->
      cy.get("[name='comment']").should("have.value", "Hello world, how are you?")
```

**Comment by brian-mann** [comment]
IDs as a whole have been removed from Cypress.

Fixed in [`0.14.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0140-03082016).
