### ISSUE TITLE
In Cypress 13.6.3, I am not able to fetch the API values from the body

### ISSUE THREAD

**Issue by Mathiarasan3** [cypress-io/cypress#29003]
### Current behavior

Currently, when I try to wait until an API call is made and I need to use the API response to fetch a value of a key, I am using this line of code :
I used this code with the previous version 9.0.0 , it worked like a charm, but when I upgraded to 13.6.3, I am seeing this error "Cannot read properties of undefined (reading 'body')"

```js
cy.wait('@apicall').then(res => { 
        cy.log(res.response.body)       
    })
```
    
    I also altered my code in the below way:
    
```js
cy.wait('@apicall').then(res => { 
        cy.log(res.body)       
    })
```
    
    Now it returns NOTHING

### Desired behavior

Actually, I expect my code to give me the body of the API response, but it doesnt

### Test code to reproduce
```js
cy.wait('@estimatebyuser').then(res => { 
        cy.log(res.response.body)       
    })
```
OR
```js
cy.wait('@estimatebyuser').then(res => { 
        cy.log(res.body)       
    })
```
### Cypress Version

13.6.3

### Node version

v18.16.1

### Operating System

Windows 10.0.19045.3930

**Comment by jennifer-shehane** [comment]
If you put a debugger in, what does it show the `res` as being? I don't have enough to understand what the problem is here because the portion of the code pasted seems like it should work, but I don't know what else is happening in the test.

```js
cy.wait('@apicall').then(res => { 
    debugger
})
```

**Comment by Mathiarasan3** [comment]
I tried adding debugger inside the then block, as you said.
nothing actually happened.
```js
When('Filter by id', () => {   
    estimate.getbutton().click()
    cy.wait('@estimatebyuser').then(resp => { 
        debugger
   
    })
})
```

I added the debugger like this, but when I ran this test, this is how the console looked like:
![image](https://github.com/cypress-io/cypress/assets/82944178/86950ee5-14a2-4b4f-b1f8-a736c608419e)

**Comment by jennifer-shehane** [comment]
You'll need to open the browser DevTools to see the code pause when adding `debugger`. What does the devtools panel show?
