### ISSUE TITLE
Cypress runner not able to interact with an image

### ISSUE THREAD

**Issue by SaadUsmanitk** [cypress-io/cypress#29005]
### Current behavior

currently when you visit aliexpress.com and after site is loaded there is an image that popups up. cypress is able to find the image but not able to actually interact with it. i have also attached a video. at the end of the video iam trying to click the cross button but nothing happens.

https://github.com/cypress-io/cypress/assets/94851764/ebf1681d-abb9-42b4-89e4-4225862f5cdf

### Test code to reproduce

```js
describe('closealiexpresspopup', () => {
  it('click on the crossbutton', { tags: 'Visit' }, () => {


    cy.visit('https://aliexpress.com/');
    cy.get('.pop-close-btn').click()
  });
  Cypress.on(
    'uncaught:exception',
    (_err, _runnable) =>
      // returning false here prevents Cypress from
      // failing the test
      false
  );
});
```

### Cypress Version

13.6.6

### Node version

16.4.2

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
I'm not able to click on the image within the Cypress browser. There must be something rendering differently within the Cypress browser as opposed to outside of it. 

![](http://g.recordit.co/5u1UwVR7CG.gif)
