### ISSUE TITLE
cypress not sending language in headers visitng airbnb

### ISSUE THREAD

**Issue by SaadUsmanitk** [cypress-io/cypress#29004]
### Current behavior

currently when iam trying to access the website airbnb.com cypress in not sending the language headers automatically which results in 403 forbiden. 
my code
```js
describe('Airbnb Test', () => {
  it('Should visit Airbnb', () => {
    cy.visit('[/](https://www.airbnb.com/)');
  
  });
});
```
however if i send the the language in custom headers it access the website 
```js
/// <reference types="cypress" />

/// <reference types="cypress" />

describe('Airbnb Test', () => {
  it('Should visit Airbnb with custom headers', () => {
    const customHeaders = {
      'Accept-Language': 'en-US,en',
    };
    cy.visit('https://www.airbnb.com/', {
      headers: customHeaders,
    });
  });
});
```

### Test code to reproduce
```js
describe('Airbnb Test', () => {
  it('Should visit Airbnb', () => {
    cy.visit('[/](https://www.airbnb.com/)');
  
  });
});
```
### Cypress Version

13.6.6

### Node version

16.4.2

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
@SaadUsmanitk Accept-Language headers are not automatically sent during `cy.visit()`. Since airbnb's website seems to require these accept-language headers, you'll need to send them as an option within `cy.visit()` as you have shown in your second example.

**Comment by SaadUsmanitk** [comment]
@jennifer-shehane they are automatically sent using selenium not sure why not on cypress. I think need to debug.
