### ISSUE TITLE
Lack of separation lines between groups of functions in Cypress Runner

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#29000]
### Current behavior

In previous versions of Cypress Runner, there were dividing lines between groups of functions in Cypress Runner (e.g. GET and TYPE functions for same element were grouped together, and divided from other groups by divining lines, which was improving log readability). Currently, all functions are displayed in one group.

### Desired behavior

Groups of functions are divided from other groups by dividing lines.

### Test code to reproduce

-

### Cypress Version

13.6.4

### Node version

20.11.1

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment]
@tomaszwojciechowski Could you provide a screenshot that explains the behavior before/after? I'm not sure exactly what this is describing.
