### ISSUE TITLE
No TypeScript intellisense

### ISSUE THREAD

**Issue by nicitaacom** [cypress-io/cypress#29016]
### What would you like?

I have this file
```ts
describe("test redirection on /companion/new route", () => {
  it("redirect user to / route if not logged in (not authenticated)", () => {
    cy.visit("/companion/new")
    // url should be changed to /
    cy.url().should("eq", Cypress.config().baseUrl + "/")
  })

  // Test when the user is authenticated
  it("redirects authenticated user to /companion/new route", () => {
    console.log(Cypress.env() as NodeJS.ProcessEnv)
    cy.log(Cypress.env("NEXT_PRODUCTION_URL"))
    // Log in the user using curl command

    cy.request({
      method: "POST",
      url: "https://<your_supabase_url>/auth/v1/token",
      headers: {
        "Content-Type": "application/json",
      },
      body: {
        email: "<your_email>",
        password: "<your_password>",
        provider: "email",
      },
    }).then(response => {
      // Check if the response is successful
      expect(response.status).to.eq(200)

      // Use the response body for further assertions or actions
      const token = response.body.access_token

      // Visit the companion/new route with the authenticated token
      cy.visit("/companion/new", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })

      // URL should be changed to /companion/new
      cy.url().should("eq", Cypress.config().baseUrl + "/companion/new")
    })
  })
})

```

And here is no TypeScript intellisense

I tried to get it in different ways - still donesn't work

I want here after . get TypeScript intellisense
![image](https://github.com/cypress-io/cypress/assets/39565703/14e441fd-87d7-47db-bc53-0657b465319f)

Also it don't let me to use enviroment values fron `.env.local` file
Instead I need to put it in `cypress.env.json` and put it in `.gitignore` file to ignore it
and also create this file `cypress.env.json.example` to let contributors understand that they need to fill out this file as well
```json
{
  "NEXT_PRODUCTION_URL": "29-ai-companion.vercel.app",
  "NEXT_DEVELOPMENT_URL": "http://localhost:3029",
  "NEXT_PUBLIC_SUPABASE_URL": "",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY": "",
  // other env
}
```

### Why is this needed?

Because I already have env but its not show me that env

**Comment by jennifer-shehane** [comment]
@nicitaacom I'd suggest checking out our [community chat](https://on.cypress.io/chat) on advise on how to provide types for your custom env vars. As for the env files, we support the `cypress.env.json` files.

**Comment by nicitaacom** [comment]
> @nicitaacom I'd suggest checking out our [community chat](https://on.cypress.io/chat) on advise on how to provide types for your custom env vars. As for the env files, we support the `cypress.env.json` files.

I need to verify my phone
![image](https://github.com/cypress-io/cypress/assets/39565703/c23fdbd8-d073-42f0-8996-ac16f522b9f3)
