### ISSUE TITLE
Firefox not working using when the Docker image (node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1) used in Jenkins

### ISSUE THREAD

**Issue by Rajesh-Kodandam** [cypress-io/cypress#29018]
### Current behavior

Firefox not working using when the Docker image (node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1) used on CI.

### Desired behavior

Firefox not working using when the Docker image (node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1) used.

### Test code to reproduce

The issue is about Firefox not working using when the Docker image (node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1) usede and its not regarding the chrome.

### Cypress Version

13.6.6

### Node version

20.11.0

### Operating System

macOS Sonoma 14.3.1

### Debug Logs

```shell
The issue is about Firefox not working using when the Docker image (node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1) used on Jenkins.
```

### Other

The issue is about Firefox not working using when the Docker image (node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1) usede and its not regarding the chrome.

**Comment by jennifer-shehane** [comment]
@Rajesh-Kodandam What is the error you see? Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by Rajesh-Kodandam** [comment]
I when I used this image tag: node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
works as expected all Chromium based browsers (Chrome, edge, etc); but not the firefox. Any advise.
```
(Run Starting)
11:44:26 ──────────────────────────────────────────────────────── 11:44:26 │ Cypress: 13.6.6 │
11:44:26 │ Browser: Firefox 118 (headless) │
11:44:26 │ Node Version: v20.9.0 (/usr/local/bin/node) │
11:44:26 │ Specs: 1 found (start-page-nina.cy.ts) │
11:44:26 │ Searched: cypress/e2e/nina/* │
────────────────────────────────────────────
11:44:26
11:44:26 Running: start-page-nina.cy.ts (1 of 1)
11:45:34 Timed out waiting for the browser to connect. Retrying...
11:45:34 Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
11:45:34 Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
```

**Comment by jennifer-shehane** [comment]
@Rajesh-Kodandam Did you try to update to a newer Firefox version in the image? It's really difficult to debug these types of disconnection issues. Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?
