### ISSUE TITLE
[BUG] - ERR_ABORTED

### ISSUE THREAD

**Issue by nicitaacom** [cypress-io/cypress#29015]
### Current behavior

I got this error
```
DevTools listening on ws://127.0.0.1:39219/devtools/browser/5e97202d-6c38-475d-96a1-4d15a4875474
Error: ERR_ABORTED (-3) loading 'http://localhost:36535/__launchpad/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:84559)
    at WebContents.navigationListener (node:electron/js2c/browser_init:2:84870)
    at WebContents.emit (node:events:514:28) {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'http://localhost:36535/__launchpad/index.html'
}
```

I don't undestand what happened - just after I run `pnpx cypress open --config watchForFileChanges=false` 
it closed with this error

### Desired behavior

I wait that after I type `pnpx cypress open --config watchForFileChanges=false` in terminal and pressed enter - I will see opened cypress

### Test code to reproduce

`pnpx cypress open --config watchForFileChanges=false`

### Cypress Version

13.6.6

### Node version

20.0.0

### Operating System

Kali Linux

**Comment by jennifer-shehane** [comment]
@nicitaacom Is this reproducible every time? Or it happens randomly? Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by nicitaacom** [comment]
> @nicitaacom Is this reproducible every time? Or it happens randomly? Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

It hapened only once
The best steps to reprocuce I can remember its after typing `pnpx cypress open --config watchForFileChanges=false` and pressing enter - just wail some time and immediately (in <100ms) after cypress window shows uo press some key


In docs I see
![image](https://github.com/cypress-io/cypress/assets/39565703/66366f52-2ad2-424c-8a90-fbd0f731e295)

<br/>

After I runned that command I got error
![image](https://github.com/cypress-io/cypress/assets/39565703/3cf1aec3-9b05-4b39-86ce-2f888724753c)

**Comment by MikeMcC399** [comment]
@nicitaacom 

```shell
pnpx cypress open
```

is probably not the best way to run Cypress using pnpm. See https://github.com/pnpm/pnpm/releases/tag/v7.0.0

---
> pnpx is now just an alias of pnpm dlx.
>
> If you want to just execute the command of a dependency, run pnpm <cmd>. For instance, pnpm eslint.
> 
> If you want to install and execute, use pnpm dlx <pkg name>.

---

If you have installed Cypress with

```shell
pnpm add cypress -D
```

then you can run Cypress in interactive mode with

```shell
pnpm cypress open
```

**Comment by nicitaacom** [comment]
> then you can run Cypress in interactive mode with
> 
> ```shell
> pnpm cypress open
> ```


If I run `pnpm cypress open`

1. It don't let me to test in production
2. It re-run test every time I chage .cy.ts file - that cause [this](https://github.com/cypress-io/cypress/issues/29012) bug

**Comment by MikeMcC399** [comment]
@nicitaacom 

I understand that you have multiple issues at the moment. The difference between `pnpx` and `pnpm` is that `pnpx` will always run the latest version of Cypress (currently `13.6.6`) and it will download and install it if necessary. Most users prefer to choose which version of Cypress they want to work with and then install it one time e.g.

```shell
pnpm add cypress@13.6.0 --save-dev
```

and then run Cypress in interactive mode

```shell
pnpm cypress open
```
