### ISSUE TITLE
Number of total tests results used is different in "Overview" view than in the "Detailed" view

### ISSUE THREAD

**Issue by tony-engineering** [cypress-io/cypress#29029]
### Current behavior

In Billing & Usage section.
Number of total tests results used is different in "Overview" view than in the "Detailed" view. 
This is confusing for the user.

### Desired behavior

Number of total tests results used is the same everywhere.

### Test code to reproduce

Run tests with an account that has free plan, then wait few mins and go check the value in Billing & Usage. 
![cypress_cloud_bug](https://github.com/cypress-io/cypress/assets/9582205/248e975c-32eb-4b7e-960c-c8cd3bd61852)

### Cypress Version

13.6.0

### Node version

Node version of cypress/included:13.6.0 Docker image

### Operating System

OS of cypress/included:13.6.0 Docker image

**Comment by jennifer-shehane** [comment]
@tony-engineering I've forwarded this feedback to our Cloud team for prioritization. I'll close this issue here since it's for tracking issues on our open source product.
