### ISSUE TITLE
peer react@"^=16.x || ^=17.x" from @cypress/react@8.0.0

### ISSUE THREAD

**Issue by Lisalisa007** [cypress-io/cypress#29026]
### Current behavior

After using React: 18.1.0 in my project, an error message will appear “peer react@"^=16.x || ^=17.x" from @cypress/react@8.0.0”

version:
react: 18.1.0
cypress:13.1.0
@cypress/react:8.0.0

### Desired behavior

When I use version 18 of React, there will be no errors

### Test code to reproduce

package.json
```json
"dependencies": {
      "react": "18.1.0",
},
"devDependencies": {
      "cypress": "13.1.0",
      "@cypress/react": "8.0.0",
},
```

### Cypress Version

13.1.0

### Node version

v18.15.0

### Operating System

macOS

### Debug Logs

```shell
error npmExecuteScripts - npm ERR! Could not resolve dependency:
error npmExecuteScripts - npm ERR! peer react@"^=16.x || ^=17.x" from @cypress/react@8.0.0
error npmExecuteScripts - npm ERR! node_modules/@cypress/react
error npmExecuteScripts - npm ERR!   dev @cypress/react@"8.0.0" from the root project
```

**Comment by MikeMcC399** [comment]
@Lisalisa007 

Are you trying to use E2E testing or Component Testing with React?

**Comment by Lisalisa007** [comment]
@MikeMcC399 
I can use E2E testing or Component Testing with React. But how can I keep my project from reporting this error? 
Due to this error, I am unable to pass the CI and merge the code. I must update the React18 version, as the React17 version I previously used did not have this issue.

**Comment by MikeMcC399** [comment]
@Lisalisa007 

If you are testing with Component Testing, then you need to follow the documentation for the [React API](https://docs.cypress.io/guides/component-testing/react/api)

---
### mount

```js
// React 18
import { mount } from 'cypress/react18'

// React 16, 17
import { mount } from 'cypress/react'
```

---

Then I suggest that you execute:

```shell
npm uninstall @cypress/react
```

referring to https://github.com/cypress-io/cypress/blob/develop/npm/react/README.md

---
# @cypress/react

Mount React components in the open source [Cypress.io](https://www.cypress.io/) test runner

> **Note:** This package is bundled with the `cypress` package and should not need to be installed separately. See the [React Component Testing Docs](https://docs.cypress.io/guides/component-testing/react/overview) for mounting React components. Installing and importing `mount` from `@cypress/react` should only be done for advanced use-cases.

**Comment by Lisalisa007** [comment]
@MikeMcC399 

I removed @ cypress/react from package.json and encountered an error when running the test.

![Screenshot 2024-02-28 at 17 32 07](https://github.com/cypress-io/cypress/assets/152941064/1ed50fd2-e476-490d-ba73-5abcad55d4ef)

**Comment by MikeMcC399** [comment]
@Lisalisa007 

Please compare the documentation

```js
import { mount } from 'cypress/react18'
```

with your error message

which shows `@cypress/react18` not `cypress/react18`

**Comment by Lisalisa007** [comment]
@MikeMcC399 
Do I need to install @ cypress/react18?

**Comment by MikeMcC399** [comment]
@Lisalisa007

You need to change the code in your test to use the built-in module `cypress/react18`. If you do this then you do not need to install the stand-alone module `@cypress/react18`. So you just need to remove `@` from your test code.

**Comment by Lisalisa007** [comment]
@MikeMcC399 

I also have this error.
![Screenshot 2024-02-28 at 18 12 52](https://github.com/cypress-io/cypress/assets/152941064/9181606a-321d-4c7a-876f-eedecd1df82d)

**Comment by MikeMcC399** [comment]
@Lisalisa007 

I would guess that the error you are now seeing

> Cannot find module '../../react18'

is due to the customization in your project as it is not reproducible in the working example of Cypress Component Testing with React which mounts `cypress/react18 `  successfully.
https://github.com/cypress-io/component-testing-quickstart-apps is the repo and
https://github.com/cypress-io/component-testing-quickstart-apps/blob/main/react/my-awesome-app/cypress/support/component.js is the code to import.

If you are able to post a link to your test setup it would be possible to take a look at what is going wrong.

**Comment by MikeMcC399** [comment]
@Lisalisa007 

Since you have a non-standard setup, it may be possible to workaround this by going back to your original configuration and then replacing `@cypress/react` using `@cypress/react18` in your package.json. This is only supposed to be done for advanced use cases and I can't say whether it will work or not. You could just try it out.

**Comment by Lisalisa007** [comment]
ok, I will try

**Comment by MikeMcC399** [comment]
@Lisalisa007 

> ok, I will try

Do you have a result?
