### ISSUE TITLE
Unable to import mongodb module in cypress test

### ISSUE THREAD

**Issue by AnandGanesh-Reflektion** [cypress-io/cypress#2902]
### Current behavior:
I am trying to import mongodb node module to update some status after the tests.
But cypress is thowing an exception and failing to start test.

mongodb import statment in cypress test
```js
const MongoClient = require('mongodb').MongoClient
```

package.json
```json
"dependencies": {
    "cypress": "^3.1.3",
    "mongodb": "^3.1.10",
  }
```

Note: I have noticed similar issue while importing "snowflake-sdk" also.

![cypress-mongo-error](https://user-images.githubusercontent.com/29747350/49507216-01027d00-f8a6-11e8-99cc-3e82e99fbf47.png)

### Desired behavior:
should be able to import 3rd party modules

### Versions
all versions of cypress

macOS Highsierra. macOS Mojave

**Comment by brian-mann** [comment]
Cypress serves your specs to the browser, they are not evaluated in `node`, but rather the `browser`.

You cannot import mongo adapter because it only works in `node`.

What you want to do is instead use `cy.task(...)` and in your `pluginsFile` write the implementation for each task. The `pluginsFile` **is** evaluated in `node`, rather than the `browser`, so you can do anything you want in there that you'd normally do in `node`.

**Comment by AnandGanesh-Reflektion** [comment]
@brian-mann thank you so much for your quick response. I would use cy.task(...) as you explained.

**Comment by jennifer-shehane** [comment]
Yes - please see this FAQ question on import/require also: https://on.cypress.io/using-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress

**Comment by nzn-idt** [comment]
Link has changed. Is now:
[https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-require-or-import-node-modules-in-Cypress](https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-require-or-import-node-modules-in-Cypress)

**Comment by a5g** [comment]
https://github.com/a5g/cypress-cy.task-example

**Comment by diegowendel** [comment]
@a5g Thank you for your time in recording this video. It helped me a lot.

**Comment by bahmutov** [comment]
See https://github.com/bahmutov/cypress-example-mongodb and read https://glebbahmutov.com/blog/testing-mongo-with-cypress/

**Comment by madhura-75** [comment]
I still see the same issue and not able to connect ti mongodb using cypress. Can someone please help me here
