### ISSUE TITLE
Cypress.env('foo') is undefined

### ISSUE THREAD

**Issue by doebi** [cypress-io/cypress#29030]
### Current behavior

The documentation at https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests states that in order to load test data from a server, one should fetch them during `setupNodeEvents` and store within a env variable to be consumable by tests with `Cypress.env()`

I did this and verified the presence of my data with a console.log:

But with my tests it simply won't load my testdata. The host env variable works however..

Here is my test code:

### Desired behavior

the data to be present, as described in the examples

### Test code to reproduce

[see example code](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__dynamic-tests/cypress/e2e/user-spec.cy.js)

### Cypress Version

13.6.4

### Node version

20.11.1

### Operating System

Linux ubuntu jammy

**Comment by doebi** [comment]
https://github.com/cypress-io/cypress-example-recipes/blob/11647775546f106b8355dc088934bc2c4325eaaa/examples/fundamentals__dynamic-tests/cypress.config.js#L40

THIS!

**Comment by jennifer-shehane** [comment]
@doebi Is this resolved for you?
