### ISSUE TITLE
Searching by part of a string

### ISSUE THREAD

**Issue by szymon-niedrygas** [cypress-io/cypress#29034]
### What would you like?

Hi Guys, 
It would be nice to have a fully working search field works like SQL-like not the test file starts with. 
I mean the search field in the Specs tab inside the  testrunner. 
This is the element that I'm talking about 
<input data-v-b37feea9 type="search" spellcheck="false" class="text-gray-800 border-0 flex-1 ml-[1px] min-w-[100px] py-[9px] pl-2 placeholder-gray-400 text-gray-800 block disabled:bg-gray-100 disabled:text-gray-400" autocomplete="off" id="spec-filter" placeholder="Search specs" aria-label="Search specs">test runner

### Why is this needed?

It's just frustrating

**Comment by jennifer-shehane** [comment]
@szymon-niedrygas Can you give an example of a search term you'd like to use and what specs it should match (that is not matching today)?

**Comment by szymon-niedrygas** [comment]
As you see below I can search by part the name (sorry didn't know it :)) but I can't search by digits
![image](https://github.com/cypress-io/cypress/assets/76098283/3c560c24-6c88-42cf-96e5-b51047ae6f42)
![image](https://github.com/cypress-io/cypress/assets/76098283/1fcd255c-c255-4842-876d-402795fa473f)

**Comment by jennifer-shehane** [comment]
@szymon-niedrygas That is weird. We'd be open to a PR to address this.

**Comment by migueldsol** [comment]
Hi @jennifer-shehane i was looking into this issue and was able to reproduce it. I think i found a solution for the issue by playing with the sort function threshold. If this is a good solution i would like to create a PR for this.
![Screenshot from 2024-04-17 15-35-53](https://github.com/cypress-io/cypress/assets/46138945/028aad0a-2e52-4213-8360-c7f2dd32555c)

**Comment by jennifer-shehane** [comment]
@migueldsol Sure, we can look at that. make sure to include some tests. We have some Cypress tests in our codebase around the search functionality here.

**Comment by migueldsol** [comment]
@jennifer-shehane , it seems like you might have missed including the link to the tests. Once I finish them, I'll create a PR.

**Comment by jennifer-shehane** [comment]
@migueldsol Here are the tests: https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/specs_list_e2e.cy.ts#L149

Here are the instructions on how to get the tests running locally: https://github.com/cypress-io/cypress/blob/develop/packages/app/README.md#development
