### ISSUE TITLE
Go down/up button to speed up scrolling

### ISSUE THREAD

**Issue by VOJAKIS** [cypress-io/cypress#29035]
### What would you like?

I would like a "Go down" button, when viewing Specs.
Also, a "Go up" button, if possible.

### Why is this needed?

I want this feature because it speeds up scrolling down, or up, when a tester has a lot of specs.

**Comment by jennifer-shehane** [comment]
@VOJAKIS Some of this is covered here: https://github.com/cypress-io/cypress/issues/24973 Can you add a comment there expressing your interest? I'll close this as a duplicate.
