### ISSUE TITLE
Component test pnpm scaffolding uses `pnpm install` not `add`

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29052]
### Current behavior

When scaffolding Cypress Component Testing in the presence of a `pnpm-lock.yaml` file from the [pnpm package manager](https://pnpm.io/) Cypress outputs a command string to instruct the user to install dependencies which starts with `pnpm install`. For instance, if "Vue CLI (Vue 3)" is selected as a front-end framework, the suggested installation command is:

```shell
pnpm install -D @vue/cli-service vue
```

### Desired behavior

Cypress Component Testing scaffolding for pnpm environments should prepend the following command to the framework modules to be installed:

```shell
pnpm add -D
```

instead of `pnpm install -D`.

Although [`pnpm install`](https://pnpm.io/cli/install) appears to install the dependencies listed, it is not the documented way to do this ("`pnpm install` is used to install all dependencies for a project."). The description for [`pnpm add <pkg>`](https://pnpm.io/cli/add) says "Installs a package and any packages that it depends on. By default, any new package is installed as a production dependency.".

Cypress should not rely on an undocumented method to add packages using [pnpm]((https://pnpm.io/)). `pnpm install` is undocumented for this purpose, whereas `pnpm add` **is** documented as the method to add packages.

### Test code to reproduce

In a terminal window, execute:

```shell
npm install pnpm@latest -g
mkdir cy-pnpm-ct
cd cy-pnpm-ct
git init
pnpm init
pnpm add cypress -D
pnpm cypress open
```

Select "Component Testing"
Select "Front-end framework" > "Vue CLI (Vue 3)"
Click "Next step"
Note the instruction

```shell
pnpm install -D @vue/cli-service vue
```

Paste the instruction into a separate terminal window and execute it.

Note that it runs successfully.

### Cypress Version

`13.6.6`

### Node version

`v20.11.1`

### Package manager and version

pnpm `8.15.4`

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

```text
$ pnpm install -D @vue/cli-service vue
 WARN  3 deprecated subdependencies found: consolidate@0.15.1, stable@0.1.8, webpack-chain@6.5.1
Packages: +547
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 724, reused 641, downloaded 82, added 547, done

devDependencies:
+ @vue/cli-service 5.0.8
+ vue 3.4.21

Done in 15.1s
```

### References

- [`pnpm install`](https://pnpm.io/cli/install)
- [`pnpm add <pkg>`](https://pnpm.io/cli/add)

**Comment by MikeMcC399** [comment]
If requested, I can submit a PR to implement the suggestion to change from

```shell
pnpm install -D
```

to 

```shell
pnpm add -D
```

for CT scaffolding.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Yah, this would be a good change if you want to open a PR. Thanks!

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Yah, this would be a good change if you want to open a PR. Thanks!

- Thanks for your confirmation! PR #29056 is ready for review
