### ISSUE TITLE
Can i test functions inside of typescript files?

### ISSUE THREAD

**Issue by vjotaa** [cypress-io/cypress#2905]
I need to know if i can test functions inside my typescript file in ionic 3.

**Comment by jennifer-shehane** [comment]
Hey @vjotaa, could you give an example of the test code you'd like to write? Have you already tried something in Cypress that isn't working currently?

You can also ask questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
