### ISSUE TITLE
cy.contains NOT support unicode variable

### ISSUE THREAD

**Issue by RealLau** [cypress-io/cypress#2906]
### Current behavior:
![image](https://user-images.githubusercontent.com/16678624/49575287-48a80800-f97d-11e8-8f4e-dedd96bc09b6.png)

### Steps to reproduce: (app code and test code)
1. add config.js as below:
```javascipt
export let 添加新设备 = "添加新设备"

```
2. reference it in code as below:
```javascript
cy.contains(data.添加新设备).click() 
```
3. run it and then u can see the error image uploaded on the top. BUT, if NOT config it in config.js and just reference it in code as `cy.contains('添加新设备').click()`， it works perfectly.

### Versions
➜  CypressTest cypress -v
    `Cypress package version: 3.1.3`
    `Cypress binary version: 3.1.3`
on Mac OSX 10.14.1

**Comment by sainthkh** [comment]
I tried to reproduce the bug, but failed. If anyone met a similar thing, please leave me a comment. 

How I tested

**HTML test fixture: **
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Issue 2906</title>
  </head>
  <body>
    <div id="test">添加新设备</div>
  </body>
</html>
```

**JS files**
```js
// config.js
export let 添加新设备 = '添加新设备'

export const 한국어 = '添加新设备'
```

```js
// test.js
const test = require('./config')
const 한국어 = '添加新设备'
const 添加新设备 = '添加新设备'

describe('issue #2906', () => {
  it('contains an element with variable with unicode names', () => {
    cy.visit('/fixtures/issue-2906.html')
    cy.get('#test').contains('添加新设备')
    cy.get('#test').contains(한국어)
    cy.get('#test').contains(添加新设备)
    cy.get('#test').contains(test.한국어)
    cy.get('#test').contains(test.添加新设备)
  })
})
```

The test passed clearly. 

### ONE THING TO NOTE:

When I was testing this, I mistakenly wrote `const test = './config'`. As we all know, it should be `const test = require('./config')`. At that moment, I met the same error message above: 'cy.contains() can only accept a string, number or regular expression'.

I want you to check if you made a same mistake I did.
