### ISSUE TITLE
When I check the UI after a test has finished, the window goes berserk

### ISSUE THREAD

**Issue by MarceloBean13** [cypress-io/cypress#29074]
### Current behavior

After the test has finished, if I hover over an element in the Cypress UI (The reporter panel), the test panel (aut-panel)  just goes get messed up.

### Desired behavior

This is how's suppose to look:
![Screenshot 2024-03-06 161332](https://github.com/cypress-io/cypress/assets/82844966/11e269d8-8f19-43e4-b547-7d9ddf3bb642)

This is how it looks after the test has finished:
![Screenshot 2024-03-06 161432](https://github.com/cypress-io/cypress/assets/82844966/5aae490e-4c97-4b5c-ac1d-0c498cef0f00)

### Test code to reproduce

This happens in all tests I have, no exception.

### Cypress Version

v13.6.6

### Node version

v18.18.0

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
@MarceloBean13 It seems something may not be reflected accurately when you hover over a command, which time travels you back to that point in the DOM. https://docs.cypress.io/guides/core-concepts/cypress-app#Time-traveling

Could you provide a reproducible example of this behavior that we could run?

**Comment by MarceloBean13** [comment]
@jennifer-shehane Thank you for your response. 

In this first screenshot it's when the test has finished:
![Screenshot 2024-03-13 132604](https://github.com/cypress-io/cypress/assets/82844966/77b553c5-9553-4233-9770-8eebc660ff2a)

This screenshot after I hover over any command (it doesn't matter what I choose) and, as you can see, the whole window went down:
![Screenshot 2024-03-13 132613](https://github.com/cypress-io/cypress/assets/82844966/209c2667-9c16-476f-8ad5-0d4699793d7c)

This screenshot is after I've scroll down in the window in order to see everything:
![Screenshot 2024-03-13 132619](https://github.com/cypress-io/cypress/assets/82844966/cc571f72-58e3-4745-bc6d-00367d2a37ed)

I hope this helped in understanding better my issue.

Thank you,
Marcelo

**Comment by jennifer-shehane** [comment]
Cypress should be reflecting the state of the DOM at the time the test ran, perhaps CSS was not loaded at that time? We'd need a reproducible example to run if you believe this is a bug with Cypress.
