### ISSUE TITLE
compare two aliases which derive value from two different contexts.

### ISSUE THREAD

**Issue by Shailth** [cypress-io/cypress#2907]
I have a two containers inside a section.
Both hit different end points to derive some a values, post that they compare these values and decide either to render. (thats how the app works).
i have written a cypress test to cover the same, wherein i have two aliases calculating the two values:

```js
.getByAutomationId('wipIssue')
.within(() => {
cy.get('section').within(() => {
      cy.getByAutomationId(‘balance’)
         .first()
         .invoke('text')
         .as(‘balance’);
});
     cy.getByAutomationId('lotCardGroup')
      .within(() => {
        cy.get('div').within(() => {
          cy.getByAutomationId('lot-CH10312823')
            .click()
            .find(‘sfb’)
           .invoke(‘text’)
            .as(‘sfbVal’);
        });
      });
});

//Assert a condition
if(@balance <= @sfbVal){
 // provide an outcome or reason
}
```

help me compare the two values ('balance' against 'sfbVal') to complete my cypress test.

**Comment by Shailth** [comment]
the issue is while comparing the latter says undefined(@balance).

**Comment by jennifer-shehane** [comment]
Ensure when comparing later that you are within a `.then(() => {})` command so the values are defined when they are called. 

In the future, we recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Issues in our GitHub repo are reserved for potential bugs or feature requests.
