### ISSUE TITLE
Cypress.spec provides inconsistent directory separators on windows

### ISSUE THREAD

**Issue by paul-sachs** [cypress-io/cypress#2909]
### Current behavior:

On windows 7, running the following in any spec (that is nested in a directory):

```js
console.log(Cypress.spec)
```

will output something like the following:

```
{
  absolute: "{projectDir}/cypress/integration/composer/create-table-spec.ts"
  name: "composer\create-table-spec.ts"
  relative: "integration\composer\create-table-spec.ts"
}
```

### Desired behavior:

Ideally, it would always be using linux directory separators:

```
{
  absolute: "xxx/cypress/integration/composer/create-table-spec.ts"
  name: "composer/create-table-spec.ts"
  relative: "integration/composer/create-table-spec.ts"
}
```

### Steps to reproduce: (app code and test code)

The above is sufficient (Assuming windows 7)

### Versions

Cypress: 3.1.2
OS: Windows 7
Browser: Chrome 70

**Comment by Saibamen** [comment]
https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/fixtures/specs_windows.json used only here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/specs_list_spec.coffee#L6

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
