### ISSUE TITLE
watchForFileChanges is not applied

### ISSUE THREAD

**Issue by mbourd** [cypress-io/cypress#29098]
### Current behavior

watchForFileChanges = false
Using Cypress open interface, the spec reload

### Desired behavior

Not reload the spec

### Test code to reproduce

n/a

### Cypress Version

13.6.6

### Node version

16.18.0

### Operating System

Ubuntu 20.04

**Comment by jennifer-shehane** [comment]
@mbourd We'll need a reproducible example in order to investigate. This works normally so likely something in your project may be a factor. See also this issue about file watching not working with an app with service workers: https://github.com/cypress-io/cypress/issues/702

**Comment by jakobjoachim** [comment]
same for me we have set "watchForFileChanges: false" in the cypress.config.ts and it still reloads the component test after each save

**Comment by jennifer-shehane** [comment]
We'll have to close this without a reproducible example. Please comment if there is a way for us to investigate this.

**Comment by artfox3** [comment]
Same on my side, setting "watchForFileChanges: false" in the cypress.config.ts file doesn't disable the auto run when running using cypress open, the cypress.config.ts file I'm using is in a custom directory, I have a custom command in package.json to open cypress with the custom config file "npx cypress open --config-file customConfigPath.ts"
After cypress is opened using this command, checking the project settings from the UI shows correctly that the option "watchForFileChanges: false" is present, but auto run is still not disabled.

**Comment by artfox3** [comment]
After some tests, it seems that the "watchForFileChanges" option works only on the exact spec files, which means that having the option set to false, if you update the actual spec file, the test doesn't rerun, but if you update any file that is imported to the spec file itself, it is rerun again.
