### ISSUE TITLE
Normal text in CI logfile is kind of unreadable

### ISSUE THREAD

**Issue by duns** [cypress-io/cypress#29099]
### What would you like?

The text in the log, unless it is an error, is "darkgrey" on "black" which makes it hard to read. Is that settable, or maybe you change the default.

**Comment by jennifer-shehane** [comment]
@duns Could you post a screenshot? This is not currently editable from any user facing API.

**Comment by duns** [comment]
![image](https://github.com/cypress-io/cypress/assets/132239/11d33732-458f-4bb2-806f-5ec601c6edec)

**Comment by duns** [comment]
The Red, the Green, the White, the Cyan are all very well readable, but the dark-grey is not. Line numbers (not yours) are just ok.

**Comment by jennifer-shehane** [comment]
@duns Thanks for sending the screenshot. We use [chalk](https://github.com/chalk/chalk/releases) for the colors within our CLI. In these areas, we're using `gray` color from Chalk. 

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/print-run.ts

We would be open to a PR to update this, perhaps changing Chalk's 'gray' theme might be the most efficient, so that the colors printed are accessible on a black and white background. (We would not support any custom background colors).

**Comment by duns** [comment]
Well, I would just refrain from using this grey... out of the chalk colours.

I am very happy with cypress in general, but when I show it to others they also say that part of the log is unreadable (unless selected, when yet again other colours become unreadable.

The log is important, as it enabled people to fix things.

**Comment by jennifer-shehane** [comment]
Just a note, after looking at this a bit, that how the colors show will be dependent on how your terminal is configured.  On my terminal, the grey passes color contrast checks.  Perhaps you could look into adjusting your terminal theme for now.

![Screenshot 2024-03-12 at 7 42 00 AM](https://github.com/cypress-io/cypress/assets/1271364/744d7691-43f8-4e0d-b603-f203068c9d08)

![Screenshot 2024-03-12 at 9 48 09 AM](https://github.com/cypress-io/cypress/assets/1271364/0f368824-c21d-4284-892f-a863bdf0cecc)

**Comment by duns** [comment]
Hi

I run cypress in gitlab-ci, it seems my pure white is the same as yours, but my gray, green and red are darker than yours (cypress). 

I guess it is part of gitlab-ci then, maybe they darken your colours ? Could that be ?

Thanks for looking at this.
Regards
Mark

**Comment by jennifer-shehane** [comment]
@duns Yah, I do believe this is up to Gitlab CI and the CSS they're applying to those ansi colors. We do the same on our Cloud product - we're just given output with ansi coloring, and we decide whatever CSS coloring to give it when displaying it in the browser. 

Our Cloud output:

![Screenshot 2024-03-12 at 2 59 44 PM](https://github.com/cypress-io/cypress/assets/1271364/bab875a7-da62-4f6e-aed3-abd4e5c1d242)

Going to close this as not being something under our control.

**Comment by duns** [comment]
Thank you for your effort and time.

Regards
Mark
