### ISSUE TITLE
cypress-grep throws error when using cypress with typescript.

### ISSUE THREAD

**Issue by harishraut-Aut** [cypress-io/cypress#29097]
### Current behavior

cypress test failes with below error 
     TypeError: The following error originated from your test code, not from Cypress.

  > (0 , support_1.default) is not a function

### Test code to reproduce

https://github.com/harishraut-Aut/Cypress-grep-issue/tree/master

### Cypress Version

13.6.6

### Node version

18.0

### Operating System

windows

**Comment by sumandeepbkaur** [comment]
I am also facing the same issue with Cypress version 10.9.0 and node version 20. Seeing (0 , support_1.registerCypressGrep) is not a function

**Comment by WilliamGusmanov** [comment]
Adding `"esModuleInterop": true` to the `cypress/tsconfig.json` fixed the issue for me.
