### ISSUE TITLE
Handling multiple windows in Cypress

### ISSUE THREAD

**Issue by rahulbendale03** [cypress-io/cypress#29091]
### Current behavior

How to handle multiple windows in cypress.

### Test code to reproduce

How to handle multiple windows in cypress.

### Cypress Version

13.6.6

### Node version

20

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
@rahulbendale03 Please check out our [puppeteer plugin](https://github.com/cypress-io/cypress/tree/develop/npm/puppeteer) and its examples, this is the only way to handle multiple windows in Cypress.
