### ISSUE TITLE
Enhancements to cy.request()

### ISSUE THREAD

**Issue by tormoseng** [cypress-io/cypress#291]
There are a few issues that would be very welcomed enhancements to cy.request():
- allow cy.request not to fail under non 2xx/3xx status codes
- turning off automatic redirect

(ref chat on November 10th)

**Comment by tormoseng** [comment]
@brian-mann would it be best to spilt these two points into two issues? The first is at the moment a showstopper in the authorization process for me. However, for you I guess it would make sense to do these enhancements at once.. Have you scheduled the issue for release yet?

**Comment by brian-mann** [comment]
Sure if you want, split these up. 

We keep our progress updated here: https://github.com/cypress-io/cypress/projects

I will see what I can do about prioritizing these. I understand that it's a stopper for you.

**Comment by tormoseng** [comment]
Split into issues #307 and #308.
