### ISSUE TITLE
Add a clock on the cypress UI

### ISSUE THREAD

**Issue by tchaton** [cypress-io/cypress#29105]
### What would you like?

I would like to see a clock on the cypress UI. This would make debugging much simpler.

### Why is this needed?

Aligning logs is complicated without a clock on the recording.

**Comment by jennifer-shehane** [comment]
@tchaton Are you using a video recording or Cypress' [Test Replay](https://docs.cypress.io/guides/cloud/test-replay)? Test Replay will show all of the logs in time with the command logs as they happen and this would be our recommended approach for debugging this. Adding a clock to the Cypress UI is not something that we will be prioritizing.

**Comment by psnehanshu** [comment]
Would love to have this too.
