### ISSUE TITLE
Windows error when unzipping cypress "File path too long"

### ISSUE THREAD

**Issue by testquantilope** [cypress-io/cypress#2910]
### Current behavior:

When downloading the windows version of cypress and unzipping it, I get multiple errors that the file path is too long, e.g.:

![image](https://user-images.githubusercontent.com/35334883/49647260-287e5480-fa22-11e8-9598-9a96e577e157.png)

I have unzipped it for example on my desktop, but also created a folder directly in the root and still had several of these issues. If I skip the files that cannot be extracted, cypress still runs without problems.

### Desired behavior:

You should be able to unzip cypress windows application without errors.

### Steps to reproduce: (app code and test code)

1. Download cypress (http://download.cypress.io/desktop)
2. Extract the zip file anywhere, e.g. on your desktop (File path here is usually "C:\Users\User Name\Desktop\", so not very long).
3. Observe the error.

### Versions

Cypress: 3.1.3, but this was also happening in earlier versions.

**Comment by jennifer-shehane** [comment]
Could you specify the paths/names of the files that cannot be extracted?

**Comment by Saibamen** [comment]
Lol. This is not related to Cypress...

Please install latest Windows Updates and latest 7zip

Please close this issue

**Comment by JohnAllenJr** [comment]
My solution is even easier. Install LongPathTool.
Spend 2 minutes - profit! Take care.

**Comment by KevinNelson0700** [comment]
Exactly, I came to face this issue also. Then some recommended me Long Path Tool software and I am grateful to that person
