### ISSUE TITLE
Unable to Type in Test Name and Save the New Test in Cypress Studio 

### ISSUE THREAD

**Issue by gulperidolkun** [cypress-io/cypress#29112]
### Current behavior

When I create a new test using Cypress Studio and I'm satisfied with the generated steps, I click on Save Commands to save the test. 
However, it's not allowing me to type in any test name, hance unable to proceed to save the new test. 
<img width="1718" alt="Screenshot 2024-03-12 at 9 09 37 AM" src="https://github.com/cypress-io/cypress/assets/142320305/ba6cef50-78f6-4804-98df-ea187b93c82a">

### Desired behavior

It should allow me to type in a test name and proceed to save the new test. 

### Test code to reproduce

Please see the screenshot attached. 

### Cypress Version

13.2.0

### Node version

18.17.0

### Operating System

macOS Sonoma 14.3.1

**Comment by jennifer-shehane** [comment]
I wasn't able to reproduce this with a simple example. I know you did quite a bit more steps than me though. 

- What browser did you open to do this? Electron? Chrome?
- If you open devTools, do you see any errors being thrown?
- Is it that the text box is disabled? Why can't you type?
