### ISSUE TITLE
Cypress & Chrome Test Third Party Cookie Phase Out

### ISSUE THREAD

**Issue by iepoch** [cypress-io/cypress#29122]
### Current behavior

As an SDET I am trying to test the new Chrome Test Third Party Cookie Phaseout flag. Currently Cypress will show the browser is set to "enabled" for the third-party-cookie-phaseout although the actual flag shows as disabled. 
![image](https://github.com/cypress-io/cypress/assets/7504929/d2decfec-f09a-4172-8769-f38adcfa532f)

### Desired behavior

We should have a flag to set in Cypress to allow the third party phase out to be enabled and that the actually setting shows enabled. IE 
![image](https://github.com/cypress-io/cypress/assets/7504929/0ac052ba-4aa0-430c-8444-9b626ffc3a10)

### Test code to reproduce

```js
 on('before:browser:launch', (browser={}, launchOptions) => {
    if (browser.family === 'chromium') {
      launchOptions.args.push('--test-third-party-cookie-phaseout');
      return launchOptions;
    }
  }
);
```

### Cypress Version

8, 12, 13

### Node version

18.17.0

### Operating System

Windows 11

### Debug Logs

```shell
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Command Line	"C:\Program Files\Google\Chrome\Application\chrome.exe" --test-type --ignore-certificate-errors --start-maximized --silent-debugger-extension-api --no-default-browser-check --no-first-run --noerrdialogs --enable-fixed-layout --disable-popup-blocking --disable-password-generation --disable-single-click-autofill --disable-prompt-on-repos --disable-background-timer-throttling --disable-renderer-backgrounding --disable-renderer-throttling --disable-backgrounding-occluded-windows --disable-restore-session-state --disable-new-profile-management --disable-new-avatar-menu --allow-insecure-localhost --reduce-security-for-testing --enable-automation --disable-print-preview --disable-device-discovery-notifications --autoplay-policy=no-user-gesture-required --disable-site-isolation-trials --metrics-recording-only --disable-prompt-on-repost --disable-hang-monitor --disable-sync --disable-web-resources --safebrowsing-disable-download-protection --disable-client-side-phishing-detection --disable-component-update --simulate-outdated-no-au="'Tue, 31 Dec 2099 23:59:59 GMT'" --disable-default-apps --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --disable-ipc-flooding-protection --disable-backgrounding-occluded-window --disable-breakpad --password-store=basic --use-mock-keychain --disable-dev-shm-usage --proxy-server=http://localhost:50750 --disable-web-security --allow-running-insecure-content --proxy-bypass-list=<-loopback> --remote-debugging-port=50760 --remote-debugging-address=127.0.0.1 --test-third-party-cookie-phaseout --load-extension
```

### Other

Would like to know if Cypress runs this setting but because Cypress needs to Frame Chrome can not provide the setting update because of the frame or if it's Google Issue that it's not toggle it based on Cypress Framing?

**Comment by jennifer-shehane** [comment]
You can look on `chrome://versions` and see the flag being set. Chrome seems to say that sometimes this isn't reflected on the `chrome://flags` page if its passed as a command line flag here: https://developer.chrome.com/docs/web-platform/chrome-flags/

>Also be aware that chrome://flags might not show the flag settings you've used from the command line. Instead, take a look at chrome://version. From the Command Line section, you can check what flags are enabled in your browser.

Is there any indication that the functionality is not as it should? Is it not enabling the third-party-cookie phase out?

![Screenshot 2024-03-12 at 3 54 01 PM](https://github.com/cypress-io/cypress/assets/1271364/3745e163-3fac-48df-9325-3db748c026b2)

**Comment by iepoch** [comment]
@jennifer-shehane Thank you for your response. The problem I found in version 12.7.4 I did not see that show however yes I was able to see this in the Version. But I couldn't find where Google had stated that it may not show in the flags setting. That was the worrisome part. However for latter versions of Cypress if it's not showing in Versions is the consideration to just update?

**Comment by jennifer-shehane** [comment]
![Screenshot 2024-03-13 at 11 59 45 AM](https://github.com/cypress-io/cypress/assets/1271364/84dda70a-f581-42e9-840d-15629cedccdb)

@iepoch I would suggest updating if you're not seeing it in older versions. I'm not exactly sure what would have impacted this flag in this case though.

**Comment by iepoch** [comment]
@jennifer-shehane  I have added this in and it does show in the version of Chrome. However, I am noticing that our test that are strictly third-party test are still succeeding. In the test is punches out to another site and the frames our site. These test succeed even when third-party cookie Phaseout is enabled. Most of the cookies are stored in Cookies Storage upon that specific URL. Overall here is what this looks like currently. Most of the cookies are set to None and Strict but not all are. However Cypress test never show a failure.
