### ISSUE TITLE
Why does cypress keep loading pages？

### ISSUE THREAD

**Issue by Apyz** [cypress-io/cypress#29127]
### Current behavior

as shown in the picture
![cypress2](https://github.com/cypress-io/cypress/assets/28755252/5d77f90f-25ea-4229-9030-c16d4ea7606f)
![cypress 页面一直在加载1](https://github.com/cypress-io/cypress/assets/28755252/b7ebb26a-c69b-476f-99e7-3deb96d568e1)
![cypress 出错源码](https://github.com/cypress-io/cypress/assets/28755252/ed40f8ef-8d87-4a42-9644-62e4aeb13d77)

### Desired behavior

The page has already loaded, why is it still stuck? This is a website that you can experiment with

### Test code to reproduce

```javascript
describe('template spec', () => {
    it('passes', () => {
        let url = 'https://www.toutiao.com'
        url = "https://mp.toutiao.com/profile_v4/weitoutiao/publish?from=toutiao_pc"
        console.log("Try the output here1111111111")
        cy.visit(url)
        console.log("Try the output here 2222222222")

        cy.xpath("//span[text()='撤销']").should('exist').click();

        cy.xpath("//div/div/span[@class=\"icon-wrap\"]").should('exist').click()
        // cy.xpath('//input[@id="kw"]').type('这是一个测试')
    })
})
```

### Cypress Version

cypress@13.6.6

### Node version

v18.19.1

### Operating System

windows 10

**Comment by Apyz** [comment]
I have observed that the background seems to be sending some requests all the time. Does it matter?
![cypress3](https://github.com/cypress-io/cypress/assets/28755252/422096d2-7900-424b-b05b-841301c2953c)

**Comment by jennifer-shehane** [comment]
@Apyz Cypress is just reflecting the state of your application loading and the requests it makes. It seems when the redirect to the login page occurs, that it takes a significant amount of time for the load event to fire. You can see this outside of Cypress also. I would suggest increasing the `pageLoadTimeout` in your Cypress configuration. 

![](http://g.recordit.co/rhTDHpbRDR.gif)
