### ISSUE TITLE
Unable to select text within span

### ISSUE THREAD

**Issue by juliod84** [cypress-io/cypress#29120]
### Current behavior

<img width="176" alt="Screenshot 2024-03-12 at 12 30 55 PM" src="https://github.com/cypress-io/cypress/assets/53156708/437d3163-38e1-4b4e-93e2-e6e9023a151a">

I'm trying to assert the _Single_ text, below _House Type:_.

My assumption is that using `cy.contains('House Type:')` would also provide access to _Single_, but it does not.

Using `.next()` moves to the`span` element below _Single_.

Shouldn't using `cy.contains('House Type:')` also select the text _Single_?

### Desired behavior

Select _House Type: Single_ when using `cy.contains('House Type:)`

### Test code to reproduce

HTML:
```html
<span>
  <b>House Type: </b>
  "Single"
  <span>...</span>
</span>
```

Attempt to select _Single_ text.

### Cypress Version

13.6.4

### Node version

18.16.0

### Operating System

macOS Sonoma 14.4

**Comment by jennifer-shehane** [comment]
@juliod84 Could you try `cy.contains('span', 'House Type:')`. There's an optional selector argument that will filter the DOM elements containing the text. 

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by juliod84** [comment]
Specifying `span` worked, thank you!
