### ISSUE TITLE
example.cypress.io deploys are broken

### ISSUE THREAD

**Issue by cacieprins** [cypress-io/cypress#29135]
### Current behavior

Currently,  `cypress-example-kitchensink` assets get removed before a deploy from `@packages/example`. This causes CSS, etc, to become missing from example.cypress.io.

### Desired behavior

Not remove `cypress-example-kitchensink` assets during `yarn`.

### Test code to reproduce

N/A

### Cypress Version

13.7.0

### Node version

18.17.1

### Operating System

macOS 14.3

**Comment by MikeMcC399** [comment]
@cacieprins / @AtofStryker 

I'm still seeing this as an issue.

When `yarn` is run, it installs `cypress-example-kitchensink` into
`cypress/node_modules/cypress-example-kitchensink`

Watching the directory
`cypress/node_modules/cypress-example-kitchensink/app`

shows that it first gets fully populated, but by the time yarn has finished, only the directories are left in `/app/assets`. The files have been removed:

```text
assets  commands  cypress-api.html  index.html  todo.html  utilities.html

./assets:
css  fonts  img  js

./assets/css:

./assets/fonts:

./assets/img:

./assets/js:

./commands:
actions.html     connectors.html  location.html    network-requests.html    storage.html    waiting.html
aliasing.html    cookies.html     misc.html        querying.html            traversal.html  window.html
assertions.html  files.html       navigation.html  spies-stubs-clocks.html  viewport.html
```

~~Could you please re-check this process?~~

## Expected

These would be the full set of files which `cypress-example-kitchensink/app` should include after installation:

```text
assets/  commands/  cypress-api.html  index.html  todo.html  utilities.html

./assets:
css/  fonts/  img/  js/

./assets/css:
styles.css  todo.css  vendor/

./assets/css/vendor:
bootstrap.min.css  bootstrap.min.css.map  fira.css

./assets/fonts:
eot/  ttf/  woff/

./assets/fonts/eot:
FiraSans-Medium.eot  FiraSans-Regular.eot

./assets/fonts/ttf:
FiraSans-Medium.ttf  FiraSans-Regular.ttf

./assets/fonts/woff:
FiraSans-Medium.woff  FiraSans-Regular.woff

./assets/img:
favicon.ico  javascript-logo.png

./assets/js:
scripts.js  todo/  vendor/

./assets/js/todo:
app.js  controller.js  helpers.js  model.js  store.js  template.js  view.js

./assets/js/vendor:
bootstrap.min.js  highlight.pack.js  jquery-1.12.0.min.js  jquery-1.12.0.min.map

./commands:
actions.html     connectors.html  location.html    network-requests.html    storage.html    waiting.html
aliasing.html    cookies.html     misc.html        querying.html            traversal.html  window.html
assertions.html  files.html       navigation.html  spies-stubs-clocks.html  viewport.html
```

**Comment by MikeMcC399** [comment]
- Should be fixed by https://github.com/cypress-io/cypress/pull/29159
