### ISSUE TITLE
Cy Cloud: Filter on Latest runs sets itself to Jan 1, 1970 - Jan 19, 2038

### ISSUE THREAD

**Issue by beccaonx** [cypress-io/cypress#29145]
### Current behavior

When I leave my Chrome browser page on Latest runs overnight, I open it the next morning and the filter is set to Jan 1, 1970 - Jan 19, 2038
![cy filter](https://github.com/cypress-io/cypress/assets/31448534/4bc83c83-cc9b-44a3-8dbd-9826c8ca83c0)
.

### Desired behavior

Filtering previously worked so well that I didn't have to think about it. I think it was automatically set to all time (which I suppose Jan 1, 1970 - Jan 19, 2038 basically is).

### Test code to reproduce

N/A

### Cypress Version

13.7

### Node version

20.10

### Operating System

14.2.1

### Other

This has been happening for a few weeks- not brand new.

**Comment by jennifer-shehane** [comment]
@beccagsc Thanks for reporting! Definitely weird. I've sent this feedback to the Cloud team. I'll close this issue here since these issues are for tracking things in the open source product.
