### ISSUE TITLE
Navigate.Share User Action Not Supported by Cypress Activation Events

### ISSUE THREAD

**Issue by QADeamon** [cypress-io/cypress#29150]
### Current behavior

OS: Windows 10 Pro v10.0.19045 Build 19045
Browser: Chrome 122.0.6261.57
Cypress: 13.6.6

On buttons which call the Web Share API (navigator.share), cypress actions such as `cy.click` are not treated as valid user gestures. Instead, when the runner attempts to click on an element which requests this data, the browser throws an exception. 

`DOMException: Failed to execute 'share'  on 'Navigator': Must be handling a user gesture to perform a share request.`

While Cypress believes it has completed the click event, the browser has thrown an exception and does not update the DOM or call the required XHR requests to update the page with a given notification of successful user interaction. The following assertion in a test which expects the existence of a notification wrapper therefore fails.

### Desired behavior

In this case, I believe Cypress should be capable of bypassing browser protections and simulate user actions on share requests.

### Test code to reproduce

```js
describe('Share Event', () => {
  it('clicks share asserts notification exists', () => {
    cy.visit('https://mdn.github.io/dom-examples/web-share/')
    cy.get('button').contains('Share MDN!').click()
    cy.get('.result').should('have.text', 'MDN shared successfully')
  })
})
```

### Cypress Version

13.6.6

### Node version

18.17.1

### Operating System

Windows 10 Pro v10.0.19045 Build 19045

### Other

I am aware that this is a very common issue, and most people have remedied it by installing the cypress-real-events library. I have already done this and made it around the issue, but I thought it would be good to document this, in case others run into the same problem, and hope that the framework can natively support these browser actions.

**Comment by jennifer-shehane** [comment]
I get this error running the example. I think we're not handling this right. We don't simulate user gestures upfront, which I think we should.

![Screenshot 2024-03-25 at 12 14 25 PM](https://github.com/cypress-io/cypress/assets/1271364/fe30a328-a3f7-48d8-9b66-678c6a6c7f45)
