### ISSUE TITLE
Cypress Test Runner - Autoscroll isn't working for the pinned elements if they're at the bottom of the page

### ISSUE THREAD

**Issue by ziyailkemerogul** [cypress-io/cypress#29155]
### Current behavior

When I have tests with a lot of steps, and I want to view the steps after the test run on the test runner; scrolling, hovering over the test body I mean, or clicking on every step that I want to view, the browser view on the right side doesn't scroll to the bottom of the page automatically. 

For every single step, I click on the step, scroll the browser view down manually, check what I need to check, and then click on the next step (**here the browser view automatically scrolls to the top of the page although the element that I clicked on the test body is at the bottom of the page**) then again I go to the browser view and scroll down manually... 

This is really time-consuming when I have tests at the bottom of the page or which need a bit of scrolling.

It doesn't focus on where it should focus.

<img width="1238" alt="Screenshot 2024-03-15 at 11 43 28" src="https://github.com/cypress-io/cypress/assets/42968830/d38d9de7-ae90-4ded-878b-038a2a7f1173">

### Desired behavior

The focus should always follow the selected or pinned element no matter where it is on the page. It should automatically scroll to show what is selected.

### Test code to reproduce

N/A

### Cypress Version

v13.6.6.

### Node version

v18.17.0

### Operating System

MacOS Sonoma 14.3.1

**Comment by jennifer-shehane** [comment]
@ziyailkemerogul Are you able to provide a reproducible example? I wonder if there's some autoscroll behavior within the application under test that is making it scroll or scroll slowly...
