### ISSUE TITLE
Sharing context in tests (`before` block to `it`) is not possible

### ISSUE THREAD

**Issue by alexttransisland** [cypress-io/cypress#2916]
### Current behavior:

Simple test
```
describe('Search results', () => {
  beforeEach(() => {
    cy.visit('http://www.google.com/')
    cy.get('div[id=gws-output-pages-elements-homepage_additional_languages__als]').invoke('text').as('googleLanguages')
  })

  it('accesses the languages', () => {
    cy.log(this.googleLanguages)
  })
})
```

fails with the exception
```
TypeError: Cannot read property 'googleLanguages' of undefined
```

### Desired behavior:

According to https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context there should possiblity to share the context. If not by let, then by `aliases`

### Steps to reproduce: (app code and test code)

Run the test according to steps described. Please do not ask why I need such case, the test created just for reproduction.

### Versions

3.1.3, MacOS, Chrome 70

**Comment by patrykkopycinski** [comment]
hey @alexttransisland,
have you tried to not use arrow functions? 
due to https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context 
![image](https://user-images.githubusercontent.com/5188868/49700803-d5ec9600-fbe3-11e8-9d77-c649a5fa5aea.png)
