### ISSUE TITLE
Cypress UI doesn't display on laptop screen upon disconnecting external screen

### ISSUE THREAD

**Issue by islamJamer** [cypress-io/cypress#29165]
### Current behavior

When using an Extended Display and then dragging the Cypress Runner on another screen, then removing the extended screen and trying to open it on the Laptop screen only, it will not open. 

To Fix this, we have to connect Screen(HDMI) again then Drag it again to the Laptop screen, and then disconnect the Extended screen. 

### Desired behavior

I shouldn't have to re-connect the external screen just to drag the Cypress UI to the laptop screen then disconnect it

### Test code to reproduce

no code is needed here

### Cypress Version

12.7.0

### Node version

v20.11.1

### Operating System

windows 11

**Comment by MikeMcC399** [comment]
@islamJamer 

This is a known issue with Microsoft Windows 11 (and 10) that is unrelated to Cypress.

You may find the Microsoft support article [Some Programs Are Displayed Off the Screen](https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4) helpful. Or Google "windows 11 move window to current monitor" for a selection of articles and videos on this topic.
