### ISSUE TITLE
Custom assertion messages create confusing output in Cypress open

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [cypress-io/cypress#29167]
### Current behavior

Hello,
I just noticed a strange behaviour regarding custom assertion messages when running Cypress in open mode.

`expect(2).to.be.a('string')`

![image](https://github.com/cypress-io/cypress/assets/45459065/4c816d5f-4d2a-4737-af41-fa5fecfd445a)

expect(2, "Custom message").to.be.a('string')

![image](https://github.com/cypress-io/cypress/assets/45459065/f077a2e2-46c9-4a42-ad10-6eebf5b2a9b1)

As you can see, the message on the first line is not in the right order : "expected Custom message: to be a string 2", whereas the "AssertionError" message below is correct : "Custom message: expected 2 to be a string"

It's even more of a problem for other chainers, particularly when the assertion passes so there is no correct "AssertionError" message below.

`expect(2).to.be.at.least(0);`
yields 
![image](https://github.com/cypress-io/cypress/assets/45459065/1d9805aa-665c-486c-b02d-168b2eb9f193)

whereas 
`expect(2).to.be.at.least(0, "Custom message");`

yields 

![image](https://github.com/cypress-io/cypress/assets/45459065/a1b52360-0d59-4e82-969d-a994c565ffe3)

The expected min value (0) is no longer displayed and the message implies that we're expecting the value to be a least 2 (the actual value).

Same problem with ` expect(2, "Custom message").to.be.at.least(0);`

### Desired behavior

When using a custom message, the output just after "assert" should match what is done for the "AssertionError" message, meaning it should be something like : "My custom message: Message I would have if no custom message"

### Test code to reproduce

The examples above are reproducible with any app, but please let me know if any additional information is needed.

### Cypress Version

13.7.0

### Node version

v16.15.0

### Operating System

Ubuntu 20.04.5 LTS / 64 bits

**Comment by jennifer-shehane** [comment]
@AlexGuironnetRTE I'm fairly certain I broke this in this PR: https://github.com/cypress-io/cypress/pull/28583 Downgrading to 13.6.2 would resolve the issue. 

13.6.2
![Screenshot 2024-03-19 at 11 49 53 AM](https://github.com/cypress-io/cypress/assets/1271364/fc860efe-03df-4354-a0ff-59ed264c105d)

13.6.3
![Screenshot 2024-03-19 at 11 48 42 AM](https://github.com/cypress-io/cypress/assets/1271364/a74c572d-5571-4b6d-b73c-c3a0e20feb58)

**Comment by AlexGuironnetRTE** [comment]
Thanks a lot for the prompt reply !

**Comment by tiago80673** [comment]
The bug is assuming this: https://github.com/cypress-io/cypress/blob/66e10d81f248d1ee86954b84f02e76d4f2f6b8c0/packages/reporter/src/commands/command.tsx#L46

The command message could start with a Custom Message before the 'expected'.
Adding this info to the Regex Expression [here](https://github.com/cypress-io/cypress/blob/66e10d81f248d1ee86954b84f02e76d4f2f6b8c0/packages/reporter/src/commands/command.tsx#L38) solves the problem.

Should I add a test of an assertion with a custom message before PR?

**Comment by jennifer-shehane** [comment]
@tiago80673 Yes, that is the incorrect assumption with this code. A test for this situation will be needed for the PR.
