### ISSUE TITLE
Cypress hangs often or crashes. In test runner it takes forever to load.

### ISSUE THREAD

**Issue by jananibalakrishnanakamai** [cypress-io/cypress#29177]
### Current behavior

Only killing the app and restarting works. 

### Desired behavior

App will work seamlessly until yesterday, was able to switch browsers and run tests easily, now specs are not loading at all.

### Test code to reproduce
```js
describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})
```

### Cypress Version

13.7.0

### Node version

16.16.0

### Operating System

macOS

### Debug Logs

```shell
The Test Runner unexpectedly exited via a exit event with signal SIGKILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-arm64 (22.6.0)
Cypress Version: 13.7.0
```

**Comment by jennifer-shehane** [comment]
@jananibalakrishnanakamai 
- What browser are you using? 
- What changed between yesterday and today? Did you update Cypress? Did your browser update? (Chrome updated yesterday)
- Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by jananibalakrishnanakamai** [comment]
I m using Chrome, Firefox and Electron. Seeing this behavior on all three browsers. 

I added couple of extensions in chrome, didn't update it.

**Comment by samelawrence** [comment]
I would recommend upgrading to Node `v.18`.
