### ISSUE TITLE
Can't omit --ci-build-id when running Cypress in Webapp.io

### ISSUE THREAD

**Issue by ianwalter** [cypress-io/cypress#29175]
### Current behavior

When I omit the `--ci-build-id` flag from the Cypress command that executes within Webapp.io (formerly LayerCI) I get:
```
{
  "message": "CI Build ID could not be generated and was not specified.",
  "code": "INDETERMINATE_CI_BUILD_ID"
}
```

### Desired behavior

The command should execute successfully when this flag is omitted since Cypress now supports Webapp.io internally as a CI provider. Omitting the flag will allow the command to be deterministic which will allow us to use Turborepo to not run Cypress when it is not necessary (e.g. only change is an update to README.md).

### Test code to reproduce

Our command looks like:
```
cypress run --spec cypress/e2e/card --record --parallel --group card --config baseUrl=http://localhost:7002 --ci-build-id $LAYERCI_JOB_ID-$RETRY_INDEX
```
So you could run something similar in Webapp.io and then remove --ci-build-id to see the issue. 

### Cypress Version

13.6.5

### Node version

20.11.0

### Operating System

Ubuntu 22.04

### Debug Logs

```shell
{
  "message": "CI Build ID could not be generated and was not specified.",
  "code": "INDETERMINATE_CI_BUILD_ID"
}
```

**Comment by jennifer-shehane** [comment]
I've forwarded this request to our Cloud team for consideration.

**Comment by ianwalter** [comment]
I've verified that this works now, thank you!
