### ISSUE TITLE
TypeError: Cannot read property 'popup' of undefined

### ISSUE THREAD

**Issue by VSathyamoorthy** [cypress-io/cypress#2917]
### Current behavior: 
The issue is caused due to a pop comes in the page, after duplicate check is made. It fails after comparing the screenshots before and after load

### Desired behavior: 
The pop-up shouldn't fail the test and continue with execution

### Versions
OS: Windows 10
Browser: Electron 59.0.3071.115
Cypress:v3.1.3

P.S - The same script was running successfully in the cypress version 3.1.1

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this - test code and application code?
