### ISSUE TITLE
Open in IDE does not work

### ISSUE THREAD

**Issue by szymon-niedrygas** [cypress-io/cypress#29176]
### Current behavior

I'm not able to use the Open in IDE feature from the Cypress Runner. When the link is pressed nothing happens.  Href is empty. 
![2024-03-21_07h28_25](https://github.com/cypress-io/cypress/assets/76098283/160fb12e-4c6b-427a-95a1-dcc71cde41e9)
![2024-03-21_07h30_38](https://github.com/cypress-io/cypress/assets/76098283/0112f07c-e184-4bdb-8290-06ab6bfc7abd)
![2024-03-21_07h37_57](https://github.com/cypress-io/cypress/assets/76098283/bf976553-944d-4ec7-a296-d282955dd699)

### Desired behavior

FIle opened in the Visual Studio Code

### Test code to reproduce

n/a

### Cypress Version

13.7.0

### Node version

v18.17.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
The anchor link is always empty, even when the link is functioning, so that's not the issue. This link works for me in a simple test.

Could you provide the filepath that this is meant to redirect to? Is the URL as shown correct? Does that file and that line still exist in the code base?

**Comment by jennifer-shehane** [comment]
Closing due to lack of information
