### ISSUE TITLE
Please implement: "Whole account Test Results dashboard" (to enable fast filtering of the results from any number of sub projects: by time, projects etc)

### ISSUE THREAD

**Issue by CloneOfAlex** [cypress-io/cypress#29207]
### What would you like?

Please implement: "Whole account Test Results dashboard" (to enable fast filtering of the results from any number of sub projects: by time, projects etc)

adding ability to create custom dashboards would be also nice ..

### Why is this needed?

I spend 1-2 hours every morning reviewing test results and it is painful waste of manual labor reviewing different test groups, one at a time
Wish I could just review Summary Dashboard and see everything there for a whole Cypress account ( totals of tests run, tests failing, other metrics with widgets to make it easy to investigate)

**Comment by jennifer-shehane** [comment]
@CloneOfAlex Are you currently using the Cypress Cloud? There are views and graphs in there. If you are using it, I'm curious to know what specific views you'd like that are not already available. https://docs.cypress.io/guides/cloud/introduction

**Comment by CloneOfAlex** [comment]
closing as this has nothing to do with this repository but Cypress cloud offering

**Comment by jennifer-shehane** [comment]
@CloneOfAlex I can forward feedback to the Cloud team, but it may also be more direct to email support@cypress.io with any Cloud feedback.

**Comment by CloneOfAlex** [comment]
> @CloneOfAlex I can forward feedback to the Cloud team, but it may also be more direct to email [support@cypress.io](mailto:support@cypress.io) with any Cloud feedback.

it is ok - found solace in custom dashboards outside of Cypress Cloud 
- if a tool does not do what i want, it is easier to write my own .. Thanks
