### ISSUE TITLE
Not able to access lightning elements while performing cypress automation on Salesforce

### ISSUE THREAD

**Issue by shubhamladhe15** [cypress-io/cypress#29201]
### Current behavior

Not able to access lightning elements while performing cypress automation on Salesforce even after invoking properties. Only body components are accessible.

### Desired behavior

able to access lightning elements while performing cypress automation on Salesforce

### Test code to reproduce

Not able to access lightning elements while performing cypress automation

### Cypress Version

13.6.7

### Node version

18.17.0

### Operating System

macOS 14.1.2

**Comment by alexsch01** [comment]
not great at all but a possible workaround is using XPATH

**Comment by jennifer-shehane** [comment]
Have you tried using `.shadow()` commands? I believe this may be built with Shadow DOm so you'd need to use that command to select the elements. https://docs.cypress.io/api/commands/shadow

**Comment by shubhamladhe15** [comment]
@jennifer-shehane Not built with shadow DOM, but seems to be working with Xpath as per suggested by @alexsch01 .

**Comment by alexsch01** [comment]
@shubhamladhe15 hey reopen this issue

`cy.get('[href="/lightning/..."]').click()` doesn't work even with `includeShadowDom: true` in the Cypress config file

**Comment by alexsch01** [comment]
I made issue https://github.com/cypress-io/cypress/issues/29217
