### ISSUE TITLE
Pass flag '--font-render-hinting' to chrome with before:browser:launch

### ISSUE THREAD

**Issue by nlarche** [cypress-io/cypress#2920]
### Current behavior:

Hello, 

I would like to test some html rendering with cypress, I use the height of div to do that. But I have 
different results between browsers and headless browsers.

I have the same results between, chrome, chromium, safari and Firefox. The Results are also the same on chrome and chromium with cypress (run and open). Those tests are run on macOs and linux.

The problem comes when I launch my test on a docker image (debian). here Pupeteer and Cypress don't make the same result. 

However launching pupeteer with "--font-render-hinting=none" fix the problem but not on cypress.

### Desired behavior:

I expect this to work with cypress: 

```js
on('before:browser:launch', (browser = {}, args = []) => {
        args.push('--font-render-hinting=none');
        return args;
   });
```

I found this issue on puppeteer, it could be helpful: https://github.com/GoogleChrome/puppeteer/issues/2410

### Versions

Cypress: 3.1.3

**Comment by jennifer-shehane** [comment]
Hey @nlarche, there is an issue with passing browser flags to the Electron based browser here: https://github.com/cypress-io/cypress/issues/1519

You could attempt to run [`--browser chrome`](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-browser-lt-browser-name-gt) during `cypress run`, although the video recording would not be available in chrome.

**Comment by jennifer-shehane** [comment]
@nlarche You are using Chrome version 66+? 

Also, how are you verifying that the flag is not being passed exactly?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by sebinsua** [comment]
I am also having this issue with Chrome 77 in headless mode within a Docker image.

There is a difference in font rendering between Headless and Headed Chrome. I was trying to use this flag to see if it would fix things, but it does nothing.

**Comment by jennifer-shehane** [comment]
@sebinsua Please open a new issue with a completely reproducible example. Truly headless Chrome was introduced in a recent version, so this is a completely new issue.
