### ISSUE TITLE
Scrolling fails for AG grid 

### ISSUE THREAD

**Issue by AnaStasia1331** [cypress-io/cypress#29226]
### Current behavior

ScrollTo() doesn't work in combination with AG table. I tried to target AG table itself or the scrollbar in the table, but regardless the targeted selector, Cypress throws the error "failed because this element is not scrollable"

### Desired behavior

The AG table is scrollable

### Test code to reproduce

```js
describe('template spec', () => {
  it('reproduce issue with AG grid scrolling', () => {
      cy.visit("https://ag-grid.com/example/");
      // accept cookies
      cy.get("#onetrust-accept-btn-handler").click();
      cy.get('#myGrid').scrollTo('bottom');
      // or try cy.get('.ag-body-vertical-scroll').scrollTo('bottom');
  })
})
```

### Cypress Version

13.7.1

### Node version

18.14.0

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment]
@AnaStasia1331 Thanks for reporting, we'll need an application to run the code against in order to act on this issue. We need to reproduce it. Otherwise, we'll have to close this issue.

**Comment by AnaStasia1331** [comment]
I found the same table on https://ag-grid.com/examples and wrote the short test to reproduce the issue. Please check the updated code snippet

**Comment by jennifer-shehane** [comment]
You need to ensure that you've selected the DOM element that is scrollable. In this case the code below does scroll to the bottom of the grid:

```js
describe('template spec', () => {
  it('reproduce issue with AG grid scrolling', () => {
      cy.visit("https://ag-grid.com/example/");
      // accept cookies
      cy.get("#onetrust-accept-btn-handler").click();
      cy.get('.ag-body-viewport').scrollTo('bottom');
  })
})
```

**Comment by AnaStasia1331** [comment]
Thanks! it worked also for my internal project. Maybe it could help to mention it in the documentation, because I was reading your examples here https://docs.cypress.io/api/commands/scrollTo and it wasn't very clear that the targeted selector should be narrowed down to the ones with 'viewport' in it.
