### ISSUE TITLE
Cloud Dashboard sometimes fails to receive pass/fail result of a test, runs it indefinitely, despite Specs tab shows result. 

### ISSUE THREAD

**Issue by anaviun** [cypress-io/cypress#29222]
### Current behavior

Cypress cloud considers a test running, occupies a container, while the test has actually completed running. Can be happening to both failing and passing tests, but mostly failing. 
Not seeing any specific pattern in the tests either, each time seems to be a different test that hanged. 
This also affects the workflow runtime - since eventually the run will auto-cancel, my overall timer will be showing (for one specific run)
 02:16:01 in Overview, vs 38:38 in Specs. Where I believe Specs is the accurate one.

### Desired behavior

The run result should be received by the runner, container should be opened for queue, the test run times should be matching. 

### Test code to reproduce

This issue is intermittently happening with in my suite, each time with a subset of tests is hanging.

### Cypress Version

13.7.1

### Node version

20.11.0

### Operating System

Linux

### Debug Logs

```shell
see attached in Other
```

### Other

The example run link:
https://cloud.cypress.io/projects/cu1zc7/runs/3342/overview?roarHideRunsWithDiffGroupsAndTags=1

Attaching logs here as the files were too long:
[logs_22187459044.zip](https://github.com/cypress-io/cypress/files/14796437/logs_22187459044.zip)

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode where it hangs and print the entire set of logs here?
