### ISSUE TITLE
Palo Alto firewall blocking download of Cypress and thus installation

### ISSUE THREAD

**Issue by moop-moop** [cypress-io/cypress#29233]
### Current behavior

As of the past week or so, all versions of Cypress 13+ fail to install due to corrupt download errors.
Palo Alto firewall is actively blocking the Cypress zip, this is what happens when malicious code is flagged in the download stream.
Palo Alto customers are free to file false positive reports, after your own analysis.

### Debug logs

```Text
[FAILED] The Cypress App could not be downloaded.
[FAILED]
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
[FAILED]
[FAILED] Otherwise, please check network connectivity and try again:
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] URL: https://download.cypress.io/desktop/13.7.1?platform=linux&arch=x64
[FAILED] Error: Corrupted download
[FAILED]
[FAILED] Expected downloaded file to have checksum: d3053a18ab9bc22dfd0caeb0f7a159beb65ca36e2a329f1ff17b80a5b696368ec39350830a942a03bbd06179991eabe25145454bf057ceb1ce45df0aa03d6a05
[FAILED] Computed checksum: a75c5a90fd4d23b5d4b68d6b450648297fbc04cab6601ecaf3aa8bb062dad04366dd5110655e22fcaaf5eec49532256acfbf053740f7e32df89856a5ecf1ca23
[FAILED]
[FAILED] Expected downloaded file to have size: 191617775
[FAILED] Computed size: 52574459
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: linux-x64 (Ubuntu - 20.04)
[FAILED] Cypress Version: 13.7.1
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/13.7.1?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: d3053a18ab9bc22dfd0caeb0f7a159beb65ca36e2a329f1ff17b80a5b696368ec39350830a942a03bbd06179991eabe25145454bf057ceb1ce45df0aa03d6a05
Computed checksum: a75c5a90fd4d23b5d4b68d6b450648297fbc04cab6601ecaf3aa8bb062dad04366dd5110655e22fcaaf5eec49532256acfbf053740f7e32df89856a5ecf1ca23

Expected downloaded file to have size: 191617775
Computed size: 52574459

----------
```

### Cypress Version

13.7.1

### Node version

v20.11.0

### Package Manager

npm

### Package Manager Version

10.2.4

### Operating system

other

### Operating System Version

Linux *** 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Other

This does not seem to affect Cypress version 12.

**Comment by moop-moop** [comment]
This does not seem to affect Cypress version 12.

**Comment by jennifer-shehane** [comment]
@moop-moop What action would you want Cypress to take, with the firewall blocking the zip?

**Comment by MikeMcC399** [comment]
@moop-moop 

Your options could be:

- Allowlist the download of the Cypress binary `cypress.zip` from https://download.cypress.io (https://cdn.cypress.io) on your firewall OR
- Move to a non-blocked network temporarily, download `cypress.zip` manually and either install to Cypress cache or use `CYPRESS_RUN_BINARY` environment variable to point to a user-defined location OR
- Move permanently to a non-blocked network

Users who have previously reported similar issues have generally managed to allowlist the download in order to get Cypress to install without error.

## Reference

[Cypress > Advanced Installation](https://docs.cypress.io/guides/references/advanced-installation)
