### ISSUE TITLE
Add option for Component Testing to JIT compile test before executing.

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#29244]
### What would you like?

An option to Just-In-Time (JIT) compile CT tests as the test is being run instead of compiling all assets at once before suite execution. 

### Why is this needed?

As component testing suites grow, `cypress open` and `cypress run` performance tends to be noticeably slower. This is due to the webpack dev server / vite dev server compiling all assets in the `specPattern` on launch, which can be very slow if a user has a lot of component tests. This would make open mode (and run mode in some scenarios) faster when it comes to running a single test as waiting for a lengthy compile is no longer needed. 

### Other

Performance impacts are starting to be felt by the Cypress core team when developing component tests as well as some of our users who have larger component testing suites. 

Since this might add a configuration option, we may need to make the signature public to allow OSS developers of other CT dev servers the option to implement.

**Comment by jennifer-shehane** [comment]
Please leave any feedback around using this experimental option in [this github discussion](https://github.com/cypress-io/cypress/discussions/30024).
