### ISSUE TITLE
Understand/fix any implications of `unload` event deprecation within Chrome

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#29241]
### What would you like?

https://developer.chrome.com/docs/web-platform/deprecating-unload

Chrome is deprecating the upload event where it will begin ceasing to functions for some websites starting Q3 2024.

We should enable the flags to turn it off to understand the implications of the deprecation. https://github.com/fergald/docs/blob/master/explainers/permissions-policy-deprecate-unload.md#testing-with-chrome

We'll also need to handle users that have this flag manually turned on past the deprecation. 

I opened a PR to deprecate the unload event to see what would fail here: https://github.com/cypress-io/cypress/pull/29242

**Comment by cacieprins** [comment]
Next step: Determine if `pagehide` event will suffice for a replacement event
