### ISSUE TITLE
Crash on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by andrade-carolina** [cypress-io/cypress#29259]
### Current behavior

I can install Cypress on Ubuntu 22.04 LTS but it simply stops responding and consequently crashes and displays the following error:
```
The Test Runner unexpectedly exited via a exit event with signal SIGKILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 22.04)
Cypress Version: 13.7.2
```

### Test code to reproduce
```
npm install cypress --save-dev
npx cypress open
```
### Cypress Version

13.7.2

### Node version

20.12.1

### Operating System

Ubuntu 22.04 LTS

**Comment by MikeMcC399** [comment]
@andrade-carolina

Cypress is well tested on Ubuntu 22.04 so it is unusual to have a crash when starting.

- Does this problem happen every time you try to use Cypress?
- Are you running Ubuntu in a stand-alone hardware environment or is it a virtual instance?
- If you installed Ubuntu yourself, is it up to date with patches? (What is the output after executing `lsb_release -a` in a terminal window?)
- If Ubuntu is running as a virtual instance, what is the software environment?
- Have you tried uninstalling and re-installing Cypress?

If you want to try uninstalling and re-installing on Ubuntu in case the installation is corrupt, the following instructions may help you:

```shell
rm -rf ~/.cache/Cypress
npm uninstall cypress
npm install cypress --save-dev --foreground-scripts
```

Normally if you then execute the following, you will see the message 
> ✔  Verified Cypress! 

```shell
npx cypress verify
```

**Comment by MikeMcC399** [comment]
- This issue has similarities to https://github.com/cypress-io/cypress/issues/29169.
