### ISSUE TITLE
XHR OnReadyStateChange receives no arguments (no event)

### ISSUE THREAD

**Issue by andezzat** [cypress-io/cypress#2925]
### Current behavior:
Cypress isn't passing the event to the callback function.

<img width="710" alt="screen shot 2018-12-11 at 2 01 10 pm" src="https://user-images.githubusercontent.com/1734293/49775783-714d4a80-fd4d-11e8-8880-20a54ac7345e.png">
<img width="782" alt="screen shot 2018-12-11 at 2 03 32 pm" src="https://user-images.githubusercontent.com/1734293/49775828-980b8100-fd4d-11e8-8f6a-aa01c454a16a.png">
<img width="728" alt="screen shot 2018-12-11 at 2 01 31 pm" src="https://user-images.githubusercontent.com/1734293/49775829-99d54480-fd4d-11e8-8ed5-95cec1eaf974.png">

### Desired behavior:
Cypress should pass the event to the XHR callback function...

#### App
```html
<html lang="en">
  <head>
    <title>Hello World</title>
    <script>
      (async function () {
        const myXhr = new XMLHttpRequest();
        myXhr.onreadystatechange = (e) => {
          if (!e) throw new Error('There is no event:', e);
        };
        myXhr.open('GET', 'https://google.com');
      })()
    </script>
  </head>
  <body>
    <div>
      <h1>This should fail...</h1>
    </div>
  </body>
</html>
```
#### Cypress
Place `index.html` in the root dir and just visit..
`cy.visit('index.html')`

### Versions
Cypress - 3.1.3

### Notes
It looks like this is a small mistake as part of a new PR to allow Cypress to handle XHRs with multiple OnReadyStateChange callbacks..

**Comment by chrisbreiding** [comment]
The code for this is complete, but has not yet been released. When it is released, we'll post a message with a link to the changelog.

**Comment by andezzat** [comment]
Thank you for the prompt response & merge ^_^
Cheers!
