### ISSUE TITLE
cypress can't find chrome in v13.7.2

### ISSUE THREAD

**Issue by Vignesh-527** [cypress-io/cypress#29256]
### Current behavior

I am using cypress v13.7.2 and trying to run a test. But I am not getting the chrome option in the test window to select browser.

![image](https://github.com/cypress-io/cypress/assets/156911970/28fc50ae-c90e-4915-88d6-6a2bca80fcc5)

I tried to use edge with an extension. But the test window is not having the extension while running the test. It would be helpful if anyone helps with this. I have given the script I am using to test a web application. The getPasscode() function returns a 6-digit OTP.

### Test code to reproduce

``` js
import { getPasscode} from "../../OAuth/getCode";

describe('Your Cypress Test Suite', () => {
  it('Should automate the process', () => {
        cy.visit(`MY_TEST_LINK`);
    
    // Start the process
    cy.wait(5000);
    cy.get('[data-cy="start-button"]',{timeout:5000}).should('be.visible').click();
    // Login process
    cy.get('#login-button').click();
    
    // Input email and submit
    cy.get('#email-input').type("skillfit.tests+test@gmail.com");
    cy.get('#send-passcode-button').click();

    // Wait for passcode input field and submit
    cy.wait(30000); // Adjust timing as needed
    const passcode =getPasscode();
    passcode.split('').forEach((char, i) => {
      cy.get(`#codeInput-${i}`).type(char);
    });
    cy.get("#submit-code-button").click();

    // Start the process after login
    cy.get('#start-button').click();

    // Agree to terms (30 times)
    for (let i = 0; i < 30; i++) {
      cy.get('//*[@id="root"]/div[2]/div/div/div[2]/div/button[2]/div').click();
    }

    // Continue the process
    cy.get('//*[@id="root"]/div[2]/div[2]/div[2]/div/div/button[2]/span').click();
    cy.get('//*[@id="root"]/div[2]/div/div[2]/div/div/button').click();
    cy.get('#Button_Upload_Resume').click();
  });
});
```

### Cypress Version

13.7.2

### Node version

20.11.0

### Operating System

Windows 11

**Comment by MikeMcC399** [comment]
@Vignesh-527 

I suggest you check if you have Chrome correctly installed on Windows. If you enter

```shell
start chrome
```

in a terminal window, then Google Chrome should start up.

If you need additional help there is a technical community available on Discord where other users will answer questions:

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

**Comment by Vignesh-527** [comment]
@MikeMcC399 Thanks for the help. Found the problem, chrome wasn't installed properly.
