### ISSUE TITLE
how can I input the value to the calendar control?

### ISSUE THREAD

**Issue by xidianyaolu** [cypress-io/cypress#2926]
### Current behavior:
Now,I want to test a calendar like this :

<input readonly="" value="" placeholder="please select date" class="ant-calendar-range-picker ant-input">

you can refer to [https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Desired behavior:

I'd like to input to a calendar control ,how can I input the value ?
`    cy.get('.ant-calendar-range-picker.ant-input')
      .type('2018/12/12')`

this doesn't work !

**Comment by jennifer-shehane** [comment]
Type in range fields
```
it('types in range field', () => {
  cy.visit('https://ant.design/components/date-picker/')
  cy.get('.ant-calendar-range-picker-input').eq(0).click()
  cy.get('.ant-calendar-date-panel').within(() => {
    cy.get('.ant-calendar-range-left .ant-calendar-input')
      .type('2018/12/12')
    cy.get('.ant-calendar-range-right .ant-calendar-input')
      .type('2018/12/14')
  })
})
```

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress) in the future. Issues in our GitHub repo are reserved for potential bugs or feature requests.

**Comment by xidianyaolu** [comment]
dear jennifer, truly grateful for your help, cypress is great , it helps a lot ! hats off to your team @jennifer-shehane
