### ISSUE TITLE
Cypress Crash on macOS Ventura - The Test Runner unexpectedly exited via a exit event with signal SIGABRT

### ISSUE THREAD

**Issue by ajaymahadeven** [cypress-io/cypress#29272]
### Current behavior

Thank you for you work on this library !

## Issue Summary
Cypress is crashing unexpectedly on macOS Ventura (23.4.0) with the following error:

```
DevTools listening on ws://127.0.0.1:54497/devtools/browser/3c9bf938-1198-4cee-bee2-874b02392fb9
2024-04-05 10:05:21.997 Cypress[4474:106891] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
(node:4492) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///Users/apm30/Library/Caches/Cypress/13.7.2/Cypress.app/Contents/Resources/app/node_modules/ts-node/esm/transpile-only.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5469) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///Users/apm30/Library/Caches/Cypress/13.7.2/Cypress.app/Contents/Resources/app/node_modules/ts-node/esm/transpile-only.mjs", pathToFileURL("./"));'
The Test Runner unexpectedly exited via a exit event with signal SIGABRT
```

## Observed Behavior
The Cypress test runner crashes unexpectedly with a `SIGABRT` signal.

### Desired behavior

The Cypress test runner should run tests without crashing.

### Test code to reproduce

Based on the related GitHub issue, it seems that the issue is related to the --experimental-loader flag used by Cypress. The warning suggests that this flag may be removed in the future, and the recommended solution is to use the register() function instead.

Not concurrently occurring atm. More of an awareness issue.

### Cypress Version

ex.13.7.2

### Node version

v21.7.2

### Operating System

macOS 14.4.1

## Related Link
https://github.com/cypress-io/cypress/issues/28158

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?
