### ISSUE TITLE
Cypress blocks my xhr request

### ISSUE THREAD

**Issue by nehbehl** [cypress-io/cypress#29297]
### Desired behavior

Cypress should not block the XHR so that application can proceed

### Test code to reproduce

```js
// Describe block to group related tests
describe('intellicus', () => {
  
  // Before hook to run setup tasks before any test in the suite
  before(() => {
    // Setup tasks (if any)
    
  });
  
  // After hook to run cleanup tasks after all tests in the suite
  after(() => {
    // Cleanup tasks (if any)
  });

  // Before each hook to run setup tasks before each test
  beforeEach(() => {
    // Setup tasks (if any)
  });

  // After each hook to run cleanup tasks after each test
  afterEach(() => {
    // Cleanup tasks (if any)
  });

  // Test case to specify the behavior of a feature
  it('login', () => {
    // Test steps
    cy.visit('/')
    cy.frameLoaded("#linkContainer")
    cy.iframe().find("input[name='TXT_USERID']").should('be.visible').type("Admin")
    cy.iframe().find("input[name='TXT_IDEN_P']").should('be.visible').type("Admin1")

    cy.intercept({
      method: 'POST',
      url: 'https://192.168.221.183:8443/intellicus/servlet/user'
    },
    {
      statusCode: 302
    }).as('servletRequest')

    cy.iframe().find("input[name='btnSubmit']").should('be.visible').click()

    cy.wait('@servletRequest')
  });


  

});
```

### Cypress Version

13.7.2

### Node version

20.12.1

### Operating System

windows 10

**Comment by KrzysztofWisniewskiAcc** [comment]
Got very similar issue, want to intercept an xhr/fetch call after clicking an input (checkbox)

```js
cy.intercept('https://someurl').as('interceptRequest');
cy.get('#popover-basic input').check(['kw-test-123']);
cy.wait('@interceptRequest');
```

Feels like a bug or I'm missing something, although I have lots of places where I was doing this likely, although it was never a checkbox.

I can see from the console 2 scenarios
1) The request was done before the interception was triggered, although the 'wait' is placed right after the click call.
2) The interception blocked loading resource loading (after clicking, the request didn't trigger until interception died out of timeout, tried different timeouts so it's not a time issue)

Also tried on various versions of cypress
Cypress 13.6.0 or 13.7.2 
node v20.11.1 
chrome 123.0.6312.123 
windows 11

What I also notice and mb it's somehow related, that the function in tested application, which is triggered after the click, is an 'async' one

` saveFavorites: async (listId, performSync = true) => {`

**Comment by jennifer-shehane** [comment]
Could you share some details on this request, like the headers?

**Comment by nehbehl** [comment]
Here are the header details, please assist to overcome this or understand the reason so that I can move ahead.

**Comment by jennifer-shehane** [comment]
@nehbehl Are there no errors in the console? I haven't seen this blocked behavior before in Cypress, but it probably has something to do with your application not playing well with how we render within an iframe. Some policy you have set or something is resulting in it being blocked?

**Comment by nehbehl** [comment]
@jennifer-shehane I get this error in console , what next steps would you suggest to resolve it?
![image](https://github.com/cypress-io/cypress/assets/6397129/a8209ab1-13ca-4325-ab72-728dbfbd0b75)

**Comment by nehbehl** [comment]
Hi @jennifer-shehane , I have shared all the available details from my side and the marked stage still shows 'needs information'. Please let me know what else is required from my end.

**Comment by jennifer-shehane** [comment]
There's not much we can do without a way to reproduce it on our side. I did do some research into blocked requests and nothing really made sense in this case with what I know we're doing. It would require a deeper dive into the code with the problem.
