### ISSUE TITLE
Cypress tests reload after clicking sign in on login page of my application

### ISSUE THREAD

**Issue by nehbehl** [cypress-io/cypress#29290]
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/6397129/17f3a7d6-b3a5-4152-9b23-d40d7e7e7c39)

Cypress does not navigate to home page after clicking Sign In button with correct credentials entered on Login page.

### Desired behavior

Cypress test should not reload and home page should appear after logging in with correct credentials

### Test code to reproduce

describe('Intellicus spec', () => {

  
  

  it('passes', () => {

    cy.session('login', () => {
      cy.visit('https://192.168.221.183:8443/intellicus')
      cy.frameLoaded("#linkContainer")
      cy.iframe().find("input[name='TXT_USERID']").type("Admin")
      cy.iframe().find("input[name='TXT_IDEN_P']").type("Admin1")
      cy.iframe().find("input[name='btnSubmit']").click()
      cy.visit('https://192.168.221.183:8443/intellicus')
      cy.url().should('contain', 'Home')
    })

### Cypress Version

13.7.2

### Node version

20.12.1

### Operating System

windows 10

**Comment by jennifer-shehane** [comment]
@nehbehl Have you looked at our cy.origin command? https://docs.cypress.io/api/commands/origin

**Comment by nehbehl** [comment]
Hi @jennifer-shehane  I don't think my case falls in cross origin as my domain stays same.
