### ISSUE TITLE
Update Lodash to 4.17.11

### ISSUE THREAD

**Issue by OmriAharon** [cypress-io/cypress#2929]
This isn't really a bug (nor is it a feature).

The current dependency of lodash is `4.17.10`, but holds a security issue according to WhiteSource:
![image](https://user-images.githubusercontent.com/12033595/49792261-f418da00-fd3a-11e8-8227-436ee22f14ba.png)

Updating to `4.17.11` does the trick and should be simple non-breaking.

**Comment by harshlele** [comment]
Hey, I'm new to open source. Can i work on this?

**Comment by brian-mann** [comment]
Released in [`3.1.4`](https://docs.cypress.io/guides/references/changelog.html#3-1-4).
