### ISSUE TITLE
After upgrading to 13.7.1, execution in Cypress cloud getting stuck after few spec files , error: This spec does not have any test results because it timed out.

### ISSUE THREAD

**Issue by cypresstestuser** [cypress-io/cypress#29299]
### Current behavior

After upgrading to 13.7.1, execution in Cypress cloud getting stuck after few spec files , error: This spec does not have any test results because it timed out.

### Desired behavior

Cypress cloud used to execute correctly all spec files.

### Test code to reproduce

Cypress cloud issue

### Cypress Version

13.7.1

### Node version

20

### Operating System

Edge 123

**Comment by jennifer-shehane** [comment]
@cypresstestuser Sorry to hear you’re encountering errors recording. I have a few questions and suggestions to narrow down what’s happening. 

- What version were you upgrading from that didn’t hang?
- Could you provide a Cloud URL to a hanged run?
- Could you update to the latest Cypress App version as we continuously fix these types of things. 
- Could you disable Test Replay, and report whether the hanging is still occurring? [Instructions here](https://docs.cypress.io/guides/cloud/test-replay#Opt-out-of-Test-Replay)
- Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?
