### ISSUE TITLE
Files with syntax errors are ignored

### ISSUE THREAD

**Issue by misogl** [cypress-io/cypress#293]
`cypress run` ignores files with syntax errors and the tests pass without any indication of a problem. The tests should fail instead.

Also when you run tests on a single file with syntax errors `cypress run --spec file.js`, cypress just displays the message "Tests should begin momentarily..." and hangs.

```
$ cypress version
Cypress CLI: 0.12.0
Cypress App: 0.17.10
```

**Comment by brian-mann** [comment]
Right, this happens because we ignore anything that is logged to the console in headless mode.

This is something we've been aware of for awhile and is actually getting fixed in `0.18.0` which is likely releasing this week.

**Comment by brian-mann** [comment]
Fixed in [`0.18.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0180-11272016).
