### ISSUE TITLE
opening tab in test window no longer works - chrome

### ISSUE THREAD

**Issue by jenkma02** [cypress-io/cypress#29301]
### Current behavior

if I have my own chrome browser window open and try to click the url in the cypress test runner chrome, it tries to open the link in the separate chrome window. In the past it has just opened a new tab in the test runner and it keeps all of the cookies, tokens, etc from the test. https://d.pr/v/R9bldP. If I close my separate chrome browser, the link works as expected in Cypress, but then I am no longer able to open the separate Chrome browser since my computer thinks Chrome is already open.

### Desired behavior

In the past it has just opened a new tab in the test runner and it keeps all of the cookies, tokens, etc from the test.

### Test code to reproduce

https://d.pr/v/83KJYe

### Cypress Version

13.7.3

### Node version

18.16.0

### Operating System

macOS 14.3.1 (23D60)

**Comment by jennifer-shehane** [comment]
This was an intentional change introduced in 13.5.0.

**Comment by UglyHobbitFeet** [comment]
Why was this change intentional? It breaks a lot of our ability to test a mock version of the site.  We also cannot manually enter URLs anymore which also are needed for manual testing since our site can behave differently under those circumstances
