### ISSUE TITLE
Remove support for webpack-dev-server v3 inside @cypress/webpack-dev-server

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#29308]
### What would you like?

With the next major version of Cypress, I would like to remove support for webpack-dev-server v3 

### Why is this needed?

webpack-dev-server v3 is now two major versions behind and hasn't been released in over 2 years [3.11.2](https://www.npmjs.com/package/webpack-dev-server/v/3.11.2). Removing the code from the  @cypress/webpack-dev-server would lessen the burden of maintenance

### Other

users would still be able to use CT with webpack-dev-server v3 support by using an older version of  @cypress/webpack-dev-server. Support would no longer ship with Cypress by default

**Comment by MikeMcC399** [comment]
- Removing `webpack-dev-server` `v3` is a prerequisite for removing the deprecated npm module [@types/webpack-dev-server](https://www.npmjs.com/package/@types/webpack-dev-server) (see Renovate deprecation list https://github.com/cypress-io/cypress/issues/3777). See also https://github.com/cypress-io/cypress/issues/30141

- [webpack-dev-server@4.7.0](https://github.com/webpack/webpack-dev-server/releases/tag/v4.7.0) introduced built-in `types`. Any earlier versions require `@types/webpack-dev-server`.
