### ISSUE TITLE
Cypress is blocking my tests due to human confirmation in any browser

### ISSUE THREAD

**Issue by forzaturian** [cypress-io/cypress#29318]
### Current behavior

I had no issue running Cypress tests, but today I've faced an identification issue on all browsers.
Even after passing a picture puzzle manually, I'm getting an incorrect password error while login.
![image](https://github.com/cypress-io/cypress/assets/47934778/c84d52a4-ba58-463f-a807-6cea98af17f7)
![image](https://github.com/cypress-io/cypress/assets/47934778/95fe6ebc-bcb4-4c8f-84e8-e4e37eea3310)
![image](https://github.com/cypress-io/cypress/assets/47934778/c27950f3-df00-486e-8031-56b6fd9f4792)
![image](https://github.com/cypress-io/cypress/assets/47934778/1ff6316a-70bc-42f5-a2a5-d2b191754437)

### Desired behavior

it works when I add long waits before each action 

### Test code to reproduce

(to be provided)

### Cypress Version

13.7.2

### Node version

16.13.2

### Operating System

macOS

**Comment by jennifer-shehane** [comment]
@forzaturian Many websites will code mechanisms to prevent automation from running on their site. This website might have added new mechanisms for this recently. Cypress is a bot, essentially, so many websites will try to block it. These downsides are outlined here: https://docs.cypress.io/guides/references/best-practices#Potential-Challenges-Authenticating-with-Social-Platforms

**Comment by forzaturian** [comment]
@jennifer-shehane thank you, I will review.
But the thing is no changes have been made on the website.

**Comment by gandhish** [comment]
@forzaturian Were you able to solve this problem?

**Comment by forzaturian** [comment]
@gandhish partially using cy.origin()
