### ISSUE TITLE
AUT not adjusting correctly with runner resizer

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2931]
Using the runner-resizer, the top of the AUT get covered up when the top bar overflows to another row

Using the window resizer, the AUT correctly adjusts, and is not coverd

**See below**
---------------------------v **incorrect**-----------------------------------------------------------------v--- **correct**
![18-12-11_11 18 24](https://user-images.githubusercontent.com/14625260/49814730-40164f80-fd38-11e8-9a4e-1b1f3cd3b6a4.gif)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
