### ISSUE TITLE
Support Ubuntu 24.04

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29319]
### What would you like?

to have support for Cypress running on Ubuntu 24.04

### Why is this needed?

- Ubuntu 24.04 is the next major [release](https://wiki.ubuntu.com/Releases) ~~planned for~~ released on April 25 2024. Users will start to install it locally and CI providers will be offering virtual machines based on this OS. The end of standard support is planned for June 2029.

- Cypress documentation [System requirements > Operating System > Linux](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System) includes the text "Ubuntu 20.04 and above", which includes Ubuntu 24.04

### Other

- ~~Beta~~ images are available from https://releases.ubuntu.com/24.04/

## End-user

Running Cypress `13.7.3` under Ubuntu `24.04` Beta:

- with [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) and Node.js `20.12.2` LTS shows success.

    `npm run local:run` reports "All specs passed!"

- with [cypress-io/cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app) and Node.js `20.12.0`

    `yarn dev` then `yarn test:headless` in a separate terminal reports "All specs passed!"

## Contributor

- Building Cypress from source on Ubuntu `24.04` Beta requires installing Python `3.11` and `NODE_GYP_FORCE_PYTHON=/usr/bin/python3.11` (see [Contributing > Requirements > Debian/Ubuntu](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#debianubuntu)). Node.js is `18.17.1.`

    - `yarn` is successful building Cypress from source

    - `yarn start` fails attempting to open Cypress Launchpad in Project mode. I would open a separate issue for this if it persists in the final release version of Ubuntu `24.04`.

        ```text
        $ yarn start
        yarn run v1.22.22
        $ yarn ensure-deps
        $ ./scripts/ensure-dependencies.sh
        success Folder in sync.
        $ cypress open --dev --global
        [8288:0412/172850.915093:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/mike/github/cypress-io/cypress/packages/electron/dist/Cypress/chrome-sandbox is owned by root and has mode 4755.
        ```

**Comment by jennifer-shehane** [comment]
@MikeMcC399 is there some indication that this won't work for end users? Or are you recommending we add specific tests around this to ensure it's working on the main repo?

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> is there some indication that this won't work for end users? Or are you recommending we add specific tests around this to ensure it's working on the main repo?

I don't see any issue for end users at this time and right now I suggest just waiting for the final release of Ubuntu `24.04` as there are still changes to be expected. The intention of my issue was just to add it to the radar, nothing more.

- For Ubuntu `23.10` there was a documentation-only issue - see https://github.com/cypress-io/cypress-documentation/pull/5528. This should be revisited after the final Ubuntu `24.04` is released to check if the suggested packages can still be installed.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Thanks for informing us. We'll have to update the docker images/docker factory to make sure it's working when that comes out.

**Comment by MikeMcC399** [comment]
- https://github.com/cypress-io/cypress/pull/29412 relates to this issue

**Comment by MikeMcC399** [comment]
[Ubuntu 24.04](https://ubuntu.com/blog/canonical-releases-ubuntu-24-04-noble-numbat) was released on April 25, 2024.

I haven't seen any issues running Cypress on this version as far as end-users are concerned.

**Comment by MikeMcC399** [comment]
I confirmed that Cypress `13.9.0` ran in a simple test on the GitHub-hosted [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) runner. The runner is in beta status and is being deployed at the moment.

Since there are no general unresolved issues with Cypress running on Ubuntu `24.04` I will go ahead and close this issue. If anything specific comes up, it should go into a new issue.

**Comment by MikeMcC399** [comment]
See also GitHub Actions announcement
[GitHub-hosted runners: Public Beta of Ubuntu 24.04 is now available](https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/) May 14, 2024.
