### ISSUE TITLE
If anything but a number is passed as the timeout option on cy.get(), the test never reaches the failure state

### ISSUE THREAD

**Issue by bernardodomingues-hotmart** [cypress-io/cypress#29323]
### Current behavior

Passing something that is not a number to the timeout field causes what should be a failing test never to reach the failure state.

### Desired behavior

If the option is not a valid number, ignore it and apply the default timeout (AFAIK 4s). 

### Test code to reproduce

https://github.com/bernardodomingues-hotmart/cypress-test-tiny

### Cypress Version

13.7.3

### Node version

v20.12.2

### Operating System

macOS 13.6.6 / Docker cypress-included

### Other

Even though we should have TS for type checking, old codebases are still in JS. This was caused by a developer error when creating custom commands, but there should be a safety net, as IMHO is better for a test to fail fast than never finish. This in a CI environment was a disaster :)

**Comment by cacieprins** [comment]
It may make the most sense here to throw a TypeError if a non-number timeout is supplied to any command, rather than falling back to the default timeout. What do you think?

**Comment by jennifer-shehane** [comment]
@bernardodomingues-hotmart We'd be open to a PR to handle this.

**Comment by sossost** [comment]
hi. @jennifer-shehane I am sossost, a new contributor. Can I fix this? thank you

**Comment by bernardodomingues-hotmart** [comment]
> It may make the most sense here to throw a TypeError if a non-number timeout is supplied to any command, rather than falling back to the default timeout. What do you think?

I agree.
