### ISSUE TITLE
Upgrade CircleCI Runner 1.1 variants to 3.0

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#29321]
### What would you like?

Runner 1.1 variants will not be supported through April 30th, 2024, at which point downloads and API endpoints will no longer be available. [Initial Notification.](https://circleci.com/changelog/machine-runner-3-0-released/)

Documentation for 3.0 migration: https://circleci.com/docs/install-machine-runner-3-on-linux/

### Why is this needed?

Our M1 builds/tests will not run after April 30th.

**Comment by AtofStryker** [comment]
migration to the 3.0 machine configuration is resolved and engineering documentation has been updated
