### ISSUE TITLE
My Run is terminating when one testcase is failed 

### ISSUE THREAD

**Issue by Vrutika** [cypress-io/cypress#29329]
### Current behavior

I can see this message 
https://on.cypress.io/readfile 
```
Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
```

It started happening after upgrading new cypress version 

### Test code to reproduce

I can see this message 
https://on.cypress.io/readfile Because this error occurred during a `after each` hook we are skipping all of the remaining tests.

### Cypress Version

V13.7

### Node version

V14

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
@Vrutika What version were you using previously? What are you using now? Can you provide a way to run and reproduce this?

**Comment by Vrutika** [comment]
I was using 12.17.4 and upgraded to 13.7.3.

**Comment by jennifer-shehane** [comment]
@Vrutika Can you provide a way to run and reproduce this? And narrow down the version that this issue began in?
