### ISSUE TITLE
cypress cloud filter by shows Jan 1, 1970 - Jan 19, 2038

### ISSUE THREAD

**Issue by bobbhatti** [cypress-io/cypress#29320]
### Current behavior

When I login to the cypress cloud and view the latest runs. The filter by dat field shows Jan 1, 1970 - Jan 19, 2038

![Screenshot 2024-04-12 at 17 36 33](https://github.com/cypress-io/cypress/assets/5570995/9c3caabe-5e6b-4032-89e0-75f260602660)

Pretty sure I've seen this raised before, but thought it had been fixed previously

### Desired behavior

filter should show dates closer to the current date, or as far basck as 90 days to the current date

### Test code to reproduce

login to cypress clous - see the screenshot in the current behaviour 

### Cypress Version

13.7.2

### Node version

20

### Operating System

Mac Sonoma 14.2.1

**Comment by jennifer-shehane** [comment]
@bobbhatti Thanks for the feedback! I'll forward this to our Cloud team. I'll close this issue since this repo is used for tracking issues on our open source App.
