### ISSUE TITLE
Time travel doesn't restore the state of custom elements

### ISSUE THREAD

**Issue by xxluke** [cypress-io/cypress#29335]
### Current behavior

When you have a HTML custom element, and use the "time travel" feature of Cypress to see the state of the document during a step, all custom components are rendered as they were initially.

In our case we have a web component for a loading screen which gets emptied when the data is loaded. In the page snapshots it always covers the page, even though it was actually already empty during that point.

On a side node, I didn't find a good documentation about how time travel works, or which JavaScript gets executed and which doesn't.

### Desired behavior

Cypress should remember and restore the actual state of the element. In my case the HTML content of the custom element.

### Test code to reproduce

This issue is the same as #8787 which got closed due to inactivity, but the issue still exists. It has a test code (I didn't test it again).

### Cypress Version

13.7.3

### Node version

v18.17.0

### Operating System

Windows 11 22H2

### Other

A workaround which might work at least in my case is to avoid all DOM-altering logic inside the custom element. It has to depend on attributes, which do get restored by Cypress.

**Comment by jennifer-shehane** [comment]
I've reopened https://github.com/cypress-io/cypress/issues/8787 and we can track it there.
