### ISSUE TITLE
Add an option to ignore preferences files load on browser relaunch

### ISSUE THREAD

**Issue by agentran** [cypress-io/cypress#29330]
### What would you like?

I'd like the option to be able to ignore chrome preferences load on relaunch

### Why is this needed?

We have a browser application that encrypts the user data dir, causing relaunches of the browser not to work.

**Comment by jennifer-shehane** [comment]
Hey @agentran, have you looked into using our existing [Browser Launch API](https://docs.cypress.io/api/plugins/browser-launch-api#Changing-browser-preferences) to change these preferences?

**Comment by agentran** [comment]
Hey @jennifer-shehane , this doesnt match the specifications of what we are trying to do.
here is the PR for reference.
https://github.com/cypress-io/cypress/pull/29332

We are trying to ignore loading the chrome preferences **files** from the --user-data-dir.
not sure how this relates to the browser launch API as I can't modify the files that we load by default no matter what..

**Comment by jennifer-shehane** [comment]
@agentran Here is a link to the binaries with the change for Linux and Mac. If you can run the command in the correct comment to see if the issue is resolved on your end, that'd be helpful: https://github.com/cypress-io/cypress/commit/e439881c64cd5f5bf4adb4cdad7ed94b9fafabd3#commitcomment-141535290

**Comment by agentran** [comment]
Hey @jennifer-shehane,
I can confirm that the binary does work as expected for me locally 👍

**Comment by jennifer-shehane** [comment]
@agentran You're welcome to use that binary for the time being. I do think they no longer stay available after something like 90 days? I'll discuss with the team how we would want to move forward with accommodating this.
