### ISSUE TITLE
when running timers after a screenshot, unhandled exceptions break the test

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/cypress#2934]
### Current behavior:

After upgrading to 3.1.3 we get tests that break because timers inside highcharts throw an exception and that falls through to cypress and fails the test

![image](https://user-images.githubusercontent.com/309321/49859468-e4130000-fdf7-11e8-8a39-8e986ea1abef.png)

and result after letting exception throw:

![image](https://user-images.githubusercontent.com/309321/49859688-6d2a3700-fdf8-11e8-8b8a-94fcca6cd22d.png)

### Desired behavior:

There is probably a bug in highcharts - but unhandled errors in timeouts should not break cypress.

### Steps to reproduce: (app code and test code)

I don't think this requires a test case - you should just wrap calling timers in a try-catch, log / or fire an event (however normal unhandled errors are handled), but not break the test.

### Versions

Cypress 3.1.3, windows 10, chrome

**Comment by jennifer-shehane** [comment]
You can listen for an catch uncaught exceptions coming from your application code by using our `uncaught:exception` event

https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by lukeapage** [comment]
@jennifer-shehane that doesn't work - what I'm reporting is that errors thrown in setTimeouts after resuming from a screenshot do not trigger that event and continue, but they make the screenshot command fail.
Its new in 3.1.3 because you weren't correctly restarting timers after screenshots previously.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
