### ISSUE TITLE
Error test with i use Cypress XHR toggle plugin

### ISSUE THREAD

**Issue by WarnnerSinotti** [cypress-io/cypress#29361]
### Current behavior

When i use Cypress XHR toggle plugin with cypress cloud/configuration idproject, the cypress broken.

Im using cypress with typescript.

import { defineConfig } from 'cypress'

export default defineConfig({
  projectId: '',
})

### Test code to reproduce

Im using cypress with typescript.

import { defineConfig } from 'cypress'

export default defineConfig({
  projectId: '',
})

### Cypress Version

V13.7.3

### Node version

V20.9.0

### Operating System

Ubuntu 22.04.4 LTS

**Comment by jennifer-shehane** [comment]
@WarnnerSinotti What is the error you’re seeing exactly? Can you print the output when you run Cypress?
