### ISSUE TITLE
The webpage is not loading properly in cypress runner and gitu

### ISSUE THREAD

**Issue by gtelus** [cypress-io/cypress#29375]
### Current behavior

when trying to navigate to https://www.telus.com/en/shop/home-services/internet/plans. the plan selection page is not loading completely in Cypress Runner, but the same is working fine in the local browser.

I have tried the below workaround, but it dosent help.

- Cypress to the latest version 13.8.0 and the lower version.
- Updating cypress config chromeWebSecurity: false, modifyObstructiveCode:false
- Clearing local storage, session
- Wait

### Desired behavior

cy.visit("https://www.telus.com/en/shop/home-services/internet/plans")

![image](https://github.com/cypress-io/cypress/assets/142248176/13da213f-03cd-4266-ac95-29a278ee3464)

but getting the below screen

![image](https://github.com/cypress-io/cypress/assets/142248176/0a0b5449-d095-4351-be31-05453b232ba6)

### Test code to reproduce

1. Navigate to "https://www.telus.com/en/shop/home-services/internet/plans"
2. check the plan selection is loading in cypress runner
![image](https://github.com/cypress-io/cypress/assets/142248176/770504b3-231c-43e9-a69b-f5c9790a04a2)

### Cypress Version

13.8.0

### Node version

v20.12.2

### Operating System

windows

**Comment by jennifer-shehane** [comment]
I do see this loading when I run this test. Ensure the `viewportHeight` and `viewportWidth` are set appropriately so that it's not switching to a different css style, hiding some areas of the app under test. 

```js
  it("should load", () => {
    cy.visit("https://www.telus.com/en/shop/home-services/internet/plans")
  });
```
![Screenshot 2024-04-25 at 10 34 12 AM](https://github.com/cypress-io/cypress/assets/1271364/36a6fccf-12d4-4e62-99a0-7561b812f24b)

**Comment by gtelus** [comment]
hey @jennifer-shehane : Thanks for your response.. i am trying with same viewport, but not able to load the page successfully.

these are default values used in cypress config
  chromeWebSecurity: false,
  viewportHeight: 660,
  viewportWidth: 1000,

![image](https://github.com/cypress-io/cypress/assets/142248176/58500e27-4ed1-4af6-b276-5b6d259eca27)

may i know the Cypress config used to load the page successfully?

**Comment by jennifer-shehane** [comment]
@gtelus Do you have any other code in the test file? It looks like you have some requests modified in the screenshot.
