### ISSUE TITLE
RangeError "offset" is out of range on `compareSnapshot` with 13.8.0, works in 12.3.0.

### ISSUE THREAD

**Issue by andersjanmyr** [cypress-io/cypress#29373]
### Current behavior

I get the following error, similar to [this issue](https://github.com/cypress-io/cypress/issues/2034) in cypress `13.8.0`.

`RangeError The value of "offset" is out of range. It must be >= 0 and <= 4371836. Received 4371840`
The value seems very arbitrary. 

The code is nothing special:
```js
        cy.findByTestId('alert-manager-container')
            .compareSnapshot({
                name: 'customer issue with photo and comment TC0064',
                testThreshold: 0.12,
                retryOptions: { limit: 6, delay: 1500 }
            });
```

Versions used:
```
$ node --version
v16.17.1

$ cat package.json |grep cypress
    "@cypress/grep": "^4.0.1",
    "cypress-browser-permissions": "^1.1.0",
    "cypress-image-diff-js": "^2.1.4",
    "eslint-plugin-cypress": "^2.15.2",
    "@testing-library/cypress": "^10.0.1",
    "cypress": "13.8.0",
    "cypress-mailosaur": "^2.14.0",
```

### Desired behavior

Behave as it did in the previous version.

### Test code to reproduce
```js
        cy.findByTestId('alert-manager-container')
            .compareSnapshot({
                name: 'customer issue with photo and comment TC0064',
                testThreshold: 0.12,
                retryOptions: { limit: 6, delay: 1500 }
            });
```

### Cypress Version

13.8.0

### Node version

v16.17.1

### Operating System

macOS 14.4.1

### Other

I know this is not a great bug report, and I haven't isolated the test, but I would like some pointers on where to look.

**Comment by jennifer-shehane** [comment]
@andersjanmyr I haven't seen this error in a long time. It would be great to isolate it down to purely a `cy.screenshot()`, and exclude the image diff plugin as a factor to see if it is on our side.

**Comment by andersjanmyr** [comment]
I'm closing it, I can't reproduce it in an isolated test.

**Comment by t00** [comment]
I think this issue might happen when the image was not fully visible on the page while doing compareSnapshot.
