### ISSUE TITLE
Chainer command 'have.length.of' in should() silently fails

### ISSUE THREAD

**Issue by bespinozam** [cypress-io/cypress#29392]
### Current behavior

When running a command for checking the ocurrences found of a given element, the usual command to use is

`should('have.length', 1)`

Any non-valid chainer command, as explained here https://docs.cypress.io/api/commands/should#Arguments should fail. But using variations like this:

`should('have.length.of', 1)`

And here's how the log looks like (the first line is the listed command, the second is just a click command on the same element):

![Screenshot 2024-04-23 at 14 08 41](https://github.com/cypress-io/cypress/assets/58754727/a8425560-be56-4dd9-a997-96f05b198028)

does NOT raise a failure. This variation in special does not cause a failure, because others like

`should('have.length.asdasdasdasdas', 1)`

DO cause a failure. I think that the reason is that there is a Chai valid chainer that has a similar pattern:

`should('have.length.of.at.most', 1)`

I believe the 'have.length.of' command hence should cause a failure to avoid silent fails in a test.

### Desired behavior

A test should fail if a command like `should('have.length.of', 1)` is issued

### Test code to reproduce

cy.get('[data-test-id="simple-signup-button"]').should('have.length.of', 1);

### Cypress Version

13.6.1

### Node version

18.18.1

### Operating System

MacOS v13.6.6

**Comment by jennifer-shehane** [comment]
@bespinozam `of` is a valid chainable getter. It doesn't actually do anything, it's just for making more readable chainers, so it won't change the actual behavior. This is noted in our docs here: https://docs.cypress.io/guides/references/assertions#Chai

So you can write any of the words below and it won't change the behavior

![Screenshot 2024-04-23 at 4 44 47 PM](https://github.com/cypress-io/cypress/assets/1271364/4c3886cb-b5ca-48d4-bdb6-b7f785598cc3)
