### ISSUE TITLE
Dashboard should not show a video link if no video has been uploaded

### ISSUE THREAD

**Issue by carlos-granados** [cypress-io/cypress#2939]
### Current behavior:

If you set `videoUploadOnPasses` to false, Cypress will not upload a video for successful tests. However, a video link is still shown in the dashboard for these tests and if you click it, you will get a page with the message `The media could not be loaded, either because the server or network failed or because the format is not supported`

### Desired behavior:

If no video was uploaded there should be no video link in the dashboard

### Steps to reproduce: (app code and test code)

Set the `videoUploadOnPasses` option to false and run a successful test. No video will be uploaded. Go to the dashboard and locate this test. It will have a link to play a video. If you click on the link you will get the message posted above

### Versions

Cypress 3.1.3

### images

This is what we see for a successful test. Notice the video button which can be clicked

![screen shot 2018-12-12 at 20 24 15](https://user-images.githubusercontent.com/1383106/49896679-046caa00-fe4c-11e8-9105-92ee64e085cd.png)

Then when the button is pressed, we get this:
![screen shot 2018-12-12 at 20 25 32](https://user-images.githubusercontent.com/1383106/49896710-1d755b00-fe4c-11e8-8586-cf1c017a40f0.png)

**Comment by jennifer-shehane** [comment]
Have confirmed, this is a bug in the API (or possibly the server) @bahmutov 

- Run has configuration `{videoUploadOnPasses: false}`
- `GET` to runs and instance return a video in the `videos` array with all fields present, including a validly formatted `url`
- `GET` to the the `.mp4` resource itself returns `403 Forbidden`

**Comment by jennifer-shehane** [comment]
There should no longer be links to play a video on passing spec files when `videoUploadOnPasses` is set to `false`. This should affect recorded runs from now on.

**Comment by carlos-granados** [comment]
I can confirm that this is working as expected now. Thanks for fixing it!

**Comment by TheDhamo** [comment]
@jennifer-shehane  
Looks like the issue is reoccurring now in cypress v7.2.0

**Comment by jennifer-shehane** [comment]
Reopening since I've seen people mention this. Also here: https://github.com/cypress-io/cypress/issues/15437

**Comment by jennifer-shehane** [comment]
I ran a simple test with a single passing specfile with `videoUploadOnPasses: false` and I don't see an area in the Dashboard to watch the video. The video button is disabled in all the places I could see. 

So, I'll need a more specific example to run to recreate this to narrow down why this happens for some people. Also can anyone with this issue run `DEBUG=cypress:server:project cypress run` and print the logs here?

**Comment by lucasmp2001** [comment]
I'm have the same problem, I want to see the video generated in the dashboard of the run test, but it contains the same error, and it doesn't generate as much when the test fails, or runs successfully

or sometimes it only records 00:01 seconds of the test, and I can't even open the video anyway...

![image](https://user-images.githubusercontent.com/74330563/129569620-61dc9282-f1e3-415b-8ef8-f40b52c8f9c6.png)

![image](https://user-images.githubusercontent.com/74330563/129569781-cb7a6d00-9787-4909-be19-8a7598db05a6.png)
