### ISSUE TITLE
Intercept doesn't work in beforeEach

### ISSUE THREAD

**Issue by lalicia** [cypress-io/cypress#29405]
I originally posted under this [issue](https://github.com/cypress-io/cypress/issues/25718) where someone had detailed the problem I was having in a different Cypress repository - I was advised to move the post to here by @nagash77.

The issue is NOT in this repository - it's in an archived repository [https://github.com/cypress-io/cypress-realworld-testing-blog](https://github.com/cypress-io/cypress-realworld-testing-blog)

The code given in cypress/e2e/practice/network-request.cy.js is:
```js
describe("Network Requests", () => {
  beforeEach(() => {
    cy.intercept("GET", "http://localhost:3000/api/posts", (req) => {
      // this is to disable browser caching
      // https://glebbahmutov.com/blog/cypress-intercept-problems/
      delete req.headers["if-none-match"];
    }).as("posts");

    cy.visit("http://localhost:3000");
  });
```

The error is:
![image](https://github.com/cypress-io/cypress-realworld-app/assets/102915959/ec2b1660-4e54-4e54-a646-292fa7dfa8db)

Can someone please explain why this is happening and how to fix it? I'm new to Cypress and trying to learn. Thanks :)

**Comment by sperrye** [comment]
I'm also experiencing this issue after upgrading from 12 to 13.
The intercept aliased in the beforeEach was working reliably until the upgrade.
