### ISSUE TITLE
Running same specs multiple times

### ISSUE THREAD

**Issue by sergioafonso** [cypress-io/cypress#2940]
I have a requirement to run all the specs multiple times using different data sets. Apart from the part of the data sets, do you know of a way to trigger multiple times the same specs with a single cypress run

### Current behavior:

With a command like npm run e2e, cypress run runs all specs once.

### Desired behavior:

Being able with the same command, run multiple times the same specs

**Comment by jennifer-shehane** [comment]
Hey @sergioafonso, I would take a look at using 'grouping' to achieve what you want. [Docs on it are here](https://on.cypress.io/parallelization#Grouping-by-spec-context).

So you could do `cypress run --group dataSet1 --specs cypress/integration/**` and depending on how you want to run the data through the specs, maybe pass a Cypress environment variable to define which dataSet to use like: 

```
cypress run --group dataSet1 --specs cypress/integration/** --env data=admin
```

```
cypress run --group dataSet2 --specs cypress/integration/** --env data=owner
```

Is this helpful? I'd have to know more specifics to give more specific instructions.

**Comment by andreasmihm** [comment]
@sergioafonso How do you have your dataSets coded? as fixtures?

**Comment by nishant-sngl** [comment]
Hey All,
Even i have the same requirement to run all my tests for multiple data.
As per the above solution given via groups, it seems that we need to run the scripts multiple times.
In my case i have 10+ data sets, so i have to run the script those many times.
Is there a way to trigger it once, and it takes the data from fixtures or any config and then run the whole suite for multiple data.

A way is to loop all the desc/it in loop of data list, but that seems to be just a work around.
Please help here.
