### ISSUE TITLE
In JetBrain Aqua could not find number alias declaration

### ISSUE THREAD

**Issue by DesKonstantin** [cypress-io/cypress#29408]
### Current behavior

Now, in JetBrain Aqua errors: could not find number alias declaration

Errors shown if alias declared in commands.js and try used in another test.cy.js
 
But alias is work for cypress test
alias declared
![image](https://github.com/cypress-io/cypress/assets/30823982/70a6ce7e-7cbe-4f67-852e-2859a6acfcbf)

Errors:
![image](https://github.com/cypress-io/cypress/assets/30823982/b7af3ced-5f9e-4bcc-bb13-6031ad66e622)

### Test code to reproduce

        cy.get('.p-datatable-tbody > :nth-child(1) > .column_incidentNumber').invoke('prop', 'innerText').as('number', { type: 'static' })

        cy.get('@number').then((number) => {
            cy.log('Test: ' + number) //prints number
            })

### Cypress Version

13.8.1

### Node version

21.1.0

### Operating System

Win 11 Pro 22621.3447

**Comment by jennifer-shehane** [comment]
@DesKonstantin I'm unfamiliar with Jetbrains IDE. What is running these checks and raising these errors?

**Comment by DesKonstantin** [comment]
@jennifer-shehane 
These are inspections in IDEA that check the alias dependency chain. For some reason, if an alias is created in one function and used in another, then the chain is not set
![image](https://github.com/cypress-io/cypress/assets/30823982/3ba199ff-5aa7-4726-8406-ec96b63bf39e)

**Comment by jennifer-shehane** [comment]
@DesKonstantin We don't work on the support of Cypress within JetBrain Aqua. I would suggest opening an issue or support ticket with the Jetbrains team to surface this.
