### ISSUE TITLE
null should be replaced with default timeout

### ISSUE THREAD

**Issue by Dale-777** [cypress-io/cypress#29425]
### Current behavior

release 13.8.1 resulted in 50% of our tests failing due to tests requiring updates.

https://github.com/cypress-io/cypress/issues/29323
https://github.com/cypress-io/cypress/pull/29327
https://github.com/cypress-io/cypress/issues/28872

I believe the changes documented here, did not consider the use of Page Object Model, when a selector/element is referenced from the test it block (from many), when ONLY in some instances do you need to specify the timeout (often you might not need to change a timeout), and thus you do not bother to pass a value. This is a valid, and I am sure a common use case.

<img width="1024" alt="Screenshot 2024-04-28 at 21 21 23" src="https://github.com/cypress-io/cypress/assets/77000850/a67e0f9a-8f28-4c26-98d9-ce8ac3719be8">

### Desired behavior

Rather when null it should be set to the default timeout rather than fail with the error

### Test code to reproduce

File 1 (test 1):
```js
globalNavigation.elements.companyNameDropdown().should("be.visible");
```

File 2 (test 2):
```js
globalNavigation.elements.companyNameDropdown(90000).should("be.visible");
```

File 3 (page object):
```js
  elements = {
    companyNameDropdown: (timeout?: number) => cy.get('[data-cy="avatar"]', { timeout })
  };
```

### Cypress Version

13.8.1

### Node version

v18.16.0

### Operating System

All OS

### Debug Logs

```shell
rolling back to 13.8.0, resolves the issue
```

**Comment by Dale-777** [comment]
@jennifer-shehane 
@percytrar 
@eos

**Comment by jennifer-shehane** [comment]
Hi @Dale-777, thanks for reaching out. I'm sorry this resulted in unexpectedly breaking tests. 

The only valid option for `timeout` has always been a Number. The addition of validations was to ensure one wouldn't get into a situation where Cypress would hang with invalid options passed to timeout as seen in this issue: https://github.com/cypress-io/cypress/issues/29323

This is not a change of any of our behavior as it has always only ever accepted a Number. We don't intend to make an update to the logic of `timeout` to accept a `null` or `undefined` value for `timeout` as this may cause confusion if that were introduced. Does `undefined` mean they want it to be `0` timeout or to use the default?

We suggest updating any custom commands for Page Object Models to handle when the timeout option is not passed via the calling function. An example is shown below that falls back to default timeout if it is not present.

```js
const elements = {
  companyNameDropdown: (timeout) => cy.get('[data-cy="avatar"]', (timeout ? { timeout } : {}))
}

it('test without timeout', () => {
  elements.companyNameDropdown().should("be.visible")
})

it('test with timeout', () => {
  elements.companyNameDropdown(7000).should("be.visible")
})
```

![Screenshot 2024-04-29 at 12 02 30 PM](https://github.com/cypress-io/cypress/assets/1271364/ee4d2c07-445e-4117-bfbd-77eba8ee0881)
