### ISSUE TITLE
Cesium <> Cypress Gitlab Pipeline

### ISSUE THREAD

**Issue by RobAmey22** [cypress-io/cypress#29427]
### Current behavior

We noticed that our tests in pipeline are taking too long to finish than usual, and jobs getting stuck/failing much frequently. 

For instance, a test case which locally takes ~2 minutes (headed run) and ~5 minutes (headless run) is taking ~11 minutes in the pipeline. Initial investigations point towards Cesium's GPU/hardware acceleration dependency to work efficiently, which is not available in the headless mode (local machine: Linux & Windows & GitLab runners). 

Otherwise, headless runs used to be much faster than headed every time. Meanwhile, Mac machines are somehow not facing this issue, only Windows and Linux (local machine and GitLab runners).

Pipeline: Linux runners

![image](https://github.com/cypress-io/cypress/assets/109523199/a00e8751-0ffa-4f2d-bcf9-f27a0efb0721)

![image](https://github.com/cypress-io/cypress/assets/109523199/8339162c-39bc-42e8-b4b7-5a9377a3b40f)

![image](https://github.com/cypress-io/cypress/assets/109523199/dcc846c2-6d16-414b-acd7-89f6bc38ff5f)

![image](https://github.com/cypress-io/cypress/assets/109523199/0c2dc4c2-39b1-4e19-b6ea-0324043f8b87)

### Desired behavior

Ideally, the pipeline should be much quicker than the local test case execution, no job should get stuck or fail.
The pipeline has multiple stages working in parallel on individual runners. Hence, the execution should be quicker and smooth without any stuck cases.

### Test code to reproduce

Due to privacy concerns, sharing text code won't be possible.

### Cypress Version

12.14.0

### Node version

18.16.0

### Operating System

Linux

**Comment by jennifer-shehane** [comment]
>Initial investigations point towards Cesium's GPU/hardware acceleration dependency to work efficiently, which is not available in the headless mode (local machine: Linux & Windows & GitLab runners).

@RobAmey22 What led you to believe this could be the cause of the issue here?

**Comment by RobAmey22** [comment]
Some articles that I read and comments on other issues. @jennifer-shehane
