### ISSUE TITLE
Windows OS cypress remains on second screen no matter what you do

### ISSUE THREAD

**Issue by Kuisaa** [cypress-io/cypress#29423]
### Current behavior

If you use cypress on the second screen in Windows 10 and close cypress from the browser x, cypress will remain on the screen it was last displayed on. If your screen setup changes you are not able to access the window again before connecting to another screen and then adjusting your screen settings to match the one you had when you last used cypress. If you do the removing of screen while cypress is running, all is ok.

### Desired behavior

If you remove the second screen after closing the software, and restart the software, you are able to retrieve the window to your screen or it will automatically spawn on your main screen.

### Test code to reproduce

Start cypress with "npx cypress open". 
Move Cypress window to the second screen of your setup.
Close Cypress from the browser x.
Detach second screen or re-arrange screen setup from settings to be different.
Run "npx cypress open" again.
Cypress opens on the screen that does not exist.

### Cypress Version

13.6.4

### Node version

v18.18.2

### Operating System

Edition	Windows 10 Pro Version	22H2 Installed on	‎03/‎05/‎2022 OS build	19045.4291 Experience	Windows Feature Experience Pack 1000.19056.1000.0

**Comment by MikeMcC399** [comment]
@Kuisaa

This is a known issue with Microsoft Windows 10 and 11 that is unrelated to Cypress.

You may find the Microsoft support article [Some Programs Are Displayed Off the Screen](https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4) helpful. Or Google "windows move window to current monitor" for a selection of articles and videos on this topic.

- The issue was also reported under #29165.

**Comment by Kuisaa** [comment]
None of the listed methods for retrieving the window is working. I have never had this issue with any other application and I use different setups daily. Other browsers get brought back to main screen. To me it seems Cypress somehow remembers where it was last used.

I have tried Method 1) There is no option for maximize on the taskbar, but cascade windows does not bring cypress back to main screen. You can see that the app opens to another screen when you press it to be active.

Method 2) There is no option for move.

Method 3) Will not help as I would like to be able to retrieve the app even when I don't have additional screen available.

I have also tried:
Moving the application to another virtual Desktop. Cypress remains on "second screen".

Activating the app screen by clicking on taskbar and pressing windows+shift+arrowkeys. If you have another screen attached in wrong orientation, this works, but if you don't have external screen attached you are not able to move it with these commands either.

**Comment by Kuisaa** [comment]
Ok it seems that to be able to retrieve the screen when you don't have the second screen what you need to do is

1) Run cypress
2) Click cypress on task bar
3) Press windows+shift+up arrow
4) Then do the cascade windows

**Comment by mpelzsherman** [comment]
The workaround above doesn't work for me in Windows 11.

**Comment by MikeMcC399** [comment]
@mpelzsherman 

For some reason the Microsoft article is not displaying at this time:

https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4

however I found a Windows 11 community discussion

https://answers.microsoft.com/en-us/windows/forum/all/app-runs-off-screen-in-windows-11/47609284-eb59-48f2-82f8-b648a143808f

**Comment by dirk-schiller** [comment]
Same happens on Tuxedo / Ubuntu 24.x.

**Comment by MikeMcC399** [comment]
@dirk-schiller 

> Same happens on Tuxedo / Ubuntu 24.x.

I believe that would be a different issue, since Ubuntu doesn't use the same windowing system as Microsoft Windows.
