### ISSUE TITLE
Getting RangeError when trying to load application and get an element

### ISSUE THREAD

**Issue by rgangal** [cypress-io/cypress#29434]
![Screenshot 2024-04-29 at 11 21 19 AM](https://github.com/cypress-io/cypress/assets/7269030/36b10c6b-134e-4f31-b5fe-8cfce04faa09)
### Current behavior

I am getting the following error when running cypress and interacting with the application. 

`RangeError : Timed out retrying after 30000ms: Maximum call stack size exceeded`

### Test code to reproduce

```js
describe('Sample - Tests', () => {
  let drive;
  before(() => {
    cy.copyCookies();
    cy.visit('****')
  });

  it('Should contain app title', () => {
    cy.get('[browser-title="*****"]').should('exist');
  });
});

```

### Cypress Version

13.8.1

### Node version

18.14.2

### Operating System

macOS 14.4.1

**Comment by jennifer-shehane** [comment]
The `collectRoots` function is called when there is shadow DOM we need to walk. In this situation, it's getting into some infinite recursive loop it seems. 

Can you provide an example of a URL or HTML file to run tests against that will cause this issue? That's the only way we'll be able to track this down.
