### ISSUE TITLE
Element is being covered by another element ({force: true} is not working)

### ISSUE THREAD

**Issue by pillsi** [cypress-io/cypress#29449]
### Description

When I click a link, I expected a pop up box to happen, but I saw the error "Element is being covered by another element" happened instead, I cannot use {force: true} to override this check since I need to check the element inside the pop up box.

### URL of Issue(s)

An Intranet site

### Steps to replicate

1. Go to home page
2. Click on product item details
3. Click on "link__text" 
4. See error: Timed out retrying after 4050ms: cy.click() failed because this element:

<span class="link__text" __skip="true">Show re...</span>

is being covered by another element:

<div class="mds-slide-in-panel__title-container">...</div>

### Browser

Google Chrome V120

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by jennifer-shehane** [comment]
@pillsi Could you provide some code to run that recreates this issue? We'll need that to investigate. Otherwise we'll have to close the issue with no path forward.

**Comment by pillsi** [comment]
Hi Jennifer,

Thanks for your kind reply! Please find my code and error message in the following:

When('I click show redemption details', ()=>{
    cy.get("body > mds-slide-in-panel-modal").find("mds-link").eq(0).click();
});

Then('Redemption array list should display', ()=>{
    cy.get("#detail-redemption-link > mds-flyout-overlay > div:nth-child(1)").contains('21.10')})

----------------------

CypressError
Timed out retrying after 4050ms: cy.click() failed because this element:

<mds-link underline="false" start-icon="ico_copy_to_clipboard" end-icon="" text="Copy" inverse="false" leading-pipe="false" trailing-pipe="false" truncation="none" tab-focusable="true" inactive="false" is-button="false" id="detail-body-copy-link" data-testid="detail-body-copy-link" href="javascript:void(0)" label-aria-text="" accessible-text="" class="mds-link--cmb"></mds-link>

is being covered by another element:

<div class="mds-slide-in-panel__heading-container">...</div>

Any suggestions will be appreciated!

Thanks!
Pillsi

________________________________

**Comment by jennifer-shehane** [comment]
@pillsi We'll need a way to run the code to see the error and inspect the DOM in order to investigate. Or an example in an example app.
