### ISSUE TITLE
cy.closest() yields multiple elements

### ISSUE THREAD

**Issue by realioseb** [cypress-io/cypress#2944]
### Current behavior:
I'm getting a specific dom element inside a table and want to get closest tr but console says that `closest` command yields 10 elements (all rows)

```js
cy.get('[data-cy="grid"]').within(() => {
    cy.contains(text)
    .first()
    .closest('tr').within(() => {
      cy.get('[data-item="gridRow_actions"]').click()
    })
  })
```

![capture](https://user-images.githubusercontent.com/6136314/49942074-b912d400-fefd-11e8-8496-113347283312.PNG)
### Desired behavior:
It should be finding first ancestor tr

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
