### ISSUE TITLE
Cypress Cloud tests hanging on specs- and timeout 

### ISSUE THREAD

**Issue by Ashorner** [cypress-io/cypress#29442]
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/135355240/b06de936-a25e-4f41-aa68-5caabfc1fd43)

You can see in the screen shot above- test specs are hanging, this test usually only takes a matter of seconds 

it now timesout 

### Desired behavior

tests run smoothly, don't hang and don't timeout

### Test code to reproduce

Running testing on CI- cypress cloud

### Cypress Version

13.8.1

### Node version

20.11.16

### Operating System

14.2.1 (23C71

### Debug Logs

```shell
na
```

### Other

na

**Comment by jennifer-shehane** [comment]
@Ashorner We'll need some more information to help. What changed from the time it used to run quickly to it now timing out? Did you update Cypress? Did you run cypress differently?

Can you also provide a way for us to reproduce the hanging? 
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?
