### ISSUE TITLE
Wrong modal renderization

### ISSUE THREAD

**Issue by ferrange** [cypress-io/cypress#29459]
### Current behavior

In a specific webpage, when we select an asset and we press on donwload, a modal is displayed showing more options than it should, like if it was loading all the possibilities without having the js logic in consideration.
![image](https://github.com/cypress-io/cypress/assets/55395962/779b6232-86bf-4879-bda4-282c6de74450)
As you can see, there are no extra flags checked

### Desired behavior

As it is when navigating through the browser or any other framework, when we perform the same actions, the modal is displayed showing only the options it has to:
![image](https://github.com/cypress-io/cypress/assets/55395962/5f62d947-9380-427e-a514-76752a4777ed)
If we check the "Dynamic Rendition(s)" flag, then more options are displayed:
![image](https://github.com/cypress-io/cypress/assets/55395962/e9f67a6f-670d-4d51-a420-16a0e9a2be04)
Here you can see how the property **display** swaps from **none** to **block** when checking and unchecking the flag:
![none](https://github.com/cypress-io/cypress/assets/55395962/02e52374-a2ce-4329-a01b-dd40c5b52b1d)
![block](https://github.com/cypress-io/cypress/assets/55395962/6c4b5fe3-8e94-447d-994c-90639c310280)

### Test code to reproduce

No need of test code to reproduce, it happens aswell when accessing to this webpage by a cy.visit() and then navigating "manually" through cypress interface using npx cypress open.
Due to confidenciality purposes I can not share the website, all I can say is it's based on the Adobe CRM, named Adobe Experience Manager

### Cypress Version

13.6.4

### Node version

v21.2.0

### Operating System

Windows 10 Enterprise 22H2

### Other

@victortfe

**Comment by jennifer-shehane** [comment]
@ferrange Are there any errors in the Cypress browser that aren't shown in an outside browser?

Also make sure you're using as close to the same browser type and version as possible. 

Without a way for us to run and see the issue, there's not much we can do to track down the root cause unfortunately.
