### ISSUE TITLE
Download Chromium link data not refreshed since Oct 2023

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29460]
### Current behavior

The Cypress Launchpad menu `Help > Download Chromium` menu item links to
https://vikyd.github.io/download-chromium-history-version/#/
which shows stale data.
For instance the latest Linux x64 version of Chromium is shown as
version 121.0.6158.0 position: 1231300 from October 2023.

![image](https://github.com/cypress-io/cypress/assets/66998419/6bc4156b-7a53-4836-b70c-15eb30039975)

### Desired behavior

The Cypress Launchpad menu `Help > Download Chromium` menu item should provide up-to-date information for downloading Chromium.

Perhaps the following link is an appropriate alternative?

https://www.chromium.org/getting-involved/download-chromium/

### Test code to reproduce

Execute

```shell
npx cypress open --browser electron
```

In Cypress Launchpad menu select `Help > Download Chromium` which links to https://on.cypress.io/chromium-downloads and forwards to https://vikyd.github.io/download-chromium-history-version/#/

### Cypress Version

`13.8.1`

### Node version

`v20.12.2` LTS

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

No relevant information in debug logs.

### Other

1. Ubuntu provides Chromium as a snap package
https://code.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source

2. [Puppeteer > Supported browsers](https://pptr.dev/supported-browsers) shows that it has transitioned from supporting "Chromium" (last supported version `112`) to instead supporting "Chrome for Testing" (last supported version `124`).

    - https://github.com/cypress-io/cypress/issues/28554 and https://github.com/cypress-io/cypress/pull/28243 regarding supporting "Chrome for Testing" in Cypress however have not yet been processed.

**Comment by jennifer-shehane** [comment]
We can easily update this to be whatever we want internally via our on link rerouting. I wonder what happened to that website because it used to be up to date. :/

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I wonder what happened to that website because it used to be up to date. :/

- The [Crawler](https://github.com/vikyd/chromium-history-version-crawler) for this site relies on https://omahaproxy.appspot.com/ which has been shut down.  Issue https://github.com/vikyd/chromium-history-version-crawler/issues/3 for this has been open since last month.

- Current Chromium version information is available on https://chromiumdash.appspot.com/releases (this is not a download site however).

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Ah, yah we had the same issue with our site. Just wasn't worth updating after the omahaproxy changed.

**Comment by jennifer-shehane** [comment]
I know you can't see this link, but this is being updated here: https://github.com/cypress-io/cypress-services/pull/8325 And would hopefully be released on Monday.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

The quick fix would be to change

https://on.cypress.io/chromium-downloads

to point to

https://www.chromium.org/getting-involved/download-chromium/

Long-term I wonder if the Cypress Launchpad should actually offer a `Help` link to `Download Chromium` as other browsers such as Chrome seem to be more in demand for testing compared to Chromium. Perhaps this link should be removed (would probabyl fall into the category "breaking change" though)?

**Comment by jennifer-shehane** [comment]
Mostly the intention of this is to offer a way to download lower versions of Chrome to test if something is working in an earlier version that's not broken.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

This issue is closed, however I'm not seeing any change to https://on.cypress.io/chromium-downloads so far, so the issue still exists.

**Comment by jennifer-shehane** [comment]
Yah I missed the release by like an hour. Will probably release on Wednesday.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thanks for the explanation!

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

The new redirect to https://www.chromium.org/getting-involved/download-chromium/ is now effective:

![image](https://github.com/cypress-io/cypress/assets/66998419/5826b6a8-057f-4456-a3ae-0b191c4d6d46)

so this issue can now be closed.

Thanks!
