### ISSUE TITLE
Cypress first time launch on windows 10 gives an error 

### ISSUE THREAD

**Issue by Janzelf** [cypress-io/cypress#2946]
cypress gives an error but appears to continue after some time
### Current behavior:
Launching with  `npx cypress open` gives following error:

```
Error: EPERM: operation not permitted, mkdir 'C:\Users\Jan'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:178:20)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:47:53
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
Install for prefix@latest failed with code 7
```

Cypress apparently fails to create a first time config file
### Desired behavior:

The environment variable `%userprofile%` contains spaces  `C:\Users\Jan de lint`
This should be put in quotes in windows scripts:

Could I try and create the config by hand so that this error is bypassed?
Removing the blanks from the windows home directory name requires a new windows installation
### Versions

Latest versions of windows 10 (1809) 64 bits, npm and cypress

**Comment by Janzelf** [comment]
Every time I start cypress, I get this error. Takes time, however testing seems to continue

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
