### ISSUE TITLE
Click on submit form does not recognize HTTP 302 response code

### ISSUE THREAD

**Issue by AngeloBadellino** [cypress-io/cypress#29488]
### Current behavior

When attempting to automate a login using Auth0's Universal Login, the automation fails to execute the click on the submit button, preventing the completion of the process.  

On a live environment the user input the username and click on the form submit. The click triggers a POST that return a [302 ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) response. Then the user can see the password field and conclude the login by performing another click on the submit button.

During the cypress e2e run the first submit seems to be performed since the password field become visible, but the test timeout after 60 second while waiting for the page to be loaded.

![image](https://github.com/cypress-io/cypress/assets/2067018/5e23eb1a-329d-4b8a-8c15-0e782ed5ec6b)

### Desired behavior

On submit click Cypress should recognize the response code returned after posting the form and continue the login process.

### Test code to reproduce

The described behavior can be seen by cloning and running the following repo.

Its enough to run _npm install_ and _npm run serve_ and then open cypress to run the only test,

https://github.com/AngeloBadellino/cypress_auth0

### Cypress Version

13.8.1

### Node version

v18.20.2

### Operating System

Windows 10 enterpsice 19045.4291

**Comment by bsdmon** [comment]
I had a similar behavior in one of my internal application and I managed to found out what was going on : `Location` response header value has `http://` and it seems that *Cypress* refuses to load the page (which may be an expected behavior, I guess).

Of course, I'm not telling that it is the same issue but it is worth to check your `Location` header value ?

**Comment by AngeloBadellino** [comment]
Running the test under HTTPS make cypress correctly intercept the responses from the external domain.
Thanks!
