### ISSUE TITLE
Cypress v13.9.0 is not running tests

### ISSUE THREAD

**Issue by FazliddinAli** [cypress-io/cypress#29491]
### Current behavior

We have recently removed all references to `cypress-cloud` but we can not get cypress to run tests in CircleCI. We are using the cypress orb and we have cleared cache but we keep getting the below output.
<img width="1077" alt="Screenshot 2024-05-08 at 6 20 17 PM" src="https://github.com/cypress-io/cypress/assets/102693663/532021b1-25a1-47c6-b086-0da738c401d5">

### Desired behavior

It works as expected locally.

### Test code to reproduce

I am not able to share the test code since it is a private repo.

### Cypress Version

13.9.0

### Node version

v20.9.0

### Operating System

Docker

**Comment by jennifer-shehane** [comment]
Our recommendations when seeing this error are:

- If you have a 3rd party installed that is listed in the error message, remove that library and all configuration / env vars related to it.
- If you have used `record: false` in some way, update your code to omit the `record` flag altogether.

**Comment by FazliddinAli** [comment]
Hi, we have removed all of the env variables related to that 3rd party library and we are not using record in any shape. Is there any way to tell what is Cypress specifically looking at?

**Comment by jennifer-shehane** [comment]
@FazliddinAli Have you cleared all env vars in your CI runs related to cypress-cloud? And config files? You can also click on the link in the error message for more dedicated assistance in migrating.

**Comment by Popone55** [comment]
> @FazliddinAli Have you cleared all env vars in your CI runs related to cypress-cloud? And config files? You can also click on the link in the error message for more dedicated assistance in migrating.

Does this mean that cypress detects CI env vars too? We currently have the same issues, deleted cypress-cloud and its config files, cleared pipelines cache, no record flag is used anywhere, but still cypress detects cypress-cloud. The only thing that I’ve noticed is a CYPRESS_API_URL env var that is pointing to sorry-cypress. 
Could it be the issue?

Note that we are running cypress 13.10.0

**Comment by jennifer-shehane** [comment]
@Popone55 Yes, I'd recommend removing that env var as well. Anything associated with cypress-cloud.
