### ISSUE TITLE
 Cypress TestRail Simple plugin always return TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by oqasem1** [cypress-io/cypress#29506]
### Current behavior

Can't execute (npx cypress run or open) when using cypress-testrail-simple plugin, 
It always gives an error with the cypress.config.js
even though, it was able to create a new test run, and returned the runId before executing the tests, 
but when trying to execute the cypress run it always gives this error,
all other env. variables are defined as of the documentation:

TESTRAIL_HOST=
TESTRAIL_USERNAME=
; the user password or API key for the user
; API key is preferred
TESTRAIL_PASSWORD=
; Note: the project ID is not very sensitive value
TESTRAIL_PROJECTID=
TESTRAIL_SUITEID=

<img width="926" alt="image" src="https://github.com/cypress-io/cypress/assets/16666334/e7015ba5-7cb1-4f9f-81c8-51e71da88da9">

### Desired behavior

After the execution of testes I should be able to have the results of the execution in order to send them right away to the TestRail test run portal test

### Test code to reproduce

<img width="1392" alt="Screenshot 2024-05-11 at 23 01 40" src="https://github.com/cypress-io/cypress/assets/16666334/7c8748c5-aa42-4dea-9321-01d594897773">

### Cypress Version

13..4.0

### Node version

v16.20.2

### Operating System

macOS 13.6.6

**Comment by Narretz** [comment]
You should open an issue in the plugin's repo. The error is not in cypress code.

Looks like somebody else hit the same problem: https://github.com/bahmutov/cypress-testrail-simple/issues/100
