### ISSUE TITLE
disable mouseover on commands-timeline in sidebar

### ISSUE THREAD

**Issue by camiant** [cypress-io/cypress#29509]
### Current behavior

At the end of test, when you hover on commands as a travel-machine, Livewire components (which are no more available in dom) fire "component missing" errors.

![2024-05-13 14_28_09-cypress-test](https://github.com/cypress-io/cypress/assets/7567420/9babb4fd-2f7b-4733-9a31-c62d251c281b)

### Desired behavior

Would be fine if mouseover on sidebar commands could be disabled in settings.

### Test code to reproduce

...

### Cypress Version

13.9.0

### Node version

20.x

### Operating System

Windows 11 - Chrome v124 as browser

**Comment by camiant** [comment]
just as a workaround, I've added these instructions inside `cypress\support\e2e.js`
```js
beforeEach(() => {
  cy.window().then((win) => {
    win.top.document.querySelector('div.wrap').style.pointerEvents = 'none'
  })
})
```
to disable mouse events in specs-sidebar

**Comment by namuol** [comment]
Try using `numTestsKeptInMemory: 0` to prevent this behavior. More info here: https://github.com/cypress-io/cypress/discussions/9650#discussioncomment-15563102
