### ISSUE TITLE
Overriding Node version with cypress.config.ts has no effect

### ISSUE THREAD

**Issue by krista-prokop** [cypress-io/cypress#29539]
### Current behavior

I couldn't find documentation on how to use the node version configs, so I'm wondering if I'm missing some other element or if this is a defect. The node version & path in config have no effect:
```
// neither of these, alone or combined, has any effect
export default defineConfig({
	resolvedNodeVersion: '20.9.0',  
	resolvedNodePath: NODE_DIR,
}
```

My test output still references version 18:
```
┌────────────────────────────────────────────────────────────────────────────────────────────
  │ Cypress:        13.9.0                                                                         │
  │ Browser:        Electron 118 (headless)                                                        │
  │ Node Version:   v18.20.2 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          7 found (...)                                                     │
  │ Searched:       cypress/test/e2e/**/*.cy.***js,jsx,ts,tsx***                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────
```
 

 
Thanks!

### Desired behavior

use specified node version instead of the bundled version

### Test code to reproduce

```
export default defineConfig({
	resolvedNodeVersion: '20.9.0',  
	resolvedNodePath: NODE_DIR,
}
```

### Cypress Version

13.9.0

### Node version

20.9.0

### Operating System

Windows

**Comment by jennifer-shehane** [comment]
We removed the `nodeVersion` config in v13: https://docs.cypress.io/guides/references/changelog#13-0-0

**Comment by krista-prokop** [comment]
@jennifer-shehane I did see that but assumed `nodeVersion` was different from the configs I'm using - `resolvedNodeVersion` and `resolvedNodePath`. Are you saying those 2 configs are deprecated too? I saw them still being referenced in the repo  :/

Can you share the correct way to specify a node path/version, if I'm not using the correct configs?

**Comment by jennifer-shehane** [comment]
What are you trying to accomplish exactly?

**Comment by MikeMcC399** [comment]
@krista-prokop 

You need to install the version of Node.js that you want to use. Since you are on Windows you may consider installing and using a Node.js manager, such as nvm-windows https://github.com/coreybutler/nvm-windows/releases/tag/1.1.11, which allows you to switch between Node.js versions.

**Comment by MikeMcC399** [comment]
You can get support from the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

**Comment by krista-prokop** [comment]
What I was hoping to do was use the node executable that is bundled with my application repo (legacy architecture/paradigms) rather than the node version installed on my ci runners.

**Comment by MikeMcC399** [comment]
@krista-prokop

What CI system are you using? GitHub Actions or something else?

This is more of a "how-to" question which typically gets discussed in Discord, but we can continue here for your next steps.
