### ISSUE TITLE
validate inputs to "cy" commands better

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2953]
## Cypress 3.1.3 on Mac

I have discovered this bad behavior while renaming `cy.contains(selector, text)` to `cy.get(...)` and leaving two strings there accidentally 

## bug

Try passing invalid arguments to `cy.get`, for example two strings and you will get error like ` TypeError: Cannot read property 'set' of undefined` without any explanation.

Example spec file

```js
it('calls cy get with 2 strings', () => {
  // TypeError: Cannot read property 'set' of undefined
  cy.get('.foo', 'bar')
})
it('calls cy get with string and number', () => {
  // TypeError: Cannot read property 'set' of undefined
  cy.get('.foo', 42)
})
it('calls cy get with string and a function', () => {
  // works (no warnings)
  cy.get('.foo', () => {})
})
it('calls cy get with string and empty object', () => {
  // works
  cy.get('.foo', {})
})
```

Here is screenshot of Cypress 3.1.3 running these tests

![screen shot 2018-12-17 at 10 30 03 am](https://user-images.githubusercontent.com/2212006/50096902-b8708b00-01e6-11e9-976b-f1075461bf69.png)

The first two tests should fail, but keep spinning on `GET` command. They fail with cryptic error message. The first test passes function instead of options object and does not complain, which is also weird. The last test fails correctly.

I have placed this spec into branch `get-args` at https://github.com/cypress-io/cypress-test-tiny/tree/get-args

## What should happen

Each command should validate the inputs at runtime and assert that the arguments are of expected type at runtime. I suggest using `check-more-types` and `lazy-ass` to generate meaningful user-friendly errors if the user passes incorrect arguments to each cy command.

**Comment by jennifer-shehane** [comment]
These last 2 use cases you mention are actually not showing the 'Cannot read property 'set' of undefined` error. It's accurately erroring that it cannot find the element. 

So, the only failures here are these, which are still present in version 3.4.0.

```js
it('calls cy get with 2 strings', () => {
  // TypeError: Cannot read property 'set' of undefined
  cy.get('input', 'bar')
})
it('calls cy get with string and number', () => {
  // TypeError: Cannot read property 'set' of undefined
  cy.get('input', 42)
})
```

Notably, if you have [TypeScript](https://on.cypress.io/typescript-support) set up on your project, you will get warnings for things like this. 

<img width="940" alt="Screen Shot 2019-07-12 at 12 07 03 PM" src="https://user-images.githubusercontent.com/1271364/61104798-98aff580-a49d-11e9-9b94-547a6876e32f.png">
