### ISSUE TITLE
401 - Unauthorized (text/html) Error 

### ISSUE THREAD

**Issue by Nithu2001** [cypress-io/cypress#29545]
### Current behavior

I am getting a 401 - Unauthorized (text/html) error while using Cypress to test an intranet site that uses Windows authentication, I get the same error in the headless mode and I am currently using the electron browser. When I use MS Edge I get an Info bar stating that Edge is being controlled by automated test software (which is Cypress) but there is nothing underneath.
![cypress error](https://github.com/cypress-io/cypress/assets/105480629/16e5c6a3-f5c6-4bfa-91e7-76931fee0771)
![edge error](https://github.com/cypress-io/cypress/assets/105480629/6731cd15-77cb-4cb0-83ee-1de3032ad434)

### Desired behavior

Cypress should run the test and visit the intranet site without giving 401 - Unauthorized (text/html) Error 

### Test code to reproduce
```js
///<reference types="Cypress"/>

describe('Sorting Threshold FLS', () => {
  it('validating the functionality of Sorting',()=>{
    cy.visit('[URL for Intranet site]');
  })
})
```
### Cypress Version

13.9.0

### Node version

10.5.1

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment]
@Nithu2001 We'll need a way to reproduce this to investigate on our side. There's not much I can do in this case.

**Comment by Nithu2001** [comment]
@jennifer-shehane, "Thank you for your response. Running Cypress to test something on your intranet may possibly replicate my issue."
We are switched from basic authentication to using Secure Kerberos authentication. While we are able to connect from basic authentication, now we are getting this error by using Kerberos authentication.

**Comment by Nithu2001** [comment]
@jennifer-shehane  could you please help us to figure out this issues.
