### ISSUE TITLE
Browser will freeze when sync request is intercepted (Tested in Cypress 10.11.0)

### ISSUE THREAD

**Issue by kalousmichal** [cypress-io/cypress#29566]
### Current behavior

The whole browser will freeze if a tested page uses a synchronous HTTP request and Cypress test intercepts this request.
Even disabling interceptions by `cy.server({ enable: false });` won't resolve the issue
Steps are:

1. Set test with `cy.intercept('https://httpbin.org/post', (req) => {})`
2. Visit the page and trigger the sync request
3. Browser will freeze

Removing `cy.intercept` from the test will fix the issue.

### Desired behavior

The browser should not freeze.

### Test code to reproduce

Cypress project with a simple reproducible example: 
[cypress-bug.zip](https://github.com/cypress-io/cypress/files/15430409/cypress-bug.zip)

```js
describe('empty spec', () => {
  it('passes', () => {
    cy.server({ enable: false });
    cy.intercept('https://httpbin.org/post', (req) => {})
    cy.visit('cypress/fixtures/syncRequest.html')
    cy.log('Browser will freeze in 5s after sending sync request')
    cy.wait(5000);
    cy.get('#sync-request-button').click();
  })
})
```

```html
<!DOCTYPE html>
<html>
<head>
    <title>Sync Request Repro</title>
</head>
<body>
<div>
    <button id="sync-request-button">Test Sync Request</button>
    <div id="counter"></div>
</div>
<script>
    const button = document.querySelector('#sync-request-button');
    button.addEventListener('click', () => {
        let xhr = new window.XMLHttpRequest();
        xhr.open('POST', 'https://httpbin.org/post', false);
        xhr.onload = () => console.log(xhr.status);
        xhr.send();
    });
    let count = 0;
    setInterval(() => {
        document.querySelector('#counter').innerHTML = `${count}`
        count++
    }, 100);
</script>
</body>
</html>
```

### Cypress Version

v10.11.0

### Node version

v16.16.0

### Operating System

macOS 14.5 (23F79)

**Comment by jennifer-shehane** [comment]
@kalousmichal Have you tried a more recent version of Cypress? This may have already been fixed. We'll only investigate issues proven in our more current versions.
