### ISSUE TITLE
Email address used when logging in with Github

### ISSUE THREAD

**Issue by suuf** [cypress-io/cypress#29595]
### Current behavior

When logging in to Cypress Cloud through my Github account, my email privacy settings are not respected (i.e. Cypress is using my primary email address instead of using {username}@users.noreply.github.com by default). Also, there is no option to change my email address when I go to Manage profile (there is an empty dropdown list).

Sorry for skipping out information below, it doesn't seem applicable as this is about Cypress Cloud.

### Test code to reproduce

-

### Cypress Version

-

### Node version

-

### Operating System

-

**Comment by jennifer-shehane** [comment]
@suuf Thanks for sharing your feedback. I've forwarded this request to our Cloud team. I'll close this issue for now in our repo since it's used for handling issues related to the Cypress App.
