### ISSUE TITLE
Chaining .selectFile from document throws an error

### ISSUE THREAD

**Issue by georgekaran** [cypress-io/cypress#29593]
### Current behavior

When attempting to use the following commad:
```ts
cy.document().selectFile('example.json', {action: 'drag-drop'});
```

I get the following error:
```bash
CypressError: `cy.selectFile()` failed because it requires a DOM element.

The subject received was:

  > `<document>`

The previous command that ran was:

  > `cy.document()`
```

### Desired behavior

It should allow drop files in the document as [described in the docs](https://docs.cypress.io/api/commands/selectfile#Usage)

### Test code to reproduce

I made a repo with the issue: https://github.com/georgekaran/cypress-test-tiny/tree/document-select-file

### Cypress Version

v12.17.4

### Node version

v20.10.0

### Operating System

macOS 14.5

**Comment by jennifer-shehane** [comment]
Yah I'm unsure if the documentation is incorrect or if we changed the behavior unintenionally somewhere to make this fail. It makes sense to me that you'd target a document to drag and drop though.
