### ISSUE TITLE
`сypress open` failed to start on Mac M1 Sonoma 14.5 (23F79)

### ISSUE THREAD

**Issue by kurashz** [cypress-io/cypress#29604]
### Current behavior

_I decided to move my problem into a separate task._  

Can't start cypress using command: `npx cypress open`. When the application starts, it loads the processor up to 100%, which leads to its freezing.

The first launch: https://drive.google.com/file/d/1cmcXJx5DqwYBNSn9M8eiJIX4DRugUOj4/view?usp=sharing

Debug launch: https://drive.google.com/file/d/1YZsQV2t5VBJkInCtAoUkE6XBF8RM9Jlk/view?usp=sharing

Full debug: [debug.js.zip](https://github.com/user-attachments/files/15534857/debug.js.zip)

**Clearing cache, changing the node version, updating macOS — none of these helped.** The installation was carried out through:
https://docs.cypress.io/guides/getting-started/installing-cypress

### Test code to reproduce

https://github.com/cypress-io/cypress-example-kitchensink

### Cypress Version

13.10.0

### Node version

20.14.0

### Operating System

14.5

### Debug Logs

```shell
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200 2109.904 ms - -
GET /chrome-variations/seed?osname=mac&channel=stable&milestone=125 304 2093.877 ms - -
The Test Runner unexpectedly exited via a exit event with signal SIGKILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-arm64 (23.5.0)
Cypress Version: 13.6.4
```

### Other

[debug.js.zip](https://github.com/user-attachments/files/15534857/debug.js.zip)
MacOs Report
https://drive.google.com/file/d/1mr5q3b_0C3_0qS_paaqbMNUhf8ydYO2F/view?usp=sharing

**Comment by jennifer-shehane** [comment]
I don't see any clear reason for this from the logs. I do see the log below at some point. With a SIGKILL

```
cypress:server:browsers:cri-client registering CDP on event { eventName: 'Target.targetCrashed' } +0ms
```

**Comment by kurashz** [comment]
> I don't see any clear reason for this from the logs. I do see the log below at some point. With a SIGKILL
> 
> ```
> cypress:server:browsers:cri-client registering CDP on event { eventName: 'Target.targetCrashed' } +0ms
> ```

What additional information can I provide?

**Comment by kurashz** [comment]
I completely reinstalled the system, having previously cleaned the disk.
I have installed node v20.14.0 and visual code. 

At the moment, the problem is not repeated. I will test it during the next day. I'll report the results..
