### ISSUE TITLE
Remove support for Node.js 16 and 21

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29601]
### What would you like?

For the next major version of Cypress, support for the following Node.js versions should be removed:

- Node.js `16.x` reached [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on Sep 11, 2023
- Node.js `21.x` reached [end-of-life](https://github.com/nodejs/Release/blob/main/README.md) on Jun 1, 2024

This should be reflected in an update to

https://github.com/cypress-io/cypress/blob/e6b422cd25e3efffcb22a9d68c38f13f771f68b8/cli/package.json#L125-L127

Changing to the following will enable the setting to stay in place until the planned end-of-life of Node.js `18` (Apr 30, 2025):

```json
  "engines": {
    "node": "^18.0.0 || ^20.0.0 || >=22.0.0"
  },
```

### Why is this needed?

- Cypress cannot effectively continue support for versions of Node.js which have reached end-of-life status.
- Users should be assisted in avoiding unsupported Node.js versions by excluding them in the `engines` section of [cli/package.json](https://github.com/cypress-io/cypress/blob/develop/cli/package.json). Package managers then either warn or prevent installation of Cypress in an unsupported Node.js environment, depending on settings.

### Other

The [Cypress 13.0.0 changelog](https://docs.cypress.io/guides/references/changelog#13-0-0) has already deprecated Node.js `16`

> Node 14 support has been removed and Node 16 support has been deprecated. Node 16 may continue to work with Cypress v13, but will not be supported moving forward to closer coincide with [Node 16's end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) schedule. It is recommended that users update to at least Node 18.

**Comment by MikeMcC399** [comment]
GitHub Actions has announced removal of Node.js 16

https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/ 

![image](https://github.com/user-attachments/assets/18e01feb-c345-4a3e-a2bc-86dfefd6a855)

**Comment by jennifer-shehane** [comment]
This will be released in Cypress 14.
