### ISSUE TITLE
Cypress crashes with "Warning: We failed to record the video."

### ISSUE THREAD

**Issue by gkrishna08** [cypress-io/cypress#29609]
### Test code to reproduce

I can't provide the test code, since it contains company data. However, I can tell you is these issue is seen in first 5-10 mins once we start our test pipelines.
![Screenshot 2024-06-04 112934](https://github.com/cypress-io/cypress/assets/151394357/d75b66de-1aa9-458c-b9ca-a6a1dea0b52e)
![image](https://github.com/cypress-io/cypress/assets/151394357/8b3c4f80-6cb4-4f84-a1aa-36c605b37e00)

As soon as we trigger our test pipelines in Jenkins, Cypress is crashing with error **Warning: We failed to record the video**.

Chrome Browser - 125

**Cypress Mode:** 
cypress run 

### Cypress Version

12.11.0

### Node version

18.20.3

### Operating System

Ubuntu/Linux

**Comment by jennifer-shehane** [comment]
@gkrishna08 Please update to the latest version of Cypress and try again. We fixed some video errors in newer versions.
