### ISSUE TITLE
cy.screenshot() print, window displayed

### ISSUE THREAD

**Issue by dansantty** [cypress-io/cypress#2962]
### Current behavior: 
Screenshot prints a complete web page when using `cy.screenshot()`

### Desired behavior: 
I wanted to use `cy.screenshot()` to have the same behavior as using the `PrtScr` key on the keyboard, which prints only the part of the window that is displayed

**Comment by dansantty** [comment]
Hi, Jennifer
In truth I need to capture only the page screen that is being viewed and not the full page of the site where I navigate.
PrtScr was an example I used, because when it is triggered, it takes a photo only of the screen that is shown.

Thanks for the reply, I'm waiting for you to return.

**Comment by brian-mann** [comment]
@dansantty 	have you read our documentation? This is part of the options already built into `cy.screenshot()`.

https://docs.cypress.io/api/commands/screenshot.html#Arguments
