### ISSUE TITLE
Problem during Cypress instalatión

### ISSUE THREAD

**Issue by Draconary** [cypress-io/cypress#29620]
### Current behavior

Hello. When I try installing Cypress it return an error. Thanks!!
![image](https://github.com/cypress-io/cypress/assets/61140976/11874713-2028-400e-b6e3-fd82df0c21f4)

### Cypress Version

v.13.10.0

### Node version

v20.14.0

### Package Manager

npm

### Package Manager Version

v10.7.0

### Operating system

Windows

### Operating System Version

Windows 10 v.22H2

**Comment by MikeMcC399** [comment]
@Draconary 

Your error
> Error: unable to get local issuer certificate

is also mentioned in the following issue with some comments which might be helpful to you:

- https://github.com/cypress-io/cypress/issues/25892

**Comment by Gitnikkx** [comment]
Hi, had the same issue but for `v13.11.0` you need to delete the **node modules** & **package-lock.json** and try again. This worked for me !

**Comment by Draconary** [comment]
> Hi, had the same issue but for `v13.11.0` you need to delete the **node modules** & **package-lock.json** and try again. This worked for me !

Thanks, Gitnikkx. I tried deleting node modules & package-lock.json, but it deliver an error too:
![image](https://github.com/cypress-io/cypress/assets/61140976/38f09740-1759-4572-bb63-f33e82e1cbff)
![image](https://github.com/cypress-io/cypress/assets/61140976/f43fc5eb-4b08-428f-8423-2de443742c85)

**Comment by MikeMcC399** [comment]
@Draconary 

- Are you on a corporate network?
- Did you read the comments in https://github.com/cypress-io/cypress/issues/25892?
- What is the result of trying to download the Cypress binary in a web browser directly from https://download.cypress.io?
- Which type of terminal window are you using: PowerShell, cmd or Git Bash? (needed if I give you debug instructions)

**Comment by Draconary** [comment]
@MikeMcC399 
- Are you on a corporate network?
Usually not. The error appears when I am connected to the corporate network and when I am not connected too
- Did you read the comments in https://github.com/cypress-io/cypress/issues/25892?
Yes. I am waiting for the corporate admins to give me adming pass for editing environment variables to use CYPRESS_INSTALL_VARIABLE environment variable
- What is the result of trying to download the Cypress binary in a web browser directly from https://download.cypress.io/?
I am able to download zip from here.
- Which type of terminal window are you using: PowerShell, cmd or Git Bash? (needed if I give you debug instructions)
PowerShell

**Comment by MikeMcC399** [comment]
@Draconary 

> What is the result of trying to download the Cypress binary in a web browser directly from https://download.cypress.io/?
I am able to download zip from here.

That is a good sign!

You could try the following in PowerShell:

```shell
npm install cypress@latest --save-dev --ignore-scripts
npx cypress cache clear
$Env:DEBUG='cypress:*'
npx cypress install
npx cypress verify
```

I expect that it will also give an error in the binary install phase. If so, it may give you a little more debug information.

There is also a small chance that it will work without error.

**Comment by Draconary** [comment]
@MikeMcC399 
Thank for the steps

During "npx cypress install" phase it gave that error.
![image](https://github.com/cypress-io/cypress/assets/61140976/80e8b2d8-d8a0-4035-8528-71f1678898de)

**Comment by MikeMcC399** [comment]
@Draconary 

Thank you for running the debug steps. This means you now have the Cypress npm module installed and you are missing the Cypress binary.

To work around the download / unzip issue, you can download `cypress.zip` manually from https://download.cypress.io. (I understood that you were able to do this successfully already. You might need to repeat this to get the latest version.)

On Windows you need to create the version-specific target cache folder. For instance if you download the current version `13.11.0` the folder would be:

`%LOCALAPPDATA%\Cypress\Cache\13.11.0`

You can then unzip the downloaded `cypress.zip` into this folder. You should then have a folder

`%LOCALAPPDATA%\Cypress\Cache\13.11.0\Cypress`

which contains the unzipped Cypress binary.

You can check this is working with

```shell
npx cypress verify
npx cypress info
```

## Certificate error

> Error: unable to get local issuer certificate

You may be able to find a solution by Googling this error message. There are many articles about this subject.

**Comment by Draconary** [comment]
Thanks @MikeMcC399 !! It works

![image](https://github.com/cypress-io/cypress/assets/61140976/d4be0de5-c5ac-4178-b532-e6c4adc8be6b)

**Comment by MikeMcC399** [comment]
@Draconary 

Congratulations!

You should be able to close this issue now if you click on the button below ⬇️
