### ISSUE TITLE
Issue during installing forked Cypress

### ISSUE THREAD

**Issue by thevladisss** [cypress-io/cypress#29623]
### Current behavior

While installing Cypress following guide in CONTRIBUTING.md I am getting following error:

```
Internal Error: Duplicate workspace name cypress: /Users/vladyslavnosal/WebstormProjects/contributions/cypress/cli conflicts with /Users/vladyslavnosal/WebstormProjects/contributions/cypress
    at ze.addWorkspace (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:439:1952)
    at async ze.setupWorkspaces (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:439:1637)
    at async ze.find (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:436:1560)
    at async gm.execute (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:499:12090)
    at async gm.validateAndExecute (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:345:673)
    at async Bs.run (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:359:2087)
    at async Bs.runExit (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:359:2271)
    at async i (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:446:12696)
    at async t (/Users/vladyslavnosal/.cache/node/corepack/yarn/3.2.3/yarn.js:446:10914)
```

### Cypress Version

13.11.0

### Node version

21.7.3

### Package Manager

yarn

### Package Manager Version

1.22.22

### Operating system

Mac

### Operating System Version

14.4.1

**Comment by MikeMcC399** [comment]
@thevladisss 

Can you clarify if you intend to contribute to the development of Cypress or if you want to install Cypress for your own use only?

It appears in any case that you have had Node.js' experimental `corepack` enabled at some stage and that you have had an outdated version of Yarn Modern (3.x) installed.

Cypress uses Yarn 1.x Classic and does not use `corepack`

**Comment by thevladisss** [comment]
> @thevladisss 
> 
> 
> 
> Can you clarify if you intend to contribute to the development of Cypress or if you want to install Cypress for your own use only?
> 
> 
> 
> It appears in any case that you have had Node.js' experimental `corepack` enabled at some stage and that you have had an outdated version of Yarn Modern (3.x) installed.
> 
> 
> 
> Cypress uses Yarn 1.x Classic and does not use `corepack`

Yes , I am installing to contribute to the project. 

I will try , however, to install not via corepack, hope this helps

**Comment by MikeMcC399** [comment]
@thevladisss 

OK. Good luck! This issue list is really intended just for bugs.

If you need setup assistance you can also use Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

and if you are not already present in the Cypress Discord community it will be of mutual great value for you to join! 🙂

**Comment by thevladisss** [comment]
> @thevladisss 
> 
> 
> 
> OK. Good luck! This issue list is really intended just for bugs.
> 
> 
> 
> If you need setup assistance you can also use Discord
> 
> 
> 
> [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)
> 
> 
> 
> and if you are not already present in the Cypress Discord community it will be of mutual great value for you to join! 🙂 

 Thank you so much!

**Comment by Gitnikkx** [comment]
Having issues installing v13.11, taking forever to install the package.

**Comment by MikeMcC399** [comment]
@thevladisss

I see you continued the discussion into https://discord.com/channels/755913899261296641/1248479156115734608 and it sounds like you have resolved your installation issue.

Please close this issue if that is true. You should see a button below ⬇️ to do this.
