### ISSUE TITLE
Cypress.moment.locale() not setting locale in a test

### ISSUE THREAD

**Issue by nimish-gupta** [cypress-io/cypress#2963]
### Current behaviour:

Currently, we can not set locale in Cypress with the context of file using `Cypress.moment.locale('fr')`

### Desired behaviour:

It should change the locale against `Cypress.moment` throughout the test

### Steps to reproduce: (app code and test code)

Create new spec file and paste the following code

```js
describe('test', () => {
  it('compare', () => {
    Cypress.moment.locale('fr');
    console.log('cypress', Cypress.moment().format('MMMM'));
  })
})
```

### Versions

os -> macos mojave 10.14
cypress -> ^3.1.0

**Comment by nimish-gupta** [comment]
Meanwhile if you use this code it will work
        
        `describe('test', () => {
            it('compare', () => {
              moment.locale('fr');
              console.log('moment', .moment().format('MMMM'));
           })
       })`

I have installed the moment library separately for working of this

**Comment by jennifer-shehane** [comment]
`moment.locale` requires an import in addition to the standard `moment` import and has not been included in Cypress. Importing `moment-with-locales.min.js` would add 81.9 KB

**Comment by Songyu-Wang** [comment]
@jennifer-shehane is there a reason that you guys intentionally choose to not add that 81.9KB?

**Comment by mkallango** [comment]
Would be good if we could set the locale to moment on Cypress!

**Comment by rubiii** [comment]
Same problem here. We would really like to use another locale because to properly translate month names, because the vast majority of our users don't access the english version of our app.

**Comment by jennifer-shehane** [comment]
No reason not to add this, just stating the facts of adding it. We're open to PRs for adding features like this.

**Comment by jennifer-shehane** [comment]
`Cypress.moment()` has been deprecated in Cypress 6.1.0. No new work will be done on this feature. We suggest you consider migrating to a different datetime formatter. Here is an example of testing using dayjs: https://github.com/cypress-io/cypress-example-recipes/tree/f4441ecf2f689f823b1f78b2b884f4164eb0dbe9/examples/blogs__dayjs
