### ISSUE TITLE
Svelte 5 component testing

### ISSUE THREAD

**Issue by tobiasBora** [cypress-io/cypress#29641]
### What would you like?

For now it is not possible to do component testing with svelte 5:

![image](https://github.com/cypress-io/cypress/assets/2164118/4ed6812e-58b7-4000-a001-492ca61fb218)

### Why is this needed?

Because svelte 5 is the new version of svelte.

**Comment by jennifer-shehane** [comment]
Thanks for opening. We've got this on our radar. Svelt 5 is currently a release candidate with no confirmed release date: https://svelte.dev/blog/svelte-5-release-candidate

**Comment by tobiasBora** [comment]
Yes, but it seems to reach some sort of stability. But right now is it just "not supported at all", or "at our own risks"? Because I get an error like "your tests are loading", but I don't know if it's me doing something stupid or if it's due to svelte5 being truly not supported.

**Comment by jennifer-shehane** [comment]
It's not supported in Cypress currently.

**Comment by AtofStryker** [comment]
svelte 5 was released 10 days ago on https://www.npmjs.com/package/svelte/v/5.0.0. We will spike into this to see how much work it takes to support. If the work is minimal, we can likely include it in Cypress 14 or a release soon there after as a feature

**Comment by claridgicus** [comment]
Looking forward to this after updating all my components and running my tests only to find out it doesn't work anymore 🤣
