### ISSUE TITLE
patch-package warning for snap-shot-it@7.9.10

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29647]
### Current behavior

Building Cypress from source with Yarn results in a warning from patch-package

> Warning: patch-package detected a patch file version mismatch
>  Patch file created for
>
>    snap-shot-it@7.9.3
>
>  applied to
>
>    snap-shot-it@7.9.10

### Desired behavior

There should be no patch-package warning when Cypress is built from source.

### Test code to reproduce

```shell
git clone https://github.com/cypress-io/cypress
cd cypress
npm install yarn@latest -g
yarn
```

### Cypress Version

`13.11.0` at https://github.com/cypress-io/cypress/commit/3f4ab2959996ffd01117fa9c103d85f5209cf1af

### Node version

`v18.17.1`

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

```text
snap-shot-it@7.9.3 ✔

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    snap-shot-it@7.9.3

  applied to

    snap-shot-it@7.9.10

  At path

    node_modules/snap-shot-it

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package snap-shot-it

  to update the version in the patch file name and make this warning go away.

---
patch-package finished with 1 warning(s).
```

### Other

- PR https://github.com/cypress-io/cypress/pull/29542 bumped `snap-shot-it` to `7.9.10`
https://github.com/cypress-io/cypress/blob/3f4ab2959996ffd01117fa9c103d85f5209cf1af/package.json#L199

- https://github.com/cypress-io/cypress/blob/develop/patches/snap-shot-it%2B7.9.3.dev.patch was not updated

- According to https://github.com/bahmutov/snap-shot-it/compare/v7.9.3...v7.9.10 there have been no changes made to `snap-shot-it/src/index.js` so it should be safe to update the patch to the latest version.

**Comment by jennifer-shehane** [comment]
Yah just need to update the patch-package to the correct version. I haven't actually had to do that before, but I imagine it's simple.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

I took a look and it seems that it just needs the file https://github.com/cypress-io/cypress/blob/develop/patches/snap-shot-it%2B7.9.3.dev.patch renaming to the new version since the contents themselves are not version specific.

I'll submit a PR for that.

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/cypress/pull/29655 submitted to resolve this issue
