### ISSUE TITLE
Cypress does not fail when cy.route throws new error

### ISSUE THREAD

**Issue by nitzansan** [cypress-io/cypress#2964]
### Current behavior:

Sometimes we want to validate that a certain API request has not been fired, for this scenarios we're adding to the relevant `cy.route` obj:

```
onRequest: () => throw new Error('This BE call should have not been triggered!')
```

When we first introduced it (don't remember which cypress version and chrome version), it failed the test if requested as desired.

However, testing it now with cypress 3.1.0 and chrome 71 does not.

### Desired behavior:

Throwing an error in `cy.route` should fail the cypress test

### Steps to reproduce: (app code and test code)

Just add any the above `onRequest` to a `cy.route` and see in the console that the error is indeed thrown but that the cypress test doesn't fail.

### Versions
Cypress 3.1.0, Chrome 71

**Comment by nitzansan** [comment]
Any updates on this? I see that it still occurs on 3.1.4

**Comment by jennifer-shehane** [comment]
I'm able to reproduce this behavior. When adding a `throw` into `onRequest`, the route never resolves. 

**Example test code**
```js
it('throw onRequest', () => {
  cy.visit('https://example.cypress.io/commands/network-requests')
  cy.server()
  cy.route({
    method: 'GET',
    url: 'comments/*',
    onRequest: () => {
      throw new Error('This BE call should have not been triggered!')
    },
  }).as('getComment')
})
```

<img width="453" alt="screen shot 2019-02-21 at 10 31 35 pm" src="https://user-images.githubusercontent.com/1271364/53183139-2b541300-3629-11e9-8814-6927d4d38636.png">

`onRequest` function is called here in code:

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/xhr.coffee#L189

**Comment by Lakitna** [comment]
I'm running into this issue too when trying to make sure that some security-sensitive data is never passed around in plaintext.

I've tested this with `onResponse` too, and it has the same issue.

Are there any workarounds for grabbing the request of an XHR?

**Comment by malixsys** [comment]
BTW, for us the desired result is for the test NOT to fail when throwing in `onResponse`, as we are testing that our app handles `TypeError`'s graciously...

**Comment by jennifer-shehane** [comment]
Closing as cy.route() is now deprecated. Please update your code to use cy.intercept() and open a new issue for any issues found using the new API.
