### ISSUE TITLE
Cypress run slow on Cypress Cloud with Bitbucket CI

### ISSUE THREAD

**Issue by lthfndra** [cypress-io/cypress#29645]
### Current behavior

When the test run on a local machine : 10 mins
When the test run on Bitbucket pipeline with Cypress Cloud : Test does not complete running and job fails after 40 mins

Browser: Electron 118 (headless)

![Screenshot 2024-06-11 at 18 39 06](https://github.com/cypress-io/cypress/assets/90565071/c02a15ed-9a81-47b3-857f-3de420caa210)
![Screenshot 2024-06-11 at 18 39 19](https://github.com/cypress-io/cypress/assets/90565071/3f479f96-8d89-4303-a8be-c73a87875f32)

### Desired behavior

I expect the test to finish running within the 10 mins timeframe

### Test code to reproduce

Not relevant in this case

### Cypress Version

13.11.0

### Node version

v20.9.0

### Operating System

Linux Debian

**Comment by lthfndra** [comment]
when it run on local machine directly to cypress cloud

![Screenshot 2024-06-11 at 18 23 50](https://github.com/cypress-io/cypress/assets/90565071/eac68058-51cf-4764-b5cd-893a4498269b)

when it run on CI with cypress cloud

![Screenshot 2024-06-11 at 18 23 58](https://github.com/cypress-io/cypress/assets/90565071/55af47c3-1c1a-4c8e-a0b4-4cd71dc49303)

**Comment by lthfndra** [comment]
when it run on local machine directly to cypress cloud

![Screenshot 2024-06-11 at 18 23 50](https://github.com/cypress-io/cypress/assets/90565071/9a3f058d-0348-4790-8007-6c22cfe0a7f5)


when it run on CI with cypress cloud

![Uploading Screenshot 2024-06-11 at 18.23.58.jpg…]()

**Comment by jennifer-shehane** [comment]
@lthfndra What are the resources on the Bitbucket CI machine running tests? This can affect runtimes if it's on a resource contrained machine. See our general recommendations: https://docs.cypress.io/guides/getting-started/installing-cypress#CPU

**Comment by lthfndra** [comment]
it run on Debian. Do you mean this is caused by an inadequate Bitbucket CI machine ?

details of the machine:
![Screenshot 2024-06-12 at 14 39 55](https://github.com/cypress-io/cypress/assets/90565071/4a1922b8-cc10-4304-80aa-bf76b7e514cc)
![Screenshot 2024-06-12 at 14 39 30](https://github.com/cypress-io/cypress/assets/90565071/f07cf377-38e5-40cc-b778-86076323a29b)

**Comment by jennifer-shehane** [comment]
It can be, it could also be something else. Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by lthfndra** [comment]
it has 12k lines, I cannot print all of the logs here
