### ISSUE TITLE
Click not firing in native Promise

### ISSUE THREAD

**Issue by aloifolia** [cypress-io/cypress#2965]
### Current behavior:

If I have a selector with a click method call `foobar.click()` I usually see an according `CLICK` entry in the event logger column of Cypress.

However, if the call happens to be inside a Promise the call does not trigger any event. For something like 

```js
Promise.resolve(() => {
  foobar.click().next();
}
```
 this means that all calls which come after `click()` are ignored, as well.

### Desired behavior:

`click()` should fire regardless of whether it resides inside a Promise or not.

### Versions

Cypress package version: 3.1.3
Cypress binary version: 3.1.3
MacOS 10.14
Chrome 71.0.3578.98

**Comment by brian-mann** [comment]
Passing a function to `Promise.resolve` does not invoke the function.

You want this if you're using bluebird: `Promise.try(() => { ...})` or you want...

`Promise.resolve().then(() => { ... })

**Comment by aloifolia** [comment]
You're right. I just corrected my mistake and now Cypress' promise detection strikes:

<img width="403" alt="screenshot 2018-12-19 at 09 34 01" src="https://user-images.githubusercontent.com/1295054/50208503-9fe0ac00-0371-11e9-8bf7-3b6e2c735c4c.png">

Is there any way to either suppress this error detection or to use some different kind of promise which is more compatible with Cypress? As mentionend in [another issue](https://github.com/cypress-io/cypress-example-recipes/issues/213) I do not see any way around using something promise-like for my specific use case.

**Comment by jennifer-shehane** [comment]
@aloifolia Could you detail more clearly the situation you are trying to test and the test code you have already tried?

**Comment by aloifolia** [comment]
Hey @jennifer-shehane, I just updated my last post. I think the issue is solved now.

**Comment by brian-mann** [comment]
@aloifolia 	if you can articulate your use case we could better help you. There is almost always a better approach in Cypress-land which does not require the use of Native Promises to interop with commands. Having more use cases would help us explain / express this better or consider changes to the API to accommodate it.

**Comment by aloifolia** [comment]
I use promises for a workaround that I mention here: https://github.com/cypress-io/cypress-example-recipes/issues/213 - my answers explain how to use a web server for testing scenarios with multiple Cypress instances (in order to implement multi-user tests). The tests use communication via websocket connections to this server and Promises in order to coordinate their actions. However, you do not actually need Native Promises. It is also possible to use the mechanism offered by Cypress to achieve the same effect.
