### ISSUE TITLE
Do not abort XHR's on unload

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2968]
### Current behavior:

Whenever Cypress encounters the page unloading, it will automatically call `xhr#abort` on all open XHR's. This is unnecessary as the browser will automatically abort it under the hood. 

Aborting it manually is not only incorrect, but this will trigger the native `abort()` handlers which can cause errors in the client application.

### Desired behavior:

Allow the native browser behavior to propagate and simply update the UI state to match what would be seen by the Network tab in dev tools.

**Comment by arpowers** [comment]
related to  #2374 ?

**Comment by jennifer-shehane** [comment]
@arpowers I can't be sure this is related to that issue since we were never able to reproduce #2374, but you're welcome to pull down the PR and see if the related issue is fixed. PR: https://github.com/cypress-io/cypress/pull/2969

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by janhjordie** [comment]
Hey @brian-mann 
I still have same issue in Electron. Also with the new 3.1.4.
And it both visual and headless Electron. It works just perfect in Chrome and Canary. 
I'm running MacOS.

I reported this issue ealier https://github.com/cypress-io/cypress/issues/1652#issuecomment-439225680

In my case is a bunch of SignalR request that runs in the application, and not any I actually use. 
One of the SignalR request gets aborted and then stops the whole test

Please advise !

**Comment by sverrelorenzen** [comment]
Hi,

I have the same issue with Electron as @janhjordie.

Regards

**Comment by jennifer-shehane** [comment]
Hey @janhjordie and @sverrelorenzen, could you [open a new issue](https://github.com/cypress-io/cypress/issues/new?template=bug_report.md) detailing a reproducible example of your issue (app code + test code). Thank you!

**Comment by 13322211021** [comment]
![image](https://user-images.githubusercontent.com/55481825/67933551-f90ba400-fc00-11e9-837b-d401660309e1.png)
Got the same issue with Electron as @janhjordie.
Did you get a workaround?@janhjordie, @sverrelorenzen
I use cypress 3.4.1.

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
