### ISSUE TITLE
envVar env not being overridden by exported envVar

### ISSUE THREAD

**Issue by gilzow** [cypress-io/cypress#29682]
### Current behavior

If i set up an environment variable `env` in my config file, and then export `CYPRESS_env` in my terminal before opening/running Cypress, the value of `env` during testing remains the value set in the config file and is not overriden by the value set in the exported environment variable. 

### Desired behavior

The exported environment variable should override an environment variable with the same name set in `cypress.env.json` and the configuration file. 

### Test code to reproduce

Repo to reproduce: https://github.com/gilzow/cypress-test-tiny 

in my shell before starting cypress:
```shell
❯ printenv | grep CYPRESS
CYPRESS_env=development
CYPRESS_barfoo=can u c me?
```

In my cypress.config.js file:
```js
    env: {
      barfoo: "from config",
      env: "local",
    },
```
in my test file i log `console.log(Cypress.env('<env-name>'))`. Output in console:
```
Env is local
Barfoo is can u c me?
```

If i change the name from `env` to `environment` ( exported `CYPRESS_environment`) then the results are as I would expect them to be.

### Cypress Version

13.11.0

### Node version

18.17.1

### Operating System

macOS 14.4.1

### Other

[The docs mention](https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_) that `CYPRESS_INTERNAL_ENV` is a reserved key, but there's nothing in the docs I've seen so far to indicate that `CYPRESS_ENV` is also reserved. 

edit: originally stated cypress.config.js  contained `env:environment` but that was incorrect. it had `env:env`.

**Comment by gilzow** [comment]
Github wouldnt let me include the log output as it put the body length beyond 65K characters. 

Debug log output: https://gist.github.com/gilzow/28f8cf67e8596d558fb3413df3336574

**Comment by jennifer-shehane** [comment]
CYPRESS_env accepts an object as its argument, to override the entire env object. If you set it to a string, it will have no effect on the env from the config. 

```
CYPRESS_env="{barfoo: 'from cli',environment: 'cli'}"
```

or override each value individually

```
CYPRESS_barfoo=cli
```

**Comment by gilzow** [comment]
AH, so this is a _documentation_ issue! I'll create an issue over there for it then.
