### ISSUE TITLE
Search by test filename

### ISSUE THREAD

**Issue by TravisL12** [cypress-io/cypress#29694]
### What would you like?

I have a test called `my-test-file.spec.ts`. I want to see how it has been performing across every run/env. I want to be able to do a search for this file and then see the results.

### Why is this needed?

This would make it immensely easy for me to keep an eye on a specific test file instead of having to dig through every "run" for a specific test file.

**Comment by jennifer-shehane** [comment]
@TravisL12 Thank you for the feedback! I've forwarded this feedback to our Cloud team for consideration. I'll close this issue here as this is used for tracking issues on the Cypress App side.
