### ISSUE TITLE
Ability to capture video without test runner sidebar (command log)

### ISSUE THREAD

**Issue by drFabio** [cypress-io/cypress#2970]
### Current behavior:
Currently the video recordings take the side bar, it is already possible to do screenshots without a sidebar since 3.0.0. I would propose allowing the same for video

### Desired behavior:
Have an option to capture the video without the sidebar to use the automated tests to create tutorials and guides easily that would be always up to date with the latest UI.

**Comment by MCTaylor17** [comment]
Funny, I just wrote an article about it: https://www.linkedin.com/pulse/creating-hyper-realistic-ux-simulations-using-cypressio-taylor/

I didn't actually see this issue before writing that so it's nice to see I'm not alone in my thinking.  I did come across issue #181 where Brian suggested:

> If we did this for video it would kind of take away the entire point of knowing why your tests failed.

From a test automation perspective, I fully agree.  Those videos are currently designed for investigating why your passing development build failed in production.  

With that said, I think using Cypress to generate tutorials and other useful artifacts is a very compelling use case.  Despite some glaring flaws easily fixed with with time and coffee, I think my first attempt at creating a "UX simulations" worked out quite well:

[![Cypress.io Generated User Simulation](https://img.youtube.com/vi/k0aXge-Xe2I/0.jpg)](https://www.youtube.com/watch?v=k0aXge-Xe2I)

In my ideal world, the commands for scripting tests and simulations would be the same, with environment variables or config files controlling the speed of those commands.

**Comment by eiswind** [comment]
I see this the same way. Having an option to record only the app, would give us the possibility to automate ui demos, screencasts, tutorials etc. This would be really cool stuff.

**Comment by Tenmak** [comment]
Hello, I've been inspiring myself from this comment https://github.com/cypress-io/cypress/issues/181#issuecomment-350117395 and came up with a simple workaround : 

My environment (I haven't tested for other versions) :
**Cypress: 3.6.1
Electron 73**

```
Cypress.Commands.add('clearViewport', () => {
  // Collapse Cypress commands panel
  const runnerContainer = window.parent.document.getElementsByClassName('runner container')[0];
  runnerContainer.setAttribute('style', 'left: 0;');
  // Resize iframe container
  const sizeContainer = window.parent.document.getElementsByClassName('size-container')[0];
  sizeContainer.setAttribute('style', '');
});
```

First part collapses the Cypress command panel, and the second one cleans up the styles set in the iframe container to make it fullscreen inside the window.

> With that said, I think using Cypress to generate tutorials and other useful artifacts is a very compelling use case. Despite some glaring flaws easily fixed with with time and coffee, I think my first attempt at creating a "UX simulations" worked out quite well:

I'm actually using this for this exact purpose. I'm for now using env variables to show or collapse the viewport accordingly.

**Comment by MCTaylor17** [comment]
@Tenmak you are an internet god!!  I never even considered accessing the parent window.  I've been looking for a reason to revisit this.  I'll have to dust off the old prototype and put it to productive use :)

**Comment by jennifer-shehane** [comment]
So, the above workaround https://github.com/cypress-io/cypress/issues/2970#issuecomment-589082328 does not work in the Cypress 4+ It just resizes the iframe to some arbitrary size and still shows Command Log.

<img width="841" alt="Screen Shot 2020-02-26 at 4 25 37 PM" src="https://user-images.githubusercontent.com/1271364/75333517-a5f6e480-58b4-11ea-88d3-1e899c3a6bb3.png">

I'm not sure what changed, but likely something from the Firefox PR https://github.com/cypress-io/cypress/pull/1359/

Needless to say, this is pretty hacky and may cause unintended consequences and could certainly break in newer releases (as it already has).

**Comment by AlexA-1976** [comment]
Can somebody please add this capability?

**Comment by cmfcmf** [comment]
The following command works in Cypress 4.7.0:
```js
Cypress.Commands.add('clearViewport', () => {
  const runnerContainer = window.parent.document.getElementsByClassName('iframes-container')[0];
  runnerContainer.setAttribute('style', 'left: 0; top: 0; width: 100%; height: 100%;');

  const sizeContainer = window.parent.document.getElementsByClassName('size-container')[0];
  sizeContainer.setAttribute('style', '');

  const sidebar = window.parent.document.getElementsByClassName('reporter-wrap')[0];
  sidebar.setAttribute('style', 'display: none;');

  const header = window.parent.document.querySelector('.runner.container header');
  header.setAttribute('style', 'display: none;');
});
```

**Comment by bahmutov** [comment]
Thank you @cmfcmf - I am using your snippet in http://github.com/bahmutov/cypress-movie to successfully hide the command log and generate high-resolution movies and screenshots from tests

<img width="961" alt="movie-screenshot" src="https://user-images.githubusercontent.com/2212006/85906050-2b46c300-b7db-11ea-94bb-7341b567d585.png">

**Comment by flotwig** [comment]
The command log can also be disabled via CYPRESS_NO_COMMAND_LOG: https://docs.cypress.io/guides/references/troubleshooting#Disable-the-Command-Log

**Comment by flotwig** [comment]
Closing since there are ways to do this now, including @cmfcmf's approach and CYPRESS_NO_COMMAND_LOG.
