### ISSUE TITLE
TypeScript 5.4 complains about methods not exist on type 'LoDashStatic' in Cypress 13.12

### ISSUE THREAD

**Issue by chaussen** [cypress-io/cypress#29702]
### Current behavior

When using methods from builtin lodash like

```Cypress._.isString(values)```

TypeScript complains about that `Property 'isString' does not exist on type 'LoDashStatic'.`. This only happens in Cypress 13.12. There was no error in the previous versions.

### Desired behavior

It should know what methods lodash have.

### Test code to reproduce

Cypress._.isString(values)

### Cypress Version

13.12

### Node version

20

### Operating System

Win11

**Comment by AtofStryker** [comment]
Hi @chaussen . Thank you for opening an issue. I created https://github.com/AtofStryker/cypress_issue_29702 to reproduce the issue but did not have any luck. Are you able to fill in the blanks to recreate the issue in the repository?

**Comment by chaussen** [comment]
> Hi @chaussen . Thank you for opening an issue. I created https://github.com/AtofStryker/cypress_issue_29702 to reproduce the issue but did not have any luck. Are you able to fill in the blanks to recreate the issue in the repository?

Thank you. I find the errors disappear after I restarted the TS server. Must be something else.
