### ISSUE TITLE
Handle deprecation of CDP in Firefox 129

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#29713]
### What would you like?

Firefox is deprecating CDP in Firefox 129. [See announcement.](https://fxdx.dev/deprecating-cdp-support-in-firefox-embracing-the-future-with-webdriver-bidi/) There is a workaround until support is removed for CDP at the end of the year and we’ll need to replace that functionality with WebDriver BiDi. 

We'll need to set the `remote.active-protocols` preference to `2` before starting Firefox.

Installing Firefox Nightly 129 and running it within Cypress does not currently work. The browser does not launch as shown below.

I'm not sure when Firefox 129 will release, they say they release every 4-5 weeks. There's [this schedule](https://whattrainisitnow.com/calendar/), but I'm not sure who's published it. Asking someone from Mozilla directly to see when it will be released.

![Screenshot 2024-06-19 at 5 33 49 PM](https://github.com/cypress-io/cypress/assets/1271364/4c95589d-9338-4371-9051-e65830af50a5)

**Comment by xwz** [comment]
Since firefox 129 is now released, the latest cypress 13.13.3 package still does not start firefox correct

**Comment by AtofStryker** [comment]
> Since firefox 129 is now released, the latest cypress 13.13.3 package still does not start firefox correct

@xwz do you have a reproduction? FIrefox 129 starts correctly in `open` mode and we execute tests in our docker containers against Firefox 129 in `run` mode and [those look correct](https://app.circleci.com/pipelines/github/cypress-io/cypress-docker-images/2223/workflows/56f4b303-611b-4b08-aeb5-92540adc0c3a/jobs/67895) as well 
![firefox](https://github.com/user-attachments/assets/e6f2a5ff-5802-43ef-942e-2518fc7682f5)

**Comment by xwz** [comment]
Oh, the mac, if there is an existing cypress installation, one needs to run `cypress cache clear` and then re-install cypress to trigger security dialog that seem to add something to System Settings on 1st run of the new install.
