### ISSUE TITLE
Get current test name within the currently running test.

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2972]
## feature

Sometimes users might need to know the name of the current test (current 'it' block and its parents). It would be nice to add the name to the object `Cypress.spec`. The name should have parts of each "describe" block from the parent to the test

```js
describe('foo', () => {
  describe('bar', () => {
    it('log spec info', function() {
      console.log(Cypress.spec)
      // {
      //   name: 'filter.spec.js',
      //   relative: 'cypress/integration/filter.spec.js',
      //   absolute: '/Users/janelane/Dev/web-app/cypress/integration/filter.spec.js',
      // . new property "test" with block and test names
      //   test: ['foo', 'bar', 'log spec info']
      // }
    })
  })
})
```

**Comment by bahmutov** [comment]
currently users can find the test names using helper package https://github.com/bahmutov/its-name but it is less than convenient.

**Comment by jennifer-shehane** [comment]
I was looking for this today. I thought maybe just a `Cypress.test`

**Comment by Euregan** [comment]
It would also be useful to be able to get the whole test names from the `beforeEach` declared in support files.
Use case I have in mind is generating stubs for each test file, and storing them with a hash of the test they are created for

**Comment by Doogiemuc** [comment]
upvote!  Would like to have this, too!

**Comment by Doogiemuc** [comment]
[SOLVED]
This worked for me:

        beforeEach(function() {
		console.log("=======>>>", Cypress.mocha.getRunner().suite.ctx.currentTest.title)
	})

**Comment by gabbersepp** [comment]
The workaround from @Doogiemuc  does not work in all circumstances.
Today after updating from cypress 3.4.1 to 3.6.1 i saw a "cannot read 'title' of undefined" exception a few times.

**Comment by gabbersepp** [comment]
@jennifer-shehane I am interested in a solution for this. In the beforeEach and afterEach I writing logs with the testname in it. Would be nice if we must not rely on this workaround.
I already took a look into the driver package but did not found the place that needs to be modified. Can you give me just a little hint so I do not have to search the whole package for the right place?

**Comment by itaditya** [comment]
This works for me

```js
  it('dashboard to challenge flow is visually correct', function () {
    console.log(this.title); // dashboard to challenge flow is visually correct
  });
```

**Comment by cadz7** [comment]
I'm planning on accessing the test names in `beforeEach` for a larger project to conditionally skip them based on whether the test name satisfies certain requirements.
@jennifer-shehane Would you recommend sticking to the workaround suggested by @Doogiemuc? I would like to avoid the situation of depending on a specific version of Cypress incase the workaround breaks for subsequent versions.

**Comment by Hecsall** [comment]
I encountered a similar issue working on a project where i wanted to add a custom screenshot name at the end of the original cypress-generated filename, so i wrote this little function based on @Doogiemuc solution:

```javascript
// utils/index.js

function getTestName () {
    let cypressContext = Cypress.mocha.getRunner().suite.ctx.test;
    let testTitles = [];

    function extractTitles (obj) {
        if (obj.hasOwnProperty('parent')) {
            testTitles.push(obj.title);
            let nextObj = obj.parent;
            extractTitles(nextObj);
        }
    }

    extractTitles(cypressContext);
    let orderedTitles = testTitles.reverse();
    let fileName = orderedTitles.join(' -- ');
    return fileName;
}
```
This function iterates over every parent element saving all their titles in an array, then it reverses it, join it with " -- " and returns the final string.
This way i can use it like this:

```javascript
import { getTestName } from '../utils';

describe('Describe One', () => {
    describe('Describe Two', () => {
        it('MyTest', () => {
            cy.screenshot(`${getTestName()} -- something`)
            // This will result in 
            // "Describe One -- Describe Two -- MyTest -- something.png"
        })
    })
})
```
Maybe it's not a beautiful solution, but for now it works, hope it helps

**Comment by Karnikel** [comment]
Small addition to the solution of @Doogiemuc and @Hecsall:
If you are using typescipt on Cypress you will get the error 
`TS2339: Property 'mocha' does not exist on type 'Cypress & EventEmitter'.`
To solve this you can write 
```javascript
(Cypress as any).mocha.getRunner().suite.ctx.test
```
It's a kind of hacky...but it works ;)

**Comment by LukasLewandowski** [comment]
Any update on this? How to get the context or describe test value?

**Comment by Karnikel** [comment]
@LukasLewandowski: You can use the chrome debugger to observe the object content mentioned above.
There you can get very much informations about your current running test.
E.g. `Cypress.mocha.getRunner().suite.ctx.test.title` will return the describe string of the current running test.

**Comment by hbriese** [comment]
This is a typescript solution. It'd be nice if they included mocha in their types

```
const getTestTitle = (test: any = (Cypress as any).mocha.getRunner().suite.ctx.test): string =>
    test.parent?.title ? `${getTestTitle(test.parent)} -- ${test.title}` : test.title;
```

Simply call `getTestTitle()`

**Comment by pierre-vr** [comment]
> This is a typescript solution. It'd be nice if they included mocha in their types
> 
> ```js
> const getTestTitle = (test: Mocha.Suite = (Cypress as any).mocha.getRunner().suite.ctx.test): string =>
>     test.parent?.title ? `${getTestTitle(test.parent)} -- ${test.title}` : test.title;
> ```
> 
> Simply call `getTestTitle()`

I had to use `currentTest` instead of `test` to make it work in my support index.ts file:

```js
beforeEach(() => {
    const getTestTitle = (test: Mocha.Suite = (Cypress as any).mocha.getRunner().suite.ctx.currentTest): string =>
        test.parent?.title ? `${getTestTitle(test.parent)} -- ${test.title}` : test.title
    console.log(getTestTitle())
})
```
