### ISSUE TITLE
Aw, Snap!

### ISSUE THREAD

**Issue by YutongZhuu** [cypress-io/cypress#29768]
### Test code to reproduce

Always get this:
![image](https://github.com/cypress-io/cypress/assets/115899167/f83766e7-bd55-45a2-81f4-56f8309571df)
If I use cypress for a long time. I suspect there is some memory leaks? Or the memory of browser is too little for cypress? I am not sure. BTW, I am just a QA intern, so I don't have a lot of experience with Cypress, so please correct me if I got anything wrong. 

### Cypress Mode

cypress open

### Cypress Version

11.2.0

### Browser Version

Chrome 126

### Node version

v16.17.1

### Operating System

Windows10 pro

**Comment by MikeMcC399** [comment]
@YutongZhuu 

- Follow the advice in [The browser process running your tests just exited unexpectedly](https://docs.cypress.io/guides/references/error-messages#The-browser-process-running-your-tests-just-exited-unexpectedly)
- Update to the latest version of Cypress (see [Changelog](https://docs.cypress.io/guides/references/changelog))
- Update to a supported version of Node.js (see [Installing Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs)). If possible, use the Node.js version shown as [LTS](https://github.com/nodejs/Release)
- Reach out to the [Cypress technical community on Discord](https://on.cypress.io/discord) if the above fails
