### ISSUE TITLE
When I create a new cypress project it crashes 

### ISSUE THREAD

**Issue by Ninad1805** [cypress-io/cypress#29777]
![Screenshot 2024-06-30 131212](https://github.com/cypress-io/cypress/assets/87935579/097d1b79-7452-45b0-9fb0-aae6a5db2c4c)
### Current behavior

I am currently trying to create a new cypress project and whenever I try to open the cypress app it crashes and gets stuck in the background. Also the browser does not respond. If I make changes to my test via VS code then I am not able to run the test again.

It is working fine for another project which I cloned via github but is not working when I am trying to create a new project

### Desired behavior

The terminal should start compiling the new test code when I hit save and the cypress app and testrunner should not freeze

### Test code to reproduce
```js
describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://www.udemy.com/course/cypress-tutorial/learn/lecture/26426180#content')
  })
})
```
### Cypress Version

@latest

### Node version

@latest

### Operating System

Windows 11

### Other

https://github.com/cypress-io/cypress/assets/87935579/d441cb46-e837-4b17-bad7-2539e2f5cf00

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?
