### ISSUE TITLE
Cypress moves onto next line before completing previous command

### ISSUE THREAD

**Issue by mmestas** [cypress-io/cypress#29780]
### Current behavior

I'm having the exact same issue reported back in 2019  with issue #5480  
https://github.com/cypress-io/cypress/issues/5480

When running a large test that checks many form fields, cypress errors at different points due to not completing the previous command before running the next command.  If I break this test into smaller sections, it seems to work fine and I get no errors, but when running the test over the entire form, each time I get an error in a different spot. 

The last time it failed, it was supposed to type an invalid value of "100" before checking to see if there was an error message for that field.  Cypress  failed stating, "expected [data-cy="alt_chan_outgain_errors_0-1"] to exist in the DOM" however, on inspection, it had NOT typed 100 before proceeding to that   next check.  On other runs, it got past this check and failed in a similar fashion on another input.   I originally had the commands chained together (ex. cy.get('[data-cy="alt_chan_outgain_'+idx+'-'+gain+'"]').clear().type('100'); )and separated them to see if that would fix it, and it helped slightly, but I'm still getting errors.  

Another instance of it failing while running the test was it didn't clear before typing the new value.  The previous value was 10 and should clear and then type 9.  This worked as it looped through several inputs just fine, but randomly failed on one.  Instead of 10 as the value, it was 910.  The value never cleared even though the command "clear()" ran.
<img width="563" alt="Screenshot 2024-07-01 at 9 10 13 AM" src="https://github.com/cypress-io/cypress/assets/17856852/c47b6290-c34f-4de4-8f9b-a295074f0d01">
<img width="617" alt="Screenshot 2024-07-01 at 9 10 32 AM" src="https://github.com/cypress-io/cypress/assets/17856852/b06089d5-6e7f-4b06-bc88-0ef1c1ab1534">

Again, if I just run the test on this one section at a time, it passes.  It seems that it gets overloaded when running the full form with the .each loops.

### Desired behavior

Finish the command fully before checking the next command.

### Test code to reproduce

```js
cy.get('[data-cy="device_alternate_gains"] > .nav-item').each(($tab, idx) => {
			cy.get('[data-cy="alt_chan'+idx+'"]').click();
			cy.get('[data-cy="alt_chan_hw_selector'+idx+'"]').should('exist');

			let gainArr = [1,2,3];
			gainArr.forEach(gain => {
				cy.get('[data-cy="alt_chan_mic_'+idx+'-'+gain+'"]').should('be.visible').check();

				cy.get('[data-cy="alt_chan_ingain_'+idx+'-'+gain+'"]').invoke('val').then(val => {
					let originalVal = parseInt(val as unknown as string, 10);
					let numToUse = originalVal === 10 ? '9' : '10';
					cy.get('[data-cy="alt_chan_ingain_'+idx+'-'+gain+'"]').clear();
					cy.get('[data-cy="alt_chan_ingain_'+idx+'-'+gain+'"]').type('-10');
					cy.get('[data-cy="alt_chan_ingain_errors_'+idx+'-'+gain+'"]').should('exist').should('not.be.empty');
					cy.get('[data-cy="fdh_save"]').should('exist').should('be.disabled');
					cy.get('[data-cy="fdh_unsaved_msg"]').should('exist').contains('Form has invalid values');
					cy.get('[data-cy="alt_chan_ingain_'+idx+'-'+gain+'"]').clear();
					cy.get('[data-cy="alt_chan_ingain_'+idx+'-'+gain+'"]').type(numToUse);
					cy.get('[data-cy="alt_chan_ingain_errors_'+idx+'-'+gain+'"]').should('not.exist')
				});
				cy.get('[data-cy="alt_chan_outgain_'+idx+'-'+gain+'"]').invoke('val').then(val => {
					let originalVal = parseInt(val as unknown as string, 10);
					let numToUse = originalVal === 10 ? '9' : '10';
					cy.get('[data-cy="alt_chan_outgain_'+idx+'-'+gain+'"]').clear();
					cy.get('[data-cy="alt_chan_outgain_'+idx+'-'+gain+'"]').type('100');
					cy.get('[data-cy="alt_chan_outgain_errors_'+idx+'-'+gain+'"]').should('exist').should('not.be.empty');
					cy.get('[data-cy="fdh_save"]').should('exist').should('be.disabled');
					cy.get('[data-cy="fdh_unsaved_msg"]').should('exist').contains('Form has invalid values');
					cy.get('[data-cy="alt_chan_outgain_'+idx+'-'+gain+'"]').clear();
					cy.get('[data-cy="alt_chan_outgain_'+idx+'-'+gain+'"]').type(numToUse);
					cy.get('[data-cy="alt_chan_outgain_errors_'+idx+'-'+gain+'"]').should('not.exist')
				});
				
			});

		});
```

### Cypress Version

13.9.0

### Node version

18.15.0

### Operating System

Mac OS 14.3.1

### Other

Using this with Angular 17.2.3

**Comment by jennifer-shehane** [comment]
@mmestas Can you provide an example that we can run to see the issue? It will be impossible to address without this, as the issue is likely dependent on how the form functions.

**Comment by mmestas** [comment]
@jennifer-shehane  Additional info is that this seems to happen particularly when the previous input was a negative number (ex. -100) Calling .clear() causes all the inputs to disappear temporarily, which is why it fails (I'm guessing) - because it's not finding the input in the DOM. I noticed this today when trying it again - but it doesn't happen all the time.  I changed the values to 300 and the clear seems to be working, however, still fails sometimes with the clear, but less so.  

**Important Note: I am looping through several fields of the following in the form.  It's an array of these input fields of the same type, which is why the IDs are rendered dynamically.  Since it only fails some of the time, it might not fail for you unless you are running this on a large form.**

What would you like as an example?  My actual html has dynamically rendered ids, but it looks something similar to this:

HTML

```html
      <div>
        <input type="number" class="form-control" formControlName="ingain" [attr.data-cy]="'ingainID'" >
        <ng-container *ngIf="alternateGainsArr.controls[idx].get('gains')?.get([i-1])?.get('ingain')?.errors">
          <div class="form-text text-danger fw-bold" [attr.data-cy]="'ingainID_errors'"
            *ngFor="let error of alternateGainsArr.controls[idx].get('gains')?.get([i-1])?.get('ingain')?.errors | keyvalue">
            <small>{{error.key === 'required' ? error.key : error.value}}</small>
          </div>
        </ng-container>
      </div>
```

Cypress 

```js
      // Enter invalid value
      cy.get('[data-cy="ingainID"]').clear();
      cy.get('[data-cy="ingainID"]').invoke('val').should('be.empty');
      cy.get('[data-cy="ingainID"]').type('-100');
      cy.get('[data-cy="ingainID_errors"]').should('exist').should('not.be.empty');
      // Enter a valid value
      cy.get('[data-cy="ingainID"]').clear();
      cy.get('[data-cy="ingainID"]').invoke('val').should('be.empty');
      cy.get('[data-cy="ingainID"]').type(10);
      cy.get('[data-cy="ingainID_errors"]').should('not.exist');
```

Again, my code is slightly different because of how the IDs are rendered, but this is the general idea.  If I use 300 instead of -100, it works more often, but still not all of the time.  It's almost like it skips to the next line "type()" before checking if the value is empty after the clear because the value "10" - appears before the check if empty is run

ALSO, it would be REALLY helpful for .type() to allow numbers.  Right now, the inputs in cypress seem to only accept strings.  I have to keep converting values to and from strings/numbers for input type number, which is excessive steps and a pain.

**Comment by mmestas** [comment]
EDIT:  I decided to try adding "wait()" between the calls and the tests passed. 

```js
// Enter invalid value
cy.get('[data-cy="ingainID"]').clear();
cy.wait(200);
cy.get('[data-cy="ingainID"]').invoke('val').should('be.empty');
cy.wait(200);
cy.get('[data-cy="ingainID"]').type('-200');
cy.get('[data-cy="ingainID_errors"]').should('exist').should('not.be.empty');
// Enter a valid value
cy.get('[data-cy="ingainID"]').clear();
cy.wait(200);
cy.get('[data-cy="ingainID"]').invoke('val').should('be.empty');
cy.wait(200);
cy.get('[data-cy="ingainID"]').type(10);
cy.get('[data-cy="ingainID_errors"]').should('not.exist');
```

So it does seem like the `type()` was getting called before `invoke.val` even though that isn't the order of the tests.  This seems to be a bug in how the lines are firing.


EDIT again.  When running the full test, even with the waits, the value was typed before the check.  Do the cypress tests not run in order of each line or something?

**Comment by jennifer-shehane** [comment]
It should execute in that order. Do you have any listeners on the input that performs some logic after the input is focused/etc? I'm not sure why the waits would be necessary.

**Comment by mmestas** [comment]
@jennifer-shehane I didn't have the wait on there originally.  I added it on as an attempt to prevent the .type() from firing before that line finished.  You are right, it shouldn't be necessary, but I'm trying anything to see why the value is getting filled before the clear() and should be empty is evaluated and passed. 

Perhaps to elaborate on the form.  It's a series of the exact same type of fields, all with different IDs.  They are set in tabs.  There are 3 sets of 2 fields each in each tab (so 6 in each tab, and 24 total over 4 tabs) 
The cypress test clicks each tab and then loops through each field   - first clearing it out, then seeing if it's empty, then typing a value, then checking the value, before proceeding to the next tab and checking those fields.  Once all the fields have been edited, the test discards the form changes and checks to see if they have the original values.   Then this is run all over again , but this time, the form is saved.  

I have run this test and on rare occasions, it makes it through and completes.  When it fails, it's not in the same place every time.  Sometimes it's on tab 1, and sometimes not until tab 4.  When I highlight over the failed part, for example, where the value should have cleared and failed on "should be empty", the value that would be typed on a future line is present.  i.e. if the value was 9, then cleared, on the cleared evaluation, it shows the value as 10 when there shouldn't be any value.  
Sometimes, the value does not get cleared at all and I get 109 or similar as if it just typed the 10 on top of the 9.

**Comment by jennifer-shehane** [comment]
We'd need a way to reproduce and investigate on our end in order to find the issue.
