### ISSUE TITLE
Elevated and consistent "502 Bad Gateway" when running in Cypress Cloud

### ISSUE THREAD

**Issue by efreethy** [cypress-io/cypress#29795]
### Current behavior

We are experiencing significantly elevated and consistent `502 Bad Gateway` errors from within cypress cloud runner. This is making it near impossible to get our tests to pass.

This started on upgrading from cypress 12 to cypress 13. This issue doesn't happen outside of cypress.

<img width="428" alt="Screenshot 2024-07-02 at 9 40 13 AM" src="https://github.com/cypress-io/cypress/assets/12145559/932fc13e-9d32-4cd0-be04-9ed3420119c0">

### Test code to reproduce

N/A

### Cypress Version

13.13.0

### Node version

20.14.0

### Operating System

Ubuntu 22.04.4 LTS

**Comment by jennifer-shehane** [comment]
We'll need some more information to narrow down this issue as we haven't seen this reported. 

- Is there a more specific Cypress version you can narrow down the problem to?
- Are you able to provide a way to reproduce the error?
- Is there anything revealing in the Test Replay that explains the difference in behavior? With timing, etc?

**Comment by MikeMcC399** [comment]
@efreethy 

Cypress Cloud isn't actually a runner. It's only the place where the results of running Cypress are recorded. I don't think it can cause a HTTP 502 Bad Gateway error. It would only record the fact that it is happening.

- Can you say where you are running Cypress?
- Is it running locally or are you using a CI provider like GitHub Actions or CircleCI?
- Where is the server located that you are trying to contact and for which you are receiving an HTTP 502 Bad Gateway error? Is it a local server which is fired up as part of the test? Is it an external website which is already running?

I'm also seeing this error occurring sporadically so it would be good to know more about your environment.
