### ISSUE TITLE
Error: read ECONNRESET Cypress not opening for Browser

### ISSUE THREAD

**Issue by Parvez785** [cypress-io/cypress#29805]
### Current behavior

Below is the error i am facing and not allowing me to run cypress in chrome
```
read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

### Desired behavior

Should open Cypress in browser for adding automated test 

### Test code to reproduce

`npx cypress open` not working in terminal

### Cypress Version

26

### Node version

20.10.0

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
@Parvez785 Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?
