### ISSUE TITLE
Routes can overrun the hover box that appears over the alias name

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#2980]
### Current behavior:
Routes can overrun the hover box as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/5534029/50348526-0945f380-0507-11e9-8aa5-28715f4e3b2c.png)

### Desired behavior:
The background expands to fit routes up to a certain higher width (say 300 px or something like that).
For routes that are longer, they wrap to multiple lines using something like 

word-wrap: break-word; 

### Steps to reproduce: (app code and test code)
1) Alias a route that has a long chunk of text with no characters that trigger a line break
2) Run your tests
3) Hover over the yellow alias name
4) Observe that the route name extends beyond the edge of the background

### Versions
Cypress 3.1.3
Chrome
Windows 10

**Comment by jennifer-shehane** [comment]
Tooltip component is here: https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/commands/command.jsx#L30

But likely, just need a change in css to have all tooltips content properly text wrap - place in this file: https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/lib/tooltip.scss#L5
