### ISSUE TITLE
cypress.tick() not updating ui in angular component testing

### ISSUE THREAD

**Issue by imaliouris** [cypress-io/cypress#29810]
### Current behavior

In angular component testing I have a standalone component with a disabled button that shows the time that needs to be enabled again.

In order to show the countdown I have a `setInterval` in `ngOnInit` that updates a signal every 1 second.

Everything works as expected both in browser and in component testing in cypress.
Although the time is long enough to wait so in component testing I use `cy.clock()` and then `cy.tick()` (with the time that I want to pass in order to test that the button becomes enabled after the time passes.

The problem is that after tick the ui doesn't change even though when I use `console.log()` inside the `setInterval` it logs the changes that occur every second

### Desired behavior

Ui should be updated after using `cy.tick()`

### Test code to reproduce

https://github.com/imaliouris/cypress-tick-bug

Run the component test and see that the ui is the same and nothing changes but when you use ng serve everything seems fine

### Cypress Version

13.13.0

### Node version

v18.19.1

### Operating System

ubuntu 22.04

**Comment by jennifer-shehane** [comment]
This is likely the same issue as https://github.com/cypress-io/cypress/issues/28846 I think there's something not working in component tests with cy.clock/tick
