### ISSUE TITLE
Browser connection failed

### ISSUE THREAD

**Issue by gersoncdias** [cypress-io/cypress#29833]
### Test code to reproduce

I'm having problems running my test battery which contains more than 300 tests, when I run a certain number of tests I get this browser connection error

### Cypress Mode

cypress run

### Cypress Version

cypress.13.6.4

### Browser Version

Chrome 126 

### Node version

 v20.5.0

### Operating System

Linux

### Memory Debug Logs

```shell
Timed out waiting for the browser to connect. Retrying...
Missing browserCriClient in connectToNewSpec
Error: Missing browserCriClient in connectToNewSpec
    at Object.connectToNewSpec (<embedded>:4438:48137)
    at Object.connectToNewSpec (<embedded>:4438:27043)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async v.relaunchBrowser (<embedded>:4504:37724)
```

**Comment by MikeMcC399** [comment]
@gersoncdias 

- I also reported this error in https://github.com/cypress-io/cypress/issues/29554
  > Error: Missing browserCriClient in connectToNewSpec

however currently it is not occurring for me using the latest Cypress version (`13.13.0`) against Chrome `126` on Linux (Debian `12.6`) running Node.js `v20.15.1`. This is in a headless (no GPU) Docker environment on CircleCI.

Are you able to test with Cypress `13.13.0` and see if it still happens? Maybe also update your Node.js version as well.

**Comment by jennifer-shehane** [comment]
Closing since there's no response. I also recommend updating as I believe this is fixed.
