### ISSUE TITLE
Video framerate inconsistency: EveryNthFrame defaults to 5 on newer chrome versions

### ISSUE THREAD

**Issue by michalkkkd** [cypress-io/cypress#29834]
### Current behavior

**There appears to be a potential issue with how Cypress handles video framerates when capturing screencasts on newer Chrome versions. The current behavior seems to be unintentional.**

_packages/server/lib/browsers/chrome.ts:_

`const screencastOptions = browserMajorVersion >= CHROME_VERSION_WITH_FPS_INCREASE ? screencastOpts() : screencastOpts(1);
`

_screencastOpts function:_
```
export function screencastOpts (everyNthFrame = Number(process.env.CYPRESS_EVERY_NTH_FRAME || 5)): Protocol.Page.StartScreencastRequest {
  return {
    format: 'jpeg',
    everyNthFrame,
  };
}

```
This function defaults to everyNthFrame = 5 if no value is provided.

**Impact:**

- Unexpected Behavior: Users might not be aware that Cypress defaults to a lower frame rate on newer Chrome, leading to confusion about video quality and performance.
- Increased File Sizes: Capturing every 5th frame on newer Chrome versions leads to larger video files, which can impact storage and bandwidth usage.

### Desired behavior

**1. Modify screencastOpts:**
- Pass a different default value (e.g., 1) to screencastOpts() when the browser version is newer.
- Introduce a new parameter to screencastOpts to control the frame rate explicitly.

**2. Update Documentation:**
- Clearly document the default behavior of everyNthFrame on newer Chrome versions in the https://docs.cypress.io/guides/guides/screenshots-and-videos section.
- Provide guidance on how users can adjust the frame rate if desired.

### Test code to reproduce

Environment: Run Cypress tests on a Chrome version 89 or newer.
Capture: Initiate screencast capture with cy.video
Observation: Cypress will capture video frames at a rate of 5 frames per second (everyNthFrame = 5) even though newer Chrome versions can handle higher frame rates.

### Cypress Version

13.13.0

### Node version

20.15.1

### Operating System

Win11 x64

**Comment by jennifer-shehane** [comment]
Capturing more frames impacts performance and can result in a drastic slowdown of runtime of the tests. We set it to a default value that seemed to not impact performance on machines that are right sized and that did not seem to visually degrade the video too much. We don’t intend to change the default and impact performance. 

You can set the value to a different value with the env var, but I would make sure to measure if there is any performance impact. We’re open to a PR to our docs to more clearly document this.

**Comment by michalkkkd** [comment]
I understand the goal of not increasing file sizes / decreasing performance to gain quality, but still the code here is somewhat wrong. So on older chromes <89 cypress captures every frame?

**Comment by jennifer-shehane** [comment]
Yes. Chrome made a change in 89 that increased their default frames captured to be much more frequent than previous versions which resulted in performance issues for everyone, so we set it lower for those affected versions. https://github.com/cypress-io/cypress/issues/16152

**Comment by michalkkkd** [comment]
Thank you very much for this info! Now it's completely understandable.
