### ISSUE TITLE
Cypress is having a dependency on xvfb when run on headless mode - chromium browser

### ISSUE THREAD

**Issue by senthilvelan89** [cypress-io/cypress#29851]
### Current behavior

Cypress version 13.7.2
Browser: chromium
OS: rhel9

`cypress run --headless --browser chromium` throws error below
```
Error : spawn Xvfb ENOENT
```
My understanding is cypress shouldn't depend on xvfb - when in  run headless mode based on https://github.com/cypress-io/cypress/issues/16505

Also tried to set ELECTRON_RUN_AS_NODE=true. no luck
                     unset DISPLAY

### Desired behavior

Cypress should start w/o xvfb dependency

### Test code to reproduce

do-not install xvfb on rhel9
cypress run --headless --browser chromium

### Cypress Version

13.7.2

### Node version

18

### Operating System

RHEL9

**Comment by MikeMcC399** [comment]
@senthilvelan89 

- This issue (for Chromium) is very similar to the open enhancement request https://github.com/cypress-io/cypress/issues/19868

**Comment by jennifer-shehane** [comment]
Yes, will close as duplicate as we would need to change our codebase to not depend on xvfb
