### ISSUE TITLE
backface-visibility: hidden doesn't hide elements from cypress

### ISSUE THREAD

**Issue by callumacrae** [cypress-io/cypress#2985]
### Current behavior:

`cy.contains()` is getting an element which isn't actually visible

### Desired behavior:

It should fail as the element isn't visible

### Steps to reproduce: (app code and test code)

https://codepen.io/desandro/pen/LmWoWe

On this pen, `cy.contains('back')` will pass even when it is hidden.

### Versions

Latest version, chrome

**Comment by jennifer-shehane** [comment]
Thank you so much for providing a reproducible example!

**Comment by jennifer-shehane** [comment]
I'm able to reproduce this with the following code:

## index.html

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
  <div style="position: absolute; width: 200px; height: 260px; background: red; backface-visibility: hidden;">
    <span id="front" >front</span>
  </div>
  <div style="position: absolute; width: 200px; height: 260px; background: blue; backface-visibility: hidden; transform: rotateY(180deg);">
    <span id="back">back</span>
  </div>
</body>
</html>
```

## spec.js

```js

it('should not be visible', function () {
  cy.visit('index.html')

  cy.get('#front').should('be.visible')
  cy.get('#back').should('not.be.visible')
})
```

I added a failing test in here: https://github.com/cypress-io/cypress/pull/4421

backface-visibility: https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility
