### ISSUE TITLE
onkeydown is inaccessible from cy.window()

### ISSUE THREAD

**Issue by robmoore-i** [cypress-io/cypress#2986]
Hi,

I've set `window.onkeydown` in my web page.

I am in a cypress test and want to access and run it (because `cy.type()` does not simulate a key down event in this way).

I call `cy.window.then((w) => w.onkeydown({key: "c"}) ) `

Upon some brief investigation, it turns out that:

- `w.onkeydown` is `null`
- When I run `console.log(w)` it shows that `w.onkeydown` is not `null`, and in fact is the function I am expecting it to be, according to the `[[FunctionLocation]]` metadata.

So the function I want to invoke is accessible from where I am, but is not being mapped over to the actual returned value of `cy.window()` I suppose.

Hope this helps,

Rob

**Comment by Bkucera** [comment]
@robmoore-i cy.type should cause window.onkeydown to be called.

possibly your cypress test code is running before that method is set on window.

this works fine for me
```js
  it.only('foobar', () => {

    const spy = cy.spy().as('onkeydown')

    cy.window().then((win) =>
      setTimeout(()=>win.onkeydown = spy, 2000)
    )

    cy.window().should((win) => {
      expect(win).to.property('onkeydown').ok
    })
    cy.window().should((win) => {
      win
    })

    cy.get('input:first').type('foobar').then(() => {
      expect(spy.callCount).to.eq(6)
    })
  })
```

**Comment by Bkucera** [comment]
I'm going to close this, but if you still believe this is a bug in cypress, feel free to leave a comment
