### ISSUE TITLE
Cypress - How to get rid of Chrome 'Change your password' popup (duplicates  #29384)

### ISSUE THREAD

**Issue by SairamNewron** [cypress-io/cypress#29877]
### Current behavior

A SUGGESTION COME FROM GOOGLE CHROME TO CHANGE PASSWORD, WHICH WE USE COMMONLY FOR EVERYONE IN THE ORGANISATION (aDMIN CREDENTAILS)

### Desired behavior

I want to close the alert 

### Test code to reproduce

![Screenshot (370)](https://github.com/user-attachments/assets/48495cbf-0309-4105-a254-e38b62148d42)

### Cypress Version

13.13.0

### Node version

20.9.0

### Operating System

windows 64

### Debug Logs

```shell
How to close the popup which is coming from the google chrome
```

**Comment by jennifer-shehane** [comment]
@SairamNewron I've been unable to find a flag to disable this prompt automatically within Chrome. I'd probably suggest changing your password since Chrome is indicating it was part of some data breech.

**Comment by gweesin** [comment]
It seems you should close it by the handle:

1. open chrome://password-manager/settings
2. click **Offer to save passwords and passkeys** to ensure that the password manager is disabled

**Comment by jennifer-shehane** [comment]
Yes, you could manually do this. Maybe these settings will persist. There's no way for Cypress to turn this off programatically.

**Comment by Santoshkk2021** [comment]
Butwe want to handle the popup programatically

**Comment by maxfriedmann** [comment]
@Santoshkk2021 this worked for me: https://stackoverflow.com/a/79548376/1227985

**Comment by maxfriedmann** [comment]
After I updated cypress + chrome this did not work for me anymore. But the guest mode does now:

```javascript
if (browser.name === "chrome") {
  launchOptions.args.push("--guest");
}
```

**Comment by SimonFischer04** [comment]
this is the proper way to do it according to google (https://issues.chromium.org/issues/42323769):

launchOptions.preferences.default.profile['password_manager_leak_detection'] = false

can this be added to cypress by default? @jennifer-shehane 
Can try to create a pr, if that helps.

**Comment by suuf** [comment]
The Chromium linked issue is informative, thank you for sharing @SimonFischer04 .

As mentioned before, this works:

>   launchOptions.args.push("--guest");`

Also:

> launchOptions.preferences.default.profile['password_manager_leak_detection'] = false

When provided in the cypress config as something like:

```                   
launchOptions.preferences.default = {
    ...launchOptions.preferences.default,
        profile: {
            password_manager_leak_detection: false,
        },
};
```
Also works.
