### ISSUE TITLE
[Cypress 13.13.1, Chrome] - unload is not allowed

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#29880]
### Current behavior

![image](https://github.com/user-attachments/assets/5266808c-39a3-44b0-a30f-49e6e5f13705)

![image](https://github.com/user-attachments/assets/bd521d5d-fa42-4aed-a92a-d18d6bc97449)

### Desired behavior

No extra error in Chrome DevTools Console

### Test code to reproduce

I have this in my cypress.config.js file

```js
on('before:browser:launch', (_, launchOptions) => {
    launchOptions.args.push('--enable-features=DeprecateUnload')
    return launchOptions
});
```

### Cypress Version

13.13.1

### Node version

v20.15.1

### Operating System

Windows 10.0.19045

**Comment by jennifer-shehane** [comment]
@alexsch01 What is the issue? Is this not the correct error showing in the console?

What version of Chrome are you using? Chrome is beginning to roll out the breaking of unload this quarter.

>In addition, from Q3 2024, we intend to start a generic phase where unload will gradually cease to function on any sites, starting with 1% of users and ending with 100% of users by the end of Q1 2025.

**Comment by alexsch01** [comment]
@jennifer-shehane I'm running Google Chrome 126.0.6478.182

the error is coming from a cypress file

I've made this patch previously for a fix for unload for older Cypress versions 

https://github.com/alexsch01/cypress-custom/blob/2ad7622c1d1e6f5eeb480ef69e34b1fda6c0a707/packages/driver/patches/jquery%2B3.1.1.dev.patch

**Comment by jennifer-shehane** [comment]
jQuery!! Yah we missed this, let me look into it.

**Comment by jennifer-shehane** [comment]
There seems to additionally be this situation where the browser is not being evaluated as Chromium and having the unload event also. 

The rest seem attributable to jQuery. 

![Screenshot 2024-07-17 at 2 57 51 PM](https://github.com/user-attachments/assets/ac234d05-c176-4544-aeec-2a467fd0b57e)

**Comment by alexsch01** [comment]
https://github.com/jquery/jquery/issues/5430

JQuery 3.7.1 fixes this but a patch works
