### ISSUE TITLE
cy.clock affects creating UTCDateMini type

### ISSUE THREAD

**Issue by AleksandrKuznetsovEF** [cypress-io/cypress#29886]
### Current behavior

I have the following line of code:
```js
const dateUtc= new UTCDate(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
```

UTCDate is the type from date-fns/utc.

The type of dateUtc is UTCDateMini when I test feature manually and everything works correctly:
![image](https://github.com/user-attachments/assets/508cd8d3-af11-450d-9634-22743c49ae0d)

But in cypress test the type of this variable is a regular JS Date that leads to unexpected behaviour later:
![image](https://github.com/user-attachments/assets/85d7ea11-4379-44fa-8f42-a1fdcf723100)

This issue appear only when I use cy.clock in the cypress test. It's used in the following way in my test:
`cy.clock(new Date(2024, 5, 24), ["Date"]);`

### Desired behavior

I expect that `dateUtc` will have type `UTCDateMini` in cypress tests.

### Test code to reproduce

```js
import { UTCDate, UTCDateMini } from "@date-fns/utc";

describe("Test", () => {
  function getUtcDate(date: Date): UTCDateMini {
    const dateUtc = new UTCDate(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
    return dateUtc;
  };

  it("Test", () => {
    cy.clock(new Date(2024, 5, 24), ["Date"]);
    var dateUtc = getUtcDate(new Date());
  });
}
```

### Cypress Version

13.13.0

### Node version

20.15.1

### Operating System

Windows 11 Pro 23H2

**Comment by jennifer-shehane** [comment]
@AleksandrKuznetsovEF Where is this `UTCDate` function from?

**Comment by AleksandrKuznetsovEF** [comment]
@jennifer-shehane this is from "@date-fns/utc" library: https://github.com/date-fns/utc

**Comment by jennifer-shehane** [comment]
@AleksandrKuznetsovEF We don't use this plugin to create our Date underneath, so it won't match that type ever.
