### ISSUE TITLE
Run takes 5 minutes to start in bitbucket pipeline when using pnpm install instead of npm install

### ISSUE THREAD

**Issue by jackhipson300** [cypress-io/cypress#29882]
### Current behavior

When running the same cypress run command with pnpm instead of npm in a bitbucket pipeline, the process hangs for approximately 5 minutes before starting. When running the command locally with pnpm, there is no delay. 

I enabled debug logs and these two statements both indicate that they took 5 minutes.

![debug1](https://github.com/user-attachments/assets/caca20ab-5343-46db-96fb-b88ac893c1eb)
![debug2](https://github.com/user-attachments/assets/662af347-ba09-4c9e-b70e-c43bd9da6f96)

I've tried both the cypress/browser image with manual cypress install as well as the cypress/included image without manual cypress install and neither work. Including `pnpm install` or even the cached result is enough to reproduce the problem. As long as `pnpm install` is replaced with `npm install` there is no issue with `pnpm cypress run` regardless of whether cypress is listed in package.json or not. 

### Test code to reproduce

Here is the failing pipeline:
```
image: cypress/included

definitions:  
  services:
    docker:
      memory: 1024

pipelines:
  branches:
    '**':
      - step:
          size: 2x
          script:
            - corepack enable
            - corepack prepare pnpm@latest-9 --activate
            - pnpm install
            - pnpm run lint
            - pnpm run compile
            - pnpm run mobile-web & 
            - DEBUG=cypress:* pnpm cypress run --env CYPRESS_USER="$TEST_USER",CYPRESS_PASS="$TEST_PASS",Pool_Id="$POOL_ID",Client_Id="$CLIENT_ID" --browser chrome --spec ./src/cypress/e2e/mobile.spec.cy.ts
```

And here is the working pipeline with npm install:
```
image: cypress/included

definitions:  
  services:
    docker:
      memory: 1024

pipelines:
  branches:
    '**':
      - step:
          size: 2x
          script:
            - corepack enable
            - corepack prepare pnpm@latest-9 --activate
            - npm install
            - pnpm run lint
            - pnpm run compile
            - pnpm run mobile-web & 
            - DEBUG=cypress:* pnpm cypress run --env CYPRESS_USER="$TEST_USER",CYPRESS_PASS="$TEST_PASS",Pool_Id="$POOL_ID",Client_Id="$CLIENT_ID" --browser chrome --spec ./src/cypress/e2e/mobile.spec.cy.ts
```

### Cypress Version

Latest

### Node version

Latest

### Operating System

Linux

**Comment by MikeMcC399** [comment]
@jackhipson300 

- Possibly related to https://github.com/cypress-io/cypress/issues/27226

**Comment by jackhipson300** [comment]
@MikeMcC399 Yes adding .pnpm-store to gitignore fixed this for me as well. Would be nice if there was something either in the logs or in the documentation to make this more obvious. As mentioned in the other issue, there isn't much in the logs that would point towards this being the problem.

**Comment by MikeMcC399** [comment]
@jackhipson300 

- It's good that the information from #27226 enabled you to work around the issue!
- I'm not sure that this issue is currently qualified to say whether it needs documentation (if it is working as designed) or if it is a bug or an enhancement request.  According to the pnpm docs the default for [--store-dir](https://pnpm.io/cli/server#--store-dir) is `<home>/.pnpm-store` so I'm wondering if the default was used or if the location was changed.
