### ISSUE TITLE
Add Auto Cancellation only for specific tags

### ISSUE THREAD

**Issue by MateuszKobiera** [cypress-io/cypress#29892]
### What would you like?

We would expect a simple table with an option to choose different auto-cancellation settings depending on tags in Cypress Cloud. 

Example similar to Slack integration:
![image](https://github.com/user-attachments/assets/7ae5a008-c064-40f0-9729-0907faf7b5db)
![image](https://github.com/user-attachments/assets/43414ec9-a67f-478b-bcbc-4f5e07ec663b)
e.g.
| tag | failures before auto canceling | status |
| dev |                          5                     | ON     |
| staging |                    1                     | ON     |
| test-1   |                     10                   | OFF    |

### Why is this needed?

We are experiencing challenges with the auto-cancellation feature because we need different settings for different environments. For instance, in our staging environment, we require all tests to pass quickly for rapid feedback. Therefore, we want to set auto-cancellation to trigger after just one failure. However, in other development environments, auto-cancellation isn't as critical. Here, we might set it to trigger after five failures because we prefer to address each issue individually: we investigate a failure, fix or report it, rerun the tests, and repeat the process for subsequent failures. This avoids the disruption caused by multiple cancellations due to numerous initial bugs.

Our testing setup is quite extensive, with many different test suites running frequently, resulting in numerous commands. Currently, our infrastructure team passes the environment name as a variable. To use the auto-cancellation settings described in the Cypress documentation, we would need to create many new commands. Instead, it would be more efficient for us to configure these settings directly in Cypress Cloud, eliminating the need to involve the Infrastructure team for configuration changes.

For reference, see the Cypress documentation on specifying failures before auto-canceling in the CLI: [Cypress Documentation](https://docs.cypress.io/guides/cloud/smart-orchestration/run-cancellation#Specifying-failures-before-auto-canceling-in-the-CLI).

**Comment by jennifer-shehane** [comment]
Thanks for the feedback! I've forwarded this directly to our Cloud team where they'll capture the input. I'll close this issue as this repo is used for tracking issues/feature requests in the Cypress App.

**Comment by MateuszKobiera** [comment]
Oh, okay, thank you @jennifer-shehane!

**Comment by MateuszKobiera** [comment]
@jennifer-shehane Is there some issue created so I can track the status of this improvement?

**Comment by jennifer-shehane** [comment]
Unfortunately not, although the Cloud team is working on a way to track feature requests. You can check in via support@cypress.io and let them know you're interested in status updates on this.
