### ISSUE TITLE
E2E Docker Compose cy.intercept

### ISSUE THREAD

**Issue by zakbaig** [cypress-io/cypress#29914]
### What would you like?

I'd like to monitor HTTP request and responses between Docker containers from within Cypress. Using Docker Compose I stand up 3 micro-services (these micro-services together represent the full E2E application) and I would love to be able to use cy.intercept to check whether a certain container calls a certain endpoint and another container responds with a certain response object.

**Comment by jennifer-shehane** [comment]
I'd suggest checking out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

This issue is reserved for the investigation of bugs with Cypress, so we'll close this issue.
