### ISSUE TITLE
Log Cypress commands during 'cypress run'

### ISSUE THREAD

**Issue by vcamposs** [cypress-io/cypress#2991]
Hello!
I need logs of actions in headless mode, just for see wich step broke. I saw "DEBUG=cypress:*" but is too much information. Informations like left side of UI mode on headless mode will be perfect.

There are some config to do that?

Thaks!

**Comment by jennifer-shehane** [comment]
Yes, you can filter the debug log to a specific Cypress module, but we do not currently have support for logging the commands in headless as they are logged from the command log. @bahmutov made a plugin to log commands on test failure that you may find useful as a workaround today. https://github.com/bahmutov/cypress-failed-log

**Comment by vcamposs** [comment]
Awsome ! Tks !
