### ISSUE TITLE
Outdated run instructions after binary install

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29935]
### Current behavior

Cypress binary installation may output the following instructions after completion:

```text
You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress
```

1. This instruction does not work on a default installation of Yarn Modern
2. The link https://on.cypress.io/installing-cypress is about installing Cypress, not about running it.

- A resolved documentation issue also described compatibility issues in detail in https://github.com/cypress-io/cypress-documentation/issues/5382

### Desired behavior

Cypress binary installation should provide instructions which are correct and up-to-date for each of the supported package managers. So either list these out explicitly:

| Package Manager | Command                  |
| --------------- | ------------------------ |
| npm             | `npx cypress open`       |
| Yarn            | `yarn cypress open`      |
| pnpm            | `pnpm cypress open` |

and / or provide a link which describes how to run Cypress:

- https://on.cypress.io/opening-the-app  or
- https://on.cypress.io/command-line 

### Test code to reproduce

Using Yarn Modern defaults:

```shell
corepack disable
npm install yarn@latest -g
mkdir cy-yarn-modern
cd cy-yarn-modern
git init
yarn set version stable
yarn init -y
yarn add cypress --dev
yarn cypress install --force
```

### Cypress Version

`13.13.1`

### Node version

`v20.16.0` LTS

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

```shell
$ yarn cypress install --force

Cypress 13.13.1 is installed in /home/mike/.cache/Cypress/13.13.1

Installing Cypress (version: 13.13.1)

✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation /home/mike/.cache/Cypress/13.13.1

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

$ node_modules/.bin/cypress open
bash: node_modules/.bin/cypress: No such file or directory
```

### Other

https://github.com/cypress-io/cypress/blob/0d5065a10646b7a4adf49a613553fef96210bc99/cli/lib/tasks/install.js#L57-L63

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Yah the good ole' days of needing this are over. Feel free to update in a PR. The trickiest part with these updates is updating the CLI snapshots since that needs to be manually updated and committed. That process should be explained in the cli/README.md though.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thanks for the confirmation and tips! I'll put it on my to-do list.

The problem is not so much visible these days either as lifecycle scripts are no longer executed in the foreground by default and so mostly the text is not displayed. Exceptions are:

- explicit use of npm option [--foreground-scripts](https://docs.npmjs.com/cli/v10/commands/npm-install#foreground-scripts)
- use of `cypress install --force`
- use of `cypress cache clear` / `cypress install`

**Comment by MikeMcC399** [comment]
- PR #29957 submitted to resolve this issue
