### ISSUE TITLE
Remove support for glibc < 2.28

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29930]
### What would you like?

For the next major version of Cypress, support for Linux systems with the `glibc` library < `2.28` should be removed. This includes:

| OS version                           | GLIBC version                           | EOL           |
| ------------------------------------ | --------------------------------------- | ------------- |
| CentOS Linux release 7.9.2009 (Core) | ldd (GNU libc) 2.17                     | June 30, 2024 |
| Amazon Linux release 2 (Karoo)       | ldd (GNU libc) 2.26                     | June 30, 2025 |
| Ubuntu 18.04.6 LTS                   | ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27 | May 31, 2023  |
| RHEL 7                               | 2.17                                    | June 30, 2024 |

### Why is this needed?

- The minimum supported version of Node.js is `18.x` (Node.js `16.x` reached [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on Sep 11, 2023).
- [Node.js 18](https://github.com/nodejs/node/blob/v18.x/BUILDING.md#platform-list) specifies `glibc` >= `2.28` for both `x64` and `arm64` architectures.

### Other

The [Cypress 13.0.0 changelog](https://docs.cypress.io/guides/references/changelog#13-0-0) has already deprecated Node.js `16`

> Node 14 support has been removed and Node 16 support has been deprecated. Node 16 may continue to work with Cypress v13, but will not be supported moving forward to closer coincide with [Node 16's end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) schedule. It is recommended that users update to at least Node 18.

[Installing Cypress > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System) contains the text:

> We recommend that users update to at least Node.js 18.x. For related reasons, Cypress deprecates the use of Linux operating systems with library glibc versions 2.17 - 2.27. The Linux CLI command ldd --version displays your glibc version.

- Relates to https://github.com/cypress-io/cypress/issues/29601
- Relates to https://github.com/cypress-io/cypress/issues/29925

**Comment by jennifer-shehane** [comment]
This will be released in Cypress 14.
