### ISSUE TITLE
Infinite re-renders when trying to authenticate on Azure Static Web App

### ISSUE THREAD

**Issue by marc-niclas** [cypress-io/cypress#29942]
### Current behavior

We are using cypress to test against a production instance of a Azure Static Web App. This is not an issue with another Azure login flow, as we do not have this issue with our other app. I believe it might be because Azure is redirecting itself immediately upon connection to the host URL and this is somehow interacting badly with the test runner.

Immediately upon `cy.visit(host)`, the test runner starts adding `iframe-request-id=...id...` to the URL infinitely, until the browser blows up because the URL gets too long. It's not an issue with the actual code, since we are not even getting to `cy.origin` before it starts blowing up.

![image](https://github.com/user-attachments/assets/84d468f2-235d-4817-bfaa-2f3d8cd0ec1a)

### Test code to reproduce

```
Cypress.Commands.add('loginToAAD', (email: string, password: string, token: string, env: string) => {
  const host = 'https://test.app.com'
  const args = { email, password, token }
  cy.session(
    `aad-${email}`,
    () => {
      cy.visit(host)

      // cy.origin code would follow here to login to login.microsoftonline.com but it's not getting there before it blows up.
    }),
});
```

### Cypress Version

13.11.0

### Node version

20.12.0

### Operating System

macOS 14.2

### Debug Logs

```shell
`(uncaught exception)Error: Uncaught [Retry 0] Failed to load external resource ['https://aadcdn.msftauth.net/shared/1.0/content/js/ConvergedLogin_PCore_Q3A1xKaK6oPrhbQSUwvJBQ2.js'], reloading from fallback CDN endpoint`
```

**Comment by ThanhLNP** [comment]
do you have this
defineConfig({
...
e2e: {
...
experimentalModifyObstructiveThirdPartyCode: true
},
...

**Comment by marc-niclas** [comment]
@ThanhLNP yes I do, should have mentioned that.

I worked with cypress support to get this resolved so in case it helps anyone else, this is what ended up working:
```js
  it('works', () => {
    cy.origin('login.microsoftonline.com', () => {
      cy.visit('/') // the base URL being our "production" testing instance
    })
  })
```

**Comment by shivgun** [comment]
Hi @marc-at-brightnight a Cypress newbie here. I'm getting exactly the same issue. But I could not understand your fix.
Is your solution as below?

cy.visit(https://test.app.com/web/testService)
  it('works', () => {
    cy.origin('login.microsoftonline.com', () => {
      cy.visit('/')
    })
  })

Thanks

**Comment by TommmLe** [comment]
```
export const login = (username, password) => {
    cy.visit('/');

    // Login to your AAD tenant.
    cy.origin(
        'login.microsoftonline.com',
        {
            args: {
                username,
                password
            }
        },
        ({ username, password }) => {
            cy.get('input[type="email"]').type(username, {
                log: false
            });
            cy.get('input[type="submit"]').click();

            cy.get('input[type="password"]').type(password, {
                log: false
            });
            cy.get('input[type="submit"]').click();

            cy.url().then((url) => {
                if (url === 'https://login.microsoftonline.com/common/login') {
                    cy.get('#idBtn_Back').click();
                }
            });
        }
    );
...
};
```

I am using this and it is working fine

**Comment by shivgun** [comment]
Thanks @TommmLe
