### ISSUE TITLE
Spike: Can't upgrade Electron due to v8 snapshot issues

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#29960]
The v8 snapshot process is erroring out due to a bus error. There is a [bug in v8](https://issues.chromium.org/issues/345280736) that is causing this.

We need to get a handle on what to do if the bug doesn't get fixed. Ideas for what can be done (likely in order of priority/ease of implementation):

- Monitor the [v8 bug](https://issues.chromium.org/issues/345280736) for any traction
- Create and monitor a discussion in the [v8 forum](https://groups.google.com/g/v8-users/c/EVqC-7LK_hc) to try and get outside help on fixing the issue
- Manually modify the v8 snapshot script to see if there's anything that can we do to prevent the problem from occurring
- Try and fix the v8 code and contribute it back to either v8 or electron

**Comment by MikeMcC399** [comment]
https://issues.chromium.org/issues/345280736 now contains an update with a workaround suggestion.

**Comment by jennifer-shehane** [comment]
Closing, we implemented the workaround which works. Chromium has closed the issue, so there doesn't seem to be a way to followup on this.
