### ISSUE TITLE
Update Electron to version with supported Chromium version

### ISSUE THREAD

**Issue by MortenChristiansen** [cypress-io/cypress#29978]
### What would you like?

The currently bundled version of Electron uses a version of Chromium that is out of service. It would be great to have the version updated to the newest version - or at least a version that is supported.

### Why is this needed?

Using an old browser means you may run into things that do not work, including things that you would otherwise expect all modern browsers to support. This in turn mean that you cannot use the Electron browser for tests and have to setup your CI pipeline to include other browsers. Case in point, the latest version of the Shoelace component library (version 16) introduced a change that is incompatible with version 118 of Chromium which is shipping with Cypress (see https://github.com/shoelace-style/shoelace/issues/2130).

**Comment by MikeMcC399** [comment]
@MortenChristiansen 

- There is already an open PR to update. See https://github.com/cypress-io/cypress/pull/28959. Unfortunately the update has hit a roadblock. See https://github.com/cypress-io/cypress/issues/29960
- According to https://www.electronjs.org/docs/latest/tutorial/electron-timelines
    - Electron 27 entered EOL on Apr 16, 2024. 
    - Electron 29 enters EOL very soon on Aug 20, 2024
    - Electron 31 is the current stable version which is supported until Jan 2025.

**Comment by MortenChristiansen** [comment]
Thanks. It is great to hear that it is on your radar.

**Comment by jennifer-shehane** [comment]
Closing as duplicate
