### ISSUE TITLE
Update browser support of Cypress to last 3 major versions

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29977]
### What would you like?

- Remove support for Chrome 64 - 79
- Make Chrome 80 minimum version

### Why is this needed?

According to feedback in https://github.com/cypress-io/cypress-documentation/pull/5104#issuecomment-1614637130 from @mike-plummer Chrome 80 is needed for `cypress open` whereas Chrome 64 is sufficient for `cypress run`.

- Chrome itself only supports the stable version (see https://chromereleases.googleblog.com/ for releases) - currently `127.x`
- Chrome 64 was [released](https://chromereleases.googleblog.com/2018/01/stable-channel-update-for-desktop_24.html) in Jan 2018
- Chrome 80 was [released](https://chromereleases.googleblog.com/2020/02/stable-channel-update-for-desktop.html) in Feb 2020

Cypress 13 enforces a minimum of Chrome 64:

https://github.com/cypress-io/cypress/blob/ef7db3d3f0e1acc2617fef638612a8efad1dc021/packages/launcher/lib/known-browsers.ts#L3-L4

For consistent and simplified clarity of supported Chrome version, Chrome 80 should be made the minimum testable browser version.

### Other

- Relates to https://github.com/cypress-io/cypress/issues/29925
Follows on from
- https://github.com/cypress-io/cypress-documentation/issues/5446#issuecomment-2263340019
- https://github.com/cypress-io/cypress/issues/29925#issuecomment-2258223492

**Comment by MikeMcC399** [comment]
- According to smoke-tests in https://github.com/cypress-io/cypress/issues/30205#issuecomment-2339822046, Cypress `11.x` seems to be the last version which worked with Chromium 64 -79.

**Comment by jennifer-shehane** [comment]
We decided that moving forward, after Cypress 14, we will only officially support the last 3 major versions, from stable for all browsers (excluding Webkit which has a static version). So if the stable release of Chrome is at 129, we would officially support Chrome 127, 128, and 129. 

We will update the docs to reflect this. 

Additionally, we will remove the warning on browsers that are under the 'minimum' within the product, as this will be a moving target and does not gaurantee that Cypress WILL NOT work in earlier versions. It may work in earlier versions and we'll do our best to not use newer APIs that could break people using Cypress, but we will not triage or prioritize issues running browsers beyond 3 major versions after Cypress 14.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

- For Chromium-family and Firefox that sounds like a good approach. It ties in with what the browser owners support.

- WebKit is a special case and due to https://github.com/cypress-io/cypress/issues/29973 & https://github.com/cypress-io/cypress/issues/29954 it is unclear what Cypress is currently supporting. v16 is configured. v17 and v18 fail internal tests.
