### ISSUE TITLE
Clarify documentation of uses for aliased variable

### ISSUE THREAD

**Issue by edudelta** [cypress-io/cypress#2997]
Currently doc for **aliased variable** using as [documented](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html) should be rewritten. There is an unclear understanding that aliased variable could be accessed by **this**.XYZ without any issue. However, for those cases of aliased variable we can clarify necessity of using **cy.get(**'@ XYZ'**)**.
Thanks

**Comment by edudelta** [comment]
Hi!
I'm based in my impression and for others that worked with. As you can see [here](https://stackoverflow.com/questions/49431483/using-aliases-in-cypress) too.

According [Sharing Context](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context) we could use **this.XYZ** and going ahead it is dubious and might be highlighted with example.

> When using this.users we have access to it synchronously, whereas when using cy.get('@users') it becomes an asynchronous command.

> You can think of the cy.get('@users') as doing the same thing as cy.wrap(this.users).

Example of issue that can be raised
```javascript
function aliasNotFound() {
    cy.get('@example').then((example) => {
        if (example == 'exist') {
            cy.log('here is ok!') 
        }
    })
    if (this.example == 'exist') {
        cy.log('TypeError: Cannot read property example')
    }
}

describe('does not work', function () {
    beforeEach(function () {
        cy.wrap('exist').as('example')
    })
    it('just a example', function () {
        aliasNotFound()
    })
})
```

**Comment by dwelle** [comment]
Your example doesn't work because you're accessing `this.example` in a function whose `thisValue` is not bound the Mocha's shared context.

Only `before`, `after`, `beforeEach`, `afterEach`, and `it` functions have access to this context implicitly.

If you want to extend that access to your custom functions, you need to bind it:

```js
function aliasNotFound() {
    cy.get('@example').then((example) => {
        if (example == 'exist') {
            cy.log('here is ok!') 
        }
    })
    if (this.example == 'exist') {
        cy.log('TypeError: Cannot read property example')
    }
}

describe('does not work', function () {
    beforeEach(function () {
        cy.wrap('exist').as('example')
    })
    it('just a example', function () {
        aliasNotFound.call(this) // <---------------------- bind here
    })
})
```

**Comment by jennifer-shehane** [comment]
@dwelle Thanks for helping out, this is good advice. 😄 

If you have any other questions, try our [community chat](https://gitter.im/cypress-io/cypress), it's a good place to debug issues or ask about Cypress in general. Issues in our GitHub repo are reserved for potential bugs or feature requests.

**Comment by selangley-wa** [comment]
A summary of @dwelle's explanation above for the proper use of aliases would be a useful addition to the documentation.
