### ISSUE TITLE
Feature Request: Configurable Jira Project Pre-selection per Cypress Cloud Project

### ISSUE THREAD

**Issue by kriedel-ifm** [cypress-io/cypress#29986]
### What would you like?

As a user of Cypress Cloud with multiple projects integrated with Jira, I would like the ability to pre-select or default to a specific Jira project for each Cypress Cloud project when creating issues. This feature would streamline the process of creating Jira tickets from Cypress Cloud and reduce the potential for human error in project selection.

When creating a Jira ticket from Cypress Cloud, users must manually select the appropriate Jira project for each issue, regardless of which Cypress Cloud project they are working in.

### Why is this needed?

- Reduces time spent on manual project selection when creating Jira tickets.
- Minimizes the risk of creating tickets in the wrong Jira project.
- Improves workflow efficiency for teams working with multiple projects in both Cypress Cloud and Jira.

### Other

This feature would be particularly beneficial for organizations managing multiple projects or teams, each with their own dedicated Jira project.

**Comment by jennifer-shehane** [comment]
@kriedel-ifm Thanks for sharing how we could improve your workflow with our Jira integation. I've forwarded this to our Cloud team to consider. I'll close this issue as this repo is used for bugs in the App.
