### ISSUE TITLE
Cypress Cloud Jira Integration: Pre-formatted text not parsed in Jira tickets

### ISSUE THREAD

**Issue by kriedel-ifm** [cypress-io/cypress#29985]
### Current behavior

The pre-formatted text supplied by Cypress Cloud appears as plain text in Jira tickets, including markdown and code blocks. For example:
The link to Cypress Cloud is displayed as raw markdown: `[CYPRESS-RUN|https://cloud.cypress.io/projects/REDACTED/runs/52/overview/REDACTED]`

Code blocks are not formatted and appear as plain text:
```
text
{code:javascript}
   99 |   // Wait for submission and validate the success message
  100 |   cy.wait('@resourceLoading');
> 101 |   cy.get('h2').should('have.text', contactSuccessMessage);
      |                ^
  102 | }
  103 |
  104 | /**
{code}
```
### Desired behavior

The pre-formatted text should be correctly parsed and displayed in Jira tickets:
1. The Cypress Cloud link should be a clickable hyperlink.
2. Code blocks should be properly formatted and syntax-highlighted.
3. Other markdown elements (if any) should be rendered correctly.

### Test code to reproduce

1. Set up Cypress Cloud and Jira integration.
2. Run a Cypress test that fails.
3. Create a Jira ticket from Cypress Cloud for the failed test.
4. Open the created Jira ticket.
5. Observe that the pre-formatted text is not parsed and appears as plain text.

### Cypress Version

13.13.1

### Node version

20.15.1

### Operating System

Linux

### Other

- This issue occurs for all tickets created from Cypress Cloud.
- The same formatting issue persists when manually pasting the Cypress-provided content into a new Jira ticket, suggesting that the problem may be related to the format provided by Cypress Cloud.

**Comment by jennifer-shehane** [comment]
@kriedel-ifm Thanks for provided your feedback! I've forwarded this information over to the Cloud team to act on. I will close this issue since this repo is used for tracking issues in the App.

**Comment by danjohansenconsulting** [comment]
@kriedel-ifm The links to Cypress Cloud in JIRA are now clickable for new issues created via Cloud.  Thanks for raising this!
