### ISSUE TITLE
click behavior changed with recent update

### ISSUE THREAD

**Issue by jenkma02** [cypress-io/cypress#29989]
### Current behavior

I recently updated from 13.8.1 and we started having issues with async data not showing up when we're running our tests. an example can be seen in the videos below - 

https://d.pr/v/px3TiT - we click the `contact info` link, we're redirected to a new url, and the modal pops up but it doesn't contain the data that it should

### Desired behavior

https://d.pr/v/DxtrAh - here is the desired/expected behavior. we click the `contact info` link, we're redirected to a new url, and a modal automatically pops up populated with the user's profile data. 

this has worked up until now and also works manually.

### Test code to reproduce

```js
cy.get('a')
      .contains('contact info')
      .click()
      .then(() => {
        cy.wait('@getProfile')

        cy.get('.modal-edit-about').should('be.visible')

        cy.get('.modal-edit-about input[name="email"]').should('have.value', 'pvtemployer@outlook.com')
)}
```

### Cypress Version

13.13.2

### Node version

20.12.2

### Operating System

macOS sonoma14.6

### Other

This works correctly in Firefox, but not Chrome.

**Comment by jennifer-shehane** [comment]
@jenkma02 I honestly cannot see anything within our recent releases that could have impacted this behavior - looking through the [changelog](https://docs.cypress.io/guides/references/changelog).

Did anything else change on your side while updating? Any other dependencies? The Chrome version? Anything else?

**Comment by jenkma02** [comment]
@jennifer-shehane sorry about this, i was still trying to track down what could have changed on my end. unfortunately i never did figure it out, and it seems to be an issue with my local environment because in our "higher" environments, the issue isn't happening. if i run into it again/figure it out, i will add a note
