### ISSUE TITLE
Download file name error when Cypress>13.6.5

### ISSUE THREAD

**Issue by happyyaqing** [cypress-io/cypress#29993]

**Comment by jennifer-shehane** [comment]
@happyyaqing I don't know what would have changed this. We'll need a reproducible example provided in order to investigate.

**Comment by happyyaqing** [comment]
> @happyyaqing I don't know what would have changed this. We'll need a reproducible example provided in order to investigate.

This example can cause problems.

`it('test', () => {
    cy.visit('https://www.google.com/').then(() => {
        var link = document.createElement('a');
        link.href = 'https://files-dev.jiandaoyun.com/_/file/get_file?bucket=jdy-excel-export&key=7d5af950-f28f-4bed-a4cb-3956e8960206&filename=%E4%B8%AD%E6%96%87_20240814114335.xlsx&expires=1723693415&token=DXBeSqFCYb1F1nzmPdx52keqiiTKupPC445aB9DX:2O9IgDXDFNksJBena5Er8qL7gi4=';
        link.textContent = '点击这里下载文件';
        link.target = '_blank';
        Cypress.$('.SDkEP').append(link)
    })
    cy.contains('点击这里下载文件').click()
    cy.wait(2000)
})`

**Comment by jennifer-shehane** [comment]
I'm not seeing this in the example. I see the exact filename.

![Screenshot 2024-08-27 at 10 16 35 AM](https://github.com/user-attachments/assets/cb6b7d0e-ad10-4d96-aaf4-02f4e71cec81)

**Comment by happyyaqing** [comment]
close

**Comment by happyyaqing** [comment]
close
