### ISSUE TITLE
Cypress 3.1.4 - Windows regression - Unable to save videos due to EEXIST error

### ISSUE THREAD

**Issue by YOU54F** [cypress-io/cypress#3000]
### Current behavior:

With Cypress 3.1.4 installed on Windows via Git Bash, when running a test suite with the CLI runner , an error occurs when trying to rename the compressed video file

### Desired behavior:

It should save the video without error as per Cypress 3.1.3

### Steps to reproduce: (app code and test code)

1. Pull down the following repo:- https://github.com/YOU54F/cypressio-docker-typescript
2. Update package.json to state `"cypress": "3.1.4"`
3. Run npm install
4. Run npm run test:cypress
5. See error as below

Reverting to `"cypress": "3.1.3"` resolves the issue

```
- Started processing:   Compressing to 32 CRF
  - Finished processing:  C:\Users\grung\dev\cypressio-docker-typescript\e2e\cypress\videos\examples\pageObjects\login\login-cucumber.feature.mp4 (0 seconds)

{ Error: EEXIST: file already exists, link 'C:\Users\grung\dev\cypressio-docker-typescript\e2e\cypress\videos\examples\pageObjects\login\login-cucumber.feature-compressed.mp4' -> 'C:\Users\grung\dev\cypressio-docker-typescript\e2e\cypress\videos\examples\pageObjects\login\login-cucumber.feature.mp4'


  cause:
   { Error: EEXIST: file already exists, link 'C:\Users\grung\dev\cypressio-docker-typescript\e2e\cypress\videos\examples\pageObjects\login\login-cucumber.feature-compressed.mp4' -> 'C:\Users\grung\dev\cypressio-docker-typescript\e2e\cypress\videos\examples\pageObjects\login\login-cucumber.feature.mp4'


     errno: -4075,
     code: 'EEXIST',
     syscall: 'link',
     path: 'C:\\Users\\grung\\dev\\cypressio-docker-typescript\\e2e\\cypress\\videos\\examples\\pageObjects\\login\\login-cucumber.feature-compressed.mp4',
     dest: 'C:\\Users\\grung\\dev\\cypressio-docker-typescript\\e2e\\cypress\\videos\\examples\\pageObjects\\login\\login-cucumber.feature.mp4' },
  isOperational: true,
  errno: -4075,
  code: 'EEXIST',
  syscall: 'link',
  path: 'C:\\Users\\grung\\dev\\cypressio-docker-typescript\\e2e\\cypress\\videos\\examples\\pageObjects\\login\\login-cucumber.feature-compressed.mp4',
  dest: 'C:\\Users\\grung\\dev\\cypressio-docker-typescript\\e2e\\cypress\\videos\\examples\\pageObjects\\login\\login-cucumber.feature.mp4' }
Error: EEXIST: file already exists, link 'C:\Users\grung\dev\cypressio-docker-typescript\e2e\cypress\videos\examples\pageObjects\login\login-cucumber.feature-compressed.mp4' -> 'C:\Users\grung\dev\cypressio-docker-typescript\e2e\cypress\videos\examples\pageObjects\login\login-cucumber.feature.mp4'


error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Versions

Cypress 3.1.4
Git Bash 2.11.2(0.329/5/3)
Windows 10 Professional v1709 OS Build 16299.847
node v8.15.0

**Comment by jennifer-shehane** [comment]
The only thing that I can think of in the last release that only affected Windows was this PR https://github.com/cypress-io/cypress/pull/2937

**Comment by bahmutov** [comment]
there was also ffmpeg upgrade due to new FFMPEG for windows release, see https://github.com/cypress-io/cypress/issues/2990

**Comment by Saibamen** [comment]
Please retest with Cypress 3.1.5

**Comment by YOU54F** [comment]
Hi, thanks for the update. I've since sold my laptop which had this dev environment on, but I cloned the hard drive, so will stick that in another machine and retest with 3.1.5

I'll aim to get it retested by the end of the week. Thanks again all

**Comment by jennifer-shehane** [comment]
Closing. Please comment if this behavior is still present and we can reopen.

**Comment by YOU54F** [comment]
Rested on a different machine  and cannot reproduce across 3.13 - 3.1.5.

```
Cypress 3.1.4
Git Bash 2.11.2(0.329/5/3)
Windows 10 Professional v1709 OS Build 17763.253
node v8.15.0
```

Thanks for investigating all, 

locking deps is a good plan too so glad that is being implemented now 🤘
