### ISSUE TITLE
cy.type shouldn't perform actionability if subject is the currently focused element 

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3001]
If the subject to cy.type is focused, we shouldn't perform actionability because the user is already able to start sending keys to the element without needing to click/tab into it.

This allows apps to call .focus() on an otherwise covered/animating element and allow cypress to still type into it, just as a user would

**Comment by jennifer-shehane** [comment]
Fixing this fixes this situation also: https://github.com/cypress-io/cypress/issues/4420
