### ISSUE TITLE
Remove support for Create React App (CRA)

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#30028]
### What would you like?

Remove support for Create React App (CRA).

### Why is this needed?

[Create React App](https://create-react-app.dev/) is de-facto abandoned and unsupported.

- The last release was [v5.0.1](https://github.com/facebook/create-react-app/releases/tag/v5.0.1) on April 12, 2022.
- See https://github.com/facebook/create-react-app/issues/13393 which has received no comment from any maintainer.
- Deprecations, such as https://github.com/facebook/create-react-app/issues/11860, have not been addressed.

### Other

- https://github.com/cypress-io/cypress/issues/29925

**Comment by jennifer-shehane** [comment]
Thanks for opening. I added it to the v14 list.
