### ISSUE TITLE
Windows: Cypress.exe removed from local cache directory upon secondary npx run

### ISSUE THREAD

**Issue by philga7** [cypress-io/cypress#3003]
After installing 3.1.4 for Windows, once Cypress is ran via 'npx cypress ...', on secondary 'npx' execution, Cypress.exe is removed from local cache directory.

Any other ways to execute Cypress appear to provide no issues.

### Current behavior:

1. Install Cypress 3.1.4 (I do this via git for Windows: npm install cypress)
2. Execute 'npx cypress ...' at the command line
3. Once test is completed, execute 'npx cypress ...' a second time
4. Cypress stops after attempting to execute and C:\Users\[MyName]\AppData\Local\Cypress\Cache\3.1.4\Cypress no longer contains Cypress.exe

### Desired behavior:

Steps 1 - 3 occur, but Cypress does not delete its own executable.

### Steps to reproduce: (app code and test code)

Reproduced five times locally; three via CLI (git for Windows):
1. npm install cypress [--force]
2. npx cypress ...
3. Run a test (unless previous command was a test)
4. npx cypress ...

Workaround is to keep a copy of Cypress.exe and simply replace when Cypress removes.

### Versions

Cypress 3.1.4 only (3.1.3 works without issue)
Microsoft Windows 10 Pro
10.0.17134

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by swatantra15081986** [comment]
Hi @jennifer-shehane 
I am facing same issue.
