### ISSUE TITLE
Flaky test: Unrecognized expression

### ISSUE THREAD

**Issue by melmoubayed** [cypress-io/cypress#30032]
### Link to Cypress Cloud or CircleCI failure

https://github.com/cypress-io/cypress-realworld-testing-course-app

### Link to failing test in GitHub

https://github.com/cypress-io/cypress-realworld-testing-course-app

### Analysis

It is failing to pass back email-input from the getByData function

### Cypress Version

10.7.0

### Other

I was following a Cypress training video: https://www.youtube.com/watch?v=Q1rHmOYyGDo&lc=UgxrF5XyA4XG1Jp3jpB4AaABAg
and the trainer added the following in commands.ts

```js
Cypress.Commands.add("getByData", (selector) => {
    return cy.get('[data-test = $ {selector}]')
})
```
When I call the above from another file as follows:
```js
 cy.getByData('email-input').type("tom@aol.com")
```

I am getting the following error:
```
Syntax error, unrecognized expression: [data-test = $ {selector}]
```
Can someone help please!!

**Comment by jennifer-shehane** [comment]
Was the cy.get command supposed to use backticks instead of single quotes?

```js
Cypress.Commands.add("getByData", (selector) => {
    return cy.get(`[data-test = ${selector}]`)
})
```

**Comment by melmoubayed** [comment]
Hi Jennifer,

Thanks for getting back to me, this is the exact code from the training video:[cid:e142b2f5-7e50-44ae-a111-cfe2fc24d585]


Actually, the getByData was underlined in red when the trainer used it in his code but it still worked for him somehow, beats me!

Regards,
Mohamad
________________________________

**Comment by melmoubayed** [comment]
Hi Jennifer,

You were right, I used the backticks and now it is all good.
Much appreciated.

Mohamad
________________________________
