### ISSUE TITLE
CLI unit tests often break - and it is flake

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3004]
When building CLI on Circle the same 5 unit tests break, but when rerunning them pass

example build (renovate PR)

https://circleci.com/gh/cypress-io/cypress/43807 from workflow https://circleci.com/workflow-run/842085ba-85aa-4b7d-a20f-2b3dd58d4409

<img width="1343" alt="screen shot 2018-12-27 at 10 15 32 am" src="https://user-images.githubusercontent.com/2212006/50484903-d85f3600-09c0-11e9-8ac7-0605c4eae6f7.png">

all 5 errors come from `lib/tasks/verify`

Seems the error message gets confused - a completely different value of snapshot, like a previous test is not cleared correctly ...

```
-Error: No version of Cypress is installed in: /cache/Cypress/1.2.3/Cypress.app
+Error: The cypress npm package is installed, but the Cypress binary is missing.
```

The other error shows

```
 TypeError: os.platform.returns is not a function
```

but `os.platform` is stubbed in `spec_helper.coffee` which should run before each test

```
beforeEach(function () {
  sinon.stub(os, 'platform')
  sinon.stub(os, 'release')
  sinon.stub(util, 'getOsVersionAsync').resolves('Foo-OsVersion')
})
```

**Comment by bahmutov** [comment]
Comparing successful and failing test run does not show anything obviously wrong, maybe this 
```
(node:580) Warning: a promise was rejected with a non-error: [object Object]
      ✓ resolves undefined if not verified
      ✓90m can accept custom binaryDir
```
which is a warning flag

**Comment by bahmutov** [comment]
Rerunning the workflow job failed first time, but succeeded on the second attempt in https://circleci.com/workflow-run/3dfc30aa-b0ee-4daf-a874-6adc3efc7495

**Comment by Bkucera** [comment]
@bahmutov this is could have something to do with mockfs, possibly a missing `mockfs.restore` ?

**Comment by bahmutov** [comment]
possible @Bkucera

**Comment by jennifer-shehane** [comment]
Closing this as resolved. Please reopen if these tests are still flaky.
