### ISSUE TITLE
Outdated Contributing instructions "Docker for built binary"

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#30071]
### What would you like?

The instructions in [CONTRIBUTING > Docker for built binary](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#docker-for-built-binary) should work with current versions of Cypress 13.x, Cypress Docker images and Docker Desktop. They require an overhaul to be useful.

### Why is this needed?

Instructions in [CONTRIBUTING > Docker for built binary](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#docker-for-built-binary) are outdated and no longer work.

1. The instructions specify using `cypress/base:8` which uses Node.js `v8.12.0`. This is not compatible with Cypress `13.x` which requires a minimum of Node.js `16.x` to run, and a minimum of Node.js `18.x` to be supported.
2. The `CMD` definition of `cypress/base` images is now `bash` by default (from `debian:12-slim`) and does not need to be explicitly included in the commmand line
3. Instead of `$PWD`, now `.` is allowed which has better cross-platform capability.
4. A reference to https://on.cypress.io/advanced-installation#Install-pre-release-version is missing, which explains how to find beta release URLs
5. There is no explanation about how to find the `cypress.zip` URL and it should be checked if separate steps for installing the Cypress binary are necessary.
6. The directory `/tmp/test-folder/node_modules/cypress/cypress-cache` in the example is not created.

**Comment by jennifer-shehane** [comment]
Definitely open to updates here.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Definitely open to updates here.

I'll see if I can work it out!

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

I suggest to completely remove the section [CONTRIBUTING > Docker for built binary](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#docker-for-built-binary). The section is out-of-date and unnecessary.

The section appears to be referring to running pre-release (beta) versions built via the PR merge process (see https://on.cypress.io/advanced-installation#Install-pre-release-version). These versions are installed and run exactly as final releases, so there is no need for special instructions.
