### ISSUE TITLE
Frequent InvalidStateError when running tests in 3.1.4 update

### ISSUE THREAD

**Issue by Dan195** [cypress-io/cypress#3008]
### Current behavior:
When running certain tests, I will frequently get an InvalidStateError on tests that worked previously in 3.1.3. Additionally, this does not happen everytime the test is run. Sometimes the test will pass, but many times this error will happen. 

`InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').`

### Desired behavior:
The test should pass without any errors. 
Consistent behavior from one test run to another.

### Steps to reproduce: (app code and test code)

The below test is on a page that loads a HERE map, and consequently receives many XHR responses upon loading. 
Example code of a test case that resulted in this error, but worked in previous Cypress versions.
```js
const Accounts = require('../../constants/accounts');
const Routes = require('../../constants/routes');

describe('Switching organizations, then refreshes the page', () => {
  before(() => {
    cy.viewport('macbook-15');
    cy.visit(Routes().dashboardBaseUrl);
    cy.get('input[name=email]').type(Accounts().email);
    cy.get('input[name=password]')
      .type(Accounts().pw)
      .type('{enter}');
  });

  it('should default back to original organization view upon refresh', () => {
    context('switch from parent organization to child organization', () => {
      cy.get('[data=subscribedName]').should(
        'have.text',
        'organization name'
      );

      //open the dropdown
      cy.get('[data=dropdown-toggle]').click();

      //Click on the first child organization
      cy.get('[data=orgName]:first').click();

      //organization title should have changed
      cy.get('[data=subscribedName]').should(
        'have.text',
        'blacklist'
      );
    });

    cy.reload();
    cy.get('[data=subscribedName]').should(
      'have.text',
      'organization name'
    );
  });
});

```

**Comment by jennifer-shehane** [comment]
Hey @Dan195, does this happen during `cypress open`, `cypress run`, or both? 
Could you also specify OS/browser being used?

**Comment by jennifer-shehane** [comment]
Do you have a screenshot of the command log that you could provide? Also any console logs/stack traces from the console dev tools may be helpful. 

A reproducible example would be the most ideal thing to provide, but more logging information will at least be better than none.

**Comment by Dan195** [comment]
Is there a way I can send this privately?

**Comment by jennifer-shehane** [comment]
Yes. Email support@cypress.io

**Comment by zerdos** [comment]
I am having the same issue - running the tests inside docker, with cypress run command

**Comment by Dan195** [comment]
> Yes. Email [support@cypress.io](mailto:support@cypress.io)

Sent just now.

**Comment by GordonTester** [comment]
Experiencing the same issue across multiple test suites, only started happening recently (after the 26th December).

**Comment by jennifer-shehane** [comment]
Thanks so much everyone for providing details of this regression!

I've created a repo demonstrated this bug: https://github.com/jennifer-shehane/array-buffer-bug

It seems this error throws when there are XHR requests of content-type `arraybuffer` that are aborted. This also makes sense since we made several changes to how we handle aborted requests in 3.1.4. 

Basic example within repo:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Array Buffer</title>
  </head>
  <body>
    <h1 class="page-title">Array Buffer Check</h1>
    <script type="text/javascript">
      (function () {
        var xhr = new XMLHttpRequest()
        xhr.responseType = 'arraybuffer'
        xhr.open('get', '/fake/data')
        xhr.send()
        xhr.abort()
      }())
    </script>
  </body>
</html>
```

```js
it('throws error on aborted request with type arraybuffer', () => {
  cy.visit('index.html')
})
```

**Screenshot**
<img width="555" alt="screen shot 2019-01-03 at 3 36 34 pm" src="https://user-images.githubusercontent.com/1271364/50630004-62813e80-0f6d-11e9-8610-d033d7ab9a1d.png">

**Comment by jennifer-shehane** [comment]
Problematic code is here - this should check that the responseType is '' or 'text' before checking responseText. https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/server.coffee#L34

**Comment by Akshaya0309** [comment]
Experiencing the same issue. 
When  you guys are planning to fix this?

**Comment by TerryMooreII** [comment]
We have a similar error since the 3.1.4 update 
```
Error: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').
    at isAbortedThroughUnload (http://localhost:9999/__cypress/runner/cypress_runner.js:62461:57)
    at onReadyStateFn (http://localhost:9999/__cypress/runner/cypress_runner.js:62816:17)
    at XMLHttpRequest.<anonymous> (http://localhost:9999/__cypress/runner/cypress_runner.js:62773:25)
```
The difference is `text' (was 'blob')` instead of `arraybuffer`

Tests only fail when running cypress run.  The tests do run successful with cypress open (chrome 71)

**Comment by jennifer-shehane** [comment]
I've started a PR to fix this, so hopefully should get out in 3.1.5 https://github.com/cypress-io/cypress/pull/3054

**Comment by VSathyamoorthy** [comment]
I have also been hit by this issue, thanks for fixing it.

**Comment by WSmonkey** [comment]
Same here. Spent a whole day debugging...

**Comment by praveenkp11** [comment]
Hi  @jennifer-shehane,

We are waiting for 3.1.5 release.
When will 3.1.5 be released ?
Will it be released by end on this month ?

**Comment by dubbha** [comment]
Would 3.1.5 also fix the `text' (was 'blob')` issue?

**Comment by mattrlong** [comment]
I've also seen similar fails since upgrading to 3.1.4, however mine "was Json": 
`Error: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').`

Seems related, is anyone else able to confirm if the fixes in 3.1.5 will also resolve this?

**Comment by katerynae** [comment]
I am having the same issue with "json" response

```Error: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json'). ```

**Comment by lessp** [comment]
I pulled down the issue-branch and built it locally. We had the `(was ’blob’)` which was solved.

Looking at the changes in the fix-branch, it looks like every `(was ’xxx’)` will be covered.

Thanks a bunch @jennifer-shehane 🎉

**Comment by bielcapanema** [comment]
Any plans to release the fix?

**Comment by kamil-rogowski-gc** [comment]
I have the same situation -> "cypress": "^4.0.1". using cypres run and open.
` cy.server()
  cy.route('GET', 'api/dic').as('dic')
  cy.visit('/')
  cy.wait('@dic').then((xhr) => {
            expect(xhr).to.have.property('status', 200)
        })
`
and error 
`InvalidStateError: Failed to read the 'responseXML' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'document' (was 'text').`

**Comment by kamiloski** [comment]
I have the same situation -> "cypress": "^4.0.1". using cypres run and open.
    cy.server()
     cy.route('GET', 'api/dic').as('dic')
     cy.visit('/')
     cy.wait('@dic').then((xhr) => {
               expect(xhr).to.have.property('status', 200)
           })
   
   and error 
   `InvalidStateError: Failed to read the 'responseXML' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'document' (was 'text').`

**Comment by pchorus** [comment]
@kamiloski I have the same issue after upgrading to Cypress 4.0.1.

**Comment by kamiloski** [comment]
@pchorus workaround
```
        cy.wait(['@dictionary').then((xhr) => {
            expect(xhr.status).to.eq(200)
        })
```

**Comment by alastair-todd** [comment]
@jennifer-shehane I too have just run into this issue after 4.0.1 update

```cy.route({ method: 'GET', url: `**?name=${filterText}` }).as(aliases.typeaheadLookupRequest);```

...

`cy.waitAlias(aliases.typeaheadLookupRequest).should('have.property', 'status', 200);`

![image](https://user-images.githubusercontent.com/595192/74607053-4850e400-50cd-11ea-8694-48a63a95990f.png)

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
