### ISSUE TITLE
Typescript config file is invalid with Node 22.7

### ISSUE THREAD

**Issue by thomashexagon** [cypress-io/cypress#30084]
### Current behavior

When using a .ts extension for your config file, start up fails. Changing it to. js fixes this.
This started happening to me from node 22.7, anything before that it works fine.

My closest and root package.json have both type: module.

`Your configFile is invalid: ./cypress.config.ts`

### Desired behavior

Compile and run tests

### Test code to reproduce

Have a config file with .ts extension and running node v22.7

Config file looks as this but shouldn't matter, it worked for 3 months or longer.

```js
import { defineConfig } from 'cypress';
import codeCoverageTask from '@cypress/code-coverage/task';

export default defineConfig({
    viewportHeight: 1000,
    viewportWidth: 1000,
    component: {
        devServer: {
            framework: 'react',
            bundler: 'vite',
        },
        setupNodeEvents(on, config) {
            codeCoverageTask(on, config);
            return config;
        },
    },
});
```

### Cypress Version

13.13.3

### Node version

v22.7.0

### Operating System

macOS 14.6.1

### Debug Logs

```shell
@boa/shared-ui:component-test:ci: Your configFile is invalid: /Users/xxxx/Sites/cit-frontend/packages/shared-ui/cypress.config.ts
@boa/shared-ui:component-test:ci:
@boa/shared-ui:component-test:ci: It threw an error when required, check the stack trace below:
@boa/shared-ui:component-test:ci:
@boa/shared-ui:component-test:ci: Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
@boa/shared-ui:component-test:ci: Please open an issue with this stack trace at https://github.com/nodejs/node/issues
@boa/shared-ui:component-test:ci:
@boa/shared-ui:component-test:ci:     at assert (node:internal/assert:14:11)
@boa/shared-ui:component-test:ci:     at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:329:5)
@boa/shared-ui:component-test:ci:     at new ModuleJobSync (node:internal/modules/esm/module_job:313:34)
@boa/shared-ui:component-test:ci:     at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:314:11)
@boa/shared-ui:component-test:ci:     at loadESMFromCJS (node:internal/modules/cjs/loader:1381:24)
@boa/shared-ui:component-test:ci:     at Module._compile (node:internal/modules/cjs/loader:1503:5)
@boa/shared-ui:component-test:ci:     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
@boa/shared-ui:component-test:ci:     at Module.load (node:internal/modules/cjs/loader:1317:32)
@boa/shared-ui:component-test:ci:     at Module._load (node:internal/modules/cjs/loader:1127:12)
@boa/shared-ui:component-test:ci:     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
@boa/shared-ui:component-test:ci:     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
@boa/shared-ui:component-test:ci:     at Module.require (node:internal/modules/cjs/loader:1339:12)
@boa/shared-ui:component-test:ci:     at require (node:internal/modules/helpers:126:16)
```

### Other

Node changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#2024-08-22-version-2270-current-rafaelgss

**Comment by jennifer-shehane** [comment]
We're looking at this. I was able to recreate this.

**Comment by AtofStryker** [comment]
I created a [reproduction repository](https://github.com/AtofStryker/cypress-issue-30084). Based on the node [release notes](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md?rgh-link-date=2024-08-22T15%3A58%3A27Z#2024-08-22-version-2270-current-rafaelgss) the `--experimental-detect-module` flag is now enabled by default which doesn't play nicely with the experimental `ts_node` module loader that cypress is using under the hood. 

Turning it off via `--no-experimental-detect-module` on the child process looks to fix the issue.  I built a binary on https://github.com/cypress-io/cypress/commit/eabc7887a16a040d3fac87feb8cc6eed6eaa1f19 to test this and looks to fix the problem on this [branch](https://github.com/AtofStryker/cypress-issue-30084/compare/fixed_with_binary?expand=1).
