### ISSUE TITLE
Failed spec not shown in slack, when tags are added to test run

### ISSUE THREAD

**Issue by sszemeresky** [cypress-io/cypress#30093]
### Current behavior

if `--tag` is used to run tests and some tests fail, there is no information on which test failed sent to slack channel using default slack integration

### Desired behavior

same as running tests without `--tag`, when some specs fail, slack shows which specs failed

### Test code to reproduce
```
npx cypress-tags run 
          --browser chrome 
          --record 
          --parallel 
          --key ${{inputs.cypressRecordKey}} 
          --tag ${{inputs.tags}}
          --ci-build-id GCP-${{inputs.tags}}-${{inputs.partner}}-${{inputs.buildEnv}}-${{inputs.appAlias}}-${{github.run_number}}
```
### Cypress Version

13.13.3

### Node version

21.5.0

### Operating System

Win10

### Debug Logs

```shell
unable to get slack integration logs
```

**Comment by jennifer-shehane** [comment]
@sszemeresky Thanks for reporting this issue. We did make some changes to Slack notifications which we've now reverted while we investigate. You should now see the failed specs on the next notifications.

**Comment by emilyrohrbough** [comment]
@sszemeresky Would you mind sharing how you leverage this data in your workflows? How do you use this in your day-to-day? Did you find the new report data helpful?
