### ISSUE TITLE
element snapshots should highlight client rects instead of bounding rect

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3010]
we need to update the logic when showing the rectangle border box (during snapshot reverts) to show the client rects instead of the whole bounding box

_Originally posted by @brian-mann in https://github.com/cypress-io/cypress/pull/2981#issuecomment-449917876_

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
