### ISSUE TITLE
Function is not called in Cy.origin 

### ISSUE THREAD

**Issue by MurleeDass** [cypress-io/cypress#30116]
### Current behavior

when I call function in cy.origin, it gives error function

### Desired behavior

It should call function inside origin 

### Test code to reproduce
```js
const searchFlight = async () => { cy.get('#sel-departure-0').should('be.visible', 'Abreise').type('FRA');
}

if (Preprod === url.preprod_url_de) {
  cy.origin('www.example.com', () => { 
    searchFlight();
  })
} 

else {
  searchFlight(); 
}
```

### Cypress Version

13.6.2

### Node version

v20.8.1

### Operating System

MacOS 

### Debug Logs

```shell
Variables must either be defined within the cy.origin() command or passed in using the args option.

Using require() or import() within the cy.origin() callback is not supported. Use Cypress.require() to include dependencies instead, but note that it currently requires enabling the experimentalOriginDependencies flag.
```

**Comment by jennifer-shehane** [comment]
@MurleeDass You'll need to pass that variable in through the args option of cy.origin like the error describes. https://docs.cypress.io/api/commands/origin#Using-dynamic-data-in-a-secondary-origin

**Comment by MurleeDass** [comment]
Thank you @jennifer-shehane  for your response. 

I don't wanna go with the args way.
As My functions are very much complex and I have more than 100 different functions. which I just want to call 

Is there any approach where I should be allowed to call simply Function in origins?

**Comment by jennifer-shehane** [comment]
@MurleeDass No. We have to do a lot of work behind the scenes to ensure the context of previous functions exist when the entirety of the window/URL has changed. This was designed to allow that.
