### ISSUE TITLE
experimentalJustInTimeCompile is not shown as enabled under cy open > settings

### ISSUE THREAD

**Issue by muratkeremozcan** [cypress-io/cypress#30126]
### Current behavior

Trying out https://github.com/cypress-io/cypress/issues/29244, we add `experimentalJustInTimeCompile` under component property, but under app settings the feature is not shown as enabled. There is also no title or description under the experiment.

### Desired behavior

The experimentalJustInTimeCompile shows as enabled under app settings, so we can confirm that things are working and an i18n description is present

### Test code to reproduce

```bash
git clone git@github.com:muratkeremozcan/react-cypress-ts-vite-template.git
cd react-cypress-ts-vite-template.
yarn 

yarn cy:open-e2e # or ct
```

View Settings, and `experimentalJustInTimeCompile`. 

<img width="1984" alt="Screenshot 2024-08-28 at 9 54 35 AM" src="https://github.com/user-attachments/assets/edc97d7d-7940-4a59-8ebd-6bb0cb465efc">

### Cypress Version

13.14.0

### Node version

20

### Operating System

macOS 14.6.1

### Other

We can log out the object in console and see it there, but not in the app itself.

**Comment by jennifer-shehane** [comment]
@muratkeremozcan Thanks for reporting. Seems adding this to this view was overlooked. We'll get a fix out for it in the next release. 

Let us know your feedback on the actual feature in [this github discussion](https://github.com/cypress-io/cypress/discussions/30024). I know you've been asking for help around this for a while.

**Comment by muratkeremozcan** [comment]
> @muratkeremozcan Thanks for reporting. Seems adding this to this view was overlooked. We'll get a fix out for it in the next release.
> 
> Let us know your feedback on the actual feature in [this github discussion](https://github.com/cypress-io/cypress/discussions/30024). I know you've been asking for help around this for a while.

I am all over it, will report soon.

**Comment by muratkeremozcan** [comment]
@jennifer-shehane @AtofStryker 

I tried this out locally in our app with 1.5k component tests. 

Without the flag, the startup time was 2:10.
With it, down to 30 seconds. Fantastic improvement. This will save plenty time in CI. 

I have to get the PR in to prove out CI is fine, but that should be fine.

**Comment by AtofStryker** [comment]
> @jennifer-shehane @AtofStryker
> 
> I tried this out locally in our app with 1.5k component tests.
> 
> Without the flag, the startup time was 2:10. With it, down to 30 seconds. Fantastic improvement. This will save plenty time in CI.
> 
> I have to get the PR in to prove out CI is fine, but that should be fine.

CI might take a bit longer to run since we need to compile each spec before running, but there shouldn't be any chunk load errors present. If CI is more reliable, but ultimately takes longer to run, smart orchestration should be more effective here and throwing more parallel workers at the problem should ultimately reduce times as well as an option.

**Comment by muratkeremozcan** [comment]
> > @jennifer-shehane @AtofStryker
> > I tried this out locally in our app with 1.5k component tests.
> > Without the flag, the startup time was 2:10. With it, down to 30 seconds. Fantastic improvement. This will save plenty time in CI.
> > I have to get the PR in to prove out CI is fine, but that should be fine.
> 
> CI might take a bit longer to run since we need to compile each spec before running, but there shouldn't be any chunk load errors present. If CI is more reliable, but ultimately takes longer to run, smart orchestration should be more effective here and throwing more parallel workers at the problem should ultimately reduce times as well as an option.

Makes sense. Previously because of the set startup time, parallelization had diminishing returns.
Ex: Startup 2.5 mins, tests take 5 mins.

If we parallelized more, the 5 minutes would not reduce further.

Now the startup is 30 secs, but tests take about 8. So we can benefit more from parallelization.

**Comment by AtofStryker** [comment]
@muratkeremozcan Does the experiment show as enabled when you open via `cy:open-ct`? The experiment shows an enabled under CT but not under e2e since it is a CT only config when I run the reproduction.
<img width="1445" alt="Screenshot 2024-08-28 at 3 18 05 PM" src="https://github.com/user-attachments/assets/caadd710-cd49-4fa3-a5d4-41e3b06873a0">

**Comment by muratkeremozcan** [comment]
> @muratkeremozcan Does the experiment show as enabled when you open via `cy:open-ct`? The experiment shows an enabled under CT but not under e2e since it is a CT only config when I run the reproduction. <img alt="Screenshot 2024-08-28 at 3 18 05 PM" width="1445" src="https://private-user-images.githubusercontent.com/3980464/362422401-caadd710-cd49-4fa3-a5d4-41e3b06873a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzM0NDYsIm5iZiI6MTcyNDg3MzE0NiwicGF0aCI6Ii8zOTgwNDY0LzM2MjQyMjQwMS1jYWFkZDcxMC1jZDQ5LTRmYTMtYTVkNC00MWUzYjA2ODczYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTkyNTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjExMzMxNjQ4NDVhZmJiMzdjMmZjNDgwMzNkNzExMzQyMmM0YjQ3Njk2MmY5NGM2N2YwNGJlZDdhODVhNDkzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-nM0BwAxJaWZQ5T-rfWFOF1cvSQ4Jqn1vglo0mcGGlU">

You are correct. The focused scripts I have are actually doing a good job of isolating the flags per the test type, and I neglected actually checking the CT mode when enabling the CT-only relevant flag. 
This flag is different to other experimental flags where you cannot enable it at base level. 

Closing the issue. I will see myself out.
