### ISSUE TITLE
CircleCI Route Stub Unknown Failure

### ISSUE THREAD

**Issue by joshmedeski** [cypress-io/cypress#3013]
### Current behavior:

A very specific stubbed route is erroring out ONLY in the CircleCI environment.

### Desired behavior:

Stubbed routes should work as expected.

### Steps to reproduce: (app code and test code)

```ts
  it('should show an error message if the email is invalid', () => {
    cy.route({
      method: 'POST',
      url: '/users/password/email',
      response: 'fixture:users-password-email-post-422-email-invalid.json',
      status: 422
    }).as('usersPasswordEmailPostEmailInvalid');
    cy.get('input[name=email]').type('nobody');
    cy.get('button[type=submit]').click();
    cy.wait('@usersPasswordEmailPostEmailInvalid');
    cy.contains('Invalid email format').should('be.visible');
  });
```

Running the test in CircleCI gives the following error:
<img width="1680" alt="screen shot 2018-12-27 at 2 50 34 pm" src="https://user-images.githubusercontent.com/2036594/50494082-d314e200-09e6-11e9-9bae-88d90f81655d.png">
<img width="1680" alt="screen shot 2018-12-27 at 2 50 44 pm" src="https://user-images.githubusercontent.com/2036594/50494083-d5773c00-09e6-11e9-9e51-cbf421423ce2.png">

I can confirm that this test works exactly as expected in the develompent environment, it is consistently failing in the CircleCI environment.

I'm unable to view the whole error log in the video and it's not stored in the NPM logs or Cypress run CLI output, please help!

### Versions

- Cypress 3.1.4
- CircleCI using the `cypress/base:10` docker image

**Comment by jennifer-shehane** [comment]
What does the CLI output print for this test when it fails? Can you copy/paste?

**Comment by joshmedeski** [comment]
I tried running the test with Electron and it passed on my machine locally 🙁 

Here is the output of the failre in the CircleCI's CLI output at the bottom of the Cypress run command:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-raven-com@0.0.0 cy:run: `cypress run --reporter junit --reporter-options "mochaFile=test-results/cypress/results.xml,toConsole=false"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-raven-com@0.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-27T20_55_03_425Z-debug.log
{ Error: Command failed: npm run cy:run
    at makeError (/tmp/app.raven.com/node_modules/start-server-and-test/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/tmp/app.raven.com/node_modules/start-server-and-test/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run cy:run',
  timedOut: false,
  killed: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-raven-com@0.0.0 cy:ci: `start-server-and-test ci:serve http-get://localhost:4200 cy:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-raven-com@0.0.0 cy:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-27T20_55_03_445Z-debug.log
Exited with code 1
```

**Comment by jennifer-shehane** [comment]
I see you are using the `start-server-and-test` module. Could you provide what you are running in the CircleCI job concerning this? Or print your CircleCI config file (excluding any sensitive data).

**Comment by jennifer-shehane** [comment]
Hey @joshmedeski, any update on this?

**Comment by joshmedeski** [comment]
My team moved away from using fixtures and we now use a local version of our API with seeded data. So we don't have to deal with this specific issue anymore.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
