### ISSUE TITLE
Dahshboard down

### ISSUE THREAD

**Issue by sszemeresky** [cypress-io/cypress#30150]
### Current behavior

Oops, something went wrong - when entering organization 

### Desired behavior

https://cloud.cypress.io/organizations opens organization

### Test code to reproduce

enter https://cloud.cypress.io/organizations
and choose organization

### Cypress Version

13.13.3

### Node version

20.17.0

### Operating System

Win10

**Comment by jennifer-shehane** [comment]
There was a database outage between 3:58 AM and 4:45 AM CDT that impacted the Dashboard and API service. Everything should be working normally now. Sorry for the inconvenience.
