### ISSUE TITLE
Unable to select a value in p-dropdown form PrimeNG (not visible)

### ISSUE THREAD

**Issue by remcogeldhof** [cypress-io/cypress#3019]
After two days of searching, after opening a stackoverflow post and after asking it in the Cypress chat, I decided to open an issue. Cypress is working fine on my Angular project, only on my dropdowns I have an issue. I'm unable to select a value. 

### Current behavior:
HTML CODE:
```html
    <span class="eco-form-component__control">
            <p-dropdown formControlName="provenanceCountry"
                        [options]="countries"
                        [style]="{'width':'100%'}">
            </p-dropdown>
          </span>
```
Exact HTML:
```html
<div _ngcontent-c11="" class="eco-form-component"><label _ngcontent-c11="" class="eco-form-component__label" ng-reflect-ng-class="eco-form-component__label"> Geïmporteerd uit </label><span _ngcontent-c11="" class="eco-form-component__control"><p-dropdown _ngcontent-c11="" formcontrolname="provenanceCountry" class="ng-tns-c14-7 ui-inputwrapper-filled ng-untouched ng-pristine ng-invalid" ng-reflect-style="[object Object]" ng-reflect-options="[object Object],[object Object" ng-reflect-name="provenanceCountry"><div class="ng-tns-c14-7 ui-dropdown ui-widget ui-state-default ui-corner-all ui-helper-clearfix" ng-reflect-ng-class="[object Object]" ng-reflect-ng-style="[object Object]" style="width: 100%;"><!--bindings={
  "ng-reflect-ng-if": "true"
}--><div class="ui-helper-hidden-accessible ng-tns-c14-7 ng-star-inserted"><select class="ng-tns-c14-7" aria-hidden="true" tabindex="-1" aria-label=" "><!--bindings={}--><!--bindings={}--><!--bindings={
  "ng-reflect-ng-if": "true"
}--><!----><!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}--><option class="ng-tns-c14-7 ng-star-inserted" value=" "> </option><option class="ng-tns-c14-7 ng-star-inserted" value="BELGIUM">BELGIUM</option><option class="ng-tns-c14-7 ng-star-inserted" value="FRANCE">FRANCE</option><!----></select></div><div class="ui-helper-hidden-accessible"><input class="ng-tns-c14-7" readonly="" role="listbox" type="text" aria-label=" "></div><!--bindings={
  "ng-reflect-ng-if": "true"
}--><label class="ng-tns-c14-7 ui-dropdown-label ui-inputtext ui-corner-all ng-star-inserted" ng-reflect-ng-class="[object Object]"><!--bindings={
  "ng-reflect-ng-if": "true"
}--><!----> <!--bindings={
  "ng-reflect-ng-template-outlet-context": "[object Object]"
}--></label><!--bindings={
  "ng-reflect-ng-if": "false"
}--><!--bindings={}--><!--bindings={}--><div class="ui-dropdown-trigger ui-state-default ui-corner-right"><span class="ui-dropdown-trigger-icon ui-clickable pi pi-caret-down" ng-reflect-klass="ui-dropdown-trigger-icon ui-cl" ng-reflect-ng-class="pi pi-caret-down"></span></div><!--bindings={}--></div></p-dropdown></span><!--bindings={
  "ng-reflect-ng-if": "false"
}--></div>
```

typescript:
```typescript
countries: any[];
this.countries = ([{label: ' ', value: ' '}, {label: 'Belgium', value: 'Belgium'}, {label: 'France', value: 'France'}]);
```

CYPRESS:

When I use these methods below, I get an error or I get the default value selected. 
On of my dropdowns:

Cypress methods that doesn't work:
```js
cy.get('select').select('FR').should('have.value', 'FR')
```

Error:
```
> CypressError: Timed out retrying: cy.select() failed because this element is not visible:
> <select class="ng-tns-c16-2" aria-hidden="true" tabindex="-1" aria-label="Nederlands">...</select>
> This element '' is not visible because its content is being clipped by one of its parent elements, which has a CSS property of overflow: 'hidden', 'scroll' or 'auto'
```

When using `{force: true}` I won't get an error, but it's not working either.

Not working:
```js
cy.get('select').select('FR',{force:true}).should('have.value', 'FR')
```

Not working: 
```js
cy.get('option').eq(2).click({force: true});
```

Not working: 
```js 
cy.get('p-dropdown[formControlName="provenanceCountry"]').click();
    cy.get('p-dropdown[formControlName="provenanceCountry"]').get('select').then(option => {
      cy.wrap(option).get('p-dropdown[formControlName="provenanceCountry"]').contains('FRANCE').click();
    });
```

```
Error: 
> CypressError: Timed out retrying: cy.click() failed because this element is not visible:
>  <option class="ng-tns-c9-15 ng-star-inserted" value="[object
>  Object]">FRANCE</option>
> This element '<option.ng-tns-c9-15.ng-star-inserted>' is not visible because it has an effective width and height of: '0 x 0' pixels.
> Fix this problem, or use {force: true} to disable error checking.
> https://on.cypress.io/element-cannot-be-interacted-with
```
> When I use {force: true} in my click, the error is just not shown.
 
Not working:
```js
 cy.get('p-dropdown[formControlName="provenanceCountry"]').click();
 cy.get('[formcontrolname="provenanceCountry"]').find('select').select('FRANCE');
```

### Desired behavior:

Select a value in my dropdown (not the default).

### Versions
I'm using windows 7, google chrome

**Comment by jennifer-shehane** [comment]
Using the provided HTML, I am unable to reproduce this issue. I suspect the issue involves something from your css stylings - that Cypress is wrongly interpreting as not visible. Can you provide any relevant css styles to reproduce the issues with the provided HTML above?

<img width="559" alt="screen shot 2019-01-02 at 4 00 55 pm" src="https://user-images.githubusercontent.com/1271364/50586426-c2adad00-0ea7-11e9-844e-8a55e81649e5.png">

<img width="256" alt="screen shot 2019-01-02 at 4 01 01 pm" src="https://user-images.githubusercontent.com/1271364/50586431-c80af780-0ea7-11e9-80ee-df4fad4bf73b.png">

**Comment by jennifer-shehane** [comment]
I'm sorry. I'm still unable to replicate an error with what it provided. You will need to provide a repo with the exact reproducible error - the application code and test code that we can open and run. 

Make an html page with the html, css, and js code to replicate exactly with the test code. Thanks.

**Comment by remcogeldhof** [comment]
Thank you for your reply @viloskovic.
Both of your solutions are working fine!

Like you said,  the second solution is the best one. When the dropdown contains a lot of values, the select takes more time than it should take. 

So performance-wise this is the best solution for my problem: 
`cy.get('p-dropdown[formControlName="provenanceCountry"]').click().contains('ul li > span', 'France').click();`

**Comment by testtek** [comment]
`cy.get('p-dropdown[formControlName="country"]').click().contains('ul li > span', 'Indian').click();` 

This solution doesn't work after Cypress version 5.2.0 (most probably after this bug fix https://github.com/cypress-io/cypress/issues/8494) ; get below error

`Timed out retrying: cy.click() failed because this element is detached from the DOM.

<span class="ng-star-inserted">Indian</span>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.contains()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands`

**Comment by tfossoul** [comment]
Hi,

This doesn't work in cypress 8.0.0. Does someone know how to do it ?

In my case I am able to click on the list, open and see items. Then I programmatically click on the first element of the list, the list disappear and... that's all... The item is never selected..

**Comment by andi-dev** [comment]
@tfossoul I have the same issue you describe. Did you figure out what was wrong in your case?

**Comment by solangeDev** [comment]
I do found one solutions this instruction selected the first option. 

 cy.get('p-dropdown[formControlName="category"]')
      .find('.p-dropdown')
      .click({ force: true })
      .find('.p-dropdown-items-wrapper > .p-dropdown-items')
      .click({ force: true })
      .get('.p-dropdown-item')
      .children()
      .first()
      .click({ force: true });

**Comment by upotekhi** [comment]
> @tfossoul I have the same issue you describe. Did you figure out what was wrong in your case?

Try to use click with { force: true } - it helped me.

**Comment by Aulerien** [comment]
> I do found one solutions this instruction selected the first option. version "cypress": "^9.1.0",
> 
> cy.get('p-dropdown[formControlName="category"]') .find('.p-dropdown') .click({ force: true }) .find('.p-dropdown-items-wrapper > .p-dropdown-items') .click({ force: true }) .get('.p-dropdown-item') .children() .first() .click({ force: true });



That hasn't work for me. I make some change like this, and it works: 
`cy.get('p-dropdown[formControlName="category"]')
            .find('.p-dropdown')
            .click({ force: true })
            .get('.p-dropdown-items-wrapper > .p-dropdown-items')
            .click({ force: true })
            .find('.p-dropdown-item')
            .children()
            .first()
            .click({ force: true });`
