### ISSUE TITLE
Video recording can exhaust all memory due to stream backpressure on slow CPU's

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#302]
When recording video it is possible due to the way stream backpressure works in node to exhaust all memory.

An example of this is here: https://circleci.com/gh/cypress-io/cypress-core-desktop-gui/416

Under the hood we are writing the image buffer frames to memory, expecting this to be streamed to `ffmpeg`. 

The reason the memory is exhausting is that the Circle CI instance cannot keep up the stream, and therefore due to backpressure the buffer of images continues to build up and up until it hits about 3G in memory and Circle CI terminates the build.

The solution here is to build a simple queuing system and write image bytes first to disk and then only buffer them temporarily since we are CPU bound and not IO bound.

**Comment by brian-mann** [comment]
Okay this is actually quite a bit more complex than originally noted. Due to the way we're recording timestamps with `ffmpeg` framework we cannot defer writing images to the `ffmpeg` stream.

We are going to simply switch to dropping frames which exceed the threshold. This prevents any kind of memory build up, and after running some preliminary tests only results in about 50 frames of 7500+ being dropped during a typical 6 minute run.

**Comment by brian-mann** [comment]
Fixed in [`0.17.12`](https://github.com/cypress-io/cypress/wiki/changelog#01712-11212016).

**Comment by mediavrog** [comment]
Is there a way to toggle this behavious? We are experimenting using cypress for tutorial demo creation and the dropped frames when recording headless are an issue for this.

**Comment by jennifer-shehane** [comment]
@mediavrog These are all of the configurable values for video recording through Cypress: https://on.cypress.io/configuration#Videos
