### ISSUE TITLE
Encountering browserSocket error using Custom Chromium 66

### ISSUE THREAD

**Issue by ZhuoHuaToKnow** [cypress-io/cypress#30200]
### Description

When I test chrome66 using cypress, I expect it to work, but it gets stuck. I used the DEBUG command to check and found an error:https-proxy received error on client browserSocket { err: Error: read ECONNRESET at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -54, code: 'ECONNRESET', syscall: 'read' }, url: 'example.cypress.io:443' }

### URL of Issue(s)

https://docs.cypress.io/guides/guides/launching-browsers#Chrome-Browsers
### Steps to replicate

1. Use chromium version
2. Stuck while running test
3. Use DEBUG to see the error
4. cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -54, code: 'ECONNRESET', syscall: 'read' }, url: 'example.cypress.io:443' }

### Browser

Google chromium 66

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by MikeMcC399** [comment]
@sgreen233 

This issue list is about errors in the documentation.

If you think that there is a bug in the Cypress software then you can open an issue on https://github.com/cypress-io/cypress/issues and supply the requested information.

Please make sure that you are using a supported operating system and a supported version of Node.js (`18.x` / `20.x` / `22.x`) according to https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements

According to https://docs.cypress.io/guides/guides/launching-browsers#Browser-versions-supported

Cypress supports the browser versions below:

Chrome 64 and above. Chrome 80 and above is required for cypress open usage.

**Comment by ZhuoHuaToKnow** [comment]
I'm using the 18.x version of the node.js and make sure the operating system supports the use of the browser. When using cypress, I used the command of cypress run, but the problem still appears

**Comment by ZhuoHuaToKnow** [comment]
It seems like that there was a problem in launching Chrome with cypress.I wonder if chromium 66 is supported with the cypress run command

**Comment by MikeMcC399** [comment]
@sgreen233 

> It seems like that there was a problem in launching Chrome with cypress.I wonder if chromium 66 is supported with the cypress run command

Officially it is supported.

I tried a few versions of Chromium < 80 on Ubuntu 20.04 with Cypress `13.14.2` and Node.js `v18.20.4` with `npx cypress run`. They gave different errors or timed out, so I could not demonstrate that the versions which are supposed to be supported do actually work.

It's up to you if you want to report your problem on https://github.com/cypress-io/cypress/issues , however given that this browser is 6 years old I don't expect anything except the documentation to be fixed.

It's already suggested to drop support for Chrome < 80 in the next major release of Cypress.

**Comment by MikeMcC399** [comment]
@sgreen233 

Please add your configuration information.

Cypress version: ?
Operating system type and version: ?
Node.js version: ?

I tried on a virtual Ubuntu system and I could get Chromium 66 to run with 
Cypress `11.2.0` and Node.js `v14.21.3`, but only in headed mode. In headless mode it hung.

On Cypress `12.17.4` / Node.js `v14.21.3` I got the error 
> 'Fetch.enable' wasn't found

On Cypress `13.14.2` / Node.js `v16.20.2` I got the error 
> 'Runtime.addBinding' wasn't found

I installed using
```shell
npx @puppeteer/browsers install chromium@540276
```

**Comment by ZhuoHuaToKnow** [comment]
Cypress version: 10.8.0
Operating system type and version: ubuntu 18.04
Node.js version: 13
You are right, it can only be run in headed mode, and the problem was solved after I used this mode.

**Comment by MikeMcC399** [comment]
@sgreen233 

- If your problem is solved, then I suggest to close this issue and follow instead https://github.com/cypress-io/cypress/issues/30205 as it does seem that there is a documentation issue. In general the documentation only covers the current latest version Cypress 13.x so it needs to be correct for this version and not so much for Cypress 10.x.
- Node.js 13 is no longer supported, but I don't think it has an influence on this issue.
