### ISSUE TITLE
breaking: remove `log:memory:pressure` and `firefox:force:gc` from the socket API

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#30222]
### What would you like?

With Cypress 14, I would like to remove the `log:memory:pressure` and `firefox:force:gc` from the socket API as they are not documented and likely not used any longer by existing Firefox users and the methods are undocumented. See 
 this [github comment](https://github.com/cypress-io/cypress/issues/8525#issuecomment-715353672) for more information.

### Why is this needed?

Since these two socket methods are no longer needed, it breaks our dependency from needing [foxdriver](https://www.npmjs.com/package/@benmalka/foxdriver) inside the `firefox-utils` file, further simplifying our firefox automation implementation.

**Comment by jennifer-shehane** [comment]
Will be released in Cypress 14
