### ISSUE TITLE
Make experimentalJustInTimeCompile default within Cypress

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#30234]
### What would you like?

Fix these issues outright instead of requiring an experimental config: https://github.com/cypress-io/cypress/issues/28644

- Rename `experimentalJITCompile` -> `JITCompile`
- Default JITCompile to `true` 
- Designate `experimentalJITCompile` as deprecated / removed??

### Why is this needed?

.

**Comment by DeepanMondal** [comment]
Hi, thanks for raising this issue! It seems you're looking to fix the problem outright without needing to rely on the experimental config (#28644). This would indeed improve stability and ease of use. To move forward, we'd need to dive into how Cypress handles the AAD login flow in different environments (especially CI/CD). If you have any logs or additional context, that could help narrow down the problem. Happy to assist with further debugging or exploring a long-term fix!
