### ISSUE TITLE
Type 'keyof T' does not satisfy the constraint 'string' (Cypress 3.1.4)

### ISSUE THREAD

**Issue by bartduisters** [cypress-io/cypress#3024]
### Current behavior:
![screenshot_20181228_141612](https://user-images.githubusercontent.com/43420049/50516504-729ba880-0aab-11e9-9c8e-bc1c92ef4fe5.png)

### Desired behavior:
No error to be thrown

### Steps to reproduce: (app code and test code)
- Run `ng e2e` in an Angular application with cypress 3.1.4 (3.1.3 does not have the same issue)

### Versions
cypress 3.1.4
OS: arch linux
browser: / (the error is in the terminal)

**Comment by bahmutov** [comment]
the same problem in https://circleci.com/gh/cypress-io/cypress-example-kitchensink/1816

**Comment by bahmutov** [comment]
First, because we never call `npm run build` inside `cypress-example-kitchensink` project when testing built NPM and test runner binary we are NOT catching this error. So the first thing to fix this is to prevent releasing new Cypress version that breaks `cypress-example-kitchensink`.

**Comment by bahmutov** [comment]
Hmm, `dtslint` is great for type assertions against `types/index.d.ts` but now breaks on `@ts-ignore` line 
```
> cypress@0.0.0 dtslint /Users/gleb/git/cypress/cli
> dtslint types

Error: At /Users/gleb/git/cypress/cli/types/index.d.ts:{"line":3938,"character":5}: 'ts-ignore' is forbidden.
```

We only need `@ts-ignore` because of `Omit<>` implementation (keys vs string-only keys)

```
// TODO - remove this if possible. Seems a recent change to TypeScript broke this. Possibly https://github.com/Microsoft/TypeScript/pull/17912
//@ts-ignore
type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>> // tslint:disable-line
```

which is only used for Sinon spies

```
  interface Agent<A extends sinon.SinonSpy> {
    log(shouldOutput?: boolean): Omit<A, 'withArgs'> & Agent<A>

    /**
     * Saves current spy / stub under an alias.
     * @see https://on.cypress.io/stubs-spies-and-clocks
     * @see https://on.cypress.io/as
     * @example
     *    cy.spy(win, 'fetch').as('winFetch') // Alias 'window.fetch' spy as "winFetch"
     */
    as(alias: string): Omit<A, 'withArgs'> & Agent<A>

    /**
     * Creates a spy / stub but only for calls with given arguments.
     * @see https://on.cypress.io/stubs-spies-and-clocks
     * @see https://on.cypress.io/as
     * @example
     *    const s = cy.stub(JSON, 'parse').withArgs('invalid').returns(42)
     *    expect(JSON.parse('invalid')).to.equal(42)
     *    expect(s).to.have.been.calledOnce
     */
    withArgs(...args: any[]): Omit<A, 'withArgs'> & Agent<A>
  }
```

Hmm, I would rather remove `Omit` to get rid of this error then ...

@NicholasBoll do you have any idea what we could do to make both TS and dtslint happy?! I have no idea ...

**Comment by NicholasBoll** [comment]
@bahmutov I suggest we upgrade Typescript to 2.8+. 2.8 introduced [Conditional Types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html) and `Exclude`. Then `Omit` can be written as `Pick<T, Exclude<keyof T, K>>`

That should make both happy. I can experiment on that upgrade and conditional types for more accurate type definitions

**Comment by bahmutov** [comment]
nice! we are already there on 2.8 in `types/index.d.ts` `// TypeScript Version: 2.8` so it might be just switching to `Exclude`
