### ISSUE TITLE
Can't execute test on Mac

### ISSUE THREAD

**Issue by GianninaInditex** [cypress-io/cypress#30253]
### Current behavior

[https://grupoinditex-my.sharepoint.com/:v:/g/personal/gianninaps_ext_stradivarius_com/EeuTb8tC9ClKmxFjoJu7nugBZ0aV5_koKHNWdlFpfzmYGw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=DBM9bH](url)

### Debug logs

```Text
2024-09-18 17:12:06.330 Cypress[11014:58301] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
objc[11017]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5520b780) and /Users/gianninapriscilasarappa-local/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x12874d9c8). One of the two will be used. Which one is undefined.
Still waiting to connect to Chrome, retrying in 1 second (attempt 18/62)
```

### Cypress Version

9.7.0

### Node version

16.20.2

### Package Manager

npm

### Package Manager Version

8.19.4

### Operating system

Mac

### Operating System Version

Somona 14.6.1

**Comment by jennifer-shehane** [comment]
@GianninaInditex Please update Cypress to the latest version and try again. Your issue may already be fixed.
