### ISSUE TITLE
For web build with salesforce lightning web components Css and JS isn't loading when running test in bitbucket w/ cypress record key

### ISSUE THREAD

**Issue by DanielaRoMi** [cypress-io/cypress#30267]
### Current behavior

When I run the test w/o the record key the test passes in bitbucket but after adding the record key to record in cypress cloud in the pipeline the css and javascript for the web page is not loading and all my tests all failing. Here  I attack a picture of the test result. I add the record key in repository variables so the configuration should be okay,  here I also attach the bitbucket pipeline. 
![image](https://github.com/user-attachments/assets/5c19b3ba-c8df-4caa-9da9-362a3527613f)
![image](https://github.com/user-attachments/assets/d6cedf7d-6a55-4bd6-9d1a-68c851693d6a)

### Test code to reproduce

image: cypress/base:20.14.0

## job definition for running E2E tests in parallel
e2e: &e2e
  name: E2E tests
  caches:
    - node
    - cypress
  script:
    - npx cypress run --record --key $CYPRESS_RECORD_KEY
  artifacts:
    # store any generates images and videos as artifacts
    - cypress/screenshots/**

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - npm
          - cypress
          - node
        script:
          - npm ci
    - step:
        name: Run E2E test
        <<: *e2e
    

definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress

### Cypress Version

13.11.0

### Node version

21.7.3

### Operating System

Windows

### Other

Every time a commit is done a new pipeline is created

**Comment by jennifer-shehane** [comment]
@DanielaRoMi Is this from the screenshot that the visuals don't look right? Is the [Test Replay](https://docs.cypress.io/guides/cloud/test-replay) in the Cloud accurate? I'm just trying to narrow down where the issue is occurring. 

Could you also try updating to latest Cypress?

**Comment by DanielaRoMi** [comment]
Hi @jennifer-shehane  I updated to the latest version and still getting the same results,  and yes the screenshot with the visuals don't look right it's what I get when run the test in bitbucket w/ cypress record key and that's the test replay results. When I run the same test w/o record key added in the pipeline they tend to pass and also locally works good

**Comment by jennifer-shehane** [comment]
We were able to track this down and resolve this. Please try to rerun your tests and see if this is resolved.

**Comment by DanielaRoMi** [comment]
It's fixed now
