### ISSUE TITLE
[Internal] Failing test causing flake in our driver tests

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#30273]
### What would you like?

(❗️2) driver-integration-tests-firefox: verify-mocha-results failed - driver test failing, but not failing the tests (net-stubbing_. [Link](https://app.circleci.com/pipelines/gh/cypress-io/cypress/64149/workflows/7762a96d-499e-4bd7-9d7e-bdd98bc67d3d/jobs/2660816)

### Why is this needed?

We should update our test so that this doesn't fail in this manner.

**Comment by ryanthemanuel** [comment]
Fixed by #30276
