### ISSUE TITLE
Docker pull failed for image cypress/browsers:latest. authentication required

### ISSUE THREAD

**Issue by OzBob** [cypress-io/cypress#30278]
### Current behavior

Docker pull fails for image cypress/browsers:latest in github action with the error "unauthorized: authentication required" 

It happened multiple times between
2024-09-24T1656GMT+8
and
2024-09-25T0946GMT+8

Logs captured at: 2024-09-25T0840GMT+8

The image is available and was updated 2924-08-18 in https://hub.docker.com/r/cypress/browsers/tags

The availability of these images is crucial to Cypress's business, the error will impact services of all subscribers using Cypress to run tests from GitHub.

### Desired behavior

If this is a github action or docker service 'authentication' issue, please suggest where to direct this issue.

### Test code to reproduce

YML section of github action:

```
jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
```

### Cypress Version

13.2.0

### Node version

18

### Operating System

ubuntu latest

### Debug Logs

```shell
/usr/bin/docker pull cypress/browsers:latest
  Error response from daemon: unauthorized: authentication required
  **Warning: Docker pull failed with exit code 1, back off 9.892 seconds before retry.**
  /usr/bin/docker pull cypress/browsers:latest
  **Error response from daemon: unauthorized: authentication required**
  **Warning: Docker pull failed with exit code 1, back off 2.658 seconds before retry.**
  /usr/bin/docker pull cypress/browsers:latest
  **Error response from daemon: unauthorized: authentication required**
  **Error: Docker pull failed with exit code 1**
```
```


### Other

_No response_

**Comment by MikeMcC399** [comment]
https://hub.docker.com/ => https://www.dockerstatus.com/

![image](https://github.com/user-attachments/assets/7e3d3663-7d2e-4cba-84d2-3a650062e7ab)

**Comment by MikeMcC399** [comment]
Should be back to normal again now:

https://www.dockerstatus.com/

![image](https://github.com/user-attachments/assets/45869ed5-ca5f-42ea-97dd-070d043ea684)
