### ISSUE TITLE
Assertion example for dynamically scoped class names

### ISSUE THREAD

**Issue by LaurieLinz** [cypress-io/cypress#3028]
### Is this a Feature or Bug?

Posted the question in gitter and @bahmutov asked me to open an issue.

### Current behavior:

Querying for a class name in a dynamic list is quite challenging with Cypress. Sub-string matches do not seem to pick it up. `Using indexOf` seems to be a good option and an assertion example would be a great help.

### Desired behavior:

A nice example of how to do this would be great!

### Steps to reproduce: (app code and test code)
Please see this convo: 
<img width="982" alt="_cypress-io_cypress_-_gitter" src="https://user-images.githubusercontent.com/14853507/50521485-29376300-0a83-11e9-9fb3-a9c40c312efd.png">
<img width="967" alt="_cypress-io_cypress_-_gitter2" src="https://user-images.githubusercontent.com/14853507/50521491-2fc5da80-0a83-11e9-859b-d595c08b4508.png">

### Versions

Version 3.1.3, Mac 10.13.6, Chrome 71.0.3578.98

**Comment by bahmutov** [comment]
Issue moved to [cypress-io/cypress-documentation #1267](https://github.com/cypress-io/cypress-documentation/issues/1267) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jennifer-shehane** [comment]
@bahmutov You can 'transfer issues' now using GitHub instead of ZenHub - it keeps a better record of the original.

<img width="244" alt="screen shot 2019-01-02 at 12 13 08 pm" src="https://user-images.githubusercontent.com/1271364/50581412-d812df00-0e87-11e9-9288-61592a60807f.png">
