### ISSUE TITLE
Be able to grep tags and run only these tests as run parameters to work with testomatio

### ISSUE THREAD

**Issue by petergeczi931** [cypress-io/cypress#30329]
### What would you like?

I would like to run specific tests based on tags, when I create a plan in testomat.io, the tests has specific ids for each test, and it greps the test unique ids, and it passes them to cypress run command, but it does not support that now.
https://docs.testomat.io/usage/continuous-integration/

For example
```
npx cypress run --grep="Tf3777012|T69a88855|T25dc1597|T3f30c7c0|Ta6dd8f4b|T123ac7a3|Tb0d0b9a8|T68819640|Td4cdabf6|Tdc6f7871|T149727c1|Td5d9c24b|Tf8c3005b
```

it should run these 13 tests, but error is thrown, unknown option.
testomat.io docs says that it is possible for playwright and The filtering functionality for test execution is currently available for the following frameworks: Playwright & CodeceptJS. It would be nice also with Cypress.

### Why is this needed?

To have specific report only for the tests that have run. And see these result directly in Jira ticket.

**Comment by jennifer-shehane** [comment]
You can use our [@cypress/grep plugin](https://github.com/cypress-io/cypress/tree/develop/npm/grep) to achieve this. Outside of that, you can express support for this to be included natively here: https://github.com/cypress-io/cypress/issues/1865
