### ISSUE TITLE
Investigate `RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received type number (NaN)` within firefox system-tests 

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#30352]
### Current behavior

Currently, sometimes in CI after the merging of #30250, firefox fails to start with the error `RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received type number (NaN)`. It looks like we are failing to parse the cdp port [here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/firefox.ts#L578). we should wrap this logic and handle the error to see what `moz:debuggerAddress` capability returns within our system-tests to see if we can fix the error or handle it more gracefully. 

Below is a screenshot of the error, which can be seen in this [job](https://app.circleci.com/pipelines/github/cypress-io/cypress/64483/workflows/222190ca-3868-4507-b97e-42137a6d75b1/jobs/2675893/parallel-runs/3)
![](https://github.com/user-attachments/assets/8223006d-1d19-4b36-8327-de7eed513781)

### Desired behavior

Once we see where the error is coming from, we can either resolve it completely or handle it more gracefully

### Test code to reproduce

N/A

### Cypress Version

N/A

### Node version

N/A

### Operating System

N/A

**Comment by AtofStryker** [comment]
I am seeing this still on the https://github.com/cypress-io/cypress/pull/30324, so this is something we need to handle. Its difficult to reproduce, but we can likely handle the issue in the case a CDP address is undefined and send a retry event to relaunch the browser. We send the capability, but it does not get set

 ![Image](https://github.com/user-attachments/assets/0e3e316a-9520-4029-827e-e32fe37d350b)

**Comment by AtofStryker** [comment]
@whimboo any idea why this would happen? It seems very seldom, but sometimes when sending the `moz:debuggerAddress` the capability address comes back as undefined. I put together a work around in #30393 but overall seems odd.

**Comment by whimboo** [comment]
@AtofStryker would you mind running tests with the Firefox preference `remote.log.level` set to `Trace`? See our [documentation for more details](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html). It might indicate what's wrong. Only from the above output I cannot tell anything and I'm also not aware of such a problem on our side. It's basically new to me. Thanks.

**Comment by AtofStryker** [comment]
@whimboo I can. I have it enabled in this [circleCI run](https://app.circleci.com/pipelines/github/cypress-io/cypress/64725) which is this [commit](https://github.com/cypress-io/cypress/commit/4e44e0179caefcc5a4ca08ee541744c0d12394d5). It happens sporadically so I might not be able to reproduce it on first try (also going to be some failures from printing additional logs) but ill see if I can get a run where it fails with this issue.

**Comment by whimboo** [comment]
Yes, understood. Let me know when it happened next and I'll take a look at it. Thanks!

**Comment by whimboo** [comment]
@AtofStryker did this issue actually happen on specific platforms only? Maybe there is some more data to localize the issue?

**Comment by AtofStryker** [comment]
> @AtofStryker did this issue actually happen on specific platforms only? Maybe there is some more data to localize the issue?

I think so far I've only seen it on linux but there is a larger sample size there. Still working on getting a reproduction in a Circle run.
