### ISSUE TITLE
Unknown origin of Cypress, no uninstaller, not a node user

### ISSUE THREAD

**Issue by TilKenneth** [cypress-io/cypress#30384]
### Current behavior

Cypress 10.11.0 existing on my computer, filetimes claim since 25.07.2023 (dd.mm.yyyy).

### Desired behavior

In this situation, as expected, a) uninstall.exe, b) uninstallable entry in currently "Installed Apps", formerly 'Control Panel\All Control Panel Items\Programs and Features'.

Cypres.exe does have a digital signatur (‎thumbprint: `1961d209c4d95ab0940b056f312f0aded17b0f15`, Validity **from** ‎tue ‎15. ‎juni ‎2021 16:31:48, **to** ‎fri ‎14. ‎juni ‎2024 16:31:48), but its the same name.

### Test code to reproduce

Browsing C:\Users\%USERNAME%\AppData\Local\Cypress\Cache\10.11.0\Cypress.

### Cypress Version

10.11.0

### Node version

I don't node.

### Operating System

Microsoft Windows Version 10.0.22631.4317

### Debug Logs

I need to know how (by your own tools/uninstaller), or where to clean up, what filenames to look for, registry changes (unknowingly may be changed).

### Other

I don't do node, the only node I *know* i have "touched" is locked safely inside inside a docker-container, and that isnt running most of the time.

Don't know where your product came from (into my pc), why, who, or really when, via what. I don't know about your product, except no uninstall.exe, for all I know you have a good product, if the number of issues is a fair enough metric to go by, actively enough used.

I dont do yarn, gem, gum, nim, npm, mnp ...etc, Re #29478 to https://docs.cypress.io/guides/getting-started/installing-cypress#Installing

Searched for 'remove', only 1 place https://docs.cypress.io/faq/questions/using-cypress-faq

Not relevant; https://docs.cypress.io/guides/cloud/integrations/source-control/github#Uninstall-the-Cypress-GitHub-app

Checked VSCode' extensions; https://docs.cypress.io/guides/tooling/IDE-integration#Visual-Studio-Code

Also found https://github.com/cypress-io/cypress/discussions/26283

But I am not a voluntary user. Thanks in advance for understanding.

**Comment by MikeMcC399** [comment]
@TilKenneth 

You should be able to resolve your issue by deleting the Windows directories

- `%LOCALAPPDATA%\Cypress`
- `%APPDATA\Cypress`

**Comment by TilKenneth** [comment]
I 7-Zip'ped the mentioned directories, deleted the directories, time went by and no unexpected events as result.

There were some firewall rules, they needed to be removed aswell. Discovered only a few days ago. They were identified by the path to the mentioned locations above. I was not able to provide a removal script for automation.

There are a few remnants in the Registry, appears to be part of Windows' housekeeping, or mitigations of sorts, as paths were located in subdirectories of the mentioned locations above.


Examples
- `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\AlignedHistogramBucketExemplarReservoir.js\{e428c6ff-dd67-2324-c181-46687e0ccc2f}`
- `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\createBatchingExecutor.d.ts\{917cf911-9a0d-1512-e3ae-edb7809697ba}`

But my subkey `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options` is literally flooded from `.log` files, picture files `.jpg`, PDF/HTML, to executables and scripts.

Thank you.

**Comment by MikeMcC399** [comment]
@TilKenneth 

- Firewall rules would have been added manually and they would depend on which Firewall is active / installed.
- The entries in the Windows Registry are also not put there by Cypress, at least not directly.

In the meantime a documentation section [Uninstall Cypress](https://docs.cypress.io/app/references/advanced-installation#Uninstall-Cypress) has been added that details the manual steps necessary to uninstall.
