### ISSUE TITLE
What is the Preprocessor expected output format? Doesn't accept `import` (es) or `require` (cjs). Need better documentation.

### ISSUE THREAD

**Issue by bvandercar-vt** [cypress-io/cypress#30414]
### What would you like?

Would like better documentation on the expected output file format of a preprocessor.

If I output as `es`, I get error `Cannot use import statement outside a module`

If I output as `cjs`, I get error `require is not defined`

Must each output file include all code to be ran, no importing of other files? Why is this? This seems like something that should be fixed. At the minimum, documentation should be improved.

### Why is this needed?

Would expect an ES output to work, but it doesn't.

**Comment by jennifer-shehane** [comment]
@bvandercar-vt Could you provide a small repo that reproduces the issue you’re describing?
