### ISSUE TITLE
Cypress crashes in headless mode but works fine in browser mode

### ISSUE THREAD

**Issue by zubairPlanera** [cypress-io/cypress#30410]
### Current behavior

Cypress is crashing in headless mode for few of my test cases unexpectedly but it is working fine in browser mode

### Desired behavior

Cypress should not crash even on headless mode as It is working fine on browser mode

### Test code to reproduce

![download (1)](https://github.com/user-attachments/assets/f8b4a054-4900-4858-91fa-f87d4f5de4be)

### Cypress Version

13.5.1

### Node version

20.17.0

### Operating System

macOS  12.0

**Comment by jennifer-shehane** [comment]
@zubairPlanera We'll need a way to reporduce this in order to investigate. There's not enough info here to investigate.
