### ISSUE TITLE
Deprecate `resourceType` in `cy.intercept`

### ISSUE THREAD

**Issue by mschile** [cypress-io/cypress#30433]
### What would you like?

We would like to deprecate `resourceType` within `cy.intercept`. The `resourceType` comes from CDP today in the pre-request. In order to potentially remove proxy correlation, we need to remove the dependency on `resourceType`. In addition, since the values come from CDP, with the transition to BiDi, these values may no longer be the same.

**Comment by AtofStryker** [comment]
If we remove `cy.intercept()`, we also need another way to disable proxy logging since `log: false` can no longer be used once the field changes or is removed
