### ISSUE TITLE
Support Next.js 15 for Component Testing

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#30445]
### What would you like?

Support Next.js 15 for Component Testing when React 19 is released.

- This goes hand-in-hand with issue https://github.com/cypress-io/cypress/issues/29470

### Why is this needed?

[Next.js 15 was announced](https://nextjs.org/blog/next-15) on Oct 21, 2024 as stable, however it currently depends on React 19 RC.

### Other

```text
$ npm view next version
15.0.3
```

React 19 is currently available only as an RC version.

```text
$ npm view react dist-tags
{
  latest: '18.3.1',
  beta: '19.0.0-beta-26f2496093-20240514',
  experimental: '0.0.0-experimental-b01722d5-20241114',
  canary: '19.0.0-rc-b01722d5-20241114',
  next: '19.0.0-rc-b01722d5-20241114',
  rc: '19.0.0-rc-b01722d5-20241114'
}
```

See https://docs.cypress.io/app/component-testing/get-started#Supported-Frameworks

![image](https://github.com/user-attachments/assets/0a1a0e93-345f-4000-bba8-45bc1895015c)

**Comment by khai-pi** [comment]
Hi, does Cypress supports Nextjs 15, i tried to test a component in Nextjs 15.1.2 and i have this following warning
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/208088e8-cdf7-4324-98fd-c3a85d363119" />

**Comment by MikeMcC399** [comment]
@khai-pi 

> Hi, does Cypress supports Nextjs 15, i tried to test a component in Nextjs 15.1.2 and i have this following warning

You'll need to wait for the Cypress 14 release.

The currently supported versions are listed on https://docs.cypress.io/app/component-testing/get-started#Supported-Frameworks

**Comment by khai-pi** [comment]
Thanks for the information :)

**Comment by AlonMiz** [comment]
adding this for reference as currently it has memory issues
https://github.com/cypress-io/github-action/issues/1338
