### ISSUE TITLE
Cypress Error: sync:during:user:test:execution failed to receive a response from the primary Cypress spec bridge within 1 second

### ISSUE THREAD

**Issue by dennisjblake** [cypress-io/cypress#30448]
### Current behavior

Hi, I just updated Cypress from 13.13.0 to 13.15.0 and started to receive this error:
Cypress Error: sync:during:user:test:execution failed to receive a response from the primary Cypress spec bridge within 1 second

I never had it before and couldn't find the same errors in a Google search.
It's reproduced a bunch of times during login. The code is pretty simple. The tests are running in Azure
![image](https://github.com/user-attachments/assets/7c9f0352-a1d0-43e8-ae40-6f12cad8e07c)

### Test code to reproduce

  cy.visit(visitUrl);
      cy.get('#username').type(username);
      cy.get('#password').type(password);
      cy.get('#btnSubmit').click();

### Cypress Version

13.15.0

### Node version

20.17.0

### Operating System

win11

**Comment by jennifer-shehane** [comment]
Similar error: https://github.com/cypress-io/cypress/issues/28284

**Comment by jennifer-shehane** [comment]
@denisbab Can you try to use cy.origin for the new origin the form is routing to?
