### ISSUE TITLE
Clicking test in cypress open in chrome 72 dont work

### ISSUE THREAD

**Issue by aldarund** [cypress-io/cypress#3045]
### Current behavior:
Clicking on test from test suite just open some wrong url and dont show any steps.

![](https://i.imgur.com/CjELokW.png)

Work fine with electron

### Desired behavior:

Clicked test is run like expected 

### Steps to reproduce: (app code and test code)

Just click any test after cypress open with chrome selected.

### Versions

Cypress 3.1.4
Chrome Version 72.0.3626.28 (Official Build) beta (64-bit)
Windows 10

**Comment by jennifer-shehane** [comment]
May be related to https://github.com/cypress-io/cypress/issues/1872

**Comment by jennifer-shehane** [comment]
Actually I don't think this is related since you are not seeing a 404 page.

**Comment by aldarund** [comment]
@jennifer-shehane i`m seeing 404 page, but its 404 page from my app e.g. same 404 as i try to access url that is in browser ( localhost:3000/__/#/tests ... )

**Comment by aldarund** [comment]
Ye, its same issue as #1872
https://github.com/cypress-io/cypress/issues/1872#issuecomment-450807452 - this fixes it
