### ISSUE TITLE
 Issue with Test Replay Availability in Cypress Cloud

### ISSUE THREAD

**Issue by enp-pbadelek** [cypress-io/cypress#30473]
### Current behavior

Today, I experienced a bug in the Cypress Cloud portal that prevents me from viewing the test recording known as "Test Replay." When I hover over the button, a tooltip appears stating that test replay is not available. The version of Cypress we are using in our organization is 13.15.1, and test replay is enabled in the project configuration.
We have our tests running in our CI/CD, but when we're checking gitlab logs there's nothing suspicious, so on our end everything seems to be fine
It may be helpful to note that several test runs today included test replay, and we discovered the availability issues around 8:30 AM (GMT +1).

### Desired behavior

The expected behavior is that each test run executed in the CI/CD environment should be recorded and available for replay in Cypress Cloud, allowing us to debug and analyze failures efficiently.

### Test code to reproduce

We're not able to provide you our cypress repository with CI/CD configuration at this stage.
Here's our organization id: 2606a4dc-525a-40a7-8fe1-34e0ca785a2d

### Cypress Version

13.15.1

### Node version

18.19.1

### Operating System

CI/CD Gitlab, ubuntu-latest

**Comment by jennifer-shehane** [comment]
@enp-pbadelek Looking into this now.

**Comment by jennifer-shehane** [comment]
@enp-pbadelek Could you provide a link to one of the runs that didn't have Test Replay available?

**Comment by enp-pbadelek** [comment]
@jennifer-shehane Hi, here's link to the run https://cloud.cypress.io/projects/xyxct7/runs/133/overview?roarHideRunsWithDiffGroupsAndTags=1 
Let me know if you'll need anything else.

**Comment by jennifer-shehane** [comment]
I can confirm that we see the issue and are actively investigating. Runs after around ~5:30am EST do appear to have Test Replay data available again.

**Comment by enp-pbadelek** [comment]
Yes, they do have Test Replay available. It would be nice to know what happened though.

**Comment by shubhamladhe15** [comment]
@jennifer-shehane  I have also found that screenshots are also not available with test replay.  @enp-pbadelek  have you faced same issue around earlier?

**Comment by enp-pbadelek** [comment]
@shubhamladhe15 I do not recon having these kind of problems before, it happened for the first time today.

**Comment by jennifer-shehane** [comment]
@enp-pbadelek @shubhamladhe15 We did have an incident that has since been resolved that would have affected runs during this time period, where screenshots, videos, and Test Replays are not available to view within the Cloud. We're updating our status page to indicate the specifics. https://www.cypressstatus.com/

**Comment by jennifer-shehane** [comment]
The relevant status update: https://www.cypressstatus.com/incidents/lgp18sclr53g

**Comment by enp-pbadelek** [comment]
@jennifer-shehane  Hi, since we're not experiencing this issue anymore, I think we can close this ticket.
