### ISSUE TITLE
Issue with Test Continuation on Failure and NTLM Session Persistence in Cypress with BDD Cucumber Framework

### ISSUE THREAD

**Issue by Nilesh10101998** [cypress-io/cypress#30483]
### Current behavior

Hi Cypress Team,
 
I’m reaching out regarding an issue I’ve encountered while using the Cypress BDD Cucumber framework in our test scripts.
 
**Problem Summary**:

**Test Continuation After Failure**:

When running scripts, if a test scenario fails, I want the remaining scenarios to continue execution. However, the entire test suite halts upon a failure, affecting our ability to run complete regression suites and gather comprehensive failure data.
 
**NTLM Authentication Session Persistence**:

Our application requires NTLM authentication for login. The NTLM session isn’t being stored when using Cypress, causing reauthentication issues across multiple test scenarios. This hinders the seamless execution of tests since each test seems to lose the session state and fails due to login requirements.
 
**Requirements**:

Continuous Execution on Assertion Failure:
I need Cypress to continue running subsequent scenarios even if a scenario fails. Additionally, any failed assertions should be reported as failed in the final report, without stopping the overall test execution.
 
**Persistent NTLM Authentication Session**:

I am looking for guidance on how to store the NTLM authentication session or workaround methods that allow the session to persist across tests, thus eliminating the need to log in before each scenario.
 
Could you please provide a solution or any recommended practices to handle these issues effectively? Your guidance would greatly help in optimizing our test automation flow.
 

### Test code to reproduce

..

### Cypress Version

13.15.1

### Node version

21.1.0

### Operating System

Windows 10

**Comment by jennifer-shehane** [comment]
@Nilesh10101998 I'd recommend reading our docs https://docs.cypress.io/app/get-started/why-cypress or asking in [community chat](https://on.cypress.io/chat) The issues are reserved for bugs within Cypress, so I'll be closing this.
