### ISSUE TITLE
Support Angular v19

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#30498]
### What would you like?

The Angular 19 Release Candidate just recently launched, meaning Cypress can spike into the effort to support Angular 19.

### Why is this needed?

To keep up to date with supported Component testing framework versions

**Comment by MikeMcC399** [comment]
@AtofStryker 

- How does this issue differ from https://github.com/cypress-io/cypress/issues/30175 ? Are they duplicates or is there something additional in this one?

**Comment by AtofStryker** [comment]
@MikeMcC399 its a duplicate 🥴 . I thought I made an original and then I couldn't find it. Thanks for digging it up! I'm going to close this in favor of #30175
