### ISSUE TITLE
Release 3.1.4 does not contain Typescript Omit definition

### ISSUE THREAD

**Issue by ytmagalhaes** [cypress-io/cypress#3053]
### Current behavior:

Under releases for [3.1.4](https://github.com/cypress-io/cypress/releases) you can see this line:

- TypeScript Omit and @ts-ignore combination #3024

But actually when inspecting the code in `index.d.ts`, under line 3937 you can see it's still using the old code. See https://github.com/cypress-io/cypress/blob/v3.1.4/cli/types/index.d.ts#L3937

Version 3.1.4 came out 8 days ago, the pull request that fixed this issue is this one https://github.com/cypress-io/cypress/pull/3031 which has been merged roughly 19 hours ago, so this change has not happened yet.

### Desired behavior:

To fix the Omit reference on Typescript which until fixed will cause TSlint to flag it up as an error and fail compilation.

### Steps to reproduce: (app code and test code)

Run Cypress 3.1.4 with TSLint installed.

### Versions

Tested for: Cypress 3.1.4, Windows, Chrome

**Comment by bahmutov** [comment]
Yes, the release 3.1.4 includes bad code which is a regression from 3.1.3 and that is the _list of regressions_, not fixes!

<img width="473" alt="screen shot 2019-01-03 at 10 08 14 am" src="https://user-images.githubusercontent.com/2212006/50644705-9cd3e700-0f3f-11e9-95c9-eba45438f28f.png">

We have fixed the regression and merged it into `develop` and will release as 3.1.5 as you can see from the label on #3024 

<img width="1029" alt="screen shot 2019-01-03 at 10 09 46 am" src="https://user-images.githubusercontent.com/2212006/50644754-bd03a600-0f3f-11e9-81a5-fdbeb9350c1e.png">

**Comment by ytmagalhaes** [comment]
Oh, my bad! I totally misunderstood what was written, I'm very sorry.
