### ISSUE TITLE
Support Vite 6 with @cypress/vite-dev-server

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#30591]
### What would you like?

Vite 6 beta is currently out. To continue support of bundler updates, Cypress should add support for Vite 6 to keep up with latest trends in bundling and Component Testing

~Vite 6 looks to require being used as an esm package. so we likely need to change the way we import it (see https://github.com/cypress-io/cypress/issues/28373#issuecomment-2219330833)~ this change was not implemented in vite 6

### Why is this needed?

keep up to date with latest bundlers

### Other

see:
#28373
#29557

**Comment by MikeMcC399** [comment]
https://github.com/vitejs/vite/discussions/15886#discussioncomment-11170973 indicates that the release of Vite 6 is in next couple of weeks.

Check back on https://vite.dev/blog.html for any announcement.

**Comment by MikeMcC399** [comment]
[vite@6.0.0](https://github.com/vitejs/vite/releases/tag/v6.0.0) release has now taken place.

**Comment by AtofStryker** [comment]
> [vite@6.0.0](https://github.com/vitejs/vite/releases/tag/v6.0.0) release has now taken place.

the timing could not be better 😄
