### ISSUE TITLE
Desktop gui error messages not stripping ansi characters on linux

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3064]
Ansi characters are not stripped before being send to the desktop gui on linux

![image](https://user-images.githubusercontent.com/14625260/50713719-15bc6700-1044-11e9-8534-77f03411abf7.png)

```
SyntaxError: /home/owner/Desktop/cypress/packages/driver/test/cypress/integration/commands/actions/click_spec.js: Unexpected token (70:3)

  68 |       return cy.get('#button').click()
  69 |     })
> 70 | >>>>>>HWA
     |    ^
  71 |     it('sends native mousedown event', (done) => {
  72 |       const $btn = cy.$$('#button')
  73 |  while parsing file: /home/owner/Desktop/cypress/packages/driver/test/cypress/integration/commands/actions/click_spec.js
```

OS: ubuntu - Linux 
vscode integrated terminal

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
