### ISSUE TITLE
run --quiet CLI option outputs test steps

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#30661]
### Current behavior

The [cypress run --quiet](https://docs.cypress.io/app/references/command-line#Options) CLI option does not suppress all Cypress `stdout` output. Test spec steps, such as the following, are output:

```text
  template spec
    ✓ passes (421ms)


  1 passing (2s)
```

### Desired behavior

According to [cypress run Options](https://docs.cypress.io/app/references/command-line#Options), there should be no `stdout` output if `--quiet` or `-q` are passed:

| Option          | Description                                                                                                                                     |
| --------------- | ----------------------------------------------------------------------------------------------------------------------------------------------- |
| `--quiet`, `-q` | If passed, Cypress output will not be printed to `stdout`. Only output from the configured [Mocha reporter](https://docs.cypress.io/app/tooling/reporters) will print. |

In a project with no Mocha reporter configured, running Cypress in a `bash` shell, the output from:

```shell
npx cypress run --quiet
```

and

```shell
npx cypress run > /dev/null
```

should be identical.

### Test code to reproduce

Scaffold a Cypress E2E project with the single default `cypress/e2e/spec.cy.js`

```js
describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})
```

Execute:

```shell
npx cypress run --quiet
```

### Cypress Version

`13.16.0`

### Node version

`v22.11.0` LTS

### Operating System

Ubuntu `24.04.1` LTS

### Debug Logs

```shell
$ npx cypress run --quiet

DevTools listening on ws://127.0.0.1:39903/devtools/browser/01a687fe-8df0-41a4-b4b4-67217f4a1d1f


  template spec
    ✓ passes (421ms)


  1 passing (2s)
```

### Other

- Related issue https://github.com/cypress-io/cypress/issues/27631

**Comment by ryanthemanuel** [comment]
@MikeMcC399, [by default](https://docs.cypress.io/app/tooling/reporters#Built-in-reporters) we use the [spec mocha reporter](https://mochajs.org/#spec) so I think the test steps, etc. are accurate to what the doc says. The dev tools output would ideally not be present though i think?

**Comment by MikeMcC399** [comment]
@ryanthemanuel 

Thanks for putting me right! The CLI `--quiet` option documentation doesn't make it clear about the built in https://mochajs.org/#spec configuration. That could be fixed by a documentation update which I will propose in the docs repo.

The dev tools output is on `stderr`, not `stdout`, so it shouldn't be suppressed by `--quiet`. See https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md#protocol-fundamentals

> DevTools listening on ws://127.0.0.1:39903/devtools/browser/01a687fe-8df0-41a4-b4b4-67217f4a1d1f

Closing as "works as designed".

**Comment by MikeMcC399** [comment]
- Documentation updated through PR https://github.com/cypress-io/cypress-documentation/pull/6016
