### ISSUE TITLE
cy.request(): allow cy.request not to fail under non 2xx/3xx status codes

### ISSUE THREAD

**Issue by tormoseng** [cypress-io/cypress#307]
I need to strip out a token from a request that returns HTTP 401. That is currently not possible.

**Comment by brian-mann** [comment]
So after looking at this... this is actually already part of `cy.request` and was documented here:

https://docs.cypress.io/v1.0/docs/request#section-options

You just need to pass `failOnStatus: false`.

**Comment by brian-mann** [comment]
Fixed in [`0.18.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0181-12112016).

**Comment by cmpDrone** [comment]
@Team - I am new to this so, i need the syntax as to how to pass the failOnStatus: false and where do i pass this

**Comment by cmpDrone** [comment]
I found the solution myself - 
cy.request({method:'POST',url:'https://xxxx.in', body:{userName: "ghnfhg", password: "ghnfhg"},failOnStatusCode: false})

**Comment by brian-mann** [comment]
It's in the documentation here https://docs.cypress.io/api/commands/request.html#Usage

it's also in many recipes you just need to search for `cy.request`
