### ISSUE TITLE
Not able to access objects in window DOM object

### ISSUE THREAD

**Issue by Manishku99251** [cypress-io/cypress#3070]
### Current behavior:
I am unable to access the window.utag_data object for my website as it is loading the cypress in a browser the browser console which i am seeing is for the url "https://www.expedia.com/__/#/tests/integration/examples/expedia.js"
but i want the url to be "https://www.expedia.com" then only i will be able to see utag_data object in my browser console.

### Desired behavior:
I want to access the window.utag_data object inside the automation developer console browser so that i can use that object for assertions and testing the website the utag_data object contains the various attributes defining the current page details e.g pagename ,pagetype,siteBrand etc.

Below is the piece of code i am writing to get the object data in my variable.
describe('trying to get the utag_data',function(){
	
	
	it('Trying to execute js command',function(){
	
	var object_data = cy.window().then((win)=>{
				//console.log("the UDO object data is "+win.utag_data)
				return win.utag_data
			})
		
		
		})
})
### Steps to reproduce: (app code and test code)

1. goto expedia.com
2. open developer console and type "utag_data"
3. i want this object to be verified in my tests like 
"expect(utag_data['SiteBrand']).to.equal('Expedia')"

Thanks in Advance please feel free to mail kumarmanish2048@gmail.com

### Versions

![image](https://user-images.githubusercontent.com/18353269/50770518-9c27b180-12ad-11e9-98a9-8dd1d69e17fb.png)

What i am seeing in cypress controlled browser when i am writing utag_Data manually
![image](https://user-images.githubusercontent.com/18353269/50770590-e0b34d00-12ad-11e9-9cda-30700965c88f.png)

**Comment by bahmutov** [comment]
please read how Cypress chained commands work in https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous

Just moved your assertion to the chain of commands, for example use `its` and assertion
```js
it('Trying to execute js command',function(){
  cy.window()
    .its('utag_data')
    .should('equal', 'Expedia')
})
```

or use `then`

```js
it('Trying to execute js command',function(){
  cy.window()
    .then(win => {
      expect(win.utag_data).to.equal('Expedia')
    })
})
```

**Comment by SUSANO-O** [comment]
Hello good day how can I find  more examples about cy.window and cy.document in GitHub ? Thank's

**Comment by bahmutov** [comment]
@SUSANO-O see https://on.cypress.io/document and https://on.cypress.io/window
