### ISSUE TITLE
Review need for React 19 RC in Component Testing

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#30722]
- Follows on from https://github.com/cypress-io/cypress/issues/29470

### What would you like?

Review if it is necessary to support React 19 release candidate in Cypress 14 and potentially remove `^19.0.0-rc`.

### Why is this needed?

React 19 was released on Dec 5, 2024. See [React v19](https://react.dev/blog/2024/12/05/react-19) blog post, making the release candidate unneeded.

### Other

```text
$ npm view react dist-tags
{
  latest: '19.0.0',
  beta: '19.0.0-beta-26f2496093-20240514',
  rc: '19.0.0-rc.1',
  next: '19.0.0-rc-1c9b1387-20241204',
  canary: '19.0.0-rc-1c9b1387-20241204',
  experimental: '0.0.0-experimental-1c9b1387-20241204'
}
```

cc: @AtofStryker

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Yah @AtofStryker is workin on removing it here: https://github.com/cypress-io/cypress/pull/30723

**Comment by MikeMcC399** [comment]
@jennifer-shehane 
> @MikeMcC399 Yah @AtofStryker is workin on removing it here: #30723

Good move! It should make things simpler in the long run.

**Comment by MikeMcC399** [comment]
- Closing, as this issue only asked for a review, and that has already happened in #30723
