### ISSUE TITLE
npm install error [example:install] npm ERR! 404 Not Found: event-stream@3.3.6

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#3072]
`event-stream@3.3.6` was removed from npm because of a security vulnerability found in that version. More info here: https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

### Current behavior:

```
[example:install    ] npm ERR! code E404
[example:install    ] npm ERR! 404 Not Found: event-stream@3.3.6
```

### Desired behavior:

No error

### Steps to reproduce: (app code and test code)

In the root of the Cypress project, run `npm install`

### Versions

Cypress: 3.1.4
node: 8.14.0
npm: 6.5.0

**Comment by bahmutov** [comment]
I believe this is coming from cypress-example-kitchensink, which has already been updated, I just need to bring in the latest version

**Comment by NicholasBoll** [comment]
@bahmutov Yeah. I thought I just had to update a lock file, but lockfiles are ignored. `cypress-example-ketchensink` uses an exact match in `package.json`, but that doesn't mean transitive dependencies (like event-stream) are locked. Probably the best thing to do is add package-lock files to git so that lockfile versions are guaranteed by the CI system.

**Comment by bahmutov** [comment]
yes, agree, we now pinned prod dependencies and started using renovate bot, but still have not switched to package locks yet
