### ISSUE TITLE
Support recording videos in Chrome

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3074]
### Current behavior:

```
Warning: Cypress can only record videos when using the built in 'electron' browser.

You have set the browser to: 'chrome'

A video will not be recorded when using this browser.
```

I'm using the Module API as documented here:  https://github.com/cypress-io/cypress/issues/416#issuecomment-337400871

### Desired behavior:

Cypress should support video capture when using Chrome.

### Versions

```
Cypress package version: 3.1.4
Cypress binary version: 3.1.4
```

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/1767
