### ISSUE TITLE
Incorrect type definitions for `.then`

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#3075]
### Current behavior:

According to the documentation for `.then`, `options` optionally come first: https://docs.cypress.io/api/commands/then.html
```ts
.then(callbackFn)
.then(options, callbackFn)
```

The type definitions for `.then` put options optionally after the callback.

### Desired behavior:

No type error

### Steps to reproduce: (app code and test code)

The following code works at runtime, but has Typescript errors
```ts
/// <reference types="Cypress" />
//@ts-check

describe('then', () => {
  it('should allow custom timeout', () => {
    const sleep = time => new Promise(resolve => setTimeout(resolve, time))

    cy.wrap(5000).then({ timeout: 6000 }, sleep) // TS error, but works at runtime
  })
})

```

### Versions

Cypress: 3.1.4

There are 2 ways to fix this:
1. Fix type definitions to be consistent with documentation and runtime. This is the easiest and has no breaking changes or modifications to runtime code. Nothing will break in the field
1. Fix runtime to have options after callback. This is consistent with other commands. To prevent breaking changes, both orders would have to be supported using runtime detection of the arguments. The type signature would remain unchanged.

**Comment by NicholasBoll** [comment]
@bahmutov @brian-mann I already have a solution ready-to-go for option #1. If that is the desired fix, I can create a PR to fix this issue. It is probably not very common to add a custom timeout to `.then` which is why we didn't noticed before.

**Comment by bahmutov** [comment]
I also vote for option `1` - just keep the same API for types as for current command http://on.cypress.io/then

**Comment by jennifer-shehane** [comment]
I vote for option 1 as well. 

We previously had someone ask about this here: https://github.com/cypress-io/cypress/issues/1772

**Comment by NicholasBoll** [comment]
PR coming soon
