### ISSUE TITLE
cy.request(): turning off automatic redirect

### ISSUE THREAD

**Issue by tormoseng** [cypress-io/cypress#308]
No description needed.

**Comment by brian-mann** [comment]
Passing `followRedirect: false` to `cy.request` should turn off automatic redirect following.

This will enable users to extract `location` headers or verify status codes.

We should also be nice and include a `redirectedTo` property on the response object from `cy.request`.

`location` headers may include a relative or absolute-relative pathname so we should also resolve to a fully qualified URL when providing the `redirectedTo` property.

**Comment by brian-mann** [comment]
Fixed in [`0.18.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0181-12112016).

**Comment by ray-kim-12** [comment]
Hi,

I am following this [example](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__single-sign-on/cypress/integration/logging-in-single-sign-on-spec.js) and am getting the  `TypeError: Parameter 'url' must be a string, not undefined` as there is no longer a `redirectedToUrl` property

**Comment by jennifer-shehane** [comment]
@ray-kim-12 Could you past the code you ran that is not working? I'm not following when you say:

> there is no longer a redirectedToUrl property attached to the resp parameter
