### ISSUE TITLE
Interactive Mode

### ISSUE THREAD

**Issue by 7ynk3r** [cypress-io/cypress#30806]
### What would you like?

ATM there's not way for `cy` commands to work in dev tools, so every time I need to test a a commands, I need to run the test which takes time due to login and other steps in the tests. I tried this using `cy.pause()` and `debugger`, the result is the same. 

### Why is this needed?

I waste so much time just figuring out selectors that this feels stupid to the point that using coordinates and re-recording might be more time effective

### Other

Optimize for creating tests, where having the right selector consumes most of the time. Also, the debugger sections in the docs aren't useful. Of course I can use `cy.log` and `cy.then` together with debugger, but what for? There's no way to run commands, just observe the variables in the scope.

**Comment by jennifer-shehane** [comment]
Closing as duplicate of https://github.com/cypress-io/cypress/issues/27215
