### ISSUE TITLE
Cypress says load event isn't fired, but it is fired

### ISSUE THREAD

**Issue by lMartin3** [cypress-io/cypress#30803]
### Current behavior

I have a setup with two extremely simple web applications. One of them is an oauth + openid identity provider (call it "auth portal").

After writing a very simple test, just going into the application (app.example.com) and clicking the log-in button which makes a couple redirects, cypress says the auth application never fires the "load" event.

This is what a typical log-in flow from the application looks like
![image](https://github.com/user-attachments/assets/dd9bd241-3f3c-4041-9f3c-0f94d0a47bb8)

The auth application loads in 500ms according to chrome dev tools, and I added a console log that fires when the site is loaded, but for some reason cypress doesn't pick it up.

Unfortunately I cannot share much information about the applications themselves, but what I can say is that there isn't any page that takes more than 1000ms to load, that's for sure.

### Desired behavior

Cypress should recognize when the page loads

### Test code to reproduce

```js
  it('Is able to reach log-in website', () => {
    cy.visit('https://app.[removed]');
    cy.get("#oauth-login").click();
  });
```

### Cypress Version

13.17.0

### Node version

18.17.0

### Operating System

Windows 11 pro 22631.4602 1000.22700.1055.0

**Comment by jennifer-shehane** [comment]
@lMartin3 Is the application under test hitting the `window:load` event in Cypress? Or can you put a debugger to see the `load` event firing from the app under test? https://docs.cypress.io/api/cypress-api/catalog-of-events#App-Events We're looking for that exact event to fire.

**Comment by lMartin3** [comment]
@jennifer-shehane Yep I had added a debugger and the event was firing correctly. However, I found the issue and it was a bit weird.

The test flow was:

1. Navigate to app
2. Find the login button and click it
3. The login button redirects to auth/oauth/access?code=etcetcetc
4. From there, it redirects to auth/login, which has a login form
5. After filling in the details, it clicks log in
6. If the login is successful, it redirects to app/oauth/code?=etcetc
7. that redirects to the app's landing page


The problem was that the redirection between step 3 and 4 would first lead you to http://auth/login rather than https://auth/login. I was serving this through cloudflare and HTTPS rewrites were on, so technically it was first vising http://auth/login and then it redirected that to https://auth/login.

For some reason, that worked flawlessly for users, but in cypress chrome and other browsers wouldn't even allow making a GET request to http://auth/login since auth/oauth/access was served over HTTPS.

What's weird is that in the preview, cypres would get to step 4 without any issues where it would see the login form, and there it would throw the "load event not fired" issue.

Anyways, thank you for your time
