### ISSUE TITLE
Cypress cannot write to the cache directory due to file permissions (Even as root)

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#3081]
Hello,

Cypress cannot write to the cache directory due to file permissions

(Wrote in the chat but just saw other peoples concerns being solved and mine left alone)

I'm running NPM as root when installing things.

From logs
```
bitnami@bitnami-djangostack-dm-508e:~/apps/logima/vue-storefront$ sudo npm install --no-save vue-eslint-parser@2.0.1-beta.2
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/jest as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/jest
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/uglifyjs as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/uglify-js
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/semver as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/semver
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/nopt as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/nopt
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/json5 as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/json5
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/jsesc as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/jsesc
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/esvalidate as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/esprima
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/esparse as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/esprima
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/browserslist as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/browserslist
npm WARN rm not removing /opt/bitnami/apps/logima/vue-storefront/node_modules/.bin/babylon as it wasn't installed by /opt/bitnami/apps/logima/vue-storefront/node_modules/babylon

node-sass@4.9.3 install /opt/bitnami/apps/logima/vue-storefront/node_modules/node-sass
node scripts/install.js

Unable to save binary /opt/bitnami/apps/logima/vue-storefront/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/opt/bitnami/apps/logima/vue-storefront/node_modules/node-sass/vendor'
at Object.fs.mkdirSync (fs.js:885:18)
at sync (/opt/bitnami/apps/logima/vue-storefront/node_modules/mkdirp/index.js:71:13)
at Function.sync (/opt/bitnami/apps/logima/vue-storefront/node_modules/mkdirp/index.js:77:24)
at checkAndDownloadBinary (/opt/bitnami/apps/logima/vue-storefront/node_modules/node-sass/scripts/install.js:114:11)
at Object.<anonymous> (/opt/bitnami/apps/logima/vue-storefront/node_modules/node-sass/scripts/install.js:157:1)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
errno: -13,
code: 'EACCES',
syscall: 'mkdir',
path: '/opt/bitnami/apps/logima/vue-storefront/node_modules/node-sass/vendor' }

cypress@3.0.3 postinstall /opt/bitnami/apps/logima/vue-storefront/node_modules/cypress
node index.js --exec install

Cypress cannot write to the cache directory due to file permissions
Failed to access /root/.cache/Cypress:

EACCES: permission denied, mkdir '/root/.cache/Cypress'
Platform: linux (Debian - 9.6)
Cypress Version: 3.0.3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.0.3 postinstall: `node index.js --exec insta

5568 error Failed at the cypress@3.1.4 postinstall script.
5568 error This is probably not a problem with npm. There is likely additional $
5569 verbose exit [ 1, true ]
```

**Comment by jennifer-shehane** [comment]
Can you make sure to read up on the discussion on this issue https://github.com/cypress-io/cypress/issues/1281 involving permissions?

**Comment by jennifer-shehane** [comment]
Hey @Decntdefalt, any update on this? Were you able to get the permissions sorted?

**Comment by WinstonN** [comment]
Hello
This might not be 100% correct, but you can get away with
`npm install -g cypress --unsafe-perm --silent`

**Comment by jennifer-shehane** [comment]
Closing due to no response. Please comment if there is a suspected bug with Cypress.

**Comment by ccheraa** [comment]
`npm install -g cypress --unsafe-perm --silent` didn't work for me

- Ubuntu 20.04.1 LTS
- node v10.22.0
- npm 6.14.6

**Comment by okgolove** [comment]
Since 7 version NPM removed some parameters like user and changed behaviour for NPM running from root.

https://github.com/npm/cli/blob/latest/changelogs/CHANGELOG-7.md#all-lifecycle-scripts
>When npm is run as root, scripts are always run with the effective uid and gid of the working directory owner.

Check a directory you run npm from permissions:
```
# Linux
stat -c 'userid - %u, groupid - %g' $PWD

#MacOS
stat -f 'userid - %u, groupid - %g' $PWD
```

In case of it is not 0 (root) and you run `npm i` or `npm ci` from root cypress won't be able to create directory `/root/.cache/Cypress`

**Comment by webia1** [comment]
How can I configure another cache directory in a Jenkins file for cypress? Are there other possibilities? 
Thanks for feedbacks, kind rgds

**Comment by EthanDunfordAspect** [comment]
Any solution for this?

**Comment by saudkhanbpk** [comment]
my ubuntu show me that error can anyone help please:
npm ERR! code 1
npm ERR! path /media/mustafa/C8180BD5180BC184/Books and tutorials/Projects/ImmoBelgium/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c node index.js --exec install
npm ERR! Cypress cannot write to the cache directory due to file permissions
npm ERR! 
npm ERR! See discussion and possible solutions at
npm ERR! https://github.com/cypress-io/cypress/issues/1281
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Failed to access /root/.cache/Cypress:
npm ERR! 
npm ERR! EACCES: permission denied, mkdir '/root/.cache/Cypress'
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Platform: linux-x64 (Ubuntu - 20.04)
npm ERR! Cypress Version: 9.7.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-06T06_03_28_655Z-debug-0.log

**Comment by RalphBragg** [comment]
I have the same problem on alpine linux node 16

**Comment by Loongphy** [comment]
1. install dependencies https://docs.cypress.io/guides/getting-started/installing-cypress
3. use local cypress
```
./node_modules/.bin/cypress install
```
4. run test
```
./node_modules/.bin/cypress open
```

**Comment by Enough7** [comment]
`npm install` instead of `sudo npm install` worked for me

**Comment by appugouda** [comment]
> `npm install` instead of `sudo npm install` worked for me

this worked for me. Thanks

**Comment by nathan5x** [comment]
Hi Team,

I'm also getting a similar error on Ubuntu based Docker machine. 

```
npm ERR! code 1
npm ERR! path /home/app/ui/workspace/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c -- node index.js --exec install
npm ERR! Note: Overriding Cypress cache directory to: /home/.cache/cypress
npm ERR! 
npm ERR!       Previous installs of Cypress may not be found.
npm ERR! 
npm ERR! Installing Cypress (version: 9.5.3)
npm ERR! 
npm ERR! [STARTED] Task without title.
npm ERR! [TITLE]  Downloading Cypress      0% 0s
npm ERR! [TITLE]  Downloading Cypress      1% 20s
npm ERR! [TITLE]  Downloading Cypress      5% 6s
npm ERR! [TITLE]  Downloading Cypress      8% 5s
npm ERR! [TITLE]  Downloading Cypress      10% 5s
npm ERR! [TITLE]  Downloading Cypress      13% 4s
npm ERR! [TITLE]  Downloading Cypress      17% 3s
npm ERR! [TITLE]  Downloading Cypress      21% 3s
npm ERR! [TITLE]  Downloading Cypress      24% 3s
npm ERR! [TITLE]  Downloading Cypress      28% 3s
npm ERR! [TITLE]  Downloading Cypress      32% 2s
npm ERR! [TITLE]  Downloading Cypress      35% 2s
npm ERR! [TITLE]  Downloading Cypress      39% 2s
npm ERR! [TITLE]  Downloading Cypress      42% 2s
npm ERR! [TITLE]  Downloading Cypress      46% 2s
npm ERR! [TITLE]  Downloading Cypress      49% 2s
npm ERR! [TITLE]  Downloading Cypress      53% 2s
npm ERR! [TITLE]  Downloading Cypress      56% 1s
npm ERR! [TITLE]  Downloading Cypress      60% 1s
npm ERR! [TITLE]  Downloading Cypress      64% 1s
npm ERR! [TITLE]  Downloading Cypress      68% 1s
npm ERR! [TITLE]  Downloading Cypress      72% 1s
npm ERR! [TITLE]  Downloading Cypress      75% 1s
npm ERR! [TITLE]  Downloading Cypress      79% 1s
npm ERR! [TITLE]  Downloading Cypress      83% 1s
npm ERR! [TITLE]  Downloading Cypress      85% 0s
npm ERR! [TITLE]  Downloading Cypress      88% 0s
npm ERR! [TITLE]  Downloading Cypress      91% 0s
npm ERR! [TITLE]  Downloading Cypress      94% 0s
npm ERR! [TITLE]  Downloading Cypress      97% 0s
npm ERR! [TITLE]  Downloaded Cypress     
npm ERR! [SUCCESS]  Downloaded Cypress     
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be unzipped.
npm ERR! 
npm ERR! Search for an existing issue or open a GitHub issue at
npm ERR! 
npm ERR! https://github.com/cypress-io/cypress/issues
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Error: EACCES: permission denied, mkdir '/home/.cache/cypress/9.5.3'
npm ERR! 
npm ERR! ----------
npm ERR! 
npm ERR! Platform: linux-x64 (Ubuntu - 20.04)
npm ERR! Cypress Version: 9.5.3
npm ERR! [FAILED] The Cypress App could not be unzipped.
npm ERR! [FAILED] 
npm ERR! [FAILED] Search for an existing issue or open a GitHub issue at
npm ERR! [FAILED] 
npm ERR! [FAILED] https://github.com/cypress-io/cypress/issues
npm ERR! [FAILED] 
npm ERR! [FAILED] ----------
npm ERR! [FAILED] 
npm ERR! [FAILED] Error: EACCES: permission denied, mkdir '/home/.cache/cypress/9.5.3'
npm ERR! [FAILED] 
npm ERR! [FAILED] ----------
npm ERR! [FAILED] 
npm ERR! [FAILED] Platform: linux-x64 (Ubuntu - 20.04)
npm ERR! [FAILED] Cypress Version: 9.5.3
```

This is the command I'm running 
```
bash -c "chmod -R 775 /home/.cache/cypress/"
bash -c "CYPRESS_CACHE_FOLDER=/home/.cache/cypress npm ci --legacy-peer-deps"
```

PS: It didn't work with `chmod` as well.

Any help is appreciated.

Thanks,
Nathan

**Comment by nathan5x** [comment]
> `npm install -g cypress --unsafe-perm --silent` didn't work for me
> 

Same! This didn't work for me as well. 

Did anyone else find an alternative solutions? Any help is appreciated. 

Thanks!

**Comment by jordanpowell88** [comment]
Does [this](https://github.com/cypress-io/cypress/issues/3081#issuecomment-1378947708) work for you @nathan5x ?

**Comment by warrensplayer** [comment]
Closing due to no response. Please reopen a new issue and link to this one if you are still having an issue.

**Comment by thestalnaker** [comment]
getting this error too:

#0 21.97 npm ERR! code 1
#0 21.97 npm ERR! path /var/www/html/node_modules/cypress
#0 21.97 npm ERR! command failed
#0 21.97 npm ERR! command sh -c node index.js --exec install
#0 21.97 npm ERR! Cypress cannot write to the cache directory due to file permissions
#0 21.97 npm ERR! 
#0 21.97 npm ERR! See discussion and possible solutions at
#0 21.97 npm ERR! https://github.com/cypress-io/cypress/issues/1281
#0 21.97 npm ERR! 
#0 21.97 npm ERR! ----------
#0 21.97 npm ERR! 
#0 21.97 npm ERR! Failed to access /var/www/.cache/Cypress:
#0 21.97 npm ERR! 
#0 21.97 npm ERR! EACCES: permission denied, mkdir '/var/www/.cache'
#0 21.97 npm ERR! 
#0 21.97 npm ERR! ----------
#0 21.97 npm ERR! 
#0 21.98 npm ERR! Platform: linux-x64 (Debian - 11.7)
#0 21.98 npm ERR! Cypress Version: 12.15.0
#0 22.02 
#0 22.02 npm ERR! A complete log of this run can be found in:
#0 22.02 npm ERR!     /var/www/html/.npm/_logs/2023-06-23T18_14_16_626Z-debug.log
------
Dockerfile:57
--------------------
  55 |     ENV npm_config_cache /var/www/html/.npm
  56 |     ARG NODE_ENV="production"
  57 | >>> RUN npm ci && npm run ${NODE_ENV}
  58 |     USER root
  59 |     ENTRYPOINT ["bash", "./docker/entrypoint.sh" ]

**Comment by mike-plummer** [comment]
@thestalnakergroup This issue has been closed for some time. Per the previous comment, if you're still encountering this problem using the latest version of Cypress you should open a new issue and provide all information requested in the issue template. Most important is a reproducible example we can use to diagnose your issue.
