### ISSUE TITLE
Add a configuration option for suppressing Command Logs

### ISSUE THREAD

**Issue by jonathanconway** [cypress-io/cypress#3087]
I want to turn off logging on all of my commands, in order to reduce clutter in the lefthand side of the Test Runner.

### Current behavior:

In order to turn off logging, I have to set log to false in the options of every individual command.

For example:

```js
const element1 = cy.get("#id", { log: false });
element1.should("be.visible");
const element2 = element1.find(".class", { log: false });
element1.should("be.visible");
```

### Desired behavior:

I want to be able to set just one Cypress configuration option, to turn command logging off globally.

```js
{
    ...
    "loggingOptions": {
        "commands": false
    }
}
```

Then I can omit log options from my command calls:

```js
...
const element1 = cy.get("#id");
element1.should("be.visible");
const element2 = element1.find(".class");
element1.should("be.visible");
```

### Versions

Cypress v3.1.0.

**Comment by jennifer-shehane** [comment]
Hey @jonathanconway, I'm curious to hear what you find as the most useful part of the test runner without the commands being logged. Are you tracking XHR requests? url changes? Anything in the Command Log at all?

**Comment by jonathanconway** [comment]
Hi @jennifer-shehane, thanks for getting back to me about this. I had a think about it and actually I think this setting isn't necessary and would be inappropriate, because I only need to suppress logging for a sub-set of the tests I'm writing, not across-the-board using a global setting. If it's Ok with you, I'll close it for now.

**Comment by Machiaweliczny** [comment]
@jennifer-shehane
I have similar request. But I don't want configuration option but API to do so.

Motivation:
I have my high level driver that is using cypress under the hood which looks like this:
```
$.PageA.enter()
$.PageA.doA():
$.PageA.doB();
$.PageA.assertFoo()
```
Which basically also generates log entries in command log automatically based on function called. 
But these operations are complex and require a lot of clicking/filling forms etc. so to avoid spam I need to pass `{ log: false }` to every basic operation like `cy.get`, `should`, `click` etc.

I would prefer to call `Cypress.basicLogs(false)` at start and only when I see failure I could go to definition of e.g. `$PageA.assertFoo()` and put there `Cypress.basicLogs(true)` for debugging.

**Comment by jennifer-shehane** [comment]
@Machiaweliczny lease [open a new issue](https://github.com/cypress-io/cypress/issues/new) detailing your feature request.
