### ISSUE TITLE
Failed downloading the Cypress binary

### ISSUE THREAD

**Issue by drphelps** [cypress-io/cypress#3089]
### Current behavior:
We are experiencing intermittent connectivity issues when attempting to install the binary on a Linux box.
```
URL: https://download.cypress.io/desktop/3.1.3?platform=linux&arch=x64
Error: Failed downloading the Cypress binary.
Response code: 503
Response message: Service Unavailable
```
See https://github.com/cypress-io/cypress/issues/1280

### Desired behavior:
We can install the lib

### Steps to reproduce: (app code and test code)
Install via Yarn

### Versions
```
Platform: linux (Ubuntu Linux - 16.04)
Cypress Version: 3.1.3
```

**Comment by jennifer-shehane** [comment]
Hey @drphelps, we were experiencing a brief outage of our download service that has since been resolved. You can review our status and any outages in the future here: https://status.cypress.io/

**Comment by ramiroiblanco** [comment]
I've been trying to install cypress for the past week and I am getting this error:

URL: https://download.cypress.io/desktop/3.4.0?platform=win32&arch=x64
Error: connect ETIMEDOUT 104.25.214.23:443

As a work around I have been trying to use CYPRESS_INSTALL_BINARY to install the binary I have download but not having much luck either.
