### ISSUE TITLE
Test Cypress test runner against beta / canary versions of Chrome

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3096]
## Problem

New versions of Chrome browser regularly break Cypress because of its changed behavior, and we have to catch up and find browser CLI flags that would fix the new problem. 

## Proposal

It would be nice to periodically run a small project like cypress-test-tiny or cypress-example-kitchensink against upcoming Chrome version to find out about potential breaking change before that version of Chrome is released as stable.

**Comment by jennifer-shehane** [comment]
Chromium Versions: https://omahaproxy.appspot.com/

**Comment by jennifer-shehane** [comment]
An example of a PR that I need to test exclusively on Chromium 72.0.3605.0+ https://github.com/cypress-io/cypress/pull/3049

**Comment by flotwig** [comment]
Based on team discussions, the solution to this looks something like this:

* create a new driver-integration-tests-chrome-beta job
* update driver-integration-tests-chrome and driver-integration-tests-chrome-beta to install Chrome from a version stored in some text file in this repository
* a GitHub action that regularly checks what the latest stable/beta chrome versions are
	* if a new version is available, opens a pull request to update that version text file (`known-good-chrome-version.json`?) like dependabot does
	* automerges PR on pass, requests reviewer on fail

**Comment by jennifer-shehane** [comment]
This was released in develop.
