### ISSUE TITLE
Wrong machine count in Cypress Dashboard

### ISSUE THREAD

**Issue by maximilianschmid** [cypress-io/cypress#3097]
### Current behavior:
Wrong machine count in Cypress Dashboard

<img width="1792" alt="screenshot 2019-01-08 at 23 46 54" src="https://user-images.githubusercontent.com/574203/50863721-e721f180-139f-11e9-9721-35943bf08ef3.png">

### Desired behavior:
Show correct machine count

### Steps to reproduce: (app code and test code)
Checkout test run https://dashboard.cypress.io/#/projects/87029743-0a51-4f4a-a7f3-4f92905b54ca/runs/7420/specs

### Versions
Cypress v3.1.4

**Comment by jennifer-shehane** [comment]
Yes, I believe this is a miscalculation while the status of the run is 'running'. Can definitely look into this.

**Comment by maximilianschmid** [comment]
Update: now it shows the correct machine count
<img width="1792" alt="screenshot 2019-01-09 at 20 22 04" src="https://user-images.githubusercontent.com/574203/50923082-5ce39700-144c-11e9-95e7-31f0df8bd7a6.png">

**Comment by jennifer-shehane** [comment]
Hey @maximilianschmid, this was indeed a bug that only displays while the run is in a status of 'running'. It should be fixed soon, so will close when it is released.

**Comment by jennifer-shehane** [comment]
This should be fixed now!
