### ISSUE TITLE
We detected that the Chromium Renderer process just crashed.

### ISSUE THREAD

**Issue by Akshaya0309** [cypress-io/cypress#3099]
### Current behavior:
Not able to run  cypress with Gradle task.
It was working fine previously.
![image](https://user-images.githubusercontent.com/42965216/50890883-5da00d00-13fb-11e9-977e-c71966b51583.png)
Jenkins Code-
```js
node('ndp') {
    checkout scm

    def props = readProperties file: '.env'
    String SLACK_MESSAGE_FAIL = "Build ${env.BUILD_NUMBER} - Cypress Regression FAILED (<${env.BUILD_URL}|Jenkins>)"
    String SLACK_MESSAGE_SUCCESS = "Build ${env.BUILD_NUMBER} - Cypress Regression SUCCESS (<${env.BUILD_URL}|Jenkins>)"

    try {

        stage('Setup') {
            sh './gradlew setup -Penv=reg'
        }

        stage('Test') {
            parallel lint: {
                sh './gradlew lint -Penv=reg'
            },
            smoketest: {
                sh './gradlew cypressJobSeekerRegressionNVB -Penv=reg'
                sh './gradlew cypressJobSeekerRegressionINT -Penv=reg'
                sh './gradlew cypressRecruiterRegressionNVB -Penv=reg'
                sh './gradlew cypressRecruiterRegressionINT -Penv=reg'
            }
        }
        slackSend channel: props.SLACK_CHANNEL_QA, color: 'good', message: SLACK_MESSAGE_SUCCESS, teamDomain: props.SLACK_TEAM_DOMAIN, token: props.SLACK_TOKEN
        currentBuild.result = 'SUCCESS'

      } catch (Throwable err) {
        sh "./gradlew sendReportToS3 -Penv=reg -PbuildNumber=${env.BUILD_NUMBER}"
        slackSend channel: props.SLACK_CHANNEL_QA, color: 'danger', message: SLACK_MESSAGE_FAIL, teamDomain: props.SLACK_TEAM_DOMAIN, token: props.SLACK_TOKEN
        currentBuild.result = 'FAILURE'
        throw err
    }
}
```

**Gradle Task**
```
task cypressRecruiterRegressionNVB(type: .docker_compose.RunTask) {
    description = 'Run the Cypress tests'
    group = 'Test'

    service "cypress-${type}"
    containerName "${PROJECT}_smoketest_${type}"
    entryPoint 'yarn'
    command 'cy-regressiontests-rf-nvb'
}
```

**Docker compose**
```
services:
  cli-jf:
    build:
      context: docker/cli
    image: qa_cypress_jf
    volumes:
      - ".:/opt/webapp"

cypress-jf:
    build:
      context: docker/cli
    image: qa_cypress_jf
    volumes:
      - ".:/opt/webapp"
```

### Desired behavior:
It should run with gradle , jenkin and docker set up

### Steps to reproduce: (app code and test code)

./gradlew cypressJobSeekerRegressionNVB 

### Versions
Cypress3.1.3

**Comment by jennifer-shehane** [comment]
Hey @Akshaya0309, you mention that "It was working fine previously.", what has changed since then? Did you change anything in your files? Your config? You cypress version?

**Comment by Akshaya0309** [comment]
hey @jennifer-shehane .

Yeah I updated to version 3.1.4 but then I was getting another error "Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob')" So I roll back to 3.1.3 but ended with this error for two  feature files.

I have four gradle  task.
                sh './gradlew cypressJobSeekerRegressionNVB -Penv=reg'
                sh './gradlew cypressJobSeekerRegressionINT -Penv=reg'
                sh './gradlew cypressRecruiterRegressionNVB -Penv=reg'
                sh './gradlew cypressRecruiterRegressionINT -Penv=reg'


And facing only problem with

    sh './gradlew cypressJobSeekerRegressionINT -Penv=reg'
    sh './gradlew cypressRecruiterRegressionINT -Penv=reg'

   I am not able to fix this.

**Comment by jennifer-shehane** [comment]
The regression in 3.1.4 is related to this issue: https://github.com/cypress-io/cypress/issues/3008

It's not immediately obvious what is causing the Chromium crash. Are you able to run the tests locally and recreate? Be sure to select "Electron 59" as the browser when running during `cypress open` to replicate the same behavior.

**Comment by Akshaya0309** [comment]
Its working I added ' ipc: host' in docker- compose file.
