### ISSUE TITLE
sinon's chai assertion msg in command ui don't grammatically make sense when test passes

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#31]
![screen shot 2015-04-30 at 12 34 10 pm](https://cloud.githubusercontent.com/assets/1271364/7417701/f5fec0b2-ef35-11e4-9972-c02ce860baf9.png)

**Comment by brian-mann** [comment]
Fixed in [`0.18.8`](https://github.com/cypress-io/cypress/wiki/Changelog#0188-02052017).
