### ISSUE TITLE
Add cypress to eslint envs (just like mocha)

### ISSUE THREAD

**Issue by jean-moldovan** [cypress-io/cypress#3100]
Hello!

Would be super useful to have cypress available here https://eslint.org/docs/user-guide/configuring#specifying-environments, so that we do not have to configure globals manually or use something like https://github.com/standard/eslint-config-standard which adds extra complexity.

**Expected**
If I add in package.json:
```json
{
  "standard": {
    "env": ["cypress"]
  }
}
```
I should not be getting `/cypress/integration/examples/location.spec.js:3:1: 'context' is not defined.` and similar.

Cheers!

**Comment by jean-moldovan** [comment]
https://github.com/eslint/eslint/blob/master/conf/environments.js

**Comment by jean-moldovan** [comment]
Current workaround:
```
{
 "standard": {
    "env": ["browser", "mocha"],
    "globals": ["cy", "Cypress", "expect", "assert"]
  }
}
```

**Comment by jennifer-shehane** [comment]
This sounds like a great idea! It looks like this would require a PR similar to [this one](https://github.com/eslint/eslint/commit/97087fb97c9101d18ac29b00423787800169aafa#diff-325a5bb13a37b8f40092f2a1cba5aa8a) made to add another environment.

**Comment by chrisbreiding** [comment]
We can try to get Cypress on eslint's default globals, but it's ultimately up to them.

I'd recommend using our [eslint plugin](https://github.com/cypress-io/eslint-plugin-cypress) and then you can do the following:

```json
{
  "standard": {
    "env": ["cypress/globals"]
  }
}
```

**Comment by brettz9** [comment]
@chrisbreiding : Did you mean to have "standard" as a key? The plugin documents it as:

```json
{
  "env": {
    "cypress/globals": true
  }
}
```

**Comment by JonnyBeoulve** [comment]
Solved this by installing `eslint-plugin-cypress` and then adding the following to the root directory's `.eslintrc`:

```
{
   "extends": [
      "plugin:cypress/recommended"
   ]
}
```

**Comment by maddhruv** [comment]
Hey @jennifer-shehane I don't think this is valid anymore, can be closed

**Comment by brettz9** [comment]
I've submitted https://github.com/eslint/eslint/issues/14904 because ESLint itself might be willing to add "cypress" as a predefined environment.

**Comment by brettz9** [comment]
The cypress plugin could still be used for setting up best practices, but the globals could at least be set without need for the plugin.

**Comment by brettz9** [comment]
Yeah, this can probably be closed as `eslint` has frozen `env` and future versions will not have this key as per https://github.com/eslint/eslint/issues/14904#issuecomment-894874837 .

And since `eslint-plugin-cypress` has the globals without being an unduly large package, I think there is no need of a separate package just for the [Cypress globals](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/index.js#L17-L23).
