### ISSUE TITLE
Optional dev dependencies pop messages during user install

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3102]
When installing new upcoming version of Cypress 3.1.5 I see the warnings that a regular user should not see

```
> cypress@3.1.5 postinstall /private/tmp/kitchensink/node_modules/cypress
> node index.js --exec install

⚠ Warning: Forcing a binary version different than the default.

  The CLI expected to install version: 3.1.5

  Instead we will install version: /tmp/urls/cypress.zip

  These versions may not work properly together.

[11:22:02]  Unzipping Cypress       [started]
[11:22:25]  Unzipping Cypress       [completed]

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

npm WARN eslint-plugin-cypress-dev@1.1.2 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-cypress-dev@1.1.2 requires a peer of eslint-plugin-mocha@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-cypress-dev@1.1.2 requires a peer of eslint-plugin-react@^7.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN marked-terminal@3.1.1 requires a peer of marked@^0.4.0 || ^0.5.0 but none is installed. You must install peer dependencies yourself.

+ cypress@3.1.5
added 3 packages from 13 contributors, removed 2 packages, updated 6 packages, moved 5 packages and audited 8277 packages in 37.835s
found 3 low severity vulnerabilities
```

**Comment by chrisbreiding** [comment]
Hmmm ... `eslint-plugin-cypress` is a dev dependency, so it shouldn't be installed when a user installs Cypress.

How are you running this?

**Comment by bahmutov** [comment]
It was built on CircleCI https://circleci.com/workflow-run/cb7133c2-edab-40f8-ac1e-3e03315e53c2 and ran in https://circleci.com/gh/cypress-io/cypress/47471 by installing the binary and package from the local files `CYPRESS_INSTALL_BINARY=/tmp/urls/cypress.zip npm i /tmp/urls/cypress.tgz`

The NPM `cypress.tgz` was built in https://circleci.com/gh/cypress-io/cypress/47454 and can be downloaded from https://cdn.cypress.io/beta/npm/3.1.5/circle-sign-mac-app-on-circle-ci-2958-4a809e6711c4a7d3ef56d2491ee5cc35f4d8a3e8-47454/cypress.tgz You can grab it using
```
http https://cdn.cypress.io/beta/npm/3.1.5/circle-sign-mac-app-on-circle-ci-2958-4a809e6711c4a7d3ef56d2491ee5cc35f4d8a3e8-47454/cypress.tgz > cypress.tgz
```

I have inspected the npm tgz file and it does look correct - only normal production dependencies are there. So these warnings come from `cypress-example-kitchensink` itself... never mind, kitchensink's problem.
