### ISSUE TITLE
force cy.route() to route an url only shown on the xhr browser

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#3112]
I have some xhr request not stubbed by cypress.
Maybe it's because the request came from an iframe, I don't know.
But I would like to force route these request.
Is there any way to do that ?

Thank you for your work !

**Comment by Bkucera** [comment]
@mandriao84 are you sure the request is from an XHR? Can you screenshot your devtools' network tab with the missed XHR for some context?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
