### ISSUE TITLE
require ('elasticsearch') - Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by clwilliams** [cypress-io/cypress#3113]
We would like to use elastic search in cypress and installed elasticsearch (https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/quick-start.html)

Then in the /support/index.js file:
 `const elasticsearch = require('elasticsearch')`

when I try to run the test suite, we immediately get the error detailed at the bottom of this report. Elasticsearch requires lodash also, but doesn't seem to be able to find it

Prior to requiring elasticsearch, tests that use Cypress._ are all working fine.

```
 (Run Starting)

  ┌──────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.0                                                                            │
  │ Browser:    Electron 59 (headless)                                                           │
  │ Specs:      12 found (account/home.spec.js, author.spec.js, basket.spec.js, category_listin… │
  └──────────────────────────────────────────────────────────────────────────────────────────────┘


──────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                  
  Running: account/home.spec.js...                                                      (1 of 12) 


  1) An uncaught error was detected outside of a test

  0 passing (151ms)
  1 failing

  1)  An uncaught error was detected outside of a test:
     Uncaught ReferenceError: _ is not defined

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at Object.32.../connection (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:55750:15)
      at o (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:1:265)
      at http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:1:316
      at Object.30../angular (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:55651:8)
      at o (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:1:265)
      at http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:1:316
      at Object.<anonymous> (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:55308:36)
      at Object.28../connectors (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:55595:4)
      at o (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:1:265)
      at http://localhost:3000/__cypress/tests?p=cypress/support/index.js-193:1:316

```

**Comment by jennifer-shehane** [comment]
Hey @clwilliams, are you able to reproduce then when running in `cypress open`? Could you provide the test code where the `_` is being used that is throwing as not defined?

**Comment by clwilliams** [comment]
_ is used within the elasticsearch module itself and we believe it is this that is causing the error - not any test code we've written. Simply the addition of the import statement in support/index.js immediately triggers the error when running cypress run

`import 'elasticsearch'`

When we run cypress open and we select a single script to run (that doesn't have anything calling _, and without the import of elasticsearch in support/index.js otherwise runs successfully ), we get the same error:

```
An uncaught error was detected outside of a test
Uncaught ReferenceError: _ is not defined

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
```

**Comment by jennifer-shehane** [comment]
Why are you wanting to use elasticsearch within the Cypress spec files? Could you explain your use case for wanting to import this? What is it your trying to achieve overall in your test suite?

**Comment by clwilliams** [comment]
Essentially we have shifting data and want to be able to test our website with the latest live data without having to keep stubbed data up to date. For example we want to be able to find catalogue listing pages on our website that use specific template type / layouts, and test the layout / navigation as this changes based on the template used. This data is stored in elastic search. Another example is to find an out of stock product, and test that the product page displays appropriately; or indeed set a product to out of stock and then test.

**Comment by jennifer-shehane** [comment]
Hey @clwilliams, yeah, the `cy.request()` may be a good solution for you actually

elasticsearch is not written to be run in the browser, it's meant to run as a node module. You could programmatically use elasticsearch with [`cy.task()`](https://on.cypress.io/task), then require elasticsearch in your plugins file. [Some background documentation on this](https://on.cypress.io/using-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress)

**Comment by clwilliams** [comment]
I have actually just implemented this as a task, so plugins/index.js now looks like the code below.This works much better. I'm new to cypress so discovering how to do things . . . still haven't used the elastic search module though and stuck to making a request:

```
const rp = require('request-promise')
const ora = require('ora')

// `on` is used to hook into various events Cypress emits
// `config` is the resolved Cypress config
module.exports = (on, config) => {
  on('task', {
    'getCategoryWithTemplate': (args) => {
      return getCategoryWithTemplateFromES(args)
    }
  })
}

// given a template type, depth and parent category, returns a category id
// matching those fields if it exists
function getCategoryWithTemplateFromES (args) {
  return new Promise((resolve, reject) => {
    let body = {"query": {
              "bool": {
                 "must": [
                    {
                       "term": {
                          "template": "TODO"
                       }
                    },
                    {
                       "term": {
                          "published": "true"
                       }
                    },
                    {
                       "term": {
                          "depth": "TODO"
                       }
                    },
                    {
                       "term": {
                          "parent": "TODO"
                       }
                    }
                 ],
                 "must_not": [],
                 "should": []
              }
           },
           "from": 0,
           "size": 5,
           "sort": [],
           "aggs": {}
        }
    body.query.bool.must[0].term.template=args.templateType
    body.query.bool.must[2].term.depth=args.depth
    if (args.parentCat) {
      body.query.bool.must[3].term.parent=args.parentCat
    } else {
      // remove the filter on the parent category if one wasn't passed in
      body.query.bool.must[3] = {}
    }

    var options = {
      method: 'POST',
      uri: 'http://localhost:9200/categories/_search',
      body: body,
      json: true // Automatically stringifies the body to JSON
    }

    const spinner = ora(
      'looking for ' + args.templateType + ' in the elastic search'
    ).start()

   let categoryId = ""
    rp(options)
      .then(function (response) {
        if (response.hits.total > 0) {
          categoryId = response.hits.hits[0]._source.id
          return resolve(response.hits.hits[0]._source.id)
        }
        return resolve("NOT FOUND")
      })
      .catch(function (err) {
        console.log(err);
        return reject(new Error('Problem finding a category with template type '
          + args.templateType + ' at depth ' + args.depth
          + ', with parent category : ' + args.parentCat))
      })
      .tap(() => {
        spinner.succeed('found category ' + categoryId + ' for '
          + args.templateType + ' at depth ' + args.depth
          + ', with parent category : ' + args.parentCat + ' in elastic search')
      })
      .tapCatch(err => {
        spinner.fail(err.message)
      })
  })
}
```

**Comment by Knaledge** [comment]
@clwilliams (and @jennifer-shehane ) - Something we came across while exploring a similar thought re: Elasticsearch: 

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/browser-builds.html

Not sure how this might influence things for either of you - especially @clwilliams - though I'd love to hear your thoughts.

**Comment by ManchoBlanko** [comment]
I seem to have a similar complaint but not sure if it's the same issue or not. I installed lodash with npm and required it in the server which seems to be running perfectly. I then downloaded lodash.js and embedded it in some html files in a <scropt> tag. When I try to load the web page I get an error - ReferenceError: _ is not defined. If I change the <script> tags to load the cloudflare cdn file it seems to work perfectly.

I really want to use a downloaded lodash.js file rather than having to download it every time a page loads but I just cannot get it to recognise _ - I have tried every suggestion I have come across so far (including lodash's noconflict code) without success. I am trying to convert my system from underscore to lodash having used underscore flawlessly for quite a long time. I would appreciate any help you may offer, I don't have that much hair left to tear out now!

Thank you in advance.
