### ISSUE TITLE
Rerouting with target="_parent" causes "Whoops, there is no test to run"

### ISSUE THREAD

**Issue by jadiaz** [cypress-io/cypress#3121]
### Current behavior:
test runner returns **Whoops, there is no test to run.** when clicking a link with selector: 
`'#sub-menu > ul > :nth-child(5) > a'`

### Desired behavior:

test passes after link is clicked.

### Steps to reproduce: (app code and test code)
app code
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-default" id="navTopBar" role="navigation">
        <div></div>
    </nav>
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="privacy-seal"></div>
                <nav id="sub-menu">
                    <ul>
                        <li><a href="AboutUs.htm" target="_parent">About Us</a></li>|
                        <li><a href="faq.html" target="_parent">FAQ</a></li>|
                        <li><a href="ContactUs.htm" target="_parent">Contact Us</a></li>|
                        <li><a href="TermsConditions.htm" target="_parent">Terms and Conditions</a></li>|
                        <li><a href="PrivacyPolicy.htm" target="_parent">Privacy Policy</a></li>
                    </ul>
                </nav>
            </div>
            <div class="row copyright">
                <span class="h6-xs">Copyright 2018.</span>
            </div>
            <div class="social">
                <ul class="social-links">
                    <li class="facebook"><a href="https://www.facebook.com" target="_blank">Facebook</a></li>
                    <li class="instagram"><a href="https://www.instagram.com/" target="_blank">Instagram</a></li>
                    <li class="twitter"><a href="https://twitter.com/" target="_blank">Twitter</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>

</html>
```
test code
```javascript
        it('causes cypress to stop running tests', () => {
            cy.visit('nav-test.html')
            cy.title().should('eq', 'Document')
            cy.get('#sub-menu > ul > :nth-child(5) > a').should('contain', 'Privacy Policy')
            cy.get('#sub-menu > ul > :nth-child(5) > a').click()
            cy.url().should('include', 'PrivacyPolicy')
        })
```

### Versions

Mac OS - Mojave
Cypress v.3.1.4
 Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by Bkucera** [comment]
@jadiaz, this is because you have `target="_parent"` in your `<a>` tag, which tells the parent frame of the window to navigate, the the current frame.

You should change that to `target="_self"`, which is also the default target of an `<a>` tag. see the `target` section here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

**Comment by Bkucera** [comment]
Actually

**Comment by jadiaz** [comment]
Confirmed. Setting to `target="_self"` does fix the issue.

**Comment by goofiw** [comment]
This happens when target is set to "_top" as well.

Theres a solution in #1364 

https://github.com/cypress-io/cypress/issues/1364

Is there any way to see better error handling rather than having the ui explode or the cli just hang?

**Comment by jennifer-shehane** [comment]
@Bkucera Brian mentioned that you are working on related work to this and this could be added to 3.1.6.

**Comment by andreirogobete** [comment]
I looked at the "anchor target Property" documentation (https://www.w3schools.com/jsref/prop_anchor_target.asp)

It seems like there is a possible "framename" value that you can assign to the "target" property of anchors.

Example: <a href="<your_url>" target="your-desired-iframe-name">Some Link URL</a>

Looking at this, would it be possible to set the name of the iframe which Cypress injects to run tests to something like "cypress-runner-iframe". This way, you may update your anchor "target" attribute to point to that during your test runs.

Maybe this is not ideal, but it would probably a way better solution to set the "target" to "_parent" since you may have multiple iframe layers in your application.

**Comment by jennifer-shehane** [comment]
Another clear reproducible example from https://github.com/cypress-io/cypress/issues/5938:

`index.html`

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<form method="post" target="_parent">
  <input id="text_value" />
  <button type="submit" id="submit_form">Save</button>
</form>
</body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('#text_value')
    .type('My Text')
  cy.get('#submit_form')
    .click()
})
```

**Comment by Santosh-src** [comment]
#[5964](https://github.com/cypress-io/cypress/issues/5964) This issue resolved for me after modifying Configuration to "modifyObstructiveCode: true" from initial "modifyObstructiveCode: false". in Cypress.json

**Comment by testn** [comment]
so how do we want to fix this? modifyObstructiveCode does not seem to work for me.

**Comment by rodybothebynder** [comment]
Hi Guys, 

For me this issue still remains. I tried everything above. 

Here you find a snippet of where I try to change the _top to _self
<img width="457" alt="Screen Shot 2020-05-07 at 2 58 16 PM" src="https://user-images.githubusercontent.com/60645867/81297653-dbb60780-9073-11ea-81a1-ce5298b25d4d.png">

Tried to invoke with both options (see below) that Jennifer mentioned on a Stackoverflow thread. It gives an error after: dialog-confirm 
<img width="494" alt="Screen Shot 2020-05-07 at 3 03 25 PM" src="https://user-images.githubusercontent.com/60645867/81297793-1881fe80-9074-11ea-8122-cdc20d1d729a.png"> 

What I am doing missing or doing wrong?

**Comment by BiswajitNanda** [comment]
In my application, the user accepts terms and conditions( a typical terms and conditions document where the the user scrolls down to the bottom and it asks the user to accept) and when the user clicks on the submit button, it throws "whoops no test found".

There are no iframes, the submit section is as follows. 

< form method="post" action id="terms-form" >
   < input type="submit" data-href="terms" name="accept" value="I accept" class="connect" > ==$0
< /form >

Any idea what is the cause of this error and how to address this.
