### ISSUE TITLE
Can't set faker's locale in support/index.js

### ISSUE THREAD

**Issue by x-yuri** [cypress-io/cypress#3123]
### Current behavior:

`faker` is executed once for `support/index.js`, and once again for a spec. As a result, changing locale in `support/index.js` has no effect, since after that `faker` is executed again for a spec file (module cache cleaned?).

E.g. with ordinary modules:

`m1.js`:

```js
console.log('m1.js');
var faker = require('faker');
faker.locale = 'xx';
var m2 = require('./m2');
```

`m2.js`:

```js
console.log('m2.js');
var faker = require('faker');
console.log(faker.locale);   // xx
```

### Desired behavior:

For changes in `support/index.js` to not be reset.

### Steps to reproduce: (app code and test code)

`support/index.js`:

```js
import faker from 'faker';
faker.locale = 'xx';
```

spec:

```js
import faker from 'faker';
console.log(faker.locale);
```

### Versions

`cypress-3.1.4`

**Comment by jennifer-shehane** [comment]
Hey @x-yuri, I am able to recreate this behavior.

**Comment by jennifer-shehane** [comment]
This is because you're creating 2 instances of faker across 2 separate files. You'll need to import that instance created from the support file into the test file. 

`support/index.js`

```js
import faker from 'faker';

faker.locale = 'xx';

export {
  faker
}
```

`spec.js`

```js
import { faker } from '../support/index';

console.log(faker.locale);
```

**Comment by x-yuri** [comment]
> This is because you're creating 2 instances of faker across 2 separate files.

Not me, `cypress` ;) For one reason or another specs and `support/index.js` are executed in separate "environments" ([browser packs][1]). Consider the following setup:

`cypress/support/index.js`:

```js
console.log('-- support/index.js');
const faker = require('faker');
faker.locale = 'de';
require('./1.js');
```

`cypress/support/1.js`:

```js
console.log('-- support/1.js');
const faker = require('faker');
console.log(faker.locale); // still de
```

`cypress/integration/1.spec.js`:

```js
console.log('-- 1.spec.js');
const faker = require('faker');
console.log(faker.locale); // en
```

The output:

```
-- support/index.js
-- support/1.js
de
-- 1.spec.js
en
```

By following your advice I basically breach that separation (`support/index.js` is executed twice):

`cypress/support/index.js`:

```js
console.log('-- support/index.js');
const faker = require('faker');
faker.locale = 'de';
export {faker};
```

`cypress/integration/1.spec.js`:

```js
console.log('-- 1.spec.js');
import { faker } from '../support/index';
console.log(faker.locale); // de
```

The output:

```
-- support/index.js
-- support/index.js
-- 1.spec.js
de
```

So for now I'd rather change the locale into every spec. Or put it into a separate file (some sort of config).

[1]: https://www.npmjs.com/package/browser-pack

**Comment by chrisbreiding** [comment]
You could utilize a global to be able to set the locale once in the support file. I haven't tested this out, but it should work.

`cypress/support/index.js`

```javascript
const faker = require('faker');
faker.locale = 'de';
window.faker = faker
```

`cypress/integration/1.spec.js`

```javascript
const faker = window.faker
console.log(faker.locale); // de
```

> ... specs and support/index.js are executed in separate "environments" ... But the behavior is unexpected (unless you know how it works under the hood).

I'd have to agree. I think other users have been tripped up by this as well. Ideally, we would only output one bundled file to the browser that would auto-import the support file, so it's part of the same 'environment'. We'd have to research the consequences of that. It might be tricky since the implementation would be preprocessor-dependent and users control the preprocessor they use.

**Comment by x-yuri** [comment]
> You could utilize a global to be able to set the locale once in the support file.

I probably could, but that sounds like a hack/workaround/kludge. I'd still probably prefer to put changing locale into e.g. `support/init.js`, and import it in every spec.

> Ideally, we would only output one bundled file to the browser that would auto-import the support file, so it's part of the same 'environment'.

I guess with specs in separate bundles, browser can cache them separately. And a change in one spec wouldn't affect the others. Not sure if that makes a difference.

As for `support/index.js` its main purpose seems to be adding commands. So putting it into spec bundles is probably not good. At least not necessary (if `Cypress.Commands.add` overwrites the command if it exists).

It might make sense to keep thing as is, and update the documentation (specify more clearly what the file is for), e.g.:

https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Support-file

But I'm not sure, just thinking aloud.
