### ISSUE TITLE
.cache/Cypress/3.1.4/Cypress/Cypress: cannot create ��Z@0f�@8: Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by rickyrsyah** [cypress-io/cypress#3125]
### Current behavior:
```
> cypress open

It looks like this is your first time using Cypress: 3.1.4

 ✖  Verifying Cypress can run /home/rickyrsyah/.cache/Cypress/3.1.4/Cypress
   → Cypress Version: 3.1.4
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

/home/rickyrsyah/.cache/Cypress/3.1.4/Cypress/Cypress: 1: /home/rickyrsyah/.cache/Cypress/3.1.4/Cypress/Cypress: cannot create ��Z@0f�@8: Invalid or incomplete multibyte or wide character
/home/rickyrsyah/.cache/Cypress/3.1.4/Cypress/Cypress: 1: /home/rickyrsyah/.cache/Cypress/3.1.4/Cypress/Cypress: ELF: not found
/home/rickyrsyah/.cache/Cypress/3.1.4/Cypress/Cypress: 3: /home/rickyrsyah/.cache/Cypress/3.1.4/Cypress/Cypress: Syntax error: Unterminated quoted string
----------

Platform: linux (Ubuntu Linux - 16.04)
Cypress Version: 3.1.4
```

### Desired behavior:

I've install Cypress as `devDependencies` from `package.json` and there is not problem.
Then i want to open cypress with script `cypress open` on `package.json`, but unfortunately i got an error.

I had a previous Windows os at another boot, so I thought about trying it there. I did not get any errors and works

### Versions

from `uname -a` i get this message:
`Linux Mate 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:30:54 UTC 2018 i686 athlon i686 GNU/Linux`

**Comment by Bkucera** [comment]
@rickyrsyah we don't currently support 32-bit linux, and the output from `uname -a` indicates you're on a 32-bit machine.

Feel free to respond to this issue with any further comments or requests, but I'm going to close this for now.
