### ISSUE TITLE
"visible" element hidden under iframe in snapshot

### ISSUE THREAD

**Issue by techieshark** [cypress-io/cypress#3126]
### Current behavior:

Despite matching on `cy.get(...).should.be.visible()`, the snapshot does not show the element visible - it is covered by an iframe / preview. Photos below.

![image](https://user-images.githubusercontent.com/1072292/51110384-a2d59c00-184c-11e9-87ac-19e0203bb87b.png)

Note you can see the outline / shaded area of the thing we want to see, but the details are obscured by the larger iframe (which was a Stripe Checkout widget - something I expected to have been gone by the time my spinner shows up).
![image](https://user-images.githubusercontent.com/1072292/51110493-fa740780-184c-11e9-9e33-6ddb045dd4dd.png)

relevant code:
![image](https://user-images.githubusercontent.com/1072292/51110557-3a3aef00-184d-11e9-9ade-8413f53d1c3a.png)

![image](https://user-images.githubusercontent.com/1072292/51110566-432bc080-184d-11e9-844d-c77e8be1e55a.png)

### Desired behavior:

I would think `should.be.visible()` will result in a screen snap showing what I'm looking for (a progress spinner in my case).

### Versions

cypress 3.1.4 on latest Chrome / mac.

**Comment by jennifer-shehane** [comment]
Hey @techieshark, is the `[data-cy=spinner-submitting]` element within the iframe itself? I want to make sure I understand. Or is the iframe on a z-plane above the `[data-cy=spinner-submitting]`?

**Comment by techieshark** [comment]
@jennifer-shehane no the spinner is not in the iframe; the iframe appears to be obscuring it.

**Comment by techieshark** [comment]
@jennifer-shehane thanks for the followup. 

The spinner is not hidden behind the iframe during the test run (i.e. when I watch it running in real time / live, I am able to personally observe the spinner). 

When I use `cy.get(...).screenshot()`, the screenshot generated *does* show the spinner.  And when I run from command line and review the video after running the test, I *do* see the spinner. 

So as it sounds like you suspect, it may be solely related to how the snapshots preview upon review is generated.

**Comment by jennifer-shehane** [comment]
Hey @techieshark, can you provide the normal css styles applied to the iframe and also to the spinner element? I've been unable to replicate this exactly just playing with some standard css styles.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by techieshark** [comment]
Just stumbled upon this GH issue again while searching something else.

To close the loop, in case others run into this - the trick to fix it was just to add a brief delay after the `click` that causes the Checkout popup to appear:

```
cy.get('[data-cy="some-button"]').click().wait(100);
cy.get('iframe.stripe_checkout_app')
    .then(($element) => {
   ...
```
