### ISSUE TITLE
Is there a way to highlight/border a specific element when taking a cypress screenshot?

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#3132]
Hey there, we're using cypress's great screenshot functionality to generate documentation for our apps. It would be nice to be able to highlight (or put a red border around or have an arrow pointing to) a certain element while taking a full page screenshot.  It would be nice if the method would also work when taking a cropped screenshot or a screenshot of a larger containing element.

For example, in the following screenshot, it would be nice to be able to have say the "Submit" button get a red outline: 
![image](https://user-images.githubusercontent.com/2730609/51142257-46e52600-1800-11e9-9d07-4a3854fdcbf2.png)

Does anyone know of a good way of doing this? Is this possible right now or does cypress need to add some functionality to make this happen. Thanks!

**Comment by bahmutov** [comment]
@tnrich you can do it yourself. For example we highlight elements the tests have interacted with in https://www.cypress.io/blog/2018/12/20/element-coverage/ Of course in your case this is much simpler

```js
cy.get('button#my-button')
  .then($button => {
    $button.css('border', '1px solid magenta')
  })
cy.screenshot('press this button')
```

**Comment by tnrich** [comment]
Thanks very much @bahmutov !!
