### ISSUE TITLE
Publish a patch

### ISSUE THREAD

**Issue by VincentLanglet** [cypress-io/cypress#3133]
Since this PR is merged : https://github.com/cypress-io/cypress/pull/3031

Could you release a patch ?
It would be really helpful for typescript users

Thanks

**Comment by Kombustor** [comment]
Agree on this. I was suggested to use `tsc` to transpile my code (here #3136), but this doesn't work in a setup that relies on webpack & babel.

Any other way to patch/use this version? @bahmutov

**Comment by bahmutov** [comment]
soon, soon, I am pushing on this internally to release the patch 3.1.5

**Comment by VincentLanglet** [comment]
@Kombustor I'm using patch-package (https://www.npmjs.com/package/patch-package) while waiting for the release

**Comment by bahmutov** [comment]
@VincentLanglet that's a great suggestion, I was trying to remember the name of the `patch-package`

**Comment by Kombustor** [comment]
@bahmutov Is there an ETA?
@VincentLanglet How exactly do I use the library? Do you have a .patch-file ready for this issue?

**Comment by jennifer-shehane** [comment]
Hi, I know everyone is anxious to have Cypress releases go faster (even more so from our team!), but 
we need to reserve issues for potential bugs or feature requests - not timeline tracking of releases. 

I will be closing this issue. We'll get 3.1.5 out as soon as we can.

@VincentLanglet Thanks for the `patch-package` suggestion, this looks very helpful.
