### ISSUE TITLE
Cypress issues a warning if beforeEach function is async

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3139]
### Current behavior:

```js
class BackEndState {
  static setup() {
     // set the back-end into a specific state, e.g. with HTTP POST or websocket
     // returns a Promise
     // this code is framework-agnostic and doesn't necessarily even need to be invoked via a cypress test
  }
}
```

This gives a warning:
```js
context('foo', function () {
  beforeEach(async done => {
    await BackEndState.setup();
    cy.visit('/').then(function() { done() });
  });
  it('test', function() { });
});
```

This does not:
```js
context('foo', function () {
  beforeEach(done => {
    BackEndState.setup().then(() => {
      cy.visit('/').then(function() { done() });
    });
  });
  it('test', function() { });
});
```

The warning is:

```
cypress_runner.js:62992 Cypress Warning: Cypress detected that you returned a promise in a test, but also invoked one or more cy commands inside of that promise.

The test title was:

  > foo.test

While this works in practice, it's often indicative of an anti-pattern. You almost never need to return both a promise and also invoke cy commands.

Cy commands themselves are already promise like, and you can likely avoid the use of the separate Promise.
```

### Desired behavior:

I think the first example is more readable, and using async/await in this way is *not* an anti-pattern, despite what the warning text says.
The promise is implicitly created due to the function being marked as `async`.

### Steps to reproduce: (app code and test code)

See above.

### Versions

Cypress 3.1.4

**Comment by fr0** [comment]
Based on what I saw in #3172, I am now wondering if both cases should generate a warning.

**Comment by jennifer-shehane** [comment]
@fr0 I'm sorry if I've misread, but I'm unsure exactly what behavior you want Cypress to do in this situation. Could you outline what you would like to happen in Cypress when running this code?

>class BackEndState {
  static setup() {
     // set the back-end into a specific state, e.g. with HTTP POST or websocket
     // returns a Promise
     // this code is framework-agnostic and doesn't necessarily even need to be invoked via a cypress test
  }
}

**Comment by fr0** [comment]
After discovering the behavior in #3172, I think the warning is appropriate, and in fact should also be issued in the case where the `done()` function is used in `beforeEach`, since that seems to break things with no obvious indication to the user that that is what's causing it.

**Comment by adomyaty55foundry** [comment]
I agree of this and concur receiving this error on a VERY reasable custom graphQL test framework. async works for us and having all these warnings come up is busy warnings that does not makes sense for me and I'm sure many others.

Propose we don't have that warning for our case
