### ISSUE TITLE
Command "contains" does not support timeout

### ISSUE THREAD

**Issue by Betree** [cypress-io/cypress#3142]
### Current behavior:

The docs state that `contains` accept an `options` object with a `timeout` param: https://docs.cypress.io/api/commands/contains.html#Arguments

However this currently doesn't work:

```es6
cy.contains('#content', '$1,337.00 per year', { timeout: 30000 })
```

From reading at [the code](https://github.com/cypress-io/cypress/blob/55b352a11d0a664517ae054c67432d98abc2389e/packages/driver/src/cy/commands/querying.coffee#L260) it seems that it hasn't been implemented yet.

### Desired behavior:

The following calls should produce the desired `timeout` in the same way it works for `get`:

```es6
cy.contains('#content', '$1,337.00 per year', { timeout: 30000 })
cy.contains('$1,337.00 per year', { timeout: 30000 })
```

### Steps to reproduce: (app code and test code)

Create a new test with the following code. It should fail instantly (without waiting for default timeout).

```es6
cy.contains('A string that does not exist', { timeout: 1 })
```

### Versions

Cypress `3.1.3`

**Comment by Saibamen** [comment]
Try with 3.1.4

It is fixed for me:
![image](https://user-images.githubusercontent.com/905878/51251552-e25dce80-1999-11e9-8250-f3990ba504eb.png)
![image](https://user-images.githubusercontent.com/905878/51251597-fc97ac80-1999-11e9-8bca-5f575011f058.png)

**Comment by bevacqua** [comment]
It seems Cypress isn't picking up all the overloads for this method, I run into a similar issue when linting TS:

```
» yarn lint-cypress
yarn run v1.16.0
$ tsc --project cypress/tsconfig.json
cypress/support/commands.ts:71:56 - error TS2345: Argument of type '{ timeout: number; }' is not assignable to parameter of type 'string | number | RegExp'.
  Object literal may only specify known properties, and 'timeout' does not exist in type 'RegExp'.

71     cy.contains(`Your deployment has been created.`, { timeout: 5 * 60 * 1000 })
                                                          ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by bahmutov** [comment]
@NicholasBoll check what version you are using and upgrade to 3.4.1 where we have this issue #4727 fixed, see https://github.com/cypress-io/cypress/releases/tag/v3.4.1

**Comment by bevacqua** [comment]
We're on `^3.3.1`, I'll look into that, thanks!
