### ISSUE TITLE
Searching for specs is a dead end when there are no results

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#3146]
### Current behavior:

After searching for spec files and receiving "zero results" we're given a very confusing error message. 

![screen shot 2019-01-16 at 12 09 08 pm](https://user-images.githubusercontent.com/1268976/51266563-9c007380-1989-11e9-8b12-ecbde7863add.png)

1. The error message refers to a "filter" yet to get here you needed to "Search" via the magnifier
2. The word we searched is not visually separated enough from the error itself, so it appears as if it is part of the error message
3. The user is left feeling at a "dead end" and confused because to remedy this error they need to perform actions that aren't part of the error message itself.

![screen shot 2019-01-16 at 12 11 09 pm](https://user-images.githubusercontent.com/1268976/51266577-a1f65480-1989-11e9-8bef-b08665ff6d14.png)

### Desired behavior:

1. Synchronize "filter" and "search" to be consistent
2. Visually separate the error message from the word you searched for
3. Provide CTA buttons directly on the error message so the user can remedy the problem without performing a separate action

### Versions

3.1.4

**Comment by flotwig** [comment]
![image](https://user-images.githubusercontent.com/1151760/51269732-3adc9e00-1991-11e9-9cf8-44d1e2eb7075.png)

Clicking "Clear search" clears the query and focuses the search text input field.
