### ISSUE TITLE
CircleCI + Ubuntu 14.04 failing

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#315]
Referenced from https://github.com/cypress-io/cypress-cli/issues/19

**Cause**
There were dependencies that were installed in Circle's base image for `Ubuntu 12.04` that are no longer part of the default installation on `Ubuntu 14.04`. These missing dependencies cause the long standing [issue with Cypress that it just "hangs"](317) instead of proceeding after installation.

**Workaround**
For the moment just change the base image used in the Build Environment settings for you project.

![screen shot 2016-11-30 at 4 01 52 pm](https://cloud.githubusercontent.com/assets/1268976/20771195/6e93e9f4-b716-11e6-809b-f4fd8f6fa439.png)

**Comment by jennifer-shehane** [comment]
Closing as resolved, especially seeing https://github.com/cypress-io/cypress/issues/317 is closed.
