### ISSUE TITLE
it.only yields type error in TypeScript

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3152]
### Current behavior:

```
/// <reference types="Cypress" />

context('foo', function() {
  it.only('bar', function() {

  });
});
```

Error:

```
TS2339: Property 'only' does not exist on type '{ (expectation: string, assertion?: (done: DoneFn) => void, timeout?: number): void; (expectation: string, assertion?: (done: DoneFn) => Promise<void>, timeout?: number): void; }'.
```

As long as you use `transpileOnly`, your test will still run. However, you'll still get the error in your editor (e.g. WebStorm, VSCode).

### Desired behavior:

No error.

### Versions

3.1.4

**Comment by bahmutov** [comment]
Do you have just Cypress there or any other testing tools, like Jest? Can you paste your dependencies 
```
npm ls --depth=0
```

**Comment by fr0** [comment]
├── @angular-devkit/build-angular@0.12.1
├── @angular/animations@7.2.0
├── @angular/cli@7.2.1
├── @angular/common@7.2.0
├── @angular/compiler@7.2.0
├── @angular/compiler-cli@7.2.0
├── @angular/core@7.2.0
├── @angular/elements@7.2.0
├── @angular/forms@7.2.0
├── @angular/http@7.2.0
├── @angular/language-service@7.2.0
├── @angular/platform-browser@7.2.0
├── @angular/platform-browser-dynamic@7.2.0
├── @angular/router@7.2.0
├── @cypress/webpack-preprocessor@4.0.3
├── @types/d3@5.5.0
├── @types/dagre@0.7.40
├── @types/dagre-d3@0.4.38
├── @types/esprima@4.0.2
├── @types/jasmine@3.3.5
├── @types/jasminewd2@2.0.6
├── @types/lodash@4.14.119
├── @types/node@10.12.18
├── @types/showdown@1.9.1
├── @webcomponents/custom-elements@1.2.1
├── atlas-ui-components@1.1.20
├── brace@0.11.1
├── codelyzer@4.5.0
├── commander@2.19.0
├── core-js@2.6.2
├── css-element-queries@1.1.1
├── css.escape@1.5.1
├── cypress@3.1.4
├── d3@5.7.0
├── dagre@0.8.4
├── dagre-d3@0.6.3
├── date-fns@1.30.1
├── esprima@4.0.1
├── fast-json-stable-stringify@2.0.0
├── fs-extra@7.0.1
├── isomorphic-ws@4.0.1
├── jasmine@3.3.1
├── jasmine-core@3.3.0
├── jasmine-reporters@2.3.2
├── jasmine-spec-reporter@4.2.1
├── js-beautify@1.8.9
├── json5@2.1.0
├── jspath@0.4.0
├── karma@3.1.4
├── karma-chrome-launcher@2.2.0
├── karma-cli@2.0.0
├── karma-jasmine@2.0.1
├── karma-jasmine-html-reporter@1.4.0
├── karma-junit-reporter@1.2.0
├── lodash@4.17.11
├── ng-packagr@4.5.0
├── node-pre-gyp@0.10.3 extraneous
├── prevent-publish@0.0.4
├── protractor@5.4.2
├── rxjs@6.3.3
├── showdown@1.9.0
├── spawn-npm-install@1.2.0
├── ts-loader@5.3.3
├── ts-node@7.0.1
├── tsickle@0.34.0
├── tslib@1.9.3
├── tslint@5.12.1
├── typedoc@0.14.1
├── typescript@3.2.2
├── webpack@4.28.4
├── webpack-bundle-analyzer@3.0.3
├── ws@6.1.2
├── xml2js@0.4.19
└── zone.js@0.8.27

**Comment by fr0** [comment]
We use Jasmine for our Karma unit tests -- maybe that's related?

**Comment by bahmutov** [comment]
ok, it probably is coming from Jamine and `@types/jasmine` packages.

**Comment by fr0** [comment]
I solved the problem by installing `@types/mocha` and then adding a `cypress/tsconfig.json` file:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "types": ["mocha"]
  }
}
```

My unit test `tsconfig.json` then uses `"types": ["jasmine"]`.

**Comment by bahmutov** [comment]
great @fr0 but I would not install additional `@types/mocha` since Cypress already includes it https://github.com/cypress-io/cypress/blob/develop/cli/package.json#L50
