### ISSUE TITLE
Stop calling `onLoad` callback when a hash changes

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#3155]
In the browser, a `hashchange` event does not also fire the `onload` event. In Cypress, if you visit a page and then visit a hash on that page, the `onload` callback is called. This should be updated so that the `onLoad` callback is not called when visiting a hash on the same page.

To reproduce:
```js
 cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html#Our-mission', {
   onLoad: onload,
   onBeforeLoad: onbeforeload
 })

 cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html#Cypress-ecosystem', {
   onLoad: onload,
   onBeforeLoad: onbeforeload
 })
```

Currently, `onBeforeLoad` then `onLoad` is called from the first visit then `onLoad` is called from the second visit.

After fixing, neither `onLoad` nor `onBeforeLoad` should be called.

**Comment by jime2003** [comment]
Is there any update on this issue?
