### ISSUE TITLE
In environment configuration file, add the custom variables in deep structures 

### ISSUE THREAD

**Issue by chuchu1313** [cypress-io/cypress#3157]
### Current behavior:

To define an environment variable, in the config file (e.g. cypress/config/development.json) I can add variables on the first level of JSON format.
The second level needs to be named **env**, like below

```json
{
  "execTimeout": "120000",
  "env": {
       "CC_COOKIES": "aaa"
  }
}
```

### Desired behavior:
Assumed I have two environments (`development` & `qa`), and have two config files to define the different environment variables, but still needs to test in three different countries in each environment, and the variable is different depending on the countries. 
The desired config structure may be like below
e.g: `development.json`

```json
    {
      "execTimeout": "120000",
      "id_env": {
          "CC_COOKIES": "aaaa"
           ...
      }, 
      "tw_env":{
          "CC_COOKIES": "bbbb"
           ...
      }, 
      "hk_env":{
          "CC_COOKIES": "cccc"
           ...
      }
    }
```

e.g: `qa.json`

```json
    {
      "execTimeout": "120000",
      "id_env": {
          "CC_COOKIES": "dddd"
         ...
      }, 
      "tw_env":{
          "CC_COOKIES": "eeee"
           ...
      }, 
      "hk_env":{
          "CC_COOKIES": "ffff"
           ...
      }
    }
```

So I can get the variables based on the environment and countries, it could be more flexibility for configs.
Current behavior needs to create 6 different files
(`development_id.json`, `development_tw.json`, `development_h.jsonk`, `qa_id.json`, `qa_tw.json`, `qa_hk.json`)

**Comment by flotwig** [comment]
You can do this by modifying your plugins file (by default, in `cypress/plugins/index.js`). In there, you can dynamically modify the configuration at run-time by using your own logic and returning a modified `config` object. Please see the documentation for details:

https://docs.cypress.io/api/plugins/configuration-api.html#Usage

**Comment by chuchu1313** [comment]
Hello @flotwig, thanks for your reply.
I'm dynamic get my config just like below example

    // promisified fs module
    const fs = require('fs-extra')
    const path = require('path')

    function getConfigurationByFile (file) {
        const pathToConfigFile = path.resolve('..', 'config', `${file}.json`)

      return fs.readJson(pathToConfigFile)
    }

    // plugins file
    module.exports = (on, config) => {
      // accept a configFile value or use development by default
      const file = config.env.configFile || 'beta'
    
      return getConfigurationByFile(file)
    }

And my `beta.config` is like below:

    {
      "execTimeout": "120000",
      "id_env": {
          "CC_COOKIES": "aaaa"
           ...
      }, 
      "tw_env":{
          "CC_COOKIES": "bbbb"
           ...
      }, 
      "hk_env":{
          "CC_COOKIES": "cccc"
           ...
      } 
    } 

In my case, I put `id_env`, `tw_env` and `hk_env` in `beta.config` is because they are in the same environment(beta).  But it is not working in this example. Only when I modify to `env` it will work.

    {
      "execTimeout": "120000",
      "env": {
           ...
      },
    } 

But which can not be seperated define the env variables by different mateix (here is country).
Is there any way that I can use to define different variables by using JSON structures?

**Comment by chuchu1313** [comment]
@flotwig @jennifer-shehane Thanks for your reply.
I use Module API, and looks like below, which works and can do what I want.


    // cypress_run.js
    
    const env = process.argv[2]
    const country = process.argv[3]
 
    fs.readFile('cypress/config/' + env + '.json', 'utf8', function (err, data) {

      const configs = JSON.parse(data)

        cypress.run({
            spec: runFiles,
            env: configs[country]
        })
    })
