### ISSUE TITLE
Elements deeply nested in elements with overflow: hidden are being recognized as not visible even though they are

### ISSUE THREAD

**Issue by alexmonteirocastro** [cypress-io/cypress#3158]
### Current behavior:

I have an application with several divs nested in each other

`.flow-wrap -> right-side -> .inside -> .content-block` (this element contains the buttons and inputs I want to interact with)

`.flow-wrap` has css property `overflow: hidden`

Elements nested in the `.inside` div are being recognized as hidden by cypress. 

Testing a visible input and a visible button inside the `.content-wrap` (expecting the element to be visible) fails and in the error message cypress says that the reason is that the parent element `div.flow-wrap` has css property `overflow:hidden`

### Desired behavior:

It should recognize the visible elements nested inside the `.inside div` has visible. 
I understand that this issue was resolved in the past (https://github.com/cypress-io/cypress/issues/631) but, apparently, after a few more levels of testing the issue reappears.

### Steps to reproduce: (app code and test code)

Try to query a visible element nested 3 levels below an element with `overflow: hidden`. Cypress will recognize it as not visible. 

### Versions

Cypress 3.1.3

**Comment by Bkucera** [comment]
@alexmonteirocastro could you put your reproducible in a jsfiddle or codepin? I want to be sure we can reproduce this error. Thanks!

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
