### ISSUE TITLE
Iterating over list and on click it route to new url which cause  element to detach and for next iteration it give Error on click

### ISSUE THREAD

**Issue by cutkarsh97** [cypress-io/cypress#3165]
### Current behavior:

```js
cy.get('[data-test-id=project-button]').each(($el, index, $list) => {
    cy.wrap($el).click({force: true});
    cy.url().should("include", "projectName")
    cy.go('back')
    cy.get('[data-test-id=project-page-button]');
    cy.wait(1000);
})
```

`cy.get(...)` return list of 3 items:
 
```
[
  div.css-v1ast0-wrapperClass-modifierClass, 
  div.css-gz0aj8-wrapperClass-modifierClass, 
  div.css-gz0aj8-wrapperClass-modifierClass
]
```

Now for each of item i want tot initiate click which route to new url. so `cy.go('back')` route to previous page and trying to get the same parent by `cy.get(..)`.

It gives error: 

<img width="407" alt="screenshot 2019-01-18 at 1 58 01 pm" src="https://user-images.githubusercontent.com/46315584/51374467-24694a80-1b29-11e9-8258-4a7d1dd634f5.png">

### Desired behavior:

It should iterate over items

### Versions 

chrome: 71
cypress: 1.3.4

**Comment by jennifer-shehane** [comment]
Yes, unfortunately this will not work. Since the entire DOM has been rerendered on the `cy.go('back')`, we no longer have a reference to the original DOM elements yielded from `cy.get(...)`. You will have to rewrite your test code to something like this:

If you're unsure about how many items will be in the list, you could do something like this:

```js
  cy.get('[data-test-id=project-button]').its('length').then((len) => {
    cy.wrap(Cypress._.range(len)).each((item, i, list) => {
      cy.get('[data-test-id=project-button]').eq(i).click({ force: true })
      cy.url().should('include', 'projectName')
      cy.go('back')
      cy.get('[data-test-id=project-page-button]')
      cy.wait(1000)
    })
  })
```
