### ISSUE TITLE
Backend integrations (aka drivers)

### ISSUE THREAD

**Issue by miiimooo** [cypress-io/cypress#3167]
I'm currently evaluation cypress. At the moment I run behat together with drone CI. 

I've set it up - also with the CI - and it's running a Drupal API with a headless react frontend fine. It's great work and very snappy.

One thing I'm missing though is the concept of drivers that is found in behat / drupal-extension / mink.

What it allows me to do is select a driver (or multiple drivers) and call for instance API functionality directly. To give an example: with the Drupal API driver I can create node and then run tests that use that node (in the browser or otherwise). A side effect of this is that the driver takes care of cleaning up after the test has run. So a test that for instance creates a page node can always expect to find it at it's url alias /content/my-title. This is because the driver removes any content it created during a test scenario.
Are there plans (or am I missing something) for a similar concept in cypress? I can see there is support for fixtures. Maybe that I need to investigate that more. I don't think that just having a custom command is a solution, or at least I can not see how to take care of the "cleanup" with that.

Thanks!

**Comment by jennifer-shehane** [comment]
You may find some usefulness with our [`cy.task()`](https://on.cypress.io/task) and/or [`cy.exec()`](https://on.cypress.io/exec) commands or our [Plugins API](https://on.cypress.io/writing-a-plugin). Let us know.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
