### ISSUE TITLE
Cannot clear timer: timer created with setTimeout() but cleared with clearInterval()

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#3170]
Hey there, I'm getting a strange clock-based error when trying to run one of my tests: 

```
Cannot clear timer: timer created with setTimeout() but cleared with clearInterval()
```

![image](https://user-images.githubusercontent.com/2730609/51409332-57561300-1b16-11e9-9262-78fe2082123d.png)

Here is the code that's throwing the error: 

![image](https://user-images.githubusercontent.com/2730609/51409387-8b313880-1b16-11e9-88f5-1a5639e336f8.png)

And here is the code to reproduce it: 

```js
it("can drag the alignment", function() {
    cy.visit("http://teselagen.github.io/openVectorEditor/#/Alignment");

    cy.tgToggle("isFullyZoomedOut")
    cy.contains("text","355").first().then((el) => {
    cy.contains("text","710").first().then((el2) => {
      
      cy.dragBetween(el,el2);
    })
    })
  });
```

```js 
//in cypress/support/commands.js

Cypress.Commands.add("tgToggle", (type, onOrOff = true) => {
  /* eslint-disable no-unexpected-multiline*/

  return cy
    .get(`[data-test="${type}"]`)
    [onOrOff ? "check" : "uncheck"]({ force: true });
  /* eslint-enable no-unexpected-multiline*/
});

Cypress.Commands.add("dragBetween", (dragSelector, dropSelector) => {
  const getOrWrap = isString(dragSelector) ? cy.get : cy.wrap

  cy.clock();
  getOrWrap(dragSelector).then(el => {
    let dragSelectDomEl = el.get(0);
    getOrWrap(dropSelector).then(el2 => {
      let dropSelectDomEl = el2.get(0);
      const [x, y] = getCenter(dragSelectDomEl);
      const [xCenterDrop, yCenterDrop] = getCenter(dropSelectDomEl);
      getOrWrap(dragSelector)
        .trigger("mousedown", {
          button: 0,
          clientX: x,
          clientY: y
        })
        .tick(1000);
      // drag events test for button: 0 and also use the clientX and clientY values - the clientX and clientY values will be specific to your system
      getOrWrap(dragSelector)
        .trigger("mousemove", {
          button: 0,
          clientX: x + 10,
          clientY: y + 10
        }) // We perform a small move event of > 5 pixels this means we don't get dismissed by the sloppy click detection
        .tick(5000); // react-beautiful-dnd has a minimum 150ms timeout before starting a drag operation, so wait at least this long.

      cy.get("html") // now we perform drags on the whole screen, not just the draggable
        .trigger("mousemove", {
          button: 0,
          clientX: xCenterDrop,
          clientY: yCenterDrop
        })
        .tick(5000);
      cy.get("html").trigger("mouseup", {
        // Causes the drop to be run
        button: 0,
        clientX: xCenterDrop,
        clientY: yCenterDrop
      });
      // Can now test the application's post DROP state
    });
  });
});


```

It is maybe related to this issue, but I'm not sure what is really going on under the hood:
https://github.com/sinonjs/sinon/issues/872

**Comment by tnrich** [comment]
Hmm a strange one indeed. It appears that a piece of setTimeout code in my own codebase was causing the error. You can see below that I'm calling clearInterval on a setTimeout that I made earlier:

![image](https://user-images.githubusercontent.com/2730609/51409952-165efe00-1b18-11e9-80c6-aed57526a8ff.png)

Fortunately I don't need this piece of code anymore so I can just drop it. It seems like this shouldn't be thrown as an error at all though because in normal, non-hijacked js no error is thrown for calling clearInterval on a timeoutId.

**Comment by BiosBoy** [comment]
Yeah! 

I've spotted the same error inside my own codebase. Seems like Cypress shall pass it on or at least provide some more user-friendly stack trace.

Thanks.

**Comment by tnrich** [comment]
Still seeing this error crop up occasionally using Cypress v8.5.0. Not sure why that would be as the error I linked in the sinon repo https://github.com/sinonjs/sinon/issues/872 has been updated already. Perhaps cypress still hadn't upgraded to use that version of sinon in v8.5.0 ?

**Comment by tnrich** [comment]
Just checked and it looks like cypress v8.5.0 has a version of @sinon/fake-timers that should have the fix. So something is wonky .. I'm just going to sprinkle some `!window.Cypress &&` on the `clearIntervals()` within my code..
