### ISSUE TITLE
cy.wrap times out when wrapping a completed promise that was already wrapped

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3173]
### Current behavior:

Wrapping a completed promise that has already been wrapped should just pass the value along, but instead it seems to time out. e.g.

```js
beforeEach(() => {
  return cy.wrap(cy.wrap(new Promise(accept => accept())));
});
```

### Desired behavior:

In general, I think `cy.wrap` should be able to be called with a promise that was already wrapped. There is no good reason to do this; however, if the caller and callee are in different places in the code and they each call `cy.wrap`, I think it should still work.

### Versions

3.1.4

**Comment by jennifer-shehane** [comment]
4.5.0:

<img width="583" alt="Screen Shot 2020-05-18 at 12 09 20 PM" src="https://user-images.githubusercontent.com/1271364/82177744-762e0a80-9900-11ea-8945-67f9ce461381.png">
