### ISSUE TITLE
Commercial Support?

### ISSUE THREAD

**Issue by rogeralsing** [cypress-io/cypress#3174]
This is neither a bug or feature request, but rather a question about commercial support.
Our internal apps are tested via Cypress, which initially worked very well.
Now we are seeing tests fail 2 out of 3 times, at random. and we have no real way of going forward with this..

So, is there any official commercial support, anyone on the core team doing consulting on the topic?

**Comment by Saibamen** [comment]
Please copy and paste:

- Cypress version
- error message
- test code

**Comment by Bkucera** [comment]
@rogeralsing Hi, please see this section of the cypress.io website. https://www.cypress.io/support/
