### ISSUE TITLE
Bootstrap modal support seems to have regressed

### ISSUE THREAD

**Issue by echav** [cypress-io/cypress#3175]
### Current behavior:

Execute the following script; it fails unless you uncomment the cy.wait line
```
describe("Troubleshooting Cypress", function () {
    it("Bootstrap modals", function () {
        cy.visit("https://getbootstrap.com/docs/4.2/components/modal/");
        cy.get("#exampleModalLive").should("not.be.visible");
        cy.get("button[data-target='#exampleModalLive']").click();
        cy.get("#exampleModalLive button.close[data-dismiss='modal']").should("be.visible");
        // cy.wait(1000);
        cy.get("#exampleModalLive button.close[data-dismiss='modal']").click();
        cy.get("#exampleModalLive").should("not.be.visible");
    });
});
```
Error message:
`
CypressError: Timed out retrying: expected '<div#exampleModalLive.modal.fade.show>' not to be 'visible'
`

### Desired behavior:

I would have expected this script to run successfully without the need to add a cy.wait

### Steps to reproduce: (app code and test code)

Execute this script in the test runner and watch it fail as described above.

### Versions

Tested with Cypress 3.1.4 running Chrome 71 on macOs Mojave 10.14.2

**Comment by bahmutov** [comment]
This is the same issue as #3135

The Cypress click happens _before_ the modal is ready to handle clicks. You can either do the `cy.wait` or use something like `cypress-pipe` to keep clicking until the modal closes

```js
/// <reference types="cypress" />

describe('Troubleshooting Cypress', function () {
  it('Bootstrap modals', function () {
    cy.visit('https://getbootstrap.com/docs/4.2/components/modal/')
    cy.get('#exampleModalLive').should('not.be.visible')
    cy.get("button[data-target='#exampleModalLive']").click()
    cy.get("#exampleModalLive button.close[data-dismiss='modal']").should(
      'be.visible'
    )
    // cy.wait(1000);

    const click = $el => $el.click()

    cy.get("#exampleModalLive button.close[data-dismiss='modal']")
      .click()
      .pipe(click)
      .should($el => {
        expect($el).to.not.be.visible
      })
    cy.get('#exampleModalLive').should('not.be.visible')
  })
})
```

We are working on a blog post that describes this race condition, keep an eye on https://www.cypress.io/blog/ when it comes out

**Comment by bahmutov** [comment]
Take a look at blog post https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

**Comment by echav** [comment]
yes already read it, very clear - thanks a lot!
