### ISSUE TITLE
New error: It looks like this is your first time using Cypress: 3.1.4

### ISSUE THREAD

**Issue by hellfireSteve** [cypress-io/cypress#3176]
A new error appeared today, when running `npm run test:e2e`

The error says:

```
It looks like this is your first time using Cypress: 3.1.4

 ×  Verifying Cypress can run C:\Users\SStaple\AppData\Local\Cypress\Cache\3.1.4\Cypress
   → Cypress Version: 3.1.4
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Command failed: C:\Users\SStaple\AppData\Local\Cypress\Cache\3.1.4\Cypress\Cypress.exe --smoke-test --ping=159
----------

Platform: win32 (10.0.17134)
Cypress Version: 3.1.4
 ERROR  Error: Command failed: C:\Development\alloy-web\node_modules\@vue\cli-plugin-e2e-cypress\node_modules\cypress\bin\cypress open --config baseUrl=http://localhost:8082/
Error: Command failed: C:\Development\alloy-web\node_modules\@vue\cli-plugin-e2e-cypress\node_modules\cypress\bin\cypress open --config baseUrl=http://localhost:8082/
    at makeError (C:\Development\alloy-web\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Development\alloy-web\node_modules\execa\index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alloy-web@0.1.0 test:e2e: `vue-cli-service test:e2e --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alloy-web@0.1.0 test:e2e script.
```

This is entirely erroneous.
I have been using Cypress without a problem up until today.
There is a line which says 'The error below should indicate which dependency is missing.' - it doesn't.
I followed the link, & it is unconnected.

How do I restore this to working order?

**Comment by jennifer-shehane** [comment]
Hey @hellfireSteve, could you provide any more information on how you are running the cypress command? Also, what may have changed in the last week regarding your build process, CI, os settings, cypress settings, anything? 

This should not fail all of a sudden one day with no changes. Do you have loose version matching Cypress (like `^3.1.0`), did it update to `3.1.4` from a previous version?

**Comment by hellfireSteve** [comment]
Thanks @jennifer-shehane - the issue has now been solved. It had been updated from a previous version, 3.1.3. Ended up having to delete all versions of cypress in the cache & then re-installing Cypress 3.1.3

**Comment by jennifer-shehane** [comment]
In order to direct better focus on the overall problem that is being described in several issues - we opened one issue to track this behavior https://github.com/cypress-io/cypress/issues/4624 Please add any information about how we can reproduce this bug there. 🙏
