### ISSUE TITLE
Support multiple `env` passing in CLI

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#3178]
### Current behavior:

Seems as though it's impossible to pass in more than one `env` variable.

Test Code:

```js
describe('cli args', () => {
    it('should work with --env x=1', () => {
      expect(Cypress.env('x')).to.eq(1);
    })
    it('should work with --env y=1', () => {
      expect(Cypress.env('y')).to.eq(1);
    })
});
```

**GOOD**: Observation 1: `--env` works as expected when passing 1 argument 

```
cypress run --spec cypress/integration/cli_spec.js --env x=1
```

Expect 1 spec to be found, 1 test to pass, 1 test to fail 

![image](https://user-images.githubusercontent.com/2848185/51496752-eb321400-1d8e-11e9-8af5-890867b8476b.png)

**BAD 1** Try to pass in second argument - `--spec` is not honored

```
cypress run --spec cypress/integration/cli_spec.js --env x=1 y=1
```

![image](https://user-images.githubusercontent.com/2848185/51496814-23d1ed80-1d8f-11e9-9978-eeb212522aab.png)

*i needed to modify my codebase so that i could reproduce without --spec being passed in since i ran into this with a 30+ minute suite with 17 specs...*

Try to pass them in together:
```
cypress run  --env x=1 y=1
```

**BAD - Now NEITHER test will pass**

![image](https://user-images.githubusercontent.com/2848185/51497010-cb4f2000-1d8f-11e9-9e67-0350fba5ddb9.png)

![image](https://user-images.githubusercontent.com/2848185/51497021-d30ec480-1d8f-11e9-8724-91651f2138a6.png)

Try to pass them in separately:

```
cypress run  --env x=1 --env y=1
```

**BAD** - Only *second* argument is respected:

![image](https://user-images.githubusercontent.com/2848185/51497096-03566300-1d90-11e9-9e55-3a823d19f690.png)

I also tried -> seperate by `,` and seperate by `;`. none produce the desired behaviour. 

### Desired behavior:

Ideally, i could pass in more than one argument. Also, it would honor my `--spec` argument in the event i passed in more than one.

### Versions

Cypress 3.1.4, MacOS

**Comment by bahmutov** [comment]
@egucciar can you double check how you pass arguments? They should be a single argument, comma-separated. I am showing how to pass:

```shell
npx cypress run --env x=foo,y=bar
npx cypress run --env x=1,y=2
```

See commits

- strings in https://github.com/cypress-io/cypress-test-tiny/commit/9566fd84abfe19fa394552919c9b7d0cf97b7f9d
- numbers in https://github.com/cypress-io/cypress-test-tiny/commit/0696ab468bf7ab97f33fca371d2fca62d3263147

BTW, whenever you have a problem, I suggest cloning one of our small projects to show it, like

- https://github.com/cypress-io/cypress-test-tiny
- https://github.com/cypress-io/cypress-example-kitchensink
- https://github.com/cypress-io/cypress-example-todomvc

**Comment by egucciar** [comment]
@bahmutov great, thanks so much for the assistance. I tried comma separated but left in the space. Now with comma separated without space, it works perfectly. Thank you so much! i was worried I'd need to refactor my code to not rely on my second argument i hadn't thought to test until after i implemented everything.

Maybe a 1 line example in the docs for `--env` could clear up this confusion for someone else with the same usecase in the future.

**Comment by bahmutov** [comment]
Agree, that's why I have opened https://github.com/cypress-io/cypress-documentation/issues/1329 to document this.

**Comment by nathan5x** [comment]
This is good! But could you also support the following pattern?
```
npx cypress run --env x=1 --env y=2
```

Sometimes, the CLI params are derived differently depending on the environment it runs on (string concatenation is not ideal). It will be great if we have the above support as well. 

Thanks,
Nathan
