### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by quany** [cypress-io/cypress#3181]
Platform: darwin (18.2.0)
Cypress Version: 3.1.4
The Cypress App could not be unzipped.

**Comment by jennifer-shehane** [comment]
This may be due to a temporary network or file disk hiccup. We will need a reproducible example in order to address the issue. Can you provide it? Thanks!

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/3515
