### ISSUE TITLE
GitLab CI fails on cy.visit()

### ISSUE THREAD

**Issue by Studio384** [cypress-io/cypress#3182]
### Current behavior:

On opening tests in GitLab's CI, Cypress will fail the `beforeAll()` hook on its `cy.visit()`-command with a 404 error. This only seems to happen if the visit-url isn't `/`. For example this will work fine and will properly navigate to `/`:

```js
beforeEach(() => {
  // I work
  cy.visit('/');
});
```

But this example crashes with a 404 error despite `/queues` being a valid URL. When `/` and `/queues` are put together in the same `beforeEach()`, the `cy.visit('/')`-command will properly go to the root, but the subsequent navigation to `/queues` will also still fail with a 404 error.

```js
beforeEach(() => {
  // I'll fail with a HTTP/404 error
  cy.visit('/queues');
});
```

![327efda2-1b9b-4cb4-8828-7831d4bbe7e5](https://user-images.githubusercontent.com/1693592/51525615-02294280-1e31-11e9-8588-ebdc727f703a.png)

However first navigating to `/` with `cy.visit()` and then using the UI to navigate to `/queues` by using `cy.click()` *does* work. But this is for obvious reasons an undesired workaround.

```js
beforeEach(() => {
  // I'm a workaround and I work too
  cy.visit('/');
  cy.get('#menu-queues').click({ force: true }); // Links to /queues
});
```

### Desired behavior:

Cypress is able to go to the page and does not fail regardless of it being the root or not and without navigation to the root and then click to navigate to the desired page.

### Steps to reproduce: (app code and test code)

Given that this is more of an issue with the CI and GitLab and I have no idea why this happens it is hard to provide a reproducable repo setup.

### Versions
Cypress 3.1.4
GitLab runner (Docker)

**Comment by jennifer-shehane** [comment]
Hey @Studio384, how are you setting the baseUrl for your project? Is there anything unusual about the baseUrl - like multi-level subdomains or anything?

Could you run the project locally where this is failing and select 'Electron', open devtools and see if there is anything unusual there?

<img width="281" alt="screen shot 2019-01-23 at 3 22 11 pm" src="https://user-images.githubusercontent.com/1271364/51594370-accd5e00-1f22-11e9-9e79-ae94cbcae585.png">

**Comment by Studio384** [comment]
The BaseUrl is being set in `cypress.json` like this:

```json
{
  "baseUrl": "http://localhost:3000",
  "viewportWidth": 1920,
  "viewportHeight": 1080,
  "fixturesFolder": "test/fixtures",
  "integrationFolder": "test/integration",
  "pluginsFile": "test/plugins",
  "screenshotsFolder": "test/screenshots",
  "supportFile": "test/support",
  "videosFolder": "test/videos",
  "videoCompression": false,
  "numTestsKeptInMemory": 1
}
```json

I've written these tests with the both Electron and the latest Chrome. Here the `cy.visit()` works as expected and no errors are thrown in the console (in both Electron and Chrome).

**Comment by jennifer-shehane** [comment]
I notice the test title is called "Should set up a first voicemail 410", does this url have anything to do with a `410` status code?

Aside from this - I don't really see anything wrong with what you've provided so far. We would need more information. Ideally a reproducible example that we could run - app code + test code.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
