### ISSUE TITLE
Chromium installed via snap is not available in Cypress

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3183]
### Current behavior:

If Chromium is installed as a snap (`snap install chromium`), Cypress won't auto-detect it as a supported browser for testing:

![image](https://user-images.githubusercontent.com/1151760/51543360-60ebbd80-1e2b-11e9-9b1c-4832a372e465.png)

### Desired behavior:

Make Chromium installed as a snap available for testing without additional configuration, like the docs say: "[Cypress automatically detects available browsers on your OS.](https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers)"

### Steps to reproduce: (app code and test code)

1. Install Chromium as a snap
2. Open the Cypress GUI
3. Try to use it as a browser

### Versions

Cypress: latest develop branch  
Ubuntu 18.04.1  
Chromium 71 stable from https://snapcraft.io/chromium

### Potentially related issues

#1400

**Comment by flotwig** [comment]
Seems to be a side-effect of being named `chromium` instead of `chromium-browser`. I'll think up a nice way to add lists of binary aliases to the launcher tomorrow.

**Comment by flotwig** [comment]
With support for binary aliases comes the possibility that we'll encounter multiple versions of the same binary. So now the launcher needs to support launching a specific version, at least internally.

**Comment by flotwig** [comment]
I think that, in order to do this, we need to be passing the Browser objects from the launcher around internally. I did some digging and the server pretty much only identifies the current browser by "name" (`chrome`, `chromium`, etc...) and this won't do, especially if we want to eventually support arbitrary browser paths being passed in.

**Comment by bahmutov** [comment]
Yeah we need to pass more info, like the entire object if possible

**Comment by hackel** [comment]
This is not fixed for me.  Ubuntu 19.10 forced a migration from the chromium-browser deb package to the chromium snap, and now Chromium does not show up in Cypress 3.5.0.

**Comment by flotwig** [comment]
@hackel Is `/snap/bin/chromium` a shell script?

**Comment by hackel** [comment]
@flotwig no, it's a symlink to /usr/bin/snap, which detects the link name and runs "snap run chromium" or something internally.

**Comment by IlCallo** [comment]
Same problem here, Cypress 4.6, Linux 18.04, Chromium via snap 81.0.4044.138

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
