### ISSUE TITLE
Cherry pick alias UI work from v4.0 branch to develop

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#3185]
Alias UI work was done on the v4.0 branch as it was brought up during 4.0 discussions. Nothing about this work is specific to 4.0, so we'll cherry pick that into develop to be released with 3.2.

**Comment by chrisbreiding** [comment]
@jennifer-shehane The changelog for this should be taken from #477 since this is just a chore to get it out of the 4.0 branch. I'm going to mark that issue's Release as `3.3.0` since that's the truth of it.
