### ISSUE TITLE
trigger('mousemove', ...) yields undefined values for screenX and screenY in event handler

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3187]
### Current behavior:

Triggering `mousemove` via `.trigger` correctly fills in `pageX`, `pageY`, `clientX`, and `clientY`. However, Cypress fails to fill in the `screenX` and `screenY` values.
This can cause erroneous behavior if the application depends on them.

### Desired behavior:

`screenX` and `screenY` should probably just have the same values as `clientX` and `clientY`.

### Versions

3.1.4

**Comment by Bkucera** [comment]
@fr0 thanks for pointing this out, I'll put it in the mix for synthetic mouse fixes
