### ISSUE TITLE
Stubbing not working for 3xx redirect situations due to "Location" header

### ISSUE THREAD

**Issue by tlpbu** [cypress-io/cypress#3190]
### Current behavior:

When "Location" header is stubbed (common case for 301 and 302 redirects), cypress actually does not set stubbed response status code and header.

```js
cy.route({
    method: 'GET',
    url: '**/profile',
    response: '',
    status: 302,
    headers: {
        'Location': '/web/redirect/target'
  }
})
```

While Chrome devtools network tab shows response status as it was stubbed, application under test and Cypress itself interprets response with status code 200 and without "Location" header.
![See image](https://user-images.githubusercontent.com/8039755/51594260-b2b04880-1efc-11e9-9b3e-eee0c2597f90.png)

Same works with any other header I tried. Wild guess is that "Location" header is internally messing with Cypress' own `cy.location()` method or `window.location`.

### Desired behavior:

Response should have 302 status code and "Location" header.

### Versions
Cypress 3.1.3,
MacOS 10.14.2
Chrome 71

**Comment by jennifer-shehane** [comment]
It doesn't seem to matter whether you set the 'Location' in the headers, stubbing the response as 302 response responds with 200 status code. 

**Reproducible code**
```js
it('302 route', () => {
  cy.visit('http://example.cypress.io/commands/network-requests')
  cy.server()

  cy.route({
    method: 'GET',
    url: 'comments/*',
    status: 302,
    response: '',
  }).as('getComments')

  cy.get('.network-btn').click()
  cy.wait('@getComments').its('status').should('eq', 200)
})
```

<img width="559" alt="screen shot 2019-01-23 at 4 03 14 pm" src="https://user-images.githubusercontent.com/1271364/51597044-b5c12e00-1f28-11e9-9a58-0f8662a5c5bb.png">

**Comment by tlpbu** [comment]
Essentially stubbing works with any other header set in route options:
```
    it('302 route something else', () => {
        cy.visit('http://example.cypress.io/commands/network-requests')
        cy.server()

        cy.route({
            method: 'GET',
            url: 'comments/*',
            status: 302,
            response: '',
            headers: {
                'X-something-else': 'https://example.cypress.io/'
            }
        }).as('getComments')

        cy.get('.network-btn').click()
        
        cy.get('@getComments').then(res => {
            expect(res.status).to.eq(302)
            expect(res.response.headers).to.include.keys('X-something-else'.toLowerCase())
        })
    })
```
and same scenario fails with fails with "location" header in route options:
```
    it('302 route location', () => {
        cy.visit('http://example.cypress.io/commands/network-requests')
        cy.server()

        cy.route({
            method: 'GET',
            url: 'comments/*',
            status: 302,
            response: '',
            headers: {
                'Location': 'https://example.cypress.io/'
            }
        }).as('getComments')

        cy.get('.network-btn').click()
        cy.get('@getComments').then(res => {
            expect(res.status).to.eq(302)
            expect(res.response.headers).to.include.keys('Location'.toLowerCase())
        })
    })
```

**Comment by tlpbu** [comment]
@jennifer-shehane please let me know if some additional info is required from me in order get past `needs investigating` stage.

**Comment by tlpbu** [comment]
Ay progress with this issue?

**Comment by jennifer-shehane** [comment]
No work has been done on this feature. We will update when work is done.

**Comment by jennifer-shehane** [comment]
There was some discussion that this may not be a bug, but reflecting the behavior of how 302 redirects work - by essentially returning a 200 after redirection. 

I haven't really found the evidence to support this from [the spec](https://tools.ietf.org/html/rfc7231#section-6.4.3) or any other docs. @brian-mann

**Comment by tlpbu** [comment]
> behavior of how 302 redirects work - by essentially returning a 200 after redirection
This is apparently how it works in Cypress under the hood right now but IMHO routed endpoint should works as described in options and different URI (in location header) should be the one that returns 200 status code.

Currently this is impossible to write tests that verify redirection works and for example does not fail with unhandled exception in case endpoint which usually returns 2xx with body suddenly returns 302 with location to SAML site in when session has expired.

**Comment by tlpbu** [comment]
@jennifer-shehane any news about when this could be fixed?

**Comment by jennifer-shehane** [comment]
This issue still occurs in 9.5.3.

**Comment by Gora2ks** [comment]
Yes, true.
Issue still presented.
Could somebody fix it?
Thank you in advance.
Br,
Igor

**Comment by bradsobie** [comment]
I'm building an authentication app which relies on 302 redirects for api calls, and am running into a similar issue.

Example: user enters credentials, I make a fetch POST request with creds which will return a 302 redirect if authentication was successful. Since it's a fetch api call that is returning a 302, the user won't automatically be navigated to the url in the Location header. To fix that I send the request with `redirect: "manual"`, which tells the browser to not actually follow the redirect through, and allows me to intercept the redirect and actually do a window.location.href page change myself given the url from the Location header.

Unfortunately when trying to stub the Location header in cypress, cypress doesn't seem to pass this Location header url along when using `redirect: "manual"`. So when running in cypress my app is redirecting to the original url (the api endpoint in this case), which is not where the user is supposed to go.

**Comment by bradsobie** [comment]
To be clear, I understand that opaqueredirect does not give you access to the headers at all for security reasons, so I'm not attempting to access the redirect via the Location header directly, but rather through the response.url property. When running in a real app/browser, the fetch response.url becomes the value that was in the Location header. In cypress the response.url remains the original url.
