### ISSUE TITLE
Error: The 'task' event has not been registered in the plugins file. You must register it before using cy.task()

### ISSUE THREAD

**Issue by maksimkarpov** [cypress-io/cypress#3198]
### Current behavior:

I copied steps from https://github.com/cypress-io/cypress/issues/2284 with slight modification.

in my spec:

```
cy.task('seedRisks',{"model": "delete"})
```

in index.js:

```js
module.exports = (on) => {
  on('task:requested', (event, arg) => {
    switch (event) {
      case 'seedRisks': {
        console.log('sdjdsj'); //just a placeholder
      }
      }
  })
}
```

When I run my tests, getting error: 

```
CypressError: cy.task('seedRisks') failed with the following error:

The 'task' event has not been registered in the plugins file. You must register it before using cy.task()

Fix this in your plugins file here:
C:\Users\Maxim.Karpov\cypress\plugins\index.js

https://on.cypress.io/api/task
```

### Desired behavior:

want to be able to proceed without an error

**Comment by chrisbreiding** [comment]
You've registered `task:requested`. The event should be `task`:

```javascript
module.exports = (on) => {
  on('task', (event, arg) => {
    switch (event) {
      case 'seedRisks': {
        console.log('sdjdsj'); //just a placeholder
      }
      }
  })
}
```

**Comment by chrisbreiding** [comment]
Missed this in my original comment, but looks like you based this off an older version of the API. The `task` event also should receive an object instead of a function. I edited the code example in that comment to reflect the right API.

**Comment by maksimkarpov** [comment]
Hi Chris, thanks for your reply. I've moved  cy.task('seedRisks',{"model": "delete"}) into under "beforeEach" clause and the error is not given anymore. I'm now trying to understand if this is doing anything at all.

Now in my spec it is:

describe('trying to do db stuff', () => {
	
	it('query db', () => {
		
  beforeEach(() => {
    cy.fixture("bsa.json").as("user");
    
    cy.task('seedRisks',{"model": "delete"})
    cy.visit('/')
  });
    })    
}
)

and in index.js:

    module.exports = (on) => {
      on('task', (event, arg) => {
        switch (event) {
          case 'seedRisks': {
           
		   
		   const sql = require('mssql')

				async () => {
					try {
						await sql.connect('mssql://<un>:<pass>@<hiost>/<db>')
						const result = await sql.query`SELECT * from [dbo].[<table>]`
						cy.log(result)
					} catch (err) {
						cy.log(err);
					}
				}
		   
          }
         }
      })
    }

When the test is run I can't see any results of cy.log()
Not sure if it ever been triggered.
Do you know how do I check if my task fired in index.js?

**Comment by maksimkarpov** [comment]
Okay, it seems beforeEach doesn't do anything (((
Sorry, its my first week with cypress, looks like i'm doing all wrong

**Comment by maksimkarpov** [comment]
Thanks, Chris

So, now in index.js I have:

    module.exports = (on) => {
      on('task', {
        'seedRisks' () {
           console.log('sdjdsj'); //just a placeholder
         }
      })
    }

and in my spec:

    beforeEach(() => {
   
        cy.visit('http://google.com')
        cy.task('seedRisks',{"model": "delete"})
      
    
      })

Getting the same error

**Comment by maksimkarpov** [comment]
sorted, thanks

**Comment by bkluczynski** [comment]
What was the issue?

**Comment by ronaiza-cardoso** [comment]
I'm having this issue too. 

```
// Task
const userFactory = require("../../server/test/factories/userFactory");
const testHelper = require("../../server/test/testHelper.js");

module.exports = (on, config) => {
  let connection = null;
  on("task", {
    async createUser(ms) {
      connection = await testHelper.connectionForTestSetup();
      const userTest = await userFactory.create(connection);
      return userTest;
    }
  });
};

// In the test
cy.task("createUser").then(userTest => console.log("userTest", userTest));
```

I'm suspicious that the problem lives inside the require, because when I run again the test without the requires and write a simple test like this:

```
// Task
module.exports = on => {
  on("task", {
    hello({ greeting, name }) {
      console.log("%s, %s", greeting, name);

      return null;
    }
  });
};

// Test
cy.task("hello", { greeting: "Hello", name: "World" });
```

![image](https://user-images.githubusercontent.com/7999914/67003970-21f74980-f0d7-11e9-82f7-3f62ddeb2139.png)

Works as expected, but when I rerun the cypres open with the requires for the `userFactory` and the `testHelper` I have this issue:
![cytasherror](https://user-images.githubusercontent.com/7999914/67004175-99c57400-f0d7-11e9-887e-8af6d05825b4.jpg)

```
node --version      
v10.13.0
```

I've already made 
```
rm -rf package-lock.json node_modules
npm i
```

and

```
npm rebuild
```

## Cypress version
```
"cypress": "^3.4.1",
```

**Comment by ronaiza-cardoso** [comment]
Well, after some search my colleagues and I found out that the current project cypress version needs these packages:
```json
"electron-rebuild": "^1.8.6",
"@babel/register": "^7.6.2",
"@cypress/browserify-preprocessor": "^2.1.1",
```
and need to run this command after `npm i`:
```json
"postinstall": "electron-rebuild -v **2.0.18**"
```
** the version is the one that has been used by cypress.

my `Project-folder/cypress/plugins/index.js` now is like this:
```js
require("@babel/register");
const browserify = require("@cypress/browserify-preprocessor");
const testHelper = require("../../server/test/testHelper");

module.exports = on => {
  on("file:preprocessor", browserify());

  on("task", {
    async createUser(data) {
      const connection = await testHelper.connectionForTestSetup();
      console.log("connection", connection);
      return null;
    }
  });
};
```

**Comment by monsam** [comment]
I am facing same issue! total crap!

**Comment by jennifer-shehane** [comment]
If you're facing this issue:

- Double check your code in the plugins file, it should match the `task` signature here: https://on.cypress.io/task#Usage
- Double check that your plugins file is building and compiling correctly. 

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by yyss8** [comment]
I was getting this issue as well when creating tasks for the first time in my project. It seems like restarting the cypress instance is needed after making some changes in the plugin file (node process side).

**Comment by J-QA** [comment]
I'm having the same issue on cypress 6.0.0, I have tried ronaiza's approach and some others with no success, am I missing something?
```
// in the test file 
cy.task('testing', 'This will be output to the terminal')    
```
```
// in the cypress/plugins/index.js
module.exports = (on, config) => {
  on('task', {
    testing (message) {
      console.log(message)

      return null
    }
  })
}
```
```
CypressError: `cy.task('testing')` failed with the following error:

The 'task' event has not been registered in the plugins file. You must register it before using cy.task()

Fix this in your plugins file here:
false
```

**Comment by chrisbreiding** [comment]
@J-QA Check your `cypress.json` for `"pluginsFile": false`. That keeps the plugins file from being loaded. That's why the error messaging says:

```
Fix this in your plugins file here:
false
```

`false` is where the path to the plugins file would be displayed if it was loaded. 

Remove `"pluginsFile": false` from `cypress.json` and `cy.task()` should work.

Looks like we could improve the error message for this case and make it clear that `cy.task()` won't work because the plugins file has been disabled.

**Comment by J-QA** [comment]
It worked like a charm, thank you @chrisbreiding for the quick response!

**Comment by J-QA** [comment]
> @J-QA Check your `cypress.json` for `"pluginsFile": false`. That keeps the plugins file from being loaded. That's why the error messaging says:
> 
> ```
> Fix this in your plugins file here:
> false
> ```
> 
> `false` is where the path to the plugins file would be displayed if it was loaded.
> 
> Remove `"pluginsFile": false` from `cypress.json` and `cy.task()` should work.
> 
> Looks like we could improve the error message for this case and make it clear that `cy.task()` won't work because the plugins file has been disabled.

It worked like a charm, thank you @chrisbreiding for the quick response!

**Comment by geekdevil** [comment]
I get the same error with cypress 8.2.0. My cypres.json does not have pluginsFile: false also. Not sure where I am making a mistake:

`{
  "projectId": "myproject",
  "integrationFolder": "cypress/e2e",
  "supportFile": "cypress/support/index.js",
  "retries": {
    "runMode": 1,
    "openMode": 0
  },
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "results/my-test-output-[hash].xml",
    "toConsole": true
  },
  "reporter": "mochawesome",
  "reporterOptions": {
    "reportDir": "cypress/results",
    "overwrite": false,
    "html": false,
    "json": true
  },
  "screenshotsFolder": "mochawesome-report/assets",
  "defaultCommandTimeout": 7000
}
`

**Comment by lasithdilshan20** [comment]
@chrisbreiding
@jennifer-shehane 

I have the same issue with the Imagesnapshot command,

![image](https://user-images.githubusercontent.com/16818367/144791617-a62ea8e6-0f85-4a17-87ad-52f1d8f38a7f.png)


cy.task('Matching image snapshot') failed with the following error:

The task 'Matching image snapshot' was not handled in the plugins file. The following tasks are registered: compareSnapshotsPlugin, copyScreenshot, generateReport

**Comment by Elidor00** [comment]
After a lot of experiments, I solved in this way:
```
"pluginsFile": "./src/plugins/index.ts",
```
Is not sufficient remove `pluginsFiles` option form `cypress.json`, as @chrisbreiding said, but you need to specify the relative path of `index.ts` file inside `plugins` folder.


### Using
`"@nrwl/cypress": "13.1.2"`
`"cypress": "^8.3.0",`

**Comment by mshamshaddin1** [comment]
> @chrisbreiding @jennifer-shehane
> 
> I have the same issue with the Imagesnapshot command,
> 
> ![image](https://user-images.githubusercontent.com/16818367/144791617-a62ea8e6-0f85-4a17-87ad-52f1d8f38a7f.png)
> 
> cy.task('Matching image snapshot') failed with the following error:
> 
> The task 'Matching image snapshot' was not handled in the plugins file. The following tasks are registered: compareSnapshotsPlugin, copyScreenshot, generateReport

Did you find a fix for the Imagesnapshot command err mentioned here, I am having same error?

**Comment by WhyAsh5114** [comment]
I had a similar issue, I solved it by specifying my file in the cypress.json like so:
`{
    "pluginsFile": "./cypress/plugins/index.cjs"
}`

I think by default cypress looks for a `.js` file, and not `.cjs` or `.ts`.
