### ISSUE TITLE
passing option respond: true to cy.route does not cause response.

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#32]
If I have `cy.server` with `respond: false` option, then have a `cy.route()` with an option of `respond: true`, the route does not properly respond.

**Example**
```js
cy.server({
  respond: false
}).route({
  method: "PATCH",
  url: /forms/,
  response: {},
  respond: true
});
```

**Comment by brian-mann** [comment]
This isn't supported at this time.  We'll see if other people also have this issue and then I'll work on fixing it.  It would cause a lot of code to be restructured.

In the mean time, just invoke a new server to cause it to auto respond again.

```js
cy.server().route(...)
```

**Comment by jennifer-mann** [comment]
Closing due to lack of interest in feature.
