### ISSUE TITLE
Changelog generation and release notifications

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3203]
Currently we write the Changelog file (in cypress-documentation repo) manually based on releases in ZenHub. It would be nice to automate this work. The generated Changelog file can be then manually edited and added to our documentation and to GitHub releases in this repo.

First, write it as CLI tool, maybe a bot is not necessary. Also, huge bonus if there are tools that can do this already.

**Comment by jennifer-shehane** [comment]
This was already delivered in https://github.com/cypress-io/release-automations/tree/master/packages/issues-in-release
