### ISSUE TITLE
Find all issues that went into the release X.Y.Z

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3204]
Based on `release` in ZenHub (how to query its API). For example all issues with release `3.1.5` will become part of the release v3.1.5.

- query ZenHub
- generate Markdown

**Comment by bahmutov** [comment]
Bonus: collect issues AND pull requests labeled

**Comment by brian-mann** [comment]
As long as the PR isn't connected to the issue. We don't set the release on both PR's AND issues - but if we are merging in a PR from an outside contributor, sometimes there isn't an associated issue - and in those cases, we would need to reference the PR only.

**Comment by bahmutov** [comment]
ZenHub API https://github.com/ZenHubIO/API

**Comment by bahmutov** [comment]
Wat

<img width="1124" alt="screen shot 2019-01-25 at 9 22 21 am" src="https://user-images.githubusercontent.com/2212006/51751412-d00f1f00-2082-11e9-8d72-6fae4fbe168e.png">

<img width="695" alt="screen shot 2019-01-25 at 9 22 28 am" src="https://user-images.githubusercontent.com/2212006/51751421-d43b3c80-2082-11e9-9ae4-2d5edf3b24a3.png">

**Comment by bahmutov** [comment]
this repo has GitHub repo id 31629751

**Comment by bahmutov** [comment]
We can find all releases in the repo
```
GET https://api.zenhub.io/p1/repositories/31629751/reports/releases
```
returns long list, including
```json
[{
    "release_id": "5c235b536098e40af3969349",
    "title": "3.1.5",
    "description": "",
    "start_date": "2018-12-26T10:43:10.000Z",
    "desired_end_date": "2019-01-19T05:30:00.000Z",
    "created_at": "2018-12-26T10:43:31.889Z",
    "closed_at": null,
    "state": "open"
  }]
```

**Comment by bahmutov** [comment]
Great, seems pretty straightforward to query ZenHub API to get all release issues and pull requests and then we can use GitHub API to comment on each with a release message. I had code to post GitHub comment in https://github.com/bahmutov/github-post-release

**Comment by bahmutov** [comment]
Created a tiny private repo for now https://github.com/cypress-io/issues-in-release that fetches all issue numbers. Can make it into a CLI tool to
- bulk set labels like `released`
- generate markdown file with changelog. Probably would require for each issue in the release finding the commit that closed it or PR and grabbing subject from it. Or maybe having a special section in the issue or commit like `Changelog` that gives the text to include
- comment on each issue with given message

**Comment by bahmutov** [comment]
Ok, will generate a markdown with all issues that went into release

**Comment by bahmutov** [comment]
Done
