### ISSUE TITLE
Comment on each issue that went into the release after publishing Cypress version

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3205]
We need to comment on each issue that was closed for release with a comment that says "Version X.Y.Z has been published" and maybe links to the Changelog and any other information.

Inspiration: semantic release bot here: 
- comment and label `release` https://github.com/bahmutov/cypress-dark/issues/29 

<img width="723" alt="screen shot 2019-01-23 at 3 46 34 pm" src="https://user-images.githubusercontent.com/2212006/51635986-169b3700-1f26-11e9-8ba8-1c08c9df2f7b.png">

**Comment by bahmutov** [comment]
bonus: comment on all pull requests that went into release

**Comment by brian-mann** [comment]
same rules as my comment here: https://github.com/cypress-io/cypress/issues/3204#issuecomment-457067802

**Comment by brian-mann** [comment]
@bahmutov 	whenever i leave a final comment on closed issues I just write this - short and sweet: https://github.com/cypress-io/cypress/issues/562#issuecomment-393025705
