### ISSUE TITLE
Collect all dependencies updated by Renovate Bot that went into release

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3206]
And include as a section in the generated Changelog

- top level in NPM package? Or all packages?

**Comment by brian-mann** [comment]
all packages i suppose - else its not really even valuable to give at all

**Comment by brian-mann** [comment]
we could likely just scan the commits for any changes to `package.json` that were part of `dependencies`... now that i think about it, it's only relevant to users if its part of the binary

**Comment by jennifer-shehane** [comment]
I only add dependency updates from `dependencies` and ignore anything in `devDependencies` when writing the changelog currently. A typical example of this section in the [Changelog](https://on.cypress.io/changelog):

```
**Dependency Updates**

- Upgraded `commit-info` from `2.0.0` to `2.1.1`. Fixes {% issue 2848 %}.
- Upgraded `lodash` from `4.17.10` to `4.17.11`. Fixes {% issue 2929 %}.
```

Issue url may go to an actual issue or just the PR.

**Comment by bahmutov** [comment]
So right now that section has all dependencies and only the target version. I could search package json file to see if the dependency update was dev (and skip it) or prod (and include it in the changelog)

**Comment by jennifer-shehane** [comment]
Yes, this would be preferable to me. I don't want users flooded with concerns over our update of a dev dependency that they have no reason to know about. I for one would hate to sift through this in a changelog.

**Comment by jennifer-shehane** [comment]
This has already been delivered as part of https://github.com/cypress-io/release-automations/tree/master/packages/issues-in-release
