### ISSUE TITLE
Changing ZenHub pipeline should change label on the GitHub issue

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3208]
If we start working on the issue and move it in the pipeline

<img width="440" alt="screen shot 2019-01-23 at 4 03 05 pm" src="https://user-images.githubusercontent.com/2212006/51636950-7abefa80-1f28-11e9-8cef-c70d1654f1e2.png">

it should change the "state: ..." label on that GitHub issue.

**Comment by flotwig** [comment]
Looks like ZenHub exposes a nice webhook for when an issue changes pipelines:

https://github.com/ZenHubIO/API#issue-transfer

And then we could use webtask to POST that change to GitHub using a personal access token.

**Comment by brian-mann** [comment]
We also need to do the REVERSE way. when updating a label in github, it needs to automatically update zenhub. 

That would make it bi-directional and obviously we would first reconcile if the state already matches to be a no-op.

this would allow both @jennifer-shehane 	doing support through zenhub and for issues to be labeled inside of github and it naturally synchronize.

we'd also get the bonus that when issues "close" they automatically move zenhub pipelines, which would then update the label as part of the hook

**Comment by NathanSweet** [comment]
This is important for me, as it allows issue management on either GitHub or ZenHub. Without labels being sync'ed to pipelines: 1) adding/removing labels in GitHub leave the issue in the wrong pipeline and, 2) from GitHub it's not possible to see which pipeline the issue is in.

**Comment by jennifer-shehane** [comment]
This has already been delivered as part of https://github.com/cypress-io/release-automations

**Comment by inspectorG4dget** [comment]
The link mentioned [here](https://github.com/cypress-io/cypress/issues/3208#issuecomment-510807584) is broken. I am also looking for this functionality. Could you please provide a link to the documentation?

**Comment by jennifer-shehane** [comment]
@inspectorG4dget Yeah, it's a private repo unfortunately. 😕
