### ISSUE TITLE
Unable to open cypress v.3.1.4 on windows

### ISSUE THREAD

**Issue by ggcaponetto** [cypress-io/cypress#3212]
### Current behavior:
Cypress doesn't open.

### Steps to reproduce: (app code and test code)

1. Update cypress to v3.1.4 on a windows host via ``npm i cypress@3.1.4``
2. run ``./node_modules/.bin/cypress open`` 

```
> cypress open

It looks like this is your first time using Cypress: 3.1.4

 ×  Verifying Cypress can run C:\Users\Giuseppe\AppData\Local\Cypress\Cache\3.1.4\Cypress
   → Cypress Version: 3.1.4
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Command failed: C:\Users\Giuseppe\AppData\Local\Cypress\Cache\3.1.4\Cypress\Cypress.exe --smoke-test --ping=920
----------

Platform: win32 (10.0.17134)
Cypress Version: 3.1.4

```
### Desired behavior:
cypress opens

### Versions

Platform: win32 (10.0.17134)
Cypress Version: 3.1.4

**Comment by jennifer-shehane** [comment]
Can you try [clearing your Cypress cache](https://on.cypress.io/command-line#cypress-cache-clear) then rerunning the command (suggesting based on https://github.com/cypress-io/cypress/issues/3176#issuecomment-456737411).

```
cypress cache clear
```

**Comment by ggcaponetto** [comment]
Solved clearing the cypress cache as described in the link provided by @jennifer-shehane . Thanks
