### ISSUE TITLE
cy.get('element').invoke('text') changes case of text

### ISSUE THREAD

**Issue by sahithya** [cypress-io/cypress#3214]
### Current behavior:

I'm using the `cy.get('element).invoke('text')` to get the text of an `h2` element in a test. 
The text of the element is **"My Cool Text"**. 
The Cypress invoke call yields **"My cool text"** making some of the text lower case and leading to some false positive assertions.

### Desired behavior:

`cy.get('element).invoke('text')`  yields the text of the HTML element as is without changing case. 

### Steps to reproduce: (app code and test code)

-Use cy.get() to get the first h2 element from the your test
- Call invoke('text') to obtain the text of the element
- Verify that the case changed. 

### Versions
cypress: 3.1.3
Chrome version 71.0.3578.98 (Official Build) (64-bit)

**Comment by Bkucera** [comment]
@sahithya you most likely have `text-transform: capitalize` on the element. Can you verify this? In that case, getting the text should return the lowercased text

**Comment by jennifer-shehane** [comment]
Closing due to no followup response. Please comment if you are still experiencing this issue and it is not related to css styling properties.
