### ISSUE TITLE
Doesn't start Chrome and Chromium on Linux Manjaro

### ISSUE THREAD

**Issue by marinakuranda** [cypress-io/cypress#3217]
Hello, thanks for working on Cypress!

I might be missing some trivial solution, please help me out.

### Current behavior:

I have a fresh local installation of Cypress for my project on my computer, no custom configuration just the default stuff user gets from opening Cypress.

It runs in Electron as expected out of the box, but if I specify a different browser I get the error:

```bash
npx cypress run --browser google-chrome-stable 
Can't run because you've entered an invalid browser.

Browser: 'google-chrome-stable' was not found on your system.

Available browsers found are: electron
```

### Desired behavior:

It runs Chrome or Chromium.

### Versions

Browser
```
chrome --version
Google Chrome 71.0.3578.98 
```

```
chromium --version
Chromium 71.0.3578.98 Arch Linux
```

OS

```bash
hostnamectl 
  ...
  Operating System: Manjaro Linux
            Kernel: Linux 4.19.13-1-MANJARO
      Architecture: x86-64
```

Cypress

```bash
npx cypress --version
Cypress package version: 3.1.4
Cypress binary version: 3.1.4
```

**Comment by marinakuranda** [comment]
Doing ln `which chrome` /usr/local/bin/google-chrome` helped, thanks a lot!

**Comment by roschaefer** [comment]
@marinakuranda I stumbled over this and got it resolved by upgrading `cypress` from `3.1.3`=>`3.2.0`. Seems the new version is looking for other binaries like `chromium` (on Manjaro/Archlinux :blue_heart:  :penguin: ) and `chromium-browser` (which is the binary on debian based systems). You can also set the path manually as stated in the [docs](https://docs.cypress.io/guides/guides/launching-browsers.html#Launching-by-a-path).

**Comment by loveqseven** [comment]
I have the same issue when I run test through gitlab, these are message:
Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system.

Available browsers found are: electron

**Comment by jennifer-shehane** [comment]
@loveqseven Please read through our guide on debugging launching browsers. https://docs.cypress.io/guides/guides/debugging.html#Launching-browsers

You will need chrome installed on your machine to run in chrome.
