### ISSUE TITLE
cy.request should `followAllRedirects` to mimic actual browser behavior

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#322]
Currently `cy.request` will not follow redirects on a non-GET request which was redirected.

This behavior differs from the way a real browser would work, and it needs to automatically follow this redirect, and by default use the `GET` method for the redirects.

**Comment by brian-mann** [comment]
Fixed in [`0.18.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0181-12112016).

**Comment by vinh3928** [comment]
@brian-mann is there support for react routing for cypress to follow the redirect that react handles?

**Comment by brian-mann** [comment]
@vinh3928 what do you mean? `cy.request` makes an HTTP request. React "redirects" aren't real redirects - they are client side redirects with the "hash" part of the URL.

An http request does not actually evaluate javascript - so the only thing `cy.request` respects are a real HTTP redirect with status code and `Location` headers.

This sounds like an [XY problem](http://xyproblem.info/) though - so maybe you could explain what it is you are trying to accomplish.

**Comment by vinh3928** [comment]
Sorry I'm not familiar enough with cypress; I'm doing a spike and researching different e2e frameworks. I found my answer in cy.visit

**Comment by vinh3928** [comment]
But the docs said you can use cy.request to skip setting up your state via through the ui and do a post to the endpoint you want your state in, the endpoint typically runs a redirect from the backend. But in a react app the routing is done on the frontend so the post doesn't redirect. Thats why I was confused.

**Comment by vinh3928** [comment]
Thank you for you help Brian, that makes sense.

**Comment by brian-mann** [comment]
@vinh3928 we recently gave a talk at a conference last week that talked about what you're asking about.

The slides are here: https://speakerdeck.com/brianmann/cypress-best-practices

They recorded the talk but have not yet posted the video. When they do I'll update the issue.
