### ISSUE TITLE
--spec doesn't recursively find all matching files in the entire folder hierarchy

### ISSUE THREAD

**Issue by jennliacl** [cypress-io/cypress#3220]
### Current behavior:
I added `"integrationFolder": "./app",` in `cypress.json`
and in the `app` folder i have 
`app/folder1/test1.spec.js`
`app/folder1/folder2/test2.spec.js`
`app/folder1/folder2/folder3/test3.spec.js`

when running `cypress run --browser chrome --spec ./app/**/*.cyp.js`
the resulting run only includes tests from `test1.spec.js`, and test2 and test3 are ignored.

### Desired behavior:
Given that file pattern argument provided for `--spec` I should be able to run all the specs in every folder and subfolder, in addition to running only the specs directly within folder1.

### Versions
version 3.1.3

OS is irrelevant as it's reproducible in both linux CI environment and on local Macbook.

**Comment by Bkucera** [comment]
@jennliacl can you try setting `integrationFolder:'./app'` in `cypress.json`? By default cypress looks in `cypress/integration`

**Comment by Bkucera** [comment]
@jennliacl can you try `--spec '**/*.cyp.js'` with quotes around the argument?

**Comment by jennliacl** [comment]
Oh! IT WORKED. also I found the documentation where it says `quotes required`. Thanks very much!
