### ISSUE TITLE
Events like mouseover don't trigger hover state on element inside an SVG

### ISSUE THREAD

**Issue by GraceAgony** [cypress-io/cypress#3222]
### Current behavior:
Tried to simulate hover state using the trigger('mouseover') on the element inside an SVG, cypress doesn't simulate this.

The line must become red when it's hover, but it's still green: 

![image](https://user-images.githubusercontent.com/20641225/51748929-893b1c80-20b6-11e9-808c-13dcc439fa8a.png)

 It correctly found the element but didn't force hover state 

![image](https://user-images.githubusercontent.com/20641225/51749038-e6cf6900-20b6-11e9-9c6d-357fffb7ad7f.png)

### Desired behavior:
![image](https://user-images.githubusercontent.com/20641225/51748968-b7206100-20b6-11e9-9811-7588f6d42fcf.png)

### Steps to reproduce:
App code
```
class App extends Component {
  render() {
    return (
      <div className="App">
        <svg height="210" width="400">
        <path d="M 0 200 l 150 0" />
      </svg>  
      </div>
    );
  }
}
  ```
CSS:
```

path{
  stroke:green;
  fill:none ;
  stroke-width: 10;
}

path:hover{
  stroke:red;
}
```

Test code:
```
 it('visualization test', () => {
   cy.get('#root > div > svg > path')
    .trigger('mouseover')
    .should('have.css', 'stroke')
    .and('equal', 'red')
  })
```

### Versions
```
 "cypress": "^3.1.4"
```

**Comment by Bkucera** [comment]
Hi @GraceAgony, please see our docs on `hover` https://docs.cypress.io/api/commands/hover.html

we do not currently respect css hover pseudo-selectors, but it is on out roadmap

see #10
