### ISSUE TITLE
Feature request: test sections

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3223]
When I first started writing tests, I originally organized them like unit tests. This meant each test was small and contained, and only tested one simple thing.
I've learned that it's better to have larger tests that test an entire feature, since this speeds up test execution and reduces duplicated actions.
However, I still want to be able to "group" actions within a test, so I know what part of the test is running when I'm looking at the test log.
I've been using `cy.log` for this.  For example, here's a original test spec before I started grouping them together:

```
context('parameters', () => {
  it('allows the user to add a parameter');
  it('allows the user to delete a parameter');
  it('allows the user to rename a parameter');
});
```

And here's what I'm doing now:

```
it('allows the user to edit parameters', () => {
  cy.log('*** add parameter ***');
  cy.log('*** delete parameter ***');
  cy.log('*** rename parameter ***');
});
```

This works fine, but the `cy.log` statements get lost in the noise and are hard to pick out.

![screen shot 2019-01-25 at 10 50 18 am](https://user-images.githubusercontent.com/435418/51756467-0fdc0380-208f-11e9-843a-4dff33b186fd.png)

I'd love to have a `cy.section` command that works like `cy.log` but with some additional styling, e.g.:

![screen shot 2019-01-25 at 10 53 22 am](https://user-images.githubusercontent.com/435418/51756626-782ae500-208f-11e9-9c94-f3968dbbfff1.png)

Bonus points if I can expand/collapse the sections.

**Comment by fr0** [comment]
I wasn't aware that plugins could tweak the styling of the log - do you have an example of one that does this? I'd be glad to take a shot at implementing it.

**Comment by fr0** [comment]
Alright, I've implemented something - here's what I've got (in `cypress/support/section.ts`):
```
Cypress.Commands.add('section', text => {
  Cypress.log({
    name: 'section',
    message: [`*** ${text} ***`]
  });
});

const css = `
.command-name-section {
  background: #008100;
  padding-top: 4px;
  padding-bottom: 2px;
}
.command-name-section .command-wrapper .command-method,
.command-name-section .command-wrapper .command-number,
.command-name-section .command-wrapper .command-message {
  color: white;
}
`.trim();
const win = window.opener || window.parent;
const head = win.document.head || win.document.getElementsByTagName('head')[0];
const style = win.document.createElement('style');

if (style['styleSheet']){
  // This is required for IE8 and below.
  style['styleSheet'].cssText = css;
} else {
  style.appendChild(win.document.createTextNode(css));
}

head.appendChild(style);
```

It would take more work to get collapsible sections, but I'll save that for a later time.

**Comment by bahmutov** [comment]
Nice! Cypress UI is a web app itself so you have full power ;)

**Comment by Bkucera** [comment]
@fr0 possibly [proposal](#1581) is a super-set of this issue. And it has a great idea, where assertions will continue to run after other failed assertions.

I'm going to close this as duplicate so we can consolidate these proposals
