### ISSUE TITLE
Cypress's dblclick does not function the same way as a user double clicking

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#3224]
### Current behavior:
Firing Cypress's `dblclick()` does not behave the same way as a user double clicking an element.  Specifically, if there is no special meaning for a double click, then when a user double clicks, the first `click` event triggers a `click` action.  However, with `dblclick()`, if nothing is defined specifically for a double click, then the element is put in focus, but the action associated with a single click does not occur. See test example below.  

### Desired behavior:
Firing Cypress's `dblclick()` behaves the same way as a user double clicking an element.  I would expect that in both the examples below Cypress would navigate to the "mission" page, because a user double clicking on a link would be interpreted as a single `click` event if no special meaning is defined for the double click.

### Steps to reproduce:
```
it('Example of successful single click', () => {
  cy.visit('https://www.google.com');
  cy.contains('About').click();
  cy.contains('Our mission is to');
});

it('Example of unsuccessful double click', () => {
  cy.visit('https://www.google.com');
  cy.contains('About').dblclick();
  cy.contains('Our mission is to');
});
```

### Versions
Windows 10
Cypress 3.1.4
Chrome 71

**Comment by calvinballing** [comment]
Also, for context, the reason I was trying to test this is I want to ensure that a particular button will only trigger the associated action once, rather than twice.  Right now we have a button that will trigger it's associated event multiple times if rapidly clicked in succession, but which should be locking out the user immediately after it is used the first time.  I've also tried .click().click(), and .type('{enter}{enter}') but neither of these work for my particular circumstance.

**Comment by calvinballing** [comment]
Possible consideration, what if .click() could take an argument telling it to click _x_ number of times on the same element repeatedly, separated by delays of _y_ milliseconds?

**Comment by Bkucera** [comment]
as a workaround, you can try this:

```
cy.get('button#foobar')
  .trigger('click', {detail: 1})
  .trigger('click', {detail: 2})
  .trigger('dblclick', {detail: 2})

```

**Comment by calvinballing** [comment]
@Bkucera Using multiple instances of .trigger('click') was successful for me as a workaround for simulating a double click.  Since I'm on the QA side, while I know what the current issue is, I'm not certain what method our dev team will implement to ensure it behaves as expected going forward. In similar instances we have had in the past the solutions we've used have worked fine though.

**Comment by scipper** [comment]
`cy.get("selector").click().dblclick()` works as well.
