### ISSUE TITLE
Cypress-to-electron version mapping

### ISSUE THREAD

**Issue by jdoubleu** [cypress-io/cypress#3228]
### Current behavior:
It is not straightforward to find out which electron version is used by Cypress.

There are also some issues with the current electron version (see #2559, #2069, 2516).
These errors can be resolved e.g. by using `babel-preset-env` and transpile the code to work with older versions of Chrome (as part of Electron).

### Proposal
It would be nice if Cypress could provide a tool similar to [`electron-to-chrome`](https://github.com/kilian/electron-to-chromium) which simply maps a given Cypress version to a Chrome version.

This Cypress version can then be used in conjunction with `babel-preset-env` in a `.browserlistrc`.

**Comment by jennifer-shehane** [comment]
Comments on Cypress being coupled to Electron version today: https://github.com/cypress-io/cypress/issues/2761#issuecomment-453563443

**Comment by dschuessler** [comment]
This is especially important if binary dependencies have to be built against the matching Electron runtime as described here: https://github.com/cypress-io/cypress/issues/3649#issuecomment-470713589

I'd like to use gRPC in my Cypress tests, but I'm totally stuck, because I simply can't find out the Electron version currently used.

**Comment by jennifer-shehane** [comment]
You can always find the current version of Electron in our `electron` package here: https://github.com/cypress-io/cypress/blob/develop/packages/electron/package.json#L27

**Comment by flotwig** [comment]
There are two ways that I know of to find the current version of Electron from within Cypress:

1. Use [`Cypress.browser.version`](https://docs.cypress.io/api/cypress-api/browser.html#Syntax) while running in Electron to get the current Chromium version bundled with Electron. Then, use [`electron-to-chromium`](https://www.npmjs.com/package/electron-to-chromium)'s `chromiumToElectron` to determine the earliest possible/all possible Electron versions.
2. Use a [`cy.task`](https://on.cypress.io/task) (or other plugin event) to read the current value of `process.versions.electron`

**Comment by jennifer-shehane** [comment]
Verified the ways suggested are working to get the current Electron version:

```js
module.exports = (on, config) => {
  const ElectronVersion = process.versions.electron

  console.log(ElectronVersion)

  on('file:preprocessor', (file) => {
    // can use version here
  })

  on('task', {
    // can use version here
  })

  // or any other plugin event or custom code you have
}
```

I'm going to close this as resolved since there seems to be a reasonable workaround for the cases asked for here.

**Comment by inorganik** [comment]
I see the Electron version is somewhere around v11, but in the Cypress UI it shows "Electron 80" (I'm on cypress 4) - does "80" correspond to the version of chrome?

**Comment by flotwig** [comment]
@inorganik that is correct. Electron is currently at 11.x in released versions of Cypress and will be bumped to 12.x when Cypress 7.0 is released.

**Comment by inorganik** [comment]
@flotwig Thanks! Is there anyway to pin a version of electron/chrome, e.g v87? Guessing not but wanted to check.

**Comment by flotwig** [comment]
@inorganik no, each version of Cypress is pinned to the version of Electron it ships with. But you can install the desired version of Chrome on your CI system and run with `--browser chrome`: https://docs.cypress.io/guides/guides/launching-browsers.html
