### ISSUE TITLE
add Cypress.log.groupEnd() and Cypress.log.groupCollapsed()

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3229]
It would be nice `Cypress.log.groupEnd()` and `Cypress.log.groupCollapsed()` APIs similar to those of `console.groupCollapsed()` `console.groupEnd()` but **for the command log**

Cypress.log.groupEnd() and Cypress.log.groupCollapsed() similar to 

https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed

This would help users make plugins like this proposal #1581 

- [ ] groupCollapsed, groupEnd
- [ ] custom styling of logs

**Comment by hinfaits** [comment]
This would be really great for us. We have long test cases that build up a lot of stored state and slow down cypress when running interactively.

Being able to periodically purge state would be huge.

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/issues/1260 which would essentially include this feature.
