### ISSUE TITLE
cy.request clarify on status code failures, enable 3xx to be successful

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#323]
Currently the `failOnStatus` property can be passed to `cy.request` to turn off failing based on a non `2xx` status code.

This needs to be upgraded to also not fail on `3xx` status code, and we should rename this property to be `failOnStatusCode` to clarify what this property does.

We'll keep the old property name backwards compatible for now and log a deprecation warning.

**Comment by brian-mann** [comment]
Fixed in [`0.18.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0181-12112016).

**Comment by royc-adsk** [comment]
Is status code 302 is supported by Cypress?

**Comment by jennifer-shehane** [comment]
@royc-adsk yes
