### ISSUE TITLE
.should chained off .then does not retry

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress#3230]
```js
it('test', () => {
  cy.window()
  .then((win) => {
    setTimeout(() => win.foo = 'bar', 1000)
    return win
  })
  .should((win) => {
    expect(win.foo).to.eq('bar')
  })	
})	
```

also causes issue here: https://github.com/cypress-io/cypress/issues/627

<img width="653" alt="Screen Shot 2021-01-05 at 4 01 09 PM" src="https://user-images.githubusercontent.com/1271364/103629858-40ad5e80-4f6f-11eb-8011-0431096f44e1.png">

**Comment by lukeapage** [comment]
Its basically the reason for https://github.com/NicholasBoll/cypress-pipe having to exist.

**Comment by Bkucera** [comment]
@lukeapage the functionality proposed here is basically making this:

(doesn't retry)
```js
cy.then(foo => foo)
  .should(foo => {
	return foo.isValid()
  })
```

act like this:

(does retry)
```js
cy.then(foo => foo)
  .then(foo => {
	cy.wrap(foo).should(foo => {
      return foo.isValid()
    })
  })
```

**Comment by BlueWinds** [comment]
Very old issue which will be resolved as part of the Detached DOM initiative. Discovered it because it's linked in one of our commented out tests.

Closing as duplicate of / will be resolved by the current work being done in https://github.com/cypress-io/cypress/issues/7306.
