### ISSUE TITLE
Cypress fail event not able to make http post from Docker

### ISSUE THREAD

**Issue by janhjordie** [cypress-io/cypress#3233]
### Current behavior:

It fails using http post in cypress fail event

### Desired behavior:
I want to capture the `fail` event, and when that happens I want to post a message to my API endpoint with the result.

It works just fine when using the UI/Cypress open. But when run in a docker, the http post is never fired. 

If the http post happens, the test post will be visible on this endpoint https://ecsact-functions.azurewebsites.net/api/GetTestPosts

It's also the same issue when running the `cypress run`. Nothing is fired to the endpoint.

### Steps to reproduce: (app code and test code)

My small test 

```js
/// <reference types="Cypress" />
Cypress.on('fail', (error, runnable) => {
  console.log("fail");
  cy.log("fail");

  fetch('https://ecsact-functions.azurewebsites.net/api/TestPost', {
      method: 'post',
      body: "Fail #cypress"
    })
    .then(function (response) {
      return response.json();
    })
    .then(function (data) {
      console.log(data);
    });
});

describe('My First Test should fail', function () {
  it('Does not do much!', function () {
    expect(true).to.equal(false)
  })
})
```

### Versions
I'm using 3.1.4 and MacOS latest

**Comment by jennifer-shehane** [comment]
Do you have anything within your `cypress.json` file? 

If you want to replicate the environment during `cypress run` locally, as close as you can, run with `cypress open`, then select Electron from the dropdown. Open your dev tools and look for errors there.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
