### ISSUE TITLE
cypress shows "waiting for page to load' forever when alert popped up

### ISSUE THREAD

**Issue by maksimkarpov** [cypress-io/cypress#3234]
### Current behavior:
Hi, I have an issue when clicking on a link that is popping up an alert, like <a href='tel: 437293223823823'> - after it cypress shows 'waiting for page to load' forever and nothing else happening. It looks like it starts waiting when a link is clicked and if page is not reloading then this is what happens. 
When not run with cypress the link just pops up an alert and not trying to load anything

### Desired behavior:

When the page is not to be reloaded - don't wait for it to reload.

**Comment by jennifer-shehane** [comment]
Hey @maksimkarpov, did this address your issue? I'd like to close this issue if so.

**Comment by maksimkarpov** [comment]
Hi Jennifer, yes, please close, thanks!
