### ISSUE TITLE
arrow keys to select specs in desktop-gui

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3237]
it would be nice to select specs with arrow keys in this view:

![image](https://user-images.githubusercontent.com/14625260/51854318-8596d800-22f8-11e9-8d69-b9490a4852fb.png)

if I'm typing in the search box, and hit `arrow down`, I would like it to highlight the first spec

**Comment by jennifer-shehane** [comment]
The code for this view is here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/src/specs/specs-list.jsx

Please see our contributing guide: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/README.md

And write tests for this view using Cypress! https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/specs_list_spec.coffee

**Comment by grabartley** [comment]
I will take a look into this

**Comment by hiramzamorano** [comment]
@grabartley did you finish it? i would like to work in this feature too if you've not finished it :)

**Comment by grabartley** [comment]
@hiramzamorano I did not get to finish it, please go ahead :)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
