### ISSUE TITLE
Extraneous messages printed in console during cypress run

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3242]
### Current behavior:

```
GVA encoder info: AMD performance mode : 2 
GVA encoder info: deleteSCDMetalContext : texture cache hits: 0, misses: 0
```

These messages aren't useful to me and are just noise.

### Versions

Cypress 3.1.4
macOS 10.13.6

I have verified that the messages are not printed in Windows.

**Comment by jennifer-shehane** [comment]
Is this during `cypress open` / `cypress run`? Any particular browser running?

**Comment by fr0** [comment]
This is with `cypress run` using electron. It also happens with chrome.

**Comment by fr0** [comment]
It also happens in `cypress open`. So basically, every situation (run/open, electron/chrome).
