### ISSUE TITLE
The UI is "jumpy"

### ISSUE THREAD

**Issue by MikeHopley** [cypress-io/cypress#3249]
I love Cypress, but the UI is extremely frustrating because it jumps all over the place.

Even with auto-scrolling disabled, mousing over the left-hand panel (test command history) frequently  makes the list jump to a different point, so it's difficult or impossible to select what you want. Sometimes you can position the mouse so the left panel continuously jumps between two spots, even though the mouse isn't moving.

**[EDIT]** It seems to stop jumping once you've pinned a command.

Apart from this one issue, the UI design in Cypress is excellent though!

**Comment by jennifer-shehane** [comment]
>mousing over the left-hand panel (test command history) frequently makes the list jump to a different point

I think you're referring to the 'time travel' [feature when hovering over the lefthand side commands](https://on.cypress.io/test-runner#Hovering-on-Commands), but let me know if I have misunderstood. When hovering over each command on the lefthand side, your application is reverted back to the exact state it was in when the command ran. Clicking on the command "pins" it in that state and disables the hovering effect for other commands.

>Sometimes you can position the mouse so the left panel continuously jumps between two spots, even though the mouse isn't moving.

For some commands, when hovered over, it previews the commands 'before' and 'after' state. For example, when hovering over a `.click()` command, the application under test reverts back to the state it was before the click and after the click for better debugging.

Most of our users have expressed the time travel on hover as being a very useful feature for them. What would make this experience better for you?

**Comment by niffin** [comment]
I noticed the same thing today when my chrome version updated to 72. It looks like the left hand panel isn't scrollable anymore and causes the entire page to jump around.

if i set a height on `.reporter-wrap .reporter .container` it seems to fix the issue.

**Comment by MikeHopley** [comment]
Thanks for the response!

> I think you're referring to the 'time travel' feature

Actually this is what happens when I'm trying to use the time travel feature. Time travel is utterly brilliant and literally made my jaw drop the first time I saw it, which is why I'm sad about the broken UI.

I think it might help if I make a video so you can see what's happening. I'll try to do that tomorrow.

**Comment by MikeHopley** [comment]
Thanks Brian, I installed 3.1.5 and it's fixed. 👍

I've been seeing that bug for a while now, presumably because I'm running Cypress on Canary.

**Comment by vesper8** [comment]
> Even with auto-scrolling disabled

How do you disable auto-scrolling please?

**Comment by jennifer-shehane** [comment]
@vesper8 There's a button in the header of the Test Runner to disable auto-scrolling. 

<img width="721" alt="Screen Shot 2019-04-03 at 3 11 35 AM copy" src="https://user-images.githubusercontent.com/1271364/55434844-854bdf00-55be-11e9-861d-6f500bbf1b55.png">

**Comment by vesper8** [comment]
thanks @jennifer-shehane 

Is there a way to set it to always disabled through configuration? Especially when running the unattended 'cypress run'

**Comment by vesper8** [comment]
in any case I'm sorry to say but that button doesn't actually fix the auto-scrolling, whether it is enabled or disabled, when running the tests manually I mean, the jumpy auto-scrolling happens regardless... really wish there was a way to force the viewport to stay at the very top. Perhaps as a workaround, if there was a way to attach a cy.scrollTo('topLeft'); to every click() / type() event

**Comment by vesper8** [comment]
if anyone else is running into this issue.. I made it go away with this hack (depends on jQuery):

```
    if (window.Cypress) {
      $(window).scroll(() => {
        $(window).scrollTop(0);
      });
    }
```

**Comment by jennifer-shehane** [comment]
Oh, right, that only disables the scrolling of the Cypress Command Log on the left - not the auto scroll behavior when testing your application under test. 

There is an issue open regarding the ability to change the scroll behavior of testing here: https://github.com/cypress-io/cypress/issues/871

**Comment by jennifer-shehane** [comment]
In Cypress 6.1.0, there’s a new `scrollBehavior` configuration option that controls the viewport position when an element is scrolled prior to action commands. Possible values are `'top'`, `'bottom'`, `'center'`, `'nearest'`, and `false`, with `'top'` being the default. `scrollBehavior: false` disables scrolling altogether. `scrollBehavior` can be specified in [global configuration](https://on.cypress.io/configuration#Actionability), [test configuration](https://on.cypress.io/writing-and-organizing-tests#Test-Configuration) or individual [action commands](https://on.cypress.io/interacting-with-elements) via options.
