### ISSUE TITLE
Add tests for Reporter UI

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#3257]
To mitigate regressions related to its responsive design and scrolling, like [this one caused by a new version](https://github.com/cypress-io/cypress/issues/3253). 

The tests could be similar to [this one](https://github.com/cypress-io/cypress/pull/3255/files).

**Comment by jennifer-shehane** [comment]
We have tests in Reporter UI now in Cypress https://github.com/cypress-io/cypress/blob/develop/packages/reporter/cypress/integration
