### ISSUE TITLE
Error when scaffolding new project

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#326]
When Cypress scaffolds the `support` directory for a new project, it causes an error when running the tests. 

```
Error: Cannot find module '/Users/chrisbreiding/Desktop/_foo/cypress/support/index.js' from '/Users/chrisbreiding/Desktop/_foo'
```

A work around for the time being is to close the project (go back to the projects list) and then return to the project and run tests. Once the scaffolded files are in place, the issue ceases to exist.

**Comment by brian-mann** [comment]
Fixed in [`0.18.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0181-12112016).

**Comment by ghengeveld** [comment]
I think you fixed this by making sure support/index.js exists? I'm getting the same error because I'm generating the sources and I don't have a support file (no need for it yet). I would expect the file to be optional. Doesn't make sense to create an empty file just to work around it.

**Comment by chrisbreiding** [comment]
You can set `supportFile: false` in your `cypress.json` and Cypress won't try to load that file.
