### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by bojaniv** [cypress-io/cypress#3261]

**Comment by jennifer-shehane** [comment]
Closing as not enough information. Please comment with more information about the issue you are having following the issue template if you are having a problem.

**Comment by DynamiteTom** [comment]
Can't start server

EPERM: operation not permitted, unlink 'C:\Users\DynamiteTom\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache\data_1'

**Comment by DynamiteTom** [comment]
When I run any test within the Playground 
the circular Opening Chrome 73 rotates but eventually comes up with the message 

 Can't start server

EPERM: operation not permitted, unlink 'C:\Users\DynamiteTom\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache\data_1'

**Comment by DynamiteTom** [comment]
This seems to be for all tests

**Comment by kruthitechjini** [comment]
![image](https://user-images.githubusercontent.com/47332688/57316027-82d72a80-7112-11e9-896a-c0e54b4ba330.png)

for fresh installation also i am facing error

**Comment by jennifer-shehane** [comment]
@kruthitechjini Please see this issue: https://github.com/cypress-io/cypress/issues/1099

I am locking conversation on this issue since it was initially an empty thread. Please search existing issues or open a new issue if you are encountering a 'Can't start server' error.
