### ISSUE TITLE
Possibly wrong match on topOrParentLocationOrFramesRe regexp

### ISSUE THREAD

**Issue by leandro-serafim** [cypress-io/cypress#3267]
### Current behavior:

Currently, having `modifyObstructiveCode` enabled didn't get a specific framebust situation:

```js
top.location!=self.location&&(top.location.href=self.location.href)
``` 

After researching over the code base I could identify the regexp used on `topOrParentLocationOrFramesRe` possibly isn't getting correctly the first group match, as you can see: (https://regex101.com/r/o0ykmR/1)

### Desired behavior:

I'd like to be able to block the given framebust.

### Steps to reproduce: (app code and test code)

The regexp on `topOrParentLocationOrFramesRe` gets an extra character as you see [here](https://regex101.com/r/o0ykmR/1?fbclid=IwAR22dyGMK9og5b3Fs37RJ4BEGUho4JOk4A4D3QDJv68_8REFGzLkv78cFF0)

Possibly the easiest fix I'd suggest could be:
https://regex101.com/r/Ophqrr/2

### Versions

Cypress: v3.1.5
Windows 11
Chrome: 71.x

**Comment by jennifer-shehane** [comment]
Thanks for the thorough investigation of the issue. Gotta <3 Regex. We'll have to update the regex, write a test to ensure if fixes this issue and ensure no other framebusting tests fail.
