### ISSUE TITLE
cy.wrap(ele) automatically scrolls to the position of the element

### ISSUE THREAD

**Issue by zquancai** [cypress-io/cypress#3274]
### Current behavior:

an element called ele is in a scrollable div container, if I use

```js
cy.wrap(ele)
```

at runtime,the div container automatically scrolls to the position of the element

### Desired behavior:

No automatic scrolling required

### Steps to reproduce: (app code and test code)

same as described above

### Versions

cypress 3.1.4
macOS 10.14
chrom 71

**Comment by jennifer-shehane** [comment]
Hey @zquancai, I believe this issue would be solved with our proposal to allow changing scroll behavior here: https://github.com/cypress-io/cypress/issues/871 Closing, please comment if this does not cover what you were looking for.

**Comment by jennifer-shehane** [comment]
In Cypress 6.1.0, there’s a new `scrollBehavior` configuration option that controls the viewport position when an element is scrolled prior to action commands. Possible values are `'top'`, `'bottom'`, `'center'`, `'nearest'`, and `false`, with `'top'` being the default. `scrollBehavior: false` disables scrolling altogether. `scrollBehavior` can be specified in [global configuration](https://on.cypress.io/configuration#Actionability), [test configuration](https://on.cypress.io/writing-and-organizing-tests#Test-Configuration) or individual [action commands](https://on.cypress.io/interacting-with-elements) via options.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
