### ISSUE TITLE
Be more user-friendly when checking that baseUrl server is responding

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3284]
Cypress 3.1.5

Currently, we only check if the server defined in `baseUrl` is responding when we start Cypress. If the user starts their server AFTER Cypress the message is very confusing and scary - and wrong

<img width="799" alt="screen shot 2019-02-01 at 12 09 55 pm" src="https://user-images.githubusercontent.com/2212006/52141322-54354980-2623-11e9-8fe8-310a507e6851.png">

It would be nicer to (a few alternatives)

- retry the server periodically and remove the error message when the server responds
- have a Retry button to test again. If the server responds, remove the message
- at least add to the message text like "If you have started the server after Cypress, ignore this error"

**Comment by EmmanuelDemey** [comment]
I think the retry button is the most normal behaviour. As the refresh button when executing the test suite.

**Comment by must-git-good** [comment]
@jennifer-shehane 

Does this still need work? I'd love to try smoothing out that experience, if so...

**Comment by jennifer-shehane** [comment]
@must-git-good yes we would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by nhc** [comment]
@jennifer-shehane Does this still need looking at ?
