### ISSUE TITLE
Cypress stopped working after clicked "Login" of the Google

### ISSUE THREAD

**Issue by gabrielbesen26** [cypress-io/cypress#3285]
### Is this a Feature or Bug? 
Bug

### Current behavior:
I was training/studyng Cypress and I used google as example to interact. After the script clicked on "Login" (in my test is described as 'Fazer login' in Portuguese), the page being blank, load the login page of google and the runner disappear/stoped working.  

![image](https://user-images.githubusercontent.com/35542922/52142742-adf83c80-2640-11e9-9c4c-854b38419048.png)

![image](https://user-images.githubusercontent.com/35542922/52142870-1d6e2c00-2641-11e9-8dbb-9bcdcd4680aa.png)

### Desired behavior:
After clicked on "Login", the login page being loaded inside of Cypress

### Steps to reproduce: (app code and test code)
![image](https://user-images.githubusercontent.com/35542922/52142929-51495180-2641-11e9-85a6-6afb15e51ffb.png)

### Versions
Cypress 3.1.5
Windows 10
Chrome71

**Comment by jennifer-shehane** [comment]
Hey @gabrielbesen26, we don't recommend testing 3rd party applications that are not under your control for a lot of reasons. Please read our full recommendation here: https://on.cypress.io/best-practices#Visiting-external-sites

Please let me know if I am wrong about this being 3rd party - and you are indeed testing the login for Google. 

Closing.

**Comment by gabrielbesen26** [comment]
> 
> 
> Hey @gabrielbesen26, we don't recommend testing 3rd party applications that are not under your control for a lot of reasons. Please read our full recommendation here: https://on.cypress.io/best-practices#Visiting-external-sites
> 
> Please let me know if I am wrong about this being 3rd party - and you are indeed testing the login for Google.
> 
> Closing.

Understood @jennifer-shehane 
Sorry about that! Have a great day
