### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [cypress-io/cypress#3286]
https://ci.appveyor.com/project/cypress-io/cypress/builds/22048921

**Comment by jennifer-shehane** [comment]
@DanielRuf Could you please fill out the Issue Template and describe what the issue if you are having with Cypress? This best helps us focus our time on improving Cypress. 😊 Please answer all of the questions below.

```
### Is this a Feature or Bug?

<!-- Is this a question? Don't open an issue. Ask in our chat https://gitter.im/cypress-io/cypress-->

### Current behavior:

<!-- images, stack traces, etc -->

### Desired behavior:

<!-- A clear concise description of what you want to happen -->

### Steps to reproduce: (app code and test code)

<!-- Issues without reproducible steps will get closed. You can fork https://github.com/cypress-io/cypress-test-tiny repo, set up a failing test, then tell us the repo/branch to try. -->

### Versions

<!-- Cypress, operating system, browser -->
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by DanielRuf** [comment]
Hi,

sorry for the late reply.
Well, you can clearly see and reproduce this.
See the CI status on the commits ;-)

![Bildschirmfoto 2019-04-25 um 11 15 34](https://user-images.githubusercontent.com/827205/56724539-813d5800-674b-11e9-8203-ea18859cf066.png)
