### ISSUE TITLE
cy.confirm() behavior

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#33]
1. I'd like the ability to conditionally accept / cancel a `cy.confirm()` command.
2. `cy.confirm` accept / cancel should log out in the commands UI.
3. After all tests are run, the default browser behavior should be restored (so that confirmation appears).

**Comment by cristopher-rodrigues** [comment]
@jennifer-mann https://github.com/cypress-io/cypress/issues/376  it's the same?

**Comment by brian-mann** [comment]
This is now done. Closing in favor of: https://github.com/cypress-io/cypress/issues/621
