### ISSUE TITLE
cy.exec() fails when trying to access a docker container using shell in Windows 

### ISSUE THREAD

**Issue by abhilashshettigar** [cypress-io/cypress#3311]
### Current behavior:

`cy.exec()` fails when trying to access a docker container using shell 

![cypress error](https://user-images.githubusercontent.com/32007548/52203913-9d420380-2898-11e9-9624-f34d6b3829df.png)

### Complete error stack:-

```
 Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stdout:
> docker exec -i -t api_database_1 mysql -uroot -pDemo123
Stderr:
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!  connect:db: `docker exec -i...
```

### Steps to reproduce: (app code and test code)

1.)`"connect:db":"docker exec -i -t api_database_1 mysql -uroot -pDemo123"` // Script written in `package.json` 
2.) `cy.exec('npm run connect:db')` // inside Spec file 

### Versions

- Operating System:- Windows 10 pro
- Cypress Version:- 3.1.5
- Docker version 18.09.1

**Comment by jennifer-shehane** [comment]
Related issue: https://github.com/docker/for-win/issues/1588

Did you try prefixing the command with `winpty` as specified in the error message? What happens then?

**Comment by abhilashshettigar** [comment]
Yup, While trying it shows `winpty is not recognized as an internal or external command `

**Comment by abhilashshettigar** [comment]
@jennifer-shehane I  have Set the Path for winpty in Environment variable in my pc 
winpty.exe Location :- C:\Program Files\Git\usr\bin\
 and command which @jennifer-shehane suggested works fine in my CMD
![cypressconnectwithwinpty](https://user-images.githubusercontent.com/32007548/52337605-1a52b180-2a2e-11e9-9564-e716fe6df496.png)

But in Cypress while running same command

Error Stack:-
![cypressconnectwithwinpty](https://user-images.githubusercontent.com/32007548/52338408-5a1a9880-2a30-11e9-877e-571af52dfa8e.png)
