### ISSUE TITLE
document.write does nothing on TravisCI in one particular example

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3314]
## Bug

Cypress 3.1.5 on TravisCI

The example https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/blogs__codepen-demo passes locally and on CircleCI but always times out on TravisCI like in https://travis-ci.org/cypress-io/cypress-example-recipes/jobs/488553504

- https://dashboard.cypress.io/#/projects/6p53jw/runs/31718/specs

<img width="1268" alt="screen shot 2019-02-04 at 10 44 14 am" src="https://user-images.githubusercontent.com/2212006/52219511-c8adf980-286a-11e9-8ec0-298a8da6c20f.png">

<img width="1192" alt="screen shot 2019-02-04 at 10 44 54 am" src="https://user-images.githubusercontent.com/2212006/52219521-cc418080-286a-11e9-8983-5752a97cf335.png">

## Details

See more details in https://github.com/cypress-io/cypress-example-recipes/issues/217

## Interesting: 

The same recipe was always failing on Travis and on Circle in Cypress 3.1.4 but now is passing on Circle with Cypress 3.1.5

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
