### ISSUE TITLE
cy.wait() never times out when passed undefined

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#332]
If `cy.wait()` is passed an argument that evaluates to `undefined`, the `wait` command appears to run forever. It never times out or throws an error. 

The command should either time out, or throw an error stating the arguments that are acceptable to pass to `cy.wait()`.

**Example Test Code**
```
it('never times out', function() {
  cy.wait(undefined)
})
```

**Comment by brian-mann** [comment]
Fixed in [`0.19.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0192-04162017).
