### ISSUE TITLE
Terminating cypress on console using ctrl+c does not close browser

### ISSUE THREAD

**Issue by bits-of-static** [cypress-io/cypress#3330]
Cypress v3.1.5
MINGW64 console
Google Chrome, running inside Sandboxie
Windows 10

**Comment by jennifer-shehane** [comment]
Hey @bits-of-static, we've never encountered this error before. Could you explain the exact steps to get to this situation? We won't be able to look into the error without being able to reproduce it.

**Comment by bits-of-static** [comment]
Yes, I will let you know as soon as I find way to reliably reproduce this issue. Yesterday, I was left with high cpu consumption of astray chrome processes, even though all chrome windows were closed.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by OscarGodson** [comment]
I have this issue on Windows 11 too. Im completely unable to close the cypress Windows after using --watch command. Im using nx so nx e2e appname --watch opens fine but then there's no way to terminate the windows. I cant even find Cypress in the task manager. Clicking the X in the menu bar, right click on the Cypress icon in my toolbar and close windows or ctrl+c in the terminal etc none work.

Made a ticket here: https://github.com/cypress-io/cypress/issues/30843
