### ISSUE TITLE
Ability to return values fetched using children() method

### ISSUE THREAD

**Issue by KartikaRajendran** [cypress-io/cypress#3332]
### Current behavior:

I am currently trying to write an utility function that fetches data in a page and returns it using the below code.

The rows of data returned within `children().each(()=>{})`  is correct and is printed properly. But I am unable to fetch the values of `arr_rows` outside of the `each` loop. I am planning to use this `fn` in tests that requires fetching and comparing a table of data.

I have attached a screenshot of my output below.

![screen shot 2019-02-05 at 9 53 40 am](https://user-images.githubusercontent.com/35237894/52281410-1d657900-292c-11e9-94ff-edc5a99e523e.png)

### Desired behavior:

To be able to access the value populated into `arr_rows` within file scope

Current code I am using to fetch data from web page

```js
let arr_rows = [];

function retreive_data_from_UI(){
    cy.get(constants.cssCustomerWoListViewTable).children().each(function($rows, ind){
            arr_rows[ind] = $rows.text();
            cy.log(ind);
            cy.log(arr_rows[ind]); // Prints proper output
  }).then((arr_rows) => {
            cy.wait(1000);
           for(var i = 0; i < 5; i++){
                cy.log(arr_rows[i]); // does not print expected output
           }
  });
}
```

**Comment by Lakitna** [comment]
`each` [always passes on its input](https://docs.cypress.io/api/commands/each.html#Yields), it never mutates the values so when you enter the `then` block you get the elements passed by `children`.

I see 2 ways of solving this:
1. Create a custom command to grab the text from any elements and pass it on to the next item in the chain. This is the hard but reusable way. In fact it's too complex to post here. I am planning on sharing my custom commands (including `text`) at some point though.
2. Use an `each` loop inside a `then` block. This is the simple, but it's not reusable. See solution below.

```javascript
function retreive_data_from_UI() {
    cy.get(constants.cssCustomerWoListViewTable)
        .children()
        .then(function(rows) {
            let arrRows = [];

            // Using JQueries `.each`
            $(rows).each((i, row) => {
                // Add the text of each row to the end of arrRows
                arrRows.push(row.text());
            });

            // Pass arrRows on to the next item in the chain
            return arrRows;
        })
        .then((arr_rows) => {
           for(var i = 0; i < 5; i++){
                cy.log(arr_rows[i]); // The correct values should be logged here now
           }
        });
}
```

A few more things:
- [Don't use arbitrary waits](https://docs.cypress.io/api/commands/wait.html#Time)
- A great way to get help with your test code is by asking questions like this in [the Gitter chat](https://gitter.im/cypress-io/cypress). It's faster and keeps the issue log clean.

**Comment by KartikaRajendran** [comment]
I tried the above method 2 but had issues while accessing the elements/rows passed by children() within the then(). But I was able to resolve it by creating and returning a Promise like below.

```function retreive_data_from_UI(){
  var result = [];
  return new Promise(function(resolve){
    cy.get(constants.cssCustomerWoListViewTable).children().each(($rows, ind) => {
      result.push($rows.text());
    }).then(function(){
      this.result = result;
      for(var i = 0; i < 5; i++){
        cy.log(this.result[i])
      }
      resolve(this.result)
    });
  });
}
