### ISSUE TITLE
Question: Read XML File and assign the contents to cy.request(body)

### ISSUE THREAD

**Issue by usermur** [cypress-io/cypress#3335]
**Question: Read XML File and assign the contents to `cy.request(body)`**

For one of my web service testing, I need to read an xml file and assign the contents of the same to `cy.request` body. Or assign the contents of the xml directly to the `cy.request` body.

How can I achieve this?

I tried the below method and was not able to successfully pass the XML to the body.

Please let me know.

eg:
```js
cy.readFile('Desktop/Testing/W1.xml')
  .then(text1 => {
    console.log(text1);
    cy.request({	
      url: 'my URL',
      method: 'POST',
      body: {text1},
      headers: { 
        'Authorization':'Basic ........',
        'content-type': 'application/......-v1.0+xml', 		 
        'Accept':'application/...v1.0+json,application/....-v1.0+json'
      }
    })
    .then((response) => {
      assert.equal(response.status, 200, "status was 200");
      cy.log("Response Body",response.body);
        console.log("Response Body",response.body);
      })
    })
```

**Comment by jennifer-shehane** [comment]
What is the request body displaying as with the code above?

**Comment by jennifer-shehane** [comment]
@usermur Checking in again, can you answer the question above? ^

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by Neeraj909** [comment]
addOneKeyCashToUser(tuidi: string) {
    const data = '<?xml version="1.0" encoding="UTF-8"?> <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">     <soap:Body>         <MT_ServiceOrderInitiaionandMgmt xmlns:prx="***"                                     xmlns="***">             <VKONTO>***</VKONTO>              <NAME>***</NAME>              <PORTION>***</PORTION>               <AKLASSE/>             <DATUM>***</DATUM>              <Contact>                 <RELTYP/>                 <NAME>***</NAME>                 <TEL_NUMBER>***</TEL_NUMBER>                 <PHTYPE>***</PHTYPE>                 <SMTP_ADDR>***</SMTP_ADDR>             </Contact>             <LifeSupportIndicator/>             <QMNUM>***</QMNUM>              <QMART>***</QMART>             <MNCOD>***</MNCOD>              <QMTXT>***</QMTXT>             <NOTST>***</NOTST>             <ServiceAddress>                 <STREET>***</STREET>                 <CITY1>***</CITY1>                 <REGIO>***</REGIO>                 <LOCATION>***</LOCATION>                 <POST_CODE1>***</POST_CODE1>                 <HAUS_NUM2/>             </ServiceAddress>             <ABLEINH>***</ABLEINH>             <CO_ASTTX>***</CO_ASTTX>              <STRMN/>             <STRUR>***</STRUR>              <LTRMN/>             <LTRUR>***</LTRUR>              <ERDAT>***</ERDAT>              <MZEIT>***</MZEIT>              <ERNAM>***</ERNAM>             <AEDAT/>             <AEZEIT>***</AEZEIT>             <AENAM/>             <PPSID>***</PPSID>             <ExternalReference>                 <ID></ID>                 <SYSNAME>***</SYSNAME>                 <TYPE>***</TYPE>             </ExternalReference>             <REFNUM/>             <PRIOK/>              <LONT_TXT>***</LONT_TXT>              <PREMS>***</PREMS>              <Meters>                                 <TPLNR>***</TPLNR>                 <VBSARTTEXT>***</VBSARTTEXT>                 <TERMSCHL/>                 <DLNOT>***</DLNOT>                 <STORT>***</STORT>                 <KTEXT>***</KTEXT>                 <EINBDAT>***</EINBDAT>                 <ISPRIM>***</ISPRIM>                 <SERNR>***</SERNR>                  <MET_SERNR></MET_SERNR>                 <HERST>***</HERST>                 <TYPBZ/>                 <PREISKLA>***</PREISKLA>                 <EQKTX>***</EQKTX>                 <DSTAT>***</DSTAT>                 <MEINS>***</MEINS>                 <STANZVORE>***</STANZVORE>                 <ISTABLART>***</ISTABLART>                 <V_ZWSTAND></V_ZWSTAND>                  <E_ZWSTANDO>***</E_ZWSTANDO>                  <E_ZWSTANDU>***</E_ZWSTANDU>                  <E_VERBERW>***</E_VERBERW>                  <ADAT>***</ADAT>                 <ATIM>***</ATIM>                 <MTU_TPLNR/>                 <MTUSN>***</MTUSN> >                 <MTU_EQKTX/>                 <MTU_EINBDAT>***11</MTU_EINBDAT>                 <MTU_SERNR></MTU_SERNR>                 <PORT>***</PORT>             </Meters>         </MT_ServiceOrderInitiaionandMgmt>     </soap:Body> </soap:Envelope>';
    const filename = 'cypress/reports/data.xml';
    cy.readFile(filename)
        .then(text1 => {
          cy.log(text1);
          cy.request({
            method: 'POST',
            url: 'url',
            form: true,
            body: data,
            headers: {
              'Content-Type': 'application/xml',
              'accept':'application/xml'
            },
          }).then(response => {
            cy.log(response.body);
          });
        });

**Comment by Neeraj909** [comment]
this is 
what i am using but getiting 415 error
