### ISSUE TITLE
Not finding an element in iframe

### ISSUE THREAD

**Issue by minams2** [cypress-io/cypress#3336]
Not able to find elements within iframe

### Current behavior:
It waits and fails

```js
cy.get('.livepreviewpane__preview-url')
  .invoke('text')
  .get('iframe')
  .wait(500).then($iframe => {
      const $body = $iframe.contents().find('body');
      cy.wrap($body)
        .find('#main #article_1-0 #toc_1-0 #mntl-toc-list_1-0')
        .click();
    });
  }
```

**Comment by jennifer-shehane** [comment]
Hey @minams2, did you check this open issue regarding finding elements within an iframe? https://github.com/cypress-io/cypress/issues/136

**Comment by minams2** [comment]
i checked and tried, but it is always is clicking at the last cell in the table and typing in the last cell
 addTable() {
    cy.get('iframe').should($iframe => {
      const body = $iframe.contents().find('body');
    }).then($iframe => {
      const body = $iframe.contents().find('body');
       //cy.wrap(body.find('tr').find('td').eq(0)).type('123');
       cy.wrap(body.find('td')).eq(0).click().type('123')
       console.log(body.find('td').eq(0));
      //  .type('{uparrow}').type('{uparrow}').type('{uparrow}')
      //  .type('{uparrow}').type('{uparrow}').type('{uparrow}')
      //  .type('{uparrow}').type('{uparrow}').type('{uparrow}')
      //  .type('col1');
    });

**Comment by jennifer-shehane** [comment]
Unfortunately, since we do not currently fully support testing iframes - I suggest tracking this issue for workarounds and the full iframe support release: https://github.com/cypress-io/cypress/issues/136

**Comment by realtebo** [comment]
I want to add 2 coins for iframe testing: our cart is using Stripe Elements for handling credit card payment. 

Because of this our test suite needs to migrate to another test system becayse we ABSOLUTELY need to test some credit card variations (for SCA compliance testing) and we cannot actually enter values into credit card form because stripe is loading itself inside an iframe.

This is not an edge case I suppose

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment in order to direct comments about iframe support into one place to avoid duplication. Please comment here: https://github.com/cypress-io/cypress/issues/136
