### ISSUE TITLE
Using Cypress with create-react-app causes @types/jquery error

### ISSUE THREAD

**Issue by danawoodman** [cypress-io/cypress#3339]
I am getting the error:

```
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209
```

When trying to use Cypress with create-react-app using Typescript. With create-react-app, you can't override the `--isolatedModules` flag. I have no idea how else to get rid of this error after googling for over an hour.

This appears to be an issue with `@types/jquery` which is imported at some level by Cypress.

I've tried `exclude`ing the `node_modules` folder and a few other things but nothing has worked thus far

### Current behavior:

Throws typescript error

### Desired behavior:

Doesn't throw typescript error

### Steps to reproduce: (app code and test code)

1. Create a new create-react-app app
2. Configure it to support Typescript
3. Setup a Cypress project
4. Run your application (which previously worked before installing Cypress)

### Versions

Cypress 3.1.5

![](https://cl.ly/53f141a9ceaa/Screen%20Shot%202019-02-05%20at%207.35.00%20PM.png)

**Comment by danawoodman** [comment]
I found a workaround. If you set `skipLibCheck` to `true` in your `tsconfig.json` it seems to resolve the issue, though I will keep open as I think this should be fixed if possible without a config change.

```json
{
  "compilerOptions": {
    // other settings...
    "skipLibCheck": true,
  },
}
```

**Comment by danawoodman** [comment]
Looks like the issue is mentioned in [the Typescript page here](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json) which says to add a Typescript config file in the `cypress` directory however from what I can tell this doesn't fix the issue in a create-react-app project.

**Comment by jennifer-shehane** [comment]
This issue may resolve these types of typing problems: https://github.com/cypress-io/cypress/issues/3371

**Comment by danawoodman** [comment]
Sweet, that would be great
