### ISSUE TITLE
Cypress is often not connecting / UI is blocked due to underlying socket problems

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#334]
Ever since `0.18.0` and possibly even as early as `0.17.11` we have noticed a dramatic increase in the number of CI failures due to the remote client / browser never connecting.

When running tests in Cypress locally we are also noticing times where the UI "hangs" on a full page refresh due to the underlying socket connection either being blocked for multiple seconds, or sometimes erroring with "Socket is in a disconnected / closed state".

The root cause still has yet to be determined.

![screen shot 2016-12-09 at 1 11 17 am](https://cloud.githubusercontent.com/assets/1268976/21039579/e941187e-bdac-11e6-8944-e963c6e9c95a.png)

**Comment by mateatslc** [comment]
I'm having the same problem with my Jenkins builds for a while now.

![screen shot 2016-12-09 at 2 22 55 pm](https://cloud.githubusercontent.com/assets/590577/21050502/55a87a02-be1b-11e6-87b4-5d0af7e29e42.png)

**Comment by brian-mann** [comment]
How long is awhile now?

Can you be specific as to which version of cypress suddenly exhibited the timeouts?

**Comment by mateatslc** [comment]
Went through my CI build history and I can confirm that the issue goes back all the way to `v0.17.11` (see screenshot).
Not sure if it came "suddenly" though, don't remember act ups coming because of the version upgrade.

![screen shot 2016-12-09 at 4 50 08 pm](https://cloud.githubusercontent.com/assets/590577/21055015/1a34f878-be30-11e6-808c-8f7a9ad114dc.png)

**Comment by brian-mann** [comment]
Okay great, this matches our own internal projects - we saw a spike in
these timeouts at this version.

If I had to guess since we introduced video recording in 0.17.11, it's
related to that. Intermittent problems like these are hard to track down
but we'll figure it out.

**Comment by mateatslc** [comment]
Not that it matters, but I remember myself blaming video recording too without any specific reason.

**Comment by mateatslc** [comment]
🙌  Testing `0.18.1` and will let you know if I see anything to add.

**Comment by brian-mann** [comment]
Thanks, yah the underlying issue is still unknown but retrying 3 times should be enough not to break CI runs. We're still looking into it.

**Comment by brian-mann** [comment]
Although we worked around this problem by retrying, it was truly caused by #572 which has been fixed and will be released next.
