### ISSUE TITLE
need of alternate command for wait and timeout

### ISSUE THREAD

**Issue by panneerselvamc** [cypress-io/cypress#3341]
### Is this a Feature or Bug?
Feature

### Current behavior:
hard coding required time

### Desired behavior:
need alternate way without hard coding

### Steps to reproduce: (app code and test code)
My First Page is Login Page and my Second Page is Dashboard Page. After Clicking Login Button in First Page Ajax calls starts happening for loading second page mean time cypress executes next command and throws error because the DOM is not loaded(Ajax calls are happening not completed), so i planned to use Wait or Timeout. My client wants not to hard code any particular amount of time.So i am Requesting you to suggest some other   way to check whether the DOM is Loaded or not. instead of using wait and Timeout.

### Versions
3.1.5

**Comment by Joelasaur** [comment]
Why not alias a route for your Ajax call and then pass it to cy.wait()?

**Comment by bahmutov** [comment]
@panneerselvamc have you read our Network guide, especially the waiting section? https://docs.cypress.io/guides/guides/network-requests.html#Waiting

**Comment by jennifer-shehane** [comment]
@panneerselvamc Closing as already a feature. Try using `cy.wait()` with specific Ajax calls instead of a set time as described here: https://on.cypress.io/network-requests#Waiting
