### ISSUE TITLE
Cypress GUI runs test in infinite loop if api call function is in index.js

### ISSUE THREAD

**Issue by nikolaJosifovic** [cypress-io/cypress#3347]
### Current behavior:
Cypress GUI looping test forever.

Can not take screenshot because tests are looping fast so I got the video.

[loopVideo.zip](https://github.com/cypress-io/cypress/files/2835899/loopVideo.zip)

My use case:

I have login api function in `index.js` file and I'm saving response into file.

In tests I use different parts of that `json` e.g `acc` token or `ref` token.

### Desired behavior:

Cypress GUI  run test once.
When user select test and run it. Test should run once.

### Steps to reproduce: (app code and test code)

Import 
```js
import * as
```

commands.js

```js
Cypress.Commands.add('apiLoginFe', (body) => {
    querystring.stringify(body)
    return cy.request({
      method: 'POST',
      url: apiUrl+signin,
      form: true,
      body
    })
    .its('body')
})
```

index.js
```js
before(() => {
  cy.loginRequest(users.admin)
        .then((resp) => {
            cy.writeFile('cypress/data/credential.json', resp.data)
  })
});
```

### Versions

I didn't try all versions but on 3+ is not working.
System OSX, Browsers all

**Comment by jennifer-shehane** [comment]
I see you have a `cy.visit()` command within the video. Does this loop run forever when you remove the `cy.visit()` command?

**Comment by nikolaJosifovic** [comment]
Here is test without `cy.visit()`

```
import users from '../../data/users/userData';


describe('Random API tests', () => {
  const admin = users.admin;
  const credetnialFilepath = 'cypress/data/credential.json';

  it('Login with admin user and save tokens to file', () => {

    cy.apiLoginFe(admin)
      .then((resp) => {
        cy.writeFile(credetnialFilepath,  resp)
      })
  })
})
```

Here is video
[withoutVisit.zip](https://github.com/cypress-io/cypress/files/2865623/withoutVisit.zip)

**Comment by jennifer-shehane** [comment]
And it doesn't rerun with just the `cy.apiLoginFe(admin)` command?

**Comment by nikolaJosifovic** [comment]
It does rerun in loop always when i have ```import * as``` in any function in my code.
I can give you access to code base if you want to check it.

**Comment by jennifer-shehane** [comment]
@nikolaJosifovic Yeah, that would be helpful if you could. You can also email support@cypress.io to send information to our support team.

**Comment by jennifer-shehane** [comment]
Hey @nikolaJosifovic Any updates on this issue?

**Comment by jasmeet17** [comment]
@jennifer-shehane my tests are running an infinite loop. Here's more info [STACKOVERFLOW_LINK](https://stackoverflow.com/questions/56139892/having-multiple-describe-in-spec-leads-to-weird-behaviour/56193026#56193026)

**Comment by jennifer-shehane** [comment]
@jasmeet17 The stackoverflow link was answered by one of our engineers. You cannot have multiple domains within a single test and you cannot have multiple top level describes in a file. If you're still experiencing this issue - provide an example in a new issue that we can run on our machines.

Unfortunately we have to close the original issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by korobochka** [comment]
@jennifer-shehane I think I've encountered the same issue.
Cypress version 3.4.1 on Windows with Typescript setup via browserify.

Reproduces if I add `import * as something from './somewhere'` to the file which is imported by the test file.
Don't even need to use `something` to trigger this. If the line is removed issue disappears.

Actual behaviour: test starts, "before all" part runs, tests starts and immediately after that interrupts and test starts again, "before all" runs again...

On each loop iteration there is an error printed and immediately cleared.
```
Uncaught TypeError: Cannot read property 'stop' of null
at $Cypress.stop (cypress_runner.js:78554)
at Object._reRun (cypress_runner.json:157679)
at Socket.rerun
```

**Comment by poponuts** [comment]
The looping issue occurred to me when I have run the cy.writeFile several times and overriding the json file. My code below:
```
cy.request(...).then(response) => {
cy.WriteFile('cypress/fixtures/tokens.json', response.body);
}
```

I removed tokens.json and still an issue. However, when I created a new json file called "tokensx.json" and changed the path from `cy.WriteFile`, I no longer have that issue. 

That is so weird.

**Comment by nodi1995** [comment]
I had the same problem, and in the end, I realized that this is not a bug. You need to set watchForFileChanges to false, because every time you overwrite your JSON file, cypress is listening to changes and restart the test. I am wondering now, is there any way to config ignore list related to changes?

**Comment by jennifer-shehane** [comment]
Yes, this may be the cause. You'll need to turn set `watchForFileChanges` to `false` as a workaround. More info on file watching here. https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Configuration

I actually am not able to reproduce it with the above code alone though. I tried this code and it works fine. Am I missing another piece.

```js
it('cy.request() - make an XHR request', () => {
  cy.visit('https://example.cypress.io/commands/network-requests')

  cy.request('https://jsonplaceholder.cypress.io/comments')
    .then((response) => {
      cy.writeFile('cypress/fixtures/example.json', response.body)
    })
})
```

**Comment by royarunendu** [comment]
I am also facing the same issue , however the same piece of code running smoothly in other test but in another test file it goes into loop.

**Comment by elado** [comment]
@jennifer-shehane if you add an `import`, and assuming there's an initial file in the fixtures folder, it'll continuously re-run.

```js
import example from '../fixtures/example.json';

it('cy.request() - make an XHR request', () => {
  cy.visit('https://example.cypress.io/commands/network-requests')

  cy.request('https://jsonplaceholder.cypress.io/comments')
    .then((response) => {
      cy.writeFile('cypress/fixtures/example.json', response.body)
    })
})
```

**Comment by KrupalVaghasiya** [comment]
> @elado you are right. Please let me know how to solve it because I am using data from the fixture file so it is necessary to import the file.
> 
> ```js
> import example from '../fixtures/example.json';
> ```

**Comment by thadk** [comment]
I moved the file I was writing into a subfolder of the file with the import, which worked for my case, and that avoided the infinite loop! Thanks for delineating this: https://github.com/cypress-io/cypress/issues/3347#issuecomment-713851803

**Comment by thadk** [comment]
I moved the file I was writing into another parent folder of the folder with the file with the import, which worked for my case, and that avoided the infinite loop! Thanks for delineating this: #3347 (comment)

**Comment by Srinivasan-ram** [comment]
watchForFileChanges:false worked for me .Thanks
