### ISSUE TITLE
Test runs infinitely with combination of async error, 'fail' event, and done callback

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#3349]
### Current behavior:

Test will hang if there's an async error, use of the `fail` event to catch the failing test, and a `done` callback. Since the command resolves before the error is thrown, the `fail` event is not fired and the `done` never gets invoked.

This is primarily an internal issue since we use the `fail` event to test Cypress. can be seen in the [failing driver test](https://circleci.com/gh/cypress-io/cypress/57375#tests/containers/1) in [this PR](https://github.com/cypress-io/cypress/pull/3244). That test is using new and changed aspects of ~4.0~ 5.0, but it can reproduced in the current version of Cypress using the steps below.

### Desired behavior:

The `fail` event should be fired, which will allow the test to finish.

### Steps to reproduce: (app code and test code)

```html
// visit_error.html
<!DOCTYPE html>
<html>
  <script>
    setTimeout(() => {
      foo.bar()
    })
  </script>
</body>
</html>
```

```js
// spec
it('tests visit error', (done) => {
  cy.on('fail', () => {
    done()
  })

  cy.visit('/visit_error.html')
})
```

### Versions

Cypress 3.1.5
Chrome 71
MacOS 10.14.2

**Comment by jennifer-shehane** [comment]
Is there any reason this is slated for 4.0 if it is reproducible with current version? Would this create a breaking change?

**Comment by chrisbreiding** [comment]
Good point. Changed it to `3.1.6`.

**Comment by Bkucera** [comment]
@chrisbreiding I think there are two separate issues here:

1) after any cypress command, the mocha timeout is cleared, so a test will never timeout. This test will hang forever:

```js
it('should timeout', (done) => {
cy.visit('/')
}))
```

2) cy.on('fail') is not getting called for some reason, unrelated

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
