### ISSUE TITLE
[Sticky] Do you use Cypress?

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#335]
Do you use Cypress? Let our community know!

1. Company/Project name & link
2. Company/Project description
3. Company/Project logo

**Comment by paulfalgout** [comment]
https://roundingwell.com

![rwell](https://cloud.githubusercontent.com/assets/2028470/21170729/7d83c818-c20a-11e6-92e9-76b7660f3f7a.png)
---

> Medical organizations rely on RoundingWell to power care management workflows. Picking up where EMRs stop, care teams use RoundingWell to track their populations, coordinate care, and engage patients.

**Comment by jhanink** [comment]
http://www.presencelearning.com

**Comment by jhanink** [comment]
![presence learning](http://www.presencelearning.com/)

**Comment by rchovatiya88** [comment]
i'm excited to learn more about cypress. Currently, i'm using nightwatch js for E2E automation testing framework. i've used protractor and seleniumwebdriver with java. Being focused on javascript and node.js lately, i'm very curious to try something new that doesn't use selenium driver.. Just signed up for early access 👍

**Comment by pdougall1** [comment]
Density Analysis
http://www.densityanalysis.com/

On the way


![Density Logo](http://www.densityanalysis.com//static/density-logo.png)

**Comment by Greta** [comment]
Vitals
http://www.vitals.com/

We provide tools and services that help consumers weigh their options and make the best decision with confidence. Search for high-quality doctors and care facilities, compare costs for procedures and read patient ratings and reviews.

![Vitals Logo](http://mdxvitals-res.cloudinary.com/image/upload/q_auto/f_auto/w_auto/v1496163187/vitals/vitals-purple-logo_2x.png)

**Comment by jennifer-shehane** [comment]
Closing. We've since been collecting Cypress users through other means.
