### ISSUE TITLE
Chrome not shut down cleanly after plugin error

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3352]
### Current behavior:

Errors in plugins that result in Chrome being closed also result in the browser not being shutdown cleanly.

### Desired behavior:

If an error in a plugin results in the browser being closed, cypress should close it in a clean way.

### Steps to reproduce: (app code and test code)

1. Use the [TypeScript with WebPack](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/preprocessors__typescript-webpack) example from the example recipes
2. Start `cypress open` and select a spec file
3. Create a TypeScript compiler error in the spec file that results in cypress closing Chrome and showing the "Error running plugin" message.
4. Fix the spec and click "Try Again".
5. See screenshot.

![restore](https://user-images.githubusercontent.com/435418/52374602-9b5c7980-2a2b-11e9-9e2e-9659e5db2980.png)

### Versions

3.1.5, Windows 10

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
