### ISSUE TITLE
Settings / Configuration has weird outline

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3357]
Cypress 3.1.5

- `npx cypress open`
- click on "Settings"
First problem - since there is "Configuration" only - why is it collapsed by default?

- click "Configuration"
There is a blue outline which cuts into the help link and just looks weird.

<img width="1048" alt="screen shot 2019-02-06 at 9 25 39 pm" src="https://user-images.githubusercontent.com/2212006/52386992-6ca7c880-2a56-11e9-94d7-9da7fc6c90cc.png">

**Comment by jennifer-shehane** [comment]
"Settings" React component can be found here: https://github.com/cypress-io/cypress/blob/renovate/develop/packages/desktop-gui/src/settings/settings.jsx

**Comment by King-Kyle** [comment]
Hi there! Can I give this a go?

**Comment by bahmutov** [comment]
Sure!
