### ISSUE TITLE
`watchForFileChanges` not respected when watching the support file

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#336]
When `watchForFileChanges` is disabled in `cypress.json` we should not watch the support file.

Currently this config setting is not taken into account.

**Comment by brian-mann** [comment]
Fixed in [`0.18.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0181-12112016).

**Comment by vineetkumar1511** [comment]
cypress watch support file but do not serve latest support file on browser.
