### ISSUE TITLE
cy.route() onRequest callbacks do not execute cy commands

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#3370]
### Current behavior:

I'm stubbing a route and would like to execute some cy commands with in the `cy.route` `options.onRequest` callback function.

```js
it('Another look at route response callbacks', function() {
    auth.startSession(config.executionMode.e2e).then((token) => {           
        const baseUrl = useCI ? config.environment.CI.url : config.environment.LOCAL.url;
        const authUrl = `${baseUrl}/authenticate/cosi?signontoken=${token}`;

        cy.fixture('_landingPage.json').then((contents) => {
            const pdp1 = contents[3];

            const onRequest = () => {
                console.log(`console.log onRequest`); // logs as expected
                cy.log(`cy.log onRequest`); // *** appears to have no effect ***
            }

            cy.server();
            cy.route({
                'method': pdp1.method,
                'url': pdp1.url,
                'onRequest': onRequest,
                'response': pdp1.body
            }).as(pdp1.url);

            cy.log('hello world'); // logs as expected
            cy.visit(authUrl);
        });
    });
}
```

![image](https://user-images.githubusercontent.com/33003441/52421696-37cd5d00-2aba-11e9-8b31-01dfd24f21f2.png)

* The `cy.route` works fine and stubs the response.
* The `onRequest` callback is getting called as evidenced by the `console.log()` that works as expected.
* However the `cy.log()` (or other cy commands I put w/in the `onRequest` or `onResponse`) call backs silently do nothing.

### Desired behavior:

* either execute the cy commands or give an error explaining why they don't work

### Steps to reproduce: (app code and test code)

See code above. 

### Versions
* cypress: 3.1.4
* os: Windows 7
* chrome: 72

**Comment by carloscheddar** [comment]
In my case adding cy commands inside those callbacks causes requests to hang. 
### Code
    cy.route({
      url: `/v2/initiatives/${initiativeId}/exports`,
      method: 'GET',
      response: exportsData,
      onRequest: () => {
        cy.get('#active-view ul li')
          .should('have.length', 4)
          .contains('button', 'Pending');
      },
      onResponse: () => {
        cy.get('#active-view ul li')
          .should('have.length', 4)
          .contains('button', 'Download');
      },
    }).as('exports');

### Execution
![Screen Shot 2019-03-12 at 8 26 45 PM](https://user-images.githubusercontent.com/3360539/54248575-9059a500-4513-11e9-8d46-448b27b9e1f3.png)

**Comment by GvS666** [comment]
I have the same issue. Have you found any workaround?

**Comment by gcirone** [comment]
My simple workaround is to add cypress command:end event like:

```
 cy.route({
      url: `/url`,
      method: 'GET',
      response: {},
      onResponse: () => {
          Cypress.once('command:end', (command) => {
              cy.log('IT WORKS :)');
          })
      },
    })
```

I hope it help you :)

**Comment by MNF** [comment]
In my case cy.log caused error instead of returning specified response 
 cy.route({
            method: 'POST',
            url: '**/Submit’
            onRequest: req => {
                const requestBody = req.request.body;
                cy.log(requestBody);
            },
            response: {},
        }); 
 When I removed cy.log, the test worked as expected

**Comment by carloscheddar** [comment]
I had to use this workaround to check the content of the UI onRequest and onResponse. I stored the values in separate variables and wrote a spec to verify the content outside of the callbacks.

```js
let onRequestButtons;
let onResponseButtons;

before(() => {
  cy.route({
    url: `/v2/initiatives/${initiativeId}/exports`,
    method: 'GET',
    response: exportsData,
    onRequest: () => {
      onRequestButtons = Cypress.$('#active-view ul li');
    },
    onResponse: () => {
      onResponseButtons = Cypress.$('#active-view ul li');
    },
  }).as('exports');
})

it('has the correct request content', () => {
  cy.wrap(onRequestButtons).should('have.length', 4).contains('button', 'Pending');
});

it('has the correct response content', () => {
  cy.wrap(onResponseButtons).should('have.length', 4).contains('button', 'Download');
});


```

**Comment by rmlira** [comment]
I'm using with:

```typescript
onRequest: async(xhr) -> {
  // Your code here
}
```

apparently works.

**Comment by jennifer-shehane** [comment]
Closing as cy.route() is now deprecated. Please update your code to use cy.intercept() and open a new issue for any issues found using the new API.
