### ISSUE TITLE
Move all @types CLI dependencies from prod to dev list

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3371]
## Problem

When we ship Cypress NPM package we include several `@types` prod dependencies because we want to reference them in our types `index.d.ts` file. 

in `cli/package.json`

```json
{
  "dependencies": {
    "@types/blob-util": "1.3.3",
    "@types/bluebird": "3.5.18",
    "@types/chai": "4.0.8",
    "@types/chai-jquery": "1.1.35",
    "@types/jquery": "3.3.6",
    "@types/lodash": "4.14.87",
    "@types/minimatch": "3.0.3",
    "@types/mocha": "2.2.44",
    "@types/sinon": "7.0.0",
    "@types/sinon-chai": "3.2.2"
  }
}
```

and in our `index.d.ts` file we reference these dependencies (and a few local files)

```ts
/// <reference path="./blob-util.d.ts" />
/// <reference path="./bluebird.d.ts" />
/// <reference path="./minimatch.d.ts" />
/// <reference path="./moment.d.ts" />

/// <reference types="chai" />
/// <reference types="chai-jquery" />
/// <reference types="jquery" />
/// <reference types="lodash" />
/// <reference types="mocha" />
/// <reference types="moment" />
/// <reference types="sinon" />
/// <reference types="sinon-chai" />
```

We need these type files because they provide types and documentation for things like Lodash `Cypress._` object, but there are a couple of problems

1. We have duplicates: for example, we depend on `@types/blob-util` but also have a local file `blob-util.d.ts`
2. type dependencies in _prod_ can conflict with user's type dependencies, which seems to the issue in #1227
3. usually `@types` is considered a _dev_ dependency, should not be _prod_

## Proposal

We can move all necessary `@types` packages from `dev` to `prod` dependencies. During building we can copy any necessary files and include them with our CLI code, just like we do for `types/blob-util.d.ts`

Our distributed `index.d.ts` thus will only refer to local paths to bring it all together, and all conflicts with the user's `@types` would be avoided (fingers crossed)

**Comment by jcreamer898** [comment]
It would be great to get this merged. We're seeing very similar issues in our mono-repo where we use Jest already. Simply installing cypress causes all kinds of mayhem...

![](https://d.pr/i/GYErYs+)

Would be glad to help test new releases after this is merged!

**Comment by jennifer-shehane** [comment]
@jcreamer898 Thanks! Feel free to pull down this branch and try it out also https://github.com/cypress-io/cypress/pull/3425

**Comment by jcreamer898** [comment]
Oh sweet, will do.

**Comment by avahe-kellenberger** [comment]
According to the proposal, was cypress not intended to install types packages in `node_modules/@types`? 
I saw [this](https://github.com/cypress-io/cypress/blob/develop/cli/scripts/utils.js) which seemed to suggest otherwise, and having `@types/chai-jquery` installed from cypress is causing conflicts with other types in my project

**Comment by bahmutov** [comment]
@avahe-kellenberger I am not sure what you are referring to. The CLI package still installs these packages _as dev dependencies_ in this repository, but when it builds NPM package _for Cypress users_ then it will NOT install them. Thus they will no longer conflict with your types. This has been merged into `develop` branch but has not been released yet.

**Comment by avahe-kellenberger** [comment]
Oh, I missed that it hasn't been released - Thanks for the info.
