### ISSUE TITLE
Add a way for custom commands to provide data for Dashboard

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3372]
External services, for example, visual diffing services, have 2 components. First is the custom command that takes the screenshot, sends the image to the external API, receives the result and continues.

For example, the test might have something like this

```js
it('looks the same', () => {
  cy.visit('/')
  cy.imageDiff('home page')
})
```

Second is the external diffing service dashboard that can show the image comparison. User has access to the 3rd party dashboard and would find the results for the above particular `cy.imageDiff()` call at some url like

```
https://app.image-diff-service.com/projects/abc123/e51d4263-1cf1-4d9c-8805-bd5fb311087f
```

If the test run is being recorded on the Cypress Dashboard, it would be nice to have this information and the right link to the external dashboard shown somehow.  For example, in addition to our own screenshots and video and terminal log, we could have a section with external links generated by the custom commands. Maybe somewhere here?

![screen shot 2019-02-07 at 11 53 44 am](https://user-images.githubusercontent.com/2212006/52427994-12971980-2acf-11e9-9394-ad755ea29502.png)

We can provide minimal information about each custom command

- external service name
- command parameters, like "home page" in the example
- success/failure status
- link to the external dashboard that should open at the relevant url

## Questions

- What information should we accept from the custom command?
- Should external services register with Cypress.io? How do we ensure that spam links to do start appearing in the Cypress Dashboard?
- Should we show the list of logical commands? And allow meta information on every command?
- Should we tie custom commands with this extra information to the timeline so we can add it to the video?

**Comment by bahmutov** [comment]
Another take: some integrations might have information only in the last `before` callback and not with each command.

**Comment by jennifer-shehane** [comment]
@bahmutov Do you still regard this as on our future roadmap?

**Comment by bahmutov** [comment]
Yes

**Comment by jennifer-shehane** [comment]
Closing as this is not currently under consideration to offer in Cypress Cloud.
