### ISSUE TITLE
window.location.hostname not updated on url change (new domain) and can't set cookie

### ISSUE THREAD

**Issue by goofiw** [cypress-io/cypress#3377]
### Current behavior:

`window.location.hostname` is not updated on domain change

### Desired behavior:

On a domain change I would expect the `window.location.hostname` to update so on cookie gets and sets the new domain is used.

I tried providing the new domain to the `.setCookie()` command as an option `({domain: 'locahost:8443'})` however setting the cookie fails without a useful error message:

`undefined: Failed to parse or set cookie named "user".`

### Steps to reproduce: (app code and test code)

kinda squanchy:

```javascript
cy.get(signInUsernameInput).type(userEmail);
cy.get(signInPasswordInput).type(userPassword);
cy.get(signInSubmit).click();

cy.wait(3000); //for some reason the link has 0 height and 0 width at first
cy.get(activitiesHeaderLink).changeLinkTarget();
cy.get("#activity-start-date__btn").should("be.visible");
```

```js
Cypress.Commands.add(
  "changeLinkTarget",
  { prevSubject: true },
  (subject, options) => {
    const proxyDomain = "localhost:8443";
    subject[0].setAttribute("target", "_self");

    const newHrefArr = subject[0].href.split("/");
    newHrefArr[2] = `//${proxyDomain}/`;

    const newHref = newHrefArr.join("");

    let userCookie;
    subject[0].setAttribute("href", newHref);

    return cy
      .getCookie("user")
      .then(cookie => {
        console.log("cookie", cookie);
        userCookie = cookie;
        console.log(subject[0].href);
        return subject;
      })
      .click()
      .wait(3000)
      .then(() => {
        console.log("hostname", window.location.hostname);
        return cy.setCookie("user", userCookie.value, { domain: proxyDomain });
      })
      .getCookie("user")
      .then(cookie => console.log("set coookie!", cookie));
  }
);
```

cypress.json
```json
{ "chromeWebSecurity": false }
```

### Versions

3.1.5, 10.13.6, (Electron 59 headless, 72.0.3626.96 chrome in app)

Happy to dig into this further, I'm trying to set up a few E2E tests that exist in production as one domain, but in a test environment share a backend but are hosted separately.

Another option would be to run a separate test using the event listeners, but passing the existing commands to a new test that is programmatically created might get tricky, or be impossible.

**Comment by jennifer-shehane** [comment]
Just a quick note regarding your `.wait()` command, you should be able to assert that the element is not 0 height and width with something like below:

```
cy.get('#signin-link').invoke('width').should('be.gt', 0)
cy.get('#signin-link').invoke('height').should('be.greaterThan', 0)
```

**Comment by MarkHancock74** [comment]
Hi, Stupid question... how do i get the value of a cookie and pass it to a variable... I have tried the following

const myvalue = cy.getcokie('cookiename').value;
but when i post my form and check the value it is undefined

Thanks

**Comment by bahmutov** [comment]
@MarkHancock74 yours is unrelated to question to the original issue, you better ask questions like these in our chat http://on.cypress.io/chat

but to answer it: we need to add an example of this to http://on.cypress.io/getcookie but Cypress commands are all async, so you would get the value like

```js
cy.getCookie('name')
  .then(value => ...)
```

**Comment by MarkHancock74** [comment]
Thanks Gleb

Did not know of the chat feature

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. 

Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
