### ISSUE TITLE
cypress does not click on some elements 

### ISSUE THREAD

**Issue by lukasdonko** [cypress-io/cypress#3388]
### Current behavior:
From version 3.1.3 cypress does not click correctly on some elements on the page in CI (localy works fine). In this case X button in top right corner, after clicking should hide the Help page.

https://dashboard.cypress.io/#/projects/218yxc/runs/1066239/specs

### Desired behavior:
The same test passed in cypress version 3.1.2. 

https://dashboard.cypress.io/#/projects/218yxc/runs/1066103/specs

### Versions
3.1.3 and higher

**Comment by szymach** [comment]
I have a similar issue - I open a bootstrap modal and when I want Cypress to click the close button, it finds the element properly, but clicks outside of it, like so:

![cypress_misclick](https://user-images.githubusercontent.com/2230556/54497575-6d0c6c80-48fc-11e9-92e0-4d658553df88.png)

If I understand correctly, the red dot marks the place where the click action has been performed? Manually clicking in the Cypress window closes the window properly, so the Javascript itself works.

**Comment by lukasdonko** [comment]
fixed with version 3.2.0
