### ISSUE TITLE
Chrome DevTools disappears once undocked in a new window

### ISSUE THREAD

**Issue by NoriSte** [cypress-io/cypress#3389]
### Current behavior:
Once undocked the Chrome devtools I can't use it anymore
![screen-shot-2019-02-08-at-15 58 51](https://user-images.githubusercontent.com/173663/52486149-b01b4780-2bba-11e9-8ca6-37cf47d4ab1c.jpg)

### Steps to reproduce: (app code and test code)
- start a Cypress test in a Chrome of your
- open the devtools
- undock the devtools
- the devtools now disappears
- you can do everything (flags, launching inpection from chrome://inspect, uninstall/reinstall Chrome) but you can't access the devtools anymore
- the only way I found is to completely remove the `~/Library/Application Support/Cypress/cy/` (completely, not only the `~/Library/Application Support/Cypress/cy/production/browsers/` folders), relaunch Cypress and everything works again. Obviously you lose every customisation of Chrome

### Versions
Cypress: 3.1.5
Chrome: both Canary 74 and Beta 72
MacOS High Sierra: 10.13.6

**Comment by elaco77** [comment]
Same thing happened to me. Take look at the very top and very left edge of your screen, I found it there. Dev tools do dock out but completely out of the screen. When you find it there you can resize dev tools window and position it where ever you want or dock it back to the Cypress ui.

**Comment by NoriSte** [comment]
Thank you so much and you're right, I found the really thin vertical line that is the default size of the devtools window once it opens... I resize it in a while with a custom Moom shortcut.
Thank you! Stefano

**Comment by jennifer-shehane** [comment]
Yes, we're aware of this issue 😭 https://github.com/cypress-io/cypress/issues/2497

>the only way I found is to completely remove the `~/Library/Application Support/Cypress/cy/` (completely, not only the `~/Library/Application Support/Cypress/cy/production/browsers/` folders), relaunch Cypress and everything works again. Obviously you lose every customisation of Chrome

This may be helpful information actually to track this down.

**Comment by jennifer-shehane** [comment]
@NoriSte I tried following what you described, deleting the `cy` folder, but I was unable to get the DevTools to show up in the correct size undocked. Are you sure there was not another step you took in your process of getting the DevTools back?

**Comment by NoriSte** [comment]
@jennifer-shehane sorry if I didn't explain correctly: the cache directory removal is useful only to make the devtools panel back again as docked.
My biggest problem was: since the devtools window disappeared, how can I get it back as docked (and use it)? Without viewing the panel it's impossible to re-dock it (and use it docked) and the cache dir removal served to do so (to remove my choice to have it undocked).
