### ISSUE TITLE
Cypress.$ accesses wrong document

### ISSUE THREAD

**Issue by JumpmanJunior** [cypress-io/cypress#3390]
If I try to access an element via jQuery which is exposed by Cypress the wrong document is queried. The queried document is the Cypress default blank page.

Steps to reproduce:
```
cy.visit('/')
cy.log(Cypress.$('body').html())
```
Cypress visits the website which is set via the baseUrl. The website is correctly rendered. But the log contains the body of the Cypress default blank page.

Cypress: 3.1.5 (ZIP download)
Operating system: Windows 10
Browser: Chrome 71

**Comment by brian-mann** [comment]
`Cypress.$` is synchronous - not asynchronous. It runs immediately before the `cy.visit()` has finished processing. Just put a `debugger` in your code and execute it from the console - you'd see the same thing.

`Cypress.$` is bound to the remote document (under test) which before the first visit succeeds is the initial blank page.
