### ISSUE TITLE
Error: INVALID_STATE_ERR - 0 when switching browser tabs during cy.route() commands running

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#34]
When I switch browser tabs while running cypress tests during cy.route() commands, the test suite fails and throws: `Error: INVALID_STATE_ERR - 0`. 

![screen shot 2015-05-05 at 11 10 35 am](https://cloud.githubusercontent.com/assets/1271364/7475743/6f7ad4b4-f317-11e4-9f38-a365b5518ed6.png)

The stack trace leads to Sinon.js `setResponseHeaders` method:

```js
    function verifyRequestOpened(xhr) {
        if (xhr.readyState != FakeXMLHttpRequest.OPENED) {
            throw new Error("INVALID_STATE_ERR - " + xhr.readyState);
        }
    }
```

**Comment by brian-mann** [comment]
Fixed in [`0.11.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0113-09162015).
