### ISSUE TITLE
Can't skip a test with a done() callback

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress#3403]
this currently fails:
```js
  it('can skip with done()', function (done) {
      this.skip()
  })
```

![image](https://user-images.githubusercontent.com/14625260/52500766-c28e8480-2bac-11e9-8031-20bbedc35da7.png)

https://mochajs.org/#inclusive-tests

![image](https://user-images.githubusercontent.com/14625260/52509418-0641b800-2bc6-11e9-83ae-c2c5aedd2178.png)

**Comment by jennifer-shehane** [comment]
This displays a different error in upcoming [v4.0 release](https://github.com/cypress-io/cypress/issues/4270) (which includes Mocha upgrade).

<img width="874" alt="Screen Shot 2019-07-13 at 9 31 33 AM" src="https://user-images.githubusercontent.com/1271364/61166282-108b2800-a551-11e9-920b-07e112664bdf.png">
