### ISSUE TITLE
Error text is not appearing on submission form after receiving a 400 error

### ISSUE THREAD

**Issue by funatronics** [cypress-io/cypress#3406]
### Current behavior:

I'm submitting a form that should return error text underneath the input field (e.g. "That screen name was not found"). However when I submit the form, the text never appears. In the console I see the site has returned a 400 error (expected response with the error).

This only happens in the Chrome browser opened by Cypress. If I go in the regular Chrome browser, the error text appears as expected. Does anyone know what's going on? Is the 400 error throwing Cypress off?

### Desired behavior:

The error text never appears.

### Versions

Chrome 71, Cypress 3.1.1

**Comment by jennifer-shehane** [comment]
Hey @funatronics, we will need a reproducible example, test code + relevant app code to look into this. Any screenshots/video would help also.

**Comment by funatronics** [comment]
Closing this issue because I wrote another that explains the problem better:
https://github.com/cypress-io/cypress/issues/3650
