### ISSUE TITLE
File upload with DataTransfer loads file to input type file, but it's not an instance of File

### ISSUE THREAD

**Issue by vikmaksimenko** [cypress-io/cypress#3420]
### Steps to reproduce: (app code and test code)

1. Create the following HTML page 
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<input type="file" id="file">
	<input type="button" id="load" value="Load File">
	<script>
		function addListener(element, eventName, handler) {
		  if (element.addEventListener) {
		    element.addEventListener(eventName, handler, false);
		  }
		  else if (element.attachEvent) {
		    element.attachEvent('on' + eventName, handler);
		  }
		  else {
		    element['on' + eventName] = handler;
		  }
		}

		addListener(document.getElementById('file'), 'change', function() {
			console.log(this.files[0] instanceof File);
		});


		addListener(document.getElementById('load'), 'click', function() {
			var file = new File(['content'], 'sample1.txt', {type: "text/txt"});
        	var dataTransfer = new DataTransfer();
        	dataTransfer.items.add(file);

        	var fileInput = document.getElementById("file");
        	fileInput.files = dataTransfer.files;
        	console.log(fileInput.files[0] instanceof File);
    	});
	</script>
</body>
</html>
```
2. Add the test, that uploads a file to input (for simplifying sample I generate a file instead of using fixtures)
```js
/// <reference types="Cypress" />

context('Files', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
  })

  it('cy.readFile() - read a files contents', () => {
    cy.get("input[type='file']").then(subject => {
        const el = subject[0];
        const testFile = new File(['content'], 'sample1.txt');
        const dataTransfer = new DataTransfer();
        dataTransfer.items.add(testFile);
        el.files = dataTransfer.files;
        cy.log(el.files[0] instanceof File);
    });

     cy.get("input[type='file']").then(subject => {
        const el = subject[0];
        cy.log(el.files[0] instanceof File);
    });
  })
})
```
3. Run test, open browser console

### Current behavior:

`instanceof File` called from Cypress returns `true`
`instanceof File` called from input `onChange` event is `false`

![ar](https://user-images.githubusercontent.com/5682824/52538177-21ecc000-2d78-11e9-8c2a-7c13d626d834.png)

### Desired behavior:

`instanceof File` called from input `onChange` event should be `true`

### Versions

Cypress - 3.1.5,
Operating system - Ubuntu 18.04
Browser - Chrome 71, Electron 59

**Note:** `console.log(this.files[0])` will display `File` object, but in our project we're using Firebase tool, and it checks, that only File or Blob can be uploaded to storage

Full demo can be found in [https://github.com/vikmaksimenko/cypress_file_upload](url)

**Comment by anis-butterfly** [comment]
You need to use window global variable to create the File and DataTransfer objects   or else the comparison  will always be **false**,
something like this should work 😄  ,

context('Files', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
  })

  it('cy.readFile() - read a files contents', () => {
    cy.get("input[type='file']").then(subject => {
 cy.window({ log: false }).then((window) => {
        const el = subject[0];
        const testFile = new window.File(['content'], 'sample1.txt');
        const dataTransfer = new window.DataTransfer();
        dataTransfer.items.add(testFile);
        el.files = dataTransfer.files;
        cy.log(el.files[0] instanceof File);
})
    });

     cy.get("input[type='file']").then(subject => {
        const el = subject[0];
        cy.log(el.files[0] instanceof File);
    });
  })
})

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
