### ISSUE TITLE
Unable to type in iframe but can get text

### ISSUE THREAD

**Issue by gbminnock** [cypress-io/cypress#3421]
Hi, I've gone through the other iframe issues and was unable to see a solution to my iframe issue. 

I am using tinymce editor which renders in an iframe (under the same domain).

### Current behavior:

I am able to select (manually entered) text from the iframe however I am unable to type.

From the console it does seem to work however the display shows it as empty.

````javascript
cy.get('iframe#MyBlog_ifr').then(($iframe) => {
  debugger;
  var doc = $iframe.contents().find("body#tinymce");
  cy.log(doc);
  cy.wrap(doc).type("Test Blog Entry");
  cy.wrap(doc).should("have.text", "Test Blog Entry");
})
````

The test output:

````bash
CypressError: Timed out retrying: expected '<body#tinymce.mce-content-body.>' to have text 'Test Blog Entry', but the text was '  '
````

### Desired behavior:
Can type into iframe using Cypress. 

### Versions
Cypress 3.1.5, Chrome, Windows 10

**Comment by jennifer-shehane** [comment]
We do not currently fully support testing iframes - please track this issue for full iframe support: https://github.com/cypress-io/cypress/issues/136

**Comment by chodorowicz** [comment]
@gbminnock it's possible to type in TinyMCE in current version of Cypress `3.4.1`. But you need to type not inside `body` but descendant `p` element

```js
cy.wrap(doc).find("p").type("Test Blog Entry");
```
