### ISSUE TITLE
Throw error when trying to set Cypress.config() for non-mutable config values

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#3422]
### Current behavior:

When trying to set `Cypress.config()` for non-mutable configurations which are ignored from inside of the tests, Cypress does not perform the action as expected and does not throw an error.

#### Example:

The test below passes, but Cypress does *not* indeed change the location of the `screenshotsFolder`, nor does it throw an error telling you that the `screenshotsFolder` was not set.

```js
it('screenshots folder not settable', () => {
  Cypress.config('screenshotsFolder', 'cypress/screenshots/desktop')
  expect(Cypress.config('screenshotsFolder')).to.eq('cypress/screenshots/desktop')
  cy.screenshot('homepage_desktop')
})
```

**Actual saved screenshot location**

<img width="428" alt="screen shot 2019-02-11 at 11 52 28 am" src="https://user-images.githubusercontent.com/1271364/52547132-93b61f80-2df3-11e9-9c05-c6195f76dd3b.png">

#### Related issues:

- Does not print full config: https://github.com/cypress-io/cypress/issues/509
- Trying to set `screenshotsFolder`: https://github.com/cypress-io/cypress/issues/1525

### Desired behavior:

- [ ] Cypress should throw an error when trying to set non-mutable configuration values. 
- [ ] Make list of all config values that are mutable vs non-mutable. Maybe add to documentation.

### Versions

Cypress 3.1.5

**Comment by aurium** [comment]
Hi, i want to solve this issue.

I `console.log`ed the extended `state` inside `set()` at `setter_getter.coffee` and the `screenshotsFolder` value was updated in it (as expected) using `Cypress.config` in a test. How can i know which key it can or can't change?

**Comment by aurium** [comment]
hi?

**Comment by jennifer-shehane** [comment]
Related larger issue: https://github.com/cypress-io/cypress/issues/6407
