### ISSUE TITLE
The mochawesome reporter is not working with the cypress

### ISSUE THREAD

**Issue by pmbaldha** [cypress-io/cypress#3426]
### Current behavior:
I have installed package by running the command:

```
npm install --save-dev mocha mochawesome mochawesome-merge mochawesome-report-generator
```

Then If I add the line `"reporter" : "mochawesome"` in the `cypress.json`, I am getting below error:

```
  Running: packages\single-site\dup-archive\mysqldump.js...                               (1 of 10)
"[object Object]" reporter blew up with error:
AssertionError [ERR_ASSERTION]: path must be a string
    at Module.require (module.js:512:3)
    at require (internal/module.js:11:18)
    at Mocha.reporter (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:167:21)
    at new Mocha (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:88:8)
    at Reporter.setRunnables (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\reporter.js:196:20)
    at Object.onSetRunnables (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\project.js:288:46)
    at Socket.<anonymous> (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\socket.js:233:21)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Error: invalid reporter "[object Object]"
    at Mocha.reporter (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:180:13)
    at new Mocha (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:88:8)
    at Reporter.setRunnables (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\reporter.js:196:20)
    at Object.onSetRunnables (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\project.js:288:46)
    at Socket.<anonymous> (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\socket.js:233:21)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Error: invalid reporter "[object Object]"
    at Mocha.reporter (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:180:13)
    at new Mocha (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:88:8)
    at Reporter.setRunnables (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\reporter.js:196:20)
    at Object.onSetRunnables (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\project.js:288:46)
    at Socket.<anonymous> (C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\lib\socket.js:233:21)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at C:\Users\admin\AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Versions

Operating System: Windows 10
Cypress: Latest

Thank you very much

**Comment by bahmutov** [comment]
I hit the same problem last week, but could not reliably recreate it. Reinstalling NPM modules helped in my case, and I was in a rush to finish part of the testing workshop to actually investigate this problem. But we have seen this before, wish the thrown error was more helpful

**Comment by pmbaldha** [comment]
@bahmutov I have already tried reinstalling NPM modules and Cypress, but I have not succeeded. I have installed below dev dependencies:

```
"devDependencies": {
    "cypress": "^3.1.5",
    "fs-extra": "^7.0.1",
    "glob": "^7.1.3",
    "mocha": "^5.2.0",
    "mocha-junit-reporter": "^1.18.0",
    "mocha-multi-reporters": "^1.1.7",
    "mochawesome": "^3.1.1",
    "mochawesome-merge": "^1.0.5",
    "mochawesome-report-generator": "^3.1.5",
    "rimraf": "^2.6.3"
  }
```

Can you please help me?

Thank you very much...

**Comment by jennifer-shehane** [comment]
Can you make sure to try:

```
npm prune
npm i
```

**Comment by pmbaldha** [comment]
@jennifer-shehane It's working. Thank you very much.

**Comment by AlbinoDrought** [comment]
I just had this issue. The solution in https://github.com/cypress-io/cypress/issues/3426#issuecomment-462622820 did not work for me.

The issue seems to stem from [`Reporter.loadReporter`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/reporter.coffee#L318) and me having a `mochawesome.json` in my current working directory.

Here's what my debug log showed:

```
trying to load reporter: mochawesome
trying to require local reporter with path: /home/sean/projects/frontend/mochawesome

"[object Object]" reporter blew up with error:
AssertionError [ERR_ASSERTION]: path must be a string
    at Module.require (module.js:512:3)
    at require (internal/module.js:11:18)
```

The solution for me was to remove the `mochawesome.json` file which was generated after merging my mochawesome reports :smile:

**Comment by sebillac81** [comment]
I removed the mochawesome.json  file from the root directory, and it's work for me.

**Comment by moinuddin14** [comment]
> I just had this issue. The solution in [#3426 (comment)](https://github.com/cypress-io/cypress/issues/3426#issuecomment-462622820) did not work for me.
> 
> The issue seems to stem from [`Reporter.loadReporter`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/reporter.coffee#L318) and me having a `mochawesome.json` in my current working directory. `Reporter.loadReporter` prefers `require`-able files in the local directory over `require`-able packages, and `mochawesome.json` (as generated in the [Multiple Reporters example](https://docs.cypress.io/guides/tooling/reporters.html#Multiple-reporters-examples)) is a `require`-able file in the local directory.
> 
> Here's what my debug log showed:
> 
> ```
> trying to load reporter: mochawesome
> trying to require local reporter with path: /home/sean/projects/frontend/mochawesome
> 
> "[object Object]" reporter blew up with error:
> AssertionError [ERR_ASSERTION]: path must be a string
>     at Module.require (module.js:512:3)
>     at require (internal/module.js:11:18)
> ```
> 
> The solution for me was to remove the `mochawesome.json` file which was generated after merging my mochawesome reports

This worked for me. Find mochawesome.json files that may have been generated in parallel to package.json and any sub-folders of the project.

**Comment by ManuBoca92** [comment]
> I just had this issue. The solution in [#3426 (comment)](https://github.com/cypress-io/cypress/issues/3426#issuecomment-462622820) did not work for me.
> 
> The issue seems to stem from [`Reporter.loadReporter`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/reporter.coffee#L318) and me having a `mochawesome.json` in my current working directory. `Reporter.loadReporter` prefers `require`-able files in the local directory over `require`-able packages, and `mochawesome.json` (as generated in the [Multiple Reporters example](https://docs.cypress.io/guides/tooling/reporters.html#Multiple-reporters-examples)) is a `require`-able file in the local directory.
> 
> Here's what my debug log showed:
> 
> ```
> trying to load reporter: mochawesome
> trying to require local reporter with path: /home/sean/projects/frontend/mochawesome
> 
> "[object Object]" reporter blew up with error:
> AssertionError [ERR_ASSERTION]: path must be a string
>     at Module.require (module.js:512:3)
>     at require (internal/module.js:11:18)
> ```
> 
> The solution for me was to remove the `mochawesome.json` file which was generated after merging my mochawesome reports 😄

This also worked for me.

**Comment by laurencehoess** [comment]
I had the same problem after trying the mochawesome-merge and mochawesome-report-generator example commands shown in the example on this page: https://docs.cypress.io/guides/tooling/reporters.html#Multiple-reporters-examples

Maybe change the doc to change the output directory?

**Comment by brettz9** [comment]
Thanks all for these tips--this had really been driving me crazy until the combined info led to a solution!

As with @laurencehoess and @pmbaldha , I was working with the multiple reporters example. The problem in such a scenario is that if one uses the `mocha-multi-reporters.json` (or presumably the `cypress-multi-reporters.json`) as the config file name, that can shadow the multi-reporters package and cypress ends up `require`'ing the config file as the reporter itself (if just a name is available) instead of requiring the reporter . This was essentially the same kind of issue as mentioned in https://github.com/cypress-io/cypress/issues/3426#issuecomment-482667911 but instead of relating to the output files, it was due to a config file.

To workaround this bug, I renamed the config file to `mmr.json` and indicated it via `cypress run --reporter=mocha-multi-reporters --reporter-options configFile=mmr.json --spec=....`

The docs should be updated to take note of this unless a fix is on the way because one will just get the frustrating error if one tries the example now.

Btw, the maintainer of `cypress-multi-reporters` is collaborating now on `mocha-multi-reporters` (and it still works on Cypress and is intended to continue working on Cypress), so the docs should probably recommend `mocha-multi-reporters` now instead of `cypress-multi-reporters` in https://docs.cypress.io/guides/tooling/reporters.html#Examples .

**Comment by itsshivam198** [comment]
Could not load reporter by name: cypress-mochawesome-reporter

We searched for the reporter in these paths:

- C:\Users\AkshayKumar\QAdemo\cypress-mochawesome-reporter
- C:\Users\AkshayKumar\QAdemo\node_modules\cypress-mochawesome-reporter

The error we received was:

Cannot find module 'C:\Users\AkshayKumar\QAdemo\node_modules\cypress-mochawesome-reporter'
Require stack:
- C:\Users\AkshayKumar\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\lib\reporter.js
- C:\Users\AkshayKumar\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\lib\project-base.js
- C:\Users\AkshayKumar\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\lib\open_project.js
- C:\Users\AkshayKumar\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\lib\cypress.js
- C:\Users\AkshayKumar\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\index.js
- C:\Users\AkshayKumar\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\index.js

**Comment by itsshivam198** [comment]
Could not load reporter by name: cypress-mochawesome-reporter

We searched for the reporter in these paths:

**Comment by kris-luminar** [comment]
I'm using the projects option where I have one folder at the repository root for each for each of many Cypress projects. To get this plugin to work for my use-case, I had to require an absolute path to the reporter's main directory or else I'd get this error message:
```log
Error: Cannot find module '/path-from-root-to-my-repo/my-repo/current-cypress-project/node_modules/cypress-mochawesome-reporter/plugin'
```
The path is wrong because `node-modules/` is in `my-repo/`, not `my-repo/current-cypress-project/`

My workaround:
```javascript
const { defineConfig } = require('cypress');

module.exports = defineConfig({
    reporter: '/path-from-root-to/node_modules/cypress-mochawesome-reporter',
    },
    e2e: {
        setupNodeEvents(on, config) {
            require('cypress-mochawesome-reporter/plugin')(
                on
            );
        }
    }
});
```

**Comment by joshianand18** [comment]
Add this command
npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator
