### ISSUE TITLE
Cypress postinstall fails on Travis:  Possible EventEmitter memory leak detected...

### ISSUE THREAD

**Issue by ruffle1986** [cypress-io/cypress#3439]
### Current behavior:

Currently, `npm ci` fails because Cypress's postinstall script returns with a `1`. It says: `Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit` but you can take a look into my Travis log:
https://travis-ci.com/ruffle1986/metron/jobs/177083473

If I ssh into the Travis VM and run the maven task manually, it works fine.

### Desired behavior:

I don't want to get the "memory leak" error message to be able to install cypress properly.

### Versions

Cypress v3.1.0

Any idea?

**Comment by jennifer-shehane** [comment]
We have seen this warning before, but have not seen it as the cause of a non-zero exit status during postinstall. 

Do you happen to have the complete log?

**Comment by ruffle1986** [comment]
@jennifer-shehane Unfortunately, it works fine if I ssh into the Travis VM. The only thing I could do is enabling full debug mode in maven by adding the `-e` and `-X` arguments. 
Here's the log. It has another error message different from the previous. It might tell something you:
https://travis-ci.com/ruffle1986/metron/jobs/177748945

But it has still a problem with the postinstall script. It seems something is wrong with the `yauzl` module.

**Comment by ruffle1986** [comment]
I think the issue is the same as in #3515
