### ISSUE TITLE
Weird "automatic" page scrolling without any trigger

### ISSUE THREAD

**Issue by ovidijusr** [cypress-io/cypress#3450]
### Current behavior:

For some reason it scrolls when being dom elements being clicked on, but this functionality does not have any scroll behaviour.

Also tried to disable auto scroll from cypress panel, doesn't do any difference.

It looks like this:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6230536/52713430-efbda700-2f9f-11e9-8a88-0e1d23ed5800.gif)

### Desired behavior:

Prevent the scrolling

### Steps to reproduce: (app code and test code)

    cy.viewport(1400, 1306);
    cy.visit('https://www.novasol.dk/');

    cy.get('.cc_btn_accept_all').click();

    cy.get('.search-form-field__input--guide')
      .click();

    cy.get(
      '.search-form-field__popout > .search-guide > .search-guide__header > div > .search-guide__link'
    )
      .click();

    cy.get(
      '.search-guide__results > .search-guide__results-conveyor-belt > .search-guide__results-list:nth-child(1) > .has-children:nth-child(1) > .search-guide__item-selection'
    ).click();

    cy.get(
      '.search-guide__results > .search-guide__results-conveyor-belt > .search-guide__results-list > li:nth-child(3) > .search-guide__item-selection'
    ).click();

    cy.get(
      ':nth-child(3) > table > .js-CalendarMonth__grid > :nth-child(3) > :nth-child(4) > .CalendarDay__button'
    ).click();

    cy.get(
      ':nth-child(3) > table > .js-CalendarMonth__grid > :nth-child(3) > :nth-child(6) > .CalendarDay__button'
    ).click();

    cy.get(
      '.guestpicker__dropdown > .guestpicker__input:nth-child(1) > .guestpicker__field > .guestpicker__incrementbutton > .button'
    ).click();

    cy.get(
      '.guestpicker__dropdown > .guestpicker__input:nth-child(2) > .guestpicker__field > .guestpicker__incrementbutton > .button'
    ).click();

    cy.get(
      '.guestpicker__dropdown > .guestpicker__input:nth-child(3) > .guestpicker__field > .guestpicker__incrementbutton > .button'
    ).click();

    cy.get(
      '.frontpage-splash__intro > #search-form > .frontpage-search > .frontpage-search__wrap > .frontpage-search__search-button'
    ).click();

### Versions
"cypress": "3.1.5", mac os x 10.14.3

**Comment by ovidijusr** [comment]
Update: also tried to trigger     cy.scrollTo(0, 0) but looks like it doesn't do anything too :(

**Comment by jennifer-shehane** [comment]
Hey @ovidijusr, currently Cypress does scroll whenever performing any actions (like click). You can read more about this behavior [here](https://on.cypress.io/interacting-with-elements#Scrolling).

However, we know this isn't ideal for everyone, so there is an issue open to change the scroll behavior that you can track here: https://github.com/cypress-io/cypress/issues/871

**Comment by vesper8** [comment]
if anyone else is running into this issue.. I made it go away with this hack (depends on jQuery):

```
    if (window.Cypress) {
      $(window).scroll(() => {
        $(window).scrollTop(0);
      });
    }
```

**Comment by chghulamnabi** [comment]
I am facing same issue.

**Comment by chghulamnabi** [comment]
I am using Cypress(version:6.0.0)

**Comment by jennifer-shehane** [comment]
In Cypress 6.1.0, there’s a new `scrollBehavior` configuration option that controls the viewport position when an element is scrolled prior to action commands. Possible values are `'top'`, `'bottom'`, `'center'`, `'nearest'`, and `false`, with `'top'` being the default. `scrollBehavior: false` disables scrolling altogether. `scrollBehavior` can be specified in [global configuration](https://on.cypress.io/configuration#Actionability), [test configuration](https://on.cypress.io/writing-and-organizing-tests#Test-Configuration) or individual [action commands](https://on.cypress.io/interacting-with-elements) via options.
