### ISSUE TITLE
How do we deal with floating point numbers in cypress/node js. ? 

### ISSUE THREAD

**Issue by anuhub** [cypress-io/cypress#3453]
Response key values which are floating point decimals retrieved from `cy.request` are auto-rounded by default. It's hard to interpret the rounding pattern. How do we avoid this auto-rounding and retrieve the values with exact precision returned from API ?

Also, same scenario happens when I try to read a file with floating point decimals using `fs` module using `readJson` method. Values are getting auto-rounded in a similar way.

Examples: 

`0.59190000000000009` is rounded to `0.5919000000000001`

`4647.3424257097241` to `4647.342425709725`

`6441579.5333300168` to `6441579.533330017`

**Comment by jennifer-shehane** [comment]
Hey @anuhub, could you detail where you are seeing the rounded numbers? Is this printed in the Command Log? Do you see this same rounding in the network tab? Are you console.logging the value? Any insight into how you went about debuggin or any screenshots would be helpful. 

Providing test code that reproduces the problem would be MOST ideal. Thanks!

**Comment by anuhub** [comment]
I see rounding of results when a file is read using fs module or using cy.request. I can see in console of network tab while debugging or using cy.log or in the output file created by writing the results to it.

Below is the sample code to reproduce it using fs module. Similar behavior happens when trying to read using cy.request.

`describe('Describe', ()=>{

    it('Test', ()=>{
        // Reading file using fs module
        cy.task('readAJson', 'C:/Share/SampleText.json').then(function(data){
            debugger
            console.log(data);
            cy.log(data)
        })
   
        // Also, we have an api which reads data from database and it's response is same as SampleText.json content
        // Results retrieved from cy.request to the above api are auto-rounded in the similar format as cy.task('readAJson') does.
    })
})
`
cy.task(readAJson) has it's implemention in index.js under plugins as below:

`  on('task', {
    readAJson(file){
         var raw = fs.readFileSync(file);
         return JSON.parse(raw);
    }
  })`

**Comment by jennifer-shehane** [comment]
This has to do with how `JSON.parse` handles numbers with many digits in JavaScript. This has nothing to do with Cypress. You can run this in your console and get the same rounding:

```js
JSON.parse('{"value": 0.91544900000000007}')
// {value: 0.9154490000000001}
```
