### ISSUE TITLE
Add clickable docs links to error messages

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#3456]
### Current behavior:
Does not support markdown

### Desired behavior:
Should support markdown for links to docs.

Originally this issue was to add full Markdown support, but that'll require a bit more work at a later date. This PR will just add links and the scaffolding to more easily add markdown support later on. 

- [x] Add Markdown rendering that only linkifys `on.cypress.io` domains

**Comment by jennifer-shehane** [comment]
Relevant issues: 
- asterisks displaying instead of single quotes in Command Log assertion https://github.com/cypress-io/cypress/issues/1360
- Allow formatting cy.log() text: https://github.com/cypress-io/cypress/issues/2134

**Comment by lilaconlee** [comment]
Ok, updated a handful of errors to get a sense of the different content in the messages. I'd love to get feedback before updating any more messages.

Changes: 
- Docs links are clickable (based on https://on.cypress.io in the text)
- Backticks added for command names, file paths, error messages (stripped in run mode)
- Blockquotes are indented (given we'd like to add code framing, didn't want to spend too much time updating these but think it'd be good to eventually add some sort of code snippet formatting)

### Examples
<img width="506" alt="screen shot 2019-02-19 at 2 42 17 pm" src="https://user-images.githubusercontent.com/7514489/53046928-d52f7600-3456-11e9-93d1-30a9d2aa7475.png">
<img width="509" alt="screen shot 2019-02-19 at 2 37 19 pm" src="https://user-images.githubusercontent.com/7514489/53046937-d791d000-3456-11e9-9c66-142d6d8c1b8b.png">
<img width="506" alt="screen shot 2019-02-19 at 2 27 19 pm" src="https://user-images.githubusercontent.com/7514489/53047070-23447980-3457-11e9-8d7f-337779307581.png">
<img width="507" alt="screen shot 2019-02-19 at 2 22 55 pm" src="https://user-images.githubusercontent.com/7514489/53047078-26d80080-3457-11e9-86ff-251f3dca86e9.png">

Before/after screenshots of all the errors I've updated in interactive and run mode can be found [here](https://airtable.com/shrQs5k3B7IHikFrX/tbl4RL7pxzADnV9Fp?blocks=hide).

**Comment by jennifer-shehane** [comment]
The inline links makes this whole thing work it. 💖

**Comment by lilaconlee** [comment]
Talked with Brian about error improvement yesterday, going to update error messages in a way where we focus on making changes to the most valuable error messages. Getting full markdown support done in a good looking way will take a bit more work, but figured we could just get clickable docs links in given it was already done.

**Comment by jennifer-shehane** [comment]
I wonder if this issue about adding doc links to command log should be part of the work here: https://github.com/cypress-io/cypress/issues/3610
