### ISSUE TITLE
cy.exec timed out

### ISSUE THREAD

**Issue by peterennis** [cypress-io/cypress#3462]
### Current behavior:

See below images

### Desired behavior:

I assumed it would work.

Possibly related: https://github.com/cypress-io/cypress/issues/789

### Steps to reproduce: (app code and test code)

Installed to this repo: https://github.com/adaept/aemo
and run the sample test.

### Versions

Cypress 3.1.5
Windows 10
Chrome 72

![capture505](https://user-images.githubusercontent.com/140737/52764749-2dd5bd80-2fd6-11e9-9987-14538cc60b49.png)
![capture504](https://user-images.githubusercontent.com/140737/52764751-2dd5bd80-2fd6-11e9-9703-1cf11062bdd7.png)
![capture503](https://user-images.githubusercontent.com/140737/52764752-2dd5bd80-2fd6-11e9-9ca1-150e8cd01667.png)
![capture502](https://user-images.githubusercontent.com/140737/52764753-2dd5bd80-2fd6-11e9-802e-8c5cce96fe9e.png)
![capture501](https://user-images.githubusercontent.com/140737/52764754-2dd5bd80-2fd6-11e9-8928-55c0166e3f3b.png)

**Comment by jennifer-shehane** [comment]
Did you try disabling the Windows Defender Firewall blocker for Cypress?

**Comment by peterennis** [comment]
@jennifer-shehane 

The setting shown on the WDF is what I accepted.
i.e. accept external to allow Cypress log reporting,
block internal to not mess with the PC.

I did not see anything in the documentation.

You will also see in the command prompt window a reference to
"not recognized as an internal or external command..."

This is from using the doc example to start Cypress.
On Windows it needs to be "\\" instead of "/"

I will test with also allowing the internal/private network WDF setting
and let you know.

I expect it will work if the demo is intended to show all tests passing.

It will then be a documentation update issue once confirmed.

**Comment by peterennis** [comment]
@jennifer-shehane 

WDF set to allow Domain, Private, Public, for UPD and TCP, inbound and outbound.
Then all tests pass.
Is HTTPS supported?

![capture507](https://user-images.githubusercontent.com/140737/52835182-45767a00-309a-11e9-99c6-2b9bc75dc3c7.png)

![capture506](https://user-images.githubusercontent.com/140737/52835299-bae24a80-309a-11e9-88a8-64647b549f20.png)

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
