### ISSUE TITLE
I can run the test and record it but it is not uploading to dashboard

### ISSUE THREAD

**Issue by MarcoAmaralQA** [cypress-io/cypress#3467]
Hey guys,

I installed Cypress via NPM on windows 10 and I am able to run Cypress and the Test runner but when I run the command > npm run cy:run --record --key XXX  --spec 'cypress\integration\POWr-Tests\log-in-test.js' to record the test it does not populate my dashboard or appears on Cypress > Runs Tab.

I got 2 issues that I do not know how to address it.

1 - Issue > It does not run the only test on the file I selected it runs the test on all files inside Integrations folder the examples files and my tests which is in a subfolder inside Integrations folder.

I ran this command >  npm run cy:run --record --key XXX  --spec 'cypress\integration\POWr-Tests\log-in-test.js' 

2 - Issue > After the test runs I get the success message, however, no files are uploaded to the dashboard or any data about this run is on and the Runs Tab on Cypress. This tab is empty as well as the dashboard.

This is the cy:run result > https://www.screencast.com/t/2urDhnceTWUK
This what I see on Runs tab after executed the command cy:run > https://www.screencast.com/t/iOliOq7hH
My dashboard after running cy:run > https://www.screencast.com/t/g7mcohuJ

I installed Cypress version 3.1.5

I can see the video file created on the videos folder after I run the script.

Here are the settings:
{
animationDistanceThreshold: 5,
baseUrl: null,
blacklistHosts: null,
chromeWebSecurity: false,
defaultCommandTimeout: 4000,
env: {},
execTimeout: 1000000,
fileServerFolder: '',
fixturesFolder: 'cypress/fixtures',
hosts: null,
integrationFolder: 'cypress/integration',
modifyObstructiveCode: true,
numTestsKeptInMemory: 50,
pageLoadTimeout: 100000,
pluginsFile: 'cypress/plugins',
port: null,
reporter: 'spec',
reporterOptions: null,
requestTimeout: 5000,
responseTimeout: 30000,
screenshotsFolder: 'cypress/screenshots',
supportFile: 'cypress/support',
taskTimeout: 60000,
testFiles: '**/*.*',
trashAssetsBeforeRuns: true,
userAgent: null,
video: true,
videoCompression: 32,
videoUploadOnPasses: true,
videosFolder: 'cypress/videos',
viewportHeight: 660,
viewportWidth: 1000,
waitForAnimations: true,
watchForFileChanges: true}

Can anyone help me?

Cheers.

**Comment by bahmutov** [comment]
@MarcoAmaralQA can you check please, are you running **exactly** the command as you have written it?
```
npm run cy:run --record --key XXX
```

When you run NPM scripts you HAVE to separate arguments to the _tool_ with `--`, so the command has to be
```
npm run cy:run -- --record --key XXX
```

**Comment by MarcoAmaralQA** [comment]
@bahmutov,

If I run > npm run cy:run --record --key xxx --spec 'path\to\file' it runs but it does not upload the file after it finishes.

If I run > .\node_modules\.bin\cypress run --record --key xxx --spec 'path\to\file' it runs and uploads the file after it finishes.

I ran > npm run cy:run -- --record --key XXX --spec 'path\to\file' and it worked.

Cheers.

**Comment by bahmutov** [comment]
so when running `npm run cy:run --record --key xxx` it was "swallowing" `--record` and passing other flags, so Cypress ran everything but without recording. We are thinking how to solve it in user-friendly manner in proposal #3470 but this issue is resolved 🎉

**Comment by gracesianturi** [comment]
Hello , I have a problem when i run the cypress dashboard. I installed Cypress 3.4.0 via NPM. When i use record key to run the dashboard "cypress run --record --key XXX" , the result is "Please reinstall Cypress by running : cypress install . And Cypress version 3.2.0.
when i run the key, no files uploaded to dashboard. Can anyone help me? Thank you
