### ISSUE TITLE
Cypress doesn't update script bundles when watchForFileChanges is false

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#347]
Due to the changes made while adding babel/module support, having `watchForFileChanges` set to `false` will cause the the produced bundles (support + tests) not to update when files change. Need to update the logic so that files are still watched and the bundles updated, but the UI isn't notified on change.

**Comment by brian-mann** [comment]
Fixed in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).
