### ISSUE TITLE
Try to catch "npm run" arguments without "--"

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3470]
Sometimes our users forget that NPM run script needs command line arguments _to the tool_ separated from the NPM's own arguments with `--`. For example, see #3467

We have a warning in our docs about it, and should put the warning in more places https://github.com/cypress-io/cypress-documentation/issues/1418 but I think we can help users even in the current situation.

Here is how. Imagine we have `index.js` that just prints command line arguments
```js
console.log('all args', process.argv)
```
and we have NPM script in `package.json`
```json
{
  "scripts": {
    "test": "node ."
  }
}
```

Here is what happens when running script directly vs through `npm run test`

Calling directly with arguments

```sh
$ node . --foo bar
all args [ '/Users/gleb/.nvm/versions/node/v10.13.0/bin/node',
  '/Users/gleb/git/training/node/test-npm-params',
  '--foo',
  'bar' ]
```

Calling via NPM script `npm test`

```json
{
  "scripts": {
    "test": "node ."
  }
}
```

```sh
$ npm test --foo bar

> test-npm-params@1.0.0 test /Users/gleb/git/training/node/test-npm-params
> node . "bar"

all args [ '/Users/gleb/.nvm/versions/node/v10.13.0/bin/node',
  '/Users/gleb/git/training/node/test-npm-params',
  'bar' ]
```

So we are losing "run" command.

## But

If we prince `process.env` we can find the original command line arguments in NPM variable `npm_config_argv` passed as a string

```
npm_config_argv:
   '{"remain":["bar"],"cooked":["test","--foo","bar"],
   "original":["test","--foo","bar"]}',
```

## Idea

In our Cypress CLI module, whenever we get an unknown command (because instead of `open` or `run` we see something like `--record`), we take a look at `npm_config_argv original` list of arguments, load user's `package.json`, if the first argument matches the script name like "test" we know the user forgot to add `--`, and in that case we can take the rest of the `npm_config_argv original` arguments as the real CLI arguments the user meant to use.

**Comment by brian-mann** [comment]
Yarn also does this by default, it doesn't need the `--` and we could actually do the same without even warning the user.

**Comment by bahmutov** [comment]
I would still warn the user since this so custom and against what the NPM does, they should be aware that this is non-standard feature we are doing.
