### ISSUE TITLE
Non english characters (Korean) encoding is broken

### ISSUE THREAD

**Issue by say8425** [cypress-io/cypress#3479]
![cypress-screenshot](https://user-images.githubusercontent.com/3258867/52840970-4365f700-313e-11e9-9a30-d9588114c71c.png)
Hello. My cypress test is works very well in local. But on the CircleCI, all of non english characters(Korean, hangul, 한글) are broke out. So I change browser from electron to chrome69 browser but it was broke out again. Is this issue caused by the CircleCI machine? or Cypress Orb browser? Thanks.

**Comment by jennifer-shehane** [comment]
Hey @say8425, could you provide a reproducible example? 

When I paste in these characters, I am able to see them render in Electron and Chrome, so I cannot reproduce. 

Do you have use any special encoding on the html? 
Do you have the proper fonts installed on your container?

**Comment by bahmutov** [comment]
I think this is the problem with fonts missing on Linux

**Comment by junghanChoi** [comment]
Korean web pages uses euc-kr Encoding. 
I visited www.naver.com using cypress.
The encoding was broken. 
Is there a way to set encoding in cypress?

**Comment by jennifer-shehane** [comment]
Thank you @junghanChoi, this site does exhibit the problem with the encoding.

Visiting https://news.naver.com/ within Cypress browser (any browser)

<img width="1124" alt="Screen Shot 2019-04-18 at 2 00 12 PM" src="https://user-images.githubusercontent.com/1271364/56344021-65cdcc80-61e2-11e9-9629-795a5ec4e64d.png">

Visiting https://news.naver.com/ outside of Cypress

<img width="1101" alt="Screen Shot 2019-04-18 at 2 00 01 PM" src="https://user-images.githubusercontent.com/1271364/56344031-6fefcb00-61e2-11e9-83d0-d2140ed3050c.png">

**Comment by junghanChoi** [comment]
Is it possible to add supported language of chrome runner in cypress?
I tried to add Korean in language setting in the chrome which opened by cypress. But It seemed not possible.
