### ISSUE TITLE
supportFile does not work for symlinked paths

### ISSUE THREAD

**Issue by ben8p** [cypress-io/cypress#3482]
### Current behavior:

When `supportFile` is pointing to a symlinked path we get the error "Your supportFile is set to /whatever/support/index.js/index.js"
Where the "index.js" is repeated

### Desired behavior:

`supportFile` should support symlinked paths

### Steps to reproduce: (app code and test code)

- Create the structure "foo/support/index.js"
- Create the a symlink "bar" linking to "foo"
- Set cypress `supportFile` configuration to "bar/support/index.js"
- Observe the error

### Versions

Cypress 3.1.5
Node 11.6.0
Linux Ubuntu 18.04

### Additional info
The cause of the problem is https://github.com/cypress-io/cypress/blob/ce3ab55f72527374cfa2a1b942dffedb5d1a232f/packages/server/lib/config.coffee#L367

It assume `sf` is a path and does not contain the filename.

But that is incorrect. `sf` is resolved to the full path, including `index.js`.

The line should probably become `obj.supportFile = path.join(path.dirname(sf), path.basename(obj.supportFile))`

**Comment by marieram** [comment]
Hey, I can change this.

**Comment by jennifer-shehane** [comment]
@marieram Great! Let us know if you have any questions on [contributing](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by tzolnai** [comment]
Any progress on this issue? I experienced the same problem with Cypress 4.5.0.
