### ISSUE TITLE
Request: pointerLock support

### ISSUE THREAD

**Issue by kevinSuttle** [cypress-io/cypress#3486]
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

### Current behavior:
Right now, it's not possible to use `trigger()` or any Cypress API for this, because the `pointerLock` API temporarily "freezes" the usual mouse event coordinate properties (`clientX`, `screenX`, etc). Instead, it adds 2 new properties: `movementX` and `movementY`.

### Desired behavior:
Would love to be able to simulate interactions that leverage `pointerLock`, e.g. alt-clicking to enter `pointerLock`, then dragging.

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
