### ISSUE TITLE
Error: Cannot find module 'fsevents' Windows

### ISSUE THREAD

**Issue by darasandeep91** [cypress-io/cypress#3490]
### Current behavior:

Installing cypress and try to run the tests is throwing the error 

```
Error: Cannot find module 'fsevents' from 'C:\e2e\node_modules\chokidar\lib'
```

### Desired behavior:

Cypress should not throw the error when we try to run the tests

### Versions

 cypress : "3.1.5"
OS : Windows 10

**Comment by mkinfrared** [comment]
Did you solve ot somehow? I got exactly same issue. I checked my node_modules and it's there

**Comment by jennifer-shehane** [comment]
To narrow down the possible causes, could you run Cypress in our [latest version](https://on.cypress.io/changelog)?

Also try running [npm prune](https://docs.npmjs.com/cli/prune.html) `npm i`.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by smrtyviks87** [comment]
Did anyone find solution to this issue , i am also facing same issue and not able to use cucumber with cypress
Log:
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/i is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397       oneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:4944) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.oneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:4944) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
GET /__/ 200 10.153 ms - -
GET /__cypress/runner/cypress_runner.css 200 3.741 ms - -
GET /__cypress/runner/cypress_runner.js 200 1.907 ms - -
GET /__cypress/iframes/integration/test.feature 200 3.077 ms - 737
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 1.162 ms - 76120
Can't walk dependency graph: Cannot find module 'fsevents' from 'C:\Users\Username\Documents\TestRepo\node_modules\cypress-cucumber-preprocessor\node_modules\chokidar\lib'
    required by C:\Users\Username\Documents\TestRepo\node_modules\cypress-cucumber-preprocessor\node_modules\chokidar\lib\fsevents-handler.js
GET /__cypress/tests?p=cypress%5Cintegration%5Ctest.feature-456 200 10642.939 ms - 442
GET /__cypress/tests?p=cypress%5Csupport%5Cindex.js-528 200 25707.495 ms - -
GET /__/ 200 1.117 ms - -
GET /__cypress/runner/cypress_runner.css 200 14.035 ms - -
GET /__cypress/runner/cypress_runner.js 200 566.768 ms - -
GET /__cypress/iframes/integration/test.feature 200 1.156 ms - 737
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 8.072 ms - 76120
GET /__cypress/tests?p=cypress%5Csupport%5Cindex.js-731 200 471.134 ms - -
Can't walk dependency graph: Cannot find module 'fsevents' from 'C:\Users\Username\Documents\TestRepo\node_modules\cypress-cucumber-preprocessor\node_modules\chokidar\lib'
    required by C:\Users\Username\Documents\TestRepo\node_modules\cypress-cucumber-preprocessor\node_modules\chokidar\lib\fsevents-handler.js
GET /__cypress/tests?p=cypress%5Cintegration%5Ctest.feature-167 200 5008.548 ms - 442

**Comment by jennifer-shehane** [comment]
@smrtyviks87 Your error is being thrown from cypress-cucumber-preprocessor, I'd suggest opening an issue with their plugin.

**Comment by RicardoBastos** [comment]
look in top file, can be import same this "const { ContextReplacementPlugin } = require("webpack");"

**Comment by ScarletMcLearn** [comment]
Im getting this issue

**Comment by themizzi** [comment]
I'm having the same issue. Windows 10 with cypress 6.1.0.

**Comment by jennifer-shehane** [comment]
Please provide a reproducible example and we can reopen. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by 3746park** [comment]
was there ever a resolution to this? i'm seeing the same issue and not sure what to do :(

**Comment by compassoLeonardo** [comment]
I'm having the same trouble! Someone discovery someting?

`"cypress": "^7.7.0",
"cypress-cucumber-preprocessor": "^4.1.3",`

**Comment by arunyadhyaan** [comment]
> Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

I get the same issue. in 2021. is there any solution

**Comment by compassoLeonardo** [comment]
I was using cypress with the cucumber-preprocessor plugin and importing the wrong path in the steps implementations.
The correct importation is: 
`import {Given, When, Then, Before} from 'cypress-cucumber-preprocessor/steps'`
But I was trying without the "s" in "steps" or with slash after steps, and receiving this fsevent error.
Hope this help someone!

**Comment by elrenegado** [comment]
> I was using cypress with the cucumber-preprocessor plugin and importing the wrong path in the steps implementations.
> The correct importation is:
> `import {Given, When, Then, Before} from 'cypress-cucumber-preprocessor/steps'`
> But I was trying without the "s" in "steps" or with slash after steps, and receiving this fsevent error.
> Hope this help someone!
@compassoLeonardo 
This actually helped me out, I am very thankful for you to share this!

**Comment by Tharun038** [comment]
Hi All,  I'm also facing the same issue tried the solution given above, but, no luck. Can anyone help with this, please
Error: Can't walk dependency graph: Cannot find module 'fsevents' from 'C:\Users\Zadmin\Documents\PageObjectModel\node_modules\cypress-cucumber-preprocessor\node_modules\chokidar\lib'
    required by C:\Users\Zadmin\Documents\PageObjectModel\node_modules\cypress-cucumber-preprocessor\node_modules\chokidar\lib\fsevents-handler.js
    at C:\Users\Zadmin\Documents\PageObjectModel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Zadmin\Documents\PageObjectModel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Zadmin\Documents\PageObjectModel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Zadmin\Documents\PageObjectModel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Zadmin\Documents\PageObjectModel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Zadmin\Documents\PageObjectModel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at callback (C:\Users\Zadmin\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:183:21)

**Comment by pccwg-antonylobo** [comment]
> > I was using cypress with the cucumber-preprocessor plugin and importing the wrong path in the steps implementations.
> > The correct importation is:
> > `import {Given, When, Then, Before} from 'cypress-cucumber-preprocessor/steps'`
> > But I was trying without the "s" in "steps" or with slash after steps, and receiving this fsevent error.
> > Hope this help someone!
> > @compassoLeonardo
> > This actually helped me out, I am very thankful for you to share this!

After passing  "/steps" on cypress-cucumber-preprocessor path it worked. Thanks mate
