### ISSUE TITLE
Commands ui not printing cy.contains() with options correctly

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#35]
When I use `cy.contains()` and pass in an option:
1. if the assertion passes, the contains is not printed in the commands ui.
2. if the assertion fails, the contains is printed with a weird object.

**Example Code**
```coffee
cy .get("#dialog").within ->
  cy.contains "1 question", exist: false
  cy.contains "4 questions"
  cy.contains "1 question"
```

**Assertion passing (does not print)**
![screen shot 2015-05-06 at 12 37 00 pm](https://cloud.githubusercontent.com/assets/1271364/7498208/1dcb4366-f3ed-11e4-80aa-9e6f9ce345bf.png)

**Assertion failing**
![screen shot 2015-05-06 at 12 37 26 pm](https://cloud.githubusercontent.com/assets/1271364/7498214/23996f98-f3ed-11e4-832d-d7df1e6dc9dd.png)

**Comment by brian-mann** [comment]
Fixed in [`0.6.2`](https://github.com/cypress-io/cypress/wiki/Changelog#062-05202015).
