### ISSUE TITLE
cy.route: wait on alias does not contain all requests

### ISSUE THREAD

**Issue by Konstruktour** [cypress-io/cypress#3516]
### Current behavior:

In the following code example an "listener" is added to the `api/test` route and after a duration of 5 seconds it waits until the route has been called. During the 5 seconds multiple (non-deterministic) calls to the route are triggered, but the alias `@getTest` only contains the xhr of the first request. 
```js
cy.visit('/');
cy.server();
cy.route('GET', 'api/test').as('getTest');
cy.wait(5000);
cy.wait('@getTest')
    .then((xhr) => {
        console.log(xhr);
     });
```

### Desired behavior:
Expected behaviour would be that the alias `@getTest` contains an array of the fired requests. 
Either I did not find any solution for that or it is not (yet) implemented?

### Versions
Cypress 3.1.5

**Comment by jennifer-shehane** [comment]
A single `cy.wait()` will only wait for a single response. To wait for multiple requests, you would need to define multiple `cy.wait()` commands. 

In order to access all responses of a single alias, you can use the undocumented `.all` property. For example:

```js
cy.wait('@getTest.all')
  .should("have.length", 2)
  .then((xhrs) => {
    console.log(xhrs);
});
```

**Comment by nvkhanh08t4** [comment]
> A single `cy.wait()` will only wait for a single response. To wait for multiple requests, you would need to define multiple `cy.wait()` commands.
> 
> In order to access all responses of a single alias, you can use the undocumented `.all` property. For example:
> 
> ```js
> cy.wait('@getTest.all')
>   .should("have.length", 2)
>   .then((xhrs) => {
>     console.log(xhrs);
> });
> ```

Hi @jennifer-shehane  Can you give full example for this?

**Comment by jennifer-shehane** [comment]
@nvkhanh08t4 Please check the docs.

**Comment by jennifer-shehane** [comment]
Docs for the usage of .all syntax can be found here. It’s not officially documented because the API may change in the future. https://github.com/cypress-io/cypress-documentation/issues/1573
