### ISSUE TITLE
Can't assert jquery data

### ISSUE THREAD

**Issue by sq33G** [cypress-io/cypress#3518]
### Current behavior:

My assertion on a DOM element's jquery data is failing.

When using `Cypress.$` to access the element's data, I get an empty object `{}`. When I open Developer Tools in the browser, then select the offending element, I get this in the console:

![image](https://user-images.githubusercontent.com/5327693/52951324-2cb3e000-338a-11e9-8879-cfa4df97bbc6.png)

### Desired behavior:

I expect to be able to make assertions on jquery data for elements in the DOM

### Versions

Cypress 3.1.5
Chrome 72.0.3626.109

**Comment by jennifer-shehane** [comment]
`data` is not listed as a proxied jQuery method in [our documentation](https://on.cypress.io/$). 

You can find something by a data attribute with this syntax: `Cypress.$('[data-foo="bar"]')`
