### ISSUE TITLE
Support login via Google OAuth in Test Runner

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#3519]
Cypress recently introduced the ability to login to the [Cypress Dashboard via Google](https://www.cypress.io/blog/2019/02/12/new-feature-log-in-to-the-cypress-dashboard-via-google/). While this is great for allowing a wider audience to access the Dashboard, the lack of feature parity with the Test Runner creates some awkwardness ... the requirement for a GitHub account in order to setup a project to record to the Dashboard.

**Comment by robert-skarzycki** [comment]
It's especially confusing when you are new to Dashboard. You create an account on Dashboard with Google, then try to proceed, but you see only GitHub login popup in Test Runner. :/

**Comment by markgoho** [comment]
We're paying customers of the Dashboard service but because of this bug: #1251 we're dead in the water. I guess I'm confused as to why I'm paying for a service that doesn't allow me to use it.
