### ISSUE TITLE
move chai from window to Cypress

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3520]
it would make more sense to allow the cypress `chai` instance to be accessed via `Cypress.chai` instead of being a global.

I think we should move `chai` onto `Cypress` and deprecate `window.chai`

**Comment by bahmutov** [comment]
Yes and also at the same time we should move expect to cy.expect

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/280
