### ISSUE TITLE
Test runner does not launch on Chrome 72

### ISSUE THREAD

**Issue by MarcoAmaralQA** [cypress-io/cypress#3526]
### Is this a Feature or Bug?

Bug

### Current behavior:

When I select to execute a test using Chrome 72 the test runner does not launch here is a video > https://www.screencast.com/t/yUJuF9poxk. It stays forever stuck on Opening Chrome 72.

The test runner launches on Electron 59

### Desired behavior:

Test runner to open on Chrome.

### Versions

Version 3.1.5, Windows 10, Chrome 72

**Comment by sainthkh** [comment]
@jennifer-shehane Cypress doesn't have a clear policy about supported Web browser versions, but I guess we can safely close this issue because Chrome 72 is not on [this list](https://chromium.cypress.io/), right?
