### ISSUE TITLE
Separate dtslint into its own CircleCI job

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3527]
`dtslint` tool that checks our TypeScript definitions is often a canary in the mind, failing when `typescript@next` fails to accept our `index.d.ts` types. For clarity it would be nice to separate `dtslint` into its own CircleCI job so it is clear that the types are wrong for the future version of TypeScript, while the rest of the tests pass

**Comment by jennifer-shehane** [comment]
Open issue for `dtslint` to not use `typescript@next` https://github.com/Microsoft/dtslint/issues/159
