### ISSUE TITLE
Cypress in NixOS not working

### ISSUE THREAD

**Issue by acyuta108** [cypress-io/cypress#3530]
Cypress fails to verify, open or run in NixOS
### Current behavior:
```
$ DEBUG=cypress:* $(npm bin)/cypress open
  cypress:cli cli starts with arguments ["/nix/store/k07vwr4l3w0l2p8z385ziwfjryxcag4k-nodejs-11.7.0/bin/node","/home/acyuta/code/sbsc-crm/spec/ui/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +2ms
  cypress:cli opening Cypress +0ms
  cypress:cli parsed cli options {} +56ms
  cypress:cli opening from options {"project":"/home/acyuta/code/sbsc-crm/spec/ui"} +0ms
  cypress:cli command line arguments ["--project","/home/acyuta/code/sbsc-crm/spec/ui"] +1ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress +2ms
  cypress:cli Binary is executable? : true +2ms
  cypress:cli binaryDir is  /home/acyuta/.cache/Cypress/3.1.5/Cypress +0ms
  cypress:cli Reading binary package.json from: /home/acyuta/.cache/Cypress/3.1.5/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 3.1.5 installed in: /home/acyuta/.cache/Cypress/3.1.5/Cypress +2ms
  cypress:cli could not read binary_state.json file +3ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli running binary verification check 3.1.5 +1ms
It looks like this is your first time using Cypress: 3.1.5

  cypress:cli clearing out the verified version +2ms
  cypress:cli running smoke test +1ms
  cypress:cli using Cypress executable /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress +0ms
  cypress:cli needs XVFB? false +1ms
  cypress:cli smoke test command: /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress --smoke-test --ping=106 +0ms
  cypress:cli Smoke test failed: { Error: spawn /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress',
  path: '/home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress',
  spawnargs: [ '--smoke-test', '--ping=106' ],
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd:
   '/home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress --smoke-test --ping=106',
  timedOut: false,
  killed: false } +9ms
 ✖  Verifying Cypress can run /home/acyuta/.cache/Cypress/3.1.5/Cypress
   → Cypress Version: 3.1.5
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

spawn /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress ENOENT
----------

Platform: linux (Raspbian - 19.03pre169108.36f31600749)
Cypress Version: 3.1.5
```

### Desired behavior:
Expects to open the electron app or run specs.
Based on the backtrace I can see it fails on verifying the binary. I have attempted a cached (cypress.zip) version and the auto download and both failed.
### Steps to reproduce: (app code and test code)
```
npm i cypress
$(npm bin)/cypress open
```
### Versions

NixOS 19.03pre169108.36f31600749 (Koi)
node v11.7.0 (attempted with 8 and 10 as well)
npm 6.5.0
Chromium 72.0.3626.81 (chrome-browser returns same error)
Cypress Version: 3.1.5

Unfortunately I cannot fulfill all requirements found in https://on.cypress.io/required-dependencies since their naming is different and I cannot find similar packages for nixos at https://nixos.org/nixos/packages.html
How come it says Platform: linux (Raspbian - 19.03pre...). Could this be related to the issue?

**Comment by Bkucera** [comment]
Hi @acyuta108, could you paste what `uname -a` prints out?

**Comment by acyuta108** [comment]
Linux acyuta-nixos0 4.14.98 #1-NixOS SMP Wed Feb 6 16:31:37 UTC 2019 x86_64 GNU/Linux

**Comment by acyuta108** [comment]
I cloned the repo and running the `npm run test test/*` in packages/server and evereything fails in 
```
cd packages/test
npm test ./test/e2e/*

Error: spawn /home/acyuta/code/cypress/packages/electron/dist/Cypress/Cypress ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by flotwig** [comment]
It looks like `binary_state.json` is missing from your Cypress install dir. Try deleting your `~/.cache/Cypress` folder:

`rm -rf ~/.cache/Cypress`

and then re-install the Cypress binary with debugging enabled:

`DEBUG=cypress:* cypress install`

If this succeeds, you should be able to just use Cypress. If it doesn't succeed or fix the problem, please send us the debug logs that are produced by that installation command so we can look in to it further.

**Comment by acyuta108** [comment]
```
[acyuta@acyuta-nixos0:~/code/sbsc-crm/spec/ui]$ rm -rf ~/.cache/Cypress/

[acyuta@acyuta-nixos0:~/code/sbsc-crm/spec/ui]$ DEBUG=cypress:* npm i cypress                                                 
> cypress@3.1.5 postinstall /home/acyuta/code/sbsc-crm/spec/ui/node_modules/cypress
> node index.js --exec install

  cypress:cli installing Cypress from NPM +0ms
  cypress:cli installing with options {} +0ms
  cypress:cli version in package.json is 3.1.5 +0ms
  cypress:cli Reading binary package.json from: /home/acyuta/.cache/Cypress/3.1.5/Cypress/resources/app/package.json +0ms
  cypress:cli no binary installed under cli version +5ms
  cypress:cli checking local file /home/acyuta/code/sbsc-crm/spec/ui/3.1.5 cwd /home/acyuta/code/sbsc-crm/spec/ui/node_modules/cypress +3ms
  cypress:cli preparing to download and unzip version  3.1.5 to path /home/acyuta/.cache/Cypress/3.1.5 +1ms
Installing Cypress (version: 3.1.5)

  cypress:cli needed Cypress version: 3.1.5 +0ms
  cypress:cli downloading cypress.zip to "/tmp/cypress.zip" +0ms
  cypress:cli Downloading from https://download.cypress.io/desktop/3.1.5?platform=linux&arch=x64 +2ms
  cypress:cli Saving file to /tmp/cypress.zip +0ms
 ⠼  Downloading Cypress    
 ⠇  Downloading Cypress      100% 0s
    Unzipping Cypress      
    Finishing Installation 
  cypress:cli downloading finished +1m
  cypress:cli finished downloading file: /tmp/cypress.zip +1m
 ✔  Downloaded Cypress
 ⠇  Unzipping Cypress        100% 0s
 ✔  Downloaded Cypress
 ✔  Unzipped Cypress
 ✔  Finished Installation /home/acyuta/.cache/Cypress/3.1.5

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

+ cypress@3.1.5
updated 1 package and audited 329 packages in 125.544s
found 0 vulnerabilities


[acyuta@acyuta-nixos0:~/code/sbsc-crm/spec/ui]$ DEBUG=cypress:* ./node_modules/.bin/cypress open         
  cypress:cli cli starts with arguments ["/nix/store/k07vwr4l3w0l2p8z385ziwfjryxcag4k-nodejs-11.7.0/bin/node","/home/acyuta/code/sbsc-crm/spec/ui/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +3ms
  cypress:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +48ms
  cypress:cli opening from options {"project":"/home/acyuta/code/sbsc-crm/spec/ui"} +0ms
  cypress:cli command line arguments ["--project","/home/acyuta/code/sbsc-crm/spec/ui"] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress +2ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /home/acyuta/.cache/Cypress/3.1.5/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/acyuta/.cache/Cypress/3.1.5/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 3.1.5 installed in: /home/acyuta/.cache/Cypress/3.1.5/Cypress +2ms
  cypress:cli could not read binary_state.json file +3ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli running binary verification check 3.1.5 +0ms
It looks like this is your first time using Cypress: 3.1.5

  cypress:cli clearing out the verified version +3ms
  cypress:cli running smoke test +1ms
  cypress:cli using Cypress executable /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress +0ms
  cypress:cli needs XVFB? false +0ms
  cypress:cli smoke test command: /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress --smoke-test --ping=155 +0ms
  cypress:cli Smoke test failed: { Error: spawn /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress',
  path: '/home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress',
  spawnargs: [ '--smoke-test', '--ping=155' ],
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd:
   '/home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress --smoke-test --ping=155',
  timedOut: false,
  killed: false } +11ms
 ✖  Verifying Cypress can run /home/acyuta/.cache/Cypress/3.1.5/Cypress
   → Cypress Version: 3.1.5
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

spawn /home/acyuta/.cache/Cypress/3.1.5/Cypress/Cypress ENOENT
----------

Platform: linux (Raspbian - 19.03pre169108.36f31600749)
Cypress Version: 3.1.5
```

**Comment by acyuta108** [comment]
`ls -laR ~/.cache/Cypress/|grep binary_state.json` returns emtpy.
From what I can tell binary_state.json is written by cli/lib/tasks/verify.js which at this point on the installation has not been completed.

**Comment by acyuta108** [comment]
I'm afraid this is going to be a bit harder than I thought.
Given that spawning the binary is where is crashing, I assume it has something to do with the Electron app requirements as described in [the docs](https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies).
I looked at the Atom editor, being a prominent electron app that I know works in NixOs (I installed it and ran without any issues). In the Nix package manager, installation packages are written in nix (language) so you can look at [Atom's package configuration](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/editors/atom) which requires the default.nix and most importantly env.nix which sets up the libs required by the electron app.
Given I am a total Nix noob, I have to learn to read this config and reproduce it in my machine in order to install all the required packages. Hopefully I won't have to inject these as described in [this GH comment in the Nixos repo](https://github.com/NixOS/nixpkgs/issues/46382#issuecomment-450251972)

**Comment by acyuta108** [comment]
I am most certainly missing deps:
```
$ ldd ~/.cache/Cypress/3.1.5/Cypress/Cypress
        linux-vdso.so.1 (0x00007ffdd83dd000)
        libnode.so => /home/acyuta/.cache/Cypress/3.1.5/Cypress/libnode.so (0x00007efc75181000)
        libpthread.so.0 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/libpthread.so.0 (0x00007efc74f62000)
        libgtk-x11-2.0.so.0 => not found
        libgdk-x11-2.0.so.0 => not found
        libpangocairo-1.0.so.0 => not found
        libatk-1.0.so.0 => not found
        libcairo.so.2 => not found
        libgdk_pixbuf-2.0.so.0 => not found
        libgio-2.0.so.0 => not found
        libpango-1.0.so.0 => not found
        libgobject-2.0.so.0 => not found
        libfontconfig.so.1 => not found
        libfreetype.so.6 => not found
        libdbus-1.so.3 => not found
        libX11-xcb.so.1 => not found
        libxcb.so.1 => not found
        libXi.so.6 => not found
        libXcursor.so.1 => not found
        libXdamage.so.1 => not found
        libXrandr.so.2 => not found
        libXcomposite.so.1 => not found
        libXext.so.6 => not found
        libXfixes.so.3 => not found
        libXrender.so.1 => not found
        libX11.so.6 => not found
        libXtst.so.6 => not found
        libXss.so.1 => not found
        libgconf-2.so.4 => not found
        libgmodule-2.0.so.0 => not found
        libglib-2.0.so.0 => not found
        libnss3.so => not found
        libnssutil3.so => not found
        libsmime3.so => not found
        libnspr4.so => not found
        libffmpeg.so => /home/acyuta/.cache/Cypress/3.1.5/Cypress/libffmpeg.so (0x00007efc74ada000)
        libasound.so.2 => not found
        libcups.so.2 => not found
        librt.so.1 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/librt.so.1 (0x00007efc748d2000)
        libdl.so.2 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/libdl.so.2 (0x00007efc746ce000)
        libexpat.so.1 => not found
        libstdc++.so.6 => not found
        libm.so.6 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/libm.so.6 (0x00007efc74339000)
        libgcc_s.so.1 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/libgcc_s.so.1 (0x00007efc74123000)
        libc.so.6 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/libc.so.6 (0x00007efc73d6f000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007efc767b8000)
        libstdc++.so.6 => not found
```

**Comment by flotwig** [comment]
It looks like that atom configuration file you linked should have most, if not all, of those missing deps:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/atom/env.nix#L7

I see freetype along with a bunch of the X dependencies that you're missing in that list. Maybe you can just install them using your distro's package manager? Sorry, not too familiar with how NixOS does it.

**Comment by acyuta108** [comment]
NixOS needs to patch (patchelf) dynamic libraries' rpath to the binary in order to run it. For electron apps most people use the Atom libPath to do so, being the canonical Electron app in linux, which was successfully "ported" to NixOS. [This article](https://qiita.com/kimagure/items/6e0fd0aad389c1f274c6) is a great guide to creating a package in NixOS which requires binary patching.
I have managed to generate a working rpath to patch the Cypress binary and successfuly(!!!) run the Cypress electron app.

This is the rpath required: `/nix/store/8c8wkbivmbn5cg2x0j5cr3vwfgdrxd88-gcc-7.4.0-lib/lib:/nix/store/w93d0agbvjgvixvgzx7dyn0g7rjg8yk8-zlib-1.2.11/lib:/nix/store/v3cifqp9jh8jp6mzqps5zbxggzywcplb-glib-2.58.2/lib:/nix/store/hmwlixqf216ywyr6b4p7pmsrd88lydwb-dbus-1.12.12-lib/lib:/nix/store/cin3yxkpfi8ngd3zb9q0608ca49l08pv-gtk+3-3.24.3/lib:/nix/store/xi2qvi19qsihpfhxvpz2wslcjm9hm86h-atk-2.30.0/lib:/nix/store/6vny49qf98ln9dzfqc3la6cilf5wml9r-pango-1.42.4/lib:/nix/store/xnhgvia9spzhzhyl8cn638s63ql8pz8g-freetype-2.9.1/lib:/nix/store/a23jigg3rcvmc8k1cdsw5l58k8dhfk46-libgnome-keyring-3.12.0/lib:/nix/store/4pghs2rl63qbhygj6kc8a1q238kbqwhc-fontconfig-2.12.6-lib/lib:/nix/store/mn2x428m2lh9k469mdbpiy9fvfv3l01i-gdk-pixbuf-2.38.0/lib:/nix/store/16h4qjylqq0sfxagkiqyxkx1lrg3zz4a-cairo-1.16.0/lib:/nix/store/8apyr7cwpazss43kq2m5bmhiy7xms2rz-cups-2.2.10-lib/lib:/nix/store/vmbii8cbr2b9fkvplynpc1lb3fcrfr5d-expat-2.2.6/lib:/nix/store/757hg6zq9hdvllpxrrwjbrhaw68qbhsr-libgpg-error-1.33/lib:/nix/store/vaxw9cy9i3vfqm19h3dxb5nqh4nyd5lk-alsa-lib-1.1.7/lib:/nix/store/0pcgpng2w81f5lk3jgj0n1i25079q54q-nspr-4.20/lib:/nix/store/vxkm89gzafppbqys32rsbjri4wdrj2hl-gconf-3.2.6/lib:/nix/store/f7ydfmpds1k5dnnri4m8j9qsvgqi5ni2-nss-3.42/lib:/nix/store/wqs26g0h1rg8mi5fqy6js9571xvpr6qk-libXrender-0.9.10/lib:/nix/store/5h2bq5r40izps9n5kyc60qzlz2h6vavi-libX11-1.6.7/lib:/nix/store/n08kajfs0p2cbap7nm3l5k9a8bmm0l9v-libXext-1.3.3/lib:/nix/store/jl56zsagp7qf52iw26kh15zcx3nx7125-libXdamage-1.1.4/lib:/nix/store/fzvd140aq7m66szab9iaracybcqxp8nd-libXtst-1.2.3/lib:/nix/store/j8mml8nbaf3kk4fcgifzish5kbscqwvj-libXcomposite-0.4.4/lib:/nix/store/iarr5rn73kqvrhwgwhxxnny04v1wfz10-libXi-1.7.9/lib:/nix/store/xmqj5d4aqmi3qzcx6vflxanck61rxy36-libXfixes-5.0.3/lib:/nix/store/rwx56fs8j7z1rxdmqliqnshyvz85wh71-libXrandr-1.5.1/lib:/nix/store/4dgvw4d4b4giyxvsdyhydym1l4nkk0ra-libXcursor-1.1.15/lib:/nix/store/9vnqrvzm0vpyxv6i1j665vbm7k14vssw-libxkbfile-1.0.9/lib:/nix/store/lw6j9bvawd5yj3xww6j4r4i5465bw2zj-libXScrnSaver-1.2.3/lib:/nix/store/znsd54lsab30gyz0h1jm7426awby3y0w-libcap-2.26-lib/lib:/nix/store/8hh0lkc6y3sil6qwmlgcnp6a0q304prw-systemd-239.20190110-lib/lib:/nix/store/kimqxn1lyydb676p2p329nxc5v91b70z-libnotify-0.7.7/lib:/nix/store/3ccx7mwzlr53wl60ma21hj53s2d5hvs8-libxcb-1.13.1/lib:/nix/store/lz1vlrqmvhbzbjmwicfcz1c2kbcwv130-libsecret-0.18.7/lib:/nix/store/8c8wkbivmbn5cg2x0j5cr3vwfgdrxd88-gcc-7.4.0-lib/lib64:/nix/store/w93d0agbvjgvixvgzx7dyn0g7rjg8yk8-zlib-1.2.11/lib64:/nix/store/v3cifqp9jh8jp6mzqps5zbxggzywcplb-glib-2.58.2/lib64:/nix/store/hmwlixqf216ywyr6b4p7pmsrd88lydwb-dbus-1.12.12-lib/lib64:/nix/store/cin3yxkpfi8ngd3zb9q0608ca49l08pv-gtk+3-3.24.3/lib64:/nix/store/xi2qvi19qsihpfhxvpz2wslcjm9hm86h-atk-2.30.0/lib64:/nix/store/6vny49qf98ln9dzfqc3la6cilf5wml9r-pango-1.42.4/lib64:/nix/store/xnhgvia9spzhzhyl8cn638s63ql8pz8g-freetype-2.9.1/lib64:/nix/store/a23jigg3rcvmc8k1cdsw5l58k8dhfk46-libgnome-keyring-3.12.0/lib64:/nix/store/4pghs2rl63qbhygj6kc8a1q238kbqwhc-fontconfig-2.12.6-lib/lib64:/nix/store/mn2x428m2lh9k469mdbpiy9fvfv3l01i-gdk-pixbuf-2.38.0/lib64:/nix/store/16h4qjylqq0sfxagkiqyxkx1lrg3zz4a-cairo-1.16.0/lib64:/nix/store/8apyr7cwpazss43kq2m5bmhiy7xms2rz-cups-2.2.10-lib/lib64:/nix/store/vmbii8cbr2b9fkvplynpc1lb3fcrfr5d-expat-2.2.6/lib64:/nix/store/757hg6zq9hdvllpxrrwjbrhaw68qbhsr-libgpg-error-1.33/lib64:/nix/store/vaxw9cy9i3vfqm19h3dxb5nqh4nyd5lk-alsa-lib-1.1.7/lib64:/nix/store/0pcgpng2w81f5lk3jgj0n1i25079q54q-nspr-4.20/lib64:/nix/store/vxkm89gzafppbqys32rsbjri4wdrj2hl-gconf-3.2.6/lib64:/nix/store/f7ydfmpds1k5dnnri4m8j9qsvgqi5ni2-nss-3.42/lib64:/nix/store/wqs26g0h1rg8mi5fqy6js9571xvpr6qk-libXrender-0.9.10/lib64:/nix/store/5h2bq5r40izps9n5kyc60qzlz2h6vavi-libX11-1.6.7/lib64:/nix/store/n08kajfs0p2cbap7nm3l5k9a8bmm0l9v-libXext-1.3.3/lib64:/nix/store/jl56zsagp7qf52iw26kh15zcx3nx7125-libXdamage-1.1.4/lib64:/nix/store/fzvd140aq7m66szab9iaracybcqxp8nd-libXtst-1.2.3/lib64:/nix/store/j8mml8nbaf3kk4fcgifzish5kbscqwvj-libXcomposite-0.4.4/lib64:/nix/store/iarr5rn73kqvrhwgwhxxnny04v1wfz10-libXi-1.7.9/lib64:/nix/store/xmqj5d4aqmi3qzcx6vflxanck61rxy36-libXfixes-5.0.3/lib64:/nix/store/rwx56fs8j7z1rxdmqliqnshyvz85wh71-libXrandr-1.5.1/lib64:/nix/store/4dgvw4d4b4giyxvsdyhydym1l4nkk0ra-libXcursor-1.1.15/lib64:/nix/store/9vnqrvzm0vpyxv6i1j665vbm7k14vssw-libxkbfile-1.0.9/lib64:/nix/store/lw6j9bvawd5yj3xww6j4r4i5465bw2zj-libXScrnSaver-1.2.3/lib64:/nix/store/znsd54lsab30gyz0h1jm7426awby3y0w-libcap-2.26-lib/lib64:/nix/store/8hh0lkc6y3sil6qwmlgcnp6a0q304prw-systemd-239.20190110-lib/lib64:/nix/store/kimqxn1lyydb676p2p329nxc5v91b70z-libnotify-0.7.7/lib64:/nix/store/3ccx7mwzlr53wl60ma21hj53s2d5hvs8-libxcb-1.13.1/lib64:/nix/store/lz1vlrqmvhbzbjmwicfcz1c2kbcwv130-libsecret-0.18.7/lib64/lib:/nix/store/0yzj26lhwz44vl2zyxvmnks4b8hg1rr2-gtk+-2.24.32/lib`

I generated this rpath in my machine by running
```
nix-repl> with pkgs; lib.makeLibraryPath [ atomEnv.libPath gtk2-x11 ]
```
and appending the path to the Cypress cache (~/.cache/Cypress/3.1.5/Cypress) which includes libnode and libffmpeg.

This was a manual patch, so I need to reproduce the packaging in a nix file ([like the example](https://qiita.com/kimagure/items/6e0fd0aad389c1f274c6)) that can be used to run the installation by itself. Perhaps I'll be able to release it as a [nixpkg](https://nixos.org/nixos/packages.html#lib) and hopefully we can figure out how to incorporate it into the npm installer.

**Comment by acyuta108** [comment]
https://github.com/NixOS/nixpkgs/pull/56387 in Nixpkgs repo.

**Comment by DamienCassou** [comment]
Can this issue be closed?

**Comment by flotwig** [comment]
Looks like it. If anyone has issues using Cypress on NixOS, please open a new issue.
