### ISSUE TITLE
logging-in-single-sign-on fails on request

### ISSUE THREAD

**Issue by andrei9669** [cypress-io/cypress#3535]
### Current behavior:

when it reaches 'can authenticate with cy.request' it gives 

```
CypressError: cy.request() failed trying to load:

http://auth.corp.com:7075/login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:7075

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://auth.corp.com:7075/login

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

RequestError: Error: connect ECONNREFUSED 127.0.0.1:7075
    at new RequestError (C:\Users\ ~~redacted~~ \AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\ ~~redacted~~ \AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users ~~redacted~~ \AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\ ~~redacted~~ \AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\request\request.js:185:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (C:\Users\ ~~redacted~~ \AppData\Local\Cypress\Cache\3.1.5\Cypress\resources\app\packages\server\node_modules\request\request.js:881:8)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) 
```

I noticed that some assertions pass, the ones that go to http://localhost:7074, also I see get requests in my terminal, so my guess is that under `Common situations why this would fail:`, 1st three are okay. I also tried to run [logging-in__html-web-forms](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/logging-in__html-web-forms) and that worked without problems

### Desired behavior:

I would want to see these example tests pass

### Steps to reproduce: (app code and test code)

run tests from here, steps are included in `cypress-example-recipes`
[logging-in__single-sign-on](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__single-sign-on/) 
I'm trying to run it as is, meaning I haven't modified anything
### Versions

  cypress: 3.1.5
  OS: Windows 10
  browser: Chrome 72

**Comment by RandallKent** [comment]
Can you confirm the server supporting that example is running as documented in [Readme](https://github.com/cypress-io/cypress-example-recipes)?

From within the directory you cloned [`cypress-example-recipes`](https://github.com/cypress-io/cypress-example-recipes) to run these commands:
```bash
cd ./examples/logging-in__single-sign-on
# start local server
npm start &
# and open Cypress GUI
npm run cypress:open
```

**Comment by andrei9669** [comment]
couldn't find where specifically it is written in Readme, but the server is responding to Cypress' requests
```
D:\stuff\cypress examples\cypress-example-recipes-master\examples\logging-in__single-sign-on>npm start &

> logging-in-single-sign-on@1.0.0 start D:\stuff\cypress examples\cypress-example-recipes-master\examples\logging-in__single-sign-on
> node app_server.js --port 7074 & node auth_server.js --port 7075

GET /dashboard 302 24.728 ms - 70
GET /unauthorized 200 611.452 ms - 293
GET / 200 46.091 ms - 1098
```

not sure what you mean by that second part, but I cloned whole ` cypress-io/cypress-example-recipes ` directory and then ran ` npm start & ` in ` examples/logging-in__single-sign-on ` and then ` npx cypress open ` in separate cmd

I hope I did it correctly

**Comment by RandallKent** [comment]
Are your running Cypress from within `examples/logging-in__single-sign-on`?

It will load the `cypress.json` ensuring `auth.corp.com` points to localhost.

**Comment by andrei9669** [comment]
yes, I'm running it within ` examples/logging-in__single-sign-on `
```
D:\stuff\cypress examples\cypress-example-recipes-master\examples\logging-in__single-sign-on>npx cypress open 
```

**Comment by RandallKent** [comment]
Can you share a screenshot/video showing the configuration under the settings tab of the Cypress Test Runner as well as the tests failing?

**Comment by andrei9669** [comment]
![image](https://user-images.githubusercontent.com/31692094/53786657-09119d80-3f25-11e9-97e6-088e6d07ee63.png)
tests that are failing are `can authenticate with cy.request` and `can parse out id_token and set on local storage`
error messages are both same as in OP

**Comment by ZachMcCorkhill** [comment]
I'm having this same issue. Because of our network settings, my localhost IP is 10.205.164.28, not the 127.0.0.1 default, so I changed that in my cypress.json file.  @andrei9669 - did you check that your localhost IP is the default and/or did you get this working? 
You can see I have it set in the Cypress settings tab image below. When I visit http://10.205.164.28:7074/ I see the index.html file, so I know my server is running. But I get the same "request failed without a response" message.
![Annotation 2019-08-09 083115](https://user-images.githubusercontent.com/52940302/62790489-1b69a780-ba80-11e9-9982-6a537015b357.png)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by IvyTheBrewer** [comment]
We ran into the same issue working in a corporate environment. Setting "corp.com" in the NO_PROXY environment variable solved the issue for us.

**Comment by ayubkhanz** [comment]
Could you guys open this please and find some solution.
