### ISSUE TITLE
Cant get past the IBM bluemix login

### ISSUE THREAD

**Issue by kthulsidoss** [cypress-io/cypress#3539]
Hi , tried a simple script to login to blue mix .. get the form & click the button. It does not get past that screen. Can cypress handle complex ones like blue mix ?

**Comment by kthulsidoss** [comment]
// cypress/integration/bluemixlogin.spec.js
describe('login', () => {
    beforeEach(() => {
        visitBlueMixLoginPage()
    })

    it('A User logs in and sees a welcome message', () => {
        loginWith('kthulsidoss@in.ibm.com')

        expect(cy.contains(' IBM Cloud')).toBeTruthy
})


})

const visitBlueMixLoginPage = () => {
    cy.visit('https://console.test.cloud.ibm.com/login')
}

const loginWith = (email) => {
    cy.get('[name="userid"]').type(email)
    //cy.get('[name="password"]').type(password)
    cy.get('button').click()
}
const logout = () => {
    cy.get('button').click()
}

**Comment by jennifer-shehane** [comment]
Testing login pages are unfortunately one of the more complex pages to test due to the frequent use of third party systems being involved for security. 

There's a pretty good talk with some advice on testing login pages [here](https://www.youtube.com/watch?v=5XQOK0v_YRE) and also a tutorial on testing logging in through Auth0 [here](https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/).

It's a bit difficult to give general advice since every login is quite different.

If you can, please detail the error you are encountering in this test + screenshots, etc.

**Comment by kthulsidoss** [comment]
@jennifer-shehane  thanks for looking at this defect , appreciate your time . The issue is that it does not proceed back to the next page after login(it simply needs to proceed to next level of authentication). There is a brief communication with ibm blue mix and returns back to the login page.

**Comment by kthulsidoss** [comment]
@jennifer-shehane  as i'm evaluating browser automation tools for IBM , it would be good to get some assistance on this hiccup. Can we try doing a small web meeting to overcome this ?
I would be thankful

**Comment by kthulsidoss** [comment]
<img width="960" alt="samepagelogin" src="https://user-images.githubusercontent.com/42998906/53151891-316ed300-35da-11e9-8d1e-7081ac6b7334.png">

**Comment by kthulsidoss** [comment]
@jennifer-shehane  i could not go further with https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/ mostly i believe we dont use that ,how ever i could take some thing from there . But how to know what token are being set ? how does one do that ? thanks a lot

**Comment by jennifer-shehane** [comment]
Hey @kthulsidoss, send us an email at support@cypress.io - we can discuss scheduling a web meeting there.

**Comment by jennifer-shehane** [comment]
We released [`cy.session()`](https://on.cypress.io/session) as an experimental command (set `experimentalSessionSupport` to `true` in config) in Cypress 8.2.0. This command can be used to cache and restore cookies, `localStorage`, and `sessionStorage`. We especially see this command as being useful for testing Auth flows and recommend giving it a try to replace your existing tests around authentication and login.

If you have any feedback about `cy.session()` for general UX improvements, new features, or unexpected behavior, please leave your feedback in our [Cypress Session Experimental Feedback Discussion](https://github.com/cypress-io/cypress/discussions/17887).

**Comment by AtofStryker** [comment]
Hi @kthulsidoss. Would you be able to try this with Cypress `10.11.0` and up? This should work with the `experimentalSessionAndOrigin` flag enabled with the following code:

```
describe("login", () => {
  it("A User logs in and sees a welcome message", () => {
    // establish a baseUrl
    cy.visit('https://docs.cypress.io')
    // now do a cross origin navigation
    cy.visit('https://console.test.cloud.ibm.com/login');
    cy.origin('https://test.cloud.ibm.com', () => {
      cy.get('#userid').type("kthulsidoss@in.ibm.com");
      cy.get('button[name="login"]:visible').click();
      cy.get('[analytics-errormessage="Realm check fetch error"]').should('contain.text', 'We are unable to validate your ID. Please try again later.')
    })
  });
});
```

https://user-images.githubusercontent.com/3980464/202570340-0381332d-4a41-4c9b-9bd2-65d70cd2a283.mp4

I am going to close as I believe this is no longer an issue, but please let me know if you continue to run into issues!
