### ISSUE TITLE
Cypress only runs the first test in my test suite

### ISSUE THREAD

**Issue by theshumanator** [cypress-io/cypress#3542]
### Current behavior:

Cypress only runs the first test in my test suite. It doesn't stop but keeps going (the time keeps going but it doesn't proceed to the next test).

Here are the contents of my spec file (I stored it inside the integration folder):

```js
describe('', () => {
    it('Healthcheck ', () => {
        cy.visit('');
    })
    it('Create good user', () => {
        expect(true).to.be.true
    })
})

```
I run `npx cypress open` and get the error below (when I have the console/inspect open in Chrome):
```
cypress_runner.js:63787 Uncaught TypeError: Cannot read property 'parent' of null
    at Runner._runner.hook (cypress_runner.js:63787)
    at next (cypress_runner.js:30815)
    at cypress_runner.js:30822
    at fn (cypress_runner.js:63781)
    at next (cypress_runner.js:30754)
    at cypress_runner.js:30790
    at timeslice (cypress_runner.js:26031)
```

From cmd line, I notice: `HEAD / 500 29.359 ms - -`

To run the second test ('create good use..'), I need to put `it.only` on it and then stop the tests (from the cypress app not chrome because it doesn't work in chrome) and then re-run the test (by selecting my spec file).

By the way, this issue also occurs when I run: `npx cypress run`.

### Desired behavior:

Cypress should be able to run all tests in the suite without having to put it.only and stopping/restarting the tests. It seems to be somewhat of an intermittent issue too.

### Steps to reproduce: (app code and test code)

Create a new file in the integration folder called `something.spec.js`.

Paste the following code:
```js
describe('', () => {
    it('Healthcheck ', () => {
        cy.visit('');
    })
    it('Create good user', () => {
        expect(true).to.be.true
    })
})

```

Start cypress using: `npx cypress open`

Choose the test from the cypress app and watch the behaviour. If it works the first time round, amend the test suite a little then save and observe. The second test will NOT run again.

### Versions

Cypress 3.1.5 - I have tried re-installing it multiple times and it still doesn't work.
Chrome 72 (but replicated the issue in Electron 59 too).
OS: mac

**Comment by jennifer-shehane** [comment]
Can verify this behavior with the test code provided above:

<img width="436" alt="screen shot 2019-02-21 at 8 35 36 pm" src="https://user-images.githubusercontent.com/1271364/53174491-52eeaf80-3618-11e9-93da-a732900c2feb.png">

This is caused by passing an empty string as the first argument passed to `describe`. 

The code is erroring here because `getTest()` returns `null`.

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/runner.coffee#L301

I think that we should handle this situation, or at least throw a better error message. 

Is there is a reason you are not defining any text in the `describe`? We'd like to know your use case.

**Comment by theshumanator** [comment]
Ohhh... it was a dummy test to try out Cypress. I'll remember to include something in the describe. Thank you for your response.

Yep a clearer error message will be helpful :)

**Comment by jfuston** [comment]
This was also happening for me in 3.3.2 and 3.4.1

Our use case was a test file that was not using `describe()` or `context()` and instead opting for descriptive test names. Our layout was something like below:
```
beforeEach(() => );
afterEach(() => );

it('', () => );
it('', () => );
it('', () => );
...
```

I'm guessing cypress/mocha wraps test files in a `describe` or `context` with no name which causes similar behavior to the described issue?

**Comment by intellix** [comment]
**3.4.1:**

I get 0 tests discovered when I have this: 
```ts
it('should not hit the cloudflare access page', () => {
  cy.visit('/login');
  cy.location('host').should('not.include', 'cloudflareaccess.com');
});
```

When I have this, it works:
```ts
it('should not hit the cloudflare access page', () => {
  cy.visit('/login');
  cy.location().then(location => {
    location.host.should('not.include', 'cloudflareaccess.com');
  });
});
```

Using:

```ts
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = function(on, config) {
  on('file:preprocessor', preprocessTypescript(config));
};
```

Extremely frustrating cause nothing happens for about 10 minutes.... and then it suddenly kicks in with no tests detected and Cypress.app just dies along with the error message in it.

**Comment by RakheeC** [comment]
Hi I am having some issues, when there are 2 tests in my suite after running first tests it just comes out of test runner/ dom snapshot and shows my app under test.

**Comment by RakheeC** [comment]
I figured out. I think the issue is with cross domain cookies. I have to login for both tests, once first test is done, cypress can not login for 2nd test. I there a way to clear cross domain Cookies?

**Comment by flotwig** [comment]
@RakheeC currently, Cypress only automatically clears cookies for the current domain at the end of the test. 

Does this work?

```js
beforeEach(() => {
  // clear cookies for all domains
  cy.clearCookies({ domain: null })
})
```

**Comment by RakheeC** [comment]
Thanks @flotwig I will try this

**Comment by RakheeC** [comment]
@flotwig still does not work.

**Comment by jennifer-shehane** [comment]
The original issue described has been fixed. This no longer errors in Cypress 5.0.
