### ISSUE TITLE
cy.wrap($el) times out with error: obj.is is not a function

### ISSUE THREAD

**Issue by andezzat** [cypress-io/cypress#3549]
### Current behavior:

If you attempt to grab the children of an element & loop through them and start making should assertions after wrapping them, it seems that 'contain' assertions do not work unless you issue a different assertion or command on the wrapped element beforehand.

```
Command:  wrap
Error:    CypressError: Timed out retrying: obj.is is not a function
```

### Desired behavior:

You should be able to just do a `cy.wrap(childEl).should('contain', 'some text')` with no prior commands or assertions.

#### Spec
```js
describe('should fail', () => {
  it('fails when asserting a wrapped child el', () => cy
    .visit('index.html')
    .get('.my-el')
    .children()
    .then(children => cy.wrap(children[0]).should('contain', 'This should fail...')));

  it('passes when asserting the el itself', () => cy
    .visit('index.html')
    .get('.my-el h1')
    .then($el => cy.wrap($el).should('contain', 'This should fail...')));

  it('passes when asserting the wrapped child el AFTER scrollIntoView', () => cy
    .visit('index.html')
    .get('.my-el')
    .children()
    .then(children => cy.wrap(children[0]).scrollIntoView().should('contain', 'This should fail...')));
});
```

#### Page
```html
<html lang="en">
  <head>
    <title>Hello World</title>
  </head>
  <body>
    <div class="my-el">
      <h1>This should fail...</h1>
      <p>words</p>
    </div>
  </body>
</html>
```

### Versions
Electron 59
Cypress 3.1.5
macOS 10.14.2

**Comment by jennifer-shehane** [comment]
Hey, this issue does not occur with using only `cy.wrap().should()`

**Works**
```js
it('wrap should', function () {
  cy.visit('https://example.cypress.io')
  cy.get('h1').then(($el) => {
    cy.wrap($el).should('contain', 'Kitchen Sink')
  })
})
```

Could you reduce your test code to the smallest amount possible to recreate the error?

**Comment by andezzat** [comment]
@jennifer-shehane Fair call.
I've reduced the test case to the barebone now.

**Comment by jennifer-shehane** [comment]
Hey @andezzat, thanks for updating your example. 

I have created a simpler example to demonstrate this behavior below.

```js
it('should not error when asserting on non jQuery el', () => {
  cy.visit('https://example.cypress.io')
  cy.get('.navbar').then(($nav) => {
    cy.wrap($nav[0]).should('contain', 'cypress')
  })
})
```

<img width="400" alt="screen shot 2019-02-21 at 7 23 13 pm" src="https://user-images.githubusercontent.com/1271364/53170286-2897f480-360e-11e9-8211-930bba71b34d.png">

Cypress is assuming that the element yielded from the wrap here is a jQuery element, but you have yielded a simple JavaScript DOM element. This should work fine, but we try to call a function that does not exist. 

I've opened a PR here to fix this: https://github.com/cypress-io/cypress/pull/3553

**Workaround**

For now, update your tests so that the element yielded from `cy.wrap()` is a jQuery element, so wrap the normal element with `Cypress.$()`:

```js
describe('should fail', () => {
  it('fails when asserting a wrapped child el', () => cy
    .visit('index.html')
    .get('.my-el')
    .children()
    .then(children => cy.wrap(Cypress.$(children[0])).should('contain', 'This should fail...')));

  it('passes when asserting the el itself', () => cy
    .visit('index.html')
    .get('.my-el h1')
    .then($el => cy.wrap($el).should('contain', 'This should fail...')));

  it('passes when asserting the wrapped child el AFTER scrollIntoView', () => cy
    .visit('index.html')
    .get('.my-el')
    .children()
    .then(children => cy.wrap(Cypress.$(children[0])).scrollIntoView().should('contain', 'This should fail...')));
});
```

**Comment by andezzat** [comment]
@jennifer-shehane Ahh, this makes sense to me now!
I thought something might be different between els yielded from `cy.get` and those from `cy.children`.
Thanks for showing me a workaround too, it should suffice for the time being!
