### ISSUE TITLE
Retrying commands should take into account page load

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#355]
Currently, we will pause command execution between finished commands if we detected a `page load` event.

However this doesn't take into account current running / retrying commands. If the command has already started, we are not properly queueing the retry once the `page load` event occurs.

In other words, a currently executing command will run to completion even if a `page load` was detecting in one of its retry loops.

Additionally we'll have to somehow factor in the total timeout so when the command retries it does not include the previous duration of the timeout.

**Comment by jennifer-shehane** [comment]
@brian-mann Is this still the current behavior within Cypress commands?

**Comment by jennifer-shehane** [comment]
Closing as resolved.
