### ISSUE TITLE
Browser Timeout while running tests in chrome headless mode

### ISSUE THREAD

**Issue by immohsin** [cypress-io/cypress#3552]
Not getting answers on chat, so putting up the issue here as this blocking me on adding more tests.

### Current behavior:
Under `plugins/index.js` i have put up `args.push('--headless')` for chrome browser to run headlessly. 

When i run the command `$(npm bin)/cypress run --browser chrome`. Its throwing me timeout error. 

<img width="894" alt="screen shot 2019-02-21 at 3 58 33 pm" src="https://user-images.githubusercontent.com/14070273/53162239-9f72c480-35f1-11e9-81f0-6d2fdff379bb.png">

### Desired behavior:
Should run all tests on chrome in headless manner

When i execute the above command it should run the tests in headless manner without any issue.

If headless for chrome is not supported then how do i run the tests on kubernets cluster?

### Versions
3.1.5

### operating system &  browser 
macos high sierra, Chrome 72

**Comment by jennifer-shehane** [comment]
Running headless Chrome is not supported yet. See this issue: https://github.com/cypress-io/cypress/issues/488
