### ISSUE TITLE
Cypress-bot adds and remove this same labels

### ISSUE THREAD

**Issue by Saibamen** [cypress-io/cypress#3557]
Spotted in https://github.com/cypress-io/cypress/issues/3540

![obraz](https://user-images.githubusercontent.com/905878/53191658-4a8c7980-3604-11e9-8752-22f36b368460.png)

**Comment by bahmutov** [comment]
I believe cypress bot is doing the right thing but github is grouping related updates into a single message

**Comment by Saibamen** [comment]
Request sent to GitHub by https://github.com/contact

**Comment by Saibamen** [comment]
Answer from GitHub:
>Hey Adam,
>
>Thank you for writing in to GitHub Support!
>
>We do have an open bug report to correct the way we currently group Issue events. The grouping sometimes doesn't quite work the way it should.
>
>I'm not sure when we'll have a fix in place but I've added your feedback to the existing report.
>
>We'll be back in touch with any updates to our progress.
>
>Cheers
>Stacey

**Comment by Saibamen** [comment]
Closing issue - this is GitHub bug
