### ISSUE TITLE
Add assertions for selection position

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3558]
### Current behavior:

I can't find any assertions in the docs that check the selected text range.

### Desired behavior:

Maybe something like this:

```
cy.get('input[type=text]').should('have.selectionStart', 0).and('have.selectionEnd', 10);
```

Or maybe:

```
cy.get('input[type=text]').should('have.selection', 'foo');
```

Right now I'm doing this, which works but is a bit more verbose than I'd like:

```
cy.get('input[type=text]').then($el => {
  expect($el[0].selectionStart).to.be.equal(0);
  expect($el[0].selectionEnd).to.be.equal(10);
});
```

### Versions

3.1.5

**Comment by flotwig** [comment]
Hey ~~the Cheat~~ @fr0,

First of all, I love your avatar. :) Second of all, there is a slightly more condensed way to do this using the [`have.prop` assertion](https://docs.cypress.io/guides/references/assertions.html#Chai-jQuery), which asserts on the properties of a DOM object:

```javascript
cy.get('textarea').should('have.prop', 'selectionStart', 0).and('have.prop', 'selectionEnd', 10)
```

**Comment by fr0** [comment]
Excellent, that does help. Thanks!
