### ISSUE TITLE
Upgrade to the latest version of Electron

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#3568]
Currently, Cypress uses Electron 2.0.18. The latest stable release is 6.0.4. This will bring along features and breaking changes from [2.x](https://electronjs.org/releases/stable?version=2&page=4#2.0.0), [3.x](https://electronjs.org/releases/stable?version=3&page=5#3.0.0), and [4.x](https://electronjs.org/releases/stable?version=4&page=2#4.0.0). The biggest changes that will affect users are:

* Upgrade Chromium to 76
* Upgrade Node.js to 12.4.0
* [Drop support for OSX 10.9 and below](https://electronjs.org/blog/electron-4-0#no-more-macos-109-support) (breaking change)

As part of this upgrade, we should also enable the right-click context menu in the Electron browser. It was disabled due to an issue in the previous version that caused Cypress to crash, but is likely fixed now.

Related:

* #1746 (not the main issue, but will add lookbehind regex support) 
* #2559
* #2253 
* #4394
* #4763 (removes need for workaround)
* #4433

**Comment by mitar** [comment]
Do you think you could explore also flags I mention #3633 as you are upgrading to new Electron/Chrome? Since Chrome 65 there is an option `--disable-dev-shm-usage` which would fix issues when running Cypress inside Docker. I think with upgrade to new Electron this option becomes available.

**Comment by benmonro** [comment]
i got here by clicking on 3 separate issues "closing in favor of <link to 2.0 update>" => "closing in favor of <link to 3.0 update>" => "closing in favor of <link to this 4.x update>"

in the meantime, cypress is using electron browser on version 59.  is there any way I can force it to use a newer build of electron?

As it stands right now, I get an error that only seems to happen in older chromium builds: ``` Cookie length should be less than or equal to 4096 characters.``` from a service I don't control.  is there either A) a work around for that or B) a work around for that?


thanks in advance
-Ben

**Comment by jennifer-shehane** [comment]
@benmonro Please read this issue in response to your question https://github.com/cypress-io/cypress/issues/3228

**Comment by benmonro** [comment]
@jennifer-shehane thank you for that but then I can't run headless in CI right?

**Comment by brandonb927** [comment]
@benmonro You can use the Cypress Docker images in CI for a particular version of Chrome https://github.com/cypress-io/cypress-docker-images

**Comment by miniak** [comment]
I am one of the Electron maintainers. Do you need any help with the update? Electron 1.8 is not supported anymore. You should move to a supported version if possible. Electron 3 could be an option as well as it still supports OS X 10.9.

**Comment by miniak** [comment]
You should also target the latest Electron 4 release, which is 4.1.3 at this time, to make sure you have all the latest security fixes.

**Comment by bahmutov** [comment]
Thank you @miniak for the offer, @chrisbreiding is there a way we can use Milan's expertise to help out?

**Comment by chrisbreiding** [comment]
@miniak Any help would be greatly appreciated. I'm incrementally upgrading Electron and working to fix issues along the way. There are [many failing tests related to upgrading to Electron 3](https://github.com/cypress-io/cypress/pull/3569), a lot because of [EPIPE](https://circleci.com/gh/cypress-io/cypress/91902?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and [ECONNRESET](https://circleci.com/gh/cypress-io/cypress/91897?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) errors. Do you have any ideas what could be the root cause?

Thanks for the tip about the latest version. We'll make sure we're on the latest before we get this merged.

**Comment by miniak** [comment]
Those failing tests could be caused by upgraded Node.js inside of Electron

**Comment by joeljeske** [comment]
Any update on this? I would very much like to use the latest version.

**Comment by eliranskyline** [comment]
after upgrading cypress to the latest **(v3.3.1)**, **Electron v61** does not support `mapbox.js`.
The thing is, that it used to work until `mapbox.js` have upgraded their library.
are you guys planning on fixing this issue any time soon?
tnx

**Comment by dyymmi** [comment]
Hi! I have the same issue as described above and probably updating electron will solve this problem. Can we get at least a rough estimate when can we expect this? Is it days, weeks, months? Just want to know if I should look for another solution or just wait patiently for some time.
Thanks

**Comment by benmonro** [comment]
@dyymmi I switched to test Cafe because of this issue and others with does and have been very happy.  I've found it to be very consistent across local Dev and CI plus it inherently supports every browser you can think of.

**Comment by warrenca** [comment]
> after upgrading to the latest cypress version **(v3.3.1)**, **Electron v61** does not support `mapbox.js`.
> The thing is, that it used to work until `mapbox.js` have upgraded their library.
> are you guys planning on fixing this issue any time soon?
> tnx

@eliranskyline I've encountered an issue where mapbox is not loading on first load. After the first page load, I did a `cy.reload();` to reload the whole page again, after that mapbox is displaying properly. Hope it works for you.

**Comment by jpike88** [comment]
Some es6 syntax breaks in latest cypress. Is there an ETA on when an alpha or something will be available?

**Comment by jennifer-shehane** [comment]
There is work being done every single day to get this upgrade out. There are a lot of breaking changes we are sorting out, upgrading version by version. See https://github.com/cypress-io/cypress/pull/4354

**Comment by fr0** [comment]
Thanks, @jennifer-shehane. Perhaps a prudent question to ask would be... how did it get so out-of-date to begin with? I think it would be much easier on you guys and your users in the future if you keep up with Electron updates incrementally, rather than doing a huge update across several major revisions every year.

**Comment by Swatinem** [comment]
Now that electron has a predictable release cycle (https://electronjs.org/blog/12-week-cadence), I hope that makes it easier for all the tools built on it to keep up.

**Comment by shinobi64** [comment]
> Some es6 syntax breaks in latest cypress. Is there an ETA on when an alpha or something will be available?

see the same Object.keys({}).values() worked with cypress 3.2.0 but breaks at least with cypress 3.4.0 (switch from electron 59 to electron 61)

**Comment by cookiescrumbs** [comment]
I hope the irony of this problem isn't lost on anyone.

**Comment by leonardoj-cit** [comment]
Is there any eta on this update?
There is a key part of my application that does not work on electron right now, only on chrome. I am assuming that is because of their version :(

Any ideas how could I by pass this while this is not updated? Or anyway that I could investigate this further? I see no logs on console, the page simply does not open

**Comment by trygveaa** [comment]
@leonardoj-cit: As a workaround, you can run Cypress against a separate Chrome installation. See https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers

**Comment by jennifer-shehane** [comment]
This will go out as soon as all of our tests pass in this PR: https://github.com/cypress-io/cypress/pull/4720#issuecomment-514316695 

There is a checklist of tasks that need to be completed. I would love an ETA just like everyone else would. We could throw out a date, but giving an estimate for how long it will take us to solve problems we don't even know the cause of is just going to be wrong.

**Comment by mabedan** [comment]
Appreciate the transparency, even though not the ideal answer

**Comment by leonardoj-cit** [comment]
@trygveaa that is true, but I cannot run that headless =(

@jennifer-shehane thanks for the update, I understand and I will keep an eye on it

**Comment by trygveaa** [comment]
@leonardoj-cit: Yeah, you can. See https://developers.google.com/web/updates/2017/04/headless-chrome and https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

**Comment by leonardoj-cit** [comment]
Hey guys, first of all, thanks so much for all the hard work on this.
How is the plan to release this?
Is there any way that I can point to a version that has that already and start using?

**Comment by janakdr** [comment]
Hi, is there a tracking bug for upgrading to the next version of Electron? It looks like 5.0.1 was released [6 months ago](https://electronjs.org/releases/stable?page=7#5.0.1). What is the expected cadence going forward for Electron releases? I understand it's a whole lot of grunge work, but just curious if there is a plan. Thanks!

(I'm particularly interested in getting Chromium up to at least v74.)

**Comment by jennifer-shehane** [comment]
@janakdr We're using nearly the latest version of Electron in our latest version. Please update. PR for newer update here https://github.com/cypress-io/cypress/pull/6085
