### ISSUE TITLE
play nice with Google's firestore-admin gRPC implementation

### ISSUE THREAD

**Issue by bpkennedy** [cypress-io/cypress#3570]
### Current behavior:

When a cypress plugin task is invoked and a call to google's Firestore is made using their `firestore-admin` SDK (which uses gRPC) I see various kinds of failures related to gRPC.  The first one was a something like this:

```
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v57-darwin-x64-unknown
Found: [node-v64-darwin-x64-unknown]
```

So, i started tinkering with manually installing versions of grpc.  Here are the things I tried, all to no avail:

* `rm -rf node_modules` and remove `package-lock.json` and reinstall
* `npm rebuild`
* switching node versions - I'm using `nvm` and have done 8.6.0, 10.0.0, 10.15.1
* `npm install grpc`  with a various options of `--target`, `--runtime`, `--arch`
* `npm install grpc --build-from-source` and tried `npm install --build-from-source` in the `node_modules/grpc` directory.
* Running cypress with `--headed false` to see if it's maybe related to headless or not
* using `yarn` for the above

The only progress I made was eventually the right combination of installing grpc manually to get the right combination of params to produce `node-v57-darwin-x64-unknown`.  Once I got to that point, cypress execution of my node script is still failing with the a grpc-related message:

```
Error: dlopen(/Users/kennedyb/Projects/kenshi-journal/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node, 1): Symbol not found: _GENERAL_NAME_free
  Referenced from: /Users/kennedyb/Projects/kenshi-journal/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node
  Expected in: flat namespace
 in /Users/kennedyb/Projects/kenshi-journal/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kennedyb/Projects/kenshi-journal/node_modules/grpc/src/grpc_extension.js:32:13)
    at Object.<anonymous> (/Users/kennedyb/Projects/kenshi-journal/node_modules/grpc/src/grpc_extension.js:63:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

I cannot get past this point - been googling around for about three hours now.  I know this is related to the `firestore-admin`'s usage of the grpc package because I've seen some people talk about firebase and electron not always working well together because of the runtimes.  (that, and when I comment out the methods that make firestore-admin calls, I don't see that error).  Here is the node script that makes calls (trimmed to the imports/exports for brevity): 

```js
// in clearDatabase.js
const admin = require('firebase-admin');
module.exports = async () => {
    try {
    await deleteCollection(db, 'entries', 500)
    await deleteCollection(db, 'stories', 500)
    await deleteCollection(db, 'users', 500)
    await deleteExtraneousUsers()
    await resetAdminUser() 
    process.exit()
  } catch(error) {
    console.log('there was an error trying to reset the db')
    console.log(error)
  }
}

// in plugins/index.js
const resetDatabase = require('./clearDatabase.js')
module.exports = (on, config) => {
  on('task', {
    async reset () {
      await resetDatabase()
      return null
    }
  })
}

// in support/index.js
beforeEach(() => {
  cy.clearCache()
  cy.visit('http://localhost:8080')
})
afterEach(() => {
  cy.task('reset')
})
```
And like I said, if I were to comment out the calling code inside the export of `clearDatabase.js`, there would be no error as cypress goes about it's merry way, which is a very merry way indeed.

And for more context on this, I can run these scripts outside of whatever cypress is running them in and it works without issue - which is frustrating me because it seems for all intents and purposes that the SAME grpc should be available to both outside and inside cypress doing whatever magic it does (sorry, I'm still learning about it).

At any rate - this is a significant stopper for me if I can't figure out a way for Cypress to call to firestore - i.e. I cannot reset my database before each (or any) test.  I'd really appreciate some help!  It might also be nice to see any sample implementation of someone who's able to do this with firestore, if you had it.

### Desired behavior:

No gRPC errors when interacting with firestore-admin SDK in Cypress plugins

### Versions

^3.1.5, MacOS High Sierra (10.13.6), Chrome headed and headless

**Comment by bpkennedy** [comment]
Any thoughts on this?

**Comment by jennifer-shehane** [comment]
This may be due to the code in the pluginsFile being run in Electron’s node but the gRPC expects a different environment.

You may find more benefit trying to implement this using [`cy.request()`](https://on.cypress.io/request) or [`cy.exec()`](https://on.cypress.io/exec) to call into the code running in your own environment.

**Comment by bpkennedy** [comment]
Ok, I'm just thinking through how I might implement this.  So, I don't think I can use `cy.request()` as the public interface of the Firebase SDK doesn't allow me to directly make http requests.

But in using `cy.exec()` - since this is a system command, I suppose I could make my `clearDatabase` module into a kind of node IIFE (and make sure it exits) and then inside my plugins file I would do something like:

```
// in plugins/index.js
module.exports = (on, config) => {
  on('task', {
    async reset () {
      await cy.exec('node clearDatabase.js') // uses Node to run the clear database script that uses Firebase SDK
      return null
    }
  })
}
```

Is that what you were meaning?

**Comment by bpkennedy** [comment]
Actually, I don't think that's the answer.  The clearDatabase.js is actually working just fine.  The issue is the app code that uses firebase where it makes actual CRUD calls to firebase (nothing I would access from Cypress test/plugin/support code).

When I drive a test to click a button, and that button initiates a GET request call to firebase in my app code, that is where the errors with gRPC happen.  I don't think this is something that can be solved with `cy.exec()` and `cy.request()`.  Additionally, I don't want to stub those calls in my tests.  I want to allow the real calls to a real instance of the database to go through and then verify the results in the interface.

Is there other things we might be able to try?

**Comment by bpkennedy** [comment]
Just to update, I can successfully call `cy.exec('node ./cypress/clearDatabase')`in my before/after.  That is doing my database wiping and reseeding using firestore-admin.  All is well.  Thank you!

**Comment by RoyalSix** [comment]
@bpkennedy I'm also trying to clear a database before a cypress test suite. Mind if I could see how you're handling that in your node script?
