### ISSUE TITLE
TypeError: Cannot read property 'unbind' of undefined

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#3572]
### Issue :
I currently have an issue on a post XHR request, the request have a 200 response but I got the following error displayed on `cypress_runner.js`:

```
- Error:        TypeError: Cannot read property 'unbind' of undefined
```

Is it a bug from Cypress itself ?
Is there a way to ignoring it ?

I already have the following commands in my `beforeEach` function :
```js
Cypress.on('uncaught:exception', (error, runnable) =>
{
  return false
})
```
```js
Cypress.on('fail', (error, runnable) =>
{
  if (error.message.includes("Cannot read property 'unbind' of undefined")) return
})
```

The `Cypress.on('fail')` actually don't help, cause it killed the script itself instead of handling the error.

Any help please ?

Best regards.

### Versions :
- Cypress 3.1.5
- Chrome 72

**Comment by jennifer-shehane** [comment]
Hey @mandriao84, I can't be sure where this is coming from just from the information you gave. 

Can you provide a reproducible example,  Test code + app code, that we can run to reproduce this? Providing the test code + screenshots or videos may be helpful in themselves if not. Thanks!

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
