### ISSUE TITLE
Error not showing in status window, only in developer tools console

### ISSUE THREAD

**Issue by thellvig** [cypress-io/cypress#3573]
This example from documentation should show as failed, but it shows as passed
```js
 cy.wrap(null).then(() => {
        return { id: 123 }
      })
        .then((obj) => {
          // subject is now the obj {id: 123}
          expect(obj.id).to.eq(321) // should show error, but shows only in the developer tools console
        })
```

**Comment by Saibamen** [comment]
Cypress 3.1.5 shows it as failed:
![obraz](https://user-images.githubusercontent.com/905878/53300011-c7546900-3839-11e9-9660-37d08a3761f3.png)

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
