### ISSUE TITLE
Run tests from a specific folder

### ISSUE THREAD

**Issue by ArmandoAA** [cypress-io/cypress#3574]
### Current behavior:

Currently I have not found a way to run the tests from just certain folders.

### Desired behavior:

It would be interesting that in addition to run spec all, the cypress allowed to execute the tests by folders.

**Comment by bahmutov** [comment]
Take a look at —spec option, you can pass a wildcard of spec files to run

**Comment by Saibamen** [comment]
Can be closed.
Add this to your `cypress.json`:
```
"integrationFolder": "C:\\test test"
```
or:
```
"integrationFolder": "C:/test test"
```

**Comment by ArmandoAA** [comment]
Got it.
Even though it would be interesting to be able to do this directly from the cypress interface.

**Comment by Saibamen** [comment]
Maybe someday will be a settings view for all config variables ;)

**Comment by bahmutov** [comment]
I believe you can see all config variables as resolved from the GUI

**Comment by Lakitna** [comment]
You might be referring to what's described in #1586

**Comment by Saibamen** [comment]
So this issue can be closed
