### ISSUE TITLE
Not able to get the updated value 

### ISSUE THREAD

**Issue by swatisharma03** [cypress-io/cypress#3577]
Hello,

In the following example, $result.text is getting me the updated value, whereas the actual value gets updated on click of the button. Its is very similar to the example on the cypress website under variables and aliases. 
Not sure what I am doing wrong.
Could you please help

cy.get('[data-tag*="row-id 1"] div:nth-child(3) >p').then(($result) => {

        const totalProcessed = parseFloat($result.text());
        cy.log("totalProcessed " + totalProcessed);

        cy.get('[data-tag*="row-id 1"] input').clear().type("1").then(($count) => {

          cy.log(($count).attr('value'))
          const addProcessed = parseFloat(($count).attr('value'));
          cy.log("addProcessed " + addProcessed);

          cy.get('[data-tag*="row-id 1"] button').click().then(() => {

            cy.wait(4000);

            const updatedtotalProcessed = parseFloat($result.text());
            cy.log("updatedtotalProcessed " + updatedtotalProcessed);
            cy.log("add :" + (totalProcessed + addProcessed))

            //expect(updatedtotalProcessed).to.eq(totalProcessed + addProcessed)
          })

**Comment by jennifer-shehane** [comment]
Hey @swatisharma03, did you find a solution? We'd love for you to share the fix for anyone finding this issue in the future.
