### ISSUE TITLE
Left panel with command log not showing running 3.1.5

### ISSUE THREAD

**Issue by maksimkarpov** [cypress-io/cypress#3578]
### Current behavior:
It the same problem as in https://github.com/cypress-io/cypress/issues/2107 which is I'm not showing left panel with command log when running tests. Opening new issue as the solution for initial one was to upgrade to 3.1.5 and I'm already running this version

### Desired behavior:

command log to show when I run tests in test runner
![aaaa](https://user-images.githubusercontent.com/41156073/53332166-92541f00-38ea-11e9-9bf7-430089e47f51.png)

**Comment by jennifer-shehane** [comment]
Hey @maksimkarpov, first, I would suggest making sure the lefthand side has not been manually shrunk - by dragging the width to zero as mentioned in this issue https://github.com/cypress-io/cypress/issues/2132

You may also try [clearing your app data](https://on.cypress.io/debugging#Clear-App-Data).

If this is not your issue, we'll need a reproducible example to help track it down.

**Comment by maksimkarpov** [comment]
yeaaah, that worked. Thanks a ton!

**Comment by MalachyCampbell12** [comment]
Pulled my hair out over this, thank you @jennifer-shehane

**Comment by worldsayshi** [comment]
I also had a similar issue but it was caused by redirect from http to https, causing the baseUrl to not match the one in cypress.json. Changing baseUrl to https fixed this issue.
