### ISSUE TITLE
Cy.wait() doesn't wait any routed request

### ISSUE THREAD

**Issue by Ivan-Katovich** [cypress-io/cypress#3579]
Hi, Looks like cy.wait doesn't wait routed request after clicking on the button. 
My simple test is:

```
it('second test', function() {
        cy.visit('https://www.cypress.io/')
        cy.server();
        cy.route({
            method: 'GET',
            url: '/dashboard'
        }).as('getDash')
        cy.get('.navbar [href="/dashboard/"]').click()
        cy.wait('@getDash')
        .its('url').should('include', 'dashboard')
    })

```
I expect that wait should intercept request after clicking on appropriate button but looks like page loads and then wait starts and fails after timeout.

I use default config.
I have such report:
![image](https://user-images.githubusercontent.com/7858279/53337123-87f94b80-3911-11e9-9bf8-a0ccc1a541f4.png)

**Comment by thomassjogren** [comment]
@Ivan-Katovich I'm pretty sure that the URL for the router must match the real URL exactly. In your case you specify a route as `/dashboard` but the real route includes a trailing `/` so should be `/dashboard/'

**Comment by Ivan-Katovich** [comment]
> @Ivan-Katovich I'm pretty sure that the URL for the router must match the real URL exactly. In your case you specify a route as `/dashboard` but the real route includes a trailing `/` so should be `/dashboard/'

![image](https://user-images.githubusercontent.com/7858279/53338140-02c36600-3914-11e9-8308-30f0b05364af.png)

looks like it doesn't help

**Comment by thomassjogren** [comment]
@Ivan-Katovich Sorry, I just realised that I missed an important detail. The request you are trying to do is a full page reload. The current implementation of `cy.wait()` doesn't support this as noted in the documentation (https://docs.cypress.io/api/commands/wait.html#Yields).

So that might be the reason why it fails.

**Comment by Ivan-Katovich** [comment]
> @Ivan-Katovich Sorry about first answer, I just realised that I missed an important detail.
> 
> The request you are trying to do is a full page reload. The current implementation of `cy.wait()` doesn't support this as noted in the documentation (https://docs.cypress.io/api/commands/wait.html#Yields).
> 
> So that might be the reason why it fails.

Thanks a lot. Looks like it is the real problem of my test. I tried it with appropriate request and it works correctly.

**Comment by Ryuh5** [comment]
@thomassjogren can you please tell me what your approach was to solve this issue?
