### ISSUE TITLE
Use Chromium not Chrome

### ISSUE THREAD

**Issue by Vandivier** [cypress-io/cypress#3580]
### Current behavior:

Cypress doesn't work OOTB on AWS CodeBuild, because CodeBuild doesn't have a browser. If I `apt-get -y install chromium-browser` it still doesn't work, complaining about `No binary for Chrome browser on your platform.  Please, set "CHROME_BIN" env variable.` If I `apt-get -y install chromium-browser` we are gtg. This indicates a dependency on Chrome, not just Chromium.

### Desired behavior:

Chrome is Chromium plus proprietary sauce. I don't know the differences in detail, but I'm just filing this issue to document/justify not using Chromium directly, and perhaps investigating it as a longer term feature. It would be wonderful to have the functionality of Cypress in a true open source implementation. When X is open source, but depends on proprietary Y, the total implementation of X in an OS way is not feasible.

### Versions

Currently using Chrome 72 & Cypress 3.1.5

**Comment by jennifer-shehane** [comment]
I think these docs on [debugging launching browser](https://on.cypress.io/debugging#Launching-browsers) should be helpful - there's likely something about the download that we're not exactly looking for.

Let us know if this does or does not help solve you issue.

**Comment by flotwig** [comment]
That underlying error comes from your operating system, not from Cypress: https://unix.stackexchange.com/questions/176980/please-set-env-variable-chrome-bin We do offer support for Chromium, Chrome Canary, and other Chrome-family browsers.

If you're using the `cypress run --browser chromium` command, it ought to just work, as we expect to find Chromium at `/usr/bin/chromium-browser`. Also, as the docs Jennifer linked mention, you can debug what's going on with the browser launcher by running `DEBUG=cypress:launcher cypress run`. Maybe that will help shed some light on the issue.

**Comment by Vandivier** [comment]
Thanks for the clarification to both of you. After debugging further, Cypress wasn't throwing the Chromium err it was Karma :)
