### ISSUE TITLE
Support Google Cloud Build details in Cypress Dashboard

### ISSUE THREAD

**Issue by joelmoser** [cypress-io/cypress#3582]
### Current behavior:

When using the Cypress Dashboard with Google Cloud Build, all of the Git information is coming back undefined/null.  From looking in the code, and asking on Gitter, it seems that is not currently supported.

### Desired behavior:

I would like the Cypress Dashboard to pull that information from Google Cloud Build and display it.  https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values

### Versions

Cypress 3.1.5

**Comment by jennifer-shehane** [comment]
@joelmoser Thanks for linking to these variables - this is helpful. 

We collect relevant env variable information in our code here, so it should entail adding Google Cloud to this process and also writing tests to ensure it's working: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.js

cc @bahmutov

**Comment by joelmoser** [comment]
@jennifer-shehane Thanks!  I might take a stab at it and see if I can figure it out.

**Comment by joelmoser** [comment]
@jennifer-shehane @bahmutov 

So after looking through the documentation for awhile, it seems like to support this, we would have to pass through the Google Cloud Build default variables I linked above.  By that, I mean they would need to be specified in the Cypress Dockerfile for each type of image.  Or the user would have to pass them through themselves every time.  Neither of these seem like clean or sustainable solutions to me.  That would add extra clutter to the Dockerfiles that feels unnecessary, when Google should be providing those to the Docker images that are being run.  They use runtime substitutions instead of environment variables for those I linked, therefore they are not stored on the node `process.env`.  We would have to wait on them to change that paradigm (if they ever do)

**Comment by jennifer-shehane** [comment]
Yeah, I'm sure @bahmutov has some input to share. He's on holiday for a couple days, so please be patient for a response. 😄

**Comment by joelmoser** [comment]
No problem!  I just wanted to share what I found in case it proved helpful.  Thank you

**Comment by joelmoser** [comment]
Any input @bahmutov ?  Saw you in Gitter, so thought I would bump this ticket.  No rush

**Comment by bahmutov** [comment]
sure, I can add these variables to https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.js and they will be reflected in the dashboard, but if Google cloud requires YOU to expose them as environment variables, then there is not much we can do. You can always expose the variables yourself by the way: we are using https://github.com/cypress-io/commit-info#fallback-environment-variables so you can set the following env variables yourself and Cypress will pick them up

```
branch: COMMIT_INFO_BRANCH
message: COMMIT_INFO_MESSAGE
email: COMMIT_INFO_EMAIL
author: COMMIT_INFO_AUTHOR
sha: COMMIT_INFO_SHA
remote: COMMIT_INFO_REMOTE
```

I will put this issue on my plate, but not sure how quickly I can get to it

**Comment by joelmoser** [comment]
Thanks @bahmutov .  Yeah I'm concerned that Google Cloud requires the user to expose them (particularly since it is still in Beta).  I must have missed the fallback variables.  I will look into those for sure.  Thanks again for your help.

**Comment by tps7** [comment]
I am going to try to solve this. It does not seem like it has been worked on in a while

**Comment by jennifer-shehane** [comment]
yes we would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.
