### ISSUE TITLE
Proposal: Authenticate through user's installed browser

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3583]
### Current behavior:

Logging in with GitHub opens the Oauth authorize page in Cypress's packaged Electron, which causes issues:

- #1251 - Electron goes out of date and GitHub blocks logging in with it
- #1162 - Electron doesn't support hard tokens
- users can't see the URL of the page, could potentially be a security problem
- users can't use password vaults
- #4337 - networking bugs can cause auth not to work

### Desired behavior:

Logging in with GitHub through the desktop app opens a tab in the user's default system browser where they can authorize our app

Could be built by creating a HTTP server on localhost to accept auth redirects: https://stackoverflow.com/questions/37546656/handling-oauth2-redirect-from-electron-or-other-desktop-platforms

~~Or by creating a custom protocol handler and setting the GH redirect URL to that: https://glebbahmutov.com/blog/electron-app-with-custom-protocol/~~ Won't work, registering a custom protocol globally usually requires advanced permissions.

**Comment by flotwig** [comment]
This depends on some changes to the Cypress dashboard API being made. Specifically, we need a way to redirect to the `http://localhost:...` URL during the OAuth flow, instead of redirecting back to the dashboard.

**Comment by alexlee-dev** [comment]
Is this related to #4337 ?

**Comment by flotwig** [comment]
@alexlee-dev It should prevent #4337 from happening, but none of the code for this has been released yet, so it wouldn't be the cause.

This should be out in the next minor release.
