### ISSUE TITLE
CircleCI timeout on cy.wait for aliased routes: No request ever occurred.

### ISSUE THREAD

**Issue by bcnichols3** [cypress-io/cypress#3585]
### Current behavior:

Local run on MacOS of Cypress tests passes as expected (both in headless and in Electron), but our CircleCI environment fails three of our tests, all of which use more than one `cy.wait()` command.

```
Timed out retrying: cy.wait() timed out waiting 5000ms for the 2nd request to the route: 'putContract'. No request ever occurred.
```

### Desired behavior:

We expect local and Circle results to fail or pass together.

### Steps to reproduce: (app code and test code)

Here's sanitized code of one of the tests failing on Circle:

```js
cy.server();
cy.route('POST', '/api/contracts').as('postContract');
cy.route('PUT', '/api/contracts/*').as('putContract');

injectDraftContract(draftContract);
cy.wait('@postContract');

cy.visit('/');

updateAndSaveDraftContract(secondDraftContract); 

cy.wait('@putContract').then((draftXhr) => {
    assert.deepEqual(draftXhr.request.body, draftContractRequestJson);
});

// back on homepage
cy.get('h1').should('contain', 'Contracts');
// custom command that gets the desired column content of the most recent row in our homepage's table
cy.latestContract('amount').should('have.text', updatedAmount);

continueToReviewPage();
cy.wait('@putContract').then((continueXhr) => {
      assert.deepEqual(continueXhr.request.body, continueDraftRequestJson);
});

submitContract();
cy.wait('@putContract').then((submittedXhr) => {
  assert.deepEqual(submittedXhr.request.body, submittedRequestJson);
});

// now on success page
cy.get('.textIntent-headline1').should('contain', 'Successful Submission!');
cy.get('#return-home').click();

// back on homepage
cy.get('h1').should('contain', 'Contracts');
cy.latestContract('amount').should('have.text', updatedAmount);
cy.latestContract('status').should('have.text', 'Submitted');
```

### Versions

Cypress v3.1.5
Axios v0.18.0
Node v10.8.0-alpine

**Comment by jennifer-shehane** [comment]
Most often in cases of flaky tests, we see that there is not enough assertions surrounding the actions or XHR requests/responses necessary before moving on to the next assertion. So if there is any variation in the speed of the XHR requests response in interactive mode versus run mode, then there will start to be failures in one over the other - or flaky tests. 

One of our engineers, Gleb, wrote a great blog post about this you can read here: https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

My best debugging tip is to get a screenshot/video of the Command Log while running in CI on the flaky failed test and compare this to a screenshot/video of the Command Log while running locally - anywhere you see that it does not match exactly, look into that - may be a request returned slower or the order of how your app responded slightly changed.

Other than this general advice, we would need reproducible code that could be run by us to look into it further. 

You may want to try asking in our [community chat](https://gitter.im/cypress-io/cypress). Alternatively, if you have any of our [paid plans](https://www.cypress.io/pricing/) this gives you access to our team for support via email at support@cypress.io. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.

**Comment by bcnichols3** [comment]
Thanks for replying @jennifer-shehane!

> not enough assertions surrounding the actions or XHR requests/responses necessary before moving on

Are you suggesting here I pad my XHR with additional assertions? Is this any different from applying a manual `cy.wait`?

If I'm understanding these blog posts right — the issue is likely that the `put` request has already executed before Cypress is aware that it should be expecting it? I did try kicking up the timeout in my `cypress.json`. That didn't help, but if I'm understanding you — of course that wouldn't. We need time _before_ the fact, not after, correct?  Then it sounds like I should try adding some additional time before the `cy.wait('@putContract')` is executed?

> get a screenshot/video of the Command Log

This sounds smart as well. I will investigate both these angles and reply with my findings. Thank you.

**Comment by jennifer-shehane** [comment]
Hey @bcnichols3, any updates after your investigation? I'd like to close this issue if it's been resolved.

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
