### ISSUE TITLE
Passing chai expects should be logged to cypress log

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3586]
### Current behavior:

```js
cy.get('foo').then($els => {
  expect($els.length).to.be.equal(3);
});
```

If this fails, it (rightfully) prints something to the cypress log pane:

![screen shot 2019-02-25 at 2 41 41 pm](https://user-images.githubusercontent.com/435418/53363844-87f64d00-390b-11e9-8ce0-4fc8f4220cc0.png)

If this passes, it seems to print nothing, other than the original `GET`.

![screen shot 2019-02-25 at 2 42 51 pm](https://user-images.githubusercontent.com/435418/53363933-af4d1a00-390b-11e9-926a-13e258a0ab93.png)

### Desired behavior:

Passing `expect`s should print something similar to passing `should`s.

![screen shot 2019-02-25 at 2 43 55 pm](https://user-images.githubusercontent.com/435418/53363986-ce4bac00-390b-11e9-8a09-44366dc0b737.png)

### Versions

Cypress 3.1.5

**Comment by jennifer-shehane** [comment]
Hey @fr0, I was unable to produce this from the exact code provided.

**My test code**

```js
it('Print to console', () => {
  cy.visit('https://example.cypress.io/commands/location')
  cy.get('div').then(($els) => {
    expect($els.length).to.be.equal(14)
  })
})
```

<img width="473" alt="screen shot 2019-02-25 at 4 51 54 pm" src="https://user-images.githubusercontent.com/1271364/53371269-c4cb3f80-391d-11e9-824d-156b5d93de44.png">

Is there some extra test code you didn't include?

**Comment by fr0** [comment]
Oh, interesting. I'm glad to hear that it is expected to work this way.
I wonder if it's because I'm using

```
import {expect} from 'chai';
```

...and in my `package.json`:

```
    "chai": "^4.2.0",
```

**Comment by fr0** [comment]
I can confirm that this is the case. Removing my version of `chai` from `package.json` and removing my import of it fixed the problem.
It would be nice if I could keep up with the latest versions of `chai`, `mocha`, `sinon`, and `sinon-chai` without having to wait for `cypress` to include them, but that's entirely a separate issue.
Thanks for the help!
