### ISSUE TITLE
.type() will not accept an empty string

### ISSUE THREAD

**Issue by DarthOpto** [cypress-io/cypress#3587]
### Current behavior:

CypressError: `cy.type()` cannot accept an empty String. You need to actually type something.

### Desired behavior:

An empty string is a valid an often necessary test on an input field. The type method should support this. 

### Steps to reproduce: (app code and test code)

```js
cy.get('input element').type('')
```
### Versions

Cypress: 3.1.5
MacOs Mojave 10.14.3
Chrome 72

**Comment by jennifer-shehane** [comment]
Hey @DarthOpto, what behavior are you expecting within an input when passing an empty string into `cy.type()`? What behavior are you trying to test in the input with this? Wouldn't this essentially be Cypress typing nothing?

**Comment by DarthOpto** [comment]
@jennifer-shehane I am basically trying to test that the sign in button is disabled when I leave the email field blank. I think I have a way around this. I am going to close this.

**Comment by StJohn3D** [comment]
Can we re-open this?
I'm trying to write dynamic tests that cleanup after themselves.
Take the value of input A and store it for later.
Type something, click save and assert on reload that it's there.

Now in the cleanup phase I want to write back whatever value was there before. This is where cy.type is breaking my tests if the original value was an empty string.

I have to add an if statement that basically checks to see if the original value was an empty string, and if it was, then don't call cy.type. This isn't ideal, cy.type feels like any string value should be a valid argument - even an empty string.

**Comment by StJohn3D** [comment]
@jennifer-shehane ☝️

**Comment by jennifer-shehane** [comment]
If you want to set the value of an input as an empty string, you can do this programatically. A person cannot type an empty string, so this will not be supported in `.type()`. 

To do this programmatically:

```
cy.get('input').invoke('val', '')

**Comment by c32hedge** [comment]
This is unfortunate--it would be nice if `cy.type('')` was treated as a no-op instead of throwing an error. The current behavior means that I can't have a helper function for testing many different inputs to a field with the following pattern:

``` js
testInput(inputValue) {
  cy.get(<inputField>)
    .clear()
    .type(inputValue);
}
```

In fact, I'm scratching my head trying to figure out how to work around this. The `cy.clear()` documentation says it yields the same subject it was called on, but the following gives me an error:

``` js
testInput(inputValue) {
  cy.get(<inputField>)
    .clear()
    .then(e => { if (batchName !== '') e.type(inputValue) });
}
```

This gives me:

> TypeError: e.type is not a function

I think this is actually an issue with combining Cypress and TypeScript because `type` is a reserved keyword in TypeScript and/or I don't have a type specified for `e`. What _is_ the correct type to use for a DOM element yielded by `cy.get()`? Anyone have another idea to work around this? Obviously, I could just do another `cy.get`, but I'd prefer to avoid that.

**Comment by chrisenitan** [comment]
> @jennifer-shehane I am basically trying to test that the sign in button is disabled when I leave the email field blank. I think I have a way around this. I am going to close this.

You can try [.clear()](https://docs.cypress.io/api/commands/clear.html#Usage) to achieve the same result.

**Comment by mrkrstphr** [comment]
> You can try [.clear()](https://docs.cypress.io/api/commands/clear.html#Usage) to achieve the same result.

This worked perfect for me, thanks!

**Comment by Amrkamel1** [comment]
Sending an empty string does make send ofc, especially if you are using a common method for multiple test case for sake of usability.

**Comment by hans2520** [comment]
Here's a 1-liner to achieve the use case:
```
cy.get(elem).clear().then(() => {if (newValue) cy.get(elem).type(newValue, {force: true})});
```

**Comment by actionJacksonfv** [comment]
Not sure if this is the best approach but I just passed the `{backspace}` command to it when editing some objects i.e. myObj.firstName = '{backspace}' and that threw validation errors that I could assert off of.

**Comment by vtanasa2792** [comment]
> 

This worked wonders. Thanks.

**Comment by youseff199959** [comment]
{backspace} works fine with me and the test case runs greatly 
Thank @actionJacksonfv

**Comment by dwvwdv** [comment]
> Not sure if this is the best approach but I just passed the `{backspace}` command to it when editing some objects i.e. myObj.firstName = '{backspace}' and that threw validation errors that I could assert off of. `cy.get('element').type('{backspace}');`

if modify field have chars, this action will broken it.
I use ESC key ignore focus field,thank your idea help me:)

`cy.get('element').type('{ESC}');`

**Comment by azhukovskygit** [comment]
To test the Login form I just used cy.get('element').type(' ') and it doesn't throw an exception.

**Comment by wahinya** [comment]
There is a tech debt on the type() function;  I want to use one test in testing several input data including null

**Comment by alexeyhimself** [comment]
Use cases when .type('') can be useful as well: parametrized tests for login, fuzzy tests for forms. 
For example:
```
['', ' ', 'non-existing@example.com', 'invalid@'].forEach((login) => {
  it(`Error message is ... when trying to login with ${login}`, () => { 
    cy.get('#login').type(login);  // it is useful and handy to have .type('') here 
                                   // along with other invalid options
    ...
  });
});
```
The same for fuzzy tests when we try to put random length and random content strings into the fields: empty string '' should be an option.

Not clear to me why [developers decided to "no op"](https://github.com/cypress-io/cypress/issues/6157) it rather than to fix it. I vote to reopen this bug and fix, rather than close and not fixing.

**Comment by t00** [comment]
type() should not really check if test code is correct but since it does  I'll share my take on testing values sourced in Partial<TestCase> - like objects:

```
Cypress.Commands.add('maybeType', { prevSubject: true }, <any>((subject: any, text?: string, options?: Partial<Cypress.TypeOptions>) => {
  if (text != undefined) {
    subject.clear();
    if (text.length > 0) {
      subject.type(text, options);
    }
  }
  return subject;
}));
```

```
declare global {
  namespace Cypress {
      /**
       * If text is not null/undefined, clears the field and enters text (if not empty)
       * @param text text or null/undefined if no change is done, or empty string '' if only clear is expected
       * @param options cypress text type options
       */
      maybeType(text?: string, options?: Partial<Cypress.TypeOptions>): Chainable<any>;
    }
  }
}
```


And usage:
```

const myTestCase = {
  noChage = undefined,
  clearMe = '',
  replaceWithText = 'new text'
}

cy.get('[data-qa=my-text-control]').maybeType(myTestCase.noChange); // not doing anything
cy.get('[data-qa=my-text-control]').maybeType(myTestCase.clearMe); // clears
cy.get('[data-qa=my-text-control]').maybeType(myTestCase.replaceWithText); // new text

```
