### ISSUE TITLE
use cypress to test electron app

### ISSUE THREAD

**Issue by marty-wang** [cypress-io/cypress#359]
Is it possible or planned to have cypress to test electron app? If so, how? Thanks!

**Comment by RandallKent** [comment]
Yes and no.

Our desktop app is an electron app and we use Cypress to test it! To do this, we test the app like it's a pure web app, stubbing out the Electron specific APIs. Our desktop app is public, so you can see exactly how we're doing this by checking out the [repo](https://github.com/cypress-io/cypress-core-desktop-gui/tree/master/cypress).

If you wanted to test with Electron's APIs, you'd want to look into [Spectron](https://github.com/electron/spectron).
