### ISSUE TITLE
Selector Playground: Being able to declare your * (data-*, with * not being cy, test or testid)

### ISSUE THREAD

**Issue by san-ouadghiri** [cypress-io/cypress#3595]
### Current behavior:
https://docs.cypress.io/guides/core-concepts/test-runner.html#Selector-Playground
The selector playground catches data-cy, data-test, data-testid (and then other patterns)

### Desired behavior:
In my company we use data-qa. Thus the selector playground offers me worse selectors, as it can't identify my custom attribute.

One could argue that you can't cover every data-<word> indeed. Thus, it would be nice for Cypress to either found any data-*, or if simpler to let the test-writer declare that special word in a file (ex. in cypress.json I set star="qa" and here I am, it finds my data-qa!).

If so, cypress could search for data-<* as declared in cypress.json> first, and then for the rest of the list.

### Versions
    "cypress": "^3.1.5"

**Comment by jennifer-shehane** [comment]
Hey @san-ouadghiri, you can customize the selector preference using the Selector Playground API. I think this should meet your needs. Let me know! https://on.cypress.io/selector-playground-api#Examples
