### ISSUE TITLE
Cypress skips first assertion without failing.

### ISSUE THREAD

**Issue by Rup1** [cypress-io/cypress#3597]
### Current behavior:
First test expects an alert prompt to appear and checks the alert text. This works fine on its own but if there is a second test it skips the assertion in the first test without failing, and moves on to the second test, adding `cy.wait(100)` fixes this but this shouldn't be necessary.

![screen shot 2019-02-26 at 2 10 17 pm](https://user-images.githubusercontent.com/15389183/53439680-978b9980-39d0-11e9-9838-b2d65102ea7b.png)

If I comment out the second test then it works:

![screen shot 2019-02-26 at 2 21 13 pm](https://user-images.githubusercontent.com/15389183/53440132-d4a45b80-39d1-11e9-9506-d7b331b4b5c8.png)

### Desired behavior:
For the assertion in the first test to run.
For the test to fail if it doesn't run.

### Steps to reproduce: (app code and test code)

```
import faker from 'faker'

describe('User can sign up', () => {
  const name = faker.name.firstName()
  const email = faker.internet.email()
  const username = name + "-" + faker.internet.userName()
  
  specify('User completes signup form and submits', () => {
    cy
    .visit('http://localhost:8080/signup')
    .get('[data-test=name]').type(name)
    .get('[data-test=email]').type(email)
    .get('[data-test=password]').type('testing')
    .get('[data-test=username]').type(username)
    .get('[data-test=btn]').click()
    .then(() => {
      cy.on('window:alert', (str) => {
        expect(str).to.equal(`${name} was registered successfully`)
      })
    })
  })

  specify('Loads forum categories after signup', () => {
    cy
    .get('.container')
    .then(el => {
      expect(el).to.contain('Categories')
    })
  })
})
```

### Versions

Latest cypress version
MacOS Mojave
Chrome 72

**Comment by Lakitna** [comment]
It could have to do with the order of operations, try the following:

```javascript
cy.on('window:alert', (str) => {
    expect(str).to.equal(`${name} was registered successfully`)
});

cy
    .visit('http://localhost:8080/signup')
    .get('[data-test=name]').type(name)
    .get('[data-test=email]').type(email)
    .get('[data-test=password]').type('testing')
    .get('[data-test=username]').type(username)
    .get('[data-test=btn]').click();
```

**Comment by Rup1** [comment]
@lakitna I wanted to try that but it's a new day and the same exact code that was failing intermittently yesterday now passes with flying colors. I wrapped my test suite in a for loop and it runs 50 times without fail. I haven't changed a single thing in the code. While this is good news this understandably makes me less confident in my tests.
