### ISSUE TITLE
passing options to an aliased DOM element gives unexpected results because it's using original DOM query

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#36]
Sometimes I write a test like the following that I expect to pass:

```coffee
cy
  .get("#button").as("submitBtn")
  .get("@submitBtn", {visible: true})
    .click()
  .get("@submitBtn", {visible: false})
```

Since Cypress is only querying the DOM for my aliased element on the first command, it will always see the submit button as visible (although the state in the DOM has changed after my click as dictated by my application logic). 

If I pass options to an alias (visible, exist, length), I want the DOM to be re-queried to find that current el, since I'm likely asserting on it's current state.

**Comment by brian-mann** [comment]
Fixed in [`0.11.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0110-09132015).

Just use regular assertions after the alias.
