### ISSUE TITLE
while double click on Cypess.exe getting 'A javaScript error occurred' error for window 7 64 bit

### ISSUE THREAD

**Issue by SachanYogesh** [cypress-io/cypress#3603]
step:
1- download from https://download.cypress.io/desktop
2- right click on cypress.zip and select Extract all.
3- double click on Cypress.exe

![crpress](https://user-images.githubusercontent.com/48051895/53486651-87ae9c80-3a46-11e9-9fc7-53ee8c61b25b.PNG)

**Comment by sainthkh** [comment]
The support for Windows 7 ended at January 14th, 2020. If the similar thing happens at Windows 10, please open a new issue.
