### ISSUE TITLE
 How can we bypass cross origin policy while automating using Cypress?

### ISSUE THREAD

**Issue by akhiltabjula** [cypress-io/cypress#3604]
I am trying to automate a web application using Cypress. But, unable to load the site as it requires authentication from another source (Iframe). Is there any way to overcome this?

**Sample code:**
```js
describe('Initial Cypress Tests', () => {
  it('navigate to MSteams site', () => {
    cy.visit('https://teams.microsoft.com/_#/')
  })
})
```
![screenshot 6](https://user-images.githubusercontent.com/38072232/53491467-80c27100-3abc-11e9-9ab4-49f714b40cd6.png)

**Comment by jennifer-shehane** [comment]
I am seeing this specific error in the console while running the code above:

```
Refused to display 'https://login.microsoftonline.com/common/oauth2/authorize?...' in a frame because it set 'X-Frame-Options' to 'deny'.
```

This looks like it is the same issue as https://github.com/cypress-io/cypress/issues/3459 except with `deny` instead of `SAMEORIGIN`. So, I will close this issue in favor of that one.

**Comment by akhiltabjula** [comment]
I tried to update my cypress.json file with "modifyObstructiveCode": false.
There is a slight improvement, able to launch web application splash screen.
But stays in same splash screen page.

![screenshot 7](https://user-images.githubusercontent.com/38072232/53617608-de1a0780-3c0d-11e9-81d9-665b4ad6385b.png)

**Comment by jpourdanis** [comment]
I have the same issue work with csp and origins

**Comment by AtofStryker** [comment]
Hi all. Would anyone be able to try https://github.com/cypress-io/cypress/issues/3459#issuecomment-1320431165 and post on that issue?
