### ISSUE TITLE
Unable to read environment variables from CLI when I run tests with Cypress

### ISSUE THREAD

**Issue by srinu-kodi** [cypress-io/cypress#3605]
**Subject: Unable to read the environment variables that I am passing from command line.**

For eg `ENV=prod npm run smoke;` I am reading as below in my tests.
`env = process.env.ENV;`

While Non-Cypress repo(`jest` or `jasmine` framework etc..) is working fine when I run as `ENV=prod npm run smoke`. 

Is it somewhat Cypress not supported with ? although `process.env.ENV` is a Node feature. My Cypress version is "3.1.4". It would be really great if someone can help me..

**Comment by jennifer-shehane** [comment]
Could you provide the test code where you are trying to use the `process.env.ENV`? And where this test code is run? Is it in a `support` file or within a test spec file? How are you determining it is unable to read it?

**Comment by srinu-kodi** [comment]
Hi,
Thank you for responding.
Below is the **spec.js** which is in my "cypress/integration" directory. I am not able to read in spec.js file.

**spec.js:**
describe('test env feature', function () {
    it('test env test', function () {
        expect(process.env.ENV).to.equal("smoke");
    })
});

**Run Command:**
ENV="smoke" npm run smoke

**package.json:**
"smoke": "./node_modules/.bin/cypress run --spec 'cypress/integration/spec.js'".

Please let me know if you need more details.

**Comment by srinu-kodi** [comment]
Hi,

Here is how I have fixed it.

package.json: 
"smoke:PROD": "./node_modules/.bin/cypress run --spec 'cypress/integration/spec.js' --env env=PROD",

run command:
npm run smoke:PROD

**Comment by srinu-kodi** [comment]
Mistakenly I have closed it.

Hi,
Here is how I have fixed it. However I would like to know your views on this issue. As I am mentioning the ""smoke:PROD" or "smoke:LOCAL" or "smoke:INT" the test script commands will keep on increasing in my package.json as I do not have any other option in order to solve the issue.

However It looks like fine.

package.json: 
"smoke:PROD": "./node_modules/.bin/cypress run --spec 'cypress/integration/spec.js' --env env=PROD",

run command:
npm run smoke:PROD

spec.js:
describe('test env feature', function () {
    it('test env test', function () {
        expect(Cypress.env().env).to.equal("prod");
    })
});

**_Note: I am still wondering why I cannot read with process.env.ENV_**

**Comment by jennifer-shehane** [comment]
I believe this is due to the `spec.js` file being run within the browser context - not node. 

You should be able to access `process.env.ENV` from within the [Plugin files](https://on.cypress.io/writing-and-organizing-tests#Plugin-files) or [Support files](https://on.cypress.io/writing-and-organizing-tests#Support-file) as these will have access to the node context.

Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
