### ISSUE TITLE
Add support for backticks in reporter error messages

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#3608]
### Current behavior:
No markdown support currently, linkify support added in #3457 

### Desired behavior:

Include support for backticks and escaping so we can use them in error messages.

**Comment by lilaconlee** [comment]
Before merging I need to figure how how to handle escaped values in the console props:
<img width="588" alt="screen shot 2019-02-27 at 2 25 28 pm" src="https://user-images.githubusercontent.com/7514489/53523418-624f7c00-3aa2-11e9-8745-3336b3865f2a.png">
<img width="621" alt="screen shot 2019-02-27 at 4 05 29 pm" src="https://user-images.githubusercontent.com/7514489/53523419-624f7c00-3aa2-11e9-9c53-d9058674453b.png">

**Comment by lilaconlee** [comment]
Blocked by #3629 which bumps snap-shot-it which fixes a bug with escaped backticks. Tried a workaround with 89566e9 replacing backticks with single quotes, but think we should just upgrade. 

Tried figuring out the failing tests on the upgrade and couldn't figure it out, @bahmutov said he'd give it a go if he has time.

**Comment by lilaconlee** [comment]
This is now unblocked by snapshot-it 🎉 but now blocked because the snapshot-it changes are gonna every saved snapshot and some of them are failing for me locally on develop (`test/e2e/8_reporters_spec.coffee`) which I'll see about getting around tomorrow.

**Comment by bahmutov** [comment]
We can look at the failing ones together

**Comment by jennifer-shehane** [comment]
Closing as part of https://github.com/cypress-io/cypress/issues/3762
