### ISSUE TITLE
cy.visit() fails to load the page

### ISSUE THREAD

**Issue by krishvv** [cypress-io/cypress#3621]
Hi ,

I am using cypress 3.1.5 and am trying to open "kitchen Sik"

```js
describe('My First Test', function() {
  it('Visit a UI!', function() {
    cy.visit("https://example.cypress.io")
  })
})
```

Simple code as given in your doc. Upon execution , the page fails to load with the following error

=============
```
We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ETIMEDOUT 104.25.215.23:443

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ETIMEDOUT 104.25.215.23:443
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
```
==============

Note: When i try to visit the same url using regular chrome browser it opens without any issues . 

Only through Cypress this happens . In fact i just checked and i am not able to open any url using Cypress

**Comment by krishvv** [comment]
Chrome version is 72.0.3626.119

**Comment by jennifer-shehane** [comment]
Are you behind a corporate proxy? You may want to look into these workarounds: https://github.com/cypress-io/cypress/issues/1469

**Comment by krishvv** [comment]
Thanks @Jennifer.  Yes i am behind a corporate proxy. Will look into the mentioned workarounds

**Comment by krishvv** [comment]
Awesome . It was indeed the proxy . I followed the workarounds and am able to progress with my tests
Thanks

**Comment by krishvv** [comment]
@jennifer-shehane - When are the proxy issues expected to be fixed? Is there an ETA? I have checked on all the workarounds mentioned but they seem to not help in my case.
Please comment

**Comment by jennifer-shehane** [comment]
We'll be releasing improved proxy support in our next release. https://github.com/cypress-io/cypress/pull/3531

**Comment by Robert3191** [comment]
Hi!
I get the same error, but I am not behind a proxy.
Is there any other reason that can trigger this error? Thx!

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

@Robert3191 If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
