### ISSUE TITLE
Allow docking Command Log in different location - like below AUT window instead of on left

### ISSUE THREAD

**Issue by Christilut** [cypress-io/cypress#3622]
### Current behavior:
The test web interface has the test list on the left and the web app on the right.

### Desired behavior:
It would be nice if there is an option to display the web app on top and the test list below it. This would work really well with a monitor that's turned 90 degrees. That way you have the web app, test list below it and dev tools on the bottom all on 1 monitor and you can keep a fullscreen editor on your main screen.

**Comment by Manuel-Suarez-Abascal** [comment]
I would love to implement this feature 😃  

**CONTEXT:**

If I understood correctly, the `reporter sidebar` is located on the left of the screen. It's not possible to dock it to the `right`, `bottom`, or `undock` it.

**BENEFIT/VALUE:** 

It provides a better `UX` experience having the ability to customize the `layout` of the `reporter sidebar`.

**PROPOSED WORK (Potential Solution):**

Implementing an `UX` solution similar to [Chrome Devtools docking feature](https://developer.chrome.com/docs/devtools/customize/placement/).

**ACCEPTANCE CRITERIA (Output):**

- Users should `click` on an `icon` to open the `docking options`.
- There will be three `docking options`: docking to the `left`, `right` & `undocking` the `reporter sidebar` (I'm not sure if we should include this in the `scope`. Thoughts? 🤔 ).
- When a docking option is selected, the `reporter sidebar` will go to the selected, layout option & the docking panel must close.
- Adding `keyboard shortcuts` support for docking feature (I'm not sure if we should include this in the `scope` as well? Thoughts? 🤔)

**Visual representation:**

https://user-images.githubusercontent.com/32891808/137596941-95110965-8cbc-486e-928a-bafef2c327da.mp4

@jennifer-shehane @Christilut let me know what you guys think? Once the details are figured out, I'll start working on this feature.

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
