### ISSUE TITLE
performance.getEntriesByType is returning undefined

### ISSUE THREAD

**Issue by atikenny** [cypress-io/cypress#3625]
### Current behavior:

Overwrite `window.performance.getEntriesByType` with NOOP that returns `undefined`.

### Desired behavior:

Don't overwrite `window.performance.getEntriesByType`.

### Steps to reproduce: (app code and test code)

* Use `cy.clock` to take over the timing functions
* open a page
* try to use methods on `window.performance` like `getEntriesByType` (you can include the Facebook JS SDK to reproduce this)

#### Stack trace from Facebook SDK JS
```js
TypeError: Cannot read property 'filter' of undefined
      at c (https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:45:1484)
      at Object.<anonymous> (https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:164:238)
      at require (https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:24:620)
      at https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:165:223
      at https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:94:929
      at Array.forEach (<anonymous>)
      at c (https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:45:1604)
      at Object.fire (https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:94:894)
      at https://connect.facebook.net/en_US/sdk.js?hash=624278b338adcdb461a65444946d6779&ua=modern_es6:161:2263
```

### Versions

Cypress 3.1.5, Chrome

**Comment by jennifer-shehane** [comment]
@atikenny I've created a repo reproducing this bug here: https://github.com/jennifer-shehane/performance-entries

## tests
```js
it('does not call cy.clock', () => {
  // PASSES
  cy.visit('index.html')
})
  
it('calls cy.clock', () => {
  // FAILS
  cy.clock()
  cy.visit('index.html')
})
```

## app code
```js
var entries = window.performance.getEntriesByType("resource")
entries.length
```

# results

<img width="601" alt="screen shot 2019-03-01 at 2 17 01 pm" src="https://user-images.githubusercontent.com/1271364/53660807-c30ac000-3c2c-11e9-8680-24052ec5c6d3.png">

**Comment by atikenny** [comment]
Forgot to post the workaround if anyone is running into the same thing:
```javascript
cy.window().then(win => {
    win.performance.getEntriesByType = () => []
})
```
This needs to be executed after you took over the clock and the window of the page under test is loaded.

**Comment by flotwig** [comment]
This error comes from `lolex` (which provides `cy.clock()`'s functionality). Luckily, it seems that they've fixed this issue in recent versions, so an update should take care of it.
