### ISSUE TITLE
Add chapters keys in the video sequence for each test start/end.

### ISSUE THREAD

**Issue by NikoEscobar** [cypress-io/cypress#3626]
### Current behavior:
In the current video record output there is a plain sequence of the running tests in which we have to manually find for each test start/result.

### Desired behavior:
I would like to find for each test start in the video timeline sequence, through chapters keys.

### Versions
Latest Cypress on Windows 10.

**Comment by jennifer-shehane** [comment]
Some info on adding metadata using ffmpeg including chapters: https://ffmpeg.org/ffmpeg-formats.html#Metadata-1

The video capture code is here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/video_capture.coffee

**Comment by jennifer-shehane** [comment]
There was a partially finished PR for this feature that needed to be closed due to inactivity, if anyone wants to pick up that work it can be found here: https://github.com/cypress-io/cypress/pull/5362
