### ISSUE TITLE
cy.setCookie incorrectly sets a non hostOnly cookie by default

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#363]
We are incorrectly setting non `hostOnly` cookies to the superdomain of the remote origin.

This means that this cookie would be sent on all subdomains.

This is wrong, by default it needs to set a `hostOnly` cookie to the remote origin.

**Comment by flotwig** [comment]
@brian-mann this would be a breaking change if updated today, correct?

**Comment by brian-mann** [comment]
Not if its been a bug since day 1

**Comment by flotwig** [comment]
Which is why I think it's breaking, fixing it would change the behavior of `cy.setCookie` since day 1 :P

I need to verify that this change didn't accidentally get made when we switched to using CDP for cookies.

**Comment by AtofStryker** [comment]
fixed by #[24692](https://github.com/cypress-io/cypress/pull/24692)
