### ISSUE TITLE
My https request keeps loading even after a wait time of 1 min

### ISSUE THREAD

**Issue by tanvipadhye** [cypress-io/cypress#3635]

**Comment by jennifer-shehane** [comment]
Hey @tanvipadhye, could you provide a reproducible example?

**Comment by tanvipadhye** [comment]
describe('Test',function(){
it('Launches application',function(){
cy.visit('https://<server>/<loginURL>/')
}
})

since it is an organisation level URL cannot share the details. However I am able to log in but post  that the server just keeps waiting, I tried increasing the timeout but no effect.

**Comment by jennifer-shehane** [comment]
Yeah, this test code looks fine. This will be nearly impossible to debug without more information. Screenshots, video, reproducible example. 

Check out some of our [debugging tips](https://on.cypress.io/debugging) to track this down. 

You may want to try asking for advice on debugging also in our [community chat](https://gitter.im/cypress-io/cypress).

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.
