### ISSUE TITLE
run commands from commandqueue

### ISSUE THREAD

**Issue by matti** [cypress-io/cypress#3636]
I can add commands to the command queue with `cy.get("button")` - but could I trigger the last command from the queue without enabling debugger as suggested in #989

**Comment by jennifer-shehane** [comment]
You may be wanting to use the undocumented `cy.now()` command - which basically behaves as a Promise and does not enqueue. 

Method signature is:

```js
cy.now(commandName, args)
```

So, for `cy.get('button')` it would be:

```js
cy.now('get', 'button')
```

**Comment by jennifer-shehane** [comment]
Hey @matti, did this answer your question?

**Comment by matti** [comment]
waiting for my code monkeys to confirm this

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Comment by jiangts** [comment]
interesting. commands like `contain` and `type` don't work through the `now` interface, but `get` and `click` do. Any place where I can find the list of working commands?

**Comment by jennifer-shehane** [comment]
Yeah, this is a bit on why it's undocumented, because it gets weird. We never intended it to be public. You can see some uses of `cy.now()` in our own code: https://github.com/cypress-io/cypress/search?q=%22cy.now%22&unscoped_q=%22cy.now%22

**Comment by lukegorman** [comment]
Interactive cypress would save me hours of tinkering,

**Comment by lukegorman** [comment]
Interactive cypress would save me hours of tinkering,

**Comment by matti** [comment]
agreed - cypress would be 10x better with this

**Comment by umanghome** [comment]
Having access to a terminal or something where I can input cypress commands while being paused via `cy.pause()` would be amazing. Currently, every time I need to check if something works, my 30-second test starts all over again. `cy.now()` doesn't work reliably with custom commands either. :(
