### ISSUE TITLE
Stub request headers response control work only for lowercase headers names

### ISSUE THREAD

**Issue by miwaniak** [cypress-io/cypress#3637]
### Current behavior:
Currently I'm not able to control response headers of  requests subbed by Cypress when headers name have any uppercase letter.

```javascript
cy.server({
  headers: {
    'x-token': 'abc-123-foo-bar'
  }
})
cy.route('GET', '/users/1', { id: 1, name: 'Amanda' }).as('getUser')
cy.visit('/users/1/profile')
cy.wait('@getUser').its('responseHeaders')
  .should('have.property', 'x-token', 'abc-123-foo-bar') // true
```

work ok but: 

```javascript
cy.server({
  headers: {
    'xToken': 'abc-123-foo-bar'
  }
})
cy.route('GET', '/users/1', { id: 1, name: 'Amanda' }).as('getUser')
cy.visit('/users/1/profile')
cy.wait('@getUser').its('responseHeaders')
  .should('have.property', 'xToken', 'abc-123-foo-bar') // true
```

dont work 

### Desired behavior:
I would like to be able to control response headers of requests subbed by Cypress when headers name contains uppercase and lowercase letters:

```javascript
cy.server({
  headers: {
    'xToken': 'abc-123-foo-bar'
  }
})
cy.route('GET', '/users/1', { id: 1, name: 'Amanda' }).as('getUser')
cy.visit('/users/1/profile')
cy.wait('@getUser').its('responseHeaders')
  .should('have.property', 'xToken', 'abc-123-foo-bar') // true
```
should work ok

### Versions
Cypress package version: 3.1.5
Cypress binary version: 3.1.5

**Comment by jennifer-shehane** [comment]
May be related https://github.com/cypress-io/cypress/issues/2879

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
