### ISSUE TITLE
Feature request: let me use aliased values directly as parameters to 'should'

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3638]
### Desired behavior:

I'd like to reference aliases in `should` parameters.

For example, testing a progress bar, I'd love it if I could write:

```js
  it('updates the progress bar', function() {
      cy.get('progress')
        .then($el => parseFloat($el.attr('value')))
        .as('progress0')
        .should('be.greaterThan', 0);
      cy.wait(2000);
      cy.get('progress')
        .then($el => parseFloat($el.attr('value')))
        .should('be.greaterThan', '@progress0');
  });
```

Instead, I have to implement it like this:

```js
  it('updates the progress bar', function() {
      cy.get('progress')
        .then($el => parseFloat($el.attr('value')))
        .as('progress0')
        .should('be.greaterThan', 0);
      cy.wait(2000).then(function() {
        cy.get('progress')
          .then($el => parseFloat($el.attr('value')))
          .should('be.greaterThan', this.progress0);
      });
  });
```

IMO, the first one is cleaner and doesn't rely on an unnecessary nested `then` function (or on the `this.` syntax which I don't like here).

If course, this would technically be a breaking change, since some users might actually have `'@'` characters at the beginning of the strings they're checking for.
In this case, maybe there'd be some way to escape them (`'@@'` ?)

If this is untenable, I'd settle for something like `cy.ref('@progress0')`.

### Versions

cypress 3.1.5

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
