### ISSUE TITLE
I keep getting Timed out retrying: Expected to find element but could not found it

### ISSUE THREAD

**Issue by mv7789** [cypress-io/cypress#3641]
I am using cypress for the first time and started with basic login test and keep getting this error message: CypressError: Timed out retrying: Expected to find element: name=username , but could not found it.
describe('My first cypress test', () => {

    it('Navigate to Testwebsite', ()=> {
        cy.visit('website/login')

        
    })
    it('Login to application', () => {
             
        cy.get('input[name=username]').click()
        //cy.get('button').click()
        
        
        
        
    })

})

**Comment by Songyu-Wang** [comment]
shouldn't it be `input[name="username"]`?

**Comment by mv7789** [comment]
I tried all combinations it doe snot work at all... keep getting the same error

**Comment by Bkucera** [comment]
@mv7789 sorry, without a reproducible example I'll have to close this issue. Feel free to update it and leave a comment if you feel this should be re-opened.
