### ISSUE TITLE
Cypress return 'Whoops, there is no test to run' after 302 Redirect

### ISSUE THREAD

**Issue by dinesh-domain** [cypress-io/cypress#3642]
### Current behavior:

We are using cypress for our user management web app

On click of a button to remove linked app, a post request is sent and `302` is returned

Cypress instead of following the `302` redirect navigating to **`https://{base_url}/__/`** and **`Whoops, there is no test to run.`** error message is displayed

We are not behind any corporate proxy.

Strange thing is instead of redirecting in app in test runner, the redirection happens in the main window which have both tests window on left and runner on right

anyone else faced this issue

### Desired behavior:
Cypress should follow redirect

### Steps to reproduce: (app code and test code)
cypress log
```
GET /Assets/svg/menu.svg 200 24.370 ms - -
GET /Assets/svg/ic_arrow_drop_down_white_24px.svg 200 38.415 ms - -
GET /App/Shared/component-panel.html 200 17.978 ms - -
GET /Assets/fonts/toadOcfmlt9b38dHJxOBGJ6-ys_j0H4QL65VLqzI3wI.woff 200 26.811 ms - -
GET /App/ConnectedApps/connected-app-card.html 200 47.962 ms - -
**POST /connected-apps/remove 302 0.743 ms - 52**
GET /__/ 200 10.852 ms - -
GET /__cypress/runner/cypress_runner.css 200 90.550 ms - -
```

This is the button html if it helps:
```html
<button class="md-primary md-button md-default-theme md-ink-ripple" type="button" ng-transclude="" ng-click="dialog.hide()" md-autofocus="dialog.$type==='alert'" aria-label="OK"><span class="ng-binding ng-scope">OK</span></button>
```

### Versions

Cypress 3.1.5
Windows 10
Chrome 72

**Comment by flotwig** [comment]
@dinesh-domain Can you share the code of how you are performing the actual redirect? It's possible that you're redirecting from `window.top` instead of `window` which would cause this behavior.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
