### ISSUE TITLE
Mouse leave event not triggered

### ISSUE THREAD

**Issue by mparpaillon** [cypress-io/cypress#3644]
### Current behavior:

While `.trigger('mouseover');` triggers onMouseEnter event but `.trigger('mouseleave');` doesn't trigger onMouseLeave event (React app)

### Desired behavior:

`.trigger('mouseleave');` should trigger onMouseLeave event

### Steps to reproduce: (app code and test code)

Checkout this stackblitz: https://stackblitz.com/edit/react-dmfnux?file=index.js
"Enter" and "leave" events both work well

Try this test

```js
context('Hovering', () => {
  it('should load properly', () => {
    cy.visit('https://react-dmfnux.stackblitz.io');
    cy.get('#target', { timeout: 60000 }).should('be.visible');
  });

  it('should trigger mouseleave event', () => {
    cy.get('#target').trigger('mouseover');
    cy.get('#text').should('contain', 'enter');
    cy.get('#target').trigger('mouseleave');
    cy.get('#text').should('contain', 'leave');
  });
});
```

and see it fail

<img width="655" alt="capture d ecran 2019-03-05 a 10 59 04" src="https://user-images.githubusercontent.com/1062115/53797067-b8ef0700-3f35-11e9-9a14-a8299907537e.png">

### Versions

Chrome 72, Mac OS Mojave, Cypress 3.1.5

**Comment by Bkucera** [comment]
Your app is listening for `mouseout` as shown here:

![image](https://user-images.githubusercontent.com/14625260/53833689-20697e80-3f57-11e9-8319-8f14cfc51735.png)


React does this under the hood, when you set `onMouseEnter`/`onMouseLeave`, it listens on `mouseover`/`mouseout`.

**Comment by mparpaillon** [comment]
Thanks @Bkucera !

**Comment by isanda-notshe** [comment]
Thank you @Bkucera  :)
