### ISSUE TITLE
Browser - Cypress fails to recognize Chrome

### ISSUE THREAD

**Issue by ZutroyBE** [cypress-io/cypress#3645]
Cypress sees the Chrome executable but fails to recognize it.

### Current behavior:

"Can't run because you've entered an invalid browser.
Browser: 'chrome' was not found on your system."

` D:\BuildAgent\work\e22e2e83d35eda58>npx cypress run --browser chrome`
>
>   cypress:launcher checking one browser chrome +0ms
>   cypress:launcher looking up chrome on win32 platform +0ms
>   cypress:launcher exe path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe +0ms
>   **cypress:launcher found C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ? true +0ms**
>   **cypress:launcher browser chrome not installed +47ms**
>   cypress:launcher checking one browser chromium +0ms
>   cypress:launcher looking up chromium on win32 platform +0ms
>   cypress:launcher exe path C:\Program Files (x86)\Google\chrome-win32\chrome.exe +0ms
>   cypress:launcher found C:\Program Files (x86)\Google\chrome-win32\chrome.exe ? false +0ms
>   cypress:launcher browser chromium not installed +0ms
>   cypress:launcher checking one browser canary +0ms
>   cypress:launcher looking up canary on win32 platform +0ms
>   cypress:launcher exe path C:\Users\DVB\AppData\Local\Google\Chrome SxS\Application\chrome.exe +0ms
>   cypress:launcher found C:\Users\DVB\AppData\Local\Google\Chrome SxS\Application\chrome.exe ? false +0ms
>   cypress:launcher browser canary not installed +0ms
>   cypress:launcher checking one browser chrome +2s
>   cypress:launcher looking up chrome on win32 platform +0ms
>   cypress:launcher exe path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe +0ms
>   cypress:launcher found C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ? true +32ms
> Warning: We failed to remove old browser profiles from previous runs.
> 
> This error will not alter the exit code.
> 
> [object Object]
>   cypress:launcher browser chrome not installed +62ms
>   cypress:launcher checking one browser chromium +0ms
>   cypress:launcher looking up chromium on win32 platform +0ms
>   cypress:launcher exe path C:\Program Files (x86)\Google\chrome-win32\chrome.exe +0ms
>   cypress:launcher found C:\Program Files (x86)\Google\chrome-win32\chrome.exe ? false +0ms
>   cypress:launcher browser chromium not installed +0ms
>   cypress:launcher checking one browser canary +0ms
>   cypress:launcher looking up canary on win32 platform +0ms
>   cypress:launcher exe path C:\Users\DVB\AppData\Local\Google\Chrome SxS\Application\chrome.exe +0ms
>   cypress:launcher found C:\Users\DVB\AppData\Local\Google\Chrome SxS\Application\chrome.exe ? false +0ms
>   cypress:launcher browser canary not installed +0ms
> **Can't run because you've entered an invalid browser**.
> 
> **Browser: 'chrome' was not found on your system**.
> 
> Available browsers found are: electron

### Desired behavior:

The Chrome browser is found and recognized.

### Steps to reproduce: (app code and test code)

Clear the App Data (just in case)
- Open up the cypress app
- Go to File -> View App Data
- Delete everything in here

Run cypress with chrome
`set DEBUG=cypress:launcher`
`npx cypress run --browser chrome`

### Versions

Cypress package version: 3.1.5
Cypress binary version: 3.1.5

Windows 7 Professional 64-bit
Service Pack 1

Chrome: Version 72.0.3626.121 (Official Build) (32-bit)

**Comment by jennifer-shehane** [comment]
@ZutroyBE Check out our [debugging guide for launching browsers](https://on.cypress.io/debugging#Launching-browsers). Let us know if you're still having issues after that.

**Comment by ZutroyBE** [comment]
I did, it didn't help:
- I checked the logs
- Chrome is installed at the default location and Cypress sees chrome.exe .
- I cleared the App Data

**Comment by flotwig** [comment]
@ZutroyBE can you paste the output of running this command in Command Prompt?

`wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value`

Cypress runs this same command internally to validate your browser. It should output something like `Version=72.0.3626.11`.

**Comment by ZutroyBE** [comment]
> D:\BuildAgent\work\e22e2e83d35eda58>wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value
> datafile - Alias not found.

We've got a winner 🥇

**Comment by flotwig** [comment]
I found a thread about a similar issue with WMIC: [wmic aliases not available](https://social.technet.microsoft.com/Forums/en-US/f5755283-2881-44fa-8b9f-a67ab591c45f/wmic-aliases-not-available?forum=ITCG)

I'm not sure why this is happening. The WMIC `datafile` alias exists on Windows 7... is this an old install of Windows? Some of the comments in that thread mention that the local WMIC database can become invalid over time.

In the long run, maybe Cypress should move away from using WMIC since it's deprecated and there are other ways of finding .exe version that might be more reliable such as using [win-version-info](https://www.npmjs.com/package/win-version-info) or the new CIM APIs that are supposed to replace WMIC.

**Comment by ZutroyBE** [comment]
It is quite old and - I assume - was used to test many products 💪 
> systeminfo
> ...
> Original Install Date:     29/Sep/2010, 5:12:57 AM
> System Boot Time:          20/Feb/2019, 4:06:34 PM

I got it working after rebuilding the WMI repository:
```
net stop winmgmt /y
C:
cd \Windows\System32\wbem
ren repository bk_repository
for /f %s in ('dir /s /b *.mof *.mfl') do mofcomp %s
```

Having a corrupt repository doesn't seem that uncommon. Cypress should probably log if the wmic step fails for now. I'm not familiar with those kind of tools, but anything not deprecated doesn't sound so bad 😃

**Comment by flotwig** [comment]
Glad to hear that you were able to get it working! Yes, the browser launcher does swallow some useful error information at times. I'll make a new issue for potentially updating the way we do Windows version checks. Closing this.

**Comment by ahillikerMDSOL** [comment]
I am having this issue as well.
When I run the `get version` command mentioned above, chrome is recognized with version 92.0.4515.159.
I tried running the WMI repository rebuild mentioned above and got access denied when running `ren repository bk_repository` but the next line executed successfully (figured I'd give it a shot).
I am unable to view anything when I open `view app data` so I can't clear that... any input would be appreciated.

Running WSL2 on windows 10, cypress v.8.3.0 (also tried upgrading to latest version of cypress with no effect).
