### ISSUE TITLE
AssertionError [ERR_ASSERTION]: path must be a string

### ISSUE THREAD

**Issue by smartHasmukh** [cypress-io/cypress#3647]
This issue faced while create a report

![screenshot from 2019 03 05 17 03 40](https://user-images.githubusercontent.com/8941195/53802861-ed2feb00-3f68-11e9-8c41-224745ee5115.png)

**Comment by jennifer-shehane** [comment]
@smartHasmukh Could you provide the configuration you have to set up your report?

**Comment by smartHasmukh** [comment]
Basically I am using four angular application in single project, I need to write cypress code every application so I have created folder strucure like that.

```
-- Cypress
    applicationApp1   
        -- Cypress
              - fixtures
                     -- user.json
                     -- route.json
              - Integration
                    -- signup_spec.js
                    -- login_spec.js
                    -- user_profile_spec.js
              -  Plugin
                    -- index.js
              -  Reporters
                   --  custom.js
              - Support 
                   -- index.js
                   -- command.js
                   -- login.js
                   -- signup.js
                   -- profile.js
              - cypress.json


    --applicationApp2
        -- Cypress
              - fixtures
                     -- user.json
                     -- route.json
              - Integration
                    -- signup_spec.js
                    -- login_spec.js
                    -- user_profile_spec.js
              -  Plugin
                    -- index.js
              -  Reporters
                   --  custom.js
              - Support 
                   -- index.js
                   -- command.js
                   -- login.js
                   -- signup.js
                   -- profile.js
              - cypress.json

```

in `cypress.json` file 1st application 

```
{
  "baseUrl": "http://localhost:4200/",
  "video": true,
  "fixturesFolder": "cypress/fixtures",
  "integrationFolder": "cypress/integration",
  "pluginsFile": "cypress/plugins/index.js",
  "supportFile": "cypress/support/index.js",
  "screenshotsFolder": "cypress/screenshots",
  "reporter": "cypress/reporters/custom.js",
  "trashAssetsBeforeRuns": true

}
```

**Project open command**
```
cypress open --project='cypress/applicationApp1'
cypress open --project='cypress/applicationApp2'
```

cypress open command work successfully and also tested my application but when i am trying to make a report then it will through error

**Project run command for report**

```
cypress run --reporter cypress/reporters/custom.js --project='cypress/applicationApp1
```

and I have created user.json

```
{
  "email_address": "hasmukh@mailinator.com",
  "pwd": "hasmukh@123",
}
```
but i want to add usng fixture in `integration spec.js file` but fixture is not working 

```
beforeEach(()=>{
       cy.fixture('user').as('userObj');
    });
    
    it('Login test',()=>{
        cy.visit('login');
        cy.get('input[email]').type(userObj['email']);
    });
```
It's doesn't work. so I am using 

```
import userObj from '../fixtures/user';
```
like that


I have asked 2 quiestions so if any doubt on my questions then I will explain in brif

**Comment by jennifer-shehane** [comment]
To reference the `user.json` alias, you need to use `this.userObj`, not just `userObj`. https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context

Also, accessing aliases as properties with `this.*` will not work if you use arrow functions for your tests or hooks.

You'll need to use the regular `function () {}` syntax as opposed to the lambda “fat arrow” syntax `() => {}`.

---

You may want to use double quotes for each argument you're passing in the `cypress run` command. We've seen some variability in how this can be read depending on the OS. So try:

```
cypress run --reporter="cypress/reporters/custom.js" --project="cypress/applicationApp1"
```

**Comment by smartHasmukh** [comment]
To reference the `user.json` alias, you need to use `this.userObj`, not just userObj. 
You'll need to use the regular `function () {}` syntax as opposed to the lambda “fat arrow” `syntax () => {}`.

> It's working fine for me
 `syntax () => {}` - I was ussed arrow syntax that's issue.

Thank for helping me.

-------------------------------------------------------------------------------------------------------------------------------------------

### But Report is not working
`cypress run --reporter="cypress/reporters/custom.js" --project="cypress/applicationApp1"` This is not workig. I am getting error. I attached screenshot.

I am using OS `Ubuntu 18.04(Linux)`
Project in `Angular 6 (CLI)`
Cypress Package `"cypress": "^3.1.5",`

![cypress_issue](https://user-images.githubusercontent.com/8941195/53932285-e1eed380-40be-11e9-8397-dc4b79965d2e.png)

Please let me know if you want to more clarify

**Comment by jennifer-shehane** [comment]
@smartHasmukh Are you still experiencing this issue? I was a bit confused by the last comment. 

Please close issue if resolved.

**Comment by smartHasmukh** [comment]
@jennifer-shehane Report command not working

### Report is not working
cypress run --reporter="cypress/reporters/custom.js" --project="cypress/applicationApp1" This is not workig. I am getting error.

**Comment by jennifer-shehane** [comment]
Hey @smartHasmukh, could you share the code inside your `cypress/reporters/custom.js` file?

**Comment by smartHasmukh** [comment]
There is no code. It's a blank file. I just put the route in `cypress.json` file

> cypress.json

`{
  "baseUrl": "http://localhost:4500/",
  "video": true,
  "fixturesFolder": "cypress/fixtures",
  "integrationFolder": "cypress/integration",
  "pluginsFile": "cypress/plugins/index.js",
  "supportFile": "cypress/support/index.js",
  "screenshotsFolder": "cypress/screenshots",
  "reporter": "cypress/reporters/custom.js",
  "trashAssetsBeforeRuns": true
}
`

Shall I need to add code in custom.js?

**Comment by jennifer-shehane** [comment]
Is there a reason you are passing in a reporter that is an empty js file? Does this still error when you remove the reporter argument?

**Comment by smartHasmukh** [comment]
I think so
But I found another way to run the project and get report on `cypress dashboard`

`cypress run --project='cypress/applicationApp1' --record --key xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxc42`

@jennifer-shehane Thank you for replied me.

__________________________________________________________________________________


### I have one questions

 **Can we find responsive design test report?** 

If yes then How?

I need a reference only

**Comment by jennifer-shehane** [comment]
I don't know much about available outside reporters to be honest, you'd have to do some googling.
