### ISSUE TITLE
TypeError: Cannot redefine property: replace

### ISSUE THREAD

**Issue by lamartire** [cypress-io/cypress#3648]
### Current behavior:

```js
cy.window().then(win => {
  cy.spy(win.location, 'replace').as('locationReplace');
});
```

Or: 

```js
cy.window().then(win => {
  cy.stub(win.location, 'replace').as('locationReplace');
});
```

Now throws an error `TypeError: Cannot redefine property: replace`

### Desired behavior:

`location` methods can be replaced with stubs or be spyed.

### Steps to reproduce: (app code and test code)

Just try this at any website.

### Versions

**OS**: osx 10.14.3
**Cypress**: 3.1.5
**Browser**: Chrome  72.0.3626.119

**Comment by flotwig** [comment]
[`window.location` is read-only](https://developer.mozilla.org/en-US/docs/Web/API/Window/location), so that's why you're getting this error. The browser won't allow you to modify this object.

Are you trying to assert on a `location` change? Have you tried using the `cy.url()` or `cy.location()` APIs for your needs?

Example of using `cy.url()` to assert on location change (from the docs):
```js
// clicking the anchor causes the browser to follow the link
cy.get('#user-edit a').click()
cy.url().should('include', '/users/1/edit') // => true
cy.url().should('eq', 'http://localhost:8000/users/1/edit') // => true
```

**Comment by mrmojica** [comment]
Hey @flotwig, I was running into a similar error where I wanted to try and stub `window.location.replace(url)` and do something like `expect(stub).to.be.calledOnce` after a user clicks a button that redirects the user to a new page. Would you also suggest I just assert the `location` change?

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Comment by willm** [comment]
How can we do this with locations on a different host?

**Comment by MattSidor** [comment]
My app uses `window.location.replace` to redirect to a different host.

How do we stub this functionality to prevent the redirect in Cypress, but still test that it was called with the correct URL?

**Comment by bahmutov** [comment]
Take a look at how I would solve this problem https://glebbahmutov.com/blog/cypress-tips-and-tricks/#deal-with-windowlocationreplace
