### ISSUE TITLE
Chaining is broken when reusing same options object in `.type()` command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#365]
Here is a good one (Cypress 0.18.4)

This works
```js
const dontLog = {log: false}
  cy
    .visit(url)
    .get('[name=email]', dontLog).clear().type(email, dontLog)
    .get('[name=password]', dontLog).clear().type(password, {log: false})
    .get('button', {log: false}).click({log: false})
```
This does not work (enters the password in the *email* field instead
```js
const dontLog = {log: false}
  cy
    .visit(url)
    .get('[name=email]', dontLog).clear().type(email, dontLog)
    .get('[name=password]', dontLog).clear().type(password, dontLog)
    .get('button', {log: false}).click({log: false})
```

The above code is inside custom command `Cypress.addParentCommand('login') {...}`

I am attaching the video (without clicking submit so it stops and shows the problem)

![login-problem-gif](https://cloud.githubusercontent.com/assets/2212006/21546993/2ed31c84-cdb1-11e6-97df-a8d04f1c1773.gif)

**Comment by bahmutov** [comment]
If I try freezing the options object, it throws an error "TypeError: Cannot read property 'is' of undefined".
```js
const dontLog = Object.freeze({log: false})
  cy
    .visit(url)
    .get('[name=email]', dontLog).clear().type(email, dontLog)
    .get('[name=password]', dontLog).clear().type(password, dontLog)
```

**Comment by brian-mann** [comment]
Yah we are internally mutating those objects which makes sense why this fails. Probably should not be doing that, should clone them first.

Curious why you can't use `cy.request` here, instead of using your UI to perform those same actions. I'm guessing you're wrapping this up as a custom command.

**Comment by bahmutov** [comment]
this is a custom login command, which includes CSRF token. You probably want to use at least `Cypress._.clone(options)` ;)

**Comment by brian-mann** [comment]
How's it flakier? It should be much *less* flakier and much faster.
