### ISSUE TITLE
Chrome Cypress browser adds "charset=utf-8" to the content-type in the response header

### ISSUE THREAD

**Issue by funatronics** [cypress-io/cypress#3650]
### Current behavior:

Some of my website's HTTP requests are failing only in the Cypress browser (e.g. signing up for a new account). After debugging, it was discovered this was due to the response header returning a different `content-type` in the Cypress browser.

Chrome browser:
```
content-type: application/json
```

Cypress browser (not running headlessly):
```
Content-type: application/json; charset=utf-8
```

Cypress is adding `"charset=utf-8"` to the `content-type`.

### Desired behavior:

Return the same `content-type` as the Chrome browser.

### Versions

3.1.5
Chrome 72

**Comment by yusinto** [comment]
I also encountered the same problem. Previously my app checks the Content-Type of the http response by doing a string comparison which fails. I refactored it so it checks the existence of the desired type instead:

```js
// wrong
if(response.headers.get('Content-Type') === 'application/json')

// right
response.headers.get('Content-Type').includes('application/json')
```

I don't think you can always safely assume that browsers will only send 'application/json' in the Content-Type header. Hope that helps.

**Comment by funatronics** [comment]
@yusinto yeah, that was my solution to this problem as well.

**Comment by ludwikd** [comment]
In my case strange is that, 
when running test on _locally deployed_ (localhost) web page, the header is unchanged: `application/json`
But when testing the same web app _remotely deployed_ (s3 + CloudFront), the header is extended with `charset=utf-8`

**Comment by flotwig** [comment]
This is a symptom of ExpressJS (which Cypress uses for the internal proxy server) forcing `charset=utf-8` on all responses, which will be fixed by #4698.

**Comment by tradesyjesse** [comment]
Thank you!

**Comment by funatronics** [comment]
Thank you!
