### ISSUE TITLE
Error: Cannot find module 'node-zlib-backport' from '.../node_modules/pngjs/lib'

### ISSUE THREAD

**Issue by janusqa** [cypress-io/cypress#3653]
### Current behavior:

Running test with a `blink-diff` import causes error
```
Error: Cannot find module 'node-zlib-backport' from '.../cypress-test-tiny-plugin-esm/node_modules/pngjs/lib'
```

### Steps to reproduce: (app code and test code)

https://github.com/janusqa/cypress-test-tiny-plugin2-esm

Run test to see error.

### Versions

chrome: Version 72.0.3626.121 (Official Build) (64-bit)
linux: Ubuntu 18.04.2 LTS
Cypress package version: 3.1.5
Cypress binary version: 3.1.5

**Comment by nym** [comment]
Also having this issue.

**Comment by jennifer-shehane** [comment]
I was able to reproduce the error with the repo provided with Cypress version 3.3.0.

This looks to be a problem from `pngjs` with browserify which has been fixed https://github.com/lukeapage/pngjs/issues?q=is%3Aissue+sort%3Aupdated-desc+node-zlib-backport+is%3Aclosed a long time ago https://github.com/toriningen/pngjs/commit/9181129ea8acad6cb77e5842af89164603348fcc

`pngjs` is a dependency of `blink-diff`

```
cypress-test-tiny@1.0.0 /Users/jennifer/Dev/cypress-test-tiny-plugin2-esm
└─┬ blink-diff@1.0.13
  └─┬ pngjs-image@0.11.7
    └── pngjs@2.3.1
```

There's a current issue to upgrade `pngjs` in `blink-diff` you may want to comment on: https://github.com/yahoo/blink-diff/issues/32 But it looks like their still using the `pngjs` version from 2016, so not sure.

Someone also mentioned:

>I believe you can tell browserify to ignore modules (null them out). Thats what another project using browserify with this package is doing.
