### ISSUE TITLE
Throws error on Cypress.log without previous command

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3658]
Cypress 3.1.5 on Mac

```js
/// <reference types="cypress" />
it('works', () => {
  Cypress.log('after hook')
})
```

Throws error 
<img width="697" alt="screen shot 2019-03-06 at 12 05 52 pm" src="https://user-images.githubusercontent.com/2212006/53899451-35eab100-4008-11e9-8b14-6167f24f1af5.png">

Code that throws

```js
    _.defaults(obj, current != null ? current.pick("name", "type") : void 0);
    if (!parentOrChildRe.test(obj.type)) {
      obj.type = current.hasPreviouslyLinkedCommand() ? "child" : "parent";
    }
```

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/log.coffee#L117

**Comment by louise-hayes** [comment]
I'd like to try resolve this?

**Comment by bahmutov** [comment]
sure, try @louise-hayes and if I may suggest
- write a test that is initially failing
- add a guard around the failing line to fix the failing test

**Comment by vrockai** [comment]
What is the expected behaviour? `Cypress.log` [doesn't accept a string as an argument](https://docs.cypress.io/api/cypress-api/cypress-log.html#Syntax), therefore I would assume an exception is expected. 

FTR it throws the same exception even if I put a command before it:
```coffee
describe "issue 3658", ->
  it 'Cypress.log should not throw an exception', ->
    cy.visit('/fixtures/generic.html')
    expect(=> Cypress.log('arbitrary_string')).not.to.throw()
```
