### ISSUE TITLE
Can't start/run any tests from the GUI (macOS)

### ISSUE THREAD

**Issue by buz-zard** [cypress-io/cypress#366]
Hi everyone,

I followed these [steps](https://docs.cypress.io/docs/installing-and-running#section-adding-projects) to setup project and got an EROFS error.
 Steps:
- Add a project.
- Click on the project.
- An error occurs.

System: macOS 10.12.2 (16C67)
Cypress version: 0.18.4
Exact error: `EROFS: read-only file system, open '/private/var/folders/wt/8txpxrj92d5ghm6gm2fykq_w0000gn/T/AppTranslocation/5B2023BF-DFBF-4110-BF48-FF4F0DBBB834/d/Cypress.app/Contents/Resources/app/node_modules/@cypress/core-extension/dist/background.js'`
Screenshot: 
![image](https://cloud.githubusercontent.com/assets/3521740/21566185/1fb1c716-cea9-11e6-8af6-db53f06a562e.png)

Also: cypres folder and cypres.json are also generated.

Somewhat similar issue, but I'm running on the same user, and error message is different #358

Thanks.

**Comment by chrisbreiding** [comment]
This is a (known issue caused by macOS's translocation feature)[https://github.com/cypress-io/cypress/issues/245].
