### ISSUE TITLE
Cannot type into a, link, or select element

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3661]
Cypress should be able to type into any focusable element, in case users want to test event listeners attached to the element

**Comment by fr0** [comment]
You should also be able to type into any element that has a `tabindex` attribute.

**Comment by jennifer-shehane** [comment]
@fr0 This is already currently supported. The current rules are:

>Cypress considers the 'body', 'textarea', any 'element' with a 'tabindex' or 'contenteditable' attribute, or any 'input' with a 'type' attribute of 'text', 'password', 'email', 'number', 'date', 'week', 'month', 'time', 'datetime', 'datetime-local', 'search', 'url', or 'tel' to be valid typeable elements.
