### ISSUE TITLE
Default installation of Cypress won't run tests under Chrome 72

### ISSUE THREAD

**Issue by webdevbe** [cypress-io/cypress#3667]
### Current behavior:

I discovered this for the first time in my own source code. While creating a minimal example, I found that even the default installation of Cypress gives me these results. When running `cypress open` and running the tests under Chrome 72. I'm getting this message
![image](https://user-images.githubusercontent.com/1104252/53969864-d5d43780-40f9-11e9-8487-ea6e9cc8f6e6.png)

I've searched through the existing issues in Cypress and sometimes found similar issues, but there could be more because the error message depends on the site you are targetting. Currently it looks a lot like the last comment in https://github.com/cypress-io/cypress/issues/1872

I've also read about proxies and firewalls, but couldn't detect any I would be behind. It's also worth mentioning that the tests do run in Electron.

### Desired behavior:

I want the tests to run as expected. 

### Steps to reproduce: (app code and test code)

```mkdir test-app
cd test-app
npm init (enter, enter, enter, etc.)
npm install cypress --save-dev
npx cypress open
run tests under Chrome
```

### Versions

Tested on Win10 64bit with Cypress 3.1.5

**Comment by flotwig** [comment]
@webdevbe Can you share your spec code? This looks like an error from GitHub Pages, not from Cypress, so it's hard to tell what's going on.

Do you see the [reporter](https://cloud.githubusercontent.com/assets/1157043/17947006/bffba412-6a18-11e6-86ee-af7e9c9d614e.png) window when you run your Cypress tests?

**Comment by webdevbe** [comment]
Hi @flotwig ,

Sorry, I didn't notice I pasted a partial screenshot. I see the reporter window for just a moment and then I see that page with the 404. Here is already a screenshot:
![image](https://user-images.githubusercontent.com/1104252/54013600-08be1000-417a-11e9-94c2-05b0cf3b8180.png)

I'll create a small repo in a moment and attach it to the ticket. 

Regards

**Comment by webdevbe** [comment]
An example repository can be found at https://github.com/webdevbe/cypress-404-error

**Comment by jennifer-shehane** [comment]
@webdevbe The repo you've linked to just looks to be running the example tests we seed to the project - visiting `https://example.cypress.io` - is this correct?

This looks like the 404 page for GitHub pages. Our `https://example.cypress.io` *is* hosted on GitHub pages, but looks to be loading for me within Chrome.

- Can you visit `https://example.cypress.io` from within your Chrome 72 (outside of Cypress) and see if it loads there?

**Comment by webdevbe** [comment]
Hi @jennifer-shehane , yes that's correct. Even with the basic installation it looks like it's failing.
The link is working in my regular Chrome browser. Please do note, that running the linked repo in Electron, does work.

**Comment by webdevbe** [comment]
Would a screencast help to identify the problem more? I can see the reporter window just for a split second, before it shows me that Github 404 page.

**Comment by jennifer-shehane** [comment]
Yeah, super strange. A recorded video *may* reveal something. I'm not sure.

- Do you have a ProxyMode policy set within Chrome? https://github.com/cypress-io/cypress/issues/1253
- Any other custom settings with Chrome? Extensions?

**Comment by webdevbe** [comment]
I found a ProxyMode key indeed, but not in the path that #1253 described, but rather in HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update whose value is set to fixed_servers. Also there is a ProxyServer key specified. But even with local admin rights, I'm unable to delete these :( (error appears) 

Is this the reason the bug is happening?

I can check with our IT team to see if these keys (or the entire policy) can be removed but I'm afraid not. 

Meanwhile I'll try to setup a vm where Chrome is installed to perform the tests there.

**Comment by flotwig** [comment]
Yeah, that's probably the issue. Cypress can't currently circumvent the `ProxyMode` setting, so you're best off asking your admins to disable it for you, or using a VM like you're doing. You can also run your tests in the built-in Electron browser, which won't experience this problem.

**Comment by webdevbe** [comment]
Hi @flotwig and @jennifer-shehane ,

The registry keys were now deleted but the issue is still persisting. For now I'll use the Electron browser indeed. I saw some integrations from Cypress coming up regarding throwing a warning when working behind a corporate proxy. Maybe that shows some more valuable information.

Thanks for the support, I'll close the ticket for now.
