### ISSUE TITLE
Related to #109. Click() worked in the page, but DOM detached exception is raised

### ISSUE THREAD

**Issue by mpagamici** [cypress-io/cypress#3670]
### Current behavior:
```
CypressError: `cy.click()` failed because this element is detached from the DOM.

<td _ngcontent-c12="" class="adress">Hauptst...</td>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.wrap()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
```

### Desired behavior:
`cy.click()` actually didn't fail !
The `click()` was successfully allowing the re-rendering of my page (during replay), I don't understand why the 'DOM detached' exception is raised. --> Is it possible to suppress the fault ? Can I add an exception handler (catch) to allow my script to continue execution ? 

### Versions
Chrome 72, Cypress 3.1.5, Mac OS X Mojave

**Comment by jennifer-shehane** [comment]
Hey @mpagamici, your DOM element was detached from the DOM sometimes in between your getting the DOM element and it being called within `cy.wrap()`. Try regetting the element closer to the command you want to perform with another `cy.get()`. 

Issues in our GitHub repo are reserved for potential bugs or feature requests, so I will be closing this.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options
