### ISSUE TITLE
Change the way that Windows browser version checks are done

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3672]
Currently, the launcher checks Windows browser versions by running a command like this in the shell:

```
C:\> wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value

Version=72.0.3626.11
```

However, WMIC was [deprecated in Windows Server 2012](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831568(v=ws.11)#wmi-providers):

> The WMI command-line tool (Wmic) is deprecated. Use PowerShell cmdlets instead.

The WMIC database can also get corrupted, which causes issues for users since this will prevent them from launching browsers (see #3645)

We should probably replace our usage of WMIC with querying [CIM](https://docs.microsoft.com/en-us/windows/desktop/WmiSdk/common-information-model), the successor. We could also use a native package like [win-version-info](https://www.npmjs.com/package/win-version-info) to check the versions ourselves.

**Comment by thebib** [comment]
The WMIC tool has been removed from Windows 11 build 22483 and higher so seeing this on a dev channel build of Windows 11

Running this:

`npx cypress run --browser "C:\Program Files\Google\Chrome\Application"`

causes

```
Command failed with ENOENT: wmic datafile where name="C:\\Program Files\\Google\\Chrome\\Application" get Version /value
spawn wmic ENOENT
'wmic' is not recognized as an internal or external command,
operable program or batch file
````

**Comment by flotwig** [comment]
The stable channel (22000.348) still seems to have WMIC at least. We should prioritize this ASAP.

@thebib do you happen to know when this change is going to be released in the stable Win11 channel? I'm having trouble tracking down an exact release for removal.

**Comment by thebib** [comment]
The build it has been removed in is the insider build 22483 however it hasn't been officially documented in that builds release notes. I am not sure if this has intentionally been removed by Microsoft but the tool has been deprecated for a while.

Having a look at it some unofficial insider sites talk about it being removed but nothing official I'm afraid 😰 

http://www.edtittel.com/blog/windows-11-says-sayonara-wmic.html

**Comment by OlsonDev** [comment]
Ran into this today. When is Cypress 10 expected to be released?

**Comment by BlueWinds** [comment]
Should be in a month or two here (please don't quote me on the timeline, 10.0 has some major changes).

If this starts affecting more users, it could be backported into a 9.x release (or feel free to open a PR). It went into 10.0 because it didn't seem urgent, not because of any breaking change.
