### ISSUE TITLE
Give Cypress's extension a static extension ID

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3673]
Currently, the Chrome extension receives a new, dynamically-assigned extension ID whenever it's launched.

If we give it a static extension ID, then users with restrictions on what extensions they can install in Chrome can request for it to be whitelisted by their admins (see #1239)

SO question that shows how to do this: https://stackoverflow.com/questions/23873623/obtaining-chrome-extension-id-for-development

**Comment by jennifer-shehane** [comment]
Relevant issue: https://github.com/cypress-io/cypress/issues/2494
