### ISSUE TITLE
Running cypress with no `project: false` actually runs cypress open

### ISSUE THREAD

**Issue by Toxicable** [cypress-io/cypress#3675]
### Current behavior:
Running `cypress.run({project: false})` opens cypress with `cypress open` instead.

### Desired behavior:
To run cypress with no config file, instead using the config I specified when calling it.

### Steps to reproduce: (app code and test code)
```js
  const cypress = require('cypress');
  const runners =  cypress.run({
    spec: [], // putting in actual spec file paths here results in same behaviour
    project: false,
    record: false,
    config: {
      video: false,
      screenshots: false,
      chromeWebSecurity: false,
    },
  });
```

### Versions
ubuntu 16.04
chrome 72
cypress 3.1.5

**Comment by jennifer-shehane** [comment]
`project` is always expecting a path value, so `false` is not valid. Honestly, I'm having a hard time even tracking in the code, by just looking, to figure out what it's doing to make it behave like `cypress open` instead. 

**Proposal:** We should update `cypress run` to throw error when specifically passed an invalid `project` key like `false`, `null`, something that is not a valid `path`.

To more specifically address what you're really trying to do here

>To run cypress with no config file, instead using the config I specified when calling it.

Passing `config` here should overwrite values from your `configFile`. You can see how the configuration is being resolved by running the Module API with `cypress.open` and seeing how it prints in the Test Runner as shown [here](https://on.cypress.io/configuration#Resolved-Configuration).

What are you having trouble overriding using the `config` argument?

**Comment by Toxicable** [comment]
>Proposal: We should update cypress run to throw error when specifically passed an invalid project key like false, null, something that is not a valid path.

Sounds good to me!

However, that dosen't solve my issue.
To clarify; I'd like to run cypress without a `configFile` at all.
Currently not specifying a `project` results in cypress throwing an error 

For example:
```
cypress.run({
    spec: specFiles,
    record: false,
    config: {
      video: false,
      screenshots: false,
      chromeWebSecurity: false,
    },
  });
```
Throws this error:
```
Could not find any tests to run.
We looked but did not find a cypress.json file in this folder: /private/var/tmp/_bazel_fabianwiles/c571a69fa4295dd5b9f7cd85a11a7fa1/execroot/myworkspace/bazel-out/darwin-fastbuild/bin/apps/projectname/e2e
```
Yet I specified what spec files to run in the above config 

You may ask why not just make a `cypress.json`?
This is apart of a bigger integration into the Bazel build system: https://github.com/bazelbuild/rules_nodejs/issues/607 and running tests under bazel it's a lot easier to not have to write any config files, it's going to make it much easier if we can specify everything from a Nodejs program.

If we could solve this and those couple of other small issues it'll be very easy for downstream consumers of Bazel to use Cypress with their projects

**Comment by jennifer-shehane** [comment]
Yeah, that is an open issue that has a PR in review: https://github.com/cypress-io/cypress/issues/1369

This is a great use case for allowing `configFile: false`. I would suggest following the issue above and closing this issue.
