### ISSUE TITLE
esm causes an error in cypress runner in windows 7/10 but works ok in linux

### ISSUE THREAD

**Issue by janusqa** [cypress-io/cypress#3678]
### Current behavior:

Using esm in windows 7/10 causes cypress test runner to throw an error about the plugin file
When using command
```
node_modules/.bin/cypress open
```

error:
```
 Can't start server

The plugins file is missing or invalid.

Your pluginsFile is set to ....\cypress\plugins\index.js, but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.

Please fix this, or set pluginsFile to false if a plugins file is not necessary for your project.

Error [ERR_UNKNOWN_STDIN_TYPE]: Unknown stdin file type
```

```node_modules/.bin/cypress run``` however works successfully across linux/windows7/windows10

```node_modules/.bin/cypress open``` works successfully in linux

### Desired behavior:

```
node_modules/.bin/cypress open
```
should also work successfully on windows 7/10

### Steps to reproduce: (app code and test code)

https://github.com/janusqa/janusqa-cypress-test-tiny-plugin3-esm
Run on windows using 
```
node_modules/.bin/cypress open
```

### Versions

Windows: 7/10
Cypress package version: 3.1.5
Cypress binary version: 3.1.5

**Comment by jennifer-shehane** [comment]
The default plugins import must export the config like below in order to be properly read by Cypress:

```js
export default (on, config) => {}
```

Since the `pluginsFile` is set to `cypress\plugins\index.js` and the config for Cypress is not imported there, it is throwing this error. 

If you want to update the default imported file, you can add `pluginsFile` to your `cypress.json` specifying the `cypress\plugins\main.index.js` file and I believe this should work.

**Comment by janusqa** [comment]
@jennifer-shehane 
It does not work.
I am actually trying to do this, but with esm module
https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/server-communication__seeding-database-in-node
```
Using ES modules import/export syntax in your plugins
```
adding ```"pluginsFile": "cypress/plugins/main.index.js"``` to cypress.json takes me back to original issue of import/export not supported across linux/windows. It gives error about using imports.

I can't pick up on anything special you would have done there.
https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/server-communication__seeding-database-in-node

**Comment by chrisbreiding** [comment]
We'll have investigate this to figure out what's wrong. We'd like to support `esm` as a way to make `import/export` work.

Looks like this error is being thrown when the `pluginsFile` gets loaded: 

```
Error [ERR_UNKNOWN_STDIN_TYPE]: Unknown stdin file type
```

A [very quick investigation](https://stackoverflow.com/questions/35820422/unknown-stdin-file-type-error-in-windows) shows that it's probably related to the combination of Electron + Windows + esm.

**Comment by axcosta** [comment]
I use elementary OS 5.0 Juno (built on Ubuntu 18.04.2 LTS / Linux 4.15.0-70-generic / GTK 3.22.30) and also getting the same error:

"Can't start server
The plugins file is missing or invalid.
Your pluginsFile is set to <project_folder_removed>/tests/e2e/plugins, but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.
Please fix this, or set pluginsFile to false if a plugins file is not necessary for your project."

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by marlonmarcello** [comment]
@jennifer-shehane this is till an issue and it's not related to Windows. Can we reopen it?
I am on a 
* Mac
* Cypress 9.1.1
* Node v16.7.0

When trying to use ESM inside my plugins file I get this error:
![Screen Shot 2021-12-06 at 5 04 57 PM](https://user-images.githubusercontent.com/1956448/144947303-fcb57b60-2d8b-48f9-a67c-06f8e3919f54.png)
