### ISSUE TITLE
Should will not wait when used on custom command

### ISSUE THREAD

**Issue by danielberecz** [cypress-io/cypress#3683]
### Current behavior:
The `should()` method will not wait in case of custom command:

### Desired behavior:

The `should()` method waits also in case of custom command

### Steps to reproduce: (app code and test code)

Custom command:
```js
Cypress.Commands.add("position", {prevSubject: 'element'}, ($subject) => {
    return {top: +$subject.get(0).getBoundingClientRect().top.toFixed(0),
        left: +$subject.get(0).getBoundingClientRect().left.toFixed(0)};
});
```
Test:
```js
cy.get('.my-class').position().should('deep.equal', {top: 25, left: 18});
```

This assertion will fail if the condition is not met immediately.

### Versions
cypress: 3.1.5
macOS 10.14.2
Chrome 72.0.3626.121

**Comment by Lakitna** [comment]
Waiting on an upcoming assertion has to be defined for every command, this is no different for custom commands. This is currently not documented. I have solved it a while ago, see https://github.com/cypress-io/cypress/issues/3109#issuecomment-458950740
