### ISSUE TITLE
SecurityError due to accessing a cross-origin frame without navigating outside of the site

### ISSUE THREAD

**Issue by Haegin** [cypress-io/cypress#3685]
### Current behavior:

I've got a very simple test that just loads a website (https://femalefunders.com) and checks the title and some links are present. The first time I ran it some of the tests passed or failed correctly but the last test threw an error and since then every test on every test run has thrown the same error.

> SecurityError: Blocked a frame with origin "https://femalefunders.com" from accessing a cross-origin frame.

### Desired behavior:

The tests shouldn't error and should pass (or fail) correctly. The tests in question aren't accessing an external site or changing the base URL.

### Steps to reproduce: (app code and test code)

1. Clone https://github.com/Haegin/cypress-test-tiny/
2. Checkout the `female-funders` branch
3. Launch Cypress with `CYPRESS_baseUrl='https://femalefunders.com' yarn cypress open`
4. Run the tests. I get the same error in both Electron and Chrome.

### Versions

Cypress: 3.1.5
OS: macOS Mojave 10.14.3
Chrome: 72.0.3626.121 (Official Build) (64-bit)

**Comment by kristian-puccio** [comment]
I'm finding the same thing.

To get around I refresh the tests in Cypress and sometimes I can get through without this error

**Comment by flotwig** [comment]
Does your server send `Content-Type: text/html` as a header? If it doesn't have this, Cypress can show this error: #4238

**Comment by kristian-puccio** [comment]
I've double checked an mine does set the correct header.

One thing I am doing though is generating the test functions inside a context call.
Maybe Cypress needs statically defined tests to cleanup after itself?

**Comment by sainthkh** [comment]
This is still happening at 5.6.0.
