### ISSUE TITLE
Update driver error structure so templates can be used

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#3688]
New error structures are required for the templates that'll be used to render different types of errors in the GUI. These changes will be made in the driver as part of this PR and leveraged by the reporter in a different PR.

The plan is to tackle one of each error type separately, then move onto the next.

Templates:
- [ ] CypressError (single code frame)
- [ ] CypressError (multiple code frames)
- [ ] AssertionError 
- [ ] Spec/App Error

**Comment by jennifer-shehane** [comment]
This was completed as part of #6724 and released in 4.3.0.
