### ISSUE TITLE
Error: EMFILE: too many open files when require external dependencies

### ISSUE THREAD

**Issue by cristopher-rodrigues** [cypress-io/cypress#369]
```
$ cypress run

Started video recording: /foo/figtf.mp4

(Tests Starting)
Oops...we found an error preparing this test file:

/foo/cypress/integration/foo_spec.js

The error was:

Error: EMFILE: too many open files, open '/foo/node_modules/ramda/package.json'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

* A missing file or dependency
* A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

  (Tests Finished)

  - Tests:           0
  - Passes:          0
  - Failures:        1
  - Pending:         0
  - Duration:        0 seconds
  - Screenshots:     0
  - Video Recorded:  true
  - Cypress Version: 0.18.4
Oops...we found an error preparing this test file:
```

**Comment by cezarlz** [comment]
Same error happens here when I require others dependencies like lodash, axios, etc.

**Comment by brian-mann** [comment]
You didn't mention which OS you're on, but this is basically a file watching limit problem. It's quite common for both `browserify` and `webpack`, and there are a bunch of issues open related to that.

By default OSX has an extremely low limit, I think around `256`.

A quick google search yields some solutions - but they are different based on linux vs OSX.

In OSX you can do `ulimit -n 10480`

**Comment by cristopher-rodrigues** [comment]
I try in OSX:

```ssh
sudo launchctl limit maxfiles 512 unlimited
```

thats work for me! 🎉 🎉

**Comment by cristopher-rodrigues** [comment]
@brian-mann should we close this?

**Comment by kentcdodds** [comment]
This solution isn't [working for me](https://github.com/kentcdodds/testing-workshop/issues/4#issuecomment-281407867) :-(

**Comment by kentcdodds** [comment]
Sorry, meant to add: Any help is appreciated. Even if you could just try to set it up locally and let me know if you get the same error, that'd be helpful :)

**Comment by brian-mann** [comment]
Fixed in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).

**Comment by kentcdodds** [comment]
Thank you!

**Comment by kentcdodds** [comment]
Verified. Thank you so much!
