### ISSUE TITLE
Cypress.config not scoped to spec when running all tests in the test runner

### ISSUE THREAD

**Issue by skimi** [cypress-io/cypress#3693]
### Current behavior:

`Cypress.config` is not scoped when running all tests in the test runner.
<img width="434" alt="Screenshot 2019-03-12 at 14 55 10" src="https://user-images.githubusercontent.com/10855180/54205705-228f8800-44d7-11e9-9119-b957aa7b59a0.png">

But it works in cli:
<img width="712" alt="Screenshot 2019-03-12 at 14 53 43" src="https://user-images.githubusercontent.com/10855180/54205781-494dbe80-44d7-11e9-99cf-486a4b92241e.png">

`spec.js`
```js
Cypress.config("hello", "world");

describe("page", () => {
  it("Hello is world", () => {
    cy.wrap(null).should(() => {
      expect(Cypress.config("hello")).to.equal("world");
    });
  });
});
```

`spec1.js`
```js
Cypress.config("hello", "tom");

describe("page", () => {
  it("Hello is tom", () => {
    cy.wrap(null).should(() => {
      expect(Cypress.config("hello")).to.equal("tom");
    });
  });
});
```

### Desired behavior:

`Cypress.config` should be scoped or the run all button should be disabled

### Steps to reproduce: (app code and test code)

I've setup a tiny repo:
https://github.com/skimi/cypress-test-tiny

Run all tests with `cypress:open` to get a fail and `cypress:run` to get a success.

### Versions

Failed with 3.1.5

**Comment by jennifer-shehane** [comment]
Yes, the scope of this work falls under this larger issue about handling running 'All Specs' https://github.com/cypress-io/cypress/issues/1586
