### ISSUE TITLE
Does not support script type="module"

### ISSUE THREAD

**Issue by shakyShane** [cypress-io/cypress#3696]
### Current behavior:

Nothing, just a blank screen

### Desired behavior:

`<script type="module" src="script.js></script>` should work as expected

### Steps to reproduce: (app code and test code)

Just have any site attempting to use `<script type="module" src="script.js></script>` as mentioned here https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

### Versions

Mac OS Mojave

**Comment by jennifer-shehane** [comment]
Can you verify which browser you are opening Cypress in? Is it Electron? Chrome? Are you doing it via `cypress open` or `cypress run`?

I notice that support for `<script type="module"` was introduce in Chrome 60+, our Electron version is using Chromium 59.

**Comment by shakyShane** [comment]
hi @jennifer-shehane - the issue was I was using chrome when building/testing (cypress open) - but then it was switching to electron in CI.

differring default versions I think is a foot 🔫 

eg: if it's always electron when headless - there should be a giant warning about using chrome to avoid this :)

**Comment by jennifer-shehane** [comment]
You can run during `cypress run` with another browser by using the [`--browser` flag](https://on.cypress.io/command-line#cypress-run-browser-lt-browser-name-or-path-gt). However, video recording is unavailable currently when using chrome during `cypress run`.

**Comment by shakyShane** [comment]
Oh really! No way - tbh i can live without video, thank you so much

**Comment by jennifer-shehane** [comment]
This will be fixed by https://github.com/cypress-io/cypress/pull/4001 which upgrades Electron and uses Chrome 61 in our upcoming release. We'll update this issue when it is released.
