### ISSUE TITLE
cy.visit() on SPA redirected 

### ISSUE THREAD

**Issue by zts3y** [cypress-io/cypress#3697]
### Current behavior:

Using simply a `cy.visit()` to browse to a URL that happens to be a single page application, the page will render in the runner before quickly being redirected to a base url of `__` and the runner losing connection and reporting "Whoops, there is no test to run." In normal Chrome browser, a redirect is not observed.

### Desired behavior:

URL should not change, or if a redirect is common for this tool to function, it should be followed and tests continue to run.

### Steps to reproduce: (app code and test code)

```js
cy.visit('https://www.medicare.gov/physiciancompare');
```

Terminal will report: 
```
GET /physiciancompare/ 302 2.960 ms - 52
GET /__/ 200 4.412 ms - -
```

### Versions

Cypress: 3.1.5
Windows 10

**Comment by jennifer-shehane** [comment]
I am able to recreate this. I notice that a location popup comes up directly before it go to the 'Whoops' page - I don't think that is related, but there is an issue open to disable the dialog here: https://github.com/cypress-io/cypress/issues/2671

<img width="474" alt="Screen Shot 2019-03-14 at 12 31 44 PM" src="https://user-images.githubusercontent.com/1271364/54334714-36f98f00-4655-11e9-8e91-8dc9ae1938a6.png">

<img width="1404" alt="Screen Shot 2019-03-14 at 12 31 48 PM" src="https://user-images.githubusercontent.com/1271364/54334720-3b25ac80-4655-11e9-8201-5a674ed36780.png">

I notice you logged a 302 redirect. Can you share the code of how you are performing the actual redirect? It's possible that you're redirecting from `window.top` instead of `window` which would cause this behavior.

**Comment by jennifer-shehane** [comment]
Related:
- https://github.com/cypress-io/cypress/issues/3642
- https://github.com/cypress-io/cypress/issues/3077

**Comment by zts3y** [comment]
Thanks @jennifer-shehane. I don't think the geolocation request is related as I've seen the same behavior on other applications without that feature. I'm working to get more information regarding the redirect now.

**Comment by zts3y** [comment]
Hi @jennifer-shehane  -- We've tried Cypress with applications on localhost that definitely wouldn't have a redirect in place, and the same thing is occurring.

**Comment by suellenz** [comment]
Hey @jennifer-shehane  I have the same problem, if you want to see it to get more information I can show you.

**Comment by zts3y** [comment]
@jennifer-shehane, I heard back from folks that would know the answer to the redirect question. There is nothing on the hosting end that would cause this, and no rules existed that would present this behavior without it also being visible when examining it manually in a browser.

I tested my application locally, and Cypress works as expected there though.

**Comment by suellenz** [comment]
@jennifer-shehane so don't have a solution for this problem? I really want to make some tests with cypress.

**Comment by jennifer-shehane** [comment]
@suellenz You are welcome to forward any information directly to support@cypress.io in reference to this bug

**Comment by suellenz** [comment]
@jennifer-shehane Thank you so much, I'm going to try again and make more some tests and if I still have with same problem I'll forward the bug to the support just like you suggested  me.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by electronrecord** [comment]
Hi there, I have the same issue of "Whoops, there is no test to run." 
I have installed cypress per project, did not touch cypress.json, and started with npx cypress open.

When I run actions.spec.js with a modified visit URL - https://www.portail-autoentrepreneur.fr I get the error message. It does work with other websites though. This website is made with VUE SSR.

Anyone encountered this issue of no tests to run?

thanks

**Comment by jennifer-shehane** [comment]
@electronrecord Typically we've seen this issue when clicking on links that have `target=_parent` https://github.com/cypress-io/cypress/issues/3121 but there are some [other issues](https://github.com/cypress-io/cypress/labels/topic%3A%20%20%F0%9F%98%B3whoops%20there%20is%20no%20test%20to%20run) open as well.
