### ISSUE TITLE
Improve headless script bundling

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#370]
Currently, during headless runs, tests and support files are bundled every time they are requested, meaning every time there is a visit in a test. This is unnecessary since the files don't change, so they only need to be bundled once. Need to ensure that files are bundled only once per headless run.

**Comment by brian-mann** [comment]
Fixed in [`0.18.5`](https://github.com/cypress-io/cypress/wiki/changelog#0185-01082017).
