### ISSUE TITLE
Test case hangs on on CIs

### ISSUE THREAD

**Issue by carrieyummy** [cypress-io/cypress#3701]
### Current behavior:
I must use `cypress run --browser chrome` and chrome to run cases, but test case will hang up every time in TeamCity or Jenkins.

I've tried it in cypress examples and my own test cases.
they stop as the pictures below shows:

cypress examples:

![image](https://user-images.githubusercontent.com/39080899/54272554-e6cfed80-45be-11e9-9d15-8dc7c1ed2531.png)

my test cases, and it's the second case to run. 

![image](https://user-images.githubusercontent.com/39080899/54272870-7e354080-45bf-11e9-87a1-f41980ff546e.png)

### Steps to reproduce: (app code and test code)

my test case stopped here:
```js
describe('产品页面用例', () => {
    before(() => { // 在用例执行前,先清理环境,删除影响新建的那些名字和测试数据相似的产品
        cy.userLogin('预置租户1租户管理员')
        Object.values(productData.查询自动化用例新建的产品).forEach((sql) => {
            cy.execPython3(sql).then((resultList) => {
                if (resultList.length != 0) { // 判断查询结果是否为空
                    resultList.forEach((result) => {
                        console.log('result', result)
                        cy.commonDelete(productEle.产品接口路径, result[0]) // 删除自动化用例新建的产品
                    })
                }
            })
        })
    })
    beforeEach(() => {
        cy.userLogin('预置租户1租户管理员')
        cy.visit(commonEle.产品管理页面)
    })
    it('租户管理员新建产品-Tenant Admin Create New Product-Highest', () => {
        // 新建产品租户内唯一,新建之后保留,直至下一次测试开始前在预置条件中删除产品
        cy.visit(productEle.新建产品页面路径)
        cy.get(productEle.输入产品名称).type(productData.产品数据集.用例创建的产品.name)
        cy.get(productEle.输入产品描述).type(productData.产品数据集.用例创建的产品.description)
        cy.get(productEle.确认新建产品).click().url().should('include', commonEle.产品管理页面)
        cy.get(productEle.产品列表中第一个产品的名称).contains(productData.产品数据集.用例创建的产品.name)
    })
    it('取消新建产品-Cancel before new a product-Low', () => {
        cy.contains(productEle.新建产品).click().url().should('include', productEle.新建产品页面路径)
        cy.get(productEle.输入产品名称).click()
        cy.contains(productEle.取消新建产品按钮).click().url().should('include', commonEle.产品管理页面)
    })
    it('租户管理员连续新建产品-Tenant Admin New Product Continuously-Low', () => {
        productData.产品数据集.用例创建的系列产品.names.forEach((name => {
            cy.visit(productEle.新建产品页面路径)
            cy.get(productEle.输入产品名称).type(name)
            cy.get(productEle.输入产品描述).type(productData.产品数据集.用例创建的系列产品.description)
            cy.get(productEle.确认新建产品).click().url().should('include', commonEle.产品管理页面)
            cy.get(productEle.产品列表中第一个产品的名称).contains(name)
        }))
    })

})
```

index.js:

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--start-fullscreen')
      args.push('--lang=zh_CN')
      // whatever you return here becomes the new args
      return args
    }
  })
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}
```

Jenkinsfile:

```
pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        echo "Begin to build test environment,Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        powershell 'npm ci'
        powershell 'npx cypress verify'
      }
    }

    stage("Test"){
      steps{
        echo "====Test Begin===="
        powershell 'npx cypress run --browser chrome'
      }
      post{
        always{
          powershell 'npx mochawesome-merge --reportDir mochawesome-report > mochawesome.json'
          powershell 'npx mochawesome-report-generator mochawesome.json'
          echo "====Test Case Finished===="
        }
        success{
          echo "====++++Test executed succesfully++++===="
        }
        failure{
          echo "====++++Test execution failed++++===="
        }
      }
    }
  }

  post {
    always {
      echo '====End===='
    }
  }
}
```

### Versions
windows 10,
chrome  72.0.3626.121 64bit
CI: 
Jenkins 2.150.3 ;
TeamCity 
  Version: 2018.2.3
  Build: 61544
  Released: March 6, 2019

dev env:
cypress 3.1.5,

package.json:
```json
    "cypress-failed-log": "^2.4.0",
    "eslint-plugin-chai-friendly": "^0.4.1",
    "eslint-plugin-cypress": "^2.1.2",
    "mocha": "^5.2.0",
    "mocha-junit-reporter": "^1.18.0",
    "mocha-multi-reporters": "^1.1.7",
    "mochawesome": "^3.1.1",
    "mochawesome-merge": "^1.0.7",
    "mochawesome-report-generator": "^3.1.5",
   "mysql": "^2.16.0"
```

I must use chrome to run my case. Please sovle the problem if it can be sovled.

**Comment by jennifer-shehane** [comment]
Hey @carrieyummy, can you run the test cases with the [DEBUG logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) and share the logs around where the runner freezes?

**Comment by carrieyummy** [comment]
> DEBUG logs



> Hey @carrieyummy, can you run the test cases with the [DEBUG logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) and share the logs around where the runner freezes?
Hi @jennifer-shehane ,
I've tried this:
![image](https://user-images.githubusercontent.com/39080899/54334761-eccada80-4661-11e9-8c92-130b7fd84467.png)
part of Jenkinsfile:
`steps{
        echo "====Test Begin===="
        powershell 'set DEBUG=cypress:*'
        powershell 'npx cypress run --browser chrome'
      }`
but there are no debug logs in command line......
![image](https://user-images.githubusercontent.com/39080899/54334920-7084c700-4662-11e9-95be-5a97f8cfa66e.png)
![image](https://user-images.githubusercontent.com/39080899/54334966-8a260e80-4662-11e9-8eea-c7d984b0d384.png)

**Comment by jennifer-shehane** [comment]
@carrieyummy Are your tests running on Windows within Jenkins?

**Comment by H-a-w-k** [comment]
Not quite sure where to put this, so I'm adding here on this freeze issue.

Had some problems with cypress freezing going from one test to another.
The problem seemed to be when a a new test started while a gql query was underway.
Anyway, waiting for queries to resolve, by looking for a loader symbol to disappear in our case, solved it.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
