### ISSUE TITLE
Runner unexpectedly change viewport when running on Windows server

### ISSUE THREAD

**Issue by viraxslot** [cypress-io/cypress#3703]
### Current behavior:

Hi, I've run my tests on server with Win10 and use default viewport.

The problem is the runner unexpectedly change viewport, our app change orientation to the mobile version and my tests fail, because of different components and locators between web/mobile versions.

I don't understand why, because locally/on Ubuntu server everything is fine.

I'll use Ubuntu then, but I'm curious what went wrong.

I tried:

1. Add `cy.viewport(1024, 768, 'landscape')` to my `before` hook.
2. Change viewport in cypress config.

### Desired behavior:

Our app should change orientation to mobile on viewport `width=990`.
The viewport is set to a greater value so I expect that this change won't occur.

### Steps to reproduce: (app code and test code)

I doubt I can give you some reproducible example so I've added some logs 

[Cypress_logs.txt](https://github.com/cypress-io/cypress/files/2963307/Cypress_logs.txt).

It's interesting that screenshots are saved in `962x720` resolution.

### Versions
Azure DevOps Server Version 17.143.28621.4
Virtual machine with Windows 10 Pro, 1803
Cypress 3.1.5
Electron 59

Thank you.

**Comment by jennifer-shehane** [comment]
Can you provide the test code where the viewport changes? Does it always happen during a `cy.screenshot()`?

**Comment by viraxslot** [comment]
@jennifer-shehane 
I've changed names, but my code looks like:
```javascript
context('Suite', function () {
  testData.forEach((d) => {
    it('Test ' + d.enter + ' (' + d.lang + ')', function () {
      const params = generator().getParams({
          param1: 'VALUE1',
          param2: 'VALUE2',
          lang: d.lang
        });
      cy.visit(Cypress.env('url') + params);
      cy.get(search.cart.edit, { timeout: Cypress.env('timeout') }).click();
      cy.get(search.form.firstField).type(d.enter + '{enter}');
      cy.get(search.form.findButton).click();
      cy.get(search.cart.firstField).invoke('text').should('eq', d.expect);
      cy.get(search.cart.secondField).invoke('text').should('eq', 'VALUE1');
    });
  });
```
params - just get parameters generated.
There is no cy.screenshot() statement in my code, I meant the default screenshots were made in lower resolution after the test run.

**Comment by jennifer-shehane** [comment]
I would suggest moving any `cy.viewport()` calls into a `beforeEach` hook. The `before` hook will only execute once and the viewport will reset to the default viewport size from `cypress.json` in between each `it()` invocation.

If this is not the problem, we'll need a fully reproducible example in order to investigate further.
