### ISSUE TITLE
uninstalling last used browser causes GUI to hang

### ISSUE THREAD

**Issue by jhanink** [cypress-io/cypress#371]
Background:

* I had been using cypress, started using it with Chrome Canary (to distinguish it in the task switcher)
* I later uninstalled Canary
* then opening the Cypress app and selecting the project displayed an endless spinner
* reinstalling Canary allowed the GUI to load the project

I see there is a dropdown in the GUI for which browser to use, with the last used pre-selected, so maybe the way the selected browser is determined can account for this case.

-----

`CYPRESS_DEBUG=true /Applications/Cypress.app/Contents/MacOS/Cypress`

```
Message: Cannot read property 'name' of undefined
Project.Project.setChosenBrowser in file:///Applications/Cypress.app/Contents/Resources/app/node_modules/@cypress/core-desktop-gui/dist/app.js:64790

info: sending ipc data type=gui:error, id=0.5514602925249226, data=null
```

**Comment by brian-mann** [comment]
Fixed in [`0.18.6`](https://github.com/cypress-io/cypress/wiki/Changelog#0186-01292017).
