### ISSUE TITLE
OAuth2.0 authorization code workflow not working because of multi super domain changes

### ISSUE THREAD

**Issue by saudixit** [cypress-io/cypress#3714]
### Current behavior:
-OAuth2.0 authorization code workflow not working because of multi super domain changes

### Desired behavior:
-Login workflow should work.

### Versions
Cypress  :3.1.5

**Comment by jennifer-shehane** [comment]
Hey @saudixit, was this previously working for you? Can you provide a reproducible example of the bug you are encountering?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
