### ISSUE TITLE
If video failed uploading, do not send video.url

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#3715]
@jennifer-shehane commented on [Thu Jun 14 2018](https://github.com/cypress-io/cypress-api/issues/624)

Within run:

```
  (Uploading Results)

  - Failed Uploading (1/1) /root/app/cypress/videos/common/select-spec.js.mp4
```

Yet, the video `url` is sent with an aws link still.

https://dashboard.cypress.io/#/projects/m7bnkc/runs/4/specs

---

@brian-mann commented on [Thu Jun 14 2018](https://github.com/cypress-io/cypress-api/issues/624#issuecomment-397324414)

The API doesn't actually know whether or not the uploading failed. It just assumes it was all successful.

For us to capture this state we would either need to send it along from the desktop client - or we'd need a lambda function to spawn in response to files being uploaded to buckets - which would then update the DB state.

Although it would be initially easier to do this out of the clients, its unnecessary and much less flexible (it wouldnt work on older versions) and I think we'd rather opt to go the lambda route because we will have to do that **anyway** when we do things like log processing.

**Comment by hari49951** [comment]
Hi @jennifer-shehane, I am running my tests on GitHub actions and tests are running fine but the video is not uploading to dashboard. I see this in the output " (Uploading Results)
Failed Uploading (1/1) C:\actions-runner_work\omv-cypress-neal\omv-cypress-neal\cypress\videos\cucumber-tests\Offices\OfficeList\OfficeList.feature.mp4".
Is this issue resolved? Thanks!

**Comment by mshivasaketh** [comment]
Surfacing the same issue in our setup. After the spec, failed testcases videos are uploading. At the end got this failure. 
- Failed Uploading (11/11) /cypress/videos/encryption/encryption_mssql.spec.js.mp4
As soon as this occurs the whole suite is timed out.

**Comment by Jeffintel** [comment]
I also had the exact same issue with the screenshot in Cypress Dashboard. is the fix coming soon?
```(Uploading Results)

  - Failed Uploading (1/1) /var/jenkins_home/cypress-artifacts/imageName(failed).png

**Comment by pontilicious** [comment]
I also had the same issue with a video upload. if it fails then the whole suite is timed out. thats really bad!
