### ISSUE TITLE
Fix flaky "e2e plugins fails" `3_plugin_spec` e2e test

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3718]
This test is super flaky for some reason, it would be nice to not run in to these anymore.

https://circleci.com/gh/cypress-io/cypress/84185
![image](https://user-images.githubusercontent.com/1151760/54443428-f9f5d100-4716-11e9-8ece-6e205769a1c2.png)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
