### ISSUE TITLE
Log for visit() should be more detailed

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#3721]
### Current behavior:
with 3.2.0 update, visit() allows more customization, but the log in dev console is not descriptive enough to display them. 
![image](https://user-images.githubusercontent.com/36670132/54457446-ab4c3500-471e-11e9-963c-4bfb25ae65e5.png)

### Desired behavior:

If the log can be more like request(). It will be easier to debug if stuff goes wrong

### Versions
cypress 3.2.0

**Comment by jennifer-shehane** [comment]
cc @flotwig
