### ISSUE TITLE
cy.type doesn't fill in KeyboardEvent.code

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3722]
### Current behavior:

The `KeyboardEvent` object generated when using the `type` command doesn't contain the `code` property.

### Desired behavior:

The `KeyboardEvent` object generated when using the `type` command should contain the `code` property.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

### Versions

3.1.5

**Comment by jennifer-shehane** [comment]
cc @Bkucera
