### ISSUE TITLE
Auto stubbing feature of visit and XHR requests in beforeEach

### ISSUE THREAD

**Issue by ramusus** [cypress-io/cypress#3723]
In this video https://www.youtube.com/watch?v=5XQOK0v_YRE Brian recommended to split out tests and assert only one feature in one test (which is generally accepted preferred behavior in testing), however [here in Best Practices](https://docs.cypress.io/guides/references/best-practices.html#Creating-“tiny”-tests-with-a-single-assertion) it's not recommended to write tiny tests with one assertion only. And these are 2 mutually exclusive approaches. 

For example, I can test my login page with one test only - doing all assertions of initial loading, scenarios of validations and one final successful submission with authentication at the end of this test. The same could be applied to almost all form submissions and all pages with the ability to reset its state to initial. 

Benefits of testing application this way - no need to execute `beforeEach` part with `cy.visit(...)` multiple times, but just once. It improves performance and execution time of tests significantly. But the downside of this way is obvious - if the test in the middle fails, the latter assertions and final submission will not be executed at all.

So, what I am trying to achieve? I'm thinking, it would be nice to have all goods from both worlds - the **ability to split tests to one feature each and still have a small execution time**. 

We definitely need the way to load the page with all initial requests at least one time for each test suite. But I think there is no need to do the same requests on subsequent tests of this `describe` section, they could be temporarily recorded and executed really fast. 

At the same time, prepare fixtures of responses and stub them manually for every test suite is unnecessary work. Also, It makes tests very brittle and doesn't test an actual response. 

The example of this idea implementation from the python world is this app https://github.com/kevin1024/vcrpy. It records all external HTTP requests and put them into files (cassettes), and on subsequent runs, it `plays` the cassettes. Once you have these files, you no longer need the network for your requests. To check if everything works correctly with a real network - just delete cassettes. I'm not sure we need using files in cypress, memory should be enough, but auto recording, where it's fully safe, could be very helpful.

Any thoughts?

**Comment by ramusus** [comment]
it seems this idea have already been implemented using files here https://github.com/PinkyJie/cypress-auto-stub-example

**Comment by ramusus** [comment]
Another article related to the topic https://medium.com/ax2-inc/dynamic-xhr-responses-recording-stubbing-with-cypress-9257d4f730cd

**Comment by jennifer-shehane** [comment]
Hey @ramusus, testing is definitely a balancing act of all of these things - having enough tests and coverage, but not too much to slow down your workflow.

Issues in our GitHub repo are reserved for potential bugs or feature requests, I'm a little unclear about whether you are asking Cypress to implement a specific feature to our product to facilitate what you need. Could you explain the feature specifically is so?

You may also want to check out our [community chat](https://gitter.im/cypress-io/cypress) to discuss this.

**Comment by ramusus** [comment]
Hi, @jennifer-shehane 
In short, I need the way to stub `cy.visit` requests to make them fast. Is there a way to do so?

**Comment by jennifer-shehane** [comment]
Perhaps [`cy.request()`](https://on.cypress.io/request) would be helpful?

**Comment by ramusus** [comment]
I believe, it's for making HTTP requests, not for stubbing them

**Comment by sainthkh** [comment]
How about trying [yakbak](https://github.com/flickr/yakbak)?
