### ISSUE TITLE
[BUG] Urgent: Running a test always succeeds, even when later assertion fails

### ISSUE THREAD

**Issue by oriqoqo** [cypress-io/cypress#3724]
### Current behavior:

Test succeeds though assertions should clearly fail

Very similar to #3664 
Also similar to #2720 , #3497 

### Desired behavior:

The test should clearly succeed - or fail - in full prior to reporting itself as successful or failed.

### Steps to reproduce: (app code and test code)

Here's a simple test code in a forked repo. Test appears as successful although it should miserably fail.

https://github.com/oriqoqo/cypress-test-tiny

### Versions
I'm running latests OSX. Tried electron and Chrome 72.

Reproducible on Cypress 3.1.5, 3.2.0

Reproducible when running with --open as well as running with --run flag as well.

Thank you!!

**Comment by lukeapage** [comment]
Why are you defining your describe/it functions as async?

**Comment by oriqoqo** [comment]
Yep, that resolves it. Old leftover pre cy.*. Thank you!!!
