### ISSUE TITLE
Cypress creating nested folders

### ISSUE THREAD

**Issue by anastasia333** [cypress-io/cypress#3726]
I have the same issue as #2388, it happened to me twice. First after npm installation, second after manual. Now I have two cypress folders I cannot delete.
https://github.com/cypress-io/cypress/issues/2388

### Current behavior:

I have used the 'download' link to download the `cypress.zip` file from Cypress.io website. Later when I try to delete the whole Cypress folder, I get 

```
Error 0x80070091 (The directory is not empty)
```

### Desired behavior:
Not to have nested folders after each run
 
### Steps to reproduce: (app code and test code)

1. Start cypress with cypress.exe
2. Create tests in examples folder 
3. Run these tests in chrome

### Versions
windows 10
v1.8.2
Chrome Version 72.0.3626.121

**Comment by jennifer-shehane** [comment]
I would love to track this issue down, this error seems specific to Windows.

- Where did you download Cypress? Was it to an external directory?
- Can you show what you mean by the nested folders? Where are you 'creating' tests in the examples folder? 
- When you 'start cypress', are you running `cypress run` or `cypress open`?

I've read somewhere that you may be able to rename the folder - like to `!Cypress` and then delete the directory.

**Comment by anastasia333** [comment]
* .zip was downloaded from https://www.cypress.io/
* cypress was started by opening .exe, not running cypress run or cypress open
* it seems that every time when user clicks on "select manually" to run tests, cypress creates a new "cypress" folder in that chosen folder, and it's impossible to remove (side note - there is a utility that can remove such nested folders - deep remove). Renaming the folder doesn't work. 

attached file shows the first nested folder created, after "select manually":
![manual](https://user-images.githubusercontent.com/16554032/54524313-573d8c80-497a-11e9-9083-28f2c34ad9d7.JPG)
![nested](https://user-images.githubusercontent.com/16554032/54524314-573d8c80-497a-11e9-9941-877d673c7737.JPG)

**Comment by jennifer-shehane** [comment]
I still haven't been able to replicate this, following the steps provided. Maybe it is only reproducible on Windows 10 OS?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by pallavi195** [comment]
Hello Team, 
I am so Glad i found you all, as i'm in the similar boat and have many issues with installation for windows . Also the folks who put this issue are on the right track and those are the exact steps 1.Go to Cypress.io 2. Do the Direct Download . This always happens(happening!) when i do the Direct Download from Cypress.io . For systems which have Proxy issues , Direct Download is the ONLY way to install Cypress as npm install cypress --save-dev , stops and will not install and  throws errors about Proxy etc. Isn't there a easy way to do this. Please help!

**Comment by pavcy** [comment]
Hello Team,
I am so Glad i found you all, as i'm in the similar boat and have many issues with installation for windows . Also the folks who put this issue are on the right track and those are the exact steps 1.Go to Cypress.io 2. Do the Direct Download . This always happens(happening!) when i do the Direct Download from Cypress.io . For systems which have Proxy issues , Direct Download is the ONLY way to install Cypress as npm install cypress --save-dev , stops and will not install and throws errors about Proxy etc. Isn't there a easy way to do this. Please help!

**Comment by jennifer-shehane** [comment]
@pavcy See our docs on [proxy configuration](https://on.cypress.io/proxy-configuration)

**Comment by pavcy** [comment]
Hello @jennifer-shehane , thanks for your response. Unfortunately the laptop i'm using has tight security issues and will not co-operate with Proxy stuff. I tried to use different ways to set the proxy but alas it doesn't work anytime on this . May be i need to try on a system which can be bend for proxy and Cypress will work on it . Appreciate your response greatly.
