### ISSUE TITLE
How can i run test runner inside docker ?

### ISSUE THREAD

**Issue by nikhiletc** [cypress-io/cypress#3727]
i am running cypress inside docker, I can run the test. when a test failed I can see the screenshots,  but i can't run a test runner, i am getting this error 
<img width="1432" alt="Screenshot 2019-03-17 at 10 38 32" src="https://user-images.githubusercontent.com/4526422/54488349-09088a80-48a1-11e9-928a-b929babdfe07.png">
It's very difficult to debug without testrunner

**Comment by jennifer-shehane** [comment]
Have you taken a look at our docker images? https://github.com/cypress-io/cypress-docker-images

**Comment by nikhiletc** [comment]
Yeah, i have tried, 
and also tried to use https://github.com/cypress-io/browser-connect-experiment  .but it was not feasible to use.
