### ISSUE TITLE
Selecting environment via the deskop appliction

### ISSUE THREAD

**Issue by anushkamds** [cypress-io/cypress#3731]
### Current behavior:
In the UI of Cypress, there is no way of selecting the environment option if we want to run the test case in a different environment. Need to run a special command kind of thing to do it. 

### Desired behavior:
There should be an option to select the environment for user convenience if user don't want to run any command by rather using the desktop appliction just for checking running test cases. Specially if some one ot that famliar with commnad line things. 

### Versions
3.20

**Comment by jennifer-shehane** [comment]
What environment options do you want exactly?

**Comment by delockdown** [comment]
We can have different `baseUrl` and other stuff for a particular environment to test in a different environment like local, QA, staging and production.  So it is possible to define different configuration files for each environment. If there is a way to select those configurations or any other way to add configuration files to a different environment via UI. 
It would life easy for some people when they are using Cypress.

**Comment by jennifer-shehane** [comment]
Closing this feature request since it hasn’t gotten a lot of interest over the years.
