### ISSUE TITLE
Cypress's CI missing dependency

### ISSUE THREAD

**Issue by zedissime** [cypress-io/cypress#3734]
Hello, 
Since a couple of days, I'm having some trouble with my CI and the [required dependencies](https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies) from the doc. 

When I execute `sudo apt-get install --ignore-missing xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2`

The installation fails, because there is a missing dependency :
`Unable to correct missing packages.
E: Failed to fetch http://deb.debian.org/debian/pool/main/w/wayland/libwayland-cursor0_1.12.0-1_amd64.deb  404  Not Found
E: Aborting install.
Exited with code 100`

How can I fix that ?

**Comment by flotwig** [comment]
It looks like Debian has updated `libwayland-cursor` to a slightly different filename with a patch update.

http://deb.debian.org/debian/pool/main/w/wayland/libwayland-cursor0_1.12.0-1_amd64.deb gives a 404 not found, 

but http://deb.debian.org/debian/pool/main/w/wayland/libwayland-cursor0_1.12.0-1+deb9u1_amd64.deb does exist. 

It looks like for some reason `apt-get` is pulling in outdated dependencies.

Have you done an `apt-get update` recently? Your index might be out of date. Alternatively, if you're running on Docker, maybe you could retry re-building the `apt-get update` stage of your image with [`docker build --nocache`](https://stackoverflow.com/a/37727984/3474615).

**Comment by bahmutov** [comment]
yeah, we advise to first run `apt-get update -y` before running `apt-get install`

**Comment by zedissime** [comment]
@flotwig @bahmutov  Yes sorry for that, I just did it and the install seems fine. Thanks for your answers !

**Comment by bahmutov** [comment]
no worries, @zedissime glad it got resolved
