### ISSUE TITLE
Run parallel cypress tests in jenkins , not in circle CI

### ISSUE THREAD

**Issue by raktim1988** [cypress-io/cypress#3736]

**Comment by raktim1988** [comment]
Closed but no comments for me ?? That's pretty weird . You can pls help me with necessary comments or helps

**Comment by bahmutov** [comment]
@raktim1988 Ben has closed the issue because you have not provided any details or asked any questions. Please read parallelization documentation and Jenkins example in

- https://on.cypress.io/continuous-integration
- https://on.cypress.io/parallelization
