### ISSUE TITLE
Documentation not clear: "How Cypress handles unit tests vs integration tests."

### ISSUE THREAD

**Issue by basickarl** [cypress-io/cypress#3737]
Not a massive ticket, but I feel the documentation isn't clear enough about one area for beginners: https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Folder-Structure

It states: 

> How Cypress handles unit tests vs integration tests.

There is unfortunately nothing that explains this in the current documentation. At least not clear enough!

(I also find it strange that there is a cypress/integration directory, but no cypress/unit directory. If the case was that the unit tests are to be located elsewhere, then shouldn't the default behaviour be that cypress looks through the application code also? Or perhaps cypress doesn't want to have anything to do with the file structure of unit tests and wants me, the developer to decide? And edit cypress.json after my own needs (which I am currently doing))

**Comment by flotwig** [comment]
Issue moved to [cypress-io/cypress-documentation #1502](https://github.com/cypress-io/cypress-documentation/issues/1502) via [**ZenHub**](https://www.zenhub.com/)
