### ISSUE TITLE
Surprise: cy.get(selector).contains(text) is not the same as cy.contains(selector, text)

### ISSUE THREAD

**Issue by mitar** [cypress-io/cypress#3745]
### Current behavior:

I am trying to wait for a `button` with some text to appear in the app. But the app has many buttons available all the time. So if I do `cy.get('button').contains('FooBar')` this fails because `cy.get('button')` finds some buttons, but they do not contain text `FooBar`. Even if button is later on added, this still fails because `cy.get` seems to not be retried and the same initial set of buttons is provided to `contains`.

### Desired behavior:

The whole chain should be retried until it succeeds.

### Versions

Linux, Cypress 3.1.1.

**Comment by jennifer-shehane** [comment]
You may try as alternatives:

```js
cy.get('button:contains("FooBar")')
cy.contains('button', 'FooBar')
cy.get('button').should('contain', 'FooBar')
```

Please check out our [retry-ability](https://on.cypress.io/retry-ability) doc on specific about how this works today in Cypress.

**Comment by mitar** [comment]
Yes, I understand other approaches to achieve this, but I think this behavior should at least be documented somewhere. I see that it is well documented [here](https://docs.cypress.io/guides/core-concepts/retry-ability.html#Only-the-last-command-is-retried), but that is not linked from `cy.get`?

**Comment by jennifer-shehane** [comment]
I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document retry doc from other areas here: https://github.com/cypress-io/cypress-documentation/issues/1506. Our documentation is open source and contributions are welcome. 😄

**Comment by kklamberty** [comment]
My colleague and I found one of your suggestions helpful, but we can't find more documentation about the syntax. Can you say more about where this example is documented? 

`cy.get('button:contains("FooBar")')`

The notation with the colon does not seem to utilize basic css selectors, but we found it helpful for finding a collection of buttons that all contained the same text. We also were not sure how this particular example related to retry-ability and if that was closely related to the syntax, we could not see how. The notation seems like it would be really useful. Thanks!

**Comment by jennifer-shehane** [comment]
@kklamberty Cypress uses the sizzle engine under the hood, same as jQuery https://github.com/jquery/sizzle/wiki

**Comment by AhmedMAnwar** [comment]
I'm using Cypress version 10.0.0 and I see the same issue. Also, where can I find an exact illustration for this issue in [retry--ability Page](https://docs.cypress.io/guides/core-concepts/retry-ability)

**Comment by jennifer-shehane** [comment]
@AhmedMAnwar https://on.cypress.io/retry-ability

**Comment by AhmedMAnwar** [comment]
@jennifer-shehane I know this page actually, but What I meant is which statement or which section on this page says that .contains should be used as you stated above in the first comment such as follow 
```
cy.get('button:contains("FooBar")')
cy.contains('button', 'FooBar')
cy.get('button').should('contain', 'FooBar')
```

**Comment by jennifer-shehane** [comment]
@AhmedMAnwar You know, I think this behavior has changed since 11.0 so that this example should work as expected now.
