### ISSUE TITLE
.should('contain', regex) fails when chained off an array of elements

### ISSUE THREAD

**Issue by bohendo** [cypress-io/cypress#3746]
### Current behavior:

```js
cy.get('button').should('contain', /next/i)
```

The above line of my e2e test fails with the following output:

```
Command:  assert
Subject:  jQuery.fn.init(3) [button.jss181.jss175.jss176, button.jss181.jss236, button.jss181.jss207.jss215.jss216.jss230.jss294, prevObject: jQuery.fn.init(1), context: document, selector: "button"]
Message:  expected [ <button.jss181.jss175.jss176>, 2 more... ] to contain /next/i
Error:    AssertionError: expected '[ <button.jss181.jss175.jss176>, 2 more... ]' to contain /next/i
```

The docs suggest that `contains` is supposed to be passed a string but it seems like it accepts a regex too because the following passes:

```js
cy.get('button').contains(/next/i).should('contain', /next/i)
```

The key difference seems to be that, in this case, the should is chained off a single element rather than an array of elements like in the first example.

But this workaround doesn't help my case because the `get` will succeed & stop retrying before the element I'm looking for pops up. See https://github.com/cypress-io/cypress/issues/904#issuecomment-343690996

### Desired behavior:

`cy.get(element).should('contain', regex)` should compare the regex against each element's inner text.

Alternatively, I'd like to have some way to assert that some element in an array has an inner text that matches some regex. See issue #3747 for another unsuccessful attempt I made at solving this problem.

### Steps to reproduce: (app code and test code)

```js
describe('Debug', () => {
  it('Should display an intro modal that can be closed', () => {
    cy.visit('https://daicard.io')
    cy.get('button').contains(/next/i).should('contain', /next/i) // This passes!?
    cy.get('button').should('contain', /next/i) // This fails
  })
})
```

### Versions

Cypress: 3.2.0
MacOS: 10.14.3 (18D109)
Google Chrome: 72.0.3626.121 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
`.contains()` accepts a string, number, or RegExp as noted here: https://on.cypress.io/contains#Arguments

The `contain` assertion comes directly from chai-jquery which seems to indicate that it does not accept RegExp, but only a string: https://github.com/chaijs/chai-jquery#containtext
