### ISSUE TITLE
cy.get(el).should('match', regex) fails to compare regex against el's innnerText

### ISSUE THREAD

**Issue by bohendo** [cypress-io/cypress#3747]
### Current behavior:

I'm not using the middle `contains` in my tests & I'll use a more interesting regex to check something else. But, for a simple failing case, see:

```js
cy.get('button').contains(/next/i).should('match', /next/i)
```

The above line of my e2e tests fails with the following output:

```
Command:     contains
Content:     /next/i
Applied To:  (3) [button.jss181.jss175.jss176, button.jss181.jss236, button.jss181.jss207.jss215.jss216.jss230.jss294]
Yielded:     <span class=​"jss208">​Next​</span>​
Elements:    1
Error:       CypressError: Timed out retrying: expected '<span.jss208>' to match /next/i
```

It looks like the `contains` yielded `<span class=​"MuiButton-label-214">​Next​</span>​` But then the match assertion is only checking `<span class=​"MuiButton-label-214">​` and not the inner text.

I don't see anything in the [assertion reference](https://docs.cypress.io/guides/references/assertions.html) that suggests `match` should only be comparing against the element name & classes.

### Desired behavior:

`cy.get(element).should('match', regex)` should compare the regex against the element's inner text too, not just the element name & classes.

Alternatively, I'd like to have some way to assert that some element in an array has an inner text that matches some regex. See issue #3746 for another unsuccessful attempt I made at solving this problem.

### Steps to reproduce: (app code and test code)

```js
describe('Debug', () => {
  it('Should display an intro modal that can be closed', () => {
    cy.visit('https://daicard.io')
    cy.get('button').should('match', /next/i) // This fails
    cy.get('button').contains(/next/i).should('match', /next/i) // This fails too
  })
})
```

### Versions

Cypress: 3.2.0
MacOS: 10.14.3 (18D109)
Google Chrome: 72.0.3626.121 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Each command in our API documents what is yielded from the command. [`.contains()`](https://on.cypress.io/contains#Yields) yields the entire DOM element, not just its innerText, so `match` will not work here since it's looking for a string to compare.

There are many ways to access and assert on the innerText of an element as documented here:
https://on.cypress.io/using-cypress-faq#How-do-I-get-an-element%E2%80%99s-text-contents

**Comment by bohendo** [comment]
Ok, so my goal is to have some way to assert whether one of the elements in an array of elements has an inner text that matches some regex.

Solutions proposed here or in issue #3746 don't work. From the documentation you linked:

`cy.get('div').invoke('text').then((text1) => { expect(text1).to.match(regex) })` <- this will concatenate all the inner texts from all divs into `text1` and then compare against that which is not what I want.

`cy.get('div').should(($div) => { const text = $div.text(); expect(text).to.match(/foo/)` <- this concatenates inner text from all divs the same way.

Is there other documentation I'm missing? Is what I'm trying to do not possible?

**Comment by bohendo** [comment]
Ok, figured it out: `cy.contains('div', /regex/).should('exist')` will do what I want.

`cy.get('div').contains('text')` will fail sometimes if there are divs present that let the first `cy.get('div')` succeed but the one containing `text` pops up later. The `.contains('text')` will repeatedly check the first collection of divs until timeout instead of running `cy.get('div')` again to get a new collection of divs to check.

But `cy.contains('div', 'text')` will retry both the div selection and the check that one contains `text` until either the correct div pops up or timeout.

Sounds like `cy.get('div').contains('text')` is actually never needed since it can always be replaced by the more robust version: `cy.contains('div', 'text')`

**Comment by BBlackwo** [comment]
Would be nice to have a matcher like this:

```js
cy.get(el).should('match.text', regex);
```

You have a bunch of other matchers for text (`contain.text`, `have.text`, `include.text`), but not one for regex 😞

**Comment by IMightGitIt** [comment]
+1 to BBlackwo.

I currently end up with a ".then" to get the text and then run the RegEx assertion in an "expect" like:

```
cy.get(theThing).then(element => {
      const text = element.text()
      expect(text).to.match(myRegEx)
    })
```

With his suggestion, this would become so much cleaner like:
``
cy.get(theThing).should('match.text',myRegEx)
``

I end up using RegEx quite a lot for me testing as we have some very dynamic labels. For example, a trend indicator for chart could either be "-1.2%" or "+123,234.5%". So having to do this text conversion each time becomes quite a hassle in the long run.

**Comment by dialex** [comment]
@jennifer-shehane can you accept this as a feature request? ☝️

```js
// "match.text" assertion
cy.get(mySelector).should("match.text", myRegex)
```

**Comment by jennifer-shehane** [comment]
You can use [`invoke('text')`](https://on.cypress.io/invoke) to already do this with a `.then`.

```js
it('match text of DOM el', function () {
  cy.get('p').invoke('text').should('match', /Some text/)
})
```

There are some examples in our FAQ on how to get element's text here https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-get-an-element%E2%80%99s-text-contents

**Comment by rafawalter** [comment]
Now we can use a RegExp in contains():
`cy.get(mySelector).contains(/regex-pattern/)`
For example:
`cy.get('span.number').contains(/\d+/)`

**Comment by IMightGitIt** [comment]
> Now we can use a RegExp in contains():
> `cy.get(mySelector).contains(/regex-pattern/)`
> For example:
> `cy.get('span.number').contains(/\d+/)`
Good to know.
But does that work as an assertion? On the top of my head, I don't think .contains actually fails, if nothing is found. So you would need to add something like .should('exists') at the end, which would make it pretty much the same length as the .invoke example from Jennifer.

**Comment by rafawalter** [comment]
Good news, @IMightGitIt, .contains() does work as an assertion, as answered above
https://github.com/cypress-io/cypress/issues/3747#issuecomment-474292167

You can use both syntaxes:
`cy.get('span.number').contains(/\d+/)`
or
`cy.contains('span.number', /\d+/)`

See for yourself running this example:
https://github.com/rafawalter/cypress-contains

**Comment by IMightGitIt** [comment]
> Good news, @IMightGitIt, .contains() does work as an assertion, as answered above
> [#3747 (comment)](https://github.com/cypress-io/cypress/issues/3747#issuecomment-474292167)
> 
> You can use both syntaxes:
> `cy.get('span.number').contains(/\d+/)`
> or
> `cy.contains('span.number', /\d+/)`
> 
> See for yourself running this example:
> https://github.com/rafawalter/cypress-contains

Uuh, interesting! I might update a few tests today with this format then. Thank you for the tip!

**Comment by pstephenwille** [comment]
Testing map layer .png's which are dynamically generated, so I'd like to see something like this...
```
should('have.attr', 'src', regExp)

**Comment by stoplion** [comment]
Why is it necessary to regex? Once you dropdown to the element and grab it's text, why can't just a string comparison be used?

**Comment by ChaddFrasier** [comment]
@pstephenwille When I was checking image hrefs I used and nested setup like this that worked perfectly.
```
cy.get('image.holder').invoke("attr", "href").should("not.match", /^(data\:image\/jpeg;base64,)/i)
    .then(() => { // some more things to check after the above runs })
});
```

**Comment by sanelen** [comment]
> Good news, @IMightGitIt, .contains() does work as an assertion, as answered above
> [#3747 (comment)](https://github.com/cypress-io/cypress/issues/3747#issuecomment-474292167)
> 
> You can use both syntaxes:
> `cy.get('span.number').contains(/\d+/)`
> or
> `cy.contains('span.number', /\d+/)`
> 
> See for yourself running this example:
> https://github.com/rafawalter/cypress-contains

Hi @IMightGitIt  

I have this regex " ^Monday:\s[0][9|8]:[\d]+:[\d]+\-[\d]+:[\d]+:[0]+"

which validated these

Monday: 09:00:00-17:00:00
Monday: 08:00:00-17:00:00

I tested this here:
https://www.regextester.com/

I cant seem to validate this in cypress
 .contains(new RegExp("^Monday:\s[0][9|8]:[\d]+:[\d]+\-[\d]+:[\d]+:[0]+"))
