### ISSUE TITLE
Cypress unable to test sites with scripts obfuscated with domain lock

### ISSUE THREAD

**Issue by shishkin17** [cypress-io/cypress#3748]
### Current behavior:

![Untitled](https://user-images.githubusercontent.com/48315811/54118645-f4457600-440c-11e9-9cf0-b552b3d82f22.png)

I noticed that I can’t run tests with cypress on a site that has scripts obfuscated with domain lock by JavaScript Obfuscator Tool (https://obfuscator.io/). Domain lock is a setting that helps protect scripts from running on other domains. I don’t know how cypress works, so I can’t even think of how can I solve that problem. I saw that it starts with localhost and then it redirects to the real domain, but the scripts fail to work after that. I tried adding localhost as approved domain, but it didn’t help. 
I like your tool, but removing a domain lock just for testing doesn't seem a good idea.

### Desired behavior:

When I run tests on a site that has scripts obfuscated with domain lock, javascript doesn't fail with error.

### Steps to reproduce: (app code and test code)

cy.visit('https://matrix.reshish.com/cramer.php');

### Versions

Cypress 3.1.5, Mac OS, Chrome

**Comment by jennifer-shehane** [comment]
I'm getting a different error when I run the `visit` code above in Cypress 3.2.0, Chrome 72. 

<img width="537" alt="Screen Shot 2019-03-19 at 6 55 52 PM" src="https://user-images.githubusercontent.com/1271364/54605926-c8fc0000-4a78-11e9-9c5c-2ee72536a608.png">

Do you have any extra configuration in your project? I'd like to reproduce this if we can.

**Comment by shishkin17** [comment]
This is the correct error (data is not defined).
I might say that this error is not from Cypress (as it is written here),
but if you go to the same link in the browser there will be no such error.

**Comment by pkucherenk0** [comment]
Having the same issue with my obfuscated project.
Have edited my test with:
```
cy.on('uncaught:exception', (err, runnable) => {
      return false
  })
```
and found that data cypress is aguing about.
