### ISSUE TITLE
how close 'ok' window alert

### ISSUE THREAD

**Issue by cristopher-rodrigues** [cypress-io/cypress#376]
![image](https://cloud.githubusercontent.com/assets/3486950/21821089/5dacae9c-d759-11e6-9c8e-cc488921bb9a.png)

**Comment by cristopher-rodrigues** [comment]
https://github.com/cypress-io/cypress/issues/33 it's the same?

**Comment by brian-mann** [comment]
We don't expose any API's to do this.

Internally we actually prevent `confirm` and `alert` messages from every appearing (we auto accept them) - so you should not be seeing these.

However it can pop up if this is coming from an `iframe` or anything other than your app's main window/frame.

Can you post some code or explain what is calling into this? You may need to update your applications code not to show a `confirm` or `alert` box when in test mode. For instance you could check `if (window.Cypress) { ... don't show the confirm... }`

**Comment by cristopher-rodrigues** [comment]
My code is Legacy 🤕. But thats:

```js
if (window.top.Cypress) { 
  //... don't show the confirm... 
}
```

Work for me!

*Very tnks* @brian-mann!

wee need close that?

**Comment by brian-mann** [comment]
Nah leave it open, we need to better explain how to get around this.

**Comment by brian-mann** [comment]
Likely fixed by: https://github.com/cypress-io/cypress/issues/621

However if `alert` happens in an <iframe> it'll still pop up. We don't handle that situation.

**Comment by jennifer-shehane** [comment]
I wanted to add an example of testing an alert in an iframe, since the last comment indicates this is not possible. Really, the comment only means that we do not *automatically* handle alerts. 

Below is an example of testing an alert from an iframe.

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<body>
<iframe id="iframe" width="300" height="200"
  src="iframe.html">
</iframe>
</body>
</html>
```

`iframe.html`

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Stubbing Iframe Window Alert</title>
</head>
<body>
  <ul>
    <li>
      <h1>My Iframe</h1>
      <button id="alert">Alert</button>
    </li>
  </ul>
  <script>
    var btn = document.getElementById('alert')
    btn.addEventListener('click', function (event) {
      window.alert("Hello world!")
    })
  </script>
</body>
</html>
```

```js
it('alerts in iframe', () => {
  cy.visit('index.html')
  cy.get('iframe').then(($iframe) => {
    const $body = $iframe.contents().find('body')
    const $win = $iframe[0].contentWindow

    cy.stub($win, 'alert').as('windowAlert')

    cy.wrap($body)
      .find('#alert').click().should(function () {
        expect(this.windowAlert).to.be.calledWith('Hello world!')
      })
  })
})
```

<img width="786" alt="Screen Shot 2020-01-16 at 11 35 04 AM" src="https://user-images.githubusercontent.com/1271364/72495140-44267200-3854-11ea-8eda-1dca581847c0.png">
