### ISSUE TITLE
Run hangs on mac OS Sierra

### ISSUE THREAD

**Issue by znat** [cypress-io/cypress#3760]
### Current behavior:

Run stops with an error message

![610FEF06-14FD-47D5-846F-1D4EB63B6E1E](https://user-images.githubusercontent.com/3694634/54708275-6c045680-4b19-11e9-8129-c4957b228f96.jpg)

### Steps to reproduce: (app code and test code)

`npx cypress run`

### Versions

Cypress 3.2.0, Mac OSX

**Comment by jennifer-shehane** [comment]
```
objc[56881]: Class FIFinderSyncExtensionHost is implemented in both ...FinderKit (0x7fff920aa210) and ...FinderSyncCollaborationFileProviderOverride (0x112bc0dc8). One of the two will be used. Which one is undefined.
```

From googling around, this actually looks to be a bug with the Mac OS itself. Can you provide the test code that you are running in the `Should allow adding non-existing intents and entities` where this fails?

**Comment by znat** [comment]
Thanks for your quick answer @jennifer-shehane !
Yes, I googled that too, and what I found said that it was merely a warning with no real impact.
I don't think the content of the test is relevant, it happens randomly. See another screenshot
![E3F3B4CE-89AC-4008-9AD5-B47578A91692](https://user-images.githubusercontent.com/3694634/54760219-facead00-4bc5-11e9-96c1-6922e2033280.jpg)

**Comment by jennifer-shehane** [comment]
I recently saw this in one of my runs as well. Closing as it does not seem to cause actual impact on run. Please comment if this is incorrect.
