### ISSUE TITLE
Improve sinon integration

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#377]
Currently, sinon.js integration is hidden behind the undocumented `cy.agents()` API. Deprecate/remove that API and add the following first-class methods:

* `cy.stub()`
* `cy.spy()`
* `cy.clock()`

These methods will be automatically sandboxed and reset between tests.

**Comment by ghengeveld** [comment]
👍

**Comment by brian-mann** [comment]
Fixed in [`0.18.8`](https://github.com/cypress-io/cypress/wiki/Changelog#0188-02052017).
