### ISSUE TITLE
Expose Cypress Binary path via CLI

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#379]
Useful for instance when a user needs to call the absolute path to Cypress.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by bahmutov** [comment]
Should show path to executable when using `$(npm bin)/cypress verify`

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
