### ISSUE TITLE
dblclick() doesn't work as click()

### ISSUE THREAD

**Issue by learningandworking** [cypress-io/cypress#3798]
### Current behavior:

> Error:       CypressError: cy.dblclick() failed because this element is not visible:
> 
> <span class="pax-add pax-enabled" id="hrefIncAdt">+</span>
> 
> This element '<span#hrefIncAdt.pax-add.pax-enabled>' is not visible because its content is being clipped by one of its parent elements, which has a CSS property of overflow: 'hidden', 'scroll' or 'auto'
> 
> Fix this problem, or use {force: true} to disable error checking.

### Desired behavior:

- The double click function gets NO error as click function works.

### Steps to reproduce: (app code and test code)
Having the code to demonstrate the issue as below

```js
context('Drop-down with navigation', () =>{
        it.only('Check drop-down with navigation', ()=>{
            cy.visit('https://www.spicejet.com/')
            cy.get('.adult-infant-child').within(() => {
                cy.get('#divpaxinfo').click()
                    // choose number of adult
                    cy.get('#divAdult #hrefIncAdt').dblclick()
                    // choose number of child
                    cy.get('#divChild #hrefIncChd').click()

            })
        })
    })
```

1. Run the code above => get error

2. Work around:
Replace the line 
`cy.get('#divAdult #hrefIncAdt').dblclick()`
by
`cy.get('#divAdult #hrefIncAdt').click()`

### Versions

```json
  "devDependencies": {
    "cypress": "^3.1.5",
    "cypress-xpath": "^1.3.0",
    "eslint-plugin-cypress": "^2.2.1"
  }
```
node version: v9.3.0
OS: MAC OS

**Comment by jennifer-shehane** [comment]
The `dblclick` command runs a check to `ensureVisibility`: 

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/click.coffee#L233

But the `click` command goes through the `actionability.verify`: 

https://github.com/cypress-io/cypress/blob/jen/reporter-error-templates/packages/driver/src/cy/actionability.coffee#L207

The `dblclick` should go through the same `actionability.verify` - for one thing, when using `dblclick`, it doesn't scroll the element into view before trying to click. As a workaround, can you try to scroll the element you want to dblclick into view before issuing the dblclick using the [`scrollIntoView`](https://on.cypress.io/scrollintoview) command?

**Comment by learningandworking** [comment]
Thanks for your comment @jennifer-shehane 

 Tried to add a command below, but it didn't work
```
cy.get('#divChild #hrefIncChd')
                      .scrollIntoView()
                      .dblclick()
```

**Comment by Konstruktour** [comment]
in one case where dblclick didn't work the following workaround helped... maybe it also helps u 

```javascript
cy.get(....)
    .then((element) => {
        element.click();
        element.click();
});
```
