### ISSUE TITLE
Cypress in Azure

### ISSUE THREAD

**Issue by oqureshi2012** [cypress-io/cypress#3799]
Good Morning,

We would like to stand up cypress in Azure. What installation method would be best? I believe the last time we tried this we went with Chef? 
Do we need Docker installed as well?

Thanks

**Comment by bahmutov** [comment]
We have Azure CI config file in https://github.com/cypress-io/cypress-example-kitchensink

In general - using Cypress Docker image https://github.com/cypress-io/cypress-docker-images helps a lot with OS dependencies.

Also, just follow the general guidelines in https://on.cypress.io/continuous-integration
