### ISSUE TITLE
Error when using length option on checkboxes

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#38]
When getting a collection of checkboxes, if I pass a `length` option, this error is thrown: 

> Error: the domexception "InvalidStateError: Failed to read the 'selectionStart' property from 
> 'HTMLInputElement': The input element's type ('radio') does not support selection."

**Example Code**
```coffee
it "has teams checked", ->
  cy.get(".teams-component").find(":checked", {length: 2})
```

**Command Log**
![screen shot 2015-05-14 at 11 36 56 am](https://cloud.githubusercontent.com/assets/1271364/7635220/b8665f6e-fa2d-11e4-9dfa-1e2988ad1904.png)

**Comment by brian-mann** [comment]
This is fixed in [`0.6.1`](https://github.com/cypress-io/cypress/wiki/Changelog#061-05152015).
