### ISSUE TITLE
Minimize number of Renovate bot pull requests

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3800]
Renovate bot opens a separate PR for each dependency upgrade, which creates a lot of PRs and takes a lot of CI time. We can reduce Renovate frequency using scheduling and package groups, see https://renovatebot.com/docs/noise-reduction/

**Comment by bahmutov** [comment]
I have experimented with groups in https://github.com/bahmutov/renovate-updates-test seems like a nice solution. For example, taking all dev dependencies and applying updates once per month, and maybe grouping dependencies to create pull requests with several upgrades at once

**Comment by jennifer-shehane** [comment]
Released in [3.3.0](https://on.cypress.io/changelog#3-3-0)
