### ISSUE TITLE
Post requests are not including Headers

### ISSUE THREAD

**Issue by RicardoVaranda** [cypress-io/cypress#3802]
### Current behavior:

We are using cy.visit to navigate to our website and it returns a set-cookie which is working correctly.

It sets the headers correctly for the rest of requests in the page load. 

As part of another step of our tests we are filling a form which submits data, when this submits it creates a post request from our angular app which is failing.

After further inspection I found that the Request Cookies are empty for POST only having: __cypress.initial true.

When I inspects all the previous GET requests made by the angular application they all include the correct Headers

### Steps to reproduce: (app code and test code)

Visit a a website which return a set cookie, complete a form which creates a post and inspect the Request cookies sent.

I'll try to post images of this in the morning.

### Versions
Cypress: 3.2.0
Windows 10
Electron 59

**Comment by jennifer-shehane** [comment]
Hey @RicardoVaranda, did you find a solution to your issue?

**Comment by RicardoVaranda** [comment]
Hi @jennifer-shehane Yes so it seems that if I try to click a button to save in a different it context it will not attach the headers from previous it contexts. I had to add the save as the last step which solved it.

**Comment by RicardoVaranda** [comment]
Example for clarification:

```
it('should visit page and fill out form', () => {
cy.visit(); // sets cookies
cy.get('whatever').type('username');
cy.get('whatever2').type('password');
})

// THIS WILL FAIL, headers will be empty
it('should login successfully' () => {
cy.get('button[type="submit"]').click();
}
```

In order to make it pass I had to do the following:

```
it('should visit page and fill out form', () => {
cy.visit(); // sets cookies
cy.get('whatever').type('username');
cy.get('whatever2').type('password');
cy.get('button[type="submit"]').click();

/// further check to see if login was succesfull
})

```
