### ISSUE TITLE
"Unzipping Cypress" takes four minutes

### ISSUE THREAD

**Issue by kevinburkenotion** [cypress-io/cypress#3803]
I have a t2.xlarge instance in AWS. I am attempting to run `npm install` inside of a Docker container to install Cypress 3.1.5. 

I noticed that 4 minutes elapse between the start of "Unzipping Cypress" and its completion.

```
[00:19:28]  Unzipping Cypress       [started]
[00:23:13]  Unzipping Cypress       [completed]
```

This seems like an awfully long time to spend unzipping a binary... any idea what is going on?

**Comment by bahmutov** [comment]
Yeah on Linux the unzipping is done in software which combined with probably slow file system takes minutes. Can you cache the unzipped binary to avoid doing it more than once?

**Comment by kevinburkenotion** [comment]
It's inside of a `npm install` step in a Docker container, so we either get the cached image or nothing, I think, unless you have better ideas.

**Comment by kevinburkenotion** [comment]
Any reason why you are not using `gunzip` or `tar` or similar to unpack the binary?

**Comment by bahmutov** [comment]
Because those tools might not be installed

**Comment by kevinburkenotion** [comment]
Understood, but 4 minute long unpacking on an AWS VM that's as powerful as a high end Macbook is not really great either.

**Comment by bahmutov** [comment]
Agree, just like node modules though - it needs to be cached even if it took 30 seconds

**Comment by cvuorinen** [comment]
Even though it does not take 4 min on my machine, after adding cypress to a project it makes switching branches just painful to always wait few minutes for downloading & unzipping cypress. Can't you cache it somewhere like other npm packages? I mean when switching branches where just one dep has changed, run `npm ci` and before cypress it was just few seconds since (almost) everything comes from cache, since adding cypress it's a waiting game that I try to avoid. I mean I just downloaded & unzipped the thing few minutes ago, such a waste (of bandwidth, cpu and most importantly my time).

**Comment by flotwig** [comment]
@cvuorinen If you're downloading the same version of Cypress, it is actually cached so it doesn't need to be downloaded multiple times. Check [`cypress cache`](https://docs.cypress.io/guides/guides/command-line.html#cypress-cache-command) for more info.

**Comment by cvuorinen** [comment]
@flotwig thanks, seems things have improved. That project is not on v3.x yet. I'll look into upgrading it.

**Comment by goodliff** [comment]
@cvuorinen did you manage to get this down at all? 

We are waiting 3+ minutes for the extraction and as we are blowing the instance away after the build and tests we need to be able to install/ extract again once the next instance starts up. I've already been asked to remove cypress as it's the only thing taking this long in the build process. (trying to avoid that)

**Comment by flotwig** [comment]
@goodliff configure your CI to cache the `~/.cache/Cypress` directory, you won't need to unzip it every time. More information: https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup

---

The code for unzipping is here:

https://github.com/cypress-io/cypress/blob/26c8e7f7e1e5f278d9c2ef7e2dd4cbecc0a9e186/cli/lib/tasks/unzip.js#L16-L16

The unzip speed could be greatly improved if code that uses the native `unzip` binary was added, in addition to the macOS-specific `ditto` code.

**Comment by flotwig** [comment]
Opened a PR to use the native `unzip` utility on Linux, which should be faster: #5851

**Comment by goodliff** [comment]
Nice looking forward to seeing whether this changes anything for us. Still looking at the CI caching options, but this will help some.

**Comment by flotwig** [comment]
I've created a separate issue for improving the unzip time on Windows: #5861

**Comment by mightyiam** [comment]
Thank you!

**Comment by goodliff** [comment]
Um.... "[14:09:00]  Unzipping Cypress        200% -56s [title changed]"

Not entirely sure what happened here but I'm being told that cypress unzipped to 200% when building my docker image. This is with 3.8.0 which incorporated the zipping change I believe.

**Comment by mightyiam** [comment]
@goodliff perhaps better to open a new issue.

**Comment by trainoasis** [comment]
> @goodliff configure your CI to cache the `~/.cache/Cypress` directory, you won't need to unzip it every time. More information: https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup
> 
> The code for unzipping is here:
> 
> https://github.com/cypress-io/cypress/blob/26c8e7f7e1e5f278d9c2ef7e2dd4cbecc0a9e186/cli/lib/tasks/unzip.js#L16-L16
> 
> The unzip speed could be greatly improved if code that uses the native `unzip` binary was added, in addition to the macOS-specific `ditto` code.

AFAIK you cant cache anything outside of the repo that's being used. But, you can set the Cypress cache folder in "variables" section like this: 

`CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"` 

and cache this. This works, but saving and extracting this cache also takes ages in our case so It does not speed things up at all.

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
