### ISSUE TITLE
All POST and PUT XMLHttpRequest made into Cypress have recently started throwing 417 Expectation Failed

### ISSUE THREAD

**Issue by Vinod-Gulia** [cypress-io/cypress#3805]
Recently upgraded - 
Cypress Version in use - 3.2.0
Chrome Browser Version - 73

All `POST` and `PUT` `XMLHttpRequest` made into Cypress have recently started throwing `417 Expectation Failed`. However all these work on the web application when I navigate through it manually.

All my code used to work well in past without any issue. 

I read about this error over internet and I'm not sure if this issue exists on the application under test, or on some firewall policy or there is some setting in Cypress which can fix it.

```js
Cypress.Commands.add("Post_Client", () => {
  cy.fixture(Cypress.env("ClientInputFile")).then(clientoBJ => {
    cy.fixture(clientoBJ.imagePath, "binary").then(imageBin => {
      Cypress.Blob.binaryStringToBlob(imageBin, clientoBJ.imageType).then(
        blob => {
          const xhr = new XMLHttpRequest();
          const data = new FormData();
          data.set(clientoBJ.nameatr, clientoBJ.nameVal);
          data.set(clientoBJ.imageatr, blob);
          xhr.open(
            "POST",
            Cypress.env("APIBaseURL") + Cypress.env("ClientPostURL"),
            false
          );
          xhr.setRequestHeader("accept", "application/json");
          xhr.setRequestHeader("access-token", accesstoken);
          xhr.setRequestHeader("client", client);
          xhr.setRequestHeader("expiry", expiry);
          xhr.setRequestHeader("token-type", tokentype);
          xhr.setRequestHeader("uid", uid);
          xhr.onload = function() {
            if (this.status === 201) {
              cy.writeFile(
                Cypress.env("ClientOutputFile"),
                JSON.parse(this.responseText)
              );
              cy.readFile(Cypress.env("IDStore")).then(obj => {
                obj.clientID = JSON.parse(this.responseText).client.id;
                cy.writeFile(Cypress.env("IDStore"), obj);
              });
            }
          };
          xhr.send(data);
        }
      );
    });
  });
});
```
And then it is called in a Test

```js
  it("CLIENT API POST TEST", () => {
    cy.Post_Client();
  });
```

**Comment by jennifer-shehane** [comment]
Hey @Vinod-Gulia, can you verify that the server has defined an `Expect` header?

**Comment by Vinod-Gulia** [comment]
Hi Jennifer,

Expect is set to false in app config file. 

Having said that, if I make a call to this endpoint with same set of data from POSTMAN it works perfectly fine. Why is Cypress then not able to manage this internally?

**Comment by Vinod-Gulia** [comment]
This stands fixed now.There were two problems causing this and both were at the application layer.

Problem# 1 - Somehow we chose 417 as the error code for any unhandled events.
Fix - We are now using 422 error code for unprocessable entities
Problem# 2 - A formData append method has three params -(name, value, filename) where filename is optional. It is made mandatory in the application code recently.
fix - 

```
data.set(
            clientoBJ.imageatr,
            blob,
            clientoBJ.imagePath.substring(
              clientoBJ.imagePath.lastIndexOf("//") + 2
            )
          );
```

**Comment by jennifer-shehane** [comment]
@Vinod-Gulia Thanks for following up!
