### ISSUE TITLE
Define different baseurls for different Parallelization groups

### ISSUE THREAD

**Issue by stefangrotz** [cypress-io/cypress#3806]
My company has artifacts that don't support multisessions (in mock mode) and they can only serve on user at a time.

If you want to tests artifacts that don't support multisessions there is no way to test them in an paralelized way.  Right now my company uses a selenium hub with 6 browsers and 6 test stages plus a self-written orchestrator that makes sure that every test stream only connects to one stage. I would like to switch this system to cypress.

### Current behavior:
You can paralelize the test cases and let them run on many machines:
https://docs.cypress.io/guides/guides/parallelization.html#Overview

All tests on all machines behave in the same way. All machines will conect to the same baseURL.

### Desired behavior:
I want to be able to define different endpoints for the paralelization. Maybe something like this:

> cypress run --record --group 2x-chrome --parallel --baseURL1 stage1.intern --baseURL2 stage2.intern 

All tests in group 1 would only conect to baseURL1 and alls tests in group2 would only conect to baseURL2

This would ensure that every machine only conects to one defined stage and that there are never two tests running on one stage at once. 

### Versions
Cypress 3.2.0

**Comment by midhun8454** [comment]
Is it something like this? the firsttest case need to be on url1 and second test case on url2 ? i am also facing same issue

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
