### ISSUE TITLE
Cannot find element from html head using jQuery

### ISSUE THREAD

**Issue by yangliurea** [cypress-io/cypress#381]
```html
<head>
    <meta name="csrf-token" content="...">
</head>
```

For using `cy.request()` on login, I tried to extract content from html head, the structure is on the top. 

```javascript
const $html = Cypress.$(response.body)
const csrf = $html.find("meta[name='csrf-token']")[0].attr('content')
```

I can see all elements in `$html`, after `find`, there is nothing even just `find("meta")`, but I can find elements by using `find("a")`. So I guess probably because the element is in `head`.

**Comment by jennifer-mann** [comment]
@yangliurea Cypress automatically proxies `jQuery` and exposes it as `Cypress.$`, nothing more. This does not appear to be an issue with Cypress. Closing for now.
