### ISSUE TITLE
Chrome doesnt support mp4

### ISSUE THREAD

**Issue by mikila85** [cypress-io/cypress#3811]
### Current behavior:
Video (currently mp4) doesnt play in chrome

![image](https://user-images.githubusercontent.com/3965957/54910079-4d74d580-4ef4-11e9-8e48-5cbd45f6eba2.png)

### Desired behavior:
Video should play in Chrome

### Versions
Latest

-----------

Please change or give option to record avi video... mp4 codecs has been dropped for chrome and it doesnt play the videos making it a hassle to download the file and open in in the video player software.

tried setting:
`"videoCompression": false,`
it didnt help

**Comment by jennifer-shehane** [comment]
Hey @mikila85, can you explain a bit more about where you are trying to play this video? Is this in a test you have written? Is this a recorded video you are trying to play from https://dashboard.cypress.io? What version of Chrome are you using? Sorry - it's not clear from the issue.

**Comment by mikila85** [comment]
Hi @jennifer-shehane,
I am using the latest Chrome version: 
`Version 73.0.3683.103 (Official Build) (64-bit)`

After running cypress from the cli i get a folder "videos/tests" and inside .mp4 files.
They run perfectly fine on my computer (Windows media player).
When i connect to a remote build and see the files output in chrome i have links to the files. and chrome wouldent play them.
when i click on the link "Save link as..." and download the file, it plays in windows media player perfectly fine.

Only Chrome is unable to play them.

**Comment by jennifer-shehane** [comment]
I'm not able to replicate this behavior. `.mp4` files play fine from within our CircleCI build artifacts. Example: https://12413-49402470-gh.circle-artifacts.com/0/root/cypress-documentation/cypress/videos/api_spec.js.mp4

Please ensure you disable all extensions in Chrome and read through Jenkins documentation on correctly accessing artifacts. 

Unfortunately we have to close this issue as there is not enough information to reproduce. Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by mikila85** [comment]
Hi, If anyone ever encounters this, 

We found that the browser had this error in Chrome-Devtools:
Refused to load media from 'https://private-jenkins/lastSuccessfulBuild/artifact/cypress/videos/ovoc/3.site.spec.ts.mp4' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

quick search in google will get you to: "Configuring Content Security Policy" which explains the problem and [how to solve it](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy)

**Comment by onmomo** [comment]
> Hi, If anyone ever encounters this,
> 
> We found that the browser had this error in Chrome-Devtools:
> 
> > Refused to load media from 'https://private-jenkins/lastSuccessfulBuild/artifact/cypress/videos/ovoc/3.site.spec.ts.mp4' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.
> 
> quick search in google will get you to: "Configuring Content Security Policy" which explains the problem and [how to solve it](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy)

You can either set the required CSP policy via Jenkins script console for testing until the next restart. (`media-src 'self' ;`)
```
System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "sandbox; default-src 'none'; img-src 'self'; style-src 'self'; media-src 'self';")
```
Or permanently via JDK system properties

```
-Dhudson.model.DirectoryBrowserSupport.CSP="sandbox; default-src 'none'; img-src 'self'; style-src 'self'; media-src 'self';"
```
To allow loading media files from the same jenkins domain.
