### ISSUE TITLE
Missing library(ibXtst.so.6) while trying Circle integration

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#3812]
### Current behavior:
Hi,
I am trying to integrate my Cypress project with Circle CI and getting an error like this:

![image](https://user-images.githubusercontent.com/38225108/54911003-83b75280-4efe-11e9-9c44-c8ae12bd229e.png)

here my .circleci/config.yml file
```js
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: node_modules/.bin/cypress run
```
thanks for helping
best,

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
