### ISSUE TITLE
Cypress- I do have one test that is running in localhost and want another one to run in test url.is it possible? Am not able to run both? one at a time only is possibel

### ISSUE THREAD

**Issue by midhun8454** [cypress-io/cypress#3814]
I do have 2 test cases in my spec file.
#1 test case with url http://localhost:8080 and some check to be done on that url.
#2 another case with url http://mytesturl.com and some check 

How cypress behave is it run on first test case and do all check and it ends fine.Now trying to take on second test case and picks it. But again the url reloads and start again with the first test url

**Comment by jennifer-shehane** [comment]
Hey @midhun8454, could you provide the test code you are running? Also, do you have a `baseUrl` set in your configuration?

**Comment by midhun8454** [comment]
yes . i do have base url in cypress.json->"baseUrl": "https://localhost:8080",
**URL WITH LOCALHOST**
describe('Check the Tabs present or not', () => {
  describe('From "Trip Details" page', () => {
before(()=>{
 cy.visit('http://localhost:8080');
});
 it(`Make sure all tabs are present`, () => {
  cy.get('#checkout-container').contains('Buy Now');
});
});
});

URL WITH TEST URL

describe('Check the Links present or not', () => {
  describe('From "Trip Details" page', () => {
before(()=>{
 cy.visit('https://mytesturl.com');
});
 it(`Make sure all links are present`, () => {
  cy.get('#checkout-container2').contains('Price');
});
});
});

**Comment by midhun8454** [comment]
@jennifer-shehane  can you please come with a solution to overcome this?

**Comment by jennifer-shehane** [comment]
Does this behavior still happen if you remove the `baseUrl` in your `cypress.json`?

**Comment by midhun8454** [comment]
@jennifer-shehane yes i tried with removing base url and behavior still continues..
after removing base url ,now my cypress.json look likes this 
{
  "testFiles": "**/*.spec.js",
  "integrationFolder": "__tests__/e2e",
  "viewportHeight": 600,
  "viewportWidth": 320
}
After localhost runs ,next is my testurl which didnot run and started again with first test with url localhost and then when comes to second test again,it actually shows 404 page with url https://mytesturl.com//__#/tests/__all

**Comment by shaunswales** [comment]
@midhun8454 I have locally created a new Cypress solution and added your tests accessing two different URLs and it works as expected. 

Please see below the tests and outputs:
[issues-3814.txt](https://github.com/cypress-io/cypress/files/3009089/issues-3814.txt)
[integration.zip](https://github.com/cypress-io/cypress/files/3009092/integration.zip)

I'm wondering if it is something within your setup that is causing the issue, out of curiosity can you set up a new project in a temporary folder and see if it works...

👍

**Comment by midhun8454** [comment]
@shaunswales :First of all thanks for the reply.. out of curiosity.. in chrome or electron you tried? i think you tried in electron that made the difference.. I will try and will let you know the results.. Can you please tell which browser you used?chrome or electron

**Comment by midhun8454** [comment]
@shaunswales  also you tried in 2 different spec files,rite? my concern was to do both in a single file? Can you do the same in single file and let me know the status .Means we will be having only test1.spec.js which will be having 2 test inside it ..one calling the localhost and other calling the testurl..is it possible? or  we need to treat them separately
?

**Comment by shaunswales** [comment]
@midhun8454 I don't believe you can in the same .spec.js file.

The Cypress tool will only allow a single orgin per spec to my understanding.

**Comment by midhun8454** [comment]
@shaunswales  oh really !!! Thanks for the info.
Have one more doubt regarding the authentication thing.. In my test url- once cypress hits the test url-it navigate to authentication page where it asks email and password.Passed the correct credentials ,but its says authentication fails. It happens in chrome browser( version 73).So from ma code am using cy.visit(https://www.mytesturl.com) ,also i had added "chromeWebSecurity": false in my cypress.json.
Here is my cypress.json 
{
  "testFiles": "**/*.spec.js",
  "integrationFolder": "__tests__/e2e",
  "viewportHeight": 600,
  "viewportWidth": 320,
  "chromeWebSecurity": false
}
Also added some code in index.js from some stackoverflow 
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  "window:before:load", (win) => { win.fetch = null; }

}
But still its failling authentication

**Comment by jennifer-shehane** [comment]
>The Cypress tool will only allow a single origin per spec to my understanding.

Cypress only allows a single origin per **test**, so per a single `it` invocation, not spec file.

**Comment by sarmistha-das** [comment]
Is there any way to close the Cypress test and rerun it from terminal once again. I am doing quit from Cypress application.
