### ISSUE TITLE
Upgrade to 3.2.0 causes error Cannot find type definition file for 'cypress'.ts

### ISSUE THREAD

**Issue by dinarabs** [cypress-io/cypress#3816]
### Current behavior:
The following line getting IntelliSense in VSCode  
```
/// <reference types="Cypress" />
```
started throwing error `Cannot find type definition file for 'cypress'.ts(2688)`

Due to this error cannot run tests.
### Steps to reproduce: (app code and test code)

Upgraded Cypress from 3.1.5 to 3.2.0

### Versions

Cypress 3.2.0

**Comment by dinarabs** [comment]
Had to close all open files of the project and rerun npm install command in VSCode terminal.

**Comment by bahmutov** [comment]
Thanks for finding the solution, Dinara
