### ISSUE TITLE
Block specific URL

### ISSUE THREAD

**Issue by benpolinsky** [cypress-io/cypress#3820]
### Current behavior:

Users can only blacklist entire hosts.

### Desired behavior:

Users should be able to blacklist a specific URI. 

As we can't stub <script> requests, a suggested approach is to blacklist the host the script comes from, and then add your stubbed/mocked functionality to the contentWindow in an onBeforeLoad hook.

However, this doesn't work for the case where you only want to block one script, but allow all other requests from that domain. An idea is to be able to blacklist specific URIs.

**Comment by flotwig** [comment]
This has been added with [cy.intercept()](https://on.cypress.io/intercept). You can now target a specific URL with a network error or other response:

```ts
cy.intercept('https://my-website.com/specific-path.html', { forceNetworkError: true })
```
