### ISSUE TITLE
expose isCy ("publicly") in docs and typescript defs

### ISSUE THREAD

**Issue by shlomiassaf** [cypress-io/cypress#3822]
### Current behavior:

`cy,isCy` is exposed physically at runtime but it's not documented and it does not appear is the typescript type definitions.

### Desired behavior:

`cy.isCy` should be exposed in the docs and in TS typings so we know it's officially public and safe to use.

I found that [cypress-pipe](https://github.com/NicholasBoll/cypress-pipe/blob/d42577fdece4290d66a58b4277c86f2ad463860a/index.js#L47) is using it and perhaps others as well... 

Typescript signature should be something like this:

```typescript
    interface Chainable {
      isCy<TSubject = any>(obj: Chainable<TSubject>): obj is Chainable<TSubject>;
      isCy(obj: any): obj is Chainable<any>;
    }
```

This will allow typescript to infer `TSubject` when possible while allowing non `Chainable` types to passthrough without complaints.

**Comment by flotwig** [comment]
This should be exposed, but it should be exposed on `Cypress.isCy()`, since it doesn't return a chainable like all the other `cy.` commands do.
