### ISSUE TITLE
Update cypress/base Docker image to use newer Node versions

### ISSUE THREAD

**Issue by ollie-o** [cypress-io/cypress#3824]
### Current behavior:

Docker image at https://hub.docker.com/r/cypress/base/dockerfile uses `node:10.13`.

### Desired behavior:

We need it to use `node:10.15`, else our app crashes when we `npm start`.

### Versions

N/A

**Comment by jennifer-shehane** [comment]
cc @bahmutov

**Comment by NicHaley** [comment]
Running into issues with this too

**Comment by emilyrohrbough** [comment]
Closing as done. The base image for Node 10.15.3 is [here](https://github.com/cypress-io/cypress-docker-images/tree/master/base/10.15.3).

The latest included docker image uses `node 16.16.0`.
