### ISSUE TITLE
When baseUrl is set, validate that this server is first up and running via net.connect

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#383]
One of the more annoying things about Cypress is that when you forget to start your webserver and try to run your tests - you will get a HUGE cascade of the same error repeating itself over again.

If `baseUrl` is set, we should validate that this server is accessible via `net.connect` and if not, prevent Cypress from opening.

This would guarantee you start the proper webserver(s) ahead of trying to run Cypress.

![screen shot 2017-01-19 at 12 07 12 pm](https://cloud.githubusercontent.com/assets/1268976/22116871/ddf8df02-de3f-11e6-8d74-415476f8d9e8.png)

**Comment by brian-mann** [comment]
Going with this when booting from the Desktop App:

![screen shot 2017-01-29 at 8 41 26 pm](https://cloud.githubusercontent.com/assets/1268976/22410231/5a8df98c-e663-11e6-886a-4c23bc67481c.png)

**Comment by brian-mann** [comment]
Going with this when running headlessly:

![screen shot 2017-01-29 at 8 41 10 pm](https://cloud.githubusercontent.com/assets/1268976/22410238/61543164-e663-11e6-90af-6622a8836291.png)

**Comment by brian-mann** [comment]
Fixed in [`0.18.6`](https://github.com/cypress-io/cypress/wiki/Changelog#0186-01292017).

**Comment by vswethalakshmi** [comment]
@brian-mann I wonder if this causing issues with the baseURL check failing when running cypress behind a proxy. As I saw in some docs that net.connect doesn't have support for proxy.

**Comment by jennifer-shehane** [comment]
@Akshaya0309 This is there on startup to tell you that we detected that your local server at `http://localhost:8900` is not running. So you'll likely want to start your server before starting up your tests.
