### ISSUE TITLE
Cypress Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by smithhan** [cypress-io/cypress#3830]
I have getting error after run this code.

sample_spec.js
```js
describe('Vist testing', function() {
    it('finds the content "type"', function() {
      cy.visit('http://localhost:3000') 
  
      cy.contains('Sign in')
     
    })
  })
```

error screen is following
![image](https://user-images.githubusercontent.com/40197547/55050533-f6741b00-502f-11e9-81a2-96502859bb48.png)

Please help .. who knows this solution?

**Comment by jennifer-shehane** [comment]
Can you try opening your devtools to see if there are any errors printed there? This looks to be originating from your application code. 

Generally I see this error in my applications when an XHR request responds with <html> rather than what it's supposed to.

**Comment by smithhan** [comment]
I found the issue reason.
My index.html includes jquery.js and it happen this issue.

![image](https://user-images.githubusercontent.com/40197547/55053182-258f8a00-503a-11e9-837f-13e78a3dfe04.png)

I comment or remove the jquery line in index.html and rerun it.



Then, its issue goes away.  :100: 
I think my jquery has some issue.

Thanks @jennifer-shehane for your concern.

**Comment by Karuhanga** [comment]
If someone else runs into this in the future, mine was down to trying to load a non existent JS file(from my index page).

Adding this to the test file got me on the right track;

```
Cypress.on('uncaught:exception', (err, runnable) => {
  console.log(err);
  return false;
})
```

**Comment by KdKwarteng** [comment]
For me I fixed it by removing breakpoints I had previously set
