### ISSUE TITLE
I have one cypress test -that is taking me to authentication page and i passes the correct credentials ,but its always showing authentication fails...

### ISSUE THREAD

**Issue by midhun8454** [cypress-io/cypress#3831]
Some times it get passes with `cypress open` ,but it always fails in `cypress run`.

i am using `cy.visit(TRIP_DETAILS_URL);` in `before` function

Actually i have 2 test cases in my spec file with login function on both. First test case always fails says authentication getting failed and second test case always pass-check the same credentials and pass through )
am not sure how this happens .Can anybody help on this will be great..since am stuck on it.
am checking on mac

  │ Cypress:  3.1.5                                                            │
  │ Browser:  Electron 59 (headless)
This is my current version am trying...

**Comment by midhun8454** [comment]
"before all" hook for -this is the command appended before my string written in 'it' keyword

**Comment by jennifer-shehane** [comment]
What is the failure you are encountering when the visit fails. Can you post the error message or a screenshot please?

**Comment by midhun8454** [comment]
its telling credentials are not valid @jennifer-shehane .This i got via cypress open

"before all" (with it invocation) in cypress run

**Comment by midhun8454** [comment]
<img width="556" alt="error1" src="https://user-images.githubusercontent.com/40997155/55057594-9f059780-508f-11e9-850d-06990f90edd1.png">

**Comment by midhun8454** [comment]
`describe('Qualified Booking  in US POS', () => {
  describe('Traversing through "Details page" and "My Page"', () => {
    before(() => {
      cy.visit(TRIP_DETAILS_URL);
      cy.url().should('include', '/user/itin');
      cy.get('#unified-itin-emailId').type(ITIN_EMAIL_ID);
      cy.get('#unified-itin-number-text').type(ITINERARY_NO);
      cy.get('button:contains("Submit")').click();
      cy.url().should('include', '/trips/');
      cy.title().should('match', new RegExp(`Itinerary: ${HOTEL_NAME_FOR_QUALIFIED}`));
    });

    it(`Navigation should work from Details page to MyBooking page`, () => {
      let viewName = "My booking";
      cy.get(`.navigationArea .uitk-card-link`)
        .eq(0)
        .click();
      cy.get('h1').contains(viewName);


    });

   
  });
});`

**Comment by jennifer-shehane** [comment]
Hey @midhun8454, we'd have to know a lot more about how credentials are processed for your application. I can't do much with the information given as is. Where are you seeing this error about credentials?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
