### ISSUE TITLE
Show "cy.route" commands in the Command Log

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3834]
### Feature

Related to common confusion about intercepted / spied on XHR calls from the application shown in https://github.com/cypress-io/cypress/issues/2188#issuecomment-477150544

Here is a screenshot of the problem

![55077972-cea8a580-5077-11e9-8edc-36f159fa9e2e](https://user-images.githubusercontent.com/2212006/55090909-4aa9ea00-5086-11e9-8cfd-2cf9c4f85025.png)

The user thinks that `cy.wait('@read')` is not working.

## UI

The Command Log currently shows ALL XHR calls. In this case the code starts listening to XHR calls using `cy.route` TOO LATE

```js
cy.visit()
cy.server()
cy.route().as('read')
cy.wait('@read')
```

But the XHR call has already happened. The user does NOT notice missing "@read" alias next to the XHR in the command log, and mistakenly thinks there is a problem with `cy.wait('@read')` ...

## Proposal

Show `cy.route` command in the Command Log, something like  `started spying on /api/** as @read` or `started stubbing /loing as @login`. Then it will be SUPER CLEAR that XHR happens BEFORE the “cy.route”

**Comment by jennifer-shehane** [comment]
I like this idea. 💡 I see this problem A LOT!

**Comment by jennifer-shehane** [comment]
Closing as cy.route is deprecated. We do have work lined up to display more information about network logs and which ones were intercepted, stubbed, aliased, etc. So be on the lookout for that.
