### ISSUE TITLE
cy.its() no longer waits on undefined

### ISSUE THREAD

**Issue by tnightingale** [cypress-io/cypress#3837]
### Current behavior:

`cy.its()` yields `undefined`.

```javascript
cy.window().its('__store__').then((store) => {
    ...
    /* `store` is undefined as value is yielded before my application gets a chance to set `window.__store__ = myStore;` */
});
```

### Desired behavior:
Docs state:

> .its() will automatically retry itself until the property exists on the subject.

https://docs.cypress.io/api/commands/its.html#Assertions

### Steps to reproduce: (app code and test code)

Interestingly, asserting that the yielded property exists resolves this issue:

```javascript
cy.window().its('__store__').should('exist').then((store) => {
    ...
    /* `store` is *not* `undefined` 👌 */
});
```

I suspect all that is required is that the documentation needs to be updated to indicate that by default it will yield `undefined` unless there's a subsequent command that triggers the retry behaviour/state.

### Versions

Cypress 3.2.0
macOS: 10.14.3
Chrome 73

**Comment by Bkucera** [comment]
Hi @tnightingale thanks for letting us know about this. The PR https://github.com/cypress-io/cypress/issues/1531 was incorrectly targeted at the wrong branch.

We'll revert this in the next release, and will keep the behavior you expect.
