### ISSUE TITLE
Reusing spec.js files to reduce code and being more DRY

### ISSUE THREAD

**Issue by kwoxer** [cypress-io/cypress#3840]
### Current behavior:

1. Create e.g. a `registration.spec.js` (does a full registration process)
2. Create e.g. a `offer.spec.js` (does click on a offer link and starts booking, then coming to the register page and doing a full registration process)

### Desired behavior:

1. Create e.g. a `registration.spec.js` (does a full registration process)
2. Create e.g. a `offer.spec.js` (does click on a offer link **and imports the `registration.spec.js`**)

### Versions

Cypress 3.2.0
Ubuntu 18.04

### Why that procedure?

Because I would like to reduce core. DRY principle. Is there a proper way to solve this. Or is rewriting specs and repeating stuff the best and already a proper way to solve this in cypress?

I was not able to find a good solution. The only way I could think of is to create a custom function. But with reusing `spec.js` files I think this would be more modular.

**Comment by Lakitna** [comment]
You can take a look at custom commands https://docs.cypress.io/api/cypress-api/custom-commands.html#Best-Practices

You could use plain old javascript imports to create dynamically generated tests https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Dynamically-Generate-Tests For example:

```javascript
// offer.spec.js
before(function() {
    require('registration.spec.js');
});
```

Also take a look at best practices, specifically this part about skipping steps in certain cases https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State

**Comment by kwoxer** [comment]
Sounds great. Gonna test it.

**Comment by brian-mann** [comment]
Read through the best practices and watch this talk I gave last year: https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State

**Comment by kwoxer** [comment]
I think I need some help. Here is what I tried out and yeah it did not work. I'm not sure what my issue is. Maybe you have some ideas:

```
const cypress = require('cypress')
cypress.run({
  spec: './cypress/integration/examples/actions.spec.js'
})
```

that says: Error: **Your OS "browser" is currently not supported by node-cachedir.**
I'm not sure what that message has to do with an require. Tested with Chrome 71 and Chromium 73.

Afterwards I tried:
```
before(function() {
    require('registration.spec.js');
});
```
that says: Error: Cannot find module 'registration.spec.js' from '/opt/cypress/cypress/integration'

The spec file exists.

Do you have any idea? I'm totally out of ideas currently.

**Comment by jennifer-shehane** [comment]
What file did you add the `require('cypress')` code in?

**Comment by kwoxer** [comment]
The are both .spec.js files. One is for the registration only. The other one as I said should contain that registration specs and add some more.

Both are located in the same folder.

**Comment by kwoxer** [comment]
Would be awesome to get just one hint on this. I think this is important for all the developers who want to write clean code and reusing code fragments.

**Comment by cwellmer-daparto** [comment]
I have the same issue and need help.
I would like reuse specs in other specs so that i could write component test and reuse them in other contexts.

**Comment by cwellmer-daparto** [comment]
> _Afterwards I tried:_
> 
> ```js
> before(function() {
>     require('registration.spec.js');
> });
> ```
> 
> that says: Error: **Cannot find module 'registration.spec.js' from '/opt/cypress/cypress/integration'**
> 
> The spec file exists.
> 
> Do you have any idea? I'm totally out of ideas currently.

Use simplified:
```js
require('/opt/cypress/cypress/integration/registration.spec.js')
```
or if you like it relative:
```js
require('./registration.spec.js')
```

**Comment by bahmutov** [comment]
Your tests can be exported from a file and imported into the spec files - they are plain functions

Read the entire explanation in https://www.cypress.io/blog/2019/12/06/use-meaningful-smoke-tests/

```js
// cypress/integration/smoke.js
/**
 * This test goes through a longer user story
 * trying to do almost everything a typical user would do.
 */
export const smokeTest = () => {
  cy.visit('/')
  cy.log('add 3 todos')
  ...
}
```

You can import and use the above `smokeTest` from a spec file

```js
// cypress/integration/smoke-spec.js 
import { smokeTest } from './smoke'

it('does not smoke', () => {
  smokeTest()
})
```

A good use case would be to run the same test in different viewport resolutions

```js
// cypress/integration/viewports-spec.js 
import { smokeTest } from './smoke'

Cypress._.each(['macbook-15', 'iphone-6'], viewport => {
  it(`works on ${viewport}`, () => {
    cy.viewport(viewport)
    smokeTest()
  })
})
```

**Tip:** We can skip non-spec files by using `testFiles: *-spec.js` file mask in `cypress.json` file
