### ISSUE TITLE
Button click event is not working on Cypress, when we use vue js $emit and $on

### ISSUE THREAD

**Issue by vijeeshvofox** [cypress-io/cypress#3842]
I have vue js application which contains the parent component and child component. I placed a button 'Submit' on parent component and it invokes api call on the child component.

Please find my source code on the parent component
```html 
<button type="button" @click.prevent="buttonSubmitEvent">
  Submit
</button>
```

```js
export default class EditModal extends Vue {
private buttonSubmitEvent(): void {
this.$router.app.$emit("saveEventTriggered");
}
}
```

Please find my code on the child component

```js
export default class EditHighlights extends Vue {
private mounted() {
this.$router.app.$on("saveEventTriggered", (data: any) => {
this.updateHighlights();
return;
});
}
private async updateHighlights() {
alert("api call");
}
}
```

When user clicks the ‘Submit’ button on the parent component, the method ‘updateHighlights’ should be worked. It is working on browser but not working on Cypress. Can any one help me to solve this issue?

**Comment by bahmutov** [comment]
Can you make a reproducible repo with the vue code and cypress test so we can run it?

**Comment by jennifer-shehane** [comment]
Can you also provide the test code you wrote in Cypress that is not working and display any error messages, if any?

**Comment by vijeeshvofox** [comment]
[parentchildtest.zip](https://github.com/cypress-io/cypress/files/3023190/parentchildtest.zip)

I have attached zip file which contains  reproducible Code with this post. 

On this source code I have used the cypress comment  `cy.get('#btnSubmitHighlights').click();` on test file. The method `updateHighlights` on the file ‘EditHighLightsComponent.controller.ts’ is not getting invoked when cypress command  `cy.get('#btnSubmitHighlights').click();` is executed. Can any one help me to solve this issue?

**Comment by ajhartenbaum** [comment]
Odd question, but does it work if you go back to Cypress version 3.1.5? We seem to be having an issue with clicks on 3.2.0. Might be related

**Comment by jennifer-shehane** [comment]
@vijeeshvofox thanks for providing the application and test code. 

When I run the test provided running `npm run test:e2e`, I see the following error in the Test Runner:

<img width="553" alt="Screen Shot 2019-04-01 at 9 50 01 PM" src="https://user-images.githubusercontent.com/1271364/55339243-4fc4ca00-54c8-11e9-8713-85abc7119b60.png">

Cannot read `app` of undefined - the error message indicates that this error is coming from your application code. If you click on this error, you will see a console.log of the stack trace in dev tools

<img width="1009" alt="Screen Shot 2019-04-01 at 9 50 11 PM" src="https://user-images.githubusercontent.com/1271364/55339301-6a973e80-54c8-11e9-9147-75a3576b80a8.png">

Which leads to this code where `this.$router` is undefined in your `EditModalComponant.vue`

<img width="504" alt="Screen Shot 2019-04-01 at 9 48 43 PM" src="https://user-images.githubusercontent.com/1271364/55339328-7551d380-54c8-11e9-87a6-97842a9cb0ac.png">

Is this the same error you are seeing? Let me know it's different or if I did not run the right test command.

**Comment by vijeeshvofox** [comment]
On the button click event, I have called a method called "updateHighlights()". It is not getting fired on the cypress. 
On the test file, I have used below code
Please find the screenshot of my running application

**Comment by vijeeshvofox** [comment]
@jennifer-shehane , Thank you for your reply. As you told, the `this.$router.app` was not available on the test file. So I have imported the VueRouter in to test file.

`import  VueRouter from 'vue-router';`

then I used below code to mount the component on test file

 ```
const extensions = {   plugins: [VueRouter],  components: {     Popup    }    }
    const router = {};
     beforeEach(mountVue({ template, router,data }, { extensions }))
```

it is worked for me
