### ISSUE TITLE
cy.type('{insert}') is not supported

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3845]
### Current behavior:

```
CypressError: Special character sequence: '{insert}' is not recognized. Available sequences are: {selectall}, {del}, {backspace}, {esc}, {{}, {enter}, {leftarrow}, {rightarrow}, {uparrow}, {downarrow}, {home}, {end}, {alt}, {option}, {ctrl}, {control}, {meta}, {command}, {cmd}, {shift}
```

### Desired behavior:

`{insert}` should be a supported key. Not sure why it isn't. For that matter, `{pageup}` and `{pagedown}` should also be supported.

### Versions

3.2.0

**Comment by jennifer-shehane** [comment]
Here's the most recent PR adding support for the `{home}` and `{end}` chars. It should help anyone wanting to get started adding support for these chars as well. https://github.com/cypress-io/cypress/pull/3071

**Comment by desfero** [comment]
@jennifer-shehane why we don't allow putting Unicode key codes inside curly braces like this 
 `cy.get('...').type('This is page up {33}')` (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) or even  better with `cy.get('...').type('This is page up {PageUp}')` (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)
