### ISSUE TITLE
Crash "Cannot read property 'error' of undefined"

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3847]
### good

A test like this work fine - cannot find an element, times out

```js
it.only('works', () => {
  cy.get('fff', { log: false }).type('foo')
})
```

<img width="343" alt="Screen Shot 2019-03-29 at 11 15 38 AM" src="https://user-images.githubusercontent.com/2212006/55242619-00567380-5214-11e9-83f4-e06cca923b5f.png">

### bad

But if I change the selector to be like this it crashes badly immediately (yes, I have just added backticks around `'foo'` string

```js
it.only('works', () => {
  cy.get(`'fff'`, { log: false }).type('foo')
})
```

<img width="341" alt="Screen Shot 2019-03-29 at 11 16 32 AM" src="https://user-images.githubusercontent.com/2212006/55242781-4f9ca400-5214-11e9-8b66-3e246652dfea.png">

Seems the crash happens at the line `options._log` in
```js
e.onFail = function() {
    return options._log.error(e);
}
```

<img width="1061" alt="Screen Shot 2019-03-29 at 11 16 52 AM" src="https://user-images.githubusercontent.com/2212006/55242773-4a3f5980-5214-11e9-9b04-dca91aa648f8.png">

### removing log: false

If I remove `{log: false}` from `cy.get` command the test correctly shows an error message

```js
it.only('works', () => {
  cy.get(`'fff'`).type('foo')
})
```

<img width="341" alt="Screen Shot 2019-03-29 at 11 18 43 AM" src="https://user-images.githubusercontent.com/2212006/55242890-8a9ed780-5214-11e9-8e17-c01af7dfc94c.png">

**Comment by jennifer-shehane** [comment]
Why though? 🤦‍♀️

**Comment by bahmutov** [comment]
Not enough defensive programming

**Comment by ithompson4** [comment]
Can I try fixing this? Thanks.

**Comment by jennifer-shehane** [comment]
@ithompson4 yes we would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by ZWkang** [comment]
@jennifer-shehane 
i saw the querying.coffee file.
here have some codes :
```js
_.defaults(options, {
        retry: true
        withinSubject: cy.state("withinSubject")
        log: true
        command: null
        verify: true
      })
```

it allows you can pass a options.log to control options._log initialization

```js
return if options.log is false
options._log ?= Cypress.log
          message: selector
          referencesAlias: if aliasObj?.alias then {name: aliasObj.alias}
          aliasType: aliasType
          consoleProps: -> consoleProps
```

the code looks like allow log: false to happen.

maybe just use options._log.error when options.log is true

when options.log is false just return error object

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/4127, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by Nikh27091** [comment]
I too had the same issue but it got resolved if you write the before function outside describe... example below

///<reference types="cypress"/>
before(function () {
  cy.fixture('example').then(function (data) {
    this.data = data;
  })
})

describe('TestSuite', function() 
 {
}
