### ISSUE TITLE
allow disable of DOM snapshots for stubs and spies

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3849]
I use a lot of spies and stubs, and don't need a DOM snapshot every time a spied function is called, since a DOM snapshot is memory/CPU intensive

We should be able to disable the snapshot similar to how we can disable the log:

```js
cy.stub().log(false)
cy.stub().snapshot(false)
```

**Comment by bahmutov** [comment]
Can we do our typical cy.command(..., {snapshot: false})?

**Comment by jennifer-shehane** [comment]
`cy.stub().log(false)`

Does this work?? This is not an intended use of `.log()` as far as I understand it. `.log()` is a parent command meant to be directly chained off of `cy` and should log what is passed in as an arg, I don't think this would affect the `cy.stub()` logging. 

Aside from this, I would advocate for extending the `options` of most of our commands to allow for `snapshot: false`, just as they allow for `log: false`. See `blur` for example: https://on.cypress.io/blur#Arguments

Although, I think that the true win here should be fixing the snapshots to not be so memory intensive as outlined here: https://github.com/cypress-io/cypress/issues/2366#issuecomment-473219896

**Comment by Bkucera** [comment]
@jennifer-shehane `.log` chained off of a cypress stub/spy sets whether the stub will log or not. We do this because you cannot pass an options object to `cy.stub()` (theres no good way to know whats the options object and whats the stub subject)

maybe simply support a `.options([..options])` method on a stub/spy instance to set the options.

here's where we create the `.log` function on a stub/spy https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/agents.coffee#L187

**Comment by Bkucera** [comment]
here's where I went ahead and implemented the `.snapshot` function: https://github.com/cypress-io/cypress/blob/test-retries/packages/driver/src/cy/commands/agents.coffee#L193

**Comment by monkeytroy** [comment]
Is there a way to do this at a page/window level?   My page loads 50 .proto files and each one creates a log entry and dom snapshot that I don't need to see.

**Comment by jennifer-shehane** [comment]
You can set the [`numTestsKeptInMemory`](https://on.cypress.io/configuration#Global) to the number of tests you'd like snapshots stored for (0 if you want them off altogether).

`cypress.json`

```json
{
  "numTestsKeptInMemory": 0
}
```
