### ISSUE TITLE
Prompted to save password when submitting login form

### ISSUE THREAD

**Issue by davidnorth** [cypress-io/cypress#385]
Likely a problem with my Chrome version (51.0.2704.106) will try upgrade.

    cy.visit('http://www.stickermule.com/account')
    cy.get('#spree_user_email').type('someone@example.com')
    cy.get('#spree_user_password').type('123123{enter}')

**Comment by jennifer-mann** [comment]
Can verify that password prompt does not display in Chrome version `55.0.2883.95`.

I also actively tried to have it save a login by having the Chrome 'prompt password' settings turned on and also having a user profile logged into a google account. I couldn't get password prompt to appear. 

Let us know if the upgrade solves the issue.

**Comment by davidnorth** [comment]
Upgrading Chrome did resolve this. Seems to run faster too.

**Comment by brian-mann** [comment]
Okay cool, likely earlier versions did not support the flag to disable this.
