### ISSUE TITLE
After upgrading to 3.2.0 specs won't run on chrome or chromium only on Electron browser

### ISSUE THREAD

**Issue by acyuta108** [cypress-io/cypress#3852]
### Current behavior:
```
Can't start server
EACCES: permission denied, unlink '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js'  
```
![image](https://user-images.githubusercontent.com/923103/55303105-8b489100-5401-11e9-822c-27b1d5bfb142.png)

Debug output:
```
$ DEBUG=cypress:* 
cypress:server:events send error: { Error: EACCES: permission denied, unlink '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js'   cause: { Error: EACCES: permission denied, unlink '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js'   errno: -13, code: 'EACCES', syscall: 'unlink', path: '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js' }, isOperational: true, errno: -13, code: 'EACCES', syscall: 'unlink', path: '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js' } +21ms                                                                
  cypress:server:events sending ipc data { type: 'launch:browser', data: { id: 0.19919725450670933, __error: { name: 'Error', stack: 'Error: EACCES: permission denied, unlink \'/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js\'\n\n', message: 'EACCES: permission denied, unlink \'/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js\'', cause: [Object], isOperational: true, errno: -13, code: 'EACCES', syscall: 'unlink', path: '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js' } } } +1ms
```

### Desired behavior:
Browser should open and run selected spec(s)

### Steps to reproduce: (app code and test code)
```
$(npm bin)/cypress open # which currently points to ~/.cache/Cypress/3.2.0/Cypress/Cypress
Click on any spec
Error shows on app screen
```

If I clear (rm -rf ~/.config/Cypress) the config folder it gets recreated on next run, but error persists.
If I switch to Electron browser, specs run as expected.
If I run specs from the cli (`$(npm bin)/cypress run`), specs run as expected.

### Versions
Cypress 3.2.0
Chrome and Chromium 72
Linux NixOS 4.14.98

**Comment by jennifer-shehane** [comment]
The only change I can think of from 3.2.0 with the extension was us adding an extension id

>The Cypress Chrome extension now has a static ID of `caljajdfkjjjdehjdoimjkkakekklcck`. This allows Cypress to be added to extension whitelists for those working under corporate policies that prohibit extensions. Addresses #3673, #1239 and #2494 

Had you at some point set up some permissions around allowing Cypress as a Chrome extension within your company or anything in the past?

**Comment by acyuta108** [comment]
I did read that in the CHANGELOG. I am pretty certain that's not the case. Another user reported the same issue to me via Nixos/nixpkgs repo. 
I'll dig in to see if there is anything else we need to do in order to get Cypress 3.2.0 working on NixOS.

**Comment by mmahut** [comment]
I confirm this persist in 3.4.0.

**Comment by acSpock** [comment]
Getting this same error in 3.4.0 and in 3.3.1

**Comment by IramFaisal** [comment]
I am also able to see this error. I have latest cypress version and my chrome version is 75. 
![cypress_issue](https://user-images.githubusercontent.com/50909488/63239923-f1299e00-c266-11e9-96b4-1e346702d4dc.png)

**Comment by ArshadIram** [comment]
This issue has fixed for me it was only happends for chrome 75 version. Now i have chrome 76 version

**Comment by mmahut** [comment]
Having the same problem with chrome 76.

**Comment by ArshadIram** [comment]
try used sudo before using cypress UI interface

**Comment by DylanVann** [comment]
I have encountered this issue. Using `sudo yarn cypress open` works though.

**Comment by Pneumaticat** [comment]
I believe the problem is that all the cypress files in the NixOS store are readonly. Doing `chmod 777 /nix/store/...-cypress-3.4.1/opt` fixes the problem, but is obviously a major hack (you have to remount the nix store read-write).

**Comment by rasendubi** [comment]
Here is my attempt to fix that: https://github.com/cypress-io/cypress/pull/5579

I wasn't able to test it, though. So if someone could help me building a zip (see PR), that would be awesome.
