### ISSUE TITLE
Simulating Drag and Drop

### ISSUE THREAD

**Issue by teterin** [cypress-io/cypress#386]
I am trying to figure out how I can create test to DnD.
It seems I have to do 3 actions:
- mousedown
- mousemove
- mouseup

But I am not sure how I can do it exactly. Can you give an example?

**Comment by brian-mann** [comment]
You just need to either fire these events directly or build them up yourself and dispatch them.

That's all the browser is doing under the hood as well.

We're working on a `cy.trigger` function to make this easier but there are examples of us doing this here:

https://github.com/cypress-io/cypress-example-recipes/blob/master/cypress/integration/hover_hidden_elements.js#L79

I'll keep this issue open until we have clearer workarounds.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by fluffywaffles** [comment]
@RandallKent

Sorry to reopen an issue here, but any updates on a solution for this approaching release?

**Comment by RandallKent** [comment]
Hey @fluffywaffles - This will land (with documentation) in our 0.20.0 release ([Roadmap](https://docs.cypress.io/guides/references/roadmap.html)). This is a big release for us and last I heard, @brian-mann was thinking 0.20.0 would release in a couple weeks, but don't hold me to it haha

In the mean time, I've updated the links in [Jan 23rd](https://github.com/cypress-io/cypress/issues/386#issuecomment-274499609) comment if you're looking for a workaround.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
