### ISSUE TITLE
Overriding user-agent when using cy.request 

### ISSUE THREAD

**Issue by AbdullahZN** [cypress-io/cypress#3873]
### Current behavior:

`cy.request` overrides the **user-agent** if it is provided in the `options.headers` object of the request

### Desired behavior:

If the `User-agent` is explicitly set in `options.headers` object when using `cy.request` it should not be overwritten with the current browsing session's **user-agent**.

### Steps to reproduce: (app code and test code)

e.g:

This implementation
```js
cy.request({
  url,
  method: 'GET',
  headers: {
    'user-agent': 'test-agent',
  },
}).then(response => {
  expect(response.requestHeaders).to.have.property('user-agent', 'test-agent');
});
```

leads to:
<img width="478" alt="Screen Shot 2019-04-03 at 17 10 44" src="https://user-images.githubusercontent.com/19940719/55490091-74898080-5633-11e9-8ab3-0934573959c9.png">

### Versions

Cypress: 3.1.5
OS: MacOS 10.13.3
Browser: Chrome - Version 73.0.3683.86

**Comment by AbdullahZN** [comment]
I already have a working PR to handle this if you guys are ok to integrate the feature.

**Comment by jennifer-shehane** [comment]
Hey @AbdullahZN, yes we would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by jennifer-shehane** [comment]
Relevant issue regarding user-agent here: https://github.com/cypress-io/cypress/issues/3719

**Comment by AbdullahZN** [comment]
Thanks @jennifer-shehane, I just opened the PR for this feature.
Regarding `cy.visit` issue, it will require more work and I think should be part of another PR.
Does that sound right?

**Comment by jennifer-shehane** [comment]
Yes, that sounds right
