### ISSUE TITLE
Environment variables being ignored (--env method)

### ISSUE THREAD

**Issue by chrisjpatty** [cypress-io/cypress#3879]
### Current behavior:

The documentation for the `--env` cli method of using environment variables doesn't make it clear if these environment variables should also be available when running in headed mode. When I call this cli command:

```
npx cypress run --headed --env --FULL_URL=testurl.com
```

The environment variables appear to be completely ignored. When I log the `FULL_URL` variable like this:
```js
cy.log(Cypress.env("FULL_URL"))
```
the log is undefined.

### Desired behavior:

I would expect that environment variables passed via `--env` would be respected.

### Steps to reproduce: (app code and test code)

All I did was install cypress via `yarn add --dev cypress`, and setup a basic test like this:

```js
const getBaseUrl = () => {
  cy.log(Cypress.env('FULL_URL'))
  const URL = Cypress.env('FULL_URL')
  const BASE_URL = URL ? URL : `localhost:${Cypress.env('DEV_PORT') || 3000}`
  return BASE_URL
}

context('Idaho Wizards', () => {
  beforeEach(() => {
    cy.visit(getBaseUrl())
  })
 it("basic test", () => {
   cy.get("main")
 })
})
```

and then run the cli command describe above.

### Versions

Mac OS 10.14.12
Cypress Version 3.2.0
Latest Chrome

**Comment by bahmutov** [comment]
@chrisjpatty read the documentation https://on.cypress.io/environment-variables - you should pass with `npx cypress run --headed --env FULL_URL=testurl.com`
