### ISSUE TITLE
How to upload a file in input type file?

### ISSUE THREAD

**Issue by cristopher-rodrigues** [cypress-io/cypress#388]
Hi guys, I'm trying to upload a file simulating a click.

There is a way to simulate a upload via browser interface, like a user?

![image](https://cloud.githubusercontent.com/assets/3486950/22214181/e7c89be4-e17d-11e6-92b6-4fa4ca051135.png)

Thanks!

**Comment by jennifer-mann** [comment]
Duplicate #170

**Comment by taofeeq3372** [comment]
Hey guys!!!

kindly help with idea on how this can be archived
once the file get uploaded, i want the file name to replace "No file chosen" and so want the name and the file to cancel whenever i click the delete button.
![capture](https://user-images.githubusercontent.com/23293728/43533761-8591b77c-95ad-11e8-9813-400a7e976f15.JPG)
