### ISSUE TITLE
Reporter doesn't receive test failures 

### ISSUE THREAD

**Issue by sjones6** [cypress-io/cypress#3881]
### Current behavior:

In CI, I'm seeing the following sporadically:
1) Despite being tests in a file, Cypress shows a failure. The logged message "No Tests to Report" comes from the reporter which doesn't receive information about the test run.
![Screen Shot 2019-04-03 at 4 26 03 PM](https://user-images.githubusercontent.com/12819256/55510882-45701080-562d-11e9-9206-bea9cd5bda10.png)
2) Cypress reports that the spec failed  in the summary.
![Screen Shot 2019-04-03 at 4 27 10 PM](https://user-images.githubusercontent.com/12819256/55510929-5a4ca400-562d-11e9-9e5c-8c00199c8fa9.png)
3) The process exits with exit code 1 (as expected), but no failures are reported since the reporter never got the information.
![Screen Shot 2019-04-03 at 4 31 06 PM](https://user-images.githubusercontent.com/12819256/55511160-e8c12580-562d-11e9-8ce2-025b3011db80.png)

### Desired behavior:

The reporter should get information about each test being run when the test suite ends.

### Steps to reproduce: (app code and test code)

Sorry, not sure how to reproduce this for your review. Perhaps if you've got some ideas to debug, I'll be able to narrow in on the problem and submit a repro for your review.

### Versions

Cypress@3.2.0
Docker container based on circleci/node:10.6-jessie-browsers

**Comment by sjones6** [comment]
One more detail, the no test reported seems to come just before this:
```javascript
(node:2765) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exitEarlyWithErr listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by jennifer-shehane** [comment]
Hey @sjones6, can you provide the test code that is within the spec file that is reporting "No tests to report."? Thanks!

**Comment by sjones6** [comment]
This issue seems to have resolved itself. I'm going to close. Thanks!
