### ISSUE TITLE
Test passing despite failed BDD assertions after FileReader.onload

### ISSUE THREAD

**Issue by Clairly** [cypress-io/cypress#3883]
### Current behavior:
I'm trying to test that our app is generating a correct .xlsx file. In order to verify the contents, my test is reading the file using FileReader. However, I've noticed that even if there is a failed `expect().to.equal()`-style assertion, the test passes.

![image](https://user-images.githubusercontent.com/4543140/55518910-9a5e5780-562a-11e9-81da-66c57cda8cad.png)

### Desired behavior:
I expect the test to fail if an `expect` assertion fails.

### Steps to reproduce: (app code and test code)
```js
  beforeEach(() => {
    cy.visit('/export');
    cy.server();
    cy.route('/rest/export*').as('getExportFile');
  });

  it('should allow user to export file and generate correct contents', () => {
    cy.get('[data-cy=exportButton]').click();

    cy.wait('@getExportFile').then(({ response }) => {
      new Cypress.Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onload = () => {
          resolve(reader.result);
        };

        reader.readAsBinaryString(response.body);
      }).then(result => {
        expect(false).to.equal(true); // This fails, as expected, but the test passes
      });
    });
  });
```

### Versions
Cypress 3.20
Mac osx 10.13.6
Chrome 73

**Comment by jennifer-shehane** [comment]
Hey @Clairly, do you happen to have this code anywhere in any of your test + support files?

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})
```

Returning false here will not fail the test when an uncaught exception is caught, but still display the assertion as failing.

**Comment by Clairly** [comment]
A-HA! I do, but in an unrelated test file. How do I reset this listener when it's no longer needed? I'm not seeing it in the docs, but I might just be missing it.

**Comment by Clairly** [comment]
Hi @jennifer-shehane -- I've removed the `Cypress.on('uncaught:exception' [...]` section, and the test is still passing despite the assertion failure. Is there anything else that springs out at you about the code provided above?

**Comment by jennifer-shehane** [comment]
We need an example that we can run locally - the above example I cannot run. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
