### ISSUE TITLE
.trigger(mousemove) doesn't work with slider

### ISSUE THREAD

**Issue by lampo4ka** [cypress-io/cypress#3884]
Hi!

I try to check behaviour of slider. I need to click on it and move it to the right. 
According to your spec I should use `.trigger()`

I use:

```js
it('Slider check', () => {
  cy.get('.slider-selector')
    .trigger('mouseover')
    .trigger('mousedown')
    .trigger('mousemove',  50, 10)
    .trigger('mouseup')
});
```

### Current behavior:

Slider doesn't move at all

### Desired behavior:

Slider should move a little bit (according this coordinate  `.trigger('mousemove',  50, 10)` )

### Versions

Cypress 3.2.0

**Comment by jennifer-shehane** [comment]
Can you check this thread to see if any of these workarounds fix it? It may be the same issue - that the `change` event is not triggered. https://github.com/cypress-io/cypress/issues/1570

**Comment by ericyahhh** [comment]
Seeing the same problem using `.trigger()` on range input sliders.

Using the workaround described in https://github.com/cypress-io/cypress/issues/1570#issuecomment-450966053 worked.

**Comment by jennifer-shehane** [comment]
@lampo4ka Any followup? Were you able to solve your issue?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
