### ISSUE TITLE
Hi i am geting this error don;t know the exact reason

### ISSUE THREAD

**Issue by Harshit2318** [cypress-io/cypress#3885]
Hi i am getting this error don't know the exact reason.

`type()` - type into a DOM element
```
CypressError: cy.visit() failed trying to load:

https://example.cypress.io/commands/actions

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ETIMEDOUT 104.25.215.23:443

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ETIMEDOUT 104.25.215.23:443
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)


Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'Actions'
```

**Comment by Lakitna** [comment]
Is the application you want to test running?

**Comment by jennifer-shehane** [comment]
Are you behind a corporate proxy? If so, try these workarounds - but we also have a fix coming soon for this. https://github.com/cypress-io/cypress/issues/1469

**Comment by jasmine-zhang-nz** [comment]
It looks likes the npm config set proxy won't solve the issue that happened during installing and running the example test. When will this corporate proxy issue can be solved?

**Comment by Harshit2318** [comment]
Hi @jennifer-shehane ,

I have downloaded the latest version 3.3.0. Now corporate proxy issue is resolved.
Thanks.

But i have one question -
I have been using NTLM plugin with my previous Cypress version. 
Do we have NTLM plugin support for the latest Cypress version(3.3.0)

Thanks In Advance

**Comment by jennifer-shehane** [comment]
@Harshit2318 	We do not maintain the https://github.com/bjowes/cypress-ntlm-auth repo. I would suggest opening an issue there.

**Comment by luogan210** [comment]
i am using 3.4.1,this issue is still existing

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run.
