### ISSUE TITLE
Close the cypress browser after executing all testcases

### ISSUE THREAD

**Issue by makwanaparth94** [cypress-io/cypress#3894]
#3894 

Step 1: `npx cypress open`
Step 2: Click on spec file that i need to check 

**Expected : Once the execution of spec file completed , browser should automatically close.

Actual : Not able to close cypress browser automatically like we do in protactor and selenium.**

How to achieve this mechanism?

**Comment by Lakitna** [comment]
I don't think you really need it. Try `cypress run` instead

**Comment by Songyu-Wang** [comment]
The `cypress open` is designed to keep open when we are developing tests, the file watcher will detect code change and rerun updated test. If browser is automatically close, that feature will be useless.

**Comment by jennifer-shehane** [comment]
You could also run [`cypress run --headed`](https://on.cypress.io/command-line#cypress-run-headed) and get a similar experience to what you are asking.

Closing this as we do not intend to change this behavior.

**Comment by nataliaroshchyna** [comment]
@jennifer-shehane hello! how can I close browser window in Cypress?

**Comment by jennifer-shehane** [comment]
@nataliaroshchyna 	Closing the browser window through a Cypress command is not supported.
