### ISSUE TITLE
Mocha's afterEach is missing "this"

### ISSUE THREAD

**Issue by cbromberg** [cypress-io/cypress#3895]
### Current behavior:

In mocha it's documented behaviour that you can access `this`, which in turn gives access to currentTest. See `Mocha.IBeforeAndAfterContext;` just like in `beforeEach`.

With Cypress intercepting `this` and inserting the screenshooter there, it misses to pass on the `this` project, here's the code I found in the debugger:

```js
_afterEach(name, function () {
    onFailed.call(this)
    fn()
})
```

where `fn` is the user-defined `afterEach` function

### Desired behavior:

`this` should be passed on. `fn.call(this)` would achieve that (in the context of the code above).

### Steps to reproduce: (app code and test code)

```js
context('Mocha afterEach', () => {
    beforeEach(function() {
        expect(this).to.be.not.undefined
        expect(this).to.have.property('currentTest')
    })

    afterEach(function() {
        expect(this).to.be.not.undefined
        expect(this).to.have.property('currentTest')
    })

    it('This', () => {
        expect(this).to.be.not.undefined
        expect(this).to.have.property('test')
    })
})
```

### Versions

Cypress 3.2.0

**Comment by Lakitna** [comment]
This might be because Cypress 3.x is using an old version of Mocha (`3.5.3` where latest = `6.1.1`). This has been upgraded in the 4.0 branch.

**Comment by jennifer-shehane** [comment]
Closing this as duplicate of https://github.com/cypress-io/cypress/issues/2528 @chrisbreiding Can you verify this will be fixed with Mocha upgrade?

**Comment by jennifer-shehane** [comment]
This is no longer `undefined` after the Mocha upgrade, but there is a circular reference error thrown when used in this way.

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Test'
    |     property 'commands' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    |     property 'actual' -> object with constructor 'Context'
    --- property 'currentTest' closes the circle

Because this error occurred during a 'after each' hook we are skipping the remaining tests in the current suite: 'Mocha afterEach'
```

`spec.js`

```js
context('Mocha afterEach', () => {
  beforeEach(function () {
    expect(this).to.be.not.undefined
    expect(this).to.have.property('currentTest')
  })

  afterEach(function () {
    expect(this).to.be.not.undefined
    expect(this).to.have.property('currentTest')
  })

  it('This', () => {
    expect(this).to.be.not.undefined
    expect(this).to.have.property('test')
  })
})
```

## 3.8.3

<img width="438" alt="Screen Shot 2020-01-29 at 3 41 01 PM" src="https://user-images.githubusercontent.com/1271364/73342837-c7f94900-42ad-11ea-9c29-8c04d435611c.png">


## 4.0.0

<img width="460" alt="Screen Shot 2020-01-29 at 3 39 51 PM" src="https://user-images.githubusercontent.com/1271364/73342762-9aac9b00-42ad-11ea-9a23-4f5522b5db02.png">

**Comment by fredbuluku** [comment]
No problem you can go a head and skip it if it does not add any value in testing.
