### ISSUE TITLE
Atlassian Pipeline Cypress failed to start.

### ISSUE THREAD

**Issue by smithhan** [cypress-io/cypress#3896]
### Current behavior:

Hello, 

I want to push my code to my bitbucket and pass pull request.

Pushing is good now.

But in building and test part is failed from the cypress part.

![image](https://user-images.githubusercontent.com/40197547/55644106-127d7680-57ff-11e9-9d05-ab53bdc3dfdd.png)
![image](https://user-images.githubusercontent.com/40197547/55644124-24f7b000-57ff-11e9-948e-f2503490c886.png)

### Desired behavior:
I want to pass the test, so cypress run correctly.
![image](https://user-images.githubusercontent.com/40197547/55644239-79029480-57ff-11e9-8a22-c87ad65e3e7a.png)

**Comment by jennifer-shehane** [comment]
Have you tried using our provided docker images? https://github.com/cypress-io/cypress-docker-images

We haven't set up an example for Atlassian that I know of, so I'm not familiar with the setup necessary @bahmutov?

**Comment by bahmutov** [comment]
We do have pipelines example, see successful runs here https://bitbucket.org/cypress-io/cypress-example-kitchensink/addon/pipelines/home You can find the pipeline file here https://bitbucket.org/cypress-io/cypress-example-kitchensink/src/master/bitbucket-pipelines.yml

@smithhan try using Cypress docker image as a base
