### ISSUE TITLE
Remove @cypress/get-windows-proxy from CLI

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3897]
In an effort to keep the size of the npm package down, remove @cypress/get-windows-proxy from the CLI and just detect proxy from registry if they're in the server.

This will mean that `cypress install` on Windows will not automatically read proxy settings from the registry. Users will have to set up their proxy environment variables to do `cypress install` behind a proxy.

**Comment by jennifer-shehane** [comment]
Released in [3.3.0](https://on.cypress.io/changelog#3-3-0)
