### ISSUE TITLE
Bundle Node.js separately, run with just Node.js in CI, make browsers dependencies

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3900]
## Current behavior

The `server` package currently runs inside Electron's node environment, which is pegged to Node 8.2.1 for Electron 1.8.2. In run mode, Electron is really just used as a convenient node.js runtime, since we don't make use of any of the native functionality it exposes.

## Desired behavior

Make all the `server` code compatible with an off-the-shelf Node.js instance. Then, ship Node.js with Cypress, and just use Electron for `cypress open`. 

This would mean that CI users don't need to have `electron` installed at all, which opens the door for us to potentially bundle it as its own NPM module that could be swapped out with another browser in CI.

This would also mean that `xvfb` isn't required, since that's an artifact of Electron expecting a frame buffer.

**Comment by jennifer-shehane** [comment]
Closing as a piece of https://github.com/cypress-io/cypress/issues/3899
