### ISSUE TITLE
Random 7s printed to console during waits

### ISSUE THREAD

**Issue by josh-byster** [cypress-io/cypress#3908]
### Current behavior:
First, thanks for creating such a useful tool. It really makes testing much easier. This is very low priority, and something that may not be specific to Cypress but could be a Travis issue. Something I've noticed is that on Travis CI, consistently random 7s get printed to the console, only during Travis runs, seemingly when things take a while. What makes me think this may be Cypress formatting specific is that I don't see any 7s printed during my build phases that do take quite a few seconds. I haven't seen it when running locally.

<img width="328" alt="Screen Shot 2019-04-08 at 5 18 34 AM" src="https://user-images.githubusercontent.com/8664074/55716952-dc3a2580-59bd-11e9-8300-b2314e64ac42.png">
<img width="404" alt="Screen Shot 2019-04-08 at 5 13 21 AM" src="https://user-images.githubusercontent.com/8664074/55716953-dc3a2580-59bd-11e9-9059-4246a9716fdb.png">

[Link to log](https://travis-ci.com/josh-byster/bus-tracker)

### Steps to reproduce: (app code and test code)
I run `$(npm bin)/cypress run --record --key [MY_KEY_HERE]` as part of my Travis CI build. 

### Versions
Cypress 3.2.0

**Comment by jennifer-shehane** [comment]
Yes, this seems to be happening in our Travis builds as well here: https://travis-ci.org/cypress-io/cypress-example-kitchensink/jobs/517316808 

I have no idea how to even begin googling this as an issue in Travis, but this is not printing in our CircleCI builds: https://circleci.com/gh/cypress-io/cypress-example-kitchensink/2385
