### ISSUE TITLE
Cookies for third-party domains aren't cleared upon exit

### ISSUE THREAD

**Issue by jhaynie** [cypress-io/cypress#391]
When I use `cy.request` to hit a 3rd party domain to login using oauth, the cookies for this domain remain after the session exists.  So when i re-run my test, it thinks I'm still logged in.  Would be nice to have all session data removed upon test exit of the browser.

**Comment by brian-mann** [comment]
Related to #408

**Comment by jennifer-shehane** [comment]
Closing as part of https://github.com/cypress-io/cypress/issues/408
