### ISSUE TITLE
How to capture a radio button having same values

### ISSUE THREAD

**Issue by Harshit2318** [cypress-io/cypress#3916]
Hi all,

i have two radio button with same values how can i capture a particular radio button click

<input id="1003_r_Create" type="radio" name="KT3" value="1003" style="margin-left:100px;">

<input id="1003_r_Modify" type="radio" name="KT3" value="1003" style="margin-left:100px;">

Thanks in Advance

**Comment by mateosilguero** [comment]
By using another identifier, or using https://docs.cypress.io/api/commands/eq.html to select the desire index.

**Comment by Harshit2318** [comment]
@mateosilguero  thanks i got it

@must-git-good  thanks man.
 I was having multiple identical names .. but for sure in two identical names your solution will work.
