### ISSUE TITLE
A fail in the after each hook covers the fail in a test run

### ISSUE THREAD

**Issue by testquantilope** [cypress-io/cypress#3918]
### Current behavior:

When a test case fails and the following after each hook also fails, only the error from the after each hook is printed in the cypress dashboard, but only the fail screenshot of the test case is included.

**Example**
This screenshot is attached to my failed test:
![image](https://user-images.githubusercontent.com/35334883/55787506-b6dd1280-5ab6-11e9-9381-b4f95692205b.png)

The same fail has the following console output, which is obviously incorrect:
![image](https://user-images.githubusercontent.com/35334883/55787593-ea1fa180-5ab6-11e9-93c4-e4729c4eebaf.png)

### Desired behavior:

When a test case fails and the following after all hook also fails, there should be fail messages, one for the test case and one for the after all hook. There should also be a screenshot for both fails attached.

### Steps to reproduce:

1. Create a test case with an after each hook.
1. Make sure the test case itself will fail.
1. Run the testcase.
1. Observe the issue.

### Versions
![image](https://user-images.githubusercontent.com/35334883/55787724-2fdc6a00-5ab7-11e9-852d-39e3d1dc3247.png)

**Comment by jennifer-shehane** [comment]
Yes, this is a bug that we actually JUST encountered ourselves. The work is already in progress for fixing this. Thanks for opening an issue!

**Comment by testquantilope** [comment]
Hi,
Is there any update on this issue?

Especially in combination with this issue it makes it a little painful to debug test cases: https://github.com/cypress-io/cypress/issues/2831

**Comment by cvasile001** [comment]
Hi Everyone. I am also experiencing this issue. Is there any update on this issue? Maybe a workaround?

**Comment by Dimbbass** [comment]
Have the same problem. IT was failed, then after each failed and then all other tests skipped, because fail was in after each block (in fact in test, not in after each)

Will be cool, if anyone offer a workaround.

**Comment by nc-williamss** [comment]
Same here. my after block cleans up, but when it doesn't execute, it causes my next tests to fail because the browser wasn't cleaned up. PLZ halp :)

**Comment by rachelruderman** [comment]
Also experiencing this. How come it hasn't been prioritized yet?

**Comment by joszo** [comment]
Also I'm facing same issue.

**Comment by cvasile001** [comment]
It has been a while, do we know if this is going to be worked on yet?

**Comment by bahmutov** [comment]
@Bkucera any updates on this issue?

**Comment by jennifer-shehane** [comment]
This doesn't happen in all cases of failures, but the below example shows the `afterEach` error being printed instead of the error in the test.

### Click fail in afterEach / it failure for visibility

```js
describe('Tests', () => {
  afterEach(() => {
    // ❗️ does not exist, purposely fails
    cy.get('.foo').click()
  })

  it('test', () => {
   // ❗️ does not exist, purposely fails
   cy.contains('it test').should('be.visible')
  })
})
```

#### During `cypress open`

<img width="523" alt="Screen Shot 2021-01-22 at 2 21 29 PM" src="https://user-images.githubusercontent.com/1271364/105462742-75cee600-5cbd-11eb-9656-abc1b1ab1733.png">


#### During `cypress run`

<img width="993" alt="Screen Shot 2021-01-22 at 2 23 20 PM" src="https://user-images.githubusercontent.com/1271364/105462758-7bc4c700-5cbd-11eb-9d9e-73ed176ce8de.png">

**Comment by cvasile001** [comment]
The problem is click actions do not work in the 'after' section when you have a failure in the 'it' section. So in your example, if you have a legit click action in the 'afterEach', with a good actionable element, does it work?

**Comment by jennifer-shehane** [comment]
yes, somewhat related but not the exact issue if the fact that `click` will not work in afterEach if a test fails: https://github.com/cypress-io/cypress/issues/2831

**Comment by pixelpax** [comment]
This still hasn't been addressed? This is making it nearly impossible for me to debug a CI-only issue.

**Comment by nagash77** [comment]
@pixelpax are you seeing this issue on the latest version of Cypress?
