### ISSUE TITLE
No way to login with a different email address in the Mac App, if you're first attempt fails.

### ISSUE THREAD

**Issue by andyshora-qb** [cypress-io/cypress#393]
When I attempted to login via Github inside the native Mac App, I used an email address which was not authorised. I couldn't get back to the original login form to attempt to use a different email address, even after re-installing the app.

Steps to replicate:

1. Install the Cypress App
2. Login via Github, with an email address which isn't authorised. You'll get an unauthorised response.
3. Close and reopen the app, and notice the unauthorised login happens again without a chance to enter the new email address.

Fixes:

- Logout from Github in the web browser, then reopen.
- File > Open

Desired fix:

- Add a logout button in the UI

**Comment by jennifer-mann** [comment]
The best workaround currently is to Log Out by selecting to `File` > `Log Out` in the Desktop Menu.

<img width="468" alt="screen shot 2017-01-25 at 9 31 49 am" src="https://cloud.githubusercontent.com/assets/1271364/22294390/2cf8ac36-e2e1-11e6-9832-9318ca3b9819.png">

**Comment by brian-mann** [comment]
This is a temporary problem as we will be removing the restrictions to log in initially.

**Comment by RandallKent** [comment]
Another workaround is to add an email address to your GitHub account. They have docs on this @ https://help.github.com/articles/adding-an-email-address-to-your-github-account/
