### ISSUE TITLE
Can't start server error in the Playground when I run any test

### ISSUE THREAD

**Issue by DynamiteTom** [cypress-io/cypress#3934]
### Current behavior:

Can't start server

```
EPERM: operation not permitted, unlink 'C:\Users\DynamiteTom\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache\data_1'
```

### Versions

Version 3.2

**Comment by DynamiteTom** [comment]
Version 3.2 

Can't start server

EPERM: operation not permitted, unlink 'C:\Users\DynamiteTom\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCache\Default\Cache\data_1'

**Comment by jennifer-shehane** [comment]
What operating system and version of npm are you using? I see this issue in 5.4.0 of npm https://github.com/npm/npm/issues/18287

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
