### ISSUE TITLE
Element is visible but can't be clicked

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#3935]
### Current behavior:
Here is an image of a failing test : 
![image](https://user-images.githubusercontent.com/2730609/55902802-21f31b80-5b81-11e9-9e73-d40b1a37cc02.png)

It is really confusing to me that the element is deemed "visible" by cypress, but then says that it is covered by another element and thus can't be clicked. 

Here is the element that is covering it: 
![image](https://user-images.githubusercontent.com/2730609/55903251-1522f780-5b82-11e9-8d54-cdd377b956c0.png)

Maybe this is a basic html/css thing that I'm misunderstanding. Why would the containing span be covering its child? 

Here is the css of that span.
![image](https://user-images.githubusercontent.com/2730609/55903351-4f8c9480-5b82-11e9-8732-d5de1237cb3b.png)

### Versions

Cypress Version 3.2.0 (3.2.0)
MacOSX latest
Chrome 73

Sorry I don't have a place to reproduce this at the moment but hopefully there's enough info here for people to understand what's happening and maybe offer an explanation. 

Thanks

**Comment by Lakitna** [comment]
Visibility is not always the same as actionability. For the time being, you can work around this by using click like this:

```javascript
.click({ force: true })
```

**Comment by BirgitPohl** [comment]
<img width="563" alt="Screenshot 2020-04-24 at 14 28 58" src="https://user-images.githubusercontent.com/4340405/80212940-b61f0c00-8638-11ea-9c00-9a9bf3a5dfb9.png">
<img width="874" alt="Screenshot 2020-04-24 at 14 29 21" src="https://user-images.githubusercontent.com/4340405/80212947-b7e8cf80-8638-11ea-8414-6b67ac084fad.png">

This is an element to be tested. Forcing it to true will falsify every test case we have.

**Comment by sainthkh** [comment]
More than a year has passed and there is no reproducible example. We cannot help closing this issue. If something similar is happening, please open a new issue with a reproducible example.
