### ISSUE TITLE
Chrome crashes with V8 js-flags using quotes

### ISSUE THREAD

**Issue by kelvinau** [cypress-io/cypress#3937]
### Current behavior:
Added launch option for V8 js-flags in `cypress/plugins/index.js`.

```js
    if (browser.name === 'chrome') {
      args.push('--js-flags="--expose-gc --expose-gc-as=abc"');
      return args
    }
```
Chrome crashes after test case starts. If quotes are not used, i.e. `args.push('--js-flags=--expose-gc --expose-gc-as=abc');`, it is worked as expected.

### Desired behavior:

`args.push('--js-flags="--expose-gc --expose-gc-as=abc"');` works as without quotes.

### Versions
Cypress: 3.2.0
OS: Ubuntu 16.04.6 LTS
Browser: Chrome 73.0.3683.103

**Comment by jennifer-shehane** [comment]
Chromium flags are meant to be passed without quotations. The [Chromium team themselves do not pass quotations](https://cs.chromium.org/chromium/src/testing/buildbot/client.v8.fyi.json?q=js-flags&sq=package:chromium&dr=C) as well as our default args. 

All we do is pass the flags onto Chromium. We'd rather not parse these args further before sending them on to Chromium, so we'll be closing this issue.

**Comment by kelvinau** [comment]
It's true for single flag, but for multiple flags you need quotes.
See here: [Chromium team advises to pass quotations for multiple flags](https://cs.chromium.org/chromium/src/third_party/blink/manual_tests/typed-array-memory.html?type=cs&q=js-flags%3D%27&sq=package:chromium&g=0&l=213)
I think this is not critical, but this issue will be a good note for any other developer who faces the same issue.

**Comment by jennifer-shehane** [comment]
Have you tried using single quotes versus double quotes? I'm not sure what Cypress is responsible for here since we are just passing on the args.
