### ISSUE TITLE
{enter} for buttons

### ISSUE THREAD

**Issue by pburkindine** [cypress-io/cypress#3938]
### Current behavior:

Tester cannot `.type({enter})` on a Button element, activating it the same as a click, which is a 508 requirement.

### Desired behavior:

Tester can `.type({enter})` on a Button element, activating it the same as a click.

### Versions
cy 3.2

**Comment by mateosilguero** [comment]
It's working fine for me.
Could share some code ?
this is the way i'm running it: 

```cy.get('button').type('{enter}')```

**Comment by pburkindine** [comment]
I was able to solve the problem by adding a tab index to my button, which should probably have been there anyway.  Thanks!
