### ISSUE TITLE
cy.trigger('mousemove') not functioning correctly for submenu hovering

### ISSUE THREAD

**Issue by playermanny2** [cypress-io/cypress#3945]
### Current behavior:

When using .trigger('mousemove') on my element it does not show the submenu in order for the test to proceed and find the next element.
It just pause, it seems to fire the event as a small grey rectangle appears but it does nto show the actual menu. What's confusing is it does not work with cypress pragmatically, but if i hover over in the browser manually it appears.

<img width="956" alt="cypress_mousemove_1" src="https://user-images.githubusercontent.com/16566894/55983444-0571e480-5c50-11e9-8482-d3ec5dc5f491.PNG">

### Desired behavior:

The submenu would be properly displayed and the test would be able to find my element

<img width="951" alt="cypress_mousemove_expected" src="https://user-images.githubusercontent.com/16566894/55983496-20dcef80-5c50-11e9-8265-9b30149d1f94.PNG">

Test is using the correct event, per event listener test
<img width="103" alt="cypress_mousemove_eventlistener" src="https://user-images.githubusercontent.com/16566894/55983524-32be9280-5c50-11e9-8ec5-44ea54fb2bb3.PNG">

### Steps to reproduce: (app code and test code)

1. Have JupyterLab installed
2. Utilize test( contain can be replaced with viable open with option)

```
cy.get('.p-Menu-item div:contains("Open With")')
                .trigger('mousemove')
            cy.get('.p-Menu-itemLabel div:contains("Voyager")')
                .trigger('mousemove')
                .click()
```

### Versions
3.2.0

**Comment by tnrich** [comment]
@playermanny2  Maybe also try triggering a "mouseover" event. I only trigger the mouseover event on blueprintjs context menus and it seems to work. Different components but maybe you'll have some luck.

**Comment by playermanny2** [comment]
hey @tnrich, thanks for the suggestion! I actually just tried that a few minutes ago(along with some other mouseevents)...no dice. From digging in a bit more, I can see the element being appended to the DOM from the mouseover event, the problem is it isn't visible(I wasn't able to inspect the element to see if it has the proper css attributes as it removes itself whenever going to inspect)...

it should be visible by default on hover, but maybe something changes within the cypress environment, is there maybe  some commands for force showing (I've tried .invoke('show) so far)

**Comment by tnrich** [comment]
@playermanny2 is there a public URL we can point a test to where we can try out JupyterLab or do we have to have it installed locally?

**Comment by playermanny2** [comment]
@tnrich There's a defauly jupyterlab binder https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo

I don't have a public url with the exact extension I'm testing, but you should be able to test the same 'Open With' functionality  with 'mouseover' trigger by opening the context menu on one of the .csv inside the binder environment

**Comment by tnrich** [comment]
I just got it to work with this code: 

```
      cy.visit("https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo")
      cy.contains("Lorenz.ipynb", {timeout: 300000000}).trigger("contextmenu")
      cy.get('.p-Menu-item div:contains("Open With")')
                .trigger('mousemove')
            cy.contains('.p-Menu-itemLabel', "Notebook")
                // .trigger('mousemove')
                .click()
```

![image](https://user-images.githubusercontent.com/2730609/56052396-28f76680-5d06-11e9-8137-c8ffc33f489c.png)

**Comment by playermanny2** [comment]
@tnrich Hmm just tried that within my environment, still doesn't pop up...I then tried it in the binder environment and it worked fine from my cypress install....so a step closer forsure, I now know it has to be something specific within my environment doing some wonky stuff

Thanks for all your help thus far, I'll close this as it isn't a cypress issue!

**Comment by tnrich** [comment]
@playermanny2 maybe it has something to do with the 
```
cy.contains('.p-Menu-itemLabel', "Notebook")
```
vs the 
```
cy.get('.p-Menu-item div:contains("Notebook")')
```
syntax. Because the latter did not work for me.

**Comment by playermanny2** [comment]
@tnrich Yea, I think that's apart of it, but trying your code verbatim in my jupyterlab environment cypress can't even find .p-Menu-itemLabel because it doesn't become visible on the mouseover.... verrrryy weird :(

```
cy.get('.p-Menu-item div:contains("Open With")')
                .trigger('mousemove')
            cy.contains('.p-Menu-itemLabel', "Voyager")
                // .trigger('mousemove')
                .click()
```

**Comment by playermanny2** [comment]
Hey @tnrich -- received an update on these issues, does look like this is expected behavior in jupyterlab. seems like cypress may be triggering the context menu without a right click?? would it be okay for me to bring you into this conversation?

https://github.com/jupyterlab/jupyterlab/issues/6242#issuecomment-487603205

**Comment by ravikiranr26** [comment]
Hi Team,

Im trying the hover too, but couldn't able to get the thing working. The hidden div block is not showing upon the trigger / show command. 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1841796/58569618-c0713400-8236-11e9-82af-7e628315902a.png">

**Comment by playermanny2** [comment]
@ravikiranr26 this appears to be tied to native browser events. Not sure on a workaround, but it is on the radar of the cypress team

https://github.com/cypress-io/cypress/issues/311

**Comment by bhimc-lm** [comment]
not able to find the solution from hrs.. got pissed with mouse hover and cypress.
