### ISSUE TITLE
Proposal: Add new Cypress command .text()

### ISSUE THREAD

**Issue by Lakitna** [cypress-io/cypress#3946]
### Current behavior:
When asserting text we are stuck with the not very specific `.contains()`/`.should('contain')` and the more specific `.should('have.text')` but the latter does not handle whitespace very well (#3887).

### Desired behavior:
Because I don't like the options above I wrote my own `.text()` command. Recently I finalized and published it in the `cypress-commands` plugin (https://github.com/Lakitna/cypress-commands).

I'm writing this issue to see if you are interested in adding this command to Cypress. If you're not, I'll keep `.text()` available via `cypress-commands` and this issue can be closed.

More about the command can be found here https://github.com/Lakitna/cypress-commands/blob/develop/docs/text.md

**Comment by mirhaCode** [comment]
I have the same problem with contains()

When I searched a formated number with `&nbsp;`, matches not worked.

**Comment by Lakitna** [comment]
@mirhaCode If you create an issue in `cypress-command` we can look into how we want whitespace handling to work for `.contains()`. If we have that straight we can implement it there, at least for the time being.

**Comment by jennifer-shehane** [comment]
I've just found this is already an issue here: https://github.com/cypress-io/cypress/issues/630 Closing in favor of longstanding issue.
