### ISSUE TITLE
Wrap scenario and step names in UI

### ISSUE THREAD

**Issue by pburkindine** [cypress-io/cypress#3947]
### Current behavior:

Scenario and step names are truncated with an ellipsis in the UI, making it difficult to tell at a glance what is failing and not.

### Desired behavior:

Names should wrap to the next line.

**Comment by pburkindine** [comment]
![SS 2019-04-11 at 6 52 23 PM](https://user-images.githubusercontent.com/20215564/56003228-41766b00-5c8b-11e9-8abd-6bf5646d2fe4.png)

**Comment by jennifer-shehane** [comment]
The css for these test titles can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/runnables/runnables.scss#L189

The test title's jsx can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/test/test.jsx#L81

Instructions on running the tests for this UI are here (tests are Cypress tests): https://github.com/cypress-io/cypress/blob/develop/packages/reporter/README.md#L65

**Comment by coderwurst** [comment]
Hi! Am I understanding this correctly, that the following is the desired effect:

![image](https://user-images.githubusercontent.com/6804123/58336044-37778880-7e43-11e9-9c1c-7054b65a8baf.png)

**Comment by coderwurst** [comment]
cool - I'm on it https://github.com/coderwurst/cypress/tree/issue-3947

I haven't managed to get the tests fully up and running locally to ensure there are no unwanted effects with very long error names, I'll get some time at the weekend to get another look!

**Comment by brian-mann** [comment]
@Bkucera 	@chrisbreiding 	@flotwig 	@bahmutov 	what are your thoughts on this?

**Comment by chrisbreiding** [comment]
Looks good to me. Here's a screenshot of it in action:

![Screen Shot 2019-06-12 at 1 26 41 PM](https://user-images.githubusercontent.com/1157043/59372563-cc202880-8d15-11e9-98b4-6d23dd5ea9fc.png)

**Comment by Bkucera** [comment]
I like it, but maybe we could hide title names at a certain minimal width, so you dont get the:

:heavy_check_mark: 
d
i
s
p
l
a
y
s

e
m
p
t
y

e

**Comment by coderwurst** [comment]
@Bkucera just the title names and leave the ticks visible?

Alternative Idea - could we set the area to have a mid-width of x pixels, so that single words are still readable?
