### ISSUE TITLE
Vaadin 8 Checkbox cannot be clicked of checked

### ISSUE THREAD

**Issue by iXo** [cypress-io/cypress#3959]
### Is this a Feature or Bug?
After many try to find a way to check a vaadin 8 checkbox (that is a valid html checkbox input element), we can't find a way to click this checkbox, as it is reported as not visible (size of 0x0 pixels) even if we force the action.

### Current behavior:
![cypress_1](https://user-images.githubusercontent.com/401900/56051309-75ff2b00-5d4e-11e9-9497-3fb55a9b9185.png)
![cypress_2](https://user-images.githubusercontent.com/401900/56051353-97f8ad80-5d4e-11e9-84df-95711f683bf1.png)

### Desired behavior:
The check can be checked

### Steps to reproduce: (app code and test code)
Test code could take us some to times to provides, we will update the report once we have pushed a minimal vaadin app with the cypress test, here is the Cypress part that we want to use :
![cypress_3](https://user-images.githubusercontent.com/401900/56051544-51f01980-5d4f-11e9-903d-4fcce3600b21.png)

### Versions
Cypress v3.2.0
Electron embedded with Cypress and Chrome 72
Windows 7

**Comment by bahmutov** [comment]
It has attribute “disabled”, no?

**Comment by iXo** [comment]
Indeed, that's what I am seeing too, I didn't noticed that before.

The code I am providing the a extract, and there is action before that is enabling the checkbox, so maybe I have to perform a should action asking it to not be disabled. I will try to test it, as I am not at work actually.

**Comment by iXo** [comment]
Ok, so I have created a very simple page to test the problem.

On this page you have :
- a single button, that will enable the checkbox
- a standalone checkbox (this one, I can check it via Cypress)
- a table with 2 lines, on each line the second column contains a checkbox, the table AND the checkbox are disable a first, then are enabled when you click on the button.

Here are 2 tests :

the first on will test the standalone checkbox, there is no problem :
`it('simple checkbox', function () {
        cy.get('.v-button').click();

        cy.get('span').should('not.have.class', '.v-checkbox-disabled').within(function () {
            cy.get('input').eq(0).should('not.be.disabled').check({force: true}).should('be.checked');
        });
    });`

the second test try to check the checkbox (second column) of the first line of the table :
`it('checkbox in a table', function () {
        cy.get('.v-button').click();

        cy.get('#checkBoxGrid').should('not.have.class', '.v-disabled').within(function () {
            cy.get('table').within(function () {
                cy.get('tbody').within(function () {
                    cy.get('tr').eq(0).within(function () {
                        cy.get('td').eq(1).within(function () {
                            cy.get('span').should('not.have.class', '.v-checkbox-disabled').within(function () {
                                cy.get('input').check().should('be.checked');
                            })
                        })
                    })
                })
            })
        })
    });`


I am using this beforeEach :
`beforeEach(function () {
        cy.visit('/');
    });`


And finally the page is available here : http://www.kawaiyume.org:8080/

**Comment by iXo** [comment]
Ok, finally I found what was the problem. This is not a Cypress bug. In fact, when the button is clicked, when we tried to enable all the checkbox of the table, we are doing it in a wrong way. The old checkbox (that is disabled) is removed from the dom, then we insert in place a new one that are enabled.
