### ISSUE TITLE
Check installed version on run

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#396]
We want to cache the installation **and** install the latest version when an older version is installed.
Currently the CLI doesn't check if there is already a version installed and if this is the latest.

Some suggestions to improve this behavior:
- On `cypress install` only download/install when the app is not installed
- On `cypress update` only download/install when the app is not installed or it is installed but it is not the latest version
- On `cypress update`/`install` and when a specific version is requested via CLI parameters or CYPRESS_VERSION environment variables, download/install that version if that version of the app is not installed.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
