### ISSUE TITLE
I can not find my test script in cypress test runner

### ISSUE THREAD

**Issue by mv7789** [cypress-io/cypress#3961]
When I open cypress using command: npx cypress open-> cypress test runner opens up where I can not find my test script NewTest.spec.js. Earlier I was able to but now I can not why?
![image](https://user-images.githubusercontent.com/41212104/56069058-14cb5d80-5d36-11e9-9fe9-522fe67dafba.png)
![image](https://user-images.githubusercontent.com/41212104/56069069-29a7f100-5d36-11e9-81c5-8144677618c3.png)

**Comment by Lakitna** [comment]
Are you opening the correct project in Cypress?
Does your cypress.json exclude the tests?
Does your cypress.json not include the tests?

**Comment by mv7789** [comment]
This issue has been resolved. Seems to be some problem with my windows. I restarted my PC and it worked. Thanks.

**Comment by zethzeth** [comment]
I had to add this to my `cypress.config.js`-file:

```
module.exports = defineConfig({
  e2e: {
    specPattern: [
      'cypress/e2e/*.js',
      'cypress/e2e/**/*.js'
    ]
  }
});
```

I elaborated here: [In test runner cannot see tests in newly created folder - cypress](https://stackoverflow.com/a/74742179/1766219)
