### ISSUE TITLE
Unexpected behavior of Google Maps (agm-map)

### ISSUE THREAD

**Issue by taimoortahir7** [cypress-io/cypress#3965]
### Current behavior:

When some location is typed in autocomplete, results don't show until mouse is clicked any where, similarly when location is selected from dropdown, it don't take map to that location until mouse is clicked.

### Desired behavior:

On typing any location or its address it should show results immediately in dropdown and onclick it should take zoom to that map location. 

### Versions

Windows 10, Google Chrome

**Comment by sainthkh** [comment]
More than a year has passed and there is no reproducible example. We cannot help closing this issue. If something similar is happening, please open a new issue with a reproducible example.
