### ISSUE TITLE
cypress dashboard thinks I'm out of private runs even though all my projects are public 

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#3976]
I asked this question on gitter but thought I'd post it here to potentially help others who might be confused by what changed in the cypress plans and to have a link to show my team.

Thomas Rich @tnrich 11:10
Hey there, I'm seeing some issues with the cypress dashboard -- it thinks that I've exceeded my amount of private runs and so has started blocking all of my test recordings. The thing is, while one of my projects was initially private, I switched that shortly after and now all of my projects are public and I'm still seeing Over Limit (You've reached your private test recordings limit of your billing plan. Is there someone who can help me?
Here's my dashboard: https://dashboard.cypress.io/#/projects/8gcfw1/runs/8/specs
As you can see all of my projects are public.

![image](https://user-images.githubusercontent.com/2730609/56234920-29ac3780-603b-11e9-8322-27369db08d2d.png)

Gleb Bahmutov @bahmutov 11:12
@tnrich https://www.cypress.io/blog/2019/04/15/introducing-the-open-source-and-full-featured-seed-dashboard-plans/#Full-Featured-Free-Plan-and-Simplified-Usage-Limits

Thomas Rich @tnrich 11:14
>This change only applies to new Dashboard users; current users won’t see any changes and their plans will continue under the same terms from when they started their subscription. Check out our pricing page for the full details. If you have questions about this feel free to drop us a line at hello@cypress.io.

Thanks for the info @bahmutov . I still have a question though: I had registered the private repo (hde) to use the public cypress dashboard well before this blog post came out. It seems like that repo should qualify for continued service according to this sentence: their plans will continue under the same terms from when they started their subscription

Thomas Rich @tnrich 11:26
@bahmutov When I hit this issue I ended up deleting and re-hooking up all my cypress repos because it was affecting all of my repos including the fully OSS ones. If I could get my two non-OSS repos that were hooked up running on the public cypress dashboard again that would be great. If not please let me know so I can discuss options with my team. Thanks!

#
#
#

Please let me know if I can provide any more information for your team to act on this. 
The two repos that I'd like to have grandfathered in are Teselagen/lims and Teselagen/hde. If this won't be possible please let me know. Or if this was not a mistake and if private repos that were registered for the public cypress dashboard were not supposed to be grandfathered in to the old system, that would be good to know.

**Comment by jennifer-shehane** [comment]
@tnrich Earlier this week we [announced](https://www.cypress.io/blog/2019/04/15/introducing-the-open-source-and-full-featured-seed-dashboard-plans/#) an update to our usage plans and released the [OSS Plan](https://www.cypress.io/oss-plan/) - a new, free plan for non-commercial, open-source projects offering unlimited test recordings and parallelization. We also simplified all of our plans by transitioning to a single Test Recording limit, removing the distinction between “public” and “private” test counts.

Back in January, we notified users via email about this change. Per our [Terms of Service](https://www.cypress.io/oss-plan/), public test recordings were always intended to support the open-source community and we’re excited to offer the OSS Plan in its place.

Unfortunately, our original blog announcement was not clear enough in who would be affected by this change. Current organizations with *paid subscriptions* won’t see any changes and their plans will continue under the same terms from when they started their subscription. Organizations/users using the Seed (free) plan will be subject to the new Seed plan's limits as listed on our [pricing](https://www.cypress.io/pricing/) as well as now have access to parallelization.

We apologize for any inconvenience this transition may have caused. If your project is non-commercial and open-source then please [follow these instructions](https://docs.cypress.io/guides/core-concepts/dashboard-service.html#Open-Source-Plan) to apply for the OSS Plan.

If your project does not qualify you can upgrade to a [paid](https://www.cypress.io/pricing/) subscription or continue using the Seed (free) plan which is limited to 500 total test recordings per month and 3 users.

Don't hesitate to reach out to support@cypress.io with any further questions.

**Comment by tnrich** [comment]
Thanks @jennifer-shehane much appreciated!
