### ISSUE TITLE
CI builds fail with "process '/usr/bin/yarn' failed with exit code 5"

### ISSUE THREAD

**Issue by swatisharma03** [cypress-io/cypress#3978]
### Current behavior:

![image](https://user-images.githubusercontent.com/19341405/56240995-5017b480-60c7-11e9-8a2b-7e6b104e454c.png)

### Desired behavior:

Test runs fine on local machine using cypress run and create a junit report as I am using the junit reporter.
```json
 "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "./results/test-output.xml",
    "toConsole": true
  }
```
But the same fails when I run it through vsts.

### Versions

Cypress:  3.2.0                                                            │
  │ Browser:  Electron 59 (headless)                                           │
  │ Specs:    8 found (Auth/LoginPage.spec.js, Global/NavigationPanel.spec.js… │
  │ Params:   Group: false, Parallel: false                           

Could you please help?

**Comment by jennifer-shehane** [comment]
The exit code emitted by Cypress is the number of tests failed. Your project had 5 failing tests, so it is exiting with a status of 5. This is the correct behavior and likely you have some tests failing in CI that do not fail locally.

Is there another problem with the test run? Is the report generated ok?
