### ISSUE TITLE
Unable to test multiple domains even with chromeWebSecurity disabled and --disable-site-isolation-trials

### ISSUE THREAD

**Issue by nicholasmaddren** [cypress-io/cypress#3985]
In my test I need to visit two domains, one to authenticate via AWS Cognito and another domain visit to the actual application.

This was working fine yesterday however when I booted up my tests today I get the following error:

```
CypressError: cy.visit() failed because you are attempting to visit a second unique domain.

You may only visit a single unique domain per test.

Different subdomains are okay, but unique domains are not.

The previous domain you visited was: 'https://www.example1.com'

You're attempting to visit this new domain: 'https://www.example2.com'

You may need to restructure some of your code to prevent this from happening.

https://on.cypress.io/cannot-visit-second-unique-domain

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'Actions'
```

I have added `"chromeWebSecurity": false` to my `cypress.json` file and added the following snippet to my plugins file:

```js
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  on('before:browser:launch', (browser = {}, args) => {
    // console.log(browser, args); // see what all is in here!

    // browser will look something like this
    // {
    //   name: 'chrome',
    //   displayName: 'Chrome',
    //   version: '63.0.3239.108',
    //   path: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    //   majorVersion: '63'
    // }

    // args are different based on the browser
    // sometimes an array, sometimes an object

    if (browser.name === 'chrome') {
      args.push('--disable-site-isolation-trials')

      // whatever you return here becomes the new args
      return args
    }
  })
}
```

To recreate this error try to visit multiple domains within your Cypress test whilst using `"chromeWebSecurity": false` and `--disable-site-isolation-trials`.

### Versions

Cypress 3.2.0, OSX, Chrome 63

**Comment by jennifer-shehane** [comment]
Cypress already passes the `--disable-site-isolation-trials` flag through here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.coffee#L53 so this should be unnecessary in your plugins file.

Could you provide the test code you are running where you are visiting the 2 domains?

**Comment by nicholasmaddren** [comment]
@jennifer-shehane Thanks for letting me know, I'll remove that from my plugins file.

Here is an example of my test:
```
describe('A cross origin test', () => {
  it('Should be able to visit cross origin domains', () => {
    cy.visit('https://www.example1.com');
    cy.visit('https://www.example2.com');
    // Check the Logo is on the page
    cy.get('#logo').should('be', true);
  });
});
```

**Comment by nicholasmaddren** [comment]
I didn't see this part of the documentation:

> 
One thing you may notice though is that Cypress still enforces visiting a single superdomain with cy.visit(), but there is an issue open to change this restriction.

I'm sure it was working the other day but maybe I was wrong.

**Comment by jennifer-shehane** [comment]
Yeah, visiting multiple domains in the same test is not supported.

**Comment by Begoodpapa** [comment]
> Yeah, visiting multiple domains in the same test is not supported.
@jennifer-shehane Do you have any plan to support it in the future? 

We have similar test scenario which verifies our business flow by covering UIs come from different superdomains. We call them end to end integration. We are not verifying the feature for those 3rd party product, but we want to see our business flow can go through all of them.

I have tried with below workarounds but none of them worked for me:
1) Set chromeWebSecurity to false in cypress.json
2) Downgrade chrome version to 65, 66
3) Try with Electron or Chromium
4) Add the --disable-site-isolation-trials argument

**Comment by kellyprankin** [comment]
This is a major problem for a lot of people. Shouldn't need to learn how to fake out your auth system to do something you could write a test for in a matter of minutes.

**Comment by jennifer-shehane** [comment]
I'd refer to this issue for all conversation on visiting multiple domains. https://github.com/cypress-io/cypress/issues/944
