### ISSUE TITLE
cy.server options not documented and not available in typescript definition file

### ISSUE THREAD

**Issue by cm0s** [cypress-io/cypress#3992]
### Current behavior:
`cy.server` command has a really useful option `onAnyRequest`. Which is really practical to inject headers or do other stuff.

Here is blog post describing how it can be used : https://medium.com/agilix/cypress-testing-include-custom-http-header-on-each-http-request-2b3693813e97

This option and apparently a few other ones are not documented and are also not available in the Typescript definition (`cli/types/index.d.ts`) (so cannot be used when using Typescript).

### Desired behavior:

Having at least the Typescript definition updated, and if possible a line in the documentation about this option.

### Steps to reproduce: (app code and test code)
```js
 cy.server({
      onAnyRequest: function (route, proxy) {
         //...
      }
  });
```

This will not work when using typescript, it works with js.

### Versions
Cypress 3.2.0

**Comment by jennifer-shehane** [comment]
We've added this as well as `onAnyAbort` and `onAnyResponse` to our documentation in this PR - https://github.com/cypress-io/cypress-documentation/pull/1652

The TypeScript defs still are in progress of being written here: https://github.com/cypress-io/cypress/pull/4109
