### ISSUE TITLE
.type() not consistently typing text until the end

### ISSUE THREAD

**Issue by Floriferous** [cypress-io/cypress#3999]
This is the same issue as #2973, but after removing autofocus it still fails.

Here are a couple clips to illustrate the issue, I'm unable to reproduce it otherwise, since it never happens locally, only on our CI.

![Cypress-bug](https://user-images.githubusercontent.com/10428082/56380607-ee646100-6212-11e9-81e3-235f1adebf14.gif)

Cypress shouldn't be able to continue if it hasn't typed what it is supposed to right?

**Comment by jennifer-shehane** [comment]
@Floriferous Could you provide the test code of what this gif is running? Thanks!

**Comment by bahmutov** [comment]
@Floriferous can it be the same case https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/ ?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
