### ISSUE TITLE
When doing 2 requests to the same cy.route alias, 2nd request isn't waited on

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#4]
```js
cy.route(/accounts/, {}).as("accountsGet")

cy.get("input")
  .type("Spring").wait("@accountsGet")
  .clear().type("Spring2").wait("@accountsGet")
```
The first `.type` causes an XHR (which we explicitly wait for)
Then the 2nd `.type` causes a 2nd XHR (which we also explicitly wait for)
The problem is that the 2nd XHR request is not waited on because Cypress waits for the 1st, which has already resolved.

**Comment by brian-mann** [comment]
Fixed in [`0.5.9`](https://github.com/cypress-io/cypress/wiki/Changelog#059-04262015).
