### ISSUE TITLE
exist and visible options are not displaying in command log when implicit assertion passes

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#40]
When I pass the options exist or length to a DOM traversal, they do not print in the command log when the implicit assertion passes.

**Example Code**
```coffee
it"displays options", ->
  cy.get(".answers-list tr", exist: true)
  cy.get(".answers-list tr", visible: true)
  cy.get(".answers-list tr", length: 55)
```

**Example Command Log**
![screen shot 2015-05-20 at 10 57 29 am](https://cloud.githubusercontent.com/assets/1271364/7728825/580e8ef0-fedf-11e4-9fd5-ff49c250da6f.png)

**Comment by brian-mann** [comment]
Fixed in [`0.6.2`](https://github.com/cypress-io/cypress/wiki/Changelog#062-05202015).  Note the `{exist: true}` would not log out since that is the default option. Only the `length` key was buggy and not logging out.
