### ISSUE TITLE
wait() - doesn't recognize route when used string like that : -my-

### ISSUE THREAD

**Issue by niedarek** [cypress-io/cypress#4004]
I use route:
```js
cy.route({ method: 'GET', url:  '/api/v1/people/-me-/favorites**'}).as('getFavoritesResults');
    cy.wait('@getFavoritesResults').then(xhr => {
      assert.isNotNull(xhr.response.body, 'getFavoritesResults API call has data');
 });
```
### Current behavior:

```
CypressError: Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'getFavoritesResults'. No request ever occurred.
```

### Desired behavior:

process results from xhr

### Steps to reproduce: (app code and test code)

use route with phrase "-my-"

when i use shortened route like that: 
`/api/v1/people/**`
wait() works ok

### Versions
"cypress": "^3.2.0",
linux xbuntu 16
Chrome 73

**Comment by jennifer-shehane** [comment]
Can you provide the part of the url you are attempting to match against please?

**Comment by niedarek** [comment]
this is full url :

http://localhost:8080/api/v1/people/-me-/favorites?where=(EXISTS(target/file)%20OR%20EXISTS(target/folder))

**Comment by jennifer-shehane** [comment]
Can you try `api/v1/people/-me-/favorites**/**`? I think minimatch is reading the `/` in `target/file` portion as another path separator which means you need to specify for it to match all directories.

**Comment by jennifer-shehane** [comment]
@niedarek Any update?

**Comment by niedarek** [comment]
Hello, sorry for delay, but i've just started my holiday and I cant check
out your suggestion.



pon., 22 kwi 2019 o 17:51 Jennifer Shehane <notifications@github.com>
napisał(a):

**Comment by niedarek** [comment]
Your suggestion is correct, it's works now.
Thanks :)
