### ISSUE TITLE
Cypress.js environment variables don't work on CircleCI

### ISSUE THREAD

**Issue by jordancalder** [cypress-io/cypress#4007]
### Current behavior:

In CircleCI, I have environment variables prefixed with `CYPRESS_` (ie, `CYPRESS_TEST_URL=http://testurl.com`). In my tests, any reference to that variable (`Cypress.env('TEST_URL')`), returns the corresponding value _locally_, but returns the environment variable name (not value) in CI.

So this:
```js
Cypress.Commands.add('stagingLogin', () => {
    cy.visit(Cypress.env('TEST_URL'));
});
```
yields the error:
```
CypressError: cy.visit() failed trying to load:

CYPRESS_TEST_URL

We failed looking for this file at the path:

/root/app/CYPRESS_TEST_URL

The internal Cypress web server responded with:

> 404: Not Found
```

### Desired behavior:

`Cypress.env('TEST_URL')` should yield the _value_ (`http://testurl.com`) and not the _name_ (`CYPRESS_TEST_URL`).

### Steps to reproduce: (app code and test code)

- install cypress 3.1.5
- Set environment variable `CYPRESS_TEST_URL` on CircleCI.
- run following test on CircleCI

```js
describe('Env vars', () => {
  it('has correct env vars', () => {
    expect(Cypress.env('TEST_URL')).to.equal('...your value...');
  })
})
```

### Versions

- cypress v3.1.5
- macos v10.4
- chrome v73.0

**Comment by jennifer-shehane** [comment]
I was unable to recreate this behavior on 3.2.0. My test:

```js
it('Get Circle environment variables', () => {
  cy.visit(Cypress.env('TEST_URL'))
  cy.url().should('eq', 'https://example.cypress.io').then(() => {
    expect(Cypress.env('test_url')).to.eq('https://example.cypress.io')
  })
})
```

CircleCI Env var:

![Screen Shot 2019-04-22 at 2 22 30 PM](https://user-images.githubusercontent.com/1271364/56490111-194bff00-650a-11e9-9ce7-7979767e45cb.png)

Also, take note that Circle builds spawned from forked PRs will not have access to environment variables if you have **Pass secrets to builds from forked pull requests** set to false (which is the default).
