### ISSUE TITLE
DOM snapshot inspection mode does not reset when reloading file on change

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4008]
It is very hard to reproduce this bug, but I have seen it a couple of times

v3.2.0 on Mac

- have a test
- when it finishes hover over a test command that changes the DOM to get "before and after" DOM snapshot animation
- while the animation is going, change the spec, causing to test to reload and restart (I was using it.only in this case)
- notice in the video below how the test runner did not clear the DOM snapshot animation, and eventually failed because the DOM never updated with the new contents

![test-does-not-reset-dom-snapshot](https://user-images.githubusercontent.com/2212006/56462037-3b1e7800-638a-11e9-83f6-4b46396cc662.gif)

**Comment by jennifer-shehane** [comment]
Looks like duplicate of https://github.com/cypress-io/cypress/issues/2796 Reopen if you think it's diff.
