### ISSUE TITLE
Unable to install Cypress in my company machine .npm install cypress fails.

### ISSUE THREAD

**Issue by shaanmishra87** [cypress-io/cypress#4010]
While I try to run `npm install` in my office machine it fails.

its throwing me an error as 

```
Cypress can't be downloaded please check network connectivity.
```

Can anyone help me resolve this issue

Company machine info--

Windows 7 32 bit
Cypress version -1.4.2

**Comment by jennifer-shehane** [comment]
Check your network connectivity and also if you are behind a corporate proxy - check [this thread](https://github.com/cypress-io/cypress/issues/1469) for workarounds. A release to handle this is soon to be released.
