### ISSUE TITLE
expect().to.be.ordered.members() throw an error "TypeError: Cannot read property 'members' of undefined"

### ISSUE THREAD

**Issue by Bigdragon13th** [cypress-io/cypress#4017]
### Current behavior:

Whenever I try to compare array (order matters) with the command `expect(...).to.be.ordered.members(...)`, Cypress always throw an error.

`expect(...).ordered(...)` as shown here also failed.
https://docs.cypress.io/guides/references/assertions.html#BDD-Assertions 

### Desired behavior:

It should works.

### Steps to reproduce: (app code and test code)

This code failed.
```
describe("First Test", () => {
    it.only("This will failed", () => {
        expect([0, 1]).to.be.ordered.members([0, 1]);
    });
});
```

### Versions

Cypress version: 3.2.0

**Comment by jennifer-shehane** [comment]
The `ordered` flag [was added in `chai` version 4.x.x](https://github.com/chaijs/chai/issues/781). Cypress is currently using chai version 3.5.0. Upgrading to 4.0 is part of our [Cypress 4.0 release](https://github.com/cypress-io/cypress/issues/2840), so will be supported when that is released.

**Comment by Bigdragon13th** [comment]
Yeah, I'm aware of the duplicated old issue, thought it got fixed already because it was closed, guess I was wrong.

**Comment by jennifer-shehane** [comment]
Issues are closed when the PR has been merged into develop, but not necessarily released. These issues have a `pending release` tag and a comment in the issue noting this.

**Comment by Bigdragon13th** [comment]
I didn't see any `pending release` tag or comments in your given issues, where should I look for to see when the feature will possibly be released?

**Comment by jennifer-shehane** [comment]
@Bigdragon13th 😅This is true. We've automated the process of tagging and commenting recently, so more recently closed issues should do this. Looks like we overlooked this one.

**Comment by westhomas** [comment]
@jennifer-shehane `ordered` is shown in the docs here: https://docs.cypress.io/guides/references/assertions.html#Chai

I'm guessing that's automatic. But it's also confusing :-(

**Comment by Neurrone** [comment]
Hi, can we please have this misleading entry removed from the docs until 4.0 is released? Wasted an hour trying to figure out what was going on until stumbling upon this issue.

**Comment by Dan503** [comment]
FYI, if you are looking for a work around solution, I managed to get the test working by doing this instead:

```js
it("test array matches (order matters)", () => {
    expect([0, 1]).to.deep.equal([0, 1]);
});
```

I was testing that a regular expression was returning the expected result values. I needed to destructure the result for that to work.

```js
it('a b test', () => {
	expect([.../(a)(b)/.exec('ab')]).to.deep.equal(['ab', 'a', 'b'])
})
```

**Comment by jennifer-shehane** [comment]
I've confirmed this is working in upcoming 4.0 release. The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

## 3.8.3

<img width="434" alt="Screen Shot 2020-01-29 at 3 49 42 PM" src="https://user-images.githubusercontent.com/1271364/73343449-10fdcd00-42af-11ea-9310-9d1facbad7f5.png">


## 4.0.0

<img width="450" alt="Screen Shot 2020-01-29 at 3 49 49 PM" src="https://user-images.githubusercontent.com/1271364/73343461-13f8bd80-42af-11ea-8d08-4e541dde4efe.png">
