### ISSUE TITLE
Use only the publix suffix registry when parsing URL's

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#402]
Currently Cypress uses the https://publicsuffix.org/learn list when parsing URL's, but it incorrectly calculates the `private suffix registry` which can lead to incorrect results.

Related to #380

**Comment by yangliurea** [comment]
Is there any possibility I can skip the cross origin error when I call cy.visit()?

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).
