### ISSUE TITLE
Error: spawn Xvfb EACCES issue while running via Jenkins

### ISSUE THREAD

**Issue by harithah** [cypress-io/cypress#4020]
I am facing an issue in Jenkins with Cypress version 3.1.5 as well as in 3.2.0. I tried reinstalling as well as running cypress cache clear. This is the error I get:

```
/node_modules/.bin/cypress verify
It looks like this is your first time using Cypress: 3.1.5

�[?25l[11:43:21] Verifying Cypress can run /home/jenkins/.cache/Cypress/3.1.5/Cypress [started]
�[?25hevents.js:167
throw er; // Unhandled 'error' event
^

Error: spawn Xvfb EACCES
at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
at onErrorNT (internal/child_process.js:406:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

Kindly help me with a solution to fix this issue..

I tried doing a cypress cache clear...setting permissions `chmod -R u+x` to `/next-tick` and to `/electron-chromium` as well as for `/node_modules/.bin/cypress`

**Comment by jennifer-shehane** [comment]
Thanks. Previous response: https://github.com/cypress-io/cypress/issues/1888#issuecomment-486063557

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
