### ISSUE TITLE
Strongly typing the invoke function

### ISSUE THREAD

**Issue by Floydjd** [cypress-io/cypress#4022]
### Current behavior:

`invoke` function is not strongly typed.

### Desired behavior:

`invoke` function is strongly typed.

TypeScript has a `ReturnType` type that you can use

```ts
invoke<K extends keyof Subject>(functionName: K, ...args: any[]): Chainable<ReturnType<Subject[K]>>
```

**Comment by flotwig** [comment]
Hey, thanks for pointing this out!

The types definition file that needs to be updated is here: https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts

If you'd like to, you can open a pull request with the changes that you think are necessary.

**Comment by bahmutov** [comment]
Reverted initial work in https://github.com/cypress-io/cypress/commit/6930cabd7bbad52be44212914ffac7a738ec7a78 - we need to handle the case

```js
cy.get('.trigger-input-range')
  .invoke('val', 25)
```

**Comment by dmtrKovalenko** [comment]
The problem is inside function overloading. Typescript takes only the first function declaration parameters. Related issues in typescript repo:
https://github.com/microsoft/TypeScript/issues/29732
https://github.com/microsoft/TypeScript/issues/32164

**Comment by gabbersepp** [comment]
I understand that this is not the best solution as overloads won't work as expected.
But they won't work currently neither.

With this fix the typings ovf `invoke` will be correct in most of the cases.

An example I stumbled across today:

```js
        it.only("asd", () => {
            cy.wrap({ fn: () => ({a: 1})})
            .invoke("fn")
            .its("a")
            .should('eq', 1);
        })
```

![image](https://user-images.githubusercontent.com/3234900/70331687-3edf0c00-1840-11ea-9244-2d207839bca1.png)

So I wanted to know if there are any plans to merge this PR again?

**Comment by CypressJoseph** [comment]
I think this is basically done as of https://github.com/cypress-io/cypress/pull/6667 (I will look again but I think we tackled most of these forms there.)
