### ISSUE TITLE
Support creating custom assertion operator like 'should('have.text.trimmed', ...)'

### ISSUE THREAD

**Issue by freewind** [cypress-io/cypress#4026]
Cypress have many assertion operators like 'eq', 'contain', 'have.text', but which is not enough for me.

E.g. I want to check a DOM element have some text but want to skip around whitespaces, I have to write:

```js
cy.get('.cell')
  .then($cell => $cell.text().trim())
  .should('eq', 'Hello')
```

Since none of `have.text`, `eq`, `contain` really work in this case.

I want to define a custom operator like `have.text.trimmed`, to simplify the code to:

```js
cy.get('.cell')
  .should('have.text.trimmed', 'Hello')
```

I can't find any document about it, does Cypress have a way to do it? Or add this feature?

PS: I also create a question before this issue: https://stackoverflow.com/questions/55842707/how-to-define-a-custom-assertion-operator-in-cypress/55842986

**Comment by jevors** [comment]
I would love that too. As I mentioned on stackoverflow it is possible to combine a .contains() with a regular expression. But it would still be a welcome add-on to use regular expressions inside .should()

**Comment by jennifer-shehane** [comment]
Related issues - closing as duplicate
- should('have.text', ...) should ignore leading and trailing whitespace 
 https://github.com/cypress-io/cypress/issues/3887
- Have .contains() strip new lines of targets. https://github.com/cypress-io/cypress/issues/92
- Provide a "Cypress" way to access textContent (and/or innerText) - .text() command https://github.com/cypress-io/cypress/issues/630

**Comment by freewind** [comment]
@jennifer-shehane not quite duplicate I think. Trimmed text before checking is just an example here, I care more is the ability to create custom operators

**Comment by bahmutov** [comment]
take a look at https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/extending-cypress__chai-assertions - this is how to add new Chair assertions to the existing ones

We could make it simpler I guess by adding something similar to custom commands

```
Cypress.Assertions.add('...', )
```

**Comment by jennifer-shehane** [comment]
Ok, that is a broader request. 

We use chai for our assertions and this is also extensible with [chai plugins](https://www.chaijs.com/plugins/) via these instructions:. https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/extending-cypress__chai-assertions

So, I believe creating a chai plugin (or using one of the many existing ones) and including it into cypress may do the trick. 

Does this satisfy the assertion extension you were looking for?

**Comment by jennifer-shehane** [comment]
@bahmutov beat me 🙃

**Comment by bahmutov** [comment]
Time zone difference 😛

**Comment by freewind** [comment]
@jennifer-shehane Thanks for the links and I managed to create it by extending chai. I've explained the code on stackoverflow, anyone interested in may see it there: https://stackoverflow.com/a/55854585/342235

**Comment by jennifer-shehane** [comment]
@freewind Awesome, and great question. I will close this issue as resolved.

**Comment by robmint** [comment]
See https://github.com/Lakitna/cypress-commands for a solution
