### ISSUE TITLE
Multiple projectIDs for multiple environments

### ISSUE THREAD

**Issue by praneetha-ck-robo** [cypress-io/cypress#4028]
### Current behavior:

`projectId` in `cypress.json` is not being overridden by `development.json`. 

### Desired behavior:

I would want to have different project ID's for different environments. Hence, I assumed https://on.cypress.io/configuration-api#Usage according to this, I would expect that the `projectId` in `development.json` would override the `projectId` in `cypress.json`. 

### Steps to reproduce: (app code and test code)
```
cypress run --record --key `<record-key>`
```

**Comment by jennifer-shehane** [comment]
ProjectIds are meant to identify a single project, as the name indicates. ProjectIds are automatically generated per project and are read only. You cannot overwrite the projectId. 

If you can, we'd like to know why you want a separate ProjectID per environment within the same project. We may be able to help you achieve the result you're looking for in another way.

**Comment by praneetha-ck-robo** [comment]
For my local developmental purposes, I'd like to have a separate project where I can view my tests in the dashboard. I also have a projectID created for an organization and I do not want to pollute my dashboard created for the organization with tests that I run locally.

**Comment by praneetha-ck-robo** [comment]
Hi @jennifer-shehane Is there any solution for my use-case?

**Comment by jennifer-shehane** [comment]
No. There is not a way to do this currently with Cypress. I'd suggest looking into grouping as possibly a way to organize some of the run data. https://on.cypress.io/parallelization#Grouping-test-runs

We don't intend to support multiple projectIds per project, so we will be closing this issue.

**Comment by aheward** [comment]
Grouping will be a workable solution as soon as you guys start beefing up the features and customizability of your dashboard UI offering. Until then, it's disappointing that we can't use multiple project IDs in the same codebase.

**Comment by bahmutov** [comment]
I believe when this PR https://github.com/cypress-io/cypress/pull/3246 lands you will be able to override project ID and every other config setting as desired.

**Comment by jennifer-shehane** [comment]
Also, this issue may be a relevant feature for you all looking here https://github.com/cypress-io/cypress/issues/2561

**Comment by borecz** [comment]
Any updated on this?

We have a repo with test for mobile and desktop and we need to have them splitted in dashboard. It seems a pretty reasonable use case.

**Comment by bahmutov** [comment]
Could use use separate config files for different environments?
