### ISSUE TITLE
Cannot insert special characters "/" and ":" in text input fields using type()

### ISSUE THREAD

**Issue by Ravinderkaur04** [cypress-io/cypress#4030]
### Current behavior:
The application I'm testing currently has a input field of `type=text` to enter date and time for eg: `2019/04/25 14:21`

I use the `cy.type()` command to insert the values here but this does not type `/` and `:`

Code looks something like this:

```js
dateTime = year+"/"+month+"/"+date+" "+hours+":"+minutes

cy.get(input).type(dateTime)
```

It only types `20190425 1421` omitting the slashes and semi-colons

### Desired behavior:

`cy.type()` also types special characters slashes and semi-colons

### Steps to reproduce: (app code and test code)

```js
cy.get(input).type("//:")
```

Cypress executes the command typing nothing in the input field and  does not complain or produce any error

### Versions

3.1.0. 

I cannot use the latest version and had to downgrade to this version due to another issue https://github.com/cypress-io/cypress/issues/1321

**Comment by jevors** [comment]
The documentation suggests is should work (https://docs.cypress.io/api/commands/type.html#Input-Textarea) but also in 3.2.0 it is broken. The code below only enters the -'. characters:
`.type("~`!@#$%^&*()-_=+[]}{|\\\"':;/?.>,<")`

**Comment by jevors** [comment]
> The documentation suggests is should work (https://docs.cypress.io/api/commands/type.html#Input-Textarea) but also in 3.2.0 it is broken. The code below only enters the -'. characters:
> .type("~\`!@#$%^&*()-_=+[]}{|\"':;/?.>,<")

**Comment by jennifer-shehane** [comment]
I'm not experiencing the same behavior as either of you are describing. Using 3.2.0, the following test passes. I also tried running this on several Chrome versions. 

```js
it('type into a input', () => {
  cy.visit('https://example.cypress.io/commands/actions')
  cy.get('#fullName1')
    .type('~`!@#$%^&*()-_=+[]}{|\\\'":;/?.>,<')
    .should('have.value', '~`!@#$%^&*()-_=+[]}{|\\\'":;/?.>,<')
})
```

Can either of y'all provide some example test code that can be run that fails to type the characters above within a `type='text'` input?

**Comment by Ravinderkaur04** [comment]
The above example I provided is the exactly what does not work. As I said Cypress does not throw any error and continues with the next steps. But when I check the field it only has numbers from the date and not the special characters. The example once again
```js
dateTime = year+"/"+month+"/"+date+" "+hours+":"+minutes

cy.get(input).type(dateTime)
```
The application I'm testing is JSF and this particular input field is of `type='text'`

**Comment by jennifer-shehane** [comment]
@Ravinderkaur04 Yeah, the only thing I can think is that there may be some custom logic like a `validate` or something that is stripping those characters on type. Creating an `index.html` with a simple `input` with `type='text'` allows typing of these characters. 

Is there any more logic on this input? Or a publicly available input of this type that we could test the typing on?

**Comment by Ravinderkaur04** [comment]
@jennifer-shehane thank you for the response. This input field was indeed not the usual html input component but a JSF input component that has a JSF lifecycle attached and sends AJAX requests on every event triggered. Therefore the value is always packed in the "value" attribute of the element and not plain text. What worked for me was to do the following

```js 
 dateTime = year+"/"+month+"/"+date+" "+hours+":"+minutes
 cy.get('iframe')
    .iframe()
    .find('input)
    .then(function($input){
                $input[0].setAttribute('value', dateTime)
            })
     .should('have.value', dateTime)
```
All the elements that the test interacts with sit inside an iframe, therefore you see a call to my custom iframe command

**Comment by jennifer-shehane** [comment]
Thanks for the update @Ravinderkaur04!
