### ISSUE TITLE
Cypress crashed when i download (Command Line)

### ISSUE THREAD

**Issue by clferrarin** [cypress-io/cypress#4032]
Hi all,
I'm a new user of cypress and i need help in order to help me in my job
So, the execution of cypress in my ubuntu bash crashed when the code arrive at a download part (on elecrtron)
However, when i launch my spec with the desktop app cypress and that open me chrome. The downloading seems to be ok but after the downloading the web page crashs.
Any idea ?

Here is the example : 

```js
it("has successfully download datas of the current widget",function(){
		cy.get('.ic-arrows')
			.click({force:true}) //Start the download
})
```
//Crash

**Comment by clferrarin** [comment]
Hi all,
I'm a new user of cypress and i need help in order to help me in my job
So, the execution of cypress in my ubuntu bash crashed when the code arrive at a download part (on elecrtron) 
However, when i launch my spec with the desktop app cypress and that open me chrome. The downloading seems to be ok but after the downloading the web page crashs.
Any idea ?

**Comment by jennifer-shehane** [comment]
What is clicking the button in your application supposed to do. Download a file?

I haven’t seen the application crash in this situation. There is an open issue about handling a download prompt here https://github.com/cypress-io/cypress/issues/433

Can you provide the logs during `cypress run` and also enable DEBUG logs as described here: https://on.cypress.io/debugging#Print-DEBUG-logs

**Comment by clferrarin** [comment]
> 
> 
> What is clicking the button in your application supposed to do. Download a file?
> 
> I haven’t seen the application crash in this situation. There is an open issue about handling a download prompt here #433
> 
> Can you provide the logs during `cypress run` and also enable DEBUG logs as described here: https://on.cypress.io/debugging#Print-DEBUG-logs

**Comment by clferrarin** [comment]
Yes exactly just download a file without popup or anything.

It's not really cypress that is crashing but chrome or electron due to cypress the error of the navigator is like : "An error has occured"

**Comment by jennifer-shehane** [comment]
Can you provide the logs during cypress run and also enable DEBUG logs as described here: on.cypress.io/debugging#Print-DEBUG-logs

Any screenshots or videos would be helpful as well. Ideally, providing a reproducible example we can run would be the most helpful - as we cannot begin work on an issue without being able to reproduce it on our machines.

**Comment by clferrarin** [comment]
It seems to be ok. I just optimize my code and the navigator doesn't crash anymore.

Just an other question, is it possible with Cypress to check if the downloading has happenned in back-end ?
Nearly like the should('have.value',value)
