### ISSUE TITLE
Cypress rest runner stops execution after competing steps within an iFrame

### ISSUE THREAD

**Issue by nkrishna79** [cypress-io/cypress#4035]
### Current behavior:
I have a payment gateway which injects the payment method via an iframe. Though I was successful in completing my card details within the iframe - when I click complete which does a post to server the test runner stops abruptly. 

### Desired behavior:

I would like to be able to continue on with my steps upon competing the payment via iFrame. 

### Steps to reproduce:
I can send you snippets of my code if needed. 

### Versions

Cypress - 3.2.0
OS - Windows 10
Browser - Chrome latest

**Comment by jennifer-shehane** [comment]
Yes we will need a completely reproducible example to be provided in order to investigate this issue.

**Comment by nkrishna79** [comment]
@jennifer-shehane Okay i will send something out over the weekend. However, in the meantime if you want more info - this issue  is similar to the one mentioned here - https://stackoverflow.com/questions/55625872/cypress-test-stops-to-execute-in-the-middle-of-code 
And you can see the screenshot in second link in the above post.

**Comment by nkrishna79** [comment]
@jennifer-shehane I think I have done a work around for this issue to complete my journey cycle by chaining certain actions upon completing things in iframe. It does work when doing that way. So i am happy to close this ticket for now. 
Thanks
krish
