### ISSUE TITLE
Cypress version property in the browser

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#404]
It would be nice to have the current Cypress version property available inside the text, since we have so many releases. Something like read only `Cypress.version` equal to "0.18.6" for example would do

**Comment by jennifer-mann** [comment]
You mean in the actual Cypress runner? Like in the header somewhere below in the photo?

<img width="587" alt="screen shot 2017-01-31 at 12 32 52 pm" src="https://cloud.githubusercontent.com/assets/1271364/22476722/6b117c26-e7b1-11e6-86b0-eef98ef3a589.png">

Curious why you need this in the browser. Is it for reviewing screenshots taken during a test run?

**Comment by brian-mann** [comment]
He just wants it as a property like

```javascript
Cypress.version // 0.18.7
```

**Comment by bahmutov** [comment]
@brian-mann is right, that's what I need. This would add important info (Cypress version) to our failed test information in https://github.com/bahmutov/cypress-failed-log

**Comment by brian-mann** [comment]
Fixed in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).
