### ISSUE TITLE
`after` hook does not display as expected.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#405]
I expect the `before` hook to display on the first test, and the `after` hook to display on the last test.

As you can see the `after` hook displays on the first test.

However the `after` is actually *executing* in the right place, it is just not displaying with the right test. It's just a visual issue.

```javascript
before(function(){
  cy.log("BEFORE")
  console.log("BEFORE")
})

after(function(){
  cy.log("AFTER")
  console.log("AFTER")
})

it('title', function(){
  cy.log("TEST 1")
  console.log("TEST 1")
})

it('title again', function(){
  cy.log("TEST 2")
  console.log("TEST 2")
})

it('title again again', function(){
  cy.log("TEST 3")
  console.log("TEST 3")
})
```

![](https://files.gitter.im/cypress-io/cypress/W47c/Screen-Shot-2017-01-27-at-2.44.12-PM.png)

![screen shot 2017-01-31 at 12 53 56 pm](https://cloud.githubusercontent.com/assets/1271364/22477518/69e4128e-e7b4-11e6-9e4d-4c7f3945427b.png)

**Comment by msharma1312** [comment]
as per some example in macha, 'done' is used . Is it something that could help here ?

**Comment by brian-mann** [comment]
No, there's not actually anything wrong. Cypress / mocha is executing things in the right order - Cypress is just associating the command with the wrong test. It's a purely visual issue.

**Comment by msharma1312** [comment]
Ok, So you mean there will be no fix?
so  the situation where the After() is running soon after Before() without BeforeEach () is just in my test ?

**Comment by brian-mann** [comment]
What we're saying is that we would need a reproducible repo / test code that displays the problem. Because to date, we cannot find anything wrong with the way that Mocha / Cypress runs hooks. There is nothing to fix other than the visual association of commands to tests, which should not affect what you're describing.

**Comment by msharma1312** [comment]
ok,Thanks!
What I observed was , it does not work with nested describe. But if all the before() and after() are under one describe with 'it' it works fine.
Thats how I'm using it for now.

**Comment by brian-mann** [comment]
If you still think there is a problem you'll need to post some code that is reproducible.

Remove everything other than `console.log` statements so we can immediately check the execution order to ensure it works correctly.

Cypress is built on top of mocha and if you think there is an issue with hooks you can also check their repo for open issues / bugs.

**Comment by jennifer-shehane** [comment]
@herobix seems to have pasted some code that claims to reproduce this in #1206

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/issues/2663
