### ISSUE TITLE
Add cy.trigger()

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#406]
Create a `cy.trigger()` command that makes it easy to trigger an event on a dom element. This will help to simulate actions such as [drag-n-drop](https://github.com/cypress-io/cypress/issues/386), [hover](https://github.com/cypress-io/cypress/issues/10), and [input range interaction](https://github.com/cypress-io/cypress/issues/287). 

`cy.trigger()` will take care of setting coordinates and sensible default properties such as `cancelable` and `bubbles`, allowing those properties to be overridden by the caller if needed.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
