### ISSUE TITLE
Cypress commands (e.g. cy.get) return undefined if previous test step fails

### ISSUE THREAD

**Issue by mk-klara** [cypress-io/cypress#4062]
### Current behavior:

Cypress test runner fails in `after()` block with error:

```
CypressError: cy.first() failed because it requires a DOM element.

The subject received was:

  > undefined

The previous command that ran was:

  > cy.get()

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite:
```

This happens each time a test step fails. In this case, it happens when the following assertion fails 
```js
.get('div.header__dob').should('contain', `${patient.birth_date}`)
```

### Desired behavior:

Cleanup step should execute with Cypress commands returning values instead of `undefined`

### Steps to reproduce: (app code and test code)

1. Write test with `before`, `test` & `after` steps
2. Have an assertion fail during testing
3. `cy.get` should return `undefined` in `after` step

### Versions

Cypress: 3.2.0
OS: MacOS 10.14.4
Browser: Electron59 & Chrome73

**Comment by jennifer-shehane** [comment]
Can you provide the portion of your test code that uses the `.first()` command since this is what is printed in the error message? 

The error is being thrown when using the `.first()` command, but it may be displaying in the Command Log at a different point, making this confusing to track down.

**Comment by kayonaise** [comment]
The section of code that fails is 
```
cy.url().should('contain', 'patients')
    .url().should('contain', 'edit')
    .get('h2').first().should('contain', 'Personal information')
```

The same function is called during an earlier stage in the test and all assertions pass. It is only after the code (pasted in first message) fails that this failure is thrown.

**Comment by jennifer-shehane** [comment]
This looks related to this issue: https://github.com/cypress-io/cypress/issues/2199 Which we were never able to reproduce. 

Does this happen during `cypress open`, `cypress run`, both? 

Just want to clarify that I understand the structure first and I will try to recreate. The code looks something like this?

```js
context('My tests', () => {
  beforeEach(() => {
    cy.visit('/')
  })

  after(() => {
    cy.url().should('contain', 'patients')
      .url().should('contain', 'edit')
      .get('h2').first().should('contain', 'Personal information')
  })

  it('tests the ui', () => {
    // this test should FAIL
    cy.get('div.header__dob').should('contain', `${patient.birth_date}`)
  })
})
```

**Comment by jennifer-shehane** [comment]
I'm able to reproduce with this code below:

```js
describe('subject of undefined thrown in after', () => {
  after(() => {
    cy.get('h2').first()
  })

  it('.make a test fail', () => {
    cy.visit('https://example.cypress.io/commands/actions')
    cy.get('.action-email').should('have.value', 'fake')
  })
})
```

This error does not throw when the test is in a passing state

```
CypressError: cy.first() failed because it requires a DOM element.

The subject received was:

  > undefined

The previous command that ran was:

  > cy.get()

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: 'subject of undefined thrown...'
```

<img width="493" alt="Screen Shot 2019-05-02 at 12 31 02 PM" src="https://user-images.githubusercontent.com/1271364/57058472-3042dc00-6cd6-11e9-89ac-aaa5228dd076.png">

**Comment by jennifer-shehane** [comment]
I wrote a failing test for this in our code here: https://github.com/cypress-io/cypress/pull/4094

**Comment by kayonaise** [comment]
Thanks! Glad you were able to reproduce the issue. To answer your previous question, it occurs on both `cypress open` & `cypress run`

**Comment by superqd** [comment]
I have run into this issue as well (I'm a cypress n00b).  I worked around it in the `after()` hook by doing something like this:

```javascript
after(() => {
   // if a test fails before "after" is called this works
  const $el= Cypress.$("[data-test='lookup-value']");
  cy.wrap($el).click();
         
  // if a test fails before "after" is called, this fails
  //cy.get("[data-test='lookup-value']").click();  
}
```

**Comment by mmonteiroc** [comment]
Hi !
I'm having the same issue when doing cy.visit() to a new url.

We have a custom command which we use to check if our loading dissappear.

When arriving to that URL I have a method which waits for our loading to dissappear (cy.get(loading).should('not.exist')....

Before doing that, we check that the main element in our DOM exists.... 

The issue comes in that check when in this custom command, we do   cy.get('mainElement', { timeout: 10000 }).should('exist');
We only do that assertion and afterwards assert that the loading does not exists

I get the following:
For some reasons, I cannot show you the ID we use. anyways tried with other ID's / css selectors and same error so that's not an issue
![image](https://user-images.githubusercontent.com/28816737/112134123-ae5f4300-8bcc-11eb-93c3-af6985ba0295.png)

**Comment by Deop** [comment]
Is there any update on this issue? Having the same problem with undefined elements in after methods after test fail

**Comment by ben-arce-hdz** [comment]
any updates on this issue? I am getting undefined when previous test step fails
