### ISSUE TITLE
Fetching a cross origin json url not being detected as XHR request, Not being stubbed

### ISSUE THREAD

**Issue by SanyasiraoM** [cypress-io/cypress#4064]
```js
it('No items', () => {
  cy.server()
  cy.route({
    method: 'GET',
    url: '**/sample-json-files/*',  
    response: []
  })
  cy.visit('/')
 })
```
### Current behavior:

On visiting `/`, We are doing fetch call with url `https://s3.ap-south-1.amazonaws.com/test-media-assets/items/items.json`

But the request is not being detected as XHR request in the cypress chrome window UI and response is not stubbing with `[]`

### Desired behavior:

The request should be detected as XHR and response should be stubbed

### Steps to reproduce: (app code and test code)

do fetch call with any json url whose origin is different with testing website url

### Versions

cypress:3.2.0
operating system: mac
browser: Chrome 74

**Comment by gopal-virtual** [comment]
This is a real scenario in web-apps. I'm stuck on certain test cases. Can someone from the team address this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. I don't doubt that this may be happening, but there is more information involved than just the plain case of it being a different domain - so we need this extra information to reproduce.

We have our own kitchen-sink files listening for a different domains json here: https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/integration/examples/network_requests.spec.js#L98

We're visiting `http://localhost:8080` and have a `cy.route()` listening for requests to `https://jsonplaceholder.cypress.io`

**PLEASE NOTE: FETCH requests are currently not fully supported: https://github.com/cypress-io/cypress/issues/95 https://github.com/cypress-io/cypress/issues/687**

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
