### ISSUE TITLE
Unable to fire event in Vue component on click

### ISSUE THREAD

**Issue by jameseg** [cypress-io/cypress#4065]
### Current behavior:

When clicking an element in a Vue component, the click event attached to that elemnt isn't firing.  It is firing however when manually testing and also using jquery in devtools.

### Desired behavior:

I want the click of the element in Vue component to fire the attached event when using Cypress

### Steps to reproduce: (app code and test code)

app code and test code are both located here:
https://stackoverflow.com/questions/55873981/can-i-trigger-a-file-upload-from-an-element-contained-within-a-vue-component-wit

### Versions

Cypress 3.2.0
WIN 10
Chrome 74

**Comment by jennifer-shehane** [comment]
Uploading files using the filesystem is not currently supported in Cypress. There are several workaround for testing dropzone in this issue: https://github.com/cypress-io/cypress/issues/170

Also see this issue for others workarounds for dropzone uploading: https://github.com/cypress-io/cypress/issues/669
