### ISSUE TITLE
'Can't start server' error when 'baseUrl' set. Can this auto-update when server is started?

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#407]
I don't like having to click "Go Back to Projects" and find my project all over again to click into after starting my server. Can we poll this data and auto-update this screen on change?

<img width="912" alt="screen shot 2017-01-31 at 5 00 29 pm" src="https://cloud.githubusercontent.com/assets/1271364/22486297/e820ade8-e7d6-11e6-8f89-c03243e3987d.png">

**Comment by brian-mann** [comment]
Since we now display `Runs` it may also make sense just to have a button that says like `Continue Anyway`.

That way you can access the other parts and not worry about the error.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
