### ISSUE TITLE
LocalStorage.clear not found

### ISSUE THREAD

**Issue by AbdealiJK** [cypress-io/cypress#4070]
### Current behavior:

As per the docs at https://on.cypress.io/using-cypress-faq#How-do-I-preserve-cookies-localStorage-in-between-my-tests for `LocalStorage` which links to https://github.com/cypress-io/cypress/issues/461#issuecomment-325402086

I am trying to override the `Cypress.LocalStorage.clear`. This gives me a typescript error that Cypress has no property `LocalStorage`.

I have `/// <reference types="cypress" />` and all my other type management is working fine.

### Desired behavior:

Was expecting to be able to override the `LocalStorage.clear` as described in docs to whitelist some keys that should not be cleared.

### Steps to reproduce: (app code and test code)

I'm adding this to my `support/commands.ts`
```ts
const oldCypressLocalStorageClear = Cypress.LocalStorage.clear

Cypress.LocalStorage.clear = function (keys, ls, rs) {
    // do something with the keys here
    cy.debug();
    if (keys) {
        return oldCypressLocalStorageClear.apply(this, arguments)
    }
}
```

### Versions
Mac OSX 10.13.6
cypress: ^3.1.5 (locked at 3.2.0)

**Comment by jennifer-shehane** [comment]
Yeah, since this isn't a publicly documented method in our documentation, there weren't any TypeScript definitions added for it. 

@bahmutov How would you handle something like this?
