### ISSUE TITLE
cy.getCookies() is empty but cookies are set

### ISSUE THREAD

**Issue by cambiph** [cypress-io/cypress#4073]
### Current behavior:
Under `support/index.js`a cookie is set to accept GDPR so a pop-up is not shown.
When I perform fetch the cookies later in a test, the array is empty.

### Desired behavior:
`cy.getCookies()`shows the GDPR-cookie, set under `support/index.js`

### Steps to reproduce: (app code and test code)

`support/index.js`
```javascript
before(function() {
  cy.setCookie("gdpr", "true");
  cy.login('admin', 'admin');
  cy.visit('');
});
```
`spec.js`
```javascript
describe('App', () => {
  it('Cookies are set, () => {
    cy.getCookies().then((cookies) => {
        console.log(cookies);
    })
  });
});
```

Using a standard Spring boot app with Spring security (hence the `login`-function)

### Versions

Cypress: 3.1.3
Node: 11.14.0
Chrome v73
OS: OsX

**Comment by jennifer-shehane** [comment]
Any commands in a `before` hook are run once and only once. Cookies are also automatically reset in between each test (`it`). So, what is effectively happening is you are setting the cookie, test runs, cookies are cleared, test runs, cookies are cleared, etc. 

You likely want to use [`Cypress.Cookies.preserveOnce` to preserve the cookie](https://on.cypress.io/cookies#Preserve-Once) across multiple tests. That or move the set cookie closer to the test case. 

You can follow this larger issue for Cypress to better handle this here: https://github.com/cypress-io/cypress/issues/686
