### ISSUE TITLE
Save SHA256 and file size as meta data when uploading test runner binary to S3

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4083]
We can compute SHA256 checksum of the `cypress.zip` and its filesize on each platform during build before uploading to S3 platform. This information can be saved as S3 object metadata and then later go into the test runner manifest and used to verify / retry ZIP file download.

Example using [hasha](https://github.com/sindresorhus/hasha)

```js
// prints size and hash SHA-256 of the local file
const hasha = require('hasha')
const path = require('path')
const fs = require('fs')
const filename = path.join(__dirname, 'foo.txt')

hasha.fromFile(filename).then(hash => {
  console.log('file: %s', filename)
  console.log('hash: %s', hash)
  console.log('size: %d', fs.statSync(filename).size)
})
/*
file: /Users/gleb/git/training/node/test-hasha/foo.txt
hash: b8bff2ca76607c81e41219cbf31b0d117234e3f94eb539ffd23862c779f6aff0b38798c76506f5a8bdf020e242acb3d8c99cc67c74425fccdad64143d3be5adb
size: 37
*/
```

## related issues

- #3515

**Comment by jennifer-shehane** [comment]
Hey @bahmutov, does this have any valuable deliverable to our users today? Like, is this something to be mentioned in the changelog? Or is there more work to be done first?

**Comment by bahmutov** [comment]
There is still work to make it useful to the user from our CLI
