### ISSUE TITLE
Installing cypress on mac - dyld: Library not loaded

### ISSUE THREAD

**Issue by kevinsimper** [cypress-io/cypress#4089]
I tried to do this but it didn't help
```
rm -rf /Users/srinuk/Library/Caches/Cypress/
```

```
$ ./node_modules/.bin/cypress open
It looks like this is your first time using Cypress: 3.2.0

 ✖  Verifying Cypress can run /Users/kevinsimper/Library/Caches/Cypress/3.2.0/Cypress.app
   → Cypress Version: 3.2.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Users/kevinsimper/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/MacOS/Cypress
Reason: no suitable image found.  Did find:
/Users/kevinsimper/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
/Users/kevinsimper/Library/Caches/Cypress/3.2.0/Cypress.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
----------

Platform: darwin (18.5.0)
Cypress Version: 3.2.0
```

```
$ node -v
v11.6.0
$ npm -v
6.5.0-next.0
$ which node
/Users/kevinsimper/.nvm/versions/node/v11.6.0/bin/node
```

Mojave 10.14.4 (18E226)

**Comment by jennifer-shehane** [comment]
Could you try running `npm clear cache` or `npm cache --force clean` as indicated in this issue: https://github.com/electron/electron/issues/10702

Also, can I ask how did you install Cypress exactly?

**Comment by kevinsimper** [comment]
> Also, can I ask how did you install Cypress exactly?

I installed it by doing `npm install cypress`

**Comment by kevinsimper** [comment]
It worked by clearing the Cypress cache, the install program must have corrupted the cache there: 

`$ rm -rf /Users/kevinsimper/Library/Caches/Cypress/`

**Comment by renekorss** [comment]
After clearing Cypress cache like @kevinsimper suggested, I had to install cypress again with:
`$(npm bin)/cypress install`
After that it worked.

**Comment by loadedsith** [comment]
This happened to me. My computer locked up and crashed during the first install. I assume it was this crash that caused the corrupted cache (or whatever the issue was/is). I do no think Cypress caused this crash. Thx!

**Comment by mayankbhadauria** [comment]
![Screenshot 2019-08-11 at 18 04 06](https://user-images.githubusercontent.com/5688268/62840089-144ebf00-bc63-11e9-8e95-9b788ef0cbc5.png)

Facing same issue tries clearing cache still same error 

Tries unistall and install again but no help either

**Comment by demisx** [comment]
This happened to me when I tried to upgrade from v3.8 to v4.6. These are the steps that eventually worked for me:

```sh
npm uninstall cypress
rm -rf /Users/(whoami)/Library/Caches/Cypress/
npm cache --force clean # oh, why not
npm install cypress --save-dev
```

**Comment by only4arunkumar** [comment]
Thanks @demisx  your comment saved a lot of time for me
