### ISSUE TITLE
404 - Not Found

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/cypress#4095]
### Current behavior:
When I execute `cypress open` and run my spec, I get 

```
Sorry, we could not load:

/

404 - Not Found
```
However, in the command line the same test works

I was restructuring my tests but before the restructuring I recall this working

Cypress Version on my mac
```
Cypress package version: 3.2.0
Cypress binary version: 3.2.0
```

Cypress version inside my docker container
```
Cypress package version: 3.2.0
Cypress binary version: 3.2.0
```

My structure now looks like
```
├── cypress
│   ├── README.md
│   ├── cypress.json
│   ├── cypress.schema.json
│   ├── examples
│   │   └── integration
│   │       └── examples
│   │           ├── actions.spec.js
│   │           ├── aliasing.spec.js
│   │           ├── assertions.spec.js
│   │           ├── connectors.spec.js
│   │           ├── cookies.spec.js
│   │           ├── cypress_api.spec.js
│   │           ├── files.spec.js
│   │           ├── local_storage.spec.js
│   │           ├── location.spec.js
│   │           ├── misc.spec.js
│   │           ├── navigation.spec.js
│   │           ├── network_requests.spec.js
│   │           ├── querying.spec.js
│   │           ├── spies_stubs_clocks.spec.js
│   │           ├── traversal.spec.js
│   │           ├── utilities.spec.js
│   │           ├── viewport.spec.js
│   │           ├── waiting.spec.js
│   │           └── window.spec.js
│   ├── fixtures
│   │   └── example.json
│   ├── integration
│   │   └── project-name
│   │       ├── cart
│   │       │   ├── gift_card.spec.js
│   │       │   ├── index.spec.js
│   │       │   ├── remove_item.spec.js
│   │       │   ├── update_qty.spec.js
│   │       │   └── voucher.spec.js
│   │       ├── catalogsearch
│   │       │   └── search.spec.js
│   │       ├── category
│   │       │   ├── filter.spec.js
│   │       │   └── view.spec.js
│   │       ├── checkout
│   │       │   ├── index.spec.js
│   │       │   ├── place_order.spec.js
│   │       │   ├── select_payment_method.spec.js
│   │       │   └── select_shipping_method.spec.js
│   │       ├── customer
│   │       │   ├── account
│   │       │   ├── login.spec.js
│   │       │   ├── register.spec.js
│   │       │   └── summitclub
│   │       ├── homepage
│   │       │   └── index.spec.js
│   │       └── product
│   │           └── view.spec.js
│   ├── node_modules
│   │   └── xvfb
│   │       ├── LICENSE
│   │       ├── README.md
│   │       ├── index.js
│   │       └── package.json
│   ├── package-lock.json
│   ├── plugins
│   │   └── index.js
│   ├── screenshots
│   ├── support
│   │   ├── commands.js
│   │   ├── index.d.ts
│   │   └── index.js
│   ├── tsconfig.json
│   └── videos
│       └── project-name
│           └── homepage
│               └── index.spec.js.mp4
├── cypress.json
├── docker-compose.yml
```

My test looks like
```
/// <reference types="Cypress" />

// print out env
Cypress.env()

// start the test
describe('homepage', () => {
    beforeEach('', () => {
        cy.visit('/')
    })

    // check for the header
    it('has header', () => {
        cy.contains('header', 'Shop')
    })

    // check for store selector
    // it('', () => {
    //
    // })

    // check for ...

});

```

My cypress.json looks like
```
{
  "baseUrl": "https://www.domain.com/",
  "fixturesFolder": "fixtures",
  "integrationFolder": "integration",
  "screenshotsFolder": "screenshots",
  "videosFolder": "videos",
  "pluginsFile": "plugins/index.js",
  "supportFile": "support/index.js",
  "env": {}
}

```

### Desired behavior:
My test should run as expected

### Steps to reproduce: (app code and test code)
Execute ```cypress open```
Run test

I run a mac

**Comment by jennifer-shehane** [comment]
The `integrationFolder` should be the directory that contains the tests of your project. The `cypress.json` will be determined as the root of the project, so the folder directories set in your configuration should be defined relative to the `cypress.json` file. 

`integrationFolder: 'examples/integration'`

Where is this error being displayed exactly? Could you paste a screenshot of the error?

**Comment by WinstonN** [comment]
Hi @jennifer-shehane 

Thank you so much for your response :)

> The integrationFolder should be the directory that contains the tests of your project.

Yep, I know, I just left the example there for reference. You'll see my integration folder in the root where my tests are. I run the command line like this:

```
cypress run --spec "integration/project-name/homepage/*"
```

Screenshot below:
![image](https://user-images.githubusercontent.com/1143789/57063307-eaf2ce80-6d16-11e9-8670-bee3b7035ba1.png)

**Comment by jennifer-shehane** [comment]
Yeah, it looks as if it is not finding the `baseUrl` that you've set in the `cypress.json`, so when you visit `/`, it thinks you want to go visit a relative file within your directory. 

Likely this has to do with you moving around the test file structure. Make sure you double check the configuration of the folders. 

Also, there's a PR open now to make the location of this config file more flexible, since it's a bit weird that you have to have it in the right spot in your project directory today https://github.com/cypress-io/cypress/pull/3246

**Comment by WinstonN** [comment]
That does make sense @jennifer-shehane - now that you mention the baseUrl, I was testing overrides via environment variables, command line arguments, and the config file seeing which takes priority

I must have borked it 

Thank you so much for helping me out here - I'm gonna go ahead and close this issue

**Comment by jennifer-shehane** [comment]
You can always see the actual resolved configuration in the Settings panel of the Test Runner. The labels are listed in order of priority (ones lower in list take precedent over higher ones) https://on.cypress.io/configuration#Resolved-Configuration

![](https://user-images.githubusercontent.com/1271364/26941279-e7903108-4c4b-11e7-8731-be118e2c30eb.jpg)

**Comment by MuckT** [comment]
Had a similar issue with 404 and not found with a server using github actions to test; however, I had no endpoint on '/' of the server so cypress was failing. Once I added an endpoint on '/' of the server GitHub Actions worked seamlessly. [Here is the pull request I was having issues with.](https://github.com/MuckT/city-explorer-api/pull/1)
