### ISSUE TITLE
Do not allow more than 1 form to submit on .submit() command

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#41]
If I have more than 1 form in the DOM and write:

```
cy.get("form").submit()
```

It will issue a form submit to all forms in the DOM. This is contrary to what would actually happen during user interaction. 

**Recommendation:**
- Throw an error if there is more than 1 subject for `.submit()` command.

**Comment by brian-mann** [comment]
Fixed in [`0.6.11`](https://github.com/cypress-io/cypress/wiki/Changelog#0611-06082015).
