### ISSUE TITLE
 Uncaught Error: Uncaught TypeError: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by nkrishna79** [cypress-io/cypress#4100]
### Current behavior:
Cypress stops the test execution when it sees this error in console. I definitely know that its coming from our internal app- whilst its not a good practise and the dev team trying to resolve this, is there a way I can exclude it from failing my tests. 

### Desired behavior:
Although, I have explicitly said cypress to ignore uncaught exception in global config via this command, Cypress stops the execution due to it being a typerror rather than exception 

### Steps to reproduce: (app code and test code)
Unfortunately, it difficult to send a test code but based on the attached screenshots you can get the main issue. 
![image](https://user-images.githubusercontent.com/37705580/57077603-60917700-6ce4-11e9-97b3-3e936955df47.png)

### Versions

Cypress - 3.2.0
OS- Windows 10
Browser - chrome

**Comment by nkrishna79** [comment]
It also sometimes does this when it encounters the above error : https://github.com/cypress-io/cypress/issues/4072

**Comment by jennifer-shehane** [comment]
Some of the work in this issue is intended to help catch errors that occur like `onerror`. https://github.com/cypress-io/cypress/issues/2884

Currently, there isn't a way built into Cypress to prevent the test from failing here.

**Comment by nkrishna79** [comment]
In which case I will close this issue for now. Thanks
