### ISSUE TITLE
Selector is influenced by assertions

### ISSUE THREAD

**Issue by dialex** [cypress-io/cypress#4102]
### Current behavior:

<img width="524" alt="Screenshot 2019-05-02 at 17 35 44" src="https://user-images.githubusercontent.com/2140450/57091339-db688b00-6d00-11e9-834d-82098bae2158.png">

The same selector finds a different number of elements. The code is the same except for the assertions.

### Desired behavior:

The same selector finds the same elements, regardless of chained assertions.

### Steps to reproduce: (app code and test code)

This code:

```js
describe("autocomplete", function() {
    var locationSearchBar = ".location-selector"
    var locationSearchField = ".select2-dropdown .select2-search__field"

    it("should display District and County results", function() {
      // ARRANGE
      cy.visit("https://www.imovirtual.com/comprar/apartamento/")
      // ACT
      cy.get(locationSearchBar).click()
      cy.get(locationSearchField).type("lisboa")
      // ASSERT
      cy.get("li.select2-results__option > div").should("contain", "Lisboa")
      cy.get("li.select2-results__option > div").should("contain", "(Distrito)")
    })
  })
```

### Versions

macOS 10.14.4, Chrome 74, Latest Cypress

**Comment by dialex** [comment]
Is it because I make two `get`s and they find different elements each time (even though the selector is the same)? Is it because [select2](https://select2.org/)'s testability is 💩 ?

**Comment by jennifer-shehane** [comment]
Can you click on the `GET` command in the Command Log while your devTools are open and see how many elements it logs there?

Also, try adding a [`.pause()`](https://on.cypress.io/pause) before each `GET` so you can see how many elements it queries when it runs. 

I'm not sure if it is not querying the correct amount of elements or if the display is just wrong (the {2} label) and would like to narrow it down.

**Comment by dialex** [comment]
The gif below shows the elements of each `GET`

![get console](https://user-images.githubusercontent.com/2140450/57239015-aa4eca00-7022-11e9-852d-c1be1467ad9e.gif)

If I pause before each `GET` then both of them return 2 elements, as expected.

![Screenshot 2019-05-06 at 17 17 03](https://user-images.githubusercontent.com/2140450/57239297-67412680-7023-11e9-9727-e9bc9ea962e6.png)

**Here's my suspicion**: The 1st `GET` is so fast that it returns while the autocomplete search is running, thus it finds +30 results, the default suggestions of `select2`. The 2nd `GET` returns after the autocomplete search finishes, thus if finds 2 results, the actual results of the search.

**Comment by jennifer-shehane** [comment]
Yes, this seems to be the case. You may want to add a `cy.wait()` for the autosuggest XHR to finish before running the `cy.get()` to ensure the correct results are populated first.

**Comment by dialex** [comment]
Right now I'm using a

`cy.get(".loading-results").should("not.be.visible") // explicit wait`

instead of the `cy.wait()` you suggested. Is that ok too? I prefer explicit waits.
