### ISSUE TITLE
Snapshotting still occurs when numTestsKeptInMemory is 0

### ISSUE THREAD

**Issue by CoryDanielson** [cypress-io/cypress#4104]
### Current behavior:

When running cypress in GUI mode with `numTestsKeptInMemory` set to `0`, snapshotting still occurs even though none of them should be kept in memory. This has a negative impact on performance and memory consumption.

#### In this screenshot, you can see that `numTestsKeptInMemory` is `0`, but 5 seconds is spent taking snapshots that will not be used.
![Screen Shot 2019-05-03 at 12 35 28 PM](https://user-images.githubusercontent.com/1461792/57152227-dbb86300-6da0-11e9-8740-ceb17e43dacd.png)

#### In this screenshot you can see where the majority of the snapshot execution took place, 3.4s converting rules from large stylesheets into a string, and 0.4s replacing URLs in those strings with absolute paths.
<img width="944" alt="Screen Shot 2019-05-03 at 12 40 53 PM" src="https://user-images.githubusercontent.com/1461792/57152228-dbb86300-6da0-11e9-8f91-049336c78dbd.png">

### Desired behavior:

When running with `numTestsKeptInMemory` set to `0`, snapshotting should be avoided in the same way that occurs while running in headless mode.
- https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/log.coffee#L262-L266

### Steps to reproduce:

1. Set `numTestsKeptInMemory` to `0`.
2. Run cypress GUI mode.

### Versions

**Cypress**: 3.2.0
**Chrome**: Chrome 74

**Comment by jennifer-shehane** [comment]
Hey @CoryDanielson, can you take a look at your resolved configuration and confirm that the `numTestsKeptInMemory` configuration is being read as set to `0`? https://on.cypress.io/configuration#Resolved-Configuration

![](https://user-images.githubusercontent.com/1271364/26941279-e7903108-4c4b-11e7-8731-be118e2c30eb.jpg)

**Comment by CoryDanielson** [comment]
@jennifer-shehane I updated the original post with new screenshots.

**Comment by CoryDanielson** [comment]
I opened up a PR to address this https://github.com/cypress-io/cypress/pull/4123

I extended the if statement to include a check against `numTestsKeptInMemory`

```coffeescript
    snapshot: (name, options = {}) ->
      ## bail early and dont snapshot
      ## if we're in headless mode
      ## TODO: fix this
      if not config("isInteractive") || _.toString(config("numTestsKeptInMemory")) is '0'
        return @
```

**Comment by CoryDanielson** [comment]
I've opened a PR to address this issue - but haven't had much time recently to keep pushing it forward.

https://github.com/cypress-io/cypress/pull/4123

**Comment by brian-mann** [comment]
I'll take this PR from here and we'll get it out in the next patch release or so.
