### ISSUE TITLE
Allow reading non-existent files in cy.readFile

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#411]
`cy.readFile` is very useful, but sometimes I am trying to load a file that does not exist. Currently I am using a terrible terrible [hack](https://glebbahmutov.com/blog/cypress-tips-and-tricks/#write-and-read-files) which works in Cypress app but not in the headless version.

Maybe something like this to let me deal with empty file?
```js
cy.readFile('filename', {noThrow: true})
  .then(text => {
     // undefined text => there was no file
  })
```

**Comment by brian-mann** [comment]
Yah we can do this. We have some improvements to `cy.writeFile` like being able to write append only data that can go out with this fix as well.

**Comment by jennifer-shehane** [comment]
@lilaconlee Maybe you can look at since you worked with `cy.writeFile()` improvements?

**Comment by jennifer-shehane** [comment]
There is an example of how to read a file that may or may not exist in our docs here: https://on.cypress.io/task#Read-a-file-that-might-not-exist
