### ISSUE TITLE
cypress run command fails silently

### ISSUE THREAD

**Issue by nwshane** [cypress-io/cypress#4117]
### Current behavior:

When we run cypress in circle, it fails silently about 80-90% of the time, and setting the DEBUG env var doesn't seem to show the cause of the failure.

Here is the output when I run the command:
```
root@<redacted>:<repo_path># DEBUG=cypress:* npx --no-install cypress run --record false
  cypress:cli cli starts with arguments ["/usr/local/bin/node","/<repo_path>/node_modules/.bin/cypress","run","--record","false"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli program parsing arguments +1ms
  cypress:cli running Cypress +1ms
  cypress:cli parsed cli options { record: false } +45ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
(node:2020) ExperimentalWarning: The fs.promises API is experimental
  cypress:cli checking if executable exists /root/.cache/Cypress/3.1.5/Cypress/Cypress +2ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /root/.cache/Cypress/3.1.5/Cypress +0ms
  cypress:cli Reading binary package.json from: /root/.cache/Cypress/3.1.5/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 3.1.5 installed in: /root/.cache/Cypress/3.1.5/Cypress +2ms
  cypress:cli { verified: true } +2ms
  cypress:cli is Verified ? true +0ms
  cypress:cli processing run options +0ms
  cypress:cli --key is not set, looking up environment variable CYPRESS_RECORD_KEY +1ms
  cypress:cli Using CYPRESS_RECORD_KEY from environment variable +54ms
  cypress:cli run to spawn.start args ["--run-project","<repo_path>","--key","<redacted_key>","--record",false] +0ms
  cypress:cli needs XVFB? false +0ms
  cypress:cli spawning Cypress with executable: /root/.cache/Cypress/3.1.5/Cypress/Cypress +1ms
  cypress:cli spawn forcing env overrides { FORCE_COLOR: '1', DEBUG_COLORS: '1', MOCHA_COLORS: '1', FORCE_STDIN_TTY: '1', FORCE_STDOUT_TTY: '1', FORCE_STDERR_TTY: '1' } +0ms
  cypress:cli spawn args [ '--run-project', '<repo_path>', '--key', '<redacted_key>', '--record', false, '--cwd', '<repo_path>' ] { dev: undefined, detached: false, stdio: 'inherit' } +0ms
root@<redacted>:<repo_path># CYPRESS_EXIT_STATUS=$?
root@<redacted>:<repo_path># echo "$CYPRESS_EXIT_STATUS"
1
```

As you can see, cypress exits with a status of 1, but it doesn't output any error message or other information after the `cypress:cli spawn args` line before exiting. It seems that cypress is failing before it runs any tests, because 1. cypress fails extremely quickly, and 2. cypress _does_ sometimes run correctly, in which case it prints test failures/successes as one would expect.

### Desired behavior:

We expect that cypress would run tests normally and consistently. If something is failing on our end, we would expect cypress to show us an error about what went wrong.  

### Versions

Cypress 3.1.5
Circle 2

---

If there's any other information I can provide that would be helpful, please let me know! This is a high priority issue for my team, because these cypress failures are causing frequent false negatives in our circle test suite. It would be great to get debugging advice as soon as possible.

**Comment by bahmutov** [comment]
- can you try running the latest version of Cypress 3.2.0 just to verify the behavior
- do you use a docker image to run Cypress?

**Comment by nwshane** [comment]
@bahmutov 

- updating Cypress now, I'll let you know when we finish
- yes, we use a custom docker image to run Cypress as well as our other tests in Circle.

**Comment by nwshane** [comment]
Update! I upgraded cypress to 3.2.0, which made it output an error that led me to [this issue](https://github.com/cypress-io/cypress/issues/4034) about the `DISPLAY` var. The workaround recommend there, running `unset DISPLAY`, seems to have fixed our cypress tests.

Thanks for the recommendation to upgrade!
