### ISSUE TITLE
Chaining after within: Return inner chainable?

### ISSUE THREAD

**Issue by maxime1992** [cypress-io/cypress#4121]
### Current behavior:
```js
cy.get(`.parent`).within(() => cy.get(`.child`))
```

Yields the parent if I'm correct (?).

### Desired behavior:

I'd expect the previous command to yields the selected child.

It would be very helpful so that when we have a function or a getter to retrieve an element we could chain them.

### Versions

Cypress 3.2.0

**Comment by jennifer-shehane** [comment]
>.within() yields the same subject it was given from the previous command.

https://on.cypress.io/within#Yields

Can you provide an example of the `html` you want to test and how you would want to write Cypress to query the element you want? It's hard to visualize exactly what you are asking for without the `html` example. Thanks!

**Comment by maxime1992** [comment]
Sure thing @jennifer-shehane 

I've found a pattern that is working pretty well for me, here's an example:

```html
<div class="card">
  <div class="title">Some title</div>
  <div class="content">Some content</div>
</div>
```

```typescript
const DOM = {
  get card() {
    return {
      get self() {
        return cy.get(`.card`);
      },
      getTitle(cb) {
        return DOM.card.self.within(() => {
          cb(cy.get(`.title`));
        });
      },
      getContent(cb) {
        return DOM.card.self.within(() => {
          cb(cy.get(`.content`));
        });
      },
    };
  },
};

describe(`Card test`, () => {
  it(`should have a title`, () => {
    DOM.card.getTitle(title => title.should(`eq`, `Some title`))
  });
});
```

What I'd like to do instead:

```typescript
const DOM = {
  get card() {
    return {
      get self() {
        return cy.get(`.card`);
      },
      get title() {
        return DOM.card.self.within(() => cy.get(`.title`));
      },
      get content() {
        return DOM.card.self.within(() => cy.get(`.content`));
      },
    };
  },
};

describe(`Card test`, () => {
  it(`should have a title`, () => {
    DOM.card.title.should(`eq`, `Some title`);
  });
});
```

Basically I'd like to be able to return the inner "Promise" of `within`.

As you [pointed out](https://on.cypress.io/within#Yields), it doesn't seem to be possible:
> `.within()` yields the same subject it was given from the previous command.

**Comment by jennifer-shehane** [comment]
Yeah, you could use `.then()` to return the inner "promise" https://on.cypress.io/then#Yields but then you'd have to scope the inner commands yourself, since you'd be losing the `within` scope. 

Something like:

```js
/// code
return DOM.card.self.then(($el) => cy.wrap($el).find(`.title`));
/// code
```

**Comment by maxime1992** [comment]
I see :smile: 

I can live with that! A small helper will do the trick to avoid being repetitive!

Thanks @jennifer-shehane :pray: 

Would it make sense for `within` to return an inner promise or not at all (should we keep this issue opened or just close it?).

**Comment by jennifer-shehane** [comment]
I think we will close for now but track if anyone else requests this feature.

**Comment by g-di-martino** [comment]
That was what I was expecting too!!
