### ISSUE TITLE
Cypress preview window disappears while running a test.

### ISSUE THREAD

**Issue by briwoto** [cypress-io/cypress#4126]
### Steps to reproduce
I was following the cypress getting started the tutorial:
https://on.cypress.io/writing-your-first-test#Step-1-Visit-a-page

In the `sample_spec.js`, I have put this code:
```js
describe('Open`` url', function() {
	it('Opens the url', function() {
		cy.visit('https://portal.surveysensum.com/')
	});
});
```
Then I ran:
```shell
touch cypress/integration/sample_spec.js
```

Then I ran:
```shell
npx cypress open
```

When the cypress gets opened, I selected `sample_spec.js` and that opened a new chrome window with the cypress preview window on the right and the test stats on the left. 

### Current behavior:

As soon as the test run starts in the new window, cypress opens my url in chrome main URL bar instead of opening it in the preview window. Plus, cypress throws a js error, which is not hit when opening the url manually

> ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '__'
> Error: Cannot match any routes. URL Segment: '__'
>     at e.noMatchError (main.e24cf8bcc1f269304df0.js:1)
>     at t.selector (main.e24cf8bcc1f269304df0.js:1)
>     at t.error (main.e24cf8bcc1f269304df0.js:1)
>     at t._error (main.e24cf8bcc1f269304df0.js:1)
>     at t.error (main.e24cf8bcc1f269304df0.js:1)
>     at t._error (main.e24cf8bcc1f269304df0.js:1)
>     at t.error (main.e24cf8bcc1f269304df0.js:1)
>     at t._error (main.e24cf8bcc1f269304df0.js:1)
>     at t.error (main.e24cf8bcc1f269304df0.js:1)
>     at t._error (main.e24cf8bcc1f269304df0.js:1)
>     at M (polyfills.2e87b51ded3ed1a0ba15.js:1)
>     at M (polyfills.2e87b51ded3ed1a0ba15.js:1)
>     at polyfills.2e87b51ded3ed1a0ba15.js:1
>     at t.invokeTask (polyfills.2e87b51ded3ed1a0ba15.js:1)
>     at Object.onInvokeTask (main.e24cf8bcc1f269304df0.js:1)
>     at t.invokeTask (polyfills.2e87b51ded3ed1a0ba15.js:1)
>     at e.runTask (polyfills.2e87b51ded3ed1a0ba15.js:1)
>     at g (polyfills.2e87b51ded3ed1a0ba15.js:1)
>     at a (main.e24cf8bcc1f269304df0.js:1)
>     at main.e24cf8bcc1f269304df0.js:1
> 

### Desired behavior:
1 - Cypress should open the url in the preview window and not in the main test window
2 - JS error should not hit because the site opens fine, without any js error, when running manually

### Versions
Cypress 3.2.0
npm 6.9.0
Windows 7 74-bit

Tried running through VS code as well as through windows command prompt.

**Comment by jennifer-shehane** [comment]
I'm unable to reproduce this using the code you provided. I am running this on OSX, which I see as one difference.

Do you have anything in your `cypress.json`, support, or plugins files? Or anything else that may be different from what you provided? 

It is normal for the main Cypress window to navigate to the domain under test, but the Command Log on the lefthand side should still remain visible as shown in my example below:

<img width="1069" alt="Screen Shot 2019-05-06 at 1 25 45 PM" src="https://user-images.githubusercontent.com/1271364/57210546-102b5980-7003-11e9-88fe-48441ab0314a.png">

**Comment by briwoto** [comment]
my cypress.json contains 
`{ "modifyObstructiveCode": false } `

other than that, I have not made any changes to the default cypress settings. I have saved my project as zip here:
[unversioned.zip](https://drive.google.com/open?id=10OYYhC3J-tGNkB9cEaRSFp4_XCHyFgic)

**Comment by briwoto** [comment]
Regarding the Command log on the left hand, it disappears for me no matter what URL I run. I hit "https://www.facebook.com" and cypress still opened the site in the Chrome main window instead of the preview window

**Comment by jennifer-shehane** [comment]
Hey @briwoto, the project in the zip does run for me. Are you behind a corporate proxy?

Is there any reason you've set `modifyObstructiveCode` to `false`, it does not seem necessary in this case.

**Comment by briwoto** [comment]
Hi @jennifer-shehane, are you able to see the username and password input elements? I tried again, and I am still not able to see those. The `modifyObstructiveCode: false` was added because I was looking for a solution to my problem and thought it might have something to do with it.

**Comment by briwoto** [comment]
I am closing this issue now that I have moved to jest. The problem might be system-specific (since @jennifer-shehane is able to get the project working without any issue)

**Comment by Phillipe-Bojorquez** [comment]
This happened to me just now as well.  I was running individual specs through the UI and I closed the console window and then the left command rail disappeared.  I restarted the test runner several times with no effect.  I changed from chromium to electron.  I restarted chrome itself in case that was an issue.  Ive never had this issue before.

v3.3.1
Settings
```{
animationDistanceThreshold: 5,
baseUrl: 'obscured',
blacklistHosts: null,
chromeWebSecurity: true,
defaultCommandTimeout: 20000,
env: {
auth_audience: 'obscured',
auth_client_id: 'obscured',
auth_client_secret: 'obscured',
auth_password: 'obscured',
auth_url: 'obscured',
auth_username: 'obscured'},
execTimeout: 60000,
fileServerFolder: '',
fixturesFolder: 'cypress/fixtures',
hosts: null,
integrationFolder: 'cypress/integration',
modifyObstructiveCode: true,
numTestsKeptInMemory: 50,
pageLoadTimeout: 60000,
pluginsFile: 'cypress/plugins',
port: null,
reporter: 'mochawesome',
reporterOptions: {
overwrite: false,
reportDir: 'reports',
reportFilename: 'QA Automation Results'},
requestTimeout: 20000,
responseTimeout: 20000,
screenshotsFolder: 'cypress/screenshots',
supportFile: 'cypress/support',
taskTimeout: 60000,
testFiles: '**/*.*',
trashAssetsBeforeRuns: true,
userAgent: null,
video: true,
videoCompression: 32,
videoUploadOnPasses: true,
videosFolder: 'cypress/videos',
viewportHeight: 800,
viewportWidth: 1280,
waitForAnimations: true,
watchForFileChanges: true}```

I may be behind a corporate fire wall since i am at a conference but it was working for until i saw this issue.   So i doubt this is the reason

**Comment by markbello** [comment]
Are your tests running any snapshots? If so, I think it closes the sidebar so it doesn't appear in snapshots. I had this issue too, and after I removed them the sidebar persisted for me

**Comment by parvane-sanaie** [comment]
I know it seems so simple, but  just zoom out the browser!

**Comment by parvane-sanaie** [comment]
Sometimes the sidebar appears, but the application preview doesn't, I know it seems so simple, but  just zoom out the browser!

**Comment by ksmigiel** [comment]
> Sometimes the sidebar appears, but the application preview doesn't, I know it seems so simple, but just zoom out the browser!

Oh man, it saved me probably days of debugging.

**Comment by hello202222** [comment]
i faced same issue .. my app url just open in a diffrent window and preview just disappear . 
other url's i tried they work fine.

looks like cypress is not able to handle something in app which is causing issue . i have to move to a diffrent test automation tool it seems :(
