### ISSUE TITLE
Cypress testing has stopped working

### ISSUE THREAD

**Issue by mturnwall** [cypress-io/cypress#4157]
### Current behavior:

On my local machine no tests are working at all. This includes the Cypress example tests. The browser opens for the test runner when clicking on a test spec but the browser remains a blank page. If I go onto my personal VPN everything works as expected.

This happens from both running it using the UI runner (`cypress open`) as well as running in the terminal (`cypress run`)

The strange thing is everything was running just fine about a month ago. I moved onto different features on the project I'm working on. I came back to working on writing test cases and things just stopped working. I even created a new branch and did a clean install of Cypress

### Desired behavior:

Test should run as expected.

### Steps to reproduce: (app code and test code)

Just run any example test spec such as `viewport.spec.js`

Here is some logging. Let me know if you need more logging information:

```
cypress:server:server Getting remote state: { auth: undefined, props: null, origin: 'http://localhost:51189', strategy: 'file', visiting: undefined, domainName: 'localhost', fileServer: 'http://localhost:51190' } +1s
  cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://mqeaipywpwwawjm/', headers: { host: 'mqeaipywpwwawjm', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3787.0 Safari/537.36', 'accept-encoding': 'gzip, deflate' }, remoteState: { auth: undefined, props: null, origin: 'http://localhost:51189', strategy: 'file', visiting: undefined, domainName: 'localhost', fileServer: 'http://localhost:51190' } } +1ms
  cypress:server:server Getting remote state: { auth: undefined, props: null, origin: 'http://localhost:51189', strategy: 'file', visiting: undefined, domainName: 'localhost', fileServer: 'http://localhost:51190' } +5ms
  cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://falozzfp/', headers: { host: 'falozzfp', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3787.0 Safari/537.36', 'accept-encoding': 'gzip, deflate' }, remoteState: { auth: undefined, props: null, origin: 'http://localhost:51189', strategy: 'file', visiting: undefined, domainName: 'localhost', fileServer: 'http://localhost:51190' } } +1ms
  cypress:server:server Getting remote state: { auth: undefined, props: null, origin: 'http://localhost:51189', strategy: 'file', visiting: undefined, domainName: 'localhost', fileServer: 'http://localhost:51190' } +2ms
  cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://sdaxobfvwrld/', headers: { host: 'sdaxobfvwrld', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3787.0 Safari/537.36', 'accept-encoding': 'gzip, deflate' }, remoteState: { auth: undefined, props: null, origin: 'http://localhost:51189', strategy: 'file', visiting: undefined, domainName: 'localhost', fileServer: 'http://localhost:51190' } } +0ms
  cypress:server:timers queuing timer id 9 after 30000 ms +35ms
  cypress:server:timers queuing timer id 10 after 30000 ms +0ms
  cypress:server:timers child received timer id 9 +1s
  cypress:server:timers child received timer id 10 +0ms
  cypress:server:timers queuing timer id 11 after 30000 ms +1ms
  cypress:server:timers child received timer id 11 +1ms
  cypress:server:timers clearing timer id 9 from queue { '7': { args: [], ms: 2500, cb: [Function: cb] }, '9': { args: [], ms: 30000, cb: [Function] }, '10': { args: [], ms: 30000, cb: [Function] }, '11': { args: [], ms: 30000, cb: [Function] } } +0ms
  cypress:server:proxy received response for { url: 'http://falozzfp/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false } +2ms
  cypress:server:proxy request failed { url: 'http://falozzfp/', status: 500, error: 'Error: getaddrinfo ENOTFOUND falozzfp falozzfp:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' } +0ms
HEAD / 500 41.597 ms - -
  cypress:server:timers clearing timer id 10 from queue { '7': { args: [], ms: 2500, cb: [Function: cb] }, '10': { args: [], ms: 30000, cb: [Function] }, '11': { args: [], ms: 30000, cb: [Function] } } +14ms
  cypress:server:proxy received response for { url: 'http://mqeaipywpwwawjm/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false } +0ms
  cypress:server:proxy request failed { url: 'http://mqeaipywpwwawjm/', status: 500, error: 'Error: getaddrinfo ENOTFOUND mqeaipywpwwawjm mqeaipywpwwawjm:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' } +0ms
HEAD / 500 61.901 ms - -
  cypress:server:timers clearing timer id 11 from queue { '7': { args: [], ms: 2500, cb: [Function: cb] }, '11': { args: [], ms: 30000, cb: [Function] } } +1ms
  cypress:server:proxy received response for { url: 'http://sdaxobfvwrld/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false } +1ms
  cypress:server:proxy request failed { url: 'http://sdaxobfvwrld/', status: 500, error: 'Error: getaddrinfo ENOTFOUND sdaxobfvwrld sdaxobfvwrld:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' } +0ms
HEAD / 500 54.523 ms - -
```

### Versions
OS: MacOS 10.14.4
Cypress: 3.2.0
Chrome: 75.0.3770.18 (Official Build) beta (64-bit)

**Comment by mturnwall** [comment]
I've been able to isolate this to my actual machine. I've tried running Cypress on other machines here at work and tests run as expected.

**Comment by jennifer-shehane** [comment]
I tried running Cypress on the Chrome version you specified - that works fine for me. I ran it on MacOS 10.13.6, which is different from yours. 

These errors look notable:
```
status: 500, 
error: 'Error: getaddrinfo ENOTFOUND falozzfp falozzfp:80\n    
at errnoException (dns.js:50:10)\n    
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' } +0ms
```

Are you behind a corporate proxy? Handling proxies will be better as soon as 3.3.0 is released, but you may require a workaround today. See https://github.com/cypress-io/cypress/issues/1469

**Comment by mturnwall** [comment]
No proxy that I know of. I’ve tried it on other machines on the same network and everything works as expected. It seems like the issue is with my individual laptop. When I’m back in the office I’m going to try logging into my work account in a different machine to eliminate the issue with my work directory account.

**Comment by mturnwall** [comment]
I logged into the guest account on my mac. Setup Cypress and am getting the same results, tests don't run. I'm not sure what on my machine could be causing it. Would be great if someone else with macOS 10.14.4 could test that Cypress runs correctly.

**Comment by Lakitna** [comment]
Cypress listens to some environment variables. Could those be the culprit here?

**Comment by debone** [comment]
I'm having the same issue, with the blank screen and the `__` in the URL. I'm on MacOS 10.14.3.

**Comment by debone** [comment]
Ok, I got it fixed. I think it was my mistake. I had a global version and a local version. I uninstalled my global and updated the local one to 3.2.0.

**Comment by crhoads1024** [comment]
Running OSX 10.14.5 (18F132) - Updated last week. Now cypress DOM before and after tracking is no longer available. Test Runner fires tests properly but no before and after of the actions listed in the app view and no highlighting or clicking representation in the APP View window either. Upgraded to Cypress 3.3.2 and still exhibiting the same behavior.

**Comment by satgalley** [comment]
I am using cypress 4.0.2. I am behind the company proxy. all proxies declared in env variables. Still, I get this error.

![image](https://user-images.githubusercontent.com/22899547/74961689-18a72200-53d4-11ea-95ef-69f5e3095993.png)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
