### ISSUE TITLE
getUserMedia with microphone fails

### ISSUE THREAD

**Issue by jaypan** [cypress-io/cypress#4160]
### Bug

Requests to access the user's microphone using `getUserMedia()` fail and crash Cypress test.

### Current behavior:

I have a web application which allows users to do voice recordings in their browser. Getting access to the microphone is done through the following

```js
var constraints = {
  audio: true,
  video: false
};

navigator.mediaDevices
  .getUserMedia(constraints)
  .then(recordAudio);
```

Cypress fails this test due to the call `.getUserMedia()` with the error:

> Uncaught TypeError: Cannot read property 'getUserMedia' of undefined

I have seen that some work has been done with webcams, but I'm not finding anything for microphones.

### Desired behavior:

I would like this to not fail, so that I can test the application.

### Steps to reproduce:

index.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <script>
      window.onload = function() {
        var constraints = {
          audio: true,
          video: false
        };

        navigator.mediaDevices.getUserMedia(constraints);
      };
    </script>
  </head>
  <body>
    <p>Hello World</p>
  </body>
</html>
```

Test:
```js
cy.visit("/index.html");
```

### Versions

macOS Mojave
Cypress 3.2.0

**Comment by flotwig** [comment]
You can follow the same basic procedure as [@jennifer-shehane's comment on the webcam issue](https://github.com/cypress-io/cypress/issues/2704#issuecomment-451361237) (#2704), but instead of using `--use-file-for-fake-video-capture`, you can use [`--use-file-for-fake-audio-capture`](https://peter.sh/experiments/chromium-command-line-switches/#use-file-for-fake-audio-capture):

In `cypress/plugins/index.js`:

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    // args.push('--use-fake-device-for-media-stream')
    if (browser.name === 'chrome') {
      args.push('--use-fake-ui-for-media-stream')
      args.push('--use-fake-device-for-media-stream')
      args.push('--use-file-for-fake-audio-capture=cypress/fixtures/your_sound.wav')
    }
    
    return args
  })
}
```

**Comment by jaypan** [comment]
Thanks, playing with that now.

**Comment by jennifer-shehane** [comment]
@jaypan Great, please let us know how it works as we haven't manually tested this. I'd love to add a working example to our docs.

**Comment by jaypan** [comment]
Sorry it's taken me a while to get back to this.

Unfortunately, it's not working for me. I've added this to cypress/plugins/index.js:

```
module.exports = function (on, config) {
  "use strict";

  on('before:browser:launch', function (browser = {}, args) {

    if (browser.name === 'chrome') {
      args.push('--use-fake-ui-for-audio-stream');
      args.push('--use-fake-device-for-audio-stream');
      args.push('--use-file-for-fake-audio-capture=cypress/fixtures/audio/test.mp');
    }

    return args;
  });
};
```

I'm still getting the same error:


Logging the args being sent to the browser, I see this:

```
[ '--test-type',
  '--ignore-certificate-errors',
  '--start-maximized',
  '--silent-debugger-extension-api',
  '--no-default-browser-check',
  '--no-first-run',
  '--noerrdialogs',
  '--enable-fixed-layout',
  '--disable-popup-blocking',
  '--disable-password-generation',
  '--disable-save-password-bubble',
  '--disable-single-click-autofill',
  '--disable-prompt-on-repos',
  '--disable-background-timer-throttling',
  '--disable-renderer-backgrounding',
  '--disable-renderer-throttling',
  '--disable-restore-session-state',
  '--disable-translate',
  '--disable-new-profile-management',
  '--disable-new-avatar-menu',
  '--allow-insecure-localhost',
  '--reduce-security-for-testing',
  '--enable-automation',
  '--disable-infobars',
  '--disable-device-discovery-notifications',
  '--autoplay-policy=no-user-gesture-required',
  '--disable-site-isolation-trials',
  '--metrics-recording-only',
  '--disable-prompt-on-repost',
  '--disable-hang-monitor',
  '--disable-sync',
  '--disable-web-resources',
  '--safebrowsing-disable-auto-update',
  '--safebrowsing-disable-download-protection',
  '--disable-client-side-phishing-detection',
  '--disable-component-update',
  '--disable-default-apps',
  '--use-fake-ui-for-media-stream',
  '--use-fake-device-for-media-stream',
  '--proxy-server=http://localhost:51989',
  '--proxy-bypass-list=<-loopback>',
  '--use-fake-ui-for-audio-stream',
  '--use-fake-device-for-audio-stream',
  '--use-file-for-fake-audio-capture=cypress/fixtures/audio/test.mp3' ]
```
Note that the file cypress/fixtures/audio/test.mp3 does exist. I've also tried the paths:

* fixtures/audio/test.mp3
* audio/test.mp3

As well as all combinations with a leading slash. I've shut down the test runner (the browser GUI) in between each change to make sure that the args are picked up during browser launch, and can confirm that they are, but that the error still occurs.

**Comment by flotwig** [comment]
Have you tried using a `.wav` file? A `.mp3` won't work, according to the docs for `--use-file-for-fake-audio-capture`:

> Play a .wav file as the microphone. Note that for WebRTC calls we'll treat the bits as if they came from the microphone, which means you should disable audio processing (lest your audio file will play back distorted). The input file is converted to suit Chrome's audio buses if necessary, so most sane .wav files should work. You can pass either <path> to play the file looping or <path>%noloop to stop after playing the file to completion. ↪

**Comment by jaypan** [comment]
I was just digging through the docs and found that myself. I tried a .wav file, but it also is not working.

**Comment by flotwig** [comment]
Hmm, that's strange. I'm using Cypress 3.3.0 with Chromium 73 on Linux and it works fine for me, even without `--use-file-for-fake-audio-capture`:

```html
<!DOCTYPE html>
<html>
  <head>
    <script>
      window.onload = function() {
        var constraints = {
          audio: true,
          video: false
        };

        navigator.mediaDevices.getUserMedia(constraints)
        .then(stream => {
          console.log(stream)
        })
      };
    </script>
  </head>
  <body>
    <p>Hello World</p>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/1151760/58258670-26dee980-7d41-11e9-97e8-898c8763e597.png)

What version of Chrome are you using?

**Comment by jaypan** [comment]
Chrome 74.
Exact html doc as you  (I copy/pasted), and I get this:

<img width="1440" alt="Screen Shot 2019-05-24 at 0 03 23" src="https://user-images.githubusercontent.com/463560/58259268-8aa3f980-7db7-11e9-907e-dd3dabc87b79.png">

**Comment by flotwig** [comment]
Well, as soon as I use Chrome 74, I get the same error.... maybe some behavior changed between 73 and 74 w.r.t. how these command line args are handled.

**Comment by jaypan** [comment]
Oh, well that's a pain. Thanks for your help, much appreciated.

**Comment by jaypan** [comment]
Guys, I've just realized this not working was me overlooking the problem altogether.
I've been developing in Firefox - works fine. Cypress of course runs in Chrome. I finally took the time to look at it in Chrome - and sure enough it wasn't working in the browser, hence not a Cypress problem.

The actual problem is that Chrome now blocks getUserMedia in non-HTTPS. This is probably documented somewhere, but I made the assumption, and sure enough it works in HTTPS.

So I can comfortably say that this works (but requires HTTPS):

```
module.exports = function (on, config) {
  "use strict";

  on('before:browser:launch', function (browser = {}, args) {

    if (browser.name === 'chrome') {
      args.push('--use-fake-ui-for-media-stream');
      args.push('--use-fake-device-for-media-stream');
      args.push('--use-file-for-fake-audio-capture=cypress/fixtures/audio/test.mp');
    }

    return args;
  });
};
```

**Comment by jennifer-shehane** [comment]
@jaypan Great to hear you were able to get it to work!

**Comment by ziadasem** [comment]
this error is due to chrome and other browsers block microphone access to not https sites
so try to install SSL
you can get your free one from here
https://www.sslforfree.com/
and follow the tutorial
