### ISSUE TITLE
'visible' assertion says visible for elements cropped by parent element with overflow: hidden

### ISSUE THREAD

**Issue by mvasin** [cypress-io/cypress#4161]
### Current behavior:
Cypress claims an element is visible, while it's completely cropped by parent `overflow: hidden` container element.

Here's html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
    .container {
      display: flex;
      overflow: hidden;
    }
    div {
      flex: 0 0 80%;
    }

    [data-cy=red] {
      background-color: red;
    }

    [data-cy=green] {
      background-color: green;
    }

    [data-cy=blue] {
      background-color: blue;
    }
  </style>
</head>
<body>
  <div class="container">
    <div data-cy="red">red</div>
    <div data-cy="green">green</div>
    <div data-cy="blue">blue</div>
  </div>
</body>
</html>
```

Here's the test:
```js
/// <reference types="Cypress" />

describe('Smoke test', () => {
  it('отображает футер', () => {
    cy.visit('http://localhost:8080')
    cy.get('[data-cy="red"]').should('be.visible')
    cy.get('[data-cy="green"]').should('be.visible')
    cy.get('[data-cy="blue"]').should('not.be.visible')
  })
})
```
All three divs, red, green and blue are 80% of the parent, parent div is `overflow: hidden`, there is no way for a user to scroll to blue div:
![Screenshot from 2019-05-08 16-32-54](https://user-images.githubusercontent.com/12434833/57379400-84a2fb80-71af-11e9-909f-3edac37b5f38.png)

But Cypress somehow scrolls to that div and thinks it's visible:
![Screenshot from 2019-05-08 16-33-11](https://user-images.githubusercontent.com/12434833/57379441-9b495280-71af-11e9-8d74-41c053a9ebf3.png)

### Desired behavior:

Above code should be enough, but just in case, here's the reproduction repo: https://github.com/mvasin/cypress-visible-bug

### Versions
Cypress 3.2.0, Ubuntu 18.04.2 LTS, Electron 59 or Chrome 74

**Comment by speir-wang** [comment]
I am having the same issue. In my case, the `react-select` dropdown menu is being cropped from the view, technically speaking, we can see part of the dropdown, but the `shoud(be.visible)` is not happy with it :(

**Comment by jennifer-shehane** [comment]
May be related to this issue: https://github.com/cypress-io/cypress/issues/683

**Comment by jennifer-shehane** [comment]
What is additionally weird is that when you go to hover to see the snapshot, the blue div does appear in the snapshot. 

I've written a failing test for this within https://github.com/cypress-io/cypress/pull/4421
