### ISSUE TITLE
Crashing issue. 

### ISSUE THREAD

**Issue by ankitharendra** [cypress-io/cypress#4173]
when we test our full platform then it stop the running because of it's take lots of memory for storing the screenshots. I think it should save only those screenshots which have errors on all the test. I am not want to use "numTestsKeptInMemory" because I want all screenshots where test case is fails.

**Comment by jevors** [comment]
There are many issues about the performance of Cypress and memory issues. A pretty common issue is the length of the tests. You could try and improve by cutting up long tests to shorter tests.

**Comment by Lakitna** [comment]
Running in CLI mode helps.

Also `numTestsKeptInMemory` does not impact screenshots, only snapshots.

There are multiple PR's right now to adress this issue, like #4068 for example

**Comment by ankitucertify** [comment]
> There are many issues about the performance of Cypress and memory issues. A pretty common issue is the length of the tests. You could try and improve by cutting up long tests to shorter tests.

But I want to test all the platform of my website at one click...

**Comment by maxime1992** [comment]
We've had our tests running slow for quite a long time on desktop and completely crashing cypress on laptop. We've ended up setting `numTestsKeptInMemory` to 2 but this is far from being the best option as failing ones may not be the last ones. An option for that would be much appreciated :)

**Comment by jennifer-shehane** [comment]
We had several performance improvements in our 3.3.^ releases, please update to our [latest version](https://on.cypress.io/changelog).

If you're still experiencing this issue in our latest release, we need a reproducible example provided in order to have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
