### ISSUE TITLE
Custom command is not available

### ISSUE THREAD

**Issue by Tazovsky** [cypress-io/cypress#4174]
### Current behavior:

[Regarding documentation](https://docs.cypress.io/api/cypress-api/custom-commands.html#Syntax) all I need to add custom command is to put it in `cypress/support/commands.js` so I  added example custom command in `command.js`

```
Cypress.Commands.add("alert", () => { 
    alert("! test alert !")
 })
```

but function is not available using `cy.alert()` - why?

My `index.js` is:

```
import './commands'
```

### Versions

Cypress v3.2.0

OS: macOS

**Comment by jennifer-shehane** [comment]
Hey @Tazovsky, any info on how you resolved your issue is appreciated since someone else may run into the same.

**Comment by jesscahelen** [comment]
Hi @Tazovsky,  could you please show how you made it work, because I'm having the same problem. :(
