### ISSUE TITLE
Cypress doesn't catch XHR request

### ISSUE THREAD

**Issue by jess-ika** [cypress-io/cypress#4178]
Hi guys, I am currently having an issue with graphql request which cypress is unable to catch.
After searching through the issues I found a solution with the use of polyfills. Here is my code :
```js
import './commands'

let polyfill

before(() => {
  const polyfillUrl = 'https://unpkg.com/unfetch/dist/unfetch.umd.js'
  
  cy
    .request(polyfillUrl)
    .then(({ body }) => {
      polyfill = body
    })
})

Cypress.on('window:before:load', (win) => {
  win.eval(polyfill)
  win.fetch = win.unfetch
})
````
in ```support/index.js````

However I would not like to use a cdn.
So I modified my code as follows
 ```js
import './commands'

import fetch from 'unfetch'

Cypress.on('window:before:load', (win) => {
  win.fetch = fetch
})
````
With this, my graphql request is correclty types as ```XHR``` in chrome debug tools, but is still not catched by cypress test runner
Any advice please.

Thank you

**Comment by gituser3000** [comment]
https://github.com/cypress-io/cypress/issues/95

**Comment by SebDuf** [comment]
I have a similar problem. I replace `fetch` with the `unfetch` polyfill, the requests are logged are `XHR` in the chrome dev tools but Cypress doesn't catch them.

Here's a screenshot from my Cypress' Chrome Network tab:

![image](https://user-images.githubusercontent.com/12822182/58717840-288c5b00-839a-11e9-87d1-4c86d17e1c87.png)

All of these requests would normally be `fetch` requests but have been correctly polyfilled to `xhr`, but they are invisible to Cypress. Route stubs do not work with them and they are not logged by the test runner

**Comment by jess-ika** [comment]
@SebDuf I ended up stubbing my fetch request without polyfill
I had this particular problem with graphql request, Here's how I fixed it :
````
Cypress.Commands.add('mockGraphQl', (stub) => {
  cy.on('window:before:load', (win) => {
    const originalFetch = win.fetch

    function newFetch(path, { method }) {
      if (stub && path.includes('/gql') && method === 'POST') {
        return Promise.resolve(responseStub(stub))
      }
      return originalFetch.apply(this, arguments);
    }

    cy
      .stub(win, 'fetch', newFetch)
      .as('Stub GraphQl');
  })
})
```

**Comment by jess-ika** [comment]
https://github.com/cypress-io/cypress-documentation/issues/122

**Comment by jennifer-shehane** [comment]
Closing as resolved / part of fetch issue https://github.com/cypress-io/cypress/issues/95
