### ISSUE TITLE
Wide selectors in the selector playground can cause GUI overflow issues 

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#4184]
### Current behavior:
Very long selectors in the selector playground text input box can overflow other page elements:
![image](https://user-images.githubusercontent.com/5534029/57643927-e3d68680-7588-11e9-89fc-9e7c9eb4f2af.png)

### Desired behavior:
When some maximum width of the field is reached (based on the browser's width), the user has to scroll to see the rest of the input.  Something like this:
https://codepen.io/Momciloo/pen/bpyMbB

### Steps to reproduce: (app code and test code)
Type or paste a very long selector in to the selector playground text input box.  And yes, I know that using selectors that look like this is not recommended :)

### Versions
Cypress 3.2, Windows 10, Chrome

**Comment by jennifer-shehane** [comment]
😬 

The code for this input can be found here: https://github.com/cypress-io/cypress/blob/issue-3658/packages/runner/src/selector-playground/selector-playground.jsx#L60

This component is currently tested with Enzyme tests here: https://github.com/cypress-io/cypress/blob/issue-3658/packages/runner/src/selector-playground/selector-playground.spec.jsx#L8

**Comment by chrisbreiding** [comment]
The code for this is done in [cypress-io/cypress#8509](https://github.com/cypress-io/cypress/pull/8509), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
