### ISSUE TITLE
Steps in a scenario end abruptly and service calls spill into next scenario

### ISSUE THREAD

**Issue by koalabearGH** [cypress-io/cypress#4189]
Hi All,

We are currently running into an issue when running a test suite. I believe Cypress is already aware of the fact that the browser does not seem to be fully closed in between tests and also that the xhr calls are "spilling over" into the subsequent tests. (https://github.com/cypress-io/cypress/issues/216)

The last issue that was opened regarding this, linked above issue #216, was from 2016 and was closed in favor of the Lifecycle events feature which has not yet been delivered.

Are there any workarounds for this currently?

We tried adding explicit waits and also clearing the `localstorage` and cookies in the `beforeeach` but still run into the problem. The tests do pass successfully when run individually using `it.only`

### Current behavior:

![image](https://user-images.githubusercontent.com/50602962/57664335-ba2f5680-75ac-11e9-98da-06f8e9e6387f.png)

### Desired behavior:

The tests in the file (currently a total of 15 tests) should pass as expected. We tried splitting the tests into separate files but encountered the same issues. (When running the tests individually using `it.only`, the tests pass with no issues)

### Steps to reproduce: (app code and test code)

Per the attached screenshot, there are multiple scenarios (total of 15 in this case) in this file.

Also, as you can see, the top scenario simply ends abruptly at the `cy.visit` step although there are many steps after that and the next scenario begins. However, when the next scenario begins, the service calls from the previous scenario seem to still be running and this seems to be causing issues and failures in subsequent tests.

### Versions

Cypress package version: 3.2.0
Cypress binary version: 3.2.0
Windows 10 Enterprise 64-bit
Chrome 74

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
