### ISSUE TITLE
Command line arrays no longer being split

### ISSUE THREAD

**Issue by dracos** [cypress-io/cypress#4198]
### Current behaviour:

If you run `cypress open --config 'blacklistHosts=[example.com,*.example.net]'` it puts a string of `[example.com,*.example.net]` in blacklistHosts rather than two entries in an array, which it used to do.

### Desired behaviour:

It should create an array in blacklistHosts of two entries, `['example.com', '*.example.net']`. It used to do this; the commit that added this behaviour was https://github.com/cypress-io/cypress/commit/31f22c24b2065268daeeca928001aa5a750bf094 and I think that the commit that broke it was https://github.com/cypress-io/cypress/commit/ce3ab55f72527374cfa2a1b942dffedb5d1a232f (done because it was affecting other command line arguments, maybe?).

### Steps to reproduce: (app code and test code)

Run any cypress open command with that config and then look at Settings -> Configuration to see the generated config (this view made it much easier to find this out, thanks!).

### Versions

Have seen on both Cypress 3.1.2 on Mac, and Cypress 3.2.0 on Linux.

**Comment by sainthkh** [comment]
NOTE: `blacklistHosts` has been changed to `blockHosts` in 5.0.0.

**Comment by sainthkh** [comment]
One workaround is to add blockHosts to `cypress.json`.

**Comment by eric-burel** [comment]
It leaves us with no way to customize blocked hosts depending on the context. We can't customize it per test either. In the past, `Cypress.config({blockHosts: [...]})` would work but it was undocumented and seems to have stopped working.
A use case is displaying/hiding tiles for visual regression testing of maps, where tile images loading takes a lot of time and can create false positive.
