### ISSUE TITLE
when scrolling to an element to click, sometimes the center of the el is out of view

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#42]
The scrolling to an element within click needs to be reworked so that the entire element (the subject of `.click()` is within the view. 

Also, it may be timing out sooner than 4 secs.

![screen shot 2015-06-08 at 1 10 45 pm](https://cloud.githubusercontent.com/assets/1271364/8040610/cf07cc74-0ddf-11e5-8194-cac21eb45676.png)

**Comment by brian-mann** [comment]
Fixed in [`0.6.11`](https://github.com/cypress-io/cypress/wiki/Changelog#0611-06082015).
