### ISSUE TITLE
`cy.clear()` not behaving the same as `{selectall}{backspace}`

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#420]
Using the library [jquery-maskmoney](http://plentz.github.io/jquery-maskmoney/) (v3.0.0) and testing typing into an input, the `cy.clear()` command does not behave the same as using `cy.type({selectall}{backspace})`.

```javascript
it('clear and type money value', function(){
    cy
        .visit('http://plentz.github.io/jquery-maskmoney/')
        .get("#demo8").clear().type('1000')
            .invoke('val').should('eq', '10.00')  // this fails
})

it('selectall and backspace money value', function(){
    cy
       .visit('http://plentz.github.io/jquery-maskmoney/')
       .get("#demo8").type('{selectall}{backspace}1000')
           .invoke('val').should('eq', '10.00')  // this passes
})
```

![screen shot 2017-02-09 at 3 25 19 pm](https://cloud.githubusercontent.com/assets/1271364/22801944/e7e584ae-eedc-11e6-823e-480ebe346871.png)

**Comment by madhuriaarth** [comment]
how to use keypad backspace in cypress
