### ISSUE TITLE
Drop Node 4 & 6 support from CLI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4200]
When one does `npm install cypress` one downloads NPM package built in "cli" folder. All production dependencies in "cli/package.json" currently support Node 4+ thus you can install Cypress even if you are rocking Node 4

But I am trying to verify downloaded binary zip file by using [hasha](https://github.com/sindresorhus/hasha) in https://github.com/cypress-io/cypress/pull/4193 Hasha has dropped Node 4, 6 support so if we include it in the CLI production dependencies, our `cypress` npm package will no longer support Node 4 or 6 either.

In fact, it is hard for me to say if all our current production dependencies really run on Node 4 since many packages do not declare engines

## Proposal

- stop supporting Node 4

- Node 4 end-of-life was in April 2018 https://github.com/nodejs/Release
- we have stopped testing Cypress on Node 4 https://github.com/cypress-io/cypress-test-node-versions/issues/20

(even Node 6 has reached end-of-life as of April 2019)

**Comment by jennifer-shehane** [comment]
I would like this also. I had to revert some updates that dropped support for Node 4, a lot of packages are dropping and it is preventing us from keeping up to date with their fixes. 

I specifically had to revert PR updates for 
- `commander` https://github.com/cypress-io/cypress/pull/3366
- `cachedir` https://github.com/cypress-io/cypress/pull/3660

I'd be happy to work on this. Will open a PR.

**Comment by brian-mann** [comment]
Sure - I am in favor of this, we can drop `node 4` support in the next release after `3.3.0`

**Comment by jennifer-shehane** [comment]
Ok, so we are planning to release 3.3.0 without dropping Node 4 and without https://github.com/cypress-io/cypress/pull/4193 then we will craft a new 4.0 branch that will drop Node 4 and any PRs that are isolated fixes that we can pull in from the 4.0 epic. https://github.com/cypress-io/cypress/issues/2840 https://github.com/cypress-io/cypress/pull/2880
