### ISSUE TITLE
unable to require node-sass within plugins - can not test svelte file with sass syntax in the style tag

### ISSUE THREAD

**Issue by JordanKlaers** [cypress-io/cypress#4202]
### Current behavior:

When I include the plugin for `cypress-svelte-unit-test` which suggested to include my webpack config, I get an error when running cypress open `A dynamic link library (DLL) initialization routine failed.`

When I remove the import for `node-sass` in the webpack config that seems to fix. I have tried many things including downloading my node to `8.2.0` and reinstalling `node-sass` and `cypress`. I am able to get things working when I remove the usage of `node-sass` in the webpack and remove the sass in the svelte file

### Desired behavior:

I would like to be able to run tests on svelte modules that contain scss syntax in the files. Running the project in `localhost` with my webpack setup currently works.

### Steps to reproduce: (app code and test code)

https://github.com/JordanKlaers/cypress_test_failing_example/tree/nodeSassDLLError

run `node_modules\.bin\cypress open`

run the only test file

### Versions

node version 8.11.2
npm 5.10.0
windows 10

**Comment by jennifer-shehane** [comment]
Hey @JordanKlaers, did you take a look at this issue about node-sass? https://github.com/cypress-io/cypress/issues/3875 I believe it may be related.

**Comment by JordanKlaers** [comment]
I have tried running npm rebuild node-sass, I have tried reinstalling node modules, as well as npm install sass all mentioned within that ticket. I downgraded to node v8.2.0 as well for all those commands

**Comment by JordanKlaers** [comment]
Also I saw some suggestions about installing the correct binary from https://github.com/sass/node-sass/releases for version 4.12 (thats the node-sass version I have) and replacing it in the node modules folder. I tried a few different binaries and they did not help. I also tried changing the folder under vendor to win32-x64-xx rather than win32-x64-57 although I then got an error saying that it was looking for 57. 
also tried npm rebuild.
I tried npm rebuild node-sass --force but got errors doing that, I can post them if they are relevant

**Comment by JordanKlaers** [comment]
many of the additional things I just tried came from https://stackoverflow.com/questions/37986800/node-sass-could-not-find-a-binding-for-your-current-environment as well

**Comment by JordanKlaers** [comment]
@jennifer-shehane I notice these two similar issues have been opened, one in 2018, with no outcome
https://github.com/cypress-io/cypress/issues/2967
https://github.com/cypress-io/cypress/issues/4162

Is this issue not resolvable?

**Comment by flotwig** [comment]
@JordanKlaers the solution is unclear, you can read #3875 for a technical explanation of the issue and workarounds.

**Comment by JordanKlaers** [comment]
I have ran every command suggested in the issue. I have also change the version of Node I am using with Nvm, to match the version that cypress uses (8.2.1) verified with the node -v in the terminal. Then I delete node modules and run npm install, as well as every command mentioned in every other thread I also mentioned. 

If I understand correctly from the issue you posted, this issue comes from a mismatch in the node I have and the node cypress uses which should have been resolved rerunning everything using the matching node version. I have also messed with changing the binding in the node modules from by downloading different bindings from  https://github.com/sass/node-sass/releases which does cause me to get the incorrect binding error, but when reverting those changes it goes back to the DLL error, not a missing bindings error like almost every other post is about.

I'm just trying to explain everything Ive tried, hopefully something will come to light, possibly that I have done wrong or haven't tried yet

**Comment by jennifer-shehane** [comment]
If it's a Node version mismatch, it should be fixed when this issue is fixed https://github.com/cypress-io/cypress/issues/4432 Closing as duplicate

**Comment by JohnnyFun** [comment]
If it's any help to anyone configuring svelte preprocess to work with `cypress-svelte-unit-test`, more info here: https://github.com/bahmutov/cypress-svelte-unit-test/issues/45

**Comment by JohnnyFun** [comment]
In fact, I'm curious why "nodeVersion" wouldn't be set to "system" for plugins by default?

**Comment by jennifer-shehane** [comment]
@JohnnyFun Because this would have been a breaking change and we see needing to set `nodeVersion` as the exception to what most users need.

**Comment by JohnnyFun** [comment]
That totally makes sense. I was actually just about to delete my comment lol. Getting late... Thanks!
