### ISSUE TITLE
Ampersand (&) in spec file causes test not to run

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#4210]
### Current behavior:
The spec file in my example has an '&' in the title: `capture_all_student_documents-&-forms_get_requests.spec.js`
![image](https://user-images.githubusercontent.com/5534029/57856711-90984a00-77bb-11e9-8933-3ab7357a67e5.png)

The dashboard lists the below error.  Note the `Error: Cannot find module [...] capture_all_student_documents-` where the wrong filename is listed because it has been truncated immediately before the ampersand.
![image](https://user-images.githubusercontent.com/5534029/57856725-968e2b00-77bb-11e9-8b02-f70a77f60094.png)

### Desired behavior:
Spec files with ampersands in the filenames run without error.  I have not tested other characters to see if there are other common characters which also cause errors, but if so, these other characters would also run without error.

### Steps to reproduce: (app code and test code)
Name a spec file with an '&' as part of the file name.  Run the spec file.

### Versions
Cypress 3.2, Windows 10, Chrome

### Workaround
Obviously you can rename the spec file to something without the '&', such as replacing it with 'and'.

**Comment by jennifer-shehane** [comment]
Can confirm, opening a spec file with an `&` character errors. On OSX too.
