### ISSUE TITLE
Allow modify html content before rendering `cy.visit`

### ISSUE THREAD

**Issue by freewind** [cypress-io/cypress#4211]
In our web page to be tested, we hardcoded some feature toggle in page, the simplified code is like:

```html
<html>
<head>
<script>
window.featureToggles = {
'toggle1': false,
'toggle2': false
}

if(window.featureToggles['toggle2']) {
  // do something
}
</script>
</head>
<body>
</body>
</html>
```

I want to test some feature when toggle `toggle1` is on, but it's too late to set it true in `onBeforeLoad`, since the code depending on the toggles already executed.

If cypress allow we modify the fetched html code before rendering, that will fix this problem. The api might be like:

```js
cy.visit({
  url: someUrl,
  modifyFetchedCode: (html) => {
    return html.replace('some', 'target');
  }
})
```

Is it possible?

**Comment by flotwig** [comment]
You can't currently modify the HTML of the response to cy.visit; however, this will be added as part of #687.

**Comment by bahmutov** [comment]
@freewind because you know the name of the `window` property the application code will be using, you can be ready - you can write it first from the Cypress test and make it read-only. I put together the repo with the example for you here https://github.com/bahmutov/cypress-example-feature-toggles

In essence, you want to do this:
```js
  cy.visit('index.html', {
    onBeforeLoad (win) {
      Object.defineProperty(win, 'features', {
        writable: false,
        value: {
          first: true,
          second: false
        }
      })
      // when the application code tries to set "window.features"
      // it will be silently ignored
    }
  })
  // confirm the first checkbox is checked
  cy.get('#first').should('be.checked')
  cy.get('#second').should('not.be.checked')
})
```
