### ISSUE TITLE
Blank screen when re-running test in GUI

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4212]
When I click the button to re-run tests, Cypress redirects to a different port and cannot connect to the server's WebSocket.

From here:
![image](https://user-images.githubusercontent.com/1151760/57870378-f04f1f00-77d4-11e9-889e-5d4e738b8d5b.png)

I click ![image](https://user-images.githubusercontent.com/1151760/57870390-f7762d00-77d4-11e9-9466-0949dac43359.png) or the refresh button and it brings me the same URL, but on the AUT's port, not Cypress's port:
![image](https://user-images.githubusercontent.com/1151760/57870424-0f4db100-77d5-11e9-8b6d-a8d3512fcc9b.png)

In the console, there is this error:
![image](https://user-images.githubusercontent.com/1151760/57870451-1c6aa000-77d5-11e9-867f-ac9e78179c48.png)

Reproducible by running the `6_visit_spec` e2e test's `visit_response_never_ends_failing_spec` with the first test `.only`'d in Chrome on the commit `c6573499b74d230994a14c325990de64a793bbb2`.

Similar issue: #2104

**Comment by planetbk9** [comment]
Try to add map for localhost to 127.0.0.1 in /etc/hosts.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
