### ISSUE TITLE
"select manually" button crashes desktop gui in Ubuntu

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#4213]
### Current behavior:

Clicking the "select manually" button immediately crashes the desktop gui. 

<img width="734" alt="Screen Shot 2019-05-29 at 10 53 42 AM" src="https://user-images.githubusercontent.com/1271364/58529239-0fe83d80-8200-11e9-8757-866659868b0a.png">

It started happening when I upgraded to Ubuntu 19.04.

debug output:

```sh
  cypress:server:updater latest version of Cypress is: 3.2.0 +226ms
  cypress:server:updater new version of Cypress does not exist +0ms
  cypress:server:events sending ipc data { type: 'updater:check', data: { id: 0.4245733230504263, data: false } } +126ms
  cypress:server:timers child sending timer id 2 +1s
  cypress:server:timers child sending timer id 3 +519ms
  cypress:server:timers child sending timer id 4 +67ms
  cypress:server:events got request for event: show:directory:dialog, undefined +3s
  cypress:electron electron closing with code null +9s
  cypress:electron calling callback with code null +0ms
  cypress:server:cypress electron finished with null +9s
  cypress:cli electron open returned 0 after 10475 ms +10s
```

### Versions

OS: ubuntu 19.04
Cypress version: 3.x.x

#### tasks:
- [ ] unset XDG_CACHE_HOME (`cachedir` will use it if exists)

**Comment by Bkucera** [comment]
Found the problem, VSCode was installed as a `snap package` causing the environment variable `XDG_CACHE_HOME` to be set to `~/snap/code/...`, and when launching Cypress from there, this caused the Cypress binary `cache directory` to be in `~/snap/code`, which caused this error.

Solution: don't use the snap version of vscode

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
