### ISSUE TITLE
cypress application preview pane scrolling issue

### ISSUE THREAD

**Issue by jehoffm** [cypress-io/cypress#4214]
With the latest version of Chrome (74.0.3729) we started having issues with the way application preview pane in the Test Runner scrolls out of view when reviewing the command log.  Then when we click on a line in the command log, the entire view scrolls to the top to show the app preview, but now we lose our place in the command log.  

We tried the 'disable autoscrolling' eature but it didn't make a difference

We need the aplication preview pane to scroll independently of the command log again.

### Steps to reproduce: (app code and test code)

1. Run a test
2. In the Cypress Runner window, scroll down the command log

### Versions

3.1.1

**Comment by jennifer-shehane** [comment]
@jehoffm Is there any way you could provide a short gif/video or some visual screenshots explaining this behavior? I've been running a lot of tests lately on 74.0.3729.157 and haven't seen this. 

Could you also offer any insight on the `viewportWidth` and `viewportHeight` set for you application under test - whether you have devTools open? are they docked, etc? What OS are you using?

I just need to know what conditions to set it up in exactly to reproduce this behavior.

**Comment by jehoffm** [comment]
Thanks for the reply.
Not sure I can send a video but maybe I could share my desktop via Slack if you have that capability?

We have the default viewport settings without dev tools open, using Windows.

Thanks,
Jeff Hoffman

**Comment by jehoffm** [comment]
Actually I was able to capture a video after all. Let me know if this helps.  Basically, when we click on an item in the log in the left pane, it jumps back to the top and we can no longer see the command log line side-by-side with the corresponding application view pane.
[Cypress scrolling issue.zip](https://github.com/cypress-io/cypress/files/3191941/Cypress.scrolling.issue.zip)

**Comment by jehoffm** [comment]
Actually I was able to capture a video after all. Let me know if this helps.  Basically, when we click on an item in the log in the left pane, it jumps back to the top and we can no longer see the command log line side-by-side with the corresponding application view pane.
[Cypress scrolling issue.zip](https://github.com/cypress-io/cypress/files/3191945/Cypress.scrolling.issue.zip)

**Comment by jennifer-shehane** [comment]
@jehoffm Thanks for providing the video. This is helpful.

The entire command log should be independently scrollable from the application under test, but they appear to be scrolling in one window. 

How it should work:

![](http://g.recordit.co/vSw6ntBIpz.gif)


[I've seen this before when users employed a workaround intended for a Chrome 72 bug on later versions of Chrome.](https://github.com/cypress-io/cypress/issues/3253) 

Do you have the code below in your test code? If you do, you will need to upgrade Cypress to a version above 3.1.5 and remove this code in order to fix the issue you are facing. 

```js
module.exports = (on) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') { 
      // ^ make sure this is your browser name, you may 
      // be using 'canary' or 'chromium' for example, so change it to match!
      args.push('--proxy-bypass-list=<-loopback>')
      return args
    }
  })
}
```

**Comment by jennifer-shehane** [comment]
Hey @jehoffm any update on if you have the code above?

**Comment by jehoffm** [comment]
Yes, thanks. Just had to update to the latest version.
