### ISSUE TITLE
Not able to see the localhost webcontent using cypress for e2e testing

### ISSUE THREAD

**Issue by mohammedroni4** [cypress-io/cypress#4215]
Hi, @jennifer-shehane

#1 So I'm new to cypress where I'm facing issue and not able to move on, the problem that I'm currently facing is, I started my localhost, and it is not somehow showing in the cypress site, I'm using `localhost:3000`, but it seems to be saying to use `cy.request()`. which I did and it still not showing the UI or the content of them html for some reason and it is not giving me any error either.

#2 And when im using the production version I see errors of:

```
Status: 401 - Unauthorized
Headers: {
  "server": "AppleHttpServer/54b48526",
  "date": "Thu, 16 May 2019 19:25:52 GMT",
  "content-type": "text/html",
  "content-length": "609",
  "connection": "close",
  "www-authenticate": "Basic realm= "some date"
```

But the case is we are not suppose to use the production version for testing we should use the localhost at all time. So for #1 option we need to know how to figure it out. 

Any suggestions.?

<img width="1766" alt="Cypress" src="https://user-images.githubusercontent.com/13221629/57880796-8171c600-77d4-11e9-9d2b-72c6f24e3225.png">

**Comment by Lakitna** [comment]
You are looking for `cy.visit()` instead of `cy.request()`

Please note that there is a Cypress Gitter where you can ask questions and get answers quicker. Asking your questions there will also help to keep the issue log clean. https://gitter.im/cypress-io/cypress

**Comment by shaunforan** [comment]
But it's a valid issue though; I am now unable to access my `http://localhost:3000` site anymore (created with Create React App) after the update to 3.3.0. For some reason I am now getting the error "Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE" even though my app is up and running properly.

**Comment by flotwig** [comment]
@shaunforan can you create a new issue describing the problem? We made a lot of network changes in 3.3.0, so it will help us to have as much information as possible.

**Comment by shaunforan** [comment]
Sure, I'll make one now. Thanks!

**Comment by mohammedroni4** [comment]
Thanks you Sander, I started posting my post now.

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
