### ISSUE TITLE
[reporting] Include pending XHR requests in report / output on test failure

### ISSUE THREAD

**Issue by Niceplace** [cypress-io/cypress#4217]
### Current behavior:

Note: We are using the default reporter (spec) in our CI environment.

When encountering a test error, logs show an error message + stack trace, something like this:
In this example ' Playlists displays number of playlists in AccountSideMenu' is the test's title.

```
1) Playlists displays number of playlists in AccountSideMenu:
      CypressError: Timed out retrying: Expected <svg> not to exist in the DOM, but it was continuously found.
      at Object.cypressErr (https://qa.******.com/__cypress/runner/cypress_runner.js:65727:11)
```

What we discovered after inspecting the video recording of the test (thank you so much for this !), is that the assertion failed because some pending XHR requests from our app were still fetching the data needed for the assertion. Although debugging was made pretty easy with the presence of video recordings, having the pending network requests logged at the time of failure would have helped us to understand the root cause much quicker.

### Desired behavior:

Include pending XHR requests (if applicable) in the error log

### Versions

Cypress 3.2.0, running on electron

**Comment by jennifer-shehane** [comment]
You may want to take a look at a couple existing plugins in the meantime of our implementing this:

- @bahmutov's 'failed-log' plugin, https://github.com/bahmutov/cypress-failed-log creates a JSON file of the Cypress 'command log' for review after `cypress run`
- @flotwig's 'log-to-output' plugin, https://github.com/flotwig/cypress-log-to-output prints console.log, console.info, and console.error statements directly in the stdout.

You may be able to create some logging in combination with these plugins to help out.

**Comment by seb-lean** [comment]
Is this still the recommended approach? 
My use case: I am using Cypress in CI and occasionally the backend is flakey, but the reported failure is something like "Thing not there". I have to go hunting around in the screenshots to see that in fact an endpoint was 500ing and that was the true cause of test failure. 
It would be very helpful to have that bubble up to the spec report.
