### ISSUE TITLE
Autorun after file change doesn't work on OSX

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#422]
When saving the test file, the test should rerun. However, it isn't even rebuilding my JS files, so any change such as adding a `.only` isn't reflected in the UI. I have to restart Cypress to see my JS changes.

This is some kind of regression bug we discussed on Gitter which I do not understand totally:
https://gitter.im/cypress-io/cypress?at=5898dc426018ccd6527b1ccd

**Comment by jennifer-shehane** [comment]
Closing. We have made several updates to our file watching since this issue was opened. Please reopen if still occuring.
