### ISSUE TITLE
Show a better error when the AUT navigates to a non-"text/html" Content-Type

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4238]
Currently, if the AUT is navigated (not by `cy.visit()`) to a page that does not have `Content-Type: text/html`, it will show this error:

![CypressError: Cypress detected a cross origin error happened on page load:](https://user-images.githubusercontent.com/1151760/57972631-566daa80-796b-11e9-890e-cb66ee9125a7.png)

It's difficult to diagnose the cause of this error without knowing Cypress internals, so it would be nice if we could show an error related to `content-type` here so that a user knows what's *really* wrong.

**Comment by jennifer-shehane** [comment]
We do have an error specific to when you visit a non `text-html` content-type. 

- See code here: https://github.com/cypress-io/cypress/blob/renovate/chai-3.x/packages/driver/src/cypress/error_messages.coffee#L1020
- Tests here: https://github.com/cypress-io/cypress/blob/renovate/chai-3.x/packages/driver/test/cypress/integration/commands/navigation_spec.coffee#L1386

There must be something unique to your run that is causing it to catch on an earlier point of error or not correctly hitting the content-type error. 

Can you provide a reproducible example of what you ran to get this and any configuration? 😉

**Comment by flotwig** [comment]
@jennifer-shehane :) I think that error is only triggered on a cy.visit to a bad domain, which is the time we verify content-type.

If you submit a `<form>` or click on a link in a test, and that causes the AUT iframe to load a page with, for example, a JSON content type, it will present this error because the HTML injection failed due to content type.

**Comment by flotwig** [comment]
It might be hard/impossible for us to fix because there's not a good way to tell, from the proxy layer, where a request originated - main frame navigation, subresource load, XHR - it has no idea

**Comment by flotwig** [comment]
Server code:

```lang-js
app.get('/form', (req, res) => {
	res.type('html')
	.send('<form action="/post" method="POST"><input type="submit"/></form>")
	.end()
})

app.post('/post', (req, res) => {
	res.type('json')
	.send('this will load, but cypress will fail')
	.end()
})
```

Test code:

```lang-js
cy.get('input[type=submit]')
.click()
```

**Comment by marcelkottmann** [comment]
Maybe this should at least be mentioned as a possible problem in the error message.
