### ISSUE TITLE
new community chat room

### ISSUE THREAD

**Issue by converge** [cypress-io/cypress#4244]
I checked the Gitter Cypress.io channel, and at the moment it has low interactions. What do you think about create/request a new channel at Reactflux (Discord)?

[Reactflux](https://www.reactiflux.com/) has a lot of users and the [Discord](https://discordapp.com/) approach to have a chat room is quite cool.

Let me know your thoughts.

**Comment by mccataldo** [comment]
I've been relying more and more on Github issue comments (sadly?) as a resource and to stay in the loop, mainly because the discussions are more organized. I think regardless of the solution we use, there needs to be a bit more organization by not communicating in one giant channel. Gitter search UX is a nightmare IMO. 
FWIW, I think we should consider Github's [Spectrum](https://spectrum.chat/) chat.

**Comment by converge** [comment]
I like the chat room idea especially to avoid so many open issues

**Comment by jennifer-shehane** [comment]
Our team agrees that the Gitter search is less than ideal. 

We revisit this topic every few months internally, we are open to changing the chat platform, but have never landed on a firm opinion as to the best solution. Any outside input is appreciated.

Also, we have an internal link rerouting system so updating the https://on.cypress.io/chat link to another chat platform is not a huge undertaking.

**Comment by jordandlaman** [comment]
My team definitely supports the discord option.  I can see that channel having the same problems most "community" support channels have.  It takes a concerted moderator presence to whittle down static and dedicated members that have enough knowledge to help.  Most of the time its just help wanted with crickets coming back.

**Comment by valasek** [comment]
My team would appreciate a forum. Questions and answers can be linked from outside in an SEO friendly way. As a side effect you have more traffic on your domain + strong tool to support the ever-growing cypress.io community.

Forums like Discourse provides even hosting for OSS for free - https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/.

**Comment by flotwig** [comment]
@valasek We don't have a forum (yet), but there is a good amount of activity on our StackOverflow tag: https://stackoverflow.com/questions/tagged/cypress

**Comment by Manuel-Suarez-Abascal** [comment]
Do you have an update in the new community chat proposal? I think that either a discord channel or a forum will be a huge improvement. The current chat support is glitter is not very good.

**Comment by quantuminformation** [comment]
Discord is a no brainer.

**Comment by sainthkh** [comment]
@jennifer-shehane We now have Github discussions and we introduce them in the issue template. I guess we can safely close this issue.

**Comment by jennifer-shehane** [comment]
Yes, as @sainthkh mentioned, there is a new Discussions tab in GitHub. This is a beta feature in GitHub still, but we hope this will be more helpful in creating threaded, searchable discussions so y'all can get answers to your questions more quickly from the community. 👉 https://github.com/cypress-io/cypress/discussions

For now, I'll close this issue. 

We'll consider reopening this issue if we change direction in how we offer a community forum or if there are enough comments here expressing that Discussions is not a great solution.

**Comment by corysimmons** [comment]
Discord link on https://www.cypress.io/support/ doesn't work.

**Comment by rmmanseau** [comment]
new link is here https://discord.gg/cMjUZg7
