### ISSUE TITLE
Blank page & Timed out waiting for the browser to connect. Retrying...

### ISSUE THREAD

**Issue by Mattensor** [cypress-io/cypress#4246]
Hey there,
I'm having a little difficulty running Cypress and am looking for some help :)

When I run `npx cypress open` and attempt to run the suite using electron 59 or chrome 74 I get a blank page. When I check network requests for the page the html and cypress runner loads fine but the upgrade to web socket does not respond.

When I run `npx cypress run` this is what I get

```
Timed out waiting for the browser to connect. Retrying...
Timed out waiting for the browser to connect. Retrying again...
The browser never connected. Something is wrong. The tests cannot run. Aborting...

  (Results)

  ┌─────────────────────────┐
  │ Tests:        0         │
  │ Passing:      0         │
  │ Failing:      1         │
  │ Pending:      0         │
  │ Skipped:      0         │
  │ Screenshots:  0         │
  │ Video:        true      │
  │ Duration:     0 seconds │
  │ Spec Ran:     signup.js │
  └─────────────────────────┘
```
I've tried reinstalling cypress a number of times and the Cypress tests run fine on other developers machines.

Node version v10.15.3
Npm version 6.4.1
Cypress Version 3.2.0
Mac OS Mojave 10.14.4

any suggestions or ideas would be great!

**Comment by bahmutov** [comment]
Can you try cypress v3.3.0 please? It solves a lot of proxy issues

**Comment by Mattensor** [comment]
I just upgraded to 3.3.0, still having the same issue

**Comment by jennifer-shehane** [comment]
@Mattensor Sorry to hear it's not connecting. 

Can you provide a reproducible example that we can run? It likely has something to do with the url you are attempting to visit during `cy.visit()` (can email url to support@cypress.io if you do not want public).

Also a screenshot of the 'blank page' on `cypress open` would be helpful. Can you make sure to open the devtools on screenshot to see any errors?

During `cypress open` - print DEBUG logs and paste here also: https://on.cypress.io/debugging#Print-DEBUG-logs

**Comment by Mattensor** [comment]
Thanks so much for your help @jennifer-shehane . 

I have some screenshots for you. It seems the websocket upgrade request is timing out, and it's not even getting to my actual cypress tests.

![Screen Shot 2019-05-23 at 7 46 34 am](https://user-images.githubusercontent.com/10224902/58211370-19b8ff00-7d2f-11e9-85f2-469ad994c90d.png)
![Screen Shot 2019-05-23 at 7 45 35 am](https://user-images.githubusercontent.com/10224902/58211385-250c2a80-7d2f-11e9-8204-cb3a97f8dca2.png)
![Screen Shot 2019-05-23 at 7 45 51 am](https://user-images.githubusercontent.com/10224902/58211390-29d0de80-7d2f-11e9-87cc-b85b358b1057.png)

Any help you can give would be really appreciated :)

**Comment by tijnster** [comment]
Facing the same issue.. Electron locally works fine, when trying remote from gitlab CI it cannnot connect..

**Comment by jennifer-shehane** [comment]
@tijnster I believe your issue is likely different since it is isolated to GitLab CI run. Could you open a new issue with as much information as possible?

@Mattensor We've seen some similar issues in the past, which they were able to resolve through some debugging or they never provided a way to reproduce. 
- Clearing app data solved it - https://github.com/cypress-io/cypress/issues/2017#issuecomment-419655002
- Issue is hosts file - https://github.com/cypress-io/cypress/issues/680#issuecomment-331217511

Can you try some of our troubleshooting techniques? Logging [DEBUG logs](https://on.cypress.io/debugging#Print-DEBUG-logs) or [clearing App Data](https://on.cypress.io/debugging#Clear-App-Data)? 

Are you behind a proxy? Have you [configured the proxy](https://on.cypress.io/proxy-configuration)?

**Comment by tijnster** [comment]
@jennifer-shehane  Sure, will do!

**Comment by Mattensor** [comment]
When I run cypress with debug here is what I get

```
cypress:server:server Got CONNECT request from localhost:55871 +21s
  cypress:https-proxy Writing browserSocket connection headers { url: 'localhost:55871' } +21s
  cypress:server:server HTTPS request does not match URL: https://localhost:55871 with props: null +0ms
  cypress:https-proxy Making connection to localhost:55871 +1ms
  cypress:network:connect received error on connect, retrying { iteration: 0, delay: 0, err: { Error: connect ECONNREFUSED ::1:55871 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ECONNREFUSED', errno: 'ECONNREFUSED', syscall: 'connect', address: '::1', port: 55871 } } +894ms
```

I have cleared App data & the same problem still persists.

**Comment by saas2813** [comment]
I got logs similar to these. The problem was that my

    /etc/hosts

file did not include a line:

    127.0.0.1 localhost

**Comment by mcntsh** [comment]
@Mattensor did you ever get a solve for this? I'm facing the exact same issue.

**Comment by Mattensor** [comment]
I needed to include 127.0.0.1 localhost in my host file
