### ISSUE TITLE
As a tester I want to run a test script multiple times with different data from a table sheet So I can test the app with multiple cases

### ISSUE THREAD

**Issue by thanhphuocdang** [cypress-io/cypress#4251]

**Comment by converge** [comment]
You're free to do that in this way, what issue are you facing?

I would suggest using https://www.npmjs.com/package/faker to generate fake data.

**Comment by bahmutov** [comment]
Check out "Dynamic tests" recipe https://github.com/cypress-io/cypress-example-recipes#fundamentals which shows how to create multiple tests from data.

**Comment by thanhphuocdang** [comment]
Many thanks, you all.
