### ISSUE TITLE
Cypress 3.3.0 .should('have.focus') does not work

### ISSUE THREAD

**Issue by jevors** [cypress-io/cypress#4265]
## Current behavior:
In issue #97 the behaviour for have.focus is implemented. As @Bkucera described in [this specific edit](https://github.com/cypress-io/cypress/issues/97#issuecomment-457388270) it should be possible to make user of .should('have.focus'). But that doesn't work with 3.3.0, usage results in:

> CypressError: The chainer: 'focus' was not found. Could not build assertion.

### Desired behavior:

Be able to use .should('have.focus')

### Versions

Cypress: 3.3.0
Chrome: 74
Electron: 61

**Comment by Bkucera** [comment]
@jevors thanks for the heads up, somehow it was not actually merged from the 3.3.0 feature branch: https://github.com/cypress-io/cypress/compare/v3.3.0

**Comment by verheyenkoen** [comment]
I guess it would be useful to update the 3.3.0 changelog removing this feature.
