### ISSUE TITLE
Running cy.visit a second time gives out a 404 for a functioning page

### ISSUE THREAD

**Issue by andrei1015** [cypress-io/cypress#4269]
### Current behavior:

I'm in the second `describe`. I've already done stuff, and since I am still logged in, I would like to do the test in another place. Using `cy.visit`, passing the correct URL. When the runner reaches that `describe`, it says the page can not be found. Clicking the URL it says can not be found opens the page ok in another tab. 

### Desired behavior:

It should load the page. The page is there and only cypress thinks it can not be found.

### Steps to reproduce: (app code and test code)
```js
describe('visit', () => {
  before(() => {
    cy.visit('')
    cy.loginAsAdmin()
  })
  describe('change page', () => {
    it('Opens staff page', () => {
        cy.visit('admin/staff/create')
    })
  })
})
```

That's literally it. I go to the login page, perform the login, then just want to change the page.

### Versions
3.3.0

**Comment by andrei1015** [comment]
seems to work if you add `{failOnStatusCode: false}` to the visit.

**Comment by jennifer-shehane** [comment]
`before` hooks only run once. If you have any state (localStorage, cookies, etc) set during the `cy.loginAsAdmin()`, this will be cleared in between each test. You'll want to move these commands into a `beforeEach`.
