### ISSUE TITLE
Cypress does not work in airplane mode or without network

### ISSUE THREAD

**Issue by digitaldrummerj** [cypress-io/cypress#4279]
### Current behavior:

When trying to run Cypress test without network or in airplane mode, the test window just shows a blank solid white screen and never brings up the tests. The website works just fine locally without network when I run everything locally.

![airplane](https://user-images.githubusercontent.com/708423/58142621-b7f87800-7bfc-11e9-9009-4f350d9fb966.png)

### Desired behavior:

Successfully launch and run the tests even without network or in airplane mode.

![cypress success](https://user-images.githubusercontent.com/708423/58143294-28a09400-7bff-11e9-84e9-a20a5b7dd4d7.png)

### Steps to reproduce: (app code and test code)

1. Clone [https://github.com/digitaldrummerj/angular-tutorial-code](https://github.com/digitaldrummerj/angular-tutorial-code)
1. cd into angular-tutorial-code
1. Checkout branch chapter-ui-tests (`git checkout chapter-ui-tests`)
1. run `npm install`
1. install Angular CLI (`npm install -g @angular/cli`)
1. run `ng serve`
1. run `npx cypress open`
1. click the "run all specs" button
1. all test should pass
1. close Cypress Chrome window
1. disconnect network or turn on airplane mode
1. click the "run all specs" button
1. the Cypress Chrome window should now just be a blank white window

### Versions

Windows 10.0.17134
Chrome 74
Cypress 3.2.0

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
