### ISSUE TITLE
Add link to easily find a cypress command in user's source code

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#4285]
### Current behavior:

Currently when clicking a command in the cypress test side panel, it will log it to the console like so: 
![image](https://user-images.githubusercontent.com/2730609/58212973-6fe16000-7ca5-11e9-98e1-17025aa4c80b.png)

### Desired behavior:

If possible I think it would be super useful to be able to jump to the line of user source code that caused that cypress command to be run. Perhaps something like: 
```
Source: http://localhost:3030/__cypress/tests?p=cypress/integration/DesignEditor/DesignInspector/binDetails.js-177-LINE_NUMBER_HERE
```

Often I find I spend a lot of time trying to figure out which part of my code spawned a given cypress command. 

Let me know if that makes sense and if it is a plausible request. Seems like it should be 😄 and would be a big win!
Thanks!

**Comment by jennifer-shehane** [comment]
This is a part of our error improvements - much of the code has already been written to allow for this, seeing the code exactly where the command ran. https://github.com/cypress-io/cypress/issues/3762 Please feel free to comment any more feedback in that issue.
