### ISSUE TITLE
Timeout waiting for the browser to connect.. On gitlab CI

### ISSUE THREAD

**Issue by tijnster** [cypress-io/cypress#4289]
### Current behavior:

When I run my test locally it works fine with Electron. When I try to run my tests from gitlab CI, I am getting the following error:

![image](https://user-images.githubusercontent.com/34685850/58237008-707d0380-7d44-11e9-8cdf-9ac62d7debd3.png)

### Desired behavior:

The desired behavior is that my tests will run on gitlab CI the way they run on my local machine.

### Steps to reproduce: (app code and test code)

![image](https://user-images.githubusercontent.com/34685850/58237119-a6ba8300-7d44-11e9-811a-1ef0c08d9bd9.png)

![image](https://user-images.githubusercontent.com/34685850/58237155-b89c2600-7d44-11e9-955b-5ee732b9569f.png)

![image](https://user-images.githubusercontent.com/34685850/58237180-c782d880-7d44-11e9-895e-043a80381158.png)

### Versions
Cypress V 3.3.0

**Comment by jsmithmg** [comment]
Not sure if it matters, but I was under the impression configs were comma delineated.

Have you tried adding a comma after the url? 
`cypress run --config baseUrl=https://www.anwb.nl,pageLoadTimeout=80000",`

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
