### ISSUE TITLE
Improve driver build process

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#429]
* Remove Bower
* Browserify
* Replace underscore with lodash
* Upgrade bluebird?
* Upgrade chai
* Use node EventEmitter
  - Change `trigger` to `emit`
  - Implement `emitThen` method

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
