### ISSUE TITLE
Too much UI tests causing browser to disconnect Cypress Google Chrome Extension

### ISSUE THREAD

**Issue by VandendriesscheWard** [cypress-io/cypress#4290]
### Current behavior:
Browser times out when running 6 or more tests.
The tests are pretty heavy to run.

Google chrome:
![timeout](https://user-images.githubusercontent.com/26407179/58238966-7d035b00-7d48-11e9-99b2-5a822c3996aa.png)
(It is in Dutch, but it basicly says something went wrong).
Electron:
![timeout2](https://user-images.githubusercontent.com/26407179/58238984-842a6900-7d48-11e9-8c2f-854861607c3d.png)

### Desired behavior:
Able to run 6 or more UI tests.

### Steps to reproduce: (app code and test code)
Make 6 tests. They are pretty heavy because they log in and logout a few times during the multiple tests.
Can't publish any code.

### Versions
Version 3.2.0
Windows 10
Google Chrome & Electron
16GB Ram

**Comment by jennifer-shehane** [comment]
Similar issues: https://github.com/cypress-io/cypress/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22topic%3A+aw+snap+%3Aslightly_frowning_face%3A%22

We'll need a specific reproducible example to address this. We also don't recommend running a large number of test files in interactive mode using the 'Run all tests' mode. Interactive mode is used for active development and debugging - use `cypress run` to run a large suite of tests. https://github.com/cypress-io/cypress/issues/1586

**Comment by VandendriesscheWard** [comment]
> Similar issues: https://github.com/cypress-io/cypress/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22topic%3A+aw+snap+%3Aslightly_frowning_face%3A%22
> 
> We'll need a specific reproducible example to address this. We also don't recommend running a large number of test files in interactive mode using the 'Run all tests' mode. Interactive mode is used for active development and debugging - use `cypress run` to run a large suite of tests. #1586

Ok, I didn't know that.
Everything is running now smoothly without any time outs.

Thank you!
