### ISSUE TITLE
Not able to upload jpg image in cypress

### ISSUE THREAD

**Issue by gitsachin** [cypress-io/cypress#4294]
### I am trying to upload a jpg file using cypress and this is that i have tried so far

I have install plugin cypress-file-upload
I have import this  import cypress-file-upload in ./cypress/commands.js

const fileName = 'img112.jpg';
        cy.fixture(fileName, 'base64').then(fileContent => {
             cy.get('input[type="file"]').upload(
                { fileContent, fileName, mimeType: 'image/jpg' },
                { subjectType: 'input' },
                );
        });

Here is my HTML Code:
![12345](https://user-images.githubusercontent.com/8189025/58254483-7ac0f100-7d88-11e9-979c-fed9663cd9bb.jpg)

After that I am getting error like - TypeError: cy.get(...).upload is not a function at my end

Node Version: v10.15.3
npm Version : 6.1.0
Cypress Version : 3.3.0

**Comment by flotwig** [comment]
The `.upload` command is not part of Cypress, you have to install a plugin to use it: https://github.com/abramenal/cypress-file-upload

Check out the README there for usage information.

**Comment by pwkip** [comment]
I have the same problem, even after installing the extension and adding `import 'cypress-file-upload';` to my commands.js file. Was anybody able to fix this?

**Comment by Nataniellev1** [comment]
Hello Good day, Everyone. Pls help me with this file upload error. It states:
[cypress-file-upload error]
One or more field is invalid within given file(s).
Please look into docs to find supported "fileOrArray" values

**Comment by Patryk0494** [comment]
I have the same problem, because i don't know where to install 'cypress-file-upload'. There is my file structure on the screenshot below. Someone could help me and tell in which folder i have to install required packages?
![Screenshot from 2021-11-25 09-03-59](https://user-images.githubusercontent.com/74532122/143403119-bbd1ab90-e174-4100-ade6-d7f560dbc908.png)
