### ISSUE TITLE
Screenshot directory names should not contain spec file extensions such as `.js`

### ISSUE THREAD

**Issue by edelgado** [cypress-io/cypress#4297]
### Current behavior:

Screenshots are written to directories that directly match the spec file name (including the extension) which creates confusing directory names that look like files:
```
cypress/screenshots
├── home_spec.js
│   └── home.png
└── login.spec.js
    └── login.png
```

### Desired behavior:

Directory names should not have the `.js` file extension in their name. And for extra credit, an ending `.spec` or `_spec` should also be removed like so:

```
cypress/screenshots
├── home
│   └── home.png
└── login
    └── login.png
```

### Steps to reproduce: (app code and test code)

_n/a_

### Versions

Cypress `3.0.2`

**Comment by ilkkanisula** [comment]
I ran into problems with postcss trying to parse test_spec.js directory as a file. As a workaround I needed to rename this directory not to have .js suffix.

**Comment by jennifer-shehane** [comment]
Closing since this hasn’t had a lot of interest over the years.
