### ISSUE TITLE
DOM Snapshot request/response

### ISSUE THREAD

**Issue by jihan0427** [cypress-io/cypress#4305]
When I point my mouse over the API request above the page snapshot, it will keep switching between request and response. I want it to default to response. How can I do that

**Comment by jennifer-shehane** [comment]
This is not currently supported. You should be able to go to the righthand side, where the application under test is, and click on the 'response' to prevent it from switching back and forth and only focus on the response. 

![](http://g.recordit.co/Lg6l6RBSG4.gif)
