### ISSUE TITLE
Allow optional, configurable exclusion of tests from `cypress open` dashboard.

### ISSUE THREAD

**Issue by kylemh** [cypress-io/cypress#4315]
### Current behavior:
I like clicking the **"Run all specs"** button to quickly run integration tests locally. I have a lot of visual regression tests which always fail in `cypress open` because of the following issues: 
- https://github.com/cypress-io/cypress/issues/2102
- https://github.com/cypress-io/cypress/issues/2175
- https://github.com/cypress-io/cypress/issues/2348
- https://github.com/cypress-io/cypress/issues/3324

With the unfortunate differences in behavior between the two environments, I never run **"Run all specs"** in `cypress open` because many of the tests will fail, I never want them to run in the first place, and they take a long time to run.

### Desired behavior:
Allow developers to optionally configure which tests should be excluded from running in `cypress open` dashboard.

**Comment by mccataldo** [comment]
@kylemh This plugin might help a little bit: [cypress-skip-and-only-ui](https://github.com/bahmutov/cypress-skip-and-only-ui)

**Comment by mccataldo** [comment]
@kylemh ...or this one: [cypress-select-tests](https://github.com/bahmutov/cypress-select-tests)

**Comment by kylemh** [comment]
Looks like those plugins do what I need. Thanks!
