### ISSUE TITLE
document.querySelector returns null for existing element

### ISSUE THREAD

**Issue by kammerer** [cypress-io/cypress#4319]
### Current behavior:

Cypress cannot find an element which exists on the page and is visible. Actually, `document.querySelector` also does not return anything. However, opening DOM inspector fixes the issue.

See screenshot:
  * the first call does not work
  * the second call works - it is made after opening DOM inspector (and nothing else)

![Screenshot from 2019-05-28 15-35-05](https://user-images.githubusercontent.com/14025/58482540-d3b0d080-815e-11e9-8632-e79f7476246b.png)

Not sure if this is the same issue as #1631.

### Desired behavior:

Elements can be found consistently.

### Steps to reproduce: (app code and test code)

Unfortunately, I cannot provide a failing example. The app in question is closed source and I was not able to reproduce the problem. 

### Versions

Cypress 3.3.1, 3.2.0
Chromium 73.0.3683.86 (Official Build) Built on Ubuntu
LinuxMint 18.2 (64-bit)

**Comment by jennifer-shehane** [comment]
It may have something to do with `focus`. Is there any special logic around your navbar involving `focus` events? 

Opening the devtools will cause focus to be given to the devtools instead of your application, which may cause the behavior to change if it involves focus.

Unfortunately, we'll have to close this issue without a way to reproduce it. Even a codepen or a basic index.html + css file that can reproduce the problem will do. We'd need to know what specifically about this element makes it so it *should* be considered visible and why Cypress is failing to see it as visible.

**Comment by kammerer** [comment]
I will try once again to prepare a reproducible example and I will look for special logic around focus events. 
However, I realized now that I skipped important information - the problem is not that `document.querySelector` does not return this one particular element. It does not work at all for this particular page under test (always returns null).

**Comment by bahmutov** [comment]
Tomacz, did you use top level document context when you ran the command the first time and then switched the drop down to “app under test” context and ran the command successfully?

**Comment by lalicari** [comment]
Also running into this issue. I don't have a codepen, but can provide some more information, and can probably make one if it isn't enough.
![querySelector repro](https://user-images.githubusercontent.com/7192558/60514520-a13b4b80-9ca7-11e9-9118-c60ac268b87b.png) The test that's in the screenshot is the following:

```javascript
it('should be able to open the panel', () => {
        cy.visit('/app/cache').then(() => {
            cy.get('[data-list-index="0"] > .ms-DetailsRow > .ms-DetailsRow-fields > [aria-colindex="2"] > .ms-Button').click('center');
            cy.get('#node-name-header').should('contain', 'cloudboi01');
        });
});
```

But then I did something like this:
```javascript
it('should be able to open the panel', () => {
        cy.visit('/app/cache').then(() => {
            cy.get('[data-list-index="0"] > .ms-DetailsRow > .ms-DetailsRow-fields > [aria-colindex="2"] > .ms-Button').click('center');
            const firstNodeId = document.querySelector('[data-list-index="0"] > .ms-DetailsRow > .ms-DetailsRow-fields > [aria-colindex="2"] > .ms-Button').textContent;
            cy.get('#node-name-header').should('contain', firstNodeId);
        });
	});
``` 
and got this
![image](https://user-images.githubusercontent.com/7192558/60517348-8b308980-9cad-11e9-8722-29f309eb7b11.png)

So it just all goes to heck once I start touching the DOM. Still pretty new to this, should I be passing the document into the promise?

**Comment by lalicari** [comment]
Also I found it weird that I had to .then the cy.visit call--am I doing something wrong there maybe?

**Comment by lalicari** [comment]
OOOOOOHHH ok, just needed the contentWindow return from the promise to do contentWindow.document. Docs are great :) https://docs.cypress.io/api/commands/visit.html#Window

**Comment by brian-mann** [comment]
@lalicari 	you are mixing up sync + async code, which will certainly cause you issues as well.

This is documented - included an example of exactly what you want to do here: https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Return-Values

**Comment by lalicari** [comment]
Ah, ok, thanks!
