### ISSUE TITLE
mapbox-gl cannot be tested in Cypress 3.3.1 - "Error: can't serialize object of unregistered class"

### ISSUE THREAD

**Issue by pburkindine** [cypress-io/cypress#4322]
### Steps to Trigger Behavior

 1. Minimal repro available here: https://github.com/pburkindine/mapboxgl-electron/
 2. run `npm run start` and `npm run cy`
 3. cypress test will fail; click on failed XHR calls to see stack trace

* Does not occur in Chrome testing with cypress
* Does not occur in Electron without cypress (e.g., in electron in cypress, `window.location.href="http://localhost:8080"` twice)
* Does not occur in normal use
* Class in question appears to be ArrayBuffer

### Link to Demonstration

https://github.com/pburkindine/mapboxgl-electron/

### Expected Behavior

Cypress test should succeed

### Actual Behavior

Cypress test fails with error "Error: can't serialize object of unregistered class" in the mapbox webworker

** cypress version
3.3.0/3.3.1

**mapbox-gl-js version**:
1.0.0, ref: https://github.com/mapbox/mapbox-gl-js/issues/8287

**browser**:
Electron 61

**Comment by Timopheym** [comment]
I have the same issue!
@pburkindine What workaround did you succeed with?

**Comment by raphael-leger** [comment]
I have the same blocking issue.

Cypress does not run on Electron 61 when a Mapbox map is included in the page.

Everything works well when Cypress runs on Chrome 75.
Using the dependency `react-mapbox-gl` here.

Any workaround would be appreciated.

**Comment by sainthkh** [comment]
I tried this with 5.6.0 + Electron 85. But I couldn't reproduce it. If it's still happening in your case, please open a new issue.
