### ISSUE TITLE
Log In With GitHub Gives Blank Screen

### ISSUE THREAD

**Issue by alexlee-dev** [cypress-io/cypress#4337]
### Current behavior:

Able to click Log In With GitHub, but a blank window appears and never loads the GitHub login. This is behind a corporate proxy, but the proxy configuration has already been set up.

<img width="960" alt="LogIn" src="https://user-images.githubusercontent.com/41493792/58570945-b8d96d00-81ed-11e9-92ea-407547f23c48.png">

<img width="960" alt="LogInBlank" src="https://user-images.githubusercontent.com/41493792/58570948-bbd45d80-81ed-11e9-9310-988322df3840.png">

### Desired behavior:

Ability to log in to GitHub to see the Dashboard Service.

### Steps to reproduce: (app code and test code)

1. Open Cypress v3.3.1
2. Click "Runs" tab.
3. Click LogIn with GitHub.
4. Get new window popup with blank screen.

### Versions

**Cypress**: _v3.3.1_
**OS**: _Windows 10_

**Comment by flotwig** [comment]
Can you share a screenshot of your [proxy settings from Cypress](https://docs.cypress.io/guides/references/proxy-configuration.html#View-proxy-settings-in-Cypress) as well as a copy of the [debug logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) when you try to do this?

**Comment by alexlee-dev** [comment]
@flotwig sure!

**Screenshot of proxy settings:**
<img width="960" alt="proxy settings" src="https://user-images.githubusercontent.com/41493792/58573309-4fa82880-81f2-11e9-82af-64ca8e30eb71.png">

**Debug Logs:**
[loginIssue.log](https://github.com/cypress-io/cypress/files/3233423/loginIssue.log)

**Comment by alexlee-dev** [comment]
@jennifer-shehane I'd love to provide whatever additional information is needed.

I've attached a copy of debug logs. What info can I provide?

**Comment by flotwig** [comment]
@alexlee-dev I've taken a look at the DEBUG logs you provided; unfortunately, there's nothing I can see that would cause this problem. Does GitHub login work for you in 3.2.0?

**Comment by alexlee-dev** [comment]
I'll give it a go on Monday when I'm back at the computer and report back here.

**Comment by alexlee-dev** [comment]
Since I'm behind a proxy, I've been using the CDN to download the latest version and point my `CYPRESS_INSTALL_BINARY` to that .zip. How can I download previous versions in a zip from the CDN? I tried to download the asset from the GitHub releases page, but the file is suspiciously small. @flotwig

**Comment by flotwig** [comment]
@alexlee-dev You should be able to install older versions of Cypress like you would install any project:

`npm i cypress@=3.2.0`

If you don't have `HTTP_PROXY` environment variables set up, you'll need them so that `npm install` can download the Cypress binary correctly. [Here are some instructions for doing that on Windows.](https://docs.cypress.io/guides/references/proxy-configuration.html#Set-a-proxy-on-Windows)

Failing that, older versions are available from the [download server at certain URLs](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Download-URLs). Try https://download.cypress.io/desktop/3.2.0?platform=win32

**Comment by alexlee-dev** [comment]
@flotwig Thanks. Yeah just using `npm i cypress@whatever` even with the `HTTP_PROXY` and `HTTPS_PROXY` set up doesn't work for me for whatever reason. 

The extra bit on the CDN url is great though. Thank you. Will report back if `3.2.0` allows me to log in.

**Comment by alexlee-dev** [comment]
`v3.2.0` does not seem to read my `HTTP_PROXY` / `HTTPS_PROXY` environment variables like `v3.3.1` does. When I click the "Runs" tab, it times out trying to contact the api.

<img width="800" alt="timeout" src="https://user-images.githubusercontent.com/41493792/58832601-2299b280-8604-11e9-9d4c-529a05c7e3a1.png">

**Comment by flotwig** [comment]
Proxy support was added in 3.3.0, though some user's environments mean that a proxy is not strictly required to access the Internet, which is why downgrading sometimes appears to fix proxy issues. Looks like it didn't help here.

**Comment by flotwig** [comment]
@alexlee-dev 	Try it without a proxy configured if there is any way to reach the Internet without a proxy on your computer. I'm fairly sure the issue lies somewhere in there.

**Comment by alexlee-dev** [comment]
Unfortunately, there is no way for me to access the internet without a proxy on this computer. (Super proxied work setup)

**Comment by alexlee-dev** [comment]
So far, I've been able to see that even when the proxy is configured and it lets me get to the "Runs" section, images are not loaded. If I force the `devTools` option to `true`, I see the failing network requests for the images with the error: `net::ERR_NO_SUPPORTED_PROXIES`.

Still digging...

**Comment by flotwig** [comment]
Could be related to this: https://github.com/electron/electron/issues/12443

Does your proxy server require auth in the URL? `http://user:pass@proxyserver.com...`

**Comment by alexlee-dev** [comment]
I don't believe so, because I've been able to use the proxy with other applications fine with no authentication in the url. `http://proxyserver.com:portNumber`

**Comment by alexlee-dev** [comment]
Does anyone know if having `localhost` in the proxy bypass list would be causing this? i.e. does Cypress make any calls to localhost in order to hit the Cypress API? If it wasn't going through the proxy, that might do it.

**Comment by flotwig** [comment]
`localhost` should always be in `NO_PROXY`, but that shouldn't be causing this issue anyways since this doesn't rely on `localhost` being reachable.
