### ISSUE TITLE
Angular PrimeNG autoComplete does not work with Cypress type

### ISSUE THREAD

**Issue by stephanj** [cypress-io/cypress#4339]
### Current behavior:

I'm using the (Angular) PrimeNG autocomplete component and I'm unable to inject text via the type() statement.  As a result I'm unable to invoke the auto-complete form logic. 

The e2e statement:

```
    cy.get('#tag_field').click()
    cy.get('#tag_field').type('c')
```

And the Cypress output :

```
CypressError: cy.type() failed because it requires a valid typeable element.

The element typed into was:

  > <p-autocomplete id="tag_field" name="tag" class="ng-tns-c12-13 ng-untouched ng-pristine ng-invalid ui-inputwrapper-focus" ng-reflect-required="true" ng-reflect-multiple="true" ng-reflect-name="tag" required="">...</p-autocomplete>

Cypress considers the 'body', 'textarea', any 'element' with a 'tabindex' or 'contenteditable' attribute, or any 'input' with a 'type' attribute of 'text', 'password', 'email', 'number', 'date', 'week', 'month', 'time', 'datetime', 'datetime-local', 'search', 'url', or 'tel' to be valid typeable elements.
```

### Desired behavior:

Use ` cy.get('#tag_field').type('c')` or another command to inject an auto-complete value.

### Steps to reproduce: (app code and test code)

You can see a PrimeNG auto-complete component in action @ https://www.primefaces.org/primeng/#/autocomplete 

### Versions

Cypress v3.3.1

**Comment by amirrustam** [comment]
Hi @stephanj, nice talking to you again. 

I quickly reproduced this locally. The important thing to look at is the *actual* rendered HTML of `p-autocomplete`:

```js
<p-autocomplete _ngcontent-acl-c0="" class="ng-tns-c12-13 ng-untouched ng-pristine ng-invalid ng-tns-c1-0" name="tag" ng-attr-id="tag_field_1" ng-reflect-multiple="true" ng-reflect-name="tag" ng-reflect-required="" required="">
<span class="ng-tns-c1-0 ui-autocomplete ui-widget" ng-reflect-ng-class="[object Object]">
<!--bindings={
  "ng-reflect-ng-if": "true"
}-->
<input aria-autocomplete="list" aria-haspopup="true" autocomplete="off" role="combobox" class="ng-tns-c1-0 ui-inputtext ui-widget ui-state-default ui-corner-all ui-autocomplete-input ng-star-inserted" ng-reflect-ng-class="ui-inputtext ui-widget ui-stat" type="text" required="" aria-expanded="false" aria-activedescendant="p-highlighted-option" aria-required="">
<!--bindings={}-->
<!--bindings={}-->
<!--bindings={}-->
<!--bindings={
  "ng-reflect-ng-if": "false"
}--></span>
</p-autocomplete>
```

So the *true input box* is nested 2 levels deep, and `cy.type` needs to receive a real input box drive. There are two ways test this input box:

1. Click and focus into the input box:
```js
cy.get('#tag_field').click().focused().type('Devoxx is awesome!')
```

2. Purely rely on element selectors:
```js
cy.get('#tag_field input').type('Devoxx is awesome!')
```

Here is the final result:
<img width="1641" alt="Screen Shot 2019-05-29 at 5 00 39 PM" src="https://user-images.githubusercontent.com/334337/58591011-5dca6900-8233-11e9-9066-0ed37725ef1f.png">

Hope that helps 🙂

**Comment by amirrustam** [comment]
Stephan followed up with me on Twitter. Closing this issue.
