### ISSUE TITLE
Improve tone of error messages

### ISSUE THREAD

**Issue by kentcdodds** [cypress-io/cypress#434]
<img width="485" alt="screen shot 2017-02-18 at 11 57 19 pm" src="https://cloud.githubusercontent.com/assets/1500684/23100158/eea6848a-f636-11e6-9a9f-01435d138bb3.png">

This error message feels a little passive aggressive. It seems to be placing blame on me, the developer (where it probably belongs), but I think that it could be worded in a more friendly/helpful tone. I've found that to be one of the things many developers love about tools they use. Where the communication style of the tool they're using is one of helpful friendliness, rather than assigning blame.

This is more of an ongoing thing than a single issue. Not sure when you can say this issue is "closed" :-/

**Comment by tdelam** [comment]
The error is great. In my opinion it's straight forward and very helpful. Maybe freehugs.org?

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this considering it should be an ongoing thing :)

Congrats on 1.0.0!
