### ISSUE TITLE
Cypress records videos even if videoUploadOnPasses is true or false

### ISSUE THREAD

**Issue by BilalRahaoui** [cypress-io/cypress#4345]
1/Open cypress.json
2/add new key/value couple : "videoUploadOnPasses" : false
3/run project using npm run cypress:run
4/Check cypress/videos folder
5/Videos are recorder whatever test pass or fail

**Comment by jennifer-shehane** [comment]
The `videoUploadOnPasses` only controls the *uploading* of videos, not the *recording*

>Whether Cypress will process, compress, and upload videos to the Dashboard even when all tests in a spec file are passing. This only applies when recording your runs to the Dashboard. Turn this off if you’d like to only upload the spec file’s video when there are failing tests.
>
>https://on.cypress.io/configuration#Videos

If you want to turn off video recording altogether, pass `video: false` to your config. 

If you want to only record videos on failure, then you're looking for this feature request: https://github.com/cypress-io/cypress/issues/2522
