### ISSUE TITLE
Not redirecting to appropriate link when navigating to site.

### ISSUE THREAD

**Issue by mohammedroni4** [cypress-io/cypress#4348]
I'm facing issue while navigating to site directly via sub-links: for instance:
In `cypress.json`, I'm using `baseUrl: http://google.com`, and then on actual test page, I'm using `cy.visit('/signIn.html)`

but it seems like its not redirecting me to Sign in page.
it stays in default homepage when it redirects such as: 'http://google.com

**Comment by jennifer-shehane** [comment]
If your `baseUrl` is formed like `http://google.com`, this will likely lead to an initial redirect (since it is missing the `https` and the subdomain. This may be causing the issue with it then not redirecting to the `/signIn.html`. 

We will need more information provided to investigate this. 

Can you provide the test code, a screenshot, anything? We'll have to close without enough information to reproduce this 'bug' ourselves.

**Comment by mohammedroni4** [comment]
The above comment was needed for the production version, but my original issue is testing it in local

So in cypress.json I'm using my http://localhost:3000 and then im using cy.visit('/path/')
I get error with undefined. Ive talked to many people it seems like but no solution...

<img width="1823" alt="Screen Shot 2019-05-31 at 10 27 22 AM" src="https://user-images.githubusercontent.com/13221629/58723488-093c0080-838f-11e9-976c-15face75cc6d.png">

**Comment by mohammedroni4** [comment]
code snippet I have tried using the cy.request as well nothing really helps.
<img width="464" alt="Screen Shot 2019-05-31 at 12 42 36 PM" src="https://user-images.githubusercontent.com/13221629/58730658-9be59b00-83a1-11e9-90fe-adbc2e8554dc.png">
<img width="389" alt="Screen Shot 2019-05-31 at 12 42 31 PM" src="https://user-images.githubusercontent.com/13221629/58730659-9be59b00-83a1-11e9-9adb-dde6aaba7573.png">

**Comment by flotwig** [comment]
@mohammedroni4 Your server is not sending a `Content-Type: text/html` header with responses. This is the same issue as #1727, the workaround should be in the next release.

**Comment by mohammedroni4** [comment]
@flotwig Alright do you happen to know when is the next release?

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/4321, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
