### ISSUE TITLE
Investigate possible slowness in `getFirstWorkingFamily`/`cy.visit()`

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4349]
https://github.com/cypress-io/cypress/blob/943c578a0b6e459044adc7c1ecfe98349645f188/packages/network/lib/agent.ts#L161-L169

This can add up to a second to the initial request to a domain, and we need to double-check that this is all network latency and there's nothing untoward going on here.

**Comment by flotwig** [comment]
Duplicate of #4313

**Comment by flotwig** [comment]
Is this actually happening? Got lost in the blur of other performance changes.

**Comment by jennifer-shehane** [comment]
Closing as resolved in [3.3.2](https://on.cypress.io/changelog#3-3-2)

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
