### ISSUE TITLE
cy.readFile("path-to-file") failed because the file does not exist, even though it does

### ISSUE THREAD

**Issue by leichteckig** [cypress-io/cypress#4352]
Hello! :) `cy.readFile` doesn't seem to find files at a given, correct path anymore. I noticed this behavior using `cypress-dark` plugin and my own theme for the test runner, details as following.

### Current behavior:
When using dark theme from `cypress-dark` plugin and my own theme I get the following error message right at the beginning of every test:

![image](https://user-images.githubusercontent.com/29896429/58693548-4ef9c880-8391-11e9-8c58-4da22622ee51.png)
```
CypressError: Timed out retrying: cy.readFile("/node_modules/cypress-dark/src/dark.css") failed because the file does not exist at the following path:

/node_modules/cypress-dark/src/dark.css

Because this error occurred during a 'before all' hook we are skipping all of the remaining tests.
```

Actual file and path itself are correct and work as soon as I rollback to 3.3.0. I can reproduce that behavior as I use `cy.readFile` in my tests as well. 

### Desired behavior:

I would love to use `cy.readFile` as before to use dark- and my custom theme for Cypress' test runner.

### Steps to reproduce: (app code and test code)

- Install version 3.3.1
- Easiest way: Use dark theme from `cypress-dark` plugin, set `"useDarkTheme": true,` in cypress.json and run any test
- Alternative: Use the following command anywhere in your test:
```
cy.readFile('./a/valid/path-to-file.spec.js');
```

### Versions
- Cypress 3.3.1, older versions are not affected
- Browser: Chrome 74
- Operating system: Manjaro linux (local development), Cypress on docker image `cypress/browsers:node8.15.1-chrome73`

Thank you very much in advance! :heart:

**Comment by jennifer-shehane** [comment]
Cypress cannot find this with the trailing `/` in front of `node_modules`, so using `cy.readFile("node_modules/cypress-dark/src/dark.css")` should work as a workaround today until a new Cypress fix goes out.

This is a bug and has nothing to do with node_modules, so can be replicated with any directory relative to the projectRoot. 

With my file being present at `projectRoot/cypress/fixtures/example.json`, there are the following differences in the versions.

## 3.3.0

```
it('Reads file', () => {
  cy.readFile('cypress/fixtures/example.json')   // passes
  cy.readFile('/cypress/fixtures/example.json')  // passes
})
```


## 3.3.1

```
it('Reads file', () => {
  cy.readFile('cypress/fixtures/example.json')   // passes
  cy.readFile('/cypress/fixtures/example.json')  // fails
})
```

Looking through the commits between 3.3.0 and 3.3.1, I picked out *this little commit* https://github.com/cypress-io/cypress/pull/4241/commits/c75a643d42c1ae36c80111bf8e2d9556f06c60e3

Instead of setting the filePath to read/write by calling `path.join(projectRoot, file)` we now call `path.resolve(projectRoot, file)`. 

I'm sure this was expected to cause no changes, but it has. 

- [path.join()](https://nodejs.org/api/path.html#path_path_join_paths) 
	- ✅ `cy.readFile('cypress/fixtures/example.json')`: `/Users/jennifer/Dev/cypress-example-kitchensink/cypress/fixtures/example.json`
	- ✅ `cy.readFile('/cypress/fixtures/example.json')`: `/Users/jennifer/Dev/cypress-example-kitchensink/cypress/fixtures/example.json`
- [path.resolve()](https://nodejs.org/api/path.html#path_path_resolve_paths)
	- ✅ `cy.readFile('cypress/fixtures/example.json')` : `/Users/jennifer/Dev/cypress-example-kitchensink/cypress/fixtures/example.json`
	- ❌ `cy.readFile('/cypress/fixtures/example.json')`: `/cypress/fixtures/example.json`

**Comment by jennifer-shehane** [comment]
So, after some discussion, this was determined to be a bugfix and the intended behavior that we want to move forward with. Although it seems to have had unintended consequences. 

`cy.readFile()` will not expect a relative path when starting with `/`

**Comment by aeendale** [comment]
Greetings, 

I am confused on how to resolve this issue. I have cypress 3.8.3 and still get the error below. please advise. 

![image](https://user-images.githubusercontent.com/23197906/75364883-66b39e00-588a-11ea-9ea2-f5408d3a3fdb.png)

**Comment by CypressCecelia** [comment]
Hi @aeendale does removing the first `/` in the file name resolve the issue?

**Comment by aeendale** [comment]
Hi @CypressCecelia, it's not clear where exactly in the project and file I need to make that update.

**Comment by CypressCecelia** [comment]
@aeendale you would update wherever you are using the `cy.readFile()` command containing the path.

**Comment by aeendale** [comment]
@CypressCecelia i am not using that specific command in any of my tests.

**Comment by bahmutov** [comment]
Seems it is coming from cypress-dark plugin. Stop using that plugin for now and / or open an issue there

**Comment by jennifer-shehane** [comment]
https://github.com/bahmutov/cypress-dark plugin

**Comment by sravankotha731** [comment]
cypress version : 9.6.0
When I tried cy.readFile() to read csv file, on cypress runner it's showing reading file but I am not able to get the expected data and also I didn't see any error on gitlab but cy.readFile() working as expected in local.
<img width="298" alt="Screenshot 2023-03-02 at 4 27 45 PM" src="https://user-images.githubusercontent.com/92846662/222409840-57014822-3e6c-42df-9885-6e022a25462c.png">
I am expecting objects inside an array.

**Comment by MuhammadAfnan26** [comment]
@sravankotha731 did you find solution for this issue? facing same issue where path works on local and not in github actionflow.

**Comment by sravankotha731** [comment]
@MuhammadAfnan26 Yes i found the solution for my issue, while splitting the rows I have used this line **const rows = dataCsv.trim().split(/\r?\n/);** .

**Comment by MuhammadAfnan26** [comment]
@sravankotha731 thanks for the reply but I just got confused, I was asking about the path issue?

Like how do you define the path to make it accessible in GitHub and local? 
for example, my code, I want to read file from downloads directory but in github ACTION FLOW it fails and works in local.

```
const fileName = 'cypress/downloads/invoice.csv';

        // Reading the contents of the downloaded CSV file
        cy.readFile(fileName).then((csvContent) => {
            const lines = csvContent.split('\n');
}
````

**Comment by sravankotha731** [comment]
@MuhammadAfnan26 I have used 'utf-8'
cy.readFile('cypress/fixtures/PROD_Master_2024_2.csv', 'utf-8').then(
      (data) => {
        //........
      },
    );

**Comment by MuhammadAfnan26** [comment]
@sravankotha731 did not work for me but thanks for the help, if you could still help, let me know and if you are busy, let it go.
