### ISSUE TITLE
option to disable scroll per command (Auto scroll on click/trigger can break virtual grids)

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/cypress#4356]
### Current behavior:

Cypress click will scroll an element inside a virtual grid to the top.

However in between the scroll and triggering the click, the virtual grid can hear the scroll, then change which dom row corresponds to which data row (usually in virtual grids, in order that mobile scrolling works you have a window of real dom nodes and upon a scroll you move the data and then the y position of the rows so that the user can continue seamlessly scrolling).

This means that day the grid is rows 1-7 and you get 3.. the trigger is executed on the same dom element that was fetched, but because of the scroll it has become a row containing the data in 5.

Because of race conditions, this usually ends up being intermittent depending on if cypress or the scroll listener wins.

### Desired behavior:

I’d love to be able to disable scroll per command or else entirely so it has to be explicit (better I think for an spa)

@Bkucera this is the scenario I mentioned on the Pr

**Comment by lukeapage** [comment]
Oh and workaround is to force every click - for some reason that doesn’t try and scroll. But I’d rather have the visibility checks.

**Comment by jennifer-shehane** [comment]
Can you try to provide a small reproducible example of this please?

**Comment by yuki-93** [comment]
I have the same problem with comboboxes in ExtJS, which are not plain <select> elements. They are kind of overlays which close again when scrolling. force:true doesn't seem to work for me.

**Comment by lukeapage** [comment]
Afaik Force true disables scrolling, so if that doesn’t work, something else is probably going on.
