### ISSUE TITLE
Ignore node_modules when watching files

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#437]
To potentially prevent issues such as https://github.com/cypress-io/cypress/issues/369, only watch the user's source files and ignore `node_modules` (and maybe other directories? https://github.com/novemberborn/ignore-by-default/blob/master/index.js).

**Comment by kentcdodds** [comment]
YES PLEASE!!!!!

**Comment by brian-mann** [comment]
Let's add a configuration option to `cypress.json` to allow users to configure other directories to ignore.

**Comment by kentcdodds** [comment]
That sounds great 👍 anything I can do to help make this happen soon?

**Comment by chrisbreiding** [comment]
I'm afraid this is unlikely to solve your issue, @kentcdodds, or #369 for that matter. When we bundle the files, browserify has to walk the dependency tree and open all the files, whether they are in `node_modules` or not. It's at that point that we're getting the EMFILE error, which is why this is reproducible when running headlessly (where we don't watch the files). 

I still think it's a good idea to implement this, but wanted to make it clear that it won't solve the EMFILE issue.

**Comment by kentcdodds** [comment]
That makes sense. :-(

What doesn't make sense is that my app is actually pretty small and I don't experience this issue when doing things that I would expect to open many more files (like bundling a large app with webpack for example). I'll move discussion over to #369...

**Comment by brian-mann** [comment]
Actually your `faker` lib does require a bunch of files - but we think there's a deeper issue here, one that is not fixed by raising `ulimit`. It's also possible the way Cypress is spawned somehow doesn't respect the `ulimit` property but we'll have to do more research.

Could be that we might have to fork or proxyquire `browserify` to use `graceful-fs` which has `EMFILE` backoff.

We're experimenting to see what we can do...

**Comment by kentcdodds** [comment]
>  It's also possible the way Cypress is spawned somehow doesn't respect the ulimit property but we'll have to do more research.

I think that may be it. When I run:

```
lsof | awk '{print $1}' | uniq -c | sort -rn | head
```

I see Cypress listed there, but it maxes out at around 500 files as far as I can tell...

**Comment by brian-mann** [comment]
Fixed in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).
