### ISSUE TITLE
Running Cypress in headless mode using Electron does not center page when autoscaling

### ISSUE THREAD

**Issue by hvuong-sigma** [cypress-io/cypress#4371]
### Current behavior:

When running Cypress using: `cypress run --env environment=xxx ` - Autoscaling does not center the website which causes certain tests to fail when elements are off screen during headless mode.

Note 1: This passes when using `cypress open --env environment=xxx`
Note 2: Both times tests were triggered using Electron 59 running Cypress 3.1.4

I came to this conclusion because the screenshot when using `run` shows that it's at 57% scale and the image is off screen. However, when I run the test with `open` and resize it to 57%, I can see that the page would shift after <1s and center the page.

### Desired behavior:

Autoscaling works properly when using `cypress run`

### Steps to reproduce: (app code and test code)

1. Write some tests that involves clicking on a button that potentially might be off screen
2. Run the test with `cypress run` using Electron 59

Result:
Page will not center during autoscaling

Expected:
Page will center during autoscaling

### Versions

Cypress 3.1.4
Electron 59
MacOS 10.14.5

Note: This might be an isolated issue with the newest Macbook Pro (2018) and MacOS 10.14.5 since the tests are fine in CI running the same command.

**Comment by hvuong-sigma** [comment]
Another interesting thing is that the tests will pass when connected to an external monitor - super weird.

**Comment by jennifer-shehane** [comment]
Could you please try updating Cypress to 3.3.1 to see if this issue persists? This issue may have already been resolved.

If this issue still persists, we will need a clearer reproducible example - for example, `index.html` of the page that does not scale properly with the test code to demonstrate it. We can't look into it without a way to see and reproduce it ourselves.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by hvuong-sigma** [comment]
@jennifer-shehane 

Actually! This was because in the config, viewport `height` and `width` needs to be `int` instead of `string`.

Example:
```
  "viewportHeight": 900,
  "viewportWidth": 1440,
```

Not sure if this needs to be made more clear anywhere in the docs.

**Comment by jennifer-shehane** [comment]
@hvuong-sigma K, you may want to look into setting up configuration with our [schema file](https://on.cypress.io/intelligent-code-completion#Configuration) to avoid this from happening again. 

Although, it may be nice for us to just accept string values and coerce them in this situation.
