### ISSUE TITLE
scrollIntoView with duration does not work

### ISSUE THREAD

**Issue by MrPickles2009** [cypress-io/cypress#4374]
### Current behavior:

Following the documentation [here](https://docs.cypress.io/api/commands/scrollintoview.html#Scroll-to-element-over-2000ms), I made the following test:

```javascript
it('Should scroll to footer', () => {

	cy.get('footer').scrollIntoView({ duration: 2000 })
})
```

When the test is run I get the following error:
![screenshot](https://user-images.githubusercontent.com/20229190/58828699-056ce000-8614-11e9-906b-e37662a1380c.png)

If I run the test *without* the `duration: 2000` option, the test scrolls as expected but scrolls too fast

### Desired behavior:

The footer should scroll into view over a duration of 2000ms

### Steps to reproduce: (app code and test code)

Add the code above to any js test file

### Versions

Cypress 3.3.1
Windows 10.0.17763
Chrome 61 (Electron)

**Comment by jennifer-shehane** [comment]
Hi @MrPickles2009, did you open the develop tools as indicated in the error message? Could you send a screenshot of the error printed there?

Also, any information about the page / footer you are attempting to scroll into view may be helpful, ideally a reproducible `index.html` that we can run and get the same result. Thanks!

**Comment by MrPickles2009** [comment]
after looking into this in more detail, this isn't an issue with cypress
