### ISSUE TITLE
allow live-reload out of paused debugger

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#4375]
#### what
When chrome is paused on a debugger breakpoint, the filewatching/livereload currently does not refesh changes until you resume execution:

_when chrome is like this, live-reloading doesn't work until you click resume_
![image](https://user-images.githubusercontent.com/14625260/58848301-058cd000-8654-11e9-84a1-a23030781bc0.png)

It would be nice to expose the option to allow file changes to re-run tests even when the browser is paused on a debugger breakpoint

#### how
we could do this by 
- using the `native debugging protocols` to temporarily disable breakpoints and resume from execution until we are able to re-run cypress tests
**or**
- simply doing a hard refresh of the page using the native protocols or extensions API

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
