### ISSUE TITLE
Collect CI environment variable from Concourse CI

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#4376]
### Current behavior:

We don't collect anything from a Concourse CI run - do not even know if they are running within Concourse CI

### Desired behavior:

Need to identify Concourse and pull any useful environment variables for use here: 

https://github.com/cypress-io/cypress/blob/issue-3909/packages/server/lib/util/ci_provider.js

Add environment variables to collect from https://concourse-ci.org/implementing-resource-types.html#resource-metadata

- `$BUILD_ID`
- `$BUILD_NAME`
- `$BUILD_JOB_NAME`
- `$BUILD_PIPELINE_NAME`
- `$BUILD_TEAM_NAME`
- `$ATC_EXTERNAL_URL`

>If the build is a one-off, `$BUILD_NAME`, `$BUILD_JOB_NAME`, and `$BUILD_PIPELINE_NAME` will not be set.

I see quite a few other env variables floating around starting with `CONCOURSE_`, which can probably be used to identify it as a run within Concource CI.

### Versions

Cypress 3.3.1

**Comment by mster** [comment]
I'd love to help contribute! :)

**Comment by jennifer-shehane** [comment]
@mster 	Thanks! We would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.
