### ISSUE TITLE
Simulated copy and paste failure

### ISSUE THREAD

**Issue by 614222611** [cypress-io/cypress#4381]
![企业微信截图_15596342298763](https://user-images.githubusercontent.com/50280980/58860865-ab395100-86df-11e9-8972-9cd802d33489.png)

**Comment by 614222611** [comment]
I can't execute Ctrl + C and Ctrl + V. What's the problem?

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/2386

**Comment by 614222611** [comment]
But my cypress test browser failed to achieve its function. What's the matter, please?

**Comment by jennifer-shehane** [comment]
Copy and paste is not supported yet - how you are doing it. Please follow this issue: https://github.com/cypress-io/cypress/issues/2386
