### ISSUE TITLE
Problem with http-to-https redirects behind corporate proxy

### ISSUE THREAD

**Issue by papb** [cypress-io/cypress#4384]
### Current behavior:

I'm trying to test the following page with cypress 3.3.1:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js"></script>
<script>_.assign()</script>
<script src="//cdn.jsdelivr.net/npm/bluebird@3.5.5/js/browser/bluebird.min.js"></script>
<script>Promise.config({ longStackTraces: true });</script>
```

* I am serving this page under `http://localhost:3000/` (not https!)
* I am behind a corporate proxy in which both `http_proxy` and `https_proxy` have the exact same value of the form `http://username:password@proxy_host:port`. Note that even the `https_proxy` value is `http`, not `https` (I am not sure this matters, but I thought I should give as much potentially relevant information as possible)

### Desired behavior:

It should work, but instead I get the following error:

```
Uncaught TypeError: Promise.config is not a function

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```

### Notes

This indicates that something went wrong when fetching the bluebird script (while the underscore script was fetched fine).

Amazingly, replacing `//cdn.jsdelivr.net` with `https://cdn.jsdelivr.net` makes it work, while replacing with `http://cdn.jsdelivr.net` gives the same error.

Since `http://cdn.jsdelivr.net/` yields a 301 REDIRECT to `https://cdn.jsdelivr.net/`, I thought this redirect was causing the problem. But as it can be seen, the bluebird script was fetched correctly, and `http://cdnjs.cloudflare.com/` also redirects to `https://cdnjs.cloudflare.com/`, so I am lost.

Although I've found this very simple workaround, I thought I should file this issue because, well, fetching with `//` instead of `https://` should work, simply because it works outside cypress. Perhaps this indicates a deeper problem, and other not-so-simple situations might not have this workaround possible.

### Steps to reproduce: (app code and test code)

I couldn't just fork https://github.com/cypress-io/cypress-test-tiny to show the problem because there wouldn't be the corporate proxy issue. But I believe the description above is enough. Let me know if any clarification is needed.

### Versions

* Cypress 3.3.1
* Both Windows and Linux
* Both Electron and Chrome

**Comment by flotwig** [comment]
I'm not able to reproduce the issue in Cypress 3.3.1 on Linux using a proxy with a username and password, it seems to work properly for me:

![image](https://user-images.githubusercontent.com/1151760/58901596-80470100-86cf-11e9-958e-55174118e9b9.png)

Can you share the full `DEBUG` logs from when you experience this issue? It should shed some light on the issue. Instructions can be found here: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

**Comment by papb** [comment]
Sorry, my minimal example was too minimal, my mistake. I missed that `crossorigin="anonymous"` was crucial for the problem to happen. I also forgot to mention that the problem only occurs from `cypress run`, not `cypress open`. When I said that it happens with both Electron and Chrome, I meant `cypress run` and `cypress run --browser chrome` - sorry I wasn't clear.

## Full steps to reproduce

0. Be under a corporate proxy in which both correct `HTTP_PROXY` and `HTTPS_PROXY` have the form `http://username:password@proxy_host:port`

1. Create empty folder, `cd` into it
2. `npm init -y`
3. `npm install cypress@3.3.1`
4. `npx cypress open` just to scaffold the `cypress` folder and then close it
5. Create file `index.html` with the following content:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js" crossorigin="anonymous"></script>
<script>_.assign()</script>
<script src="//cdn.jsdelivr.net/npm/bluebird@3.5.5/js/browser/bluebird.min.js" crossorigin="anonymous"></script>
<script>Promise.config({ longStackTraces: true });</script>
```

6. Remove all `example` tests created automatically and instead add `simple.test.js`:

```js
describe('Weird things happening', function() {
    it('Weird things should not happen', function() {
        cy.visit('http://localhost:8080/index.html');
    });
});
```

7. `npx http-server` to serve on `localhost:8080` (which is the default)

8. `npx cypress run`, and see the error (uses Electron 61 headless):

```
Uncaught TypeError: Promise.config is not a function

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```

### Notes

* Using `npx cypress run --browser chrome` also fails with the same error (uses Chrome 73).

* Strangely, there is no error if `npx cypress open` is used.

* Removing `crossorigin="anonymous"` fixes the problem (but I don't want to do that because I want to check [Subresource Integrity](https://www.srihash.org/). I didn't include the hash in the minimal example because it did not matter.

* I will share the full DEBUG logs once I make sure I have redacted everything which could be sensitive information from it...

**Comment by papb** [comment]
@flotwig - I forgot to ping you. Also thank you very much for the fast response above and for your time. Sorry I took so long to carry on.

**Comment by flotwig** [comment]
Nice, I've gotten it to reproduce in Electron 61, not Chrome 75, though. What version of Chrome are you testing on?

This error appears in console: 
![image](https://user-images.githubusercontent.com/1151760/60464173-cb472c00-9c1b-11e9-898c-98151dacdea9.png)

It looks like `access-control-allow-origin` is not being received for one of the CDN domains for some reason.

**Comment by papb** [comment]
@flotwig - Nice!

I tested with Chrome 73 (mentioned in first post :grimacing:)

Let me know if you need further information. I'm very curious about this!

**Comment by papb** [comment]
@flotwig - Hmm, something clicked in my mind now (11 hours later) - If you saw something in the console, does this mean you reproduced the problem with `cypress open`? Because as I said, I only have the issue with `cypress run`, and there I wouldn't see the console like you posted above...
