### ISSUE TITLE
Cypress error when try to use `cy.deleteEntity` 

### ISSUE THREAD

**Issue by mihaidanuta** [cypress-io/cypress#4392]
In this PR https://github.com/eclecticiq/platform-ui/pull/3074

after we have all tests runned we want to delete the created entity so i got cypress error 
![image](https://user-images.githubusercontent.com/26868437/58967398-c62dc300-87bc-11e9-87d9-f84d59b157f4.png)
after adding `cy.deleteEntity`

This blocks us

**Comment by flotwig** [comment]
Your backend is returning a 404, which causes `cy.request` to fail. If you don't want `cy.request` to fail on a 404, pass `failOnStatusCode: false` as an option, like so:

```
cy.request({
  url: 'blah',
  method: 'DELETE',
  failOnStatusCode: false
})
```
