### ISSUE TITLE
json fixture validation is removing all formatting on values. 

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#44]
I've defined a `cy.fixture("form")`. My form.json file used to look like this:

```json
{
  "item": {
    "id": 129083,
    "instructions": "Inspect equipment to see what their condition is and repair any conditions found.",
    "note": "All equipment seen on site.",
    "requiresAsset": false
}
```

But cypress has reformatted my JSON file to look like below, removing all of the spacing in my values. You should not be doing any formatting on any values in a key:value pair.

```json
{
  "item": {
    "id": 129083,
    "instructions": "Inspectequipmenttoseewhattheirconditionisandrepairanyconditionsfound.",
    "note": "Allequipmentseenonsite.",
    "requiresAsset": false
}
```

**Comment by jennifer-mann** [comment]
It looks like only this fixture was formatted incorrectly. I haven't been able to recreate this behavior, so I'm not sure under what circumstance it does this. It's definitely not reformatting on a simple `cy.fixture("form")` command.

**Comment by brian-mann** [comment]
I will give this bug a few more weeks and a few more users before closing this as "cannot recreate, not actually a bug".

**Comment by brian-mann** [comment]
Closing this as it hasn't occurred anymore and in [`0.12.4`](https://github.com/cypress-io/cypress/wiki/changelog#0124-11192015) there were updates to how fixtures write their data, which may have fixed this edge case (if it was ever an issue).
