### ISSUE TITLE
Question: Backend only testing with Cypress?

### ISSUE THREAD

**Issue by basickarl** [cypress-io/cypress#4409]
This is more of a question. 

```
  1)  Checks to see if server is alive:
     TypeError: Cannot read property 'write' of undefined
      at Context.<anonymous> (http://localhost:38125/__cypress/tests?p=.build/cypress/unit/libs.mqtt.spec.js-246:208:18)
```

I was attempting to do `process.stdout.write` but I notcied that it doesn't detect any of the normal node.js objects, nor when require 'fs' for example. I'm attempting to unit test some of my backend modules with Cypress. Since this can be done with Mocha and that Cypress is built on-top of Mocha, it should be possible to use Cypress for backend only testing in node?

**Comment by jennifer-shehane** [comment]
This answers your question in a roundabout way, in terms of Node vs browser context: https://on.cypress.io/using-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress

You likely want to use `cy.task()` or `cy.exec()` commands basically.

**Comment by basickarl** [comment]
Ok thanks! Found a good example here: https://docs.cypress.io/api/commands/task.html#Read-a-file-that-might-not-exist

**Comment by basickarl** [comment]
@jennifer-shehane I've noticed that this cy.task() increases code maintainability a whole lot when writing backend only modules.

Would it be fair to say that Cypress is a frontend test framework? I'm only seeing more work using Cypress than using only Mocha.

**Comment by bahmutov** [comment]
@basickarl `cy.task` helps your front-end tests check backend systems. For example, it can check if files have been written, database updated, email system has sent an email, etc. Thus it is not a replacement for Mocha. I have more `cy.task` examples here https://glebbahmutov.com/blog/powerful-cy-task/ and in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/server-communication__seeding-database-in-node

**Comment by basickarl** [comment]
@bahmutov Thank you for clarifying that Cypress is not a replacement for Mocha (Why can't it be, since you have mocha under the hood anyway? That would be so awesome! Truly one framework to rule them all)!

I'll have to revert to Mocha then :(.
