### ISSUE TITLE
Unable to get value by id of a readonly input field

### ISSUE THREAD

**Issue by hvuong-sigma** [cypress-io/cypress#4412]
### Current behavior:

When running `cy.get(<element>).should("contain", <value">)`, Cypress will timeout and fail because the value does not exist.

### Desired behavior:

`cy.get(<elementId>).should("contain", <someValue">)` on a `readonly` input field will return its value from `<input readonly="" id=<elementId>" value="someValue"">`

### Steps to reproduce: (app code and test code)

1. Have the following input field: `<input readonly="" id=<elementId>" value="someValue"">`
2. Write a cypress test and include: `cy.get(<elementId>).should("contain", <someValue">)`

### Versions

Cypress 3.1.4
MacOS 10.14.5

**Comment by jennifer-shehane** [comment]
The assertion to use to assert on the value of an input is `have.value`, not `contain`:

```js
cy.get(<elementId>).should("have.value", <someValue">)
```

You're not the first to do this though, there is an issue to also accept the `contain` assertion here: https://github.com/cypress-io/cypress/issues/988
