### ISSUE TITLE
Can't click button to show popup.

### ISSUE THREAD

**Issue by Thanh96** [cypress-io/cypress#4413]
### Current behavior:
POST 204 /Prod/desole
![Screenshot 2019-06-08 16 16 02](https://user-images.githubusercontent.com/29529118/59145064-30d33e80-8a09-11e9-8116-03e72d1d86ac.png)
### Desired behavior:

No error should be found

### Steps to reproduce: (app code and test code)
![Screenshot 2019-06-08 16 21 22](https://user-images.githubusercontent.com/29529118/59145085-7bed5180-8a09-11e9-8290-c9d4fdf4ac4c.png)
### Versions
3.3.1

**Comment by jennifer-shehane** [comment]
Hey @Thanh96, we would need a reproducible example - that we can run completely locally on our machine to verify this is a bug. 

Also, I have some recommendations I think may help after looking at some of this test code:

- We would recommend using [`cy.get(el)`](https://on.cypress.io/get) over using `cy.wrap(el)`, as this will give you Cypress [retry feature](https://on.cypress.io/retry-ability). 
- Reading through the core concepts of Cypress here will also be the most beneficial part of our docs to start with https://on.cypress.io/introduction-to-cypress
- You can also ask questions on to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).

This issue will be closed until you provide a way to reproduce this - and we will reopen if needed. Thanks.
