### ISSUE TITLE
 cy.click() failed because this element is detached from the DOM.

### ISSUE THREAD

**Issue by Thanh96** [cypress-io/cypress#4414]
### Current behavior:
![Screenshot 2019-06-08 18 18 33](https://user-images.githubusercontent.com/29529118/59146569-1d7c9f00-8a1a-11e9-8d11-f11375b75629.png)
### Desired behavior:
No error should be found
### Steps to reproduce: (app code and test code)
![Screenshot 2019-06-08 18 18 53](https://user-images.githubusercontent.com/29529118/59146578-3d13c780-8a1a-11e9-9733-75bacd6fd778.png)
![Screenshot 2019-06-08 18 19 07](https://user-images.githubusercontent.com/29529118/59146583-41d87b80-8a1a-11e9-82e4-a61f6d6d758b.png)

### Versions
3.3.1

**Comment by jennifer-shehane** [comment]
@Thanh96 Please see the comment on your other issue - the same applies here, we need an exact way to run and reproduce. https://github.com/cypress-io/cypress/issues/4413#issuecomment-500288511
