### ISSUE TITLE
visit fails because of long poll

### ISSUE THREAD

**Issue by prontiol** [cypress-io/cypress#4415]
I have a website which uses long poll technique for notifications.
onload is never fired so `visit()` fails to load the page
I tried to block longpoll url using `blacklistHosts` configuration but it only accepts domains
how can I make it work?

**Comment by jennifer-shehane** [comment]
Hey @prontiol, you likely want this feature - the ability to ignore waiting for the `onload` event of your page - https://github.com/cypress-io/cypress/issues/788

If this meets what you are looking for, I would suggest closing this issue as a duplicate and commenting / 👍 in that issue to express your interest.

**Comment by prontiol** [comment]
Closing then.
