### ISSUE TITLE
Add blacklisting of requests made to specific hosts

### ISSUE THREAD

**Issue by stigkj** [cypress-io/cypress#442]
Would be nice to stop requests made to other domains than my own, for example scripts/css loaded from other CDNs.

**Comment by davidperta** [comment]
I was also looking for something like this!  Eg, a way to not send requests to certain domains when running tests (eg NewRelic / Intercom)

**Comment by sanjivsahayamrea** [comment]
Same. Would be nice to have this feature.

**Comment by jennifer-shehane** [comment]
Requires documentation: https://github.com/cypress-io/cypress-documentation/issues/329

**Comment by brian-mann** [comment]
Requests are blocked with `503` response code.

![screen shot 2017-12-14 at 2 28 49 pm](https://user-images.githubusercontent.com/1268976/34010643-776e6550-e0db-11e7-8570-448e62354e6d.png)

The response headers also include the rule that caused the blockage.

![screen shot 2017-12-14 at 2 28 26 pm](https://user-images.githubusercontent.com/1268976/34010650-7f810e1e-e0db-11e7-8b4e-5a6258287135.png)

**Comment by brian-mann** [comment]
Released in [`1.2.0`](https://docs.cypress.io/guides/references/changelog.html#1-2-0).

**Comment by davidperta** [comment]
👏
