### ISSUE TITLE
npm download 404

### ISSUE THREAD

**Issue by silloyd** [cypress-io/cypress#4423]
### Current behavior:

npm install fails to download binary.

### Desired behavior:

Cypress to download.

### Steps to reproduce: (app code and test code)

`npm install cypress`

```
URL: https://download.cypress.io/desktop/3.3.1?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
```

### Versions

Debian 9 - 32 bit

**Comment by flotwig** [comment]
Cypress is not available for 32-bit Linux, only 64-bit.

**Comment by MiniGod** [comment]
For other people that have this issue:

Cypress v3.2.0 appears to be the latest version with a Linux 32bit build.
You can lock the cypress version to `"3.2.0"` if you need it to run / install on 32bit Linux, like I do because of the CI server is 32bit.
