### ISSUE TITLE
Cypress does not catch XHR requests in componentDidMount

### ISSUE THREAD

**Issue by ryan-snyder** [cypress-io/cypress#4425]
### Is this a Feature or Bug?
Bug

### Current behavior:
![Screenshot from 2019-06-10 15-07-18](https://user-images.githubusercontent.com/36665494/59216188-7e7ab300-8b91-11e9-89cd-634c046989c7.png)

### Desired behavior:
Cypress catches all XHR requests, even if they occur in componentDidMount

### Steps to reproduce: (app code and test code)
Clone https://gitlab.com/ryan-snyder/cypress-bug-example and change the URL for the request to whatever you want. Notice how the request is sent by the application but Cypress doesn't catch it at all
### Versions
Cypress: 3.3.1
Chrome: 79
OS: Fedora 30

**Comment by jennifer-shehane** [comment]
You need to define the `cy.route()` before your `cy.visit()`. The `cy.route()` command basically says - "ok Cypress, listen out for this route in the future", then you do the actions that will cause the XHR request so that Cypress finds it and you can wait on it. 

Try the code below.

```js
describe('XHR Demo', () => {
    beforeEach(() => {
		cy.server();
        cy.route('https://webhook.site/e3e5989d-ca4d-456d-b6b3-5d31c6067955').as('request');
        cy.visit('/');
    });

    it('Catches XHR request', () => {
        cy.wait('@request');
    })
})
```

Also, in the future try asking in our [community chat](https://on.cypress.io/chat) first, it can be a quick place to debug problem points.

**Comment by DomDabrowski** [comment]
Hey @jennifer-shehane as far as I can see he did it. Look: 
![image](https://user-images.githubusercontent.com/28804591/59267738-36b86200-8c4b-11e9-946c-2abbe4ec99ba.png)

**Comment by ryan-snyder** [comment]
So the reason I made this ticket is I am seeing this behaviour in my companies actual tests, even with setting up server/route before the visit. That does seem to fix the problem in that example repo. I still believe that this is a bug though. Will continue to try and reproduce it though

![Screenshot from 2019-06-11 08-35-40](https://user-images.githubusercontent.com/36665494/59268827-f09bd800-8c23-11e9-8eba-15487b7d82b3.png)

**Comment by ryan-snyder** [comment]
Nevermind...Didn't realize that our application is using fetch which cypress doesn't support...
