### ISSUE TITLE
UI: "Found undefined alias for 'myalias'" when multiple aliases defined for element

### ISSUE THREAD

**Issue by nitzel** [cypress-io/cypress#4429]
### Current behavior:

When using `.as('myalias')` in a loop the message `Found undefined alias for: 'myalias'` shows up in the UI but it still works (in the console you can see that the alias resolved to two elements).
![](http://0i5.de/cZuU)

The message does not show up when the loop is only executed once.

### Desired behavior:

This message should not appear and irritate the developer :)

### Steps to reproduce: (app code and test code)
```typescript
describe('Test', () => {
  it('test', () => {
    cy.visit('http://google.com');
    for (let i = 0; i < 2; i += 1) {
      cy.get('[name="btnK"]').as('search-button');
      cy.get('@search-button');
    }
  });
});
```

### Versions
|||
|-|-|
|Cypress|3.3.1|
|OS| Windows 10|
|Browsers| Electron headed|

### PS:
Am I using aliases incorrectly here or is this just a misguided message from the UI?

**Comment by jennifer-shehane** [comment]
Oh, yeah, this is a bug. This isn't even concerned with the loop, it seems that when using aliases for elements, if more than 1 is matching, the UI messes up a bit and displays this `undefined` message. 

I believe this was introduced in this PR https://github.com/cypress-io/cypress/pull/2960

Code to reproduce:

```js
it('test', () => {
  cy.visit('http://google.com')
  cy.get('[name="btnK"]').as('search-button')
  cy.get('@search-button')
  cy.get('[name="btnK"]').as('search-button')
  cy.get('@search-button')
})
```

**Comment by aislanmaia** [comment]
I'm having the same bug

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
