### ISSUE TITLE
Cypress failed to start. After recent update? Docker Gitlab CI

### ISSUE THREAD

**Issue by tijnster** [cypress-io/cypress#4430]
### Current behavior:
Hi, as of today our Cypress suddenly does not work anymore from Gitlab CI. It was working perfectly a few days ago. I checked the Dockerhub and saw the last update was 16 hours ago. Could this be something due the update?

I tried using differents images (we used cypress/base:10), also tried cypress/base and cypress/base:latest.

All options returning the same error.

![image](https://user-images.githubusercontent.com/34685850/59268200-7895d800-8c4c-11e9-9b2a-015d3cb1d267.png)

### Desired behavior:
Desired behaviour is running our testset from gitlab CI without any errors.

### Steps to reproduce: (app code and test code)

Run this yml file from CI:
![image](https://user-images.githubusercontent.com/34685850/59268341-cc082600-8c4c-11e9-9cd6-64a9102bed1a.png)

### Versions
OS: linux Debian
Browser: Electron
Cypress version: latest

**Comment by bahmutov** [comment]
Hi @tijnster 

What Cypress image are you using? Are you explicit about `cypress/base:10` - that image has not changed, the update yesterday was a new `cypress/base:centos7-12.4.0`.  All our CI builds seem to be passing just like before.

PS: you should never rely on `:latest` tag, since it can change unexpectedly.

**Comment by tijnster** [comment]
@bahmutov 
Thanks for the reply. I indeed use the cypress/base:10 version. I also never just use base or :latest, that was just to test if that would work. For one strange reason Cypress automatically updated to 3.3.1 (which is odd because I always update manually). I downgraded to 3.2 and now it works again. Thanks anyways!
