### ISSUE TITLE
Add more advanced screenshot clipping options

### ISSUE THREAD

**Issue by mattbrailsford** [cypress-io/cypress#4440]
### Current behavior:

When creating a screenshot you can pass an options object with a clip option which accepts an x, y, width and height setting defining the absolute position that you want the screenshot to be clipped to.

### Desired behavior:

I’d like to see the clipping options be extended to support relative or calculated coordinates. For example, the following could define a screenshot the viewport dimensions but inset by 50px.

```js
cy.screenshot({ capture: “viewport”, clip: { inset: 50 } });
```

Or when screenshotting an element, allow offsetting it’s coordinates to capture 20px of its surrounding area.

```js
cy.get(“#myId”).screenshot({ clip: { offset: 20 });
```

My use case for this is mostly to use cypress for automating documentation screenshots, but I’m sure it could have uses within the testing arena.

**Comment by sebinsua** [comment]
@mattbrailsford My colleague and I might try to implement this. We couldn't decide whether to have a `padding` option, or the `inset`/`offset` idea you put forth. Is there some prior art to the naming you recommended?

**Comment by NMinhNguyen** [comment]
An API like this might be good? https://github.com/GoogleChrome/puppeteer/pull/1692#issuecomment-356142312

**Comment by sebinsua** [comment]
We've raised a preliminary PR #5078.

/cc @mattbrailsford @jennifer-shehane

**Comment by mattbrailsford** [comment]
@sebinsua sorry I never replied to your question, but this looks great. I think basing it on padding is a good solution. Inset could technically be achieved via a negative padding value so sounds like 2 birds with one stone 👍
