### ISSUE TITLE
CypressError: cy.click() failed because it requires a DOM element.

### ISSUE THREAD

**Issue by onkar-bhagwat-zocdoc** [cypress-io/cypress#4444]
### Is this a Feature or Bug?

This is bug

### Current behavior:

Click is not working at all

### Steps to reproduce: (app code and test code)

I am trying to click on first autosuggestion in location box in a mobile web on https://www.zocdoc.com/

Code:
```js
const enterLocationSelectFirstOption = (
		query
	) => {
		let timeout = { timeout: 99999 };
		cy.get('[data-test="takeover-input-input"]').type('19001', {
			delay: 200,
        });
      
		cy.get('[data-test="takeover-input-dropdown"]', timeout)
			.find('[data-test="location-picker-option-0"]', timeout)
			.then($firstOption => {
				console.info(`asserting on ${$firstOption.text()}`);
				cy.wrap($firstOption.text()).should('contain', 'OGONTZ CAMPUS, PA 19001')
				cy.wrap('[data-test="takeover-input-dropdown"] div:nth-child(2)[data-test="location-picker-option-0"]')
					.click({ force: true })
					.then(() => {
						 {
							cy.get('[data-test="takeover-input"]').invoke(
								'attr',
								'data-dropdown-active',
								'false'
							);
						}
					});
			});
	};
```
<img width="1355" alt="Screen Shot 2019-06-12 at 9 30 43 PM" src="https://user-images.githubusercontent.com/46367983/59367830-89cd0a80-8d5a-11e9-9118-75c4e8f87cf1.png">zi

**Comment by jennifer-shehane** [comment]
Hey @onkar-bhagwat-zocdoc, can you provide the html you are trying to click on? 

The error seems to indicate that what you passed to `cy.wrap()` is not returning a DOM element. 

Could you also try using `cy.get()` to get the element? `cy.wrap()` shouldn't be necessary in this example as I see it and won't do some of the automatic checks that `cy.get()` has to query the element.

**Comment by onkar-bhagwat-zocdoc** [comment]
Thanks @jennifer-shehane for revert, I tried with cy.get() also but no luck. Please find attachment which highlighted the area where I want to click. 
<img width="1680" alt="Screen Shot 2019-06-13 at 11 09 32 AM" src="https://user-images.githubusercontent.com/46367983/59406582-51feab00-8dcc-11e9-9060-675379889923.png">
