### ISSUE TITLE
Cypress on fail don't allow to send cy.task request

### ISSUE THREAD

**Issue by a-zharkov** [cypress-io/cypress#4447]
### Current behavior:

When any test failed I would like to send request to JIRA plug-in to mark the test failed. I can do this via back-end using `cy.task()` to send command to JIRA.

### Desired behavior:

I would like to have ability to report errors using `cy.task()`.

### Steps to reproduce: (app code and test code)

```js
Cypress.on('fail', (error, runnable) => {
    const title = runnable.title;
    if (title) {
        const regexp = new RegExp(/(TASK-T\d+) ::(.*)/gm);
        const matches = regexp.exec(title);
        if (matches[1]) {
            cy.task('tm4jFail', { testCaseKey: matches[1], error });
        }
    }
    throw error;
});
```

And cypress return:

```
CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > cy.get()

The cy command you invoked inside the promise was:

  > cy.task()
```

### Versions

Cypress: 3.3.1
OS: MacOS

**Comment by a-zharkov** [comment]
@jennifer-shehane Hey. Any updates on this ?

**Comment by jennifer-shehane** [comment]
Have you taken a look at our [Module API](https://on.cypress.io/module-api#cypress-run)? You could use that to collect the failing tests and send to JIRA after all the test results return. 

But yeah, I've seen this Promise error floating around...it's not really a great error.

**Comment by a-zharkov** [comment]
@jennifer-shehane Will check now. Thank you.

**Comment by a-zharkov** [comment]
@jennifer-shehane Thanks. This solution works!
