### ISSUE TITLE
cypress open --spec errors with "unknown option --spec"

### ISSUE THREAD

**Issue by DanweDE** [cypress-io/cypress#4454]
In https://github.com/cypress-io/cypress/issues/161 it was stated that the `--spec` option should work with `cypress open`

### Current behavior:

Running `cypress open --spec path` returns

```
error: unknown option: --spec
```

### Desired behavior:

Should open the interactive mode, immediately running the specified spec.

### Steps to reproduce: (app code and test code)

_See above_

### Versions

Cypress version: 3.3.1

**Comment by jevors** [comment]
#161 only states that `cypress run --spec` works.

**Comment by DanweDE** [comment]
> #161 only states that `cypress run --spec` works.

And `cypress ci --spec` after the fix. But yes, sorry, I confused `ci` with `open`. So I'll open a separate ticket. Thanks.

**Comment by CarlosAlbertoVala** [comment]
cual es la solucion exacto
