### ISSUE TITLE
cy.writeFile() is not working as stated in the documentation

### ISSUE THREAD

**Issue by Kondasamy** [cypress-io/cypress#4456]
### Current behavior:
I use **TypeScript** specs for running Cypress tests. When I call `cy.writeFile()` with below syntax as stated in the docs - https://docs.cypress.io/api/commands/writefile.html#Syntax ,

```js
cy.writeFile("../output/oozie_workflows.csv", oozieId + ",False", 'utf-8', {
      flag: "a"
    });
```

Below error messages are returned,

```
Argument of type '{ flag: string; }' is not assignable to parameter of type 'Partial<Loggable>'.
  Object literal may only specify known properties, and 'flag' does not exist in type 'Partial<Loggable>'.
```

I see the `cy.writeFile()` is referenced to below code in **index.d.ts**, which is not as per the documentation,

```
    writeFile<C extends FileContents>(filePath: string, contents: C, options?: Partial<Loggable>): Chainable<C>
    /**
     * Write to a file with the specified encoding and contents.
     *
     * @see https://on.cypress.io/writefile
     */
    writeFile<C extends FileContents>(filePath: string, contents: C, encoding: Encodings, options?: Partial<Loggable>): Chainable<C>
  }
```

### Versions
Cypress version - 3.3.1

**Comment by jennifer-shehane** [comment]
`cy.writeFile()` accepts 3 arguments. As I can see, you are passing 4. 

1: `"../output/oozie_workflows.csv"`
2: `oozieId + ",False"`
3: `'utf-8'`
4: `{ flag: "a" }`

Either `cy.writeFile(filePath, contents, encoding)` or `cy.writeFile(filePath, contents, options)` are accepted.

You want to write 

```js
cy.writeFile("../output/oozie_workflows.csv", oozieId + ",False", {
  encoding: 'utf-8'
  flag: "a"
});
```

Please do try debugging in our [community chat](https://gitter.im/cypress-io/cypress) first before opening an issue - it can help catch these types of things.

**Comment by Kondasamy** [comment]
I have tried this though. Still the same issue,

```
Argument of type '{ encoding: string; flag: string; }' is not assignable to parameter of type 'Encodings'.
  Type '{ encoding: string; flag: string; }' is not assignable to type '"utf-16le"'.ts(2345)
```

**Comment by sudheer-cypress** [comment]
Need your help to fix the issue with Excel file :

cy.request ({
method: 'GET',
url : 'something'
body: {},
headers: {
'Accept-Encoding': 'gzip, deflate'
}
}).then(function (response1) { cy.writefile('filename.xls',response1.body,'utf-8'} }) When I use the above code, I am not able to open the xls file in readable format.

_
