### ISSUE TITLE
cy.contains(selector, content) does not resolve element in headed Electron browser

### ISSUE THREAD

**Issue by davidzambrana** [cypress-io/cypress#4457]
### Current behavior: 

I've a statement in my test code that works fine in Chrome and headless Electron, but when I run it in headed Electron (v61) it doesn't resolve.

The code is:

```js
cy.contains('.braintree-option__label', 'Card').click({
  force: true
});
```

The element is one of the options provided by Braintree payments

![payments1](https://user-images.githubusercontent.com/36962817/59417181-0f869f80-8dc7-11e9-8ddc-3248bc22d020.png)

![payments2](https://user-images.githubusercontent.com/36962817/59417194-13b2bd00-8dc7-11e9-9b93-8312d8189e96.png)

It actually doesn't fail, because it can click on the element, and I see that the test finishes, but it doesn't mark it as so (no :heavy_check_mark:  nor :x: ). But in the Cypress log I see that it doesn't resolve the element even though cypress does click:

![payments3](https://user-images.githubusercontent.com/36962817/59417563-c6831b00-8dc7-11e9-84aa-72bf37e279a0.png)

### Desired behavior:

Cypress is able to resolve the element both in Chrome and Electron (headed and headless)

### Steps to reproduce: (app code and test code)

App code
```html
<div class="braintree-option__label" aria-label="Paying with Card">
  Card
  <div class="braintree-option__disabled-message"></div>
</div>
```

test code
```js
cy.contains('.braintree-option__label', 'Card').click({
  force: true
});
```

### Versions

Cypress 3.3.1
Ubuntu Linux 18.04.2 LTS
Electron Browser 61

**Comment by jennifer-shehane** [comment]
Hey @davidzambrana, thanks for the detailed description. 

If you open DevTools while running `cypress open` in Electron, are there any errors in the console there? Or perhaps some pending requests in the Network panel - I do see that XHR is pending, wonder if it's weirdly related. 

If you run a test directly after this test (really anything - `expect(true).to.be.true`), does the test resolve? Any errors?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
