### ISSUE TITLE
Fix file bundling when `watchForFileChanges: false`

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#446]
When `watchForFileChanges` is false, the javascript bundles don't get updated when a source file changes. We need to still watch the files when `watchForFileChanges: false`, just not tell the runner to re-run on changes.

**Comment by chrisbreiding** [comment]
@sarahgracesmith I believe you were having issues with this. It will be fixed in `0.19.1`, which is being released shortly.

**Comment by brian-mann** [comment]
Fixed in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).
