### ISSUE TITLE
cy.writeFile() is working with JS specs, but not with TypeScript specs

### ISSUE THREAD

**Issue by Kondasamy** [cypress-io/cypress#4461]
This is in reference to the issue - https://github.com/cypress-io/cypress/issues/4456

### Current behavior:
```
cy.writeFile("../output/oozie_workflows.csv", oozieId + ",False", {
  encoding: 'utf-8'
  flag: "a"
});
```

The above code works fine with JavaScript specs, but with TypeScript specs - it throws below error message.

```
Argument of type '{ encoding: string; flag: string; }' is not assignable to parameter of type 'Encodings'.
  Type '{ encoding: string; flag: string; }' is not assignable to type '"utf-16le"'.ts(2345)
```

I'm sure this something to do with the **file:  index.d.ts**. Please check.

### Versions
Cypress - 3.3.1

**Comment by jennifer-shehane** [comment]
Oh, yes, this definitely looks like a Typing issue. Thanks for following up.

**Comment by jennifer-shehane** [comment]
The code for this is done in #4463, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
