### ISSUE TITLE
Chainer not pointing to correct field

### ISSUE THREAD

**Issue by valoricDe** [cypress-io/cypress#4477]
### Current behavior:

When I'm righting a test like:

```js
describe('user > login', () => {
  beforeEach(() => {
    cy.visit('https://advisor.fortunica-app.com/login')
  })

  const fillForm = () => ({
    email: cy.get('input[name="u"]').type('abc@example.com'),
    password: cy.get('input[name="p"]').type('asdfghjkl'),
  })

  it('foobar', () => {
    const { email, password } = fillForm()
    console.log(email, password)
    email.should('have.value', 'abc@example.com')
    password.should('have.value', 'asdfghjkl')
  })
})

```
I would assume that `email` is pointing to the email field and `password` to the password field. I can see in the logs that the output of these variables have different ChainerIds but when executing `email.should('have.value', '...')` it says `expected \<input name="u"> to have value cs.fortunica@gmail.com, but the value was 123456`

### Desired behavior:

I would like to point email to \<input name="u"> not \<input name="p">

### Steps to reproduce: (app code and test code)

https://github.com/valoricDe/cypress-test-tiny

### Versions

Latest cypress, Mac OSx 10.13.4, Chrome

**Comment by jennifer-shehane** [comment]
I would recommend taking a look at this document about variables and aliases. These are not quite evaluating how you expect they are I think. https://on.cypress.io/variables-and-aliases
