### ISSUE TITLE
Create fall-through for API warning messaging

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#4489]
### Current behavior:

If the API sends a warning message to the Test Runner that is not recognized as a key, the warning message is never displayed.

There is also some new messaging that should be added per our upcoming Dashboard changes:

- `FREE_PLAN_NEARING_MONTHLY_TESTS`
- `PAID_PLAN_NEARING_MONTHLY_TESTS`
- `PAID_PLAN_PARALLELIZATION_DISABLED`
- `PAID_PLAN_RUNS_HIDDEN`
- `PLAN_IN_GRACE_PERIOD_PARALLEL_FEATURE_USED` (somehow there is not a message written for this, although this is an older message)

### Desired behavior:

If the Cypress API sends a warning message and we haven't coded a key to match it, it should fall-through and print the API's message as is. 

### Steps to reproduce: (app code and test code)

- No warning fall-through if switch case is not matching: https://github.com/cypress-io/cypress/blob/master/packages%2Fserver%2Flib%2Fmodes%2Frecord.coffee#L304
- Error fallthrough if switch case not matching (should be updated to be like this): https://github.com/cypress-io/cypress/blob/master/packages%2Fserver%2Flib%2Fmodes%2Frecord.coffee#L376

### Versions

Cypress 3.3.1

**Comment by brian-mann** [comment]
Closed by https://github.com/cypress-io/cypress/pull/4567
