### ISSUE TITLE
Customize displayed element name on assertion failures

### ISSUE THREAD

**Issue by scott-ad-riley** [cypress-io/cypress#4492]
### Current behavior:

With an assertion (example forced to fail):
```javascript
cy.get(
	'div[data-test-id="AccountSettingsUpdatedSuccessfullyMessage"]'
).contains('Personal details updated successfullyer')
```

This causes the output in `cypress run` to not display the data-test-id (which would help a lot with debugging), and instead uses the classes on the element. In our case we use a css-in-js framework that obfuscates classnames which makes that output/error message more difficult to read/debug.

![image](https://user-images.githubusercontent.com/11612724/59704497-29bfe380-91f4-11e9-8618-6a182402a831.png)

### Desired behavior:

We'd like to configure the displayed name so that it doesn't use the element's classes and instead displays the data-test-id (or uses the original selector passed to `cy.get`). This would make debugging test failures much easier as we could take that test id and go straight to where it's used in the codebase. I think it would be fine for this to ignore any scopes where the `cy.get` is in a `cy.within` or something.

I did look into wrapping `cy.get` with some kind of custom command, and having it create some special kind of subjects for assertions failures to pick up on but it all seems quite confusing/unstable.

### Versions

We're on cypress `3.1.5`, OSX (Mojave) and Linux (Ubuntu mostly), Using Chrome 74 in Cypress

**Comment by jennifer-shehane** [comment]
You can add your own messaging to the assertions as another argument to `.should()` like so:

```js
cy.get('div[data-test-id="AccountSettingsUpdatedSuccessfullyMessage"]')
  .should('contain', 'Personal details updated successfullyer', '[data-test-id="AccountSettingsUpdatedSuccessfullyMessage"] should find the content')
```

This will prepend this custom message to your printed error.

**Comment by mhdsysy** [comment]
@jennifer-shehane This does not work for me.
`cy.get(
          "[data-test-id=import-attempt-status] > [data-test-id=boolean-output-fail2]"
        ).should("not.exist", `Importing file ${xmlTestFile.filename} was not successful.`);`
       
![Screenshot 2021-11-08 at 20 00 49](https://user-images.githubusercontent.com/27953412/140801710-117b5911-e31f-4dd5-bbb8-b17aa2cfc670.png)
