### ISSUE TITLE
cypress cant see chrome confirmation box and cant click on buttons

### ISSUE THREAD

**Issue by mushon89** [cypress-io/cypress#4496]
### Current behavior:

Hi all
I'm using cypress and I'm trying to click on the button that appears on chrome confirmation box
but when I'm running the test I'm getting this error
![image](https://user-images.githubusercontent.com/51986050/59742286-fde54200-9275-11e9-9c8d-636a565d8967.png)
in addition, the confirmation box does not appear 

    it('delete user', () => {
        //delete user
        cy.get('.fa-user').click();
        cy.get('.pull-left > .form-control').type('example');
        cy.get('.ng-scope:nth-child(1) > td > .iconBtn').click({ force: true })    

    })

the correct confirmation box is:
![image](https://user-images.githubusercontent.com/51986050/59742406-4f8dcc80-9276-11e9-9de9-80803ef8bfe3.png)
I'm want to click on the 'OK' button, but the confirmation box does not appear and cant click on the button

thanks

**Comment by jennifer-shehane** [comment]
You can find an answer to your originally opened issue here: https://github.com/cypress-io/cypress/issues/4497#issuecomment-504350123 Closing this as a duplicate.
