### ISSUE TITLE
Cypress cant see chrome confirmation box when run test, and cant click on buttons of the confirmation box

### ISSUE THREAD

**Issue by mushon89** [cypress-io/cypress#4497]
Current behavior:
Hi all
I'm using cypress and I'm trying to click on the button that appears on chrome confirmation box
but when I'm running the test I'm getting this error
image
![image](https://user-images.githubusercontent.com/51986050/59744104-836af100-927a-11e9-815f-5634fa649abc.png)

in addition, the confirmation box does not appear

```js
it('delete user', () => {
    //delete user
    cy.get('.fa-user').click();
    cy.get('.pull-left > .form-control').type('example');
    cy.get('.ng-scope:nth-child(1) > td > .iconBtn').click({ force: true })    
})
```
the correct confirmation box is:
image
![image](https://user-images.githubusercontent.com/51986050/59744137-941b6700-927a-11e9-9284-74bebeb645d4.png)

I'm want to click on the 'OK' button, but the confirmation box does not appear and cant click on the button

thanks

**Comment by jennifer-shehane** [comment]
Please see this docs on testing confirmation boxes: https://on.cypress.io/catalog-of-events#Window-Confirm

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by jennifer-shehane** [comment]
@mushon89 In the code and screenshot provided above, it seems to indicate that the test is failing at `cy.get('.fa-user').click()`, have you tried passing `cy.get('.fa-user').click({force: true})` to this command? 

I'm not completely sure why the confirmation dialog is already open at the point where `cy.get('.fa-user').click()` is open though, with the code I see provided.

**Comment by mushon89** [comment]
thank u very much,
I succeed to click o the confirmation box button.

**Comment by timaihsoj** [comment]
> thank u very much, I succeed to click o the confirmation box button.

@mushon89  How you resolved this , I am facing same issue.

**Comment by DanielPhangHL** [comment]
@mushon89 please share your way to fix this please
