### ISSUE TITLE
Error grouping

### ISSUE THREAD

**Issue by wwalmnes** [cypress-io/cypress#45]
Is it possible to get Cypress to group errors (of the same type) together?

Want to avoid the same error being repeated (for example when using cy.wait()).
![screen shot 2015-06-22 at 09 13 39](https://cloud.githubusercontent.com/assets/1506750/8283702/13c6e5c4-18f9-11e5-9c3b-5bda8c251cd4.png)

**Comment by jennifer-mann** [comment]
I'd like to see the failed assertions be grouped similar to how the DOM elements are grouped when multiple are found. That way I can see the number increment as they fail, but it won't clutter the entire command log.

**Example of grouping failed assertions**
![errors_with_num](https://cloud.githubusercontent.com/assets/1271364/8311550/e26bef18-19a4-11e5-920b-05dfdc89c9d9.png)

**Comment by brian-mann** [comment]
Fixed in [`0.11.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0110-09132015).

Upcoming Assertions are now predicted and will not output their log multiple times.

There should never be a reason to ever write `cy.wait` with a function now.
