### ISSUE TITLE
Setting fixturesFolder to false throws error that prevents server from starting

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#450]
In a new project with the following `cypress.json`:

```
{
  "fixturesFolder": false
}
```

![fixturesFolder false error screenshot](https://cloud.githubusercontent.com/assets/1157043/23809593/38fd8898-059c-11e7-9f6c-9b89dcd33ca3.png)

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
