### ISSUE TITLE
Cypress will fail wit urls with a domain in the form of "*.local*"

### ISSUE THREAD

**Issue by carlos-granados** [cypress-io/cypress#451]
If you try to run Cypress having set up the baseUrl as something like `something.localhost` or `something.localsite` it will not run and instead it will bring up a browser screen with a grey background, no command log window

**Comment by Okyne** [comment]
Is there any news about this issue ? I'm stuck on this, every testing on localhost fails. Do you have workaround ?

**Comment by bahmutov** [comment]
Can you provide details: OS, browser, and most importantly how you run your server at .local ?

**Comment by carlos-granados** [comment]
We resorted to using a different domain like `something.test` and using our local hosts file to point it to localhost

**Comment by carlos-granados** [comment]
@brian-mann looked into this at some point and he said this was related to some code related to cookies and domains, I seem to remember

**Comment by Okyne** [comment]
In my case : 
OS: Ubuntu 14.01
Browser: Chrome v62
Server: NGINX
The front-end is served through `name.localhost:8000`
The API is served through `api.name.localhost:8001`

As carlos said, the browser's window opens, but instantly, it redirects to a grey background screen without the reporter section.

**Comment by wulfovitch** [comment]
I also have this problem. In our testing environment we use a domain with 'local'-name in it. As soon we remove the 'local' from the domain name, the tests are working again as @carlos-granados pointed out.

**Comment by brian-mann** [comment]
I believe this issue is the same one related to publix suffix parsing here: https://github.com/cypress-io/cypress/issues/802

**Comment by ndf** [comment]
Also grey screen here, but only when using .localhost 
When changing to .local or .dev or whatever there are no issues.

OS: MacOS 10.13.2
Browser: Chrome v63
Server: MampPro 4.2.1

The only difference between my setup and @wulfovitch seem to be the server.
Extra note: we run tests without https.

**Comment by steveperrycreative** [comment]
Same here. I'm just trying out Cypress so it's a very basic HTML site.

OS: MacOS 10.13.2
Server: MampPro 4.2.1
URL: http://cypress.localhost

![35161856-5c55fb46-fd39-11e7-8181-667bf2ecf5bb](https://user-images.githubusercontent.com/2418930/35210282-7f87c088-ff49-11e7-9452-74d33a38e6ab.png)

**Comment by peterhry** [comment]
This PR should fix: https://github.com/cypress-io/cypress/pull/1216

**Comment by brian-mann** [comment]
I'm working on merging this in now

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).

**Comment by steveperrycreative** [comment]
Thanks!

**Comment by pmatisko** [comment]
I see a fix is supposed to be released, but I still get the error with anything.localhost. Any advice, please?

**Comment by jennifer-shehane** [comment]
@pmatisko Could you open a new issue detailing the exact problem you are encountering as well as the test code?
