### ISSUE TITLE
Add electron as available browser for running tests

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#452]
This may help with debugging tests that only fail in CI, since it's the browser used in CI.

![browser dropdown screenshot](https://cloud.githubusercontent.com/assets/1157043/23814429/7a35bba4-05b1-11e7-8aa8-bc8fbce37acf.png)

![running electron browser screenshot](https://cloud.githubusercontent.com/assets/1157043/23814589/15917dcc-05b2-11e7-930d-6dd29715dd68.png)

**Comment by brian-mann** [comment]
Fixed in [`0.19.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0192-04162017).
