### ISSUE TITLE
Language spillover in docs: CLI page

### ISSUE THREAD

**Issue by jhays-nhaschools** [cypress-io/cypress#4523]
### Current behavior:
https://docs.cypress.io/guides/guides/command-line.html#Installation

Some non-English is appearing on this English docs page:
命令行
 Improve this doc
 你将会学习到什么

### Desired behavior:

The English docs are all in English

### Steps to reproduce: (app code and test code)

Go to 
https://docs.cypress.io/guides/guides/command-line.html#Installation
Set language to English

### Versions

Chrome

**Comment by bahmutov** [comment]
Thank you for noticing and opening an issue (even if this issue is better in cypress-io/cypress-documentation repo) We are fixing this in https://github.com/cypress-io/cypress-documentation/pull/1793
