### ISSUE TITLE
Track certain metrics over time

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4535]
We should do some long-term logging of various statistics that are collected about Cypress during CI builds.

Things that would be nice to track on each commit:

- results of `proxy_performance` server spec
- results of `6_visit_spec` "resolves visits quickly": https://github.com/cypress-io/cypress/blob/c4bf698013998a38ff955f5487275ed47e41c5fd/packages/server/test/e2e/6_visit_spec.coffee#L155-L155

**Comment by jennifer-shehane** [comment]
This was released in https://github.com/cypress-io/cypress/pull/4989
