### ISSUE TITLE
Create a master readme which summarizes Cypress, and sets the expectations for new users

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#454]
It's about time we started acting like stewards and begin fostering a real open source community.

We need a great main `readme` which outlines the case for Cypress, why'd you'd use it, what makes it so different, and sets the expectations for everyone coming in.

We can synchronize this `readme` inside of our official docs.

The idea here is that users should be able to come into our repo, and read our readme that flows like a story. From there there should be a series of call to actions for further reading and investigation.

Our documentation needs this same love.

[This is currently a WIP in progress here.](https://github.com/cypress-io/cypress/tree/readme)

**Comment by brian-mann** [comment]
pinging @kentcdodds for sanity and tone check. 

All sections in `Key Differences` are purely WIP. Going to pad each section with a lot of screenshots and animated gifs to drive home the differences.

**Comment by kentcdodds** [comment]
> It's about time we started acting like stewards and begin fostering a real open source community.

Having been a really new member of the community, I'm unsure of how well you all have been doing up until now, but I can say that seeing you say this is extremely encouraging! I'm excited to give this a look.

**Comment by brian-mann** [comment]
This was done when we released the new docs - specifically here:

https://docs.cypress.io/guides/getting-started/why-cypress.html
