### ISSUE TITLE
Having a dedicated command to show up local environment information 'cypress info'

### ISSUE THREAD

**Issue by jamesgeorge007** [cypress-io/cypress#4540]
## Feature Request

Most CLI tools these days are shipped with a dedicated `info` command which shows up local environment information. Also, the present issue template includes a section which expects to have information regarding the local environment.

With this all the user has to do is just copy and paste the information as shown by `cypress info` within the respective section.

**Comment by jamesgeorge007** [comment]
I would love to work on this :+1:

**Comment by jamesgeorge007** [comment]
cc @bahmutov

**Comment by jennifer-shehane** [comment]
The code for this can be found here (for example this is the `cypress help` command) for anyone that would like to contribute this `cypress info` command. https://github.com/cypress-io/cypress/blob/develop/cli/lib/cli.js#L156

I imagine it would print:

- Cypress version
- OS platform info

Maybe some environment variables from the OS we care about? like...

- `HTTP_PROXY`
- `NO_PROXY`
- `CYPRESS_INSTALL_BINARY`

**Comment by jennifer-shehane** [comment]
From [this previous issue](https://github.com/cypress-io/cypress/issues/1041), there was a recommendation on the structure of printing browser information we've found that I liked. Pasting here from @bahmutov previous comment. 

It cold also perhaps link to our debugging guide on how to get browsers to be detected that are not currently. https://on.cypress.io/debugging#Launching-browsers

```
Detected 3 browsers

Browser info
-------------------------------------------------
name      displayName  majorVersion  version     
--------  -----------  ------------  ------------
chrome    Chrome       62            62.0.3202.94
chromium  Chromium     60            60.0.3110.0 
canary    Canary       65            65.0.3287.0 

Browser paths
------------------------------------------------------------------------------------
name      path                                                                      
--------  --------------------------------------------------------------------------
chrome    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome              
chromium  /Applications/Chromium.app/Contents/MacOS/Chromium                        
canary    /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary
```
