### ISSUE TITLE
chrome

### ISSUE THREAD

**Issue by tikihpy** [cypress-io/cypress#4549]
### Current behavior:

![image](https://user-images.githubusercontent.com/5051163/60015818-fc24df80-96b6-11e9-84e9-1a6e80e988c8.png)

![image](https://user-images.githubusercontent.com/5051163/60015887-26769d00-96b7-11e9-9e25-e86541789039.png)
just cancel cypress control  then can not open chrome by cypress anymore, how can i reset open by  chrome  default

### Desired behavior:
reset open by  chrome  default

### Steps to reproduce: (app code and test code)

1.run test by chrome
2.open chrome setting 
3.cancel cypress control
4.restart cypress 

### Versions

cypress@3.3.1
MAC OS  Mojave 10.14.5
chrome  75.0.3770.100

**Comment by jennifer-shehane** [comment]
Try quitting the Chrome process in activity monitor.

Try [clearing your app data](https://on.cypress.io/debugging#Clear-App-Data).

**Comment by clarmso** [comment]
Here's my settings and I can run cypress tests no problem.
![Screenshot from 2019-06-25 17-06-18](https://user-images.githubusercontent.com/1740517/60133603-a9592f80-976b-11e9-81d3-878dfc72d3cf.png)
P.S. The screenshot is the corresponding section of the Chrome settings shown in the OP's report.

**Comment by tikihpy** [comment]
> Try quitting the Chrome process in activity monitor.
> 
> Try [clearing your app data](https://on.cypress.io/debugging#Clear-App-Data).

thanks its ok now
