### ISSUE TITLE
Provide a way to correlate multiple instances to a single "run" in the Dashboard

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#455]
Our Dashboard supports the ability the have multiple instances associated to a single run.

This is useful when you are:

- Splitting up individual instances by spec file
- Running across multiple docker containers for parallelization
- Doing cross browser testing (in the future)

We need a way from the CLI and from the cypress `node_module` to make this possible. Some internal changes in the Desktop App have to be made, but it's fairly straightforward.

**Comment by bahmutov** [comment]
Test runner can take `--group` flag (and optional `--group-id <id>`) and send it to the API to group instances. API needs to be deployed to production.

**Comment by bahmutov** [comment]
Set up example repo https://github.com/cypress-io/cypress-example-group with Circle V1 and parallel containers, should group results from 4 runs into single dashboard item
