### ISSUE TITLE
uncaught error from onBeforeLoad is mistakenly attributed to application code

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4551]
Mac, Cypress v3.3.x

Reproducible example in [branch `set-navigator-language` in cypress-test-tiny](cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny/tree/set-navigator-language)

Sample page (does not really matter)

```html
<body>
  <p>Hi there</p>
</body>
```

spec 
```js
/// <reference types="cypress" />
it('catches correctly exception', () => {
  cy.visit('index.html', {
    onBeforeLoad (win) {
      win.navigator.language = 'JavaScript'
    }
  })
})
```

When the test runs it thinks the exception is from the application code, but even from the stacktrace it is coming from the spec code

<img width="1117" alt="Screen Shot 2019-06-24 at 9 03 33 AM" src="https://user-images.githubusercontent.com/2212006/60021186-7f1a4b80-965f-11e9-858e-d961ee687387.png">

**Comment by mgxcool** [comment]
I have the same problem on Mac, Cypress v3.3.x .   hoping someone to fix it
