### ISSUE TITLE
Cypress won't start on OS X Catalina beta (19A471t)

### ISSUE THREAD

**Issue by ukd1** [cypress-io/cypress#4569]
### Current behavior:

```bash
russ$ cat package.json 
{
  "devDependencies": {
    "cypress": "^3.3.1"
  }
}
russ$ node_modules/.bin/cypress verify
It looks like this is your first time using Cypress: 3.3.1

 ✖  Verifying Cypress can run /Users/russ/Library/Caches/Cypress/3.3.1/Cypress.app
   → Cypress Version: 3.3.1
Cypress verification timed out.

This command failed with the following output:

/Users/russ/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/MacOS/Cypress --smoke-test --ping=177

----------

Command failed: /Users/russ/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/MacOS/Cypress --smoke-test --ping=177

----------

Platform: darwin (19.0.0)
Cypress Version: 3.3.1
russ$
```

Digging a little, the OS X console contains the following under the process Kernel (AppleSystemPolicy):

```
Security policy would not allow process: 58470, /Users/russ/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/MacOS/Cypress
```

### Desired behavior:

Cypress starts

### Steps to reproduce: (app code and test code)

1. install or upgrade to catalina beta
2. follow instructions down to https://docs.cypress.io/guides/getting-started/installing-cypress.html#Opening-Cypress

### Versions

* Cypress 3.1.1
* OS X Catalina 19A471t

**Comment by ukd1** [comment]
p.s. I know it's beta, I have it on one of my machines and wanted to hack on something. Hopefully this gets fixed / I figure it out and post back!

**Comment by jennifer-shehane** [comment]
Can you go within System Preferences, click Security & Privacy, then click General. Can you provide a screenshot of what your settings are here?

**Comment by kkliuiev** [comment]
Actually I have no problems running Cypress on Catalina

**Comment by ukd1** [comment]
@jennifer-shehane I've moved on since this, plus missed the notification. Closing for now!
