### ISSUE TITLE
Cypress fails to run in a docker container within CircleCI

### ISSUE THREAD

**Issue by carlos-granados** [cypress-io/cypress#457]
If you create a docker container with Cypress installed (you can use this semi-official container if you want: https://hub.docker.com/r/bahmutov/cypress-image/) and try to use it in CircleCI, cypress will not work. 
- Most commands just hang with no output, even if you set CYPRESS_DEBUG=true.
- It seems that this could be related to network connectivity because if you run the container without --net=host then cypress will not hang (it will just not work because it will not be able to connect to your server). 
- Does not seem to be a dependency issue because that same container runs fine in a local ubuntu machine. 
- Tested both in CircleCI Ubuntu 12.04 and 14.04 images

**Comment by carlos-granados** [comment]
I was able to run the tests by starting directly the cypress runtime using `xvfb-run -a -s "-screen 0 1280x1024x24" {path to Cypress} --run-project={path to project}` within the container

**Comment by bahmutov** [comment]
Hmm, this is weird, can you try latest Docker image from https://github.com/cypress-io/cypress-docker-images ?

**Comment by wescarr** [comment]
I am seeing this issue as well on Circle 2.0 with the latest `cypress/base` image. I ssh'd into a circle build and ran the following:
```
docker run -it --net=host cypress/base /bin/bash

npm install --save-dev cypress

DEBUG=* /node_modules/.bin/cypress verify
  cypress:cli cli starts with arguments ["/usr/local/bin/node","/node_modules/.bin/cypress","verify"] +0ms
  cypress:cli verifying Cypress app +153ms
  cypress:cli path to info.json file /node_modules/cypress/dist/info.json +2ms
  cypress:cli { version: '0.20.1', verifiedVersion: null } +3ms
  cypress:cli installed version is 0.20.1 comparing to 0.20.1 +3ms
  cypress:cli checking if executable exists /node_modules/cypress/dist/Cypress/Cypress +0ms
  cypress:cli path to info.json file /node_modules/cypress/dist/info.json +1ms
  cypress:cli has verified version null +1ms
  cypress:cli run verification check? true +0ms
  cypress:cli running binary verification check 0.20.1 +0ms
It looks like this is your first time using Cypress: 0.20.1

  cypress:cli writing verified version string "null" +4ms
  cypress:cli path to info.json file /node_modules/cypress/dist/info.json +0ms
  cypress:cli path to info.json file /node_modules/cypress/dist/info.json +1ms
  cypress:cli running smoke test +2ms
  cypress:cli using Cypress executable /node_modules/cypress/dist/Cypress/Cypress +0ms
  cypress:cli needs XVFB? true +0ms
  cypress:cli Starting XVFB +1ms
 ⠴  Verifying Cypress can run /node_modules/cypress/dist/Cypress
```

As you can see it just hangs trying to verify without any further output.

Running without `--net=host` works just fine.

**Comment by jennifer-shehane** [comment]
Is this still an issue? Please close if resolved.

**Comment by tylergets** [comment]
@jennifer-shehane I detailed what I believe is the problem (and a potential fix) here https://github.com/cypress-io/cypress-docker-images/issues/54#

**Comment by jennifer-shehane** [comment]
Closing as issue related to docker-images - not cypress project itself.
