### ISSUE TITLE
Login test fails every odd run due to cookie not being saved

### ISSUE THREAD

**Issue by reallyusefulengine** [cypress-io/cypress#4580]
### Current behavior:

When running  a login script the tests passes on the first go but every second run(after clicking on the rerun test Icon on the test runner) it will fail.

On the failing second run the order of execution is as following:

1. clicking login button
2. `POST` to `/api/signi`
3. Page loads
5. `GET` Client state 

The cookies _doesnt_ seem to get saved on the second run.

### Desired behavior:

Test to pass every time by:

1. clicking login button
2. `POST` to `/api/signi`
3. Page loads
4. New URL loaded for the landing page
5. `GET` Client state 

I want the test to work on every execution.

### Steps to reproduce: (app code and test code)

```js
 it('navigates to onboarding on successful login', () => {
        cy.server();
        cy.route('POST', '**/api/signin').as('signInApi');
        cy.route('GET', '**/api/client-state**').as('clientState'); 
        cy.visit('/onboarding');
        cy.get('input[name="username"]').type('doctor@foster.com');
        cy.get('input[name="password"]').type('foster12345');
        cy.get('button').click();
        cy.wait('@signInApi');
        cy.wait('@clientState');
        cy.get('h1').should('contain', 'Welcome');
});
```

### Versions
Using Cypress 3.3.1
Windows 10 operating System with Chrome version 75.0.3770.100

**Comment by jennifer-shehane** [comment]
>When running a login script the tests passes on the first go but every second run it will fail.

Can you explain what you mean by 'second' run. How is the 'it' being run the second time? Are you refreshing the browser. Are you clicking the rerun button? Are you writing the 'it' twice?

**Comment by reallyusefulengine** [comment]
hi Jennifer, there is only one test. It happens when I rerun the test via the rerun button.

**Comment by jennifer-shehane** [comment]
It's strange. 🤔 

As a first step, can you add an assertion around the cookies to ensure that is IS indeed a cookie issue and not something else? https://on.cypress.io/getcookie

So, add this where appropriate:
```js
cy.getCookie('fakeCookie1').should('exist')
// or
cy.getCookie('fakeCookie1').should('have.property', 'value', '123ABC')
```

After confirming this, we will need some way to narrow down the issue some more. Maybe setting the cookie from within Cypress to replicate the behavior? Or providing a simple `index.html` with a cypress spec to replicate this? We can't really track down why this would be happening otherwise.

**Comment by reallyusefulengine** [comment]
The failing test:
![image](https://user-images.githubusercontent.com/45160568/60307616-b2731800-9988-11e9-8761-425b2c591e9e.png)

The passing test(i pressed rerun):

![image](https://user-images.githubusercontent.com/45160568/60307648-d46c9a80-9988-11e9-9fe0-93cb06694a73.png)
