### ISSUE TITLE
setting localStorage in beforeEach() fails occasionally

### ISSUE THREAD

**Issue by danatemple** [cypress-io/cypress#4582]
I have a system with JWT authentication and, as I understand is a best practice, set the localStorage in a `beforeEach()` to ensure the user is logged in before each test.

```js
describe('A test', function() {
    beforeEach(function() {
        if (this.currentUser) {
            localStorage.setItem('currentUser', this.currentUser);
            localStorage.setItem('token', this.token);
        }
    });
   it('does a test', function() {});
   it('does another test', function() {});

```

Occasionally,  one of the tests fails as it perceives the user is not logged in. This seems random, i.e. the first one can pass and the second then fail.
(Like, once in 500 `it()` tests).

As it is not reproducible it is rather hard to debug, as it only happens about once in 30 minutes running headless on a CI server.  I would say however that it seems to have gotten worse with 3.3.1. Earlier, it was so rare that I could live with it.

I am using Electron browser.

**Comment by jennifer-shehane** [comment]
I wonder if you can set an expectation in your `beforeEach`, to ensure it is indeed `localStorage` that is not being set and which item is not being set. So when it fails next time, post the results here. This will be hard to debug as is. :/

Something like:
```js
expect(JSON.parse(localStorage.getItem('currentUser'))).to.eq(this.currentUser)
expect(JSON.parse(localStorage.getItem('token'))).to.eq(this. token)
```

**Comment by danatemple** [comment]
Done. And fortunately, can now reproduce in a fairly tight loop on a local server.

The asserts in the beforeEach never trigger, neither do the extra ones I placed in the it()s. It now fails on a random iteration but always in the same place, see THIS FAILS line below.

```
    for (let i = 0; i < 100; i++) {

        it('try a first thing', function() {
            expect(localStorage.getItem('currentUser')).to.eq(this.currentUser);
            expect(localStorage.getItem('token')).to.eq(this.token);
            cy.get('div.dd-item-type-select');
        });

        it('Try another thing', function() {
            expect(localStorage.getItem('currentUser')).to.eq(this.currentUser);
            expect(localStorage.getItem('token')).to.eq(this.token);
            cy.get('div.dd-item-type-select');
            cy.userMenu('Settings')
            cy.get('#dd-settings')
        });

        it('Try yet again', function() {
            expect(localStorage.getItem('currentUser')).to.eq(this.currentUser);
            expect(localStorage.getItem('token')).to.eq(this.token);
            cy.get('#dd-settings')  **<= THIS FAILS**
            cy.userMenu('Profile')
            cy.get('#dd-profile')
        });
        // more it()s here
}
```

Note that this check for #dd-settings is identical to the one in the previous it(), so the page has reloaded in the meantime. It's a React SPA. The page has switched to the "not logged in" screen.

I speculate that some of the browser state clearing at the end of an it() has triggered some update and this has caught the browser in the short period between localStorage being cleared, and the beforeEach executing and setting it again?  Something has at least caused the browser to update.

I have checked for any event listener on localStorage but these have been disabled already (specifically because they break in Cypress...).

**Comment by jennifer-shehane** [comment]
If it is not failing at the `expect(localStorage.getItem('token')).to.eq(this.token);`, then I don't suspect this is an issue with `localStorage` - the `localStorage` is set, something else is causing it to reroute incorrectly. 

If you're expecting a route change, I also would recommend putting in assertions for this, so that it doesn't try to prematurely check the wrong page for the DOM content. 

```
cy.url().should('contain', 'dashboard') // for example
```

I can't debug much more than this since I'm unfamiliar with your application, but this doesn't look to be a bug with localStorage failing.

**Comment by danatemple** [comment]
I see what you're saying, but there are many things pointing to localStorage.
Note that there are *no actual operations* happening between the cy.get() assertions in the two it()s. Somehow, the app has spontaneously updated in the meantime, and at that point (not later, when the extra check is run) it looks like localStorage is empty, as it concludes there is no JWT login.

Also, if I prevent localStorage getting cleared (by just putting a return statement to replace Cypress.LocalStorage.clear() as per https://github.com/cypress-io/cypress/issues/461 ) the problem goes away.

There is presumably a period between Cypress clearing localStorage, and the beforeEach() reinstating it, where localStorage is empty.

Could some event be happening (an async get returning late?) to trigger an app update that occasionally hits exactly that period?

This beforeEach() workaround seems to be a very fragile construction if so.

**Comment by danatemple** [comment]
Having done more testing now, I can confirm that the tests are absolutely rock solid if I prevent the LocalStorage.clear from having an effect, whereas the unreliability exists if I use the official workaround of trying to restore localStorage in a beforeEach before each test.

It seems there really needs to be a *reliable* way to keep DOM-critical local storage from getting deleted at all, even temporarily? I know the philosophy of cleaning up each time, but for an SPA with JWT, the user login is integral to the app state. The DOM state is after all allowed to persist.

Otherwise, each it() will need to re-start the app 100% from scratch with a full page load and reset the entire DOM, which for an SPA especially removes the point of having the it() level of test hierarchy.

**Comment by jennifer-shehane** [comment]
There is an issue open to whitelist localStorage from being cleared in between each test here: https://github.com/cypress-io/cypress/issues/461

Maybe this workaround will help your situation https://github.com/cypress-io/cypress/issues/461#issuecomment-392070888

Also, it's on our larger roadmap to make handling these things across tests clearer in this issue https://github.com/cypress-io/cypress/issues/686

**Comment by danatemple** [comment]
Thanks - I look forward to #686 being implemented. This is exactly what is needed.

For info, the workaround https://github.com/cypress-io/cypress/issues/461#issuecomment-392070888 (or my similar one, on the comment right below that one!) is what is not working 100%.

As I don't use localStorage for anything that I don't want to persist, the following does the trick reliably:
```
Cypress.LocalStorage.clear = function (keys, ls, rs) {
   return;
}
```

**Comment by pavelsmajda** [comment]
Hi I will leave comment rather here than in https://github.com/cypress-io/cypress/issues/461

First of all thanks for your response, but I find out my Electron (61) is somehow not deleting local storage. I used commands you sent even before and it works but now whole storage is not cleared. Strange. btw.  Where do you put: 
`Cypress.LocalStorage.clear = function (keys, ls, rs) {
   return;
}`

To command.js or directly into test? Thanks!

**Comment by danatemple** [comment]
The clear function is in a file included by support/index.js, e.g. commands.js.

**Comment by simplenotezy** [comment]
Wow, I came here because I am writing my first tests in Cypress.

So I am currently having a great time writing my first test in Cypress - really cool stuff. However, I have a weird issue that happens when I part up my big test, into smaller pieces using it('Something'). On the final step (adding a product to cart) it fails, because the localStorage is empty - so cart is empty. This didn't happen until I parted up the big test into smaller pieces. I didn't change ANY code. It's really freaking me out lol. Here's my first written test:https://paste.laravel.io/d1ac2f6f-cb7d-4913-ac97-9122766d3467 (that works) and here is the test that fails: https://paste.laravel.io/7bbe730f-1600-45b4-ab87-e4351a03d9e0 - any clue why this happens? It's like between each test it loses it's "localStorage" state.

It turned out I needed to add:

Cypress.LocalStorage.clear = function (keys, ls, rs) {
	return;
}

And then it works like a charm.

**Comment by MolotovCherry** [comment]
Using https://github.com/javierbrea/cypress-localstorage-commands , and this is happening in our system.

We're using the recommended methods, and it intermittently fails
```js
  before(() => {
    // do login stuff

    cy.saveLocalStorage('spec');
  });

  beforeEach(() => {
    cy.restoreLocalStorage('spec');
    // we needed to reload the page to get the right logged in state
    cy.reload();
  });

  afterEach(() => {
    cy.saveLocalStorage('spec');
  });
```

I also tested using the direct cypress provided mechanisms for localStorage, and the problem still happened. Seems to not be an issue with that plugin at all. This needs to be re-opened

Using Cypress 10.10.0
