### ISSUE TITLE
Can not install through proxy

### ISSUE THREAD

**Issue by whizsid** [cypress-io/cypress#4583]
### Current behavior:

Can not install cypress.

### Desired behavior:

I want to start developing the package

### Steps to reproduce: (app code and test code)

When I try to run yarn install in [reac-select](https://github.com/JedWatson/react-select) package it gives me an error like `The Cypress App could not be downloaded.` . And full error is:-

```
error /home/u15/Documents/Ramesh/projects/react-select/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /home/u15/Documents/Ramesh/projects/react-select/node_modules/cypress
Output:
Installing Cypress (version: 1.4.2)

[11:23:13]  Downloading Cypress     [started]
[11:23:13]  Downloading Cypress     [failed]
[11:23:13] → The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/1.4.2?platform=linux&arch=x64
Error: tunneling socket could not be established, cause=write EPROTO 140077320272768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
----------

Platform: linux (Ubuntu Linux - 17.04)
Cypress Version: 1.4.2
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/1.4.2?platform=linux&arch=x64
Error: tunneling socket could not be established, cause=write EPROTO 140077320272768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

```

I have googled it. But found answers doesn't help me. This is my config variables.

```
$ echo $https_proxy
http://<proxy>:<port>

$ echo $http_proxy
http://<proxy>:<port>

$ npm config get https-proxy
http://<proxy>:<port>

$ npm config get http-proxy
http://<proxy>:<port>

$ yarn config get https-proxy
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
http://192.168.0.254:3128

$ yarn config get http-proxy
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
http://192.168.0.254:3128

$ ping download.cypress.io
--- download.cypress.io ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 4459ms

```

### Versions

OS:-Ubuntu Linux - 17.04
npm:-6.9.0
yarn:- 1.16.0
node:- v12.2.0

**Comment by jennifer-shehane** [comment]
I'm confused why you are downloading version 1.4.2 of Cypress. We are currently on version 3.3.1. 

Can you set the version number to 3.3.1 and try installing again.

**Comment by whizsid** [comment]
@jennifer-shehane Still same error. Not resolved.

**Comment by jennifer-shehane** [comment]
@whizsid How are you installing exactly? You have it in a package.json as a dependency?

**Comment by whizsid** [comment]
Yes. This is the [package.json](https://github.com/JedWatson/react-select/blob/master/package.json) . This is not my repo. This an open source react component. I want to contribute to it. I have pulled it and run the `yarn install` command.

**Comment by flotwig** [comment]
@whizsid Can you run `yarn install` with debug logs enabled, then share all of those logs here? It should let us know what's going wrong with your proxy.

```
DEBUG=cypress:* yarn add cypress@=3.3.1
```

You may also need to manually start the install, if so, share these logs too:

```
DEBUG=cypress:* $(yarn bin)/cypress install
```

**Comment by whizsid** [comment]
@flotwig @jennifer-shehane Thank you for your responses. I have solved it by editing `/etc/environment` file. This file contained a variable like `https_proxy="https://` I have changed https to http. `export` command is setting env variables for only user space. But installation proccess will looking for global space to retrieving env variables.
