### ISSUE TITLE
3.3.1 Websockets dont work behind a Proxy when NO_PROXY is configured.

### ISSUE THREAD

**Issue by MichaelHindley** [cypress-io/cypress#4585]
### Current behavior:
Websockets cant be established with error:
```
client.js:267 WebSocket connection to 'ws://wslocation/graphql' failed: WebSocket is closed before the connection is established.
```

when the `wslocation` is part of the `NO_PROXY` environment variable. 
I can only observe these network errors within Cypress, if the same page is visited in Chrome or Firefox, both that are configured with the same proxy config as Cypress, then they dont fail with this error.

Gist of logs with DEBUG=cypress:*
https://gist.github.com/MichaelHindley/c32ce535016089e079ce657fe0200e40

### Desired behavior:
Websockets are established.

### Steps to reproduce: (app code and test code)
Be behind a proxy, open cypress browser.
Try to establish a websocket in any page you visit that is part of NO_PROXY environment variable, no need for any code or config otherwise.

I'm not sure how to supply a reproduction, you will need a proxy and 3.3.1 installed and started in a shell with the mentioned proxy settings.
I used http://demos.kaazing.com/echo as base URL as well as our own product. 
However there is also the issues of #4366.

So if you are behind a proxy and set NO_PROXY to include `*.kaazing.com` then it will not work with the error from #4366, only in Cypress.

However if you remove it, then it works and there is no error, but the `wslocation` example will still fail with a different error, only in Cypress.

Might be related to #4257 .

### Versions
Cypress 3.3.1
Windows 10,
Chrome (latest)

**Comment by jennifer-shehane** [comment]
Can you try Cypress version 3.3.2, we fixed a NO_PROXY issue in there. If not fixed, will forward to @flotwig

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
