### ISSUE TITLE
Filling forms using Hyperform

### ISSUE THREAD

**Issue by MarS919** [cypress-io/cypress#4587]
I encountered issues filling form fields with type() when the form is "enhanced" with Hyperform (https://hyperform.js.org/).

### Current behavior:
The form field is not filled.

### Desired behavior:
The form field shoud be filled.

### Steps to reproduce: (app code and test code)
No app code needed.

Test code:
```js
describe('Hyperform basic test', function() {
  it('it should be possible to fill a form field', function() {
    cy.visit('https://hyperform.js.org/examples.html#file=simple')
    cy.get('input').type('This will never appear')
  })
})
```

### Versions
Cypress 3.3.0 and 3.3.1
Chromium 69 and Electron 61

**Comment by jennifer-shehane** [comment]
I can recreate this in Cypress 3.3.2 in Chrome 75. 

When running in Cypress, I've noticed the same `keyup`, `keypress`, and `click` events firing and being listened to as the same as manually typing. Don't see any obvious reasoning for this. 

Failing test @Bkucera 	

```js
describe('Hyperform basic test', function () {
  it('it should be possible to fill a form field', function () {
    cy.visit('https://hyperform.js.org/examples.html#file=simple')
    cy.get('input').type('hello').should('have.value', 'hello')
  })
})

```

**Comment by MarS919** [comment]
Any news here? This is a major blocker for us.

**Comment by Bkucera** [comment]
This is because hyperform is overriding the `maxLength` getter for the input, and forcing it to return 0. We simply need to borrow the property getter from the outer frame when reading maxlength.

I'll have a fix up soon
