### ISSUE TITLE
Failing to compile Typescript using uncaught:exception

### ISSUE THREAD

**Issue by hunghau** [cypress-io/cypress#4591]
### Current behavior:

There is an issue with uncaught exceptions that New Relic and Cypress throws.  We are able to handle this using `.js`, but moving to `.ts` does not allow it to run.

```js
// This is required when testing a system that has the New Relic agent installed
// https://discuss.newrelic.com/t/exception-in-nrwrapper/72759/9
Cypress.on('uncaught:exception', (err) => {
  console.warn(err);
  if (err.message &&
     err.message.startsWith('Cannot set property \'status\' of undefined')) {
    return false;
  }
  return true;
});

```
The Error from Typescript is:
```
TS2345: Argument of type '"uncaught:exception"' is not assignable to parameter of type '"test:after:run"'.
```

### Desired behavior:

We should be able to compile Typescript with this code.

### Steps to reproduce: (app code and test code)

I forked the cypress examples repo at: https://github.com/HungHau/cypress-example-recipes
I committed the code above and just added the file `exceptions.ts` file under `cypress/support/exceptions.ts`.

1. Clone the repo.
2. Run `npm i` at the root.
3. cd to the `cypress-example-recipes/examples/preprocessors__typescript-webpack` directory
4. Run `npm run tsc` to compile the TS

### Versions
Cypress 3.3.1
Typescript 3.3.3

**Comment by jennifer-shehane** [comment]
In the example-recipes changes you provide, you need to import the `exceptions.ts` file from the `support/index.ts` file, otherwise this file is never being read in. https://github.com/HungHau/cypress-example-recipes/blob/master/examples/preprocessors__typescript-webpack/cypress/support/index.ts

**Comment by HungHau** [comment]
Thanks for the quick response Jennifer.  I ended up pushing to the forked example with exceptions added to the index.ts, but it still fails when running ```npm run tsc```.

**Comment by bahmutov** [comment]
what happens when you use `// @ts-ignore`?

**Comment by HungHau** [comment]
> what happens when you use `// @ts-ignore`?

**Comment by HungHau** [comment]
Hah, whoops, clicked closed by mistake.

Sure I can ignore the error, but wouldn't it be better to fix the d.ts file?

**Comment by MichaelBitard** [comment]
The d.ts states that you should not be returning anything if you don't want cypress to fail, is this the correct behavior?

**Comment by HungHau** [comment]
> The d.ts states that you should not be returning anything if you don't want cypress to fail, is this the correct behavior?

Yes, I included the comments, so what we are having conflicts with is New Relic causes this exception and we are ignoring it.  That is correct behavior.

**Comment by sainthkh** [comment]
Is it still happening? I followed the instruction with Cypress 4.10.0 and TS 3.9.5. But the problem was not reproducible.

**Comment by hunghau** [comment]
Great we can close this issue.  Thanks!

**Comment by pradeepku123** [comment]
I am facing same issue when convert js to ta file which is working fine earlier but it's showing application typeError.

**Comment by sainthkh** [comment]
@pradeepku123 Can you open a new issue with a reproducible example?
