### ISSUE TITLE
Maximum call stack size exceeded when click retries & el is animating / fixed position el in it's place

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#46]
I am calling `click` on a el in a dropdown that is animating into view. When Cypress initially gets the coordinates for where the el should be, it doesn't find the element I wanted to click. Instead, it finds another element in the background, then goes through the Cypress logic of finding a parent element with `position: fixed`, then attempting to scroll (in case the fixed position element is covering the element I want to click). 

It's stuck within this loop of finding a parent element with `position: fixed` then attempting to scroll. It eventually times out. 

**Example Code**
```coffee
    it "clicks loading dock in dropdown", ->
      cy
        .contains("Warehouse").click()
        .contains(".k-item", "Loading Dock").click()
```

**The dropdown animated in**
![screen shot 2015-06-23 at 12 24 33 pm](https://cloud.githubusercontent.com/assets/1271364/8311282/fce6e43a-19a2-11e5-8fd4-cc9838601dcb.png)

**Command Log Error**
![screen shot 2015-06-23 at 12 24 46 pm](https://cloud.githubusercontent.com/assets/1271364/8311291/11bdc0c2-19a3-11e5-8e7a-aaf39ec6033e.png)

**Comment by brian-mann** [comment]
Fixed in [`0.7.6`](https://github.com/cypress-io/cypress/wiki/Changelog#076-06232015).
