### ISSUE TITLE
Add option to only upload videos if there is a failure

### ISSUE THREAD

**Issue by carlos-granados** [cypress-io/cypress#460]
Compressing and uploading videos takes a long time, and If the tests pass, the video is usually not interesting, so It would be good to have an option to only save, compress and upload the video if there was a test failure.

**Comment by brian-mann** [comment]
The code for this is merged, but it has not been released yet.

**Comment by brian-mann** [comment]
Fixed in [`1.0.2`](https://docs.cypress.io/guides/references/changelog.html#1-0-2).
