### ISSUE TITLE
Cannot type() into different Elements using slatejs

### ISSUE THREAD

**Issue by mthomas87** [cypress-io/cypress#4603]
### Current behavior:

When typing into two different textfields:
```js
cy.get('[data-key="1975"]').type('Text1')
cy.get('blockquote[data-key="1987"]').type('Text2')
```

into the slatejs richtext editor, all of the text is saved in the first block.

DOM looks like this:

<img width="558" alt="Bildschirmfoto 2019-06-28 um 18 32 36" src="https://user-images.githubusercontent.com/6641079/60357570-41f1e880-99d4-11e9-92a9-ccb40d4f65b3.png">

The test run is also green as long as I don't make assertions.
The elements are found correctly but it seems the focus could not change.

### Desired behavior:

type() should only write into the element specified in the cy.get() function.
DOM-Result should look like:

<img width="634" alt="Bildschirmfoto 2019-06-28 um 18 34 57" src="https://user-images.githubusercontent.com/6641079/60357551-32729f80-99d4-11e9-8a1d-09aaa64b5f6b.png">
(edited manually)

### Steps to reproduce: (app code and test code)

You easily reproduce on the slatejs demo page with following test-code:
```js
describe('My First Test', function() {
  it('Visits slatejs', function() {

    cy.visit('https://www.slatejs.org/#/rich-text')
    cy.get('[data-key="1975"]').type('Text1')
    cy.get('blockquote[data-key="1987"]').type('Text2')
  })
})
```

### Versions

Cypress: 3.3.2
Chrome: 75

**Comment by jennifer-shehane** [comment]
Yeah, slatejs is definitely doing some tricks to get typing to work in the main editor, but show up in the correct DOM line within it. The code they ship is so obfuscated it's impossible to track down from this live site. 

The code is open source however here: https://github.com/ianstormtaylor/slate

**Comment by Bkucera** [comment]
Cypress treats a contenteditable element as a single input, so if the cursor is focused anywhere in the contenteditable, Cypress will start typing.

If you'd like to select a certain node inside the contenteditable, you can write a function that moves the cursor:

```js
const cursorToStart = (el) => {
  const doc = el.ownerDocument
  const sel = doc.getSelection()
  sel.removeAllRanges()
  const range = doc.createRange()
  range.selectNode(el)
  sel.addRange(range)
  sel.collapseToStart()
}

describe.only('My First Test', function() {
  it('Visits slatejs', function() {
    cy.visit('https://www.slatejs.org/#/rich-text')
    cy.get('[contenteditable]').type('Text1')
    cy.get('[data-key="1988"]')
    .then($el => {
      cursorToStart($el[0])
    })
    .type('Text2')
  })
})
```
