### ISSUE TITLE
Cannot find module 'intl'

### ISSUE THREAD

**Issue by bote795** [cypress-io/cypress#4607]
### Current behavior:
im getting following error: `Cannot find module 'intl' from '/Users/nicolasbotello/Documents/workspace/code/rmc/node_modules/lighthouse/lighthouse-core/lib/i18n`
```
Error: Cannot find module 'intl' from '/Users/nicolasbotello/Documents/workspace/code/rmc/node_modules/lighthouse/lighthouse-core/lib/i18n'
    at /Users/nicolasbotello/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/nicolasbotello/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/nicolasbotello/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/nicolasbotello/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/nicolasbotello/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/nicolasbotello/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at /Users/nicolasbotello/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:282:31
    at FSReqWrap.oncomplete (fs.js:152:21)
```

### Desired behavior:
No errors

### Steps to reproduce: (app code and test code)
install cypress
install lighthouse

```javascript
import lighthouse from 'lighthouse';
describe('My First Test', function() {
  it('Does not do much!', function() {
    expect(true).to.equal(true);
  });
});
```
repo:
https://github.com/bote795/cypress-test-tiny

### Versions
Lighthouse version: 5.1.0
Node.js version:v10.15.0
cypress version: 3.3.1

**Comment by bote795** [comment]
Talked with lighthouse team and they recommended adding `intl` since they were dev requirements and I followed it n got here: 

so I added `bufferutil`, `intl`, `utf-8-validate`
Then I got the following error
```
Uncaught TypeError: require.resolve is not a function

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```
also not sure if this helps: https://github.com/GoogleChrome/lighthouse/issues/9306

**Comment by jennifer-shehane** [comment]
Spec files within Cypress are run within the context of the browser. As stated by the lighthouse team, this dep is meant to be run in the Node context. 

>This sounds like a cypress issue. All of these require statements are guarded by try/catch and in normal node execution should pass right on through the optional requires just fine.

You can follow the instructions given here on how to utilize Node code in your Cypress spec files: https://on.cypress.io/using-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress
