### ISSUE TITLE
Ability to pass browser to headless cypress run

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#462]
### Are you requesting a feature or reporting a bug?
Feature

### Current behavior:
Currently, headless runs of Cypress invoked using `cypress run` always run on Electron. 

### Expected behavior:

I'd like the ability to pass a `--browser` option to the CLI's `cypress run`, specifying a locally installed browser by name to run Cypress within. Cypress could also optionally accept `--browser-path` where the path of the locally installed browser is passed in (so that if there are any logically issues w/ Cypress' behavior of finding a locally installed browser, this can be overridden until the issue is fixed.)

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
