### ISSUE TITLE
TypeError: cy.get(...).text is not a function

### ISSUE THREAD

**Issue by JayeshRGujar** [cypress-io/cypress#4629]
Cypress was working fine with the below code but currently throwing error  cy.get(...).text is not a function

```js
context('Testing Application', () => {
    beforeEach(() => {
        cy.test();
    })
    it('Verify Application List', () => {
        cy.get('.MuiButtonBase-root').each((item, index) => {
            cy.get(`:nth-child(${index + 1}) > .ButtonBase-root > .title__text`)
            .text()
                .then((itemDesc) => {
                    cy.get(`:nth-child(${index + 1}) > .ButtonBase-root`).click();
                    cy.get('.title__text').text().should('eq', itemDesc);
```
------
```json
"devDependencies": {
    "@cypress/snapshot": "^2.1.3",
    "cypress": "^3.3.2",
    "cypress-image-snapshot": "^3.0.2",
    "cypress-slack-reporter": "^0.3.1",
    "mocha": "^5.2.0",
    "mocha-junit-reporter": "^1.23.0",
    "mocha-multi-reporters": "^1.1.7",
    "mochawesome": "^4.0.0",
    "mochawesome-merge": "^2.0.1",
    "mochawesome-report-generator": "^4.0.0",
    "regenerator-runtime": "^0.13.2"
  }
```

**Comment by JayeshRGujar** [comment]
Above code was working before, but currently throwing error "cy.get(...).text is not a function"

**Comment by jennifer-shehane** [comment]
`.text()` is not a Cypress command. So the error you are getting is accurate. 

Perhaps you had a custom command written for `.text()` in one of the files in `cypress/support/*` that had defined a `text` command? Can you share the code from the files within `cypress/support/*`?

**Comment by Shelex** [comment]
You have typo in selector, thats why it can not get it:
```
:mth-child
```
Suppose it should be `nth-child`

**Comment by JayeshRGujar** [comment]
thanks @jennifer-shehane , strange, `text()` was working before , didn't had anything in `cypress/support/*` for text(). 
Nevertheless I got it working with `.invoke('text')` . 
@Shelex, `:mth-child` was a typo I made when drafting my post question(corrected above now), in my code it was always `nth-child`.

**Comment by TolikChirkov** [comment]
https://metebalci.com/blog/what-is-new-in-java-13/
What is new in Java 13 ? - Mete Balci

**Comment by TolikChirkov** [comment]
hsf-jde Show she
Handle this situation I would be interested 😉

**Comment by vjpr** [comment]
I think there has been an api deprecation...`cy.navigateByUrl` stopped working for me and I cannot seem to find any references to it anywhere via Google.

**Comment by Green125** [comment]
Having the same problem. Was just working, and now 20 minutes later, the same exact error as mentioned above

**Comment by jennifer-shehane** [comment]
`.navigateByUrl` was never a Cypress command. It may have been a command from another plugin. 

This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
