### ISSUE TITLE
Your framework is f*cking bullsh*t

### ISSUE THREAD

**Issue by alexeychikk** [cypress-io/cypress#4630]
It is impossible to configure your f\*cking moronic framework to work with TypeScript and Webpack when project is bigger than hello f\*cking world example you have. I spent all day tweaking different options and had no success. I'm f\*cking done. F\*ck you and your stupid framework.

**Comment by jennifer-shehane** [comment]
Hey @alexeychikk, sorry to hear about the frustrating experience you're obviously having 😞 	

We have a [community chat](https://on.cypress.io/chat) that can be helpful for debugging these types of things. 

We also have an issue open to improve our documentation with TypeScript + Webpack specifically - so it seems your not alone here. https://github.com/cypress-io/code-coverage/issues/19

And if you think you're encountering some sort of bug on our end, we can look at that if you can post it. 

Also, as a reminder, our GitHub repo falls under our [Code of Conduct](https://github.com/cypress-io/cypress/blob/develop/CODE_OF_CONDUCT.md) which encourages maintaining a positive environment here.

**Comment by alexeychikk** [comment]
@jennifer-shehane  Well, I'm really sorry. It's open source in the end. I've just had a really bad experience using cypress and gone mad.

**Comment by lluia** [comment]
> It's open source in the end

@alexeychikk the fact that this is an open source project doesn't justify you being rude 😉
