### ISSUE TITLE
error while loading shared libraries: libgtk-3.so.0

### ISSUE THREAD

**Issue by fanshyiis** [cypress-io/cypress#4631]
When I'm running in docker
But I did install gtk3
and i find it in /usr/lib/
why？？

![image](https://user-images.githubusercontent.com/15103283/60501015-e1252180-9ced-11e9-8835-854486d1e9fe.png)

Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

/home/tutor/.cache/Cypress/3.3.2/Cypress/Cypress: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

----------

Platform: linux (Centos - 7.1.1503)
Cypress Version: 3.3.2

**Comment by JohnWillker** [comment]
I fixed that running `sudo apt install libgtk-3-0`

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Comment by aldo-roman** [comment]
Hi, where can I find documentation on this requirement?

The official docs on [Continuous Integration](https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies) only declare `libgtk2.0-0`.

Also, I see the docker image [base:10](https://github.com/cypress-io/cypress-docker-images/blob/master/base/10/Dockerfile) only asks for GTK2, but [base:10.2.1](https://github.com/cypress-io/cypress-docker-images/blob/master/base/10.2.1/Dockerfile) (and up) declares GTK3.

**Comment by jennifer-shehane** [comment]
There is a PR in the docs to fix this here https://github.com/cypress-io/cypress-documentation/pull/1912

**Comment by alastair-todd** [comment]
@jennifer-shehane this is an issue for me on AWS Linux 2 running jenkins (and not through docker)

 `sudo yum install libgtk-3-0`

does not exist

did some googling and 

`gtk3-3.22.26-4.amzn2.i686` installs ` libgtk-3.so.0`

but the error pesists

**Comment by ruhkopf** [comment]
@alastair-todd had the same issue. `yum install gtk3` solved it for me.

**Comment by Tigersdkfz** [comment]
> @alastair-todd had the same issue. `yum install gtk3` solved it for me (compared to `yum install gtk3-3.22.26-4`, which did not resolve it)

Thank you bro, your command works for me

**Comment by InacomSj** [comment]
> @alastair-todd had the same issue. `yum install gtk3` solved it for me (compared to `yum install gtk3-3.22.26-4`, which did not resolve it)

Its work, thans

**Comment by ThamuGrg** [comment]
`yum install gtk3` gives `No package gtk3 available.`. Doing this on Amazon Linux.
