### ISSUE TITLE
Getting coordinates of an element

### ISSUE THREAD

**Issue by mohamedyoussefmaaref** [cypress-io/cypress#4632]
Hello

I m really blocked. i can't execute the function **getBoundingClientRect()** 
could you please give me some instructions or another way to get the coordinates.

Thank you in advance.

**Comment by Shelex** [comment]
```
cy.get(target)
        .then($target => {
            let coords = $target[0].getBoundingClientRect();
 })
```
Please use gitter chat for such questions next time :)

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

**Comment by joetidee** [comment]
I'm stuck on this too - was there a solution?
