### ISSUE TITLE
click event not propagated on ASP.NET Core Blazor app button element

### ISSUE THREAD

**Issue by vmandic** [cypress-io/cypress#4635]
Hi. Thanks for making Cypress. I am experiencing an issue with passing click events in a Blazor app. Blazor is _a framework for building interactive client-side web UI with .NET_ enabling users to use a single language for FE/BE i.e. C#. It does involve JavaScript "magic" (whose internals I am not aware) on the FE which might be causing this issue.

### Prerequisites:

- latest .NET Core 3 preview SDK version: "3.0.100-preview6-012264" (download [here](https://dotnet.microsoft.com/download/dotnet-core/3.0#3.0.0-preview6))
- ensure dotnet CLI new tool blazor templates are installed: `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2`
- trust .NET Core development SSL certificate with global tool: `dotnet dev-certs https --trust`, this will prompt you on windows to allow installing the cert
- ensure `https://localhost:5001` is free of apps

### Current behavior:

```JavaScript
it.only("opens counter page", function () {
    cy.visit("https://localhost:5001"); 
    cy.contains("Counter").click(); // works on anchor, navigates you ahead
    cy.contains("Click me").click();  // does not work on button
    cy.get(".content p").should("contain", 1);
}
```

Result: Click event does not cause the button to really _click_ and cause the `<p>` tag to increment its counter from 0 to 1.

Using `.trigger("click")`also has no effect.

Screenshot example of the issue (with assertion checking that 0 turned into 1):
![image](https://user-images.githubusercontent.com/1390895/60525241-4c6ef380-9cee-11e9-8671-7863aa934858.png)

### Desired behavior:

The `cy.contains("Counter").click();` should cause a real click event to be passed _into_ the DOM button element which will result in updating the `<p>` tag counter from 0 to 1.

### Steps to reproduce: (app code and test code)

1. Ensure prerequisites from this issue filing
2. `> git clone https://github.com/vmandic/blazor-cypress-playground`
3. open cloned project directory in terminal 1
4. `> cd src && dotnet run` (you should get a running ASP.NET Core server hosting the blazor app on: https://localhost:5001, you can check it in your browser)
5. open cloned project directory in terminal 2
6. `> npm install`
7. `> npm test` (runs cypress with `npx cypress run`)
8. Observe failed test (located in file `blazor.test.js`)

### Versions

Cypress: 3.3.2
OS: macOS Sierra Version 10.12.5 (experienced the same on Win 8.1)
Browser: Chrome 75
.NET Core SDK: 3.0.100-preview6-012264

**Comment by bahmutov** [comment]
Do you see the "page loaded" event that happens AFTER the "click"? Can you wait for the url to be the application url "/counter" before clicking? For example you could probably do

```js
cy.visit("https://localhost:5001/counter")
```
or wait for location to be `/counter`
```js
cy.visit("https://localhost:5001")
cy.location('pathname').should('equal', '/counter')
cy.contains("Counter").click()
```

**Comment by vmandic** [comment]
Hi. Bad copy paste in the initial code snippet, was missing `/counter`pathname after host, added it now in edit. 

So I tried what you said with:

```JavaScript
  it.only("opens counter page", function () {
    cy.visit("https://localhost:5001/counter");
    cy.location('pathname').should('equal', '/counter');
    cy.contains("Counter").click();
    cy.get(".content p").should("contain", 1);
  });
```

But again no luck.

Screenshot:
![image](https://user-images.githubusercontent.com/1390895/60528494-d6ba5600-9cf4-11e9-878c-96653fc65d0d.png)

Interesting, but clicking (with cy `.click()`) on anchor tags works. e.g. if clicked on the side menu item to navigate to a /counter page.

**Comment by bahmutov** [comment]
Hmm this is very weird because I see the page load event after click. If you click the button manually does it load the page too?

**Comment by vmandic** [comment]
Jeez I messed up with "Counter" and "Click me" strings in previous comments, sorry, fixed that now... but still not working. 
I click the button "Click me" in the "browser" on the right side of Cypress app the click is propagated, works.

Here is more:
![image](https://user-images.githubusercontent.com/1390895/60529052-0ddd3700-9cf6-11e9-90e1-3f8a4d7c5ac2.png)

**Comment by vmandic** [comment]
Also here you can see a trace produced by me clicking manually the side menu (which as mentioned also does work from cy's click() as it is a anchor element):
![image](https://user-images.githubusercontent.com/1390895/60529311-a07dd600-9cf6-11e9-9028-0680b7f447d1.png)

**Comment by gabbersepp** [comment]
Hey are you still faced with this problem?
I had a similar issue with a react app yesterday.
As a workaround you can use jquery's click:
`get(...).then($e => $e.click())` and maybe also `get(...).invoke("click")`

**Comment by vmandic** [comment]
> Hey are you still faced with this problem?
> I had a similar issue with a react app yesterday.
> As a workaround you can use jquery's click:
> `get(...).then($e => $e.click())` and maybe also `get(...).invoke("click")`

Hello @gabbersepp, I have not had the time to retest. Thanks for coming back at this once again. I'll retest with latest updates of Cypress and Blazor on .NET Core 3.1 this week and let you know here.

**Comment by vmandic** [comment]
FYI BTW this is taged OS: Windows, but the test was on a Mac*

**Comment by flotwig** [comment]
I was able to repro on Linux as well, I'll remove the OS tag

**Comment by xithan** [comment]
I run into the same issue while I was trying to figure out if I can use Cypress for a Blazor app. The suggested workarounds `get(...).then($e => $e.click())` and `get(...).invoke("click")` didn't help.

**Comment by gabbersepp** [comment]
@xithan You can give this a try: https://dev.to/gabbersepp/doing-native-clicks-with-cypress-io-and-open-file-dialog-18n6
In this example I show how one can use native click events in Cypress. This should work regardless of the underlying framework

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by singh-sukhpreet** [comment]
I had a similar issue and I resolved it by using [cypress-real-events](https://github.com/dmtrKovalenko/cypress-real-events) i.e cy.get(selector).realClick()
