### ISSUE TITLE
Flappy tests after .click() - using a before hook

### ISSUE THREAD

**Issue by sydneybarlow** [cypress-io/cypress#4639]
### **Current behavior**: 

I am struggling with flappy tests (flakey tests). **Randomly** Cypress cannot find DOM elements after a `.click()`. My errors read like:

```
CypressError: Timed out retrying: Expected to find element: '[data-e2e="row"]', but never found it.
```

I am using:
Cypress 3.3.2
Google Chrome Version 75.0.3770.100
Mac Mojave Version 10.14.5

### **Desired behavior**: 

I would like more consistent tests, that do not randomly fail.

### **Steps to reproduce**: 

I am trying to test a page redirect and then assert that the elements showed up on the page after the redirect. 

```js
describe("Everything beautifully works", () => {
  before(function () {
    cy.login() 
    cy.visit('/Homepage')
    cy.url().should('include', '/homepage')
  })

  it("App shows correct information", () => {
    cy.get('[data-e2e="nav-bar"]')
      .contains('Link to another page')
      .click()
    cy.url().should('include', '/otherpage') //<---- sometimes the tests will fail here
    cy.get('row').should(function (div) { //<---- this is where the tests usually fail
      expect(div).to.have.lengthOf(5)
    })
    cy.get('row').should(function (div) {
      expect(div).to.contain('A bunch of words')
    })
  })
})
```

Again - these tests RANDOMLY fail. Is there a better way to write these tests? Is there something that I am doing wrong?

**Comment by kylane** [comment]
Having similar issues - runs locally fine - fails on codeship. Will keep monitoring this thread.

**Comment by jennifer-shehane** [comment]
@sydneybarlow When your application navigates to the `/otherpage`, are there any XHR requests that need to complete before the `row` is visible on the page? If so, there is likely some variability in the response time of these XHRs - sometimes it can be slower, sometimes faster to respond resulting in flaky tests.

One of our engineers, @bahmutov , wrote a great blog post about this you can read here: https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

I would write tests using `cy.route()` and `cy.wait()` to verify that the XHR requests have responded completely before attempting to assert that the `row` elements are visible.

If you are still finding that this is a bug in Cypress. Comment with an example that we can run and reproduce locally to see the bug and we can reopen the issue.

**Comment by kylane** [comment]
@jennifer-shehane - Would this affect how this would pan out on codeship (given my local platform is a mac pro, and codeship could be running on a pi for all I know)?

**Comment by jennifer-shehane** [comment]
@kylane I've seen variability in response times that only exhibit in CI before. We also use the Electron (Chrome 61) browser to auto run tests in CI, which may be slightly different from a locally run `cypress open` with Chrome.

**Comment by sydneybarlow** [comment]
@jennifer-shehane - Thank you for the quick response and thank you for the article that you linked above, it really cleared things up theoretically. However about this comment...
>I would write tests using cy.route() and cy.wait() to verify that the XHR requests have responded completely before attempting to assert that the row elements are visible.
I was hoping to avoid using a **cy.route() and cy.wait()** because I wanted to follow the clicking experience that a _user_ would experience. I think that the `cypress-pipe` is a great idea but I'm not using jQuery and I also do not want to use a hard **cy.wait()** command either. Sometimes the tests run for over a minute, and I think that making these tests wait for _that long_ by default is the wrong way to go.
Do you have an idea on a different strategy? I will work on making a reproducible example.

**Comment by sydneybarlow** [comment]
I have tried the `cy.route()` and `cy.wait()` solution that you offered using the example code that I had from above...
```
  before(function () {
    cy.login() 
    cy.visit('/Homepage')
    cy.url().should('include', '/homepage')   //<--- this whole before() test is probably no longer 
                                                                      //         necessary, but - whatever, ignore it for now
  })

  it("App shows correct information", () => {
    cy.server()
    cy.route('**/applications').as('appPage')
    cy.visit('/applications')
    cy.wait('@appPage')                                // <----- it errors out here now
    cy.get('row').should(function (div) { 
      expect(div).to.have.lengthOf(5)
    })
    cy.get('row').should(function (div) {
      expect(div).to.contain('A bunch of words')
    })
  })
})
```
I will attach screenshots of what is happening, but in the browser of the Cypress app, the page is now totally done uploading to the browser, but it fails at the `cy.wait()` - and not only that but it says that the request was **_never made_**. ?????
<img width="620" alt="Screen Shot 2019-07-03 at 10 49 46 AM" src="https://user-images.githubusercontent.com/37448056/60602205-5a218900-9d81-11e9-861a-0163b8cf190b.png">

**Comment by jennifer-shehane** [comment]
The `cy.route()` definition is for defining a listener any XHR requests your application makes - so all of the `(XHR)` requests shown in the Command Log, you would then define a `cy.wait()` to wait for each of these requests to load. Because the content on your page is dependent on the data being loaded from these XHRs. 

<img width="620" alt="60602857-a28d7680-9d82-11e9-9083-42885789bf40 copy" src="https://user-images.githubusercontent.com/1271364/61272959-5c96d080-a7ce-11e9-9297-401a6e435099.png">

Please read the documentation for cy.route, cy.wait, and network requests - https://docs.cypress.io/guides/guides/network-requests.html

**Comment by sydneybarlow** [comment]
@jennifer-shehane All right. Thank you for the clarification. It's good to know I exhausted all avenues! Thank you for your patience and answering these questions.
