### ISSUE TITLE
Install cypress from zip Error when trying to use

### ISSUE THREAD

**Issue by MatthD** [cypress-io/cypress#4641]
# Current behavior:

I am using cypress in one of my monorepo project , we have a docker image for our firm & I try to add the cypress binary inside it via Dockerfile like this

```
COPY cypress.zip /tools
ENV CYPRESS_INSTALL_BINARY=/tools/cypress.zip
```

It seems to used it when I run npm install but when I try to use cypress `cypress run`I got :

```bash

No version of Cypress is installed in: /root/.cache/Cypress/3.3.2/Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: /root/.cache/Cypress/3.3.2/Cypress/Cypress

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.3.2
```

### Versions

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.3.2

**Comment by jennifer-shehane** [comment]
After setting the location for the Cypress  binary, you need to then run `npm install cypress` to install it on your machine as detailed in the docs here: https://on.cypress.io/installing-cypress#Install-binary

Are you running an install command?

**Comment by MatthD** [comment]
Yes totally I am running a simple `npm install ` and cypress is in my
package.json dependencies as well,
Should I run `npm install cypress` after a npm install ?

Le mer. 3 juil. 2019 à 09:07, Jennifer Shehane <notifications@github.com> a
écrit :

**Comment by bahmutov** [comment]
@MatthD can you paste output from `npm install` please? I bet it is not running post-install hook script

**Comment by MatthD** [comment]
This is what I got ![img1](https://image.noelshack.com/fichiers/2019/27/3/1562164567-capture-d-ecran-2019-07-03-a-16-25-36.png)

At the end: 

![imgend](https://image.noelshack.com/fichiers/2019/27/3/1562164567-capture-d-ecran-2019-07-03-a-16-35-32.png)

**Comment by bahmutov** [comment]
right, BUT if you install in docker container A and then run in docker container B you need to copy the app folder (which you do) AND the folder where Cypress binary is installed - which is `~/.cache/Cypress`. Copy that folder too and the tool should be installed. In the run container you can verify it by running commands

```
npx cypress cache path
npx cypress cache list
npx cypress verify
```

**Comment by bahmutov** [comment]
you can find more info about caching Cypress at http://on.cypress.io/caching

PS: also, just as another suggestion you can start with the Docker image with Cypress pre-installed globally https://github.com/cypress-io/cypress-docker-images/tree/master/included
