### ISSUE TITLE
Basic auth for different subdomain not working since 3.3.2

### ISSUE THREAD

**Issue by feedm3** [cypress-io/cypress#4646]
### Current behavior:

My test setup looks like the following:

- Visit the app on `dev.example.com`
- User is not logged in, so click on "Login"
- User gets redirected to `dev-login.example.com` where he can login
- do the rest ...

Both the app `dev.example.com` and `dev-login.example.com` are secured with the same basic auth credentials, I therefore extended the `visit` command:

```
Cypress.Commands.overwrite('visit', ( orig, url, options ) => {
    options = options || {};
    options.auth = {
        username: Cypress.env('USERNAME'),
        password: Cypress.env('PASSWORD'),
    };
    return orig(url, options);
});
```

This was working totally fine until the latest release `3.3.2`. 

Since `3.3.2`, the auth header only gets set for `dev.example.com` and as soon as the url changes to `dev-login.example.com` the basic auth alert pops up and the test doesn't continue anymore. 

### Desired behavior:

If a subdomain changes, the `visit` method should still be called and set the `auth` header. This was always the case up until `3.3.1`.

### Versions

- Cypress 3.3.2
- Node 8

**Comment by flotwig** [comment]
Passing HTTP basic auth to sibling subdomains is not correct behavior, this was fixed in 3.3.2. Check out this issue comment: https://github.com/cypress-io/cypress/issues/4633#issuecomment-507703135

**Comment by feedm3** [comment]
All right. Can you recommend me how I can then set the basic auth for the login page?

I tried to extract the `href` and do a manual `cy.visit` with the auth header as options. But once on the login page, there are a lot of other redirects happening until the users gets finally redirected back to the app with the auth cookie, so extracting all the requests manually and "warpping" them in `cy.visit` and `cy.request` is very cumbersome and probably also pretty error prone.

**Comment by flotwig** [comment]
Is it necessary to use both HTTP Basic Auth and cookie auth for your application? If you have it secured with a normal session-based login, the basic auth could be superfluous.

I would recommend that you don't log in in your tests - instead, programmatically obtain an auth cookie from your test server and then use [`cy.setCookie`](https://on.cypress.io/setcookie) to send it with future requests, which is also what is recommended in the [Best Practices](https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State) document.

---

That being said, Cypress could also do with some more robustness around HTTP Auth... it would be nice for users to be able to specify auth credentials for multiple domains besides the one that was just cy.visited. Perhaps we could add some kind of event to allow the test to react appropriately. Something like this would be nice I think: 

```js
Cypress.on('http:auth:requested', (url, realm, login) -> {
	// figure out the correct credentials, then...
	login(username, password) // allow Cypress's proxy to forward the credentials onward
})
```

**Comment by feedm3** [comment]
The whole dev environment of the product is secured by basic auth (this is a pattern which a lot of customers I was / I'm working for are using), so it cannot be turned of.

Programmatically logging in will get very messy. The login flow requires a bunch of redirects (also with different subdomains) and a CSRF token (already found [a recipe for that](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/logging-in__csrf-tokens)). As it's getting pretty complex (in comparison to not need to do anything with working subdomain basic auth) I want to avoid that if it's somehow possible.

**Comment by flotwig** [comment]
@feedm3 Definitely, this is something that is not easy to do in Cypress, though it should be. I've started another issue to track a new feature to allow users to do what you're trying to do: #4670 Let me know if you have feedback on the proposed design, it's a lot more flexible than the current implementation.

Closing this issue since it's working as designed.
