### ISSUE TITLE
No cypress commands are working

### ISSUE THREAD

**Issue by kadamAbhijeetBalasaheb** [cypress-io/cypress#4648]
below is my code

*************

const waitForPlayerDbRequests = ['@playerdb/metadata', '@playerdb/lookups', '@playerdb/search']
const waitForCompetitionsRequests = ['@competition/sop', '@competition/delta']

const getContractNames = () => new Promise((resolve, reject) => {
    var contractNames = []; 

    cy.get("div[ng-repeat='c in vm.costcenters']>p")
        .each((el) => {
            const contractNameText = el.text();
            //cy.log(contractNameText);
            contractNames.push(contractNameText);
        }).then(async () => {

            resolve(contractNames);
        })
})

const getPlayerName = (contractName) => new Promise((resolve, reject) => {
    let playerNames = [];
    cy.xpath("//p[contains(text(),'" + contractName + "')]").click();
    let contractPlayersXpath = "//p[contains(text(),'" + contractName + "')]/..//h3";

    cy.xpath(contractPlayersXpath)
        .each((playerElement) => {
            let playerName = playerElement.text();
            playerNames.push(playerName);
        })
        .then(() => {
            let contractNamePlayerNamesObject = { contractName: playerNames };
            resolve(contractNamePlayerNamesObject);
        });
});
describe('abk pto describe', () => {
    it('abk pto it', async () => {

    let module = 'playerdb';
        var waitFor
        if (module=='playerdb') {
          waitFor = waitForPlayerDbRequests
        }
        else if (module=='competition') {
          waitFor = waitForCompetitionsRequests
        }
      
        cy.login({
          module,
          waitFor
        })

        cy.get("button[class='btn btn-module dropdown-toggle ng-binding']").click();
        cy.get("ul[id='top-menu'] li a[ng-href='/payment/']").click();   

        let contractNames = [];
        contractNames = await getContractNames();
    
        const conName = contractNames[0];
        cy.log('conName' + conName);

        
    const object = await getPlayerName(conName);
    let playerNames = object.contractName
    let playerName = playerNames[0];
    console.log('playername - > ' + playerName);

    let playerNameXpath = '//h3[text()="' + playerName + '"]';
    cy.xpath(playerNameXpath).click();
})
})

************

my last cy.xpath command is not working. dont see any error also :( please help

**Comment by dialex** [comment]
@kadamAbhijeetBalasaheb you can do better than this:

- Use markdown properly to format all code "as code"
- While you're at it, [format your JS code](https://www.prettifyjs.net/) to have proper indentation
- Don't write a title saying that all commands are not working, and then say a single command `cy.xpath` is not working
- Define not working... what were you expecting? what happened instead?
- Logs? Cypress version? What did you try to solve it...

**Comment by kadamAbhijeetBalasaheb** [comment]
so sorry for this. thanks for the inputs. i will keep these in mind.

**Comment by kadamAbhijeetBalasaheb** [comment]
not an issue.
