### ISSUE TITLE
Feature: Show total percentage of tests failed

### ISSUE THREAD

**Issue by dialex** [cypress-io/cypress#4649]
Currently, Cypress displays the % of specs failed.

That's fine, yet **I would find more useful to know the % of tests failed**. Right now I have only 8% of tests failing, but since they are on two files, the failed spec percentage is 30% -- quite different.

I would make a PR if I had permissions to. Instead here's the code I changed, on `run.coffee`:

```js
formatFooterSummary = (results) ->
  { totalFailed, runs } = results

  ## pass or fail color
  c = if totalFailed then "red" else "green"

  total = runs.length ## <-- MOVED
  percentFailed = Math.round(totalFailed / runs.length * 100) ## <-- ADDED
  phrase = do ->
    ## if we have any specs failing...
    if not totalFailed
      return "All specs passed!"

    ## number of specs
    failingRuns = _.filter(runs, "stats.failures").length
    percent = Math.round(failingRuns / total * 100)

    "#{failingRuns} of #{total} failed (#{percent}%)"

  return [
    color(phrase, c),
    gray(duration.format(results.totalDuration)),
    colorIf(results.totalTests, "reset"),
    colorIf(results.totalPassed, "green"),
    colorIf("#{totalFailed} (#{percentFailed}%)", "red"), ## <-- EDITED
    colorIf(results.totalPending, "cyan"),
    colorIf(results.totalSkipped, "blue"),
  ]
```

**Comment by jennifer-shehane** [comment]
Hey @dialex, you are always free to open a PR in our repo. We may have to add an extra row to show this information so that we don't break any current implementations that may rely on the specs failed count.

**Comment by sainthkh** [comment]
Closing for now because it got no thumbs-up after a year.
