### ISSUE TITLE
async in beforeEach causes actions to be performed twice in test

### ISSUE THREAD

**Issue by kubas246** [cypress-io/cypress#4651]
### Current behavior:

*WHEN* `beforeEach` is using async function (e.g. `beforeEach(async() => {})`)
*THEN* in tests (e.g. `it('test1', () => {})`) every action is performed twice.

### Desired behavior:

During test every action should be performed exact amount of times it's called in the code.

### Steps to reproduce: (app code and test code)

Create tests where you set async function in `beforeEach`. Example code:

```js
describe('some tests', () => {
beforeEach(async() => {
    const data = {
        'data':'someData'
    }
    cy.visit('url');
    const window = await cy.window();
    window.postMessage(JSON.stringify(data), '*');
})

it('test1', () => {
    cy.get('#login-field').type('email', {force: true});
    cy.get('#password-field').type('password', {force: true});
    cy.get('#login-button').click({force: true});
})
})
```

### Versions

Cypress 3.3.2
Chrome v75.0.3770.100
Windows 10 1903 build 18362.175

**Comment by gabbersepp** [comment]
You can not use async/await pattern as stated here:
https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous
-> "Why can’t I use async / await?"
Please try your code without that.

**Comment by jennifer-shehane** [comment]
@kubas246 There is an issue open to support await in Cypress you should follow here: https://github.com/cypress-io/cypress/issues/1417
