### ISSUE TITLE
Mocha teamcity reporter does not work with Mocha 6

### ISSUE THREAD

**Issue by jinder** [cypress-io/cypress#4654]
When using Mocha 6 or above and @cypress/mocha-teamcity-reporter, the following error occurs:

```
TypeError: Cannot read property 'duration' of undefined
at Runner.<anonymous> (D:\BuildAgents\BuildAgent2\work\e66087cafd2fca06\mosaic-core\e2e\node_modules\@cypress\mocha-teamcity-reporter\lib\teamcity.js:55:78)
```

This is caused by the issue reported here: https://github.com/travisjeffery/mocha-teamcity-reporter/issues/49

A fix is available, but needs to be merged into the forked @cypress/mocha-teamcity-reporter and published to NPM.

**Comment by jennifer-shehane** [comment]
There's a PR to fix this open here: https://github.com/cypress-io/cypress/pull/4643

I need to add some extra tests to make sure the upgrade is ok.
