### ISSUE TITLE
Blacklisting only works sometimes (flaky tests)

### ISSUE THREAD

**Issue by dialex** [cypress-io/cypress#4656]
### Current behavior:

I had 6 tests, all passed, all stable.

![Screenshot 2019-07-03 at 16 25 37](https://user-images.githubusercontent.com/2140450/60723955-081d6680-9f2d-11e9-8a60-e9b8df570fe4.png)

Now I have 20 tests, and previous stable tests are now flaky.

I blacklisted a domain (`googlesyndication.com`), but **sometimes** the request is not blacklisted and Cypress times out waiting for a reply. Why?

Am I missing something? Is there a workaround?

- This issue is very similar to https://github.com/cypress-io/cypress/issues/2714, which is forgotten since Nov'18.
- Another user detected the same behaviour in Feb'19 https://github.com/cypress-io/cypress/issues/1039#issuecomment-461761215, but got no reply.
- And here I am now, Jul'19, worried that Cypress is not fit for purpose, just like this comment https://github.com/cypress-io/cypress/issues/2938#issuecomment-505313268 from the same user flagging the issue five months ago.

### Desired behavior:

I want blacklisted domains to be ignored, **always**.

### Versions

Cypress 3.2.0, MacOS 10.14.5, Chrome 75

**Comment by flotwig** [comment]
@dialex We've made a lot of network fixes between 3.2.0 and 3.2.2, could you let me know if you still experience this issue in 3.3.2?

If so, could you provide the [full debug logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) from when you experience the issue?

**Comment by dialex** [comment]
I upgraded to `3.3.2` and all tests are passing consistently: I got 5 runs all green, looks promising :)
