### ISSUE TITLE
Cypress states a 404 when using Azure Blob Storage

### ISSUE THREAD

**Issue by alucardu** [cypress-io/cypress#4661]
#4239 

# Current behavior:

Cypress states a 404 when doing a test but the page does actually load. I'm testing a ReactJS application on a Azure Blob Storage environment.

### Steps to reproduce: (app code and test code)

Host  a ReactJS app on a Azure Blob Storage and run a Cypress test against it.

### Versions

Cypress package version: 3.3.1
Cypress binary version: 3.3.1
Browser: Chrome
OS: Hosted Windows 2019 with VS2019

**Comment by jennifer-shehane** [comment]
@alucardu Can you provide a repo with the ReactJS app + Azure Blog Storage with a failing test to run in Cypress? Thanks

**Comment by alucardu** [comment]
I've found the issue. When my ReactJS app is opened in the browser: https://www.myurl.io/ it redirects to: https://www.myurl.io/onboarding/welcome 

This Cypress test succeeds:

    const url = `${Cypress.config().baseUrl}`;
    describe("Open index.html", () => {
      it("can open index.html", () => {
        cy.visit(url);
      });

      it("contains text", () => {
        cy.contains("Welcome at Embrace!");
      });
    });


But when I add `/onboarding/welcome` to the baseUrl:

    const url = `${Cypress.config().baseUrl}/onboarding/welcome`;
    describe("Open index.html", () => {
      it("can open index.html", () => {
        cy.visit(url);
      });

      it("contains text", () => {
        cy.contains("Welcome at Embrace!");
      });
    });

The Cypress test fails. If I go to the base url in Chrome I can open the page and everything is fine. When I navigate to the `/onboarding/welcome` url I get a 404:

![image](https://user-images.githubusercontent.com/779921/61059894-16222a00-a3fa-11e9-8f16-339a012bc7f0.png)

In my Azure Storage Account > Static Website I've set my error document path to index.html:

![image](https://user-images.githubusercontent.com/779921/61060085-5681a800-a3fa-11e9-9ed1-45d9ffda95e6.png)

When I remove the index.html from the error document path I also get a 404 in Chrome:

![image](https://user-images.githubusercontent.com/779921/61060227-82049280-a3fa-11e9-86eb-09b2d95248cd.png)

So it looks like Chrome can handle the redirect, but the Chrome browser in Cypress cannot.

**Comment by alucardu** [comment]
I've resolved the issue by adding `{ failOnStatusCode: false }` to the visit command:

    cy.visit(url, { failOnStatusCode: false });

**Comment by jennifer-shehane** [comment]
@alucardu Can you tell me what version of Chrome you have that is running Cypress?

**Comment by alucardu** [comment]
I am using Electron to run Cypress.

**Comment by thebinaryfelix** [comment]
> I've resolved the issue by adding `{ failOnStatusCode: false }` to the visit command:
> 
> ```js
>     cy.visit(url, { failOnStatusCode: false });
> ```

This was a valid workaround for me also. I Had the same problem with Cypress 3.4.1.

I can't visit any url succeeding a '/'. If I visit the home URL with `cy.visit(https://www.mypage.com/)` it works.

If I try to execute `cy.visit('https://www.mypage.com/something')` it returns a 404 error.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
