### ISSUE TITLE
cy.server onResponse/onAnyResponse only returns null/{} body

### ISSUE THREAD

**Issue by adieCodes** [cypress-io/cypress#4665]
### Current behavior:

I’m looking to run an npm command that will use `cy.server` and `cy.route` to grab the responses from my api and move these into fixture files to mock. The theory being this will make my tests a little faster, whilst also making it easier to know what to test against. For example, how many list items should be rendered based on the api response.

The problem I’m facing is that I can see the majority of the xhr data from the route but for whatever reason the body is either an empty array or `null` on **all** endpoints.

For context, this [article](https://medium.com/ax2-inc/dynamic-xhr-responses-recording-stubbing-with-cypress-9257d4f730cd) explains the process I’m trying to emulate. I’ve removed `win.fetch` via the `support/index.js` file to allow me to monitor requests made with fetch.

Everything appears to be working as my tests are passing, it just seems to be missing the body when adding to fixtures. 

I've discussed this in the Cypress Gitter room and it was suggested that I replace `onRequest` with `onAnyResponse` but that still returns `null` responses (just in a different shape).

I've found that making requests with `cy.request` returns the `body` as expected. So my current workaround is to use `cy.server` and `cy.route` to make an array of the requests made and then duplicate them with `cy.request` to get the data.

An example of the returned xhr data in my fixture is:

``` json
{
    "url": "http://example.com/route",
    "method": "GET",
    "data": {
      "xhr": {
        "method": "GET",
        "url": "http://example.com/route",
        "id": "xhr64"
      },
      "id": "xhr64",
      "url": "http://example.com/route",
      "method": "GET",
      "status": 200,
      "statusMessage": "200 (OK)",
      "request": {
        "headers": {
          "authorization": "Bearer examplestuffhere...",
          "x-stuff": "12345",
          "x-stuff2": "12345",
          "x-stuff3": "12345"
        },
        "body": null
      },
      "response": {
        "headers": {
          "x-token": "exampletoken",
          "content-type": "application/json; charset=utf-8",
          "cache-control": "no-cache"
        },
        "body": {}
      },
      "duration": 532
    }
  }
```

### Desired behaviour

Capturing all requests and their responses to be able to create fixture files, improving test speed and providing useful data to tests against. So the below would create a fixture file that would include the response body.

```js
describe('MyApp', () => {
  // We declare an empty array to gather XHR responses
  const xhrData = [];
  after(() => {
    // In record mode, save gathered XHR data to local JSON file
    if (Cypress.env('RECORD')) {
      const path = './cypress/fixtures/fixture.json';
      cy.writeFile(path, xhrData);
    }
  });
  it('Works', () => {
    cy.server({
      // Here we handle all requests passing through Cypress' server
      onResponse: (response) => {
        if (Cypress.env('RECORD')) {
          const url = response.url;
          const method = response.method;
          const data = response.response.body;
          // We push a new entry into the xhrData array
          xhrData.push({ url, method, data });
        }
      },
    });
    // This tells Cypress to hook into any GET request
    if (Cypress.env('RECORD')) {
      cy.route({
        method: 'GET',
        url: '*',
      });
    }
    if (!Cypress.env('RECORD')) {
      cy.fixture('fixture').then((data) => {
        for (let i = 0, length = data.length; i < length; i++) {
          cy.route(data[i].method, data[i].url, data[i].data);
        }
      });
    }
    // Your test scenario here
  });
});
```

**Comment by chauey** [comment]
I cannot get it to go into the onResponse handler method, can someone let me know some reasons why?

**Comment by jennifer-shehane** [comment]
I am not experiencing this in the example below - maybe you can pin down the differences to track down the issue, but I'd need a reproducible example to keep this open as a bug in Cypress. 

```js
describe('MyApp', () => {
  // We declare an empty array to gather XHR responses
  let xhrData = []

  after(() => {
    // In record mode, save gathered XHR data to local JSON file
    const path = './cypress/fixtures/fixture.json'

    cy.debug().writeFile(path, xhrData) // try .debug() here
  })

  it('Works', () => {
    cy.server({
      // Here we handle all requests passing through Cypress' server
      onResponse: (xhr) => {
        // debugger Try a DEBUGGER HERE
        const url = xhr.url
        const method = xhr.method
        const data = xhr.response.body

        const obj = { url, method, data }

        // We push a new entry into the xhrData array
        xhrData.push(obj)
      },
    })
    // This tells Cypress to hook into any GET request
    cy.route({
      method: 'GET',
      url: '*',
    }).as('getComment')

    cy.visit('https://example.cypress.io/commands/network-requests')
    cy.get('.network-btn').click()
    cy.wait('@getComment')
  })
})
```

My fixture.json after the run

```json
[
  {
    "url": "https://jsonplaceholder.cypress.io/comments/1",
    "method": "GET",
    "data": {
      "postId": 1,
      "id": 1,
      "name": "id labore ex et quam laborum",
      "email": "Eliseo@gardner.biz",
      "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
    }
  }
]
```

**Comment by allyraza** [comment]
Hi there,

I am still experiencing this `xhr.response.body` is returning null value.

thanks

**Comment by julian-sf** [comment]
For anyone still looking here, the problem is that the body is a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob).  The solution is this:

```typescript
// We push a new entry into the xhrData array
if (body && 'text' in body) {
  // body is a Blob, so .text() it to get the value
  body.text().then((data: string) => {
    xhrData[url] = {
      ...xhrData[url],
      [method]: { status, body: JSON.parse(data) },
    };
  });
} else {
  xhrData[url] = {
    ...xhrData[url],
    [method]: { status, body },
  };
}
```
