### ISSUE TITLE
Some XHRs loop infinitely since 3.3.1

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4668]
### Current behavior:
I noticed the some of our API, mainly XHR requests were continuously getting looped indefinitely when i upgraded Cypress from 3.2.0 to 3.3.0. So we rolled it back.
Now we hit some other bugs, for which we wanted to upgrade to Cypress 3.3.1, once again i am getting a similar issue.

1. For some of the tests some XHR requests are loading indefinitely.
2. The Timer is not incrementing
3. The Test Runner is not responding
 
<img width="501" alt="cypress_1" src="https://user-images.githubusercontent.com/45758076/59108876-936d0180-8959-11e9-9adb-afab8a7e2be1.png">
<img width="1439" alt="cypress_2" src="https://user-images.githubusercontent.com/45758076/59108878-94059800-8959-11e9-9ea7-60a260d8c486.png">
<img width="938" alt="cypress_3" src="https://user-images.githubusercontent.com/45758076/59108879-94059800-8959-11e9-9f1a-63deb1b1a91c.png">

```
------------ Configuration -------
{
animationDistanceThreshold: 5,
baseUrl: null,
blacklistHosts: null,
chromeWebSecurity: true,
defaultCommandTimeout: 20000,
env: {
CLIENT: 'demoaccount',
failOnSnapshotDiff: false},
execTimeout: 60000,
fileServerFolder: '',
fixturesFolder: 'cypress/fixtures',
hosts: null,
integrationFolder: 'cypress/integration',
modifyObstructiveCode: true,
numTestsKeptInMemory: 1,
pageLoadTimeout: 60000,
pluginsFile: 'cypress/plugins',
port: null,
reporter: 'spec',
reporterOptions: null,
requestTimeout: 5000,
responseTimeout: 30000,
screenshotsFolder: 'cypress/screenshots',
supportFile: 'cypress/support',
taskTimeout: 60000,
testFiles: '**/*.{spec.js,feature}',
trashAssetsBeforeRuns: true,
userAgent: null,
video: true,
videoCompression: 32,
videoUploadOnPasses: true,
videosFolder: 'cypress/videos',
viewportHeight: 660,
viewportWidth: 1000,
waitForAnimations: true,
watchForFileChanges: true}
-----------
```

Scenario failing- `Validating the time/date picker yields a correct date in the calendar while scheduling email message (we are using cucumber library)`

### Desired behavior:

Things are fine in 3.2.0, except some known issues like forwarding of socket failures related error in HTTP api level, which causes some parse error (Internal Error 500) in cypress.

### Steps to reproduce: (app code and test code)

I am sharing some snippet of the login code, which we use to login. 

```js
Cypress.Commands.add(
	'login',
	{
		prevSubject: 'true'
	},
	(client, user) => {
		cy.logout();
		return cy.visit(`${BASE_URL}`).then(() => {
			return cy.getCookie('csrftoken').then(({ value }) => {
				return cy
					.request({
						url: `${client.url}/accounts/login`,
						form: true,
						method: 'POST',
						body: {
							username: client.users[user].email,
							password: client.users[user].password,
							csrfmiddlewaretoken: value
						}
					})
					.then(() => client);
			});
		});
	}
);
```

### Versions
cypress - 3.3.1
electron - 61
OS - Mac OS Mojave 10.14.5

### Attachments
[cy_3.3.0_debug.log](https://github.com/cypress-io/cypress/files/3276250/cy_3.3.0_debug.log)
[cy_3.3.1_debug.log](https://github.com/cypress-io/cypress/files/3276251/cy_3.3.1_debug.log)

---

During my re-testing with version 3.3.2 i can see the same issue is occurring again and i confirm that this occurs only in electron.

One of the calls that (XHR) that kept looping was `mark_as/` . I am attaching a HAR dump file for the network requests during the test. I hope that would be useful.

[cypress.har.txt](https://github.com/cypress-io/cypress/files/3344077/cypress.har.txt)

p.s. Please rename `cypress.har.txt` to `cypress.har` if your HAR analyser needs that.

_Originally posted by @joydeep100 in https://github.com/cypress-io/cypress/issues/4411#issuecomment-507124618_

**Comment by flotwig** [comment]
@joydeep100 I looked at the HAR you supplied, but I can't find the XHR requests that you mentioned as looping. Specifically, in your test, it looks like the `/api/v1/oauth2_connections` endpoint is loading forever, but in the HAR there is no such URL being visited:

![image](https://user-images.githubusercontent.com/1151760/60814615-ee199900-a163-11e9-93cf-ec3a9df0a21e.png)

Also, is your `blacklistHosts` option still empty like in your original post? I notice that Google Adsense and Analytics, among others, appear to have been blocked:

![image](https://user-images.githubusercontent.com/1151760/60814698-1bfedd80-a164-11e9-8c17-75111e2b05c4.png)

---

I can't reproduce the issue you're running in to since 3.3.2. To get this solved, it would help me a lot if you could create an example repo that I can clone and run locally so I can see the problem first-hand and debug it.

**Comment by flotwig** [comment]
Potentially related (HTTP requests never receiving response): #4656

**Comment by joydeep100** [comment]
@flotwig I have uploaded a video, so that you can see what i am able to see. I am not sure if u could share a reproducible code at this point. I am okay to do a screen share (maybe zoom ) to debug further any time this week before friday. If thats okay with you. 

https://drive.google.com/open?id=1bKcIkowEg7vJ-pdDZs3Et9QKD54q0ugH

**Comment by flotwig** [comment]
@joydeep100 I don't have access to view that file. Do you think you could create a small example repo that does similar things to your test that showcases the bug occurring? It will be hard for me to debug without being able to reproduce the issue on my machine.

**Comment by joydeep100** [comment]
@flotwig I am pretty new to js and cypress :P I really doubt i would be able to create an example test for this. As this interaction is with our React based App.

**Comment by joydeep100** [comment]
@flotwig @jennifer-shehane This issue got fixed in 3.4.1. I have tested it and works properly. Please close this.

**Comment by rangrasjay** [comment]
Facing the same issue in 3.4.1

**Comment by flotwig** [comment]
@rangrasjay Please open a new issue to describe what you're experiencing.
