### ISSUE TITLE
Create + document formal API's around cy internal properties

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#467]
- [ ] Rename the internal `cy.prop` to `cy.state` and move store to a private property.
- [ ] Rename the internal `cy.private` to `cy.privateState` and move store to a private property.
- [ ] Throw a very specific error message when accessing the old properties directly (which was never supported or documented)
- [ ] Throwing on `cy.props` or `cy.privates` should tell the user to go through `cy.state(...)` or `cy.privateState(...)`
- [ ] Document `cy.state` and why you'd use it https://github.com/cypress-io/cypress-documentation/issues/108

**Comment by jennifer-shehane** [comment]
@chrisbreiding @brian-mann Can either of you confirm:

1. Was this work ever done?
2. Does this work still need to be done?

**Comment by proCrichard** [comment]
Any progress here?  Need information on `cy.state()`. Specifically how to add objects/images to test context for use with reporters like Mochawesome.

**Comment by andrey-semin** [comment]
+1

**Comment by jennifer-shehane** [comment]
Closing since there hasn't been activity here in a while. Refer to issue open in documentation for cy.state() work: https://github.com/cypress-io/cypress-documentation/issues/108
