### ISSUE TITLE
We could not identify a known browser at the path you provided

### ISSUE THREAD

**Issue by JayeshRGujar** [cypress-io/cypress#4679]
### Current behavior:

**Command:** 

`npx cypress run --browser C:\\Users\\333765\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe`

**Output**
```
We could not identify a known browser at the path you provided: 

C:\Users\333765\AppData\Local\Google\Chrome\Application\chrome.exe

The output from the command we ran was:

Version=74.0.3729.108
------
"devDependencies": {
    "@cypress/snapshot": "^2.1.3",
    "cypress": "^3.3.2",
    "cypress-image-snapshot": "^3.0.2",
    "cypress-slack-reporter": "^0.3.1",
    "mocha": "^5.2.0",
    "mocha-junit-reporter": "^1.23.0",
    "mocha-multi-reporters": "^1.1.7",
    "mochawesome": "^4.0.0",
    "mochawesome-merge": "^2.0.1",
    "mochawesome-report-generator": "^4.0.0",
    "regenerator-runtime": "^0.13.2"
  }
```
Question - Can we run cypress test on remote machine.

**Comment by flotwig** [comment]
Hey @JayeshRGujar, could you share [debugging logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) from when you try to launch the browser? It will help shed some light on the issue.

Also, try this fix, it has worked for other people: https://github.com/cypress-io/cypress/issues/4260#issuecomment-507767328

**Comment by JayeshRGujar** [comment]
@flotwig Somehow I am able to find the solution by adding google chrome in Program files. After running the below command I am able to see chrome.
**Command**
npx cypress **open** --browser C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe

![image](https://user-images.githubusercontent.com/50454566/60916857-2220b700-a255-11e9-969b-482defd4d30e.png)

Issue is "npx cypress **open**"is working But "npx cypress **run**" is still having issues We could not identify a known browser at the path you provided: `C:\User\333765\Google\Chrome\Application\chrome.exe`
The output from the command we ran was:

**My Question is :- Can we run cypress test on remote machine.**

**Comment by flotwig** [comment]
Could you share [debugging logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) from when you try to launch the browser in `run` mode? It will contain the exact error.

Did you try the fix I linked above? https://github.com/cypress-io/cypress/issues/4260#issuecomment-507767328

Yes, you can run Cypress tests in Chrome on a remote machine.

**Comment by JayeshRGujar** [comment]
Please find the below debugging logs:
------
  cypress:launcher checking one browser chrome +0ms
  cypress:launcher looking up chrome on win32 platform +0ms
  cypress:launcher exe path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe +0ms
  cypress:server:profilecleaner found 1 profile folders: [ 'C:/Users/333765/AppData/Roaming/Cypress/Partitions/run-27296' ] +0ms
  cypress:server:profilecleaner finding process by pid: 27296 +1ms
  cypress:launcher found C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ? true +12ms
  cypress:server:profilecleaner found 0 root level profile matches: [] +33ms
  cypress:server:profilecleaner found 0 profile folders: [] +0ms
  cypress:launcher Version=74.0.3729.108 +140ms
  cypress:launcher browser chrome at 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' version 74.0.3729.108 +0ms
  cypress:launcher setting major version for {"name":"chrome","family":"chrome","displayName":"Chrome","version":"74.0.3729.108","path":
  "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"} +1ms
  cypress:launcher browser chrome version 74.0.3729.108 major version 74 +0ms
  cypress:launcher checking one browser chromium +1ms
  cypress:launcher looking up chromium on win32 platform +0ms
  cypress:launcher exe path C:\Program Files (x86)\Google\chrome-win32\chrome.exe +0ms
  cypress:launcher found C:\Program Files (x86)\Google\chrome-win32\chrome.exe ? false +1ms
  cypress:launcher browser chromium not installed +1ms
  cypress:launcher checking one browser canary +0ms
  cypress:launcher looking up canary on win32 platform +0ms
  cypress:launcher exe path C:\Users\333765\AppData\Local\Google\Chrome SxS\Application\chrome.exe +0ms
  cypress:launcher found C:\Users\333765\AppData\Local\Google\Chrome SxS\Application\chrome.exe ? false +1ms
  cypress:launcher browser canary not installed +0ms
  cypress:server:cypress exiting with err { Error: We could not identify a known browser at the path you provided:
  `C:\Users\333765\AppData\Local\Google\Chrome\Application\chrome.exe`

The output from the command we ran was:
    at get (C:\Users\333765\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\lib\errors.js:294:11)
    at Object.throwErr [as throw] (C:\Users\333765\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\lib\errors.js:308:11)
    at C:\Users\333765\AppData\Local\Cypress\Cache\3.3.2\Cypress\resources\app\packages\server\lib\browsers\index.js:80:33
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:188:7)

  isCypressErr: true,
  type: 'BROWSER_NOT_FOUND_BY_PATH',
  details: 'Version=74.0.3729.108' } +8s
We could not identify a known browser at the path you provided: `C:\Users\333765\AppData\Local\Google\Chrome\Application\chrome.exe`

The output from the command we ran was:

 Version=74.0.3729.108
  cypress:server:cypress about to exit with code 1 +1ms
------

**Comment by JayeshRGujar** [comment]
@flotwig is there any documentation on how to run cypress test on remote machine.

**Comment by flotwig** [comment]
Try this fix, it will probably work for you: https://github.com/cypress-io/cypress/issues/4260#issuecomment-507767328

Here is a guide to running Cypress in CI: https://docs.cypress.io/guides/guides/continuous-integration.html

Here are examples for popular CI providers: https://docs.cypress.io/guides/guides/continuous-integration.html#Examples

**Comment by praveendvd** [comment]
I am having the same issue , any work around ?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
