### ISSUE TITLE
Create + document cy.subject() which synchronously returns current subject

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#468]
- [ ] Add `cy.subject`
- [ ] Document `cy.subject` to explain when you'd want to use this method https://github.com/cypress-io/cypress-documentation/issues/109

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
