### ISSUE TITLE
App View > DOM Before and After app action tracking not displaying after MAC OSX 10.14.5 update

### ISSUE THREAD

**Issue by crhoads1024** [cypress-io/cypress#4680]
## Current behavior: 

Running OSX 10.14.5 (18F132) - Updated last week. Now cypress DOM `before` and `after` tracking is no longer available. Test Runner fires tests properly but no `before` and `after` of the actions listed in the app view and no highlighting or clicking representation in the APP View window either. Upgraded to Cypress 3.3.2 and still exhibiting the same behavior.

### Desired behavior: 

Test runner displays the DOM `before` and `after` highlighting for each user action

### Steps to reproduce: (app code and test code)

- Update to Mac OSX 10.14.5
- Run Cypress test runner
- Observe App view not showing the DOM `Before` and `After` History Tracking

### Versions

Cypress: 3.3.2
MAC OSX Mojave 10.14.5 (18F132)
Chrome: 75

**Comment by jennifer-shehane** [comment]
Can you run the test below and confirm that the snapshot of the before and after on a click is not working for you? Can you provide a screenshot of the behavior / open DevTools and ensure there are no errors there?

```js
  it('.click() - click on a DOM element', () => {
    cy.visit('https://example.cypress.io/commands/actions')
    cy.get('.action-btn').click()
  })
```

Just want to have a test sample to run before upgrading to Mojave.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
