### ISSUE TITLE
Cypress GUI and Cypress CLI have different behaviors on cy.visit

### ISSUE THREAD

**Issue by lassiter** [cypress-io/cypress#4682]
### Current behavior:

[Video on GDrive](https://drive.google.com/open?id=1W1Nf5CJKgOUTo_YwD-JgNMD1XowCWHIX)

#### Test In Question
```js
// / <reference types="Cypress" />

context('Location', () => {
  it('cy.location() - get window.location', () => {
    cy.visit('http://local.candidco.com:3000', { timeout: 30000 });
    // https://on.cypress.io/location
    cy.location().should(location => {
      expect(location.host).to.eq('local.candidco.com:3000');
    });
  });
});

```

### Desired behavior:

To be able to use the GUI to load our app.

### Steps to reproduce: (app code and test code)

Clone [this repo](https://github.com/lassiter/cy-test) and follow instructions in readme.

### Versions

Cypress package version: 3.3.1
Cypress binary version: 3.3.1
MacOS 10.14.5
Chrome and Chromium; CLI - Electron

**Comment by jennifer-shehane** [comment]
@lassiter I'd like to get some more info to narrow down why this loop of reloading is happening. 

I am not able to reproduce this behavior. I ran in Cypress 3.3.1 and 3.4.0 from the repo provided in Chrome 75 & Chrome 71 on a MacOS 10.13.6 after adding the host to my `etc/hosts` file. 

Can you run `DEBUG=cypress:* yarn cypress:open` and post the debug logs in a comment here?

Also, please provide any proxy settings you have set up. https://on.cypress.io/proxy-configuration#Linux-or-macOS You should be able to see any env vars set by running `env | grep -i proxy` in your terminal.

Thanks.

**Comment by stevenvachon** [comment]
@jennifer-shehane can you help at all with this one? It is very much annoying.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
