### ISSUE TITLE
Import static assets

### ISSUE THREAD

**Issue by MatteoGioioso** [cypress-io/cypress#4685]
### Current behavior:

Cannot import static assets

### Desired behavior:

Able to import static assets and use it.

### Steps to reproduce: (app code and test code)
To make my test less brittle I am trying to import sample images from my folder in the cypress project, rather than a remote server. I will then reference the image into my sample data to mock my response.

```js
import fs from "fs-extra";

const avatarImg = fs.readFileSync(
  __dirname + "/sample-assets/avatar.jpg",
  "base64"
);

export const mockedResponse = {
    Items: [
    {
      avatar: avatarImg
      //...other stuff
    },
 ]
}
```
This snippet will work correctly if run on node, but in cypress I get this error

```
Uncaught TypeError: Cannot read property 'toString' of undefined

....

at Object.<anonymous> (http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:10981:42)
    at Object.80../clone.js (http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:11199:4)
    at o (http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:1:265)
    at http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:1:316
    at Object.58.graceful-fs (http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:9722:12)
    at o (http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:1:265)
    at http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:1:316
    at Object.59../copy (http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:9834:3)
    at o (http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:1:265)
    at http://localhost:43087/__cypress/tests?p=cypress/integration/timeline/timeline.js-587:1:316
```

Here I am trying to convert to base64, since normal import is not working.
Is there a way to achieve what I have described?
Thanks.

### Versions

Cypress: 3.4.0
Node: 12.6.0
Ubuntu 18.04.2 LTS

**Comment by jennifer-shehane** [comment]
Your test file is run within the context of the browser, not node. See https://on.cypress.io/using-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress

Also, did you try the [`cy.fixture()`](https://on.cypress.io/fixture) or [`cy.readFile()`](https://on.cypress.io/readfile) commands? This is exactly what those command are for.

**Comment by MatteoGioioso** [comment]
Yes I know about these methods but they are not useful in this case.
`cy.readFile()` and `cy.readFile()` and cannot be called outside a running test

Why did you close the issue?

**Comment by jennifer-shehane** [comment]
You cannot import node modules within your test files because they are run in the context of the browser, not node - as explained here: https://on.cypress.iousing-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress We will not be supporting requiring them within the specfile directly.

You can require a node module in one of the `cypress/support` files and use it from there - which is likely what you want to do. See our example: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__node-modules

**Comment by MatteoGioioso** [comment]
I actually do not need to require a node module, I just need to import an image in my file.

**Comment by jennifer-shehane** [comment]
`fs-extra` is a node module and requires being run in a Node environment. I've linked to several other solutions you can use to reference an image file, due to the way you are currently doing it will not work in Cypress - you will have to use one of the other methods.

**Comment by MatteoGioioso** [comment]
Sorry to bother again, but If you are referring to `cy.fixture() `or `cy.readFile()`, I already told you that they do not work for me.
My goal is to import a simple image and cypress fails to import it, that is why I was trying to use `fs-extra`, but also that fails.
