### ISSUE TITLE
Cypress tasks are not killed on test rerun

### ISSUE THREAD

**Issue by tomhoffer** [cypress-io/cypress#4692]
I have a custom cypress task which executes Node.js code. The purpose of the task is to check if an email has been delivered to a specific mailbox (I am using gmail api for this.) If the email is not received, the task re-tries the check in 30sec intervals and stops when email is received or a 10minute timeout is reached.

### Current behavior:

If I launch the E2E test in the GUI, test starts the task and waits for its completion. However, if I modify the test and save changes made to the spec file, cypress restarts the test and keeps the task running in the background. Once the restarted test reaches the line of code with the `cy.task()`, it creates another instance of the task. Now we have 2 tasks running ! Task from the current run and task from the previous run. This results in tens of cypress tasks running on my computer while developing E2E tests and gmail API blocking me because I'm hitting their API rate limits.

### Desired behavior:

When the test starts, cypress kills all tasks created by the previous run.

### Steps to reproduce:

1. Open cypress GUI (`npx cypress open`)
2. Run the following test. This results in some output being displayed in console every 5 sec.
3. Modify the test source file and save changes. Cypress now restarts the test and has 2 instances of the same task running. The output is printed twice every 5 seconds.

#### Test code
```js
it('should fetch an email', function() {
  cy.task('print-output').then(() => {
    // Do something here
  });
});
```

#### Task which prints output every 5sec. This is an anti-pattern (tasks have to end). I'm putting it here only for easy debugging.

```js
on('task', {
  'print-output': () => {
    setInterval(() => {
      console.log('Executing...');
    }, 5000);

    return null
  },
});
```

### Versions
Cypress: 3.1.5
OS: Max OS Mojave 10.14
Browser: Chrome 75

**Comment by jennifer-shehane** [comment]
I've verified the code above. You can demonstrate this by simply clicking the 'rerun' button in the Test Runner. It will continue to create new instances of the task.

We definitely don’t want to restart the child process on each test. Part of the usefulness of the plugins file is that you can store state that lasts for the whole run and isn’t lost when the browser reloads.

## Workaround

You will probably want to write another task that cancels the process you are executing in your first task and add this to a `beforeEach`.

**Comment by fingolfinor** [comment]
+1 for this bug (ran into it also)
