### ISSUE TITLE
Unable to upload a picture to a hidden input 

### ISSUE THREAD

**Issue by devil-pc** [cypress-io/cypress#4695]
Hello Cypress community,

I am unable to upload a picture using all the code suggested in previous file upload issues.
Here is the HTML of my upload area:

![image](https://user-images.githubusercontent.com/52492577/61029786-7e561900-a3c4-11e9-9d05-8402622c1966.png)

The input has `display:none` so cypress sees only the `.upload-image` div. I have installed the `cypress-file-upload` and added the import in `commands.js` then I tried code like this:

```js
const fileName = '1.jpg'

cy.fixture(fileName).then((fileContent) => {
  cy.get('.upload-image')
    .wait(3000)
    .upload({
      fileContent, fileName, mimeType: 'image/jpeg',
    },
    {
      subjectType: 'drag-n-drop',
    },
    )
  cy.wait(3000)
})
```

No errors but NO UPLOAD also..

Or code like this:

```js
const dropEvent = {
  dataTransfer: {
    files: [
    ],
  },
};

cy.fixture('1.jpg').then((picture) => {
  return Cypress.Blob.base64StringToBlob(picture, 'image/jpeg').then((blob) => {
    dropEvent.dataTransfer.files.push(blob);
  });
});

cy.get('.upload-image').trigger('drop', dropEvent);
```

Same problem - beautiful execution, no errors but NO UPLOAD also !!!!
I am developing on a Win 10 machine, with latest version of Cypress - 3.4.0 and Chrome 75.0.3770.100 (Official Build) (64-bit)

Any help will be greatly appreciate.

Thank you.

Clau

**Comment by devil-pc** [comment]
After long talks I managed to convince the team to adopt Cypress into our E2E testing philosophy BUT....
today I just had a long talk with the product owner and the dev team and they will not change the html of the hidden input to upload files. If I do not get an answer soon from Cypress about this issue, I will be forced to find another framework for E2E testing....

Cypress still has a lot of issues that can  be a NO GO for many big companies - like total lack of support for any other browser (like FireFox, Safari, IE etc), no true support for Gerkin feature files - Cucumber style of automating etc etc.... 

Thank you

**Comment by must-git-good** [comment]
While I can't help you with the rantier parts of your posts...

I can say that I've encountered similar when trying to upload to a feature that wasn't visible (using the cypress-file-upload). I found this solution worked for me, maybe it will for you, as well:

`
...
cy.fixture('test.jpg', 'base64')
.then( (fileContent) => {
                  cy.log("Next test changes the view. The hidden upload button is now showing intentionally.");
                  cy.get(theElementWe'reTesting)
                    .invoke('removeAttr', 'style') //makes element easier to interact with/accessible. Headless test fails wihout this.
                    .upload(
                    { fileContent, fileName: 'test.jpg', mimeType: 'image/jpeg'},
                    { subjectType: 'input', force: true },
                    );
                  cy.get ... (and so on)`

**Comment by kaabtahir** [comment]
Hi @devil-pc 
I have successfully uploaded a PDF file in my project. Here are the following things you need to do
1- In the fixtures folder place file e.g(pdf, csv, jpge) etc.
2- Change your input id to **_"create-notice-upload-image"_** you are placing the wrong id that is of div not of the input tag. 
 
Here is my code snippet might help!
> it('successfully uploads a file', () => {
            cy.fixture('test.pdf').then(fileContent => {
                cy.get('[id="upload"]').upload(
                    { fileContent, fileName: 'test.pdf', mimeType: 'application/pdf' },
                    { subjectType: 'input' },
                );
                cy.wait(10000)
                cy.get('.modal-footer > .btn-primary').click();
                cy.wait(10000)
            });
        });

**Comment by jennifer-shehane** [comment]
Since file upload is not built-in behavior into Cypress yet, we have zero code from Cypress that could be affecting this behavior, I would refer to the [`cypress-file-upload` plugin](https://github.com/abramenal/cypress-file-upload) for this issue and watch the [file upload issue](https://github.com/cypress-io/cypress/issues/170) for official Cypress support.

**Comment by devil-pc** [comment]
Hello @must-git-good - using your suggestion we did manage to upload a picture - thank you for the input !!!. 
BUT..... at code review it will fail because we are manipulating the HTML of a web page in a way that an end user will never do.... any E2E testing framework should reproduce the user action / interaction on a web app without manipulating the html....

And hello @kaabtahir - we tried your suggestion from the start but the issue was that because of the "style=display: none;" on the input, cypress was unable to see the object....so at runtime the error was obvious: CypressError: Timed out retrying: Expected to find element: 'create-notice-upload-image', but never found it......

And hello @jennifer-shehane - We do appreciate all the work that Cypress does to build this E2E framework... 

Thank you all for the reply. Have a nice day...

Claudiu

**Comment by jenchek** [comment]
Hello, thanks @must-git-good. 
I use this code:
```
cy.fixture('1.mp4', 'base64').then( fileContent => {
   cy.get('[type="file"]').eq(1).upload(
      { fileContent, fileName: '1.mp4', mimeType: 'video/mp4'},
      { subjectType: 'input', force: true })
   cy.get('.el-upload.el-upload--text').eq(1).click()
})
```
But if i upload video.mp4 instead photo.jpeg Cypress give me error:
![image](https://user-images.githubusercontent.com/42541466/61392733-29386c80-a8c8-11e9-9c65-94db4a9c5c40.png)

How i can upload video?

**Comment by jenchek** [comment]
hello

**Comment by jenchek** [comment]
hello can i get answer for question to the up?

**Comment by alexandruchitenco** [comment]
if you use the repo of cypress-file-upload is possible to do that, i jus had the same issue but i fixe it with that
