### ISSUE TITLE
Document Cypress.log interface

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#470]
The `Cypress.log` interface is how a user can modify the "reporter" left side and display commands / pending / take snapshots / indicate failure, etc.

This is currently undocumented and needs to be documented.

**Comment by jennifer-shehane** [comment]
Issue moved to [cypress-io/cypress-documentation #110](https://github.com/cypress-io/cypress-documentation/issues/110) via [**ZenHub**](https://www.zenhub.com/)
