### ISSUE TITLE
Before and beforeEach in supportFile - unexpected behavior during 'run all specs'

### ISSUE THREAD

**Issue by MUTOgen** [cypress-io/cypress#4703]
### Current behavior:

`before` and `beforeEach` executed from support file seems unlogical.
As docs described, `beforeEach` runs before each test in each spec file.
In this way, I expect to see `before` hook before starting each spec file. But it doesn't, it runs only once.

![Снимок экрана 2019-07-12 в 11 22 22](https://user-images.githubusercontent.com/300644/61117801-a2365f00-a497-11e9-843f-7a732d8e6003.png)
 

### Desired behavior:

Seems like more clear to run `before` hook before each spec file, like each `before` hook from spec file does.

### Steps to reproduce: (app code and test code)

I just pasted this piece of code into `support/index.js`

```js
before(() => {
    cy.log('Run before');
});

beforeEach(() => {
    cy.log('Run before each');
});
```

### Versions

Cypress: 3.3.1
MacOs: 10.14.5
Google Chrome: 75.0.3770.100

**Comment by Songyu-Wang** [comment]
you can also put before() and beforeeach() inside spec files...

**Comment by MUTOgen** [comment]
> you can also put before() and beforeeach() inside spec files...

Sure, but I'd like to extract some logic to `support` file. I don't really want to copy-paste `before` hook to each spec file.

**Comment by Songyu-Wang** [comment]
I'm so confused… If you have generic before and before each, you put it in support file, cypress will apply them to the spec you wanna run… if you have unique logic for each spec file, you put before and before each into particular spec files. I don't see anything wrong with that. 

And based on the screenshot you have,  you fixture loading got ran for each spec. What is the issue?

**Comment by MUTOgen** [comment]
> I'm so confused… If you have generic before and before each, you put it in support file, cypress will apply them to the spec you wanna run… if you have unique logic for each spec file, you put before and before each into particular spec files. I don't see anything wrong with that.
> 
> And based on the screenshot you have, you fixture loading got ran for each spec. What is the issue?

That is what I'm talking about. I want to put some generic code into `support` file as `before` hook.
In my case it's just `cy.log('Run before');`.
Then I want to run all spec files at once (like CI does, for example). As you can see, I got a log message only once. When `For non-registered users` runs, there is no log message. I expected the same `before` hook there.
Fixtures loading is ok, b/c I copy-pasted it in each spec file.

**Comment by Songyu-Wang** [comment]
Oh, I see the issue now… sorry I didn't realize there are two before defined by you. Sorry… please ignore whatever I said… I think you are right

**Comment by jennifer-shehane** [comment]
This falls under this body of work: https://github.com/cypress-io/cypress/issues/1586

**Comment by MUTOgen** [comment]
> This falls under this body of work: #1586

Are there any estimates about finishing this?
