### ISSUE TITLE
Cypress.config(user-agent not working in spec file.

### ISSUE THREAD

**Issue by movingelectrons** [cypress-io/cypress#4706]
I have this 

```js
Cypress.config('user-agent', "Mozilla/5.0 (Linux; Android 6.0.1; SM-G532G Build/MMB29T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.83 Mobile Safari/537.36")
```

at top of my spec file, but its not applied.  If I put it in `cyprress.config`, then it gets used right, but I dont want to do that, i would have to manually change it every time I wanted to run tests against mobile vrs desktop.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
