### ISSUE TITLE
Bug:  Assertions run before steps required to make assertion pass run.

### ISSUE THREAD

**Issue by NoMan2000** [cypress-io/cypress#4708]
### Current behavior:

Here is the code:

```js
// @flow
import {
    loginAdmin,
    loginRscManager,
    loginMarketingManager,
    goToMainPage
  } from "./../utils/loginUtils";
  import { createMakeRequest } from "./../utils/routeUtils";

  describe('RAL-45', () => {
      describe('As an RSC Manager User I want to filter the maintenance log so I can view maintenance from a specific Date Range', () => {
          it('Should allow a RSC manager to sort the maintenance log by date', () => {
            loginRscManager();
            goToMainPage();
            createMakeRequest();
            cy.get('[data-tab-id="maintenanceLog"]').click();
            cy.wait('@makeRequest');
            cy.wait('@makeRequest');
            cy.wait("@makeRequest");
            const initialDate = cy.get('[data-test="createdAt-0"]').invoke('text');
            const initialDateTime = new Date(initialDate).getTime();
            cy.get('[data-test="created_at_log"]').click({force: true});
            cy.wait("@makeRequest");
            const secondDate = cy.get('[data-test="createdAt-0"]').invoke('text');
            const secondDateTime = new Date(secondDate).getTime();
            expect(secondDateTime).to.be.greaterThan(initialDateTime);
          });
          it("Should allow a Marketing manager to set start and end dates", () => {
            loginMarketingManager();
            goToMainPage();
            createMakeRequest();
            cy.get('[data-tab-id="maintenanceLog"]').click();
            cy.wait('@makeRequest');
            cy.wait('@makeRequest');
            cy.wait("@makeRequest");
            cy.get('[data-test="filter-icon"]').click();
            cy.get('[name="startDate"]').type('2019-05-01');
            cy.get('[name="endDate"]').type('2019-07-01');
            cy.get('[data-test="send-filter"]').click();
            cy.get('[data-test="toggle-icon"]').click();
            const testInitialDate = new Date('2019/05/01').getTime();
            const secondTestDate = new Date('2019/07/01').getTime();
            const initialDate = cy.get('[data-test="createdAt-0"]').invoke('text');
            const initialDateTime = new Date(initialDate).getTime();
            expect(initialDateTime < testInitialDate && initialDateTime > secondTestDate).to.be.true;
          });
      });
  });
```
Here is what happens.

<img width="746" alt="Screen Shot 2019-07-14 at 7 55 08 PM" src="https://user-images.githubusercontent.com/812215/61193667-c483d480-a671-11e9-8c08-08e0d752b2a6.png">

Now, if I remove both assertions, here is what happens.

<img width="738" alt="Screen Shot 2019-07-14 at 7 59 52 PM" src="https://user-images.githubusercontent.com/812215/61193693-f006bf00-a671-11e9-978b-ecf2aedc8855.png">

### Desired behavior:

I expect an assertion not to run until the line of code the assertion is on.

### Versions

Cypress 3.4, Mac OSX 10.14.5, Chrome 75.

**Comment by jennifer-shehane** [comment]
This is due to the way the Cypress API works. Cypress commands are asynchronous. I'd suggest you thoroughly read through [this doc](https://on.cypress.io//introduction-to-cypress#Commands-Are-Asynchronous) and the document on [variables and aliases](https://on.cypress.io/variables-and-aliases#Return-Values).

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

You can also ask questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).

**Comment by NoMan2000** [comment]
If I'm correct debugging this, (the first link you provided doesn't work, it's a 404 page) using `expect` runs at the moment of execution, and it doesn't get enqueued into the Promise chain that the `cy` chain runs.  If that's correct, then that should be noted somewhere in the docs, since it's a fairly big gotcha in the code.

Correct url: [Commands are async](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Promises)

The solution then would be to use some form of 

```
cy.get('#foo').then(() => {
   expect(dependency).to.equal(value);
});
```

Even if the cy.get is basically a no-op, it will put it onto the promise chain and keep it from running until the other promises have first resolved.  Unfortunately, the more semantic `Promise.resolve()` doesn't seem to work.

While not a "bug", the docs do need to be updated since that particular gotcha is not there from what I can gather.

**Comment by johnflux** [comment]
Can we please get an update in the docs on how to do this properly?
Do we really need to do cy.get on some arbitrary item?
