### ISSUE TITLE
Fix slowness when sending complex objects over the websocket

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4713]
Since #4407, socket messages have been taking longer to encode. This is mostly not noticeable except in certain cases like code coverage: cypress-io/code-coverage#26

There is probably room for optimization in the `socket.io-circular-parser` and related packages that could improve this condition.

**Comment by ariellephan** [comment]
the package is pointing to a patch: "socket.io-circular-parser": "cypress-io/socket.io-circular-parser#unpatched-has-binary-2" that is using deprecated code

GMT express deprecated req.host: Use req.hostname instead at ../socket/node_modules/socket.io-circular-parser/binary.js:132:25

**Comment by flotwig** [comment]
Going to close this as it is not actionable at this time.
