### ISSUE TITLE
cy.contains(content, options) syntax works, but missing in typescript declaration and not documented

### ISSUE THREAD

**Issue by jodelasur** [cypress-io/cypress#4727]
### Current behavior:

I tried `cy.contains('content', {timeout: 6000})` and it works, but my IDE is complaining that "Argument types do not match parameters". I checked `types/index.d.ts` and didn't find a matching declaration. 

![image](https://user-images.githubusercontent.com/34933233/61280442-7219f380-a7ea-11e9-9feb-ad77a9bb759d.png)

I also checked the [documentation](https://docs.cypress.io/api/commands/contains.html#Syntax) and didn't find it referenced.

![image](https://user-images.githubusercontent.com/34933233/61280664-d8067b00-a7ea-11e9-9ab7-5e6c9891a4d0.png)

### Desired behavior:

Just want to make this function signature official, as I happen to use it many times (and others might as well).

### Versions
Cypress 3.3.2, Windows 10, Chrome 75

**Comment by bahmutov** [comment]
The typescript definition for `cy.contains` are included, see https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L577 

I suggest restarting TS server in your IDE, sometimes it gets frozen?

**Comment by jodelasur** [comment]
Yes, I reviewed the definitions file, but the exact definition I'm looking for (with two arguments: a content string, and an optional options object) isn't there.

I think the params list of lines 577 and 586 should be extended as 
`(content: string | number | RegExp, options?: Partial<Loggable & Timeoutable>)`.

Then the documentation should add `cy.contains(content, options)` as another syntax.

I could make a pull request, but can only do so later in the week.

**Comment by jennifer-shehane** [comment]
Yes, this is a valid use of `.contains()` as noted in the code here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/querying.coffee#L288 - the TypeScript defs should be updated. 

I updated the docs here: https://github.com/cypress-io/cypress-documentation/commit/7c1ce33becb74438fb8b005385308054c6de2353
