### ISSUE TITLE
Fix crash due to state.json being empty

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#473]
Our fork of `conf` has a bug in regards to how it handles (or doesn't handle) JSON parsing errors, so if the [state.json file ends up empty somehow](https://github.com/cypress-io/cypress/issues/474), it will throw and crash the entire process. Need to add proper error handling.

**Comment by chrisbreiding** [comment]
Fixed: https://github.com/cypress-io/conf/commit/8ed25903333809cea19bdcb39ee5a5ab738537d5

**Comment by brian-mann** [comment]
Fixed in [`0.19.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0192-04162017).
