### ISSUE TITLE
Trigger event overridden by mouse placement

### ISSUE THREAD

**Issue by zach446** [cypress-io/cypress#4732]
### Current behavior:
I have a 3JS element that is clickable all within its canvas.  Along the 3D model the user can place spheres.  When I click inside my viewerPage to place a sphere the location of the sphere lands on the center of the document rather than the desired location.

Here you can see that the placement of the mouse influences where the trigger event occurs.
![seq1](https://user-images.githubusercontent.com/22154347/61321467-93beaf00-a7d9-11e9-9560-a79fef2e76af.gif)

Without the influence of the mouse the trigger event seems to go to the center of the page
![seq2](https://user-images.githubusercontent.com/22154347/61321498-a507bb80-a7d9-11e9-9f4e-e3529b182a47.gif)

### Desired behavior:

I would like the cypress trigger to fire the mouse events at the desired coordinates. 

The coordinates provided below should place the sphere at the top of the model.  Similar placement as to what you see in the first GIF.

### Steps to reproduce: (app code and test code)
**I can not divulge any code for legal reasons, so I will do my best to describe the elements structure through pictures and gifs.**

The page itself is designed like a page within a page.  The parent element is called the ViewerPage with a series of children within it.  One of which we call the canvas, which holds the 3D model.  Much like this...

![Screen Shot 2019-07-16 at 11 47 08 AM](https://user-images.githubusercontent.com/22154347/61309107-96140f80-a7bf-11e9-8adc-79bada2481e6.png)

We are using styled components, so here is the styling for the canvas component
```js
const ViewerCanvas = styled.div`
  display: flex;
  flex: 1 1 auto;
  position: relative;

  border-radius: 4px;
  overflow: hidden;
`;
```

And then inside of the canvas the actual scene is...
```js
const ViewerSceneContainer = styled.div`
  position: absolute;
  width: 100%;
  background-image: linear-gradient(
    to bottom,
    ${props => props.theme.colors.grey80},
    ${props => props.theme.colors.grey40}
  );
`;
```
Here is a snippet of my cypress code 

```js
Viewer.viewerPage.trigger('mousedown', {
      pageX: 600,
      pageY: 230,
      clientX: 600,
      clientY: 230,
    });
    Viewer.viewerPage.trigger('mouseup', {
      pageX: 600,
      pageY: 230,
      clientX: 600,
      clientY: 230,
    });
    Viewer.nextStageButton.click();
```

### Versions

Cypress: 3.3.1
OS: MacOS Mojave
Browser: Chrome
Node: v8.10.0

**Comment by Bkucera** [comment]
@zach446 could share snippets of your spec code?

**Comment by zach446** [comment]
Please let me know if you need anything else.  The project itself is monolithic, I will try to shed some light on what the source code looks like.

Within our ViewerPage we create a scene. 

A snippet of our source code on how we create the scene...
```
this.camera = new THREE.OrthographicCamera(
      window.innerWidth / -2,
      window.innerWidth / 2,
      window.innerHeight / 2,
      window.innerHeight / -2,
    );
    // orient camera so it's parallel to airway long axis
    this.camera.position.y = -200;
    this.camera.up.set(0, 0, 1);

    this.scene = new THREE.Scene();
    this.raycaster = new THREE.Raycaster();
    this.plane = new THREE.Plane();
    this.objectPlane = new THREE.Plane();
    this.originPlane = new THREE.Plane(); // used for adding new spheres to scene
    this.light = new THREE.DirectionalLight(0xffffff, 0.8);
    this.light.position.copy(this.camera.position).normalize();
    this.scene.add(this.light);
    this.scene.add(new THREE.AmbientLight(0x505050));

    this.innerWidth = window.innerWidth;
    this.innerHeight = window.innerHeight;

    this.renderer = new THREE.WebGLRenderer({ alpha: true });
    this.renderer.domElement.id = 'canvas';

    this.composer = new THREE.EffectComposer(this.renderer);

    const renderPass = new THREE.RenderPass(this.scene, this.camera);
    this.composer.addPass(renderPass);

    const initialResolution = new THREE.Vector2(window.innerWidth, window.innerHeight);
    this.outlinePass = new THREE.OutlinePass(initialResolution, this.scene, this.camera);
    this.outlinePass.styleOutline(WARNING_OUTLINE_STYLE);
    this.composer.addPass(this.outlinePass);

    const copyPass = new THREE.ShaderPass(THREE.CopyShader);
    copyPass.renderToScreen = true;
    this.composer.addPass(copyPass);
```

The test in question from `cypress/integration/viewer_page_spec`
```
it.('Viewer page', () => {
    Login.email.type('testsurgeon2@customorthopaedics.com');
    Login.password.type('password');
    Login.loginButton.click().wait(5000);

    Patients.tableNameColumn.should('exist');
    Patients.tableNameColumn.contains('Patient 1, Test').click();

    Patient.newStentButton.click();
    Patient.scanExpiredModalProceedButton.click();
    Patient.stentNameModalContinueButton.click().wait(8000);
    Viewer.viewerPage.trigger('mousedown', {
      pageX: 600,
      pageY: 230,
      clientX: 600,
      clientY: 230,
    });
    Viewer.viewerPage.trigger('mouseup', {
      pageX: 600,
      pageY: 230,
      clientX: 600,
      clientY: 230,
    });
    Viewer.nextStageButton.click();
    Viewer.viewerPage.click(525, 485, { multiple: true, force: TextTrackCue });
    Viewer.nextStageButton.click();
  });
```
