### ISSUE TITLE
Cypress replacing code in transpiled application code.

### ISSUE THREAD

**Issue by dalinarkholin** [cypress-io/cypress#4734]
### Current behavior:

This happens during `cypress open` and `cypress run`

When I run my project locally outside of cypress and look at the transpiled output I see `stop.location`, but when I look at the transpiled code with the runner it shows as `sself.location` and I get a error:

```
Uncaught ReferenceError: sself is not defined

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```
<img width="405" alt="Screen Shot 2019-07-16 at 12 05 02 PM" src="https://user-images.githubusercontent.com/2343017/61310499-6c101c80-a7c2-11e9-81c6-8d4d301b9ded.png">

![Screen Shot 2019-07-16 at 12 06 21 PM](https://user-images.githubusercontent.com/2343017/61310549-834f0a00-a7c2-11e9-866f-01b0e122ae35.png)

cypress.json
```
{
  "baseUrl": "http://localhost:8084",
  "video": false
}

```

### Desired behavior:

Im not sure why application code is getting modified at all. I don't believe it should?

### Steps to reproduce: (app code and test code)

This is hard to reproduce, but perhaps there is some area where cypress does replacements in the application being tested? Might be a starting place to look. Also not sure if it is specific to the word `stop` since that is what is getting mangled.

### Versions

Cypress: ^3.4.0
macOS Mojave 10.14
Chrome 75

**Comment by bahmutov** [comment]
@dalinarkholin can you try changing `modifyObstructiveCode` setting in `cypress.json` - we do a few changes to the website code to remove most commonly used iframe busting techniques, https://docs.cypress.io/guides/references/configuration.html#Browser

**Comment by dalinarkholin** [comment]
@bahmutov thanks for the quick reply. Yes that resolved the issue!
