### ISSUE TITLE
i cannot run using chrome 75

### ISSUE THREAD

**Issue by josealania** [cypress-io/cypress#4735]
### Current behavior:
When trying to run a test on chrome 75, a page like the one in the following screenshot loads:

![image](https://user-images.githubusercontent.com/52972855/61317589-e5127280-a7c8-11e9-87a7-f148483749d7.png)

### Desired behavior:

run same as it does using electron 61 browser please see the following screenshot:

![image](https://user-images.githubusercontent.com/52972855/61318090-e1332000-a7c9-11e9-840d-ad7adeacee24.png)

**Comment by flotwig** [comment]
Are you using Cypress 3.4.0? Can you share the contents of `chrome://policy` inside of Chrome?

**Comment by josealania** [comment]
yes cypress 3.4.0
and this is my chrome policy screenshot:

![image](https://user-images.githubusercontent.com/52972855/61322194-bf8a6680-a7d2-11e9-9c7c-a6f3ba4d14e7.png)

**Comment by flotwig** [comment]
Thanks for providing more details.

The Websense Endpoint Chrome extension is auto-installed by your company and is known to cause problems running Cypress. Another user was able to uninstall Websense and it fixed their problems: https://github.com/cypress-io/cypress/issues/4578#issuecomment-506485995 Try to uninstall it and re-launch Cypress.

Cypress should've detected this and warned you, but it looks like that didn't happen and I'd like to debug why. Can you share [debugging logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) from when you launch Cypress?

**Comment by josealania** [comment]
This is part of debug log but shows the moment chrome is called:

![image](https://user-images.githubusercontent.com/52972855/61325305-07f95280-a7da-11e9-9f87-5ad02c3dfa88.png)

**Comment by flotwig** [comment]
Can you share the entire log file? The part I need is actually near the beginning.

**Comment by josealania** [comment]
what is log file location see the following screenshot, folder is empty

![image](https://user-images.githubusercontent.com/52972855/61326570-b0a8b180-a7dc-11e9-82ce-f89be426b69c.png)

**Comment by flotwig** [comment]
Run Cypress like this: `DEBUG=cypress:* cypress open > log-file.txt 2>&1` This will redirect all output to a file named `log-file.txt` in your current directory.

**Comment by josealania** [comment]
Here it is...

[log-file.txt](https://github.com/cypress-io/cypress/files/3399291/log-file.txt)

**Comment by josealania** [comment]
About Forcepoint, my company's tech support team are asking for urls cypress needs to work well, so they can add to the whitelist. Disabling Forcepoint is not an option.

**Comment by jennifer-shehane** [comment]
@josealania Typically if `*.cypress.io` is whitelisted on your infrastructure's side we're good to go.

**Comment by josealania** [comment]
I have added *.cypress.io to whitelist and still not connecting cypress to chrome.

**Comment by josealania** [comment]
did you find why cypress is not showing an alert about the forcepoint? maybe that is the real issue and not forcepoint...

**Comment by flotwig** [comment]
@josealania It is most likely because your company configures the policies via GPO, not via the registry. Currently Cypress only checks the registry.

Even with the warning, Cypress just won't work with Forcepoint installed. Here's what the warning would've linked to, and some workarounds that may work for you: https://docs.cypress.io/guides/references/error-messages.html#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues
