### ISSUE TITLE
state.json ends up empty somehow

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#474]
Somehow, the state.json file is ending up empty, (subsequently causing #473). Likely, a write is being interrupted by a read or another write or the process terminates in the middle of a write, causing the file to be emptied. Need to look into best practices for file reading/writing, including whether using createReadStream/createWriteStream is sufficient or if we need to implement a locking mechanism or a retry mechanism.

**Comment by brian-mann** [comment]
Fixed in [`0.19.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0192-04162017).
