### ISSUE TITLE
Add file menu option to desktop app that opens app data directory

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#475]
![screen shot of desktop app with file menu open](https://cloud.githubusercontent.com/assets/1157043/24264873/0fb4d2ca-0fd8-11e7-81fb-a38b5b462bdc.png)

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
