### ISSUE TITLE
How to supports multiple cy.route methods with same request url at once

### ISSUE THREAD

**Issue by hakuna0829** [cypress-io/cypress#4753]
Hi, 

I am going to get multiple(3 things) `cy.route` for same url requests.
Of course, each one returns different json array.
But, It's got error except only first request(`@me`).

### Current behavior:
Here is my code.
```js
cy.server();
cy.route('POST', 'http://localhost:4000/graphql', 'fixture:me.json').as('me');
cy.visit('mySiteUrl');

cy.wait('@me');
cy.route('POST', 'http://localhost:4000/graphql', 'fixture:getAppList.json').as('appData');
cy.wait('@appData');
cy.route('POST', 'http://localhost:4000/graphql', 'fixture:getModelList.json').as('modelData');
cy.wait('@modelData');
```

### Desired behavior:

I want to get all of requests when browser visit my page.
So I can start testing with mockup data.

### Versions
cypress version : v1.16.0
chrome 75
Windows 10

**Comment by hakuna0829** [comment]
@jennifer-shehane 
I didn't see any solution for this error. Can you let me know?
Thanks.

**Comment by jennifer-shehane** [comment]
Sorry, I linked to the wrong issue. Duplicate of https://github.com/cypress-io/cypress/issues/4460

**Comment by hakuna0829** [comment]
Thanks, @jennifer-shehane 
Here is another problem.

I am going to use stub before page load, so I can use sample mockup data without calling api.
I checked this link https://github.com/cypress-io/cypress-documentation/issues/122?source=post_page---------------------------

But, it doesn't work correctly. 
Of course, there is no error, too.

Here is my status.

https://files.slack.com/files-pri/T0J3YAY3E-FLN2XF17X/image.png
https://files.slack.com/files-pri/T0J3YAY3E-FLAKZQXPC/image.png

I hope you can understand what I mean and let me know its reason.
Also, solution, too.

Thanks.
