### ISSUE TITLE
Add support for 'screenshotOnRunFailure' as CLI argument

### ISSUE THREAD

**Issue by csdivine** [cypress-io/cypress#4754]
### Current behavior:

Cypress supports `screenshotOnRunFailure` as a configuration option, but does not allow it as an argument to the command-line '--config' option.

### Desired behavior:

It would be nice if Cypress supported passing in `--config screenshotOnRunFailure=false` as part of a `cypress run` command.

**Comment by jennifer-shehane** [comment]
`screenshotOnRunFailure` is not part of the global configuration API, but an option that can be set within the [Cypress.Screenshot API](https://on.cypress.io/screenshot-api#Arguments). 

Can you explain a bit about why you need this as part of the `--config` flag? What about using the Screenshot API doesn't work for what you are currently trying to achieve - this way we can understand the problem more directly.

**Comment by csdivine** [comment]
@jennifer-shehane Turns out setting `Cypress.Screenshot.defaults({screenshotOnRunFailure: false})` in `/cypress/support/index.js` works fine for me. Feel free to close this issue.
