### ISSUE TITLE
Handle global spec file errors which prevent tests from being parsed or run

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#476]
## Problem
Currently when there is a synchronous global error in a `spec` file - we will display the misleading message:

![screen shot 2017-03-26 at 10 10 30 pm](https://cloud.githubusercontent.com/assets/1268976/24338156/2c00c952-1271-11e7-8aba-d16fb4dfe276.png)

This can happen due to incorrectly calling methods, or anything else that busts JS during runtime.

The user then has to check their console for the specific error and then go debug it:

![screen shot 2017-03-26 at 10 10 40 pm](https://cloud.githubusercontent.com/assets/1268976/24338180/5324583c-1271-11e7-860b-acc1479d0724.png)

## Solution

It's possible for us to detect global errors in the spec code and provide a really great error message indicating this error happened in a spec file and not the remote application.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
