### ISSUE TITLE
Comment on closed issues when building the test runner (pre-release install)

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4760]
We comment on each built test runner in `develop` with instructions how to install the pre-release. For example see https://github.com/cypress-io/cypress/commit/7857dac9071d578ea6f4540ad1fbe3f2798da7a2

<img width="797" alt="Screen Shot 2019-07-18 at 2 54 42 PM" src="https://user-images.githubusercontent.com/2212006/61484343-c0570000-a96c-11e9-9330-b033b903318c.png">

It would be also very good to find all issue numbers referenced from the commit message (like `- closes #1234`) and paste the same comment with installation instructions there.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
