### ISSUE TITLE
Cypress extension not available in Chrome browser

### ISSUE THREAD

**Issue by iackc** [cypress-io/cypress#4762]
### Current behavior:
IT team policies blacklist everything unless the entries are Whitelisted. SO, we had IT whitelist the extension ID for Cypress: caljajdfkjjjdehjdoimjkkakekklcck. 
 - Verified the chrome://policy has the extension id Whitelisted.
 - Verified chrome://extension is not displaying Cypress extension id 
 - Deleting everything under "cy" folder from "View App Data" and restarted Cypress did not help

When running a spec/ test in Chrome browser, seeing the following error message in Browser:

> Whoops, we can't run your tests.
> 
> This browser was not launched through Cypress. Tests cannot run.
> 

### Desired behavior:
The Cypress extension should be loaded and The spec / test should be run in Chrome browser 

### Steps to reproduce: (app code and test code)
- Install latest build of Cypress on Windows
- Try running any spec (using default action.spec.js) in Chrome 

### Versions
Cypress Version 3.4.0 
Chrome Browser: Version 72.0.3626.121 
Symantec Management Agent & CylanceProtect are installed 

### Logs
````

> 2019-07-17T15:37:48.607Z cypress:server:events sending ipc data { type: 'get:spe
> cs', data: { id: 0.6542233886544999, data: { integration: [Array] } } }
> 2019-07-17T15:37:57.202Z cypress:server:events got request for event: close:brow
> ser, undefined
> 2019-07-17T15:37:57.215Z cypress:server:events sending ipc data { type: 'close:b
> rowser', data: { id: 0.44799581114381914, data: undefined } }
> 2019-07-17T15:37:57.224Z cypress:server:events got request for event: launch:bro
> wser, { browser: { displayName: 'Chrome', family: 'chrome', isChosen: true, majo
> rVersion: '72', name: 'chrome', path: 'C:\\Program Files (x86)\\Google\\Chrome\\
> Application\\chrome.exe', version: '72.0.3626.121' }, spec: { absolute: 'C:/User
> s/abcdef/Documents/cypress/resources/app/packages/example/cypress/integration/exa
> mples/actions.spec.js', name: 'examples\\actions.spec.js', relative: 'cypress\\i
> ntegration\\examples\\actions.spec.js' } }
> 2019-07-17T15:37:57.242Z cypress:server:openproject resetting project state, pre
> paring to launch browser
> 2019-07-17T15:37:57.248Z cypress:server:project resetting project instance C:\Us
> ers\abcdef\Documents\cypress\resources\app\packages\example
> 2019-07-17T15:37:57.252Z cypress:server:buffers resetting buffers
> 2019-07-17T15:37:57.254Z cypress:server:server Setting remoteAuth undefined
> 2019-07-17T15:37:57.256Z cypress:server:server Setting remoteOrigin http://local
> host:49478
> 2019-07-17T15:37:57.258Z cypress:server:server Setting remoteStrategy file
> 2019-07-17T15:37:57.259Z cypress:server:server Setting remoteHostAndPort null
> 2019-07-17T15:37:57.260Z cypress:server:server Setting remoteDocDomain localhost
> 
> 2019-07-17T15:37:57.262Z cypress:server:server Setting remoteFileServer http://l
> ocalhost:49479
> 2019-07-17T15:37:57.264Z cypress:server:server Getting remote state: { auth: und
> efined, props: null, origin: 'http://localhost:49478', strategy: 'file', visitin
> g: undefined, domainName: 'localhost', fileServer: 'http://localhost:49479' }
> 2019-07-17T15:37:57.280Z cypress:server:openproject launching browser: { display
> Name: 'Chrome', family: 'chrome', isChosen: true, majorVersion: '72', name: 'chr
> ome', path: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
> version: '72.0.3626.121', isHeaded: true, isHeadless: false }, spec: cypress\int
> egration\examples\actions.spec.js
> 2019-07-17T15:37:57.301Z cypress:server:browsers opening browser { displayName:
> 'Chrome', family: 'chrome', isChosen: true, majorVersion: '72', name: 'chrome',
> path: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', versio
> n: '72.0.3626.121', isHeaded: true, isHeadless: false }
> 2019-07-17T15:37:57.311Z cypress:server:plugins plugin event registered? { event
> : 'before:browser:launch', isRegistered: false }
> 2019-07-17T15:37:57.338Z cypress:server:appdata path: C:\Users\abcdef\AppData\Roa
> ming\Cypress\cy\production\extensions
> 2019-07-17T15:37:57.417Z cypress:server:browsers launch in chrome: http://localh
> ost:49478/__/#/tests/integration\examples\actions.spec.js, --test-type,--ignore-
> certificate-errors,--start-maximized,--silent-debugger-extension-api,--no-defaul
> t-browser-check,--no-first-run,--noerrdialogs,--enable-fixed-layout,--disable-po
> pup-blocking,--disable-password-generation,--disable-save-password-bubble,--disa
> ble-single-click-autofill,--disable-prompt-on-repos,--disable-background-timer-t
> hrottling,--disable-renderer-backgrounding,--disable-renderer-throttling,--disab
> le-restore-session-state,--disable-translate,--disable-new-profile-management,--
> disable-new-avatar-menu,--allow-insecure-localhost,--reduce-security-for-testing
> ,--enable-automation,--disable-infobars,--disable-device-discovery-notifications
> ,--autoplay-policy=no-user-gesture-required,--disable-site-isolation-trials,--me
> trics-recording-only,--disable-prompt-on-repost,--disable-hang-monitor,--disable
> -sync,--disable-web-resources,--safebrowsing-disable-auto-update,--safebrowsing-
> disable-download-protection,--disable-client-side-phishing-detection,--disable-c
> omponent-update,--disable-default-apps,--use-fake-ui-for-media-stream,--use-fake
> -device-for-media-stream,--proxy-server=http://localhost:49478,--proxy-bypass-li
> st=<-loopback>,--load-extension=C:\Users\abcdef\AppData\Roaming\Cypress\cy\produc
> tion\browsers\chrome\interactive\CypressExtension,C:\Users\abcdef\Documents\cypre
> ss\resources\app\packages\extension\theme,--user-data-dir=C:\Users\abcdef\AppData
> \Roaming\Cypress\cy\production\browsers\chrome\interactive,--disk-cache-dir=C:\U
> sers\abcdef\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\Cyp
> ressCache
> 2019-07-17T15:37:57.472Z cypress:launcher launching browser { displayName: 'Chro
> me', family: 'chrome', isChosen: true, majorVersion: '72', name: 'chrome', path:
>  'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', version: '7
> 2.0.3626.121', isHeaded: true, isHeadless: false } to open http://localhost:4947
> 8/__/#/tests/integration\examples\actions.spec.js
> 2019-07-17T15:37:57.483Z cypress:launcher spawning browser { displayName: 'Chrom
> e', family: 'chrome', isChosen: true, majorVersion: '72', name: 'chrome', path:
> 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', version: '72
> .0.3626.121', isHeaded: true, isHeadless: false } with args http://localhost:494
> 78/__/#/tests/integration\examples\actions.spec.js --test-type --ignore-certific
> ate-errors --start-maximized --silent-debugger-extension-api --no-default-browse
> r-check --no-first-run --noerrdialogs --enable-fixed-layout --disable-popup-bloc
> king --disable-password-generation --disable-save-password-bubble --disable-sing
> le-click-autofill --disable-prompt-on-repos --disable-background-timer-throttlin
> g --disable-renderer-backgrounding --disable-renderer-throttling --disable-resto
> re-session-state --disable-translate --disable-new-profile-management --disable-
> new-avatar-menu --allow-insecure-localhost --reduce-security-for-testing --enabl
> e-automation --disable-infobars --disable-device-discovery-notifications --autop
> lay-policy=no-user-gesture-required --disable-site-isolation-trials --metrics-re
> cording-only --disable-prompt-on-repost --disable-hang-monitor --disable-sync --
> disable-web-resources --safebrowsing-disable-auto-update --safebrowsing-disable-
> download-protection --disable-client-side-phishing-detection --disable-component
> -update --disable-default-apps --use-fake-ui-for-media-stream --use-fake-device-
> for-media-stream --proxy-server=http://localhost:49478 --proxy-bypass-list=<-loo
> pback> --load-extension=C:\Users\abcdef\AppData\Roaming\Cypress\cy\production\bro
> wsers\chrome\interactive\CypressExtension,C:\Users\abcdef\Documents\cypress\resou
> rces\app\packages\extension\theme --user-data-dir=C:\Users\abcdef\AppData\Roaming
> \Cypress\cy\production\browsers\chrome\interactive --disk-cache-dir=C:\Users\cka
> ku\AppData\Roaming\Cypress\cy\production\browsers\chrome\interactive\CypressCach
> e
> 2019-07-17T15:37:57.564Z cypress:server:browsers browser opened
> 2019-07-17T15:37:58.361Z cypress:server:events got request for event: get:projec
> t:status, { path: 'C:\\Users\\abcdef\\Documents\\cypress\\resources\\app\\package
> s\\example' }
> 2019-07-17T15:37:58.367Z cypress:server:project get project status for undefined
>  C:\Users\abcdef\Documents\cypress\resources\app\packages\example
> 2019-07-17T15:37:58.373Z cypress:server:project no project id
> 2019-07-17T15:37:58.378Z cypress:server:events sending ipc data { type: 'get:pro
> ject:status', data: { id: 0.7535993345185117, data: { path: 'C:\\Users\\abcdef\\D
> ocuments\\cypress\\resources\\app\\packages\\example', state: 'VALID' } } }
> 2019-07-17T15:37:58.566Z cypress:server:events sending ipc data { type: 'launch:
> browser', data: { id: 0.538287740447811, data: { browserOpened: true } } }
> 2019-07-17T15:37:59.190Z cypress:server:routes Serving Cypress front-end by requ
> ested URL: /__/
> 2019-07-17T15:37:59.206Z cypress:server:server Getting remote state: { auth: und
> efined, props: null, origin: 'http://localhost:49478', strategy: 'file', visitin
> g: undefined, domainName: 'localhost', fileServer: 'http://localhost:49479' }
> 2019-07-17T15:37:59.211Z cypress:server:runner serving runner index.html with co
> nfig { version: '3.4.0', platform: 'win32', arch: 'x64', projectName: 'example'
> }
> 2019-07-17T15:37:59.275Z cypress:server:server Got CONNECT request from clientse
> rvices.googleapis.com:443
> 2019-07-17T15:37:59.277Z cypress:https-proxy Writing browserSocket connection he
> aders { url: 'clientservices.googleapis.com:443', headLength: 0, headers: { host
> : 'clientservices.googleapis.com:443', 'proxy-connection': 'keep-alive', 'user-a
> gent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like
>  Gecko) Chrome/72.0.3626.121 Safari/537.36' } }
> 2019-07-17T15:37:59.336Z cypress:https-proxy Got first head bytes { url: 'client
> services.googleapis.com:443', head: '\u0016\u0003\u0001\u0002\u0000\u0001\u0000\
> u0001∩┐╜\u0003\u0003V\u000e∩┐╜0hL∩┐╜∩┐╜∩┐╜\u0001\f∩┐╜∩┐╜7F┘Å\b⌂\t∩┐╜∩┐╜|∩┐╜╩á\u0
> 01fd∩┐╜∩┐╜ \u0003j∩┐╜∩┐╜NW\u001b∩┐╜)\u00174∩┐╜+∩┐╜\u000f~∩┐╜∩┐╜Cg∩┐╜∩┐╜∩┐╜\u001d
> ' }
> 2019-07-17T15:37:59.338Z cypress:server:server HTTPS request does not match URL:
>  https://clientservices.googleapis.com:443 with props: null
> 2019-07-17T15:37:59.339Z cypress:https-proxy Making connection to clientservices
> .googleapis.com:443
> 2019-07-17T15:37:59.340Z cypress:https-proxy getting proxy URL { port: 443, serv
> erPort: 49478, sniPort: 49480, url: 'https://clientservices.googleapis.com:443'
> }
> 2019-07-17T15:37:59.343Z cypress:server:server Got CONNECT request from accounts
> .google.com:443
> 2019-07-17T15:37:59.346Z cypress:https-proxy Writing browserSocket connection he
> aders { url: 'accounts.google.com:443', headLength: 0, headers: { host: 'account
> s.google.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0
> (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.
> 3626.121 Safari/537.36' } }
> ←[0mGET /__/ ←[32m200 ←[0m122.682 ms - -←[0m
> 2019-07-17T15:37:59.360Z cypress:https-proxy Got first head bytes { url: 'accoun
> ts.google.com:443', head: '\u0016\u0003\u0001\u0002\u0000\u0001\u0000\u0001∩┐╜\u
> 0003\u0003X#]∩┐╜AS<∩┐╜$v∩┐╜u∩┐╜ \u0015]\r∩┐╜∩┐╜∩┐╜5∩┐╜∩┐╜∩┐╜t∩┐╜\u0016∩┐╜CU∩┐╜$
> {?Z∩┐╜.AoX∩┐╜∩┐╜∩┐╜d^∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜∩┐╜ε½ê' }
> 2019-07-17T15:37:59.360Z cypress:server:server HTTPS request does not match URL:
>  https://accounts.google.com:443 with props: null
> 2019-07-17T15:37:59.360Z cypress:https-proxy Making connection to accounts.googl
> e.com:443
> 2019-07-17T15:37:59.361Z cypress:https-proxy getting proxy URL { port: 443, serv
> erPort: 49478, sniPort: 49480, url: 'https://accounts.google.com:443' }
> 2019-07-17T15:37:59.427Z cypress:network:connect successfully connected { opts:
> { port: '443', host: 'clientservices.googleapis.com', getDelayMsForRetry: [Funct
> ion: getDelayForRetry] }, iteration: 0 }
> 2019-07-17T15:37:59.431Z cypress:https-proxy received upstreamSocket callback fo
> r request { port: '443', hostname: 'clientservices.googleapis.com', err: undefin
> ed }
> 2019-07-17T15:37:59.442Z cypress:network:connect successfully connected { opts:
> { port: '443', host: 'accounts.google.com', getDelayMsForRetry: [Function: getDe
> layForRetry] }, iteration: 0 }
> 2019-07-17T15:37:59.443Z cypress:https-proxy received upstreamSocket callback fo
> r request { port: '443', hostname: 'accounts.google.com', err: undefined }
> ←[0mGET /__cypress/runner/cypress_runner.css ←[32m200 ←[0m47.626 ms - -←[0m
> ←[0mGET /__cypress/runner/cypress_runner.js ←[32m200 ←[0m5.365 ms - -←[0m
> ←[0mGET /__cypress/static/favicon.ico ←[32m200 ←[0m1.739 ms - -←[0m
> 2019-07-17T15:38:00.693Z cypress:server:server Got CONNECT request from localhos
> t:49478
> 2019-07-17T15:38:00.694Z cypress:https-proxy Writing browserSocket connection he
> aders { url: 'localhost:49478', headLength: 0, headers: { host: 'localhost:49478
> ', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Windows NT 6.1;
>  Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/
> 537.36' } }
> 2019-07-17T15:38:00.696Z cypress:https-proxy Got first head bytes { url: 'localh
> ost:49478', head: 'GET /__socket.io/?EIO=3&transport=websocket HTTP/1.1\r\nHost:
>  loca' }
> 2019-07-17T15:38:00.696Z cypress:server:server HTTPS request does not match URL:
>  https://localhost:49478 with props: null
> 2019-07-17T15:38:00.696Z cypress:https-proxy Making connection to localhost:4947
> 8
> 2019-07-17T15:38:00.697Z cypress:https-proxy getting proxy URL { port: 49478, se
> rverPort: 49478, sniPort: 49480, url: 'https://localhost:49478' }
> 2019-07-17T15:38:00.698Z cypress:network:connect successfully connected { opts:
> { port: '49478', host: 'localhost', getDelayMsForRetry: [Function: getDelayForRe
> try] }, iteration: 0 }
> 2019-07-17T15:38:00.699Z cypress:https-proxy received upstreamSocket callback fo
> r request { port: '49478', hostname: 'localhost', err: undefined }
> 2019-07-17T15:38:00.700Z cypress:server:server Got UPGRADE request from /__socke
> t.io/?EIO=3&transport=websocket
> 2019-07-17T15:38:00.711Z cypress:server:socket socket connected
> ←[0mGET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 ←[32m200 ←[0m1
> .845 ms - 77160←[0m
> 2019-07-17T15:38:02.049Z cypress:server:events got request for event: close:brow
> ser, undefined
> 2019-07-17T15:38:02.049Z cypress:server:browsers killing browser process
> 2019-07-17T15:38:02.094Z cypress:server:events sending ipc data { type: 'launch:
> browser', data: { id: 0.538287740447811, data: { browserClosed: true } } }
> 2019-07-17T15:38:02.102Z cypress:server:browsers browser process killed
> 2019-07-17T15:38:02.105Z cypress:server:events sending ipc data { type: 'close:b
> rowser', data: { id: 0.8687377968984005, data: null } }
> 2019-07-17T15:38:08.361Z cypress:server:events got request for event: get:projec
> t:status, { path: 'C:\\Users\\abcdef\\Documents\\cypress\\resources\\app\\package
> s\\example' }
> 2019-07-17T15:38:08.369Z cypress:server:project get project status for undefined
>  C:\Users\abcdef\Documents\cypress\resources\app\packages\example
> 2019-07-17T15:38:08.372Z cypress:server:project no project id
> 2019-07-17T15:38:08.377Z cypress:server:events sending ipc data { type: 'get:pro
> ject:status', data: { id: 0.1901979354181671, data: { path: 'C:\\Users\\abcdef\\D
> ocuments\\cypress\\resources\\app\\packages\\example', state: 'VALID' } } }
> 2019-07-17T15:38:18.362Z cypress:server:events got request for event: get:projec
> t:status, { path: 'C:\\Users\\abcdef\\Documents\\cypress\\resources\\app\\package
> s\\example' }
> 2019-07-17T15:38:18.369Z cypress:server:project get project status for undefined
>  C:\Users\abcdef\Documents\cypress\resources\app\packages\example
> 2019-07-17T15:38:18.372Z cypress:server:project no project id
> 2019-07-17T15:38:18.375Z cypress:server:events sending ipc data { type: 'get:pro
> ject:status', data: { id: 0.11333642136317579, data: { path: 'C:\\Users\\abcdef\\
> Documents\\cypress\\resources\\app\\packages\\example', state: 'VALID' } } }
> 2019-07-17T15:38:28.362Z cypress:server:events got request for event: get:projec
> t:status, { path: 'C:\\Users\\abcdef\\Documents\\cypress\\resources\\app\\package
> s\\example' }
> 2019-07-17T15:38:28.367Z cypress:server:project get project status for undefined
>  C:\Users\abcdef\Documents\cypress\resources\app\packages\example
> 2019-07-17T15:38:28.372Z cypress:server:project no project id
> 2019-07-17T15:38:28.375Z cypress:server:events sending ipc data { type: 'get:pro
> ject:status', data: { id: 0.6337090478925431, data: { path: 'C:\\Users\\abcdef\\D
> ocuments\\cypress\\resources\\app\\packages\\example', state: 'VALID' } } }
> 2019-07-17T15:38:38.363Z cypress:server:events got request for event: get:projec
> t:status, { path: 'C:\\Users\\abcdef\\Documents\\cypress\\resources\\app\\package
> s\\example' }
> 2019-07-17T15:38:45.094Z cypress:server:project get project status for undefined
>  C:\Users\abcdef\Documents\cypress\resources\app\packages\example
> 2019-07-17T15:38:45.100Z cypress:server:project no project id
> 2019-07-17T15:38:45.104Z cypress:server:events sending ipc data { type: 'get:pro
> ject:status', data: { id: 0.11085827183667396, data: { path: 'C:\\Users\\abcdef\\
> Documents\\cypress\\resources\\app\\packages\\example', state: 'VALID' } } }`

```

**Comment by jennifer-shehane** [comment]
@iackc Have you tried to run the test outside of the IT teams network - like, at home? The cause may be something else other than the whitelisting of the extensions.

**Comment by flotwig** [comment]
@iackc Could you try running your tests in Chromium? It may not be subject to the same restrictions as Chrome at your company.

You should be able to run tests in the included Electron browser either way: https://docs.cypress.io/guides/guides/launching-browsers.html

**Comment by iackc** [comment]
@jennifer-shehane : The tests fail on the IT issued laptop (regardless of network connected to).

@flotwig : Tests run fine in Electron browser but the application under tests have features that are not rendered in Electron and requires Chrome / Edge.

One thing to note: The test runs are successful when executed as "local-admin' but fails under normal-user.

**Comment by flotwig** [comment]
@iackc Have you tried installing Chromium and using that? It has exactly the same behavior as Chrome and it might work. If not, sadly, this is still something we have yet to find a good workaround for.

**Comment by iackc** [comment]
@flotwig: Unfortunately, Chromium is restricted from being installed on to the machines.

**Comment by iackc** [comment]
@flotwig Got Chromium installed as local-user, so the installation is not in the directory Cypress is expecting(C:/Program Files (x86)/Google/chrome-win32/chrome.exe).
So, I created the `mklink ` as per the debugging guide.

Chromium now appears in Cypress window as one of the browsers, however when running a spec, the Chromium window opens with "Chrome is being controlled by automated test software" but the page is blank and it is not able to execute the tests. Any thoughts / suggestions will be helpful.

**LOGS**

> 2019-07-19T16:09:40.948Z cypress:server:events got request for event: launch:bro

> wser, { browser: { displayName: 'Chromium', family: 'chrome', isChosen: true, ma
> jorVersion: '77', name: 'chromium', path: 'C:\\Program Files (x86)\\Google\\chro
> me-win32\\chrome.exe', version: '77.0.3858.0' }, spec: { absolute: 'C:/Users/xxx
> xx/Documents/cypress/resources/app/paxxxges/example/cypress/integration/examples
> /actions.spec.js', name: 'examples\\actions.spec.js', relative: 'cypress\\integr
> ation\\examples\\actions.spec.js' } }
> 2019-07-19T16:09:40.967Z cypress:server:openproject resetting project state, pre
> paring to launch browser
> 2019-07-19T16:09:40.972Z cypress:server:project resetting project instance C:\Us
> ers\xxxxx\Documents\cypress\resources\app\paxxxges\example
> 2019-07-19T16:09:40.978Z cypress:server:buffers resetting buffers
> 2019-07-19T16:09:40.981Z cypress:server:server Setting remoteAuth undefined
> 2019-07-19T16:09:40.984Z cypress:server:server Setting remoteOrigin http://local
> host:61392
> 2019-07-19T16:09:41.003Z cypress:server:server Setting remoteStrategy file
> 2019-07-19T16:09:41.005Z cypress:server:server Setting remoteHostAndPort null
> 2019-07-19T16:09:41.008Z cypress:server:server Setting remoteDocDomain localhost
> 
> 2019-07-19T16:09:41.012Z cypress:server:server Setting remoteFileServer http://l
> ocalhost:61393
> 2019-07-19T16:09:41.017Z cypress:server:server Getting remote state: { auth: und
> efined, props: null, origin: 'http://localhost:61392', strategy: 'file', visitin
> g: undefined, domainName: 'localhost', fileServer: 'http://localhost:61393' }
> 2019-07-19T16:09:41.027Z cypress:server:openproject launching browser: { display
> Name: 'Chromium', family: 'chrome', isChosen: true, majorVersion: '77', name: 'c
> hromium', path: 'C:\\Program Files (x86)\\Google\\chrome-win32\\chrome.exe', ver
> sion: '77.0.3858.0', isHeaded: true, isHeadless: false }, spec: cypress\integrat
> ion\examples\actions.spec.js
> 2019-07-19T16:09:41.050Z cypress:server:browsers opening browser { displayName:
> 'Chromium', family: 'chrome', isChosen: true, majorVersion: '77', name: 'chromiu
> m', path: 'C:\\Program Files (x86)\\Google\\chrome-win32\\chrome.exe', version:
> '77.0.3858.0', isHeaded: true, isHeadless: false }
> 2019-07-19T16:09:41.059Z cypress:server:plugins plugin event registered? { event
> : 'before:browser:launch', isRegistered: false }
> 2019-07-19T16:09:41.077Z cypress:server:appdata path: C:\Users\xxxxx\AppData\Roa
> ming\Cypress\cy\production\extensions
> 2019-07-19T16:09:41.087Z cypress:server:browsers cleaning up unclean exit status
> 
> 2019-07-19T16:09:41.154Z cypress:server:browsers launch in chrome: http://localh
> ost:61392/__/#/tests/integration\examples\actions.spec.js, --test-type,--ignore-
> certificate-errors,--start-maximized,--silent-debugger-extension-api,--no-defaul
> t-browser-check,--no-first-run,--noerrdialogs,--enable-fixed-layout,--disable-po
> pup-blocking,--disable-password-generation,--disable-save-password-bubble,--disa
> ble-single-click-autofill,--disable-prompt-on-repos,--disable-background-timer-t
> hrottling,--disable-renderer-backgrounding,--disable-renderer-throttling,--disab
> le-restore-session-state,--disable-translate,--disable-new-profile-management,--
> disable-new-avatar-menu,--allow-insecure-localhost,--reduce-security-for-testing
> ,--enable-automation,--disable-infobars,--disable-device-discovery-notifications
> ,--autoplay-policy=no-user-gesture-required,--disable-site-isolation-trials,--me
> trics-recording-only,--disable-prompt-on-repost,--disable-hang-monitor,--disable
> -sync,--disable-web-resources,--safebrowsing-disable-auto-update,--safebrowsing-
> disable-download-protection,--disable-client-side-phishing-detection,--disable-c
> omponent-update,--disable-default-apps,--use-fake-ui-for-media-stream,--use-fake
> -device-for-media-stream,--proxy-server=http://localhost:61392,--proxy-bypass-li
> st=<-loopback>,--load-extension=C:\Users\xxxxx\AppData\Roaming\Cypress\cy\produc
> tion\browsers\chromium\interactive\CypressExtension,C:\Users\xxxxx\Documents\cyp
> ress\resources\app\paxxxges\extension\theme,--user-data-dir=C:\Users\xxxxx\AppDa
> ta\Roaming\Cypress\cy\production\browsers\chromium\interactive,--disk-cache-dir=
> C:\Users\xxxxx\AppData\Roaming\Cypress\cy\production\browsers\chromium\interacti
> ve\CypressCache
> 2019-07-19T16:09:41.202Z cypress:launcher launching browser { displayName: 'Chro
> mium', family: 'chrome', isChosen: true, majorVersion: '77', name: 'chromium', p
> ath: 'C:\\Program Files (x86)\\Google\\chrome-win32\\chrome.exe', version: '77.0
> .3858.0', isHeaded: true, isHeadless: false } to open http://localhost:61392/__/
> #/tests/integration\examples\actions.spec.js
> 2019-07-19T16:09:41.213Z cypress:launcher spawning browser { displayName: 'Chrom
> ium', family: 'chrome', isChosen: true, majorVersion: '77', name: 'chromium', pa
> th: 'C:\\Program Files (x86)\\Google\\chrome-win32\\chrome.exe', version: '77.0.
> 3858.0', isHeaded: true, isHeadless: false } with args http://localhost:61392/__
> /#/tests/integration\examples\actions.spec.js --test-type --ignore-certificate-e
> rrors --start-maximized --silent-debugger-extension-api --no-default-browser-che
> ck --no-first-run --noerrdialogs --enable-fixed-layout --disable-popup-blocking
> --disable-password-generation --disable-save-password-bubble --disable-single-cl
> ick-autofill --disable-prompt-on-repos --disable-background-timer-throttling --d
> isable-renderer-backgrounding --disable-renderer-throttling --disable-restore-se
> ssion-state --disable-translate --disable-new-profile-management --disable-new-a
> vatar-menu --allow-insecure-localhost --reduce-security-for-testing --enable-aut
> omation --disable-infobars --disable-device-discovery-notifications --autoplay-p
> olicy=no-user-gesture-required --disable-site-isolation-trials --metrics-recordi
> ng-only --disable-prompt-on-repost --disable-hang-monitor --disable-sync --disab
> le-web-resources --safebrowsing-disable-auto-update --safebrowsing-disable-downl
> oad-protection --disable-client-side-phishing-detection --disable-component-upda
> te --disable-default-apps --use-fake-ui-for-media-stream --use-fake-device-for-m
> edia-stream --proxy-server=http://localhost:61392 --proxy-bypass-list=<-loopback
> > --load-extension=C:\Users\xxxxx\AppData\Roaming\Cypress\cy\production\browsers
> \chromium\interactive\CypressExtension,C:\Users\xxxxx\Documents\cypress\resource
> s\app\paxxxges\extension\theme --user-data-dir=C:\Users\xxxxx\AppData\Roaming\Cy
> press\cy\production\browsers\chromium\interactive --disk-cache-dir=C:\Users\xxx
> \AppData\Roaming\Cypress\cy\production\browsers\chromium\interactive\CypressCac
> he
> 2019-07-19T16:09:41.300Z cypress:server:browsers browser opened
> 2019-07-19T16:09:42.302Z cypress:server:events sending ipc data { type: 'launch:
> browser', data: { id: 0.14460671076361153, data: { browserOpened: true } } }
> 2019-07-19T16:09:47.926Z cypress:server:events got request for event: close:brow
> ser, undefined
> 2019-07-19T16:09:47.926Z cypress:server:browsers killing browser process
> 2019-07-19T16:09:47.965Z cypress:server:events sending ipc data { type: 'launch:
> browser', data: { id: 0.14460671076361153, data: { browserClosed: true } } }
> 2019-07-19T16:09:47.971Z cypress:server:browsers browser process killed
> 2019-07-19T16:09:47.975Z cypress:server:events sending ipc data { type: 'close:b
> rowser', data: { id: 0.3945706625304646, data: null } }
> 2019-07-19T16:09:49.254Z cypress:server:events got request for event: get:projec
> t:status, { path: 'C:\\Users\\xxxxx\\Documents\\cypress\\resources\\app\\paxxxge
> s\\example' }

**Comment by flotwig** [comment]
Nice, progress! Can you share a screenshot of the Chromium browser when you launch it via Cypress?

**Comment by iackc** [comment]
![image](https://user-images.githubusercontent.com/53011860/61550821-8136b680-aa21-11e9-989e-9ef535b46582.png)

**Comment by iackc** [comment]
@flotwig Any suggestions to troubleshoot this further?

**Comment by flotwig** [comment]
@iackc We can't bypass the restrictions that your company places on Chrome, unfortunately. You can try the workarounds here: https://docs.cypress.io/guides/references/error-messages.html#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues
