### ISSUE TITLE
Proxy auto-configuration (PAC) file support

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4766]
### Current behavior:

Cypress only supports a single HTTP_PROXY configuration.

### Workaround

This may work for some users.

1. Examine the PAC file to see what your company's main proxy URL is.
2. Set HTTP_PROXY to this proxy URL in the [proxy environment variables](https://docs.cypress.io/guides/references/proxy-configuration.html#Proxy-environment-variables)
3. Maybe set NO_PROXY to prevent the proxy being used to reach internal domains that don't need it. For example, `NO_PROXY=localhost,internal-api.mycompany.com,assets.mycompany.net`
4. Verify that you've configured it correctly in the [proxy settings](https://docs.cypress.io/guides/references/proxy-configuration.html#View-proxy-settings-in-Cypress​)

### Desired behavior:

Add support for PAC files, so that Javascript can be used to determine what proxy to use.

Potentially auto-discover PAC files, either with WPAD or with native APIs.

**Comment by rinshadkt** [comment]
Hi team,Any update on this.

**Comment by flotwig** [comment]
@rinshadkt this is not currently being worked on by anyone on the Cypress team. If you want to pick it up, feel free to open a pull request
