### ISSUE TITLE
cannot `type` negative number into number input with text selection

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#4767]
Cannot `type` negative number into number input with text selection

Relevant issue description: https://github.com/cypress-io/cypress/issues/2173#issuecomment-513099254

**Comment by fr0** [comment]
I am also having this problem, but `clear()` doesn't work either (the text remains in the input box) so I'm somewhat stuck. Is there an ETA for a fix?

**Comment by Bkucera** [comment]
@fr0 if `clear()` isn't working for you it may be another issue. Could you post a reproducible or show a video?

**Comment by fr0** [comment]
> @fr0 if `clear()` isn't working for you it may be another issue. Could you post a reproducible or show a video?

I discovered that my app had `preventDefault()` and `stopPropagation()` calls on the `delete` `keydown` handler that cypress was injecting. When I removed those the `clear()` worked.
