### ISSUE TITLE
Indicate when XHR's match aliases multiple times, and correlate those to waits

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#477]
### Current behavior:
There's not an easy to know or correlate multiple matched XHR aliases to knowing how to wait for them.

Here's an example screenshot:

![zone_single_modal_edit_name_spec js-1](https://cloud.githubusercontent.com/assets/1268976/24377327/0f5a42f0-130d-11e7-98d4-d4191be0b558.png)

The problem is that the user is trying to wait **on the 2nd** XHR. But since they've only added a single `cy.wait("@getTable")` Cypress only waited on the first XHR to resolve.

### Desired behavior:

When an XHR matches an alias multiple times we should add a number indicator next to it... 

```
(XHR) /getTable @getTable
(XHR) /getTable @getTable.2
(XHR) /getTable @getTable.3
```
So then when adding code like:

```js
cy
.wait("@getTable")
.wait("@getTable")
.wait("@getTable")
```

The command log would actually look like:

```
WAIT @getTable
WAIT @getTable.2
WAIT @getTable.3
```

**Comment by bsmithEG** [comment]
Any news on this one?  There's a circumstance where I need to actually check if the same XHR gets requested N times, so I'm encountering this issue.

**Comment by itaykotler-fundbox** [comment]
Hi @brian-mann, any progress with this issue?

**Comment by jennifer-shehane** [comment]
@bsmithEG There actually is an undocumented way to check the number of times an XHR was responsed to using `.all` on the alias. 

```js
cy.wait('@getRuns')
cy.tick(10000)
// should have done 2 request responses, and definitely not 3
cy.get('@getRuns.all').should('have.length', 2)
```

**Comment by jennifer-shehane** [comment]
We've created a new issue to track this - with work started in a PR here: https://github.com/cypress-io/cypress/issues/2868

**Comment by lilaconlee** [comment]
Played around with UI options a bit, would love any opinions. @jennifer-shehane @chrisbreiding 

Ordinal:
![screen shot 2018-12-04 at 4 34 21 pm](https://user-images.githubusercontent.com/7514489/49477966-81fd3e00-f7ec-11e8-9141-8dc42421c1a8.png)

Cardinal:
![screen shot 2018-12-04 at 4 41 53 pm](https://user-images.githubusercontent.com/7514489/49478020-ab1dce80-f7ec-11e8-83ac-4582646b6ead.png)

Tooltip:
![screen shot 2018-12-04 at 4 39 47 pm 2](https://user-images.githubusercontent.com/7514489/49478041-ba048100-f7ec-11e8-8981-e4115f3e95f3.png)

Labels for stub:
![screen shot 2018-12-04 at 4 42 37 pm](https://user-images.githubusercontent.com/7514489/49478060-c8529d00-f7ec-11e8-9910-601a8ca8810e.png)
![screen shot 2018-12-04 at 4 42 23 pm](https://user-images.githubusercontent.com/7514489/49478061-c8eb3380-f7ec-11e8-9c7e-d4988a89693a.png)

**Comment by chrisbreiding** [comment]
/cc @brian-mann ^

I like the ordinal version. For the stub itself, I like only having `3` with a tooltip saying something like  "This event occurred 3 times".

**Comment by jennifer-shehane** [comment]
I think that the numbers by themselves is a bit tricky because it's so close to the stylings for when we print the number of elements found for a command.

But I also think that the ordinal numbers are very English-centric, as ordinals are printed differently in each language. They also take up more room, which is a negative. 

I would also make sure that you take into account there being 3 digit numbers - someone will have 100+ requests

Maybe an alternative would be to write the number *beside* the printed alias...so:
```
WAIT      @getFoo | 1
```

**Comment by lilaconlee** [comment]
Some iteration, think I'm liking the first one so it keeps the visual relationship with the original stub. 
![screen shot 2018-12-06 at 10 50 15 am](https://user-images.githubusercontent.com/7514489/49598676-25656480-f94d-11e8-8ce5-7fcb0f33191c.png)


![screen shot 2018-12-06 at 10 27 03 am](https://user-images.githubusercontent.com/7514489/49598528-d0c1e980-f94c-11e8-995b-45a805e396d9.png)

**Comment by brian-mann** [comment]
Just like how counting the DOM elements works, I don't think we need to include anything if the event happens *once*, but do include the numbering for every subsequent event.

**Comment by lilaconlee** [comment]
I'll do something more like this for now for when there are more than one
<img width="188" alt="screen shot 2018-12-07 at 12 49 01 pm" src="https://user-images.githubusercontent.com/7514489/49666708-e7d50a00-fa26-11e8-959f-47f78467d36e.png">

**Comment by lilaconlee** [comment]
PR'd in #2960, screenshots of that below. 

One topic I'm not sure on:
- Showing the counts for all aliases/references, not just ones that were fired multiple times. Changing the design to always show the count was brought up at the most recent test runner meeting. This was my original implementation, but got some feedback to change it. Am definitely down to change it back as it cuts down on branching logic. Main downside would be the case where you only have one fired alias, the count might seem out of place.

Some topics we discussed but I didn't implement:
- Adding more emphasis to collapsed stub so folks know it opens. (now that we show the numbers on the aliases, not that important to see the duplicates)
- Adding alias counts to collapsed duplicates (didn't for same reason as above)
- Updating the similar UI for DOM elements (not the same usage, doesn't make sense to have the same UI)
- Showing the range of the counts found, like "1-4" or "1...4" (all of the options I came up with seemed more confusing, seems explained by the tooltip)

A couple of different scenarios with aliases:
![screen shot 2018-12-17 at 1 51 40 pm](https://user-images.githubusercontent.com/7514489/50111833-56724e80-0203-11e9-8776-8f8b81cab8b8.png)
With duplicates open:
![screen shot 2018-12-17 at 1 52 32 pm](https://user-images.githubusercontent.com/7514489/50111835-57a37b80-0203-11e9-9212-0149770ced38.png)

**Comment by chrisbreiding** [comment]
The code for this is complete, but not yet released. It will be released in 4.0. At that time, we'll post a new message referencing the [changelog](https://docs.cypress.io/guides/references/changelog.html).

**Comment by danielclariondoor** [comment]
This is just what I need, but I can't find anything in the docs.
How would wait the nth instance of a particular call?

**Comment by strass** [comment]
Graphql only has a single endpoint so we have cases where we load the same URI multiple times on the page. I don't see any suggestions on how to wait for a variable number of requests in the docs. I would love a way to wait for all routes of a certain alias to finish, such as `cy.wait('@graphql.all')`.
