### ISSUE TITLE
Property 'state' does not exist on type 'Chainable<undefined>'

### ISSUE THREAD

**Issue by lifeiscontent** [cypress-io/cypress#4771]
### Current behavior: 

`cy.state` doesn't exist on typescript definitions

### Desired behavior: 

`cy.state` exists on typescript definitions

### Steps to reproduce: (app code and test code)

just check `cy.state` and see its not defined

### Versions

Cypress Latest

**Comment by jennifer-shehane** [comment]
Previous docs issue for cy.state https://github.com/cypress-io/cypress-documentation/issues/108

**Comment by amitguptagwl** [comment]
Property 'state' does not exist on type 'cy'.

```js
/// <reference types="cypress" />
// @ts-check
exports.HomePage = () => {
    return cy.state("currentPage");
}
```

**Comment by sainthkh** [comment]
We can define it like below:

```ts
interface State {
  (property: 'document'): Document
  (property: 'window'): Cypress.AUTWindow
  (property: 'runnable'): any
  // etc. etc.
  (property: string): any
}
```

But the problem is that it's not sure `cy.state` should be revealed or not. => [Related link](https://github.com/cypress-io/cypress-documentation/pull/805)

**Comment by ShaneHudson** [comment]
For anyone that is trying to use @sainthkh's answer, use it like this:

```
  interface cy {
    state: State;
  }
```

**Comment by kdp88** [comment]
@ShaneHudson where would I put this interface, currently I have it in the index.d.ts but my spec file still gives ts error, im thinking i gotta add it to commands.ts?

**Comment by Keysox** [comment]
We're using:
```
declare global {
  namespace Cypress {
    interface Chainable {
      state(state: any): any
    }
  }
}
```
