### ISSUE TITLE
aut-iframe size does not respect scrollbar dimensions

### ISSUE THREAD

**Issue by WillsB3** [cypress-io/cypress#4772]
### Current behavior:

When a viewport width is set via `cy.viewport(…)`, the size set on the iframe does not take into account the dimensions of any visible scrollbar.

My assumption as to why this has not been observed more frequently is that when you use an Apple input device on MacOS (i.e. one that is "touch" supported - including a Magic Mouse) the default setting for scrollbar behaviour in the operating system is to use overlay scrollbars, which differ from traditional scrollbars in that they overlay the page content and do not reduce the available viewport width for page content. If you connect a "normal" (non-touch device) mouse, or set the operating system to "Always" show scrollbars (as in the screenshot below) you get regular scrollbars which do not overlay the content of the page. Chrome on Windows does not use overlay scrollbars and so likely always exhibits this same behaviour.

I have the "Show scroll bars" setting set to `Always` on my dev machine as it helps catch errors in code that cause unintended horizontal scrolling which are tricky to notice with overlay scrollbars which aren't always visible – however it's important to note that this problem affects everyone using a non-touch based input device on MacOS (not just those with non-default system settings), and potentially also those on other operating systems that have more traditional scrollbars (e.g. Windows)

<img width="780" alt="Screenshot 2019-07-19 at 15 41 02" src="https://user-images.githubusercontent.com/868834/61544058-8d7c3d00-aa3c-11e9-8033-9b37d83d156e.png">

As an example, if I call `cy.viewport('iphone-5')` the width of the iframe is set to 320px. With non-overlay scrollbars the actual visible portion of the iframe is ~306px (In Chrome on MacOS the scrollbar width appears to be 14px by default) as the scrollbar width eats into the width of the viewport.

Ultimately, this is a problem because it has the effect of making horizontal scrollbars appear when viewing a page in cypress even though scrollbars do not appear on the actual device or when using Chrome Devtools device emulation (outside of Cypress). It's especially problematic for pages which have a `min-width: 320px;` declaration on the body or similar.

### Desired behavior:

I realise this is one of those thorny issues where it may be tricky to resolve in a clean way, but I'll outline my expectations from an ideal dev experience point-of-view…

For the emulation of touch devices at least, I expect the `aut-iframe` to take the scrollbar width into account and set it's size accordingly, so that any visible scrollbars do not reduce the available space for actual content in the iframes viewport below the dimensions passed to the call to `cy.viewport`.

I'm not sure where/when you'd be able to measure the scrollbar width in the Cypress execution flow, but here's a basic snippet of how to measure the scrollbar width:

https://jsbin.com/katorec/7/edit?js,console,output (click `Run with JS`)

### Steps to reproduce: (app code and test code)

1. Checkout https://github.com/WillsB3/cypress-test-tiny/tree/scrollbars
2. `npm i`
3. In MacOS `General` system preference pane, set "Show scroll bars:" to `Always`
3. `npm run cypress:run`

### Versions

Cypress 3.4.0
MacOS 10.14.5
Chrome Version 75.0.3770.100

**Comment by jennifer-shehane** [comment]
@WillsB3 Thanks for the detailed description and example repo. Test that fails:

```js
describe('page', () => {
  it('test viewport sizing', () => {
    cy.visit('https://example.cypress.io/')
    cy.viewport('iphone-5');
    cy.window().then(win => {
      expect(win.document.documentElement.scrollWidth).to.equal(320)
    })
  })
})
```

**Comment by jiagangzhang** [comment]
Am having the same problem, the visible scrollbar is causing top menu divs in undesired positions, thus covering elements destined for cy.click(). And the rootcause is my mouse 🤣 
@jennifer-shehane could you kindly share some info as whether this "behavior" will be addressed, or some walk-around?  
Thanks!

**Comment by jpierson** [comment]
I've just run into this issue trying to set up a test to catch any visual regressions in a responsive design which may accidentally cause horizontal scrolling in our supported mobile viewport sizes. I'm using Electron and Windows 10 which probably explains why I'm also noticing this issue. It's been about two years, are there any workarounds or plans in place to fix this?
