### ISSUE TITLE
Not able to pass space key in type('{SPACE}')

### ISSUE THREAD

**Issue by rakutenRandhir** [cypress-io/cypress#4773]

**Comment by nataliejuner** [comment]
https://github.com/cypress-io/cypress/issues/807

This might help you.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
