### ISSUE TITLE
`preinstall` script is broken on Windows

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4775]
### Current behavior:

`preinstall` in the main package doesn't work on Windows because of `rm` and `true`:

![image](https://user-images.githubusercontent.com/1151760/61635933-964e5800-ac62-11e9-917b-ef4a070e70d1.png)

AppVeyor appears to be passing because it has busybox or something similar installed

**Comment by bahmutov** [comment]
Ha, on AppVeyor Windows we don't call `npm install` in the root

- See https://github.com/cypress-io/cypress/blob/develop/appveyor.yml
- Instead we call "npm install --ignore-scripts"
- Successful AppVeyor CI Windows run https://ci.appveyor.com/project/cypress-io/cypress/builds/26111267/job/vme8dftwtmexx97p

**Comment by flotwig** [comment]
What's the reason for doing `--ignore-scripts` and executing it all step by step in `appveyor.yml`?

**Comment by bahmutov** [comment]
Appveyor falling on its face over and over trying to do too much

**Comment by bahmutov** [comment]
But to catch your error we should call “npm run postinstall” there

**Comment by flotwig** [comment]
> Appveyor falling on its face over and over trying to do too much

Makes sense... I'm currently on my third re-install attempt in Windows, just trying to get `npm run all install --serial` to work once :D

> But to catch your error we should call “npm run postinstall” there

Good idea.

**Comment by bahmutov** [comment]
Except on Windows we also run commands several times I think. I think we should just have a shelljs node script to remove folders and ignore errors - that should be cross platform
