### ISSUE TITLE
cy.route({..., respond: false}) response should not validate for non-null / non-undefined value

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#48]
If I pass in the option `respond: false` to `cy.route()` command, the command log is displaying error:
```
CypressError: cy.route() cannot accept an undefined or null response. It must be set to something, 
even an empty string will work.
```
Cypress should not be validating the response when option `respond: false` is defined.

**Example code**
```
describe "class doesn't load", ->
  cy.route({
    url: /^\/classifications\/\d+/
    respond: false
  }).as("classNotResponded")
```

**Example of commands log**
![screen shot 2015-07-01 at 10 56 30 am](https://cloud.githubusercontent.com/assets/1271364/8457606/5513957a-1fe0-11e5-9934-e1d93b267290.png)

**Comment by brian-mann** [comment]
Fixed in [`0.9.1`](https://github.com/cypress-io/cypress/wiki/Changelog#091-07032015).
