### ISSUE TITLE
Set ui to tdd in Cypress?

### ISSUE THREAD

**Issue by basickarl** [cypress-io/cypress#4801]
Code:
```
suite('example client unit test', function() {
    test('should just pass', function() {
        assert(true);
    });
});
```
Error:
```
  1)  An uncaught error was detected outside of a test:
     Uncaught ReferenceError: suite is not defined

This error originated from your test code, not from Cypress.
```

Since Cypress uses Mocha, I was surprised at this. In mocha you would set the ui property to tdd in the .mocharc.json file. How does one do this in Cypress?

**Comment by bahmutov** [comment]
Please read https://on.cypress.io/writing-your-first-test to see the Mocha test syntax we support. Also the assertions are described in https://on.cypress.io/assertions

**Comment by basickarl** [comment]
@bahmutov It states in that page (yes, I have read both pages plus this one: https://docs.cypress.io/guides/references/bundled-tools.html#Mocha).

> Over in the Command Log you’ll see Cypress display the suite, the test and your first assertion (which should be passing in green).

> Cypress provides a nice Test Runner that gives you a visual structure of suites, tests, and assertions. 

Suite, test and assert are used in a TDD domain. Describe, it, and expect in BDD. Cypress documentation states a TDD approach yet uses BDD in code. This is confusing.

Perhaps an update to the documentation or perhaps pulling in the TDD from Mocha if it's not supported.

(The documentation in Cypress doesn't always include everything, hence why I am asking).

**Comment by bahmutov** [comment]
I see. So it would be just aliases, `suite -> describe`, `test -> it`, but nothing terribly different. We have forked Mocha a very long time ago, so pulling from Mocha would not be feasible I am afraid. Functionally, I don't think this would make any difference, and to be honest we are trying to come up with ways to even avoid using global variables like `describe` and `it` in the first place.

**Comment by basickarl** [comment]
@bahmutov Exactly. However there is a lot of confusion already around BDD vs. TDD on the net as it is for beginners, leading to mixed code. I really enjoy Cypress, so I just hope it would reflect good practice.

But ok, it's not supported, thanks!
