### ISSUE TITLE
CypressError: Timed out retrying: Expected to find element: '#Login.Submit', but never found it.

### ISSUE THREAD

**Issue by sapna014109** [cypress-io/cypress#4803]
Upon running the below code in cypress tool 

it("Login Application", () =>{

    cy.visit("url");
    cy.contains("Administration Portal");
    cy.get('#IDToken1');
    cy.get('#passwordInput').type("xyz");
    cy.get('#cbxDisclaimer').click();
    //cy.get('#Login.Submit').should('be.visible').click();
    cy.wait(3000);
    cy.get('#Login\.Submit').click();

})

we are getting the error : 
CypressError: Timed out retrying: Expected to find element: '#Login.Submit', but never found it.

I assume i have an issue as one div tag is not closed in the HTML source code. Is there any way we can ignore or by pass  the HTML tag close validation?

**Comment by sapna014109** [comment]
Issue resolved by using the name tag and setting the chrome setting as { chromeWebSecurity: false }

**Comment by sapna014109** [comment]
issue resolved

**Comment by sfiorotti** [comment]
{ chromeWebSecurity: false } this configuration was in cypress.json?

**Comment by chkashif167** [comment]
![image](https://user-images.githubusercontent.com/3283419/67683261-e13ee080-f9b2-11e9-84ba-411b696b5046.png)

facing this issue

**Comment by chkashif167** [comment]
here is code
describe('My first Cypress Test', ()=> {


    it('Navigate To Partie Site', () => {
        cy.visit('https://app-dev.partie.com/');
       
    })

    it('Login To Application', ()=> {
        cy.get('.btn-outline').click();
    })
          

            it('Provide User and Password', ()=> {
            cy.get('input[type="text"]')
            .type('kashifn1')
		    .get('input[type="password"]')
            .type('!1234567aA')
            .get('button.btn').click();
            })



            it('Click on account ', ()=> {
                cy.wait(500);
                cy.get('.bg-blue').click();
                cy.wait(500);
            })


    
})

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run since this one was already resolved. There may be a specific edge case with the issue that we need more detail to fix.
