### ISSUE TITLE
Any argument in Mocha callback cause the test to run forever

### ISSUE THREAD

**Issue by AlainBouchard** [cypress-io/cypress#4805]
### Current behavior:

When you use any argument in Mocha callback, it thinks the test is asynchronous and this callback means "done" to be called later.   This will cause the Test Runner to run forever.

### Desired behavior:

It would be nice to disallow it or to throw an error.

### Steps to reproduce: (app code and test code)

Causing the issue:

```js
    it.only('should return the all accounts when search is clicked with empty search input', (callback) => {
        cy
            .get(AccountsPage.searchButton)
            .click()
            .get(AccountsPage.totalAccountsFoundText)
            .invoke('text')
            .should('match', /^[0-9]+ accounts? found$/);
    });
```

vs working version:

```js
    it.only('should return the all accounts when search is clicked with empty search input', () => {
        cy
            .get(AccountsPage.searchButton)
            .click()
            .get(AccountsPage.totalAccountsFoundText)
            .invoke('text')
            .should('match', /^[0-9]+ accounts? found$/);
    });
```

### Versions
Cypress: 3.4.0
operating system: Windows8.1
browser: Chrome 75

**Comment by jennifer-shehane** [comment]
This is how Mocha, and in turn Cypress, works. https://mochajs.org/#asynchronous-code 

>In Mocha v3.0.0 and newer, returning a Promise and calling done() will result in an exception, as this is generally a mistake
>
>test will fail with `Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both..` In versions older than v3.0.0, the call to `done()` is effectively ignored.

Cypress is using a version older than 3.0.0, so this will throw when we update Mocha, which is part of this issue: https://github.com/cypress-io/cypress/issues/2528 which is pending release in 4.0

**Comment by jennifer-shehane** [comment]
Actually, revisiting this issue - this is just how Mocha works. This argument will always be treated as a 'done' callback, regardless of the name you give it. This behavior does not change in 4.0.
