### ISSUE TITLE
contains and find inside within should use the root

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#481]
## Current behavior:

I cannot use `.contains` inside `within` block, because it is a child command, so I have to use dummy `get` to get around it.

```js
cy.get('something').within(function () {
  cy.get('div').contains('my text')
})
```
I can also get around by explicitly using `root`

```js
cy.get('something').within(function () {
  cy.root().contains('my text')
})
```

## Expected behavior:

I think we can skip the `cy.root` if inside `within`

```js
cy.get('something').within(function () {
  cy.contains('my text')
})
```

Also, the docs for `root` in https://on.cypress.io/root call it `get`

```
Timeout	cy.get will retry for the duration of the defaultCommandTimeout
```

* Operating System: MacOS
* Cypress Version: 0.19.1

**Comment by jennifer-mann** [comment]
Fixed typo in `root` doc. https://github.com/cypress-io/cypress-documentation/commit/fd3aa419eafa9b01470b786057295a9b1cff2e2b

**Comment by jennifer-shehane** [comment]
This doesn't appear to be a problem anymore. `cy.contains()` is a dual command. This example works:

```js
it('within root contains', () => {
  cy.visit('https://example.cypress.io/commands/misc')
  cy.get('.container').eq(0).within(() => {
    cy.contains('Commands')
  })
})
```
