### ISSUE TITLE
Usage of async-await instead of then

### ISSUE THREAD

**Issue by janbaer** [cypress-io/cypress#4820]
Yesterday I did my first steps with Cypress and I was really impressed about it! 

Then I tried to use the content of a fixture, to pass it to a command. But I don't wanted to use the result of the async function `cy.fixture()` within a **then**. Instead I just made the whole beforeEach function async and used the result with an **await**
 
```
const searchInput = await cy.fixture('search-input')
```

And it was working great, but it had an unwanted side effect. The effect was that wherever I used **type**  inside of the same context, it was slowing down and wasn't typing the caharacters mulitple times. So instead of just typing **hello** it was typing in the browser **hhhheeeellllooo**. When I changed it backwards to read the result **fixture()** with **then** it was working again as expected?

Are there any explanations for this behaviour? Should async/await not be used?

**Comment by bahmutov** [comment]
@janbaer can you share your entire spec file (with all but the relevant code removed). I love that it prints **hhhheeeellllooo**

**Comment by janbaer** [comment]
I was trying to create a simple spec file with only the problem relevant test, but it was working there without any problem. So I'll invest a bit more time to make it reproducible.

**Comment by janbaer** [comment]
I was playing a bit with the order of when I load the fixture and when I visit the page and it seems that I have to load the data before and then goto the page where I want to type something. Initially I did it in the opposite direction because I also wanted to test some other things where I don't need the data from the fixture. So after changing the order of loading it was working fine with using async/await.
