### ISSUE TITLE
Stub / spy counter badge is cut off

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4822]
Cypress 3.4.0 with Electron or Chrome

Recipe in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window

Run the spec file and after it is finished click on the button "Open new window" _inside the application frame_ (like a user). The `cy.stub` counter keeps incrementing - and the badge appears, but the badge gets cut off on the left.

<img width="737" alt="Screen Shot 2019-07-25 at 9 25 51 AM" src="https://user-images.githubusercontent.com/2212006/61878210-921e7680-aebe-11e9-845e-e8bf8d74b130.png">

<img width="1138" alt="Screen Shot 2019-07-25 at 9 26 23 AM" src="https://user-images.githubusercontent.com/2212006/61878216-964a9400-aebe-11e9-9597-8520d40afe29.png">

Relevant markup

<img width="1279" alt="Screen Shot 2019-07-25 at 9 29 42 AM" src="https://user-images.githubusercontent.com/2212006/61878307-c4c86f00-aebe-11e9-9ff6-d1574e1ee8ec.png">

Relevant files:
- packages/reporter/src/commands/command.jsx
- packages/reporter/src/commands/commands.scss

**Comment by hhudson** [comment]
Hello @bahmutov  - I think I know how to address this. It would seem that the counter is not so much being 'cut off' as the border-radius css hasn't been defined to create a symmetrical pill shape around the counter. 

Specifically, I would propose changing the css to
```
.num-duplicates.has-alias {
      border-radius: 10px 10px 10px 10px;
      line-height: 2;
      padding: 3px 5px 3px 5px;
    }
```
I believe this change would give the desired 'not cut-off look' you are seeking. Would you like me to contribute this change?

**Comment by jennifer-shehane** [comment]
@hhudson Sure! The CSS is here. I def broke this about a month ago. 😝 	https://github.com/cypress-io/cypress/blob/issue-4874/packages/reporter/src/commands/commands.scss#L164
