### ISSUE TITLE
Scrolling parent containers in snapshots does not always reflect actual command behavior.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#483]
### Current behavior:
When writing commands like `cy.get('button').should('be.visible')`, during the snapshot preview, Cypress scrolls the appropriate scrollable containers so that I can see the `<button>` within the viewport of the Cypress Runner.

### Expected behavior:
The behavior of the automatically scrolling so that I can view the subject of the command is sometimes unexpected. Users may think that the `cy.get('button')` command *itself* scrolled the appropriate scrollable parents during it's execution, when in actuality it did not.

#### Test code:

In Kitchen Sink
```js
it('cy.get() - query DOM elements', function(){
  cy.visit('http://localhost:8080/commands/querying')

  cy.get('.query-ul').should('be.visible')
```

After running the test above, hover over the `get` command in the Command Log, the snapshot will scroll the window to have the `.query-ul` into view.

*Element is not visible until Window is scrolled in actuality*
<img width="1176" alt="screen shot 2017-04-07 at 1 58 11 pm" src="https://cloud.githubusercontent.com/assets/1271364/24812983/4cdf5396-1b9a-11e7-8e01-7d336edeccbf.png">

*Element is shown in snapshot as if Window was scrolled during cy.get*
<img width="1176" alt="screen shot 2017-04-07 at 1 58 22 pm" src="https://cloud.githubusercontent.com/assets/1271364/24812985/5129ce04-1b9a-11e7-86f8-fd0b0dbc0d21.png">

### Additional Info (images, notes, stack traces, etc)
**One can always inspect the exact behavior of Cypress during command execution by using cy.pause() to walk through each command. This is the most accurate way to determine the actual command's behavior and whether scrolling occurred.**

* Operating System: N/A
* Cypress Version: 0.19.1

**Comment by jennifer-mann** [comment]
One of the issues in reflecting scrolling during snapshots is that every element would have to have it's `scrollLeft` and `scrollTop` captured and reflected in the snapshot. 

Our current DOM snapshot code utilizes jQuery's `clone` (which uses JavaScript's `cloneNode`). This method does not properly clone over `scrollTop` and `scrollLeft`, so we'd have to write this behavior ourselves.

**Comment by jennifer-shehane** [comment]
Issue where the snapshot appears to have the element hidden under a sticky header https://github.com/cypress-io/cypress/issues/5989

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close this issue.
