### ISSUE TITLE
Optional values: bearer and sendImmediately are missing in Cypress.Auth interface (TypeScript)

### ISSUE THREAD

**Issue by hvuong-sigma** [cypress-io/cypress#4837]
### Current behavior:

The current interface for Auth:

```js
 interface Auth {
    username: string;
    password: string;
  }
```

### Desired behavior:

Both `bearer` and `sendImmediately` should be optional props:

```js
  interface Auth {
    username: string;
    password: string;
    bearer?: string;
    sendImmediately?: boolean;
  }
```

### Steps to reproduce: (app code and test code)

Try passing either `bearer` or `sendImmediately` as options

### Versions

Cypress 3.3.2

**Comment by jennifer-shehane** [comment]
Code can be found here for types: https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L47

**Comment by msarfrazanwar** [comment]
Is it done or can I work on this one ? @hvuong-sigma  @jennifer-shehane

**Comment by jennifer-shehane** [comment]
@msarfrazanwar 	You can work on this. Issues are closed when they are done.

**Comment by gabbersepp** [comment]
what seems to work is "bearer" auth. But to use this, it does not make sense to provide username and password as mandatory fields. So we should make username/password/bearer optional. @jennifer-shehane  will this be ok for you?

**Comment by flotwig** [comment]
`bearer` is not a valid option if passed to `auth`. It may appear to work, but it will not send the `bearer` token on subsequent requests, only the initial request. This behavior is currently only supported for username/password:

https://github.com/cypress-io/cypress/blob/c1416035e9cd0dfc0bd342ea2992cd8b4bc7a888/packages/server/lib/controllers/proxy.coffee#L364-L372

So more work would need to be done on the proxy to make the `bearer` token get sent with every request.

**Comment by gabbersepp** [comment]
hey thanks for your help. I will have a look at the code. Let's see if I understand what's going on there :-)

**Comment by gabbersepp** [comment]
> `bearer` is not a valid option if passed to `auth`. It may appear to work, but it will not send the `bearer` token on subsequent requests, only the initial request. This behavior is currently only supported for username/password:
> 
> https://github.com/cypress-io/cypress/blob/c1416035e9cd0dfc0bd342ea2992cd8b4bc7a888/packages/server/lib/controllers/proxy.coffee#L364-L372
> 
> So more work would need to be done on the proxy to make the `bearer` token get sent with every request.

Hey,

is there any documentation that shows how the behaviour should be?
Based on your comment I assumed that the basic auth header should be sent in subsequent requests. This is done if cy.visit is called with the `auth` option. If the options are omitted, no basic auths are sent along with the second request:
```
it('should go to Google directly', () => {
    cy.visit('http://localhost:3000', { auth: {username: "u", password: "p"} });
    cy.visit('http://localhost:3000/a');
  })
```

The same behaviour counts when a `bearer` token is provided.

**Comment by gabbersepp** [comment]
@flotwig Would you have a look at this again? Would be great :-)

**Comment by gabbersepp** [comment]
fyi: I have not finished the work on this issue and closed my PR. Feel free to take the changes made in the PR and finish the work :-)

**Comment by bruna-vaz** [comment]
Hey guys, any update on this one?

I have tried also directly passing Authorization inside the body but still does not work.

cy.request({
            method: 'GET',
            url: 'myuRL',
            headers: {
                Authorization: 'Berear myToken'
            }
})

Is there any workaround to solve this? I rather not have to pass my user and pwd in the headers for API testing.

**Comment by flotwig** [comment]
I am closing this issue since we won't be adding HTTP bearer auth to the `cy.visit` API at this time.

However, if you really need to send a bearer token with an HTTP request, there is a workaround: https://github.com/cypress-io/cypress/pull/15596#issuecomment-818909685

Please read https://github.com/cypress-io/cypress/pull/15596#issuecomment-818909685 for reasoning and workaround.
