### ISSUE TITLE
use production dependencies in final prod bundle

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#4844]
Ensure we are bundling production version of dependencies such as `react`, `bluebird`, `react-dom` etc

### Purpose
- if we bundle development versions, it hurts bundle size and efficiency(cpu, memory usage) and can conflict with development versions in AUT, for example messing up react devtools
- additionally, development versions such as `react` add in internal debug code that holds onto references, which can keep objects around in memory and lead to performance degradation or increased memory / heap size

**Comment by Saibamen** [comment]
How much bundle size we saved before and after?
