### ISSUE TITLE
Add `.includes` as a valid partial matcher for DOM assertions

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#4846]
Using the `contains` flag works but the `includes` does not work like so:

```js
cy.get('input').should('contain.value', '...') // works
cy.get('input').should('include.value', '...') // does not work
```

Per chai's API - it's standard that these flags are aliases of one another so you can use them either way. We need to accept `include` and `includes` when using assertions on DOM elements.

**Comment by jennifer-shehane** [comment]
In the updates in the PR, I'm still seeing the messaging with the `contain` text. Is this expected?

**My test**

```js
cy.get('input:first').should('include.value', '')
cy.get('input:first').should('includes.value', 'foo')
```

**Command Log**

<img width="540" alt="Screen Shot 2019-07-29 at 11 59 12 AM" src="https://user-images.githubusercontent.com/1271364/62023747-4cccb280-b1f8-11e9-800b-c5a558164cf7.png">

**Comment by Bkucera** [comment]
@jennifer-shehane yes, we use same messaging since the underlying functionality is the same. this is what chai does I believe
