### ISSUE TITLE
command args are not displayed in the Command Log when options also passed into command

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#485]
### Current behavior:
The Command Log displays a specific message for most commands, but for commands that allows args AND options, the args no longer display in the Command Log; only the options display.

### Expected behavior:
The args and options should display in the message for each command in the Command Log

#### Test code:

```js
it('test', () => {
  cy.visit('https://example.cypress.io/commands/actions')
  cy.get('#action-canvas').click('topRight')                // command log shows 'topRight'
  cy.get('#action-canvas').click('topRight', { force: true }) // command log shows '{force: true}'
})
```

### Additional Info (images, notes, stack traces, etc)

<img width="535" alt="screen shot 2017-04-13 at 4 04 49 pm" src="https://cloud.githubusercontent.com/assets/1271364/25022239/293f8352-2063-11e7-9bf2-263795aa492f.png">
 
* Operating System: N/A
* Cypress Version: 0.19.1

**Comment by jennifer-shehane** [comment]
This is still occurring in Cypress 3.4.0

**Comment by sainthkh** [comment]
#5762 will accidentally fix this issue, right? Because it moves options to have its own line.

**Comment by emilyrohrbough** [comment]
Verified in v11.1.0 that this is still and issue.

**Comment by Manuel-Suarez-Abascal** [comment]
@emilyrohrbough @sainthkh iI have opened a PR for review to fix this issue.
