### ISSUE TITLE
[Feature Request] In the GUI, show the number line of code being run rather than the step number

### ISSUE THREAD

**Issue by ChaseBig** [cypress-io/cypress#4858]
### Current behavior:

When viewing running tests via the GUI or recordings online, there is a number associated with each step. This isn't really helpful for any of my personal use-cases and I'm unsure if it's really that helpful for anyone else.

![image](https://user-images.githubusercontent.com/10504626/62048217-f3ea2380-b1d1-11e9-9070-67b9a4f3307a.png)

### Desired behavior:

What WOULD be incredibly helpful is if the number shown in the GUI for each step was in reference to the specific line of code being run. This would help to easily debug which specific line of the test is failing.

![image](https://user-images.githubusercontent.com/10504626/62048268-0f552e80-b1d2-11e9-80e8-d0468b844255.png)

### Versions

Cypress 3.4.0
OSX 10.14.6
Chrome 75
Electron 61

**Comment by pictuner** [comment]
That would be useful indeed. First thing I do is 'what does the step say? Grep it in the test script and revisit.

**Comment by ChaseBig** [comment]
> That would be useful indeed. First thing I do is 'what does the step say? Grep it in the test script and revisit.

I do the same. It's not a "blocker" at all, per-say. But when I have a few longggg tests that execute similar steps multiple times throughout the test, it makes it a bit difficult to know exactly which step failed when the test is so long. The feature I'm testing is a long user-flow, so segmenting it into smaller tests isn't exactly possible for these instances. 

Nonetheless, being able to reference the line of code that the failed step is located at would be much more helpful than somewhat-arbitrary ascending numbers.

**Comment by jennifer-shehane** [comment]
We've made some progress in this issue https://github.com/cypress-io/cypress/issues/3762 involving associating the Command Log output to the associated test code.

The first and biggest improvement, we believe, will be displaying the test code on error (with lines of code) and also allowing you to click to view the test file for each test / error. 

We haven't thought about this implementation *exactly*, and I'm not sure that we would display the lines of code to *replace* the step numbers, but it's definitely a good idea to somehow associate each printed command with the actual written test code.

**Comment by ChaseBig** [comment]
> We've made some progress in this issue #3762 involving associating the Command Log output to the associated test code.
> 
> The first and biggest improvement, we believe, will be displaying the test code on error (with lines of code) and also allowing you to click to view the test file for each test / error.
> 
> We haven't thought about this implementation _exactly_, and I'm not sure that we would display the lines of code to _replace_ the step numbers, but it's definitely a good idea to somehow associate each printed command with the actual written test code.

Hi @jennifer-shehane, thank you for taking the time to review and respond! 

These new improvements sound very exciting and will definitely be helpful. While I would still love to have a way to reference each step to a specific line of code, I understand that may not be viable.

**Comment by ChaseBig** [comment]
@jennifer-shehane How is this coming along?

**Comment by jennifer-shehane** [comment]
A lot of the code necessary to associate lines of code with tests and errors is being done in this PR https://github.com/cypress-io/cypress/pull/4041 

That PR will be merged into this PR about error improvements which will at least show code line information per error: https://github.com/cypress-io/cypress/pull/3930

**Comment by jennifer-shehane** [comment]
Closing this issue since it hasn’t had a lot of interest over the years. We do show a preview of the lines of code ok error now.
