### ISSUE TITLE
Improve clicking with modifier(s)

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#486]
The current experience issuing a ctrl-click , cmd-click, etc could use some improvement. 

First, add a section to the `cy.click` doc concerning modifiers, with an example or two. 

Second, consider updating the `cy.click` command to accept modifiers directly instead of needing `cy.type` command first. 

Currently you need this to ctrl-click:

```javascript
cy.get('body').type('{ctrl}', { release: false })
cy.get('#some-el').click()
```

Something like this would be a lot better:

```javascript
cy.get('#some-el').click({ ctrlKey: true })
```

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-191) by [Unito](https://www.unito.io/learn-more)

**Comment by tascioglu** [comment]
Hi Chris.. is it also possible to do this when there isn't any textfield?

**Comment by chrisbreiding** [comment]
The first example above works for a non-textfield.

**Comment by fr0** [comment]
The workaround didn't work for me. The `cy.get('body').type('{ctrl}', { release: false })` never fired the `keydown` event on `window`, which is what my app is looking for.

**Comment by chrisbreiding** [comment]
`cy.type` does exactly that. `cy.get('body').type('{ctrl}a')` will handle keydown/keyup. I think it expresses the user's actions pretty well as is, but we're always looking for ways to make the API more intuitive, so I'd love to hear any suggestions for improvement.

Can you describe in more detail what your test is doing that requires `cy.trigger`? It's possible it can be accomplished with `cy.type`. Or it might point out a use-case we haven't considered and that we can improve the experience for.

**Comment by fr0** [comment]
> `cy.type` does exactly that. `cy.get('body').type('{ctrl}a')` will handle keydown/keyup. I think it expresses the user's actions pretty well as is, but we're always looking for ways to make the API more intuitive, so I'd love to hear any suggestions for improvement.

That's not what I've experienced.  Try these two tests, which (IMO) should both pass. However, only the second one does.

```
    it('handles keydown (via type)', () => {
      let shiftPressed = false;
      cy.window().then(win => {
        win.addEventListener('keydown', ev => {
          if (ev.key === 'shift') {
            shiftPressed = true;
          }
        });
      });
      cy.get('body').type('{shift}', {release: false}).then(() => {
        expect(shiftPressed).to.be.true;
      });
    });

    it('handles keydown (via trigger)', () => {
      let shiftPressed = false;
      cy.window().then(win => {
        win.addEventListener('keydown', ev => {
          if (ev.key === 'shift') {
            shiftPressed = true;
          }
        });
      });
      cy.get('body').trigger('keydown', {key: 'shift'}).then(() => {
        expect(shiftPressed).to.be.true;
      });
    });
```

**Comment by chrisbreiding** [comment]
I see. Thanks for the information. This looks like a bug in how `cy.type` handles modifiers. I [created a separate issue](https://github.com/cypress-io/cypress/issues/3316) to track this.

**Comment by kevinSuttle** [comment]
Does `trigger()` work for things that are click sub-events, like `mouseDown` etc? e.g. `Alt-mousedown` + `mousemove` (not `onStartDrag`)

**Comment by gnapse** [comment]
I created this custom command, in case is helpful for others, or to know if there are any caveats here, if I'm shooting myself in the foot or anything like it (just devised it and seems to work well, but who knows, especially the hack to be able to use it inside `.within`):

```js
Cypress.Commands.add(
    "clickWithModifier",
    { prevSubject: "element" },
    (subject, modifier) => {
        // Make sure we can get the body even if inside a .within block
        cy.document().then($doc => {
            // Type the modifier into <body /> without releasing it
            const body = $doc.querySelector("body")
            cy.wrap(body).type(modifier, { release: false })
        })

        // Click the element while the modifier key is pressed
        cy.wrap(subject).click()

        cy.document().then($doc => {
            // Release the modifier key, again against <body />
            cy.wrap($doc.querySelector("body")).type(modifier)
        })
    }
)
```

Use it like this:

```js
cy.findByText("Hello world").clickWithModifier("{shift}")
```
