### ISSUE TITLE
Do not commit examples spec files

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4860]
When we bundle cypress-example-kitchensink example specs, we copy them and commit to the repo. This leads to the duplication and makes updating `cypress-example-kitchensink` version hard (have to remember to run `npm run build`!)

Instead we should just "build" the example when building the test runner binary and not commit these files

**Comment by brian-mann** [comment]
I believe we just need to add `packages/example/cypress` to `.gitignore` and delete the existing files.

The binary building process already runs the appropriate `npm run build` steps to ensure that the latest files are copied over from the kitchensink.
