### ISSUE TITLE
cy.type() can only accept a string or number. You passed in: 'undefined'

### ISSUE THREAD

**Issue by pablogiroud** [cypress-io/cypress#4866]
### Current behavior:
When I try to get data form a Json file, this message shown.
The question: Can I get text from a Json file?

![image](https://user-images.githubusercontent.com/47010042/62080116-6684ee80-b226-11e9-9d7b-75d1e94d584b.png)

### Desired behavior:
I Need to insert this data (that the Json file have) in the text area

### Steps to reproduce: (app code and test code)

**Test**
```
beforeEach(() => {
        cy.server()
        cy.fixture("licencia.json").then((data) => {
            cy.route('GET', 'licencia.json', data)
        })
it.only('POST - Add License', function () {
        cy.get('[id=operations-License-Post]').children('div').click()
          .get('button').contains('Try it out').click()
        cy.get('textarea').clear()
          .get('textarea').type(this.data)
```
** Json Example/format**
``` 
  {
      "nombres": "Pulga",
      "apellido": "Rodriguez",
      "tipoDocumento": "NOT_DEFINED",
      "fechaNacimiento": "1986-08-10T17:40:08.484Z",
      "nroLicencia": "32001001",
      "cuil": "20320010013",
      "domicilio": "25 de mayo 1350",
      "nacionalidad": "Argentino",
      "sexo": "Masculino",
      "grupoFactor": "0+",
      "nroTramite": "251350",
      "numeroInsumo": "string 1",
      "fechaOtorgamiento": "2019-07-26T17:40:08.484Z",
      "fechaRenovacion": "2019-07-26T17:40:08.484Z",
      "fechaVencimiento": "2019-07-26T17:40:08.484Z",
      "categoria": "A",
      "clase": "1",
      "restricciones": "ninguna",
      "observaciones": "cinco",
      "centroEmisor": "Las Talitas",
      "donante": true,
      "firmante": "Leito",
      "estado": "Vigente"
    }```
<!-- Issues without reproducible steps WILL BE CLOSED -->

<!-- You can fork https://github.com/cypress-io/cypress-test-tiny repo, set up a failing test, then tell us the repo/branch to try. -->

### Versions

<!-- Cypress, operating system, browser -->
win10
Chrome v75

**Comment by bahmutov** [comment]
Please read the https://docs.cypress.io/api/commands/fixture.html#Using-an-alias-to-access-a-fixture and the examples linked there. You are never saving the loaded fixture, so there is no `this.data` later on. You probably want
```js
beforeEach(() => {
  cy.server()
  cy.fixture("licencia.json")
    .as('data')
    .then((data) => {
       cy.route('GET', 'licencia.json', data)
    })
})
```
Or even shorter https://docs.cypress.io/api/commands/fixture.html#Shortcuts

```js
beforeEach(() => {
  cy.fixture("licencia.json").as('data')
  cy.server()
  cy.route('licencia.json', 'fixture:licencia')
})
```

**Comment by pablogiroud** [comment]
@bahmutov Thanks for the comment! I made this corrections but still have the other issue that I found in the other tries (a lot of tries)
![image](https://user-images.githubusercontent.com/47010042/62085368-caf97b00-b231-11e9-8ac1-fdda5484aee0.png)

**Comment by bahmutov** [comment]
so the JSON from the fixture is automatically parsed and converted into an object, right? You probably want to type it as text. This should do the trick
```
.get('textarea').type(JSON.stringify(this.data))
```

**Comment by pablogiroud** [comment]
@bahmutov this is another of the issues that I saw. using ```cy.get('textarea').type(JSON.stringify(this.data))``` is shown again

![image](https://user-images.githubusercontent.com/47010042/62136944-7dc1eb80-b2bb-11e9-8081-7ff8c1bf288c.png)

**Comment by bahmutov** [comment]
see https://github.com/cypress-io/cypress/issues/4287

**Comment by pablogiroud** [comment]
Finally! Thanks for all the help @bahmutov

First solution was use the correct sintaxis like bahmutov explained:
```
beforeEach(() => {
  cy.server()
  cy.fixture("licencia.json")
    .as('data')
    .then((data) => {
       cy.route('GET', 'licencia.json', data)
    })
})

Spec

cy.get('textarea').type(JSON.stringify(this.data))
```

BUT the second one, is related with this particular issue: I need a TXT file instead Json. The .txt don't need any particular syntax, so I can put the script with no issues related with specials characters.

For the .txt:

```
beforeEach(() => {
  cy.server()
  cy.fixture("licencia.txt")
    .as('data')
    .then((data) => {
       cy.route('GET', 'licencia.txt', data)
    })
})

Spec

cy.get('textarea').type(this.data)
``` 
![image](https://user-images.githubusercontent.com/47010042/62145692-427ae900-b2ca-11e9-99a9-443e5b622e19.png)

There's my first suite in cypress. Thank you guys!
