### ISSUE TITLE
Cannot click on 'readonly' inputs / textarea

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#4874]
### Current behavior:

As noted initially from this comment https://github.com/cypress-io/cypress/pull/4783#issuecomment-516174805, Cypress now errors since 3.4.1 release when attempting to click on a `readonly` input or textarea. 

### Desired behavior:

Unlike an input being `disabled`, having a `readonly` attribute does not restrict clicking, focusing, selecting, or triggering events on the element. These actions should be allowed and only typing should be restricted.

### Steps to reproduce: (app code and test code)

```js
cy.get('input[readonly]`).click()
```

### Versions

Cypress 3.4.1

**Comment by prashantabellad** [comment]
I updated to latest Cypress version and facing this issue of 'readonly' inputs while clicking the Calendar to select a date. When will this be resolved?

**Comment by jennifer-shehane** [comment]
@prashantabellad We have a working PR in, so just needs review. https://github.com/cypress-io/cypress/pull/4881

**Comment by jackwestmoretab** [comment]
Hey, any update on when this change will be merged in? :-)

**Comment by jennifer-shehane** [comment]
@Alendorff You're correct. The issue will be closed an commented on as released when this is fixed.

**Comment by hesamossanloo** [comment]
Put the input inside a div and click on the div. It worked for me.

**Comment by hajdun** [comment]
Same happens in 3.5.0 :(
But only in gitlab ci, image: cypress/base:12.13.0, not on local machine :(

**Comment by hajdun** [comment]
Turns out it was covered by another element https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Actionability
