### ISSUE TITLE
'this' is undefined

### ISSUE THREAD

**Issue by briwoto** [cypress-io/cypress#4880]
### Steps to reproduce: (app code and test code) and Current Code
```js
describe('Check Broken links', ()=>{
    beforeEach(function() {
        cy.visit('https://www.cypress.io/').get('a').as('links')
    })
    it('prints handler', ()=> {
       console.log(this.links);
    });
});
```

package.json
```json
{
  "name": "cypress_test",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cypress:open": "cypress open"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^3.4.1"
  }
}
```
### Error received

![image](https://user-images.githubusercontent.com/50180912/62158999-5c4e1780-b32e-11e9-9e35-bc01681f2945.png)

### Desired behavior:
it should print the "links" in the console

**Comment by Shelex** [comment]
https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Sharing-Context
 You can not access mocha context from arrow function, please use es5 function syntax:
```
it('has access to text', function () {
  this.text // is now available
})
```

**Comment by briwoto** [comment]
@Shelex Thanks for the response. I replaced arrow function with the ES5 syntax and it worked
