### ISSUE TITLE
The Cypress App could not be downloaded.

### ISSUE THREAD

**Issue by bfagundez** [cypress-io/cypress#4883]
# Current behavior:

When `yarn install` runs on Jenkins, this messages is displayed:

```
[?25hThe Cypress App could not be downloaded.

Please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.4.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 92ead24d077815fc02b8a42fba398cd9136f79fc8b6f2a07fe3f7137b365087b34039397bcda195b62db3da3e98643bf9647519e96b46eecfb243ca198d0d0c2
Computed checksum: 55de1b3d77d4ef57c0f893f1d53b726a29b522d6b3ea821cd7a133743679b0f790b18c26aa3120027fcef5b7ec39574e09672e2c5c6ac52027912b34d8a2a183

Expected downloaded file to have size: 141130568
Computed size: 141130568

----------

Platform: linux (Raspbian - )
Cypress Version: 3.4.0
```
### Desired behavior:

The installation of the module should be successful.

### Steps to reproduce: (app code and test code)

Create a package.json file, add:
```
"cypress": "^3.4.0"
```
As a dependency.
Run `yarn install` on linux alpine.

### Versions

Cypress: 3.4.0
Node: 10.14.2
Linux Alpine

**Comment by bfagundez** [comment]
Closing until I figure a way to reproduce.

**Comment by jennifer-shehane** [comment]
Check out this issue too: https://github.com/cypress-io/cypress/issues/4595

**Comment by jonauz** [comment]
This issue seems to be repeating again, or was never resolved. Should not be closed, as it's a massive blocker.

**Comment by jennifer-shehane** [comment]
@jonauz If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run since none was provided here.

**Comment by wjessop** [comment]
I'm getting this too on Travis CI:

```
URL: https://download.cypress.io/desktop/4.0.1?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 7e26904b56c560f9ba893085903b8435c651a86058b4ba81075f51158e4846e884a039c473d07ce74ef93ab8134164e8fe6eac192a8fababe99fc13ce757310e
Computed checksum: 333ecb0c0853026d8fe112c61dd62f47db4d52fab3031b994e589c821a348d4f3826ed31bb9fc72a98d5b0900753d46f601f9a0a3ebd7f3f159f9534f807f08e

Expected downloaded file to have size: 167819701
Computed size: 167819701
```

**Comment by majklovec** [comment]
Same here (gitlab pipeline)

```
77 Installing Cypress (version: 4.0.1)
78 [02:11:47]  Downloading Cypress     [started]
79 [02:11:56]  Downloading Cypress     [failed]
80 The Cypress App could not be downloaded.
81 Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
82 Otherwise, please check network connectivity and try again:
83 ----------
84 URL: https://download.cypress.io/desktop/4.0.1?platform=linux&arch=x64
85 Error: Corrupted download
86 Expected downloaded file to have checksum: 7e26904b56c560f9ba893085903b8435c651a86058b4ba81075f51158e4846e884a039c473d07ce74ef93ab8134164e8fe6eac192a8fababe99fc13ce757310e
87 Computed checksum: 57a8337690dfbc4ae533c63cd2541d8429d8276691012fe92e351042ed3c9ea8d3fb66664c8b8ef332183b89bc676fa7008da9065bdee6cd25c985697e612eac
88 Expected downloaded file to have size: 167819701
89 Computed size: 167819701```

**Comment by jlengstorf** [comment]
I just hit this error, and in my case the culprit was that I had mismatched lockfiles (I used `yarn` when I should have used `npm`

I deleted my `yarn.lock` and `node_modules`, ran a new `npm install`, and committed the updated `package-lock.json`, and that fixed the issue

**Comment by przemuh** [comment]
I confirm - removing `yarn.lock` + fresh install helped in my case.

What I did:

- upgrade cypress version in package.json
- run yarn install
- commit

My build on gitlabCI constantly failed because of corrupted download (checksum).

- remove `yarn.lock` + run `yarn install`
- commit

Now it works :)

**Comment by philipboeken** [comment]
I also hit this error on the gitlab CI server (using yarn). I'm sure that #4595 does not apply to my case. 
Switching from yarn to npm seems to resolve this issue:

- remove `yarn.lock`
- remove `node_modules`
- run `npm install`
- change `yarn install` into `npm install` in the `.gitlab-ci.yml` file
- commit

After performing these steps the job succeeded on the CI server. I prefer to use yarn, so I tried to switch back:

- remove `package-lock.json`
- remove `node_modules`
- run `yarn install`
- change `npm install` into `yarn install` in the `.gitlab-ci.yml` file
- commit

This resulted in the error again. I guess we'll use npm until this checksum mismatch with yarn is resolved.

**Comment by waspeer** [comment]
> I confirm - removing `yarn.lock` + fresh install helped in my case.
> 
> What I did:
> 
>     * upgrade cypress version in package.json
> 
>     * run yarn install
> 
>     * commit
> 
> 
> My build on gitlabCI constantly failed because of corrupted download (checksum).
> 
>     * remove `yarn.lock` + run `yarn install`
> 
>     * commit
> 
> 
> Now it works :)

This did the trick for me as well! Thanks!

**Comment by mustafawm** [comment]
Hi @jennifer-shehane I think the reason this issue occurs has to do with the way Cypress informs us about new versions availability.
<img width="468" alt="Screen Shot 2020-04-22 at 10 12 21 am" src="https://user-images.githubusercontent.com/13101565/79936477-cccf3280-8481-11ea-8718-7610d7c5ae3b.png">

As you can see, the popup tells users to install instead of **upgrade**. This will result in two entries in `yarn.lock`.
The first entry is for the first install `yarn add cypress` which will start with `cypress@*...`
The 2nd one will be for installing the specific version and it'll start with `cypress@3.6.1...`

If the popup message shows **upgrade** commands instead of install i.e. `yarn upgrade cypress@^3.6.1`, this duplicate entries issue will go away (_at least for projects that don't use yarn workspace_)

**Comment by jennifer-shehane** [comment]
@mustafawm yeah, this messaging is likely not helping. I'll open a PR to update this.

**Comment by Ilesanmi-Erioluwa-Victor** [comment]
Fixed this bug on my window 10 64 bits system, by deleting my `yarn.lock` file and `node_modules` folder and reinstall both `cypress` and `node_modules` using `npm install` to install my `nodule_modules` and `npm install cypress` to also install cypress package..
I hope this work for anyone facing this bug
