### ISSUE TITLE
click() on a react-router link makes cypress reload the whole page

### ISSUE THREAD

**Issue by ChrisGitter** [cypress-io/cypress#4887]
Expected: Cypress should not reload the window, instead it should the router let it do its thing
Actual: Cypress reloads the whole page, breaking the current setup.

Using version 3.4.1

**Comment by ChrisGitter** [comment]
Seems to be something else entirely

**Comment by supunkavinda** [comment]
Looks like this is still the default behavior. Any way to change this and avoid pushState reloading the page?
