### ISSUE TITLE
Layout issues with desktop GUI in 3.4.1

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#4888]
### Current behavior:

Moving to flexbox for the desktop GUI has created some layout problems.

When loading, the footer appears at the top:

![Screen Shot 2019-07-31 at 10 26 39 AM](https://user-images.githubusercontent.com/1157043/62304290-abd63580-b44b-11e9-90eb-12be4db4d1b5.png)

When there is a long list of specs and the update banner is present, the bottom of the list is cut off and it's impossible to scroll to the last spec:

![Screen Shot 2019-07-31 at 10 26 46 AM](https://user-images.githubusercontent.com/1157043/62220489-1f117600-b37e-11e9-9ef8-99f51d01a9c5.png)

### Desired behavior:

Layout should be the same as previous versions.

### Versions

Cypress: 3.4.1
OS: MacOS
Browser: N/A

**Comment by brian-mann** [comment]
Can you post screenshots of the after fix?

**Comment by brian-mann** [comment]
Good use case for screenshot diff'ing.

**Comment by chrisbreiding** [comment]
After screenshots:

![Screen Shot 2019-08-02 at 9 05 33 AM](https://user-images.githubusercontent.com/1157043/62372169-c7e9dd80-b504-11e9-965d-2a297f86187a.png)
![Screen Shot 2019-08-02 at 9 05 49 AM](https://user-images.githubusercontent.com/1157043/62372170-c7e9dd80-b504-11e9-88c0-69aa788a1fd5.png)
