### ISSUE TITLE
Parse YAML files automatically in cy.readFile()

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#489]
## Current behavior:
In order for me to parse a YAML file, I have to add this code to my tests:

```js
YAML = require('yamljs')

it('displays links', function () {
  cy.readFile('source/_data/sidebar.yml').then(function (yamlString) {
    var sidebar = YAML.parse(yamlString);
    expect(sidebar.api.and).to.equal('and.html')
  })
})
```

## Expected behavior:
I'd like Cypress to parse the YAML file for me, similar to how it does for JSON files. So I could write this:

```js
it('displays links', function () {
  cy.readFile('source/_data/sidebar.yml').then(function (sidebar) {
    expect(sidebar.api.and).to.equal('and.html')
  })
})
```

* Operating System: N/A
* Cypress Version: 0.19.2

**Comment by jennifer-shehane** [comment]
We have decided to go a different direction than was originally planned when this issue was opened over 2 years ago. 

I will be closing this issue since we do not want to integrate Yaml file parsing directly into the Cypress product at this time. 

We think this would be a good use case for a [Cypress plugin](https://on.cypress.io/plugins-guide), if there is demand for that, that others could pull into their Cypress tests.

**Comment by MiguelNiblock** [comment]
I was looking specifically for how to load yml files. Thank you @jennifer-shehane for documenting this use case. I might be able to create a custom cypress command to load yml files in a simplified manner. Please update this thread should you learn of a better practice/ plugin for reading yml files as fixtures in cypress.
