### ISSUE TITLE
Screenshot does not capture canvas in AUT when browser size is smaller than Cypress viewport size.

### ISSUE THREAD

**Issue by cpandit201** [cypress-io/cypress#4891]
### Current behavior:
Screenshot does not captures actual image present in browser

### Expected : 
Map present in application should be present in Screenshot

![image](https://user-images.githubusercontent.com/42322819/62267552-fb9d0880-b41b-11e9-8d00-781258dba55a.png)

### Actual: 
![image](
https://user-images.githubusercontent.com/42322819/62267616-3acb5980-b41c-11e9-8f28-9817d9816ee9.png)

### Desired behavior:
Any objects present in browser should be present in the screenshot. 

### Steps to reproduce: (app code and test code)
Cypress Test Code : https://gist.github.com/cpandit201/e51946a3af46febef59ea98d4e45f323

### Manually:
Go to - https://xyz.here.com/studio/
Login with user : cypress.io.tests@gmail.com
Password : cypress.io.tests
Create a Project
Check the Map

Expected screenshot to contain the map present in that project, Map does not appear in the screenshot

Code Captures the screenshot after navigating to the app.

### Versions
"cypress": "^3.4.0", MacOS Mojave with Chrome 75

**Comment by jennifer-shehane** [comment]
Thanks for providing a reproducible example!

Is a canvas element that's not being captured: 

```html
<canvas width="1570" height="625" oncontextmenu="return false;" type="layer" class="tmc" style="user-select: none; left: 0px; top: 0px; position: absolute; width: 1570px; height: 625px;"></canvas>
```

So, I've isolated this problem down to the browser size at the time of capturing the screenshot. Regardless of electron or Chrome, if you resize your browser below the size that is set for the `cy.viewport()` in Cypress, then the canvas is no longer captured in the screenshot. 

**Test code has**

```js
cy.viewport(1280, 920)
```

**Browser inner size: 1280 x 920**

![Screen Shot 2019-08-01 at 4 04 45 PM](https://user-images.githubusercontent.com/1271364/62282835-48153200-b476-11e9-8bbd-6271d5c0194a.png)

**Browser inner size: 1279 x 919**

![Screen Shot 2019-08-01 at 4 04 15 PM](https://user-images.githubusercontent.com/1271364/62282856-4f3c4000-b476-11e9-9266-a9a61e8ef62c.png)

**Comment by cpandit201** [comment]
Hi Jennifer, Thanks for finding the RCA, I was interested in fixing this issue,
Can you please tell me the cy.screenshot() implementation file responsible for taking screenshots?

I was looking into '[./packages/driver/src/cypress/screenshot.coffee](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/screenshot.coffee)', But was not able to get the method implementation for cy.screenshot(),

Also how did you figure out that it is due to change in the browser window size?

Thanking in advance,
Chirag Pandit

**Comment by cpandit201** [comment]
Hi @jennifer-shehane , Do we have any ETA for correcting this issue?

**Comment by cpandit201** [comment]
@jennifer-shehane , Thanks for your inputs on this issue. I eventually figured out the RCA by reducing the resolution in cy.viewport by less than my browser inner size. Have made it to 1200x500 which worked and took the screenshot as expected :)

**Comment by webdevisme** [comment]
Hi all, I've tried the viewport size fix, but no luck. The AUT in browser shows blank (as described above) however, screenshot() works ok.

**Comment by jennifer-shehane** [comment]
I'm no longer able to recreate this. The screenshot is taken at both sizes in Cypress 4.10.0.

Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by Arishyn** [comment]
Hey guys, am currently working on testing some games and we use Canvas to display UI, but Cypress browser records show blank (as described above) however, screenshot() works okay
I v tried to use cy.viewport fix, but didn't work out for me, still a blank canvas

**Comment by jennifer-shehane** [comment]
@Arishyn Cypress Test Replay does not currently capture Canvas elements. We'll be working on this in the future. Please open a new issue to report issues in the future.
