### ISSUE TITLE
Collect more CI info from bamboo CI

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#4895]
### Current behavior:

We're only capturing a few env vars from bamboo and most of them appear to be deprecated, we want to automatically capture some more - esp the git info laid out here: https://docs.cypress.io/guides/guides/continuous-integration.html#Git-information

There's a lot more we can capture from here: https://confluence.atlassian.com/bamboo/bamboo-variables-289277087.html

### Versions

3.4.1

Changes can be made here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.js

**Comment by Jazz405** [comment]
@jennifer-shehane 
I've pulled cypress down to take a whack at this. I've made the changes and the unit tests pass, but I'm unsure how to test this in a CI environment. When I had it running locally to test with local environment variables, I was getting the Service Unavailable error when trying to log into dashboard.

Any guidance is appreciated, thank you

**Comment by jennifer-shehane** [comment]
@Jazz405 We have unit tests to ensure the env variables are being properly pulled if they are passed as Bamboo has documented so you just need to have tests in the `ci_provider_spec.coffee`

**Comment by Jazz405** [comment]
Awesome thank you much. I've updated the test and merged in master. Preparing to open PR
