### ISSUE TITLE
Error on XHR stub if resonse json only contains a number or boolean

### ISSUE THREAD

**Issue by amberjs** [cypress-io/cypress#4899]
## Current behavior:

When a `fixture.json` ONLY contains a number or a boolean, cypress throws the following error: 

```
CypressError: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at Object.<anonymous> 
```

### Desired behavior:

For Cypress to accept fixtures that contain a number or a boolean only.

### Steps to reproduce: (app code and test code)

Fixtures:

content of _my-number.json_:
```json
26
```

content of _my-bool.json_:
```
true
```

Tests:
```js
 // fails:
    it('accepts a number', () => {
        cy.server();
        cy.route({method: 'GET', url: '/getnumber', response: 'fixture:my-number.json'}).as('mynumber');
        cy.visit('/');
        cy.wait('@mynumber').its('responseBody').should('be', 26);
    });

    // fails:
    it('accepts a boolean', () => {
        cy.server();
        cy.route({method: 'GET', url: '/getbool', response: 'fixture:my-bool.json'}).as('mybool');
        cy.visit('/');
        cy.wait('@mybool').its('responseBody').should('be', true);
    });
```

repo: https://github.com/amberjs/cypress-test-tiny

### Versions

Cypress 3.2.0 - 3.4.1
Chrome

**Comment by amberjs** [comment]
Any update on this?

**Comment by jennifer-shehane** [comment]
I can verify this behavior. This is a bug. This error only occurs when you use the `fixtures:` shorthand within the `cy.route()` property.

`num.json`

```json
26
```

`spec.js`

```js
it('accepts a number in cy.fixture', () => {
  cy.server()
  cy.fixture('num.json').as('number')
  cy.visit('https://example.cypress.io/commands/files')
  cy.route('GET', 'comments/*', '@number').as('getNumber')
  cy.get('.fixture-btn').click()

  cy.wait('@getNumber').its('responseBody')
    .should('eq', 26) // passes
});

it('fails when a number in fixture:', () => {
  cy.server()
  cy.visit('https://example.cypress.io/commands/files')
  cy.route('GET', 'comments/*', 'fixture:num.json').as('getNumber')
  cy.get('.fixture-btn').click() // fails after click

  cy.wait('@getNumber').its('responseBody')
    .should('eq', 26)
});
```

<img width="583" alt="Screen Shot 2020-01-06 at 5 29 03 PM" src="https://user-images.githubusercontent.com/1271364/71814195-1732cc00-30aa-11ea-910a-de9fbe7bcc17.png">

This error used to look slightly different: in 3.0.0 for example. 

![Screen Shot 2020-01-06 at 5 31 53 PM](https://user-images.githubusercontent.com/1271364/71814341-7d1f5380-30aa-11ea-8fc1-4da7c554892d.png)


## Cause / Fix

This is being thrown from this line of code:

https://github.com/cypress-io/cypress/blob/issue-2869-config-changes/packages/server/lib/controllers/xhrs.coffee#L58:L58

`Buffer.from` only accepts a String when `encoding` is passed as explained here: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding

@sainthkh added a fix for if the JSON file is `null`, but this does not handle cases where the JSON file is valid and a non-string (like being a Number of Boolean). https://github.com/cypress-io/cypress/pull/5562

## Workaround

Switch to using `cy.fixture()` syntax with `.as()` alias as shown above.

**Comment by mrmodise** [comment]
PR on the way @jennifer-shehane
