### ISSUE TITLE
cy.clear does not work on number inputs

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#490]
* Operating System: N/A
* Cypress Version: 0.19.2

### Are you requesting a feature or reporting a bug?
Bug

### Current behavior:
Using `cy.clear()` on a number input does not clear the input and throws an error

#### Test code:

```js
cy.get("input[type='number']").type("500").clear()
```

### Additional Info (images, notes, stack traces, etc)

*Error: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.*

<img width="465" alt="screen shot 2017-04-28 at 3 22 29 pm" src="https://cloud.githubusercontent.com/assets/1271364/25544033/c5867fee-2c26-11e7-8a3c-c37a93c24ffe.png">

---

A current workaround is to replace `cy.clear` with `cy.type("{ctrl}a{backspace}")`

**Comment by marinamarina** [comment]
Noticed that as well 👍

**Comment by jennifer-mann** [comment]
@marinamarina Thanks, fixed the typo!

**Comment by jbrecht** [comment]
@jennifer-shehane - this workaround worked for a while and then stopped working, but this works for me: `type('{selectall}{backspace}')`

**Comment by chrisbreiding** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
