### ISSUE TITLE
More Desktop gui weirdness since the flexbox changes

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#4909]
Maybe we need some visual testing setup 😅 	

### Current behavior: 

<img width="912" alt="Screen Shot 2019-08-02 at 3 03 23 PM" src="https://user-images.githubusercontent.com/1271364/62356321-ce914880-b536-11e9-8c8e-82dc4d0a6636.png">

### Desired behavior:

<img width="903" alt="Screen Shot 2019-08-02 at 3 05 42 PM" src="https://user-images.githubusercontent.com/1271364/62356414-09937c00-b537-11e9-8a89-138bd3ef232c.png">

### Versions

`develop` branch - 3.4.2 pre-release

**Comment by chrisbreiding** [comment]
Whoops - didn't see this and duplicated it: #4192. Going to close this one since the other includes another layout issue and is tied to the PR.
