### ISSUE TITLE
Unexpected behavior when editing cypress.json while running tests.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#492]
* Operating System: OSX
* Cypress Version: 0.19.2

### Are you requesting a feature or reporting a bug?
Bug

### Current behavior:
Since version 0.19.2: When running tests in Cypress (in Chrome 58), if I edit the `cypress.json` file and refresh my running tests, I get the dead Chrome page as shown below.

<img width="925" alt="screen shot 2017-05-05 at 12 47 49 pm" src="https://cloud.githubusercontent.com/assets/1271364/25755490/39e78e4a-3191-11e7-8e79-91155843fbea.png">

### Expected behavior:
Before 0.19.2, when I edited my `cypress.json` file, Cypress would close my current browser running tests. To be honest, this was never really an ideal solution either, but it did save me from having to manually go out and Stop my browser in Cypress and restart it.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
