### ISSUE TITLE
`.each` changes scope for next dual-command (like `cy.contains()`)

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#4921]
### Current behavior:

When you call `.each()`, e.g. on a `cy.get()` command, it changes the scope for next `cy.contains()` command.

Possibly affects other commands, and possibly calls other than `.each()` change the scope, too.

Originally reported [here](https://stackoverflow.com/questions/57293122/how-to-correctly-use-wrap-in-cypress).

### Steps to reproduce: (app code and test code)

```js
describe(`test`, () => {
    it(`test`, () => {
        cy.document().then(doc => {
            doc.body.innerHTML = `
                <div class="one"></div>
                <div>Search</div>
            `;
        });
        cy.get(`.one`)
            // comment this out for the next `cy.contains` to work properly
            .each(() => {});
        cy.contains(`Search`);
    });
});
```

![image](https://user-images.githubusercontent.com/5153846/62411597-a1f03600-b5f5-11e9-81b0-cb0ac8faaf3e.png)

### Versions

cypress `3.4.1`

**Comment by GazEdge** [comment]
@dwelle thanks for reporting this. I can confirm I am seeing the same issue (as per my SO post)

**Comment by jennifer-shehane** [comment]
Reproducible example from https://github.com/cypress-io/cypress/issues/5163

```js
it('FAILS with contains after each', () => {
  cy.visit('https://www.google.com/')
  cy.contains('About')
  cy.get('input[type="submit"]').each(() => {})
  cy.contains('About')
})

it('passes with contains after then', () => {
  cy.visit('https://www.google.com/')
  cy.contains('About')
  cy.get('input[type="submit"]').then(() => { })
  cy.contains('About')
})

it('passes with contains after should', () => {
  cy.visit('https://www.google.com/')
  cy.contains('About')
  cy.get('input[type="submit"]').should(() => { })
  cy.contains('About')
})
```

**Comment by jennifer-shehane** [comment]
Interesting to note that this seems to happen with custom dual-commands also (aside from just `cy.contains()` as noted in https://github.com/cypress-io/cypress/issues/6550

**Comment by jennifer-shehane** [comment]
Another example:

```js
it('BUG? - breaks a following contains command', () => {
  cy.visit('https://example.cypress.io/commands/connectors')
  cy.get('.connectors-each-ul>li').each(() => {})
  cy.contains('Chai', { timeout: 10 })
})
```
