### ISSUE TITLE
Server Error in '/' error during login on Chrome 76 

### ISSUE THREAD

**Issue by maximkoshelenko** [cypress-io/cypress#4923]
### Current behavior:
<img width="1429" alt="Screen Shot 2019-08-04 at 19 29 54" src="https://user-images.githubusercontent.com/35900275/62426501-4d7cb180-b6ee-11e9-8607-6459efeb6993.png">

Error:
```
<!-- Web.Config Configuration File -->  <configuration>     <system.web>         <customErrors mode="Off"/>     </system.web> </configuration>
--
```
Error start occurs only on Chrome 76 during executing test using UI runner (on Chromium, Electron and during manual execution error is not reproduces)
### Desired behavior:
The user becomes logged in.

```js
 cy.visit('https://www.empr.com');
    cy.get('button[aria-controls="modal-login"]')
      .click();
    cy.get('.medicallogin input#root_email:last()')
      .type('testuserukr@yopmail.com');
    cy.get('.medicallogin input#root_password:last()')
      .type('testuserukr@yopmail.com');
    cy.get('.medicallogin button:last()')
      .click();
  });
```

### Versions
Cypress 3.4.1
MacOS Mohave
Chrome Version 76.0.3809.87 (Official Build) (64-bit)

**Comment by maximkoshelenko** [comment]
Error text:
Server Error in '/' Application.
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine. 

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".

**Comment by maximkoshelenko** [comment]
On gitlab CI/CD im using this image cypress/browsers:node12.6.0-chrome75 and issue also not reproduses

**Comment by jennifer-shehane** [comment]
Hey I'm getting this error when running the provided test code. Can you provide any configuration you set while running Cypress also?

<img width="488" alt="Screen Shot 2019-08-05 at 8 15 14 PM" src="https://user-images.githubusercontent.com/1271364/62469212-cf87db80-b7bd-11e9-9375-cad1e7f1dfad.png">

**Comment by maximkoshelenko** [comment]
@jennifer-shehane  Sure:
support/index:
import './commands';
require('cypress-plugin-retries');
Cypress.env('RETRIES', 2);
Cypress.on('uncaught:exception', (err, runnable) => false);
plugins/index:
module.exports = (on, config) => {
  // ref: https://docs.cypress.io/api/plugins/browser-launch-api.html#Usage
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--disable-dev-shm-usage');
      return args;
    }
    return args;
  });
};
cypress/json:
  "defaultCommandTimeout": 20000,
  "chromeWebSecurity": false,
  "baseUrl": "https://www.empr.com/",
  "video": true,
  "numTestsKeptInMemory": 0
packedge/json:
{
  "name": "cypress-tests",
  "version": "1.0.0",
  "description": "Cypress implementation on sites",
  "main": "index.js",
  "scripts": {
    "cypress:open": "cypress open",
    "cypress:run": "cypress run",
    "lint": "eslint",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Maksim Koshelenko",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^3.4.0",
    "cypress-plugin-retries": "^1.2.2",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-cypress": "^2.2.1",
    "eslint-plugin-import": "^2.17.3"
  },
  "dependencies": {
    "faker": "^4.1.0"
  }
}

**Comment by maximkoshelenko** [comment]
@jennifer-shehane your error occurs due to lack of 
Cypress.on('uncaught:exception', (err, runnable) => false) is support/index

**Comment by jennifer-shehane** [comment]
This test seems to be passing now in 5.4.0.

```js
Cypress.on('uncaught:exception', (err, runnable) => false);

it('test', () => {
  cy.visit('https://www.empr.com');
  cy.get('button[aria-controls="modal-login"]')
    .click();
  cy.get('.medicallogin input#root_email:last()')
    .type('testuserukr@yopmail.com');
  cy.get('.medicallogin input#root_password:last()')
    .type('testuserukr@yopmail.com');
  cy.get('.medicallogin button:last()')
    .click();
})

```

<img width="1291" alt="Screen Shot 2020-10-20 at 2 50 53 PM" src="https://user-images.githubusercontent.com/1271364/96559974-b0eb0300-12e3-11eb-9df4-4f70df9d0581.png">


Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by maximkoshelenko** [comment]
@jennifer-shehane Looks like issue is repro only with:
"chromeWebSecurity": false
Demo project with your tests attached
[cypress-example.zip](https://github.com/cypress-io/cypress/files/6411674/cypress-example.zip)

**Comment by jennifer-shehane** [comment]
Yah I do see this behavior with the `chromeWebSecurity: false` option using this example: https://github.com/cypress-io/cypress/issues/4923#issuecomment-712681696. I'm not sure what's causing the application under test to error in this way.
