### ISSUE TITLE
Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by fanshyiis** [cypress-io/cypress#4925]
When I'm running in a docker environment
When you launch cypress
Always report dbus error
![image](https://user-images.githubusercontent.com/15103283/62434085-ca993c80-b769-11e9-9906-c1bf85f1e717.png)

**Comment by adomyaty55foundry** [comment]
Receiving this issue as well constantly always, I can still use cypress okay but nonetheless the error keeps coming in console

Using WSL 2 

![2019-12-03_1449](https://user-images.githubusercontent.com/54867449/70096544-2e2e5c00-15dc-11ea-8c18-eb9f9656c8a7.png)

**Comment by jennifer-shehane** [comment]
I'm not entirely sure this is a Cypress issue instead of something isolated to the docker container. 

Have you tried our docker images https://github.com/cypress-io/cypress-docker-images or made sure that you have [all system dependencies installed](https://hub.docker.com/r/cypress/base/dockerfile) required for cypress?

**Comment by iperdomo** [comment]
Hi,

You can see the same error in this CI job execution:
https://akvo.semaphoreci.com/jobs/1be15282-d440-40da-9932-7f245d4b48a6#L452

The actual test finished successfully but the dbus error is there.

We're using a container based on the latest `cypress/included:3.8.1`
https://github.com/akvo/akvo-dockerfiles/blob/9f9bb5317ebbca14972424b074792f9dd0eb785c/lumen-e2e-test/Dockerfile#L3

Any hints are more than welcome

**Comment by iperdomo** [comment]
The errors are shown when `ELECTRON_ENABLE_LOGGING=true` environment variable is set. The tests pass successfully.

A minimum sample system that shows this error. It's using the published Docker image `cypress/included:3.8.1`

https://github.com/iperdomo/cypress-docker-test

In Cypress documentation site you can find the same error message:

![2020-01-11_1399x670_scrot](https://user-images.githubusercontent.com/178474/72208687-2baa0680-34a6-11ea-877f-413ab1de3d7a.png)


* https://docs.cypress.io/guides/guides/debugging.html#Run-the-Cypress-app-by-itself

**Comment by iperdomo** [comment]
If you use a Linux host you expose the `/var/run/dbus/system_bus_socket` socket to the container and the errors go away. Disclaimer: Not entirely sure what security problems this "solution" brings.

See: https://github.com/iperdomo/cypress-docker-test#fixing-the-errors

**Comment by jennifer-shehane** [comment]
@iperdomo It also explains in the docs that these errors are fine if Cypress launches successfully. 

>Note: verbose Electron logging might show warnings that still allow Cypress to work normally. For example, the Cypress Test Runner opens normally despite the scary output below:

<img width="915" alt="Screen Shot 2020-01-13 at 4 01 49 PM" src="https://user-images.githubusercontent.com/1271364/72245089-18ba4200-361e-11ea-8932-bc9230470a0b.png">

You can safely ignore the dbus error if your tests are executing fine.

**Comment by matchu** [comment]
I think this is because WSL doesn't do any system startup, so there isn't a system dbus process running!

I fixed this by added `sudo dbus-daemon --system &> /dev/null` to my `.bashrc`, based on what I found here: https://github.com/Microsoft/WSL/issues/2941

**Comment by tahv0** [comment]
Having this issue. Is @matchu 's solution best or is there a better fix?

**Comment by saurabhmehta1601** [comment]
the issue is still persistent . Is there any workaround to get is working . I tried using cypress clean cache and then reinstalling it with yarn but it still shows the same error message 😖

**Comment by saurabhmehta1601** [comment]
Here is some information about my machine  💁‍♂️ :

Node Version : 14.18.2
Yarn Version : 1.22.17
OS: Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by dani8art** [comment]
Hi team, happening here as well, both using `cypress run` and the official docker image:

```
$ docker run -ti   \
  -v $(pwd)/cypress:/tmp/project   \
  -w /tmp/project   \
  cypress/included:9.1.1
[19:1217/115259.028519:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[19:1217/115259.032036:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[19:1217/115259.037345:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[178:1217/115259.085612:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
```

```
$ cypress run
It looks like this is your first time using Cypress: 9.1.1

✔  Verified Cypress! /home/vs/.cache/Cypress/9.1.1/Cypress

Opening Cypress...
[194:1217/115424.620771:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[194:1217/115424.625402:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[194:1217/115424.625457:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[356:1217/115424.656528:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
```

We have tried to hide those logs without success using what is told in the docs:

```
$ ELECTRON_ENABLE_LOGGING=false cypress run
[409:1217/120217.982611:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[409:1217/120217.986901:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[409:1217/120217.986943:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[566:1217/120218.010931:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
```

It isn't good for us to show logs with an `ERROR` level so it would be great if the issue is reopened and some investigations are performed. Or maybe there is a safe way to hide those logs.

Thanks in advance.
Don't hesitate to ask for whatever you need, happy to help with it.

**Comment by dzschille** [comment]
Same here, with Cypress 9.2 running Chrome 97 headless on Ubuntu 18.04.6, all dependencies installed.

```
npx cypress run --spec "integration/smoke/*" --config video=false --reporter junit --reporter-options "mochaFile=results/test-output-[hash].xml,toConsole=true" --headless --browser chrome

[32441:0107/132541.367106:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[32441:0107/132541.367258:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[32612:0107/132541.417021:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
```

**Comment by timwis** [comment]
I'm getting the same error with the basic recommended GitHub Action:

```yaml
name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          browser: chrome
        env:
          MAPBOX_API_KEY: test
```

**Comment by raress96** [comment]
Same issue in Github Actions, but I am using the cypress container image:
cypress/browsers:node16.13.0-chrome95-ff94

**Comment by nossila** [comment]
Same issue here running on CircleCI with image `cypress/base:16.13.2`. Also tried with `cypress/included:9.4.1` same issue, tests runs fine locally but on CircleCI some tests fail.

**Comment by raress96** [comment]
> Same issue as ^ in Github Actions, but I am using the cypress container image: `cypress/browsers:node16.13.0-chrome95-ff94`

Maybe it helps someone, managed to solve the issue by running the application and Cypress tests in a single `run` section in Github Actions. Not sure why but it worked before even in separate `run` sections:

```
      - name: Run App & Cypress
        run: |
          yarn ci-start & # run app in background
          npx -y wait-on DOMAIN_OF_APP --timeout 300000 &&
          yarn cypress:ci
```

**Comment by groovenectar** [comment]
Running into this as well. Tests that pass locally fail in Circle CI, intermittently, and also seeing the dbus errors

**Comment by Hideman85** [comment]
Still not working! `dbus-daemon` solution does not help either :(

Docker image: cypress/included:9.2.0

```bash
dbus-daemon --system &> /dev/null
cypress open --config baseUrl=http://localhost:3000

cypress_1  | dbus-daemon[8]: Failed to start message bus: Failed to bind socket "/var/run/dbus/system_bus_socket": No such file or directory
cypress_1  | [20:0302/135232.286048:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
cypress_1  | [20:0302/135232.296052:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
cypress_1  | [20:0302/135232.296220:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
```

**Comment by ShaneHudson** [comment]
It may or may not be relevant, but I found a single test (one to do with testing a stubbed `window.print` in an iframe) was responsible for it not exiting properly. When I removed that test (I couldn't find a fix for it), the CI tests completed correctly despite still showing the error bus message.

**Comment by Hideman85** [comment]
Mine does not wort, I do see cypress poping up and just die instantly.
I have multiple error thrown I don't even know which one is relevant neither how to fix it :(

<details>
<summary>docker-compose.yml</summary>

```
version: '3.7'
services:
  cypress:
    build:
      context: .
      dockerfile: ./Dockerfile.cypress
      network: host
    environment:
      - WAYLAND_DISPLAY
      - DISPLAY
    working_dir: /cypress
    entrypoint: ''
    command: bash -c '/cypress/start_cypress.sh'
    volumes:
      - ./cypress:/cypress/cypress
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
      - /tmp/.X11-unix:/tmp/.X11-unix
```

</details>

<details>
<summary>Full log</summary>

```
cypress_1  | dbus-daemon[8]: Failed to start message bus: Failed to bind socket "/var/run/dbus/system_bus_socket": No such file or directory
cypress_1  | [20:0302/135232.286048:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
cypress_1  | [20:0302/135232.296052:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
cypress_1  | [20:0302/135232.296220:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
cypress_1  | [20:0302/135232.327059:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [20:0302/135232.327135:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 1 time(s)
cypress_1  | [20:0302/135232.354858:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [20:0302/135232.354939:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 2 time(s)
cypress_1  | [20:0302/135232.382057:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [20:0302/135232.382136:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 3 time(s)
cypress_1  | [20:0302/135232.408801:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [20:0302/135232.408866:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 4 time(s)
cypress_1  | [20:0302/135232.445739:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [20:0302/135232.445824:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 5 time(s)
cypress_1  | [20:0302/135232.970337:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [20:0302/135232.970357:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 6 time(s)
cypress_1  | [20:0302/135232.970374:FATAL:gpu_data_manager_impl_private.cc(417)] GPU process isn't usable. Goodbye.
cypress_1  | [181:0302/135233.054929:ERROR:broker_posix.cc(43)] Invalid node channel message
cypress_1  | The Test Runner unexpectedly exited via a exit event with signal SIGILL
cypress_1  | 
cypress_1  | Please search Cypress documentation for possible solutions:
cypress_1  | 
cypress_1  | https://on.cypress.io
cypress_1  | 
cypress_1  | Check if there is a GitHub issue describing this crash:
cypress_1  | 
cypress_1  | https://github.com/cypress-io/cypress/issues
cypress_1  | 
cypress_1  | Consider opening a new issue.
cypress_1  | 
cypress_1  | ----------
cypress_1  | 
cypress_1  | Platform: linux-x64 (Debian - 10.11)
cypress_1  | Cypress Version: 9.2.0
```

</details>

To be honest I just tried multiple things nothing works :( in comparison I can run playwright webkit from docker without issue

**Comment by Uninen** [comment]
I'm now running into this w/ the latest Cypress (v9.5.1) in GitHub actions with the recommended setup.

This ticket is marked as closed but is there something being done about this or are we supposed just to downgrade? (Haven't had these issues w/ any previous version, been running actively w/ latest versions for over a year.)

**Comment by kashban** [comment]
Same as @Uninen, just running on Azure DevOps in Docker containers (Ubuntu 20.04). Locally (Windows 10, Chrome Headless) no issues.

**Comment by 1Copenut** [comment]
I'm seeing a similar error on WSL2 using Ubuntu 20 after installing latest Cypress 9.5.2, running on Node 14 LTS:

```
Opening Cypress...
[15034:0315/221126.886778:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[15034:0315/221126.886995:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[15213:0315/221126.912017:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
[15034:0315/221127.203895:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[15034:0315/221127.237355:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
^C[15034:0315/221150.336298:ERROR:connection.cc(66)] X connection error received.
```

**Comment by dani8art** [comment]
Hi @jennifer-shehane, could anyone take a look at this issue, please? I [commented some months ago](https://github.com/cypress-io/cypress/issues/4925#issuecomment-996679165) but it is still closed. We know cypress is working well despite the error, however, it would be great having a way to hide those confusing messages, don't you think?

**Comment by Uninen** [comment]
To be perfectly clear, at least for me this is an **actual bug** in the failing my tests in CI and there's no workaround sense, it's not just some random error messages (which I get in dev and frankly I couldn't give a s*it if the actual tests still work).

It's especially bad as this ticket is closed. So if there's no intention to fix it, the only real solution seems to be to start converting tests for Playwright :(

**Comment by donaldwasserman** [comment]
I wanted to write a follow up to @Uninen's comment. 

I just started testing our app with cypress, and it's shocking that running these tests in Github Actions isn't currently possible.

**Comment by cawoodm** [comment]
Any feedback from the cypress devs on what this error actually means?

**Comment by PauloFavero** [comment]
I am using docker compose to launch an electron app and I had the same issue. 
I fixed it setting `ipc: host` configuration in my docker-compose.yml.

**Comment by nemonemi** [comment]
I too am experiencing this issue with v9.1.0. 
Could we please re-open this ticket?

**Comment by cwveysey** [comment]
My Cypress tests pass locally, this issue looks to be preventing my tests from passing via CircleCI...

**Comment by qeviking** [comment]
So, this issue is still happening in 2022.  I see that this is a "closed" issue, but it is VERY much blocking me.  Anyone from the Cypress team want to weigh in?

**Comment by kevinjcliao** [comment]
I was unable to get this error message to disappear, which was causing running Cypress in GitLab CI to fail. I love Cypress, but this bug makes it completely unusable for me in continuous integration right now. :(
```
node:events:504
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}
```

**Comment by nemonemi** [comment]
@groovenectar, what should that link represent? It would be great if you could be a tiny bit more specific.

**Comment by groovenectar** [comment]
> @groovenectar, what should that link represent? It would be great if you could be a tiny bit more specific.

See the first item in the changelog released yesterday:

https://docs.cypress.io/guides/references/changelog#9-5-4

```
Updates were made to silence Electron warnings related to being unable to connect to dbus. These errors are normal and expected, and do not result in test failures. Because they are always present when running Electron inside docker containers, it has incorrectly led people to believe it is the root-cause of an error within their test run. By silencing these errors, it will improve the debug experience to allow users to focus on meaningful warning and error messages. Fixed [#19299](https://github.com/cypress-io/cypress/issues/19299).
```

**Comment by ShaneHudson** [comment]
Do you have any suggestions for how to debug failures on CI that have no trouble locally? It seems to be a blocker for a lot of people.

**Comment by groovenectar** [comment]
> Do you have any suggestions for how to debug failures on CI that have no trouble locally?

If your application is authenticated, that can get finicky... would double check the sessions and maybe use the experimental session support... be sure the session is validated

Can try increasing timeouts: https://docs.cypress.io/guides/references/configuration#Timeouts

Here are some general troubleshooting tips including specifying the browser: https://docs.cypress.io/guides/references/troubleshooting#Isolate-the-Problem

**Comment by Yashrocky96** [comment]
I'm facing the same errors but Cypress is executing fine with them on my Jenkins (Running without Dockers) and passing all tests as expected

**Comment by ManasPecenek** [comment]
This solved my problem: "mkdir -p /var/run/dbus && dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address"

For details: https://georgik.rocks/how-to-start-d-bus-in-docker-container/

**Comment by Zumwaloro** [comment]
This guide here help me get rid of the original issue in this thread:

https://docs.cypress.io/guides/getting-started/installing-cypress#Windows-Subsystem-for-Linux

Now I have another issue and I can't seem to find the solution for it.

![image](https://user-images.githubusercontent.com/36601162/165932934-d197a0e1-b07a-4227-b2ef-8319b46c021d.png)

**Comment by hutber** [comment]
If it helps, also having it with WSL and cypress v9.7.0

**Comment by repeat** [comment]
I got this issue too, with WSL2, Ubuntu 22.04 LTS, nodejs 16.15.1, npm 8.12.1, cypress 10.1.0.

**Comment by 2manoj1** [comment]
Failed to connect to the bus: Failed to connect to socket. Getting this error in Gitpod after
```bash
# use Cypress provided image with all dependencies included
FROM cypress/included:10.1.0
RUN node --version
RUN npm --version

RUN echo  " node version:    $(node -v) \n" \
    "npm version:     $(npm -v) \n" \
    "yarn version:    $(yarn -v) \n" \
    "debian version:  $(cat /etc/debian_version) \n" \
    "Chrome version:  $(google-chrome --version) \n" \
    "Firefox version: $(firefox --version) \n" \
    "git version:     $(git --version) 
```

**Comment by tertek** [comment]
https://gist.github.com/pjobson/6b9fb926c59f58aa73d4efa10fe13654

**Comment by Redskinsjo** [comment]
I am running a **puppeteer** instance on **docker** and it was failing on launch because of $DISPLAY not set not X server installed. Personally i am on macos but these [explanations](https://askubuntu.com/questions/432255/what-is-the-display-environment-variable) helped me understand the problem. 
However, in puppeteer if you don't need any mouse or keyboard actions, the solution to this failing is to set **headless: true**

**Comment by georgisoft2020** [comment]
For my case, it was caused by the fact that the service was not started.
`service dbus start`

**Comment by shubham-damkondwar** [comment]
> I am running a **puppeteer** instance on **docker** and it was failing on launch because of $DISPLAY not set not X server installed. Personally i am on macos but these [explanations](https://askubuntu.com/questions/432255/what-is-the-display-environment-variable) helped me understand the problem. However, in puppeteer if you don't need any mouse or keyboard actions, the solution to this failing is to set **headless: true**

This was helpful

**Comment by henriquecustodia** [comment]
> For my case, it was caused by the fact that the service was not started. `service dbus start`

@georgisoft2020 thanks! It just fixed my problem! 

I was tryng to run Cypress 13 with Nx 19 on WLS Ubuntu 22. After facing a lot of errors, this fixed everything: 

```bash 
sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
```
> Command from https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian

```bash
sudo service dbus start
```

>  Starting the dbus service will create the dbus folder and avoid some errors.

**Comment by sergiubologa** [comment]
I'm using `cypress/factory:4.2.1` base image and the issue still reproduces for me in Azure, even if the docs say that 
> See below under [Docker Prerequisites](https://docs.cypress.io/app/get-started/install-cypress#Docker-Prerequisites) for information on [Cypress Docker images](https://github.com/cypress-io/cypress-docker-images). These already include the necessary dependencies.

Here are my logs:
```
[2024-11-19 00:53:37.465] [INF] > e2e-cypress@1.0.0 test-cy
[2024-11-19 00:53:37.465] [INF] > cypress run --browser chrome --env=ACCOUNT=bbdedec --reporter=junit --reporter-options=mochaFile=/app/testresults/junit.athena.xml
[2024-11-19 00:54:01.455] [INF] [STARTED] Task without title.
[2024-11-19 00:54:36.496] [ERR] [FAILED] Cypress verification timed out.
[2024-11-19 00:54:36.496] [ERR] [FAILED] 
[2024-11-19 00:54:36.496] [ERR] [FAILED] This command failed with the following output:
[2024-11-19 00:54:36.496] [ERR] [FAILED] 
[2024-11-19 00:54:36.496] [ERR] [FAILED] /root/.cache/Cypress/13.13.3/Cypress/Cypress --no-sandbox --smoke-test --ping=584
[2024-11-19 00:54:36.496] [ERR] [FAILED] 
[2024-11-19 00:54:36.496] [ERR] [FAILED] ----------
[2024-11-19 00:54:36.496] [ERR] [FAILED] 
[2024-11-19 00:54:36.496] [ERR] [FAILED] [37:1119/005425.235261:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2024-11-19 00:54:36.496] [ERR] [FAILED] 
[2024-11-19 00:54:36.496] [ERR] [FAILED] ----------
[2024-11-19 00:54:36.496] [ERR] [FAILED] 
[2024-11-19 00:54:36.496] [ERR] [FAILED] Platform: linux-x64 (Debian - 12)
[2024-11-19 00:54:36.496] [ERR] [FAILED] Cypress Version: 13.13.3
[2024-11-19 00:54:36.497] [INF] Cypress verification timed out.
[2024-11-19 00:54:36.497] [INF] This command failed with the following output:
[2024-11-19 00:54:36.497] [INF] /root/.cache/Cypress/13.13.3/Cypress/Cypress --no-sandbox --smoke-test --ping=584
[2024-11-19 00:54:36.497] [INF] ----------
[2024-11-19 00:54:36.497] [INF] [37:1119/005425.235261:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2024-11-19 00:54:36.497] [INF] ----------
[2024-11-19 00:54:36.497] [INF] Platform: linux-x64 (Debian - 12)
[2024-11-19 00:54:36.497] [INF] Cypress Version: 13.13.3
```

**Comment by ziaulrehman40** [comment]
facing same issue, unable to resolve with provided suggestions so far. Cypress fails to start.

**Comment by ivo-ruzicka-neit** [comment]
facing the same issue using the cypress/included:13.7.0 image inside of GitHub Actions

error im getting: 
```
Run cypress run --headless
  
[STARTED] Task without title.
[FAILED] Cypress failed to start.
[FAILED] 
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED] 
[FAILED] Please refer to the error below for more details.
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] [106:0114/142320.785662:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Debian - 11.9)
[FAILED] Cypress Version: 13.7.0
Cypress failed to start.
This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
Please refer to the error below for more details.
----------
[106:0114/142320.785662:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
----------
Platform: linux-x64 (Debian - 11.9)
Cypress Version: 13.7.0
Error: Process completed with exit code 1.
```

**Comment by thehejik** [comment]
I resolved this issue with unavailable dbus socket by disabling `AppArmor` on my openSUSE 15.6 host system:
```bash
sudo aa-teardown # Temporary unloads aa profiles
sudo systemctl disable --now  apparmor.service 
sudo systemctl mask apparmor.service 

```

**Comment by johngray-glitch** [comment]
For any future /run/dbus/system_bus_socket error chasers: check if you are running on a readOnlyRootFileSystem. Cypress loves to write stuff to its binary folder (e.g. the `cypress verify` that runs first), and that binary folder's location in this included image, by default, is /root/.cache/Cypress. The _only_ error I was getting in my log output was this dbus error, no file permissions errors or anything like that. So it was quite the red herring, as this thread indicates. 

The two workarounds that worked for us:
1. mount a writeable /tmp (or any path you're feeling) directory, have an init container or start command `cp -r /root/.cache/Cypress /tmp`, and set `CYPRESS_INSTALL_BINARY` to `/tmp/Cypress`. 
2. use the browser images instead, with `CYPRESS_CACHE_FOLDER` and `NPM_CONFIG_PREFIX` set to some writeable mount, and use npm to install cypress instead.

**Comment by dmitriy-drenkaliuk** [comment]
This seems to be fixed in Cypress 15.0.0. We've updated to this version recently and still get these errors, but that doesn't break Cypress.

```
13:18:48  cypress-1  | [STARTED] Task without title.
13:18:49  cypress-1  | [SUCCESS] Task without title.
13:18:49  cypress-1  | [205:0904/121849.847099:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
13:18:50  cypress-1  | [205:0904/121850.463552:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
13:18:50  cypress-1  | [205:0904/121850.463595:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
13:18:50  cypress-1  | [205:0904/121850.464849:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Address does not contain a colon
13:18:50  cypress-1  | [205:0904/121850.464871:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Address does not contain a colon
13:18:50  cypress-1  | [205:0904/121850.464878:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Address does not contain a colon
13:18:50  cypress-1  | [205:0904/121850.464888:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Address does not contain a colon
13:18:50  cypress-1  | [205:0904/121850.464898:ERROR:dbus/object_proxy.cc:590] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type: 
13:18:50  cypress-1  | 
13:18:50  cypress-1  | DevTools listening on ws://127.0.0.1:36521/devtools/browser/8ae5c756-c504-4f82-a017-8e69b4ec7dd6
13:18:52  cypress-1  | Couldn't determine Mocha version
13:18:52  cypress-1  | 
13:18:52  cypress-1  | ====================================================================================================
13:18:52  cypress-1  | 
13:18:52  cypress-1  |   (Run Starting)
13:18:52  cypress-1  | 
13:18:52  cypress-1  |   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
13:18:52  cypress-1  |   │ Cypress:        15.0.0                                                                         │
13:18:52  cypress-1  |   │ Browser:        Electron 136 (headless)                                                        │
13:18:52  cypress-1  |   │ Node Version:   v22.19.0 (/usr/local/bin/node)                                                 │
13:18:52  cypress-1  |   │ Specs:          1 found (core-spec.cy.ts)                                                      │
13:18:52  cypress-1  |   │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
13:18:52  cypress-1  |   │ Experiments:    experimentalStudio=true                                                        │
13:18:52  cypress-1  |   └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**UPDATE:** wrote too soon, it happened again after 21 successful runs...

**Comment by dellis23** [comment]
I'm getting the errors and it doesn't seem to be problematic, but it's really noisy.  I'm using the latest official cypress docker image.

**Comment by SergeyYakubov** [comment]
I solved it by setting HOME variable to /tmp in Dockerfile.
