### ISSUE TITLE
Domain relaxation is buggy

### ISSUE THREAD

**Issue by tuberlinsap** [cypress-io/cypress#493]
* Operating System: Linux
* Cypress Version: Cypress CLI: 0.13.1

### Are you requesting a feature or reporting a bug?

Bug

### Current behavior:

When trying to run a test, I get the following error upon trying to "visit" the page.

```js
cy
      .visit(DOMAIN);
/* ... */
```

```
SecurityError: Failed to set the 'domain' property on 'Document': 'de' is a top-level domain.
```

### Expected behavior:

It should not try to "relax" to a top-level Domain.

### How to reproduce the current behavior:

Unfortunately we're trying to use cypress as a test tool in an intranet environment which I can not open access to. It seems to be an error with the relaxing of the domain, where the domain is not split up correctly or something like that. If you need further info, let me know.

**Comment by brian-mann** [comment]
I believe this is the same problem as #380. 

When there are 5 subsets in the domain Cypress fails to properly parse this. Switching to use the publicsuffix will fix this in #402.

**Comment by tuberlinsap** [comment]
Can you give me some kind of estimate of when this is going to be implemented?

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).

**Comment by nrutman** [comment]
I was not having this problem until I upgraded to 1.4.2 (see attached screenshot). Now I get a blank screen and this error in the console.

![cypress](https://user-images.githubusercontent.com/165184/35833488-7ad39b78-0a9f-11e8-9b51-af274382cf5d.png)

**Comment by brian-mann** [comment]
@nrutman Can you provide your test code and your `/etc/hosts` file?

I believe the **local** part is messing up the URL because there is a special override specifically for those.

**Comment by nrutman** [comment]
@brian-mann we are using custom DNS rules to route these domains (and nothing references `jazzhrd.local`). If you give me an email, I can send you more info about the DNS configuration privately—but it doesn't look like there are any smoking guns there.

Regarding my code, this happens as soon as my test opens. My first call is `cy.visit('/');`.

Let me know how you want to proceed. Thanks!

**Comment by chielos24** [comment]
Having the same issues here : https://github.com/cypress-io/cypress/issues/1278
1.4.1 is working fine.

**Comment by brian-mann** [comment]
@nrutman opened new issue here: https://github.com/cypress-io/cypress/issues/1292
