### ISSUE TITLE
No 'screenshot': true option in Config

### ISSUE THREAD

**Issue by nym** [cypress-io/cypress#4931]
### Current behavior:

Config does not squelch screenshots if `'screenshot': false` is specified. 

### Desired behavior:

Due to the extra time it takes to screenshot, we want to be able to control this via the config like `video: true/false`

**Comment by nym** [comment]
We ended up doing this via env flags and overwriting the screenshot command. Closing since true/false wouldn't work (would have to be "always|never|error".

**Comment by AliceShi789654** [comment]
I also want to achieve this goal, how to set up to prohibit the generation of screenshots? Thanks.
