### ISSUE TITLE
Capture stack traces from spec frame

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#4932]
It's currently not possible to capture stack traces from the spec frame because `cy` is defined in the top frame and browser don't allow cross-frame stack traces to be captured. In order to achieve this, we need to:

* Wrap the spec & support file, so code can be injected into them
  * This will also allow passing in information about the spec (i.e. its file path) that's otherwise inaccessible
* Define the `cy` object in the spec file and proxy it up to the top frame. Stack traces can be captured within the spec frame and then passed up into the top frame

**Comment by jennifer-shehane** [comment]
@chrisbreiding 	Is this related to this issue? https://github.com/cypress-io/cypress/issues/881

**Comment by chrisbreiding** [comment]
#881 is more related to #3966. This issue is tracking a blocker for that.

I thought this work would be somewhat involved and necessitate some structural changes, so I created this issue. However, it currently seems that it won't end up being significant enough for its own issue, so I'll probably close this issue and the work will just done as a part of #3966.

**Comment by chrisbreiding** [comment]
Closing because this ended up not being enough work to require its own issue and PR outside of #3966.
