### ISSUE TITLE
random trigger mouseover

### ISSUE THREAD

**Issue by dimitriylol** [cypress-io/cypress#4936]
### Current behavior:

Launching tests in a container from cypress/browsers:node10.11.0-chrome75 image produces triggering mouseover event occasionally. 

### Desired behavior:

Trigger mouseover event only manually.

### Steps to reproduce: (app code and test code)

I created a small repo to reproduce the behaviour. It renders 4 buttons with a tooltip. Cypress test use cypress-image-snapshot for visual regression. 

Execute the following in the first terminal:
```bash
git clone https://github.com/dimitriylol/cypress-random-bug.git
cd cypress-random-bug
docker pull cypress/browsers:node10.11.0-chrome75
docker run -d -ti --name cypress-bug-example -v "`pwd`":/home/work cypress/browsers:node10.11.0-chrome75
docker exec -ti cypress-bug-example bash
cd /home/work/
npm install
npm start
```
Open the second terminal:
```bash
docker exec -ti cypress-bug-example bash
cd /home/work/
(i=0 ; while npm run cypress:run; do echo "~~~~~~~~~~~~~~success $i"; ((++i)); done)
```
After random amount of ~~~~~~~~~~~~~~success messages, there must be a visual regression. Sometimes it fails even at the first launch. Diff shows triggering mouseover event on one of buttons, e.g. tooltip appears. Diff can be found at "cypress/snapshots/buttons.spec.js/__diff_output__/just\ check\ buttons\ --\ render\ buttons.diff.png". 
Please don't forget to execute ```sudo chown -R `whoami` ``` in cypress-random-bug folder to avoid permission issues.

**Important note**: I can't reproduce such behaviour on my local machine with the same cypress, chrome, node, npm versions.

### Versions

cypress: 3.4.1
browser and OS from cypress/browsers:node10.11.0-chrome75 image.

**Comment by dimitriylol** [comment]
@Bkucera if you can point a module which is responsible for mouse events in cypress driver for chrome, I'd try to debug on my own. Unfortunately, I have no idea where to look for.

**Comment by Bkucera** [comment]
@dimitriylol the mouseover is definitely not coming from cypress code. I'm not sure how cursors work in xvfb, but that could be the issue here.

**Comment by Bkucera** [comment]
Ok, I've confirmed that the Xvfb cursor defaults to position `[640, 512]`, which when adjusted for vertical space taken up by chrome window bars, matches the location of the event in your code.

I'll open up a more specific issue about dealing with the Xvfb cursor

**Comment by jennifer-shehane** [comment]
@Bkucera @dimitriylol I'm going to close this issue. To track it further follow the Xvfb issue opened here: https://github.com/cypress-io/cypress/issues/4936
