### ISSUE TITLE
cypress run --record should print the URL to the cypress.io dashboard

### ISSUE THREAD

**Issue by arthens** [cypress-io/cypress#494]
### Are you requesting a feature or reporting a bug?

Feature request.

### Current behavior:

Running `cypress run --record ...` does not print the URL of the report it created in the cypress.io dashboard.

### Expected behavior:

Running `cypress run --record ...` should print the URL of the report it created in the cypress.io dashboard. (`https://dashboard.cypress.io/#/projects/.../run/....`)

### Additional Info

This feature would be very useful when working in large teams. Right now you have to check all recent reports until you find your own.

**Comment by cameronc56** [comment]
Would love this so i could post a direct URL to the dashboard run in hipchat/slack/etc. ex: 
`FooBar test complete, 37/40 tests passed in 100 seconds. [View Report](direct-url-to-dashboard-run)`

**Comment by jennifer-shehane** [comment]
@cameronc56 We're also working on integration with services like these if you have any feedback for that issues: https://github.com/cypress-io/cypress/issues/981

**Comment by arthens** [comment]
Brilliant, thank you!

**Comment by Enriquecava** [comment]
@brian-mann is there any option to get this dashboard URL from inside the test?

**Comment by rojalbati-cf** [comment]
> @brian-mann is there any option to get this dashboard URL from inside the test?

Same question
