### ISSUE TITLE
The item selector is not working, _cypress/runner/cypress_selector_playground.css Not Found

### ISSUE THREAD

**Issue by joselada** [cypress-io/cypress#4941]
### Current behavior:

![image](https://user-images.githubusercontent.com/44770347/62610756-8ee6aa00-b904-11e9-981c-cdec01977c90.png)

### Desired behavior:

The element selector is not working, it does not shade the selected area worsening the precision of elements

### Versions

Cypress 3.4.1, win 10, Chrome

**Comment by chrisbreiding** [comment]
Duplicate of #4872
