### ISSUE TITLE
[Dashboard] Bug: GitHub integration registration not working

### ISSUE THREAD

**Issue by srilq** [cypress-io/cypress#4955]
### Current behavior:

1. Click `Install the Cypress GitHub App`

<img width="1248" alt="Screenshot 2019-08-08 at 13 44 54" src="https://user-images.githubusercontent.com/18026180/62705089-aac17d00-b9e4-11e9-8d54-0964b2c2153f.png">

2. Navigate to repository for the project

<img width="558" alt="Screenshot 2019-08-08 at 13 59 43" src="https://user-images.githubusercontent.com/18026180/62705252-ef4d1880-b9e4-11e9-8c1c-f8c2ed1058d9.png">

3. Click `Update Access`

<img width="660" alt="Screenshot 2019-08-08 at 14 00 39" src="https://user-images.githubusercontent.com/18026180/62705290-0429ac00-b9e5-11e9-86fe-aeb64a1a8140.png">

4. Go back to step 1 and repeat

### Desired behavior:

After step 3:
* The greyed out area should be accessible, and the GitHub integration should work

OR

* An error message should be displayed saying what went wrong

### Versions

Google Chrome 76
macOS Mojave

**Comment by GuessWhoSamFoo** [comment]
I am running into a similar problem as well. My workflow involves approval from a github org admin. After it was approved, the integration still did not update despite trying to hit the integrate button again then updating the repository settings.

**Comment by desfero** [comment]
The same problem with Github Integration, after org admin approval it still says `Install The Cypress Github app`

**Comment by srilq** [comment]
Quote from cypress support team regarding our issue (in case this helps others encountering the problem):

> I've looked into this and think I see what's going on. There are two organizations in Cypress, and that appears to be the source of the issue here:
> 
> * The [A] organization is your official, subscribed organization. It is not currently integrated with GitHub.
> * The [B] organization is a new organization that was created separately while attempting to get the GitHub integration working. There is a successful integration in that organization, but it looks like we didn't keep the GitHub Integration project settings in-tact while the relevant project was transferred between the two organizations.
> 
> I've retargeted the GitHub App installation into your paid organization, and that appears to have resolved the issue.

**Comment by jennifer-shehane** [comment]
I will be closing this issue as resolved. Please email us as support@cypress.io if the duplicate organization issue (as @srilq explained) seems to be affecting your organization.

**Comment by srilq** [comment]
@jennifer-shehane 
I would also suggest adding better error handling here so some kind of relevant error message appears upon failure.
