### ISSUE TITLE
Need a help: mochaawsome with code coverage nyc example.

### ISSUE THREAD

**Issue by 2manoj1** [cypress-io/cypress#4957]

**Comment by mpahuja** [comment]
Can you please provide more details about the issue being encountered?

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
