### ISSUE TITLE
Cypress Runner could not load Jira page after logged in

### ISSUE THREAD

**Issue by trongbui** [cypress-io/cypress#4960]
Try to login Jira (cloud) with cypress

### Current behavior:
After input logged in information from id.atlassian.com page, Cypress Runner could not load the Jira Dashboard page.
### Steps to reproduce: (app code and test code)
   cy.visit('https://tbui.atlassian.net');
    cy.get('#username').should('be.visible').type(username);
    cy.contains('Continue').click();
    cy.contains(username).should('be.visible');
    cy.get('#password').should('be.visible').type(password);
    cy.contains('button', 'Log in').click();
### Versions
OS: mac 10.14.6
Cypress:  "^3.4.1"

**Comment by Lakitna** [comment]
I do not know the url to Jira but I think it's related to this https://docs.cypress.io/guides/references/trade-offs.html#Same-origin

See https://docs.cypress.io/examples/examples/recipes.html#Logging-In for workarounds

**Comment by trongbui** [comment]
Thank you so much.

**Comment by galczo5** [comment]
@trongbui Hi, did you find a good solution for the Jira login problem?
