### ISSUE TITLE
Support ansi color parsing in command log API

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress#4965]
Currently, we only support rendering markdown using `Cypress.log` (and cy.log by extension).

It would be nice to support ansi coloring which could allow for much richer logging for messages and plugins, **while still allowing compatibility between command log, browser console, and node console**

This would allow users to use something like `chalk` to create colored custom logs via `Cypress.log` or `cy.log` that will render everywhere.

It would solve #2134 which is asking for color support.

### Example use cases:

- diffing results (related to #3130): show a rich inline diff when asserting on strings, or objects
![image](https://user-images.githubusercontent.com/14625260/62805490-25aa9680-babe-11e9-8092-dd60f475bd73.png)

### Related
cy.log color support #2134
Cypress.log.groupEnd support https://github.com/cypress-io/cypress/issues/3229

**Comment by jennifer-shehane** [comment]
Closing due to there not being a lot of interest in this feature.
