### ISSUE TITLE
Support index.js is not evaluated before cypress run command

### ISSUE THREAD

**Issue by RichieRunner** [cypress-io/cypress#4975]
### Current behavior:
Per the [documentation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Support-file), the support file "runs before every single spec file". However, that is not the case for my scenario.

### Steps to reproduce: (app code and test code)
In my `support/index.js` file, I have the following: 

```Javascript
`support/index.js`
beforeEach(function() {
  console.log('cypress support index: process.env.CONFIG', process.env.CONFIG);
  const config = process.env.CONFIG || 'nonprod';

  if (config == 'nonprod') {
    Cypress.config('baseUrl', Cypress.env('nonprod_baseUrl'));
  } else if (config == 'prod') {
    Cypress.config('baseUrl', Cypress.env('prod_baseUrl'));
  }
});
```
```Javascript
`cypress/json`
{
  "baseUrl": "http://localhost:8000",
  "env": {
    "local_baseUrl": "http://localhost:8000",
    "nonprod_baseUrl": "myUrl",
    "prod_baseUrl": "myUrl"
  },
  "integrationFolder": "./cypress/integration/FunctionalityTests",
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "cypress/test-results/Cypress-Test-Results.xml",
    "toConsole": false
  },
  "suportFile": "./cypress/support/index.js",
  "video": false
}

```
When running locally, I set config with:
`SET config='nonprod`
Then I run `cypress run`, and I don't see see my console.log, as well I do not see my `baseUrl` being changed.

Is support index.js not running before every test file as indicated? If not, how should I build this logic to change my `baseUrl` before `cypress run`?

### Versions

"cypress": "^3.4.1"

**Comment by jennifer-shehane** [comment]
Where are you looking for this `console.log` messaging? This will only log to the Chrome console, so would not be viewable during `cypress run` unless you're using an associated plugin that logs console logs to your standard out in the terminal. 

Printing the logs, I can see that it does print a lot before every single spec file as noted in the documentation.

The problem here is in trying to set the `baseUrl` at this stage - in the `support/index.js` file. At this point the browser has already launched and the `baseUrl` is readonly. You will need to set the `baseUrl` at an earlier stage of running the Cypress tests.

**Comment by bahmutov** [comment]
Yup, @jennifer-shehane is right - inside `support/index.js` it is too late to change the base url. But it is easy to change it via CLI argument or via environment variables, see this blog post for example https://www.cypress.io/blog/2017/05/30/cypress-and-immutable-deploys/ that tests same app before and after deploy

**Comment by sagorla** [comment]
@RichieRunner 
I am able to change baseUrl with the following function, you need to include in Plugins/Index.js

please refer below cypress document how plugins work in cypress https://docs.cypress.io/guides/tooling/plugins-guide.html#Use-Cases

And also create another folder called "config" in your repository, under config create another file called "nonprod.json" & "prod.json". In these files maintain your baseUrl.

When you run cypress, you need to pass the env name through the command line as below
npx cypress open --env name=prod
npx cypress run --env name=prod

if you run cypress without passing --env name it will execute with baseUrl which is specified in Cypress.json

**Plugins/Index.js:**

const fs = require('fs-extra')
const path = require('path')

module.exports = (on, config) => {
    function getConfigByEnvName(config) {
        if (config.env.name) {
            const file = config.env.name
            const pathToConfigFile = path.resolve('config', `${file}.json`)
            return fs.readJson(pathToConfigFile)
        }
    }
    return getConfigByEnvName(config);
}
