### ISSUE TITLE
Full path to failed specfile is not viewable from stdout

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#4977]
### Current behavior:

The specfiles are truncated in the stdout results of a run, making it difficult for users to track down which test file results they are looking at. 

<img width="833" alt="Screen Shot 2019-08-13 at 4 20 09 PM" src="https://user-images.githubusercontent.com/1271364/62926080-55bba780-bde6-11e9-866e-e40db73b380a.png">

### Desired behavior:

Some suggestions

- Make this configurable somehow
- Have a better way to display the full specfile name (maybe return the line to print the entire length)

### Versions

Cypress 3.4.1

**Comment by Hydrock** [comment]
Please do that. I want to format the output to the console myself.

**Comment by bahmutov** [comment]
I wonder if we could get away with the following (simple) solution:
if the filepath is longer than let's say 20 characters, print it by itself on the first line and then print the rest of the stats on the second line for each spec.

By the way, this reporting is done not in the CLI NPM module but in `packages/server` in file "packages/server/lib/modes/run.coffee"

**Comment by elena258** [comment]
Hey team! We need it badly... lets make it happen! :)
