### ISSUE TITLE
cy.task unexpectedly converts Dates to Strings

### ISSUE THREAD

**Issue by philjones88** [cypress-io/cypress#4980]
### Current behavior:

If I create a task like:

(TS, we transpile to JS for Cypress)
```ts
const generateCMLicenseHandler = (args: any) => {
  logger.log('args: ' + JSON.stringify(args));
  const { mode, name, validUntil, evaluation }: { mode: AnalyticsMode, name: string, validUntil: Date, evaluation: boolean } = args;
  logger.log(`generating license: mode: ${mode}, name: ${name}, valid until: ${validUntil} (${typeof validUntil}), eval: ${evaluation} (${typeof evaluation})`);
  return new LicenseGenerator().generate(mode, name, validUntil, evaluation);
};

module.exports = {
  'cm:generate-license': generateCMLicenseHandler
};
```

And call it like:

```ts
Cypress.Commands.add('uploadLicense', { prevSubject: true }, (subject, mode: AnalyticsMode, name: string, validUntil: Date, evaluation: boolean) => {
  if (!subject) {
    throw new Error('uploadLicense must be chained off your upload target!');
  }

  return cy.task('cm:generate-license', { mode, name, validUntil, evaluation })
    .then((result: string) => cy.upload(
      [{
        fileContent: result,
        fileName: 'license.lic',
        mimeType: 'text/plain',
        encoding: 'utf-8'
      }],
      {
        force: true,
        subjectType: 'drag-n-drop'
      })
  );
});
```

In Spec
```ts
    licenseModal
      .uploadZone()
      .uploadLicense('Full', 'Cypress Testing Ltd', new Date(new Date().getFullYear() + 5, 0, 1, 0, 0, 0, 0), false);
```

I see this as the args object logged:

```
args: {"mode":"Full","name":"Cypress Testing Ltd","validUntil":"2024-01-01T00:00:00.000Z","evaluation":false}
generating license: mode: Full, name: Cypress Testing Ltd, valid until: 2024-01-01T00:00:00.000Z (string), eval: false (boolean)
```

### Desired behavior:

The documentation at:

https://docs.cypress.io/api/commands/task.html#Arguments

Implies it should be serialised and deserialised correctly.

See code above

### Versions

Cypress 3.4.1
MacOS Mojava latest

**Comment by philjones88** [comment]
It makes a bit more sense now, you guys use JSON.stringify() then JSON.parse().

So say this example, you do end up with a string date:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/677167/63008746-1f7c3780-be7b-11e9-9e0f-2d919859d6e7.png">

Something to consider:

https://stackoverflow.com/questions/4511705/how-to-parse-json-to-receive-a-date-object-in-javascript/14509447#14509447

**Comment by jennifer-shehane** [comment]
Hey @philjones88 Could you explain the desired behavior you'd like to see from Cypress here? 

What exactly you would like to send to `cy.task()` and what exactly the args should evaluate as within `cy.task()`?

What are you trying to achieve at the end of this that you are not currently capable of doing from Cypress?

**Comment by philjones88** [comment]
Desired behavior:

Passing a Date object to a task as an argument that stays a Date object

Actual behavior:

It passes it as a string.

**Comment by bahmutov** [comment]
since we use JSON to shuffle objects around, if it is a Date string, we have no way of knowing it after conversion. I really would not want to create our own serialization protocol to pass things like "this field is a Date" in addition to JSON serialization. I think it is up to the `task` code to convert ISO date string if it needs back the Date instance

**Comment by philjones88** [comment]
@bahmutov I think that is ok but the documentation could be expanded to clarify how you do this internally. I expected Date to work reading what the documentation said wouldn't work (functions/etc being set to null).
I did link to how to parson JSON with dates using the reviver option in JSON.parse. You wouldn't need to design a custom serialization protocol using a reviver to detect Date objects.

**Comment by levz0r** [comment]
Hi,

I am the author of [gmail-tester](https://github.com/levz0r/gmail-tester), which allows searching Gmail-powered inboxes in code. One of the main use-cases of the library is e2e testing of a user registration flow, where a new user registers and receives an email with a confirmation link. The library allows asserting that the email was received and so on...
One of the library's features is filtering messages in specific dates ranges:

```
const tester = require("./gmail-tester");

(async () => {
  const messages = await tester.get_messages("credentials.json", "token.json", {
    include_body: true,
    before: new Date(2019, 1, 1), // before February 1st
    after: new Date(2019, 0, 1) // after January 1st
  });
})();
```
To be able to call the libary using cypress, a task was defined:
```
on("task", {
    "gmail:get-messages": async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json"),
        args.options
      );
      return messages;
    }
  });
```
Then called from a `spec` file, like so:
```
describe("Email assertion:", () => {
  it("Look for an email with specific subject and link in email body", function() {
    // debugger; //Uncomment for debugger to work...
    cy.task("gmail:get-messages", {
      options: {
        from: "AccountSupport@ubi.com",
        subject: "Ubisoft Password Change Request",
        include_body: true,
        before: new Date(2019, 8, 24, 12, 31, 13), // Before September 24rd, 2019 12:31:13
        after: new Date(2019, 7, 23) // After August 23, 2019
      }
    }).then(emails => {
      assert.isAtLeast(
        emails.length,
        1,
        "Expected to find at least one email, but none were found!"
      );
      const body = emails[0].body.html;
      assert.isTrue(
        body.indexOf(
          "https://account-uplay.ubi.com/en-GB/action/change-password?genomeid="
        ) >= 0,
        "Found reset link!"
      );
    });
  });
});
```
Unfortunately, as reported above, both `before` and `after` Dates are stringified and break the library functionalities. I can locally patch this behavior by converting the stringified values back to Dates, but it happens only when integrated with cypress, so I don't think this is the correct way...

I can help to reproduce the issue.

Thanks

**Comment by levz0r** [comment]
Hi,
It's been a while since this issue was raised... Any updates please?
@jennifer-shehane if you need help recreating, I can help.
Thanks

**Comment by jennifer-shehane** [comment]
Simplified reproducible example:

`plugins/index.js`

```js
module.exports = (on) => {
  on('task', {
    'sendDate': args => {
      return args;
    }
  });
};
```

`spec.js`

```js
it('test', () => {
  const date = new Date(2019, 7, 23)
  // passes, it's a Date!
  expect(Cypress._.isDate(date)).to.be.true

  cy.task("sendDate", {
    date: new Date(2019, 7, 23)
  }).then((opts) => {
    expect(opts.date).to.eq("2019-08-22T17:30:00.000Z")
    // fails, it's no longer a Date but a String
    expect(Cypress._.isDate(opts.date)).to.be.true
  })
})
```

<img width="561" alt="Screen Shot 2020-05-05 at 4 53 59 PM" src="https://user-images.githubusercontent.com/1271364/81056738-09267800-8ef1-11ea-9a41-5b28684caf36.png">

**Comment by TomaszG** [comment]
Any updates for this? The clean way of fixing it would be to add an option to pass custom JSON serializer to the task() command which then can be used to create a custom Date serializer, as described below:

https://weblog.west-wind.com/posts/2014/jan/06/javascript-json-date-parsing-and-real-dates

**Comment by prescottprue** [comment]
+1 for the custom JSON serializer

**Comment by sainthkh** [comment]
@TomaszG @prescottprue 

Internally, Cypress uses [`child_process.fork()`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) to create a child process and runs the command inside it.

By default, `child_process` uses json as serializer. And it doesn't provide custom serializer. Because of that, supporting custom serializer is impossible now.
