### ISSUE TITLE
Can't chain mutliple `cy.should(callbackFn)`

### ISSUE THREAD

**Issue by garretmh** [cypress-io/cypress#4981]
### Current behavior:

Chaining multiple `.should()` commands that use callback functions throws if any of the callback functions other than the last one contain more than one assertion.

```js
cy.wrap('ab')
  .should(subject => {
    expect(subject).to.be.a('string');
    expect(subject).to.contain('a');
  })
  .should(subject => {
    expect(subject).to.contain('b');
  });
```

![Screenshot from 2019-08-13 16-01-21](https://user-images.githubusercontent.com/1526013/62977068-a41b7700-bde3-11e9-9b1d-5f677ec88f99.png)

### Desired behavior:

Chaining multiple `.should()` commands should work regardless of the number of assertions per callback function.

### Steps to reproduce: (app code and test code)

```js
describe('chaining cy.should(callbackFn)', () => {
  it('should work, but does not', () => {
    cy.wrap('a')
      .should(subject => {
        expect(subject).to.be.a('string');
        expect(subject).to.contain('a');
      })
      .should(() => {});
  });

  it('works when separated by .then()', () => {
    cy.wrap('a')
      .should(subject => {
        expect(subject).to.be.a('string');
        expect(subject).to.contain('a');
      })
      // Adding an empty then fixes the issue.
      .then(() => {})
      .should(() => {});
  });

  it('works when there is only one assertion per callbackFn', () => {
    cy.wrap('a')
      .should(subject => {
        expect(subject).to.be.a('string');
      })
      .should(subject => {
        expect(subject).to.contain('a');
      })
      .should(() => {});
  });
});
```

### Versions

Cypress: 3.4.5
OS: Ubuntu 19.04
Browser: Electron 61

**Comment by mpahuja** [comment]
these are two different assertion libraries. Whats the motivation behind trying to use both at the same time?

**Comment by jennifer-shehane** [comment]
Simpler example from https://github.com/cypress-io/cypress/issues/5979

```js
it('two should callbacks (crashes and burns)', () => {
  cy.wrap(null)
    .should(() => {
      console.log('in should()')
      expect(true).to.be.true
      expect(true).to.be.true
    })
    .and(() => {
      console.log('in and ()')
    })
})
```

**Comment by bahmutov** [comment]
Relevant stack 
<img width="1281" alt="Screen Shot 2019-12-16 at 9 30 38 PM" src="https://user-images.githubusercontent.com/2212006/70999051-a568f300-20a6-11ea-8a8a-47adcd2f1368.png">
