### ISSUE TITLE
cy.click() should allow for more position arguments

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#499]
**Current Behavior**
Currently, `cy.click()` only accepts 5 position arguments: `center`, `topLeft`, `topRight`, `bottomLeft`, `bottomRight`.

**Expected Behavior**
Update `cy.click()` command to accept 9 position arguments: `topLeft`, `top`, `topRight`, `left`, `center`, `right`, `bottomLeft`, `bottom`, and `bottomRight`. This will match the behavior of the upcoming `cy.scrollTo()` command's position arguments - #497

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
