### ISSUE TITLE
cy.get/find(...) finding more than one item does not filter with .should('have.text','...')

### ISSUE THREAD

**Issue by travis-flint** [cypress-io/cypress#4991]
### Current behavior:
When a display has multiple elements of the same type (say buttons for this example) and the difference is the text, using the call:
```
cy.get('button')
   .should('have.text','New');
```
Will compare the a string containing all the found buttons' text to 'New'.

### Desired behavior:

When a display has multiple elements of the same type (say buttons for this example) and the difference is the text, using the call:
```
cy.get('button')
   .should('have.text','New');
```
This should filter the list of buttons by eliminating all the buttons that do not have the text 'New'
### Steps to reproduce: (app code and test code)

Start with a webpage that has multiple buttons inside of a div, or any other element.
Each button has its own name ("New", "New Project", "Save").
In the cypress code have:
`
cy.get('div')
   .find('button')
   .should('have.text','New');
`
When this is run.. it will fail, because it will compare 'NewNew ProjectSave' to 'New'.

### Versions

Cypress 2.4.1
Windows 10
Chrome 76

**Comment by Lakitna** [comment]
This is intentional and I don't think it should be changed. The rules of `.should()` state that it will always yield it's exact input.

In your situation, I would use `.filter()` like this:

```javascript
cy.get('get')
  .find('button')
  .filter((button) => {
    // Remove all buttons that do not have the exact text 'New'
    return button.text() === 'New';
  })
  // Make sure we have at least one button that has the text 'New'
  .its('length')
  .should('be.above, 0);
```

**Comment by dannynicolas** [comment]
Another way to do this is: 

`cy.get("button:contains('New')")`

**Comment by sainthkh** [comment]
@Lakitna is right. It's intended feature. `should` is for assertion, not filtering. It's the job of `filter`. Close this issue.
