### ISSUE TITLE
Can't open Cypress on Ubuntu 18.04

### ISSUE THREAD

**Issue by gracesianturi** [cypress-io/cypress#4992]
Hello, I have installed new version Cypress on Ubuntu 18. But I can't open the Cypress app.

### Steps to reproduce: (app code and test code)
1. Install nodejs
2. Install npm
3. Install cypress : npm install cypress --save-dev
4. Run cypress : cypress run

Error : 
![Screenshot from 2019-08-16 13-48-29](https://user-images.githubusercontent.com/29389000/63148829-9573d080-c02c-11e9-939f-d958208e7ae0.png)

Is there anything that i can do with this?
I already installed the dependencies, but it still error.

### Versions
Cypress Version : 3.4.1
OS : Ubuntu 18.04.3
Browser : Chrome

**Comment by Lakitna** [comment]
Looks like you're missing libgconf-2-4. This is a known thing when using CI https://docs.cypress.io/guides/guides/continuous-integration.html#Travis

You should be able to get away with simply running `apt-get libgconf2-4` first

**Comment by gracesianturi** [comment]
Thank you so much @Lakitna  I will run apt-get libgcinf2-4.
