### ISSUE TITLE
How to pull some data in cypres? 

### ISSUE THREAD

**Issue by dispssins** [cypress-io/cypress#4993]
i wanna testing with doing update in a set of data like a picture bellow. 
in this update, I want to do an assertion after I press the save button. 
Before I press the button, there are several fields that I replace with new data like phone number from 44555667788 to 02199299 and some fields some I don't replace at all or skip. 

according to my supervisor's explanation, that if I want to do an assertion
1. I have to open this menu in the written image EDIT CLIENT 
2. before I do the update / edit, I'm not sure about the previous data in EDIT CLIENT and 
    if I want to know for sure, I have to open it
3. according to my supervisor, before i click the save button, **i must pull of data in EDIT CLIENT  
   and make data be a json** and the json that I will use to do an assert on the field that I skip after i 
  click the save button. 

![image](https://user-images.githubusercontent.com/44185191/63148853-a6244680-c02c-11e9-8d81-3419f19ed9ba.png)

**Comment by Lakitna** [comment]
Like with any tests, you basically have three main steps:

1. Arrange - Setup the situation (open screen, alter data)
2. Act - Make the application do a thing (click save)
3. Assert - Make sure the application did the right thing (did it save?)

The first two steps require a bit of time to get the correct commands and selectors in place, but that should not be too difficult.

The last step requires you to know two things:

1. What did I intend the outcome to be (
2. What is the actual outcome

JSON could be a way to structure these.

I suggest you try to tackle these steps one at a time. If you're running into specific issues try the Gitter chat so the issue log remains clean :)
