### ISSUE TITLE
Canary crashes when attempting opening developers tools

### ISSUE THREAD

**Issue by dkouvdis** [cypress-io/cypress#4995]
### Current behaviour:
Canary browser is crashing when trying opening developers tools

### Desired behaviour:
Shall not crash/close the browser

> Electron and Chrome is ok

### Steps to reproduce:
When the Canary head mode is open, two ways to reproduce it
- (right-click, select inspect)
- cmd+alt+J

### Versions

Cypress: 3.4.1
Canary: 78

**Comment by gfviegas** [comment]
I'm also experiencing this issue with Google Chrome Version 78.0.3880.4 (Official Build) dev (64-bit) on Mac (macOS High Sierra v 10.13.6).

I've tried to restart Cypress a couple of times but i've had no luck.

**Comment by sainthkh** [comment]
The time has passed and I hope the problem has been solved with Cypress 6.2.0. Sometimes, Cypress won't work as expected because of some bugs in the canary versions. If the problem is still happening, please open a new issue with a reproducible example.
