### ISSUE TITLE
Proposed tsconfig.json fails in latest vscode

### ISSUE THREAD

**Issue by SteveALee** [cypress-io/cypress#4996]
### Current behavior:

Using the [recommend tsconfig.json](https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Reference-type-declarations-via-tsconfig) and latest vs code the intellisense is not working and I get errors for my spec files

![image](https://user-images.githubusercontent.com/618922/63186129-92d8a180-c053-11e9-97dc-38ab6bc0fbdc.png)

The solution is to add an `outDir` setting. eg
```
"outDir": "./out"
```

I've not idea why as code should not actually be creating any output files for intellisense and the out folder is not created.

Possibly a vs code bug?

### Desired behavior:

The tsconfig you supply should just work

### Steps to reproduce: (app code and test code)

* Clone https://github.com/LearnHyperapp/hyperapp-cypress-demo
* Update all deps and install
* Open a test file in VS code 
* look for intellisense - and check output for the errors

### Versions

Windows 10 latest
code 1.37.1
cypress 3.4.1

**Comment by Lakitna** [comment]
When there is a `tsconfig.json` VS code will assume that it is there because it's a Typescript project. In such a project an output directory is needed to prevent overwriting the js source files with the compiled versions.

You can safely ignore this error message when using Cypress with js.

**Comment by SteveALee** [comment]
@Lakitna thanks While I appreciate your thinking having zero TS files is perfectly possible with allowJS/ 

Now I think about it more I realise the compiler will possibly write the output as it might be transpiling depending on other options. However in this case the outDir is never created. Seems like a little weirdness in TSC error reporting.

I have a policy of 0 errors, largely as once you accept a few 1) important errors get lost in the noise and 2) it's a start of sloppy habits IMHO.

Ideally the example config for cypress would not cause any errors.

**Comment by SteveALee** [comment]
Perhaps `--noEmit` would be better as long as the intellisense gets created for vscode

**Comment by nerjamartin** [comment]
Hi!
I fix that putting the "tsconfig.json" file in a separate "/lib" folder.
Hope that's works for you too

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
