### ISSUE TITLE
cy.type(...) to type global shortcut on <body> element too restrictive

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress#4997]
### Current behavior:

`cy.type(...)` can be used on global shortcuts. We can type into the `<body>`.  This use of `cy.type(...)` is well documented:

https://on.cypress.io/type#Global-Shortcuts
https://on.cypress.io/type#Supported-Elements

However, the shortcuts may not be attached on the `<body>` element. In my case, the key events associated with the shortcuts are not attached to a `<body>`. Instead, they are attached to a particular `<div>`.  Fortunately, this particular `<div>` has a `tabindex` attribute/`contenteditable` attribute that allows me to enter a shortcut using `cy.type(...)` as a workaround.  Some other Cypress developers may not be this lucky.

### Desired behavior:

Remove or relax the restrictions on the elements that accept shortcut keys.

### Steps to reproduce: (app code and test code)

```js
cy.get("html").type("b")
```

### Versions

Cypress 3.4.1
Ubuntu 16.04 LTS
Chrome 76 and 78 (google-chrome-unstable)

**Comment by clarmso** [comment]
If my description sounds like #4953, please feel free to close this issue. :)

**Comment by eps1lon** [comment]
> If my description sounds like #4953, please feel free to close this issue. :)

Looking at the code and [documentation](https://docs.cypress.io/api/commands/type.html#Global-Shortcuts) it looks like you should be able to `cy.get('body').type("b")`.  

Looking at the spec `type` should be able to target `html` elements if `document.activeElement` and `document.body` is not available. In general I would prefer a type command that is not chainable from an element but lets cypress detect where the keydown event should be dispatched to since that's how the UIEvents spec defines it.

> The event target of a key event is the currently focused element which is processing the keyboard activity. This is often an HTML input element or a textual element which is editable, but MAY be an element defined by the host language to accept keyboard input for non-text purposes, such as the activation of an accelerator key or trigger of some other behavior. If no suitable element is in focus, the event target will be the HTML body element if available, otherwise the root element.

-- https://w3c.github.io/uievents/#events-keyboard-event-order

**Comment by clarmso** [comment]
I've tried `cy.get('body').type("b")`, too. For some reason, I need to type to the `<div>` element. Let me try to come up with a small example.

**Comment by Bkucera** [comment]
@clarmso  @eps1lon this is why we support `cy.focused().type(...)`, if you just want to send keys to the activeElement. this mimicks what happens if the user just presses the keys at that moment in the test

**Comment by eps1lon** [comment]
> this is why we support cy.focused().type(...), if you just want to send keys to the activeElement. this mimicks what happens if the user just presses the keys at that moment in the test

@Bkucera  Could you please take a look at https://github.com/cypress-io/cypress/pull/4953 then? It includes a testcase where `cy.focused().type()` is rejected without changing the implementation.

The documentation also does not indicate you support type on focused elements. Only on elements matching a specific heurstic. There is no mention of the focus state only focus-ability.

**Comment by Bkucera** [comment]
@eps1lon yes, there is a PR open for that exact change, but I apologize it wasn't clearly tagged as fixing that issue #4870
