### ISSUE TITLE
allow for aliasing of things beside DOM elements

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#5]
I'd like to be able to alias things other than DOM elements, for example a url string of a request. example:
          
```js
describe "asset search", ->
  beforeEach ->
   cy
     .route(/assets/, {}).as("getAssets")
     .get("form").submit()
     .wait("@getAssets").its("url").as("requestUrl")

   it "does not search areaId", ->
     cy.get("@requestUrl").should("not.match", /areaId/)

   it "does not search locationId", ->
     cy.get("@requestUrl").should("not.match", /locationId/)
```

This currently just says `Syntax error, unrecognized expression: @requestUrl`

**Comment by brandon-beacher** [comment]
Would `assign` work for this?

**Comment by jennifer-mann** [comment]
Yes, `.assign()` would work for this. Wanted @brian-mann to just look over to decide if `.as()` should be extended to accommodate for this or not.

**Comment by brian-mann** [comment]
Yah that's what I talked to Jennifer about when she brought up this issue.  Should I extend `cy.get` to alias any object or primitive, or only allow it as glue between command relationships.  I'm not sure yet.  This is the use case I imagined for `cy.assign`.

There are still advantages to `cy.assign` but you would see its usefulness go down by extending `cy.get`.   This biggest disadvantage of `cy.assign` is that its difficult to get this into a cy chain.  However the `cy.wrap` command is coming soon which takes any existing value and allows you to chain off of it.  

I don't know yet I'll keep coming up with examples and make a decision after I see more situations.

**Comment by brian-mann** [comment]
This has been implementing in [`0.5.8`](https://github.com/cypress-io/cypress/wiki/Changelog#058-04242015).

`cy.assign` has been removed, and has been folded into `cy.as`.

In other words, `cy.as` does what `cy.assign` did automatically now.
