### ISSUE TITLE
Specifying coordinates for a click event on DOM elements

### ISSUE THREAD

**Issue by seltar** [cypress-io/cypress#50]
Is it possible to add the option to specify coordinates for a click event on certain types of DOM elements, like canvas?

For example
`cy.get("canvas").click(50, 200);`
would trigger a click event 50px from the left and 200px from the top of the specified canvas element.

**Comment by brian-mann** [comment]
Yes, will be done within the next 1-3 patch releases.

**Comment by brian-mann** [comment]
Added in [`0.9.3`](https://github.com/cypress-io/cypress/wiki/Changelog#093-07062015).
