### ISSUE TITLE
Cypress GUI needs to be updated to account for cypress being installed per project as npm module

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#500]
- [ ]  No global projects list
- [ ] No add project GUI
- [ ] Project show needs "title" instead of "Back to Projects" button
- [ ] Display full absolute path to project as window title

**Comment by chrisbreiding** [comment]
If launched globally:
- show message about how to properly launch, link to docs
- allow dragging or selecting project to use
- show list of recent projects
- show 'back' button on project show view

If launched locally:
- go straight to project show view
- replace 'back' button with project name
- show full absolute path to project in window title

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
