### ISSUE TITLE
Selector playground broken in Cypress 3.4.1

### ISSUE THREAD

**Issue by mlienhart** [cypress-io/cypress#5002]
### Current behavior:

![image](https://user-images.githubusercontent.com/33730035/63253074-71ed9780-c271-11e9-85df-40ca955c6b44.png)

### Desired behavior:

If you click any UI element using selector playground, Cypress should select it properly. In version 3.4.0 the selector playground was working fine.

### Steps to reproduce: (app code and test code)

1) Click on any UI element in any App in Cypress
2) Desired element is not properly selected by Cypress (see screenshot)

### Versions

3.4.1, Windows 10, Chrome 76

**Comment by dialex** [comment]
What do you mean by "properly"?
Can you be more precise, ie. describe what you expect as "properly"?

**Comment by mlienhart** [comment]
Hi @dialex,
when you take a look at the picture I have provided, you can see '#hplogo' and a diamond sign right below Google. When you click on any element of the page, the element should be marked & selected with a border (properly) and it should be obvious, which element you have taken. There should be no diamond sign visible and the element should stay marked. Below is another visual example (including link) how it should be.
Thank you very much for your support.

![image](https://user-images.githubusercontent.com/33730035/63264069-78d4d400-c28a-11e9-925c-aaaa8d396f50.png)

https://docs.cypress.io/guides/core-concepts/test-runner.html#Running-Experiments

**Comment by Darrenb7979** [comment]
Opt out of these messages please ó don't want to receive them anymore
Sent from Outlook
________________________________

**Comment by ZiqiWill** [comment]
Dude, same as #4941 and #4872 , and seems it was fixed

**Comment by mlienhart** [comment]
Hi @ZiqiWill,
thank you for your answer.
