### ISSUE TITLE
Feature Request: config to enable/disable screenshots

### ISSUE THREAD

**Issue by dialex** [cypress-io/cypress#5003]
One of the use cases of Cypress is API testing. In that scenario it doesn't bring much value to take screenshots. However there's no way to disable screenshots.

- There is a [config](https://docs.cypress.io/guides/references/configuration.html#Videos) `"video": false` for videos.
- Please add a [config](https://docs.cypress.io/guides/references/configuration.html#Screenshots) `"screenshots": false` for screenshots as well.

**Comment by mpahuja** [comment]
you can set this value `"screenshotOnRunFailure":false` to achieve that. as described here: https://docs.cypress.io/api/cypress-api/screenshot-api.html#Arguments

**Comment by dialex** [comment]
Oh ok, so it's possible to do it, just not intuitive. I would prefer it was a simple config value, together with other configs as for video. The solution you showed forces me to have this config on `support/index.js`.

**Comment by jennifer-shehane** [comment]
Closing as duplicate of https://github.com/cypress-io/cypress/issues/5029
