### ISSUE TITLE
How to verify mouse over text?

### ISSUE THREAD

**Issue by spnmodi** [cypress-io/cypress#5005]
I'm new to cypress and want to verify the below mouse hover text as shown below in the picture. It appears only when the mouse hovers and disappears when clicked on the button. Also, as the button name is 'Left' the text also appears on left, if hover on the button named right, the text appears on the right.
### Current behavior:

<img width="295" alt="Tooltip" src="https://user-images.githubusercontent.com/38531914/63272185-7c208d80-c293-11e9-8187-263c92a4c138.png">

### Desired behavior:

I want to verify the mouse hover text with its position

### Steps to reproduce: (app code and test code)

```js
cy.get('[tooltip-position="3"]').invoke('show')
  .contains('Left').trigger('mouseover','bottom');
```

### Versions

Running on latest cypress on chrome 75

Kindly help me.

**Comment by spnmodi** [comment]
Please somebody kindly help.

**Comment by jennifer-shehane** [comment]
Hey @spnmodi there is not much we could do to help without the accompanying application to run the test code against. Can you provide the app / html, css, javascript to run it on? 

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by spnmodi** [comment]
@jennifer-shehane I may not be able to share the code/Html etc. due to sensitive data. However, I found the solution, as I was triggering on the wrong event listener. It has to be mouseenter instead of mouseover
Right code
cy.get('[your selector]')
        .eq(0).invoke('show')
        .trigger('mouseenter')
        .wait(1000)
        .should('have.attr','your-selector','Active tooltip')
        .trigger('mouseleave');

**Comment by spnmodi** [comment]
@jennifer-shehane Thanks, though to reply. :)

**Comment by jennifer-shehane** [comment]
Closing as resolved.
