### ISSUE TITLE
Is there a way I can block all images requests?

### ISSUE THREAD

**Issue by dkouvdis** [cypress-io/cypress#5006]
In some of our tests, we don't need images. We would like to block it to speed it up

Is there a way we can block all images requests (no images on the page)?

For example, in puppeteer we do this
```
async blockImageRequests() {
    await this.page.setRequestInterception(true)

    this.page.on('request', request => {
      if (request.resourceType() === 'image') request.abort()
      else request.continue()
    })
  }
```

**Comment by mpahuja** [comment]
if the images are coming from a single source then you can probably use this feature: https://docs.cypress.io/guides/references/configuration.html#blacklistHosts

**Comment by dkouvdis** [comment]
Thanks, not sure why I missed this in the docs

**Comment by ghost** [comment]
guys blacklistHosts has been renamed to blockHosts. check out this:
https://docs.cypress.io/guides/references/configuration#blockHosts
