### ISSUE TITLE
cypress_download_mirror in .npmrc gets ignored

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5009]
### Current behavior:
.npmrc:
```
registry = https://...
cypress_download_mirror=https://...
```

```
  cypress:cli installing Cypress from NPM +0ms
  cypress:cli installing with options {"force":true} +0ms
  cypress:cli version in package.json is 3.4.1 +0ms
  cypress:cli Reading binary package.json from: /Users/X/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/package.json +0ms
  cypress:cli installed version is 3.4.1 version needed is 3.4.1 +7ms

Cypress 3.4.1 is installed in /Users/X/Library/Caches/Cypress/3.4.1

  cypress:cli performing force install over existing binary +0ms
  cypress:cli checking local file Master +1ms
  cypress:cli Cypress already installed at /Users/X/Library/Caches/Cypress/3.4.1 +0ms
  cypress:cli but the installation was forced +0ms
  cypress:cli preparing to download and unzip version  3.4.1 to path /Users/X/Library/Caches/Cypress/3.4.1 +0ms
Installing Cypress (version: 3.4.1)

  cypress:cli needed Cypress version: 3.4.1 +0ms
  cypress:cli source url https://download.cypress.io/desktop/3.4.1?platform=darwin&arch=x64 +1ms

```

### Desired behavior:
Reads the config value and use it.

Workaround use an environment variable.

### Steps to reproduce: (app code and test code)

1. add cypress_download_mirror to .npmrc
2. install cypress or start download manually `DEBUG=* node node_modules/cypress/index.js --exec install --force`

### Versions

Cypress 3.4.1
npm 6.4.1
Linux & Mac

**Comment by tomasbjerre** [comment]
You should use upper case:

```bash
registry = https://...
CYPRESS_DOWNLOAD_MIRROR = https://...
```

**Comment by CSchulz** [comment]
I have also tried the upper case variant, it doesn't work for me.

**Comment by tomasbjerre** [comment]
Right, I actually did not try exactly your command. I tried:
```bash
bjerre@bjerre-ubuntu:~/sandbox/cyprsandbox$ cat .npmrc 
CYPRESS_DOWNLOAD_MIRROR = https://asdasdasd.com/hej.zip
bjerre@bjerre-ubuntu:~/sandbox/cyprsandbox$ npm install cypress --save-dev --verbose
...
```

Your command actually also fails for me.

**Comment by tomasbjerre** [comment]
This seems only logical to me. I might be wrong but NPM reads `.npmrc` and Node does not. Because Node has no dependency to NPM, it is the other way around, NPM depends on Node.

So the problem is really that Node is not reading your `.npmrc` and what you would need to do is to set the environment variable yourself.
```bash
CYPRESS_DOWNLOAD_MIRROR=https://asdasdasd.com/asdasd.zip DEBUG=* node node_modules/cypress/index.js --exec install --force
```

**Comment by flotwig** [comment]
Indeed, .npmrc configuration variables are not the same as environment variables. CYPRESS_DOWNLOAD_MIRROR is only supported as an environment variable. This is expected behavior.

**Comment by CSchulz** [comment]
Ups, I was missleaded by https://github.com/cypress-io/cypress/blob/develop/cli/lib/util.js#L326-L347 .
Perhaps it can be removed someday.
