### ISSUE TITLE
take print on error

### ISSUE THREAD

**Issue by yaanr3is** [cypress-io/cypress#5011]
Hello guys, I have a problem that when it is detected the error is not taking print and then an exception is thrown, could you help me?

```js
Cypress.on('fail', function (err, runnable) {
  cy.screenshot('teste')
  throw err
})
```

![image](https://user-images.githubusercontent.com/12881853/63397508-1de1d080-c3a1-11e9-9664-a1e64b822afa.png)

![image](https://user-images.githubusercontent.com/12881853/63397451-f8ed5d80-c3a0-11e9-85d1-5c729ccd4697.png)

Version 3.4.1 | Changelog

**Comment by mpahuja** [comment]
there is a screenshot that is already taken on a failure. Not sure what you are trying to do here but if you need to modify the screenshot then you should probably follow this document: https://docs.cypress.io/api/cypress-api/screenshot-api.html#Syntax

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
