### ISSUE TITLE
"el-checkbox" can't use " cy.check( )"  , can't use " .should('be.checked')  ",how to Assertions ?

### ISSUE THREAD

**Issue by cmhtdv** [cypress-io/cypress#5012]
![image](https://user-images.githubusercontent.com/31730581/63414566-b8d4bc00-c42e-11e9-8094-f0ed24a675a5.png)
![image](https://user-images.githubusercontent.com/31730581/63415004-968f6e00-c42f-11e9-9af7-104fba235fff.png)
![image](https://user-images.githubusercontent.com/31730581/63415231-00a81300-c430-11e9-8406-93de3417a035.png)

"el-checkbox" can't use " cy.check( )"  , can't use " .should('be.checked')  "  

i don't know how to Assertions ? : "el-checkbox"

**Comment by cmhtdv** [comment]
<label role="checkbox" class="el-checkbox">
<span aria-checked="mixed" class="el-checkbox__input">
<span class="el-checkbox__inner">
</span>
<input type="checkbox" aria-hidden="true" class="el-checkbox__original" value="" tabindex="-1"></span>

</label>

**Comment by mpahuja** [comment]
the correct locator that you should be using here `el-checkbox__original`

**Comment by jennifer-shehane** [comment]
You need to use `.check()` on the `input` element as explained by @mpahuja
