### ISSUE TITLE
Audio of videos with autoplay is played multiple times

### ISSUE THREAD

**Issue by testquantilope** [cypress-io/cypress#5015]
### Current behavior:
When a video with autoplay is displayed in cypress, the audio plays multiple times.

### Desired behavior:
The audio should only play once in synchronization with the video.

### Steps to reproduce:
1. Execute the following test cases:
```js
describe('Video Issue', function() {
  it('Reproduction', function() { 
    cy.visit(`https://survey.quantilope.com/dXm3LrqLiopRQ2Arq/RmydaiJepkEn69BQT/BN7tbPwzDPmHMNamF`)
    cy.get('#startSurvey').click()
  })
})
```
2. Observe the issue.

### Versions

* Cypress version 3.4.1
* Browser version Chrome 76 and Electron 61

### Notes

* The test case will pass, but the issue will occur anyhow.
* If you only hear the sound once, wait a little, sometimes it takes a little time to trigger.
* The issue get's much worse with longer videos, sometimes the browser even crashes through this issue, making then the test case fail
* This issue was reported as #2548, but was closed since it couldn't be reproduced.

**Comment by jennifer-shehane** [comment]
Thanks for providing a reproducible example. I can recreate the behavior you are describing. 

The issue is isolated to the audio of the videos. And the audio seems to be playing every time this `sync` network request is triggered from `https://kadira-engine.quantilope.com/simplentp/sync`

I can see these `sync` network requests also happening in regular Chrome and the audio does NOT play. 

This issue happens in Electron 61, Chrome 76 and Canary 78 (just happen to have these installed)

The video doesn't even load or appear in Chrome 71. 

This issue also happens all the way back to Cypress version 2.1.0.

**Comment by malwilley** [comment]
I am also experiencing this issue, but with the `<audio />` element instead. This only happens during `cy.get('...')` and you can it also affects elements without the `autoPlay` attribute by bogging down the test with network requests. An example:

```js
describe('audio issues', () => {
	it('fires many network requests during cy.get', () => {
		// Custom audio player with HTML5 audio element
		// No autoplay because I couldn't find one in my quick search
		cy.visit('https://one.npr.org/?sharedMediaId=803780511:803837404')

		// Everything is fine while waiting
		cy.wait(5000)

		// Hundreds of requests made and a lot of looped audio if autoPlay=true
		cy.get('.classThatDoesNotExist') 
	})
})
```

Network tab during the `cy.get` portion of the test:

![image](https://user-images.githubusercontent.com/10888943/74296450-7919cd80-4d09-11ea-9cc1-5e023ba43215.png)

Any idea what is is about `cy.get` that is affecting media elements?

**Comment by paulconlin** [comment]
We're getting this as well. It's almost like in the sidebar keeps each instance of the video element, and if it's autoplaying, then it can create multiple instances of the video element all autoplaying at the same time.

**Comment by EtienneBruines** [comment]
What might be related: browsers send to "seek" the content, especially when the server outputs `Accept: bytes`

However, the Cypress internal proxy breaks this behavior. The HTTP request-headers would include the requested byte-range, but the HTTP response-headers do not include the correct headers to go with it. 

At first glance, it seems like this area could use some work in Cypress: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by melbourne2991** [comment]
If anyone finds this issue, and like me just wants to disable auto play (default browser behavior) you can strip the flag cypress passes through by adding this code to `cypress/plugins/index.js`:

```
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  on('before:browser:launch', (browser = {}, launchOptions) => {
    launchOptions.args.splice(launchOptions.args.indexOf('--autoplay-policy=no-user-gesture-required'), 1)

    return launchOptions
  })
}
```
