### ISSUE TITLE
Cypress auto-generated files should have trailing newlines

### ISSUE THREAD

**Issue by lorennorman** [cypress-io/cypress#502]
## Current behavior:

Frequently (not sure if it's every file), when Cypress auto-generates a file for the user, the files do not include trailing newlines. This is an anti-pattern in general, [see this discussion](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline), and an added nuisance when using `git`:

![image](https://cloud.githubusercontent.com/assets/17697/26119976/3b62a76e-3a3d-11e7-9b14-abad4a4f3b76.png)

and GitHub:

![pasted image at 2017_05_16 01_12 pm](https://cloud.githubusercontent.com/assets/17697/26120022/6710d78c-3a3d-11e7-86d5-92e9ed481b19.png)

## Expected behavior:

I expect Cypress to be aware of common idioms and not generate extra work for users.

### How to reproduce the current behavior:

Generate files and see what git says! Might be harder to see in CLI since git doesn't get a chance to complain for new files, normally the complaints happen in diffs. GitHub for Mac shows it clearly, though.

* Operating System: MacOS
* Cypress Version: 0.19.2

**Comment by jennifer-shehane** [comment]
Commit made here to example project. Need to release and update dep within `cypress`. https://github.com/cypress-io/cypress-example-kitchensink/commit/14c815d45202de51c92d9034e06bd5d984b9f70a
