### ISSUE TITLE
Chrome is being controlled by automated test software alert info bar

### ISSUE THREAD

**Issue by TLadd** [cypress-io/cypress#5021]
### Current behavior:

Since Chrome 76, this `Chrome is being controlled by automated test software` alert info bar is shown when running tests. 

<img width="1438" alt="Screen Shot 2019-08-22 at 6 49 23 AM" src="https://user-images.githubusercontent.com/5084492/63512566-c4b19400-c4a9-11e9-9297-d91caababedf.png">

Related to https://github.com/cypress-io/cypress/issues/1466. disable-infobars was removed again: chromium/chromium@1f2ed68

Commit message mentions An alternative middle-ground is to offer an enterprise policy which allows disabling the security infobars related to automation.. Based on the PR, I believe it's this one: https://cloud.google.com/docs/chrome-enterprise/policies/?policy=CommandLineFlagSecurityWarningsEnabled. So if I'm understanding correctly, I think we would want to enable that policy.

### Desired behavior:

As before, this alert would not render

### Steps to reproduce: (app code and test code)

Open any cypress test suite with Chrome 76 or later.

### Versions

Cypress: 3.4.1
Chrome: 76
OS: Mac OS X

**Comment by magynhard** [comment]
Occurs on any test environment using chromedriver **76** / Chrome **76**.

Same here with Cucumber BDD 3.1.2 @ ruby 2.4.4p296 @ Win7

**Comment by flotwig** [comment]
Cypress uses the `--disable-infobars` flag to disable that toolbar, but the [Chrome team removed it in Chrome 76](https://support.google.com/chrome/a/answer/7679408?hl=en) as you've noticed.

The `CommandLineFlagSecurityWarningsEnabled` has to be set by an administrator, Cypress cannot set it. There's a Local State preference, `browser.command_line_flag_security_warnings_enabled`, which Cypress also cannot set. 

So unfortunately right now there's not a way for us to remove this banner. It shouldn't have an adverse impact on your tests.

----

You can download an older version of Chromium to work around this for now: https://chromium.cypress.io
