### ISSUE TITLE
Selector playground tooltips and highlighter are not rendering

### ISSUE THREAD

**Issue by danielpe7** [cypress-io/cypress#5024]
### Current behavior:

When using the Selector Playground, the tooltips and the highlighted region do not work

![image](https://user-images.githubusercontent.com/53837714/63549452-1a139280-c4f6-11e9-85b4-a44393dd414f.png)

### Desired behavior:

The Selector Playground should work as shown in the documentation:
https://docs.cypress.io/guides/core-concepts/test-runner.html#Selector-Playground

### Steps to reproduce: (app code and test code)
- I installed Cypress yesterday
- Afterwards, I created a sample code that just visits Google
- After running the test, I used the Selector Playground to obtain an identifier for an element in the page and noticed that the tooltips weren't working
Other sites that I tried experienced the same issue.

### Versions

- Cypress v3.4.1
- MacOS Mojave v10.14.6
- Google Chrome v76.0.3809.87

**Comment by jbpallingayan** [comment]
any update on this?

**Comment by danielpe7** [comment]
Today I noticed this in the console output. It seems that the css file with the playground styles is missing:

![image](https://user-images.githubusercontent.com/53837714/64128759-cfa7d680-cd7d-11e9-9d06-b11b738e57c1.png)

**Comment by Elzebub** [comment]
Still an issue in 9.2.0 disappears following a flaky or failing test & that is Exactly the time that I need it. Very frustrating. Please fix!
