### ISSUE TITLE
XHR formData request doesn't work in run mode

### ISSUE THREAD

**Issue by Emsiri** [cypress-io/cypress#5028]
### Current behavior:

When running Cypress in open mode (`npx cypress open`) the XHR `formData` request works as expected, however when running Cypress in run mode (`npx cypress run`) the steps are not run and will report as passed (even when they should fail)

![cypressOpen](https://user-images.githubusercontent.com/5369541/63568712-8e633a00-c5b9-11e9-9ee9-321c27adae69.png)

![cypressRun](https://user-images.githubusercontent.com/5369541/63568761-c23e5f80-c5b9-11e9-8929-97dc2ffec05c.png)

### Desired behavior:

Consistent behavior between run mode and open mode

### Steps to reproduce: (app code and test code)

I've created a repo (https://github.com/Emsiri/Cypress-formData-test) that tests the public swagger API (https://petstore.swagger.io/)

Clone the repo, npm install and run the tests

### Versions

Cypress: 3.4.1, 3.3.1 and 3.2.0
Chrome: 76
Electron: 61

**Comment by luisbolanoss** [comment]
I have the same problem, the test pass (with cypress run)  but this does not finish (do not print the video link and the pass log)

**Comment by Emsiri** [comment]
@jennifer-shehane The tests pass with --browser chrome in run mode and also pass with electron as the browser in open mode. It seems the only way to get a (correctly) failing test is to run in open mode and use Chrome.

**Comment by jc21** [comment]
To represent that last comment:
```
+-----------+------+--------+----------+
| Browser   | Mode | Result | Expected | 
+-----------+------+--------+----------+
| Chrome    | Open | Fail   | Fail     |
| Chrome    | Run  | Pass   | Fail     |
| Electron  | Open | Pass   | Fail     |
| Electron  | Run  | Pass   | Fail     |
+-----------+------+--------+----------+
```

**Comment by Emsiri** [comment]
Just tested on 3.5.0 and Cypress still behaves as per the table above ^
Chrome version 78
Electron version 73

**Comment by Threnos** [comment]
Put up a simple reproduction for this case.
Note, that It uses a file fixture and convert it to blob. Due to this, I am not sure if it's the same problem as reporter had, but surely behaves the same - fails in Open and passes in Run.

`describe('Reproduction test for xhr case', () => {
  it('Send xhr request', () => {
    cy.fixture('someDocument.pdf', 'binary').then(file => {
      Cypress.Blob.binaryStringToBlob(file, 'application/pdf').then(fileBlob => {
        let formData = new FormData()

        formData.set('key', 'value')
        formData.set('file', fileBlob, 'fileName.pdf')

        cy.server()
          .route('POST', 'https://httpbin.org/post')
          .as('formRequest')
          .window()
          .then(win => {
            let xhr = new win.XMLHttpRequest()
            xhr.open('POST', 'https://httpbin.org/post')
            xhr.send(formData)
          })
          .wait('@formRequest').then(response => {
            expect(response.status).to.eq(111)
          })
      })
    })
  })
})
`

**Comment by jennifer-shehane** [comment]
I'm not able to recreate this issue from the issues provided. I see both failing in cypress open and cypress run with the examples. 

Additionally, `cy.route()` has been deprecated and will no longer have any work done on it. We suggest migrating to use `cy.intercept()`.
