### ISSUE TITLE
Add configuration option for disabling screenshots in cypress.json

### ISSUE THREAD

**Issue by Svish** [cypress-io/cypress#5029]
To disable video, all I need to do is to add the following to my `cypress.json` file:

```json
{
  "video": false
}
```

To disable screenshots on the other hand, I have to put this ugly code somewhere:

```js
Cypress.Screenshot.defaults({
  screenshotOnRunFailure: false,
});
```

Can you please just add a simpler config for this so I can keep the global cypress test configuration in one place? E.g.

```json
{
  "video": false,
  "screenshotOnRunFailure": false,
}
```

**Cypress version:** 3.4.1

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-165) by [Unito](https://www.unito.io/learn-more)

**Comment by harshitjuneja** [comment]
@jennifer-shehane @Svish Can this be please assigned to me. Interested to fix this.

**Comment by jennifer-shehane** [comment]
@harshitjuneja Feel free to open a PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.
