### ISSUE TITLE
cy.type() does not append text correctly in certain circumstances

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#503]
Broken historically:

* Regular inputs that have the value set in html
* Number inputs that have the value set in html
* Email inputs that have the value set in html

Broken by a recent version of Chrome:

* Number inputs that have the value set by `.invoke("val")`
* Email inputs that have the value set by `.invoke("val")`

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
