### ISSUE TITLE
trashAssetsBeforeRuns not clearing down screenshot folder

### ISSUE THREAD

**Issue by ARChilton** [cypress-io/cypress#5033]
### Current behavior:
I have `trashAssetsBeforeRuns` set to `true` (as is default) but every run is creating a new screenshot with (1) , (2), (3) etc... added to the name.

a subset of my config which is all default except for baseUrl:
![Screenshot 2019-08-23 at 13 08 42](https://user-images.githubusercontent.com/22243890/63591623-31f71f00-c5a7-11e9-8d42-c87a92a5aec0.png)

### Desired behavior:
to delete the screenshot folder before each test run to provide fresh images only to the screenshot folder.

### Steps to reproduce: (app code and test code)
add `cy.screenshot()` to a test and run multiple times, then see the screenshot folder to see repeated screenshots

### Versions
cypress 3.4.1
macOS mojave 10.14.6
default cypress - chrome 76

Thanks for a fantastic tool and in advance for any assistance with this problem.

**Comment by jennifer-shehane** [comment]
>every run is creating a new screenshot with (1) , (2), (3) etc... added to the name.

Could you define what you mean by 'every run'? How are you running the tests? Are you running tests in `cypress open`? `cypress run`? Are you clicking the 'rerun test' button in the Test Runner?

Per [the docs](https://on.cypress.io/configuration#Screenshots), deleting the screenshots folder will only happen before each execution of [`cypress run`](https://on.cypress.io/command-line#cypress-run).

**Comment by danbroooks** [comment]
I am currently tinkering with the screenshot functionality in my project, and would quite like the behaviour to be that screenshots are overwritten each time. For me, if something has changed, this will be flagged by `git`, and if nothing has changed to impact the screenshot then my git status will be clean. It may be that some people will want the `(1), (2)` behaviour, but is it possible to configure cypress to simply overwrite the screenshot as described?

**Comment by jennifer-shehane** [comment]
Closing since there was no response from original commenter. 

@danbroooks You can express interest in this feature here https://github.com/cypress-io/cypress/issues/7955
