### ISSUE TITLE
Platform specific environment variables

### ISSUE THREAD

**Issue by tomasbjerre** [cypress-io/cypress#5036]
We want to allow different versions of Cypress with different projects, npm packages in Git repositories.

### Current behavior:

If we add this in our `.npmrc`
```bash
CYPRESS_INSTALL_BINARY = https://this.is/the/linux/binary.zip
```

We will have something that will download the wrong binary when developers use Windows.

### Desired behavior:

Allow platform specific environment variables, and fall back on current behavior if no specific variables are set.

The `.npmrc` can have:
```
CYPRESS_INSTALL_BINARY___linux = https://this.is/the/linux/binary.zip
CYPRESS_INSTALL_BINARY___win32 = https://this.is/the/win32/binary.zip
```

Where the suffix is taken from platform [names in Nodejs](https://nodejs.org/api/process.html#process_process_platform).

So that on Windows the effective value of `CYPRESS_INSTALL_BINARY` would be `https://this.is/the/win32/binary.zip`.

These environment variables could then be put in the `.npmrc` in the repository of each application.

### Steps to reproduce: (app code and test code)

https://github.com/cypress-io/cypress/pull/5037

### Versions

All of them.

**Comment by mpahuja** [comment]
There is also https://docs.cypress.io/api/cypress-api/platform.html#Syntax along with https://docs.cypress.io/api/plugins/configuration-api.html#Usage can possibly do what you need

**Comment by tomasbjerre** [comment]
Thanks. I tried `cypress/plugins/index.js` with:
```javascript
    if (Cypress.platform === 'win32') {
        config.env.INSTALL_BINARY =
            'https://npm.asdasd.se/win32-64/cypress.zip';
    } else {
        config.env.INSTALL_BINARY =
            'https://npm.asdasd.se/linux/cypress.zip';
    }
```

But it **did not take**. Still it downloads from default location, not the ones specified above.

**Comment by mpahuja** [comment]
should it be `config.env.CYPRESS_INSTALL_BINARY` instead of `config.env.INSTALL_BINARY`

**Comment by tomasbjerre** [comment]
I tried both.

**Comment by mpahuja** [comment]
actually by the time plugins file is read, cypress has already been installed so yeah this will not work. Sorry i misunderstood what you were trying to do here.

**Comment by bahmutov** [comment]
You have to set the environment variables before starting Cypress, which you can do with a small script. See https://github.com/cypress-io/cypress/pull/5037#issuecomment-529922977 too.
