### ISSUE TITLE
setting process.env to empty object

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#5042]
### Current behavior:

```js
cy.log( "Environment: " + JSON.stringify(process.env,null,4)  );
```
output in browser console
```js
Environment: {}
```

### Desired behavior:

It should not mutate/empty the process.env.

### Versions

OS: Ubuntu 18
Cypress: 3.4.1

**Comment by amitguptagwl** [comment]
Not sure why but `console.log` doesn't work in case of cypress. I thought we are overriding it.

**Comment by mpahuja** [comment]
@amitguptagwl it should be logging to the browser console when you run the tests. 
use `cypress open` to open cypress in interactive mode, run the test and open browser console to see the log you added above.

**Comment by amitguptagwl** [comment]
Thanks @mpahuja .

@jennifer-shehane 
It is `{}` in both case.

**Comment by mpahuja** [comment]
i am assuming you have read this? https://docs.cypress.io/guides/guides/environment-variables.html#Setting

**Comment by amitguptagwl** [comment]
@mpahuja Yes, I did. My question is about why `process.env` is empty? Because currently, I need to make multiple tasks to pass the correct environment variables to run my tests in a different environment. On top of that, I have the tasks to run the tests for the different user journey. They again need to be duplicated per environment.

**Comment by jennifer-shehane** [comment]
Cypress is run in the browser environment, so there will is no access to Node in the browser nor Node's `process.env` within the spec files. 

You can access Node, such as `process.env` within the `support/index.js` or `plugins/index.js` files however for use of any setup you require.

**Comment by dandv** [comment]
Impressive that Cypress supports 6 ways of setting environment variables, but not the uber-popular dotenv... Thankfully there's a [plugin for dotenv](https://www.npmjs.com/package/cypress-dotenv), but I was surprised .env isn't supported out of the box.

**Comment by morficus** [comment]
@dandv are you still having issues getting the plugin to work?
I've tested it using Cypress 4.9 and didn't see any issues.
