### ISSUE TITLE
How can we validate non xhr network request or img type request(applicable for analytics tag)

### ISSUE THREAD

**Issue by suvendupanja** [cypress-io/cypress#5047]
For my testing I want to validate all the analytics tag using cypress. But When i lunch an website different analytics tags are fired. i would like to validate the outgoing request for different analytics. These sorts of tags are available in network tab img section. Can anyone provide me a sample code to check that .. 

I have used the following code which is not working :

```js
describe('test ', function () {
      it('test analytics tag ', () => {
        cy.server();


         cy.route({
             url: /b\/ss/
         }).as('getURL');
         
         cy.visit("www.example.com");
         
      
         cy.wait('@getURL').its("url").should("include", "b");
          })
```

   This is not able to intercept the rerquest for analytics tag

**Comment by mpahuja** [comment]
if its a non-xhr request, e.g. being served from a CDN or something, then it must be attributing to an element. You should get that element and check for the url. Something described here: https://docs.cypress.io/api/commands/should.html#Method-and-Value

**Comment by suvendupanja** [comment]
In that case Do I need to capture thru cy.server , cy.route or some other way.

**Comment by suvendupanja** [comment]
> if its a non-xhr request, e.g. being served from a CDN or something, then it must be attributing to an element. You should get that element and check for the url. Something described here: https://docs.cypress.io/api/commands/should.html#Method-and-Value

That outgoing request is not attributed to any element in the webpage. In that can how can we capture that outgoing request captured a img.

**Comment by mpahuja** [comment]
can you please clarify if you are trying to verify an image request on a webpage or are you trying to validate an analytics event?
if the image you are trying to validate comes from a different origin then cy.route may not work.

Can you please site an example of a public webpage that can be used to understand what you are trying to validate?

**Comment by suvendupanja** [comment]
I am trying to verify the image request.
You can refer one of Australia's public  internet broadband website https://www.latitudefinancial.com.au/

the requirement to validate the adobe tags. 
We can get the adobe tag request by following ways: 
Go to network tab in dev tool and filter with b/ss. 
I would like to validate the some parts of query string parameter of body of the request. 

The body of the request is having some of the adobe analytics values

**Comment by mpahuja** [comment]
This might be close to what you are looking for: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__google-analytics

**Comment by RichieRunner** [comment]
> Hi Richie,
> 
> I have figure out in different way. When I land into a webpage I get all the network request by using window.performance.getEntries(). Store into an array.
> After that put an assertion what analytics tag I am looking for.
> Hope this will help.

hmm interesting, but i'm noticing that in the cypress test runner console. your webpage is actually embedded in its own iframe, so any network request calls are not reachable through the parent page.


![image](https://user-images.githubusercontent.com/20289967/64894490-bed54b80-d62e-11e9-9bbe-cbd59c9e4b0f.png)

**Comment by suvendupanja** [comment]
I can see all the request including img (which are mostly analytics tag). Can you give me an example website?

**Comment by RichieRunner** [comment]
That is odd...are you using `cypress open` or `cypress run`?

The product I'm using (Adobe) isn't GTM, but it's the same concept. There's a script tag on my web page that loads in the javascript resource, which then exposes a new function onto the global window object. In my code, I am executing this function which then sends out a network request of type `img/gif`.

But as we find out in the documentation for `cy.route()`, 
```
Requests using the Fetch API and other types of network requests like page loads and <script> tags will not be intercepted or visible in the Command Log.
```

https://docs.cypress.io/api/commands/route.html#Syntax

**Comment by suvendupanja** [comment]
Hi Richie,

I have implemented in the following ways 

visit the site  then within window object call window.performance.entries() and store it into a array/object. please do not use cy.route. My understanding is that cy.route only capture xhr request. but window.performance.entries() this gives you all request. 

Then can filter which is relevant for you and asset accordingly. 
I am not sure is there any better way we can do but it works for me so far

**Comment by ccodecamp** [comment]
Hi @suvendupanja , I am having the same issue as @RichieRunner . In the cypress test runner console I can see all the requests coming through except for the img tag(adobe analytics). Were you able to see the img requests only for cypress run ?

**Comment by suvendupanja** [comment]
In the network tab you can the request. You can filter thru adobe filter `b/ss`.
if you wan to access programatically you can use the following code 
```
cy.window().then((win) => {
                var networkrequests = win.performance.getEntries().map(r => r.name);
})
```
Withing window you can filter the which request is adobe by name. You can put assertion on top it.

**Comment by suvendupanja** [comment]
@ccodecamp Ideally cypress should not block any network request as you know under the hood it  runs electron (headless chrome browser). 
By default cyprss does not block anything. 
Can you please double check your cypress config. I would say if you can re-install cypress and do it fresh. Again it upto you.

**Comment by sbbird** [comment]
+1 for not able to capture img request. 
Our site uses javascript to create a new image for sending a tracking request. Note that the javascript is served from CDN.

**Comment by geyuqiu** [comment]
thanks @suvendupanja  I needed  `cy.wait(3000);` to make it work

**Comment by bahmutov** [comment]
You can spy / intercept any requests using the new [cy.intercept](https://on.cypress.io/intercept) command. Find our examples in [Stubbing using cy.intercept](https://github.com/cypress-io/cypress-example-recipes#stubbing-and-spying) recipe

You can also spy on image resources directly using `window.performance.getEntries()` browser API, see [Waiting for static resource](https://github.com/cypress-io/cypress-example-recipes#testing-the-dom) recipe.

**Comment by RichieRunner** [comment]
hi @bahmutov , I've been trying `cy.route2`/`cy.intercept` since it came out, but unfortunately, it still cannot intercept the issue that I mentioned above:

> The product I'm using (Adobe) isn't GTM, but it's the same concept. There's a script tag on my web page that loads in the javascript resource, which then exposes a new function onto the global window object. In my code, I am executing this function which then sends out a network request of type img/gif

This `.gif` request in the network tab does **not** get picked up by `cy.intercept`

![image](https://user-images.githubusercontent.com/20289967/100808521-2a990500-33e9-11eb-9b6a-850512b93651.png)

**Comment by jennifer-shehane** [comment]
@RichieRunner If you can provide a failing example, please open an issue using `cy.intercept()` as this should work.

**Comment by Lei-Xu** [comment]
Hi @bahmutov. 

I want to validate all the adobe analytics tag using cypress. below is part of my code:

`cy.intercept('POST', 'https://XXXX', {statusCode: 200}).as('adobe-analytics-events')`
`cy.wait('@adobe-analytics-events')`

However, it seems that all the adobe analytics outgoing requests are "not caught" in cypress test runner console. 

<img width="1483" alt="Screen Shot 2021-01-11 at 1 45 53 PM" src="https://user-images.githubusercontent.com/18302244/104226131-50b4ba80-5415-11eb-8037-ccdf44759712.png">

<img width="1027" alt="Screen Shot 2021-01-11 at 1 46 45 PM" src="https://user-images.githubusercontent.com/18302244/104226146-55796e80-5415-11eb-81f1-f730e90d5219.png">

My question is:
1. Is it the cypress issue? having problems when dealing with adobe analytics.
2. If not. could you point out my mistakes of implementation?

**Comment by DharaniY** [comment]
> In the network tab you can the request. You can filter thru adobe filter `b/ss`.
> if you wan to access programatically you can use the following code
> 
> ```
> cy.visit("Pagename")
> cy.window().then((win) => {
>                 var networkrequests = win.performance.getEntries().map(r => r.name);
>                //previous step will give you array of all the Network request. 
>               // You can filter the network request based on the you filter criteria (like Adobe b/ss string 
>                   should be thet for GA : google-analytics etc)
>  
> })
> ```
> 
> Withing window you can filter the which request is adobe by name. You can put assertion on top it.

Hi ,can you please share sample code here, Thanks in advance

**Comment by JayKishoreDuvvuri** [comment]
Hi, can anyone help me with the sample code of yours for adobe tracking with cypress please? I have my network tab showing dynamic request names changing for every new login. 

My case is similar to @ Lei-Xu mentioned above .

Can anyone share me sample code please? 

Thanks in advance.

cheers,
Jay.

**Comment by HappyMan0001** [comment]
Yes, I am having the same issue. I can't intercept "_/b/ss_", I tried various ways for Cypress to intercept it. It works perfectly well for Google Analytics, but for **_Adobe_**, it does not "_Timed out retrying after 5000ms: cy.wait() timed out waiting 5000ms for the 1st request to the route: adobe-analytics. No request ever occurred_". Like JayKishoreDuvvuri mentioned: Can anyone share sample code? What I am trying to figure out, is what are you intercepting? how do you call it? Can I intercept Adobe Analytics? Can Cypress handle this? Any help is appreciated. Thanks

**Comment by JayKishoreDuvvuri** [comment]
Hi @HappyMan0001 

thanks for your reply and pointing this out.

You can go through this, if you are interested:
https://lnkd.in/dHWMcWMn - cypress 
https://lnkd.in/d_4HaErt - playwright 

thank you!

**Comment by HappyMan0001** [comment]
@JayKishoreDuvvuri, Hi thanks for sharing. My issue is that the cy.intercept() is not intercepting the API call. Cypress, just skips over it or doesn't find it. I keep getting stuck on that part or a response: Timed out retrying after 5000ms: cy.wait() timed out waiting 5000ms for the 1st request to the route: adobe-analytics. No request ever occurred. 
I'm curious has there been a fix for this after Cypress version 11.1? Because I'm using Cypress version 11.1.

**Comment by VenkatMuthineni** [comment]
@HappyMan0001  did you find the solution for the issue

**Comment by HappyMan0001** [comment]
This is an old post, so I had to look through my code for this test, and yes I did find a solution. It was really about where in the best  location I'd set up: `cy.intercept('/b/ss/**').as('adobeAnalytics')`. So in my test, I had to use 2 separate intercepts not just one. Since I am testing 2 different areas, with 2 different results. The first one just like you see in my example, is right after the it() block. Anywhere else, like in the before() block or in any other area else, would cause a failure. I had to set it up as the first thing after the it() block. Then, the second one, is after a few actions. In my own test as step 3. and then do my assertions something like:  
```
            cy.log('**Step 3**')
           //After DOM settles, launch intercept
            cy.intercept('/b/ss/**').as('adobe-button-analytics')
            //Click button to create an action
            buttonAndSeparator.getAdobeLinkButton().invoke('removeAttr', 'target').click({force:true})
            cy.wait(2000)
            //Assert after button click
            cy.go('back')
            cy.waitForStableDOM({timeout: 55000})

            cy.log('**Step 4**')           
            //test intecept results
            cy.wait('@adobe-button-analytics').its('request.url').then((s) => 
            new URL(s)).its('searchParams').then((url)=>
                {
                   return {
                    name: url.get('c5'),
                    type: url.get('c9')
                   }
                }).should('deep.equal', 
                {
                    type: 'Afte Button Clicks',
                    name: 'Adobe Analytics Result',
                })
```
Anyhow, for me it was where I was locating my intercept, and where I was locating my cy.wait('@adobe-button-analytics'). I really hope this helps, finally for my tests it was about location, location, location where in the test you are placing the intercepts & cy.wait(). I hope that helps. @VenkatMuthineni

**Comment by VenkatMuthineni** [comment]
Thanks for sharing @HappyMan0001 i will try this one
