### ISSUE TITLE
Cypress v3.4.1 is not compatible with Windows (Platform: win32 (10.0.17134) )

### ISSUE THREAD

**Issue by viet-le-cko** [cypress-io/cypress#5048]
### Current behavior:

Platform: win32 (10.0.17134) Cypress Version: 3.4.1 error Command failed with exit code 1.

### Desired behavior:

```Cypress open``` should run

### Steps to reproduce: (app code and test code)

Nothing to do with the test code, just unable to run cypress. However, it works on Mac.

### Versions

^3.2.0

**Comment by tomasbjerre** [comment]
We are using win32 and Cypress 3.4.1. Without such problems.

I would suggest providing a not working example.
