### ISSUE TITLE
Starting browser in GUI does not work if the current project's server is no longer running

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#505]
* Operating System: OS X
* Cypress Version: 0.19.2
* Browser/Browser Version: Chrome 58.0.3029.110

### Are you requesting a feature or reporting a bug?
Bug 🐛 

### Current behavior:
I have my `baseUrl` set in my `cypress.json` as a locally running server: `http://localhost:2222`. If I click into a project with my project's server running, then kill my project's server, then try to run a test, the GUI says "Opening Chrome" with the spinning icon, but Chrome never opens.

### Expected behavior:

- If the server at my `baseUrl` is no longer running when I click to run a test or All tests - I should see an error saying that Cypress could not start. 

### How to reproduce the current behavior:
- Set `baseUrl` in `cypress.json` to a local server.
- Run the server
- Click into the project
- Kill the server
- Click on a test 

### Additional Info (images, notes, stack traces, etc)

**What I See**
<img width="912" alt="screen shot 2017-05-19 at 2 11 32 pm" src="https://cloud.githubusercontent.com/assets/1271364/26261749/6863747c-3ca0-11e7-9971-98a9fc8051ab.png">

**What I Should See**
<img width="912" alt="screen shot 2017-05-19 at 2 31 36 pm" src="https://cloud.githubusercontent.com/assets/1271364/26261754/6d146f58-3ca0-11e7-8fc9-62422eb277a4.png">

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by jennifer-shehane** [comment]
This is actually still not slated to be fixed in 0.20.0. Although the warning message when your server is not running has been modified in 0.20.0, it still will not display AFTER the Cypress tests have started and you later kill your server.

**Comment by jennifer-shehane** [comment]
This should no longer be a prohibiting bug. We now show a dismissible warning message when we see the baseUrl is not running.

<img width="912" alt="screen shot 2019-02-01 at 6 10 09 pm" src="https://user-images.githubusercontent.com/1271364/52121039-a50d6800-264c-11e9-94fd-8f4f2875e603.png">
