### ISSUE TITLE
When I run the tests together ("Run all specs"), it crashes. But when I run each one individually, they all work. any solution?

### ISSUE THREAD

**Issue by Rohit1990Sharma** [cypress-io/cypress#5054]
![image](https://user-images.githubusercontent.com/54660583/63918432-5006c880-ca5a-11e9-9902-ca3f69517a70.png)

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
