### ISSUE TITLE
Can't run cypress verify and cypress run in Dockerfile

### ISSUE THREAD

**Issue by gracesianturi** [cypress-io/cypress#5056]
### Steps to reproduce: (app code and test code)
1. I have a Dockerfile
2. In my docker file there are : 
    RUN npm install
    RUN npm install --save-dev cypress
    RUN $(npm/bin)/cypress verify
    RUN $(npm/bin)/cypress run
3. open terminal in folder and type " docker build . "

Thank you.

### Versions
Cypress : 3.4.1
OS : Ubuntu 18.04
![Screenshot from 2019-08-29 15-29-02](https://user-images.githubusercontent.com/29389000/64020975-1ff41e00-cb5d-11e9-8027-2803b8892f69.png)

**Comment by bahmutov** [comment]
@gracesianturi it seems your Docker file has syntax errors
- `$(npm/bin)/cypress verify` should be `$(npm bin)/cypress verify`
- why is it running NPM install inside folder `cypress/integration/unit_test/test_runner`? It seems very wrong

**Comment by gracesianturi** [comment]
Thank you for helping me , Sir. I just want to run my Dockerfile but i don't know how to run my dockerfile with cypress project. So I can run it in my docker. thank you

**Comment by jennifer-shehane** [comment]
Hey @gracesianturi has your issue been resolved? Because we'll close the issue if so.

**Comment by gracesianturi** [comment]
hello @jennifer-shehane  . the issue has been resolved. thank you
