### ISSUE TITLE
Feature request - API to get the listing of a directory

### ISSUE THREAD

**Issue by andreaazzara** [cypress-io/cypress#507]
* Operating System: macOS Sierra
* Cypress Version: 0.19.2
* Browser/Browser Version: Chrome 58

### Are you requesting a feature or reporting a bug?
Feature request

### Expected behavior:
It would be great to have a Cypress API to get the content of a directory, similar to fs.readdir, possibly with detailed information about the content of the directory (files or directories) so that multiple files can be loaded using cy.readFile().

**Comment by jennifer-shehane** [comment]
@lilaconlee Also related to cy.readFile() improvements https://github.com/cypress-io/cypress/issues/411

**Comment by bahmutov** [comment]
You can do this using [`cy.task`](https://on.cypress.io/task)

**Comment by jaydeep987** [comment]
> You can do this using [`cy.task`](https://on.cypress.io/task)

what if I want to use `cy.task` to generate `it()` dynamically ?

**Comment by jennifer-shehane** [comment]
@jaydeep987 There are examples here https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests
