### ISSUE TITLE
Yield sameSite attribute in getCookies

### ISSUE THREAD

**Issue by goldenshun** [cypress-io/cypress#5070]
### Current behavior:

The list of attributes yielded by `cy.getCookie` does not include the [sameSite](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/SameSiteStatus) attribute.

https://docs.cypress.io/api/commands/getcookie.html#Yields

### Desired behavior:

Yield `sameSite` in `getCookies`.

### Steps to reproduce: (app code and test code)
```js
cy.getCookie('TOKEN').then((cookie) => {
  expect(cookie.sameSite).to.equal('Lax'); // Cannot do this now
});
```
### Versions

Cypress `3.4.1`. I don't think system/browser matters.

**Comment by flotwig** [comment]
There is a related issue to add support for setting SameSite here: #2437
