### ISSUE TITLE
Timestamp retrieval not correct

### ISSUE THREAD

**Issue by 9odzilla** [cypress-io/cypress#5073]
### Current behavior:

I'm trying to get the current timestamp throughout my test for to determine wait times. I'm using moment to get the current timestamp. After some elapsed time I call moment to get the current timestamp again. When I check the timestamps though, they are the exact same.

### Desired behavior:

Calling moment() should return the current timestamp.

### Steps to reproduce: (app code and test code)

Example code:

const date1 = Cypress.moment().format("x");
cy.log(date1);
cy.wait(5000);
const date2 = Cypress.moment().format("x");
cy.log(date2);
cy.wait(5000);
const date3 = Cypress.moment().format("x");

All the dates have the exact same values when they should be 5 seconds apart.

### Versions

Cypress 3.4.1
OS: Win 10
Browser: Chrome 75

**Comment by 9odzilla** [comment]
I figured out why this does not work. Still learning as I go!

**Comment by jennifer-shehane** [comment]
@9odzilla Thanks for the update. Please try to let us know your solution so others can learn too.

**Comment by th2tran** [comment]
@9odzilla: You said you figured out why it does not work. Could you please share the reason? I'm encountering the same problem with cy.log(new Date().toTimeString()) getting the same value for successive entries.

**Comment by 9odzilla** [comment]
@th2tran In my case, the reason I was getting the same timestamp is because of how Cypress executes. I believe Cypress queues up all the 'cy' commands and then executes them in order. Any other javascript outside of those commands are executed before hand, hence why the timestamps are all instantiated first. In your case I'm not sure why if you wrapped generated the timestamp inside a 'cy' log statement, it is still the same. You might have to nest those statements like
````
cy.log(new Date().toTimeString()).then(() => {
  cy.log(new Date().toTimeString();
});
```

**Comment by th2tran** [comment]
@9odzilla thanks for your response. I came up with a workable solution by adding a custom command like so:
```
Cypress.Commands.add('customLog', (message) => {
    Cypress.log({
        name: 'LOG',
        message: '[' + new Date().toTimeString()+ '] ' + message
    });
});
```

And then everywhere in my test, I simply replace
```
cy.log(...)
```
with 
```
cy.customLog(...)
```
