### ISSUE TITLE
Upgrade Node version to latest (your version is very old)

### ISSUE THREAD

**Issue by nettad** [cypress-io/cypress#5074]
Create node service with version 10+. Use util.promisify in your server. Try to start that server in cypress env. You will get "util.promisify is not a function". 
I'm not sure it's worth reproducing. Fact of the matter is, the node version cypress ships with is very old.

**Comment by bahmutov** [comment]
See https://github.com/cypress-io/cypress/issues/4432 and there is a pull request that implements this https://github.com/cypress-io/cypress/pull/4436
