### ISSUE TITLE
Enforce chaining off of cy for new series of commands

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#508]
One of the best (and yet worst) parts about Cypress is the chainable API interface. 

While it is actually quite simple, it is unlike any other interface developers are familiar with - and their tendencies are to overcomplicate it / overprogram it, or simply not use it correctly.

This, in our opinion is because:

- it looks synchronous (but its not)
- it uses a promise interface (but has different semantics)
- there is a concept of parent / child / dual commands which has an upfront learning cost

As part of the API changes to create commands noted here: https://github.com/cypress-io/cypress/issues/436 we are also considering enforcing commands to be 'broken' up and not chained per sequence.

This would likely clear up some confusion around the relationship between commands and make it easier to explain in our docs.

For instance, all parent commands would become enforced to be chained off of `cy` and not an existing sequence.

It would turn this:

```js
cy
  .get('button').click().should('have.class', 'active')
  .get('form').submit()
  .url().should('include', '/users')
```

...into...

```js
cy.get('button').click().should('have.class', 'active')
cy.get('form').submit()
cy.url().should('include', '/users')
```

### Upsides
- This is easy to catch and throw very specific errors. You incorrectly chained 'foo' and it should be called after 'cy'.
- This makes `cy.should` and `cy.then` much easier to explain
- Dual commands still work both ways
- Docs can be simplified and the language around these requirements can be more easily explained.
- When a command is created it specifies its subject dependencies up front. It either requires an existing subject (of an specific type) or it doesn't, and therefore must be chained off of `cy`
- `cy.end` would be removed
- Internally a lot of the driver code could be simplified (especially around aliasing)

### Potential Problems

When querying into the DOM this works well, but other commands (which are not meant to be chained) this would mean you'd be constantly typing `cy.command()` all alone by itself.

Examples:

- `cy.server`
- `cy.route`
- `cy.server`
- `cy.clearLocalStorage`
- `cy.clearCookie`
- `cy.clearCookies`
- `cy.setCookie`
- `cy.screenshot`
- `cy.clock`
- `cy.tick`

### Upgrading Woes

The worst part about this change is that it would likely break *every single* existing Cypress project, which would create a lot of chaos.

**Comment by bahmutov** [comment]
also, this does not work :(
```js
const {visit, contains, screenshot} = cy
describe('header TypeScript test', () => {
  it('is has expected text', () => {
    visit('index.html')
    contains('h2', 'test')
    screenshot('page')
  })
})
```
with error
```
TypeError: this.private is not a function
      at $Cypress.Cy.(anonymous function) (http://localhost:61210/__cypress/static/js/cypress.js:1013:31)
      at Context.<anonymous> (http://localhost:61210/__cypress/static/js/cypress.js:3735:29)
```

**Comment by bahmutov** [comment]
Also, should we add `cy.subject` child command? As alias to `.then` probably

**Comment by dwelle** [comment]
If this gets discarded to not break existing projects, I'd at least allow it as a config option. I'm in the camp of people that prefer clarity over convenience.

I'd be glad to be able to enforce this rule in our codebase, since it'll make it much easier to teach it to other people on the team, easier to maintain, less probable for the tests to be misinterpreted in the future etc.

**Comment by brian-mann** [comment]
We could also enable this by default in a breaking version but enable you to turn **off** restrictive chaining. I agree with you - I would prefer being stricter by default but give people an escape hatch to bypass this requirement (since Cypress already works both ways).

Do you have any other thoughts in regards to the proposal above?

**Comment by dwelle** [comment]
No, I agree that enabling it by default as a breaking change, and allowing to opt-out, is probably the best solution here.

Other than that, the proposal seems good, and cypress as a whole will IMO benefit -- particularly when onboarding new users.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
