### ISSUE TITLE
CYPRESS_baseUrl not override baseUrl from cypress.json 

### ISSUE THREAD

**Issue by bapohka** [cypress-io/cypress#5080]
I have baseUrl written in cypress.json and another in scripts of package.json for different envinronments to test

> cypress.json
`"baseUrl": "https://prod.com",`

> package.json
`"scripts": {`
`"cypress:open": "cypress run --browser chrome --reporter mochawesome --parallel",`
`"cy.run:prod": "cypress run CYPRESS_baseUrl=https://prod.com --browser chrome --reporter mocha-multi-reporters",`
`"cy.run:dev": "cypress run CYPRESS_baseUrl=https://dev.prod.com  --browser chrome --reporter mocha-multi-reporters",`

so when i use `npm run cypress:open` - it opens my prod.com website and tests are running.
but when i use `npm run cy.run:dev` - it also open my prod.com website, but not the dev.prod.com.

As i understand, variable `CYPRESS_baseUrl` should override my link from cypress.json, but this never happens.

i tried to debug with `cy.log("We are on this environment: " + Cypress.config('baseUrl'));` and it always show me my cypress.json baseUrl

**Comment by bahmutov** [comment]
@bapohka you put the environment variable in the wrong place - move them to be the first ones in the command. For example

```
"cy.run:prod": "CYPRESS_baseUrl=https://prod.com cypress run --browser chrome --reporter mocha-multi-reporters"
```

Even better is to reuse an existing command, for example

```
"cy.run": "cypress run --browser chrome --reporter mocha-multi-reporters",
"cy.run:prod": "CYPRESS_baseUrl=https://prod.com npm run cy.run"
```

Alternatively, you can pass the base config as a CLI argument

```
"cy.run:prod": "cypress run --browser chrome --reporter mocha-multi-reporters --config baseUrl=https://prod.com"
```

See https://on.cypress.io/configuration#Overriding-Options

**Comment by bapohka** [comment]
D:\dev>npm run cy.run:prod

> @ cy.run:prod D:\dev
> CYPRESS_baseUrl=https://prod.com cypress run --browser chrome --reporter mocha-multi-reporters

"CYPRESS_baseUrl" not internal or external
command, executable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ cy.run:prod: `CYPRESS_baseUrl=https://prod.com cypress run --browser chrome --reporter mocha-multi-reporters`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ cy.run:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bapohka** [comment]
"cy.run": "cypress run --browser chrome --reporter mochawesome --parallel",
"cy.run:dev": "CYPRESS_baseUrl=https://dev.prod.com npm run cy.run",


D:\dev>`npm run cy.run:dev`

> @ cy.run:dev D:\dev
> CYPRESS_baseUrl=https://dev.prod.com npm run cy.run

"CYPRESS_baseUrl" not internal or external
command, executable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ cy.run:dev: `CYPRESS_baseUrl=https://dev.prod.com npm run cy.run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ cy.run:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bahmutov** [comment]
you are using a wrong syntax for setting an environment variable on Windows, I suggest using https://www.npmjs.com/package/cross-env to achieve this

```
npm i -D cross-env
cross-env CYPRESS_baseUrl=https://dev.prod.com npm run cy.run
```
