### ISSUE TITLE
[Feature] blacklistHosts should return failed or similar

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5084]
### Current behavior:

The current implementation of the blacklistHosts returns a 503 service unavailable error. For some scripts this leads to unexpected errors f.e. they are crashing completely.

see https://github.com/cypress-io/cypress/blob/84f99e6e8752e5e422e298b0e894930c275023ee/packages/server/lib/controllers/proxy.coffee#L115

Screenshot of Chrome ran by cypress:
<img width="433" alt="Screenshot of Chrome ran by cypress" src="https://user-images.githubusercontent.com/1520593/64252200-9062bc80-cf1a-11e9-8955-cb6c17b893ec.png">

### Desired behavior:

The blacklistHosts implementation should return a failed or similar error like the DNS is not resolvable.

Screenshot of Chrome with failing DNS resolution:
<img width="421" alt="Screenshot of Chrome" src="https://user-images.githubusercontent.com/1520593/64252149-6e693a00-cf1a-11e9-8297-76c5739d4fe2.png">

### Versions

3.4.1

**Comment by jennifer-shehane** [comment]
There doesn't seem to be any documented conversation on why this decision was initially made: https://github.com/cypress-io/cypress/issues/442#issuecomment-351812386

>For some scripts this leads to unexpected errors f.e. they are crashing completely.

Can you explain more fully by what you mean? 

I kind of feel like any implementation we choose is going to go down some avenue of 'not truly representing what we want'. But I'll bring it up with engineering.

**Comment by CSchulz** [comment]
In our case it is an external tracking script written by Adobe, it handles connection failed errors but no server errors.

Most scripts are checking if the return code is not equal to 0, if so they continue. If the return code equals 0, you know the connection failed.

**Comment by flotwig** [comment]
Hey @CSchulz, when #687 is complete, it will allow you to end requests with a network error by doing something like this:

```js
// force all requests to `tracking.adobe.com` to end early
cy.route({ domain: 'tracking.adobe.com' }).end()
```
