### ISSUE TITLE
cy.get() grabbing incorrect iframe

### ISSUE THREAD

**Issue by ryan-snyder** [cypress-io/cypress#5085]
### Current behavior:
For context, I am testing an application which dynamically plays content in an iframe. So some of my tests try to ensure that the correct content is playing. So what I have done is attach a data-cy attribute as shown in the Cypress Best Practices so I can grab the correct content based on what should be playing.

The element that I am trying to get has a data-cy attribute of `data-cy="youtube-test.html"`, however the element that is returned to me has a data-cy attribute of `data-cy="video-test.html"`.
I don't quite understand how that could be possible but my best guess is some sort of fallback if an iframe is not loaded?

![Screenshot from 2019-09-04 15-34-33](https://user-images.githubusercontent.com/36665494/64281741-2eaa4e80-cf2a-11e9-9d1a-016bc7509e84.png)

### Desired behavior:

cy.get() should, or is expected to, return the matching element if found or fail if it isn't found

### Steps to reproduce: (app code and test code)

Since this is a somewhat complicated commercial application, it will not be easy for me to set up a reproducible example but if there is no obvious answer I can try

### Versions

Cypress: 3.4.1
OS: Linux Fedora
Browser: Chrome 76 (according to cypress)

**Comment by jennifer-shehane** [comment]
See our open issue on iframe support. It's not fully supported, so we will not address newly created issues about iframes until it is fully supported: https://github.com/cypress-io/cypress/issues/136
