### ISSUE TITLE
Cypress test runner not rendering Blockly categories

### ISSUE THREAD

**Issue by vaibzzz123** [cypress-io/cypress#5092]
### Current behavior:

I have a React web app which uses Blockly that I'm currently trying to write automated tests for using the Cypress framework.

Cypress works pretty well for the basic process of signing on, but starts behaving inconsistently once Blockly is supposed to load.

About **half the time**, the entire Blockly portion of the app doesn't show up at all in the Cypress viewport. Sometimes this shows up, sometimes it doesn't, and I'm unsure what causes it or how to really reproduce it, it seems to be random.

Here is how it looks when it loads properly: 
![image](https://user-images.githubusercontent.com/26746509/64360362-5526c300-cfd8-11e9-9631-1cf61afb65c4.png)

Here is how it looks when it doesn't load properly: 
![image](https://user-images.githubusercontent.com/26746509/64360383-5f48c180-cfd8-11e9-97e4-945671dd4c31.png)

At first, I thought that the reason it didn't work is because the resources for Blockly hadn't loaded, and Cypress was trying to access resources that didn't exist.

To work around this, I added a delay, using cy.wait(). I tried anywhere from 1s-10s, but the delay doesn't seem to affect anything, no matter how long the delay is, it doesn't seem to impact if the Blockly portion of the app loads properly or not.

### Desired behavior:

I'd like to have it show up like the first picture above every time, which it doesn't seem to do every single time.

### Steps to reproduce:

Here is the code for the portion of the Cypress test file used:

```js
  it('Sign in with created profile', () => {
    cy.visit('localhost:3000/');

    cy.get('input[name="email"]')
      .type('test123@test.com').should('have.value', 'test123@test.com');

    cy.get('input[name="password"]')
      .type('testtest').should('have.value', 'testtest');
    cy.get('button[type="submit"]').click();
  });

  it('Open created project', () => {
    cy.get('div[class="project-container"]').contains('test project').click();
  });

  it('Drop 1+1 block into grid', () => { //2s delay
    cy.wait(2000).then((prom) => {
      cy.get('div[class="blocklyTreeRow"]').contains('Math').click({ force: true });
    });
  });
```
It works perfectly, until just after the 'Open created project' part of the test is run, then it's a hit or miss if the Blockly part of the app shows up. Refer to the images above for possible scenarios that happen.

It doesn't seem to be reproduced reliably, it's pretty random with about a 50/50 chance of being rendered properly or not.

### Versions

Cypress 3.4.1, Chrome 76

**Comment by jennifer-shehane** [comment]
I would suggest opening your Developer Tools and see if there are any errors in there when it's loading - also the Network tab. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run on our machines and see the failure and we will reopen the issue. 🙏
