### ISSUE TITLE
Need ability to navigate 'back' / simulate history's previous routes

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#51]
I want to be able to test my application's behavior of updating the url on a user's click of the back button within their browser. I'd like to be able to have a way to do this in cypress commands.

**Comment by brian-mann** [comment]
That's what `cy.navigate` will be. You'll be able to go back and forth as well as change the url or hash params without reloading the page. It just needs to be created at this point.

**Comment by brian-mann** [comment]
Currently this can be achieved by doing `cy.window().invoke("history").invoke("back")`.

**Comment by brian-mann** [comment]
This was implemented in [`0.13.5`](https://github.com/cypress-io/cypress/wiki/changelog#0135-01032016).
