### ISSUE TITLE
`Cypress.Commands.overwrite` doesn't pass down the context

### ISSUE THREAD

**Issue by x-yuri** [cypress-io/cypress#5101]
### Current behavior:
```js
Cypress.Commands.overwrite('then', function(originalCommand, subject, fn, options = {}) {
    return originalCommand.call(this, subject, options, fn);
});
 
specify('aliases work', function () {
    cy.wrap(1).as('myAlias');
    cy.wrap(2).then(function(subj) {
        expect(this.myAlias).to.eq(1); // undefined
    });
});
```

### Desired behavior:

The test succeeds.

### Steps to reproduce: (app code and test code)

https://github.com/x-yuri/issues/tree/cypress-overwrite

### More info

`Cypress.Commands.overwrite()` is used by [`cypress-commands`][1] package. Is there a possibly better way to change `then()` command?

[1]: https://github.com/Lakitna/cypress-commands/issues/27

### Versions

Cypress 3.4.0, Arch Linux, Electron 61

**Comment by Lakitna** [comment]
Pinging @jennifer-shehane as this has not been answered within a month :)

**Comment by bahmutov** [comment]
Good:

<img width="500" alt="Screen Shot 2020-12-09 at 10 13 03 AM" src="https://user-images.githubusercontent.com/2212006/101648099-7a8a5400-3a07-11eb-9e42-adcfe86f618d.png">

Broken:

<img width="493" alt="Screen Shot 2020-12-09 at 10 15 18 AM" src="https://user-images.githubusercontent.com/2212006/101648117-7f4f0800-3a07-11eb-93b4-536364c06915.png">
