### ISSUE TITLE
Possible namespace collision?

### ISSUE THREAD

**Issue by bm-stschneider** [cypress-io/cypress#5102]
I was just wondering, if I'd use cytoscapejs with cypressjs, would I run into a namespace collision since they both seem to use `cy.` for their namespace?

**Comment by jennifer-shehane** [comment]
I don't think so. Cypress `cy` will only apply to the application under test in the test file, you could always redefine this so that there's no confusion like below. 

```js
const cypress = cy

it('works', () => {
  cypress.viewport(550, 750)
})
```

Try it out. Comment if there's a huge bug you run into.
