### ISSUE TITLE
Cypress calling home?

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5105]
### Current behavior:

I am wondering what kind of calls are behind the following:

```
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 503 0.648 ms - -
GET /chrome-variations/seed?osname=mac&channel=stable&milestone=76 503 0.250 ms - -
GET /__cypress/runner/cypress_runner.js 200 5.420 ms - -
GET /__cypress/iframes/integration/spec.ts 200 7.755 ms - 716
GET /__cypress/runner/fonts/fontawesome-webfont.woff2 200 0.977 ms - 77160
GET /tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZxkx2ZXSPanojLZFhlU4kIy0viD6CJCMtkWGVTiQU 503 0.249 ms - -
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 503 0.230 ms - -
GET /tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZxkx2ZXSPanojLZFhlU4kIy0viD6CJCMtkWGVTiQU 503 0.237 ms - -
GET /tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZxkx2ZXSPanojLZFhlU4kIy0viD6CJCMtkWGVTiQU 503 0.309 ms - -
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 503 0.275 ms - -
GET /tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZxkx2ZXSPanojLZFhlU4kIy0viD6CJCMtkWGVTiQU 503 0.241 ms - -
```

I couldn't find anything here in this repository.

### Desired behavior:

No calls to any unknown destination:

```
GET /__cypress/runner/cypress_runner.js 200 5.420 ms - -
GET /__cypress/iframes/integration/spec.ts 200 7.755 ms - 716
GET /__cypress/runner/fonts/fontawesome-webfont.woff2 200 0.977 ms - 77160
```

### Steps to reproduce: (app code and test code)

cypress.json:

`"blacklistHosts": ["*.net", "*.com"]`

Cypress call options:

```
{ project: 'projects/app-e2e',
  config: { baseUrl: 'http://localhost:4200/app' },
  env:
   { tsConfig:
      '.../tsconfig.e2e.json' },
  exit: true,
  headed: true,
  record: false,
  key: undefined,
  parallel: false }
```

### Versions

3.4.1

**Comment by CSchulz** [comment]
It seems Chrome is very noisy:

https://www.google.com/search?q=ListAccounts%3Fgpsia%3D1%26source%3DChromiumBrowser%26json%3Dstandard
https://www.google.com/search?q=tbproxy%2Faf%2Fquery

Can we set some flags stopping Chrome from calling home?

**Comment by jennifer-shehane** [comment]
Yeah. The majority of this is not Cypress. The logs below are Cypress loading the actual Test Runner UI and you can get full debug logs as described here: [https://on.cypress.io/debugging#Print-DEBUG-logs](https://on.cypress.io/debugging#Print-DEBUG-logs]

```
GET /__cypress/runner/cypress_runner.js 200 5.420 ms - -
GET /__cypress/iframes/integration/spec.ts 200 7.755 ms - 716
GET /__cypress/runner/fonts/fontawesome-webfont.woff2 200 0.977 ms - 77160
```

@CSchulz 	Can you explain the actual issue with the requests? What are you trying to do? Is it the logs that are the problem or the actual requests? Why are they a problem?

**Comment by CSchulz** [comment]
I just struggled about it after checking the logs. I want to get rid of all noisy features in Chrome talking to the internet, to have an easy readable log.

f.e. https://github.com/brave/brave-browser/issues/1676 tells about some autofill feature, perhaps there is a flag do disable it.

**Comment by jennifer-shehane** [comment]
You can pass flags to Chrome as documented here: [https://on.cypress.io/browser-launch-api](https://on.cypress.io/browser-launch-api)

Closing as this doesn't seem to be related to Cypress specifically.
