### ISSUE TITLE
Support setting config for current test only

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#5106]
We have `Cypress.config('foo', bar)`, but this changes the Cypress config for the rest of the entire spec run, no matter where it's called.

It would be nice to support something like `cy.config('foo', bar)` that only sets the config for the current test run.

For example this would enable:
- users to configure `defaultCommandTimeout` for just one test or suite of tests 
- plugin authors to add custom config that can be on per-test basis (e.g. disable plugin for suite of tests)

#### notes
Yes, we have talked about a more robust configuration model where you supply test-specific configuration _not in the test body_ so it can be known ahead of test-run time, but I think this proposal can go in earlier and alongside that proposed solution

**Comment by jennifer-shehane** [comment]
This now exists as Test Configuration. See docs: https://on.cypress.io/writing-and-organizing-tests#Test-Configuration

Closing as resolved.
