### ISSUE TITLE
launcher: improve browser detection

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#511]
Planned for [0.20.0](https://github.com/cypress-io/cypress/wiki/changelog)

Several issues consolidated:

## Linux

- [x] can we grab `google-chrome-stable` if available? https://github.com/cypress-io/cypress-core-launcher/issues/1
- [x] we should check if alias `/usr/local/bin/chrome` is valid  - this is where user could define an alias with additional command line flags

## Mac 

- [x] if spotlight is off, the Chrome detection fails https://github.com/cypress-io/cypress-core-launcher/issues/2
- [ ] add ability to pass path to the browser, rather than a name to detect

**Comment by bahmutov** [comment]
Need to make sure we assign different colors to full names in UI

<img width="870" alt="screen shot 2017-05-24 at 3 53 06 pm" src="https://cloud.githubusercontent.com/assets/2212006/26422783/32426554-4099-11e7-8828-e7f805ca8a86.png">

**Comment by bahmutov** [comment]
Done, launcher is "smarter" trying to fid browsers.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
