### ISSUE TITLE
Handle multiple projects in server

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#512]
* per-project `state.json`
* bundles saved in unique per-project location to prevent collisions

State of Cypress saved in `~/Library/Application\ Support/Cypress/`

Store projects like so:

```
<app-data path>
|- <env>
   |- cache
   |- projects
      |- <app-name + hash>
         | - bundles
            | - spec1.js
            | - spec2.js
         | - state.json
      | - <app2-name + hash>
         | - etc...
```

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
