### ISSUE TITLE
Interactive mode shows pass, run mode shows fail

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#5121]
![19-09-10_18:08::54](https://user-images.githubusercontent.com/14625260/64654230-92cf8580-d3f6-11e9-92ad-9d1415062b5f.png)
![image](https://user-images.githubusercontent.com/14625260/64654262-aa0e7300-d3f6-11e9-9333-787e759bbd95.png)

Simple reproducible:
```js	
describe('suite', () => {
  it('expect fail', () => {})
})

after(() => {
  expect(false).ok
})
```

Cypress: `3.4.1`

**Comment by fingolfinor** [comment]
+1 for this bug (ran into it also)

**Comment by Bkucera** [comment]
@fingolfinor please leave a :+1: on the top comment, it helps us prioritize.

**Comment by Bkucera** [comment]
duplicate of #2296
