### ISSUE TITLE
How to access iframe

### ISSUE THREAD

**Issue by alagiri7** [cypress-io/cypress#5128]
I have created a script for iframe which is working partially, after deposit it redirect to third party URL where we should authorise the payment. Could anyone let me know how to handle this. below i have pasted the script along with third party elements.

```html
<p> Please choose how the ACS would respond: </p> <input type="button" value="AUTHORISE" onclick="chooseOutcome('AUTHORISE')"> 
<input type="button" value="BYPASS" onclick="chooseOutcome('BYPASS')"> 
<input type="button" value="UNAVAILABLE" onclick="chooseOutcome('UNAVAILABLE')"> 
<input type="button" value="NOT_AUTHORISED" onclick="chooseOutcome('NOT_AUTHORISED')">
``` 

and my script is       
```js
// Iframe      
cy.get('iframe', {timeout:100000}).then($iframe => {         
  cy.wrap($iframe.contents().find('body')).as('iFrameBody')     
})    
    
// Enter the Security Code     
cy.get('@iFrameBody', {timeout:100000}).find('#card-selection-cv2').type('885')      // Click Pay now           
cy.get('@iFrameBody', {timeout:100000}).find('.hosted-form-payment').submit()
```

**Comment by alagiri7** [comment]
NA

**Comment by jennifer-shehane** [comment]
I would check our existing issue on iframes https://github.com/cypress-io/cypress/issues/136

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request, but a question.
