### ISSUE TITLE
Change Desktop GUI update banner with messaging about package.json versioning

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#513]
* Remove 'Check for updates' from menu
* Keep 'Update available' banner for both local and global mode
* 'Update' link in banner opens a modal
  - In global mode: tells user to click 'download' link and replace their older version
  - In project mode: explains how to update the version through `package.json`

**Comment by chrisbreiding** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
