### ISSUE TITLE
Videos on the cypress dashboard are not playing completely, just spins - loading spinner

### ISSUE THREAD

**Issue by dtranVAMP** [cypress-io/cypress#5138]
Noticing the recording on the cypress dashboard is not working, just spins

**Comment by jennifer-shehane** [comment]
Hey @dtranVAMP we're investigating this issue currently and will update this issue when there is a fix. 

## Workarounds

- Open the Dashboard in a non-Chrome browser (we believe this is isolated to Chrome)
- Download the video directly. I've posted a GIF below of how to do this. 

![](http://g.recordit.co/jncVlSQy5M.gif)

**Comment by dtranVAMP** [comment]
Thanks!  Yeah definitely does look to just be Chrome, I'm able to watch
just fine with Firefox.

**Comment by jennifer-shehane** [comment]
Our engineering team pushed a fix our for this approximately 9 hours ago. 

The video recordings in the Dashboard should play in Chrome without stalling and also allow you to scrub through the video without any lagging effect.

**Comment by makedirectory** [comment]
Is it possible this issue still exists or came back? I'm on cypress `7.5.0` and using `cypress/browsers:node12.18.3-chrome89-ff86` and the videos are being uploaded but are very jumpy / resemble the image posted above.

**Comment by dwilt** [comment]
I have a similar issue.. sometimes (and in multiple browsers) I can't play videos of certain runs:

![image](https://user-images.githubusercontent.com/1065539/132506757-edb48e30-ecd7-4452-a9b2-0e4906cd3265.png)

Any ideas?
