### ISSUE TITLE
Enable CYPRESS_DOWNLOAD_MIRROR to be used with a static file server

### ISSUE THREAD

**Issue by tomasbjerre** [cypress-io/cypress#5141]
### Current behavior:

When `CYPRESS_DOWNLOAD_MIRROR` is specified Cypress will download the binaries from something like `https://whatever/desktop?platform=OS&arch=ARCH`.

This means we cannot serve these binaries from a static file server. Because of the query parameters.

### Desired behavior:

Change the API so that the file gets downloaded from something like `https://whatever/desktop/platform/:platform/arch/:arc/cypress.zip`.

Such an API can easily be implemented with a simple static file server. Something that is usually easy to setup in corporate environments.

### Steps to reproduce: (app code and test code)

1. Set `CYPRESS_DOWNLOAD_MIRROR` to point at a static file server.
2. Try to create files on this server that will implement the API so that Cypress will use linux binary when on Linux and Windows binary when on Windows.

### Versions

3.4.1

**Comment by Bkucera** [comment]
@tomasbjerre it wouldn't be pretty, but I think you can still name your static files with the query param strings. Let me know if that works for you.

**Comment by tomasbjerre** [comment]
I also "think" it is likely possible, but not easy. And I think it should be easy as I think it is part of solving a very common problem.

This would solve the problem reported in #5036 where users are working on mixed platforms. Some will need the Windows binary and some the Linux binary. With this we could just set the version in `package.json` and have this mirror in `.npmrc` and then the current implementation will pick the binary fit for the current platform.

**Comment by tomasbjerre** [comment]
Tried with Github, does not seem to work.

 * https://bjurr.com/desktop/3.4.1?platform=linux
 * https://github.com/tomasbjerre/bjurrcom/tree/master/desktop

**Comment by NMinhNguyen** [comment]
@Bkucera just curious if the source code for the download server is available so one could easily host it in a corporate environment?

**Comment by ztolley** [comment]
Same. I need to run Cypress on a private network that has a private proxied npm registry with no access to the outside world. The docs mention running a local mirror but no mention of how to do that

**Comment by tomasbjerre** [comment]
I created a tool to deal with this problem:
https://github.com/tomasbjerre/dictator-cypress-example

You would need to clone this repository and publish your own `cypress-dictator` to your private npm repository:
https://github.com/tomasbjerre/dictator-cypress

It uses [dictator builder](https://github.com/tomasbjerre/dictator-builder) to, before `npm install`, copy platform specific zip-files to root of repository and make sure it is pointed at by `.npmrc`.

```json
{
  "message": "Copy linux cypress to cypress.zip",
  "triggers": [
    {
      "runningOnPlatform": ["linux"]
    }
  ],
  "actions": [
    {
      "copyFrom": "linux-x64.zip",
      "target": "cypress.zip"
    }
  ]
}
```

**Comment by mattdsteele** [comment]
We also found a way to make this work with static file servers. We're using Artifactory to host these assets, but it should work more generally.

You'll want to download the .zip files and from Cypress, and upload them to your file server with the version number as the filename.

For example:

* https://example.com/artifactory/mirrored-binaries/cypress/linux-x64/desktop/8.4.0
* https://example.com/artifactory/mirrored-binaries/cypress/win32-x64/desktop/8.4.0

Then, set `CYPRESS_DOWNLOAD_MIRROR` based on your OS and architecture; for example:

```
set CYPRESS_DOWNLOAD_MIRROR https://example.com/artifactory/mirrored-binaries/cypress/win32-x64
```

**Comment by jemerald** [comment]
`CYPRESS_DOWNLOAD_PATH_TEMPLATE` was added since 9.3.0 which should enable this.
