### ISSUE TITLE
cy.setCookie is broken with chrome 77

### ISSUE THREAD

**Issue by bryant-slack** [cypress-io/cypress#5142]
### Current behavior:

![image](https://user-images.githubusercontent.com/53798821/64892242-bd088980-d628-11e9-8ad7-fceb39b94646.png)

### Desired behavior:
![image](https://user-images.githubusercontent.com/53798821/64892338-00fb8e80-d629-11e9-84f5-8319cf4203a6.png)

### Steps to reproduce: (app code and test code)
run the following test: it will fail:
```javascript
/// <reference types="Cypress" />

context('Window', () => {
  beforeEach(() => {
    cy.visit('http://google.com')
  })

  it('cy.window() - can set cookies', () => {
    // https://on.cypress.io/window
    cy.setCookie('cookieKey', 'angelfoobar', {
  		domain: '.google.com',
  		path: '/',
  		httpOnly: true,
  		secure: true,
  	});
  })

})


```

If you remove the domain it works:

```javascript

/// <reference types="Cypress" />

context('Window', () => {
  beforeEach(() => {
    cy.visit('http://google.com')
  })

  it('cy.window() - can set cookies', () => {
    // https://on.cypress.io/window
    cy.setCookie('cookieKey', 'angelfoobar', {
  		path: '/',
  		httpOnly: true,
  		secure: true,
  	});
  })

})


```

NOTE: this works fine on chrome 76. it broke with chrome 77 upgrade.
### Versions

Max OS 10.14.6
Chrome 77
Cypress 3.4.1

**Comment by flotwig** [comment]
Hey @bryant-slack, the error you're experiencing comes from Chrome's [Cookies API](https://developer.chrome.com/extensions/cookie), which means something is wrong with the supplied cookie's format.

Have you tried changing `domain: '.google.com'` to `domain: 'google.com'`? The leading dot may be invalid in this setting.

**Comment by jennifer-shehane** [comment]
@flotwig Leading `.` should be ignored per the spec though https://tools.ietf.org/html/rfc6265#section-4.1.2.3 So I doubt that it's the domain format. 

Previous convo: https://github.com/cypress-io/cypress/issues/1896#issuecomment-515379209

**Comment by flotwig** [comment]
Yeah, but I think the Chrome extensions API specifically does not follow that convention, instead setting a HostOnly cookie only if the `domain` option is missing entirely. It's worth a try I think.

**Comment by bryant-slack** [comment]
Just going on a website and looking at the cookies it seems that they are able to set the cookies with the `.` in front on chrome 77

Example on github: 
![image](https://user-images.githubusercontent.com/53798821/65220704-2f85c900-da70-11e9-8f86-2f1dc325b68b.png)


I can try it without the `.` and if that works it should unblock me, but this could still be a bug?

**Comment by flotwig** [comment]
The DevTools display the cookies in the Chrome DevTools Protocol format, which does use a leading `.` to denote non-HostOnly cookies: https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Cookie

Chrome extensions API uses a `HostOnly` boolean to denote that: https://developer.chrome.com/extensions/cookies#type-Cookie

Try without the `.`. If that works, this is still probably something we should clean up for the user so that the behavior is more expected.

**Comment by bryant-slack** [comment]
this looks like it works for us if we remove the `.`

**Comment by flotwig** [comment]
Nice! It does work fine with the `.` on Chrome 76, just not Chrome 77?

**Comment by bryant-slack** [comment]
Yes that is correct, before we had the `.` there and after chrome 77 upgrade we started noticing this part starting failing as the above example shows.  If you run the above example on 76 it works fine.
