### ISSUE TITLE
npm ERR! when running cypress from npm scripts object command in package.json

### ISSUE THREAD

**Issue by ruvengam** [cypress-io/cypress#5143]
I have several Cypress projects, all of them have this issue.
Both on windows an Linux OS.

In my main project I was using npx cypress run to run tests.
after adding a reporter I wanted to start using package.json npm scripts object to run a build 
and produce reports.
The problem is when any of the tests fail after the (Run Finished) report table 
npm exit with an error.

I set up an example cypress project without any modification to test this behavior.

### Current behavior:
when using:
`npm run cy:run` to run tests
If any of the tests fail, NPM exits with error.
The NPM error is outputted even if I try to run a file that doesn't exist:
npm run cy:run -- -s cypress/integration/examples/file_dose_not_exist.js
Cypress tell me:
"Can't run because no spec files were found..."
and then the error:

**package.json:**
```
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cy:open": "cypress open",
    "cy:run": "cypress run "
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^3.4.1"
  }
}
```
**CLI Error:**
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 cy:run: `cypress run "-s" "cypress/integration/examples/act*.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@1.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Data\Users\reuve-ga\AppData\Roaming\npm-cache\_logs\2019-09-15T06_28_18_534Z-debug.log
```

**Debug Log:**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Data\\Users\\reuve-ga\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cy:run',
1 verbose cli   '--',
1 verbose cli   '-s',
1 verbose cli   'cypress/integration/examples/act*.js' ]
2 info using npm@6.8.0
3 info using node@v10.15.1
4 verbose run-script [ 'precy:run', 'cy:run', 'postcy:run' ]
5 info lifecycle example@1.0.0~precy:run: example@1.0.0
6 info lifecycle example@1.0.0~cy:run: example@1.0.0
7 verbose lifecycle example@1.0.0~cy:run: unsafe-perm in lifecycle true
8 verbose lifecycle example@1.0.0~cy:run: PATH: D:\Data\Users\reuve-ga\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\tmp\example\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files (x86)\WinMerge;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\reuve-ga\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\reuve-ga\AppData\Local\Programs\Python\Python37-32\;C:\Users\reuve-ga\AppData\Local\Microsoft\WindowsApps;C:\Users\reuve-ga\AppData\Roaming\npm;C:\Users\reuve-ga\AppData\Local\Programs\Microsoft VS Code\bin;C:\dev\apache-maven-3.6.0\bin;
9 verbose lifecycle example@1.0.0~cy:run: CWD: C:\tmp\example
10 silly lifecycle example@1.0.0~cy:run: Args: [ '/d /s /c',
10 silly lifecycle   'cypress run "-s" "cypress/integration/examples/act*.js"' ]
11 silly lifecycle example@1.0.0~cy:run: Returned: code: 1  signal: null
12 info lifecycle example@1.0.0~cy:run: Failed to exec cy:run script
13 verbose stack Error: example@1.0.0 cy:run: `cypress run "-s" "cypress/integration/examples/act*.js"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Data\Users\reuve-ga\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Data\Users\reuve-ga\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid example@1.0.0
15 verbose cwd C:\tmp\example
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "D:\\Data\\Users\\reuve-ga\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "cy:run" "--" "-s" "cypress/integration/examples/act*.js"
18 verbose node v10.15.1
19 verbose npm  v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error example@1.0.0 cy:run: `cypress run "-s" "cypress/integration/examples/act*.js"`
22 error Exit status 1
23 error Failed at the example@1.0.0 cy:run script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
### Desired behavior:
Running cypress as NPM package.json commands will not result in an error.

### Steps to reproduce: (app code and test code)
Install cypress.
Set `"cy:run": "cypress run"` in package.json
Change any test file in the examples folder to faile.
Do: `npm run cy:run`

### Versions
Cypress: 3.4.1
Windows 10
Browser: electrone

**Comment by ruvengam** [comment]
I have setup fresh install of Cypress 3.4.1 on my home PC (Win 10, Node: v10.5.0, NPM: 6.1.0),
No configuration made (except the package.json scripts command).
I get the same error if I run "npm run cyrun" this time I omitted the  : in cy:run
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypresstester@1.0.0 cyrun: `cypress run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypresstester@1.0.0 cyrun script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anna & Reuven\AppData\Roaming\npm-cache\_logs\2019-09-16T11_15_46_763Z-debug.log
```

**Comment by bahmutov** [comment]
@ruvengam does it run when you don't pass spec mask? Like the simple `npm run cy:run`?

**Comment by ruvengam** [comment]
No, the only way it finishes without an error is if I us:
`npx cypress run` 
Got the same issue on Ubuntu 18.04, Node: v10.16.3, NPM: 6.8.0

Every time I use packge.json scripts command, only if a test fails I got this error.
If all tests pass I don't get the npm ERR

**Comment by bahmutov** [comment]
Wait, @ruvengam - let me get this clear

- when tests pass, NPM exits without an error message
- when tests fail you see 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypresstester@1.0.0 cyrun: `cypress run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypresstester@1.0.0 cyrun script.
```

?

This is expected - Cypress fails the tests, exits, then NPM that calls Cypress when you do `npm run cyrun` receives non-zero exit code and prints its own "command failed" error message.

**Comment by ruvengam** [comment]
Yes you are correct,
So if Cypress fails the test NPM will exit with an error?

I want to use post run scripts to be executed after Cypress run is over to merge and create reports.
So I do `"postcy:run": "npm run visualreport"`, because NPM exits with an error it is not executing the post command.

I understand the non-zero exit code passed to NPM will trigger NPM error message,
On the other hand there was no error in Cypress execution and all test were executed, even if some of them failed.
The test are supposed to be isolated in Cypress.

Is it possible to overcome this issue?

**Comment by bahmutov** [comment]
The NPM error behavior is expected and cannot be changed. But most CIs allow you to run commands on previous command's failure. If you really want to get the results of Cypress run yourself and do additional processing, then you can call it via its https://on.cypress.io/module-api - it won't fail if there are failed tests, it is up to you.
