### ISSUE TITLE
Unable to Select values from cy.select() command when there are two Select tag on the same page

### ISSUE THREAD

**Issue by jatinaggarwal10** [cypress-io/cypress#5145]
### Current behavior: If a user tries to select a value then this error comes -

![image (4)](https://user-images.githubusercontent.com/24910090/64919008-579cd000-d7c3-11e9-90c1-c09243b88348.png)

Original Website page-

![image](https://user-images.githubusercontent.com/24910090/64919048-f6293100-d7c3-11e9-9449-be2bf201c713.png)

### Steps to reproduce: (app code and test code)- 1-Go to https://insider.in/pune

3. Open the page of the first event under the "FEATURED EVENTS" section. For e.g. Bacardi NH7 Weekender 2019, Pune.
4. Once you are on the event page (EDP as we call it), click on the "BUY NOW" button.
5. You will be asked to choose between options such as "Tickets", "F & B Coupons". Click on the "Buy" button for "Tickets".
6. Now choose 1 quantity of the first option. Currently it shows "Phase 2 | Under 21 Season Ticket". Click "Buy".

Code which I have written -
```js
describe('The Home Page', function() {
  it('Visit the Insider Page', function() {
    cy.visit('https://insider.in/pune')
    
    cy.contains('Bacardi NH7 Weekender 2019, Pune').click()
    cy.contains('BUY NOW').click()
    
    cy.wait(1000)
    cy.scrollTo('top') 
    cy.wait(500)
   cy.contains('button', 'Book').click()
   
    cy.scrollTo('top') 
   cy.get('select').select('1')
    
  })
})
```

I have tried almost all your cy.select() command given in your Documentation but still getting the same issue.

### Versions

I'm using Windows and I'm testing on Chrome Browser

**Comment by nitzanashi** [comment]
The error talks for itself 
```
CypressError: cy.select() can only be called on a single <select>. Your subject contained 2 elements.
```

Because you have more than one select element in your page, cypress don't know to which one of the this elements you want to apply the action, therefore throwing an error instead.

You should add [eq](https://docs.cypress.io/api/commands/eq.html#Syntax) to your code
for example if you want to check the first select element write:
 `cy.get('select').eq(0).select('1');`
