### ISSUE TITLE
config files not loaded/used correctly

### ISSUE THREAD

**Issue by elPrusso** [cypress-io/cypress#5147]
### Current behavior:

`cypress/config/abc.json`  Folder 

Try to run environment file like this 

`node_modules/.bin/cypress run --env configFile=abc`

In config file there is a parameter for `"testFiles": "abc/**"`, but the `abc.json` in not called/used correctly. Instead all tests are loaded (not only the specific ones in the `"abc/"` folder).

In Version 3.3.2 all works fine. The config file is correct, cause if i rename and replace it to `cypress.json` the correct test files are loaded. 

### Desired behavior:
config files should work again, like in Version 3.3.2 ;-)

### Versions

Cypress 3.4.1 on Windows 7

**Comment by jennifer-shehane** [comment]
Can you provide a repo of this? I'm having a hard time following where the files are located and how they're being called and how this every relates back to 'testFiles' in Cypress and how they are run.

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
