### ISSUE TITLE
Need better errors for rejected promises from the app code

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#5148]
Cypress v3.4.1
Recreate using branch `wait-on-failed-app-promise` in https://github.com/cypress-io/cypress-test-tiny/tree/wait-on-failed-app-promise

## Application code

Here is the `index.html`

```html
<body>
  <p>Example app with promises</p>
  <script>
    window.app = {
      resolves () {
        return new Promise((resolve) => {
          setTimeout(resolve, 1000)
        })
      },
      rejects () {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject(new Error('App says no'))
          }, 1000)
        })
      },
      rejectsWithUndefined () {
        return new Promise((resolve, reject) => {
          setTimeout(reject, 1000)
        })
      }
    }
  </script>
</body>
```

## Resolved promise

If we invoke an application method which returns a promise, the test waits for the promise to resolve before it continues, all good

```js
it('resolves', () => {
  cy.visit('index.html')
  // should wait for the promise returned from
  // the "window.app.resolves()" call to resolve
  cy.window()
    .its('app')
    .invoke('resolves')
})
```

<img width="1278" alt="Screen Shot 2019-09-16 at 11 25 41 AM" src="https://user-images.githubusercontent.com/2212006/64971524-d3575500-d875-11e9-9681-8abe766d973e.png">

## Promise rejected with an Error object

Test

```js
it('rejects', () => {
  cy.visit('index.html')
  // should wait for the promise returned from
  // the "window.app.resolves()" call to reject and fail the test
  cy.window()
    .its('app')
    .invoke('rejects')
})
```
The error is kind of confusing
<img width="1279" alt="Screen Shot 2019-09-16 at 11 26 20 AM" src="https://user-images.githubusercontent.com/2212006/64971597-ee29c980-d875-11e9-896d-63c1d21491e6.png">

This might get better when we get error stacks and better error messages

### Promise rejected without an error argument

Notice we are calling an app method that just calls `reject()`
```js
it('rejects with undefined', () => {
  cy.visit('index.html')
  // should wait for the promise returned from
  // the "window.app.resolves()" call to reject and fail the test
  cy.window()
    .its('app')
    .invoke('rejectsWithUndefined')
})
```
The error is really weird, even if it is correctly saying what has happened

<img width="1282" alt="Screen Shot 2019-09-16 at 11 27 52 AM" src="https://user-images.githubusercontent.com/2212006/64971810-3ba63680-d876-11e9-989f-e655ed421b6b.png">

I would love to see a less confusing error, especially because it does not print the error stack there (there is no error)

**Comment by timvahlbrock** [comment]
Regarding Promise without an error object:

If a promise is rejected with `Promise.reject(undefined)` and isn't handled, Cypress 8.4.1 still assumes that the reason for an unhandled promise rejection event still is an error object and tries to read "message" which fails, since reason is undefined. The user the is prompted with:

>The following error originated from your application code, not from Cypress.
>
>  \> Cannot read properties of undefined (reading 'message')

which is quite misleading, since in fact there was an error in the application, but the reason was not that message could not be read. It also came to notice that Cypress seems to register 'unhandledrejection' listener before the application has a chance, so the application is unable to take care of unhandled rejections itself, but I guess that is a different issue.
