### ISSUE TITLE
unhelpful error message when taking screenshot of element with zero height

### ISSUE THREAD

**Issue by egrubbs** [cypress-io/cypress#5149]
### Current behavior:

`cy.get(element).screenshot()` displays a very confusing error if the element has zero height.

```
TypeError: Cannot destructure property `duration` of 'undefined' or 'null'.
```

![image](https://user-images.githubusercontent.com/477907/64983051-3f8d8500-d885-11e9-994d-b2051b72e585.png)

#### The code that is causing the confusing error

`numScreenshots` ends up being zero when `elPosition.height` is zero.

https://github.com/cypress-io/cypress/blob/c0962511f045f07f2dc255b251ac251b2d8ae718/packages/driver/src/cy/commands/screenshot.coffee#L138

This causes `_.last(results)` to return `undefined`.

https://github.com/cypress-io/cypress/blob/c0962511f045f07f2dc255b251ac251b2d8ae718/packages/driver/src/cy/commands/screenshot.coffee#L99

Which causes `takeScreenshot().then()` to receive an undefined `props` parameter that it cannot destructure with `{ duration, path, size } = props;`.

https://github.com/cypress-io/cypress/blob/c0962511f045f07f2dc255b251ac251b2d8ae718/packages/driver/src/cy/commands/screenshot.coffee#L357

### Desired behavior:

`cy.get(element).screenshot()` should report an error that the element has zero height.

It is also extremely difficult to troubleshoot an error like this because bluebirdjs doesn't automatically log exceptions, so I have no idea where the code in the error message existed.

It appears that bluebirdjs has events for unhandled errors. It would be great if Cypress provided a filename and line number of the where the error is occurring in the Cypress log as well as a stack trace in the browser console.

http://bluebirdjs.com/docs/api/error-management-configuration.html

```js
process.on("unhandledRejection", function(reason, promise) {
});
process.on("rejectionHandled", function(promise) {
});
```

### Steps to reproduce: (app code and test code)

You can recreate the confusing error message by trying to take a screenshot of a `span` with zero height.

```js
cy.get('.zero_height_element').screenshot();
```

### Versions

Cypress 3.4.1
Ubuntu 16.04 & 18.04

**Comment by jennifer-shehane** [comment]
@egrubbs Thanks for the thorough debugging work. I can recreate this as you described. 

```html
<!DOCTYPE html>
<html>
<body>
    <div class='zero_height_element' style='height: 0'>abc</div>
</body>
</html>
```

```js
it('screenshot zero height el', () => {
  cy.visit('index.html')
  cy.get('.zero_height_element').screenshot();
})
```

<img width="459" alt="Screen Shot 2019-09-17 at 1 18 11 PM" src="https://user-images.githubusercontent.com/1271364/65064089-a70f0780-d94d-11e9-89c2-43383c816370.png">

We would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.
