### ISSUE TITLE
Cypress >= 3.3.0 having issues with click and application routing

### ISSUE THREAD

**Issue by sardell** [cypress-io/cypress#5152]
### Current behavior:

After upgrading my version of Cypress from 3.2.0 to 3.4.1, I noticed that my Cypress tests are randomly failing. After recording video of the tests, it looks like using click() on a link sometimes leads to my application quickly routing to the desired location and routing back to the previous route before the tests have ran (I'm using Angular 7 here, FYI). This leads to failures like waiting for xhr requests, not being able to find elements, etc that are supposed to happen after the expected route change. Below is a gif I took of a Cypress video recording. You can see the desired route `/pcap` flash very quickly before redirecting back :

![cypress-failure](https://user-images.githubusercontent.com/7304869/65031576-c2741580-d941-11e9-8ad5-305c29d3717e.gif)

### Desired behavior:

When clicking on a link, the url/route should change (in my case, I'm using Angular so the route should update). This is how the tests behave using Cypress 3.2.0 (which uses Electron 59). I know this correlation does not necessarily mean causation, but this is the best I can come up with at this point.

### Steps to reproduce: (app code and test code)

Important note: We've only been able to reproduce this error on macOS running Electron 61 headless.

* Clone this branch locally: https://github.com/sardell/metron/tree/METRON-2243
* From the root of the project, navigate to `metron-interface/metron-alerts` and run `npm ci` to install dependencies. If you then run `npm list cypress`, you'll notice that the version is 3.4.1.
* Run `npm run cypress:ci`. This builds the application dist folder, starts a small server for Cypress to run against and then runs the Cypress tests. You will see tests fail. If you run it multiple times, you will notice the failure is random and happens to different tests each time.
* To see passing tests, run the same steps above against this PR branch: https://github.com/apache/metron/pull/1513. The only difference is I downgraded the release of Cypress to 3.2.0 (which uses Electron 59)

If you set the cypress configuration to record video, you'll notice similar routing behavior to what is shown in the above gif. 

### Versions
Cypress: >= 3.3.0
OS: macOS
browser: Electron 61

**Comment by jennifer-shehane** [comment]
I appreciate being provided a repo to run this on, but this is a lot of cypress tests and code, is there any way you can narrow it down to a single test that is failing more often than not? I don't even know which test I'm supposed to be focusing on. 

I ran the tests multiple times and they always passed. Please comment if you have a smaller repro example.
