### ISSUE TITLE
TypeError: cy.matchScreenshot is not a function

### ISSUE THREAD

**Issue by Kevdog777** [cypress-io/cypress#5154]
### Current behavior:

I am getting the error: `TypeError: cy.matchScreenshot is not a function` when I try to use the package `cypress-match-screenshot`. I followed the information from: https://www.npmjs.com/package/cypress-match-screenshot. But this has given me the above error.

### Desired behavior:

As per the webpage: https://www.npmjs.com/package/cypress-match-screenshot, I would like Cypress to take an image of the webpage and then on the next run, it will compare the image to the new image. Basically to match the content of the webpage to the image and vice versa.

#### cypress/support/commands.js
```js
import { register } from 'cypress-match-screenshot';

register ();
```

#### cypress/Support/Screenshots.js
```js
describe('Screenshots', function () {
    it('Should match Postcode screenshot', function () {
        cy.visit('http://www.afd.co.uk/support/manuals/windows/postcode/');
        cy.matchScreenshot('Postcode Manual Screenshot');
    });
    it('Should match Postcode Plus screenshot', function () {
        cy.visit('http://www.afd.co.uk/support/manuals/windows/postcode-plus/');
        cy.matchScreenshot('Postcode Plus Manual Screenshot');
    });
});
```

### Versions

```js
"dependencies": {
    "cypress-match-screenshot": "^1.1.0"
```

**Comment by Kevdog777** [comment]
OK, I had put the above code, from `command.js` in the wrong path.

I am now getting this error:

```
CypressError: cy.exec('mkdir -p cypress/match-screenshots/new') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
The syntax of the command is incorrect.
```

**Comment by frazboyz** [comment]
You should report your issue to the github of the package, this is not a cypress maintained package.
https://github.com/julianburr/cypress-match-screenshot

**Comment by Kevdog777** [comment]
I have reported the issue on here: https://github.com/julianburr/cypress-match-screenshot/issues/22

**Comment by Kevdog777** [comment]
Just as information, this error is actually a Cypress issue: https://github.com/cypress-io/cypress/issues/789
