### ISSUE TITLE
XHRs sometimes not caught right after page load

### ISSUE THREAD

**Issue by oreqizer** [cypress-io/cypress#516]
* Operating System: macOS Sierra (though the same happens when running in Docker Ubuntu)
* Cypress Version: 19.2
* Browser/Browser Version: Chrome 58.0.3029.110 (64-bit)

### Are you requesting a feature or reporting a bug?

Bug

### Current behavior:

Cypress _most of the time_ (~85%) doesn't catch outcoming XHRs that fire right after a page load. They should be logged and replaced with stubs if available.

### Expected behavior:

Cypress should reliably catch outcoming XHRs and maybe stub them.

### How to reproduce the current behavior:

* create a stub server
* create a page that fires a XHR request right after the page load
* repeat the test a couple of times, the XHRs should not be caught most of the time

#### Test code:

```js
Cypress.addParentCommand("searchMock", () => {
	cy
		.server()
		.route(/locations/, 'fx:locations.json').as('locations')
})

Cypress.addParentCommand("fetchVisit", (path, options) => {
	cy
		.visit(path, Object.assign({}, options, {
			onBeforeLoad: win => { delete win.fetch },  // replacing it with a polyfill
		}))
})

Cypress.addParentCommand("searchVisit", (path, options) => {
	cy
		.searchMock()
		.fetchVisit(path, options);
});

// ...later in a test
cy
  .searchVisit("/en/")
  .wait('@locations')  // nope, never fired
```

### Additional Info (images, notes, stack traces, etc)

OK run:
<img width="385" alt="screen shot 2017-05-26 at 15 32 06" src="https://cloud.githubusercontent.com/assets/11172408/26496695/deb41fc2-4228-11e7-974b-5a6ae1456c75.png">

Nope:
<img width="385" alt="screen shot 2017-05-26 at 15 33 13" src="https://cloud.githubusercontent.com/assets/11172408/26496696/deb9378c-4228-11e7-9644-331038fc583a.png">

**Comment by oreqizer** [comment]
turns out it wasn't Cypress' fault, but this little script here:

```
if (caveman) {
	var script = document.createElement("script")
	script.src = window.GLOBALS.POLYFILLS
	script.async = false
	document.head.appendChild(script)
}
```

was racing with our bundle. A good experience, though!

**Comment by brian-mann** [comment]
These kinds of issues make me happy :-)
