### ISSUE TITLE
Bug: Cypress route doesn't match 100% of the time

### ISSUE THREAD

**Issue by nWidart** [cypress-io/cypress#5161]
### Current behavior:

```js
  
context('Cy Server Randomness', () => {
  beforeEach(() => {
    cy.visit('https://hub.docker.com/_/php?tab=tags')
  })

  it('something', () => {
    cy.server();
    cy.route("get", "https://hub.docker.com/api/content/v1/products/images/php", "fixture:php.json")
      .as('dockerPhp');

    cy.get('[data-testid=productHeader_productName]').should('contain', "php-mocked");
  });
});
```

We mock a XHR request using `cy.route()` and returning a fixture, which doesn't match 100% of the time.

A successful match :
![image](https://user-images.githubusercontent.com/882397/65132613-8607ee80-da01-11e9-98dc-532f60416954.png)

A failing match:
![image](https://user-images.githubusercontent.com/882397/65132643-915b1a00-da01-11e9-9325-75818c2fd125.png)

### Desired behavior:

It should match 100% of the time.

### Steps to reproduce: (app code and test code)

1. `git clone git@github.com:nWidart/cypressServerMocks.git`
2. `yarn`
3. `yarn cypress:open`
4. Refresh a few times until it fails. The test expects to find a title that mocked in the fixture. So if the route doesn't match, it won't match the mocked title and instead retrieve real title from docker hub.
***
1. `git clone git@github.com:nWidart/cypressServerMocks.git`
2. `yarn`
3. `yarn cypress:run`
4. Re-run a few times until it fails. The test expects to find a title that mocked in the fixture. So if the route doesn't match, it won't match the mocked title and instead retrieve real title from docker hub.

### Versions

- `3.4.1`
- `3.2.0`

**Comment by ryan-snyder** [comment]
So with the code you have, I was able to get it to fail but by changing the code to 
```js
context('Cy Server Randomness', () => {
  beforeEach(() => {
    cy.server();
    cy.route("get", "https://hub.docker.com/api/content/v1/products/images/php", "fixture:php.json")
      .as('dockerPhp');
    cy.visit('https://hub.docker.com/_/php?tab=tags')
  })

  it('something', () => {
    cy.wait('@dockerPhp')
    cy.get('[data-testid=productHeader_productName]').should('contain', "php-mocked");
  });
});
```
It works every time.

Explanation:
The majority of the time you should set up your server and your route in the beforeEach block. This is just good practice to ensure that there's no possible way cypress misses your route. As well, You should wait for the request to happen before doing any assertions so that If the test fails you know it's because of the request not because of the assertion itself

**Comment by jennifer-shehane** [comment]
As @ryan-snyder mentioned, you should always set up `cy.route()` before `cy.visit()` - think of `cy.route()` as just a listener - if the request happens before that is defined it will never be caught.
