### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by sensuraj92** [cypress-io/cypress#5178]
Only in cypress initiated browser i am getting below error, as soon as login to out webapplication.

tried several things but not working can you please suggest what can be done here

'TypeError: Right-hand side of 'instanceof' is not an object' 

![cy_error](https://user-images.githubusercontent.com/41458305/65370630-c329e600-dc78-11e9-9519-f49f8706b381.PNG)

**Comment by sensuraj92** [comment]
Can someone please look into this issue ?

**Comment by RandallKent** [comment]
@sensuraj92 How the behavior you are seeing can be reproduced?

**Comment by jennifer-shehane** [comment]
@sensuraj92 As noted by @RandallKent, we need a fully reproducible example provided that we can run on our end to investigate to see the error - including the test code you are running. Screenshots, stacktraces, any logs and errors are also helpful. Thanks.

**Comment by sensuraj92** [comment]
Hello Jennifer,

 Issue is reproducible only at my end, since it is an private application,

I have written simple code of entering user name , password and click logon
button. Which takes inside the application, where no methods, properties
are getting loaded.

Even simple this.id returns undefined in cypress browser console, which
perfectly works with normal browser.

Regards,
Suraj A

**Comment by sensuraj92** [comment]
spec file
describe('My First Cypress Test Suite',function()
{ 
  
  it('My First Test Case',function() {
     
    cy.visit("http://localhost:9500/login")               
    cy.get('#userNameTxt').type('ABC')
    cy.get('#passwordTxt').type('Password0!')
    cy.get('.login-links').find('.login-button').click()
    cy.wait(20000)
    cy.get('#app-picker').click({force:true})

**Comment by sensuraj92** [comment]
Hello Team,

Any update on this issue please ?

Thanks & Regards.
Suraj A

**Comment by oak-wildwood** [comment]
In order for us to be able to help with this, we'll need a fully reproducible example. I'd suggest trying to create a small example as either a zip file or github repo with minimally reproducible code. Without having access to your system we can't really debug this.

**Comment by sensuraj92** [comment]
-- Please reply above this line --


            Hi Suraj,

I've read the github issue and responded there with this response: 

In order for us to be able to help with this, we'll need a fully
reproducible example. I'd suggest trying to create a small example as
either a zip file or github repo with minimally reproducible code.
Without having access to your system we can't really debug this
without a reproducible example.
- Oak

 How would you rate my reply?

**Comment by sensuraj92** [comment]
Hi Team,

I have checked with my technical team,
 they are asking to **write a page with iframe having some Js that refers to a variable in top**.
since it is a private application, i am not getting any other option.
if anyone can take a call with screen sharing option is appreciated.

**Comment by jennifer-shehane** [comment]
@sensuraj92 We do not offer screen sharing. 

Issues in our repo are only for bugs that we can reproduce. Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example of the bug and we will reopen the issue.

**Comment by AStoker** [comment]
@sensuraj92, did you ever resolve this? I'm running into it now while migrating our Angular application. It's failing in some node module called jsonwebtoken/sign.js. It's trying to import `KeyObject` from `crypto`, but it's returning undefined, which breaks the check later on in the module
``` js
if (secretOrPrivateKey != null && !(secretOrPrivateKey instanceof KeyObject)) {
```

EDIT: I see the bot automatically moved this into Triage. Probably doesn't need to be changed yet :) 

EDIT 2: Yeah, our issue is that a library was using the `crypto` library which is a Node specific library. Previous versions of webpack pollyfilled this, but not anymore, hence why it's breaking now (related issue: https://github.com/auth0/node-jsonwebtoken/issues/885). So likely not a Cypress issue, but rather a library issue. Writing this here for future wanderers seeking answers.
