### ISSUE TITLE
Cannot combine within, should, and contains commands as expected

### ISSUE THREAD

**Issue by erwinheitzman** [cypress-io/cypress#5183]
### Current behavior:

Taken this example:
```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
cy.contains(`span`, `Hello World!`).should(`exist`);
```
The first assertion passes but the second assertion fails. This is because it looks for `article span` instead of `span`.

### Desired behavior:

Taken this example:
```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
cy.contains(`span`, `Hello World!`).should(`exist`);
```
I expect that it looks for `span` instead of `article span` and I expect both assertions to pass.

### Steps to reproduce: (app code and test code)

```html
<article class='post'>
    <h1>My Blog Post</h1>
</article>

<div>
    <span>Hello World!</span
</div>
```

```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
cy.contains(`span`, `Hello World!`).should(`exist`);
```

### Versions

Cypress: 3.4.1
OS: MacOS Mojave 10.14.5
Browser: Electron 61 + Chrome 77

**Comment by ryan-snyder** [comment]
The way you have it written it will not look for `span` instead of `article span`. If you rewrite as
```
cy.get('article').within(() => {
   cy.get('h1')).should('have.text', 'My Blog Post');
   cy.contains('span', 'Hello World!').should('exist');
}
```
The reason for this is that in js if you have a function with no `{}` and one return statement, js assumes that the next line after is not part of that function. For example:
```
somefunction = () => return "something";
```
With cypress, `cy.get().should()` is considered a return statement so you have to wrap it in curly braces

**Comment by jennifer-shehane** [comment]
I can recreate this - this is not the documented behavior of these commands. This seems possibly related to these 2 issues about incorrect scope: https://github.com/cypress-io/cypress/issues/4757 https://github.com/cypress-io/cypress/issues/4921

```html
<!DOCTYPE html>
<html>
<body>
<article class='post'>
    <h1>My Blog Post</h1>
</article>
<span>Hello World!</span> 
</body>
</html>
```

```js
it('scope', () => {
  cy.visit('index.html')
  cy.get('article').within(() => {
    cy.get('h1')
  })
  .should('have.text', 'My Blog Post');
  cy.contains('Hello World!').should('be.visible');
})
```
