### ISSUE TITLE
Broken method setCookie or document.cookie

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#5198]
### Current behavior:

Can't set a cookie for a browser to recognize as the login user. The cookie should be a string with the format:

`a41c0f40492c7a0ce155e4fde1d800a9; Path=/XXX-crm-api; HttpOnly
`

I tried both methods - setCookie and document.cookie. I do not see the cookie in browser memory if I set specified path other than "/'. If the path is not specified the cookie does not work properly. 

![image](https://user-images.githubusercontent.com/25055105/65584581-65034880-df81-11e9-9263-9baf71c1e552.png)

![image](https://user-images.githubusercontent.com/25055105/65586044-c4faee80-df83-11e9-9e6f-bc1a2e89fa3d.png)

Here I left the path empty, but as you can see Cypress ads "." before the domain. 

### Desired behavior:

Cookie is set properly and app redirects to the main site as a logged user. Test passes. 

### Steps to reproduce: (app code and test code)
login_using_cookie.js:

```js
describe('login using token', () => {
        it('should successfully log into our app', () => {
          Cypress.Cookies.debug(true)
          cy.loginViaCookie()
            .then(() => {
              cy.visit('/')
              cy.get('[class="icon-people"]').click()
            })
        });
}

```

commands.js:

```js
Cypress.Commands.add('loginViaCookie', () => {
    Cypress.log({
        name: 'loginViaCookie'
    })

    return cy.request({
        method: 'POST',
        url: 'http://lab2.YYY:8080/XXX-crm-api/login',
        headers: {
            "Content-Type": "application/json"
        },
        body: {
            username: "a@admin.com",
            password: "Cypress111"
        },
    })
        .then((resp) => {
             //use document.cookie or setCookie
            // document.cookie = `authtoken=${resp.body.accessToken};path=/XXX-crm-ap;httpOnly: true`
            cy.setCookie('authtoken', resp.body.accessToken, {Path='/XXX-crm-api', httpOnly: true})
        })
})
```

### Versions

Cypress v3.4.1
Chrome v76
Electron v61

**Comment by must-git-good** [comment]
I'll just +1 that setting cookies seems to have changed (broken) without us changing any code or Cypress versions. 

In my case the error is 'TypeError: Cannot read property 'replace' of undefined [even though we are successfully getting a token that should be set as a cookie.  

Programmatic login DOES seem to work on Electron, but is broken in Chrome, and happens across our local systems but not on our CI (which is Chrome-pinned).

So it feels like something changed in how Chrome assigns cookies?

**Comment by flotwig** [comment]
Related: #5142 (changes between chrome 76 => 77)

**Comment by must-git-good** [comment]
Thanks for the link, flotwig. I'll dig into that ticket and see if it resolves our issues.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
