### ISSUE TITLE
cy.contains() should log found element when el found but options don't 

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#52]
If an element within `cy.contains()` is found, but does not meet the requirements of the options, the element found should be shown in the `applied to` area of the console. Currently when I click to log the element, it shows the `applied to` as the contain's scoped DOM element.

**Example Code**
```coffee
it"does not display Back button", ->
  cy.get("#form-header-region").contains("Back", {visible: false})
```

**Commands Log**
<img width="522" alt="screen shot 2015-07-06 at 1 56 37 pm" src="https://cloud.githubusercontent.com/assets/1271364/8529380/9709e852-23e7-11e5-8c06-4ae42e822f7f.png">

**Console**
<img width="402" alt="screen shot 2015-07-06 at 1 59 53 pm" src="https://cloud.githubusercontent.com/assets/1271364/8529382/9baf1b20-23e7-11e5-9d0b-a85e1b96d08f.png">

**Comment by brian-mann** [comment]
Fixed in [`0.9.4`](https://github.com/cypress-io/cypress/wiki/Changelog#094-07062015).
