### ISSUE TITLE
Routing pattern matching

### ISSUE THREAD

**Issue by monalisasahoo19** [cypress-io/cypress#5200]
I am looking to mock an api with few routing options.

Below is the route option.
```js
cy.route({
  method: 'GET',      
  url: 'https://api.foo.com/location/pathsearch/v1/airports*',    
  response: []        
})

```
https://api.foo.com/location/pathsearch/v1/airports?queryFrom=SIN -- This works

https://api.foo.com/location/pathsearch/v1/airports/SIN?queryTo=LON -- Doesn't work

Even when I tried to alter the url pattern to below then both of them fails while mocking and can't match the urls.
 url: 'https://api.foo.com/location/pathsearch/v1/airports[/?]'

Can It be any generic glob pattern which would work for both the patterns

**Comment by ryan-snyder** [comment]
I would look at https://docs.cypress.io/api/utilities/minimatch.html#Syntax and try out the two urls against the various patterns.

**Comment by jennifer-shehane** [comment]
Agree with @ryan-snyder
