### ISSUE TITLE
[BUG] Cypress GUI Window scrolls steps out of view when viewing pinned steps. 

### ISSUE THREAD

**Issue by ChaseBig** [cypress-io/cypress#5202]
## Current behavior:

While a test is running and while reviewing test steps after they've completed, the intended element being fetched is highlighted in the GUI browser window to show you which specific element is being found. 

The problem is that the element being fetched/highlighted is always out of view. The screenshot below shows a `cy.get` step I pinned following the completion of the test. 

You'll see that the highlighted/focused element being found is just out of view/reach. This issue does not affect cypress' ability to interact with the elements, though, even if they're visibly out of view. 

Cypress' scroll feature automatically scrolls to the found element location but that location is not in view. This makes test debugging frustrating sometimes when you're trying to view a multi-click feature, such as a dropdown (click dropdown container, select dropdown option, dropdown menu closes automatically). 

Screenshot: (all boxes in black were added for privacy, though I don't think anyone cares anyway lol)
<img width="1450" alt="Screen Shot 2019-09-25 at 9 27 55 AM" src="https://user-images.githubusercontent.com/10504626/65612867-a2b0a300-df7a-11e9-829a-f4443beefa67.png">

### Desired behavior:

I just want the pinned element to be in-view automatically instead of it being out of view. I want the cypress browser GUI to snap scroll to the selected element and that the entire element would be in view as if I were using it as a real person. Focusing on an element that isn't in view of the browser window doesn't make sense.

### Steps to reproduce: (app code and test code)

1) Run any UI test with a browser window longer than one-page 
2) After completion, hover over the interactive UI element steps
3) go back to any individual step where an element is interacted with and click it/pin it
4) Where does the highlighted space end up in the GUI?

### Versions

Cypress - v.3.4.1
MacOSX - v.10.14.6
Cypress runner GUI - Chrome v77

**Comment by jennifer-shehane** [comment]
@ChaseBig This does not happen in most cases. We would need an HTML example of a page that this happens on. Likely there is something like a sticky header or some css that we're not taking into account.

**Comment by ekulabuhov** [comment]
Hi @jennifer-shehane!

I'm seeing similar problem.

This is HTML/CSS causing the issue: https://cdpn.io/ekulabuhov/debug/bGdzMGx/VJMxxOpKZYQM

![image](https://user-images.githubusercontent.com/4452263/77932952-d204eb80-72e0-11ea-800c-344e30c59687.png)


That's the test:
```js
describe('Sticky header', () => {
    beforeEach(() => {
        cy.visit('https://cdpn.io/ekulabuhov/debug/bGdzMGx/VJMxxOpKZYQM');
    });

    it('Type text', () => {
        cy.get('#inputText')
        .type('new york ny');
    });
})
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
