### ISSUE TITLE
eifjccilfgclglivjlneutidlbvilifhtkecfhrnenrc

### ISSUE THREAD

**Issue by oracleason** [cypress-io/cypress#5211]

**Comment by Kjelli** [comment]
Cannot reproduce, thereby solved

**Comment by ryan-snyder** [comment]
Able to reproduce by mashing random keys. Could be a user error though, hard to tell

**Comment by laurenskling** [comment]
Crashes in IE11 :(

**Comment by stijnbernards** [comment]
I was able to reproduce this by kljashdjkaSGHdkluadsfTAHSDFGSADKLFG

**Comment by oracleason** [comment]
haha, not sure why.....create this bug.....
