### ISSUE TITLE
Enable JSON5 parsing for cypress.json to support comments

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5213]
### Current behavior:

Currently the cypress.json does not support comments.

### Desired behavior:

Comments should be allowed in the cypress.json.

### Steps to reproduce: (app code and test code)

add a comment to the cypress.json and start cypress.

### Versions

3.4.1

**Comment by paulfalgout** [comment]
`json` does not support comments

**Comment by CSchulz** [comment]
> Comments
Single and multi-line comments are allowed.

https://json5.org/

**Comment by jennifer-shehane** [comment]
Closing as this issue is meant to be superseded by this proposal: https://github.com/cypress-io/cypress/issues/5218
