### ISSUE TITLE
Clicking on nth option in select not possible

### ISSUE THREAD

**Issue by jdvegmond** [cypress-io/cypress#5215]
# Issue:
I'm testing a web app with a select element, with different values per (test) environment or even per run. I would like to be able to always select the 'nth' option in the select, but this is not possible, because the .select() command only accepts a value or display text.
 
### Steps to reproduce: (app code and test code)
Now I'm forced to use
cy.get(selector).select('some text')

But I would like to be able to use something like
cy.get(selector).select(2), where '2' represents the 2nd or 3rd (depending on where you start to count) option in the select element.

### Versions
Cypress 3.4.1, Windows 10, Chrome 76

**Comment by Bkucera** [comment]
workaround here https://stackoverflow.com/questions/50708295/cypress-select-specific-child-of-html-select/50892977#50892977:

Here's how you'd use `select()` based on index. First you get the `4th` value of the `select`, then use a `.then()` that yields it's `value`:
```js
cy.get('select.myselect option').eq(4).invoke('val').then((val)=>{      
  cy.get('select.myselect').select(val)
})

// .eq(n) yields the nth element
```

**Comment by jdvegmond** [comment]
Thank you for the workaround.
Though I'll have to use invoke('text') instead. For some reason all options have the same '[object Object]' value. (Maybe thanks to Vue?)
