### ISSUE TITLE
Expose an API to get the default config

### ISSUE THREAD

**Issue by Aghassi** [cypress-io/cypress#5217]
https://github.com/cypress-io/cypress/blob/dc251cc5d6c18da2be64ae3de269a00b75985099/cli/schema/cypress.schema.json#L1

We run Cypress through the API for our internal tooling, and have some config validation we wish to do. Right now, we use `jest-validate` to compare what is passed in to what is the "default". With other packages, like `jest` we can load their default config via `jest-config`. This makes it super easy to get the updates to the default config without having to add them manually.

We would like to do something similar with Cypress, but right now it seems this is the only file (above) that defines the config. It would be nice to have a `cypress-config` package that exposed a `getDefault()` function that gives this schema as an object which we can pass around and manipulate.

Is that something that would be possible?

**Comment by Bkucera** [comment]
@Aghassi do you need access in plugins (node) or support (browser, during test) ? We could probably do this pretty easily.

**Comment by Bkucera** [comment]
here's where we set defaults: https://github.com/cypress-io/cypress/blob/issue-2957/packages/server/lib/config.coffee#L81

**Comment by Aghassi** [comment]
@Bkucera the `node` API is how we are interfacing with triggering cypress, so preferably in `node`. I'll have a look at the example.

**Comment by Aghassi** [comment]
@Bkucera It seems that although you set the defaults in that file, they are not exported in anyway that I could get them right? If there were a `getDefaults` function in there that I could use to get the `CONFIG_DEFAULTS` that would be helpful. Is that a change I could contribute/make?

**Comment by ryan-snyder** [comment]
@Aghassi @Bkucera could probably confirm but that definitely seems like something doable and worth while. I would go for it and make that change but again, I'm not a part of the cypress team so....But I would personally love to see that change

**Comment by Bkucera** [comment]
@Aghassi yes, we would be open to a PR that exports the default values and exposes them via plugins/node API. We would need to think of the API for that, feel free to recommend how we should exposed it to the user (docs page on plugins/node API https://docs.cypress.io/api/plugins/writing-a-plugin.html#Plugins-API)

**Comment by Aghassi** [comment]
@Bkucera this is my first time in the codebase, so I'm trying to get a mental model of how it compiles. It seems to be a monorepo, but the monorepo compiles into a single package called "cypress" yes? I guess, what I'm thinking is:

- Take the constant you linked and make a separate package called `@cypress/config` that just exports that file as the main
- Have `@packages/server` reference that file so it can still use the defaults
- Publish `@cypress/config` as a standalone library that I can require or install so I can do `const cypressDefaultConfig = require('@cypress/config').getDefault()`
- Update the docs to reflect that.

Does that make sense? I still don't fully understand the publishing model (though I have read the deploy docs) so I wanted to check if I was missing anything

**Comment by flotwig** [comment]
@Aghassi The `cli` package is the source code for the actual `cypress` NPM module that gets distributed. Everything in `packages/*` gets bundled up with the Electron binary and downloaded at install time to be started by the `cli`.

Your solution could work, it would also force us to set up publishing for sub-repos which would be neat.

We could also just import and re-export `cypress.schema.json` in `cli/lib/cypress.js` to make it accessible. `cypress.configSchema` or something.

> here's where we set defaults: [/packages/server/lib/config.coffee@`issue-2957`#L81](https://github.com/cypress-io/cypress/blob/issue-2957/packages/server/lib/config.coffee#L81) [](/cypress-io/cypress/blob/HEAD@{2019-09-26T23:08:12Z}/packages/server/lib/config.coffee#L81)

side note, it would be cool if this could pull from `cypress/cli/schema/cypress.schema.json` - deduplication and all that

**Comment by Bkucera** [comment]
@Aghassi yes, don't worry about the specifics and implementation, its all possible. We have no precedence of exporting anything as a module except for the module API used to launch runs in node. So I was thinking something yielded to you in the `module.exports = (on, config) => {}` function instead of the imports.

**Comment by ryan-snyder** [comment]
I would personally be in favor of publishing the default cypress configs as it's own npm module. Similar to how you would publish an eslint-config as an npm module. Think it offers much more flexibility in the long run as well as letting people extend it and apply there own defaults. 
@Aghassi @Bkucera

**Comment by Bkucera** [comment]
@ryan-snyder default config values can make the difference between a release being a feature vs being breaking. For this reason we need to control default configs in tandem with the cypress core release. Especially considering new cypress releases will introduce new config values. 

There's an argument to be made with releasing subpackages such as `cypress/config` however

**Comment by ryan-snyder** [comment]
@Bkucera I totally argree about needing control over default config values. I guess I meant that if it were it's own module, someone could fork the code and publish their own specific config values. And that way, if something breaks, it's their fault and they can use the same config across multiple projects/repos or whatever. But I do get needing to have some measure of control over the configs so maybe that reason is a great own. 

Still definitely a fan of that decision but I can see both sides

**Comment by Aghassi** [comment]
Ok, let me push a branch with my change while trying to keep what is existing. It may take a few iterations, but I understand the problem @Bkucera is alluding to because we face it with our internal tooling too.

**Comment by Aghassi** [comment]
@Bkucera I opened a PR. It doesn't "work" so to speak, but it is a starter to show what I'm trying to get at. Ideally, the `@packages/config` would be something that we could publish to NPM anyway so that I could install it on my end and get the same config you guys use internally.

**Comment by Aghassi** [comment]
@Bkucera Just wanted to circle back on this and see if I could get some feedback on that PR. Would like to see if we can drive this to completion 😄

**Comment by sainthkh** [comment]
I close this issue because it is not necessary to the most users. The PR related to this issue is closed and this issue didn't get any thumbs-up. 

If anyone really wants this feature, please open a new issue.
