### ISSUE TITLE
Same project is initialized multiple times

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#522]
* Operating System: Mac
* Cypress Version: 0.19.2

### Are you requesting a feature or reporting a bug?

bug

### Current behavior:

1. Create an empty folder, for example `~/test-home-project`
2. Open Cypress desktop app `cypress open`
3. Add project
4. Browser to home folder and add `~/test-home-project`
5. App shows a message and creates example spec files, adds `cypress` folder and `cypress.json` file

<img width="800" alt="screen shot 2017-06-01 at 11 47 28 am" src="https://cloud.githubusercontent.com/assets/2212006/26688388/7ea0ee20-46c0-11e7-8747-52480f843177.png">

6. Click "Back to projects"
7. Click on the same project again
8. The "To help you get started..." dialog is shown again.

### Expected behavior:

I do not want to see the same dialog every time new folder is opened

**Comment by brian-mann** [comment]
We should cache this in `state.json` and no longer show the message.

**Comment by brian-mann** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
