### ISSUE TITLE
cy.wait() timed out ... to the route. No request ever occurred.

### ISSUE THREAD

**Issue by majco333** [cypress-io/cypress#5222]
### Current behavior:

Error message:
![image](https://user-images.githubusercontent.com/4101721/65762093-7afb3f80-e120-11e9-96fd-2949051a73c4.png)

Output in terminal:
![image](https://user-images.githubusercontent.com/4101721/65763320-69676700-e123-11e9-974f-7fb4c58f196d.png)

### Desired behavior:
When I try it on localhost, everything works. But when I change app url (real domain over HTTPS), I get this error message. However in terminal you can see that request on todos was called...

### Steps to reproduce: (app code and test code)
I attached demo project. You can only run it.

[CypressDemo.zip](https://github.com/cypress-io/cypress/files/3662273/CypressDemo.zip)

### Versions
Cypress: 3.4.1
Operating system: Windows 10 Pro
Browser: Chrome 77 and Electron 61

**Comment by ryan-snyder** [comment]
This is most likely a timing issue because it works for me. I would move your server and route setup to before the visit and the login like so:
```js
before(() => {
  cy.server()
  cy.route()
  // then visit and login here
}
```

**Comment by majco333** [comment]
> This is most likely a timing issue because it works for me. I would move your server and route setup to before the visit and the login like so:
> 
> ```js
> before(() => {
>   cy.server()
>   cy.route()
>   // then visit and login here
> }
> ```

It's not working for me. Can there be a problem with the CORS? See output in terminal...

**Comment by ryan-snyder** [comment]
Maybe? You have chromeWebSecurity set to false so it's nothing with Cypress I don't think. Again, it works for me so unless you can provide a reproducible example there's not much I can do. If you head over to the cypress gitter room, you may receive more help

**Comment by majco333** [comment]
@ryan-snyder Can you run multiple times? Because I try it on other computer and first time it worked, but the next times didn't work...

**Comment by ryan-snyder** [comment]
So you are right, this may actually be a bug. If you run the test and open chrome dev tools, and go to application and service workers and click `Bypass for network` it works. So there seems to be an issue with cypress catching networks that are triggered by a service worker?
Can @jennifer-shehane speak to this more?

**Comment by majco333** [comment]
Thanks @ryan-snyder 

@jennifer-shehane, @Bkucera Is it really a bug?

**Comment by Bkucera** [comment]
@majco333 could you screenshot the chrome devtools network tab and show the request? it should give us more information about the request

**Comment by majco333** [comment]
@Bkucera Here you are.
![image](https://user-images.githubusercontent.com/4101721/66018557-e312a280-e4df-11e9-821e-ceff267beee7.png)

All info:
![image](https://user-images.githubusercontent.com/4101721/66018580-089fac00-e4e0-11e9-9667-e99645858e07.png)

**Comment by majco333** [comment]
@jennifer-shehane, @Bkucera Do you have any new detections?

**Comment by Bkucera** [comment]
@majco333 sorry, I meant to see the view with the "type" column. It should say XHR or fetch

**Comment by majco333** [comment]
> @majco333 sorry, I meant to see the view with the "type" column. It should say XHR or fetch

![image](https://user-images.githubusercontent.com/4101721/66373597-42bdf180-e9a9-11e9-8b6d-97aa8b087edc.png)

**Comment by ryan-snyder** [comment]
@majco333 Seems to me like service workers only use fetch? I will admit that my knowledge on service workers is limited so I'm unsure if you can change that yourself or...?

**Comment by majco333** [comment]
I solved this problem. I disable servis-worker in my Angular app. I set this in angular.json:
`"serviceWorker": false`
