### ISSUE TITLE
Couldn't type using cy.type because cypress expecting some typeable elements, we are using angular with bootstrap responsive UI for forms?

### ISSUE THREAD

**Issue by MounarajElangovan** [cypress-io/cypress#5225]
Cypress Errors:
```
CypressError: cy.type() failed because it requires a valid typeable element.

The element typed into was:

<span translate="labels.REQUIRED_PROJECT_NAME" translate-values="{projectName:$root.trustedDataHtml(list.displayName)}" aria-label="REQUIRED_PROJECT_NAME">Project...</span>

Cypress considers the 'body', 'textarea', any 'element' with a 'tabindex' or 'contenteditable' attribute, or any 'input' with a 'type' attribute of 'text', 'password', 'email', 'number', 'date', 'week', 'month', 'time', 'datetime', 'datetime-local', 'search', 'url', or 'tel' to be valid typeable elements.
```

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
