### ISSUE TITLE
Selector is applied in wrong page context

### ISSUE THREAD

**Issue by herschel666** [cypress-io/cypress#5234]
### Current behavior:

I'm testing a prev/next-navigation between the image detail pages of a gallery, where the text of the links between the images is their respective title. The links to those image detail pages on the parent gallery page are each a set of linked image elements and also a link with the text of the respective title.

What happens now is that Cypress is able to visit the gallery page, click on an image to navigate to the image detail page, but then isn't able to get the link of the previous image by its title.

What's so confusing about it is the error message that I get: Cypress somehow applies the `.contains(…)`-selector not to the prev-link on the image detail page (where it's currently on — verified by a check!), but to the parent page, where this link also theoretically exists. Cypress is even able to get a hold of that link on the parent page, but isn't able to click it — which is then the feeback that I get via error message.

[You can see it here in the Travis output](https://travis-ci.org/herschel666/photoblog/builds/591042915#L407). The link, Cypress got, is on the parent page of the one it's currently on. 🤯 I'm not even sure atm whether this isn't rather an issue with Gatsby, but yeah…

### Desired behavior:

Cypress should only take elements from the current page into account.

### Steps to reproduce:

- clone out [this repo](https://github.com/herschel666/photoblog)
- check out the branch [`refactor-integration-tests`](https://github.com/herschel666/photoblog/pull/153)
- run `npm install`
- run `npm run test:e2e`

### Versions

MacOS 10.13.6, Cypress 3.4.1, Electron 61, Gatsby 2.15.28

**Comment by jennifer-shehane** [comment]
Closing as I can no longer reproduce with the branch being deleted.
