### ISSUE TITLE
Request: saving different file should run it

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#5235]
### Current behavior:

When you save a different spec file than the one currently being run in headed cypress runner, it does nothing.

Current workaround is to close the runner, filter the new spec, and run it manually.

### Desired behavior:

It should run the spec file just being saved.

### Versions

`3.3.1`, Windows 7

**Comment by jennifer-shehane** [comment]
@dwelle How are you running the spec file exactly? Why would changes to another spec file rerun a different specfile? What is the use case?

**Comment by dwelle** [comment]
Say you're modifying or reviewing several spec files in a row, and want to run them in interactive mode upon each modification.

I've tried implementing it on my own via custom watcher, but was unable to figure out a a non-hacky approach to run different spec files from a plugins file.

**Comment by jennifer-shehane** [comment]
I would say this is outside of the scope of Cypress if you want to have this custom watching behavior.
