### ISSUE TITLE
Documentation does not list all available options how to override config

### ISSUE THREAD

**Issue by ddeath** [cypress-io/cypress#524]
### Are you requesting a feature or reporting a bug?
Bug

### Current behavior:
The documentation does not state all available options how to override config in cypress:
https://docs.cypress.io/docs/configuration#section-overriding-options

There is third option:

* use `Cypress.config(key, value)`

### Expected behavior:
The documentation will state that there is third option...

**Comment by jennifer-shehane** [comment]
This is now be documented in our new docs: [https://on.cypress.io/configuration#Cypress-config](https://on.cypress.io/configuration#Cypress-config)
