### ISSUE TITLE
URI resolver does not recognize absolute URI

### ISSUE THREAD

**Issue by thorlacius** [cypress-io/cypress#5244]
An absolute URI of the form `https:adversary.io` is not recognized as an absolute URI.

### Current behavior:

Cypress thinks the URI `https:adversary.io` is a relative URI specifying only a pathname component. If resolved with base URI as the current working directory (the default) it will think `https:adversary.io` is a file named `https:adversary.io`.

### Desired behavior:
Cypress should recognise that `https:adversary.io` is an absolute URI (and normalize it to `https://adversary.io/` if Cypress developers prefer that form).

### Steps to reproduce:
Tiny example:

https://github.com/thorlacius/cypress-test-tiny/commit/6869aee8ee7204ef6769710ec56bfe2b3729c929

### Versions
From my package.json:
`"cypress": "^3.4.1"`

**Comment by jennifer-shehane** [comment]
Yeah, this behavior is a bit weird. 

```js
it('visits https:// site', () => {
  cy.visit('https://adversary.io')
  cy.url().should('eq', 'https://www.adversary.io/') // passes
})

it('visits https: site', () => {
  cy.visit('https:adversary.io')
  cy.url().should('eq', 'https://www.adversary.io/') // does not work
})
```

## visiting https:// site

![](http://g.recordit.co/F2LrAcvUwG.gif)

## visiting https: site

reroutes entire window to `https://www.adversary.io/__#/tests/integration/spec.js` which 404s.

<img width="962" alt="Screen Shot 2020-01-03 at 4 43 52 PM" src="https://user-images.githubusercontent.com/1271364/71718009-48ac5d00-2e48-11ea-939e-2bdd98b773c7.png">
