### ISSUE TITLE
EEXIST: file already exists, mkdir 'C:\Cypress.Node\node_modules.bin\cypress'

### ISSUE THREAD

**Issue by gogamera** [cypress-io/cypress#5253]

**Comment by ZwapKillrath** [comment]
I see a \ missing between node_modules and .bin right?
I am having the same issue
@jennifer-shehane ?

**Comment by Krak86** [comment]
I have the same issue.

**Comment by EdwinvanDessel** [comment]
I have the same issue with a fresh installed 4.4.1 version

**Comment by jennifer-shehane** [comment]
Duplicate of #1099
