### ISSUE TITLE
Windows reports one of Cypress dependency (flatmap-stream) miner

### ISSUE THREAD

**Issue by shahidcodes** [cypress-io/cypress#5255]
### Current behavior:
Installing cypress windows defender blocks this `AppData\Local\Cypress\Cache\3.1.2\Cypress\resources\app\packages\server\node_modules\flatmap-stream\test\data.js` file reporting it is a miner

### Desired behavior:
It should be removed if it contains miner. I am attaching a screenshot and the detected file.
### Steps to reproduce: (app code and test code)
Install cypress 3.1.2 using npm. 

### Versions
3.1.2

![image](https://user-images.githubusercontent.com/17620737/65936498-6e395d00-e43a-11e9-8820-8179c5708ebe.png)
[pastebin link to miner file](https://pastebin.com/LNLNxs6W)

**Comment by jennifer-shehane** [comment]
@shahidcodes `flatmap-stream` is not an included dependency in the cypress project as of 3.8.1.

```
 npm ls flatmap-stream
cypress@3.8.1 /Users/jennifer/Dev/cypress
└── (empty)
```

We are undergoing the process of notarization with Mac that will also give gaurantees that there is no malicious software in our product. https://github.com/cypress-io/cypress/issues/5791
