### ISSUE TITLE
.should() function usage - err when cy called within callback function

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#526]
* Cypress Version: 0.19.2

### Are you requesting a feature or reporting a bug?
Feature

### Current behavior:

When writing `cy` commands within a `.should()` callback function, the following error is given: [on.cypress.io/command-queue-ended-early](on.cypress.io/command-queue-ended-early)

### Expected behavior:

The docs specify that on `.should()` function usage: 

> Just be sure not to include any code that has side effects in your callback function.
> The callback function will be retried over and over again until no assertions within it throw.

Cypress should check if there are any `cy` commands within a `.should()` callback function and give a more specific error warning not to do this.

#### Test code:

```js
it('delete row', () => {
  cy.get('.row').should($els => {
    const could = $els.length;

    cy.get('.row:last .delete-btn').click();
    cy.get('.row').should('have.length', could - 1);
  });
});
```

**Comment by ddeath** [comment]
I would also suggest to add something like this 
![image](https://user-images.githubusercontent.com/2537379/26847993-42a6b858-4aff-11e7-8a84-b6db682b1b60.png)

in the docs with red color as warning that you can not call `cy` commands inside `should()`

**Comment by jennifer-shehane** [comment]
Closing. I can no longer create this bug in version 3.1.5
