### ISSUE TITLE
have.prop Chainer yields wrong subject type

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5261]
### Current behavior:

```js
cy.get<DivElement>('div')
  .should('have.prop', 'loading', false)
  .then(e => // e is DivElement);
```

### Desired behavior:

```js
cy.get<DivElement>('div')
  .should('have.prop', 'loading', false)
  .then(e => // e is boolean);
```

The declaration should be something like:

`<T = any>(chainer: 'have.prop', value: string, match?: T): Chainable<T>`

In all cases the `Subject` have to replaced with anything else.

`(chainer: 'have.prop', value: string, match?: any): Chainable<Subject>`

### Versions

3.4.1

**Comment by sainthkh** [comment]
Current typing is correct. It correctly types the current behavior of the function. 

```js
beforeEach(() => {
  cy.visit('fixtures/dom.html')
})

it('t', () => {
  cy.get('#tabindex')
  .should('have.prop', 'tabindex', 1)
  .then((e) => {
    expect(e).not.to.eql(1)
  })
})

it('t2', () => {
  cy.get('select[name=disabled]')
  .should('have.prop', 'disabled', true)
  .then((e) => {
    expect(e).not.to.eql(true)
  })
})
```

**Comment by sainthkh** [comment]
If my understanding is wrong, please tell me more about the problem. If not, let's close this issue.

**Comment by jennifer-shehane** [comment]
Yeah, the `.then()` in these situations does return a DOM element, so the typing is correct.
