### ISSUE TITLE
"bad option: --run-project" error when using VS Code

### ISSUE THREAD

**Issue by luisherranz** [cypress-io/cypress#5262]
### Current behavior:

I've added cypress to our husky configuration to pass e2e tests before pushing to GitHub, but when I try to push from VS Code, I get this `bad option: --run-project` error:

```
2019-10-02T09:37:13.366Z start-server-and-test waitOn finished successfully
2019-10-02T09:37:13.367Z start-server-and-test running test script command: cypress run --env HEADLESS=true
/Users/luisherranz/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/MacOS/Cypress: bad option: --run-project
2019-10-02T09:37:13.821Z start-server-and-test getting child processes
2019-10-02T09:37:13.850Z start-server-and-test stopping child processes
2019-10-02T09:37:13.850Z start-server-and-test stopping server
{ Error: Command failed with exit code 9 (EBADF): cypress run --env HEADLESS=true
    at makeError (/Users/luisherranz/Code/frontity/node_modules/start-server-and-test/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/luisherranz/Code/frontity/node_modules/start-server-and-test/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  command: 'cypress run --env HEADLESS=true',
  exitCode: 9,
  exitCodeName: 'EBADF',
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontity-monorepo@ test:e2e: `cross-env DEBUG=start-server-and-test start-server-and-test cy:project http://localhost:3001 'cypress run --env HEADLESS=true'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontity-monorepo@ test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Running the same script works fine when executed in the terminal, so it's not a problem with the script.

Running `git push origin some-branch` in the terminal works fine, so it's not a problem of husky.

So it definitely has something to do with the way VS Code is running git.

### Desired behavior:

We can use cypress in git hooks and push code using VS Code.

### Steps to reproduce: (app code and test code)

- Clone this repo: https://github.com/luisherranz/cypress-test-tiny
- Checkout the `git-hooks-in-vs-code-bug` branch.
- Make some changes.
- Try to push with VS Code.

Here is a video of the steps:
https://youtu.be/4em2yQ_BoyY

### Versions

Cypress: 3.4.1
Node: 10.16.3
VS-Code: 1.38.1

**Comment by flotwig** [comment]
I am closing this issue since it is for a very out of date version of Cypress and this has not been reported in newer versions. Please try upgrading to the latest version of Cypress (currently 9.7.0) and if this issue persists please open a new GitHub issue.

**Comment by leticiafontoura** [comment]
Hi, I'd like to reopen this as I'm having the same issue here, although with a different error message. 
exact same situation: command works on terminal but not when clicking "publish branch" on VSCode

"cypress": "^13.6.3"
"node": "v16.16.0"
"vscode": 1.85.2

![Captura de Tela 2024-01-24 às 18 05 01](https://github.com/cypress-io/cypress/assets/47862337/4105029d-d2ae-46c1-b0aa-0a5781bd060a)
