### ISSUE TITLE
Page loaded, but not displayed

### ISSUE THREAD

**Issue by aellopos** [cypress-io/cypress#5266]
Hi!

I am writing test for website that runs locally on my computer (using docker). I want to put sign in information and sign in to website. When I run this test, it will put in sign in information, click to sign in button, everything seems to be fine, but next page will not load, test passed. I can see in report that (PAGE LOAD) --page loaded-- (NEW URL) etc., but new page not displayed.

![image](https://user-images.githubusercontent.com/39790985/66048077-3bba5d80-e529-11e9-9c4b-5a63980201be.png)

Any ideas? Code is here:

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  return false
})

Cypress.config(
  {
      "baseUrl": "http://czechitas-is.localhost"
  }
);

describe('Test prihlaseni do ISu', function() {
  it('Prihlaseni k domene', function() {
    cy.visit('/cs')
  })

  it('Kliknuti na tlacitko prihlaseni', function() {
    cy.get('#frm-signIn-login')
      .type('test')
      .should('have.value', 'test')

    cy.get('#frm-signIn-password')
      .type('test')
      .should('have.value', 'test')

      cy.contains('Přihlásit').click()

      cy.url().should('include', '/cs/account/sign/in')
  })
})
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run and we will reopen the issue. 🙏
