### ISSUE TITLE
Cypress promise gets ignored or throws an error

### ISSUE THREAD

**Issue by bob-zs** [cypress-io/cypress#5267]
### Current behavior:
Cypress promise gets ignored or throws an error.

### Desired behavior:
It runs through either commands.

### Steps to reproduce: (app code and test code)
Diff:
https://github.com/cypress-io/cypress-test-tiny/pull/50/files#diff-2b07e229b86aa9d270302ce5fcdf29a1L18

<img width="525" alt="Screen Shot 2019-10-02 at 10 26 38 AM" src="https://user-images.githubusercontent.com/4698973/66052869-4fe96500-e4ff-11e9-81d3-ea204397adee.png">

### Versions
On a macOS Mojave 10.14.6

```
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^4.0.3",
    "cypress": "^3.3.2",
    "ts-loader": "^6.0.4",
    "typescript": "^3.5.3",
    "webpack": "^4.35.3"
  },
```

https://github.com/cypress-io/cypress-test-tiny/pull/50/files

**Comment by sainthkh** [comment]
This is the expected behavior. If you want to wait, please use [`cy.wait()`](https://docs.cypress.io/api/commands/wait.html#Syntax).
