### ISSUE TITLE
Errors thrown in test get swallowed when preceded by a Cypress command

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#527]
Consider the following test code:

```javascript
it('has the right title', function () {
  cy.get('h1').contains(this.content.title)
})
```

This should fail (and does fail) if `this.content` is not defined, or if any runtime exception is thrown after a Cypress command has been enqueued. The problem is that the error displayed is `Cypress still has commands in its queue`. That's true, but it doesn't indicate the source of the problem, the true error, which is something like `Cannot read property 'bar' of undefined`. 

Cypress should display the error if one causes the test to end early with commands in the queue.

Here's a more contrived (but easier to reproduce) example:

```javascript
it('needs a better error display ;)', function () {
  cy.wrap({})
  this.foo.bar
})
```

**Comment by jennifer-shehane** [comment]
This has been fixed since this was opened. 

<img width="558" alt="screen shot 2019-02-01 at 6 32 56 pm" src="https://user-images.githubusercontent.com/1271364/52121972-d8052b00-264f-11e9-83ac-a587d90c9270.png">
