### ISSUE TITLE
`not.be.visible` assertion fails when element does not exist in DOM and Stripe JS SDK is imported

### ISSUE THREAD

**Issue by bahalperin** [cypress-io/cypress#5270]
### Current behavior:
Normally when asserting that an element is not visible (using `.should('not.be.visible')`), if the element does not exist in the DOM, the assertion passes.

For some reason, simply by including the Stripe JS SDK in the head of the document (following the instructions [here](https://stripe.com/docs/web/setup#setup)), the `not.be.visible` assertion fails (by timing out when retrying to find the element) when the element is not in the DOM.

There is a work around by checking `not.exist` before `not.be.visible`

### Desired behavior:
The behavior should be consistent whether or not the Stripe SDK is imported

### Steps to reproduce: (app code and test code)
Repro can be found in [this repo](https://github.com/bahalperin/cypress-test-tiny/tree/visibility-bug)

### Versions

Cypress 3.4.1

**Comment by jennifer-shehane** [comment]
I was able to reproduce this in 3.8.1. Code to reproduce below:

`with_stripe.html`

```js
<!DOCTYPE html>
<head>
  <script src="https://js.stripe.com/v3"></script>
</head>
<body>
</body>
</html>
```

`without_stripe.html`

```js
<!DOCTYPE html>
<head>
</head>
<body>
</body>
</html>
```

`spec.js`

```js
it('without stripe asserting "not visible"', () => {
  cy.visit('without_stripe.html')
  cy.get('.foo').should('not.be.visible') // passes
})

it('with stripe asserting "not visible"', () => {
  cy.visit('with_stripe.html')
  cy.get('.foo').should('not.be.visible') // falsely fails because can't find element
})

it('with stripe asserting "not exists" then "not visible"', () => {
  cy.visit('with_stripe.html')
  cy.get('.foo')
    .should('not.exist')
    .and('not.be.visible') // passes
})
```

![Screen Shot 2020-01-03 at 5 14 04 PM](https://user-images.githubusercontent.com/1271364/71719366-8317f900-2e4c-11ea-8769-a5ed5e0cfe7b.png)

Stripe injects an iframe into the html, which may have something to do with it, but I tried injecting a simple iframe into the html and it did not fail like with the Stripe script.

![Screen Shot 2020-01-03 at 5 21 37 PM](https://user-images.githubusercontent.com/1271364/71719707-8f508600-2e4d-11ea-8822-48b5284bbc53.png)
