### ISSUE TITLE
[Doc] 404 on the cypress dashboard page

### ISSUE THREAD

**Issue by juristr** [cypress-io/cypress#5279]
### Steps to reproduce: (app code and test code)

Visiting [this site](https://www.cypress.io/dashboard/#targetText=The%20Cypress%20Dashboard%20enables%20you,machines%20as%20you%20want%20to.)

![image](https://user-images.githubusercontent.com/542458/66109283-9b197b80-e5c4-11e9-8db0-bb909fc7e1b4.png)

Click the "Configure your project to record....it points to https://docs.cypress.io/dashboard-service#Setup which results in a 404.

### Versions

Docs page (not sure such bugs should be reported here as well or if there is a better place :) )

**Comment by oak-wildwood** [comment]
Good catch @juristr. Appreciate the heads up. Will get this fixed.

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress as a product. This issue will be closed in this repository.

We're deploying a fix for the broken link though. Thanks for pointing it out!
