### ISSUE TITLE
Have command text length (for ellipsis ...) be aware of width of Command Log

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#528]
* Cypress Version: 0.19.2
* Browser/Browser Version: Chrome

### Current behavior:

The command text is cutoff at a certain length regardless of width of Command Log

### Expected behavior:

If I expand the width of the Command Log, I expect the allowed length of command text to expand.

### How to reproduce the current behavior:

I can't see the entire request Url for each request in the screenshot below even though I've expanded my Command Log's width.

### Additional Info (images, notes, stack traces, etc)

![screen shot 2017-06-06 at 2 33 00 pm](https://user-images.githubusercontent.com/1271364/26845745-7e19a1c8-4ac5-11e7-97a0-67044e821c98.png)

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
