### ISSUE TITLE
better dom node highlights

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress#5281]
Priority: low

Currently, we use absolutely positioned dom nodes placed on the `body` of the app frame.
We could switch to using pseudo element + svg rects to render dom highlights.

**benefits**:
- element transforms will always be taken into account. Currently, we cannot take into account parent transforms 

Demo here:
https://codesandbox.io/s/dom-hightlight-pseudo-demo-mrwv5

**Comment by jean343** [comment]
I like this idea, right now if the highlighted node is an svg element, the width is undefined.
Also, in chrome on windows, the highlight does not show up with an opacity of 0.7.

![image](https://user-images.githubusercontent.com/7070881/79701537-f0b92b00-826b-11ea-8e4d-5d1332e65d3b.png)

![image](https://user-images.githubusercontent.com/7070881/79701542-f9a9fc80-826b-11ea-8595-2a72cba79d89.png)

**Comment by Bkucera** [comment]
@jean343 is the opacity broken for every element or just when targeting svgs?
