### ISSUE TITLE
onclick event fired when disabled the icon button in blazor

### ISSUE THREAD

**Issue by mohankumar91** [cypress-io/cypress#5286]
### Current behavior:

`@onclick` event fired when disabled the button (with icon) in blazor

### Desired behavior:

`@onclick` event not fired when disabled the button(with icon) in blazor

### Steps to reproduce: (app code and test code)

```html
<button class="btn1" @onclick="onToggleClick" disabled>
<span class="fa fa-home" />@Content</button>
```

```js
@code {
  public string Content = "Play";
private void onToggleClick(Microsoft.AspNetCore.Components.Web.MouseEventArgs e)
    {
        if (this.Content == "Play")
        {
            this.Content = "Pause";
        }
        else
        {
            this.Content = "Play";
        }
    }
}
```

```html
<style>
  
.btn1 {
 
  border: none;
  color: white;
  padding: 12px 16px;
  font-size: 16px;
  cursor: pointer;
}
</style>
```

**Refer the below css file in **_host.cshtml** page**

https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

### Versions

3.4.1

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run completely on our machines and we will reopen the issue. 🙏

**Comment by mohankumar91** [comment]
Hi @jennifer-shehane ,
I have uploaded the reproducible example. Could you please reopen the issue and ensure the sample.

[DemoSample.zip](https://github.com/cypress-io/cypress/files/3700718/DemoSample.zip)
![Demo](https://user-images.githubusercontent.com/18420823/66367553-499d3200-e9b2-11e9-9c14-3a42eea088da.gif)

**Comment by mohankumar91** [comment]
Hi @jennifer-shehane ,

Please reopen this issue.

Regards,
@mohankumar91

**Comment by mohankumar91** [comment]
Hi @jennifer-shehane ,

Any update on this.

Regards,
@mohankumar91
