### ISSUE TITLE
"Unexpected identifier" error when used "userAgent" in cypress.json and running with  "cypress run"

### ISSUE THREAD

**Issue by Artem-Kushch** [cypress-io/cypress#5288]
### Current behavior:
Get `Uncaught SyntaxError: Unexpected identifier` error after visit step in the test, only when used `userAgent` in `cypress.json` and running tests with `cypress run`
 
<img width="391" alt="2019-10-04_1459" src="https://user-images.githubusercontent.com/18553982/66206070-a6010880-e6b7-11e9-9673-318e05f318d8.png">

Without `userAgent` - works fine.

Running with `cypress open` (electron or chrome)- works fine.
`userAgent` + `cypress run` (electron or chrome) - error

In debug logs many similar errors:

```
cypress:https-proxy received error on client browserSocket { err: { Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }, url: 'www.something.com:443' } +3s
```

### Steps to reproduce: (app code and test code)

- spec file: https://gist.github.com/Artem-Kushch/00b318aac35bd586bb63d14a53247d09
- `cypress.json`: https://gist.github.com/Artem-Kushch/15dd5cf3ad321fbd52eb4561e17cc202
- run with the command: `cypress run --spec "cypress/integration/name_spec.ts" --headed`

### Versions

    "@cypress/webpack-preprocessor": "^4.1.0",
    "cypress": "^3.4.1",
    "ts-loader": "^6.2.0",
    "webpack": "^4.41.0",
     node 10.16.0/12.7.11

**Comment by jennifer-shehane** [comment]
`Test` is not a valid user-agent, I'm not sure where this error is throwing from, but I would recommend passing a valid user-agent as defined in the MDN docs. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

The code below works in `cypress open` and `cypress run`. Can you provide an example that fails when you pass a valid User-Agent? We can't guarantee invalid User-Agents will work.

cypress.json

```js
{
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0"
}
```

specfile

```js
it('Debug test', function () {
  cy.visit('https://nustay.com/')
})
```

**Comment by Artem-Kushch** [comment]
Yes, with mozilla userAgent is works fine.
I understood my problem.
Thank you!
