### ISSUE TITLE
`onAnyRequest` does not fire when set from `Cypress.Server.defaults`

### ISSUE THREAD

**Issue by ryardley** [cypress-io/cypress#5289]
### Current behavior:

If I do this: 

```js
// cypress/integration/mytest.js

describe('My test ', () => {
  before(() => {
    cy.server({
      force404: true,
      onAnyRequest: (route, proxy) => {
        // Errors thrown here don't become test failures
        // Instead we need to throw them from within the XHR
        const { xhr } = proxy;
        if (route.status === 404) {
          xhr.onreadystatechange = function() {
            if (xhr.readyState === 4) {
              throw new Error(
                `Route not stubbed. Please add a cy.route() for url: "${xhr.url}" or provide it to your server whitelist.`,
              );
            }
          };
        }
      },
    });
  });

  it('should be able to do the things...', () => {
    cy.visit('/'); // This page will go fire a route somewhere lets say `/api/prices`
    // etc...
  });
});
```

I find all my un-stubbed routes fail the test they are called in appropriately and tell me what I should do to fix the failure.

---

Now, according to the following, I can put my default `cy.server` config in `Cypress.Server.defaults()`:

https://docs.cypress.io/api/cypress-api/cypress-server.html#Syntax 

However, when I do the following:

```js
// cypress/support/index.js

Cypress.Server.defaults({
  force404: true,
  onAnyRequest: (route, proxy) => {
    // Errors thrown here don't become test failures
    // Instead we need to throw them from within the XHR
    const { xhr } = proxy;
    if (route.status === 404) {
      xhr.onreadystatechange = function() {
        if (xhr.readyState === 4) {
          throw new Error(
            `Route not stubbed. Please add a cy.route() for url: "${xhr.url}" or provide it to your server whitelist.`,
          );
        }
      };
    }
  },
});
```

and 

```js
// cypress/integration/mytest.js

describe('My test ', () => {
  before(() => {
    cy.server();
  });

  it('should be able to do the things...', () => {
    cy.visit('/'); // This page will go fire a route somewhere lets say `/api/prices`
    // etc...
  });
});
```

My routes merely 404. 

### Desired behavior:

I expect unstubbed routes to fail with the above error. 

### Steps to reproduce: (app code and test code)

As above 

### Versions

Cypress: 3.4.1
OS: macOs
Browser: Cypress Chrome ( 77.0.3865.90 )

**Comment by jennifer-shehane** [comment]
I can recreate this - seems like a bug to me.

```js
it('server settings', () => {
  Cypress.Server.defaults({
    onAnyRequest: (route) => {
      // this debugger and console do not log 😞
      console.log('Cypress.Server onAnyRequest', route)
      debugger
    },
  })

  cy.server({
    onAnyRequest: (route) => {
      // this debugger and console log 😀
      console.log('cy.server onAnyRequest', route)
      debugger
    },
  })

  cy.route('GET', 'comments/*').as('getComment')
  cy.visit('https://example.cypress.io/commands/network-requests')
  cy.get('.network-btn').click()
})
```

<img width="680" alt="Screen Shot 2019-10-07 at 5 03 53 PM" src="https://user-images.githubusercontent.com/1271364/66348543-cd104200-e924-11e9-8da0-12cf0dc94fee.png">

**Comment by RiZKiT** [comment]
I would like to set `Accept-Language` header on `onAnyRequest`. I doesn't work. Any other idea except using Browser Launch API with `launchOptions.preferences[]` which doesn't work either.

**Comment by gustawx** [comment]
Exactly same issue is with `onAnyResponse`

**Comment by gustawx** [comment]
I see this bug was reported a year ago. Is it plan to be fixed? It seems to be very useful feature...

**Comment by emilyrohrbough** [comment]
In the upcoming v12.0.0 release, the deprecated `Cypress.Server.defaults` will be removed. This has been related with [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept). Closing as won't fix.
