### ISSUE TITLE
Cypress Dashboard  project status icons not properly synced with main panel

### ISSUE THREAD

**Issue by amazza-bg** [cypress-io/cypress#5291]
### Current behavior: 

The cypress dashboard has three status icons:

1. Green check to display tests have passed for the most recent test run (assumed)
2. Red X to display tests have failed for the most recent test run (assumed)
3. Yellow question mark to display tests have not been executed (assumed)

These icons are displayed next to the name of the project on the left panel AND on the main panel. These statuses or icons do not seem to be synced correctly. 

[https://ibb.co/zNkPzXf](https://ibb.co/zNkPzXf)

### Desired behavior:

Desired behavior would be to have the icons synced between the left panel and middle panel

### Steps to reproduce: (app code and test code)

1) create a dashboard with multiple projects
2) have a project that has no test runs to show the question mark icon within the left panel and also within the middle panel
3) test the sync between the panels and icons as well as the logic behind what each icon means and the display on the dashboard

### Versions

3.4.1 / windows 10 / chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Hey @amazza-bluegrace, we are aware of some situations where the project's status icon is not matching the true status of the project in our new navigation bar in the Dashboard. Our engineering team is working on a fix. We'll update this issue as soon as that fix is released.

**Comment by jennifer-shehane** [comment]
There is a PR in development to fix this issue. It will be fixed in the next release of the Dashboard Service.

**Comment by amazza-bluegrace** [comment]
Fantastic! Thank you for the update @jennifer-shehane

**Comment by jennifer-shehane** [comment]
This issue has been fixed.
