### ISSUE TITLE
junit reports are not logging failed testcase time in the generated xml files

### ISSUE THREAD

**Issue by keertyverma** [cypress-io/cypress#5301]
Hi, I have problems to get the built-in junit reporter working. Failed testcase time is not logged in generated junit xml files.

### Current behavior:
1. I am running multiple test files. Reports are getting generated for each specs.
But if any tests are failing then in the report, test time is 0

![image](https://user-images.githubusercontent.com/13656449/66294428-94fa0680-e906-11e9-9a0c-a207d4adefb8.png)

In the attached xml snapshot for last test-suites, failure=1 but time=0.
In the Test run, I can see it is taking 30 second, but why is it not logged in the generated junit xml report ? 

![image](https://user-images.githubusercontent.com/13656449/66294479-b5c25c00-e906-11e9-9e3c-573c5d5706a4.png)

### Desired behavior:

Failed testcase proper time should be logged into generated junit xml file.

### Steps to reproduce: (app code and test code)
1. Add below configuration in `cypress.json` file
```
    "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "cypress/reports/result-[hash].xml"
```
2. Create any failed testcase
3. Run the tests
4. Check the time attribute in the the generated junit xml file

### Versions

Cypress = 3.4.1
OS = Windows 10
Browser = chrome

**Comment by jennifer-shehane** [comment]
Have you isolated that the time shows correctly when set up outside of the Cypress test runner? 

Cypress doesn't generate these reports - junit is, so I do not think this is an issue with Cypress.

**Comment by keertyverma** [comment]
This xml is generated by built-in cypress reporter option for junit.

**Comment by keertyverma** [comment]
@jennifer-shehane Any update ?

**Comment by selangley-wa** [comment]
Did you see this note about the changes to this behavior with Cypress 3?

https://docs.cypress.io/guides/tooling/reporters.html#Report-per-spec

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
