### ISSUE TITLE
Kill long running test

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#5302]
Hey there, I'm wondering if there is already a built in way or a recommended way to kill any tests that run longer than a particular arbitrary timeout. In my case I'm finding that certain tests are taking an unexpected amount of time to complete and can completely hang my CI environment. 

For that reason I'd like to set a `maxTestRunTimeout` variable to 5 mins and kill any tests with an error if they go longer than that. Is there already a good way to do that? Would `maxTestRunTimeout` be something that you think should be added as a config option?

Thanks!

**Comment by jennifer-shehane** [comment]
Hey @tnrich, I'd need to know more specifically what the situation is within the test - why it 'hangs' exactly, but we have implemented a fix that will go out in 3.5.0 that will timeout tests with a `done` callback that 'hang' within the allowed `defaultCommandTimeout`. See PR here: https://github.com/cypress-io/cypress/pull/5097

You could pull down and try the prerelease with that fix by following these instructions on the commit: https://github.com/cypress-io/cypress/commit/d8bdd4a85d899fcd1deb2f9f5ed376790fbcb701#commitcomment-35267134

If you believe this will fix your issue - feel free to close, otherwise we will need an example of a test that times out for you in order to find a solution.

**Comment by tnrich** [comment]
@jennifer-shehane thanks for getting back to me! I don't think the defaultCommandTimeout would work for my use case because it is not necessarily a command itself that would cause the test to hang. Here is an example of a test that I would want to fail based on a `maxTestRunTimeout` (as opposed to a `defaultCommandTimeout`): 

```
import {times} from 'lodash'

it(`should throw an error if running too long!`, ()=> {
      times(10000000).forEach(() => {
        cy.wait(200)
        cy.get("body")
      })
  })
```

In this example code there is no command that runs longer that 200 ms, the issue is that the whole test would run for 200ms * 10000000 because we're looping through a giant array. 

This is a contrived example of course but in practice I still think it would be nice to find a good way to error on unexpectedly long running tests. 

I hope that all makes sense. Let me know if you'd like more info @jennifer-shehane 

Thanks!

**Comment by tnrich** [comment]
Just poking around a bit.. it seems like I can do this by adding: 

```
beforeEach(() => {
  setTimeout(() => {
    throw new Error("Test taking tooooo long!")
  }, 6000 * 5); 

})
```

to `support/index.js`

That way this will run before every test and error if it takes too long.

**Comment by tnrich** [comment]
@jennifer-shehane I'm re-opening this because the solution I described above actually does not work per it() block, it actually errors whenever the whole file goes above 5 mins. 

I need a way to cancel that setTimeout if the test has already passed successfully.

**Comment by jennifer-shehane** [comment]
@tnrich There are many events that you can listen to from Cypress that may help you figure out how to workaround what you're trying to do. https://on.cypress.io/catalog-of-events#Cypress-Events

I don't think this would qualify as a bug in Cypress or a feature that we intend to add though, so I'm not sure this is the best place for this discussion.

**Comment by tnrich** [comment]
Sounds good @jennifer-shehane , after some playing around it appears that this code should work: 
```js
//in support/index.js
beforeEach(() => {
  setTimeout(() => {
    throw new Error("Test taking tooooo long!")
  }, 60000 * 5); 
  afterEach(() => {
    clearTimeout(timeoutId)
  })
})
```js
