### ISSUE TITLE
Does anyone *actually* know how to set-up and/or use cypress `groups`? 

### ISSUE THREAD

**Issue by ChaseBig** [cypress-io/cypress#5303]
# Current behavior:
Currently, there is no behavior because the documentation on the cypress docs website is useless (there's not really any documentation on how to use/implement/set-up groups). 

### Desired behavior:
I just want to see some sort of documentation on how cypress --groups are supposed to be set up. 

### Steps to reproduce: (app code and test code)

1) Navigate to https://docs.cypress.io/guides/guides/parallelization.html#Grouping-by-spec-context
2) Read the nearly empty documentation
3) Try and set up cypress groups with the documentation available
4) Realize that you can't set up cypress groups because the documentation is useless
5) Go to google and search "how to set up cypress groups" 
6) Find that the results are equally as useless.

**Comment by brian-mann** [comment]
Have you read the section here?

https://docs.cypress.io/guides/guides/parallelization.html#Grouping-test-runs

Maybe you can provide more specifics as to what is not satisfactory about the docs and grouping content. I see several sections that explain exactly how to use the `--group` flag, and what the effect of it is (including screenshots).

I took a screenshot of the docs in case they are not loading for you. I respectfully disagree that the length of them qualifies as "...nearly empty documentation".

![Parallelization_Cypress_Documentation_-_2019-10-07_15 41 05](https://user-images.githubusercontent.com/1268976/66343194-19ee1b80-e919-11e9-91e7-b788fcc2a492.png)

**Comment by ChaseBig** [comment]
@brian-mann 
This documentation is primarily regarding parallelization, but there's still no explanation of how or where `groups` are defined. All this documentation shows in regard to the `group` feature is a list of arbitrary terminal commands. I'm not using parallelization at this time and just want to assign a file path to a "group" so I can set up my CI to only run certain groups when certain packages are published.

Or is this documentation stating that `groups` are simply just assigned on a per-run-basis? Like, "groups" aren't "assigned" anywhere in a cypress.json file (or any file), but rather the "group" must manually be passed in each specific run and with a manually specified path that my "<group name>" is referencing? and I need to manually specify a group name and path every time I run the command because the "group" is only being assigned inside each individual run rather than being referenced as a variable from a file somewhere?

**Comment by jennifer-shehane** [comment]
>Or is this documentation stating that groups are simply just assigned on a per-run-basis? 

Yes

>Like, "groups" aren't "assigned" anywhere in a cypress.json file (or any file), but rather the "group" must be manually passed in each specific run and with a manually specified path that my "group name" is referencing? 

Yes. 

>and I need to manually specify a group name and path every time I run the command because the "group" is only being assigned inside each individual run rather than being referenced as a variable from a file somewhere?

Yes. 👍 

You can pass in a group name through `cypress run` or using our Module API. 

- https://on.cypress.io/command-line#cypress-run-group-lt-name-gt
- https://on.cypress.io/module-api#cypress-run

Cypress only reads the group name at runtime, we do not look anywhere else for groups. We will associate separate `cypress run` with the same group name passed and put them in the same group. The usefulness of groups is to create the separate sections within a single 'Run' in the Dashboard view. 

We are working on building out 'tags' which may fit your usecase better https://github.com/cypress-io/cypress/issues/2561 - I'm not sure since you didn't detail your exact endgoal. 

This repo is only for issues relating to Cypress as a product, not our documentation. If you want to open an issue for our documentation, you can open it [here](https://github.com/cypress-io/cypress-documentation/issues/new). This issue was closed in this repository due to this.

**Comment by ChaseBig** [comment]
@jennifer-shehane 

Perfect, I appreciate you taking the time to confirm these points. 

Thank you.

**Comment by anveshpuli** [comment]
Just wanted know, while using the command cypress run from command line, it starts running the total number of test files in the Integration folder. Now, cypress gonna open the browser broswser as specified and runs each test file individually and instead can we run all the test files at once ???

**Comment by jennifer-shehane** [comment]
During `cypress run` each test file is run individually - with the browser being closed and reopened in between each spec file. There is no way to 'run all' during `cypress run`. https://github.com/cypress-io/cypress/issues/1586
