### ISSUE TITLE
cy.tick is not working as expected when setTimeout is invoked from the application

### ISSUE THREAD

**Issue by desaiuditd** [cypress-io/cypress#5305]
As per the documentation and the example is given there, it suggests that the `setTimeout` should be called from the Cypress test suite. But often it's not the case. In most of the cases, `setTimeout` is invoked from within the application based on certain business logic/rule. Is that case, `cy.tick()` is not behaving as expected.

I've created a demo app in a repository to show the use case.

I'm invoking the `setTimeout` from the application code here
https://github.com/desaiuditd/demo-cypress-clock-tick/blob/master/public/index.html#L20

And I'm checking for the result in the Cypress test here (which is failing)
https://github.com/desaiuditd/demo-cypress-clock-tick/blob/master/cypress/integration/cypress-clock.js#L14

### Current behaviour:
The cypress suite fails to test the effect that happens after `setTimeout` is invoked from the application.
![2019-10-08 14 14 51](https://user-images.githubusercontent.com/2236554/66364697-60558000-e9d6-11e9-9f74-64291ccb607b.gif)

### Desired behaviour:
Cypress should allow to test the effect of `setTimeout` even if it is invoked from the application.

### Steps to reproduce: (app code and test code)
- Clone the repo - https://github.com/desaiuditd/demo-cypress-clock-tick/
- Install dependencies. `yarn install`
- Start dev server. `yarn start`
- Open `http://localhost:300` to see the application.
- In another terminal, start Cypress suite. `yarn run cypress open`
- Observe that the tests are failing. The same test is passed, if I invoke the setTimeout from the test suite.

### Versions
Cypress: 3.4.1
OS: MacOS Mojave 10.14.6
Browser: Chrome 77.0.3865.90 (Official Build) (64-bit)

**Comment by Nume** [comment]
I've had similar issues with `cy.clock` and my conclusion is that the implementations will be switched when calling `cy.clock` but cypress won't modify native implementations that already have been called before that.
In your case that means that `setTimeout` must be called after `cy.clock` has been called because its only after `cy.clock` that the implementation of `setTimeout` will be replaced 

With that in mind i changed your example with this diff:
```
 diff --git a/cypress/integration/cypress-clock.js b/cypress/integration/cypress-clock.js
index 3e79279..68286aa 100644
--- a/cypress/integration/cypress-clock.js
+++ b/cypress/integration/cypress-clock.js
@@ -3,12 +3,11 @@

 describe( 'Cypress Clock & Tick', () => {
     before( () => {
+        cy.clock();
         cy.visit( 'http://localhost:3000' );
     } );

     it( 'works', () => {
-        cy.clock();
-
         cy.tick( 10000 );

         cy.get( '#header' ).should( 'have.text', 'Hello, World' );
```
And now the test passes

**Comment by desaiuditd** [comment]
Ah. Okay. That worked. Thanks.

Closing this one.

**Comment by franiakat** [comment]
@Nume Unfortunately when I move `cy.clock()` to before block the `cy.visit` is returning an empty page, which works correctly otherwise.
