### ISSUE TITLE
SyntaxError: Expected atom at position 0     {(.+)}  ^ while parsing file

### ISSUE THREAD

**Issue by nakhodkin** [cypress-io/cypress#5308]
### Current behaviour:

I have the following piece of code that causes an error in Cypress:

<img width="1219" alt="Screen Shot 2019-10-08 at 5 35 19 PM" src="https://user-images.githubusercontent.com/14351638/66404957-0c589480-e9f2-11e9-8258-e6744ac52397.png">

```javascript
const o = {
  "id": 221,
  "data": "Hello Dave"
};

const s = JSON.stringify(o, null, 2);
const p = s.replace(/{(.+)}/s, '$1');
```

The problem comes from RegExp that I'm using in the following line
```js
const p = s.replace(/{(.+)}/s, '$1');
```

So basically to make this to work I have to escape curly braces as I did here
```
const p = s.replace(/\{(.+)\}/s, '$1');
```

It's strange that the erroneous behaviour tightly coupled with the presence both of curly braces and RegExp dot all flag, the following line will work without errors though.
```js
const p = s.replace(/{(.+)}/, '$1');
```
### Versions

Cypress: `3.4.1`
OS: `macOS Mojave 10.14.6`
Browser: `Chrome Version 77.0.3865.90 (Official Build) (64-bit)`

**Comment by jennifer-shehane** [comment]
Found this mentioned in babel https://github.com/babel/babel/issues/8951 @chrisbreiding

**Comment by sainthkh** [comment]
The external cause(babel/babel#8951) is fixed. Close this.

**Comment by Onur325** [comment]
print("onur")
