### ISSUE TITLE
CLI flag --detached on `cypress open`

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#531]
Instead of `cypress open` always opening a detached process we should change that to *not* open a detached process but accept a new flag `--detached` which will replicate the existing behavior.

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
