### ISSUE TITLE
Please add recommendations of CPU/memory to system requirements documentation

### ISSUE THREAD

**Issue by stark525** [cypress-io/cypress#5317]
### Current behavior:
Hello, I was wondering if there were minimum CI requirements for running Cypress on CI (EC2 instances + Jenkins, specifically). I'm seeing network timeouts and I'm not sure if this is due to the cpu, memory, or network performance of the EC2 instances. I've tried t3.medium (low-to-moderate network) and m3.medium (moderate network), but still experience timeouts that I don't experience on my Macbook pro.

### Desired behavior:
I believe there should be a section under https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements that includes the minimum recommended CPU and memory requirements. This will allow developers to set up a CI pipeline using Cypress that will produce results similar to their experience on their own workstation (or at least be able to rule these factors out if they do see a difference).

### Steps to reproduce: (app code and test code)

This is a documentation feature request, I am hoping someone at Cypress knows this information. I've asked twice in the Gitter and haven't received a response. I'm hoping this is a quick fix for someone on the team.

### Versions

N/A

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to the Cypress product. If you want to open an issue on our documentation, you can open it [here](https://github.com/cypress-io/cypress-documentation/issues/new). This issue will be closed in this repository.

We've internally discussed ways to detect the machines CPU and warn when it is low or detect especially when it is too low during video recording here: https://github.com/cypress-io/cypress/issues/5061

**Comment by jennifer-shehane** [comment]
Also, I will add that we've experimented with restricting CPU here and its effects noted: https://github.com/cypress-io/cypress/issues/4722#issuecomment-515562987. I'll try and get with the team and see if they have recommendations we can document.

**Comment by csvan** [comment]
We use c6i.large in AWS for our tests and it's working fine
