### ISSUE TITLE
Why is cypress run different from cypress open with the same browser and the same configuration?

### ISSUE THREAD

**Issue by zadigus** [cypress-io/cypress#5318]
### Current behavior:

`cypress open` and `cypress run` do not provide the same tests results.

Configuration is the very same, `--browser chrome` is used in both cases. Upon running the tests with `cypress run`, I really am running the chrome browser, as I do when I run `cypress open`.

### Desired behavior:

`cypress open` and `cypress run` provide the same tests results.

### Steps to reproduce: (app code and test code)

How to reproduce:

1. Clone the repo (don't worry, it's small)
```
git clone --branch setup-build-definition https://github.com/shopozor/consumer-frontend
cd consumer-frontend
git submodule init
git submodule update
```
2. download the npm packages
```
yarn
```
3. start app
```
yarn start:dev
```
4. run `cypress run`
```
yarn cypress:integration
```
Here I have errors.
5. run `cypress open`
```
yarn cypress:open
```
Make sure you select `Chrome 77`. Run all the tests. There I have no errors (except one that is normal because I have a test where I expect true to be false).

### Versions

Tested on ubuntu 18.04 and Windows 10. 
Cypress version 3.4.1.
Browser: Chrome 77

**Comment by jennifer-shehane** [comment]
I'm getting this error trying to run your repo. I ran the installation suggestion, but the error continues

```
 ERROR  Failed to compile with 3 errors                                                                                                                                                               11:11:56

These dependencies were not found:

* @gql/calls/activateConsumer.graphql in ./src/store/user/actions.js
* @gql/calls/login.graphql in ./src/store/user/actions.js
* @gql/calls/signup.graphql in ./src/store/user/actions.js

To install them, you can run: npm install --save @gql/calls/activateConsumer.graphql @gql/calls/login.graphql @gql/calls/signup.graphql
```

Please provide a repo with all dependencies available from an outside contributor.

**Comment by zadigus** [comment]
@jennifer-shehane you must have forgotten a step in my description. That is exactly what I do on my build server with fresh clones. Have you really done the submodule init and update? From the message you obtain, it seems like files are missing. They are located in the graphql submodule. Also, you only need to call yarn to install everything, no npm.

**Comment by jennifer-shehane** [comment]
Yup! That did it. I saw 'clone the repo' and glazed over. 😝 

I'm running in Chrome Version 77.0.3865.90 on a macOS Mohave machine.

I am seeing multiple failures during `yarn cypress:integration`, saw 4 one time and 6 another time. All of which seem to be related to an error like `Expected to find element: ..., but never found it.`

<img width="1659" alt="Screen Shot 2019-10-09 at 1 36 43 PM" src="https://user-images.githubusercontent.com/1271364/66505757-f56d7d00-ea99-11e9-8b81-27bc98416afa.png">

I am seeing 1 failure during both `yarn cypress:open` and `yarn cypress:integration`

<img width="458" alt="Screen Shot 2019-10-09 at 1 38 04 PM" src="https://user-images.githubusercontent.com/1271364/66505826-1a61f000-ea9a-11e9-8151-9712c1a57a98.png">


The one consistent failure is because `expect(true).to.be(false)` should be `expect(true).to.be.false`

This doesn't seem to be the same behavior you are detailing, so we'd have to get on the same page to recreate the same behavior.

**Comment by zadigus** [comment]
That's exactly the behavior I have. Why do I get the failures «Expected to find element...» in one case and not in the other case? The common failure where false is expected to be true is clear.

**Comment by zadigus** [comment]
So, to be more explicit about the problem: you notice that `yarn cypress:integration` runs
```
wait-on http://localhost:4000 && cross-env CYPRESS_baseUrl=http://localhost:4000/# cypress run --env configFile=integration --browser chrome
``` 
Then, in the console, you see (of course, the start of the path to the `integration.json` file will be different in your case)
```
loading cypress config file:  D:\workspace\shopozor\consumer-frontend\common\cypress\config\integration.json
```
That means that the `common\cypress\config\integration.json` config file is used to run the tests. I made sure that `./cypress.json` is empty. In addition, I made sure that `common\cypress\config\integration.json` contains the very same values as those used in `yarn cypress:open` (I ran `yarn cypress:open`, then I browsed the settings menu and put all the values I found there in the `common\cypress\config\integration.json` file). That way, I ensured that I really am using the very same configuration in both cases.

Yet, the test results are different.

**Comment by zadigus** [comment]
By coincidence, I was able to see this:

![image](https://user-images.githubusercontent.com/8761254/66583997-99cbee00-eb84-11e9-81d0-d8710e35c5a3.png)

So on the left side, you see one of Cypress' error message in red. On the right, you see a console view of the current application state. On the left side, Cypress complains about `enabled` class not being included. On the right side, you clearly see that class `enabled` is present in the `classList`.

**Comment by jennifer-shehane** [comment]
I would suggest narrowing down the variables involved here so that we can clearly focus on what is causing the issue. 

- Narrow it down to a single failing simple test case
- Remove as much extra config as possible while still having the test failures discrepancies.

After that I would compare the Test Runner command log within each run to see if there is some timing variability between the 2 runs.

**Comment by zadigus** [comment]
I strongly suspect that the following code is the problem (corresponds to one of the failing tests): 
```
cy.get(`[id="pageLink->${label}"]`)
 .then(
    link => link[0].classList.value
  ).should('include', 'isActive')
```
How can I rewrite that in a more cypress-friendly way? I mean, I'm pretty sure that the `then` step is the problem here because there is no way cypress can wait until `isActive` is present in `link[0].classList.value`. Am I seeing that right? It's probably pure coincidence that it works in one case.

**Comment by zadigus** [comment]
So, I changed the above code to
```
cy.get(`[id="pageLink->${label}"]`)
 .first()
 .should('have.class', 'isActive')
```
and it's working. I believe you are right, @jennifer-shehane, it's a usability issue. We are using Cypress wrong. Thanks for the help!

**Comment by zadigus** [comment]
To fix the 2nd failing test, I replaced
```
cy.get('button[id="createAccount"]')
  .then(btn => {
    expect(btn).to.have.class('enabled')
  })
```
with
```
cy.get('button[id="createAccount"]')
  .should('have.class', 'enabled')
```

**Comment by zadigus** [comment]
I have no clue about why 
```
cy.get('[id="emailSentDialog"]').should('be.visible') 
```
doesn't work. It's supposed to be a dialog that pops up like this:

![image](https://user-images.githubusercontent.com/8761254/66646234-e1568680-ec25-11e9-80a5-ce8324b34522.png)

It doesn't appear in Electron and it doesn't appear in run mode with Chrome, even though with `cypress open` it appears in Chrome.

**Comment by zadigus** [comment]
All the tests are green. It was really a misuse of Cypress.

**Comment by gkgeorgiev** [comment]
Unfortunately there are too many of those "misuse" cases, which could speak of design flows, cos a well defined API shouldn't have "misuse".
