### ISSUE TITLE
Ability to save text outside of closure 

### ISSUE THREAD

**Issue by ayandebbarman** [cypress-io/cypress#5322]
### Current behavior: 

Currently cypress provides ability to get text content using invoke text. However my scenarios is i have to go through items of cart get price text and then sum it
So while for one element `cy.get().invoke('text).then()` works i need ability to store the text value for each of cart so something like

```js
let price1 = cy.get().invoke('text')
let price2 = cy.get().invode('text)

total = price1+price2+.....
```

verify that total is matching total

**Comment by jennifer-shehane** [comment]
Check out using aliases. https://on.cypress.io/variables-and-aliases

**Comment by ayandebbarman** [comment]
I have tried that but didn't work for me not sure if i am missing something below is mock it. Please note i further need to split the texts to get the value and then sum it coz the text i would get is like $50 and i need split it to get 50 for all cart items and then sum it


    it.only('should compare text',()=>{

        cy.get('h6').invoke('text').as('text1')
        cy.log(this.text1)

    })

**Comment by jennifer-shehane** [comment]
@ayandebbarman Check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by ayandebbarman** [comment]
@jennifer-shehane Sorry i should have commented back here .... I figured it out. Thanks for pointing to right direction

**Comment by oronshvartz** [comment]
I have the same problem
What is your solution?

**Comment by ayandebbarman** [comment]
> I have the same problem
> What is your solution?

Basically used 2 different strategies

1. Instead of capturing data at UI used cy.route() to interpret the api response and used validations using that

2. Used jquery and wrote validations inside then()

something like
cy.get('h6').then(($el)=>{
let txt = $el.text()
cy.get('span').contains(txt).should('exist')

})

**Comment by nikhiletc** [comment]
but how are you going to use outside `txt` ?

**Comment by ayandebbarman** [comment]
I actually ended up doing my validations in the same test but if you want you can save the text in an outside file using cy.writeFile and then read it in different block

**Comment by nikhiletc** [comment]
> I actually ended up doing my validations in the same test but if you want you can save the text in an outside file using cy.writeFile and then read it in different block

well. i wrote 2 small tasks **putCache** it will hold the data and  **getCache** it will release the holding data, which i can use anywhere i want

**Comment by spsingham1902** [comment]
> well. i wrote 2 small tasks **putCache** it will hold the data and **getCache** it will release the holding data, which i can use anywhere i want
Can you share code for putCache and getCache

**Comment by nikhiletc** [comment]
/cypress/plugins/index.js

```
module.exports = (on, config) => {
  on('task',{
 putInCache: ({ key, data }) => {
      return (cache[key] = data);
    },
    getCache: (key) => cache[key],
});
}
```
