### ISSUE TITLE
Cypress.env('') cant access CircleCi's `CYPRESS_<env-variable>` if cypress root directory lives outside of the repo project root 

### ISSUE THREAD

**Issue by ChaseBig** [cypress-io/cypress#5334]
### Current behavior:

My codebase is of the monorepo architecture with 20+ packages each with their own `package.json` (path: `<root>/packages/<monorepo-packages>/*`). 

I first implemented cypress at the project root folder (path: `<root>/cypress/*`) and held all of my tests inside of this `./cypress/*` folder. 

Many of my tests are UI tests to confirm login/logout functionality works, as such, the `password` secrets needed to be set as an env variable as to not have them checked-in to the repo on github. 

I decided to go the `cypress.env.json` route and hold all of my secrets in this file at the root of the project (path: `<root>/cypress.env.json`) as designed and then added the various `CYPRESS_<env-variable>`'s to CircleCi's Environment Variables configuration table. 

This was working great and all my tests that were using `cy.get('[data-testid="password-field"]').type(Cypress.env('secret-token')` were working great locally and via runs on CircleCi. 

We now have over 40 api/ui tests and builds are approaching +20min. To help with this, I segmented-out the tests into three specific packages and installed cypress inside each of these three packages so the tests respective to each package are only found inside of the package that relates to them. This way I could configure scripts to check if there were any changes to any one of the three packages and only run tests against changed packages rather than running all tests on every build regardless of whether there were relevant package changes or not. 

I've _MOSTLY_ been successful with this implementation, but I'm having an issue now with my tests being able to find the `CYPRESS_<env-variable>` configuration on circleCi now that the cypress test files have been moved inside three packages instead of at the `<root>/cypress/` folder. 

To resolve this issue locally, I just needed to add a `cypress.env.json` file to each of the three packages and it works great when running tests on my local machine. But, for some reason the `(Cypress.env('<env-variable>')` in my test isn't able to access the `CYPRESS_<env-variable>` configuration in CircleCi's Environment Variables table. 

It's almost as if CircleCi's Environment Variable configuration table is now out of reach due to the fact that the tests are now living in `<root>/packages/<package-name>/cypress/*` rather than at the project root `<root>/cypress/*`.

The tests work locally but when tests are executed in CircleCi, they're returning this failure error for steps using `cy.get('[data-testid="password-field"]').type(Cypress.env('<env-vairable>')`

![Screen Shot 2019-10-10 at 7 01 15 AM](https://user-images.githubusercontent.com/10504626/66566937-c9024100-eb2b-11e9-8b83-bf8e66e37cf5.png)

### Desired behavior:

Regardless of where the `cypress/*` directory lives, whether that's at the project root or inside of individual packages under the project root, the test should be able to access CircleCi's `CYPRESS_<env-variable>`'s variables. 

FWIW, I DO still have a `cypress/*` folder in at the project root but have removed the "integration" folder. I also have identical `cypress.json` and `cypress.env.json` files at the project root _and_ in each of the three individual packages. 

### Steps to reproduce: (app code and test code)

This is difficult to really reproduce without having a monorepo architecture repo handy... I'd rather not post screenshots of my file structure as our github repo is private. But below you'll see my best attempt at offering steps. 

1) Open a monorepo repository on your local machine
2) `cd` into one of the monorepo package roots
3) install cypress in the package repo rather than at the 

### Versions

Cypress 3.4.1 
CircleCi 2.0
Most recent chrome/electron versions

**Comment by bahmutov** [comment]
You could create an empty monorepo and same folder structure with dummy packages and make it into public repo and connect CircleCI to show the problem. Otherwise it is hard to say what is going on - and why running Cypress from subpackage would affect _anything_ in regards to reading environment variables. Are you sure the variables are injected correctly? Are you sure the environment variables are not somehow overriden from the `env` files?

You can run Cypress locally with env variables then open the "Settings" tab to see what Cypress see https://docs.cypress.io/guides/references/configuration.html#Resolved-Configuration

```
CYPRESS_password=foo npm run cy:open
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
