### ISSUE TITLE
ensure up-to-date page state when finishes "type" command in react/redux apps

### ISSUE THREAD

**Issue by bencao** [cypress-io/cypress#534]
* Operating System: MacOS
* Cypress Version: 0.19.2
* Browser/Browser Version: Electron 53

### Are you requesting a feature or reporting a bug?

Requesting a feature. Please advice a better solution for the following case.

### Case Description:

*Context*

the page is built with react/redux

*Scenario*

Assume there's a form to update current user first name, it has a "first name" input box and a submit button.

```
cy
  .get('#first_name'))
    .type("abcd")
  .get('#submit')
    .click()
```

*Problem*

the first name received by server is **not stable**, sometimes it is "abc" and sometimes it can be "abcd".

*Root Cause Analysis*

In the above assumed redux app, an input box change will trigger an action to be dispatched, and be processed by the root reducer to create a new "page state object".
If user typing happens really fast, the following scenario can happen:

1. user types abcd, which creates 4 actions, with input value "a", "ab", "abc", "abcd" as payload respectively
2. at the time user click on 'submit', the first a few actions has been processed, but the last one action with input value "abcd" is still in the queue, so the "page state object" still has input value "abc"
3. the callback of submit get "current" input value from "page state object", and find it to be "abc"
ajax call with first name value "abc" is sent to the server

*Current Solution*

Current solution I have is to add an additional should assertion on the input box itself, which will "wait until" the input box actually renders the exact value we want, which is a signal that the "page state object" has already been updated:

```
cy
  .get('#first_name')
    .type('abcd')
    .should('have.value', 'abcd')  // use should to wait until input box actually shows the abcd value
  .get('submit')
    .click()
```

**Comment by brian-mann** [comment]
Full discussion for this is here: https://gitter.im/cypress-io/cypress?at=593ab439f2dd2dba068560c3

I would be in favor of adding a `delay: 0` special scenario to `cy.type` which turns all the keystrokes from being async to sync.

**Comment by Bkucera** [comment]
I think this is a feature of Cypress, and will help users catch race conditions for bugs that happen to fast-typing users. 
However, I believe the solution to this is actually a global 'waitBeforeEachCommand' option that users have requested elsewhere.
