### ISSUE TITLE
Additional web page files not loaded using auth settings

### ISSUE THREAD

**Issue by rubenreyes2000** [cypress-io/cypress#5340]
### Current behavior:

When running a test on a site that uses HTTP Basic Auth, the URL opened with `cy.visit` or `cy.request` properly handles the `auth` options, but any web page files (e.g. CSS, JS, images) called from the web page and hosted on the same domain and path, do not use the `auth` options.

Those files fail loading with error 401 (Unauthorized).

This leads to broken pages and JS errors. and ultimately failed tests.

### Desired behavior:

To work like a regular browser (e.g. when testing on Chrome), the auth settings are automatically used for subsequent requests to the same domain/path (I am unsure how this is handled)

### Steps to reproduce: (app code and test code)

1. Go to http://rubenreyes2000.orgfree.com/httpbasicauth/ on your browser, and use `guest` for username and password. You will see that the browser loads related CSS and JS files stored in the same path.
2. Create a test spec with the following code:
```js
/// <reference types="Cypress" />

describe('HTTP Basic Auth', () => {
  it('Loads js and css files', () => {
    cy.visit('http://rubenreyes2000.orgfree.com/httpbasicauth/', {
      auth: {
        user: 'guest',
        password: 'guest'
      }
    })
  })
})
```
3. Run the test on Electron. Open the Inspector and check the Network tab. You will see that loading of `main.css` and `main.js` fails with error 401 (Unauthorized). Because the JS file is not loaded there is an unhandled JS error in the page and the test fails.

### Versions

Cypress 3.4.1
Electron 61
Windows 10

**Comment by rubenreyes2000** [comment]
I forgot to mention that I tried using Authorization header instead, with the same result:

```
/// <reference types="Cypress" />

describe('HTTP Basic Auth', () => {
  it('Loads js and css files', () => {
    cy.visit('http://rubenreyes2000.orgfree.com/httpbasicauth/', {
      headers: {
        Authorization: 'Basic Z3Vlc3Q6Z3Vlc3Q='
      }
    })
  })
})
```

**Comment by jennifer-shehane** [comment]
@rubenreyes2000 Your example attached was not providing the correct key for the `auth` option as documented. `user` should be `username`. https://on.cypress.io/visit#Add-basic-auth-headers Please confirm you are sending the correct key.

I was able to see the css and js resources load correctly in both Chrome and Electron after passing in the correct `username` key in Cypress 3.4.1 on a macOS Mohave.

This example also worked with the second example for me with the Authorization header.

<img width="1175" alt="Screen Shot 2019-10-10 at 1 29 06 PM" src="https://user-images.githubusercontent.com/1271364/66591883-f538b480-eb61-11e9-8b89-1094a7374007.png">


Please comment if I am missing something and we can reopen - are you behind a proxy? Can you isolate to Windows OS? Something in your configuration not included?

**Comment by rubenreyes2000** [comment]
Oh boy.... that was dumb of me.... sorry... changing to `username` "magically" fixed it...  :anguished:
