### ISSUE TITLE
Types for Cypress.Commands.overwrite are incorrect - does not take command options

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5341]
### Current behavior:

```js
    Commands: {
      add(name: string, fn: (...args: any[]) => void): void
      add(name: string, options: CommandOptions, fn: (...args: any[]) => void): void
      overwrite(name: string, fn: (...args: any[]) => void): void
      overwrite(name: string, options: CommandOptions, fn: (...args: any[]) => void): void
    }
```

### Desired behavior:

```js
    Commands: {
      add(name: string, fn: (...args: any[]) => void): void
      add(name: string, options: CommandOptions, fn: (...args: any[]) => void): void
      overwrite(name: string, fn: (...args: any[]) => void): void
    }
```

### Steps to reproduce: (app code and test code)

https://github.com/cypress-io/cypress/blob/a038e7f5d4c56d3efa844e745da40a3d917fefea/packages/driver/src/cypress/commands.coffee#L151-L152

### Versions

3.4.1

**Comment by jennifer-shehane** [comment]
@CSchulz Yeah, this seems to be completely true, which means the docs are incorrect as well. https://on.cypress.io/custom-commands#Syntax 

I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document the `options` not being available during `overwrite` here: https://github.com/cypress-io/cypress-documentation/issues/2147.

**Comment by jennifer-shehane** [comment]
I've opened a PR to fix the typings here: https://github.com/cypress-io/cypress/pull/5347
