### ISSUE TITLE
Windows 10 does not load cypress extension on Chrome 77 or Chomium 79

### ISSUE THREAD

**Issue by jeremyGrannanSEL** [cypress-io/cypress#5342]
### Current behavior:

When running a test in either Chrome 77 or Chromium 79 the browser opens but the extension does not load. This works on Ubuntu 18.04 with the same configuration files.

Troubleshooting steps taken:

- Tested on multiple Windows machines. 2 of the machines are administered by our company. The other machine was a system that was not on our network nor administered by our company.
- Tested Chromium
- Tested both `cypress open` and `cypress run --browser Chrome/Chromium`
- Installed a local copy of Cypress with examples on both administered and non-administered machines. `npm install cypress --save-dev`

### Steps to reproduce:

Install Chrome 77 
Install Cypress 
Run `cypress open`
Run test

### Versions

Tested On:
Cypress 3.4.1
Chrome 77.0.3865.90
Chromium 79.0.3937.0
Ubuntu 18.04 - worked as expected
Centos 7 - worked as expected
Windows 10 64 bit Version 1803 OS build 17134.556
Windows 10 64 bit Version 1803 OS build 17134.1006

**Comment by jennifer-shehane** [comment]
@jeremyGrannanSEL Thanks for opening this issue. Could you detail more about what you mean by 'the extension does not load'. 

What are you seeing? How are you assessing the extension is 'not loading'? Are you getting an error somewhere? Screenshots are ideal. Thanks!

**Comment by jeremyGrannanSEL** [comment]
This is what I see when running it with either command:
![image](https://user-images.githubusercontent.com/55515103/66598323-a71db400-eb55-11e9-89e8-4d61dfa0947e.png)

**Comment by jeremyGrannanSEL** [comment]
Here is the console log:
![image](https://user-images.githubusercontent.com/55515103/66598373-c3215580-eb55-11e9-9e0d-6c6bfbd0c2f5.png)

**Comment by flotwig** [comment]
@jeremyGrannanSEL How do you have Chrome installed? It looks like none of the command-line arguments Cypress passes are being accepted by Chrome.

**Comment by jeremyGrannanSEL** [comment]
Downloaded and installed. I tried both Chrome and Chromium with the same warnings

**Comment by flotwig** [comment]
Downloaded from where?

**Comment by jeremyGrannanSEL** [comment]
https://www.google.com/chrome/
and
https://www.chromium.org/Home

**Comment by flotwig** [comment]
Can you visit `chrome://policy` in the browser and share the contents please?

**Comment by jeremyGrannanSEL** [comment]
![image](https://user-images.githubusercontent.com/55515103/66598756-99b4f980-eb56-11e9-913e-f3361ed93f94.png)

**Comment by flotwig** [comment]
Strange, it should work on the computer with no policies set... can you share the entire DEBUG logs from the time you start Cypress to when you launch Chrome on that computer?

Instructions: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

**Comment by jeremyGrannanSEL** [comment]
This is the only thing I get when following the instructions:
![image](https://user-images.githubusercontent.com/55515103/66760931-e438bd80-ee57-11e9-9e44-c2263fcf7514.png)
