### ISSUE TITLE
Run e2e tests in all browsers by default

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#5357]
### Current behavior:

e2e tests only run on 1 browser at a time. To run on multiple browsers requires multiple e2e tests.

### Desired behavior:

* Run an `electron-e2e-tests` stage and a `chrome-e2e-tests` stage that set `E2E_BROWSER=electron/chrome` respectively
* For each e2e test:
	* If a `browser` field is not specified...
		* Run the test against all browsers individually
	* If `browser` is specified and a string, run the test in that browser individually
	* If `browser` is specified and an array, run the test in those browsers individually
* When running a test against an individual browser:
	* If E2E_BROWSER is set and is not the current browser, bail since the current test is not meant for the current stage
* By default, only 1 snapshot will be saved per test, and all browsers should conform to that snapshot
	* can be overridden with `snapshotPerBrowser: true`

**Comment by jennifer-shehane** [comment]
This has been released.
