### ISSUE TITLE
Skipped test icon looks too much like a stuck spinner

### ISSUE THREAD

**Issue by krokofant** [cypress-io/cypress#5366]
### Current behavior:
![image](https://user-images.githubusercontent.com/5908498/66764508-35719d00-eeaa-11e9-860b-ea4953a667ef.png)

### Desired behavior:
A better icon - I've looked through Font Awesome and didn't find anything especially good.

### Steps to reproduce: (app code and test code)
```javascript
/// <reference types="Cypress" />
describe('Login page integration', function() {
	it.skip('foo', () => {

	});
});
```

### Versions
Cypress 3.4.1

**Comment by blumk** [comment]
Proposal:
![image](https://user-images.githubusercontent.com/2436496/66911445-cf535a00-f010-11e9-8723-417848b381af.png)

![image](https://user-images.githubusercontent.com/2436496/66911599-20fbe480-f011-11e9-81c2-ff3774c52600.png)

https://fontawesome.com/icons/ban?style=solid

**Comment by krokofant** [comment]
@blumk Looks great to me!

**Comment by krokofant** [comment]
Related issue https://github.com/cypress-io/cypress/issues/3092

Seems _skipped_ and _pending_ is not what you'd expect it to mean because cypress mimics the mocha design. The image seen in this issue is for a test with pending status. So not only is the terminology weird the ui is weird because of it.
