### ISSUE TITLE
cy.visit does not send headers / change HTTP method when baseUrl contains `:80`

### ISSUE THREAD

**Issue by Richard-Walton** [cypress-io/cypress#5367]
### Current behavior:

`cy.visit({ url, method, headers })` does not appear to honour the `method`, or `headers`

### Desired behavior:

`cy.visit({ url, method, headers })` should send the specified method and headers.

### Steps to reproduce: (app code and test code)

```
cy.visit({ 
  url: '/ui', 
  method: 'POST',
  headers: {
    'mock-user': JSON.stringify(mockUser)
  }
});
```

I include an annotated Cypress debug log:

![debug-log](https://user-images.githubusercontent.com/481427/66814784-1537f180-ef2f-11e9-9252-b32527a9d9ed.png)

Changing the method to `GET` still results in the headers not being sent 

### Versions

I tested Cypress 3.4.1 and 3.2.0.
Ubuntu LTS
Chrome 77

### UPDATE: Cause tracked down to: https://github.com/cypress-io/cypress/issues/5367#issuecomment-542329058

**Comment by Richard-Walton** [comment]
Ok, something odd is going on here.

`cy.request` works (Passing the same `url`, `method`, and `headers` as I use in `cy.visit`).

BUT, I can get `cy.visit` to work.   My app lives behind a load balancer.   If I make my tests target the app directly (rather than going via the LB) the visit command works.  

I'm not sure how to explain that behaviour?!  `cy.request` works in both cases.  The LB logs show that Cypress `cy.visit` doesn't send the headers etc (I don't think the LB is stripping them out... especially given `cy.request` works)

**Comment by Richard-Walton** [comment]
Further info:  There is definitely some Cypress-level caching going on which I've just noticed.

The first time I run the tests (with `cy.visit({ url, method, headers })`) I see two requests made to my server... the first request contains correct method/headers, the 2nd is a GET without headers.

The first request/response is seemingly ignored, and the 2nd response is provided to the test runner.

Afterwards, clicking the re-run tests button results in only 1 request being made to my server (The one without the correct method/headers).

It almost feels like a CORS issue (two requests made, but in a CORS situation the first request is usually an OPTIONS req)... ?

**Comment by Richard-Walton** [comment]
So, it seems the cookie header persists between the two requests (as long as the cookie is set via `cy.setCookie`.  That's the only workaround I can see right now - to set my mock data in the cookie.  Though this doesn't solve the method always being a GET (even when POST is specified).

**Comment by flotwig** [comment]
> Further info: There is definitely some Cypress-level caching going on which I've just noticed.

Yes, I can shed some more light on this:

`cy.visit()` doesn't actually do a normal Javascript navigation (for example, by setting `window.location.href` or submitting a `<form>`). Instead:

1. cy.visit asks the Cypress backend to retrieve the remote content (the red arrow from your annotation)
2. Once it receives the response from the backend, it validates the content (is HTML, is a 200 status code, ...)
3. If it's a valid response, it is cached
4. Then, the frontend is navigated to the requested URL using a normal HTTP GET with no special headers (the blue arrow from your annotation)
5. The Cypress proxy serves the cached content from (3) in response

So, although you don't see the correct method and headers in DevTools, they are actually being sent in (2). Only one request is sent to the origin server in a cy.visit.

---

Are you 100% sure that your destination server isn't receiving a `POST`? I just tested locally on 3.4.1 and couldn't reproduce:

```js
it("", () => {
  cy.visit({
    method: 'POST',
    url: 'http://requestbin.net/r/165n5db1'
  })
})
```

Request received: 

![image](https://user-images.githubusercontent.com/1151760/66852101-365a0b80-ef4a-11e9-8810-c89871a5f5ff.png)

**Comment by Richard-Walton** [comment]
@flotwig Thank you for the reply.

Yes, my server does get a POST - But only the first time I start the test runner.  The response my server gives to the initial POST seems to be ignored as cypress makes a 2nd GET to the server immediately afterwards.  When the tests are re-run (i.e I don't close/re-open the test runner) the server only receives a GET.

**Comment by flotwig** [comment]
@Richard-Walton The 2nd GET (step 4 in my explanation) should not make it to your server. It's just pulling the response to your POST (step 3) from the proxy layer.

I hear what you're saying, but I can't reproduce this problem unfortunately. Can you provide a minimum reproducible example? A Git repo with a server setup that shows the problem would be perfect.

**Comment by Richard-Walton** [comment]
I would love to, but I'm not sure how.  The app being tested is running behind a load balancer (https://www.pulsesecure.net/products/virtual-traffic-manager/) - so the setup is a little complicated.  I'll have a think.

So, it seems perhaps, for _reasons_ that the 2nd request makes it to my server.  Perhaps the logic in the cypress backend for determining which requests it handles / vs which ones make it to the origin is buggy?  The only other bit of information I can offer is that the url I am visiting contains a query string param (http://cc2?version=<version>)... perhaps it is relevant.

**Comment by Richard-Walton** [comment]
Haha, I got it!  So...my baseURL is  set to `http://cc2:80`.

Removing the port fixes the issue.  So, I assume there is some cache code which doesn't take into account the presence/lack of presence of `:80` for HTTP requests?

**Comment by Richard-Walton** [comment]
@flotwig Any thoughts on the above^ ?

**Comment by flotwig** [comment]
Ugh, that definitely sounds possible. The `cy.visits` are cached by URL, maybe we're keeping the default port when storing the response but not when pulling it back out, or vice versa. Thanks for tracking this down, this should be pretty easy to fix now.
