### ISSUE TITLE
XHR.send() with undefined parameter

### ISSUE THREAD

**Issue by davidhennemann** [cypress-io/cypress#5379]
We are currently testing an application with a lot of legacy code. After opening the website cypress initially crashed with `Error 'Cannot read property '_setRequestBody' of undefined' in request to URL`. The error is thrown from within the `server.coffee`, where the XHR prototype is overwritten. 

```coffeescript
XHR.prototype.send = (requestBody) ->
        # ...
        proxy = server.getProxyFor(@)
        proxy._setRequestBody(requestBody)
        if not server.isWhitelisted(@)
          options.onSend(proxy, sendStack, route)
  
```

After following the call stack we figured out that the legacy application made a call `XHR.send(a)`, where `a` was `undefined`. This lead to the proxy variable to be undefined.
Obviously it's not really useful to make such a call, but maybe cypress could nevertheless check if the parameter is valid? After changing the corresponding source code to
```coffeescript
XHR.prototype.send = (requestBody) ->
        # ...
        proxy = server.getProxyFor(@)
        if typeof proxy != 'undefined'
             proxy._setRequestBody(requestBody)
             if not server.isWhitelisted(@)
                options.onSend(proxy, sendStack, route)
``` 

Are there any downsides involved with checking for the proxy to be defined?

**Comment by flotwig** [comment]
Hey, thanks for the report!

> After following the call stack we figured out that the legacy application made a call `XHR.send(a)`, where `a` was `undefined`. This lead to the proxy variable to be undefined.

Hmm, if I'm reading this right, it sounds like the Cypress implementation of `XHR.send` has a bug. It's totally valid to do `XHR.send(undefined)`, and it shouldn't cause Cypress to err.

It would probably be best to find out why `proxy` is null, or why the code is reaching this point, instead of adding a guard for `proxy` being null here. It doesn't really fix anything to do that except to hide a problem.

**Comment by davidhennemann** [comment]
Okay, i'll close this issue for now. It seems it occurred because the tested application messed with the prototype of XHR. Cypress also overwrites the prototype and in the end they overwrote each other.

**Comment by mayank13** [comment]
@davidhennemann : Facing a similar issue. How can this be fixed?

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
