### ISSUE TITLE
Proposal: add option to pass in an array of fixtures to cy.fixture

### ISSUE THREAD

**Issue by ryan-snyder** [cypress-io/cypress#5384]
### Current behavior:
Currently, in order to load multiple fixtures you have to do something like [this](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__fixtures/cypress/integration/multiple-fixtures-spec.js) or [this](https://github.com/cypress-io/cypress/issues/2932)

### Desired behavior:
It would be really nice from a user perspective if we could load multiple fixtures like so:
```js
cy.fixture(['file1', 'file2']).then(files => {
    cy.log(files); // [ firstFile, secondFile ]
}
```
Why this would be nice is that it makes the code a lot neater as well you don't have to navigate through callback hell especially if you're trying to load more than two or three fixtures at once. Personally, This would be nice to have for something like file uploads where you potentially want to upload more than one file at a time.

### Steps to reproduce: (app code and test code)
See links.
### Versions
Chrome: latest
Cypress: 3.4.1

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
