### ISSUE TITLE
Only first env variable is taken when using --env option

### ISSUE THREAD

**Issue by gustawx** [cypress-io/cypress#5391]
When I try to run tests with `--env firstEnv=value1,secondEnv=value2`, only first env variable is being picked up by Cypress. When i do `export secondEnv=value2` then it works as expected.

I use secondEnv to set the `testFiles` programatically in plugins/index.js in `module.exports = (on, config) => { ... }`, this might be some hint

Cypress 3.4.1

**Comment by jennifer-shehane** [comment]
Can you provide the code where you are reading the 'environment variable' - asserting that it is not set?

With the example provided, I can't isolate whether this is never writing the env var or whether it is a problem later reading the env var. 

Please also note that Cypress environment variables are *completely different* than environment variables set on your machine - they would need be be read in using `Cypress.env()` later in your test files. https://on.cypress.io/environment-variables

**Comment by gustawx** [comment]
ouch, i set this in `module.exports = (on, config) => {...}` and i notice that first env i get properly using `config.env.<name>` and second one using `process.env.<name>`.
Sorry for wasting your time...
