### ISSUE TITLE
Session storage returns outdated value

### ISSUE THREAD

**Issue by nicompa** [cypress-io/cypress#5392]
### Current behavior:

In the `pricing_loop` command (invoking `pricing_call`), the last `cy.log('cookie value end = ' + cookie_value)` returns `false`, although the value has been already updated to `true` in the `if` above. 

It seems like the session storage reverts back to the previous value, ignoring what happens within the context of `cy.wait`. Weird thing is, when I debug and pause the application, `window.sessionStorage` is returning the expected value (i.e. `true`).

```js
Cypress.Commands.add("pricing_call", (token,product) => {
  return cy
    .server()
    .route("GET", 'https://test-pricing' + product)
    .as("pricingCall")
    .window()
    .then(win => {
      var xhr = new win.XMLHttpRequest();
      xhr.open('GET', 'https://test-pricing' + product);
      xhr.setRequestHeader('apiKey', 'apikey')
      xhr.setRequestHeader('Authorization', 'Bearer ' + token)
      xhr.send()
    })
});


Cypress.Commands.add("pricing_loop", (token, product) => {
  var i = 0

sessionStorage.setItem('found_pricing','false');

  var cookie_value = sessionStorage.getItem("found_pricing");
  cy.log('cookie value start = ' + cookie_value)
    while(i<24 && cookie_value == 'false') {

      cy.wait(5000)

      cy.pricing_call(token,product)
  
      cy.log('debug start')

      cy.wait('@pricingCall').then(function(xhr) {

        var logged = JSON.stringify(xhr.response.body)

        console.log(logged)
        
        if (xhr.response.body != "") {

          cy.log('debug if')

          sessionStorage.setItem("found_pricing", "true");

          cookie_value = sessionStorage.getItem("found_pricing");
          
          cy.log('cookie value = ' + cookie_value)

        }
        cy.debug()

        cy.log('cookie value halfway= ' + cookie_value)  

      })

      cookie_value = sessionStorage.getItem("found_pricing");

      console.log(window.sessionStorage)
      cy.log('cookie value end = ' + cookie_value)

      i++
    }
  })
```

### Desired behavior:

Session storage values should be consistent across contexts.

**Comment by jennifer-shehane** [comment]
This has to do with mixing async and sync code, not the session storage. I can demonstrate this by replacing all of the cookies with static values as shown below. 

Irrespective of sessionStorage - the cookie value will always print false at the end with the way this is written. 

Please see our guide about Cypress commands being async https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous

```js
it('test', () => {
  let i = 0
  let cookie_value = false

  cy.log(`cookie value start = ${cookie_value}`)

  while (i < 24 && cookie_value == false) {
    cy.wrap('foo').then(function () {
      if (true) {
        cookie_value = true
        cy.log(`cookie value = ${cookie_value}`)
      }

      cy.log(`cookie value halfway= ${cookie_value}`)
    })

    cy.log(`cookie value end = ${cookie_value}`)
    i++
  }
})
```

<img width="438" alt="Screen Shot 2019-10-17 at 5 04 04 PM" src="https://user-images.githubusercontent.com/1271364/67047344-26842800-f100-11e9-955f-955a6e01976d.png">

**Comment by nicompa** [comment]
Clear thanks. How can I break out of a loop based on a value assigned within a cypress command then?

**Comment by jennifer-shehane** [comment]
I'd suggest checking out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
