### ISSUE TITLE
Broken ag-grid input cell 'type'ing

### ISSUE THREAD

**Issue by K41eb** [cypress-io/cypress#5394]
#5358 # Current behavior:

`type()`ing into an ag-grid cell that was either focused, get, or clicked on is broken: only the first character is typed in the cell.

(After hot reload, by saving the test file while Cypress is already running, it types the full word 'in place', each character overwriting the former one, eventually only leaving the last character in the cell)

### Desired behavior:

The full word in typed into the cell just like any other conventional input field.

### Steps to reproduce: (app code and test code)
Make a simple ag-grid and try to type something in a cell:
```js
cy.get('.ag-center-cols-container [row-index="0"] div:nth(1)').type('something')
```

### Versions

"cypress": "^3.4.1"
Windows 10
Chrome 77.0.3865.120

### Additional comments

I think it might be due to the way ag-grid handles inputs but at the same time Cypress is supposed to act just like an human user and it does not: clicking or focusing cells works just fine for me as I am able to type anything without any issue.

It's not about ag-grid responding too slowly as I have already trie to `wait()` before typing, it's not an input speed problem either as `type('something', { delay: 1000 })` didn't work, and I am able to manually input 3 keys at the same time and ag-grid has no problem writing all 3.

Any ideas?

**Comment by K41eb** [comment]
I finally got it to work but it feels a lot like a work-around and doesn't match standard user workflow at all:
```
    cy.get('.ag-center-cols-container [row-index="0"] div:nth(1)').focus()
      .type('{del}')

    cy.focused().type('something')
```

The `{del}` keypress is to [start editing the cell](https://www.ag-grid.com/javascript-grid-cell-editing/), which should have been trigerred by any other 'standard' keypress (e.g. alphanum characters) but for some reason it didn't work.

**Comment by jennifer-shehane** [comment]
Glad you found a workaround, albeit not ideal. This *may* be fixed in this PR which has a *lot* of fixes for typing that we've been working on for a while. https://github.com/cypress-io/cypress/pull/4870

Is there an example webpage that displays an ag-grid that could be visiting through Cypress or an example repo that already exists with this? Would need a quick way to reproduce this without starting an angular project with ag-grid from scratch.

**Comment by Bkucera** [comment]
just confirmed its fixed in #4870 , did not dig into exactly why however

**Comment by K41eb** [comment]
It loks like I slept on my workaround, and my github notifications too. Can confirm it works now.

**Comment by LMFinney** [comment]
I'm still seeing this, with ag-grid 25.1.0 and Cypress 6.5.0, and @K41eb's [workaround](https://github.com/cypress-io/cypress/issues/5394#issuecomment-543221704) doesn't help.

Is anyone else seeing this?

**Comment by jkillian** [comment]
Also hitting this with ag-grid 26 and Cypress 7, and the workaround didn't seem to work for me either. There are some interesting differences between Cypress and usage by a real user - I have `singleClickEdit` enabled, so in real life, after a user clicks on a cell once, the inline editor appears (which has an underlying `input` element). However, when running in Cypress, when I click on the cell and then try to `get` an `input` withing the cell, none exists. It seems as if clicking the cell in Cypress isn't having the same effect as clicking the cell normally. Have to look in to all of this more, but didn't find a quick solution yet.
