### ISSUE TITLE
Cypress doesn't support SAML authentication workflow

### ISSUE THREAD

**Issue by yogeshdeshmukh86** [cypress-io/cypress#5397]
### Current behavior:

PFA DOM screenshot & the cypress script & logs & reports 

1)  Enter user name works fine
2)  Enter password works fine
3) click on signup works partially( as seen in reports)  but after than it doesn't render the next page/form 
4) Even manually if i click on signup inside cypress ( electron or chrome browser) signup is not working url is not redirecting 

I tried the similar script with selenium webdirver it was able to sign in successfully

### Desired behavior:

When I click on sign in next page should be loaded and visible ( as it is visible in manually flow the next page contains dashboard and map view) 

### Steps to reproduce: (app code and test code)

Execute the above test script attached it contains the url & login information 

PFB screenshot for DOM 

![Cypress_issues_saml_token](https://user-images.githubusercontent.com/39789703/67094061-9d88f180-f1d0-11e9-905c-c831d914b377.JPG)

PFA testscript

[Cypress_testscript.txt](https://github.com/cypress-io/cypress/files/3743830/Cypress_testscript.txt)

PFA test results

![Cypress_saml_login](https://user-images.githubusercontent.com/39789703/67094766-150b5080-f1d2-11e9-8ec8-300db7b7328e.JPG)

### Versions

Cypress 3.4.1
Windows 10 enterprise,
Chrome & electron

**Comment by bahmutov** [comment]
You don't want to go through the user interface to log in, and Cypress has limit on the top-level domain that it can control - there can only be one during the test. Thus Cypress "loses" the control of the test. See our logging in recipes that show possible solutions (you want to log in using API call, not through the UI) https://github.com/cypress-io/cypress-example-recipes#logging-in-recipes

**Comment by yogeshdeshmukh86** [comment]
@bahmutov 

yes i know that issue for super-domain. I have used only one url  the rest are commented out they where only for trial & debugging i had added. 
   
I want to login through UI as a black-box test. Simple test case as  enter username & password & clicks on sign in.

For all other websites which doesn't have SAML auth implemented  my Black-box test do works?
 My issue is why it fails in this scenario.  
Also for API our developers have not exposed it for signin purpose, meaning they come from IAM with centralized run-time saml  token which the form takes care while loading 

PFB updated test script 
[Cypress_testscript.txt](https://github.com/cypress-io/cypress/files/3744022/Cypress_testscript.txt)

**Comment by jennifer-shehane** [comment]
@yogeshdeshmukh86 We can't be sure what the issue is from the information provided. We'd need a reproducible example in order to narrow down why the page is not loading on click of the sign in, otherwise we can't really begin to look at the issue unfortunately.

**Comment by yogeshdeshmukh86** [comment]
You can try writing a simple js test script with url & password provided or
execute the js script i have attached and reproduce the issue.
 i have tried in 2 ways first way is entering username password on login
screen and click on sign in.
 Next way is i refereed  the login receipes on cypress website where i
tried login via api request ,xhr webform but it dint work reason is how i
can get the saml token added in body of post request.
Kindly suggest how should i proceed.

**Comment by jennifer-shehane** [comment]
@yogeshdeshmukh86 Please provide a repo of this so that we can run and see the issue on our machines.

**Comment by dlbock** [comment]
@jennifer-shehane This is actually the same issue that was pointed out on Jan 2019 in this issue https://github.com/cypress-io/cypress/issues/3119

Testing a user login flow with SAML (using keycloak as an identity provider) isn't actually testing the internals of keycloak, but testing that the configuration between my application and the identity provider was done correctly such that a user can login via SAML. Because these interactions (between application and identity provider) are all browser-based, such workarounds like the one describe [here](https://github.com/cypress-io/cypress/issues/3119#issuecomment-495115515) is very painful.

Is there a plan to create a way forward that doesn't require heavy-handed workarounds?

**Comment by MathieuB1** [comment]
Seems working with cypress 10.3.0 by adding `experimentalSessionAndOrigin: true` to cypress.config.js.

```
Cypress.Commands.add('login', (username, password) => {
    cy.visit(Cypress.config().baseUrl);
    cy.get('#id_username').type(username);
    cy.get('#id_password').type(password);
    cy.get('form').submit();
    // Important to wait for SSO redirection
    cy.wait(200);
});
```
