### ISSUE TITLE
GUI - Tests navigation sidebar alignment (bottom/top/left/right)

### ISSUE THREAD

**Issue by MacGyver27** [cypress-io/cypress#5399]
Please allow to choose tests sidebar navigation to be at the bottom or top.. I would like to use that window on my vertical monitor.. so I have like 3 split screens:
- top - actual site
- middle - tests navigation
- bottom - dev tools
thx

**Comment by jennifer-shehane** [comment]
This will be low priority on the list of things our team works on, if we work on this at all, just to be upfront.

**Comment by jennifer-shehane** [comment]
\Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
