### ISSUE TITLE
Problem with Google Hosted lirbraries when testing application.

### ISSUE THREAD

**Issue by ivormac** [cypress-io/cypress#540]
I have an application that is using Hosted library e.g. https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js.

It just won't load in the runner for me!
I get a time out on it and other hosted libraries built into the app.

### Current behavior:
I created a simple sanity test:

```js
describe('Sanity Check', function(){
  it('Make sure its oodleplex', function(){
    cy.visit('https://internal.oodleplex.com')
    cy.title().should('include', 'oodleplex')
  })
})
```

When I run the test from the Runner I get:

> Uncaught Error: Bootstrap's JavaScript requires jQuery

I'm getting a timeout (302) on the loading of https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js.

> GET https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js net::ERR_TIMED_OUT

### Expected behavior:

I'm expecting to be able to verify my page loads :(

### How to reproduce the current behavior:

As above.....

### Additional Info (images, notes, stack traces, etc)

* Operating System: Ubuntu 16.10
* Cypress Version: 0.19.4 (Runner) 0.13.1 (CLI)
* Browser/Browser Version: Chrome 59.0.3071.104

**Comment by tschaka1904** [comment]
Did you every solve this?

**Comment by scambier** [comment]
Is there an update or a workaround for this issue? The project I'm working heavily relies on google maps scripts, and the Cypress browser simply cannot load them.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
