### ISSUE TITLE
Suggestion: add running count of failures to command-line output

### ISSUE THREAD

**Issue by danatemple** [cypress-io/cypress#5403]
### Current behavior:

After each test on the command line, it prints a summary:

```
Running: my_test_name.js...                                              (3 of 4) 
```

### Desired behavior:

It would be nice, when glancing at a terminal where a command-line test is running, to be able to see the current error status.  Like if "all good so far?".

```
Running: my_test_name.js...                                              (3 of 4, 2 failed)
```

This is a minor thing, but would add to usability. It's hard to see this by having to either wait for completion or scroll a long way upwards.

**Comment by jennifer-shehane** [comment]
Thanks for opening a feature request. I discussed this with the team and adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
