### ISSUE TITLE
Redirect mime type being recognized incorrectly - Blank Page

### ISSUE THREAD

**Issue by kuroiokami** [cypress-io/cypress#5404]
### Current behavior:
I am logging into our page via Okta SSO. During the redirect process the page just becomes blank. I've included a screenshot. The errors in console are

- Refused to apply style from 'https://xxx.okta.com/login/login.htm?' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
- Refused to execute script from 'https://xxx..okta.com/login/login.htm? because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

![image](https://user-images.githubusercontent.com/7980119/67212424-5c6c2980-f3ea-11e9-9abb-9d59dd90689b.png)

         <p>App relies on JavaScript to function properly.<br>Please enable JavaScript and then refresh the page to login.</p>
    
Seems to be some sort of cross site issue.  I have chrome web security off.

### Desired behavior:

I want it to be able to redirect fully to the site. I've used other automation tools and it works without an issue (taiko.. testcafe.. etc). I would like to use Cypress as part of one of the plans but if I can't get past login then what can i do?

### Steps to reproduce: (app code and test code)

Hits the webpage, gets redirected to Okta and passes in the correct token. Redirects again? and goes to blank during the process.

### Versions

Mac OSX, latest cypress, latest chrome

**Comment by jennifer-shehane** [comment]
This will be quite difficult if not impossible to track down the issue without a reproducible example. Is there any way to provide an example?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
