### ISSUE TITLE
Update Cypress CLI command interface

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#541]
Currently Cypress has two main commands `cypress open` and `cypress run`. Other testing tools (like `mocha`) have just one execution mode. For example, the command `mocha spec.js` runs the given spec file. Maybe it is time for us to rethink what the expected Cypress workflow should be.

I see the following:

1. User installs Cypress as dev dependency `npm i -D cypress`
2. User writes a spec file `spec.js`
3. User runs Cypress to execute this `spec.js` file with `cypress spec.js`.
   - this opens the Cypress GUI, runs the tests and if there are no errors, closes the GUI
   - if the user wants to run Cypress without GUI, need to use `cypress --headless spec.js`
   - on CI, the headless mode is assumed by default
4. If the user wants to bootstrap `cypress` folder, setup options, etc we need separate command 
`cypress --init`
5. We still have a command to open GUI without running tests `cypress open` just like today.

What do you think?

**Comment by jennifer-shehane** [comment]
Hey @bahmutov, see anything to take from this issue? It was opened a while ago, so some things have changed. Please close the issue if not.

**Comment by jennifer-shehane** [comment]
Closing as resolved.
