### ISSUE TITLE
Unable to access my own private project through Test Runner

### ISSUE THREAD

**Issue by mlyonsFE** [cypress-io/cypress#5414]
### Current behavior:

When I go to the Runs tab, I'm told to log in and then request access. When I hit Request Access, a 422 bug comes up and says "This User has an existing MembershipRequest to this Organization." The membership requests that I have approved have not allowed me to access my own project.

### Desired behavior:

Be able to access my private project.

### Steps to reproduce: (app code and test code)
 -> Open cypress test runner
 -> Log in
 -> Attempt to ask for access
 -> (before getting the 422 request already exists bug) "Grant access" through the email I received
 -> User (myself) was already a part of the organization so no changes seem to happen on the Cypress Dashboard
 -> Continue to not have access

### Versions

3.4.1, ubuntu 16.04

**Comment by jennifer-shehane** [comment]
Hey @mlyonsFE We're not aware of an issue with this currently.

Can I ask you to email support@cypress.io about this issue? Specifically, some helpful information to provide in that email would be the project url from the Dashboard and the email that is associated with your login.

**Comment by mlyonsFE** [comment]
Will do, thanks!

**Comment by mlyonsFE** [comment]
For me it was that I had created 2 different accounts, one through github and one through google. Good luck!

**Comment by jennifer-shehane** [comment]
Yes, every case that we have seen this someone has accidentally created 2 accounts in Cypress. One through Google Auth, for example and one through GitHub auth, for example. 

Then they log in via say GitHub in the Test Runner when they previously had logged in through Google when they set up the project. 

If you're experiencing this issue - log out of all Cypress logins, Dashboard and Test Runner and ensure you are logging back in through the exact same login again. If you find no projects - try the other authorization mechanism.
