### ISSUE TITLE
failed to run test if hostname isn't map to localhost

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#5416]
in development, we have to change our hostname
```
127.0.0.1	app1.myapp.com
```

as we take the hostname to determine which set of config to load, in short we are developing a whitelabel software.

but since we isn't map 127.0.0.1 it break the cypress. I can't launch cypress. I got this error in my console

```
cypress_runner.js:106667 WebSocket connection to 'ws://localhost:58001/__socket.io/?EIO=3&transport=websocket' failed: Connection closed before receiving a handshake response
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
