### ISSUE TITLE
Cannot dynamically create tests with cy.task

### ISSUE THREAD

**Issue by GMchris** [cypress-io/cypress#5418]
### Current behavior:

Running `cy.task` in `context` instead of within an `it` block, results in `Uncaught CypressError: Cannot call "cy.task()" outside a running test.`. This blocks me from creating tests dynamically using data read from the file system. Calling my custom task inside `before()` or in a dummy `it()`, seems to be too late for Cypress to pickup the newly generated tests.

### Desired behavior:

Be able to either call `cy.task` outside of tests, or provide an alternative way of interacting with the file system, before tests are run.

### Steps to reproduce: (app code and test code)

1. Create a cypress integration test file, with a `context` block.
2. Declare the following custom task in `plugins/index.js`

```javascript
const { readdirSync, lstatSync } = require('fs');
const { join } = require('path');
const _ = require('lodash');

const isDirectory = source => lstatSync(source).isDirectory();

module.exports = (on, config) => {
  on('task', {
    getAllDirectories(source) {
      const fullSource = `${process.cwd()}/cypress/${source}`;

      return readdirSync(fullSource)
        .map(name => join(fullSource, name))
        .filter(isDirectory)
        .map(name => _.last(name.split('/')));
    },
  });
};
```
3. Inside the integration test, call `cy.task('getAllDirectories', 'somePath');`
4. Error is thrown

### Versions

Cypress 3.4.1
Chrome 77

**Comment by jennifer-shehane** [comment]
Yeah, you can't call `cy` commands outside of an `it` or `hook` block. 

Maybe you could do something like in this example - running cy.task in a before and then iterating over the assigned value of its return? https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__dynamic-tests/cypress/integration/dynamic-spec.js#L100

**Comment by GMchris** [comment]
My problem is that I need to dynamically generate all new tests, using the results, rather than load some data that will be used by my tests. So for example my cy.task will fetch all directories in a folder, and then for each directory I'll create a `describe` block. I want these tests to take advantage of `beforeEach` blocks and don't want to manually reset state after each one. So just iterating the folder names inside a single `describe` block isn't ideal.

**Comment by bahmutov** [comment]
You cannot create _more_ tests once the tests have started (and `cy.task` command is running), you probably want to create a fixture with test data as a pre-test script, and then launch tests. Again, refer to the recipe https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests

**Comment by jaydeep987** [comment]
I also wanna achieve same.

So Problem with cypress is:
1. Cannot use file system as everything run inside browser. 
2. Even there is way to do that using `task`, then it does not allow to execute task directly in `describe`. (If it does, I can generate `it()` dynamically.

and @bahmutov's comment letting me to think about switching to WebDriverIO!

**Comment by jennifer-shehane** [comment]
You cannot run code involving Node code in your tests files (which completely execute inside the browser). We provide a way to run this code in the support and plugins files.

You cannot create more tests once the tests have started  running- as @bahmutov has explained.

There is a working example of generating tests using `cy.task()` here:  https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests

Closing as we've explained the limitations and workarounds and there is no intended work to go forward with executing Node code in the browser.

**Comment by GMchris** [comment]
To @jaydeep987 and anyone else who stumbles upon this thread - the workaround for not being able to dynamically fetch the folder structure for these tests within the `spec` files, was to do it in the `config` or more appropriately in the `plugin/index.js`. Using info from this  [page](https://docs.cypress.io/api/plugins/configuration-api.html#Promises). What I do is run some code that fetches all directories in a certain path, creates an object out of them which it then `JSON.stringify`-es (since your config values needs to be either strings or booleans). And finally assigns this stringified object to an `env` variable in the config.

```javascript
module.exports = (on, config) => {
  const STATIC_CATEGORIES = ['pathOne', 'pathTwo'];
  const staticPaths = {};

  STATIC_CATEGORIES.forEach((category) => {
    const path = `${process.cwd()}/cypress/fixtures/${category}/static`;
    const cat = readdirSync(path)
      .map(name => join(path, name))
      .filter(isDirectory)
      .map(name => _.last(name.split('/')));

    staticPaths[category] = cat;
  });

  config.env.staticPaths = JSON.stringify(staticPaths);

  return config;
};
```
I then get these directories with something like

`JSON.parse(Cypress.env('staticPaths')).pathOne`
