### ISSUE TITLE
Support custom timeouts for `its`

### ISSUE THREAD

**Issue by knagarajan1984** [cypress-io/cypress#5419]
This issue is related to #2941 
current behavior
```js
cy.window().its('Something')
```
```
CypressError: Timed out retrying: cy.its() errored because the property: 'Something' does not exist on your subject.
```

Desired behavior:
```js
cy.window().its('Something', {timeout: 10000})
```

In my app, 

1) the property in the `window`  doesn't exists until the page loads
2) then the property in the `window` loads up as `null` after which it takes few seconds (~10 secs) for the property to get updated to not null property. 

But the below line of code fails due to the behavior of `its` as per cypress documentation

>.its() will automatically retry until the subject's property is not null or undefined.

My code:
```js
cy.window({ timeout: 20000}).its('myproperty.Hash').should('not.equal', null).and('equal', '1234')
```

Is there anyway to get around this. I don't have anything else to wait on or assert about.

**Comment by Bkucera** [comment]
Yes, you can add a `should` assertion before the `its` to ensure it's not null

**Comment by knagarajan1984** [comment]
Thank you , will give it a try. Initial thoughts, Did you mean something like this?
`cy.window({ timeout: 20000}).should('not.equal', null).its('myproperty.Hash').should('not.equal', null).and('equal', '1234')`
The above will check if window is not null isn't it? My problem is that window is not null but myproperty.hash is null when the page loads and updates to a value after 20 secs. I need to wait for this value.

**Comment by jennifer-shehane** [comment]
You shouldn't need to check that window is not null. The below should be enough.

```js
cy.window().its('Something').should('eq', `1234')
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat].

**Comment by knagarajan1984** [comment]
@jennifer-shehane , I understand this is reserved for bugs. I am seeing this as a bug and not a question.If you read my comment once again, what ever you have suggested will not work in my case as the documentation explains that cypress is going to retry until the property is available. In my case the property is available at 0th seconds but its value changes after 10 seconds and i want to check for the value. Cypress timeout at verification point and there is no way for me to change the default timeout

**Comment by bahmutov** [comment]
@knagarajan1984 see this example https://github.com/cypress-io/cypress-fiddle/blob/master/cypress/integration/window-property.md 

<img width="921" alt="Screen Shot 2019-10-23 at 1 44 31 PM" src="https://user-images.githubusercontent.com/2212006/67419995-c11ab600-f59b-11e9-8921-9acff23f3ac2.png">

**Comment by knagarajan1984** [comment]
@bahmutov : It works great, I learnt something new, thanks to you!
