### ISSUE TITLE
Add some `develop` CI jobs to PR builds

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#5421]
### Current behavior:

Some CI stages are run in `develop` but not in PRs, which leads to surprises when merging PRs.

### Desired behavior:

Run more stuff from `develop` against all commits.

After looking at the timing of the last build's stages, I think these 3 jobs (at least) could be added without increasing build times:

1. Build binary (dry run, no upload) - takes about 5 minutes, less than an e2e test - maybe smoke-test it at the end if we don't currently do that in build-binary
2. build npm package (dry run, no upload) - takes about 1:30
3. run kitchensink using un-built Cypress - takes about 5 minutes, less than the longest e2e test

**Comment by bahmutov** [comment]
1. we can split building binary and NPM package from uploading them and only inject sensitive variables for upload in the upload jobs
3. we are already running kitchensink against un-built Cypress in `test-kitchensink-against-staging` job

**Comment by bahmutov** [comment]
we could also run unbuilt binary against TodoMVC - it is fast and exercises a lot of typing and editing commands

**Comment by jennifer-shehane** [comment]
Released in [3.6.0](https://on.cypress.io/changelog#3-6-0)
