### ISSUE TITLE
cy.type should not insert text when non-shift modifier key is pressed

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#5424]
Current Behavior:
`cy.get('input').type('{meta}a')` 
sends `keypress`, `input`, and inserts 'a' into the input

Desired Behavior:
`cy.get('input').type('{meta}a')` 
should only send `keydown`/`keyup` and not insert the charater 'a' into the input

> This could be seen as a breaking change if fixed, but I'd say it could go in as  a patch

versions: -`3.4.1`

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/4870, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by tnrich** [comment]
@jennifer-shehane @Bkucera I think that the following code is now acting differently for me in v3.5.0^

```
.type("{selectall}100")
```

![image](https://user-images.githubusercontent.com/2730609/67978825-31e35300-fbd8-11e9-8f64-68764ccbaef9.png)

As you can see in the screenshot, instead of tying in `100` as expected, it only types in `00` 

I think that {selectall} should also be made to act like the "shift" key.

Thoughts?

**Comment by Bkucera** [comment]
@tnrich what version of Cypress are you on?

**Comment by tnrich** [comment]
Latest, 3.6.0

**Comment by tnrich** [comment]
@Bkucera bump

**Comment by Bkucera** [comment]
@tnrich could you screenshot the console table that gets logged when you click on the `type` command log?

**Comment by tnrich** [comment]
Still happening with v3.6.1 
![image](https://user-images.githubusercontent.com/2730609/69272674-d596a200-0b8b-11ea-9235-3c868758a27d.png)

Here's that screenshot @Bkucera 
![image](https://user-images.githubusercontent.com/2730609/69272623-c283d200-0b8b-11ea-8289-6d69451d51e7.png)

**Comment by tnrich** [comment]
@Bkucera bump?

**Comment by jennifer-shehane** [comment]
The behavior detailed in this original issue has a test around it and has been fixed. Please open a new issue with a complete reproducible example - likely there is something special in your use case that we didn't cover. Include test code and html files to run the test against. Commenting in closed issues is not ideal.
