### ISSUE TITLE
File watching of spec file doesn't work for path / directory / specfile containing bracket `[ ]` characters

### ISSUE THREAD

**Issue by varma22333** [cypress-io/cypress#5426]
### Desired behavior:

cypress is recognizing the code change and executing tests but it is not validating updated code  

### Steps to reproduce: (app code and test code)

I
![vs_code](https://user-images.githubusercontent.com/19255128/67421940-21f3bf80-f597-11e9-99b6-8dd0ce82dba1.png)
![cypressui](https://user-images.githubusercontent.com/19255128/67421941-21f3bf80-f597-11e9-980f-1a8f2c967565.png)

 have opened cypress from VS code 

I executed all specs from cypress 

works fine 

I have added new code 

cypress still executing old code 

cypress is recognizing code change but not updated code 
### Versions

cypress 3.4.1
chrome

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by varma22333** [comment]
Steps:

I have created a spec file in cypress/integration 
I have opened cypress runner from VS Code 
when I click on to run all specs  
cypress runner executed all my test cases in that spec file which is good 
then I modified code in the spec file and saved it 
cypress runner started haven't recognized the new changes and it started executing the old changes 
then I renamed my spec file and executed it then it executed the new code 
when I added a new piece of code and save it cypress runner failed to run the tests

**Comment by jennifer-shehane** [comment]
@varma22333 I'm not able to recreate the issue as you've described. I tried on version 3.4.1 and 3.8.1 of Cypress. 

1. Created 2 spec files in `cypress/integration`
2. Ran `cypress open` from VS Code
3. Ran all specs (they run)
4. Modify either of the 2 spec files `cy.type()` command and `ctrl+s`
5. Cypress reruns with the new changes for `cy.type()` command.

We'd need more information specific to your case. Likely there is an edge case not being described. Please also make sure you have `watchForFileChanges` `false` not set in your configuration file.

**Comment by kishanchaitanya** [comment]
I currently face the same issue, It doesnt seem to run the new changes

**Comment by nfssfn** [comment]
It seems like if you have `[` or `]` (or both / probably any other special characters which must be escaped) in your project path, then cypress can't watch for changes in `*.spec.js` files.

Using: 
```
Ubuntu 16.04
Node.js v12.13.1
Cypress package version: 4.0.1
Cypress binary version: 4.0.1
```
Steps to reproduce:
1. Create a folder `[GH] Cypress`
2. Run `npm init -y`
3. Run `npm i --save-dev cypress`
4. Run `npx cypress open` and open an IDE/Text editor
5. Try to run any test, then edit this test
6. Even if you refresh browser tab manually, it will still use your old code. Only restarting cypress/reopening browser helps

**Comment by dacort** [comment]
Experiencing this as well. It doesn't happen all the time and I haven't been able to put together a consistent reproduction. I _think_ if often happens when my computer is backing up, so high disk activity may be a factor. I'm on version 2.8.3 on Node 12.16.1 or 10.15.0.

**Comment by Mkots** [comment]
@dacort do you use ServiceWorker?

**Comment by jennifer-shehane** [comment]
@nfssfn Thanks for clarifying - this is a case where the file watching does appear to be broken. When there is a bracket character in the directory or the filename.

The following filenames/paths will not have any file watching:

```
📁[Foo] Folder
📄[Foo] Spec
``` 

I tried a bunch of other special charcters and couldn't find anything else that would break file watching, but this doesn't exclude any other chars. 

Can anyone else verify if they are using unusual characters in the directory or spec file name?

**Comment by Mkots** [comment]
@varma22333 Could you send screenshot your tests file structure?
I think your problem doesn't connect to brackets

**Comment by dacort** [comment]
@Mkots I don't believe I'm using ServiceWorker, but will try some of the workarounds there.

@jennifer-shehane No unusual characters for me unfortunately.

**Comment by jennifer-shehane** [comment]
Yeah, I think there is another situation where the original opened issue is applying. The difference being that the file 'reloads', but the code changes do not actually take effect. I've opened another issue to address this situation here: https://github.com/cypress-io/cypress/issues/6919 - if this looks more like your issue (you do not have `[]` in your file name) please comment there .

**Comment by jennifer-shehane** [comment]
We found that there is an issue with file watching when the application under test utilizes Service Workers - see this issue for an explanation and workaround. https://github.com/cypress-io/cypress/issues/6919

**Comment by amannn** [comment]
Here's a reproduction for the square brackets issue: https://github.com/cypress-io/cypress/issues/7980#issue-656622994.

**Comment by ashwin-unnikrishnan** [comment]
I'm facing the same issue where I tried executing the new set of code which is running fine. Then I added a new line to the existing code and saved it. But, cypress is executing the old code and not the changed one
![image](https://user-images.githubusercontent.com/64316727/95680967-e49a9e80-0bfa-11eb-91ac-356a091bd88c.png) 
![image](https://user-images.githubusercontent.com/64316727/95680972-ecf2d980-0bfa-11eb-8baa-ca5a44cfa2e2.png)

**Comment by paulina-grunwald** [comment]
i seem to be having same issue on Mac

**Comment by dorito** [comment]
I have a very similar issue when I have a path with `[ ]` characters.
Files inside `cypress/integration` works and are watched, but files inside `cypress/fixtures` and `cypress/support` are completely ignored.
