### ISSUE TITLE
Cannot read property ‘ownerDocument’ of null on 'cy.click' in 3.5.0

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#5430]
### Current behavior:

Since 3.5.0, I am getting this error on `.click()`.

```
Timed out retying: Cannot read property ‘ownerDocument’ of null
```

<img width="515" alt="Screen Shot 2019-10-23 at 5 26 45 PM" src="https://user-images.githubusercontent.com/1271364/67435627-7eb4a180-f5ba-11e9-8f57-40a1d4601fb0.png">

### Desired behavior:

Not throwing this error

### Steps to reproduce: (app code and test code)

```js
context('contact us modal', () => {
  before(() => {
    cy.visit('http://www.cypress.io/pricing')
  })

  it('opens modal on click of custom plan', () => {
    cy.contains('.call-modal', 'Get in touch').click()
    cy.get('.modal-body').should('be.visible')
  })

  it('form with proper class/script is in modal', () => {
    cy.contains('.call-modal', 'Get in touch').click()
  })
})
```

### Versions

3.5.0

**Comment by lukeapage** [comment]
Also getting this on selected tests
![image](https://user-images.githubusercontent.com/309321/67561568-65783600-f71d-11e9-911a-fb93228fe981.png)
