### ISSUE TITLE
Support Microsoft Edge

### ISSUE THREAD

**Issue by Studio384** [cypress-io/cypress#5433]
### Current behavior:

Microsoft Edge is not supported.

### Desired behavior:

Microsoft Edge is supported. Although this issue is specifically about Anaheim (v74+), support for Spartan (v20-v44) would also be welcome. Given that Anaheim is pretty much the same as Chrome, this shouldn't be a major change, but it would allow Windows users to not have to install Chrome just for Cypress.

### Steps to reproduce: (app code and test code)

N/A

### Versions

Microsoft Edge 74+

**Comment by dwelle** [comment]
Cypress bundles with its own chrome, you don't need to install your own, AFAIK. Can you elaborate the issue?

**Comment by jennifer-shehane** [comment]
There's a Pull Request open for this here: https://github.com/cypress-io/cypress/pull/4203

**Comment by Studio384** [comment]
> Cypress bundles with its own chrome, you don't need to install your own, AFAIK. Can you elaborate the issue?

That would be nice if the Electron browser in Cypress would actually be kept up-to-date.

**Comment by LayZeeDK** [comment]
>There's a Pull Request open for this here: #4203
That's Chromium-base Edge. Commercial and enterprise sectors will be using Microsoft Edge Classic for years to come, if you know what I mean  🐢

**Comment by flotwig** [comment]
Released in [`4.0.0`](https://on.cypress.io/changelog#4-0-0).
