### ISSUE TITLE
Cypress.env() return value is garbled when multibyte string in 3.5.0

### ISSUE THREAD

**Issue by aomoriringo** [cypress-io/cypress#5435]
### Current behavior:

Return value of `Cypress.env()` is garbled when `cypress.env.json` includes multibyte string.

### Desired behavior:

Return value of `Cypress.env()` is not garbled.

On cypress 3.4.1, I got desired behavior.

### Steps to reproduce: (app code and test code)

- Create following files
```js
// cypress/integration/garbled_test.js
const myenv = Cypress.env()
describe('garbled test', function() {
  it('garbled test', function() {
    expect(myenv.alphabet).to.equal('aiueo')
    expect(myenv.multibyte).to.equal('あいうえお')
  })
})
```

cypress.env.json

```json
{
  "alphabet": "aiueo",
  "multibyte": "あいうえお"
}
```

`あいうえお` is Japanese characters.

- Execute `$ npx cypress open` and select `garbled_test.js`

![image](https://user-images.githubusercontent.com/694377/67469553-55157c00-f687-11e9-817a-435293b2dbec.png)

### Versions

- Cypress 3.5.0
- macOS Mojave

**Comment by jennifer-shehane** [comment]
Thank you so much for providing a full reproducible example. I also see this behavior with the code provided. I can also confirm that this is a regression introduced in 3.5.0

## 3.4.1

<img width="523" alt="Screen Shot 2019-10-24 at 8 41 33 AM" src="https://user-images.githubusercontent.com/1271364/67486507-2a510680-f63a-11e9-88cf-08bc71a32cc5.png">

## 3.5.0

<img width="525" alt="Screen Shot 2019-10-24 at 8 43 12 AM" src="https://user-images.githubusercontent.com/1271364/67486605-59677800-f63a-11e9-925c-44a131bd9556.png">

I have confirmed that this also takes place when setting the Environment Variable in the following ways:

- Via `cypress.env.json`
- Via `env` object in `cypress.json`
- Via `CYPRESS_multibyte=あいうえお cypress open` in terminal
- Via `--env multibyte=あいうえお` in terminal
- Via plugins file, setting config

The env var shows up correctly in the configuration panel in the Desktop GUI.

<img width="288" alt="Screen Shot 2019-10-24 at 8 50 29 AM" src="https://user-images.githubusercontent.com/1271364/67487284-a566ec80-f63b-11e9-984c-6aca86bd64a4.png">

**Comment by bahmutov** [comment]
I have added a failing test in branch `unicode-env-variables` see https://github.com/cypress-io/cypress-example-recipes/pull/353

**Comment by bahmutov** [comment]
The env variables are incorrectly encoded in the runner block

<img width="1193" alt="Screen Shot 2019-10-24 at 9 52 37 AM" src="https://user-images.githubusercontent.com/2212006/67492217-13afad00-f644-11e9-9d4d-5bad04f4a0e7.png">

**Comment by bahmutov** [comment]
Added logging env variables on the server side
```
cypress:server:runner serving runner index.html with config { version: '3.5.0', platform: 'darwin', arch: 'x64', projectName: 'server-communication__env-variables', env: { 'my-var': 'ok', 'unicode-var': 'привет', CACHE_FOLDER: '' } }
```
