### ISSUE TITLE
Improve reporter's responsive design so controls still show at narrower widths

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#544]

**Comment by jennifer-shehane** [comment]
This should probably be worked on with this #528

**Comment by RandallKent** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
