### ISSUE TITLE
Typing one field clears previous one

### ISSUE THREAD

**Issue by vedmant** [cypress-io/cypress#5447]
### Current behavior:

I have a form with date field and other fields, when it types date in it stays there but after typing something to the next field it clears previous date field:
https://screencast.com/t/VzAiKnOaK6z
https://screencast.com/t/z7cRIah0W1Z
https://screencast.com/t/xkc6Oxj3YEX

It works properly if I just type this all manually.

### Desired behavior:

It should not clear any other field when typing in different one. It didn't clear date field before on previous versions, I noticed this after upgrade.

### Steps to reproduce: (app code and test code)

You can reproduce it if you install this https://github.com/vedmant/running-time
and run `yarn e2e`, failing test is `entries.js`.
### Versions

Cypress package version: 3.5.0
Cypress binary version: 3.5.0
MacOs Mojave 10.14.6 (18G103)

**Comment by jennifer-shehane** [comment]
Hey @vedmant I pulled down https://github.com/vedmant/running-time and did the following

```
yarn
yarn watch
yarn e2e
```

I am seeing the following failure in Cypress within the `entries.js` specfile. 

Please provide **all** required steps to run the project here in a comment.

<img width="487" alt="Screen Shot 2019-10-24 at 11 00 24 AM" src="https://user-images.githubusercontent.com/1271364/67498476-840efc00-f64d-11e9-93fd-798fb8eb786b.png">

**Comment by vedmant** [comment]
Hi, here it is:

```bash
git clone https://github.com/vedmant/running-time.git # To clone repo
cd running-time
composer install # Install php dependencies

# Prepare enviroment variables
cp .env.example .env # Copy configuration file
php artisan key:generate # Generate unique key

# Prepare database
touch database/database.sqlite # Create sqlite database
php artisan migrate --seed # Create DB Schema and seed sample data
php artisan passport:install # Install Passport

# Compile assets
yarn # Install Javascript dependencies
yarn prod # Compile assets

# Start server
php artisan serve # Start server
```

**Comment by lukeapage** [comment]
I’m seeing something wrong with type clearing fields when typing into them in relation to a test that does a type click type - could be related - but I’m still working on a test case

**Comment by vedmant** [comment]
The test that fails is following:

entries.js
```
  it('can add new entry', function () {
    cy.visit('/entries') // Needs for correct redirect back
    cy.visit('/entry/new')

    cy.wait(500)
    cy.get('#entry_form').within(() => {
      cy.get('#date').type(moment().format('YYYY-MM-DD'))
      cy.get('#distance').type('6')
      cy.get('#time_hours').invoke('attr', 'maxlength', '10').clear().type('0')
      cy.get('#time_minutes').invoke('attr', 'maxlength', '10').clear().type('30')
      cy.get('#time_seconds').invoke('attr', 'maxlength', '10').clear().type('17')
      cy.root().submit()
    })
    cy.url().should('include', '/entries')
    cy.get('#entries_list').should('be.visible')
    cy.get('.toast-message').should('contain', 'added')
  })
```

So basically it just types form one by one and date field is cleared on `cy.get('#distance').type('6')` line after it's executed.
https://screencast.com/t/z7cRIah0W1Z
https://screencast.com/t/xkc6Oxj3YEX
