### ISSUE TITLE
`clearCookie` not working anymore in 3.5.0 under certain baseUrls

### ISSUE THREAD

**Issue by jweingarten** [cypress-io/cypress#5453]
Our code used to do exactly what the documentation states:

```js
cy.setCookie('foo', 'bar')
cy.clearCookie('foo')
cy.getCookie('foo').should('be.null')
```

This works with 3.4.1 and started failing with 3.5.0. 

Since there are tickets about `clearCookies` not working this was the only way we actually could delete a specific cookie. Now even that doesn't work any longer.

**Comment by jennifer-shehane** [comment]
Hey @jweingarten, the example you provided works in 3.5.0 in Chrome and Electron when run during `cypress open` in my MacOS Mohave OS. 

<img width="511" alt="Screen Shot 2019-10-24 at 1 28 31 PM" src="https://user-images.githubusercontent.com/1271364/67510160-6dbf6b00-f662-11e9-9496-0656034f9301.png">

Please provide an entirely reproducible example - also, there is an open cookies issue involving 3.5.0 here - https://github.com/cypress-io/cypress/issues/5432 ensure your issue is not related to this one also.

**Comment by jweingarten** [comment]
Well this is all my test has ... not sure what else to give you ...
The only thing we do have in our index.js is 

```Cypress.Cookies.preserveOnce('B', 'UB', 'YCorp', 'T', 'Y');```

Which isn't even preserving the `foo` cookie.

**Comment by jweingarten** [comment]
Ok I found what you need to reproduce .... and that is basically setting a `baseUrl` in `cypress.json`.

Here the exact steps:

* mkdir foo
* cd foo
* npm install cypress
* mkdir cypress/integration
* vi cypress/integration/sample_spec.js
* copy/paste the following into sample_spec.js
```
describe('Load Main Dashoard after Login', function() {
    context('Login', function() {
      it('The Main Dashboard should be able to load now', function() {
        cy.setCookie('foo', 'bar')                                                
        cy.clearCookie('foo')
        cy.getCookie('foo').should('be.null')
      });
    });
}); 
```
* vi cypress.json
* copy/paste the following into cypress.json
```
{
  "baseUrl":"https://www.google.com"
}
```
* node_modules/cypress/bin/cypress open
* click `sample_spec.js`

Result: ```AssertionError: expected { Object (name, value, ...) } to be null```

**Comment by jennifer-shehane** [comment]
@jweingarten Thanks! I can reproduce this after setting a `baseUrl` in the `cypress.json`

I also confirmed this was introduced in 3.5.0

## 3.4.1 DEBUG cookies

<img width="1060" alt="Screen Shot 2019-10-24 at 4 01 01 PM" src="https://user-images.githubusercontent.com/1271364/67520799-900fb380-f677-11e9-847f-e1dc7397fed9.png">

## 3.5.0 DEBUG cookies

<img width="1108" alt="Screen Shot 2019-10-24 at 4 01 56 PM" src="https://user-images.githubusercontent.com/1271364/67520851-a61d7400-f677-11e9-9e03-39a1533e7753.png">

**Comment by ianldgs** [comment]
Not only `clearCookie`, but apparently lots of things related to cookies and `baseUrl`.

Our tests have a fast login and logout implementation, like the docs show, that doesn't work anymore.

```
cy.request({
  method: 'POST',
  url: '/api/auth',
  body: {
    email,
    password,
  }
})

cy.getCookie('session').should('exist')
```

**Comment by ianldgs** [comment]
Related: #3221 (might be fixable together)

**Comment by borecz** [comment]
I am having the same.

**Comment by flotwig** [comment]
@ianldgs This is the issue you're having, there is already a fix in `develop` to be released soon: #5432

**Comment by flotwig** [comment]
> ```js
> cy.setCookie('foo', 'bar')
> cy.clearCookie('foo')
> cy.getCookie('foo').should('be.null')
> ```

This works in some cases and fails in others (I've only tested in Electron, but results should be the same in Chrome):

* FAILS: https://www.bar.foo.com
* FAILS: http://www.bar.foo.com
* FAILS: https://www.bar.foo.com:2323
* FAILS: http://www.bar.foo.com:2121
* PASSES: http://localhost
* PASSES: https://localhost
* PASSES: no `baseUrl`

I have written some automated tests for this here: #5478

I'll continue working on fixing this in that PR.

**Comment by dwelle** [comment]
Not sure if it's related, but I couldn't get cypress to clear a cookie on a `.`-leading domain.

**Comment by flotwig** [comment]
Thanks for the additional info!

There were some huge changes in how cookies are handled in Cypress 3.5.0. We went from a split approach (using Electron `cookies` APIs to control Electron and Chrome Extension API to control Chrome) to a different, unified approach (Chrome DevTools Protocol to control both Electron and Chrome). Once we get the initial bugs ironed out, this will hopefully be a much more reliable and maintainable approach.

**Comment by PetMou** [comment]
Additional: we use DELETE requests to reset test data. The GET requests still work, but the DELETE's don't work any more since 3.5.0. The requests now return a 403 status
