### ISSUE TITLE
3.5.0 cy.click() behavior change caused broken tests

### ISSUE THREAD

**Issue by leimd** [cypress-io/cypress#5459]
### Current behavior:

With the update to 3.5.0, Cypress has stopped working with [Select 2](https://select2.github.io/select2/#basics) library, when click() is called on the drop down element, no drop down is shown. @rakhid and I have made a sample test in Cypress and recorded video to show the problem. 

[Video Recording 3.5](https://github.com/leimd/cypress-bug-demo/blob/cypress-35/cypress/videos/test.js.mp4)

### Desired behavior:

When triggering click on the drop down element, a drop down should be shown [Video Recording 3.4](https://github.com/leimd/cypress-bug-demo/blob/cypress-34/cypress/videos/test.js.mp4)

### Steps to reproduce: (app code and test code)

[Here is a sample repo](https://github.com/leimd/cypress-bug-demo) that we made to show the bug, there are two branches: cypress-34 and cypress-35  which has Cypress 3.4.0 and Cypress 3.5.0 in their package.json respectively. By checking out the respective branch and run `npx cypress run`, you can recreate the bug.

### Versions

Cypress 3.5.0
Browser: Chrome & Electron

**Comment by leimd** [comment]
If I'm understanding correctly, looking from the diff between 3.4 and 3.5, the mechanism behind cy.click() has changed.
In [3.4](https://github.com/cypress-io/cypress/blob/a9927b13f47c5e010c32f406a867b4090f6d1e08/packages/driver/src/cy/commands/actions/click.js), what's behind `cy.click()` is really something like this `$Mouse.mouseDown($elToClick, coords.fromViewport)` where the `mouseDown`, `click` and `mouseUp` event on the element are triggered sequencially with the element choosen.  
In [3.5](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/click.js), it looks like mousedown and mouseup events are dropped. which caused the problem, because Select 2 is only triggered on mousedown event.

**Comment by leimd** [comment]
More Notes from my investigation

It seems that this is how it works in 3.4:
in [click.js](https://github.com/cypress-io/cypress/blob/a9927b13f4/packages/driver/src/cy/commands/actions/click.js) , x and y coordinates are determined, and then a `$actionability.verify (...)` is returned.

In [actionability.coffee](https://github.com/cypress-io/cypress/blob/a9927b13f4/packages/driver/src/cy/actionability.coffee), in the verify method, at line 263:
`ensureElIsNotCovered(cy, win, $el, coords.fromViewport, options, _log, onScroll)` is triggered,
 inside `ensureElIsNotCovered` , eventually this is executed, which subsitutes the element to the deepest element that we are about to interact with and let the events bubble up.
``` 
ensureDescendents = (fromViewport) ->
    ## figure out the deepest element we are about to interact
    ## with at these coordinates
    $elAtCoords = getElementAtPointFromViewport(fromViewport)
```,
 what's behind `getElementAtPointFromViewport` is `doc.elementFromPoint(x, y)` which

**Comment by jennifer-shehane** [comment]
I can confirm that the provided repo passes in 3.4.1 and fails in 3.5.0 https://github.com/leimd/cypress-bug-demo

**Comment by jennifer-shehane** [comment]
There's a PR open to fix this here: https://github.com/cypress-io/cypress/pull/5496

**Comment by leimd** [comment]
Thanks @jennifer-shehane  !
