### ISSUE TITLE
"Suggest Edits" popup loads with missing CSS in new tab

### ISSUE THREAD

**Issue by mo** [cypress-io/cypress#546]
If you right-click "Suggest Edits" and click "Open in new tab" in the docs (or middle click using the mouse if you're a PC user), it opens a page with with missing CSS and unresolved templates:

![image](https://user-images.githubusercontent.com/7117/27707455-b39adb2a-5d15-11e7-857e-d53228731d87.png)

For example, try it at:
https://docs.cypress.io/docs/making-assertions#section-implicit-subjects-with-cy-should-or-cy-and-

A normal single click pops the dialog correctly though.

**Comment by jennifer-shehane** [comment]
This seems to be coming from Readme.io directly unfortunately. We are soon moving our documentation off of Readme's service, so things like this will no longer be an issue.

**Comment by jennifer-shehane** [comment]
We've released our new docs, so this should no longer be an issue. [https://docs.cypress.io](https://docs.cypress.io)
