### ISSUE TITLE
Active test file in desktop GUI loses style when a separate file is changed

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#547]
When running a spec file, the file shows as active (highlighted green with bullseye icon). If you change a different spec file (add/delete/rename), the highlighting is removed even though the spec file is still active.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
