### ISSUE TITLE
Date/time input broken (no input events) since 3.5.0

### ISSUE THREAD

**Issue by dvic** [cypress-io/cypress#5476]
### Current behavior:

Date inputs are not emitting *input* events since version 3.5.0.

### Desired behavior:

When typing into a date input field,  I expect the field to emit an input event (works in <= 3.4.1).

### Steps to reproduce: (app code and test code)

https://github.com/cypress-io/cypress-test-tiny/pull/52/files

![image](https://user-images.githubusercontent.com/1214337/67598531-05f64680-f76e-11e9-86a5-e0db0a415533.png)

### Versions

3.5.0

**Comment by jennifer-shehane** [comment]
I have confirmed that the code example above passes in 3.4.1 and fails in 3.5.0.

**Comment by dvic** [comment]
@Bkucera the fix in 3.6.0 seems to fix most of our failing tests but there still seems to be a problem with programmatically resetting the input field back to the original value after calling `clear()`. Will investigate and let you know.

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
