### ISSUE TITLE
Failure in Windows during cypress verify

### ISSUE THREAD

**Issue by gtmtech** [cypress-io/cypress#5487]
I am trying to help a tester install your software.

We couldn't get cypress to open on a fresh install on Windows 10 Professional. `nodejs` and `npm install cypress --save-dev` worked fine. 

There was then an error during running `cypress open`, which included information that it couldnt run the `verify --smoke-test=xxx, -ping=xxx`. But no information about why not, no useful stack traces, no useful output lines to help you reason why. If anything, for first-time users, please get AT LEAST the demonstration (on cypress.io) working to the point if any commands fail, it tells you why. 

If it needs some debugmode flag set to true to tell you, then please include that information in the Installing Cypress page - "https://docs.cypress.io/guides/getting-started/installing-cypress.html#Switching-browsers". When you're new to something having errors with no info is a bit overwhelming to go and read in depth how something works internally just to get it to run the first time.

### Current behavior:

Very first `cypress open` command doesnt work reporting that the verify phase errored. No specific error reported. This is whilst attempting to run the demonstration in the video on cypress.io - getting the console up. Fresh npm install as of 21:00GMT Sun 27th October 2019

```
Cypress verification failed.

This command failed with the following output

...\Cypress.exe --smoke-test --ping=676

Platform:
Win32 (10.0.18362)
Cypress version 3.5.0
```

### Desired behavior:

Cypress should work and have been tested on target operating systems, however if there are problems, it should at the very minimum display errors/reasons as to why it doesnt work without having to turn on debug mode which is not documented in the demonstration 

### Steps to reproduce: (app code and test code)

After successful npm install cypress --save-dev
.\node_modules\.bin\cypress open

### Versions

Windows 10 Pro

**Comment by jennifer-shehane** [comment]
We do extensively test on all operating systems, but considering the number of operating systems, user permissions, node versions, npm versions, the number of configuration that could be passed, the number of browsers and that every application running on the web could be tested under Cypress, bugs are released sometimes. 

There is something specific about the situation that this user is running within that is unique and not being tested.

Please try to downgrade to 3.4.1 and let us know if this fixes the issue, this may have been a bug released in our latest issue. 

Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document troubleshooting install here: https://github.com/cypress-io/cypress-documentation/issues/2201 (although this has nothing to do with install but it indeed happening when you run `cypress open`. Our documentation is open source and contributions are welcome.

**Comment by aleitch1** [comment]
Are there any updates to this topic? I'm seeing ~20% of a 150-person group get this error, but even a force-install doesn't appear to be working to update cypress for running.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by alexeyr** [comment]
How can I run Cypress in debug mode? The section linked seems to be removed from the docs.

**Comment by alexeyr** [comment]
Found the answer in https://github.com/cypress-io/cypress/issues/6082#issuecomment-570277687: `DEBUG=cypress* yarn cypress ...`
