### ISSUE TITLE
cypress issues on multi user system

### ISSUE THREAD

**Issue by erez-cellbuddy** [cypress-io/cypress#5489]
"npm install cypress" accesses file /tmp/cypress.zip
running cypress accesses directory /tmp/cypress

in both cases, if more than one user tries to install or run cypress, user gets permission denied

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
