### ISSUE TITLE
Is there a way to increase number and delay of retries with global baseUrl ?

### ISSUE THREAD

**Issue by JBustin** [cypress-io/cypress#5490]
### Current behavior:

On Travis, server is slow to start, and sometimes, the result is : 

<img width="720" alt="Capture d’écran 2019-10-28 à 15 50 32" src="https://user-images.githubusercontent.com/2632709/67688812-b6489280-f99a-11e9-884e-91e36b30a9b6.png">

Local, no problem.
Travis, the good days, no problem.

### Desired behavior:

Increase time and number of retries to connect to server with global baseUrl connection (this behaviour : https://docs.cypress.io/guides/references/best-practices.html#With-baseUrl-set-Cypress-loads-main-window-in-baseUrl).

Thanks for help

**Comment by jennifer-shehane** [comment]
No, we will not be updating this to increase the number of retries. I would recommend ensuring your server is ready before calling into cypress. There are some suggested solutions here: https://docs.cypress.io/guides/guides/continuous-integration.html#Boot-your-server

**Comment by JBustin** [comment]
Thx @jennifer-shehane 
I have removed `wait-on` by thinking that global baseUrl should a better solution.
