### ISSUE TITLE
log in console the target el of cy.root() command

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#55]
When I click on a `.root()` command in the commands log, the console doesn't log anything useful:

**Console log of .root()**
<img width="277" alt="screen shot 2015-08-19 at 3 25 23 pm" src="https://cloud.githubusercontent.com/assets/1271364/9366690/bf41c99a-4686-11e5-8d59-d65b80def689.png">

I would like the console log to display the DOM element that the root command returns (similar to what `.get()` command logs.

**Comment by brian-mann** [comment]
Fixed in [`0.11.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0112-09142015).
