### ISSUE TITLE
baseUrl is being ignored

### ISSUE THREAD

**Issue by terwort** [cypress-io/cypress#5501]
Version 3.5.0

When using baseUrl, in either the cypress.json file, or directly via the command line, it is sometimes being ignored, and sometimes works as expected.

![image](https://user-images.githubusercontent.com/37204984/67713143-3ff46200-f993-11e9-847c-286230121b82.png)

This is running on VSTS.

**Comment by jennifer-shehane** [comment]
@terwort The error you posted a picture of looks like this bug: https://github.com/cypress-io/cypress/issues/5445

The issue about it not reading `baseUrl` - may be this bug, although I don't see the same error as they are indicating: https://github.com/cypress-io/cypress/issues/5466

These are likely both isolated to Windows, although we are still assessing this. Closing as a duplicate, please comment in the other issues respectively.

**Comment by terwort** [comment]
@jennifer-shehane Just a heads up, our servers were running ubuntu-latest.

**Comment by jennifer-shehane** [comment]
Released in [3.8.0](https://on.cypress.io/changelog#3-8-0).
