### ISSUE TITLE
Cypress 3.4.1 in not unzipping while installing for windows 10

### ISSUE THREAD

**Issue by afnankhalid** [cypress-io/cypress#5506]
```
Installing Cypress (version: 3.4.1)
√  Downloaded Cypress
×  Unzipping Cypress
  → Cypress Version: 3.4.1
   Finishing Installation
The Cypress App could not be unzipped.
----------
Error: end of central directory record signature not found
----------
Platform: win32 (10.0.17763)
Cypress Version: 3.4.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchify\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.4.1 postinstall: node index.js --exec install
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Platform: win32 (10.0.17763)
Cypress Version: 3.4.1
Node: 10.16.3 
Npm: 6.9.0

**Comment by jennifer-shehane** [comment]
@afnankhalid Are you using yarn? Are you by change downloading 2 versions of Cypress by mistake as detailed here? https://github.com/cypress-io/cypress/issues/4595

**Comment by jennifer-shehane** [comment]
Also, could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by afnankhalid** [comment]
@jennifer-shehane No I am not downloading multiple versions of Cypress, I was just downloading the requirements create a framework in cypress. I am new with Cypress and JS.
I used npm not yarn!
My package json looks something like this:

"dependencies": {
   "@cypress/browserify-preprocessor": "^2.1.1",
   "chai": "^4.1.2",
   "chokidar": "^2.0.4",
   "cosmiconfig": "^4.0.0",
   "cucumber": "^4.2.1",
   "cucumber-expressions": "^6.0.1",
   "cucumber-tag-expressions": "^1.1.1",
   "debug": "^3.0.1",
   "gherkin": "^5.1.0",
   "glob": "^7.1.2",
   "js-string-escape": "^1.0.1",
   "through": "^2.3.8"
 },
 "devDependencies": {
   "commitizen": "^4.0.3",
   "cypress": "^3.4.1",
   "cz-conventional-changelog": "^3.0.2",
   "eslint": "^4.16.0",
   "eslint-config-airbnb-base": "^13.0.0",
   "eslint-config-prettier": "^2.9.0",
   "eslint-plugin-cypress": "^2.0.1",
   "eslint-plugin-import": "^2.12.0",
   "eslint-plugin-prettier": "^2.6.0",
   "husky": "^1.1.1",
   "jest": "^24.9.0",
   "lint-staged": "^7.3.0",
   "prettier": "^1.13.5",
   "semantic-release": "^15.12.3"
 }

**Comment by jennifer-shehane** [comment]
@afnankhalid Thanks, that information is helpful. 

Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
