### ISSUE TITLE
"Found .only in folder" error when trying to commit

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#5518]
### Current behavior:

I tried to commit into my own branch in my fork of cypress. This fails with the error:

> Found .only in folder(s) 👎
> 544:     * Mocks global clock but only overrides specific functions.
> 1847:     * Creates a spy / stub but only for calls with given arguments.
> 2108:     * Whether Cypress will upload the video to the Dashboard even if all tests are passing. This applies only when recording your runs to the Dashboard. Turn this off if you’d like the video uploaded only when there are failing tests.
> 2721:     * Causes all `.keys` assertions that follow in the chain to only require that the target have at least one of the given keys. This is the opposite of `.all`, which requires that the target have all of the given keys.
> 3221:     * Causes all `.keys` assertions that follow in the chain to only require that the target not have at least one of the given keys. This is the opposite of `.all`, which requires that the target have all of the given keys.
> 4352:    /** Override *name* for display purposes only */

But I have done nothing related to this I think.

### Desired behavior:

I should be able to commit on Windows without using "--no-verify"

### Steps to reproduce: (app code and test code)

Fork cypress-io/cypress repo, make a branch and try to commit the changes made in https://github.com/gabbersepp/cypress/commit/de0a7c0d4936886b1b7576b60bb0b533c9207cb2

### Versions

Current develop branch, Win10

**Comment by jennifer-shehane** [comment]
There was a PR recently opened in the docs to address a situation where our stop-only was catching areas too liberally, I wonder if this is related. https://github.com/cypress-io/cypress-documentation/pull/2194

**Comment by bz2** [comment]
@jennifer-shehane Yes, this looks very similar to the issue that I proposed a fix for in https://github.com/cypress-io/cypress-documentation/pull/2194 - I can work a similar change in the main repo is the approach is approved.

**Comment by gabbersepp** [comment]
@bz2 do you know if this error depends on specific changes? I just re-tested this behaviour by creating a new local branch and commit a new file. 
This time everything works as expected

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are facing this issue again when contributing to Cypress repo and we will reopen.

**Comment by kevcodez** [comment]
Actually ran into that for the runs-list.jsx file in the packages/desktop-gui

```
npx stop-only --skip .cy,.publish,.projects,node_modules,dist,dist-test,fixtures,lib,bower_components,src --exclude e2e.ts,cypress-tests.ts --folder C:/Users/Kevin/Documents/Github/cypress/packages/desktop-gui/src/runs/runs-list.jsx  
Found .only in folder(s) �
186:      // other error, but only show if we don't already have runs
```

**Comment by bz2** [comment]
Looks like this wasn't fixed in the main repo. The solution is to remove `stop-only` which behaves poorly on windows and generates false positives, and use eslint instead to detect `.only` in tests. Only extra complication is there are coffee script files that are also covered by this check at the moment, but don't use eslint. They probably could.

**Comment by bz2** [comment]
@jennifer-shehane As (but slightly delayed) promised, brought the change I made on the doc repo over to fix the same issue here.
