### ISSUE TITLE
On Win10 I can not run packages/driver tests

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#5523]
### Current behavior:

I want to run the tests in `packages/driver`. To do this, I need to start the node server, as mentioned in the driver's readme. This fails with following exception:

![image](https://user-images.githubusercontent.com/3234900/67795342-65aa6580-fa7e-11e9-8e27-ffde8988e80c.png)

//Edit
As I have an German system, I provide you the english translation:
**The command ".." is either misspelled or could not be found.**

### Desired behavior:

I want to be able to run the tests without doing manual stuff like fixing paths in the package.json

### Steps to reproduce: (app code and test code)

- checkout cypress-io/cypress
- open command
- insert `npm install`
- `cd packages/driver`
- `npm install`
- `npm start`

### Versions

current cypress develop branch, Win10, executed from Powershell

**Comment by gabbersepp** [comment]
If I follow the hint here:
https://stackoverflow.com/a/50998274/9809950
and change the npm script to this:
`"start": "node ../coffee/node_modules/.bin/coffee test/support/server.coffee"`

I get another error:
![image](https://user-images.githubusercontent.com/3234900/67796047-9b9c1980-fa7f-11e9-9a82-894e4e25e9f0.png)

**Comment by jennifer-shehane** [comment]
Are you using verion 12.0.0 of Node as indicated in this file? https://github.com/cypress-io/cypress/blob/fix-type-single-value-change-inputs/.node-version

My running `npm start` command works on osMac Mohave.

**Comment by jennifer-shehane** [comment]
But yah, none of us run development in Windows, so this may not be ideal. We're open to PRs that would make this work across machines.

**Comment by gabbersepp** [comment]
> Are you using verion 12.0.0 of Node as indicated in this file? https://github.com/cypress-io/cypress/blob/fix-type-single-value-change-inputs/.node-version
> 

Well, I am running 10.x on my Laptop. I can try to upgrade but I think that this will make no differences. Maybe I find some time and can setup a platform independent solution

**Comment by gabbersepp** [comment]
I upgraded Node to 12.0 and tried on both, cmd.exe and Powershell without success

**Comment by avallete** [comment]
> I upgraded Node to 12.0 and tried on both, cmd.exe and Powershell without success

It is not an ideal solution but did you try to give a shot to a "more POSIX like" shell like GitBash ? 

Because a lot of subscripts (like in your second error) are based on UNIX systems and are not necessarily compatibles with windows environment.

**Comment by gabbersepp** [comment]
> It is not an ideal solution but did you try to give a shot to a "more POSIX like" shell like GitBash ?
> 
> Because a lot of subscripts (like in your second error) are based on UNIX systems and are not necessarily compatibles with windows environment.

Not yet. If I have time, I will try GitBash.

**Comment by gabbersepp** [comment]
> > I upgraded Node to 12.0 and tried on both, cmd.exe and Powershell without success
> 
> It is not an ideal solution but did you try to give a shot to a "more POSIX like" shell like GitBash ?
> 
> Because a lot of subscripts (like in your second error) are based on UNIX systems and are not necessarily compatibles with windows environment.

Unfortunately this does not help. Maybe I find some time to make every command runnable under windows.

**Comment by gabbersepp** [comment]
> > I upgraded Node to 12.0 and tried on both, cmd.exe and Powershell without success
> 
> It is not an ideal solution but did you try to give a shot to a "more POSIX like" shell like GitBash ?
> 
> Because a lot of subscripts (like in your second error) are based on UNIX systems and are not necessarily compatibles with windows environment.

At least you were right. I had to set the git bash as default shell as mentioned here:
https://stackoverflow.com/a/46006249/9809950

**Comment by jennifer-shehane** [comment]
Released in [3.8.1](https://on.cypress.io/changelog#3-8-1)
