### ISSUE TITLE
Cypress randomly doesn't catch routes when runs in jenkins

### ISSUE THREAD

**Issue by ElderMorgun** [cypress-io/cypress#5531]
### **Current behavior:**
When Jenkins automatically runs cypress tests sometimes it fails on the same step, when cypress is waiting for the XHR request. It never happens if I run tests on my computer or on the server manually.

I'm sure that the request really sent coz the next test based on it, and if the request never occurred the next test will fail too, but it's not.

```js
it('SCRAPPING', () => {
        let route = '/scraper/fetchReport?report_id=042b63a2-aeb6-4a84-a520-8afb38b9fe11';
        cy.server();
        cy.route('GET', route).as('getScraped');
        cy.route('POST', '/scraper/scrapeReport').as('startScrape')
        cy.visit(reportUrl);
        cy.wait(2000);
        cy.get('.btn-group-vertical > .btn-info').click().then(() => {
            cy.get('.modal-body > .form-control').should('be.visible').as('textField');
            cy.get('@textField').type(links).then(() => {
            cy.get('.modal-footer > .btn-primary').click().then(() => {
                let startTime = Cypress.moment().format('MMMM Do YYYY, h:mm:ss a');
                cy.wait('@startScrape').then(() => {
                    cy.log(`Start scraping: ${startTime}`);
                    cy.wrap(links).each(() => {
                        waitScraping();
                    });
                });
            });
        });

        function waitScraping() {
            cy.log(route);
            cy.wait('@getScraped', { requestTimeout: 90000, responseTimeout: 90000 }).then((request) => {
                let resp = request.status;
                let id = request.id;
                let endTime = Cypress.moment().format('MMMM Do YYYY, h:mm:ss a');
                cy.then(() => {
                    cy.log(`Link #${id}`, `status: ${resp}`);
                    cy.log(`Сaught this response at: ${endTime}`);
                    expect(resp).to.eq(200);
                });
            });
        }
    });
```

**That's what happens in the CI:**

> 15:29:54 get .btn-group-vertical > .btn-info
> 15:29:54 click 
> 15:29:54 get .modal-body > .form-control
> 15:29:54 assert expected <textarea.form-control.modalClass.ng-untouched.ng-pristine.ng-valid> to be visible
> 15:29:54 get @textField
> 15:29:54 type Array[5]
> 15:29:54 get .modal-footer > .btn-primary
> 15:29:54 click 
> 15:29:54 xhr  POST https://mysite.com/storage/addImageToReport
> 15:29:54 wait @startScrape
> 15:29:54 xhr  POST https://mysite.com/scraper/scrapeReport
> 15:29:54 log Start scraping: October 29th 2019, 3:28:21 pm
> 15:29:54 wrap Array[5]
> 15:29:54 log First request @getScraped: /scraper/fetchReport?report_id=042b63a2-aeb6-4a84-a520-8afb38b9fe11
> 15:29:54 wait @getScraped, Object{3}
> 
> CypressError: Timed out retrying: cy.wait() timed out waiting 90000ms for the 1st request to the route: 'getScraped'. No request ever occurred.

**Sometimes cypress catches these requests, but more often - not**

### **Desired behavior:**
Cypress should catch all XHR requests

### Steps to reproduce: 
I don't know how to reproduce it, because it happens randomly and only when cypress runs in the CI. Maybe somebody else had similar problems and know how to solve the problem.

### **Versions**
Cypress 3.4.1
Electron 61
Jenkins
Ubuntu 18.04.2

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example. 🙏

**Comment by ElderMorgun** [comment]
I would like to give you more information, but unfortunately, I can't coz it's related to the company NDA... May something else will help u to find a solution? And I don't think that it's a reproducible example, how I said before, it happens only when cypress runs automatically in the CI (Jenkins) after the build and not every time. Sometimes the routes passed and sometimes cypress doesn't catch any of them.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
