### ISSUE TITLE
Improve cy.select handling of all options having same value

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#554]
The current workaround for a `<select>` whose `<option>`s all have the same value seems to be insufficient.

Currently, when all the options have the same value, we set the 'selected' prop on the `<option>`(s) that match. I believe we also need to set the selectedIndex and selectedOptions props on the `<select>` itself.

> @damianocastro commented on July 5, 2017
> 
> I don't think this case is fixed in all cases. I tried this example and always selects the first one when a valid text is selected. The html and test.js are both in the zip. My version is 0.19.4.
> 
> [select.html.zip](https://github.com/cypress-io/cypress/files/1125944/select.html.zip)

**Comment by chrisbreiding** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by AdamJ816** [comment]
I am also running into this issue. Trying to find a good workaround because the drop-down selection populates other data on the form, which enables or disables the submission. Problem is, if i force select it, none of the other options will populate to enable the submission.

**Comment by Laess3r** [comment]
Is there now a solution for this?

**Comment by Aeny202** [comment]
I ran into this one today as well on the latest release (3.4.1) Anyone knows of a decent workaround?

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested.  in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
