### ISSUE TITLE
has trouble finding Uppy input

### ISSUE THREAD

**Issue by adventmedia** [cypress-io/cypress#5540]
Problem with Uppy file uploader (for React, uppy.io);

Here is the html:

```jsx
      <div style={{ display: 'none' }} data-cy="uppy-input">
        <div className="UppyForm" ref={uppyFormEl} />
      </div>

```
Rendered DOM looks like this:

```html
<div data-cy="uppy-input" style="display: none;">
  <div class="UppyForm">
    <div class="uppy-Root uppy-FileInput-container">
       <input class="uppy-FileInput-input" type="file" name="files[]" multiple="" accept="image/*" style="">
    </div>
  </div>
</div>
```

This is the test:

```js
    cy.fixture('images/bucephalus.jpg', 'base64', { timeout: 12000 }).then(
      fileContent => {
        cy.get('[data-cy=uppy-input] input', {
          timeout: 12000,
          force: true,
        }).upload(
          { fileContent, fileName: 'bucephalus.jpg', mimeType: 'image/jpeg' },
          { subjectType: 'input' }
        );
      }
    );
```
On first run, Cypress throws this:
![uppy timeout](https://user-images.githubusercontent.com/1529172/67896990-dc556a80-fb33-11e9-8e4f-795935295e77.jpg)

This always happens on first run of the spec - subsequent runs usually (not always) pass.

Cypress 3.4.1, 3.5; MacOS 10.14.6; Chrome 78.0.3904.70

**Comment by jennifer-shehane** [comment]
Hey @adventmedia, are you using a plugin to do this with Cypress? Because we don't support uploading files in the base Cypress app. I would suggest referring to the plugin for the error you are seeing. We don't have an `.upload` command - that I see you are using.

**Comment by adventmedia** [comment]
no, .upload is an Uppy api
[https://uppy.io/docs/uppy/#uppy-upload](https://uppy.io/docs/uppy/#uppy-upload)
what is weird is that it only fails on the first run of the spec - run it again and it works

**Comment by adventmedia** [comment]
hmm, yes, we are using cypress-file-uploader. Apologies.

**Comment by zifahm** [comment]
@adventmedia  How did you solve this? Did the plugin work?
