### ISSUE TITLE
Assertion chaining should never change the subject

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#555]
Because Cypress follows the underlying rules of the assertion engine, we automatically follow subject changes in assertions.

This leads to extremely confusing behavior and causes you to have to rewrite assertions awkwardly.

When failures due to this happen they fail in deep chai / assertion code and so the stack traces are very confusing.

## Current Behavior
```js
cy
  .get('a')
  .should('have.prop', 'href', '/foo')
  .and('have.class', 'active') // fails because subject is now a string
```

## Proposed Behavior
```js
cy
  .get('a')
  .should('have.prop', 'href', '/foo')
  .and('have.class', 'active') // passes, subject is unchanged
```

When you do want to chain off of an existing subject you can simply use an assertion callback function and explicitly pass in the subject.

```js
cy.get('a').should(($a) => {
  expect($a).to.have.prop('href').and.match(/foo/) // continues to work naturally in chai
  expect($a).to.have.class('active')
})

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by lifeiscontent** [comment]
@jennifer-shehane I just ran into this.

my test:

```ts
      cy.get('button')
        .should('have.attr', 'aria-controls')
        .should('have.attr', 'aria-disabled', 'false')
        .should('have.attr', 'aria-expanded', 'false')
        .should('have.attr', 'id')
        .should('have.attr', 'type', 'button');
```

in the first assertion, cypress goes from the button elements to the element of the id in `aria-controls`.

I agree with @brian-mann this is super confusing.
