### ISSUE TITLE
Accept option to `click` to send mouseout events after click

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress#5552]
currently, we wait until the next `click` or `type` command in order to send `mouseout`/`mouseleave` to the previously clicked element.

Since we wait to fire the mouse leave events, event-listener tooltips will stick around until the next mouse command, which users might want to disable

We should accept a new option `{ unHoverAfterClick: true }` to fire mouse leave events after the click

### related
#5500

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
