### ISSUE TITLE
Support disabling cookies in request headers

### ISSUE THREAD

**Issue by miteshrathod09** [cypress-io/cypress#5560]
Hi Team Cypress,

There are cases where one would want to test flows in cookie disabled browser/webviews.

https://docs.cypress.io/guides/references/configuration.html#Browser

If there is a user agent that can mimic a cookie disabled browser, then that would be great but unfortunately I could not find one (Any idea?)

Or if Cypress can help support this via config and disable request header cookies.

Thank you.

**Comment by jainmitesh09** [comment]
Hello @jennifer-shehane @bahmutov! 
Is it possible to do the above with Cypress? Please let me know if you can share some resource.

If not, we can close this issue. However, it would be good to have this feature for testing cookie disabled browser requests. 

Thank you.

**Comment by jennifer-shehane** [comment]
@jainmitesh09 In order to provide the best solution, we'd need to know the code in your application that you want tested. What are you doing in your application to detect if cookies are disabled exactly?

**Comment by jainmitesh09** [comment]
Hi @jennifer-shehane , so we do two kinds of checks
1. Client side
```
typeof document.cookie === 'string' && document.cookie.length > 0`
```
2. Server side 
```
req.headers && typeof req.headers === 'object' && !req.headers.cookie
```

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
