### ISSUE TITLE
--config-file doesn’t work alongside --global

### ISSUE THREAD

**Issue by KittyGiraudel** [cypress-io/cypress#5570]
### Current behavior:

It appears that the `--config-file` doesn’t work alongside the `--global` flag of `cypress open`. Consider the following configuration file (at `src/tests/cypress/config.json`):

```json
{
  "baseUrl": "http://localhost:8080",
  "chromeWebSecurity": false,
  "defaultCommandTimeout": 10000
}
```

Then `npx cypress open --global --config-file src/tests/cypress/config.json` yields:

<img width="684" alt="Screenshot 2019-11-01 at 11 53 09" src="https://user-images.githubusercontent.com/1889710/68020307-5dc90c00-fc9e-11e9-8122-03684072ec62.png">

And from the Cypress project root, without the `--global` flag:

<img width="717" alt="Screenshot 2019-11-01 at 11 54 09" src="https://user-images.githubusercontent.com/1889710/68020309-5dc90c00-fc9e-11e9-883a-2894542b7593.png">

### Desired behavior:

I would expect the `--global` flag not to have an impact on the configuration when a file is provided.

### Steps to reproduce: (app code and test code)

1. Initialise a Cypress project in a sub-directory.
2. Run `npx cypress open --global --config-file <path/to/config>/config.json` from the root directory.
3. Open the “Settings” tab of the Cypress app.

### Versions

3.6.0, but I suspect it was not working in 3.5.0 either.

**Comment by jennifer-shehane** [comment]
@HugoGiraudel Can you detail the actual use case of what your issue was? 

The global mode of Cypress is not supported to be run via `npm` like you are demonstrating. The `--global` flag is undocumented and not meant to be used except for internal use. 

Please detail the actual problem you encountered while using global mode and the configFile (aka, manually downloading and running the Cypress app).

**Comment by HugoGiraudel** [comment]
Hey Jennifer! Thank you for your quick answer. :)

> Why are you passing the `--global` flag, may I ask.

We use Cypress in a mono-repo which hosts 5 projects. Each project‘s configuration and end-to-end tests live in a sub-directory (`src/servers/<name>`). When working on the tests locally, we use `--global` from the root directory to open the Cypress app (`$(npm bin)/cypress open --global` or `npx cypress open --global`), and from there we open a project from the app itself. This saves us from `cd`-ing in and out of the project directory (e.g. `src/servers/website`).

> Please detail the actual problem you encountered while using global mode and the configFile (aka, manually downloading and running the Cypress app).

Pardon me, I am not sure what’s missing from my initial report to make it more clear. As we can tell from the screenshots, when the `--global` option is passed to `cypress open` alongside the `--config-file` option, the configuration from the `--config-file` option is not loaded (at least not in the “Settings” tab of the Cypress app).

Does that make sense?

**Comment by jennifer-shehane** [comment]
@HugoGiraudel Thanks, yes, this is clear. From your screenshots - I do see the configFile being read (you can see the config file and where it is reading in relation to the root of the opened project highlighted below)

<img width="684" alt="68020307-5dc90c00-fc9e-11e9-8122-03684072ec62 copy" src="https://user-images.githubusercontent.com/1271364/68040402-a4216980-fca4-11e9-815e-fe7926593c18.png">

I was also able to verify that changing the config in my custom config-file works and reads through into the configuration. 

Please verify that you are sending the correct directory path to the `configFile` argument and let us know the results.

**Comment by HugoGiraudel** [comment]
That’s also what I’ve noticed. The path to the configuration file is correctly displayed, however the configuration it contains doesn’t seem to be loaded. I can double check again on Monday, but I’m pretty sure that as soon as we use `--global`, the content of the configuration file is no longer loaded.

**Comment by eabusharkh0** [comment]
We also have an angular mono repo at my job.  My team has their own folder project out there.  I just upgraded to the 3.6 version of cypress from 3.4.1 and the tests are launching but the browser is blank.

Here is the command that I'm used to running in the older version that worked for me before: npx ng e customer-app-e2e --configuration=qa.  Now this command launches an empty browser when I run it with cypress 3.6.0.  Any help would be much appreciated.

**Comment by jennifer-shehane** [comment]
@eabusharkh0 Could you [open a new issue]*https://github.com/cypress-io/cypress/issues/new) detailing exactly what you are running and screenshots of what is happening? What you are describing is not related to the issue about the `configFile`. Thanks.

**Comment by HugoGiraudel** [comment]
@jennifer-shehane Hello Jennifer. I created a reproducible test case for you: https://github.com/HugoGiraudel/cypress-5570. The instructions are in the README.md, and I believe it should help diagnose the problem. :)

**Comment by jennifer-shehane** [comment]
Yeah, this is a strange situation. 

When cypress is run in `--global` mode in this way, it has no concept of the directory it is being run from yet, so passing it `src/config/cypress.json`, it's just not reading this in from the correct directory I think. 

Basically, we have not done a lot to support global mode in this manner because it is such an edge case that we rarely see, but I can confirm what you are experiencing - that the configuration values are not being read in `--global` mode from a specified `--config-file`.
