### ISSUE TITLE
`should()` does not retry `.not.to.throw()` assertion

### ISSUE THREAD

**Issue by omarmeky** [cypress-io/cypress#5572]
### Current behavior:

According to documentation for `should()`:

> The callback function will be retried over and over again until no assertions within it throw.

I am not getting this behavior, however, for a `.not.to.throw()` assertion. Rather, the callback is not retried.

### Desired behavior:

The callback function is retried until it passes (within the standard timeout).

### Steps to reproduce:

Here is an artificial example I wrote while debugging:

```
let fail = true;
cy.get('body').should(() => {
    expect(() => {
      if (fail) {
        throw new Error('fail was true');
      } else {
        fail = false;
      }
    }).not.to.throw();
  });
```

The output:

![image](https://user-images.githubusercontent.com/5597513/68044386-97554380-fcad-11e9-8faa-a5e7315dd51c.png)

The behavior suggests that the function was not retried. I also added some console logs and they show the `else` block never being reached. One weird thing is that the error message is different when I add logs (does not mention retrying):

![image](https://user-images.githubusercontent.com/5597513/68044232-4b0a0380-fcad-11e9-9aeb-a3c30dd2788b.png)

### Versions

Cypress 3.4.1
Mac 10.14

**Comment by omarmeky** [comment]
I tried the opposite and it passes:

```
let fail = false;
cy.get('body').should(() => {
    expect(() => {
      if (fail) {
        throw new Error('fail was true');
      } else {
        fail = true;
      }
    }).to.throw();
  });
```

**Comment by gabbersepp** [comment]
you should move the assignment of `fail = false` in the line direct above the `throw` In your example the variable is never set and thus every retry will throw an exception:

![image](https://user-images.githubusercontent.com/3234900/68143485-d1cf1280-ff31-11e9-8643-1e8848972076.png)

**Comment by gabbersepp** [comment]
tested with cypress 3.6.0

**Comment by omarmeky** [comment]
Thanks @gabbersepp, that was a hastily written example 😞 

Anyway, the issue with my actual code was that it was an async `throw` which I believe is not caught in these expectations (comes back as a promise rejection).
