### ISSUE TITLE
Suggestion: TypeScript: remove fallback for `should` to increase type safety

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#5573]
### Current behavior:
```ts
cy.get('foo').should('whatevergoeshere'); // no error :-(

cy.get('foo').should('exis'); // oops, typo—but no error :-(
cy.get('foo').should('exist'); // ✅
```

### Desired behavior:
```ts
cy.get('foo').should('whatevergoeshere'); // type error, `whatevergoeshere` is not a valid assertion

cy.get('foo').should('exis'); // type error, `exis` is not a valid assertion
cy.get('foo').should('exist'); // ✅
```

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-161) by [Unito](https://www.unito.io/learn-more)

**Comment by sainthkh** [comment]
I tried to remove this, but I think that's impossible with current chai.js. There are too many valid combinations and we cannot cover everything. And we might block some valid assertions. 

And this type of error is not hard to find. It can be easily found by running tests once. 

So, I decided to add more types and leave the fallback.
