### ISSUE TITLE
TypeScript: `then` does not return correct type when `undefined` is used

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#5575]
### Current behavior:
```ts
const result = cy.get('foo').then(el => el.attr('foo'))
```

Expected type: `Cypress.Chainable<string | HTMLElement>` (because `attr` returns `string | undefined`, and `then` ignores returned `undefined`s)

Actual type: `Cypress.Chainable<HTMLElement>`

I would also like to take this opportunity to ask if it's really necessary for `then` to ignore `undefined`s like it does. This tripped me up and I was very surprised to find that Cypress deviates from the standard promise behavior. In the example above I expected my promise to hold a type of `string | undefined`.

### Versions

┆Issue is synchronized with this [Jira Story](https://cypress-io.atlassian.net/browse/TR-117) by [Unito](https://www.unito.io/learn-more)

**Comment by gabbersepp** [comment]
@jennifer-shehane 

Casting the return value of `attr` to string works as expected:

![image](https://user-images.githubusercontent.com/3234900/68074093-a7e1e880-fd97-11e9-8248-19b901f2150d.png)

A possible solution would be to put this more specific definition just before the more generic one:

![image](https://user-images.githubusercontent.com/3234900/68074165-73baf780-fd98-11e9-9db2-46fd27df68ab.png)

But I do not know whether this is the desired way in this project.

**Comment by OliverJAsh** [comment]
I don't think changing the order of overloads will achieve the desired behavior here. The resulting promise should have type `Cypress.Chainable<string | HTMLElement>`, not `Cypress.Chainable<string>` nor `Cypress.Chainable<string | undefined>`.

**Comment by gabbersepp** [comment]
@OliverJAsh Ah ok. Now I know what is desired.
then() yields the last subject if the callback returns nothing (or "undefined").

But in this case you shouldm expect `Cypress.Chainable<string | JQuery<HTMLElement>` and not `Cypress.Chainable<string | HTMLElement>` I think.

**Comment by gabbersepp** [comment]
` then<S>(fn: (this: ObjectLike, currentSubject: Subject) => S | undefined): Chainable<S | Subject>` 
which will lead to:

![image](https://user-images.githubusercontent.com/3234900/68134109-ec998b00-ff21-11e9-8776-6363da31b71e.png)

**Comment by karol-majewski** [comment]
@gabbersepp This will also target functions that do not return `undefined` because `currentSubject: Subject) => S` is assignable to `currentSubject: Subject) => S | undefined` .

```ts
// Expected: Cypress.Chainable<string>
// Actual: Cypress.Chainable<string | JQuery<HTMLElement>
const result = cy.get('foo').then(el => `${el}`);
```

This can be fixed by adding two overloads:

```ts
    then<S>(fn: (this: ObjectLike, currentSubject: Subject) => Exclude<S, undefined>): Chainable<S>
    then<S>(fn: (this: ObjectLike, currentSubject: Subject) => S | undefined): Chainable<S | Subject>
```
