### ISSUE TITLE
3.6.0 - click event not firing when mouseup and mousedown are different elements 

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#5578]
currently, if the same element does not receive both the mouseup and mousedown, we do not fire the `click` event

The correct behavior is to fire the click event to the `commonAncestor` element.

This is a regression introduced in `3.6.0`

**Comment by jennifer-shehane** [comment]
This was causing an issue when testing our own Dashboard. 

![](https://user-images.githubusercontent.com/1271364/68052185-831a4200-fcbf-11e9-94df-4fcb09882417.png)

**Comment by lukeapage** [comment]
This is hitting us on quite a few tests while trying to upgrade to 3.6.0. Is there a plan to release soon? (am also blocked by critical issues in 3.5.0)

**Comment by Bkucera** [comment]
@lukeapage yes, we're working to get a 3.6.1 release out ASAP
