### ISSUE TITLE
Can not run packages/server e2e tests on Windows

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#5583]
### Current behavior:

This relates to #5523 I think.
I am not able to execute the server/e2e tests and thus would have a hard time to develop something in this package.

![image](https://user-images.githubusercontent.com/3234900/68074789-7a00a200-fd9f-11e9-8273-f910d0e19408.png)

### Desired behavior:

I want to execute the tests on WIn10

### Steps to reproduce: (app code and test code)

- checkout repo
- follow the steps in the package readme
- execute `npm run test-e2e -- --spec request_spec`

### Versions

Current Cypress develop branch, Win10, Powershell

**Comment by gabbersepp** [comment]
I upgraded Node to 12.0 and tried on both, cmd.exe and Powershell without success

**Comment by gabbersepp** [comment]
I think the problem is the mocha command:

![image](https://user-images.githubusercontent.com/3234900/68076425-7c212b80-fdb4-11e9-8409-c51b531ae802.png)

On Windows the `_mocha.cmd` should be executed but instead the bash file is selected. Thus the syntax is wrong on windows.
But if I change it temporary to "_mocha.cmd" it does also not run:

![image](https://user-images.githubusercontent.com/3234900/68076451-dde19580-fdb4-11e9-8420-31c4912aeb65.png)

Maybe the node process does not utilize cmd.exe to execute the batch file.

**Comment by gabbersepp** [comment]
![image](https://user-images.githubusercontent.com/3234900/68076533-04540080-fdb6-11e9-9eb4-0182d04617a9.png)

Why is the `_mocha.cmd` passed as command line arg to `mocha`?

**Comment by gabbersepp** [comment]
I think that the additional pushed argument is not necessary on windows because it is added a few lines above already.

If this is solution is OK I will have a look if it is the same problem in #5523

**Comment by jennifer-shehane** [comment]
Released in [3.7.0](https://on.cypress.io/changelog#3-7-0)
