### ISSUE TITLE
Can't use console to debug plugins run with "nodeVersion" : "system"

### ISSUE THREAD

**Issue by Talii123** [cypress-io/cypress#5587]
### Current behavior:

console.log(..) and console.error(..) statements in plugins do NOT produce output in the console used to open cypress if the {nodeVersion: "system"} setting is used.

All works as expected if:
* using Cypress v3.4 
* using Cypress v3.5, v3.6 provided that {nodeVersion: "system"} is not used.

### Desired behavior:

We should be able to continue to use console.log/error to print messages to the console as part of our debugging approach when running plugins with our system's node.

### Steps to reproduce: (app code and test code)

In your cypress.json, include:   
`  "nodeVersion": "system" `

In your plugin file, include:

`console.log('You can't see me!')`

### Versions

Cypress v3.5 and 3.6
OS: Windows 10
Browser: N/A

Related: https://github.com/cypress-io/cypress/issues/4432

**Comment by brian-mann** [comment]
Haven't looked into this, but we should be inheriting the `stdio` streams from the child process so they should log out. We'll look at it and see what's up. Should be an easy fix if that's the case.

**Comment by Talii123** [comment]
Yeah I figured as much. Thanks @brian-mann
