### ISSUE TITLE
Before function times out on its own

### ISSUE THREAD

**Issue by Francismb** [cypress-io/cypress#5589]
### Current behavior:
The before function in cypress can time out on its own without invoking any Cypress functions.

`before(() => {
    return Cypress.Promise((resolve) => setTimeout(resolve, 999999));
});`

### Desired behavior:
Allow for the before/after functions to accept a timeout parameter.
My use case is to wait for a backend queue task to get processed which can take up to 10 minutes.

### Steps to reproduce: (app code and test code)
`before(() => {
    return Cypress.Promise((resolve) => setTimeout(resolve, 999999));
});`

### Versions
Cypress@3.6.0
Chrome@77

**Comment by jennifer-shehane** [comment]
@frazboyz Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the logs here? 

Many CI providers automatically timeout after 10 minutes of no logs, so I wanted to isolate that this is Cypress sending the timeout and not your CI provider.

**Comment by frazboyz** [comment]
@jennifer-shehane this issues happens locally in the standard mode, I have no tried the CI mode but I presume it's the same.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
