### ISSUE TITLE
Cypress Tries to Scroll on Dropdown with 'position: fixed', Fails to Select from Dropdown in 3.5.0

### ISSUE THREAD

**Issue by TheWanderingWalnut** [cypress-io/cypress#5604]
### Current behavior:
Cypress expnds the dropdown and clicks on the proper row in the list, though the row which should've been clicked does not save into the dropdown.

### Desired behavior:
Cypress should expand the dropdown and select the option 'Five', in my below example, as it did back in v3.4.1.

### Steps to reproduce: (app code and test code)
1. Pull repo from here: https://github.com/TheWanderingWalnut/cypressReactPortalDropdown
2. Run `yarn install`
3. Run `yarn start`
4. Run the provided cypress test and observe that on Cypress 3.4.1 it works, while any higher version(s) will fail to select the correct value.

### Versions
Cypress v3.5.0/3.6.0
Mac OSX 10.14.6
Chrome 78 / Electron 73

**Comment by jennifer-shehane** [comment]
I can confirm this is failing in 3.6.0 and passing in 3.4.1 - although your assertion on visibility fails in both (is best to have a test asserting the value of the dropdown has changed).

Simplest code below:

https://github.com/TheWanderingWalnut/cypressReactPortalDropdown

```js
it("Changes dropdown value", () => {
  cy.visit("http://localhost:3000/");
  cy.contains("One").click();
  cy.contains("Five")
    .click();
  // This check will fail on Cypress v3.5.0+, works on v3.4.1
  cy.get('input[name=form-field-name]')
    .should('have.value', 'five'); 
});
```

**Comment by Bkucera** [comment]
Hi, this isn't a regression since this is intended behavior. We always try to scroll the element to the top of the screen which causes this to happen. Now the test correctly fails since hovering on the scrolled drop down causes it to snap away from the cursor

**Comment by TheWanderingWalnut** [comment]
Hello Ben,

Right, but in Cypress v3.4.1 this was not the case. Why was the behaviour changed, and why was this not mentioned in the release notes?

**Comment by Bkucera** [comment]
@TheWanderingWalnut  it is the first entry under "Bugfixes" in https://docs.cypress.io/guides/references/changelog.html#3-5-0. 

We properly send mouse hover events as of 3.5.0

**Comment by TheWanderingWalnut** [comment]
Ah okay, thank you, I didn't realize those were related. Well I suppose we'll have to work around this bug then. Thank you for the attempt.

**Comment by Bkucera** [comment]
@TheWanderingWalnut here's how I'd rewrite the test:

```js
  it("Builds a day product with an optional upsell", () => {
    cy.visit("http://localhost:3000/");
    cy.contains("One").click();
    cy.contains("Five")
      .should("be.visible")
      .click({force:true});
    cy.get('.Select-value').should('contain', 'Five').should('be.visible');
  });
```
