### ISSUE TITLE
Cypress Run Not Working On Jenkins Pipeline

### ISSUE THREAD

**Issue by LucasL94** [cypress-io/cypress#5612]
### Current behavior:
Electron never connect during yarn cypress run command
![image](https://user-images.githubusercontent.com/44097590/68249563-d9f48400-fffd-11e9-9bb3-9bf7d6316af6.png)

### Desired behavior:

I expect 3 tests to be executed in Jenkins build to log into the product and insert two types of forms

### Steps to reproduce: (app code and test code)

1. yarn install
2. yarn cypress run

![image](https://user-images.githubusercontent.com/44097590/68249729-2b047800-fffe-11e9-805a-7770083af545.png)

### Versions

Cypress 3.5.0
Windows server 2012
Node 10.16.0

**Comment by gabbersepp** [comment]
we have a similar setup that works like a charm. How does your cypress.json look like? are you running it in headless mode? only headless will work.

**Comment by LucasL94** [comment]
Hi gabbersepp, thanks for answering.
My cypress.json is pretty much empty at the moment, I only declared an environment variable
![image](https://user-images.githubusercontent.com/44097590/68254657-d36c0980-0009-11ea-89a1-cec873c82009.png)


I'm running Cypress with the `yarn cypress run` command, and for what I've been reading in the docs, this runs the headless mode by default, so I would assume it's doing that, right?

**Comment by gabbersepp** [comment]
Hi, yes that looks right.
You can try to get more log by setting the env variable. Should be able on windows with this line in your npm script section. If it is not working let me know. Then I can look into our code. Currently I am not at my work pc. 

"run" : "set DEBUG=cypress:* & & cypress open"

**Comment by LucasL94** [comment]
I kept trying and debugging but I still can't make it work in my CI server. Even though it works perfectly fine locally. Any more ideas?

**Comment by gabbersepp** [comment]
Can you provide us the output of the debug logging?

**Comment by LucasL94** [comment]
Ok, so I ran the debugger on Jenkins and found this. I still don't know why it's failing
![image](https://user-images.githubusercontent.com/44097590/68703370-46750300-0569-11ea-898a-9ca183a1b6b7.png)

**Comment by gabbersepp** [comment]
hey sorry for the late response. I have forget this thread.
Please try to deactivate videos. They should be set to `on` by default.

Tyr to use this in your cypress config
```
{
...
"video": false
...
}
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
