### ISSUE TITLE
Error when trying to get multiple aliases at once

### ISSUE THREAD

**Issue by TomaszG** [cypress-io/cypress#5616]
### Current behavior:

Cypress returns `TypeError: name.replace is not a function` error when trying to get() array of aliases and later spread it into multiple arguments:

![error](https://i.imgur.com/SakFUCC.png)

### Desired behavior:

Multiple aliases should be spread into multiple arguments in an arrow function (code below should not end up with an error)

### Steps to reproduce: 

Run the following code:
```js
describe('Cypress get() function', () => {
  it('should have ability to spread multiple aliases', () => {
    cy.wrap('value1')
      .as('alias1')

      .wrap('value2')
      .as('alias2')

      .get(['@alias1', '@alias2'])
      .spread((var1, var2) => {
        expect(var1).to.be.equal('value1');
        expect(var2).to.be.equal('value2');
      });
  });
});
```

### Versions

Cypress 3.6.0,
macOS

**Comment by jennifer-shehane** [comment]
`cy.get()` does not accept an array of aliases as arguments. See [`cy.get()` docs](https://on.cypress.io/get#Arguments).
