### ISSUE TITLE
Unable to Log In to Facebook...cookies anabling error message

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#5621]
### Current behavior:
**cookies issue.**
"**There was an error with your request. Please make sure your browser has cookies enabled and try again."**

### Desired behavior:
On clicking on the button, a new page should open allowing the user to proceed with the next step of signUp process

### Steps to reproduce: (app code and test code)
**Run this sample cypress code. its supposed to sign up the user in facebook**
```js
describe('My First test Suit', ()=>{
it('Create Facebook Account', ()=> {
cy.visit('https://www.facebook.com')
cy.wait(2000)
cy.get('#u_0_f').type('Claudine')
cy.get('#u_0_h').type('Milo')
cy.get('#u_0_k').type('6606656666')
cy.get('#u_0_p').type('Bryano#44')
cy.get('#month').select('Jan')
cy.get('#day').select('20')
cy.get('#year').select('2000')
cy.get('#u_0_9:visible').click()//femal
cy.get('#u_0_a').click()//male
cy.get('._1lch').find('button').click()
})

//it('Log in to facebook ', ()=>{

})
})
```

### Versions

Win10
cypress version 6.12.0
chrome 78
Electron 73

**Comment by jennifer-shehane** [comment]
@ghost I'm not sure exactly why this error is prompting. It seems that Facebook likely prompts for consent to use cookies and this is not triggered at the time this is run. 

Regardless, we do not support running automated scripts on website you do not control. See our full guidelines here: https://docs.cypress.io/guides/references/best-practices.html#Visiting-external-sites 

Creating accounts on Facebook through automated scripts is likely also against Facebook's TOS.
