### ISSUE TITLE
click red target is at the wrong position in 3.5.0

### ISSUE THREAD

**Issue by warpdesign** [cypress-io/cypress#5624]
### Current behavior:
When issuing a click on a element using the `click` command and specifying the position, for eg. `cy.get('button').click(10, 2)`, there is a red pointer that is supposed to indicate where the click was issued but it always appears at the bottom of the button:

![image](https://user-images.githubusercontent.com/199648/68384403-d70da680-0157-11ea-925e-6ce3727c3096.png)

Other signatures of the click command seem to show the red indicator at the correct position.

### Desired behavior:
The red indicator should be there:

![image](https://user-images.githubusercontent.com/199648/68384500-04f2eb00-0158-11ea-82de-c0ea26bd53c1.png)

I thought the click was happening at the wrong position before I noticed that it's actually the red indicator that's not at the correct position.

### Steps to reproduce: (app code and test code)
I created a sample app [here](https://github.com/warpdesign/cypress-click-test). First run the server with `npm run server` then open Cypress with `npm run cypress:open`, the project contains a single spec file, comparing the three call signatures of the `click` command.

The third test exhibits the problem. Also notice how when clicking on the `click` operation on the left, the red indicator moves down after the click operation but doesn't move when using `click()` without any parameter:

![click-problem](https://user-images.githubusercontent.com/199648/68385077-4cc64200-0159-11ea-830b-1c079f32201b.gif)

### Versions
Cypress: 3.6.0
OS: macOS Catalina
Browser: Chrome 78

**Comment by jennifer-shehane** [comment]
Just to make the issue a bit clearer - I made the 'button' 50px x 50px with a bg color (cause I wasn't sure how large it was from the initial video)

The button should be clicked at 20, 1 which would be 20px to the right and 1px down, but it is clicked at the lower left corner (this happens regardless of the `onclick` handler's existence.

The `onclick` handler demonstrates the second problem of the red indicator moving in the snapshot.

`index.html`

```html
<!DOCTYPE html>
<html>
<body>
<button 
  style="width: 50px; border: none; background-color: cyan; height: 50px;"
  onclick="log.innerHTML='clicked!'">
    Click me!
</button>
<div id="log"></div>
</body>
</html>
```

`spec.js`

```js
it('click at (20, 1) of button should show message', () => {
    cy.visit('index.html')
    cy.contains('Click me!').click(20, 1)
    cy.get('#log').should('contain', 'clicked!')
})    
```

## 3.4.1

![](http://g.recordit.co/GWYSc7uXP9.gif)

## 3.5.0

![](http://g.recordit.co/hhqe76ahiP.gif)

**Comment by Bkucera** [comment]
I've found the issue and should have a bugfix PR up soon. Thanks for catching this!

**Comment by warpdesign** [comment]
Great! This drove me crazy last week since I thought the click wasn't happening at the right position :)
