### ISSUE TITLE
cy.getCookie() do not support path option

### ISSUE THREAD

**Issue by lauterry** [cypress-io/cypress#5627]
### Current behavior:

My cookies are stored using a path= "/fr-FR". I cant read those cookies using `cy.getCookie` since I can't specify the path in the options.

`cy.setCookie` supports path in his options.

### Desired behavior:

I want to be able to specify `path` in the `cy.getCookie` options like `cy.getCookie("auth", {path: "/fr-FR"})` in order to read the cookie store un a specific path

### Versions

Cypress version : 3.4.1
OS : MACOS MOJAVE v 10.14.6

**Comment by jennifer-shehane** [comment]
Since this feature hasn’t gotten a lot of interest over the years, we’ll close this issue.
