### ISSUE TITLE
Cypress do not write in input field and display this error

### ISSUE THREAD

**Issue by CaioWillianMoreira** [cypress-io/cypress#5628]
**Cypress do not write in input field and display this error**

cy.get('#buy-box .builder__step[data-step-number="1"] input[qa-automation][name="Nome"]').type('Teste') 

TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.

Command:     type
cypress_runner.js:177821 Typed:       Test
cypress_runner.js:177821 Applied To:  `<input qa-automation name=​"Nome" maxlength=​"12" class=​"builder-input ns-maxlength ns-only-letters" type=​"text" placeholder=​"Nome" required supportedchars=​"alphanumeric" builder-input-sku=​"004-7788-002-01" builder-input-step=​"1" builder-input-name=​"Nome" builder-input tabindex=​"-1" autocomplete=​"off" autocorrect=​"off" autocapitalize=​"off" spellcheck=​"false">​`
cypress_runner.js:177821 Elements:    1
cypress_runner.js:177821 Coords:      {x: 845, y: 955}
cypress_runner.js:177920 Mouse Move Events
cypress_runner.js:177920 Mouse Click Events
cypress_runner.js:177920 Keyboard Events

**Comment by Bkucera** [comment]
@CaioWillianMoreira can you provide a reproducible example or a publicly hosted site that demonstrates this issue? Otherwise we cannot reproduce and fix the issue

**Comment by CaioWillianMoreira** [comment]
**I managed to solve it that way**

```
cy.get('div[builder-combo-step="4"].active')
       .find('input[qa-automation][name="Nome"]')
       .invoke('attr', 'value', 'Stallone cobra')
       .should('have.value', 'Stallone cobra')
```

**Comment by CaioWillianMoreira** [comment]
**I managed to solve it that way**

```
cy.get('div[builder-combo-step="4"].active')
       .find('input[qa-automation][name="Nome"]')
       .invoke('attr', 'value', 'Stallone cobra')
       .should('have.value', 'Stallone cobra')
```
