### ISSUE TITLE
Clicking on "set up project to record" then closing "log in" modal leaves modal backdrop covering app in 3.5.0

### ISSUE THREAD

**Issue by gittyhubberess** [cypress-io/cypress#5631]
### Current behavior:
the log in pop-up:
![image](https://user-images.githubusercontent.com/57494933/68402484-afc8d080-017b-11ea-8b84-d44ed86474e0.png)

cypress.exe unresponsive and not operational:
![image](https://user-images.githubusercontent.com/57494933/68401700-7a6fb300-017a-11ea-9b6c-9d85e7ca443c.png)

### Desired behavior:

cypress.exe is fully operational after closing the "Log in" pop-up.

### Steps to reproduce: (app code and test code)

1. open cypress.exe
2. under the section "Recent Projects" , click on any recent opened project which has no runs recorded.
3. on the tabs menu, click on "Runs" tab => result: it will display a page with a title that says "You have no recorded runs"
4. click on the blue button at the bottom "Set up project to record"
5. on the Log in pop-up message ,click on the X button at the right upper corner of the message
6. observe behavior of cypress.exe

**Another scenario to reproduce:**

same as above scenario from step 1 to step 4 and then:

5. on the Log in pop-up message ,click on "Log In to Dashboard" 
6. close the browser tab that has opened
7. go back to the cypress.exe window => the "Log In" window is still open and the status shown is "Waiting for browser login ..."
8. on the Log in pop-up message ,click on the X button at the right upper corner of the message
9. observe behavior of cypress.exe

*the only way to go back to a functional cypress.exe is to close it and open it again.

**A Scenario where it does not reproduce:** 

if the "Log in" pop-up message is opened via the upper right corner icon of "Log In". 

### Versions
cypress.exe version 3.6.0
browser: chrome Version 77.0.3865.120 (Official Build) (64-bit)
OS: windows 10 enterprise x64

**Comment by jennifer-shehane** [comment]
Yes, this is a bug. Showing a video below. The `.modal-backdrop in` never goes away and covers the content even after hitting `x` to close the modal. 

This does not happen in 3.4.1 and was introduced in 3.5.0.

![](http://g.recordit.co/vSSsSmuMbf.gif)

<img width="1423" alt="Screen Shot 2019-11-07 at 4 48 49 PM" src="https://user-images.githubusercontent.com/1271364/68430707-8eb5af00-017e-11ea-99ec-34c2000ca8cb.png">
