### ISSUE TITLE
Cy.contains throws wrong error message when 2nd argument is not valid (since 3.5/6)

### ISSUE THREAD

**Issue by Narretz** [cypress-io/cypress#5649]
### Current behavior:

With an *incorrect* use of `cy.contains()`:

```js
it('should throw the correct error', () => {
  // Calling contains with an invalid second parameter generates a wrong error;
  cy.contains('.container', ['Wrong', 'Type'])
})
```

cypress throws this error:

```
CypressError: cy.get() only accepts an options object for its second argument. You passed Wrong,Type
```

### Desired behavior:

The error should reflect that:

- the function is `cy.contains`, not `cy.get`
- the second argument is the wrong type, but `cy.contains` does accept "content" at the second position if the first argument is "selector"

Note that this error is only thrown since 3.5/ 3.6. Before, this was executed without an error.

### Steps to reproduce: (app code and test code)

The above spec is enough to reproduce the error.

### Versions

3.6

**Comment by jennifer-shehane** [comment]
Running the test provided in 3.6.1 does not throw this error for me. I tried it against various DOM structures also and could never get it to throw. 

Mind you, it does really weird things when I pass in an Array, but I couldn't get it to show this error. Can you provide an exact example with HTML to recreate?

My example. 

```js
  it('cy.contains() wrong argument', () => {
    cy.visit('https://example.cypress.io/commands/querying')
    cy.contains('.third', ['bananas'])
  })
```

<img width="777" alt="Screen Shot 2019-11-12 at 7 43 18 PM" src="https://user-images.githubusercontent.com/1271364/68722865-da07fd00-0584-11ea-81a4-aa5529abe234.png">

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by Narretz** [comment]
Thanks for the fast response. Weird thing is that I still see the error with 3.6.1, and the exact example you used. I'm using Windows, and `cypress open` (but it looks like you do, too). Can't really think of anything else that could cause this difference.
