### ISSUE TITLE
Cypress unable to click an element - scrolls up & down infinitely

### ISSUE THREAD

**Issue by kamituel** [cypress-io/cypress#565]
- Operating System:
Max OS X 10.11.6

- Cypress Version:
0.19.4

- Browser Version:
Canary 61

### Is this a Feature or Bug?
Bug

### Current behavior:
When attempting to click a first (or any other I think) element in the table, Cypress would start to scroll it up and down until a timeout happens. Error message is:

> CypressError: Timed out retrying: cy.click() failed because this element is being covered by another element:
> 
> &lt;div style="position: sticky; top: 60px; left: 0; width: 100%; height: 36px; z-index: 10; background-color: tomato;">&lt;/div>

### Desired behavior:

First row just gets clicked. Table is positioned correctly from the start and no scrolling/flickering happens.

### How to reproduce:

Save this file:

```html
<!DOCTYPE html>
<!-- saved from url=(0023)http://localhost:8445/# -->
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
</head>
<body style="box-sizing: border-box">
    <div id="app">
        <div style="position: fixed; top: 0; left: 0; width: 100%; height: 60px; z-index: 10; background-color: red"></div>
        <div style="position: relative; top: 60px; width: 100%">
            <div style="position: absolute; top: 0; width: 100%">
                <div style="position: sticky; top: 60px; left: 0; width: 100%; height: 36px; z-index: 10; background-color: tomato;"></div>
                <div style="margin: 0 20px 30px 15px">
                    <table>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>2</td>
                                <td>3</td>
                                <td>4</td>
                            </tr>
                            <!-- many more rows here -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
```

Just maybe add many more rows, I truncated those for readability. Or use a file I host on Google Drive (link below).

Then serve it:

```bash
$ python -m SimpleHTTPServer
```

Finally, run test:

#### Test code:

```js
describe("Quirk.", () => {
  beforeEach(() => {
    cy
      .visit("http://localhost:8000/cypress-quirk.htm")
      .get("#app > div > div > div > table > tbody > tr:first-child")
      // Using force: true fixes this test.
      .click({force: false});
  });

  it("blah", () => {
    // Nothing, cypress never gets to this point anyway.
  });
});
```

### Additional Info (images, stack traces, etc)

Video of the behaviour, as well as test HTML file that fails, are here: https://drive.google.com/open?id=0B_Kr8lR7GpI6NFM0ajNwNnd6OGM

Also note that using `{force: true}` fixes this. Not sure why I need that though - first row should never be covered by another element, and in fact it isn't when I open the file in regular Chrome Canary. I verifed that using screenshot captures on "performance" tab in dev tools - first row appears well below the positioned `div`'s right from the start, there's no flickering there.

**Comment by brian-mann** [comment]
Thanks for going into so much detail, especially when providing a video - that really helps us.

We'll take a look at this and update the issue.

**Comment by kamituel** [comment]
No problem at all. I do solve bug reports from time to time myself and so I know how useful few details can be :) Cheers

**Comment by brian-mann** [comment]
I'm pretty sure this is now resolved by fixing #553, and #569. I'll keep this issue open until after 0.20.0 comes out which will enable you to verify it works.

**Comment by brian-mann** [comment]
I have verified this is still broken even with new `0.20.0` code, so working on it now. It no longer bounces up and down, but the first row is still being partially covered when there is a huge number of rows.

**Comment by brian-mann** [comment]
The bouncing has been fixed, and a new issue has been opened to specify the sticky + multiple covered elements behavior.

Closing in favor of issue: #571
