### ISSUE TITLE
Fixture data not available to dynamically generate tests

### ISSUE THREAD

**Issue by gurjeetbains** [cypress-io/cypress#5652]
I am trying to dynamically generate tests. I am have fixtures in before hook which reads data from the `example.json`. One of the key value pair is an array. But when i try to dynamically generate tests it throws error saying the variable is `undefined` 
Here is the `example.json` file

```json
{
  "name": "Using fixtures to represent data",
  "email": "hello@cypress.io",
  "body": "Fixtures are a great way to mock data for responses to routes",
  "ess":["bar","foo"]
}
```

And here is the test 

```js
/// <reference types="Cypress" />
describe('test',()=>{
    before(function(){
        cy.fixture('example').then((dats)=>{
            this.dsw=dats
        })
        cy.log('before')
    })
    beforeEach(function(){
        cy.log('beforeeach')
    })
    it('test1',function(){
        cy.log(this.dsw.name)
    })
    (dsw.ess).forEach(function(datas){
        it('swa '+datas,function(){
            cy.log(datas)
        })
    })
    it('test2',function(){
        cy.log('@exam.ess[1]')
    })
})
```

Here is the error in test runner

```
Uncaught ReferenceError: dsw is not defined
```

**Comment by jennifer-shehane** [comment]
Things attached to `this` will only be available *within* the context of another test (`it` function). 

There are some examples of dynamic tests in our recipes, including one for how to create dynamic tests from a file. https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__dynamic-tests/cypress/integration/fixture-spec.js

**Comment by dhuriaditi1** [comment]
I am getting No tests found error for the example shared above. I copied and tried to run fixture-spec .
<img width="742" alt="image" src="https://user-images.githubusercontent.com/83175299/135037609-4fbd644f-bddb-40c9-b9c4-398b878e9992.png">

**Comment by dhuriaditi1** [comment]
reported a new issue since this one is already closed - https://github.com/cypress-io/cypress/issues/18269
