### ISSUE TITLE
Mouse events not sending pointerId

### ISSUE THREAD

**Issue by testorangemac** [cypress-io/cypress#5660]
### Current behavior:

```
Failed to execute 'setPointerCapture' on 'Element': No active pointer with the given id is found.
```

### Desired behavior:

`Element.hasPointerCapture()` is not invoked by Cypress:
https://developer.mozilla.org/en-US/docs/Web/API/Element/hasPointerCapture

### Steps to reproduce: (app code and test code)

Use the code from:
https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture 

We created 2 simple examples (attached as zips, see below):

1) A slider object which uses pointer capture
2) A canvas which uses pointer events to draw

### Versions

Cypress: 3.4.0 - 3.6.1
OS: Win10
Browser: Chrome 78

### Attachments

[CanvasPointer.zip](https://github.com/cypress-io/cypress/files/3832142/CanvasPointer.zip)
[PointerCapture.zip](https://github.com/cypress-io/cypress/files/3832134/PointerCapture.zip)

**Comment by testorangemac** [comment]
We did find a solution (with the assumption Chrome always uses pointerId 1):
```js
cy.get('#slider")
   .trigger("pointerdown", { pointerId: 1 })
   .trigger("pointermove", { clientX: 250 })
   .trigger("pointermove", { clientX: -150 })
   .trigger("pointerup", { pointerId: 1})
```

**Comment by jennifer-shehane** [comment]
I'm unable to open the zip files attached. Can you provide a link to a repo or something that will open?

Can you clarify exactly which Cypress command is effected? Are you solely concerned with the `.triger()` command or were you using `.click()`, `.rightclick`, `.dblclick`?

**Comment by testorangemac** [comment]
Here's a [link ](https://codepen.io/testorangemac/pen/aboWeJQ?&editable=true)to a Codepen repo or you can use https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture

At first we did not get it working with the .click() command. Later we used the .trigger() command because we also needed a move after a click.

**Comment by jennifer-shehane** [comment]
@testorangemac Thanks for providing this!

**Comment by reno1979** [comment]
Same problem here, our code depends on a valid pointerId. Thus the current click() from Cypress is not accepted and throws a invalid PointerId exception

**Comment by connerleverett** [comment]
> We did find a solution (with the assumption Chrome always uses pointerId 1):
> 
> ```js
> cy.get('#slider")
>    .trigger("pointerdown", { pointerId: 1 })
>    .trigger("pointermove", { clientX: 270 })
>    .trigger("pointermove", { clientX: 150 })
>    .trigger("pointerup", { pointerId: 1})
> ```

I found that this didn't work in Firefox, but simply changing the `pointerId` from `1` to `0` did.
```
 cy.get('#slider")
    .trigger("pointerdown", { pointerId: 0 })
```
