### ISSUE TITLE
type() parseSpecialCharSequences: false, does not work (headless electron cli)

### ISSUE THREAD

**Issue by nabilamin** [cypress-io/cypress#5661]
### Current behavior:
I currently have a function in a page object file (typescript) that types in a string with the special character `{`. 

In order to get this to type properly I set the `parseSpecialCharSequences` option to `false` and it works when running the test through the GUI. However running the same test through the CLI more specifically headless electron, the following error is thrown as if the `false` flag has been ignored ... 

```
CypressError: Special character sequence: '{...}' is not recognized
``` 

Using `{{}` as outlined here - https://docs.cypress.io/api/commands/type.html#Arguments - makes it work through the CLI with `parseSpecialCharSequences` still set to `false` when that should not be the case. 

It may be important to note that the string I am passing in has a nested object so the string looks something like this

```
{
   key: value
    {
       key:value
    }
}
```

### Desired behavior:

the `parseSpecialCharSequences` on `cy.type()` should not be ignored when running cypress through the cli.

### Steps to reproduce: (app code and test code)

- Try to type a string with the special char `{` using `cy.type()`.
- Set the `parseSpecialCharSequences` option to `false` on `cy.type()`.
- Run the test through the cli (headless electron)

```js
cy.get('ace-editor > textarea').type(data.nestedObject, {force: true, parseSpecialCharSequences: false});
```

### Versions

3.6.0, Mac OSCatalina, electron (headless)

**Comment by jennifer-shehane** [comment]
I cannot recreate this in Cypress 3.6.0 or Cypress 3.8.1 in Electron during `cypress open` or `cypress run`. Please comment with the exact test code to run against an application that will recreate the error. 

My test code is below.

`index.html`

```html
<!DOCTYPE html>
<html>
<body>
<textarea></textarea>
</body>
</html>
```

`spec.js`

```js
it('type special chars', () => {
  cy.visit('index.html')
  cy.get('textarea')
    .type('{key: {key: "foo"}}', { parseSpecialCharSequences: false })
})
```

![](http://g.recordit.co/82le42AObT.gif)
