### ISSUE TITLE
Feature: Run until test fails (debug flakey/intermittent errors)

### ISSUE THREAD

**Issue by MadLittleMods** [cypress-io/cypress#5665]
Add a way to keep re-running the test-suite until you run into a failure. When debugging flakey, intermittent failures, it would be nice to just keep retrying the tests until something fails. I don't want to keep pressing re-run manually.

This could be accomplished with `cypress run` and some outside scripting on top of it but I want to do this inside the `cypress open` test runner. Using `cypress run` is also tough to get useful info out of when a failure happens but this is being tracked by https://github.com/cypress-io/cypress/issues/448

There is a **Run all tests** button in the UI but it only re-runs the test suite once. I want to keep retrying the test suite until some test fails.

![](https://i.imgur.com/sQ33x28.png)

---

Related issues but mainly around retrying failed tests,

 - https://github.com/cypress-io/cypress/issues/518
 - https://github.com/cypress-io/cypress/issues/1599
 - https://github.com/cypress-io/cypress/issues/4886

**Comment by gabbersepp** [comment]
Maybe you can take the great retry plugin and inverse its behaviour? Should not be too much efford i think

**Comment by gabbersepp** [comment]
Or open an issue in its repository. Maybe the owner introduces a flag to switch between both modes?

**Comment by MadLittleMods** [comment]
Thanks @gabbersepp! Created an issue over there, https://github.com/Bkucera/cypress-plugin-retries/issues/37

**Comment by jennifer-shehane** [comment]
There is an example in our recipes that kind of does something similar to this here: https://github.com/cypress-io/cypress-example-recipes/blob/master/test-repeat.js

**Comment by alxndr** [comment]
I've defined [a shell function which re-runs the command given until it fails](https://github.com/alxndr/dotfiles/blob/18c0b4f04d89/.zshenv#L48-L53)...

```shell
until_fail () {
        eval "$@"
        while [ "$?" -eq "0" ]
        do
                eval "$@"
        done
}
```

Example usage:

```
$ until_fail npm run -s cypress:run -- --spec cypress/integration/spec_file.js
```

**Comment by jennifer-shehane** [comment]
Please try our 'experimentalRetries’ feature. We’ll be coming out with more around flake detection soon. I’ll close this since we’ve already prioritized this work.

**Comment by ConorFayleTCO** [comment]
hi @jennifer-shehane am I right in thinking this feature is locked behind the Team plan, even for running locally? If so, that would be quite disappointing.

**Comment by gabbersepp** [comment]
> hi @jennifer-shehane am I right in thinking this feature is locked behind the Team plan, even for running locally? If so, that would be quite disappointing.

We are using native retry function since 5.0.0 or so without team plan. This is the original issue where the feature was introduced:
https://github.com/cypress-io/cypress/issues/1313#issuecomment-677275014

not sure what are the differences to the new experimental retry feature

**Comment by morremeyer** [comment]
@jennifer-shehane experimentalRetries do not solve this: The question here is to have a feature that enables running *until* a test fails. This would help debugging flaky tests since it is cumbersome to manually run them until they fail.

experimentalRetries are a feature to retry a test *after* it has already failed, and therefore does not solve this question.

**Comment by wburgess-sdx** [comment]
Aren't y'all automation engineers? :P

Paste this into the `cypress` debug window's console, restart your tests, invoke it: `runUntilWheelsFallOff()`, and close the console because it can cause the window to crash if tests are running with it open.

It will check every 3 seconds and retry if no failures. If there are failures it will play a lovely beep sound.

```javascript
let runUntilWheelsFallOff = async function() {
    let failures = null;
    const alertSound = new Audio("https://cdn.freesound.org/previews/66/66589_321967-lq.mp3")
    while (!failures) {
        console.log(`Checking...`)
        await new Promise(resolve => setTimeout(resolve, 3000))
        const stopButtonExists = document.querySelectorAll('[class="stop"]').length !== 0
        failures = document.querySelector('[class="failed"]').textContent.match(/\d/g)
        if (!stopButtonExists && !failures) {
            document.querySelector('[class="restart"]').click()
        }

    }

    alertSound.play() // will play when failures are found
}
```
