### ISSUE TITLE
Vuex: window.app not accessible from tests

### ISSUE THREAD

**Issue by mspoulsen** [cypress-io/cypress#5667]
Hi, I am following this tutorial https://www.cypress.io/blog/2017/11/28/testing-vue-web-application-with-vuex-data-store-and-rest-backend/ trying to test my vuex store.
However I am unable access the app object from my tests. This is how I try to attach the app object to window in main.ts:

```javascript
const app = new Vue({
    router,
    store,
    render: (h) => h(App)
})
// @ts-ignore
window.app = app
app.$mount('#app')
```
It works when I open http://localhost:8080/ in my browser but when I run my cypress test via cypress open I get window.app is undefined.

```javascript
it('store test', () => {
    cy.window().then((win) => {
        console.log(win)
    })
})
```
Any ideas?

**Comment by mspoulsen** [comment]
Solved: Had to do a cy.visit("/") before cy.window().
Would have been nice if that was mentioned in the tutorial. I am not the only one who has made that mistake :)

**Comment by bahmutov** [comment]
Great, thank you @mspoulsen - I have updated the blog post to make it explicit and avoid future confusion.
