### ISSUE TITLE
which command need to run on CI/CD

### ISSUE THREAD

**Issue by cullsin** [cypress-io/cypress#5672]
Hello, 

I have successfully included cypress command into package.json

 `  "cy:run": "cypress run", `
   ` "cy:open": "cypress open",`
    `"uitest": "start-server-and-test start http://localhost:3000 cy:run",`
    `"uidebug": "start-server-and-test start http://localhost:3000 cy:open" `

Which command that I need to run inside CI / CD without server or browser. ( I hope you understand that is run on command line ) ?

**Comment by bahmutov** [comment]
on CI/CD you should do
```
npm run uitest
```
which will trigger `cypress run` after server has been started

**tip:** you can shorted `start-server-and-test` command because `start` is default command, and you can simply use port number, so you block would be
```
"cy:run": "cypress run",
"cy:open": "cypress open",
"uitest": "start-server-and-test 3000 cy:run",
"uidebug": "start-server-and-test 3000 cy:open"
```
