### ISSUE TITLE
Support Safari browser

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#5673]
### Desired behavior:

Cypress should support the Safari browser on MacOS.

(I see there is an issue for Firefox, but I couldn't find one for Safari. Feel free to link & close this as a duplicate if I missed it.)

**Comment by donysukardi** [comment]
This definitely. Would love to be able to run tests against Safari on iOS (macOS should also be a good enough target)

**Comment by jordandlaman** [comment]
Obviously things can change but I have been monitoring the cross browser state of cypress for a while and it was mentioned by at least one cypress dev in the past that safari is difficult for multiple reasons and that it would be probably come last on cross browser road map.  Just FYI.

**Comment by elgalu** [comment]
Indeed, there are open [PRs for Firefox and MS Edge latest](https://github.com/cypress-io/cypress/issues/310#issuecomment-577627854) so I guess they will start working on Safari after that.

**Comment by amirrustam** [comment]
Closing in favor of #6422
