### ISSUE TITLE
Cypress config files should support "extends" option

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#5674]
### Desired behavior:

TypeScript config files (`tsconfig.json`) allow the user to "extend" an existing file, e.g.:

`tsconfig.json`:
```json
{
  "someOption": "value",
  "someOption2": "value2"
}
```

`tsconfig.test.json`:
```json
{
  "extends": "./tsconfig.json",
  "someOption": "value3"
}
```

The end result is that the TypeScript compiler sees `tsconfig.test.json` as this:

```json
{
  "someOption": "value3",
  "someOption2": "value2"
}
```

This allows the config files to remain DRY and avoid duplicating data, but still have multiple files for different scenarios.

Now that cypress has the `--config-file` option, I think `cypress.json` should support this too.

**Comment by pitgrap** [comment]
I like this. We wrote some function in our CypressPlugin.js to do this for us. Would be nice, if this is supported by default.

**Comment by stefanzmf** [comment]
@pitgrap is there any chance you could share the functionality you are talking about? thanks a lot.

**Comment by martinsik** [comment]
I would love this functionality too. Is this open for PRs?

**Comment by bahmutov** [comment]
If we implement https://github.com/cypress-io/cypress/issues/5941 then it would be simple for an external plugin to do this, see https://github.com/bahmutov/cypress-extends-example

**Comment by stevenvachon** [comment]
This is really needed.

**Comment by stevenvachon** [comment]
I've been trying to find the file(s) that handle config parsing, but the source code is like spaghetti to me.

**Comment by stevenvachon** [comment]
Anything?

**Comment by mstruensee** [comment]
^^ same, this is something that would be useful, or allowing to do a js config file vs json only

**Comment by bahmutov** [comment]
I have implemented a userspace plugin to read configs that use `extends` and merge them, see https://github.com/bahmutov/cypress-extends 

We will publish a blog post next week describing it, follow https://www.cypress.io/blog/

**Comment by bahmutov** [comment]
Can I ask what is the issue @mstruensee ? That you point at a different plugins file or disable it completely?

**Comment by mstruensee** [comment]
also, we changed the location of where the cypress files are located, and that needs to be in the base.json ... cannot be overridden in the extends :(

**Comment by bahmutov** [comment]
Seems @mstruensee your best best is to load the config yourself using plugins code, since the situation is so complex

**Comment by mstruensee** [comment]
yes, trying to, but I need to figure out how to lap into cypress load process ... by the time you get into plugins/index.js the config is already loaded

**Comment by Camo30** [comment]
Unfortunately the plugin from @bahmutov doesn't work in my environment. This should work out of the box

**Comment by ling1726** [comment]
@bahmutov  @jennifer-shehane  An extra scenario where this would be useful: in Fluent UI we have a lerna monorepo. We would like each package to be responsible for its own cypress tests, but would like to have one place for test helpers and configurations. At the same time a package should be able to extend or override the base config.

It seems too heavy weight to create a completely new package in the monorepo just to share cypress utilities, if it's possible to do path extension

```
packages/
├── scripts/ cypress
│   ├── fixtures
│   ├── plugins
│   ├── support
│   ├── cypress.json // base
├── menu/
│   ├── package.json
│   ├── Menu.spec.ts
|   ├── cypress.json // extends root
└── button/
    ├── package.json
    ├── Button.spec.ts
    ├── cypress.json // etends root
```

**Comment by jennifer-shehane** [comment]
We're working on replacing the cypress.json config with a cypress.config.js file, that can be written in JavaScript to define config, so I think this makes this issue no longer relevant. 

Issue: https://github.com/cypress-io/cypress/issues/5218
PR: https://github.com/cypress-io/cypress/pull/17000

**Comment by Hotell** [comment]
@jennifer-shehane curious why was this closed as nothing has been implemented/released yet? can we re-open to not confuse folks reading this ? 

github will auto-close this, once proper solution was implemented/merged ( that will reference this issue ). thx
