### ISSUE TITLE
backface-visibility: hidden with transform-style: preserve-3d fails the "is.visible" test

### ISSUE THREAD

**Issue by loekup** [cypress-io/cypress#5682]
### Current behavior:
Currently an element with `backface-visibility: hidden; transform: rotateY(180deg);` that is inside a parent with `transform-style: preserve-3d; transform: rotateY(180deg)` will fail the `is.visible` assertion

The same problem mentioned in #2985 was marked as fixed by https://github.com/cypress-io/cypress/pull/5591 i only think the case where the parent has the css property `transform-style: preserve-3d;` was forgotten

### Desired behavior:
it should not fail the `is.visible` assertion

### Steps to reproduce: (app code and test code)

**app code**
https://codepen.io/loekup/pen/rNNZqZW

**test code**
```js
describe('backface-visibility: hidden; test', function () {
    it('should flip and validate the visibility of the card faces', function () {
        cy.visit('index.html')
        cy.get('.front').should('be.visible');
        cy.get('.back').should('not.be.visible');
        cy.get('.container').click();
        cy.get('.front').should('not.be.visible');
        cy.get('.back').should('be.visible');
    });
});
```

### Versions
3.6.1.

**Comment by loekup** [comment]
Hey guys, any update on this? would it be possible for you guys to confirm that this is an issue ?

**Comment by jennifer-shehane** [comment]
Hey @loekup, yes this indeed is not being calculated correctly in Cypress 3.7.0.

`index.html`

```index.html
<!DOCTYPE html>
<html>
<body>
  <style type="text/css">
    .container {
      position: relative;
      transform-style: preserve-3d; /* This breaks visible check */
      width: 200px;
      height: 300px;
    }

    .flipped {
      transform: rotateY(180deg);
    }

    .face {
      backface-visibility: hidden;
      position: absolute;
      width: 100%;
      height: 100%;
    }

    .front {
      background: blue;
    }

    .back {
      transform: rotateY(180deg);
      background: red;
    }
  </style>

  <div class="container">
    <div class="face front">
      Front
    </div>
    <div class="face back">
      Back
    </div>
  </div>
  
  <script>
    const container = document.querySelector('.container');
    container.addEventListener('click', () => {
      container.classList.toggle('flipped');
    })
  </script>
</body>
</html>
```

Failing `spec.js`

```js
it('should flip and validate the visibility of the card faces', () => {
  cy.visit('index.html')
  cy.get('.front').should('be.visible')
  cy.get('.back').should('not.be.visible')
  cy.get('.container').click()
  cy.get('.front').should('not.be.visible')
  cy.get('.back').should('be.visible')
})
```

![](http://g.recordit.co/zjxphc3t4C.gif)

The fix would require some similar logic as was written in https://github.com/cypress-io/cypress/pull/5591/files including tests. cc @sainthkh

**Comment by sainthkh** [comment]
@jennifer-shehane 

This requires a little more complicated matrix calculation. I'm thinking about the edge cases and solution.
