### ISSUE TITLE
Workspace recommended VS code extensions

### ISSUE THREAD

**Issue by andrew-codes** [cypress-io/cypress#5689]
Provide developers a list of recommended VS Code extensions when developing Cypress. These recommendations are specific to the Cypress workspace/repo.

I have included a starting point for recommendations. These can be accessed via the extensions pane and searching for `@recommended`.

![image screenshot of searching for recommended extensions](https://user-images.githubusercontent.com/1578436/68786749-52ff6700-060e-11ea-83e6-68121f31b118.png)

**Comment by flotwig** [comment]
* [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) is great for tracking your progress when tracing through CoffeeScript that doesn't have intellisense
* [CoffeeScript Checker/Previewer](https://marketplace.visualstudio.com/items?itemName=jhessin.coffee2preview) gives you a "Coffeescript check" command that can be used to quickly see what a selected block of CS will transpile to in JS
* [coffeescript-support](https://marketplace.visualstudio.com/items?itemName=yorkxin.coffeescript-support) provides some basic language support for coffeescript
* [Terminals Manager](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) is highly recommended, by using "Terminals: Open Single..." you can quickly spawn most common commands, like running an e2e test for example

Not Cypress-specific but also great:
* [GitHub linker](https://marketplace.visualstudio.com/items?itemName=gimenete.github-linker) - select a block of code and copy a permalink that will autoembed the code, like this: https://github.com/cypress-io/cypress/blob/b4df51b4c67e494e8f3951233f5b1848c59c6c6b/packages/server/lib/browsers/chrome.coffee#L243-L250

**Comment by sainthkh** [comment]
@jennifer-shehane @flotwig It seems that this issue can be closed, right?

**Comment by flotwig** [comment]
Yes, thank you @sainthkh
