### ISSUE TITLE
how to assert AWS verification Code ?

### ISSUE THREAD

**Issue by cullsin** [cypress-io/cypress#5697]
Hi,

In my application, when user signed-up, we are sending verification code to the end user from amazon aws. I can test the negative flow. Can you please suggest me an approach how to test this success flow ?

Thanks,
Raja K

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
