### ISSUE TITLE
3.5.0-3.6.1 regression - cy.type() may skip a character on a autofocussing textbox

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/cypress#5703]
### Current behavior:

When typing '10' into a textbox with text selected and that text is '1', the textbox doesn't lose the selection upon typing the first '1' so when the '0' is typed the textbox ends up with '0' but if a user types it, we get '10'

### Steps to reproduce: (app code and test code)

https://github.com/cypress-io/cypress-test-tiny/pull/54

### Versions

3.6.1, windows

@Bkucera I guess this is a regression from your type() changes.

**Comment by jennifer-shehane** [comment]
I have verified this fails in an unexpected ways in both 3.5.0 and 3.6.1 (in different ways).

`index.html`

```html
<html>
<body>
  <input type="text" value="1" />
</body>
<script>
  const el = document.getElementsByTagName('input')[0];
  el.addEventListener('focus', (ev) => ev.target.select());
</script>
</html>
```

`spec.js`

```js
it('works', () => {
  cy.visit(`index.html`);
  cy.get('input').type('10');
  cy.get('input').should('have.value', '10');
})
```

## 3.4.1

Types in `10` as expected

![](http://g.recordit.co/LVHawyzTnb.gif)

## 3.5.0

Types in `110`

![](http://g.recordit.co/KecutXUby1.gif)

## 3.6.1

Types in `1` which is then replaced with `0`.

![](http://g.recordit.co/UT4smOKopY.gif)

**Comment by jennifer-shehane** [comment]
There is a PR open to fix this here: https://github.com/cypress-io/cypress/pull/5854 Our initial attempt at a fix broke some other behavior, so this is the latest.
