### ISSUE TITLE
Setting CYPRESS_value returns undefined when read from Cypress.env('value') if the value is used as a configuration value within Cypress, like CYPRESS_CONFIG_FILE or CYPRESS_PORT

### ISSUE THREAD

**Issue by cdanielsen** [cypress-io/cypress#5706]
### Current behavior:

Certain environment variable names appear to be reserved / produce unexpected behavior when used. As of v3.5.0 when the `--configFile` flag was introduced, it looks like setting `CONFIG_FILE` as an environment variable via the [`CYPRESS_` prefixing method](https://docs.cypress.io/guides/guides/environment-variables.html#Option-3-CYPRESS) does not work.

I happened to be using the more common SCREAMING_SNAKE_CASE convention to set a `CONFIG_FILE` environment variable for an older project ( using v3.1.3) that was otherwise using [this example](https://docs.cypress.io/api/plugins/configuration-api.html#Promises) pretty much verbatim for setting configuration values by file, and it no longer works now that I've upgraded to v3.6.1 because `Cypress.env('CONFIG_FILE')` returns `undefined`.

### Desired behavior:

Would be nice if any reserved variable names were at least documented in the[ Environment Variables](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) section so that users do not inadvertently use them. 

### Steps to reproduce: (app code and test code)

See https://github.com/cdanielsen/cypress-test-tiny/tree/bug/undocmented-env-vars-appear-to-be-reserved

The following scripts can be used to demonstrate the behavior on different OS environments:
`npm run cypress:run:windows`
`npm run cypress:run:nix`

### Versions

Cypress: 3.6.1
Windows 10

**Comment by jennifer-shehane** [comment]
The only OS level reserved environment variable is `CYPRESS_ENV`, which throws an error when set, and `CYPRESS_KONFIG_ENV` so I suspect something else is going on here.

**Comment by jennifer-shehane** [comment]
Ran your test code. You are not setting `CONFIG_FILE` as described in the issue, you are setting `CYPRESS_CONFIG_FILE` - anything with a `CYPRESS` prefix should set Cypress internal environment variables (not OS level environment variables) as documented here: https://on.cypress.io/environment-variables#Option-3-CYPRESS

I don't know why this is not settable and requires more investigation.

**Comment by cdanielsen** [comment]
Appreciate the quick response; updated my description of the issue for clarity. Interestingly, using the `--env` command line flag to set this variable works fine: pushed an additional commit to that branch that demonstrates that [here](https://github.com/cdanielsen/cypress-test-tiny/commit/e4cfbe0b5717dde8cd4b5ed9e963f0c79feea8e1)

**Comment by bahmutov** [comment]
yeah, I spent sometime today after copying an example text and trying to see it in action debugging this. Turns out one of the variables was `port` which is special config value in our system, and is removed form the `env` object.
