### ISSUE TITLE
New updates banner covers the last test in the list

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress#5708]
### Current behavior:

On an old installation of Cypress, the "New updates are available" banner covers the last tests in the list:
![Screenshot from 2019-11-14 18-06-27](https://user-images.githubusercontent.com/1740517/68903713-f5504500-0709-11ea-9c79-f65485189bec.png)

### Desired behavior:

I know the developers would like all users to upgrade, but I'd like to see all my tests in the list, too.

### Steps to reproduce: (app code and test code)

1. Install an old version of Cypress. (Example: 3.4.1)
2. npx cypress open
3. Create multiple .spec.js test files until you need to scroll in the Cypress window.  Note the last test alphabetically that should appear in the list.

### Versions

3.4.1
Ubuntu 16.04
Chrome 78

**Comment by jevors** [comment]
Just run into that one as well. As long as you use directories you have a work around. Other work around is to use the search bar at the top to search for the specific test.

**Comment by clarmso** [comment]
Agree. Another workaround is to upgrade, but having a file just "disappeared" on me looks like bad user experience.

I should upgrade Cypress soon!

**Comment by jennifer-shehane** [comment]
We cannot fix old versions of Cypress that were released. It is a completely packaged application, so any bugs that are released in a version will be present in that version forever. 

You will need to update to get the bug fixes.
