### ISSUE TITLE
scrolling elements should factor in position: sticky and multiple covered elements

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#571]
- Cypress Version: 0.19.4
- Browser Version:

### Is this a Feature or Bug?
Bug

Originally seen here: #565

### Current behavior:
- Cypress will not scroll beyond a single fixed position element when its covering up the desired element
- Cypress does not factor in `position: sticky` for elements covering up the desired element

### Desired behavior:
- Factor in multiple elements
- Factor in `position: sticky` elements

### Additional Info (images, stack traces, etc)

Cypress scrolls past the fixed header but not beyond that. This is the problem:
![screen shot 2017-07-21 at 7 29 36 pm](https://user-images.githubusercontent.com/1268976/28485906-065ac4ec-6e4b-11e7-8625-8a7a10b2630c.png)

This is what it should do:
![screen shot 2017-07-21 at 7 29 47 pm](https://user-images.githubusercontent.com/1268976/28485908-0831b05a-6e4b-11e7-9689-2fa5f729025c.png)

**Comment by brian-mann** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Cypress will now scroll past multiple elements that cover up the desired element, and now factors in `position: sticky`.

**Comment by kamituel** [comment]
Awesome, thanks for looking at that quickly. Will it be released in `0.20.0` or later?

**Comment by jennifer-shehane** [comment]
@kamituel This will be released in 0.20.0.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
