### ISSUE TITLE
cy.request with failOnStatusCode: false not working

### ISSUE THREAD

**Issue by bartzaalberg** [cypress-io/cypress#5719]
Running the call `cy.request({url: '/abcde', failOnStatusCode: false});` returns the following error for me.
```
CypressError: cy.request() failed on:

https://mysite.com/abcde

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------
```
I actually want the 404 to appear and check do some checks there.
I am currently on the last version of Cypress(3.6.1) so that's not the problem.

**Comment by Hatamleh** [comment]
I have the same problem :(

**Comment by rajkon** [comment]
I have seen it works in one of the tests and not on another. 

`cy.request({
            method: options.method,
            url: options.url,
            failOnStatusCode: options.failOnStatusCode,
            headers: options.headers,
            body: JSON.stringify(options.body)
        }).then((response) => {
            cy.log("response.body: " + JSON.stringify(response.body));
            
        });`

**Comment by bartzaalberg** [comment]
So you can reproduce the issue? Should I reopen?

**Comment by bartzaalberg** [comment]
Somehow error doesn't occur anymore. Closing the issue.

**Comment by yunusHW** [comment]
I see the same error in my test case. I am not able to verify the error messages if status code is not 200.

 cy.request('/newpatron/'+newPatronId, {failOnStatusCode: false}).then((response) => {
      console.log(response);
      expect(response.status).to.eq(500)
      expect(response.body.name).to.eql('Error')
      expect(response.body.message).to.eql("Patron Already Exists.")
})

**Comment by gissavem** [comment]
I still seem to have the same issue

`        cy.request(
            'POST',
            'http://localhost:13337/api/order', {failOnStatusCode: false},
        ).then(response =>{
            expect(response.status).to.eq(400)
            expect(response.body).to.eq("Not enough of ingredients in stock: ham, mushrooms, cheese, tomatosauce")
        })  `

**Comment by jennifer-shehane** [comment]
@yunusHW @gissavem `cy.request()` does not accept 2, 3, args with an options argument as the last arg as you have written. If you need to pass options, you need to pass a single options argument with all arguments including `url`, `method` (if necessary) and `failOnStatusCode`. Please check the docs: https://on.cypress.io/requesttax

<img width="322" alt="Screen Shot 2021-01-22 at 12 05 28 PM" src="https://user-images.githubusercontent.com/1271364/105451018-2632ef00-5caa-11eb-84d7-0f99324ad112.png">

```js
it('test 500', () => {
  cy.request({
    url: 'https://httpstat.us/500', 
    failOnStatusCode: false 
  }).then((response) => {
    expect(response.status).to.eq(500)
    expect(response.body).to.eql("500 Internal Server Error")
  })
})
```

**Comment by RealLau** [comment]
@jennifer-shehane 
I tried your sample code, still not working for me. 
my test code:
```javascript
/// <reference types="cypress" />

context('Aliasing', () => {
    beforeEach(() => {
    })

    it('test 500', () => {
        cy.request({
            method: "GET",
            url: "http://127.0.0.1:5001" + "/hostui",
            failOnStatusCode: false
        }).then((response) => {
            expect(response.status).to.eq(500)
            expect(response.body).to.eq("500 Internal Server Error")
        })
    })
})

```

and the output is:
```shell

request
GET --- http://127.0.0.1:5001/hostui
CypressError
cy.request() failed trying to load:

http://127.0.0.1:5001/hostui

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:5001

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://127.0.0.1:5001/hostui

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computerLearn more
cypress/integration/custom/HOST.js:8:12
   6 | 
   7 |     it('test 500', () => {
>  8 |         cy.request({
     |            ^
   9 |             method: "GET",
  10 |             url: "http://127.0.0.1:5001" + "/hostui",
  11 |             failOnStatusCode: false

```
pls help:) Thanks in advance.

**Comment by drumslave-git** [comment]
It was working for me, but suddenly not anymore (just ran same test again after a week).
Cypress: 8.3.1

**Comment by drumslave-git** [comment]
It was working for me, but suddenly not anymore (just ran same test again after a week).
Cypress: 8.4.1

**Comment by begoniaSaa** [comment]
Hello, I am having the issue using the below:

 cy.request({
      method: 'PUT',
      url: `http://${Cypress.env('baseUrl')}/url`,
      failedOnStatusCode: false,
      headers: {Authorization: authorizationValue},
      body: {"name": "random"}
    }).then((response) => {
      expect(response.status).to.eq(404)
    })

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not 2xx or 3xx.

If you do not want status codes to cause failures pass the option: failOnStatusCode: false

cypress version 7.3.0

**Comment by MagAPI1** [comment]
**I'm getting the same error message and still couldn't figure out how to fix it.**


`/// <reference types="Cypress" />


describe('Post user request', () => {

  let accessToken = 'a72fc76d1587423bb47d248b27229b9dc7e66473470b1461bc1fd0b40fc41e16'

  it('create user test', () => {
      cy.request({
          method: 'POST',
          url: 'https://gorest.co.in/public/v2/users',
          headers: {
              'Authorization': 'Bearer' + accessToken
          },
          body: {
              "name": "Test Automation",
              "gender": "male",
              "email": "req112ue2312st@gmail.com",
              "status": "active"
          }
      }).then((res)=>{
        //.isEqual
        

          expect(res.body.data).to.eq(201)
         
          expect(res.body.data).has.property('email','req112ue23st@gmail.com')
          expect(res.body.data).has.property('name','Test Automation')
          expect(res.body.data).has.property('gender','male')
          expect(res.body.data).has.property('status','active')
      })
  });
})

`

**### Error Message:** 

requestPOST 401 https://gorest.co.in/public/v2/users
CypressError
cy.request() failed on:

https://gorest.co.in/public/v2/users

The response we received from your web server was:

> 401: Unauthorized

This was considered a failure because the status code was not 2xx or 3xx.

If you do not want status codes to cause failures pass the option: failOnStatusCode: false

**Comment by tymocoder** [comment]
The solution is:
```
cy.request({url: '/yourUrl', failOnStatusCode: false}).should((response) => {
expect(response.status).to.eq(404);
});
```

just change 404 for your needed value

**Comment by troy1lk** [comment]
> **I'm getting the same error message and still couldn't figure out how to fix it.**
> 
> `///
> 
> describe('Post user request', () => {
> 
> let accessToken = 'a72fc76d1587423bb47d248b27229b9dc7e66473470b1461bc1fd0b40fc41e16'
> 
> it('create user test', () => { cy.request({ method: 'POST', url: 'https://gorest.co.in/public/v2/users', headers: { 'Authorization': 'Bearer' + accessToken }, body: { "name": "Test Automation", "gender": "male", "email": "[req112ue2312st@gmail.com](mailto:req112ue2312st@gmail.com)", "status": "active" } }).then((res)=>{ //.isEqual
> 
> ```
>       expect(res.body.data).to.eq(201)
>      
>       expect(res.body.data).has.property('email','req112ue23st@gmail.com')
>       expect(res.body.data).has.property('name','Test Automation')
>       expect(res.body.data).has.property('gender','male')
>       expect(res.body.data).has.property('status','active')
>   })
> ```
> 
> }); })
> 
> `
> 
> **### Error Message:**
> 
> requestPOST 401 https://gorest.co.in/public/v2/users CypressError cy.request() failed on:
> 
> https://gorest.co.in/public/v2/users
> 
> The response we received from your web server was:
> 
> > 401: Unauthorized
> 
> This was considered a failure because the status code was not 2xx or 3xx.
> 
> If you do not want status codes to cause failures pass the option: failOnStatusCode: false

To fix your issue:
headers: { 'Authorization':  accessToken },
