### ISSUE TITLE
Internal timers are inaccurate / busted due to Electron

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#572]
- Cypress Version: 0.19.4

### Is this a Feature or Bug?
Bug

### Current behavior:
Timers when running in electron are busted due to https://github.com/electron/electron/issues/7079

This manifests itself in several ways:
- oftentimes during a hard refresh the Cypress UI will hang / block for several seconds while the underlying socket connection is being made
- tests will not re-run on file change due to timer polling problems
- using options like `delay` with `cy.route` can provide inaccurate delays which can lead to failing tests

### Desired behavior:
Timers should "just work correctly"

**Comment by brian-mann** [comment]
This is likely related to #334.

**Comment by brian-mann** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.

**Comment by TimNZ** [comment]
@brian-mann What's the fix?
I'm experiencing setTimeout() throttling as well.

**Comment by brian-mann** [comment]
You spawn a forked process and use ipc with the child process (which will be spawned in node, not electron) and not have busted timers.

You then override all of the global timers (first thing in your code) and create a lightweight queuing mechanism that reimplements `setTimeout`, `clearTimeout`, `setInterval`, and `clearInterval`. 

We disable node-integration so this was only a problem outside the renderer process for us. It sounds more complicated than it really was to setup.

For the moment I'll post a gist on the electron issue with the code I wrote. 

I'll be happy to point you to our code so you can see how it's implemented once we open source it in the next week or so.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
