### ISSUE TITLE
Random tests get stuck using headless run.

### ISSUE THREAD

**Issue by Reemet** [cypress-io/cypress#5720]
1. Random tests get stuck and hang until the process is killed in the dashboard ( 90 min ). I've been stuck on this issue for days now, and can't figure out what's wrong, because it happens at random times, usually 3rd or 5th test-CASE hangs and it happens every 2 -3 test-RUN.

 At first, I thought, that it might be caused because I'm using cy.visit() twice in one test.spec.js file, but the super-domain is always the same, just the endpoint is different
 Now I have a test, where I switch page language using a dropdown menu. every time when I switch, the page reloads, runs fine when I run tests through the GUI. Hangs with " cypress run" ( headless electron ).
![stuck](https://user-images.githubusercontent.com/14996247/69039703-1d36f580-09f5-11ea-901d-b0d6064890f0.JPG)

**Comment by Reemet** [comment]
![stuckagain](https://user-images.githubusercontent.com/14996247/69042333-b0722a00-09f9-11ea-858e-3ea3689fe88e.JPG)

**Comment by Reemet** [comment]
![agayyybn](https://user-images.githubusercontent.com/14996247/69050119-06e76480-0a0a-11ea-8e82-c4a7ed633930.JPG)
![again](https://user-images.githubusercontent.com/14996247/69050125-08b12800-0a0a-11ea-8abd-41a327a8defd.JPG)

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
