### ISSUE TITLE
Allow clicking to set the caret position in ContentEditable components.

### ISSUE THREAD

**Issue by Tohaker** [cypress-io/cypress#5721]
### Current behavior:

Clicking anywhere on a `contenteditable` box (such as `input`) always places the caret at the end of the word.

### Desired behavior:

We should be able to choose where the caret is placed when clicking, such as at the start, or 3 characters in, for instance.

### Steps to reproduce: (app code and test code)

Same as this issue: https://github.com/cypress-io/cypress/issues/2857

### Versions

Cypress: 3.3.1
OS: MacOS 10.15 Catalina
React: 16.10.2
Browser: Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Opened from @Bkucera comment suggesting this could be an option added to `.type()` https://github.com/cypress-io/cypress/issues/2857#issuecomment-554425404

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.
