### ISSUE TITLE
Wait for multiple elements to disappear

### ISSUE THREAD

**Issue by MacGyver27** [cypress-io/cypress#5725]
We have an info page consisting of multiple cards where each card has its own spinning loader.. I want to be able to proceed once all cards are loaded -> no loader is visible..

So my question is if cypress applies `.should()` logic to all elements from the array the `cy.get('loader')` returns..

Expected behaviour would be to wait until all elements disappear but this doesnt seem to be the case with the current 3.5.0 version.. Maybe it can be used just with single element but how would I then check such a case where I need to wait for multiple elements to be gone?

Thanks

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

If you believe this is a bug in 3.5.0 - provide a fully reproducible example of the bug in question and we will reopen.
