### ISSUE TITLE
Cypress failing to Parse cookie in Chrome Browser

### ISSUE THREAD

**Issue by vidhyaSoundararajan** [cypress-io/cypress#5727]
Hi all,  Im trying to bypass multifactor Authentication and attaching the code below. I m getting the error "Failed to parse or set cookie "sid"" in chrome browser.
Please let me any workaround for this issue.

```js
cy.request('POST', 'https://cfahome.oktapreview.com/api/v1/sessions', {
        "sessionToken": sessionToken
      })
      .then((response) => {
        console.log(response.body);
        var options = {};
        options.domain = '.cfahome.oktapreview.com';
       options.log = 'true';
        options.secure= true;
      //cy.clearCookies()
    //  cy.clearCookie('sid')
        cy.setCookie('sid', response.body.id,options);
      })
    })
    cy.visit(applicationURL)
```

**Comment by flotwig** [comment]
@vidhyaSoundararajan Could you share a screenshot of the error you get?

What is the value of `response.body.id`?

**Comment by vidhyaSoundararajan** [comment]
![Screen Shot 2019-11-19 at 9 57 54 AM](https://user-images.githubusercontent.com/34387183/69158036-ccd29d00-0ab3-11ea-9a01-bee37762d890.png)

**Comment by flotwig** [comment]
Thanks for the additional info @vidhyaSoundararajan, I'll look into this.

**Comment by vidhyaSoundararajan** [comment]
Thanks!

**Comment by flotwig** [comment]
@vidhyaSoundararajan I tried this locally, and I don't get an error. Are you on Cypress 3.6.1?

Here's what I ran since I don't have the `sessionToken` from your snippet:

```js
cy.request('POST', 'https://example.com', {})
.then((response) => {
  console.log(response.body);
  var options = {};
  options.domain = '.cfahome.oktapreview.com';
  options.log = 'true';
  options.secure= true;
//cy.clearCookies()
//  cy.clearCookie('sid')
  cy.setCookie('sid', 'foo' ,options);
})
```

**Comment by flotwig** [comment]
@vidhyaSoundararajan Are you still having the issue on Cypress 3.7.0?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
