### ISSUE TITLE
DeprecationWarning in Node 12: setting the TLS ServerName to an IP address

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#5729]
### Current behavior:

There is a DeprecationWarning printing during `cypress run` that someone reported seeing.

![image](https://user-images.githubusercontent.com/1271364/69093427-69496080-0a1c-11ea-8402-5261c97baf36.png)

https://nodejs.org/api/deprecations.html#deprecations_dep0123_setting_the_tls_servername_to_an_ip_address

### Desired behavior:

Handle deprecations introduced in switching to Node 12.

### Versions

3.6.1

**Comment by flotwig** [comment]
@jennifer-shehane Was the user `cy.visit`ing an IP address?

**Comment by flotwig** [comment]
I'm still seeing this error when running the `https://127.0.0.1` test case in `2_cookies_spec` e2e test

**Comment by nmschulte** [comment]
I see this warning when visiting an IP address in version 3.7.0.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

This warning no longer displays when visiting an IP address in our current version.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
