### ISSUE TITLE
Lint error introduced in #5714

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#5734]
### Current behavior:

CI lint test fails because of a trailing whitespace. 

### Desired behavior:

CI passes.

### Steps to reproduce: (app code and test code)

Checkout develop branch and `npm run lint-all`.

### Versions

develop branch.

**Comment by sainthkh** [comment]
Somehow it passes without fail in CI. But I believe it's better to fix it.

**Comment by jennifer-shehane** [comment]
Released in [3.7.0](https://on.cypress.io/changelog#3-7-0)
