### ISSUE TITLE
Cypress shows which the cookie is set but it doesn't 

### ISSUE THREAD

**Issue by Skhoshhal** [cypress-io/cypress#5737]
### Current behavior:

I want to set cookie in local domain `https://app.travel-test.me.lan/` , and it shows which the cookies are setted, but it deosn't. If I set the same cookie for my `localhost:3000`, it works fine.

<img width="972" alt="Screen Shot 2019-11-19 at 11 09 13" src="https://user-images.githubusercontent.com/20300562/69137788-b7fb0700-0abd-11ea-9a16-f867544f110e.png">

### Desired behavior:

After setting cookie the cookie should be visible

### Steps to reproduce: (app code and test code)

here is my code how to set cookie
```js

        cy.setCookie('AIDU', 'DEYZZk');

        cy.setCookie('ascc', 'rerun%3A2');

        cy.setCookie('token', token);

        cy.getCookie('token').should('have.property', 'value', token);

        cy.visit(`https://app.travel-test.me.lan/${id}`);

```

### Versions
Node 12.13.0
Cypress 3.6.1
Chrom 78
electron 73

I use macOS high Sierra 10.13.6
Node 12.13.0
Cypress 3.6.1

this image is from local host, which the cookie will set fine.

<img width="959" alt="Screen Shot 2019-11-19 at 11 24 32" src="https://user-images.githubusercontent.com/20300562/69138753-84b97780-0abf-11ea-9c6b-d55955bfc0a1.png">

**Comment by flotwig** [comment]
@Skhoshhal If you do not specify a `domain` parameter for `cy.setCookie`, it will set it on the current domain.

The test that you shared seems to not use a `baseUrl`, so I think you might just need to change your `baseUrl` in `cypress.json` to `https://app.travel-test.me.lan/` when you are running in prod.

--

This should also work, since it explicitly sets the `domain`:

```
cy.setCookie('AIDU', 'DEYZZk', { domain: 'app.travel-test.me.lan' });

cy.setCookie('ascc', 'rerun%3A2', { domain: 'app.travel-test.me.lan' });

cy.setCookie('token', token, { domain: 'app.travel-test.me.lan' });

cy.visit(`https://app.travel-test.me.lan/${id}`);

cy.getCookie('token').should('have.property', 'value', token);
```

**Comment by Skhoshhal** [comment]
@flotwig Thanks it helped me.

**Comment by flotwig** [comment]
@Skhoshhal glad you were able to get it to work. closing this for now.
