### ISSUE TITLE
After upgrade to version 3.6.1 tests start failig 

### ISSUE THREAD

**Issue by mschaaf** [cypress-io/cypress#5742]

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏

**Comment by mschaaf** [comment]
I don't know what happened but I thought I opened only one issue this is it https://github.com/cypress-io/cypress/issues/5743
