### ISSUE TITLE
cypress open - new projectId creation not respecting --config-file

### ISSUE THREAD

**Issue by oak-wildwood** [cypress-io/cypress#5747]
### Current behavior:

Creating a new projectId using `cypress open` with a _**different config file**_ results in the new projectId being placed into the `cypress.json` file.

### Desired behavior:

I expect Cypress to honor the value passed to the `--config-file` option and add the new projectId to the specified configuration file and not the original `cypress.json`

### Steps to reproduce: (app code and test code)

1. Clone this repo: `git@github.com:oak-wildwood/cypress-test-tiny.git`
2. Run `npm i`
3. Run `npx cypress open --config-file cypress-other.json`
5. Sign in and click **Setup project to record**
6. On the modal click **Set up project** to complete
7. See the changes to the wrong file

![image](https://user-images.githubusercontent.com/5605406/69187806-4638b280-0ae9-11ea-8428-61667cfc77e9.png)

### Versions
Cypress 3.6.1, MacOS Catalina, Chrome 78

**Comment by jennifer-shehane** [comment]
The UI also doesn't seem to react to a new project being created. I have to kill cypress and restart to see the changes. I think this may be due to this option, unless there's some other variable involved.

![](http://g.recordit.co/MX15wB4jOd.gif)
