### ISSUE TITLE
cypress.env.json is not respected

### ISSUE THREAD

**Issue by itsthatguy** [cypress-io/cypress#575]
- Operating System: macOS 10.12.5
- Cypress Version: 0.19.4
- Browser Version: Electron

### Is this a Feature or Bug?
Bug

### Current behavior:
Values set in `cypress.env.json` do not override values from `cypress.json`

### Desired behavior:
Values set in `cypress.env.json` override values from `cypress.json`

### How to reproduce:

Run cypress in either cli, or the desktop app with the test code below

#### Test code:

```js
// cypress.json

{
  "environmentVariables": {
    "APPLES": 1
  }
}
```

```js
// cypress.local.json

{
  "environmentVariables": {
    "APPLES": 3
  }
}
```

```js
// integration/simple_spec.js

const apples = Cypress.env('APPLES');

describe('My First Test', function () {
  it('Does not do much!', function () {
    expect(apples).to.equal(3);
  });
});

```

### Additional Info (images, stack traces, etc)

![image](https://user-images.githubusercontent.com/1118006/28681292-01692f5c-72c7-11e7-86be-dbada71370d4.png)

![image](https://user-images.githubusercontent.com/1118006/28681296-0775d3b4-72c7-11e7-8455-f13e43fe46ca.png)

**Comment by brian-mann** [comment]
The problem is that you're not writing your env vars correctly.

https://docs.cypress.io/guides/guides/environment-variables.html#Option-1-cypress-json

You're using a key called `environmentVariables` and its really `env`.

And you're using `cypress.local.env` which is not a file Cypress looks for - it looks for `cypress.env.json`.

**Comment by itsthatguy** [comment]
the cypress.local.env was a typo, I corrected it

**Comment by itsthatguy** [comment]
the behavior is the same using `env` as the key

**Comment by brian-mann** [comment]
`cypress.env.json` does not use a nested env key - you just write them straight up at the root level.

**Comment by itsthatguy** [comment]
ohhhh, that's not very clear in the documentation.

**Comment by itsthatguy** [comment]
that makes me wonder, how is it getting a value for apples at all?

**Comment by brian-mann** [comment]
Internally cypress actually munges `env` into a key called `environmentVariables` which you just happened to use in the `cypress.json`. So basically its working by chance. If you change the key in `cypress.json` to anything else, it won't work.

Also you can see which env vars are set (and from where) in the UI itself - which is much faster to iterate than actually running a spec.

https://docs.cypress.io/guides/references/configuration.html#Resolved-Configuration

**Comment by brian-mann** [comment]
In the resolved configuration we also call this key `environmentVariables` which is a bit confusing since the actual property is `env`.
