### ISSUE TITLE
Wrong error message shown when attempting to run a spec in a browser that wasn't launched by Cypress

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#5757]
### Current behavior:

Opening a spec to run in a browser that hasn't been launched by Cypress shows the wrong error message. It shows a cross-origin error in the reporter and 'Whoops, there is no test to run' in the AUT.

![Screen Shot 2019-11-20 at 3 15 27 PM](https://user-images.githubusercontent.com/1157043/69274647-cb36d100-0ba8-11ea-882c-9ecacc772183.png)

### Desired behavior:

In this case, it's supposed to show a message to the effect of 'This browser was not launched through Cypress', making it clear what's going on.

### Steps to reproduce: (app code and test code)

1. Run a spec in Cypress
2. Copy the URL from the browser that Cypress launches and paste it into a normal browser

### Versions

Cypress: 3.6.1
Cypress Browser: N/A
User Browser: Chrome 78
System: MacOS Mojave 10.14.6

**Comment by jennifer-shehane** [comment]
I'm not able to replicate this in Cypress 4.8.0. This seems to have been fixed somewhere between 3.6.1 and 4.8.0.
