### ISSUE TITLE
cy.click() does not work properly

### ISSUE THREAD

**Issue by LikWid-23** [cypress-io/cypress#5761]
### Current behavior:

From version 3.5.0 cypress does not click correctly on elements on the page in CI. Workaround is to pass in {force:true} as an argument, but that is not what I expect how it should work.

Perhaps relates to this bug https://github.com/cypress-io/cypress/issues/3388, which was actually solved in version 3.2.0 

### Desired behavior:

The same test passed in cypress version 3.4.1. 
Click on element should should trigger the javascript function

### Steps to reproduce: (app code and test code)

**Screenshot (v3.4.1)**
![cy_click_3_4_1](https://user-images.githubusercontent.com/56432138/69321975-53b67f80-0c44-11ea-83d6-bc4ae0cf1435.PNG)

**Screenshot (v3.6.1)**
![cy_click_3_6_1](https://user-images.githubusercontent.com/56432138/69322128-96785780-0c44-11ea-8c25-2ece537be806.PNG)

**AppCode** 
![frontend](https://user-images.githubusercontent.com/56432138/69322259-d5a6a880-0c44-11ea-8233-4fd49736ba85.PNG)

**Testcode**
```js
Cypress.Commands.add('setFavoriteMarket',(zipcode)=>{
  if(zipcode != ""){
    cy.contains('Markt suchen')
    .click()
    .get('input#marktsearch_section').type(zipcode)
    .get('#marktsearch_button').click()
    .get('.jspPane > .result:nth-child(1) .details > .info a')
    **.click()**
    .getCookie('EDEKA_B2C').should('exist').then((c) => {
      return(JSON.parse(JSON.parse(c.value)));
    }).its('marketID').should('be.not.empty',{ timeout: 10000 })
    .get('.o-offers-offer-categories__store-information-item:nth-child(2) p').as('storeAddress')
  }
});>
```

### Versions

3.5.0 and higher

**Comment by priyajeet** [comment]
Having the same issue starting with 3.5.0

**Comment by MarioPuzzo** [comment]
does param {force:true} help? or not in this case?

**Comment by LikWid-23** [comment]
Yes, I already mentioned that in the current behavior part of the bug description

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. We need the HTML to run the test code against, so that we can run the error ourselves. 

This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Also please try updating to the [current version of Cypress](https://on.cypress.io/changelog) as we've fixed several bugs. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by Hultner** [comment]
@jennifer-shehane I also experience this problem, tried with `{force: true}`, sometimes works if a put long enough of a wait before.

**Comment by ShamiliPrabu** [comment]
Yes, even force sometimes fails could someone help

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) or comment with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by srcenteredge** [comment]
Having same issue with cy.click() even **{ force: true }** does not help

**Comment by jennifer-shehane** [comment]
@srcenteredge Please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a reproducible example. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by sandeep110690** [comment]
Hello, I have an element in Web Page, Where using Cypress i am able to click action, but unable to open the Pop-up.
![image](https://user-images.githubusercontent.com/74452707/126459421-7802a80f-f50a-4658-abdf-1d70c2df21d0.png)

**Comment by sandeep110690** [comment]
Can anyone suggest what needs to be done to open the Pop-up window when clicked on this Orange Button.

**Comment by chandrakumar1988** [comment]
I am not able to Click the button even though i have enter correct CSS Selector .
![image](https://user-images.githubusercontent.com/47958062/190375729-77a0920b-75e3-4698-9d73-ea05068a159c.png)
![image](https://user-images.githubusercontent.com/47958062/190376410-3cc5fc70-fb2d-4aa8-9ef9-ebbe236579dd.png)
I have used both command - Its detecting the element but not click the button .
cy.get('#submitButton').click()
cy.get('.Submitbtn').contains('Log In').click()
