### ISSUE TITLE
Asserting something should('not.have.value') / should('not.be.visible') logs element as "undefined"

### ISSUE THREAD

**Issue by davidzambrana** [cypress-io/cypress#5763]
### Current behavior:

What I try to check in my test is that a given field should not have an empty value as the following code shows.

```js
cy.get('[data-test=ext-referral-form-btn]').should('be.visible').click();
cy.get('[data-test=ext-referral-formSuccess-code]').should('not.have.value','');
```

Such assertion is set right after a click where I submit form data and wait for `ext-referral-formSuccess-code` in the next view (after loading) to have an empty value.

The test passes but in the log I see the following:

![notempty](https://user-images.githubusercontent.com/36962817/69353355-aad94600-0c7e-11ea-827c-b0d9d5e683f5.png)

The assertion seems to go well but the cypress logger doesn't work as expected, logging the field names as `undefined`. Actually, if I wait some ms after the `click` just to give some time to Cypress to see the fields I see the following:

![successfields](https://user-images.githubusercontent.com/36962817/69353713-33f07d00-0c7f-11ea-9232-4563eff409d6.png)

I also see the correct data logged if instead of asserting `should('not.have.value','')` I set `should('have.value','whatever')`.

### Desired behavior:

I expect to see the correct value of the field names I am asserting using `should('not.have.value','')` in a view that is onloading instead of `undefined`. 
It seems that when Cypress logs the data it doesn't have the value at hand, and only explicitly waiting some time it is able to read it and log it properly.

### Steps to reproduce: (app code and test code)

You can verify this behavior by setting an assertion like `cy.get('yourThing').should('not.have.value','')` right after submitting a form.

- Fill up required data
- submit the form
- assert that an element in the next view `should('not.have.value','')`
- See the Cypress log

### Versions

Cypress 3.6.1
Ubuntu Linux 18.04.3 LTS
Electron 73
Also using Cucumber pre-processor 1.16.2

**Comment by frankind** [comment]
I found this issue as well after Cypress3.4.1. 
May you try on Cypress3.4.1?
For my case, my element is not visible due to the caretDown is not expanded yet but Cypress return undefined.

If found element as "undefined" that I want to check it before "View Order Detail" is expanded or click
![image](https://user-images.githubusercontent.com/16382131/70777918-8e2eba80-1db3-11ea-8da9-d2b4d38bfff1.png)

If it is expanded, then it will show element under "View Order Detail" as below:
![image](https://user-images.githubusercontent.com/16382131/70777989-bf0eef80-1db3-11ea-8ac3-a07621b07250.png)

**Comment by jennifer-shehane** [comment]
We'll need a reproducible example provided - test code + html in order to investigate. Likely it has to do with something rerendering in the DOM at a strange time when we're trying to access the element.

**Comment by frankind** [comment]
> We'll need a reproducible example provided - test code + html in order to investigate. Likely it has to do with something rerendering in the DOM at a strange time when we're trying to access the element.

This is the code
`it('should found "xxx" element not to be visible', () => {
    cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html')
    cy.get('xxx').should('not.be.visible')
  })`
This is the result in Cypress3.4.1
![image](https://user-images.githubusercontent.com/16382131/70891516-f7176c00-2019-11ea-92ec-0896cd517d13.png)
This is the result in Cypress3.8.0
![image](https://user-images.githubusercontent.com/16382131/70891559-0696b500-201a-11ea-87ba-fb842a85205b.png)

**Comment by jennifer-shehane** [comment]
Perfect, thank you! I verified this was introduced in 3.5.0.

**Comment by davidzambrana** [comment]
Thanks for providing the example @frankind

**Comment by s0oft** [comment]
Any news on this?

**Comment by MarkConway94** [comment]
hey team, just noticed the same thing a month after upgrading to cypress version `4.0.2`.
Any news on a fix? 
I have lots of tests that are now giving false positives 😢

**Comment by jennifer-shehane** [comment]
Just adding a smaller repro and confirming that this still occurs in 4.9.0. 

```html
<html>
<body>
</body>
</html>
```

```js
it('should find "xxx" element not to be visible', () => {
  cy.visit('index.html')
  cy.get('xxx').should('not.be.visible')
})
```

### 3.4.1

![Screen Shot 2020-07-09 at 12 42 53 PM](https://user-images.githubusercontent.com/1271364/87003481-bcf1ff80-c1e1-11ea-885a-e7034495e566.png)


### 3.5.0+

![Screen Shot 2020-07-09 at 12 39 52 PM](https://user-images.githubusercontent.com/1271364/87003339-73091980-c1e1-11ea-835a-0a70b2227d69.png)
