### ISSUE TITLE
Issue- Auto-login to dashboard (WSL 2)

### ISSUE THREAD

**Issue by adomyaty55foundry** [cypress-io/cypress#5764]
Issue- Auto-login to dashboard (WSL 2)

### Current behavior:

Everytime I launch my test in with verbose debug on, I see cypress throwing 'errors' not 'warning' on not being logged in dashboard. Even if I log in and then if I close my VSC remote/wsl and relaunch it tells me to relog

I believe this was working for WSL 1 architecture but upgrading to WSL 2 seems to not keep that login stuff remembered. Not sure it's because windows is spinning real HW VM that's now accessing the real linux kernal
![2019-11-21_0858](https://user-images.githubusercontent.com/54867449/69359676-dee04700-0c3d-11ea-9f2e-fa8f2d440fba.png)

### Desired behavior:

We should track internally if user is logging in from the same IP or is running cypress from CLI (User have access to system) then after login, it should keep that session

### Steps to reproduce: (app code and test code)

1. Windows 10 ( WSL 2 installed)

### Versions

WSL 2, Windows 10, Cypress 3.6.1

**Comment by jennifer-shehane** [comment]
We throw this error when the authToken is not available. I'm not sure what we can do if the way your environment is launched is resetting this session after having successfully logged in before. 

Code here: https://github.com/cypress-io/cypress/blob/issue-2869-config-changes/packages/server/lib/user.coffee#L53:L53

**Comment by adomyaty55foundry** [comment]
@jennifer-shehane Perhaps through /plugins or such I can pass my Cypress credentials within my code and when I do cypress open it uses the credential I passed and logs me in. This is a minor inconvenience but a nice to have for people who test on Windows with (WSL2) Windows Subsystem for Linux

**Comment by jennifer-shehane** [comment]
@adomyaty55foundry I'm not aware of a way that we've exposed to allow you to pass credentials through the code. I also wouldn't recommend writing login credentials in your code or passing them through the code in that way for security reasons. We don't even log any login credentials at all - it is all handled by a 3rd party.

**Comment by adomyaty55foundry** [comment]
Makes total sense, thanks @jennifer-shehane

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
