### ISSUE TITLE
`cypress run` does not log `stderr` from plugins

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#5765]
### Current behavior:

Run this existing spec that has a plugin which logs to `process.stderr`:

```
npm run cypress:run -- --project ./packages/server/test/support/fixtures/projects/system-node
npm run cypress:open -- --project ./packages/server/test/support/fixtures/projects/system-node
```

https://github.com/cypress-io/cypress/blob/99ec5c7b41dd6865dda9a597cc686b19280d6a39/packages/server/test/support/fixtures/projects/system-node/cypress/plugins/index.js#L1-L5

It will log in `cypress open`, but not `cypress run`.

### Desired behavior:

The pluginsfile should log either way.

**Comment by flotwig** [comment]
The culprit is that this code path will cause the `onStderrData` callback to always return falsey:

https://github.com/cypress-io/cypress/blob/99ec5c7b41dd6865dda9a597cc686b19280d6a39/cli/lib/exec/spawn.js#L238-L256

I believe this was a mistake, as line 252 returns false, but there is no "default case" that returns true after that.

If you add "return true", once again, output will contain Electron debug information (#4255). But we can just filter that out or not set `ELECTRON_ENABLE_LOGGING` at any point.

**Comment by santoshyadav198613** [comment]
HI @jennifer-shehane ,
I would like to take this issue.

**Comment by flotwig** [comment]
@santoshyadav198613 Feel free to pick this issue up, ping me if you have any questions. I think changing that `onStderrData` callback to `return true` will be a good starting point.

**Comment by santoshyadav198613** [comment]
Hi @flotwig ,
Are we looking for this to be logged?
![image](https://user-images.githubusercontent.com/11923975/70196886-136cfc00-1730-11ea-9272-a09f1e8911cc.png)

**Comment by santoshyadav198613** [comment]
Hi @flotwig ,
PR is open now.

**Comment by flotwig** [comment]
> Hi @flotwig ,
> Are we looking for this to be logged?
> ![image](https://user-images.githubusercontent.com/11923975/70196886-136cfc00-1730-11ea-9272-a09f1e8911cc.png)

Yep, that's great!

**Comment by santoshyadav198613** [comment]
Hi @flotwig,
Cool just need some help on Testing , mentioned the error which I am getting in PR.

**Comment by dompetqqbiz** [comment]
very cool

**Comment by justin335** [comment]
Nice

**Comment by purejgleason** [comment]
Also seems to not log std err in tests

**Comment by jennifer-shehane** [comment]
This now works. I'm not sure which version this was released in. Closing as resolved. 

@purejgleason console.logs or stderr within a test file is exectued within the browser - so will not log to stdout. Use cy.task to log any info within a test to stdout as shown here: https://on.cypress.io/api/commands/task#Usage
