### ISSUE TITLE
Multiple Reporters

### ISSUE THREAD

**Issue by amcdnl** [cypress-io/cypress#577]
### Is this a Feature or Bug?
Feature

### Requirements
Right now its possible to use a different reporter, however, if you use a reporter that does something like post to slack and doesn't output the results, the dashboard shows a blank screen. This could be solved by having the ability to use multiple reporters (im sure there is other use cases for this too).

I'd envision the configuration looking something like:

```js
{
  "projectId": "34524",
  "baseUrl": "foo.com/",
  "reporters": [
      {
          "reporter": "mocha-ci-slack-reporter",
          "options": { "channel": "notifications" }
      },
      {
          "reporter": "junit"
      }
  ]
}
```

**Comment by watermanio** [comment]
👍 
I can't use JUnit in CircleCI at the moment without this (or ugly hacks), as Circle complains there has been no output for too long and kills the process.

**Comment by dziamid** [comment]
Voting for this too. Would love to leave the default reporter for the console output and JUnit XML reporter for the ci.

**Comment by bahmutov** [comment]
@amcdnl you already can do this with `0.19.4` and I put an example in https://github.com/cypress-io/cypress-example-docker-circle#spec--xml-reports
- single junit reporter
- spec + junit reporter
(using [mocha-multi-reporters](https://github.com/stanleyhlng/mocha-multi-reporters))

**Comment by Hipska** [comment]
Can someone look into this? It seems that mocha-multi-reporters is not working fine: https://github.com/cypress-io/cypress-example-docker-circle/issues/6
