### ISSUE TITLE
Got the TypeError: Illegal invocation when getting the locator 

### ISSUE THREAD

**Issue by sangmai** [cypress-io/cypress#5774]
### Current behavior:

Cypress got the issue when getting the normal locator. It throws the exception TypeError: Illegal invocation in version 3.6.1

### Desired behavior:

Can get the locator properly 

### Versions

3.6.1

**Comment by gabbersepp** [comment]
Unfortunately my glass sphere is broken currently. I will try to buy a new one.

**Comment by jennifer-shehane** [comment]
Closing as there is not reproducible example provided. Duplicate of #6412 though likely.
