### ISSUE TITLE
TypeError: win.Event is not a constructor when entering text

### ISSUE THREAD

**Issue by ShaminKarim** [cypress-io/cypress#5778]
### Current behavior:

Whenever I try to enter text during my test run, using .type, I come across a "TypeError: win.Event is not a constructor" error.

![image](https://user-images.githubusercontent.com/54899924/69455401-5396ac80-0d36-11ea-8962-cc5f2f9e9ca2.png)

### Desired behavior:

Enter the desired text when running the script.

### Steps to reproduce: (app code and test code)

1. Create a normal Cypress test.
2. Use .type in order to have text inputted into text box.

![image](https://user-images.githubusercontent.com/54899924/69455445-6f9a4e00-0d36-11ea-8dbc-b460031833d9.png)

### Versions

Cypress 3.6.1

**Comment by rlaneve** [comment]
@ShaminKarim We had a similar issue testing one of our apps. In our case, it was our app causing the issue, as we had some old code which declared an `Event` hash globally, which trashed the browser's built-in `Event` function. We stumbled upon it once we confirmed that the out-of-the-box sample tests in Cypress had no issue with the `type()` function; the issue only existed when our app was being tested.

Might be worth checking in your app. Simple test is to load up your app in Chrome, open the Dev Tools, and use the console to spit out `window.Event`. If it's anything other than a function, you have the same problem.

(Cypress dependency on the window.Event function was, I believe, introduced in v3.5.0, via this PR: https://github.com/cypress-io/cypress/pull/4870).

**Comment by jennifer-shehane** [comment]
@rlaneve Thanks for the detailed response. This error message is less than ideal regardless of if the Application is overwriting event, but this would be helpful in recreating if that is the case. 

@ShaminKarim Could you click on the yellow error in the Command Log with DevTools open and paste of screenshot of where the stack of the error is coming from? Thanks!

**Comment by heloisam** [comment]
Hey!
I had the same problem today in v.3.8.2.
The solution was to downgrade to v.3.4.1.

Any news for the fix? @ShaminKarim

**Comment by ValentinK00** [comment]
Hi, got the same problem in versions 3.5.0 and higher. Hope you will fix this problem soon. I was reading the comment below and can attach the screenshot of errors in console, hope it'll help you.

![image](https://user-images.githubusercontent.com/45227573/83598708-3caa0000-a58c-11ea-9cc7-b9d49a9cdb1a.png)
