### ISSUE TITLE
Plugin with native dependency that is also required in project - module version conflict

### ISSUE THREAD

**Issue by danielschwartz85** [cypress-io/cypress#5785]
Hi ✋, 
Our plugin (Applitools) fails due to:

### Current behavior:

Requiring a pre-compiled package (canvas for example) from a plugin file while the package also exists as a dependency in package.json, fails cypress:

![cycy](https://user-images.githubusercontent.com/4113198/69529247-8e882280-0f78-11ea-9c7a-5f52c26e0bfb.png)

(The plugin's node module version is different from the one the project was installed on..)

### Steps to reproduce:

See simple repo:
https://github.com/danielschwartz85/Cypress-NODE_MODULE_VERSION-ISSUE

Or 

1. just install canvas package:
https://github.com/Automattic/node-canvas
```npm i canvas```
2. add ```require('canvas')``` in the plugins file.

### Versions

Cypress 3.6.1
Ubunto 18.04.3
Node 10.15.1

Tnx.

**Comment by bahmutov** [comment]
@danielschwartz85 since you use a Node module with native extension in your project, you need to run plugins file with the same Node version, which you can do thanks to `nodeVersion: system` setting, see https://on.cypress.io/configuration#Node-version and https://on.cypress.io/writing-a-plugin#Execution-context

**Comment by bahmutov** [comment]
another good example is https://github.com/bahmutov/cypress-gh-action-example

**Comment by danielschwartz85** [comment]
@bahmutov I see thanks for the fast reply, and sorry for not being more precise : 

My actual use case was slightly different (I tried to simplify for the reproduction) and that original use case might be more interesting, not sure..

So basically the plugin required "jsdom" (which just has an optional dependency of canvas) and everything works fine with just that, But when the user adds canvas to it's project only then some how we get the dependency error..(even though before the user required it it was fine and even though the plugin dependency is an optional one).

Thanks.
