### ISSUE TITLE
Cypress hangs for 5s in the "Content Download" phase since 3.3.0

### ISSUE THREAD

**Issue by lukebjerring** [cypress-io/cypress#5790]
### Current behavior:
All requests are lagging for 5s, which is during the download content phase of each request.

![image](https://user-images.githubusercontent.com/777956/69584222-aaa4b780-0faa-11ea-99ec-8ae839d17331.png)

### Desired behavior:

Not hanging for 5s.

### Steps to reproduce: (app code and test code)
Running any tests against our simple localhost server hang.

### Versions
3.2.0 does not exhibit the behaviour, all subsequent releases do.

**Comment by flotwig** [comment]
Hey @lukebjerring, thanks for reporting this. Can you try running your tests with [debug logs enabled][debug], and share those logs here? It will show some more information which we can use to get to the root of the issue.

* On Linux/macOS: `DEBUG=cypress:* cypress ...`
* On Windows: `npx cross-env DEBUG=cypress:* cypress ...`

Make sure to scrub any private data from the logs before sharing here.

[debug]: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

**Comment by lukebjerring** [comment]
https://gist.github.com/lukebjerring/b05e315d2204aed6f3aab171aa13ea82

**Comment by lukebjerring** [comment]
@flotwig - ping. This issue is forcing us to pin at 3.2.0 which is causing all sorts of flow-on problems (e.g. the spread operator isn't supported, and `cypress run --record` is erroring)

**Comment by flotwig** [comment]
Hmm, 3.3.0 contained a bunch of changes which improved network speed for most users: https://docs.cypress.io/guides/references/changelog.html#3-3-0 It's possible that it caused a regression for your specific setup.

Can you describe your environment, or better yet, share a reproducible example that I can use to replicate the issue?

**Comment by lukebjerring** [comment]
> Hmm, 3.3.0 contained a bunch of changes which improved network speed for most users 

Sounds like the culprit. We are running on MacOS (as well as Travis CI), using a local NodeJS express server. Nothing fancy, but it's all private code, so pulling out a reproducible setup would be non-trivial.

**Comment by lukebjerring** [comment]
@flotwig - I think I've diagnosed this as HTTP keep-alive not playing nicely with our development server. It's specifically POST requests that have the issue, and it looks like it's because we proxy some requests in which we're mutating some JSON (so we consume the request body's stream, but don't stream the response correctly).
Closing this since the bug is in expressjs, not Cypress.
