### ISSUE TITLE
“Cypress” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by MargaretZhao** [cypress-io/cypress#5791]
I try to open this after download and I see this message on mac.
------------------------------------------------------
“Cypress” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Firefox downloaded this file today at 1:28 PM from docs.cypress.io.

------------------------------------------------------
### Current behavior:

“Cypress” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Firefox downloaded this file today at 1:28 PM from docs.cypress.io.

### Desired behavior:

able to open and use after download 

### Steps to reproduce: (app code and test code)

1. download from here 
https://download.cypress.io/desktop

2. open after download

### Versions

firefox 68.2.0esr(64-bit)
mac os catalina 10.15

**Comment by Verdagio** [comment]
If you go to system preferences > security & Privacy it should ask you if you want to allow it to run.
 
![image](https://user-images.githubusercontent.com/15673201/69746296-d99e6300-113b-11ea-8950-7b6e62b92c90.png)

**Comment by jennifer-shehane** [comment]
Yes, this will require the workaround as described by @Verdagio for now. 

This is a notification automatically sent starting in macOS Catalina. It means that the Cypress App has not undergone the process of notarization which Apple offers - basically they scan the application and verify it contains no malicious components. 

We are currently in the process of evaluating what is required to notarize the Cypress application so that this warning will no longer appear on downloads. 

We are confident the application will pass the notarization process, but have to go through some steps to get there first: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by bahmutov** [comment]
Resources:
- general doc https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution
For CI:

Add a Notarization Step to Your Build Scripts
If you use an automated build system, you can integrate the notarization process into your existing build scripts. The altool and stapler command-line tools (included with Xcode) allow you to upload your software to the Apple notary service, and to staple the resulting ticket to your executable.

For information about how to incorporate notarization into your custom build scripts, see Customizing the Notarization Workflow.

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow

**Comment by bahmutov** [comment]
More docs https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

**Comment by bahmutov** [comment]
Hmm, electron-builder has removed `build` script https://github.com/electron-userland/electron-builder/commit/bea9db9 need to upgrade step by step. Also need latest builder for Electron 7

**Comment by bahmutov** [comment]
hmm, upgrading electron-builder has to go hand in hand with electron upgrade
```
11:40:34 AM #codeSign /Users/distiller/cypress/build/darwin/Cypress.app darwin
  • electron-builder version=21.0.2
  • loaded configuration file=/Users/distiller/cypress/electron-builder.json
  • effective config config=
                       directories:
                         output: dist
                         buildResources: build
                       mac:
                         forceCodeSigning: true
                         publish: null
                         target: zip
                       
Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
```

**Comment by bahmutov** [comment]
Testing electron-builder versions in branch electron-upgrade https://github.com/cypress-io/cypress/pull/5849

- `20.41.0` works
- `20.41.0` with hardened os setting works

**Comment by bahmutov** [comment]
working on it - seems between 20.41.0 and 20.42.0 this PR has changed the sign step https://github.com/electron-userland/electron-builder/pull/3912

**Comment by bahmutov** [comment]
`20.41.0` signs the app and Taccy shows the following

<img width="479" alt="Screen Shot 2019-12-09 at 4 12 00 PM" src="https://user-images.githubusercontent.com/2212006/70473284-b7db9f00-1a9e-11ea-9a93-fd4554089a21.png">

**Comment by bahmutov** [comment]
ughh, seems we have a weird situation:
- we use `electron-packager` to actually build the application, but we do not sign it - because `electron-packager` does not know how to extract Mac identity from env variables and put into a temporary unlocked keychain 
- newer versions of `electron-builder` that DO KNOW how to work with Mac code sign do not sign a packaged app ...

**Comment by bahmutov** [comment]
Trying to use `electron-builder` to pack and build our app
```
$ as-a codesign ./node_modules/.bin/electron-builder --publish never --c.electronVersion=7.1.2 --c.directories.app=dist/darwin --c.directories.output=build/darwin --c.npmRebuild=false --c.electronCompile=false --c.electronDist=packages/electron/node_modules/electron/dist/
```

Right now failing with a weird error
```
 • packaging       platform=darwin arch=x64 electron=7.1.2 appOutDir=build/darwin/mac
  • copying Electron source=/Users/gleb/git/cypress/packages/electron/node_modules/electron/dist/Electron.app destination=/Users/gleb/git/cypress/build/darwin/mac/Electron.app
  • copying         src=/Users/gleb/git/cypress/packages/electron/node_modules/electron/dist/Electron.app destination=/Users/gleb/git/cypress/build/darwin/mac/Electron.app
  • async task error error=ENOENT: no such file or directory, stat '/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/.com.microsoft.edgemac.Canary.luXzue/SingletonSocket'
Error: ENOENT: no such file or directory, stat '/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/.com.microsoft.edgemac.Canary.luXzue/SingletonSocket'
    at AppFileWalker.handleSymlink (/Users/gleb/git/cypress/node_modules/app-builder-lib/src/util/AppFileWalker.ts:39:14)
    at /Users/gleb/git/cypress/node_modules/app-builder-lib/src/util/AppFileWalker.ts:30:21
```

**Comment by bahmutov** [comment]
Removed that link with `rm dist/darwin/packages/server/.cy` and built the signed app 
```
$ codesign --verify --deep --strict --verbose=2 build/darwin/mac/Cypress.app
...
build/darwin/mac/Cypress.app: valid on disk
build/darwin/mac/Cypress.app: satisfies its Designated Requirement
$ spctl --assess --verbose build/darwin/mac/Cypress.app/
build/darwin/mac/Cypress.app/: accepted
source=Developer ID
```

Taccy shows
<img width="484" alt="Screen Shot 2019-12-09 at 6 10 50 PM" src="https://user-images.githubusercontent.com/2212006/70481017-43f5c280-1aaf-11ea-9933-6af990bccae7.png">

**Comment by bahmutov** [comment]
Next step - add notarization via `electron-builder`

**Comment by bahmutov** [comment]
Here is the command where we pass electron version and icons
```
./node_modules/.bin/electron-builder 
  --publish never --c.electronVersion=7.1.2 
  --c.directories.app=dist/darwin 
  --c.directories.output=build 
  --c.npmRebuild=false 
  --c.electronCompile=false 
  --c.electronDist=packages/electron/node_modules/electron/dist/ 
  --c.icon=dist/darwin/packages/electron/node_modules/\@cypress/icons/dist/icons/cypress
```

**Comment by bahmutov** [comment]
hmm, the app that electron-builder produces in this case crashes not being able to find production dependencies from `packages/server`

<img width="420" alt="Screen Shot 2019-12-10 at 2 15 32 PM" src="https://user-images.githubusercontent.com/2212006/70561191-0305b880-1b58-11ea-8940-ab4d41bb44fd.png">
