### ISSUE TITLE
Screenshot of webGL content does not render anything

### ISSUE THREAD

**Issue by vomc** [cypress-io/cypress#5792]
### Current behavior:

Running a test script where I am clicking around on a webGL map (using mapboxGL). The video recording is fine, everything shows up as it should. I also periodically take a few screenshots of the map content since we are testing some geoJson rendering on top of the map.

The screenshot output shows all of the other elements on the page, including the map controls but the map content itself is not displayed.

![Screenshot 2019-11-26 at 09 53 11](https://user-images.githubusercontent.com/78635/69613941-af14b300-1032-11ea-8ea3-42bad84b823d.png)
_The above image is a screenshot that I myself took from the generated mp4 file that Cypress created in which my map is rendering correctly_

![Screenshot 2019-11-26 at 09 53 39](https://user-images.githubusercontent.com/78635/69614019-c653a080-1032-11ea-9013-07535074b32d.png)
_Output showing the screenshot is taken_

![Screenshot 2019-11-26 at 09 53 54](https://user-images.githubusercontent.com/78635/69614053-cfdd0880-1032-11ea-88a8-85d9e1efb1e6.png)
_The actual screenshot as it ends up in the Cypress dashboard_

All of this works perfectly on my local machine but not when I run it in CI.

### Desired behavior:

It would be cool if the CI output worked in the same way as it does locally, otherwise it sort of doesnt really make sense to use a tool for visual comparison that does not work consistently.

### Steps to reproduce: (app code and test code)

1. Create a project that uses a mapbox map (using mapboxGL)
2. Record yourself clicking on the map
3. Take a screenshot of the map

### Versions

Works well in latest macos using latest Chrome, does not work on Cypress 
v3.6.1 which I guess is using Linux Debian - 9.6, Electron 73.0.3683.121

**Comment by jennifer-shehane** [comment]
@vomc Can you try running this in CI using [`--browser chrome`](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-browser-lt-browser-name-or-path-gt), specifying an installed version of Chrome from your system?

Also, conversely, try running this locally and selecting 'Electron' to run the tests. I'd like to see if this issue is isolated to Electron 73.

**Comment by vomc** [comment]
@jennifer-shehane hi! Thanks for taking a look. I am not sure what you mean though, in terms of specifying the browser flag. When I do this in CI, I get

```javascript
213 $ node_modules/.bin/cypress run --browser chrome --record --key 1db92da6-9af4-4266-ad31-a2b53ad23641
214 Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
215 Can't run because you've entered an invalid browser name.
216 Browser: 'chrome' was not found on your system.
217 Available browsers found are: electron
```

This is when I am running it inside our Gitlab CI.

Now for more context:

I can see artifacts from Cypress in both CI and also in the Cypress dashboard. For the script in which I am generating screenshots, I see a recorded mp4 video in which the parts of the map that I need to do visual testing on renders fine, i.e.:

![Screenshot 2019-11-26 at 13 36 53](https://user-images.githubusercontent.com/78635/69634299-37568080-1052-11ea-96f5-84a686387d63.png)
_Note that I have blacked out some areas in that screenshot of the video_

But you can see that there is a map that is rendering something, in our case a heatmap

You can also see that a screenshot is being generated.

However this is the screenshot that Cypress generates:

![Screenshot 2019-11-26 at 13 36 36](https://user-images.githubusercontent.com/78635/69634369-58b76c80-1052-11ea-928a-3099d84ddb36.png)
_Again, I have blacked out some areas_

As you can see here, the rest of the page elements render just fine but the map -- ONLY IN THE SCREENSHOT -- is not visible.

Could you let me know why that is?

**Comment by vomc** [comment]
If it helps, for CI I am using the Gitlab recommended image which uses `cypress/base:10` ...

**Comment by jennifer-shehane** [comment]
Cypress will launch within an installed browser on your machine. The base images do not have the Chrome browser installed, so you would need to use one of the images that also includes an installation of the Chrome browser as detailed here: https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

I'm not sure from the initial information on why the screenshot is not displaying the WebGL element in the screenshot. This would require some investigation - including us having an example to run that shows the problem. Providing an example of some HTML + test code that we can run would be ideal.

You mentioned this only happens in CI. I am also trying to isolate whether this happens in Electron and/or Chrome. Can you run the tests locally and select 'Electron', then check the screenshots taken when you run the tests locally to see if this is still a problem.

**Comment by vomc** [comment]
Hi @jennifer-shehane -- I can confirm that using a newer image (`cypress/base:12.13.0` which I am using now) allows the webGL content to render. It might be good to make a note in the recommended Gitlab yaml file about that...

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
