### ISSUE TITLE
cy.visit("/") is failed to load page

### ISSUE THREAD

**Issue by vinod236** [cypress-io/cypress#5793]
When we try to use cy.visit("/") , our Home page is not loading and while tracing network requests we got "Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'" error in response one of doc type.

we use Reactjs + Okta where i am able to login with Okta's API (authn & authorize) but after login , my home page is not loading. 

Cypress Version 3.4.1 

[CypressLog.txt](https://github.com/cypress-io/cypress/files/3890966/CypressLog.txt)

**Comment by jennifer-shehane** [comment]
To narrow down the possible causes, could you run Cypress in our [latest version](https://on.cypress.io/changelog).

Also, I do not see the error described in the Log provided, could you send a screenshot or some information on where this error is displaying. 

Having a url to visit with a reproducible example is ideal, can you provide anything more? Without this it means that we do not have a path to move forward in investigating.

**Comment by vinod236** [comment]
Thanks Jennifer for response, We tried upgrading to latest version 3.6.1 but its gives blank screen error so we are sticking with 3.4.1 version only , i am attaching some of error screen shots , please have look and let me know if you find any problem in the way we are using cypress.
![Capture1](https://user-images.githubusercontent.com/7825972/69645615-70abe200-108c-11ea-990c-a149913e17de.PNG)
![Capture2](https://user-images.githubusercontent.com/7825972/69645616-7275a580-108c-11ea-87cd-d9bfb2ea521c.PNG)
![Capture3](https://user-images.githubusercontent.com/7825972/69645624-73a6d280-108c-11ea-9076-8b8ae20c2346.PNG)
![Capture4](https://user-images.githubusercontent.com/7825972/69645659-87523900-108c-11ea-9330-9624ace969f0.png)

**Comment by irtrends** [comment]
any update on this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
