### ISSUE TITLE
Typescript declarations are using deprecated Mocha interfaces

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#5795]
### Current behavior:

```js
  Cypress.on('test:after:run', (test, runnable) => {
    if (test.state === 'failed') {
      // leads to 'parent' is deprecated. `.parent` has type `Mocha.Suite | undefined` in `Mocha.Test`.
      const screenshotFileName = `${runnable.parent!.title} -- ${test.title} (failed).png`;
    }
  });
```

### Desired behavior:
Should not be deprecated.

### Versions

3.6.1

**Comment by drewbrend** [comment]
I just came here to log this.  I would like this to be fixed as well.  It is currently returning `Mocha.ITest` but should be returning `Mocha.Test`.  It seems like there are other deprecated Mocha interfaces returned as well, but I hit this same one from `test:after:run`.

Also there are properties missing from `Mocha.Test`, like `timings`, but that'll be an issue I'll log with them/DefinitelyTyped.
