### ISSUE TITLE
Shadow dom component dose not load in Cypress browser

### ISSUE THREAD

**Issue by sarafs** [cypress-io/cypress#5798]
### Current behavior:
spec.js
![Screen Shot 2019-11-26 at 11 55 30](https://user-images.githubusercontent.com/437874/69628758-c14b1d00-1043-11ea-8307-eb8088aa0892.png)

Output on `npx cypress open`
![Screen Shot 2019-11-26 at 11 56 49](https://user-images.githubusercontent.com/437874/69629047-e8095380-1043-11ea-9ffc-a43a7042cea0.png)

DOM Snapshot of the page on run 
![Screen Shot 2019-11-26 at 10 55 12](https://user-images.githubusercontent.com/437874/69627839-57cb0e80-1043-11ea-8003-cfacc9ef7a0e.png)

### Desired behavior:
The component in the blue box with title `Did your MP vote to take control of Parliament's agenda?` should  load in the Cypress Electron or Chrome browser to allow me to inspect it using the cypress-showdom-dom plugin. Tests should pass
![Screen Shot 2019-11-26 at 10 57 09](https://user-images.githubusercontent.com/437874/69627853-60234980-1043-11ea-9e82-67802fea43f9.png)

### Steps to reproduce: (app code and test code)
**npm install cypress-shadow-dom**

**package.json** 
```json
"dependencies": {
    "cypress": "^3.6.1",
    "cypress-shadow-dom": "^1.1.1",
```

**commands.js**
```js
import 'cypress-shadow-dom';
```

**Test spec.js**
```js
import 'cypress-shadow-dom';

describe('e2e tests for MP lookup', () => {
  it('finds the mp lookup embed', () => {
  	cy.visit('https://www.bbc.co.uk/news/uk-politics-49571868');
  	cy.get('.bbc-news-vj-embed-wrapper');

  	cy.shadowGet(('.bbc-news-vj-wrapper'), { timeout: 5000 });
  });
})
```

`**npx cypress open**`

**Snapshot of the Shadow dom elements on the page** 
![Screen Shot 2019-11-26 at 12 23 50](https://user-images.githubusercontent.com/437874/69633349-f35e7e00-1047-11ea-8f25-9aaab79da868.png)

**You can fork https://github.com/cypress-io/cypress-test-tiny repo, set up a failing test, then tell us the repo/branch to try** - I have done this locally but unable to push branch to cypress-test-tiny repo. Could you please grant me access?

### Versions
 "cypress": "^3.6.1",
 "cypress-shadow-dom": "^1.1.1"
Mac OS 10.12.6 , Running tests off Terminal Version 2.7.5 `npx cypress run` or `npx cypress open`

**Comment by jennifer-shehane** [comment]
Shadow DOM testing is not fully supported in Cypress as per this issue: https://github.com/cypress-io/cypress/issues/144 Please note anything that you would like to see in Shadow DOM support in that issue (like reviewing snapshots in time travel)

All related questions for the cypress-shadow-dom plugin should be directed to the plugin's repo (it is not supported by the Cypress team). https://github.com/abramenal/cypress-shadow-dom

**Comment by jennifer-shehane** [comment]
We've added experimental shadow DOM support through the `experimentalShadowDomSupport` configuration option.

To use it, update to Cypress 4.8.0 and pass the following to your configuration file or however you pass in configuration. 

```json
{
  "experimentalShadowDomSupport": true
}
```

See the [Experiments](https://on.cypress.io/experiments#Cross-boundary-selectors) for more information including how to use the new `.shadow()` command and `includeShadowDom` option.

This is still experimental, so we'd like your help working through any bugs or unexpected behavior before releasing into the main product. If you encounter any issues using the new experimental shadow DOM feature, please **[open a new issue](https://github.com/cypress-io/cypress/issues/new)**, filling in the issue template and providing a reproducible example.
