### ISSUE TITLE
Buttons are being scrolled behind the sticky header and tests are failing as they cannot be clicked.

### ISSUE THREAD

**Issue by ZoeJa** [cypress-io/cypress#5801]
```
CypressError: Timed out retrying: cy.click() failed because this element: 
<a href="/pages/subscribe" class="btn">Try ...</a>
is being covered by another element:
<div class="bar"> ... </div>
```

### Current behavior:
My tests are failing due to elements being covered by the Sticky Header when it is trying to click them. 

When doing this manually this is not an issue. Running in the cypress editor it looks like cypress is scrolling the buttons behind the header and then failing to click them.

The tests were passing fine on the October 30th, then after code changes where ran again on November 5th and they were failing. Re-running the tests on the previous version of code from October 30th has them all failing in the same way as the November 5th tests. Which leads me to conclude the code changes haven't caused the issue. The tests were not changed in this time period either. 

After investigation it seems like you have released updates recently (October 31st and November 8th). This is the only thing I can think might have potentially caused this issue. 

My tests run automatically via Travis when the GitHub repository is pushed or pulled. Are there any changes I might need to make with regards to my Travis integration since these updates, which might be causing this issue?

Here is the first error I am getting in the Travis log:
![errorMessage1](https://user-images.githubusercontent.com/49906033/69648688-b0120880-1063-11ea-8ae0-d02a92632ddd.png)

Here is the rest of the error message displayed after the test file has finished:
![errorMessage](https://user-images.githubusercontent.com/49906033/69649667-498dea00-1065-11ea-9cfd-038dc186b521.png)

Almost all of the tests are failing on this error or something similar. 
Some of the tests which are passing when run through Travis are failing when run on the Cypress only. 

The tests pass fine if I apply the {force:true} to the click, however, this is not an ideal way to have the test running as this will pass if a button genuinely is being covered. 

Any help with solving what is causing this issue would be greatly appreciated.

### Desired behavior:
The test should be able to click elements, it should not be scrolling them behind the sticky header. 

### App code and test code
Here is one of my tests that is failing:
```js
//From the homepage to the subscription flow
describe('HomePage to subscription flow', () => {
  beforeEach(() => {
    cy.visit('/')
  })
//Select the button in the hero at the top of the page to enter the subscription
  it("Navigates via first button", () => {
    cy.get('.shell > .intro__inner > .intro__actions > .btn').eq(0).click();
    cy.url().should('include', url1);
  })
})
```
When using the cypress runner to go through the states of the test at each stage the test visits the page fine, and when it gets to the 'get' command it scrolls the button to the top of the page behind the sticky header. Then when it is trying to click the button it cannot as it is behind another element. 

Here is the header code: 
``` html
<header class="header" id="header__{{ section.id }}">
  {% if section.settings.top_text != blank and section.settings.top_bar  %}
  <div class="bar">
    <div class="shell">
      <p>{% if section.settings.top_url != blank %}<a href="{{ section.settings.top_url }}">{% endif %}{{ section.settings.top_text }}{% if section.settings.top_url != blank %}</a>{% endif %}</p>
    </div>
    <!-- /.shell -->
    <style type="text/css">
      {% if section.settings.bg_color != blank %}
      #header__{{ section.id }} .bar {
        background-color: {{ section.settings.bg_color }};
      }
      {% endif %}
      {% if section.settings.text_color != blank %}
      #header__{{ section.id }} .bar, #header__{{ section.id }} .bar a {
        color: {{ section.settings.text_color }};
      }
      {% endif %}
    </style>
  </div>
  <!-- /.bar -->
  {% endif %}
  <div class="shell">
    <div class="header__inner">
      <div class="header__mobile-holder">
        <a href="javascript:void(0);" class="btn-menu hidden-sm hidden-md hidden-lg">
          <span></span>

          <span></span>

          <span></span>
        </a>

        <a href="/" class="logo">
          {{ 'logo.svg' | asset_url | img_tag }}
          
        </a>
      </div>
      <!-- /.header__mobile-holder -->

      <nav class="nav">
          <ul>
            {% assign navCounter = 0 %}
          {% for link in linklists[section.settings.main_linklist].links %}
            
          <li>
            <a class="link-item" {% if link.links != blank %} onclick="showSubnav({{ navCounter }})"{% else %} href="{{ link.url }}"{% endif %}>{{ link.title | escape }} {% if link.links != blank %}<i class="fas fa-chevron-down"></i>{% endif %}</a>
            {% if link.links != blank %}
            {% assign navCounter = navCounter | plus: 1 %}
            <div class="subnav hideSubnav" id="subnav{{ navCounter }}">
              <div class="subnav-split"></div>
              <div class="subnav-content">
              {% for child_link in link.links %}
                <a class="sub-link-item" href= "{{ child_link.url }}">{{ child_link.title }}</a><br>
              {% endfor %}
              </div>
              <div class="subnav-split"></div>
            </div>
            
            {% endif %}
          </li>
          
		  {% endfor %}
          {% if customer %}
          <li class="hidden-sm hidden-md hidden-lg">
            <hr>
            <br>            
            <a href="/account/logout">{{ 'layout.customer.sign_out' | t }}</a>  
          </li>
          {% endif %}
          </ul>
      </nav>
      <!-- /.nav -->

      {%- include 'nav-access' -%}
    </div>
    <!-- /.header__inner -->
  </div>
  <!-- /.shell -->
</header>
<!-- /.header -->
```
Here is the code for the section containing the button being clicked in the test: 
```html
<div id="intro__{{ section.id }}" data-section-id="{{ section.id }}">
  <div class="intro">
    <div class="intro__content">
      <style type="text/css">
        {% if section.settings.image %}
        #intro__{{ section.id }} .intro__content {
          background-image: url({{ section.settings.image | img_url: 'original' }});
        }
        {% endif %}
        {% if section.settings.text_color != blank %}
        #intro__{{ section.id }} .intro {
          color: {{ section.settings.text_color }}
        }
        {% endif %}
        {% if section.settings.m_image %}
        @media only screen and (max-width: 767px) {
          #intro__{{ section.id }} .intro__content {
            background-image: url({{ section.settings.m_image | img_url: 'original' }});
          }
        }
        {% endif %}
      </style>
      <div class="shell">
        <div class="intro__inner">
          {% if section.settings.sub_heading != blank %}
          <h4>{{ section.settings.sub_heading }}</h4>
          {% endif %}
		  {% if section.settings.heading != blank %}
          <h1>{{ section.settings.heading }}</h1>
          {% endif %}
		  {% if section.settings.content != blank %}
          <div class="intro__info">
            {{ section.settings.content }}
          </div><!-- /.intro__info -->
		  {% endif %}
          {% if section.settings.btn_text != blank and section.settings.btn_url != blank %}
          <div class="intro__actions mobile-fixed--bottom">
            <a href="{{ section.settings.btn_url }}" class="btn">{{ section.settings.btn_text }} <i class="fas fa-long-arrow-alt-right"></i></a>
          </div>
          {% endif %}
          <!-- /.intro__actions -->
        </div>
        <!-- /.intro__inner -->
      </div>
      <!-- /.shell -->
    </div>
    <!-- /.intro__content -->
  </div>
  <!-- /.intro -->
</div>
<!-- /#section-id {{ section.id }} -->
```

My tests are set to run with viewport sizes: 
```
"viewportWidth": 1366,
 "viewportHeight": 768
```

Testing is done in Chrome 78, on Windows 10

**Comment by jennifer-shehane** [comment]
You mentioned newer Cypress versions maybe being the issue - can you run your project on each previously released version of Cypress to see which version this is fixed in? All released versions here: https://on.cypress.io/changelog

If you find a previous version that works - the best solution for you today would be to revert and stick to that version. 

Aside from that, there are a lot of factors you included that make this impossible for us to run - you included code that is not runnable without the templates and data involved in your template, likewise css is probably a crucial component and you did not provide the css.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
