### ISSUE TITLE
Cypress --> Test doubled

### ISSUE THREAD

**Issue by gianlucabaldin** [cypress-io/cypress#5806]
### Current behavior:

In one of my xxx.spec.js files I have one context with one tests, I noticed that after adding an `import` inside `commands.js` from `xxx.specs.js` file, the Test Runner shows (and runs) the tests twice !

Depending on commenting/uncommenting the import inside the `commands.js` file, the Test Runner shows one context with one test (desired) or two contexts with one test per context (current)

### Desired behavior:

Test Runner should show/run just the described tests, not double them

### Steps to reproduce: (app code and test code)

In my actual real project I have three `*.spec.js` files, the latter in which I found the problem has one context with four tests, but I get the problem even with this minified version.

- `cypress/integration/share.spec.js`

```js
/* eslint-disable no-undef */
/// <reference types="Cypress" />
export const MY_CONSTANT = "myCostant";
context("test1", () => {
  it("Project - Should show 'No shares'", () => {
    console.log("Hi");
  });
});
```

- `cypress/support/commands.js`

```js
import { MY_CONSTANT } from "../integration/share.spec.js";
// no other code lines necessary!!
```

### Versions

Cypress 3.6.1, Node v10.16.3, npm v6.9.0

**Comment by jennifer-shehane** [comment]
@gianlucabaldin I can recreate this issue as described in version 3.8.1. The key being that the import is coming from a spec file within Cypress integration folder.

`cypress/integration/spec.js`

```js
export const MY_CONSTANT = "myCostant"

it("Test 1", () => {})
```

`support/index.js`

```js
import { MY_CONSTANT } from "../integration/spec.js";
```

<img width="385" alt="Screen Shot 2020-01-03 at 12 23 48 PM" src="https://user-images.githubusercontent.com/1271364/71709149-eb9eb000-2e23-11ea-9e9f-dc4d05e4ccef.png">

**Comment by sainthkh** [comment]
This is not a Cypress problem.

This is happening because when you import the constant from a spec file, the test is executed first. And when Cypress executes the spec file, they are run one more time. 

It's how JavaScript works. So, it's not the part of Cypress problem.

To solve this, the project structure should be changed. In this case, it is recommended to create a `shared` folder inside `cypress` like below:

```
cypress
-- shared
   -- constants.js
-- integration
   -- x.spec.js
-- support
   -- index.js
```

And import constants.js from both x.spec.js and index.js.
