### ISSUE TITLE
Plugin system for preprocessors

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#581]
Create a plugin system for preprocessing test code so that users can utilize any build system they want to process spec files. 

In addition to processing the files, a preprocessor can control file watching.

By default, the current preprocessing strategy will be enabled, allowing ES2015+ and CoffeeScript to be used without any extra configuration. 

A user will be able to configure the system to use their own preprocessing strategy instead or none at all if they don't need it.

**Comment by chrisbreiding** [comment]
Closing in favor of https://github.com/cypress-io/cypress/issues/684

**Comment by brian-mann** [comment]
Released in [`1.1.0`](https://docs.cypress.io/guides/references/changelog.html#1-1-0).
