### ISSUE TITLE
Feature request: --cypress-env-file flag

### ISSUE THREAD

**Issue by pcj** [cypress-io/cypress#5811]
I have various different "scenarios" that are saved in cypress.env.json-like files.  It would be favorable if I could override the file to be used as the `cypress.env.json` file at the command line.

Something like:

`$ cypress open --cypress-env-file=cypress.env.my-test-scenario.json`

**Comment by stefanzmf** [comment]
What about using [```--config-file``` flag ](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-config-file-lt-config-file-gt)?

**Comment by jennifer-shehane** [comment]
The flag would be called `--env-file` since we do not prepend any of our flags with `cypress`. 

Here is the PR for the `--config-file` argument, so a similar amount of work would need to be done for the `--env-file` argument. https://github.com/cypress-io/cypress/pull/3246

**Comment by pcj** [comment]
Would you be willing to accept a PR for this?

**Comment by jennifer-shehane** [comment]
We'll be deprecating the cypress.env.json file in a future version, so this is no longer in our scope of work.
