### ISSUE TITLE
[GithubActions] Cypress v3.7.0 does not determine CI build ID

### ISSUE THREAD

**Issue by jon301** [cypress-io/cypress#5814]
### Current behavior:

When running Cypress v3.7.0 on Github Actions with `record` and `parallel` flags, this error occurs:

```
StatusCodeError: 422

{
  "code": "INDETERMINATE_CI_BUILD_ID",
  "message": "CI Build ID could not be generated and was not specified."
}
```
`projectId` is correctly set in `cypress.json`

Record Key is correctly exposed in an environment variable in Github Actions YAML config file:

```
...
        run: yarn e2e:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
...
```

Output:

![image](https://user-images.githubusercontent.com/122108/69787187-422d2480-11bc-11ea-9095-92a03718dd3c.png)

### Desired behavior:

CI Build ID should be determined when running tests on Github Actions

### Versions

Cypress v3.7.0

**Comment by bahmutov** [comment]
seems related to #5609 - in our kitchensink example we are passing the CI build id manually https://github.com/cypress-io/cypress-example-kitchensink/blob/7019b85f0a8467089da33cda823d04fee8bc2cf1/.github/workflows/parallel.yml#L130

```
--ci-build-id "$GITHUB_WORKFLOW-$GITHUB_SHA"
```

The Test Runner v3.7.0 sends the workflow and SHA information to the dashboard API (see #5687) but we have not implemented the API side (forming build id there)

**Comment by bahmutov** [comment]
After thinking about it - it would require a lot of refactoring to support this feature. Right now we only consider CI environment variables while forming CI build id, and do not pass commit information. Passing commit information would require too many changes and tests. Soon GitHub Actions will set an environment variable with unique workflow ID, which we will pass in the Test Runner to support this.

Watch this issue when it lands and reopen this issue to use it https://github.com/actions/toolkit/issues/65#issuecomment-566164554

For now, pass custom CI build id, please
