### ISSUE TITLE
CypressError: cy.visit() failed trying to load: http://IP:port/something.action We attempted to make an http request to this URL but the request failed without a response.  Error: Setting cookie failed

### ISSUE THREAD

**Issue by bharat8657** [cypress-io/cypress#5821]
Hello Team,

We are facing issues while opening one of the in house application which is in intranet.
Application is reachable from the Jenkins slave where we are running cypress docker image. Below is the command we re using to run,

```
docker run -it -v $PWD:/e2e -w /e2e docker-registry/cypress/included:3.4.0
```

It pulls the image start wait for test execution and throws below exception.
```

│ Cypress:    3.4.0                                                                              │
  │ Browser:    Electron 61 (headless)                                                             │
  │ Specs:      5 found 

Running: examples/AppPOM.js...                                                       (1 of 5)


  App - Commercial Report 3.0 Registration Form
    1) test1
    2) test2
```

![image](https://user-images.githubusercontent.com/19266496/69854727-d0ce9e00-12af-11ea-985f-cd0c7341f32a.png)

However, URL is reachable from Jenkins slave and we are getting the response as well, but when it runs in cypress container it throws above exception.

I tried exporting proxy variables `http_proxy`, `https_proxy`, `no_proxy` on the machine and then running the docker container.

I also tried passing environment variable to docker container, also to env to `cypress.json` but so far nothing is working, tried with different container images as well

Cheers,
Bharat

**Comment by bharat8657** [comment]
Just to add further, when I curl inside container, i gets response. but when it hits in URL it still give above exception

**Comment by lnm8910** [comment]
I am facing same issue with contenerized cypress. I have a spring boot application running on port 8080. CURL returns 200 OK, however Cypress fails with ERR Connection refused.

**Comment by jennifer-shehane** [comment]
@bharat8657 I'm a bit confused between the error you pasted an image of and the error you pasted in the title. They are completely different. 

The screenshot shows a response code of 403. 

But in the title you are mentioning the error:

```
cy.visit() failed trying to load: http://IP:port/something.action We attempted to make an http request to this URL but the request failed without a response. Error: Setting cookie failed 
```

Which is the problem you are having? 

Also please try updating to the [current version of Cypress](https://on.cypress.io/changelog) and let me know if this is still happening for you? If it is a cookies issue (like you mentioned in the title) then we have fixed a lot of cookies issues.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
