### ISSUE TITLE
CypressError: cy.click() failed because it requires a DOM element.

### ISSUE THREAD

**Issue by 90sidort** [cypress-io/cypress#5825]
### Current behavior:

Cypress adds click that is not in the code and fails to perform it. Funny thing is that the exact same code is executed with no errors in the first test (but then fails in other test cases). 

Code:
![image](https://user-images.githubusercontent.com/55019396/69862505-d2da3200-129a-11ea-8996-a197d07da943.png)

First run:
![image](https://user-images.githubusercontent.com/55019396/69862358-85f65b80-129a-11ea-9055-969385167173.png)

no errors, only one click (as in the code)

From test run with error (two clicks, the second one is not in the code) 
![image](https://user-images.githubusercontent.com/55019396/69862798-8d6a3480-129b-11ea-811d-6650ef730c7f.png)

### Desired behavior:

Cypress should not add the click that is not in the code. 

### Steps to reproduce: (app code and test code)

DOM Element to be clicked:
'input[id=loginButton]'

Cypress code: 
```js
cy.get('input[id=loginButton]', {timeout: 30000}).click()
```

### Versions

Cypress 3.6.1, Windows 10, Chrome 78,

**Comment by 90sidort** [comment]
I added wait before cy.loginAdmin and now I have even more strange error:
Code: 
![image](https://user-images.githubusercontent.com/55019396/69863823-fc488d00-129d-11ea-9553-0ddaaf0f3f8f.png)

Error:
![image](https://user-images.githubusercontent.com/55019396/69863734-ce634880-129d-11ea-86f4-5b411df1d1f0.png)

I have no idea what is happening here.

**Comment by BasheerBadaha** [comment]
Hey,

Have you already found a solution for this issue here?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
