### ISSUE TITLE
CypressWorks on winserver2016 if we trigger with jenkins?

### ISSUE THREAD

**Issue by bharat8657** [cypress-io/cypress#5828]
We ran a test with Jenkins to trigger cypress on win server.
Test got triggered, but got below
[project_cypress] $ powershell.exe -NonInteractive -ExecutionPolicy ByPass "& 'C:\Users\bharatm\AppData\Local\Temp\jenkins6500695436121681447.ps1'"

> CypressPOC@1.0.0 test D:\jenkins\workspace\TestAutomation\project\cypress\project
> cypress open

And it loads and it loads, does not give any output, is it expected behaviour?

![image](https://user-images.githubusercontent.com/19266496/69871828-d17c2a00-12d9-11ea-96fb-2ad31be9c25b.png)

**Comment by bahmutov** [comment]
`cypress open` is for local development that opens the GUI
`cypress run` is for headless runs on CI

Switch to `cypress run` and you should be good to go, see more at https://on.cypress.io/ci
