### ISSUE TITLE
mousedown does not have event.button property

### ISSUE THREAD

**Issue by inovramadani** [cypress-io/cypress#5829]
### Current behavior:

`.trigger('mousedown')` on an element does not have `event.button` property. This makes a lot of part on my application code can't be tested properly.

### Desired behavior:

There should be an options property for opting which button preferred triggered along with the mousedown event. Could be left, middle, or right click. 

### Steps to reproduce: (app code and test code)

```js
// app code
_handleMouseDown = (e) => {
    console.log('_handleMouseDown: ', e.button); // this will print undefined with current cypress 
 mousedown functionality
    if (e.button === 0) { // left click
      mouseDown = true;
      this._handleStartRecord();
     }
  }
```

```js
// test code
it('Should record when clicking mic button > 300ms (1100ms) repeatedly', async () => {
    finishLoadingMessages()
    cy.get('.single.right').then(els => {
      const recordingNumber = 10
      const initialLength = els.length
      cy.log('audio messages sent: ', initialLength)

      for (let i=0; i < recordingNumber; i++) {
        cy.get('.mic').trigger('mousedown')
        cy.wait(1100)
        cy.get('.mic').trigger('mouseup')
        cy.wait(1000)
      }

      cy.get('.single.right').should((messages) => {
        const finalLength = initialLength + recordingNumber
        expect(messages.length).to.equal(finalLength)
      })
    })
  })
```

### Versions

Cypress: 3.3.2
OS: Windows 10
Browser: chromium

**Comment by avallete** [comment]
`.trigger`  will construct an event based on the options you pass to him.

So, in your case, you should add the `button` desired as an option for the MouseEvent constructor as documented [here](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent).

```js
cy.get("#test").trigger('mousedown', {button: 0});
cy.get("#test").trigger('mousedown', {button: 1});
cy.get("#test").trigger('mousedown', {button: 2});
cy.get("#test").trigger('mousedown', {button: 42});
...
```

**Comment by inovramadani** [comment]
@avallete thanks for the guide, it works!
Hope to have it listed as well on cypress docs pages.

**Comment by jennifer-shehane** [comment]
Closing as resolved.

I've opened a PR to add this example to our docs here: https://github.com/cypress-io/cypress-documentation/pull/2277 Our documentation is open source and contributions are welcome. 😄

**Comment by yGuy** [comment]
That's actually a very unfortunate default because the "correct usage" [in the documenation](https://docs.cypress.io/api/commands/trigger#Syntax) is missing the button argument. 
As the OP said, this triggers the creation of a mouse event that you won't find anywhere in real browsers, because it is simply missing the button property. Most software that checks for the button property (e.g. to find out if it was the left mouse button) will fail this way leading to hard to debug testing issues.
