### ISSUE TITLE
Using trigger() in command specification leads to 'Cypress detected that you returned a promise' error

### ISSUE THREAD

**Issue by seyfer** [cypress-io/cypress#5834]
# Current behavior:

Cypress missing the `hover()` method for some reason. https://github.com/cypress-io/cypress/issues/10

I have added my own implementation with use of `trigger()` as it is recommended in docs.
https://on.cypress.io/trigger

```js
Cypress.Commands.add('hover', {prevSubject: 'element'}, subject => {
    cy.get(subject.selector).trigger('mouseover');
});
```

But when I use it
```js
cy.get('#some').hover();
```

I get this error from the docs https://on.cypress.io/error-messages#Cypress-detected-that-you-returned-a-promise-from-a-command-while-also-invoking-one-or-more-cy-commands-in-that-promise

```
CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > cy.trigger()

The cy command you invoked inside the promise was:

  > cy.task()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.
```

In my case this hover works, I can see it hovering in the test runner. But I have an animation to show up some children element on hover. Probably it is considered as Promise for Cypress? Because I do not return it explicitly anywhere.

### Desired behavior:

https://github.com/cypress-io/cypress/issues/10 resolved or at least Cypress doesn't react to `trigger()` side effects or any other workaround possible.

### Steps to reproduce: (app code and test code)

Described in the description.

### Versions

Latest Cypress (3.7.0), latest Chrome from deb repositories, Debian.

**Comment by seyfer** [comment]
I have disabled the error for now
```
Cypress.on('fail', err => {
    //workaround for using trigger() in command bug
    if (err.message.includes('Cypress detected that you returned a promise')) {
        return false;
    }
});
```

**Comment by avallete** [comment]
I just tried your command code and it don't show on my machine :/

Are you sure you don't make any other call to "Promise like" function into your test (like `.then(...)`)  who may cause the error ?

If not, could you please provide an [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) or the code of your `it` test case in error, to be able to reproduce ?

**Comment by seyfer** [comment]
@avallete I have Vue app and it renders some elements on hover. I thought it might be the reason.
```
it('I Want to see messages and create a new one', async () => {
        cy.get('#multiple-message-open-modal-btn').hover().click();
        cy.get('.v-modal').should('be.visible');
        cy.get('.v-modal__body > .multiple-message-type').should('have.length', 3);
        cy.get('.multiple-message-type:first-child').click();

        cy.url().should('contain', 'edit');
        cy.get('#individual-message-settings-panel').should('be.visible');
    });
```

also after the last `click` there is XHR request performed on the background (in Vue).

**Comment by avallete** [comment]
I think your error come from the way you declare your `it` test and the use of the `async` keyword.

According to [cypress documentation](https://docs.cypress.io/guides/getting-started/writing-your-first-test.html#Step-1-Visit-a-page) there is no need for your `it` to be an `async` style funciton.

This is probably why you see the 'invoking from a promise' error.

@seyfer could you try your `it` without the `async` keyword ? I think it should fix your error.

**Comment by seyfer** [comment]
@avallete I started to use Cypress Cucumber plugin and with new syntaxis, the issue disappeared from errors, but still outputs in the browser dev tools console as a warning.

In my example, I just forgot to remove `async`, sorry. It still was failing without it.
Anyway, the issue was kind of solved with Cucumber plugin.
