### ISSUE TITLE
cy.clear({ force: true }) only deletes first character of hidden input in 3.5.0

### ISSUE THREAD

**Issue by mpetrovich** [cypress-io/cypress#5835]
### Current behavior:

`.clear({ force: true })` only deletes the first character of a hidden input's initial `value`.

### Desired behavior:

`.clear({ force: true })` should delete all characters of a hidden input's initial `value`.

### Steps to reproduce: (app code and test code)

https://github.com/mpetrovich/cypress-test-tiny ([compare](https://github.com/cypress-io/cypress-test-tiny/compare/master...mpetrovich:master))

Given:

```html
<input type="text" value="initial value" style="visibility: hidden">
```

This assertion fails:

```js
cy.get('input').clear({ force: true }).should('have.value', '')
```

With error:
```
CypressError: Timed out retrying: expected '<input>' to have value '', but the value was 'nitial value'
```

Note: Issue persists when input is hidden with `style="display: none"` as well.

### Versions

These versions have been confirmed to be affected:
v3.7.0
v3.6.1
v3.6.0
v3.5.0

These versions have been confirmed to NOT be affected:
v3.4.1
v3.4.0
v3.3.2

**Comment by jennifer-shehane** [comment]
I've confirmed this is an issue introduced in 3.5.0. @Bkucera 

`index.html`

```html
<!DOCTYPE html>
<html>
<body>
  <input type="text" value="initial value" style="visibility: hidden">
</body>
</html>
```

`spec.js`

```js
it('clear value of hidden input', () => {
  cy.visit('index.html')
  cy.get('input').clear({ force: true }).should('have.value', '')
})
```

## 3.4.1

<img width="1084" alt="Screen Shot 2019-12-03 at 2 55 25 PM" src="https://user-images.githubusercontent.com/1271364/70033098-27541900-15dd-11ea-85f3-3f5f94ecc6b2.png">

## 3.5.0

<img width="1084" alt="Screen Shot 2019-12-03 at 2 53 49 PM" src="https://user-images.githubusercontent.com/1271364/70033112-2d49fa00-15dd-11ea-8736-453bb46ac449.png">

**Comment by mpetrovich** [comment]
Thanks for the quick turnaround!
