### ISSUE TITLE
TypeError: Cannot read property 'URL' of undefined in 3.7.0

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#5836]
### Current behavior:

`cy.request()` in version 3.7.0 fails with `TypeError: Cannot read property 'URL' of undefined` and the failure does not contain the same information as pre-3.7.0

Compare output for the same 404 failure in version 3.4.1 with output in version 3.7.0

#### 3.4.1

<img width="568" alt="image001 (4) copy" src="https://user-images.githubusercontent.com/1271364/69908511-72253380-1419-11ea-8b96-126b6a4eb765.png">

#### 3.7.0

<img width="564" alt="image002 (1) copy" src="https://user-images.githubusercontent.com/1271364/69908515-7bae9b80-1419-11ea-8268-71954d5881e7.png">

### Desired behavior:

Print information from request in error message so that it can be better debugged.

### Steps to reproduce: (app code and test code)

No steps to reproduce were provided from the user experiencing this problem. I have the url of the request, but do not have the proper test code to run to get past a 401 validation on the URL, so cannot fully reproduce.

### Versions

Cypress 3.7.0
Do not know OS or browser version being used either

## Please provide reproducible example

If anyone if facing this issue, we need a fully reproducible example provided - it's the best way forward for us to fix the issue.

**Comment by elenaflorko** [comment]
Dear @jennifer-shehane ,

To reproduce this issue this simple test is enough:
`describe('Test Cypress cy.request output', () => {
    it('When I have cy.request that fails I can see the reason in UI', () =>{
        cy.request('https://docs.cypress.io/api/commands/blabla')
    })
})`

The output in Cypress UI 3.7.0:
<img width="591" alt="Screenshot 2019-12-02 at 14 49 25" src="https://user-images.githubusercontent.com/46819948/69964724-2bb3ff80-1513-11ea-9e0a-d7ebeb7258f6.png">

The output in Cypress UI 3.4.1:
<img width="856" alt="Screenshot 2019-12-02 at 14 52 51" src="https://user-images.githubusercontent.com/46819948/69964852-79306c80-1513-11ea-9b27-1cc923ae82c6.png">

The error in Cypress version 3.7.0 says nothing about the reason why it failed. We run tests in GitLab and Cypress screenshots with proper output about errors are important for us.

**Comment by jennifer-shehane** [comment]
Hey @elenaflorko - this seems a bit strange, but I actually can't recreate this behavior with the test provided above, doing the cy.request in the docs. The full length of the error message is displayed in both 3.4.1 and 3.7.0.

Can you double check and ensure there is no code in your `support/index.js` file, no code in your `plugins/index.js` file and no configuration in your `cypress.json` file when you run the code above? Maybe this issue can be narrowed down to something else present in your configuration.

Also, what browser are you running the tests within?

**Comment by elenaflorko** [comment]
@jennifer-shehane you are right!
I checked the `support/index.js` and have found a bit of hack added by my colleague half a year ago.
I think it was added for better error output:

`Cypress.on('fail', error => {
    const loggableError = error
    const urlOfPageWithFailure = Cypress.$('.runner container').context.URL //hack to get url of page under test, not url of cypress runner
    loggableError.message = `${error.message} \nOn page ${urlOfPageWithFailure}`
    Cypress.env('isFailed', true)
    throw loggableError
})`

Thank you very much and sorry for the inconvenience!

**Comment by jennifer-shehane** [comment]
@elenaflorko Great! glad we found a solution 😄 I'll be closing this issue as resolved.
