### ISSUE TITLE
Hangs cypress in case of multiple await statment for electron 61 browser

### ISSUE THREAD

**Issue by dalipkumar703** [cypress-io/cypress#5838]
### Current behavior:
Test case hang after reaching await statement in electron 61 working fine with chrome 78.

In case of electron 61

![image](https://user-images.githubusercontent.com/11908216/69915490-872fb000-1475-11ea-9a8b-dc82fd28a66e.png)

in case of chrome 78

![image](https://user-images.githubusercontent.com/11908216/69915608-fc4fb500-1476-11ea-9c05-24bdb95a05f2.png)

### Desired behavior:

It should work fine as work in chrome 78 doesn't hang after reaching first get statement.

```js
describe('Performance Tests', () => {
  const result = null;
  let welcomeLoadTime;
  const activitiesTimeMeasure = [];

  describe('Performance Benchmarking', () => {
    it('should log the user in', async () => {
      // await cy.wait(5000);

      console.log('login');
      cy.visit('https://rees52.com/');

      cy.title().should('eq', 'REES52');
      await cy.get('.level-1', {timeout: 20000});

      await cy
        .get('.level-1', {timeout: 30000})
        .first()
        .click({force: true});
    });
  });
});
```

### Steps to reproduce: (app code and test code)

1. Paste same code in integration folder of cypress
2. run once in chrome 78
3. run once in electron 61
Observe difference

### Versions
3.4.1
Window 10
Electron 61

**Comment by jennifer-shehane** [comment]
Cypress does not support `await` written in this way. We will not be fixing any issues regarding using `await` in a manner that is not supported by the API. See https://github.com/cypress-io/cypress/issues/1417

**Comment by dalipkumar703** [comment]
> Cypress does not support `await` written in this way. We will not be fixing any issues regarding using `await` in a manner that is not supported by the API. See #1417
Thanks for update ! I did refactor in my code now using .then .
