### ISSUE TITLE
Stubbed route doesn't pass response when configured with error status

### ISSUE THREAD

**Issue by kylemh** [cypress-io/cypress#5840]
### Current behavior:

I have a form where the submit handler has a big try-catch and makes a PATCH request to `myapi.com/auth/profile`...

```js
cy.route({
    method: 'PATCH',
    url: 'auth/profile/',
    status: 500,
    response: {
    data: {
      error,
    },
  },
}).as('badProfileUpdate');
```

Error statuses are correctly thrown and caught, but the response passed is disregarded. Instead, a system error is thrown and passed to the `catch`.

### Desired behavior:

An error status throws on `cy.route()`, but any caught error form that should pass the response as the error object.

### Steps to reproduce: (app code and test code)

[**Test code**](https://github.com/OperationCode/front-end/blob/6971cba328e44bf158ffe2401c63c17497d6d53d/cypress/integration/profile/update.spec.js) and [**source code**](https://github.com/OperationCode/front-end/blob/6971cba328e44bf158ffe2401c63c17497d6d53d/components/UpdateProfileForm/UpdateProfileForm.js)

### Versions
- Cypress: latest
- Chrome: latest
- MacOS: latest

**Comment by jennifer-shehane** [comment]
Hey @kylemh, could you be more specific about which test exactly is failing and should not be failing? I got the update.spec.js up and running in your project and see all of the tests are passing. I would like to know the exact example to focus on. Is this on a specific branch?

Also, has this always been the behavior or did you make a change where now this is failing? Thanks.

**Comment by kylemh** [comment]
I made a smaller example spec for you to toy with! It's `example.spec.js` on the branch `mve-cypress-issue-5840`. The first test passes, but the 2nd fails.

Basically, when the `handleSubmit` in `MultiStepForm` throws, I would expect [this `generateError` method](https://github.com/OperationCode/front-end/blob/master/components/UpdateProfileForm/UpdateProfileForm.js#L28) to parse the response to render the error thrown by the server.

Sorry I didn't make it easier for you to begin with - I wasn't even sure if my complaint was valid.

**Comment by jennifer-shehane** [comment]
I can see the 500 responding with the `data.error` you specified in the mock when running the code below and inspecting in the debugger. 

```js
    cy.wait(`@${ErrorAPICall}`).then(response => {
      debugger;
    });
```

![Screen Shot 2020-01-03 at 12 51 28 PM](https://user-images.githubusercontent.com/1271364/71710071-d0826f00-2e28-11ea-828c-94fc951c84c5.png)

I can also see the request in the Network tab returning the response you asked it to. 

![Screen Shot 2020-01-03 at 12 59 32 PM](https://user-images.githubusercontent.com/1271364/71710098-f871d280-2e28-11ea-841f-39d1cd622296.png)

I'm not sure what else there is for me to look at here. If the application is not showing the message you are expecting from the request that is clearly going through from Cypress then this must be some wrong logic in the application code. This is not a problem with Cypress.
