### ISSUE TITLE
Improve cy.route alias/waiting interface

### ISSUE THREAD

**Issue by dil-jmcgill** [cypress-io/cypress#5841]
While interacting with cy.route I've found the .as / .wait syntax to be a little clunky.
As a result I wrapped cy.route in a helper method to achieve the below desired behaviour and believe this could be a preferable interface to interact with the route so pushing it up for feedback/input.

### Current behavior:

```js
cy.route({ 
  url: '/login',
  response: { success: true }
}).as('loginRequest');
...

cy.wait('@loginRequest');
```

### Desired behavior:

```js
const loginRequest = cy.route({ 
  url: '/login',
  response: { success: true }
});
...

loginRequest.wait();
```

I currently have route being wrapped as
```js
function route(options: Partial<Cypress.RouteOptions> & {url: string | RegExp}) {
    const url = options.url.toString();
    if (!counter[url]) {
        counter[url] = 0;
    }

    const identifier = `${options.url}-${counter[url]}`;
    const result = cy.route(options).as(identifier);
    counter[url] ++;
    return Object.assign(result, {
      as: undefined,
      wait: () => {
        return cy.wait(`@${identifier}`);
      },
    });
}
```

**Comment by gabbersepp** [comment]
Imagine a situation where you define the route in a `beforeEach` step and use the request in subsequent tests. In my opinion the alias-usage is nicer as a local variable. But this is very subjective.

In cases where the route definition is directly followed by the `wait` I would prefer the suggested variant.

**Comment by dil-jmcgill** [comment]
I don't see the difference between storing an alias at the describe scope and the request object itself.

```describe('Describe', () => {
  let loginRequest: Cypress.WaitableRequest;
  beforeEach(() => {
    loginRequest = cy.route({ 
      url: '/login',
      response: { success: true }
    });
  });
  it('it', () => {
    loginRequest.wait();
  });
});
```

```describe('Describe', () => {
  const loginRequest = 'loginRequest';
  beforeEach(() => {
    cy.route({ 
      url: '/login',
      response: { success: true }
    }).as(loginRequest);
  });
  it('it', () => {
    cy.wait(`@${loginRequest}`);
  });
});
```

**Comment by jennifer-shehane** [comment]
Thanks for sharing your suggestions on the `cy.route()` interface. Our full network layer rewrite will expand the API for `cy.route()` making it more robust. 

- See the issue here: https://github.com/cypress-io/cypress/issues/687 
- Work in Progress here: https://github.com/cypress-io/cypress/pull/4176

I'll be closing this issue as part of that larger issue.
