### ISSUE TITLE
Cypress job do not exit on fail (Gitlab CI)

### ISSUE THREAD

**Issue by AlexLo33** [cypress-io/cypress#5845]
Hi everyone ! I don't know if it's a Cypress bug or a Gitlab bug but i'm stuck with my pipeline...

### Current behavior:

I run my tests in a job with Gitlab.

When all tests are OK (no fails), the job end correctly and the next job is launched

BUT

When one test fail, the job is still running altough the Cypress process is trying to exit with code 1

**gitlab-ci.yml** 

```yml
tests_e2e:
  stage: tests_e2e 🖥️
  script:
    - yarn cy:test
```

**package.json :**

```json
"cy:run": "DEBUG=cypress:* cypress run",
"cy:test": "wait-on -t 600000 http://localhost:9000 && yarn cy:run"
```

### Desired behavior:

My job will "successfully" fail after a test fail

With Debug mode, when all tests passed :
![success_tests_job_end](https://user-images.githubusercontent.com/36440833/69953160-f7cbe080-14f8-11ea-9d98-86e595a5ddbe.jpg)

With debug mode when a test fail :
![fail_tests_job_stuck](https://user-images.githubusercontent.com/36440833/69953293-3cf01280-14f9-11ea-89b4-165d69a212ae.jpg)

### Steps to reproduce: (app code and test code)

* Launch a Gitlab job with successfull tests
* See the job pass
* Retry with a failed test
* See the job stuck

**My test code :**

_Success :_ 

```js
it('Go to login page', () => {
    cy.visit('/signin');
    cy.get('input[name=login]').should('be.visible');
  });
```

_Fail : (input with name login123 does not exist)_

```js
it('Go to login page', () => {
    cy.visit('/signin');
    cy.get('input[name=login123]').should('be.visible');
  });
```

### Versions
Cypress 3.7.0

**Comment by AlexLo33** [comment]
FYI, Maybe i'm not the only one with this issue : 
https://stackoverflow.com/questions/58880355/gitlab-ci-runner-hangs-after-cypress-tests

**Comment by gabbersepp** [comment]
Hey I have the same issue since a update from cypress 3.4.1 to 3.6.1 today. We are using jenkins and the pipeline plugin. The build process hangs:
![image](https://user-images.githubusercontent.com/3234900/69960887-e8559300-150a-11ea-8890-844fdc49de42.png)

Currently I try to find more information by activating debug logs.

**Comment by jennifer-shehane** [comment]
@AlexLo33 Can you try running the tests in CI passing [`--browser chrome`](https://on.cypress.io/command-line#cypress-run-browser-lt-browser-name-or-path-gt)? This will launch the tests within a Chrome browser detected on your machine. I'd like to narrow does if this is an issue isolated to the Electron browser.

Also, there is an issue with hanging in CI here that we're working to fix: https://github.com/cypress-io/cypress/issues/5475 It may be related, but I haven't seen this happen in the same way your describing - only when a test fails.

You may want to try downgrading to 3.4.1 regardless, see if this is an issue isolated to a recent release in the past 6 weeks.

**Comment by AlexLo33** [comment]
I already have tried to downgrade to v3.4.1, same issue...
I'll try with a Chrome :)

**Comment by AlexLo33** [comment]
I have found the issue, it was not with Cypress but with Gitlab...

For informations : 

I started my server in background with ```/myapp/bin/start &``` (so with ```&```) and at the end of my tests Gitlab didn't want to go to the next script because my application's process was still running...

So I had to, in the same script, launch my application, run my tests, save the exit code out by Cypress, kill my application and return the saved exit code.

And, it works! 

This issue can be closed

**Comment by bahmutov** [comment]
@AlexLo33 we recommend using something like https://github.com/bahmutov/start-server-and-test to start and shutdown server after the tests complete, you can find a few examples in our https://on.cypress.io/ci guide as well
