### ISSUE TITLE
Launching custom Brave browser throws error in plugins (3.7.0)

### ISSUE THREAD

**Issue by pgroot91** [cypress-io/cypress#5848]
### Current behavior:

![image](https://user-images.githubusercontent.com/6934501/69969522-da107280-151c-11ea-94eb-b2d98cda1137.png)

See docs: https://docs.cypress.io/guides/guides/launching-browsers.html#Customize-available-browsers

### Desired behavior:

Tried specifying hard-coded path for simplicity, unable to make it to work browser launching with 3.7.0

**Using absolute paths:**

`C:\\Program Files (x86)\\BraveSoftware\\Brave-Browser\\Application`

**Using absolute paths mklink:**

`C:\\Users\\Patrick.DESKTOP-Q3EBHKB\\cypress\\browsers\\brave`

### Steps to reproduce: (app code and test code)

See docs of the example provided:

```js
// cypress/plugins/index.js
const execa = require('execa')
const findBrowser = () => {
  // the path is hard-coded for simplicity
  const browserPath =
    'C:\\Users\\Patrick.DESKTOP-Q3EBHKB\\cypress\\browsers\\brave'

  return execa(browserPath, ['--version']).then((result) => {
    // STDOUT will be like "Brave Browser 77.0.69.135"
    const [, version] = /Brave Browser (\d+\.\d+\.\d+\.\d+)/.exec(
      result.stdout
    )
    const majorVersion = parseInt(version.split('.')[0])

    return {
      name: 'Brave',
      family: 'chrome',
      displayName: 'Brave',
      version,
      path: browserPath,
      majorVersion
    }
  })
}

module.exports = (on, config) => {
  return findBrowser().then((browser) => {
    return {
      browsers: config.browsers.concat(browser)
    }
  })
}
```

### Versions

Cypress 3.7.0
Windows 10 Pro 10.0.18362 (Build 18362)
x64

**Comment by bahmutov** [comment]
Hmm, I am not sure why `<browser path> --version` does not work on your machine - does the command `... --version` work when you call it from the terminal?

**Comment by jennifer-shehane** [comment]
Make sure you're passing the correct path to the browser, I don't know exactly what it would be for Brave on Windows, but we look for locations with `.exe` for other Chromium browsers as noted here: https://on.cypress.io/debugging#Windows

**Comment by pgroot91** [comment]
* Its not only the Brave browser also tested with the EDGE Dev but it doesn't work in general for me. Also true the command line i have the exact same issues/errors. 

The only thing i can try to do later is test this on a fresh install again and see if that solves it for me or that i'm having the same exact issues once again. 

I haven't seen any reports from other users yet so maybe it's just me doing something wrong here.

**Comment by jeansordes** [comment]
I know it's sketchy, but I've found the following solution

```js
// cypress/plugins/index.js
const { promises: { readdir } } = require('fs')

const getDirectories = async source =>
  (await readdir(source, { withFileTypes: true }))
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name)

const findBrowser = async () => {
  const browserPath =
    'C:/Program Files (x86)/BraveSoftware/Brave-Browser/Application'

  const version = (await getDirectories(browserPath))[0]

  const majorVersion = parseInt(version.split('.')[0])

  return {
    name: 'Brave',
    channel: 'stable',
    family: 'chromium',
    displayName: 'Brave',
    version,
    path: browserPath + '/brave.exe',
    majorVersion,
  }
}

module.exports = (on, config) => {
  return findBrowser().then((browser) => {
    return {
      browsers: config.browsers.concat(browser),
    }
  })
}
```

**Comment by pgroot91** [comment]
I think this issue can be closed. We used the following:

```
module.exports = (on, config) => {
    config.browsers.push({
        name: 'brave',
        channel: 'stable',
        family: 'chromium',
        displayName: 'Brave',
        version: '99.1.36.116',
        path: 'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe',
        majorVersion: 99
    });
    
    return config;
}
```
