### ISSUE TITLE
Running all the suites for multiple dataset

### ISSUE THREAD

**Issue by nishant-sngl** [cypress-io/cypress#5856]
### Current behavior:
There is no way to run all the tests for multiple data sets

### Desired behavior:

Introduce a way to run all the specs with multiple data sets in a single trigger.

### Steps to reproduce: (app code and test code)

Say, i have 10 files. each having 5 tests. My application is client specific, where i need to test all my tests for all the clients. I need a way to run all the 10 files for all the clients in a single trigger.
I have gone through the ticket https://github.com/cypress-io/cypress/issues/2940.
As per the solution in this ticket is via groups, it seems that we need to run the scripts multiple times.
Is there a way to trigger it once, and it takes the data from fixtures or any config and then run the whole suite for all the clients.

One way is to loop all the desc/it in loop of data list, but that seems to be just a work around.
Please help here.

**Comment by jennifer-shehane** [comment]
As mentioned in the previous thread - this is possible by calling `cypress run` several times with different environment vars, configuration or whatever you like, so this is possible. The way you decide to run these scripts is completely up to you, whether you want to loop through several configuration files - all of this can be done in whatever setup you choose. 

You could also use the Module API to call cypress.run several times - each time with your configuration data set. https://on.cypress.io/module-api#cypress-run Again, the way you decide to loop through your configuration multiple times is up to you. 

Closing as this is possible, the calling of your configuration being outside the scope of the Cypress project on how you decide to call the scripts multiple times with the multiple data sets.
