### ISSUE TITLE
Hi, My application opens child window and want to perform some operation under child window page. I have used cy.window but it didnt worked. Can you please help.

### ISSUE THREAD

**Issue by yogesh-aknurwar** [cypress-io/cypress#5857]
### Current behavior:

My application opens child window which belongs to different domain, focus is not getting transferred. There were multiple work around given but all those works only when child windows open with same domain so that we can open that page in same parent window. I have used `chromeWebSecurity = 'false'` as well, but it didnt help.

Error - 
```
CypressError: cy.visit() failed because you are attempting to visit a second unique domain.

You may only visit a single unique domain per test.

Different subdomains are okay, but unique domains are not.

The previous domain you visited was: 'https://www.plus2net.com'

You're attempting to visit this new domain: 'null'

You may need to restructure some of your code to prevent this from happening.
```

### Desired behavior:

I want to handle child window and move focus from current to child so that automation can be performed.

### Steps to reproduce: (app code and test code)

This is the sample link which I have found with similar case.
https://www.plus2net.com/javascript_tutorial/window-parent.php

here, click on open child window. New window will get popped up. I have to click on Close Window under that child window.

Here is the sample code

```js
   it.only('Verify Child Window Clicked', function(){
      cy.visit('https://www.plus2net.com/javascript_tutorial/window-parent.php', { timeout: 100000 })
      cy.log("Application launched")
      cy.xpath("(//a[@name='My Window Name'])[1]").then(function(el)
     {
        const url=el.prop('href')
        cy.log(url)
        cy.log("Trying to visit child URL")
        cy.visit(url)
      // cy.request(url).should('have.attr', 'href')
        cy.log("Child URL Visited")
       // cy.request(url).its('body').should('include', '</html>')
        cy.xpath("//input[@value='Close this window']").click()
       // cy.xpath("//input[@id='sso-discovery']").type('testing@gmail.com')
   
      })
   }) 
```

### Versions

Cypress - 3.6.1
OS - windows 8.1

**Comment by yogesh-aknurwar** [comment]
Tried with this as well but didnt help.

onBeforeLoad(win) {
          cy.stub(win, 'open').as('windowOpen')
        }
 const child = cy.get('a').then(($a) => { var url = $a[0].getAttribute('href') })

    cy.log(child)
    cy.window().its('open').should('be.calledWith')
    })

**Comment by jennifer-shehane** [comment]
The code you have written is pulling out a `url` of `javascript:void(0)` which you are then calling `cy.visit()` on. This is why the error is throwing. It is telling you that you are visiting `cy.visit('null')` which is not of the same domain as the originally visiting url. 

Please a `debugger` in your test code to see. 

<img width="571" alt="Screen Shot 2020-01-02 at 2 03 01 PM" src="https://user-images.githubusercontent.com/1271364/71656194-c731cd80-2d68-11ea-96d2-90dabb5e1681.png">
