### ISSUE TITLE
Update/improve cy.type validation logic

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#586]
It appears fairly common that users need to type into an input that has an invalid *type* attribute (`type="STRING"`, `type="username"`), triggering the error `cy.type() can only be called on textarea or :text`. 

Here are two possible ways to improve the experience for this use case:

1. Allow validation to be bypassed with either `{ force: true}` or `{ validation: false }`. Also, improve the error message so it's clear what `:text` means and include details on how to bypass validation.

2. Instead of whitelisting input types, blacklist certain types instead (e.g. checkbox). This would provide a good error message if typing into something that's blacklisted, but allow users to type into inputs with types that aren't accounted for, just as a browser actually allows.

**Comment by GoupilRobin** [comment]
:+1:

**Comment by noah-potter** [comment]
Having a `{ force: true }` option would be great for our use case. We have a div listening for keyboard shortcuts such as `ctrl + b`, `ctrl + m`, etc. These are used to access power-user/admin windows. We're able to work around the issue by attaching these to the body, but ideally we would be able to force cypress to type into any element.

**Comment by jennifer-shehane** [comment]
`.type()` code can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/type.coffee#L23

**Comment by anocaj** [comment]
Is this something that will be edited? We are struggling to make cypress type into a paragraph that is inside a content editable div.
```
cy.type() can only be called on textarea or :text. Your subject is a: <p>...</p>
```

**Comment by patrickdorn** [comment]
Is there any kind of "workaround" or "dirty hack" available to bypass this issue until this is solved?

**Comment by Magneticmagnum** [comment]
My company is also exploring Cypress and wondering if this will be a feature that will be supported by the Cypress team in the future?

Our use case is similar to anocaj;  We want to simulate typing into a complex text editor that is a div.

**Comment by jennifer-shehane** [comment]
Yes, we do intend this to be done in the future, but currently it is not assigned to anyone. The code can be found here if anyone wants to begin a Work in Progress PR: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/type.coffee#L23

**Comment by vdsabev** [comment]
I have a similar use case with `<input type="color" />` - I couldn't find any command that would set its value properly, and assumed maybe `type` would work, as color inputs fall back to text inputs if the browser doesn't support them.

Excerpt from the docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color
> When a browser doesn't support a color picker interface, its implementation of color inputs will be a text box that validates the contents automatically to ensure that the value is in the correct format.

**Comment by Bkucera** [comment]
@Magneticmagnum that is not addressed by this issue...however we should already support typing into `div`s with attribute `contenteditable` .

**Comment by Bkucera** [comment]
This will be fixed by an upcoming patch release. It's really as simple us using the type property instead of type attribute. 
The type property of <input type="asdf"> is "text"

**Comment by wasiqkhan786** [comment]
nothing is working with cy.type when subject is not typeable.please create some solution.

**Comment by jennifer-shehane** [comment]
@wasiqkhan786 This issue has been resolved and there are tests against it. This issue will be closed to further comment. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
