### ISSUE TITLE
new fontawesome spinner icon is visually clipped in 3.8.0 prerelease

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#5863]
new fontawesome spinner icon is visually clipped

![19-12-03_13:55::50](https://user-images.githubusercontent.com/14625260/70080565-ca546500-15d4-11ea-97ed-1a5c4bd39f75.png)

introduced in: #5822

**Comment by jennifer-shehane** [comment]
This was released as part of 3.8.0
