### ISSUE TITLE
Cypress stays logged in between two tests (changed behavior b/w 3.6.1 and 3.7.0)

### ISSUE THREAD

**Issue by jkyuusai** [cypress-io/cypress#5867]
### Current behavior:
1. Cypress finishes a test.
2. Cypress starts the next test, visiting the root of the app as the first step.
3. Cypress lands on the admin screen of the app, already logged into the app.

<img width="1677" alt="Screenshot 2019-12-03 18 25 30" src="https://user-images.githubusercontent.com/667921/70107069-57f67b80-15fa-11ea-97bf-dad985779dad.png">

### Desired behavior:
1. Cypress finishes a test.
2. Cypress starts the next test, visiting the root of the app as the first step.
3. Cypress lands on the login screen of the app.

### Steps to reproduce: (app code and test code)
I have spent a few hours trying to build a reproducible test case I can share. I can 100% reliably reproduce it on my computer's local development instance of our application, but I cannot reproduce it on a publicly accessible instance. I think part of the bug is tied to Cypress config options that are only applicable to the local instance anyway, which is probably why I couldn't reliably repro it there, however, I believe I did see it happen sporadically on a non-local instance of the app.

Having said that, here is the test case I used to repro it against my local app: https://github.com/jkyuusai/cypress-test-tiny

To repro, I run the spec file as is through the Cypress Runner GUI.

When I run the spec file, the first spec passes, then the second spec starts, but after the `cy.visit("/")`, it's already logged into the app.

Every line in the first spec is necessary to get the undesired behavior in the second spec. If I remove the `cy.request('/')` from the first spec, the second spec lands on the login page. Same if I remove the `cy.visit('http://my.conversa.local...')` after the request, or if I remove the `cy.contains(/choose a color/);`. I had replaced the `contains` with a `wait` of a few seconds and that also worked. I think the actual important part is that the loading of the page from `cy.visit('http://my.conversa.local...')` must complete before the first test is exited to trigger the undesired behavior in the second test.

I have found two separate ways to make the spec above have the desired behavior instead of the undesired behavior:
- Downgrading Cypress from 3.7.0 to 3.6.1
- Removing `"chromeWebSecurity": false` from `cypress.json`

Note that either one of those two by themselves will stop the spec from producing the undesired behavior. So, for instance, I can use 3.7.0, as long as I remove the `"chromeWebSecurity": false`. Or, I can keep `"chromeWebSecurity": false`, but I have to downgrade to 3.6.1.

My plan for now is to hang out at 3.6.1 for a bit (since I think I was still seeing this happen on CI after upgrading, sporadically) and to also remove `"chromeWebSecurity": false`, as I don't think I actually need it for our app at this point after all (this was an early addition to the file when I was still working domain stuff out). I wanted to go ahead and file this though, since me being able to "fix" it by downgrading Cypress seemed to indicate there might have been a bug introduced .

### Versions
Cypress 3.7.0
macOS Mojave 10.14.6
Chrome 78

**Comment by vbrundic** [comment]
If I'm not mistaken, you're trying to log in again inside the same test set, so clearLocalStorage is never called. See https://docs.cypress.io/api/commands/clearlocalstorage.html#Syntax for details, you can use cy.clearLocalStorage() with beforeEach if you need to log in / log out multiple times inside the same test.

**Comment by jkyuusai** [comment]
You are mistaken. I'm not trying to log in twice in a single test. That's not what I described in my repro steps, and it's not the code that's in the repo I linked. Cypress clears state between each `it`. You'll see in the first image I linked - it's running the second `it` and the very first action is a visit to the root of the app, and it's already logged in. This is a run from the reproduction repo I linked against my local environment.

The second image is slightly different, as it's a shot from the CI run on a remote environment using our actual cypress specs. What you're seeing in that log is it firing a chain of login related commands that decide how to login, and it decided that it needed to login through the UI. It tries to find the user_email input on the login page and fails, because it's already authenticated, even though it's at the very start of a new `it`.

**Comment by sainthkh** [comment]
The urls provided in the example, http://clinic.conversa.local/,  http://conversa.local/, http://my.conversa.local/, are unreachable. Can you change the link with the working one? Otherwise, we cannot help closing this issue.

**Comment by jkyuusai** [comment]
I put in a fair amount of effort on this ticket 13 months ago and was ignored. It's kind of amazing you would actually reply after this much time and tell me to address something in the report and not even acknowledge that y'all just straight up ignored the ticket for so long. I don't even work at that company anymore and don't have access to those apps.

**Comment by jennifer-shehane** [comment]
@jkyuusai Sorry for the delay in response and sorry that we couldn't respond to your issue sooner. @sainthkh is just trying to help out with any issues that haven't been resolved.

**Comment by jkyuusai** [comment]
My apologies for being snippy last week, wasn't in a good headspace.
