### ISSUE TITLE
Cypress is clearing a field when trying to get another field in 3.5.0

### ISSUE THREAD

**Issue by jpike88** [cypress-io/cypress#5868]
Cypress version 3.7.0
Happens on both chrome and electron 
```js
cy.get('#phone-field')
  .clear()
  .type('1234567');
```

![Screen_Shot_2019-12-04_at_10 48 18-2](https://user-images.githubusercontent.com/9585787/70111241-317d2280-1684-11ea-9c21-37a6dd71546b.png)

We place a dummy text field as the first field in our dialog (with title 'OK'), and give it an initial value of 'abc'.

When the dialog shows, the above cypress code is used to fetch the phone field, clear it, type a value. This happens fine, but the top field is cleared just beforehand.

This clearing behaviour is definitely tied to this line of cypress code. It was working on Cypress 3.4.1, 3.5.0 breaks like crazy for a bunch of other reasons, and this issue also exists on 3.6.1

**Comment by jpike88** [comment]
temporarily resolved with a workaround, where we manually fill the field back in before proceeding:

```
cy.get('#ok-field')
            .type('test@email.com'); 
```

**Comment by jennifer-shehane** [comment]
@jpike88 Can you provide the html of the form and any necessary css please? We need the test code as well as the html to run it against, ideally a test visiting a simple `index.thml` page. Thanks.

**Comment by jpike88** [comment]
That's hard to do as our app uses angular, seems like dumping it to static files won't do the job. If I gave you a demo account and showed you where the dialog of interest is would that be ok?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example and we will consider reopening the issue.
