### ISSUE TITLE
Log Java Script to Dev tools Command Line

### ISSUE THREAD

**Issue by M-Kamenzin** [cypress-io/cypress#5874]
### Current behavior:

Java Script Code is not executed in the Developer tools Command line

### Desired behavior:

I want to automate a test that requires me to type and execute commands in the console in the Chrome Developer tool:

The goal is to trigger PopUps with these commands
I tried different ways, but every time, the report says everything is fine, but nothing happened
When i tried by my own it works perfectly

### Steps to reproduce: (app code and test code)

```
Try 1:
console.log("...")

Tray 2:
cy.window().then((win) => {console.log("...")
       })

Try 3:
cy.task('log', '...)')
```

### Versions

Chrome 78.0.3904.108
Cypress 3.6.1

**Comment by M-Kamenzin** [comment]
With this code the command is issued but not executed:

console.log("service.popup.requestPopup (service.popup.Popups.POPUP_17_pop__Update_error_1.id)")

**Comment by M-Kamenzin** [comment]
I found out a work arround with Python:

`from selenium import webdriver
import time
driver = webdriver.Chrome('...my Path...')
driver.get('....my Webpage....)
driver.maximize_window()
popup_befehl = 'debuggingService.popups.requestPopup(debuggingService.popups.PopupsPOPUP_Update_error_1.id)'
time.sleep(2)
driver.execute_script("document.body.style.zoom='75%'")
time.sleep(10)
driver.execute_script(popup_befehl)`

**Comment by jennifer-shehane** [comment]
@M-Kamenzin You can tab into the Chrome Remote Interface, although there is not a unique API built into Cypress to achieve this. Here is an example someone wrote up of some things you could do. https://github.com/cypress-io/cypress-example-recipes/pull/384/files
