### ISSUE TITLE
Mistype at FAQ-General Question page

### ISSUE THREAD

**Issue by teddorian** [cypress-io/cypress#5877]
Current behavior:
![General_Questions___Cypress_Documentation](https://user-images.githubusercontent.com/39402350/70149769-79ff0500-16b1-11ea-9868-b3e37b383838.jpg)

Desired behavior: correct is  - rewrite

Steps to reproduce:

1. open https://docs.cypress.io/faq/questions/general-questions-faq.html#Do-you-support-native-mobile-apps
2. scroll down to subtitle - When should I write a unit test and when should I write an end-to-end test? - 4th bullet point

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to the Cypress App. If you want to open an issue on our documentation project, you can open it [here](https://github.com/cypress-io/cypress-documentation/issues/new). This issue will be closed in this repository.

**Comment by teddorian** [comment]
ok, thanks
