### ISSUE TITLE
Access stub server from server side rendering

### ISSUE THREAD

**Issue by phzimmermann** [cypress-io/cypress#588]
- Operating System: OSX
- Cypress Version: 0.13.1
- Browser Version: 59.0.3071.115

### Is this a Feature or Bug?
Question

### Current behavior:
We have a react app with server side rendering enabled. The underlaying node server uses the same API as the client does. As expected, starting cy.server() only mocks the client calls.

### Desired behavior:
Is there an url to the cy.server(), that we could set to our node server, to use the same mocks as the client does?

**Comment by brian-mann** [comment]
Server side rendering is happening in a completely isolated process that only you control - and could not be affected or injected by Cypress. Cypress works at the network proxy layer, and unless this request is going over the network it's impossible to access or modify.

What you should likely do is disable server side rendering when testing in Cypress (if you want to be able to stub things via the network).

Another option is to write your own code to stub out the server side rendering but still using Cypress fixtures. It's completely up to you to implement this though - maybe with the use of `cy.exec` or booting your server in a specific mode, or maybe using something as simple as query params in the URL.

**Comment by luujam1** [comment]
> Another option is to write your own code to stub out the server side rendering but still using Cypress fixtures

Could you explain this please?
From what I understand it sounds like an HTML fixture would be used which would fake the server side rendered HTML. Then we could do something like this:

```
cy.server();
cy.fixture('server-side-rendered.html').then(html => {
      cy.route('http://your-page.com', html); //can't return HTML from a mock
      cy.visit('https://your-page.com');
});
```

**Comment by kylemh** [comment]
Is there anyway for me to force my app and Cypress to use the same network?
