### ISSUE TITLE
It's not possible install cypress in Windows 7 machine

### ISSUE THREAD

**Issue by nonum** [cypress-io/cypress#5887]
### Current behavior:

I tried install cypress (any version) in Windows 7 and I have an error during the installation. When cypress try to unzip the package the console give me an error.

![image](https://user-images.githubusercontent.com/5755213/70238754-39af8d80-176a-11ea-9fd4-3be398b33bde.png)

I think it is a problem with 'radnomstring' installed in the cypress.zip. This library has a '.empty' file that it is not possible decompress by Windows 7 because Windows think that it is a file with permissions.

### Steps to reproduce: (app code and test code)

npm install cypress

### Versions

Cypress 3.7.0
Windows 7 Enterprise

**Comment by ayandebbarman** [comment]
i have been using 3.4.1 for few months now in windows 7 didn't face any issue .. i don't think its a general but but something specific to the machine

**Comment by jennifer-shehane** [comment]
Try to clear the cache as explained here: https://docs.cypress.io/guides/guides/command-line.html#cypress-cache-clear 

Otherwise we will need more information. Cypress can be installed in Windows for most users so it is something specific to your system.
