### ISSUE TITLE
cy.location('pathname') throws an error, claiming not having a pathname key

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#589]
### Current behavior: 

When using `cy.location('pathname')` , asserting throws error. 

assertion looks like this:
```js
cy.location('pathname').should("eq", `/onboarding/name`)
```

error:
```CypressError: Location object does not have key: pathname```

fyi: writing out assertion with function works no problem:

```js
cy.location().should(function(location){
  expect(location.pathname).to.eq('/events')
})
```

### Desired behavior:
Should not throw error, when trying to use `cy.location('pathname')`

### How to reproduce:
in this particular case, the assertion comes right after redirect after login

### Additional Info (images, stack traces, etc)
looks like this. you can see the test does not wait for path change and throws an error.

<img width="418" alt="screenshot 1" src="https://user-images.githubusercontent.com/23213553/29189779-17ece384-7e18-11e7-9f9b-d3c62d856bbe.png">
<img width="450" alt="screenshot 2" src="https://user-images.githubusercontent.com/23213553/29190002-d84a2c86-7e18-11e7-9e4e-b601970794cd.png">

**Comment by andezzat** [comment]
I'm having this issue as well.

What's most interesting is that it's not consistent, however, it ONLY occurs with the `cypress run` command.
Regardless of whether it is run normally or with the `--headed` flag, it will happen 70-80% of the time, and is causing my tests to needlessly fail...
I cannot understand why or what the difference between running this via `cypress open` or just `cypress run` is. Even though I'm using Electron 57 for `cypress open`...

**Comment by leandrokanis** [comment]
It works with cy.window()

```
        it('signs in to backoffice', () => {
          cy.window().then((win) => {
            expect(win.location.pathname).to.equal('/backoffice')
          })
        })
```

**Comment by Vandivier** [comment]
issue replicated doing like:
`cy.location('pathname').should($pathname =>`

**Comment by sainthkh** [comment]
Tried to reproduce the problem, but failed. 

You can see the failed attempts here. 

* [Adding tests](https://github.com/sainthkh/cypress/pull/1)
* [Checked login recipes, but all works.](https://github.com/cypress-io/cypress-example-recipes/pull/364)

If anyone encounters with this problem, please leave an example code/project that fails.

Thanks.

**Comment by Kokogino** [comment]
It doesn't work for me either. I'm on version 3.8.0 and this is my code:
```
cy.location().then((loc) => {
	cy.visit('#' + loc.pathname + '/whatever');
});
```

The resulting url is `http://host.docker.internal:4200/#//whatever`.
I'm running the test on a docker container, but that shouldn't matter.
But `location.href` is fine.

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment with a completely reproducible example if you are still having this issue and we will consider reopening.
