### ISSUE TITLE
Take screenshots using Chrome DevTools Protocol 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#5899]
### Current behavior:

Cypress screenshot algorithm is complicated and has introduced several challenges.

- Cypress doesn't take correct snapshots in 'fullPage' mode in Electron and Chrome browsers https://github.com/cypress-io/cypress/issues/5876
- Screenshot of webGL content does not render anything https://github.com/cypress-io/cypress/issues/5792
- Chance of race condition when using screenshot() https://github.com/cypress-io/cypress/issues/3276
- Screenshot "scroll and stitch together" functionality does not play nicely with React Single Page Apps https://github.com/cypress-io/cypress/issues/2681
- Full page screenshots are not rendering as expected https://github.com/cypress-io/cypress/issues/2348

### Desired behavior:

Now that #4628 is merged, Cypress has access to Chrome's Debugger Protocol which could be used to take screenshots. 

Page.captureScreenshot docs: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot

### Challenges

- This would only be usable in Chrome browser and not extensible to other browsers, so we would have to maintain the other screenshot algorithm anyway unless there are comparable substitutions for other browsers.

### Versions

3.7.0

**Comment by mikila85** [comment]
Fix this already!!!

**Comment by flotwig** [comment]
@mikila85 You are welcome to open a pull request if you need this quickly. You will want to start with the handler for `take:screenshot` in `cdp_automation.ts`. Let us know if you have any questions.

**Comment by ThomasGHenry** [comment]
Hey, folks. What's the lowest overhead alternative to this in the meantime? Would anyone recommend a workaround? Thanks

**Comment by flotwig** [comment]
@ThomasGHenry Does [`cy.screenshot()`](https://docs.cypress.io/api/commands/screenshot.html) not work for you? This issue is about changing the internal implementation of screenshots, so there's not really a workaround for it.

**Comment by ThomasGHenry** [comment]
Thanks, @flotwig.

It does not. I'm experiencing this https://github.com/cypress-io/cypress/issues/5876

I'm wondering if anyone recommends a 3rd party option that plays nicely with cypress in the meantime. Cloud-based solutions like Percy and Applitools aren't ideal. Anything else I've found so far uses `cy.screenshot()` under the covers. Thanks!

**Comment by flotwig** [comment]
@ThomasGHenry Might have to wait to use `--headless` until #5876 is fixed, I'm not sure if there are any 3rd-party screenshot tools for Cypress.

---

With regard to this issue - @jennifer-shehane I think we actually are already taking screenshots using CDP in Chrome and Electron since 3.5.0:

https://github.com/cypress-io/cypress/blob/719fd98b15bf1382d795c86cb45030fa417053c9/packages/server/lib/browsers/cdp_automation.ts#L170-L177

So closing this... oops :sweat_smile:
