### ISSUE TITLE
cy.server will not mock requests after the 1st test when used prior to cy.visit

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#59]
When multiple tests run the same beforeEach hook and use `cy.server` before a `cy.visit` only the 1st test mocks the server.

If the `cy.server` call is moved out of a `beforeEach` hook it will work, or if `cy.server` is invoked **after** a `cy.visit`.

This is due to a bug in the way Cypress juggles the server prior to a `cy.visit` happening.

**Comment by tomatau** [comment]
Any ETA on a minor update for this?

**Comment by brian-mann** [comment]
Fixed in [`0.11.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0111-09142015).
