### ISSUE TITLE
Unable to Detect 'disabled' Attribute in <a /> Tag

### ISSUE THREAD

**Issue by natejcho** [cypress-io/cypress#5903]
### Current behavior:

running cy.get().should('be.disabled') on an <a /> will return false, even when attr exists.

### Desired behavior:
should return true, when disabled. This works for <button /> tag.

### Steps to reproduce: (app code and test code)

`<a data-cy="test" disabled />`

`cy.get([data-cy=test]).should('be.disabled')` => will fail

### Versions
cypress@3.4.1
react@16.9.0

**Comment by gabbersepp** [comment]
I think `be.disabled` relates to chaiJS
see: https://docs.cypress.io/guides/references/assertions.html#Chai-jQuery
And the official chaiJS docu refers to jquerys `:disabled` selector which indeed does not check for the existence  of the `disabled` attribute:

![image](https://user-images.githubusercontent.com/3234900/70353423-9b0c5500-186d-11ea-89e3-fe4f09fcbcce.png)

As you can see, the `a` tag is not supported by this assertion.

**Comment by natejcho** [comment]
it goes deper actually 

https://stackoverflow.com/questions/13955667/disabled-href-tag/13955695

Not cypress's fault at all. Though it would be nice if there was support for this. <a /> has no support for disabled, but it will still be displayed in the DOM as an html attribute, since additional logic can be built around it still.

**Comment by pastorga-gap** [comment]
Im having the same issue with a div element

`<div class="ag-filter-select" disabled="">`

so Im using something like: 

`cy.get('.ag-filter-select').should('be.disabled');`

Does anyone found a workaround?

**Comment by pastorga-gap** [comment]
I found this way cy.get('.ag-filter-select').should('have.attr', 'disabled', 'disabled') and it works.

**Comment by jetlinds** [comment]
I also had the same issue. cy.get().should('be.disabled') returned false when attr is disabled.

but it works in this way:

```
cy.get().should('have.attr', 'disabled');
cy.get().should('not.have.attr', 'disabled');
```
