### ISSUE TITLE
Trying to open URL "https://develop.gocoderz.com" using cypress get command and getting security error

### ISSUE THREAD

**Issue by nireini** [cypress-io/cypress#5907]
### Current behavior:

Trying to open URL "https://develop.gocoderz.com" using cypress get command and getting error.

I tried to Disabling Web Security But it didn't help.

This is the error I am getting - SecurityError: Blocked a frame with origin "https://develop.gocoderz.com" from accessing a cross-origin frame.

![14](https://user-images.githubusercontent.com/29025071/70370781-39cb9c80-18d4-11ea-894c-8d6f0d9a656a.png)
![14](https://user-images.githubusercontent.com/29025071/70370785-48b24f00-18d4-11ea-82ca-e164390a2dfa.png)

### Desired behavior:

Website should be opened without error

### Steps to reproduce: (app code and test code)

Trying to open URL "https://develop.gocoderz.com" using cypress get command and getting error

### Versions
O.S - Windows
Browser - Chrome
Cypress version - 3.4.1

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this issue in Cypress 3.8.1. 

Please update to the [current version of Cypress](https://on.cypress.io/changelog) and provide ALL configuration on your project include any support, plugins, cypress.json and we will consider reopening. Thanks!

```js
  it('visits a page', () => {
    cy.visit('https://develop.gocoderz.com');
  });
```

![Screen Shot 2020-01-02 at 1 25 06 PM](https://user-images.githubusercontent.com/1271364/71655077-99965580-2d63-11ea-8bfd-40fb8f721e64.png)

**Comment by nireini** [comment]
Hi

There is no issue

I didn't modify the correct JSON configuration file.
