### ISSUE TITLE
file name contains character ”+“ not run

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#5909]
the file `cy_web+_20191207220608.js` is exsite, but run cypress, 

```
Cannot find module web _20191207220608.js, this character ”+“  instead of " ", so not find the file.
```

### Current behavior:
```
  │ Cypress:    3.7.0                                                                              │
  │ Browser:    Electron 73 (headless)                                                             │
  │ Specs:      1 found (web+_20191207220608/web+_20191207220608.js)                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  web+_20191207220608/web+_20191207220608.js                           (1 of 1)

Oops...we found an error preparing this test file:

  /home/admin/cypress/web _20191207220608/web _20191207220608.js

The error was:

Error: Cannot find module '/home/admin/cypress/web _20191207220608/web _20191207220608.js' from '/home/admin/cypress'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-158) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Yes, confirmed. Specfiles with `+` character do not run in Cypress. 

The error seems to print the filename with the `+` character replaced with a ` ` character.

My file was at `cypress/integration/foo+bar.js`

![Screen Shot 2019-12-24 at 2 35 24 PM](https://user-images.githubusercontent.com/1271364/71402213-af689400-265a-11ea-88d0-04894e3edd50.png)

**Comment by emchoi7** [comment]
Could I take a look at this, if nobody else is already?

**Comment by jennifer-shehane** [comment]
@emchoi7 Sure

**Comment by jennifer-shehane** [comment]
Reopening as this is still an issue.

**Comment by jennifer-shehane** [comment]
The code for this is done in [cypress-io/cypress#8015](https://github.com/cypress-io/cypress/pull/8015), but has yet to be released.

We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
