### ISSUE TITLE
Unable to auth through GitHub login using UTF Security Key

### ISSUE THREAD

**Issue by luketlancaster** [cypress-io/cypress#591]
- Operating System: macOS 10.12.6
- Cypress Version: 0.19.4
- Browser Version: Chrome 60.0.3112.90

### Is this a Feature or Bug?
Bug

### Current behavior:
Trying to login through GitHub with a FIDO U2F Security Key configured for the account causes "something to go really wrong"

### Desired behavior:
Successful auth through GitHub

### How to reproduce:
Attempt to login to GitHub

### Additional Info (images, stack traces, etc)

<img width="986" alt="screen shot 2017-08-12 at 5 15 13 pm" src="https://user-images.githubusercontent.com/8376505/29244651-0569f2bc-7f83-11e7-86af-b4f96adefd13.png">

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/1162
