### ISSUE TITLE
Rufus can't select ISO image win7

### ISSUE THREAD

**Issue by cyberb13** [cypress-io/cypress#5911]
Rufus can't see the ISO image I downloaded. How to fix this.  I've done it before and it worked, but when I try this time Rufus and universal USB installer do not detect the ISO it's only show boot, source and support files that can't be selected,

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
