### ISSUE TITLE
if chaining .clear() with .type(), do not issue 'blur', 'click', etc to input in between

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#593]
- Operating System: Mac
- Cypress Version: 0.19.4
- Browser Version: Chrome

### Is this a Feature or Bug?
Enhancement

### Current behavior:
If I write a test:

```js
cy.get('input').clear().type('Jane')
```

After the `.clear()`, Cypress blurs off the input, then attempts to click back onto the input at the beginning of the `type`. 

These events firing can cause some unexpected results when I'm essentially expecting the caret to clear the input and stay in the input to then type. 

### Desired behavior:

If `.clear()` is followed with `.type()`, keep the caret in the input and do not fire the events to blur the input after clear and click on the input at the start of type.

**Comment by Bkucera** [comment]
@jennifer-shehane I'm currently working on this. An upcoming patch release should fix this issue
