### ISSUE TITLE
Authentication events for plugins

### ISSUE THREAD

**Issue by bjowes** [cypress-io/cypress#5935]
### Current behavior:

Plugins cannot interact with the http traffic through the plugin API. The only way to build a authentication plugin today is by using an external proxy process.

### Desired behavior:

A plugin API for authentication. 
#### auth-request event
In essence there would need to be an "auth-request" event in the plugin API, which is triggered when Cypress receives a 401 response with a `www-authenticate` header. The API call should pass at least the following arguments:
* content of the `www-authenticate` header (or headers) 
* client endpoint (at least port)
* server endpoint (hostname, protocol, port, path)

The auth plugin should then return the content for an `authorization` header to be used in the next request to the server. Cypress should then resend the previous request with this new header set. If the auth cycle is complete (non 401 response), all is well. If not, another call to the auth plugin may be required. (Some protocols require just one rountrip while others require two roundtrips).
The auth plugin could also return null if it does not support the required authentication protocol. 

#### auth-free event
To allow the plugin to clean up authorization states, there should be an additional "auth-free" event, which should be called when the client socket is destroyed. 

#### Auth method registration
A possible addition could be that the plugin should register which authentication methods it supports during initialization. This would simplify a scenario where multiple auth plugins are used simultaneously to cover different methods.

#### Benefits
As the developer of the NTLM authentication plugin [cypress-ntlm-auth](https://github.com/bjowes/cypress-ntlm-auth) I see many benefits with the suggested auth plugin API.
* No external proxy would be required to deal with authentication
  - greatly reducing the complexity for developers to develop authentication plugins
  - better performance
* Cypress is aware that authentication is performed
* An auth plugin could be used also for proxy authentication

#### Help needed?
If this suggestion makes sense to you, I would be happy to assist in making it happen.

### Steps to reproduce: (app code and test code)

No reproduction, this is a feature request.

### Versions

All versions, All OS, All browsers

**Comment by flotwig** [comment]
Hey @bjowes, did you see this issue I opened describing something similar? https://github.com/cypress-io/cypress/issues/4670

**Comment by bjowes** [comment]
Hi @flotwig, I had not seen that issue. Did a preliminary search before posting, but didn't come across that one. 

I agree, the concept of #4670 looks promising and could be extended to support my suggested auth plugin API! Actually, if the APIs behind #4670 were in place, the schema variants could be provided by plugins and wouldn't have to be developed by Cypress internally. Some of them are trivial but NTLM is not (if you want to be compliant with modern servers).  

What I'm missing in #4670 for the schema.raw variant to be usable for plugins, there is some state information required by some methods when authentication is performed in multiple steps. That is why I added client endpoint, server endpoint to the auth-request event and also the auth-free event.

Secondly, to support SSO a node environment is required for native calls. So the schema must be able to execute in the node space (not only browser space) to make this possible.

**Comment by jennifer-shehane** [comment]
Closing since there has not been a lot of interest in this over the years.
