### ISSUE TITLE
Missing XHR in the cypress log

### ISSUE THREAD

**Issue by joszo** [cypress-io/cypress#5939]
### Current behavior:

When I run tests in the window there is no XHR visible to me, I cannot easily debug with request/response feature. 

<img width="311" alt="Screen Shot 2019-12-12 at 12 56 48 PM" src="https://user-images.githubusercontent.com/32454314/70710421-70902100-1cdf-11ea-994a-69fd979e210a.png">

Networks:

<img width="360" alt="Screen Shot 2019-12-12 at 12 58 11 PM" src="https://user-images.githubusercontent.com/32454314/70710439-78e85c00-1cdf-11ea-81f8-c022b14e8c91.png">

### Desired behavior:

I would like to  see those XHR in my application to use wait('@request')

### Versions
3.7.0
Macos

**Comment by bahmutov** [comment]
The network requests your web application is making are using `fetch` and not `XMLHttpRequest` method, which Cypress currently does not "see" - read https://on.cypress.io/network-requests for the warning. We will support spying and stubbing `fetch` when we finish full network stubbing epic
