### ISSUE TITLE
Cypress config object passed to the plugins file should have config filename

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#5941]
Cypress v3.7.0

The plugins file receives resolved config object with properties from `cypress.json` resolved. But the config object has plugins, fixtures, integration paths - yet it does not have the project root or configuration filename. Since we have added `--config-file` option, we should pass it in the config object (or `false` is the user has disabled it)

See https://docs.cypress.io/guides/guides/command-line.html#cypress-run-config-file-lt-config-file-gt

Expected behavior with the following plugins file

```js
module.exports = (on, config) => {
  console.log(config.configFile)
}
```
```
$ cypress run
cypress.json
$ cypress run --config-file false
false
$ cypress run --config-file my-config.json
/resolved/path/to/my-config.json
```

**Comment by bahmutov** [comment]
Relevant for https://github.com/bahmutov/cypress-extends-example

**Comment by jennifer-shehane** [comment]
Yah, I thought this was a bit weird too when I began investigating https://github.com/cypress-io/cypress/pull/5855 It's a weird edge case config just like `browsers` and should probably follow the same implementation as that value.
