### ISSUE TITLE
Update cypress docker images automatically on release

### ISSUE THREAD

**Issue by alexbrazier** [cypress-io/cypress#5950]
### Current behavior:

Cypress docker images are behind the cypress release
See the tags for `cypress/included`: https://hub.docker.com/r/cypress/included/tags
Currently the latest is `3.7.0`, but `3.8.0` was released yesterday

### Desired behavior:

An automated build should be setup to build the new docker images as soon as a release is cut

### Versions
3.8.0

**Comment by alexbrazier** [comment]
Just seen the images are managed from this repository https://github.com/cypress-io/cypress-docker-images/pull/184

**Comment by jennifer-shehane** [comment]
@alexbrazier I merged in the docker-images PR now. I fully agree and have been advocating automating this for the last few releases.

**Comment by alexbrazier** [comment]
> @alexbrazier I merged in the docker-images PR now. I fully agree and have been advocating automating this for the last few releases.

Perfect, thanks for the fast response @jennifer-shehane

**Comment by aelmekeev** [comment]
@bahmutov , is this something you can look at?

**Comment by bahmutov** [comment]
sure, I am all for it, just don't have time to figure out how to do this

**Comment by bahmutov** [comment]
I am thinking a webhook registered with NPM that gets notified on a new release that opens a pull request with new included folder? But then when does it get built - on merge to master? and pushed? Have to figure out how to build an image but only the new one
