### ISSUE TITLE
Can't start server - "Expected majorVersion to be a string or positive number"

### ISSUE THREAD

**Issue by adworacz** [cypress-io/cypress#5961]
Possibly related to? https://github.com/cypress-io/cypress/pull/5068
### Current behavior:
Command: `npx cypress open`

cypress.json
```
{
    "baseUrl": "http://localhost:3000"
}
```

integration/home_page_spec.ts
```
describe('The Home Page', function() {
  it('successfully loads', function() {
    cy.visit('/')
  })
})
```

Result:
![Screenshot from 2019-12-13 17-00-34](https://user-images.githubusercontent.com/561689/70840845-2c2d7f80-1dca-11ea-801b-9f04acd0785b.png)

### Desired behavior:
For Cypress to open without error, in order to run my tests.

### Steps to reproduce: (app code and test code)
1. Run Linux (Ubuntu 18.04.3 LTS)
1. `npm install -D cypress @bahmutov/add-typescript-to-cypress eslint-plugin-cypress`
1. `npx cypress open`

### Versions
Cypress version: 3.8.0
Ubuntu 18.04.3

`apt show chromium-browser`
```
Package: chromium-browser
Version: 78.0.3904.70-0ubuntu0.18.04.2
```

**Comment by bahmutov** [comment]
What is the output of chromium-browser —version ?

**Comment by adworacz** [comment]
Chromium 78.0.3904.70 Built on Ubuntu , running on Ubuntu 18.04

**Comment by bahmutov** [comment]
Can you paste exactly the output from version command running in the terminal, please?

**Comment by adworacz** [comment]
```
u662b1ab6f1175f % chromium-browser --version
Chromium hook launcher starting up
run-parts: executing /usr/lib/company/chrome-hooks/00company-chrome-certs
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Notice: Trust flag u is set automatically if the private key is present.
Chromium hook launcher finished
Using PPAPI flash.
Chromium 78.0.3904.70 Built on Ubuntu , running on Ubuntu 18.04
```

**Comment by bahmutov** [comment]
Right, so this particular installation of Chrome is very weird - normally a browser shows pretty succinct version which we parse to get version. We cannot parse the output here and get “hook” instead of the version and undefined for major. You can add this browser via custom in the plugins file yourself and remove other chrome browsers

**Comment by adworacz** [comment]
Hmmm, I'll give that a shot, presumably following the example here:
https://github.com/cypress-io/cypress-example-electron/blob/master/cypress/plugins/index.js

Will have to be careful about doing this though, since I'm going to be sharing this configuration with my team, which is running a combination of Linux/Windows/Mac laptops, and I can't just blow away "good" configuration.

**Comment by bahmutov** [comment]
Ok if this is the case just for your setup you can add an alias or shell script with Chrome name that just returns the version string to be parsed.

**Comment by adworacz** [comment]
> Ok if this is the case just for your setup you can add an alias or shell script with Chrome name that just returns the version string to be parsed.
> […](#)
> Sent from my iPhone
> On Dec 13, 2019, at 20:40, Austin Dworaczyk Wiltshire ***@***.***> wrote: ﻿ Hmmm, I'll give that a shot, presumably following the example here: https://github.com/cypress-io/cypress-example-electron/blob/master/cypress/plugins/index.js Will have to be careful about doing this though, since I'm going to be sharing this configuration with my team, which is running a combination of Linux/Windows/Mac laptops, and I can't just blow away "good" configuration. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Hmm okay, thank you for the suggestion, I'll give that a shot.

**Comment by jennifer-shehane** [comment]
@bahmutov is there any action that should be taken in Cypress code to handle this? Trying to followup on the status of this issue.

**Comment by adworacz** [comment]
Solution:
Since my company appeared to write a wrapper around my `chromium-browser` binary, I manually edited the wrapper (which was a simple Bash script), and removed the use of the words "Chromium" for their custom status messages.

Example:
```sh
echo "Chromium hook blah blah"
...custom logic...
echo "Chromium hook foo foo"
/path/to/real/chromium-browser
```

Becomes
```sh
echo "Company hook blah blah"
...custom logic...
echo "Company hook foo foo"
/path/to/real/chromium-browser
```

You can consider this resolved from my end. I leave the decision up to the developers to decide if they want to improve the version parsing code to handle this use case better.

**Comment by bahmutov** [comment]
Nice, thank you @adworacz for fixing this, yeah we really expect the plain browser version - this is how we plan to detect the browser and display it, thus we need the right text. Since this is so rare, I will close this for now. If more people hit this problem, we could revisit it
