### ISSUE TITLE
UnExpected error, Some recourses are not getting loaded. As per log GET /__/img/no-spec-instructions.png  returns 404

### ISSUE THREAD

**Issue by Santosh-src** [cypress-io/cypress#5964]
### Current behavior:  

Cypress unexpectedly Stops execution and returns "Whoops, there is no test to run". As per the Cypress execution logs, I notice some resource was not found. Pls find the logs
Logs : 

```
GET /__cypress/runner/cypress_runner.css 200 2.102 ms - -
GET /__cypress/runner/cypress_runner.js 200 1.454 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2 200 1.019 ms - 77160
#### GET /__/img/no-spec-instructions.png 404 280.884 ms - -
```

What might be the root cause? Someone help me out.

### Versions
CY: 3.6.1
Chrome: 79

**Comment by santu12ec** [comment]
![Screen Shot 2019-12-16 at 11 23 12 AM](https://user-images.githubusercontent.com/17429530/70882656-73985380-1ff6-11ea-88aa-e860c4427b52.png)

**Comment by jennifer-shehane** [comment]
The most likely cause is this issue: https://github.com/cypress-io/cypress/issues/3121

Please comment in the other issue. Will be closing this issue.

**Comment by Santosh-src** [comment]
This issue resolved after modifying Configuration  to "modifyObstructiveCode: true" from initial "modifyObstructiveCode: false".

**Comment by saurabhp-onit** [comment]
@Santosh-src how/where did you modify that configuration

**Comment by jennifer-shehane** [comment]
You can set this in your `cypress.json` file. More info here: https://on.cypress.io/configuration#modifyObstructiveCode
