### ISSUE TITLE
Chrome headless fails with "Error: could not find CRI target"

### ISSUE THREAD

**Issue by marmite22** [cypress-io/cypress#5966]
### Current behavior:

I'm running the command `node_modules/.bin/cypress run -b chrome --headless -s './cypress/integration/003_website_settings/01_init.js'` (the path to the test is not relevant)

I get the error `Error: could not find CRI target`

I have tried on my Macbook and also on our CI server (Ubuntu).

Running with debug env variable shows the following

![image](https://user-images.githubusercontent.com/2477900/70909549-a269f600-2005-11ea-903f-731d6e2d9fee.png)

I think the relevant part is: 

```
  cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:56319     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 56319 } } +250ms
  cypress:network:connect successfully connected { opts: { getDelayMsForRetry: [Function: _getDelayMsForRetry], port: 56319 }, iteration: 1 } +104ms
  cypress:server:protocol CRI.List on port 56319 +106ms
  cypress:server:protocol CRI List { numTargets: 0, targets: [] } +37ms
  cypress:server:cypress exiting with err Error: could not find CRI target

```

### Desired behavior:

I would like the test to run in a headless Chrome instance.

### Steps to reproduce: (app code and test code)

Install and run cypress with a test (the contents of the test seem to be irrelevant as it fails before it starts running the test.

### Versions

Chrome Version 79.0.3945.79
Cypress Version 3.8.0

**Comment by jennifer-shehane** [comment]
Possibly related: https://github.com/NeuraLegion/cypress-har-generator/issues/17

Do you have any plugins or other setup? Maybe tapping into Chrome remote debugger?

**Comment by marmite22** [comment]
Thank you, removing my node modules folder and re-installing so that I got the up to date version of that dependency has fixed the issue.

**Comment by WinstonN** [comment]
I can confirm that I had to remove 3.8.1 cache folder, as well as my node_modules folder, and reinstall from scratch. After that the error went away

**Comment by jonsmithers** [comment]
I had to delete our `yarn.lock` file in addition to the `node_moduels/` folder.

**Comment by erezrokah** [comment]
@jonsmithers I'm experiencing the same issue. `yarn cache clean`, removing node modules and cleaning Cypress cache didn't work. Very inconsistent.

**Comment by SharanyaRK** [comment]
I could experience the same while running in docker containers.

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run since the original issue was resolved. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by jennifer-shehane** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/6053
