### ISSUE TITLE
{enter} on input type=number leads to invalid input (3.8.0 regression)

### ISSUE THREAD

**Issue by Narretz** [cypress-io/cypress#5968]
### Current behavior: 

 when you  type a number in an number input and then type enter, the input becomes empty and the console logs an error:

```
cypress_runner.js:107262 The specified value "12\n" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
```

You can see that the `{enter}` adds `\n` to the input value.

### Desired behavior:

It should set the value without `\n` 

### Steps to reproduce: (app code and test code)

html:
```html
<input type="number" id="input" />
```

spec code:

```js
cy.get('#input')
  .type('2')
  .type('{enter}')
```

### Versions

Cypress 3.8.0
edit: Chrome 79 with cypress run

Possibly related to https://github.com/cypress-io/cypress/pull/5854

**Comment by jennifer-shehane** [comment]
@Narretz I'm not able to recreate this from the code provided in 3.8.0 in Electron 78 or Chrome 79. Can you double check the provided code exactly and see if the error occurs for you? Thanks.

The code I ran with no other settings:

`index.html`

```html
<!DOCTYPE html>
<html>
<body>
  <input type="number" id="input" />
</body>
</html>
```

`spec.js`

```js
it('types', function () {
  cy.visit('index.html')
  cy.get('#input')
    .type('2')
    .type('{enter}')
})
```

<img width="574" alt="Screen Shot 2019-12-17 at 4 10 42 PM" src="https://user-images.githubusercontent.com/1271364/70983910-e59c9580-20e7-11ea-907a-26b0ed9a145f.png">

**Comment by Narretz** [comment]
Hi @jennifer-shehane thanks for the quick response. Since the screenshot seems to be showing the end of the test run, then it's also showing the wrong result I mentioned - the input shouldn't be empty, it should still have the 2 in it. Did you check the console for the message / warning?

(There will be no error in the test log, so the result being "green" is expected)
(Forgot to mention that I tested this with cypress run and Chrome 79)

**Comment by Narretz** [comment]
@jennifer-shehane do you need anything else for this issue?
As I wrote in response to you, your screenshot already shows the problem.

**Comment by jennifer-shehane** [comment]
@Narretz Right, sorry. It's helpful to provide the incorrect failing test case. So, the assertion below incorrectly fails.

I do see the message in the console. I misread and thought that was an error throwing in the Test Runner directly. 



```html
<!DOCTYPE html>
<html>
<body>
  <input type="number" id="input" />
</body>
</html>
```

```js
it('types', function () {
  cy.visit('index.html')
  cy.get('#input')
  // doing .type('2{enter}`) causes same error
    .type('2')
    .type('{enter}') 
    .should('have.value', '2')
})
```

## 3.7.0

![Screen Shot 2019-12-20 at 1 26 45 PM](https://user-images.githubusercontent.com/1271364/71236089-6cda4b00-232c-11ea-82ba-be3b310337ac.png)


## 3.8.0

<img width="787" alt="Screen Shot 2019-12-20 at 1 12 07 PM" src="https://user-images.githubusercontent.com/1271364/71235417-7ebaee80-232a-11ea-967d-e9ae6a3c2d30.png">

`2` console table

![Screen Shot 2019-12-20 at 1 29 40 PM](https://user-images.githubusercontent.com/1271364/71236230-d0647880-232c-11ea-976b-a04f862e1550.png)

`{enter}` console table

![Screen Shot 2019-12-20 at 1 29 01 PM](https://user-images.githubusercontent.com/1271364/71236244-de19fe00-232c-11ea-942b-f9a734aaee51.png)

**Comment by Narretz** [comment]
Thanks! Next time I will include a failing test.

**Comment by reukies** [comment]
I believe I have a similar issue. When typing '02' or any number with 0 at the start will results in the input only being 0.

**Comment by reukies** [comment]
I believe I have a similar issue. When typing '0500' or any number with 0 at the start will results in the input only being 0.
