### ISSUE TITLE
Cypress Desktop App crashes when opening a project (probably a permissions issue)

### ISSUE THREAD

**Issue by TalonLaurens** [cypress-io/cypress#597]
- Operating System: Xubuntu 14.10, NodeJS 8.4.0
- Cypress Version: 0.19.4
- Browser Version:

### Is this a Feature or Bug?

Bug

### Current behavior:

After installing cypress following the tutorial (https://docs.cypress.io/guides/guides/command-line.html), I can not open project folders in the Cypress UI **unless I run it as sudo**

### Desired behavior:

It should also work fine without sudo permissions

### How to reproduce:

- Upgraded node.js to latest version
- installed cypress using the `-g` flag
- run `cypress install`
- run `cypress open`
- Add a Project in the UI
- Open a project in the UI
- App crashes at this point with no visible stacktrace

**Comment by bahmutov** [comment]
Is the Cypress version really 0.13.1? That is a very old version

**Comment by TalonLaurens** [comment]
@bahmutov sorry, it's version 0.19.4.

0.13.1 is what I got from typing `cypress version` in the terminal but that returned the cypress CLI version apparently.

**Comment by jennifer-shehane** [comment]
@TalonLaurens Hi, what tests are you running in the project? Are they our example kitchen-sink tests or do you have a suite of tests you've written that you are running? If it's your tests, could you paste the test code?

I've been unable to replicate this with just the circumstances outlined above.

**Comment by TalonLaurens** [comment]
Hey @jennifer-shehane , thanks for the reply.

I was just about to add some more detailed steps to reproduce here, but... it seems like restarting my machine has fixed the problem... :frowning: I can now open project folders as expected in the cypress UI (without using root)

Sorry for this false alarm... I always expected it was more an issue with my machine than with cypress itself.
