### ISSUE TITLE
Debugging failing test with cy.on("fail")

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#5970]
### Current behavior:

Here: https://docs.cypress.io/api/events/catalog-of-events.html#Catching-Test-Failures
it is documented that we can debug a failing test with this piece of code:

```js
// if you want to debug when any test fails
// You likely want to put this in a support file,
// or at the top of an individual spec file
Cypress.on('fail', (error, runnable) => {
  debugger
  // we now have access to the err instance
  // and the mocha runnable this failed on
  throw error // throw error to have test still fail
})
```

But I tried this and the breakpoint is never hit.

### Desired behavior:

Event should be thrown according to documentation.

### Steps to reproduce: (app code and test code)

Test this simple code:

```js
cy.on("fail", (error, runnable) => {
    debugger;
});

describe("Parent", () => {
    debugger;
    describe("nested", () => {
        it("test", () => {
            cy.visit("https://google.com").then(() => expect(true).to.eq(false))
           // (this.test as any).attachments = ["ascreenshots"]
            ;
        })
    })
})

```

### Versions

Cypress 3.8.0

**Comment by jennifer-shehane** [comment]
So, this is due to the subtle different between `cy` and `Cypress`, which admittedly is not explained very well in the docs. Little `cy` will apply within the context of the test, big `Cypress` will apply globally over all of the tests. 

So either of the examples below will work:

```js
it("test", () => {
  cy.on("fail", (error, runnable) => { 
    debugger; // listening within test
  });
  cy.visit("https://google.com").then(() => expect(true).to.eq(false))
})
```

```js
Cypress.on("fail", (error, runnable) => {
  debugger; // listening globally
});

it("test", () => {
  cy.visit("https://google.com").then(() => expect(true).to.eq(false))
})
```

**Comment by gabbersepp** [comment]
Thanks for making this clear!
