### ISSUE TITLE
react portal issue with cypress 3.8.0

### ISSUE THREAD

**Issue by JonathanRiv** [cypress-io/cypress#5971]
hi there,
I've spotted an issue on cypress 3.8.0 that was working on version 3.6.1 (my previous version)

### Current behavior:

I'm not able to click on an element inside a dropdown (coded in react.js and of the course the dropdown is opened with the previous action)

### Desired behavior:

I should be able to click on an element inside a dropdown

### Steps to reproduce: (app code and test code)

here is my test code :
```js
describe('test mail test', function() {
    it("should send a test mail", function() {
        cy.visit('/')
        cy.get('.Dropdown').click() //open the dropdown
        cy.get(':nth-child(3) > .OptionBlock').click() //try to click on an element inside the dropdown (react portal)
```

raise the error :
```
CypressError: Timed out retrying: cy.click() failed because this element is not visible:
```

for the app code, I can't provide it here as I'm not a developer (only QA) and it's a client code and also it's not yet released on production.
I can say that it's a portal on react side, the portal is created when we click on the dropdown, if we don't do so, the portal is not in the DOM

### Versions

browser : Google chrome Version 78.0.3904.108 (Build officiel) (64 bits)
operating system : Windows 10 Professionnel 64 bits (10.0, version 18362)
cypress : v 3.8.0
please note that I also send my test to my colleague who have a 3.6.1 cypress version and it's working perfectly, I also checked the changelog for 3.7.0 and 3.8.0 and I don't find anything related 

best regards

**Comment by jennifer-shehane** [comment]
@JonathanRiv We won't be able to investigate without a way to run this ourselves. 

Can you provide a small subset of the html/css/js to recreate? What does the generate html of the dropdown look like, what css makes it visible as opposed to not visible as Cypress is asserting.

**Comment by JonathanRiv** [comment]
@jennifer-shehane thanks for your quick answer

I asked a dev to provide me a sandbox code to reproduce the issue, will provide it tomorrow as it's nearly end of the working day here (4:51 pm) and we will not have enough time today.

please note that I never work on the 3.7.0 version, I switched directly from v 3.6.1 to 3.8.0

**Comment by aprea** [comment]
>We aren't aware of any current regressions in 3.7.0 for this clicking.
I am experiencing this issue in 3.8.0 but not in 3.7.0.

**Comment by jennifer-shehane** [comment]
@aprea Please provide a reproducible example. We cannot begin fixing the issue if we cannot recreate it. Thanks.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by pedroAVS** [comment]
Hi,
I'm having the same issue with 4.8.0, we are using react.js and this is a fixed element that drops from the top of the page, after a button is clicked:
![2020-06-22_17h24_49](https://user-images.githubusercontent.com/13781287/85311598-962b8d80-b4ad-11ea-801e-d4284a585154.png)


The dropdown is spawning outside the application as it's shown on the below screenshot:
![2020-06-22_17h15_17](https://user-images.githubusercontent.com/13781287/85310903-81022f00-b4ac-11ea-8682-ee9ebc254709.png)

If i query for that dropdown-layer i find it is hidding on top/bottom:
![2020-06-22_14h21_45](https://user-images.githubusercontent.com/13781287/85311830-eb679f00-b4ad-11ea-8b85-0ac0752271c8.png)

and if i force a click via console i get this weird bug on the UI, where it starts creating the list repeatedly below the UI area:
![2020-06-22_14h06_19](https://user-images.githubusercontent.com/13781287/85311926-0cc88b00-b4ae-11ea-9f97-eb545d76b1eb.png)

**Comment by sinharaksh1t** [comment]
I'm getting the exact same issue as @pedroAVS. 
Do you have any suggestions for this issue @jennifer-shehane?

**Comment by tabrez96** [comment]
I'm facing the same issue while trying to click a button from a `Modal` which is rendered using `Portal`

**Comment by jennifer-shehane** [comment]
@sinharaksh1t If you can provide a repo that reproduces the error, we can look at the error - as of now we can't recreate this issue so there are no suggestions.
