### ISSUE TITLE
Add new setting for chrome: time zone/TZ

### ISSUE THREAD

**Issue by HomoncikT** [cypress-io/cypress#5973]
Hi, 

Could you add the option of setting the time zone? 
It is now available in chrome dev tools. 
https://developers.google.com/web/tools/chrome-devtools/device-mode/geolocation

**Comment by jennifer-shehane** [comment]
This would fall under the solution for this issue: https://github.com/cypress-io/cypress/issues/2671 We will be closing this in favor of the other issue and I will note the update to CDP in that issue. Thanks!
