### ISSUE TITLE
Renderer process crashed

### ISSUE THREAD

**Issue by behlrattan** [cypress-io/cypress#598]
@brian-mann @jennifer-shehane 

- Operating System: Its Cypress/base docker running on AWS Linux
- Cypress Version:19.4
- Browser Version: Chromium

### Is this a Feature or Bug? 
Bug

### Current behavior: 
Intermittently (very frequently)  getting "Renderer process crashed" when running the tests via jenkins. Captured video shows tests passing and then execution stops abruptly in the middle. Sometimes there is no error stack at all and on other occasions there is this message and link https://on.cypress.io/renderer-process-crashed

### Desired behavior: 
Should display more information for the cause of failure rather than a generic message, at this moment i am totally clueless.

#### Test code:

```js

```

**Comment by sanjivsahayamrea** [comment]
Have you tried running docker with `--ipc=host` ? 

https://github.com/cypress-io/cypress/issues/350

**Comment by brian-mann** [comment]
I'm assuming this is related to this issue: https://github.com/cypress-io/cypress/issues/681

**Comment by behlrattan** [comment]
Running docker with --ipc=host fixed the issue.
