### ISSUE TITLE
cy.wrap does not respect timeout

### ISSUE THREAD

**Issue by janakdr** [cypress-io/cypress#5980]
This example spec file fails with the error below:

```js
describe('Cypress wait', () => {
  it('wrap does not wait', () => {
    cy.wrap(
        new Promise((resolve) => setTimeout(resolve, 5000)), {timeout: 20000});
  });
});
```

```
 Cypress wait
    1) wrap does not wait


  0 passing (4s)
  1 failing

  1) Cypress wait wrap does not wait:
     Error: Cypress command timeout of '4000ms' exceeded.
      at http://localhost:57838/__cypress/runner/cypress_runner.js:103532:25
```

Shouldn't `cy.wrap` respect the `timeout` option? The test passes if I pass `--config defaultCommandTimeout=6000` on the command line, but I want to pass a specific timeout for this `cy.wrap` command.

**Comment by jennifer-shehane** [comment]
I do feel like it should respect the timeout option here.

The code for the `.wrap()` command can be found here: 

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/misc.coffee#L28:L28

**Comment by datner** [comment]
should the entire run wait for the timeout before advancing the test? Won't that potentially make the test take too long?

**Comment by janakdr** [comment]
Not sure I understand the question. Is it different from how you expect
cy.get to behave with respect to the timeout?

**Comment by jennifer-shehane** [comment]
Please read the docs for the `defaultCommandTimeout` definition. https://on.cypress.io/configuration#Timeouts It is not per test, but per command.

**Comment by jasonkoon** [comment]
I am seeing the same issue.  I am using cy.wrap to make an async call to set up some data.  Sometimes it takes longer than 4 seconds which causes the test to fail.

**Comment by figalex** [comment]
I'm seeing the same problem. I'm setting the timeout property to 12000 and I'm still getting the "4000ms timeout exceeded" error.

Using cypress version 3.6.1

**Comment by donleqt** [comment]
Hello here is an workaround to force Cypress to wait for a promise:

```javascript

/**
 *  helper function that forces cy to wai for a promise
 *
 * @export
 * @param {Promise} promise promise to wait
 * @param {number} [interval=1000] recheck in minlisecons
 * @returns
 */
export function waitPromise(promise, interval = 1000) {
  let isDone = false;

  const runPromise = () => {
    if (isDone) {
      // Wrap and returns the result
      return cy.wrap(promise.catch(error => assert.isNotOk(true, error)));
    }
    return cy.wait(interval).then(() => runPromise());
  };

  // Marks as resolved
  promise.then(() => (isDone = true)).catch(() => (isDone = true));

  return runPromise();
}
```
And in-use example

```javascript
    it('Restore Password - Should received an email', () => {
      // This is an promise
      const task = emailHelper.searchLastEmail({
        emailAddress: user.email,
        subject: 'Reset Password',
        timeout: 2 * 60000 // 2 min
      });

      testHelpers.waitPromise(task).then(mail => {
        // Save for later test
        restorePasswordMail = mail;
        return expect(mail).not.to.be.null;
      });
    });
```
