### ISSUE TITLE
Support switching off the default test run result output

### ISSUE THREAD

**Issue by seyfer** [cypress-io/cypress#5985]
It is a proposal

### Current behavior:

First described in https://github.com/cypress-io/cypress/issues/5833

I set a reporter in the config.
And then I have mixed output from default spec reporter with the reporter I have set-up.
For some reason spec still outputs and my specified reporter adds dots or cats in between.

```
Running:  backend/settings/my.spec.js                   (4 of 5)


  ․․

  2 passing (11s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     11 seconds                                                                       │
  │ Spec Ran:     backend/settings/my.spec.js                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Why is it a problem?**

Cypress floods the CI output with not needed information. Other tools like Jest + Puppeteer, Behat, PHPUnit are providing just dots output for the test result and it is very useful for CI.
And it looks like that in CI output
```
...........................................
```
And I see the full output only in case of error.

### Desired behavior:

I have an option in the config to not only choose a custom or mocha reporter but also to switch off the default output.

```
reporterDefaultOutput: false
```

In this case, the only reporter specified in `reporter` config option outputs to console. I should see only dots in the case of `dot` reporter specified in the config and the default output is switched off.

### Steps to reproduce: (app code and test code)

Set
`"reporter": "dot"`
or
`"reporter": "nyan"`

in cypress.json. do `cypress run`, see the mixed output.

### Versions

Cypress 3.8.0

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.

**Comment by ThatBrianDude** [comment]
Please reopen this issue! Its seriously annoying that we cant disable the default output. What do we write our custom reporters for if theyre ruined by the default output anyway?
