### ISSUE TITLE
can not open cypress.

### ISSUE THREAD

**Issue by vinodreddy21** [cypress-io/cypress#5986]
```
PS C:\Users\CFS\CypressAutomationProject> ./node_modules/.bin/cypress open
./node_modules/.bin/cypress : File C:\Users\CFS\CypressAutomationProject\node_modules\.bin\cypress.ps1 cannot be loaded because     
running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./node_modules/.bin/cypress open
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by Kailash1980** [comment]
I have faced the same problem 

Solution :
In Window::
Open Windows PowerShell
Run Set-ExecutionPolicy RemoteSigned 
Press Yes 
Now Run run ./node_modules/.bin/cypress run will work properly

**Comment by jennifer-shehane** [comment]
@vinodreddy21 Please try to solution offered above. Closing as resolved.

**Comment by Vinnarasis** [comment]
Typing the  command ' ./node_modules/.bin/cypress run' it says the following error

 ./node_modules/.bin/cypress : The term './node_modules/.bin/cypress' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ ./node_modules/.bin/cypress run Test runner
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./node_modules/.bin/cypress:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by venkatabonda** [comment]
> I have faced the same problem
> 
> Solution :
> In Window::
> Open Windows PowerShell
> Run Set-ExecutionPolicy RemoteSigned
> Type Yes
> Now Run run command ./node_modules/.bin/cypress run Test runner will work properly

Hi I tried the same it is throwing an error like this:
![image](https://user-images.githubusercontent.com/27727368/91036304-00bc8f00-e5ff-11ea-8c15-2296bb56f991.png)
PS C:\Users\User> Set-ExecutionPolicy -Scope CurrentUser

cmdlet Set-ExecutionPolicy at command pipeline position 1
Supply values for the following parameters:
ExecutionPolicy: Set-ExecutionPolicy RemoteSigned
Set-ExecutionPolicy : Cannot bind parameter 'ExecutionPolicy'. Cannot convert value "Set-ExecutionPolicy RemoteSigned"
to type "Microsoft.PowerShell.ExecutionPolicy". Error: "Unable to match the identifier name Set-ExecutionPolicy
RemoteSigned to a valid enumerator name. Specify one of the following enumerator names and try again:
Unrestricted, RemoteSigned, AllSigned, Restricted, Default, Bypass, Undefined"
At line:1 char:1
+ Set-ExecutionPolicy -Scope CurrentUser
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-ExecutionPolicy], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.SetExecutionPolicyComman

**Comment by Premsing** [comment]
> Set-ExecutionPolicy RemoteSigned

Oh, it's PowerShell, not a cmd prompt😋.
Thank you guys
