### ISSUE TITLE
Do not load full environment while building Test Runner

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#5990]
Current environment.coffee no longer silently swallows errors while processing command line flags:

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/environment.coffee#L66

Now the build script shows the error message, but works fine

```
npm run binary-zip -- --platform $PLATFORM

> cypress@3.8.0 binary-zip /root/cypress
> node ./scripts/binary.js zip "--platform" "linux"

Cannot find module 'electron'
Require stack:
- /root/cypress/packages/server/lib/environment.coffee
- /root/cypress/packages/server/lib/konfig.coffee
- /root/cypress/scripts/binary/get-config.js
- /root/cypress/scripts/binary/upload.coffee
- /root/cypress/scripts/binary/index.coffee
- /root/cypress/scripts/binary.js
#zip
#zip linux
...
```

We load the environment from the build binary script indirectly - via upload.coffee that needs to know JUST 1 url - CDN url where to upload the built zip

```coffee
  getManifestUrl: (folder, version, uploadOsName) ->
    {
      url: [konfig('cdn_url'), folder, version, uploadOsName, zipName].join("/")
    }
```

This url comes from https://github.com/cypress-io/cypress/blob/develop/packages/server/config/app.yml and there is just one default value 

```yml
default:
  cdn_url: "https://cdn.cypress.io"
```

## Proposal

Just load the `app.yml` and grab the `cdn_url` without loading the entire config

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
