### ISSUE TITLE
`.type()` does not type chars in number input beyond special chars (like `,`)

### ISSUE THREAD

**Issue by abaybabaydabudidabuday** [cypress-io/cypress#5997]
### Current behavior: 

Pre-conditions - in my text form "," sign not allowed to input

Input inside type() func: 

**1,99**

Output: 

**1**

### Desired behavior:

**199**

It worked in previous version of cypress correctly and problem I met in 3.8.0

### Steps to reproduce: (app code and test code)

Just try to type from tests some signs that couldn't be written.

### Versions

Cypress 3.8.0
OS: Mac Mojave
Browser: Chrome

**Comment by aelmekeev** [comment]
What is the type of your input? We've also noticed some difference in recent versions and tracked it down to these regexp: https://github.com/cypress-io/cypress/blob/6ed8d31cf045acd486757474934ef84f5f96cb74/packages/driver/src/cy/keyboard.ts#L65

To be honest I don't think that automation framework should do this at all.

**Comment by Narretz** [comment]
This is only for number inputs, and Cypress has to do this because they replicate certain browser / html functionality, unlike Selenium.
But I agree, something went really quite wrong with the number input in 3.8.0.

**Comment by abaybabaydabudidabuday** [comment]
> What is the type of your input? We've also noticed some difference in recent versions and tracked it down to these regexp:

I'm using them as string obj. Should I prefer to use them as a number type or it doesn't matter?

**Comment by jennifer-shehane** [comment]
@abaybabaydabudidabuday Can you paste in the html of the input element? We want to know the `type` attribute. Should look something like:

```
<input type="???" />
```

**Comment by jennifer-shehane** [comment]
I verified this behavior in 3.8.0. 

When typing manually, I can type `1` `,` `0` `0` `0` where the `,` does not display in the input, but the entire `1000` is set as the value.

`index.html`

```html
<!DOCTYPE html>
<html>
<body>
  <input type="number"/>
</body>
</html>
```

```js
it('Type in number', () => {
  cy.visit('index.html')
  cy.get('input').type('1,000')
})
```

## 3.7.0

<img width="562" alt="Screen Shot 2019-12-19 at 2 57 47 PM" src="https://user-images.githubusercontent.com/1271364/71157252-03950200-2270-11ea-80cc-9a973e5e0680.png">


Events table when clicking on 'type' command

<img width="1329" alt="Screen Shot 2019-12-19 at 2 59 53 PM" src="https://user-images.githubusercontent.com/1271364/71157361-3f2fcc00-2270-11ea-89b6-d756845432e1.png">


## 3.8.0

You can see the test run where it only has `1` in the value. 

<img width="548" alt="Screen Shot 2019-12-19 at 2 56 30 PM" src="https://user-images.githubusercontent.com/1271364/71157142-cd578280-226f-11ea-9e3d-1b1349ffd7bb.png">

Events table when clicking on 'type' command. Seems like the `input` event is never firing for the `,` + `0` characters.

<img width="1328" alt="Screen Shot 2019-12-19 at 2 53 24 PM" src="https://user-images.githubusercontent.com/1271364/71157262-0b54a680-2270-11ea-87a6-5b7d9b91496a.png">
