### ISSUE TITLE
CypressError: cy.visit() failed because you are attempting to visit a second unique domain.

### ISSUE THREAD

**Issue by justinjdickow** [cypress-io/cypress#600]
The two domains are formatted as

https://sso.something.mydomain.com and
http://qa.someotherthing.mydomain.com.

This to me seems like they are unique subdomains, not unique domains, and it's preventing me from testing my login page.

The error in Cypress sends me to: https://on.cypress.io/cannot-visit-second-unique-domain which references which sends me to https://docs.cypress.io/api/commands/visit.html which has no information about this error.

**Comment by brian-mann** [comment]
Likely same issue as this: https://github.com/cypress-io/cypress/issues/380

Cypress fails to parse subdomains in some situations because the rules are quite complex and ever changing. We'd need to update the code in multiple places to be async because the TLD list is quite extensive and couldn't be sent into the browser.

**Comment by justinjdickow** [comment]
@brian-mann Do you have a priority on fixing this issue? having multiple level sub domains is quite common, especially in qa/stage environments

**Comment by brian-mann** [comment]
It's likely 2-3 dev days of work, and its not as high as several other things. I can't really comment on when it'd get into the pipeline, but I'll note this issue when it gets started.

**Comment by justinjdickow** [comment]
Appreciate it

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).

**Comment by vineetkumar1511** [comment]
Any update on this issue ?

**Comment by jennifer-shehane** [comment]
@vineetkumar1511 This issue should be resolved in Cypress versions > 1.4.2, if you're experiencing an issue that you think is related, please give us a reproducible example in this issue or open a new issue if unrelated.
