### ISSUE TITLE
Unable to paste password into Github auth screen

### ISSUE THREAD

**Issue by tomsturge** [cypress-io/cypress#601]
- Operating System: Mac OSX 10.12.6
- Cypress Version: CLI 0.13.1 | APP 0.19.4
- Browser Version: N/A

### Is this a Feature or Bug?
When signing in into the Cypress app via Github I am unable to paste my copied password from my password manager, via either a context menu or with the paste keyboard short cut

### Current behaviour:
Nothing happens when I try to paste my 64 characters random password string into the Github password input

### Desired behaviour:
Copied password is pasted into the password input

### How to reproduce:
Start Cypress app as an anonymous user and try to paste anything into the password input of the Github login screen

**Comment by mrmohtas** [comment]
That's really weird, I just tried it again and pasting via keyboard shortcut worked fine... Very odd, I tried many times when I first started the Cypress app. Wonder if it's a first time run issue
