### ISSUE TITLE
Chrome --headless requires xvfb

### ISSUE THREAD

**Issue by ext** [cypress-io/cypress#6012]
### Current behavior:

On a Linux CI environment I run `cypress run --headless --browser chrome`  (and tried the workaround from #5949) but I keep getting the error:

> Your system is missing the dependency: Xvfb
> Install Xvfb and run Cypress again.

### Desired behavior:

Since this is headless I expect it to run without xvfb as other E2E-frameworks allows me. I dont control the environment so I cannot decide what is and isn't installed and docker is not yet an option so I was very hopeful when I saw the release announcement about supporting headless for chrome.

### Steps to reproduce: (app code and test code)

1. Install cypress 3.8.0
2. Configure to run headless chrome
3. Run on Linux machine without X and xvfb.

### Versions

Cypress 3.8.0

**Comment by flotwig** [comment]
Electron still requires a valid display server to run, so you will still need Xvfb for the time being. #3899 will remove this dependency.

Closing since this is expected - unfortunate, but expected.
