### ISSUE TITLE
Second Unique domain error even though app running on localhost

### ISSUE THREAD

**Issue by abhidp** [cypress-io/cypress#6016]
### Current behavior:

![image](https://user-images.githubusercontent.com/30851622/71229042-4ae6c580-2338-11ea-8ca6-1ea0ab2c68d0.png)

### Desired behavior:

Cypress should redirect back to `baseUrl=localhost:XXXX` after getting token from the 3rd party Auth server and continue with the next steps.

### Steps to reproduce: (app code and test code)

The problem:

I am running our React app locally on `port:3000`

Upon accessing `http://localhost:3000` on the browser, it automatically redirects to the 3rd-party auth-server. 

The app gets Auth-token from a 3rd-party and then re-directs back to `baseUrl`.

This works all good when I login manually in the browser from the same localhost. But when the same runs in Cypress, it errors out as shown in the above screenshot. Cypress thinks that I am using two different urls in my test - the auth-server link and localhost link. Whereas the only link in my config is the baseUrl and nothing else as you can see in the screenshots and the config below.

cypress.json

```json
{
  "baseUrl": "http://localhost:3000",
  "video": false,
  "env": {
    "user": "",
    "pass": ""
  },
  "viewportWidth": 1440,
  "viewportHeight": 900,
  "chromeWebSecurity": false
}

```

Note: I am already very well aware of the best practices which says we should be logging in programmatically via API requests and not thru the UI. This works well in simple straight-forward apps like kitchen-sinks, todos, apples and oranges etc. But enterprise-grade applications are a bit more complex than getting a token by just doing a single `cy.request()` to a `/apples/giveMeUserToken` endpoint. Just to give an overview of the complexity, our dev teams are distributed across multiple countries and there are about 7 different multifactor authentication calls where tokens are passed between the headers of these APIs to retrieve the final `session-cookie`. Not to mention these tokens get changed periodically for security purposes. These are all owned by different co-located security teams who are beyond a feature team's reach and in different time-zones. Hence, logging in via API is out of question here.

### Versions

```
$ cypress -v
Cypress package version: 3.8.0
Cypress binary version: 3.8.0

$ node -v
v10.17.0

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 9 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB

    System Software Overview:

      System Version: macOS 10.14.6 (18G1012)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```

**Comment by jennifer-shehane** [comment]
Your application is rerouting to a two urls which are considered different superdomains, which you can see in the Command Log: 

- `https://localhost:3000`
- `https://test.secure.myob.com` & `https://sit.login.myob.com` 

We do not support navigating or being rerouted through different superdomains within a single test.

Please add your feedback for supporting navigating to 2 superdomains to this existing issue: https://github.com/cypress-io/cypress/issues/944 Closing as duplicate.
