### ISSUE TITLE
Screenshot of element is not properly captured with `scroll-behavior: smooth`

### ISSUE THREAD

**Issue by Workito** [cypress-io/cypress#6018]
### Current behavior:
I want to screenshots some elements, but screenshot command for some reason scroll when picture is taken. So picture doesn't contain the element.

There is video from testing...
https://images.dvanakoncisveta.cz/nav.spec.js.mp4

There is taken picture...
https://images.dvanakoncisveta.cz/actual.png

### Desired behavior:
Screenshot the set element...

### Steps to reproduce: (app code and test code)
I'm using `cypress-plugin-snapshots` plugin with default settings. But I havesame issue with cypress screenshot() too.
`it('nav', () => {
	cy.get('nav').toMatchImage();
});
`

Working demo with this issue is here https://github.com/Workito/cypress-test-tiny

### Versions
cypress: 3.8.0
cypress-plugin-snapshots: 1.2.9
npm: 6.7.0
node: 11.15.0
Browser: Electron 78 (headless) or Chrome 79 (same issue)
OS: MacOs 10.15.2 (19C57)

**Comment by jennifer-shehane** [comment]
Yeah, this is weird. I am not sure why it's doing this scroll behavior to capture an element that is already visible on the screen. 

I narrowed it down from the original HTML to the example below. If you remove the `scroll-behavior: smooth`, the screenshot is taken correctly. 

```html
<html style="scroll-behavior: smooth;">
<body>
  <div style="height: 100px;"></div>
  <nav style="height: 60px; background-color: red;"></nav>
  <div style="height: 1000px;"></div>
</body>
</html>
```

```js
it('works', () => {
  cy.visit('index.html');
  cy.get('nav').screenshot()
})
```

The screenshot *should* take a screenshot of the element with background-color: red, but it takes a screenshot slightly below it. 

![](http://g.recordit.co/sHRIBXb6ow.gif)

Screenshot is completely white bg:

![works (56)](https://user-images.githubusercontent.com/1271364/71253260-d753b100-2355-11ea-9f58-b42c78dfc41d.png)

## Workaround

Disabled `scroll-behavior: smooth` in tests when taking screenshots as explained in these comments:

- https://github.com/cypress-io/cypress/issues/3200#issuecomment-505965470
- https://github.com/cypress-io/cypress/issues/3200#issuecomment-512228495

**Comment by Workito** [comment]
Thank you! This fix the issue. 👍

**Comment by jennifer-shehane** [comment]
@Workito I'm reopening this issue as this is a bug in Cypress. I've only given a temporary workaround but this should not be required to get the screenshots properly working.

**Comment by azaeng04** [comment]
@jennifer-shehane any update on this since I am seeing screenshots being chopped off when executing them in Chromium browser.

**Comment by lukesdm** [comment]
+1. Perhaps consider adding this issue and workaround to Notes here?
https://docs.cypress.io/api/commands/screenshot

**Comment by virginiacini** [comment]
We are experiencing this `scroll-behavior` issue, running cypress 8.5.0
