### ISSUE TITLE
Values set by plugin no longer highlighted in Test Runner Settings

### ISSUE THREAD

**Issue by drewbrend** [cypress-io/cypress#6024]
This used to work so this is a regression in 3.8.0 - or maybe earlier.

### Current behavior:

Values set by plugin are not highlighted and at a glance look the same as default values.  Values set by other methods are working properly.

### Desired behavior:

Values set by plugin should be highlighted purple as they were previously

### Steps to reproduce: (app code and test code)

1. Set an env var in a plugin
2. Launch Cypress Test Runner
3. Go to the Settings tab

### Versions

Cypress 3.8.0

![image](https://user-images.githubusercontent.com/5375799/71293996-2218fd00-2345-11ea-9480-a5a81ab3c1f1.png)

**Comment by jennifer-shehane** [comment]
I confirmed this was introduced in 3.7.0, likely from this PR https://github.com/cypress-io/cypress/issues/5067 

I also confirmed that this only affects the visual display of the configuration not highlighting as the same color as 'plugin', the value is actually set and read in correctly. 

## 3.6.1

![Screen Shot 2019-12-23 at 10 07 06 AM](https://user-images.githubusercontent.com/1271364/71334369-43a7fd80-256c-11ea-933c-27bbde967683.png)

## 3.7.0

![Screen Shot 2019-12-23 at 10 03 41 AM](https://user-images.githubusercontent.com/1271364/71334373-47d41b00-256c-11ea-9b65-88afd68d7fc5.png)
