### ISSUE TITLE
Not all characters being typed during cy.type()

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/cypress#6027]
My code looks like this

```js
cy
.get('[name="lastname"]')
.type(tester.surname)
.should('have.value', tester.surname)
```

I get the error:
```
Error:       CypressError: Timed out retrying: expected '<input#lastname.input-text.required-entry>' to have value 'Automation', but the value was 'Autom'
```

I tried to add a timeout, which according to the docs, will get passed down to .should
https://docs.cypress.io/api/commands/should.html#Timeouts and changed my code to 

```js
cy
.get('[name="lastname"]', { timeout: 5000 })
.type(tester.surname)
.should('have.value', tester.surname)
```

However, on occasion, I still receive the error
```
Error:       CypressError: Timed out retrying: expected '<input#lastname.input-text.required-entry>' to have value 'Automation', but the value was 'Autom'
```

screengrab of the error below

![image](https://user-images.githubusercontent.com/1143789/71328076-df8a3700-2575-11ea-986f-68c260426254.png)

**Comment by jennifer-shehane** [comment]
Hey @WinstonN, in the console - the screenshot that you pasted, can you click on `Mouse Events` and `Keyboard Events` to expand those 2 tables? This should print exactly which events fired and why. Please paste a screenshot of that. 

Also, the HTMl to run the test code against to recreate this, can you provide that too please?

**Comment by WinstonN** [comment]
@jennifer-shehane Sure, I was able to reproduce it

Here is the info you requested
HTML
```
<input type="text" minlength="1" id="lastname" name="lastname" value="" title="Last Name" class="input-text required-entry" data-validate="{required:true}" placeholder="Last Name" autocomplete="off" aria-required="true">
```
The way I can reproduce it easily, is by running the test in a loop
```
/**
 * there are times, when we want to run a test more than once
 * the below covers that
 */
var numberOfTestRuns = 10
var testIterations = Cypress.env('testIterations') ? Cypress.env('testIterations'):numberOfTestRuns
for (var i = 1; i <= testIterations ; i++) { 
  runTest(i)
}
```

Some screengrabs below
![image](https://user-images.githubusercontent.com/1143789/71346432-bb0d7980-25cc-11ea-8a55-cccda0b4c3ac.png)

![image](https://user-images.githubusercontent.com/1143789/71346491-e8f2be00-25cc-11ea-8e74-8e0a30c81fb4.png)

![image](https://user-images.githubusercontent.com/1143789/71346562-0a53aa00-25cd-11ea-9cff-740bc0c07298.png)

**Comment by jennifer-shehane** [comment]
@WinstonN I'm not able to reproduce this from the HTMl + test code provided. I ran the test several, several times. 

- What version of Cypress are you using? Please make sure you are using the [current version of Cypress](https://on.cypress.io/changelog).
- What browser are you running the tests in?

My exact code:

```html
<!DOCTYPE html>
<html>
<body>
<input type="text" minlength="1" id="lastname" name="lastname" value="" title="Last Name"
  class="input-text required-entry" data-validate="{required:true}" placeholder="Last Name" autocomplete="off"
  aria-required="true">
</body>
</html>
```

```js
it('types', function () {
  cy.visit('index.html')
  cy.get('[name="lastname"]')
    .type('Hammersmith')
    .should('have.value', 'Hammersmith')
})
```

**Comment by gabbersepp** [comment]
We had the same issue with a VueJS app. It turned out that some logic removed the focus from the input for a short time and due to this some characters were missing in nearly every test.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by klipnot** [comment]
> My code looks like this
> 
> ```js
> cy
> .get('[name="lastname"]')
> .type(tester.surname)
> .should('have.value', tester.surname)
> ```
> 
> I get the error:
> 
> ```
> Error:       CypressError: Timed out retrying: expected '<input#lastname.input-text.required-entry>' to have value 'Automation', but the value was 'Autom'
> ```
> 
> I tried to add a timeout, which according to the docs, will get passed down to .should https://docs.cypress.io/api/commands/should.html#Timeouts and changed my code to
> 
> ```js
> cy
> .get('[name="lastname"]', { timeout: 5000 })
> .type(tester.surname)
> .should('have.value', tester.surname)
> ```
> 
> However, on occasion, I still receive the error
> 
> ```
> Error:       CypressError: Timed out retrying: expected '<input#lastname.input-text.required-entry>' to have value 'Automation', but the value was 'Autom'
> ```
> 
> screengrab of the error below
> 
> ![image](https://user-images.githubusercontent.com/1143789/71328076-df8a3700-2575-11ea-986f-68c260426254.png)

Hello,

I'm little bit curious because I'm facing the same issue and I was wondering if you always has this issues , 🤔 

Regards,

**Comment by nagash77** [comment]
Hi @klipnot , it's hard to tell what's going on based on the information you provided.  I would suggest you open a new ticket and provide a reproducible example via a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  That will give our engineers the best chance of being able to figure out what exactly is going on.

Also, check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by bvandrc** [comment]
This can occur due to typing while the component gets re-rendered, such as in React. This would never occur in a human scenario but occurs due to the speed of test actions. For example, Cypress is filling a form and clicks a button that triggers a re-render of the form. Cypress immediately starts typing in a text input box after that button click. After a couple keystrokes, the re-render occurs. Cypress has now lost control of that text input, and so doesn't input the remaining keystrokes.

Some solutions:

- Add a `cy.wait` before `.type` to to wait a short time for any rendering to occur and complete
- Or, set `keystrokeDelay=0` in Cypress config. This way, the typing of the whole string occurs instantly; no re-render occurs mid-typing.

It would be nice if Cypress accounted for this possibility and re-grabbed the input and started typing again, if it lost control before the typed string was complete.
