### ISSUE TITLE
Fix navigation_spec "page load" flaky test.

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#6030]
### Current behavior:

navigation_spec `does not log "page load" events` is really flaky. 

### Desired behavior:

It should always pass.

### Steps to reproduce: (app code and test code)

It fails a lot on PR.

### Versions

develop.

**Comment by jennifer-shehane** [comment]
Is this test specifically https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/commands/navigation_spec.coffee#L391:L391

**Comment by sainthkh** [comment]
I learned that it's related to the execution order of events and promises. But needs to research more about how to fix it.

**Comment by sainthkh** [comment]
@jennifer-shehane 

To pass this flaky test, 4 things should be done in the exact order below: 

1. [`go()` content](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/navigation.coffee#L428)
2. [`win.history.go()`](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/navigation.coffee#L449)
3. [navigationChanged()](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/navigation.coffee#L91)
4. [then() content](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/navigation.coffee#L461)

These are made possible by [`Promise.delay(100)`](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/navigation.coffee#L460). In that delay, step 2 and 3 are done so that step 4 should clear up things. 

When the flaky test fails, the steps 2 and 3 aren't done in 100ms for some reason (it might be because of the Chrome scheduler's scheduling.). 

I thought about using [`popstate` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) to check if `go` is done. But it cannot be a solution, because we need to show a command message when `go` process slows down (if you're moving from hash to hash, it can be done under 100ms, but when you need to load a new page, it's usually impossible). 

So, I came to the conclusion that it's impossible to fix this flakiness completely. It's more of a feature than a bug. 

However, I think there are some ways to suppress this problem. 

1. Increase the delay to 150 or 200. It might slow down the test a little, but it'll be less flaky because browser has more time to finish steps 2 and 3. 
2. Rerun the flaky test several times until it fails. Maybe, we need to wait for #3968 to be merged. 
3. Maybe, use both 1 and 2. 

For some reason, "page load" isn't flaky these days. Should we wait for #3968 and revisit later?

**Comment by Bkucera** [comment]
@sainthkh I can't reproduce the flake locally. Can you link to a CI run that exhibits this behavior?

**Comment by sainthkh** [comment]
Here it is: https://circleci.com/gh/cypress-io/cypress/221683#tests/containers/4. 

To forcefully reproduce it, change [`Promise.delay(100)`](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/navigation.coffee#L460) to `Promise.delay(1)`. 

It'll always fail.

**Comment by Bkucera** [comment]
ok, I believe this will fix it https://github.com/cypress-io/cypress/tree/flaky-test-page-load-event
