### ISSUE TITLE
Using add-typescript-to-cypress module, when TypeScript code not compiling, Cypress crashes

### ISSUE THREAD

**Issue by yonigibbs** [cypress-io/cypress#6032]
### Current behavior:
When using the [add-typescript-to-cypress module](https://github.com/bahmutov/add-typescript-to-cypress), if a test written in TypeScript is saved with the code not compiling, it causes the window containing the test to crash, and the main Cypress window to show the following:

![TypeScript crash screenshot](https://raw.githubusercontent.com/yonigibbs/cypress-typescript-crash/master/typescript-crash-screenshot.png)

This does not occur with JavaScript files left in an invalid state.

I'm not sure if this is related to add-typescript-to-cypress, or to Cypress itself, so let me know if you'd rather I logged this in the module's repo (@bahmutov, fyi, just in case you can immediately tell whether this is something that would be better logged in your repo rather than here).  I'm also aware that work is currently being done on TypeScript handling in Cypress (#1859 and #5906), so not sure if either of those will affect this issue.

### Desired behavior:
TypeScript files with invalid code should be handled in same way as JavaScript files are, i.e. the window containing the test should be left open, and an explanatory message should be shown, e.g.

![JavaScript error handled screenshot](https://raw.githubusercontent.com/yonigibbs/cypress-typescript-crash/master/javascript-error-handled-screenshot.png)

### Steps to reproduce: (app code and test code)
A repo with instructions on how to reproduce is available here: https://github.com/yonigibbs/cypress-typescript-crash

### Versions
* Cypress: 3.8.0
* add-typescript-to-cypress: 2.1.2
* OS: Ubuntu 18.04
* Browser: Chrome or Electron from within Cypress

**Comment by yonigibbs** [comment]
FYI, I swapped to using `cypress-webpack-preprocessor` instead of `add-typescript-to-cypress` and the error no longer occurs, so looks like maybe it is specific to that module, or an error in that module isn't being correctly handled in Cypress.

**Comment by jennifer-shehane** [comment]
Closing as likely an issue with https://github.com/bahmutov/add-typescript-to-cypress module. I'd recommend opening an issue in that repo.

**Comment by yonigibbs** [comment]
Thanks @jennifer-shehane. Have logged an issue in that repo as suggested: https://github.com/bahmutov/add-typescript-to-cypress/issues/105
