### ISSUE TITLE
Bad file descriptor crash

### ISSUE THREAD

**Issue by NickBolles** [cypress-io/cypress#6037]
### Current behavior:
```
 lerna run test --stream --no-prefix

lerna notice cli v3.18.4
lerna info Executing command in 1 package: "yarn run test"
yarn run v1.19.1
$ start-test start:test :3001 cy:run
starting server using command "npm run start:test"
and when url "[ 'http://localhost:3001' ]" is responding
running tests using command "npm run cy:run"
> client@1.0.0 start:test C:\dev\Projects\goalsapp\project\packages\client
> cross-env NODE_ENV=test nuxt-ts
> client@1.0.0 cy:run C:\dev\Projects\goalsapp\project\packages\client
> cypress run
child_process.js:114
  p.open(fd);
    ^
Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:114:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:328:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:49:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}
```
### Desired behavior:

No crash :(

### Steps to reproduce: (app code and test code)

1. init Lerna project
2. init cypress in a lerna package
3. run cypress command with `lerna run` - for example `lerna run test`
4. crash

I can try to setup a repro if need be. I don't have time to right now though

- it's very possible this is something in my config, I'm doing typescript preprocessing that I can't really pull out easily
- Jest, in one of my other monorepo packages, works fine

### Versions
3.8.0

**Comment by jennifer-shehane** [comment]
Please provide a repo we can run with instructions on how to run it. I attempted the steps given and have not been able to reproduce. 

We will be closing this issue without a reproducible example.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
