### ISSUE TITLE
SecurityError: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents.

### ISSUE THREAD

**Issue by hieutrandn9889** [cypress-io/cypress#6047]
Dear,

I got an issue when running cypress with cucumber on chrome 79
I added command plugins/index.js
args.push('--disable-site-isolation-trials');
      return args;
and using code cypress.json:
 "chromeWebSecurity": false

But I still got this error

**Comment by hieutrandn9889** [comment]
Pls help me to fix this issue

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by adrianblynch** [comment]
I'm seeing the same error while testing a payments form.

Running this locally on http we load in a 3rd party JS script which we call. That script has the following:

```
document.open();
```
This is the only reference to `open()`.

In a similar test suite we have the same code running where the parent page is on https and it works as expected.

**Comment by universeroc** [comment]
> I'm seeing the same error while testing a payments form.
> 
> Running this locally on http we load in a 3rd party JS script which we call. That script has the following:
> 
> ```
> document.open();
> ```
> 
> This is the only reference to `open()`.
> 
> In a similar test suite we have the same code running where the parent page is on https and it works as expected.

Please tell me the `document.open` issue is solved or not ?
