### ISSUE TITLE
DOM Snapshot always shows 'loading DOM element' when hovering over any command.

### ISSUE THREAD

**Issue by dulle88** [cypress-io/cypress#6052]
### Current behavior:

After the test runs, tests are passing just fine in full browser mode, and headless both, and I want to see DOM snapshot in the point of certain step, BUT there is always default app splash screen loader displayed on top of it. I can run a manual script in the browser console to remove loader after I select (pin) any step, but that is not something that works for us having to enter the code every time you want to see some step.

![hIapu8T](https://user-images.githubusercontent.com/1271364/71574707-5005fa80-2b18-11ea-87c5-5c5fbd686db2.png)

### Desired behavior:

After test run finishes and I click on the certain step I want to be able to use cypress tool to see DOM state before and after the action executed by cypress tool. 

### Steps to reproduce: (app code and test code)

Test is very simple and it passes fine, you can see all the screens and steps when it's running, once it's done and you pin any step in the test you can see the splashscreen animation over the UI. 

### Versions
Cypress 3.7.0 (we didn't upgrade to 3.8.0 due to problems where .clear() and .type() commands stopped working properly after the update. 

Windows 10 Pro

Browser : Chrome Version 79.0.3945.88

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example, the test code and application code we can run locally to recreate the problem and we will reopen the issue. 🙏

**Comment by dulle88** [comment]
So this is just a one simple example, but you can see in the DOM inspector it's always forcing the animation : 

`it('Example', () => {
        cy.visit('https://devppebankingsta.z6.web.core.windows.net/');
        cy.get('#wrapper > div > fuse-content > div.cover > div > dashboard-component').should('be.visible');
        cy.get('[aid="txt_accountTitle"]').should('be.visible');
        cy.get('[aid="lnk_clients"]').click();
        cy.get('.title').should('have.text', 'ALL CLIENTS LIST').should('be.visible');
})`

**Comment by jennifer-shehane** [comment]
@dulle88 Thanks for providing a reproducible example. 

Gif of what is happening when hovering over snapshots.

![](http://g.recordit.co/LWdgzq3gjk.gif)

**Comment by jennifer-shehane** [comment]
I wonder if this is somehow related to this issue https://github.com/cypress-io/cypress/issues/5348 involving keyframe animations. The splash screen is using a css animation on initial visit.

**Comment by dulle88** [comment]
Hey @jennifer-shehane cannot say with 100% certainty, but it looks like the same problem to me.

**Comment by fredbuluku** [comment]
If it does not add any change in the system we can do without it or we can automate the issue.

**Comment by dulle88** [comment]
@fredbuluku what do you mean by automating the issue?

**Comment by StephaneColson** [comment]
Same here with an Angular application (also using @keyframes so maybe related to #5348)

![Screenshot 2021-05-07 at 09 08 02](https://user-images.githubusercontent.com/1481595/117411320-bc1a1f00-af13-11eb-8b45-99985269fb62.png)


https://user-images.githubusercontent.com/1481595/117412010-8590d400-af14-11eb-8a16-4b4a59d699f1.mov

Using Cypress 6.6.0 with Chrome, Electron or Firefox on MacOS.
