### ISSUE TITLE
Ckeditor 5 ->SecurityError

### ISSUE THREAD

**Issue by expectral** [cypress-io/cypress#6054]
I'm actually on a problem with CKeditor and Cypress 3.8.1

I try to edit ckeditor iframe ( `cy.type( )` ), but cypress send me this error :

>"SecurityError: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents."

-------------------------------------------------------
**On my app :** 

**Step 1 :** 
I select a option
![image](https://user-images.githubusercontent.com/45633007/71520202-27cd9000-28bb-11ea-8a94-0ad3bd9bb855.png)

**Step 2 :** 
ckeditor iframe appear 
![image](https://user-images.githubusercontent.com/45633007/71520250-5f3c3c80-28bb-11ea-9084-240b1441c039.png)

-------------------------------------------------------
**On Cypress :** 

Test N°1 : 
![image](https://user-images.githubusercontent.com/45633007/71520393-2ea8d280-28bc-11ea-8048-2a00702f42a5.png)

1/ Connection
2/ Select Option
3/ I wait XHR response to wait load dynamic data
4/ I try the way propose by @brian-mann (https://github.com/cypress-io/cypress/issues/2272)
5/ After type(), the "Save" button must be enabled
6/ log off

Test N°2 : 
![image](https://user-images.githubusercontent.com/45633007/71520543-f81f8780-28bc-11ea-8ddb-4cef2075a600.png)

1/ Connection
2/ Select Option
3/ I wait XHR response to wait load dynamic data
4/ I try the way propose here -> (https://medium.com/@nickdenardis/getting-cypress-js-to-interact-with-ckeditor-f46eec01132f)
5/ After type(), the "Save" button must be enabled
6/ log off

I try multiple variants of this solution, but i always have this message : 
**_"SecurityError: Failed to execute 'open' on 'Document': Can only call open() on same-origin documents."_**

![image](https://user-images.githubusercontent.com/45633007/71520666-898ef980-28bd-11ea-848e-136340bc4edf.png)

It looks like the ckeditor instance is never (or too late) loaded

Yes, i put this option too on "cypress.json"  : 
 ` "chromeWebSecurity": false,`

My 200 others tests not affected by the ckeditor work perfectly.
Ckeditor was added recently by devteam, and the problems started :D

If I use : 
`win.CKEDITOR.instances['champDescriptionPageStatique'].destroy(); `

the sesson ckeditor is destroyed, and the test does not end in error. (but of course, I can't test my functional cases, like activating buttons, recording, previewing, etc.)

Anyone have a *magical* idea, please ?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example - the exact test code and application code we can run and we will reopen the issue. 🙏

**Comment by davidashman** [comment]
I'm experiencing the same issue.  What version of ckeditor do you have in your application?

**Comment by expectral** [comment]
> I'm experiencing the same issue. What version of ckeditor do you have in your application?

Hi @davidashman ,

We use CkEditor 5.
if you find a solution, we take it ;D
(and vice versa, of course)

**Comment by ManavJethani** [comment]
@expectral @brahimmouhamou did you guys find any solution for this , i am getting error while i do `cy.get(".ck-content").type('1234')`  i am getting` TypeError: Cannot read properties of null (reading 'root')`

**Comment by alexHu20221003** [comment]
@ManavJethani I have the same issue, do you have a solution?

**Comment by nagash77** [comment]
@alexHu20221003 @ManavJethani please open a new issue with a reproducible example if you are encountering a problem.

**Comment by ManavJethani** [comment]
> @ManavJethani I have the same issue, do you have a solution? - I have updated my code, now its working fine

  // Define the command
      ```
Cypress.Commands.add("type_ckeditor", (element, content) => {
        cy.window().then((win) => {
          win.CKEDITOR.instances[element].setData(content);
        });
      });
```
      // Use the command
      `cy.type_ckeditor(cy.get(".ck-content").eq(0), "<p>HTML body</p>");`

make sure your window object has CKEDITOR instance, type window.CKEDITOR if it is there

**Comment by someshver-pri** [comment]
In drupal ckeditor 5 below code works for content insert.

```js
cy.window().then(win => {
  win.Drupal.CKEditor5Instances.forEach(editor => editor.setData('<p>Test</p>'))
})
```
