### ISSUE TITLE
Error "cannot be loaded because running scripts is disabled on this "

### ISSUE THREAD

**Issue by Kailash1980** [cypress-io/cypress#6059]
Hi,
After installing 3.8.1 I am getting the following error  when I run node_modules\.bin\cypress open in terminal

node_modules\.bin\cypress : File D:\CypressAutomation\node_modules\.bin\cypress.ps1
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ node_modules\.bin\cypress open
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException

**Comment by Kailash1980** [comment]
I found the solution 

I have faced the same problem 

Solution :
In Window::
Open Windows PowerShell
Run Set-ExecutionPolicy RemoteSigned 
Type Yes 
Now Run run command ./node_modules/.bin/cypress run  Test runner will work properly

**Comment by mayankjain2020** [comment]
Hello, I have tried the above command still facing the issue. Could you please help on this.

**Comment by romanichh** [comment]
> Hello, I have tried the above command still facing the issue. Could you please help with this.
> After running the above command as an administrator it working fine thanks for your help.

Thank you for your solution to run as administrator. It has taken a time to me to understand where is a problem.

**Comment by maniziva** [comment]
> I found the solution
> 
> I have faced the same problem
> 
> Solution :
> In Window::
> Open Windows PowerShell
> Run Set-ExecutionPolicy RemoteSigned
> Type Yes
> Now Run run command ./node_modules/.bin/cypress run Test runner will work properly

Thank you for the solution. Now its working fine.

**Comment by YuhuiRainie** [comment]
> I found the solution
> 
> I have faced the same problem
> 
> Solution :
> In Window::
> Open Windows PowerShell
> Run Set-ExecutionPolicy RemoteSigned
> Type Yes
> Now Run run command ./node_modules/.bin/cypress run Test runner will work properly

Thx, just right-click PowerShell and then select run as administrator! Everything will be fine afterwards!

**Comment by moutushisen** [comment]
> I found the solution
> 
> I have faced the same problem
> 
> Solution :
> In Window::
> Open Windows PowerShell
> Run Set-ExecutionPolicy RemoteSigned
> Type Yes
> Now Run run command ./node_modules/.bin/cypress run Test runner will work properly

Thanks for solution now it's working fn.

> Solution :
> In Window::
> Open Windows PowerShell
> Run Set-ExecutionPolicy RemoteSigned
> Type Yes
> Now Run run command ./node_modules/.bin/cypress run Test runner will work properly

**Comment by Premsing** [comment]
> I found the solution
> 
> I have faced the same problem
> 
> Solution :
> In Window::
> Open Windows PowerShell
> Run Set-ExecutionPolicy RemoteSigned
> Type Yes
> Now Run run command ./node_modules/.bin/cypress run Test runner will work properly

Not helping

**Comment by rahulpreeti** [comment]
![Set_execution_policy](https://user-images.githubusercontent.com/77009639/144634223-ec02c1ff-297d-44a0-95ce-b0a2f8497e90.PNG)

**Comment by rahulpreeti** [comment]
do not use "Run" word with the command
You have to execute only "Run Set-ExecutionPolicy RemoteSigned"
if you get error on running above command, Check instruction displaying in result
I executed "Set-ExecutionPolicy -Scope CurrentUser"
it will ask you set ExecutionPolicy, enter "RemoteSigned" & hit enter key
then enter "Yes" or "Y" & hit enter key

**Comment by IPrasadMCA** [comment]
If anyone still unable to resolve this issue with above conditions...
You can use below command by opening Windows PowerShell by clicking on Run as Administrator
Set-ExecutionPolicy Unrestricted
and click on 'Y", Then problem will be resolved
![image](https://user-images.githubusercontent.com/64774233/150918608-f9f80c16-ffcb-4231-92f6-22728d08e69c.png)

**Comment by Feruzka1706** [comment]
> do not use "Run" word with the command You have to execute only "Run Set-ExecutionPolicy RemoteSigned" if you get error on running above command, Check instruction displaying in result I executed "Set-ExecutionPolicy -Scope CurrentUser" it will ask you set ExecutionPolicy, enter "RemoteSigned" & hit enter key then enter "Yes" or "Y" & hit enter key

Thank you so much! It's working now!

**Comment by Richa729** [comment]
> I found the solution
> 
> I have faced the same problem
> 
> Solution : In Window:: Open Windows PowerShell Run Set-ExecutionPolicy RemoteSigned Type Yes Now Run run command ./node_modules/.bin/cypress run Test runner will work properly

it worked for me thanks

**Comment by nimmyranjee** [comment]
I was able to resolve as an admin . Thanks

**Comment by hanamthai** [comment]
I fixed the error, thanks.

**Comment by malithheshantha** [comment]
> If anyone still unable to resolve this issue with above conditions... You can use below command by opening Windows PowerShell by clicking on Run as Administrator Set-ExecutionPolicy Unrestricted and click on 'Y", Then problem will be resolved ![image](https://user-images.githubusercontent.com/64774233/150918608-f9f80c16-ffcb-4231-92f6-22728d08e69c.png)

Thank you it worked

**Comment by AkshayKDeshmukh** [comment]
Thank [Kailash1980](https://github.com/Kailash1980) The solution worked for me as well.

**Comment by rupak-bhuyan** [comment]
do not use "Run" word with the command
You have to execute only "Set-ExecutionPolicy RemoteSigned"
if you get error on running above command,then use command.
Set-ExecutionPolicy -Scope CurrentUser
it will ask you set ExecutionPolicy, enter "RemoteSigned" & hit enter key
then enter "Yes" or "Y" & hit enter key

**Comment by GeeTechh77** [comment]
> > I found the solution
> > I have faced the same problem
> > Solution :
> > In Window::
> > Open Windows PowerShell
> > Run Set-ExecutionPolicy RemoteSigned
> > Type Yes
> > Now Run run command ./node_modules/.bin/cypress run Test runner will work properly
> 
> Not helping

You have to open Windows power shell in administrator mode

**Comment by GeeTechh77** [comment]
![image](https://github.com/cypress-io/cypress/assets/134050126/6b7f632d-97a8-4b2d-b97a-969bfd184e6a)


If you face the above issue while running Ui 5 tooling solution Is below

Open Windows power shell – open in administration mode.
![image](https://github.com/cypress-io/cypress/assets/134050126/a30eb06c-46f6-4f8f-a457-15cb07cb2ea1)
