### ISSUE TITLE
Expect is failing but test is passing in cy.on confirm & alert message

### ISSUE THREAD

**Issue by nimit199** [cypress-io/cypress#6068]
I wanted to test my content of the confirmation message but it seems that even if my test fails my case passes
```js
it('Should Get Confirm Message', () => {
        cy.get('.button')
            .click();
        cy.on('window:confirm', str => {
            expect(2 + 2).to.equal(5);
        })
    })
```
![Error](https://user-images.githubusercontent.com/29063055/71617538-8196c880-2be1-11ea-9960-aab7dae3a1bf.png)

The issue seems to be similar to 
https://github.com/cypress-io/cypress/issues/3497
and 
https://github.com/cypress-io/cypress/issues/2413

But their solution does not work for me.
The issue persists for ```window:alert```

**Comment by dwelle** [comment]
As I explained in my [SO answer](https://stackoverflow.com/a/59542949/927631), Cypress events are not guaranteed to run within the timeframe of a test, thus without a bit more work you can't make test assertions within them.

With that being said, I believe Cypress should:
1. Display an error message when an assertion is made outside the running test.
2. The assertion itself shouldn't be displayed in Command Log in such cases.

**Comment by jennifer-shehane** [comment]
@nimit199 @dwelle  You should just need to set up the listening above the actual action right?

```js
it('Should Get Confirm Message', () => {
  cy.on('window:confirm', str => {
    expect(2 + 2).to.equal(5);
  })
  cy.get('.button').click();
})
```

**Comment by bahmutov** [comment]
I believe the test does not know that it needs to assert the window confirm, it finishes after the click then the window confirm triggers - with a failing assertion. By then the test has completed and does not change its status. The command log still shows a failing assertion though. Try adding another assertion there to force retrying until the confirm has executed

**Comment by bahmutov** [comment]
Here is an example waiting for the confirm to have been called before finishing the test
```js
/// <reference types="cypress" />
it('confirms', () => {
  cy.visit('index.html')

  let called
  cy.on('window:confirm', (text) => {
    // make the assertion fail on purpose
    // but the test does NOT wait for this assertion to pass
    // By the time the assertion fails, the test has passed
    expect(false).to.be.true
    called = true
  })

  cy.get('#click').click()
  cy.should(() => {
    expect(called).to.be.true
  })
})
```

**Comment by dwelle** [comment]
Here's my take without using state:

```js
cy.wrap(new Promise((resolve, reject) => {
  cy.on('window:confirm', msg => {
    try {
      // expect(msg).to.eq(confirmMessage); // optional
    } catch ( err ) {
      return reject(err);
    }
    resolve();
  });
  // set a timeout to ensure we don't wait forever
  setTimeout(() => {
    reject(new Error('window.confirm wasn\'t called within 4s'));
  }, 4000);
}), { log: false });
```

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
