### ISSUE TITLE
Another button is not enabled when ticking a checkbox

### ISSUE THREAD

**Issue by poponuts** [cypress-io/cypress#6077]
### Current behavior:

I have UI where I have a list of items (via checkbox) and when you ticked a checkbox, then another button (Batch Payment) will be enabled. Until you have not ticked a checkbox, the "Batch Payment" button remains disabled.

Before ticking the checkbox, the attributes below:

Checkbox A (class is not selected):
```html
<tr id="row1" class>
<input type="checkbox" name="selectedItem" value="d9d8eac0-fc23-413b-a417-1f3ceb30d847" id="id001">
```
"Batch Payment" button (with disabled attribute):
```html
<div class="small thin skip js-actionButton button disabled" id="approve-button">
<a href="#" id="ext-id002"><em class="none">&nbsp;</em>
<span class="text" automation-id="Approve-button">Batch Payment</span></a></div>
```
After ticking the checkbox, the attributes below:

Checkbox A (class is set to selected):
```html
<tr id="row1" class=" selected">
<input type="checkbox" name="selectedItem" value="d9d8eac0-fc23-413b-a417-1f3ceb30d847" id="id001">
```

"Batch Payment" button (with disabled attribute gone):
```html
<div class="small thin skip js-actionButton button" id="approve-button">
<a href="#" id="ext-id002"><em class="none">&nbsp;</em>
<span class="text" automation-id="Approve-button">Batch Payment</span></a></div>
```

This works in Selenium, but for some reason, I can't make it work using Cypress (the "Batch Payment" button remains disabled). My code below:
```js
cy.get('[type="checkbox"]').check(['d9d8eac0-fc23-413b-a417-1f3ceb30d847']);
cy.get('[automation-id="Approve-button"]').click();
```

screenshot with cypress: 
![2019-11-14 16_06_16-e2e-tests-cypress](https://user-images.githubusercontent.com/36245304/71649878-65706400-2d66-11ea-9e2b-8e76e769f310.png)

screenshot with manual / selenium:
![2019-11-14 16_06_52-e2e-tests-manual](https://user-images.githubusercontent.com/36245304/71649880-6d300880-2d66-11ea-97f1-30dfc53cf36b.png)

Sample HTML:
```html
div class="bridge-lower">
  <div class="action-bar" style="padding-top:4px;" id="ext-gen114">
    <div class="small thin skip js-actionButton disabled button" id="ext-gen71">
    <a href="#" onclick="CompanyN.widget.Tables.bulkUpdateToJs(this, 'ItemPrint.PrintItemsFromForm(&quot;selectedItems&quot;, false, &quot;Bill&quot;);', 'print', false, true); return false;" id="ext-gen72">
    <em class="none">&nbsp;</em>
    <span class="text" automation-id="Print-button">Print</span>
    </a>
    </div>
    <div id="ItemPay-pay-container">
      <div class="small thin skip js-actionButton disabled button" id="ItemPay-bills-button">
      <a href="#" id="ext-gen73"><em class="none">&nbsp;</em><span class="text" automation-id="Approve-button">Batch Payment</span></a>
      </div>
    </div>
  <table class="standard" id="ext-gen79">
    <thead>
    <tr>
    <td class="thin"><input type="checkbox" id="ext-gen115"></td>
    <td class=" ">
    <a href="/Search.aspx?ItemStatus=ItemSTATUS%2fAPPROVED&amp;graphSearch=False&amp;dateWithin=any&amp;pageSize=25&amp;orderby=ItemNumber&amp;direction=ASC">Ref
    </a>
    </td>
    <td class=" selected">
    <a href="/Search.aspx?ItemStatus=ItemSTATUS%2fAPPROVED&amp;graphSearch=False&amp;dateWithin=any&amp;pageSize=25&amp;orderby=ItemDate&amp;direction=ASC">Date
    </a>
    <span class="icons descend">&nbsp;</span>
    </td>
    <td class="date ">
    <a href="/Search.aspx?ItemStatus=ItemSTATUS%2fAPPROVED&amp;graphSearch=False&amp;dateWithin=any&amp;pageSize=25&amp;orderby=PayDate&amp;direction=ASC">Pay Date
    </a>
    </td>
    </tr>
    </thead>
    <tbody>
      <tr id="row1" class="">
        <td id="ext-gen81"><input type="checkbox" name="selectedItem" value="9cd1075a-f047-46ab-82fc-ea4bd6760b0c" id="ext-gen82">
        <input type="hidden" id="reference_9cd1075a-f047-46ab-82fc-ea4bd6760b0c" value="REFERENCE/PAY"></td>
        <td id="ext-gen83">Reference 2</td>
      </tr>
      <tr id="row2" class="">
        <td id="ext-gen98"><input type="checkbox" name="selectedItem" value="08e10c45-7777-4e3d-8045-f253413fd73e" id="ext-gen99">
        <input type="hidden" id="reference_08e10c45-7777-4e3d-8045-f253413fd73e" value="REFERENCE/PAY"></td>
        <td id="ext-gen100">Reference 3</td>
      </tr>
    </tbody>
  </table>
</div>
```

I used the cleaner code below but the problem seems to be within cypress:
```js
cy.get('table > tbody > #row1 > td > input[type="checkbox"]').check().then(()=>{
                cy.wait(3000);
                cy.get('#ItemPay-bills-button').should('be.visible');
                    // or if you want to click on the button
                cy.get('#ItemPay-bills-button').click();
            }) 
```

Lastly, `.click({force: true })` does not work as well.

### Desired behavior:
The "Batch payment" button should be enabled as per doing it manually or via Selenium. Within the Cypress runner, it remains disabled all throughout.

### Steps to reproduce: (app code and test code)
The steps are provided in the code and sample HTML above.  The actual HTML or video can be provided via secured email as I work for a company where code propriety might be an issue.

### Versions
Cypress Version (3.7.0)
Node.js Version (12.8.1)
Windows 10 OS
Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
@poponuts In the Command Log, where the `check` command runs. Click `CHECK` with devtools open. This will log to the console any relevant events. Click 'Mouse Events' to open the table of events that were fired and paste that here. 

This is likely dependent on the events that your UI is listening to to enable the button after check.

**Comment by poponuts** [comment]
Hi @jennifer-shehane , please see mouse event details below:
```
Mouse Events
cypress_runner.js:159308 
(index)
Event Type
Target Element
Prevented Default
Stopped Propagation
Active Modifiers
0	"pointerover"	input	null	null	null
1	"mouseover"	input	null	null	null
2	"pointermove"	input	null	null	null
3	"mousemove"	input	null	null	null
4	"pointerdown"	input	null	null	null
5	"mousedown"	input	null	null	null
6	"pointerup"	input	null	null	null
7	"mouseup"	input	null	null	null
8	"click"	input	null	null	null
Array(9)
0: {Event Type: "pointerover", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
1: {Event Type: "mouseover", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
2: {Event Type: "pointermove", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
3: {Event Type: "mousemove", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
4: {Event Type: "pointerdown", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
5: {Event Type: "mousedown", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
6: {Event Type: "pointerup", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
7: {Event Type: "mouseup", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
8: {Event Type: "click", Target Element: input, Prevented Default: null, Stopped Propagation: null, Active Modifiers: null}
length: 9
__proto__: Array(0)
```

Also, attached screenshot for better visuals: 
![2020-01-02 15_51_11-Cypress-mouse-events](https://user-images.githubusercontent.com/36245304/71652268-5abeca80-2d78-11ea-8686-3a61bcbc4b02.png)

**Comment by jennifer-shehane** [comment]
@poponuts It looks like all of the proper events are being fired on the input you checked. 

Do you know what event your button is listening to in order to become disabled?

**Comment by poponuts** [comment]
Hi @jennifer-shehane It is disabled by default when the frame below "Awaiting Payment" is clicked.
![2020-01-03 16_50_53-AwaitingPayment](https://user-images.githubusercontent.com/36245304/71709116-83fb5b80-2e49-11ea-8d59-c050d4227047.png)

from my HTML code above, 
`<div class="small thin skip js-actionButton button disabled" id="approve-button">`

Manually or via Selenium, it will only be "enabled" when an invoice has been ticked.

I am happy to send the actual website or video recording to replicate the issue in private if required if an email address can be provided.

**Comment by jennifer-shehane** [comment]
@poponuts Yes, support@cypress.io

**Comment by jennifer-shehane** [comment]
Unable to reproduce from examples provided. Please provide a more simplified example of test code that can be run once and fail by emailing us and we will consider reopening.

**Comment by poponuts** [comment]
I have sent a running version of the test code via support email. Thanks.

**Comment by poponuts** [comment]
I know this has been closed and @jennifer-shehane has been really patient assisting on this issue but I might include the resolution here just in case anyone encountered a similar problem in the future.
This is now working from Cypress version 4.6.0 and above by bypassing the integrity check on the script file. This is achieved by including the below on your` cypress.json` file 
```
{
  "experimentalSourceRewriting": true
} 
```
