### ISSUE TITLE
Click() on a drupal button element does not work properly

### ISSUE THREAD

**Issue by keljaus** [cypress-io/cypress#608]
### Current behavior:
I try to click the button with it's id.

The browser keeps on loading forever. When I now click the button manually from Cypress browser view I can continue

### Desired behavior:

The automation of clicking this type of button would work.

### How to reproduce:

It's a button element from Drupal. I am not sure how to reproduce it.

#### Test code:

```js
<button data-drupal-selector="edit-submit" class="button button--primary js-form-submit form-submit btn-primary btn" type="submit" id="edit-submit" name="op" value="Buy">Buy</button>

cy.get('#edit-submit').click()
```

- Operating System: El Capitan
- Cypress Version: 0.19.4
- Browser Version: Electron53

**Comment by keljaus** [comment]
Note: After a while, when I re-tested this it actually started working. For some reason it did not work properly at the beginning. I believe I did not change the test code or anything.

**Comment by brian-mann** [comment]
It's doubtful there's anything wrong with clicking the button - likely there is something wrong with the side effect of clicking the button - such as navigating to a new URL or something like that.

We'd need screenshots / stack traces / reproducible repo to look at anything. As is there's not much we can do with what's been provided.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?
