### ISSUE TITLE
The CypressRunResult TS interface is missing the runUrl attribute

### ISSUE THREAD

**Issue by robcresswell** [cypress-io/cypress#6087]
Fairly straightforward I think, but the result returned from `cypress.run()` [documented here](https://docs.cypress.io/guides/guides/module-api.html#cypress-run) mentions a `runUrl` in the return value, which is a string. However, the type definitions do not mention it, though it still appears to be in the codebase from what I can see.

**Comment by jennifer-shehane** [comment]
Released in [`3.8.2`](https://on.cypress.io/changelog#3-8-2).
