### ISSUE TITLE
Can we correctly assign assertions to a test?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6088]
Cypress v3.8.1

https://github.com/cypress-io/cypress-test-tiny/tree/confirm-after-test spec cypress/integration/two-tests.js

```js
/// <reference types="cypress" />
it('first', () => {
  setTimeout(() => {
    expect(false).to.be.true
  }, 1000)

  expect(1).to.equal(1)
})

it('second', () => {
  expect(2).to.equal(2)
  cy.wait(2000)
})
```

Notice the first test - it has an async assertion that fails after 1 second while the second test is running.

<img width="1275" alt="Screen Shot 2020-01-03 at 10 41 47 AM" src="https://user-images.githubusercontent.com/2212006/71732596-aa9f9f00-2e15-11ea-9cca-bde94a42161d.png">

The error claims the exception was thrown from the application code, but it is a test assertion. Can we accurately assign each assertion to its test?

**Comment by jennifer-shehane** [comment]
This is still an issue in 9.5.3
