### ISSUE TITLE
move binary_state.json file

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6089]
Cypress v3.8.1

When Cypress starts for the very first time after installation, it checks that it can run using a smoke test and then saves its status in JSON file. Usually this file is inside `~/.cache/Cypress/<version>/<Cypress app>/binary_state.json`. Unfortunately, this breaks the new Mac code notarization, see https://github.com/cypress-io/cypress/pull/6013#issuecomment-570678273 - no new files can be saved into the `<Cypress app>` folder.

I propose we move the `binary_state.json` file into ``~/.cache/Cypress/<version>/` folder instead.

**Comment by jennifer-shehane** [comment]
Released in [3.8.2](https://on.cypress.io/changelog#3-8-2)
