### ISSUE TITLE
watchForFileChanges doesn't work when defined in cypress.env.json

### ISSUE THREAD

**Issue by jimpriest** [cypress-io/cypress#6092]
#4239 # Current behavior:
I have cypress.json and cypress.env.json files defined.

Within cypress.env.json file I have set "watchForFileChanges": false

But it still reloads.  If I move watchForFileChanges to cypress.json it works as expected.

### Desired behavior:

If I'm in test runner and click Configuration it says:

```
Your project's configuration is displayed below. A value can be set from the following sources:
set from cypress.json file
set from cypress.env.json
```

### Steps to reproduce: (app code and test code)

* Create both cypress.json and cypress.env.json
* Add watchForFileChanges to cypress.env.json and set to false
* Make changes and notice tests re-run on changes

### Versions
Cypress 3.8.1
OS: Mac
Browser: Chrome 79

**Comment by jennifer-shehane** [comment]
`cypress.env.json` is for environment variables only. So anything that you would place within the `env` key of the `cypress.json` can be overwritten in this file. The `env` file cannot be used to change configuration values ourside of `env` that would normally be given to `cypress.json` file.

https://docs.cypress.io/guides/guides/environment-variables.html#Option-2-cypress-env-json

I can see how the wording of the configuration panel is a bit misleading in this as it seems all configuration can be set in this file, when in actually only `env` variables can be set from this file.

**Comment by Grao123** [comment]
In the newer version of Cypress, we have cypress.config.js and we should define watchforfilechanges outside setupnodeversion function

**const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {},
    watchForFileChanges: false,
    defaultCommandTimeout: 10000,
    screenshotOnRunFailure: true,
    specPattern: "cypress/e2e/**/*.cy.{js,jsx,ts,ysx}",
  },
});**

**Comment by tibioneh** [comment]
Unfortunately this is not working (anymore?) in Cypress v12.3.0 - when set in cypress.config.js
