### ISSUE TITLE
[API Test Automation] : Very slow when response body is large

### ISSUE THREAD

**Issue by hardikdiyora** [cypress-io/cypress#6098]
### Current behavior:

I have automated 4 GET API tests. Surprisingly, execution time is more than “**6 Minutes**”. For comparison, similar tests I automated in Mocha+supertest, Its taking 20 sec in total.
When I set `{$limit: 10}`, then all tests are completed very fast like in 2 sec.

### Steps to reproduce: (app code and test code)

 All tests are similar to below code.  

```js
cy.request({
    url: <URL>,
    method: 'GET',
    headers: {'Authorization' : Cypress.env('api-key')},
    qs: {cityId: ‘ABC’, $limit: 10000}
})
    .then((response) => {
        expect(response.status).to.eq(200);
        expect(validateResponseSchema(schema, response.body)).to.be.true; // using jsonschema 
        response.body.forEach(r => expect(r[‘cityId']).to.eq(‘ABC’));
    })
```

### Versions
Cypress version: ^3.8

**Comment by jennifer-shehane** [comment]
@hardikdiyora I'm not exactly sure what the issue is, since I cannot run the code you provided exactly. 

I think this line is the culprit.

```
response.body.forEach(r => expect(r[‘cityId']).to.eq(‘ABC’));
```

Indeed, adding this line to my code makes Cypress completely lock up during `cypress open` and `cypress run`. 

In my case, my `response.body` is an array in length of 500 items, so this assertions runs 500 times + 4 requests would be iterating through over 2,000 items. 

I think this is contributing to the larger timing of the test run. 

![Screen Shot 2020-01-07 at 2 31 24 PM](https://user-images.githubusercontent.com/1271364/71878607-689a9400-315a-11ea-8e55-f1f9e2ad5aba.png)

```js
it('Example', () => {
  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
  })

  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
    })

  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
    })

  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
  })
})
```

![Screen Shot 2020-01-07 at 2 38 22 PM](https://user-images.githubusercontent.com/1271364/71878992-6422ab00-315b-11ea-91a0-77a276753c8b.png)

When I split them up into 4 separate tests however, they run fine, within 4 seconds. 

```js
it('Example', () => {
  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
  })
})
it('Example 2', () => {
  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
    })
  })
it('Example 3', () => {
  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
    })
})
it('Example 4', () => {
  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then((response) => {
      expect(response.status).to.eq(200);
      response.body.forEach((r) => expect(r['cityId']).to.be.undefined)
  })
})
```

Have you tried splitting the requests into separate tests?

**Comment by hardikdiyora** [comment]
@jennifer-shehane , Yes you actually re-produced the issue but with different way. 

Also, Yes, I have 4 separate tests with each containing single cy.request(). The thing is my response body contains more than 1000 json objects, and I am validating them and that's lock up.

**Comment by Uzlopak** [comment]
forEach is traditionally very slow, as it forces the browser to create a function call for each array entry. 

Use instead a for-of-structure or a classical for-loop

**Comment by hardikdiyora** [comment]
I have changed all forEach to for-of structure, but I am not seeing any improvements.

**Comment by sainthkh** [comment]
Confirmed that there's a slowdown when there are a lot assertions. 

With Cypress, it takes about 210 seconds. 

```js
// Cypress
it('Example', () => {
  cy.request("https://jsonplaceholder.cypress.io/comments")
    .then(() => {
      const arr = []

      for(let i = 0; i < 10000; i++) {
        arr.push('ABC')
      }

      return arr
  })
  .then(arr => {
    arr.forEach((a) => expect(a).to.eq('ABC'))
  })
})
```

Only with `mocha` and `chai`, it takes 50~60**ms**. It's **ms**, not second. It's 3500x slower.

```js
const { expect } = require('chai')

it('x', () => {
  const arr = []

  for(let i = 0; i < 10000; i++) {
    arr.push('ABC')
  }

  arr.forEach((a) => expect(a).to.eq('ABC'))
})
```
