### ISSUE TITLE
Calling screenshot() on an element that changes sizes after scrolling throws 'is invalid for option "size"' exception

### ISSUE THREAD

**Issue by Keysox** [cypress-io/cypress#6099]
### Current behavior:
Using the screenshot command on an element that changes sizes after scrolling causes an exception to be thrown when trying to stitch them together.

![](https://user-images.githubusercontent.com/6796642/71846379-a084d700-3087-11ea-952f-f3616f64e4f6.png)
![](https://user-images.githubusercontent.com/6796642/71846386-a67ab800-3087-11ea-97bf-6a1a46a5ca7a.png)

```
RangeError: The value "-36960000" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:272:3)
    at Jimp.cropQuiet (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/plugin-crop/dist/index.js:42:27)
    at Jimp.<computed> [as crop] (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/core/dist/index.js:1266:23)
    at crop (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:145:26)
    at Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:209:22
    at arrayEach (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9342:14)
    at stitchScreenshots (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:206:7)
    at Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:350:21
    at processImmediate (internal/timers.js:439:21)
```

### Desired behavior:

The screenshot command should properly create an image instead of throwing an exception.

### Steps to reproduce:
See: https://github.com/Keysox/cypress-screenshot-issue

### Versions
Cypress: 3.8.1

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-59) by [Unito](https://www.unito.io/learn-more)

**Comment by Keysox** [comment]
I was thinking to put up a PR that would allow a caller to pass a `delay` argument to `screenshot()` that would fix this issue for some.

**Comment by jennifer-shehane** [comment]
I'm able to reproduce this error from the repo.

![Screen Shot 2020-01-07 at 3 33 55 PM](https://user-images.githubusercontent.com/1271364/71882597-288bdf00-3163-11ea-916c-e3d9958cb6a2.png)

**Comment by Keysox** [comment]
Thanks @jennifer-shehane!

I currently have a WIP branch that I can put a PR up for, which fixes this issue for us:
* [Adding a delay argument to screenshot](https://github.com/cypress-io/cypress/compare/develop...Keysox:screenshotDelay?w=1#diff-a684738dc2636d59e17b7ebad49368f1R308)
  * I could then use a setTimeout of 0 in order to wait for the animation to finish, allowing for visual tests to be taken at the correct time

Additionally, here are a few other ways I've thought of to fix the issue so far:
* [Change logic around stitching screenshots together](https://github.com/cypress-io/cypress/compare/develop...Keysox:fixMovingElements)
  * Unfortunately, this only handles this edge case and doesn't feel very robust
* Re-use `disableTimersAndAnimations` to fix this
  * Wouldn't allow for us to take the screenshot after our animation is finished, which is needed for visual testing
* Detect if an element has resized and if so, restart the screenshot process
  * I'd be afraid of an infinite loop with this approach
* Pass a cypress command to screenshot that would have to resolve before one is taken
  * This feels pretty robust but would require the caller to think hard about how/when to use it

**Comment by jennifer-shehane** [comment]
This is still failing in 4.9.0. Full reproducible example:

`index.html`

```html
<html>
<body>
  <main style="transform: scaleY(10); background-color: blue; height: 50vh; transition: 10s;"></main>
  <script>
    window.addEventListener('scroll', () => {
      const main = document.getElementsByTagName('main')[0]
      main.style.transform = "scaleY(1)";
    })
  </script>
</body>
</html>
```

`spec.js`

```js
it('screenshot element', () => {
  cy.visit('index.html')
  cy.get('main').screenshot()
})
```

<img width="1274" alt="Screen Shot 2020-07-07 at 11 19 20 AM" src="https://user-images.githubusercontent.com/1271364/86713084-b9287680-c043-11ea-95f5-7dabc60c9ab1.png">

**Comment by panzarino** [comment]
I've noticed that this issue isn't only related to changing the size after scrolling, there's also a bug with elements that extend beyond the top of the viewport. I've created a new issue here: https://github.com/cypress-io/cypress/issues/7966
