### ISSUE TITLE
Memory leak in desktop app

### ISSUE THREAD

**Issue by begizi** [cypress-io/cypress#61]
Upon first starting the cypress desktop app and running a project through once, the memory usage remains < 200mb. When left for several hours and run the tests multiple times, the "nwjs helper" memory consumption climbed to > 1.5gb of memory usage.

**Comment by brian-mann** [comment]
Were you running the tests headlessly or is this regular usage inside of Chrome?

**Comment by begizi** [comment]
Regular use inside chrome. I had left the app running since this morning, but increased memory consumption can be seen even after a short time monitoring the apps memory during regular use.

**Comment by brian-mann** [comment]
Ok I'll take a look. The App which runs inside of Chrome has had regular profiling done on it, and should be leak free - but the desktop app is a separate instance and that could result in some memory leaks, so it's possible.

There's actually [quite a few issues open](https://github.com/nwjs/nw.js/issues/3722) related to NWjs on memory. I'll have to look to see if there's really much I can do on my end. Could probably silently restart the process when it goes unused for 60 minutes or so just to force the memory to be flushed.

**Comment by brian-mann** [comment]
We moved off of `nwjs` in `0.14.1` and this is likely fixed by that. Doing cursory profiling on the desktop app has not indicated there are any memory leaks. Closing this for now.
