### ISSUE TITLE
applies blur to wrong element after a series of tests

### ISSUE THREAD

**Issue by spearmootz** [cypress-io/cypress#610]
### Current behavior:
when doing tests on input validation (clearing, typing, blurring), for some reason its giving me "failed because this element you are chaining off of has become detached or removed from the DOM:" error unexpectedly, if i comment out some of the previous tests run it works.

and it shows the blur being applied to the last input of the previous test for some reason

### Desired behavior:
blur should be applied to current element

### How to reproduce:
look at code below, if i comment out the first password complexity tests then the email passes. but i cannot get both to run and pass.

#### Test code:

```js
const blurOptions = {
  force: true
};

const invalidSelector = 'hwui-FormInput__has-errors';
const invalidCheckboxSelector = 'hwui-Checkbox__has-errors';

describe('validates fields', () => {
  beforeEach(() => {
    cy.visit(cy.urls.register);
  });

  it('firstName', () => {
    cy.get('#id_first_name').as('firstName');
    cy.get('@firstName').focus().blur();
    cy.get('@firstName').parent().should('have.class', invalidSelector);
    cy.get('@firstName').type('asd').blur(blurOptions);
    cy.get('@firstName').parent().should('not.have.class', invalidSelector);
  });

  it('lastName', () => {
    cy.get('#id_first_name').as('lastName');
    cy.get('@lastName').focus().blur();
    cy.get('@lastName').parent().should('have.class', invalidSelector);
    cy.get('@lastName').type('asd').blur(blurOptions);
    cy.get('@lastName').parent().should('not.have.class', invalidSelector);
  });
});
```

### Additional Info (images, stack traces, etc)
note in the picture i am selecting the email field but in the console it is saying that the password field is removed. it also happens even if both test are on the same input

![screen shot 2017-08-28 at 2 40 00 pm](https://user-images.githubusercontent.com/19737290/29787954-d4e1789e-8bfe-11e7-807f-916b1312c72e.png)

- Operating System: macOS Sierra
- Cypress Version: 
Cypress CLI: 0.13.1
Cypress App: 0.19.4

**Comment by spearmootz** [comment]
it seems to happen on all subsequent blur calls after testing 1 field in the manner shown above.

the bug seems to be specific to blur because i did have a test that filled out and submit a form after the bug got triggered and it passed successfully. always breaks on blur.  I wanted to debug and find the underlying issue but the code is not open source :(

**Comment by brian-mann** [comment]
Possibly fixed by the `0.20.0` release. Can you check to see if you still have this issue? 

Our next major release is `1.0.0` and Cypress will be open source then.

**Comment by spearmootz** [comment]
This is great news! I will try out the tests tomorrow and report! Thanks.

**Comment by spearmootz** [comment]
I tested today and encountered and error with blue in a similar test which said "Referenced tried: command is not defined"

**Comment by brian-mann** [comment]
Can you post a screenshot please. That error message does not match
anything we have.

**Comment by spearmootz** [comment]
<img width="1440" alt="screen shot 2017-09-13 at 10 39 09 am" src="https://user-images.githubusercontent.com/19737290/30383631-21f95732-9870-11e7-81d1-aa00d9ffbdaf.png">
<img width="676" alt="screen shot 2017-09-13 at 10 39 54 am" src="https://user-images.githubusercontent.com/19737290/30383634-22bc9c7e-9870-11e7-98b2-4f9a42603bb4.png">

it has something to do with blur options. when i take it off from the code above it passes sometimes, i get the random error that says that an element is not focused even though i just typed on it.

**Comment by spearmootz** [comment]
note: this still happens. ive tried to replicate this code on regular html and i havent been able to get the same error. i get this error when running on a react application.  I would attribute the error to my application if the command failed to select and type into the input, but it does so perfectly.

**Comment by Bkucera** [comment]
@spearmootz can you try removing the use of the alias in your test code? Instead, try using a cy.get() before every type

**Comment by Bkucera** [comment]
I suspect this is because rerendering of DOM elements in react, so the element that is aliased is no longer attached after an update.

**Comment by jennifer-shehane** [comment]
I think this was fixed as part of https://github.com/cypress-io/cypress/pull/2016

Please reopen a new issue if you are experiencing something similar.
