### ISSUE TITLE
Remote Development Support for online.visualstudio.com

### ISSUE THREAD

**Issue by Stewartarmbrecht** [cypress-io/cypress#6100]
### Current behavior:

Unable to run cypress when working with a remote development environment hosted 

### Desired behavior:

You can run cypress locally and connect to the remote server in the same way you can run and interact with a node application you are developing. Ideally you can run the cypress app locally while having it connect to a cypress server running in the remote environment. Unfortunately running Cypress Open while it works produces no local interface to use. 

### Steps to reproduce: (app code and test code)

Build and run a cypress project in an environment hosted by online.visualstudio.com. 

### Versions

Latest.

**Comment by Stewartarmbrecht** [comment]
Any chance someone might be able to explain if this is possible or a target feature?

**Comment by flotwig** [comment]
Hi Stewart, I don't know too much about VS Online, but if it runs on Linux and allows you to expose ports, you may be able to set up X forwarding which would allow you to use Cypress.

**Comment by sainthkh** [comment]
When we visit online.visualstudio.com, we're redirected to [Github Codespaces](https://visualstudio.microsoft.com/services/github-codespaces/). And it's still in beta. We need to wait until it gets out of beta.
