### ISSUE TITLE
Cypress not recognizing network requests

### ISSUE THREAD

**Issue by Rawnly** [cypress-io/cypress#6103]
### Current behavior:
I'm currently testing my NextJS application and I need cypress to wait for my network requests.

I've done a test page but it doens't work as expected.

Below the code of the page:
```ts
const Page = (props: any) => {
	const [isLoading, setIsLoading] = useState<boolean>(false);

	useEffect(() => {
		setIsLoading(true);
		props.store
			.get('/test/slow')
			.then(() => setIsLoading(false))
			.catch(console.error);
	}, []);

	return (
		<h1>{isLoading ? 'Loading...' : 'Loaded.'}</h1>
	);
};

```
<img width="523" alt="CleanShot 2020-01-07 at 11 46 03@2x" src="https://user-images.githubusercontent.com/16429579/71889832-4ba69680-3143-11ea-9651-33393e2253d9.png">

<img width="485" alt="CleanShot 2020-01-07 at 11 45 48@2x" src="https://user-images.githubusercontent.com/16429579/71889814-434e5b80-3143-11ea-98a2-f88d2773eef8.png">

### Desired behavior:
I'd like that cypress waits for my network request.

### Test code to reproduce
```js
	it('wait for slowww request', () => {
		cy.server();
		cy.route({
			method: 'GET',
			url: '/api/test/slow',
		}).as('slowcall');

		cy.wait('@slowcall');
		cy.log('It Works!');
	});
```

### Versions

- Mac OS `10.15.2`

```json 
{
	"next": "9.1.7",
	"react": "16.8.6",
	"react-dom": "16.8.6",
	"cypress": "^3.7.0"
}
```

**Comment by Uzlopak** [comment]
Your call is getting timing out.

See the configurations for defaultCommandTimeout, requestTimeout and responseTimeout

You could increase the values in the cypress.json
```
{
	"defaultCommandTimeout": 30000,
	"requestTimeout": 30000,
	"responseTimeout": 30000
}
```

**Comment by Rawnly** [comment]
yeah that's seems to be the error but it isn't. The call response is hardcoded to be `3000ms`

(java code below)
```java
    @GetMapping("/slow")
    public ResponseEntity slowCall() throws InterruptedException {
        Thread.sleep(1000 * 3);
        return ResponseEntity.ok().build();
    }
```

this happens with all my api requests. However I'll try to increase the timeout

**Comment by Rawnly** [comment]
The problem was that next was doing the API call on the server
