### ISSUE TITLE
Cypress Runner : Assert messages not conclusive enough

### ISSUE THREAD

**Issue by abhidp** [cypress-io/cypress#6105]
### Current behavior:
I am expecting to see an Assert message in the Cypress runner stating that it validated the length of my input value but it doesn't show any msgs when the test passes:

The code is:
```js
  it('Validate ClientList Number is 9-digits without dashes', () => {
    cy.get('[name="clientListNumber"]')
      .invoke('val')
      .should('have.length', 9)
      .and('not.contain', '-');
  });
```
![image](https://user-images.githubusercontent.com/30851622/71866816-b06deb00-315b-11ea-8769-f7f21fa5a923.png)

I expected the above image to contain a message `ASSERT  expected '039584360' to have a length of 9`

But when I change the code for it to fail deliberately, I get the expected error Assert message
The code:
```js
  it('Validate ClientList Number is 9-digits without dashes', () => {
    cy.get('[name="clientListNumber"]')
      .invoke('val')
      .should('have.length', 8)
      .and('not.contain', '-');
  });
```
![image](https://user-images.githubusercontent.com/30851622/71867058-b2847980-315c-11ea-9001-f8ef979d40b5.png)
The above assert message is expected and works fine for failed scenarios related mismatch of length of the input value. A similar length match Assert message for passed scenarios should also be shown.

### Desired behavior:

I expected the PASSed Test image to contain a message `ASSERT  expected '039584360' to have a length of 9`. Also the `ASSERT expected '039584360' to have a property length` doesn't make any sense as my test code never expected if the input value has a property of length or not. In my view it should not be displayed in the cypress runner.

### Steps to reproduce: (app code and test code)

Test Code : Please refer above under Current behavior section

### Versions
```json
  "devDependencies": {
    "cypress": "3.8.1"
  }
```

**Comment by jennifer-shehane** [comment]
This happens when you chain assertions together using the `.and()` command in this example. 

Given the 2 tests below, the 1st one logs the output as you are expecting when passing. The second one does not log the way you are expecting.

```js
it('have length', () => {
  cy.visit('index.html')
  cy.get('input').type('123').invoke('val')
    .should('have.length', 3)
})

it('have length and', () => {
  cy.visit('index.html')
  cy.get('input').type('123').invoke('val')
    .should('have.length', 3)
    .and('not.include', '-')
})
```

<img width="445" alt="Screen Shot 2020-01-08 at 5 44 52 PM" src="https://user-images.githubusercontent.com/1271364/71973932-99ec9000-323e-11ea-80ef-81b44797919f.png">

**Comment by jennifer-shehane** [comment]
This still occurs in 9.5.3
