### ISSUE TITLE
Display element that is being covered in error msg when element is covered by another element.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#611]
### Is this a Feature or Bug?
Feature

### Current behavior:
Whenever there is an error about an element not being interactable due to being covered by another element, this error displays: 

<img width="508" alt="screen shot 2017-08-30 at 3 51 08 pm" src="https://user-images.githubusercontent.com/1271364/29892120-6482eefe-8d9b-11e7-9834-d26388d24b56.png">

### Desired behavior:
It'd be nice to see the actual element that was attempted to be interacted with that is being covered (since the element being interacted with may *not* be the element you expect).

**Comment by jennifer-shehane** [comment]
We've updated the error to display the element that was attempted to be interacted with:

<img width="561" alt="screen shot 2017-08-30 at 3 53 12 pm" src="https://user-images.githubusercontent.com/1271364/29892222-d7a8d24a-8d9b-11e7-8f52-696210056be1.png">

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
