### ISSUE TITLE
cy.readFile timing out if inside a promise in a before all function.

### ISSUE THREAD

**Issue by Francismb** [cypress-io/cypress#6112]
### Current behavior:
The cy.readFile function times out when it is placed inside of a Cypress.Promise which is inside of a cy.wrap().then. 

```js
CypressError: cy.then() timed out after waiting '20000ms'.

Your callback function returned a promise which never resolved.

The callback function was:

function () {
    return new Cypress.Promise(function (resolve) {
      cy.readFile('package.json').then(function (data) {
        resolve(true);
      });
    });
  }

Because this error occurred during a 'before all' hook we are skipping all of the remaining tests.
```

### Desired behavior:

The file gets read and the contents of the file is returned.

### Test code to reproduce

```javascript
before(() => {
    cy.wrap(null).then(() => {
        return new Cypress.Promise(resolve => {
            cy.readFile('package.json').then(data => {
                resolve(true);
            })
        });
    });
});
```

### Versions

3.8.1, Windows 10, Headless electron and standard chrome 79.

**Comment by jennifer-shehane** [comment]
@frazboyz Can you explain why you are need to do this? Having the actual usecase would be helpful in evaluating the importance of this, since this example seems a bit contrived just to demonstrate the issue.

**Comment by frazboyz** [comment]
> @frazboyz Can you explain why you are need to do this? Having the actual usecase would be helpful in evaluating the importance of this, since this example seems a bit contrived just to demonstrate the issue.

Of course, I have multiple JSON environment files that are read in the before function. Inside these files, we check that the resources are available via an HTTP request, another use case could be reading an environment file, and checking that the database is setup based on some information inside the environment file.

Basically any use case where you need to read a file and run some async code in response to that. That is why the use of Cypress.Promise is required.

**Comment by jennifer-shehane** [comment]
Yeah, you don’t really need to coordinate async commands within Cypress, they are run serially no matter what. So, an couple of examples of what I think you're trying to do:

```js
before(() => {
  const files = ["foo.js", "bar.js", "baz.js"]
  const contents = []
  Cypress._.each(files, (file) => {
    cy.readFile(file).then((data) => {
      contents.push(data)
    })
  })
  .then(() => {
	// do whatever you want after all reading files is done
    console.log(contents)
  })
})
```

or

```js
before(() => {
  cy.wrap(files).each((file) => {
    cy.readFile(file).then((data) => {
      contents.push(data)
    })
  })
  .then(() => {
    // do whatever you want after all reading files is done
    console.log(contents)
  })
})
```
