### ISSUE TITLE
--headless argument still opens Chrome

### ISSUE THREAD

**Issue by MkMan** [cypress-io/cypress#6113]
### Current behavior:
Hi,

I am trying to run my tests in Chrome in headless mode. The tests run in Chrome which is good but the browser still opens as if the headless flag is not there.

The argument is picked up as shown below:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/33766083/71932757-9fbd8380-31f4-11ea-98a5-7d8010d25788.png">

### Desired behavior:

`--headless` should not open headed browser.

### Test code to reproduce

This is the command I am using `cypress run --headless --browser chrome`

### Versions
Cypress version 3.8.0
MacOS version 10.14.6

**Comment by flotwig** [comment]
Try updating to 3.8.1, where this was fixed: https://docs.cypress.io/guides/references/changelog.html#3-8-1
