### ISSUE TITLE
cy.type(force: true) doesn't type characters for readonly inputs

### ISSUE THREAD

**Issue by polom01** [cypress-io/cypress#6116]
Hello i have found one bug in newest version cypress (3.8.1). In cypress 3.4.1 can type readonly input with option {force: true} but in new version stop working.

It doesn't throw exception but don't fill the input.

**Comment by jennifer-shehane** [comment]
This is a regression in Cypress 3.5.0

`index.html`

```html
<html>
<body>
<input readonly />
</body>
</html>
```

`spec.js`

```js
it('types in readonly', () => {
  cy.visit("index.html")
  cy.get('input').type('foo', {force: true})
    .should('have.value', 'foo')
})
```

## 3.4.1

![Screen Shot 2020-01-08 at 2 33 19 PM](https://user-images.githubusercontent.com/1271364/71960700-09a15180-3224-11ea-8dd9-ad614adc7517.png)

## 3.5.0

![Screen Shot 2020-01-08 at 2 32 03 PM](https://user-images.githubusercontent.com/1271364/71960714-1160f600-3224-11ea-96dc-fb8cd0306e72.png)

## Code

It seems the check for whether we should type does properly run if `force !== true` here, so the error does not throw if it is readonly with force: true. https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.js#L328:L328

The problem though is that the actual typing is not occurring on the input. 

We did not have a test for this although we should have here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/commands/actions/type_spec.js#L224:L224

## Workaround

Downgrade to Cypress 3.4.1.
