### ISSUE TITLE
Cypress run my first test file but not the rest

### ISSUE THREAD

**Issue by jboucly** [cypress-io/cypress#6117]
When I run my tests on my dev (heroku) server the tests do not work fully, it stops on the end of the first test file and does not continue with the other test files.
It reloads the page but no longer displays anything on chrome or electron.
The weird thing is that when I do it with my local server (http://localhost:4200) everything works perfectly ...

Another bizarre behavior is that when I stop the chrome or electron page that launches my tests and I restart there, the tests start again where they stopped
A response to this bug?
Thank for your help.

ScreenShot screen bug : 
![image](https://user-images.githubusercontent.com/33218155/71963019-09d92700-31fb-11ea-811a-1778a947d8e5.png)

### Current behavior:

The first test file is executed but the others do not...

### Desired behavior:

All my test runs.

### Test code to reproduce
My first file test : 
```js
/// <reference types="cypress" />

import { LoginService } from '../../plugins/service/login.service';
import { RegisterService } from '../../plugins/service/register.service';
import { EmailSubject } from '../../plugins/shared/email_subject';
import { SharedService } from '../../plugins/shared/shared.service';

describe('Test register in Socle-Full-JS', (): void => {

    beforeEach(function (): void {
        cy.fixture('user_1').then((user1): void => {
            this.user1 = user1;
        });
        cy.fixture('user_2').then((user2): void => {
            this.user2 = user2;
        });
    });

    it('Register and logout ramdom user on Socle', function (): void {
        RegisterService.setTypeInRegisterForm(false, this.user1);
        cy.get('p.ng-star-inserted').contains(this.user1.firstName);
        LoginService.logoutUser(true);
    });

    it('Register and logout ramdom user on Socle with button enter', function (): void {
        RegisterService.setTypeInRegisterForm(true, this.user2);
        cy.get('p.ng-star-inserted').contains(this.user2.firstName);
        LoginService.logoutUser(true);
    });

    it('Validated register the first user', function (): void {
        SharedService.setTypeInEtherealForm();
        cy.get('tbody > :nth-child(1) > :nth-child(2) > a').should('contain.text', EmailSubject.WELCOME).click();
        SharedService.clickLinkInIframe();
        RegisterService.checkMessageValidateEmail();
    });

    it('Validated register second user', function (): void {
        SharedService.setTypeInEtherealForm();
        cy.get(':nth-child(2) > :nth-child(2) > a').should('contain.text', EmailSubject.WELCOME).click();
        SharedService.clickLinkInIframe();
        RegisterService.checkMessageValidateEmail();
    });
});
```

My second file test not execute : 

```js
/// <reference types="cypress" />

import { LoginService } from '../../plugins/service/login.service';
import { RouteName } from '../../plugins/shared/route_name';

describe('Test login on Socle-Full-JS', (): void => {

    beforeEach(function (): void {
        cy.fixture('user_1').then((user1): void => {
            this.user1 = user1;
        });
        cy.fixture('user_2').then((user2): void => {
            this.user2 = user2;
        });
    });

    it('Login and logout user on Socle', function (): void {
        LoginService.loginUser(this.user1.email, this.user1.password, true, true, RouteName.SHOWCASE_PATH);
        LoginService.logoutUser(true);
    });

    it('Login and logout user on Socle with button enter', function (): void {
        LoginService.loginUser(this.user2.email, this.user2.password, false, true, RouteName.SHOWCASE_PATH);
        LoginService.logoutUser(true);
    });
});
```
### Versions

3.8.1

**Comment by jboucly** [comment]
Login.service.ts : 

`import { RouteName } from '../shared/route_name';

export class LoginService {
    static frontUrl: string = Cypress.env('FRONT_URL');

    static loginUser(email: string, password: string, isClick: boolean, isVisit: boolean, urlTest: string): void {
        if (isVisit) {
            cy.visit(this.frontUrl + RouteName.LOGIN_PATH);
        } else {
            cy.get(':nth-child(1) > a').click();
        }
        cy.get('#USERNAME').type(email);
        if (isClick) {
            cy.get('#PASSWORD').type(password);
            cy.get('.login-form-button').click();
        } else {
            cy.get('#PASSWORD').type(`${password}{enter}`).wait(3000);
        }
        cy.url().should('eq', this.frontUrl + urlTest);
    }

    static logoutUser(isInShowcase: boolean): void {
        if (isInShowcase) {
            cy.get(':nth-child(1) > a').click();
        }
        cy.get('.QATEST-account > .ant-menu-submenu-title').click();
        cy.get('.QATEST-account > .ant-menu > .ng-star-inserted > .ant-menu-item > a').click();
        cy.url().should('eq', this.frontUrl + RouteName.SHOWCASE_PATH);
    }
}`
register.service.ts : 
`import { NzMessage } from '../shared/nz_message';
import { RouteName } from '../shared/route_name';

export class RegisterService {

    static setTypeInRegisterForm(
        isEnter: boolean,
        user: { firstName: string; lastName: string; email: string; password: string; organizationName: string }
    ): void {
        cy.visit(`${Cypress.env('FRONT_URL')}${RouteName.REGISTER_PATH}`);
        cy.get('#FIRST_NAME').type(user.firstName);
        cy.get('#LAST_NAME').type(user.lastName);
        cy.get('#EMAIL').type(user.email);
        cy.get('#PASSWORD').type(user.password);
        cy.get('#PASSWORD_CONFIRM').type(user.password);
        if (isEnter) {
            cy.get('#ORGANIZATION_NAME').type(`${user.organizationName}{enter}`).wait(3000);
        } else {
            cy.get('#ORGANIZATION_NAME').type(user.organizationName);
            cy.get('.register-form-button').click().wait(3000);
        }
    }

    static checkMessageValidateEmail(): void {
        cy.get('#cdk-overlay-0 > *').contains(NzMessage.EMAIL_VALIDATED);
    }
}`

email_subject.ts : 

`export enum EmailSubject {
    WELCOME = 'Bienvenue', 
    FORGOT_PASSWORD = 'Mot de passe oublié'
}`

Shared.service.ts : 

`import { FixtureName } from './fixture_name';

// eslint-disable-next-line
const random = require('random-name');

export class SharedService {
    // USER \\

    static setUsersInFixtureFile(): void {
        cy.writeFile(FixtureName.USER1_PATH, this.getRandomUserObject());
        cy.writeFile(FixtureName.USER2_PATH, this.getRandomUserObject());
    }

    static getRandomUserObject(): { firstName: string; lastName: string; email: string; password: string; organizationName: string } {
        const firstName = random.first();
        const lastName = random.last();
        const email = `${firstName}.${lastName}@test.fr`;
        return {
            firstName,
            lastName,
            email,
            password: 'password',
            organizationName: 'Organization'
        };
    }

    static setNewPasswordInUserFixture(
        user: { firstName: string; lastName: string; email: string; password: string; organizationName: string },
        newPwd: string,
        filePath: string
    ): void {
        user.password = newPwd;
        cy.writeFile(filePath, user);
    }

    // EMAIL \\

    static setTypeInEtherealForm(): void {
        cy.visit(Cypress.env('MAIL_URL'));
        cy.get('#address').type(Cypress.env('MAIL_ADDRESS'));
        cy.get('#password').type(`${Cypress.env('MAIL_PASSWORD')}{enter}`);
        cy.get(':nth-child(4) > .nav-link').click();
    }

    static clickLinkInIframe(): void {
        cy.get('iframe').then((iframe: JQuery<HTMLElement>): void => {
            const body = iframe.contents().find('body');
            cy.wrap(body).find('a').click().wait(1000);
        });
    }

}`

fixture_name.ts : 

`export enum FixtureName {
    USER1 = 'user_1.json',
    USER2 = 'user_2.json',
    USER1_PATH = 'cypress/fixtures/user_1.json',
    USER2_PATH = 'cypress/fixtures/user_2.json'
}`

**Comment by jboucly** [comment]
After setting the 
`modifyObstructiveCode parameter:  false`
no change

**Comment by avallete** [comment]
Hi there !

I would like to help you but to be honest your issue is difficult to understand.

Here some suggestion to help other people to help you:

- Use proper formatting (you can use triple back-tick to surround your code `` ``` ``and even add some syntax coloration by giving him the language like so: `` ```js ``
- Use [MRE](https://stackoverflow.com/help/minimal-reproducible-example) instead of copy/pasting all your code. Specially when a lot of code are involved, it's way easier to help debug an issue when you can simply copy/paste little snippet or even clone a repo and then compile/debug it on your machine.
- Edit your previous messages as much as you can. It prevent you to flood your own issue and keep it readeable for other people.

That said, and for what I've been able to see from your issue, it look like you do a LOT of stuff around the simple test (loading fixtures, doing IO operations, custom services, ...).

I would recommend to use the 2nd point mentioned above, reduce your test case to the minimal (simply to basic test case like `1 == 1` into multiples tests files), and then, incrementally add your code logic to nail down where your bug occurs really.

Something looking like:

1. Does two simple basics tests into two different files are properly runs one after another ?
2. Does the import of other modules break my tests ?
3. Does the visit on the targeted url work properly ?
4. Does the usage and loading of my fixtures is working ?
5. Test one by one your custom services, does they break your tests ?

**Comment by jennifer-shehane** [comment]
@jboucly You didn't provide the code for `plugins/shared/route_name`, so the code above is not runnable, but I would agree with @avallete advice above in general. Please reduce the problem to a smaller example, removing all unnecessary code. 

Providing a repository that can be forked and run without having to copy and paste 7 files would also be best. Thanks.

**Comment by jboucly** [comment]
@jennifer-shehane 
I found my error while reading the good practice of cypress. thank you !
