### ISSUE TITLE
Update verbiage in Cypress application to display what commands 'yield' as opposed to 'return'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#612]
### Is this a Feature or Bug?
Feature

### Current behavior:
Cypress has been very careful to update the verbiage in it's documentation to specify what a command 'yields' (and very rarely 'returns'). [See the documentation on `cy.get()` for example.](https://on.cypress.io/get#Yields)

But, the Cypress app itself often uses the incorrect verbiage of 'returns' when the command actually 'yields'. For example, this is the current log to the console when clicking on a `cy.get()` command from the Command Log, notice the use of the word **Returned**:

<img width="569" alt="screen shot 2017-08-30 at 4 03 37 pm" src="https://user-images.githubusercontent.com/1271364/29892535-e7b47904-8d9c-11e7-943f-e7991da9d8ac.png">

### Desired behavior:
The app verbiage should accurately reflect the behavior of the command, whether it yields or returns.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
