### ISSUE TITLE
cypress-cli type for CypressRunResult::runs is incorrect (can be null/undefined)

### ISSUE THREAD

**Issue by xdumaine** [cypress-io/cypress#6126]
### Current behavior:

In the event that the browser fails to connect, the run promise resolves with results which has `runs` of `null` or `undefined`. (Which is likely a separate issue altogether. It should probably not resolve at all - it should reject).

However, the typings indicate that the type of `runs` is `RunResult[]` which doesn't match `null`

### Desired behavior:

The type should indicate that `runs` can be undefined or null, or `run()` should not resolve on an error running the tests altogether.

### Test code to reproduce

1. Clone https://github.com/xdumaine/cypress-test-tiny
2. `npm i && npm test`

**Comment by ddayguerrero** [comment]
👋 Hey! While there might be work in progress, I'd be interested in helping and ultimately achieving a first time contribution for Cypress.

Following the instructions within the `cypress-test-tiny` fork, I've been able to reproduce the error with the following environment:

```
Cypress:    3.8.1
Browser:    Chrome 79
```

As previously mentioned and from my understanding, there are currently a couple of ways of solving this:

1. Playing around with the `CypressRunResult` type interface to support `null` or `undefined` special types.
2. Handling the _rejected_ state upon invoking the promise.

Option 2 sounds like the long term solution. I think changes will be around the lines of https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/plugins/util.coffee#L37 however it seems like we would need to distinguish `before:browser:launch` and `task` events.

Can I help with with 2, with the short term solution 1, or with any other suggested solution?

**Comment by jennifer-shehane** [comment]
@ddayguerrero Yes we would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by xdumaine** [comment]
@jennifer-shehane my PR is ready for final review...
