### ISSUE TITLE
Improve visibility algorithm

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#613]
Take into account the following scenarios:

* If an element is outside the bounds of an `overflow: hidden` ancestor (OA), but its offset parent is an ancestor of OA, the element is still visible
* If an element is position relative and outside the bounds of an `overflow: hidden` ancestor, the element is hidden

**Comment by chrisbreiding** [comment]
The code for this is done, but has yet to be released. We'll update this issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)
