### ISSUE TITLE
cy.visit randomly not loading the web application.

### ISSUE THREAD

**Issue by sarfrazwk** [cypress-io/cypress#6132]
I am testing Cypress to see If we can use it for the automation of our test cases.
I have created 4 test cases. And, `cy.visit(desired link)` is placed in `beforeEach` 

Current behavior:

Sometimes all four of them run and pass without issues. 
Randomly, web application doesn't load correctly for one of the four test cases. Console displays the following message:

```
Uncaught syntax error: Unexpected end of input
```

Desired behavior:

Every time `cy.visit(desired link)` is launched I should be able to land on the Login screen.

Versions:

Windows 10 Pro
Cypress 3.8.1
Chrome 79

I have also added `"modifyObstructiveCode":false` in the `cypress.json`

Issue screenshot attached.

If somebody knows what's happening and how can it be fixed, please let me know. Thank you.

![image](https://user-images.githubusercontent.com/19843800/72092549-87c32e00-32e0-11ea-8368-7ad56965ba9b.png)

**Comment by jennifer-shehane** [comment]
Hey @sarfrazwk, the error indicates that you have an uncaught syntax error being thrown from you application itself. Open up DevTools and click the giant yellow error to see the full stack trace of where this error is being thrown.

Also, if you'd like to ignore this uncaught exception being thrown from within your application, follow these instructions: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

**Comment by sarfrazwk** [comment]
Hi Jennifer,
Thank you for your prompt reply.

Before posting the issue here, I had already followed your suggestions.

1. There is no "Giant yellow arrow". 
![1](https://user-images.githubusercontent.com/19843800/72165435-7e47cd80-3395-11ea-8da9-db8f553d15c1.png)

After cy.visit(desired link) the XHR request (web api call) should be made.
But it is not happening. It goes in error at cy.visit. I am attaching the image of a test case that passed before it
![3](https://user-images.githubusercontent.com/19843800/72165621-cf57c180-3395-11ea-9f2d-21c7d76f5bac.png)

2. If I ignore this uncaught exception, the webelement on the webpage is not found and it goes in timeout. Tests are blocked.

If it is an issue of the application then why randomly all of them pass or it gives the uncaught exception error on one of them.

Thanks.

**Comment by jennifer-shehane** [comment]
1. I original asked you to click on the 'giant yellow error', not 'arrow'. The block of text on the page that has a yellow background. 

![72092549-87c32e00-32e0-11ea-8368-7ad56965ba9b copy](https://user-images.githubusercontent.com/1271364/72237269-41374180-3608-11ea-947d-b645e85887b2.png)

We'll need a reproducible example provided in order to move forward debugging this issue. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Comment by sarfrazwk** [comment]
Hi Jennifer,
I am sorry that I completely misunderstood what you wrote. This time I clicked on the yellow area and got this

![Error](https://user-images.githubusercontent.com/19843800/72267868-c6adf800-35ee-11ea-9e4b-cb4474ee21b9.png)

On Thursday, we made some changes to the code. Now we are not getting anymore "Unexpected end of input" but "Invalid or unexpected token" as uncaught SyntaxError.

Thanks.

**Comment by jennifer-shehane** [comment]
@sarfrazwk Your application may be using "frame busting". By default Cypress modifies code it detects as frame busting so the application under test runs properly in the Cypress Test Runner (which runs your app inside an iframe itself). Can you try disabling this by setting `modifyObstructiveCode=false` in your configuration? Further explanation can be found here: https://on.cypress.io/configuration#modifyObstructiveCode

This is a bit of a guess though since I can't run the code provided.

**Comment by sarfrazwk** [comment]
Hi Jennifer,

Thanks again for your prompt reply.
 
I have already tried without success:
"modifyObstructiveCode":false in the cypress.json

Thanks.

**Comment by jennifer-shehane** [comment]
@sarfrazwk We'll need a reproducible example provided in order to continue any work towards addressing your issue at this point. There's nothing we can do without that.

**Comment by hwood-sp** [comment]
Got here via google, as I also was getting "Unexpected end of input" in my Cypress tests --

> Can you try disabling this by setting modifyObstructiveCode=false in your configuration?

This seems to have fixed it!

To spell it out, add to your `cypress.json`:

```
{
  "modifyObstructiveCode": false
}
```

**Comment by queicherius** [comment]
Just for other people coming here via Google, for me the case was that I was using TypeScript with Cypress, and starting all processes at the same time seemed to remove/overwrite the typescript output. Adding a bit of time between starting the processes solved the issue.

**Comment by cadesalaberry** [comment]
I had the same issue, the fix took me a while. My problem was with how angular mangles the `index.html` file.
```html
...
<script>
  function getName() {
    // do not show in production
    if (window.production) return '';
    return 'beta';
  }
</script>
```
the code would turn into a single line of js, leading to a `Unexpected end of input`
```html
<script>
  function getName() {    // do not show in production    if (window.production) return '';    return 'beta';  }
</script>
```

Which would lead to the end of the code being commented out. Turning them into multi-line comments did the trick.

```html
...
<script>
  function getName() {
    /* do not show in production */
    if (window.production) return '';
    return 'beta';
  }
</script>
```

```html
<script>
  function getName() {    /* do not show in production */    if (window.production) return '';    return 'beta';  }
</script>
```
