### ISSUE TITLE
"No files found in" error, when trying add --config testFiles["**/*.js","**/*.coffee"] to open command

### ISSUE THREAD

**Issue by abaybabaydabudidabuday** [cypress-io/cypress#6135]
I have the problem with `--config testFiles["pattern"]` (example from official docs https://docs.cypress.io/guides/references/configuration.html#Command-Line) 

I'm using this command to open cypress 
```
NODE_PATH=cypress cypress open --config watchForFileChanges=false,testFiles=["**/*.js","**/*.coffee"] --env configFile=staging
```

### Current behavior:

I'm getting error - 

>No files found in /Users/ranger/Developer/powr/cypress/integration 

(as on screenshot)

![image](https://user-images.githubusercontent.com/50987561/72148566-5ffcc480-33cb-11ea-95d0-0d17ea910273.png)

### Desired behavior:
Actually I want to open scope of my smoke test files. And i'm trying to use `testFiles` array and input my file names inside. And can't use array anyway. 

Want to mention that it works when i'm using only 1 pattern (not array, just string)
```
NODE_PATH=cypress cypress open --config watchForFileChanges=false,testFiles="**/*.js" --env configFile=staging
```

### Test code to reproduce
it's cli command, and not related to test code. Tried on 3.4.1 & 3.8.1 versions.

### Versions

Cypress 3.8.1 
Mac OS Mojave
Chrome browser

**Comment by jennifer-shehane** [comment]
I can't recreate the behavior as explained. 

```
cypress open --config watchForFileChanges=false,testFiles=["**/*.js","**/*.coffee"] --env configFile=staging
```

![Screen Shot 2020-01-13 at 12 51 49 PM](https://user-images.githubusercontent.com/1271364/72236005-7db46e80-3603-11ea-9289-e853806c0993.png)

Please provide the project structure or the configuration required to reproduce this and we will consider reopening. My project has no configuration and a single `spec.js` file in `cypress/integration`.
