### ISSUE TITLE
Freezes during manual tests

### ISSUE THREAD

**Issue by craig-dae** [cypress-io/cypress#6137]
Summary: 

I can't reproduce reliably. It started happening sometime in the past few weeks. We wrote about half a dozen integration tests on a new project before it started happening.

I'll run a test manually, using the UI. It's a coin-flip whether it freezes or runs smoothly. It will usually freeze when the app is loading initially. It will freeze less often, after the preloading animation, somewhere usually near the beginning of the tests. It will usually complete the test if gets through maybe the first 25% of the test.

It will sometimes freeze for 10s and then unfreeze. This causes the test to fail due to timeout. It usually freezes long enough for me to grow impatient and kill it. I'll then go back to the cypress UI, select the test, and run it again, and it's another coin-flip as to whether it gets through.

This is not me doing hundreds of tests. This is freezing when I run one single test. The test clicks a few buttons and fills out a form. The most complicated thing in it is `cy.server()` and some `cy.wait(@example)` calls to wait for some web services to return before continuing.

I have not seen the test fail when I do `npx cypress run`, only when I do npx cypress open.

I'm testing an Angular project, if you think that might be relevant.

Please advise on troubleshooting steps. 

### Current behavior:

Freezes, about half the time, when tests are run manually through the UI. Causes tests to fail when it unfreezes. Doesn't always unfreeze. 

### Desired behavior:

Don't freeze. 

### Test code to reproduce

I can not provide a test example for this. Happens with all of my tests now, even very simple ones. Possible that it is something external to Cypress, but I'm not sure what, since my app doesn't freeze outside of cypress. 

### Versions
Cypress package version: 3.8.1
Cypress binary version: 3.8.1
Angular 8.2.6
Node: v10.18.0 and v13.6.0 (I just upgraded to see if it fixed the problem. It did not)

**Comment by c32hedge** [comment]
What browser and OS?

**Comment by jennifer-shehane** [comment]
Honestly, there is nothing we can do without a reproducible example. 

Can you provide some sample code of what you are doing, configuration you have set, a video of the UI freezing. There could be a number of things causing Chrome to freeze, including a memory leak in your own application. 

This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment with any of the information above and we will consider reopening.

**Comment by craig-dae** [comment]
Browser: Version 79.0.3945.88 (Official Build) (64-bit)
OS

[~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
[~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Amazon
Description:	Amazon Linux release 2 (Karoo)
Release:	2
Codename:	Karoo

@jennifer-shehane Sure thing. I don't care whether you keep this ticket open or closed, as long as I can try to use it to give you the feedback you need. I've been strongly advocating Cypress on our project, and I've gotten everyone to use it for our pre-push hooks. If we don't figure out what's going on here, we may have to switch to Selenium, which is what the testers prefer. I think that developers should write their own tests, and I have preferred Cypress for developer-written tests (for integration and functional tests), and left the testers to Selenium for testing customer requirements.

**Comment by craig-dae** [comment]
Also note that when it freezes, the rest of my Workspaces is not frozen. For example, I continue to see http activity in the terminal that I used to open Cypress.

**Comment by craig-dae** [comment]
New information ...

After running a test, that I froze the first time but went through the second time, I started clicking around. I needed to see why the test failed. The entire thing froze. It has been about 2 minutes and it hasn't unfrozen yet. 

Is there a log or something somewhere that I can send you?

**Comment by c32hedge** [comment]
@craig-dae I wonder if you're seeing this: https://github.com/cypress-io/cypress/issues/6023

Have you tried downgrading to Chrome 78? That's what I had to do when my tests started hanging. It looks like Cypress maintains downloads for older Chrome versions: https://chromium.cypress.io/

**Comment by craig-dae** [comment]
That seems to match my experiences, except I'm on CentOS, not Ubuntu. 

I don't see an rpm file in the linux downloads that cypress maintains. I'm struggling a bit to figure out how to install it. I'm going to keep trying.

**Comment by jennifer-shehane** [comment]
@craig-dae If you can, when running your tests select "Electron 78" during `cypress open`, this will not use Chrome 79 and would isolate the cause of the issue to Chrome. 

![Screen Shot 2020-01-14 at 12 11 04 PM](https://user-images.githubusercontent.com/1271364/72317235-f6c8ca00-36c6-11ea-9745-9695ffa672a6.png)

To take an extra step in isolating it to the Chrome version (and not our Electron install), you can download the last stable Chrome 78 version from this url https://chromium.cypress.io/ and see if the freezing can be isolated to a specific Chrome version.

<img width="887" alt="Screen Shot 2020-01-14 at 12 10 01 PM" src="https://user-images.githubusercontent.com/1271364/72317215-ea447180-36c6-11ea-9f5d-efac7345150b.png">

**Comment by craig-dae** [comment]
@jennifer-shehane , I think we're getting somewhere. I didn't realize I could switch to Electron that easily. I've run about half a dozen times. It hasn't frozen, and any sluggishness that was there is gone now. I didn't realize how sluggish it was being until using Electron. 

I tried to install Chrome 78 yesterday, but couldn't figure it out before quitting for the day. I don't see an RPM or anything in the Linux install zip, and I don't see anything else that looks like an obvious installer script. I'm willing to try a few different versions to isolate where the problem started, if you can save me the time of figuring out how to install.

**Comment by c32hedge** [comment]
@craig-dae Comment 24 on this Chromium issue gives an RPM for Chrome 78: https://bugs.chromium.org/p/chromium/issues/detail?id=1036742#c24

**Comment by craig-dae** [comment]
Thanks hedge. 

Downgraded to 78. I've run 3 tests without freezing, and with a noticeable reduction of slugishness.

**Comment by craig-dae** [comment]
@c32hedge , I'm seeing other weirdness with Chrome now that I've rolled back. Electron might be the better option. 

Reloading my app gets stuck. No idea why. No JS errors, no web service calls. Fixed by going back to 79 or by using Electron.

**Comment by craig-dae** [comment]
Summary of issues for anyone else who comes here: 

Cypress is freezing on Chrome version 79 when run manually (through the UI). If you have 79, which is the latest version as of today, the problem is Chrome, NOT CYPRESS. 

There are two solutions. I prefer the first: 
1) Select the Electron browser from within Cypress instead of Chrome
2) Rollback to version 78 of Chrome (link above)

I prefer #1 because it doesn't involve rolling back Chrome, which is a huge pain. Also, Chrome had some other weird behavior for me, where it struggled when I tried to reload the app I'm writing.

Thanks Cypress Team (@jennifer-shehane) for your help!

**Comment by jennifer-shehane** [comment]
Marking as duplicate of https://github.com/cypress-io/cypress/issues/6023
