### ISSUE TITLE
Groups should not require Build Id 

### ISSUE THREAD

**Issue by kuroiokami** [cypress-io/cypress#6139]
### Current behavior:

When using the grouping tag it must have a build id to be able to use the groups tags. As there are times where we aren't running cypress with a ci tool (For example with Bitbucket Pipelines I need to run my windows test against a standalone windows server) I can't use the group flag.

### Desired behavior:

In the example you gave in a thread we could use the group and tag functions in to do something like --group Windows --tag staging . But unless I get the system to generate a possibly arbitrary build id then I can't use the group flag.

### Test code to reproduce

Just add the group tag when not in a CI system.

### Versions

3.8.1

**Comment by jennifer-shehane** [comment]
@kuroiokami A CI Build ID is required for us to be able to associate separate `cypress run` commands together - there is no other way, we need a unique ID. 

You can pass your own completely unique generated id by using the `--ci-build-id` flag whenever you are not running in an environment where Cypress can automatically generate one. 

- `--ci-build-id` flag: https://on.cypress.io/command-line#cypress-run-ci-build-id-lt-id-gt
- How we get this ID when they're not provided: https://on.cypress.io/parallelization#CI-Build-ID-environment-variables-by-provider
