### ISSUE TITLE
Angular auto reload hangeth

### ISSUE THREAD

**Issue by alastair-todd** [cypress-io/cypress#6140]
Just hit a big ball of mud with angular and webpack.

Effectively the workaround is running` ng serve --live-reload=false` with the auto reload flag off (not ideal)

However it nearly cost me my life getting there.

There is some race condition between cypress aborting xhrs - which includes the web socket open for auto reloading the angular app.

You get this error in the console:

> sockjs.js:2999 WebSocket connection to 'ws://localhost:4200/sockjs-node/502/xincxufb/websocket' failed: WebSocket is closed before the connection is established.

It seems it tries to abort before its been opened!? and then the thing gets opened...and never dies and the test hangs forever.

<img width="602" alt="xhr" src="https://user-images.githubusercontent.com/595192/72174820-7fe3b680-33d2-11ea-8246-e366d8be33c7.png">

This only started happening when testing a reasonably weighty page that was making real API requests...

**Comment by jennifer-shehane** [comment]
@alastair-todd Any insight on what solved your issue? May be helpful to others in the future.

**Comment by alastair-todd** [comment]
The test was hanging for another reason - simple as that.
