### ISSUE TITLE
Do not truncate Command Log message in default commands

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#6145]
### Current behavior:

Logs from `cy.log` are now truncated at 50 lines: https://github.com/cypress-io/cypress/issues/5625
But logs from `cy.get` not.

### Desired behavior:

I wanted to know if we can add a global option in `cypress.config` that tells cypress to apply the same truncate logic as it does on manual `cy.log` calls?

### Test code to reproduce

use `cy.get` with a very large selector and let it fail. You are not able to determine the failure from the screenshot:

```js
describe("3.8.2", () => {
    it("truncate", () => {
        cy.visit("https://cypress.io")
            .get("#page-content > div:nth-child(2) > div > main > section.index-hero.Hero__StyledHero-sc-15j8hrl-2.kegIwW.gatsby-image-wrapper > div > h1 > div")
            .should("not.be.visible")
    })
})
```

![image](https://user-images.githubusercontent.com/3234900/72217214-ba149b80-352b-11ea-8e9d-f9b48d24ff17.png)

### Versions

3.8.2

**Comment by jennifer-shehane** [comment]
We would likely just extend the same stylings for other commands as `cy.log()`. 

Making this configurable is problematic because setting the truncation too large will cause the browser to lock up in some circumstances currently. 

Can you explain the use case for needing this configurable as opposed to always showing up to 50 lines?

**Comment by gabbersepp** [comment]
> We would likely just extend the same stylings for other commands as `cy.log()`.
> 
> Making this configurable is problematic because setting the truncation too large will cause the browser to lock up in some circumstances currently.
> 
> Can you explain the use case for needing this configurable as opposed to always showing up to 50 lines?

Please have a look at the screenshot above. You see that the locator is not fully visible. For us this is problematic because we have a complex application with deeply nested elements and thus the locator are very long.

For example:
+ i create an object that has an id 123456
+ i create an object that has an id 345567
+ i want to display object 123456 in a subview within the AUT
+ I test if the object is in the subview
+ the test fails
  + and is showing only a partial selector
  + the subview shows an object 

Now I see that an object was displayed but the test fails. As i do not see the full selector, I do not know which object was used within the `cy.get`. So I have to assume that it might have been failed because of the wrong object beeing loaded. This now forces me to analyze where the data is loaded wrongly. This costs time and it is not guaranteed that I can fix the bug because I never know if this was the real error.

Now you might argue that our selectors are too long. But The structure of the application does not allow to reduce the length and keep readability at all places. 

But I understand that this is something you probably don't want to implement. Do you think that this can be done by using a cypress plugin? Then I can create one that fits exactly our usecase.

**Comment by jennifer-shehane** [comment]
@gabbersepp Yes, I understand the need to show more of the info in the error, up to 50 lines like the `cy.log()`. We can do this. 

I was asking why you believed this needed to be configurable and not just show 50 lines max always for every default command?

**Comment by gabbersepp** [comment]
@jennifer-shehane sorry. Now I understand what you mean. I do not know if this behaviour is necessary for all user and for all commands. So adding a true/false flag to the config would avoid applying this breaking feature to all user

**Comment by jennifer-shehane** [comment]
@gabbersepp I wouldn't consider this a breaking change. Should be good to extend the truncation to 50 lines.
