### ISSUE TITLE
Clicking buttons inside an iframe fails in headless Chrome only

### ISSUE THREAD

**Issue by allwefly** [cypress-io/cypress#6152]
### Current behavior:

Play/Pause buttons inside of the body of an embedded Youtube video on a webpage (in an iframe) are not found in headless Chrome 79 and test is failing. The same test passes in headless Electron 78 as well as headed Chrome 79 and headed Canary 81. 
```
CypressError: Timed out retrying: Expected to find element: 'button[aria-label="Play"]', but never found it. Queried from element: <body.date-20200113.de_DE.ltr.exp-invert-logo.exp-kevlar-settings.exp-responsive.exp-search-big-thumbs.site-center-aligned.site-as-giant-card.webkit.webkit-537>
```

### Desired behavior:

I know iframes are a bit of a murky area with Cypress, I just cannot figure out why there is a difference and the same test fails only in headless Chrome. Ideally the desired behavior would be the Play/Pause buttons to be found inside of the Youtube iframe body in headless Chrome.

### Test code to reproduce

```js
cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell')
  cy.get('iframe[title="youtube video"]').then(($iframe) => {
    const $body = $iframe.contents().find('body')
    cy.wrap($body).find('button[aria-label="Play"]').click()
    cy.wrap($body).find('button[aria-label="Pause (k)"]').click()
})
```

### Versions

Cypress 3.8.1, Windows 10, headless Chrome 79

Screenshots

Failed test in headless Chrome 79:
![cmd_rJBhY6dx0s](https://user-images.githubusercontent.com/19595532/72265226-6cc42700-361c-11ea-91e9-45c21d658d59.png)

Passed test in headless Electron 78:
![cmd_KftnodqORY](https://user-images.githubusercontent.com/19595532/72265246-7c437000-361c-11ea-8c1a-445bf205e8cd.png)

Passed test in headed Chrome 79:
![chrome_1I4joyyACV](https://user-images.githubusercontent.com/19595532/72265258-7fd6f700-361c-11ea-9184-023215ee3695.png)

**Comment by jennifer-shehane** [comment]
I can't get the provided test case to run in 3.8.2 as pasted. Am I missing something?

<img width="1203" alt="Screen Shot 2020-01-13 at 9 59 43 PM" src="https://user-images.githubusercontent.com/1271364/72268386-1bce2600-3650-11ea-8835-54a6d04c2629.png">

**Comment by allwefly** [comment]
Sorry, I haven't updated to 3.8.2 yet. My screenshots are from 3.8.1. Let me update real quick and I will let you know.

**Comment by allwefly** [comment]
@jennifer-shehane 
I have no problem running the test in 3.8.2 
![chrome_Itmw8JOKgZ](https://user-images.githubusercontent.com/19595532/72269619-3094c480-3624-11ea-960a-d1762beb4dee.png)

Attaching also a screenshot of my cypress.json file if it can give any additional information:
![idea64_UIGTvpZ288](https://user-images.githubusercontent.com/19595532/72269850-8e291100-3624-11ea-9ed3-9986c6902cab.png) 

Please let me know what other information I can provide in order to assist.

**Comment by jennifer-shehane** [comment]
The test requires having `chromeWebSecurity: false` in the `cypress.json` which was not originally specified.

Once I got the scenario running, I was not able to reproduce the failure in chrome headless 79 however. Ran it a few times.

<img width="837" alt="Screen Shot 2020-01-14 at 1 44 16 PM" src="https://user-images.githubusercontent.com/1271364/72322169-0e5a7f80-36d4-11ea-9f01-763a14b669f7.png">

**Comment by allwefly** [comment]
@jennifer-shehane 
After your reply, as funny as it sounds I thought of what's the difference between you and me - I live in Germany. And I should have figured this out earlier with the error that Cypress threw at me: _"Queried from element: <body.date-20200113.**de_DE**.ltr.exp-invert..."_ . It turns out and this is quite unexpected behavior for me that there is a difference with locale in headless and headed Chrome. Not sure if it isolated to Youtube iframe only, but I suspect so. 

Fixed by passing browser arg on launch in the pluginsFile

```js
    on('before:browser:launch', (browser = {}, args) => {        
        if (browser.name === 'chrome') {        
          args.push('--lang=en-US')        
          return args      
        }  
    })
```
Really sorry for the waste of your time. Thanks for the help!

**Comment by jennifer-shehane** [comment]
@allwefly No worries, it's not the first time I've seen locale differences with tests. 

It's usually good practice to set one in your tests. You can also set timezone for datetime variations as a machine environment variable like `TZ=America/New_York cypress run`.

**Comment by zillerehman** [comment]
> @jennifer-shehane
> I have no problem running the test in 3.8.2
> ![chrome_Itmw8JOKgZ](https://user-images.githubusercontent.com/19595532/72269619-3094c480-3624-11ea-960a-d1762beb4dee.png)
> 
> Attaching also a screenshot of my cypress.json file if it can give any additional information:
> ![idea64_UIGTvpZ288](https://user-images.githubusercontent.com/19595532/72269850-8e291100-3624-11ea-9ed3-9986c6902cab.png)
> 
> Please let me know what other information I can provide in order to assist.

please send code of that test

**Comment by SonaliAvaya** [comment]
Well , i know this issue closed but i got the same error like you got at first time  @jennifer-shehane  
![image](https://user-images.githubusercontent.com/62263280/90688550-9db4ac00-e23c-11ea-865d-a5fecd4088d0.png)

**Comment by jgonzalezalbisu** [comment]
Still hapenning
