### ISSUE TITLE
cy.type('') should be treated as no-op instead of throwing an error

### ISSUE THREAD

**Issue by c32hedge** [cypress-io/cypress#6157]
### Current behavior:

Calling `cy.type` with the empty string throws the error

> CypressError: cy.type() cannot accept an empty String. You need to actually type something.

I saw https://github.com/cypress-io/cypress/issues/3587 that was closed, but the request there seemed to imply that passing the empty string to `cy.type()` should implicitly clear the input.

Instead, I propose that `cy.type('')` should simply be a no-op. The rationale is that it sometimes makes sense to include `cy.type()` in a chain of commands even when the input could be the empty string. In these situations, instead of being able to include the `cy.type()` even when "typing" the empty string would be a no-op, we have to special-case the empty string to prevent the error above.

For example, I would like the ability to write a helper function for testing many different inputs to a field with the following pattern:

```js
testInput(inputValue) {
  cy.get(<inputField>)
    .clear()
    .type(inputValue);
}
```

But instead, I have to do the following, just to avoid passing the empty string to `cy.type()`. In this example, I want to run the rest of the commands in the chain, but I can't chain `cy.type()` due to the current behavior:

```js
testInput(inputValue) {
  cy.get(<inputField>)
    .clear()
    .then(e => { if (inputValue !== '') cy.wrap(e).type(inputValue) });
}
```

### Desired behavior:

Calling `cy.type('')` should be a no-op, and return the same subject it was called on. It should behave as if the customer literally typed _nothing_.

### Test code to reproduce

```js
describe("type", () => {
  testSearch(inputValue) {
    cy.get('input')
      .clear()
      .type(inputValue)
      .type('{Enter}');
  }

  before(() => {
    cy.visit('https://www.google.com');
  });

  it('Searches for documentation on cy.type', () => {
    testSearch('cy.type');
  });

  it('Tries an empty search', () => {
    testSearch(''); // Currently explodes
});
```

### Versions

Cypress 3.8.1

**Comment by bahmutov** [comment]
Can't you check in the helper function and do early return?
```js
  testSearch(inputValue) {
    if (!inputValue) {
      return
    }
    cy.get('input')
      .clear()
      .type(inputValue)
      .type('{Enter}');
  }
```

**Comment by c32hedge** [comment]
@bahmutov The problem is that the other commands in the chain are _not_ no-ops in the empty string case. You would still want the `cy.clear()` and `cy.type('{Enter}')` to execute. In the real example that made this come up, I made that exact mistake and then my test was using the value that was left in the input field by the previous test.

**Comment by c32hedge** [comment]
Seems like it would be pretty easy to change `cy.type()` to just not throw this special-cased error message, but as another "option", could we at least add a key to the `options` object for `cy.type()` to suppress the error? Something like `noErrorOnEmptyString` with a default of `false`?

**Comment by jennifer-shehane** [comment]
In this case, we would recommend overwriting the `.type()` command to handle empty strings gracefully. 

I've added an example below, although you will like want the overwritten command definition in your `support/index.js` or `support/commands.js` file. 

```js
Cypress.Commands.overwrite('type', (originalFn, subject, str, options) => { 
  if (str !== '') {
    return originalFn(subject, str, options)
  }

  return subject
})

it('.type() - type into a DOM element', () => {
  cy.visit('index.html')

  const arr = ['fake', 'text', '', 'here']
  cy.wrap(arr).each((str) => {
    cy.get('input')
      .clear()
      .type(str).should('have.value', str)
  })
})
```

<img width="538" alt="Screen Shot 2020-01-22 at 7 30 49 PM" src="https://user-images.githubusercontent.com/1271364/72896265-b9f77580-3d4d-11ea-9715-12bf1f66a041.png">

**Comment by CodeTroopers** [comment]
I have the same need. It would be nice if it could be activated from options

**Comment by kristapsmelderis** [comment]
use case:
As a test automation engineer,
I would like to reuse my test code that handles filling a large form that has many optional fields,
by replacing the input model that is passed to the method as test data

`fillTheBigForm(testdatamodel.bigForms.formInput)`

if `type()` would handle empty strings, it simplifies the ability to reuse code, as I do not have to write many functions AND testdata models, as I would be able to simply have the same testdata model, but with empty strings as values. Test Data then can be loaded from external sources in cases where test data sets can become rather large.

`fillTheBigFormExceptOptionalStuffA(testdatamodel.bigForms.datasetA)`
`fillTheBigFormExceptOptionalStuffB(testdatamodel.bigForms.datasetB)`
`fillTheBigFormExceptOptionalStuffC(testdatamodel.bigForms.datasetC)`

Maybe I am not understanding some Cypress paradigm that would fit in this case and I am not following some best practice? But, well, here is my use case.

**Comment by jennifer-shehane** [comment]
You can overwrite `.type()` to achieve this today - see https://github.com/cypress-io/cypress/issues/6157#issuecomment-577171154

**Comment by matthiasmoier** [comment]
We have the same need in the test setup for our app and used your proposed workaround. But personally, I would also prefer to have this as an option in Cypress directly rather than overwriting the command.

**Comment by TestIsTest001** [comment]
I know this is an old thread but what does Cypress._.noop and Cypress._.isEmpty mean? .i cannot seem to find a proper documentation on it.
