### ISSUE TITLE
Runtime error for ES2015 import of SCSS module 

### ISSUE THREAD

**Issue by senseforce-james** [cypress-io/cypress#6159]
### Current behavior:

I have several test files in my project, with folder structure:
```
cypress
    > integration
        > folder 1
        > folder 2
```

Folder 1 contains all my existing tests, which run fine. Folder 2 is new and only has a single test in it. When I attempt to run it, I receive the following error.

![image](https://user-images.githubusercontent.com/57433746/72330025-199eb280-36b6-11ea-9fc4-d1904c434af0.png)

This error does not seem to be related to the content of the test itself, as it is thrown even when the test is empty. If I move the breaking test into Folder 1, the issue appears to be resolved (this is not a practical solution for this project however).  

The only fix I have been able to find for this issue is to change from an ES2015 "import" to using "require". 

#### Working

```js
const styles = require("./colors-editor.module.scss");
```
#### Not working

```js
import styles from "./colors-editor.module.scss";
```

I have many other SCSS modules used throughout the code, and can see no reason why this one is being treated differently. 

### Desired behavior:

ES2015 import of SCSS module should not break Cypress test

### Versions

Cypress 3.6.1 / 3.8.2 (tried updating to solve issue) 

node-sass 4.13.0

react 16.11.0

Ubuntu 19.10 / Windows 10

Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Do you have a preprocessor setup for Cypress? https://on.cypress.io/preprocessors-api 

Could you include an example of the `scss` file with its export so that we can run and test this ourselves?

**Comment by senseforce-james** [comment]
plugins/index.js
```
const cypressTypeScriptPreprocessor = require("./cy-ts-preprocessor");

module.exports = on => {
	on("file:preprocessor", cypressTypeScriptPreprocessor);

	on("before:browser:launch", (browser = {}, args) => {
		console.log(`Testing on ${browser.name}`);
		if (browser.name === "chrome") {
			args.push("--disable-dev-shm-usage");
			return args;
		}

		return args;
	});
};
```

plugins/cy-ts-preprocessor.js
```
const wp = require("@cypress/webpack-preprocessor");

const webpackOptions = {
	resolve: {
		extensions: [".ts", ".js"]
	},
	module: {
		rules: [
			{
				test: /\.ts$/,
				exclude: [/node_modules/],
				use: [
					{
						loader: "ts-loader"
					}
				]
			}
		]
	}
};

const options = {
	webpackOptions
};

module.exports = wp(options);

```

colors-editor.module.scss (file doesn't have a specific export, is just imported as a whole)
```
.container {
	margin-top: 1rem;
	margin-bottom: 3.5rem;
}

.label {
	margin-bottom: 1rem;
	font-size: 1.2rem;
	font-weight: 600;
	line-height: 1.5;
	letter-spacing: 0.1px;
	color: #9ea0a5;
	text-transform: uppercase;
}

.grid {
	display: grid;
	grid-template-columns: repeat(5, 1fr);
	grid-column-gap: 10px;
	grid-row-gap: 10px;
}
```
Thanks!

**Comment by jennifer-shehane** [comment]
Your webpack config doesn't have any configuration to handle `scss` files. You need to configure some type of scss loader just like you did to handle ts files.

**Comment by senseforce-james** [comment]
Thanks for your help! Unfortunately I'm now unable to reproduce the issue but I'll try your solution the next time it happens.
