### ISSUE TITLE
Stubbed Fetch requests not detected by Cypress, despite being sent as XHR

### ISSUE THREAD

**Issue by AnderssonChristian** [cypress-io/cypress#6167]
### Current behavior:

Fetch workaround posted in #95 and on [Stubbing window-fetch](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window-fetch#readme) does not work when loading the polyfill from Cypress. My application does not have any polyfills and so I opted for doing it like in [polyfill-fetch-from-tests-spec.js](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/stubbing-spying__window-fetch/cypress/integration/polyfill-fetch-from-tests-spec.js).

### Test code to reproduce

spec.js:

```js
describe.only('Blah', () => {
  before(() => {
    doStuff();
    cy.visit('http://root:pass@localhost:8080/foobar/index.html');
  });

  it('Bleh', () => {
    cy.server();
    cy.route({
      url: 'test.cgi',
      method: 'POST'
    }).as('test');

    cy.get('[data-cy=send').click();
    cy.wait('@test');
  });
});
```

support/index.js:

```js
Cypress.on('window:before:load', win => {
  var unfetch = require('unfetch');
  delete win.fetch;
  win.fetch = (url, options) =>
    // Since we are using relative url's in the application, we need to parse these correctly
    unfetch(
      `http://localhost:8080${url.charAt(0) === '/' ? url : `/foobar/${url}`}`,
      options
    );
});
```

However Cypress is not picking these up. The requests *are* being send via XHR though, as seen in Chrome: 
![image](https://user-images.githubusercontent.com/12988898/72451384-1db4f800-37bc-11ea-9d1a-e551c11cddce.png)

I also added a control in my React app just for troubleshooting:

```js
//Fetch
fetch('test', {method: 'POST'});
//XHR
var http = new XMLHttpRequest();
http.open('POST', 'test', true);
http.send();
```

Both work, but only the latter is being picked up by Cypress. Investigating the requests in the network tab, the *only* difference I can see is that the `Referer` header is the "original" in the XHR variant, while the polyfilled XHR one has that header set to `http://localhost:8080/__cypress/iframes/integration/guide/spec.js`.

![image](https://user-images.githubusercontent.com/12988898/72452063-3245c000-37bd-11ea-8221-97f64e5e31d5.png)

Could this be a bug?

### Versions

Cypress 3.70, Chrome 73, Debian Jessie.

**Comment by AnderssonChristian** [comment]
Found the solution here: https://github.com/cypress-io/cypress/issues/6167

**Comment by jennifer-shehane** [comment]
Hey @AnderssonChristian that link links back to this issue

**Comment by AnderssonChristian** [comment]
@jennifer-shehane oops. Updated the link
