### ISSUE TITLE
Detect browser/renderer crashes 

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#6170]
### Current behavior:

Cypress doesn't know if the browser tab crashes during a test.

### Desired behavior:

Cypress detects browser tab crashes/browser crashes and exits cleanly after printing some debug information.

Dependency of: #349 

### Issues that this would make easier to debug

* Random hanging in Docker: https://github.com/cypress-io/cypress/issues/8206

**Comment by jennifer-shehane** [comment]
Related issue for sending crash reports from Electron https://github.com/cypress-io/cypress/issues/1660
