### ISSUE TITLE
setCookie() does not recognize domain correctly 

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#6173]
### Current behavior:

This is a strange issue that happened to my CICD env, but I can't reproduce it locally. I only post it here just to see if anyone has the same problem or can make sense of this. If this issue is too hard to investigate due to the lack of reproducibility, feel free to close it as it is.

So I have this line: `cy.setCookie('django_language', locale)` of code.
On my local env, my domain is `localhost` so it works perfectly
On my CICD env, my domain is `test.company.fe` and below is the console print of this cookie:
```
console.info called
Arguments:
[
  {
    "type": "string",
    "value": "Cookie Set: 'django_language'"
  },
  {
    "type": "object",
    "className": "Object",
    "description": "Object",
    "objectId": "{\"injectedScriptId\":2,\"id\":13}",
    "preview": {
      "type": "object",
      "description": "Object",
      "overflow": true,
      "properties": [
        {
          "name": "name",
          "type": "string",
          "value": "django_language"
        },
        {
          "name": "value",
          "type": "string",
          "value": "de"
        },
        {
          "name": "path",
          "type": "string",
          "value": "/"
        },
        {
          "name": "domain",
          "type": "string",
          "value": "company.fe"
        },
        {
          "name": "secure",
          "type": "boolean",
          "value": "false"
        }
      ]
    }
  }
]
```

Please notice `"value": "company.fe"` in the domain section. 

### Desired behavior:

The correct value should be `.company.fe` or `test.company.fe`

### Test code to reproduce
See comment above

### Versions
Cypress 3.8.0
CICD: docker node:10.13 with chrome 79
Local: Mac 10.14.6 with chrome 79

**Comment by jennifer-shehane** [comment]
@Songyu-Wang Leading dots in domain names (.company.fe) are ignored and shouldn't effect the behavior. 

You didn't exactly describe what the problem is here. Is something functionally not working? Because this seems like expected behavior when setting cookies.

**Comment by Songyu-Wang** [comment]
`Leading dots in domain names (.company.fe) are ignored and shouldn't effect the behavior.`
@jennifer-shehane I assume you mean it is ignored by cypress. That is irrelevant to the use case here. I set the cookie so my application can use it and display accordingly. I do not expect cypress to do anything with it.
 `You didn't exactly describe what the problem is here. Is something functionally not working? Because this seems like expected behavior when setting cookies.`
Here is the problem:
My full url is `http://test.company.fe:9002`
when I set the cookie, the cookie domain is `company.fe`
so this cookie would apply to url starts with `company` which is not the case since my url starts with `test`
The correct behavior should be `.company.fe`(with leading dot to apply this cookie to subdomain) or `test.company.fe`(full domain)

**Comment by Songyu-Wang** [comment]
As a workaround, I have to input domain when set cookie by getting current url and get the substring between `//` and `:` so this cookie will be applied to given full url

**Comment by Songyu-Wang** [comment]
which seems like should be the default behavior

**Comment by jennifer-shehane** [comment]
>Leading dots in domain names (.company.fe) are ignored and shouldn't effect the behavior.

No, what I mean is that leading dots on domain names do not affect it's application to subdomains within browsers, per spec: https://tools.ietf.org/html/rfc6265#section-4.1.2.3

The leading dot is not necessary for the cookie to apply to all subdomains.

>The Domain attribute specifies those hosts to which the cookie will
   be sent.  For example, if the value of the Domain attribute is
   "example.com", the user agent will include the cookie in the Cookie
   header when making HTTP requests to example.com, www.example.com, and
   www.corp.example.com. https://tools.ietf.org/html/rfc6265#section-4.1.2.3

**Comment by corwinstephen** [comment]
Related to https://github.com/cypress-io/cypress/issues/5688 ?

**Comment by Songyu-Wang** [comment]
@jennifer-shehane Then I have no idea.... Based on the doc you provided, I agree the leading dot does not matter, but the behavior I observed is different

**Comment by Songyu-Wang** [comment]
@corwinstephen Thank you! I think https://github.com/cypress-io/cypress/issues/5688#issuecomment-566751048 is related, but I only see one cookie set instead of two.

**Comment by Songyu-Wang** [comment]
This is not likely to get anywhere. Close it as it is
