### ISSUE TITLE
Behavior of reload() is not the same as on other browsers

### ISSUE THREAD

**Issue by kamiloski** [cypress-io/cypress#6177]
I want to do simple test. I have angular base page with dropdown where are some inputs - filters. 
When I fill any of them with some text and I save it dropdown is closing and value is remembered in this imput. In cypress test after fill and save this input and use `cy.reload()`, value in input is cleared. But when I do it (refresh page by F5) in normal browser chrome/IE/FF input is still filed with this value.
Why behavior is different? Is it possible to reload page with the result that input will be fillet with value?

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example that we can run to see the issue and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
