### ISSUE TITLE
Cypress verify command failing with no changes to docker image

### ISSUE THREAD

**Issue by drewbrend** [cypress-io/cypress#6182]
### Current behavior:

Cypress verify step has started claiming that a dependency is missing.

We have used the same dockerfile and image for over a year.  It is the same base docker image our application uses, but has steps to install the cypress dependencies and verify by following https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies

This has worked perfectly but just today started failing.  We have a similar setup in several different repos and they have all started failing at once, so I suspect this is an issue with cypress or one of its dependencies and not with our configuration.

I added a call to `apt list --installed` in the dockerfile and verified that each dependency listed in the cypress docs appeared in the installed list, so I know they are all there.  Unfortunately the output from the cypress verify stage does not specify which dependency it thinks is missing.

See the output with `DEBUG=cypress.*` below (I removed some sensitive paths with `[.....]`, otherwise it's as it was outputted in CI):

> Step 16/16 : RUN DEBUG=cypress* /[....]/node_modules/.bin/cypress verify
> 
>  ---> Running in a6bcccfd3372
> 
> 2020-01-16T21:21:40.748Z cypress:cli:cli cli starts with arguments ["/usr/bin/node","/[....]/node_modules/.bin/cypress","verify"]
> 
> 2020-01-16T21:21:40.750Z cypress:cli NODE_OPTIONS is not set
> 
> 2020-01-16T21:21:40.750Z cypress:cli:cli program parsing arguments
> 
> 2020-01-16T21:21:40.753Z cypress:cli parsed cli options {}
> 
> 2020-01-16T21:21:40.806Z cypress:cli verifying Cypress app
> 
> 2020-01-16T21:21:40.807Z cypress:cli checking environment variables
> 
> 2020-01-16T21:21:40.822Z cypress:cli checking if executable exists /root/.cache/Cypress/3.8.2/Cypress/Cypress
> 
> 2020-01-16T21:21:40.824Z cypress:cli Binary is executable? : true
> 
> 2020-01-16T21:21:40.824Z cypress:cli binaryDir is  /root/.cache/Cypress/3.8.2/Cypress
> 
> 2020-01-16T21:21:40.824Z cypress:cli Reading binary package.json from: /root/.cache/Cypress/3.8.2/Cypress/resources/app/package.json
> 
> 2020-01-16T21:21:40.827Z cypress:cli Found binary version 3.8.2 installed in: /root/.cache/Cypress/3.8.2/Cypress
> 
> 2020-01-16T21:21:40.828Z cypress:cli could not read binary_state.json file at "/root/.cache/Cypress/3.8.2/binary_state.json"
> 
> 2020-01-16T21:21:40.828Z cypress:cli {}
> 
> 2020-01-16T21:21:40.828Z cypress:cli is Verified ? undefined
> 
> 2020-01-16T21:21:40.828Z cypress:cli force verify
> 
> 2020-01-16T21:21:40.828Z cypress:cli running binary verification check 3.8.2
> 
> It looks like this is your first time using Cypress: 3.8.2
> 
> 
> 
> [21:21:40]  Verifying Cypress can run /root/.cache/Cypress/3.8.2/Cypress [started]
> 
> 2020-01-16T21:21:40.833Z cypress:cli clearing out the verified version
> 
> 2020-01-16T21:21:40.835Z cypress:cli undefined DISPLAY environment variable
> 
> 2020-01-16T21:21:40.835Z cypress:cli Cypress will spawn its own Xvfb
> 
> 2020-01-16T21:21:40.835Z cypress:cli needs Xvfb? true
> 
> 2020-01-16T21:21:40.835Z cypress:cli Starting Xvfb
> 
> 2020-01-16T21:21:40.852Z cypress:cli disabling Electron sandbox
> 
> 2020-01-16T21:21:40.852Z cypress:cli running smoke test
> 
> 2020-01-16T21:21:40.852Z cypress:cli using Cypress executable /root/.cache/Cypress/3.8.2/Cypress/Cypress
> 
> 2020-01-16T21:21:40.852Z cypress:cli smoke test command: /root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=574
> 
> 2020-01-16T21:21:40.852Z cypress:cli smoke test timeout 30000 ms
> 
> 2020-01-16T21:21:41.002Z cypress:cli Smoke test failed: { Error: Command failed: /root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=574
> 
> 
> 
> 
> 
>     at makeError (/[....]/node_modules/cypress/node_modules/execa/index.js:172:9)
> 
>     at Promise.all.then.arr (/[....]/node_modules/cypress/node_modules/execa/index.js:277:16)
> 
>     at <anonymous>
> 
>     at process._tickCallback (internal/process/next_tick.js:189:7)
> 
>   code: null,
> 
>   stdout: '',
> 
>   stderr: '',
> 
>   failed: true,
> 
>   signal: 'SIGSEGV',
> 
>   cmd: '/root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=574',
> 
>   timedOut: false,
> 
>   killed: false }
> 
> 2020-01-16T21:21:41.003Z cypress:cli error message: Command failed: /root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=574
> 
> 
> 
> 
> 
> 2020-01-16T21:21:41.007Z cypress:cli Stopping Xvfb
> 
> [21:21:41]  Verifying Cypress can run /root/.cache/Cypress/3.8.2/Cypress [failed]
> 
> [21:21:41] → Cypress failed to start.
> 
> 
> 
> This is usually caused by a missing library or dependency.
> 
> 
> 
> The error below should indicate which dependency is missing.
> 
> 
> 
> https://on.cypress.io/required-dependencies
> 
> 
> 
> If you are using Docker, we provide containers with all required dependencies installed.
> 
> 
> 
> ----------
> 
> 
> 
> Command failed: /root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=574
> 
> 
> 
> ----------
> 
> 
> 
> Platform: linux (Ubuntu Linux - 18.04)
> 
> Cypress Version: 3.8.2
> 
> Cypress failed to start.
> 
> 
> 
> This is usually caused by a missing library or dependency.
> 
> 
> 
> The error below should indicate which dependency is missing.
> 
> 
> 
> https://on.cypress.io/required-dependencies
> 
> 
> 
> If you are using Docker, we provide containers with all required dependencies installed.
> 
> 
> 
> ----------
> 
> 
> 
> Command failed: /root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=574
> 
> 
> 
> ----------
> 
> 
> 
> Platform: linux (Ubuntu Linux - 18.04)
> 
> Cypress Version: 3.8.2
> 
> The command '/bin/sh -c DEBUG=cypress* /[....]
/node_modules/.bin/cypress verify' returned a non-zero code: 1
> 
> script returned exit code 1

### Desired behavior:

cypress verify should pass

### Versions

Originally was using 3.4.1 when the issue was first discovered, then upgraded to latest 3.8.2 and still saw the same issue.

**Comment by drewbrend** [comment]
This appears to have started working again for us so I'm closing this issue.

**Comment by dschwank** [comment]
We are facing the same issue, by now it did not resolve "magically" - it seems like one of these packages are causing the error:

```
libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libgcrypt20 libglapi-mesa libglx-mesa0 libgnutls30 libllvm8 libsystemd0 libudev1
```

**Comment by drewbrend** [comment]
Yes, we've started seeing this consistently again.  We had something work that tricked me into thinking this was resolved but it was only fixed on one repo.  We're seeing this as well still.

Since I closed this https://github.com/cypress-io/cypress/issues/6184 was logged which is the exact same issue, I won't re-open this since they duplicate each other.

**Comment by jennifer-shehane** [comment]
Duplicate of #6184
