### ISSUE TITLE
Incorrect Node version is being shown in Setting tab

### ISSUE THREAD

**Issue by vinod236** [cypress-io/cypress#6186]
Incorrect Node version is being shown in Setting tab

Actual :
    Node  version 12.8.1 is being shown in setting tab

Expcted :
   Node Version 12.14.1 should be shown in setting tab.

Version Details:
  Cypress 3.8.2
  OS : Win 10 Enterprise (64 bit)
  Chrome : 79.0.3945.117 (64 
![NodeIssue](https://user-images.githubusercontent.com/7825972/72626988-b50f7c00-3971-11ea-8a33-a3630fb93676.GIF)
bit)

**Comment by jennifer-shehane** [comment]
Please click on the 'Node Version' section in Settings to see a full explanation of where this NodeVersion comes from and how you can override it with your system node version. 

<img width="802" alt="Screen Shot 2020-01-22 at 1 18 02 PM" src="https://user-images.githubusercontent.com/1271364/72871564-b0541a80-3d19-11ea-850a-c7f78ab36dd8.png">
