### ISSUE TITLE
Update browser icons to use branded iconography

### ISSUE THREAD

**Issue by trydionel** [cypress-io/cypress#6188]
### Current behavior:

The Test Runner uses the Chrome font-awesome icon for many browser logos, and the Firefox logo is out-of-date with Mozilla's current branding. With cross browser support nearly complete, we should take the opportunity to use official, branded iconography for all of the browsers we support.

<img width="169" alt="Screen Shot 2020-01-17 at 1 01 15 PM" src="https://user-images.githubusercontent.com/104908/72636272-b2d6fe80-392c-11ea-8c1d-3fba9800c48d.png">

### Desired behavior:

- [ ] Replace all usage of font-awesome browser logos with the proper branded icon
  - [ ] Edge: https://github.com/alrra/browser-logos/tree/master/src/edge
  - [ ] Firefox: https://github.com/alrra/browser-logos/tree/master/src/firefox
  - [ ] Chrome: https://github.com/alrra/browser-logos/tree/master/src/chrome
  - [ ] Chrome Canary: https://github.com/alrra/browser-logos/tree/master/src/chrome-canary
  - [ ] Chromium: https://github.com/alrra/browser-logos/tree/master/src/chromium
  - [ ] Electron: https://github.com/alrra/browser-logos/tree/master/src/electron
- [ ] The test runner allows users to test against arbitrary Chromium browsers. If given a name (e.g. `brave`), attempt to find the correct icon in the `browser-logos` package. If no icon matches, continue to use the `.fa-globe` icon.
- [ ] Increase the size of the browser logo in the Test Runner from 14px to 24px. Ensure all text that follows is vertically centered with the logo.

**Comment by chrisbreiding** [comment]
> The test runner allows users to test against arbitrary Chromium browsers. If given a name (e.g. brave), attempt to find the correct icon in the browser-logos package. If no icon matches, continue to use the .fa-globe icon.

My concern with this is that we would have to ship Cypress with all the logo images included, which could increase its size a decent bit. Maybe we should decide on a subset of browsers to include, so the size increase is limited? Thoughts, @cypress-io/test-runner?

@jennifer-shehane, @brian-mann, where did we land on what to do for the Electron logo? Actual Electron logo, chromium logo, globe icon?

**Comment by trydionel** [comment]
Yea, that's a fair concern. Even just grabbing the SVGs of the 6 browsers outlined above would suffice for the most common cases. That should add well under 100kb to the overall package size.

**Comment by flotwig** [comment]
Released in [`4.0.0`](https://on.cypress.io/changelog#4-0-0).
