### ISSUE TITLE
Cypress error while open htpps site

### ISSUE THREAD

**Issue by calinepatriota** [cypress-io/cypress#6192]
Im testing a HTTPS site, and after the script put the credencials to log in, its not login with success. I've opened the security sheet's page and notice that a error about certificate was showed.

**Comment by jennifer-shehane** [comment]
When opening a pull request, please fill out the [pull request template](https://github.com/cypress-io/cypress/blob/develop/PULL_REQUEST_TEMPLATE.md) provided - it requires necessary information we need to move forward with reviewing pull requests. 

This PR will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#pull-requests). Please open a new PR filling out the pull request template including an explanation for why this PR is necessary.
