### ISSUE TITLE
SyntaxError: F:\CYPRESS\cypress.json: Unexpected end of JSON input

### ISSUE THREAD

**Issue by sivasgit** [cypress-io/cypress#6195]

**Comment by onadikuda** [comment]
I got the same issue today and would you be able to post the fix.

**Comment by bahmutov** [comment]
Is cypress.json empty or does it have a json syntax error?

**Comment by onadikuda** [comment]
Yeah it had syntax error and I have corrected it. Thanks for your response

**Comment by Ihtisham-Khattak** [comment]
> ### Current behavior:
> ### Desired behavior:
> ### Test code to reproduce
> ### Versions

I had the same problem. That is what you are facing now. I think you should delete the `baseurl` from `cypress.json` with `ctrl+a,` with it you also delete the braces {} in which your whole `baseurl` is. In the `cypress.js `type the braces and your problem will be solved
