### ISSUE TITLE
Unable to scroll the grid table and inspect the element (Assertion) in a cell simultaneously

### ISSUE THREAD

**Issue by yalaIrfan** [cypress-io/cypress#6201]
### Current behavior:

I have some 92 records in a grid table with scroll option but at single time on 15 rows are visible. Suppose if I want to inspect one cell with some string assertion (lets say that row is number is 50 and not visible). my assertion is failing because that row is not visible at all. `cy.get('.ui-grid-viewport')` has length of only 13 elements.

### Desired behavior:
Will it possible while scrolling get all the rows and inspect the string

### Test code to reproduce

```js
cy.get('.ui-grid-viewport > .ui-grid-canvas > .ui-grid-row').contains('div  >  .ui-grid-cell:nth-child(1) > .ui-grid-cell-contents',_code1.toUpperCase())
cy.get('.ui-grid-viewport > .ui-grid-canvas > .ui-grid-row').contains('div  >  .ui-grid-cell:nth-child(2) > .ui-grid-cell-contents',_description1.toUpperCase())
```

error:
```
CypressError: Timed out retrying: Expected to find content: 'AAFGIAKGPHOA' within the element: [ <div.ui-grid-row.ng-scope>, 12 more... ] and with the selector: 'div  >  .ui-grid-cell:nth-child(1) > .ui-grid-cell-contents' but never did.
```

### Versions

https://legacy.datatables.net/release-datatables/examples/basic_init/scroll_y_infinite.html

**Comment by jennifer-shehane** [comment]
As shown in the live example, the rows of the table do not exist in the DOM until scrolling has taken place, so it is impossible for Cypress to evaluate more rows than actually exist in the DOM. 

<img width="954" alt="Screen Shot 2020-01-21 at 3 18 32 PM" src="https://user-images.githubusercontent.com/1271364/72789084-67d92600-3c61-11ea-933f-25206b77cd50.png">

Please utilize the [`.scrollTo()`](https://on.cypress.io/scrollTo) and/or [`.scrollIntoView()`](https://on.cypress.io/scrollIntoView) commands offered by Cypress to test the scrolling behavior and autogeneration of rows in your table.

**Comment by chiragbhakar89** [comment]
HI - can you please elaborate your answer above. I have a similar use case where i have to get an element in the slick grid which is like 20th row and cypress can only see first 13 rows. And hence when i try to find out the 20th row, it errors out. When i try to use your suggested functions from above, for scrollInToView(), it scrolls for a specific condition and hence it just cannot scroll until it see the element. Please correct me if i am wrong about scrollInToView. And about scrollTo(), it simply fails stating following error: Timed out retrying: cy.scrollTo() failed because this element is not scrollable:
<window>
Not sure if i am doing anything wrong here for scrollTo(). Can you please give me an example as to how i should be scrolling inside the grid?

**Comment by jennifer-shehane** [comment]
You're going to have to scroll the table in order for the 20th row to even exist in the DOM. Example from the example site below. For each scroll of the scrollable table element, 10 new rows are added. Then you'll have to get the element you wanted. 

```js
it('tests', () => {
  cy.visit('https://legacy.datatables.net/release-datatables/examples/basic_init/scroll_y_infinite.html')
  cy.get('.dataTables_scroll').scrollIntoView().within(() => {
    cy.get('tbody>tr').should('have.length', 10)
    cy.get('.dataTables_scrollBody').scrollTo('bottom')
    cy.get('tbody>tr').should('have.length', 20)
    cy.get('.dataTables_scrollBody').scrollTo('bottom')
    cy.get('tbody>tr').should('have.length', 30)
    cy.get('.dataTables_scrollBody').scrollTo('bottom')
    cy.get('tbody>tr').should('have.length', 40)
    cy.get('tbody>tr').eq(39).should('contain', 'Presto')
  })
})
```

**Comment by Pradhakrishna284** [comment]
At a time, in the grid, only 12 rows are visible (1 header row, 1 empty row to enter data, and then the remaining 10 rows are data if there are any records), 
my grid has more than 10 data rows, my expected text("Test_TT_16") is at 18th data row, though I used
scrollIntoView() method, I am unable to move to the grid to bottom to find my text. Any help to modify the code.

Approach1:-	
Issue1:- cy.scrollTo() can only be used to scroll 1 element, you tried to scroll 12 elements. 
I get this issue, when I use the below code.
cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"]').scrollIntoView().within(() => {

			cy.get('div[role=\'row\']').each((row, index) => {
				cy.log('Index within the loop: -' + index)
				cy.wrap(row).within(() => { //within the selected row
	
					//1st row is header row, 2nd row is empty row to enter data in the grid, the actual data starts from 3rd row in the grid
					if (index > 1) {
						cy.get('div[role=\'gridcell\']:nth-child(1)').invoke('text').then((name) => {
							cy.log("First column value:- " + name)
							if (name == "Test_TT_16") {
								cy.log("Expected text present:- " + name)
								return false
							}
				
						})
					}

				})				
			})

			cy.get('div[role=\'row\']').scrollTo('bottom')

		})

Approach2:-
Issue2:- When I use the below code, only the first 10 visible data rows are printed, but my data is not printed, but the grid is scrolled to bottom
after printing the first 10 rows data
cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"] div[role=\'row\']', { timeout: 30000 }).each((row, index) => {
			cy.wrap(row).scrollIntoView().within(() => { //within the selected row

				if (index > 1) {
					cy.get('div[role=\'gridcell\']:nth-child(1)').invoke('text').then((name) => {
						cy.log("First column value:- " + name)
						if (name == "Test_TT_16") {
							cy.log("Expected text present:- " + name)
							return false
						}
				
					})
				}

			})	
			cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"]').scrollTo('bottom')		
				
		})

**Comment by Pradhakrishna284** [comment]
At a time, in the grid, only 12 rows are visible (1 header row, 1 empty row to enter data, and then the remaining 10 rows are data if there are any records), 
my grid has more than 10 data rows, my expected text("Test_TT_16") is at 18th data row, though I used
scrollIntoView() method, I am unable to move to the grid to bottom to find my text. Any help to modify the code.

Approach1:-	
Issue1:- cy.scrollTo() can only be used to scroll 1 element, you tried to scroll 12 elements. 
I get this issue, when I use the below code.
cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"]').scrollIntoView().within(() => {

			cy.get('div[role=\'row\']').each((row, index) => {
				cy.log('Index within the loop: -' + index)
				cy.wrap(row).within(() => { //within the selected row
	
					//1st row is header row, 2nd row is empty row to enter data in the grid, the actual data starts from 3rd row in the grid
					if (index > 1) {
						cy.get('div[role=\'gridcell\']:nth-child(1)').invoke('text').then((name) => {
							cy.log("First column value:- " + name)
							if (name == "Test_TT_16") {
								cy.log("Expected text present:- " + name)
								return false
							}
				
						})
					}

				})				
			})

			cy.get('div[role=\'row\']').scrollTo('bottom')

		})

Approach2:-
Issue2:- When I use the below code, only the first 10 visible data rows are printed, but my data is not printed, but the grid is scrolled to bottom
after printing the first 10 rows data
cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"] div[role=\'row\']', { timeout: 30000 }).each((row, index) => {
			cy.wrap(row).scrollIntoView().within(() => { //within the selected row

				if (index > 1) {
					cy.get('div[role=\'gridcell\']:nth-child(1)').invoke('text').then((name) => {
						cy.log("First column value:- " + name)
						if (name == "Test_TT_16") {
							cy.log("Expected text present:- " + name)
							return false
						}
				
					})
				}

			})	
			cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"]').scrollTo('bottom')		
				
		})

**Comment by Pradhakrishna284** [comment]
> You're going to have to scroll the table in order for the 20th row to even exist in the DOM. Example from the example site below. For each scroll of the scrollable table element, 10 new rows are added. Then you'll have to get the element you wanted.
> 
> ```js
> it('tests', () => {
>   cy.visit('https://legacy.datatables.net/release-datatables/examples/basic_init/scroll_y_infinite.html')
>   cy.get('.dataTables_scroll').scrollIntoView().within(() => {
>     cy.get('tbody>tr').should('have.length', 10)
>     cy.get('.dataTables_scrollBody').scrollTo('bottom')
>     cy.get('tbody>tr').should('have.length', 20)
>     cy.get('.dataTables_scrollBody').scrollTo('bottom')
>     cy.get('tbody>tr').should('have.length', 30)
>     cy.get('.dataTables_scrollBody').scrollTo('bottom')
>     cy.get('tbody>tr').should('have.length', 40)
>     cy.get('tbody>tr').eq(39).should('contain', 'Presto')
>   })
> })
> ```

Grid Name:- wj-flex-grid.bento-flex-grid
Grid Row:- div[role=\'row\']
Grid Cell:- div[role=\'gridcell\']

At a time, in the grid, only 12 rows are visible (1 header row, 1 empty row to enter data, and then the remaining 10 rows are data if there are any records), 
my grid has more than 10 data rows, my expected text("Test_TT_16") is at 18th data row, though I used
scrollIntoView() method, I am unable to move to the grid to bottom to find my text. Any help to modify the code.

		
Approach1:-	
Issue1:- cy.scrollTo() can only be used to scroll 1 element, you tried to scroll 12 elements. 
I get this issue, when I use the below code.
cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"]').scrollIntoView().within(() => {

			cy.get('div[role=\'row\']').each((row, index) => {
				cy.log('Index within the loop: -' + index)
				cy.wrap(row).within(() => { //within the selected row
	
					//1st row is header row, 2nd row is empty row to enter data in the grid, the actual data starts from 3rd row in the grid
					if (index > 1) {
						cy.get('div[role=\'gridcell\']:nth-child(1)').invoke('text').then((name) => {
							cy.log("First column value:- " + name)
							if (name == "Test_TT_16") {
								cy.log("Expected text present:- " + name)
								return false
							}
				
						})
					}

				})				
			})

			cy.get('div[role=\'row\']').scrollTo('bottom')

		})

Approach2:-
Issue2:- When I use the below code, only the first 10 visible data rows are printed, but my data is not printed, but the grid is scrolled to bottom
after printing the first 10 rows data
cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"] div[role=\'row\']', { timeout: 30000 }).each((row, index) => {
			cy.wrap(row).scrollIntoView().within(() => { //within the selected row

				if (index > 1) {
					cy.get('div[role=\'gridcell\']:nth-child(1)').invoke('text').then((name) => {
						cy.log("First column value:- " + name)
						if (name == "Test_TT_16") {
							cy.log("Expected text present:- " + name)
							return false
						}
				
					})
				}

			})	
			cy.get('wj-flex-grid.bento-flex-grid div[wj-part="root"]').scrollTo('bottom')		
				
		})

**Comment by scorpyto** [comment]
Working with scroll is kinda pain when it is up to grids. It is almost impossible to scroll to the bottom if you don't know how many elements are in the grid. I think the idea is to be dynamic, not hardcoded value scroll like:
` cy.get('tbody>tr').should('have.length', 10)
    cy.get('.dataTables_scrollBody').scrollTo('bottom')
    cy.get('tbody>tr').should('have.length', 20)
    cy.get('.dataTables_scrollBody').scrollTo('bottom')
.......`
There is an option to use Cypress Real Events -> cy.realMouseWheel but unfortunately it is not getting recognized as a function for some reason. https://github.com/dmtrKovalenko/cypress-real-events#cyrealmousewheel 
However, it really depends on the library which is used for the grid. In some you can "catch" the side slider and control it, in others - you just can't (most of the cases :D ). In other words - there is no simple way to do it at this point. I hope mouseWheel will be available in the future or there will be a new cypress command.
