### ISSUE TITLE
Failed tests are Succesful in Jenkins log

### ISSUE THREAD

**Issue by zbigniewkalinowski** [cypress-io/cypress#6205]
### Current behavior:
We have 6/69 failed tests, but status in Jenkins is SUCCESS
Please see screenshot.

![obraz](https://user-images.githubusercontent.com/34089686/72797140-dfe32400-3c40-11ea-80b8-7d79404dce89.png)

### Desired behavior:

We sholuld get status FAILED

### Versions

Checked on 3.8.1 and 3.8.2

**Comment by jennifer-shehane** [comment]
@zbigniewkalinowski How are you running Cypress tests? Are you running using the Module API? Can you provide the code there? https://on.cypress.io/module-api.html

It appears there are a lot of running processes after the test run and I don't see Cypress issuing it's exit code, so would need more information on your setup to determine why this is happening. 

It also looks like you're using a separate reporter configuration which may be interfering somehow. Please provide your setup and configuration.

**Comment by zbigniewkalinowski** [comment]
I got mochavesome html reports configured as it's described here:
https://docs.cypress.io/guides/tooling/reporters.html#Examples

I also using this configuration in Jenkins:
![obraz](https://user-images.githubusercontent.com/34089686/72878241-e504a980-3cfa-11ea-93d3-97792d0bc23f.png)

And this is my cypress_runner.js code:

`const cypress = require('cypress')
const yargs = require('yargs')
const { merge } = require('mochawesome-merge')
const marge = require('mochawesome-report-generator')
const rm = require('rimraf')
const cypressConfig = require('./cypress')
const ls = require('ls')
const argv = yargs.options({
  'browser': {
    alias: 'b',
    describe: 'choose browser that you wanna run tests on',
    default: 'chrome',
    choices: ['chrome', 'electron']
  },
  'spec': {
    alias: 's',
    describe: 'run test with specific spec file',
    default: 'cypress/endToEndTests/*.js'
  }
}).help()
  .argv

const reportDir = cypressConfig.reporterOptions.reportDir
const reportFiles = `${reportDir}/*.json`
// list all of existing report files
ls(reportFiles, { recurse: true }, file => console.log(`removing ${file.full}`))

// delete all existing report files
rm(reportFiles, (error) => {
  if (error) {
    console.error(`Error while removing existing report files: ${error}`)
    process.exit(1)
  }
  console.log('Removing all existing report files successfully!')
})

cypress.run({
  browser: argv.browser,
  spec: argv.spec
}).then((results) => {
  const reporterOptions = {
    reportDir: results.config.reporterOptions.reportDir,
  }
  generateReport(reporterOptions)
}).catch((error) => {
  console.error('errors: ', error)
  process.exit(1)
})

function generateReport(options) {
  return merge(options).then((report) => {
    marge.create(report, options)
  })
}`

**Comment by jennifer-shehane** [comment]
@zbigniewkalinowski Can you run the following in Jenkins so that we can see extra DEBUG information on whether cypress is issuing the correct exit code. If Cypress is issuing the correct exit code, it is up to the CI provider to correctly handle the exit code. 

```
DEBUG=cypress:cli node cypress_runner -b chrome
```

This should print something like below at the end of the run if Cypress is doing the correct thing - with the code corresponding to the number of failures.

```
  cypress:cli child event fired { event: 'exit', code: 6, signal: null } +7s
  cypress:cli child event fired { event: 'close', code: 0, signal: null } +0ms
```

**Comment by zbigniewkalinowski** [comment]
`  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  01-02HomePagetests.js                    01:10       23       22        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     01:10       23       22        1        -        -  

2020-01-22T13:30:41.788Z cypress:cli child event fired { event: 'exit', code: 1, signal: null }
2020-01-22T13:30:41.788Z cypress:cli Stopping Xvfb
2020-01-22T13:30:41.790Z cypress:cli child event fired { event: 'close', code: 1, signal: null }
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/workspace/HTML Reports Test/cypress/report/mochawesome-report to /var/lib/jenkins/jobs/HTML Reports Test/builds/39/htmlreports/HTML_20Report_20test_205
Email was triggered for: Always
Sending email for trigger: Always
Sending email to: zbigniew.kalinowski@oke.pl
Finished: SUCCESS`

**Comment by jennifer-shehane** [comment]
So, Cypress in this case is issuing the proper exit code. This appears to be an issue with Jenkins not responding to the exit code for some reason - not sure if it's Jenkins or something with your configuration, so this is not an issue with Cypress. 

I'm going to close this issue since this is not something we can control.

**Comment by Jadedy** [comment]
Hello,
I'm doing the same practice with @zbigniewkalinowski and I also get

`[2020-12-24T05:48:32.311Z] 2020-12-24T05:48:32.167Z cypress:cli child event fired { event: 'exit', code: 0, signal: null }
[2020-12-24T05:48:32.311Z] 2020-12-24T05:48:32.168Z cypress:cli Stopping Xvfb
[2020-12-24T05:48:32.311Z] 2020-12-24T05:48:32.170Z cypress:cli child event fired { event: 'close', code: 0, signal: null }`

I thought it was issue with the Jenkins but when I changed it back to use
`sh 'npm run cy:run'`
It worked fine. So I'm guesting it's the part
`cypress.run({
  browser: argv.browser,
  spec: argv.spec
}).then((results) => {
  const reporterOptions = {
    reportDir: results.config.reporterOptions.reportDir,
  }
  generateReport(reporterOptions)
}).catch((error) => {
  console.error('errors: ', error)
  process.exit(1)
})`
which need fixing. Any suggestion ?

**Comment by Jadedy** [comment]
> Hello,
> I'm doing the same practice with @zbigniewkalinowski and I also get
> 
> ```
> [2020-12-24T05:48:32.311Z] 2020-12-24T05:48:32.167Z cypress:cli child event fired { event: 'exit', code: 0, signal: null }
> [2020-12-24T05:48:32.311Z] 2020-12-24T05:48:32.168Z cypress:cli Stopping Xvfb
> [2020-12-24T05:48:32.311Z] 2020-12-24T05:48:32.170Z cypress:cli child event fired { event: 'close', code: 0, signal: null }
> ```
> 
> I thought it was issue with the Jenkins but when I changed it back to use
> `sh 'npm run cy:run'`
> It worked fine. So I'm guesting it's the part
> 
> ```
> cypress.run({
>     browser: argv.browser,
>     spec: argv.spec
> }).then((results) => {
>     const reporterOptions = {
>         reportDir: results.config.reporterOptions.reportDir,
>     }`
>     generateReport(reporterOptions)
> }).catch((error) => {
>     console.error('errors: ', error)
>     process.exit(1)
> })
> ```
> 
> which need fixing. Any suggestion ?

Ok I finally figured it out, according to https://docs.cypress.io/guides/guides/module-api.html#cypress-open when tests failed it doesn't go to .catch(). You should catch error in .then(() instead. My code looks like
```
then((results) => {
    const reporterOptions = {
        reportDir: results.config.reporterOptions.reportDir,
    }
    generateReport(reporterOptions)
    if (results.failures) {
        console.error('Could not execute tests')
        console.error(results.message)
        process.exit(results.failures)
    }
})
```
