### ISSUE TITLE
Handle `alert` and `confirm` better

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#621]
As it stands Cypress's current behavior is to auto accept `alert` and `confirm`.

We should make the following changes:

## Alerts
- Alerts should at least log in the command log as a page event so you can visually see them 
- Alert command log events should capture the alerted value for debugging purposes
- We should expose an event which enables you to listen to alerts and receive their values

## Confirms
- Confirms should log in the command log as a page event so you can visually see them
- Confirms should auto accept by default, and save their values for debugging purposes
- However we should expose an event which enables you to listen for confirms and `return false`
- By returning false we will decline the confirmation as opposed to accept it.

You'll now see and have control over these events.

**Comment by brian-mann** [comment]
This is how they'll appear.

![screen shot 2017-09-06 at 3 26 21 pm](https://user-images.githubusercontent.com/1268976/30130906-d0fa9cc6-9318-11e7-9312-1197634dd682.png)

This is how the confirm event can be controlled:

```coffeescript
it "can turn on and off confirmation", ->
      cy.on "window:confirm", (str) ->
        switch str
          when "foo" then false
          when "bar" then true
          when "baz" then undefined

      cy.window().then (win) ->
        confirmedFoo = win.confirm("foo")
        expect(confirmedFoo).to.be.false

        confirmedBar = win.confirm("bar")
        expect(confirmedBar).to.be.true

        ## undefined is not strictly false
        ## so the confirmation should be true
        confirmedBaz = win.confirm("baz")
        expect(confirmedBaz).to.be.true
```

**Comment by brian-mann** [comment]
The code for this is done, but has yet to be released. We'll update this issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Fixed in [`0.20.0`](https://docs.cypress.io/guides/references/changelog.html#0-20-0)

**Comment by drumbeg** [comment]
I realise that confirms originating from an iframe will appear, but is there a way to handle and dismiss them?

**Comment by novarichuffman** [comment]
If it is a prompt box Cypress will not automatically accept it.

**Comment by FabiGomes** [comment]
Any news about how to working on with a prompt box ? Cypress still not automatically accept it.

**Comment by jennifer-shehane** [comment]
@FabiGomes Yes there are examples here: https://github.com/cypress-io/cypress-example-recipes/issues/339
