### ISSUE TITLE
Cypress reroutes main window to localhost url with port removed when on corporate proxy.

### ISSUE THREAD

**Issue by Jeezy8** [cypress-io/cypress#6211]
### Current behavior:

Setup:
I have a create-react-app running locally on `http://localhost:3000`

When running `cypress open`:
As soon as I write a test that runs `cy.visit('http://localhost:3000')` im loosing the Cypress GUI Panel to the left.
It seems like a redirect. I will have a regular chrome with the website opened but with no cypress GUI.

If I provide a `baseUrl` like http://localhost:3000 inside cypress.json the same happens.

If I execute a test as such:
```
cy.wait(2000);
cy.visit('http://localhost:3000');
```

The GUI vanishes after the set interval

### Desired behavior:

Being able to see the GUI

### Test code to reproduce

I forked a basic example to reproduce the issue:
https://github.com/Jeezy8/cypress-example

Here i have a static html file that i serve via `npx serve -p 80`
Now when i run the same test i still loose the cypress GUI and im being shown:
    404 The requested path could not be found

When i stop the server, im getting a timeout

![1](https://user-images.githubusercontent.com/60149181/72827818-c4e1d580-3c7b-11ea-8d8a-f9993eef2d70.JPG)

![2](https://user-images.githubusercontent.com/60149181/72827830-c9a68980-3c7b-11ea-8f68-8edec4cc5ff4.JPG)

Also worth mentioning im behind a corporate proxy and i installed cypress by providing `CYPRESS_INSTALL_BINARY` env var.

### Versions

cypress 3.8.2
Windows 10
node v12.13.0
npm v6.12.0

**Comment by jennifer-shehane** [comment]
This is likely very much due to your corporate proxy as I am unable to reproduce this behavior on my machine. 

Did you follow the instructions for Proxy configuration from our docs here? https://on.cypress.io/proxy-configuration

Can you share any information regarding your proxy settings?

<img width="1225" alt="Screen Shot 2020-01-22 at 12 40 45 PM" src="https://user-images.githubusercontent.com/1271364/72869735-8e0bce00-3d14-11ea-882a-3d7ed3e299c4.png">

**Comment by Jeezy8** [comment]
I have configred the Proxy as described in the docs.
The proper URL appears on the Cypress settings.

Regarding the proxy itsself, it looks like this:
http://wwwproxy.name.domain.de:8080

I also added
`NO_PROXY=localhost`
and tried
`NO_PROXY="localhost, localhost:3000"`

As far as the proxy is concerned, Im lacking knowledge of what else could cause the issue,
or which information could help you diagnose this further?!

**Comment by Jeezy8** [comment]
i also noticed when i choose Electron, the behaviour seems to be the same at first, but then it restores the cypress panel and works as expected

**Comment by jennifer-shehane** [comment]
Can you visit chrome://policy/ within your Chrome browser? Is there any kind of group policy set in there?

**Comment by jennifer-shehane** [comment]
@Jeezy8 Any update?

**Comment by gopijaganthan** [comment]
@jennifer-shehane I'm Facing the same issue. I don't see any kind of Group policy in the chrome browser

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
