### ISSUE TITLE
Cypress could not install Xvfb and run cypress again 

### ISSUE THREAD

**Issue by hieuTranEnouvo** [cypress-io/cypress#6214]
Hello,

I run google cloud and use cypress v3.8.2 Then I got a bug about installing Xvfb 
==> I can't install xvfb of cypress' lib 
That is my log:
```
Step #2 - "run": If you are using Docker, we provide containers with all required dependencies installed.
Step #2 - "run": 
Step #2 - "run": https://on.cypress.io/required-dependencies
Step #2 - "run": 
Step #2 - "run": Read our documentation on dependencies for more information:
Step #2 - "run": 
Step #2 - "run": Install Xvfb and run Cypress again.
Step #2 - "run": 
Step #2 - "run": [04:45:10] → Your system is missing the dependency: Xvfb
Step #2 - "run": [04:45:10]  Verifying Cypress can run /builder/home/.cache/Cypress/3.8.2/Cypress [failed]
Step #2 - "run": [04:45:10]  Verifying Cypress can run /builder/home/.cache/Cypress/3.8.2/Cypress [started]
```

**Comment by jennifer-shehane** [comment]
@hieuTranEnouvo There are instructions on how to install all necessary dependencies in our docs here: https://on.cypress.io/continuous-integration#Dependencies

**Comment by jennifer-shehane** [comment]
This may likely be a duplicate of https://github.com/cypress-io/cypress/issues/6184, see the workarounds there to see if it resolves your issue.

**Comment by TheDirigible** [comment]
I'm not using CI, just installing Cypress for the first time and got this error running npx cypress open - this should be on the main installation page.

**Comment by jennifer-shehane** [comment]
@TheDirigible Can you open a new issue, filling out the issue template. Thanks!

**Comment by TheDirigible** [comment]
I could not. A big report is a gift.

**Comment by hvaandres** [comment]
@jennifer-shehane I opened a new issue [14457](https://github.com/cypress-io/cypress/issues/14457) Please let me know if it is sufficient or not.
