### ISSUE TITLE
 this element is detached from the DOM

### ISSUE THREAD

**Issue by parvanehsdn** [cypress-io/cypress#6215]
I wrote a code in Cypress and still I get an error.

```js
cy.get('iframe').then(function ($iframe) {

        const $form = $iframe.contents().find('form')

        cy.wrap($form).click({force: true}).find('input[name="credit-card-number"]').type('4111111111111111')
        
        cy.wrap($form).find('input:eq(1)').type('12')
    
        cy.wrap($form).find('input:eq(2)').type('21')

        cy.wrap($form).find('input:eq(3)').type('123')
      })
```

I got error:

```
CypressError: cy.click() failed because this element is detached from the DOM.

<form novalidate="true">...</form>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  cy.wrap()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
```

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

We cannot run the code provided above as the HTML to run the test code against was not provided. There error is as described though - the element you are trying to get is detached from the DOM. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
