### ISSUE TITLE
Docker image ships with npm 6.10.0 which has a bug

### ISSUE THREAD

**Issue by jonathannaim** [cypress-io/cypress#6222]
### Current behavior:

The provided docker images ship with npm 6.10.0 which has a bug and ignores npmrc configuration. It forces us to install the latest npm version from the docker image. 

### Desired behavior:

Docker image ship with the latest npm version

### Test code to reproduce

Related to that issue : https://github.com/nodejs/node/issues/28987

### Versions

Cypress:    3.8.2 Docker image

**Comment by bahmutov** [comment]
What image are you referring to - `cypress/included:3.8.2`? It is built on top of `cypress/base:12.6.0` which does have `npm 6.10.0`, but we will not replace existing an image people are already using in production. I think the next image we are going to build will have Cypress v3.8.3 and will be built on top of a newer `cypress/base` image with latest NPM and Yarn https://github.com/cypress-io/cypress-docker-images/tree/master/base

**Comment by jonathannaim** [comment]
That works for me. 

Sorry I didn't mean to update an existing image I meant to ship the next version with a version of npm that has the bug fix i.e. `>6.11.1`

**Comment by bahmutov** [comment]
Yeah when 3.8.3 comes out I will use a newer base image
