### ISSUE TITLE
Screenshots taken in CI show the Test Runner

### ISSUE THREAD

**Issue by lunaboona** [cypress-io/cypress#6226]
### Current behavior:

Screenshots taken in my CI environmment show the Test Runner, whereas screenshots taken locally don't.

### Desired behavior:

Screenshots shouldn't show the Test Runner.

### Test code to reproduce
cypress.json configuration used locally:
```json
{
    "baseUrl": "http://localhost:4200/showcase",
    "viewportWidth": 1280,
    "viewportHeight": 1024,
    "video": false
}
```

cypress.json configuration used in CI:
```json
{
  "baseUrl": "http://localhost:4200/showcase",
  "viewportWidth": 1280,
  "viewportHeight": 1024,
  "video": false,
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "reports/[hash].xml",
    "jenkinsMode": true,
    "testsuitesTitle": "SDK Cypress Tests",
    "rootSuiteTitle": "SDK"
  }
}
```

plugins/index.js
```js
const { addMatchImageSnapshotPlugin } = require('cypress-image-snapshot/plugin');

module.exports = (on, config) => {
  // Visual Regression Test plugin
  addMatchImageSnapshotPlugin(on, config);

  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--window-size=1280,1024')
      return args
    }
  })
};
```

Commands used to run Cypress:
```
"cy:run:local": "npx cypress run --headless --browser chrome",
"cy:run:jenkins": "npx cypress run --headless --browser chrome --config-file cypress.jenkins.json"
```

Docker image used: [Node 12 | Chrome 79](https://hub.docker.com/layers/cypress/browsers/node12.14.0-chrome79-ff71/images/sha256-6687d4f824ce33b1d262595c18192267b352d64e0045a05ad815d60b7b4c860e)

### Versions

Cypress 3.8.1
OS (locally): Windows 10 1909
OS (CI): Ubuntu 18.04.3 LTS

**Comment by lunaboona** [comment]
For comparison, this is a screenshot taken locally:

**Comment by lunaboona** [comment]
This is a screenshot taken locally:

**Comment by jennifer-shehane** [comment]
Can you include the test code where you are taking the screenshot please?

**Comment by lunaboona** [comment]
@jennifer-shehane Sure. I'm using the cypress-image-snapshot plugin:
```
describe('components/accordion', function() {
    it('visual', function() {
        cy.visit("/components/accordion")
        cy.matchImageSnapshot();
    })
})
```

**Comment by lunaboona** [comment]
I realize now that this issue should've been opened in the cypress-image-snapshot repo. The problem doesn't happen when simply using cy.screenshot(). My bad.

**Comment by FangSen9000** [comment]
> 这是本地截取的截图： ![componentsaccordion -- 视觉捕捉](https://user-images.githubusercontent.com/29905183/72985248-552b3200-3dc4-11ea-97ad-5a76cafa59b0.png)
> 
> 这是 CI 中的相同屏幕截图： ![componentsaccordion -- 视觉（失败）](https://user-images.githubusercontent.com/29905183/72985266-5eb49a00-3dc4-11ea-81fd-a18e476102af.png)

@lunaboona Can I ask how to get screenshots of cypress running on GitHub
