### ISSUE TITLE
Creating a stubbed DELETE route goes to the real server

### ISSUE THREAD

**Issue by nieve** [cypress-io/cypress#6228]
### Current behavior:

I created a test with a stubbed route that responds with a 204 like so:

```js
cy.server();

cy.route({ method: 'DELETE', url: /\/candidates\/46336\?/, status: 204 }).as('deleteCandidate');

cy.window().then(win => {
    var request = new win.XMLHttpRequest()
    
    request.open('DELETE',
        'https://cy-test.free.beeceptor.com/candidates/46336?foo=bar',
        true);
    request.send();

    cy.wait('@deleteCandidate').then(xhr => {
        console.log(xhr);
        const status = xhr.response.statusCode;
        expect(status).to.be.equal(204);
    })
})
```
However, when I run the request seems to actually hit the real server:

![image](https://user-images.githubusercontent.com/202493/72996010-2def5780-3dfa-11ea-9f54-329f773a6e19.png)

### Desired behavior:

request should go through the stubbed route (and return 204).

### Test code to reproduce

[my test repo](https://github.com/nieve/cypress-test-tiny)

### Versions

Cypress 3.8.2
OS windows 10
Browser Chrome 79

**Comment by jennifer-shehane** [comment]
@nieve For a request to be stubbed, you need to provide a `response` option. Anything without a `response` option will go directly through to the given url. From our docs:

>If you do not pass a response to a route, Cypress will pass the request through without stubbing it. We can still wait for the request to resolve later.
>https://on.cypress.io/route#Without-Stubbing

>If you pass a response to `cy.route()`, Cypress will stub the response in the request.
>https://on.cypress.io/route#With-Stubbing

Please make sure to thoroughly read the https://on.cypress.io/route doc.

**Comment by nieve** [comment]
Thanks for the prompt reply and sorry about the confusion. I thought the status specified in the route stood for a response to be stubbed and returned when called.
