### ISSUE TITLE
Ctrl+F to set focus on the search bar

### ISSUE THREAD

**Issue by Regnander** [cypress-io/cypress#6229]
### Current behavior:

Pressing Ctrl+F does nothing at the moment as this keybinding seems not be bound to anything.

### Desired behavior:

I want said keybinding to set focus on the search bar in the GUI (and select all existing text), since I'm using the search bar quite often to find files.

### Test code to reproduce

N/A

### Versions

3.8.2 and older

**Comment by jennifer-shehane** [comment]
Hey @Regnander Can you be more specific about where you're like to use `ctrl+f`? There are several parts to our application and I'm not sure where you're trying to use it. 

Here?

<img width="831" alt="Screen Shot 2020-01-24 at 5 12 33 PM" src="https://user-images.githubusercontent.com/1271364/73063240-c2c28580-3ecc-11ea-8624-87f71d19848e.png">

Here?

<img width="1228" alt="Screen Shot 2020-01-24 at 5 12 44 PM" src="https://user-images.githubusercontent.com/1271364/73063257-ca822a00-3ecc-11ea-8183-f8aa7b150ec0.png">

**Comment by Regnander** [comment]
> <img alt="Screen Shot 2020-01-24 at 5 12 33 PM" width="831" src="https://user-images.githubusercontent.com/1271364/73063240-c2c28580-3ecc-11ea-8624-87f71d19848e.png">

I meant this window. Sorry about that!

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane @Regnander  I would like to give it a go to this issue. Can you give me some feedback on where to find the file related to this issue? Which implementation do you have in mind?

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane @Regnander I would like to give it a go. Can you please guide me on where to find the related file to implement the enhancement? I would like to know which implementation do you have in mind?

**Comment by Regnander** [comment]
> I would like to know which implementation do you have in mind?

I don't quite follow. Do you want me to elaborate my suggestion?

**Comment by Manuel-Suarez-Abascal** [comment]
> > I would like to know which implementation do you have in mind?
> 
> I don't quite follow. Do you want me to elaborate my suggestion?

@Regnander no, it's good. I understand the problem. It's more about implementation, if you guys are thinking a particular approach on how to implement the feature. If not, I would go ahead & start implementing the functionality.

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane is this the file related to the `input` search? 
`cypress\packages\desktop-gui\src\specs\specs-list.jsx`

**Comment by jennifer-shehane** [comment]
@Manuel-Suarez-Abascal Yes, that's the right file with the corresponding tests in Cypress found here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/specs_list_spec.js#L1:L1

There is a Contributing guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

To run the tests:

- within `cypress` root, run `npm i`
- cd to `cypress/packages/desktop-gui` and run `npm run watch`
- In `cypress/packages/desktop-gui` run `npm run cypress:open`
- click on the test you're writing to run it within Cypress

Instructions for running the `desktop-gui` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/README.md

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane @Regnander I have created a PR for this feature [here](https://github.com/cypress-io/cypress/pull/6325)! 🎉

**Comment by panzarino** [comment]
@jennifer-shehane @Manuel-Suarez-Abascal What is the future of this issue? Looks like the PR was getting somewhere but was abruptly closed.

If no one is working on this anymore, I feel like it would be pretty easy to just add the keyboard shortcut in the background and call it a day.

**Comment by phuong2020** [comment]
Thanks . I also often do this Ctrl + F is very convenient when searching
[Friv 9](https://www.friv9.xyz/) | [Friv 1000 ](http://friv1000.pro/) | [Friv 1000](http://friv1000.icu/)

**Comment by jennifer-shehane** [comment]
@panzarino The issue was more complex than originally thought, which is what the PR thread reflects. 

- Need to have different keyboard bindings per Windows / Mac
- Need to surface in the UI that ctrl + f did something, (highlighting the internal search bar)
- Need to surface that this keyboard shortcut exists to people that don't know about it (showing shortcut in search bar based on their current OS)

The PR was almost there but I think we got stuck at the end detecting their OS in the proper place and the Cypress team didn't have the time to implement ourselves. Feel free to pull the commits from the PR into a new PR to finish and attribute @Manuel-Suarez-Abascal for their work.

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane @panzarino @Regnander I decided to finish this PR since I'm currently no too busy or overwhelm at work. This is the [new PR](https://github.com/cypress-io/cypress/pull/15388). Let me know if I need to do any changes! 😃
