### ISSUE TITLE
Cypress application is Crashing and shutting down.

### ISSUE THREAD

**Issue by hamzazaidi** [cypress-io/cypress#623]
- Operating System: MAC OS
- Cypress Version: 0.19.4
- Browser Version: Google Chrome, Version 61.0.3163.79

### Is this a Feature or Bug?
Bug

### Current behavior:
Cypress application is Crashing and shutting down.

### Desired behavior:
It should not crash

### How to reproduce:
Just running the following test.

Following is the `cypress.json` file
```json
{
	"baseUrl" : "https://qaserver.flqa.net",
	"defaultCommandTimeout": 60000,
	"screenshotOnHeadlessFailure" : false,
	"videoRecording": false,
	"chromeWebSecurity": false
}
```

#### Test code:

```js
describe('Test Module - Testing ', () => {
	it('Visit the Url', () => {
		cy.visit('/ec-forms');
		cy.wait(10000);
	})

	it('Logging In', () => {
		let userNameField = '#Username';
		let passwordField = '#Password';
		let loginButton = '#qa-button-login';
		cy.get(userNameField, { timeout: 10000 })
			.should('be.visible')
			.type('ectester3');
		cy.get(passwordField, { timeout: 10000 })
			.should('be.visible')
			.type('a12ds34567{enter}');
	})	
})

```

### Additional Info (images, stack traces, etc)
Cypress is crashing so i am not been able to capture stack trace.

**Comment by hamzazaidi** [comment]
Our application has iframe, i am suspecting that Cypress also create an iframe which might be conflicting with other iframe and Cypress is crashing.

**Comment by brian-mann** [comment]
Cypress works just fine on iframes. 

When you say crashing what exactly do you mean? Like the browser quits and Cypress *literally* crashes?

Or you just see an error in the browser? 

Can you take a screenshot / record a video?

**Comment by hamzazaidi** [comment]
Cypress crashes and getting close. I am unable to get any stack trace. I tried to run in the CLI and record the run, 
https://dashboard.cypress.io/#/projects/2ovtbx/runs/16aa1f17-1c26-4611-9d8b-812e7cca3e1a/output

**Comment by hamzazaidi** [comment]
https://drive.google.com/open?id=0B0MHl8XpRmQzZUFyRVJnUjdpOGc

**Comment by hamzazaidi** [comment]
In our login process with do lots of redirections, server send's down status code 302 and does redirection, is it possible that redirection is causing the problem how Cypress works? 
Outside the Cypress login works fine and we have Protractor test's which works fine also.

**Comment by hamzazaidi** [comment]
@brian-mann If i change the test mentioned above to the following, it works. Is there any explanation about this behavior?

`describe('Test Module - Testing ', () => {
	
	it('Logging In', () => {
		let userNameField = '#Username';
		let passwordField = '#Password';
		let loginButton = '#qa-button-login';
                cy.visit('/ec-forms');
		cy.get(userNameField, { timeout: 10000 })
			.should('be.visible')
			.type('ectester3');
		cy.get(passwordField, { timeout: 10000 })
			.should('be.visible')
			.type('a12ds34567{enter}');
	})	
})
`

**Comment by jennifer-shehane** [comment]
I've been unable to recreate this issue. Please reopen this issue and give a reproducible example if this is still occurring.

**Comment by saranyas72** [comment]
I still see the system getting shutdown frequently when some error occurs in cypress. One such reproducible instance is when the element could not be found resulting in timeout error - 

![image](https://user-images.githubusercontent.com/9431304/76218932-5352ec00-6215-11ea-839a-a12fbb27cf55.png)

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
