### ISSUE TITLE
Missing CI information from GitLab

### ISSUE THREAD

**Issue by TomaszG** [cypress-io/cypress#6231]
It seems that the project URL and default branch are not utilized correctly by the runner. Due to this, some 3rd party tools may not work properly when they expect `remoteOrigin` and `defaultBranch`  in `commitParams` for runs recorded by Cypress running as GitLab job.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

Please include a screenshot of the area you're mentioning with the 'Default branch' and the 'project URL' that is specifically missing.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏

**Comment by TomaszG** [comment]
@jennifer-shehane I have updated the first message in the discussion, also please see my comment in related PR.
