### ISSUE TITLE
Node version 'learn more' link in Desktop-GUI is broken

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6237]
### Current behavior:

The 'Learn more' link inside 'Node version' routes to `http://on.cypress.io/configuration#Node-Version` which goes to no where since the heading in the docs was renamed to `Node version` (lowercase). 

<img width="800" alt="Screen Shot 2020-01-24 at 4 15 41 PM" src="https://user-images.githubusercontent.com/1271364/73059801-dec22900-3ec4-11ea-84ba-ad380101c34a.png">

### Desired behavior:

Hashtags should **never** be hardcoded into on links - this on link cannot be fixed outside of updating the actual link in the Desktop or changing the link in the docs and *never* changing that heading every again.

This will unfortunately be broken in older versions forever. 

All `on.cypress.io` links should be specifically formed and added on `on` package - never hash tags. cc @flotwig 

Granted I think that more issues like this wouldn't happen if it were easier to actually deploy the on links because right now it is a nightmare - https://github.com/cypress-io/cypress-services/issues/1979

### Versions

3.8.2

**Comment by flotwig** [comment]
> All `on.cypress.io` links should be specifically formed and added on `on` package - never hash tags. cc @flotwig

Generally, I think we should avoid breaking hash links in the docs since there's no telling where they're linked to from. We can add anchor tags whenever the hash has to change:

```html
<a name="Node-version"></a>
```

**Comment by flotwig** [comment]
Released in [`4.0.0`](https://on.cypress.io/changelog#4-0-0).
