### ISSUE TITLE
Misleading cy.task error message when returning Promise<undefined>

### ISSUE THREAD

**Issue by GrzegorzKazana** [cypress-io/cypress#6241]
### Current behavior:

When running a task returning promise that fulfils with undefined, we get an error with following message: `The task 'exampleAsyncTask' returned undefined. You must return a promise, a value, or null to indicate that the task was handled.`

### Desired behavior:

 
Cypress should either handle promises fulfilling to undefined, or give clear error message that it's not allowed (i.e.` The task 'exampleAsyncTask' returned promise fulfilling with undefined.`).

### Test code to reproduce

1. Clone https://github.com/cypress-io/cypress-test-tiny
2. Create simple task that returns promise resolving with undefined
```javascript
// plugins/index.js
module.exports = (on, config) => {
  on("task", {
    exmapleAsyncTask() {
      return new Promise(resolve => setTimeout(resolve, 100));
    }
  });
};
``` 
3. Execute the task in test
```javascript
describe("page", () => {
  it("works", () => {
    cy.visit("https://example.cypress.io");
    cy.task("exmapleAsyncTask");
  });
});
```

Test fails with:
```
CypressError: cy.task('exmapleAsyncTask') failed with the following error:

The task 'exmapleAsyncTask' returned undefined. You must return a promise, a value, or null to indicate that the task was handled.
```

Changing task promise to return any value fixes the issue:
```javascript
exmapleAsyncTask() {
      return new Promise(resolve => setTimeout(() => resolve(42), 100));
}
```
### Versions

`Cypress 3.8.2`
`macOS 10.14.6`

**Comment by jennifer-shehane** [comment]
We can update the error message to be more descriptive that the Promise cannot resolve to undefined. 

```
The task 'foo' returned undefined. You must return a value, null, or a Promise that resolves to a value or null to indicate that the task was handled.
```

**Comment by vicrac** [comment]
To be honest, I wonder why is there such a constraint? Is `undefined` (or `Promise<undefined>`) returned from task used to indicate that it failed?

@jennifer-shehane

**Comment by brettz9** [comment]
Yes, I am curious about this constraint too.

**Comment by brettz9** [comment]
My apologies, I see the docs explain it thus:

> In the task plugin event, the command will fail if undefined is returned. This helps catch typos or cases where the task event is not handled.

**Source**: https://docs.cypress.io/api/commands/task.html#Command
