### ISSUE TITLE
cy.server() not playing nicely with cy.request()

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#6244]
I'm curious as to why `cy.server()` isn't adding headers to subsequent `cy.request()` calls, but DOES add them to subsequent `cy.route()` calls. This seems out of step with the docs which say: 

![image](https://user-images.githubusercontent.com/2730609/73098803-fc7c9780-3e9e-11ea-9f43-dc331ac4d9b9.png)

Here is my pseudocode: 

```js
cy.request("PUT", "design/cli-api/public/auth", {
    username: "susanB@fastCompany.com",
    password: "imA_fake_pass",
    expiresIn: "1w"
  }).then(res => {
    token = res.body.token;
    cy.server({
      headers: {
        "x-fc-token": res.body.token
      }
    })
   
    cy.route({
      url: "design/cli-api/public/auth",
    }).then(res => {
      assert(res.status === 200); //THIS WORKS -- the token is added to the request header
    });
   cy.request({
      url: "design/cli-api/public/auth",
    }).then(res => {
      assert(res.status === 200);  //THIS FAILS -- the token is NOT added to the request header
    });
  });
```

Is this by design? I would have expected the token to have been added to the header in both cases.

If anyone can provide some insight here that would be great. 

Thanks!

**Comment by tnrich** [comment]
And just to add, I've also tried 
```js
cy.server({
  onAnyRequest: (route,  proxy) => {
      proxy.xhr.setRequestHeader( "x-fc-token", res.body.token)
    }
})
```
to no avail.

**Comment by jennifer-shehane** [comment]
Per the docs, the `headers` only affect subsequent `cy.route()`, not `cy.request()`. Not all options affect both, there are 2 headings: `The following options are merged in as default options to cy.route()` and `The following options control the behavior of the server affecting all requests`, you can only change the options under the second heading for `cy.request()`. 

https://on.cypress.io/server#Arguments

**Comment by tnrich** [comment]
@jennifer-shehane ok, point taken that `cy.request` isn't affected by calling `cy.server({headers:"asdf"})`. However, like you said, I would expect it to be affected by calling:

```js
cy.server({
  onAnyRequest: (route,  proxy) => {
      proxy.xhr.setRequestHeader( "my-token", "sometokenhere")
    }
})
```

I've set up a test case showing how this functionality is not occurring -- https://github.com/tnrich/cypress-test-tiny

Here's the test case I set up: 

```js
/// <reference types="cypress" />

beforeEach(() => {
  cy.server({
    onAnyRequest: (route, proxy) => {
      console.log("hit") //it doesn't look like this even gets hit..
      proxy.xhr.setRequestHeader("my-token", "lalalalal");
    }
  });
})
describe("page", () => {
  it("cy.server({onAnyRequest}) does not set headers on ", () => {
    cy.wait(1).then(() => {
      console.log("hit2")
      cy.request("https://example.cypress.io").then(() => {
        console.log("hit3")
      })
    })
  });
});
```

and here's a screenshot of the request being logged:

![image](https://user-images.githubusercontent.com/2730609/73473302-608cd900-4341-11ea-9cd6-3cdf44a3c7bd.png)

As you can see there are no headers set on the request. Also, it doesn't ever log "hit" to the console. 

Is this the expected behavior? Am I missing something here? 

Thanks!

**Comment by jennifer-shehane** [comment]
Ok, this is definitely my fault and a fault on our documentation. And I am making a PR to fix this very fundamental miswriting of the `cy.server()` doc here: https://github.com/cypress-io/cypress-documentation/pull/2450. 

And I also definitely misspoke earlier as I was relying on that documentation. 

`cy.server()` cannot be used to interact with `cy.request()` in any way. When the docs say 'control the behavior of requests', it purely means XHR requests (or newer XMLHttpRequest). Sorry for all the confusion. 

To change the request `headers` during [`cy.request()`](https://on.cypress.io/request) you will need to pass them individually for each request like below:

```js
cy.request({
  url: 'https://example.cypress.io',
  headers: {
    'foo': 'bar'
  }
})
```

If you have to do this for a large amount of requests, you could [overwrite](https://on.cypress.io/custom-commands#Overwrite-Existing-Commands) the request command to always send these headers like below:

```js
Cypress.Commands.overwrite('request', (originalFn, options) => {
  options.headers = {
    'foo': 'bar'
  }

  return originalFn(options)
})

// later in your tests
cy.request({
  url: 'https://example.cypress.io',
})
```

**Comment by tnrich** [comment]
@jennifer-shehane thanks for the clarification! Maybe you could also add a note specifically saying that cy.request is NOT affected by cy.server()? I think that would be very helpful. 

Thanks!

**Comment by jennifer-shehane** [comment]
I opened an issue in the docs for this here: https://github.com/cypress-io/cypress-documentation/issues/2452
