### ISSUE TITLE
Cypress not able to load a different domain used in the second test

### ISSUE THREAD

**Issue by pranaydua1987** [cypress-io/cypress#6245]
I have 2 tests. In one test the user goes to www.nordstromrack.com and login and in the second test case it goes to www.hautelook.com and tries to the same. Ideally the test should be able to navigate between 2 domains within the same test case but since that's not possible in cypress so I had to add the second test case.

### Current behavior:

In the first test case its able to successfully login but when it goes to the second test case then it tries to load the page and after a few seconds it shows the page not found . 

If in test case 1 , I dont log in and if is imply go to nordstromrack.com and just click on login button and then move to second test case then it actually loads the hautelook.com page in the second test case .But when i include login step then it fails to load the second url in the second test.

<img width="1397" alt="cypressPageNotLoading" src="https://user-images.githubusercontent.com/12158094/73148469-5634bb80-4071-11ea-981d-d1c155869edb.png">

### Desired behavior:
Cypress should able to successfully open the second domain and proceed with the test.

### Test code to reproduce

```js
describe('My Second Test Suite', function () {
  it('My FirstTest case', function () {
    cy.visit("https://www.nordstromrack.com/")
    cy.contains('Log In').click({ force: true })
    cy.get('button:contains("Log In")').click()
    cy.get('input[name="email"]:visible').clear().type("cypresstest@test.com")
    cy.get('input[name="password"]').clear().type("Cypress@123")
    cy.get('button:contains("Log In")').click()
    cy.get('.modal-template__close-icon').click()
    cy.get('.secondary-nav__name').should('have.text', 'tester')
    cy.wait(3000)
  })

  it('My SecondTest case', function () {
    cy.visit("https://www.hautelook.com/") //cypress not loading this page in second test case
    cy.contains('Log In').click({ force: true })
    cy.get('button:contains("Log In")').click()
    cy.get('input[name="email"]:visible').clear().type("cypresstest@test.com")
    cy.get('input[name="password"]').clear().type("Cypress@123")
    cy.get('button:contains("Log In")').click()
    cy.get('.secondary-nav__name').should('have.text', 'tester')
  })
})
```

### Versions

Cypress package version: 3.8.2
Cypress binary version: 3.8.2
Macbook 
Google Chrome :79

**Comment by id-dan** [comment]
@pranaydua1987 Pls read this documention: 
https://docs.cypress.io/guides/guides/web-security.html#Same-superdomain-per-test

**Comment by pranaydua1987** [comment]
I have gone through this documentation that's why my 2 different domains are part of 2 separate tests. According to docs you cant have 2 different superdomains as a part of a single test.

**Comment by sznowicki** [comment]
There is another issue about the same thing: https://github.com/cypress-io/cypress/issues/944

Long story short, cypress loads tested page within an iframe with introduces some limitations (more in the thread).

**Comment by pranaydua1987** [comment]
@sznowicki I have gone through this issue but in my case, I am using 2 different tests and it should work . Actually If I remove the login step and simply clicks come button in test 1 and then move to test 2 then it actually does open the page .

**Comment by pranaydua1987** [comment]
@brian-mann and @jennifer-shehane  : can you guys please help ? I have to give a demo to my manager soon but i cant move ahead with it unless i resolve this issue . thanks for understanding.

**Comment by downeyfe** [comment]
Have you tried splitting the two tests into totally separate files?
For example, `nordstrom.js` containing the Nordstrom test, and `hautelook.js` containing the Hautelook test. I tried this structure locally and the separation seemed to be enough to resolve the superdomain restrictions mentioned above.

**Comment by pranaydua1987** [comment]
@downeyfe how can i make cypress run 2 different .js files run 1 after another?

**Comment by downeyfe** [comment]
@pranaydua1987 I take it you already have Cypress up and running based on your first comment. You should be able to make another file in the same directory as the original problematic test and split the two tests across the both of them.
The Cypress documentation has a [section on organising tests](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Folder-Structure) which should help.

**Comment by jennifer-shehane** [comment]
You should be able to visit 2 domains of different origin in 2 separate tests as you have described. 

I am not actually able to reproduce this in Cypress 3.8.3. The given test case does load both of the pages with no special settings. 

My test code:

```js
describe('My Second Test Suite', function () {
  it('My FirstTest case', function () {
    cy.visit("https://www.nordstromrack.com/")
    cy.contains('Log In').click({ force: true })
    cy.get('button:contains("Log In")').click()
    cy.get('input[name="email"]:visible').clear().type("cypresstest@test.com")
    cy.get('input[name="password"]').clear().type("Cypress@123")
    cy.get('button:contains("Log In")').click()
    cy.get('.modal-template__close-icon').click()
    cy.get('.secondary-nav__name').should('have.text', 'tester')
    cy.wait(3000)
  })

  it('My SecondTest case', function () {
    cy.visit("https://www.hautelook.com/") //cypress not loading this page in second test case
    cy.contains('Log In').click({ force: true })
    cy.get('button:contains("Log In")').click()
    cy.get('input[name="email"]:visible').clear().type("cypresstest@test.com")
    cy.get('input[name="password"]').clear().type("Cypress@123")
    cy.get('button:contains("Log In")').click()
    cy.get('.secondary-nav__name').should('have.text', 'tester')
  })
})
```

<img width="1414" alt="Screen Shot 2020-02-04 at 1 51 14 PM" src="https://user-images.githubusercontent.com/1271364/73722670-6cb7d280-4755-11ea-9f01-d8603a9b0163.png">

Now this Error that is showing is another story, but the issue described as is I'm not able to reproduce. 

```
Error: the string "The prodid value must be within 1 to 50 characters." was thrown, throw an Error :)
```

Make sure if you have any proxy on your network that it's properly configured https://on.cypress.io/proxy-configuration

**Comment by pranaydua1987** [comment]
@jennifer-shehane : This is certainly an issue . Please add : 
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  }) before each test to handle uncaught exception. You will be able to reproduce it

**Comment by pranaydua1987** [comment]
I have the code which you provided in under support/index.js forgot to include it here . Please look into the issue again.Thanks

**Comment by jennifer-shehane** [comment]
Sorry, I am still not able to reproduce. Double check any other code in your tests that may be affecting this. I ran in Chrome 79 and Electron 78. Both sites load. 

Gif of my tests running

![](http://g.recordit.co/umC5S3jEFT.gif)

**Comment by pranaydua1987** [comment]
@jennifer-shehane the issue starts happening when a user is able to successfully login with the first test . But seeing you gif , it seems like the website is treating u as bot and thats why the login is failing . Do you mind trying in few minutes ? I really want to move ahead with this tool but without this icant do a demo with my manager .

**Comment by pranaydua1987** [comment]
If you see the api responses on the left then you will see that login is failing with 403. You can also try with stg.nordstromrack.com and stg.hautelook.com

**Comment by jennifer-shehane** [comment]
I am able to reproduce this issue now with the following test code. 

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  return false
})

describe('My Second Test Suite', function () {
  it('My FirstTest case', function () {
    cy.visit("https://www.nordstromrack.com/")
    cy.contains('Log In').click({ force: true })
    cy.get('button:contains("Log In")').click()
    cy.get('input[name="email"]:visible').clear().type("cypresstest@test.com")
    cy.get('input[name="password"]').clear().type("Cypress@123")
    cy.get('button:contains("Log In")').click()
    cy.get('.modal-template__close-icon').click()
    cy.get('.secondary-nav__name').should('have.text', 'tester')
    cy.wait(3000)
  })

  it('My SecondTest case', function () {
    cy.visit("https://www.hautelook.com/") //cypress not loading this page in second test case
  })
})
```

The second visit navigates the top window to the hautelook.com website.

<img width="1009" alt="Screen Shot 2020-02-04 at 9 27 18 PM" src="https://user-images.githubusercontent.com/1271364/73755905-24b8a000-4795-11ea-9fb5-d9d34da1ace0.png">

**Comment by pranaydua1987** [comment]
@jennifer-shehane  when can we expect a fix for this bug ? Is it an easy fix ?

**Comment by kai22** [comment]
I'm having this same issue, I need to use cy.visit() to catch the cy.route() API call - but cy.visit() just seems...broken? Like it breaks the test out of the iframe.

**Comment by kai22** [comment]
Odd thing is, if I replace cy.visit() with cy.request() I get the page I expect (I get the HTML back as a response) but cy.visit() prompts a "page not found"

**Comment by abhidp** [comment]
> @jennifer-shehane when can we expect a fix for this bug ? Is it an easy fix ?
I am afraid you won't be hearing any good news anytime soon. Cypress fixes bug as per the priority and this bug is not the priority as this has been pending over 2years. 

Better move to [Puppeteer](https://jestjs.io/docs/en/puppeteer) or [TestCafe](https://devexpress.github.io/testcafe/) for your demo

**Comment by poponuts** [comment]
Same issue here and had to demo as well. I was scrambling and had no choice but look for a workaround.
The simple one is having two separate .js files as per @downeyfe 
Although its considered anti-pattern from cypress, to make it sequential, you can add `01.My FirstTest case` then `02.My SecondTest case`

**Comment by CJ-Markus** [comment]
Any updates on this? It's still an issue in 10.3.0 and it's been 2.5 years now..

**Comment by jhinzzz** [comment]
> Any updates on this? It's still an issue in 10.3.0 and it's been 2.5 years now..

Nothing update here. It still in 11.0.1 and its about 2.8 years now..
