### ISSUE TITLE
Error: Cannot find module 'worker_threads' from 'write-file-atomic'

### ISSUE THREAD

**Issue by sanehab** [cypress-io/cypress#6250]
### Current behavior:
Cypress opens successfully but whenever i try to run the tests i receive the following Error:
Error: Cannot find module 'worker_threads' from 'write-file-atomic'

This is related to worker_threads in nodejs, I'm on Cypress 3.8.1 - i also tried 3.8.4 - which comes bundled with node 12, which should have these worker threads supported by default and not behind an experimental flag.

Anyway i tried running cypress with nodejs on my system, and i also tried setting the experimental flag for nodejs using the NODE_OPTIONS environment variable, and i still get the same error.

I tried npm prune, i cleared cache of cypress and installed more than once, and i even reinstalled my entire node modules, and tried this on a different machine all with the same error.

### Versions

Cypress 3.8.1
System Version: macOS 10.15.2 (19C57)
Kernel Version: Darwin 19.2.0
Chrome 79

**Comment by sanehab** [comment]
This is unrelated to cypress ... happening because of conflicts between some dependencies of my project.

**Comment by dantswain** [comment]
@sanehab would you mind sharing what dependencies were causing trouble for you?  I'm running into a similar error.

**Comment by sanehab** [comment]
@dantswain  i'm sorry this is late but i don't remember exactly, but i think it was related to package that has a binary that was built with node-gyp.

**Comment by Mugane** [comment]
That's not it. Mine is a blank project with no dependencies and I'm getting the error for the sample_spec.js test script in the documentation.
