### ISSUE TITLE
Tests fail on 4.0 branch with 'Error: Resolution method is overspecified' message

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#6260]
### Current behavior:

When you use `cy.on` on 4.0 branch, tests fail with 'Error: Resolution method is overspecified'

### Desired behavior:

Tests should pass.

### Test code to reproduce

1. Check out `v4.0-release` branch
2. Run tests. 
3. Tests fail when `cy.on` is used. 

If you want to see the failures, [check here](https://circleci.com/gh/cypress-io/cypress/234902?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

### Versions

`v4.0-release` branch

**Comment by chrisbreiding** [comment]
This was the result of a bad merge. Fixed now in `v4.0-release`.
