### ISSUE TITLE
Bypassing   Content Security Policy directive: "frame-ancestors 'none'"

### ISSUE THREAD

**Issue by PiotrAdamus** [cypress-io/cypress#6263]
I want to test my checkout process where we are using mollie gateway process. After redirects to their site i got that kind of error `Refused to display [private link here] in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'"`

In cypress.json i added `chormeWebSecurity: false` and on plugins file i added something like this 

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {

    if (browser.name === 'chrome') {
      args.push('--disable-site-isolation-trials')

      return args
    }
  })
}
```

Is there any option to go through that gateway ? Cannot mock this because we want to have full e2e test. Disabling web security doesn't work on that case. I thought about running cypress tests not in iframe but directly in browser but also haven't found any information.

**Comment by anveshpuli** [comment]
I'm facing the same issue as well . Looking forward  for it

**Comment by jennifer-shehane** [comment]
Cypress runs the application under test within an iframe. If a particular website that is run within Cypress has `"frame-ancestors 'none'`, then it has restricted itself from running within an iframe and cannot run within Cypress. Turning off `chromeWebSecurity` has no effect over this.

If you have control over the application that is throwing this Content Security Policy, we suggest you remove it when [running within Cypress](https://on.cypress.io/using-cypress-faq#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress). 

If this application is not under your control, this is [one of the many reasons](https://on.cypress.io/best-practices#Visiting-external-sites) that we suggest you do not test a 3rd party application's behavior that is not under your control.

Duplicate of https://github.com/cypress-io/cypress/issues/1555

**Comment by Mrpolat** [comment]
```js
import React, { useEffect } from 'react'
import Iframe from 'react-iframe'

const CodePanel = () => {
  return (
    <div className='codePanel'>
      <Iframe url="https://github.dev/hakanbaysal/php_nginx_msodbc_oci8_pgsql"
        width="100%"
        height="500px"
        id=""
        className=""
        display="block"
        position="relative"
      />
    </div>
  )
}

export default CodePanel
```
Refused to frame 'https://github.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

Due to security policies. I cannot display the github.dev ide on my website with iframe. What is the alternative way to do this? Do I need to use something like restApi?
