### ISSUE TITLE
GitHub actions v2 are not supported - Cypress crashes.

### ISSUE THREAD

**Issue by mastrolinux** [cypress-io/cypress#6264]
### Current behavior:

GitHub actions v2 makes cypress crash.

```
Cypress test command: npx cypress run --record --config-file cypress.json --env configFile=ci
/opt/hostedtoolcache/node/12.14.1/x64/bin/npx cypress run --record --config-file cypress.json --env configFile=ci
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.8.2
Error: The process '/opt/hostedtoolcache/node/12.14.1/x64/bin/npx' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:894:25)
```
Full report here: https://github.com/encrypted-dev/userbase/pull/92/checks?check_run_id=413005466

### Desired behavior:

Not to crash

### Test code to reproduce

Here the source code, https://github.com/encrypted-dev/userbase/tree/actions-v2/cypress does not depend on the tests, if I rever back to actions v1 it works, the change was:
https://github.com/encrypted-dev/userbase/pull/92/files#diff-4f7ad2fc645ee03d0e087a0252b7d815R35

### Versions
Cypress 3.8.2 headless running in GitHub actions with Ubuntu 18.04

**Comment by bahmutov** [comment]
https://github.com/cypress-io/github-action#important

**Comment by mastrolinux** [comment]
It worked, thanks a lot!

**Comment by stuart-williams** [comment]
This is still a problem:

<img width="844" alt="Screenshot 2020-02-14 at 16 20 31" src="https://user-images.githubusercontent.com/2526507/74548595-0ba6b080-4f46-11ea-8e5e-091e3ff6bddd.png">

**Comment by jennifer-shehane** [comment]
Yes, this is still an issue, please see this note: https://github.com/cypress-io/github-action#important

For issues related to cypress GitHub Action, please open them at https://github.com/cypress-io/github-action
