### ISSUE TITLE
Cypress not able to set the  cookie after cy.request

### ISSUE THREAD

**Issue by MehranShafqat** [cypress-io/cypress#6271]
### Current behavior:

Im trying to achieve something like like this I have login api and send `cy.request` and get the access token and set in cookie. But in response not able to set the cookies and  `cy.setCookie` never worked. If Im using `cy.setCookie` outside the response and it is working. Not sure its is a bug or how we can set the cookie after getting the response.

### Test code to reproduce

```js
cy.request({
  method: 'POST',
  url: 'https://stage.api.test.com/api/login',
  headers: { "Content-Type": "application/json;charset=UTF-8", "Origion": "https://stage.web.test.com" },
  body: { grant_type: "password", client_id: "2", username: "test@gmail.com", password: "123123", scope: "*" }
})
  .its('body')
  .then((body) => {
    var mycookie = JSON.stringify(body.body.userToken);
    console.log(myJSON)
    cy.setCookie('userToken', mycookie);
  })
```

### Versions
c.v 3.8.2

**Comment by jennifer-shehane** [comment]
You've misspelled `Origin` as `Origion`. Could that be related?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
