### ISSUE TITLE
The tests list hierarchy is confusing in the Desktop-GUI

### ISSUE THREAD

**Issue by Svish** [cypress-io/cypress#6275]
I find the tree view in the test-runner to be rather confusing because it looks like folders are on a separate level than files.

### Current behavior:

As seen in the screenshot below, it looks like `feature` is on the same level as `1`, `2`, etc., but it's actually their parent. And it looks like `3` is on a level below `2`, but it's actually its sibling. It becomes even more messy with several levels and folders opened (which they all are by default).

![image](https://user-images.githubusercontent.com/142162/73465411-a4530300-4380-11ea-8af7-711f3a26398a.png)

### Desired behavior:

Please remove the unnecessary arrow (open/closed state is already shown with the open/closed folder icon), and have the folder icon line up with the file icons, like this:

![image](https://user-images.githubusercontent.com/142162/73465855-496ddb80-4381-11ea-84ac-49fad5a7af8d.png)

### Versions

**Cypress:** 3.8.3

**Comment by jennifer-shehane** [comment]
The change in indentation is welcome. However there needs to be some indication that the folders when clicked will expand to show more content and I think that removing the arrow altogether makes this less obvious. We're open to other design ideas as long as they still convey this concept. 

This is very low priority for us, but we would accept an outside PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane @Svish I have opened a PR [here](https://github.com/cypress-io/cypress/pull/18994) which it's removing the arrows. I have also included other redesign ideas. Let me know what you guys think.

**Comment by flotwig** [comment]
Cypress 10 has been released, featuring a brand new specs list design where this issue has been resolved:


![image](https://user-images.githubusercontent.com/1151760/171512638-db328be3-5b00-4861-bdf1-b8fa8a0dc9bc.png)

Closing since this is fixed by upgrading to Cypress 10.
