### ISSUE TITLE
Blocked frame origin error when having css rule: background-image: url();

### ISSUE THREAD

**Issue by pawelgalazka** [cypress-io/cypress#628]
### Current behavior: 

When page has style rule `background-image: url();` Cypress fails with:

```
SecurityError: Blocked a frame with origin "http://your.page.dev" from accessing a cross-origin frame.
```

### Desired behavior:

For sure better messaging what's the problem, it was very hard to find the source of this issue in a working full app.

Then again there is a question, why this error happens in Cypress ? Cypress should not fail as there is no such error on tested page when browsed separately.

#### Test code/page:

```html
    <html>
      <body>
      <div>
        <style> .headerstrip { background-image: url(); } </style>
        <div class='headerstrip'>abc</div>
      </div>
      </body>
    </html>
```

```js
describe('cypress error', () => {
  beforeEach(() => {
    cy.visit([page address])
  })

  it('should not fail', () => {
  })
})
```

- Operating System: macOs 10.12.5
- Cypress Version: 0.19.4
- Browser Version: Chrome 61

**Comment by jennifer-shehane** [comment]
Please look into our workarounds with cross origin errors here: [https://on.cypress.io/web-security#Common-Workarounds](https://on.cypress.io/web-security#Common-Workarounds)

Also, look into upgrading to [version 0.20.0](https://on.cypress.io/changelog) as there were a lot of technical improvements.

**Comment by brian-mann** [comment]
When is this actually erroring? And can you provide an example of the `background-url`?

When Cypress runs it runs on the same domain as your app expects, so it avoids most cross origin errors.

However we do special stuff when we restore snapshots and should handle this situation.

Is this problem occuring during snapshot handling or somewhere else? Can you provide a screenshot

**Comment by pawelgalazka** [comment]
@brian-mann the point is that is happening when `url()` is empty in `background-url` as in the example.

**Comment by pawelgalazka** [comment]
<img width="1263" alt="screen shot 2017-09-15 at 8 25 37 am" src="https://user-images.githubusercontent.com/829242/30458572-825531a2-99ef-11e7-8eb6-96c4d5129226.png">

The error disappears when I remove `background-image: url();` rule. This was run on `0.20.0`

**Comment by smkarnan** [comment]
I'm facing the same issue in Out-System application. Any solution or any workaround  for this issue ?

**Comment by christian-fei** [comment]
same issue here

**Comment by christian-fei** [comment]
I got around this by setting in `cypress.json`:

```
{
  ...
  "chromeWebSecurity": false
}
```

and [reading best-practices](https://docs.cypress.io/guides/references/best-practices.html) really helped :)

**Comment by jennifer-shehane** [comment]
I'm unable to recreate this in version 3.4.0. Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
