### ISSUE TITLE
Cypress could not exit from Promise

### ISSUE THREAD

**Issue by aartisoni1** [cypress-io/cypress#6281]
I am running below test but it seems like it stuck at the resolving first promise and never been able to get out of it. The interesting thing is that if the same test has been run through the Chrome in UI mode (not in headless mode) then the test runs fine otherwise it fails. It always fails with Electron78 and also fails if test is kicked off with command line in Chrome as well.
I'm using Cypress V3.8.2, Node v12.10.0.

I have modified the original test and pasting a copy here:

```js
it('example test', async () => {
  cy.visit("http://www.qaclickacademy.com/");
  const content = await getText(cy.get('#content').find('h2'));
  assert.equal("Featured Courses", content);
  const reviews = await getText(cy.get('#about-reviews').find('h2'));
  assert.equal("What Our Students Say", reviews);
});

function getText(htmlElement) {
  return new Cypress.Promise((resolve) => {
    htmlElement.then(($el) => {
      cy.wrap($el);
      let message = $el.text();
      return resolve(message);
    });
  });
}
```

I raised an issue #6202 for this previously but it was never re opened so I'm raising a new issue.

Thanks
Aarti

**Comment by jennifer-shehane** [comment]
Closing. Do not open new issues for existing issues. We will reopen if necessary.
