### ISSUE TITLE
Create a toggle to close/open all folders in Tests list

### ISSUE THREAD

**Issue by Mat-Longinow** [cypress-io/cypress#6282]
**Current Behavior:**
Currently there seems to be no way to have all your folders defaulted to close when you open up Cypress.

The results is a messy UI that isn't as clean when you try and organize your many Cypress tests into folders.

**Desired Behavior:**
Have a setting option to default your folders to close on Cypress open that way you can navigate a cleaner interface when you organize your multiple tests into their appropriate folders.

![Screen Shot 2020-01-30 at 4 46 20 PM](https://user-images.githubusercontent.com/6404079/73503230-8dacac00-4380-11ea-9a1c-f5da020361ef.png)

**Comment by jennifer-shehane** [comment]
I would suggest adding something in the interface to click to collapse all folders to satisfy your needs.

Saving this as project state or global state would be trickier. Although we are working on interfaces for more configurable 'global' settings from within the UI, this would be a very low priority for us.

**Comment by netochaves** [comment]
Can I take this?

**Comment by sabina-rohman** [comment]
Hi, I am new to open source contributions. Please, assign it to me if it's not assigned to anybody. Thanks.
