### ISSUE TITLE
Returning arraybuffer from route does not work

### ISSUE THREAD

**Issue by travikk** [cypress-io/cypress#6287]
### Current behavior:

When trying to stub a route which returns an `ArrayBuffer`, Cypress will `JSON.stringify` the response.

### Desired behavior:

If it's detected that the response is an `ArrayBuffer`, raw bytes should be passed to the consumer.

### Test code to reproduce

```javascript
cy.route({
   method: 'POST',
   url: '/myapi',
   response: new ArrayBuffer(20), // this could be any array buffer, the result is always the same
   headers: {
      'Content-Type': 'binary/octet-stream'
   },
   onResponse: xhr => {
      console.log(xhr.response.body) // <-- the result here is an ArrayBuffer consisting of 123 and 125, which represent the following characters: "{" and "}" respectively.
   }
})
```

I believe it is due to the following: https://github.com/cypress-io/cypress/blob/master/packages/server/lib/controllers/xhrs.coffee#L51

### Versions

Cypress 3.8.2

**Comment by jennifer-shehane** [comment]
Yeah I don't think this is handled automatically, but seems that it may work if you set up a fixture and pass the `encoding` option.

**Comment by travikk** [comment]
@jennifer-shehane could you give me an example of what do you mean with encoding for fixture? How would that make things different compared to just hardcoding an arraybuffer as a response (like in the example above)?

**Comment by travikk** [comment]
@jennifer-shehane ping?

**Comment by jennifer-shehane** [comment]
Read about using fixtures for the response of your `cy.route()`: https://on.cypress.io/network-requests#Fixtures

`cy.fixture()` accepts an encoding argument: https://on.cypress.io/fixture

**Comment by travikk** [comment]
@jennifer-shehane according to the doc encoding refers to the format of the fixture file itself:

```
The encoding to be used when reading the file. The following encodings are supported:
```

If I understand the flow correctly, Cypress will use `encoding` to read and parse the fixture, then pass it down to `cy.route` which in turn will go to the Cypress XHR handler (see below).
How is that different to passing hardcoded Arraybuffer as a response directly to the `cy.route`? What I mean is, the part where the response (be it hardcoded or coming from the fixture) is stringified is always at the end of the flow right?

```
        ## TODO: if data is binary then set
        ## content-type to binary/octet-stream
        if _.isObject(data)
          data = JSON.stringify(data)
```

**Comment by DaleMatthews** [comment]
Has anyone gotten this to work yet? I'm on Cypress 5.5 and still see this issue.
```
    cy.fixture('images/example.png').then((base64_string) => {
      var arraybuffer = Uint8Array.from(atob(base64_string), c => c.charCodeAt(0));
      cy.route({
        method: 'GET',
        url: /v2/rendition?*',
        // response: arraybuffer,
        response: Cypress.Blob.blobToArrayBuffer(Cypress.Blob.base64StringToBlob(base64_string)),
        headers: {
          'Content-Type': 'application/octet-stream',
        },
      }).as('getRendition');
    });
```
The code then receives `[123, 125]` as stated in the original ticket.

**Comment by jquintozamora** [comment]
I'm having same issue with route2:

```typescript
          cy.route2({ method, pathname }, (req) => {
            req.reply((res) => {
              // buffer: Array(2)
              const data = new Uint8Array(buffer)
         
              console.log(data) // Uint8Array (2) [250, 260]
              
              res.send(200, data, {
                "content-type": "application/octet-stream",
              })
            })
          }).as("bufferArray")
```

data has the correct value before sending with res.send, but if console.log the real response is not returning `Uint8Array (2) [250, 260]` but instead is returning `{0: 220, 1: 260 }`. Looks like the array is converted to JSON

**Comment by DaleMatthews** [comment]
Here's a hacky work-around:
```js
    cy.fixture('images/example.png').then((base64_string) => {
      var buffer = Uint8Array.from(atob(base64_string), c => c.charCodeAt(0));
      cy.route({
        method: 'GET',
        url: '/v2/rendition?*',
        response: buffer,
        headers: {
          'Content-Type': 'application/octet-stream',
        },
        onResponse: (xhr) => {
          Object.defineProperty(xhr.xhr, 'response', { value: buffer});
        },
      }).as('getRendition');
    });
```

**Comment by flotwig** [comment]
`cy.route()` was removed in [Cypress 12.0.0](https://docs.cypress.io/guides/references/changelog#12-0-0), please try using [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept) instead, where stubbing the `body` with an `ArrayBuffer` should work. If you encounter issues with `cy.intercept()` and `ArrayBuffer`, please open a new issue. Closing this issue since the relevant API has been deprecated and removed.
