### ISSUE TITLE
Can't start Server!!!

### ISSUE THREAD

**Issue by Willie010** [cypress-io/cypress#6292]
### Current behavior:

Using cypress open or cypress run in Chrome browser and running specfile (with any tests) results in error: Can't start server 

Running in Electron 78 on either cypress open or cypress run works fine.

cypress open error message with Chrome
![image](https://user-images.githubusercontent.com/53355146/73568012-2862c480-442d-11ea-8b1e-6dabe9708d6c.png)

### Desired behavior:
cypress should work 
### Versions
Cypress version: 3.8.3
Chrome version: 79

**Comment by Willie010** [comment]
Pls i need help with this. All i did was updated cypress.

**Comment by Willie010** [comment]
@jennifer-shehane

**Comment by Sumedh-k** [comment]
Try reinstalling Cypress, clear your cache first.

https://docs.cypress.io/guides/guides/debugging.html#Clear-Cypress-cache

**Comment by jennifer-shehane** [comment]
@Willie010 Are you still experiencing this issue? Did you try clearing the cache?

**Comment by adomyaty55foundry** [comment]
@Sumedh-k & @jennifer-shehane 

Clearing the cache and reinstalling cypress 3.8.3 will not resolve this issue for me. And to reiterated with the OP; I'm also getting this issue

**OS:** Windows Subsystem for Linux 2 (WSL 2) on Windows 10

Electron works okay; just chrome and chromium getting connection refused:
cypress:network:connect retries exhausted, bubbling up error: errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect'

**Comment by Willie010** [comment]
> Try reinstalling Cypress, clear your cache first.
> 
> https://docs.cypress.io/guides/guides/debugging.html#Clear-Cypress-cache

@jennifer-shehane its working for me now after reinstalling cypress. Thanks

**Comment by tarponjargon** [comment]
I upgraded from 3.8.1 to 4.0.1 and can't run any tests in chrome, either in test runner or cli.  Receiving attached message.  I can run tests when choosing Firefox, Canary or Electron.

<img width="392" alt="Screen Shot 2020-02-12 at 8 42 59 PM" src="https://user-images.githubusercontent.com/12751386/74402965-97033300-4dda-11ea-988a-f61914c5f278.png">

**Comment by jennifer-shehane** [comment]
@tarponjargon Please open a new issue - this is not related to the original.
