### ISSUE TITLE
Make browser dropdown look more 'clickable'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6299]
### Current behavior:

Currently we see a lot of users who don't seem to realize that the browser dropdown is clickable. 

<img width="799" alt="Screen Shot 2020-02-03 at 2 16 25 PM copy" src="https://user-images.githubusercontent.com/1271364/73634978-d7530a80-4690-11ea-8e5e-b56d5518b311.png">

### Desired behavior:

Make it more obvious that the browser dropdown is clickable, especially since we'll be supporting more browsers

### Versions

3.8.2

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/6298, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by flotwig** [comment]
Released in [`4.0.0`](https://on.cypress.io/changelog#4-0-0).
