### ISSUE TITLE
Routes defined in beforeEach are incorrectly displayed in command log with no status

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#63]
Any `cy.route()` definitions in the beforeEach are displaying as grey with no status. When I click on the route in the command log, my console displays the status as 200 with a response and my UI is performing correctly (as if 200 response was received with data).

<img width="508" alt="screen shot 2015-09-15 at 2 10 42 pm" src="https://cloud.githubusercontent.com/assets/1271364/9885554/b872a25a-5bb3-11e5-9ee9-a0fdefd136b5.png">

**Comment by brian-mann** [comment]
Fixed in [`0.11.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0113-09162015).
