### ISSUE TITLE
 getting "chrome-error://chromewebdata/" 

### ISSUE THREAD

**Issue by swnathan** [cypress-io/cypress#6302]
In my Current Test when i click on Login Button i am redirecting to New Page 

1)But when running from Cypress i am getting "chrome-error://chromewebdata/" in the next Page
2) How to validate the Certficate for the Domain ,CypressProxyCA is sending Certificate Issue to the Domain i am currently Testing 

Any Suggestions are welcome

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

Cypress should handle certificates and there is no extra configuration required. If you need to set up Proxy configuration, see this guide: https://on.cypress.io/proxy-configuration

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏

**Comment by Tomas-Tr** [comment]
cypress does not support crossdomain testing. you can not navigate from one domain to another

**Comment by jennifer-shehane** [comment]
See this issue - is likely a duplicate https://github.com/cypress-io/cypress/issues/4220
