### ISSUE TITLE
Handle better cache list if there are no binaries installed

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6303]
Cypress v3.8.3 on CI

If we skill installing Cypress binary with `CYPRESS_INSTALL_BINARY: 0` env variable, then `cypress cache path` returns a folder name, but the folder does not exist. Then `cypress cache list` throws an error, yet exits with 0

![](https://user-images.githubusercontent.com/2212006/73661136-8ed32700-4667-11ea-8f26-33fc4014ea09.png)

https://github.com/bahmutov/cypress-gh-action-split-install/runs/423294744?check_suite_focus=true

## Proposal
`cypress cache list` should show a good warning message if the cache folder does not exist. It should still exit with zero code since there might not be any versions installed

**Comment by jennifer-shehane** [comment]
PR opened here to resolve this: https://github.com/cypress-io/cypress/pull/9023
