### ISSUE TITLE
Test Files aren't ignored after adding new code to index.js

### ISSUE THREAD

**Issue by AndresJCremades** [cypress-io/cypress#6305]
### Current behavior:

I modified the first time my `plugins/index.js` to ignore the` example` folder which is created the first time Cypress is opened and it worked:

```js
plugin/index.js
module.exports = (on, config) => {
  config.ignoreTestFiles = "**/examples/*.spec.js";
  return config
}
```

![image](https://user-images.githubusercontent.com/3080768/73666802-a3cdab80-46a3-11ea-8a25-cc366d7b4914.png)

Then I added these lines from the Plugin Documentation for switching between multiple configuration files

```js
plugin/index.js
const fs = require('fs-extra') 
const path = require('path') 

function getConfigurationByFile (platform, license, environment) {
  const pathToConfigFile = path.resolve('.', 'cypress', 'config', `${platform}.${license}.${environment}.json`)
  return fs.readJson(pathToConfigFile)
}

module.exports = (on, config) => {
  const license = config.env.license
  const environment = config.env.environment
  const platform = config.env.platform
  
  config.ignoreTestFiles = "**/examples/*.spec.js";

  return getConfigurationByFile(platform, license, environment)
}
```

And suddenly the `examples` folder is not ignored anymore

![image](https://user-images.githubusercontent.com/3080768/73666829-acbe7d00-46a3-11ea-9f32-c7f1fd369078.png)

### Desired behavior:

The `examples` folder is ignored.

### Test code to reproduce

More code isn't relevant in my opinion. The structure of the project is

![image](https://user-images.githubusercontent.com/3080768/73667572-c01e1800-46a4-11ea-822b-46b3203ec3d5.png)

### Versions

Cypress 6.13.7
Windows 10 Enterprise
Visual Studio Code

**Comment by jennifer-shehane** [comment]
The last line of your code is just returning the contents of the cypress config file, so it wouldn't have any of the mutation you already made to the `config` object previously. 

You never actually use the `config` object again that you set `ignoreTestFiles` on. You have to return the `config` object with the `ignoreTestFiles` property set how you want or it will not take effect. Try debugging by putting `console.log()` to see the Object you are returning and ensure it has the property you want.
