### ISSUE TITLE
Expand `before:browser:launch` to pass `options` argument instead of `args`

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6306]
### Current behavior: 

The current implementation of working off of the `args` Array during `before:browser:launch` is restrictive and doesn't allow for future adaptations needed. 

### Desired behavior:

Deprecate `before:browser:launch` argument `args: string[]` in favor of more configurable `launchOptions: object`, which allows user to control extensions, user preferences, and launch arguments passed to the browser.

### Versions

3.8.2

**Comment by Bkucera** [comment]
closed in #6293

**Comment by jennifer-shehane** [comment]
Released in [4.0.0](https://on.cypress.io/changelog#4-0-0)
