### ISSUE TITLE
`have.css` width and height calculating getBoundingClientRect not getComputedValue

### ISSUE THREAD

**Issue by wesmangum** [cypress-io/cypress#6309]
### Current behavior:

CSS width and height numbers are incorrectly calculated when transforms are applied.
<img width="1676" alt="Image 2020-02-03 at 1 59 44 PM" src="https://user-images.githubusercontent.com/5713417/73686442-9ad1df80-468d-11ea-96c7-f699959225df.png">
<img width="1671" alt="Image 2020-02-03 at 2 00 26 PM" src="https://user-images.githubusercontent.com/5713417/73686458-a2918400-468d-11ea-9082-1e05810eb743.png">
<img width="1670" alt="Image 2020-02-03 at 2 00 47 PM" src="https://user-images.githubusercontent.com/5713417/73686471-a7eece80-468d-11ea-8c67-cd4c8762a1ef.png">

### Desired behavior:

When calling for an element's width, it should use the `width` CSS value and not the client rect value.

### Test code to reproduce
Test Code:
```js
it('can activate custom animation on published site', function() {
  cy.step(
    'Activate custom animation with all possible action items including lottie'
  );
  cy.get('.custom').click();

  cy.step(`Assert element width correctly changed`);
  cy.get('.custom')
    .should('have.css', 'width')
    .and('eq', '306px');

  cy.step(`Assert element height correctly changed`);
  cy.get('.custom')
    .should('have.css', 'height')
    .and('eq', '372px');
  });
```
HTML for div with `custom` class:
```html
<div data-w-id="7674e6c0-102b-ba8e-6f7b-647aa0288ac4" data-animation-type="lottie" data-src="https://d1otoma47x30pg.cloudfront.net/5e399c02c3188d20fc3e90a3/5e399c02c3188d20fc3e90a4_cheer.json" data-loop="0" data-direction="1" data-autoplay="0" data-is-ix2-target="1" data-renderer="svg" data-duration="0" data-wf-id="[&quot;7674e6c0-102b-ba8e-6f7b-647aa0288ac4&quot;]" class="custom" style="display: grid; border-color: rgb(255, 0, 0); background-color: rgba(3, 153, 255, 0.67); filter: blur(1px) brightness(127%); opacity: 0.63; transform: translate3d(204px, 0px, 0px) scale3d(1.4, 1.4, 1) rotateX(360deg) rotateY(0deg) rotateZ(360deg) skew(12deg, -29deg); transform-style: preserve-3d; width: 306px; height: 372px; color: rgba(145, 253, 73, 0.91);"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 654 556" width="654" height="556" preserveAspectRatio="xMidYMid meet" style="width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px);"></svg></div>
```

### Versions
Cypress 3.8.3, macOS Catalina 10.15.3, Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
@wesmangum Can you provide the HTML code and test code to reproduce this? We'll need that to move forward with the issue. Thanks!

**Comment by wesmangum** [comment]
@jennifer-shehane I've updated the original comment with the test code and the HTML element in question.

**Comment by jennifer-shehane** [comment]
It seems that in Cypress, the comparison for `have.css`, `width` and `have.css` `height` is returning the values of height and width from the `getBoundingClientRect()` and not the `getComputedStyle()` of the element.

I'm pretty sure we just forward along chai-jquery's assertions here, so this is Chai-jquerys behavior? I'd have to verify this. 

`index.html`

```html
<html>
<body>
  <div id="custom" style="width: 306px; height: 372px; transform: skew(12deg, -29deg); background-color: blue; "></div>
  <script>
    const el = document.getElementById('custom')

    console.log(window.getComputedStyle(el).width) // 306
    console.log(window.getComputedStyle(el).height) // 372

    console.log(el.getBoundingClientRect().width) // 385.071044921875px
    console.log(el.getBoundingClientRect().height) // 541.6185913085938px
  </script>
</body>
</html>
```

`spec.js`

```js
it('css width', () => {
  cy.visit('index.html')

  cy.get('#custom')
    .should('have.css', 'width')
    .and('eq', '306px') // 385.071044921875px
});

it('css height', () => {
  cy.visit('index.html')

  cy.get('#custom')
    .should('have.css', 'height')
    .and('eq', '372px') // 541.6185913085938px
});
```

### Workarounds

To check on the actual style attribute, you could write the following assertion:

```js
it('css attr', () => {
  cy.visit('index.html')

  cy.get('#custom')
    .should('have.attr', 'style')
    .and('include', 'width: 306px')
    .and('include', 'height: 372px')
});
```

This is a bit more roundabout but would work

```js
it('css attr', () => {
  cy.visit('index.html')
  cy.window().then((win) => {
    cy.get('#custom').then(($el) => {
      expect(win.getComputedStyle($el[0]).width).to.eq('306px')
      expect(win.getComputedStyle($el[0]).height).to.eq('372px')
    })
  })
});
```

**Comment by Fodilahy-mena** [comment]
Hello here, 
This post really helped me a lot. I do appreciate it! I am just having an issue with my animation cypress test. 
 
I have `cy.get('.card').should('have.css', 'animation', 'whatever value here')` but it throws errors. I also got the same with border value. Without value works fine though `cy.get('.card').should('have.css', 'animation')` .

Do you think you have any solutions for this issue?

Thanks!
