### ISSUE TITLE
Jenkins display incorrect cypress logs.

### ISSUE THREAD

**Issue by NikitaUstsiushenka** [cypress-io/cypress#6313]
Hello, Jenkins build display incorrect logs:
![Screenshot (101)](https://user-images.githubusercontent.com/43332226/73726646-f9a46100-4740-11ea-8e8f-ec47a4049b43.png)

I updated encoding to UTF-8 and it is didn't help.

Thanks.

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Before I dive in to completely recreate the issue, could you update to the [current version of Cypress](https://on.cypress.io/changelog) and let me know if this is still happening for you? Your issue may have already been fixed. Thanks!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
