### ISSUE TITLE
One of the network request is skipped with cypress open or run

### ISSUE THREAD

**Issue by knagarajan1984** [cypress-io/cypress#6314]
### Current behavior:

Manually, When visiting my app and clicking on a button I see two network calls getting initiated for the same endpoints (One as `GET `and other as `OPTIONS`)

The request with initiator polyfills is an `OPTIONS` request and the initiator other is `GET` request

![image](https://user-images.githubusercontent.com/15121799/73737271-987d8d00-4742-11ea-99ba-662ad58a1039.png)

When clicking on the same button through my tests in cypress opened chrome browser (either cypress run or cypress open), I see that only the `GET` call is initiated and but the `OPTIONS` is not called. 

### Versions

Cypress 3.8.2
Chrome 79

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Comment by knagarajan1984** [comment]
I understand it may be impossible to fix the issue with the details provided earlier. Currently I have no clue why one of the call is not happening when going through cypress. May be some one in cypress might have come across such issue and share any info that can lead me to find workarounds or give you more information. @flotwig - any help please?

**Comment by youssef-sourour** [comment]
Hello, 
I got the same issue trying to click on button connect, first time the event doesn't redirect at all, for a second attempt it work perfectly and i saw that there are two request initiators ( other, and cypress ) that make tests randomly succeed or fail.
![image](https://user-images.githubusercontent.com/17954974/91330699-1631e480-e7ca-11ea-8af3-2f608aabafed.png)
