### ISSUE TITLE
Cypress can't find Chrome on v3.8.3 but fine on v3.8.0

### ISSUE THREAD

**Issue by 1881713** [cypress-io/cypress#6331]
Cypress can't find Chrome on v3.8.3 but fine on v3.8.0

### Current behavior:

Cypress can't find Chrome on v3.8.3, I am working on a project using v3.8.0 and cypress runs on Electron 78 and Chrome 79 - all's good
![image](https://user-images.githubusercontent.com/55796852/73856359-3baad100-482d-11ea-8723-28c0cfc1014b.png)

I have another project that I have cloned that uses v3.8.3 which has been installed, when I open the Test runner its only Electron 78 that is available
![image](https://user-images.githubusercontent.com/55796852/73856481-6e54c980-482d-11ea-8e3e-df8757f5ebd2.png)

If I try to run in Chrome from the CI I get "Can't run because you've entered an invalid browser name.
Browser: 'chrome' was not found on your system.

Available browsers found are: electron"
![image](https://user-images.githubusercontent.com/55796852/73856259-15853100-482d-11ea-9636-7cbda250f0cd.png)

The output from the DEBUG says chrome is not installed 
![image](https://user-images.githubusercontent.com/55796852/73857862-6dbd3280-482f-11ea-9c4e-080dadfd23ba.png)

but clearly is (as the other version can use it)
![image](https://user-images.githubusercontent.com/55796852/73858059-b543be80-482f-11ea-8db5-5fba299bff46.png)

I've tried the work around's suggested in #2843 and #4260 but still can get it to find Chrome

### Desired behavior:

Chrome is available in all Cypress versions

### Versions

Cypress 3.8.0 & 3.8.3
Windows 10 - Version 10.0.17763 Build 17763
Chrome - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Before I dive in to completely recreate the issue, could you update to the [current version of Cypress](https://on.cypress.io/changelog) and let me know if this is still happening for you? Your issue may have already been fixed. Thanks!

**Comment by 1881713** [comment]
This seemed to be an issue with commander, running with admin rights then opening Cypress I was getting Chrome again. I've reinstalled commander which has solved the issue. I've also upgraded Cypress to v4.0.1 and all good. Thanks
