### ISSUE TITLE
Recorded videos from Firefox play at the wrong speed

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#6337]
### Current behavior:
* Firefox records videos as a WEBM with variable framerate.
* When Cypress streams these chunks to `ffmpeg`, the variable framerate is incorrectly interpreted at a constant 15fps.
* This results in the output video appearing to run more quickly and more slowly at times, as the CPU load of other processes go up and down and affect the output framerate.
* A related issue occurs when a navigation of the `runner` occurs, which causes the timestamps of the WEBM to reset to 0.

### Desired behavior:
* Use the correct `ffmpeg` options so that the timestamp and framerates are accurately represented in the final captured `mp4`.
	* https://github.com/stoyanovgeorge/ffmpeg/wiki/Variable-Frame-Rate recommended `.outputOption('-vsync=0').videoFilter('setpts=N/FRAME_RATE/TB')`
	* `framerate` video filter may help: https://www.ffmpeg.org/ffmpeg-all.html#framerate
	* `fps` video filter may help: https://www.ffmpeg.org/ffmpeg-all.html#fps-1

### Versions
* Cypress 4.0.0
* Firefox, any version

Possibly caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1717868

**Comment by flotwig** [comment]
Seems to be much more evident with FF 80 now that we're not pausing so much...

**Comment by jennifer-shehane** [comment]
With the provided video from https://github.com/cypress-io/cypress/issues/9566, the Test Runner shows 13 seconds of runtime, but the video has already spread through it in 1 second of video time - then the frames are frozen for the rest of the 17 secs of video. https://github.com/cypress-io/cypress/files/5660042/actions.spec.js.mp4.zip

I was able to easily reproduce this on my Mac, running Firefox 81. The video speeds up very quickly (showing 30 seconds of tests in 1 sec) and then is frozen for the duration of the video. This makes the videos recorded from Firefox completely unusable.

**Comment by jpita** [comment]
I'm also having this issue on circleCI with firefox 83, so it seems platform independent

**Comment by oembe** [comment]
Same issue on Azure DevOps

Versions:
Cypress 6.2.1
Firefox 84.0.2

**Comment by flotwig** [comment]
Possibly related, this workaround bug impacts Firefox:  #16648

**Comment by flotwig** [comment]
This seems to be a bug with the `mediaSource: 'browser'` API used in `video-recorder.ts` to record videos in FF. Filed a bug on Mozilla's end: https://bugzilla.mozilla.org/show_bug.cgi?id=1717868

**Comment by jennifer-shehane** [comment]
This issue still exists. Reopening for tracking purposes.
