### ISSUE TITLE
Test Failed unexpectedly while recording on Dashboard

### ISSUE THREAD

**Issue by aman-mcmb** [cypress-io/cypress#6338]
Record on DashBoard

### Current behavior:

TestCase is passed, but shows failed unexpectedly.

Here are Logs

GVA info: Successfully connected to the Intel plugin, offline Gen75 

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.8.3                                                                              │
  │ Browser:    Electron 78 (headless)                                                             │
  │ Specs:      1 found (examples/messaging.js)                                                    │
  │ Params:     Tag: false, Group: false, Parallel: false                                          │
  │ Run URL:    https://dashboard.cypress.io/projects/kranha/runs/1                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  examples/messaging.js                                                           (1 of 1)

  Individual Chat Automation Scripts
[32452:0206/105344.459986:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[32452:0206/105344.460019:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
    ✓ send message 1-0-1 (37923ms)

TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (/Users/ajuneja1/webmessagingautomationv2.0/node_modules/mocha/lib/reporters/base.js:349:30)
    at Object.onceWrapper (events.js:291:20)
    at Runner.emit (events.js:208:15)
    at Reporter.emit (/Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:234:55)
    at Object.onMocha (/Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:359:18)
    at Socket.<anonymous> (/Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:303:32)
    at Socket.emit (events.js:203:13)
    at /Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (/Users/ajuneja1/webmessagingautomationv2.0/node_modules/mocha/lib/reporters/base.js:349:30)
    at Object.onceWrapper (events.js:291:20)
    at Runner.emit (events.js:208:15)
    at Reporter.emit (/Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:234:55)
    at Object.onMocha (/Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:359:18)
    at Socket.<anonymous> (/Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:303:32)
    at Socket.emit (events.js:203:13)
    at /Users/ajuneja1/Library/Caches/Cypress/3.8.3/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (18.7.0)
Cypress Version: 3.8.3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webmessaging@1.0.0 recordOnDashboard: `node_modules/cypress/bin/cypress run --record --key b6901b9c-7677-4e97-a658-200a22b9795e`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webmessaging@1.0.0 recordOnDashboard script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajuneja1/.npm/_logs/2020-02-06T05_24_15_992Z-debug.log
server:webmessagingautomationv2.0 root# 

### Test code to reproduce

/// <reference types="Cypress" />

describe('Individual Chat Automation Scripts', function() 
{
    before(function() {
        cy.fixture('example').then(function(data)
        {
            this.data=data;
        });
      });

    it('send message 1-0-1',function() {
        cy.visit(Cypress.env('url'));
        cy.get('#email').type('XXXXX@XXXXX');
        cy.get('#password').type('XXXXXX');
        cy.get('.loginBtNew').click();
        cy.task(`seleniumBrowser`);
        cy.get('[data-dialoglastmsg=dialogLastMsg]').eq(0).should('have.text',"Indivudal Chat Automation");
});
});

//Plugin Code

const {Builder, By} = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
require('chromedriver');
const chromeCapabilities = new chrome.Options();
const until = require('selenium-webdriver/lib/until');

module.exports = on => {
    on('task', {
        seleniumBrowser: async() =>{
            driver = new Builder().setChromeOptions(chromeCapabilities).forBrowser('chrome').build();
            myDriver = driver;
            await myDriver.get(`http://webv2.medicbleep.com/`);
            await myDriver.findElement(By.id("email")).click();
            await myDriver.findElement(By.id("email")).clear();
            await myDriver.findElement(By.id("email")).sendKeys("xyz@zxc.com");
            await myDriver.findElement(By.id("password")).clear();
            await myDriver.findElement(By.id("password")).sendKeys("XXXXXXX");
            await myDriver.findElement(By.xpath("//form[@id='passCryption']/div[3]/div/button")).click();
            await myDriver.sleep(5000);
            await myDriver.findElement(By.xpath("//section[@id='index']/div/div/div/div[2]/div[3]/section/div/div/div/div[2]/span")).click();
            await myDriver.findElement(By.id("newMsgTextarea")).click();
            await myDriver.findElement(By.id("newMsgTextarea")).clear();
            await myDriver.findElement(By.id("newMsgTextarea")).sendKeys("Indivudal Chat Automation");
            await myDriver.sleep(5000);
            await myDriver.findElement(By.id("chatMessageListing")).click();
            await myDriver.findElement(By.xpath("//section[@id='chat_dialog_id']/footer/div/div/div[3]/button/i")).click();
            await myDriver.sleep(5000);
            await myDriver.quit();
            return myDriver;
            }
        })
};
[cypress.zip](https://github.com/cypress-io/cypress/files/4163373/cypress.zip)

![Package_JSON](https://user-images.githubusercontent.com/54840531/73908890-14a5db00-48d1-11ea-8c7d-17bfcd974761.png)
![PLUGIN](https://user-images.githubusercontent.com/54840531/73908893-18396200-48d1-11ea-9953-6f327b34058e.png)
![CYPRESS_JSON](https://user-images.githubusercontent.com/54840531/73908895-1a032580-48d1-11ea-9b27-204071aba26a.png)
![error](https://user-images.githubusercontent.com/54840531/73908896-1a9bbc00-48d1-11ea-83ce-44358e59dce6.png)

### Versions
"cypress": "^3.8.3"
Chrome : 79
Mac OS version : 10.14.6

**Comment by DmitriyNikitinA** [comment]
what is this? `[32452:0206/105344.460019:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility`
in your result

**Comment by aman-mcmb** [comment]
> what is this? `[32452:0206/105344.460019:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility`
> in your result

After updating cypress to latest version. I started getting these messages.

**Comment by fedebertolini** [comment]
@aman-mcmb I had the same problem, I fixed it by downgrading `mocha` to `5.2.0`.
Also, if I were you I would remove all the references to auth credentials you have in screenshots and logs you posted
