### ISSUE TITLE
`channel` is not part of `Cypress.browser` object

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6339]
### Current behavior:

This is related to firefox/4.0 release branch.

The `Cypress.browser` object does not include the `channel` property. 

<img width="511" alt="Screen Shot 2020-02-06 at 12 22 14 PM" src="https://user-images.githubusercontent.com/1271364/73909713-c2b68280-48db-11ea-98fb-05d1dfb426a5.png">

### Desired behavior:

`Cypress.browser` should log all property from `before:browser:launch` and new `isBrowser`

### Test code to reproduce

```
it('should log props', () => {
  console.log(Cypress.browser)
})
```

### Versions

firefox branch -prerelease

**Comment by flotwig** [comment]
Fixed in https://github.com/cypress-io/cypress/pull/1359/commits/4139607638c05ede783517a374bbbd0b9c03f0da

We simply weren't copying the channel property to the browser obj which is later sent via the launch:browser IPC event.
