### ISSUE TITLE
`Cypress.isBrowser({ channel: 'stable' })` logging `false` with stable Google Chrome 80

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6340]
### Current behavior:

This is part of 4.0/firefox prerelease

Checking for `isBrowser` stable channel logs `false` when I run it in Chrome 80 stable browser. 

### Desired behavior:

Should print true for stable channels that are stable channels.

### Test code to reproduce

Ran this code and got the output below. `Cypress.browser` unfortunately does not log `channel` which is part of this issue so I can't see what channel it is evaluating to: https://github.com/cypress-io/cypress/issues/6339

```js
it('should be stable', () => {
  console.log('Cypress.browser', Cypress.browser)
  console.log(`Cypress.isBrowser({ channel: 'stable' })`, Cypress.isBrowser({ channel: 'stable' }))
})
```

<img width="817" alt="Screen Shot 2020-02-06 at 12 32 37 PM" src="https://user-images.githubusercontent.com/1271364/73910233-22f9f400-48dd-11ea-8a2a-ba1463bcb21f.png">

Got this to log through `cypress run` `before:browser:launch` and it does show as `stable` channel. 

<img width="622" alt="Screen Shot 2020-02-06 at 12 37 42 PM" src="https://user-images.githubusercontent.com/1271364/73910375-8d129900-48dd-11ea-981a-6d7697ac2123.png">

### Versions

firefox branch - prerelease

**Comment by brian-mann** [comment]
Your first issue is causing this issue. https://github.com/cypress-io/cypress/issues/6339
