### ISSUE TITLE
Make the position argument type of click, dblclick, rightclick more specific

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#6341]
### Current behavior:

Currently, the type of `position` in `click`, `dblclick`, `rightclick` is just `string`. Because of this, we cannot get the help of Intellisense.

### Desired behavior:

They should be replaced to `PositionType` like `scrollTo`, etc.

### Test code to reproduce

```js
it('test', () => {
  cy.get('#button').click('top')`. 
}
```

Intellisense doesn't work. 

![Screenshot from 2020-02-06 15-41-09](https://user-images.githubusercontent.com/8130013/73912442-db349600-48f7-11ea-9c1d-46c2e555ece8.png)

### Versions

3.8.3

**Comment by markoelez** [comment]
@sainthkh  Could I try tackling this issue? I am new to the codebase but would like to start contributing if possible :)

**Comment by sainthkh** [comment]
Good. Go on.

**Comment by markoelez** [comment]
@sainthkh  So I found the `VALID_POSITIONS` in packages/driver/src/cy/ensures.coffee, but I am not sure where to define the `PositionType` object. For Intellisense to work, I assume we would need to restrict the type in packages/driver/src/cy/commands/actions/click.js correct?

**Comment by sainthkh** [comment]
Cypress types are defined in cli/type/index.d.ts. Check the file, please.
