### ISSUE TITLE
{log:false} of clearLocalStorage doesn't work.

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#6342]
### Current behavior:

`cy.clearLocalStorage({log:false})` should not show the command on the reporter. But it does. 

### Desired behavior:

It should not show the command.

### Test code to reproduce

```js
it('test', () => {
  cy.clearLocalStorage({log:false})
})
```

Result:

![Screenshot from 2020-02-06 15-42-33](https://user-images.githubusercontent.com/8130013/73912310-87c24800-48f7-11ea-98ad-9b7f1e562578.png)

### Versions

3.8.3

**Comment by Jelijah** [comment]
Hello, I would like to work on this bug. Am I able to start working on this? What is required?

**Comment by sainthkh** [comment]
Just go on and submit a PR. [Here's the guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#committing-code).

If you have anything to ask, feel free to do it.

**Comment by maddhruv** [comment]
@sainthkh raised a PR here - https://github.com/cypress-io/cypress/pull/6495
