### ISSUE TITLE
Internal Server Error (500) thrown on click of ( New ) UI button action in my current application

### ISSUE THREAD

**Issue by subburajautomation** [cypress-io/cypress#6347]
Hi All ,

I am trying to automate a UI behavior where click on a New button in the admin site and  cypress throwing with 500 (Internal Server Error).

When clicking the same action manually in the cypress chrome browser we are not getting the Internal Server Error.

=================================
https://admin-.alk.com

![image](https://user-images.githubusercontent.com/17191182/73930381-6a43ad00-48fc-11ea-9a1c-9f3884045623.png)

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
