### ISSUE TITLE
All chrome docker image versions upgraded to chrome 80 again

### ISSUE THREAD

**Issue by tallkid24** [cypress-io/cypress#6353]
### Current behavior:
Repeat of yesterdays issue: https://github.com/cypress-io/cypress/issues/6335

Looks like the docker images were updated again today?

### Desired behavior:
Should run the correct version of Chrome

### Versions
cypress/browsers:node12.13.0-chrome78-ff70

**Comment by bahmutov** [comment]
ughh, I commented this out... one second

**Comment by bahmutov** [comment]
fixed
- cypress/browsers:node12.13.0-chrome78-ff70
- cypress/browsers:chrome67
- cypress/browsers:node12.6.0-chrome77
- cypress/browsers:chrome69

**Comment by bahmutov** [comment]
Closing for now - let me know if restoring one of the 3 images is needed

**Comment by bahmutov** [comment]
I have rebuilt and pushed two images - the only one I cannot rebuild because I cannot find Chrome v67 is cypress/browsers:chrome67-ff57
