### ISSUE TITLE
Cypress does not detect Firefox 64-bit browser

### ISSUE THREAD

**Issue by smit9234** [cypress-io/cypress#6355]
### Desired behavior:

On Windows 10 using Cypress v4.0.0, the Test Runner doesn't now show Firefox as an option in the browser list.

![image](https://user-images.githubusercontent.com/7388782/73985274-9dcc0a80-48ef-11ea-99d7-cdf838b7171e.png)

Looking at the browser configuration, Firefox is not listed.
![image](https://user-images.githubusercontent.com/7388782/73985324-b9cfac00-48ef-11ea-84ef-819df2c36698.png)

I copied the Firefox directory (C:\Program Files\Mozilla Firefox) to the AppData directory
..\AppData\Roaming\Cypress\cy\production\browsers

This doesn't update the browser list.

### Versions

4.0.0

**Comment by smit9234** [comment]
I just installed the 32 bit version (https://www.mozilla.org/en-US/firefox/all/#product-desktop-release).

I would suggest that Cypress be updated to also look at the C:/Program Files directory for 64 bit browser versions.

**Comment by flotwig** [comment]
Thanks for reporting this, you're right, currently only the 32-bit Program Files are considered.

**Comment by jennifer-shehane** [comment]
In the meantime, please follow the instructions for launching the Firefox browser by path
- https://on.cypress.io/launching-browsers#Launching-by-a-path 
- https://on.cypress.io/debugging#Launching-browsers

**Comment by jdvegmond** [comment]
Is the title correct? For me it doesn't detect the 64-bit version, but it does detect the 32-bit version.
Even when I specify the path to the 64-bit version, Cypress can't handle it. When I use
`npx cypress open --browser  C:\Progra~1\Mozill~1\firefox.exe` I get the following message:

Can't start server
We could not identify a known browser at the path you provided: C:\Progra~1\Mozill~1\firefox.exe
The output from the command we ran was:
Version=72.0.2.7321

(Cypress 4.0.0, Windows 10, latest Firefox 64-bit version)

**Comment by Amrkamel1** [comment]
@jennifer-shehane 

im experiencing same issue 

![image](https://user-images.githubusercontent.com/32042806/74017101-e2a97d00-4993-11ea-9621-89995dd8ab24.png)

![2020-02-07_10h22_07](https://user-images.githubusercontent.com/32042806/74017108-e89f5e00-4993-11ea-92e8-607f8f61020e.png)

**Comment by rzegnam** [comment]
> 
> 
> Is the title correct? For me it doesn't detect the 64-bit version, but it does detect the 32-bit version.
> Even when I specify the path to the 64-bit version, Cypress can't handle it. When I use
> `npx cypress open --browser C:\Progra~1\Mozill~1\firefox.exe` I get the following message:
> 
> Can't start server
> We could not identify a known browser at the path you provided: C:\Progra~1\Mozill~1\firefox.exe
> The output from the command we ran was:
> Version=72.0.2.7321
> 
> (Cypress 4.0.0, Windows 10, latest Firefox 64-bit version)

It doesn't detect 64-bit version using `--browser firefox` and providing the path to the firefox.exe.
Installing 32-bit helped.
