### ISSUE TITLE
App does not remember project when pinned to dock

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#636]
### Current behavior:
I already have a working Cypress project and I upgraded to 0.20.
The cypress files are in the `cypress` folder and our FE code is in the `sites` folder. Cypress will be installed in `site/node_modules`

First of all I have to open Cypress by calling the `open` command from the project root, to make sure that Cypress doesn't scaffold a new project in the `sites` folder. This is related to #635.

Second, the "Cypress should be versioned per project" message is displayed.
<img width="503" alt="image" src="https://user-images.githubusercontent.com/963136/30332709-51c872f8-97db-11e7-8048-9f501412f77a.png">

How is Cypress detecting if it installed per project/locally?
In think for both issues it would be better that Cypress is more flexible, for example by remembering which locally installed app is linked to which test codebase. In this case this would be `<root>/cypress` <-> `<root>/sites/node_modules/cypress` 

The main thing is that it doesn't remember my active project so everything I start up the app using the pinned App in the dock (attached it after I opened it locally). I have to reselect the project from the Recent Projects list. Maybe it is opening the globally installed app?

PS: I did uninstall `cypress-cli` globally.

- Operating System: OSX 10.12.6
- Cypress Version: 0.20
- Browser Version: n/a

**Comment by brian-mann** [comment]
Right, this is exactly what is happening - and we built `0.20.0` to account for this.

When you open the app directly (double click style) you're bypassing the CLI entirely and there is no `process.cwd()` so Cypress opens in "global mode".

It still works as it did in `0.19.4` albeit with a slightly new interface. We still remember and display a list of projects (and even sort them by how recently they were opened).

We assumed users who worked in this mode would not be opening the app after installing it via `npm` - we assumed they were users who just downloaded Cypress manually to try it out - or wanted to keep it in their `/Applications/` folder.

I'm actually having trouble understanding your other points - the #635 is definitely a bug and we'll fix that, and you should be able to point the binary to a subfolder other than where your `node_modules` is installed.

You'd then just be able to set this up in an `npm` script. Yes, it's true doing `cypress open` isn't as easy as launching the binary directly from OSX, but you can still do that and click into the project manually.

**Comment by jennifer-shehane** [comment]
Closing as outdated. Was only an issue on upgrade to 0.20.0
