### ISSUE TITLE
Error running plugin

### ISSUE THREAD

**Issue by EniFawehinmi** [cypress-io/cypress#6365]
### Current behavior:

I'm seeing this error when I run some of my tests. These tests were previously passing before I updated to version 3.8.3 (also seeing the error on 4.0.0)

<img width="704" alt="Screen Shot 2020-02-07 at 15 48 36" src="https://user-images.githubusercontent.com/26142257/74043992-3fbc2780-49c2-11ea-8038-8de34b6c9828.png">

My failing test is a version of [Gmail Tester](https://github.com/levz0r/gmail-tester)

This is what I currently have in my plugins/index.js file 

```
const cucumber = require('cypress-cucumber-preprocessor').default
const path = require("path");
const gmail = require("gmail-tester");
const gmail_tester = require("gmail-tester");

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())

  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--start-fullscreen')
      return args
    }

    if (browser.name === 'electron') {
      args['fullscreen'] = true
      return args
    }
  });

  on("task", {
    "gmail:get-messages": async args => {
      const messages = gmail_tester.get_messages(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "gmail_token.json"),
        args.options
      );
      return messages;
    }
  });
};

```
### Desired behavior:

Tests run as before without errors.

### Versions

Cypress - 3.8.3, operating system - macOS , browser - Chrome

**Comment by YOU54F** [comment]
https://docs.cypress.io/guides/references/migration-guide.html#Plugin-Event-before-browser-launch

try tweaking your config, to support the new interface for the browser launch api (https://docs.cypress.io/api/plugins/browser-launch-api.html#Syntax)

**Comment by EniFawehinmi** [comment]
That seems to have fixed the issue for me. Thank you @YOU54F
