### ISSUE TITLE
CircleCI throwing Socket hang up errors when running tests

### ISSUE THREAD

**Issue by utkarshsaxena93** [cypress-io/cypress#637]
### Is this a Feature or Bug?
Bug

### Current behavior:
When running a test on CircleCI, it throws `socket hangup error`. This error disappears randomly when it is rerun (only when I push new changes which lead to a new CircleCI run, not when I rebuild/rerun the same pipeline) 

### Desired behavior:
It should run the test.

### How to reproduce:
Attempt to run a test on circle CI

#### Test code:

```
cy.visit('https://admin4.myshopify.com') // This is a production URL you can go to from any browser
```

### Additional Info (images, stack traces, etc)
![screen shot 2017-09-12 at 11 19 32 am](https://user-images.githubusercontent.com/22102095/30336097-297c85d8-97b2-11e7-9ab1-1f22db35aa9e.png)

**Comment by brian-mann** [comment]
Possibly a bug in node code. Will investigate.

Refs:
https://github.com/nodejs/node/issues/9845

https://github.com/request/request/issues/2047

**Comment by utkarshsaxena93** [comment]
Thanks @brian-mann Let me know if I can help you with this in any way (testing it out, etc)

**Comment by Bkucera** [comment]
thanks @vladgolubev , I'm going to close this for now
