### ISSUE TITLE
TypeError Test Argument

### ISSUE THREAD

**Issue by zkilleb** [cypress-io/cypress#6371]
### Current behavior:

Running Cypress 4.0.0, I am presented with an error message at the start of my test run that states 

```
Uncaught TypeError: Test argument "title" should be a string. Received type "undefined"
```

Previously, running Cypress 3.8.3, it was able to successfully run the tests. Attempting to view the stack trace in the console presents me with the same message.

### Desired behavior:

Ability to run tests in Cypress 4.0.

### Versions

Cypress 4.0.0, Chrome 79, Electron 78, Node 12.8.1, Windows

**Comment by zkilleb** [comment]
We have a describe at the end of each spec file with an empty 'it' for reporting. This empty 'it' was causing the issue.

**Comment by jennifer-shehane** [comment]
I can recreate this. I ran this in a project with solely Mocha, and this seems to be coming from Mocha as a breaking change from the upgrade. 

<img width="920" alt="Screen Shot 2020-02-10 at 2 11 14 PM" src="https://user-images.githubusercontent.com/1271364/74130012-6622d280-4c0f-11ea-9c07-bf87c54d36a9.png">

We will not be fixing this behavior, as this is the default behavior now in Mocha. You need to provide a test title to your tests. 

I will add this to the [migration guide](https://on.cypress.io/migration-guide).

Code to recreate:

```js
it()
```

## 3.8.3

<img width="447" alt="Screen Shot 2020-02-10 at 2 02 43 PM" src="https://user-images.githubusercontent.com/1271364/74129486-11328c80-4c0e-11ea-90bd-fe2cc75f6d72.png">

## 4.0.0

<img width="442" alt="Screen Shot 2020-02-10 at 1 58 17 PM" src="https://user-images.githubusercontent.com/1271364/74129235-75a11c00-4c0d-11ea-91b0-3cee11bcf773.png">

**Comment by janupan** [comment]
<img width="977" alt="Screen Shot 2020-11-16 at 08 11 41" src="https://user-images.githubusercontent.com/18500720/99202909-60cc6700-27e3-11eb-95c2-ec0ea188823b.png">


Hi All, 
Anyone can that have the same problem?
Anyone can help me. 

I use "mocha": "^7.0.1", and "chai": "^4.2.0",
