### ISSUE TITLE
Broken links in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress#6373]
### Current behavior: 

Multiple broken links and a few typos in CONTRIBUTING.md

- [x] _Blog about Cypress. We display blogs featuring Cypress on our Examples page. If you'd like your blog featured, **open a PR to add it to our docs**._
Broken link: https://github.com/cypress-io/cypress-documentation/blob/develop/.github/CONTRIBUTING.md#adding-examples

- [x] _Write some documentation or improve our existing docs. Know another language? You can help us translate them. **See our guide to contributing to our docs**._
Broken link: https://github.com/cypress-io/cypress-documentation/blob/master/.github/CONTRIBUTING.md

- [x] _Issues may be opened about wanting changes to our **documentation**, our example-kitchensink app, or another repository. In this case you should_
Broken link: https://github.com/cypress-io/cypress/blob/develop

- [x] _Cypress documentation lives in a separate repository with its own dependencies and build tools. See **Documentation Contributing Guideline**._
Broken link: https://github.com/cypress-io/cypress-documentation/blob/master/.github/CONTRIBUTING.md

- [x] _Fill out the **Pull Request Tempalte** completely within the body of the PR. If you feel some areas are not relevant add N/A as opposed to **deleteing** those sections. PR's will not be reviewed if this template is not filled in._ (Some typos)
Broken link: https://github.com/cypress-io/cypress/blob/develop/PULL_REQUEST_TEMPLATE.md

### Desired behavior: 

all links go to a real page 👍🏽

### Test code to reproduce 

N/A

**Comment by jennifer-shehane** [comment]
@CypressCecelia Can you provide the exact links that are broken?

**Comment by thulin82** [comment]
I found some more as well, PR coming later this evening

**Comment by CypressCecelia** [comment]
@thulin82 Great! Submitting a PR now for the ones documented above. Can you add the additional broken links as a comment?

**Comment by thulin82** [comment]
In the CI-status-table:
[docsearch-scraper](https://github.com/cypress-io/docsearch-scraper) is not pointing to anything

Under "Coding Style"
[@cypress/eslint-plugin-dev ](https://github.com/cypress-io/cypress-eslint-plugin-dev) is not pointing to anything. (Should proably be "https://github.com/cypress-io/eslint-plugin-cypress"?

**Comment by clarmso** [comment]
Sounds crazy...but could we add tests ensure no links are broken in the docs? If so, where could we add such tests? I can see we have use `cy.request()` and check none of them results in HTTP 400. https://docs.cypress.io/api/commands/request.html

**Comment by thulin82** [comment]
> @thulin82 Great! Submitting a PR now for the ones documented above. Can you add the additional broken links as a comment?

Commented, will you add them in your PR?

**Comment by CypressCecelia** [comment]
@thulin82 Yes, adding the https://github.com/cypress-io/eslint-plugin-cypress link fix. The docsearch-scraper link does work but it is a private repo.

**Comment by jennifer-shehane** [comment]
Released in [4.0.2](https://on.cypress.io/changelog#4-0-2)
