### ISSUE TITLE
focus() didnt work with angular.how can I fix it?

### ISSUE THREAD

**Issue by chobijaeyu** [cypress-io/cypress#6379]
### Current behavior:

```
cy.get('[name="username"]').focus().type('username').should('have.class', 'ng-touched')
```

```
CypressError: Timed out retrying: expected '<input#mat-input-0.mat-input-element.mat-form-field-autofill-control.cdk-text-field-autofill-monitored.ng-untouched.ng-dirty.ng-valid>' to have class 'ng-touched'
```

### Desired behavior:
It's should be touched after focused and inputted.

### Test code to reproduce
```
/// <reference types="Cypress" />

const Testusername ="owner01",Testpassword="1234gogo"


describe('login',()=>{
    it('login with wrong password',()=>{
        cy.visit('localhost:4200')

        let _un = cy.get('[name="username"]').focus().type('owner01')
        _un.should('have.class', 'ng-dirty')
        _un.should('have.class', 'ng-valid')
        _un.should('have.class', 'ng-touched')
    })
})
```

### Versions
  "cypress": "^4.0.1",

**Comment by CypressCecelia** [comment]
Hello, in your test code, you are trying to save cy.get('[name="username"]').focus().type('owner01') to a variable _un. Cypress does not work this way, as outlined in the [Best Practices documentation here](https://docs.cypress.io/guides/references/best-practices.html#Assigning-Return-Values).

If you are trying to make an assertion on the initial element, you could chain the .should() command after the .type() command. There is additional [documentation on Assertions here](https://docs.cypress.io/guides/references/best-practices.html#Assigning-Return-Values).

**Comment by CypressCecelia** [comment]
Closed as resolved.

**Comment by chobijaeyu** [comment]
@CypressCecelia 
thanks for you answer.

actually,I tried `        cy.get('[name="username"]').focus().type('owner01').should('have.class','ng-touched')`

same error 
```
CypressError: Timed out retrying: expected '<input#mat-input-0.mat-input-element.mat-form-field-autofill-control.cdk-text-field-autofill-monitored.ng-untouched.ng-dirty.ng-valid>' to have class 'ng-touched'
```

but inspect html with devtool, this element does have 'ng-touched' class.

```
<input _ngcontent-bdm-c359="" type="text" matinput="" formcontrolname="username" name="username" placeholder="ユーザーID" required="" class="mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-dirty ng-valid ng-touched" ng-reflect-type="text" ng-reflect-placeholder="ユーザーID" ng-reflect-required="" ng-reflect-name="username" ng-reflect-form-control-name="username" id="mat-input-0" aria-invalid="false" aria-required="true">
```


here is my code:
```
describe('login',()=>{
    it('login with wrong password',()=>{
        cy.visit('localhost:3999')

        cy.get('[name="username"]').focus().type('owner01').should('have.class','ng-touched')
    })
})
```

**Comment by CypressCecelia** [comment]
Hey @chobijaeyu I was unable to replicate the issue. I tested with the following code:

`index.html`
```
<input _ngcontent-bdm-c359="" type="text" matinput="" formcontrolname="username" name="username" placeholder="ユーザーID" required="" class="mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-dirty ng-valid ng-touched" ng-reflect-type="text" ng-reflect-placeholder="ユーザーID" ng-reflect-required="" ng-reflect-name="username" ng-reflect-form-control-name="username" id="mat-input-0" aria-invalid="false" aria-required="true">
```
`test-spec.js`
```
describe('test', function() {
    it("checks class of element", function() {
        cy.visit("localhost:8080")
        cy.get('[name="username"]').focus().type('owner01').should('have.class','ng-touched')
    })
}
)
```
And it does pass.

![Issue6379Example](https://user-images.githubusercontent.com/60482585/75045311-0939de80-5491-11ea-8801-bb20b9fb77b7.gif)

**Comment by chobijaeyu** [comment]
@CypressCecelia 
thanks 
here is my issue gif

![ng-touched-issue](https://user-images.githubusercontent.com/25117318/75082530-5a140a80-5557-11ea-992d-0acbb839aa56.gif)
