### ISSUE TITLE
Tests running in Firefox still fails (on MAcOS) when a browser is already opened

### ISSUE THREAD

**Issue by StephaneColson** [cypress-io/cypress#6380]
### Current behavior:
Have a Firefox running
Open cypress ui
Select Firefox 72 (beta) and run tests (tested with [this repo](https://github.com/StephaneColson/HackatonApplitools) )
This page is opened in a new Firefox window (with 2 tabs, one empty): `file:///Users/stephane/Library/Application%20Support/Cypress/cy/production/browsers/firefox/interactive/`

<img width="947" alt="Screenshot 2020-02-08 at 09 38 35" src="https://user-images.githubusercontent.com/1481595/74082214-0fbf6380-4a58-11ea-98d1-599f1089cad4.png">

Then we saw that cypress cannot connect to the server

<img width="732" alt="Screenshot 2020-02-08 at 09 54 39" src="https://user-images.githubusercontent.com/1481595/74082322-18646980-4a59-11ea-846e-d9594a1f69b8.png">

It's OK if no Firefox running at the moment we launch the tests in Cypress.

### Desired behavior:
Be able to run the tests with FF without closing any other existing Firefox instances

### Versions
Cypress 4.0.1
Firefox 72.0.2 (64 bit)
MacOS Catalina 10.15.3

### Additional informations
This ticket follows [6356](https://github.com/cypress-io/cypress/issues/6356) which is closed (I don't have the error in console anymore)

**Comment by YOU54F** [comment]
@flotwig I wonder if the message should state something like “no other instances of Firefox launched, prior to opening cypress”

As it is not just related to two Firefox instances launched by cypress, but an ff instance being launched first by any means. Which would be nice to resolve in a future release if possible

**Comment by flotwig** [comment]
@YOU54F Weird. I wrote it like that because all open-mode sessions use the same profile and on Linux, I am able to run my personal Firefox profile alongside the profile Cypress launches. Is this reproducible 100% of the time on macOS?

**Comment by flotwig** [comment]
Sounds like passing -no-remote during Firefox launch might be the solution: https://www.brycevandyk.com/dissecting-firefoxs-no-remote-option/
