### ISSUE TITLE
Cypress not showing XHR requests in left hand pane causing api assertions to fail

### ISSUE THREAD

**Issue by iamdaniyalz** [cypress-io/cypress#6383]
while execution, cypress is not showing xhr calls in left hand pane (they are not fetch calls). if we look inside the network tab, there are multiple xhr requests there. 
### Current behavior:
So i have two .js files. 
1st file: I have the code in singlt long describe it() function. There, xhr requests are visible and everything works smoothly. all api assertions are passed
![single test valid login auth request](https://user-images.githubusercontent.com/52025650/74108301-be6bbd00-4b9a-11ea-93ac-06ffc017c8cf.png)

2nd file: Divided code into multiple describes and multiple it() functions for test cases. there i see no xhr calls in the left hand pane and every api assertion is failing. 

Please see the attached screenshots.
![valid login auth request](https://user-images.githubusercontent.com/52025650/74108304-c88dbb80-4b9a-11ea-8a18-1bd40650f8a2.png)
![invalid login auth request](https://user-images.githubusercontent.com/52025650/74108307-ca577f00-4b9a-11ea-9315-eed7a78953ab.png)

I get the error: CypressError: Timed out retrying: cy.wait() timed out waiting 5000ms for the 1st request to the route: 'invalidloginAuth'. No request ever occurred.

Please note that the above error is not due to invalid request syntax. I made sure to perform click after route() and before wait().

Please let me know if i need to add something in index.js or commands.js to get all requests in multiple test methods.

Running on windows x64.
Cypress: 4.0.0

**Comment by dupli-kate** [comment]
Hello,
Cypress automatically clears all cookies before each test to prevent state from being shared across tests.
From those screenshots it seems that you only have visit in your first test (first it).
More info: https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests

**Comment by CypressCecelia** [comment]
Closed as resolved.
