### ISSUE TITLE
cy.contains() falsely failing when using negative assertion 'not.contain'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6384]
### Current behavior:

When I use the `not.contain` assertion chained off of `.contains()`, it falsely fails. I suspect this is some regression introduced in https://github.com/cypress-io/cypress/pull/5653 cc @sainthkh 

#### 3.8.3

<img width="628" alt="Screen Shot 2020-02-10 at 1 28 51 PM" src="https://user-images.githubusercontent.com/1271364/74127531-4e485000-4c09-11ea-881f-5b6e5b9876bd.png">

#### 4.0.0

<img width="657" alt="Screen Shot 2020-02-10 at 1 25 10 PM" src="https://user-images.githubusercontent.com/1271364/74127497-383a8f80-4c09-11ea-94f1-cfc04f364f7c.png">

### Desired behavior:

The `div` does not contain the text `new` and should pass.

### Test code to reproduce

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <div>actions.spec.js</div>
</body>
</html>
```

#### This test falsely fails ❌ 

```js
it('repro', () => {
  cy.visit('index.html')
  cy.contains('actions.spec.js')
    .should('not.contain', 'new')
})
```

#### This test passes though ✅ 

This makes me believe it has to do with the return value of `cy.contains()`

```js
it('repro', () => {
  cy.visit('index.html')
  cy.get('div')
    .should('not.contain', 'new') // passes
})
```

#### And this passes though ✅ 

```js
it('repro', () => {
  cy.visit('index.html')
  cy.contains('actions.spec.js').then((el) => {
    
  }).should('not.contain', 'new') // passes
})
```

### Versions

Cypress 4.0.0

**Comment by sainthkh** [comment]
It has nothing to do with #5653. For some reason, [`obj.is(selector) || !!obj.find(selector).length`](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/chai.js#L281) is `false false` in 3.8.3, but `true false` in 4.0.1. 

Needs investigating.

**Comment by brian-mann** [comment]
Did we update a dependency in `4.0.0` that introduced this? Did we keep jquery versions the same? We've seen that be the root cause before.

**Comment by brian-mann** [comment]
Actually this might have to do with `chai` maybe?

**Comment by sainthkh** [comment]
Sorry, I was wrong. #5653 introduced this regression.

**Comment by Bkucera** [comment]
@sainthkh no worries, it was broken before that if you used a regex, but no one noticed. I'm working on the fix, which should clean up some logic.
