### ISSUE TITLE
Cypress 4.0.1 | Unable to detect Edge browser in Test Runner| Windows 10

### ISSUE THREAD

**Issue by a-onkar** [cypress-io/cypress#6390]
### Current behavior:

Update the existing cypress project to 4.0.1, when checked for browser options could not locate Microsft Edge.
Created a new project folder and freshly installed the new cypress, but still could not find the edge.

Screenprint attached.
![cyerror-edge not found](https://user-images.githubusercontent.com/25897622/74143129-1f72af80-4bf2-11ea-9e65-8111920c3ffb.png)

### Desired behavior:

I should be able to see edge browser in browsers drop-down of Test runner.

### Test code to reproduce
Windows 10
Install cypress
Check for edge browser in test runner.

### Versions

4.0.1

**Comment by a-onkar** [comment]
Found the solution

**Comment by bbonevPIT** [comment]
would you be able to share with us what was the solution if you dont mind please as I am facing the exact same problem?

**Comment by a-onkar** [comment]
Download Chromium Edge.

**Comment by jennifer-shehane** [comment]
Yes, Cypress only supports the Chromium-based Edge browser.
