### ISSUE TITLE
Cypress v4.0.1 - Cannot start server: args.find is not a function

### ISSUE THREAD

**Issue by you1anna** [cypress-io/cypress#6391]
### Current behavior:

- Click on test to run in Cypress UI

### Desired behavior:

- Chrome opens and runs the test

### Actual behaviour

![Screen Shot 2020-02-10 at 11 09 33](https://user-images.githubusercontent.com/7108767/74145271-49c66c00-4bf6-11ea-9fc2-dbb74afb5f95.png)

### Versions

MacOS Mojave 10.14.6
Cypress 4.0.1

**Comment by KJDataFeedWatch** [comment]
I not an experienced cypress user but I had quite a similar problem with Chrome version 80.0.3987.87
![screenshot](https://user-images.githubusercontent.com/47561013/74158828-0d593700-4c1b-11ea-888d-762e3373ecb2.png)
Linux Ubuntu 18.04.3 LTS
Cypress 4.0.1

**Comment by Zbychersky** [comment]
I had the same problem.

If you use cypress-log-to-output, just update it :)

**Comment by Dangeranger** [comment]
We have experienced this same error when starting cypress in CI mode using the following command line task run by Yarn.

```sh
PORT=${PORT:=3000} &&  start-server-and-test 'PORT=${PORT:=3000} && next start -p $PORT' http://localhost:$PORT 'PORT=${PORT:=3000} && cypress install && cypress run --config baseUrl=http://localhost:$PORT --browser=chrome'
```

**Comment by mck3nz1e** [comment]
Updating cypress-log-to-output resolved this issue for me

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
