### ISSUE TITLE
Cypress mat-menu inside button sometimes covered by another element

### ISSUE THREAD

**Issue by Tomas-Tr** [cypress-io/cypress#6393]
### Current behavior:

I have mat-menu inside button. **Circa once in 10runs** of cypress test, it is trying to click the mat-menu, but got error, that element is not visible, as it is covered by another element.

![image](https://user-images.githubusercontent.com/46347494/74155134-49d56480-4c14-11ea-94a3-3d93087227f1.png)

![image](https://user-images.githubusercontent.com/46347494/74155209-70939b00-4c14-11ea-8c2e-ab67a827a216.png)

### Desired behavior:

mat-menu inside button should be clickable

### Test code to reproduce

 
```html
<button
    mat-raised-button
    class="submit"
    [matMenuTriggerFor]="menu"
    data-cy="submit_btn"   
  >
    {{ 'forms.btn_submit' | translate }}
  </button>
  <mat-menu #menu="matMenu">
    <button
      mat-menu-item
      (click)="onClick()"     
      data-cy="submit_and_create_new_btn"
    >
      {{ 'forms.btn_submit_and_new' | translate }}      
    </button>
    <button mat-menu-item (click)="onClickAndClose()" data-cy="submit_and_close_btn">
      {{ 'forms.btn_submit_and_close' | translate }}
    </button>
  </mat-menu>
```

The test is clicking the green Submit button on picture. Waiting 1000ms to roll out the mat-menu and trying to click the `submit_and_close_button`.

```js
cy.get('[data-cy=submit_btn]')
        .should('be.enabled')
        .click();
      cy.wait(1000);
      cy.get('[data-cy=submit_and_close_btn]')
        .should('be.visible')
        .click();
```

### Versions

chrome
![image](https://user-images.githubusercontent.com/46347494/74155341-bbadae00-4c14-11ea-8b5b-008461c64fc2.png)

**Comment by jennifer-shehane** [comment]
I can't recreate the issue as described without the given css and or javascript used for the dropdown display. 

Below is the result of running the exact code you provided. 

<img width="777" alt="Screen Shot 2020-02-11 at 1 02 20 PM" src="https://user-images.githubusercontent.com/1271364/74215235-cb89c880-4cce-11ea-96a5-8ceb556b1bd5.png">

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <button mat-raised-button class="submit" [matMenuTriggerFor]="menu" data-cy="submit_btn">
    Button
  </button>
  <mat-menu #menu="matMenu">
    <button mat-menu-item (click)="onClick()" data-cy="submit_and_create_new_btn">
      Submit & create new
    </button>
    <button mat-menu-item (click)="onClickAndClose()" data-cy="submit_and_close_btn">
      Submit & close
    </button>
  </mat-menu>
</body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('[data-cy=submit_btn]')
    .should('be.enabled')
    .click();
  cy.wait(1000);
  cy.get('[data-cy=submit_and_close_btn]')
    .should('be.visible')
    .click();
})
```

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by Tomas-Tr** [comment]
I added css styles and div where are the buttons wrapped. also screenshot from browser.
I wanna mention again, that it runs OK also for me, but fails around once in 10 runs.

```
<div class="buttons">
  <button type="submit" (click)="cancel()" mat-raised-button
  data-cy="cancel_btn">
    CANCEL
  </button>
  <button
    type="submit"
    (click)="save()"   
    mat-raised-button
    color="accent"
    data-cy="save_btn"
  >
    CLOSE
    <mat-spinner           
      [diameter]="14"
    ></mat-spinner>
  </button>
  <button
    mat-raised-button
    class="submit"
    [matMenuTriggerFor]="menu"
    data-cy="submit_btn"    
  >
    SUBMIT
  </button>
  <mat-menu #menu="matMenu">
    <button
      mat-menu-item
      (click)="submit()"      
      data-cy="submit_and_create_new_btn"
    >
      SUBMIT AND NEW  
    </button>
    <button mat-menu-item (click)="submitClose()" data-cy="submit_and_close_btn">
     SUBMIT AND CLOSE
    </button>
  </mat-menu>
</div>
```


```

section mat-card {
  box-shadow: none !important;
  border-radius: 5px;
  color: gray;
}

.summary_row {
  padding: 10px 5px;
  border-bottom: 1px solid gray;
  & p:nth-of-type(2) {
    text-align: right;
    margin-right: 2rem;
  }
}

.summary_row:nth-of-type(odd) {
  background: white;
}

.summary_row:last-of-type {
  p {
    font-weight: bold;
  }
  border-top: 2px solid gray;
}

h3 {
  font-weight: 500;
  text-transform: uppercase;
}

.lastRowBold .mat-row:last-child .mat-cell {
  font-weight: 500;
}

.holder {
  height: calc(100% - 16px - 5rem);
  overflow: auto;
  margin: 0 0 1rem;
  color: gray;
}

section {
  padding: 0.5rem;
}

.buttons {
  text-align: center;
  margin-bottom: 1rem;
  & button {
    display: inline-block;
    margin: 0 0.25rem;

    &.submit:not(:disabled) {
      background: green;
      color: white;
    }
  }
}

p {
  color: grey;
  margin: 0;
}

.done-error {
  background-color: red;
}

.done {
  background-color: green;
}

.done,
.done-error {
  color: white;
  border-radius: 100%;
  overflow: hidden;
  display: inline-block;
  width: 16px;
  text-align: center;
  line-height: 16px;
  font-size: 12px;
  height: 16px;
  margin: 0 0.5rem;
}

.financial_info_value {
  text-align: right;
  margin-right: 2rem;
}

mat-spinner {
  display: inline-block;
}

```

![image](https://user-images.githubusercontent.com/46347494/74222706-64134f00-4cb5-11ea-8826-0ba01587dfda.png)

![image](https://user-images.githubusercontent.com/46347494/74222750-77beb580-4cb5-11ea-885c-7e275d8aefeb.png)

**Comment by ranetpgit** [comment]
I also have this issue, only happens occasionally.

**Comment by Tomas-Tr** [comment]
@jennifer-shehane  could you please check my reply on this closed issue? Thank you.

**Comment by jennifer-shehane** [comment]
@Tomas-Tr I'm still not able to recreate the issue with the HTML and CSS given. The tests pass - I ran many many times - it passes every time. My styles on my page do not look the same as yours so I don't think everything was provided to reproduce.
