### ISSUE TITLE
do not require security context when running performance tests on Circle

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6399]
Right now CircleCI job `server-performance-tests` gets environment variables from a security context `test-runner:performance-tracking`

```
- server-performance-tests:
    context: test-runner:performance-tracking
```

The variables are `PERF_API_KEY` and `PERF_API_URL` - but the security context blocks all outside PRs since the job cannot run.

## Workaround

- move the performance key and url to "regular" environment variables. They will be shared by all jobs, but will be undefined for outside PRs (which our code handles)

**Comment by jennifer-shehane** [comment]
Released in [4.0.2](https://on.cypress.io/changelog#4-0-2)
