### ISSUE TITLE
`onBeforeLoad` handler not called when overwriting `visit`

### ISSUE THREAD

**Issue by adamdicarlo** [cypress-io/cypress#640]
- Operating System:
macOS Sierra 10.12.6 (16G29)

- Cypress Version:
0.20.0

- Browser Version:
Built-in Electron

### Current behavior:

`onBeforeLoad` hook is not getting called when overwriting the `visit` command.

### Desired behavior:

`onBeforeLoad` hook should get called as it did in previous versions, and the docs state it should

### How to reproduce:

* Clone test repo
* From test repo, run `yarn`
* Run its cypress tests -- an `alert()` would happen if `onBeforeLoad` got called

#### Test code:

https://github.com/adamdicarlo/cypress-bug-640

**Comment by brian-mann** [comment]
This will go out in the next patch release.

**Comment by brian-mann** [comment]
Fixed in [`0.20.1`](https://docs.cypress.io/guides/references/changelog.html#0-20-1).
