### ISSUE TITLE
"Constructor is not a constructor" error on basic click() scenario

### ISSUE THREAD

**Issue by mlbrgl** [cypress-io/cypress#6402]
### Current behavior:

![Screenshot 2020-02-10 at 17 52 27](https://user-images.githubusercontent.com/13406362/74171474-ea388280-4c2e-11ea-86a4-e4b7d5b229f2.png)

Error: CypressError: Timed out retrying: Constructor is not a constructor

This seems to be specific to my app. I ran this same basic test on other sites without problems.

### Desired behavior:

I am expecting the link to be clicked without errors.

### Test code to reproduce

https://github.com/mlbrgl/cypress-test-tiny

```js
describe('page', () => {
  it('fails', () => {
    cy.visit('https://ourworldindata.org/polio')
    cy.contains('here').click() // error: CypressError: Timed out retrying: Constructor is not a constructor
  })
})
```
### Versions

Cypress: 4.0.1
Operating system: macOS 10.14.6
Browser: Chrome 80.0.3987.87

**Comment by jennifer-shehane** [comment]
Thank you so much for providing a reproducible example. 🙏 

There's another constructor warning detailed here that may be related: https://github.com/cypress-io/cypress/issues/5778

This is a regression introduced in 3.5.0.

*Note: The test you provided doesn't exactly work in 3.4.1 due mixed content, the link being clicked on containing a different protocol of `http` on an `https` site - @mlbrgl I'd recommend updating this on your webpage btw. All links within an https site should link to a secure `https` link. https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content*

I was able to narrow the issue down to this code:

`index.html`

```html
<!doctype html>
<html>
<body>
  <a href="https://polioeradication.org/polio-today/polio-now/">here</a>
  <script src="https://ourworldindata.org/assets/js/commons.js"></script>
  <script src="https://ourworldindata.org/assets/js/owid.js"></script>
</body>
</html>
```

`spec.js`

```js
it('fails', () => {
  cy.visit('index.html')
  // error: CypressError: Timed out retrying: Constructor is not a constructor
  cy.get('a').click() 
})
```

## 3.4.1

**Does not throw constructor error**

<img width="671" alt="Screen Shot 2020-02-11 at 1 54 21 PM" src="https://user-images.githubusercontent.com/1271364/74217516-0e02d380-4cd6-11ea-9ff8-17955eb8320b.png">


## 3.5.0

**Throws constructor error**

<img width="499" alt="Screen Shot 2020-02-11 at 1 52 43 PM" src="https://user-images.githubusercontent.com/1271364/74217522-13601e00-4cd6-11ea-9529-84cdd2ca51ba.png">

**Comment by mlbrgl** [comment]
Thanks for narrowing this down @jennifer-shehane, that's really helpful!

I'm not seeing any mixed-content issues on https://ourworldindata.org/polio. Are you referring to the link to http://polioeradication.org/polio-today/polio-now/? If that's the case, I don't think this is considered mixed-content. If I were to **load** a resource from an http:// site, then it would be - but in that case, I'm only **linking** to it, without loading it on the page. Please let me know if I got something wrong here and you meant something else.

Following your feedback, I updated the repro repo to isolate the problem further: https://github.com/mlbrgl/cypress-test-tiny/commit/7fdb1128f757d476119226a2aa939589a5194239.

**Comment by mlbrgl** [comment]
@jennifer-shehane I'm closing that issue as we found the incompatibility in our codebase:
https://github.com/owid/owid-grapher/pull/352/commits/9a5598f71a329a8dc912c00bf0c4bfb2eb13ac1f

Thanks!

**Comment by NateDawg90** [comment]
Hi, I am experiencing the "Constructor is not a constructor" error on Cypress 5.3. It occurs when I submit a form and then try to click something on the redirected page. As you can see the button is found by Cypress, but the click() function fails.

![Screen Shot 2020-12-07 at 10 24 16 AM](https://user-images.githubusercontent.com/18134083/101376699-8abef980-3876-11eb-8a84-0b6b3f0478a1.png)
