### ISSUE TITLE
Unable to perform if condition

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#6413]
im using protractor and recently started migration to cypress, but since im still new with it im encountering an issue with if condition and no way to avoid using it in my project as we are dealing with many API that are not stable and sometime it snapped during test so it requires if conditional, was using many error handling method like the on below but im unable to generate it in cypress

```js
afterEach(function () {
  ErrorOccured.isPresent()
    .then(function (timedOut) {
      if (timedOut) {
        ErrorOccured.getText()
          .then(function (text) {
            console.log('Ops!! we are getting ' + text);
          });
        helper.findElementByValueAndClick('span', 'RETURN TO HOME PAGE', 0);
        helper.waitVisibility(AccOverview);
      } else {
        SnapOccured.isPresent()
          .then(function (snapError) {
            if (snapError) {
              SnapOccured.getText()
                .then(function (Text) {
                  console.log('Damn we are facing!! ' + Text);
                });
              helper.findElementByValueAndClick('span', 'RETURN TO HOME PAGE', 0);
              helper.waitVisibility(AccOverview);
            } else {
              helper.waitVisibility(AccOverview);
            }
          });
      }
    });
  return;
});
```

### Current behavior:

![image](https://user-images.githubusercontent.com/32042806/74227082-09cabc00-4cbe-11ea-8bed-11939822cf48.png)

cypress not getting inside the else condition

### Desired behavior:

Should be able to perform this code or any alternative way that will give same behavior
 

### Test code to reproduce

```js
Cypress.Commands.add('errorHandling', () => {
  cy.get('[data-spec="error-page"]').then((visibility) => {
    // .then((timedOut) => {
    if (visibility) {
      cy.get('[data-spec="error-page"]').text().as('text');
      console.log('Ops!! we are getting ' + text);
      cy.get('span').contains('RETURN TO HOME PAGE', { matchCase: true }).first().click();
      cy.xpath('//span[contains(text(),\'Account Overview\')]').first().should('be.visible');
    } else {
      cy.get('[data-spec="page-500"]').then((visibility) => {
        // .then((snapError) => {
        if (visibility) {
          cy.get('[data-spec="page-500"]').text().as('Texa');
          console.log('Damn we are facing!! ' + Texta);
          cy.get('span').contains('RETURN TO HOME PAGE', { matchCase: true }).first().click();
          cy.xpath('//span[contains(text(),\'Account Overview\')]').first().should('be.visible');
        } else {
          cy.xpath('//span[contains(text(),\'Account Overview\')]').first().should('be.visible');
        }
      })
    }
  });
}); 
```

### Versions

4.0.1 chrome browser

**Comment by jennifer-shehane** [comment]
Cypress will fail the `cy.get()` command if the element is not found on the page, so there is zero possibility of the code within the `.then()` every running if the `[data-spec="error-page"]` element does not exist on the page. Therefore, if the `cy.get()` assertion passes, it will always exist and will never reach the `else` statement. 

Please read our [intro to Cypress](https://on.cypress.io/introduction-to-cypress#Cypress-Can-Be-Simple-Sometimes) doc which explains these concepts in detail. 

Also read our [conditional testing](https://on.cypress.io/conditional-testing) doc.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
