### ISSUE TITLE
Trouble with check if element contains some text

### ISSUE THREAD

**Issue by Brestachan** [cypress-io/cypress#6415]
OK, so I'm having trouble, and I'm not sure if I'm going in the right direction with this.
Anyway, the idea is that child element contains or do not contains some text. It's not working, not how I want it anyway. Any idea how to get this to work.

### **Current behavior:**

.expect error

### **Desired behavior:**

check if child element contains certain text

### Test code to reproduce

```js
Cypress.Commands.add('Delete_Roles',() => {
  //selects Roles->First Role, and checking if it contains "Admin"
  cy.get(':nth-child(7) > .border-left-black-3 > div.md-button > .md-no-style').expect('#iiotRoleListEdit0 > :nth-child(1)').not.to.contain("Admin")
  //click on Menu button next to selected role
  cy.get('#iiotLabelListActionMenu').click()
  //click on button DELETE located within menu
  cy.get('#iiotLabelListDelete').click({force:true})
  //click on confirmation pop-up OK button
  cy.get('.md-confirm-button').contains("OK").click()
  //selects Roles
  cy.get(':nth-child(7) > .border-left-black-3 > div.md-button > .md-no-style').click().wait(2000)

})
```

### **Versions**

Cypress 4.0, Ubuntu 18.4, Chrome 79

**Comment by jennifer-shehane** [comment]
`.expect()` is not a Cypress command and cannot be used in this way. Please read our docs. 

```js
// This is not the correct syntax of Cypress
cy.get('el').expect('el').not.to.contain("Admin")
```
