### ISSUE TITLE
Chainer descendants not found

### ISSUE THREAD

**Issue by dkln** [cypress-io/cypress#642]
### Is this a Feature or Bug?

Bug

### Current behavior:

Spits out error

`CypressError: The chainer: 'descendants' was not found. Could not build assertion.`

### How to reproduce:

Add a spec with:

`.should("have.descendants", ".some-selector")`

#### Test code:

```js
.should("have.descendants", ".some-selector")
```

**Comment by dkln** [comment]
Hopefully this is enough information for you guys! Seems to be broken in version 0.20.0.

**Comment by dkln** [comment]
Ah! Thanks! By the way, the documentation currently states this, I guess this should also be updated there 😃 

![screen shot 2017-09-13 at 14 51 15](https://user-images.githubusercontent.com/59295/30378294-0550c534-9893-11e7-93a8-9c66db339699.png)

**Comment by dkln** [comment]
Before I forget: this used to work in version 0.19.x

**Comment by brian-mann** [comment]
We rewrote chai-jquery in 0.20.0 and during that time we misspelled the word. It works right now as `descendents` but we'll update this to the proper spelling and get it out in the next patch release.

Perhaps we could do a levenshtein check to do the "Did you mean '...' suggestion

**Comment by brian-mann** [comment]
The code for this is merged, but it has not been released yet.

**Comment by jennifer-shehane** [comment]
Documentation typo fixed: https://github.com/cypress-io/cypress-documentation/pull/77

**Comment by brian-mann** [comment]
Fixed in [`0.20.1`](https://docs.cypress.io/guides/references/changelog.html#0-20-1).
