### ISSUE TITLE
Automate checking broken links in our Markdown files

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6420]
In #6373 @CypressCecelia has noted that several links are broken in the contributing guide markdown. We need to automatically check for broken links on CI

Here is a good tool to do this: https://github.com/tcort/markdown-link-check

Here is how it finds those broken links

<img width="862" alt="Screen Shot 2020-02-11 at 3 03 18 PM" src="https://user-images.githubusercontent.com/2212006/74274163-a487c280-4cdf-11ea-9c08-cb85c3878557.png">

Complication: some of our urls are internal links to private repos, so we need to handle that somehow

```
ERROR: 4 dead links found!
[✖] https://circleci.com/gh/cypress-io/cypress-on → Status: 404
[✖] https://github.com/cypress-io/cypress-on → Status: 404
[✖] https://circleci.com/gh/cypress-io/docsearch-scraper → Status: 404
[✖] https://github.com/cypress-io/docsearch-scraper → Status: 404
```

Second complication

```
$ npx markdown-link-check ./README.md --quiet
npx: installed 66 in 3.692s

FILE: ./README.md
[✖] /LICENSE

14 links checked.

ERROR: 1 dead links found!
[✖] /LICENSE → Status: 400
```

where we used the following in Markdown

```
[MIT license](/LICENSE)
```

**Comment by jennifer-shehane** [comment]
This is super low priority. Almost not worth the development time imo. What happens if a markdown link is broken? We're going to fail the whole build? That would not be ideal.

**Comment by bahmutov** [comment]
I respectfully disagree. @CypressCecelia just hit it, blocking her a little bit. Our users would be blocked when hitting a dead link, and our docs are out best part in my opinion, so we should keep this way. Automating link checks is sooooo easy and once automated, they should not go bad

- process https://glebbahmutov.com/blog/check-markdown-links/
- examples:
  * https://github.com/cypress-io/github-action/pull/87
  * https://github.com/cypress-io/code-coverage/pull/136

**Comment by elistone** [comment]
Hi, I have added the required npm package & setup a script in the packge.json.
I'm just not sure how or where to have this running automated. 

I assume circle.yml ?
