### ISSUE TITLE
require a json file doesn't work when path is given dynamic

### ISSUE THREAD

**Issue by bhaskerchari** [cypress-io/cypress#6427]
I basically want to load the assets dynamically from a json file which is dynamically generated from another pre executed script before my cypress test runner starts.
So I want to refer to that dynamicaly generated json file and load the data and generate tests (it blocks) dynamically based on the data.

![image](https://user-images.githubusercontent.com/5499784/74321899-124bf100-4da9-11ea-90b1-b9d9568f91a3.png)

**Comment by jennifer-shehane** [comment]
Have you tried using the [`cy.fixture()` command](https://on.cypress.io/fixture) to reference the dynamic file?

**Comment by bhaskerchari** [comment]
I don't get it why it is closed simply??? If you have really understood the problem I have a very valid question. require works differently when path is static vs dynamic as part of Cypress execution.

**Comment by jennifer-shehane** [comment]
@bhaskerchari Please provide a repo we can run with the provided code to demonstrate that require behaves differently within Cypress.

**Comment by peppi-scaleforce** [comment]
We have a similar issue reported here https://github.com/cypress-io/cypress/issues/23027
