### ISSUE TITLE
.its command with compound properties failing TypeScript check

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6431]
Cypress v3, v4

Our typescript definition for `cy.its` command "understands" the properties of the subject, thus it can do

```js
cy.wrap({ foo: 1 }).its('foo') // yup, subject has property "foo"
```

but it does not understand nested (compound) properties that Lodash `_.get` can do and we use under the hood

```js
cy.wrap({
  foo: {
    bar: 1
  }
}).its('foo.bar') // oops, TypeScript freaks out, "foo.bar" is invalid
```

Maybe someone can look at Lodash and its TypeScript definition for `_.get` to see if they have solved this problem and bring the solution?

**Comment by bahmutov** [comment]
Work-around

Add `// @ts-ignore` above the `its('foo.bar')` command to ignore just this line

**Comment by arshmakker** [comment]
can i work on this one?

**Comment by jennifer-shehane** [comment]
@arshmakker yes we would love an open PR. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by arshmakker** [comment]
Hi Jennifer, 

I am trying to write the test case:
`cy.wrap({
  foo: {
    bar: 1
  }
}).its('foo.bar')`

in the tests in 'CypressItsTests' namespace, I had two questions:

1. is 'CypressItsTests' the right place for this?
2. How to run exclusively the tests for 'CypressItsTests'

**Comment by jennifer-shehane** [comment]
1. This seems correct.
2. There is a Contributing Guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

Instructions for running the `cli` tests can be found here: https://github.com/cypress-io/cypress/blob/develop/cli/README.md 

Please feel free to open a WIP PR where we can address questions about the specific code you're writing.
