### ISSUE TITLE
When chainers are not found calculate Levenshtein distance for suggested: 'Did you mean'

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#644]
```js
expect($el).to.have.clas('foo') // should error and suggest: Did you mean 'class' ?
```

**Comment by bahmutov** [comment]
Use this https://www.npmjs.com/package/leven for fast computation

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
