### ISSUE TITLE
EINVAl for mkdir when running cypress to test a vue component on Jenkins on Windows10

### ISSUE THREAD

**Issue by eilensm** [cypress-io/cypress#6441]
### Current behavior:

I have a component test for a Vue component which is tested using the "cypress-vue-unit-test" library (https://github.com/bahmutov/cypress-vue-unit-test) mounted standalone on a page.

The test works fine when run locally on a Windows machine but fails on Jenkins (also on Windows). It seems that the argument passed to `mkdir` is wrong. The argument contains two paths and they are not separated by ";" and thus the invalid argument exception as shown below.

Command "cypress run" fails with the following error:

```
2020-02-13T10:25:00.688Z cypress:webpack errored bundling C:\Users\cruise\AppData\Roaming\Cypress\cy\production\projects\web-widgets-cfe04c3953f003c1b4eebca44f82952b\bundles\tests\components\support\index.js [Error: EINVAL: invalid argument, mkdir 'C:\Users\cruise\AppData\Roaming\Cypress\cy\production\projects\web-widgets-cfe04c3953f003c1b4eebca44f82952b\bundles\tests\components\support\d:\jenkinsInstanzen\WUF\home\workspace\_komponenten-tests-untersuchen_2\packages\web-widgets\dist'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'C:\\Users\\cruise\\AppData\\Roaming\\Cypress\\cy\\production\\projects\\web-widgets-cfe04c3953f003c1b4eebca44f82952b\\bundles\\tests\\components\\support\\d:\\jenkinsInstanzen\\WUF\\home\\workspace\\_komponenten-tests-untersuchen_2\\packages\\web-widgets\\dist',
  filePath: 'd:\\jenkinsInstanzen\\WUF\\home\\workspace\\_komponenten-tests-untersuchen_2\\packages\\web-widgets\\tests\\components\\support\\index.js',
  originalStack: "Error: EINVAL: invalid argument, mkdir 'C:\\Users\\cruise\\AppData\\Roaming\\Cypress\\cy\\production\\projects\\web-widgets-cfe04c3953f003c1b4eebca44f82952b\\bundles\\tests\\components\\support\\d:\\jenkinsInstanzen\\WUF\\home\\workspace\\_komponenten-tests-untersuchen_2\\packages\\web-widgets\\dist'"
}
2020-02-13T10:25:00.707Z cypress:server:plugins promise rejected for id inv2 ':' Error: EINVAL: invalid argument, mkdir 'C:\Users\cruise\AppData\Roaming\Cypress\cy\production\projects\web-widgets-cfe04c3953f003c1b4eebca44f82952b\bundles\tests\components\support\d:\jenkinsInstanzen\WUF\home\workspace\_komponenten-tests-untersuchen_2\packages\web-widgets\dist'

Oops...we found an error preparing this test file:

  tests\components\support\index.js

The error was:

Error: EINVAL: invalid argument, mkdir 'C:\Users\cruise\AppData\Roaming\Cypress\cy\production\projects\web-widgets-cfe04c3953f003c1b4eebca44f82952b\bundles\tests\components\support\d:\jenkinsInstanzen\WUF\home\workspace\_komponenten-tests-untersuchen_2\packages\web-widgets\dist'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
  (Results)
```

### Desired behavior:

The tests should run during the Jenkins build. The test runs without any errors on a local Windows 10 machine.

### Test code to reproduce

The following repo contains a Vue cli project with the same setup as used in the "real" repo. But of course I cannot provide a Jenkins integration/setup ;) On Jenkins, the same npm script is run as on local windows machine (`yarn run test:components`)

https://github.com/eilensm/cypress-jenkins-issue.git

### Versions

Cypress:  4.0.1
Browser:  Electron 78 (headless)
OS: Windows 10
Jenkins: 2.204.1
NodeJS: 12.14.1 LTS

**Comment by carcamano** [comment]
Hi,

Any update here? Facing same issue.

@eilensm have you found any solution?

Thank you

**Comment by eilensm** [comment]
I'm sorry. Didn't find a solution and have no idea yet...

**Comment by iongion** [comment]
Same stuff happening to me, on Windows using msys2 bash and conemu

**Comment by sense-it-gmbh** [comment]
The same happens to me. As far as i undestood this behavior is linked to the usage of `@cypress/webpack-preprocessor`: when using the plugin `mkdir` fails, wen not using it path aliases dont get resolved. `Error: Cannot find module '#/e2e/helpers' from 'Y:\GIT\****\tests\e2e\specs'` (`#` points to `/tests`)

**Comment by pavandixit93** [comment]
Same happens to me while running cypress test in angular project on windows system. FYI, when i run cypress commands manually e.g `yarn run cypress open` the same setup is working fine.

**Comment by dkazakov8** [comment]
Same error here, but it seems the roots of the problem may be different. I use `@cypress/webpack-preprocessor` as `webpackPreprocessor(webpackConfig)` and had
```
Oops...we found an error preparing this test file:
cypress\support\index.js
The error was:
Error: EINVAL: invalid argument, mkdir 'C:\Users\{user}\AppData\Roaming\Cypress\cy\production\projects\tests-f8dff6f6fde4ae18acdc262d03779461\bundles\cypress\support\D:\projects\{project}\build'
```
The problem was in `copy-webpack-plugin`, so disabling it or just `webpackPreprocessor(_.omit(webpackConfig, ['plugins']))` makes the trick.

**Comment by qieman** [comment]
Same stuff happening to me，on windows OS and Vue project. any solution ?
