### ISSUE TITLE
Key combinations that include a number are not working. 

### ISSUE THREAD

**Issue by danrhjones** [cypress-io/cypress#6444]
### Current behavior:
I am testing wordpress plugin that utilises keyboard shortcuts. An example of the shortcuts are:

For MacOs:

`option + 5` to add a comment
`option + k` to add a strikethrough

And the commands I am using are respectively:

```js
cy.get("body").type('{option}k5); //comment
cy.get("body").type('{option}k'); //strikethrough
```

When I call the command to strikethrough, the keyboard shortcut is run, and the strikethrough is applied to the text, however when I call the command for comment, nothing happens.

This is not the only keyboard shortcut that fails. All shortcuts that have a modifier key followed by a letter work fine, but any that are modifier then number do not work

(I have checked that these work fine manually!)

### Desired behavior:

Keyboard shortcut that contain a one or more modifiers followed by a number should be acted upon in the browser

### Test code to reproduce

I do not have a public version of the application, I will try to get one created 
### Versions

Cypress 4.0.1
Operating system MacOS 10.15.3
browser Chrome 79.0.3945.130

**Comment by jennifer-shehane** [comment]
@danrhjones I'm a little confused by the difference between your description and example. You say:

>option + 5 to add a comment

But then your code is typing a `k5` instead of just a `5`.

>cy.get("body").type('{option}k5')

Can you clear up exactly which usecase is not working? Is it doing `{option}k5` or doing `{option}5`?

Also, provided HTML code to run this against to show the issue would be very very helpful.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
