### ISSUE TITLE
Can't Start Server - options.onWarning is not a function

### ISSUE THREAD

**Issue by tarponjargon** [cypress-io/cypress#6445]
I upgraded from 3.8.1 to 4.0.1 and can't run any tests in chrome 79 or canary 82, either in test runner or cli. Receiving attached message. I _can_ run tests when choosing Firefox or Electron. I tried clearing the cache and reinstalling, according to the docs (no change).

### Current behavior:

<img width="392" alt="Screen Shot 2020-02-12 at 8 42 59 PM" src="https://user-images.githubusercontent.com/12751386/74450149-7d8dd580-4e32-11ea-9e2e-a3fd9ff15a07.png">

### Versions

Cypress 4.0.1, Mac 10.14.6, Chrome 79

**Comment by c32hedge** [comment]
I ran into a similar error before checking the [migration guide](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-4-0) -- in my case it was related to the [before-browser-launch](https://docs.cypress.io/guides/references/migration-guide.html#Plugin-Event-before-browser-launch) change.

**Comment by tarponjargon** [comment]
Ah - thank you for pointing that out to me.  Sorry for missing it!  For posterity's sake, this was my OLD plugins/index.js:

```
module.exports = (on, config) => {
  on("before:browser:launch", (browser = {}, args) => {
    if (browser.name === "chrome") {
      args = args.filter(arg => {
        return arg !== "--disable-blink-features=RootLayerScrolling";
      });

      return args;
    }
  });
  on("task", {
    failed: require("cypress-failed-log/src/failed")()
  });
};	
```

And the new one:

```
module.exports = (on, config) => {
	on("before:browser:launch", (browser, launchOptions) => {
		if (browser.name === "chrome") {
			launchOptions.args.push("--disable-blink-features=RootLayerScrolling");
		}
	});
	on("task", {
		failed: require("cypress-failed-log/src/failed")()
	});
};
```

**Comment by jennifer-shehane** [comment]
There should be a much clearer error in these cases when using 4.0.2 now.
