### ISSUE TITLE
Error looking for Global Cypress

### ISSUE THREAD

**Issue by zbomani03** [cypress-io/cypress#6455]
### Current behavior: 

An error is returned when looking for the global Cypress in the parent window.

```
 document.domain = 'localhost'; var Cypress = window.Cypress = parent.Cypress; if (!Cypress) { throw new Error('Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing!. This should never happen and likely is a bug. Please open an issue!'); }; Cypress.action('app:window:before:load', window); 
```

### Desired behavior:

global Cypress found.

### Test code to reproduce

![2020-02-13_20-28-46](https://user-images.githubusercontent.com/27927392/74493252-8c5ea180-4e9f-11ea-8799-df8c124c7bf2.png)

**Comment by jennifer-shehane** [comment]
This is not an error - there is no error being thrown within your console when you open it the Console tab. 

This is a script we inject into the head of web application when run within Cypress to ensure Cypress is properly defined (which will throw if it is not).
