### ISSUE TITLE
Unable to install dependencies via "npm install"

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress#6477]
### Current behavior:

After updating my fork of the repo, I cannot (re)install the dependencies without any errors.  Here is the relevant snippet of the error message:
```
> fmerge@1.2.0 install /home/ubuntu/environment/cypress/node_modules/fmerge
> node install.js

`fmerge.min.js` created

> husky@2.4.1 install /home/ubuntu/environment/cypress/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done
husky > Like husky? You can support the project on Patreon:
husky > https://www.patreon.com/typicode 🐕

> core-js@2.6.11 postinstall /home/ubuntu/environment/cypress/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /home/ubuntu/environment/cypress/node_modules/ejs
> node ./postinstall.js


> postinstall-postinstall@2.0.0 postinstall /home/ubuntu/environment/cypress/node_modules/postinstall-postinstall
> node ./run.js

00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn run postinstall
ERROR: [Errno 2] No such file or directory: 'run'

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/home/ubuntu/environment/cypress/node_modules/postinstall-postinstall/run.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

### Desired behavior:

`npm install` should output no errors.

### Test code to reproduce

* `cd` to the root directory of the Cypress repo.
* `npm install`

### Versions

OS: 
Mac OS Catalina 10.15.3
Ubuntu LTS 18.04

npm:
6.9.0
6.13.4

**Comment by sainthkh** [comment]
Cypress now uses yarn and lerna. Install it with the command, `yarn`.

**Comment by jennifer-shehane** [comment]
Yes, all of the Contributing and README files should be updated with the new `yarn` commands, so check those out for equivalents.

**Comment by maddhruv** [comment]
@sainthkh @jennifer-shehane I am also seeing the same error even when using `yarn` and `lerna`

How I fixed it?
- removed the `postinstall-postinstall` package and did `yarn`

Which finally succeeded the build/postinstall, (it fails in `ui-components` and `reporter` for me)

**Comment by sainthkh** [comment]
@maddhruv Maybe you might need to remove `packages-lock.json` and install packages again.

**Comment by maddhruv** [comment]
@sainthkh I don't have a `package-lock` in my local

**Comment by sainthkh** [comment]
How about removing all node_modules and reinstall?

**Comment by maddhruv** [comment]
I did ->
`yarn clean-deps` which removes all `node_modules` and did fresh `yarn`
still fails

**Comment by clarmso** [comment]
I removed all `node_modules` (including the ones in the sub-directories) and `yarn` works for me.

**Comment by maddhruv** [comment]
My system config
- OS - `Ubuntu 19.10 (x64)`
- Node - `12.8.1` (picked up from https://github.com/cypress-io/cypress/blob/develop/.node-version)

This time I did a fresh clone and ran `yarn` in the root, and it failed :fallen_leaf:

**Comment by maddhruv** [comment]
@jennifer-shehane @sainthkh @andrew-codes I don't understand why `postinstall-postinstall` is being used. It is failing there.

**Comment by maddhruv** [comment]
Raised a [PR](https://github.com/cypress-io/cypress/pull/6497) https://github.com/cypress-io/cypress/pull/6497 removing `postinstall-postinstall` script, which is actually fixing the `install` for me

**Comment by andrew-codes** [comment]
I am pulling some comments from the PR into this issue for better visibility:

Initial thoughts: https://github.com/cypress-io/cypress/pull/6497#issuecomment-588335879
Additional context: https://github.com/cypress-io/cypress/pull/6497#issuecomment-588402548
