### ISSUE TITLE
Docker for rhel8/centos8

### ISSUE THREAD

**Issue by mpalki1** [cypress-io/cypress#6483]
Hi,
 Could you please provide the Dockerfile for running cypress on RHEL8/Centos8

**Comment by bahmutov** [comment]
Have you checked our list of Docker images - I think we have cypress base image built on top of centos

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to the Cypress product. If you want to open an issue for our docker images, you can open it in [`cypress-docker-images`](https://github.com/cypress-io/cypress-docker-images). This issue will be closed in this repository.
