### ISSUE TITLE
Cookies are not being set correctly and Cypress is reporting that they are

### ISSUE THREAD

**Issue by pjaws** [cypress-io/cypress#6484]
### Current behavior:

I'm trying to write e2e tests for a very simple A/B test framework that sets a cookie to either '0' or '1', the UI will be different depending on the value of the cookie. Here's the test:

```js
  it('should show the original version if the cookie is set to "0"', () => {
    cy.setCookie(Cypress.env('OPTIMIZE_EXP_ID'), '0');
    cy.visit('/');
    cy.getCookie(Cypress.env('OPTIMIZE_EXP_ID')).should('have.property', 'value', '0');
    cy.reload();

    cy.get('input#firstname').should('exist');
    cy.get('input#lastname').should('exist');
  });
```

It doesn't matter whether I do `cy.reload()` or not. I've just been trying basically everything to get this test to work reliably.

The first assertion (that the cookie's value is '0') will always pass - whether or not the cookie is actually set to '0'.

[Here's a video showing this in action](https://www.loom.com/share/5f5f0fee582d48fb98d5962001b9cd31)

### Desired behavior:

`cy.setCookie()` and `cy.getCookie()` should work as expected.

### Versions

Cypress 4.0.2, Chrome 80

**Comment by jennifer-shehane** [comment]
This is absolutely related to the `cy.reload()`. The first test below passes without the `cy.reload()` and the second test fails with the `cy.reload()`. 

`cy.setCookie()` within my test below is setting the cookie within the application without the `cy.reload()`. If this is not the case in your test, then I'll need more information about your web app on why this isn't happening - provide an `index.html` like I have below. 

I'm not sure why `cy.reload()` should reset cookies however. This should not be happening. It seems to just be calling `win.location.reload()`

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <script>
    function showCookie() {
      document.getElementById('cookies-display').innerHTML = document.cookie
    }
  </script>
  <button id="cookies-btn" onclick="showCookie()">Show cookies</button>
  <div id="cookies-display"></div>
</body>
</html>
```

```js
it('should show the original version if the cookie is set to "0"', () => {
  cy.setCookie('FOO_BAR', '0');
  cy.visit('index.html');
  cy.getCookie('FOO_BAR').should('have.property', 'value', '0');
  cy.get('#cookies-btn').click()
  cy.get('#cookies-display').should('contain', 'FOO_BAR=0')
});

it('should show the original version if the cookie is set to "0"', () => {
  cy.setCookie('FOO_BAR', '0');
  cy.visit('index.html');
  cy.getCookie('FOO_BAR').should('have.property', 'value', '0');
  cy.get('#cookies-btn').click()
  cy.reload(); // reload
  cy.get('#cookies-display').should('contain', 'FOO_BAR=0') // fails
});
```

<img width="495" alt="Screen Shot 2020-02-18 at 1 18 34 PM" src="https://user-images.githubusercontent.com/1271364/74710952-3435ef80-5251-11ea-8067-102b7b576980.png">

**Comment by pjaws** [comment]
No, it’s absolutely not. Like I said, it happens with and without it.

**Comment by pjaws** [comment]
Also, cy.reload() should not affect cookies at al. I’ll post a video
showing the bug without reload when I can.

**Comment by pjaws** [comment]
Actually, you'll just have to take my word for it that `cy.reload()` was not the issue, because I discovered what the issue actually is.

Cypress is incorrectly setting the domain for the cookie. My local dev domain is `stage.wpengine.com.test, however Cypress sets the domain to `com.test` by default. So, it is setting a cookie, and the cookie does have the correct value, it's just for the wrong domain. My app sets the cookie if it's not already set, so then, we sometimes have a mismatch.

Thank you for responding to this quickly.

**Comment by dylangarcia** [comment]
We're having an issue too with the domain not being set properly (we use a subdomain).

**Comment by jennifer-shehane** [comment]
Sorry, relooking at this, my initial test was written incorrectly. This is not an issue with `cy.reload()` - the tests do still have the cookies set after `cy.reload()`. 

And yes, was coming to also comment this about the cookies. 

>Need host only cookie, so it’s not just applied to the subdomain

cc @flotwig

**Comment by flotwig** [comment]
@pjaws Have you tried setting the desired domain manually?

By default, `cy.setCookie` and other commands operate on the superdomain - so for `wpengine.com.test`, that is `com.test`.

Does this work like you want?

```js
cy.setCookie(Cypress.env('OPTIMIZE_EXP_ID'), '0', { domain: 'stage.wpengine.com.test' });
```

---

@dylangarcia The bulk of the tests for cookies are contained in [`2_cookies_spec`](https://github.com/cypress-io/cypress/blob/e0736b1358ef95c571122dd1dd9c8601f6361b94/packages/server/test/e2e/2_cookies_spec.coffee), which tests a variety of configurations.

**Comment by flotwig** [comment]
@pjaws Looking back at this, since the top-level domain is `.test`, you may be running in to the same issue as #6628, which will be fixed in the next release.

**Comment by pjaws** [comment]
Yes this ended up being the issue, which I fixed by manually setting the
domain.
