### ISSUE TITLE
Screenshots taken on retina displays are twice the resolution of their expected size

### ISSUE THREAD

**Issue by philcunliffe** [cypress-io/cypress#6485]
### Current behavior: 

cy.screenshot()'s taken on retina displays are twice the resolution of their actual size

When running cypress with the runner open, if the cypress controlled browser window is on a retina display (MacBook etc) the resolution of the screenshot is doubled. This is very problematic for visual regression testing.

### Desired behavior:

No matter what kind of screen the cypress controlled browser window is on it should come out with the same resolution

### Test code to reproduce

Any screenshot of an element should work this way

### Versions

Cypress: 3.8.3
OS: OSX
Browser: Either chrome or electron in the runner

**Comment by roman01la** [comment]
Any chance this gets fixed soon? Or are there known workarounds?

**Comment by roman01la** [comment]
I'd like to help with this issue. Any pointers where to look at would be helpful.

**Comment by roman01la** [comment]
A workaround is to run tests in Chrome and force 2x resolution through a flag

```js
// plugins/index.js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      launchOptions.args.push('--force-device-scale-factor=2')
    }
    return launchOptions
  })
}
```

and then run with Chrome
```bash
yarn run cypress run --browser chrome
```

**Comment by Bkucera** [comment]
I would recommend for visual regression testing that you use `--headless` when generating the screenshots if you intend to have a machine analyze them. Otherwise it's nearly impossible to get consistent screenshots across OS/screen sizes.

**Comment by mgrn0** [comment]
I don't know why but I am also getting double resolution images when running **HEADLESS** on a mac. I have to actively set my primary monitor to something that is NOT the built in retina screen to get "normal" sized screenshots.

**Comment by jennifer-shehane** [comment]
The default for all headless browsers after 8.0 will be 1.0 device pixel ratio, so standardized across `cypress run`. This change does not effect Cypress run during `cypress open` or headed. 

The code for this is done in [cypress-io/cypress#17377](https://github.com/cypress-io/cypress/pull/17377), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
