### ISSUE TITLE
503 From Cypress Server

### ISSUE THREAD

**Issue by garytryan** [cypress-io/cypress#6498]
### Current behavior:
Receiving this error when running in CI(Travis):

```
We encountered an unexpected error talking to our servers.
We will retry 3 more times in 30 seconds...
The server's response was:
StatusCodeError: 503 - "<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>"
```

### Test code to reproduce

Run a Cypress test in a CI platform using the following command:
`cypress run --record --key <KEY> --parallel`

### Versions
Cypress: 3.8.2
OS: :Linux
Broswer: Chrome

**Comment by dominicroessner** [comment]
Seeing the same thing running builds in GitHub Actions. Re-ran the build and it worked this time.

**Comment by CypressCecelia** [comment]
Hello @garytryan, this was related to a known issue affecting the Cypress Dashboard today. A fix has been implemented and we are currently monitoring results. [You can see and subscribe to updates here](https://status.cypress.io/incidents/601tfh5dnnqd). I apologize for the issue and inconvenience.

Closing this as resolved, but please add a comment or reopen if you continue to experience errors.
