### ISSUE TITLE
Chrome-beta 81: "The automation client disconnected. Cannot continue running tests."

### ISSUE THREAD

**Issue by bsodmike** [cypress-io/cypress#6501]
### Current behavior:
We had no issues with `chromium 79`, however, now with `chromium 80` or Chrome-beta `chrome-81`, we get the following error:

Error "The automation client disconnected. Cannot continue running tests."

### Desired behavior:

As with `chromium 79`, specs should run just fine.

### Versions

- Cypress 3.3.2
- Chromium 80
- Chrome (beta) 81

**Comment by bsodmike** [comment]
Seeing https://github.com/cypress-io/cypress/issues/6023 I'm not entirely sure it's worth doing a manual install of Chromium 79

**Comment by jennifer-shehane** [comment]
We have a PR open to test against Chrome 80 that may potentially find some issues. https://github.com/cypress-io/cypress/pull/6428 cc @flotwig

**Comment by dthomason** [comment]
Also seeing this issue in CI with Chrome 80

**Comment by bsodmike** [comment]
Hey @jennifer-shehane Thanks for the feedback!

I took a deeper look at the issue by building Chromium 78.0.3904.130 as I wasn't sure exactly which build "broke" between 79 and 80/81.

This provided a bit more insight with the additional detail of `Timed out waiting for the browser to connect. Retrying...`.

```
================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:  3.3.2                                                            │
  │ Browser:  Custom Chromium 78                                               │
  │ Specs:    24 found (active_members/change_status_spec.js, active_members/… │
  │ Searche…  spec/cypress/integration/active_members/change_status_spec.js, … │
  └────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────

  Running: active_members/change_status_spec.js...                    (1 of 24) 

Warning: Cypress can only record videos when using the built in 'electron' browser.

You have set the browser to: 'chromium'

A video will not be recorded when using this browser.

Timed out waiting for the browser to connect. Retrying...
The automation client disconnected. Cannot continue running tests.
```

Here's the [full log with debugging turned on](https://gist.github.com/bsodmike/3262804675eea74d4deff118722fa4bb).  I also took a look at the fixes you were posting at https://github.com/cypress-io/cypress/pull/6428 and interestingly there seems to be some issue with https-proxying going on here as well.

Chromium seems to be:

- calling out to `https://www.gstatic.com:443`
- calling out to `accounts.google.com:443` (this is probably to set the user account on the browser)
- From this point onwards there are gibberish proxied calls to `cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://rcuofdbafhynfb/'` and this continues.  I'm seeing _this_ issue being reported here https://github.com/cypress-io/cypress/issues/5263 but that issue is in the context of Docker. FYI I'm not testing with Docker.

**Comment by bsodmike** [comment]
@jennifer-shehane I wanted to verify behaviour with Chromium 80 (default Ubuntu install) and Cypress 3.3.2; here's the [full log (see my comment in the at the bottom of the linked Gist)](https://gist.github.com/bsodmike/3262804675eea74d4deff118722fa4bb).

The timeout behaviour does not present itself in this case.  Hope this will help you diagnose the issue further.

**Comment by bsodmike** [comment]
Upgrading Cypress has resolved this issue.  Thanks!

  │ Cypress:    4.0.2                                                                              │
  │ Browser:    Chromium 80

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
