### ISSUE TITLE
Running cypress tests in docker included image does not find cypress.json

### ISSUE THREAD

**Issue by tommueller** [cypress-io/cypress#6502]
### Current behavior:
I try running cypress tests in the `included` docker image. I found both a blog article describing it: https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/ as well as the minimal example from @bahmutov here: https://github.com/bahmutov/demo-docker-cypress-included

Cloning the repo and running the `cy-run.sh` results in the error:

> Could not find any tests to run.
> We looked but did not find a cypress.json file in this folder: /e2e

### Desired behavior:
The tests should run just fine.

### Test code to reproduce
Just clone the repo mentioned above and run `./cy-run.sh`. I tried switching to different versions of the cypress-included image (also 4.0.1), always the same error.

### Versions
Different cypress versions (see above).
Docker version: 19.03.3, build a872fc2f86

**Comment by jennifer-shehane** [comment]
I can't recreate the issue as described cloning and running directly from the repo.

This repo is only for issues relating to the Cypress product. If you want to open an issue on the demo-docker-cypress-image, you can open it [here](https://github.com/bahmutov/demo-docker-cypress-included). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.

**Comment by arjun9218** [comment]
I'm facing similar issue, trying to run `docker run -v $PWD:/e2e -w /e2e cypress/included:4.2.0` inside folder containing cypress.json throws an error stating that 
> We looked but did not find a cypress.json file in this folder: /e2e

**Comment by jennifer-shehane** [comment]
@arjun9218 If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by marlenemaiobarroso12** [comment]
Hello I'm facing the same issue. Have some news regarding this? or I should open a new issue?

Thanks

**Comment by jennifer-shehane** [comment]
@marlenemaiobarroso12 Please open a new issue filling in the issue template.
