### ISSUE TITLE
`cy.get('#foo$bar')` causes `Error: Syntax error, unrecognized expression: #foo$bar`

### ISSUE THREAD

**Issue by vjpr** [cypress-io/cypress#6503]
```
Error: Syntax error, unrecognized expression: #foo$bar
```

### Versions

```
Version 79.0.3945.130 (Official Build) (64-bit)
```

**Comment by vjpr** [comment]
Using the SelectorPlayground feature it seems to escape it as `#jobs\$Menu` but when I do this in code it still produces the error.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

Please provide the HTML you are testing against where you are looking to find an element using the `cy.get('#foo$bar')` syntax. We'd like to run the test ourselves to see the error.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
