### ISSUE TITLE
Cypress + PX (proxy) - Slowness + Temp workaround

### ISSUE THREAD

**Issue by Thundix** [cypress-io/cypress#6506]
### Current behavior:

Cypress with PX proxy software is very slow from the version 3.8.3 and above (working fine in 3.8.2)

https://github.com/genotrance/px

### Desired behavior:

Cypress with PX proxy should have a normal speed 

### Test code to reproduce

Any Cypress project with PX running Configured with local Host as Proxy

### Versions

3.8.2 working
3.8.3 + 4.0.2 not working

Electron browser, Windows OS

**Workaround :** 

If I increase the number of workers to 30, it reduce the slowness to acceptable level
Direct proxy (used in CI) is working fine

**Comment by Thundix** [comment]
![image](https://user-images.githubusercontent.com/17887868/74840149-c3610700-5326-11ea-9fc8-550b26d2665c.png)

**Comment by Thundix** [comment]
Any check on this ?

**Comment by Thundix** [comment]
Any news ?

**Comment by jennifer-shehane** [comment]
Can you  update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you? We did fix a performance issue in 4.2.0 - that was introduced in 3.8.3, so it may be related. https://github.com/cypress-io/cypress/pull/6705

**Comment by Thundix** [comment]
Yes, upgrading to 4.2.0 fix it

Thx !
