### ISSUE TITLE
No able to load test into cypress where URL having http://10.10.11.09/app/admin/home

### ISSUE THREAD

**Issue by amitdhanke** [cypress-io/cypress#6511]
code ->

```js
describe("  This testsuite is for test cloud scenarios ",function(){

    it(" Check cloud functionality ",function(){

       cy.visit("URL with IP")

       cy.get('input[name="j_username"]').type('XXX')

       cy.get('input[name="j_password"]').type('XXXXX')

       cy.get('button[title="Sign in"]').click()

    })

})
```

Issue 
oops there is now test to load!!!

Browser: Chrome79/78 ,FF72,electron78

OS: windows

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

Please provide an example that we can run on our machines and we will consider reopening. We do not have access to your application under test, so we can't move forward with this information.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
