### ISSUE TITLE
Error when installing cypress using Node.js version < 8.12.0

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6512]
### Current behavior:

When installing Cypress with Node.js version less than 8.12.0 install is prevented by the following errors.

`yarn`

Warning you are not on compatible engine

```
error execa@3.3.0: The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.0.0"
error Found incompatible module.
```

`npm install`

Even more cryptic - there's just an execa error

```
 npm i --save-dev cypress

> cypress@4.0.2 postinstall /Users/jennifer/Dev/cypress-transform-test/node_modules/cypress
> node index.js --exec install

/Users/jennifer/Dev/cypress-transform-test/node_modules/execa/index.js:18
	const env = extendEnv ? {...process.env, ...envOption} : envOption;
	                         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jennifer/Dev/cypress-transform-test/node_modules/cypress/lib/util.js:18:13)
```

### Desired behavior:

Cypress install [should support Node.js 8+ as of 4.0.0](https://on.cypress.io/migration-guide#Node-js-8-support), so should support an install with Node.js versions as low as 8.0.0

### Why

Execa introduced this breaking change (a fix for a change that should have gone in their 2.0.0 release I guess) without actually noting it as a breaking change., requiring at least Node.js 8.12.0 in their 2.0.1 release.

**Execa 2.0.1 release notes:** https://github.com/sindresorhus/execa/releases/tag/v2.0.1

You can see this change by diffing the package.json from the releases

- execa 2.0.0 package.json https://github.com/sindresorhus/execa/commit/ec10a4c7b5732edb76e7a20e29ffa3996bcde80a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
- execa 2.0.1 package.json https://github.com/sindresorhus/execa/commit/97ef87d5d30542041d69cb4942bc10f98fc7579c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

### Code required

We should revert execa dep in the cli back down to 2.0.0.

### Versions

Cypress 4.0.0

**Comment by jennifer-shehane** [comment]
I actually don't think this is closed. We really need to go back to execa 1.0.0, because 2.0.1 was simply changing the engines field and the real effective non-support for 8.0.0 went into 2.0.0.

**Comment by jennifer-shehane** [comment]
I verified this by installing the binary from `develop` myself on Node 8.0.0 - it fails.

**Comment by Ebazhanov** [comment]
FYI the same here, caught 2 weeks ago after trying to switch to the new version - 4.0.0
```
#!/bin/bash -eo pipefail
$ meteor yarn
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error execa@3.3.0: The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.11.4"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exited with code exit status 1
