### ISSUE TITLE
Cypress adds trailing slash to baseUrl during cy.visit('/')

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6515]
### Current behavior:

Cypress adds a trailing slash to the `baseUrl` during `cy.visit('/')` which can causing routing to go to a non-existent route.

### Desired behavior:

No trailing slash should be added. This is similar to a very, very old issue here: https://github.com/cypress-io/cypress/issues/3

Changelog from fix for older issue:

>cy.visit() now inserts a trailing slash intelligently into the correct path position (not after query params or hashes).

It should likely also not add a trailing slash after a file extension.

### Test code to reproduce

`cypress.json`

```json
{
  "baseUrl": "https://docs.cypress.io/guides/overview/why-cypress.html"
}
```

`spec.js`

```js
it('visits', () => {
  cy.visit('/')
})
```

<img width="1196" alt="Screen Shot 2020-02-20 at 3 48 52 PM" src="https://user-images.githubusercontent.com/1271364/74919122-849b8180-53f8-11ea-9395-cfc48a5f12e5.png">

### Versions

Cypress 4.0.2

(I don't see any indication in previous versions that this has ever worked)

**Comment by jennifer-shehane** [comment]
I originally opened this from another comment that I can no longer find. Anyway, this is not considered an issue because the definition of `baseUrl` is not a fully qualified url, which a url with a file extension is. Will not fix.

**Comment by scytacki** [comment]
This behavior just caused me problems. I understand changing it would probably break a lot of stuff. So I'm not asking to fix it, but wanted to leave a comment to record that it is a pain point.

In my use case we sometimes test against urls like `https://example.com` and sometimes urls like `https://example.com/index-staging.html`. And we usually configure the app with query params. 
- Using `cy.visit("?appMode=qa")` results in `https://example.com/index-staging/?appMode=qa`. 
- Using `cy.visit("", qs: {appMode: "qa"}) also results in `https://example.com/index-staging/?appMode=qa`

My work around for now is to overwrite the visit command so it handles this case.
