### ISSUE TITLE
Consecutive hash changes do not fire in backbone

### ISSUE THREAD

**Issue by paulfalgout** [cypress-io/cypress#652]
https://github.com/paulfalgout/cypress-issue

- Operating System: osx
- Cypress Version: 0.20.0
- Browser Version: chrome 60

### Is this a Feature or Bug?
Bug

### Current behavior:
Consecutive hash changes don't hit every route

### Desired behavior:
All routes are hit

### Additional Info (images, stack traces, etc)
Adding `wait(0)` between the `visit`s will run all routes.

**Comment by jennifer-shehane** [comment]
Second hash change never hits "url:changed" event. Forked repo here: https://github.com/cypress-io/cypress-issue

**Comment by brian-mann** [comment]
The code for this is merged, but it has not been released yet.

**Comment by brian-mann** [comment]
Fixed in [`0.20.1`](https://docs.cypress.io/guides/references/changelog.html#0-20-1).
