### ISSUE TITLE
we should print video resolution in the terminal

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6520]
If we are saving a video file, we should report its resolution in the terminal. We already show the resolution of each saved screenshot

<img width="1125" alt="Screen Shot 2020-02-20 at 10 58 43 AM" src="https://user-images.githubusercontent.com/2212006/74953867-3d00ff80-53d0-11ea-9552-ffabc3a66c41.png">

**Comment by Sumedh-k** [comment]
@bahmutov  There is small bug with the logging as well.

In cypress.json if you have "videoCompression": false

and then run the tests, you wont see any message in the log about the Video, if you change false to videoCompression": 0. (or any other valid number) you will see the logs

  (Video)
  -  Started processing:  Compressing to 0 CRF

Even if the video compression is false there should be message in the log.

**Comment by maddhruv** [comment]
Hey, @bahmutov can you point me to the file/module which is responsible for this logging? Is it `server`?
