### ISSUE TITLE
cy.ng fails with misleading error that does not show the real issue in the callback

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6526]
Cypress v4.0.2

In project https://github.com/cypress-io/cypress-example-phonecat/tree/fail the failure is misleading

To run:
- clone
- `npm install`
- `npm run dev` and open the test

The test is as follows

```js
it('fails', () => {
  cy.visit('/index.html#!/phones')
  cy.ng('model', '$ctrl.query').as('q')
  function getNames($names) {
    return $names.map(function (index, el) {
      return Cypress.$(el).text()
    }).get()
  }

  cy.get('@q').type('tablet')
  cy.ng('binding', 'phone.name')
    .should(function ($names) {
      expect(getNames($names), 'default order of names').to.deep.eq [
        'Motorola XOOM™ with Wi-Fi',
        'MOTOROLA XOOM™'
      ]
    })
})
```

Notice the real problem - missing braces around the array, should be `expect(getNames($names), 'default order of names').to.deep.eq([ ...`

But the error shows the following, implying that the `cy.ng` has failed to find the names.

<img width="1279" alt="Screen Shot 2020-02-20 at 3 23 23 PM" src="https://user-images.githubusercontent.com/2212006/74975590-49e41a00-53f5-11ea-954d-147624208699.png">

(you can add console.log or debugger statements into the `should` callback to see that the names are actually there)

**Comment by chrisbreiding** [comment]
This must be the culprit: https://github.com/cypress-io/cypress/blob/e0736b1358ef95c571122dd1dd9c8601f6361b94/packages/driver/src/cy/commands/angular.coffee#L38-L38

**Comment by emilyrohrbough** [comment]
We have removed support for `cy.ng()` in https://github.com/cypress-io/cypress/pull/23791. For support testing Angular in Cypress, see https://docs.cypress.io/guides/component-testing/angular/overview.
