### ISSUE TITLE
I have updated my cypresss to 4.0.2 but still do not  have firefox and edge in the cypress runner

### ISSUE THREAD

**Issue by begli80** [cypress-io/cypress#6528]

**Comment by begli80** [comment]
<img width="373" alt="no edge and firefox" src="https://user-images.githubusercontent.com/39811047/75002719-f7bdeb80-542a-11ea-8a00-082fc5271a22.PNG">

**Comment by prabhumohan09** [comment]
Hi,

Cypress support only chromium-based edge browsers and beta firefox browser even we update with the latest version. 

Could you find here release notes
https://docs.cypress.io/guides/references/changelog.html#4-0-1

So make sure your browsers version and type
firefox - https://lnkd.in/fvSUXq4
edge - https://lnkd.in/fDaJ64n

**Comment by jennifer-shehane** [comment]
@prabhumohan09 We support any Firefox browser - not just *beta* Firefox browsers. So Firefox, Firefox Developer Edition, Firefox Nightly Edition. 

Full list of browsers supported here: https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers

There shouldn't be an issue finding these browsers installed on your system. 

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress and OSX you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏

**Comment by prabhumohan09** [comment]
thanks, @jennifer-shehane for the details
