### ISSUE TITLE
Travis CI run fails when local test run is successful

### ISSUE THREAD

**Issue by ror6ax** [cypress-io/cypress#6531]
### Current behavior:

Running same test locally and in Travis gives different results. My local run works fine, whereas CI run fails.

### Desired behavior:

CI run fails only when my local run fails. I've added a wait-on as per documentation's advice. Didn't help.

### Test code to reproduce

CI run is here https://travis-ci.org/phylogeny-explorer/explorer/jobs/653594139?utm_medium=notification&utm_source=github_status

All tests in https://github.com/phylogeny-explorer/explorer repo fail and all of them pass locally.

### Versions
4.0.2

**Comment by jennifer-shehane** [comment]
My best debugging tip is to get a screenshot/video of the Command Log while running in CI on the failed test and compare this to a screenshot/video of the Command Log while running locally - anywhere you see that it does not match exactly, look into that.

Unfortunately, we do not have the dedicated time to dive into your entire application and CI run to debug why this is failing. If you can narrow the issue down to a single repo with a single failing test we can run in each, we can try to take a look.
