### ISSUE TITLE
render colored compilation error message in interactive mode

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#6533]
currently we try to strip-ansi from the `file:preprocessor` compilation error. In some cases it doesn't get stripped and results in this:
![image](https://user-images.githubusercontent.com/14625260/75070602-94cb6380-54c1-11ea-84b1-72b9854d879d.png)

we should instead parse those ansi characters and render a colored message

This will give a better experience around viewing syntax errors while watching a spec file.

**Comment by bahmutov** [comment]
Term-to-html now supports string to html string output, you can run it through it and render as DOM node

**Comment by Bkucera** [comment]
@bahmutov what about your beloved `ansi-to-html` ?

**Comment by bahmutov** [comment]
Sure! That works
