### ISSUE TITLE
GUI input for environment

### ISSUE THREAD

**Issue by shcallaway** [cypress-io/cypress#654]
### Current behavior:

I have to spawn a process using Node and pass options as a command string.

### Desired behavior:

I want to be able to do `cypress.open()` with a config/env object, like I can with `cypress.run()`.

---

## Update

*I'm updating this issue to reflect my conversation with @brian-mann in the comments section.*

### Current behavior:

I have to restart the GUI every time I want to change the environment.

### Desired behavior:

I want an input for the environment within the GUI so I can modify environment variables without exiting and restarting.

**Comment by bahmutov** [comment]
What would be the use case @shcallaway ? The spawned process would have its GUI, and you cannot really control it.

**Comment by shcallaway** [comment]
I have a gulp task that runs my cypress tests and then does some reporting with the failures. I want to do `cypress.open` instead of `cypress.run` using the same gulp task so that I can watch the GUI while developing tests. The existing `cypress open` allows met o launch the GUI from the command line but I can't do anything before/after running Cypress.

**Comment by brian-mann** [comment]
Oh you cannot automate `cypress open`. It's strictly for interactive GUI development. In other words, the process will never exit until you manually close it. It's for when you're writing your tests.

`cypress run` will go through and run to completion and exit the process. The default mode for `cypress run` is to run headlessly but you can pass a `--browser` option to run a headed browser (such as chrome).

You probably want to set this up in CI though as opposed to running it on your computer. Eventually your tests will take too long.

**Comment by shcallaway** [comment]
Ok, this may not be the feature I need. 

My issue is: I'm trying to set up a way for developers to toggle fixtures on and off while using the GUI. Like, I want to use the GUI while I'm developing tests, but I don't want to have to change an environment variable in `cypress.json` to enable/disable stubbing.

**Comment by brian-mann** [comment]
I'm not sure toggling fixtures on or off really changes anything in `cypress.json` for your tests. In other words, if you use fixtures in your test code as `cy.fixture` or `cy.route` it will use those regardless.

You should probably just conditionally use those commands in your spec code...

```js
if (Cypress.env("FIXTURES") {
  cy.route(...)
}
```

You could also overwrite `cy.route` or `cy.fixture` too... not sure if this is what you're talking about.

**Comment by brian-mann** [comment]
you could probably wrap this into a utility function which based on an env var removes route response stubbing

**Comment by shcallaway** [comment]
That's exactly what I am doing right now actually.

**Comment by shcallaway** [comment]
But I want to be able to set `Cypress.env("FIXTURES")` without modifying the config every time.

**Comment by shcallaway** [comment]
I can do that no problem with `cypress.run()`, but there's no method for doing so from the GUI.

**Comment by brian-mann** [comment]
you can modify the env from within the spec files themselves. it's just javascript. you don't have to restart cypress.

```js
Cypress.env("FIXTURES", "1") // now its set
```

**Comment by shcallaway** [comment]
Yeah I think you are misunderstanding me. Let's say I have a  like this:
```
it('login', () => {

  if (!Cypress.env('stubs')) {
    cy.server();
    cy.route('POST', '/login', 'fx:sessions.json');
  }

  cy.visit('/');
  cy.contains('Log In').click();
  cy.get('input[placeholder="Email Address"]').type('fake@email.com);
  cy.get('input[placeholder="Password"]').type('secret);
  cy.get('button').contains('Log In').click();

  cy.contains('Log In').should('not.exist');
})
```
I want to be able to run this with and without stubs, using the GUI, without modifying the config file. If I had a way of overriding environment vars from the GUI, I could set `stubs`.

**Comment by brian-mann** [comment]
`cypress open --env stubs=0`

**Comment by shcallaway** [comment]
But that permanently sets the environment. To turn off stubbing, I have to manually exit the process and re-run `cypress open` without the `--env` flag. So I'm not getting to take advantage of the wonderful app you guys have put together. It would be much nicer if I could, within the GUI, set and unset `env.stubs`.

**Comment by brian-mann** [comment]
Right so the goal here is to:

- conditionally set or unset stubbing
- in the gui
- without restarting the gui

If that's the case then you'll have to control this with a line of code - and you can do just that.

In your support file like `index.js`

```js
// comment this line out to let the --env option apply
// else override the env now
Cypress.env("stubs", false)

```

**Comment by shcallaway** [comment]
Hmm that's no better than changing the `env.stubs` line `cypress.json`. 😕

**Comment by brian-mann** [comment]
But you can do flip it on and off in your code without restarting Cypress or the process. Because we watch `support/index.js` the tests will actually instantly reload once you make that single line change.

Not seeing any other solution here if you want to **conditionally** turn stubs on and off like this. If you can't start Cypress in a mode without wanting to change it, I'm not seeing how else you could do this.

Is there a way you can describe what you're wanting as if the feature already existed?

**Comment by shcallaway** [comment]
You seem to understand the problem well enough. It's true that since Cypress watches the support files I can comment/uncomment that line to enable/disable stubbing.

I think I am just not excited about developers modifying a file that's checked into source control. I can see devs commenting out `Cypress.env("stubs", false)` while debugging their tests, and accidentally committing that lone along with their work. I would rather give developers the ability to override the default environment from the GUI.

**Comment by brian-mann** [comment]
I see.

So an `input` for modifying the env vars from the GUI itself. We talked about that at one point but never bothered to build it in. Never could find a good use case.

**Comment by shcallaway** [comment]
Yep. That's exactly what I'm hoping for. I think the GUI you guys have built is really freaking powerful, and I absolutely want to my teammates using it when they write their tests, as opposed to the command-line.

**Comment by shcallaway** [comment]
I'll update this issue to reflect our conversation.

**Comment by jennifer-shehane** [comment]
Our team has decided that adding this feature is not currently within our scope of feature work. This should be possible with current workarounds.

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
