### ISSUE TITLE
Cypress exited with signal SIGSERV

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress#6543]
### Current behavior:

I kept `npx cypress open` opened over the weekend unintentionally.  When I came back this morning, the Cypress has already exited with the following messages on the command line:

```
<--- Last few GCs --->

[10170:0x115875e7d000] 214483958 ms: Mark-sweep 2043.2 (2053.3) -> 2043.1 (2053.3) MB, 1394.6 / 1.4 ms  (average mu = 0.406, current mu = 0.203) last resort GC in old space requested
[10170:0x115875e7d000] 214485578 ms: Mark-sweep 2043.1 (2053.3) -> 2043.1 (2053.3) MB, 1620.7 / 1.4 ms  (average mu = 0.244, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x55d60c8bb7b9]
Security context: 0x026b67be0dd1 <JSObject>
    1: /* anonymous */ [0x3d7145273d29] [/home/cso/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/lodash/lodash.js:~12638] [pc=0xcea70338433](this=0x3efb2f1c0259 <JSGlobal Object>,0x00449a8a2f61 <Object map = 0x3a91d5f00439>,0x12566cafb599 <Object map = 0x1e44f299f79>)
    2: arguments adaptor frame: 4->2
    3: /* anonymous */ [0x3d...

[10170:0223/173505.544460:ERROR:electron_bindings.cc(41)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu Linux - 16.04)
Cypress Version: 4.0.2
```

Not sure if the following is related: The web application on my test server had a scheduled down time over the weekend. 

I've searched for existing tickets.  There are tickets that look similar to the error message above but they have been closed.  If it's a lodash bug please feel free to close this bug.

### Desired behavior:

The Cypress UI and test runner should not crash even if no test is running.

### Test code to reproduce

```
npx cypress open
```

### Versions

Cypress 4.0.2
Ubuntu 16.04 LTS
Chrome 80

**Comment by estefafdez** [comment]
The same problem that I had here: https://github.com/cypress-io/cypress/issues/6458#issuecomment-590831658

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
