### ISSUE TITLE
ProjectId passed via --config flag pulls to configuration settings in Test Runner but is not used for --record

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress#6546]
### Current behavior:

When running `cypress open --config projectId=<PROJECT ID>`, the passed project Id is pulled in and displayed in the Project Settings in the Test Runner, overwriting the value in the configuration file.

<img width="839" alt="Screen Shot 2020-02-24 at 2 09 49 PM" src="https://user-images.githubusercontent.com/60482585/75183868-6217aa00-5711-11ea-8d47-93fd6436d739.png">

However, when running `cypress run --record --config projectId=<PROJECT ID> --key <KEY>`, the passed projectId in the configuration file is NOT overwritten, and the test does not run due to incorrect key.

<img width="957" alt="Screen Shot 2020-02-24 at 2 03 17 PM" src="https://user-images.githubusercontent.com/60482585/75184324-35b05d80-5712-11ea-8459-e46ba0a5cc39.png">

### Desired behavior:

ProjectId is not a documented option to the `--config/-c` flag, but behavior should be consistent on whether it is accepted or not.

### Test code to reproduce

Run `cypress open --config projectId=<OTHER PROJECT ID>` with any value other than what is in the configuration file. The passed value will appear in the Test Runner settings under Project Id.

To recreate the recording issue, run `cypress run --record --config projectId=<OTHER PROJECT ID> key <KEY FOR OTHER PROJECT ID>` and an error will output that <KEY FOR OTHER PROJECT ID> does not match with the project Id in the configuration file.

### Versions

4.0.2
macOS 10.15.3

**Comment by jennifer-shehane** [comment]
## Current Workaround

Just wanted to note that the current workaround for this is to pass a different `--config-file` containing the `projectId` you want to pass for recording.

**Comment by kevinold** [comment]
`CYPRESS_PROJECT_ID=new-project-id` can be used to override the `projectId`

**Comment by agoldis** [comment]
@evereq
