### ISSUE TITLE
Multiple (potentially related) bugs: 1) `cy.contains().click()` does not play well with regular expressions, 2) `cy.click()` can cause weird jumps in specific scenarios.

### ISSUE THREAD

**Issue by thisissami** [cypress-io/cypress#6548]
### Current behavior:

Using components from `Ant Design`, I have a `Select` within a `Form` within a `Modal`. `Select`s in `Ant Design` are a bit weird, in that the library generates a `div` that's positioned absolutely that is placed immediately below the `Select`. It does not use `select` from `html`.

I am running UX tests where I open the `Modal` + `Form`, and then try to select a specific option from the `Select` using the following code:

```typescript
cy.findByLabelText(label) // this is from @testing-library/cypress
  .click();

cy.get('.ant-select-dropdown')
  // using a Regular Expression to ensure we find an exact match
  .contains(new RegExp(option, 'g'))
  .click();
```

For some reason, using a regular expression can cause `cy.click()` to click on the wrong location. It's inconsistent - most often, it selects the wrong option, but sometimes it gets the right one. Bizarre! 

Using `cy.contains(option)` instead of `cy.contains(new RegExp(option, 'g'))` works without issue, and the click is always centered exactly where it should be.

Additionally, if the main `div` (as in the background that isn't the `Modal`) has a height that is greater than the size of the screen (and accordingly is scrollable), `cy.click()` causes a jump in the `y position` of said main `div`, which causes the absolutely positioned `Select` to jump as well, and potentially causes the `click()` to misfire further. When the the background is scrollable, the rate of "misclicks" increases hugely (to almost 100% for me), so it does seem to have some kind of effect (beyond visual). Again, without a `RegExp`, this is not an issue.

### Desired behavior:

Using a regular expression within `cy.contains()` should work flawlessly. It should behave identically to passing in an equivalent string. I am using regular expressions to ensure that the match within `cy.contains()` is exact (so that if I have a `<span>One</span>` and a `<span>One One</span>`, I can ensure that it finds the `span` with `One` if that is what I'm specifically looking for).

Additionally, when there is a large background, I expect `cy.click()` not to cause huge jumps - as that no longer mimics the user experience that would be had if we just clicked using a mouse not controlled by `cypress`.

### Test code to reproduce

https://github.com/thisissami/cypress-test-tiny

A few notes about this test repo:

1) in `cypress/integration/spec.js`, you can toggle lines 6 & 7 to switch from using normal variables or regular expressions that require exact matches. I've placed `cy.wait(2000)` before and after the `cy.click()` so that it's easier to visually see what happens in with the second (background) related bug.
2) In `src/App.jsx`, you can comment out lines 19-24 in order to reduce the length of the background (to test the 2nd bug).

### Versions

cypress v4.0.2
browser - the default `chrome` used by that version of `cypress`
OS - linux / Pop OS 18.04 (basically identical to Ubuntu 18.04)

**Comment by jennifer-shehane** [comment]
Thanks so much for providing a reproducible example. I can reproduce this difference in behavior between `cy.contains()` with and without RegExp matching. 

I evaluated this in previous versions of Cypress and did *not* find this to be a regression. This has always been the behavior. I also checked this against `develop` pre-release to ensure this behavior did not change from changes in https://github.com/cypress-io/cypress/pull/6434

<img width="1202" alt="Screen Shot 2020-02-25 at 3 17 33 PM" src="https://user-images.githubusercontent.com/1271364/75230415-f94c3280-57e1-11ea-94c8-1d1bf775c528.png">


### `cy.contains(text)`

In the case of `cy.contains('One')`, Cypress is matching the specific `<li>` in the dropdown, hence matching the element you wish to click on.

You can evaluate this information by putting a debugger after the contains to inspect the $el. 

```js
cy.get('.ant-select-dropdown')
  .contains('One').then(($el) => {
    debugger
  })
```

<img width="341" alt="Screen Shot 2020-02-25 at 2 52 23 PM" src="https://user-images.githubusercontent.com/1271364/75228663-ceacaa80-57de-11ea-9b19-719fc9b04e05.png">


### `cy.contains(regexp)`

In the case of `cy.contains(new RegExp('One', 'g')`, Cypress is matching the specific `<ul>` of the dropdown - clicking in the middle which happens to be the 2nd dropdown of 'Two'. 

```js
cy.get('.ant-select-dropdown')
  .contains(new RegExp('One', 'g')).then(($el) => {
    debugger
  })
```

<img width="341" alt="Screen Shot 2020-02-25 at 2 51 41 PM" src="https://user-images.githubusercontent.com/1271364/75228679-d79d7c00-57de-11ea-9b05-f85f5193a502.png">

Why is this happening? I don't know.

**Comment by thisissami** [comment]
@jennifer-shehane you're welcome! I spent a few hours yesterday distilling the giant codebase I'm working on into a small reproducible example, and in the process was able to debug further and figure out with greater certainty what the issue was. :) (I didn't realize the regular expression had anything to do with it until I finished putting together the repo that I shared)

Also... that explains why it clicks exactly on the middle between the two options, which also explains why *sometimes* it does hit the right option. Fingers crossed this is something that's easy for the `cypress` team to address, as we have some `Select` options with very similar texts - and need the regular expression to be able to choose the right one.

**Comment by thisissami** [comment]
Also, I'm happy you shared what you did above - that `debugger` would have been real useful while I was trying to figure this out. I'm glad to know that's a tool available within `cypress` now.

**Comment by thisissami** [comment]
Hi @jennifer-shehane - do you have any sense of how long this is likely to take to address?

**Comment by ahmead23yaser23** [comment]
مالعمل وكيف يمكن اصلاح المشاكل الظاهرة وطريقه الاصلاح

**Comment by buddyp450** [comment]
Running into this issue myself as a recent cypress adopter. Looking for PRs?

**Comment by thisissami** [comment]
My team and I would really love for this to be solved, as we've had to change parts of both our actual codebase and our tests to get around this issue. Regular expressions are a core JavaScript tool, and it's a real shame that we can't use them to have the most effective tests possible.

**Comment by buddyp450** [comment]
@thisissami if it's any consolation I determined this to be an issue with my css where the overflow property wasn't set correctly and I refactored my styling to no longer need it - I'll have to take a look at your tiny repo when I get a sec to see if it's a similar problem.

**Comment by thisissami** [comment]
if memory serves me correctly, there isn't any CSS in the tiny rep that I
submitted.

--
Sami Majadla
CEO, CTO // CertiCraft.com
