### ISSUE TITLE
window.Cypress is undefined when running with Cucumber preprocessor.

### ISSUE THREAD

**Issue by Gurubg1** [cypress-io/cypress#6551]
### Current behavior:

I have written 5 BDD tests using cucumber plugin and cypress. When running tests using 'Cypress run' command, `window.Cypress` is `undefined` after first successful test. 

However, all tests pass when run individually using 'Cypress open'
Here is the code to check Cypress object, 
```js
cy.window().its('Cypress').should('be.an', 'object') 
```

### Desired behavior:

`window,Cypress` should not be undefined after first test.

### Test code to reproduce
```js
cy.visit('http://localhost:8081').then(currentWindow => {
  cy.window().its('Cypress').should('be.an', 'object')
  cy.HandleEvents(currentWindow.parent)
  handleRouteEvent(currentWindow.parent)
})
```

### Versions
Cypress version: 4.0.1
Windows OS

**Comment by jennifer-shehane** [comment]
I was not able to recreate the issue as described. Please provide the full set of tests required to reproduce this issue (including where you are running these commands - in a `before` `beforeEach`, `it` for example). Providing a repo is ideal.

I also tried this test across 2 spec files - it still passes in both during `cypress run`. 

`spec.js` with locally running server

```js
it('window is defined', () => {
  cy.visit('http://localhost:2222').then(() => {
    cy.window().its('Cypress').should('be.an', 'object')
  })
})
```

<img width="503" alt="Screen Shot 2020-02-26 at 3 43 12 PM" src="https://user-images.githubusercontent.com/1271364/75330058-1569d580-58af-11ea-86b3-359f5fd07926.png">
<img width="835" alt="Screen Shot 2020-02-26 at 3 43 47 PM" src="https://user-images.githubusercontent.com/1271364/75330062-18fd5c80-58af-11ea-9cee-998e445b8e2c.png">
