### ISSUE TITLE
Installing Cypress Fails On 4.0.2 But Works Fine On 3.8.0

### ISSUE THREAD

**Issue by lots0logs** [cypress-io/cypress#6554]
### Current behavior:

Installation fails due to an error that occurs during the Cypress binary download. It started happening with 4.0.2. It works fine on 3.8.0. The issue only affects Mac users AFAICT.

<img width="877" alt="Screen Shot 2020-02-24 at 4 49 46 PM" src="https://user-images.githubusercontent.com/4675662/75276095-23dec100-57cb-11ea-90aa-d600b30be309.png">

### Desired behavior:

Install should complete without errors.

### Test code to reproduce

N/A

### Versions

4.0.2, Mac OSX

**Comment by CypressCecelia** [comment]
@lots0logs  How are you installing?

**Comment by lots0logs** [comment]
We're using Yarn and this issue happens when you delete node_modules and run `yarn install` (or run it for the first time in a new copy of the repo)

**Comment by CypressCecelia** [comment]
@lots0logs Are you getting the same issue when running `yarn add cypress`? Or is it only on `yarn install`? Also, can you confirm the version of Cypress in your `package.json` file?

Thanks!

**Comment by lots0logs** [comment]
After troubleshooting this further with my boss it does not appear that the issue is with Cypress. Sorry for the false alarm!
