### ISSUE TITLE
snapshot dispalys <iframe> place holder

### ISSUE THREAD

**Issue by shazaddad** [cypress-io/cypress#6565]
### Current behavior:
The main screen which is in an iframe, displays <iframe> place holder for , after the test has complete preventing traversing through test history.

![image](https://user-images.githubusercontent.com/36929002/75363530-2c5df700-58b2-11ea-92f0-02117e07c778.png)

### Desired behavior:
to show traversal - DOM snapshot before and after

### Test code to reproduce
i have used cypress-frame plugin to work with iframes, but cannot get DOM Snapshot of the area in the Iframe.

**Comment by CypressCecelia** [comment]
This is an existing issue [#1433](https://github.com/cypress-io/cypress/issues/1433) closing as duplicate.
