### ISSUE TITLE
http request with port 443 fail

### ISSUE THREAD

**Issue by luogan210** [cypress-io/cypress#6572]
### Current behavior
http request  http://xxx.com:443/path  is not ok

### Desired behavior:
http request  http://xxx.com:443/path  is  ok

**Comment by luogan210** [comment]
backend port is 443,but do not use https,so ,i make a request like this http://xxx.com:443/path ,when my page is running on mormal web broswer,there with  corect response,but ,when i run this page on cypress,there is no response ,no response status, but with "Provisional headers are shown"

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

Also @luogan210, I'm not sure I completely understand the initial issue. You seem to have linked the exact same url for the 'not ok' and 'ok'. Can you clarify this as well as provide the other information asked.

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

**Comment by luogan210** [comment]
in my app,i make a request to httt://xxx.com:443/ ,when my app is running in normal broswer, the request  reponse with right response
when my app is running in cypress,the request  reponse with failed

**Comment by jennifer-shehane** [comment]
Please comment in this issue with a reproducible example and we will consider reopening the issue.
