### ISSUE TITLE
Chrome browser not detected in v4.0.2

### ISSUE THREAD

**Issue by emijmker** [cypress-io/cypress#6580]
### Current behavior:
When I install Cypress 4.0.2 it doesn't show Chrome anymore. Chrome is normally installed and works fine with 4.0.1 version and same Chrome version installed. See enclosed screenshots for the difference between the 2 versions.

![afbeelding](https://user-images.githubusercontent.com/35372494/75451440-da2fdb00-5970-11ea-86bc-7236c2f37f61.png)

Already posted on Gitter but no replies. 
Already checked the Migration guide https://docs.cypress.io/guides/references/migration-guide.html#Chromium-based-browser-family#Example-2-Finding-Chromium-based-browsers and have this in my plugins/index.js file but that doesn't fix it:

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      // pass launchOptions to Chromium-based browsers in 4.0
      return launchOptions
    }
  })
}
```

### Desired behavior:
I want to be able to test with Chrome like I can in older versions.

### Test code to reproduce
Not related to test code, therefore not applicable

### Versions
MacOs Mojave 10.14.6
Google Chrome_80.0.3987.122 (but same behavior with Google Chrome_80.0.3987.116)
Cypress 4.0.2

**Comment by jennifer-shehane** [comment]
The code in the `plugins` file should not be necessary. You can remove this code to return it to:

```js
module.exports = (on, config) => {}
```

Have you looked at the [launching browsers](https://on.cypress.io/debugging#Launching-browsers) troubleshooting guide?

My other suggestion is to do what I have shown below, since you're on Mac (hopefully this works in your terminal). 

![](http://g.recordit.co/4EFP24BTc2.gif)


1. Does this work and launch the browser
2. Share the path printed in the console for you here.

**Comment by emijmker** [comment]
@jennifer-shehane Tnx for your quick reply. Instructions video worked, it launched in Chrome. 

Do you mean this?
$ cypress run --browser /Applications/Google\ Chrome_80.0.3987.122.app/Contents/MacOS/Google\ Chrome
It looks like this is your first time using Cypress: 4.0.2
✔  Verified Cypress! /Users/username/Library/Caches/Cypress/4.0.2/Cypress.app

**Comment by jennifer-shehane** [comment]
Yeah, there may be something about the `Chrome_80.0.3987.122.app` portion of the browser path that we're not detecting properly.

**Comment by emijmker** [comment]
To give you some background: I always add the version number to Chrome and don't auto update so I'm in full control of which cypress and which chrome run together, both locally and in pipeline. Otherwise debugging is impossible since both a different Chrome or a different Cypress version can give different results (aka might not work). Never had any problems with it before so would be nice if this could continue to work.

**Comment by jennifer-shehane** [comment]
Yeah, I don't see any changes in the code that I think would have effected this in 4.0.2 release. When you redownload 4.0.1 and `cypress open` it detects the same `Chrome_80.0.3987.122.app` that is not deteced in 4.0.2?

**Comment by emijmker** [comment]
Yups. 

$ cypress run --browser /Applications/Google\ Chrome_80.0.3987.122.app/Contents/MacOS/Google\ Chrome
  (Run Starting)
Cypress:    4.0.1
Browser:    Custom Chrome 80

![afbeelding](https://user-images.githubusercontent.com/35372494/75525752-b2904f80-5a10-11ea-81e7-1bb1c26ef9fa.png)


4.0.1 works without problems that's why I'm currently using that version.

**Comment by Saibamen** [comment]
Could you retest with Cypress 4.1.0?

**Comment by emijmker** [comment]
Same result, why would you expect anything different in an older version?

**Comment by jennifer-shehane** [comment]
@emijmker 4.1.0 is newer than 4.0.2

**Comment by emijmker** [comment]
Haha my bad, i read it as 4.0.1. Will be able to test later today

**Comment by emijmker** [comment]
Nope still the same: 
<img width="617" alt="afbeelding" src="https://user-images.githubusercontent.com/35372494/75780161-27d68a00-5d5b-11ea-944c-c6e7c9480de1.png">

**Comment by jennifer-shehane** [comment]
Can you run `cypress info` from 4.1.0 and provide that information here? This new command was added in the hopes of helping us detect situations like this. 

But, essentially the only workaround in the current version is the one I gave above - that or renaming the `App` to a name that we auto-detect.

**Comment by emijmker** [comment]
![afbeelding](https://user-images.githubusercontent.com/35372494/75965889-c08b1800-5ec9-11ea-82ab-aaa073b9a24e.png)

Can confirm that this is causing the problems
<img width="426" alt="afbeelding" src="https://user-images.githubusercontent.com/35372494/75965985-e6b0b800-5ec9-11ea-8222-1b2a2b99432b.png">
If I rename back to Google Chrome.app, then 4.0.2 and 4.1.0 display Chrome in the runner. Also then cypress info displays this:
![afbeelding](https://user-images.githubusercontent.com/35372494/75966499-c1707980-5eca-11ea-9c4d-b61595ec47de.png)

Still weird that I've been doing since the 2 years I've been using Cypress and only now causes problems, but according to you there hasn't been any change in the code that could cause this...

**Comment by emijmker** [comment]
@jennifer-shehane i'd say close it, I'm sure there are more important issues to address. As workaround I'll just add an FYI doc in the Applications folder so I can easily see which version I'm using and stop renaming the Google Chrome.app
