### ISSUE TITLE
cy.reload in Angular app disconnects webpack

### ISSUE THREAD

**Issue by alastair-todd** [cypress-io/cypress#6598]
Running an ivy-compiled angular 9 app with

`ng serve`

(aot enabled by default there)

when we do a 

`cy.reload()`

We see this in dev tools

> Invalid Host/Origin header 
> [WDS] Disconnected!

`ng serve --live-reload=false`

works around but not ideal or I can use` cy.visit(path)` again

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
