### ISSUE TITLE
Cypress doesn't start when running in RHEL7 docker container

### ISSUE THREAD

**Issue by mpeyper** [cypress-io/cypress#660]
- Operating System: RHEL 7.4
- Cypress Version: 0.20.0
- Browser Version: N/A

### Is this a Feature or Bug?
Bug or maybe just an unsupported OS

### Current behavior:
Cypress fails to start.  It produces the following output:

```
It looks like this is your first time using Cypress: 0.20.0

[16:44:03]  Verifying Cypress can run /data/node_modules/cypress/dist/Cypress [started]
[16:44:05]  Verifying Cypress can run /data/node_modules/cypress/dist/Cypress [failed]
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you using Docker, we provide containers with all required dependencies installed.
----------
----------

Platform: linux (Red Hat Linux - 7.4)
Cypress Version: 0.20.0
```

*NOTE:* despite declaring it would list the missing dependencies, the output does not contain any.

### Desired behavior:
Cypress starts, or gives better output as to what is missing or what went wrong.

### How to reproduce:
Run `cypress run` in a RHEL7 docker image with the following dependencies installed:

```
yum install -y xorg-x11-server-Xvfb GConf2 alsa-lib libXScrnSaver gtk2 nss-devel libnotify-devel
```

#### Test code:

N/A

### Additional Info (images, stack traces, etc)

The dependencies listed in the [CI documentation](https://docs.cypress.io/guides/guides/continuous-integration.html#Dependencies) are for an `apt-get` command, but RHEL uses `yum`.  We attempted to find the relevant dependencies for yum, but it is entirely likely that we got them wrong.  The following shows which dependencies were used as replacements for the `apt-get` versions:

```
xvfb -> xorg-x11-server-Xvfb
ibgconf-2-3 -> GConf2
libasound -> alsa-lib
libxss1 -> libXScrnSaver
libgtk2.0-0 -> gtk2
libnss3 -> nss-devel
libnotify-dev -> libnotify-devel
```

The reason we are trying to run on a RHEL image instead of just using your docker container is that it needs to run in our corporate network and there are lots of certificates and other configurations required, so we were hoping to make it easier for us and use one of our base images and install Cypress on top of that.

**Comment by tormoseng** [comment]
I've made it run on RHEL 7.3. I installed same pacakges as you, except for "yum install nss-3*" instead of "nss-devel". In addition I guess you'll need "yum install gnu-free-sans-fonts*". Don't know if it works for you, but give especially the fonts package a go.

**Comment by mpeyper** [comment]
Thanks @tormoseng, I'll try those and see (will be tomorrow before I have time though).

**Comment by tormoseng** [comment]
Otherwise you might also try the "under hood" xvfb-run command:

$ xvfb-run a -s "-screen 0 1280x1024x24" ./node_modules/cypress/dist/Cypress/Cypress --run-project <project.basedir> --spec <project.basedir><spec.file>

**Comment by brian-mann** [comment]
In older versions of Cypress you needed to do this to see the `stderr` failure output but it should no longer be necessary.

**Comment by mpeyper** [comment]
Thanks to @tormoseng we got cypress running on our RHEL7 docker image.  We had to install the gnu-free-sans-fonts and run the command to `xvfb-run a -s "-screen 0 1280x1024x24" npx cypress run`.

Not sure what you can take away from this issue, but from my perspective, it can be closed now.

**Comment by ajzawawi** [comment]
@jennifer-shehane Do we think we can make an official section in the documentation about RHEL's dependencies? A lot of enterprises use RHEL (financial, government, insurance, etc).

**Comment by jennifer-shehane** [comment]
@ajzawawi Open an new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document the RHEL.. Our documentation is open source and contributions are welcome.
