### ISSUE TITLE
New cypress info command's free memory report doesn't seem correct

### ISSUE THREAD

**Issue by crfrolik** [cypress-io/cypress#6602]
### Current behavior:

```
Cypress Version: 4.1.0
System Platform: darwin (17.7.0)
System Memory: 34.4 GB free 133 MB
```

This doesn't seem right.

<img width="616" alt="Screen Shot 2020-02-28 at 5 49 51 PM" src="https://user-images.githubusercontent.com/60711200/75593284-dd9b9300-5a52-11ea-8d67-2b1d2aa40733.png">

**Comment by bahmutov** [comment]
Can you use node os memory functions to see actual values reported on you machine?

**Comment by crfrolik** [comment]
I just tried using `node-os-utils` to check it, and got this:

```
{"totalMemMb":32768,"usedMemMb":22500.32,"freeMemMb":10267.68,"freeMemPercentage":31.33}
```

**Comment by bahmutov** [comment]
The code for this is in https://github.com/cypress-io/cypress/blob/develop/cli/lib/exec/info.js#L88 which is simply

```
const os = require('os') // Node built-in
const prettyBytes = require('pretty-bytes')
console.log('System Memory: %s free %s', g(prettyBytes(os.totalmem())), g(prettyBytes(os.freemem())))
```

If `os.totalmem()` or `os.freemem()` returns incorrect values, or if they are not formatted correctly, I would love to know why

**Comment by Billy-** [comment]
@bahmutov `os.freemem()` returns wildy incorrect values for me in ubuntu:

![image](https://user-images.githubusercontent.com/4316168/96995731-8ccb3400-1526-11eb-9b8f-1cb0ca899ad4.png)

even the totalmem is a bit off - but that just seems to be diving by 1000<sup>3</sup> rather than 1024<sup>3</sup>
