### ISSUE TITLE
Cypress open does not accept --project flag

### ISSUE THREAD

**Issue by spearmootz** [cypress-io/cypress#661]
- Operating System: MacOs 0.12.6
- Cypress Version: 0.20.1
- Browser Version: electron 53

### Is this a Feature or Bug?
Bug, its in the documentation
the run command works corectly.

### Current behavior:
Opens cypress in root folder

### Desired behavior:
Opens cypress in specified folder

### How to reproduce:
run cypress open
move files created into /tests folder
cypress open --project ./tests

**Comment by brian-mann** [comment]
The code for this is merged, but it has not been released yet.

**Comment by brian-mann** [comment]
Fixed in [`0.20.2`](https://docs.cypress.io/guides/references/changelog.html#0-20-2).
