### ISSUE TITLE
Chromium 79: Unable to detect chromium browser in cypress test runner.

### ISSUE THREAD

**Issue by a-onkar** [cypress-io/cypress#6613]
### Current behavior:

Installed Chromium 79. Browsers installed in the machine: Chrome 80, Chromium 79, Edge (Chromium) & Firefox.
The test runner only all other supported browsers excluding Chromium.

![image](https://user-images.githubusercontent.com/25897622/75699139-db7e4200-5ca7-11ea-8173-79eb1a8845ce.png)

### Desired behavior:

Chromium 79 should be displayed on the list on test runner.

### Test code to reproduce

Install all mentioned browsers and try if you are able to see chromium.

### Versions

Chrome 80
Chromium 79
Cypress 4.1.0
OS: Windows 10 prof x64

**Comment by jennifer-shehane** [comment]
Please look at the [launching browsers](https://on.cypress.io/debugging#Launching-browsers) troubleshooting guide?

My other suggestion is to do what I have shown below, if you're on Mac - you did not indicate your OS/OS version

![](http://g.recordit.co/4EFP24BTc2.gif)


1. Does this work and launch the browser
2. Share the path printed in the console for you here.

**Comment by a-onkar** [comment]
OS version: Windows 10 Professional x64

Based on your suggestion on mac, I made it work on windows using the below steps:

- Found the location of Chromium (It was in Appdata)
- Created a folder named 'chrome-win32' following the path (C:/Program Files (x86)/Google/chrome-win32/) mentioned [here](https://docs.cypress.io/guides/guides/debugging.html#Windows).
- Copied the contents of application folder to C:/Program Files (x86)/Google/chrome-win32/

@jennifer-shehane Please let me know if I have done it correctly? Is it the recommended steps? Maybe I might blog it.

Thanks,
Anand

**Comment by jennifer-shehane** [comment]
@a-onkar Yes, this is one of the ways to workaround it when we can't auto-detect a browser. 

Can I closed this as resolved then?
