### ISSUE TITLE
Typescript: `clearLocalStorage({ log:false })` fails type checking

### ISSUE THREAD

**Issue by celeryclub** [cypress-io/cypress#6615]
### Current behavior:

It seems like the type definitions for `clearLocalStorage` weren't updated with https://github.com/cypress-io/cypress/pull/6495. Calling `clearLocalStorage({ log: false })` within a .ts file fails type checking.

```js
No overload matches this call.
  Overload 1 of 2, '(key?: string | undefined): Chainable<Storage>', gave the following error.
    Argument of type '{ log: boolean; }' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(re: RegExp): Chainable<Storage>', gave the following error.
    Argument of type '{ log: boolean; }' is not assignable to parameter of type 'RegExp'.
      Object literal may only specify known properties, and 'log' does not exist in type 'RegExp'.ts(2769)
```
### Desired behavior:

It would be nice if this didn't throw an error. :)

### Test code to reproduce

Within a .ts file:

`cy.clearLocalStorage({ log: false });`

### Versions

Cypress 4.1.0
Node 12.16.1
macOS 10.15.3

**Comment by jennifer-shehane** [comment]
Yes, it does appear that the typings were not updated as part of that PR.

**Comment by elillesaeter** [comment]
As this is labeled first-timers-only, does this mean i could claim this issue and contribute to this project? I have never really used GitHub for other than private projects, and I am not really familiar with contributing yet.
