### ISSUE TITLE
File already exists Error

### ISSUE THREAD

**Issue by AlpeshMN** [cypress-io/cypress#6617]
### Test code to reproduce: Installed Cypress and run it.
![Annotation 2020-03-02 152448](https://user-images.githubusercontent.com/37811280/75719243-05306c80-5c9a-11ea-99c6-33254462b925.png)

**Comment by CypressCecelia** [comment]
This appears to be a duplicate of #1099. Can you confirm the OS you are using?

**Comment by AlpeshMN** [comment]
I am currently using windows 10 Enterprise.

**Comment by AlpeshMN** [comment]
Ohk, now it worked for me after adding below script in package.json.
  "scripts": {
    "test": "cypress open"
  },
