### ISSUE TITLE
Rerunning spec in open mode hangs with after hook

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#6619]
In open mode, if you click the stop/restart button or update your spec code, sometimes the rerun test run will hang on the first test and show all tests as queued:

![image](https://user-images.githubusercontent.com/14625260/75724789-1cc52080-5cad-11ea-8bf4-2ed48489b18b.png)

this happens if you have an after hook, which ends up causing an uncaught exception in the console (only with debug logs enabled: `localStorage.debug = 'cypress:*'`)

```js
 listeners - with args: Uncaught Error: runnable must have an id
```
![20-03-03_10:39::24](https://user-images.githubusercontent.com/14625260/75792112-7ecc6700-5d3b-11ea-8ee3-f378653b8e82.png)

**Comment by shwarcu** [comment]
I am also having this issue. It happens after I save my spec file or other files multiple times. At stop point the runner hangs and tests are not executed but the timer keeps counting.

**Comment by chrisbreiding** [comment]
@Bkucera Could you include the exception that appears in the description of this issue? I think it would be useful for posterity's sake, so if a user encounters this on an older version once this is fixed, it will be easier to reference this issue.

**Comment by Bkucera** [comment]
@chrisbreiding updated, it's not uncaught, but is logged when debug is enabled
