### ISSUE TITLE
KeyboardEvent triggered by type is not complete

### ISSUE THREAD

**Issue by pawelgalazka** [cypress-io/cypress#662]
- Cypress Version: 0.20.0

### Is this a Feature or Bug?

feature

### Current behavior:

It seems that `KeyboardEvent` generated by `type`, for example `cy.get('body').type('{arrowright}')` has mainly `which` property which represents the key code.

<img width="1260" alt="screen shot 2017-09-19 at 10 45 40 am" src="https://user-images.githubusercontent.com/829242/30570934-b73a2f54-9d27-11e7-99f3-52279e037e6c.png">

### Desired behavior:

`KeyboardEvent` generated by `type` should also have other `KeyboardEvent` properties, like `key` or `code`, so if app checks `KeyboardEvent.key`, `type` should also work for that app.

Especially that `which` attribute is deprecated.

Ref: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

Expected attributes of `KeyboardEvent`:

<img width="842" alt="screen shot 2017-09-19 at 10 50 03 am" src="https://user-images.githubusercontent.com/829242/30571037-5d4539de-9d28-11e7-9d1b-8798afe50504.png">

**Comment by brian-mann** [comment]
We added key support in 0.20.1 that was released yesterday.

**Comment by pawelgalazka** [comment]
HA! :) Alright then, will check this out

**Comment by jennifer-shehane** [comment]
Although `key` support has been added, the console.log when clicking on `.type()` doesn't seem to print any information about a `key` property that I can see. Could we have the newly added properties print to the console.log?

**Comment by pawelgalazka** [comment]
Can confirm, `key` property can be found in `0.20.1`

**Comment by brian-mann** [comment]
@jennifer-shehane open a separate issue for adding it to the console.
