### ISSUE TITLE
Unable to connect multiple DB

### ISSUE THREAD

**Issue by kavitha24** [cypress-io/cypress#6621]
### Current behavior:

I have tests to execute SQL queries to two DB under same server
Select * from customers - execute in DB Customers
Select * from roles - execute in DB identity.

I have used Cypresses-Sql-Server  which is given here https://www.npmjs.com/package/cypress-sql-server

created two DB configuration, but it always ended with executing query in database identity. Fails all the test cases which are in database  Customers.

Is there a way to connect and work with Multiple DB.

### Test code to reproduce

plugins\index.js

    database = require('./database');
    databaseIdentity = require('./identityDatabase')
const sqlServer = require('cypress-sql-server');
const sqlIdentityServer = require('cypress-sql-server')

module.exports = (on, config) => {
var dbconfig = database(on, config);
    sqlTask = sqlServer.loadDBPlugin(dbconfig);
    on('task', sqlTask);
  

var dbconfig1 = databaseIdentity(on, config);
    tasks = sqlServer.loadDBPlugin(dbconfig1);
    on('task', tasks);
 
   
};

support - index.js:

import sqlServer from 'cypress-sql-server';
Cypress.Commands.add(sqlServer, sqlServer.loadDBCommands())

Plugins\database.js

var dbconfig = {
            server: "ddddddddddd",
            port:yourport,
            userName: "dfdsfdsf",
            password: "xxxxxxxxxx",
            options: {
                database: Customers,
                encrypt: true,
                rowCollectionOnRequestCompletion : true
            }
       };
       return dbconfig;

Plugins\identityDatabase.js (deleted original values)
var dbconfig = {
            server: "dddddddddd",
            port: yourPort,
            userName: "dddddddddddd",
            password: "xxxxxxxxx",
            options: {
                database: Orders,
                encrypt: true,
                rowCollectionOnRequestCompletion : true
            }
       };
       return dbconfig;

TestCase:
cy.task('sql.server:execute':'select * from Customers').then(output=>
{

})

Failing with error Customers not found.

### Versions
Cypress - 4.1.0

**Comment by CypressCecelia** [comment]
Hey @kavitha24,

This is not a plugin that we support. However, I do not see an example for multiple databases in the documentation link you provided. You would need to use whatever support channels are available for this package specifically.

Also, when submitting an issue, please provide a reproducible example. Because this is not a plugin we support and there is not a reproducible example, we are not able to action this issue at this time.

I would recommend reaching out via our [Gitter chat](https://gitter.im/cypress-io/cypress), as someone else may have experience working with this package.

Thank you!

**Comment by djpasch** [comment]
I have a solution for you. 
cypress-sql-server is using Tedious. So you could use Tedious directly. The following code is based on cypress-sql-server

Install Tedious

**package.json:**
```
  "dependencies": {
    "coffeescript": "^2.5.1",
    "tedious": "^8.3.0"
  },
```

**plugins/index.js**
```
module.exports = (on, config) => {

    on('task', {
      sqlServerDB1: sql => {
        return execSQL(sql, config.env.db1)
      },
    }),

    on('task', {
      sqlServerDB2: sql => {
        return execSQL(sql, config.env.db2)
      },
    }),

  config = ntlmAuth.initNtlmAuth(config)
  return config
}

const tedious = require('tedious')
function execSQL(sql, config) {
  const connection = new tedious.Connection(config);
  return new Promise((res, rej) => {
    connection.on('connect', err => {
      if (err) {
        rej(err);
      }

      const request = new tedious.Request(sql, function (err, rowCount, rows) {
        return err ? rej(err) : res(rows);
      });

      connection.execSql(request);
    });
  })
}
```

**support/command.js**
```
Cypress.Commands.add('sqlServerDB1', (query) => {
    if (!query) {
        throw new Error('Query must be set');
    }

    cy.task('sqlServerDB1', query).then(response => {
        let result = [];

        const flatten = r => Array.isArray(r) && r.length === 1 ? flatten(r[0]) : r;

        if (response) {
            for (let i in response) {
                result[i] = [];
                for (let c in response[i]) {
                    result[i][c] = response[i][c].value;
                }
            }
            result = flatten(result);
        } else {
            result = response;
        }

        return result;
    });
});

Cypress.Commands.add('sqlServerDB2', (query) => {
    if (!query) {
        throw new Error('Query must be set');
    }

    cy.task('sqlServerDB2', query).then(response => {
        let result = [];

        const flatten = r => Array.isArray(r) && r.length === 1 ? flatten(r[0]) : r;

        if (response) {
            for (let i in response) {
                result[i] = [];
                for (let c in response[i]) {
                    result[i][c] = response[i][c].value;
                }
            }
            result = flatten(result);
        } else {
            result = response;
        }

        return result;
    });
});
```

**cypress.json (config)**
```
  "env": {
    "db1": {
      "server": "server_db1",
      "authentication": {
        "type": "default",
        "options": {
          "userName": "",
          "password": ""
        }
      },
      "options": {
        "port": 50001,
        "database": "db1_name",
        "encrypt": true,
        "rowCollectionOnRequestCompletion": true
      }
    },
    "db2": {
      "server": "server_db2",
      "authentication": {
        "type": "default",
        "options": {
          "userName": "",
          "password": ""
        }
      },
      "options": {
        "port": 50001,
        "database": "db2_name",
        "encrypt": true,
        "rowCollectionOnRequestCompletion": true
      }
    }
  }
```

Application code could then use:
```
    cy.sqlServerDB1("select db_name()").then(result => cy.log(result))
    cy.sqlServerDB2("select db_name()").then(result => cy.log(result))
```

**Comment by vsix27** [comment]
works perfect!

**Comment by isabellemr** [comment]
> I have a solution for you.
> cypress-sql-server is using Tedious. So you could use Tedious directly. The following code is based on cypress-sql-server
> 
> Install Tedious
> 
> **package.json:**
> 
> ```json
>   "dependencies": {
>     "coffeescript": "^2.5.1",
>     "tedious": "^8.3.0"
>   },
> ```
> 
> **plugins/index.js**
> 
> ```js
> module.exports = (on, config) => {
> 
>     on('task', {
>       sqlServerDB1: sql => {
>         return execSQL(sql, config.env.db1)
>       },
>     }),
> 
>     on('task', {
>       sqlServerDB2: sql => {
>         return execSQL(sql, config.env.db2)
>       },
>     }),
>   
>   return config
> }
> 
> const tedious = require('tedious')
> function execSQL(sql, config) {
>   const connection = new tedious.Connection(config);
>   return new Promise((res, rej) => {
>     connection.on('connect', err => {
>       if (err) {
>         rej(err);
>       }
> 
>       const request = new tedious.Request(sql, function (err, rowCount, rows) {
>         return err ? rej(err) : res(rows);
>       });
> 
>       connection.execSql(request);
>     });
>   })
> }
> ```
> 
> **support/command.js**
> 
> ```js
> Cypress.Commands.add('sqlServerDB1', (query) => {
>     if (!query) {
>         throw new Error('Query must be set');
>     }
> 
>     cy.task('sqlServerDB1', query).then(response => {
>         let result = [];
> 
>         const flatten = r => Array.isArray(r) && r.length === 1 ? flatten(r[0]) : r;
> 
>         if (response) {
>             for (let i in response) {
>                 result[i] = [];
>                 for (let c in response[i]) {
>                     result[i][c] = response[i][c].value;
>                 }
>             }
>             result = flatten(result);
>         } else {
>             result = response;
>         }
> 
>         return result;
>     });
> });
> 
> Cypress.Commands.add('sqlServerDB2', (query) => {
>     if (!query) {
>         throw new Error('Query must be set');
>     }
> 
>     cy.task('sqlServerDB2', query).then(response => {
>         let result = [];
> 
>         const flatten = r => Array.isArray(r) && r.length === 1 ? flatten(r[0]) : r;
> 
>         if (response) {
>             for (let i in response) {
>                 result[i] = [];
>                 for (let c in response[i]) {
>                     result[i][c] = response[i][c].value;
>                 }
>             }
>             result = flatten(result);
>         } else {
>             result = response;
>         }
> 
>         return result;
>     });
> });
> ```
> 
> **cypress.json (config)**
> 
> ```json
>   "env": {
>     "db1": {
>       "server": "server_db1_ip_addr",
>       "authentication": {
>         "type": "default",
>         "options": {
>           "userName": "",
>           "password": ""
>         }
>       },
>       "options": {
>         "port": 50001,
>         "database": "db1_name",
>         "encrypt": true,
>         "rowCollectionOnRequestCompletion": true
>       }
>     },
>     "db2": {
>       "server": "server_db2_ip_addr",
>       "authentication": {
>         "type": "default",
>         "options": {
>           "userName": "",
>           "password": ""
>         }
>       },
>       "options": {
>         "port": 50001,
>         "database": "db2_name",
>         "encrypt": true,
>         "rowCollectionOnRequestCompletion": true
>       }
>     }
>   }
> ```
> 
> Application code could then use:
> 
> ```js
>     cy.sqlServerDB1("select db_name()").then(result => cy.log(result))
>     cy.sqlServerDB2("select db_name()").then(result => cy.log(result))
> ```
> 
> Any suggestions for improvement are welcome.



> I have a solution for you.
> cypress-sql-server is using Tedious. So you could use Tedious directly. The following code is based on cypress-sql-server
> 
> Install Tedious
> 
> **package.json:**
> 
> ```json
>   "dependencies": {
>     "coffeescript": "^2.5.1",
>     "tedious": "^8.3.0"
>   },
> ```
> 
> **plugins/index.js**
> 
> ```js
> module.exports = (on, config) => {
> 
>     on('task', {
>       sqlServerDB1: sql => {
>         return execSQL(sql, config.env.db1)
>       },
>     }),
> 
>     on('task', {
>       sqlServerDB2: sql => {
>         return execSQL(sql, config.env.db2)
>       },
>     }),
>   
>   return config
> }
> 
> const tedious = require('tedious')
> function execSQL(sql, config) {
>   const connection = new tedious.Connection(config);
>   return new Promise((res, rej) => {
>     connection.on('connect', err => {
>       if (err) {
>         rej(err);
>       }
> 
>       const request = new tedious.Request(sql, function (err, rowCount, rows) {
>         return err ? rej(err) : res(rows);
>       });
> 
>       connection.execSql(request);
>     });
>   })
> }
> ```
> 
> **support/command.js**
> 
> ```js
> Cypress.Commands.add('sqlServerDB1', (query) => {
>     if (!query) {
>         throw new Error('Query must be set');
>     }
> 
>     cy.task('sqlServerDB1', query).then(response => {
>         let result = [];
> 
>         const flatten = r => Array.isArray(r) && r.length === 1 ? flatten(r[0]) : r;
> 
>         if (response) {
>             for (let i in response) {
>                 result[i] = [];
>                 for (let c in response[i]) {
>                     result[i][c] = response[i][c].value;
>                 }
>             }
>             result = flatten(result);
>         } else {
>             result = response;
>         }
> 
>         return result;
>     });
> });
> 
> Cypress.Commands.add('sqlServerDB2', (query) => {
>     if (!query) {
>         throw new Error('Query must be set');
>     }
> 
>     cy.task('sqlServerDB2', query).then(response => {
>         let result = [];
> 
>         const flatten = r => Array.isArray(r) && r.length === 1 ? flatten(r[0]) : r;
> 
>         if (response) {
>             for (let i in response) {
>                 result[i] = [];
>                 for (let c in response[i]) {
>                     result[i][c] = response[i][c].value;
>                 }
>             }
>             result = flatten(result);
>         } else {
>             result = response;
>         }
> 
>         return result;
>     });
> });
> ```
> 
> **cypress.json (config)**
> 
> ```json
>   "env": {
>     "db1": {
>       "server": "server_db1_ip_addr",
>       "authentication": {
>         "type": "default",
>         "options": {
>           "userName": "",
>           "password": ""
>         }
>       },
>       "options": {
>         "port": 50001,
>         "database": "db1_name",
>         "encrypt": true,
>         "rowCollectionOnRequestCompletion": true
>       }
>     },
>     "db2": {
>       "server": "server_db2_ip_addr",
>       "authentication": {
>         "type": "default",
>         "options": {
>           "userName": "",
>           "password": ""
>         }
>       },
>       "options": {
>         "port": 50001,
>         "database": "db2_name",
>         "encrypt": true,
>         "rowCollectionOnRequestCompletion": true
>       }
>     }
>   }
> ```
> 
> Application code could then use:
> 
> ```js
>     cy.sqlServerDB1("select db_name()").then(result => cy.log(result))
>     cy.sqlServerDB2("select db_name()").then(result => cy.log(result))
> ```
> 
> Any suggestions for improvement are welcome.


Hello, I'm following the step-by- step and I succefully installed Tedious. But, the the configuration of the Index.js didn't work. There's an error related to Typescript (Expression expected.ts 1109) and I can not solve it. Other forums said that the Typescript versions needed to be above 3.7 for the configuration to work, and mine is 4.3.0. But again, it doesn't work. Could you assist me somehow?

https://stackoverflow.com/questions/58820889/expression-expected-ts1109-after-typescript-upgrade-to-3-7-2
https://stackoverflow.com/questions/54611471/typescript-optional-chaining-error-expression-expected-ts1109/58943069#58943069
https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it

**Comment by djpasch** [comment]
> Hello, I'm following the step-by- step and I succefully installed Tedious. But, the the configuration of the Index.js didn't work. There's an error related to Typescript (Expression expected.ts 1109) and I can not solve it. Other forums said that the Typescript versions needed to be above 3.7 for the configuration to work, and mine is 4.3.0. But again, it doesn't work. Could you assist me somehow?
> 
> https://stackoverflow.com/questions/58820889/expression-expected-ts1109-after-typescript-upgrade-to-3-7-2
> https://stackoverflow.com/questions/54611471/typescript-optional-chaining-error-expression-expected-ts1109/58943069#58943069
> https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it

Hi,

Do you mean you have an issue with the plugin/index.js?
If so, please make sure you only have 1 instance of the module.exports.

Kind regards,
Patrick

**Comment by isabellemr** [comment]
![sql](https://user-images.githubusercontent.com/67551942/111522737-53939a80-8739-11eb-8bb6-f200afcb875f.png)

Thank you for assisting me. I was able to fix the error just as you said. But now there is an error with the connection, cy.sqlserverDB1 and cy.sqlseverDB2, not beeing able to connect.

**Comment by djpasch** [comment]
> Thank you for assisting me. I was able to fix the error just as you said. But now there is an error with the connection, cy.sqlserverDB1 and cy.sqlseverDB2, not beeing able to connect.

Hi,
I think there is still something wrongly configured.
Tedious recently also made some changes by adding the options:
        "trustServerCertificate": true,
        "validateBulkLoadParameters": true
Please add those (i also updated my earlier post) and try again. If it fails, please zip your files and post them for analysis.

Good luck,
Patrick

**Comment by isabellemr** [comment]
Hello, I did all the changes that you said and it still doesn't work. I'm going to send you the files as you asked. Thank you very much for your support!

**Comment by djpasch** [comment]
> [CypressArcus.zip](https://github.com/cypress-io/cypress/files/6189085/CypressArcus.zip)
> Hello, I did all the changes that you said and it still doesn't work. I'm going to send you the files as you asked. Thank you very much for your support!

Hi,

Please remove the installation of "cypress-sql-server" as it might have conflicting dependencies.
And i see you still have multiple instances of "module.exports = (on, config) => { }", it's content should be merged. Otherwise calling cy.sqlServerDB1("select db_name()").then(result => cy.log(result)) won't work.

Please let me know if it fixes the issue

**Comment by victorio1** [comment]
@djpasch Thanks you so much!! 

I had the same problem like @isabellemr had with index.js. But the problem was what I used the same version of Tedius for instance before what you write "npm install" you should write this:

"dependencies": {
    "coffeescript": "^2.5.1",
    "tedious": "^8.3.0"
  },

And later when you write "npm install". This will make it install with the same version that @djpasch proposes.

The result in my case was here!

![image](https://user-images.githubusercontent.com/42095275/113780178-7a1f7280-96f4-11eb-8ebc-13c7fe5321d5.png)


Finally. If you use this comand "npm install tedious" don't works because for a weird reason with the last version don't work for me.

This was my result with the last version 

![image](https://user-images.githubusercontent.com/42095275/113781203-eea6e100-96f5-11eb-9905-2c8309e3f697.png)

Hope this is some help to everyone who is frustrated with this.

Regards!

**Comment by estebanaragonc** [comment]
> @djpasch Thanks you so much!!
> 
> I had the same problem like @isabellemr had with index.js. But the problem was what I used the last version of Tedius with the last version not work but if you use the same version 8.3.0 for tedious and 2.5.1 for coffeescript this works. Then before what you write "npm install" you should write this:
> 
> package.json:
> 
> "dependencies": { "coffeescript": "^2.5.1", "tedious": "^8.3.0" },
> 
> And later when you write "npm install". This will make it install with the same version that @djpasch proposes.
> 
> The result in my case was here! This works perfectly well!!!!!!
> 
> ![image](https://user-images.githubusercontent.com/42095275/113780178-7a1f7280-96f4-11eb-8ebc-13c7fe5321d5.png)
> 
> Finally. If you use this comand "npm install tedious" don't works because for a weird reason with the last version don't work for me.
> 
> This was my result with the last version. This not work :(
> 
> ![image](https://user-images.githubusercontent.com/42095275/113781203-eea6e100-96f5-11eb-9905-2c8309e3f697.png)
> 
> Hope this is some help to everyone who is frustrated with this.
> 
> Regards!

that version worked for me, thx

**Comment by bijojoseph99** [comment]
> djpasch

Hi @djpasch,

 I followed your steps and worked perfectly well after having the correct versions of **coffeescript** and **tedious**.
 So it works fine when I run it using the Cypress App, but while running from the console it gives me error. It will be great if you can help me out in it.
 
<img width="1053" alt="DB Connectivity Console Error" src="https://user-images.githubusercontent.com/22940554/162026203-4e75f61d-e0ac-4e87-abbb-4f5864d41524.png">

Thanks

**Comment by bijojoseph99** [comment]
Hi @djpasch,

 Please ignore my message above.
 I got it resolved as the command line run was picking a wrong config.
 
 Thanks

**Comment by djpasch** [comment]
> Hi @djpasch,
> 
> 
> 
>  Please ignore my message above.
> 
>  I got it resolved as the command line run was picking a wrong config.
> 
>  
> 
>  Thanks

Good to hear it's working for you!

**Comment by leolpc21** [comment]
@djpasch Fiz todas as alterações, porém o meu continua dando erro de conexão.
![image](https://user-images.githubusercontent.com/43275999/221872543-1822b9da-d34d-4851-89df-6c720895e862.png)

Poderia me ajudar por gentileza?
Estou usando a versão 12.7.0 do cypress
Subi o meu projeto para o github, segue o link https://github.com/leolpc21/consultaSQLServer

**Comment by bijojoseph99** [comment]
Hi @djpasch,,

 Me again.
 It all worked fine and I was using it from quite a long time without any issues.
 But now for a new project I use Azure so want to use the following for the Authentication:
 **type: 'azure-active-directory-default'**

 Also to use this I came to know we should have the latest Tedious. But having a latest Tedious gives me the following issue:
 **cy.task('sqlServer') timed out after waiting 60000ms.**
 
 Any help on it would be much appreciated.

Thanks

> > Hi @djpasch,
> > Please ignore my message above.
> > I got it resolved as the command line run was picking a wrong config.
> > Thanks
> 
> Good to hear it's working for you!
