### ISSUE TITLE
Describe block is linked to another spec file out of the file it is defined in.

### ISSUE THREAD

**Issue by poojyasankar** [cypress-io/cypress#6623]
### Current behavior:
There are two test spec files, and one test in each. But when the tests in the second test spec is run, the test in first spec file is rerun although defined in a very different describe block. So cypress reports in the end that it found 3 tests, when it should have been only 2.

![image](https://user-images.githubusercontent.com/60782196/75772056-e8586f80-5d53-11ea-895b-f40b753452ab.png)

This is how it looks, although that describe block "Routine prod test" is defined in another file and run separately there also.

![image](https://user-images.githubusercontent.com/60782196/75773317-556d0480-5d56-11ea-86b6-f2568199aa27.png)

It is also reproducible when I run only the second spec file with the command "cypress run -s "cypress/integration/Test2_spec.js"

### Test code to reproduce

I tried to make a reproducible example with the cypress-test-tiny. Unfortunately I am unable to because I can't find what causes this behavior.

### Versions

Cypress 4.1.0 and electron 78. Test is run on command line.

**Comment by jennifer-shehane** [comment]
I cannot reproduce the behavior with the information given. Please provide the test code we can run to reproduce this completely and we will consider reopening.

*My test code*

`spec.js`

```js
describe('describe 1', () => {
  before(() => {
    cy.log('before 1')
  })

  beforeEach(() => {
    cy.log('beforeEach 1')
  })

  it('test 1', () => {
    cy.log('test 1')
  })
})
```

`spec2.js`

```js
describe('describe 2', () => {
  beforeEach(() => {
    cy.log('beforeEach 2')
    // (to mimic failure, leaving this in or out does not cause issue)
    // expect(true).to.be.false 
  })

  it('test 2', () => {
    cy.log('test 2')
  })
})
```

<img width="824" alt="Screen Shot 2020-03-04 at 3 02 52 PM" src="https://user-images.githubusercontent.com/1271364/75860000-7b170e00-5e29-11ea-90b5-662e01ef6dfc.png">

**Comment by poojyasankar** [comment]
I made a reproducible example with my own stuff, try this. https://github.com/poojyasankar/cypress-test-tiny

**Comment by poojyasankar** [comment]
@jennifer-shehane Please reconsider opening this issue.

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this issue from the repo provided. With the repo given, both of the tests fail in the `beforeEach` trying to click `button`, I suspect this is your desired result.

It appears that your output in the STDOUT looks a bit different from mine for each failure. Are you using a different reporter by chance?

<img width="1091" alt="Screen Shot 2020-03-10 at 3 10 24 PM" src="https://user-images.githubusercontent.com/1271364/76294492-54e9e600-62e1-11ea-85b1-d2d4f0365026.png">

<img width="1145" alt="Screen Shot 2020-03-10 at 3 10 35 PM" src="https://user-images.githubusercontent.com/1271364/76294537-67641f80-62e1-11ea-8729-50fab22095ba.png">

Still only 2 tests ran

<img width="846" alt="Screen Shot 2020-03-10 at 3 10 43 PM" src="https://user-images.githubusercontent.com/1271364/76294558-6f23c400-62e1-11ea-8be8-c32369878bc0.png">

**Comment by poojyasankar** [comment]
I just tried again, and it doesn't run like that anymore in the test-tiny. I guess the issue can remain closed then. 
There's definitely something strange going on because at one point it was looping. The Routine Prod Test kept running when the other test block was trying to run and I had to force exit. I can't quite put my finger on it yet. Let me try to find more on why this happens.

**Comment by poojyasankar** [comment]
It seems to happen when I share a variable between the spec files. 
I declared a variable in Test1_spec.js as 
```
export var sessionCookie =""
```
And I use it in Test2_spec.js
```
import {variablename} from "./Test1_spec.js"
cy.setCookie("cookie-name", sessionCookie);
```
This seemed to immediately produce the results of the other describe block also run as a part of Test2_spec.js

**Comment by bahmutov** [comment]
@poojyasankar by importing the variable from one spec file, you automatically executed that spec file (it added its tests!). If you want common variables, just put them into another file like

```
// utils.js
export const variableName = ...

// spec1.js
import {variableName} from './utils'

// spec2.js
import {variableName} from './utils'
```

and to avoid trying to run any tests from `utils.js` itself, either place it in a folder different from `cypresss/integration` (and use relative paths) or add it to `cypress.json` using `ignoreTestFiles` setting https://on.cypress.io/configuration#Folders-Files

**Comment by poojyasankar** [comment]
@bahmutov Yes, that's how I planned to change the use. Thanks for the tip about the "ignoreTestFiles". 
I didn't know that automatic execution with import was expected behavior.
