### ISSUE TITLE
when running my test in firefox get an error of "CypressError: Cypress detected a cross origin error happened on page load:" 

### ISSUE THREAD

**Issue by rahulbasu86** [cypress-io/cypress#6629]
For chromium browsers all test runs as we are setting "chromeWebSecurity" to false. Can anyone suggest how to resolve this issue in Firefox browser.

**Comment by jennifer-shehane** [comment]
Currently if your sites relies on disabling web security, you will not be able to run tests on browsers that do not support `chromeWebSecurity`. 

There are other workarounds mentioned in our [Web Security](https://on.cypress.io/web-security#Common-Workarounds) doc to avoid cross origin errors other than setting `chromeWebSecurity` that we advise looking into.

**Comment by KhizerRehan** [comment]
@jennifer-shehane  @rahulbasu86  any update?

How to surpass this chromeWebSecurity in firefox?  we are using axios for simple API request to upload config that enables our dashboard.

It is working in 1 repo and test case is also running in **firefox** using same axios but the same thing i tried to do in other subrepo it fails to upload config?

Project contains multiple repos.

Any reasons?

- Below code is wrapped in promise.

```js
try {
  axios({
          method : 'PATCH',
          url    : `${SERVER_BASE_URL}`,
          data,
          headers: { 'Content-Type': 'application/yang-patch+json' },
          auth   : {
            username: USERNAME,
            password: PASSWORD
          }
        }).then((response) => {
    if (response.status !== 200) {
      reject();
    } else {
      console.debug(filePath + ' config uploaded');
      esolve();
    }
  });
} catch (error) {
 reject(error);
}

```


![failed-to-run-firefix](https://user-images.githubusercontent.com/17727069/123097793-e7b48280-d449-11eb-9764-552bdd1fdf84.png)
