### ISSUE TITLE
click() with iterator with type is not works

### ISSUE THREAD

**Issue by qkreltms** [cypress-io/cypress#6634]
### Current behavior:

![get](https://user-images.githubusercontent.com/25196026/75832506-af72d600-5df9-11ea-8db7-0c5dd62c0040.png)

It gets all spans and click it to check each span has not style "text-decoration: line-through" 

As you can see the picture above, It gets all spans, but don't clicks each span. Why is it?

### Desired behavior:

I want to get all spans and click it to check whether it has not style"text-decoration: line-through".

### Test code to reproduce
```js
  it("excutes toggle", () => {
    cy.get("[data-testid=todoItem-span]").each<HTMLSpanElement>((span, index) => {
      cy.wrap(span).click().should("not.have.css", "text-decoration: line-through");
    })
  });
```
### Versions

```
"cypress": "^4.0.2"
```

**Comment by qkreltms** [comment]
It was due to each's generic type ```each<HTMLSpanElement>``` .

**Comment by bahmutov** [comment]
What is the actual error though? Is it TypeScript error? Is it not clicking? Is there an error in the DevTools console?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
