### ISSUE TITLE
OSS release - Next.js boilerplate with Jest/Cypress and CI/CD pipeline built-in (monorepo, multi-tenants) 

### ISSUE THREAD

**Issue by Vadorequest** [cypress-io/cypress#6635]
We recently released https://github.com/UnlyEd/next-right-now which is a Next.js boilerplate with built-in Jest/Cypress. We love Cypress and we wanted to spread the love :)

It also features a CI/CD pipeline, that works with multi-tenants (monorepo design, same base code but deploy on multiple projects, hosted on Zeit platform).

It could be quite a good learning resources for developers who'd like to do something similar, or want to use Next.js + Cypress. Should it be referenced somewhere?

**Comment by jennifer-shehane** [comment]
@Vadorequest It's a bit weird how we're showing boilerplates using Cypress in the docs right now, but we've essentially listed them in our Plugins page under Framework Tooling. But, this could change in the future, so I suggest opening a pull request and adding this to the plugins there.  https://on.cypress.io/plugins/#framework-tooling

[Instructions here.](https://github.com/cypress-io/cypress-documentation/blob/develop/CONTRIBUTING.md#adding-plugins)

This repo is only for issues relating to the Cypress product and not documentation. This issue will be closed in this repository.
