### ISSUE TITLE
Cypress execution with Cucumber : Too Slow while running multiple scenarios in a feature file

### ISSUE THREAD

**Issue by mohitsingla1** [cypress-io/cypress#6637]
Cypress got slow on running multiple scenarios in feature file
We have 30 scenarios in single feature and it slows down drastically after 2 scenarios.
Our  avg. script execution time is 4 mins average.
For later scripts,it behaves abnormamlly like not able to click,xpath not found.

Is it slow due to BDD plugin and xpath plugin we used in our framework?
>Is there any option to launch new Browser Instance after every scenario
>Should I split my scenarios 1 scenario per 1 feature file.

I tried with 
1>cypress run headless mode 
2> keeping numtestsmemory field as 1
But no Luck

Looking for suggestions

_

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

Some quick notes here though. 

- What version of [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) are you using? I have seen others mention that updating that dep to 2.0+ improved the performance of running tests. 
- You say "Cypress got slow" - are you implying it used to be fast? What changed, did you update Cypress, change something else?

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
