### ISSUE TITLE
make cy.route onRequest and onResponse async

### ISSUE THREAD

**Issue by spearmootz** [cypress-io/cypress#664]
### Current behavior:
`onRequest` and `onResponse` are synchronous so you cannot test inside them 

its really hard to test some situations, for example.

lets say that you have `call1` and `call2`. with the current scenario you would have to stub and then do the following:

```js
cy.wait('@call1').then(validate);
cy.wait('@call2').then(validate);
```

but if `call1` and `call2` happen close the same time, and `call2` request happens to resolve before `call1`, then the test above would fail since the `cy.wait('@call2');` would not be fulfilled. i guess then you could add a delay, but that would not be performant.

### Desired behavior:
run tests inside, so for example
```js
onResponse: (request) => cy.get('.someElement').should('contain', request.response.body);
```

**Comment by jennifer-shehane** [comment]
cy.route() has been deprecated and no more work will be done for it. Please try migrating to `cy.intercept()` to achieve the above described behavior.
