### ISSUE TITLE
Sub-dependency causing download to fail in enterprise-environments.

### ISSUE THREAD

**Issue by annitya** [cypress-io/cypress#6644]
### Current behavior:

The `server-package` has a dependency `tar-fs` which has a dependency `bl`
which contains a file `test/indexOf` containing the string `arglebargleglopglyf`.
Our firewall then gets a hit on [this signature](https://github.com/wireghoul/htshells/blob/master/dos/apache.dos.htaccess) which causes the download to fail.

The problem is present in `4.1.0`, but absent in `4.0.2`.

### Desired behavior:

Download goes smoothly because there are no "hacking-signatures" in any sub-dependencies 

### Test code to reproduce

Can't help you with this one I'm afraid. Our firewall is apparently super-secret, so I don't know which tool they are using.

### Versions

Cypress, Windows 10 version 4.1.0.

### Related

Posted issue in offending dependency [here](https://github.com/rvagg/bl/issues/79).
[Pull-request](https://github.com/rvagg/bl/pull/80) for said issue.

**Comment by jennifer-shehane** [comment]
Opened PR to pull in `bl` dep update with PR into `tar-stream` which would then need to be released and updated in `tar-fs`. https://github.com/mafintosh/tar-stream/pull/113

**Comment by annitya** [comment]
Opened PR to pull in tar-stream dep update into [tar-fs](https://github.com/mafintosh/tar-fs/pull/90).

**Comment by annitya** [comment]
Semver should take care of things @jennifer-shehane I installed registry-js locally and it correctly pulled in tar-stream@2.1.1 :)

**Comment by jennifer-shehane** [comment]
Closing as resolved.
