### ISSUE TITLE
why  AssertionError: expected [ 2 ] to equal [ 2 ]?

### ISSUE THREAD

**Issue by chobijaeyu** [cypress-io/cypress#6655]
hi 
goods day.
why expected [ 2 ] to equal [ 2 ] is wrong?

### Current behavior:
![スクリーンショット 2020-03-06 9 46 59](https://user-images.githubusercontent.com/25117318/76039424-bcc1c900-5f8f-11ea-874a-826dbea0b57b.png)

AssertionError: expected [ 2 ] to equal [ 2 ]

### Desired behavior:

```
        cy.wait('@users').should(xhr=>{
             expect(xhr.method).to.eq('POST')
            expect(xhr.status).to.eq(201)
            cy.log(JSON.stringify(xhr.requestHeaders))
            cy.log(JSON.stringify(xhr.requestBody))
            expect(xhr.responseBody).to.have.property('id').to.be.a('string')
            expect(xhr.responseBody).to.have.property('shopowner')
            expect(xhr.responseBody).to.have.property('username').to.be.a('string')
            expect(xhr.responseBody).to.have.property('groups').to.be.a('array').to.eq([2])
        })
```

### Versions

Node: 13.8.0
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cdk                      9.0.0-rc.7
@angular/cli                      9.0.1
@angular/material                 9.0.0-rc.7
@ngtools/webpack                  9.0.1
@schematics/angular               8.0.6
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2

"cypress": "^4.0.1",

**Comment by chobijaeyu** [comment]
fixed by use deep.eq

**Comment by michielreyers** [comment]
Question "why" remains ...
