### ISSUE TITLE
Cypress - screenshots

### ISSUE THREAD

**Issue by carlos426** [cypress-io/cypress#6658]
Hi, 

I'm using cypress version 4.0.2 

I'm having trouble configuring screenshot support in cypress. 

In case of an error, the screenshots directory is not created and there is no dump in it.

I took the steps:

a) accordance with https://docs.cypress.io/guides/references/configuration.html#Screenshots I added the `"screenshotsFolder"` parameter to `cypress.json`: `"cypress/screenshots"`, and `"trashAssetsBeforeRuns": true`,

b) according with https://docs.cypress.io/api/cypress-api/screenshot-api.html#Arguments - in `cypress/support` I created the file `index.js` adding in it: 

```js
Cypress.Screenshot.defaults ({    screenshotOnRunFailure: true })
```

I run tests and although 2 of them have an error, the directory and screenshots were not created.

**Comment by jennifer-shehane** [comment]
Cypress only automatically captures screenshots on failure when running `cypress run`. Screenshots on failure will not be taken when running `cypress open`.

All of the other settings you have can be removed since these are the default values for all.
