### ISSUE TITLE
Network requests taking a long time to complete

### ISSUE THREAD

**Issue by steve-tapley** [cypress-io/cypress#6659]
### Current behavior:

For us, network requests are taking an extremely long time to complete.   In our application we're seeing requests become 300+ms when running in cypress compared to 30ms running in chrome.   Some longer requests are 10+ seconds in cypress, compared to 600ms in chrome.

To attempt to to verify this wasn't just our application or server, we tried using your smurf page (https://test-page-speed.cypress.io/index1000.html) outlined in your 3.3 blog post https://www.cypress.io/blog/2019/05/22/how-we-improved-network-speed-by-300-in-cypress-3-3-0

We ran this directly in Chrome, and it took 1578ms.   Running a very basic cypress script like this
```js
it('speed test', () => {
  cy.visit('https://test-page-speed.cypress.io/index1000.html')
})
```

and Cypress took `76570ms` to run the same page, which is significantly longer than the chrome version.

### Desired behavior:

Something much faster.  At the moment, this is pretty much unusable for us :(

When doing some digging, it looks like cypress sets the `Transfer_encoding` to be chunked in its response (thru its proxy?). We guess its something to do with this?

Are there any settings we can try to help speed this up?

### Versions
Cypress 4.1

**Comment by jennifer-shehane** [comment]
I can verify this slowness in the network speed. All runs below running via `cypress open` in Chrome. All times based on initial run (not reruns).

I didn't test across every single version, but...it's pretty clear that it's much slower than Chrome normally. 

I'm also pretty confused by the 3.3.0 timings. I reinstalled and reran just to make sure I had the version right. 

## Running in Chrome outside of Cypress (incognito)

~ `4958 ms`

![Screen Shot 2020-03-06 at 6 20 59 PM](https://user-images.githubusercontent.com/1271364/76081340-4648b980-5fd7-11ea-9b72-86d54e7455ba.png)

## 3.0.0

~ `74567 ms`

<img width="878" alt="Screen Shot 2020-03-06 at 6 33 32 PM" src="https://user-images.githubusercontent.com/1271364/76082129-0e427600-5fd9-11ea-82c7-b13b797612f7.png">

## 3.3.0 (performance enhancements with blog)

~ `50755 ms`

<img width="875" alt="Screen Shot 2020-03-06 at 6 44 48 PM" src="https://user-images.githubusercontent.com/1271364/76082852-a9881b00-5fda-11ea-8d2c-a0aa4d83cd9e.png">


## 3.7.0

~ `9479 ms`

<img width="956" alt="Screen Shot 2020-03-06 at 6 29 56 PM" src="https://user-images.githubusercontent.com/1271364/76081896-878d9900-5fd8-11ea-88c9-ea152625c02a.png">


## 3.8.0

~ `10998 ms`

<img width="955" alt="Screen Shot 2020-03-06 at 6 24 36 PM" src="https://user-images.githubusercontent.com/1271364/76081597-dbe44900-5fd7-11ea-81da-da3612e15b14.png">

## 4.0.0

~ `32578 ms`

<img width="854" alt="Screen Shot 2020-03-06 at 6 52 49 PM" src="https://user-images.githubusercontent.com/1271364/76083319-beb17980-5fdb-11ea-98a0-d50137e6410f.png">



## 4.1.0

~ `76743 ms`

<img width="1013" alt="Screen Shot 2020-03-06 at 6 19 45 PM" src="https://user-images.githubusercontent.com/1271364/76081254-20231980-5fd7-11ea-9d91-6c42078a554e.png">

---

When they are slow, the first few seem to come in under 100ms, then they all are around 430ms with some coming in above 10000ms

<img width="380" alt="Screen Shot 2020-03-06 at 6 34 57 PM" src="https://user-images.githubusercontent.com/1271364/76082293-6aa59580-5fd9-11ea-847d-64967278286f.png">

**Comment by steve-tapley** [comment]
Thanks @jennifer-shehane for checking this out.

We'll revert back to 3.7 or 3.8 in the meantime until this is resolved.

**Comment by flotwig** [comment]
> When doing some digging, it looks like cypress sets the `Transfer_encoding` to be chunked in its response (thru its proxy?). We guess its something to do with this?

This is most likely not the source of the slowness.

We actually have tests that run on the proxy that try to validate that our proxy is not any slower than a normal HTTP proxy that you'd use in Chrome, and they seem to

**Comment by flotwig** [comment]
> When doing some digging, it looks like cypress sets the `Transfer_encoding` to be chunked in its response (thru its proxy?). We guess its something to do with this?

This is most likely not the source of the slowness.

@steve-tapley is your application running over HTTPS while you perform tests?

**Comment by steve-tapley** [comment]
Thanks for the quick response @flotwig. Yes we are running over HTTPS.
Looking forward to the new release.
