### ISSUE TITLE
Cypress app logs requests even when not run in debug mode

### ISSUE THREAD

**Issue by carlos-granados** [cypress-io/cypress#666]
## Current behaviour: 

When running the app it will output some logging about routes being requested. For example:
```
GET /__/ 200 31.778 ms - -
GET /__cypress/runner/cypress_runner.css 200 57.190 ms - -
GET /__cypress/runner/cypress_runner.js 200 337.162 ms - -
...
```

## Desired behaviour:
This output should only be shown if the app is run in debug mode

## How to reproduce:
Run the app and start some tests. It will output the logs described above

- Operating System: Mac OS
- Cypress Version: 0.20.1
- Browser Version: Chrome 60

**Comment by jennifer-shehane** [comment]
This still occurs. There is logging when running `cypress open` and clicking on a spec without specifying wanting logging. 

<img width="698" alt="screen shot 2019-02-01 at 6 39 18 pm" src="https://user-images.githubusercontent.com/1271364/52122259-be181800-2650-11e9-8fe6-d2cdf94b1b73.png">

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
