### ISSUE TITLE
Cypress tests Passing but showing message "cannot visit site"

### ISSUE THREAD

**Issue by kchemutai** [cypress-io/cypress#6661]
My cypress tests are Running well when i use npx cypress open but when running all tests are passing though i can see a message on the console, Failed to load xDesk an angular app i am testing and this is making the detached tests to fail when i run npx cypress run.. Attached is the screen shot. 

My expectation is that it should not show "Failed to load xDesk" since it loads it successfully and all the tests run as expected
<img width="533" alt="Screen Shot 2020-03-06 at 2 25 31 PM" src="https://user-images.githubusercontent.com/22611265/76080342-bcd5bf00-5fb7-11ea-9dca-ce0b52a9fe4e.png">

**Comment by CypressCecelia** [comment]
Can you share a reproducible example of your test code? That message reflects the name of the test passed to the it() command. Presumably, your code looks something like:

```javascript
it('fails to visit xDesk', () => {
  //test code here
  })
```
so regardless of whether the test passes or fails, it will show whatever the name is for the test. If the Test Runner is showing a different name for that test than what is displayed, please let me know.

**Comment by kchemutai** [comment]
/// <reference types="cypress" />
describe('Login  Test', function() 
{
    it('Navigate to login page', ()=> {
      cy.visit('https://staging.xdesk.fenixdb.com/login')

      cy.wait(500)

      // verify the title
      cy.title().should('eq', 'xDesk')

      // select the country
      cy.get('select').should('be.visible')

      cy.get('select').select('UG').should('have.value', 'UG')

      cy.get('.abcRioButtonContentWrapper').should('be.visible').click()

      cy.wait(500)
      //click sign in with Google

      cy.url().should('eq', 'https://staging.xdesk.fenixdb.com/dashboard')
    }) 
})

**Comment by jennifer-shehane** [comment]
@kchemutai I'm not able to run the provided tests. The `https://staging.xdesk.fenixdb.com/login` url does not resolve to an actual url. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
