### ISSUE TITLE
Why different date in chrome console and cypress console ?

### ISSUE THREAD

**Issue by golubvladimir** [cypress-io/cypress#6663]
I have test for match select date with table date.

```js
cy.get('.errors-table tbody tr td:nth-child(3)')
  .should($td => {
    const dateStartSelect = new Date(
      Cypress.env('year') +
      '-' +
      Cypress.env('month') +
      '-' +
      Cypress.env('day')
    );

    console.log(dateStartSelect);

    for (let i = 0; i < $td.length; i++) {
      expect(new Date($td[i].innerText)).to.be.greaterThan(dateStartSelect);
    }
  });
```

cypress config
```
{
  "env": {
    "year": "2020",
    "month": "2",
    "day": "1"
  }
}
```

In console Chrome -

> Sat Feb 01 2020 00:00:00 GMT+0200 (Восточная Европа, стандартное время)

In console Cypress

> ASSERT expected Mon, 17 Feb 2020 13:26:58 GMT to be above Fri, 31 Jan 2020 22:00:00 GMT
> ASSERT expected Mon, 17 Feb 2020 13:20:48 GMT to be above Fri, 31 Jan 2020 22:00:00 GMT
> ASSERT expected Mon, 17 Feb 2020 13:17:05 GMT to be above Fri, 31 Jan 2020 22:00:00 GMT
> ASSERT expected Mon, 17 Feb 2020 13:10:21 GMT to be above Fri, 31 Jan 2020 22:00:00 GMT
> ASSERT expected Mon, 17 Feb 2020 13:01:06 GMT to be above Fri, 31 Jan 2020 22:00:00 GMT

**Comment by jennifer-shehane** [comment]
JavaScript dates basically 😅 

I have no idea why all of the below are different values. This seems not related to the reading of the `Cypress.env()` though.

```js
it('should print date', () => {
  // The above is the equivalent of 
  // logs Sat Feb 01 2020 00:00:00 GMT+0630
  console.log(new Date('2020-2-1'))

  // But you probably wanted
  // logs Sat Feb 01 2020 06:30:00 GMT+0630
  console.log(new Date('2020-02-01'))

  // The below assertion failed
  // expected Fri, 31 Jan 2020 17:30:00 GMT to deeply equal Sat, 01 Feb 2020 00:00:00 GMT
  expect(new Date('2020-2-1')).to.deep.eq(new Date('2020-02-01'));
})
```

**Comment by jennifer-shehane** [comment]
Closing as not an issue in Cypress.
