### ISSUE TITLE
Cypress failing to generate same request as browser

### ISSUE THREAD

**Issue by TotalerBob** [cypress-io/cypress#6677]
### Current behavior:

I'm currently workin on a project with .Net Core 3.1, a React Frontend and Identity Server. The whole application is built on top of the Net Core 3.1 React with Authentication Template.

The goal is, to test the whole workflow of register and user, to login of an user, to deletion of an user. Unfortunately, this fails already at the register stage. While registering as a person, the request generated looks like this (Request copied as curl).

```
curl "https://localhost:44350/Identity/Account/Register?returnUrl=^%^2Fauthentication^%^2Flogin" -H "authority: localhost:44350" -H "cache-control: max-age=0" -H "origin: https://localhost:44350" -H "upgrade-insecure-requests: 1" -H "content-type: application/x-www-form-urlencoded" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" -H "sec-fetch-dest: document" -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" -H "sec-fetch-site: same-origin" -H "sec-fetch-mode: navigate" -H "sec-fetch-user: ?1" -H "referer: https://localhost:44350/Identity/Account/Register?returnUrl=/authentication/login" -H "accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7" -H "cookie: .AspNetCore.Antiforgery.Ld4fXaZiaqo=CfDJ8CPvt2vHayFAuTHpJJyQMYEYF6YIM_MpcsGLmx33iC7krKpz2WB41_BZLE1_21t0HhJm1qw92Bb6pjMi65hyL5Y_HGMBxvUxZcD5F6vP-GkqwfjMAc6-QTxBOmP5Q2FNovVCMBQ-yLUmbkv8Cj9EVOA; .AspNetCore.Mvc.CookieTempDataProvider=CfDJ8CPvt2vHayFAuTHpJJyQMYFRtGxyZOcbDZOX-TLpT_G4Shy0AFcFSGhPzUEraIJwyv-Y0pt5qlRC7bI5vpob1JkjFkjTirHei6harfH6HzNkR0akbk0mDMkma5-mknWkd19VcBmGx_lZHirbeA8YOqYs2HTQPu6hdE4ybwTD6QPCur8HQCbJunKcJEVPUOTYyA" --data "Input.Email=testnormal^%^40test123.com^&Input.Password=Password.1^&Input.ConfirmPassword=Password.1^&__RequestVerificationToken=CfDJ8CPvt2vHayFAuTHpJJyQMYFC5au8GJb95V2IsPcIND9gJXLpum-WFZ4zCRU97gCg1PSEVQdc7JDBvREE_KC6sSXz_YpAA0TNhklkD-bOtlcI3tGy6fKbT67ryvYVZi9CztCCECy32ypChcv0HAQDdGQ" --compressed
```

This returns a status code 312 and redirects us to the correct page.

On the other hand, there is the same procedure automated with cypress, there the requests looks strangely not the same.

```
curl "https://localhost:44350/Identity/Account/Register?returnUrl=^%^2Fauthentication^%^2Flogin" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" -H "Origin: https://localhost:44350" -H "Upgrade-Insecure-Requests: 1" -H "Content-Type: application/x-www-form-urlencoded" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" -H "Sec-Fetch-Dest: iframe" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" -H "Sec-Fetch-Site: same-origin" -H "Sec-Fetch-Mode: navigate" -H "Referer: https://localhost:44350/Identity/Account/Register?returnUrl=/authentication/login" -H "Accept-Language: en-US,en;q=0.9" -H "Cookie: __cypress.initial=true" --data "Input.Email=testcypress^%^40test123.com^&Input.Password=Password.1^&Input.ConfirmPassword=Password.1^&__RequestVerificationToken=CfDJ8CPvt2vHayFAuTHpJJyQMYEDLBgAJl2xt4FStDkGgS4mfCwYJj7Oaig3GGUnHoFRUjqrOPjUC5RSjmku_Tck8N8osVpCKiL0IwgNuxHSh3spcIGSGUiXRxkXLfdi872BI4GPbIQTYInZOUQwt9SKy9Y" --compressed --insecure
```

This request returns an statuscode 400 and does not redirect me (as expected). The register process cannot be tested like this.

The code to create the request from cypress is the following:

```js
it("should be possible to register a new user", () => { 
    cy.fixture("user").then(user => {
    cy.get("#Input_Email").type(user.email);
    cy.get("#Input_Password").type(user.password);
    cy.get("#Input_ConfirmPassword").type(user.password);
    cy.get("form").submit();
  });
});
```

### Desired behavior:

Cypress should behave like the case where the user submits the form and generate the same http request.

### Test code to reproduce

Generate an ASP Net Core 3.1 React Template with Authorization and create a test on the register form submitting the form.

### Versions

Cypress: 4.1.0
Windows: 10
Chrome: 80.0.3987.132

**Comment by TotalerBob** [comment]
Found a workaround. The Problem was the antiforgerytoken which was required. As you can see in the request, if an actual user submits the form, the token is being sent as cookie. However, if cypress does the request, the cookie is not being sent. This results in the difference of the status codes and the success.

The workaround is just to disable antiforgery on the forms required in testing.

Yet it is still unclear to me, why cypress does not attach the cookie to the request like the request of an actual user does?

**Comment by kentferolino** [comment]
We have the same problem. The thing is, I think our backend team might not agree to disable the Antiforgery. Do you think there is another workaround that can be done in the front-end? Thanks ahead

**Comment by TotalerBob** [comment]
I was able to resolve the issue, the primary problem being the lacking knowledge of the tool.

What I did NOT know was, that between every "it()" statement, ALL cookies, localstorage and so on is deleted. Meaning, the csrf token provided by the server is being deleted.

The solution for me was, to put every action tied to the registration process inside the same "it()" statement, so no cookies or localstorage is being deleted. Like this it works without a single issue.

**Comment by VesterDe** [comment]
@TotalerBob I don't know how much localstorage you need for those specs, but perhaps [preserveOnce](https://docs.cypress.io/api/cypress-api/cookies.html#Preserve-Once) could be useful for you, so you don't clutter a single it().

**Comment by jennifer-shehane** [comment]
Yes, Cypress clears all cookies in between tests in an attempt to create a clean browser state for each test. You can preserve cookies across tests by using the [Cypress.Cookies.preserveOnce()](https://on.cypress.io/cookies#Preserve-Once) function, passing the name of the cookies you'd like preserved.

We hope to improve the transparency of this API and make it more customizable in the future. https://github.com/cypress-io/cypress/issues/686

Closing as resolved. If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run.

**Comment by j1000** [comment]
I have a related noob question. My guess, TotalerBob, is that you allowed the page to be fully rendered before submitting the form, right? My question is, can Cypress instead provide a mock response to the server when it checks for the presence of the RVT in the hidden form field? I'm looking for that extra bit of speed that comes from not rendering the page.
