### ISSUE TITLE
Replace deprecated request library dependency

### ISSUE THREAD

**Issue by JustFly1984** [cypress-io/cypress#6679]
### Current behavior:

Request library is deprecated. Getting this message on installing packages in logs.

### Desired behavior:

Replace request with maintained alternative like node-fetch

### Test code to reproduce

just run `yarn add request`

**Comment by JustFly1984** [comment]
https://github.com/request/request/issues/3142

**Comment by jennifer-shehane** [comment]
Alternatives to `request`: https://github.com/request/request/issues/3143

Technically we have replaced our dependency of `request` with our own branch requiring `cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16`, although it seems not all packages are using this - and some are still using 2.88.0. 

https://github.com/cypress-io/request
