### ISSUE TITLE
Ability to specify folder path on cy.screenshot() command

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#668]
### Is this a Feature or Bug?
Feature

### Desired behavior:
It would be nice to specify folder path for cy.screenshot() command. In that case, user could have all the error screenshots in one folder, and all the standard ones in another folder. That way user could specify screenshot folder for errors in config file, and test screenshots in individual tests.

so config would be like:
```
"screenshotsFolder": "cypress/screenshots/errors"
```
and I would set up screenshots in each test file according to my taste (e.g. cy.screenshot('/loginScreens')), so after running the whole suite I would end up with something like this:
e.g. 
```
cypress/screenshots/errors
cypress/screenshots/loginScreens
cypress/screenshots/dashboardScreens
...
```

**Comment by filiphric** [comment]
I guess this is fixed in 3.0.2 by this - https://github.com/cypress-io/cypress/issues/1771

**Comment by jennifer-shehane** [comment]
Yes! Good catch, we missed tagging this one. So, here's an example of how it works now in [3.0.2](https://on.cypress.io/changelog#3-0-2).

```js
// screenshot will be saved as
// cypress/screenshots/actions/login/clicking-login.png
cy.screenshot('actions/login/clicking-login')
```

**Comment by sharmarahul** [comment]
@jennifer-shehane I am not seeing the behaviour you specified above in v3.0.3
```
// screenshot will be saved as
// cypress/screenshots/actions/login/clicking-login.png
cy.screenshot('actions/login/clicking-login')
```
// from file test.js
If I use `cy.screenshot('/login/my-screenshot' I expect path // cypress/screenshots/login/my-screenshot.png`

instead spec file name is also appended and I get
`cypress/screenshots/test.js/login/my-screenshot.png`
Is there a way to turn off `test.js` being added to the path?
