### ISSUE TITLE
Can't add 2 values to 1 cookie name using cy.setCookie

### ISSUE THREAD

**Issue by lopgab** [cypress-io/cypress#6680]
I'm having a hard time setting 2 values to the same cookie name

### Current behavior:

This is my code:
```js
cy.setCookie(
  "name",
  "value1,value2"
);
```

I've tried to encodeURI, I've tried changing the comma to a semi-colon, I've tried change the quotes to something else.

Whatever I do, it always triggers `cy.setCookie()` must be passed an RFC-6265-compliant cookie value.

I also tried separating into 2 lines but, of course, the latter cookie removes the one prior.

### Desired behavior:

To have `name` with the 2 values: `value1,value2`.

### Versions

Cypress 3.7.0

**Comment by jennifer-shehane** [comment]
This was already fixed in a more recent version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog).
