### ISSUE TITLE
Export TypeScript types from `driver` for NPM package

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#6683]
The NPM module's `types` are manually defined and kept up-to-date in `cli/types/index.d.ts`, but the code for these types is largely defined by the shapes of objects in `packages/driver`

Historically, this was done because the `driver` was all coffeescript, so types had to be manually defined. Now that it's starting to get converted to Typescript, we can potentially generate the type declaration file from the Typescript files.

This has some benefits:

- not having to manually update `index.d.ts` all the time
- better guarantees that what's being exported from the declaration file matches the implementation
- we can take advantage of better types internally

Challenges:

- more dtslint tests will be necessary, especially to ensure that there is not a backwards-incompatible change in the declarations when this change is made
- many files in the driver are still coffeescript and do not export types - may need to add external module declaration shims for now since some coffee files cannot be converted since there are open PRs against them

Related issues:

- https://github.com/cypress-io/cypress/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22type%3A+typings%22
- https://github.com/cypress-io/cypress/issues/4218

**Comment by CypressJoseph** [comment]
This is definitely a good idea! Maybe we could revisit when the coffee-to-TS conversion is more fullsome?

Note that `driver/src` is still about 2/3 coffee: ```find packages/driver/src -type f | sed 's/.*\.//' | sort | uniq -c | sort
   1 json
   9 ts
  29 js
  60 coffee```
