### ISSUE TITLE
Parallelization with Jenkins on 4.1.0 cause one of the machines to hang

### ISSUE THREAD

**Issue by dtranVAMP** [cypress-io/cypress#6685]
### Current behavior:

Having issues with parallelization when updating to 4.1.0:
https://dashboard.cypress.io/projects/yzyqri/runs/553/specs

Worked fine in 4.0.2.
https://dashboard.cypress.io/projects/yzyqri/runs/549/specs

We also use Jenkins as our CI/CD platform when kicking off these tests.  When we updated to 4.1.0 for some reason one of the machines will get stuck in the first spec it runs, while the second machine continues on as usual.

I'm not sure where else I can get logs from as jenkins console is running as fine.

We're only running on two machines.

### Versions

4.1.0

**Comment by dtranVAMP** [comment]
I was able to successfully run a test run after taking away parallel in the jenkins script.
https://dashboard.cypress.io/projects/yzyqri/runs/554/specs

<img width="1086" alt="Screen Shot 2020-03-09 at 3 08 45 PM" src="https://user-images.githubusercontent.com/49879370/76261759-f147b600-6217-11ea-99ad-7e424a140336.png">

**Comment by jennifer-shehane** [comment]
We're not currently aware of any issues introduced during Cypress 4.1.0. 

We'd be happy to assist you in tracking down the issue. As a paying customer, you have access to email support and can email us at support@cypress.io - this may be more convenient sharing potentially sensitive information about your tests and project configuration.

**Comment by dtranVAMP** [comment]
Moving this to email support.  You can close if needed @jennifer-shehane .
