### ISSUE TITLE
Drag & Drop upload

### ISSUE THREAD

**Issue by SMenigat** [cypress-io/cypress#669]
We are still looking for an option to test Drag & Drop file uploads. 
Is there anything in the plans about this?

Would be nice if I could drop a fixture onto the selected subject. Something like this maybe:

```js
// fixture reference according to: 
// https://docs.cypress.io/api/commands/fixture.html#Shortcuts
cy.get('.dnd-upload-area').dropFile('fixture:image.jpg');
```

Thanks in advance 😊

**Comment by jennifer-shehane** [comment]
We actually have a way to do this in version  `0.20.0`. We have our own drag-and-drop folder select in our Desktop App if you [globally install cypress](https://on.cypress.io/installing-cypress#Direct-Download) that we test using Cypress. Just going to throw in some of our tests for this (which will soon be Open Source). This is a bit of a firehose, but hopefully it's helpful. 

**Mostly you're looking to use the new [`.trigger()`](https://on.cypress.io/trigger) command.**

```js
describe('Drag and Drop', function() {
  beforeEach(function() {
    this.dropEvent = {
      dataTransfer: {
        files: [{ path: '/foo/bar' }]
      }
    }
  })

  it('shows project drop area with button to select project', function() {
    cy.get('.project-drop p:first')
      .should('contain', 'Drag your project here')
  })

  describe('dragging and dropping project', function() {
    it('highlights/unhighlights drop area when dragging over it/leaving it', function() {
      cy.get('.project-drop')
        .trigger('dragover')
        .should('have.class', 'is-dragging-over')
        .trigger('dragleave')
        .should('not.have.class', 'is-dragging-over')
    })

    it('unhighlights drop area when dropping a project on it', function() {
      cy.get('.project-drop')
        .trigger('dragover')
        .should('have.class', 'is-dragging-over')
        .trigger('drop', this.dropEvent)
        .should('not.have.class', 'is-dragging-over')
    })

    it('adds project and opens it when dropped', function() {
      cy.get('.project-drop')
        .trigger('drop', this.dropEvent)
    })
  })
})
```

**Comment by SMenigat** [comment]
Wow thanks a lot @jennifer-shehane ! I'm going to try this out tomorrow and give you feedback about my success here.

**Comment by jennifer-shehane** [comment]
Hi @SMenigat, did this work out for you?

**Comment by egucciar** [comment]
Could also use some guidance on this approach, turns out I decide to start doing TDD when I'm building an upload screen w/ drag and drop existing third party

**Comment by jennifer-shehane** [comment]
Hey @egucciar, what about the test code above did not work exactly? Did you get an error? Did the assertions fail?

I will add that some of the test code I pasted is particular to our implementation, so you will have to be familiar with how your drag and drop area is coded. 

Our implementation is open source here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/src/app/intro.jsx#L30

With the tests for this implementation here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/global_mode_spec.coffee#L75

**Comment by egucciar** [comment]
I guess the issue might be that I'm using angular-file-upload? Could that be it?

@jennifer-shehane

**Comment by jennifer-shehane** [comment]
@egucciar You have to look at the way the particular drag and drop you want to test is currently working. The way I do this is, within the Sources panel of the DevTools, you set some Event Listener Breakpoints for Drag/drop, then you *use* the drag and drop normally in your app by dragging an image in. Then you can see exactly what these events look like and the data that it uses in your application. 

**Set a global Event Listener Breakpoint**
![screen shot 2017-11-08 at 3 01 35 pm](https://user-images.githubusercontent.com/1271364/32571802-b53ae43c-c496-11e7-8913-d260fa711ce4.png)

**The dataTransfer object from me dragging in a photo manually to their site**
![screen shot 2017-11-08 at 3 04 31 pm](https://user-images.githubusercontent.com/1271364/32571801-b52f764c-c496-11e7-9732-4d2dd4f08b3f.png)

Doing this with the demo page of angular-file-upload, I can see that a `dragover`, `drop` and `dragleave` are all triggered (you'll need to select and deselect them one by one as you set the breakpoint to inspect each one. 

From this, I can see that they have code around more data than my implementation above cared about in their `dragover` and `drop` event. They're expecting a `types` array in the `dataTransfer` object for example. And in order to get the filename to show up in the table, they have more data in their files array. The test code below should help get you started. I'm closing this issue. 

```js
describe('Drag and Drop', function() {
  const fileName = "foobar.jpg"
  
  beforeEach(function() {
    this.dropEvent = {
      dataTransfer: {
        files: [{
          name: fileName,
          size: 32796,
          type: "image/jpeg",
          lastModified: 1510154936000,
          webkitRelativePath: ""
        }],
        types: ["Files"]
      }
    }
  })
  
  it('drag and drop upload', function(){
    cy.visit('http://nervgh.github.io/pages/angular-file-upload/examples/simple/')
    cy.get('.my-drop-zone').first()
      .trigger('dragover', this.dropEvent)
      .should('have.class', 'nv-file-over')
      .trigger('drop', this.dropEvent)

    cy.get('table').contains(fileName)
  })
})
```

**Comment by egucciar** [comment]
@jennifer-shehane thats perfect and it works. Thanks so much for explaining your methodology as it will come in handy when we implement upload tests for other non angular code bases!!!

**Comment by EirikBirkeland** [comment]
@jennifer-shehane Thanks for the extremely helpful debugging post above. I learned a lot!

I tried this, and most of it worked, but the resulting POST has completely incorrect content somehow, and the server chokes on it.

It may relate to my `getAsFile` method mock below (I looked at the HTML5 spec and just tried some stuff):

```
			// Drag and drop a file to upload it
			const dropEvent = {
				dataTransfer: {
					dropEffect: "none",
					effectAllowed: "all",
					files: [],
					items: [
						{
							kind: "file",
							type: "text/plain",
							// TODO: Mock getAsFile: https://www.w3.org/TR/html51/editing.html#a-drag-data-item-kind
							getAsFile: function() {
								return dropEvent.dataTransfer.files.length
									? dropEvent.dataTransfer.files[0]
									: null;
							}
						}
					],
					types: ["Files"]
				}
			};

			cy.get('#upload-files').trigger('dragover', dropEvent).should('have.class', 'dragover').then(() => {
				dropEvent.dataTransfer.files.push({
					path: "/tmp/upload_cache/9a4611785ac01f967598d59ab536ee/2824-document.txt",
					name: "2824-document.txt",
					lastModified: 1522144523092,
					size: 36,
					type: "text/plain",
					webkitRelativePath: ""
				})
			})
			.trigger('drop', dropEvent);
```

**Comment by EirikBirkeland** [comment]
Or perhaps I am misunderstanding here: I was expecting to upload a file from the harddrive.

Perhaps I should restrict the scope of the test to actually testing the visuals drag'n'drop, without expecting end-to-end functionality?

**Comment by blaynem** [comment]
@jennifer-shehane thank you so much, this helped me a ton! Was a little confused at first, but ended up working through it.

For our specific drag and drop, it didn't care about `mousedown`, `mouseup` or any sort of clicking. After digging a bit deeper into the code, found that I had to call `dragstart`, `dragenter`, and `drop`. Drag start began on the element I wanted to drag, then I needed to dragenter on the element that it needed to be dropped at. And finally, had to grab the element we wanted to drag one more time and drop it there.

Been working on this all day, so pretty hyped right now.

Example Code:
```js
describe('a user can change the order of specific action types', () => {
    const { firstChip, secondChip, thirdChip } = rulesPageConstants
    it.only('can reorder boost actions', () => {
      setRuleActions(0)
      cy
        .get('#boosts-input-icon').click()
        .get('#reorder-actions-dnd-chip-0').as('firstChip')
          .should('have.text', firstChip)
        .get('#reorder-actions-dnd-chip-1').as('secondChip')
          .should('have.text', secondChip)
        .get('#reorder-actions-dnd-chip-2').as('thirdChip')
          .should('have.text', thirdChip)
        .get('@firstChip')
          .trigger("dragstart")
        .get('@secondChip')
          .trigger('dragenter')
        .get('@firstChip')
          .trigger('drop')
    })
  })
```

**Comment by kutlaykural** [comment]
@jennifer-shehane 
Hi!
Same code is not work for me. Trigger with "drop" not gives any reaction at dropable area.

dataTransfer object is little different:

![image](https://user-images.githubusercontent.com/38225108/39529408-49fc16c8-4e2f-11e8-9357-08631186241c.png)

Do you have any idea why it is not "FileList" but "Array"
Can this be cause of the problem?

thanks for advise

**Comment by andygock** [comment]
Does anyone have any tips on how one could simulate a drag and drop upload and be able to specify the *file contents* as well?

Let's say for example, I could predefine define the file contents in a variable.

The above example, at least from what I can see, doesn't say much about defining the actual file data.

**Comment by andygock** [comment]
I've actually found a solution to my previous question, referring to [this comment](https://github.com/cypress-io/cypress/issues/170#issuecomment-389837191):

To drag and drop upload file `myfile.csv` from `fixtures/`

```js
Cypress.Commands.add('upload_file', (selector, fileUrl, type = '') => {
  return cy.fixture(fileUrl, 'base64')
    .then(Cypress.Blob.base64StringToBlob)
    .then(blob => {
      const nameSegments = fileUrl.split('/')
      const name = nameSegments[nameSegments.length - 1]
      const testFile = new File([blob], name, { type })
      const event = { dataTransfer: { files: [testFile] } }
      return cy.get(selector).trigger('drop', event)
    })
});

describe("drag and drop upload", function() {
  it("uploads file from filesystem", function() {
    cy.upload_file('.drop', 'myfile.csv');
  });
});
```

**Comment by kutlaykural** [comment]
unfurtunately it does not work for me.
Maybe it is about ember.js. Is there anybody have solution with Ember?

**Comment by ZwaarContrast** [comment]
I ended up with something similar to @andygock. I made a gist here: https://gist.github.com/ZwaarContrast/00101934954980bcaa4ae70ac9930c60

This could be refactored to also make use of `Cypress.Blob.base64StringToBlob`, which I didn't know existed up till now :) Thanks for that!

**Comment by akarolewski** [comment]
@DanielStoica85 same here.

**Comment by ZwaarContrast** [comment]
@DanielStoica85  and @andygock did you check my gist? 

https://gist.github.com/ZwaarContrast/00101934954980bcaa4ae70ac9930c60

Something important to make it work for me was using `new window.File([blob], fileName)` instead of `new File([blob], fileName)`.

**Comment by kutlaykural** [comment]
@ZwaarContrast your solution not works for me. Maybe this caused from Ember.js. 
@DanielStoica85 and  @andygock  same as yours. Which framework do your test run against?

**Comment by andygock** [comment]
@kutlaykural @DanielStoica85 

Hi,

I haven't had time to look at this, but regarding the framework with my solution I had working, I was working with React and interacting with a [react-dropzone](https://github.com/react-dropzone/react-dropzone) component.

Andy

**Comment by allanpaiste** [comment]
I would personally sleep better if the test for this does not expect tested to go and research the implementation; Would be much better to just cover multiple situations with a working simulated drop. Anyhow. Created this for a friend who had an issue with getting drag-and-drop working for his project.

```javascript
/// <reference types="Cypress" />

const createEvent = function (eventName) {
    const event = new CustomEvent(eventName, {
        // The "bubbles" is important as it'll otherwise not be caught by document-level observers
        bubbles: true,
        cancelable: true
    });

    event.dataTransfer = {
        files: [],
        data: {},
        setData: function (type, val) {
            this.data[type] = val
        },
        getData: function (type) {
            return this.data[type]
        },
        dropEffect: 'move'
    };

    return event;
};

Cypress.Commands.add('dragAndDropUpload', (selector, fileUrl, type = '') => {
    return cy.fixture(fileUrl, 'base64')
        .then(Cypress.Blob.base64StringToBlob)
        .then(blob => new File([blob], fileUrl.split('/').pop(), {type}))
        .then(file => {
            const event = createEvent('drop');

            event.dataTransfer.files.push(file);

            return event;
        })
        .then(event => {
            cy.get(selector).trigger('drop', event);
        });
});

context('Tiny PNG', () => {
    beforeEach(function() {
        cy.visit('https://tinypng.com');
    });

    it('converts an uploaded file and provides usable download link', function() {
        cy.dragAndDropUpload('.upload .target', 'img.png');
        cy.get('.upload .progress.success').should('be.visible');
        cy.get('.upload .files a').contains('download');
    });
});
```

**Comment by kutlaykural** [comment]
@allanpaiste thank you for sharing 
but unfortunately, it doesn't work for me (Ember.js)

**Comment by allanpaiste** [comment]
Do you have an equivalent public site with similar uploader that I could test the whole thing against?

**Comment by abramenal** [comment]
https://www.npmjs.com/package/cypress-file-upload

**Comment by BataevDaniil** [comment]
```js
Cypress.Commands.add(
  'dropFiles',
  { prevSubject: true },
  (subject, namesFiles) => {
    const createFile = name => picture =>
      Cypress.Blob.base64StringToBlob(picture, name.replace('.', '/')).then(
        blob => new File([blob], name),
      )
    const createEvent = files => {
      const dropEvent = { dataTransfer: new DataTransfer() }
      files.forEach(file => dropEvent.dataTransfer.items.add(file))
      return dropEvent
    }
    let process = cy
      .fixture(namesFiles[0])
      .then(createFile(namesFiles[0]))
      .then(file => [file])
    for (let i = 1; i < namesFiles.length; i++) {
      process = process.then(files =>
        cy
          .fixture(namesFiles[i])
          .then(createFile(namesFiles[i]))
          .then(file => [...files, file]),
      )
    }
    return process.then(files =>
      cy.wrap(subject).trigger('drop', createEvent(files)),
    )
  },
)
```

**Comment by abramenal** [comment]
@BataevDaniil https://github.com/abramenal/cypress-file-upload/blob/master/example/cypress/integration/dropzone.spec.js#L8 😈

**Comment by khaldrago96** [comment]
Hi @jennifer-shehane , just wondering if I can use Cypress with ng-file-upload? I've been working on my upload file testing, that uses ng-file-upload and the test always passes an error. Thanks!

**Comment by abramenal** [comment]
@khaldrago96 
I've faced some users with ng-file-upload recently, you can take a look on:
https://github.com/abramenal/cypress-file-upload/issues/51

In short, cypress-file-upload works perfectly with ng-file-upload 😈

**Comment by khaldrago96** [comment]
hi @abramenal , thanks for your response!
I just took a look on your thread and found out its using ng2-file-upload, which is dedicated for Angular2.
Does it work the same way for angularjs and its ng-file-upload ?

**Comment by abramenal** [comment]
@khaldrago96 
well then you'll be the first one who comes with AngularJS :)
I don't see any reason for the plugin to be not compatible, so you can try this out.
If you face any issue, feel free to submit it and I'll help you chase it!

**Comment by bijoutrouvaille** [comment]
I spent several hours today trying to get Filestack to automate. The solution is simple but not obvious: the `File` class you get inside your Cypress test file seems to be different from the one inside the browser, so the `instanceof` operator will return `false` on objects you instantiated with `new File`. Workaround: grab the browser's window object and use the `File` class from that, e.g.,

`cy.window().then(win => sendFileToFilestackOrWhatever(new win.File([blob], {type})))`

**Comment by krinhorn** [comment]
Hello! @jennifer-shehane (or anyone else who knows and sees this) - could you please explain how to see the dataTransfer object, as shown in [your screenshot here](https://github.com/cypress-io/cypress/issues/669#issuecomment-342944640)? I'm not sure which part of the console to click, and then I'm not sure how to drill down into the right object to find what's shown in your screenshot. Thanks!!

**Comment by allanpaiste** [comment]
It should be part of the event object that you'd be getting when observing the events that are also listed on the screenshot. So, register an observer for those events for a given DOM object, throw in a break-point and the event payload should have that dataTransfer you are looking for :)

**Comment by iltera** [comment]
> I've actually found a solution to my previous question, referring to [this comment](https://github.com/cypress-io/cypress/issues/170#issuecomment-389837191):
> 
> To drag and drop upload file `myfile.csv` from `fixtures/`
> 
> ```js
> Cypress.Commands.add('upload_file', (selector, fileUrl, type = '') => {
>   return cy.fixture(fileUrl, 'base64')
>     .then(Cypress.Blob.base64StringToBlob)
>     .then(blob => {
>       const nameSegments = fileUrl.split('/')
>       const name = nameSegments[nameSegments.length - 1]
>       const testFile = new File([blob], name, { type })
>       const event = { dataTransfer: { files: [testFile] } }
>       return cy.get(selector).trigger('drop', event)
>     })
> });
> 
> describe("drag and drop upload", () => {
>   it("uploads file from filesystem", () => {
>     cy.upload_file('.drop', 'myfile.csv');
>   });
> });
> ```

@andygock
Your solution should work with any other drag-n-drop upload plugins out there! Just brilliant!!!
Thank you very much for sharing :)

By the way, I'm working with vue-dropzone and nuxt-dropzone plugins.

**Comment by natre01** [comment]
I'm trying to test the drag and drop of a folder recursively. I could create an implementation of a DataTransfer object with every folder/subfolder/file being defined, but it would be very ugly very fast. Does anyone know of an easy way to do it? My folder would simply be fixtures
