### ISSUE TITLE
Unexpected shutdowns while running tests

### ISSUE THREAD

**Issue by saranyas72** [cypress-io/cypress#6692]
While running cypress tests, the system shut down unexpectedly. It happens intermittently (but frequently) so I cannot provide valid reproducible steps. I cannot figure out from logs on why it happened. While this happens under-recording folder I can see - `js.mp4` and `js-compressed.mp4` so the recording was partial and did not complete. 

From one shutdown instance - 
Found below the log in cypress console from the recording and screenshot. Could this be an issue?

![image](https://user-images.githubusercontent.com/9431304/76303161-95396c00-62c1-11ea-8c9c-7c85da15f9fd.png)

Another instance - 

I tried troubleshooting from Windows system logs and found (related ref: https://answers.microsoft.com/en-us/windows/forum/all/windows-10-system-keeps-initiating-unexpected/07a3b3f6-e2cf-4af9-bf04-22244850a050)

```
The system was shut down due to a critical thermal event.             
Shutdown Time = ‎2020‎-‎03‎-‎10T09:50:59.004913800Z             
ACPI Thermal Zone = Intel(R) Dynamic Platform Thermal Framework             
_CRT = 373K

The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user AzureAD\xxxxx SID (S-1-12-1-1259666139-1126642054-3536920749-3005351317) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user AzureAD\xxxxx SID (S-1-12-1-1259666139-1126642054-3536920749-3005351317) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```

I am running cypress tests on - 
Dell laptop
Windows 10 OS 

Are there any known compatibility issues with cypress and windows OS?

**Comment by saranyas72** [comment]
This issue was already reported but closed as could not reproduce  - https://github.com/cypress-io/cypress/issues/623

**Comment by saranyas72** [comment]
+ I am running on headless default browser - Electron 

Cypress:    4.1.0 
  │ Browser:    Electron 78 (headless)

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
