### ISSUE TITLE
Show change event in console on cy.check() and cy.uncheck() commands

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#67]
I typically listen to the change event on checkboxes to see if they've been checked / unchecked. Could you list the change event in the list of events within the console's log?

```js
it('check', () => {
  cy.visit('index.html')
  cy.get('input').check()
})
```

```html
<html>
<body>
  <input type="checkbox">
</body>
</html>
```

<img width="509" alt="screen shot 2015-09-30 at 1 19 29 pm" src="https://cloud.githubusercontent.com/assets/1271364/10200762/3900cdb6-6776-11e5-83fc-a6da798067e6.png">

**Comment by gabbersepp** [comment]
Hi is this still relevant?
I am looking for a first issue to start contributing and this seems to be an easy one.

I started investigation into this and I think I had to modify `click.js` in order to achieve this:

```js
consoleObj.groups = function () {
              const groups = [{
                name: 'MouseDown',
                items: _.pick(domEvents.mouseDown, 'preventedDefault', 'stoppedPropagation', 'modifiers'),
              }]

              if (domEvents.mouseUp) {
                groups.push({
                  name: 'MouseUp',
                  items: _.pick(domEvents.mouseUp, 'preventedDefault', 'stoppedPropagation', 'modifiers'),
                })
              }

              if (domEvents.click) {
                groups.push({
                  name: 'Click',
                  items: _.pick(domEvents.click, 'preventedDefault', 'stoppedPropagation', 'modifiers'),
                })
              }

              return groups
            }
```

**Comment by jennifer-shehane** [comment]
This issue is still relevant! Yes, this looks to be the exact lines of code I would look at as well for the PR. Make sure to review our [Contributing](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) guide also.

**Comment by jennifer-shehane** [comment]
Closing due to lack of interest for this feature. We log all Mouse events in the console log on uncheck/check currently.
