### ISSUE TITLE
Non-revocable commitment to OSS (engine/cli), concerns about binding arbitration in terms of use and suggestions

### ISSUE THREAD

**Issue by rmharrison** [cypress-io/cypress#670]
I understand that you're still in beta and probably intended to "cover your arse" against bad actors, but the binding arbitration provision in your [terms of use](https://www.cypress.io/terms-of-use/) gives me pause (that said, thank you for making that term clear up-front instead of burying it in the legalese).

If for whatever reason there is an issue (and I certainly hope there isn't), e.g. an undisclosed data breech or other activity that causes substantial economic damage, the recourse of individuals and small firms is substantially limited by not being able to participate in class action.

Even if you choose not to alter your terms, please consider:
- Providing a link to the "PRE-DISPUTE ARBITRATION CLAUSE" mentioned in section 19 (Binding Arbitration)
- Write a short, **non-legalese** synopsis of agreements so folks have at least some understanding of what they're signing.
  * [Github is a reasonable example](https://help.github.com/articles/github-terms-of-service/#b-account-terms) 
- Add the "Cypress CLI" and other OSS components (Cypress Desktop is already mentioned), and ensure they are indeed released under the MIT licence.
  * Folks are skittish following Facebook's unilateral BSD + Patents debacle.
  * I'd feel much more comfortable if I knew the licence/right-to-use on the engine/CLI was non-revocable.
  * Certainly understand monetizing the dashboard, but without some guarantees around the engine/CLI I'm left holding the bag on a rushed-migration off my entire front-end test-suite should something happen to yal. For example, folks only had a few months to transition their entire auth-stacks off [Stormpath](https://stormpath.com/blog/stormpaths-new-path). Adding to the pain, [Okta bungled](https://hackernoon.com/authentication-as-a-service-an-honest-review-of-auth0-315277abcba1#5a8e) the transition.

**Comment by SMenigat** [comment]
> I'd feel much more comfortable if I knew the licence/right-to-use on the engine/CLI was non-revocable.

> ... without some guarantees around the engine/CLI I'm left holding the bag on a rushed-migration off my entire front-end test-suite should something happen to yal.

Push. We are also investing heavily on cypress right now and this is one of our main concerns at the moment.

**Comment by brian-mann** [comment]
I understand your concerns. To be clear:

- We are in Beta
- We have not open sourced yet

If you're looking for guarantees around this, I would just say to wait. We're open sourcing in `1.0.0` (our next major release) with everything under an MIT license. That has been the plan that we've been working towards for months, if not years. 

At that time the Desktop Application will work independently of our services and never stop working. There is zero risk of your tests ever not being coupled to us as a company, or being able to run. We've been clear about this in our documentation.

I am not a lawyer, but after open sourcing I'm not sure what if anything we'd need to do to alleviate your concerns. I'd be happy to let our counsel take a look at anything more you want to provide.

**Comment by rmharrison** [comment]
Thanks for taking the time to respond (ohh great CEO :stuck_out_tongue: ).

**Per the CLI**, this makes me feel a lot better:
> There is zero risk of your tests ever not being coupled to us as a company, or being able to run.

The MIT license is "as-is", so there should be no need to run the OSS stuff past the lawyers.

**Per the dashboard**, there's still specific issue of the arbitration clause, and the general issue of communicating "legalese" to developers. No immediate action requested; just hope you'll take the suggestions under consideration.

**Comment by RandallKent** [comment]
A lot has happened since this issue was last updated over a year ago, so I wanted to take a moment to cirlce back on where we currently stand ...

The [Test Runner](https://github.com/cypress-io/cypress/) has been Open Sourced under the [MIT License](https://github.com/cypress-io/cypress/blob/develop/LICENSE.md).

The [Dashboard Terms of Use](https://on.cypress.io/terms-of-use) have been completely rewritten, taking into consideration many comments and suggestions we've received from user's and their legal teams. Anyone requiring alternative terms for their specific organization is encouraged to email sales@cypress.io - We try to be as flexible as we can be 😄
