### ISSUE TITLE
Uncaught ReferenceError: main.css is not defined

### ISSUE THREAD

**Issue by ShahidHShah** [cypress-io/cypress#6701]
I am trying to run a simple cypress test to our test server:
Getting a lot of this meassage rmark:1582796376/app-watermark/style.css net::ERR_EMPTY_RESPONSE

![image](https://user-images.githubusercontent.com/4621933/76414638-01869f00-6398-11ea-891b-7cc946ca90e2.png)

**Comment by jennifer-shehane** [comment]
This error is coming from your application code as stated in the error. Open your DevTools to see the error being thrown in order to fix it or you can disable failing tests in Cypress by [turning off exception handling](https://on.cypress.io/catalog-of-events#Uncaught-Exceptions)
