### ISSUE TITLE
"videosFolder":"."

### ISSUE THREAD

**Issue by hlb-schmidt** [cypress-io/cypress#6702]
https://docs.cypress.io/guides/references/configuration.html#Folders-Files
> `videosFolder` Path to folder where videos will be saved during `cypress run` (END OF TEXT)

so nothing _bad_ will happen, right? RIGHT?
```
$ ./node_modules/.bin/cypress --version
Cypress package version: 4.1.0
Cypress binary version: 4.1.0
```

**Comment by jennifer-shehane** [comment]
I'm not following what you're saying exactly here. 

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
