### ISSUE TITLE
Usage of "this" inside of "it"

### ISSUE THREAD

**Issue by kof** [cypress-io/cypress#6706]
### Current behavior:

Hey, we had a debate on the usage of arrow functions, because of some cases where the API can be used with `this`.

The origins of this debate are mostly because cypress documentation isn't super clear about not recommending to use `this`, so one thing that could help is to be more clear about it [here](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Avoiding-the-use-of-this) and say explicitly "we don't recommend" or so.

Another part is that Cypress is using a function declaration everywhere in documentation, which sends the wrong signal considered you don't recommend the use `this`. So a second improvement would be to convert all examples to use arrow functions instead.

Thoughts?

**Comment by jennifer-shehane** [comment]
There is no blanket recommendation to be given on whether to use `this` or not to use `this`. It depends on the context and how you are writing your tests. We use `this` a lot in our own tests and you need to remember where and when to use arrow functions versus not.

The use of `function` declarations sprinkled in the docs is just a reflection of older docs that have not been updated. New documentation is always be written using arrow functions except when necessary.

This repo is only for issues relating to the Cypress product. If you want to open an issue on our documentation, you can open it [here](https://github.com/cypress-io/cypress-documentation/issues/new). This issue will be closed in this repository.

**Comment by kof** [comment]
@jennifer-shehane Thank you for the answer! I guess there is no real need to reopen this issue over there.
