### ISSUE TITLE
Timed out retrying: Maximum call stack exceeded when typing into Salesforce Lightning Components

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6707]
### Current behavior:

When attempting to type into certain elements from Salesforce lightning components, an error is thrown like below:

```
CypressError: Timed out retrying: Maximum call stack size exceeded
```

<img width="555" alt="Screen Shot 2020-03-12 at 12 43 29 PM" src="https://user-images.githubusercontent.com/1271364/76492859-9ef8d600-645f-11ea-9640-6d6642ad124f.png">

Similar to previous issue that was resolved in 4.1.0 when doing visibility checks on elements - likely we are naively doing another check during type that is not considering the shape of elements generated in Salesforce Lightning Web Components https://github.com/cypress-io/cypress/issues/4373

### Desired behavior:

Should not throw Max call stack error

### Test code to reproduce

Pending

### Versions

Cypress 4.1.0

**Comment by jennifer-shehane** [comment]
I was able to track this Max call stack being thrown from the `getFirstStickyPositionParent` method. Similarly to the previous visibility check, it is iterating over the element without checking if `$el[0]` exists first. So, goes into an infinite loop. 

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/elements.ts#L917:L917

Likely there are other places where this check is insufficient still, so I'll take a look at some other instances and hopefully extract out this check into a broader method of 'checkExistence' and/or 'checkIfHtmlBodyOrDocument'.

Now comes the hard part of isolating a failing test case for the PR.

**Comment by jennifer-shehane** [comment]
Getting past the max call stack error, there is a separate error trying to type into a `textarea` in Salesforce Lightning Components. 

<img width="546" alt="Screen Shot 2020-03-12 at 1 52 12 PM" src="https://user-images.githubusercontent.com/1271364/76497119-c607d580-6468-11ea-85d2-e2428b15a090.png">

**Comment by mksjha** [comment]
Hi Jennifer,

Thanks for your help in opening and addressing this issue related to #4373.

We will test it again after your fix and let you know our feedback.
