### ISSUE TITLE
Why is a github account necessary

### ISSUE THREAD

**Issue by bm-stschneider** [cypress-io/cypress#671]
I'm feeling a bit uncomfortable letting cypress access my github. Can you maybe explain why this is necessary? Maybe projects I'm working on are not even on github so why would a testrunner need access to it?

**Comment by brian-mann** [comment]
It's only necessary in Beta and even then we only use it to receive your Github email. It's how we link up permissions for accessing the Dashboard projects and users.

In 1.0.0 we are moving the login to only be around Dashboard functionality. It will still require a Github account.

**Comment by bm-stschneider** [comment]
Thank you for the quick answer :)
