### ISSUE TITLE
cy.exec does not work on Shippable CI when using our cypress/base image

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6718]
When using `cypress/base:12.16.1` image on ShippableCI `cy.exec` gives the following error

Cypress v4.1.0
Linux Debian

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)' to be empty
```

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
