### ISSUE TITLE
`yarn clean-deps` requires `yarn install`

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6731]
### Current behavior:

If my `yarn install` is completely messed up - I want to be able to clean up my node_modules, but the `yarn clean` script requires that `lerna` be installed which is pretty counterintuitive. 

### Desired behavior:

A `clean-deps` script should never require actual node_modules be installed that you need to clean.

### Test code to reproduce

mess up your install somehow - for me, I accidentally ran `npm i`

`yarn clean-deps`

<img width="693" alt="Screen Shot 2020-03-16 at 11 42 42 AM" src="https://user-images.githubusercontent.com/1271364/76725052-5ef56400-677b-11ea-9d79-9a63cd4a6280.png">

### Versions

4.1.0

**Comment by andrew-codes** [comment]
Good point; an oversight. I'll have a PR ready for this shortly.
