### ISSUE TITLE
how to know error line number on script code in linux headless test 

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#6738]
After the Linux environment test, I want to know exactly which line the error line is. Now I can only see the screenshot, but I still need to analyze the corresponding script by myself, which is quite troublesome， on the long script code.

**Comment by jennifer-shehane** [comment]
I'm not exactly sure which 'error' you're referring to here, but believe that likely this PR will address what you want, which should go out in our next release - it's better errors and shows line/column location of where error originated https://github.com/cypress-io/cypress/pull/6724
