### ISSUE TITLE
Cannot print error details on tests with `.only`

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#6744]
### Bug (regression - 4.0.0)
 In open mode, if you put an `.only` on a failing test
 and click on the error,

the error is not printed to console;
instead it fails with 
```yaml
No error found for test id [testid]
```
![image](https://user-images.githubusercontent.com/14625260/76798337-c88a6800-67a5-11ea-8798-6422e349f095.png)

this is due to changes with handling mocha `.only` tests made for `4.0`

**Comment by jennifer-shehane** [comment]
I would not really broadly apply this to any failing test with a `.only`. I can reproduce from example below:

```js
it.only('failing spec', () => {
  throw(new Error())
})
```

But many other failing spec examples work fine with logging on click of the error, so it's something specific to the way the test fails.

This is fixed from https://github.com/cypress-io/cypress/pull/6724 though, which has put a lot of tests and thought around these situations.

<img width="442" alt="Screen Shot 2020-03-17 at 1 36 36 PM" src="https://user-images.githubusercontent.com/1271364/76830816-7b190400-6854-11ea-8de0-3f2777764045.png">

The code for this is done in https://github.com/cypress-io/cypress/pull/6724, but has yet to be released.
We'll update this issue and reference the changelog when it's released.

**Comment by Bkucera** [comment]
it does appear to be fixed now, great
