### ISSUE TITLE
Cannot read property 'map' of null at parseMatrix2D

### ISSUE THREAD

**Issue by shoomakov** [cypress-io/cypress#6745]
### Current behavior:

Trying `cy.get('.selector')` - fail with TypeError: `Cannot read property 'map' of null`

When the "vue-fragment" component is included in the project, cypress, for some reason, cannot parse

![image](https://user-images.githubusercontent.com/17549325/76803838-71a38380-67e3-11ea-9023-3aa006c6301b.png)

### Test code to reproduce

I created a repository to reproduce:
https://github.com/shoomakov/cypress-issue

```
npm i
npm run serve

cd tests/e2e
npm i
npm run dev
```

### Versions
Cypress v.4.0.2
Browser Chrome

**Comment by jennifer-shehane** [comment]
I can recreate this. This was introduced in Cypress 3.8.2 - like by this PR https://github.com/cypress-io/cypress/pull/5916 cc @sainthkh 

This error is being thrown here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/transform.ts#L180:L180

In this case the `transform = ""`, which evaluates to `null` within `transform.match(numberRegex)`

One of the elements has empty strings for all these values for some reason. 

<img width="615" alt="Screen Shot 2020-03-17 at 3 16 35 PM" src="https://user-images.githubusercontent.com/1271364/76838259-588de780-6862-11ea-946e-ac534710e10e.png">


## 3.8.1

Incorrectly determined element as not visible.

<img width="527" alt="Screen Shot 2020-03-17 at 3 05 23 PM" src="https://user-images.githubusercontent.com/1271364/76837315-bfaa9c80-6860-11ea-822d-cebb3d204f8e.png">

## 3.8.2

Erroring with 'Cannot read property map of null'

<img width="969" alt="Screen Shot 2020-03-17 at 2 50 31 PM" src="https://user-images.githubusercontent.com/1271364/76837207-86722c80-6860-11ea-9f5b-5b346b5451fd.png">

**Comment by sainthkh** [comment]
The cause of this problem is that [`vue-fragment`](https://github.com/y-nk/vue-fragment) creates a DOM element that returns empty CSSStyleDeclaration. 

I'm trying to mock this behavior.
