### ISSUE TITLE
Deprecation warnings from electron / node during `cypress open`

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6750]
### Current behavior:

Since updating to 4.2.0, I'm seeing some deprecation warnings in the stdout when running `cypress open`

```
Opening Cypress...
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:87713) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:87713) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```

### Desired behavior:

Would like for users of cypress to either not have these deprecation warnings shown to them or fix the usecases so the deprecation warnings do not need to be shown at all.

### Deprecation warnings

I believe all of these originate from https://github.com/cypress-io/cypress/pull/6555

1. Electron https://github.com/electron/electron/issues/18397

	This is being used here, looks like this issue is already noted https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/electron-app.js#L18:L18

2. Node - also coming from Electron. Explanation of this one here: https://www.electronjs.org/docs/breaking-changes#sending-non-js-objects-over-ipc-now-throws-an-exception

### Versions

4.2.0

**Comment by flotwig** [comment]
Bleh, the `app.allowRendererProcessReuse` should not be appearing, that's why that code is there in `electron-app`... maybe something is different in the packaged app.

I can look into the IPC warnings, most likely just need to filter out non-clonable objects in the desktop-gui's IPC code.

**Comment by flotwig** [comment]
Found some info to help clean up objects so they can be cleanly cloned and avoid the second deprecation warning: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
