### ISSUE TITLE
npm install -g cypress throw error

### ISSUE THREAD

**Issue by Nightbr** [cypress-io/cypress#6751]
Hey folks,

### Current behavior:

```shell
npm install -g cypress

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-17T09_42_31_708Z-debug.log
```

Same problem with `nxp cypress ...`

![image](https://user-images.githubusercontent.com/4228646/76843781-8f510700-683c-11ea-9a67-7a065149db88.png)

![image](https://user-images.githubusercontent.com/4228646/76843840-a8f24e80-683c-11ea-9b93-b215da1274e7.png)

Seems he doesn't resolve `ssh://git@github.com/cypress-io/request.git`.

### Desired behavior:

`npm install -g cypress` install successfully

### Test code to reproduce

run `npm install -g cypress`

### Versions

`cypress@latest`

Thanks in advance for your help & don't hesitate if you need more info/tests!

Continue the good work!

Cheers

**Comment by Nightbr** [comment]
Ok seems a docker problem. Latest image of `node:12-slim` doesn't include git anymore (and wget, ...).

`RUN apt-get update && apt-get install -y gnupg2 ca-certificates wget git`

+

`RUN npm install -g --unsafe-perm cypress`

Seems to fix this :ok_hand: 

Sorry fo the noise, but if this can help other!

**Comment by prabhumohan09** [comment]
Hi @Nightbr,
Are you installing thru the docker image?

**Comment by Nightbr** [comment]
Yes, it was on a `gitlab-ci.yml` to build a docker image.

**Comment by asaldivar** [comment]
thanks @Nightbr , this _workaround_ did the trick for my Dockerfile. However, wish we didn't need to run those installs...my build is _that_ much slower now. 😬

**Comment by nicolas-marcq** [comment]
But, git commands based on SSH are require authentication, isn't it?

So ssh://git@github.com/cypress-io/request.git will always refuse to clone if your are not a member of the project.
It should be based on an https url.

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/cypress-io/request.git
npm ERR! 
npm ERR! Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by SanderMeesterIndepender** [comment]
> But, git commands based on SSH require authentication, isn't it?
> 
> So ssh://git@github.com/cypress-io/request.git will always refuse to clone if your are not a member of the project.
> It should be based on an https url.
> 
> ```
> npm ERR! Error while executing:
> npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/cypress-io/request.git
> npm ERR! 
> npm ERR! Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
> npm ERR! Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR! 
> npm ERR! exited with error code: 128
> ```

install is now also failing on my win-machine which does not have port 22 open
