### ISSUE TITLE
Add support for arrays of keys in `its` and `invoke` commands

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#6758]
### Current behavior:

The [its](https://docs.cypress.io/api/commands/its.html) and [invoke](https://docs.cypress.io/api/commands/invoke.html) commands both use path traversal to get to paths, but don't allow arrays to be passed. 

This code prevents an array from being passed: https://github.com/cypress-io/cypress/blob/36866da64d86dc7e162489e357d7fc814ff025bb/packages/driver/src/cy/commands/connectors.coffee#L196

Later, the path is turned into an array anyways: https://github.com/cypress-io/cypress/blob/36866da64d86dc7e162489e357d7fc814ff025bb/packages/driver/src/cy/commands/connectors.coffee#L336

Array paths would allow both `its` and `invoke` to be type-safe.

### Desired behavior:

```js
cy
  .wrap({ a: { b: 2 } })
  .its('a.b') // returns 2, but the type is `any`
  .should('equal', 2)

cy
  .wrap({ a: { b: 2 } })
  .its(['a', 'b']) // returns 2, type is `number`
  .should('equal', 2)
```

### Test code to reproduce

```js
cy
  .wrap({ a: { b: 2 } })
  .its(['a', 'b'])
  .should('equal', 2)
```

### Versions

All up to 4.2.0

**Comment by CypressJoseph** [comment]
While I do think this is a great idea I think there's a little bit of a question 'how deep' to go with these types -- the recursive forms are pretty unmanageable or unattainable without bleeding-edge typescript and even if they work in a lot of cases seem like they have the potential to freak the compiler out anyway.

My suggestion would be adding 2-3 layers of signatures for property-path based traversal by array of keys (forms with one key, two keys, three keys, and then fall back to any beyond that). However, I have definitely experimented with this before and there are some drawbacks with that sort of approach too. Edges that I am thinking about would be not supporting ellipsis things very well (deconstructing even an array literal I think would fall back to any, but this is probably "fine".)

**Comment by NicholasBoll** [comment]
Lodash only goes 4 levels deep. I think that's fine: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/object.d.ts#L1736-L1740

When you say deconstructing an array literal, do you mean:

```js
_.get([42], [0])
```

This looks like it is supported in lodash types. It comes out as `number`.

I think a compromise is falling back to `any` if there it is too deep is fine. At the moment I either use more than one `its`, or I use [cypress-pipe](https://github.com/NicholasBoll/cypress-pipe) for type-safe traversal of objects:

```js
cy
  .wrap({ a: { b: 2 })
  .pipe(o => o.a.b) // o is { a: { b: number}}. Return type is `number`. Access is type-checked
  should('equal', 2)
```

**Comment by CypressJoseph** [comment]
The thing I was thinking about was that, with these signatures active, TS still falls back to `any` when contemplating something like `.its(...['my', 'nested', 'prop'])`. 

But to be clear I think this behavior is *completely fine* here, since the call doesn't actually _formally_ match any of the literal signatures (even if semantically it 'feels' the same.)
