### ISSUE TITLE
Create webpack preprocessor

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#676]
Create a preprocessor that utilizes webpack, with watching feature and utilizing babel loader by default. This will make it easy for users already using webpack to customize it to their needs as well as serve as another example of how to write a preprocessor plugin.

**Comment by chrisbreiding** [comment]
The code for this is done, but has yet to be released. We'll update this issue and reference the changelog when it's released.

**Comment by brian-mann** [comment]
Released in [`1.1.0`](https://docs.cypress.io/guides/references/changelog.html#1-1-0).
