### ISSUE TITLE
cypress - mochawesome reporter failed to create results folder & separate json files

### ISSUE THREAD

**Issue by a-onkar** [cypress-io/cypress#6772]
### Current behavior:

I am trying to add Mochawesome reporter using cypress docs: https://on.cypress.io/reporters#Spec-to-STDOUT-produce-a-combined-Mochawesome-JSON-file

At a step I execute cmd:  https://on.cypress.io/reporters#Command-line-4
```
./node_modules/.bin/cypress run --reporter mochawesome \ --reporter-options 
reportDir=reporter-config.json,overwrite=false,html=false,json=true
```

According to the doc: A folder named results must be created. Apparently I am getting a folder named "reporter-config.json,overwrite=false,html=false,json=true"
which is equivalent to a string mentioned in above cmd. 

Problem 2: I have 2 spec files, the report for only 1 spec file is being created.

Problem 3: The report is created in both HTML & JSON format.

All these problems are highlighted in screenshot below:

![image](https://user-images.githubusercontent.com/25897622/76962209-b976f780-6916-11ea-8ff0-b671cbb9c39a.png)

### Desired behavior:

The results folder should be created.
Generate files `cypress/results/mochawesome.json`, `cypress/results/mochawesome_001.json` as mentioned in doc.

### Versions

Cy: 4.2.0
Win 10
The latest version of Mocha dependencies.

@jennifer-shehane : Can we have a detailed guidelines on mochawesome report generation with versions to be used. I went through many blogs & tuts coiuld not find one that works.

**Comment by a-onkar** [comment]
@jennifer-shehane Can someone please look into this or guide me to appropriate resource who can help.

**Comment by jennifer-shehane** [comment]
Yeah, you might want to try playing around with quotes of the arguments in your terminal. We've seen a lot of issues with Windows not recognizing arguments properly unless they're quoted. I think all of the issues you're noting are related to the `reporter-options` not being read in correctly from the terminal on Windows. 

Running this on my Mac has the intended effect.

Maybe try:

```
cypress run --reporter mochawesome --reporter-options reportDir="reporter-config.json",overwrite="false",html="false",json="true"
```

**Comment by a-onkar** [comment]
@jennifer-shehane Thanks I will try. Closing as of now, because went ahead with Junit reporter.
