### ISSUE TITLE
Cannot set cypress.json nodeVersion=system (when using Yarn / Windows)

### ISSUE THREAD

**Issue by remjx** [cypress-io/cypress#6775]
### Current behavior:

In `cypress.json` if I set 
```json
{
    "nodeVersion": "system"
}
```
and run `yarn run cypress:open`, it gets stuck on loading spinner. And when I run `yarn run cypress:run`, I get this error: 
```
child_process.js:122
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:122:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:325:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:51:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}
```

No issues if I run these commands with NPM

### Desired behavior:

Able to run `cypress open` and `cypress run` with Yarn.

### Test code to reproduce

https://github.com/markjackson02/cypress-test-tiny-nodeversion-yarn-issue

Run `yarn install`, then `yarn run cypress:open` or `yarn run cypress:run` 

### Versions

Cypress 4.2.0
Node 12.16.1
Yarn 1.22.0
Windows 7

**Comment by jennifer-shehane** [comment]
My initial run of this - I was not encountering this issue. I was using Node.js v8.11.2. I installed and am now using Node.js v12.16.1 and am still not able to reproduce the error. 

This sounds similar if not exactly the same as https://github.com/cypress-io/cypress/issues/6792 which seemed to be a Windows issue combined with using system Node.js in the cypress.json - maybe yarn is another combining factor to this?

**Comment by crfrolik** [comment]
I suspect this is related to using `"nodeVersion": "system"` with node 13.9.0; I was also using yarn so that may be a factor.

**Comment by crfrolik** [comment]
I was also using `yarn` when I had this trouble.

**Comment by jennifer-shehane** [comment]
Closing as Duplicate of #6792

**Comment by markjackson02** [comment]
@jennifer-shehane I don't think this is a duplicate. I WANT to be able to run with nodeVersion=system.  Can you please reopen?

**Comment by jennifer-shehane** [comment]
Yeah, didn't realize that other issue was closed. Will open this to track why this is an issue.

**Comment by nlarsson** [comment]
Any progress on this? I face the same issue.

Cypress package version: 8.2.0
Cypress binary version: 8.2.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1

Yarn version: 1.22.4
System Node version: 16.6.1
Windows 10 (20H2 build 19042.1083)

**Comment by TerrySlack** [comment]
@jennifer-shehane I ran into this issue, using yarn.  Switch over to use npm to run a specific test in Cyress and no issues.
I'd say, without digging into why, it's a yarn issue on Windows.
