### ISSUE TITLE
Can't access saved objects from spec/test file that was saved from custom command

### ISSUE THREAD

**Issue by tvutx** [cypress-io/cypress#6779]
### Current behavior:

1. Created a custom command and assigned a variable to an object in the fixtures/globals.js
2. The object is assigned and I can log it within the custom command but the object is empty if I try to call it from the spec or test file.

![image](https://user-images.githubusercontent.com/19938919/77010892-b260e100-6938-11ea-8f13-fa5c1194347e.png)

![image](https://user-images.githubusercontent.com/19938919/77010976-dc1a0800-6938-11ea-9e81-87a324f441b4.png)

![image](https://user-images.githubusercontent.com/19938919/77011645-5303d080-693a-11ea-9214-07ea8b45377c.png)

### Desired behavior:
The object should be saved and I should be able to call it from the spec/test file

### Test code to reproduce

![image](https://user-images.githubusercontent.com/19938919/77011551-1a63f700-693a-11ea-8f2a-6044ca99ee99.png)

### Versions

Cypress - latest
OS - windows 10
browser - chrome 80

**Comment by jennifer-shehane** [comment]
Can you provide a full repo of code we can run here? There's some missing information here like where the `globals` is defined in your code and reaccessed within your test file. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
