### ISSUE TITLE
[Security] issues with linting yarn-lock after updating cypress to 4.2.0 with lockfile-lint

### ISSUE THREAD

**Issue by JustFly1984** [cypress-io/cypress#6785]
Our build pipeline lint yarn.lock file for security issues.

We have allowed only yarn as dependency source, and getting next error at build time:

```shell
yarn run v1.22.4
$ lockfile-lint --path yarn.lock --allowed-hosts yarn --validate-https
detected invalid host(s) for package: request@cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16
    expected: registry.yarnpkg.com
    actual: codeload.github.com

error: command failed with exit code 1 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

can you please confirm that it is a safe and intended change in source?

meanwhile downgrading cypress to 4.1.0

**Comment by JustFly1984** [comment]
https://github.com/lirantal/lockfile-lint/issues/79

**Comment by lencioni** [comment]
I think this was fixed in https://github.com/cypress-io/cypress/pull/6777 but that change has not been published yet.

**Comment by jennifer-shehane** [comment]
Duplicate of #6752

**Comment by lirantal** [comment]
@jennifer-shehane perhaps consider adding lockfile-lint to this repo as well to set a security policy for cypress's nested dependencies and avoid it in the future? [why it's important](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/)

/plug :-)

**Comment by jennifer-shehane** [comment]
@lirantal Yeah this is pretty interesting. Will take a look.

**Comment by lirantal** [comment]
@jennifer-shehane cool. I'm happy to assist if there's anything to help with.
