### ISSUE TITLE
Missing dependency @cypress-io/request in 4.2.0 when installed with npm ci

### ISSUE THREAD

**Issue by lkappeler** [cypress-io/cypress#6788]
I'm getting the following error when installing the version 4.2.0 with `npm ci` and executing `npm ls`

`npm ERR! missing: request@github:cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16, required by cypress@4.2.0`

### Test code to reproduce

```
mkdir cypress-test
cd cypress-test/
npm init
npm i -D cypress
rm -rf node-modules
npm ci
npm ls
```

### Versions

cypress@4.2.0

```
legatore@mbp15 cypress-test $ node --version
v13.7.0
legatore@mbp15 cypress-test $ npm --version
6.13.6
```

### Logs

Output of npm ls

<details>
<pre>
cypress-test@1.0.0 ~/cypress-test
└─┬ cypress@4.2.0
  ├─┬ @cypress/listr-verbose-renderer@0.4.1
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├── escape-string-regexp@1.0.5 deduped
  │ │ ├─┬ has-ansi@2.0.0
  │ │ │ └── ansi-regex@2.1.1
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.1.1 deduped
  │ │ └── supports-color@2.0.0
  │ ├─┬ cli-cursor@1.0.2
  │ │ └─┬ restore-cursor@1.0.1
  │ │   ├── exit-hook@1.1.1
  │ │   └── onetime@1.1.0
  │ ├── date-fns@1.30.1
  │ └─┬ figures@1.7.0
  │   ├── escape-string-regexp@1.0.5 deduped
  │   └── object-assign@4.1.1 deduped
  ├─┬ @cypress/xvfb@1.2.4
  │ ├─┬ debug@3.2.6
  │ │ └── ms@2.1.2 deduped
  │ └── lodash.once@4.1.1
  ├── @types/sizzle@2.3.2
  ├── arch@2.1.1
  ├── bluebird@3.7.2
  ├── cachedir@2.3.0
  ├─┬ chalk@2.4.2
  │ ├─┬ ansi-styles@3.2.1
  │ │ └─┬ color-convert@1.9.3
  │ │   └── color-name@1.1.3
  │ ├── escape-string-regexp@1.0.5
  │ └─┬ supports-color@5.5.0
  │   └── has-flag@3.0.0
  ├── check-more-types@2.24.0
  ├─┬ cli-table3@0.5.1
  │ ├── colors@1.4.0
  │ ├── object-assign@4.1.1
  │ └─┬ string-width@2.1.1
  │   ├── is-fullwidth-code-point@2.0.0
  │   └─┬ strip-ansi@4.0.0
  │     └── ansi-regex@3.0.0
  ├── commander@4.1.0
  ├── common-tags@1.8.0
  ├─┬ debug@4.1.1
  │ └── ms@2.1.2
  ├── eventemitter2@4.1.2
  ├─┬ execa@1.0.0
  │ ├─┬ cross-spawn@6.0.5
  │ │ ├── nice-try@1.0.5
  │ │ ├── path-key@2.0.1
  │ │ ├── semver@5.7.1
  │ │ ├─┬ shebang-command@1.2.0
  │ │ │ └── shebang-regex@1.0.0
  │ │ └─┬ which@1.3.1
  │ │   └── isexe@2.0.0
  │ ├─┬ get-stream@4.1.0
  │ │ └─┬ pump@3.0.0
  │ │   ├─┬ end-of-stream@1.4.4
  │ │   │ └── once@1.4.0 deduped
  │ │   └─┬ once@1.4.0
  │ │     └── wrappy@1.0.2
  │ ├── is-stream@1.1.0
  │ ├─┬ npm-run-path@2.0.2
  │ │ └── path-key@2.0.1 deduped
  │ ├── p-finally@1.0.0
  │ ├── signal-exit@3.0.2
  │ └── strip-eof@1.0.0
  ├─┬ executable@4.1.1
  │ └── pify@2.3.0
  ├─┬ extract-zip@1.6.7
  │ ├─┬ concat-stream@1.6.2
  │ │ ├── buffer-from@1.1.1
  │ │ ├── inherits@2.0.4
  │ │ ├─┬ readable-stream@2.3.7
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── inherits@2.0.4 deduped
  │ │ │ ├── isarray@1.0.0
  │ │ │ ├── process-nextick-args@2.0.1
  │ │ │ ├── safe-buffer@5.1.2 deduped
  │ │ │ ├─┬ string_decoder@1.1.1
  │ │ │ │ └── safe-buffer@5.1.2 deduped
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ ├─┬ debug@2.6.9
  │ │ └── ms@2.0.0
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ └─┬ yauzl@2.4.1
  │   └─┬ fd-slicer@1.0.1
  │     └── pend@1.2.0 deduped
  ├─┬ fs-extra@8.1.0
  │ ├── graceful-fs@4.2.3
  │ ├─┬ jsonfile@4.0.0
  │ │ └── graceful-fs@4.2.3 deduped
  │ └── universalify@0.1.2
  ├─┬ getos@3.1.4
  │ └── async@3.2.0
  ├─┬ is-ci@2.0.0
  │ └── ci-info@2.0.0
  ├─┬ is-installed-globally@0.1.0
  │ ├─┬ global-dirs@0.1.1
  │ │ └── ini@1.3.5
  │ └─┬ is-path-inside@1.0.1
  │   └── path-is-inside@1.0.2
  ├── lazy-ass@1.6.0
  ├─┬ listr@0.14.3
  │ ├─┬ @samverschueren/stream-to-observable@0.3.0
  │ │ └── any-observable@0.3.0
  │ ├─┬ is-observable@1.1.0
  │ │ └── symbol-observable@1.2.0
  │ ├── is-promise@2.1.0
  │ ├── is-stream@1.1.0 deduped
  │ ├── listr-silent-renderer@1.1.1
  │ ├─┬ listr-update-renderer@0.5.0
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1 deduped
  │ │ │ ├── escape-string-regexp@1.0.5 deduped
  │ │ │ ├── has-ansi@2.0.0 deduped
  │ │ │ ├── strip-ansi@3.0.1 deduped
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ cli-truncate@0.2.1
  │ │ │ ├── slice-ansi@0.0.4
  │ │ │ └─┬ string-width@1.0.2
  │ │ │   ├── code-point-at@1.1.0
  │ │ │   ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │   │ └── number-is-nan@1.0.1
  │ │ │   └── strip-ansi@3.0.1 deduped
  │ │ ├── elegant-spinner@1.0.1
  │ │ ├── figures@1.7.0 deduped
  │ │ ├── indent-string@3.2.0
  │ │ ├─┬ log-symbols@1.0.2
  │ │ │ └── chalk@1.1.3 deduped
  │ │ ├─┬ log-update@2.3.0
  │ │ │ ├── ansi-escapes@3.2.0
  │ │ │ ├─┬ cli-cursor@2.1.0
  │ │ │ │ └─┬ restore-cursor@2.0.0
  │ │ │ │   ├─┬ onetime@2.0.1
  │ │ │ │   │ └── mimic-fn@1.2.0 deduped
  │ │ │ │   └── signal-exit@3.0.2 deduped
  │ │ │ └─┬ wrap-ansi@3.0.1
  │ │ │   ├── string-width@2.1.1 deduped
  │ │ │   └─┬ strip-ansi@4.0.0
  │ │ │     └── ansi-regex@3.0.0
  │ │ └── strip-ansi@3.0.1 deduped
  │ ├─┬ listr-verbose-renderer@0.5.0
  │ │ ├── chalk@2.4.2 deduped
  │ │ ├─┬ cli-cursor@2.1.0
  │ │ │ └─┬ restore-cursor@2.0.0
  │ │ │   ├─┬ onetime@2.0.1
  │ │ │   │ └── mimic-fn@1.2.0
  │ │ │   └── signal-exit@3.0.2 deduped
  │ │ ├── date-fns@1.30.1 deduped
  │ │ └─┬ figures@2.0.0
  │ │   └── escape-string-regexp@1.0.5 deduped
  │ ├── p-map@2.1.0
  │ └─┬ rxjs@6.5.4
  │   └── tslib@1.11.1
  ├── lodash@4.17.15
  ├─┬ log-symbols@3.0.0
  │ └── chalk@2.4.2 deduped
  ├── minimist@1.2.2
  ├── moment@2.24.0
  ├── ospath@1.2.2
  ├── pretty-bytes@5.3.0
  ├── ramda@0.26.1
  ├─┬ UNMET DEPENDENCY request@github:cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16
  │ ├── aws-sign2@0.7.0
  │ ├── aws4@1.9.1
  │ ├── caseless@0.12.0
  │ ├─┬ combined-stream@1.0.8
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.2
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.3.3
  │ │ ├── asynckit@0.4.0
  │ │ ├── combined-stream@1.0.8 deduped
  │ │ └── mime-types@2.1.26 deduped
  │ ├─┬ har-validator@5.1.3
  │ │ ├─┬ ajv@6.12.0
  │ │ │ ├── fast-deep-equal@3.1.1
  │ │ │ ├── fast-json-stable-stringify@2.1.0
  │ │ │ ├── json-schema-traverse@0.4.1
  │ │ │ └─┬ uri-js@4.2.2
  │ │ │   └── punycode@2.1.1 deduped
  │ │ └── har-schema@2.0.0
  │ ├─┬ http-signature@1.2.0
  │ │ ├── assert-plus@1.0.0
  │ │ ├─┬ jsprim@1.4.1
  │ │ │ ├── assert-plus@1.0.0 deduped
  │ │ │ ├── extsprintf@1.3.0
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └─┬ verror@1.10.0
  │ │ │   ├── assert-plus@1.0.0 deduped
  │ │ │   ├── core-util-is@1.0.2 deduped
  │ │ │   └── extsprintf@1.3.0 deduped
  │ │ └─┬ sshpk@1.16.1
  │ │   ├─┬ asn1@0.2.4
  │ │   │ └── safer-buffer@2.1.2 deduped
  │ │   ├── assert-plus@1.0.0 deduped
  │ │   ├─┬ bcrypt-pbkdf@1.0.2
  │ │   │ └── tweetnacl@0.14.5 deduped
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0 deduped
  │ │   ├─┬ ecc-jsbn@0.1.2
  │ │   │ ├── jsbn@0.1.1 deduped
  │ │   │ └── safer-buffer@2.1.2 deduped
  │ │   ├─┬ getpass@0.1.7
  │ │   │ └── assert-plus@1.0.0 deduped
  │ │   ├── jsbn@0.1.1
  │ │   ├── safer-buffer@2.1.2
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.26
  │ │ └── mime-db@1.43.0
  │ ├── oauth-sign@0.9.0
  │ ├── performance-now@2.1.0
  │ ├── qs@6.5.2
  │ ├── safe-buffer@5.1.2
  │ ├─┬ tough-cookie@2.5.0
  │ │ ├── psl@1.7.0
  │ │ └── punycode@2.1.1
  │ ├─┬ tunnel-agent@0.6.0
  │ │ └── safe-buffer@5.1.2 deduped
  │ └── uuid@3.4.0
  ├─┬ request-progress@3.0.0
  │ └── throttleit@1.0.0
  ├─┬ supports-color@7.1.0
  │ └── has-flag@4.0.0
  ├─┬ tmp@0.1.0
  │ └─┬ rimraf@2.7.1
  │   └─┬ glob@7.1.6
  │     ├── fs.realpath@1.0.0
  │     ├─┬ inflight@1.0.6
  │     │ ├── once@1.4.0 deduped
  │     │ └── wrappy@1.0.2 deduped
  │     ├── inherits@2.0.4 deduped
  │     ├─┬ minimatch@3.0.4
  │     │ └─┬ brace-expansion@1.1.11
  │     │   ├── balanced-match@1.0.0
  │     │   └── concat-map@0.0.1
  │     ├── once@1.4.0 deduped
  │     └── path-is-absolute@1.0.1
  ├── untildify@4.0.0
  ├─┬ url@0.11.0
  │ ├── punycode@1.3.2
  │ └── querystring@0.2.0
  └─┬ yauzl@2.10.0
    ├── buffer-crc32@0.2.13
    └─┬ fd-slicer@1.1.0
      └── pend@1.2.0
<pre>
</details>

**Comment by lencioni** [comment]
I think this was fixed in https://github.com/cypress-io/cypress/pull/6777 but that change has not been published yet.

**Comment by jennifer-shehane** [comment]
Duplicate of #6752
