### ISSUE TITLE
cypress open shows infinite spinner on Windows

### ISSUE THREAD

**Issue by crfrolik** [cypress-io/cypress#6792]
### Current behavior:

<img width="338" alt="cursor" src="https://user-images.githubusercontent.com/60711200/77105634-58255600-69f4-11ea-8600-61bffd657b14.PNG">

`cypress open` works for me on Mac OS but not on Windows 10. I tried it with `DEBUG=cypress:*` turned on and attached the log file.

[cypress-open.log](https://github.com/cypress-io/cypress/files/4356536/cypress-open.log)

### Versions

Cypress 4.2.0, Windows 10

**Comment by enikolaev1405** [comment]
I have the same problem on Ubuntu 18

**Comment by jennifer-shehane** [comment]
Can you try an earlier version of Cypress to see if it is isolated to any recent newer versions?

**Comment by enikolaev1405** [comment]
Cypress 4.0.1 - reproduced

**Comment by crfrolik** [comment]
I tried deleting `node_modules` and re-installing (no luck) and downgrading cypress to various versions (down to 3.5.0) (no luck).

**Comment by jennifer-shehane** [comment]
@crfrolik You used to be using Cypress fine though right? So what has changed since then? 

I notice that you have `nodeVersion: 'system'` set in your configuration - which is resolving to Node.js 13.9.0. Can you try changing this to `nodeVersion: 'bundled'` and see if it runs? Did you recently update Node.js on your system?

**Comment by crfrolik** [comment]
> @crfrolik You used to be using Cypress fine though right? So what has changed since then?

Yes, many times on my Mac. I've recently been forced onto my Windows laptop so I can work from home, and this issue popped up.
 
> I notice that you have `nodeVersion: 'system'` set in your configuration - which is resolving to Node.js 13.9.0. Can you try changing this to `nodeVersion: 'bundled'` and see if it runs? Did you recently update Node.js on your system?

Oh, you are brilliant. That fixed it. I set it to `system` as a workaround for https://github.com/cypress-io/cypress/issues/5943, but I'll change it back for now. Thank you so much!
