### ISSUE TITLE
cy.exec() executes twice when first opening the cypress page. 

### ISSUE THREAD

**Issue by karlhan628** [cypress-io/cypress#6797]
### Current behavior:
cy.exec() executes twice when first opening the cypress page, it seems the page will be refreshed when cypress meet cy.visit(). then the hold code will be running again, please see my code below. 
in my code, the cy.exec('xxxx.js') is running twice. 

### Desired behavior:
it should only run the part after before()

### Test code to reproduce
    before('', ()=>{
        cy.exec('xxxx.js') 
        cy.visit('.......')
    })
    it('', ()=>{
       xxxxxx
})

**Comment by bahmutov** [comment]
Try putting the url you visit into base url as an experiment

**Comment by karlhan628** [comment]
thanks man, it works.  closing the ticket.
