### ISSUE TITLE
Total time should take into account setup and teardown

### ISSUE THREAD

**Issue by vjeux** [cypress-io/cypress#6802]
### Current behavior:

![image](https://user-images.githubusercontent.com/197597/77235624-cc870300-6b74-11ea-8ea8-2ee3be959802.png)

### Desired behavior:

The total time should be ~30s rather than 12s

### Test code to reproduce

https://github.com/excalidraw/excalidraw/pull/691
`time npm run test:e2e`

### Versions

Cypress: 3.8.3

**Comment by jennifer-shehane** [comment]
This timing only accounts for the actual test time. Our Dashboard does however does track and display all timing including setup/teardown separate from each tests execution. `

**Comment by jennifer-shehane** [comment]
I’ve actually been thinking about this lately since I’ve been taking a closer look at performance. I do kind of agree with this, there is some timing that can get lost. I don’t see us overhauling everything to iodate this however. We could have more insight via timings in the Cloud a bit easier.

**Comment by vjeux** [comment]
I would disagree with “some timing that can get lost”. In this case it’s 18 lost compared to 12 tracked. That’s a lot being lost.

I understand that it’s hard to properly track, and also it probably looks better on the marketing side to say 12s instead of 30s.

But also agree that it’s not the end of the world and you probably have more important things to focus on :)
