### ISSUE TITLE
cucumber report

### ISSUE THREAD

**Issue by rishichenna** [cypress-io/cypress#6805]
### Current behavior:

Unable to generate cucumber HTML report with cypress
### Desired behavior:

Need support for cucumber HTML reports

### Versions
LINUX
"cucumber-html-reporter": "^5.1.0",
"cypress": "^4.0.1",
"cypress-cucumber-preprocessor": "^2.0.1",

**Comment by rishichenna** [comment]
Issue generating Cucumber html report.
Conf used:
    "cucumber-html-reporter": "^5.1.0",
    "cypress": "^4.0.1",
    "cypress-cucumber-preprocessor": "^2.0.1",

**Comment by Shelex** [comment]
@rishichenna 
How to configure cucumber report: [link](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#output)
cucumber-json is generated on cucumber-preprocessor side. In case you have not managed to make it work - please post issue in [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/) repo.

**Comment by jennifer-shehane** [comment]
Closing as there is not enough information provided to confirm this is a bug within the Cypress product. Issues in our GitHub repo are reserved for potential bugs or feature requests for our Test Runner - not 3rd party plugins.

As stated above, please open an issue in the https://github.com/TheBrainFamily/cypress-cucumber-preprocessor repo if there is a bug or refer to their documentation on getting set up. 

If you think this is a bug in Cypress, please provide a fully reproducible example of a repo to show the Cypress bug and we will consider reopening.
