### ISSUE TITLE
Images cannot be inserted into the input file generated after clicking the img tag

### ISSUE THREAD

**Issue by ryosuke-fujisawa** [cypress-io/cypress#6806]
I am writing a React test. One of the tests is to insert an image into the input file.

we need clicks the img tag from a browser first, and selects a image from the browser, After selecting an image from computer, generate an input file with javascript.

So there is no inpu file in the whole dom of html. I need always click the img tag from the browser and select an image.

it is not possible to select an image from computer by clicking on the img tag from the Cypress program.

Is there a solution for this?

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
