### ISSUE TITLE
Unable to install cypress - error ENOENT during postinstall

### ISSUE THREAD

**Issue by richard-pal** [cypress-io/cypress#6807]
Cypress 3.8.3, 4.2.0 can not be installed on Windows 10.

### Current behavior:

```npm install cypress --save-dev

npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

> cypress@4.2.0 postinstall c:\dev\cyp-test\node_modules\cypress
> node index.js --exec install

npm WARN rollback Rolling back strip-ansi@4.0.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'c:\dev\cyp-test\node_modules\wrap-ansi\node_modules'
npm WARN cyp-test@1.0.0 No description
npm WARN cyp-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn =
npm ERR! file =
npm ERR! path =
npm ERR! errno ENOENT
npm ERR! cypress@4.2.0 postinstall: `node index.js --exec install`
npm ERR! spawn = ENOENT
npm ERR!
npm ERR! Failed at the cypress@4.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\R\AppData\Roaming\npm-cache\_logs\2020-03-23T06_52_30_322Z-debug.log
```

Logs:

```5346 warn cyp-test@1.0.0 No description
5347 warn cyp-test@1.0.0 No repository field.
5348 verbose stack Error: cypress@4.2.0 postinstall: `node index.js --exec install`
5348 verbose stack spawn = ENOENT
5348 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
5348 verbose stack     at onErrorNT (internal/child_process.js:469:16)
5348 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
5349 verbose pkgid cypress@4.2.0
5350 verbose cwd c:\dev\cyp-test
5351 verbose Windows_NT 10.0.18362
5352 verbose argv "C:\\apps\\nodejs\\node.exe" "C:\\Users\\R\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "cypress" "--save-dev"
5353 verbose node v12.16.1
5354 verbose npm  v6.14.3
5355 error code ELIFECYCLE
5356 error syscall spawn =
5357 error file =
5358 error path =
5359 error errno ENOENT
5360 error cypress@4.2.0 postinstall: `node index.js --exec install`
5360 error spawn = ENOENT
5361 error Failed at the cypress@4.2.0 postinstall script.
5361 error This is probably not a problem with npm. There is likely additional logging output above.
5362 verbose exit [ 1, true ]
```

### Desired behavior:

Cypress gets installed without error.

### Test code to reproduce

npm init
npm install cypress --save-dev

### Versions

npm-version: 6.14.3
node-version: v12.16.1
OS: Windows 10 (Windows_NT 10.0.18362)

**Comment by jennifer-shehane** [comment]
This is the same error when installing Cypress 3.8.3? We have had an install issue in 4.2.0 here: https://github.com/cypress-io/cypress/issues/6752

**Comment by richard-pal** [comment]
Thanks for looking into this issue.

For version 3.8.3 the log is the same.
The machine is not using a proxy.

Under WSL-Ubuntu the installation is OK, however the test execution is not - due to #5918 the known GPU problem ( "The display compositor is frequently crashing.")

With Ubuntu (running as a guest on Hyper-V) both the installation and test execution is OK.

**Comment by jennifer-shehane** [comment]
Can you update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you?

**Comment by richard-pal** [comment]
Thanks for getting back to this issue.

Unfortunately install still fails with cypress 4.4.1.
Please see the output below.

```
c:\dev\cyp-test>npm install cypress --save-dev

> cypress@4.4.1 postinstall c:\dev\cyp-test\node_modules\cypress
> node index.js --exec install

npm WARN cyp-test@1.0.0 No description
npm WARN cyp-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn =
npm ERR! file =
npm ERR! path =
npm ERR! errno ENOENT
npm ERR! cypress@4.4.1 postinstall: `node index.js --exec install`
npm ERR! spawn = ENOENT
npm ERR!
npm ERR! Failed at the cypress@4.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2020-04-27T11_58_20_003Z-debug.log
```

**Comment by pauloalexandre3d** [comment]
Hi, I have the same problem in Ubuntu 18.04 and the same cypress version.

**Comment by lunayui** [comment]
hi, I have the same problem in windows 10 and cypress 4.8

**Comment by NeoLovesPython** [comment]
Is there any resolution to this ? I'm facing the same thing on Ubuntu 20.04, cypress 4.8

**Comment by pauloalexandre3d** [comment]
Hi, I have the same problem in Ubuntu 20.04 and the same cypress 4.8.

**Comment by cmanriquee** [comment]
Hi there, is there any resolution on this?
I'm facing the same issue in Windows 10 for Cypress Version 5.0

> cypress@5.0.0 postinstall C:\Users\hp\Documents\Workstation\Cypress\cypress_e2e_automation\node_modules\cypress
> node index.js --exec install

npm WARN cypress_e2e_automation@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn bash
npm ERR! file bash
npm ERR! path bash
npm ERR! errno ENOENT
npm ERR! cypress@5.0.0 postinstall: `node index.js --exec install`
npm ERR! spawn bash ENOENT
npm ERR!
npm ERR! Failed at the cypress@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2020-08-25T01_14_50_903Z-debug.log

**Comment by sivulich** [comment]
Got the same problem on:
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
With npm version: 6.14.4
Full error output:
```
*********/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (************/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm WARN notsup Unsupported engine for cypress@5.2.0: wanted: {"node":">=10.0.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cypress@5.2.0
npm WARN notsup Unsupported engine for chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.0
npm WARN notsup Unsupported engine for cli-table3@0.6.0: wanted: {"node":"10.* || >= 12.*"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cli-table3@0.6.0
npm WARN notsup Unsupported engine for execa@4.0.3: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: execa@4.0.3
npm WARN notsup Unsupported engine for fs-extra@9.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fs-extra@9.0.1
npm WARN notsup Unsupported engine for log-symbols@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: log-symbols@4.0.0
npm WARN notsup Unsupported engine for tmp@0.2.1: wanted: {"node":">=8.17.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: tmp@0.2.1
npm WARN notsup Unsupported engine for human-signals@1.1.1: wanted: {"node":">=8.12.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: human-signals@1.1.1
npm WARN notsup Unsupported engine for universalify@1.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: universalify@1.0.0
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN draftjs-utils@0.10.2 requires a peer of draft-js@^0.11.x but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-chartist@0.13.3 requires a peer of chartist@^0.10.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/googlemaps@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/markerclustererplus@^2.1.29 but none is installed. You must install peer dependencies yourself.
npm WARN react-hamburgers@1.0.0 requires a peer of hamburgers@^0.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-ionicons@2.1.6 requires a peer of browserify-css@0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-multistep@3.7.3 requires a peer of react@16.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.62.0 requires a peer of react@16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-progress-steps@0.0.8 requires a peer of react@0.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-widgets-globalize@5.0.21 requires a peer of globalize@>=0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN window-resize-listener-react@1.1.0 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@5.2.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@5.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by sivulich** [comment]
> Got the same problem on:
> Description: Ubuntu 18.04.5 LTS
> Release: 18.04
> With npm version: 6.14.4
> Full error output:
> 
> ```
> *********/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
>       } catch {
>               ^
> 
> SyntaxError: Unexpected token {
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:616:28)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (************/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
> npm WARN notsup Unsupported engine for cypress@5.2.0: wanted: {"node":">=10.0.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: cypress@5.2.0
> npm WARN notsup Unsupported engine for chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.0
> npm WARN notsup Unsupported engine for cli-table3@0.6.0: wanted: {"node":"10.* || >= 12.*"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: cli-table3@0.6.0
> npm WARN notsup Unsupported engine for execa@4.0.3: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: execa@4.0.3
> npm WARN notsup Unsupported engine for fs-extra@9.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: fs-extra@9.0.1
> npm WARN notsup Unsupported engine for log-symbols@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: log-symbols@4.0.0
> npm WARN notsup Unsupported engine for tmp@0.2.1: wanted: {"node":">=8.17.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: tmp@0.2.1
> npm WARN notsup Unsupported engine for human-signals@1.1.1: wanted: {"node":">=8.12.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: human-signals@1.1.1
> npm WARN notsup Unsupported engine for universalify@1.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.10.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: universalify@1.0.0
> npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
> npm WARN draftjs-utils@0.10.2 requires a peer of draft-js@^0.11.x but none is installed. You must install peer dependencies yourself.
> npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
> npm WARN react-chartist@0.13.3 requires a peer of chartist@^0.10.1 but none is installed. You must install peer dependencies yourself.
> npm WARN react-google-maps@9.4.5 requires a peer of @types/googlemaps@^3.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-google-maps@9.4.5 requires a peer of @types/markerclustererplus@^2.1.29 but none is installed. You must install peer dependencies yourself.
> npm WARN react-hamburgers@1.0.0 requires a peer of hamburgers@^0.8.1 but none is installed. You must install peer dependencies yourself.
> npm WARN react-ionicons@2.1.6 requires a peer of browserify-css@0.12.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-multistep@3.7.3 requires a peer of react@16.12.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-native@0.62.0 requires a peer of react@16.11.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-progress-steps@0.0.8 requires a peer of react@0.14.7 but none is installed. You must install peer dependencies yourself.
> npm WARN react-widgets-globalize@5.0.21 requires a peer of globalize@>=0.1.0 but none is installed. You must install peer dependencies yourself.
> npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
> npm WARN window-resize-listener-react@1.1.0 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/react-scripts/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! cypress@5.2.0 postinstall: `node index.js --exec install`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the cypress@5.2.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> ```

Fixed it by updating node to newer version.

**Comment by bahmutov** [comment]
Ok, closing as this seems to be for old versions of Cypress and old versions of Node that are no longer supported.

**Comment by maximkoshelenko** [comment]
Same error. Cypress 5.5.0, Windows 10, Node 12.19.0

**Comment by maximkoshelenko** [comment]
In my case helped this solution:
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
Alternatively you could check if your ComSpec or PATH enviromental variables includes C:\Program Files (x86)\git\bin\bash.exe' value and replace it with path to your actual shell executable

**Comment by Fish-in-a-Barrel** [comment]
> Ok, closing as this seems to be for old versions of Cypress and old versions of Node that are no longer supported.

Seems like it should throw a useful error if the version of node is too old. The current behavior leaves the user with no clue as to the underlying problem.

**Comment by quantuminformation** [comment]
I'm getting this all the time, and get rid of it, even with no cypress deps:
```
Packages: +631
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/nikos/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 629, reused 628, downloaded 1, added 1, done
node_modules/.pnpm/cypress@12.3.0/node_modules/cypress: Running postinstall script, failed in 889ms
.../cypress@12.3.0/node_modules/cypress postinstall$ node index.js --exec install
│ Installing Cypress (version: 12.3.0)
│ [STARTED] Task without title.
│ [FAILED] The Cypress App could not be downloaded.
│ [FAILED]
│ [FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment v
│ [FAILED]
│ [FAILED] Otherwise, please check network connectivity and try again:
│ [FAILED]
│ [FAILED] ----------
│ [FAILED]
│ [FAILED] URL: https://download.cypress.io/desktop/12.3.0?platform=darwin&arch=x64
│ [FAILED] Error: unable to get local issuer certificate
│ [FAILED]
│ [FAILED] ----------
│ [FAILED]
│ [FAILED] Platform: darwin-x64 (22.2.0)
│ [FAILED] Cypress Version: 12.3.0
│ The Cypress App could not be downloaded.
│ Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable b
│ Otherwise, please check network connectivity and try again:
│ ----------
│ URL: https://download.cypress.io/desktop/12.3.0?platform=darwin&arch=x64
│ Error: unable to get local issuer certificate
│ ----------
│ Platform: darwin-x64 (22.2.0)
│ Cypress Version: 12.3.0
```

**Comment by quantuminformation** [comment]
solved, re install pnpm

**Comment by Ragunath** [comment]
Hi Team

Node v16.20.1
Angular cli 11.2.19

We are migrating our Angular JS project to Angular . Now we are in Angular 11.
 suddenly we are getting this error in Azure build pipeline.
 ```
  npm ERR! Installing Cypress (version: 4.2.0)
2024-03-21T10:22:36.8774331Z npm ERR! 
2024-03-21T10:22:36.8774573Z npm ERR! [?25l[10:18:20]  Downloading Cypress     [started]
2024-03-21T10:22:36.8774760Z npm ERR! [10:18:20]  Downloading Cypress     [failed]
2024-03-21T10:22:36.8775002Z npm ERR! [?25hThe Cypress App could not be downloaded.
2024-03-21T10:22:36.8775603Z npm ERR! 
2024-03-21T10:22:36.8776033Z npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
2024-03-21T10:22:36.8776269Z npm ERR! 
2024-03-21T10:22:36.8776663Z npm ERR! Otherwise, please check network connectivity and try again:
2024-03-21T10:22:36.8777008Z npm ERR! 
2024-03-21T10:22:36.8777314Z npm ERR! ----------
2024-03-21T10:22:36.8777452Z npm ERR! 
2024-03-21T10:22:36.8777604Z npm ERR! URL: https://download.cypress.io/desktop/4.2.0?platform=win32&arch=x64
2024-03-21T10:22:36.8777790Z npm ERR! Error: certificate has expired
2024-03-21T10:22:36.8777910Z npm ERR! 
2024-03-21T10:22:36.8778092Z npm ERR! ----------
2024-03-21T10:22:36.8778200Z npm ERR! 
2024-03-21T10:22:36.8778333Z npm ERR! Platform: win32 (10.0.20348)
2024-03-21T10:22:36.8778485Z npm ERR! Cypress Version: 4.2.0
```
So, we decided to upgrade the cypress according to node version
On installing any version of cypress grater than 4.12.1 , we are getting below error in local
```
 PS C:\Angular-Project> npm install cypress@8.1.0 --save-dev

> cypress@8.1.0 postinstall C:\Angular-Project\node_modules\cypress
> node index.js --exec install

C:\Angular-Project\node_modules\cypress\node_modules\is-installed-globally\index.js:12
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Angular-Project\node_modules\cypress\lib\util.js:43:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    
    
    npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@5.6.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@5.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Any solution please?, blocked for more than a week
