### ISSUE TITLE
Array in environment variables CYPRESS_BLACKLIST_HOSTS, CYPRESS_testFiles not handled correctly

### ISSUE THREAD

**Issue by tobiashinz** [cypress-io/cypress#6810]
# Current behavior:
Setting multiple hosts via the environment variable `CYPRESS_BLACKLIST_HOSTS` as an array leads to them not picked up corretly.

Example:

```bash
export CYPRESS_BLACKLIST_HOSTS=["www.google-analytics.com","*.hotjar.com"]
```

The environment variable is always handled as a string

### Desired behavior:
The desired behavior is to analyze if an array was provided and handled each item separately.

### Test code to reproduce
```bash
export CYPRESS_BLACKLIST_HOSTS=["www.google-analytics.com","*.hotjar.com"]

cypress open
```

### Versions

Node.js Version 12.8.1
Cypress Version 4.1.0

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-189) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Can confirm, this is resolved as a string when passed as an array in via environment variables. 

```
CYPRESS_BLACKLIST_HOSTS=["www.google-analytics.com","*.hotjar.com"] cypress open
```

<img width="553" alt="Screen Shot 2020-03-23 at 4 36 03 PM copy" src="https://user-images.githubusercontent.com/1271364/77305552-9a1c0800-6d24-11ea-9c74-f6c8f3bbebfd.png">

This is the only configuration value passable via `CYPRESS_` that accepts a non string or number, so I imagine we're just not handling it at all.

**Comment by JosiahOne** [comment]
Looks like there is at least one other array-based CYPRESS_ env var that behaves incorrectly: `CYPRESS_testFiles`.

`CYPRESS_testFiles="[\"**/196*\", \"**/475*\", \"**/476*\"]" npx cypress open`

![Screen Shot 2020-07-16 at 1 57 24 PM](https://user-images.githubusercontent.com/2743835/87705688-48ccd400-c76c-11ea-845b-1ef41c9f6fcf.png)

**Comment by dmoini** [comment]
Would I be able to work on this issue? If so I had a few questions since I am new at contributing open source.
1) Where should I look in the codebase to address this issue, specifically where environment variables are parsed?
2) How would I be able to debug and test my changes locally?

**Comment by jennifer-shehane** [comment]
@dmoini Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) for general guidance on running changes and tests locally. Generally, part of the work to parse env vars prefixed with `CYPRESS_` is done in our `config.js` here https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/config.js#L930:L930
