### ISSUE TITLE
CypressError: Timed out retrying: Expected to find element: '#name', but never found it.

### ISSUE THREAD

**Issue by archanahm** [cypress-io/cypress#6811]
Hi ,

I am facing timeout issue running cypress test in circle ci .

below is my HTML 

```html
<form id="new-firmware-image-form" class="form _2Gc1lUsI1nsEgxQUQbSMFO">
  <div class="stack-panel _1ymm4z8MDZqYQmnUWe9GZI vertical gutter form-controls">
     <label class="formLabel _2MvCRziMA8n3GScnUvYDg3">
        <div class="stack-panel _1ymm4z8MDZqYQmnUWe9GZI horizontal gutter content">
            <input id="name" name="name" maxlength="128" type="text" class="textbox            _1gUJmIoz_Ch9J6ReOuQEjz" value="">
            <div class="_22txD77MIM87j_XKmBPzE5 small dialog-error">&nbsp;</div
    < label/>
```

My code to get the name text box element .

```js
 get firmwareName() {
        return cy.get("#new-firmware-image-form").within(el => {
            cy.get("#name");
        });
    }
```

Issue :

works perfectly fine in local run.
Fails with below error in CI 
```
CypressError: Timed out retrying: Expected to find element: '#name', but never found it.
```

Dont want to use `cy.wait()` 

Please help me how can i solve this ?

**Comment by jennifer-shehane** [comment]
Please go through our steps for debugging why something fails locally versus in CI: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

I can't recreate this behavior with the HTML and test code provided. 

`index.html`

```html
<html>
<body>
<form id="new-firmware-image-form" class="form _2Gc1lUsI1nsEgxQUQbSMFO">
  <div class="stack-panel _1ymm4z8MDZqYQmnUWe9GZI vertical gutter form-controls">
    <label class="formLabel _2MvCRziMA8n3GScnUvYDg3">
      <div class="stack-panel _1ymm4z8MDZqYQmnUWe9GZI horizontal gutter content">
        <input id="name" name="name" maxlength="128" type="text" class="textbox_1gUJmIoz_Ch9J6ReOuQEjz" value="">
        <div class="_22txD77MIM87j_XKmBPzE5 small dialog-error">&nbsp;</div> 
      </div>
    <label />
  </div>
</form>
</body>
</html>
```

`spec.js`

```js
it("test", () => {
  cy.visit('index.html')
  cy.get("#new-firmware-image-form").within(el => {
    cy.get("#name")
  })
})
```

<img width="829" alt="Screen Shot 2020-03-23 at 6 37 38 PM" src="https://user-images.githubusercontent.com/1271364/77315161-6dbcb780-6d35-11ea-8464-b2967268cb58.png">

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by archanahm** [comment]
That is quick Response Thanks @jennifer-shehane .
As i said ,
<img width="381" alt="Screenshot 2020-03-23 at 12 18 50" src="https://user-images.githubusercontent.com/13199505/77316558-87dca280-6d01-11ea-98d5-48fcbcfb5ac8.png">
 these is piece of code for which it fails in CI every time . where as in local i don't see any issue it works perfectly fine.
I am not sure what more information i can provide here as i am also unsure why is it failing ONLY in ci.
I went through debugging step but no luck . I have attached Screen shot if that helps to have look

**Comment by AndersonZacharyT** [comment]
Seen a lot of this too! Curious if anyone has any insights

**Comment by PrakashDahal** [comment]
There is a package in cypress called as waitUntil. The link is [here](https://www.npmjs.com/package/cypress-wait-until) 
I am also looking for the solution of this problem.

**Comment by devamani83** [comment]
I am facing the same issue. All of my test cases are throwing the following exception after the Azure AD login is successful.  I tried to add wait in the test cases but they did help to resolve the issue.  Please help me out to resolve this issue. 
![image](https://user-images.githubusercontent.com/13065329/104326916-41d31400-54b8-11eb-963c-030ef0383e38.png)

**Comment by PrakashDahal** [comment]
> ![image](https://user-images.githubusercontent.com/13065329/104326916-41d31400-54b8-11eb-963c-030ef0383e38.png)

---
## Some of the solutions that ma help you are given below:

* #### Generally Id is unique throughout the page, if it is unique then you can just use id selector i.e.  ```cy.get('#app-name').contains('Recon')```

**Comment by devamani83** [comment]
I tried that one already prior to use 'h3#app-name' but that did not help me to resolve this issue. I opened an another issue for this error but it was closed without the final solution. 

https://github.com/cypress-io/cypress/issues/14502

**Comment by devamani83** [comment]
I have set the "chromeWebSecurity": false in the Cypress.json file.

**Comment by haase1020** [comment]
I am running into the same issue with GitHub actions - the test passes locally but fails in CI - I am interested in what a solution could be!

**Comment by Hakizu** [comment]
The only workaround I discovered until is to use a `className` instead to access the element with `cy.get`
For instance: 
![image](https://user-images.githubusercontent.com/35292022/106881850-546af280-66de-11eb-8d0c-b3efe434431d.png)

**Comment by sarainatera** [comment]
I had a similar problem. I solved it by getting the element by a selector or class instead of its id.

I went from:

`cy.get('#mat-options-text').click()`

to

`cy.get('mat-options').click()`
