### ISSUE TITLE
dtslint failing on TypeScript@next

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6814]
Currently blocking our builds on CircleCI

```
yarn lerna exec  --scope cypress "yarn dtslint"
```

Installs all versions of TypeScript including `typescript@next` and fails

https://circleci.com/gh/cypress-io/cypress/287117

<img width="1342" alt="Screen Shot 2020-03-23 at 9 24 28 AM" src="https://user-images.githubusercontent.com/2212006/77321428-8f438200-6ce8-11ea-8ffd-e9adf8095156.png">

**Comment by jennifer-shehane** [comment]
A bunch of people have opened issues about how using @next is very fragile in dtslint. Someone suggested using your version of typescript:

```
dtslint --localTs node_modules/typescript/lib
```
