### ISSUE TITLE
Allow chaining "blur" off "cy"

### ISSUE THREAD

**Issue by lunaboona** [cypress-io/cypress#6815]
### Current behavior:

Currently, the "blur" command can only be chained from an element that is currently focused. Sometimes, this can lead to the developer having to write multiple "cy.get()" expressions since an action in one element might focus another element.

### Desired behavior:

Chaining "blur" off "cy" should automatically blur all focused elements on the page.

**Comment by jennifer-shehane** [comment]
You can currently do this with: 

```js
cy.focused().blur()
```

Only one element can have 'focus' at a time, so it could never 'blur all focused element**s**'

Adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
