### ISSUE TITLE
Cypress reload when I open a local Files

### ISSUE THREAD

**Issue by atemor** [cypress-io/cypress#6816]
I have write a test file with differents `it()` accross my `describe()`

During the test, I visit several website page threw the `it()` and store one variable that I want to use accross all my test.

When I open webpage the variable is store accross all my test.

BUT when I open a `local.html` file, cypress runner reload and I lose the value of my variable

```js
describe('My test', () => {

  it('Test one', () => {
    cy.visit('www.google.com')
    const variable = 'Hello'
    cy.log(variable) => log Hello
  });

  it('Test two', () => {
    cy.visit('www.yahoo.com')
    cy.log(variable) => log Hello
  });

  it('Test Three', () => {
    cy.visit('cypress/fixtures/Mails/candidateActivePropositionFromClient.html') // cypress reload here
    cy.log(variable) => log Null
  });
});
```

**Comment by jennifer-shehane** [comment]
You'll need to store the value outside of the test file because Cypress wipes all state when visiting a new cross domain page. 

There's a workaround for storing variables across cross domain visits explained here: https://github.com/cypress-io/cypress/issues/6562#issuecomment-595042151

**Comment by atemor** [comment]
thx
