### ISSUE TITLE
Flaky Percy snapshot in Desktop-GUI configuration panel

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6817]
### Current behavior:

The diff is failing because it is animating open. https://percy.io/cypress-io/cypress/builds/4608760

### Desired behavior:

Look at if there is some way to tell the animation is over before taking percy snapshot.

### Versions

4.2.0

**Comment by bahmutov** [comment]
Interesting. The "Configuration - Click" snapshot shows the same half-expanded settings element

<img width="1360" alt="Screen Shot 2020-03-23 at 4 02 52 PM" src="https://user-images.githubusercontent.com/2212006/77358363-1a8c3a00-6d20-11ea-8b91-9d8a5fc39b4f.png">
