### ISSUE TITLE
Scrolling element in the viewport when clicking on step in reporter is too agressive

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#682]
Applies to all versions of Cypress

Imagine simple test with two steps:
- get parent element
- find child element

When we click on the second step in the reporter (on the left), it scrolls so aggressively, that it puts the top edge of the child element at the top of the viewport. Thus the parent element is now invisible. Think submit button and the form around it - I would like to still see the form when clicking on the submit button step.

Here is an example. First element is a demo div with some graphics and "Next step" button. At first I see the demo div and plan to click on the "next step" in the reporter

<img width="1274" alt="screen shot 2017-09-22 at 10 53 47 am" src="https://user-images.githubusercontent.com/2212006/30750730-4660c1f2-9f85-11e7-8a9b-aed7b8e49925.png">

The "next step" button element is *already visible*, but when I click on the reporter, it scrolls it way up, hiding the demo block it is inside of. And since the "next step" button changes the appearance of the demo block, I do not see right away how it changed it.

<img width="1274" alt="screen shot 2017-09-22 at 10 53 57 am" src="https://user-images.githubusercontent.com/2212006/30751147-7fdb84f2-9f86-11e7-8d08-bf6f7d6879db.png">

A better solution for scrolling would be
- if the element is already fully visible in the viewport when clicking do not scroll
- otherwise scroll
    - scrolling so that the element is in the middle of the viewport is best

**Comment by jennifer-shehane** [comment]
Closing as part of https://github.com/cypress-io/cypress/issues/871 which will allow the user to control things like this themselves.
