### ISSUE TITLE
[Cypress] How to resolve "For security reasons, framing is not allowed" alert in chrome

### ISSUE THREAD

**Issue by madhant** [cypress-io/cypress#6820]
### Current behavior:

I’m automating E2E customer flow in chrome browser using cypress and when I login and navigate to the dashboard page, the following alert is thrown and the execution stops when I click ‘Ok’.
#### Alert: "For security reasons, framing is not allowed"
- When I run the test, cypress opens the browser with command logs pane in the left and execution in the right.
- I tried running in headless mode and same error is thrown.
- I have also tried adding the flag "chromeWebSecurity": false in cypres.json and it didn't work.
- I read through the cypress docs on web security https://docs.cypress.io/guides/guides/web-security.html#Limitations and am unable to resolve. Can you guys please help me on this ?

### Versions
Cypress: 4.1.0
Chrome Version 80.0.3987.132
OS: Mojave 10.14.6

**Comment by jennifer-shehane** [comment]
This alert is likely  specific to the website you are testing. The application under test likely has some code similar to the below which alerts the user whenever the application is loaded within an iframe. Cypress runs the application under test within an iframe.

```
if (!(parent) && top != self) {
    top.location.replace(document.location);
    alert('For security reasons, framing is not allowed.');
}
```

You should only test applications that are under your control - so we suggest updating the code of the application to allow prevent the alert when running within Cypress - something like:

```js
if (!window.Cypress) {
  if (!(parent) && top != self) {
    top.location.replace(document.location);
    alert('For security reasons, framing is not allowed.');
  }
}
```

If the application code cannot be changed, you can stub try stubbing the alert - I'm not sure exactly what the application is calling here, so I can't give an exact example of how this may work but there are some examples here: https://github.com/cypress-io/cypress-example-recipes
