### ISSUE TITLE
Starting web server from within Cypress test

### ISSUE THREAD

**Issue by osmanamjad** [cypress-io/cypress#6834]
### Current behavior:
I want to execute a powershell command to start a service within my cypress test. I tried using `cy.exec("Start-Service NameOfService")` but that just doesn't work, and it doesn't give any error message either.

### Desired behavior:

I want to start a service using powershell command from within cypress test.

### Test code to reproduce
```
cy.exec('Start-Service AnyService')
```

### Versions
Cypress version 3.3.2
Operating system: Windows 10 Pro
Browser: Google Chrome

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by osmanamjad** [comment]
> I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed.
> 
> Other than that, we have several tests around `cy.exec()`, so we would need more information about what you are running, how you're running it, what doesn't 'it doesn't work' mean exactly?

I updated to the latest version of Cypress and the problem is still persisting. 

My test is simply trying to start/restart a service; this is my test code with an example service:
cy.exec("Restart-Service GoogleChromeElevationService")

I've attached the error code I get when I run this test. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/50644787/77567105-0caff380-6e9d-11ea-905e-9f27a5897bff.png)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
