### ISSUE TITLE
SAML sso issue 

### ISSUE THREAD

**Issue by NilukaSripalim** [cypress-io/cypress#6838]
Related #https://github.com/cypress-io/cypress/issues/6837
@jennifer-shehane if the issue with app, so why the issue is not occurring when try with manually, do you have any idea to avoid page reload, It is great if you can give me any clue .

**Comment by NilukaSripalim** [comment]
or how we check whether we have add any code to page reload,

**Comment by jennifer-shehane** [comment]
**Do not** open new issues for existing issues. Comment in the existing issue and we will consider reopening. This creates a lot of unnecessary noise.
