### ISSUE TITLE
Cypress' browser intermittently failing to update `set-cookie` header

### ISSUE THREAD

**Issue by bsodmike** [cypress-io/cypress#6839]
In our Cypress codebase we have custom command to aid logging in a test user against the app backend

I added a delay during troubleshooting this particular issue.

```javascript
Cypress.Commands.add("fakeLogin", () => {
    cy.request('POST', '/test_utils/fake_login', {contact_id: 1})
      .then((response) => {
          expect(response.status).to.eq(204);
          console.log('Headers: %O', response.headers);
      });
});
```

### Current behavior:

Notice that I am logging the `cy.request` response header to the console, which looks like this:

```
cache-control: "no-cache"
referrer-policy: "strict-origin-when-cross-origin"
set-cookie: Array(1)
0: "_app_session_id=42b9c34bb4e3830c7f0cb5ff80633dc2; path=/; expires=Wed, 08 Apr 2020 11:41:18 -0000; HttpOnly"
length: 1
__proto__: Array(0)
x-content-type-options: "nosniff"
x-download-options: "noopen"
x-frame-options: "SAMEORIGIN"
x-permitted-cross-domain-policies: "none"
x-request-id: "e19814be-c8ac-431c-8bf6-10744cf9d5d5"
x-runtime: "0.453860"
x-xss-protection: "1; mode=block"
```

Intermittently, some of these login attempts fail, leaving the Cypress browser in a logged-out state, causing tests to fail.

Comparing against the session cookie in Chrome inspector, I can confirm that the cookie stored has not been updated whenever a spec fails incorrectly due to being logged-out.

### Desired behavior:

Cypress should always update any cookies defined in a `set-cookie` header.

### Versions

Cypress: v4.2.0
Browser: Chromium 82
Node: v12.16.1

**Comment by flotwig** [comment]
@bsodmike 4.3.0 contained some cookie fixes that may apply to your situation, can you try updating to 4.3.0 and see if the issue persists? https://docs.cypress.io/guides/references/changelog.html#4-3-0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
