### ISSUE TITLE
cy.url() and cy.location('href') does not return the correct URL of page

### ISSUE THREAD

**Issue by HussamAlHunaiti** [cypress-io/cypress#6840]
### Current behavior:
- According to the documentation, `cy.url()` should produce a string. I wanted to capture the current URL into a variable and then reference it after I run a custom Cypress command.

### Desired behavior:
- When try to save current URL in variable: 
```js
cy.url().should((href: string) => pom.currentHref = href);
cy.location('href').should((href: string) => pom.currentHref = href);
```
It's return the chrome browser URL "file path".

- Expected to return the current page URL. 

### Test code to reproduce

```js
cy.url().should((href: string) => pom.currentHref = href);
cy.location('href').should((href: string) => pom.currentHref = href);
```

### Versions
3.8.3

#Chrome

**Comment by jennifer-shehane** [comment]
I can't recreate this in the current 4.2.0 version of Cypress. Please provide a **fully *failing* test example** that we can run and see where `pom.currentHref` is returning incorrect URL.

```js
const pom = {}

it('test', () => {
  cy.visit('https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell')
  cy.url().should((href) => pom.currentHref = href).then(() => {
    expect(pom.currentHref).to.eq('https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell')
  })
  cy.location('href').should((href) => pom.currentHref = href).then(() => {
    expect(pom.currentHref).to.eq('https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell')
  })
})
```

<img width="436" alt="Screen Shot 2020-03-26 at 4 30 46 PM" src="https://user-images.githubusercontent.com/1271364/77634336-2b86b680-6f7f-11ea-8c10-3fd96673386b.png">
