### ISSUE TITLE
How can I select an element duplicated in a list?

### ISSUE THREAD

**Issue by eGoudi** [cypress-io/cypress#6841]
Hi,
I present the HTML list below:

<img width="802" alt="Capture d’écran 2020-03-24 à 18 52 21" src="https://user-images.githubusercontent.com/58534476/77534719-74643f80-6e99-11ea-846f-fc19a7f3fc06.png">

Now I want to select the first one using just the following command which I call via Gherkin in my test file (.feature):

When(I select {string} in {string} list, (string, field) => { cy.get(select[name="${field}"]`).select(string, { force: true }); });

But I got this following result:

<img width="620" alt="Capture d’écran 2020-03-24 à 19 00 18" src="https://user-images.githubusercontent.com/58534476/77534784-95c52b80-6e99-11ea-9e1c-b13ce8e74803.png">

Can someone Help me?

**Comment by jennifer-shehane** [comment]
Do not open new issues that are already opened. I've already answered your question here: https://github.com/cypress-io/cypress/issues/6830

Issues are not the proper place to ask questions and they will be closed. See my other comment.
