### ISSUE TITLE
Move type-level tests from dtslint to tsd

### ISSUE THREAD

**Issue by CypressJoseph** [cypress-io/cypress#6848]
### Current behavior:

- `dtslint` induces test flake, sometimes due to external dependencies (failing even on latest versions of the published types for foundational tools like jQuery, Bluebird, etc). More broadly, relying on `dtslint` causes churn (since sometimes even if you do end up responding to failures in `ts@next`, they may be resolved by the time new versions stabilize.)

### Desired behavior:
- Type-level validations are expressed as `tsd` test cases, and `dtslint` is run more narrowly in CI over a single installation of TS

1. Run `dtslint` only over a local install of typescript.

I don't have a lot of specific guidance here. The invocation of `dtslint` with local typescript is well-documented, and whatever 3.x typescript circle is using should be fine. A puzzle there might be how to feed `dtslint` the right path to local TS in CI.

2. Migrate from `dtslint` to `tsd`.

[`tsd`](https://github.com/SamVerschueren/tsd#usage) is a type-level testing tool that provides a specialized DSL for expressing type-level assertions. The type validations have a different form, and the test cases are actually code that is run. The translation seems reasonably straightforward, and it does seem like named test cases might have a positive effect on overall structure.

**Comment by CypressJoseph** [comment]
Note that we don't necessarily need to do these in lockstep. If we're able to narrow `dtslint` effectively, it may no longer be as important it to translate to tsd expectations immediately (although again I think it would be worthwhile to do for its own sake.)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
