### ISSUE TITLE
Missing 'some' command that checks some elements in an array

### ISSUE THREAD

**Issue by librehat** [cypress-io/cypress#6859]
This is a feature request.

### Current behavior:

Currently there is no way to do `some` similar to the JavaScript Array method which checks that if any one of them passes the assertions

### Desired behavior:

```js
cy.get('tbody > tr').some(($tr) => expect($tr).contain('hello') && expect($tr).contain('world'));
```
passes when any `tr` meets the assertions (the syntax is for illustration) but fails when none of them does. This is useful when the criteria cannot be expressed in a single assertion (because for example, if we want to test that this row has two such cells)

### Versions

Cypress 4.1.0
macOS

**Comment by jennifer-shehane** [comment]
This can do what you want essentially, but basically you can use any JavaScript you want in Cypress tests so there are likely a lot of ways to test this without a new command. 

```html
<html>
<body>
  <ul>
    <li>hello world</li>
    <li>bye world</li>
  </ul>
</body>
</html>
```

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('li').should(($lis) => {
    const allLIsText = $lis.text() // hello worldbye world
    expect(allLIsText).to.include('hello')
    expect(allLIsText).to.contain('world')
  })
})
```

**Comment by librehat** [comment]
I think you misunderstood my question, the HTML is more like

```html
<html>
<body>
<table>
<tbody>
  <tr>
    <td>First</td>
    <td>12</td>
  </tr>
  <tr>
    <td>Second</td>
    <td>10</td>
  </tr>
</tbody>
</table>
</body>
</html>
```

And I want to find if there is a `<tr>` whose descendants have both `<td>` that I'm interested. In other words, trying to find `First` and `10` should fail, but `First` and `12` should succeed.

`cy.get('tbody > tr')` gives me the array of elements (both <tr>) and if I simply check that array, it'll always pass for `('First', 10)` because the second row has `10`.

**Comment by jennifer-shehane** [comment]
Thanks, please include all relevant HTML upfront. The below should work - can do anything in JavaScript.

`index.html`

```html
<html>
<body>
  <table>
    <tbody>
      <tr>
        <td>First</td>
        <td>12</td>
      </tr>
      <tr>
        <td>Second</td>
        <td>10</td>
      </tr>
    </tbody>
  </table>
</body>
</html>
```

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('tbody > tr').should(($trs) => {
    const someTextCheck = $trs.toArray().some((tr) => {
      return tr.textContent.includes('First') && tr.textContent.includes('12')
    })

    expect(someTextCheck).to.be.true
  })
})
```

Please check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by librehat** [comment]
thank you!
