### ISSUE TITLE
XHR Form-Data requests turned into application/json?

### ISSUE THREAD

**Issue by pmelab** [cypress-io/cypress#6862]
### Current behaviour:
Our current project uses [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) to communicate with a GraphQL API. Uploading files via mutations use [GraphQL multipart requests](https://github.com/jaydenseric/graphql-multipart-request-spec). When running in cypress, these requests are turned into normal `POST` `application/json` requests without the form and file data.

### Desired behaviour:

The form-data requests remain form-data requests.

### Versions
Cypress 4.2.0 - Chrome-based browsers. **Does not happen in Firefox beta!**

### Test code to reproduce

I did not have time yet to set up a full example. I was hoping that someone could tell me if this should work in theory. #687 suggests that the `XMLHttpRequest` is modified, so I suspect the problem is there and might be resolved with the new network stubbing. The fact that it works in Firefox (which probably has some differences on the network level) supports that.

Request when executed manually:
<img width="814" alt="manual" src="https://user-images.githubusercontent.com/501415/77724808-2adc3780-6ff4-11ea-85ca-51850ff5e2ba.png">

Request when executed by Cypress:
<img width="809" alt="cypress" src="https://user-images.githubusercontent.com/501415/77724863-48110600-6ff4-11ea-941c-42be1b29f563.png">

**Comment by jennifer-shehane** [comment]
Please comment in this issue with a reproducible example so we can investigate the issue.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by sixnames** [comment]
Hi @jennifer-shehane ! I'm experiencing the same issue.
Actualy, @pmelab described whole problem. 

Request sent manually:
<img width="281" alt="Google Chrome_2020-04-14 10-32-24" src="https://user-images.githubusercontent.com/6926510/79197924-4a1ff500-7e3b-11ea-811f-eb7d9bd4e3ac.png">

Request sent from cypress:
<img width="772" alt="1f19739a376e63584292926b8e13adfe" src="https://user-images.githubusercontent.com/6926510/79197675-d382f780-7e3a-11ea-9c51-a3c06d8892ff.png">

**Comment by jennifer-shehane** [comment]
@sixnames Can you provide a fully reproducible example? Some Cypress test code we can run ourselves to see the issue? Thanks!

**Comment by sixnames** [comment]
Thank you for answer, @jennifer-shehane ! I've created a simple example. And, it works :))). Now i know that the problem in my project. 
[Example](https://github.com/sixnames/cypress-apollo-file-upload-example)

**Comment by pmelab** [comment]
@sixnames Do you know _what_ the problem was? Perhaps it is the same issue here.

**Comment by sixnames** [comment]
@pmelab No, I don't. I will add the solution, if I found it out.
What stack do you use?
Mine:
NextJs / api routes with middlewares for DB connection
apollo-server-micro and apollo-upload-client
I suspect that the problem in the middlewares, in my case.

**Comment by sixnames** [comment]
@pmelab Problem was in cypress-graphql-mock, in my case.
It ruins file upload request, some how.
I use this plugin for mocking authorisation process. Other requests goes to the server. So, in my case, solution was to create separate Describe block with manual authorisation.
