### ISSUE TITLE
Cypress stuck when run by Module API `cypress.run()` on Windows.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#6863]
## Current behavior:

1. Run by Module API:

Screenshot:
![fail](https://user-images.githubusercontent.com/22906174/77730886-b7124d00-703c-11ea-9d0c-f4444e95a235.PNG)

**And cypress will stuck there forever.**

2. Run by commond line:
Can't reproduce and program exit.

Log:
```
C:\Users\kzdatd\Desktop\cypress-foo>npx cypress run

Could not find a Cypress configuration file, exiting.

We looked but did not find a cypress.json file in this folder: C:\Users\kzdatd\Desktop\cypress-foo
libpng warning: iCCP: cHRM chunk does not match sRGB

C:\Users\kzdatd\Desktop\cypress-foo>
```

### Desired behavior:

When run success or fail, program should exit.

### Test code to reproduce

1. ```npm install cypress```
2. copy example code from [docs.cypress.io](https://docs.cypress.io/guides/guides/module-api.html#cypress-run), and save to a js file, like foo.js
```js
const cypress = require('cypress')

cypress.run({
  spec: './cypress/integration/examples/actions.spec.js'
})
.then((results) => {
  console.log(results)
})
.catch((err) => {
  console.error(err)
})
```
3. run commad: ```node foo.js```

### Versions
Cypress:  4.2.0
node: v12.16.1
OS: Windos10 64

**Comment by jennifer-shehane** [comment]
Do you have a `cypress.json` within the `C:\Users\kzdatd\Desktop\cypress-foo` folder as the error indicates? 

This file is required. It can be an empty json Object, but the file needs to be there. 

`cypress.json`

```js
{}
```

**Comment by JFRabbit** [comment]
@jennifer-shehane the issue is "stuck",  whether or not this file exists, program should exit after run success of fail.

If cypress.json exit, no error happened, still stuck. 
If no this file, program throw an error but not exit, and stuck forever.

I reproduce this issue on windows,  and only use ```cypress.run()```, on Mac can't reproduce.
