### ISSUE TITLE
Unable to trigger Cypress events on a Google Maps Angular application

### ISSUE THREAD

**Issue by Ryguy1979** [cypress-io/cypress#6875]
### Current behavior:

Events triggered with the mouse will successfully initiate the opening of a tooltip on the UI, but various attempts with Cypress to execute those same events do absolutely nothing despite Cypress UI triggering what looks to be a successful test.

Angular 8 code:  

```js
addDataLayerListeners(dataLayer: google.maps.Data, equipmentLayer: google.maps.Data): void {
    dataLayer.addListener('click', (event) => {
      console.log('text to check Cypress');
      dataLayer.revertStyle();
      dataLayer.overrideStyle(event.feature, { icon: '/assets/DefaultHoverPin.png'});
      this.infoWindow.setContent(this.getInfoWindowContent(event));
      this.infoWindow.setPosition(event.feature.getGeometry().get());
      this.infoWindow.setOptions({pixelOffset: new google.maps.Size(0, -30)});
      this.infoWindow.open(this.map);
    });
```

### Desired behavior:

I would expect to be able to interact with the map elements by triggering their mouse events in Cypress, despite those elements being embedded on the canvas of the map.

### Test code to reproduce

Cypress test code: 

```js
it('should show map center based on current location and open dealer within that location', () => {
    cy.window().then(($window) =>  {
      cy.stub($window.navigator.geolocation, 'getCurrentPosition', (callback) => {
        return callback({ coords: { latitude: 35.0844, longitude: -106.6504 } });
      });
    });

    cy.get('[data-cy="dealerInfoWindow"]').should('not.be.visible');
    cy.get('#btn-locate').click();
    // unsuccessful attempts with various events
    // cy.get('[data-cy="map-container"]').trigger('click', 551, 180);
    // cy.get('[data-cy="map-container"]').trigger('mousedown', 551, 180);
    // cy.get('[data-cy="map-container"]').trigger('mouseover', 551, 180);
    cy.get('[data-cy="map-container"]').click(551, 180);
    cy.get('[data-cy="dealerInfoWindow"]').should('be.visible');
    cy.get('[data-cy="dealerInfoWindow"] .dealerName').should('have.text', 'Santa Fe LLC');
  });
```

Screenshot of what Cypress does:

![Cypress click issue](https://user-images.githubusercontent.com/31529454/77788229-e02be100-702e-11ea-8ccd-5621517c3244.png)

**Comment by jennifer-shehane** [comment]
Without being completely familiar with the code or being provided the code itself, this is pretty difficult to debug here. It does look like Cypress is issuing a click (and the circle is drawing there? again, I'm not familiar enough to know). 

But the next assertion is failing - to get the `[data-cy='dealerInfoWindow']` - what code is responsible for showing this `dealerInfoWindow` and what is it listening to do show this?

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example (a repo of the example) and we will consider reopening the issue.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by Ryguy1979** [comment]
I can fork your test branch and give you some more of the framework, but you are essentially seeing what I am.

```
cy.get('[data-cy="map-container"]').click(551, 180);
cy.get('[data-cy="dealerInfoWindow"]').should('be.visible');
```

These 2 events are linked.  The click should directly open that `dealerInfoWindow` only it does not.  I can mouse click it from within the UI, get my `console.log('text to check Cypress');` I placed for testing this Cypress implementation and the element opens.  Cypress, for whatever reason, does not open it despite stating it successfully clicks there.

**Comment by Ryguy1979** [comment]
In rebuilding this within a `cypress-test-tiny` fork, I pulled all of our OAuth login components and can no longer recreate.   I am uncertain what within an OIDC implementation would be preventing events on the webpage, but I have another avenue to try.  If I cannot track it down, I will see how much of our OAuth implementation I can actually share.

**Comment by sandeepvortexa** [comment]
@Ryguy1979  Did you solved this issue? I am in kind of similar situation where I have a canvas of map and need to click on co-ordinates. But cypress (v8.4.0) doesn't fire event which trigger the another window pop up.
