### ISSUE TITLE
break up task errors into newer err object (with docsUrl)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6878]
### Current behavior:

This `cy.task()` error is just a string generated here: https://github.com/cypress-io/cypress/blob/dae76a8ec0a149d5f4ca4fbe4d15bea1b5f7449d/packages/server/lib/task.js#L19

<img width="498" alt="Screen Shot 2020-03-30 at 1 34 02 PM" src="https://user-images.githubusercontent.com/1271364/77884510-38f7b580-728b-11ea-8f43-c0efc8df099e.png">

### Desired behavior:

 Should be transformed into our new error objects which will display a 'learn more' link and have better code highlighting. 

### Test code to reproduce

```js
it('failed', () => {
  cy.task('error', 'foo')
})

it('timed_out', () => {
  cy.task('wait', null, { timeout: 100 })
})
```

### Versions

4.3.0 (pre-release)

*Edited to link to correct JS file*

**Comment by sainthkh** [comment]
The line is decaffeinated and it's here: https://github.com/cypress-io/cypress/blob/dae76a8ec0a149d5f4ca4fbe4d15bea1b5f7449d/packages/server/lib/task.js#L19
