### ISSUE TITLE
chrome-error://chromewebdata/

### ISSUE THREAD

**Issue by ilianabe** [cypress-io/cypress#6880]
### Current behavior:

In my current test I have a button and on click I need to navigate to a different page.
I have disabled chrome security by this:

on cypress.json
`  "chromeWebSecurity": false,`
and I have followed the issue #1951 (https://github.com/cypress-io/cypress/issues/1951)
and added this on my `plugins/index.js`

```js
on('before:browser:launch', (browser = {}, args) => {
  if (browser.name === 'chrome') {
    args.push('--disable-site-isolation-trials');

    return args;
  }
});
```

So now when the button is clicked I don't get the classic cross-origin error but instead I am getting this:
`chrome-error://chromewebdata/` and the new page doesn't load.

### Desired behavior:

Click the button on my site, navigate to the new superdomain and execute some code.

### Versions
Ubuntu 18.04.4
Cypress 3.8.2
Chrome 80

**Comment by jennifer-shehane** [comment]
Duplicate of #4220

**Comment by thyvutha** [comment]
https://policies.google.com/terms[]()
