### ISSUE TITLE
If we cannot connect to Chrome via RDP we should re-launch the browser

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6884]
Cypress v4.20

Sometimes we randomly get "Failed to connect to Chrome" error, like this
<img width="1140" alt="Screen Shot 2020-03-30 at 4 52 13 PM" src="https://user-images.githubusercontent.com/2212006/77963184-e8905000-72aa-11ea-89a6-4aa5e7fc82f5.png">

Since the error is pretty random, I believe this is due to RDP port being blocked or some transient thing. We do retry to connect, allowing the browser to start, but seems in some cases the browser is completely unable to receive our connection.

I have come up with a way to simulate the situation in https://github.com/bahmutov/cypress-native-chrome-code-coverage-example/tree/change-rdp-port branch `change-rdp-port`. Its plugin replaces the RDP port Cypress wants with random number

```js
// cypress/plugins/index.js
// on event 'before:browser:launch'
  // find how Cypress is going to control Chrome browser
  // and change the port number
  const rdp = 40000 + Math.round(Math.random() * 25000)
  console.log('plugin: new RDP port', rdp)
  // have to replace an item in the array without changing the reference
  launchOptions.args.forEach((arg, k) => {
    if (arg.startsWith('--remote-debugging-port')) {
      console.log('replacing "%s"', arg)
      launchOptions.args[k] = `--remote-debugging-port=${rdp}`
    }
  })

  console.log('updated browser arguments')
  console.log(launchOptions.args.join('\n'))

  return launchOptions
```

causing the same failure. 

<img width="1440" alt="Screen Shot 2020-03-30 at 4 48 42 PM" src="https://user-images.githubusercontent.com/2212006/77963444-5dfc2080-72ab-11ea-9c6a-4aa0c6a1fba4.png">

**Proposal:** in this case, we should kill the browser process, pick new RDP port and try again.

**Comment by jennifer-shehane** [comment]
You can recreate this if you open 2 instances of Cypress. Not sure it's relevant to what you're experimenting with, but it does annoy me. https://github.com/cypress-io/cypress/issues/5613

**Comment by flotwig** [comment]
Do you think this is a port collision issue, or what?

I think that this might not be the best idea because of how new browser processes interact with existing browser processes. In the case of #5613, relaunching the browser would open up a new window in the existing browser session each time the browser is relaunched, which would be pretty undesirable behavior imo.

**Comment by bahmutov** [comment]
Don’t we know the child browser process pid so we can kill it accurately before relaunching ?

**Comment by flotwig** [comment]
That was my first thought, but then I remembered that (for Chromium, at least) it will only use the launched process to connect to the existing browser process and launch a window there, then exit. So closing the child process won't close the window it created in an existing session.

**Comment by bahmutov** [comment]
Hmm so maybe it is a problem with previous chrome instance NOT exiting correctly, not with the new instant spawning

**Comment by flotwig** [comment]
In #5613's case it's having two copies of Cypress open that causes it. I've also seen GPO on Windows cause `--user-data-dir` to be ignored, so it launches in the users existing non-Cypress browser session.

Maybe it could make sense in CI only?

**Comment by bahmutov** [comment]
I wonder if we print list of all running processes on this error

**Comment by bahmutov** [comment]
Another user just commented that the first spec ran fine on CI, but the second could not connect. Points in favor of first browser not shutting down correctly, preventing connecting when we spawn the browser again.

Maybe if we cannot connect, we could use https://github.com/sindresorhus/ps-list to see if Chrome is hanging around and try to kill it. Or do it by default after shutting down the browser, instead of assuming it has exited.

**Comment by jennifer-shehane** [comment]
Yes, most recently I have seen this occur during `cypress run` in people's logs when there are multiple spec files in a run - never really happens on first open.
