### ISSUE TITLE
when parallelization，why don`t start multi cypress process

### ISSUE THREAD

**Issue by luogan210** [cypress-io/cypress#6886]
### Current behavior:
    now ,the doc says that  use ci mathines to parallelization,it is every hard to do,
   because it is complex,like we can open many browser tabs ,whe can not we start many 
   cypress process directly 

### Desired behavior:
  in my case ,i split test files into many parts ,every part run on a cypress process,
   why cypress won`t use multi cypress process to parallelization directly

**Comment by jennifer-shehane** [comment]
Cypress processes (each `cypress run`) should be run on a separate machine so that CPU is not maxed. We allow the user to run the processes where they need and want them to have the choice on how to execute across machines.

**Comment by luogan210** [comment]
> Cypress processes (each `cypress run`) should be run on a separate machine so that CPU is not maxed. We allow the user to run the processes where they need and want them to have the choice on how to execute across machines.

so，your meaning is   that user can start multi `cypress run` on one mathine?

**Comment by jennifer-shehane** [comment]
You **can* run multiple `cypress run` commands on one machine - you can open multiple tabs on your computer now and do this. But we do not recommend it because most machines do not have enough CPU to run multiple cypress/chrome/background processes at once.

**Comment by CSchulz** [comment]
We are running multiple cypress run commands in parallel on one machine and we encountering the issue that cypress crashes without any message or the x server isn't available.
