### ISSUE TITLE
The mochawesome reporter is not working with the cypress

### ISSUE THREAD

**Issue by senthkum** [cypress-io/cypress#6888]
### Current behavior:
I have installed package by running the command:

```
npm install --save-dev mocha.
npm install --save-dev mochawesome.
```

**cypress.json**
```json
{
    "defaultCommandTimeout": 4000,
    "pageLoadTimeout": 60000,
    "Environments": {
      "L-Env": ""
    },
    "chromeWebSecurity": false,
    "reporter": "mochawesome",
    "reporterOptions": {
      "reportDir": "/cypress-multiple-project/mochawesome-report",	
      "overwrite": false,
      "html": true,
      "json": true
    }

  }
```
  **package.json**

```json
{
  "name": "cypressmultipleproject",
  "version": "1.0.0",
  "description": "multi project setup",
  "main": "index.js",
  "scripts": {
    "OpenAmazon": "cd ./Amazon && cypress open",
    "OpenFlipkart": "cd ./Flipkart && cypress open",
    "OpenDemowebshop": "cd ./Demowebshop && cypress open",
    "test": "node_modules/.bin/cypress run",
    "runAmazon": "cd ./Amazon && cypress run",
    "runFlipkart": "cd ./Flipkart && cypress run",

    "runDemowebshop": "cd ./Demowebshop && cypress run",
    "Projectkey": "npm run runDemowebshop -- --record --key 8e58f1b5-01c8-435d-94a7-ed1a425fd8e7",
    "headTest": "npm run Projectkey -- --headed",
    "browser": "npm run headTest -- --browser chrome",
    "reportview": "npm run browser -- --reporter mochawesome",
    "ProductSuite": "npm run reportview -- --spec \"./cypress/integration/Categories-Modules/*\"",
    "SingleSuit": "npm run reportview -- --spec \"./cypress/integration/Categories-Modules/Books.js\""
  },
  "author": "Senthil",
  "license": "ISC",
  "devDependencies": {
    "chai": "^4.2.0",
    "cypress": "^4.2.0",
    "cypress-cucumber-preprocessor": "^2.2.0",
    "cypress-iframe": "^1.0.1",
    "mocha": "^7.1.1",
    "mochawesome": "^5.0.0"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
}
```
When I try to execute from the terminal it's giving me the below error.
![image](https://user-images.githubusercontent.com/46837197/78011771-c4f30580-738f-11ea-9ec8-8351663d5992.png)

My project folder structure below,
![image](https://user-images.githubusercontent.com/46837197/78011859-e3f19780-738f-11ea-9aac-fb6fbd384225.png)

![image](https://user-images.githubusercontent.com/46837197/78011917-f8359480-738f-11ea-9e00-bea1bf2809ee.png)

![image](https://user-images.githubusercontent.com/46837197/78011974-0b486480-7390-11ea-8f5e-97a35e5ee3c0.png)

![image](https://user-images.githubusercontent.com/46837197/78012014-1e5b3480-7390-11ea-930d-f954f10ab0e1.png)

**Comment by jennifer-shehane** [comment]
Cypress will look for the reporters installation at the paths specified - so 

- `projectRoot\mochawesome`
- `projectRoot\node_modules\mochawesome`

You'll have to install mochawesome within the Demowebshop directory as a workaround. 

OR...this is likely a better solution for what it looks like you're trying to do. In your `scripts`, always run `cypress` from the root `cypress-multi-project` path, then when you run, pass a specific `config-file`. So, your scripts would look like this. 

```json
  "scripts": {
    "OpenAmazon": "cypress open --config-file=OpenAmazon/cypress.json",
    "OpenFlipkart": "cypress open --config-file=OpenFlipkart/cypress.json",
    "OpenDemowebshop": "cypress open --config-file=OpenDemowebshop/cypress.json",

    "runAmazon": "cypress run --config-file=runAmazon/cypress.json",
    "runFlipkart": "cypress run --config-file=runFlipkart/cypress.json",
    "runDemowebshop": "cypress run --config-file=runDemowebshop/cypress.json"
  }
```

Then within each `cypress.json` configuration file, you would specify the directory that has the test files you want to run by setting the `integrationFolder`. 

```json
{
  "integrationFolder": "runDemowebshop/cypress/integration",
  "reporter": "mochawesome",
  "reporterOptions": {
    "reportDir": "./cypress-multiple-project/mochawesome-report",
    "overwrite": false,
    "html": true,
    "json": true
  }
}
```

This was you can share node_modules access.

**Comment by senthkum** [comment]
Hi Jennifer,

Thanks a lot for your response. I was able to execute the script with the given approach. But I was able to execute all the spec in a folder. I was not able to execute an individual spec. Could you please help me with executing the individual spec file. I have tried with below options but nothing worked.
"SingleScript": "npm run runDemowebshop --spec 'Books.js'"
"SingleScript": "npm run runDemowebshop --spec '.Books.js'"
"SingleScript": "npm run runDemowebshop --spec '/Books.js'"
"SingleScript": "npm run runDemowebshop --spec "Books.js""

**cypress.json:**
{
  "defaultCommandTimeout": 4000,
  "pageLoadTimeout": 60000,  
  "Environments": {
    "L-Env": "http://demowebshop.tricentis.com/"
  },

  "projectId": "p7n7io",

  "integrationFolder": "Demowebshop/cypress/integration/Categories-Modules/",
  "reporter": "mochawesome",
  "reporterOptions": {
  "reportDir": "./mochawesome-report",
  "overwrite": false,
  "html": true,
  "json": true
  }

}
**package.json**
  "scripts": {
    "runDemowebshop": "cypress run --config-file=Demowebshop/cypress.json",
    "SingleScript": "npm run runDemowebshop --spec 'Books.js'"
  },


![specExecution](https://user-images.githubusercontent.com/46837197/78223847-47580280-7513-11ea-9c2a-4d0db9333a10.jpg)












Thank
Senthil.M

**Comment by bahmutov** [comment]
@senthkum in general, please open a new issue when describing a different problem from the original, especially if the original issue has been closed. In your case, you forgot to separate _npm run arguments_ from the _npm run script_.

Instead of

```
npm run runDemowebshop --spec 'Books.js'
```

it needs to be

```
npm run runDemowebshop -- --spec 'Books.js'
```
