### ISSUE TITLE
Then function persists returned value

### ISSUE THREAD

**Issue by G0L0L** [cypress-io/cypress#6893]
### Current behavior:

Currently `than` command persist returned value.
```js
const div = cy.get('div')
div.then(() => 123)
div.then(el => console.log(el)) // this will print "123"
```

```js
const div = cy.get('div')
// div.then(() => 123)
div.then(el => console.log(el)) // this will print div element
```

One more example:
```js
const div = cy.get('div')
cy.wrap({}).then(() => 123)
div.then(el => console.log(el)) // this will print "123"
```

### Desired behavior:

I expect it to work as Promise do. Instead of mutating its own subject, create new `Chainable` with new subject

```js
const div = cy.get('div')
div.then(() => 123)
div.then(el => console.log(el)) // this SHOULD print div.element
```

### Test code to reproduce

Already provided

### Versions

cypress 4.2.0, windows, chrome

**Comment by jennifer-shehane** [comment]
We do not recommend assigning variables to Cypress commands - they are enqueued and run asynchronously, so will not work as you expect assigning `const div = cy.get('div')`. 

If you put a `debugger` below the `const` assignment, you can see that the `cy.get()` is evaluating as a Cypress Chainer - not the resolved element, so when you're then doing the below, it's as if you're writing `.then(() => {}).then(() => {})`, so it's just passing on the return value from the previous chainer. 

**Please very carefully read this doc!** https://on.cypress.io/variables-and-aliases#Return-Values

```js
it('then', () => {
  const div = cy.get('div')
  debugger
  // div is just a chainer, not the el
  div.then(() => {
    debugger
    return 123
  })
  // div is just a chainer, not the el
  div.then((el) => {
    debugger
    console.log(el)
  }) 
})
```

<img width="615" alt="Screen Shot 2020-03-31 at 9 39 50 PM" src="https://user-images.githubusercontent.com/1271364/78042870-a5140f80-7398-11ea-925b-628101e6ff3e.png">


Alternatives to what you're doing:

```js
cy.get('div').as('myDiv')
cy.get('@myDiv').then(() => 123)
cy.get('@myDiv').then(el => console.log(el)) // this will print "el"
```

```js
cy.get('div').then(() => 123)
cy.get('div').then(el => console.log(el)) // this will print "el"
```

**Comment by G0L0L** [comment]
@jennifer-shehane thanks a lot for the answer! I definitely missed this part of documentation
