### ISSUE TITLE
The webpack error in the app iframe cannot be fully scrolled

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6898]
Cypress v4.3.0

If there is a webpack error with a long text line, I can only scroll it horizontally for a few characters, but never to fully read it

![overflow](https://user-images.githubusercontent.com/2212006/78094767-591a9800-73a3-11ea-9d56-0cdf0930187f.gif)

**Comment by jennifer-shehane** [comment]
Looks like you're gonna need a wider screen. 😳 

Can recreate this situation by running the following code basically:

`spec.js`

```js
const foo = require('MaecenasfaucibusmollisinterdumLoremipsumdolorsitametconsecteturadipiscingelitMaecenasfaucibusmollisinterdumLoremipsumdolorsitametconsecteturadipiscingelit')

describe('long error msg')
```

**Comment by bahmutov** [comment]
I should just stop coding errors

**Comment by adancarrasco** [comment]
Hi - Can I take this one? 💪

**Comment by jennifer-shehane** [comment]
@adancarrasco Yes we would love an open PR - Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).
