### ISSUE TITLE
Event listener error while working on Cypress

### ISSUE THREAD

**Issue by shivaIMS** [cypress-io/cypress#6904]
I have 11 spec files in my JavaScript code (Visual Studio) and I am getting the below error : 

```
(node:32306) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exitEarlyWithErr listeners added to [Project]. Use emitter.setMaxListeners() to increase limit
(node:32306) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exitEarlyWithErr listeners added to [Project]. Use emitter.setMaxListeners() to increase limit
```

And I see many of them suggested the code : process.setMaxListeners(0);

But no one mentioned about where exactly to add this functionality. I am new to cyprees please help me

**Comment by shivaIMS** [comment]
Please let me know how do I fix this issue ASAP.

Thanks in advance :)

**Comment by jennifer-shehane** [comment]
This is a warning and can be safely ignored.

Duplicate of #1305

**Comment by shivaIMS** [comment]
Thanks a lot jennifer :)
