### ISSUE TITLE
SERVER_ECHOED_INVALID_SESSION_ID when trying to connect to Redis cli

### ISSUE THREAD

**Issue by tracer13** [cypress-io/cypress#6906]
### Current behavior:

When using a redis client (i.e. node_redis or ioredis) and trying to connect to **rediss** (secured), there is an error  
```
Unhandled error event: Error: 140361912369256:error:1000011e:SSL 
routines:OPENSSL_internal:SERVER_ECHOED_INVALID_SESSION_ID:../../third_party/boringssl/src/ssl/handshake_client.cc:661:
```

**NOTE: If I use redis (not secured) there is no issue.**

### Desired behavior:

Connection is established and allows query execution.

### Test code to reproduce

From *plugins/index.js*

Happens when I try to establish a connection, doing the following (mind, that connection string is only a pattern, but gives the idea)

```js
const Redis = require('ioredis');
let redisConnectionString = 'rediss://:password@host:port/db'
const redisClient = new Redis(redisConnectionString);
```

Also, adding parameters to connection string, like `?ssl_cert_reqs=CERT_REQUIRED`, doesn't help

**NOTE: When I try doing the same thing directly through NodeJs it works perfectly.**

### Versions

Cypress versions from 3.7.0 to latest, redis client version latest

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you. Your issue may have already been fixed. Thanks!

**Comment by tracer13** [comment]
I did use the latest version 4.3.0. What I meant is that I tried on older versions as well.

**Comment by flotwig** [comment]
Try using the config option `nodeVersion: "system"`, this sounds like a bug in Electron's SSL implementation.

**Comment by tracer13** [comment]
Yes, @flotwig , that solved the issue! Thank you for the quick solution.
