### ISSUE TITLE
Could not install cypress behind firewall 

### ISSUE THREAD

**Issue by nids2307** [cypress-io/cypress#6908]
This relates to Issue #6895 

### Current behavior:
Unable to install Cypress 4.3.0

```
PS C:\data\prj_folder>  yarn add cypress@4.3.0
yarn add v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning cypress > extract-zip > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
[4/4] Building fresh packages...
[1/3] ⠂ deasync
[2/3] ⠂ husky
error C:\data\prj_folder\node_modules\cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: C:\data\prj_folder\node_modules\cypress
Output:
Installing Cypress (version: 4.3.0)

[09:08:02]  Downloading Cypress     [started]
[09:08:03]  Downloading Cypress     [failed]
[09:08:03] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.3.0?platform=win32&arch=x64
Error: unable to get local issuer certificate

----------

Platform: win32 (10.0.17134)
Cypress Version: 4.3.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configurationypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.3.0?platform=win32&arch=x64
Error: unable to get local issuer certificate

----------

Platform: win32 (10.0.17134)
```

### Desired behavior:

I want to install cypress. I had issues upgrading cypress, so I removed the project and cloned a fresh one from bitbucket repo. I am unable to install yarn as well as cypress due to the above error

### Versions

node.js - v13.11.0
yarn version v1.22.4
OS: Windows 10
git version 2.20.1

**Comment by jennifer-shehane** [comment]
>warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

Have you tried removing your `package-lock.json` file - it may have a reference to the older 4.2.0 deps. You shouldn't have a `package-lock.json` file when using `yarn`.

But, more generally this error is usually thrown if you are behind a corporate proxy - you'll need to configure this here: https://on.cypress.io/proxy-configuration

**Comment by nids2307** [comment]
It wasn't a proxy configuration issue and perhaps the package-lock.json was causing the issue. I took an alternate route and used the latest desktop version of cypress and it resolved the issue.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
