### ISSUE TITLE
`cy.task` fail to resolve when used in `server` `onAnyRequest`

### ISSUE THREAD

**Issue by flovilmart** [cypress-io/cypress#6914]
We are validating some payloads against an out of browser library through a task. 
At this time, `cy.task` seem to suspend the execution and never resolve.

Consider the following:

```js
// support/index.js

beforeEach(() => {
  cy.server({
    onAnyRequest: (route, proxy) => {
      console.log('before');
      cy.task('validateRequest', proxy.request.body).should('be', true);
      console.log('after');
    },
  });
});

// plugins/index.js

module.exports = (on) => {
  on('task', {
    validateRequest: (body) => {
      // TODO: validate body
      return  Math.round(Math.random() * 10) % 2 === 0
    }
  });
}
```

### Current behavior:

The following error occurs:

```
Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > cy.visit()

The cy command you invoked inside the promise was:

  > cy.task()

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.
```

At this time, the assertion is never triggered and the `validateRequest` task is run appropriately.

### Desired behavior:

The assertion should trigger, and no error / unhandled exception should be fired.

### Test code to reproduce

See the example repository here: https://github.com/flovilmart/cypress-test-tiny

### Versions

```
$ cypress --version
Cypress package version: 4.3.0
Cypress binary version: 4.3.0
```

**Comment by jennifer-shehane** [comment]
Yeah, you can't run cypress commands inside of these handlers. I thought we had an existing issue for this, but I can't find it. 

`plugins/index.js`

```
module.exports = (on) => {
  on('task', {
    validateRequest: (body) => {
      const res = Math.round(Math.random() * 10) % 2 === 0
      console.log(res);
      return res;
    }
  });
} 
```

`spec.js`

```js
it('Hello world', () => {
  cy.server({
    onAnyRequest: (route, proxy) => {
      cy.task('validateRequest', proxy.request.body).should('be', true);
    },
  });
  cy.visit('https://www.airbnb.ca/s/homes')
});
```

**Comment by flovilmart** [comment]
Thanks @jennifer-shehane. Is there any workaround that you would know about? I thought of collecting the requests and processing them in `afterEach`, this breaks the ability to know *when* the request was processed relative to other xhr calls.

**Comment by jennifer-shehane** [comment]
What do you need to do in the actual function? Do you need access to Node? The only reason to do this in a `task` is that you need access to Node for some reason. Otherwise this can just be a normal function. Or you can pull in what you need into the spec file to check in the function. 

Collecting them in an `afterEach` may be fine depending on what you're doing also. It's difficult to recommend a workaround without knowing the exact nature of what you want to do with the data. 

But yes, after discussing this further with the team, we can’t support running `cy.task()` within an `onAnyRequest` because we can’t ‘block’ the request from processing.

**Comment by flovilmart** [comment]
Ok sounds good. We need to call out to node as we perform some tests against the request bodies. 
Performing it within the onAnyRequest itself would allow marking the issue on the proper request but we’re fine with running in the `afterEach`
