### ISSUE TITLE
Installation: Download hangs on 100%

### ISSUE THREAD

**Issue by b-m-f** [cypress-io/cypress#6918]
### Current behavior:
Installation does not progress beyond downloading. Stuck at 100%.

![image](https://user-images.githubusercontent.com/2843450/78226438-fec92680-74cb-11ea-8823-ef9f32077c6d.png)

### Desired behavior:

Installation should continue with unzipping

### Test code to reproduce
`npm install --save-dev cypress`

### Versions

5.5.13-1-MANJARO Linux
Cypress 4.3.0

**Comment by jennifer-shehane** [comment]
@b-m-f Could you run install in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

We have never seen this issue before, so likely it is something specific to your environment/setup that we'll need to identify.

**Comment by b-m-f** [comment]
@jennifer-shehane here is the output. The debugging does not continue, so I am guessing the code hangs somewhere

```
  cypress:cli installing Cypress from NPM +0ms
  cypress:cli installing with options {} +0ms
  cypress:cli version in package.json is 4.3.0 +0ms
  cypress:cli Reading binary package.json from: /home/user/.cache/Cypress/4.3.0/Cypress/resources/app/package.json +0ms
  cypress:cli no binary installed under cli version +12ms
  cypress:cli checking local file /home/user/Workspace/app/4.3.0 cwd /home/user/Workspace/app/node_modules/cypress +6ms
  cypress:cli preparing to download and unzip version  4.3.0 to path /home/user/.cache/Cypress/4.3.0 +12ms
Installing Cypress (version: 4.3.0)

  cypress:cli needed Cypress version: 4.3.0 +0ms
  cypress:cli source url https://download.cypress.io/desktop/4.3.0?platform=linux&arch=x64 +0ms
  cypress:cli downloading cypress.zip to "/tmp/cypress.zip" +0ms
  cypress:cli Downloading package {
  url: 'https://download.cypress.io/desktop/4.3.0?platform=linux&arch=x64',
  proxy: null,
  downloadDestination: '/tmp/cypress.zip'
} +4ms
  ⠼  Downloading Cypress
  ⠦  Downloading Cypress
     Unzipping Cypress
  ⠇  Downloading Cypress      100% 0s
     Unzipping Cypress
     Finishing Installation
```

**Comment by b-m-f** [comment]
I just downloaded the zip file from https://download.cypress.io/desktop/4.3.0?platform=linux&arch=x64 manually and compared it to the one that was downloaded to `/tmp/`

```
manually md5sum: bc3fc129fdb9be4a136f98a7e5445db4  cypress.zip

/tmp md5sum: 497cd1b9090ff7a4a7f20ce9bc191052  cypress.zip
```

No idea what is going wrong here.

Looking at the code I found this:
https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/download.js#L203
```
        const version = response.headers['x-version']

        debug('redirect version:', version)
        if (version) {
          // set the version in options if we have one.
          // this insulates us from potential redirect
          // problems where version would be set to undefined.
          redirectVersion = version
        }
```
Which does not provide a fallback for the version.

**Comment by b-m-f** [comment]
Reran the installer again and not it worked. 
No idea what went wrong, but glad it resolved itself.

**Comment by jennifer-shehane** [comment]
The `redirect version:` shouldn't be related (this did not log in your debug logs). 

And yeah, I have no idea :( We haven't seen this stall like this before. Glad to hear it's resolved.

**Comment by inspiraluna** [comment]
I have the problem on Mac. npm install cypress --save-dev hangs when it reaches 100%. (it doesn't unpack)

**Comment by jennifer-shehane** [comment]
@inspiraluna If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by riyadelberkawy** [comment]
I have the problem same problem ( npm install cypress --save-dev ) 

 > ![Screenshot from 2021-04-09 00-34-30](https://user-images.githubusercontent.com/53310178/114197648-d8499100-9952-11eb-8e7c-5cde0c55c34d.png)

> ### Versions
> Ubuntu 20.04.2 LTS Linux
> Cypress 7.0.1

**Comment by jpike88** [comment]
I have the same issue, it seems to happen only sometimes. Am using Amazon Linux CI.

**Comment by binarykitchen** [comment]
This is not resolved and is still happening.

**Comment by Pachat** [comment]
Still happening on Windows 10
```
npm i -g cypress --save-dev
[##################] \ reify:rxjs: timing reifyNode:node_modules/cypress/node_modules/lodash Completed in 18061ms
```

**Comment by luzdealba** [comment]
I had the same issue with Cypress 9.6.0.  It was a filed locked in `C:\Users\[username]\AppData\Local\Cypress\Cache\...` which apparently was blocking the unpacking process; after restarting and manually deleting the directory altogether, and re-installing, it worked okay.

**Comment by Coder-VooOoo** [comment]
I also encountered the problem of stuck in 100%, because I used other mirror source downloads. When I restored the NPM default source code, there was no such problem.

**Comment by ViniciusResende** [comment]
I'm having the same issue using yarn, already deleted the `/home/[username]/.cache/Cypress/...` folder content still can't install it.

![Screenshot from 2022-11-20 09-41-24](https://user-images.githubusercontent.com/52660930/202902426-ca8f1813-3863-4023-9fc7-a135b14ed232.png)
