### ISSUE TITLE
Feature request: global configuration of type delay

### ISSUE THREAD

**Issue by timhwang21** [cypress-io/cypress#6925]
### Current behavior:

Delay has to be specified per-use as `.type('string', { delay: num })`.

### Desired behavior:

A global config that's something like `typeDelay: number`. Specifically, I'd like to globally reduce the timeout to 1ms or something.

I have the beginnings of a PR [here](https://github.com/timhwang21/cypress/tree/tim/feat-type-delay) but it might be incomplete in parts, especially in the specs. Would be happy to help close it out, though I feel this task would be trivial for someone with more knowledge of the codebase! (Assuming this feature is something others want, of course.)

**Comment by jennifer-shehane** [comment]
You can override the type command (or any command) so that every use of `.type()` uses the delay you'd like by default. 

```js
Cypress.Commands.overwrite('type', (originalFn, subject, text, options = {}) => {
  options.delay = 100

  return originalFn(subject, text, options)
})

it('type override', function () {
  cy.visit('index.html')
  cy.get('input').type('my text')
})
```

Adding this feature as a global configuration is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by timhwang21** [comment]
Great! Exactly what I was looking for. Thank you!

**Comment by DanaGoyette** [comment]
When doing such an override, is there any easy way to suppress the logging of `{delay: 100}` on every `type` step, without outright disabling logging of the step (`{log: false}`)?

**Comment by allenhwkim** [comment]
Slight modification from @jennifer-shehane's answer to allow overriding. 

Without it, `type('foo', {delay:1000})` does not delay 1000ms, but default to 100ms.
```
Cypress.Commands.overwrite('type', (originalFn, subject, text, options = {}) => {
  options.delay = options.delay || 100;

  return originalFn(subject, text, options)
})
```

**Comment by RuilinYang-beta** [comment]
The above 2 solutions somehow don't work for me - I'm using TypeScript and it complains about the 3rd arg in `return originalFn(subject, text, options)`. 

But I find this - add these lines to your support file then it works!
```
Cypress.Keyboard.defaults({
  keystrokeDelay: 20,
})
```

See: https://docs.cypress.io/api/cypress-api/keyboard-api#Arguments
