### ISSUE TITLE
Is Cypress plugin a filepath or is it a module to be resolved

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6926]
Cypress v4.3.0
Demo in https://github.com/bahmutov/try-cra-with-unit-test

Imagine I want to load Cypress plugin from 3rd party module, not from `cypress/plugins/index.js`. In that demo project I have a dependency `"cypress-react-unit-test": "2.8.0-use-bundler-from-cra.2"` and it includes the plugins file that should be good for an application created using `create-react-app` before ejecting. So in `cypress.json` I can set this and it works

```json
{
  "pluginsFile": "node_modules/cypress-react-unit-test/plugins/cra-v3/index.js"
}
```

Now - the following works too, so to me this looks like we resolve the module 

```json
{
  "pluginsFile": "node_modules/cypress-react-unit-test/plugins/cra-v3"
}
```

Hmm, let's remove `node_modules`

```json
{
  "pluginsFile": "cypress-react-unit-test/plugins/cra-v3"
}
```

Nope, an error (with `[object object]` too)

<img width="1307" alt="Screen Shot 2020-04-02 at 6 35 29 PM" src="https://user-images.githubusercontent.com/2212006/78306186-c26be980-7510-11ea-98c7-610fc7c49d34.png">

I think it would be marvelous to try the `pluginsFile` first as a path, and if not found try to resolve as a module.

**Comment by jennifer-shehane** [comment]
Closing since this implementation has completely changed in 10.0. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
