### ISSUE TITLE
onBeforeLoad doesn't trigger on HTTPS page

### ISSUE THREAD

**Issue by GMchris** [cypress-io/cypress#6929]
### Current behavior:

Running Cypress tests on a domain with `HTTPS` behaves differently than on `HTTP`, basically disabling the `onBeforeLoad` event which Cypress provides.

### Desired behavior:

`onBeforeLoad` and `Cypress.on('window:before:load')` should trigger properly no matter where they're being executed.

### Test code to reproduce

Our tests require users to be logged in, so before any of them we  run a login action and save the token to the localStorage

```javascript
cy.request({
    method: 'POST',
    url: loginURL
    body: {
      email: Cypress.env('email'),
      password: Cypress.env('password'),
    },
  }).then((resp) => {
    cy.visit(`/#/${url}`, {
      onBeforeLoad(win) {
        alert('On before load works!');
        win.localStorage.setItem(storageToken, resp.body.token);
      },
    });
  });
```
I do a similar thing with Cypress' other way of handling `onBeforeLoad` when performing a mock login

```javascript
Cypress.on('window:before:load', (win) => {
    alert('On before load works!');
    win.localStorage.setItem('session-token', 'mocktoken');
  });
```

This worked perfectly so far while we were running the tests on our test environment, however when we tried to run it on production (which is `https`) no tests were able to get past the login stage. I decided to add `alerts` to the `onBeforeLoad` handlers and it appears that they're not even being called on `https`. 

Oddly enough if I add `onLoad` handlers they work pretty much as expected on both environments. There are no code differences between the TEST and PROD environments, the two UIs are identical.

### Versions

Cypress 4.0.1
Chrome 80 / Electron 78

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce this visiting an https site. 

```js
Cypress.on('window:before:load', (win) => {
  alert('On before load works!');
});

describe("Test", () => {
  it("visit", () => cy.visit("https://example.cypress.io"))
})
```

I would look to other things that may have changed through your build process or environment. Or there is something more specific than just visiting `https` that it making this not be called. Can you provide any more information to reproduce this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
