### ISSUE TITLE
Filter Runs tab on status

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#693]
We run a lot of tests and when we want to investigating a failing build, we have go to Older Runs to finnd the failing build.

I want to filter the Runs tab on failing/errored runs so that they will appear on top.

**Comment by jennifer-shehane** [comment]
This has been delivered in the Dashboard. 

<img width="333" alt="screen shot 2019-02-08 at 12 32 19 am" src="https://user-images.githubusercontent.com/1271364/52432532-0cd61e00-2b39-11e9-9223-101b3ee0015b.png">
