### ISSUE TITLE
Chrome 80 - Hot reloading not working

### ISSUE THREAD

**Issue by melibe23** [cypress-io/cypress#6933]
### Current behavior:

I have a simple test:

```js
describe('My First Test', function () {

  it('Testing"', function () {

    cy.log('Test 2');

  });
});
```

The first time I run it, all good.

Now I edit the file, and the change is not reflected. It still runs the previous version. I did save the file.

See gif

I tried to paste it here, I was able to.  Here is the gif saved https://drive.google.com/file/d/1kzTCxaN9SHZtNgkWbGet1X7RHN2-XtXK/view?usp=sharing

**Only happens with Chrome 80, not happening with Firefox nor Electron, nor headless**

### Desired behavior:
Tests should be updated

### Versions
Cypress 4.3.0
Chrome 80
Mac Catalina

![image](https://user-images.githubusercontent.com/32499737/78368617-2c919680-75c4-11ea-99ff-945243d98fa8.png)

**Comment by melibe23** [comment]
No news on this? No one is with the same issue?

**Comment by jennifer-shehane** [comment]
I can't recreate this currently within Chrome 80, ran from VSCode terminal. 

Do you have any other configuration? preprocessors / cypress configuration, etc?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
