### ISSUE TITLE
XHR aborted within Cypress tests, but not outside of test.

### ISSUE THREAD

**Issue by rajendragola** [cypress-io/cypress#6938]
CypressError: The network request for this XHR could not be made. Check your console for the reason.

Steps to reproduce:

1. Browse https://www.myperfectresume.com/

2. Click on "Build My Resume" button.

3. Verify https://www.myperfectresume.com/build-resume is opened.

4. Click on "Create My Resume" button.

Expected Result: Verify it has redirected to https://www.myperfectresume.com/build-resume/experience-level.

Actual Result: XHR post request accounts/v4/createguestuser is ABORTED.

Please find below the snapshot.

Can you please look into this issue? 

### Versions
Cypress : 4.3.0
Operating System : Windows 8.1
Browser : Electron 80
![xhrfailMpr](https://user-images.githubusercontent.com/58481004/78465823-ef3e1d80-7717-11ea-8857-e2c71783622f.JPG)
![ForcedStuckInUserCreation](https://user-images.githubusercontent.com/58481004/78465832-fe24d000-7717-11ea-90c4-2062ff402a3e.JPG)

**Comment by jennifer-shehane** [comment]
The second click for 'Create my resume' is not necessary to show what the application is doing - it is force redirecting back to the main page with url `https://www.myperfectresume.com/?forceRedirect=StuckInUserCreation`

Test code to reproduce:

```js
it('test', () => {
  cy.server()
  cy.route('POST', 'https://perf-accounts.com/accounts/v4/createguestuser').as('createUser')
  cy.visit('https://www.myperfectresume.com/');
  cy.contains('BUILD MY RESUME').click()
  cy.url().should('include', 'build-resume')
  cy.wait('@createUser').its('status').should('eq', 200)
})
```

I'm not sure why this POST is aborting in Cypress and not outside. 

### Outside Cypress

<img width="1281" alt="Screen Shot 2020-04-08 at 11 57 38 AM" src="https://user-images.githubusercontent.com/1271364/78748050-fd4aa300-7990-11ea-9167-3f0d7518187e.png">

### Inside Cypress

<img width="1058" alt="Screen Shot 2020-04-08 at 12 02 35 PM" src="https://user-images.githubusercontent.com/1271364/78748068-06d40b00-7991-11ea-991e-f4ba8b0fe3d4.png">

**Comment by jwalton** [comment]
I am running into a similar problem.  My test is failing because a GET to a resource has aborted:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/1771003/101422467-c1bbfc00-38c4-11eb-87a6-2e5d19703665.png">

But if I go look in the network tab, all requests for m3u8 files have succeeded:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1771003/101422532-df896100-38c4-11eb-9811-8c17d8d40ce6.png">

Why does Cypress think this request was aborted?

**Comment by ArtMyWeb** [comment]
Any updates on this?
I'm facing the same issue, cypress version is 7.2.0

**Comment by whoiskonstantin** [comment]
Facing the same issue with 7.6.0. Very strange behavior: I'm building pagination tests and when cypress changes the page there's a request that goes out to fetch data for the new page. That request is aborted 90% of the time and 10% of the times is successful. However, if you just change pages in the browser you can never see an aborted request. All other tests are running smoothly, just the pagination one is breaking. Here's a snippet of the test and some screenshots.

```javascript
describe('Verify if table pagination works correctly', () => {
  it('Changes page', () => {
    cy.login()
    cy.visit('http://localhost:3000/menu/campaigns/ALL')
    cy.url().should('eq', 'http://localhost:3000/menu/campaigns/ALL')
    cy.contains("Izakaya Kirby")
    cy.get('.center-page_count').find('input').clear().type('2{enter}')
  })
})
```

Aborted:
<img width="1185" alt="Screen Shot 2021-07-05 at 11 00 14 PM" src="https://user-images.githubusercontent.com/60210072/124636863-43b5d880-de46-11eb-90d4-58c17ef65a3a.png">

Successful:
<img width="1193" alt="Screen Shot 2021-07-05 at 10 59 35 PM" src="https://user-images.githubusercontent.com/60210072/124636879-487a8c80-de46-11eb-92e0-14bb268bbc29.png">

**Comment by whoiskonstantin** [comment]
Oh so I just noticed something strange about that request. The problem occurs when the initial fetch is delayed. On the aborted screenshot you can see that the response was processed between line 5 and 6, whereas on the successful response it that initial fetch is processed between line 2 and 3. I fixed it by inserting an arbitrary wait of 3 seconds.

```javascript
cy.url().should('eq', 'http://localhost:3000/menu/campaigns/ALL')
cy.wait(3000) // wait until pending requests are resolved.
cy.contains("Izakaya Kirby")
```
Not the most elegant solution but it did work.

**Comment by whoiskonstantin** [comment]
I tried to rewrite it with intercepters and tried waiting for an alias. However the problem persists.

``` javascript
cy.intercept({
pathname: '/api/v2/collection-view/campaigns*',
}).as('campaigns')

cy.url().should('eq', 'http://localhost:3000/menu/campaigns/ALL')
cy.wait(@campaigns) // wait until pending campaigns request is resolved.
cy.contains("Izakaya Kirby")
```

Here's the cypress code block from the stack trace which triggers the abort (Line: 159073): 

```javascript
XHR.prototype.abort = function (...args) {
  // if we already have a readyState of 4
  // then do not get the abort stack or
  // set the aborted property or call onXhrAbort
  // to test this just use a regular XHR
  if (this.readyState !== 4) {
    server.abortXhr(this); // <- this line invokes the abort.
    }

  return abort.apply(this, args);
};
```


I guess I'll have to go with an anti pattern `wait(3000)` for now.

**Comment by jacobmfoley** [comment]
Changing 'localhost' to '127.0.0.1'  resolved the error for me.
