### ISSUE TITLE
Intersection Observer not detecting intersection in Chrome when run by Cypress.

### ISSUE THREAD

**Issue by sunfit** [cypress-io/cypress#6943]
Please see https://github.com/cypress-io/cypress/issues/3848 and my comment https://github.com/cypress-io/cypress/issues/3848#issuecomment-609759933_

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.

Please give a reproducible example - which is neither available here nor in the previously closed issue.
