### ISSUE TITLE
Expose event for when Cypress is about to exit

### ISSUE THREAD

**Issue by D0rmouse** [cypress-io/cypress#6946]
We have a process that starts up when Cypress does, which we start from the Cypress plugins index.js, using NodeJS's `child_process`. The process is Wiremock, to be exact. We know we can use Cypress' fixtures, but for now this is not an option.

We would like an event to be implemented that we can bind to so we can kill the `child_process` when Cypress is about to exit.

On Windows the `child_process` is killed automatically, but on Linux it needs to be manually stopped, because it keeps running even after the parent process is killed.

**Comment by jennifer-shehane** [comment]
You can have more debug logs log, by running `DEBUG=cypress:server:cypress cypress run`. This will issue a debug log when it's about to exit, but...I don't think you could actually prevent the exit code in this case.

<img width="835" alt="Screen Shot 2020-04-07 at 12 47 56 PM" src="https://user-images.githubusercontent.com/1271364/78636288-10e10580-78ce-11ea-9d11-646c40f0e1af.png">

Have you looked at our [Module API](https://on.cypress.io/module-api)? It may be a medium where you can craft something you want.

**Comment by D0rmouse** [comment]
Thanks I will have a look at the module API.

But lifecycle events are always useful and it seems easy to fire an event when it's about to exit (maybe where it's logged)? 
Then if listeners are registered, wait for their promises to resolve, else just exit?

**Comment by jennifer-shehane** [comment]
Even if easy to implement, there are many considerations when deciding what to put into the product beside its ease of implementation. We'll leave this issue as a proposal and see if this issue gains more 👍 or comments in support from other users.

This would likely fall under the work slated for https://github.com/cypress-io/cypress/issues/2840

**Comment by rsudarson** [comment]
+1. This is a useful feature.

**Comment by chrisbreiding** [comment]
This is now supported by using the [`after:run` event](https://docs.cypress.io/api/plugins/after-run-api.html#Syntax). You currently need to enable it with the `experimentalRunEvents` option, but that will no longer be necessary when Cypress 6.7.0 is released in the near future.

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
