### ISSUE TITLE
Click (mouse event) trigger weird behaviour

### ISSUE THREAD

**Issue by DarkSorrow** [cypress-io/cypress#6955]
Hello,
I'm trying to make a test of a click in a canvas area, this canvas contain an SVG. I'm actually working to test cypress because our current test tools are based on selenium but most our dev are from the js world and selenium is also pretty heavy :p 

My test was to create a "room" in our app and click on the wall to display the menu.
I'm able to simulate a click (even tho i have to use a different element that we were using on selenium) but i can't seems to make the mouse click on the coordinate i choose.
I took screen shot of the coordinate and as you can see on them they seems not to point in the correct area

### Current behavior:
This is when i use the position of the trigger function

![mouse_move](https://user-images.githubusercontent.com/8224508/78653366-4c2a0700-78c3-11ea-9879-6f45cd91427c.PNG)

And this is when i add the parameter screenX, pageX....

![mouse_down](https://user-images.githubusercontent.com/8224508/78653446-682da880-78c3-11ea-93f8-3cbdf4bb2976.PNG)

As you can see its the same coordinate but the click seems to be taking the center of my canvas.
It seems that the click does trigger tho as the menu appears in the middle of the room but i can't make it move to the wall

### Desired behavior:

The trigger with the client parameters should be able to point to the same target taken from the previous position

### Test code to reproduce

```js
it('Check if the room has correct size', () => {
  cy.get("#3DContainer").should('have.attr', 'style', 'cursor: default;');
  cy.get('#canvas')
    .trigger('mouseover', {
      log: true,
      force: true,
    })
    .trigger('mousemove', {
      log: true,
      force: true,
    })
    cy.get("#3DContainer").should('have.attr', 'style', 'cursor: pointer;');
    /*cy.get('#canvas').rightclick({
      force: true,
      log: true,
    })*/
    cy.get('#canvas')
    .trigger('mousemove', 386, 296, {
      log: true,
      force: true,
    })
    .trigger('mousedown', {
      clientX: 386,
      clientY: 411,
      screenX: 386,
      screenY: 411,
      pageX: 386,
      pageY: 411,
      button: 0,
      log: true,
      force: true,
    }).wait(50).trigger('mouseup', {
      clientX: 386,
      clientY: 411,
      screenX: 386,
      screenY: 411,
      pageX: 386,
      pageY: 411,
      button: 0,
      log: true,
      force: true,
    });
  });
```
Also i was wondering if there was a way with the click and rightclick to generate a long hold like i'm doing with the wait in the middle as it seems that just a click doesn't work on my canvas

### Versions

Chrome 80, cypress: 4.3.0

**Comment by DarkSorrow** [comment]
Just an update changeing trying the use the click position doesn't seems to work, i keep having the red dot focus on the middle of my screen.
Also i've been trying to use chrome monitorEvents to see the difference between the event i trigger and the one in my browser and they both seems to be exactly the same

**Comment by DarkSorrow** [comment]
Ok me again, i like talking to myself but in my cypress code on the click even i pass this
`cy.get('#canvas')
    .click({
      button: 0,
      log: true,
      screenX: 984,
      screenY: 352,
      clientX: 463,
      clientY: 293,
      pageX: 463,
      pageY: 293,
      x: 463,
      y: 293,
      offsetX: 463,
      offsetY: 179,
      layerX: 463,
      layerY: 178,
    })`

and when i look at it in my javascript code by logging the event received  i get this
`isTrusted: false
screenX: 463
screenY: 408
clientX: 463
clientY: 408
ctrlKey: false
shiftKey: false
altKey: false
metaKey: false
button: 0
buttons: 1
relatedTarget: null
pageX: 463
pageY: 408
x: 463
y: 408
offsetX: 463
offsetY: 293
movementX: 0
movementY: 0
fromElement: null
toElement: canvas#canvas
layerX: 463
layerY: 293`

The coordinate seems to not be the same. Is there some transformation made in the click or are some parameters not passed in cypress?

**Comment by DarkSorrow** [comment]
Well sorry wrong button for the close but testing again the difference between triggers and click here is the code i tried again:

`const clickEvent = {
      button: 0,
      log: true,
      screenX: 984,
      screenY: 352,
      clientX: 463,
      clientY: 293,
      pageX: 463,
      pageY: 293,
      x: 463,
      y: 293,
      offsetX: 463,
      offsetY: 179,
      layerX: 463,
      layerY: 178,
    }
    cy.get('#canvas')
    //.click(clickEvent)
    .trigger('mousedown', clickEvent)
    .trigger('mouseup', clickEvent);`

With the trigger the coordonate seems to work on my canvas but when i'm using the click it doesn't. The position in my parameters are altered it seems. So i asked the question in the chat but i'm not sure if its the intended behaviour i don't really see this being mentioned in the document either that the parameter we will pass is going to be changed by the click event

**Comment by DarkSorrow** [comment]
What i see from a click i perform myself and the result of the click i get in my console log is this

sourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}

On the click perform by cypress this is set to null. Also in the trigger if i take out the button: 0 and buttons: 1 it does the same as the click event

**Comment by tomdelahaba** [comment]
I have the same, trigger coordinates mismatch with option client coordinates. option coordinates seems to always be centered in the screen while trigger coordinates works.

Another problem is that if you will look into the options that cypress is showing, in your case the trigger mousedown, object{17}, if you pass just clientX, clientY, they are being transcripted into clientx clienty....
