### ISSUE TITLE
Error: You must first sign the relevant contracts online.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6957]
### Current behavior:

We're getting an error thrown from `cypress/node_modules/electron-notarize` during building of the binary in `develop` branch here: https://circleci.com/gh/cypress-io/cypress/297860

```
1 package(s) were not uploaded because they had problems:

/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/393FBFE1-5903-4AF1-893C-3545527D7A99/com.electron.cypress.itmsp - Error Messages:

You must first sign the relevant contracts online. (1048)

2020-04-07 10:06:18.588 altool[1215:8304] *** Error: You must first sign the relevant contracts online. (1048)

at /Users/distiller/cypress/node_modules/electron-notarize/src/index.ts:83:13

at Generator.next (<anonymous>)

at fulfilled (/Users/distiller/cypress/node_modules/electron-notarize/lib/index.js:4:58)

at processTicksAndRejections (internal/process/task_queues.js:93:5)
🔥 deploy error
```

### Versions

`develop` branch - failed checks from this commit specifically https://github.com/cypress-io/cypress/commit/f47f3d64648f09b5b922eb423375580ff8d4902c

**Comment by jennifer-shehane** [comment]
>check your developer.apple.com account has admin permissions for your organization and go to https://appstoreconnect.apple.com/ to accept the legal docs.

>After a team member with admin access navigated to https://appstoreconnect.apple.com/ there was a pending agreement that had to be accepted and the error went away.

https://stackoverflow.com/questions/58358449/notarizing-electron-apps-throws-you-must-first-sign-the-relevant-contracts-on

**Comment by bahmutov** [comment]
Fixed by signing the agreement in Apple support dashboard https://app.circleci.com/pipelines/github/cypress-io/cypress/10328/workflows/bb9b1de9-ec14-44d6-9e8d-af18a757fb88
