### ISSUE TITLE
Improve UI when el not actionable by distinctly displaying stale elements vs hidden elements

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#696]
The visibility algorithm correctly identifies detached elements as "hidden".

But when determining and providing the **reason** its hidden, we get an error message about the effective width and height being 0.

Since detached elements do not actually displace any content, this is technically correct, but miscommunicates the reason why.

We should provide a better error message in this circumstance and also add a new UI icon for detached elements (as opposed to just hidden).

Here's an example.

In this situation I've caused the element to be removed **after** the `cy.get()` but **during** the `.click()`

This test should correctly fail but the error message sends me down the wrong path.

![screen shot 2017-09-29 at 11 07 44 am](https://user-images.githubusercontent.com/1268976/31022430-c2995618-a506-11e7-8f9a-e47a3def9232.png)

Here's a suggestion where instead of displaying the **invisibility** icon, we add a new icon and tooltip to indicate that this element has become detached.

![screen shot 2017-09-29 at 11 11 19 am](https://user-images.githubusercontent.com/1268976/31022486-f0fbabb4-a506-11e7-81e9-7e1aec996a08.png)

**Comment by brian-mann** [comment]
Another idea here is to either add a mutation observer, or just override `removeChild` so we could detect the very instant a DOM element is detached so we could immediately fail a chain of commands, since there is no way to recover.

**Comment by tnrich** [comment]
@brian-mann is there a way to tell a chain of commands to re-run? Such that if the element is removed after a `.get()` but before a `.click()` we could have cypress re-run both the `.get()` and the `.click()` ?

Thanks!

**Comment by jennifer-shehane** [comment]
This has already been delivered - we correctly error that the element has been detached from the DOM instead of showing the 0x0 error.
