### ISSUE TITLE
Assertion errors do not include a useful stack

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#6969]
### Current behavior:

When an assertion fails, the stack trace included with the error is not useful. It either doesn't exist or points to Cypress internals.

### Desired behavior:

Assertion failure stack traces should include the calling code, since that is where the assertion failure originates.

### Test code to reproduce

For a root level assertion, there will be no strack trace (in Chrome, at least):

```javascript
expect(true).to.be.false
```

For an assertion in a test, there will be a stack trace, but it only points to Cypress internals

```javascript
it('fails', () => {
  expect(true).to.be.false
})
```

### Versions

Cypress: 4.3.0

**Comment by raylon-silberman** [comment]
Any update on this? This is also affecting my QA team.

**Comment by jennifer-shehane** [comment]
Yes, there is an open PR to fix this here https://github.com/cypress-io/cypress/pull/6965
