### ISSUE TITLE
Trim cy.exec output text

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#697]
- Operating System: Mac / all
- Cypress Version: 0.20.1
- Browser Version: all

### Is this a Feature or Bug?

a **breaking feature**

### Current behavior:

`cy.exec('cmd')` returns an object with `stdout, stderr, code`. I always as a rule trim the `stdout` and `stderr` before comparing them to the expected values to avoid silly whitespace differences. Other tools like [execa](https://github.com/sindresorhus/execa) also trim `stdout` by default, removing extra new line. 

### Desired behavior:

Can we match `execa` behavior (and even switch to it for better cross platform support) and trim both `stdout` and `stderr` output by default?

**Comment by brian-mann** [comment]
The code for this is merged, but it has not been released yet.

**Comment by brian-mann** [comment]
Fixed in [`0.20.2`](https://docs.cypress.io/guides/references/changelog.html#0-20-2).
