### ISSUE TITLE
Unable to locate elements on Cesium 3D map using Cypress

### ISSUE THREAD

**Issue by chaitanyac-git** [cypress-io/cypress#6970]
Hi,

I am new to Cypress and cesium . Our application has HTML elements and 3D maps shown using Cesium viewer. I am able to locate HTML elements using CSS selectors , but having issue with the 3D map shown in Cesium viewer . 
It is identified as Canvas with no other identification . 
Please help if any option to locate elements on Cesium 3D maps using cypress .

Thanks.
Chaitanya

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
