### ISSUE TITLE
Refused to display 'https://www.nisum.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'. 

### ISSUE THREAD

**Issue by shahmed-nisum-com** [cypress-io/cypress#6971]
This is a bug;

### Current behavior:
I am writing a scenario in cypress where i first visit google site then i type 'nisum Karachi' then i go to go to search page where i found result set. Then i click the first link in it.

Actual Result: following error is being displayed on console;

```
"Refused to display 'https://www.nisum.com/' in a frame because it set
'X-Frame-Options' to 'sameorigin'."
```

### Desired behavior:

Nisum link should be opened after clicking it through google link. 

### Test code to reproduce

Code is being given URL:
https://github.com/shahmed-nisum-com/TaskOne.git

### Versions
"cypress": "^4.3.0",
Window 10
Electron 80

**Comment by EtienneBruines** [comment]
Is `nimsum.com` part of the code you are testing? You may need to navigate to `nisum.com` through `cy.visit()`. 

If so, then Cypress will intercept the `X-Frame-Options`  header and resolve the issue, because all requests go through the Cypress proxy. 

If it is not, then Cypress will treat it as a thid-party dependency, and not intercept it. It then adheres to the `X-Frame-Options` header sent by `nimsum.com`. That HTTP header is designed to prevent exactly this. 

(Anyone feel free to correct me)

**Comment by jennifer-shehane** [comment]
Your plugins file is not correctly written for Cypress version 4.0+ - it shows a warning when opening your repo via `cypress open`:

```
Deprecation Warning: The before:browser:launch plugin event changed its signature in version 4.0.0

The before:browser:launch plugin event switched from yielding the second argument as an array of browser arguments to an options object with an args property.

We've detected that your code is still using the previous, deprecated interface signature.

This code will not work in a future version of Cypress. Please see the upgrade guide: https://on.cypress.io/deprecated-before-browser-launch-args
```

You need to update your plugins file to be:

```js
module.exports = (on, config) => {
  on("before:browser:launch", (browser = {}, launchOptions) => {
    if (browser.name === "chrome" || browser.name === "electron") {
      launchOptions.args.push("--disable-features=CrossSiteDocumentBlockingIfIsolating,CrossSiteDocumentBlockingAlways,IsolateOrigins,site-per-process");
      launchOptions.args.push("--load-extension=cypress/extensions/Ignore-X-Frame-headers_v1.1");
      return launchOptions;
    }
  });
};
```

We don't recommend testing sites that are not under your control (like google.com) also.

But yes, as @EtienneBruines stated above, you shouldn't need to click through to the site to verify it's working. There are several workarounds detailed here: https://on.cypress.io/web-security#Common-Workarounds
