### ISSUE TITLE
Feature for click event, delay release

### ISSUE THREAD

**Issue by DarkSorrow** [cypress-io/cypress#6972]
Hello,

I'm working on 3D web application and i had a weird behaviour that i could not understand, i was able to read a bit the code that was used to handle the canvas drawing behind and it would seems that the events of mouseup is getting fired too fast which prevent the app from catching the second event
I know this behaviour is not good but i can't change that "custom" framework but i think other people might have the same use on delaying a click release button so i was wondering if it could be a feature to add to the set of click buttons?

I could reimplement all the events of the click to do this tho but again i'm thinking other might have the use for it :x

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
