### ISSUE TITLE
Travamento Cypress

### ISSUE THREAD

**Issue by arborges12** [cypress-io/cypress#6976]
Após atualizar o Cypress para versão 4.3.0 está ocorrendo travamentos no meio da execução. Apenas a coluna destinada a evolução dos estes trava. A seção do navegador continua sendo manuseada.

A área sinalizada que está travando.

![image](https://user-images.githubusercontent.com/63407915/78901580-e5d1ef80-7a4e-11ea-84f3-75ac5443160d.png)

**Comment by jennifer-shehane** [comment]
Click this button to enable 'auto-scroll'. Button should be orange to scroll.

![](http://g.recordit.co/tXcBWP5AzL.gif)
