### ISSUE TITLE
Login failed due to HTTPS and HTTP: This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by ndhunagan** [cypress-io/cypress#6978]
Application is HTTP and login App is HTTPS

Error:
```
Mixed Content: The page at 'https:/...' was loaded over HTTPS, but requested an insecure form action 'http://....'. This request has been blocked; the content must be served over HTTPS.
```

Windows 10
Electron 80

Question: is there is any setting or different way to resolve the issue? Basically looking for a setting to ignore HTTPS vs HTTP?

Cypress Version 4.2.0

**Comment by ndhunagan** [comment]
Already did cypress.json

{
  "chromeWebSecurity": false
}

But the browser I am using is Electron. Is there other setting for Electron ?

**Comment by jennifer-shehane** [comment]
This warning is coming due to how you visited an HTTPS site from an HTTP site. This has nothing to do with Cypress - this warning will show outside of Cypress. Read more about how to prevent this security issue: https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content

**Comment by ndhunagan** [comment]
If I follow same steps what i am doing on Cypress. I don't error outside Cypress. I am able to login without any error on Chrome and Chromium browser. Is there a way to try manually Electron browser outside Cypress.

**Comment by jennifer-shehane** [comment]
Do you have your DevTools open when doing the same thing outside of Cypress? The warning would be printed there. 

You can try turning off failing of tests on uncaught exceptions by following these directions: https://on.cypress.io/catalog-of-events#To-turn-off-all-uncaught-exception-handling

**Comment by ndhunagan** [comment]
Thanks Jen.

Also I added following code on index.js and no help (basically not able to login to application)

// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
  })

1)
On Cypress with "chromeWebSecurity": false DevTool:
![image](https://user-images.githubusercontent.com/43826204/79714107-a8f2cd80-8284-11ea-95b1-22ed44c4649c.png)

2)On Cypress with "chromeWebSecurity": true DevTool:
![image](https://user-images.githubusercontent.com/43826204/79714307-37ffe580-8285-11ea-946a-c8c707e476e8.png)

3) Outside Cypress on Chrome 81 DevTool:
No error on DevTool console with Chrome. No issue login to application (Able to login properly)
------------------------------------------------------------------------------------------------------------

**Inside Cypress with Electron 80 and Edge 81**: Above error and not able to login.
**Outside Cypress with Chrome 81**: No error and able to login.

What are suggestions you have ?

Thanks,

NIresh

**Comment by jennifer-shehane** [comment]
@ndhunagan I'm really unable to advise how to get the login working without an example provided. Can't tell from the provided info why the login is not working exactly.

**Comment by ndhunagan** [comment]
is there a way to send private message with code you or someone or also have if possible private session with you or someone so  that I can show the code what do you think? I cannot paste code code on the public space. what are your suggestions?

**Comment by jennifer-shehane** [comment]
You can privately email full reproducible examples to support@cypress.io. We do not offer private coding sessions.

**Comment by Yaroslav-Malevany** [comment]
Are there any updates on this? I have the same issue with my project. Outside the cypress, everything works fine. But inside the cypress(v5.5) tests, I am getting the same error every time. I'm using HTTPS on both pages. For the redirect link generation, I'm using `window.location.origin` from the original page.

**Comment by jennifer-shehane** [comment]
@Yaroslav-Malevany If you believe you are encountering a bug within Cypress - separate from this issue which we cannot fix - this is a warning from Chrome, then open a new issue with a reproducible example.

**Comment by GhateMadhuri** [comment]
@jennifer-shehane encountered same issue when i use SSO login which uses Https and after successful login it redirects to http site.
With manual execution chrome shows message but provides option to click send any ways while redireting but with cypress i dont see this and cypress blocks the request.
Is there any way we could pass this in browser config and not block request?

**Comment by monalijangale** [comment]
@jennifer-shehane  we are encountering same issue when a HTTPS website redirects to http site. cypress is blocking the http site to open.
ON normal flow with manual steps, we see a warning in chrome asking to proceed or not but with cypress the redirect is totally blocked.
Is there any way to bypass this or force cypress not to block?

**Comment by magjed4289** [comment]
> @jennifer-shehane we are encountering same issue when a HTTPS website redirects to http site. cypress is blocking the http site to open.
> ON normal flow with manual steps, we see a warning in chrome asking to proceed or not but with cypress the redirect is totally blocked.
> Is there any way to bypass this or force cypress not to block?

hey @monalijangale did you find anything interesting to solve it? I'm experiencing the same problem just now, trying to apply all the solutions I can find googling, but nothing works so far....

**Comment by acodavid** [comment]
I have same problem with mixed content warning... Any solutions?

**Comment by jamesw201** [comment]
I get the same issue. The site works fine on https manually in Chrome but through Cypress I get:
`Mixed Content: The page at 'https://##.#####.########.net/__/#/tests/integration/signin_spec.js' was loaded over HTTPS, but requested an insecure frame 'http://##.#####.########.net/myfrontend/'. This request has been blocked; the content must be served over HTTPS.`

In Firefox I also see this message:
`Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored`.

The certs for this site are generated locally using mkcert (https://github.com/FiloSottile/mkcert).

**Comment by SaiMadhav9494** [comment]
Hey @jamesw201, I am facing the same exact scenario you do with Cypress. did you figure out any solution?

**Comment by bahunov** [comment]
same here

**Comment by LuckyBoy1004** [comment]
I have same problem.
I am finding someone that solve this problem for me.

**Comment by bahunov** [comment]
Using electron instead of chrome works…

**Comment by RadoslavSt** [comment]
add to cypress.config.js
"chromeWebSecurity": false //add this param to your config file
*********************
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
  "chromeWebSecurity": false //add this param to your config file
});

**Comment by shaharb-hs** [comment]
Even when setting "chromeWebSecurity": false, when running headed this error is only a WARNING, but when Cypress runs headless this issue is an ERROR...

**Comment by nagash77** [comment]
hi @shaharb-hs , If you have a specific reproducible use case where this is happening please open a new issue and we will be happy to investigate.

**Comment by rakeshnambiar** [comment]
Do we have any work-around for Firefox?

**Comment by Ekta34** [comment]
@shaharb-hs  Did you find any solution or work around ? I am facing same issue. Even with `chromeWebSecurity: false` In headed mode it is working fine and not giving any error, but it won't work with headless mode.

**Comment by cjkepinsky** [comment]
hello @shaharb-hs @Ekta34 have you found any workarounds for the issue? I am facing it on Chrome and FF.
