### ISSUE TITLE
Display accurate error message when browser is not supported

### ISSUE THREAD

**Issue by mydiemho** [cypress-io/cypress#6979]
### Current behavior:

Safari is currently not supported.  However, the error message is misleading user to think that `Safari` is not installed vs it not being supported.

```
> npx cypress run --browser  "safari"

Can't run because you've entered an invalid browser name.

Browser: 'safari' was not found on your system.

Available browsers found are: chrome, firefox, electron
```

### Desired behavior:

Accurate error message.  For example:

```
> npx cypress run --browser  "safari"

Can't run because you've entered an invalid browser name.

Browser: 'safari' is not supported

Supported browsers are: chrome, firefox, electron, edge
```

### Test code to reproduce

Run the following on a host with Safari installed. 
```
 npx cypress run --browser  "safari"
```

### Versions

1. Cypress
```
➜ npx cypress -v
Cypress package version: 4.3.0
Cypress binary version: 4.3.0
```

1. Operating System
`macOS 10.15.4`

1. Browser
`Safari`

Related #6422

**Comment by jennifer-shehane** [comment]
Yah, this may not be as straightforward because you can actually customize the available browsers. https://on.cypress.io/launching-browsers#Customize-available-browsers

But yes, I agree this could be a better error message. 

Supported browser is actually a bit longer also:

```
Canary
Chrome
Chromium
Edge
Edge Beta
Edge Canary
Edge Dev
Electron
Firefox (Beta support)
Firefox Developer Edition (Beta support)
Firefox Nightly (Beta support)
```

**Comment by flozender** [comment]
Hi, I'd like to work on this!

**Comment by flozender** [comment]
One way to do it would be to add a conditional statement in ```packages/server/lib/errors.coffee```, in the ```    when "BROWSER_NOT_FOUND_BY_NAME"``` switch statement, and modify the error string accordingly for when ```safari``` is an argument. Please let me know if I am on the right track.
