### ISSUE TITLE
Factor in `pointer-events: none` on action commands and visibility algorithm

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#698]
Currently action commands do not factor in `pointer-events: none` on elements.

In the spec, this states that action events will "fall through" the element and trigger descendants. 

Additionally our visibility algorithm get's confused by this if the element is or belongs to a `position: fixed`.

When the browser calculates `document.elementFromPoint` if the element has `pointer-events: none` it will automatically return an element underneath it.

This causes the algorithm to fail in an unexpected way.

## Solution 1

Update `ensureReceivability` to account for `pointer-events: none` with a good error message.

## Solution 2

When calculating a fixed position element we should detect that it has `pointer-events: none` and flip this rule off temporarily and then flip it back on.

**Comment by Bkucera** [comment]
fixed in #3168 
Released in [`3.4.0`](https://on.cypress.io/changelog#3-4-0).

**Comment by mightyiam** [comment]
Any chance that this bug is re-appearing?

**Comment by mightyiam** [comment]
Specifically, in `be.visible`, if it has `pointer-events: none;`, Cypress claims it is `position: fixed;` and covered by what is below it (its parent).

**Comment by Bkucera** [comment]
@mightyiam this is possible. can you open an issue with a reproducible html + test code?

**Comment by mightyiam** [comment]
Possibly. Is there a template repo for reporting an issue such as this, please?

**Comment by Bkucera** [comment]
@mightyiam our new issue template will have all that info

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
