### ISSUE TITLE
Allow use of cy.* commands outside of tests/hooks to allow building a dynamic list of tests

### ISSUE THREAD

**Issue by snickell** [cypress-io/cypress#6982]
### Current behavior:

Dynamic tests cannot use familiar `cy` methods (such as `cy.get`, `cy.task`, etc) to determine the list of tests.

### Desired behavior:

Feature request: a mechanism to allow the use of `cy.*` commands when constructing a dynamic list of tests to execute.

A few example use cases enabled by this feature request:
1. Developer would like to parse a file on their filesystem generated by another tool to dynamically determine the suite of tests to run: e.g. 'every line of this XML file generated by my game compiler represents a different test case'
2. Developer would like to run an external UNIX command using `cy.task` to dynamically construct the set of tests.
3. Developer would like to inspect the DOM of a webapp using `cy.visit()`, `cy.get()`, etc to determine a dynamic set of tests to run: e.g. "visit this URL, make a list of buttons in the DOM, each button is a test, and we test it by sending a click event and looking for an error code", or e.g. "visit this URL which is a jupyterlab instance, load a notebook, every cell of the notebook should be treated as a test written by a datascientist, when the tests are run, run a snapshot of each cell and report inconsistencies".

I can see at least two possible "API" approaches to enabling this feature request, neither may be possible architecturally, but both seem sane from an API perspective:

1.  Permit late extending of the dynamic list of tests inside the `before()` handler
2. Permit the importing or use of (some?) cy.* commands inside the `context()` block

**Comment by jennifer-shehane** [comment]
This is *somewhat* possible. See https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests 

But yeah, currently running cypress commands outside of tests or hooks is not supported and would be a quite difficult challenge considering how it's architected today. I'm not sure if we can or will support this. Will have to check with the team.

**Comment by snickell** [comment]
Oh, I hadn't actually gotten far enough to encounter #3114 , very good point, that would indeed block this approach too.

**Comment by jennifer-shehane** [comment]
So, I reviewed this proposal with the team and basically - this will never be possible in Cypress. Cypress commands will always have to be run within a test/hook. So, working around this will require other means - like using other utilities other than cypress commands to generate dynamic tests.

So we will be closing this issue.
