### ISSUE TITLE
Environment Variables get cleared when I run cypress

### ISSUE THREAD

**Issue by Gbahdeyboh** [cypress-io/cypress#6985]
Before running my Cypress tests, I set some environment variables using the `export` command line code. I tried reading these variables using the `Cypress.env` command but it returns an empty string. I tried using process.env to read the environment variable and I get the same behavior. I'm able to ascertain that it returns an empty string by doing the following.
- Running `cy.log(Cypress.env('VARIABLE_USERNAME')`
- Closing Cypress via the console(`CTRL + c`) and running `echo $VARIABLE_NAME` to print out the environment variable I set before starting the test on the same console.
Both stated above returns an empty string.

## Code Example Causing this issue
`cypress/integration/test.spec.js`

```js
let Api = require('../myFolder/Api.js')
describe("Should ensure that user account is created", () => {
	let bot;
	before(async () => {
		cy.log("Variable name is ", process.env.VARIABLE_USERNAME);
		cy.log("Variable name 2 is", Cypress.env('VARIABLE_USERNAME'));
		bot = await Api.bot();
	})
})
```
`cypress/myFolder.Api.js` contains the following

```js
const MWBot = require( 'mwbot' );
module.exports = {
	async bot(
		username = Cypress.env("VARIABLE_NAME"'),
		password = Cypress.env('VARIABLE_PASSWORD'),
		baseUrl = Cypress.config().baseUrl
	) {
		const bot = new MWBot();

		await bot.loginGetEditToken( {
			apiUrl: `${baseUrl}/api.php`,
			username: username,
			password: password
		} );
		return bot;
	}
}
```

I get the error in the image below
![CypressError](https://res.cloudinary.com/gbahdeyboh/image/upload/v1586534652/cypressError_bfjpt4.png)

I would you like you to note the output of my Cy.log above which is an empty string as shown in the image.

**Comment by jennifer-shehane** [comment]
>Before running my Cypress tests, I set some environment variables using the export command line code.

Reading Cypress environment variables via `Cypress.env()` will only have variables that were set with the `CYPRESS_` prefix. These are special environment variables (different from your regular OS environment variables), so you'll need to set them with `CYPRESS_` prefix as outlined here: https://on.cypress.io/environment-variables#Option-3-CYPRESS

Any OS level environment variables will not be available in a spec file via `process.env` - these spec files are run within the context of the browser (just as any `process.env` would not be available to log from Chrome dev tools from within your web app)

If you want to read `process.env`, these values can be read from within your `plugins/index.js` or `support/index.js` files - which run within the context of Node.js. 

If you are setting an environment variable prefixes with `CYPRESS_` that is not being read later via `Cypress.env()`, please comment here with more detailed explanation of how this is being set and we will consider reopening.

**Comment by ShourryaGuha** [comment]
`import E2ePlatformService from "src/app/services/e2e/e2e-platform.service";
import * as dotenv from "dotenv";
import { TestPlatform } from "src/app/enums/TestPlatform";

// When a command from ./commands is ready to use, import with `import './commands'` syntax
// import './commands';

// tslint:disable-next-line: no-namespace
dotenv.config({ path: '.env.local' });
dotenv.config();

console.log('TEST PLATFORM = ', process.env.TEST_PLATFORM);`

This is what I have written in my support/index.ts file. It still does not output the correct environment value in the console.

`TEST_PLATFORM=cypress` is my .env file.

**Comment by dwhieb** [comment]
@ShourryaGuha any luck getting dotenv to work with Cypress? I'm struggling to get the two to work together. I'm loading dotenv in my Cypress config file, but the environment variables aren't getting loaded.
