### ISSUE TITLE
Feature request: .stop() command

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#6987]
Something similar to .pause() but instead of pausing the run, just make the test stop altogether. Might be useful if you need to run only part of test. Now you do it by commenting out the rest of the test.

Example:

```javascript
it('Should test a thing', () => {

  // gets executed
  cy
    .get('item')

  // similarly to .pause() is ignored in CLI 
  cy
    .stop()

  // test stops before this command, right now I need to comment this out If I want to run my test, but stop before this command
  cy
    .get('item2')

})
```

.pause() is good and all, but I cannot stop the test after it is paused, just continue or go to next step. .debug() turns on debugger, which is not the thing I necessarily need.

Alternatively, adding an option to stop run on .pause() might be sufficient 😄

**Comment by jennifer-shehane** [comment]
>.pause() is good and all, but I cannot stop the test after it is paused

What functionality do you get by 'stopping' the test as opposed to letting it sit there paused? What does 'stop' mean exactly? You want it to exit? 

Are you using this functionality via `cypress run` or `cypress open`?

**Comment by filiphric** [comment]
Stopping test instead can especially useful when you have a very long test and you only want to play only a part of it. For example I have a super-long e2e smoke test test that:

1. logs in
2. goes to dashboard
3. does couple of actions here and there
4. logs out

so let’s say that in latest update of our app, we added a checkbox to our application. that checkbox sends an additional http request during my test flow. I want to test the checkbox and the http request between step 1 and 2 and I want to add a couple of assertions there. 

While I’m writing the test, I want to stop my test between step 1 and 2, find my selector, check my http request and then only run the first part of test to make sure everything is ok. 

right now, if I wanted to do this, I would need to go to my text editor and comment out steps 2, 3 and 4 to run only the first part of the test. .pause() looks like something that could help me, unfortunately, I cannot use „time travelling“ feature of cypress runner e.g. If I want to examine the http request. Also, I cannot _stop_ the test, only resume it and stop it right after.

obviously, there are workarounds for this. It’s a „nice to have“ feature, but I think it makes sense. it seems that a big part of functionality is already there with the .pause() command. so I think adding a .stop() command or adding an option to stop test runner on .pause() could be an easy win.

I’m using `cypress open`  to answer your question.

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work.

We will be closing this issue, but keeping it open for comments. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by larryzoumas** [comment]
The alternative to a much-desired "stop" command is the need to constantly comment out sections of the spec code which is quite annoying.
