### ISSUE TITLE
Not possible to call cy.eq multiple times on a cy.get result

### ISSUE THREAD

**Issue by D0rmouse** [cypress-io/cypress#6989]
I'm using cucumber to assert a table using Cypress.  So it's basically a [matrix](https://www.youtube.com/watch?v=Brl7WmHDG-E) comparison.

I have to get the element using get every time to be able to use eq, while one time should be enough.
Performance is degraded having to fetch every row for every assert.

### Current behavior:

```js
const cyRows = cy.get('table tbody tr');
cyRows.eq(0).find('td'); //fails
cy.get('table tbody tr').eq(0).find('td') //succeeds
```

### Desired behavior:

```js
const cyRows = cy.get('table tbody tr');
cyRows.eq(0).find('td'); //succeeds
```

### Versions

"cypress": "^3.8.2"

**Comment by D0rmouse** [comment]
So what I did to try to increase the performance of this is the following. Assume that dataTableRaw is the Cucumber datatable.

```
const cyRows = cy.get('table tbody tr');
cyRows.should('have.length.of', dataTableRaw.length - 1);
const results = new Array;
cyRows.each((value) => {
  results.push(new Array);
    const latest = results[results.length - 1];
    cy.wrap(value).children('td').each((col) => {
        latest.push(cy.wrap(col));
    })
 }).then(() => {
    for (let row = 0; row < dataTableRaw.length - 1; row++) {
      for (let column = 0; column < dataTableRaw[row].length; column++) {
          results[row][column].should('contain', dataTableRaw[row + 1][column]);
      }
    }
 })
```
This code executed in 12.43s. Previous code in 18.44s. I'm unsatisfied by a 33% peformance increase🙄

**Comment by bahmutov** [comment]
How big is the table?

**Comment by D0rmouse** [comment]
7 rows, 5 columns.

**Comment by jennifer-shehane** [comment]
Please read our entire guide of variables and aliases. This won't work the way you think it will when assigning a variable to a Cypress chain in this way, you'll want to use `.as()` to alias the element. https://on.cypress.io/variables-and-aliases#Return-Values

```js
cy.get('table tbody tr').as('cyRows')
cy.get('@cyRows').eq(0).find('td')
cy.get('@cyRows').eq(0).find('td')
```

**Comment by D0rmouse** [comment]
@jennifer-shehane Thanks for pointing me to the aliases! :) 
```
cy.get('table tbody tr').as('cyRows').should('have.length.of', dataTableRaw.length - 1);
for (let row = 0; row < dataTableRaw.length; row++) {
    cy.get('@cyRows').eq(row).find('td').as('cyRowColumns');
    for (let column = 0; column < dataTableRaw[row].length; column++) {
        cy.get('@cyRowColumns').eq(column).should('contain', dataTableRaw[row][column]);
    }
}
```
