### ISSUE TITLE
Setting DEBUG=cypress:* or DEBUG=cypress:driver should launch the Cypress GUI in this debug mode

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#699]
Currently users have to do two separate steps to see debugging output. 

1. They have to run this from the command line to get output in stdout
2. Then they also have to run a separate command in their browser console to see it there.

We should fuse this together and automatically launch the driver in debug mode if this flag was set.

https://docs.cypress.io/guides/guides/debugging.html#Using-the-DevTools

**Comment by brian-mann** [comment]
Related to #448.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
