### ISSUE TITLE
Not able to click a certain element using Cypress

### ISSUE THREAD

**Issue by gitanshumalhotra** [cypress-io/cypress#6994]
I have multiple yFiles nodes in my UI with the same class name. Th only thing that differentiates these nodes is the text within them, which when inspected, is the text content of the many children of the node. Using Cypress, not able to figure out how to click the node with the particular text value. 

I have something like:

```html
<g class="**class1" **>
  <rect fill="#ffffff" stroke="stroke-width=" 1.5" width="170" height="50" rx="10" ry="10">
  </rect>
  <foreignObject>Something</foreginObject>
    <div text=somehing></div>
    //grandchild of the tag g // <text style="style1"> yFileNode1</text>
```

Now, I want to click on the `yFile` node that has the value "yFileNode1", meaning it should return me the node with class "class1". 

I tried with this: 
```js
cy.get('.class1').contains('yFileNode1').click({force:true});
```

but it doesnt seem to be working. Any ideas on how to approach this would be helpful. Thanks

**Comment by jennifer-shehane** [comment]
There is not enough information to reproduce the problem.

Please comment in this issue with complete, valid HTML. Currently the HTML provided is malformed when pasted into a `index.html` and tried to be tested against.

Can you also describe what the problem is? Is it failing at the `.contain()` or on the `.click()`? What is the error message within Cypress exactly?

**Comment by gitanshumalhotra** [comment]
Its not giving any error message, but its not able to select that node for which the value is yFileNode1

**Comment by gitanshumalhotra** [comment]
Figured the solution. So 
cy.get('.class1').contains('yFileNode1').click({force:true});
doesnt work for me, but this did:

cy.get('.class1:contains("yFileNode1")').click({force:true})

Whats the difference between the two?
