### ISSUE TITLE
stuck when installing mdbootstrap vue included cypress

### ISSUE THREAD

**Issue by fbryo** [cypress-io/cypress#6995]
### Current behavior: 

stuck when installing mdbootstrap vue included cypress

### Desired behavior: 

I'm installing on Visual Studio Code using integrated Bash terminal. I don't know from my internet or from program itself
![cypress problem](https://user-images.githubusercontent.com/36603375/79071387-a7b22580-7d05-11ea-8b95-e811a5abf9e1.PNG)

### Test code to reproduce: 

running `yarn install` or you can check your code, whether is a bug or not

**Comment by jennifer-shehane** [comment]
I don't actually see this output failing anywhere within installing Cypress. Please refer to the mdbootstrap vue project's documentation or support to see why their install is failing. This project is not maintained by Cypress.
