### ISSUE TITLE
append (failed) to video filenames when test fails

### ISSUE THREAD

**Issue by dnaverdo** [cypress-io/cypress#6998]
### Current behavior: 

Video files do not indicate if the screenshot is a failing test like screenshots do.

### Desired behavior: 

The videos that are taken during failure are named the same name as the test it failed within with ` (failed)` appended to the filename, so you can detect the ones during failure. This PR added the (failed) functionality for screenshots: https://github.com/cypress-io/cypress/pull/1858

### Test code to reproduce

1. fail a test that has screenshots and videos
2. observe filenames of video and screenshot

### Versions

all

**Comment by jennifer-shehane** [comment]
We've had some discussion about this feature request and feel that this would be better served under the larger feature requested in https://github.com/cypress-io/cypress/issues/2522

Our thinking being that people essentially want to not save the non-passing test videos, which could be achieved in #2522 as opposed to just adding a string to the video and still leaving it up to people to implement the deletion. 

Appending the `(failed)` string may still be part of that larger work - we haven't decided, so opinions are welcome if you'd like to comment within here or in #2522.
