### ISSUE TITLE
cy.wait expects responses to return in the exact same order as requested.

### ISSUE THREAD

**Issue by vizjerai** [cypress-io/cypress#6999]
### Current behavior:

If first xhr request returns before the second request the test will pass
If first xhr request returns after the second request the test will fail with a time out for `@getTest`

### Desired behavior:

The test to pass and for the xhr requests to wait for the correct xhr requests.

### Test code to reproduce

```js
beforeEach(() => {
  cy.server();
  cy.route('GET', '/test').as('getTest');
});

it('should always pass', () => {
  cy.visit('/'); // page will GET 2 requests for /test

  cy.wait('@getTest'); // hooks to the first xhr request
  cy.wait('@getTest'); // hooks to the second xhr request

  // cy.wait(['@getTest', '@getTest']); // this will result in the same thing.
});
```

### Versions

Tested on Cypress 3.8.3 and 4.0.3 using `cypress open`
operating system: OSX 10.14.6
browser: Chrome 80

**Comment by jennifer-shehane** [comment]
`cy.wait()` will wait for the first matching request that comes through - in this case *any* GET request that has the `/test` url. 

I'm not sure how you're defining 1st versus 2nd here - because they are the exact same matcher for both. Cypress will simply resolve the wait if a request came through that matched GET `/test`, it has no concept of which should be 1st or 2nd in this case - it just looks for anything that matches. 

Are the urls of the XHR request exactly the same?

**Comment by vizjerai** [comment]
In the actual code they are nearly identical, but the `cy.route()` we are using matches for both. For example `/test/1/foo` and `/test/2/foo`. We don't have the ability to know what those numbers are before the requests end up being triggered. There is an initial request that returns with some results that will trigger additional xhr requests with those ids.

**Comment by jennifer-shehane** [comment]
If the initial results contain the info for the subsequent requests, then you can get that data from the XHR response and use that to generate new `cy.wait()` commands building the route matchers. 

If you can't give the exact matchers, Cypress will work as I described above. There's not really any other way for Cypress to know what you want 1st, 2nd, etc.

**Comment by vizjerai-vineti** [comment]
This looks like the same issue as #5999 after looking through the comments.
