### ISSUE TITLE
Typescript support: support / load user defined tsconfig.json for transpiling files

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#7006]
### Current behavior:
index.spec.ts

```ts
import { forward } from '@apps/commons-e2e';
```

Fails with

> Error: Cannot find module '@apps/commons-e2e' from 'e2e\src\integration'

### Desired behavior:
`ts-node` should load an user defined `tsconfig.json` to find own path mappings.

### Test code to reproduce
1. create a `tsconfig.json` with a path mapping to a lib
1. create a spec file using this path mapping
1. run cypress

### Versions
4.4.0

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-150) by [Unito](https://www.unito.io/learn-more)

**Comment by maxime1992** [comment]
I just tried to upgrade to 4.4.0 and ended up with the same error.

Everything was working just fine with that version but if I try to take advantage of the [new feature](https://github.com/cypress-io/cypress/releases/tag/v4.4.0):

> TypeScript test files are now supported without using special preprocessors plugins. Addresses #1859.

To have it working previously I had to do the following:

```ts
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  resolve: {
    extensions: ['.ts', '.js'],
    plugins: [
      new TsconfigPathsPlugin({
        configFile: './tsconfig.json',
      }),
    ],
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'ts-loader',
            options: {
              configFile: 'tsconfig.e2e.json',
            },
          },
        ],
      },
    ],
  },
};
```

**Comment by kpittman-securus** [comment]
I am having trouble with 4.4.0 and TypeScript files also. When I run a build with my own `tsconfig.json` and then use the generated `*.spec.js` files for my specs, Cypress works fine.

When I run Cypress against all of my `*.spec.ts` files, 90% of them work fine, but 10% give cryptic error messages about `Unexpected Token`s.

I say "cryptic" messages because A. the TS files compile just fine on their own, and B. the error message points to a line:column number that makes no sense (issue with not having sourcemaps maybe?)

```
Oops...we found an error preparing this test file:

  C:\path\to\my.spec.ts
 
The error was:
 
Error: Parsing file C:\path\to\my.helper.ts: Unexpected token (55:12)  

 
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:
 
- A missing file or dependency
- A syntax error in the file or one of its dependencies
 
Fix the error in your code and re-run your tests.
```

When I look at `my.helper.ts` line 55 is something like this:
``` typescript
export function myFunction(s: string) {
           ^ this is char 12 where Cypress says there is an error
```

**Comment by bahmutov** [comment]
Reproducible test case in https://github.com/cypress-io/cypress-test-tiny/tree/test-path-ts

**Comment by kpittman-securus** [comment]
@jennifer-shehane any update on the status for this one?

**Comment by RocketPuppy** [comment]
I'm on Cypress 4.7.0 and running into something that looks remarkably similar to this. I'm seeing cryptic syntax errors on line:columns that make no sense (in my case, they are empty lines).

**Comment by csalazar1** [comment]
Hoping this gets picked up soon. We are trying to move to typescript and eliminate relative path hell

**Comment by eric-burel** [comment]
Good, I am not alone. I can reproduce this issue only in my Docker image, using `cypress/base:11`, while tests work fine locally without even specifying the `configFile` of ts-loader.
