### ISSUE TITLE
Proposal: SauceLabs Support

### ISSUE THREAD

**Issue by estefafdez** [cypress-io/cypress#7008]
### Objective:

Add support for running Cypress tests on external cloud tests provider such as Saucelabs. 

Saucelabs is a tool we use a lot to be able to launch tests on different browsers and Operative Systems. It gives you the freedom to run tests (even in parallel) on different browsers and operatives systems and you can choose the combination you needed, even the screen resolution you want to test on. 

It will be absolutely GREAT to be able to have support from you guys to be able to launch my cypress test there. 

Thanks!

**Comment by CSchulz** [comment]
> A note about Cypress and Sauce Labs
> Cypress’ API is written to be completely compatible for integration with Sauce Labs. It is our goal to offer full integration with Sauce Labs in the future; however, complete integration is not yet available.

https://docs.cypress.io/faq/questions/general-questions-faq.html#Sauce-Labs

No hint on the roadmap:

https://docs.cypress.io/guides/references/roadmap.html#Upcoming-features

**Comment by estefafdez** [comment]
Any idea when this future could be? or how to add it into the roadmap? thanks @CSchulz!

**Comment by jennifer-shehane** [comment]
There has been no work done on SauceLabs support, although I know we've internally had discussion on this in the past. We do not have an estimate on when this would be delivered.

**Comment by jennifer-shehane** [comment]
Closing since there hasn’t been a lot of interest for this over the years.
