### ISSUE TITLE
Block cookies from being set

### ISSUE THREAD

**Issue by tvthatsme** [cypress-io/cypress#7015]
### Current behavior:

In the [documentation for cookies](https://on.cypress.io/cookies), the `Cypress.Cookies.defaults` method is provided to "enable you to control Cypress’ cookie behavior".

This method's interface is:
```js
interface CookieDefaults {
  whitelist: string | string[] | RegExp | ((cookie: any) => boolean)
}
```

What I'm missing in this defaults option is some way to tell Cypress to block cookies from being set at all. Imagine for example, that you want your application to behave differently depending on the user's browser security settings.

### Desired behavior:

An additional parameter option to block cookies being set in the application.

```js
interface CookieDefaults {
  whitelist: string | string[] | RegExp | ((cookie: any) => boolean)
  blockAllCookies: boolean
}
```

It should change the value of `navigator.cookieEnabled`

### Test code to reproduce

N/A

### Versions

N/A

**Comment by jennifer-shehane** [comment]
Hey @tvthatsme, you can already test this by using [`cy.stub()`](https://on.cypress.io/stub) to stub what the `navigator.cookieEnabled` returns. 

`index.html`

```html
<html>
<body>
    <div id="message"><div>
</body>
<script>
    if (navigator.cookieEnabled === false) {
       document.getElementById("message").innerHTML = "Error: cookies not enabled!"
    } else {
       document.getElementById("message").innerHTML = "Yay! cookies are enabled!"
    }
</script>
</html>
```

`spec.js`

```js
it('cookies are disabled for user', () => {
  cy.visit('index.html', {
    onBeforeLoad(win) {
      cy.stub(win.navigator, 'cookieEnabled', false).as('cookieEnabled')
    },
  })

  cy.get('#message').should('contain', 'Error: cookies not enabled!')
})

it('cookies are enabled for user', () => {
  cy.visit('index.html')

  cy.get('#message').should('contain', 'Yay! cookies are enabled!')
})
```

**Comment by jennifer-shehane** [comment]
Been thinking since writing this that this doesn't actually block the cookies, but...it is a way to test your implementation and how it responds to this being enabled/disabled.

**Comment by tvthatsme** [comment]
Hmm yeah thats true. That becomes more of a test of the actual implementation rather than the experience of a user blocking all cookies. But this will work for now I guess! Thanks for the idea about subbing and the example. 😄I had overlooked that idea!

**Comment by rcowsill** [comment]
This workaround is great for testing sites that rely solely on navigator.cookieEnabled to tell whether they can set cookies.

Unfortunately navigator.cookieEnabled is broken in Firefox <8 and IE6-11; it returns true even if cookies are blocked by security settings. For that reason people often test for cookie support by setting and getting a cookie in JS (see https://stackoverflow.com/a/15582757 for more on this)

To test such sites there really needs to be a way to block cookies as if the user changed their browser settings.
