### ISSUE TITLE
Command Log doesn't show all XHR requests and can't catch them

### ISSUE THREAD

**Issue by andrey11231990** [cypress-io/cypress#7017]
### Current behavior:
I can't 'catch' requests to BE with Cypress. And even more, I can't see some XHR requests to BE, but they are in DevTools. I've added a screenshot with arrows to describe the problem better.
![image](https://user-images.githubusercontent.com/4784857/79369523-c6105f00-7f59-11ea-974a-49ba230c3568.png)

### Desired behavior:
I would like to be able to spy on all the routes and be able to stub them.

### Test code to reproduce

I can't upload my project to the public repo, but maybe you can get some ideas based on the test itself. I don't have any beforeEach, etc. 

```js
it('should generate the right request for password change', () => {
    cy.visit(`/courses/reset-password?token=${token}&userId=${userId}`);
    cy.server();
    cy.route('POST', '/auth/local/reset-password').as('resetRequest');
    // cy.route({
    //   method: 'POST',
    //   url: '/auth/local/reset-password',
    // }).as('resetRequest');
    cy.get('#password').type(password);
    cy.get('#confirmPassword').type(password);
    cy.get('button[type="submit"]').click();
    console.log('at the end');
    cy.wait('@resetRequest').then((request) => {
// never got here
      console.log('fff', request);
      console.log('requestBody', request.requestBody);
      expect(request.body.newPassword).to.eq(password);
      expect(request.body.token).to.eq(token);
      expect(request.body.userId).to.eq(userId);
    });
  });
```

**Comment by jennifer-shehane** [comment]
I can't see any obvious reasons why this shouldn't work. You're sure the `reset-password` POST is requesting and responding within 5 seconds?

**Comment by andrey11231990** [comment]
yes, it is.
and it doesn't log any xhr requests on any page. I just tried to make tests for another page - and I still can't find any XHR requests in my Command Log.

I think I will try to reinstall Cypress. Will let you know later

**Comment by andrey11231990** [comment]
@jennifer-shehane is there a way to spy for a 'fetch', not XHR ?

after reinstallation, I understood, that I'm doing to a simple XHR, but fetch request

**Comment by andrey11231990** [comment]
I've found a solution. You can find it by the [link](https://stackoverflow.com/questions/61235428/cypress-dont-see-requests-in-command-log)

hope it will be useful
