### ISSUE TITLE
Extra css spacing below Desktop GUI menu

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7023]
### Current behavior:

There's some extra css spacing below the menu

<img width="349" alt="Screen Shot 2020-04-15 at 10 18 01 PM" src="https://user-images.githubusercontent.com/1271364/79419489-e8978c00-7fdc-11ea-94c9-d87f2394d2fd.png">

### Desired behavior:

Menu shouldn't have extra spacing below.

### Versions

4.4.0

**Comment by chrisbreiding** [comment]
Re-opening because I realized I undertested the work I did on this and broke more than I fixed. So much so a gif is needed to show it 😓

![desktop-gui-css-issues](https://user-images.githubusercontent.com/1157043/79577932-8188de80-8093-11ea-88ed-56d9fd4bde84.gif)

I'll open a new PR with fixes.

**Comment by jennifer-shehane** [comment]
Sorry, I should have retested your changes. 😞
