### ISSUE TITLE
Sample or Simple cypress scripts not opening in Electron 80, Chrome 81

### ISSUE THREAD

**Issue by santhoshbk24** [cypress-io/cypress#7025]
### Current behavior:

1. Selected the Electron 80 - Address bar not shown, Page displayed blank
2. Chrome - Address bar displayed blank, Chrome controlled by Automated test software message displayed. Page displayed blank

### Desired behavior:

Entered URL not opened

### Test code to reproduce

```js
  describe('My First test Suite', function()
  {
      it('My First Test case', function() {
          cy.visit('https://google.com');
      })

  })
```

```
←[0mGET /__/ ←[32m200 ←[0m39.803 ms - -←[0m
←[0mGET /__cypress/runner/cypress_runner.css ←[32m200 ←[0m9.426 ms - -←[0m
←[0mGET /__cypress/runner/cypress_runner.js ←[32m200 ←[0m1.614 ms - -←[0m
```

### Versions

Windows 7 Prof
Google Chrome-Version 81.0.4044.113 (Official Build) (64-bit)
Cypress package version: 4.4.0
Cypress binary version: 4.4.0

**Comment by jennifer-shehane** [comment]
Can you provide a screenshot so we can tell exactly what you mean by 'page displays blank'. 

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by santhoshbk24** [comment]
C:\Users\IndiaPC_Test_01>node -v
v12.16.2
Terminal:
IndiaPC_Test_01@IndiaPC_TestTL MINGW64 /d/Cypress/CypressAutomation
$ node -v
v12.16.2
----------------------------------------------------------------------------------------
//Debug
C:\Program Files\nodejs\node.exe cypress\integration\examples\Test1.js
d:\Cypress\CypressAutomation\cypress\integration\examples\Test1.js:1
describe('My First Test', () => {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (d:\Cypress\CypressAutomation\cypress\integration\examples\Test1.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

--------------------------------------------------------------------------------------------
Step1: Installed the node.js
Step2: Given global node.js path
Step3: Created the Folder
Step4: Visual studio code -  opened the blank folder
Step5:Open the Terminal
Step6:npm install cypress --save-dev
Step7:Created the file and written below code
describe('My First Test', () => {
    it('Visits the Kitchen Sink', () => {
      cy.visit('https://example.cypress.io')
    })
  })
----------------------------------or 
  /// <reference types="cypress" />
  describe('My First Test Suite', function() 
  {
      it('My First Test case', function() {
          cy.visit("https://google.com")
          
      })

  })
-------------------------------------------------
Step8: terminal $node_modules/.bin/cypress open
Step9: Selected Electron 80 / Chrome Browser
Step10: Click on file
Step11: Blank Electron 80 browser opened


![IMG_20200417_234028](https://user-images.githubusercontent.com/59028194/79600611-0cee8800-8105-11ea-84a4-39fa26da4822.jpg)


--------------------------------------------------------
