### ISSUE TITLE
Showing spinner only and won't run

### ISSUE THREAD

**Issue by marinsagovac** [cypress-io/cypress#7027]
After run on Ubuntu 18.04 LTS Cypress show spinners only and won't start. Previous projects a few days ago worked fine.

### Current behavior:

After Cypress run it will open Cypress with spinner and after 5 min it is still on spinner. Checked on ver 4.4, 4.3 and 4.2. Same result.

Full log: https://pastebin.com/raw/ijzm38Rv

Ubuntu 19.04 LTS

### Desired behavior:

Run electron based cypress app to show fixtures and browser.

### Test code to reproduce
Run `node_modules/bin/cypress` open and shows spinners only without possibility to choose fixtuers of tests or browser version.

### Versions

Chromium (/usr/bin/chromium)

**Comment by marinsagovac** [comment]
Resolved by removing Chromium from snapd and apt.

**Comment by rdar-lab** [comment]
The issue happens again when using node version 17.x
The following message will show "--openssl-legacy-provider is not allowed"

Workaround: downgrade node to version 16,x
