### ISSUE TITLE
cy.task promise not resolving

### ISSUE THREAD

**Issue by rcaunt** [cypress-io/cypress#7029]
### Current behavior:

Our application consists of a data upload and processing pipeline.  We have a requirement to write a test that uploads the maximum file size that our system can handle and ensures that it processes etc. in a certain time.

The file we load is 200MB in size and is a CSV file consisting of ~230000 lines.

We utilise `cy.task()` to call into Node and then use a `Promise` to load the file into an array (one entry per line), once loaded it resolves the Promise.  With logging in that function we can see that it executes and loads the file almost instantly.

In our Cypress test in the `then()`, the first thing we do is to log that the file has been loaded.  This line is never being logged and the rest of the Cypress test is never processing.  No timeout is occurring at this stage.

This is our (simplified) `cy.task`:

```js
readTextFile (filename) {
      const fullFilePath = path.resolve('cypress', 'fixtures', filename)

      console.log(`Loading file: ${fullFilePath}`)

      return new Promise((resolve) => {
        countFileLines(fullFilePath)
          .then((lines) => {
            console.log('Loading file into array, lines:', lines)

            let data = Array(lines)
            let idx = 0
            
            lineReader.eachLine(fullFilePath, function(line, last) {
                data[idx++] = line + '\n'; 
                
                if (last) {
                  console.log('File loaded, array size', data.length)
                  resolve(data)
                }
            })
          })
      })
    },
```

This is how we call cy.task:

```js
const fileName = getFileName()

  cy.task('readTextFile', fileName, { timeout: 1200000 })
    .then({ timeout: 1200000 }, (fileContent) => {
      console.log('File loaded')

      //...

      const file = new File(fileContent, fileName, { type: 'text/csv' })

      //...
    })
```

With debugging enabled I get this log:

```
  cypress:server:plugins:child execute plugin event: task ({ eventId: 3, invocationId: 'inv78' }) +23s
  cypress:server:task run task readTextFile with arg FILE.csv +0ms
  cypress:server:plugins plugin event registered? { event: 'task', isRegistered: true } +23s
  cypress:server:plugins execute plugin event 'task' Node 'v12.13.0' with args: 'readTextFile' 'FILE.csv' undefined +0ms
  cypress:server:plugins call event task for invocation id inv78 +0ms
Loading file: X:\cypress\fixtures\FILE.csv
File size 203926062
Loading file into array, lines: 229853
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51807 } +3s
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51810 } +0ms
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51809 } +108ms
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51808 } +4ms
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51805 } +11ms
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51806 } +1ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────┬──────────────┬──────────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │   group   │ processCount │                           pids                           │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────┼──────────────┼──────────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'Chrome'  │      7       │ '14212, 7788, 7440, 10552, 6932, 15160 ... 1 more items' │   15.73    │      6.23      │  461.88  │    372.46    │   461.88    │
  cypress:server:util:process_profiler │    1    │ 'cypress' │      1       │                         '11948'                          │    9.22    │      5.62      │  179.84  │    156.02    │   179.84    │
  cypress:server:util:process_profiler │    2    │ 'plugin'  │      1       │                         '14628'                          │   16.67    │     19.69      │  138.49  │    140.26    │   162.55    │
  cypress:server:util:process_profiler │    3    │  'other'  │      5       │            '7008, 14948, 13400, 14828, 2440'             │     0      │       0        │  70.04   │    58.13     │    70.1     │
  cypress:server:util:process_profiler │    4    │  'TOTAL'  │      14      │                           '-'                            │   41.62    │     25.06      │  850.25  │    598.69    │   850.25    │
  cypress:server:util:process_profiler └─────────┴───────────┴──────────────┴──────────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +11s
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51851 } +2s
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51853 } +419ms
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51852 } +3ms
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51854 } +4ms
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51749 } +1ms
File loaded, array size 229853
  cypress:server:plugins promise resolved for id 'inv78' with value [
  ... 229753 more items
] +19s
  cypress:server:task result is: [
  ... 229753 more items
] +13s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────┬──────────────┬──────────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │   group   │ processCount │                           pids                           │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────┼──────────────┼──────────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'plugin'  │      1       │                         '14628'                          │   16.23    │     18.82      │  1956.8  │    594.39    │   1956.8    │
  cypress:server:util:process_profiler │    1    │ 'cypress' │      1       │                         '11948'                          │   11.56    │      6.81      │ 1419.82  │    408.78    │   1419.82   │
  cypress:server:util:process_profiler │    2    │ 'Chrome'  │      8       │ '14212, 7788, 7440, 10552, 6932, 15160 ... 2 more items' │    7.91    │      6.65      │  372.56  │    372.49    │   461.88    │
  cypress:server:util:process_profiler │    3    │  'other'  │      5       │            '7008, 14948, 14664, 13364, 15124'            │    0.03    │      0.01      │  70.15   │    60.53     │    70.15    │
  cypress:server:util:process_profiler │    4    │  'TOTAL'  │      15      │                           '-'                            │   35.73    │     27.19      │ 3819.33  │   1242.82    │   3819.33   │
  cypress:server:util:process_profiler └─────────┴───────────┴──────────────┴──────────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +13s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────┬──────────────┬──────────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │   group   │ processCount │                           pids                           │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────┼──────────────┼──────────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'plugin'  │      1       │                         '14628'                          │     0      │     15.06      │  1956.8  │    866.87    │   1956.8    │
  cypress:server:util:process_profiler │    1    │ 'cypress' │      1       │                         '11948'                          │   27.34    │     10.23      │  807.63  │    475.25    │   1419.82   │
  cypress:server:util:process_profiler │    2    │ 'Chrome'  │      7       │ '14212, 7788, 7440, 10552, 6932, 15160 ... 1 more items' │    4.66    │      6.25      │  357.44  │    369.48    │   461.88    │
  cypress:server:util:process_profiler │    3    │  'other'  │      5       │            '7008, 14948, 14652, 7384, 15056'             │     0      │      0.01      │  70.14   │    62.14     │    70.15    │
  cypress:server:util:process_profiler │    4    │  'TOTAL'  │      14      │                           '-'                            │     32     │     27.99      │   3192   │   1567.68    │   3819.33   │
  cypress:server:util:process_profiler └─────────┴───────────┴──────────────┴──────────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +11s
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51760 } +27s
  cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 51762 } +95ms
```

As you can see, it logs the result from the promise resolving but nothing afterwards.

With a fresh reboot of my computer I can usually get the Promise to resolve OK but not after that.  I have tried:

`NODE_OPTIONS=--max-old-space-size=8192`

With no luck either.

### Desired behavior:

The Promise to always resolve and the test to continue.

### Test code to reproduce

Currently not available

### Versions

Node 12.14.1
Cypress - 4.3.0
Chrome - 80
Windows 10

**Comment by jennifer-shehane** [comment]
Yeah, this may resolve around the sheer amount of data you're trying to iterate over.

Can you provide an example that we can run locally on our machines? There's a lot of code in here that was not provided so we can't run the provided code as is. 

Are you running this via `cypress run` or `cypress open`? What happens when you run it via `cypress open`, does the Chrome browser lock up?

**Comment by rcaunt** [comment]
Thanks for the reply @jennifer-shehane 

I will look to put together a simple solution that replicates this issue.

We are having the issue with both cypress run and open, with it in CI and not-CI.  Typically Chrome continues to respond and eventually Cypress will fail with the timeout that we have set.

**Comment by shivasrini** [comment]
I am also having the same issue that @rcaunt has reported. I have created a task that uses node-fetch to pull data from an email server. It polls the server until the response is not empty and then resolves the response but my test keeps failing saying the task timed out even though my console log says the task resolved its promise. Mailsac has a free API that you can use to recreate this issue if you want. Here is how my task code looks 

`function getEmail(
    emailId,
    retriesLeft = 2,
    interval = 3000
) {
    return new Promise((resolve, reject) => {
        console.log('Retry attempt number ', retriesLeft);
        fetch(
            `https://mailsac.com/api/addresses/${emailId}/messages?_mailsacKey=${apiKey}`
        )
            .then((response) => {
                console.log('Response obtained ', response);
                if (response.ok) {
                    console.log('Response was good');
                    response.json().then((parsedResponse) => {
                        console.log('Parsed response is ', { parsedResponse });
                        if (parsedResponse && !isEmptyObject(parsedResponse)) {
                            console.log('Body has data return it');
                            resolve(parsedResponse);
                        } else {
                            console.log('Response was good but body was empty');
                            setTimeout(() => {
                                getEmail(
                                    emailId,
                                    retriesLeft - 1,
                                    interval
                                );
                            }, interval);
                        }
                    });
                }
            })
            .catch((error) => {
                console.log('Fetch failed. Bad response. Try again');
                console.log(error);
                setTimeout(() => {
                    if (retriesLeft === 1) {
                        reject('Maximum retries exceeded', error);
                        return;
                    }
                    getEmail(emailId, retriesLeft - 1, interval).then(
                        resolve,
                        reject
                    );
                }, interval);
            });
    });`


And this is how I am calling it in the test 

`cy.task('getEmail', 'emailxxx@mailsac.com').then(
                (body) => {
                    console.log('I called retriever');
                    console.log(body);
                    cy.log(body);
                }
            );`

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
