### ISSUE TITLE
Cypress is opened with infinitelly throbber after the environment variable was added

### ISSUE THREAD

**Issue by Nadya913** [cypress-io/cypress#7030]
### Current behavior:

Cypress open and throbber appears infinitely. Before it, I added the CYPRESS_BRANCH environment variable to system ubuntu 18.04 and after it can't be open or run.
![cypress_throbber](https://user-images.githubusercontent.com/33111683/79435753-3ec6f800-7ffa-11ea-9a55-b3e0e655f453.png)

### Desired behavior:

Cypress GUI is opened.

### Test code to reproduce
export CYPRESS_BRANCH=develop
try to open cypress 

### Versions

Ubuntu 18.04.4 LTS
cypress 3.4.0, 4.4.0

**Comment by Nadya913** [comment]
I unset the variable but still doesn't work.

**Comment by LaurensBosscher** [comment]
I've got the same issue on Ubuntu 18.04 after upgrading to 4.4. 

I've ran ```yarn cypress cache clear```

**Comment by Nadya913** [comment]
I have the same issue in 
![cypress 3 4 0](https://user-images.githubusercontent.com/33111683/79440011-b6e3ec80-7fff-11ea-81be-c6a0b43253be.png)

**Comment by marinsagovac** [comment]
Similar here: https://github.com/cypress-io/cypress/issues/7027

Just removed chromium and works. Don't know what happens and many others are reported that issues.

**Comment by LaurensBosscher** [comment]
It seems that this is somehow linked to a chromium update. Removing chromium does seem to fix it.

**Comment by Nadya913** [comment]
@marinsagovac thank you, I removed chromium and it was fixed
