### ISSUE TITLE
Cypress in every second it block it is navigating to Login page

### ISSUE THREAD

**Issue by ajinkya26** [cypress-io/cypress#7033]
Hi all, 
I am new to Cypress I have 10 "it" blocks after the execution of first "it" block it is navigating to the second "it" block and in second it blocks after clicking on button it reloads the page and navigates to the login page. I have checked in test runner API as well always it is calling Login method, manually it's working fine and I have written my "login" method in before file only and I have tried several ways but couldn't find the appropriate solution.
Please help me
Thanks

**Comment by jennifer-shehane** [comment]
Cypress clears cookies and localStorage in between tests. This is a pure guess, but it may be that the cookies and localStorage are being cleared, so rerouting you back to login. You may want to whitelist the cookies to have them persist across tests: https://on.cypress.io/cookies#Set-global-default-cookies

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue.
